### ISSUE TITLE
RViz cannot display the STL format model file in the noetic version of ROS under Ubuntu20.04

### ISSUE THREAD

**Issue by PiBigStar5712** [microsoft/WSL#10002]
### Windows Version

Windows 10 Home 22H2  Insider: 19045.2006

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu20.04.5 LTS

### Other Software

Nvidia-smi = 530.41.03
CUDA Version = 11.7
OpneGL under WSL use D3D12 = 3.1 Mesa 21.2.6
GLSL =1.4
ROS = noetic 1.16.0
RViz = 1.14.20

### Repro Steps

1. Install Ubuntu20.04

2. wsl --set-default-version 2

3. Install the xfce4 GUI

4. sudo apt install ros-noetic-desktop-full

5. Run RViz and import the STL model into it

### Expected Behavior

In the case of using D3D12 as the renderer of OpenGL, I used my GPU for the rendering task and achieved the following effects:

![image](https://user-images.githubusercontent.com/102813129/233319250-70d55da5-2e92-41b4-9470-1b1fd86bbeba.png)

### My question:
**1.Is there a way I can use GPU-accelerated OpenGL to render STL models in RViz without upgrading Ubuntu branch or Windows?**
**2.If so, do I need to upgrade OpenGL? What should I do if I need to upgrade? (I have tried to upgrade OpenGL using `sudo add-apt-repository ppa:kisak/kisak-mesa` and `sudo apt update && sudo apt upgrade`)**

### Actual Behavior

![image](https://user-images.githubusercontent.com/102813129/233315488-a584adf3-20ce-43e9-b11b-10d7f5f7bdb7.png)

**When I used the default D3D12 as the renderer for OpenGL, it ran as follows：**

![image](https://user-images.githubusercontent.com/102813129/233315234-046d6c68-2e83-4383-ac30-b04b70cf3289.png)

**The STL model is not visualized, and no errors are reported.**
**According to ros-visualization/rviz#1748, this problem should be caused by D3D12 and can be resolved by modifying D3D12 to llvmpipe. The modified result is as follows:**

When I type `export LIBGL_ALWAYS_SOFTWARE=true in the terminal`

![image](https://user-images.githubusercontent.com/102813129/233318773-0e377235-50b2-497d-857f-35da2ca82b4b.png)

**At this point, I run the previous code again, and the result is as follows：**

![image](https://user-images.githubusercontent.com/102813129/233319213-08dd6dae-6fa7-4701-8008-c8c1f836fbf4.png)

**Although RViz can render STL models normally, this function is achieved through the CPU. This results in a very low framerate, which is not what I want. After all, the competitiveness of WSL is that I can use my GPU without reservation.**

**Comment by OneBlue** [comment]
Thanks for reporting this @PiBigStar5712. 

@iourit: Can you help diagnosing the issue ?
