### ISSUE TITLE
Launching Ubuntu 20.04 LTS... The group or resource is not in the correct state to perform the requested operation.

### ISSUE THREAD

**Issue by foochin** [microsoft/WSL#10003]
Hi, I've been trying to install Ubuntu-20.04 on my PC.
![image](https://user-images.githubusercontent.com/131353818/233327723-d5cee209-90cc-45c1-bfd2-7ea20a7fdd08.png)

I've just updated my WSL2 kernel, issue still persist

Here is the log:

[WslLogs-2023-04-20_10-38-58.zip](https://github.com/microsoft/WSL/files/11284767/WslLogs-2023-04-20_10-38-58.zip)

**Comment by benhillis** [comment]
Unfortunately your trace doesn't have any. Could you please take another trace?

1. Begin tracing
2. Repro issue
3. End tracing
/logs

**Comment by foochin** [comment]
it appears that running `wsl --install -d Ubuntu-20.04 --web-download`
in Administrator Power Shell gives me:
`Launching Ubuntu 20.04 LTS...
The group or resource is not in the correct state to perform the requested operation.
Error code: Wsl/InstallDistro/0x8007139f`

but in a standard Power Shell, it gives:
`WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.`

**Comment by foochin** [comment]
I think I understood the issue now:
When running on standard PowerShell:
Virtual Machine Platform was not turned on. 
Once turned on, rebooted, and I was able to complete `wsl --install -d Ubuntu-20.04 --web-download`

When running on elevated PowerShell: 
Network access is disabled by the company, hence unable to unpack the downloaded package
