### ISSUE TITLE
[WSL2] Accessing files from \\wsl.localhost sometimes slow/hangs/disappears?

### ISSUE THREAD

**Issue by ForbiddenEra** [microsoft/WSL#10007]
### Windows Version

Microsoft Windows [Version 10.0.19045.2846]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop Windows Version 4.18.0 (104112)
  Engine: 20.10.24
  Compose: v2.17.2
  Credential Helper: v0.7.0
  Kubernetes: v1.25.4

### Repro Steps

Access/write any files on \\wsl.localhost\Ubuntu\*

### Expected Behavior

No issues; worked perfectly on WSL1

### Actual Behavior

Using Sublime text as IDE as always, sometimes it acts as if it's a network mount on a bad connection.

Sublime refreshes the file when it receives focus, sometimes it's like the filesystem has gone away and it thinks the files been deleted.

Same with saving on occasion, instead of just saving/overwriting, it pops up the save dialog as if the file doesn't already exist although generally the file is there because by then it's done glitching.

Sometimes saving as well just takes like 30 seconds or so..

Again, all these are behaviors you'd expect on a network mount that has a high latency/unstable connection - not something local.

I recently upgraded to WSL2 in order to be able to run Docker stuff; it was fine before this - it always responded/acted as if I was accessing files on a local filesystem.

It's not even occasional, it's nearly constant and insanely aggravating to the point I'm considering alternatives like SSHFS into the WSL instance, using Multipass or throwing another VM on my Xen box, heck, even a remote VM would be faster.

I'm creating thread because everything else I search about this results in people complaining about the opposite problem, that accessing files on their local NTFS drive FROM the WSL instance is slow; I'm not doing this at all.

**Comment by OneBlue** [comment]
Thanks for reporting this @ForbiddenEra. Unfortunately this is a consequence of how WSL2 works. When a requests comes throw \\wsl.localhost, the WSL2 vm needs to be started, which can take a bit of time and appear like a "slow connection".

If you think that this happens while the VM is running, you can collect /logs and share them here

**Comment by kosi2801** [comment]
This sounds similar to the issue #9504 that I opened in January. 

Does your slowness-experience change depending on the file if it has been opened in the same session just right before or if it has "simple" or "complex" content. 
eg. does the handling behavior change if the file just has a "A" character in it or consists of a much longer part of text (eg sourcecode)?

**Comment by ForbiddenEra** [comment]
> Thanks for reporting this @ForbiddenEra. Unfortunately this is a consequence of how WSL2 works. When a requests comes throw \wsl.localhost, the WSL2 vm needs to be started, which can take a bit of time and appear like a "slow connection".
> 
> If you think that this happens while the VM is running, you can collect /logs and share them here

Of course the VM is still running; what good would the comparison of SSHFS be if it wasn't?

I literally haven't even bothered trying since, just using SSHFS instead - it was so slow it basically was always crashing any app that was using it, like Sublime or vscode when having a folder from \\wsl.localhost added.

I'll see about trying again sometime and getting logs if I can.
