### ISSUE TITLE
WSL seems to prevent system from hibernating

### ISSUE THREAD

**Issue by molohov** [microsoft/WSL#10005]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

Start > Power > Hibernate
The screen blanks for a few seconds
The lock screen returns

Event viewer reports the following Kernel-Power events:
```
User-mode process attempted to change the system state by calling SetSuspendState or SetSystemPowerState APIs.
The driver \Driver\vpcivsp for device ROOT\VPCIVSP\0000 stopped the power transition.
```

The system can eventually hibernate if I try enough times.

### Expected Behavior

I expect the system to hibernate correctly on the first try

### Actual Behavior

The system does not hibernate

**Comment by molohov** [comment]
Closing as the real issue is actually
Error 45 The system could not sucessfully load the crash dump driver.
Unrelated to WSL

**Comment by MuelNova** [comment]
I'm facing the same issue, have you ever found how to solve the hibernate problem?
