### ISSUE TITLE
Cant change Ubuntu from WSL1 to 2 in windows 10

### ISSUE THREAD

**Issue by manuel-huawei** [microsoft/WSL#10004]
### Windows Version

Microsoft Windows [Version 10.0.19045.2604]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Ubuntu 22.04

### Repro Steps

`wsl --set-version Ubuntu 2  `

### Expected Behavior

Should smoothly change from WSL1 to WSL2

### Actual Behavior

```
PS C:\windows\system32> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
```

```
PS C:\windows\system32> wsl --set-version Ubuntu 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
Error: 0xc0000606
Error code: Wsl/Service/CreateVm/0xc0000606
```

### Diagnostic Logs

[WslLogs-2023-04-20_18-49-34.zip](https://github.com/microsoft/WSL/files/11289071/WslLogs-2023-04-20_18-49-34.zip)

**Comment by Biswa96** [comment]
Is Control Flow Guard (CFG) disabled in your system? If yes, try to enable it first.

**Comment by manuel-huawei** [comment]
It is on. I tried as well with with it off but still same issue. It is a weird error I havent found it anywhere online

**Comment by Biswa96** [comment]
The error code 0xc0000606 is defined in Windows SDK as STATUS_STRICT_CFG_VIOLATION. That means "The specified image file was blocked from loading because it does not enable a feature required by the process: Control Flow Guard."

**Comment by manuel-huawei** [comment]
No idea then. How comes it can work in WSL 1 and not 2? Shouldnt the same error be raised?

**Comment by DraymondBruce** [comment]
I got the same issue, even after I upgraded to win11. CFG was enabled when this error occured. After I disabled CFG, the error didnt show up but wsl --list hang forever.

**Comment by manuel-huawei** [comment]
I finally made it work. I had to follow [these steps](https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74) but for both of these programs.

![image](https://user-images.githubusercontent.com/131394031/233607000-ba164af3-297c-48c9-8045-6d6221386855.png)

Disabling/Enabling CFG globally did not work.

**Comment by AlstoX** [comment]
> I finally made it work. Disabling/Enabling CFG globally did not work. I had to follow [these steps](https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74) but for both of these programs.
> 
> ![image](https://user-images.githubusercontent.com/131394031/233607000-ba164af3-297c-48c9-8045-6d6221386855.png)

and you, my bro, you are the real hero. 
for others:

**Comment by wingmor99** [comment]
> I finally made it work. Disabling/Enabling CFG globally did not work. I had to follow [these steps](https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74) but for both of these programs.
> 
> ![image](https://user-images.githubusercontent.com/131394031/233607000-ba164af3-297c-48c9-8045-6d6221386855.png)

You are my Hero!!!!,
