### ISSUE TITLE
fd -i returns negative IUsed

### ISSUE THREAD

**Issue by shinhs0506** [microsoft/WSL#10017]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

run `df -i`

### Expected Behavior

Should not see negative numbers under IUsed

### Actual Behavior

observe negative numbers

**Comment by benhillis** [comment]
I am not seeing this locally, can you share the exact commands you are running and the output you are seeing please?

**Comment by shinhs0506** [comment]
![df](https://user-images.githubusercontent.com/51249639/234116786-dfcb5644-330c-449d-8bdd-8a1625b7685c.png)

**Comment by benhillis** [comment]
Cool thanks for the info - will investigate.
