### ISSUE TITLE
Unable to use Removable USB devices with Kali Linux

### ISSUE THREAD

**Issue by 3kh0** [microsoft/WSL#10013]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2

### Distro Version

Kali GNU/Linux Rolling on Windows 10 x86_64

### Other Software

`usbipd-win` version 2.4.1

### Repro Steps

1. Plug in drive and run `GET-CimInstance -query "SELECT * from Win32_DiskDrive"`

![image](https://user-images.githubusercontent.com/58097612/233868992-94c4bf33-5c68-4f8d-ba7b-b2121d835264.png)

2. mount the disk with `wsl --mount` and fail
![image](https://user-images.githubusercontent.com/58097612/233869564-5e6a2bc1-43dd-4811-a86d-58581689a2ab.png)
> output from dmesg https://pastebin.com/QEdF3sC8

### Expected Behavior

To be able to see the drive mounted on the the Linux Distro

### Actual Behavior

IT failed to mount with many errors.

Error file: https://pastebin.com/QEdF3sC8

### Diagnostic Logs

[WslLogs-2023-04-23_18-37-21.zip](https://github.com/microsoft/WSL/files/11305115/WslLogs-2023-04-23_18-37-21.zip)

**Comment by 0xbadfca11** [comment]
Step 1 shows that the device has a partition, but you didn't specify ``--partition``.

If the partition is NTFS the [expected failure](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations) will occur.
Use --bare instead of --partition, and mount it manually.

**Comment by 3kh0** [comment]
Ah ok, that fixed it
