### ISSUE TITLE
Creating new user don't inherit default user $PATH

### ISSUE THREAD

**Issue by theCrius** [microsoft/WSL#10015]
### Windows Version

Microsoft Windows [Version 10.0.19045.2846]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) `#1` SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Create a new WSL instance with the parameters specified above
2. Run `echo $PATH` and take note of the value
3. Run `sudo adduser newUser` and fill the details
4. Run `sudo su newUser -` to log as that user
5. Run `echo $PATH` and take note of the value.

### Expected Behavior

Any user created inherit the default WSL/Windows path.

### Actual Behavior

The value of the two `$PATH` is different with the "default" user including additional paths related to WSL and your windows installation while the new user having only the default Ubuntu paths.

**Comment by benhillis** [comment]
This is Linux behavior. When you run `su` you are clearing out your current environment variables.

https://man7.org/linux/man-pages/man1/su.1.html

**Comment by theCrius** [comment]
> This is Linux behavior. When you run `su` you are clearing out your current environment variables.
> 
> https://man7.org/linux/man-pages/man1/su.1.html

Of course it's Linux behaviour. The point here it's that this is WSL, not a barebone Linux isn't it?
How are the current ENV variables inherited on the default user then? Can you point out some documentation on that so I can give it a look myself and see if I can write a tool that would (semi) automate that inheritance myself?

**Comment by Biswa96** [comment]
>  Is there a way to conveniently change which user to connect to when starting WSL then?

`wsl.exe -u <user>` command may help.

**Comment by theCrius** [comment]
Great @Biswa96, just tested and work perfectly 👍
