### ISSUE TITLE
Cannot enable custom Chrony daemon

### ISSUE THREAD

**Issue by pbotros** [microsoft/WSL#10024]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2 

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Install fresh WSL2, via wsl --install. Reboot as necessary
2. `sudo apt install chrony`
3. `sudo systemctl stop chrony` # stop chrony
4. `ps aux | grep chrony` # verify there's no running chrony
5. `chronyc tracking` # yet chronyc still works, successfully connecting to some chrony daemon, and returns "PHC0" as a source

Said another way, it seems that there's some default version of `chrony` running that's invisible to the WSL2 user. This interferes with custom `chrony` config or sources that are used within the WSL2 Ubuntu image (e.g. when synchronizing to a custom server on a local network).

### Expected Behavior

I expect that installing chrony, changing the config in `/etc/chrony/chrony.conf`, restarting chrony via `sudo systemctl restart chrony`, and then monitoring chrony sources via `chronyc tracking` or `chronyc sources` should return the custom servers/pools/sources configured in that .conf file.

Is there a way to stop this "default" chrony server from running?

### Actual Behavior

```
iebl@DESKTOP-1JJC6GO:~$ sudo systemctl stop chrony
iebl@DESKTOP-1JJC6GO:~$ ps aux | grep chrony
iebl         741  0.0  0.0   4024  2072 pts/0    S+   09:31   0:00 grep --color=auto chrony
iebl@DESKTOP-1JJC6GO:~$ chronyc tracking
Reference ID    : 50484330 (PHC0)
Stratum         : 1
Ref time (UTC)  : Tue Apr 25 16:31:19 2023
System time     : 0.000000221 seconds slow of NTP time
Last offset     : -0.000000156 seconds
RMS offset      : 0.000007208 seconds
Frequency       : 0.029 ppm fast
Residual freq   : -0.000 ppm
Skew            : 0.018 ppm
Root delay      : 0.000000001 seconds
Root dispersion : 0.000008706 seconds
Update interval : 8.0 seconds
Leap status     : Normal
```

This "PHC0" PTP clock should not be present. Chronyc should've failed.

**Comment by OneBlue** [comment]
Thanks for reporting this @pbotros.

There is indeed a default chrony server running in the root namespace, which is why you can't see it.

Out of curiosity, why are you trying to run your own chrony ? Is WSL's clock not synchronized ?

**Comment by pbotros** [comment]
@OneBlue thanks for the feedback. WSL's clock is indeed synchronized to the host clock, but I wanted to use chrony, instead of NTP, for more accurate synchronization (c.f.: https://engineering.fb.com/2020/03/18/production-engineering/ntp-service/). Chrony is only available on Linux, hence the idea to use WSL2 to synchronize at least the container's time via chrony.

**Comment by elsaco** [comment]
@pbotros when you run `systemctl start chrony` you'll see `Warning: Running in a container, likely impossible and unintended to sync system clock`. You've been noted!

 The first PTP source is build into the hypervisor, not sure it can be disabled or removed:

```
tux@focal:~$ ls /sys/class/ptp
ptp0
tux@focal:~$ cat /sys/class/ptp/ptp0/clock_name
hyperv
tux@focal:~$ ls -l /dev/ptp*
crw------- 1 root root 249, 0 Apr 25 20:08 /dev/ptp0
lrwxrwxrwx 1 root root      4 Apr 25 20:08 /dev/ptp_hyperv -> ptp0
```

so `chronyc` will pick this source when `chronyd` is not running. Check `chronyc sources` when the service is running and PTP0 is ignored.

**Comment by pbotros** [comment]
Re: the warning: got it!

Re: when the service is running: something I didn't mention in the initial report is that when the WSL2 `chronyd` is running, via `systemctl start chrony`, `chronyc sources` seems to connect to either the root or the WSL2 chrony on an arbitrary basis. If you run `chronyc sources` many times, you'll see that sometimes it connects to a `chronyd` daemon that only has a PTP source (ref id `PHC0`), or sometimes it connects to the WSL2 daemon with the custom config (with custom servers/pools, for instance). I imagine this is an artifact of chrony using UDP, where the first response arriving from either daemon is used by `chronyc`.

Outside of `chronyc` connecting to the wrong daemon, I think the bigger problem is that there are two `chrony` daemons running effectively in the same container (IIUC). Given this, is there a way to edit the root namespace's `chrony.conf` or otherwise disable the root namespace's chrony manually?

**Comment by FrothyB** [comment]
I have unending clock sync issues and wanted to switch to chrony also. I have encountered all the above issues. Has anyone found a solution to get chrony to ignore PHC0?
