### ISSUE TITLE
Can't start wsl from run window

### ISSUE THREAD

**Issue by JenyaRostov** [microsoft/WSL#10025]
### Windows Version

Microsoft Windows [Version 10.0.19045.2846]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

open Run window (win+r)
type wsl, press enter

### Expected Behavior

Launch wsl successfully

I was messing around with conhost.exe (mainly security tab to transfer ownership to myself but i've since returned it to TrustedInstaller)
Would appreciate any tips on how to debug this issue
WSL starts fine from cmd

### Actual Behavior

got error (Application was unable to start correctly (0xc0000022))

**Comment by JenyaRostov** [comment]
[WslLogs-2023-04-26_00-25-54.zip](https://github.com/microsoft/WSL/files/11326991/WslLogs-2023-04-26_00-25-54.zip)

**Comment by pmartincic** [comment]
Did you let the tracing collect logs while reproducing the issue? I don't see much in there.

**Comment by JenyaRostov** [comment]
Yes, the issue is that wsl doesn't start at all when trying to start from Run window and gives 0xc0000022 error

**Comment by JenyaRostov** [comment]
Every other app I tried works fine

**Comment by pmartincic** [comment]
I didn't read this fully. If you changed the app execution alias permissions and haven't restored them completely it is likely to not work.

**Comment by the-exodus** [comment]
The error you're getting is the NTSTATUS constant for access denied. I'm guessing that when playing around with the ACLs you forgot to re-add yourself, or Authenticated Users etc, with read/execute permissions. Because when you made yourself owner, you most likely broke the inheritance, meaning when you gave up ownership you may not have any permissions at all :)

**Comment by JenyaRostov** [comment]
Thanks for the insight, I will try again with permissions!

**Comment by JenyaRostov** [comment]
Also is there a way what file exactly gives access denied error? that would help a lot

**Comment by the-exodus** [comment]
It's possible that it gets recorded in the application, system or security logs that you can view in Event Viewer, but it's far from certain.

The fastest way to repair this would probably be to start an elevated cmd.exe (if you can :P) and run `icacls.exe c:\windows\system32 /reset /t /c /l`, assuming you have your installation there.

**Comment by JenyaRostov** [comment]
just tried that, didn't work

**Comment by the-exodus** [comment]
How did it fail? Were you able to launch an elevated console or did you get access denied? Did you get cmd.exe running as admin, but got access denied when attempting to reset permissions? Did everything appear to work, only to not have any effect?

**Comment by JenyaRostov** [comment]
I fixed it, apparently i also messed up WindowsApp permissions.
I returned them to normal and everything works fine now
Thanks for the help!
