### ISSUE TITLE
SSH, apt Update, cannot connect

### ISSUE THREAD

**Issue by CoryKniefel** [microsoft/WSL#10035]
### Windows Version

Microsoft Windows [Version 10.0.22621.1635]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Other Software

Git, apt. 

### Repro Steps

1. Open a terminal to Ubuntu
2. run `sudo apt update`
3. After a moment I get this output: 
Err:1 https://dl.google.com/linux/chrome/deb stable InRelease
  Cannot initiate the connection to dl.google.com:443 (2607:f8b0:4007:815::200e). - connect (101: Network is unreachable) Could not connect to dl.google.com:443 (142.250.176.14), connection timed out
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out
Err:3 http://archive.ubuntu.com/ubuntu focal InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.38), connection timed out
Err:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable)
Err:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.38), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out
W: Failed to fetch https://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Cannot initiate the connection to dl.google.com:443 (2607:f8b0:4007:815::200e). - connect

### Expected Behavior

I expect the process to update and proceed. 

### Actual Behavior

I get the above output in steps to reproduce.  What's weird is that I can ping an address like google.com. 

This started about 24 hours ago when I noticed when I do a `git pull` it would just hang, whereas it had been working all day long. I've restarted my machine, fully updated everything I can think of, and still the problem persists. 

I've installed the Debian distro and I get the same exact problem with the `apt update` command. 

I haven't tried some things I've seen online because they are from over a year ago and I have a more recent version than they did then. 

UPDATE: 
This happens for all new distribution installs. For instance, I get this same behavior on Ubuntu 22 (Ubuntu 22.04.2 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64))

**Comment by CoryKniefel** [comment]
Example of SSH failing a test
![ssh cannot connect](https://user-images.githubusercontent.com/15177683/235006102-b792f5d2-0dd0-4a2a-bb27-1240df87ac8f.png)

**Comment by zcobol** [comment]
@CoryKniefel you forgot to hide `strawberry.aravo.nework` starting with `debug2` statement!

**Comment by CoryKniefel** [comment]
> @CoryKniefel you forgot to hide `strawberry.aravo.nework` starting with `debug2` statement!

Sweet, thanks for letting me know. Can you delete your comment for me?

**Comment by CoryKniefel** [comment]
@zcobol thank you. Can you please delete your comment?

**Comment by CoryKniefel** [comment]
This is an example of it failing to ssh
![ssh cannot connect](https://user-images.githubusercontent.com/15177683/235037201-bbba5e11-e3c6-4624-b8d6-546c764a8236.png)

**Comment by CoryKniefel** [comment]
Problem solved with: https://github.com/microsoft/WSL/issues/8985#issuecomment-1347481765
Why would this just start to happen out of the blue?
