### ISSUE TITLE
Can't open self written GUI apps WSL2 (Ubuntu)

### ISSUE THREAD

**Issue by weebik** [microsoft/WSL#10034]
### Windows Version

Microsoft Windows [Version 10.0.22621.1635]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

My custom application (arkanoid written in C with SDL2)

### Repro Steps

launching game

### Expected Behavior

After launching app game interface should be visable, sound should play and after input game should start.

### Actual Behavior

After launching app music plays normally but the screen of the app remains black, after input we can hear  sounds (the game actually works, but we cant see the gui).

### Diagnostic Logs

this is what launched game looks like:
![image](https://user-images.githubusercontent.com/115700420/234940100-a88dc475-a86a-4859-a296-fc6eea44809c.png)
![image](https://user-images.githubusercontent.com/115700420/234940209-63f1b6e8-b04a-4030-9d2d-5638faf495ee.png)
this is how it should look like:
![image](https://user-images.githubusercontent.com/115700420/234940971-662adeaa-28d5-4e68-a932-1687094a484e.png)

**Comment by pmartincic** [comment]
You'll want to file a bug for wslg https://github.com/microsoft/wslg/issues/new?assignees=&labels=bug&template=bug_report.yml and include more reproduction information.
