### ISSUE TITLE
need to completely remove WSL and start over

### ISSUE THREAD

**Issue by mzimmersfluidra** [microsoft/WSL#10043]
### Windows Version

[Version 10.0.19045.2846]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu-22.04

### Repro Steps

Open PowerShell as admin
Enter the following commands with the errors shown:
`PS C:\windows\system32> wsl
Windows Subsystem for Linux has no installed distributions.

Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.

Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error code: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND
PS C:\windows\system32> wsl -l -o
The following is a list of valid distributions that can be installed.
Install using 'wsl.exe --install <Distro>'.

NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
OracleLinux_7_9                        Oracle Linux 7.9
OracleLinux_8_7                        Oracle Linux 8.7
OracleLinux_9_1                        Oracle Linux 9.1
SUSE-Linux-Enterprise-Server-15-SP4    SUSE Linux Enterprise Server 15 SP4
openSUSE-Leap-15.4                     openSUSE Leap 15.4
openSUSE-Tumbleweed                    openSUSE Tumbleweed
PS C:\windows\system32> wsl --install -d Ubuntu-22.04
Ubuntu 22.04 LTS is already installed.
Launching Ubuntu 22.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.`

### Expected Behavior

Should be able to install Ubuntu.

### Actual Behavior

Get the error 0x80070002.

Also: when I type "wsl" into my search, and right-click to select "Show file location" it opens this directory:
C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
There is another copy of wsl.exe in Windows\System32, which I suspect is what I want.

I'd like to delete ALL occurrences of WSL and reinstall, but I don't know how to do this.

Thanks...

### Diagnostic Logs

none

**Comment by danabases** [comment]
I have this same issue.  I've been trying to remove and reinstall WSL, but I still have an old copy in Windows/System32 with files wsl.exe, wslapi.dll, and wslconfig.exe.  

I've tried reinstalling, however, the .wslconfig file is missing in %UserProfile%.  I am running the latest version and installed distributions report WSL 2.  

The new installation of wsl.exe is in C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe


![image](https://user-images.githubusercontent.com/30123146/235463913-2fcc81ce-8fd2-413e-aeeb-54e005a0fb1a.png)
![image](https://user-images.githubusercontent.com/30123146/235466100-8a0d4e96-e28a-4d81-9bc6-ab020bf48f7a.png)
![image](https://user-images.githubusercontent.com/30123146/235466735-68cede74-8c9a-452f-bf06-d69b0688169b.png)

**Comment by risg99** [comment]
Yes, I am experiencing the same issue.
