### ISSUE TITLE
How does WSL fix ip?

### ISSUE THREAD

**Issue by HKTY569** [microsoft/WSL#10048]
Hello, the parameters of my device are
WSL Version： 1.2.5.0
using WSL 2
Kernel Version： 5.15.90.1
Distro Version：Debian 11
Windows Version： 10.0.22621.1413

After I adjust the IP in cat /etc/resolv.conf, the initial IP will be restored every time I boot. How to fix IP? And it is not the IP of the same network segment every time....
Or is there any way to fix the IP?
![de28f55d3242a3599ab3e87ea1f6ce5](https://user-images.githubusercontent.com/35788811/235408038-aedaf8aa-f154-4a09-95ca-281313fd7f1d.png)

**Comment by Biswa96** [comment]
> Or is there any way to fix the IP?

The `/etc/resolv.conf` file is automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:

```ini
[network]
generateResolvConf = false
```

**Comment by HKTY569** [comment]
> > 或者有什么办法可以修复IP吗？
> 
> 该`/etc/resolv.conf`文件由 WSL 自动生成。要停止自动生成此文件，请将以下条目添加到 /etc/wsl.conf：
> 
> ```ini
> [network]
> generateResolvConf = false
> ```

But will wsl still get ip automatically?

**Comment by Biswa96** [comment]
> But will wsl still get ip automatically?

The answer is mostly yes :)

Though WSL2 sometimes get a static IP address. See this thread https://github.com/microsoft/WSL/discussions/9580. Those reserve a random private IP block for WSL2. But its working conditions are not known yet.

**Comment by HKTY569** [comment]
> > But will wsl still get ip automatically?
> 
> The answer is mostly yes :)
> 
> Though WSL2 sometimes get a static IP address. See this thread #9580. Those reserve a random private IP block for WSL2. I have added parameters but it doesn't work. I have set a static ip by editing /etc/network/interfaces, but I restart wsl and it will automatically reassign me an ip.....
And the docker container uses the automatically assigned ip segment.....
![4f3cbc9420c5f70bbc2fab5179a0392](https://user-images.githubusercontent.com/35788811/235463685-5d0f57c4-0590-4e13-b2b8-8b4fea44440b.png)
![cc4d7687c16387a4134d9673dd86b37](https://user-images.githubusercontent.com/35788811/235463693-e3b110c0-bac5-4938-afad-8d2f3cb64553.png)

**Comment by Biswa96** [comment]
> but I restart wsl and it will automatically reassign me an ip.....

The result is expected. The WSL2 is a lightweight VM. The network interface is managed by the WSL2 system and not by any program which reads `/etc/network/interfaces` file.

**Comment by HKTY569** [comment]
> > 但我重新启动wsl ，它将自动为我重新分配一个ip ......
> 
> 结果在意料之中。WSL2是轻量级虚拟机。网络接口由WSL2系统管理，而不是由任何程序管理 `/etc/network/interfaces` 文件。

Oh, I really didn't expect it to be the wsl management network, because I installed Debian, so I always thought it was the Debian management network, thank you, please, is there any good way to change the IP？

**Comment by Biswa96** [comment]
> is there any good way to change the IP？

Not yet. Coming soon™

**Comment by HKTY569** [comment]
> 

Ok, thank you, I need this feature very much

**Comment by HKTY569** [comment]
> 

Ok, thank you, I need this feature very much

**Comment by Biswa96** [comment]
There are many issues with the static IP feature request https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+static+ip

**Comment by HKTY569** [comment]
> 静态IP功能请求有很多问题https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+static+ip

It seems that compared with the virtual machine, wsl2 still has many problems that need to be improved~~~
