### ISSUE TITLE
Error code 0x800704d4 when export WSL

### ISSUE THREAD

**Issue by healenrens** [microsoft/WSL#10058]
### Windows Version

Microsoft Windows [10.0.22621.1391]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

wsl --export {my subsystem name} {location}

### Expected Behavior

I want to export my wsl to another harddisk as a backup.By the way ,it is around 350GB.

### Actual Behavior

I get the error below:
The network was closed by system.
Error code: Wsl/Service/0x800704d4

**Comment by Biswa96** [comment]
> I want to export my wsl to another harddisk as a backup.By the way ,it is around 350GB.

For WSL2, you could just copy-paste the ext4.vhdx file as a backup.

**Comment by healenrens** [comment]
Ok,thanks for your advice.
