### ISSUE TITLE
drvfs should clean opts to report on /proc/mounts

### ISSUE THREAD

**Issue by jaysonsantos** [microsoft/WSL#10056]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.90.1

### Distro Version

Arcch

### Other Software

Docker Desktop Windows

### Repro Steps

Let docker desktop or any mount that uses drvfs where the path passed to opts contains whitespaces.

### Expected Behavior

Those spaces should be converted to `\040`

### Actual Behavior

The opts includes whitespaces, which breaks getmntent and any parsing mechanisms that tries to rely on the file being separated by spaces:

```
drvfs /Docker/host 9p rw,dirsync,noatime,aname=drvfs;path=C:\Program Files\Docker\Docker\resources;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio 0 0
```

an example of how it should be (not really in opts):

```
/dev/sdc /home/jayson/src/a\040folder\040abc ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
```
I am not sure if this would be done in drvfs or on wsl's kernel to be honest.

**Comment by pmartincic** [comment]
I think this is in the kernel. Proc fs is in the kernel.

When I strace `mount --bind Meh\ what/ meh\ here/` there doesn't seem to be any special escaping that happens before the mount syscall. `mount("/home/me/Meh what", "/home/me/meh here", 0x555b306f0820, MS_BIND, NULL)`

**Comment by jaysonsantos** [comment]
@pmartincic does it mean I need to post somewhere else?

**Comment by pmartincic** [comment]
Yes, elsewhere. I think they accept PRs but not issues here: https://github.com/microsoft/WSL2-Linux-Kernel
