### ISSUE TITLE
Git clone exception

### ISSUE THREAD

**Issue by hyic123** [microsoft/WSL#10066]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu20.04

### Repro Steps

 Firstly, I use a bridged network, configure WSL2, and use this network. Then I run `git clone https://gitlab.utopilot.com.cn/utopilot/planning/planning-project.git`, but I get an error: `hzy@HXYZ:~/uto_ws/aiv_hh2p0$ git clone --verbose https://gitlab.utopilot.com.cn/utopilot/planning/planning-project.git
Cloning into 'planning-project'...
fatal: unable to access 'https://gitlab.utopilot.com.cn/utopilot/planning/planning-project.git/': gnutls_handshake() failed: Error in the pull function.` After that, I ping gitlab.utopilot.com.cn and find that I can ping it successfully, so I want to know where the problem lies.

### Expected Behavior

git clone --verbose https://gitlab.utopilot.com.cn/utopilot/planning/planning-project.git

### Actual Behavior

Cloning into 'planning-project'...
fatal: unable to access 'https://gitlab.utopilot.com.cn/utopilot/planning/planning-project.git/': gnutls_handshake() failed: Error in the pull function.`

**Comment by Biswa96** [comment]
There is probably some issue with that website. For example, see https://downforeveryoneorjustme.com/gitlab.utopilot.com.cn?proto=https
