### ISSUE TITLE
`bpftool` can't run on Ubuntu@WSL2

### ISSUE THREAD

**Issue by inliquid** [microsoft/WSL#10069]
### Windows Version

Version 10.0.22621.1555

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

22.04

### Repro Steps

1. Run `apt install linux-tools-common linux-tools-generic`
2. Run `bpftool -V`

### Expected Behavior

`bpftool` printed its version

### Actual Behavior

```
# bpftool -V
WARNING: bpftool not found for kernel 5.15.90.1-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.15.90.1-microsoft-standard-WSL2
    linux-cloud-tools-5.15.90.1-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
```

When trying to install any of above packages, `apt` returns an errors, such as:
```
# apt install linux-tools-standard-WSL2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-tools-standard-WSL2
```

**Comment by bobaoapae** [comment]
same problem here

**Comment by zaoying** [comment]
> same problem here

I solved this problem by install bpftool manually.

```sh
git clone --recurse-submodules https://github.com/libbpf/bpftool.git
cd bpftool/src
sudo make install
```

**Comment by inliquid** [comment]
I solved by adding a symlink with `uname -r` name in: `/usr/lib/linux-tools`:
![изображение](https://github.com/microsoft/WSL/assets/6797881/2cae629f-dcde-417d-b808-1e3f070151e2)

There also has to be appropriate `linux-tools-*` package present.

**Comment by zaoying** [comment]
> I solved by adding a symlink with `uname -r` name in: `/usr/lib/linux-tools`: ![изображение](https://user-images.githubusercontent.com/6797881/246636747-2cae629f-dcde-417d-b808-1e3f070151e2.png)
> 
> There also has to be appropriate `linux-tools-*` package present.

you need to be more careful, because wsl has modify kernel to nat between windows localhost and linux localhost,  struct ipdhr is different from the original one.

**Comment by inliquid** [comment]
@zaoying yes, I'm aware. It works as I see, no issues so far in my scenarios. However, I did compile `bpftrace` from sources with WSL2 kernel headers, for the reason you highlighted.

**Comment by vincenzo-dip8** [comment]
Hi everyone, I'm trying to use your suggestions to get use of BPF, EBPF, or LinuxTC with WSL, but I'm still unable to use them. Can you help me to solve this? i will be very grateful if you can share the script to follow in a way to have your same scenario, and work also for me

**Comment by zaoying** [comment]
> 

Would you like to share some logs?

**Comment by vincenzo-dip8** [comment]
yes, i obtain the same result of the starting of this issue report (even after trying different potential solutions):

# bpftool -V
WARNING: bpftool not found for kernel 5.15.90.1-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.15.90.1-microsoft-standard-WSL2
    linux-cloud-tools-5.15.90.1-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2

**Comment by vincenzo-dip8** [comment]
so, basically, I m trying to use LinuxTC, BPF e EPBF (and tools implementing them) on WSL2 on Windows. I m trying different code, different repositories, but they never work
