### ISSUE TITLE
regkey -DefaultUid 1000 gives error

### ISSUE THREAD

**Issue by Hifilo** [microsoft/WSL#10075]
### Windows Version

Microsoft Windows [Version 10.0.19045.2846]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

export  > unregister  > reinstall distro > unregister  > import .

However now the default user is set to root.

setting user in `wsl.conf` works correctly, but setting regkey gives error.

### Expected Behavior

`1000` is added to regkey `DefaultUid` in  
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{96f5a9dc-be29-4550-979c-d171d546cb34}`

Should set default user, and run correctly like other methods

### Actual Behavior

<3>WSL (500) ERROR: CreateProcessEntryCommon:370: getpwuid(4096) failed 0
<3>WSL (503) ERROR: CreateProcessEntryCommon:370: getpwuid(4096) failed 0

### Diagnostic Logs

Runs correct when user is specified `wsl -d Ubuntu -u <user>`

Runs correct when `[user]` added to `wsl.conf`

**Comment by Biswa96** [comment]
Does the WSL registered distribution have any user with 1000 uid?

**Comment by Hifilo** [comment]
Yes user 1000 is my default user Sent from my iPhoneOn May 7, 2023, at 1:18 AM, Biswapriyo Nath ***@***.***> wrote:﻿
Does the WSL registered distribution have any user with 1000 uid?

**Comment by elsaco** [comment]
@Hifilo what is the output of `reg query "hkcu\software\microsoft\windows\currentversion\lxss\{96f5a9dc-be29-4550-979c-d171d546cb34}" /v defaultuid`?

**Comment by Hifilo** [comment]
> @Hifilo what is the output of `reg query "hkcu\software\microsoft\windows\currentversion\lxss\{96f5a9dc-be29-4550-979c-d171d546cb34}" /v defaultuid`?

I get `HKEY_CURRENT_USER\software\microsoft\windows\currentversion\lxss\{96f5a9dc-be29-4550-979c-d171d546cb34}
    defaultuid    REG_DWORD    0x1000`

**Comment by elsaco** [comment]
That is the issue, change it to `0x3e8`

**Comment by Hifilo** [comment]
> That is the issue, change it to `0x3e8` which is 1000 in decimal. Hex 1000 is 4,096 in decimal.

Oh I see. Yes that fixed it. Thank you!
