### ISSUE TITLE
Incorrect Error Message When Exporting Distro to FAT32

### ISSUE THREAD

**Issue by atmaranto** [microsoft/WSL#10088]
### Windows Version

Microsoft Windows [Version 10.0.19044.2846]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian 11

### Repro Steps

1. Create WSL distribution with total drive size significantly over 4GB (the max FAT32 file size)
2. Insert a flash drive with sufficient total storage to hold the distro but with a FAT32 file system
3. Navigate to the FAT32 drive in `cmd.exe` and run `wsl --export <Distro> Distro.tar`. Wait for the command to terminate.
4. Observe the misleading error: `Wsl/Service/0x80070070` error with the message stating `there is not enough space on the disk`.

### Expected Behavior

The error should have referred to the fact the FAT32 file system's maximum file size is insufficient to hold the exported distro.

### Actual Behavior

The error stated `there is not enough space on the disk`, which is incorrect -- there _was_ enough space, but the maximum file size was too small.

**Comment by benhillis** [comment]
I'd be curious to see where the error is coming from, could you collect /logs? Thanks!

**Comment by atmaranto** [comment]
I'm afraid the original computer was already wiped (why I was performing the export). I'll see if I can simulate it with a virtual FAT32 mount in the next day or so (assuming I can't find another nonessential flash drive kicking around) to get the logs.
