### ISSUE TITLE
Server Execution Failed consistently happens after a period of time.

### ISSUE THREAD

**Issue by ShaneYCG** [microsoft/WSL#10091]
### Windows Version

10.0.19045.2965 / various

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Several build servers use WSL for our project's CI. Every few weeks, without fail, all of them simultaneously stop working. All interaction with WSL fails, generally with "Server Execution Failed'. Rebooting the machines sometimes works, but only if I remote into them and manually invoke wsl from the desktop. Simply remotely rebooting them never fixes it.

It is particularly strange that they always break at more or less the same time, the load on the servers is not even, and the same revisions are not built on all of them.

### Expected Behavior

WSL doesn't stop working simultaneously on all of our servers.

### Actual Behavior

wsl --version
Server execution failed

### Diagnostic Logs

Attached logs are from after the failure has occurred, and after the machines were already rebooted once, but are still in the failing state, attempting to open WSL and failing with "Server Execution Failed". All machines were subsequently "rebooted with babysitting" and the failures disappeared.
[WslLogs-2023-05-10_14-43-08.zip](https://github.com/microsoft/WSL/files/11446371/WslLogs-2023-05-10_14-43-08.zip)
[WslLogs-2023-05-10_14-43-31.zip](https://github.com/microsoft/WSL/files/11446373/WslLogs-2023-05-10_14-43-31.zip)
[WslLogs-2023-05-10_14-43-59.zip](https://github.com/microsoft/WSL/files/11446374/WslLogs-2023-05-10_14-43-59.zip)
[WslLogs-2023-05-10_14-41-50.zip](https://github.com/microsoft/WSL/files/11446375/WslLogs-2023-05-10_14-41-50.zip)

**Comment by Biswa96** [comment]
> Several build servers use WSL for our project's CI.

Just curious. Isn't it possible to use Linux in CI?

**Comment by ShaneYCG** [comment]
> > Several build servers use WSL for our project's CI.
> 
> Just curious. Isn't it possible to use Linux in CI?

It is. But almost all of our targets build on Windows, so it is convenient to just build Linux there as well, rather than have dedicated servers just for one configuration.
