### ISSUE TITLE
Line drawing characters no longer pipe to clip.exe correctly under 1.1.2 and later

### ISSUE THREAD

**Issue by NotTheDr01ds** [microsoft/WSL#10095]
### Windows Version

Tested in both Windows 10 (`[Version 10.0.19045.2965]`) and Windows 11 (`[Version 10.0.22621.1702]`)

### WSL Version

1.1.2 and later

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Tested under 5.15.83.1 and 5.15.90.1

### Distro Version

Tested in Ubuntu 20.04, 22.04, and Debian Bullseye

### Repro Steps

```
> echo "╭────────────" | clip.exe
> powershell.exe -c "Get-Clipboard"
```

### Expected Behavior

In 1.1.0 and prior releases:

```
╭────────────
```

### Actual Behavior

In WSL 1.1.2 and later:

```
Γò¡ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
```

### Background

This is especially problematic when using the Nushell shell, since it "pretty prints" much of its output in tables formatted with line-draw characters.  Previously was able to easily pipe tables to `clip.exe` and paste into the browser, a la:

```
╭───┬─────────┬─────────┬─────────╮
│ # │ Column1 │ Column2 │ Column3 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ Value1  │ Value2  │         │
│ 1 │ Value3  │ Value4  │ Value5  │
│ 2 │ Value6  │         │         │
╰───┴─────────┴─────────┴─────────╯
```

Now, in 1.1.2 and later, get the much less useful: 😉

```
Γò¡ΓöÇΓöÇΓöÇΓö¼ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö¼ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö¼ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓò«
Γöé # Γöé Column1 Γöé Column2 Γöé Column3 Γöé
Γö£ΓöÇΓöÇΓöÇΓö╝ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö╝ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö╝ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöñ
Γöé 0 Γöé Value1  Γöé Value2  Γöé      Γ¥Ä Γöé
Γöé 1 Γöé Value3  Γöé Value4  Γöé Value5  Γöé
Γöé 2 Γöé Value6  Γöé      Γ¥Ä Γöé      Γ¥Ä Γöé
Γò░ΓöÇΓöÇΓöÇΓö┤ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö┤ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓö┤ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓò»
```

**Comment by elsaco** [comment]
Not sure if this is a WSL issue. Trying the same test inside a powershell session this is the result:

```
PS C:\GitHub> Set-Clipboard ''
PS C:\GitHub> get-clipboard

PS C:\GitHub> echo "╭────────────" | clip
PS C:\GitHub> get-clipboard
Γò¡ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
```

Powershell v7.3.3 on Windows 11.

**Comment by NotTheDr01ds** [comment]
@elsaco I think the PowerShell behavior is explained by [this post](https://stackoverflow.com/a/48029600/11810933).  You can change the encoding behavior of *PowerShell* with:

```
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

... in which case the `Get-Clipboard` returns as expected.

WSL *used to* work with line-drawing characters as expected with `clip.exe`.  I installed uninstalled 1.2.5, installed 1.1.0, and it works.  I then installed 1.1.2 and it breaks again.  I then went back to 1.1.0 and it worked again.  I'm fairly sure that narrows it down to a change in WSL itself - I made no other system changes in between these tests.

I just don't see anything in the release notes for 1.1.2 that would indicate what changed, or I'd have a starting point to see if there's some way to change the encoding.

I did try starting WSL from inside a PowerShell Core session where I changed the encoding, but it didn't change the result that was placed in the clipboard when piping through `clip.exe`.

**Comment by NotTheDr01ds** [comment]
As a workaround for anyone that comes across this, I'm passing the text into `pwsh.exe -c Set-Clipboard`.  This can be a bit complicated for different use-cases, but here are some forms that are working for me:

* Bash, assign result to variable, then put that variable on the Windows clipboard:

   ```Bash
   b="╭─────────────╮
   │    Clip     │
   ╰─────────────╯"
   pwsh.exe -c "
   Set-Clipboard @'
   ${b}
   '@
   "
   ```

   Correctly results in:

   ```
   ╭─────────────╮
   │     Clip    │
   ╰─────────────╯
   ```


* In Nushell, which has better quoting mechanisms (similar to PowerShell), it's easier to call a commandline directly in the nested strings:

   ```
   pwsh.exe -c $'Set-Clipboard @"
   (ls | table | ansi strip)
   "@'
   ```

   Output:
   ```
   ╭────┬────────────────────────────────┬──────┬─────────┬────────────╮
   │  # │              name              │ type │  size   │  modified  │
   ├────┼────────────────────────────────┼──────┼─────────┼────────────┤
   │  1 │ dev.db                         │ file │  3.8 MB │ 2 days ago │
   ╰────┴────────────────────────────────┴──────┴─────────┴────────────╯
   ```
   
   The `to table` converts the output *back* to a table, normally Nushell would notice that it was being passed to an external command and convert it to text.  The `ansi strip` removes the color formatting from the table for use in Markdown, et. al.

**Comment by NotTheDr01ds** [comment]
While this issue still exists, I'll leave it to someone else to reopen it.

For additional workarounds, see [Use clipboard through WSL?](https://superuser.com/questions/1618537/use-clipboard-through-wsl) on Super User.
