### ISSUE TITLE
the wsl [automount] shouldn't mount all windows drive into wsl2, users should be able to select which windows drive or folder to mount

### ISSUE THREAD

**Issue by wy6688** [microsoft/WSL#10109]
*the wsl [automount] shouldn't mount all windows drives into wsl2, users should be able to select which windows drive or folders to mount.

**Comment by Biswa96** [comment]
User can unmount a Windows partition with command like `sudo umount -R /mnt/c`

**Comment by benhillis** [comment]
This is already possible. You can disable automount and add entries to /etc/fstab.

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings
