### ISSUE TITLE
install the wsl2 with WslRegisterDistribution failed with error: 0x80070002Error: 0x80070002 ???????????;Update wsl1 to wsl2 with Error code: Wsl/Service/CreateVm/ConfigureNetworking/ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by yikenie** [microsoft/WSL#10107]
### Windows Version

10.0.22000.1936

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Repro Steps

wsl --install;
wsl --set-default-version 1
wsl --install
wsl --set-version Ubuntu 2;

### Expected Behavior

I want to know why can`t I install the wsl2

### Actual Behavior

I tried every solution but it was still the same.
WslRegisterDistribution failed with error: 0x80070002Error: 0x80070002 ???????????
Error code: Wsl/Service/CreateVm/ConfigureNetworking/ERROR_FILE_NOT_FOUND

**Comment by 0146148541** [comment]
> Version

https://github.com/microsoft/WSL/issues/10107#issue-1709931256

**Comment by yikenie** [comment]
> 你好！您能否提供更多日志以帮助我们更好地诊断您的问题？
> 
> 要收集 WSL 日志，请在**管理 powershell 提示符**下下载并执行[collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1)：****
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> 完成后，scipt 将输出日志文件的路径。
> 
> 完成后请将输出文件上传到此 Github 问题。
> 
> [单击此处](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method)了解有关日志记录的更多信息
> 
> 谢谢你！


[WslLogs-2023-05-17_10-04-01.zip](https://github.com/microsoft/WSL/files/11493532/WslLogs-2023-05-17_10-04-01.zip)
