### ISSUE TITLE
Nested virtualization is not supported on this machine. (But, it should be?)

### ISSUE THREAD

**Issue by 44lr** [microsoft/WSL#10106]
### Windows Version

Microsoft Windows [Version 10.0.19044.2728]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Rebuild WSL2 Linux Kernel with relevant KVM / Virtualization settings enabled.
2. Set kernel image and nestedVirtualization to true on .wslconfig.
``
[wsl2]
kernel=C:\\Users\\nahu\\bzImage
nestedVirtualization=true
``
4. Start WSL.

### Expected Behavior

It should work? I've read there's issues with AMD processors but I'm running it on an Intel CPU (i7-11700KF), which, as far as I'm aware, should support it.

### Actual Behavior

Upon starting WSL it prints ``wsl: Nested virtualization is not supported on this machine.``, and kvm-ok says that the CPU does not support KVM extensions.

**Comment by benhillis** [comment]
This error indicates that your processor does not have the required processor feature for nested virtualization.

**Comment by AriFordsham** [comment]
I believe the true reason is that WSL nested virtualization is not suported on Windows 10.
