### ISSUE TITLE
wsl.conf not applied on opsenSUSE-tumbleweed

### ISSUE THREAD

**Issue by lsborg** [microsoft/WSL#10100]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

openSUSE Tumbleweed 20230304

### Other Software

systemd 252 (252.6+suse.48.g8e0a8094b8)

### Repro Steps

Install openSUSE-tumbleweed, open it, create wsl.conf enabling systemd and preventing resolv.conf automatic creation. 

`/etc/wsl.conf` contents

```
# [boot]
systemd=true

# [network]
generateResolvConf=false
```

Commands typed. 

```
wsl --install -d openSUSE-Tumbleweed
sudo nano /etc/wsl.conf
wsl --shutdown 
wsl -d openSUSE-Tumbleweed
```

This was the first try. Then I changed `/etc/resolv.conf` like this: 

```
nameserver 8.8.8.8
nameserver 10.10.10.10
```

Then installed wsl_systemd pattern, shutdown, reopened, but the result was the same, except for an extra `systemd=true` at `/etc/wsl.conf`. 

```
zypper refresh
zypper in -t pattern wsl_systemd
wsl --shutdown 
wsl -d openSUSE-Tumbleweed
``` 

### Expected Behavior

`systemd` should be running and `/etc/resolv.conf` should not be updated.  

### Actual Behavior

`systemd` is not running and `/etc/resolv.conf` was changed.  

Result from `systemctl is-system-running` is offline. 

And result from `cat /etc/resolv.conf` is similar to: 
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver x.x.x.x
```

### Diagnostic Logs

I am not admin on Windows.

**Comment by elsaco** [comment]
@lsborg the correct syntax is:

```
[boot]
systemd=true

[network]
generateResolvConf=false
```

**Comment by Biswa96** [comment]
The `/etc/wsl.conf` file should follow ini file format, see https://en.wikipedia.org/wiki/INI_file#Format

**Comment by lsborg** [comment]
I changed many things and lost track of it. It is working with or without spaces. 

Thanks for your contributions.
