### ISSUE TITLE
Default WSL version to 2 when `wsl --import <distro> <dir> <file>`

### ISSUE THREAD

**Issue by kumkee** [microsoft/WSL#10117]
### Windows Version

Microsoft Windows [Version 10.0.19044.1466]

### WSL Version

No such command option.

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

wsl --import <distro> <dir> <file> # import any wsl2 backup 

### Expected Behavior

Getting a WSL2 distro by default

### Actual Behavior

Getting legacy WSL1 instead if WSL version is not specified when importing.

### Diagnostic Logs

n.a.

**Comment by benhillis** [comment]
`wsl.exe --set-default-version 2`
`wsl.exe --import <distro> <dir> <file> --version 2`

**Comment by kumkee** [comment]
> `wsl.exe --set-default-version 2` 

Shouldn't version 2 be the default out of the box?
If it is not the default on a brand new machine after WSL installation, please re-open the issue and make it default. @benhillis

**Comment by kumkee** [comment]
Okay, if you think

1. that this issue is only about the setting the default version command, then I'll open a new issue raise the fact that the default import version before doing `--set-default-version 2` is version 1
2. that having version 1 as the out-of-the-box import default is your desired behavior, then I'd open a new issue to argue why this is bad.

Please let me know what's in your head, @benhillis. Thanks.

**Comment by kumkee** [comment]
> Okay, if you think
> 
> 1. that this issue is only about the setting the default version command, then I'll open a new issue to raise the fact that the default import version before doing `--set-default-version 2` is version 1
> 2. that having version 1 as the out-of-the-box import default is your desired behavior, then I'd open a new issue to argue why this is bad.
> 
> Please let me know what's in your head, @benhillis. Thanks.

I've assumed 1 and opened https://github.com/microsoft/WSL/issues/10158.
If it is 2, let me know, @benhillis, PLEASE.
