### ISSUE TITLE
Network connectivity fails after update to KB5026361 

### ISSUE THREAD

**Issue by mindentropy** [microsoft/WSL#10111]
### Windows Version

Microsoft Windows 10 [ Version 22H2 OS Build 19045.2846 ]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-wsl2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Install KB5026361
2. Open Ubuntu shell
3. Setup DNS
4. Ping fails.

### Expected Behavior

1. Network connectivity should work

### Actual Behavior

1. No network connectivity
2. Cannot ping any address

**Comment by sosnik** [comment]
This seems to be similar to #10068. 

Have reproduced it, and have "fixed" it by manually defining other DNS servers in resolv.conf. Underlying problem (host doesn't respond to DNS so local resolution might be borked) still remains though.
