### ISSUE TITLE
bash -c does not find executables that are found in a dedicated terminal

### ISSUE THREAD

**Issue by SkyfallWasTaken** [microsoft/WSL#10125]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

PS C:\Users\Mahad\PolyPass2> wsl.exe --version WSL version: 1.2.5.0 Kernel version: 5.15.90.1 WSLg version: 1.0.51 MSRDC version: 1.2.3770 Direct3D version: 1.608.2-61064218 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22621.1702

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Have some executable somewhere in your PATH (for me, it was `/home/skyfall/.cargo/bin/just`)
2. Run something like:
```sh
$ just build
```
3. Get an error like this:
```
PS C:\Users\Mahad\PolyPass2> bash -c "just build"
/bin/bash: line 1: just: command not found
```

Confirm whether it works in a dedicated WSL2 terminal _or_ by running `bash`, then the command.

### Expected Behavior

```
PS C:\Users\Mahad\PolyPass2> bash -c "just build"
[command output]
```

### Actual Behavior

I got an error that looks like this:
```
PS C:\Users\Mahad\PolyPass2> bash -c "just build"
/bin/bash: line 1: just: command not found
```

**Comment by pmartincic** [comment]
You may need to use ` wsl --shell-type login` to accomplish this.

**Comment by SkyfallWasTaken** [comment]
Doesn't work, this is what I'm doing:
```powershell
wsl --shell-type login "just build"
if ($LastExitCode -ne 0) {
    Write-Error "Exit code $LastExitCode while running build"
}
```
Here's the output:
```
PS C:\Users\Mahad\PolyPass2> ./run
-bash: line 1: just build: command not found       
Write-Error: Exit code 127 while running build
```

**Comment by pmartincic** [comment]
You're going to need sure that the path is set in a place where it gets picked up.

```wsl --shell-type login echo `$PATH``` will show you what is currently in the path.

As an example:
`wsl --shell-type login cargo help` and `wsl --shell-type login "cargo help"` will do two different things. The first is the correct form.
