### ISSUE TITLE
fcntl(..., F_GETPIPE_SZ, ...) returns EINVAL 

### ISSUE THREAD

**Issue by ericeil** [Microsoft/WSL#1012]
On rs_preview build 14905:

`fcntl(..., F_GETPIPE_SZ, ...)` returns EINVAL.  Is this not yet implemented?

This causes one test failure in .NET Core.

**Comment by sunilmut** [comment]
@ericeil - That's correct. This is currently not implemented and I have opened a task to track it. No ETA at this moment.

**Comment by ViktorHofer** [comment]
any update?

**Comment by Brian-Perkins** [comment]
I believe this has been fixed for a couple of releases. I will leave it open until someone can verify.

**Comment by tara-raj** [comment]
Closing this as it's fixed. Please re-open if you run into any issues.
