### ISSUE TITLE
wsl2 fail to build kernel

### ISSUE THREAD

**Issue by yoshino-polyu** [microsoft/WSL#10126]
### Windows Version

Microsoft Windows [Version 10.0.23451.1000]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 18.04 LTS

### Repro Steps

go to https://github.com/microsoft/WSL2-Linux-Kernel

run `sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev` in wsl2, no problems exist
run `make KCONFIG_CONFIG=Microsoft/config-wsl` in wsl2, output:
make: *** No targets specified and no makefile found.  Stop.

### Expected Behavior

go to https://github.com/microsoft/WSL2-Linux-Kernel

run `sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev` in wsl2, no problems exist
run `make KCONFIG_CONFIG=Microsoft/config-wsl` in wsl2, output:
make: *** No targets specified and no makefile found.  Stop.

### Actual Behavior

go to https://github.com/microsoft/WSL2-Linux-Kernel

run `sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev` in wsl2, no problems exist
run `make KCONFIG_CONFIG=Microsoft/config-wsl` in wsl2, output:
make: *** No targets specified and no makefile found.  Stop.

**Comment by elsaco** [comment]
@yoshino-polyu where are you invoking `make` from? Looks like it can't locate the `Makefile`. The latest WSL2 kernel extracts to `WSL2-Linux-Kernel-linux-msft-wsl-6.1.21.2` and if you didn't rename the directory start the build process there:

```
elsaco@ubuntu:~/WSL2-Linux-Kernel-linux-msft-wsl-6.1.21.2$ make KCONFIG_CONFIG=Microsoft/config-wsl
  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
---cut---

```

I usually specify a target to make:

`elsaco@ubuntu:~/WSL2-Linux-Kernel-linux-msft-wsl-6.1.21.2$ make KCONFIG_CONFIG=Microsoft/config-wsl bzimage`

and this will build a compressed kernel.

**Comment by yoshino-polyu** [comment]
Thanks. Actually, I didn't know where my WSL2 kernel extracts to, and Google gives C:\WINDOWS\System32\lxss\tools\kernel , which is definitely not what you said (~/WSL2-Linux-Kernel-linux-msft-wsl-6.1.21.2). I also use the command `find / -name "WSL2-Linux-Kernel-linux*" -print 2>/dev/null` to search that file, but output shows nothing.
