### ISSUE TITLE
Stop background launching distro for files that end on recently used file list in explorer

### ISSUE THREAD

**Issue by XEmpty** [microsoft/WSL#10123]
### Windows Version

[Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Open any file using `\\wsl.localhost\distro\path` from the host ~~from WSL user path.~~
Make sure that file will appear on recent list in explorer.
Shutdown wsl by wsl --shutdown
~~Make sure that VmmemWSL isn't on process list~~
Open File Explorer and go to Home Tab
See that the distro has started int he background.

### Expected Behavior

~~Stop partly startup VmmemWSL process while i don't want to use WSL in case when i open File Explorer or Start Menu.~~
Don't background launch distro for files that end up on the recently used file list in explorer. If files accessed through plan9 end up on the recently used file list but aren't opened by the user it still causes the distro to start in the background.

### Actual Behavior

When I open File Explorer and go to my home folder, there are some recently opened files, and if something comes from WSL of any file type, File Explorer loads much slower and a new `VmmemWSL` process appears, which costs me about 600 MB of RAM because a 0.1 kb file was opened in the past.

I have to shut down WSL with the `wsl --shutdown` command, but if I select that file in the list or reopen File Explorer, the process comes back and is there every time I do.

The process kills itself after a few minutes when the explorer does nothing, but if I just click on that file, reopen the explorer or right-click on that file in the Start menu (yes, in the Start menu it happens too), again the process returns.

_There is a simple solution, just clear files or this particular file from the list of recent files._

PS. Menu Start might much slower open window, like in explorer.

**Comment by rllane17** [comment]
#10127

**Comment by pmartincic** [comment]
I took the liberty of editing your comment and title for readability. 

@craigloewen-msft, I'm not sure what to do about this.

Have you tried turning off the recently used files list?
<img width="280" alt="image" src="https://github.com/microsoft/WSL/assets/102559858/c50b58a5-0597-48dc-8e79-3f662d97a98a">

**Comment by XEmpty** [comment]
> I took the liberty of editing your comment and title for readability. 
> 
> @craigloewen-msft, I'm not sure what to do about this.
> 
> Have you tried turning off the recently used files list?
> <img width="280" alt="image" src="https://github.com/microsoft/WSL/assets/102559858/c50b58a5-0597-48dc-8e79-3f662d97a98a">
> 

Yes, it is better to clean before, and then you can turn it off. But this function is useful for daily use. So it would be better to disable it only for WSL. If there was such an option.
