### ISSUE TITLE
WSL ssh remote port forwarding does not works 

### ISSUE THREAD

**Issue by callmeks** [microsoft/WSL#10134]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90

### Distro Version

kali 

### Repro Steps

- remote 
```
ss -tulpn
tcp          LISTEN        0             4096                     127.0.0.1:3000                     0.0.0.0:*
```
Step 1: run `ssh -R 3000:127.0.0.1:3000 user@IP`
Step 2: login with the password
Step 3: check your localhost and see if the port is forwarded or not

### Expected Behavior

the port should be forwarded into localhost

### Actual Behavior

the port did not forward into localhost

**Comment by OneBlue** [comment]
Fixed by [WSL 1.3.10](https://github.com/microsoft/WSL/releases/tag/1.3.10)
