### ISSUE TITLE
WSL2 use wrong ip address when NIC have mutliple ip address.

### ISSUE THREAD

**Issue by tpunix** [microsoft/WSL#10137]
### Windows Version

Microsoft Windows [版本 10.0.19044.2846]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04

### Repro Steps

NIC has 3 address:
172.16.8.28  <-- local.
192.168.1.2  <-- local.
192.168.136.2  <-- wan. gateway 192.168.136.22

when ping(ping 8.8.8.8) from wsl2, I can see a packet on gateway:  ICMP request 172.16.8.28 -> 8.8.8.8.
It seems that WSL always use minimal address as source when forward.
gateway can receive ICMP reply form 8.8.8.8, but can't send back to 172.16.8.28. gateway only know 192.168.136.xx.

### Expected Behavior

packet on gateway should be: ICMP request 192.168.136.2 -> 8.8.8.8

### Actual Behavior

packet on gateway:  ICMP request 172.16.8.28 -> 8.8.8.8.

### Diagnostic Logs

the same problems: #9803

**Comment by OneBlue** [comment]
Thank you for reporting this @tpunix. What's the context in which your NIC has multiple ip addresses ? What's the output of `wsl ip a ` ?

**Comment by OneBlue** [comment]
> Thank you for reporting this @tpunix. What's the context in which your NIC has multiple ip addresses ? What's the output of `wsl ip a ` and `wsl ip route show` ?

**Comment by tpunix** [comment]
"wsl ip a":
C:\Users\tpu>wsl ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 5e:67:a7:e3:08:3a brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ba:0b:7b:dd:e7:58 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:53:e0:44 brd ff:ff:ff:ff:ff:ff
    inet 172.29.56.207/20 brd 172.29.63.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe53:e044/64 scope link
       valid_lft forever preferred_lft forever


"wsl ip route show":
default via 172.29.48.1 dev eth0
172.29.48.0/20 dev eth0 proto kernel scope link src 172.29.56.207

**Comment by OneBlue** [comment]
Thank you @tpunix. From what I see everything is expected. I'm surprised the source address of the ICM packet isn't correctly set when the packet goes to the gateway. 

@keith-horton: How could we root cause this ?

**Comment by keith-horton** [comment]
What does "Get-NetRoute" and "Test-NetConnection -InformationLevel Detailed -DiagnoseRouting" say when you run it from powershell on the host?

**Comment by tpunix** [comment]
![图片](https://github.com/microsoft/WSL/assets/3216648/cdc35e12-df72-4fdb-b117-d392c0349010)
![图片](https://github.com/microsoft/WSL/assets/3216648/df884d8a-2e49-4a4c-91ea-5c384a71f0af)
