### ISSUE TITLE
Catastrophic failure : Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

### ISSUE THREAD

**Issue by ShafiqAiman94** [microsoft/WSL#10140]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu-20.04

### Repro Steps

Start Ubuntu 20.04 from Windows terminal.

### Expected Behavior

Ubuntu 20.04 should start normally.

### Actual Behavior

Unable to open up my Ubuntu 20.04.6
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

[process exited with code 3221225786 (0xc000013a)]

Attached is the log during the issue was happening.

### Diagnostic Logs

[WslLogs-2023-05-26_15-20-30.zip](https://github.com/microsoft/WSL/files/11572717/WslLogs-2023-05-26_15-20-30.zip)
```[tasklist]
### Tasks
```

**Comment by OneBlue** [comment]
Thank you for reporting this @ShafiqAiman94. Looking at the logs, I see: 

`EXT4-fs (sdc): Remounting filesystem read-only`, which is probably the root cause of the issue you're seeing. 

Can you follow [these instructions](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error) to repair your filesystem ? This should resolve the issue.

**Comment by brookst** [comment]
Thanks @OneBlue, that worked for me. I couldn't see the logs but searching this error code led me here.
I used a second distribution (Ubuntu) to recover like so:
```
PS> wsl -d Ubuntu --mount C:\Users\User\AppData\Local\Jammy\ext4.vhdx --vhd --bare
The operation completed successfully.
PS> wsl -d Ubuntu lsblk
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda    8:0    0 363.3M  1 disk
sdb    8:16   0     2G  0 disk [SWAP]
sdc    8:32   0   256G  0 disk
sdd    8:48   0   256G  0 disk /mnt/wslg/distro
PS> wsl -d Ubuntu sudo e2fsck -f /dev/sdc
[sudo] password for user:
e2fsck 1.46.3 (27-Jul-2021)
...
PS> wsl --unmount
```

**Comment by zlcai12138** [comment]
安装过程中显示：C:\Windows\system32>wsl --install -d Ubuntu
正在安装: 虚拟机平台
已安装 虚拟机平台。
正在安装: 适用于 Linux 的 Windows 子系统
已安装 适用于 Linux 的 Windows 子系统。
正在安装: 适用于 Linux 的 Windows 子系统
灾难性故障

C:\Windows\system32>

**Comment by JustSuperHuman** [comment]
I had trouble trying to repair this using Ubuntu or another WSL installation. This was my complete steps and it worked perfectly. 
```bash
wsl --list --all --verbose # List all WSL Installations
wsl -d docker-desktop --mount "C:\Users\user\AppData\Local\Docker\wsl\disk\docker_data.vhdx" --vhd --bare # Specifically chose docker-desktop and mounted my docker-data.vmdx with --vhd and --bare
wsl -d docker-desktop # Connect to WSL

#> lsblk # List all partitions
#> fsck /dev/sda
#> fsck /dev/sdb
#> fsck /dev/sdc
#> fsck /dev/sdd
#> fsck /dev/sde
#> fsck /dev/.... # Scorched Earthed this... just ran on every partition
#> exit # Leave
wsl -d docker-desktop --unmount "C:\Users\userAppData\Local\Docker\wsl\disk\docker_data.vhdx"
```

Restarted Docker Desktop and all was goooood 😎

**Comment by rgdigital** [comment]
@JustSuperHuman Thank you very much, connecting to Docker was a great idea 👍All fixed now.

**Comment by bigcat2014** [comment]
@JustSuperHuman This was the way. Tried so many other "solutions" that didn't work. The `fsck` was the ticket. Thanks!

**Comment by notable-equivalent** [comment]
A tip for anyone else getting this issue, running `fsck` in the same distribution that's having the issue may not work (you may see a "disk in use" error). Just install another distribution in that case, mounting the disk to the new distribution
