### ISSUE TITLE
VPN connection within instance 1, blocks traffic to instance2

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [microsoft/WSL#10145]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Repro Steps

you have to have 2 instances
connect to vpn using openvpn in instance1
open another instance, all traffic to second instance is blocked by first instance due vpn cpnnection

### Expected Behavior

I would expect vpn connection for instance 1, wouldn't influence in instance 2. their network should be isolated each other

### Actual Behavior

VPN connection within instance one is blocking network traffic for instance2 or mores

**Comment by pmartincic** [comment]
Unfortunately, is by design. Distros are not separated in the network namespace.
