### ISSUE TITLE
Change Apache document Root folder on NTFS partition

### ISSUE THREAD

**Issue by JayBeeDe** [Microsoft/WSL#1015]
Hi,

I have successfully enabled and installed the WSL on my Windows 10 laptop. I have also installed apache.
The default apache webpage is available at [http://localhost](http://localhost) so it works.
What I would like to do is to change the document root configuration to the mounted Windows disk partition, in _**/mnt/d/Dropbox/blog**_. I have checked the blog folder and set :

```
chown to www-data:www-data
chmod to 755
```

After service restart, I get the Apache _403 Forbidden Error_.
I have checked over the internet, but no serious issue. Do you have any idea?
- Required packages and commands to install : _apache2_

**Comment by fpqc** [comment]
WSL's "DriveFS" does not support true linux-style permissions.  There was a way to do it in the past (for example, April and May's insider builds) by moving your whole WSL installation with "VolFS" to a .vhdx file on another harddrive, but there are problems doing that in recent builds.  Nobody is completely sure why it doesn't work anymore, but the devs have said they're looking into it.

**Comment by JayBeeDe** [comment]
Thanks for your answer fpqc!

**Comment by rodrymbo** [comment]
@fpqc -- That doesn't entirely explain the "Forbidden" response, since on DrvFS everything is wide open to begin with (except for obvious protected directories) and chown doesn't accomplish anything. Or maybe that is the reason, something about permissions being too open?

**Comment by rodrymbo** [comment]
I think I may know what is going on...

What does apache's error log say about it?

Is there an index.html file in that directory, or any files at all for that matter?

**Comment by JayBeeDe** [comment]
Hi,
In the meantime, I have disabled the WSL feature so I can't really take a look in the log file, but I can still re install it...
But the folder /mnt/d/Dropbox/blog was empty*
*### It probably had a desktop.ini file

**Comment by Sajito** [comment]
I don't know why it doesn't work using a folder on NTFS partition as apache root, but as a workaround you can set it up the same way I do.
Just make a symlink to your folder on NTFS partition in /var/www.

**Comment by rodrymbo** [comment]
@JayBeeDe -- If I am not mistaken (which I certainly could be) the reason you got a "403 Forbidden" error was because there was no index.html file in the directory and the apache config "forbid" the creation of a directory index to replace it. If I am right, putting an index.html file there would have resulted in normal rendering of the web page. Or maybe some other problem would have shown itself...

**Comment by adisoftbn** [comment]
I have the same problem. Running apache as root needs recompile... I cannot move the www files into linux subsystem folders... I need them to be accessed from windows

**Comment by tforesti** [comment]
Hi,
One year later I have the same problem :).
I don't really understand what @fpqc write... Is it a solution ? Does anyone have a solution ?
My goal is to have a web environment on WSL but with source files accessible from Windows.
Thank you very much.

**Comment by therealkenc** [comment]
This this is #81, although the go-to appears to be closed issue #1283 ([message](https://github.com/Microsoft/WSL/issues/1283#issuecomment-353169743)). Release notes for 17063 [here](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063).

**Comment by gwsone** [comment]
Same problem here. Any solution?

**Comment by diplopito** [comment]
I had the same issue and solved it by adding the new directory to apache2.conf, i.e.:

```
<Directory  /mnt/d/Dropbox/blog/>
       Options Indexes FollowSymLinks
       AllowOverride None
       Require all granted
</Directory>
```

And restart Apache.

**Comment by gwsone** [comment]
That actually worked. But still I am not sure why it can't work with just VirtualHost configuration. Maybe that issue is not just with NTFS systems, it might be so by the Apache design.

**Comment by diplopito** [comment]
It's Apache design indeed. Yesterday I managed to setup multiple virtual hosts in my D drive following this guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04. Once you have made the change in apache2.conf, it's virtually copy & paste to create more hosts.

**Comment by tforesti** [comment]
Personally it was an Apache configuration like @diplopito, sorry...

**Comment by LowitGC** [comment]
> I had the same issue and solved it by adding the new directory to apache2.conf, i.e.:
> 
> ```
> <Directory  /mnt/d/Dropbox/blog/>
>        Options Indexes FollowSymLinks
>        AllowOverride None
>        Require all granted
> </Directory>
> ```
> And restart Apache.
##############
Hi, I have same issue, done this but stil not working for me, I am getting 
" chmod(): Operation not permitted "

do you know who owns that folder in your setup? is it $USER:$USER or apache:apache 
?? >> /mnt/d/Dropbox/blog/

**Comment by LowitGC** [comment]
@diplopito @everyone well, my issue is, in wsl, when I do chown to www-data and chmod 755, the permission changes are not being applied, hence the " chmod(): Operation not permitted " error I am getting, apache2 can't read those application files as it hasn't got right permissions, this is on Windows subsystems for linux, (WSL).
I am running ubuntu.

**Comment by diplopito** [comment]
@LowitGC sorry for this silly question, but are you using `sudo`? I'm also using Ubuntu and don't have this problem. Which command are you exactly using so I can try to reproduce it?

**Comment by LowitGC** [comment]
@diplopito I don't know if you understood, I am using Ubuntu on WSL >> windows subsystems for linux.
my drive where wwwdocroot is d: on windows machine which I have mounted to this Ubuntu machine as /mnt/d/xyz
now, on the bash, I am as non sudo user lets say xxxx >> below is my bash with sudo as xxx is normal user.

xxx@XYNsystem sudo chown www-data:www-data /mnt/d/xyz/
and
xxx@XYNsystem sudo chmod -R 755 /mnt/d/xyz

and to check it if I did ls -la on /mnt/d/xyz
its still shows as owned by user xxxx  xxxx instead of www-data www-data 
and my apache2 says >> chmod90: Operation not permitted

This is in detail, I can't see how much more better I can explain this for you to replicate!!

**Comment by LowitGC** [comment]
@JayBeeDe 
Did you solve your issue? and how?

**Comment by JayBeeDe** [comment]
It was 2 years ago... I just remember that no it was not working as expected at the end!

**Comment by LowitGC** [comment]
@diplopito , Thanks for clarifying, It isn't working for me with %U %U and I still have file permission errors, however, I have been able to mount using drvfs file type with metadata and I could change to www-data and it all works fine now and file permissions are persistent.
This might give you more info on drvfs file type mount, 

[https://www.howtogeek.com/331053/how-to-mount-removable-drives-and-network-locations-in-the-windows-subsystem-for-linux/](url) 

Thanks

**Comment by mhobesong** [comment]
> 
> 
> I had the same issue and solved it by adding the new directory to apache2.conf, i.e.:
> 
> ```
> <Directory  /mnt/d/Dropbox/blog/>
>        Options Indexes FollowSymLinks
>        AllowOverride None
>        Require all granted
> </Directory>
> ```
> 
> And restart Apache.

Just had same 404 Forbidden error with Apache2 running on WSL in Windows 10.
This your tip actually solve the issue. Thanks again
@diplopito

**Comment by diplopito** [comment]
> 
> Just had same 404 Forbidden error with Apache2 running on WSL in Windows 10.
> This your tip actually solve the issue. Thanks again
> @diplopito

Glad that it helped. I've taken it a step forward: https://www.youtube.com/watch?v=0U2oN4v_bnQ

**Comment by teneco-c** [comment]
> That actually worked. But still I am not sure why it can't work with just VirtualHost configuration. Maybe that issue is not just with NTFS systems, it might be so by the Apache design.
> --- edit ---
> Yup! Checked with Ubuntu, you can't set VirtualHost with root outside "/var/www" without adding the destination in apache2.conf.

I resolved with VirtualHost configuration like this:
<Directory  /mnt/e/www/test/>
Options Indexes FollowSymLinks
AllowOverride None
Require all granted
</Directory>
<VirtualHost *:80>
	ServerName test.local

	ServerAdmin webmaster@localhost
	DocumentRoot /mnt/e/www/test

	ErrorLog ${APACHE_LOG_DIR}/error_test.log
	CustomLog ${APACHE_LOG_DIR}/access_test.log combined
</VirtualHost>
