### ISSUE TITLE
How to solve WSL2 error 0x803b0017?

### ISSUE THREAD

**Issue by m-takahashi-lattice** [microsoft/WSL#10150]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Enable "Virtualization Technology" in BIOS.
1. Run the following commands on CMD.exe as admin:
    ```
    > wsl --set-default-version 2
    > wsl --install
    ```
1. Then, wsl2 installs latest Ubunts and starts.
1. Exit Ubunts with `exit` command.
1. Exit CMD.exe with `exit` command.
1. Start CMD.exe again.
1. Run `wsl` command and get the following error:
    ```
    低下状態のオブジェクトに対する操作の試みがありました。
    Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x803b0017
    ```

### Expected Behavior

Ability to access my WSL2.

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/80650996/8f0dde14-f790-49b5-b621-86905cc40bb8)

**Comment by m-takahashi-lattice** [comment]
The attachment is logs output by collect-wsl-logs.ps1.
[WslLogs-2023-06-02_16-56-15.zip](https://github.com/microsoft/WSL/files/11633272/WslLogs-2023-06-02_16-56-15.zip)

**Comment by OneBlue** [comment]
@m-takahashi-lattice: I'm not seeing any WSL logs in the zip file you shared. Can you run the log collection while you reproduce the issue and share logs again ? 

/logs
