### ISSUE TITLE
WSL2 CentOS OpenGL version not correct

### ISSUE THREAD

**Issue by WorkingDogTT** [microsoft/WSL#10153]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

CentOS 7.9.2009 Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

CentOS 7.9.2009

### Other Software

Docker Desktop

### Repro Steps

When using GUI program such as paraview, get the error about: 
(   2.784s) [paraview        ]vtkOpenGLRenderWindow.c:761    ERR| vtkXOpenGLRenderWindow (0x87071f0): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.

Created by Docker

When using glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 7.0, 256 bits)
OpenGL version string: 2.1 Mesa 18.3.4
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

### Expected Behavior

Should use NVIDIA OpenGL

### Actual Behavior

Get VMWare vendor 2.1 Mesa 18.3.4

**Comment by pmartincic** [comment]
Can you please refile this under https://github.com/microsoft/wslg ?

They also have different log requirements, so you'll need to rewrite the bug for them. Thanks!
