### ISSUE TITLE
Rootless Docker: 'lookup registry-1.docker.io: no such host'

### ISSUE THREAD

**Issue by SStranks** [microsoft/WSL#10152]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

- Install docker
- Configure rootless docker (https://docs.docker.com/engine/security/rootless/)
- Run dockerd-rootless-setuptool.sh --skip-iptables, on non-sudo user.
- Set $PATH to /usr/bin:$PATH and $XDG_RUNTIME_DIR=/home/user123/.docker/run, in .bashrc for non-sudo user.
- Switch ipv4 and ipv6 iptables to legacy mode using, update-alternatives --config iptables

- docker run hello-world

### Expected Behavior

Hello from Docker!
This message shows that your installation appears to be working correctly.

### Actual Behavior

```
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: no such host.
```

Note: Rootless worked on Ubuntu 20.04. I thought upgrading had wiped my previous images, but I located my old images in .local/share/docker under the 'vfs' storage. The upgrade switched the storage method to 'overlay2' so they became invisible.

Note: Running the non-rootless 'dockerd' and executing 'docker run hello-world' works as expected. It seems like the rootless daemon has no connectivity to the internet or network.

**Comment by SStranks** [comment]
Found a solution: https://github.com/microsoft/WSL/issues/7466#issuecomment-1488731997

It seems you have to enable 'systemd' on boot, disable the automatic creation of resolv.conf and manually create the resolv.conf file with a nameserver of 1.1.1.1

Rootful docker worked fine with the automatica resolv.conf file, not sure why rootless didn't.

**Comment by OneBlue** [comment]
Thanks for reporting this @SStranks. When you get this DNS error, what's the content of `/etc/resolv.conf` ? I wonder where the DNS is pointing to in that state

**Comment by SStranks** [comment]
> Thanks for reporting this @SStranks. When you get this DNS error, what's the content of `/etc/resolv.conf` ? I wonder where the DNS is pointing to in that state

If I enable the auto-create resolv.conf again, the file has one working line; nameserver x.x.x.x. The first two numbers (x) are the same as the eth0 interface inet & broadcast values, using ifconfig to check.

No idea what that means and why dockerd can still use it (if it is?) and dockerd-rootless can not.

**Comment by OneBlue** [comment]
Interesting. Inside docker can you actually reach that DNS server ? What's the output of `dig github.com @<dns-server-ip>` when you do that ?

**Comment by OneBlue** [comment]
And also, what's the output of `ip a` ? I'd guess that the container just doesn't have a way to contact that ip address.
