### ISSUE TITLE
WSL displays "System cannot find the specified path."

### ISSUE THREAD

**Issue by LUXUS1** [microsoft/WSL#10161]
### Windows Version

Microsoft Windows [版本 10.0.19044.2728]

### WSL Version

System cannot find the specified path.

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I accidentally deleted the C:\Users\name\AppData\Local folder and when I typed "wsl" in the command line, it showed "The system cannot find the specified path." Restarting or turning off and on "Windows Subsystem for Linux" in Windows Features did not solve the problem. How can I solve the above problem? Thank you.

### Expected Behavior

How to solve the above problem, besides reinstalling the system, haha.

### Actual Behavior

How to solve the above problem, besides reinstalling the system？

**Comment by OneBlue** [comment]
Hi @LUXUS1. Sadly I don't think this will be easily recoverable. Distributions are stored in appdata/local by default and if you deleted that folder, there's no way to recover them.

One thing you could do would be to unregister them with wsl --unregister <distro> and install them again, but that won't recover your files unfortunately.
