### ISSUE TITLE
Ubuntu Crashing during installation : Processing fstab with mount -a failed

### ISSUE THREAD

**Issue by Nobunaji** [microsoft/WSL#10165]
I uninstalled ubuntu, disabled WSL Feature, restarted my computer then re-enabled it, restarted again.

Now i reinstalled ubuntu and once i launch it i get the following error code : 
```
Processing fstab with mount -a failed.
Failed to mount C:\, see dmesg for more details.
Failed to mount X:\, see dmesg for more details.

<3>WSL (51) ERROR: CreateProcessEntryCommon:370: getpwuid(0) failed 2
<3>WSL (51) ERROR: CreateProcessEntryCommon:374: getpwuid(0) failed 2
<3>WSL (51) ERROR: CreateProcessEntryCommon:577: execvpe /bin/sh failed 2
<3>WSL (51) ERROR: CreateProcessEntryCommon:586: Create process not expected to return
```

And it crashes.

What did i do wrong. It used to work before i uninstalled it.

**Comment by Nobunaji** [comment]
@OneBlue Hi, thank you for your help. I'm not sure i did this correctly. At the step where they say please reproduce the error, i opened ubuntu and made it crash, then once it crashed i pressed a key to generate the log. Not sure if this is how i was supposed to do it, but here you go :
[WslLogs-2023-06-07_09-05-56.zip](https://github.com/microsoft/WSL/files/11673594/WslLogs-2023-06-07_09-05-56.zip)

**Comment by OneBlue** [comment]
Thank you @Nobunaji. Based on the logs it looks like the issue comes from the fstab. Can you share the output of `cat /etc/fstab` ?

**Comment by Nobunaji** [comment]
@OneBlue I'm on Windows. I'm trying to install a WSL (Windows Subsystem for Linux). So i'm sorry i cannot do cat /etc/fstab since that file does not exist.

**Comment by OneBlue** [comment]
Interesting. If the distribution is corrupted and you can't access it, can you try to export it via `wsl --export ubuntu ubuntu.tar` and look at `/etc/fstab` inside that tar file ?

**Comment by Nobunaji** [comment]
@OneBlue /etc/fstab is non existent. I get a folder that looks like this :
.
-- /bin/
-- /dev/
-- /mnt/
-- /proc/
-- /run/
-- /sbin/
-- /sys/
-- /tmp/
-- /init

And yes i have a folder named "." at the root of my .tar. No idea if that's normal.

**Comment by OneBlue** [comment]
> @OneBlue /etc/fstab does not existent. I get a folder that looks like this : . -- /bin/ -- /dev/ -- /mnt/ -- /proc/ -- /run/ -- /sbin/ -- /sys/ -- /tmp/ -- /init
> 
> And yes i have a folder named "." at the root of my .tar. No idea if that's normal.

Hmm looking at the output it looks like there's not `/etc` folder, which explains the error you saw. Was this folder deleted by accident maybe ? 

Easiest way to fix this would be to back-up your distro .tar and re-create it via `wsl.exe --unregister <distro>` and `wsl --install <distro>`

**Comment by Nobunaji** [comment]
@OneBlue This worked. Thank you for your help.
