### ISSUE TITLE
how-to-repair-a-vhd-mounting-error? the tutorial not work at all!

### ISSUE THREAD

**Issue by ethever** [microsoft/WSL#10169]
### Windows Version

Microsoft Windows [Version 10.0.19044.2965]

### WSL Version

WSL version: 1.2.5.0 Kernel version: 5.15.90.1 WSLg version: 1.0.51 MSRDC version: 1.2.3770 Direct3D version: 1.608.2-61064218 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19044.2965

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Debian

### Other Software

non

### Repro Steps

visit and try https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error.

### Expected Behavior

should repaired

### Actual Behavior

PS F:\wsl\Debian> wsl --shutdown
PS F:\wsl\Debian> wsl.exe --mount .\ext4.vhdx --vhd --bare
The operation completed successfully.
PS F:\wsl\Debian> wsl.exe sudo e2fsck -f /dev/sdc
Failed to attach disk 'F:\wsl\Debian\ext4.vhdx' to WSL2: 另一个程序正在使用此文件，进程无法访问。
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020
PS F:\wsl\Debian>

### Diagnostic Logs

Why ?

**Comment by ethever** [comment]
PS F:\wsl\Debian> wsl.exe sudo e2fsck -f /dev/sdc
An error occurred mounting the distribution disk, it was mounted read-only as a fallback.
See recovery instructions on: https://aka.ms/wsldiskmountrecovery
e2fsck 1.46.2 (28-Feb-2021)
/dev/sdc is in use.
e2fsck: Cannot continue, aborting.

**Comment by ethever** [comment]
PS F:\wsl\Debian> wsl --shutdown
PS F:\wsl\Debian> wsl --mount .\ext4.vhdx --vhd --bare
The operation completed successfully.
PS F:\wsl\Debian>
PS F:\wsl\Debian> wsl sudo e2fsck -f /dev/sdb
Failed to attach disk 'F:\wsl\Debian\ext4.vhdx' to WSL2: 另一个程序正在使用此文件，进程无法访问。
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020
PS F:\wsl\Debian> wsl --shutdown
PS F:\wsl\Debian> wsl --mount .\ext4.vhdx --vhd --bare
The operation completed successfully.
PS F:\wsl\Debian> wsl sudo e2fsck -f /dev/sdc
Failed to attach disk 'F:\wsl\Debian\ext4.vhdx' to WSL2: 另一个程序正在使用此文件，进程无法访问。
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020

**Comment by ethever** [comment]
(base) root@DESKTOP-D2P8H7D:/mnt/f/wsl/Debian# lsblk
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda    8:0    0 363.3M  1 disk
sdb    8:16   0     3G  0 disk [SWAP]
sdc    8:32   0   256G  0 disk

**Comment by EngineerReversed** [comment]
Facing the same error and I can't access my `WSL2` terminal. 
Error:
```
Failed to attach disk 'D:\Ubuntu_20.04_LTS\ext4.vhdx' to WSL2: The requested operation could not be completed due to a file system limitation
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070299"
```

I had to `unregister` and install `ubuntu` distribution again to solve the problem. I lost all of my ssh keys(to access servers), vpn configurations etc. 
I don't know if it was because of the pre-release version of recent windows updates which broke it.

**Comment by elsaco** [comment]
@ethever the error message is obivous `Another program is using this file and the process cannot access it`. You already mounted Debian vhd and `wsl.exe sudo e2fsck -f /dev/sdc` is trying to mount it again. Is Debian your default distro?

You could use the `system` distro or another after mounting Debian's vhd. Here's sample run using the system distro:

```
PS E:\> wsl --mount e:\fedora\ext4.vhdx --vhd --bare
The operation completed successfully.
PS E:\> wsl --system -u root e2fsck -f /dev/sdc
e2fsck 1.46.5 (30-Dec-2021)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/sdc: 24973/67108864 files (0.3% non-contiguous), 4959752/268435456 blocks
```

Make sure you specify the root user otherwise you'll be greeted by:

```
PS E:\> wsl --system e2fsck -f /dev/sdc
e2fsck 1.46.5 (30-Dec-2021)
e2fsck: Permission denied while trying to open /dev/sdc
You must have r/w access to the filesystem or be root

```

**Comment by ethever** [comment]
> @ethever the error message is obivous `Another program is using this file and the process cannot access it`. You already mounted Debian vhd and `wsl.exe sudo e2fsck -f /dev/sdc` is trying to mount it again. Is Debian your default distro?
> 
> You could use the `system` distro or another after mounting Debian's vhd. Here's sample run using the system distro:
> 
> ```
> PS E:\> wsl --mount e:\fedora\ext4.vhdx --vhd --bare
> The operation completed successfully.
> PS E:\> wsl --system -u root e2fsck -f /dev/sdc
> e2fsck 1.46.5 (30-Dec-2021)
> Pass 1: Checking inodes, blocks, and sizes
> Pass 2: Checking directory structure
> Pass 3: Checking directory connectivity
> Pass 4: Checking reference counts
> Pass 5: Checking group summary information
> /dev/sdc: 24973/67108864 files (0.3% non-contiguous), 4959752/268435456 blocks
> ```
> 
> Make sure you specify the root user otherwise you'll be greeted by:
> 
> ```
> PS E:\> wsl --system e2fsck -f /dev/sdc
> e2fsck 1.46.5 (30-Dec-2021)
> e2fsck: Permission denied while trying to open /dev/sdc
> You must have r/w access to the filesystem or be root
> ```
Debian is my default distribution: 
```bash 
PS F:\wsl\Debian> wsl --list
Windows Subsystem for Linux Distributions:
Debian (Default)
Ubuntu
docker-desktop-data
docker-desktop
```

`wsl --system -u root e2fsck -f /dev/sdc` not work for the same error: 

``` bash
PS F:\wsl\Debian> wsl --shutdown
PS F:\wsl\Debian> wsl --list
Windows Subsystem for Linux Distributions:
Debian (Default)
Ubuntu
docker-desktop-data
docker-desktop
PS F:\wsl\Debian>
PS F:\wsl\Debian>
PS F:\wsl\Debian> wsl --mount .\ext4.vhdx --vhd --bare
The operation completed successfully.
PS F:\wsl\Debian> wsl --system -u root e2fsck -f /dev/sdc
Failed to attach disk 'F:\wsl\Debian\ext4.vhdx' to WSL2: 另一个程序正在使用此文件，进程无法访问。
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020
PS F:\wsl\Debian> 
```
But i try it using `Ubuntu` instread of `system` distri and it works: 

``` bash 
PS F:\wsl\Debian> wsl -d Ubuntu -u root e2fsck -f /dev/sdc
e2fsck 1.46.5 (30-Dec-2021)
/dev/sdc: recovering journal
Pass 1: Checking inodes, blocks, and sizes
Inode 501800 extent tree (at level 1) could be shorter.  Optimize<y>? yes

Inode 1056183 extent tree (at level 1) could be shorter.  Optimize<y>? yes
Inode 1955138 extent tree (at level 1) could be shorter.  Optimize<y>? yes

Inode 3313721 extent tree (at level 1) could be shorter.  Optimize<y>? yes
Inode 3349709 extent tree (at level 1) could be shorter.  Optimize<y>? yes
Pass 1E: Optimizing extent trees
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information

/dev/sdc: ***** FILE SYSTEM WAS MODIFIED *****
/dev/sdc: 3516340/16777216 files (0.2% non-contiguous), 67104763/67108864 blocks
```

**Comment by ethever** [comment]
> wsl --system -u root e2fsck -f /dev/sdc

Extremely appriciate this.

**Comment by rikrdo89** [comment]
This worked for me! thanks for posting this. I just would add that after e2fsck is completed successfully, unmount the vhd using `wsl.exe --unmount`  and you are ready to have your wsl2 working again.

**Comment by phocks** [comment]
Just thought I'd add my fix for this error, without losing data:

```
Failed to attach disk '\\?\C:\Ubuntu\ext4.vhdx' to WSL2: The requested operation could not be completed due to a file system limitation
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/0x80070299
```

The issue was with Windows File Compression. I copied the ext4.vhdx to a different drive/folder that didn't have Windows File Compression, removed the compression (right-click -> properties -> advanced -> compress contents to save space) then copied it back and restarted WSL2 and it worked.

Just in case this helps someone else.
