### ISSUE TITLE
Wrong store IDs for old Ubuntu releases

### ISSUE THREAD

**Issue by EduardGomezEscandell** [microsoft/WSL#10162]
### Windows Version

Microsoft Windows [Versión 10.0.22631.1830]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 18.04, Ubuntu 20.04

### Repro Steps

Store App IDs for Ubuntu 18.04 and 20.04 are outdated:

| Release | Currently | Should be |
|---------|-----------|-----------|
| Ubuntu 18.04 | 9N9TNGVNDL3Q | 9PNKSF5ZN4SW |
| Ubuntu 20.04 | 9N6SVWS3RX71 | 9MTTCL66CPXJ |

They point to the old `Ubuntu XX.XX on Windows`. The "PackageFamilyName" confirms this. They need be changed as well. The `*PackageUrl` properties are outdated as well.

### Expected Behavior

Install the right AppxPackage

### Actual Behavior

Installs the old AppxPackage

**Comment by craigloewen-msft** [comment]
Fixed here:
https://github.com/microsoft/WSL/pull/10176

**Comment by OneBlue** [comment]
Closing since the fix has been merged.
