### ISSUE TITLE
`wsl --install -d Debian` fails `Error Code: 0x80070520`

### ISSUE THREAD

**Issue by Athanasius** [microsoft/WSL#10179]
### Windows Version

Microsoft Windows 11 Pro [22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Distro Version

Debian

### Repro Steps

Trying out the Windows Store preview as per https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/#:~:text=There%20are%20two%20big%20reasons%20to,when%20getting%20the%20latest%20WSL%20updates.&text=There%20are%20two%20big,the%20latest%20WSL%20updates.&text=two%20big%20reasons%20to,when%20getting%20the%20latest

1. Installed WSL from the Windows Store.
2. Ran the `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all` command.
3. Rebooted for that to take effect.
4. Ran into https://github.com/microsoft/WSL/issues/9521
5. Toggled "Windows Subsystem for Linux" on in "Windows Features".
6. Rebooted for *that* to take effect.
7. Login as my non-Admin/Limited user.
8. Run a Powershell *as Administrator* (UAC prompt, password)
9. `wsl --list --online`, which includes a line `Debian                                 Debian GNU/Linux`
10. `wsl --install --distribution Debian` results in:
```powershell
PS C:\WINDOWS\system32> wsl --install --distribution Debian
Installing: Debian GNU/Linux
An error occurred during installation. Distribution Name: 'Debian GNU/Linux' Error Code: 0x80070520
PS C:\WINDOWS\system32>
```

### Expected Behavior

Debian distribution should be installed.

### Actual Behavior

The cited error.

**Comment by Athanasius** [comment]
After another reboot I tried this by *actually logging in as an Admin account* and running PowerShell, and the command worked.

So, WSL requires the current Windows session to be an Admin user ?  You can't just "Run as Administrator" ?

**Comment by Athanasius** [comment]
> Thank you for reporting this @Athanasius. I wonder if this a store issue. Can you try installing via:
> 
> ```
> wsl --install -d debian --web-download
> ```

Right now it will succeed even without `--web-download` because the system already has the distribution.  Checking `wsl --help` there only seems to be `wsl --unregister <Distribution>` (as per `--list`), but after that even `wsl --install -d Debian` quickly succeeds, presumably because the download has been cached.

Some websearching later I find https://petri.com/how-to-uninstall-and-reset-windows-subsystem-for-linux-distributions/ and remove 'Debian' from "Apps > Installed apps", and now:

```powershell
PS C:\WINDOWS\system32> wsl --install -d Debian
Debian GNU/Linux is already installed.
Launching Debian GNU/Linux...
```
```
Failed to attach disk 'C:\Users\Athan\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState\ext4.vhdx' to WSL2: The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/MountVhd/ERROR_FILE_NOT_FOUND
Press any key to continue...
```
So, that's only gotten it into an even worse state.

How do I make WSL actually forget about the distribution so I can even test if `--web-download` would have worked ?

**Comment by Athanasius** [comment]
Having gone through even more of a dance now.

1. Completely removed the path under Packages for 'TheDebianProject'.
2. `wsl --unregister Debian` **as Limited user** (all the last comment was under PowerShell > Run as Administrator).

This now appears to work.  So, either something has been fixed in the meantime... or it's just a consequence of this now not being a WSL clean system, with something left behind allowing it to work.

I don't have the time or resources to re-test this from scratch now.

**Comment by alex-aperia** [comment]
I get exactly same error when trying to install Ubuntu. 
Any updates on this topic ?

**Comment by natewaddoups** [comment]
I ran into the same error code when trying to install Ubuntu.

In my case, the error happened in a cmd window, but the same command succeeded in a PowerShell window.

 ¯\_(ツ)_/¯

**Comment by natewaddoups** [comment]
@OneBlue please consider reopening this ticket. The problem is still present, and the workaround instructions are no longer usable.

**Comment by romanwerpachowski** [comment]
Confirming that it doesn't work when I run Powershell as Admin, but works in User mode.

**Comment by GOKU900** [comment]
Works for me when I run Powershell in standard user mode, NOT with admin.

**Comment by Jim-Fan** [comment]
> Works for me when I run Powershell in standard user mode, NOT with admin.

Just so to let all of you know. This is the solution for me.

**Comment by JM-delatorre** [comment]
It worked for me running on PS without admin

**Comment by ray-dorai** [comment]
Had the same problem with installing Ubuntu WSL, worked out of admin as well.

**Comment by maxspahn** [comment]
Worked for me as well as non-admin user.

**Comment by dlenski** [comment]
Yet another +1 to https://github.com/microsoft/WSL/issues/10179#issuecomment-2373577452 and everyone else who points out that it _only_ works as a "normal" user, and not in a run-as-admin `cmd` or Terminal window.

**Comment by gliziakin** [comment]
wsl --install -d Ubuntu --web-download
worked for me.
