### ISSUE TITLE
Error code: Wsl/Service/CreateVm/ERROR_PATH_NOT_FOUND

### ISSUE THREAD

**Issue by MatousKundrik** [microsoft/WSL#10170]
### Windows Version

Microsoft Windows [Version 10.0.19045.3031]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Repro Steps

Unable to install WSL 2 distros. Can successfully install and access WSL 1 distro but attempting to update from 1 to 2 results in the following:
```
PS C:\Windows\system32> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         1
PS C:\Windows\system32> wsl --set-version Ubuntu 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
The system cannot find the path specified.
Error code: Wsl/Service/CreateVm/ERROR_PATH_NOT_FOUND
```

Attempting to install a WSL 2 distro directly results in the following:
```
PS C:\Windows\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.
PS C:\Windows\system32> wsl --install -d ubuntu
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 The system cannot find the path specified.

Press any key to continue...
```
I have tried installing various distributions both from the command line and from the Microsoft Store, all of which result in the same issue. Most relevant support I have found suggests ensuring Intel VT-x is enabled in BIOS (which I have verified to be the case) as well as enabling the correct Windows features, which I also believe I have done correctly.
![image](https://github.com/microsoft/WSL/assets/19365577/2feaf265-834b-42ba-b3be-957d6c9d3840)
The closest existing issue (https://github.com/microsoft/WSL/issues/9349) I was able to find suggests clearing out missing values from `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss` but that dosen't appear to be the problem in my case.
![image](https://github.com/microsoft/WSL/assets/19365577/1e499734-2336-499f-af59-0ee7857789ae)

This issue (https://github.com/microsoft/WSL/issues/6363) also appears similar, unfortunately I have no `.wslconfig` present and  making the suggested changes to the registry yielded no results.

### Expected Behavior

See Above

### Actual Behavior

See Above

**Comment by MatousKundrik** [comment]
[WslLogs-2023-06-07_17-57-29.zip](https://github.com/microsoft/WSL/files/11680094/WslLogs-2023-06-07_17-57-29.zip)

I have attached WSL logs while attempting to install a distro above, as suggested here: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs

**Comment by OneBlue** [comment]
Thank you for reporting this @MatousKundrik. Looking at the logs it looks like Hyper-V is in a bad state, which causes the VM to fail to start. 

Can you try to disable both Virtual machine platform and all hyper-v components, then reboot, re-enable them and reboot again ? 

I'd be curious to see if that will solve the issue.

**Comment by MatousKundrik** [comment]
> Thank you for reporting this @MatousKundrik. Looking at the logs it looks like Hyper-V is in a bad state, which causes the VM to fail to start.
> 
> Can you try to disable both Virtual machine platform and all hyper-v components, then reboot, re-enable them and reboot again ?
> 
> I'd be curious to see if that will solve the issue.

Thanks for the feedback, seems you're exactly right! WSL + Ubuntu 22.04.2 LTS is now working as expected! 😁 

For anyone else having the same issue, the exact steps I followed were:
- Toggle Hyper-V and Virtual Machine Platform **off** in Windows Features
- Restart PC allowing updates to be applied
- Toggle Hyper-V and Virtual Machine Platform **on** in Windows Features
- Restart PC allowing updates to be applied
- Reinstall WSL Distribution

[WslLogs-2023-06-08_01-30-00.zip](https://github.com/microsoft/WSL/files/11682891/WslLogs-2023-06-08_01-30-00.zip)
WSL logs are again attached above in case they prove useful.

I was at my wits end and about to do an in-place reinstall of Windows, glad this worked!
