### ISSUE TITLE
WSL2 Failure to start on Windows 11

### ISSUE THREAD

**Issue by teharris1** [microsoft/WSL#10187]
### Windows Version

Microsoft Windows [Version 10.0.22621.1778]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 16.04

### Repro Steps

I do not know how to repoduce on a different system. I have uninstalled LSW, Hyper-V, and WSL with no success. 

### Expected Behavior

WSL will start to a command prompt

### Actual Behavior

WSL hangs at this step: Adding 8388608k swap on /dev/sdb.  Priority:-2 extents:1 across:8388608k

Full debug log below.

### Diagnostic Logs

[WSL debug.txt](https://github.com/microsoft/WSL/files/11727895/WSL.debug.txt)
[WslLogs-2023-06-12_15-45-36.zip](https://github.com/microsoft/WSL/files/11727897/WslLogs-2023-06-12_15-45-36.zip)

**Comment by teharris1** [comment]
FYI, if I let the `wsl` command run a little longer I get this in the log:
`[   49.405592] hv_balloon: Max. dynamic memory size: 32646 MB`

**Comment by OneBlue** [comment]
Thank you for reporting this @teharris1. I'm not seeing any WSL logs in the zip file you shared. 

Can you try to run wsl --shutdown, then start the log collection and then reproduce the issue while the log collection is running ? 

Also, how are you starting WSL ?

**Comment by teharris1** [comment]
I have decided to reinstall win11 because this is not the only issue I am having with it. Very frustrating user experience with Win11. If it breaks again I will go back to win10.
