### ISSUE TITLE
WslService listed in Services as "ms:AppName"

### ISSUE THREAD

**Issue by Terrance** [microsoft/WSL#10182]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Repro Steps

Check the Services management console or Task Manager tab for WSL-related services.

(For context, occasionally WSL freezes on boot, with attempts to launch a distro console or run any wsl.exe commands just hanging.  A restart of the service seems to be the least destructive action to get things working again.)

### Expected Behavior

WslService would be listed with a sensible name.

### Actual Behavior

WslService uses "ms:AppName" and "ms:AppDescription" for its name and description respectively.  This makes it impossible to find (without knowing it's named this way) in the management console, and is only discoverable in Task Manager by process name.

![image](https://github.com/microsoft/WSL/assets/4025899/523498a9-cd0b-4e78-a227-8d79a3a38871)

**Comment by OneBlue** [comment]
Thanks for reporting this @Terrance. Unfortunately this is a known issue on Windows 10, but it's fixed on Windows 11. 

Upgrading to Windows 11 should resolve the problem.

**Comment by iamexe** [comment]
Solution: open PowerShell as Administrator.

Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\WslService -Name DisplayName -Value "WslService"
Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\WslService -Name ServiceName -Value "WslService"

Don't even have to restart (or install Windows 11..).

@Terrance
