### ISSUE TITLE
WSL stops working if "Authenticated Users" is removed from local "Users" group

### ISSUE THREAD

**Issue by tjnsn** [microsoft/WSL#10195]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

Remove "Authenticated Users" from the local users group and reboot.
Try to start wsl, it will fail to work.

The removal of "Authenticated Users" is typicaly done due to company security policies.

### Expected Behavior

wsl starting up normaly

### Actual Behavior

WSL failing to start with error:
No such interface supported
Error code: Wsl/0x80004002

but i suspect other errors may also show up depending on how far you got in the installation, i have seen other errors too.

### Diagnostic Logs

If logs is needed let me know.
but i think this issue should be easy to reproduce so perhaps logs is not needed.

**Comment by jcrben** [comment]
can you add the powershell commands you're using to add / remove "Authenticated Users" from the local users group? I've got the same error and want to try debugging it.

**Comment by fuxishuyuan** [comment]
Any solution? It is common in company.

**Comment by ysn2233** [comment]
Any solution? It is common in company.

**Comment by Reflyer823** [comment]
I've found a more perfect solution to this problem [here](https://github.com/microsoft/WSL/issues/9202#issuecomment-1711618332), much better than the one above, without having to modify your enterprise's security rules.
