### ISSUE TITLE
Git clone fails with Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by kquote03** [microsoft/WSL#10191]
### Windows Version

Microsoft Windows [Version 10.0.19044.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian 12 and Ubuntu 20.04

### Other Software

git version 2.39.2

### Repro Steps

Just try to clone a codeberg repo
`git clone https://codeberg.org/joostkremers/visual-fill-column.git`

### Expected Behavior

The repo gets cloned

### Actual Behavior

```
 GIT_CURL_VERBOSE=1 git clone https://codeberg.org/joostkremers/visual-fill-column.git --verbose
Cloning into 'visual-fill-column'...
21:27:28.721266 http.c:699              == Info: Couldn't find host codeberg.org in the (nil) file; using defaults
21:27:28.834167 http.c:699              == Info:   Trying 217.197.91.145:443...
21:27:28.963775 http.c:699              == Info: Connected to codeberg.org (217.197.91.145) port 443 (#0)
21:27:29.081604 http.c:699              == Info: found 420 certificates in /etc/ssl/certs
21:27:29.081677 http.c:699              == Info: GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
21:27:29.081706 http.c:699              == Info: ALPN: offers h2,http/1.1
21:27:29.090009 http.c:699              == Info: Recv failure: Connection reset by peer
21:27:29.090114 http.c:699              == Info: gnutls_handshake() failed: Error in the pull function.
21:27:29.090143 http.c:699              == Info: Closing connection 0
21:27:29.090167 http.c:699              == Info: Send failure: Broken pipe
fatal: unable to access 'https://codeberg.org/joostkremers/visual-fill-column.git/': Recv failure: Connection reset by peer
```

**Comment by kquote03** [comment]
I have set the MTU values for both my WiFi card and WSL to be the same, it's not the issue. I've also tried to update my network drivers, to no avail. And tried to disable the generation of /etc/resolv.conf and manually setting it to 8.8.8.8, but that didn't change as well. I made sure that all the necessary ssl libraries are installed.

**Comment by pmartincic** [comment]
I can not reproduce this. /logs

**Comment by kquote03** [comment]
> I can not reproduce this. /logs

I shutdown WSL, ran the script, started WSL, attempted the same git clone, and saved the logs

[WslLogs-2023-06-14_11-40-27.zip](https://github.com/microsoft/WSL/files/11742984/WslLogs-2023-06-14_11-40-27.zip)
