### ISSUE TITLE
SD Card (on PCIe reader) bare mount fails.

### ISSUE THREAD

**Issue by Penta0308** [microsoft/WSL#10198]
### Windows Version

Microsoft Windows [Version 10.0.22000.2057]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Realtek PCIE Cardreader (PCI\VEN_10EC&DEV_5209&SUBSYS_02321854&REV_01\4&4AF7531&0&00E8) (works well on Windows)
SD Card has only one FAT32 partition

`wsl --mount "\\.\PHYSICALDRIVE2" --bare`

### Expected Behavior

It should be mounted.

### Actual Behavior

`GET-CimInstance -query "SELECT * from Win32_DiskDrive"` gives me:
```
DeviceID           Caption                Partitions Size         Model
--------           -------                ---------- ----         -----
\\.\PHYSICALDRIVE0 CT500MX500SSD1         4          500105249280 CT500MX500...
\\.\PHYSICALDRIVE1 Crucial_CT250MX200SSD4 3          250056737280 Crucial_CT...
\\.\PHYSICALDRIVE2 SDHC Card              1          15924142080  SDHC Card
```

But when I run `wsl --mount "\\.\PHYSICALDRIVE2" --bare`,
```
The system cannot find the drive specified.
Error code: Wsl/Service/AttachDisk/0x8007000f
```
appears.
And my disk disappears on "This PC", but it is present on "Disk Management" with offline state and without a drive letter assigned.
I can't find the disk with `lsblk` in WSL.

### Diagnostic Logs

[WslLogs-2023-06-15_18-07-35.zip](https://github.com/microsoft/WSL/files/11755403/WslLogs-2023-06-15_18-07-35.zip)

```
> wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                             DeviceID            InterfaceType  MediaLoaded  MediaType              Model                   Name                Partitions
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}        \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media  CT500MX500SSD1          \\.\PHYSICALDRIVE0  4
              {3, 4, 10}    {"Ra
[WslLogs-2023-06-15_18-07-35.zip](https://github.com/microsoft/WSL/files/11755396/WslLogs-2023-06-15_18-07-35.zip)
ndom Access", "Supports Writing", "SMART Notification"}        \\.\PHYSICALDRIVE1  IDE            TRUE         Fixed hard disk media  Crucial_CT250MX200SSD4  \\.\PHYSICALDRIVE1  3
              {3, 4, 7}     {"Random Access", "Supports Writing", "Supports Removable Media"}  \\.\PHYSICALDRIVE2                 TRUE         Removable Media        SDHC Card               \\.\PHYSICALDRIVE2  1

```

**Comment by OneBlue** [comment]
Unfortunately this is by design because wsl --mount doesn't support sdcards at the moment.

**Comment by penenkel** [comment]
Can we maybe reopen this as a feature request? So far I have not found any workaround for this. With USB based readers we have usbipd as a workaround, but for PCIe based readers (e.g. the build-in readers in most Dell laptops) that obviously does not help.
