### ISSUE TITLE
printf '\033[3J' escape code does not clear scrollback 

### ISSUE THREAD

**Issue by spiffomatic64** [Microsoft/WSL#1020]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  Running /usr/bin/clear && printf '\033[3J', clears the scrollback if the scrollback is short enough, but after running a number of other commands, stops working
- Expected results
  The screen should clear, and the scrollback should be wiped
- Actual results (with terminal output if applicable)
  The screen is cleared, but the scollback is not wiped
- Your Windows build number
  14905
- Steps / commands required to reproduce the error
  for i in `seq 1 1000`;do echo yay;done;/usr/bin/clear && printf '\033[3J'
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by zadjii-msft** [comment]
We don't support using `CSI 3 J` to clear the screen buffer currently. IIRC, `3J` is supposed to also clear the scrollback of *nix terminals, which we don't really have in the traditional sense. 

We do support `CSI 2 J` (`\033[2J`) however, which will also clear the screen

**Comment by spiffomatic64** [comment]
ah ok, thanks :) are there any plans to support CSI 3 J? Worth throwing on the user voice page?

**Comment by zadjii-msft** [comment]
@spiffomatic64 See my comment in the issue that I just linked to this one, but basically, no, we're not planning on supporting it in the next release. 

I'd say in general, this GH repo is the best place for reporting issues. I personally don't read the uservoice very often, but I'm on here daily.

**Comment by TuxVinyards** [comment]
This workaround deals will sort all existing Linux scripts that make calls to `printf` and straight forward use of the escape sequence `\033c`.  ie `printf "\033c"` or  `printf "\033c \n \n  Text text \n text etc"`

The `clear` command in WSL seems to route through to Windows and follows normal Window behaviour. The same as `printf "\033c"`. Whereas in native Linux, the `clear` command is supported by the ncurses library and only clears the current viewing area.  

When a Bash executes a instruction, it will first look in the script for functions of that name before going externally.  We can use this feature to trap the `printf` call and to modify it's behaviour. This text should be added to the start of a script:  

[wsl-printf.txt](https://github.com/Microsoft/BashOnWindows/files/611680/wsl-printf.txt)

If someone can code the recursive loops to check for multiple or buried screen clear requests within a `printf` request, then I am guessing that a proper fix could be done. Slightly out of my depth as to whether this could be added to something like .bashrc ??  But something similar to this should do-able, I would have thought.  Anyone ... ?

**Comment by zadjii-msft** [comment]
@TuxVinyards Could you open a new issue regarding "ESC c" not working? I'd prefer if we not pollute threads with multiple separate problems.

For the record, it looks like we don't offer support for \033c at the moment either, but we do support DECSTR - SoftReset, or at least the subset of features covered in DECSTR that we otherwise support.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by zjturner** [comment]
@bitcrazed 

1. It is not fixed in recent Win10 builds.

2. The Windows console can do this just fine.  Type `cls` in the Windows console and it works fine.  So the console does in fact support this.

Based on that, can we please re-open this?

**Comment by zadjii-msft** [comment]
I'm actually very certain I added support for clearing the scrollback in either Fall Creators or the April Update. If it's still not working, please open a new issue on [microsoft/console](https://github.com/microsoft/console). We're not tracking console issues on this repo anymore.
