### ISSUE TITLE
wsl.exe hang after windows update

### ISSUE THREAD

**Issue by crgarcia12** [microsoft/WSL#10209]
### Windows Version

Microsoft Windows [Version 10.0.22621.1848]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22

### Repro Steps

Update windows to the latest version. WSL hangs, even `wsl -l` hangs

Disabled Hyper-V
Uninstalled WSL + reinstalled wsl
500GB of free disk 
CPU < 20% - Memory <30%

```
sc queryex LxssManager

SERVICE_NAME: LxssManager
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 0
        FLAGS              :
```

All wsl commands exept `wsl --version` hang. Trying to open Ubuntu from anywhere (Start menu, PowerShell, etc) hang with a black screen. 
No error message in the System Event Viewer

If I manually start LxssManager, nothing changes. I also tried killing all wsl* tasks and services

Here are the logs:
[WslLogs-2023-06-17_02-43-22.zip](https://github.com/microsoft/WSL/files/11777567/WslLogs-2023-06-17_02-43-22.zip)

### Expected Behavior

WSL to not to hang :)

### Actual Behavior

all wsl commands hang without error message

### Diagnostic Logs

https://github.com/microsoft/WSL/files/11777567/WslLogs-2023-06-17_02-43-22.zip

**Comment by bin-emanuele** [comment]
Hi, have the same identical issue: any wsl command hangs. Did you have any luck finding a solution?

**Comment by bin-emanuele** [comment]
UPDATE: After some deep googling I've found the following command to restart WSL, that fixes the problem (for the moment at least)
`tasklist /svc /fi "imagename eq svchost.exe" | findstr LxssManager`

**Comment by crgarcia12** [comment]
I found the issue. No clue how it is related, but it fixed the problem.
I had a network-mounted file system failing due to no connection. I was not usinging it or referencing it in any form from my WSL, but it was making it hanging (even for an hour).

**Comment by SKART1** [comment]
In my case it was about CFG feature on my windows installation

Followed this [solution](https://superuser.com/a/1736446) from question on [superuser](https://superuser.com/questions/1736443/wsl-2-installing-linux-failed-error-code-0x80370114)


and finally wsl returned back to work
