### ISSUE TITLE
Can't load the iSCSI modules - USB Storage Device Access on WSL2

### ISSUE THREAD

**Issue by piggy2011** [microsoft/WSL#10203]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Kali 2023.2

### Repro Steps

I follow the instructions according to [https://github.com/jovton/USB-Storage-on-WSL2/blob/master/README.md](url) but modules can't be loaded after executing the command "modprobe". Here are the messages.

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v libiscsi
modprobe: FATAL: Module libiscsi not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v scsi_transport_iscsi
modprobe: FATAL: Module scsi_transport_iscsi not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v iscsi_tcp
modprobe: FATAL: Module iscsi_tcp not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v libiscsi_tcp
[sudo] password for sherman:
modprobe: FATAL: Module libiscsi_tcp not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2

I check the directory /lib/modules and find that there isn't the directory "5.15.90.1-microsoft-standard-WSL2" under /lib/modules. However, the kernel version is "5.15.90.1-microsoft-standard-WSL2" . I don't know why there is no 'uname -r' directory under /lib/modules.

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ uname -r
5.15.90.1-microsoft-standard-WSL2

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ ls -l /lib/modules
total 8
drwxr-xr-x 3 root root 4096 Jun 15 20:51 5.15.90.1+
drwxr-xr-x 3 root root 4096 Jun 14 23:23 5.15.90.1-microsoft-standard-WSL2+

If I create a softlink directory  "5.15.90.1-microsoft-standard-WSL2" under /lib/modules, there are another error messages when loading /lib/modules.

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo ln -s /lib/modules/5.15.90.1-microsoft-standard-WSL2+ /lib/modules/5.15.90.1-microsoft-standard-WSL2

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ ls -l /lib/modules
total 8
drwxr-xr-x 3 root root 4096 Jun 15 20:51 5.15.90.1+
lrwxrwxrwx 1 root root   47 Jun 15 22:43 5.15.90.1-microsoft-standard-WSL2 -> /lib/modules/5.15.90.1-microsoft-standard-WSL2+
drwxr-xr-x 3 root root 4096 Jun 14 23:23 5.15.90.1-microsoft-standard-WSL2+

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v libiscsi
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x556d9ee03370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/scsi_transport_iscsi.ko error=No such file or directory
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x556d9ee03370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/scsi_transport_iscsi.ko error=No such file or directory
insmod /lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi.ko
modprobe: ERROR: could not insert 'libiscsi': Unknown symbol in module, or unknown parameter (see dmesg)

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v libiscsi
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x5642de5cd370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/scsi_transport_iscsi.ko error=No such file or directory
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x5642de5cd370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/scsi_transport_iscsi.ko error=No such file or directory
insmod /lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi.ko
modprobe: ERROR: could not insert 'libiscsi': Unknown symbol in module, or unknown parameter (see dmesg)

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v scsi_transport_iscsi
insmod /lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/scsi_transport_iscsi.ko
modprobe: ERROR: could not insert 'scsi_transport_iscsi': Unknown symbol in module, or unknown parameter (see dmesg)

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v iscsi_tcp
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x560b67fb0370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi_tcp.ko error=No such file or directory
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x560b67fb0370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi_tcp.ko error=No such file or directory
insmod /lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/iscsi_tcp.ko
modprobe: ERROR: could not insert 'iscsi_tcp': Unknown symbol in module, or unknown parameter (see dmesg)

┌──(sherman㉿LAPTOP-FPRQU4NE)-[~]
└─$ sudo modprobe -v libiscsi_tcp
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x555c78e28370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi.ko error=No such file or directory
modprobe: ERROR: ../libkmod/libkmod-module.c:191 kmod_module_parse_depline() ctx=0x555c78e28370 path=/lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi.ko error=No such file or directory
insmod /lib/modules/5.15.90.1-microsoft-standard-WSL2/kernel/drivers/scsi/libiscsi_tcp.ko
modprobe: ERROR: could not insert 'libiscsi_tcp': Unknown symbol in module, or unknown parameter (see dmesg)

### Expected Behavior

Load the iSCSI modules successfully.

### Actual Behavior

Can't load the iSCSI modules after ompiling and installing kernel modules&iSCSI modules.

**Comment by OneBlue** [comment]
Thank you for reporting this @piggy2011. WSL2 doesn't support kernel modules so modprobe's output is expected. 

To get the modules you need, you can set them as `=y` in your kernel config so they're built-in (if you do that you don't need to load them as modules).
