### ISSUE TITLE
WSL cannot access port forwarded on Windows 10

### ISSUE THREAD

**Issue by sindrom91** [microsoft/WSL#10206]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

OpenSUSE 15.4

### Repro Steps

Run some kind of server on Windows on loopback address which is not 127.0.0.1, for example:
`python3.exe -m http.server -b 127.128.0.11 11224`

Forward that address and port to localhost:
`netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=11224 connectaddress=127.128.0.11 connectport=11224`

Try to access the forwarded port from Windows, for example:
`wget localhost:11224` (this works for me)

Try accessing that port from WSL:
`wget ${HOST}.local:11224` (this doesn't work for me, connection times out)

Note that if I run the server directly on `127.0.0.1:11224`, it works correctly.

### Expected Behavior

I expected to be able to access the forwarded port.

### Actual Behavior

I get connection timeout.

**Comment by pmartincic** [comment]
If I'm reading this correctly this is by design. On ipv4 only binds on 127.0.0.1 or 0.0.0.0 have port forwarding.

**Comment by sindrom91** [comment]
I see, thanks for the feedback. I thought I could work around this with forwarding.
