### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/CreateVm/WSL_E_CUSTOM_KERNEL_NOT_FOUND

### ISSUE THREAD

**Issue by piggy2011** [microsoft/WSL#10210]
### Windows Version

Microsoft Windows [Version 10.0.22621.1702]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

kali-linux 2023.2

### Repro Steps

WSL2 bash session couldn't open by .configwsl. here are the message.

```
PS C:\WINDOWS\system32> wsl
The custom kernel specified in C:\Users\Sherman\.wslconfig was not found: 'C:\Uers\Sherman\bzImage'.
Error code: Wsl/Service/CreateInstance/CreateVm/WSL_E_CUSTOM_KERNEL_NOT_FOUND
PS C:\WINDOWS\system32> 
```

The content of .wslconfig is as below

```
[wsl2]
kernel=C:\\Uers\\Sherman\\bzImage
swap=0
localhostForwarding=true
```

I have confirmed that kernel image file is located under the defined path. 

```
PS C:\WINDOWS\system32> dir C:\Users\Sherman\


    Directory: C:\Users\Sherman


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/6/16     19:08                .ms-ad
d-r---         2023/6/16      9:45                Contacts
d-r---         2023/6/16      9:45                Desktop
d-r---         2023/6/17     21:30                Documents
d-r---         2023/6/17     20:14                Downloads
d-r---         2023/6/16      9:45                Favorites
d-r---         2023/6/16      9:45                Links
d-r---         2023/6/16      9:45                Music
dar--l         2023/6/17     21:46                OneDrive
d-r---         2023/6/16      9:45                Pictures
d-r---         2023/6/16      9:45                Saved Games
d-r---         2023/6/16     17:21                Searches
d-r---         2023/6/16     17:27                Videos
-a----         2023/6/17     21:39             75 .wslconfig
-a----         2023/6/17     19:57       10631136 bzImage


PS C:\WINDOWS\system32>
```

### Expected Behavior

Open WSL2 bash session successfully.

### Actual Behavior

It seems that the image file is not recognized.

Error code: Wsl/Service/CreateInstance/CreateVm/WSL_E_CUSTOM_KERNEL_NOT_FOUND

**Comment by sarim** [comment]
![image](https://github.com/microsoft/WSL/assets/1235888/41ac3e90-a4d8-4d2c-a2a7-2575b66cc542)
check the typo :P

**Comment by piggy2011** [comment]
> ![image](https://user-images.githubusercontent.com/1235888/246619947-41ac3e90-a4d8-4d2c-a2a7-2575b66cc542.png) check the typo :P

Hi, thanks a lot for your remind. It is typo error in .wslconfig file. The problem is solved after correcting the typo.
