### ISSUE TITLE
WSL and Linux related commands not working

### ISSUE THREAD

**Issue by BL1Z33** [microsoft/WSL#10211]
### Windows Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

Check the Diagnostic Logs

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

1. Open cmd as admin
2. Type wsl --install (or wsl --install -d Ubuntu)

### Expected Behavior

I was expecting for WSL to install successfully.

### Actual Behavior

This is what happened:
![image](https://github.com/microsoft/WSL/assets/134890107/ac3b3a65-6b50-4770-a84a-bc367c0c45c4)

This error also shown when trying to run Ubuntu:
![image](https://github.com/microsoft/WSL/assets/134890107/018a9db7-d4d9-490c-a8b5-fbd9e357d6c7)

### Diagnostic Logs

Some commands didn't work, so the ones that aren't filled in didn't work.

**Comment by DavidMartynWood** [comment]
You need to add the windows subsystem for Linux feature in windows. Go to the start menu, and search "add feature" and enable it from there

**Comment by BL1Z33** [comment]
This is what comes up: 
![image](https://github.com/microsoft/WSL/assets/134890107/1729af3b-7783-4891-9587-84f0c18387f8)

**Comment by Jrograms** [comment]
Try fixing the blank features panel by opening a run box and entering services.msc, going down to Windows Modules Installer and changing its startup type to Automatic and clicking start. Then navigate to the panel again and make sure Windows Subsystem for Linux and Virtual Machine Platforms are enabled
