### ISSUE TITLE
Bump version to 2.0

### ISSUE THREAD

**Issue by kodfodrasz** [microsoft/WSL#10217]
The versioning is very confusing right now.

With the recent release 1.1.3 https://github.com/microsoft/WSL/releases/tag/1.1.3 it was really confusing to for people who do not follow the project on a day to day basis, just see news/marketing pieces about WSL, WSL2, and releases.

The .Net project finally cleared up its versioning mess. I think the situation for WSL is far simpler, and it would make communication more straightforward, if version 2.x+ would simply mean WSL2.

**Comment by benhillis** [comment]
Agreed. We will be bumping our version number to 2 fairly soon.
