### ISSUE TITLE
Can't Change from WSL1 to WSL2

### ISSUE THREAD

**Issue by LFL38** [microsoft/WSL#10215]
### Windows Version

Microsoft Windows [Version 10.0.19045.3086]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Latest version of Kali Linux

### Repro Steps

No Idea

### Expected Behavior

I was expecting for it to change the WSL version to 2 instead of giving me "Error: 0x80041002".

### Actual Behavior

These past couple of days I've bene trying to install Kali Linux on Windows 10 using WSL. However, whatever I do I just get the same error: Error: 0x80041002.
I've done some research on what to do and here's the full list of what I've done so far:

- Clearing Lxss registry key.
- Restarting Lxss service.
- Uninstall and reinstalling wsl.
- Uninstalling any program that makes another internet adapter.
- Removed every unwanted network adapter from device manager.
- Disabled my anti virus.
- Installed WSL from MS Store.
- Installed WSL from https://aka.ms/wsl2kernel.
- Checked for windows updates.
- Enabled "Receive updates for other Microsoft products when you update Windows".
- Removed any file mentioning "WSL".

Commands:

- net stop winmgmt
- ren %windir%\System32\wbem\Repository Repository.old
- winmgmt /resetrepository
- net start winmgmt
- dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /quiet
- dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /quiet
- wsl --set-default-version 2
- wsl --set-version kali-linux 2
- wsl --unregister kali-linux
- wsl --install kali-linux
- wsl --set-default-version 2
- wsl --set-version kali-linux 2
- wsl --shutdown
- wsl --start
- wsl --restart
- wsl --unregister --all
- wsl --install --web
- net stop LxssManager
- net start LxssManager
- netsh winsock reset
- netsh int ip reset
- wsl --update
- wsl --shutdown
- sc delete LxssManager
- PowerShell -ExecutionPolicy Unrestricted -Command "& {$manifest = (Get-AppxPackage -Name Microsoft.WSL).InstallLocation + '\AppxManifest.xml' ; Add-AppxPackage -DisableDevelopmentMode -Register $manifest}"

Only thing working so far is doing "wsl --set-version kali-linux 1" but that doesn't allow me to use xrdp (Can't find ip  in "ip add") nor winkex.

**Comment by Jrograms** [comment]
How you tried restarting the Virtual Machine feature when you disabled the WSL feature?
