### ISSUE TITLE
After updating to 1.3.11.0, msrdc.exe starts and then crashes incessantly, taking control of window focus

### ISSUE THREAD

**Issue by dziban303** [microsoft/WSL#10223]
### Windows Version

Microsoft Windows [Version 10.0.19045.3086]

### WSL Version

1.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.2-2

### Distro Version

Ubuntu 20.04.6 LTS

### Repro Steps

wsl --terminate Ubuntu
wsl --update --pre-release

### Expected Behavior

Normal functionality

### Actual Behavior

After updating to WSL v1.3.11.0, something would begin rapidly taking over window focus, resulting in the active window losing then regaining focus twice per second. I rebooted the machine but the behavior continued. It seems to have been msrdc.exe (v1.2.4240) which was starting, then immediately crashing, over and over. Running `wsl --terminate Ubuntu` would stop it for anywhere from 15 seconds to a few minutes, then it would start again. The computer was otherwise totally unusable, so I was forced to take ownership of `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.3.11.0_x64__8wekyb3d8bbwe\msrdc.exe` so that I could delete it. Initially I tried to rename it, but that kept demanding permission from my own user account; I couldn't delete it to recycle bin for the same reason, but it did let me shift-delete. 

It was then that I noticed over 7000 etl files in `C:\Users\dziba\AppData\Local\Temp\DiagOutputDir\RdClientAutoTrace`, over 45GB of them, all but four of them generated in the last hour.

Unfortunately I can't recreate the problem now for Feedback Hub because the offending msrdc.exe is deleted. I'm not sure where to go from here. I've submitted a bug report in Feedback Hub with one of the etl files attached

### Diagnostic Logs

[Feedback Hub](https://aka.ms/AAl88n0)

**Comment by chenxi050402** [comment]
same issue

**Comment by pmartincic** [comment]
This sounds like an issue for https://github.com/microsoft/wslg, I'd refile over there according to their template and instructions.
