### ISSUE TITLE
wsl: Unknown key 'wsl2.locahostForwarding' in C:\Users\psmi045\.wslconfig:7

### ISSUE THREAD

**Issue by psmith1303** [microsoft/WSL#10225]
### Windows Version

Version 10.0.19044.2846

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian GNU/Linux 12

### Other Software

GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2023-02-27

### Repro Steps

Launching WSL.EXE generates an error message:

`wsl: Unknown key 'wsl2.locahostForwarding' in C:\Users\psmi045\.wslconfig:7`

### Expected Behavior

There should be no error message

### Actual Behavior

When I launch WSL.EXE, either from a CMD or in Windows Terminal, there is a long wait before the following error message:

`wsl: Unknown key 'wsl2.locahostForwarding' in C:\Users\psmi045\.wslconfig:7`

My .wslconfig is: 

```
[wsl2]
memory=6GB # Limits VM memory in WSL 2 to 6 GB
processors=2 # Makes the WSL 2 VM use two virtual processors
swap=0
locahostForwarding=true
```
Everything else works as expected.

Commenting out the last line (`localhostForwarding`), removes the delay and the error message. But then, when I run `emacs` the status bar then says `WARN:COPY MODE`.

**Comment by 0xbadfca11** [comment]
Has misspelling.

**Comment by psmith1303** [comment]
Doh! My dyslexia got the better of me. Thank you for letting me know.
