### ISSUE TITLE
On the Conflict between VM and WSL in Hypervisorlaunchtype Settings

### ISSUE THREAD

**Issue by Burgerd4sh** [microsoft/WSL#10229]
### Windows Version

Microsoft Windows [版本 10.0.19045.3086]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

If I set the hypervisorlaunchtype to auto, WSL can run but VMware cannot run my Win 11 virtual machine and report my platform does not support virtualized amd-v/rvi.
If I set the hypervisorlaunchtype to off, my Win 11 virtual machine can run but WSL can't.

Is this normal？

### Expected Behavior

After I set the hypervisorlaunchtype to an option that can run both wsl and VMware simultaneously.

### Actual Behavior

As mentioned above.

**Comment by 0xbadfca11** [comment]
Yes.
https://docs.vmware.com/en/VMware-Workstation-Player-for-Windows/17.0/com.vmware.player.win.using.doc/GUID-778DD0ED-6FC9-415F-B071-0CEC127BE719.html
