### ISSUE TITLE
Error code: Wsl/InstallDistro/E_UNEXPECTED - Catastrophic failure

### ISSUE THREAD

**Issue by ronyshaji** [microsoft/WSL#10222]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I am facing an issue with installation of Ubuntu 20.04 in my wsl. I have earlier installed WSL without any issues on my PC and was running fine with ROS1 and ROS2. But when i tried to uninstall a python verison, it show how corrupted the ubuntu. so i unregistered the older version. And now trying to install new one. But i doubt that the old files are still in my system as I can see the older version of ubuntu in my program and I am not an admin of the PC. But i have admin rights.

What I did was as follows: 

`wsl --update --web-download`

I used --web-download as without arguments was not working.

Then i tried to run the following command: 

`wsl.exe --install Ubuntu-20.04`

and got the error as : >> 

```
Installing: Ubuntu 20.04 LTS
Ubuntu 20.04 LTS has been installed.
Catastrophic failure
Error code: Wsl/InstallDistro/E_UNEXPECTED
```

What may be reason and how can I install Ubuntu 20.04 ?

I have already turn on:
```
windows subsystem for linux
virtual environment
```

![image](https://github.com/microsoft/WSL/assets/104928271/abb988a3-a080-497c-b59b-c31cc72c3b03)

Update:

Based on some research, i have tried:
`wsl.exe --install Ubuntu-20.04 --web-download`

It downloaded the ubuntu and unfortunately another error poped up as shown below:

![image](https://github.com/microsoft/WSL/assets/104928271/d212de38-1169-4056-bdbf-08d1423f26b5)

### Expected Behavior

Install Ubuntu 20.04

### Actual Behavior

getting error:

```
Ubuntu 20.04 LTS has been installed.
Catastrophic failure
Error code: Wsl/InstallDistro/E_UNEXPECTED
```

**Comment by ronyshaji** [comment]
@OneBlue Do you have any feedback on this as I saw another incomplete issue here?

**Comment by OneBlue** [comment]
Interesting. It looks like the ubuntu application is in a bad state.  Can you try to uninstall it and then run wsl --install again ?

**Comment by ronyshaji** [comment]
@OneBlue But in the wsl list, it is showing like this......

![image](https://github.com/microsoft/WSL/assets/104928271/1a6561ea-3780-49f0-af8a-f11f6bcf6cea)


and when i try to run the ubuntu 2004.exe i get the following error......

![image](https://github.com/microsoft/WSL/assets/104928271/c91dc89b-7b7e-417e-8f24-8bcafc82da94)

**Comment by OneBlue** [comment]
@ronyshaji: I'm suggesting to remove the ubuntu application, not the WSL distribution.

You can do that with (elevated powershell): 
```
Get-AppxPackage CanonicalGroupLimited.Ubuntu20.04LTS -AllUsers | Remove-AppxPackage
```

**Comment by ronyshaji** [comment]
@OneBlue It looks like the windowsApp folder is messed up with many installations....

![image](https://github.com/microsoft/WSL/assets/104928271/8484af8d-1195-4502-b5d5-cdd71e5830e4)


and i try to remove it using `Get-AppxPackage CanonicalGroupLimited.Ubuntu20.04LTS -AllUsers | Remove-AppxPackage`  an error is coming up in the powershell.......

![image](https://github.com/microsoft/WSL/assets/104928271/194f0cc6-960a-4d2d-ac57-2a3beb9deb3d)

**Comment by OneBlue** [comment]
I see. Unfortunately it looks like your machine is just in a bad state. Sadly I think you might to repair / reinstall Windows to solve this. 

Closing since this is not a WSL issue.

**Comment by pyorot** [comment]
I mean when your error message is `E_UNEXPECTED`, you can't just say ~~perchance~~ reinstall Windows lmao

I get messages like that from Appx all the time; it's not exactly known for its robustness
