### ISSUE TITLE
<3>WSL (366) ERROR: CreateProcessEntryCommon:357: getpwnam(volke) failed 0 <3>WSL (407) ERROR: CreateProcessEntryCommon:357: getpwnam(volke) failed 0 The default user in your distro seems to be root. Please configure an ordinary default user In Zeile:21 Zeichen:5 +     throw "The default user in your distro seems to be root. Please c ..

### ISSUE THREAD

**Issue by vschwoerer** [microsoft/WSL#10221]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vschwoerer** [comment]
i install on windows 11 docker for desktop. When  i will install ddev with C:\Users\volke> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
PS C:\Users\volke> iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ddev/ddev/master/scripts/install_ddev_wsl2_docker_inside.ps1'))

i get the message <3>WSL (366) ERROR: CreateProcessEntryCommon:357: getpwnam(volke) failed 0
<3>WSL (407) ERROR: CreateProcessEntryCommon:357: getpwnam(volke) failed 0
The default user in your distro seems to be root. Please configure an ordinary default user
In Zeile:21 Zeichen:5
+     throw "The default user in your distro seems to be root. Please c

i try to change etc/wsl with 
[user]
default=volker 
and i restart.

**Comment by Hassanzhao** [comment]
Have the same truble.
