### ISSUE TITLE
Updating from an unknown version of WSL?

### ISSUE THREAD

**Issue by Makeshift** [microsoft/WSL#10236]
### Windows Version

Microsoft Windows [Version 10.0.22000.1219]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

(This is less a bug report and more a support request, but treating the lack of direction as a bug may assist others with similar issues)

When doing research in an attempt to combat #8696 (which has been plaguing me for a while), I attempted to follow some of the debugging steps listed in that thread. I then realised that I'm running a woefully out of date kernel version (which WSL will not update to any newer) and my WSL install is so old that it doesn't even have the `--version` argument.

I initially installed WSL via installing the [Ubuntu](https://www.microsoft.com/store/productId/9PDXGNCFSCZV) package from the Microsoft Store. Opening this page gives me an 'update' option, but it does literally nothing when I click it. This being the Microsoft store, it doesn't make an attempt at showing me an error to Google either, which is rather frustrating.

Running `wsl --update` tells me I have the latest version of the kernel at 5.10.102.1. I can see that there is a [WSL](https://www.microsoft.com/store/productId/9P9TQF7MRM4R) store page, but I'm reluctant to install it in case it breaks my (working, if flawed) installation.

Trying to install the [Linux kernel update package](https://learn.microsoft.com/en-gb/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package) tells me a later version of the Windows Subsystem for Linux Update is already installed. Opening the installer from the releases in this repository prompts me to install WSL, but again I fear installing WSL over an existing version that the installer doesn't recognise may break my working installation, so I was hoping for some support around that. There are no Windows updates available to my system.

Is there an upgrade path I can safely follow here, or any way to work out my installed WSL version without the `--version` arg?

### Expected Behavior

WSL should be updateable to the latest version.

### Actual Behavior

WSL claims that it is up to date, contrary to popular opinion, and the store does not fill me with confidence.

**Comment by OneBlue** [comment]
Thanks for reporting this @Makeshift. Upgrading to Store WSL will not change anything to the distros have installed (you can upgrade and downgrade and the distros will stay).

I recommend trying out store WSL to see if that solves the issue for you.
