### ISSUE TITLE
docker oracle cannot connect in wsl

### ISSUE THREAD

**Issue by duhuangwen** [microsoft/WSL#10240]
### Windows Version

Microsoft Windows [版本 10.0.22621.1848]

### WSL Version

WSL 版本： 1.1.3.0 
内核版本： 5.15.90.1 
WSLg 版本： 1.0.49 
MSRDC 版本： 1.2.3770 
Direct3D 版本： 1.608.2-61064218 
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp 
Windows版本： 10.0.22621.1848

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Oracle Linux Server release 7.9

### Other Software

Docker version 23.0.0, build e92dd87
Docker Compose version v2.16.0
openssh-server,the port is 822,then I can use ssh client connect oracle linux 7.9

### Repro Steps

docker pull jaspeen/oracle-11g

mkdir ~/docker/oracle/{install,dpdump} -p

vi ~/docker/docker-compose.yml

add  content :

version: "3.5"
services:       
  oracle:
    #https://github.com/jaspeen/oracle-11g
    #https://blog.csdn.net/qq_39316391/article/details/100542751
    image: jaspeen/oracle-11g:latest
    container_name: oracle
    volumes:
      - ~/docker/oracle/install:/install
      - ~/docker/oracle/dpdump:/opt/oracle/dpdump
    ports:
      - 1521:1521
    privileged: true

upload linux.x64_11gR2_database_1of2.zip &&linux.x64_11gR2_database_2of2.zip to  ~/docker/oracle/install

cd  ~/docker/oracle/install

unzip "*.zip"

docker-compose -f ~/docker/docker-compose.yml up -d oracle

docker logs -f oracle

docker exec -it oracle /bin/bash

su - oracle

sqlplus / as sysdba

alter user scott account unlock;

commit;

conn scott/tiger

### Expected Behavior

use plsql developer can connect oracle service

### Actual Behavior

the same steps in vmware ,use plsql developer can connect to the oracle service.
but wsl can not !
docker redis and docker mysql can connect ,only docker oracle cannot

### Diagnostic Logs

IO 错误: The Network Adapter could not establish the connection.

**Comment by OneBlue** [comment]
This doesn't look like a WSL issue, but most likely a configuration / networking issue. Closing

**Comment by duhuangwen** [comment]
> This doesn't look like a WSL issue, but most likely a configuration / networking issue. Closing

@OneBlue If it's a network configuration issue, why can Redis and MySQL connect successfully? The same steps work fine in the VMware virtual machine, but it doesn't work when using WSL.
