### ISSUE TITLE
wsl2 start is too slowly,about 90s . 

### ISSUE THREAD

**Issue by werewolf666** [microsoft/WSL#10243]
### Windows Version

22621.1848

### WSL Version

WSL 版本： 1.2.5.0 内核版本： 5.15.90.1 WSLg 版本： 1.0.51 MSRDC 版本： 1.2.3770 Direct3D 版本： 1.608.2-61064218 DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows 版本： 10.0.22621.1848

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

CPU:AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
RAM:32.0 GB

### Repro Steps

start very slowly everytime.

### Expected Behavior

start very quickly,maybe take 5s or 10s ,like other PC.

### Actual Behavior

is take my time about 90s...

### Diagnostic Logs

[WslLogs-2023-06-27_21-13-56.zip](https://github.com/microsoft/WSL/files/11882670/WslLogs-2023-06-27_21-13-56.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @werewolf666.

Does this happen will all distros or just one ? What if you just run one command like: `wsl echo ok`, does this take as long ?
