### ISSUE TITLE
io_uring doesn't work in WSL2

### ISSUE THREAD

**Issue by GlassBeaver** [microsoft/WSL#10250]
### Windows Version

Microsoft Windows [Version 10.0.22621.1848]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Install liburing on WSL2:
sudo apt install liburing-dev

Build & run the following C++ program and observe that `sqeIn` is null in WSL2 but valid in say a VirtualBox or a cloud-hosted Linux VPS running the exact same version of Ubuntu (22.04 in my case):

```cpp
#include <string.h>
#include <liburing.h>
#include <netinet/in.h>

int main()
{
	io_uring ring;
	int result = io_uring_queue_init(32, &ring, 0);
	if (result != 0)
	{
		printf("error in io_uring_queue_init: %d, %s\n", result, strerror(-result));
		return 1;
	}

	io_uring_sqe* sqeIn = io_uring_get_sqe(&ring);
	if (!sqeIn)
	{
		printf("error in io_uring_get_sqe\n");
		return 1;
	}

	printf("io_uring verified\n");
	return 0;
}
```

### Expected Behavior

"io_uring verified" should be printed to the console and sqeIn shouldn't be null.

### Actual Behavior

"error in io_uring_get_sqe" is printed to the console and sqeIn is null.

**Comment by zcobol** [comment]
@GlassBeaver try this: https://github.com/ton-blockchain/ton/issues/431#issuecomment-1511391789

Sample run on WSL2:

```
tux@dragon:~/test3$ g++ test.cpp -luring
tux@dragon:~/test3$ ./a.out
io_uring verified
```

**Comment by Spear-Neil** [comment]
> Fixed it. The issue was that I'd installed io_uring via apt. To make it work, I had to remove it and build from source:
> 
> ```
> sudo apt remove liburing-dev
> sudo apt remove liburing2
> git clone https://github.com/axboe/liburing.git
> cd liburing
> make && sudo make install
> ```

This works for me.
WSL2, 5.15.167.4-microsoft-standard-WSL2
