### ISSUE TITLE
[Network] I cant ping 8.8.8.8 or any other IP

### ISSUE THREAD

**Issue by ocelik94** [microsoft/WSL#10256]
### Windows Version

Microsoft Windows [Version 10.0.19045.3086]

### WSL Version

1.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

5.15.90.2-3

### Repro Steps

Fresh Windows Installation

### Expected Behavior

I should be able to ping 8.8.8.8 or any other public IP-address. 

### Actual Behavior

A ping results in "Host Network unreachable".

```
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4172ms
```

**Comment by pmartincic** [comment]
This isn't an actionable bug. We'd need /logs and a usable set of repro instructions.
