### ISSUE TITLE
System cannot find drive

### ISSUE THREAD

**Issue by simonSilverse** [microsoft/WSL#10267]
### Windows Version

Microsoft Windows [Version 10.0.22621.1848]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Repro Steps

wsl --mount \\\\.\PHYSICALDRIVE1  --bare
![Screenshot 2023-07-07 133929](https://github.com/microsoft/WSL/assets/24142828/79e18e2e-d74b-4065-915b-e0b2dbfa97f8)

### Expected Behavior

The disk should be mounted successfully.

### Actual Behavior

See title of this bug report...

### Diagnostic Logs

https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

**Comment by pmartincic** [comment]
Thanks for reporting, I can reproduce it, will look.

**Comment by simonSilverse** [comment]
Seems like this thread of mime has been marked as duplicate as closed.
However, I cannot determine that this is exactly the same as issue #6011.
I am trying to mount a disk which has been attached to the host machine @ https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk.
Issue #6011 is trying to attach a USB of the host machine to the VM itself @ https://learn.microsoft.com/en-us/windows/wsl/connect-usb.
I know there is the USB/IP open source project @ https://github.com/dorssel/usbipd-win to support attaching of USB to the VM.
I think both cases are treated differently @ https://learn.microsoft.com/en-us/windows/wsl/ grouped under the 'How-to' navigation link.

Anyways, I will lightly hope that the next build update will solve the issue.

**Comment by simonSilverse** [comment]
Seems like this thread of mime has been marked as duplicate and closed.
However, I cannot determine that this is exactly the same as issue https://github.com/microsoft/WSL/issues/6011.
I am trying to mount a disk which has been attached to the host machine @ https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk.
Issue https://github.com/microsoft/WSL/issues/6011 is trying to attach a USB of the host machine to the VM itself @ https://learn.microsoft.com/en-us/windows/wsl/connect-usb.
I know there is the USB/IP open source project @ https://github.com/dorssel/usbipd-win to support attaching of USB to the VM.
I think both cases are treated differently @ https://learn.microsoft.com/en-us/windows/wsl/ grouped under the 'How-to' navigation link.

Anyways, I will lightly hope that the next build update will solve the issue.
