### ISSUE TITLE
Nessus found the following service with an untrusted path : WslService 

### ISSUE THREAD

**Issue by THBrew** [microsoft/WSL#10262]
### Windows Version

Microsoft Windows [Version 10.0.19045.3086]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

unknown

### Distro Version

unknown

### Repro Steps

Nessus scan results

### Expected Behavior

Nessus scan results

### Actual Behavior

Nessus found the following service with an untrusted path : WslService : C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslservice.exe

**Comment by pmartincic** [comment]
This doesn't have any actionable feedback?

**Comment by THBrew** [comment]
Sorry for the delayed reply - I thought the fix of quoting the service path was implied. 
So the requested fix/action is to quote the service path for WslService to be  "C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslservice.exe" by adding the quotes.
