### ISSUE TITLE
git push hangs

### ISSUE THREAD

**Issue by six1203** [microsoft/WSL#10273]
### Windows Version

Microsoft Windows [版本 10.0.22000.675]

### WSL Version

5.15.90.1

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Other Software

git version 2.25.1

### Repro Steps

When I submitted the code to the company's remote gitlab server, git rammed

### Expected Behavior

Submit the code normally

### Actual Behavior

Enumerating objects: 58, done.
Counting objects: 100% (58/58), done.
Delta compression using up to 16 threads
Compressing objects: 100% (32/32), done.
Writing objects: 100% (37/37), 9.41 KiB | 9.41 MiB/s, done.
Total 37 (delta 16), reused 16 (delta 3)

it blocked，I can submit by starting a git gui client

**Comment by pmartincic** [comment]
Without any more information this doesn't seem like the right place for this. We'd need both logs and a concrete repro. Your company's gitlab server isn't something we would use?
