### ISSUE TITLE
error: internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --insert POSTROUTING --jump LIBVIRT_PRT: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#10281]
### Windows Version

Windows 11 PRO Version 10.0.22000.2176

### WSL Version

Versione WSL: 1.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.1.38-microsoft-standard

### Distro Version

Ubuntu 22.10

### Repro Steps

I've just installed virt-manager on my Ubuntu 22.10 that I've installed within the WSL2 system running on Windows 11 with the aim to virtualize FreeBSD. I've reaized that virt-manager didn't create any bridge device so I can't assign it to the FreeBSD vm that I'm creating,as you can see :

![zm9awzabkobb1](https://github.com/microsoft/WSL/assets/755339/498717d0-8061-442d-8fbb-5a04be1d77d4)

Do you have some straight documentation that I can study to learn the process to create the missing bridge adapter ? I've found some documentation,but due to the recent changes made by Microsoft to the WSL2,I'm not sure about which method found on internet is the good one. I don't want to break the hard work that I did until now to make work everything correctly. So I don't wat to experiment,I want to go directly to the right steps to perform to reach the result I want. Thank you.

```
NAT is also inactive and I'm not able to enable it :

root@marietto-windows11:/mnt/c/Users/virtu/Downloads/cmder# virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   yes         yes

root@marietto-windows11:/mnt/c/Users/virtu/Downloads/cmder# sudo virsh net-start default

error: Failed to start network default

error: internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --insert POSTROUTING --jump LIBVIRT_PRT: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
```

### Expected Behavior

Starting virt-manager network default succesfully,enabling NAT succesfully.

### Actual Behavior

`error: internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --insert POSTROUTING --jump LIBVIRT_PRT: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING`

**Comment by Marietto2008** [comment]
Fixed enabling the legacy iptables :

`update-alternatives --set iptables /usr/sbin/iptables-legacy`

**Comment by ikitayama** [comment]
I'm facing this issue but on Mac. Is there any other workaround other than using legacy?

**Comment by ikitayama** [comment]
> I'm facing this issue but on Mac. Is there any other workaround other than using legacy?

Installing nftables package onto Ubuntu 22.04 fixed this issue.
