### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102 on WSL 2

### ISSUE THREAD

**Issue by SaraSpena** [microsoft/WSL#10295]
### Windows Version

Microsoft Windows [Versione 10.0.19045.3208]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Repro Steps

wsl --install ubuntu (after downloaded) 
![cmd_4P2Njq8wGi](https://github.com/microsoft/WSL/assets/127884375/de25c458-9ce5-4910-a824-1e2aafdcc12c)

### Expected Behavior

I was expected to install the distro on wsl 2

### Actual Behavior

i got the WslRegisterDistribution failed with error: 0x80370102

### Diagnostic Logs

I can add some things useful as images:
![msinfo32_Vxhd7Shx7l](https://github.com/microsoft/WSL/assets/127884375/2422a7ab-9656-4904-ba83-227d26962e26)
![OptionalFeatures_PMYdXUbcV8](https://github.com/microsoft/WSL/assets/127884375/9513a896-484d-44b5-8316-099f18e339bc)
![regedit_6RGcDpb0ad](https://github.com/microsoft/WSL/assets/127884375/d8ee7343-4a09-48fc-b64a-ca451ab0997d)
![Speccy64_FJJFhSf0OS](https://github.com/microsoft/WSL/assets/127884375/e9ed620e-377e-4190-87cf-daf81fa05180)

**Comment by neksodebe** [comment]
I have the same issue here.

**Comment by OneBlue** [comment]
Thank you for reporting this @SaraSpena. My Italian isn't great, but based on what I see on the first screenshot the issue is that your hardware doesn't support virtualization. You probably need to enable it on your BIOS settings.

**Comment by SaraSpena** [comment]
The issue Is not that. Is the First thing i've done months ago, enabling virtualization. Is not that simple😅 why did you close the ticket?
As you can see in the screenshot it says that the virtualization is enabled.

**Comment by OneBlue** [comment]
Oh ok I probably mis-interpreted the last line on the first screenshot. Re-opening.

**Comment by SaraSpena** [comment]
> Oh ok I probably mis-interpreted the last line on the first screenshot. Re-opening.

Still closed

**Comment by Melfos-md** [comment]
I have the same issue, I also have AMD Ryzen 5 (virtualization is enabled) ; windows family 10 22h2 19045.3324

**Comment by Melfos-md** [comment]
[WslLogs-2023-08-26_10-32-44.zip](https://github.com/microsoft/WSL/files/12444886/WslLogs-2023-08-26_10-32-44.zip)

thank you

**Comment by OneBlue** [comment]
Thank you @Melfos-md. Did you reproduce the issue while the log collection was running ? I'm not seeing any WSL logs in the output.

/logs
