### ISSUE TITLE
Getting warning: Processing fstab with mount -a failed.

### ISSUE THREAD

**Issue by joaompinto** [microsoft/WSL#10298]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Repro Steps

Follow the instructions described at https://github.com/kind-in-open-source/DevEx-Linux .
Run: wsl -d DevEx

### Expected Behavior

Get a shell without any warning

### Actual Behavior

I get the warning:
Processing fstab with mount -a failed.

**Comment by Biswa96** [comment]
Could you provide the content of `/etc/fstab` file?

**Comment by joaompinto** [comment]
DevDesktop:~# cat /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
DevDesktop:~#

**Comment by joaompinto** [comment]
I resolved it by adjusting my distro configuration:
```sh
cat <<EOF > etc/wsl.conf
[automount]
mountFsTab = false

[user]
default = developer
EOF
```

**Comment by drewaogle** [comment]
I get the same thing.
my `/etc/fstab`  
```
UUID=148e0ac8-7864-46df-a27f-a77fe56febcd /home ext4    defaults        0 0
```

when I su to root and run `mount -a` it runs.

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1992
```

```
root@LEICA:~# dmesg | head -1
[    0.000000] Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023
root@LEICA:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
root@LEICA:~#
```

**Comment by drewaogle** [comment]
seems to be working now, not sure what changed.
