### ISSUE TITLE
Trying to compile a kernel results in "FAILED: load BTF from vmlinux: No such file or directory"

### ISSUE THREAD

**Issue by ReneNyffenegger** [microsoft/WSL#10299]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2

### Distro Version

Debian 11 (lsb_release is not available as command)

### Repro Steps

```
git clone https://github.com/microsoft/WSL2-Linux-Kernel
cd WSL2-Linux-Kernel
cp Microsoft/config-wsl .config
make -j 4
```

### Expected Behavior

The kernel would be built

### Actual Behavior

The build process ends with the error message

    FAILED: load BTF from vmlinux: No such file or directory

**Comment by OneBlue** [comment]
Thank you for reporting this @ReneNyffenegger. Do you see the same error by following the build instructions ? 

```
$ sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev
$ make KCONFIG_CONFIG=Microsoft/config-wsl
``` 

?

**Comment by ReneNyffenegger** [comment]
It turned out I had quite a few packages not installed: `flex`, `bison`, `dwarves`, `libssl-dev` and `libelf-dev`.

After installing them with the proposed `sudo apt install...` command and building it with `make KCONFIG...`, I got
    /bin/sh: 1: bc: not found

after also nstalleding `bc` ...
    sudo apt install -y bc

the build went on without further problems (I did not yet try to install the new built kernel)

**Comment by okineadev** [comment]
I found the cause of the problem on Stack Exchange - https://unix.stackexchange.com/a/616479/608997

> I ran into the same issue today, for me the issue was that pahole ran out of memory (peak memory usage of pahole was around 2.5GB).

In order to solve this problem, I removed the RAM limit in `.wslconfig`:

```ini
[wsl2]
# memory=3GB
```

After that I compiled the kernel without any problems

You can learn more about `.wslconfig` and memory limits at this link- https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings
