### ISSUE TITLE
An operation was attempted on something that is not a socket.

### ISSUE THREAD

**Issue by SmashingQuasar** [microsoft/WSL#10313]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Debian

### Repro Steps

WSL stopped being able to start after a recent Windows update.
I am unable to start it whatsoever.
I am running `wsl` in a PowerShell command line, it returns:

```ps
PS C:\Users\nicol> wsl
An operation was attempted on something that is not a socket.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x80072736
```

### Expected Behavior

WSL should be starting normally.

### Actual Behavior

WSL does not start and complains about a socket issue.

### Diagnostic Logs

/!\ IMPORTANT /!\
I have followed the steps to retrieve the logs, however contrary to what's indicated, it returns a directory (as a zip file) instead of a simple log file. It is then not possible to attach it here. If you provide more information on how to extract one single log file, I will gladly paste it in the diagnostics logs section.

**Comment by OneBlue** [comment]
Thank you for reporting this @SmashingQuasar. Are you sure you're using WSL1 ? Based on the error code it looks like a WSL2 instance creation is failing.

Can you try to capture logs again ? You should be able to attach the entire .zip file here

**Comment by SmashingQuasar** [comment]
It was a mistake on my end, I am indeed using WSL 2.

Here are the WSL logs you requested (the original extract I did when opening this issue).

[WslLogs-2023-07-20_13-10-30.zip](https://github.com/microsoft/WSL/files/12192147/WslLogs-2023-07-20_13-10-30.zip)

Thanks for your time!

**Comment by OneBlue** [comment]
Thank you. In the logs I can see that the source of this error is HNS: 

```
1297	True	Microsoft.Windows.Lxss.Manager	Error	0	07-20-2023 04:10:47.522	"	"	"code: 	
failurecount: 	497
file: 	D:\a\1\s\src\windows\wslcore\lib\NatNetworking.cpp
function: 	
hr: 	0x80072736
linenumber: 	887
message: 	""HcnCreateNetwork {""""Success"""":false,""""Error"""":""""An operation was attempted on something that is not a socket. """",""""ErrorCode"""":2147952438}""
threadid: 	41632
type: 	0"	D:\a\1\s\src\windows\wslcore\lib\NatNetworking.cpp			5392	41632	2		00000000-0000-0000-0000-000000000000		

```

@keith-horton: Can you help root causing the issue ?

**Comment by keith-horton** [comment]
Hi there.

This is an issue with the ICS DNS proxy in Windows - it's fixed in the next release of Windows but was not fixed in the current release.

You can work around this by turning off DNS proxy and WSL will instead push across the DNS servers configured in Windows. To do that, you'll want to update the .wslconfig file with the following:

dnsProxy=false


But this requires the latest builds of WSL. You can get the latest WSL builds with the --wsl --update --pre-release command line option.

Thanks!

**Comment by SmashingQuasar** [comment]
Well, since I use WSL for work, I was forced to entirely delete it and thus lose part of my work.

Thanks for the update, it would be very appreciated if the next releases of WSL and Windows were thoroughly tested together prior to release as Windows vastly dominates the market and it impacts hundreds of thousands of developers worldwide.

In any case, let's hope this thread helps other people facing the same issue.

**Comment by dj-sf** [comment]
yeah if yall are gonna dominate the entire market using unethical anticompetitive businesses practices that force us to use your OS that we dont actually need because there are viable free alternatives, at least make it work properly.  ffs.

**Comment by therealplato** [comment]
i worked around this issue by disabling a vpn

**Comment by OneBlue** [comment]
Closing the fix will be on the next Windows release and a workaround has been published

**Comment by sailingbikeruk** [comment]
> i worked around this issue by disabling a vpn

I found this happened when I had OpenVPN GUI open even when not connected. System Tray > OpenVPN > Exit and WSL working again.

**Comment by dj-sf** [comment]
can confim i just needed to turn off my vpn to fix this
