### ISSUE TITLE
Bash Utility Process Name is missing in ProcessExplorer or in ProcMon Logs

### ISSUE THREAD

**Issue by suhastawade** [Microsoft/WSL#1031]
- A brief description
  Bash Utility Process Name is missing in process explorer or in procmon logs. 
- Expected results
  Name should be displayed to identify process.
- Actual results (with terminal output if applicable)
  No process name is displayed causing configuring security rules for outgoing traffic over the network.
- Your Windows build number
  Windows 10 - 14901
- Steps / commands required to reproduce the error
1. \- Run Bash utility (not compulsory but can keep any update commands running like sudo apt-get update) 
2. \- Run Process explorer or procmon logs 
3. \- Right click on bash logs or bash process name on process explorer 
4. - Check name is missing.
- Required packages and commands to install
1. \- Process explorer or ProcMon utility 

![process_exp_bash_process_name_missing](https://cloud.githubusercontent.com/assets/15941720/18167130/823da1e8-706c-11e6-9148-02b179733dc8.png)
![bash_process_name_missing](https://cloud.githubusercontent.com/assets/15941720/18167131/8255f194-706c-11e6-8b01-1bb9f6b178fb.png)

**Comment by rodrymbo** [comment]
You might observe that it is any "linux process" that behaves like this. In your example above, both `init` and `bash` behave the same way. Also, Bash.exe behaves (relatively) normally. So the title is a bit off. 

Anyway, you've identified two issues: the linux processes don't behave like Windows processes from the perspective of Procmon or Procexp (which isn't surprising, given that they are radically new), and Windows Firewall, or at least its UX, doesn't know what to do with them. 

Or maybe they are the same ... but they look different to me. At any rate, fixing Windows Firewall's user interface so we can open or block ports for specific Linux programs seems to be the more important.

**Comment by sunilmut** [comment]
Thanks for reporting these issues. We definitely appreciate the feedback. The so called "Linux processes" are pico processes and are relatively newer as part of a production environment. As you have pointed out, all the UI elements are not fully compatible with these yet. Moving forward, I think it makes sense to address these.

@russalex - Can we reach out to the owners of these tools to see if we can get them to work nicely with the technology?

**Comment by suhastawade** [comment]
@rodrymbo  @sunilmut  - Thanks for your comments. Please let me know once this issue is addressed or in which build it will be addressed.

**Comment by JimBrennan3** [comment]
@sunilmut - Your state that the tool needs to be fixed. Can you or someone outline the solution to get the "Linux processes" / pico process info? It is likely that other vendors may need to address this also.

**Comment by suhastawade** [comment]
@sunilmut - Please correct me if I am wrong.
From the process explorer it is clear that svchost.exe is launching Bash.exe process and in procmon logs we can see once it is launched it has no process name.
It means while launching that process the name should be given.

**Comment by russalex** [comment]
We are aware that pico processes do not integrate with tools such as procman as well as many would like.  We are looking at how to improve this, but do not have any instructions or official statements at this time.

@suhastawade, just wondering: are you looking for the process names for a specific purpose or just looking?  It is always interesting to see what people are trying to run and the tools the community creates.

**Comment by JimBrennan3** [comment]
3rd party application firewalls are blocking traffic based on the inability to trace the network activity to a specific process and knowing that process name. So, apt-get update and scp connections are failing because of the firewall connection blocks.

**Comment by dmex** [comment]
We also have a similar problem in Process Hacker:
http://i.imgur.com/taJq5bx.png

The lack of ImageName is somewhat a security issue since both Process Hacker and Process Explorer are both directly integrated with VirusTotal, Jotti and Comodo cloud services for antiviral/malware analysis and are presently unable to submit Pico processes to those services. Anti-virus software vendors are also in the same situation and are unable to properly scan running Pico processes and they are additionally blocked or shown as malicious by nearly all 3rd party security tools (including some Microsoft tools such as AutoRuns) all due to the lack of ImageName.

There is also an additional issue with Process Hacker since we also allow users to inspect PE header information via a separate dialog and are unable to show ELF64 header information for Linux binaries (since we're unable to query ImageName and pass that path into our peview utility). We would like to show a dialog similar to this one when inspecting ELF binaries:
http://i.imgur.com/2aWQgzO.png

Process Hacker, Process Explorer and Process Monitor all query the "Process Name" from the ImageName field of the SYSTEM_PROCESS_INFORMATION structure and the Command line and Current directory are copied directly from the process' PEB structure.

The ImageName field is queried via native methods:
https://github.com/processhacker2/processhacker2/blob/1989541f2f402a6ae972f8326333c73d61832c67/phlib/native.c#L3897

The Command line and Current directory information is not important for either Process Explorer or Process Hacker but for reference it's copied directly from the process' PEB:
https://github.com/processhacker2/processhacker2/blob/1989541f2f402a6ae972f8326333c73d61832c67/phlib/native.c#L596

Process Explorer uses identical techniques and methods so feel free to review our source to see how both tools query various information:
https://github.com/processhacker2/processhacker2 

You can also download the installer or pre-built binaries from either our website or via Github:
https://wj32.org/processhacker/downloads.php
https://github.com/processhacker2/processhacker2/releases/tag/v2.39

Please add support for querying the ImageName so that Microsoft's own tools and 3rd party tools can function correctly! :P

Thanks

**Comment by aseering** [comment]
@dmex -- in WSL, you can (and programs frequently do) use the `exec()` syscall to change which image a process points at.  Will Windows-based tools and firewalls correctly detect if a process's ImageName changes and updates their rules accordingly?  (I don't know; I don't have a lot of experience with these Windows APIs.)

**Comment by suhastawade** [comment]
@russalex - As Jim pointed out in his comment 3rd party applications of firewall are not able to process the outgoing packets just because the network activity is done by a process which has no name.
And this all is happening because of missing ImageName.

**Comment by rodrymbo** [comment]
Another possible perspective (or silly ravings, depending on your point of view):

I don't so much care that WSL processes behave exactly like Windows processes, as I do that there is an officially sanctioned and recommended Microsoft way to handle the two kinds of processes. We need the same functionality to work from things like firewalls, anti-virus, and maintenance tools like Microsoft's own Process Explorer -- a "best practices" recommendation from Microsoft for how to do it, with API or documentation or whatever works to get it done, that can even be used by third parties, even if it is different between WSL and Windows.

The same would apply to other tasks, such as backup. There needs to be some documentation about how, for example, System Restore and/or File History handle files in VolFS, in particular, so we can have some confidence whether or not we can count on those tools to recover missing or broken files in WSL. (Even if the word is just "sorry, don't count on it, use `tar`".) Documentation about how third-party tools **could** back up VolFS files (including extended attributes) would be welcome.

Let's see: Best Practices for managing WSL from Windows, including Backup, Anti-virus, Firewall.  What other topics in this category need to be addressed? Perhaps audit and logging?

**Comment by russalex** [comment]
We are working on our best practices for Anti-Virus, Anti-Malware, and Firewall vendors.  It is one of the top items on our priority list.

It is important to note that while we will slide into existing APIs when possible, the fact that we are running Linux processes and not Windows means some information will either need to be queried in new ways or may not be available.  This is shown a little in our [Pico Process Overview](https://blogs.msdn.microsoft.com/wsl/2016/05/23/pico-process-overview/) where we point out that these processes do not contain a PEB or TEB.

We are committed to providing guidance, best practices, and instructions for vendors.  Just not quite ready to roll out yet.

**Comment by dmex** [comment]
@russalex 

Will this information also be made available publicly? Anti-virus and Anti-malware vendors can already identify the ImageName using ZwQueryVirtualMemory with the MemoryMappedFilenameInformation class when they're scanning memory...

Process Hacker uses this technique to show modules and files that are presently in-use by processes and this helps for both debugging and identifying malicious activity (just like anti-virus software): http://i.imgur.com/5EvnDLC.png

However it's a bit overkill having to enumerate the entire memory region of a Pico process just to query the ImageName of that process... We're hoping there might be a proper API or structure with this information at some point in the future?

**Comment by russalex** [comment]
We are shooting to have official support sometime in October.

For a bit more visibility, we have a good idea of what we want to do here.  We have run our proposed changes past the Windows Defender team and may consult some of the larger AV vendors before making documentation public.

**Comment by dmex** [comment]
@russalex @scooley @benhillis 

Are we able to close this issue considering the SystemProcessIdInformation class now returns the ImageName?

> consult some of the larger AV vendors before making documentation public.

It's been almost two years since this comment and no documentation has been made available. I guess we should give up waiting for something? :confused:

**Comment by benhillis** [comment]
@dmex - Here is a link to our documentation: https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/

**Comment by jtmoon79** [comment]
Still a problem in Process Explorer 16.21.  I'm not sure if this is a Process Explorer Issue.  I'm posting this here in case someone-in-the-know wants to look into this.

Using Windows Pro 10,

1. enable Windows Feature _Windows Subsystem for Linux_
2. From the Microsoft Store, Install _Debian GNU/Linux_
3. Start the _debian_ program (in the Windows Programs Menu)
This starts a bash prompt within the Linux Subsystem.
4. start _Process Explorer_ with Administrator Privileges
5. Review the *bash* process entry within Process Explorer
**_BUG:_** _Process Explorer_ does not have information about the root-privileged Linux processes
For example, column _Path_ has string "_[A device attached to the system is not functioning]_".
Other common columns are also empty; _Command Line_, _Version_, etcetera.

Using _Process Explorer 16.21_.

Also posted in [this MSDN Technet Forum post](https://social.technet.microsoft.com/Forums/msonline/en-US/52f29251-9548-4c8a-ab2b-ec6f6b7ace5c).

**Comment by Trass3r** [comment]
Confirmed Process Explorer 16.22 only displays the process name, not the path.
Process Hacker Nightly is able to fetch the image path but no commandline (PEB address 0x0), is this to be expected?

**Comment by benhillis** [comment]
Yes, WSL processes do not have PEBs.
