### ISSUE TITLE
Docker Desktop (Windows) not starting after windows update. 

### ISSUE THREAD

**Issue by farseem** [microsoft/WSL#10312]
### Windows Version

 10.0.22621.1992

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Other Software

Docker Desktop (Windows): Version: 4.21.1

### Repro Steps

1. **Try opening Docker Desktop, after some time it'll yield the following popup error**

Failed to deploy distro docker-desktop to C:\Users\User\AppData\Local\Docker\wsl\distro: : Element not found.

Some WSL system related access rights are not set correctly. This sometimes happens after waking the computer or not being connected to your domain/active directory. Please try to reboot the computer. If not sufficient, WSL may need to be reinstalled fully. As a last resort, try to uninstall/reinstall Docker Desktop.

Action Taken: Rebooted computer, WSL reinstalled several times, reinstalled Docker Destop 

2. **Installing Ubuntu/ Ubuntu 22.0.xxx from App Store**

After getting either distro, when opened a window appears and tries to install the distro, but after few minutes it displayes the following message:  

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070490
Error: 0x80070490 Element not found.

3. **After installing/enabling wsl, I've also tried installing from cmd**

When trying the "wsl -install" command it displays the following message

**wsl.exe --install**
Windows Subsystem for Linux is already installed.
The following is a list of valid distributions that can be installed.
Install using 'wsl --install -d <Distro>'.

Contrary to that when running 'wsl -l -v' it yields the following message:

 **wsl -l -v**
Windows Subsystem for Linux has no installed distributions.

Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.

Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error code: Wsl/WSL_E_DEFAULT_DISTRO_NOT_FOUND

 **wsl.exe --update**
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

**wsl.exe --version**
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1992

The update causing the issue is listed below happened on 13 Jul 2023
**Update: KB5028851 & KB5028185**
![image](https://github.com/microsoft/WSL/assets/30997753/a54e8c45-6cd9-45f6-bb46-9919aba9b470)

**I have run the diagnostics too, here is the upload confirmation output** 
 [2023-07-20T10:04:33.405904500Z][com.docker.diagnose.exe][I] Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/69E96770-6913-4D95-A9C5-F0BF6631FE5C/20230720100111.zip
              Diagnostics ID:     69E96770-6913-4D95-A9C5-F0BF6631FE5C/20230720100111 (uploaded)system-related

### Expected Behavior

Docker desktop to run

### Actual Behavior

It's not running after some time the following popup is displayed 

![image](https://github.com/microsoft/WSL/assets/30997753/9eb10ee0-9068-4649-90ca-e4073a73a000)

### Diagnostic Logs

[https://docker-pinata-support.s3.amazonaws.com/incoming/3/69E96770-6913-4D95-A9C5-F0BF6631FE5C/20230720100111.zip](url)

### Log
Log uploaded @OneBlue 
[WslLogs-2023-07-26_08-53-33.zip](https://github.com/microsoft/WSL/files/12167975/WslLogs-2023-07-26_08-53-33.zip)

**Comment by farseem** [comment]
@OneBlue I've attached the log to the original issue and also adding here too. 
[WslLogs-2023-07-26_08-53-33.zip](https://github.com/microsoft/WSL/files/12167983/WslLogs-2023-07-26_08-53-33.zip)

**Comment by tanzeelxcb** [comment]
same issue with me

**Comment by Hedgineering** [comment]
I have the same issue, here are my logs
[WslLogs-2023-12-24_17-32-11.zip](https://github.com/microsoft/WSL/files/13762948/WslLogs-2023-12-24_17-32-11.zip)

**Comment by OneBlue** [comment]
Thank you @farseem. Looks like you're hitting an HNS issue: 

```
1551	False	Microsoft-Windows-Host-Network-Service	ActivityError	0	07-25-2023 19:58:24.558	"	"	"wilActivity: 
{
	callContext: 	\HnsRpcV2_Create\NetworkActivity\ResourceActivity
	currentContextId: 	19
	currentContextMessage: 	
	currentContextName: 	ResourceActivity
	failureCount: 	11
	failureId: 	13
	failureType: 	0
	fileName: 	onecore\vm\dv\net\hns\service\common\helperlib\src\iphelper.cpp
	function: 	
	hresult: 	0x80070490
	lineNumber: 	458
	message: 	
	module: 	hostnetsvc.dll
	originatingContextId: 	17
	originatingContextMessage: 	
	originatingContextName: 	HnsRpcV2_Create
	threadId: 	2616
}"	onecore\vm\dv\net\hns\service\common\helperlib\src\iphelper.cpp	458	 	2556	2616	2		eb9d1714-bd51-000a-0150-a1ee51bdd901		

```

@keith-horton : How can we root cause this issue ?

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by craigloewen-msft** [comment]
Closing this issue and will track at #11554 instead

**Comment by nicogonz88** [comment]
[WslLogs-2024-07-01_14-42-10.zip](https://github.com/user-attachments/files/16057231/WslLogs-2024-07-01_14-42-10.zip)
