### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370114

### ISSUE THREAD

**Issue by Vibhushit07** [microsoft/WSL#10318]
### Windows Version

Windows  11 [10.0.22000]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Other Software

Docker Desktop (Windows)- 4.21.1

### Repro Steps

wsl --install

### Expected Behavior

WSL should get installed

### Actual Behavior

Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.

![wsl_error](https://github.com/microsoft/WSL/assets/41487076/209540d0-1b8a-44f9-940c-3c7342ab44ce)

**Comment by OneBlue** [comment]
Thank you for reporting this @Vibhushit07. Do you have the VirtualMachineMachinePlatform optional component enabled ? It's required to run WSL2
