### ISSUE TITLE
Error: 0x80070057 The parameter is incorrect.

### ISSUE THREAD

**Issue by chorongi** [microsoft/WSL#10317]
### Windows Version

Microsoft Windows [Version 10.0.25905.1000]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

2

### Repro Steps

wsl --install

### Expected Behavior

Installation happens, asks for Linux Username.

### Actual Behavior

```
PS C:\WINDOWS\system32> wsl --install
Installing: Ubuntu
Ubuntu has been installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.
```

**Comment by PhyX-Meow** [comment]
dup https://github.com/microsoft/WSL/issues/10285
