### ISSUE TITLE
How can I access the /root folder manually without any commands?

### ISSUE THREAD

**Issue by jfhnjisdfn** [microsoft/WSL#10320]
![Screenshot (34)](https://github.com/microsoft/WSL/assets/140168347/4d3a62bc-6a78-4e11-957a-03aad7d085fd
This error always encounters when I'm attempting to access the root folder. Can anyone help me?

**Comment by Abhijeet-kadance** [comment]
navigate to \\wsl$ in explore, Then you would see Ubuntu folder right click on the folder and choose the Map network drive. This will give you a drive in the in THIS PC in the explorer. Please try this

**Comment by OneBlue** [comment]
Thank you for reporting this @jfhnjisdfn.

This is most likely because your default user is not root.

You can change this by adding: 

```
[user]
default=root
```

in `/etc/wsl.conf` and restarting wsl via: `wsl.exe --shutdown`
