### ISSUE TITLE
Windows Freezes When WSL 2 Running

### ISSUE THREAD

**Issue by jacksimpsoncartesian** [microsoft/WSL#10328]
### Windows Version

Microsoft Windows Version [10.0.22621.1848]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Windows on my Dell XPS 15 laptop (2021) will frequently freeze once WSL is installed and I start using it (either via terminal or VS Code). I will have to do a hard reboot of the machine to restart. Sometimes it freezes within 5 minutes of using WSL, sometimes it freezes within an hour or two.

I've done three complete wipes of my laptop and had Dell replace the hard drive and battery. This issue only occurs once I install WSL on my laptop and use it - absolutely no freezing issue otherwise.

### Expected Behavior

Not to freeze.

### Actual Behavior

Laptop completely freezes multiple times a day when using WSL

**Comment by zemacnica** [comment]
I have same issue with this same version.
I'm just trying to log into wsl instance and CPU go crazy. But it seems it triggers defender threat protection and Antimalware  too. I have no rights to try it with disabled defender, unfortunately.

**Comment by DominikJuran** [comment]
I have same issue. When I run wsl CPU go crazy and screen is flickering. 
Distro version:
Ubuntu 22.04

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.3208

**Comment by jacksimpsoncartesian** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

Does this logging tool have to be running before it freezes, or can I run it immediately after a freeze?

**Comment by DominikJuran** [comment]
This helped me to resolve the issue. 
1. Uninstalled everything 
2. download older kernel version 5.10.102.2 and install
3. install ubuntu
4. set default version wsl to 2
5. !!! DO NOT RUN wsl --upgrade !!!

**Comment by OneBlue** [comment]
> > Hello! Could you please provide more logs to help us better diagnose your issue?
> > To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> > ```
> > Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> > Set-ExecutionPolicy Bypass -Scope Process -Force
> > .\collect-wsl-logs.ps1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The scipt will output the path of the log file once done.
> > Once completed please upload the output files to this Github issue.
> > [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> > Thank you!
> 
> Does this logging tool have to be running before it freezes, or can I run it immediately after a freeze?

It would need to run before the freeze. You can also try to do /dumps after the freeze, that should also be useful to us.

**Comment by jacksimpsoncartesian** [comment]
@OneBlue when WSL freezes the computer at random the only way to resolve it is to hold down the power button and force it to shut down then start it again, How will the script output the path to the log file when done if the error freezes the computer and I and the script never has a chance to finish runnning?
