### ISSUE TITLE
NFS cannot be used in WSL

### ISSUE THREAD

**Issue by sunshineharry** [microsoft/WSL#10331]
### Windows Version

Microsoft Windows [Version 10.0.22631.2050]

### WSL Version

1.3.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 18.04

### Repro Steps

I try to use NFS, but it cannot work. I test the NFS by 

```bash
sudo mount -t nfs -o nolock,vers=3 127.0.0.1:/root /mnt
```

and it tells me that

```
mount.nfs: Connection timed out
```

The code I used to open NFS is as follows:

**Step1: Install the NFS Server**

```
sudo apt-get install nfs-kernel-server
```

**Step2: Editor the `/etc/exports` and add the following lines to it**

```
 /root  *(rw,nohide,insecure,no_subtree_check,async,no_root_squash)
```

**Step3: Restart the NFS Server**

```
sudo /etc/init.d/nfs-kernel-server restart
```

### Expected Behavior

mount successfully

### Actual Behavior

time out and unsuccessfully

**Comment by OneBlue** [comment]
Hello,

Are you certain that the server is running on 127.0.0.1 ? Based on the output it looks like there's just nothing running and so the connection times out.

Closing since this doesn't look like a WSL issue
