### ISSUE TITLE
Unable to connect to the internet from WSL2 on Windows 11

### ISSUE THREAD

**Issue by ksakai1977** [microsoft/WSL#10339]
### Windows Version

Windows 11, 22H2, build 22621.1992.

### WSL Version

WSL2 Ubuntu 22.04.2 LTS 

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux XYZ 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/LinuxLinux XYZ 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Distro Version

 Ubuntu 22.04.2 LTS, jammy

### Other Software

Windows 11, 22H2, build 22621.1992.
WSL2 Ubuntu 22.04.2 LTS 

The issue I'm reporting is specific to WSL2 and Ubuntu 22.04.2 LTS, and does not involve interaction with other software.

### Repro Steps

Linux KS-cosmos 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
KS@KS-cosmos:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
KS@KS-cosmos:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether AA:BB:CC:DD:EE:FF brd ff:ff:ff:ff:ff:ff
    inet 111.222.333.444/20 brd 555.666.777.888 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::AAAA:BBBB:CCCC:DDDD/64 scope link
       valid_lft forever preferred_lft forever
(The string AA:BB:CC:DD:EE:FF is a placeholder for original MAC address, and 111.222.333.444 and 555.666.777.888 are placeholders for original IP addresses.)

KS@KS-cosmos:~$ cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
KS@KS-cosmos:~$ ping -c 1 google.com
ping: google.com: Temporary failure in name resolution**

### Expected Behavior

"Expected Behavior" for this situation would be to successfully utilize Ubuntu on WSL (Windows Subsystem for Linux). Specifically, this involves resolving the current error, updating Ubuntu, and setting up the Ubuntu environment on WSL without encountering any issues.

In other words, after installing WSL2 and Ubuntu, and following the necessary setup steps, the system should allow for seamless operation of Ubuntu within the Windows environment. This includes being able to execute Linux commands, install and update Linux software, and perform other typical tasks that one would expect to do on an Ubuntu system.

### Actual Behavior

In my case, after I installed WSL2 and Ubuntu and tried to set up the Ubuntu environment on WSL, I encountered unexpected errors. Instead of allowing seamless operation of Ubuntu within the Windows environment, the system presented issues. These included errors related to 'hv_utils' and problems with mounting the 'drvfs' filesystem. As a result, I was unable to fully use Ubuntu on WSL as I had initially expected. Despite my attempts to resolve these issues, they persisted, which contradicts the behavior outlined in the official documentation for WSL and Ubuntu.

### Diagnostic Logs

KS@KS-cosmos:~$ ping -c 1 google.com
ping: google.com: Temporary failure in name resolution

Here is the revised summary in the format you requested:
1) Disabled Proxy: I ensured that no proxy settings were interfering with my connection by disabling them.
2) Checked Internet Connection on Windows: I confirmed that my internet connection was working fine on Windows 11, which indicated that the issue was specific to WSL2.
3) Disabled Firewall: I temporarily disabled my firewall to rule out the possibility that it was blocking the connection.
4) Updated Windows 11: I updated my Windows 11 to the latest version to ensure that the issue was not due to an outdated system.
5) Checked Network Configuration in WSL2: I checked my network configuration in WSL2 using commands like ip addr and cat /etc/resolv.conf. I also tried changing the DNS settings in /etc/resolv.conf.
6) Attempted to Ping External Server: I attempted to ping an external server (e.g., google.com) from within WSL2, but it resulted in a "Temporary failure in name resolution" error.
7) Checked Status of systemd-resolved.service: I checked the status of systemd-resolved.service in WSL2, which is responsible for network name resolution.

Despite these extensive troubleshooting steps, I am still unable to establish an internet connection in WSL2.

I would appreciate any assistance or suggestions on how to resolve this issue. Thank you in advance for your help.
Best regards,
ksakai1977

**Comment by ashemedai** [comment]
`Temporary failure in name resolution` means it is unable to reach the hosts defined in `/etc/resolv.conf`.

When you do an `ip a`, you should see an `eth0`, which by default in WSL2 has IP address `172.21.55.146`. Can you ping its IP address without problems?
