### ISSUE TITLE
Any chance to run this on Server 2019?

### ISSUE THREAD

**Issue by mhechthz** [microsoft/WSL#10337]
### Windows Version

Microsoft Windows [Version 10.0.17763.4645]

### WSL Version

qsl --version doesn't work

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

wsl --status doesn't work

### Distro Version

Ubuntu 2004

### Repro Steps

I'm on Windows Server 2019. WSL is availabe in PowerShell. I cannot install any Ubuntu version.

WSL says (invalid command line option):

PS D:\Software> wsl --status
Ungültige Befehlszeilenoption: --status
Verwendung: wsl.exe [Option] ...
Optionen:
    -d, --distribution <DistributionsName>
        Starten der angegebenen Distribution

    -e, --exec <Befehlszeile>
        Ausführen des angegebenen Linux-Befehls. Die weiteren Argumente werden
        zur Ausführung der Befehlszeile verwendet.

    -u, --user <Benutzername>
        Ausführen als angegebener Benutzer.

    --help
        Diese Informationen zur Verwendung anzeigen.

    --
        Stoppt das Parsen von Argumenten und übergibt den Rest an den Linux-Prozess.

### Expected Behavior

should run.

### Actual Behavior

Get error on malformed manifest: Das App-Manifest muss gemäß dem Schema gültig sein: Zeile 22,
Spalte 96. Hinweis: Das festgelegte Schema für MaxVersionTested erkennt keine XML-Felder mit dem
http://schemas.microsoft.com/appx/manifest/uap/windows10/10-Namespace.

I did run wsl_update_x64.msi (downloaded on 26.07.023) but nothing changed.

**Comment by OneBlue** [comment]
`wsl --status` and `wsl --version` are not supported on Windows Server 2019 unfortunately. To use those commands you need to upgrade a newer windows version.
