### ISSUE TITLE
WSL is taking a long time to start ~10s

### ISSUE THREAD

**Issue by Pedromdsn** [microsoft/WSL#10341]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.05

### Repro Steps

I just installed WSL, but I changed the location to a specific SSD disk to run WSL.

### Expected Behavior

Start almost immediately.

### Actual Behavior

When started, WSL takes +- 10s to start.

### Diagnostic Logs

[New Text Document.txt](https://github.com/microsoft/WSL/files/12177571/New.Text.Document.txt)

**Comment by KonanTheLibrarian** [comment]
Windows does a lot of things without asking - telemetry, compression of files without asking. All slowing down your PC.
A full disk is the worst.  If you have 40GB free do this decompression in admin powershell:
*	Shutdown all applications
*    Exit all wsl terminals
*    wsl.exe --shutdown
*  cd \
*  compact /U /S /I

At bootup restarting WSL2(Ubuntu) or VSCODE-->WSL trys to restore the previous session but now it just trys to load the data and crashes try's again and then you may even reboot to get over the problem - it is a bag of bugs!
Get rid of docker desktop and it fixes an whole load of bugs.  But you have to reinstall everything.  
Docker Desktop is a mountain of bugs!!!!!!
=============================
