### ISSUE TITLE
Add Linux GUI

### ISSUE THREAD

**Issue by v-pun215** [microsoft/WSL#10356]
It would be absolutely epic if WSL had an *optional* GUI for Linux. This could be good for testing GUI applications.

**Comment by aki-k** [comment]
You can already start GUI applications from WSL 2

**Comment by aki-k** [comment]
You can do it like this:

1) disable acpid (installing acpi-support breaks the wsl 2 distro)

https://github.com/microsoft/WSL/issues/8867
https://github.com/microsoft/WSL/issues/8867#issuecomment-1256344696
```
# ln -s /dev/null /etc/systemd/system/acpid.service
# ln -s /dev/null /etc/systemd/system/acpid.path
```
2) install xephyr and ubuntu-mate-desktop
```
# apt-get install xserver-xephyr ubuntu-mate-desktop
```
3) create ~/.xinitrc
```
$ echo "exec mate-session" > ~/.xinitrc
```
4) startup xephyr
```
$ startx -- /usr/bin/Xephyr -br -ac -noreset -screen 1400x1050 :1
```

**Comment by aki-k** [comment]
Wow you can actually do it like this too:
```
# apt-get install xwayland glmark2 glmark2-wayland
$ ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000
$ nohup Xwayland -br -ac -noreset :1 &
$ export DISPLAY=:1 WAYLAND_DISPLAY=wayland-1
$ mate-session
```
then in mate desktop, open a terminal and set WAYLAND_DISPLAY to point to wayland-0
```
$ export WAYLAND_DISPLAY=wayland-0
$ glmark2-wayland
```
