### ISSUE TITLE
wsl --install -d ubuntu Error Code: 0x80070520

### ISSUE THREAD

**Issue by Simon-Bertram** [microsoft/WSL#10352]
### Windows Version

Microsoft Windows 22H2 (OS build 22621.1992)

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Other Software

Docker Desktop 4.21.1.
Git 2.41.0.3

### Repro Steps

1. Installed Docker Desktop 4.21.1. It fails to load and displays the error: Docker Desktop requires a newer WSL kernel version. Update the WSL kernel by running "wsl --update" or follow instructions at https://docs.microsoft.com/windows/wsl/wsl2-kernel
2. When running wsl --update I get the error: A specified logon session does not exist. It may already have been terminated. What does this mean?
3. When I run wsl --list --verbose, I get the message Windows Subsystem for Linux has no installed distributions.
4. When I run wsl --install, I get the message: Windows Subsystem for Linus is already installed. The following is a list of valid distributions that can be installed followed by a list of Linux OS. 
5. So I run wsl --install -d ubuntu, but get the error: An error occurred during installation. Distribution Name: 'Ubuntu' Error Code: 0x80070520.
6. WSLLogs attached.
[WslLogs-2023-07-31_14-31-06.zip](https://github.com/microsoft/WSL/files/12215618/WslLogs-2023-07-31_14-31-06.zip)

### Expected Behavior

![2023_07_31_14_46_22_WSL feature details](https://github.com/microsoft/WSL/assets/50182890/33f415f8-63df-480d-935e-1edc7fa7e3d5)
Shows WSL is enabled.

### Actual Behavior

WSLLogs attached.
Installing: Ubuntu
An error occurred during installation. Distribution Name: 'Ubuntu' Error Code: 0x80070520

### Diagnostic Logs

WSL logs attached. Thanks.

**Comment by Simon-Bertram** [comment]
Ran Windows update and it found a Windows Subsystem for Linux Update - 5.10.102.2 and a Windows Subsystem for Linux WSLg Preview 1.0.27. Installed these, restarted and Docker loaded successfully.
![2023-07-31 14_56_11-Settings](https://github.com/microsoft/WSL/assets/50182890/37ae5ac4-1212-4fe4-a222-be21b3599aea)

**Comment by explodoboy** [comment]
Quick potential solution to anyone searching off Google:

Try to run the command _wsl --update --web-download_. In my case, it caused an update to be downloaded and installed, and then I was able to successfully install Ubuntu. I have no idea why, but it worked for me.

**Comment by MarkBaginski** [comment]
> Quick potential solution to anyone searching off Google:
> 
> As a preface, I successfully installed Ubuntu off the Microsoft Store, but decided to make a fresh installation, installing this time from the command line. So, this is for the people who are trying to do a reinstall but encounter the same error.
> 
> Try to run the command _wsl --update --web-download_. In my case, it caused an update to be downloaded and installed, and then I was able to successfully install Ubuntu. I have no idea why, but it worked for me.

Thanks @explodoboy, tried numerous methods, and only _wsl --update --web-download_ worked.
