### ISSUE TITLE
SHIFT+PU/PD not scrolling

### ISSUE THREAD

**Issue by youngm** [Microsoft/WSL#1035]
- A brief description

Using a linux terminal I can scroll with SHIFT+PU/PD.  Doesn't work in Bash for windows terminal
- Expected results

IF I press SHIFT+PU I'd expect the terminal to scroll one page up and back down with SHIFT+PD
- Actual results (with terminal output if applicable)

SHIFT+PU produces no output.  SHIFT+PD writes a `~`
- Your Windows build number

14393.82
- Steps / commands required to reproduce the error
1. Open terminal
2. produce enough output to scroll page.
3. Press SHIFT+PU to try to scroll to the data moved off the screen.

**Comment by zadjii-msft** [comment]
This isn't a currently supported feature of conhost, unfortunately. It is on our backlog however! I'll see if I can't get it bumped up, considering this is a pretty common workflow that there isn't any windows equivalent ATM.

**Comment by pavel-a** [comment]
When you get to this, please support also other popular keyboard shortcuts: 
 - Ctrl/INS to copy, SHIFT/Ins to paste.
 - Ctrl/shift/UP/DOWN to scroll without a mouse!

**Comment by sunilmut** [comment]
@pavel-a - Please use our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to provide feedback on which features you would like us to prioritize. We definitely look at it. Your feedback is important!

**Comment by pavel-a** [comment]
Dear Sunil,

This item already appears on the backlog

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341399-bash-copy-paste

so I only can whish you all success with it ?

Thanks a lot for the good work!

P.

**Comment by sunilmut** [comment]
Thanks! You can also up vote the user voice article, if not already :). Every vote counts!

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by gmckeown** [comment]
If you're using Windows Terminal to host your WSL terminal sessions, see https://github.com/Microsoft/Terminal/issues/237 for keybindings to enable shift-pageup/pagedown.
