### ISSUE TITLE
WSL2 cannot start VS Code

### ISSUE THREAD

**Issue by brandochn** [microsoft/WSL#10363]
### Windows Version

Microsoft Windows [Version 10.0.19045.3208]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu-22.04

### Other Software

VS code Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Repro Steps

If I tried to open both a file or folder by vs code:

`code . or code file.txt` 

I got the following error:

`/mnt/c/Program Files/Microsoft VS Code/bin/code: 61: /mnt/c/Program Files/Microsoft VS Code/Code.exe: Exec format error`

### Expected Behavior

be able to open a file or folder without errors.

### Actual Behavior

I got this error:

`/mnt/c/Program Files/Microsoft VS Code/bin/code: 61: /mnt/c/Program Files/Microsoft VS Code/Code.exe: Exec format error`

**Comment by martin-rueegg** [comment]
I have a similar situation. The root cause seems to have been either a Windows Update or Ubuntu update (not sure which).

However, the capability to run windows executables without running them explicitly through `/init`, has vanished today.

In the startup debug log I can see the following entry:

```
proc-sys-fs-binfmt_misc.automount: Path /proc/sys/fs/binfmt_misc is already a mount point, refusing start.
[FAILED] Failed to set up automount Arbitrar…rmats File System Automount Point.
See 'systemctl status proc-sys-fs-binfmt_misc.automount' for details.
```

However, `systemctl status proc-sys-fs-binfmt_misc.automount` does not return anything in particular:

```
$ systemctl status proc-sys-fs-binfmt_misc.automount
○ proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point
     Loaded: loaded (/lib/systemd/system/proc-sys-fs-binfmt_misc.automount; static)
     Active: inactive (dead)
   Triggers: ● proc-sys-fs-binfmt_misc.mount
      Where: /proc/sys/fs/binfmt_misc
       Docs: https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
```

Shortly before the above mentioned error during boot, there are a few more errors:

```
Welcome to Ubuntu 22.04.2 LTS!

Couldn't move remaining userspace processes, ignoring: Input/output error
[   25.308929] Failed to connect to bus: No such file or directory
[   25.513394] scsi 0:0:0:2: Direct-Access     NVMe     KXG50PNV2T04 NVM 4104 PQ: 0 ANSI: 6
[   25.530352] sd 0:0:0:2: Attached scsi generic sg2 type 0
[   25.531478] sd 0:0:0:2: [sdc] 4000797360 512-byte logical blocks: (2.05 TB/1.86 TiB)
[   25.532809] sd 0:0:0:2: [sdc] Write Protect is off
[   25.533439] sd 0:0:0:2: [sdc] Mode Sense: 0f 00 00 00
[   25.535467] sd 0:0:0:2: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   25.545744]  sdc: sdc1 sdc2 sdc3 sdc4 sdc5
[   25.549952] sd 0:0:0:2: [sdc] Attached SCSI disk
[   25.562617] Failed to connect to bus: No such file or directory
[   25.815706] Failed to connect to bus: No such file or directory
[   26.069414] Failed to connect to bus: No such file or directory
[   26.323978] Failed to connect to bus: No such file or directory
Queued start job for default target Graphical Interface.
-.slice: Failed to migrate controller cgroups from /, ignoring: Input/output error
```

Also, `/proc/sys/fs/binfmt_misc/WSLInterop` does not exist!

```
$ ls -la /proc/sys/fs/binfmt_misc/
total 0
drwxr-xr-x 2 root root 0 Aug  4 14:28 .
dr-xr-xr-x 1 root root 0 Aug  4 14:28 ..
-rw-r--r-- 1 root root 0 Aug  4 14:29 python3.10
--w------- 1 root root 0 Aug  4 14:28 register
-rw-r--r-- 1 root root 0 Aug  4 14:28 status
```

The setting can be set with
```
$ sudo su -
# echo ":WSLInterop:M::MZ::/init:" > /proc/sys/fs/binfmt_misc/register
```

which makes the file appear:
```
 $ ls -la /proc/sys/fs/binfmt_misc/
total 0
drwxr-xr-x 2 root root 0 Aug  4 14:28 .
dr-xr-xr-x 1 root root 0 Aug  4 14:28 ..
-rw-r--r-- 1 root root 0 Aug  4 17:47 WSLInterop
-rw-r--r-- 1 root root 0 Aug  4 14:29 python3.10
--w------- 1 root root 0 Aug  4 17:47 register
-rw-r--r-- 1 root root 0 Aug  4 14:28 status
```

And `CMD.EXE` can now be run:
```
$ /mnt/c/Windows/System32/cmd.exe /c ver
'\\wsl.localhost\Ubuntu\home\mdr\projects\humhub\htdocs'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Microsoft Windows [Version 10.0.19045.3271]
```

However, this seems to fix only part of the issue. But may be helping in getting to the source of the problem.

Btw, #10359 seems to be the same issue.

**Comment by martin-rueegg** [comment]
https://github.com/microsoft/WSL/issues/9353#issuecomment-1356459891 indicates that disabling `systemd` would solve the issue. However, in my case, the issue only appeared today after reboot, while I was already using `systemd` before.

**Comment by martin-rueegg** [comment]
[`sudo apt purge wslu`](https://askubuntu.com/a/1453085) **did not** resolve the issue.

**Comment by Flydiverny** [comment]
Also tried to nuke wslu earlier today with no luck. Uninstalled it and reinstalled it.

> [#9353 (comment)](https://github.com/microsoft/WSL/issues/9353#issuecomment-1356459891) indicates that disabling `systemd` would solve the issue. However, in my case, the issue only appeared today after reboot, while I was already using `systemd` before.

Based on this I just tried to disable systemd, which I've also been having enabled for a really long time. But I don't really depend on it. VSCode launches again however still get some weird errors on some commands.

Enabling `systemd` again causes issues again:
```
❯ wsl.exe --shutdown
exec: Failed to execute process: '/mnt/c/windows/system32/wsl.exe' the file could not be run by the operating system.
```
which works fine before, or when I disable systemd.. 🤔

Seems like this has broken for a bunch of people during the last day.

```
wsl.exe --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1992
```

**Comment by martin-rueegg** [comment]
Since this might be a regression (by WSL or Ubuntu) that potentially is going to affect more and more people, I'm just trying to get some attention: @DHowett, @craigloewen-msft. Thanks!

**Comment by renanlido** [comment]
Hy guys, i have the same issue 

`🤞 code .
/mnt/c/Users/myUser/AppData/Local/Programs/Microsoft VS Code/bin/code: 61: /mnt/c/Users/myUser/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error`

😫

**Comment by younes0** [comment]
@martin-rueegg same situation here, also I can't run windows executables from WSL anymore
```bash
Failed to execute process '/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe'. Reason:
exec: unknown error (errno was 8)
The file '/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe' is marked as an executable but could not be run by the operating system.
```

**Comment by elsaco** [comment]
@younes0 look for `/proc/sys/fs/binfmt_misc/WSLInterop` file. If missing, that's the issue.

**Comment by younes0** [comment]
@elsacoI I couldn't check, I removed the [KB5028244](https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c) Windows Update and had to turn on again WSL/Hyper-V features as mentionned on https://superuser.com/a/1736464/256461 
**Everything is working now.** I suspended Windows Updates for now.

But you must be right, I managed to exec Windows executables when [KB5028244](https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c) was installed by following this solution : https://stackoverflow.com/a/76826327/822837

**Comment by renanlido** [comment]
The solution for my problem was opened /etc/wsl.conf and change the line systemd=true to #systemd=true

I hope this help you!

**Comment by younes0** [comment]
@renanlido thanks but then you disable systemd which I require in my setup

**Comment by elsaco** [comment]
`WSLInterop` is hardcoded into `init` process and is supposed to add `/proc/sys/fs/binfmt_misc/WSLInterop` to the filesystem:

```
 [elsaco@fedora ~]$ strings /init | grep binfmt
<3>WSL (%d) ERROR: %s:%u: binfmt registration failed %d
/proc/sys/fs/binfmt_misc/register
/proc/sys/fs/binfmt_misc
<3>WSL (%d) ERROR: %s:%u: open /proc/sys/fs/binfmt_misc/register failed %d
binfmt_misc
[elsaco@fedora ~]$ strings /init | grep WSLInterop
:WSLInterop:M::MZ::/init:P
:WSLInterop:M::MZ::/init:FP
```

And it does, on distros that don't have `systemd-udev` package installed. This package has `systemd-binfmt.service` that overrides `/proc/sys/fs/binfmt_misc/` and `WSLInterop` file disappears:

`Starting systemd-binfmt.service - Set Up Additional Binary Formats...`

The other unit file, `proc-sys-fs-binfmt_misc.automount` refuses to run:

```
proc-sys-fs-binfmt_misc.automount: Path /proc/sys/fs/binfmt_misc is already a mount point, refusing start.
[FAILED] Failed to set up automount proc-sysΓÇªrmats File System Automount Point.
See 'systemctl status proc-sys-fs-binfmt_misc.automount' for details.

```

**Comment by chinsoon12** [comment]
Following this 
https://github.com/microsoft/WSL/issues/8952#issuecomment-1568212651 

resolved the below for me
`/mnt/c/Program Files/Microsoft VS Code/bin/code: 61: /mnt/c/Program Files/Microsoft VS Code/Code.exe: Exec format error`

**Comment by einarpersson** [comment]
I started seeing this today. Very disrupting. 😢 

```
Microsoft Windows [Version 10.0.19044.3086]
```
```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.3086
```
```
Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023
```
```
Release:        22.04
```

**Comment by rihards-simanovics** [comment]
this has resolved the issue on my wsl: https://github.com/microsoft/WSL/issues/8952#issuecomment-1572193568

**Comment by emeric-martineau** [comment]
In my case, I need to remove `~/.vscode*` folders to slove this issue.

**Comment by brandochn** [comment]
In my case following this:

 > But you must be right, I managed to exec Windows executables when [KB5028244](https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c) was installed by following this solution : https://stackoverflow.com/a/76826327/822837
 
 Resolved the issue.

**Comment by abrahamprz** [comment]
> @elsaco I couldn't check, I removed the [KB5028244](https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c) Windows Update and had to turn on again WSL & VM Machine as mentionned on https://superuser.com/a/1736464/256461 **Everything is working now.** I suspended Windows Updates for now as an annoying workaround
> 
> But you must be right, I managed to exec Windows executables when [KB5028244](https://support.microsoft.com/en-us/topic/july-25-2023-kb5028244-os-build-19045-3271-preview-8cf92c9b-3a60-4c6a-8f4c-fc41fe8f4f2c) was installed by following this solution : https://stackoverflow.com/a/76826327/822837

This also worked for me, I also wasn't able to run `explorer.exe`, but that comment fix it too.

**Comment by welja** [comment]
I just had this problem today.

WSL version: 2.6.3.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.7623

The stackoverflow comment mentioned by @abrahamprz fixed it for me
