### ISSUE TITLE
WSLv1: how to find real throttled laptop CPU frequency

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#10360]
### Windows Version

10.0.22621.1992

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

My Dell XPS 13 throttles CPU quite severely, especially on battery. This makes benchmarking some number crunching CPU programs in WSLv1 quite hard. What's worse is that I couldn't find a way to get the real CPU freq in WSLv1 Ubuntu 20.04. The real CPU freq is reported in Windows Task Manager, but not in WSLv1 Ubuntu 20.04. I've tried some ways recommended for real Ubuntu, but they all report only nominal/constant/max CPU freq.

<img width="582" alt="image" src="https://github.com/microsoft/WSL/assets/1041752/3912f54d-fb57-421c-bac6-42cb34e2824c">

```shell
$ cat /proc/cpuinfo | grep MHz
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000
cpu MHz         : 2918.000

$ cat /sys/devices/system/cpu/cpu0/cpufreq/*
2918000
2918000
``` 

### Expected Behavior

can find from WSLv1 ubuntu real CPU freq (to detect amount of throttling)

### Actual Behavior

always reports 2.90 GHz

**Comment by OneBlue** [comment]
Thank you for reporting this @vadimkantorov. This is the expected behavior since WSL1 doesn't have any way to access real time CPU frequency information.


The only way to get this information would be by using a [win32 API](https://stackoverflow.com/questions/7544049/win32-api-function-to-get-processors-current-speed)

**Comment by vadimkantorov** [comment]
If anyone finds this issue, I found two ways (using WinAPI under the cover):
```
# has no way to stop refreshing, will go on printing perf counters until Ctrl+C is hit
typeperf.exe "\Processor Information(_Total)\Processor Frequen
cy"

# relatively slower to complete, but will just quit after printing the requested info
wmic.exe cpu get name,CurrentClockSpeed,MaxClockSpeed

typeperf.exe -qx | grep Frequency
\Windows Time Service\Clock Frequency Adjustment (PPB)
\Windows Time Service\Clock Frequency Adjustment
\Processor Information(0,0)\% of Maximum Frequency
\Processor Information(0,1)\% of Maximum Frequency
\Processor Information(0,2)\% of Maximum Frequency
\Processor Information(0,3)\% of Maximum Frequency
\Processor Information(0,4)\% of Maximum Frequency
\Processor Information(0,5)\% of Maximum Frequency
\Processor Information(0,6)\% of Maximum Frequency
\Processor Information(0,7)\% of Maximum Frequency
\Processor Information(0,_Total)\% of Maximum Frequency
\Processor Information(_Total)\% of Maximum Frequency
\Processor Information(0,0)\Processor Frequency
\Processor Information(0,1)\Processor Frequency
\Processor Information(0,2)\Processor Frequency
\Processor Information(0,3)\Processor Frequency
\Processor Information(0,4)\Processor Frequency
\Processor Information(0,5)\Processor Frequency
\Processor Information(0,6)\Processor Frequency
\Processor Information(0,7)\Processor Frequency
\Processor Information(0,_Total)\Processor Frequency
\Processor Information(_Total)\Processor Frequency
```
