### ISSUE TITLE
Unable load firmware.

### ISSUE THREAD

**Issue by xunanmu** [microsoft/WSL#10370]
### Windows Version

10.0.22621.1992

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu22.04

### Repro Steps

1. make menuconfig Choose cfg80211 and mac80211 as [M].
2. make modules && sudo make modules_install 
3. sudo modprobe mac80211

Then cfg80211 fails to load regulatory.db under /lib/firmware.

Error message:
platform regulatory.0: Direct firmware load for regulatory.db failed with error -2.
cfg80211: failed to load regulatory.db.

![E1CC9D87-0EF7-4734-BD0C-B5A035BB33FB](https://github.com/microsoft/WSL/assets/34336047/a2bf3586-7b29-463c-a34e-7cc774adc34a)

### Expected Behavior

正常加载regulatory.db 

### Actual Behavior

[  752.936630] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[  752.936760] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[  752.936806] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  752.936809] cfg80211: failed to load regulatory.db
![E1CC9D87-0EF7-4734-BD0C-B5A035BB33FB](https://github.com/microsoft/WSL/assets/34336047/a2bf3586-7b29-463c-a34e-7cc774adc34a)

**Comment by OneBlue** [comment]
Thank you for reporting this. Kernel modules are not officially supported. Closing since we already have issues for kernel modules support
