### ISSUE TITLE
Maximize windows no longer works correct after installing pre-release

### ISSUE THREAD

**Issue by jepet** [microsoft/WSL#10372]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

1.3.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.90.4-1

### Distro Version

Ubuntu 20.04

### Other Software

IntelliJ

### Repro Steps

Open IntelliJ and maximize the window.

### Expected Behavior

Starting IntelliJ
Double click on the window bar to maximize the window
The window fills the entire screen and mouse actions relate to the artifacts in the application.

### Actual Behavior

The window is not completely maximized
Clicking in the editor with the mouse places the cursor about a line below the mouse pointer
The top bar is now no longer accessible and the window can no longer be minimized/return to its former size

### Diagnostic Logs

...
[WslLogs-2023-08-08_09-59-38.zip](https://github.com/microsoft/WSL/files/12288800/WslLogs-2023-08-08_09-59-38.zip)

**Comment by jonasPoehler** [comment]
Hi @jepet, we had the same issue with IntelliJ >=2023.2, but I think this is actually a bug in IntelliJ since this seems to also occur with some tiling window managers in pure Linux (https://youtrack.jetbrains.com/issue/IDEA-323700). Try with another application (like a browser) and especially check out the workaround for IntelliJ.

**Comment by jepet** [comment]
Ah - that's so nice. Thanks @jonasPoehler! I did the mistake of changing more than one thing at once (upgraded IntelliJ and wsl at the same time...)

Hope they get this fixed soon - the merge of the main menu into the window title is actually quite nice :-)
