### ISSUE TITLE
Flashing Blue Spinner on 1.3.15

### ISSUE THREAD

**Issue by Connortsui20** [microsoft/WSL#10385]
### Windows Version

Microsoft Windows [Version 10.0.19045.3208]

### WSL Version

1.3.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Downloaded the 1.3.15 pre-release package, and on every startup of WSL the blue spinner next to my cursor flickered indefinitely. The only way to stop it from flickering that I found was to go into Task Manager and stop whatever WSL related executable was running. One of them was `wslhost.exe`, another was the full name, etc...

Unfortunately I immediately uninstalled the package and went to 1.2.5, and that solved the issue. I know 1.3.15 is a pre-release though so I thought I'd give a heads up here just in case, I just don't have the time to test more myself.

### Expected Behavior

I expected it to not have a flashing blue spinner

### Actual Behavior

There was a flashing blue spinner that kept flashing indefinitely.

**Comment by pmartincic** [comment]
I think you want to refile this issue under https://github.com/microsoft/wslg/issues. Make sure to fill out the template and provide all the logs that they ask for.
