### ISSUE TITLE
Processing fstab with mount -a failed.

### ISSUE THREAD

**Issue by Mikes-Git** [microsoft/WSL#10398]
### Windows Version

Microsoft Windows [Version 10.0.22000.2295]

### WSL Version

WSL-Version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Standardversion: 2

### Repro Steps

Typing wsl or any other wsl command (wsl ls)
PS C:\WINDOWS\system32> wsl
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:370: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:374: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:577: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:586: Create process not expected to return

### Expected Behavior

show me data

### Actual Behavior

PS C:\WINDOWS\system32> wsl
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:370: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:374: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:577: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:586: Create process not expected to return

**Comment by OneBlue** [comment]
Thank you for reporting this @Mikes-Git. Can you share the content of `/etc/fstab` ?
