### ISSUE TITLE
Exec format Error not solved with wsl.conf in /etc/binfmt. Trying to delete .vscode-server turns entire WSL filesystem to read-only

### ISSUE THREAD

**Issue by MikeBarberry** [microsoft/WSL#10391]
### Windows Version

Microsoft Windows [Version 10.0.19045.3324] 

### WSL Version

WSL version: 1.2.5.0  

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

22.04

### Other Software

Visual Studio Code latest (8/14/23) and after downgrade to 1.80.2. 

### Repro Steps

Try to open VSCode from WSL2 with code command (e.g. code <some_folder>

### Expected Behavior

It opens VSCode in WSL remote window.

### Actual Behavior

It exits with "Exec format error". 

Creating wsl.conf file in /etc/binfmt and adding ":WSLInterop:M::MZ::/init:PF" did not work as it did when I encountered the exact same error on another machine running Windows 11. 

On this PC, the error persists. Attempting to delete .vscode-server results in the operation failing and turning my entire WSL filesystem into read-only.

**Comment by tinlittle** [comment]
Same "Exec format error" on Fedora 38 and openSUSE Tumbleweed as well. No systemd enabled.

This applies to VS Code 1.8.1 and the latest VS Code-insiders.

Worked once between multiple Windows reboots. But only once among multiple reboots.

**Comment by mmontesi** [comment]
Exactly the same, creating wsl.conf file in /etc/binfmt and adding ":WSLInterop:M::MZ::/init:PF" did not work.
I tried to disable systemd but no luck.
When I start WSL the first time I can run Windows executables as usual, but after a minute (more or less) it stops working.

**Comment by mmontesi** [comment]
UPDATE I fixed it upgrading to WSL 1.3.15 (`wsl --update --pre-release`), unfortunately it's not a stable version, so I don't know if it's fit for everyone.
I use VPNs and wsl-vpnkit and just discovered that this tool breaks the possibility to run Windows executables if you run it in `distro` mode, I had to set it up as a standalone script https://github.com/sakai135/wsl-vpnkit#setup-as-a-standalone-script.
It has always worked both ways, but something weird happened in the last weeks. (Win updates, etc)

**Comment by babysnakes** [comment]
I have the same problems (starting about a week ago) on all my distributions:

* ubuntu 20.04 LTS systemd disabled
* Ubuntu 22.04 LTS systemd enabled
* Arch Linux systemd disabled

They all worked flowlessly until a few days ago. I'm not sure what is the workaround of `wsl.conf` inside `/etc/binfmt` so I didn't try it.

Thanks

**Comment by MikeBarberry** [comment]
I was able to fix this on Windows 10 by also using fsck on /dev/sdc. First, I had to umount and find / kill all snap processes that were preventing unmounting.

**Comment by pmartincic** [comment]
This looks to me like something you've installed has broken the binfmt registration. And unfortunately binfmt_misc is not namespaced. So if you have multiple distros open, and one of them nukes the registration here, then interop won't work anymore (Calling windows executables from within the guest). Do you still have `/proc/sys/fs/binfmt_misc/WSLInterop`?

```
cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a

**Comment by zcobol** [comment]
Until a fix will be released, if using `systemd` mask `proc-sys-fs-binfmt_misc.mount` and `systemd-binfmt.service` inside each WSL distro. This prevents `/proc/sys/fs/binfmt_misc/WSLInterop` registration from breaking.
