### ISSUE TITLE
Unable to start .exe files after Debian12 update

### ISSUE THREAD

**Issue by Fede2782** [microsoft/WSL#10404]
### Windows Version

Microsoft Windows [Versione 10.0.22621.2213]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian 12

### Repro Steps

Open a fresh Debian installation and then run "explorer.exe ." or any other .exe file

### Expected Behavior

Before Debian 12 if I executed .exe they would start normally

### Actual Behavior

-bash: /mnt/c/Windows/explorer.exe: cannot execute binary file: Exec format error

**Comment by HUAHUAI23** [comment]
I'm having the same problem.

**Comment by U3erKa** [comment]
I had the same problem on ubuntu. The solution/workaround recently got mentioned in #8843 and #8952

Run this in bash:

```sh
sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
```

After that restart your WSL distro:

```bat
wsl --shutdown
```

**Comment by Fede2782** [comment]
It works. However it should be included out of the box as it happened before Debian12
