### ISSUE TITLE
Issue with --set-default command

### ISSUE THREAD

**Issue by Siddharth1India** [microsoft/WSL#10405]
### Windows Version

Version 10.0.19045.3324

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Repro Steps

![image](https://github.com/microsoft/WSL/assets/46651743/38bcc00c-3e0c-478c-8fd4-368e970d052c)

### Expected Behavior

Change from WSL 1 to 2

### Actual Behavior

Not changing version

**Comment by 0xbadfca11** [comment]
Maybe `--set-version`.
