### ISSUE TITLE
Better exit codes for WSL cmd

### ISSUE THREAD

**Issue by KarelChanivecky** [microsoft/WSL#10414]
**Is your feature request related to a problem? Please describe.**
It is difficult to use WSL in another program because a lot of different issues seem to cause WSL to exit with the same code.
Also, it is difficult to understand all the different reasons that can cause the WSL cmd to fail.

Some examples of some of the errors I have ran into:
- WSL is not enabled at all
- WSL kernel is not installed/out of date
- VM/Container took too long to respond
- Distro is not installed
- File not found error when importing distro
- Distro name is already taken
- install path of distro is not available

**Describe the solution you'd like**
A unique, explicit exit code for each problem that occurs. The exit codes are listed in the WSL documentation.

**Describe alternatives you've considered**
I currently use a combination of return code and matching resulting text from stdout/stderr to determine the WSL state.
The matching text within stdout/stderr is very unreliable, as the text can change on a developer's whim, but there is no other way that I know of.

**Comment by OneBlue** [comment]
Thank you for the suggestion @KarelChanivecky. Unfortunately this would be an API change since other programs depend on existing return codes so this is not a change we can make without causing major issues for existing users.

**Comment by KarelChanivecky** [comment]
Of course that would be a breaking change. However, there is always the possibility of providing a separate executable meant for programmatic use.
