### ISSUE TITLE
Module loop not found

### ISSUE THREAD

**Issue by badgeminer** [microsoft/WSL#10412]
### Windows Version

Microsoft Windows [Version 10.0.22621.2134]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu and Ubuntu-22.04

### Repro Steps

run `sudo modprobe loop`

### Expected Behavior

not return an error

### Actual Behavior

results in `modprobe: FATAL: Module loop not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2`

**Comment by zcobol** [comment]
@badgeminer unless you build a custom kernel, the default WSL has everything built-in, no modules, so you're seeing expected behavior.

**Comment by badgeminer** [comment]
k thanks
