### ISSUE TITLE
Unable to mount SATA hard drive: Wsl/Service/AttachDisk/0x80070032

### ISSUE THREAD

**Issue by CliffracerX** [microsoft/WSL#10416]
### Windows Version

Microsoft Windows [Version 10.0.25931.1010]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Determined drive path through the wmic disklist function (PHYSICALDRIVE1), unmounted all partitions through diskmgmt, ran WSL mount with the ``bare`` modifier as follows:
```wsl --mount \\.\PHYSICALDRIVE1 --bare```

### Expected Behavior

The intended WSL mount functionality; bare-mounting it so I can give WSL the full drive and then pass through it to access both its EXT4 and NTFS partitions.

### Actual Behavior

```
$ wsl --mount \\.\PHYSICALDRIVE1 --bare
The request is not supported.
Error code: Wsl/Service/AttachDisk/0x80070032
```

Of note, this happens be it with ``--bare`` or specifically targeting a partition (e.g, the known ext-4 partition ``--partition 4``), as well as when targeting my other external data drive (``\\.\PHYSICALDRIVE0``)

### Diagnostic Logs

Diskdrive output
```
C:\Windows\System32>wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType              Model                   Name                Partitions
              {3, 4}        {"Random Access", "Supports Writing"}                        \\.\PHYSICALDRIVE2  SCSI           TRUE         Fixed hard disk media  WDS200T1X0E-00AFY0      \\.\PHYSICALDRIVE2  5
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media  WDC WD4005FZBX-00K5WB0  \\.\PHYSICALDRIVE0  1
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE1  IDE            TRUE         Fixed hard disk media  TOSHIBA DT01ACA200      \\.\PHYSICALDRIVE1  4
```
WSL Logs
[WslLogs-2023-08-23_18-34-12.zip](https://github.com/microsoft/WSL/files/12423773/WslLogs-2023-08-23_18-34-12.zip)

**Comment by zcobol** [comment]
@CliffracerX the interface type is `IDE` but your hard drive is `SATA` capable, it should show `InterfaceType=SCSI`. How do you connect your hard drive?

**Comment by OneBlue** [comment]
Indeed, wsl --mount only supports SCSI disks at the moment so this is why you're seeing this error

**Comment by CliffracerX** [comment]
> @CliffracerX the interface type is `IDE` but your hard drive is `SATA` capable, it should show `InterfaceType=SCSI`. How do you connect your hard drive?

They're connected by some cables yoinked from the drive bays on the old computer I pulled them from; my current one doesn't have proper drive bays so I had to make do with some bodge-job mounting and cabling.

> Indeed, wsl --mount only supports SCSI disks at the moment so this is why you're seeing this error

This would explain it, then- unfortunate that I'll need to futz with the setup to get them supported, but good to know it's user error on my part!
