### ISSUE TITLE
interop reads all stdin

### ISSUE THREAD

**Issue by ilatypov** [microsoft/WSL#10429]
### Windows Version

Microsoft Windows [Version 10.0.19043.2364]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Debian 12

### Other Software

Not a fan of Docker Desktop, I am sticking to the older docker.io 20.10.24.  But it has nothing to do with WSL and I did not run it.

### Repro Steps

In the GUI Windows Terminal:
```
$ for ((i=1; i<=3; i++)); do read -r line || echo huh; echo "$i: ${line}"; java.exe 2> /dev/null || :; done <<< $'one\ntwo\nthree'
```

### Expected Behavior

```
$ for ((i=1; i<=3; i++)); do read -r line || echo huh; echo "$i: ${line}"; true 2> /dev/null || :; done <<< $'one\ntwo\nthree'
1: one
2: two
3: three
```

### Actual Behavior

```
1: one
huh
2:
huh
3:
```

**Comment by ilatypov** [comment]
Work-around: make the interop invocation read from somewhere else.
```
$ for ((i=1; i<=3; i++)); do read -r line || echo huh; echo "$i: ${line}"; java.exe 2> /dev/null < /dev/null || :; done <<< $'one\ntwo\nthree'
1: one
2: two
3: three
```

**Comment by pmartincic** [comment]
I don't see what you see. Perhaps I'm misreading something. I'm gonna need more information on what's need to reproduce this issue.

<img width="1063" alt="image" src="https://github.com/microsoft/WSL/assets/102559858/fa3cd38b-e6e9-4f87-9ab3-2716dbf88900">

**Comment by ilatypov** [comment]
In a Command Prompt started as an Administrator,
```
choco install openjdk
```

In WSL (in my case, Debian),
```
$ for ((i=1; i<=3; i++)); do read -r line || echo huh; echo "$i: ${line}"; "/mnt/c/Program Files/OpenJDK/jdk-21.0.1/bin/java.exe" 2> /dev/null || :; done <<< $'one\ntwo\nthree'
1: one
huh
2:
huh
3:
```

```
$ "/mnt/c/Program Files/OpenJDK/jdk-21.0.1/bin/java.exe" -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)
```
