### ISSUE TITLE
Automatically create missing root account when importing custom distribution

### ISSUE THREAD

**Issue by thawkins** [microsoft/WSL#10427]
When importing some distribution images, from say cloud images or other sources, the image does not contain any defined users or their home directories. No error message is given during import, bu this results in a distribution that cannot be started as it cannot locate the account for the user or for "root", launch fails with an error. 

if a distribution is imported, and WSL2 determines that there is no root account available in the image, that one be crested automatically, that a /root folder is created and a root user created with no password, and with a suitable login shell.

I am unable to think of a solution other than manipulating the source image

**Comment by OneBlue** [comment]
WSL doesn't touch the distribution configuration at all. When importing a distro, setting up user accounts is the distribution's responsibility, no WSL's.
