### ISSUE TITLE
Error 0x80004005 when trying to register Kali Linux

### ISSUE THREAD

**Issue by ebrocoli** [microsoft/WSL#10424]
### Windows Version

Version 10.0.22000.2295

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Kali Linux

### Repro Steps

I was enabling WSL with the steps that Microsoft already listed
Then i tried to install Kali Linux, which the installation is succesfull
But when i typed `kali` it started to show `Installing, this may take a few minutes...`
And then the error happened, but this only happens with Kali and not other distros
I tried Ubuntu and Debian which worked fine so far

### Expected Behavior

`Installing, this may take a few minutes...                                                                              Please create a default UNIX user account. The username does not need to match your Windows username.                   For more information visit: https://aka.ms/wslusers                                                                     Enter new UNIX username:  `

### Actual Behavior

`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error`

**Comment by TuanDung0902** [comment]
I also got same problem while trying to register Kali Linux although I can register Ubuntu normally.

**Comment by TuanDung0902** [comment]
I have same problem with Kali Linux, but I found a solution is installing WSL from Microsoft Store.

**Comment by Lopez017** [comment]
can you post a link to which WSL you used from the Microsoft store?

**Comment by TuanDung0902** [comment]
> can you post a link to which WSL you used from the Microsoft store?
> 

Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

**Comment by Gabistakk** [comment]
im also having this issue, with kali linux.
tried all the fixes online but none works.

**Comment by TuanDung0902** [comment]
> im also having this issue, with kali linux.
> tried all the fixes online but none works.

Have you try to install WSL from MS Store?

**Comment by Gabistakk** [comment]
yeah it worked **thank you so much**!
for others what i did was (after installing WSL from MS store): 
in the windows power shell: "wsl.exe --list --online"
it returns a list of the distros avaible.
then 'wsl.exe --install <Distro>'

**Comment by TuanDung0902** [comment]
> yeah it worked **thank you so much**!
> for others what i did was (after installing WSL from MS store): 
> in the windows power shell: "wsl.exe --list --online"
> it returns a list of the distros avaible.
> then 'wsl.exe --install (distro name)'

No problem :)

**Comment by nateesh** [comment]
for me `wsl --update` and also setting LxssManager to automatic (via services or regedit) worked.

**Comment by TaoKe-One** [comment]
> 对我来说`wsl --update`，还将 LxssManager 设置为自动（通过服务或注册表）也有效。

Very Good,Thank you for solving my problem！

**Comment by id-widi** [comment]
> yeah it worked **thank you so much**! for others what i did was (after installing WSL from MS store): in the windows power shell: "wsl.exe --list --online" it returns a list of the distros avaible. then 'wsl.exe --install (distro name)'

i tried to install kali linux as you methode but don't work with me.

wsl --install -d kali-linux

but after few second show same problem, error "WslRegisterDistribution failed with error: 0x80004005"

what i do for solving this problem is editing registry lxssManager to value 2, manual install with powershell, and direct install from microsoft store. 

oh btw i use windows 11.

**Comment by ihynar** [comment]
> > yeah it worked **thank you so much**! for others what i did was (after installing WSL from MS store): in the windows power shell: "wsl.exe --list --online" it returns a list of the distros avaible. then 'wsl.exe --install (distro name)'
> 
> i tried to install kali linux as you methode but don't work with me.
> 
> wsl --install -d kali-linux
> 
> but after few second show same problem, error "WslRegisterDistribution failed with error: 0x80004005"
> 
> what i do for solving this problem is editing registry lxssManager to value 2, manual install with powershell, and direct install from microsoft store.
> 
> oh btw i use windows 11.

first use wsl.exe --update

**Comment by Junior-Programming** [comment]
wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

wsl --install -d kali-linux
Installing: Kali Linux Rolling
Kali Linux Rolling has been installed.
Launching Kali Linux Rolling...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

Press any key to continue...


i keep getting error

**Comment by Duodecimy** [comment]
> wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> 
> wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> 
> Press any key to continue...
> 
> i keep getting error

Did you try to edit registry lxssManager to value 2?
What I did:
1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
2. run powershell in administrator mode -> wsl --update
3. kali
4. then it worked!

**Comment by alkebe** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

This worked for me also.
Thanks

**Comment by nshettys** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

Thanks a ton!!! This worked for me. Thanks again

**Comment by Algunas** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
>     1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 
>     2. run powershell in administrator mode -> wsl --update
> 
>     3. kali
> 
>     4. then it worked!

Thanks!!

**Comment by ShabbirMehdi110** [comment]
> wsl.exe --list --online

bro you are genius it take my whole day for kali linux these method works

**Comment by veelorn** [comment]
Hi, I try "wsl --update" and then "wsl --install -d <distribution>" Its worked for me

**Comment by veelorn** [comment]
> ### Windows Version
> Version 10.0.22000.2295
> 
> ### WSL Version
> 0.0.0.0
> 
> ### Are you using WSL 1 or WSL 2?
> * [x]  WSL 2
> * [ ]  WSL 1
> 
> ### Kernel Version
> 5.10.16
> 
> ### Distro Version
> Kali Linux
> 
> ### Other Software
> _No response_
> 
> ### Repro Steps
> I was enabling WSL with the steps that Microsoft already listed Then i tried to install Kali Linux, which the installation is succesfull But when i typed `kali` it started to show `Installing, this may take a few minutes...` And then the error happened, but this only happens with Kali and not other distros I tried Ubuntu and Debian which worked fine so far
> 
> ### Expected Behavior
> `Installing, this may take a few minutes... Please create a default UNIX user account. The username does not need to match your Windows username. For more information visit: https://aka.ms/wslusers Enter new UNIX username: `
> 
> ### Actual Behavior
> `Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error`
> 
> ### Diagnostic Logs
> _No response_

Hi, I try "wsl --update" and then "wsl --install -d " Its worked for me

**Comment by Yaser-Ebrahimi** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

This worked for me also.
Thanks

**Comment by Yanis0alpha** [comment]
pour mi toujour pas 

PS C:\Windows\system32> wsl --update
Installation en cours : Sous-système Windows pour Linux
Sous-système Windows pour Linux a été installé.
PS C:\Windows\system32> kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80072746
Error: 0x80072746 Une connexion existante a d¹ Ûtre fermÚe par l?h¶te distant.

Press any key to continue...
PS C:\Windows\system32>

**Comment by permadidevelopersofficial** [comment]
semua tips yang anda berikan tidak berhasil untuk saya, entah apa yang terjadi, saya tidak tahu

**Comment by dhruvsharma1904** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

thanks a lot dude!

**Comment by isaga7** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

help me it didnt work for me, still says error

**Comment by Pinto-Katende-Jonathan** [comment]
> > > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > > Press any key to continue...
> > > i keep getting error
> > 
> > 
> > Did you try to edit registry lxssManager to value 2? What I did:
> > 
> > 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> > 2. run powershell in administrator mode -> wsl --update
> > 3. kali
> > 4. then it worked!
> 
> help me it didnt work for me, still says error

Make sure to unregistered your old kali (or installez it), and follow these steps : https://github.com/microsoft/WSL/issues/10424#issuecomment-1807888925

**Comment by 01in123** [comment]
Hello I have a problem with Kali Linux and hoping somebody could help me. It says this when I try to start it up.
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
Error: 0x8007019e Windows-undersystem til Linux er ikke blevet aktiveret.

**Comment by stasbalazuk** [comment]
win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
run powershell in administrator mode -> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Wait for the PC to reboot and check if it works.

**Comment by MuhammetSonmez** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

I've tried every possible way to solve the problem for the past few hours, and this worked for me, thank you :)

**Comment by afifafifafifafifali** [comment]
this worked for me too

**Comment by javidmajidov2023** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

THANK YOUUUUU BROOOO THANKSSSZSS TYSMMMMMMMMMMMMM

**Comment by ITZalireza2008** [comment]
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error 
can anyone help me with this error when i run kali in cmd

**Comment by Pinto-Katende-Jonathan** [comment]
> WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error can anyone help me with this error when i run kali in cmd

Just remove the distribution, and reinstall it using PowerShell as administrator

**Comment by bae-mars** [comment]
> > > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > > Press any key to continue...
> > > i keep getting error
> > 
> > 
> > Did you try to edit registry lxssManager to value 2? What I did:
> > 
> > 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> > 2. run powershell in administrator mode -> wsl --update
> > 3. kali
> > 4. then it worked!
> 
> help me it didnt work for me, still says error

dude were u able to fix it? pls help me too i am also facing same problem as u :(

**Comment by d0lla646** [comment]
> I have same problem with Kali Linux, but I found a solution is installing WSL from Microsoft Store.

Thx

> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

thx bld

**Comment by LenTrex28** [comment]
> > > > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > > > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > > > Press any key to continue...
> > > > i keep getting error
> > > 
> > > 
> > > Did you try to edit registry lxssManager to value 2? What I did:
> > > 
> > > 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> > > 2. run powershell in administrator mode -> wsl --update
> > > 3. kali
> > > 4. then it worked!
> > 
> > 
> > help me it didnt work for me, still says error
> 
> Make sure to unregistered your old kali (or uninstall it), and follow these steps : [#10424 (comment)](https://github.com/microsoft/WSL/issues/10424#issuecomment-1807888925)
> 
> ( **Unregistration**
> 
> ```shell
> wsl --unregister <DistributionName>
> ```
> 
> Replace `<DistributionName>` with the name of the distribution you want to unregister. For example, if you want to unregister the "Ubuntu" distribution, the command would be:

still just isnt working

**Comment by bae-mars** [comment]
I actually took my 2nd laptop and installed kali without any error :)

**Comment by YigitOzdemir34** [comment]
> 1. Make sure to use Powershell (as adminstrator) instead of cmd
> 2. Type these two commands :
>    
>    * `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
>    * `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all`
> 3. Download and install the WSL 2 Linux Kernel from here: [aka.ms/wsl2kernel](https://aka.ms/wsl2kernel)
> 4. Restart
> 5. Open again Powershell
> 6. Type : `wsl --set-default-version 2`
> 7. Install KALI : `wsl --install --distribution kali-linux`

Did it. Now, 

> 1. Make sure to use Powershell (as adminstrator) instead of cmd
> 2. Type these two commands :
>    
>    * `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
>    * `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all`
> 3. Download and install the WSL 2 Linux Kernel from here: [aka.ms/wsl2kernel](https://aka.ms/wsl2kernel)
> 4. Restart
> 5. Open again Powershell
> 6. Type : `wsl --set-default-version 2`
> 7. Install KALI : `wsl --install --distribution kali-linux`

Did it. Now i cant watch any videos on youtube. HOW DID THIS HAPPENED???

**Comment by YigitOzdemir34** [comment]
> 1. Make sure to use Powershell (as adminstrator) instead of cmd
> 2. Type these two commands :
>    
>    * `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
>    * `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all`
> 3. Download and install the WSL 2 Linux Kernel from here: [aka.ms/wsl2kernel](https://aka.ms/wsl2kernel)
> 4. Restart
> 5. Open again Powershell
> 6. Type : `wsl --set-default-version 2`
> 7. Install KALI : `wsl --install --distribution kali-linux`

Thank you. İt Works!!

**Comment by nomore1007** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

Thank you for the link. I tried to search for it in the store, but it was not to be found. This link brought me right to it.

**Comment by TheMrM** [comment]
> for me `wsl --update` and also setting LxssManager to automatic (via services or regedit) worked.

This worked for me as well.

**Comment by piaono3** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

Thank so much bro. It worked

**Comment by UsamaMo** [comment]
Thank you so much everyone!

**Comment by MishanGhimire** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

Press any key to continue...

**Comment by MishanGhimire** [comment]
> Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> 
> Press any key to continue...

I used this too wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.
PS C:\Windows\system32> wsl --install --distribution kali-linux
Kali Linux Rolling is already installed.
Launching Kali Linux Rolling...
PS C:\Windows\system32>

**Comment by MR-LeonardoGomes** [comment]
Friend you just need to install " wsl --set-default-version 2 " 

https://learn.microsoft.com/pt-br/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by MishanGhimire** [comment]
> Friend you just need to install " wsl --set-default-version 2 "
> 
> https://learn.microsoft.com/pt-br/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
still got error saying Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

Press any key to continue...

**Comment by MishanGhimire** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

Press any key to continue...

**Comment by 1ambd4** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

Works for me, thanks a lot.

**Comment by MR-LeonardoGomes** [comment]
bro cmd  admin "wsl --set-default-version 2" Enter

**Comment by MishanGhimire** [comment]
> bro cmd admin "wsl --set-default-version 2" Enter

not working still bro

**Comment by Pinto-Katende-Jonathan** [comment]
Use these commands in powers powershell with admin right

**Comment by tienphat2101** [comment]
> yeah it worked **thank you so much**! for others what i did was (after installing WSL from MS store): in the windows power shell: "wsl.exe --list --online" it returns a list of the distros avaible. then 'wsl.exe --install (distro name)'

Thank you, it works for me now.

**Comment by l-urk** [comment]
- In an admin PowerShell use: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux"
Then...
- In an admin CMD window use: "wsl --update && wsl --install -d DISTRO-NAME"
Replace DISTRO-NAME with your desired distribution.

**Comment by MishanGhimire** [comment]
> * In an admin PowerShell use: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux"
>   Then...
> * In an admin CMD window use: "wsl --update && wsl --install -d DISTRO-NAME"
>   Replace DISTRO-NAME with your desired distribution.

Tried all of it still got this error 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8037010d
Error: 0x8037010d The virtual machine or container JSON document is invalid.

**Comment by l-urk** [comment]
> > * In an admin PowerShell use: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux"
> >   Then...
> > * In an admin CMD window use: "wsl --update && wsl --install -d DISTRO-NAME"
> >   Replace DISTRO-NAME with your desired distribution.
> 
> Tried all of it still got this error Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x8037010d Error: 0x8037010d The virtual machine or container JSON document is invalid.

Check this one out https://github.com/microsoft/WSL/issues/6317

**Comment by adisawant2005** [comment]
> can you post a link to which WSL you used from the Microsoft store?

Search this in Microsoft Store "Windows Subsystem for Linux"

**Comment by l-urk** [comment]
WSL version: 2.2.4.0

**Comment by ErikPervious** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

This work for me in 22/08/24

**Comment by adisawant2005** [comment]
It's the same, the original one on Microsoft Store

**Comment by l-urk** [comment]
it is the same.

**Comment by Makvagabo** [comment]
I am not positive that my experience can be helpful but I had the same trouble with installation and running of any distributive. I have been trying I think almost everything I could find on the internet. Unfortunately it worked nothing.
I went to extreme - Reset my PC. Yes, I have lost something, especially time, but finally WLS2 works properly without any movements.

![image](https://github.com/user-attachments/assets/ae5470e4-75e4-438d-9538-bebfa6b60e67)

**Comment by Coti7** [comment]
> yeah it worked **thank you so much**! for others what i did was (after installing WSL from MS store): in the windows power shell: "wsl.exe --list --online" it returns a list of the distros avaible. then 'wsl.exe --install (distro name)'

That worked for me. Thanks!

**Comment by james28909** [comment]
i was having the same error code as op, then i realized i was in an admistrative cmd. opened a regular cmd and ran the wsl --install command and it worked

**Comment by Ankit-Ojha16** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
>     1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 
>     2. run powershell in administrator mode -> wsl --update
> 
>     3. kali
> 
>     4. then it worked!

Thanks its working for me.

**Comment by barkamol-valiy** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

thanks dude, Kali is working ))

**Comment by bozo88** [comment]
Can I suggest renaming or deleting .wslconfig

I've just spent 1.5 hours trying to solve this and simply deleting .wslconfig has solved the problem

**Comment by szpytka** [comment]
nothing mentioned above worked for me, but I found the final solution.

1. Delete the file at %UserProfile%\.wslconfig (only if exists, if not just skip this step)

2. Create an empty file at %UserProfile%\.wslconfig

3. Inside the file paste:
[wsl2]
memory=4GB # Limits VM memory in WSL 2 to 4 GB
processors=2 # Makes the WSL 2 VM use two virtual processors

4. Run PowerShell as an administrator and paste:
a) wsl --set-default-version 2
b) wsl --install -d kali-linux

Thanks 😁

**Comment by David-Muithya** [comment]
> > can you post a link to which WSL you used from the Microsoft store?
> 
> Here is the link: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

it also workedfor me nigga , thanks a lot

**Comment by xdevman9** [comment]
I am getting this error
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.

Press any key to continue...

**Comment by Devloop69** [comment]
How do I uninstall and re-install wsl from Microsoft Store?

**Comment by valdogarnica** [comment]
> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!



> > wsl --update Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed.
> > wsl --install -d kali-linux Installing: Kali Linux Rolling Kali Linux Rolling has been installed. Launching Kali Linux Rolling... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x80004005 Error: 0x80004005 Unspecified error
> > Press any key to continue...
> > i keep getting error
> 
> Did you try to edit registry lxssManager to value 2? What I did:
> 
> 1. win + R -> regedit -> \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager -> click the start option -> edit the value to 2
> 2. run powershell in administrator mode -> wsl --update
> 3. kali
> 4. then it worked!

funciona, gracias bro

**Comment by GuiGuii28** [comment]
> wsl --update Instalando: Subsistema de Windows para Linux Se ha instalado el subsistema de Windows para Linux.
> 
> wsl --install -d kali-linux. Instalando: Kali Linux Rolling . Kali Linux Rolling se ha instalado. Iniciando Kali Linux Rolling... Instalando. Puede tardar unos minutos... WslRegisterDistribution falló con el error: 0x80004005. Error: 0x80004005. Error no especificado.
> 
> Presione cualquier tecla para continuar...
> 
> Sigo recibiendo un error

Yo realice todo sobre lo de este post y ahora me sale este error 0x80040321

**Comment by AdriProg2000** [comment]
Im doing:
wsl --update
I edited regedit
wsl --install -d kali-linux
and  error 0x80072746

Can you help me?
