### ISSUE TITLE
SSH Tunnel exposed via WSL2 cannot be accessed via Windows Tools

### ISSUE THREAD

**Issue by ashenwgt** [microsoft/WSL#10420]
### Windows Version

Microsoft Windows [Version 10.0.22621.2134]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04

### Other Software

sshuttle, version 1.0.5 ()

### Repro Steps

I'm trying to connect to an AWS ElastiCache Redis instance via an SSH tunnel exposed with WSL2.

On the WSL2 Ubuntu 22.04 terminal, open up an SSH Tunnel using `sshuttle`.
```
sshuttle -vvv --dns -r myserver1 172.16.0.0/16 --python=/usr/bin/python3
```

Verify that the SSH tunnel is working and the AWS ElastiCache Redis instance is visible to access via the WSL2 terminal. 
```
redis-cli -u "redis://XXXXX-redis-elasticache-cluster.XXXXXX.XX.XXXX.XXXX.cache.amazonaws.com:6379" --scan --pattern "auth:*"
```

Try the same on a non-WSL2 terminal (e.g. `git bash`) or software installed on Windows (e.g. RedisInsight) and this connection request times out. 
```
curl XXXXX-redis-elasticache-cluster.XXXXXX.XX.XXXX.XXXX.cache.amazonaws.com
```

### Expected Behavior

SSH Tunnels created on WSL2 must be visible to Windows software and terminal tools as well. 

### Actual Behavior

SSH Tunnel created on WSL2 is not visible to Windows software (e.g. RedisInsight) and terminal tools (e.g. `git bash`).

**Comment by OneBlue** [comment]
Thank you for reporting this @ashenwgt. What's the output of `netstat -lnptu` inside WSL when the tunnel is running ?

**Comment by OneBlue** [comment]
After having a quick look at what sshuttle does, this is expected. sshuttle modifies the routing logic inside WSL, but that change doesn't affect windows. 

WSL only forwards bound ports from the WSL to Windows, but custom interfaces / routing isn't shared.
