### ISSUE TITLE
Cannot copy folder/files with non-english characters

### ISSUE THREAD

**Issue by yagueto** [microsoft/WSL#10445]
### Windows Version

Microsoft Windows [Version 10.0.22621.2134]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

Windows File Explorer

### Repro Steps

- Connect ext4 formatted hard drive
- ```wsl --mount \\.\PHYSICALDRIVE1```
- Open the file explorer and navigate to the folder (```\\wsl.localhost\Ubuntu\mnt\wsl\PHYSICALDRIVE1```)
- Try to copy the folder "Imágenes" to the host
- Error 0x80004005 (unespecified error)

### Expected Behavior

It should copy the file correctly

### Actual Behavior

The copy fails with error 0x80004005 (unespecified error). Also, trying to rename the folder fails with permission denied.

**Comment by pmartincic** [comment]
\logs please

Does this absolutely require that an external drive be mounted into wsl? If the same file is located at `/home/$USER/Imágenes.txt` does it still fail for you?

**Comment by yagueto** [comment]
I've just checked that, if created a file in my local folder with that name manually it works. I also tried to create a "Imágenes.txt" file manually in the hard drive, which works fine as well. It seems like, for some reason, it can't process the file/folder names created before using Windows (created on a Linux machine). When opened from the file explorer it looks like this:

![imagen](https://github.com/microsoft/WSL/assets/48566793/1bcfbc5a-75ab-4a4c-9c70-f7d623639552)

I also tried to rename the folder from the Windows File Explorer, which fails with "the file could not be found". If renamed via WSL terminal (```mv /mnt/wsl/blabla/ /mnt/wsl/blabla2/```) it says permission denied, but works when using sudo and solves all the issue.

**Comment by pmartincic** [comment]
No logs, no clear reproduction instructions, means I don't have anything to go on.

I'm still unclear, did you have to mount an external drive in wsl in order to reproduce this? Because I don't see why this issue would require an external drive. I'm trying to see if you can give me repro instructions without that.

Here I create a file and folder on the guest filesystem copying the name you gave (`/home/me/*`) It also worked via the explorer.exe gui.
```
PS C:\Users\TestVMAdmin> wsl
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

me@PC11c37e7e-3377:/mnt/c/Users/TestVMAdmin$ cd
me@PC11c37e7e-3377:~$ mkdir Imágenes
me@PC11c37e7e-3377:~$ echo meh > Imágenes/Imágenes.txt
me@PC11c37e7e-3377:~$ exit
logout
PS C:\Users\TestVMAdmin> cp -Recurse \\wsl.localhost\Ubuntu\home\me\Imágenes .
PS C:\Users\TestVMAdmin> cat .\Imágenes\Imágenes.txt
meh
