### ISSUE TITLE
Would someone please give #6572 some attention?

### ISSUE THREAD

**Issue by maxb** [microsoft/WSL#10441]
**Is your feature request related to a problem? Please describe.**
No-one has responded to #6572 in over 2 years.

**Describe the solution you'd like**
Respond to and ideally action the simple requested configuration addition.

**Describe alternatives you've considered**
I suppose I could attempt to build my own WSL2 kernel, but that's a lot of work that could be solved by just flipping a config option in the standard build. It's not even that obscure a feature.

**Comment by pmartincic** [comment]
I'm sorry, we are small, we are few. /dupe #6572

@craigloewen-msft, do we have a list of kernel config options that we're tracking and want switched by lsg?
