### ISSUE TITLE
.wslconfig ignored after windows update

### ISSUE THREAD

**Issue by GuidoBallabio** [microsoft/WSL#10442]
### Windows Version

Microsoft Windows [Version 10.0.19045.3393]

### WSL Version

1.3.17.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.4-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Start wsl and check output of `free -h`

### Expected Behavior

Same memory value as in .wslconfig

### Actual Behavior

Half of my RAM

### Description

I ha d my WSL2 setup and workiing with my .wslconfig file as such:

```
[wsl2]
memory=26GB # Limits VM memory
```

encoded UTF-8 with CRLF. The memory in the VM was as configured.

After coming back from th holidays and a windows update it started ignoring my .wslconfig. I checked that it ignored other config values as well.
I tried everything: restart, all windows updates, LF line ending, changing to 6GB memory. Eventually I also update wsl to prerelease and everytime i did `wsl --shutdown` between changes.

Nothing works. What's happening?

**Comment by pmartincic** [comment]
/logs please, I fiddled with the values briefly and could not reproduce the issue, and I'm running the same version as you report.

**Comment by GuidoBallabio** [comment]
Here are the logs of a shutdown and activation of WSL. Hoping it will show the loading of the config.

[WslLogs-2023-09-07_12-51-54.zip](https://github.com/microsoft/WSL/files/12547878/WslLogs-2023-09-07_12-51-54.zip)
