### ISSUE TITLE
Access to windows host service from WSL2

### ISSUE THREAD

**Issue by Ghostman863** [microsoft/WSL#10440]
### Windows Version

Version 10.0.23531.1001

### WSL Version

1.3.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.4

### Distro Version

Ubuntu 22.04

### Repro Steps

Ive got http service on windows host and iam not able to access to it from WSL2. From WSL2 iam not able to ping windows host ip, but all other ip address in network are accessable (computers, routers, NAS...). From windows host iam able to ping WSL2.
WSL ip is 172.23.248.53, windows 192.168.8... and windows WSL adapter is 172.24.240.1.

### Expected Behavior

I just need to open service from windows host (0.0.0.0, 127.0.0.1 ....) in WSL.

### Actual Behavior

wsl is not comunicating with windows host computer over ip.

**Comment by pmartincic** [comment]
Have you tried using the host address on that subnet you see on eth0? In your case `172.24.240.1`
