### ISSUE TITLE
<3>WSL (930) ERROR: UtilTranslatePathList:2803

### ISSUE THREAD

**Issue by kaze-0** [microsoft/WSL#10454]
### Windows Version

Microsoft Windows [Version 10.0.19045.3324]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Once open wsl, terminal prompts:
`<3>WSL (930) ERROR: UtilTranslatePathList:2803: Failed to translate G:\Program Files\Pixeval`

`<3>WSL (930) ERROR: UtilTranslatePathList:2803: Failed to translate G:\Program Files\R\R-4.1.2\bin`

I downloaded and used wsl once before. 
Disk G is removed before I download the new wsl just now.
Seems like there's old configs remaining.

### Expected Behavior

I can still use wsl even though errors prompted. But how to fix those errors?

### Actual Behavior

errors prompted.

```[tasklist]
### Tasks
```

**Comment by kaze-0** [comment]
[WslLogs-2023-09-09_10-46-37.zip](https://github.com/microsoft/WSL/files/12564449/WslLogs-2023-09-09_10-46-37.zip)

**Comment by OneBlue** [comment]
Thank you @kaze-0.

Does the issue also happen if you WSL systemd in /etc/wsl.conf and if you restart WSL ? 

Also what's the content of `/etc/fstab` ?

**Comment by kaze-0** [comment]
Yes. The issue still happen whenever I set false for systemd or not.
Only `# UNCONFIGURED FSTAB FOR BASE SYSTEM` in `/etc/fstab`

**Comment by OneBlue** [comment]
Interesting. Can you share the output of :`wsl echo $PATH`  ? I wonder if you have an old path referring to that drive

**Comment by kaze-0** [comment]
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/dotnet/:/mnt/c/ProgramData/mingw64/bin:/mnt/c/Soft/curl/I386:/mnt/c/Program Files/Calibre2/:/mnt/c/Program Files (x86)/Common Files/Apple/Apple Application Support:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/d/Extra/LLVM/bin:/mnt/d/MATLAB/R2022a/runtime/win64:/mnt/d/MATLAB/R2022a/bin:/mnt/d/Program Files/WinSCP/:/mnt/c/Program Files/nodejs/:/mnt/d/xampp/php:/mnt/d/texlive/2022/bin/win32:/mnt/c/Users/shinelon/scoop/shims:/mnt/c/Users/shinelon/AppData/Local/Programs/Python/Python39/Scripts/:/mnt/c/Users/shinelon/AppData/Local/Programs/Python/Python39/:/mnt/c/Users/shinelon/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/shinelon/.dotnet/tools:/mnt/c/Program Files/Bandizip/:/mnt/d/Program Files/Microsoft VS Code/bin:/mnt/c/ProgramData/mingw64/mingw32/bin:/mnt/c/flutter/bin:/mnt/c/Users/shinelon/AppData/Roaming/npm:/mnt/d/Program Files/PyCharm 2022.3.2/bin:/mnt/c/Users/shinelon/AppData/Roaming/com.nesbox.tic/TIC-80/tic80.exe:/mnt/c/Users/shinelon/AppData/Local/GitHubDesktop/bin:/snap/bin`
Seems like my windows path settings. But no "Pixeval" or "R" path.

**Comment by OneBlue** [comment]
Interesting. Do you have anything that could try to resolve this path in your .bashrc ? 

Can you share the output of `grep -nriF "G:" ~/.*` ?

**Comment by kaze-0** [comment]
I don't find anything trying to resolve this path in .bashrc
 `grep -nriF "G:" ~/.*` keeps prompting so huge amount of contents that I have to press ^C to stop it.

**Comment by jason-matthew** [comment]
Giving anecdotal evidence, issue is seen if your Windows %PATH% contains \\unc locations.

**Comment by kaze-0** [comment]
Thank you. This works.

**Comment by felpsg** [comment]
The issue arises from the Windows and WSL environment path variables conflicting or the WSL attempting to access unavailable paths.
A solution is to prevent WSL from appending the Windows PATH to the WSL PATH.
To implement this solution, you need to edit the file located in the directory in your WSL instance.wsl.conf/etc/
Add the following lines to the file:wsl.conf

[interop]
appendWindowsPath=false

**Comment by zhenda-hub** [comment]
> The issue arises from the Windows and WSL environment path variables conflicting or the WSL attempting to access unavailable paths. A solution is to prevent WSL from appending the Windows PATH to the WSL PATH. To implement this solution, you need to edit the file located in the directory in your WSL instance.wsl.conf/etc/ Add the following lines to the file:wsl.conf
> 
> [interop] appendWindowsPath=false

A solution is to prevent WSL from appending the Windows PATH to the WSL PATH.
This message helped me. 
There is a non-existent path in my Windows PATH .
