### ISSUE TITLE
Not working from Sublime Text Build system

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/WSL#1046]
### A brief description

Using bash in Sublime Text build system results in error. 

(This could probably be Sublime Text issue ([which I've reported](https://github.com/SublimeTextIssues/Core/issues/1346)) but still posting here.)
### Expected results

Bash should work from Sublime Text build system.
### Actual results (with terminal output if applicable)

Invoking bash from a Sublime plugin using Sublime Build system

```
self.window.run_command("exec", {'cmd': 'bash'})
```

gives this error:

```
E[NULL]r[NULL]r[NULL]o[NULL]r: 0[NULL]x[NULL]8[NULL]0[NULL]0[NULL]7[NULL]0[NULL]0[NULL]5[NULL]7
[Finished in 0.2s with exit code 4294967295]
```

And I know there's probably nothing wrong with bash or its path because this works:

```
import subprocess
subprocess.call('bash')
```
### Your Windows build number

14393
### Steps / commands required to reproduce the error

Inside a Sublime plugin run `self.window.run_command("exec", {'cmd': 'bash'})`

---

(backlinks to related issues: [SublimeTextCore](https://github.com/SublimeTextIssues/Core/issues/1346), [Shell-Turtlestein](https://github.com/misfo/Shell-Turtlestein/issues/75), [GitSavvy](https://github.com/divmain/GitSavvy/issues/493))

**Comment by ashvinnihalani** [comment]
I get this error too, when trying to use bash in Glue

**Comment by tara-raj** [comment]
WSL has changed a lot of interop-related functionality over the past two years. Please re-open if you run into this issue in 1803.

**Comment by therealkenc** [comment]
> E[NULL]r[NULL]r[NULL]o[NULL]r

After two years I actually read that. This is dupe #1228
