### ISSUE TITLE
WSL2 Suddenly Stopped Working

### ISSUE THREAD

**Issue by tohitsugu** [microsoft/WSL#10467]
### Windows Version

Microsoft Windows [Version 10.0.22621.2134]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Kali Linux

### Repro Steps

Kali was running fine. 
Rebooted machine. 
Run `kali ` command from powershell 

Receive following error: 

```
WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/CreateInstance/CreateVm/0x80370102
Press any key to continue...
```

Virtual Machine Platform is enabled 
Virtualization is enabled in BIOS

### Expected Behavior

`kali` command should start Kali Linux using WSL2

### Actual Behavior

`WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/CreateInstance/CreateVm/0x80370102
Press any key to continue...`

### Diagnostic Logs

[WslLogs-2023-09-12_10-45-56.zip](https://github.com/microsoft/WSL/files/12589378/WslLogs-2023-09-12_10-45-56.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @tohitsugu. I wonder if your hypervisor is actually launching. Can you share the output of `bcdedit` in an elevated command prompt ?
