### ISSUE TITLE
I can't use WSL2

### ISSUE THREAD

**Issue by capediemmmm** [microsoft/WSL#10469]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0

### Distro Version

Ubuntu 22.04

### Repro Steps

1. I run
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
`
and 
`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
`
and reboot the computer.

2. `wsl --set-default-version 2`
3. `wsl --install -d Ubuntu`
4. error :
`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...`
5. check task manager and find that the vt bios is enabled
6. So how can I fix it?

### Expected Behavior

I could download Ubuntu using WSL2 successfully

### Actual Behavior

error :
`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...`

**Comment by salmansarwar5102** [comment]
I have the same issue!!
