### ISSUE TITLE
WslRegisterDistribution failed with error: 0x8000000d

### ISSUE THREAD

**Issue by Oosher** [microsoft/WSL#10479]
### Windows build number:

10.0.19045.3324

### Your Distribution version:

20.04

### Your WSL versions:

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3324

### Steps to reproduce:

i type in cmd or powershell as admin  wsl --instal -d Ubuntu 

its installing ubuntu opens ubuntu and gives me this message

PS C:\Windows\system32> wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8000000d
Error: 0x8000000d An illegal state change was requested.

### Expected behavior:

installing ubuntu successfully  

### Actual behavior:

PS C:\Windows\system32> wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8000000d
Error: 0x8000000d An illegal state change was requested.

**Comment by pmartincic** [comment]
Also, do you already have a distrobution called `ubuntu` installed?

See `wsl -l`

**Comment by ZararSW** [comment]
Guys, if anyone is still facing issues. Then the only solution left is.
 Open Registry Editor (regedit).

Navigate to:

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss
Delete the two subkeys (folders) for Ubuntu and Kali:

{d86f25eb-0c90-4104-8f28-b809f5fe31db}

{f834ce26-d8a0-4e63-b262-b07134958c6f}

You should see keys lie this under lxss. Delete all. Then the wsl will run instantly.

**Comment by helofaridx** [comment]
It works perfectly on my Windows 11! Amazing! Thank you!

**Comment by ZararSW** [comment]
Amazing.
