### ISSUE TITLE
Cannot execute bash command in ssh after wsl --update.

### ISSUE THREAD

**Issue by thelastfantasy** [microsoft/WSL#10488]
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu-20.04

### Repro Steps

Since my old wsl (wsl 2, version forgot) usually not response to some command like wsl --shutdown, I updated wsl with `wsl --update`.
But after this update, my vscode from another machine in the LAN cannot connect to this machine any more.
I tested a lot and finally find that ssh connect is all ok, but run `bash` command(vscode Remote Explorer extension run it automaticlly) returns the `??????????` result.
I also tried run bash command from the wsl host machine, and got the same `??????????`  result.

```powershell
PS C:\Users\To Gyokuryu> ssh 192.168.3.4
PowerShell 7.3.6
PS C:\Users\To Gyokuryu> bash
??????????
```

### Expected Behavior

run bash in ssh should connect the shell successfully of wsl.

### Actual Behavior

Got `??????????`  after run bash in ssh.

**Comment by OneBlue** [comment]
Thank you for reporting this @thelastfantasy. Are you actually calling WSL's bash ? What's the output of 'where bash' ? 

Also /logs

**Comment by thelastfantasy** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

I ran this script but got this.
![图片](https://github.com/microsoft/WSL/assets/6077584/8a2e7bed-c988-4527-96d7-67c9615c5511)

**Comment by thelastfantasy** [comment]
> Thank you for reporting this @thelastfantasy. Are you actually calling WSL's bash ? What's the output of 'where bash' ?
> 
> Also /logs

This is result of ran bash with no ssh connection. Shell is Powershell and everything looks OK.
![图片](https://github.com/microsoft/WSL/assets/6077584/0752aca2-52f7-4f19-8cd7-c7ee52bcfea5)

This is result of ran bash after ssh connection. Shell is Powershell setted by:
```powershell
Set-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.6.0_x64__8wekyb3d8bbwe\pwsh.exe"
```

![图片](https://github.com/microsoft/WSL/assets/6077584/b673d483-a4a6-4909-8939-48ef856d485e)

Sorry, but where can I found the logs?
![图片](https://github.com/microsoft/WSL/assets/6077584/43b7d55f-7a23-4925-a3dc-4994d0ba8a16)

**Comment by benhillis** [comment]
Is it possible you were using the inbox version of WSL previously?

With WSL 2.0 you should be able to access wsl.exe and bash.exe from ssh. Could you try updating? `wsl.exe --update --pre-release`

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.1.
