### ISSUE TITLE
WSL suddenly stopped working error code - Error: 0x80090006 Invalid Signature.

### ISSUE THREAD

**Issue by MISSEY** [microsoft/WSL#10486]
[WslLogs-2023-09-19_17-19-04.zip](https://github.com/microsoft/WSL/files/12662843/WslLogs-2023-09-19_17-19-04.zip)
### Windows Version

Microsoft Windows [Version 10.0.25201.1000]

### WSL Version

WSL version: 1.2.5.0 Kernel version: 5.15.90.1 WSLg version: 1.0.51 MSRDC version: 1.2.3770 Direct3D version: 1.608.2-61064218 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.25201.1000

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Initially, wsl stopped working. I tried a few available solutions, didn't help. So, then I try to reinstall the distro, still had same issue: 

```bash
PS C:\Users\smishra> wsl --install -d Ubuntu-22.04
Ubuntu 22.04 LTS is already installed.
Launching Ubuntu 22.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80090006
Error: 0x80090006 Invalid Signature.

```

Previously installed wsl distro Ubuntu-22.04 also had the 

```bash
Invalid Signature. Error code: Wsl/Service/CreateInstance/CreateVm/0x80090006
```

### Expected Behavior

![image](https://github.com/microsoft/WSL/assets/11891755/55884174-cb3e-4fe4-823e-f4b8c037dda1)

### Actual Behavior

WSL should start the distro

**Comment by MISSEY** [comment]
![image](https://github.com/microsoft/WSL/assets/11891755/b3c7edcd-0abf-466f-a55a-83616ad77035)

**Comment by webme818** [comment]
### Windows Version
Microsoft Windows [Version 10.0.25227.1010]

### WSL Version
2.0.0.0

### Are you using WSL 1 or WSL 2?
- [x]  WSL 2
- [ ]  WSL 1

### Kernel Version
5.15.123.1-1

Hi, I am in almost the same situation.
I ran the logging, could you please check?

[WslLogs-2023-09-19_11-01-56.zip](https://github.com/microsoft/WSL/files/12655003/WslLogs-2023-09-19_11-01-56.zip)

**Comment by webme818** [comment]
### Windows Version
Microsoft Windows [Version 10.0.25951.1010]

I was fixed by Windows Update.

**Comment by MISSEY** [comment]
@OneBlue Here is the logs 
[WslLogs-2023-09-19_17-19-04.zip](https://github.com/microsoft/WSL/files/12662848/WslLogs-2023-09-19_17-19-04.zip)

**Comment by MISSEY** [comment]
@webme818 , I am not able to update, update window shows that, it is upto date.

**Comment by pmartincic** [comment]
Did you let /log collection run while running the `install` commands you were having problems with? I don't see anything in the logs.

**Comment by MISSEY** [comment]
Hi @pmartincic, this time I ran the script `collect-wsl-logs.ps1` in parallel with wsl install commands. 

[WslLogs-2023-09-20_10-26-57.zip](https://github.com/microsoft/WSL/files/12670801/WslLogs-2023-09-20_10-26-57.zip)
[WslLogs-2023-09-20_10-30-16.zip](https://github.com/microsoft/WSL/files/12670804/WslLogs-2023-09-20_10-30-16.zip)

Thank you

**Comment by OneBlue** [comment]
Thank you @MISSEY. Looking at the logs I can see that the issue is that the hyper-V firmware signature has expired on your machine. Can you try to update to a more recent build and see if that solves the issue ?

**Comment by MISSEY** [comment]
@OneBlue, My windows version is Microsoft Windows [Version 10.0.25951.1010], and there is no more updates. On windows insder programme page I am seeing this error, 

![image](https://github.com/microsoft/WSL/assets/11891755/e932c8b9-bc40-45ae-8fab-2913c2d4d97e)

**Comment by MISSEY** [comment]
So, Unfortunately, I had to install new windows 11 to solve the issue

**Comment by mquangdev** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

Hello, i have the sample problem and this is my logs file
[WslLogs-2024-10-09_15-08-11.zip](https://github.com/user-attachments/files/17305120/WslLogs-2024-10-09_15-08-11.zip)
Can you help me ?

**Comment by mahmoudgx** [comment]
Hi, I'm experiencing the same issue, and here is my log file. Could you assist me?

[WslLogs-2024-12-19_14-57-58.zip](https://github.com/user-attachments/files/18196718/WslLogs-2024-12-19_14-57-58.zip)
