### ISSUE TITLE
Cannot use experimental network features

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/WSL#10492]
### Windows Version

Microsoft Windows [Version 10.0.23545.1000]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Arch

### Repro Steps

Write a `~/.wslconfig` like
```
[experimental]
sparseVhd=true
autoMemoryReclaim=gradual
networkingMode=mirrored
dnsTunneling=true
firewall=true
```

### Expected Behavior

According to the release note, it should work well.

### Actual Behavior

(the error message is translated)

```
wsl: Hyper-V firewall is not supported
wsl: mirrored networking mode is not supported, fallback to NAT
wsl: DNS tunneling is not supported
```

**Comment by BurgerTown** [comment]
Windows加入Insider

**Comment by Berrysoft** [comment]
> Windows加入Insider

Microsoft Windows [Version 10.0.23545.1000]

It's dev channel.

**Comment by BurgerTown** [comment]
> > Windows加入Insider
> 
> Microsoft Windows [Version 10.0.23545.1000]
> 
> It's dev channel.

Oh, you are using a Windows 10. Maybe those feature support Windows 11 Insider only.

**Comment by BurgerTown** [comment]
> > Windows加入Insider
> 
> Microsoft Windows [Version 10.0.23545.1000]
> 
> It's dev channel.

[here](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/#new-networking-mode-mirrored)

**Comment by Berrysoft** [comment]
![图片](https://github.com/microsoft/WSL/assets/37586447/092a8725-0909-4164-88cf-1373a74939a4)

I wonder how do you understand the version of kernel, and product name:)

**Comment by Berrysoft** [comment]
I've noticed that there's a patch I could not install - Update Stack Package - (Version 1201.2307.4011.0)

It always fail to install. Is it the reason?

**Comment by nick-beer** [comment]
I'm also seeing this.  I've tried on two different computers, and on both I get:
```
wsl: Hyper-V firewall is not supported
wsl: Mirrored networking mode is not supported, falling back to NAT networking
```

I'm on Windows 11, "Release Preview" ring of the insider's program, OS Build 22621.2282.  I get the following with `wsl --version`.
```
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22621.2283
```

Here's the contents of my `.wslconfig`:

```
[experimental]
networkingMode=mirrored
```

**Comment by craigloewen-msft** [comment]
Hi folks if you're seeing this it's because you're not on the latest version.

If you're on the release preview ring, you need this build or higher (Note the minor number): [Version 10.0.22621.2359

@Berrysoft are you able to move to the canary channel? That should fix you right away. I will check version numbers with the Dev channel.

**Comment by Berrysoft** [comment]
So...why dev channel could not use the feature? The release note doesn't say that.

**Comment by rjy7wb** [comment]
The Release notes : https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/

say the release channel has the networking changes, specifically

```
Please note this feature is currently only available to Windows Insiders (across all Insider Channels) including the **_Release Preview Channel_** with the latest Windows 11, version 22H2 update [here](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/). You can get access now by [joining the Windows Insider Program](https://support.microsoft.com/en-us/windows/join-the-windows-insider-program-and-manage-insider-settings-ef20bb3d-40f4-20cc-ba3c-a72c844b563c) and choosing to opt in your device into the _**Release Preview Channel*_*.
```

_**Release Preview Channel**_

**Comment by Berrysoft** [comment]
It also says "across all insider channels", so I thought dev channel should be OK.
