### ISSUE TITLE
Docker CE no longer works with WSL 2.0.0 and `autoMemoryReclaim=gradual`

### ISSUE THREAD

**Issue by felipecrs** [microsoft/WSL#10497]
### Windows Version

Microsoft Windows [Version 10.0.22631.2338]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 24.0.6, installed following https://docs.docker.com/engine/install/ubuntu/.

### Repro Steps

1. Be on WSL older than 2.0.0.0
1. Enable systemd through `wsl.conf`
2. Install docker following https://docs.docker.com/engine/install/ubuntu/
1. Confirm it works by running `docker version`
3. Update WSL to 2.0.0.0
4. Add `autoMemoryReclaim=gradual` to `.wslconfig`'s `[experimental]`
5. `docker version` times out

### Expected Behavior

Docker to work just like before.

### Actual Behavior

Docker daemon does not start.

### Diagnostic Logs

Docker daemon logs:

```
Sep 19 09:46:20 FELIPE-MSI systemd[1]: Starting Docker Application Container Engine...
Sep 19 09:46:20 FELIPE-MSI dockerd[887]: time="2023-09-19T09:46:20.482638672-03:00" level=info msg="Starting up"
Sep 19 09:46:20 FELIPE-MSI dockerd[887]: failed to start daemon: Devices cgroup isn't mounted
Sep 19 09:46:20 FELIPE-MSI dockerd[887]: time="2023-09-19T09:46:20.500829506-03:00" level=info msg="stopping event stream following graceful shu>
Sep 19 09:46:20 FELIPE-MSI systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 19 09:46:20 FELIPE-MSI systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 19 09:46:20 FELIPE-MSI systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by craigloewen-msft** [comment]
Yes this is a known issue! We are working with the Docker team to get a fix for this.

**Comment by felipecrs** [comment]
> Yes this is a known issue! We are working with the Docker team to get a fix for this.

Thanks for the heads up!

BTW sorry, I made a mistake in the reproduction steps (I said keep the `.wslconfig` empty while in fact you need `autoMemoryReclaim` to trigger the issue).

**Comment by benhillis** [comment]
I believe I have a fix for this issue, we should be pushing a 2.0.1 here in the next couple of days.

**Comment by zcobol** [comment]
@felipecrs when you enable the `[experimental]` features it disables `cgroupv1` nuking `docker` service which depends on it. See `/proc/cmdline` and you'll find `cgroup_no_v1=all` there!

**Comment by felipecrs** [comment]
Makes sense, but I did some things like:

```console
$ cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF
```

To make docker use cgroups v2, and it didn't work out well. Maybe I did something wrong though.

**Comment by felipecrs** [comment]
Please note that I'm not using Docker Desktop.

**Comment by driver1998** [comment]
Saw on https://github.com/microsoft/WSL/issues/10499, just tested, `autoMemoryReclaim=dropcache` works with docker as well.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.1.

**Comment by felipecrs** [comment]
I can confirm it was fixed indeed. Thank you!

**Comment by corebonts** [comment]
Note that although you may think that you've updated WSL with `wsl --update --pre-release`, for some the update silently fails: #10539
In this case you should install it manually by downloading the MSI.

**Comment by felipecrs** [comment]
I had noticed the failure as well, and that's why I update through the Microsoft Store. I will double check the version though.

**Comment by felipecrs** [comment]
Yes, confirmed:

```console
❯ wsl --version
WSL version: 2.0.1.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2338
```

**Comment by carlosrmendes** [comment]
wsl version 2.0.7.0 and .wslconfig with:
```
[experimental]
autoMemoryReclaim = "gradual"
```
Docker Desktop cannot start, it hangs forever

**Comment by dfenerski** [comment]
> wsl version 2.0.7.0 and .wslconfig with:
> 
> ```
> [experimental]
> autoMemoryReclaim = "gradual"
> ```
> 
> Docker Desktop cannot start, it hangs forever

I have the same issue with both `autoMemoryReclaim=dropcache` and `autoMemoryReclaim=gradual` with following versions:

```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693
```
