### ISSUE TITLE
Extremely Slow Performance

### ISSUE THREAD

**Issue by 4i8** [microsoft/WSL#10509]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

NAME="Debian GNU/Linux" VERSION_ID="12"

### Repro Steps

```ssh
time brew
```

https://github.com/microsoft/WSL/assets/76555623/7f4edcf0-6e63-4e3f-aaf4-6f9b527c7060

### Expected Behavior

I expect the command to execute within a reasonable amount of time, similar to previous experiences with WSL where commands executed swiftly.

### Actual Behavior

The command execution is extremely slow. For instance, running "time brew" takes significantly longer than expected, with delays of several minutes for simple operations. This slow performance negatively impacts my ability to use WSL effectively for development and tasks that involve frequent interactions with the Linux environment.

**Comment by OneBlue** [comment]
Thank you for reporting this @4i8. I wonder if this issue is caused by your prompt.

Can you try to open a shell and run: `PS1='> '` and see if that solves the issue for the following commands ?

**Comment by 4i8** [comment]
> Thank you for reporting this @4i8. I wonder if this issue is caused by your prompt.
> 
> Can you try to open a shell and run: `PS1='> '` and see if that solves the issue for the following commands ?
After this poor performance, I proceeded to uninstall everything related to WSL. The performance was extremely unexpected; you must work on improving it
