### ISSUE TITLE
LxssManager keeps shutting down and getting stuck in STOP_PENDING state

### ISSUE THREAD

**Issue by cfitz** [microsoft/WSL#10505]
### Windows Version

Microsoft Windows [Version 10.0.19045.3324]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

1.2.5.0

### Distro Version

Ubuntu 22.04

### Other Software

We have a windows service setup using winsw, which works on other machines. It runs as a service under it's own AD bound user account. 
However, this is a worker I setup this week, so it has a newer version of WSL running. 

### Repro Steps

1) Boot windows
2) Run service that executes WSL commands 
3) Everything works
4) Some time passes...
5) WSL commands are not longer responding
6) sc.exe queryex LxssManager shows WSL STOP_PENDING, task manager shows svchost as "stopping". 
7) Kill that svchost
8) WSL works again, for awhile...repeat steps 4-7

### Expected Behavior

WSL should keep running and respond to commands. 

### Actual Behavior

LxssManager is dying and getting stuck in some stopping state

### Diagnostic Logs

[WslLogs-2023-09-19_20-13-43.zip](https://github.com/microsoft/WSL/files/12665941/WslLogs-2023-09-19_20-13-43.zip)

Seeing:
 <Event EventName="Microsoft.Windows.Lxss.Manager/VerboseLog" TimeMsec="1933747.906" ProcessName="Process(15320) (15320)" ThreadID="12,632" file="onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp" linenumber="873" failurecount="2" threadid="12,632" hr="-2,147,023,584" message="onecore\vm\wsl\lxss\service\lib\lxsssecurity.cpp(228)\lxssmanager.dll!00007FFA4E42DB06: (caller: 00007FFA4E43D75B) Exception(1) tid(3158) 80070520 A specified logon session does not exist. It may already have been terminated. " code="" function="" ActivityID="f8bd0989-1ed3-4658-8700-ad41ebf2c19d" />

and a lot of 
 <Event EventName="Microsoft.Windows.Lxss.Manager/VerboseLog" TimeMsec="2940440.559" ProcessName="Process(15320) (15320)" ThreadID="5,308" file="" linenumber="65,536" failurecount="-939,524,096" threadid="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP ArgumentOutOfRangeException&gt;&gt;&gt;" hr="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP ArgumentOutOfRangeException&gt;&gt;&gt;" message="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP ArgumentOutOfRangeException&gt;&gt;&gt;" code="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP ArgumentOutOfRangeException&gt;&gt;&gt;" function="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP ArgumentOutOfRangeException&gt;&gt;&gt;" ActivityID="f5e05f89-e20f-49ca-a6a3-698037b21f33" />

**Comment by OneBlue** [comment]
Hmm I'm a bit confused because I see a wslservice.exe dump, but no svchost dump. 

Do you ever run commands let's say from session 0 / task manager / psremote / ssh ? I wonder if you're using both inbox and store WSL

**Comment by cfitz** [comment]
Hi,  Sorry about the delay, was out a few days.
Thanks for looking at this. 
This workstation seems to be having other issues as well, so I'm going to have them re-image it and start with an all fresh install. 
Will come back if the issue happens again. Thanks again for the help!
