### ISSUE TITLE
.wslconfig doesn't work: `Unknown key ...`

### ISSUE THREAD

**Issue by yhsb2k** [microsoft/WSL#10510]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

Remove /etc/wsl.conf file.
wsl --shutdown
Create .wslconfig file in C:\Users\<UserName> with the following content:
```ini
[boot]
systemd=true

[interop]
# Restrict launching Windows processes in WSL
enabled=false

# Do not appent Windows PATH to WSL $PATH
appendWindowsPath = false
```
NOTE: there is another issue that .wslconfig file should have LF line endings. Otherwise, with CRLF, it doesn't work in my setup.

Start the WSL and see output in Terminal:
```
wsl: Unknown key 'boot.systemd' in C:\Users\root\.wslconfig:2
wsl: Unknown key 'interop.enabled' in C:\Users\root\.wslconfig:6
wsl: Unknown key 'interop.appendWindowsPath' in C:\Users\root\.wslconfig:9
```

Also, see that, for example, docker inside WSL isn't accessible because systemd doesn't start due to broken .wslconfig.
_Windows or WSL reboot doesn't fix this problem._

### Expected Behavior

WSL configuration successfully loaded from C:\Users\<UserName>\.wslconfig file.

### Actual Behavior

Errors when loading WSL configuration from C:\Users\<UserName>\.wslconfig file.

**Comment by yhsb2k** [comment]
Or did I misunderstand something and the **/etc/wsl.conf** and **C:\Users<UserName>.wslconfig** configuration keys are not compatible?

**Comment by 0xbadfca11** [comment]
.wslconfig is not a globalization of wsl.conf.

**Comment by yhsb2k** [comment]
Understood. So, closing this issue.
