### ISSUE TITLE
Include by default an ssh-agent to prevent type ssh key password every time

### ISSUE THREAD

**Issue by lucamosca1** [microsoft/WSL#10512]
**Is your feature request related to a problem? Please describe.**
Since I need terminal, more or less 100 times a day, It's a bit annoying unlock my ssh key 100 times.

**Describe the solution you'd like**
The way Ubuntu handle this issue is preatty easy, the command ssh-add store my key password for the whole session. A similar stuff already included could be interesting and comfortable. 

**Describe alternatives you've considered**
There are not immediate ways to do this, like this one https://nazmul-ahsan.medium.com/how-to-prevent-ssh-key-passphrase-prompt-every-time-you-launch-wsl-6856eae31add
Prefer to avoid if possible

**Comment by sarim** [comment]
Are you running with systemd enabled? You can install ssh-agent etc... in ubuntu.

**Comment by OneBlue** [comment]
WSL doesn't control what runs in the distro. Adding an ssh-agent would be something that distro maintainers need to implement (or potentially users by starting the daemon with boot.cmd in /etc/wsl.conf)
