### ISSUE TITLE
wsl 2.0.0 proxy bug in networkingMode = mirrored network

### ISSUE THREAD

**Issue by Morrigan-Ship** [microsoft/WSL#10517]
### Windows Version

10.0.25931.1000

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

ubuntu kali

### Repro Steps

nothing

### Expected Behavior

if i enable vpn on windows wsl network will use windows vpn
but if enable proxy on windows you need to restart wsl to use proxy

### Actual Behavior

if i enable vpn on windows wsl network will use windows vpn
but if enable proxy on windows you need to restart wsl to use proxy

**Comment by craigloewen-msft** [comment]
Are you using the new experimental networking features? Can you please share the content of your `.wslconfig` file? 

And is the bug that you're seeing here that you need to restart WSL for the proxy to take effect?

**Comment by keith-horton** [comment]
Hi there.
It's possible with some VPNs that the time for Windows to resolve possible proxy servers takes too long - so we startup the WSL container before we know what proxy configurations exist in Windows. Once Windows resolves the proxy server information, if we have already started the WSL container, we will prompt to restart the WSL container.

Once you restart the WSL container, we should correctly set the proxy.
