### ISSUE TITLE
cd + tab does not change colors, setting via zsh does not work

### ISSUE THREAD

**Issue by dehlong** [microsoft/WSL#10522]
### Windows Version

Microsoft Windows [Version 10.0.19044.3448]

### WSL Version

Invalid command line option: --version

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

No

### Repro Steps

Since my bug report was closed for no good reason, I have to recreate the issue.

Go to a folder which has a subfolders, Run cd+TAB and you will see stupid folder highlighting:
![268524367-5f4056af-7f1b-48a4-a964-25b660e4e9a9](https://github.com/microsoft/WSL/assets/112163027/c800ff8a-6a74-458f-b5a2-41ff8b7e6fd0)

### Expected Behavior

No highlight, just different color like in ls after fix:
![268524507-506c628d-f357-4710-ad98-98884e794d97](https://github.com/microsoft/WSL/assets/112163027/5ff32d86-2a1e-4e69-852d-10064c2d9af9)

### Actual Behavior

Highlighting that makes folders' names impossible to read:
![268524367-5f4056af-7f1b-48a4-a964-25b660e4e9a9](https://github.com/microsoft/WSL/assets/112163027/7e6a4b64-8be1-44db-88e2-058724df68da)

I have added these lines at the end of the .zshrc:
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit

In normal linux distributions, this works and sets cd + TAB autocompletion to pre-set colors,. Here is the proof: https://github.com/ohmyzsh/ohmyzsh/issues/1563#issuecomment-26591369

However, this "fix" does not work in ubuntu WSL, so there is definitely something not correct going on.

PS: Please, do not close unsolved issues. I doubt this is by design.

**Comment by OneBlue** [comment]
WSL does not control the terminal nor the shell. 
In your case you need to investigate why your prompt is coloring folders and change your settings.

Based on your screenshots it looks like you're using zsh with oh-my-zsh. I'd recommend looking at [themes](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes) and the rest of the oh-my-zsh documentation.

Closing since this is not a WSL issue.
