### ISSUE TITLE
How can I downgrade from WSL2 2.0 to the latest 1.x ?

### ISSUE THREAD

**Issue by speller** [microsoft/WSL#10528]
### Windows Version

10.0.22621.2359

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

The new WSL2 version 2.0.0.0 is not suitable for me. I want to revert back to v 1.x (**NOT** WSL1). How can I do that?

**Comment by OneBlue** [comment]
You can download older builds [here](https://github.com/microsoft/WSL/releases).

Before downgrading to 1.X from 2.X build, you need to completely remove WSL from your machine via the control panel (there might be 2 entries there, you need to remove both before installing the older build)

**Comment by speller** [comment]
@OneBlue does it mean that I will lose all my data in the distro?

**Comment by OneBlue** [comment]
No, distros are separate from the WSL package.
