### ISSUE TITLE
Enable CONFIG_HIDRAW=y in WSL kernel

### ISSUE THREAD

**Issue by oliviacrain** [microsoft/WSL#10526]
**Is your feature request related to a problem? Please describe.**
General problem: I can't use FIDO2 discoverable credentials from my YubiKey in WSL2.
My particular scenario: I would like to be able to use the SSH key stored in my YubiKey in my Ubuntu 22.04 WSL2 environment for SSH authentication/Git commit signing.

**Describe the solution you'd like**
Enable `CONFIG_HIDRAW=y` in the WSL2 kernel config.

I can successfully pass the security key to WSL using `usbipd-win`, and I can perform actions with the key that don't use FIDO-based features. For such features, `libfido2` is used (by way of OpenSSH, in my particular case) to interface with the security key. On Ubuntu/Fedora, that library is configured to communicate with the security key using the `/dev/hidraw*` interface exposed by the kernel. In WSL2, that interface is not available because `CONFIG_HIDRAW` is not set.

**Describe alternatives you've considered**
I could maintain my own kernel. I could continue to use an on-disk SSH key for my WSL2 distros. The first alternative is a maintenance burden, the second requires me to keep track of more keys than I care to keep track of.

**Additional context**
This request was made in #7686, but I'm opening this as a more narrowly scoped request.

**Comment by kelsey-steele** [comment]
CONFIG_HIDRAW and CONFIG_USB_HIDDEV are now enabled in the latest WSL2 kernel release [linux-msft-wsl-5.15.150.1](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.150.1)

Please keep in mind the kernel is released to the WSL2-linux-kernel repo first and will be included in an upcoming WSL release.
