### ISSUE TITLE
Reads in GB for minutes after deleting .wslconfig

### ISSUE THREAD

**Issue by anirugu** [microsoft/WSL#10533]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

No distro

### Other Software

Docker desktop with no distro.

### Repro Steps

 I install the latest pre-released 2.0 from this repo. After installing it I first set the 4gb limit than 1gb than 2gb with 4 core in .wslconfig in %userprofile% folder.

I deleted .wslconfig in %userprofile% and 
I restart my machine and docker doesn't start in seconds, which usually happen.  I see a lot of R/W happen (in GBs) from vmmem kind of exe which I usually seen running docker.

What exactly wsl do when it doesn't find the .wslconfig. in my case I see a lot of R/W.

### Expected Behavior

it should not do too much R/W. look like a bug.

### Actual Behavior

it should not do too much R/W. look like a bug.

### Diagnostic Logs

NA

**Comment by benhillis** [comment]
What setting are you changing? It's not clear from your description.
