### ISSUE TITLE
CAnnot access to WSL2 in windows 11

### ISSUE THREAD

**Issue by acidphuck** [microsoft/WSL#10542]
![image](https://github.com/microsoft/WSL/assets/40587818/82ac457b-bdfb-4adc-b4d0-f10ea1e15eb8)

This is the error that occurred whenever i try to access WSL.
Please i need help. I am a newbie

**Comment by pavelpikta** [comment]
Hi @acidphuck 
You have issue with .wslconfig file. Pls check config file `C:\Users\sailfulnizam\.wslconfig`
