### ISSUE TITLE
Starting terminal sometimes results in $SHLVL as high as 41?!

### ISSUE THREAD

**Issue by eggbean** [microsoft/WSL#10548]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Pengwin 23.07.1 (Debian 12)

### Other Software

tmux 3.3a

### Repro Steps

I start a Windows Terminal tab for Pengwin (not for the first time since booting Windows).

Start tmux. I use [starship](https://github.com/starship/starship), with a minimal config. I recently added `$SHLVL` suppport, so I get an indiction of what it is when above 4.

I often find it is at something like 9. I just now got it at 41!

### Expected Behavior

After starting a new terminal session and then starting tmux, it should be 2.

### Actual Behavior

It's often much higher than two and as high as 42.

This is with no previous tmux sesssion existing before making a new one.

I have to `wsl.exe --shutdown` to make it start acting like normal.

**Comment by OneBlue** [comment]
Thanks for reporting this @eggbean. Are you using systemd ?

**Comment by eggbean** [comment]
Yes, I'm using `systemd`.

**Comment by OneBlue** [comment]
Do you see if a difference if you start the distro without systemd enabled ?

**Comment by eggbean** [comment]
I'll disable `systemd` and see. Will probably be a day or two before I can tell for sure.

**Comment by zcobol** [comment]
@eggbean notice that `SHLVL` is a `bash` variable and not `tmux` or `starship`. It is supposed to tell you how deeply your bash shells are nested. Here's a sample tmux session, with starship level set to 4:

![shlvl_tmux_test](https://github.com/microsoft/WSL/assets/104515072/a9a96eb8-4e92-4352-935e-418c8a7c350e)

Just opening new tmux panes won't do it. You can try the same w/out tmux.
