### ISSUE TITLE
Install WSL to other disk

### ISSUE THREAD

**Issue by gty111** [microsoft/WSL#10553]
**Is your feature request related to a problem? Please describe.**
WSL occupy too much resources on C disk. So I need to manually migrate WSL to another disk.

**Describe the solution you'd like**
WSL can be installed to other disks(at the time of installation), not just the C disk(at default).

**Describe alternatives you've considered**
Export the WSL to the file, and import that file to WSL which is on other disk.

**Additional context**
The resource of C disk is precisous. So please offer a option to install WSL to other disk(at default).

**Comment by AzureZeng** [comment]
A workaround: export the distro you want to move, then unregister the original distro. After that, register the distro in the path you desired to store the distro vhdx file, using your export file

**Comment by OneBlue** [comment]
Indeed you can change the location of where distributions are installed by using `wsl --import <name> <location> <source>` or `wsl --import-in-place <name> <source>`.

**Comment by gty111** [comment]
Maybe my description is not clear.

> A workaround: export the distro you want to move, then unregister the original distro. After that, register the distro in the path you desired to store the distro vhdx file, using your exported file
Indeed you can change the location of where distributions are installed by using `wsl --import <name> <location> <source> or wsl --import-in-place <name> <source>`.

That's what I'm doing right now. But I think it's not very convenient.  

My proposal is that providing a option to install WSL to other disk when using command `wsl  --install [Distro] [Options...]` instead of installing WSL to C disk and doing stuff like exporting and importing. 

Image a situation that a user who doesn't know that WSL will be installed into C disk. He will use it for a long time until finding that C disk is almost full. Then he find that he needs to export WSL to a file and import it to move WSL to other disk. But the size of WSL maybe very big. So the elapsed time for exporting and importing is annoying. That's the pain spot when using WSL actually.
