### ISSUE TITLE
Please explain difference between store, distribution, and wsl --update wsl versions

### ISSUE THREAD

**Issue by rfay** [microsoft/WSL#10551]
**Is your feature request related to a problem? Please describe.**

I have been baffled for some time by the various recipes for installing or maintaining WSL2. Some people/recipes say that you have to install from the store. Others say you have to download it. Often `wsl --update` and `wsl --install` are fine. A recent issue said that wsl.exe might be in 3 different places on the Windows side.

Is any of this true? Surely there can be one wsl.exe distributed in different ways. 

In writing the [DDEV docs for WSL2 install](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows) I tell people to install with `wsl --install` and *then* go install it from the store. Is that really reasonable? 

**Describe the solution you'd like**

1. One wsl.exe using multiple distribution techniques but with the same behavior would be the best outcome.
2. Otherwise... please sort out this confusion in this issue or in docs somewhere? Thanks!

**Describe alternatives you've considered**
Live on in confusion.

**Comment by blakeduffey** [comment]
> In writing the [DDEV docs for WSL2 install](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows) I tell people to install with `wsl --install` and _then_ go install it from the store. Is that really reasonable?

It is not :)

**Comment by OneBlue** [comment]
@rfay: The recommended method is always to use wsl.exe --install. 

If the Windows version supports store WSL, then wsl --install will install Store WSL. If not, it will install inbox WSL. 
wsl --install will also install ubuntu and all required optional components to run WSL.

**Comment by rfay** [comment]
Thank you @OneBlue - Why were three different WSL.exe installations mentioned in the recent issues?

**Comment by OneBlue** [comment]
> Thank you @OneBlue - Why were three different WSL.exe installations mentioned in the recent issues?

`C:\windows\system32\wsl.exe` is the inbox entry point. It will always call the correct WSL version based on what's installed (inbox vs store)

`C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\wsl.exe` is the Store entry point for WSL < 2.0.0. It's still used for backwards compatibility but should not be called directly 

`C:\Program Files\WSL\wsl.exe` is the WSL entry point for WSL >= 2.0.0. It can be called directly, but it's often better to call the inbox entry point instead

**Comment by rfay** [comment]
Thank you! I hope there  will be more consistency in the future. 

I should be able to completely remove references to the MS Store version in [DDEV Docs](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows) right? Just tell them to `wsl --install`, not need for then installing from store? Currently it says to `wsl --install`, then...

> Visit the Microsoft Store and install the updated [“Windows Subsystem for Linux”](https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R) and click “Open”. It will likely prompt you for a username and password for the Ubuntu WSL2 instance it creates.

That's completely obsolete right?

**Comment by OneBlue** [comment]
> That's completely obsolete right?

Not really, installing via the store is still supported. Under the hood this will install the latest WSL release and we'll continue to support that.
