### ISSUE TITLE
WslRegisterDistribution failed with error: 0xc03a0014 during Ubuntu installation

### ISSUE THREAD

**Issue by badeadrian** [microsoft/WSL#10555]
### Windows Version

Microsoft Windows [Version 10.0.22621.2361]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.90.1

### Distro Version

Ubuntu

### Other Software

Windows Version: (e.g., Windows 10 Pro, Build 19043)
Hyper-V Status: Enabled
Disk Space: Sufficient
Virtualization: Enabled in BIOS
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2361

### Repro Steps

Open PowerShell as an administrator.
Run the command wsl --install -d Ubuntu.
Wait for the installation process to begin.

### Expected Behavior

I expected Ubuntu to install successfully and be usable within WSL 2. The terminal should show a message indicating that the installation was successful, and I should be able to launch Ubuntu from the Start menu or by running wsl -d Ubuntu.

### Actual Behavior

The installation process starts but fails with the following error:
WslRegisterDistribution failed with error: 0xc03a0014
Error: 0xc03a0014 A virtual disk support provider for the specified file was not found.

### Diagnostic Logs

[WslLogs-2023-09-27_23-14-32.zip](https://github.com/microsoft/WSL/files/12742976/WslLogs-2023-09-27_23-14-32.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @badeadrian. I've added new log providers to our logging script.

Can you collect logs of a repro again so I can have a deeper look ? 

/logs

**Comment by JOY** [comment]
I have the same issue today.
`PS C:\Windows\System32> wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xc03a0014
Error: 0xc03a0014 A virtual disk support provider for the specified file was not found.`

**Comment by OneBlue** [comment]
@JOY: Please collect logs and share them if you can reproduce the issue /logs

**Comment by Martyr28** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

I have been experiencing the same issue, provided is the WslLogs. Wasn't exactly sure how I was meant to achieve reproducing it to get the logs so i assumed I ran the provided command to collect logs then in another terminal reproduced the issue with "wsl --install" (which from my understanding is the exact same as wsl --install -d ubuntu).
[WslLogs-2024-01-24_14-29-19.zip](https://github.com/microsoft/WSL/files/14033999/WslLogs-2024-01-24_14-29-19.zip)

**Comment by neokofg** [comment]
1. Open the "Device Manager."
2. Look for "System devices."
3. Locate and enable the following devices related to virtualization:

    Microsoft Hyper-V Virtualization Infrastructure Driver
    Composite Bus Enumerator
    Microsoft Virtual Disk Enumerator
    UMBus Root Bus Enumerator
    Microsoft Virtual Network Adapter Enumerator NDIS
    Device Redirector Bus Enumerator (if applicable)

Please note that the actual names might slightly vary depending on the language localization of your Windows system (This names was translated from russian). Ensure you enable the corresponding devices related to virtualization.

**Comment by pxcnsmith** [comment]
I started having this issue today (4/15/2024) when trying to export and import Ubuntu 22.04 distributions.  

Configuration:
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4170


Seems I can now no longer install any online distribution.  In looking at all of the related items / issues I see that Microsoft Virtual Disk Enumerator is displayed in my system as disabled and when I try to enable it indicates another service is disabling this one.  Feels like this is related to no longer being able to create a distribution under WSL2. 

I have un-register Ubuntu and un-installed Ubuntu 22.04 and other versions that I have since tried to install.  Also tried 'remove data' and 'repair' options for WSL in add / remove programs before re-starting WSL2 in administrative powershell.  Not sure what the next troubleshooting step is.

Log file attached

[WslLogs-2024-04-15_11-58-35.zip](https://github.com/microsoft/WSL/files/14982458/WslLogs-2024-04-15_11-58-35.zip)

**Comment by pixelpilotUm** [comment]
I wanted to install Docker, but the prompt said that I need to install Ubuntu first to install Docker on Windows. However, I encountered this error while installing Ubuntu. Thank you for helping me solve this error.

**Comment by pixelpilotUm** [comment]
> I wanted to install Docker, but the prompt said that I need to install Ubuntu first to install Docker on Windows. However, I encountered this error while installing Ubuntu. Thank you for helping me solve this error.我想安装 Docker，但提示说我需要先安装 Ubuntu 才能在 Windows 上安装 Docker。然而，在安装 Ubuntu 时我遇到了这个错误。谢谢你帮我解决这个错误。

**Comment by charvlex** [comment]
Any solutions?

**Comment by JacksonSmithey** [comment]
Issue resolved (1/30/2025) Instead of installing with WSL 2, use WSL 1 with command:
wsl --set-default-version 1
then install Ubuntu

**Comment by esobreira** [comment]
> 1. Open the "Device Manager."
> 2. Look for "System devices."
> 3. Locate and enable the following devices related to virtualization:
>    Microsoft Hyper-V Virtualization Infrastructure Driver
>    Composite Bus Enumerator
>    Microsoft Virtual Disk Enumerator
>    UMBus Root Bus Enumerator
>    Microsoft Virtual Network Adapter Enumerator NDIS
>    Device Redirector Bus Enumerator (if applicable)
> 
> Please note that the actual names might slightly vary depending on the language localization of your Windows system (This names was translated from russian). Ensure you enable the corresponding devices related to virtualization.

Worked for me like a charm! thanks!

**Comment by Sabbir** [comment]
> Issue resolved (1/30/2025) Instead of installing with WSL 2, use WSL 1 with command: wsl --set-default-version 1 then install Ubuntu

This solution works for me. Thank you.

**Comment by xxx200323-hub** [comment]
> Issue resolved (1/30/2025) Instead of installing with WSL 2, use WSL 1 with command: wsl --set-default-version 1 then install Ubuntu

Thank you!!!!
