### ISSUE TITLE
I have weird terminal in my right click menu and I don't know how to remove it!

### ISSUE THREAD

**Issue by AhmedAladdin96** [microsoft/WSL#10578]
![1](https://github.com/microsoft/WSL/assets/143898580/3bc827ec-9741-451b-b2cb-1221aba8004e)
![1](https://github.com/microsoft/WSL/assets/143898580/93c4e462-239c-4014-a24f-ce81c19ef615)

**Comment by benhillis** [comment]
Unfortunately, that's not us. But if you search around for this registry path you should be able to find some information on how to clean those up: `HKEY_CLASSES_ROOT\Directory\shell`

Be careful modifying your registry though, good luck.
