### ISSUE TITLE
wsl version number not updated.

### ISSUE THREAD

**Issue by dwhobrey** [microsoft/WSL#10574]
### Windows Version

23H2 25951.1010

### WSL Version

2.0.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

None

### Other Software

None

### Repro Steps

wsl --update --pre-release
Which then says it's downloading version 2.0.3.
That completes download with no errors or other messages.

### Expected Behavior

wsl --version
Should now show: WSL version: 2.0.3

### Actual Behavior

Still shows WSL version: 2.0.1.0

**Comment by tinlittle** [comment]
It shows the old version number because upgrade failed. This is a known issue on 2.0.0 and 2.0.1. The solution is to download 2.0.3 MSI and apply it directly.

**Comment by DoctorWho8** [comment]
Last I heard the version that this duplicate is discussing is available from GitHub, not the MS Store.

**Comment by dwhobrey** [comment]
Do you know where on GitHub? Couldn't find it.

**Comment by DoctorWho8** [comment]
@dwhobrey  did you see the announcement regarding WSL 2.0.3? It had a location on it.

**Comment by dwhobrey** [comment]
Thanks DrWho,
Yup, found the link now: https://github.com/microsoft/WSL/releases/download/2.0.3/wsl.2.0.3.0.x64.msi
Not sure how I missed it when searching!
