### ISSUE TITLE
Errors on startup after upgrading to WSL2 2.0.0+

### ISSUE THREAD

**Issue by kczx3** [microsoft/WSL#10585]
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu 18.04

### Repro Steps

Setup your .wslconfig file to have the below.  I also have several corporate network drives mapped which may be related.
```ini
[experimental]
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
```

Upon login to my machine, I get a notification that WSL encountered errors on startup.  Clicking the button provided in the notification opens Event Viewer to `Applications and Service Logs > Microsoft > Windows > SMBClient > Connectivity`.  I do not see any errors around the time of login but there are several Information and Warning messages stating TCP/IP bindings and TDI transport interfaces were deleted and/or added.  The Warnings are all notifying that the client lost its connection to the server and they are all mapped network drives from what I can see.

### Expected Behavior

Startup without errors.

### Actual Behavior

Upon login to my machine, I get a notification that WSL encountered errors on startup.  Clicking the button provided in the notification opens Event Viewer to `Applications and Service Logs > Microsoft > Windows > SMBClient > Connectivity`.  I do not see any errors around the time of login but there are several Information and Warning messages stating TCP/IP bindings and TDI transport interfaces were deleted and/or added.  The Warnings are all notifying that the client lost its connection to the server and they are all mapped network drives from what I can see.

As far as I can tell, WSL is working fine for what I use it for.  I don't typically access these network drives from WSL.

I'm not sure what else to provide to assist but I wanted to at least report it.  Please let me know how else I can provide assistance.

**Comment by craigloewen-msft** [comment]
@kczx3 you're seeing this since your Windows version does not have support for the networking modes you've requested. To get support please join the Windows Insiders program and select the "RElease Preview" or "Canary" Channel. Thanks!

**Comment by kczx3** [comment]
Oh... I was going to try and get the logs but I'm pretty sure that I'd have to get the powershell script allowed through our security controls.

I must have missed the minimum Windows version requirement for the new network mode.  Can you link to that requirement?  Everything seems to be working much better in WSL2 than it did before I upgraded it.  Before I couldn't use it at all really due to connectivity with my corporate network/VPN.

I definitely won't be able to join the Insiders program either due to this being a work machine.  Can you pinpoint which setting I have configured that I should revert to see if things till function while not showing the error?

**Comment by kczx3** [comment]
Here are the logs just in case
[WslLogs-2023-10-04_11-50-46.zip](https://github.com/microsoft/WSL/files/12805477/WslLogs-2023-10-04_11-50-46.zip)

**Comment by benhillis** [comment]
@kczx3 - you should remove the experimental settings you added to `%userprofile%\.wslconfig`
