### ISSUE TITLE
Permissions Error Compiling

### ISSUE THREAD

**Issue by bite-your-idols** [Microsoft/WSL#1059]
When I try to use bash on ubuntu on windows to compile some github projects for my Raspberry Pi I have some errors and the process can not be done.

`make[1]: Leaving directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
make: the '-j' option requires a positive integer argument
make[1]: Entering directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
make DESTDIR= LEAPSECONDS='' PACKRATDATA='' TZDIR=./.install_pkg/etc/zoneinfo YEARISTYPE=./yearistype ZIC='./zic ' LEAPSECONDS= install_data
make[2]: Entering directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
./zic  -y ./yearistype -d ./.install_pkg/etc/zoneinfo  africa antarctica asia australasia europe northamerica southamerica pacificnew etcetera backward systemv factory
awk '/^Rule/' africa antarctica asia australasia europe northamerica southamerica pacificnew etcetera backward systemv factory | ./zic  -y ./yearistype -d ./.install_pkg/etc/zoneinfo  -
make[2]: Leaving directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
rm -fr ./.install_pkg/etc/zoneinfo-posix
ln -s zoneinfo ./.install_pkg/etc/zoneinfo-posix || \
          make DESTDIR= LEAPSECONDS='' PACKRATDATA='' TZDIR=./.install_pkg/etc/zoneinfo YEARISTYPE=./yearistype ZIC='./zic ' TZDIR=./.install_pkg/etc/zoneinfo-posix posix_only
make DESTDIR= LEAPSECONDS='' PACKRATDATA='' TZDIR=./.install_pkg/etc/zoneinfo YEARISTYPE=./yearistype ZIC='./zic ' TZDIR=./.install_pkg/etc/zoneinfo-leaps right_only
make[2]: Entering directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
make DESTDIR= LEAPSECONDS='' PACKRATDATA='' TZDIR=./.install_pkg/etc/zoneinfo-leaps YEARISTYPE=./yearistype ZIC='./zic ' LEAPSECONDS='-L leapseconds' \
                install_data
make[3]: Entering directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
./zic  -y ./yearistype -d ./.install_pkg/etc/zoneinfo-leaps -L leapseconds africa antarctica asia australasia europe northamerica southamerica pacificnew etcetera backward systemv factory
awk '/^Rule/' africa antarctica asia australasia europe northamerica southamerica pacificnew etcetera backward systemv factory | ./zic  -y ./yearistype -d ./.install_pkg/etc/zoneinfo-leaps -L leapseconds -
make[3]: Leaving directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
make[2]: Leaving directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
mkdir -p ./.install_pkg/etc ./.install_pkg/etc/zoneinfo \
                ./.install_pkg/lib \
                ./.install_pkg/man/man3 ./.install_pkg/man/man5 \
                ./.install_pkg/man/man8
./zic  -y ./yearistype -d ./.install_pkg/etc/zoneinfo  -l GMT -p America/New_York
cp -f iso3166.tab zone1970.tab zone.tab ./.install_pkg/etc/zoneinfo/.
cp tzselect zic zdump ./.install_pkg/etc/.
cp libtz.a ./.install_pkg/lib/.
: ./.install_pkg/lib/libtz.a
cp -f newctime.3 newtzset.3 ./.install_pkg/man/man3/.
cp -f tzfile.5 ./.install_pkg/man/man5/.
cp -f tzselect.8 zdump.8 zic.8 ./.install_pkg/man/man8/.
make[1]: Leaving directory '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a'
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Africa' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Africa': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/America' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/America': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Asia' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Asia': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Atlantic' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Atlantic': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Etc' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Etc': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Europe' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Europe': Permission denied
mv: cannot move '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/etc/zoneinfo/Pacific' to '/home/josu/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/timezone-data-2016a/.install_pkg/usr/share/zoneinfo/Pacific': Permission denied
make: *** [image] Error 1`

I don't know why these folders can not be moved... I tried to change permissions but no luck.  I can copy manually these folders to destination but when I try to compile again, it fails in the same place...

I think the problem must be related with compiling with bash on ubuntu on windows, because I tried in several PCs with W10 and always fails in the same place and if I do the same in another ubuntu PC it worked...
- Windows build number: 14393
- Steps / commands required to reproduce the error: Just follow the official instructions here: https://wiki.libreelec.tv/index.php?title=Compile

`sudo apt update && sudo apt upgrade
sudo apt install gcc make
git clone https://github.com/LibreELEC/LibreELEC.tv.git
cd ~/LibreELEC.tv
PROJECT=RPi2 ARCH=arm make image`

**Comment by sirdezzy** [comment]
Finding the same issue building OpenELEC and LibreELEC. Not specific to either builds, seems to be issue with WSL itself.

**Comment by fabio70mi** [comment]
Same problem

**Comment by sunilmut** [comment]
Thanks for the post. Apologize for the slow response. I was able to repro this on the latest Insider build 15046. Will need some time to root cause. Also adding @SvenGroot.

**Comment by therealkenc** [comment]
Probably another #1529
