### ISSUE TITLE
Admin enforcing .wslconfig settings

### ISSUE THREAD

**Issue by zeehio** [microsoft/WSL#10602]
**Is your feature request related to a problem? Please describe.**

Enforcing security on a WSL distribution is currently very hard or imposible, since WSL bypasses the windows firewall by default. The September 2023 update makes it easier to enforce windows firewall rules using the mirrored mode and other network settings, but these experimental options must be written to the `.wslconfig` file, controlled by the user, instead of the administrator.

**Describe the solution you'd like**

As a system administrator I would like to enforce some `.wslconfig` settings to all the Linux distributions for all users in the system, without users being able to workaround them. I haven't seen an easy way to do that.

Is there any windows registry setting or policy or file that allows to restrict the valid .wslconfig allowed values?

Thanks!

**Describe alternatives you've considered**

- Changes in the Linux distribution (e.g. using "sudo iptables") are not reliable from a security perspective. The windows user has write access to the virtual Linux drive so the user can get sudo permissions by modifying the sudoers file in the virtual drive from the windows host.

**Additional context**

The security model of WSL2 is as follows:

1. The installation of the virtualization component requires admin privileges.
2. The installation of WSL Linux distributions does not require elevated privileges.
3. The virtual drive where the Linux distribution is stored is writeable by the user (see https://stackoverflow.com/q/64185560)
4. The user may enter WSL2 and run commands there with or without sudo, apparently having different privileges within the Linux instance.
5. Until the [September 2023 update](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update), WSL2 Linux network connections would not be affected by conventional Windows Firewall settings. This update provides some experimental settings that have to be applied to the `.wslconfig` file, writeable by a conventional unprivileged user.

**Comment by craigloewen-msft** [comment]
This is a great request! What specific settings would you want to enforce in .wslconfig ? And what values would you want to enforce them to:?

**Comment by zeehio** [comment]
Hey, thanks for listening!

This has been fixed with:

https://devblogs.microsoft.com/commandline/new-enterprise-grade-security-controls-for-the-windows-subsystem-for-linux/

Have a great day!
