### ISSUE TITLE
Driver segmentation fault when closing sfml window

### ISSUE THREAD

**Issue by Touchebag** [microsoft/WSL#10608]
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

SFML 2.5 (libsfml-dev)

### Repro Steps

Compile a minimal program opening and closing an SFML window

```
// main.cpp
#include <SFML/Window.hpp>

int main() {
    auto window = sf::Window();
    window.close();
}
```

Command line `g++ main.cpp -lsfml-graphics -lsfml-window -lsfml-system`

### Expected Behavior

The program should exit cleanly with no issues.

### Actual Behavior

Program produces a segfault in nvmdi driver during exit

```
(gdb) bt
#0  0x00007fffe99f2b56 in ?? () from /usr/lib/wsl/drivers/nvmdi.inf_amd64_faac8d1bca70beae/libnvwgf2umx.so
#1  0x00007fffe99f177e in ?? () from /usr/lib/wsl/drivers/nvmdi.inf_amd64_faac8d1bca70beae/libnvwgf2umx.so
#2  0x00007fffe99f16f6 in ?? () from /usr/lib/wsl/drivers/nvmdi.inf_amd64_faac8d1bca70beae/libnvwgf2umx.so
#3  0x00007ffff7baaac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007ffff7c3ca40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

It should be noted that the library works otherwise. Opening windows, rendering and all. It's only during shutdown (after closing window) that the segfault occurs.

Issue has been brought up with SFML devs but as it seemed to be a driver issue they were unable to proceed further.

**Comment by OneBlue** [comment]
Thank you for reporting this @Touchebag. This is unfortunately not an issue that WSL can help since the segfault is happening in nvidia code.

This issue should be reported [directly to nvidia](https://www.nvidia.com/en-us/support/consumer/).

Closing since the segfault happens in nvidia code.
