### ISSUE TITLE
App run as service can't visit wsl directory and files

### ISSUE THREAD

**Issue by lld1995** [microsoft/WSL#10617]
### Windows Version

Microsoft Windows [版本 10.0.19045.3448]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

Directory.Exists("\\wsl.localhost\Ubuntu\etc") or Directory.Exists("\\wsl$\Ubuntu\etc")

### Expected Behavior

it can visit the direcotry and files

### Actual Behavior

it returns not exist when i run my app as service

**Comment by lld1995** [comment]
and i try set service user as system or current admin user,it all failed

**Comment by lld1995** [comment]
and i try set service user as system or current admin user,it all failed

**Comment by OneBlue** [comment]
@lld1995: The right path takes two "\", so "\\wsl.localhost" in your case. depending on the language you're using you might need to double them ("\\\\wsl.localhost").

**Comment by lld1995** [comment]
> @lld1995: The right path takes two "", so "\wsl.localhost" in your case. depending on the language you're using you might need to double them ("\\wsl.localhost").

it both can't visit the directory
