### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by SilkArt** [microsoft/WSL#10615]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Open the Ubuntu app
2. Run `git clone (url)`

### Expected Behavior

I expected it to clone the git repo

### Actual Behavior

It gave a connection timeout error

**Comment by SilkArt** [comment]
This is the error:

Cloning into 'MagiskOnWSALocal'...
fatal: unable to access 'https://github.com/LSPosed/MagiskOnWSALocal.git/': Failed to connect to github.com port 443 after 134002 ms: Connection timed out

**Comment by SilkArt** [comment]
And here are the log files:
[bcdedit.txt](https://github.com/microsoft/WSL/files/12852861/bcdedit.txt)
[optional-components.txt](https://github.com/microsoft/WSL/files/12852862/optional-components.txt)
[wpr.txt](https://github.com/microsoft/WSL/files/12852863/wpr.txt)
[acl.txt](https://github.com/microsoft/WSL/files/12852865/acl.txt)
[appxpackage.txt](https://github.com/microsoft/WSL/files/12852866/appxpackage.txt)
[HKCU.txt](https://github.com/microsoft/WSL/files/12852867/HKCU.txt)
[HKLM.txt](https://github.com/microsoft/WSL/files/12852868/HKLM.txt)
[P9NP.txt](https://github.com/microsoft/WSL/files/12852869/P9NP.txt)
[Winsock2.txt](https://github.com/microsoft/WSL/files/12852870/Winsock2.txt)

**Comment by SilkArt** [comment]
[WslLogs-2023-10-09_21-45-52.zip](https://github.com/microsoft/WSL/files/12864573/WslLogs-2023-10-09_21-45-52.zip)

**Comment by SilkArt** [comment]
@benhillis Any update on this?

**Comment by keith-horton** [comment]
Hi there. I took a look at the trace. There isn't anything from this view that looks incorrect. Please collect the state within Linux with  https://github.com/microsoft/WSL/blob/master/diagnostics/networking.sh.

Then if you can get a packet mon capture, we can see if we can follow this through the NAT.
pktmon start -c --flags 0x1a

<repro>

pktmon stop

<that will generate pktmon.etl>

**Comment by kmanoj845** [comment]
I am also facing this issue. I have 
Windows 10 Enterprise, Version : 22H2, OS build : 19045.3570. I installed Ubuntu (Ubuntu 22.04.2 LTS) by following instructions provided on this page: https://learn.microsoft.com/en-us/windows/wsl/install. I have WSL2. I have git installed for windows. 
git clone https://github.com/AI4Bharat/indic-punct.git works in git bash.

It does not work in WSL.  
$ git clone https://github.com/AI4Bharat/indic-punct.git
Cloning into 'indic-punct'...
fatal: unable to access 'https://github.com/AI4Bharat/indic-punct.git/': Could not resolve host: github.com

Can someone help me with this?

**Comment by keith-horton** [comment]
If you are having name resolution issues, please look at troubleshooting documentation we just added here: https://github.com/MicrosoftDocs/WSL/blob/main/WSL/troubleshooting.md#troubleshooting-dns-in-wsl.

It walks through some configurations which can break name resolution from the WSL container - as well as a work around for an HNS issue which can also break connectivity.

Thanks!
