### ISSUE TITLE
`--event-viewer` option not working

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#10610]
### Windows Version

Microsoft Windows [Version 10.0.22621.2361]

### WSL Version

2.0.4.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

Run `wsl --event-viewer` to open the application view of the Windows Event Viewer.

### Expected Behavior

Open event viewer.

### Actual Behavior

```
PS C:\Users\elsaco> wsl --event-viewer
Invalid command line argument: --event-viewer
Please use 'wsl.exe --help' to get a list of supported arguments.
```

**Comment by benhillis** [comment]
Thank you, we removed this functionality but forgot to remove the command from the help text. This will be fixed in an upcoming release.

**Comment by benhillis** [comment]
Same issue as /dupe #10600
