### ISSUE TITLE
/usr/bin/pkexec /usr/bin/gdb does not work

### ISSUE THREAD

**Issue by SiyuChen** [microsoft/WSL#10626]
### Windows Version

Win10

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #3393-Microsoft Mon Aug 14 14:52:00 PST 2023

### Distro Version

Ubuntu 22.04

### Other Software

VScode with remote extension.

I basically follow https://nadiah.org/2020/03/01/example-debug-mixed-python-c-in-visual-studio-code/ to set up the debugger. The issue takes place at the following step:
![image](https://github.com/microsoft/WSL/assets/22484673/c6b32350-1d36-452a-ba82-a439832e3726)

### Repro Steps

pkexec /usr/bin/gdb

### Expected Behavior

gdb launches

### Actual Behavior

Error getting authority: Error initializing authority: Could not connect: No such file or directory

**Comment by zcobol** [comment]
@SiyuChen do you have the `Python C++ Debugger` extensions added to your `VSCode`? Also, do you have `gdb` installed? Using the `launch.json` from the tutorial `gdb` stats as expected:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceRoot}/bin/python", /* My virtual env */
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

Also, why do you use `pkexec` to launch `gdb`?

**Comment by SiyuChen** [comment]
@zcobol Have you managed to attach gdb to the Python debugger process on WSL?

I tried `Python C++ Debugger` but it does not work either. I indeed already installed `gdb ` on WSL.

I don't fully know the deep reason why `pkexec` is needed here for launching `gdb`, but in the instruction of https://nadiah.org/2020/03/01/example-debug-mixed-python-c-in-visual-studio-code, (please see the terminal output in Step 5), this is what I need WSL to do and it fails with saying `Error getting authority: Error initializing authority: Could not connect: No such file or directory`

Could you please help?

**Comment by zcobol** [comment]
@SiyuChen yes, attaching the debugger to the python debugger process works also. Here's a screenshot for reference:

![code_debug_test](https://github.com/microsoft/WSL/assets/104515072/d16fe4bc-e139-48b2-9bd0-0926c337302f)

**Comment by SiyuChen** [comment]
@zcobol Thank you very much! This looks great!! How did you manage to NOT use `pkexec`? 

Here is my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/home/siyu/bin/miniconda3/envs/test/bin/python", 
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
```
}

I don't see where I could ask VScode not to use `pkexec` before gdb. Thanks in advance for your help.
