### ISSUE TITLE
WSL cannot find rootfs location

### ISSUE THREAD

**Issue by FrodoChao** [microsoft/WSL#10627]
### Windows Version

Microsoft Windows [versions 10.0.19045.3448]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Repro Steps

> wsl.exe
指定的網路名稱無法使用。

### Expected Behavior

A BASH prompt is expected.

### Actual Behavior

Ubuntu subsystem does not start.

### Diagnostic Logs

> dir \\wsl$\Ubuntu-20.04
找不到網路名稱。

The actual location is at %localappdata%\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkplfndgsc\LocalState\rootfs, and \\wsl$\Ubuntu-20.04 is supposed to point to this location, but now it is a network folder (which does not exist at all).

This happens when I reboot my computer.

Maybe there is a way to configure the rootfs location when launching WSL?

**Comment by FrodoChao** [comment]
I renamed the old rootfs, unregistered Ubuntu-20.04, and install the distro again. Now everything works fine.

The problem is, what should be done to prevent this from happening again?

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3448

**Comment by benhillis** [comment]
What is unclear to me is how the path was modified to point to a network share, did you do this manually?

**Comment by FrodoChao** [comment]
No, I didn't do it manually.
If I can modify it, then I should be able to modify the path to the correct location.

**Comment by OneBlue** [comment]
@FrodoChao: You need two backslashes ( \\wsl$\Ubuntu-20.04).

If that doesn't work, can you share logs if trying to access that path with the windows explorer ? 

/logs

**Comment by FrodoChao** [comment]
> @FrodoChao: You need two backslashes ( \wsl$\Ubuntu-20.04).
> 
> If that doesn't work, can you share logs if trying to access that path with the windows explorer ?
> 
> /logs

Unfortunately, I didn't collect logs, so there is nothing to share.

**Comment by FrodoChao** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> Thank you!

Thank you for the tips.
I will collect logs if I encountered this problem again.
