### ISSUE TITLE
App run as service can't visit wsl directory and files

### ISSUE THREAD

**Issue by lld1995** [microsoft/WSL#10622]
### Windows Version

Microsoft Windows [版本 10.0.19045.3448]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Directory.Exists("\\\\wsl.localhost\Ubuntu\etc") or Directory.Exists("\\\\wsl$\Ubuntu\etc")

### Expected Behavior

it can visit the direcotry and files when app run as service.

### Actual Behavior

It returns not exist when i run my app as service
And i try to set service user as system or current admin user,it all failed.
But if i run app directly,it returns exist

**Comment by benhillis** [comment]
The `\\wsl.localhost' paths are all user-specific. Are you impersonating the user when trying to access this path?

**Comment by lld1995** [comment]
> The `\wsl.localhost' paths are all user-specific. Are you impersonating the user when trying to access this path?

yes,i have set service loged as the wsl run user

**Comment by OneBlue** [comment]
Thank you @lld1995. Can share the configuration of your service ?
