### ISSUE TITLE
i am getting an error on powershell

### ISSUE THREAD

**Issue by raomohsinkhan** [microsoft/WSL#10625]
PS C:\Users\HP> GET-CimInstance -query "SELECT (size/1024) from Win32_DiskDrive"
GET-CimInstance : Invalid query
At line:1 char:1
+ GET-CimInstance -query "SELECT (size/1024) from Win32_DiskDrive"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041017,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

**Comment by benhillis** [comment]
Not related to WSL.
