### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070424

### ISSUE THREAD

**Issue by Kare-Udon** [microsoft/WSL#10623]
### Windows Version

Microsoft Windows [Version 10.0.22635.2419]

### WSL Version

2.0.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

any

### Repro Steps

- Upgrade WSL to 2.0
- Try to switch to mirrored network using .wslconfig
- It says "Invalid networking 'Mirrored'"
- Switching back to NAT
-  It says "Invalid networking 'NAT'" (WTF）
- Try to reinstall WSL
- It says "WslRegisterDistribution failed with error: 0x80070424 Error: 0x80070424 The specified service does not exist as an installed service." (???)
- Try to hit 'repair' or 'reset' button in Settings menu of "WIndows Subsystem of Linux" and nothing changed

### Expected Behavior

It works.

### Actual Behavior

It doesn't work.

### Diagnostic Logs

[WslLogs-2023-10-11_15-48-33.zip](https://github.com/microsoft/WSL/files/12866576/WslLogs-2023-10-11_15-48-33.zip)

**Comment by benhillis** [comment]
Not much information in this trace, could you please collect the trace while reproducing the issue? /logs

Thanks!

**Comment by Kare-Udon** [comment]
> Not much information in this trace, could you please collect the trace while reproducing the issue? /logs
> 
> Thanks!

I used the script in a wrong way. This time it would be ok.

[WslLogs-2023-10-12_09-05-57.zip](https://github.com/microsoft/WSL/files/12875948/WslLogs-2023-10-12_09-05-57.zip)

**Comment by benhillis** [comment]
@keith-horton - HcnCreateNetwork Failed to open service: vfpext

**Comment by keith-horton** [comment]
FeatureName : VirtualMachinePlatform
State       : Disabled

Hi there. Please go to the "Turn Windows features on or off" and install "Virtual Machine Platform". That's required for WSL.

**Comment by Kare-Udon** [comment]
> FeatureName : VirtualMachinePlatform State : Disabled
> 
> Hi there. Please go to the "Turn Windows features on or off" and install "Virtual Machine Platform". That's required for WSL.

Thank you for your support! I only intall "Hyper-V" but not "Virtual Machine Platform". This time it works fine!

**Comment by jeffbromberger** [comment]
@keith-horton I just hit this myself and found your answer so thanks for that info!  

Is there a reason that the Virtual Machine Platform feature can't be automatically turned on when you turn on Windows Subsystem for Linux?   I enabled the latter and had to reboot only to find that it still wouldn't work.  After finding the cause here I had to reboot again to enable the second feature.  That doesn't seem ideal if WSL always requires VMP.

**Comment by keith-horton** [comment]
@jeffbromberger , yeah, this has hit a few people. Our WSL installer tries to declare dependencies, and it usually works. There appears to be some configurations which confuse MSI/MSIX into thinking the requisite dependencies are not yet installed :(

We have made a recent change to better detect this at startup to give a more specific warning.

**Comment by zubairahmed-ai** [comment]
> > FeatureName : VirtualMachinePlatform State : Disabled
> > Hi there. Please go to the "Turn Windows features on or off" and install "Virtual Machine Platform". That's required for WSL.
> 
> Thank you for your support! I only intall "Hyper-V" but not "Virtual Machine Platform". This time it works fine!

Works, thanks

**Comment by wittelw** [comment]
@keith-horton , I got hit by this when a perfectly working Ubuntu distro failed to start (very likely following KB5032190 - see https://aka.ms/AAnt772). Uninstalling Ubuntu and WSL and reinstalling both from Microsoft Store and admin PowerShell failed to turn on the "Virtual Machine Platform". I can't tell you at this point what turned this feature off, however it definitely is not getting turned back on by "wsl --install" in the current releases, so I really appreciate your work to address this and better error reporting!

```
Windows 11 Pro Version 23H2
Microsoft Windows [Version 10.0.22631.2792]

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2792
```

**Comment by JosephLagana** [comment]
Hi!
I had the same problem today.
For the resolution, i did follow the steps in this order and it worked. I hope it works for you. Please note that since i'm using Windows in a different language, the names that i'm using may differ from the original english form.
1)Open windows applications manager
2)Uninstall Ubuntu
3)Uninstall Windows subservice for Windows
5)Go to windows features and disable HyperV, windows subsystem for linux and Windows Virtual Machine Platform.
4)Go to cmd and open it as adm
5)type wsl --install
from now on follow the procedure that wsl tells you. 
Note that when wsl asks for a nickname use all lowercase letter.

Hope this helps, have a nice day!

**Comment by kangarooo** [comment]
Removed Ubuntu, WSL update, WSL in Add windows features deselected WSL
Restart
Installed in Features WSL
Restart
Did https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
Installed update
Restart
Opened WSL
Didnt open
In store opened Ubuntu 22.04.3
Installed
WORKS

It should fix it all automatically

**Comment by tobyliu415** [comment]
> Hi! I had the same problem today. For the resolution, i did follow the steps in this order and it worked. I hope it works for you. Please note that since i'm using Windows in a different language, the names that i'm using may differ from the original english form. 1)Open windows applications manager 2)Uninstall Ubuntu 3)Uninstall Windows subservice for Windows 5)Go to windows features and disable HyperV, windows subsystem for linux and Windows Virtual Machine Platform. 4)Go to cmd and open it as adm 5)type wsl --install from now on follow the procedure that wsl tells you. Note that when wsl asks for a nickname use all lowercase letter.
> 
> Hope this helps, have a nice day!

Great solution, it works for me
