### ISSUE TITLE
Add support for `wsl --restart` option

### ISSUE THREAD

**Issue by InvisibleDev** [microsoft/WSL#10624]
**Is your feature request related to a problem? Please describe.**
Sometimes when WSL env starts lagging, nothing can beat a simple restart. Right now this is achieved by executing 2 commands: `wsl --shutdown` and then starting back up my Ubuntu.

**Describe the solution you'd like**
`wsl --restart` would simply achieve exactly above in a single step.

**Describe alternatives you've considered**
Alternative is doing this in 2 steps as described above or create user custom macro which achieves smth similar.

**Additional context**
None

**Comment by benhillis** [comment]
Thanks for the suggestion, we are not planning on implementing this.
