### ISSUE TITLE
Starting WSL from "C:\Program Files\WSL\wsl.exe" in ssh session breaks my systemd service

### ISSUE THREAD

**Issue by aquirdTurtle** [microsoft/WSL#10634]
### Windows Version

10.0.22621.2283

### WSL Version

2.0.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1

### Distro Version

22.04

### Other Software

Python 3.10
Custom 3rd Party Software (C-based DLL)

### Repro Steps

Sorry, 3rd party software a block here. Just wanted to report though in case it is useful or anyone has any ideas. I realize solutions may be difficult.

### Expected Behavior

Running a python-based systemd service after starting wsl through `C:\Program Files\WSL\wsl.exe` should work the same as it does when running from desktop (not session 0) using `C:\Windows\system32\wsl.exe`

### Actual Behavior

My python code running in systemd works fine up until it tries to use a function from a 3rd party dll. The dll is loaded from python using `ctypes.cdll.LoadLibrary`, and on calling a function from said library I get `OSError: exception: access violation reading 0x0000000000000000`. I realize this is not helpful. I double-checked and was able to repeat this behavior, toggling back and forth between starting wsl through an ssh session (program files version) and through remote desktop (system32 version). Furthermore the 3rd party doesn't write particularly good code... so I wouldn't be surprised if this is due to the specifics of how this dll was compiled. 

I know there is some amount of work being done to resolve the inconsistency between the system32 wsl and program files wsl. I just hope that this resolves the issue and doesn't spread the issue to both methods...

**Comment by OneBlue** [comment]
Thank you for reporting this @aquirdTurtle. Can you share an strace of the command when it fails and when it suceeds to we can figure out what the difference comes from ? (strace -f <command>)
