### ISSUE TITLE
Can not update from 2.0.0 to 2.0.4

### ISSUE THREAD

**Issue by speller** [microsoft/WSL#10636]
### Windows Version

10.0.22621.2428

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I can not update 2.0.0 to 2.0.4 while the console output says nothing about the error. 

```none
> wsl --update --pre-release; echo $?
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.4.
False
PS C:\Users\mail> wsl --version
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22621.2428
```
The update command's return status is False - it fails.

The following events are in the event viewer:

<img width="1056" alt="image" src="https://github.com/microsoft/WSL/assets/1829515/3374b72c-096d-4ccd-abd4-628e202361af">

Event details in the chronological order:

> Beginning a Windows Installer transaction: C:\Users\mail\AppData\Local\Temp\129022800 (4). Client Process Id: 39492.
> 
> Starting session 0 - ‎2023‎-‎10‎-‎17T07:28:20.391883200Z.
> 
> Fault bucket 1517084156090128272, type 5
> Event Name: MoAppHangXProc
> Response: Not available
> Cab Id: 0
> Problem signature:
> P1: MicrosoftCorporationII.WindowsSubsystemForLinux_2.0.4.0_x64__8wekyb3d8bbwe
> P2: praid:wsl
> P3: 2.0.4.0
> P4: 651c8955
> P5: bc0e
> P6: 2129920
> P7: NO_PACKAGE
> P8: wsl.exe
> P9: 2.0.0.0
> P10: 
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.84f53461-02bb-42da-a2dc-98237b3a8bce.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f8077e9b-b49d-4ff2-acf1-4449388d1219.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ecba7873-24b4-4484-b467-67b1d5cd0aaa.tmp.txt
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e360d6b0-9f37-4302-be34-1fb235428d65.tmp.xml
> These files may be available here:
> \\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_MicrosoftCorpora_ada97687b666c9a3307e8dd8a3d314636615693f_63366c2c_270ca008-3e15-4698-9a94-ad35208d7ad7
> Analysis symbol: 
> Rechecking for solution: 0
> Report Id: 3443b3cd-ad9d-4e0f-a972-b053e67cad70
> Report Status: 2147487744
> Hashed bucket: 7f95a983b0360612050dc4008a201790
> Cab Guid: 0
> 
> The program wsl.exe version 2.0.4.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
>
> Product: Windows Subsystem for Linux -- Installation completed successfully.

It reports success while it has failed.

I'm running the update as a privileged administrator.

### Expected Behavior

I can update WSL

### Actual Behavior

Update fails

### Diagnostic Logs

Errors in the installation log:

```none
=== Verbose logging started: 2023-10-17  16:28:20  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
...
MSI (s) (2C:A4) [16:28:20:391]: Product not registered: beginning first-time install
MSI (s) (2C:A4) [16:28:20:391]: Product {1AD1E78D-8267-4776-B972-DF7AB5C1FBA7} is not managed.
MSI (s) (2C:A4) [16:28:20:391]: MSI_LUA: Credential prompt not required, user is an admin
MSI (s) (2C:A4) [16:28:20:391]: PROPERTY CHANGE: Adding ProductState property. Its value is '-1'.
MSI (s) (2C:A4) [16:28:20:391]: Entering CMsiConfigurationManager::SetLastUsedSource.
MSI (s) (2C:A4) [16:28:20:391]: User policy value 'SearchOrder' is 'nmu'
MSI (s) (2C:A4) [16:28:20:391]: Adding new sources is allowed.
MSI (s) (2C:A4) [16:28:20:391]: PROPERTY CHANGE: Adding PackagecodeChanging property. Its value is '1'.
MSI (s) (2C:A4) [16:28:20:391]: Package name extracted from package path: '129022800 (4)'
MSI (s) (2C:A4) [16:28:20:391]: Package to be registered: '129022800 (4)'
MSI (s) (2C:A4) [16:28:20:391]: Note: 1: 2205 2:  3: Error 
MSI (s) (2C:A4) [16:28:20:391]: Note: 1: 2262 2: AdminProperties 3: -2147287038 
MSI (s) (2C:A4) [16:28:20:391]: Machine policy value 'DisableMsi' is 0
...
=== Logging started: 2023-10-17  16:28:20 ===
MSI (s) (2C:A4) [16:28:20:407]: Note: 1: 2203 2: C:\Windows\Installer\inprogressinstallinfo.ipi 3: -2147287038 
MSI (s) (2C:A4) [16:28:20:407]: PROPERTY CHANGE: Adding Preselected property. Its value is '1'.
MSI (s) (2C:A4) [16:28:20:407]: Note: 1: 2205 2:  3: LaunchCondition 
MSI (s) (2C:A4) [16:28:20:407]: Note: 1: 2228 2:  3: LaunchCondition 4: SELECT `Condition` FROM `LaunchCondition` 
MSI (s) (2C:A4) [16:28:20:407]: APPCOMPAT: [DetectVersionLaunchCondition] Failed to initialize pRecErr.
MSI (s) (2C:A4) [16:28:20:423]: PROPERTY CHANGE: Adding ACTION property. Its value is 'INSTALL'.
...
Action ended 16:28:20: CreateFolders. Return value 0.
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2205 2:  3: Patch 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2228 2:  3: Patch 4: SELECT `Patch`.`File_`, `Patch`.`Header`, `Patch`.`Attributes`, `Patch`.`Sequence`, `Patch`.`StreamRef_` FROM `Patch` WHERE `Patch`.`File_` = ? AND `Patch`.`#_MsiActive`=? ORDER BY `Patch`.`Sequence` 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2205 2:  3: Error 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1302 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2205 2:  3: MsiSFCBypass 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2228 2:  3: MsiSFCBypass 4: SELECT `File_` FROM `MsiSFCBypass` WHERE `File_` = ? 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2205 2:  3: MsiPatchHeaders 
MSI (s) (2C:A4) [16:28:20:611]: Note: 1: 2228 2:  3: MsiPatchHeaders 4: SELECT `Header` FROM `MsiPatchHeaders` WHERE `StreamRef` = ? 
Action start 16:28:20: InstallFiles.
...
Property(S): SOURCEDIR = C:\Users\mail\AppData\Local\Temp\
Property(S): SourcedirProduct = {1AD1E78D-8267-4776-B972-DF7AB5C1FBA7}
MSI (s) (2C:A4) [16:28:59:703]: Note: 1: 1707 
MSI (s) (2C:A4) [16:28:59:703]: Note: 1: 2205 2:  3: Error 
MSI (s) (2C:A4) [16:28:59:703]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1707 
MSI (s) (2C:A4) [16:28:59:703]: Note: 1: 2205 2:  3: Error 
MSI (s) (2C:A4) [16:28:59:703]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (2C:A4) [16:28:59:703]: Product: Windows Subsystem for Linux -- Installation completed successfully.
...
```

**Comment by daddycocoaman** [comment]
Same issue on Windows Build 23565. If I try to upgrade in an administrative prompt, it doesn't error out in the console but it also doesn't actually update. The error missing from OP text at the bottom is:

```
MSI (s) (F0:5C) [14:42:24:884]: Windows Installer installed the product. Product Name: Windows Subsystem for Linux. Product Version: 2.0.4.0. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 1603.
```

**Comment by pmartincic** [comment]
Can we have full /logs? Please?

**Comment by JAZ-013** [comment]
I had this issue just now.  Installed the MSI from the releases page and was able to update to 2.0.4.

**Comment by speller** [comment]
@pmartincic 

[wsl-install-logs_.txt](https://github.com/microsoft/WSL/files/12974929/wsl-install-logs_.txt)

Here is the full log. I've redacted some sensitive data in it.

**Comment by OneBlue** [comment]
Unfortunately this is known issue that was introduced in 2.0 and the only way to solve it is to do a clean installation from `2.0.4` or above.

In your case I recommend manually installing [2.0.6](https://github.com/microsoft/WSL/releases/download/2.0.6/wsl.2.0.6.0.x64.msi). This should solve the issue

**Comment by speller** [comment]
Yes, manual upgrade worked.

**Comment by Elnadrion** [comment]
Had the same problem, manual installation helped, thanks 😇

**Comment by OneBlue** [comment]
Closing since the manual upgrade solved the issue.
