### ISSUE TITLE
SSH sessions disconnect when running group policy update (Virtual Adapter Reset?)

### ISSUE THREAD

**Issue by decarlo-cliff** [microsoft/WSL#10638]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

WSL version: 1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.90.1

### Distro Version

Ubuntu 22.04.3 LTS

### Repro Steps

1. Connect a SSH session to an external host
2. Ping an external host from a wsl2 console
3. Run the group policy update (gpupdate or gpupdate /force)

This will cause the SSH sessions to disconnect and the pings to drop packets and report destination host unavailable.  It looks like the group policy update is restarting the Hyper-V virtual adapter during the group policy update.

### Expected Behavior

SSH sessions should not drop (and Hyper-V virtual adapter should not be reset).

### Actual Behavior

SSH client sessions get disconnected and ping packets drop and report destination host unavailable.

client_loop: send disconnect: Broken pipe

From 172.17.161.41 icmp_seq=81 Destination Host Unreachable
From 172.17.161.41 icmp_seq=82 Destination Host Unreachable
From 172.17.161.41 icmp_seq=83 Destination Host Unreachable

126 packets transmitted, 119 received, +3 errors, 5.55556% packet loss, time 126514ms

**Comment by OneBlue** [comment]
Unfortunately if the network adapters are reset there is no way to maintain a connection. If you need a shell that can persist connectivity drops, I'd recommend [mosh](https://github.com/mobile-shell/mosh)
