### ISSUE TITLE
Update windows 2019 version of WSL1

### ISSUE THREAD

**Issue by paradoxicalNL** [microsoft/WSL#10641]
Hi! I am happily running WSL1 in windows server 2019, version > 4.4.0-17763-Microsoft. WSL build i am using would be 17763. Now I want to update this to following version:

https://github.com/MicrosoftDocs/WSL/releases/tag/21354
or even build 18890, as I suffer from BOUND ports on making connections and I need this solved asap. Installing WSL2 is not an option (and not even possible in windows 2019 i think).

I don't see any packages available (like which are available for WSL2). Can I find these packages somewhere or can I compile these myself? Any pointers would be greatly appreciated.

Thanks

**Comment by sirredbeard** [comment]
Servicing WSL updates via `wsl.exe --update` requires Windows builds 19044 or higher.

Builds prior to 19044 were serviced by upgrading versions of Windows.

It is not possible to compile your own versions of WSL1.

To get the fix from 18890 or 21354 to Windows Server 2019, the WSL team would need to backport a fix to 17763.

The WSL team is generally only supporting 19044 or higher.

WSL1 itself is in maintenance mode.

Windows Server 2019 is just a few months from standard EOL.

Unfortunately, for these reasons, it is very unlikely this will happen.

**Comment by paradoxicalNL** [comment]
@sirredbeard thank you very much for this answer.
It just amazes me that 2019 came with a version that is unusable. So there is not really a solution to my problem then restarting WSL on a daily basis. I will ask our team to upgrade the OS to Windows Server 2022 - since this seems to be the only solution!

**Comment by paradoxicalNL** [comment]
Closed after detailed answer from @sirredbeard
