### ISSUE TITLE
Ubuntu distributions fail to start with error 0x80070522

### ISSUE THREAD

**Issue by jeffj254** [microsoft/WSL#10642]
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Install wsl with default Ubuntu distro using `wsl --install`
2. complete setup and user creation
3. Reboot
4. Open windows terminal
5. Attempt to open Ubuntu terminal

Attempting to run ubuntu2204.exe from an administrator prompt also returns the same error

### Expected Behavior

Ubuntu terminal launches

### Actual Behavior

Ubuntu terminal fails to launch with
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070522
Error: 0x80070522 A required privilege is not held by the client.

Press any key to continue...
```

If I run a different distro like Kali first and then try Ubuntu, it will open normally.  It also works if I run vscode as administrator and then open a Ubuntu terminal there.  Once successfully opening an ubuntu terminal I can then run new terminals without errors.

**Comment by jeffj254** [comment]
I've also found that running `wsl.exe` first and then trying to open the terminal window works.  It seems like Ubuntu is not initializing wsl correctly

**Comment by ericohlin** [comment]
I also have this issue. 👍🏻

**Comment by mcaulifn** [comment]
Where are the log files saved?

**Comment by OneBlue** [comment]
The above script prints the log file location once done
