### ISSUE TITLE
Cuda kernel function doesn't print in wsl2

### ISSUE THREAD

**Issue by Tom-Teamo** [microsoft/WSL#10658]
### Windows Version

Microsoft Windows [version 10.0.19045.3570]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

Cuda compilation tools, release 12.3, V12.3.52
Nvidia Driver version: 537.58

### Repro Steps

I use a cuda kernel function in file `hello.cu`:
```
#include <stdio.h>

__global__ void hello() {
    printf("Hello from GPU\n");
}

int main() {
    hello<<<1, 1>>>();
    {
        cudaError_t e = cudaDeviceSynchronize();
        if (e != cudaSuccess)
            printf("kernel launch failed with error \"%s\".\n",
                   cudaGetErrorString(e));
        else
            printf("kernel launch succeeded");
    }
    return 0;
}
```
then I compile this file:
```
nvcc hello.cu -o hello
```
finnally execute:
```
./hello
```

### Expected Behavior

it should print:
```
Hello from GPU
kernel launch succeeded
```

### Actual Behavior

```
kernel launch succeeded
```

**Comment by ashgold** [comment]
how did you solve this problem?
