### ISSUE TITLE
wsl.exe does not properly parse PowerShell variable for distribution

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/WSL#10669]
### Windows Version

10.0.23570.1000

### WSL Version

2.0.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Pengwin

### Other Software

PowerShell 7.4.0-preview.6

### Repro Steps

Run the following in PowerShell to set the name of the default WSL distro as $defaultDistro and echo:
`$defaultDistro = wsl -l -v | Where-Object { $_ -match '(\*|DEFAULT)' } | ForEach-Object { ($_ -split ' +')[1] }; echo $defaultDistro`

Run the following in PowerShell to set the username of the default user of $defaultDistro as $defaultUser and echo:
`$defaultUser = wsl -d $defaultDistro whoami; echo $defaultUser`

### Expected Behavior

The username of the default user of $defaultDistro would be set as $defaultUser and echoed. 

### Actual Behavior

$defaultUser is set to`Argument --distribution is missing a required parameter.` 

This does not correspond to a missing distribution name or incorrect distro name.

![image](https://github.com/microsoft/WSL/assets/33820650/da8a7eaa-dc20-4a8d-9222-b6649edd47bf)

Adding `.Trim()` to the $defaultDistro assignment does not address the issue:

![image](https://github.com/microsoft/WSL/assets/33820650/1717655f-61b7-48a5-8f76-5f4979fd5d7d)

**Comment by OneBlue** [comment]
Thank you for reporting this @sirredbeard. 

WSL does not "parse" powershell variables. Powershell expands the variables and then calls WSL with expanded variables. 

Interestingly, I can reproduce the issue you're seeing but I'm not a powershell expert so i can't explain it. I recommend opening an issue on [the powershell repository][https://github.com/PowerShell/PowerShell)

**Comment by craigloewen-msft** [comment]
This drove me crazy so I had to look into it. The answer is because `wsl.exe -l -v` is UTF 16! So you can fix this by setting the UTF8 variable.

```
PS C:\Users\crloewen> $env:WSL_UTF8=1
PS C:\Users\crloewen> $defaultDistro = wsl -l -v | Where-Object { $_ -match '(\*|DEFAULT)' } | ForEach-Object { ($_ -split ' +')[1] }; echo $defaultDistro
Ubuntu
PS C:\Users\crloewen> wsl echo $defaultDistro
Ubuntu
PS C:\Users\crloewen>
```

**Comment by sirredbeard** [comment]
It's always UTF.

**Comment by tonymet** [comment]
> This drove me crazy so I had to look into it. The answer is because `wsl.exe -l -v` is UTF 16! So you can fix this by setting the UTF8 variable.

thank you for explaining this workaround. I was going bonkers.  For future readers, here are some examples

```

### Before – Output = UTF-16

```
wsl --list -q | select-Object -first 1 |format-hex 

   Label: String (System.String) <0926008A>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 44 00 65 00 62 00 69 00 61 00 6E 00             D e b i a n 
```

### AFTER – Output = UTF 8

```
 wsl --list -q | select-Object -first 1 |format-hex

   Label: String (System.String) <25238533>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 44 65 62 69 61 6E                               Debian
```

**Comment by tonymet** [comment]
@OneBlue Can we reopen this bug?   Powershell tools are expected to be UTF8 by default.  Otherwise, there should be warnings printed to STDERR.  UTF16 is very uncommon in terminals.
