### ISSUE TITLE
Please, Reopen #10662

### ISSUE THREAD

**Issue by josemtella** [microsoft/WSL#10678]
### Windows Version

Any windows 11

### WSL Version

2.0.X.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Reopen bug. #10662. Distro maintainers suggest to come back

ONLY OCCURS en wsl 2.0.X.0

### Expected Behavior

Let it work as in previous versions

### Actual Behavior

Still crashing in versions 2.0.X.0. Please, Reopen #10662

**Comment by OneBlue** [comment]
The right place for this issue would be [here](https://github.com/WhitewaterFoundry/Pengwin-Enterprise/issues). Once the distro maintainers looked at it we can continue the discussion on #10662 and it can be reopened if needed.
