### ISSUE TITLE
Feature request: update Direct3D from 1.608.2 to 1.611.0 for AV1 encode libVA support under WSL..

### ISSUE THREAD

**Issue by oscarbg** [microsoft/WSL#10671]
**Is your feature request related to a problem?

yes in part.. I want to get support for AV1 encode under VAAPI (LibVA) under WSL..
this required until few days ago a Agility Preview release (711) but now with [SDK 1.611.0](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12/1.611.0) we get DX AV1 encode in a stable Agility SDK release..

Mesa master right now supports AV1 D3D encode.. as shown by commits like these:

> https://cgit.freedesktop.org/mesa/mesa/commit/?id=1d5b5bb9e18055f1d87f3171e21b814661d3a4d9

right now we get `Versión de Direct3D: 1.608.2-61064218 ` as shown using latest WSL 2.0.5 build:
```
wsl --version
Versión de WSL: 2.0.5.0
Versión de kernel: 5.15.133.1-1
Versión de WSLg: 1.0.59
Versión de MSRDC: 1.2.4485
Versión de Direct3D: 1.608.2-61064218
Versión DXCore: 10.0.25880.1000-230602-1350.main
Versión de Windows: 10.0.25951.1000
```

**Describe the solution you'd like**
update Direct3D from "Direct3D: 1.608.2-61064218" to 611..

**Describe alternatives you've considered**
no other way to support it..

**Additional context**

**Comment by benhillis** [comment]
Good timing, I've already made this change and it will be in WSL 2.0.6.

**Comment by oscarbg** [comment]
nice!
just a quick question @benhillis : it's possible for an user to update these libraries (Agility SDK version) without waiting for WSL version updates.. even in a hacky (unsupported way).. mainly thinking about for testing Agility "preview" releases such as work graphs or WMMA under WSL..

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL/releases/tag/2.0.6
