### ISSUE TITLE
WSL 2.0.6 mirrored network - can not connect to Docker container ports from Windows host

### ISSUE THREAD

**Issue by speller** [microsoft/WSL#10683]
### Windows Version

10.0.22621.2500

### WSL Version

2.0.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

- Configure WSL to use the mirrored networking mode.
- Open a port in a Docker container.
- Connect to this port using `localhost:port` from the host Windows system.

### Expected Behavior

Connected successfully.

### Actual Behavior

Chrome error:

> This site can’t be reached
> localhost refused to connect.

### Diagnostic Logs

Configuration:
```
[wsl2]
autoMemoryReclaim=gradual
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
```

Reconfiguration to the NAT mode solves the issue.

**Comment by kyryl-bogach** [comment]
+1

**Comment by dons20** [comment]
This definitely cost me quite a few hours of development time as I tried to identify the root cause of certain docker connections being randomly rejected.

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues
