### ISSUE TITLE
Force shutdown and restart the PC, and then launch wsl, show Error code: Wsl/Service/CreateInstance/MountVhd/0×80070570

### ISSUE THREAD

**Issue by GladioFeng** [microsoft/WSL#10684]
### Windows Version

Microsoft Windows [Version 10.0.19042.8671]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu20.04

### Repro Steps

1. Wsl Runing
2. Forced shutdown

### Expected Behavior

open wsl

### Actual Behavior

![IMG_5474](https://github.com/microsoft/WSL/assets/100987925/fbe5811e-acca-489a-a736-98e543490d7d)

Error code: Wsl/Service/CreateInstance/MountVhd/0×80070570

**Comment by xiezhipeng-git** [comment]
@GladioFeng 
Have you solved this problem? How was it resolved?

**Comment by HuangLab-CBI** [comment]
No, I reinstall the wsl lastly.
