### ISSUE TITLE
the IP has changed after updating to WSL 2.0.6

### ISSUE THREAD

**Issue by FlowerBirds** [microsoft/WSL#10682]
### Windows Version

 10.0.22635.2486

### WSL Version

2.0,6

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 18.04

### Other Software

PS C:\Users\merit> wsl --version
WSL 版本： 2.0.6.0
内核版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25880.1000-230602-1350.main
Windows 版本： 10.0.22635.2486

### Repro Steps

download Microsoft.WSL_2.0.6.0_x64_ARM64.msixbundle and install.

### Expected Behavior

ip not changed.

### Actual Behavior

After start wsl and create new network（以太网适配器 vEthernet (WSL (Hyper-V firewall))）.

old ip: 172.29.190.147
new ip: 172.28.220.144
```
以太网适配器 vEthernet (WSL):

   连接特定的 DNS 后缀 . . . . . . . :
   IPv4 地址 . . . . . . . . . . . . : 172.29.176.1
   子网掩码  . . . . . . . . . . . . : 255.255.240.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 vEthernet (WSL (Hyper-V firewall)):

   连接特定的 DNS 后缀 . . . . . . . :
   IPv4 地址 . . . . . . . . . . . . : 172.28.208.1
   子网掩码  . . . . . . . . . . . . : 255.255.240.0
   默认网关. . . . . . . . . . . . . :
```

### Diagnostic Logs

When starting up after installing WSL, there were two error log lines indicating that the previous network adapter could not be used and a new network adapter was created. Unfortunately, I forgot to take a screenshot!

**Comment by speller** [comment]
I had the same issue. The following warnings are in the Event Viewer:

> Failed to create virtual network with address range: '172.26.192.0/20', created new network with range: '172.23.128.0/20', The object already exists. 
>
> Failed to create network endpoint with address: '172.26.203.151', assigned new address: '172.23.133.222'

**Comment by benhillis** [comment]
Hyper-V firewall is now enabled by default, this requires creating a new virtual network.
