### ISSUE TITLE
Warning during installation via .msi installer

### ISSUE THREAD

**Issue by adokitkat** [microsoft/WSL#10692]
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

2.0.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Repro Steps

Try to install latest pre-release version (2.0.6) via x64 .msi installer.

### Expected Behavior

To not get any warning or error.

### Actual Behavior

Get this warning message:

```
Warning 1946.Property
'System.AppUserModel.ToastActivatorCLSID' for shortcut
'WSL.Ink' could not be set.
```

![Screenshot 2023-10-30 003608](https://github.com/microsoft/WSL/assets/1345895/15fb1ed1-e94a-4b06-87fa-9fa803424656)

However it seems version 2.0.6 did install anyway.

**Comment by OneBlue** [comment]
Thank you for reporting this @adokitkat.

Can you try to collect the MSI logs of an installation with this warnings ? You can do that via: 

```
msiexec /i <path/to/msi> /L*V C:\wsllogs.txt
```

You might need to remove WSL for the warnings to show up again during installation.

**Comment by soutzis** [comment]
I'm experiencing this. WSL got bricked on its own and I can't even remove it from my system!

**Comment by OneBlue** [comment]
> I'm experiencing this. WSL got bricked on its own and I can't even remove it from my system!

What do you mean by you "can't remove it" ? What exact error do you see ?

**Comment by soutzis** [comment]
> > I'm experiencing this. WSL got bricked on its own and I can't even remove it from my system!
> 
> What do you mean by you "can't remove it" ? What exact error do you see ? 

Idk, even uninstalling it and disabling the optional feature would still not work. Even if I uninstalled it, it would still seem like it was still installed. A chad in the comments for a similar issue advised to manually delete a registry key (i think it was wslService?) and after that it got fixed.

**Comment by Mikary29** [comment]
I also uninstalled WSL and it is still there. Us telling you these things are what helps you guys and gals create the best product. That no one could ever beat. If you would quit avoiding actual problems. No one is perfect, don't have to act so sour.
