### ISSUE TITLE
'wsl --version' not available any more

### ISSUE THREAD

**Issue by Peter-76** [microsoft/WSL#10693]
### Windows Version

Microsoft Windows [Version 10.0.19045.3570]

### WSL Version

2.0.6

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Repro Steps

wsl --version

### Expected Behavior

Version output

### Actual Behavior

~#@❯ wsl.exe --version
Ungültige Befehlszeilenoption: --version
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Verwendung: wsl.exe [Argument] [Options...] [CommandLine]

...

**Comment by benhillis** [comment]
/logs

I suspect the store version of WSL has been uninstalled.

**Comment by Peter-76** [comment]
Hello!

Here are the Logs:
[WslLogs-2023-10-30_19-06-57.zip](https://github.com/microsoft/WSL/files/13208825/WslLogs-2023-10-30_19-06-57.zip)

Update on the issue:
--version works well as administrator:

> wsl --version
WSL version: 2.0.6.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3570

Also the reported kernel version is newer/current here.
Looks like something went wrong during update to 2.0.6.0.

**Comment by benhillis** [comment]
Can you clarify your statement about --version working as administrator? Does it work as one user and not as the other? If so, what environment are you running with the user that does not work?

**Comment by Peter-76** [comment]
I try to clarify:
'wsl --version' works as expected in an elevated powershell session but does not work in a standard powershell session.

**Comment by benhillis** [comment]
That is very odd. Can you run this in both?
`cmd.exe /c where wsl`

**Comment by Peter-76** [comment]
Standard:
~#@❯ cmd.exe /c where wsl                                                                                                                                                     ❮  
C:\Windows\System32\wsl.exe
C:\Users\nmr\AppData\Local\Microsoft\WindowsApps\wsl.exe

Elevated:
> cmd.exe /c where wsl
C:\Windows\System32\wsl.exe
C:\Users\nmradm\AppData\Local\Microsoft\WindowsApps\wsl.exe

**Comment by Peter-76** [comment]
I've checked the store -> wsl was missing there, after I installed from store 'wsl --version' works and shows the correct versions.

So problem fixed... but now I reproduced the issue:

>~#@❯ wsl --version
WSL version: 2.0.6.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3570

Check for update:

>~#@❯ wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.7.
Der angeforderte Vorgang erfordert erhöhte Rechte.
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.7.

This asks for elevated privileges - I don't remember this from older versions.
After the update, old issue again:

>~#@❯ wsl --version
Ungültige Befehlszeilenoption: --version
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
>
>Verwendung: wsl.exe [Argument] [Options...] [CommandLine]
>
>Argumente zum Ausführen von Linux-Binärdateien:
>
>    Wenn keine Befehlszeile angegeben wird, startet wsl.exe die Standardshell.
>
>    --exec,-e <CommandLine>
>        Führen Sie den angegebenen Befehl aus, ohne die Standard-Linux-Shell zu verwenden.
>
>    --
>        Übergeben Sie die restliche Befehlszeile ohne Änderung.
>...

Install from store again:

>~#@❯ wsl --version
WSL version: 2.0.7.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3570

**Comment by Peter-76** [comment]
I think my problem started a bit earlier.
A week ago I tried to update from 2.0.0 to 2.0.5, this failed (see [my comment on #10635](https://github.com/microsoft/WSL/issues/10635#issuecomment-1774595412)).
I installed the msi package from the wsl repo -> this worked but I think this was the start of the problem.

**Comment by OneBlue** [comment]
> So problem fixed... but now I reproduced the issue:

Can you share a log collection during the installation ? I'd be curious to see what's happening.

/logs

**Comment by OneBlue** [comment]
Also @Peter-76: wsl --update is not sycnhronous (meaning that the installation runs in background), so it might be worth waiting a minute or two to see if the issue goes away

**Comment by Peter-76** [comment]
Ok, some more information:

WSL seems to be uninstalled/downgraded when I reboot !?
(WSL is working as expected -> reboot -> 'WSL --version' not working)

Logs after reboot, before installation of WSL via Store:
[WslLogs-2023-11-02_09-07-33.zip](https://github.com/microsoft/WSL/files/13236053/WslLogs-2023-11-02_09-07-33.zip)

Logs after installation of WSL via Store:
[WslLogs-2023-11-02_09-08-03.zip](https://github.com/microsoft/WSL/files/13236057/WslLogs-2023-11-02_09-08-03.zip)

After installation:
~#@❯ wsl --version
WSL version: 2.0.7.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3570

Note on the log-collection-script:
The script runs with an error:

>`>.\collect-wsl-logs.ps1`
>``
>`    Directory: C:\Git`
>``
>`Mode                 LastWriteTime         Length Name`
>`----                 -------------         ------ ----`
>`d----          02.11.2023    09:08                WslLogs-2023-11-02_09-08-03`
>`Der Vorgang wurde erfolgreich beendet`
>`Der Vorgang wurde erfolgreich beendet.`
>`Der Vorgang wurde erfolgreich beendet.`
>`get-appxpackage: C:\Git\collect-wsl-logs.ps1:36`
>`Line |`
>`  36 |  get-appxpackage MicrosoftCorporationII.WindowsSubsystemforLinux > $fo …`
>`     |  ~~~~~~~~~~~~~~~`
>`     | The 'get-appxpackage' command was found in the module 'Appx', but the module could not be loaded due to the`
>`     | following error: [Operation is not supported on this platform. (0x80131539)] For more information, run`
>`     | 'Import-Module Appx'.`
>`Log collection is running. Please reproduce the problem and press any key to save the logs.`
>`Saving logs...`
