### ISSUE TITLE
The difference in GPU running points between Windows and wsl is too large

### ISSUE THREAD

**Issue by androiddisk** [microsoft/WSL#10696]
### Windows Version

Microsoft Windows [版本 10.0.22621.2428]

### WSL Version

2.0.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1

### Distro Version

Ununtu 22.04

### Other Software

Download gputest on the official website or use the one I provided
https://www.geeks3d.com/gputest/

[GpuTest_Linux_x64_0.7.0.zip](https://github.com/microsoft/WSL/files/13215637/GpuTest_Linux_x64_0.7.0.zip)

[GpuTest_Windows_x64_0.7.0.zip](https://github.com/microsoft/WSL/files/13215638/GpuTest_Windows_x64_0.7.0.zip)

### Repro Steps

First of all, I will determine the graphics card driver that I need to install for the wsl

https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

The ubuntu can display graphics card information

```
root@future:~/kooapk/kooapk-kitchen/tmp/222/GpuTest_Linux_x64_0.7.0# nvidia-smi
Tue Oct 31 19:31:17 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.94       Driver Version: 472.88       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:2B:00.0  On |                  N/A |
|  0%   50C    P5    15W / 170W |   3446MiB / 12288MiB |    ERR!      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

ubuntu

```
./GpuTest /test=fur /width=1920 /height=1080 /fullscreen /benchmark
```

windows

```
.\GpuTest /test=fur /width=1920 /height=1080 /fullscreen /benchmark
```

### Expected Behavior

I feel that playing a video has resulted in a GPU usage rate of 98% when using EMBY software. I feel that the GPU performance under wsl has suffered a significant loss

So we specifically use gputest for score testing. Logically speaking, the difference in scores should not be too large

### Actual Behavior

The difference between running points and fps is too large

ubuntu
<img width="158" alt="27a7ce3506187062e3f660c2caa02e1" src="https://github.com/microsoft/WSL/assets/11062371/cf3ff591-39fc-4054-bcab-858d3d3720eb">

windows
<img width="202" alt="9803e575e66066d4816c3e87acb9db6" src="https://github.com/microsoft/WSL/assets/11062371/4266b60d-3294-409c-85fe-76a72bc44846">

**Comment by androiddisk** [comment]
@OneBlue @iourit @craigloewen-msft  May I ask if you can answer my question. thanks

**Comment by iourit** [comment]
This could be the result of inefficient update of the window content inside WSL vs. the host. Could you take ETW traces on the host for both scenarios using WPR (Windows Performance Recorder)? Open an elevated CMD window and run:
wpr -start GPU -filemode
<run your scenario>
wpr -stop tracefile.etl
You can look at the traces yourself using WPA.EXE or GpuView.EXE from Windows Performance tools (https://learn.microsoft.com/en-us/windows-hardware/test/wpt) and also share in this thread. 
https://learn.microsoft.com/en-us/windows-hardware/test/wpt/
Trace files could be big, so run your scenario only for several seconds.
