### ISSUE TITLE
WSLENV values exported to WSL with trailing equal-sign (=)

### ISSUE THREAD

**Issue by DennisDyallo** [microsoft/WSL#10697]
### Windows Version

Microsoft Windows [Version 10.0.19045.3570]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

```
PS C:\Users\dendya01> [System.Environment]::SetEnvironmentVariable("WSLENV", "Hello=World")
PS C:\Users\dendya01> wsl
```

```
dendya01-ubuntu@SR210633:/mnt/c/Users/dendya01$ env | grep -i hello
Hello=World=
WSLENV=Hello=World
dendya01-ubuntu@SR210633:/mnt/c/Users/dendya01$ echo $Hello
World=
```

### Expected Behavior
```
dendya01-ubuntu@SR210633:/mnt/c/Users/dendya01$ echo $Hello
World
```
without the trailing equal (=)-sign

### Actual Behavior
```
dendya01-ubuntu@SR210633:/mnt/c/Users/dendya01$ echo $Hello
World=
```
Notice the equal sign. What should I do with this?

**Comment by OneBlue** [comment]
@DennisDyallo: WSLENV doesn't contain the actual environment variables values, but only the list that should be "translated" between Windows and WSL.

For instance you can do: 

```
PS  [System.Environment]::SetEnvironmentVariable("WSLENV", "Hello")
PS   [System.Environment]::SetEnvironmentVariable("Hello", "World")
PS wsl
$ echo $Hello
World
```

See [this](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) for more details.

**Comment by DennisDyallo** [comment]
Thank you, that makes it so much more clear. I don't know why I wasn't able to gather that from blogpost you mentioned (which I'd skimmed though a couple of times)
