### ISSUE TITLE
In cat, vim, nano and other similar situations, the mouse wheel cannot be used.

### ISSUE THREAD

**Issue by 1trapbox** [microsoft/WSL#10707]
### Windows Version

Microsoft Windows [version 10.0.22621.2428]

### WSL Version

2.0.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

ubuntu 23.04

### Other Software

`vim` `nano` `cat` Similar file viewing/editing programs.
All software is based on the latest version of ubuntu23.04

### Repro Steps

use `vim` `nano` `cat` Similar file viewing/editing programs. open any file.

### for example
`sudo nano /etc/systemd/system.conf`

<img width="920" alt="Snipaste_Ubuntu_2023-11-02_17-18" src="https://github.com/microsoft/WSL/assets/118535944/9a036e39-f6c4-4128-9053-c5d9c29a639a">

Then the mouse wheel cannot scroll
Can only be scrolled via keyboard ↑↓

### Expected Behavior

Support mouse wheel scrolling

### Actual Behavior

no logs.
If so, please tell me where and I'll be happy to share.

**Comment by zyl-WHU** [comment]
I met the same issue in Ubuntu WSL2，but mouse wheel works well in Debian WSL2
