### ISSUE TITLE
Ubuntu 22.04.3 in start menu is named Ubuntu 22.04.2

### ISSUE THREAD

**Issue by kangarooo** [microsoft/WSL#10702]
### Windows Version

2H22

### WSL Version

1.2.5.0 shows info in russian

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu 22.04.3

### Repro Steps

Install Ubuntu from microsoft website like here mentioned
https://github.com/microsoft/WSL/issues/8402#issuecomment-1256020846
Update Ubuntu to latest
Still shows in start menu old version

### Expected Behavior

To show latest version in name

### Actual Behavior

.

**Comment by OneBlue** [comment]
WSL doesn't control the shortcut name for distributions. I'd recommend opening an issue [here](https://github.com/ubuntu/WSL/issues) instead
