### ISSUE TITLE
Can't even get it to start :/

### ISSUE THREAD

**Issue by DorkyPsych** [microsoft/WSL#10700]
I'm new to linux, although I have a little experience with other languages. I downloaded ubuntu and have been troubleshooting for the past 3 days (mostly looking for obscure settings that aren't on by default). But the most recent error is the hardest because it gives me very little information. Upon startup I get greeted with.

The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
Press any key to continue...
        Then if I press any button the terminal closes. If I open a tab before closing the terminal it shows the same text but with a red tint and when I press a key it tells me

[process exited with code 4294967295 (0xffffffff)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
        And no buttons work except enter which just loops back to the first text. this error code has a bunch of forums to address the problem but none of them have worked. I've gone to the command console to disable and enable the windows hypervisor platform. I've tried reinstalling updating and setting the versions of wsl, one of which was to use
wsl --set-version Ubuntu-20.04 1
to downgrade but no matter how I retype doesn't work with a variety of error reports depending on the wording. the most annoying problem is since I can't type anything in the terminal I can't explore the files very easily as every forum I've come across assumes you can look in the terminal and doesn't mention there location in file explorer or wherever. If anyone has any ideas It'd be really helpful and appreciated.

**Comment by spicerackk** [comment]
I am having a similar issue, however when I reboot my computer, Docker doesn't startup anymore and it won't run, and when I try to run a distro via cmd using wsl, it just hangs. If I run `wsl --update`, it says it's already the latest version. If I run `wsl --install Ubuntu`, it says it's already installed then says Launching Ubuntu but does absolutely nothing and just hangs. 

I have tried completely uninstalling all distro's and have turned off windows features, rebooted then turned them back on again with no change. Nothing on my computer changed between when it all worked two nights ago to yesterday morning when I woke up and nothing was working.
