### ISSUE TITLE
Windows 10 WSL2 no wifi and no internet, while wsl1 wifi and internet works.

### ISSUE THREAD

**Issue by arkady1200** [microsoft/WSL#10704]
### Windows Version

Microsoft Windows [Version 10.0.19045.3570]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.123.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Installed WSL1 with ubuntu.  Internet works.  Upgraded to WSL2 Ubuntu, no internet.

### Expected Behavior

Be able to connect to the internet.  Ping, apt update etc.

### Actual Behavior

ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
--- 1.1.1.1 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9366ms

### Diagnostic Logs

On WSL2
ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:ae:0f:91 brd ff:ff:ff:ff:ff:ff

on Wsl1
ip link
21: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether 00:15:5d:83:e9:c1
1: lo: <LOOPBACK,UP> mtu 1500 group default qlen 1
    link/loopback 00:00:00:00:00:00
4: wifi0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ieee802.11 78:0c:b8:e9:25:dc
13: wifi1: <> mtu 1500 group default qlen 1
    link/ieee802.11 78:0c:b8:e9:25:dd
9: wifi2: <> mtu 1500 group default qlen 1
    link/ieee802.11 7a:0c:b8:e9:25:dc

**Comment by mgarber-ops** [comment]
Have you tried temporarily disabling your windows firewall?

**Comment by arkady1200** [comment]
I did.

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues
