### ISSUE TITLE
wsl.exe hangs on launching

### ISSUE THREAD

**Issue by spicerackk** [microsoft/WSL#10710]
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu

### Other Software

Docker Desktop 

### Repro Steps

Load terminal, enter `wsl` and it doesn't do anything. Other commands like `wsl --install` show that Ubuntu is already installed then it says Launching Ubuntu but nothing happens. `wsl -l -v` also hangs and does nothing. 

I have tried to uninstall everything to do with WSL and ubuntu and restarted the pc, then tried to configure it all again but the same thing is still happening. 

### Expected Behavior

Allow me to configure and use ubuntu

### Actual Behavior

Nothing happens, it just keeps flashing a cursor at me.

### Diagnostic Logs

[WslLogs-2023-11-04_10-05-48.zip](https://github.com/microsoft/WSL/files/13255312/WslLogs-2023-11-04_10-05-48.zip)

**Comment by pmartincic** [comment]
Thanks for reporting and attaching logs.

**Comment by pmartincic** [comment]
If you use `resmon.exe` do you see other existing handles open?

<img width="522" alt="image" src="https://github.com/microsoft/WSL/assets/102559858/5856bbb2-4480-4b57-bee0-16a1191ef502">

**Comment by persalmi** [comment]
Same problem here with WSL on WIndows 11 since yesterday when it looks like the 2.0.9 update was installed. Directy after a restart of the PC I can run "wsl --list" but if I try starting a distro it just hangs with a blinking cursor.

**Comment by danieleades** [comment]
seeing this too for the last few days. WSL2 is my daily driver and I haven't found a workaround
