### ISSUE TITLE
Missing /proc/vmstat breaks software included with default installation.

### ISSUE THREAD

**Issue by sprink** [microsoft/WSL#1071]
Missing /proc/vmstat breaks programs like vmstat, which ship by default with the current installer.

Windows 10 Home version 1607 build 14393.105

To reproduce, run the command `vmstat`
You will see errors about /proc not being mounted.

`strace vmstat` will reveal that /proc/vmstat was not found.

`open("/proc/vmstat", O_RDONLY)          = -1 ENOENT (No such file or directory)`

**Comment by gudenuff** [comment]
@sprink 
Same thing with other utilities underneath `/proc`. I have the following:
```
root@computer:~# ls /proc/
1   2   35       cpuinfo      interrupts  meminfo  net   stat  uptime
19  20  cmdline  filesystems  loadavg     mounts   self  sys   version
```

```
root@computer:/proc# strace version
strace: Can't stat 'version': No such file or directory
```

**Comment by russalex** [comment]
Thank you for filing this.  I have filed this one as a bug.

To help prioritize, is this blocking a specific scenario?

**Comment by sprink** [comment]
This is not blocking anything for me. Uncovered it while troubleshooting an entirely unrelated issue. 

Thank you!

**Comment by phdyang007** [comment]
I also encountered this problem, and my dropbox could not work prompting missing /proc/vmstat

**Comment by bratsos** [comment]
Same error ( `[Errno 2] No such file or directory: '/proc/vmstat'` ) occurs after @EasyEngine 's installation.

**Comment by fantore** [comment]
dropbox original install as in 

http://www.dropboxwiki.com/tips-and-tricks/install-dropbox-in-an-entirely-text-based-linux-environment

is impacted by this bug.

I got this: IOError: [Errno 2] No such file or directory: '/proc/vmstat'

**Comment by JoseLauro182** [comment]
Will umask help fix the  [Errno 2] No such file or directory: '/proc/vmstat'  error? I don't understand the reference.

**Comment by fantore** [comment]
Same issue after upgrading to WSL 16.04 Xenial support

This happens just after installing dropbox,  daemon can not start. This is the generated log tail messages.

  File "dropbox/event.py", line 244, in start
  File "psutil/__init__.py", line 1626, in swap_memory
  File "psutil/_pslinux.py", line 195, in swap_memory
IOError: [Errno 2] No such file or directory: '/proc/vmstat'

**Comment by WizardCM** [comment]
Just to add to the list, [Glances](https://nicolargo.github.io/glances/) also fails to load due to lack of vmstat (log below).

```
/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py:344: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.6.2', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 130, in main
    args=core.get_args())
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 67, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 154, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 658, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_fs.py", line 103, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1801, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 899, in disk_partitions
    fstype = line.split("\t")[1]
IndexError: list index out of range
```

**Comment by robwilde** [comment]
is there any progress on this issue?

I utilise the EasyEngine.io suite for WordPress development and if I could run this in WSL, WOW that would make a massive difference to my production work and quite possibly a lot of Web Developers who work on windows machines.
The install process makes it all the way to the end and returns error. Hear are the last few lines

`Installed /usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg
Searching for python-apt==0.9.3.5ubuntu2
Best match: python-apt 0.9.3.5ubuntu2
Adding python-apt 0.9.3.5ubuntu2 to easy-install.pth file
Using /usr/lib/python3/dist-packages
Finished processing dependencies for ee==3.7.4
[Errno 2] No such file or directory: '/proc/vmstat'
`

really hoping to find a way around this or getting some info as to what is cuasing this issue.

**Comment by pedosb** [comment]
This is also causing problems for me we trying to run: https://github.com/ray-project/ray

**Comment by ThibzR** [comment]
@pedosb `sudo pip3 install psutil` fixes this issue

**Comment by Shaun252** [comment]
> @pedosb `sudo pip3 install psutil` fixes this issue

This did not solve the issue for me, still same error...

**Comment by mwilcox12015** [comment]
re: sudo pip3 install psutil fixes this issue
Why is pip3 being used to install psutil ?  Is psutil installed on Windows or in Ubuntu ? 
As a Mac user, can't we use an equivalent to brew ?  or use yum ?

**Comment by ColOfAbRiX** [comment]
```
root@host:~# pip3 install psutils
ERROR: Could not find a version that satisfies the requirement psutils (from versions: none)
ERROR: No matching distribution found for psutils
```

**Comment by dickymoore** [comment]
> @pedosb `sudo pip3 install psutil` fixes this issue

Unfortunately this doesn't work for tools like dropbox, which uses its own version of psutil.

Does anyone know another workaround? Can we fake a '/proc/vmstat'?

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/80077405-51619580-8502-11ea-96c8-cc80949444d6.png)

**Comment by wolf99** [comment]
Another "fixed-in-wsl2"  😞  This is not a solution for those of us held back or for which the 2004 update of Windows *still* hasn't rolled out to.

**Comment by WizardCM** [comment]
WSL2 should have rolled out to 1909 and 1903 if you're on x64. https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/

**Comment by wolf99** [comment]
Thanks @WizardCM  I had forgotten about that. It helps with my own machine, but unfortunately my work machine is held back on 1809 on a supposed "evergreen" program.
