### ISSUE TITLE
WSL 2.0.7 bridge mode doesn't work on Win 10 Pro without extra hackery

### ISSUE THREAD

**Issue by zenczykowski** [microsoft/WSL#10711]
### Windows Version

Microsoft Windows [Version 10.0.19045.3636]

### WSL Version

2.0.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Fedora 39

### Other Software

not important, it doesn't get that far

### Repro Steps

PS C:\Users\MaZe> wsl --version
WSL version: 2.0.7.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3636
PS C:\Users\MaZe> wsl
Failed to configure network (networkingMode Bridged). To disable networking, set `wsl2.networkingMode=None` in C:\Users\MaZe\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HCS/0x8037010d

this is with

PS C:\Users\MaZe> type .\.wslconfig
[wsl2]
dhcp = false
ipv6 = true
networkingMode = bridged
vmSwitch = External

and hyperV switch created External bridge

### Expected Behavior

it should use the ready bridge

### Actual Behavior

it errors out (see above)

Note that bridging *can* be made to work, by not putting networkingMode/vmSwitch in .wslconfig and instead *manually* changing the WSL bridge to be 'external' mode in HyperV switch manager.

This is just annoying to do, because it means the system boots with broken networking, and then needs to be manually fixed...

**Comment by zenczykowski** [comment]
note that the failure is different if the named bridge doesn't actually exist, for example:

PS C:\Users\MaZe> wsl
The VmSwitch 'NameOfAVMSwitchThatDoesNotExist' was not found.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/WSL_E_VMSWITCH_NOT_FOUND

so if you specify an existing VmSwitch, it does find it and it tries to use it... just something goes wrong

as a Linux kernel dev myself I'm guessing this is some stupid typo and can be fixed with a few lines of code...
(but of course who knows)

**Comment by pmartincic** [comment]
+@craigloewen-msft, I'm pretty sure we never released bridged mode as a supported/documented feature. If the state of the universe has changed I'll let craig update this bug.

**Comment by zenczykowski** [comment]
Considering bridge mode works, and it's just missing integration in the startup scripts to prevent one from having to manually set it up on every boot, that's a pity.

**Comment by onwardmk** [comment]
> Considering bridge mode works, and it's just missing integration in the startup scripts to prevent one from having to manually set it up on every boot, that's a pity.

@zenczykowski did you have a workaround? My personal laptop is on Windows 10 Pro, and neither bridged nor mirrored (#10823) networking mode are supported.

**Comment by zenczykowski** [comment]
The workaround is basically to *manually* reconfigure things after every
reboot.

Basically going into HyperV switch manager and manually forcing the WSL
bridge to bridge with the external wired nic [ie. External vSwitch mode].
Unfortunately this has a tendency to fail (by virtue of already being
busy/used by vSwitch/hyperV), so you also have to go into CMD+I -> network
configuration of the external nic and manually toggle it's vSwitch/hyperV
setting (and then try again).

It's... finicky, but I can always get things working in a minute or two,
and once it does, you're good until you reboot.

But note that this is with wired ethernet.
Wireless simply doesn't support bridging (it's basically a fundamental
limitation of wireless protocols, needing WDS for bridging which just isn't
very standardized nor well supported by wireless clients).

Also note I bought Win10 Pro thinking it would help, but I did have things
working with Win10 non-pro as well (previously), with just a normal (non
hyperv I think) bridge... the issue there was mostly that the normal bridge
driver would periodically panic the machine.  Eh, the wired broadcom nic in
this 27" 2013 iMac has a terrible windows driver: I have to turn off some
large receive/transmit and checksum offload to get good performance (in
Windows), and get DHCP working in WSL2.  I'd have never figured it out if I
wasn't actually a network developer...

Anyway, nowadays I don't really care any more.  I only use Win10 for gaming
(the hw is just slightly too old for Win11 so I can't upgrade it), and my
dev machines are all Linux based.

**Comment by onwardmk** [comment]
@zenczykowski thanks so much for the detailed response. I unfortunately only use WiFi to connect to the Internet with this laptop. Even if I was on Ethernet, the process you described sounds too cumbersome since I'd have to do that every time I reboot. I wanted to use my personal laptop to tinker, but I guess I can do that on my work laptop. Thanks again!
