### ISSUE TITLE
networkingMode: mirrored not working but virtioproxy does.

### ISSUE THREAD

**Issue by ssantosv** [microsoft/WSL#10717]
### Windows Version

10.0.19045.3570

### WSL Version

2.0.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

.wslconfig

networkingMode=virtioproxy

or 

networkingMode=mirrored

### Expected Behavior

For me, a mirrored network. **It des not work.**

EventViewer:
"No se admite el modo de red reflejada, revirtiendo a las redes NAT"

### Actual Behavior

I think I found a not documented mode that works:

networkingMode=virtioproxy 

It shows a new lookback0 interface with a 169 network and eth0 gets the same IP as the host network. Example (redacted)

sergio@desktop:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether [redacted] brd ff:ff:ff:ff:ff:ff
    altname [redacted]
    altname [redacted]
    inet **192.168.1.50**/24 brd 192.168.1.255 scope global eth0 **[THIS IP ADDRES IS THE SAME AS IN WINDOWS]**
       valid_lft forever preferred_lft forever
    inet6 [redacted]/64 scope link
       valid_lft forever preferred_lft forever
3: loopback0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether [redacted] brd ff:ff:ff:ff:ff:ff
    altname [redacted]
    altname [redacted]
    inet 169.254.73.153/30 brd 169.254.73.155 scope global loopback0
       valid_lft forever preferred_lft forever
    inet6 f[redacted]/64 scope link
       valid_lft forever preferred_lft forever

In windows:

Adaptador de Ethernet vEthernet (WSL):

   Sufijo DNS específico para la conexión. . :
   Vínculo: dirección IPv6 local. . . : fe80::2322:8351:528f:1874%35
   Dirección IPv4. . . . . . . . . . . . . . : 172.25.160.1
   Máscara de subred . . . . . . . . . . . . : 255.255.240.0
   Puerta de enlace predeterminada . . . . . :

Adaptador de LAN inalámbrica Wi-Fi:

   Sufijo DNS específico para la conexión. . :
   Vínculo: dirección IPv6 local. . . : fe80::f610:a801:c872:99c4%23
   Dirección IPv4. . . . . . . . . . . . . . : 192.168.1.50
   Máscara de subred . . . . . . . . . . . . : 255.255.255.0
   Puerta de enlace predeterminada . . . . . : 192.168.1.1

cat /etc/networks
symbolic names for networks, see networks(5) for more information
link-local 169.254.0.0

If no virtioproxy (no networkingMode swith, so NAT by default).

sergio@desktop:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1492 qdisc mq state UP group default qlen 1000
    link/ether [redacted] brd ff:ff:ff:ff:ff:ff
    inet 172.25.173.122/20 brd 172.25.175.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe08:66c7/64 scope link
       valid_lft forever preferred_lft forever

So:
* Why is mirrored not working?
*  this virtioproxy seems to be a new feature. Virtio is already used in WSL for GPU, but seems to be something is going to be used in networks?

**Comment by zcobol** [comment]
@ssantosv you need Windows 11 for `mirrored` mode to work!

**Comment by ssantosv** [comment]
Yeps, I guessed that it was for Windows 11 only (but it is mentioned in logs, as an option in Windows 10). 

But what is interesting is "virtioproxy" seems to be undocumented yet and working in Windows 10. Any information about it?

**Comment by pmartincic** [comment]
@ssantosv, as @zcobol says, mirrored is not supported on Win11. I'm having a hard time following your writing. If the issue is that NAT mode is not working, feel free to reopen the bug.

**Comment by YAMLcase** [comment]
Is there any documentation on VirtuoProxy?  I'm getting error message after ugprading to Windows 11 22H2:

```
wsl: Failed to configure network (networkingMode Nat), falling back to networkingMode VirtioProxy.

```

**Comment by Morrigan-Ship** [comment]
what is virtioproxy mode?

**Comment by bdarwin** [comment]
For Windows10 mirrored mode was fine. After windows11 upgrade, I couldn't get mirrored mode working. However, VirtioProxy mode works exactly like mirrored. No clue what it is and can't find any documentation.

```propertoes
WSL version: 2.5.7.0
Kernel version: 6.6.87.1-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.5335
```

**Comment by ssantosv** [comment]
That is what I was asking in the first place :). What is virtioProxy. The only documentation availible is me talking about it here....

**Comment by marbaa** [comment]
> For Windows10 mirrored mode was fine. After windows11 upgrade, I couldn't get mirrored mode working. However, VirtioProxy mode works exactly like mirrored. No clue what it is and can't find any documentation.
> 
> ```
> WSL version: 2.5.7.0
> Kernel version: 6.6.87.1-1
> WSLg version: 1.0.66
> MSRDC version: 1.2.6074
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.22631.5335
> ```

I wouldn't say that virtioproxy works exactly like mirrored. With mirrored you see all interfaces from Windows inside WSL distro. With virtioproxy, you see completely different interface.

**Comment by ssantosv** [comment]
Same question remains.

Virtioproxy appears as an option in the logs, but why isn’t it officially documented, as far as I know (AFAIK)?"

**Comment by krju13** [comment]
> Is there any documentation on VirtuoProxy? I'm getting error message after ugprading to Windows 11 22H2:
> 
> ```
> wsl: Failed to configure network (networkingMode Nat), falling back to networkingMode VirtioProxy.
> ```

My WSL also print same log. So I wonder what it means.
