### ISSUE TITLE
unreachable app installed by default : "Install RELEASE (Ubuntu)"

### ISSUE THREAD

**Issue by adrsr** [microsoft/WSL#10715]
### Windows Version

10.0.22621.2506

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.3 LTS

### Repro Steps

Hello everyone, I have installed a fresh WSL2 with the default install (wsl --install).

Once the computer has restarted there are 3 new entries in the Windows start/apps menu. 2 of them are expected : "Windows subsystem for linux" and "Ubuntu". But there's another weird one : "Install RELEASE (Ubuntu)".

It's actually a shortcut for launching an app installed as a snap on Ubuntu, with wslg.exe, the file is the following : `/var/lib/snapd/desktop/applications/ubuntu-desktop-installer_ubuntu-desktop-installer.desktop`

2 things :

- I believe this snap should not be installed by default, it's the Ubuntu desktop installer, it's rather confusing : https://github.com/Canonical/ubuntu-desktop-installer
- trying to start it from windows (from the start menu for example) will not work anyway. The target of the shortcut, being limited to 260 characters (windows limitation) fails to contain the entire path to the said file

In all, I believe this might be a little issue and maybe it is possible to fix the WSL/ubuntu installation in order to not have this strange thing showing afterwards.

there is this issue with complementary info : https://github.com/microsoft/wslg/issues/1027

### Expected Behavior

I don't expect this snap is installed by default. It may be a leftover after the installation ? It's confusing to see this after the installation of WSL2.

### Actual Behavior

See above in "repro steps"

**Comment by pmartincic** [comment]
This is currently intentional. We have a `--no-distribution` option on lifted. It is also inbox (without store wsl), but I don't know if that's rolled out to your build or not.

@craigloewen-msft thoughts? I know a little back we added this to lifted to match the match the behavior we had inbox.
