### ISSUE TITLE
can't use wsl command 

### ISSUE THREAD

**Issue by godlikegit** [microsoft/WSL#10728]
### windows version
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎8/‎9/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0
```

### command like this
```
PS C:\Users\admin> wsl
Access to %1 has been restricted by your Administrator by policy rule %2.
```

I installing the `wsl` by [ https://learn.microsoft.com/en-us/windows/wsl/install-manual](url)
I tryed many point like: `Run powershell as administrator` `restart my pc`
but the wsl command always tips above error.
What should i do?

**Comment by godlikegit** [comment]
> /logs

hi, here is the logs file:
[WslNetworkingLogs-2023-11-13_18-43-11.zip](https://github.com/microsoft/WSL/files/13334029/WslNetworkingLogs-2023-11-13_18-43-11.zip)

**Comment by OneBlue** [comment]
@godlikegit: It looks like your machine has a group policy that specifically blocks WSL. I'd recommend contacting your administrator to try to solve the issue.

Unfortunately this is not something that can be solved on the WSL side.

**Comment by zoeyzhao19** [comment]
I am encounting the same issue, have you solved it?
