### ISSUE TITLE
Oracle Java 8 process hangs when executed with no arguments, consumes 25% CPU

### ISSUE THREAD

**Issue by badvision** [Microsoft/WSL#1072]
- Brief description:
  After installing Oracle Java 8 from the Webupd8team PPA, the process is unable to start.  
- Expected results:
  The  executable should exit with usage instructions.
- Actual results (with terminal output if applicable)
  The command freezes and consumes 25% CPU
- Your Windows build number
  W10 Enterprise 1607
- Steps / All commands required to reproduce the error from a brand new installation 
  Installation instructions here: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

After installing, try to start Java command with no parameters (trying with -v to print version and exit also hangs in a similar manner)
- Strace of the failing command
  % time     seconds  usecs/call     calls    errors syscall
  ---
  
  0.00    0.000000           0         9           read
  0.00    0.000000           0        23        14 open
  0.00    0.000000           0         9           close
  0.00    0.000000           0         9         6 stat
  0.00    0.000000           0         9           fstat
  0.00    0.000000           0        23           mmap
  0.00    0.000000           0        12           mprotect
  0.00    0.000000           0         3           munmap
  0.00    0.000000           0         3           brk
  0.00    0.000000           0         2           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         7         6 access
  0.00    0.000000           0         1           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2           readlink
  0.00    0.000000           0         1           getrlimit
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         2         1 futex
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           set_robust_list
  ---
  
  100.00    0.000000                   120        27 total
- Required packages and commands to install
  See steps to reproduce

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by SRGOM** [comment]
Java currently has multiple issues in 14393 (anniversary build). #541 talks of it.

**Comment by therealkenc** [comment]
#746 #857
