### ISSUE TITLE
Network bridge broke after system update 

### ISSUE THREAD

**Issue by YumeAyai** [microsoft/WSL#10736]
### Windows Version

10.0.19045.3636

### WSL Version

2.0.7

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Apache mysql etc

### Repro Steps

After windows update my wsl net is broken and now could only visited service in wsl through ip(wsl) but not localhost add the port.
Another thing is the port might still be used so I can't reuse the port through in different host.

### Expected Behavior

visit my Apache and MySQL through localhost add ip , but not ip for wsl.

### Actual Behavior

I could only visit wsl through ip for wsl ,that is horrible , Actually my docker desktop is also be influenced and can't work at all

**Comment by benhillis** [comment]
Sorry wrong button :)

**Comment by YumeAyai** [comment]
Sorry for long time not see, I've known why I use apache in wsl, but the bridge used IPV6 so I colud only use [::1] to visit but not 127.0.0.1, hope for update.
