### ISSUE TITLE
ERROR_SHARING_VIOLATION with --export --vhd

### ISSUE THREAD

**Issue by JEAYNE** [microsoft/WSL#10737]
### Windows Version

Microsoft Windows [Version 10.0.22621.2506]

### WSL Version

2.0.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Repro Steps

```
wsl  --shutdown
wsl  --import  new_distro  .\dir\  distro.tar.gz
wsl  --list  --verbose 
wsl  --export  new_distro  new_distro.vhdx  --vhd
```

The `wsl --list` is not mandatory, it is just to check that all distro are _stopped_.

### Expected Behavior

When a distro is not running, I expect to be able to --export that distro using the --vhd format without the need to --shutdown WSL.

### Actual Behavior

The last step

> `wsl --export new_distro new_distro.vhdx --vhd`

generates this error

> ```
> The process cannot access the file because it is being used by another process.
> Error code: Wsl/Service/ERROR_SHARING_VIOLATION
> ```

Note: without the option `--vhd` it works without error and generate a tar file.

### Diagnostic Logs

[WslLogs-2023-11-10_15-10-17.zip](https://github.com/microsoft/WSL/files/13320430/WslLogs-2023-11-10_15-10-17.zip)

### Terminal output

_My wsl.exe displays a mix of French (my Windows region) and English (my Windows language). This is another [problem](https://github.com/microsoft/WSL/issues/9242#issuecomment-1787324180) ..._

```
C:\tmp>wsl --shutdown

C:\tmp>wsl --import my_distro .\dir\ alpine.tar.gz
Importation en cours. Cette opération peut prendre quelques minutes.
The operation completed successfully.

C:\tmp>wsl --list --verbose
  NAME                      STATE           VERSION
* OracleLinux_9_1           Stopped         2
  docker-desktop            Stopped         2
  my_distro                 Stopped         2
  docker-desktop-data       Stopped         2
  podman-machine-default    Stopped         2

C:\tmp>wsl --export my_distro my_new_distro.vhdx --vhd
Exportation en cours. Cette opération peut prendre quelques minutes.
The process cannot access the file because it is being used by another process.
Error code: Wsl/Service/ERROR_SHARING_VIOLATION
```

### Additional information
- In the same situation --export to tar format is working
- Between the --export and the --import I tried (without success) to
  * wait during several minutes
  * --terminate my_distro
- Only --shutdown fix the problem.

**Comment by JEAYNE** [comment]
I'm now using WSL 2.0.14.0 and the problem is still here :-(
(I don't really know what the label _fixinbound_ means, so I don't know what I can expect.)

@benhillis  Does this bug also explain why, when a distro is --terminate (status stopped), it is not possible to read its vhdx.ext4 to calculate its SHA1?

**Comment by davidgouldbjss** [comment]
Great.  Still broken :(

**Comment by Weltolk** [comment]
still

**Comment by aj-ats** [comment]
WSL version: 2.6.1.0 still

**Comment by bobitza** [comment]
> WSL version: 2.6.1.0 still

I found fix thank chatgpt: type this in power shell
`Get-Process | Where-Object { $_.ProcessName -match "wsl|vmmem|debian" }`

Then stop processes with :

`Stop-Process -Id 6840 -Force`

if wslservice stil running go to services -> WSL Service and STOP

Than run again move command

**Comment by gbraad** [comment]
Just run

```ps
PS> wsl --shutdown
```

beforehand!

> [!NOTE]
> this should be documented or mentioned in the error
