### ISSUE TITLE
zshrc not sourced and still souce /etc/profile after login

### ISSUE THREAD

**Issue by rickywu** [microsoft/WSL#10746]
### Windows Version

10.0.18363.720

### WSL Version

20.04

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

zsh 5.8

### Repro Steps

Install zsh and zsh-common by dpkg -i
chsh -s $(which zsh)

### Expected Behavior

echo $SHELL shows zsh and source ~/.zshrc

### Actual Behavior

echo $SHELL shows zsh but not source ~/.zshrc, still source /etc/profile

**Comment by zcobol** [comment]
@rickywu you are replacing the login shell, therefore you need to terminate your instance for it to take effect.

**Comment by rickywu** [comment]
I have login again, even though restart wsl, but still the same

**Comment by OneBlue** [comment]
Thank you @rickywu. Can you share the output of `cat /etc/passwd` after trying to change your shell ? 
You do need to run wsl --shutdown for the change to take effect.

**Comment by rickywu** [comment]
@OneBlue 
passwd:
root:x:0:0:root:/root:/usr/bin/zsh

wsl1 no shutdown, so I used terminate, but still the same, I also restarted host machine

**Comment by OneBlue** [comment]
Ok looks like the shell is correctly configured. 

Can you share the output of `zsh -x`  ?

**Comment by elsaco** [comment]
@rickywu the passwd entry is for `root`, Do you launch WSL  instance as user root or another user? You might have to change the shell for your user account also.

**Comment by rickywu** [comment]
I use LxRunOffline set default user as root, also I tried change to zsh for another user which created at installation, but no change.

**Comment by rickywu** [comment]
@OneBlue 
seems wsl zsh -x > log not work, how should I capture output?
But I can see zshrc sourced because I installed oh-my-zsh, the prompt changed
