### ISSUE TITLE
file "perf_event_paranoid" doesn't exist

### ISSUE THREAD

**Issue by Dagbert1337** [microsoft/WSL#10740]
### Windows Version

Microsoft Windows [Version 10.0.19045.3570]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Write in the terminal: sudo sysctl kernel.perf_event_paranoid=-1
2. Write your password if asked for

### Expected Behavior

Value in the file "/proc/sys/kernel/perf_event_paranoid" is set to "-1"

### Actual Behavior

Terminal says: "sysctl: cannot stat /proc/sys/kernel/perf_event_paranoid: No such file or directory"
(in fact, there is no such file in this directory)

**Comment by OneBlue** [comment]
@Dagbert1337: I can't reproduce the issue in latest WSL: 

```
$ cat /proc/sys/kernel/perf_event_paranoid
2
```
Can you try updating to the [latest version](https://github.com/microsoft/WSL/releases/tag/2.0.9) ?

**Comment by Dagbert1337** [comment]
reinstalling WSL helped, now everything works

**Comment by Dagbert1337** [comment]
reinstalling WSL helped, now everything works
