### ISSUE TITLE
wsl: Unknown key 'wsl2.autoMemoryReclaim'

### ISSUE THREAD

**Issue by dhtzs** [microsoft/WSL#10759]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 23.04

### Repro Steps

1. Create `.wslconfig` file with the following content:

```
[wsl2]
memory=24GB
autoMemoryReclaim=gradual
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
```

2. Terminate WSL using `wsl.exe --shutdown`
3. Start WSL and get the following warning message:
`wsl: Unknown key 'wsl2.autoMemoryReclaim'](wsl: Unknown key 'wsl2.autoMemoryReclaim' in C:\Users\<user>\.wslconfig:3)`

![image](https://github.com/microsoft/WSL/assets/12586834/a5f22804-f30e-4b0b-88c0-27d531632b6c)

### Expected Behavior

-

### Actual Behavior

-

**Comment by craigloewen-msft** [comment]
the `autoMemoryReclaim` feature is still experimental, and not yet in the `[wsl2]` setting. You can access it by adjusting your existing `.wslconfig` like so:

```
[wsl2]
memory=24GB
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
[experimental]
autoMemoryReclaim=gradual
```
