### ISSUE TITLE
WSL2 and Docker Desktop crashed

### ISSUE THREAD

**Issue by LitchiInn** [microsoft/WSL#10752]
### Windows Version

10.0.22631.2715

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Debian

### Other Software

Docker Desktop 4.25.1 (128006)

### Repro Steps

1. WSL started, everything is ok
2. Start Docker Desktop, show "Docker Engine stopped", 
3. When I create new tab of linux(wsl), I get error and wsl cannot start
~~~
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\system32
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\dotnet\
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate J:\Git\bin
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate K:\ffmpeg-master-latest-win64-gpl-shared\bin
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\ZeroTier\One\
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Tailscale\
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Docker\Docker\resources\bin
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\.cargo\bin
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\AppData\Local\Microsoft\WindowsApps
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\AppData\Local\JetBrains\Toolbox\scripts
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate K:\Microsoft VS Code\bin
<3>WSL (322) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (322) ERROR: UtilTranslatePathList:2853: Failed to translate L:\Administrator\AppData\Local\GitHubDesktop\bin
distrod 0.1.7

USAGE:
    -bash [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -l, --log-level <log-level>    Log level in the env_logger format. Simple levels: trace, debug, info(default), warn,
                                   error

SUBCOMMANDS:
    create
    disable
    enable
    exec
    help       Prints this message or the help of the given subcommand(s)
    start
    stop
~~~

another situation：
1. WSL started
2. Start Docker Desktop Service manually
3. Start Docker Desktop with Administrator
5. Docker Engine is running, but when I run `docker ps`, return `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
6. Then create new tab of linux(wsl),same as first situatin, and Docker Desktop show `Docker Desktp - Unexpected WSL error`
 
Everything is ok yesterday, I don't known what happened? Maybe Windows updated?

### Expected Behavior

<img width="857" alt="屏幕截图 2023-11-15 110410" src="https://github.com/microsoft/WSL/assets/31427353/c96e3ded-2f49-49af-9c71-b625b2e0de24">

### Actual Behavior

~~~

C:\Users\94189>wsl
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: CreateProcessParseCommon:708: Failed to translate C:\Users\94189
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\system32
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\dotnet\
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate J:\Git\bin
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate K:\ffmpeg-master-latest-win64-gpl-shared\bin
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\ZeroTier\One\
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Tailscale\
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Docker\Docker\resources\bin
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\.cargo\bin
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\AppData\Local\Microsoft\WindowsApps
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\94189\AppData\Local\JetBrains\Toolbox\scripts
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate K:\Microsoft VS Code\bin
<3>WSL (364) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (364) ERROR: UtilTranslatePathList:2853: Failed to translate L:\Administrator\AppData\Local\GitHubDesktop\bin
distrod 0.1.7

USAGE:
    -bash [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -l, --log-level <log-level>    Log level in the env_logger format. Simple levels: trace, debug, info(default), warn,
                                   error

SUBCOMMANDS:
    create
    disable
    enable
    exec
    help       Prints this message or the help of the given subcommand(s)
    start
    stop

~~~

**Comment by kissge** [comment]
I've found I could avoid the problem by disabling Distrod; i.e. launch the Distrod instance, and `sudo /opt/distrod/bin/distrod disable` in the Linux shell.

**Comment by rabindangol** [comment]
I got similar issue since yesterday. In my case when I open VS code from WSL. 
![image](https://github.com/microsoft/WSL/assets/5866812/67e27941-5eb1-44f0-86d8-d84f0ea28bab)
![vs-code-error](https://github.com/microsoft/WSL/assets/5866812/e568132c-71c8-4392-a9c4-13d8e99f1e17)

**Comment by Meai** [comment]
I think the easiest way to fix this is to do go into wsl once (still works for me after wsl --shutdown) then run `sudo /opt/distrod/bin/distrod disable`, then switch away from distrod (permanently?) because it's not really needed anymore and use the native systemd support that Windows added for wsl: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#:~:text=release%20page.-,Set%20the%20systemd%20flag%20set%20in%20your%20WSL%20distro%20settings,-You%20will%20need

This works for me so far, not sure yet if the distrod disablement sticks around after a windows restart.

**Comment by PacoCapgemini** [comment]
I have the same problem with vscode this morning. I have tried above solutions but to no avail. This was simply NOT happening yesterday. Only difference is I am working from the office today. I'll retest from home this afternoon, just in case.
My vscode terminal log is this:
[2023-11-16 07:38:04.059] Extension version: 0.81.8
[2023-11-16 07:38:04.059] L10N bundle: undefined
[2023-11-16 07:38:04.071] authorityHierarchy: wsl+Ubuntu
[2023-11-16 07:38:04.071] WSL extension activating for a local WSL instance
[2023-11-16 07:38:04.109] Resolving wsl+Ubuntu, resolveAttempt: 1
[2023-11-16 07:38:04.110] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --status
[2023-11-16 07:38:04.554] WSL feature installed: true (wsl --status)
[2023-11-16 07:38:04.554] NodeExecServer run: C:\WINDOWS\System32\wsl.exe --list --verbose
[2023-11-16 07:38:04.937] 1 distros found
[2023-11-16 07:38:04.938] Starting VS Code Server inside WSL (wsl2)
[2023-11-16 07:38:04.938] Windows build: 22631. Multi distro support: available. WSL path support: enabled
[2023-11-16 07:38:04.938] Scriptless setup: false
[2023-11-16 07:38:05.004] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c [ -f '/tmp/vscode-distro-env.iYFWIK' ] && cat '/tmp/vscode-distro-env.iYFWIK' || echo ''
[2023-11-16 07:38:05.221] WSL daemon log file: 
[2023-11-16 07:38:05.224] Probing if server is already installed: if [ -d ~/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2023-11-16 07:38:05.228] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c if [ -d ~/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2023-11-16 07:38:05.981] Using shell environment from invoking shell: /tmp/vscode-distro-env.iYFWIK
[2023-11-16 07:38:08.310] Probing result: install-found x86_64
[2023-11-16 07:38:08.310] Server install found in WSL
[2023-11-16 07:38:08.313] NodeExecServer run: C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" f1b07bd25dfad64b0167beb15359ae573aecd2cc stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=1644673133-3415860368-742007446-3247370016 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: CreateProcessParseCommon:708: Failed to translate C:\Users\flamadri\AppData\Local\Programs\Microsoft VS Code
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate c:\Users\flamadri\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\system32
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\Wbem
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\System32\OpenSSH\
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Git\cmd
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\PowerShell\7\
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\flamadri\AppData\Local\Microsoft\WindowsApps
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\flamadri\AppData\Local\Programs\oh-my-posh\bin
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\flamadri\AppData\Local\Programs\Microsoft VS Code\bin
[2023-11-16 07:38:08.976] <3>WSL (1214) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\flamadri\Programs\clink.1.5.13.290610
[2023-11-16 07:38:08.976] sh: 1: /scripts/wslServer.sh: not found
[2023-11-16 07:38:09.010] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2023-11-16 07:38:20.118] Download in background is enabled

Looks like a problem with the filesystem manager here.

**Comment by PoProstuWitold** [comment]
> I think the easiest way to fix this is to do go into wsl once (still works for me after wsl --shutdown) then run `sudo /opt/distrod/bin/distrod disable` as mentioned and then switch away from distrod (permanently?) because it's not really needed anymore. Instead use the native systemd support that Windows added for wsl: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#:~:text=release%20page.-,Set%20the%20systemd%20flag%20set%20in%20your%20WSL%20distro%20settings,-You%20will%20need
> 
> This works for me so far, not sure yet if the distrod disablement sticks around after a windows restart.

I think that currently is the only solution

**Comment by PacoCapgemini** [comment]
No distrod in my case, so this does not work for me, I'm afraid.

**Comment by PacoCapgemini** [comment]
I am also including the "code -s" I get when I execute vscode as "code ." in any WSL2 folder:
Version:          Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS Version:       Windows_NT x64 10.0.22631
CPUs:             11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)
Memory (System):  15.69GB (3.22GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --folder-uri=vscode-remote://wsl+Ubuntu/opt/microsoft/powershell/7 --remote=wsl+Ubuntu --crash-reporter-id aa595f95-91a7-4ca0-b841-f074ca530a6f
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  video_decode:                           enabled
                  video_encode:                           enabled
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled

CPU %   Mem MB     PID  Process
    0      112   19144  code main
    0      180    6760  window [1] (7 [WSL: Ubuntu] - Visual Studio Code [Administrator])
    0       30   14460     crashpad-handler
    0       99   15976  extensionHost [1]
    0       41   17784     utility-network-service
    0      145   18780  shared-process
    0      194   19308     gpu-process
    0       76   19636  fileWatcher [1]

Connection to 'wsl+Ubuntu' could not be established

**Comment by httpete** [comment]
My steps to fix this:

1. ) Reboot your computer and get into your wsl one last time.
2.) sudo /opt/distrod/bin/distrod disable


You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.

Add these lines to the /etc/wsl.conf (note you will need to run your editor with sudo privileges, e.g: sudo nano /etc/wsl.conf):

[boot]
systemd=true

Then:
Go into powershell and wsl.exe --shutdown

Restart your wsl in your terminal, seems good now!

**Comment by rabindangol** [comment]
Thanks @httpete, followed the steps you posted, fixed my issue.

**Comment by PacoCapgemini** [comment]
This does not work for me but anyway VSCode is working correctly if I run it from home. This seems to be a problem only at the office, so I will try and solve it internally with my company's IT. Thanks anyway, guys.

**Comment by dancristiancecoi** [comment]
The suggestion from [here](https://github.com/microsoft/WSL/issues/9360#issuecomment-1810569798) works for me. 

Add the following to .wslconfig: 

`[wsl2]
virtio9p=false`

After rebooting the laptop (just wsl --shutdown was not sufficient for me) I can start VS Code (both from the exe or the wsl terminal) & Docker desktop without issues. Don't know what are the repercussions for disabling virtio9p but things seem to work okay for me.

**Comment by std4453** [comment]
Entering WSL and disabling `distrod` works for me.

I got into WSL with `wsl.exe -e bash`, if anybody wants to know.

**Comment by panuhorsmalahti** [comment]
I'm also seeing this. Current workaround is to downgrade to WSL 1.3.17.0.

**Comment by andreas-mennel** [comment]
# UBUNTU 22.04
```
[wsl2] 
# keep existing values
virtio9p=false
```

fixed it for me.

**Comment by Reilkay** [comment]
Thanks to @httpete , problem solved!
