### ISSUE TITLE
expo app

### ISSUE THREAD

**Issue by hmz22** [microsoft/WSL#10765]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I create expo app with wsl and I enabled networkingMode mirrored then show my mirrored ip but when scan qr code with expo app in android dont work and app not run i disable windows firewall and not work when run with browser in android mobile show error Somthing went wrong
![Screenshot 2023-11-16 120816](https://github.com/microsoft/WSL/assets/36853974/76d62f21-cfeb-4f5c-aba0-89757153d76f)

this error in browser android
![Screenshot_2023-11-16-12-07-04-421_com android chrome](https://github.com/microsoft/WSL/assets/36853974/ca56c1e1-c90c-460c-b210-7c4ec016445e)

### Expected Behavior

if the mirrored must like work windows beacuse in windows when creat expo app it's worked

### Actual Behavior

--

**Comment by Jefferson111** [comment]
Try tunnel mode on expo. 
Like: `npx expo start --tunnel`

**Comment by OneBlue** [comment]
Closing since this doesn't look like a WSL issue.

**Comment by hmz22** [comment]
but in your video show run app in wsl and then type ip in mobile browser show app. if in localhost must show like windows so what do exactly mirrored network mode?
