### ISSUE TITLE
Cannot install it on my system. Throws multiple errors "cannot create symbolic link" while unzipping the file. Installer is missing once unzipped.

### ISSUE THREAD

**Issue by Jayse9** [microsoft/WSL#10768]
### Windows Version

Microsoft Windows [Version 10.0.19045.3570]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

unzip the file in a local folder

### Expected Behavior

To access the installer

### Actual Behavior

No installer in the file.
Throws me errors while trying to unzip
![Screenshot (52)](https://github.com/microsoft/WSL/assets/66253905/903ade26-7b6a-4420-8dd8-44ebfbadacd1)
![Screenshot (49)](https://github.com/microsoft/WSL/assets/66253905/74283883-58b9-4903-a141-9de4782237ea)

**Comment by OneBlue** [comment]
What exactly are you trying to unzip ? The recommended way to install is to use `wsl --install`
