### ISSUE TITLE
The specified service does not exist as an installed service. Error code: Wsl/0x80070424  [process exited with code 4294967295 (0xffffffff)]

### ISSUE THREAD

**Issue by omar2535** [microsoft/WSL#10779]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

WSL is now unable to launch following a Sindows update. Attempted to diagnose this issue by following the comments in #10755 (Disable hyper-v, enable virtual machine, reinstall WSL) but still doesn't work.

```sh
C:\Users\omart>wsl.exe
```

### Expected Behavior

WSL to launch

### Actual Behavior

Errored out with this:

```
The specified service does not exist as an installed service.
Error code: Wsl/0x80070424
```

**Comment by bousch** [comment]
The latest windows updates completely broke my wsl. Disabling/re-enabling features did not help. Complete uninstall and reinstall of wsl and distributions does not help. At one point the wsl executable was working again but after wsl --update it was yet again broken and reports:
PS C:\WINDOWS\system32> wsl -l
The specified service does not exist as an installed service.
Error code: Wsl/0x80070424

**Comment by bousch** [comment]
Now wsl works again. What I did was:

- copy the ext4.vhxd file from my distribution to reimport later.
- Uninstall all Distros and WSL
- disable Windows features:
  - Hyper-V
  - Virtual Machine Platform
  - Windows Hypervisor Platform
  - Windows Subsystem for Linux
- Reboot
- wsl --install
- manually update wsl to 2.0.5 (because wsl --update breaks wsl for me)
- wsl --import-in-place ext4.vhxd

Now I have to find a way to block all Windows Updates because this took me 4 hours to get working again.

**Comment by bousch** [comment]
Great stuff, not only did my office Windows Pro laptop had this issue, my personal Windows Home laptop has the exact same issue!

**Comment by bousch** [comment]
Sadly what I did on Windows Pro does not seem work on Windows Home. Only with Administrator priviliges I can start wsl, as my normal user I get: 
PS C:\Users\bousch> wsl -l -v
Element not found.
Error code: Wsl/ERROR_NOT_FOUND

[WslLogs-2023-11-17_23-54-29.zip](https://github.com/microsoft/WSL/files/13398125/WslLogs-2023-11-17_23-54-29.zip)

**Comment by OneBlue** [comment]
@bousch: Based on the output it looks like WSL is in a bad state. Can you try uninstalling WSL, and then re-install it via [the MSI package](https://github.com/microsoft/WSL/releases/tag/2.0.9) ?

**Comment by omar2535** [comment]
@bousch How did you uninstall all your distros? I tried to do using the usual uninstall programs from settings but every time I restart the installation (`wsl --install`), the newly installed wsl still gives the same error

**Comment by bousch** [comment]
@OneBlue Thanks, yes, I have uninstalled/rebooted/reinstalled many times. I will try again today as I was not in the best mood after trying all day yesterday :)
@omar2535 if get the wsl executable to work and "wsl -l" still lists your distro's you can use "wsl --unregister <distro-name>" to uninstall them. But beware this will delete completely delete the distro (including your ext4.vhxd file) so if you still want to keep the data make sure to copy it somewhere so you can import it later.

**Comment by omar2535** [comment]
Yea, I'm not able to get the executable working at all except for `--help`. I have copied the ext4.vhxd file so that's not a concern. I'll try to see if I can use the MSI package after my semi-uninstall

**Comment by bousch** [comment]
I have WSL working now on my Windows Home laptop. I did uninstall wsl and re-installed from MSI but this resulted in the same error as before. I did notice that there were two entries in "Apps & Features"; one of 459 MB which says 2.0.9.0 and a smaller one (8 KB or 8MB) without version but with advanced options. I deleted this one. 
If I remember correctly the wsl command worked after this. I did run "wsl --update --inbox" and used "wsl --install -d Distroname" to reinstall the distro's I had before. Then I ran "wsl --shutdown" and replaced the .vhxd files in %localappdata% with my backups. Now wsl seems to run fine. The WSL entries in my "Apps & Features" list are:
![image](https://github.com/microsoft/WSL/assets/12599972/bd2856e3-1ba1-4a93-931e-08190ac4385b)
![image](https://github.com/microsoft/WSL/assets/12599972/0f9e04de-55a0-41ec-a5e2-0904b91a4e77)

**Comment by omar2535** [comment]
Oddly enough, I have two of these and the one on the bottom errors when trying to uninstall
![image](https://github.com/microsoft/WSL/assets/9442294/fcf68503-6945-4cfe-a955-38fe0dd678e5)
![image](https://github.com/microsoft/WSL/assets/9442294/4d21e309-1ced-464c-b0e1-99752f5f9535)

**Comment by omar2535** [comment]
Ok so I had the exact same thing (with two WSLs showing up), I removed the smaller one and ran the `wsl --install -d Distroname` command. But after that, running any `wsl` commands will fail except for help.

Interestingly, after I removed the smaller WSL entry from Apps & Features, anything I ran (such as `wsl --update --inbox`) would just prompt the help menu

![image](https://github.com/microsoft/WSL/assets/9442294/3bdc6446-70fd-4747-8f11-a51512a46851)

**Comment by bousch** [comment]
I also had this last situation ever every wsl command showed the help. I
think I then executed "wsl --update --inbox" as Administrator.

**Comment by jbgomond** [comment]
Just updated my W10 PC and I now have the same problem. WSL shows version 2.0.9, it does not work in user mode but works only in administrator mode ...

> C:\Users\XXX> wsl
Élément introuvable.
Error code: Wsl/ERROR_NOT_FOUND

> Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070490
Error: 0x80070490 ╔lÚment introuvable.
Press any key to continue...

**Comment by omar2535** [comment]
Ok. I finally fixed WSL. I haven't re-imported my files, but what I had to do was a complete re-installation of WSL. These were the steps I took:

1. Go to features and turn off the following: Hyper-V, Windows Subsystem for Linux, and Virtual Machine Platform
2. Go to Windows _Add or remove programs_ and remove everything related to WSL (one of them was a very big WSL one that kept erroring when I tried to remove it, I ignored this)
3. Further make sure WSL is uninstalled using the [troubleshooter](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d)
4. Reboot
5. Re-enable features: Windows Subsystem for Linux and Virtual Machine Platform
6. Reboot
7. Open the command prompt as admin, run `wsl -l` and make sure it runs without the "service does not exist" error
![image](https://github.com/microsoft/WSL/assets/9442294/5e1348a9-965f-4385-8fbf-fb41c0af39fb)
8. Install WSL package directly from releases: [2.0.8](https://github.com/microsoft/WSL/releases/tag/2.0.8)
9. Install WSL
![image](https://github.com/microsoft/WSL/assets/9442294/9e0a5407-4bf7-4c12-9d6b-dde1c884ebac)

and now it works. I also tried using #10764 as previously mentioned, but I wasn't able to find that registry entry so skipped the steps. Additionally, I haven't imported my `ext4.vhxd` file yet, but will soon. Thanks @bousch :)

**Comment by omar2535** [comment]
Closing as solved for now.

**Comment by pahar0** [comment]
Launching WSL from a terminal with administrator privileges seems like a temporal workaround. Can somebody else confirm?
https://github.com/microsoft/WSL/issues/10788#issuecomment-1817734924

**Comment by bousch** [comment]
> Ok. I finally fixed WSL. I haven't re-imported my files, but what I had to do was a complete re-installation of WSL. These were the steps I took:
> 
> 1. Go to features and turn off the following: Hyper-V, Windows Subsystem for Linux, and Virtual Machine Platform
> 2. Go to Windows _Add or remove programs_ and remove everything related to WSL (one of them was a very big WSL one that kept erroring when I tried to remove it, I ignored this)
> 3. Further make sure WSL is uninstalled using the [troubleshooter](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d)
> 4. Reboot
> 5. Re-enable features: Windows Subsystem for Linux and Virtual Machine Platform
> 6. Reboot
> 7. Open the command prompt as admin, run `wsl -l` and make sure it runs without the "service does not exist" error
>    ![image](https://user-images.githubusercontent.com/9442294/284034937-5e1348a9-965f-4385-8fbf-fb41c0af39fb.png)
> 8. Install WSL package directly from releases: [2.0.8](https://github.com/microsoft/WSL/releases/tag/2.0.8)
> 9. Install WSL distro
>    ![image](https://user-images.githubusercontent.com/9442294/284034987-9e0a5407-4bf7-4c12-9d6b-dde1c884ebac.png)
> 
> and now it works. I also tried using #10764 as previously mentioned, but I wasn't able to find that registry entry so skipped the steps. (Also note that I'm too afraid to update to 2.0.9 in-case anything bricks 😬) Additionally, I haven't imported my `ext4.vhxd` file yet, but will soon. Thanks @bousch :)

Nice! BTW afaik you do not have to import the ext4 file. You can just install the same distribution, do wsl --shutdown and overwrite the file in localappdata with your ext4 backup file.

**Comment by bousch** [comment]
> Launching WSL from a terminal with administrator privileges seems like a temporal workaround. Can somebody else confirm? [#10788 (comment)](https://github.com/microsoft/WSL/issues/10788#issuecomment-1817734924)

yes, in the end you should be able to run wsl as your regular user. Try to follow the steps Omar2535 described. Something similar worked for me on Windows 10 Pro. On Windows Home the same steps did not work for me, than maybe follow the steps I described [above](https://github.com/microsoft/WSL/issues/10779#issuecomment-1817535417). I also did not mess with the windows registry.
