### ISSUE TITLE
VHDX cannot be detached with full path

### ISSUE THREAD

**Issue by dantmnf** [microsoft/WSL#10771]
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133

### Distro Version

N/A

### Repro Steps

```console
C:\>wsl --mount --vhd --bare E:\test\a.vhdx
The operation completed successfully.

C:\>wsl --unmount E:\test\a.vhdx
The system cannot find the file specified.
Error code: Wsl/Service/DetachDisk/ERROR_FILE_NOT_FOUND

C:\>cd /d E:\test

E:\test>wsl --unmount a.vhdx
The operation completed successfully.
```

### Expected Behavior

The VHDX can be detached with either full path or relative path.

### Actual Behavior

VHDX cannot be detached with full path.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.12.

**Comment by conioh** [comment]
A workaround in case somebody can't get the update is to use `\\?\path`, e.g. `wsl.exe --unmount \\?\E:\test\a.vhdx`. For some reason this works.
