### ISSUE TITLE
Can't use WSL2 after last update

### ISSUE THREAD

**Issue by EmpereurWaza** [microsoft/WSL#10788]
### Windows Version

Microsoft Windows [version 10.0.19045.3693]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04.2

### Repro Steps

wsl --update from an elevated terminal

### Expected Behavior

Working as intended

### Actual Behavior

I can't use WSL anymore
![image](https://github.com/microsoft/WSL/assets/21972359/b1e92377-774e-442c-945f-e8836adc2a6e)
And when I try to open Ubuntu I have this error
![image](https://github.com/microsoft/WSL/assets/21972359/5dabde2e-6585-440f-8061-7a38660ebf70)

**Comment by EmpereurWaza** [comment]
It got fixed with this
https://github.com/microsoft/WSL/issues/10764#issuecomment-1815485695

**Comment by EmpereurWaza** [comment]
I found a temporary fix here : https://github.com/microsoft/WSL/issues/10764#issuecomment-1815485695
And the same issue here : 
https://github.com/microsoft/WSL/issues/10764

**Comment by cnjawi** [comment]
Go to the "Turn Windows features on or off" and check whether "Virtual Machine Platform" is enabled. It seemed that the latest Windows update has turned off this option. I faced similar issue and solved it this way.

**Comment by pahar0** [comment]
Accessing to WSL through a PowerShell with administrator privileges seems to fix the issue.
I used `wsl.exe` and not `wsl`, once you run WSL this way seems that you can access WSL again normally.

**Comment by EmpereurWaza** [comment]
> Accessing to WSL through a PowerShell with administrator privileges seems to fix the issue. I used `wsl.exe` and not `wsl`, once you run WSL this way seems that you can access WSL again normally.
> 
> It worked for me, can somebody else confirm?
> 
> EDIT: I can only access to WSL through a terminal with administrator privileges.

Same with me but since update GUI is laggy

**Comment by EmpereurWaza** [comment]
> Go to the "Turn Windows features on or off" and check whether "Virtual Machine Platform" is enabled. It seemed that the latest Windows update has turned off this option. I faced similar issue and solved it this way.

I launch as an admin It works

**Comment by baiciluigi** [comment]
Same issue, can only run wsl with admin rights, everything else fails. Have to manually run it on admin.
Docker Desktop fails, but when launched with admin rights, succeeds aswell.
For now I can work like this but it needs to be fixed..

**Comment by OneBlue** [comment]
Thanks everyone for reporting this. If you hit the "element not found / ERROR_NOT_FOUND" issue, please follow [this post](https://github.com/microsoft/WSL/issues/10782#issuecomment-1819864778) to collect logs to help us root cause it.

**Comment by waliaryan** [comment]
The application cannot be started because it is currently updating
