### ISSUE TITLE
error parameter in "WSL/networking.md" from Resolve issues Nov 23 #1848

### ISSUE THREAD

**Issue by zhaoqiu-china** [microsoft/WSL#10797]
### Windows Version

Microsoft Windows [版本 10.0.22621.2506]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. open terminal
```
Set-NetFirewallHyperVVMSetting -Name ‘{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}’ -DefaultInboundConnection Allow
```

I think that "-DefaultInboundConnection" may be "-DefaultInboundAction"?

### Expected Behavior

no error

### Actual Behavior

Set-NetFirewallHyperVVMSetting: A parameter cannot be found that matches parameter name 'DefaultInboundConnection'.

**Comment by benhillis** [comment]
Could you submit a PR please?

**Comment by ChnMig** [comment]
I had the same problem because I wanted to set wsl2 's network connection to mirror mode as documented
https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking

**Comment by zhaoqiu-china** [comment]
@benhillis 

> Could you submit a PR please?

[my PR 1858](https://github.com/MicrosoftDocs/WSL/pull/1858)
