### ISSUE TITLE
WSL cannot use proxy with networkingMode=mirrored

### ISSUE THREAD

**Issue by mingo99** [microsoft/WSL#10794]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu20.04

### Repro Steps

- Set `.wslconfig`：
```
[experimental]
autoMemoryReclaim=gradual
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
``` 
- `wsl --shutdown` to stop WSL
- Set proxy port to `7890` in clash for windows and open system proxy
![image](https://github.com/microsoft/WSL/assets/71544752/6addb0b8-5949-46b5-9982-27eaadfc2830)
- Restart WSL

### Expected Behavior

Both WSL and Windows can successfully access `google.com`(banned in my place) by curl

### Actual Behavior

1. Execute curl in Wondows(Powershell)
   - `curl google.com`  **succeeded**
![image](https://github.com/microsoft/WSL/assets/71544752/1e80453b-8363-4269-9d1c-48ca492818da)
2. Excute curl in WSl
  - `curl google.com` **failed**
![image](https://github.com/microsoft/WSL/assets/71544752/4744a9ce-1d9e-4493-8b7b-4bbb0395c373)

### Diagnostic Logs

- My log [https://github.com/mingo99/wsl2proxy/blob/main/WslNetworkingLogs-2023-11-19_17-03-14.zip](https://github.com/mingo99/wsl2proxy/blob/main/WslNetworkingLogs-2023-11-19_17-03-14.zip)
- Generate by [https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1](https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1)

**Comment by zhaoqiu-china** [comment]
try firewall=false?

**Comment by mingo99** [comment]
> try firewall=false?
I've tried, but it still doesn't work

**Comment by zhaoqiu-china** [comment]
BTW, experimental feature has moved to wsl2.
![image](https://github.com/microsoft/WSL/assets/51221150/2a5f9a6d-72cc-4656-91aa-25af5b89f4da)

**Comment by mingo99** [comment]
yeah，now my .wslconfig is 
```
[wsl2]
kernel=C:\\WINDOWS\\System32\\lxss\\tools\\5.15.90.1-kernel-usb
networkingMode=mirrored
dnsTunneling=true
firewall=false
autoProxy=true

[experimental]
sparseVhd=true
autoMemoryReclaim=gradual
```

**Comment by mingo99** [comment]
Additionally, access the external network is normal, like `ping` github.com is ok

**Comment by PhyX-Meow** [comment]
It may not help but, I tried `firewall=false` then everything works fine. Did you restart wsl by `wsl --shutdown`?

**Comment by mingo99** [comment]
yeah,even reboot computer

**Comment by mingo99** [comment]
I upgraded from Ubuntu 20.04 to Ubuntu 22.04, and the issue got resolved, although I don't know how it was fixed. The reason I had this idea is that my other computer, which has Ubuntu 22.04 installed, could successfully use the proxy.

**Comment by zhaoqiu-china** [comment]
@mingo99 

> I upgraded from Ubuntu 20.04 to Ubuntu 22.04, and the issue got resolved, although I don't know how it was fixed. The reason I had this idea is that my other computer, which has Ubuntu 22.04 installed, could successfully use the proxy.

whether you set the HTTP_PROXY environment variable?

**Comment by mingo99** [comment]
No, it will set itself.

**Comment by KnineF** [comment]
我也遇到了这个问题。请问你解决了吗

**Comment by mingo99** [comment]
升级到 22.04 就没问题了🤣

**Comment by HawtinZeng** [comment]
> `ping` github.com

Me too, but the tip about the local proxy is not mirrored into WSL still appears.

**Comment by HawtinZeng** [comment]
> Additionally, access the external network is normal, like `ping` github.com is ok

Me too, but the tip about the local proxy is not mirrored into WSL still appears.

**Comment by SuAutumn** [comment]
I changed the inbound rules of the Clash for windows in firewall, that does work in Ubuntu 20.

**Comment by Minphie** [comment]
> I changed the inbound rules of the Clash for windows in firewall, that does work in Ubuntu 20.
@SuAutumn 
怎么改的？我的都勾选了还是不行。
![image](https://github.com/microsoft/WSL/assets/16850655/875142fe-bf39-43aa-8cb4-073bc608bf7c)

**Comment by SuAutumn** [comment]
> > I changed the inbound rules of the Clash for windows in firewall, that does work in Ubuntu 20.
> > @SuAutumn
> > 怎么改的？我的都勾选了还是不行。
> > ![image](https://private-user-images.githubusercontent.com/16850655/311659131-875142fe-bf39-43aa-8cb4-073bc608bf7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTM4ODUsIm5iZiI6MTcxMDI1MzU4NSwicGF0aCI6Ii8xNjg1MDY1NS8zMTE2NTkxMzEtODc1MTQyZmUtYmYzOS00M2FhLThjYjQtMDczYmM2MDhiZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MTRiYjc2YjcwZDQwNDhjNWEyYjMwODE0MDNiMmJlNTcyNWFmYjNhNzAwNzNmMDFjMzMzMDM4NDc0NmJlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2CwY7ucyZXRouFQGF1sAzOCT3NfaQKrsQMMuCtUGRH4)



> > I changed the inbound rules of the Clash for windows in firewall, that does work in Ubuntu 20.
> > @SuAutumn
> > 怎么改的？我的都勾选了还是不行。
> > ![image](https://private-user-images.githubusercontent.com/16850655/311659131-875142fe-bf39-43aa-8cb4-073bc608bf7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTQwNzMsIm5iZiI6MTcxMDI1Mzc3MywicGF0aCI6Ii8xNjg1MDY1NS8zMTE2NTkxMzEtODc1MTQyZmUtYmYzOS00M2FhLThjYjQtMDczYmM2MDhiZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE0MjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDFkMDcxNDdjMWY0MmVhM2JhYjAyMzFiZTczMjdkNGYzNjBhNGRjODBiMTM3ZjQ4MWY0ZjIwMzg1MTllM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IFPuPguUcGfBEos_HC10d5DpcroA1saG3bPERm0nfJ4)

You can `curl http://<host_ip>:7890` in wsl terminal, get a 4xx status code means that you can successfully visit clash proxy in wsl. otherwise Just Shutdown firewall, and try again.

**Comment by amorZhu** [comment]
Try deleting the Linux distribution and reinstalling it.
`wsl --unregister <DistributionName>`
`wsl --install`
