### ISSUE TITLE
Drives other than C: are not mounted in /mnt

### ISSUE THREAD

**Issue by streamholder** [Microsoft/WSL#1079]
Drives other than the C: drives are not mounted under /mnt.
I have two more fixed drives, D: and V:, and they are not being mounted. They are both exFAT drives.

I'm on Windows 14393.105.

**Comment by rodrymbo** [comment]
Sounds like #891, if the system thinks the drives are removable.

If they are not removable, but mounted after the first long-running bash.exe starts, the WSL environment won't see them (e.g mounting a drive with VeraCrypt). The workaround is to mount the drives before using bash.exe

**Comment by benhillis** [comment]
Currently only fixed NTFS drives show up under /mnt/.

**Comment by iz0eyj** [comment]
@streamholder  This is my /mnt:
federico@BESTIA:/mnt$ ll
totale 24
drwxr-xr-x 2 root root 0 set 14 19:11 ./
drwxrwxrwx 2 root root 0 set  2 14:34 ../
drwxrwxrwx 2 root root 0 set 14 19:08 c/
drwxrwxrwx 2 root root 0 set 14 01:29 d/
drwxrwxrwx 2 root root 0 set 13 22:04 x/
federico@BESTIA:/mnt$

All the drive is NTFS, X is an external unit (I don't know what program mounts it).
I have also many dir mapped on the Win side (symlink).

**Comment by streamholder** [comment]
@benhillis I understand that. My D: and V: drives are fixed.

**Comment by benhillis** [comment]
You also said they are exFAT (not NtFS) correct? That's why they aren't showing up.

**Comment by streamholder** [comment]
@benhillis That is correct, and that also doesn't make the removable drives by any classification. Windows doesn't look at the filesystem type to decide whether a drive is fixed or removable (rightly so). The fact that Bash On Windows (or WSL, whichever is at fault) does is a bug.
You may want to undo the closing. This is clearly not a duplicate of #891.

**Comment by benhillis** [comment]
Sorry I inadvertently closed this issue (clicked wrong button).

Let me try to clarify.  In order for a drive to show up under /mnt/ it must meet the following criteria:

1. The drive must be a fixed drive (your drives satisfy this requirement)
2. The drive must be formatted to NTFS (your drives to _not_ satisfy this requirement).

**Comment by iz0eyj** [comment]
@benhillis "1. The drive must be a fixed drive" **->** my "x" drive is an external, USB (2.0) drive and is mounted under /mnt.
I don't know what program mounts it, but it is impossible to umount it both from WSL and Win.
To umount I need to shutdown the system then turn it off. :)

**Comment by streamholder** [comment]
@benhillis I did not know about the second requirement. I tried to make a symlink and a junction somewhere on the C drive to the ExFAT drives, but either way it just doesn't show up in Bash.

**Comment by iz0eyj** [comment]
@streamholder you need to format using NTFS.

**Comment by streamholder** [comment]
@iz0eyj Yeah - that would be the obvious solution. However, that is not a possibility for me. Those hard disk contain data that has to be easily accessible from other platforms, and ExFAT is the only out-of-the-box solution to do that.

**Comment by iz0eyj** [comment]
@streamholder it would be possible for you to create a little NTFS partition for data exchange between WSL and Win?

**Comment by streamholder** [comment]
@iz0eyj Definitely, however that would not be an ideal solution at all, and furthermore it kind of defies the whole usefulness of WSL. Rebooting into Linux whenever I need Bash would be less of a hassle than manually copying data I need to use to a NTFS partition.

**Comment by fpqc** [comment]
@streamholder All platforms (I think except for *BSD) support NTFS read/write now.  On Mac, you can install a FUSE module or install the third-party ntfs-3g driver, and ntfs-3g on Linux.

**Comment by MaxPleaner** [comment]
Would appreciate some advice on how to mount another drive in Bash.

I have a dualbooted Ubuntu and Windows and I want to get Windows Bash to access the Linux partition.

I'm using the Ext2Fsd program in Windows to mount the Linux partition at D:// but I don't know how to make it available to Bash. I tried making a link but it is the `.lnk` format and I'm not sure what to do with that in Bash.

**Comment by aseering** [comment]
@MaxPleaner -- WSL unfortunately only supports NTFS partitions right now.

**Comment by frohro** [comment]
Is there anything new on this thread?  I'm investigating how we might be able to use WSL on our campus lab machines which use [Deep Freeze](http://www.faronics.com/products/deep-freeze/enterprise/).  I need to put the / directory somewhere other that C:.  

I note that you can now mount network and other drives on /mnt.  See [this](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) for example:  

Is there anything new on this topic?

**Comment by alkis** [comment]
Is this being worked on?

**Comment by fpqc** [comment]
@alkis kinda.  Right now each filesystem driver for win32 seems like it might needs to have its own compatibility layer registered generically somehow through drvfs or potentially could make use of an unstable and undocumented kernel-side API to provide functionality to the Linux subsystem.  Right now Microsoft's solution allows mounting of most of the filesystems with Windows built-in Win32 support (CDFS, Samba network shares, NTFS, and FAT32) with sort of stripped-down functionality using Microsoft's `drvfs`.  This does not extend to third-party filesystem drivers for now (unless they are a special kind of tricky filesystem that masquerades as NTFS (the Windows BTRFS prerelease driver plays this game).  

There are a couple of other topics about this (requests to expose the kernel-side API for driver makers and to add things like the drvfs driver sources to the KMDF) as well as requests for direct support for things like FUSE (possibly implemented on top of the gvflt filter driver from GVFS). A lot of progress was made only a few builds ago that added all of the FAT32, SAMBA, and CDFS stuff.

Mostly speculation, but it seems like they're making moves on these things.

**Comment by alienmind** [comment]
Under WSL, add to /etc/fstab
D: /mnt/d drvfs defaults 0 0

then back to bash:

1) Create the mount point
   sudo mkdir /mnt/d

2) Mount it
   sudo mount -a

voila! /mnt/d now points to d:

It works even with non fixed drives

**Comment by therealkenc** [comment]
Yeah given that the OP predates the [WSL filesystem improvements](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) introduced in 16176 I think we can call this closed. It won't mount exFAT fixed drives automatically via `init`, but that kind of falls under the umbrella startup task topic per #2636 #511 #994. Previously you couldn't mount exFAT drives period.

**Comment by xNevo** [comment]
I recently ran into this error as well. What helped me solving this problem was restarting the `LxssManager` service
```
net stop LxssManager && net start LxssManager
```

**Comment by fpqc** [comment]
wsl supports loading an fstab, so make one

**Comment by renatovassao** [comment]
Windows and WSL2 now supports mouting Linux filesystems

https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/

**Comment by p-racoon2** [comment]
I created the partition after installing WSL. This helped me might help others as well:- 
To Mount :- 
```
$ sudo mkdir /mnt/d
$ sudo mount -t drvfs D: /mnt/d
```
To Unmount :-
```
$ sudo unmount /mnt/d
```

**Comment by jknair0** [comment]
> 
> 
> I recently ran into this error as well. What helped me solving this problem was restarting the `LxssManager` service
> 
> ```
> net stop LxssManager && net start LxssManager
> ```

this worked for me. Please mention this has to be run in powershell

**Comment by therealkenc** [comment]
If folks are experiencing a problem with `D:\` not being automounted _on WSL2 on 20H2 (or Insiders)_, contrast whatever was the long resolved issue from 2016, please feel free to spin up a new issue following the submission template. There should not be any requirement for a start/stop or `mkdir` raindance to get `/mnt/d`. Be sure to include as many details about your `D:` as possible.

**Comment by caleb15** [comment]
@therealkenc I just ran into the same issue with WSL2 and other people have too - see https://github.com/microsoft/WSL/issues/6286

**Comment by gbatra222** [comment]
> I created the partition after installing WSL. This helped me might help others as well:- To Mount :-
> 
> ```
> $ sudo mkdir /mnt/d
> $ sudo mount -t drvfs D: /mnt/d
> ```
> 
> To Unmount :-
> 
> ```
> $ sudo unmount /mnt/d
> ```

When do we use unmount? when we want to unplug the external ssd?

**Comment by tfha** [comment]
It should be `sudo umount /mnt/d` right? Ie. not `unmount`. I get error on that.
