### ISSUE TITLE
Irrecoverable failure when trying to install

### ISSUE THREAD

**Issue by Big-bros** [microsoft/WSL#10796]
### Windows Version

Microsoft Windows [version 10.0.19045.2965]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I had an rather old version of windows 10 installed. I installed WSL manually (following this : https://learn.microsoft.com/fr-fr/windows/wsl/install-manual) on it and it seemed to work ok. I had my linux distro working.
Then I tried to install docker but the windows version was too old.
So i updated the version as much as i could, reinstalled Docker client but it didn't launch.
I tried to execute wls to see but then I had a error "Défaillance irrémédiable" (which can be translated by "unrecoverable failure")
Nothing more.
I tried wsl --update : same error
I completely uninstall wsl, following these steps : 
https://superuser.com/questions/1317883/completely-uninstall-the-subsystem-for-linux-on-win10
tried wsl --install and this is what i have each time :

> PS C:\WINDOWS\system32> wsl --install
> Installation en cours : Sous-système Windows pour Linux
> Sous-système Windows pour Linux a été installé.
> Installation en cours : Sous-système Windows pour Linux
> Défaillance irrémédiable

The error message doesn't give many clues...

### Expected Behavior

I'd like to install wsl

### Actual Behavior

PS C:\WINDOWS\system32> strace -ff wsl --install
    strace : Le terme «strace» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
    exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
    et réessayez.
    Au caractère Ligne:1 : 1
    + strace -ff wsl --install
    + ~~~~~~
        + CategoryInfo          : ObjectNotFound: (strace:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Big-bros** [comment]
Sorry, i had a very busy week...
And today, when i try wsl --install, I have

        PS C:\Users\xxxx> wsl --install
        Copyright (c) Microsoft Corporation. Tous droits réservés.

        utilisation : WSL. exe [Argument] [Options...] [CommandLine]

        arguments pour l’exécution des fichiers binaires Linux :

         si aucune ligne de commande n’est fournie, WSL. exe démarre l’interpréteur de commandes par défaut.

        --exec,-e <CommandLine>
         exécutez la commande spécifiée sans utiliser le shell Linux par défaut.
         [...]

So I can't post my logs. I have to understand why wsl --install doesn't work.

**Comment by Big-bros** [comment]
[WslLogs-2023-11-27_08-33-51.zip](https://github.com/microsoft/WSL/files/13471108/WslLogs-2023-11-27_08-33-51.zip)

When I execute wsl --update, i have the error mentioned above... So here are the logs.

**Comment by OneBlue** [comment]
Thank @Big-bros. Can you try to run `wsl.exe --update --web-download` ? This might solve your issue.

**Comment by Big-bros** [comment]
Thank you. I made a good step.
I ran 

     wsl.exe --update --web-download

It seemed to work.
Then :

     PS C:\WINDOWS\system32> wsl

Le Sous-système Windows pour Linux n’a aucune distribution installée.
So i did : 

     PS C:\WINDOWS\system32> wsl --install --web-download

It installed ubuntu and thats ok
Now, when i'm admin, i can run wsl :
 
     PS C:\WINDOWS\system32> wsl --version
     Version WSL : 2.0.9.0
     Version du noyau : 5.15.133.1-1
     Version WSLg : 1.0.59
     Version MSRDC : 1.2.4677
     Version direct3D : 1.611.1-81528511
     Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
     Version de Windows : 10.0.19045.3693

But when i try to use it in a non admin account, I have another error : 

    PS C:\Users\xxxx> wsl
    WSL 2 nécessite une mise à jour de son composant noyau. Pour plus d’informations, visitez https://aka.ms/wsl2kernel

I tryed : 

     PS C:\Users\xxxx> wsl --update
     Installation en cours : Sous-système Windows pour Linux
     Le package spécifié est déjà installé. La réinstallation du package a été bloquée. Pour plus d’informations, consultez le journal des événements AppXDeployment-Server.

I didn't see anything in the logs (but i'm not very familiar with them)
Do I have to be admin to use wsl ?
