### ISSUE TITLE
Exit code -11 when launching Rviz

### ISSUE THREAD

**Issue by ShroyerL** [microsoft/WSL#10790]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04.6

### Repro Steps

Follow this page:
https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html#install-ros-and-catkin

Followed by this command to launch the software with which I am having a segmentation fault:
roslaunch panda_moveit_config demo.launch rviz_tutorial:=true

### Expected Behavior

A window like this should open:
![image](https://github.com/microsoft/WSL/assets/146552876/e8024a6e-0cbb-454e-a490-e60a84fcc692)

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/146552876/f09061b0-5efb-48d6-bc87-09a0c55ae140)

**Comment by ShroyerL** [comment]
[WslLogs-2023-11-22_08-31-30.zip](https://github.com/microsoft/WSL/files/13440104/WslLogs-2023-11-22_08-31-30.zip)

**Comment by OneBlue** [comment]
@ShroyerL: I'm not seeing the .etl log file in the zip you shared. Can you try again and make sure that the .etl file is collected ? 
/logs

**Comment by ShroyerL** [comment]
There is no .etl file that gets saved. I just tried it again.

**Comment by ShroyerL** [comment]
I don't think I was doing it right the first time as I did not "push any key to save" in the powershell window. When I do that though and get a confirmation message, there is still no .etl file saved.
[WslLogs-2023-11-23_07-44-57.zip](https://github.com/microsoft/WSL/files/13450002/WslLogs-2023-11-23_07-44-57.zip)
