### ISSUE TITLE
`ping` breaks when using `experimental.networkingMode=mirrored` and a VPN

### ISSUE THREAD

**Issue by aentwist** [microsoft/WSL#10805]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

WSL version: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version (`uname -a`)

Linux DESKTOP-VSMCCUF 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

### Distro Version (`cat /etc/os-release`)

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

### Other Software

NordVPN [wireguard]

### Repro Steps

1. enable `networkingMode=mirrored`
2. connect to VPN
3. `ping linux.org`

### Expected Behavior

0% packet loss

### Actual Behavior

100% packet loss

### Diagnostic Logs

[WslNetworkingLogs-2023-11-21_15-28-40.zip](https://github.com/microsoft/WSL/files/13430692/WslNetworkingLogs-2023-11-21_15-28-40.zip)

**Comment by aentwist** [comment]
| `networkingMode=mirrored` | VPN | `ping` |
|-|-|-|
| yes | yes | no |
| no | yes | IPv4 only |
| yes | no | yes |

Note that other connectivity works - for example `curl google.com` and `wget https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md`. It seems to just be `ping`!

**Comment by aentwist** [comment]
###### See Also

- https://github.com/microsoft/WSL/issues/5068
- https://github.com/microsoft/WSL/issues/4518
- https://github.com/microsoft/WSL/issues/5109

**Comment by PhyX-Meow** [comment]
Same here, I can't connect to proxy client in wsl side.
```
❯ wget https://images.dmzj.com/w/我又做相同的梦了/第08话/0222\ 副本.jpg
--2023-11-22 14:13:05--  https://images.dmzj.com/w/%E6%88%91%E5%8F%88%E5%81%9A%E7%9B%B8%E5%90%8C%E7%9A%84%E6%A2%A6%E4%BA%86/%E7%AC%AC08%E8%AF%9D/0222%20%E5%89%AF%E6%9C%AC.jpg
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8128... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8128...
**get stuck here**
```

**Comment by aentwist** [comment]
NordVPN does not appear to support IPv6 and `ping google.com` defaults to IPv6. Being more explicit and using `ping -4` works as expected.
