### ISSUE TITLE
autoProxy doesn't work with proxy requiring Kerberos / NTLM authentication

### ISSUE THREAD

**Issue by AndreasAckermannTSystems** [microsoft/WSL#10804]
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Corporate proxy requiring Kerberos / NTLM authentication

### Repro Steps

1. Be inside a corporate network environment with a proxy that requires Kerberos / NTLM Authentication
2. Configure WSL with the following `.wslconfig`:
```
[wsl2]

networkingMode = mirrored
firewall = true
autoProxy = true
```
3. Run `apt-get update` or `curl` for any webpage

### Expected Behavior

Proxy is configured and authenticated with automatically, `apt-get update` and `curl` work out-of-the-box.

### Actual Behavior

`apt-get update` gives me errors like:

```
Err:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
  407  authenticationrequired [IP: 10.XXX.XXX.XXX 8080]
```

`curl`ing for any webpage, I receive a reply from the proxy containing the following headers and a message in the HTML page that I am not authenticated via Kerberos / NTLM:
```
< Proxy-Connection: Keep-Alive
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM
```

**Comment by nvtienanh** [comment]
Me too

**Comment by oli-ver** [comment]
Does anyone know if this was solved in the meantime? As far as I know the proxy support does only set the variables but is missing support to use credentials

**Comment by raypappa** [comment]
Only way I've found around this is to use something like cntlm or alpaca to provide a http proxy  that is authenticated. Possibly this too [px](https://github.com/genotrance/px), which would run in windows and you could just always point at that proxy.
