### ISSUE TITLE
WSL Cannot undertand linux host with mirrored mode and custom domain name

### ISSUE THREAD

**Issue by Dokman** [microsoft/WSL#10813]
### Windows Version

Microsoft Windows [Versión 10.0.22631.2715]

### WSL Version

2.0.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop: 4.25.2

### Repro Steps

Use mirrored in networking, set hosts file in windows to point your lAN ip 192.168.1.x hostname.name

### Expected Behavior

Enter into the website

### Actual Behavior

Refuses to connect but outside network is working

**Comment by Dokman** [comment]
After a new fresh install with Ubuntu 22.0.4 it's the same

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by CatalinFetoiu** [comment]
@Dokman, can you please try setting dnsTunneling=true, restart WSL and retry your scenario?

In mirrored mode, in order for Windows DNS policies (such as the Windows hosts file) to be applied to WSL DNS traffic, dnsTunneling must be enabled

thanks

**Comment by Dokman** [comment]
it doesn't work too. sorry for being inactive too long, i was having troubles i tried with dnsTunneling=true but it doesn't work too

**Comment by Dokman** [comment]
i'm trying to access to my nginx that i've made but it doesn't work i'll upload the zip

[WslLogs-2024-04-03_19-34-49.zip](https://github.com/microsoft/WSL/files/14856310/WslLogs-2024-04-03_19-34-49.zip)

**Comment by CatalinFetoiu** [comment]
@Dokman please use the networking script (https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1).

It looks like you used the regular https://github.com/microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1

thanks

**Comment by Dokman** [comment]
> @Dokman please use the networking script (https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1).
> 
> It looks like you used the regular https://github.com/microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1
> 
> can you please also share the name you are trying to resolve? from your description, I see "hostname.name"
> 
> thanks

I was trying to resolve localhost and 192.168.1.130 if I can't connect to the IP I cannot connect to the nginx hahahah

**Comment by CatalinFetoiu** [comment]
thanks. a few follow up questions to better understand your scenario

how are you configuring the 192.168.1.130 IP? is it an IP assigned to Windows?
are you connecting to 192.168.1.130 from inside WSL or from Windows?
how are you using nginx?
are you adding configurations to the Windows hosts file? from your description it sounds like that's the case

**Comment by CatalinFetoiu** [comment]
are you connecting from Windows to a Linux server listening on 192.168.1.130? or the opposite way (connecting from Linux to a Windows server listening on 192.168.1.130)? what is the port you are connecting to?

**Comment by Dokman** [comment]
> [<img alt="@Dokman" width="40" height="40" src="https://avatars.githubusercontent.com/u/2290904?s=80&amp;v=4">](/Dokman)
> 
> 
> #### Add a comment
> Comment
> Write
> Preview
> 
> 
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 
> Paste, drop, or click to add files
>  Close issue
> Comment
> Remember, contributions to this repository should follow its [contributing guidelines](/microsoft/WSL/blob/b848170b8770d3f3092890ec1423532c18215ed0/CONTRIBUTING.md), [security policy](/microsoft/WSL/blob/b848170b8770d3f3092890ec1423532c18215ed0/SECURITY.md), and [code of conduct](/microsoft/WSL/blob/b848170b8770d3f3092890ec1423532c18215ed0/CODE_OF_CONDUCT.md).
> Assignees
> No one assigned
> Labels
> [ network ](/microsoft/WSL/labels/network)
> Projects
> None yet
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> Notifications
> Customize
> 
> Unsubscribe
> You’re receiving notifications because you were mentioned.
> 
> 4 participants
> [ <img alt="@Dokman" width="26" height="26" src="https://avatars.githubusercontent.com/u/2290904?s=52&amp;v=4"> ](/Dokman)

i'm trying to connect my windows to the linux wsl machine

**Comment by CatalinFetoiu** [comment]
thanks. from the Linux tcpdump output in the logs you shared, I see SYN packets sent to 192.168.1.130, port 80 reaching Linux, but I don't see a reply from the server listening on 192.168.1.130, port 80

do you have logs from your nginx server (I assume nginx is the server listening on 192.168.1.130, port 80), where you can check if nginx received the connection request?

**Comment by Dokman** [comment]
[WslNetworkingLogs-2024-04-03_23-14-02.zip](https://github.com/microsoft/WSL/files/14858625/WslNetworkingLogs-2024-04-03_23-14-02.zip)

**Comment by Dokman** [comment]
After adding the firewall Rules works outside my PC but in localhost mode it doesn't work so i can't work in my pc vieweing anything

**Comment by CatalinFetoiu** [comment]
thanks for your quick responses and patience for this issue

from the latest logs you shared, I see the same case of SYN packets being sent to 192.168.1.130, port 80 reaching Linux, then there is no reply from the server listening on 192.168.1.130, port 80

can you please share the steps you use to install and start the nginx or apache2 server? I can try to reproduce this on my setup.

**Comment by Dokman** [comment]
I'm using a default config, so i cannot understand how it doesn't connect
[default.zip](https://github.com/microsoft/WSL/files/14942410/default.zip)

**Comment by CatalinFetoiu** [comment]
thanks. I tried installing nginx (looking at the /etc/nginx/ folder, nginx has the same default config as you shared) - unfortunately I was not able to repro the issue

a few things to try:
1) we have seen compat issues with localhost communication between Windows and Linux not working when the Linux "network manager" service is running (similar issue - https://github.com/microsoft/WSL/issues/10632)

Can you run "systemctl status network-manager.service" and if it shows the service as running, try disabling it using "systemctl disable network-manager.service", then retry your scenario.

2) we have seen issues when a Linux application will listen on IPv6, but localhost communication between Windows and Linux is not supported for IPv6, it's only supported for IPv4 at the moment.

Can you run "netstat -tlnp" and verify the output is similar to the one below, showing a listener on port 80 on IPv4 and one listener on IPv6

netstat -tlnp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.255.255.254:53       0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      -

**Comment by Dokman** [comment]
So you will tell me

![image](https://github.com/microsoft/WSL/assets/2290904/ec325561-43a2-4688-922b-e9760e2f6ad8)

![image](https://github.com/microsoft/WSL/assets/2290904/1445b473-790a-4ea1-8c24-3bcd5bfbb09c)

**Comment by Dokman** [comment]
![image](https://github.com/microsoft/WSL/assets/2290904/4f90c3e5-32d1-4b5a-9dc6-2bae8e63fff9)
![image](https://github.com/microsoft/WSL/assets/2290904/29cb1b6b-ef96-4e9f-aafc-6a1a6e1bb052)

so i cannot curl it

**Comment by Dokman** [comment]
My windows was borken after a Windows 11 reinstall worked well
