### ISSUE TITLE
generateResolvConf creates nameserver with IPv6 and DNS resolution doesn't work

### ISSUE THREAD

**Issue by sommella** [microsoft/WSL#10810]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-22621-Microsoft

### Distro Version

Ubuntu 20.04

### Repro Steps

I have generateResolvConf  = true in /etc/wsl.conf
and /etc/resolve.conf is generate like this:
nameserver fec0:0:0:ffff::1
nameserver fec0:0:0:ffff::2
nameserver fec0:0:0:ffff::3
search lan

### Expected Behavior

If manually edited, following configuration works:
nameserver 192.168.2.1
search lan

### Actual Behavior

$ ping google.com
ping: google.com: Temporary failure in name resolution

**Comment by devicelocksmith** [comment]
Also impacted by this

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by chanpreetdhanjal** [comment]
Please follow the networking diagnostic script. https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

It should create a folder like [WslNetworkingLogs-date_ver.zip]

**Comment by sommella** [comment]
Hi,
Network logs collected but the file is 123MB and github is not allowing me to attach it.
What should I do?
ty

**Comment by chanpreetdhanjal** [comment]
Can you please try it again? I had other customers successfully attach networking logs to github.

**Comment by sommella** [comment]
[WslNetworkingLogs-2023-12-12_09-25-50.zip](https://github.com/microsoft/WSL/files/13645621/WslNetworkingLogs-2023-12-12_09-25-50.zip)

Done a new capture with less app open (to reduce the size of the dump)
Here is it

Tnx

**Comment by achojak** [comment]
I have upgraded WSL today and experiencing the same issue

```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.3155
```

The only workaround I could find for this problem was disabling IPv6 on each of my network adapters.
You might need to reboot your PC after changing these settings.

![disable-ipv6](https://github.com/microsoft/WSL/assets/706774/01e3d14c-2ba7-43df-9612-a1a110811364)

**Comment by CatalinFetoiu** [comment]
hello. sorry for the delay following up on this.

I recommend turning on dnsTunneling

If you still encounter DNS issues after doing this, please collect a new set of networking logs

thanks

**Comment by Msprg** [comment]
Hello, I have the same issue and wasn't able to solve it by enabling or disabling the DNS tunneling. Have any of you managed to find a better solution than to turn off ipv6 on all NICs in the system? Should I open a new issue?

**Comment by CatalinFetoiu** [comment]
@Msprg please open a separate issue. thanks
