### ISSUE TITLE
guiApplications=false causes broken systemd environment

### ISSUE THREAD

**Issue by fknittel** [microsoft/WSL#10818]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu-22.04

### Repro Steps

1. Disable wslg in `.wslconfig`:
    ```
    [wsl2]
    guiApplications=false
    ```
2. Install a distribution using systemd, e.g. `Ubuntu-22.04`:
    ```
    wsl.exe --install Ubuntu-22.04
    ```
3. Shutdown wsl:
    ```
    wsl.exe --shutdown
    ```
4. Enter distribution again:
    ```
    wsl.exe -d Ubuntu-22.04
    ```

### Expected Behavior

The system should have a working XDG runtime directory:
```
$ ls -lnd $XDG_RUNTIME_DIR
drwx------ 4 1000 1000 120 Nov 23 16:30 /run/user/1000/
```
Additionally, the system should have a proper X11-unix socket dir:
```
$ ls -la /tmp/.X11-unix
total 8
drwxrwxrwt  2 root root 4096 Nov 23 17:01 .
drwxrwxrwt 11 root root 4096 Nov 23 17:01 ..
```

### Actual Behavior

The system has a broken XDG runtime directory:
```
$ ls -ldn $XDG_RUNTIME_DIR
drwx------ 2 root root 4096 Nov 23 13:42 /run/user/1000/
```

Additionally, the system has a missing /tmp/X11-unix direcotry:
```
$ ls -l /tmp/.X11-unix
ls: cannot access '/tmp/.X11-unix': No such file or directory
```

### Diagnostic Logs

The directory `/run/user` appears to be bind mounted from the distributions root filesystem:
```
$ grep /run/user /proc/mounts
none /run/user tmpfs rw,nosuid,nodev,noexec,noatime,mode=755 0 0
/dev/sdc /run/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
$ ls -lid /mnt/wslg/run/user /run/user
29471 drwxr-xr-x 3 root root 4096 Nov 23 16:30 /mnt/wslg/run/user
29471 drwxr-xr-x 3 root root 4096 Nov 23 16:30 /run/user
```
Moving `/mnt/wslg` out of the way, running wsl --shutdown and then re-entering wsl fixes this once. Without moving /mnt/wslg away, the issue returns on the next cycle.

The missing X11-unix directory is caused by the presence of `/run/tmpfiles.d/x11.conf`, which might be a good idea for wslg mode, but not when that is disabled.

Generally, it seems that at least some wslg-specific actions/mounts/system overrides are still active despite of the "guiApplications=false" setting.

**Comment by benhillis** [comment]
Should be fixed with https://github.com/microsoft/WSL/releases/tag/2.0.12.

**Comment by fknittel** [comment]
@benhillis Can you please re-open? Or should I create a new issue?

**Comment by jeffrson** [comment]
Even with WSL 2.0.14 (current stable) or 2.1.3.0 (current pre-release) /run/user/<userid> is not created with
```
[wsl2]
guiApplications=false
```

`guiApplications=true` is no option, unfortunately, since Windows Terminal still/again loses focus after start.

So will this issue be reopened or should we report another one?
