### ISSUE TITLE
autoProxy=true doesn't work for multiple users via su or ssh

### ISSUE THREAD

**Issue by mio-19** [microsoft/WSL#10820]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2 

### Distro Version

Arch

### Repro Steps

+ setup `autoProxy=true`
+ install and run sshd
+ ssh into wsl or `su -l` into another user
+ No proxy env variables

### Expected Behavior

Env for other users

### Actual Behavior

no

**Comment by zcobol** [comment]
@mio-19 you might want to look at these `su` options:

 ```
-m, -p, --preserve-environment      do not reset environment variables
 -w, --whitelist-environment <list>  don't reset specified variables
```

Basically, preserve the environment when su-ing!

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by mio-19** [comment]
> Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

I don't think networking logs would be useful for this issue

**Comment by i-curve** [comment]
2.0.14.0 version also has the problem.

**Comment by Renan-Di** [comment]
This is not a wsl problem, you must configure su/sudo tu propagate env from your user when doing sudo:

`
echo 'Defaults env_keep += "http_proxy https_proxy no_proxy"' | sudo tee -a /etc/sudoers.d/wsl-setup
`

With su you could pass `-p`

https://man7.org/linux/man-pages/man1/su.1.html

**Comment by CatalinFetoiu** [comment]
Please follow the recommendations shared earlier in the thread, to preserve the environment variables
