### ISSUE TITLE
Autostart WSL2 instance after loading Windows 10 (from Stopped state to Running state)

### ISSUE THREAD

**Issue by NicoleLon** [microsoft/WSL#10828]
Tell me, can the WSL2 instance start when Windows starts (in the Running state) without using third-party scripts (such as .vbs), without startup and task scheduler? I tried interacting with LxssManager, nothing worked. I know that VM based on Hyper-v can be configured with autostart when the system starts. Maybe somehow it can be done for WSL2 instance?
![scr1](https://github.com/microsoft/WSL/assets/152089820/1e157120-5941-47e3-bc84-24dce7f8ad60)

**Comment by NicoleLon** [comment]
Maybe there are settings for .wslconfig?

**Comment by 4t8dd** [comment]
I googled some and can not find any good sultion.  wls.conf is for post start config. 
Any good way?
