### ISSUE TITLE
Cisco Any Connect connected VPN no internet

### ISSUE THREAD

**Issue by ieeeeeeee** [microsoft/WSL#10821]
### Windows Version

Microsoft Windows [Version 10.0.19045.3693]

### WSL Version

WSL version: 2.0.9.0 Kernel version: 5.15.133.1-1 WSLg version: 1.0.59 MSRDC version: 1.2.4677 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19045.3693

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.133.1-microsoft-standard-WSL2 (root@1c602f52c2e4) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Oct 5 21:02:42 UTC 2023

### Distro Version

NAME="Ubuntu" VERSION="20.04.6 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.6 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal

### Repro Steps

1. ping 8.8.8.8 works and ping google.ch works
2. connect host with Cisco AnyConnect Secure Mobility Client
3. ping 8.8.8.8 does not work and ping google.ch does not work

### Expected Behavior

1. ping 8.8.8.8 works and ping google.ch works
2. connect host with Cisco AnyConnect Secure Mobility Client
3. ping 8.8.8.8 works and ping google.ch works

### Actual Behavior

1. ping 8.8.8.8 works and ping google.ch works
2. connect host with Cisco AnyConnect Secure Mobility Client
3. ping 8.8.8.8 does not work and ping google.ch does not work

### Diagnostic Logs

Tried different google topics but really not sure what of all this helpful things works because I tried what I could and its still not working...
- [x] https://superuser.com/questions/1630487/no-internet-connection-ubuntu-wsl-while-vpn
  - [x] not working using "Workaround (new - automatic)" 
- [x] not working https://github.com/sakai135/wsl-vpnkit

**Comment by pmartincic** [comment]
/logs

What networking mode are you using in your `.wslconfig`
