### ISSUE TITLE
Error code: 0x80004005

### ISSUE THREAD

**Issue by Alex92-n** [microsoft/WSL#10822]
I tried installing kali-liux in my wsl but i get this error:"Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error"
![image](https://github.com/microsoft/WSL/assets/142750801/5e77d9d3-77e6-4ef4-b5b8-0ac2fcf5c012)

**Comment by CobraSnakeByte** [comment]
I experienced this same issue my machine info listed below
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

I fixed this by updating wsl running the update command "wsl --update"

hope this helps
