### ISSUE TITLE
Missing space in german translation

### ISSUE THREAD

**Issue by londonjob** [microsoft/WSL#10833]
### Windows Version

Microsoft Windows [Version 10.0.22631.2506]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu

### Repro Steps

wsl --install -d Ubuntu
![Screenshot 2023-11-27 222729](https://github.com/microsoft/WSL/assets/19534282/75fe227a-3271-47a8-8b45-fe5817a908f6)

### Expected Behavior

Ubuntu wird gestartet...

### Actual Behavior

Ubuntuwird gestartet...

**Comment by pmartincic** [comment]
Thanks for reporting, what version are you on? I just had a look through our internationalized strings and on recent builds I see where the space should be `%1$ls wird gestartet...` ?
