### ISSUE TITLE
Mirrored networking mode makes requests to localhost:PORT wait 2 minutes

### ISSUE THREAD

**Issue by kenzhemir** [microsoft/WSL#10844]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Setup `.wslconfig` to
```
[wsl2]
networkingMode=mirrored
```
2. Select a free port (9000 in my case, nothing is listening to that port) and run:
```
curl -v localhost:9000
```

### Expected Behavior

Connection is immediately refused

```
➜  ~ curl -v localhost:9000
*   Trying 127.0.0.1:9000...
* connect to 127.0.0.1 port 9000 failed: Connection refused
*   Trying ::1:9000...
* connect to ::1 port 9000 failed: Connection refused
* Failed to connect to localhost port 9000 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9000 after 0 ms: Connection refused
```

### Actual Behavior

It waits for 2 minutes and then times out

```
➜  ~ curl -v localhost:9000
*   Trying 127.0.0.1:9000...
*   Trying ::1:9000...
* connect to ::1 port 9000 failed: Connection refused
* connect to 127.0.0.1 port 9000 failed: Connection timed out
* Failed to connect to localhost port 9000 after 131210 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to localhost port 9000 after 131210 ms: Connection timed out
```

**Comment by ZedG2** [comment]
Any progress here? It's made vscode debugging too slow on mirrored network.

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by MichiBab** [comment]
Seems like its the same problem that i have:
https://github.com/microsoft/WSL/issues/10855
