### ISSUE TITLE
`dnsTunneling` not supported according to EventLog

### ISSUE THREAD

**Issue by jantari** [microsoft/WSL#10853]
### Windows Version

10.0.19045.3693

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Use all the same versions as me (particularly Windows, WSL)
2. Create a `~/.wslconfig` on the Windows side with the following content:
    ```
    [experimental]
    networkingMode=NAT
    dnsTunneling=true
    ```
3. Attempt to open an Ubuntu 22.04 WSL2 instance
4. It takes a bit longer than it should and a notification pops "Error starting WSL, see details in EventLog"
5. The Ubuntu 22.04 WSL2 instance does start, but `dnsTunneling` is not functioning

### Expected Behavior

The Ubuntu instance should start in the usual (pre-enabling dnsTunneling) speed, no error notification should pop and dnsTunneling should work.

### Actual Behavior

The Ubuntu instance takes a bit longer to start than before (no big deal), an error notification pops up and dnsTunneling does not work.

### Diagnostic Logs

This is the XML view of the Event in EventLog. I am so terribly sorry for it being localized to german, but it was Microsofts' terrific idea to localize errors and event messages in this OS, not mine, so I am unfortunately unable to provide logs in english:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="WSL" /> 
    <EventID Qualifiers="40960">0</EventID> 
    <Version>0</Version> 
    <Level>3</Level> 
    <Task>0</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x80000000000000</Keywords> 
    <TimeCreated SystemTime="2023-11-30T08:22:17.0503417Z" /> 
    <EventRecordID>49501</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="0" ThreadID="0" /> 
    <Channel>Application</Channel> 
    <Computer>NB-SERIALNUMBER.domain.local</Computer> 
    <Security /> 
  </System>
  <EventData>
    <Data>DNS-Tunneln wird nicht unterstützt</Data> 
  </EventData>
</Event>
```

**Comment by OneBlue** [comment]
Indeed @jantari. DNS tunnelling is only supported on Windows 11 so this is why you're seeing this warning.
