### ISSUE TITLE
The Windows admin user cannot see the WSL installed on a normal user.

### ISSUE THREAD

**Issue by llagerlof** [microsoft/WSL#10863]
### Windows Version

10.0.22631.2715

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

openSUSE-Tumbleweed 20231101

### Repro Steps

Install wsl2 and a distro as a normal user. 

Try to run `wsl -l -v` as a admin (admin command prompt or full logged as admin)

The installed wsl distro doesn't appear for the admin.

### Expected Behavior

List and see wsl2 installations as admin user.

### Actual Behavior

I installed WSL2 and OpenSUSE with my regular user, and everything is working. Running `wsl -l -v` lists `* openSUSE-Tumbleweed Running 2`

But when I log in with the admin user and run `wsl -l -v`, it says I don't have any distributions installed.

**Comment by OneBlue** [comment]
Thank you for reporting this @llagerlof. This is the expected behavior: Distributions are installed per user and not per machine.
