### ISSUE TITLE
The loopback device can`t be used when I update the kernel version 

### ISSUE THREAD

**Issue by KorvinChen** [microsoft/WSL#10860]
### Windows Version

 10.0.22631.2715

### WSL Version

 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

steps:
1.Download a chromiumos code 
2.Build chromiumos
3.I build successfully
4.I run `sudo apt update` and `sudo apt upgrade`
5.After updating kernel, I can`t build chromiumos successfully again

result:
I can`t run build_image because it tell me the reason is "No free lookback device to create partitions"

### Expected Behavior

I can build chromiumos successfully

### Actual Behavior

I can`t run build_image because it tell me the reason is "No free lookback device to create partitions"

**Comment by OneBlue** [comment]
What's the output of `lsblk` and `dmesg` when you see this error message ?

**Comment by KorvinChen** [comment]
<img width="488" alt="image" src="https://github.com/microsoft/WSL/assets/41417502/311a7d40-2fd7-4272-9e72-9c8a92b6f316">

**Comment by KorvinChen** [comment]
Today, I build a 5.15.123.1 kernel, then change wsl kernel to it, evething is ok, So I am sure 5.15.133-1 version caused the problem

**Comment by KorvinChen** [comment]
![image](https://github.com/microsoft/WSL/assets/41417502/792bb416-ba20-4030-8665-ff776cc50783)
The picture has some information, the graffitied part involves some personal privacy, but I can tell you that this is just a board name and dirname.
