### ISSUE TITLE
Correct messages that appear when installing WSL without or with WSL1

### ISSUE THREAD

**Issue by manelrodero** [microsoft/WSL#10867]
### Windows Version

Microsoft Windows [Version 10.0.22631.2428]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Does not apply

### Repro Steps

* Clean Windows 11 installation
* Open new Administrator prompt
* Install WSL2 from Microsoft Store using `wsl.exe --install --no-distribution` (and/or enable WSL1 adding `--enable-wsl1`)

### Expected Behavior

In case a) no message about Windows Subsystem for Linux should appear because default installation don't enable this Feature as we can see in this screenshot:

![image](https://github.com/microsoft/WSL/assets/26098260/97212331-39ee-49d8-a0f2-59ea35bc4bc7)

In case b) the message should appear once we're enabling this feature as we can see in this screenshot:

![image](https://github.com/microsoft/WSL/assets/26098260/f69317a7-1064-4533-8804-6709cd992f37)

### Actual Behavior

* Case a) Execute `wsl.exe --install --no-distribution`

A message about "Installing: Windows Subsystem for Linux" appear as in this screenshot:

![image](https://github.com/microsoft/WSL/assets/26098260/028a2741-5d7e-40d4-a53e-ed88570a3214)

* Case b) Execute `wsl.exe --install --enable-wsl1 --no-distribution`

The message about Windows Subsystem for Linux appears twice:

![image](https://github.com/microsoft/WSL/assets/26098260/61fb5cf7-3946-4777-88a8-f32f7c2782fb)

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.15
