### ISSUE TITLE
Performance issue when running `pacman` (Arch Linux's package manager)

### ISSUE THREAD

**Issue by KireinaHoro** [Microsoft/WSL#1087]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description

WSL shows a bad performance when running `pacman` (from verifying signature to checking package integrity to installing the package itself). For example, `perl` installation would take 3 minutes (excluding download time) while on real Linux systems this would just take seconds.
- Expected results

Performance nearly as good as native Linux
- Actual results (with terminal output if applicable)

Pretty bad
- Your Windows build number

14926
- Steps / All commands required to reproduce the error from a brand new installation 
1. Get an Arch `rootfs` ready for WSL. (Refer to https://github.com/RoliSoft/WSL-Distribution-Switcher if necessary)
2. Install some packages (like this: `sudo pacman -Syu base-devel`)
3. Watch the package checking and installation process.
- Strace of the failing command

No observable failures 🌚
- Required packages and commands to install

`pacman`

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
This thing is installing a fake version of chroot, libchroot, and fakeroot. It is very hacky and likely will continue to be until chrooting is supported.  I don't think it's fair to do a test like this based on a hack that is just skipping lots of stuff willy-nilly.

**Comment by SRGOM** [comment]
@xubin990510 While a lot of us would like to see Arch come to life on WSL- unfortunately that is not one of Microsoft's focus right now as their primary goal, as they state, is to help developers use programming/dev related tools comfortably on Windows. 

The good news though is that full Arch support is likely just a chroot system call away, something MS has shown interest in implementing to support SSH server. So I think waiting is the best bet right now.

**Comment by xubin990510** [comment]
@SRGOM

That's great news. But this is actually not about the choot things as I have already done the things of moving around things and replacing the Ubuntu root with Arch and now it doesn't need root. What I mean is the performance issues (like verifying gpg signatures, calculating hashes or extracting tar into the filesystem). These things are not limited to Arch and is about the WSL (even not about that Ubuntu 14.04 pre-shipped).

**Comment by fpqc** [comment]
@xubin990510 If it's doing filesystem io it will be slow, btw.

**Comment by therealkenc** [comment]
Well [this](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14936) was a nice Easter Egg.

**Comment by benhillis** [comment]
Are you referring to Xenial?

**Comment by therealkenc** [comment]
From SGROM "The good news though is that full Arch support is likely just a chroot system call away"

**Comment by therealkenc** [comment]
Okay this is making a little bit of sense now. I've never run Arch, but it looks like `pacman` uses `rsync` (right?). So this is probably a dup of #1076. The original post there complains of CPU usage, but I think bringing up CPU speed lost the wider message that "`rsync` is slow". 

`chroot` looks great by the way, `rsync` performance notwithstanding. When the 14901 announcement said that `mount` support was added I didn't consider the obvious of what they were working on. There's a number of GH issues that can be closed I think. I said "easter egg" above because there weren't even any fixinbound tags set to give a hint `chroot` was coming so soon. Thumbs up all around. 👍

**Comment by fpqc** [comment]
@therealkenc I dunno. I knew chroot was coming because I asked Ben and Russ, and they both said it was coming soon lol.

**Comment by therealkenc** [comment]
I think it is safe to place this one under perennial "networking slow" issue #2502 #2864 etc and open (as of this writing) landing zone #2477. Whatever the cause of the performance issue, it isn't going to be specific to 'pacman'.
