### ISSUE TITLE
when installing with wsl --install, linux icon in windows explorer is missing

### ISSUE THREAD

**Issue by uishon** [microsoft/WSL#10872]
### Windows Version

Microsoft Windows (Version 10.0.22631.2715)

### WSL Version

2.0.12.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Install Windows Subsystem for Linux using `wsl --install` (fresh install). Linux icon does not show up in Windows Explorer. Not even after reboot. Wsl itself working well. 

To work around this, go to _add windows feature_ from _Settings_ and check the _Windows Subsystem for Linux_ checkbox, reboot and then it showed up.

### Expected Behavior

Linux icon should show up in Windows Explorer side bar after running `wsl --install`.

### Actual Behavior

No linux icon.

**Comment by fitrarhm** [comment]
I also got the same problem when update WSL through Microsoft Store recently too.

![image](https://github.com/microsoft/WSL/assets/63356065/bcb427c6-e143-4c36-bcf2-c3e36d6e6c2e)

**Comment by WinkelCode** [comment]
I installed WSL2 via the Windows Store and I just coincidentally noticed that the "Linux" item was missing from the Explorer sidebar. I could've sworn it was there before, even when just installing WSL2 from the Windows Store?

However, I can confirm that the item is displayed when installing the _Windows Subsystem for Linux_ Windows Feature.

**Comment by trolledbypro** [comment]
This is happening to me, installed using wsl --install on Windows 11

**Comment by dorea-l** [comment]
this is happening to me as well, I've checked the registry and make sure that WSL in optional features is checked and correct.
But there's no difference.

**Comment by dorea-l** [comment]
It didn't work for me actually.
I've checked the registry editor as well, and namespace is '1', I've also checked WSL in optional features, but the icon doesn't appear for me at all.

**Comment by dorea-l** [comment]
I've tried version 2.1.1.0. It didn't actually work for me, the only things I've changed since uninstalling it previously was double checking if the registry was '0/1', editing that, and turning on/off WSL in optional features.

I've installed WSL about a year ago, then, I still have the Linux icon, I've uninstalled it since and reinstalled it this year, and the icon didn't appear for me.

**Comment by leograba** [comment]
2.1.1 and 2.0.14 didn't work for me:

```
# Before
PS C:\Users\leonardo.veiga> wsl --version
WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3155
# After downgrade 1
PS C:\Users\leonardo.veiga> wsl --version
WSL version: 2.1.1.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3155
# After downgrade 2
PS C:\Users\leonardo.veiga> wsl --version
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3155
```

And the Linux icon is still missing.

I just closed and reopened Explorer, but didn't reboot the machine.

**Comment by bilal-akbar-9** [comment]
Guide to get the icon in **windows 11**, but the process should be somewhat similar to windows 10 as well.
1. Click on the following icon and choose "Add a network location"
![image](https://github.com/microsoft/WSL/assets/94855224/45720733-1957-4c59-b7ac-a1b171dca146)
2. Choose a custom network location and add "\\wsl.localhost\<distroname>" e.g., "\\wsl.localhost\Debian".
![image](https://github.com/microsoft/WSL/assets/94855224/17ed000c-26fc-4d2a-85ff-e0a19d48c625)
And the network location will appear in the file explorer 
![image](https://github.com/microsoft/WSL/assets/94855224/52569e39-1324-47dc-8b82-69eee34a79f5)

**Comment by bilal-akbar-9** [comment]
> > Guide to get the icon in **windows 11**
> 
> Thanks! This is just a temporary workaround though. Helps short term, but it does not solve the underlying issue. The real shortcuts are on the left pane of explorer and are grouped under a little penguin (Linux) icon.

Yeah the shortcut in the left panel disappeared for me too, since then using the one mentioned above.

**Comment by OneBlue** [comment]
Fixed in [2.2.1](https://github.com/microsoft/WSL/releases/tag/2.2.1)

**Comment by okineadev** [comment]
> This might be the same issue as #11026
> 
> See my comment on this issue: [#11026 (comment)](https://github.com/microsoft/WSL/issues/11026#issuecomment-1956749485)
> 
> > I can confirm this issue (missing Linux shortcuts in explorer) exists for me in some WSL2 versions. I tested the few latest ones:
> > The issue persists in versions: 2.0.15, 2.1.0, 2.1.3, 2.1.4
> > However, the issue **does not** exist in versions 2.0.14 and 2.1.1.
> > Downgrading from WSL 2.1.3 to 2.1.1 immediately makes the shortcuts appear in the explorer (without restarting Windows or the explorer).
> > System info:
> > Windows 11 build: 22631.3155
> > WSL kernel for both WSL 2.1.1 and 2.1.3: 5.15.146.1-2
> 
> @uishon @fitrarhm @WinkelCode @trolledbypro As a workaround, you can try installing version 2.1.1 from here: https://github.com/microsoft/WSL/releases/tag/2.1.1 (simply download `wsl.2.1.1.0.x64.msi` and install it) If it works for you, a short feedback comment may help solving this issue in future releases :)

True, I installed the latest version of **WSL** (https://github.com/microsoft/WSL/releases/tag/2.2.1) and that helped - now there is a "linux" section in explorer

![image](https://github.com/microsoft/WSL/assets/81070564/2f2e03ee-5231-457c-a9f2-b6d502f2a1d7)

If suddenly someone gets an error when installing the `.msi` or "`wsl --install`" package, here is the solution - https://github.com/microsoft/WSL/issues/11319#issuecomment-2024192550

**Comment by gael-rukundo** [comment]
This worked for me. https://www.tenforums.com/tutorials/46769-enable-disable-windows-subsystem-linux-wsl-windows-10-a.html

**Comment by carlos-landeira** [comment]
This problem is happening again in WSL2 + Windows 11, `wsl -v` output:

WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605

![Image](https://github.com/user-attachments/assets/18a3438f-b316-4dff-9c87-545b212ccd87)

**Comment by Pavlogal** [comment]
Same, the penguin disappeared, and last week it was there.
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605

**Comment by rama4zis** [comment]
Same, my Linux icon was disappeared 

WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2894

**Comment by AkramiPro** [comment]
same here

```
WSL version: 2.4.8.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2894
```

**Comment by thekovic** [comment]
Also here
```
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2894
```

**Comment by dylangovender** [comment]
Updated Windows and now the WSL access via Explorer is gone.

WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2894

**Comment by HowellBP** [comment]
Same issue, no Linux/penguin icon in the Explorer sidebar anymore.

```
WSL version: 2.4.11.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3194
```
![Image](https://github.com/user-attachments/assets/505fe8be-dc2b-4e58-bf49-eab27c663536)

**Comment by lucagiorgino** [comment]
Same here: 

```
wsl --version
WSL version: 2.4.11.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3194
```

**Comment by rikka0w0** [comment]
I'm having the exact same problem.

```
WSL version: 2.4.11.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3194
```

**Comment by Shararamosh** [comment]
Same thing with WSL 2.4.13.0 and Russian Windows 11 23H2:
```
Версия WSL: 2.4.13.0
Версия ядра: 5.15.167.4-1
Версия WSLg: 1.0.65
Версия MSRDC: 1.2.5716
Версия Direct3D: 1.611.1-81528511
Версия DXCore: 10.0.26100.1-240331-1435.ge-release
Версия Windows: 10.0.22631.5189
```

**Comment by jromero-onclick** [comment]
Same issue after Windows Update. I have solved it with:

- Go to Start Menu and then WSL Settings.
- Change something on the settings (for example, Swap size).
- Close window.
- Restart Windows.

**Comment by JasonBroderick** [comment]
Same for me: 

```
WSL version: 2.5.7.0
Kernel version: 6.6.87.1-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26200.7462
```

Confirmed fix: 

https://github.com/microsoft/WSL/issues/10872#issuecomment-2820709240

> Same issue after Windows Update. I have solved it with:
> 
> * Go to Start Menu and then WSL Settings.
> * Change something on the settings (for example, Swap size).
> * Close window.
> * Restart Windows.

**Comment by dfjs19** [comment]
> Same issue after Windows Update. I have solved it with:
> 
> * Go to Start Menu and then WSL Settings.
> * Change something on the settings (for example, Swap size).
> * Close window.
> * Restart Windows.

me too.
