### ISSUE TITLE
Default user stopped being respected (only on WSLv1 profiles, WSLv2 are okay)

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#10874]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Distro Version

Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #2506-Microsoft Fri Jan 01 08:00:00 PST 2016

### Repro Steps

On my machine I have both WSLv1 and WSLv2 distros and Terminal profiles.

For many years I had it somehow set up that WSLv1 profile in my Terminal logs me in as `vadimkantorov` by default. I just rebooted the laptop, and somehow WSLv1 logs me into as `root`. I created a `/etc/wsl.conf` with 
```
[user]
default=vadimkantorov
```
but it did not help.

WSLv2 profiles still log me in as `vadimkantorov` correctly

The `ubuntu.exe config --default-user vadimkantorov` affects only WSLv2 as it appears

How can I fix my WSLv1 to log me in as `vadimkantorov`?

<hr>

**UPD**: I just fixed it by appending `--user vadimkantorov` to my wsl.exe command line in Terminal config: https://superuser.com/a/1566031/813257, but it would still be nice to know how to fix it from within the distro, as `/etc/wsl.conf` appears to have no effect

**Comment by benhillis** [comment]
I was not able to reproduce this. dmesg likely has some errors.

**Comment by vadimkantorov** [comment]
@benhillis If I stumble on this again, I'll add information. For now, it seems to me that it might have coincided with some Windows Update - and this might have been the reason.

I also had spurious keyboard layouts added to Windows (this is a 15-years old bug affecting all non-English layout users, but still not fixed), and this is typically a sign that Windows had installed some update.
