### ISSUE TITLE
WSL2 boot freeze - VspDeviceWriteErrorLog

### ISSUE THREAD

**Issue by hellicopterpd** [microsoft/WSL#10873]
### Windows Version

Microsoft Windows [Version 10.0.22631.2792]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu

### Other Software

Similar to issue #9942, the ext4.vhdx appears to have been corrupted while running a high CPU and disk workload. The distro froze and will no longer boot after a full system restart.

Debug:
**Collecting logs from failed boot**
Windows Performance Analyzer shows a flood of tthe following error on the host. Full logs attached further down.
```
Event Name: Microsoft-Windows-Hyper-V-StorageVSP//
Source: VspDeviceWriteErrorLog
Message: Log status 0xC0000001: VspDeviceWriteErrorLog: AnsiDeviceName = C:\Users\Redacted\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx, Initiator = 2, SCSIOP = 0x2A, SrbStatus = 0x04
```

**Attempt to mount and recover the ext4.vhdx image from another wsl installation**
host:  `wsl -d Ubuntu-22.04 --mount --bare --vhd <path>`
Ubuntu-22.04:
```$ sudo fsck.ext4 /dev/sdd
[sudo] password for debug:
e2fsck 1.46.5 (30-Dec-2021)
/dev/sdd: recovering journal
```
and fsck hangs. Looking at dmesg shows a flood of errors:
```
[  415.127466] hv_storvsc fd1d2cbd-ce7c-535c-966b-eb5f811c95f0: tag#674 cmd 0x2a status: scsi 0x2 srb 0x4 hv 0xc0000001
```

### Repro Steps

N/A

### Expected Behavior

Succesfully boot, or fail gracefully at the very least (timeout for example)

### Actual Behavior

wsl.exe cmd indefinitely hangs until system restarted.

### Diagnostic Logs

[WslLogs-2023-12-05_16-41-47.zip](https://github.com/microsoft/WSL/files/13559135/WslLogs-2023-12-05_16-41-47.zip)

**Comment by pmartincic** [comment]
I had a look at the raw data in the etl file, saw redacted. Did you perform a blind string replacement on all the data? I don't know the data format well for etl, if it has checksums. But if the replacement was a different length than the original string I won't at all be surprised that it didn't work for us when reading it.

**Comment by hellicopterpd** [comment]
Logs again
[WslLogs-2023-12-06_14-09-45.zip](https://github.com/microsoft/WSL/files/13577448/WslLogs-2023-12-06_14-09-45.zip)

Thankfully I've been able to recover the system image with the following command: `wsl --import new_distro .\new_distro\ <path to ext4.vhdx> --vhd`
