### ISSUE TITLE
Shell freezing

### ISSUE THREAD

**Issue by opensw** [microsoft/WSL#10887]
### Windows Version

Microsoft Windows [Version 10.0.22631.2792]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

When I have 2 WSL2 shells opened, if on the first one, there is a heavy task (i.e. docker pull of a big image, building something that requires a lot of CPU etc), the second shell is responsive (I can issue any command and it works) but if I try to open a third shell it hangs on and after some time it closes.

### Expected Behavior

The third shell should be responsive like the others

### Actual Behavior

The third shell hangs on and it closes after some time

**Comment by opensw** [comment]
No, it is not the same

**Comment by OneBlue** [comment]
Thank you @opensw. Does you see this beahvior with cmd.exe, terminal, or both ?
