### ISSUE TITLE
Problem launching Windows processes from inside WSL2 Docker

### ISSUE THREAD

**Issue by nrclark** [microsoft/WSL#10883]
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker CE, version 24.0.7. Installed on WSL2 from Docker's apt repo.
Notepad.exe

### Repro Steps

I am working on a project that needs to run Windows applications from inside of a WSL2 Docker container. When I try to launch a Windows application directly (notepad.exe used as an example), I get a strange failure. The failure _doesn't_ occur if I launch it from inside of a shell instead.

Inside of WSL2 (with dockerd running as `sudo` in another tab),  this command fails:
```
docker run --rm -it --privileged --mount type=bind,source=/mnt,target=/mnt \
    --mount type=bind,source=/run/WSL,target=/run/WSL \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
    --mount type=bind,source=/etc/group,target=/etc/group,readonly \
    --mount "type=bind,source=$HOME,target=$HOME" \
    --workdir "$HOME" \
    -u $(id -u):$(id -g) \
    --env WSLENV="${WSLENV}" \
    --env WSL_DISTRO_NAME="${WSL_DISTRO_NAME}" \
    --env WSL_INTEROP="${WSL_INTEROP}" \
    --env WT_PROFILE_ID="${WT_PROFILE_ID}" \
    --env WT_SESSION="${WT_SESSION}" \
    ubuntu \
    '/mnt/c/Windows/system32/notepad.exe'
 ```
with the following error:

```
<3>WSL (1) ERROR: ConfigInitializeEntry:1621: Failed to mount (null) at /dev as devtmpfs 1
```

but this one succeeds OK:
```
docker run --rm -it --privileged --mount type=bind,source=/mnt,target=/mnt \
    --mount type=bind,source=/run/WSL,target=/run/WSL \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
    --mount type=bind,source=/etc/group,target=/etc/group,readonly \
    --mount "type=bind,source=$HOME,target=$HOME" \
    --workdir "$HOME" \
    -u $(id -u):$(id -g) \
    --env WSLENV="${WSLENV}" \
    --env WSL_DISTRO_NAME="${WSL_DISTRO_NAME}" \
    --env WSL_INTEROP="${WSL_INTEROP}" \
    --env WT_PROFILE_ID="${WT_PROFILE_ID}" \
    --env WT_SESSION="${WT_SESSION}" \
    ubuntu \
    sh -c '/mnt/c/Windows/system32/notepad.exe'
```

Interestingly, I also see that `bash -c '/mnt/c/Windows/system32/notepad.exe'` fails in the same way, even though `sh -c '/mnt/c/Windows/system32/notepad.exe'` works just fine. I can also make a script with the contents of:
```
#!/bin/bash
/mnt/c/Windows/system32/notepad.exe "$@"
``` 

and run that instead of a shell, and it works as expected.
What's going on here? Can anybody help me out with a workaround?

### Expected Behavior

In all cases, notepad should launch identically.

### Actual Behavior

Launching notepad.exe from `sh`/`dash` works, as does putting it in a shell-script that runs under `bash`. Launching it directly fails, as does launching it from `bash` (even though that works when placed in a script).

All failures produce this message on stderr:
```
<3>WSL (1) ERROR: ConfigInitializeEntry:1621: Failed to mount (null) at /dev as devtmpfs 1
```

### Diagnostic Logs

I couldn't think of any useful dianostic logs. Let me know if there's anything specific that you'd like to see.

**Comment by OneBlue** [comment]
Thank you @nrclark. The issue is that the executable that runs windows executables has special logic when its pid is 1, and inside a docker container it will behave that if it's the first process. 

This is a bug, but until it's fixed you can work around it like this: 
```
docker run --rm -it --privileged --mount type=bind,source=/mnt,target=/mnt \
    --mount type=bind,source=/run/WSL,target=/run/WSL \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
    --mount type=bind,source=/etc/group,target=/etc/group,readonly \
    --mount "type=bind,source=$HOME,target=$HOME" \
    --workdir "$HOME" \
    -u $(id -u):$(id -g) \
    --env WSLENV="${WSLENV}" \
    --env WSL_DISTRO_NAME="${WSL_DISTRO_NAME}" \
    --env WSL_INTEROP="${WSL_INTEROP}" \
    --env WT_PROFILE_ID="${WT_PROFILE_ID}" \
    --env WT_SESSION="${WT_SESSION}" \
    ubuntu \
    bash -c '/mnt/c/Windows/system32/notepad.exe && echo done'
```

**Comment by nrclark** [comment]
Thanks @OneBlue. I also noticed something else that's related. When I have `systemd` enabled in wsl.conf, I can't run Windows processes from inside of Docker at all. Running this:

```
docker run --rm -it --privileged --mount type=bind,source=/mnt,target=/mnt \
    --mount type=bind,source=/run/WSL,target=/run/WSL \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
    --mount type=bind,source=/etc/group,target=/etc/group,readonly \
    --mount "type=bind,source=$HOME,target=$HOME" \
    --workdir "$HOME" \
    -u $(id -u):$(id -g) \
    --env WSLENV="${WSLENV}" \
    --env WSL_DISTRO_NAME="${WSL_DISTRO_NAME}" \
    --env WSL_INTEROP="${WSL_INTEROP}" \
    --env WT_PROFILE_ID="${WT_PROFILE_ID}" \
    --env WT_SESSION="${WT_SESSION}" \
    ubuntu \
    sh -c '/mnt/c/Windows/system32/notepad.exe'
``` 

gives me an different error than before. Instead of that `/dev` error, I get this interesting one instead:

```
sh: 1: /mnt/c/Windows/system32/notepad.exe: not found.
```

Note that if I run `sh -c 'ls /mnt/c/Windows/system32/notepad.exe' instead, the executable is -detected- OK, so it's definitely still getting mounted into Docker without issue. 

This error occurs when:
1. Systemd is enabled and running.

2. Docker is installed and active. It doesn't matter which Docker I use, or whether I run the service using `systemctl start docker` or manually using `service docker start`. When using `service docker run`, it also doesn't matter whether I do it from inside of a shell or whether I do it via `wsl.exe` from  Windows via `cmd.exe`.

3. I try to run any Windows process from inside of a Docker image, even through methods that work when `systemd` is disabled.

I took a log capture of this happening and attached it to this ticket.
[WslLogs-2023-12-08_22-14-56.zip](https://github.com/microsoft/WSL/files/13622963/WslLogs-2023-12-08_22-14-56.zip)

**Comment by ndreys** [comment]
@nrclark does adding
```
-v /init:/init:ro
```
or equivalent `--mount` incantation to your `docker run` help? I think I might have just had the pleasure of running into exactly the  same issue and from what I can tell the problem is that `WSLInterop` registers `/init` as interpreter:
```
cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```
but `/init` isn't present in the container AKA `ENOENT`/"file not found". Adding explicit bind-mount resolved the problem in my case.

I could swear this used to work without, but now I'm starting to doubt my memory. 🤷

**Comment by nrclark** [comment]
@ndreys thanks for the pro-tip! You're right, that got .exe execution working under Docker when systemd is active.  It's interesting that .exe execution works in non-systemd Docker without the explicit /init binding - maybe some more PID1 trickery.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.1.0

**Comment by djc5166** [comment]
Trying to understand what I am doing wrong here. Followed all of the above but my windows binaries always throw

`<3>WSL (12 - ) ERROR: UtilBindVsockAnyPort:307: socket failed 38`

WSL version: 2.6.2.0
Kernel version: 6.6.87.2-1
