### ISSUE TITLE
ARM RVCT error

### ISSUE THREAD

**Issue by opensw** [microsoft/WSL#10886]
### Windows Version

Microsoft Windows [Version 10.0.22631.2792]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I have an ARM application that I am trying to build under Docker image with ARM RVCT 5.x.x compilers (we have different versions for different target platforms). The same image on a real Linux machine works as expected; under WSL2 the build starts correctly, ARM license server is reachable, but after some minutes the ARM compiler complains that it is not able to reach anymore the license server; we have tried to disable the firewall, antivirus, Windows Defender etc but the error
persists. I do not understand what is the problem because if I have a second shell, it is responsive and I can connect to the network and reach the license server during the ARM license failure on the first shell.

### Expected Behavior

The ARM license server should be reachable during the entire time required to build the applications (several minutes) like on a real Linux machine

### Actual Behavior

The ARM license server, for some reason, is not reachable after some minutes the build has started (but on a secondary shell, the license server is reachable)

**Comment by chanpreetdhanjal** [comment]
Hello,

Is it ARM64 or ARM32? Also we suggest using the most recent version of Docker.

**Comment by opensw** [comment]
Hi,
   it is ARM32 and I am using the latest Docker engine version
