### ISSUE TITLE
Copy speed very slow wsl2 windows 11

### ISSUE THREAD

**Issue by Bobbll** [microsoft/WSL#10881]
### Windows Version

Windows 11

### WSL Version

Newest

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu

### Repro Steps

Copy a lot of files from sata 3 hdd extern to sata 3 hdd extern

### Expected Behavior

1 GB folder copy  6gb/s speed

### Actual Behavior

1 GB folder copy speed 5mb/s

**Comment by OneBlue** [comment]
@Bobbll: Are you copying a lot of small files ? Small files can take a lot of time to copy over /mnt/*

**Comment by cody8764** [comment]
WSL 2 uses a **network share** to transfer data and this can be very slow. WSL 1 is faster for file sharing.
