### ISSUE TITLE
GNOME desktop has a lock in Settings and I cannot unlock it because "System policy prevents changes. Contact your system administrator"

### ISSUE THREAD

**Issue by Heng-Zhou** [microsoft/WSL#10893]
### Windows Version

Microsoft Windows [Version 10.0.19045.3693]

### WSL Version

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu
Default Version: 2

### Distro Version

Ubuntu 22.04

### Repro Steps

- Use `wsl --install -d ubuntu` to install WSL and Ubuntu 22.04
- When installation is completed, log into Ubuntu and run:
```
sudo apt update
sudo apt upgrade
sudo apt-mark hold acpid acpi-support
sudo apt install ubuntu-desktop gnome
```
- `sudo apt install xrdp`
- Edit `/etc/xrdp/xrdp.ini` file to change line `port=3389` to `port=3390`
- `sudo systemctl restart xrdp`
- In home directory, create a file `.xsessionrc` containing
> export GNOME_SHELL_SESSION_MODE=ubuntu
> export XDG_CURRENT_DESKTOP=ubuntu:GNOME
> export XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
> export WAYLAND_DISPLAY=
> export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
- Restart wsl and log into Ubuntu
- In Windows, remote desktop to `localhost:3390`
- In GNOME desktop, go to Settings -> Printer. There is a notification below "Unlock ..." button saying "System policy prevents changes. Contact your system administrator":
![image](https://github.com/microsoft/WSL/assets/111557423/9904a151-9969-4613-8b57-7ccfcb32c6dd)

The same is true if I use X forwarding to view the GNOME desktop.

### Expected Behavior

There is no lock or the "Unclock..." button is clickable so that root users can freely make settings in Settings dialog.

### Actual Behavior

There is a "Unlock..." button in Settings dialog and there will be a message when hovering over the button:  "System policy prevents changes. Contact your system administrator". Because of this lock, I cannot add printers.
This problem does not occur on normal Ubuntu system, so I think the issue is related to WSL. I would greatly appreciate it if you can help me with this issue.
I have tried removing `chrome-remote-desktop` package but this method does not work.

### Diagnostic Logs

[WslLogs-2023-12-09_04-25-49.zip](https://github.com/microsoft/WSL/files/13623601/WslLogs-2023-12-09_04-25-49.zip)

**Comment by Lazheart** [comment]
Fixed?
