### ISSUE TITLE
It takes too long to start WSL

### ISSUE THREAD

**Issue by Heng-Zhou** [microsoft/WSL#10891]
### Windows Version

Microsoft Windows [Version 10.0.19045.3693]

### WSL Version

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu
Default Version: 2

### Distro Version

Ubuntu 22.04

### Repro Steps

Run wsl from command line cmd.exe.

### Expected Behavior

I can start wsl (enter Ubuntu) in a few seconds.

### Actual Behavior

It takes 1 minute and 30 seconds to start wsl (enter Ubuntu). 

`wsl "dmesg"` output:

> [    2.118330] systemd-journald[37]: Received client request to flush runtime journal.
> [    2.132267] systemd-journald[37]: File /var/log/journal/65e17a2efc1543a496e347928dfa741a/system.journal corrupted or uncleanly shut down, renaming and replacing.
> [    3.633146] misc dxg: dxgk: dxgglobal_acquire_channel_lock: Failed to acquire global channel lock
> [   49.170849] hv_balloon: Max. dynamic memory size: 8144 MB
> [   92.790399] Failed to query system state: Transport endpoint is not connected
> [   92.790880] WSL (2) ERROR: WaitForBootProcess:3237: /sbin/init failed to start within 10000
> [   92.790882] ms
> [   92.800087] WSL (2): Creating login session for <my user name>
> 

### Diagnostic Logs

[WslLogs-2023-12-08_18-45-25.zip](https://github.com/microsoft/WSL/files/13621811/WslLogs-2023-12-08_18-45-25.zip)

**Comment by craigloewen-msft** [comment]
@Heng-Zhou did you close this issue because of one of the links from the other issues listed there? (I made the bot that responds to similar comments and want to check if it helped you out)

**Comment by Heng-Zhou** [comment]
> @Heng-Zhou did you close this issue because of one of the links from the other issues listed there? (I made the bot that responds to similar comments and want to check if it helped you out)

Yes, I closed the ticket because I solved the issue myself. The solution is not from any of other issues your bot listed.

**Comment by suitable-name** [comment]
@Heng-Zhou How did you solve the problem?
