### ISSUE TITLE
npm start on WSL2 holds time back

### ISSUE THREAD

**Issue by lucashill1717** [microsoft/WSL#10899]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

Node Package Manager (npm)

### Repro Steps

`sudo apt install npm`
`npx create-react-app .`
`date`
`npm start`
(leave running for some time, for development)
`ctrl+c`
`date`

### Expected Behavior

`date` commands should output the correct system time on the device

### Actual Behavior

Second `date` command outputs the same time as the first, completely desyncing from system time

**Comment by pmartincic** [comment]
Did your machine go to sleep? When you look at `powercfg /a` what are the options you see? If you see ` Standby (S0 Low Power Idle) Network Connected` as an available sleep state then I think this is a duplicate of #10006

**Comment by lucashill1717** [comment]
I think you're right! Thank you.
