### ISSUE TITLE
wsl: Unknown key 'network.generateResolvConf'

### ISSUE THREAD

**Issue by rudiwh** [microsoft/WSL#10892]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04

### Repro Steps

i get an error when im implement this config

# Network host settings that enable the DNS server used by WSL 2. This example changes the hostname, sets generateHosts to false, preventing WSL from the default behavior of auto-generating /etc/hosts, and sets generateResolvConf to false, preventing WSL from auto-generating /etc/resolv.conf, so that you can create your own (ie. nameserver 1.1.1.1).
[network]
generateResolvConf = false

![image](https://github.com/microsoft/WSL/assets/144006329/2400c33c-2f84-4545-bf8d-9c7bbee458f3)

### Expected Behavior

this config already im implement 3 months ago and it doesn't get an error. i think this config still support by config wsl and must not get an error.

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/144006329/ee629883-3bb9-4218-aef7-6dd35fd465a9)

**Comment by rudiwh** [comment]
thanks this fix my issue https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6?permalink_comment_id=4468904#gistcomment-4468904

**Comment by craigloewen-msft** [comment]
@rudiwh did you find that gist from one of the linked issues above?? (I made the bot that responds to similar comments and want to check if it helped you out)
