### ISSUE TITLE
Problem starting libvirtd in WSL-2

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#10894]
### Windows Version

Microsoft Windows [Version 10.0.22635.2850]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Debian GNU/Linux 12 (bookworm)

### Other Software

qemu & virt-manager

### Repro Steps

sudo apt -y install  libguestfs-tools libosinfo-bin  qemu-system virt-manager
sudo systemctl enable --now virtlogd # Virtual machine log manager
sudo systemctl enable --now libvirtd # Virtualization daemon

### Expected Behavior

service libvirtd should be running

### Actual Behavior

systemctl status libvirtd
```
* libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: * libvirtd.socket
             * libvirtd-admin.socket
             * libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org

Dec 09 02:40:12 mlwphpenvy360 systemd[1]: Starting libvirtd.service - Virtualization daemon...
Dec 09 02:40:12 mlwphpenvy360 systemd[1]: Started libvirtd.service - Virtualization daemon.
Dec 09 02:40:12 mlwphpenvy360 libvirtd[244]: libvirt version: 9.0.0, package: 9.0.0-4 (Debian)
Dec 09 02:40:12 mlwphpenvy360 libvirtd[244]: hostname: mlwphpenvy360
Dec 09 02:40:12 mlwphpenvy360 libvirtd[244]: internal error: Failed to get udev device for syspath '/sys/devices/virtua>
Dec 09 02:42:12 mlwphpenvy360 systemd[1]: libvirtd.service: Deactivated successfully.

```

**Comment by elsaco** [comment]
@mwoodpatrick `libvirtd` service is starting and stopping okay. Notice last entry `libvirtd.service: Deactivated successfully`. libvirtd is split in separate daemons now. Try running `virsh nodeinfo` or another command and see if it works. Or try ` virt-install` and create a vm. It works, but you're limited to `qemu` as there's no `kvm` support in the WSL default kernel. You'll get a friendly `WARNING  KVM acceleration not available, using 'qemu'`

The `Failed to get udev device for syspath '/sys/devices/virtual/dmi/id'` can be safely ignored. You're doing nested virtualization and there's no dmi info available. If you run `dmidecode` in a WSL container you'll get `No SMBIOS nor DMI entry point found, sorry`.

On a real system  this is the output in `/sys/devices/virtual/dmi/id`:

```
/sys/devices/virtual/dmi/id/
├── bios_date
├── bios_release
├── bios_vendor
├── bios_version
├── board_asset_tag
├── board_name
├── board_serial
├── board_vendor
├── board_version
├── chassis_asset_tag
├── chassis_serial
├── chassis_type
├── chassis_vendor
├── chassis_version
├── modalias
├── power
├── product_family
├── product_name
├── product_serial
├── product_sku
├── product_uuid
├── product_version
├── subsystem -> ../../../../class/dmi
├── sys_vendor
└── uevent
```
