### ISSUE TITLE
After updating to 2.0.14, there is no wsl --update --pre-release command?

### ISSUE THREAD

**Issue by lzy1960** [microsoft/WSL#10897]
### Windows Version

Microsoft Windows [Version 10.0.22631.2792]

### WSL Version

--update: unrecognized option: pre-release

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

I could run wsl commands with any option before, but just after executing `wsl --update --pre-release`, I found problems with some commands:
1. `wsl --version`
Invalid command line option: --version
2. `wsl --update --pre-release`
--update: unrecognized option: pre-release
3. `wsl --update`
正在安装: 适用于 Linux 的 Windows 子系统
[                           0.0%                           ]
部署操作被阻止，因为某个根据程序包系列的策略不允许部署到非系统卷。根据策略，该应用必须安装到系统驱动器，但是系统驱动器未设置为默认值。请在存储设置中，将系统驱动器设置为新内容的默认保存位置，然后重试安装。

And I downloaded the latest 2.0.14 version of the msi installation package, but it prompted that it could not be installed.

![image](https://github.com/microsoft/WSL/assets/40552111/c172927c-8d6b-4578-b467-b2dd722ff843)

### Expected Behavior

1. Solve the above three problems and restore the command to a normal and usable state;
2. Support update in non-system disk

### Actual Behavior

See Repro Steps

**Comment by OneBlue** [comment]
Thank you @lzy1960. Based on what you shared it looks like the installation problem is the root cause. 

Can you share MSI logs ? You can get them via: 
```
msiexec /i <msi> /L*V C:\wsllogs.txt
```

**Comment by lzy1960** [comment]
Sorry for waiting, but when I execute this command, an error will be reported,
![image](https://github.com/microsoft/WSL/assets/40552111/aedaac75-984f-4ad5-b12f-fcac72511321)

but there is an installation log in the `C:\Users\19605\AppData\Local\Temp\wsl-install-logs.txt`, but it seems to have nothing to do with this problem.
[wsl-install-logs.txt](https://github.com/microsoft/WSL/files/13648101/wsl-install-logs.txt)

**Comment by lzy1960** [comment]
> Collaborator

Sorry for waiting, but when I execute this command, an error will be reported,
![image](https://github.com/microsoft/WSL/assets/40552111/aedaac75-984f-4ad5-b12f-fcac72511321)

but there is an installation log in the `C:\Users\19605\AppData\Local\Temp\wsl-install-logs.txt`, but it seems to have nothing to do with this problem.
[wsl-install-logs.txt](https://github.com/microsoft/WSL/files/13648101/wsl-install-logs.txt)

**Comment by OneBlue** [comment]
Thank you @lzy1960. Looking at the logs I can see this: 

```
MSI (s) (A4:98) [18:18:28:661]: Executing op: ActionStart(Name=InstallMsix,,)
MSI (s) (A4:98) [18:18:28:663]: Executing op: CustomActionSchedule(Action=InstallMsix,ActionType=3073,Source=BinaryData,Target=InstallMsix,CustomActionData=C:\WINDOWS\Installer\1a1b857.msi)
MSI (s) (A4:30) [18:18:28:666]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSID695.tmp, Entrypoint: InstallMsix
MSI (s) (A4!C4) [18:18:29:703]: Note: 1: 2205 2:  3: Error 
MSI (s) (A4!C4) [18:18:29:703]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (A4!C4) [18:18:29:703]: Product: Windows Subsystem for Linux -- 无法安装 MSIX 程序包(错误： 不支持该请求。 )。
```

Which is most likely the issue.

Can you collect WSl /logs while the MSI is installed ? This should capture the error code we need to root cause this.

**Comment by jat001** [comment]
try this in an administrative powershell prompt

```
Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers | Remove-AppxPackage
wsl --update --web-download
```

**Comment by lzy1960** [comment]
> try this in an administrative powershell prompt
> 
> ```
> Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers | Remove-AppxPackage
> wsl --update --web-download
> ```

OH God! It works for me!🥰 All commands and options now work properly.
Thank you very much!

**Comment by KodoShinichi** [comment]
> 在管理 powershell 提示符中尝试此操作
> 
> ```
> Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers | Remove-AppxPackage
> wsl --update --web-download
> ```

It works for me!
