### ISSUE TITLE
Trying to install ubuntu-desktop apparently broke my installation

### ISSUE THREAD

**Issue by intentodemusico** [microsoft/WSL#10908]
### Windows Version

Microsoft Windows [Version 10.0.22631.2792]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 24.0.7, build afdd53b

VS Code Version: 1.85.0 w/ WSL extension v0.81.8

### Repro Steps

Tried installing ubuntu-desktop (sudo apt-get install ubuntu-desktop), then cancelled the install. Continued my life for a couple days, but now dpkg and docker are not working.

### Expected Behavior

Being able to use apt-get to update or upgrade. 

### Actual Behavior

Every time I try to install something, I get this:
E: dpkg was interrupted, you must manually run `sudo dpkg --configure -a` to correct the problem. 

I try the above command, but get:

```
Setting up whoopsie (0.2.77) ...
Failed to preset unit: Transport endpoint is not connected
/usr/bin/deb-systemd-helper: error: systemctl preset failed on whoopsie.path: No such file or directory
Failed to reload daemon: Transport endpoint is not connected
Failed to retrieve unit state: Transport endpoint is not connected
invoke-rc.d: could not determine current runlevel
```

When I try to run `sudo service docker start` I get:
`Failed to preset unit: Transport endpoint is not connected`

### Diagnostic Logs

[WslLogs-2023-12-12_17-14-11.zip](https://github.com/microsoft/WSL/files/13653750/WslLogs-2023-12-12_17-14-11.zip)

**Comment by intentodemusico** [comment]
For those coming new to this thread, this is the solution I found.

I ran all the below commands, when one of those got stuck, I pressed ctrl c, and continued with it!

```
sudo mv /etc/acpi/events /etc/acpi/events.bak
sudo ln -s /dev/null /etc/systemd/system/acpid.service
sudo ln -s /dev/null /etc/systemd/system/acpid.path
```

Lastly, I modified `/etc/wsl.conf ` to disable systemd

**Comment by addiaddiaddi** [comment]
> For those coming new to this thread, this is the solution I found.
> 
> I ran all the below commands, when one of those got stuck, I pressed ctrl c, and continued with it!
> 
> ```
> sudo mv /etc/acpi/events /etc/acpi/events.bak
> sudo ln -s /dev/null /etc/systemd/system/acpid.service
> sudo ln -s /dev/null /etc/systemd/system/acpid.path
> ```
> 
> Lastly, I modified `/etc/wsl.conf ` to disable systemd

Thank you so much. It is amazing to me how a simple `sudo apt-get install ubuntu-desktop` can brick my whole wsl for hours...

**Comment by jcanfield** [comment]
I know this is an old issue but I needed to jump in. I have a bootstrap script that I use for Debian and a seperate one for Ubuntu installations. It basically just sets up everything the way I prefer. It does also install a standard KDE win man, which I believe is why WSL2 was having such an issue.

I was getting various errors like:

```
Setting up whoopsie (0.2.77) ...
Failed to preset unit: Transport endpoint is not connected
/usr/bin/deb-systemd-helper: error: systemctl preset failed on whoopsie.path: No such file or directory
Failed to reload daemon: Transport endpoint is not connected
Failed to start whoopsie.service: Transport endpoint is not connected
See system logs and 'systemctl status whoopsie.service' for details.
invoke-rc.d: initscript whoopsie, action "start" failed.
Failed to get properties: Transport endpoint is not connected
dpkg: error processing package whoopsie (--configure):
 installed whoopsie package post-installation script subprocess returned error exit status 1
```

And was unable to run `wsl --user myunsername` from Powershell. 

The above changes fixed the issue. I believe it was mainly having `systemd` set to false in the `/etc/wsl.conf` file.

Thanks @intentodemusico

**Comment by ssshake** [comment]
a couple years later and this saved me, wth
