### ISSUE TITLE
WSL not taking external connections

### ISSUE THREAD

**Issue by Mizuno-Mashiro** [microsoft/WSL#10919]
### Windows Version

Microsoft Windows [Version 10.0.22631.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1

### Distro Version

Ubuntu 22.04

### Other Software

WSLAttachSwitch
Nginx

### Repro Steps

I used [WSLAttachSwitch ](https://github.com/dantmnf/WSLAttachSwitch) to attach a hyper-v switch to my WSL and it is now accessible from LAN, but the problem is that, whenever I tried to port forward to my WSL(In my router), it would just have no response at all.
![image](https://github.com/microsoft/WSL/assets/62197506/7095b898-3f43-4227-937f-5545b3751608)
****

### Expected Behavior

All the ports should've been exposed to LAN and WAN and should be able to be accessed from the internet.

### Actual Behavior

I also tried disabling/adding firewall rules but it just didn't work.
![image](https://github.com/microsoft/WSL/assets/62197506/4f8fa220-ddb2-4903-9ae7-1788b49ab743)

**Comment by Mizuno-Mashiro** [comment]
To be more specific I did tested port forwarding to my other laptop and it was working with no issues so I assume it's not a router fault...

**Comment by davea38** [comment]
I have the same issue. I'm on Windows 10 and I suspect we need the new mirrored networking mode for this. WSL 1 works fine.

**Comment by craigloewen-msft** [comment]
@davea38 this feature is now released to Windows 11 22H2, and so is no longer preview specific! 

Please enabled mirrored networking mode, and ensure you have set the right firewall rule to allow connections and this scenario should work. [See this doc page for full info](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking). 

If you still see an issue after doing so, please reopen or refile this issue. I'll close this one out for bookkeeping purposes. Thank you!

**Comment by Mizuno-Mashiro** [comment]
In the case of mirroring, I won't get a real LAN IP address right? I'll need to port forward to my WSL. Are there any ways it could be exposed to LAN directly? As I do have two physical network cables connecting to my computer, and in the meanwhile I do get 2 IP addresses.... For which one is for my Windows distro and I want to use the other one dedicated for WSL. Is it possible? 
The situation is I do get internet connection after using WSLAttachSwitch and the WSL is able to be accessed from LAN, using that IP address, but it is inaccessible from WAN, as described... Looks like mirrored networking mode only do port forwarding from Windows to WSL?
Checked this [Post](https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723) but seems not solving my concern... Should I be switching to WSL1?

**Comment by Mizuno-Mashiro** [comment]
Very weird the issue has been resolved like magic...? In this case I exposed WSL successfully to LAN and WAN after a blackout... omg

**Comment by davormilutinovic** [comment]
It seems there is a magic repo that has solved at least problem for me https://github.com/sakai135/wsl-vpnkit?tab=readme-ov-file
