### ISSUE TITLE
Java Audio fails under WSL2 under Windows 11

### ISSUE THREAD

**Issue by johnworchester** [microsoft/WSL#10920]
### Windows Version

Microsoft Windows [Version 10.0.22621.2861]

### WSL Version

WSL version: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Debian

### Repro Steps

Compile sample java Audio program:

```java
import javax.sound.sampled.*;
import java.io.*;

public class AudioRecorder {

    public static void main(String[] args) {
        try {
            AudioFormat format = new AudioFormat(44100, 16, 1, true, true);
            TargetDataLine line = AudioSystem.getTargetDataLine(format); // fails here - no sound support

        } catch (LineUnavailableException e) {
            e.printStackTrace();
        }
    }
}
```

### Expected Behavior

Should detect sound

### Actual Behavior

`javax.sound.sampled.LineUnavailableException: The system does not support the specified format.`

**Comment by OneBlue** [comment]
@johnworchester: Do you have sound if let's say you open firefox and open a video on youtube ?

**Comment by johnworchester** [comment]
Flawlessly.

**Comment by OneBlue** [comment]
> Other sound works flawlessy. I also completly reinstalled the distro - to no avail

Ok in this case this issue is probably related to the above code sample or the java libraries that you're using. I'm not a java expert so unfortunately I'm not able to help root cause it. 

Closing since sound works in other applications so this issue isn't caused by WSL.

**Comment by stolsvik** [comment]
This following link is a great writeup of why this happens. Tl;dr: Java uses ALSA directly. There is no emulated soundcard in WSL. Any listing of hardware sound cards yields 0 cards. Ffplay uses PulseAudio. Which normally uses ALSA below. But in WSL is implemented as a RDP-sink back to Windows. So, WSL has hacked this for PulseAudio, but that doesn't help applications that use ALSA directly.

This can be fixed, @OneBlue - your close was rather premature without looking for what is the actual problem.

https://sidshome.wordpress.com/2025/04/11/not-able-to-play-audio-in-java/

**Comment by stolsvik** [comment]
Okay, so I got further: This is actually a 95% solved issue (apparently doesn't survive laptop going to sleep): Install `libasound2-plugins`, and edit `~/.asoundrc`, as explained here: https://github.com/microsoft/wslg/issues/864 - and as that points out, it feels strange that this isn't default.

Here's a quick rundown:
```bash
sudo apt install pulseaudio-utils alsa-utils libasound2-plugins
```

Edit/create `~/.asoundrc`:
```
pcm.!default {
    type pulse
}
ctl.!default {
    type pulse
}
```

Restart WSL, or just reboot the machine.

Test with any WAV file:
```bash
paplay testfile.wav  # Plays via PulseAudio
aplay testfile.wav   # Plays via Alsa
```

Interestingly, `aplay -l` which should list all soundcards still write "no soundcards found...", but Java now do list a "default (default)" JavaAudio mixer, with all the features, both playback and recording. Where both works somewhat - albeit with some minor artifacts.

Also got some info from this Reddit:
https://www.reddit.com/r/bashonubuntuonwindows/comments/17jpeu4/comment/kondz4t/
