### ISSUE TITLE
Still getting WSL.lnk and waiting for an upgrade to finish errors.

### ISSUE THREAD

**Issue by soutzis** [microsoft/WSL#10931]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

WSL is finishing an upgrade... Update failed (exit code: 1603). Error code: Wsl/CallMsi/E_ABORT

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

WSL is finishing an upgrade... Update failed (exit code: 1603). Error code: Wsl/CallMsi/E_ABORT

### Distro Version

Ubuntu

### Other Software

Just running (trying to) wsl from powershell

### Repro Steps

Same as issues in https://github.com/microsoft/WSL/issues/10527

### Expected Behavior

I just wanted my WSL distro to start and be able to use bash

### Actual Behavior

WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT

### Diagnostic Logs

Tell me what logs you need

**Comment by soutzis** [comment]
Thank god my man Mikolaj shared the fix here: https://github.com/microsoft/WSL/issues/10764#issuecomment-1815485695

**Comment by jcrben** [comment]
@OneBlue at the very least there's an error message that could be improved here I think
