### ISSUE TITLE
Question: does WSL create unmovable files?

### ISSUE THREAD

**Issue by rommeswi** [microsoft/WSL#10938]
I am trying to shrink my Windows partition and encounter the problem that due to unmovable files, the partition can only shrink by 1GB.

I already removed other unmovable files (paging file, system protection, restore points, hibernation), so I am wondering if my WSL installation may have created any unmovable files.

**Comment by OneBlue** [comment]
If WSL is running the distribution VHD's might be opened. You can force WSL to close them with wsl.exe --shutdown.
