### ISSUE TITLE
Missing `/proc/sys/kernel/shm`

### ISSUE THREAD

**Issue by PopSlime** [microsoft/WSL#10945]
### Windows Version

Microsoft Windows [Version 10.0.19045.3803]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0

### Distro Version

OracleLinux_8_7

### Other Software

- oraclelinux-developer-release-el8
- oracle-database-preinstall-23c
- oracle-database-free-23c-1.0-1.el8.x86_64

### Repro Steps

1. Install Oracle Database following [the official instructions](https://docs.oracle.com/en/database/oracle/oracle-database/23/xeinl/installing-oracle-database-free.html).
2. Modify the entry for the host PC in `/etc/hosts` to the correct IP instead of `127.0.1.1` (or the configuration would fail with another error.)
3. Configure the database with `/etc/init.d/oracle-free-23c configure`.

### Expected Behavior

Configuration succeeds.

### Actual Behavior

Configuration failed with the following fatal error:
```
[FATAL] ORA-00600: internal error code, arguments: [ksmcsg: failed to get total shm available], [], [], [], [], [], [], [], [], [], [], []
ORA-27300: OS system dependent operation:Cannot open /proc/sys/kernel/shm failed with status: 2
ORA-27301: OS failure message: No such file or directory
ORA-27302: failure occurred at: sskgmgtssa_1
```

**Comment by zcobol** [comment]
@PopSlime you are using `WSL1` and that's the issue. Try upgrading to WSL2. OracleDB installs/works fine in WSL2. 

Sample install log on `OracleLinux_8_7`:

```
[root@RIPPER ~]# /etc/init.d/oracle-free-23c configure
Specify a password to be used for database accounts. Oracle recommends that the password entered should
be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database FREE.
Enter SYS user password:
***********
Enter SYSTEM user password:
*********
Enter PDBADMIN User Password:
**********
Prepare for db operation
7% complete
Copying database files
29% complete
Creating and starting Oracle instance
30% complete
33% complete
36% complete
39% complete
43% complete
Completing Database Creation
47% complete
49% complete
50% complete
Creating Pluggable Databases
54% complete
71% complete
Executing Post Configuration Actions
93% complete
Running Custom Scripts
100% complete
Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/FREE.
Database Information:
Global Database Name:FREE
System Identifier(SID):FREE
Look at the log file "/opt/oracle/cfgtoollogs/dbca/FREE/FREE.log" for further details.

/etc/init.d/oracle-free-23c: line 373: /bin/hostname: No such file or directory
Connect to Oracle Database using one of the connect strings:
     Pluggable database: :1539/FREEPDB1
     Multitenant container database: :1539
```

Add `hostname` package before running the installer to get rid of the `/bin/hostname: No such file or directory` error.

**Comment by OneBlue** [comment]
@PopSlime indeed upgrading to WSL2 should fix the issue. Closing since WSL2 is the supported way to do this.
