### ISSUE TITLE
WSL2 create GBs of swap file using docker or apache2

### ISSUE THREAD

**Issue by XJTLUmedia** [microsoft/WSL#10941]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 11.2.0

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 24.0.7, build afdd53b installed on WSL2

### Repro Steps

mkdir plane-selfhost

cd plane-selfhost

curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh

chmod +x setup.sh

### Expected Behavior

It shouldn't create so many swap.vhdx

### Actual Behavior

![t12](https://github.com/microsoft/WSL/assets/102778070/fe907f8d-226f-42c1-ab17-5a9a75106682)
it constantly create swap.vhdx, according to https://learn.microsoft.com/en-us/windows/wsl/wsl-config Swap storage is disk-based RAM used when memory demand exceeds limit on hardware device. Everytime I use localhost(starting the service), it create a new swap.vhdx. Why WSL2 is creating swap file more than once, and keep demanding memory?

Can I delete all these swap.vhdx?

**Comment by isolitude** [comment]
The same problem. Every time I open docker, it will create two random-name filefolder  in AppData\Local\Temp with swap.vdhx in it

**Comment by OneBlue** [comment]
@XJTLUmedia: These swap VHD's are safe to delete. I'm curious about why they don't get automatically deleted though. Can you share /logs of a repro where the file is left behind ? 

/logs

**Comment by lzyang2000** [comment]
I am also experiencing the same issue
