### ISSUE TITLE
WSL update to 2.0.14.0 says Virtual Machine Platform not enabled

### ISSUE THREAD

**Issue by borjamunozf** [microsoft/WSL#10946]
### Windows Version

Microsoft Windows [19045.3570) 22H2

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1) WSL was working fine.
2) Somehow it updated automatically
3) Stopped working after update 2.0.14

![imagen](https://github.com/microsoft/WSL/assets/25910927/34641d5c-1791-4628-b47d-6becb9856bbc)

We have uninstalled & reinstalled Virtual Machine Platform without success.

### Expected Behavior

WSL works, cannot access any distro.

### Actual Behavior

![imagen](https://github.com/microsoft/WSL/assets/25910927/00b2ada3-b494-4673-b868-811ff50418b2)

WSL2 stöds inte med den aktuella datorkonfigurationen.
Aktivera den valfria komponenten Virtual Machine Platform och se till att virtualisering har aktiverats i BIOS.
Aktivera Virtual Machine Platform genom att köra: wsl.exe --install --no-distribution
Mer information finns på https://aka.ms/enablevirtualization
Error code: Wsl/Service/CreateInstance/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED

**Comment by MrDiagnose** [comment]
same mine wsl2 is broken too idk must be the new windows update because of that google play games is also not working before it was working fine

**Comment by Katrawud** [comment]
> ### เวอร์ชั่นวินโดวส์
> ไมโครซอฟต์ วินโดวส์ [19045.3570) 22H2
> 
> ### เวอร์ชัน WSL
> 2.0.14.0
> 
> ### คุณใช้ WSL 1 หรือ WSL 2 หรือไม่?
> * [x] ดับเบิลยูเอสแอล 2
> * [ ] ดับเบิลยูเอสแอล 1
> 
> ### เวอร์ชันเคอร์เนล
> _ไม่มีการตอบสนอง_
> 
> ### เวอร์ชันดิสโทร
> _ไม่มีการตอบสนอง_
> 
> ### ซอฟต์แวร์อื่น ๆ
> _ไม่มีการตอบสนอง_
> 
> ### ขั้นตอนการทำซ้ำ
> 1. WSL ทำงานได้ดี
> 2. ยังไงก็ตามมันอัปเดตอัตโนมัติ
> 3. หยุดทำงานหลังจากการอัพเดต 2.0.14
> 
> ![รูปภาพ](https://private-user-images.githubusercontent.com/25910927/292456493-34641d5c-1791-4628-b47d-6becb9856bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4ODkzNjcsIm5iZiI6MTcwMzg4OTA2NywicGF0aCI6Ii8yNTkxMDkyNy8yOTI0NTY0OTMtMzQ2NDFkNWMtMTc5MS00NjI4LWI0N2QtNmJlY2I5ODU2YmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIyMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMjhhZWU2MGI5NTA1MTljMTBmNGI5ZTA3YzhlYzVkMDVjM2ZjMDQ2OWJjODVjNDc4NjBiZGFlZmQxYTFmZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgO55nLKcm1DwsEGE9PfIA0E79iDkXF_QPsL9pLJvcY)
> 
> เราได้ถอนการติดตั้งและติดตั้ง Virtual Machine Platform ใหม่โดยไม่ประสบความสำเร็จ
> 
> ### พฤติกรรมที่คาดหวัง
> WSL ใช้งานได้ ไม่สามารถเข้าถึง distro ใด ๆ
> 
> ### พฤติกรรมที่แท้จริง
> ![รูปภาพ](https://private-user-images.githubusercontent.com/25910927/292456503-00b2ada3-b494-4673-b868-811ff50418b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4ODkzNjcsIm5iZiI6MTcwMzg4OTA2NywicGF0aCI6Ii8yNTkxMDkyNy8yOTI0NTY1MDMtMDBiMmFkYTMtYjQ5NC00NjczLWI4NjgtODExZmY1MDQxOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIyMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDk1YmVhOWU1MTJmMzUxNDliMzE3MjViMTcyNmNjODcyNGFmYTdjYmI4ZTU3ODFiOTY3ZDQ1ODYzMzk0YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rVc2wmYF7YBRyNIdPrsv8qyNI_TRDOXz0DfYHJaRngc)
> 
> WSL2 มีอยู่ในการกำหนดค่าเริ่มต้น เปิดใช้งาน Virtual Machine Platform แล้วและยังใช้งาน virtualisering ใน BIOS อีกด้วย Aktivera Virtual Machine Platform จีโนมที่: wsl.exe --install --no-distribution Mer information finns på https://aka.ms/enablevirtualization รหัสข้อผิดพลาด: Wsl/Service/CreateInstance/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED
> 
> ### บันทึกการวินิจฉัย
> _ไม่มีการตอบสนอง_

**Comment by borjamunozf** [comment]
We reinstalled back & forth Virtual Machine Platform without success. However, we realized that **bcedit** showed

**hypervisorlaunchtype    Off**

This has been changed automatically for some reason by the last update.

The fix:
```
bcdedit /set hypervisorlaunchtype auto
```

Reboot & it should be work.

It's really urgent & critical for enteprise to get stable releases & be allowed to disable automatic updates of WSL. Not sure how we can avoid & minimize all this problems each time WSL is automatically updated.

**Comment by MrDiagnose** [comment]
i tried everything even this It doesn't fix it I can only use wsl for now wsl2 doesn't work it used to work flawlessly :/

**Comment by OneBlue** [comment]
Closing since the original issue was fixed. @MrDiagnose: If the issue isn't resolved feel free to reopen a new one and share your logs.
