### ISSUE TITLE
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'

### ISSUE THREAD

**Issue by jegrami** [microsoft/WSL#10954]
### Windows Version

Microsoft Windows [Version 10.0.19045.3803]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 22.0

### Repro Steps

`wsl.exe --install -d Ubuntu`

### Expected Behavior

WSL should begin installing Ubuntu

### Actual Behavior

Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. The operation timed out
Error code: Wsl/InstallDistro/0x80072ee2

**Comment by OneBlue** [comment]
Unfortunately this looks like either a networking issue on your machine or a github related issue. Do you still see the same error ?

**Comment by jegrami** [comment]
Yes, I still get the error. And when i run `wsl --list --online`, i get this error: `Error: 0x80072ee2.`

WSL2 was working fine. I woke up one day and tried launching Ubuntu as usual, but it wasn't responding. so I uninstalled it and tried installing it again. That was when the issue started.

ChatGPT says the error `Wsl/0x80072ee2` usually indicates connectivity issues or problems with WSL itself. 

I'm guessing my manual deletion of the program files might have caused the connectivity problem. but the system was already misbehaving before I decided to uninstall, delete residual config files, and reinstall.  

#### Solutions I've tried: 
* resetting WSL by running `wsl --shutdown` 
* switching to an alternative DNS server
* flushing DNS cache: `ipconfig /flushdns`
* deleting residual WSL files
* running `lxrun /uninstall /full /y`
* made sure WSL is enabled in my Windows Features

None of the above worked. Also, annoyingly, Tux 🐧 is still showing on my filesystem. I can't delete it.

**Comment by jegrami** [comment]
When I try `ping raw.githubusercontent.com`, i get a timeout: 

```
Pinging raw.githubusercontent.com [185.199.108.133] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 185.199.108.133:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by OneBlue** [comment]
Thank you @jegrami. Sadly this shows that this is a networking issue on your side or with github so this is unfortunately not something that WSL can solve. 

Closing since the issue doesn't come from WSL

**Comment by sharath3589** [comment]
Hey, was having the same issue and turning of Cloudflare WARP and then doing "ipconfig /flushdns" in terminal did the trick for me. Hope it helps for anyone later.

**Comment by JackWUK** [comment]
> Hey, was having the same issue and turning of Cloudflare WARP and then doing "ipconfig /flushdns" in terminal did the trick for me. Hope it helps for anyone later.

I can confirm that the ipconfig /flushdns command solved the issue for me immediately. This was on a new PC, completely fresh install, but after a WiFi driver update.

**Comment by Sysloom** [comment]
jajaja wooo, puedo confirmar, encendí mi VPN luego ejecute "ipconfig /flushdns", volvi a hacer los pasos del wsl y fue como por arte de magia se instalo todo correctamente.

**Comment by simbiosis-tom** [comment]
Flushing the dns cache didn't work for me. I had to disable ipv6. This is on a brand new laptop Windows 11 Pro.

https://theitbros.com/ping-returns-ipv6-address-ping-ipv4/

**Comment by javichz** [comment]
Had to disable ipv6 too (brand new install, Windows 11 Home  25H2 - 26200.7171)

**Comment by atoledo91** [comment]
> Flushing the dns cache didn't work for me. I had to disable ipv6. This is on a brand new laptop Windows 11 Pro.
> 
> https://theitbros.com/ping-returns-ipv6-address-ping-ipv4/

it worked for me

**Comment by AlCaTrAzzALZ** [comment]
> > Flushing the dns cache didn't work for me. I had to disable ipv6. This is on a brand new laptop Windows 11 Pro.
> > https://theitbros.com/ping-returns-ipv6-address-ping-ipv4/
> 
> it worked for me

this solved the issue for me as well. freshly formatted win11pro laptop
