### ISSUE TITLE
Alternative connection to network and host machine in mirrored mode

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/WSL#10952]
### Windows Version

Microsoft Windows [Version 10.0.26016.1012]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Archlinux

### Other Software

I also have wsa installed and running.

### Repro Steps

Start an http server on host machine, say `python -m http.server`.
(1) Try `wget www.google.com`.
(2) try `curl localhost:8000`.

### Expected Behavior

Both commands should work.

### Actual Behavior

Sometimes, usually when I just reboot my computer, (1) works normally and (2) hangs. Sometimes, usually after I run `wsl --shutdown` then restart wsl, (1) shows that no route to host but (2) works.

### Diagnostic Logs

Please let me know what logs I can provide.

**Comment by PhyX-Meow** [comment]
https://github.com/microsoft/WSL/issues/10791
This may be related. Also, here is my `.wslconfig`
```
[wsl2]
localhostForwarding=true
networkingMode=mirrored
#networkingMode=NAT
dnsTunneling=true
firewall=false
autoProxy=false

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
```

**Comment by orobardet** [comment]
I have the exact same issue.

I'm using a professionnal VPN on my windows host. Until the network mirror mode appears, we had to do some trick with WSL-VPNkit to have networking inside WSL.
Now with the new networking mode, vpnkit is not needed anymore (way much easier to setup a working WSL), but from time to time, I have the issue mentioned here:
- my wsl distro does not have outoing network access
- and/or from windows I can't access with localhost on a service listening in the wsl distro (but it's accessible from within the wsl)

My `.wslconfig`:
```
[wsl2]
memory=20GB
swapFile=C:\\wsl-run\\wsl2-swap.vhdx

[experimental]
sparseVhd=true
autoMemoryReclaim=gradual
networkingMode=mirrored
#dnsTunneling=true
```

My `/etc/wsl.conf`:
```
[boot]
systemd=true

[network]
generateResolvConf=true
```

**Comment by PhyX-Meow** [comment]
Added: I'm using latest insider preview build 26016, there's no issue on 23xxx channel.

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by PhyX-Meow** [comment]
This is somehow fixed in latest wsl and latest Windows insider build.
