### ISSUE TITLE
Interop broken

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/WSL#10951]
### Windows Version

Microsoft Windows [Version 10.0.26016.1012]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Archlinux

### Repro Steps

Run ipconfig.exe in wsl shell.

### Expected Behavior

It should prints normally.

### Actual Behavior

The shell freeze, `ctrl-c` is not working, and there is a windows process named `conhost.exe` using huge amount of cpu.
However, gui applications run normally, for example, `explorer.exe` and `notepad.exe` will start normally.

**Comment by PhyX-Meow** [comment]
This may due to https://github.com/microsoft/terminal/issues/16343

**Comment by OneBlue** [comment]
This indeed looks related to the above terminal issue. Closing since this is not a WSL issue.
