### ISSUE TITLE
wsl: Unknown key 'wsl2.hostAddressLoopback' in C:\Users\<username>\.wslconfig:9

### ISSUE THREAD

**Issue by oldshensheep** [microsoft/WSL#10965]
### Windows Version

Microsoft Windows [Version 10.0.22635.2915]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.133.1-microsoft-standard-WSL2

### Distro Version

ArchLinux

### Repro Steps

my wslconfig in  C:\Users\<username>\.wslconfig
```
[wsl2]
swap=0
memory=8G

dnsTunneling=true
firewall=true
autoProxy=true
networkingMode=mirrored
hostAddressLoopback=true

```

### Expected Behavior

Working, as my Windows version is 23H2 > 22H2 https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings

### Actual Behavior

wsl: Unknown key 'wsl2.hostAddressLoopback' in C:\Users\<username>\.wslconfig:9

**Comment by elsaco** [comment]
That feature is still experimental, as explained at https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings

Try:

```
[wsl2]
swap=0
memory=8G

dnsTunneling=true
firewall=true
autoProxy=true
networkingMode=mirrored

[experimental]
hostAddressLoopback=true
```

**Comment by oldshensheep** [comment]
@elsaco thanks, this worked. However, the document only mentions that `autoMemoryReclaim` and `sparseVhd` are experimental
see this https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings There may be a documentation error.
