### ISSUE TITLE
E: Unable to locate package linux-headers-5.15.133.1-microsoft-standard-WSL2

### ISSUE THREAD

**Issue by jtmic** [microsoft/WSL#10967]
### Windows Version

Microsoft Windows [Version 10.0.22621.2861]

### WSL Version

 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Debian 2023.4 (No Lsb modules are available.

### Repro Steps

Commands
sudo apt update
sudo apt upgrade

RESTART YOUR COMPUTER

Install dkms and git :
sudo apt install dkms git

Install Build Dependencies :
sudo apt install build-essential libelf-dev linux-headers-$(uname -r)

Download the Driver files using git :

git clone https://github.com/aircrack-ng/rtl881... 

Navigate to the Downloaded directory :
cd rtl8812au

Install the Driver
sudo make dkms_install

Check the wireless interface Is Connected
lsusb

TO CHECK MONITOR MODE

iwconfig
airmon-ng check kill
airmon-ng start wlan0
iwconfig

TO CHECK PACKAGE INJECTION

aireplay-ng --test wlan0

### Expected Behavior

THe expected behavior is that it downloads the file. I cnat write out that much code, but I will paste the link to the video.

Video: https://www.youtube.com/watch?v=JAoj5tOFJZc&t=243s

Go to timestamp 4:15

### Actual Behavior

I am trying to install drivers for my TP-LINK ARCHER T2U PLUS On Kali With MONITOR MODE And PACKAGE INJECTION. 

When I enter the input: sudo apt install build-essential libelf-dev linux-headers-$(uname -r), 

I get the error: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-5.15.133.1-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-headers-5.15.133.1-microsoft-standard-WSL2'

**Comment by pmartincic** [comment]
/dupe #10913

There are also the `linux-(tools|headers)-generic` packages if you want to go that route.
