### ISSUE TITLE
ROS can't smoothly run over the "mirrored" networking mode

### ISSUE THREAD

**Issue by itsrealkk** [microsoft/WSL#10960]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04

### Other Software

ROS: Noetic 1.16.0

### Repro Steps

When my `.wslconfig` set to the following settings,

```
[experimental]
autoMemoryReclaim=gradual  # gradual  | dropcache | disabled
networkingMode=mirrored
dnsTunneling=true
firewall=false
autoProxy=true
```
When I run the command `roscore`, nothing happends here, just **a blank line**.

After that, I type `CTRL + C`, then it worked.

![20231228-103933](https://github.com/microsoft/WSL/assets/38235044/cdc85fcc-6b16-45dc-8629-8a5df08c16bb)

This also happends to `rviz`, `turtlesim` demo and any roscore-related program.

I suspect it's a firewall issue，then I change my settings in `.wslconfig`,

```
[experimental]
autoMemoryReclaim=gradual  # gradual  | dropcache | disabled
networkingMode=mirrored
dnsTunneling=true
# firewall=false
autoProxy=true
```

**This problem still occured.**

So I change my settings in `.wslconfig`,

```
[experimental]
autoMemoryReclaim=gradual  # gradual  | dropcache | disabled
# networkingMode=mirrored
dnsTunneling=true
# firewall=false
autoProxy=true
```
I commented two lines: change the networkingMode from `mirrored` to `bridged` and disable the firewall.

Then, it works, I don't need to press `CTRL + C` on my keyboard that `roscore` can smoothly run.

So I suspect it's a issue with `mirrored` network mode and `ros`.

### Expected Behavior

I hope that the `ros` can perfectly run on wsl2.

### Actual Behavior

```
➜  kk roscore
^C... logging to /home/kk/.ros/log/3e701144-a52a-11ee-b9c7-9991ff5cc5fd/roslaunch-DESKTOP-NNJ41KM-1170.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://DESKTOP-NNJ41KM:60799/
ros_comm version 1.16.0


SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES

auto-starting new master
process[master]: started with pid [1189]
ROS_MASTER_URI=http://DESKTOP-NNJ41KM:11311/

setting /run_id to 3e701144-a52a-11ee-b9c7-9991ff5cc5fd
process[rosout-1]: started with pid [1199]
started core service [/rosout]
```

**Comment by OneBlue** [comment]
Unfortunately there isn't enough information to root cause the issue. This should probably be raised from the ROS side. 

Closing since this isn't a WSL issue.

**Comment by venabled** [comment]
Just FYI to get this to work you need to manually set your ROS_MASTER_URI to something that it can resolve

**Comment by haiha95** [comment]
> Just FYI to get this to work you need to manually set your ROS_MASTER_URI to something that it can resolve

Thank you, this solution works for me. For future reference, you can do
`export ROS_MASTER_URI=http://localhost:11311/`
either in your .bashrc file or before running a ROS master.

Note that this is for `networkingMode=mirrored` in `[wsl2]`.

**Comment by TCXM** [comment]
I resolved this issue by changing the Wi-Fi network profile from "Public Network" to "Private Network" in Windows. I think it might have been related to the Windows firewall settings.
