### ISSUE TITLE
edit-and-execute-command execute the command(that was already enter when ctrl x ctrl e) even when quiting the editor without saving.

### ISSUE THREAD

**Issue by rapasite** [microsoft/WSL#10962]
### Windows Version

Microsoft Windows [Version 10.0.22621.2861]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 23.04

### Repro Steps

-lunch WSL from terminal (type `wsl` in cmd).
-start typing a command.
-press ctrl+x then ctrl+e
-quit the editor without saving

### Expected Behavior

the command should not be executed if you do not save the edit in the editor.

### Actual Behavior

Ubuntu execute the command I started typing before using the shortcut (ctrl x ctrl e).

**Comment by OneBlue** [comment]
WSL doesn't control the behavior of the shell. What you're seeing is depending on the shell you're using.

Closing since this is not a WSL issue.
