### ISSUE TITLE
VS2023 dialog: CPU virtualisation warning, even though it is enabled

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/WSL#10970]
### Windows Version

Microsoft Windows [Version 10.0.22621.2861]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu (Default) (Ubuntu 22.04.2 LTS)

### Other Software

Visual Studio 2022 - 17.8.3

### Repro Steps

Open a C++ CMake project. VS will then show this:

![image](https://github.com/microsoft/WSL/assets/4967343/9ea2a90d-630c-4a82-a596-ae37a501ec47)

Then press "Install WSL". Then this "installation guide" shows:

![image](https://github.com/microsoft/WSL/assets/4967343/ab7f3e78-4409-4114-9d29-db26d7640fd9)

It says "CPU virtualisation is enabled in BIOS. You must enable virtualisation... etc", with a yellow warning triangle. This is very confusing: CPU virtualisation is enabled on my machine in BIOS, and the Task Manager confirms it - and WSL works of course. So I would expect a **green checkmark** for this item, not a yellow warning triangle.

### Expected Behavior

 I would expect a **green checkmark** for this item, not a yellow warning triangle.

### Actual Behavior

A yellow warning triangle is shown, even though virtualisation is enabled and WSL works without any problems.

**Comment by OneBlue** [comment]
Closing since this is a Visual Studio issue and not a WSL one.

**Comment by patrikhuber** [comment]
I reported this on the VS bugtracker https://developercommunity.visualstudio.com/t/WSL-dialog:-CPU-virtualisation-warning/.
