### ISSUE TITLE
WSL Update 2.0.14 Removes the 'Linux' Folder from File Explorer's Navigation Pane

### ISSUE THREAD

**Issue by mannkeithc** [microsoft/WSL#10979]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.3 LTS

### Other Software

Visual Studio 17.8.3

### Repro Steps

Fresh install of WSL, admin term 'wsl --install'

Set-up Ubuntu, create user name & password, and sudo apt update && upgrade. Linux folder appears in Explorer navigation as expected, and includes Ubuntu folder with access to Ubuntu file system.

Run Microsoft Store "check for updates", and no WSL update

Action 'wsl --update' command from admin terminal and WSL is updated from version 2.0.9 to 2.014. After update completed, 'Linux' folder is missing from Explorer navigation pane.

I had to do a full WSL uninstall and reinstall WSL and not perform the WSL update to 2.01.4 to restore 'Linux' folder in the Explorer navigation pane.

### Expected Behavior

<img width="849" alt="LInux folder from Explorer Navigation Pane WSL 2 09" src="https://github.com/microsoft/WSL/assets/43237916/bd19a7b8-ca06-427c-b65c-783c111d8ed7">

### Actual Behavior

<img width="844" alt="Missing LInux folder from Explorer Navigation Pane after udate to WSL 2 014" src="https://github.com/microsoft/WSL/assets/43237916/7c39b217-e5bc-4603-910e-55c10971c519">

**Comment by mannkeithc** [comment]
Above similar issues relate to older WSL versions. This problem relates to going from WSL version 2.0.9 (stable) to WSL 2.0.14 (latest). Linux folder present in Explorer navigation pane in version 2.0.9 but removed by version 2.0.14. I am not sure if this issue relates the "Allow port binds from different network namespaces when mirrored networking is enabled" change.

**Comment by wimhuizinga** [comment]
I've got the same issue after updating to 2.0.14.0. Currently using workaround: You can navigate to `\\wsl$` and then pin the distro folder to quickstart.

Versions:
WSL 2.0.14.0
Kernel: 5.15.133.1-1
WSLg: 1.0.59
MSRDC: 1.2.4677
Direct3D: 1.611.1-81528511
DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows: 10.0.22621.2715
