### ISSUE TITLE
WSL does not support `--version` option to report version of WSL

### ISSUE THREAD

**Issue by Heng-Zhou** [microsoft/WSL#10975]
### Windows Version

Microsoft Windows [Version 10.0.19045.3803]

### WSL Version

Don't know, hence this ticket.

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04

### Repro Steps

1) Follow https://learn.microsoft.com/en-us/windows/wsl/install-manual to install WSL2. Step1-3 are the same.
2) In Step 4, download the latest update package of WSL2. After download, restart Windows.
3) After back from reboot, install the update package downloaded in the last step.
4) Open cmd.exe and run `wsl --install -d ubuntu` to install Ubuntu. Input username and password as prompted.
5) When installation of Ubuntu guest OS is done, exit to Windows command line.
6) Run `wsl --version`, you got errors:

> Invalid command line option: --version
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Usage: wsl.exe [Argument] [Options...] [CommandLine]
> 
> Arguments for running Linux binaries:
> 
> ... ... 

### Expected Behavior

As expected of the bug report guide, `wsl.exe --version` should return WSL version, instead of an error.

### Actual Behavior

Instead of WSL version, `wsl.exe --version` returns an error:

> Invalid command line option: --version
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Usage: wsl.exe [Argument] [Options...] [CommandLine]
> 
> Arguments for running Linux binaries:
> ... ...

If newer version of WSL indeed doesn't support `--version` option, please remove it from Bug Report guidance page. But I think most of WSL users need an option to return the version of WSL installed. So, I don't understand why this useful option is removed. 

### Diagnostic Logs

[WslNetworkingLogs-2024-01-03_11-46-59.zip](https://github.com/microsoft/WSL/files/13821433/WslNetworkingLogs-2024-01-03_11-46-59.zip)

**Comment by Heng-Zhou** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> ### Open similar issues:
> 
>     * ['wsl --version' not available any more (#10693)](https://github.com/microsoft/WSL/issues/10693),  similarity score: 0.83
> 
>     * [Set version to WSL '1' fails with 'Invalid command line option' (#9503)](https://github.com/microsoft/WSL/issues/9503),  similarity score: 0.81
> 
>     * [Add default version info flag/parameter for wsl command (#5985)](https://github.com/microsoft/WSL/issues/5985),  similarity score: 0.81
> 
>     * [Having a bit of an issue using wsl --set-version (#9724)](https://github.com/microsoft/WSL/issues/9724),  similarity score: 0.81
> 
>     * [Can not use --set-version command to switch to wsl2. Error: 0xffffffff (#5193)](https://github.com/microsoft/WSL/issues/5193),  similarity score: 0.81
> 
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

I did not find an answer in ticket #10693.

**Comment by OneBlue** [comment]
@Heng-Zhou: You're probably using inbox WSL. Running wsl.exe --update  should solve the issue.
