### ISSUE TITLE
Stale link for 'reporting security bugs' in wsl-kernel repo README.md.

### ISSUE THREAD

**Issue by ReneNyffenegger** [microsoft/WSL#10986]
### Windows Version

Microsoft Windows [Version 10.0.22621.2861]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1

### Distro Version

Debian

### Repro Steps

The link points to https://www.kernel.org/doc/html/latest/admin-guide/security-bugs.html, but should be changed to https://www.kernel.org/doc/html/latest/process/security-bugs.html (it was changed with https://github.com/torvalds/linux/commit/44ac5abac86b20856e6d9e5e5e40dcc2623fe330)

### Expected Behavior

Correct link

### Actual Behavior

Wrong link

### Diagnostic Logs

I am wondering why you don't support direct Pull Requests for things like this. I feel it would be easier for everyone involved.

**Comment by pmartincic** [comment]
I see pull requests from other folks? You're welcome to submit a pull request.

**Comment by ReneNyffenegger** [comment]
https://github.com/microsoft/WSL2-Linux-Kernel/pull/249 explicitely says *Thanks for creating the PR. Unfortunately, we don't take PRs through this repo. I'm really sorry that you went through the trouble of creating a PR only to be told this.*

"feature request" takes me to https://github.com/microsoft/WSL2-Linux-Kernel#feature-requests which is where I've opened this request.

**Comment by pmartincic** [comment]
Ahh, it wasn't clear to me that you're talking about the README in the other project. I updated the title to reflect that. I don't have access/control on that other repo. This is unfortunate because they point to us, they don't read our bugs unless we explicitly call them out, and I don't have access to their repo.

**Comment by ReneNyffenegger** [comment]
I see. thanks for clearing this up. I guess, it makes no sense then to keep this 'issue' open.
