### ISSUE TITLE
Increased memory in .wslconfig file not detected by Ubuntu or docker

### ISSUE THREAD

**Issue by madstist** [microsoft/WSL#10985]
### Windows Version

Microsoft Windows [Version 10.0.19045.3803]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### Repro Steps

1) I built the .wslconfig txt file in _C:\Users\myprofile\.wslconfig_ as follows:

```
[wsl2]
memory=20GB 
processors=4
swap=4GB
```
2) Saved it as .txt UTF w/o BOM. 
3) In Windows Powershell, I ran` wsl --shutdown `
4) Restarted Ubuntu, ran` free -mh` and did not see change in total memory.

### Expected Behavior

Increased memory limit for Docker container use to 20GB. I have enough free space on my laptop : 98.5GB

### Actual Behavior

After typing free -mh on Ubuntu terminal I see the following output: 
total        used        free      shared  buff/cache   available
Mem:           7.7Gi       433Mi       6.7Gi       3.0Mi       551Mi       7.0Gi
Swap:          2.0Gi          0B       2.0Gi

**Comment by OneBlue** [comment]
@madstist: The path to the config file is: C:\user\<user>\.wslconfig (extra '\'). If you move your config file there the changes should be picked up by WSL.
