### ISSUE TITLE
`/mnt/wsl` is uninitialized affecting `resolv.conf` with no visibility into why

### ISSUE THREAD

**Issue by Josh-Marshall-FactSet** [microsoft/WSL#11036]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

2.0.9, 2.0.14, 2.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.137.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04 LTS

### Repro Steps

I have uninstalled everything, followed the installation procedure here (https://learn.microsoft.com/en-us/windows/wsl/install#prerequisites) at `wsl --install` and I have my error.  `resolve.conf`, it is a dangling link.  This is because `/mnt/wsl` is not populated and appears to 'just' be uninitialized.  There is nothing in the Event Viewer about an error or issue.  No warnings from WSL.  No obvious errors in journalctl or systemctl services.  No errors from the WSL debug console except for the DNS lookup errors which are caused by the aforementioned missing `resolve.conf`.  I'm really at a loss here.

### Expected Behavior

`/mnt/wsl/resolv.conf` should exist with the header noting that it has been automatically generated by WSL and the typical DNS entries it populates.

### Actual Behavior

Absence of any behavior.

### Diagnostic Logs

Not yet applicable.  I require direction on what information to gather.

**Comment by Josh-Marshall-FactSet** [comment]
One thing of note during my day of debugging is that there are many, many pages of `resolve.conf` changing or getting over-written, but this is the first I've ran into of it missing.  If someone can point me to where the logging in for where WSL creates and updates files in `/mnt/wsl`, that is sure to make this bug easy.

**Comment by ivarprudnikov** [comment]
Posted my steps to regenerate resolv.conf in https://github.com/microsoft/WSL/issues/11928#issuecomment-2419664478
