### ISSUE TITLE
Installation of 2.1.0 does not remove all older installed wsl packages

### ISSUE THREAD

**Issue by janderssonse** [microsoft/WSL#11049]
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

2.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04.03

### Repro Steps

Having an older version of WSL installed, namely 5.10.16, https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=3a0c55a7-52db-4f8f-91bc-52683cf327cc. Install 2.1.0 with installer package or intune. Notice that 5.10.16 is still left dangling even though 2.1.0 succeded. 

### Expected Behavior

When installing 2.1.0 older wsl packages are removed, like in my case https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=3a0c55a7-52db-4f8f-91bc-52683cf327cc 5.10.16 update should not be left dangling.

### Actual Behavior

When installing 2.1.0 older wsl packages like 5.10.16 is left dangling,  which leaves an old wsl.exe under System32. This might lead to starting up ancient wsl-versions, depending on PATH-order etc. In my case wsl 2.1.0 is installed under Program Files/WSL/ which is not first in my PATH, so you can guess what happens (and with no admin rights, there is no possibilty to change PATH order either).

**Comment by janderssonse** [comment]
![bild](https://github.com/microsoft/WSL/assets/37870813/abfcb5c1-3d3e-4987-8960-79330408e601)


The dangling old component in red. This should not be left after installation of 2.1.0 and overshadows anything in "Program Files/WSL" due to being in "System32/wsl", i. e earlier in the default env PATHS. in windows.

**Comment by benhillis** [comment]
The component you have circled above is the kernel for the inbox version of WSL. This will be getting removed in the future once the lifted version of WSL is available everywhere.
