### ISSUE TITLE
Wireless tools not detecting adapters

### ISSUE THREAD

**Issue by PrivateHere** [Microsoft/WSL#1104]
I'd like to do advanced wireless monitoring with tools like ifconfig, airmon-ng, iwconfig, but none of them seem to recognize wireless adapters.

This is the output I receive for the following commands I'd like to use.

```
ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

airmon-ng


Interface       Chipset         Driver

iwconfig
eth0      no wireless extensions.

wifi0     no wireless extensions.

eth1      no wireless extensions.

eth2      no wireless extensions.

wifi1     no wireless extensions.

wifi2     no wireless extensions.

lo        no wireless extensions.

und0      no wireless extensions.

und1      no wireless extensions.

und2      no wireless extensions.

und3      no wireless extensions.

und4      no wireless extensions.

```

All the above output show that the software is working flawlessly but it cannot detect the wireless adapters I use. I have no problems with connecting to the internet on bash (Admin).

I have Microsoft Windows [Version 10.0.14393].

I'd like to know if I have to install these wireless adapters to the Windows subsystem for Linux shell and how I should.

**Comment by fpqc** [comment]
The way it works right now, the Win32-side networking settings control the kernel, which then controls the LX-side networking.  There are no real networking devices set up in /dev on the LX side, at the moment at least.

**Comment by misenesi** [comment]
We are aware of some of these tools not working and are actively looking into enabling more of these. Added a feature label to you bug. Could you please vote on [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)?

**Comment by Bazalia** [comment]
Yes I would like to have this feature too. Note I think you can vote [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17268656-add-wireless-device-support).

**Comment by IkiM0no** [comment]
Any progress on this since ~1 year has passed? Looking to use iwconfig.

**Comment by therealkenc** [comment]
Consolidating to #1077 which has a UserVoice [ref](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/17268656-add-wireless-device-support).

**Comment by DarthVader101** [comment]
and still no progress. any work around

**Comment by aoliaoliao** [comment]
and now, the [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) is 404

**Comment by DavidSamir** [comment]
any updates?

**Comment by RandomVersion** [comment]
any updates?

**Comment by batyrkanov** [comment]
any updates?

**Comment by map32** [comment]
any updates pls??

**Comment by Lightmarey** [comment]
any progress yet？

**Comment by hariadiarief** [comment]
is there any update 😢?

**Comment by morowenka** [comment]
rip progress...

**Comment by MKokeshi** [comment]
Any updates about this problem? How u can update all things but none of this problem?
lol

**Comment by hanzlahabib** [comment]
Oh, its almost about to cross 6 years no updates, wow

**Comment by KSriki** [comment]
Looks like Im just gonna boot up ubuntu

**Comment by SaturnineTitan** [comment]
I came here looking for a workaround but at least I'm not the only one with this problem 😄
