### ISSUE TITLE
Non-ASCII characters incorrectly encoded when piping to `clip.exe` or creating zip file

### ISSUE THREAD

**Issue by pcgaustad** [microsoft/WSL#11047]
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

WSL-versjon: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

```
$ zip --version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
...
```

### Repro Steps

In Ubuntu, pipe `å` (`U+00E5`, encoded as `0xc3 0xa5` in UTF-8) to `clip.exe` and read the contents.

```bash
$ printf "å" | clip.exe && powershell.exe -noprofile -command Get-Clipboard
```

### Expected Behavior

Command output: `å`

### Actual Behavior

Command output: `├Ñ`.

These characters happen to correspond to the code points `0xc3 0xa5` in Code page 437 and 850 (among others):

```bash
$ printf "\xc3\xa5" | iconv -f 437
├Ñ
```

Non-ASCII characters are displayed correctly in Windows Terminal. When I copy text directly from the terminal window, the encoding is also correct. But not when piping to `clip.exe`.

Also, when I create a zip archive in Ubuntu and open it in File Explorer, non-ASCII characters in file names are encoded incorrectly, e.g. `aaåaa` becomes `aa├Ñaa`. If I force `unzip` with `-U` to escape all non-ASCII characters from UTF-8 coded filenames, the `å` is not escaped.

```bash
$ touch aaåaa
$ zip test aaåaa
  adding: aaåaa (stored 0%)
$ zipinfo -U test.zip
Archive:  test.zip
Zip file size: 162 bytes, number of entries: 1
-rw-r--r--  3.0 unx        0 bx stor 24-Jan-19 22:40 aaåaa
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%
```

I'm running Ubuntu 22.04 WSL on another computer (previously Windows 10, now Windows 11) without encoding problems with `clip.exe`. On that computer, file names in zip files are encoded correctly when I open them in File Explorer. And `unzip -U` returns escaped non-ASCII characters:

```
Zip file size: 162 bytes, number of entries: 1
-rw-r--r--  3.0 unx        0 bx stor 24-Jan-19 22:41 aa#U00e5aa
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%
```

I have not been able to pin down the cause of the problem by comparing the two environments: In both instances, `locale charmap` in Ubuntu outputs `UTF-8` and `[System.Text.Encoding]::Default` in PowerShell outputs:

```posh
IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252
```

If I convert a string to UTF16LE encoding before I pipe it to `clip.exe`, the clipboard contents is correctly encoded in both environments. However, this step in necessary only in the environment with encoding problems.

```bash
$ echo "å" | iconv -t UTF16LE | clip.exe && powershell.exe -noprofile -command Get-Clipboard
å

```

Probably unrelated: When I create an empty file `aaåaa.txt` in File Explorer, right click and select "Compress to ZIP file", there is an encoding problem in both environments: `aaåaa.txt` becomes `aaЖaa.txt`:

```
$ zipinfo -U aaåaa.zip
Archive:  aaåaa.zip
Zip file size: 116 bytes, number of entries: 1
-rw-a--     2.0 fat        0 b- stor 24-Jan-19 22:56 aaЖaa.txt
1 file, 0 bytes uncompressed, 0 bytes compressed:  0.0%
```

**Comment by pmartincic** [comment]
This is well written, thanks for writing this up! I'm not immediately sure what to do about this, but I'll think about it.

**Comment by kneckehexan** [comment]
I stumbled across this because I had issues with neovim's copy to clip.exe and later pasting the characters "å", "ä" and "ö". I'm also on WSL2 (Windows 11) and could reproduce the behavior above.

However, after changing the system language to use _Beta: Use Unicode UTF-8 for global language support_ in **settings -> time and language -> administrative language settings -> administrative settings -> change system language** I could use Å Ä Ö. Tried
`printf "å" | clip.exe && powershell.exe -noprofile -command Get-Clipboard`
and the result was å.

My Windows isn't in English, so the path above is a translation by me, i.e. actual path might be slightly different.

**Comment by pmartincic** [comment]
I'm not sure that this is a solvable problem. When the output is going to stdout/err on the console we know it needs to be converted to the output format. If it is being redirected to another program, I don't think the interop utility should be make decisions to convert data that may not even be human readable. `cat somedatafile` getting piped to an interop process for instance. I think us adding heuristics to do that would make things even more confusing.

**Comment by justhalf** [comment]
@kneckehexan thanks, that's a solution that works for me (Windows 10, wsl2, copying from Vim to clipboard via clip.exe). So it's a solvable problem via the system, not from WSL 😀

**Comment by jalal-o** [comment]
i found a solution via iconv

`tree | iconv -f utf8 -t utf16le | clip.exe`

**Comment by beyarkay** [comment]
If anyone comes here wishing vim-under-wsl would copy things to the system clipboard:

```viml
" Yank -> Windows clipboard via iconv + clip.exe (WSL)
if executable('clip.exe') && executable('iconv')
  let s:CLIP_CMD = 'clip.exe'
  let s:ICONV_CMD = 'iconv -f utf8 -t utf16le'

  function! s:SendToWindowsClipboard() abort
    " Read unnamed register (yank target)
    let l:reg_text = getreg('"')
    if empty(l:reg_text)
      return
    endif

    " Determine register type and ensure linewise yanks keep a trailing newline
    let l:reg_type = getregtype('"')
    if l:reg_type ==# 'V'
      let l:payload = l:reg_text . "\n"
    else
      let l:payload = l:reg_text
    endif

    " Pipe through iconv to produce UTF-16LE then send to clip.exe
    call system(s:ICONV_CMD . ' | ' . s:CLIP_CMD, l:payload)
  endfunction

  augroup YankToWinClipboard
    autocmd!
    autocmd TextYankPost * call s:SendToWindowsClipboard()
  augroup END
endif
```
Add to your .vimrc and it should just work.
