### ISSUE TITLE
WSL2 uses Windows Region or Region Format as display language, instead of Windows Display Language

### ISSUE THREAD

**Issue by stefan-oskamp** [microsoft/WSL#11051]
### Windows Version

Windows 11 23H2

### WSL Version

2.0.14

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Fedora 39

### Repro Steps

1. Set your Windows Display Language to e.g. English (United States).
2. Set your Windows Region to e.g. Germany
3. Set your Windows Regional Format to e.g. German (Germany)
4. Open cmd.exe and run `wsl --help`

### Expected Behavior

Wsl.exe should use the Windows Display Language as its display language.

### Actual Behavior

Wsl.exe uses either the Windows Region or Regional Format setting as its display language.

**Comment by stefan-oskamp** [comment]
Comments in #9242 come to the same conclusion,, but the issue is still not fixed since more than a year.

**Comment by OneBlue** [comment]
Fixed in [2.1.3](https://github.com/microsoft/WSL/releases/tag/2.1.3)
