### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/0x80070032

### ISSUE THREAD

**Issue by Bahtiyar57** [microsoft/WSL#11052]
I downloaded from [here](https://learn.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions) Debian.
Extracted the files from the donwloaded file to my external hard drive (K:) and run debian.exe .
It started successfully. So it was possible to start WSL from my hard drive.
The files contained in _ext4.vhdx_

My intention now is to start WSL with Debian from NAS.
But it seems that it is not possible to mount the _ext4.vhdx_ from a NAS drive.

Is theree any other option to realize booting WSL from a NAS drive?

**Comment by DK-DARKmatter** [comment]
Hi, I got the same issue, have you solved this problem?
