### ISSUE TITLE
Cannot launch GUI apps since 2.0.12

### ISSUE THREAD

**Issue by dciarniello** [microsoft/WSL#11064]
### Windows Version

11

### WSL Version

2.1.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Since v2.0.12 of WSL, it has not been possible to launch GUI apps without jumping through hoops.  This issue was reported here but the issue was moved to WSLg (https://github.com/microsoft/wslg/issues/1156).  The issue is not, however, a WSLg issue but a WSL issue as the problem appeared with 2.0.12 which had no WSLg-related changes.
The problem looks to have been introduced with the "fix" to https://github.com/microsoft/WSL/issues/10818.

https://github.com/microsoft/wslg/issues/1156, amongst others, has the details of the workaround that is required to be able to launch GUI apps.

### Expected Behavior

GUI apps start as usual

### Actual Behavior

GUI apps do not start

**Comment by OneBlue** [comment]
Closing since there is no repro instruction nor error message.

**Comment by dciarniello** [comment]
Pointing the to the ticket that does have the repro instructions was not enough?  I would have updated this ticket if asked.
