### ISSUE TITLE
docker failed to create task for container

### ISSUE THREAD

**Issue by yikuo123** [microsoft/WSL#11060]
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Oracle Linux 7.9

### Other Software

Docker version 24.0.7, build afdd53b

### Repro Steps

run `docker run --rm hello-world`

### Expected Behavior

print "Hello world!"

### Actual Behavior

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit "docker-95d983a7d1475f549f8d7dcf631602f41da6d9cef9469cd8911c60e680ac2d41.scope" (properties [{Name:Description Value:"libcontainer container 95d983a7d1475f549f8d7dcf631602f41da6d9cef9469cd8911c60e680ac2d41"} {Name:Slice Value:"system.slice"} {Name:Delegate Value:true} {Name:PIDs Value:@au [1467]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): Cannot set property IOAccounting, or unknown property.: unknown.

**Comment by OneBlue** [comment]
Thank you @yikuo123. Unfortunately I'm not seeing anything abnormal in the logs. Do you have other WSL distributions, and if so, do they work properly ?

**Comment by OneBlue** [comment]
Thank you for confirming. In this case I recommend raising the issue with them, since it looks like WSL is functionning properly on your machine.
