### ISSUE TITLE
wsl --update not possible after initial installation without admin rights- Initial wsl --update works

### ISSUE THREAD

**Issue by ropetry** [microsoft/WSL#11065]
### Windows Version

Microsoft Windows 22H2 19045.3930

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22 

### Repro Steps

Activate Features and do an update for wsl with "wsl --update" ... do it one more time to get latest version and you get an error. first update works. second displays error.

--------------------
Features enabled via powershells script from admin context:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform

---- switching now to normal user with cmd
C:\Users\user>wsl --status
Standard Distribution: Ubuntu-22.04
Standardversion: 2

the Windows-Subsystem for Linux was last updated on 11.07.2023
auto updates enabled.

Kernel-Version: 5.10.102.1

C:\Users\user>wsl --update
Installation: Windows-Subsystem für Linux
Windows-Subsystem for Linux was installed.

C:\Users\user>wsl --status
Standard-Distribution: Ubuntu-22.04
Standardversion: 2

C:\Users\user>wsl --version
WSL-Version: 2.0.9.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.3930

doing the wsl --update again to get latest version and not stay on 2.0.9.0 -->

C:\Users\user>wsl --update
searching for Updates.
Windows-Subsystem for Linux will get updated to Version 2.0.14 .

Action needs elevated rights.
blocked by GroupPolicy by Administrator
this programm was blocked by a group policy. please contact your Systemadministrator for further informations.
Error code: Wsl/UpdatePackage/ERROR_ACCESS_DISABLED_BY_POLICY

from event log i see the first wsl --update installs version 2.0.9.0:
Windows Installer Action ended: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_2.0.9.0_x64__8wekyb3d8bbwe\wsl.msi. Clientprozess-ID: 35780.

### Expected Behavior

should update wsl to latest version without admin rights, from a user session every time the users enters
wsl --update

### Actual Behavior

wsl --update drops an error and needs "elevated" rights to update from the initial installation to the latest

**Comment by pmartincic** [comment]
Note to future me, could not repro on 26039.1001.amd64fre base2_hyp.240122-1813_client_enterprise_en-us_vl

**Comment by OneBlue** [comment]
@ropetry Unfortunately this is by design. It looks like WSL has been disabled by policy on your machine, you might need to contact your network administrator to resolve this.
