### ISSUE TITLE
Install WSL command step: wsl --list --online => Access is denied. 

### ISSUE THREAD

**Issue by pekuz** [microsoft/WSL#11063]
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

Invalid command line option: --version

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Other Software

Docker Desktop 4.25.0 

### Repro Steps

I have followed https://docs.docker.com/desktop/install/windows-install/ and https://learn.microsoft.com/en-us/windows/wsl/install.

In the first Install WSL command step I had to resort to the note

> The above command only works if WSL is not installed at all. If you run wsl --install and see the WSL help text, please try
> running wsl --list --online to see a list of available distros ...

from run as administrator PS getting:

    wsl --list --online
    Access is denied. 

from regular PS getting (i.e. deviating from the install steps):

    wsl --list --online
    The following is a list of valid distributions that can be installed.
    Install using 'wsl --install -d <Distro>'.

    NAME                                   FRIENDLY NAME
    Ubuntu                                 Ubuntu
    ...

I eventually want to use Docker Desktop as a regular user but I'm puzzled why  https://learn.microsoft.com/en-us/windows/wsl/install requests the administrator mode and in that mode it fails with: *Access is denied.*.   

BTW I speculatively continued https://docs.docker.com/desktop/install/windows-install/ but Docker Desktop does not start, no errors, everything success but it does not start. So back at WSL as this early problem cannot be apparently ignored. 

#10475 has similar symptom but does not look like the duplicate.

### Expected Behavior

    wsl --list --online
    The following is a list of valid distributions that can be installed.
    Install using 'wsl --install -d <Distro>'.

    NAME                                   FRIENDLY NAME
    Ubuntu                                 Ubuntu
    ...

### Actual Behavior

    wsl --list --online
    Access is denied.

**Comment by pmartincic** [comment]
Are you intentionally using WSL1 instead of WSL2?

**Comment by pekuz** [comment]
Docker Desktop for Windows recommends WSL 2.  The install steps I have followed should install WSL 2. (I have followed https://docs.docker.com/desktop/install/windows-install/ and https://learn.microsoft.com/en-us/windows/wsl/install.) I got stuck at the *Install WSL command* section of wsl/install.

When reporting this *Access is denied* issue , I had to fill the *WSL version* field  and I got:

    wsl --version
    Invalid command line option: --version

I matched against troubleshooting https://learn.microsoft.com/en-us/windows/wsl/troubleshooting but to no avail.

As newcomer being stuck I could not answer the *Are you using WSL 1 or WSL 2?* field so nothing is ticked there.

Anyway my intent is WSL 2.
