### ISSUE TITLE
Unable to access VPN from WSL2 when networking mode set to `mirrored`

### ISSUE THREAD

**Issue by AlexandreDenis** [microsoft/WSL#11072]
### Windows Version

Microsoft Windows [version 10.0.22631.3007]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu-20.04

### Repro Steps

1. Connect to VPN on Windows
2. Set networking mode to `mirrored` in .wslconfig file on Windows
3. Relaunch WSL
4. From WSL, try to ping any private IP address of the VPN. It does not work anymore while it was working with default networking mode

### Expected Behavior

I would have expected to be able to access to VPN connection from WSL

### Actual Behavior

Ping command to any private IP address of the VPN fails

**Comment by Tofu-AKI** [comment]
though don't know why, trying to manually install it really worked. the conclusion I came to after trying for several days.

**Comment by tomadimitrie** [comment]
Same issue here. Any workaround yet?

@Tofu-AKI sorry, but I don't understand what you mean. How did you solve it?

**Comment by rayae** [comment]
Thanks to @tomadimitrie, I tried Viscosity and it worked well.

**Comment by yakuninmax** [comment]
I'm using the latest version of WSL, mirroring mode. OpenVPN Connect 3 works with ipv6, but does not work with ipv4, Viscosity, on the contrary, works with ipv4, but does not work with ipv6 :)

**Comment by dangaogit** [comment]
Hello, is there any progress on this issue at the moment?

**Comment by CatalinFetoiu** [comment]
hi, can you please collect logs using instructions below?

please do the following:
Run https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1
disconnect VPN
run "wsl --shutdown"
start WSL
connect VPN
reproduce the issue
stop collect-networking-logs.ps1 and share the generated zip

please also refer to https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues before running the script - you need to install tcpdump and WPR.

what is the name of the VPN product you are using?

**Comment by dangaogit** [comment]
@CatalinFetoiu 
use OpenVPN Connect 3.4.4
The collected networking logs are too large to upload.

**Comment by CatalinFetoiu** [comment]
@dangaogit thanks for following up
unfortunately at the moment openvpn is known to be incompatible with mirrored mode networking. this is tracked in #10879 

/dupe #10879
