### ISSUE TITLE
WSL command line displays in wrong language

### ISSUE THREAD

**Issue by black-pwq** [microsoft/WSL#11087]
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

unrelated

### Distro Version

unrelated

### Repro Steps

Simply type `wsl --help` and observe the displayed language. (not the language inside a distro)

In my case, it is Chinese which isn't consistent with my display language:
```
PS > wsl --help
版权所有 (c) Microsoft Corporation。保留所有权利。
有关此产品的隐私信息，请访问 https://aka.ms/privacy。

用法: wsl.exe [参数] [选项...][命令行]

运行 Linux 二进制文件的参数:

   如果未提供命令行，wsl.exe 将启动默认 shell。
blabla...
```

It showed in correct language (i.e. the display language set on my machine which is English) at the first time I installed it via command line. However, the command line result is present in Chinese after I type `wsl --update` now. 

Few things may help locate the issue:
- The display language and preferred language of the current user are both English, though I use Chinese as my secondary language.
  <img width="765" alt="image" src="https://github.com/microsoft/WSL/assets/105478488/1af4cd1c-0034-42a4-8676-bfd40ae579a0">
- DISM may give more info:
  ```sh
  PS > dism /online /get-intl
  
  Deployment Image Servicing and Management tool
  Version: 10.0.19041.3636
  
  Image Version: 10.0.19045.3930
  
  Reporting online international settings.
  
  Default system UI language : zh-CN
  The UI language fallback is : en-US
  System locale : zh-CN
  Default time zone : China Standard Time
  Active keyboard(s) : 0409:00000409, 0804:{6A498709-E00B-4C45-A018-8F9E4081AE40}{82590C13-F4DD-44F4-BA1D-8667246FDF8E}, 0804:{81D4E9C9-1D3B-41BC-9E6C-4B40BF79E35E}{FA550B04-5AD7-411F-A5AC-CA038EC515D7}
  Keyboard layered driver : Not installed.
  
  Installed language(s): en-US
    Type : Fully localized language.
  Installed language(s): zh-CN
    Type : Partially localized language, MUI type.
    Fallback Languages en-US
  
  The operation completed successfully.
  ```
- All of other built-in commands, like `winget` or `ping` shows the result in English which is expected.

### Expected Behavior

Show the correct language according to the display language in the current user settings.

### Actual Behavior

Display in the wrong language as discussed above.

**Comment by OneBlue** [comment]
Solved with [2.0.15](https://github.com/microsoft/WSL/releases/tag/2.1.5)
