### ISSUE TITLE
Help! Three whole days. WSL is E...

### ISSUE THREAD

**Issue by GiantKs** [microsoft/WSL#11083]
### Windows Version

Microsoft Windows [版本 10.0.19045.3996]

### WSL Version

WSL version： 2.1.1.0 core： 5.15.146.1-2 

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [x] WSL 1

### Kernel Version

5.15.146.1-2    default: 2  

### Distro Version

Ubuntu-20.04

### Other Software

WSLg ： 1.0.60 MSRDC version： 1.2.5105 Direct3D version： 1.611.1-81528511 DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version： 10.0.19045.3996

### Repro Steps

1: First of all, there is no hyper option in the startup or shutdown options, manually install hyper and other related components and restart the computer;
2: : WSL and virtual platform are selected and restarted
3: wsl --install -d Ubuntu-20.04
4: Perform numerous restarts and reinstallations
5: update Various updates have also been made

### Expected Behavior

into linux ... input nikename ...

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8000000d
Error: 0x8000000d ???????????
or
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800070424

### Diagnostic Logs

na

**Comment by GiantKs** [comment]
Do I need to install hyper in the end? There is no Hyper. If not, how can I uninstall it..

**Comment by GiantKs** [comment]
info: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 2.70 GHz

**Comment by GiantKs** [comment]
INFO:

**Comment by GiantKs** [comment]
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 2.70 GHz;    RAM : 4GB(3.87GB);

**Comment by GiantKs** [comment]
@echo off
net.exe session 1>NUL 2>NUL && (
    goto as_admin
) || (
    goto not_admin
)

:as_admin
pushd "%~dp0"
dir /b %SystemRoot%\servicing\Packages\*Hyper-V*.mum >hyper-v.txt
for /f %%i in ('findstr /i . hyper-v.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i"
del hyper-v.txt
Dism /online /enable-feature /featurename:Microsoft-Hyper-V -All /LimitAccess /ALL 
echo xxx！

:not_admin
echo xxx

:end
pause


Use the above command to install hyper alone, so silly = =...

**Comment by GiantKs** [comment]
hello?

**Comment by sirredbeard** [comment]
You do not need Hyper-V to run WSL 2, just WSL and Virtual Machine Platform.

I see you are getting errors:
`WslRegisterDistribution failed with error: 0x8000000d` and `WslRegisterDistribution failed with error: 0x800070424`.

How are you installing your WSL distro?

Are you running any third-party security software?

Can you please collect and post /logs?
