### ISSUE TITLE
 Segmentation fault when using conda

### ISSUE THREAD

**Issue by aiVoyager** [microsoft/WSL#11094]
### Description

I am encountering a segmentation fault error when using Conda on Windows Subsystem for Linux (WSL). This issue persists across different Ubuntu distributions (Ubuntu 22.04 LTS and Ubuntu 20.04) and both WSL versions (WSL 1 and WSL 2). The error predominantly occurs when I attempt to create a new Conda environment with a specified Python version using the conda create command. However, the command occasionally succeeds without any apparent reason, adding to the unpredictability of the issue.

### Windows Version

Microsoft Windows [Version 10.0.22621.3085]

### WSL Version
```bash
WSL version: 2.1.1.0 
Kernel version: 5.15.146.1-2 
WSLg version: 1.0.60 
MSRDC version: 1.2.5105 
Direct3D version: 1.611.1-81528511 
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22621.3085
```
### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 5.15.146.1-microsoft-standard-WSL2 (root@65c757a075e2) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Jan 11 04:09:03 UTC 2024

### Distro Version

Ubuntu 20.04

### Repro Steps

* install conda
```bash
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
bash Miniforge3-$(uname)-$(uname -m).sh
source ~/.bashrc
```
* create env
```bash
conda create -n myenv python=3.10
```

### Expected Behavior

The commands runs correctly without bugs.

### Actual Behavior

Segmentation fault

### Diagnostic Logs
```bash
(base) wsl@DESKTOP-V0DJDRP:~$ conda create -n bid python=3.10
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - Segmentation fault
```
_No response_

**Comment by aiVoyager** [comment]
I'm uncertain whether this is pertinent, but I stumbled upon a similar issue where a user's laptop had more memory installed than what was supported by their mainboard. A related discussion can be found here: [WSL #6325](https://github.com/microsoft/WSL/issues/6325).

For my setup, I have equipped my system with 128GB of memory, and I am using a Z690-A motherboard, which is compatible with up to 128GB of memory. This leads me to question the memory support in WSL—specifically, is there official support or any known limitations when using 64GB or 128GB of memory with WSL?

**Comment by pmartincic** [comment]
You've established that the conda application seg faults. That's not much for us to go on and is sparse little to start an investigation with. You should start an investigation with the application developer: https://github.com/conda/conda, if it turns out that they need something from us, they can come back to us with more descriptive bug.

**Comment by elsaco** [comment]
@aiVoyager here are the memory limitations in WSL `50% of total memory on Windows or 8GB, whichever is less; on builds before 20175: 80% of your total memory on Windows`

See details at https://learn.microsoft.com/en-us/windows/wsl/wsl-config

Try to find what's core dumping on your WSL image. Didn't repro on a  new Focal image:

```
elsaco@texas:~$ conda env list
# conda environments:
#
myenv                    /home/elsaco/.conda/envs/myenv
base                     /opt/miniforge3

elsaco@texas:~$ conda activate myenv
(myenv) elsaco@texas:~$ python --version
Python 3.10.13
(myenv) elsaco@texas:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
```
