### ISSUE TITLE
WSL update not working on 26020-26040

### ISSUE THREAD

**Issue by ErikMoreau** [microsoft/WSL#11101]
### Windows Version

26040.1000

### WSL Version

2.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu-22.04

### Repro Steps

running WSL --update or WSL --update --pre-release

### Expected Behavior

update is succesfull, new wsl version is disaplyed when running wsl --version

### Actual Behavior

seems goes through the updates steps, no errors

wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.14.

wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.1.

wsl --version
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.26040.1000

### Diagnostic Logs

repro recording with feedback hub: https://aka.ms/AAotrdo

**Comment by Bai-Jinlin** [comment]
same issue
```bash
❯ sudo wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.1.

❯ wsl --version
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.3085

❯ wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.1.
Update failed (exit code: 1603).
Log file: C:\Users\windo\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/E_ABORT
```

**Comment by OneBlue** [comment]
This is unfortunately a known issue when upgrading from 2.0.0. The easiest way to fix this is to manually download and install the latest [MSI package](https://github.com/microsoft/WSL/releases/download/2.1.1/wsl.2.1.1.0.x64.msi)

**Comment by ErikMoreau** [comment]
That does indeed solve the issue Thanks!
