### ISSUE TITLE
IRQL_NOT_LESS_OR_EQUAL BSOD a few times a day

### ISSUE THREAD

**Issue by QAnders** [microsoft/WSL#11108]
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

1.2.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop v4.17.1
VSCode 1.83.1

### Repro Steps

Well... I just fiddle around in WSL for some time and then boom, goes the BSOD

### Expected Behavior

Not to BSOD

### Actual Behavior

BSOD between 1-4 times daily. Not due to load, file operations or anything in particular that I can pinpoint and it happens whether or not I am actually using WSL2 actively. WSL2 is loaded though, all days, every day and Docker Desktop and VSCode are active all day as well. 

### Diagnostic Logs

```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

IRQL_NOT_LESS_OR_EQUAL (a)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If a kernel debugger is available get the stack backtrace.
Arguments:
Arg1: ffffc06673fe4578, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff806600ae57d, address which referenced memory

Debugging Details:
------------------


BUGCHECK_CODE:  a

BUGCHECK_P1: ffffc06673fe4578

BUGCHECK_P2: 2

BUGCHECK_P3: 0

BUGCHECK_P4: fffff806600ae57d

PROCESS_NAME:  wsl.exe

SYMBOL_NAME:  nt!MiWalkVaCheckCommon+1d

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

FAILURE_BUCKET_ID:  AV_nt!MiWalkVaCheckCommon

FAILURE_ID_HASH:  {18f0f161-6c2c-5db0-d879-b666add2f2f6}

Followup:     MachineOwner
---------
```

**Comment by benhillis** [comment]
Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.
