### ISSUE TITLE
Path sanitation might changes the desired file name

### ISSUE THREAD

**Issue by Grarie** [microsoft/WSL#11104]
### Windows Version

Microsoft Windows [Version 10.0.23620.1000]

### WSL Version

2.1.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. In powershell create files foo.txt and .foo.txt. The exact filenames don't matter but the second filename has to be the first file name with a dot added to the front.
```
echo "bar" > foo.txt
echo "not bar" > .foo.txt
```
2. Try to access the file with a linux tool from outside via WSL and reference it with leading `.\`
```
wsl cat .\foo.txt
```

### Expected Behavior

I'd expect the output to be either an error or to see the contents of foo.txt
```
> wsl cat foo.txt
bar
> wsl cat .\foo.txt
bar
```

### Actual Behavior

The actual behaviour is that no error is thrown but the results of both commands are different:
```
> wsl cat foo.txt
��bar
> wsl cat .\foo.txt
��not bar
```
(The BOMs at the beginnig are due to the use of Windows Powershell and not related to the problem. It works without BOM but still different outputs in Powershell 7.4.1.)

So it seems to me, that `.\foo.txt` is being processed to be understandable by linux so the `.\` is to be replaced. For some reason it seems to remove the backslash but keeps the dot. It should either remove both (or change the backslash to a slash) or none.

**Comment by OneBlue** [comment]
@Grarie: This is because of shell expansion. You can get this working by running wsl like this: 

```
wsl --shell-type none cat .\foo.txt
```

**Comment by Grarie** [comment]
Thanks for the hint! I agree.

For anyone stepping into this:
I also found out that I had a misconception. The script (here `cat .\foo`) is handed over to wsl as-is.
I didn't recognise that because bash (within wsl) doesn't err given a windows path as stated. It just interprets `\f` as an escaped character. So the result is indeed the same as `cat .foo.txt`. So there is no problem on the wsl side.
