### ISSUE TITLE
After update HCS_E_HYPERV_NOT_INSTALLED

### ISSUE THREAD

**Issue by SirLouen** [microsoft/WSL#11117]
### Windows Version

10.0.22631.3007

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. Virtual Machine Platform is installed
2. VT is enabled on BIOS
3. Hyper-V IS NOT INSTALLED`(and I won't be installing because I don't need Hyper-V and AFAIK, is not needed for WSL2)

### Expected Behavior

Ubuntu VM starts on command

### Actual Behavior

Everything was running perfect (except for one minor bug with some graphics glitch I wanted to solve). I updated to latest 2.0.14.0 WSL version with `wsl --update` and the issue started from there.

When I start the VM with Ubuntu, it fails with the error:
`Error code: Wsl/Service/CreateInstance/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED`

### Further information

I'm using an Android Emulator called MuMu, which happens to disable Hyper-V. I don't have the Hyper-V libraries installed (in Features) but I only have Virtual Machine Platform. 

I tried to uninstall -> Reboot -> and then reinstall -> Reboot, the  Virtual Machine Platform and it happened to work again the WSL2, but as soon as I go into MuMu it says that Hyper-V has been enabled with the Virtual Machine Platform. So I must assume that despite of not installing the specific features of Hyper-V the Virtual Machine Platform HAS Hyper-V by Default

Conclusion: WSL2 **does not,** work without Hyper-V, despite I've read that it does. It seems that there is a subset of Hyper-V inside Virtual Machine Platform. Very unfortunate I could not use WSL2 anymore, while using Android instances with Intel's VT Virtualization platform (what MuMu emulator uses)

**Comment by SirLouen** [comment]
I've updated the original report with **Further Information** to clarify a situation that I have encountered. Maybe it could be useful to get some extra answers to dig further, or maybe it's plain impossible to run WSL2 under the circumstances described, and this issue can be closed.

**Comment by benhillis** [comment]
MuMu uses a hypervisor that is not compatible with Hyper-V's hypervisor. This is by design.

**Comment by SirLouen** [comment]
> MuMu uses a hypervisor that is not compatible with Hyper-V's hypervisor. This is by design.

Yes, that was my original question: Hyper-V is actually a full requirement for WSL2, right?
I was reading in this issue that it wasn't
https://github.com/MicrosoftDocs/WSL/issues/899

But maybe the answers were biased.

**Comment by 4use2** [comment]
Win+R: optional-features, then set checkbox for hyper-V
