### ISSUE TITLE
File Systems mounted on junctions fail

### ISSUE THREAD

**Issue by d3x0r** [microsoft/WSL#11118]
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Arch Linux

### Other Software

n/a

### Repro Steps

https://github.com/microsoft/WSL/issues/3759 Previously reported, and not fixed.

```
mkdir c:\general
mkdir c:\general\work

```
create VHD
mount VHD on a folder c:\general\work

in WSL go to /mnt/c/general/work  and get Input/output error

```
[d3x0r@tundra sack-gui]$ ls /mnt/c/general/work
ls: cannot access '/mnt/c/general/work': Input/output error
```

### Expected Behavior

Use folder like any other folder on system.

### Actual Behavior

Unable to access partitions mounted on folders as a junction.

**Comment by OneBlue** [comment]
Thank you @d3x0r. The fix for this should be in the latest insider build now (22635.3350  has the fix).
