### ISSUE TITLE
Invalid command line argument: -–import

### ISSUE THREAD

**Issue by johnwspirent** [microsoft/WSL#11126]
### Windows Version

Microsoft Windows [Version 10.0.22631.3085]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

n/a

### Other Software

none

### Repro Steps

I am trying to import a .tar based on Debian. The "--import" doesn't work at all for me, although it does for a colleague. Entering "wsl --import" with or without additional arguments returns "Invalid command line argument: -–import" error. 

### Expected Behavior

Enter "wsl -–import" in a PowerShell with admin rights. I would expect to see the "--help" text because the command arguments are missing.

Enter "wsl --import" with correct arguments and I would expect the .tar file to be import.

Enter "wsl --help" and I would to see help text.

### Actual Behavior

I see an "Invalid command line argument" error for import:

_PS C:\svn\wsl_images> wsl -–import
Invalid command line argument: -–import
Please use 'wsl.exe --help' to get a list of supported arguments._

"wsl --help" is working for me now, but even this stopped working for some time. I have no idea why it stopped working or why it started working again:

_PS C:\svn\wsl_images> wsl -–help
Invalid command line argument: -–help
Please use 'wsl.exe --help' to get a list of supported arguments._

**Comment by 0xbadfca11** [comment]
You are mixing a hyphen(-) and an EN DASH(–).
