### ISSUE TITLE
\\wsl.localhost\ not accessible from sshd on windows

### ISSUE THREAD

**Issue by anatawa12** [microsoft/WSL#11120]
### Windows Version

Microsoft Windows [Version 10.0.22631.3085]

### WSL Version

wsl.exe --version

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu-22.04

### Other Software

OpenSSL SSH Server installed with `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`

### Repro Steps

1. configure & launch ssh server on windows
2. start wsl
3. connect to the ssh server on windows
4. run ls '\\wsl.localhost\Ubuntu-22.04' on the ssh connection

### Expected Behavior

show list of files of '/' of Ubuntu

### Actual Behavior

```
> ls '\\wsl.localhost\Ubuntu-22.04'
Get-ChildItem: Cannot find path '\\wsl.localhost\Ubuntu-22.04' because it does not exist.
```

### Diagnostic Logs

See #8697. Exactly same issue.

**Comment by anatawa12** [comment]
https://github.com/microsoft/WSL/issues/11120#issuecomment-1925147119
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!

https://github.com/microsoft/WSL/issues/8697#issuecomment-1921175131
> If you're still experiencing this issue please re-file this as a new issue or feature request.


Which is true? Should I close this issue and add :+1: to #8697? or keep this issue opened?

**Comment by pmartincic** [comment]
Those shares/targets/net-roots are namespaced on per user basis. Multiple users can run wsl with a given distro. Do you know what session the ssh daemon is running in? If it's not running in the same session as the user you're not going to see this, and I'd classify this behavior as intentional.
