### ISSUE TITLE
VScode WSL Remote open very slowly

### ISSUE THREAD

**Issue by disloot** [microsoft/WSL#11133]
### Windows Version

Microsoft Windows [version 10.0.22621.3085]

### WSL Version

2.1.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Debian

### Repro Steps

 My WSL Remote opens very slowly and it takes a long time for files to load. I tried disabling the network proxy, but the problem persisted. When I checked the network information in WSL, I found there was a VMware virtual network card inside. I tried uninstalling the virtual network card, and then the problem was resolved. The connection speed became very fast.

### Expected Behavior

I want to know if the virtual network card will affect the connection of WSL Remote.

### Actual Behavior

after uninstalling the virtual network card, it fixed.
 ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 2c:f0:5d:9c:1f:3c brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.7/24 brd 192.168.3.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
5: loopback0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:16:a4:fd brd ff:ff:ff:ff:ff:ff

**Comment by OneBlue** [comment]
@disloot: Can you share /logs of WSL being slow to start ? Do you see this behavior when you start wsl with wsl.exe as well or is this specific to vscode ?
