### ISSUE TITLE
Memory not returned back from swapfile

### ISSUE THREAD

**Issue by JannikSchneider12** [microsoft/WSL#11132]
### Windows Version

Microsoft Windows [Version 10.0.22631.3085]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

-Define swapspace in wsl.config
-Run application that uses swapspace

### Expected Behavior

-Memory should be returned back when finished or at the next start of the system

### Actual Behavior

-Memory is not returned

**Comment by JannikSchneider12** [comment]
Hello,

It says that I should reproduce the problem and then save the logs. However in my case there is no single step to reproduce the problem since there is the existing swap file and it doesn't return memory back. I think it is the same problem as with the vhdx from wsl itself, which has been a problem for a long time until it has been solved with the SparseVhd parameter. However for the swapfiles, there is no such parameter and one has to delete the swapfile manually when it gets too large

**Comment by benhillis** [comment]
@JannikSchneider12 - can you clarify what you mean by "does not reclaim the memory back"? Are you referring to the swap vhd  disk that is created?
