### ISSUE TITLE
How do I keep My WSL 2 Host from disconnecting the Remote SSH Session from  VS Code

### ISSUE THREAD

**Issue by grahama1970** [microsoft/WSL#11134]
### Windows Version

Windows 10 Build 19045

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

VS Code (on macbook) running SSH Remote Extension into a PC Host running WSL 2

### Repro Steps

My remote session times out every 3-4 mintutes regardless of the client or server side configs.
on WSL 2 Host
sudo nano /etc/ssh/sshd_config
ClientAliveInterval 160
ClientAliveCountMax 120

On VS Code client (on my macbook)
Host Ubuntu 
    HostName my_host_name
    User my_user_name
    IdentityFile ~/.ssh/my_key
    RemoteCommand wsl
    ServerAliveInterval 60
    ServerAliveCountMax 120

### Expected Behavior

I expect the SSH session to hold on for dear life and never drop a running session unless I manually close it. 

### Actual Behavior

It times out every 3-4 minutes and has to reload..

**Comment by OneBlue** [comment]
@grahama1970: If you don't want WSL to time out, you can write: 

```

[wsl2]
vmIdleTimeout=-1
```

in .wslconfig. With this WSL will never time out.

**Comment by grahama1970** [comment]
Thank you.

**Comment by joekiller** [comment]
`vmIdleTimeout=-1` per https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings

**Comment by OneBlue** [comment]
Thank you. Edited the original message
