### ISSUE TITLE
WSL exits with Catastrophic failure

### ISSUE THREAD

**Issue by isurugiu** [microsoft/WSL#11144]
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu-22.04

### Distro Version

Default Distribution: Ubuntu-22.04

### Repro Steps

```
PS C:\Users\iulian> wsl --distribution Ubuntu-22.04
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED
``` 

```
PS C:\Users\iulian> wsl --distribution Ubuntu-22.04
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED
```

### Expected Behavior

Working normally 

### Actual Behavior

Catastrophic failure

### Diagnostic Logs

[WslLogs-2024-02-09_18-52-39.zip](https://github.com/microsoft/WSL/files/14225424/WslLogs-2024-02-09_18-52-39.zip)
[WslLogs-2024-02-09_18-38-33.zip](https://github.com/microsoft/WSL/files/14225426/WslLogs-2024-02-09_18-38-33.zip)

**Comment by OneBlue** [comment]
@isurugiu: I see that you have this in .wslconfig: 

```
[wsl2]
memory=4096
``` 

That's very little memory. Can you try to replace this by: 

```
[wsl2]
memory=4GB
``` 

?
