### ISSUE TITLE
Experiencing file permissions randomly changing.  See #5463

### ISSUE THREAD

**Issue by ggarra13** [microsoft/WSL#11146]
### Windows Version

Microsoft Windows [Version 10.0.22621.3007]

### WSL Version

WSL version: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.133.1-1

### Distro Version

Rocky Linux 8.9

### Other Software

Running a cmake compilation that does not find a file due to permission randomly changing on Rocky Linux 8.9.

$ cmake --version
cmake version 3.26.5

### Repro Steps

Create a long running compilation with multiple steps.  cmake will randomly fail as the permissions of WSL2 randomly change.  You can also see it if you run ls -l on the files on the NTFS drive.

### Expected Behavior

Permissions should remain consistent while the WSL2 runs.  The permissions should also remain if /etc/wsl.conf is configured properly.

### Actual Behavior

These two commands were run just seconds from each other:
```

# gga@rocky8 ~
# Sat Feb 10 06:09:33 [919] $ ll code/lib/NDI_SDK_for_Linux/lib/x86_64-linux-gnu/
total 25M
---------- 1 gga gga  38 Jan 16 18:25 libndi.so
---------- 1 gga gga  38 Jan 16 18:25 libndi.so.5
---------- 1 gga gga 25M Nov 17 13:26 libndi.so.5.6.0

# gga@rocky8 ~
# Sat Feb 10 06:09:41 [920] $ ll code/lib/NDI_SDK_for_Linux/lib/x86_64-linux-gnu/
total 25M
-rwxrwxrwx 1 gga gga  38 Jan 16 18:25 libndi.so
-rwxrwxrwx 1 gga gga  38 Jan 16 18:25 libndi.so.5
-rwxrwxrwx 1 gga gga 25M Nov 17 13:26 libndi.so.5.6.0

$ alias ll
alias ll='ls -lh'

$  cat /etc/wsl.conf
[user]
default=gga
[boot]
systemd=true
[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=11"
mountFsTab = false

```

**Comment by ggarra13** [comment]
I am keeping this issue open as the AI issues do not describe the problem.

**Comment by ggarra13** [comment]
One more note:

The "code" directory is actually a symlink to /mnt/d/code.

**Comment by ggarra13** [comment]
The problem seems to happen (wild guess here) when you access a different part of the filesystem as when accessing all contiguous files, it does not happen.

**Comment by pmartincic** [comment]
Are you able to collect /logs while reproducing this? and your `~/.wslconfig` if you would be so kind.

**Comment by ggarra13** [comment]
I am afraid I won't be able to follow through with the testing as I have uninstalled WSL2 as it was clearly not yet ready for production use (or for my needs at least).  Not only the permission issue was problematic but its NTFS performance was abismal.
