### ISSUE TITLE
Unable to detect second CPU while windows does.

### ISSUE THREAD

**Issue by Kevincav** [microsoft/WSL#1115]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  I have a dual socket workstation with 2 e5-2696 v4s in there.  Through both top (and htop) lscpu I'm only able to see threads from the first socket.
- Expected results
  I'm expecting 2 sockets, with 44 cores and 88 threads to show up.
- Actual results (with terminal output if applicable)
  Kevin@DESKTOP-ALHNGUT:~$ lscpu
  Architecture:          x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
  CPU(s):                44
  On-line CPU(s) list:   0-43
  Thread(s) per core:    2
  Core(s) per socket:    22
  Socket(s):             1
  Vendor ID:             GenuineIntel
  CPU family:            6
  Model:                 79
  Stepping:              1
  CPU MHz:               2201.000
  BogoMIPS:              4402.00
  Virtualization:        VT-x
- Your Windows build number
  Windows 10 version 1607 build 14393.187.
- Steps / All commands required to reproduce the error from a brand new installation 
  N/A
- Strace of the failing command
  N/A
- Required packages and commands to install
  N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
What? 44cores on one cpu? Never seen anything like that.

**Comment by misenesi** [comment]
Recognition of multiple processor sockets is something we are aware of. Currently only a single socket is supported.

**Comment by GabeAl** [comment]
Here's one such issue on Voice for ease of voting: 
https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16393417-please-add-multi-cpu-socket-support-for-bash

**Comment by PetrKryslUCSD** [comment]
What is the status? I do see all 32 CPUs with cat /proc/cpuinfo.
On the other hand, I do have some doubts: https://discourse.julialang.org/t/distributed-computing-in-the-windows-subsystem-for-linux/23723/13

**Comment by muratyurdakul75** [comment]
Hi

Unfortunately, there is no development on this issue. There are constant requests on this issue, but they are marked as "duplicate requests" and directed to old notifications. Is there any development?

Actually, there are multiple expectations regarding this NUMA issue;
1> More than one NUMA needs to be supported.
2> It needs to be able to work with more than 64 processors.
3> We need to be able to decide which NUMA it will work on. (There may be those who want it to work on only one NUMA)

It would be really great if such a development could be made.

Thank you in advance for your efforts.

**Comment by hyjforesight** [comment]
It has been 8 years! @misenesi @muratyurdakul75 
The Peloponnesian War (431-404 BC)
The American Revolutionary War (1775-1783)
World War I (1914-1918) and its immediate aftermath (1918-1922)
The Iraq War (2003-2011)
WSL2 DOES NOT SUPPORT DUAL CPUS (2016-2024)

**Comment by benhillis** [comment]
Should be fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5 - but let me know if this needs more tweaks by opening a new issue.

**Comment by muratyurdakul75** [comment]
> Should be fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5 - but let me know if this needs more tweaks by opening a new issue.

I have been using it since the day it was published. There is no problem. Thank you again for your efforts.

Actually, I had a different suggestion about this. There may be a NUMA option in the wslconfig file. If you want, you can run it in all NUMA, if you want, you can run it in the NUMA you specify. Maybe it is not a very important request. But it may be needed in this way.

#12319

**Comment by hyjforesight** [comment]
> Should be fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5 - but let me know if this needs more tweaks by opening a new issue.

Hello @benhillis , thank you for releaing this new version. I saw the updates `Use GetLogicalProcessorInformationEx to determine max number of processors`. I've installed this version, but still can only detect 1 socket of CPUs. I'm not a developer. Could you please let me know how to make WSL2 v2.4.5 detect dual CPUs? Thank you!

**Comment by muratyurdakul75** [comment]
> > Should be fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5 - but let me know if this needs more tweaks by opening a new issue.
> 
> Hello [@benhillis](https://github.com/benhillis) Thank you for releaing the new version. Previously,
> 
> ```
> lscpu | grep -E "CPU\(s):|Thread|Core\(s|Socket"
> CPU(s):                               48
> Thread(s) per core:                   2
> Core(s) per socket:                   24
> Socket(s):                            1
> ```
> 
> I've installed this new version, all threads are deteced but still only 1 socket of CPUs detected.
> 
> ```
> lscpu | grep -E "CPU\(s):|Thread|Core\(s|Socket"
> CPU(s):                               96
> Thread(s) per core:                   2
> Core(s) per socket:                   48
> Socket(s):                            1
> ```
> 
> I tried
> 
> ```
> openssl speed -evp aes-256-cbc -multi 96
> ```
> 
> but still only 1 socket of CPU can be maximum loaded. ![Image](https://github.com/user-attachments/assets/44ebd3b9-69a6-4e6a-b101-3a7a77fb8757)
> 
> I'm not a developer. Could you please let me know how to make WSL2 v2.4.5 use dual CPUs? Thank you!

I don't know why. Maybe you need to do something in BIOS settings. It would be good if you check the NUMA settings in BIOS screen.

**Comment by Atsuzuki0605** [comment]
> I'm not a developer. Could you please let me know how to make WSL2 v2.4.5 use dual CPUs? Thank you!

Hello [hyjforesight](https://github.com/hyjforesight).

I also have a dual-socket workstation equipped with Xeon Gold 6138 processors.
I have updated WSL2 to version 2.4.8; however, it still only detects one CPU socket. 
If you have solved this issue, could you please provide guidance on how to enable WSL2 to utilize both CPUs?

**Comment by hyjforesight** [comment]
@Atsuzuki0605 
I didn't figure it out. My PC only detects one socket. We need @benhillis help.
