### ISSUE TITLE
Slow down related to uptime

### ISSUE THREAD

**Issue by stevenh** [microsoft/WSL#11155]
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Run WSL for a number of days without restarting, it gets slower and slower.

Today I was really noticing it so ran a test, a refactor I'd been developing which is some shell, perl and golang reported by time:

real    6m51.373s
user    0m21.999s
sys     0m3.586s
After closing wsl and restarting with wsl --shutdown the same thing took:

real    0m42.377s
user    0m34.388s
sys     0m14.403s
Before the restart vmmem was using 22GB of RAM, afterwards 2.3GB

### Expected Behavior

WSL should not slow down after time

### Actual Behavior

Significant slowdown and significant memory usage just be using it for a few days.

**Comment by stevenh** [comment]
This is just a re-post of https://github.com/microsoft/WSL/issues/9137 which was closed by the bot without resolution, really should ditch that as its just causing repetition of details, forcing users to recreate bugs losing the original context.

**Comment by craigloewen-msft** [comment]
Reopened to the original and will mark this as duplicate. Thank you for refiling this!
