### ISSUE TITLE
WSL1 STOP Error in Windows Server 2022 (MEMORY_MANAGEMENT)

### ISSUE THREAD

**Issue by DesktopECHO** [microsoft/WSL#11160]
### Windows Version

4.4.0-22000-Microsoft

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-22000-Microsoft

### Distro Version

Any

### Other Software

https://sh.rustup.rs

### Repro Steps

Windows 11 BugCheck occurs randomly.

Easily reproducible steps:
- Install rust using rustup as follows: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
- System will BSOD before installation completes.

This issue existed in Windows 11 RTM and was fixed in 21H2, but has **not been fixed in Server 2022.**

### Expected Behavior

BugCheck-free computing

### Actual Behavior

BugCheck

### Diagnostic Logs

An example of the bugcheck with other software:

[WinDBG-seamonkey.txt](https://github.com/microsoft/WSL/files/7261505/WinDBG-seamonkey.txt)
[WinDBG-spotify.txt](https://github.com/microsoft/WSL/files/7261506/WinDBG-spotify.txt)
[WinDBG-WebKitWebProcess.txt](https://github.com/microsoft/WSL/files/7261507/WinDBG-WebKitWebProcess.txt)

**Comment by OneBlue** [comment]
Thank you @DesktopECHO. Can you follow [these instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#10-reporting-a-windows-crash-bsod) to capture and share the BSOD dump with us ?
