### ISSUE TITLE
ping -T not working correctly

### ISSUE THREAD

**Issue by j0nne** [microsoft/WSL#1116]
running ping -T tsonly [destination] returns the following error:

ping: ts option: invalid argument

according to the man page for ping, this should work and works in Ubuntu

**Comment by fpqc** [comment]
Which build number of Windows?

**Comment by wizardist** [comment]
@fpqc I can reproduce this issue on Version 1607 (OS Build 14393.187) (Release Preview / Slow).

See the strace for `ping -T tsonly example.com` in the gist.

https://gist.github.com/wizardist/73535a9d7ea66a188af2b2bcd5c77c75

**Comment by sunilmut** [comment]
@j0nne Thanks for reporting the issue and @wizardist for the trace. From the strace, it looks like the `-T tsonly` option uses the IPPROTO_IP\IP_OPTIONS, which is currently not implemented in WSL, but something we are already tracking.
`setsockopt(3, SOL_IP, IP_OPTIONS, "D(\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 40) = -1 EINVAL (Invalid argument)
setsockopt(3, SOL_IP, IP_OPTIONS, "D(\5\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 40) = -1 EINVAL (Invalid argument)`

**Comment by sunilmut** [comment]
Just an update that support for `IP_OPTIONS` was added in [16176](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176), but it does not fully unblock `ping -T` yet. Now it errors out with `Invalid timestamp type`.

**Comment by DjArt** [comment]
This issue was fixed. Needs to close.
