### ISSUE TITLE
Slow loopback in WSL2 with mirrored network

### ISSUE THREAD

**Issue by Hydrostic** [microsoft/WSL#11173]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I install the nginx 1.18 and set up a file server. When I send request from windows host to wsl, it costs 250ms to retrieve a 17mb file. In comparison, it only costs 12ms by using curl in wsl.

### Expected Behavior

Expect speed to be much faster

### Actual Behavior

A low speed

**Comment by AlejandroAkbal** [comment]
Happens to me too
