### ISSUE TITLE
git clone (with core.sshcommand=ssh.exe) hangs forever instead of showing host key prompt

### ISSUE THREAD

**Issue by o-alquimista** [microsoft/WSL#11175]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04.4

### Other Software

Windows OpenSSH (ssh.exe)

### Repro Steps

1. First, set `core.sshcommand=ssh.exe` in `~/.gitconfig` in the WSL distro.
2. Delete or move `C:\Users\<your_user>\.ssh\known_hosts` if it exists.
3. In WSL, clone from a remote repository (e.g. `git clone git@github.com:o-alquimista/passwiz.git`).

### Expected Behavior

It should show a prompt to accept or reject the unknown host key; and if you accept it, it should continue with the `git clone`.

### Actual Behavior

It hangs forever, and there is no output.

As a workaround, run `ssh.exe git@github.com`, accept the host key, then retry the cloning.

**Comment by OneBlue** [comment]
Thank you @o-alquimista. Do you have the git credential helpers configured ? If so I'd guess that it's what's hanging. 

Can you share the output of `git config credential.helper` ?

**Comment by o-alquimista** [comment]
> Thank you @o-alquimista. Do you have the git credential helpers configured ? If so I'd guess that it's what's hanging.
> 
> Can you share the output of `git config credential.helper` ?

Sorry for the delay. There was no output. Undefined.

**Comment by Angada28** [comment]
I also have this issue, one thing that works sometimes is first trying to clone on my windows side and then trying again on wsl. But this doesnt work consistently. I have tried the above steps as well but they did not help.
