### ISSUE TITLE
Shm max memory available is very low

### ISSUE THREAD

**Issue by cyborgdennett** [microsoft/WSL#11178]
### Windows Version

10.0.22623.741

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I'm using the linux mm.h library

Calling the function 
```c
size_t mm_maxsize(void)
{
    return (mm_core_maxsegsize()-SIZEOF_mem_pool);
}
```
It gives me a value of 67,100,632 or 67 Mb while I have 20 Gb RAM memory installed. The program cannot be used anymore due to this.

Callstack dump
```c
size_t mm_core_maxsegsize(void)
{
    return mm_core_align2page((MM_SHM_MAXSEGSIZE-SIZEOF_mem_core)-mm_core_pagesize());
}


static size_t mm_core_pagesize(void)
{
    static int pagesize = 0;
    if (pagesize == 0)
#if defined(MM_VMPS_GETPAGESIZE)
        pagesize = getpagesize();
#elif defined(MM_VMPS_SYSCONF)
        pagesize = sysconf(_SC_PAGESIZE);
#elif defined(MM_VMPS_BEOS)
        pagesize = B_PAGE_SIZE;
#else
        pagesize = MM_CORE_DEFAULT_PAGESIZE;
#endif
    return pagesize;
}

size_t mm_core_align2page(size_t size)
{
    int psize = mm_core_pagesize();
    return ((size)%(psize) > 0 ? ((size)/(psize)+1)*(psize) : (size));
}


````

### Expected Behavior

I expected to see a value close to 20 Gb

### Actual Behavior

Only 67Mb was seen

**Comment by OneBlue** [comment]
Thank you @cyborgdennett.

shm is usually a tmpfs mount. Can you share the output of `mount` inside WSL ?

**Comment by cyborgdennett** [comment]
Sorry I made an error in my code not a walk problem
