### ISSUE TITLE
VHD mount issue with "WSL (2156) ERROR: UtilMount"

### ISSUE THREAD

**Issue by hitesh-sourcefuse** [microsoft/WSL#11183]
### Windows Version

Microsoft Windows [Version 10.0.22621.3155]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Other Software

WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.3155

### Repro Steps

mount a new VHD using 
`wsl.exe -d Debian --mount --vhd 'D:\example.vhdx' --name example --type ext4`
put system to sleep wake up after sometime and unmount vhd using 
`wsl.exe --unmount '\\?\D:\example.vhdx'`
and then remount it will show 

The disk was attached but failed to mount: Invalid argument.
For more details, run 'dmesg' inside WSL2.
To detach the disk, run 'wsl.exe --unmount \\?\D:\example.vhdx'.

### Expected Behavior

It should mount the drive

### Actual Behavior

throw error with 

The disk was attached but failed to mount: Invalid argument.
For more details, run 'dmesg' inside WSL2.
To detach the disk, run 'wsl.exe --unmount \\?\D:\example.vhdx'.

### Diagnostic Logs

dmesg log 

[ 1831.003841] sd 0:0:0:3: [sdc] Synchronizing SCSI cache
[ 1833.216590] scsi 0:0:0:3: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[ 1833.223442] sd 0:0:0:3: Attached scsi generic sg2 type 0
[ 1833.224220] sd 0:0:0:3: [sdc] 83886080 512-byte logical blocks: (42.9 GB/40.0 GiB)
[ 1833.224901] sd 0:0:0:3: [sdc] 4096-byte physical blocks
[ 1833.225406] sd 0:0:0:3: [sdc] Write Protect is off
[ 1833.225776] sd 0:0:0:3: [sdc] Mode Sense: 0f 00 00 00
[ 1833.226295] sd 0:0:0:3: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[ 1833.228271]  sdc: sdc1
[ 1833.228799] EXT4-fs (sdc): VFS: Can't find ext4 filesystem
[ 1833.229377] WSL (2156) ERROR: UtilMount:1681: mount(/dev/sdc, /mnt/wsl/IdeaProjects, ext4, 0x
[ 1833.229380] 0, ) failed 22
[ 1833.229521] sd 0:0:0:3: [sdc] Attached SCSI disk
[ 2269.240484] EXT4-fs (sdc): VFS: Can't find ext4 filesystem
[ 2269.241612] WSL (2208) ERROR: UtilMount:1681: mount(/dev/sdc, /mnt/wsl/IdeaProjects, ext4, 0x
[ 2269.241617] 0, ) failed 22

**Comment by hitesh-sourcefuse** [comment]
lsblk output 
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 389.8M  1 disk
sdb      8:16   0     8G  0 disk [SWAP]
sdc      8:32   0    40G  0 disk
└─sdc1   8:33   0    40G  0 part
sdd      8:48   0     1T  0 disk /


WSL debug output
[    1.469053]  sdc: sdc1
[    1.470238] sd 0:0:0:3: [sdc] Attached SCSI disk
[    1.483132] scsi 0:0:0:2: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    1.490828] sd 0:0:0:2: Attached scsi generic sg3 type 0
[    1.491607] sd 0:0:0:2: [sdd] 2147483648 512-byte logical blocks: (1.10 TB/1.00 TiB)
[    1.492302] sd 0:0:0:2: [sdd] 4096-byte physical blocks
[    1.492728] sd 0:0:0:2: [sdd] Write Protect is off
[    1.493288] sd 0:0:0:2: [sdd] Mode Sense: 0f 00 00 00
[    1.493840] sd 0:0:0:2: [sdd] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.497099] sd 0:0:0:2: [sdd] Attached SCSI disk
[    1.511024] EXT4-fs (sdd): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered. Quota mode: none.
[    1.644820] /sbin/ldconfig:
[    1.644826] /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link
[    1.645607]
[    1.833595] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x6d567a2e9e9, max_idle_ns: 881590759303 ns
[    1.835716] clocksource: Switched to clocksource tsc
[    1.926169] mount:
[    1.926177] /home/xx/example: special device /dev/sdd1 does not exist.

**Comment by OneBlue** [comment]
Thank you for reporting this @hitesh-sourcefuse. Based on the output it looks like your disk is partitioned. 

Can you try: 

```
wsl.exe -d Debian --mount --vhd 'D:\example.vhdx' --name example --type ext4 --partition 1
``` 
instead ?
