### ISSUE TITLE
wsl --install fails with Wsl/InstallDistro/0x80072f8f

### ISSUE THREAD

**Issue by canon-cmi-jesper-dam** [microsoft/WSL#11181]
### Windows Version

Microsoft Windows [Version 10.0.22621.3155]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

wsl --install

### Expected Behavior

The command succeeds

### Actual Behavior

Installing: Ubuntu
Content decoding has failed 0.0%'
Error code: Wsl/InstallDistro/0x80072f8f

### Diagnostic Logs

[WslLogs-2024-02-20_11-32-27.zip](https://github.com/microsoft/WSL/files/14343147/WslLogs-2024-02-20_11-32-27.zip)

**Comment by CodrinSocol** [comment]
I encountered the same issue. The problem was that I was trying to install wsl from command prompt with admin rights, instead of an elevated powershell. Retrying in elevated powershell fixed it for me. 

Ref: https://learn.microsoft.com/en-us/windows/wsl/install
