### ISSUE TITLE
Understanding the WSL release mode

### ISSUE THREAD

**Issue by lgmorand** [microsoft/WSL#11192]
Question is simple: we have a new release every two weeks but what make a release to be a stable release and not a "prerelease"? I found not logical by looking at the semver and trying to guess when the next version will be stable and thus upgradable with "wsl --update"

**Comment by OneBlue** [comment]
We make a mark a release as "stable" based on how many open issues / bugs are opened on that release. The version number itself doesn't describe itself whether a release is stable or not.

`wsl --update` always updates to the newest stable release and `wsl --update --pre-release` always updates to the latest available release
