### ISSUE TITLE
wsl.2.1.3.0.x64.msi package does not install or update windows Subsystem for Linux.

### ISSUE THREAD

**Issue by Mikary29** [microsoft/WSL#11190]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Debian 12

### Repro Steps

Click on wsl.2.1.3.0.x64.msi installer, to update or install with WSL shutdown. Now the wsl.2.1.1.0.x64.msi package does the same thing.
![PXL_20240221_002512988](https://github.com/microsoft/WSL/assets/5043013/8ba67641-3d60-49fa-ab0d-837ac219a7ae)
![PXL_20240221_153129576 MP](https://github.com/microsoft/WSL/assets/5043013/698d3b5c-428a-474c-bc5a-db6f448723d8)

### Expected Behavior

To install just like the Microsoft.WSL_2.1.3.0_x64_ARM64.msixbundle installer of the same application and version. From the same GitHub repo, releases page. It should work just like the MicrosoftEdgeEnterpriseX64.msi installer, I used to update Microsoft Edge right before.

### Actual Behavior

It retracts the progress bar of the installer and closes. And this picture is what I end up with, no WSL.
![PXL_20240221_155332902](https://github.com/microsoft/WSL/assets/5043013/90f2f910-7f6d-4334-bfba-0458262be3bb)

**Comment by Mikary29** [comment]
[WslLogs-2024-02-26_18-48-33.zip](https://github.com/microsoft/WSL/files/14412902/WslLogs-2024-02-26_18-48-33.zip)

**Comment by OneBlue** [comment]
Thank you @Mikary29. It looks like the installer is failing to deploy the package on E:

```
46	True	Microsoft.Windows.Subsystem.Lxss	LxssVerboseLog	0	02-26-2024 16:48:49.178	"	"	"Code: 	
File: 	D:\a\1\s\src\windows\wslinstall\DllMain.cpp
FunctionName: 	
HRESULT: 	0x80070490
Line number: 	302
Message: 	Deployment DeprovisionPackageOperation operation with target volume E: on Package MicrosoftCorporationII.WindowsSubsystemForLinux_2.1.1.0_neutral_~_8wekyb3d8bbwe from:   failed with error 0x80070490. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
Type: 	2
wslVersion: 	2.1.3.0"				14216	16908	5		aa596cc7-6912-0009-463f-5aaa1269da01		

``` 

Did you change a setting to force apps to deploy on a non system drive maybe ?

**Comment by Mikary29** [comment]
I have also deployed the last one from the downloads folder under my user account. AMD the same thing is happening. I will send a error log for it being deployed from that location also.

**Comment by Mikary29** [comment]
Fixed by redoing windows and installing Windows Beta, instead of Public. Again, multiple Microsoft teams, not communicating with each other. To overcome a problem.

**Comment by getulioanywhere** [comment]
Solution here:

[https://apps.microsoft.com/detail/9P9TQF7MRM4R](url)
