### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down when systemctl start virtqemud

### ISSUE THREAD

**Issue by Windows98SE-dev** [microsoft/WSL#11209]
### Windows Version

Microsoft Windows [version 10.0.22631.3085]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Fedora Linux 39

### Repro Steps

systemctl start  virtqemud

### Expected Behavior

The qemu process starting

### Actual Behavior

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by yilmazdurmaz** [comment]
Hi @Windows98SE-dev, first time I see the AI bot searching for issues, that is nice, but in case someone real you would prefer to hear, here is a few parts from those links:
- check if you restarted your pc and then WSL properly: systemd will need a restart of at least the WSL
- check the existence, location and content of wsl config file, conforming to linux standards
- check a few required packages for the distro you are trying to use, like dbus.

I will keep the post short as we have accumulated many solutions in the linked issues, some short some long, it would be few pages long to trying to post them here again. Please take your time and read them. (8883 has solutions, it is just kept open for awareness).

**Comment by Windows98SE-dev** [comment]
Unfortuantely I don't have admin perms on my PC and .ps1 scripts have been disabled

**Comment by OneBlue** [comment]
Unfortunately we need to logs to diagnose this issue. I'll close this for now but feel free to reopen if you get the permissions to collect logs on your machine.
