### ISSUE TITLE
“Nested virtualization is not supported on this machine”, but it works in Hyper-V

### ISSUE THREAD

**Issue by JojOatXGME** [microsoft/WSL#11216]
### Windows Version

Microsoft Windows [Version 10.0.19045.4046]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

Hyper-V-Manager, Version: 10.0.19041.1

### Repro Steps

 1. Create `%USERPROFILE%\.wslconfig`
    ```
    [wsl2]
    nestedVirtualization=true
    ```
 2. Install the following _Features_:
    * Hyper-V/*
    * VM-Plattform
    * Windows-Hypervisor-Platform
    * Windows-Subsystem for Linux
 3. Start any distro with WSL

### Expected Behavior

Nested virtualization should be working with WSL as long as it is working with Hyper-V. If there are additional requirements not present in Hyper-V, they should be documented.

I tested running Ubuntu in Qemu on NixOS in Hyper-V. I used `qemu-system-x86_64 -enable-kvm` to lunch Ubuntu within NixOS. Everything worked with reasonable good performance. So, I am sure that nested virtualization actually works on my processor with Hyper-V.

![Image showing YT on Ubuntu in Qemu on NixOS in Hyper-V](https://github.com/microsoft/WSL/assets/1288216/e2b2e2ff-d363-46ad-a4db-49e22d7f4d0a)

### Actual Behavior

WSL reports the following message (German) before starting the distro:

```
wsl: Geschachtelte Virtualisierung wird auf diesem Computer nicht unterstützt.
```

(Translates to “Nested virtualization is not supported on this machine.”)

The distro reports that KVM is not supported,

```
jojo@DellBox-DESKTOP166:/mnt/c/Users/jojo$ dmesg | grep kvm
[    0.115998] kvm: no hardware support
[    0.116001] kvm: no hardware support
```

### Diagnostic Logs

[WslLogs-2024-02-27_23-07-35.zip](https://github.com/microsoft/WSL/files/14426270/WslLogs-2024-02-27_23-07-35.zip)

**Comment by JojOatXGME** [comment]
FYI, someone actually created a script for WinDbg to hock into the hypervisor and enable nested virtualization for WSL. I haven't tested this script, though.

https://gist.github.com/xtrnc/496da9243bab29629bc0461562bff458

It is also a bit absurd that WSL claims that my machine does not support nested virtualization, but it works when I add another layer of virtualization in between. I can run WSL with nested virtualization on the same machine within a Windows 11-VM on Hyper-V. (It is not very performant, though.)

![wsl-on-windows11_edit](https://github.com/microsoft/WSL/assets/1288216/518df730-21d1-4221-928a-319acb9d4d82)

**Comment by elsaco** [comment]
@JojOatXGME check this closed issues #9400 for some info:

https://github.com/microsoft/WSL/issues/9400#issuecomment-1364737637

**Comment by JojOatXGME** [comment]
@elsaco So nested virtualization is not supported by WSL on Windows 10, even after [WSL has been moved to the store](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/)? Is there a reason for it, as it seems that WSL could just set the flag for the VM to enable it. I mean, nested virtualization is definitely supported by Windows 10, as you can see in my screenshots. WSL is just not enabling the flag for the hypervisor. At least this is how it looks to me.

Maybe there was some confusion because nested virtualization is only supported on Windows 11 for AMD CPUs? Maybe the check in WSL was accidentally implemented too strictly, so that it also blocks access on Intel CPUs?

While the [documentation](https://learn.microsoft.com/en-us/windows/wsl/wsl-config) claims that nested virtualization is Windows 11 only, it has the same note for WSLg, which is supported by Windows 10 since it was moved to the Windows Store. So the documentation is definitely out of date regarding such claims regarding support in Windows 10, which is why I don't take this claim very seriously.

**Comment by OneBlue** [comment]
Yes @JojOatXGME, WSL indeed doesn't support nested virtualization on Windows 10.  This is because of a limitation in the virtualization API that WSL uses. If you need nested, the simplest solution would be to upgrade your machine to Windows 11.

**Comment by nick-wellinghoff** [comment]
It does not support it because Microsoft wants you to upgrade to 11. There is no physical limitation that would prevent them from supporting it if they wanted to.

**Comment by SingeStheos** [comment]
yes
