### ISSUE TITLE
Wsl won't upgrade to new kernel

### ISSUE THREAD

**Issue by DaDoFtWiNs2011** [microsoft/WSL#11212]
The current running kernel version is 5.15 0.113 point one Microsoft standard wsl2 which is not expected kernel version 6.69 AMD 64 restarting the system to load the new car will not be handled automatically so you should consider

**Comment by OneBlue** [comment]
The kernel is part of the WSL package. The latest available version is: 5.15.146.1-2.  If you want a more recent version, you can build one yourself from https://github.com/microsoft/WSL2-Linux-Kernel and use it via `wsl2.kernel` in .wslconfig.
