### ISSUE TITLE
`mpirun` hangs when `networkingMode=mirrored`

### ISSUE THREAD

**Issue by dhtzs** [microsoft/WSL#11215]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 23.04

### Other Software

mpirun (Open MPI) 4.1.4

### Repro Steps

1. Create `.wslconfig` file with the following content:
```
[wsl2]
dnsTunneling=true
networkingMode=mirrored
firewall=true
autoProxy=true

[experimental]
autoMemoryReclaim=dropcache
```

2. Terminate WSL using `wsl.exe --shutdown` and start a new WSL instance.

3. Compile the following C program using `mpicc mpi.c -o mpi`:
```
#include <stdio.h>
#include <stdlib.h>
#include "mpi.h"

#define ARRAY_SIZE 16

int main(int argc, char *argv[]) {
    int rank, size;
    int A[ARRAY_SIZE] = {2,5,6,1,6,7,3,9,5,0,6,8,3,5,6,1};
    int chunk_size, remainder, local_chunk_size, local_start, local_sum, total_sum;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    chunk_size = ARRAY_SIZE / size;
    remainder = ARRAY_SIZE % size;

    if (rank < remainder) {
        local_chunk_size = chunk_size + 1;
        local_start = rank * local_chunk_size;
    } else {
        local_chunk_size = chunk_size;
        local_start = rank * chunk_size + remainder;
    }

    local_sum = 0;
    for (int i = local_start; i < local_start + local_chunk_size; i++) {
        local_sum += A[i];
    }

    MPI_Reduce(&local_sum, &total_sum, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);

    if (rank == 0) {
        printf("Total sum: %d\n", total_sum);
    }

    MPI_Finalize();
    return 0;
}
``` 

4. Execute the program using `mpirun -np 2 ./mpi` and notice that `mpirun` hangs.

### Expected Behavior

![screenshot01](https://github.com/microsoft/WSL/assets/12586834/86a4f845-3e3e-4133-99d1-6f14e18e07bf)

### Actual Behavior

![screenshot02](https://github.com/microsoft/WSL/assets/12586834/e9ffdad7-fef1-4412-b3d5-d473ee297358)

**Comment by sadaisystems** [comment]
Same problem here

**Comment by anak1st** [comment]
Same problem

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by dhtzs** [comment]
Hi @chanpreetdhanjal, I collected the networking logs following the provided instructions. I hope they can help resolve the issue.

[WslNetworkingLogs-2024-06-19_12-15-44.zip](https://github.com/user-attachments/files/15898386/WslNetworkingLogs-2024-06-19_12-15-44.zip)

**Comment by CatalinFetoiu** [comment]
hello @dhtzs . thanks for reporting the issue and sending the logs! I was able to repro the issue

this is the same symptom as https://github.com/microsoft/WSL/issues/10855. MPI appears to connect to 127.0.0.1:6001, because of the RST issue mentioned in the other issue, the connection hangs

I will resolve it as a duplicate of that issue

**Comment by wang1zhen** [comment]
Though it might be a dupe, it's still a existing problem and I feel maybe it would be better to leave it open?

**Comment by BoqianBIT** [comment]
Same problem

**Comment by Nul1-Ptr** [comment]
same problem

**Comment by EarlFan** [comment]
same problem, extremely annoying

**Comment by tbcbcabral** [comment]
Same problem

**Comment by csm054** [comment]
Same problem.

**Comment by JackYoustra** [comment]
same problem. Note this blocks tensorrt's builder from launching

**Comment by LordInator** [comment]
Same problem

**Comment by SV001R** [comment]
I have same issue. In my case, it takes about 30 min to start operation.

**Comment by XavierNie715** [comment]
Same problem. MPI takes 20 min to start in my case.
