### ISSUE TITLE
Add option to escape/quote return values from wslpath

### ISSUE THREAD

**Issue by jtnord** [microsoft/WSL#11213]
**Is your feature request related to a problem? Please describe.**
if I am converting paths that have some non shell / argument safe characters I need to handle escaping them myself.
This is tedious as it involves quoting strings which may themselves be commadn lines that are already quoted

e.g. consider `wslpath -u -a "C:\Program Files\Google\Chrome\Application\chrome.exe"` which will give you that command to lanuch chrome from the WSL shells.  (`/mnt/c/Program Files/Google/Chrome/Application/chrome.exe`)
however `/mnt/c/Program Files/Google/Chrome/Application/chrome.exe` is a single string - but at the shell level which is where interaction with wslpath is likjely to happen that would be treated as 2 strings due to the space.

e.g. it is not possible to simply write  ```EXPORT BROWSER=`wslpath -u -a "C:\Program Files\Google\Chrome\Application\chrome.exe"` ```

as the resulting string will not launch a browser due to the space (its is interpreted as a program `/mnt/c/Program` with the argument `Files/Google/Chrome/Application/chrome.exe`

**Describe the solution you'd like**

I would like an argument I can pass that can escape shell characters in a way suitable for the shell.

e.g. 
`--escape=[backslasg,caret,single_quote,double_quote]`

escaping may need to be different if getting a windows path (where `^` would be needed) or on linux where spaces (and other characters) need to be escaped with a backslash.   the simple alternative (that may not work in all cases) would be to surroud the return in quotes.

**Describe alternatives you've considered**

alias wslpath to a script that does its own thing escapes resulting strings and then passes them back)

**Additional context**

makes it harder to write `bashrc` or scripts that would want to use the output of `where.exe` to obtain paths to windows binaries.

**Comment by OneBlue** [comment]
@jtnord: There's a simpler way to do that. This issue can be solved by expanding $BROWSER within double quotes, which won't caused the path to be split. For instance: 

```
➜ hvlite-vso export BROWSER=`wslpath 'C:\Program Files\Mozilla Firefox\firefox.exe'`
➜ hvlite-vso echo $BROWSER
/mnt/c/Program Files/Mozilla Firefox/firefox.exe

 # Fails because of argument splitting
➜ file $BROWSER
/mnt/c/Program:      cannot open `/mnt/c/Program' (No such file or directory)
Files/Mozilla:       cannot open `Files/Mozilla' (No such file or directory)
Firefox/firefox.exe: cannot open `Firefox/firefox.exe' (No such file or directory)

# Note the double quotes here
➜ file "$BROWSER"
/mnt/c/Program Files/Mozilla Firefox/firefox.exe: PE32+ executable (GUI) x86-64, for MS Windows, 10 sections

[Browser launches]
```

Overall, shell variables should always expand within double quotes unless you specifically want them to be split into arguments again.

Beyond that, wslpath shouldn't try to "escape" paths because it doesn't have a way to know which shell the output will be used with (and shells can have widely different behaviors, especially with different shopts values).

Closing since the issue can be solved with expansion under double quotes.

**Comment by jtnord** [comment]
> Overall, shell variables should always expand within double quotes unless you specifically want them to be split into arguments again.

That only works in this specific case and is not general.  

I have many scripts that may reference $TOOL, often provided by third parties, and changing them is not an option.

Generally in Unix land you would set (iun the above example) `BROWSER=/mnt/c/Program Files/Mozilla\ Firefox/firefox.exe`

> Beyond that, wslpath shouldn't try to "escape" paths because it doesn't have a way to know which shell the output will be used with (and shells can have widely different behaviors, especially with different shopts values).

please re-read the request,  I am not asking for it to be enabled by default, and have suggested a way that you can escape for different shells (if only bash and cmd.exe / powershell where provided at the outset that would fit a lot of users)

> Closing since the issue can be solved with expansion under double quotes.

The simple alternative (that may not work in all cases) would be to surroud the return in quotes.

As already stated this is not reliable.  File names can contain quotes.

Please re-open as this is not possible and remains valid.

```
jnord@pc-jnord:~$ ls -la foo
total 8
drwxr-xr-x  2 jnord jnord 4096 Apr 19 11:05  .
drwxr-x--- 16 jnord jnord 4096 Apr 19 11:05  ..
-rw-r--r--  1 jnord jnord    0 Apr 19 11:05 'this file " has some quotes'
jnord@pc-jnord:~$
```

and quite clearly wslpath is buggy here already
```
jnord@pc-jnord:~$ wslpath -w foo/this\ file\ \"\ has\ some\ quotes
\\wsl.localhost\Ubuntu\home\jnord\foo\this file  has some quotes
jnord@pc-jnord:~$
```

(yes that is a funky unicode character!)
