### ISSUE TITLE
WSL2 Freezes when rapidly pressing '/' and ';' keys in CLI

### ISSUE THREAD

**Issue by Aherontas** [microsoft/WSL#11221]
### Windows Version

Microsoft Windows [Version 10.0.19044.3930]

### WSL Version

WSL version: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.133.1-1

### Distro Version

Fedora release 29

### Repro Steps

Typing in CLI really quick the keys:/; in this specific sequence causes WSL app to freeze and be non responding to Ctrl + c and all other cmds tried for 20-30secods.

### Expected Behavior

I was expecting not a freeze of WSL terminal after pressing those 2 keys in that exact sequence

### Actual Behavior

Not responding terminal as previously mentioned. It is good to mentioned that I get the same problem in other environments that I ssh too.

**Comment by OneBlue** [comment]
@Aherontas: Do you see this behavior across multiple terminals ? (Windows terminal / cmd.exe) 

Do you also see this behavior if let's say you run `/bin/sh` ? This could potentially be caused by a specific shell configuration

**Comment by Aherontas** [comment]
> @Aherontas: Do you see this behavior across multiple terminals ? (Windows terminal / cmd.exe)
> 
> Do you also see this behavior if let's say you run `/bin/sh` ? This could potentially be caused by a specific shell configuration

I see this behavior across different OSs in WSL only, such as Ubuntu, Fedora and Suse. I haven't experienced something similar inside Windows terminal. I don't see this behavior by running also /bin/sh (tested with some cmds). I will keep testing it also via /bin/sh you proposed in order to see if something comes up though.
