### ISSUE TITLE
config `networkingMode=mirrored` doesn't apply to wsl2

### ISSUE THREAD

**Issue by ruienger** [microsoft/WSL#11228]
### Windows Version

Microsoft Windows [Version 10.0.22621.3155]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I got only 1 distro installed in my PC, here's the steps:

- set up Windows's VPN
- run `wsl --shutdown` in cmd.exe
- run `New-NetFirewallHyperVRule -Name MyWebServer -DisplayName “My Web Server” -Direction Inbound -VMCreatorId “{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}” -Protocol TCP -LocalPorts 80` in cmd.exe, i copy this command from [Doc](https://learn.microsoft.com/en-us/windows/wsl/networking)
- edit the %UserProfile%/.wslconfig
- wait for 10 sec or reboot the PC
- run `wsl` in cmd.exe

Here is the .wslconfig file:
```txt
# Settings apply across all Linux distros running on WSL 2
[wsl2]

# Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=4GB 

# Sets the VM to use two virtual processors
processors=2

# Network settings
[experimental]

networkingMode=mirrored
# dnsTunneling=true
# firewall=true
# autoProxy=true
```

### Expected Behavior

successfully set the wsl's `networkingMode` to `mirrored` and hopefully wsl can access the network using VPN.

### Actual Behavior

I got a message from Ubuntu:
```bash
C:\Users\somebody>wsl
wsl: 检测到 localhost 代理配置，但未镜像到 WSL。NAT 模式下的 WSL 不支持 localhost 代理。
somebody@localhost:/mnt/c/Users/somebody$
```
Traslation:
```bash
C:\Users\somebody>wsl
wsl: localhost proxy configuration detected, but not mirrored to WSL. WSL in NAT mode does not support the localhost proxy.
somebody@localhost:/mnt/c/Users/somebody$
```

**Comment by peterbro1** [comment]
the `networkingMode=mirrored` needs to be under `[wsl2]`, not `[experimental]`

**Comment by ruienger** [comment]
> the `networkingMode=mirrored` needs to be under `[wsl2]`, not `[experimental]`

Thank you for comment.

but the method dosen't reslove the problem directly.
in result, i solved this issue by accident.

Here is the final .wslconfig
```txt
# Settings apply across all Linux distros running on WSL 2
[wsl2]

# Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=4GB 

# Sets the VM to use two virtual processors
processors=2

# Network settings
# [experimental]

networkingMode=mirrored
# dnsTunneling=true
# firewall=true
# autoProxy=true
```

i reboot after change the .wslconfig, seems like it doesn't apply to wsl2.
a few days later, i reset my network setting to factory mode then my issue has been sloved......

**Comment by Devinwong** [comment]
> > the `networkingMode=mirrored` needs to be under `[wsl2]`, not `[experimental]`
> 
> Thank you for comment.
> 
> but the method dosen't reslove the problem directly. in result, i solved this issue by accident.
> 
> Here is the final .wslconfig
> 
> # Settings apply across all Linux distros running on WSL 2
> [wsl2]
> 
> # Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
> memory=4GB 
> 
> # Sets the VM to use two virtual processors
> processors=2
> 
> # Network settings
> # [experimental]
> 
> networkingMode=mirrored
> # dnsTunneling=true
> # firewall=true
> # autoProxy=true
> i reboot after change the .wslconfig, seems like it doesn't apply to wsl2. a few days later, i reset my network setting to factory mode then my issue has been sloved......

This works for me too.
