### ISSUE TITLE
/etc/wsl.conf appendWindowsPath && nvim clipboard has bugs

### ISSUE THREAD

**Issue by ipsfsw** [microsoft/WSL#11223]
### Windows Version

edition: Windows11 22H3 version: 22631.3155

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu-22.04

### Repro Steps

/etc/wsl.conf
enabled=true
appendWindowsPath=false
command: su
passwrold:
command: halt 
restart
nvim a.txt
Copy content
clipboard: No provider. Try ":checkhealth" or ":h clipboard". 

### Expected Behavior

Copy content to windows Clipboard

### Actual Behavior

neovim tips: 
clipboard: No provider. Try ":checkhealth" or ":h clipboard". 
not Copy content to windows Clipboard

**Comment by ipsfsw** [comment]
if vim.fn.has("wsl") == 1 then
  vim.g.clipboard = {
    name = "win-clip.exe",
    copy = {
      ["+"] = "clip.exe",
      ["*"] = "clip.exe",
    },
    paste = {
      ["+"] = 'powershell.exe -NoProfile -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
      ["*"] = 'powershell.exe -NoProfile -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
    },
    cache_enable = 0,
  }
end

This is the clipboard setting of neovim. Have you found any problems? Because pwsh will load the configuration by default, if there is no NoProfile -c, if there is a problem in loading the configuration, for example, windows powershell is 5.x version, but the latest powershell is 7.x version, if some configuration is loaded and cannot be used on 5.x, This will cause problems, so if you can, add a non-configured pwsh command like powershell -NoProfile -c to the clip associated code.

**Comment by ipsfsw** [comment]
Maybe the bug was submitted by neovim, but I'm not sure if it's a wsl problem or a neovim problem, so if it's a neovim problem, I submitted the bug to the wrong place. I'm sorry.

**Comment by byguid** [comment]
I had the same issue. For anyone looking for a solution, it's actually in documentation `:help clipboard-wsl`.
I only needed to tweak its syntax to Lua and provide absolute paths to `clip.exe` and `powershell.exe`, since they're no longer in WSL PATH when `appendWindowsPath=false`.

Here's working config for Neovim
```lua
if vim.fn.has('wsl') == 1 then -- you may drop this condition if you don't share your Neovim config with other platforms
  vim.g.clipboard = {
    name = "win-clip.exe",
    copy = {
      ["+"] = "/mnt/c/Windows/system32/clip.exe",
      ["*"] = "/mnt/c/Windows/system32/clip.exe",
    },
    paste = {
      ["+"] = "/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe",
      ["*"] = "/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe",
    },
    enable_cache = 0,
  }
end
```

Note: this assumes you did _not_ disable windows integration entirely. 
```toml
# /etc/wsl.conf
[interop]
appendWindowsPath = false
enabled = true # solution above won't work if it's false
```
