### ISSUE TITLE
hyperV virtual processors 64 limit problem

### ISSUE THREAD

**Issue by zomzzzz** [microsoft/WSL#11236]
i am not sure if this the correct place to share this or not, but I have problem and i can't find any workaround for it so maybe someone has solution for it, so basically i am using AWS instance windows server 2022 Base and i connect to this AWS through the RDP, and on this windows server instance i enabled the HyperV feature and enabled WSL as well and then installed Ubuntu the problem is that i found Hyper V has limit of virtual processors used for Ubuntu is 64 vCPU. and i want to enable it for more than 64 to be able to do my work. Any solution or suggestions? thanks in advance

**Comment by OneBlue** [comment]
Closing since this is not a WSL issue
