### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070424

### ISSUE THREAD

**Issue by Endt4sk** [microsoft/WSL#11233]
### Windows Version

Microsoft Windows [Version 10.0.22631.3235]

### WSL Version

2.0.14

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Version: 2

### Distro Version

Kali-Linux

### Repro Steps

1. install from Microsoft Store
2. type kali in command prompt to install the distro

### Expected Behavior

kali will init success.

### Actual Behavior

C:\Users\Endt4sk>kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070424
Error: 0x80070424 The specified service does not exist as an installed service.

Press any key to continue...

### Diagnostic Logs

[WslLogs-2024-03-01_17-33-56.zip](https://github.com/microsoft/WSL/files/14459652/WslLogs-2024-03-01_17-33-56.zip)

**Comment by OneBlue** [comment]
@Endt4sk: I see that virtual machine platforme is disabled: ```
FeatureName : VirtualMachinePlatform
State       : Disabled
```

That's most likely what's causing the issue. Running ` wsl --install --no-distribution` should solve the issue.

**Comment by Endt4sk** [comment]
> @Endt4sk: I see that virtual machine platforme is disabled:
> 
> ```
> FeatureName : VirtualMachinePlatform
> State       : Disabled
> ```
> 
> That's most likely what's causing the issue. Running ` wsl --install --no-distribution` should solve the issue.

thanks for reply, I have tired `wsl --install --no-distribution` , but still init failed.

![Screenshot 2024-03-05 102613](https://github.com/microsoft/WSL/assets/6152879/822f5604-f4ed-4d84-9731-3675ce1ae210)

**Comment by OneBlue** [comment]
@Endt4sk: 'Virtual platform platform' is the component that you need, but I think that `wsl --install` is tricked by Hyper-V being enabled so it doesn't automatically enabled it. 

Can you try to run (elevated command prompt): 

```
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

Then reboot, and see if that solves the issue ?

**Comment by Endt4sk** [comment]
> @Endt4sk: 'Virtual platform platform' is the component that you need, but I think that `wsl --install` is tricked by Hyper-V being enabled so it doesn't automatically enabled it.
> 
> Can you try to run (elevated command prompt):
> 
> ```
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> ```
> 
> Then reboot, and see if that solves the issue ?

@OneBlue Thanks, it's work!
