### ISSUE TITLE
Debugging no longer possible after updating WSL to version 2.0.9.0

### ISSUE THREAD

**Issue by JustAnotherLars** [microsoft/WSL#11231]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop Windows  (v4.28.0)
WSL-Version: 2.0.9.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.22631.3155

Visual Studio 2022 Professional (17.9.1)

### Repro Steps

- Update WSL-Version from 1.2.5 to 2.0.9 with `wsl.exe --install`
- Create a new vs project (with docker compatibility)
- select windows docker container
- Add this to the docker arguments: --network="WSL"
- start debugging
- notice that the network is not found
- Check which Hyper V switches exist and find the following: WSL (Hyper-V firewall)
- customize docker arguments with the existing network
- start debugging again

### Expected Behavior

VS compiles the project and will start the debugging process.
Among other things, Docker uses the Hyper v virtual switch with the name "WSL".

### Actual Behavior

The project is not compiled.
VS reports that the remote debugging service is not available and cancels the process.
The following switch appears in the Hyper v virtual switches list:
WSL (Hyper-V firewall)

VS gives the following error:

---------------------------
Microsoft Visual Studio
---------------------------
Debugging cannot be started.

Visual Studio Remote Debugger (MSVSMON.EXE) does not appear to be running on the remote computer. This may be because communication with the remote computer is prevented by a firewall. Information on configuring remote debugging can be found in the help.
---------------------------
OK   
---------------------------

I have already switched off all firewalls. The behavior persists.
Even reinstalling my computer did not solve the problem.

**Comment by Denarius33** [comment]
I have exactly the same issue and can't find a solution for it.

**Comment by benhillis** [comment]
I think I have an idea what's going on here... When we introduced support for Hyper-V Firewall, the name of the network we create is now "WSL (Hyper-V firewall)".

**Comment by benhillis** [comment]
Try passing that instead.
