### ISSUE TITLE
Occassionally garbage/scrambled/blurry UI

### ISSUE THREAD

**Issue by codebymikey** [microsoft/WSL#11235]
### Windows Version

Microsoft Windows [Version 10.0.22621.3155]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.133.1-microsoft-standard-WSL2 (root@1c602f52c2e4) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Oct 5 21:02:42 UTC 2023

### Distro Version

Ubuntu 18.04

### Other Software

PHPStorm launched from within WSL2.

### Repro Steps

Not easily repeatable, but happens on occassion.

### Expected Behavior

UI should be perfectly functional.

### Actual Behavior

The UI of tools such as PHPStorm occassionally get very mangled.

**Comment by codebymikey** [comment]
Example issue on Stackoverflow: https://stackoverflow.com/questions/77869463/gui-programs-are-blurry-pixelated-in-wsl2

![image](https://github.com/microsoft/WSL/assets/9484406/10932777-c250-4d60-931b-9d425c2151fb)

And this has been a fairly long-running issue.

**Comment by benhillis** [comment]
Have you tried a new pre-release WSL version? I think we resolved this with an updated msrdc.

`wsl.exe --update --pre-release`
