### ISSUE TITLE
WSL freezes

### ISSUE THREAD

**Issue by andreasWallner** [microsoft/WSL#11232]
### Windows Version

Microsoft Windows [Version 10.0.19045.4046]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

- Run Ubuntu after reboot
- disconnect docking station, send computer to sleep/hibernate
- wake up machine, reconnect docking station

### Expected Behavior

WSL should continue working like before the sleep/disconnect

### Actual Behavior

- WSL is frozen, terminal does not react anymore
- `vmem` uses >80% CPU
- `wsl --shutdown` hangs
- `wslservice.exe` needs to be killed manually to restore functionality

### Diagnostic Logs

[WslLogs-2024-03-01_09-42-28.zip](https://github.com/microsoft/WSL/files/14458810/WslLogs-2024-03-01_09-42-28.zip)

**Comment by andreasWallner** [comment]
@OneBlue I attached the output from `collect-wsl-logs.ps1` the to OP, from exactly those commands. Is something wrong with them?

**Comment by OneBlue** [comment]
@andreasWallner: What we need is a dump of the WSL processes, which you can get by adding `-Dump` to `collect-wsl-logs.ps`.

For some reason the bot didn't trigger, but it should give the exact command for that.

/dumps
