### ISSUE TITLE
Graphical Issues On Virt-Manager

### ISSUE THREAD

**Issue by Windows98SE-dev** [microsoft/WSL#11248]
### Windows Version

Microsoft Windows [version 10.0.22631.3085]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04.4 LTS

### Repro Steps

Run virt-manager

### Expected Behavior

A normal screen

### Actual Behavior

![image_2024-03-04_175550962](https://github.com/microsoft/WSL/assets/152313255/8238b027-9b34-40ee-b0c0-496109f28589)

**Comment by benhillis** [comment]
Should be fixed in https://github.com/microsoft/WSL/releases/tag/2.1.1 and later.
