### ISSUE TITLE
Use a fallback font to display missing characters 

### ISSUE THREAD

**Issue by musm** [Microsoft/WSL#1124]
Use a fallback font to display missing glyphs. This is especially important for mathematical programming using Julia and other console apps that heavily use unicode characters. Unfortunately, most of the monospaced fonts do not have a rich set of glyphs so most things show up blank.

**Comment by bitcrazed** [comment]
Thanks for reporting. This capability is on our backlog for the Console.

**Comment by S-ed** [comment]
Default font now have no Cyrillic, Japanese, Thai etc characters.
This is UNACCEPTABOOOOOL!

**Comment by bitcrazed** [comment]
Thanks for the feedback.

We look forward to the Console being able to render more glyphs, ligature monospace fonts, emoji, etc., but it is dependent on us building a new text renderer based on DirectWrite vs. our current GDI-based renderer.

This is a work item that's starting to get quite close to the top of our priority list, but it's a significant work item, so it'll take a little while to complete.

HOWEVER, we WILL make A LOT of noise when this feature ships, so I'd be surprised if you miss it when we do announce ;)

Closing for now as this is already high up our task list.
