### ISSUE TITLE
How can I troubleshoot intermittent WSL2 system shutdown?

### ISSUE THREAD

**Issue by rfay** [microsoft/WSL#11251]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.1.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

"Default distribution: Ubuntu; Default version: 2"

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop windows 4.27.2

### Repro Steps

Periodically the WSL subsystem on our test runners with Docker Desktop completely crashes. This is intermittent and can't give you repro steps.

However, when it happens *all* WSL2 distros have crashed, both the Ubuntu and the two Docker Desktop distros.

### Expected Behavior

I would like to know how to debug this situation. What causes all of the WSL2 subsystem to crash, all distros to exit? How can I find out? Is it in the Event Log? 

### Actual Behavior

Thanks for any suggestions

### Diagnostic Logs

Unfortunately, the collection of logs requires me to reproduce, and this is intermittent.

**Comment by OneBlue** [comment]
Is WSL crashing or just shutting down ? I'd recommend to follow [these instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#11-reporting-a-wsl-process-crash) to collect the crash if WSL is indeed crashing. 

If not, continuously running log collection until you can get a repro would be the best bet. /logs

**Comment by rfay** [comment]
> Is WSL crashing or just shutting down ? I'd recommend to follow [these instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#11-reporting-a-wsl-process-crash) to collect the crash if WSL is indeed crashing.

That would be one of the questions: How can I tell the difference between crashing and shutting down? What I see after this event is that all (three) distros have exited, so `wsl -l -v` shows 3 stopped distros.

> If not, continuously running log collection until you can get a repro would be the best bet

This happens ever few days, but not more often that that. The test runners run a number of jobs in those days. I'm not sure about the consequences of capturing an infinite amount of logs, or how they're going to be useful to you when we do. Willing to do it though...

**Comment by OneBlue** [comment]
> That would be one of the questions: How can I tell the difference between crashing and shutting down? What I see after this event is that all (three) distros have exited, so `wsl -l -v` shows 3 stopped distros.

The instructions I linked would be the best way: If you see a crash dump in the crash folders, then the WSL process crashed

**Comment by rfay** [comment]
I see [enable automatic crash dump collection](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#enable-automatic-crash-dump-collection) in that article, which put the dump in C:\crashes. 

(I will do that)

But you say
> If you see a crash dump in the crash folders

are you implying that there are other crash folders, or perhaps crash folders other than C:\crashes that I should be looking for?

**Comment by OneBlue** [comment]
No there is only one crash folder
