### ISSUE TITLE
Additional vhdx disk from linux distro recognized as pttype=dos in new wsl linux distro

### ISSUE THREAD

**Issue by borjamunozf** [microsoft/WSL#11250]
### Windows Version

10.0.19044.4046

### WSL Version

2.0.14

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Repro Steps

Developer was using external vhdx as /workspace inside an Ubuntu 20.04 to locate some repositories.
Reinstalled WSL packages,& a customized Ubuntu 22.04.

1. wsl.exe -d Ubuntu-22.04-abc --mount --vhd D:\workspace\workspace.vhdx --bare
2. sudo blkid shows /dev/sdd with PTTYPE="dos"
![imagen](https://github.com/microsoft/WSL/assets/25910927/0d33aaad-e3b5-4ac5-a824-43fcbc867fe7)
3. This does not allow me do e2label or mount it.

### Expected Behavior

VHDX disk from other distro recognized as ext4.
VHDX disk can be mounted in new one.

### Actual Behavior

1. Mounted as --bare vhdx disk from Ubuntu distro is recognized as PTTYPE="dos". Blocks any next step like mounting & seeing the contents inside the new Ubuntu 22 distro, changing e2label.

**Comment by OneBlue** [comment]
Based on this it looks like this VHDX has a dos partition table. What's the output of `cfdisk /dev/<disk>` ?

**Comment by borjamunozf** [comment]
Bad news?
![imagen](https://github.com/microsoft/WSL/assets/25910927/677fba5d-2b95-4790-bcb3-b04eb097e220)

**Comment by borjamunozf** [comment]
God has listened to me:

Could recover the disk & the contents, able to mount now.

Used TestDisk:
- Analyse > Quick Search > Detected Linux ext4.
- First recover & copy important items.
- Then Write partition table, reboot wsl, remount disk & disk recognized properly.


Thanks!
