### ISSUE TITLE
Wsl/Service/CreateInstance/CreateVm/HCS/E_INVALIDARG

### ISSUE THREAD

**Issue by iceuw** [microsoft/WSL#11260]
### Windows Version

10.0.22631.3235

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04

### Repro Steps

wsl -d Ubuntu-20.04

### Expected Behavior

start up the ubuntu subsystem

### Actual Behavior

[process exited with code 4294967295 (0xffffffff)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/HCS/E_INVALIDARG

### Diagnostic Logs

[WslLogs-2024-03-07_10-20-54.zip](https://github.com/microsoft/WSL/files/14517916/WslLogs-2024-03-07_10-20-54.zip)

**Comment by OneBlue** [comment]
Looking at the logs, this is caused by an old Windows build. Can you try to update Windows and see if that solves the issue ?

**Comment by iceuw** [comment]
But my windows hasn't pushed any updates to me.

**Comment by iceuw** [comment]
Here Several of my colleagues' computers have also encountered this issue in the past few days. If it is a version problem, is there any way to roll back the version of WSL?

**Comment by iceuw** [comment]
Sorry， I realized that this problem is caused by my encryption software on my computer.

**Comment by iceuw** [comment]
Sorry，I realized that this problem is caused by my encryption software on my computer.
