### ISSUE TITLE
Version 2.1.4 is marked as release although totally unusable

### ISSUE THREAD

**Issue by Wladastic** [microsoft/WSL#11272]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.1.4

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu-20.04

### Distro Version

Ubuntu-20.04

### Repro Steps

When updating through apt upgrade wsl is upgraded to 2.1.4 which has no functioning Port Forwarding.
When executing the installer for 2.0.14 everything runs smoothly again.

### Expected Behavior

Port forwarding should work when:

netsh interface portproxy delete v4tov4 listenport=7860 listenaddr=0.0.0.0
netsh interface portproxy delete v4tov4 listenport=5000 listenaddr=0.0.0.0

netsh interface portproxy reset

netsh interface portproxy add v4tov4 listenport=7860 listenaddress=0.0.0.0 connectport=7860 connectaddress=$(wsl hostname -I)
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=7860 connectaddress=127.0.0.1 connectport=7860

netsh interface portproxy add v4tov4 listenport=5000 listenaddress=0.0.0.0 connectport=5000 connectaddress=$(wsl hostname -I)
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=5000 connectaddress=127.0.0.1 connectport=5000

### Actual Behavior

IP Service explodes in CPU usage and then keeps crashing

### Diagnostic Logs

A request to allocate an ephemeral port number from the global TCP port space has failed due to all such ports being in use.
and
The IP Helper service terminated unexpectedly.  It has done this 2 time(s).  The following corrective action will be taken in 300000 milliseconds: Restart the service.

**Comment by Wladastic** [comment]
When I install 2.0.14 it just runs without any flaw, dont even have to portproxy wsl to localhost

**Comment by Wladastic** [comment]
> /logs

I did a Network reset, automagically everything works again

**Comment by OneBlue** [comment]
Thank you for confirming. Closing since the repro is gone.

**Comment by Wladastic** [comment]
Apparently the network reset only let the port forwarding run only once.
I figured out why it stopped working:
"A request to allocate an ephemeral port number from the global TCP port space has failed due to all such ports being in use."
Whenever I start a Gradio Server, close it and start it again I get this error.
