### ISSUE TITLE
Error Wsl/0x80070422 starting WSL (Worked fine a week or two ago)

### ISSUE THREAD

**Issue by GrahamDo** [microsoft/WSL#11273]
I tried to start Docker Desktop yesterday, and it gave me an error relating to WSL not being started properly. It suggested I run wsl --shutdown (I think that's the command) or restart my computer. It was working fine... maybe 2/3 weeks ago.

At that point, I didn't really understand Docker for Desktop's dependency on WSL. I've learnt a lot since then.

I launched PowerShell and tried to run a variety of different "wsl" commands, but each one of them comes back with "The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
Error code: Wsl/0x80070422"

I've done a lot of Googling, and one of the first things I found was an article (I think it was actually an issue on this Github) talking about how the LxssManager service was stopped and set to Manual. That fit my scenario, so I started my service and set it to Automatic (I had to do this via an administrative command prompt, because the Services app wouldn't let me change the startup type: "Access Denied").

It didn't solve my problem, though.

While i was in Services, I noticed the "Windows Subsystem for Linux" service was stopped. I tried to start it, but it starts and then immediately stops. And I can't find any entries in the Event Log about it.

I found another article online about how to completely remove all Linux distros and all WSL packages from my machine. I did that, restarted, ran wsl --install, and it installed Ubuntu and asked for the reboot. But immediately after the reboot I got a console window saying "WslRegisterDistribution failed with error: 0x80070422" followed by the same error.

Again, this was working fine a couple of weeks ago, and I remember a recent batch of Windows updates, so perhaps that broke it? 

(Unfortunately, I no longer have the restore point from before those updates were installed)

I'm running Windows 11 Home.

Can anyone make a suggestion as to what the problem might be?

**Comment by GrahamDo** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!

Nope. None of them solve my problem. Although I have seen a couple of them already during my searching.

**Comment by fantinodavide** [comment]
Hi @GrahamDo,

I had the exact same issue, tried many suggested solutions, including making sure windows is updated, set the automatic start of the LxssManager service, nothing of that helped me, but running `wsl --update` and then `wsl --install -d ubuntu` fixed it!

Let me know if this helps!

**Comment by GrahamDo** [comment]
@fantinodavide Thanks for the suggestion, but unfortunately no luck:

![image](https://github.com/microsoft/WSL/assets/2564311/6cbabcf7-43c3-4165-9ee1-cd0ad8867b4b)

I do, however, see that my machine needs a reboot to finish installing updates. If this problem _was_ in fact caused by a Windows Update, then perhaps that'll fix it.

Can't reboot right now, though. I'll do it this afternoon and see if it helps.

**Comment by OneBlue** [comment]
Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):

```
 sc.exe config wslservice start= demand
```

**Comment by GrahamDo** [comment]
> Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> 
> ```
>  sc.exe config wslservice start= demand
> ```

Oh, damn! Who knew there was more than one service? I've been checking the Windows Subsystem For Linux service. I didn't know there was a second service. :-D

True enough, it was disabled. I ran your command, and was able to start wsl and ubuntu, and my Docker Desktop started working again!

That is, until I rebooted to install that update I mentioned earler, and immediately thereafter, the service was disabled again so I had to run the command again.

Why does Windows keep disabling that service? And is there any way I can tell it not to?

**Comment by OneBlue** [comment]
> EDIT: It's not just on Windows Update. It's on _any_ reboot. I just rebooted again, and that service was disabled again. :-(

Hmm that's really weird. Do you have any antivirus software running ? I'm wondering if it could be doing that.

**Comment by GrahamDo** [comment]
I do: AVG. Maybe you're right. I'll do some searching and see if I can find anything specifically about AVG disabling the WSL Service on every boot (because that is still happening).

**Comment by GrahamDo** [comment]
OK, that settles it. It was AVG.

I set the service to Manual, then went into AVG and added "C:\Program Files\WSL\wslservice.exe" to the list of allowed apps, then rebooted, and it stayed Manual.

For anyone else reading this, if you have anti-virus or personal firewall software installed, you should do the same.

**Comment by younes-io** [comment]
> Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> 
> ```
>  sc.exe config wslservice start= demand
> ```

I wish I could pay you for this ! Thank you!!!

**Comment by Caveats** [comment]
As above - but also add Docker and WSL to exceptions list to Anti Virus Software - also restore Docker to Factory Default settings *(nuclear option to wipe both data and settings)

**Comment by Freakazoid1305** [comment]
> Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> 
> ```
>  sc.exe config wslservice start= demand
> ```

Had same issue like the OP, but no antivirus installed. Ur solution helped me run Docker again! It was very frustrating, so many thanks for ur help!

**Comment by OfficiallyCrazy** [comment]
> > Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> > ```
> >  sc.exe config wslservice start= demand
> > ```
> 
> Had same issue like the OP, but no antivirus installed. Ur solution helped me run Docker again but after i reboot pc docker is broken again, same error occurs. From that point ur solution does not help me anymore. I have win11 home. What can it be? I also added wslservice.exe in windows security exclusions.

Same here. WSL is being set to disabled automatically. From aditional reserach I did it seems like some program is running on port 53 and that is preventiong WSL to start

**Comment by wandiro** [comment]
> Thank you @GrahamDo. based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> 
> ```
>  sc.exe config wslservice start= demand
> ```

thanks you  save my live

**Comment by Olney1** [comment]
AVG was installed in my issue too. The command ` sc.exe config wslservice start= demand` worked for me running from PowerShell with elevated permissions.

**Comment by Farzane2630** [comment]
I ran into the same error and tried out the entire solutions on the internet and the error still was there.
But at the end of the day I came up with this command and it works!😉
wsl --install -d Debian --web-download

Apparently, there was some problems with my windows and for some reason I was not able to download this distribution from MS.
I hope this works for you guys too.

**Comment by AbadonnaAbbys** [comment]
In my case I get same error when I "sleep on" "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17" application by the CCleaner. And after switched this application on, WSL work fine again.

**Comment by denis-beurive** [comment]
> Thank you [@GrahamDo](https://github.com/GrahamDo). based on the logs it looks like wslservice is disabled. Does the following command solve the issue (elevated command prompt):
> 
> ```
>  sc.exe config wslservice start= demand
> ```

I recently encountered the same issue, and this command successfully resolved it.

For your information, I found that the problem arose after my antivirus (AVAST) performed a system cleanup.

**Comment by Camila0400** [comment]
Gente eu devo dar os parabéns para quem deixou o comentário com o comando ( sc.exe config wslservice start= demand ) resolveu totalmente o meu problema eu já tinha tentado de tudo vou deixar umas observações aqui viu:

Erro Wsl/0x80070422 ao iniciar o WSL (funcionou bem há uma ou duas semanas)

site ensinando como resolver esse erro:
https://github.com/microsoft/WSL/issues/11273

passo 1:
Certo, isso resolve. Era AVG.

Configurei o serviço como Manual, depois entrei no AVG e adicionei "C:\Arquivos de Programas\WSL\wslservice.exe" à lista de aplicativos permitidos, reiniciei e continuou como Manual.

Para qualquer outra pessoa que esteja lendo isso, se você tiver um software antivírus ou firewall pessoal instalado, faça o mesmo.

passo 2:  sc.exe config wslservice start= demand

passo 3 caso o passo 2 não funcione: wsl --install -d Debian --web-download

No WSL (Windows Subsystem for Linux), você não deve rodar os comandos como se estivesse no PowerShell ou no terminal do Windows. Quando você abre o WSL, você precisa estar dentro do terminal da distribuição Linux (como o Ubuntu) para poder executar comandos como sudo apt update ou sudo apt upgrade.

Como resolver:
Abra o terminal do Ubuntu (WSL):

Digite wsl no PowerShell ou no menu iniciar para abrir o terminal do Ubuntu (ou a distribuição Linux que você está utilizando).

Dentro do terminal Ubuntu (WSL), execute os comandos de atualização:

Para atualizar os repositórios, use:

bash
Copiar código
sudo apt update
Para atualizar os pacotes, use:

bash
Copiar código
sudo apt upgrade
Se você estiver no PowerShell e tentar usar o apt, o comando não funcionará porque apt é um comando específico do Linux, e não do PowerShell.

Importante:
Sempre execute os comandos relacionados ao Linux dentro do terminal do Ubuntu ou da distribuição Linux que você configurou no WSL, não no PowerShell do Windows.

----

Para verificar o estado dos pacotes instalados e continuá-los, use:

(bash)
{Copiar código}
sudo apt update
sudo apt upgrade

ou por ultima opção caso nenhuma dessas funcione você tenta:
O erro **"O serviço não pode ser iniciado porque está desativado ou não tem dispositivos ativados associados. Código de erro: Wsl/0x80070422"** está relacionado a um problema de ativação do **Windows Subsystem for Linux (WSL)** no seu sistema. Esse erro é normalmente causado por serviços essenciais do **WSL** que estão desativados ou não configurados corretamente.

### Vamos tentar as seguintes soluções passo a passo para corrigir esse erro:

### 1. **Verificar e Ativar o Serviço LxssManager**

O erro pode estar relacionado ao serviço **LxssManager**, que é responsável pela execução do **WSL**. Vamos garantir que esse serviço esteja ativo.

#### Passo 1: Abrir o **PowerShell** como Administrador
- Clique com o botão direito em **Iniciar** e escolha **Windows PowerShell (Admin)**.

#### Passo 2: Tentar iniciar o serviço **LxssManager**
Execute o comando abaixo para tentar iniciar manualmente o serviço **LxssManager**:

```powershell
sc start LxssManager
```

Se o serviço não puder ser iniciado ou não existir, passe para o próximo passo.

### 2. **Habilitar os Recursos Necessários do WSL**

Certifique-se de que os recursos necessários do **WSL** estão habilitados. Execute os seguintes comandos no **PowerShell** (como Administrador) para ativar o **WSL**, **Hyper-V**, e **Virtual Machine Platform**:

#### Passo 1: Ativar o **WSL**, **Hyper-V** e a **Plataforma de Máquina Virtual**

```powershell
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:Microsoft-Hyper-V-All /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

Esses comandos garantem que os componentes necessários para o **WSL 2** sejam ativados corretamente.

#### Passo 2: Reiniciar o Sistema

Após executar os comandos, reinicie o computador para garantir que as alterações sejam aplicadas.

### 3. **Ativar a Virtualização no BIOS/UEFI**

A **virtualização** precisa estar ativada no **BIOS/UEFI** para que o **WSL 2** funcione corretamente. Isso é especialmente importante para as versões do **WSL 2** que dependem do **Hyper-V**.

#### Passo 1: Acessar o BIOS/UEFI
- Durante o boot, pressione a tecla **F2** ou **DEL** (dependendo do modelo do seu PC) para acessar o **BIOS/UEFI**.

#### Passo 2: Ativar a **Virtualização**
- No BIOS, procure por **Intel VT-x** ou **AMD-V** (dependendo do seu processador) e **habilite** essas opções.
- Salve as configurações e saia do BIOS.

### 4. **Reparar a Imagem do Windows**

Execute o comando **DISM** para reparar a imagem do Windows e corrigir problemas relacionados à instalação de componentes do sistema.

#### Passo 1: Reparar a Imagem
No **PowerShell (Admin)**, execute o seguinte comando:

```powershell
dism.exe /online /cleanup-image /restorehealth
```

Isso irá verificar e corrigir possíveis problemas com a instalação do sistema.

#### Passo 2: Tentar novamente instalar o WSL
Após a reparação, tente novamente rodar o comando de instalação do **WSL**:

```powershell
wsl --install
```

### 5. **Verificar e Atualizar o Windows**

Se o problema persistir, verifique se o **Windows** está atualizado, pois algumas correções de bugs podem ser aplicadas em atualizações mais recentes.

1. Vá para **Configurações > Atualização e Segurança > Windows Update**.
2. Clique em **Verificar atualizações** e instale todas as atualizações disponíveis.

### 6. **Reinstalar o WSL**

Se nada funcionar, você pode tentar desinstalar o **WSL** completamente e, em seguida, reinstalá-lo. Para isso, siga os passos abaixo:

#### Passo 1: Desinstalar o WSL
Execute o seguinte comando para desinstalar a distribuição **Ubuntu** do **WSL**:

```powershell
wsl --unregister Ubuntu
```

Se o comando falhar, você pode tentar reiniciar o computador e tentar novamente.

#### Passo 2: Reinstalar o WSL
Após desinstalar o **WSL**, tente reinstalá-lo com o seguinte comando:

```powershell
wsl --install
```

Isso deve reinstalar o **WSL 2** e o **Ubuntu** como a distribuição padrão.

---

### Resumo das Soluções:
1. **Tentar iniciar o serviço LxssManager**.
2. **Habilitar os recursos necessários do WSL** com **DISM**.
3. **Ativar a virtualização no BIOS/UEFI**.
4. **Reparar a imagem do Windows com DISM**.
5. **Verificar atualizações do Windows**.
6. **Desinstalar e reinstalar o WSL**.

Após seguir esses passos, se o erro persistir, por favor, compartilhe mais detalhes para que possamos continuar investigando a solução.

**Comment by poznianski** [comment]
> In my case I get same error when I "sleep on" "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17" application by the CCleaner. And after switched this application on, WSL work fine again.

thanks, it was exactly my case

**Comment by weto4ka** [comment]
> Hi [@GrahamDo](https://github.com/GrahamDo),
> 
> I had the exact same issue, tried many suggested solutions, including making sure windows is updated, set the automatic start of the LxssManager service, nothing of that helped me, but running `wsl --update` and then `wsl --install -d ubuntu` fixed it!
> 
> Let me know if this helps!

Fixed it for me. I had also issue with Docker *error Wsl/0x80070422). update helped to fix it. 

Ps. next time i opened docket it was as well not working, what really fixed my issue, is that i need first t start manually WSL app on my windows, with double clicking it, and then it all starts to work so not the update fixed it, but starting WSL app in reality (the one with blue pinguin icon)

**Comment by 0XOPx** [comment]
Dude, i have this same issue!
(polish windows)

<img width="1113" height="626" alt="Image" src="https://github.com/user-attachments/assets/50336214-6d6b-4144-ab86-cb0490ab423a" />
