### ISSUE TITLE
Unable to run WSL2 as LocalSystem user

### ISSUE THREAD

**Issue by Tiklyt** [microsoft/WSL#11280]
### Windows Version

Microsoft Windows [version 10.0.22631.3155]

### WSL Version

Version WSL : 2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu

### Repro Steps

Create a service in any Language and run any wsl command with wsl.exe

### Expected Behavior

The behavior I want to be able to run WSL command as LocalSystem.

### Actual Behavior

Run I run any wsl command I got error  : Access Denied

**Comment by OneBlue** [comment]
This is unfortunately by design. WSL is tied to a user profile so it's not possible to run WSL as LocalSystem
