### ISSUE TITLE
wsl: Mirrored networking mode is not supported, falling back to NAT networking

### ISSUE THREAD

**Issue by devlancer412** [microsoft/WSL#11283]
### Windows Version

Microsoft Windows [Version 10.0.19045.4046]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04.3

### Repro Steps

I set network mode to mirrored on .wslconfig and restart wsl.
But wsl returns this error

### Expected Behavior

Can't call localhost ports on wsl

### Actual Behavior

Can't use correct network mode

### Diagnostic Logs

![image](https://github.com/microsoft/WSL/assets/101313445/813a61b3-a512-4988-952c-821d47679a48)

[WslLogs-2024-03-11_09-08-36.zip](https://github.com/microsoft/WSL/files/14559103/WslLogs-2024-03-11_09-08-36.zip)

**Comment by OneBlue** [comment]
This is unfortunately by design. Mirrored networking is only supported on Windows 11.

**Comment by reoLantern** [comment]
Is there any plan to support this feature on Windows 10?

**Comment by valinet** [comment]
Yeah, why not support it on Windows 10 and Server 2022? There are many places where this would be useful, yet upgrading to Windows 11 is not yet possible. Please reconsider the decision, like you did with WSLg which everyone is grateful about.

**Comment by bpsib** [comment]
The annoying thing is Mirrored appears as an option in the WSL networking settings Windows 10 which tricked me into thinking it was supported when it isn't.
