### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070057

### ISSUE THREAD

**Issue by karashiiro** [microsoft/WSL#11284]
### Windows Version

Microsoft Windows [Version 10.0.22621.3235]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 20.04.6 LTS

### Repro Steps

Unclear, I had a power outage and WSL was broken when I started my computer again - nothing else appears to be broken.

### Expected Behavior

WSL registers the Linux distro successfully.

### Actual Behavior

When starting an existing WSL installation using Ubuntu 20.04, it failed with an error: `Error code: Wsl/Service/CreateInstance/CreateVm/HCS/E_INVALIDARG`.

I unregistered the distro and attempted to install Ubuntu 20.04.06 LTS, and was unable to do so successfully (both on WSL 1 and WSL 2). The error I get when booting the distro is now `WslRegisterDistribution failed with error: 0x80070057`. I also tried installing Debian and got the same error. I've been experiencing this issue for a few days now, and attached two sets of logs from both when I started seeing this and today.

### Diagnostic Logs

https://github.com/microsoft/WSL/files/14559913/WslLogs-2024-03-09_15-34-38.zip
https://github.com/microsoft/WSL/files/14559914/WslLogs-2024-03-11_07-13-32.zip

**Comment by OneBlue** [comment]
Thank you for reporting this @karashiiro. It looks like your Hyper-V firmware might be expired. Can you share the output of: 
(powershell)
``` 
(Get-Item C:\Windows\System32\vmfirmware.dll).VersionInfo
```

**Comment by karashiiro** [comment]
```
ProductVersion   FileVersion      FileName
--------------   -----------      --------
10.0.22621.1     10.0.22621.1 (W… C:\Windows\System32\vmfirmware.dll
```

**Comment by OneBlue** [comment]
Thank you @karashiiro. These versions look correct. Let's look at the signatures. Can you share the output of: 
(powershell)
```
Get-AuthenticodeSignature c:\windows\system32\vmfirmware.dll | select *
```

**Comment by karashiiro** [comment]
```
SignerCertificate      : [Subject]
                           CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Windows Production PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000004158295A1A3D82E2857000000000415

                         [Not Before]
                           2/2/2023 4:05:42 PM

                         [Not After]
                           1/31/2024 4:05:42 PM

                         [Thumbprint]
                           8870483E0E833965A53F422494F1614F79286851

TimeStamperCertificate : [Subject]
                           CN=Microsoft Time-Stamp Service, OU=Thales TSS ESN:0842-4BE6-C29A, OU=Microsoft Ireland Operations Limited, O=Microsoft Corporation,
                         L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Time-Stamp PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000001DA8ED5C95A00D111B10001000001DA

                         [Not Before]
                           10/12/2023 12:06:59 PM

                         [Not After]
                           1/10/2025 11:06:59 AM

                         [Thumbprint]
                           42A21F2189631D46CDA18D3FC23857467FEC480D

Status                 : Valid
StatusMessage          : Signature verified.
Path                   : C:\windows\system32\vmfirmware.dll
SignatureType          : Catalog
IsOSBinary             : True
```

**Comment by OneBlue** [comment]
Thank you @karashiiro. Looking at the logs again this issue might be caused by a corrupted WSL installation. 

Can you try to run `wsl.exe --update --pre-release` to see if that solves the issue ?

**Comment by karashiiro** [comment]
That gave another error:
```
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.5.
The older version of Windows Subsystem for Linux cannot be removed.  Contact your technical support group.
Update failed (exit code: 1603).
Log file: C:\Users\luca\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/ERROR_INSTALL_FAILURE
```

Logs: [wsl-install-logs.txt](https://github.com/microsoft/WSL/files/14579369/wsl-install-logs.txt)

**Comment by OneBlue** [comment]
Hmm it does indeed look like a corrupted installation. Does manually downloading the [MSI](https://github.com/microsoft/WSL/releases/download/2.1.5/wsl.2.1.5.0.x64.msi)  helps ? 

If that doesn't work, you can also try: `Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers   | Remove-AppxPackage` in an elevated powershell

**Comment by karashiiro** [comment]
Manual MSI installation failure: ![image](https://github.com/microsoft/WSL/assets/49822414/0b351657-b1bb-4a6a-b375-f1599009e7d3)
Tries and fails to read `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_2.0.9.0_x64__8wekyb3d8bbwe\wsl.msi`, which indeed does not exist.

Cancelling gives this before exiting:
![image](https://github.com/microsoft/WSL/assets/49822414/49ccd3f9-908f-46a8-bafb-32e747528e9c)

The command doesn't give an error, and attempting to `wsl --install -d Ubuntu-20.04` now works 🚀 

Attempting to run `wsl --update` afterwards causes it to break again in the same way, but re-running the PowerShell command fixes it.

**Comment by karashiiro** [comment]
While it's concerning that `wsl --update` breaks things again, my WSL installation seems to otherwise be working now, so thank you for all your help!

**Comment by OneBlue** [comment]
Interesting. It looks like your machine is hitting some sort of MSIX issue where the MSIX package doesn't properly install. Closing for now since the issue is resolved.

**Comment by startergo** [comment]
Same s**t again:
```
PS C:\Windows\System32> (Get-Item C:\Windows\System32\vmfirmware.dll).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
10.0.27764.1000  10.0.27764.1000… C:\Windows\System32\vmfirmware.dll
 Get-AuthenticodeSignature c:\windows\system32\vmfirmware.dll | select *

SignerCertificate      : [Subject]
                           CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Development PCA 2014, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000006E65A10D4FA641B41150000000006E6

                         [Not Before]
                           7/17/2024 5:16:46 PM

                         [Not After]
                           9/15/2025 5:16:46 PM

                         [Thumbprint]
                           CA76BD7051E43A78AD45D94981181E36F107FE9E

TimeStamperCertificate :
Status                 : Valid
StatusMessage          : Signature verified.
Path                   : C:\windows\system32\vmfirmware.dll
SignatureType          : Catalog
IsOSBinary             : True
PS C:\Windows\System32> wsl.exe --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.4.8.
The older version of Windows Subsystem for Linux cannot be removed.  Contact your technical support group.
Update failed (exit code: 1603).
Log file: C:\Users\G5\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/ERROR_INSTALL_FAILURE
PS C:\Windows\System32> Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers   | Remove-AppxPackage
PS C:\Windows\System32> Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers   | Remove-AppxPackage
PS C:\Windows\System32> wsl.exe --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.4.8.
The older version of Windows Subsystem for Linux cannot be removed.  Contact your technical support group.
Update failed (exit code: 1603).
Log file: C:\Users\G5\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/ERROR_INSTALL_FAILURE
```

**Comment by karashiiro** [comment]
This broke again a few months after the issue was resolved and I didn't get around to fixing it until now - the crux of the issue appears to have been a dangling entry in the Windows Installer Products database, and deleting that finally fixed the issue and allowed installations to work properly again.

This should be the rough solution:

Delete the old uninstaller registry entry:
```powershell
winget install Microsoft.WSL
# Check the installer log path in the error output

# Check registry uninstall entries
Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where-Object {$_.DisplayName -like "*Windows Subsystem*"}

# Check for leftover program files
Test-Path "C:\Program Files\WSL\"

# Check Windows Installer cache for the PSChildName (product code in this case) of the old installation
Get-ChildItem "HKLM:\SOFTWARE\Classes\Installer\Products\" | ForEach-Object {
    $props = Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue
    if ($props.ProductName -like "*Windows Subsystem*") {
        Write-Host "Found: $($_.PSChildName) - $($props.ProductName)"
    }
}

Remove-Item "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{OLD-PRODUCT-CODE}" -Force
```

Delete any actual installations still hanging around:
```powershell
# Stop WSL services first
Stop-Service LxssManager -Force -ErrorAction SilentlyContinue
Stop-Service WslService -Force -ErrorAction SilentlyContinue
Get-Process *wsl* | Stop-Process -Force -ErrorAction SilentlyContinue

# Remove files
Remove-Item "C:\Program Files\WSL\" -Recurse -Force
```

Delete the dangling entry from the installer cache:
```powershell
# Remove cached product entry (use the same product code from before)
Remove-Item "HKLM:\SOFTWARE\Classes\Installer\Products\{CACHED-PRODUCT-ID}" -Recurse -Force
```

Reinstall WSL:
```
winget install Microsoft.WSL
wsl --install -d Debian  # or your preferred distribution
```

---

And after all that I have a fully-working WSL installation again. For the record, I just threw the error into Claude Code and followed its debugging steps for a few hours until it finally got a working solution - I uploaded the final issue report here for posterity (mind the dramatization): https://claude.ai/public/artifacts/ecf56871-0e93-4e77-b3da-9c6afaa9f77f

Also attached as a file in case that link dies: [WSL Error 0x80070057.md](https://github.com/user-attachments/files/21827244/WSL.Error.0x80070057.md)
