### ISSUE TITLE
disable wsl by accident in "Turn Windows Features on or off"

### ISSUE THREAD

**Issue by ChanCody** [microsoft/WSL#11296]
### Windows Version

win 10 pro, 19045.2486

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu16.04

### Repro Steps

1. Install wsl & ubuntu16.04
2. In Start Menu > Turn Windows Features on or off: disable **Virtual Machine Platform** and **Windows Subsystem for Linux**
3. In Start Menu > Turn Windows Features on or off: enable **Virtual Machine Platform** and **Windows Subsystem for Linux**
4. Will wsl get reinstalled after I reboot my computer?

### Expected Behavior

This is not a bug but rather a misoperation. I’m reporting it as a bug because I’m eagerly awaiting the outcome. I have a lot of data and development configurations in my WSL, so I hope this misoperation won’t erase everything.

How I did this: I have two computers A & B. I was operating B from A by Windows Remote. I wanted to reinstall wsl on B but operated A instead...

### Actual Behavior

None

**Comment by OneBlue** [comment]
On Windows 11 WSL requires the optional component to run. As long as you re-enable it and reboot, WSL and your distros will be available.
