### ISSUE TITLE
I want to execute the npm installation command in Windows, but it is automatically running in WSL2.

### ISSUE THREAD

**Issue by zhao-wuyan** [microsoft/WSL#11294]
### Windows Version

Microsoft Windows [版本 10.0.22631.3235]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.146.1

### Distro Version

Ubuntu 22.04

### Repro Steps

I want to upgrade the npm version, but encountered an error when following the tutorial.

I recently upgraded to 23h2 and enabled the wls2 mirrored network mode.

1. `npm install --force -g n`
2. `n stable`

then

![image](https://github.com/microsoft/WSL/assets/59789646/07299776-7fb8-4cb9-b2d6-d2a3776c2ecc)

When I type bash. terminal opened WSL. Is this correct?

![Clip_2024-03-13_15-14-24](https://github.com/microsoft/WSL/assets/59789646/6e9688c9-2427-4c50-a48f-ededbd602165)

### Expected Behavior

execution on Windows

### Actual Behavior

The corresponding command is not executed on the correct system

**Comment by OneBlue** [comment]
`bash.exe` is indeed an entrypoint for WSL. This is the expected behavior.
