### ISSUE TITLE
unable to open wsl 2 in windows 11

### ISSUE THREAD

**Issue by maheshshali25** [microsoft/WSL#11314]
### Windows Version

Microsoft Windows [10.0.22631] 

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04.6 

### Repro Steps

Step 1: press Win key
Step 2: search wsl
Step 3: click open

### Expected Behavior

expected result, it should open wsl terminal

### Actual Behavior

terminal is not opening

### Diagnostic Logs

when i run wsl.exe --version, it's showing the below error

Class not registered
Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG

**Comment by pmartincic** [comment]
/logs
Are you missing any of the prerequisites? Virtual Machine Platform?

**Comment by pmartincic** [comment]
This looks the same as /dupe #11282
