### ISSUE TITLE
Error code: Wsl/Service/AttachDisk/E_INVALIDARG

### ISSUE THREAD

**Issue by HadiSDev** [microsoft/WSL#11317]
### Windows Version

Microsoft Windows [Version 10.0.23620.1000]

### WSL Version

WSL version: 2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Repro Steps

Try to attach a vhdx file with mount command:
`wsl --mount I:\WSLDistro.vhdx`

### Expected Behavior

Should just attach the disk file with no issue

### Actual Behavior

The parameter is incorrect.
Error code: Wsl/Service/AttachDisk/E_INVALIDARG

**Comment by HadiSDev** [comment]
[WslLogs-2024-03-22_11-51-49.zip](https://github.com/microsoft/WSL/files/14721481/WslLogs-2024-03-22_11-51-49.zip)

**Comment by OneBlue** [comment]
Thank you @HadiSDev. Looks like you're trying to mount a vhd file. 

Does this work for you ? 

```
wsl --mount I:\WSLDistro.vhdx --vhd
```

**Comment by HadiSDev** [comment]
> Thank you @HadiSDev. Looks like you're trying to mount a vhd file.
> 
> Does this work for you ?
> 
> ```
> wsl --mount I:\WSLDistro.vhdx --vhd
> ```

I get this now:
Failed to attach disk '\\?\I:\WSLDistro.vhdx' to WSL2: Access is denied.
Error code: Wsl/Service/AttachDisk/MountVhd/HCS/E_ACCESSDENIED

**Comment by OneBlue** [comment]
Does your user account have permission to edit this file ? You can also try as administrator.
