### ISSUE TITLE
Updating Windows Subsystem for Linux to version: 2.1.5 hangs

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#11313]
### Windows Version

Microsoft Windows [Version 10.0.22635.3350]

### WSL Version

10.0.22635.3350

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1

### Distro Version

arch linux

### Repro Steps

Run

`    wsl --update --pre-release` 
    
  
  
  

### Expected Behavior

Update would be installed

### Actual Behavior

Reports
  
```
Starting WSL ...
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.5
```

Then just hangs

**Comment by mwoodpatrick** [comment]
Running 

wsl --update --pre-release

As an admin did complete normally, however when I try to run a powershell script it now reports:

```
.\boot_wsl.ps1 : File C:\Users\mlwp\boot_wsl.ps1 cannot be loaded because running scripts is disabled on this system.
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\boot_wsl.ps1
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

```
I can run scripts as an admin

Running:

`Get-ExecutionPolicy -List`

I get:

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process    Unrestricted
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted
```

Please advise

**Comment by pmartincic** [comment]
Have you tried setting the execution policy? For the issue you saw the first time, is it possible there was a UAC prompt that didn't get brought to the foreground? I've seen that happen before.

**Comment by mwoodpatrick** [comment]
Many thanks for your reply. I think I missed the UAC prompt, installation on a second PC worked fine. Setting the security policy did work, not sure how it got changed.
