### ISSUE TITLE
xdg-open moves to the next line without opening the file / link

### ISSUE THREAD

**Issue by MwaniN** [microsoft/WSL#11315]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04.3 LTS

### Other Software

Chrome Version 122.0.6261.112 
Any software

### Repro Steps

Type `$ xdg-open https://www.google.com`  into the Ubuntu command line in WSL
Press `Enter` 
_alternatively_
Try to open any text or video file locally using `$ xdg-open {filename}`
Then press `Enter` on the keyboard

### Expected Behavior

The link should open in the default application
_or_
The file should open in the default application

### Actual Behavior

The cursor goes to the next line and sits there blinking
Without doing anything
I need to Ctrl + C to kill the process 

This was also working fine until quite recently, as I had already reinstalled after upgrading to Ubuntu 22.04 using the PPA version as described [here](https://wslutiliti.es/wslu/install.html).

### Diagnostic Logs

strace for xdg-open is [here](https://gist.github.com/MwaniN/a581f3714d35ebb74a39f5a870684bb0)

I tried to get the WSL logs with the .ps1 file yet it would show some red text at the top and crash when I tried to run it in PowerShell. Please let me know if the logs are still necessary and I'll try the other way. Thank you.

**Comment by pmartincic** [comment]
What am I missing? From the strace xdg-open is printing the help menu. Something is missing and this seems like a usage issue. I don't see how this is a wsl issue.

```
[pid 743290] write(1, "xdg-open - opens a file or URL i"..., 147xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

) = 147
