### ISSUE TITLE
[Only 2.1.5.0] Error code: Wsl/Service/CreateInstance/MountVhd/HCS/E_ACCESSDENIED

### ISSUE THREAD

**Issue by RickoNoNo3** [microsoft/WSL#11323]
### Windows Version

10.0.19045.4170

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

0.15.146.1-2

### Distro Version

Ubuntu 22.04 (from imported vhdx)

### Other Software

Both Docker and my own distro

### Repro Steps

Update from an old WSL version to 2.1.5.0, then starting any of WSL distros will get the Error code: `Wsl/Service/CreateInstance/MountVhd/HCS/E_ACCESSDENIED`

Downgrading to 2.1.4.0 fully solved it.

Here is [another report on StackExchange](https://superuser.com/a/1835136/1159688)(not mine) that is same as my issue and is consistent with my solution

### Expected Behavior

Run successully

### Actual Behavior

Error code: Wsl/Service/CreateInstance/MountVhd/HCS/E_ACCESSDENIED

**Comment by Morrigan-Ship** [comment]
same problem

**Comment by rtentser** [comment]
Same problem, downgrading didn't help

**Comment by rtentser** [comment]
Update to 2.2.4 helped

**Comment by rtentser** [comment]
But after reboot it's broken again

**Comment by rtentser** [comment]
So, after reboot it's broken with this error code, but after about 3 minutes of waiting it works

**Comment by rtentser** [comment]
Same problem, downgrading didn't help

UPD1: Update to 2.2.4 helped
UPD2: But after reboot it's broken again
UPD3: So, after reboot it's broken with this error code, but after about 3 minutes of waiting it works
UPD4: Can reproduce with imported from external drive instance, but not with default ubuntu installation

**Comment by cramirezmartin** [comment]
I have the same problem:

Failed to attach disk 'D:\Development\Ubuntu2204\ext4.vhdx' to WSL2: Access is denied.
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/E_ACCESSDENIED

WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.525

**Comment by Morrigan-Ship** [comment]
i solved:
change full permission of drive that contain *.vhdx file of wsl change permission to everyone with sub folders and subfiles
if its drive c:\ dont do this it will destroy your Windows OS

**Comment by FortiJeremy** [comment]
I had the same problem, and was able to just grant full control to "Hyper-V Administrators" for the VHD itself to fix this issue. A little less invasive then granting everyone permissions to the entire drive.

**Comment by marcelobastos** [comment]
I have the same problem when a _**move**_ distros to another location using the comand wsl --manage, but it doesn't happing after the process finish. The error ocurred another day after I have installed another instance. 

My wird solution was _**set default user**_ in inicialization and, apparentelly, word well. Even thought, I'm not convinced that is the solution.
`wsl --manage Ubuntu --move "D:\WSL\Ubuntu"`
After error:
`wsl --manage Ubuntu --set-default-user marcelo`
A operação foi concluída com êxito.
