### ISSUE TITLE
An unremovable Linux icon shows up on the desktop upon install

### ISSUE THREAD

**Issue by adrianghc** [microsoft/WSL#11325]
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Install WSL on a new machine through this command: `wsl --install -d Ubuntu` (I suppose the `-d` argument doesn't make a difference.)

### Expected Behavior

A Linux icon should be added to the File Explorer sidebar and nowhere else (not the desktop).

### Actual Behavior

Upon install, a Linux icon appears on the desktop that cannot be removed other than through registry changes ([see here](https://www.brainbytez.nl/windows/windows-11-hide-remove-wsl-linux-icon-from-desktop/)). The icon is equivalent to the one on the File Explorer sidebar and takes you to `\\wsl$`. (The icon in the sidebar is still created.)

![image](https://github.com/microsoft/WSL/assets/11506007/93773fa7-eecd-4f43-b378-f5386d718fcc)

This is new and unexpected behavior, as previously, an icon would only be added to the sidebar, not the desktop. It also only happens on new installs. On another machine where WSL has been installed and continually updated (through the Microsoft Store and GitHub) since July 2022, no desktop icon appears even after updating to the latest WSL version.

**Comment by pmartincic** [comment]
I think this icon is from the ubuntu appx package? We're not going to have control over this.

**Comment by adrianghc** [comment]
What do you base this on, and so conclusively at that? Nothing about this says to me that it's from Ubuntu. I have two accounts on this machine, only one of them has Ubuntu installed, yet this icon appears on both. Can you point me to some evidence that this is from the Ubuntu package?
