### ISSUE TITLE
Bezel build from scratch hangs indefinitely

### ISSUE THREAD

**Issue by 4creators** [Microsoft/WSL#1132]
- A brief description

Latest Bezel build on Oracle JDK 8 fails by hanging indefinitely at initial command. To reproduce clone Bezel repository and start build from scratch as described on Bezel website [Installing Bezel](https://bazel.io/versions/master/docs/install.html)

**Comment by muojp** [comment]
seems dupl https://github.com/Microsoft/BashOnWindows/issues/620

**Comment by benhillis** [comment]
Closing out old issues. Much has changed since 2016, please reopen a new issue if you continue to have issues building bezel.
