### ISSUE TITLE
WSL2 will occur network mirrored mode isn't supported, fallback to NAT mode

### ISSUE THREAD

**Issue by dnisqa** [microsoft/WSL#11333]
### Windows Version

Micorsoft Windows 10 Pro [10.0.19045.4170]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.15.146.1@WSL2
4.4.0-19041@WSL1

### Distro Version

Ubuntu 20.04 & 22.04

### Other Software

No!

### Repro Steps

.wslconfig is below
[wsl2]
memory=4G
processors=2
networkingMode=mirrored
dnsTunneling=true
autoProxy=false
ipv6=true
#dhcp=false
localhostforwarding=true
[experimental]
sparseVhd=true
firewall=false

Test 1 (WSL setup to version 2)
wsl --set-default-version 2
wsl --install -d Ubuntu-22.04
Windows log will show
1. Mirrored mode isn't support , fallback to NAT mode
2. dnsTunneling isn't support
![WSL2-mirrored_dnsTunnel_not_support](https://github.com/microsoft/WSL/assets/42328219/97361dae-5984-4fda-a27d-3d952811eddb)

wsl --shutdown
wsl --unregister Ubuntu

Test 2 (WSL setup to version 1)
wsl --set-default-version 1
wsl --install -d Ubuntu-22.04
Windows log doesn't show WSL warning message

### Expected Behavior

WSL2 should support mirrored and dnsTunneling

### Actual Behavior

Mirrored is not support
DnsTunneling is not support

**Comment by craigloewen-msft** [comment]
Please see the duplicated issues below, this is due to your Windows version not being correct. Please upgrade to Win11 latest and you should be able to use these features!

/dupe#11283
