### ISSUE TITLE
WSL fresh install reports Error: 0x80070422

### ISSUE THREAD

**Issue by mj8w** [microsoft/WSL#11336]
### Windows Version

Version 10.0.22631.3296

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.146.1-2

### Distro Version

Ubuntu

### Repro Steps

Installed WSL
wsl --install -d Ubuntu
Rebooted
wsl

Results in:
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
Error code: Wsl/0x80070422

### Expected Behavior

Linux terminal prompt

### Actual Behavior

C:\Users\mike>wsl
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
Error code: Wsl/0x80070422

**Comment by mj8w** [comment]
Added requested log file:
[WslLogs-2024-03-21_19-34-35.zip](https://github.com/microsoft/WSL/files/14716534/WslLogs-2024-03-21_19-34-35.zip)

**Comment by OneBlue** [comment]
Thank you @mj8w. 

Based on the logs it looks like wslservice is disabled. Does running (elevated command prompt): 

```
sc.exe config wslservice start= demand
```

Solve the issue ?

**Comment by mj8w** [comment]
Yes, that fixed it. Not sure how it got disabled...

**Comment by mj8w** [comment]
Thanks for the help!
