### ISSUE TITLE
How to enable Alt-A keyboard shortcut in Windows' Bash 

### ISSUE THREAD

**Issue by yuvval** [Microsoft/WSL#1133]
- A brief description

I SSH with WSL Bash to another machine where I use an app that needs to receive the "Alt-A" keyboard sequence.
However it doesn't work, I get an error sound when I press Alt-A.
Yet, pressing Alt-X (in emacs through SSH) works

How can I allow the Alt-A keyboard shortcut?
- Your Windows build number

14393.187
- Steps / All commands required to reproduce the error from a brand new installation 

install `tmux` on a remote machine
edit the file `~/.tmux.conf` with

```
# Changes prefix from Ctrl-b to Alt-a
unbind C-b
set -g prefix M-a
```

Start the `tmux` application and press Alt-A

**Comment by zadjii-msft** [comment]
So I'm running through some test cases, I think I got it figured out 
 - Alt-a works fine in emacs on WSL without bash.
 - Alt-a works fine in emacs on a remote machine connected via ssh from WSL
 - bind-key M-a display foobar works within a tmux session on a remote machine connected via ssh from WSL
 
So I think it might be the fact that your tmux.conf hasn't reloaded. Make sure all your tmux session are closed (`tmux list-sessions`), then try again. tmux only reloads the tmux.conf if there are no previous sessions, or as I have in my .tmux.conf: 
 ```
 bind R source-file ~/.tmux.conf 
 ```

**Comment by yuvval** [comment]
You are right. Yet, the issue still happens if press Alt-A too fast or too repeatedly. In that case I need to wait for a few seconds before hitting it, otherwise I will get the error sound again.

**Comment by zadjii-msft** [comment]
That sounds external to conhost, either tmux or ssh maybe. M-a works as the prefix key for you now, correct? I'm trying out that scenario and i can't get the repeated beeping to reproduce. 

 - On the remote machine I've bound M-a to the prefix, and relaunched tmux
 - On the local machine, I'ev tried both without tmux running, and with tmux running (with leaving the prefix bound to C-b), and neither connection produces beeping.

**Comment by zadjii-msft** [comment]
@yuvval any update on this bug? It does kinda sound similar to an issue I had been investigating with `byobu` for a while, but I never got it to repro in plain `tmux`.

**Comment by yuvval** [comment]
Hi Mike,
I haven't tried it since the last time I wrote you.

Best
Yuval

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
