### ISSUE TITLE
WSL can no longer be uninstalled since Windows 11 22631.3371

### ISSUE THREAD

**Issue by adrianghc** [microsoft/WSL#11349]
### Windows Version

Microsoft Windows [Version 10.0.22631.3371]

### WSL Version

2.0.15.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Repro Steps

Install WSL through any of the available means.

### Expected Behavior

WSL should appear as an app in the apps list and be uninstallable in Settings under Apps > Installed Apps.

### Actual Behavior

WSL can no longer be uninstalled since Windows 11 22631.3371, i.e., the update in the Release Preview channel from March 21, 2024 (KB5035942). It shows in the apps list as a system app and it no longer appears in Settings under Apps > Installed Apps, but under System > System Components, where no uninstall button appears. Right-clicking in the start menu and clicking on Uninstall simply opens Settings under Apps > Installed Apps.

![image](https://github.com/microsoft/WSL/assets/11506007/c4de70d9-cfa0-40af-8cf0-58dd49ea12aa)
![image](https://github.com/microsoft/WSL/assets/11506007/395c2214-0884-4ad2-959e-3d06e0af74a0)

**Comment by OneBlue** [comment]
Indeed since WSL 2.0.15, WSL doesn't appear here anymore. It can be uninstalled via: `wsl.exe --uninstall` though.

**Comment by adrianghc** [comment]
Do you mean 2.1.5? Even up to 2.1.0, the entry in Apps > Installed Apps still appears (although there is a second entry under System Components with 2.0.15). 2.1.5 is the first one where I no longer find the entry in Installed Apps. I was fairly certain I didn't see the System label before the RP update, but I might have just missed it.

What was the reason behind the decision to make it a system app and only make it uninstallable with `wsl --uninstall`?

**Comment by koffiato** [comment]
> Indeed since WSL 2.0.15, WSL doesn't appear here anymore. It can be uninstalled via: `wsl.exe --uninstall` though.

This is still the case, incredibly annoying as I spent last hour or so trying to uninstall my broken WSL install.

**Comment by Zaflis** [comment]
Yeah the Linux folder won't go away from Explorer after uninstalling WSL. As seen in image; there are no distros installed or active. I'm now attempting to also uninstall Windows feature "Virtual Machine Platform" too, and it is doing something. However that should be completely unnecessary. With WSL feature disabled i shouldn't even be able to execute that command, right? And yes i had rebooted after disabling it.
Edit: I still see Linux icon in Explorer (it has no contents though).

<img width="628" height="219" alt="Image" src="https://github.com/user-attachments/assets/5cfd43bc-646d-4c17-a0a1-190c8f5fb497" />

<img width="306" height="326" alt="Image" src="https://github.com/user-attachments/assets/85ad1c65-6422-4f03-935c-86a201a7d56b" />

<img width="177" height="137" alt="Image" src="https://github.com/user-attachments/assets/084a206e-4434-466f-a0b4-1fbe446b6e4c" />
