### ISSUE TITLE
dnsTunneling default option prevents accessing LAN machines via their host names

### ISSUE THREAD

**Issue by HattDroid** [microsoft/WSL#11352]
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.2.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.150.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

Pinging or ssh'ing or trying to connect local hosts via their hostnames.

### Expected Behavior

Prior to 2.2.1.0, connecting to local hosts worked via their hostnames.

### Actual Behavior

Connection time out. It can only work by using their IP addresses or by disabling dnsTunneling altogether (which now is a default).

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by CatalinFetoiu** [comment]
sounds like /dupe #11022
