### ISSUE TITLE
unable to start service jenkins in wsl2

### ISSUE THREAD

**Issue by maheshshali25** [microsoft/WSL#11354]
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

fedora

### Repro Steps

1. open fedora in terminal
2. install jdk and jenkins from official website using terminal
3. run following command sudo systemctl start jenkins

### Expected Behavior

jenkins server should start

### Actual Behavior

[fedora@MSI ~]$ sudo systemctl start jenkins
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

### Diagnostic Logs

![image](https://github.com/microsoft/WSL/assets/163128846/b99a4aaa-9575-4b9f-bb7e-64a052f18dad)

**Comment by gunters63** [comment]
Did you enable Systemd support like described in [Systemd support is now available in WSL](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)?

**Comment by maheshshali25** [comment]
![image](https://github.com/microsoft/WSL/assets/163128846/f2ba849c-85d6-4ec8-a3bb-18534a01a9bc)

**Comment by maheshshali25** [comment]
It's giving this error

**Comment by OneBlue** [comment]
@maheshshali25: Do you have systemd enabled ? You can do it via: 

```
[boot]
systemd=true
```

in /etc/wsl.conf. (wsl --shutdown needs to be ran to restart the distribution after the change).

**Comment by maheshshali25** [comment]
Thank you, It's working now
