### ISSUE TITLE
networkMode=mirrored ssh clone github repo failed with timeout

### ISSUE THREAD

**Issue by Ghost-LZW** [microsoft/WSL#11361]
### Windows Version

10.0.22621.3296

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Repro Steps

set `.wslconfig` as
```
[wsl2]
networkingMode=mirrored
````
start wsl, run `git clone git@github.com:NVIDIA/cutlass.git` , get `Operation timed out after 300003 milliseconds`
unset networking mode, git clone with ssh get work.

### Expected Behavior

ssh clone work under `networkingMode=mirrored`

### Actual Behavior

git clone via ssh failed, even I set mtu follow https://github.com/microsoft/WSL/issues/4253

**Comment by Ghost-LZW** [comment]
More information, even `git clone git@github.com:xxx/xxx.git` failed, `ssh -T git@github.com` still work under mirrored network mode.

**Comment by zcobol** [comment]
@Ghost-LZW please post the full output of `git clone`. Could be a transient connectivity issue. I did a quick test and it seems to work as expected:

```
zcoblo@texas:~$ wslinfo --networking-mode
mirrored
zcobol@texas:~$ git clone git@github.com:NVIDIA/cutlass.git
Cloning into 'cutlass'...
remote: Enumerating objects: 26383, done.
remote: Counting objects: 100% (9558/9558), done.
remote: Compressing objects: 100% (2135/2135), done.
remote: Total 26383 (delta 7952), reused 8409 (delta 7369), pack-reused 16825
Receiving objects: 100% (26383/26383), 42.67 MiB | 11.71 MiB/s, done.
Resolving deltas: 100% (19588/19588), done.
```

**Comment by Ghost-LZW** [comment]
after close my proxy, git clone get work ..., now the problem becom git clone via vpn work in powershell, but failed in wsl2. sorry for false report, I'll close this issue and check if this issue due to vpn software.

**Comment by oldshensheep** [comment]
If you are using a VPN, could you try setting the MTU to 1500 in WSL2? The interface should be the VPN's interface. 

show interface
```
ip a 
```
change MTU
```
ip link set dev <interface_name> mtu 1500
```

**Comment by Ghost-LZW** [comment]
> If you are using a VPN, could you try setting the MTU to 1500 in WSL2? The interface should be the VPN's interface.
> 
> show interface
> 
> ```
> ip a 
> ```
> 
> change MTU
> 
> ```
> ip link set dev <interface_name> mtu 1500
> ```

I do set the MTU as the same as the host value but still does not work.

**Comment by oldshensheep** [comment]
I have a similar issue, git clone doesn't work, but ping works.

> I do set the MTU as the same as the host value but still does not work.

Make sure the interface is VPN not the host's interface and set it in WSL not windows (I have not tested in windows)


You can test whether it's the same issue by using this command.

```
curl http://google.com --trace - -L
```
There will be an HTTP 301 redirect to http://www.google.com/. It should hang at this point, as it is sending a large web page. If you don't see the HTTP 301 redirection, this might not be the case.

```
== Info: Connected to www.google.com (142.251.32.36) port 80
=> Send header, 77 bytes (0x4d)
0000: 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a GET / HTTP/1.1..
0010: 48 6f 73 74 3a 20 77 77 77 2e 67 6f 6f 67 6c 65 Host: www.google
0020: 2e 63 6f 6d 0d 0a 55 73 65 72 2d 41 67 65 6e 74 .com..User-Agent
0030: 3a 20 63 75 72 6c 2f 38 2e 38 2e 30 0d 0a 41 63 : curl/8.8.0..Ac
0040: 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a          cept: */*....
== Info: Request completely sent off
```

**Comment by Ghost-LZW** [comment]
@oldshensheep  Good catch ! Same issue, set mtu to 1500 instead of 9000 helped. I think the upcoming discussion will shift to your open issue.
