### ISSUE TITLE
My Accounts

### ISSUE THREAD

**Issue by Cre-Dy** [microsoft/WSL#11373]
![Screenshot_2024-03-25-18-16-51-36_680d03679600f7af0b4c700c6b270fe7.jpg](https://github.com/microsoft/WSL/assets/162235945/cd25b151-255f-4362-8aad-68ab756ef80e)

This screen shot shows me signed in on google![Screenshot_2024-03-25-18-15-39-35_95dbc2b164ac5249587bf655507ac86b.jpg](https://github.com/microsoft/WSL/assets/162235945/b1687d93-197d-4ed0-8f7e-f1e8e822f5d3)

![Screenshot_2024-03-24-14-47-23-85.jpg](https://github.com/microsoft/WSL/assets/162235945/88521a1b-12d8-40ee-bffd-9daf7419bee3)

![Screenshot_2024-03-25-18-15-06-59_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/microsoft/WSL/assets/162235945/380a4d19-9822-49ba-8df8-0c97319c82eb)

![Screenshot_2024-03-25-18-15-55-56_95dbc2b164ac5249587bf655507ac86b.jpg](https://github.com/microsoft/WSL/assets/162235945/4cf9cc29-b521-41b0-9bc9-d880c75f502e)

![Screenshot_2024-03-24-14-29-05-84.jpg](https://github.com/microsoft/WSL/assets/162235945/2d85a33b-b11f-4f77-a93f-6fd5c106463d)

![Screenshot_2024-03-24-14-55-40-29.jpg](https://github.com/microsoft/WSL/assets/162235945/f51e2339-544c-4bd2-8e78-2fd3625ce5b8)

![Screenshot_2024-03-24-15-22-51-82.jpg](https://github.com/microsoft/WSL/assets/162235945/d4402379-6906-40f9-9ad2-f14a62e29524)

There Is one that show I'm not other screenshots are blurry.. Get whomever completely off my accounts! Half my apps isn't showing up, I'm steadily having to go through web to get access to emails or anything and screen changes up... IM FED UP, GET MY ACCOUNTS RIGHT PLEASE AND THANK YOU OTHERWISE I WILL GO TO THE NEXT LEVEL AND YOU WILL BE LIABLE! NO ONE SHOULD HAVE ACCESS NOR THE ABILITY TO CHANGE ANYTHING ON MY ACCOUNTS BUT ME!

**Comment by DoctorWho8** [comment]
Aside from what the bot is thinking of, and please do not be annoyed, how is this relevant to WSL?
