### ISSUE TITLE
Network disconnects after a few minutes of normal usage

### ISSUE THREAD

**Issue by cxlanyagege** [microsoft/WSL#11387]
### Windows Version

Microsoft Windows [Version 10.0.22631.3374]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1

### Distro Version

Ubuntu 20.04 LTS

### Other Software

WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg vesion: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3374

My laptop has an ARM64-based CPU (Snapdragon 8cx Gen 2), all the configurations related to WSL has been set to default, while Ubuntu 20.04 distro is also a fresh copy downloaded from Microsoft store.

### Repro Steps

1. Launch WSL2 Ubuntu 20.04
2. Run `ping www.google.com`
3. Wait and monitor network conditions

### Expected Behavior

Ping produces continuous positive feedbacks while internet connection is good, such as `64 bytes from xxx.net (xxx.xxx.xxx.xxx): icmp_seq=154 ttl=117 time=3.53 ms`

### Actual Behavior

Ping reports `sendmsg: Network is unreachable` after a few minutes of running. While Windows host can use the internet as casual and internet connection can be confirmed as robust
![image](https://github.com/microsoft/WSL/assets/30802053/9d013f5f-81f1-4905-81b8-abc885ca9769)

### Diagnostic Logs

[WslNetworkingLogs-2024-03-28_01-29-37.zip](https://github.com/microsoft/WSL/files/14775027/WslNetworkingLogs-2024-03-28_01-29-37.zip)
The above network diagnostic file should contain the faulty period where network inside ubuntu gets a problem. If there are any further investigations, additional log or descriptions that I need to provide, please let me know

#### Some updates to diag logs
I have added a second copy of network diagnostic file and a regular diagnostic file for debugging needs:
[WslNetworkingLogs-2024-03-28_02-12-37.zip](https://github.com/microsoft/WSL/files/14775449/WslNetworkingLogs-2024-03-28_02-12-37.zip)
[WslLogs-2024-03-28_02-22-55.zip](https://github.com/microsoft/WSL/files/14775531/WslLogs-2024-03-28_02-22-55.zip)

**Comment by cxlanyagege** [comment]
### Some updates to diag logs
I have added a second copy of network diagnostic file and a regular diagnostic file for debugging needs:
[WslNetworkingLogs-2024-03-28_02-12-37.zip](https://github.com/microsoft/WSL/files/14775546/WslNetworkingLogs-2024-03-28_02-12-37.zip)
[WslLogs-2024-03-28_02-22-55.zip](https://github.com/microsoft/WSL/files/14775548/WslLogs-2024-03-28_02-22-55.zip)

**Comment by cxlanyagege** [comment]
Seems like this issue only occurs while there are multiple distros being installed (ip conflicts maybe?), even through only one single instance is running at the same time. I discovered it by unregistering other distros and keep only my daily driver ubuntu, running ping for 30 minutes is just fine without any network issues. Wonder if this problem only consists in arm64, since i never encounter similar ones on x64

**Comment by CatalinFetoiu** [comment]
hi @cxlanyagege. thanks for attaching the logs

from the logs, the Linux eth0 interface has an IPv4 address assigned before the repro, but the address is no longer present after the repro, leading to loss of Internet connectivity. This IP address is configured only when WSL starts and not changed afterwards. 

This suggests something in Linux might be deleting the IP.

the logs indicate a tool called "Cloud-init v. 23.4.4-0ubuntu0~20.04.1" is running a "network service" in Linux and configuring networking - the tool could be the one deleting the IP. is the cloud-init tool something you are using? is it possible to uninstall it and see if the problem goes away?

we have also seen compat issues with the Linux Network Manager service. this might not be the issue you are hitting, but you can also try running the command below:
sudo systemctl disable network-manager.service

**Comment by cxlanyagege** [comment]
Thanks for checking my log @CatalinFetoiu 

Actually, I didn't really remember when I had installed cloud-init. I download this fresh copy of ubuntu 20.04 from msstore hours before experiencing this issue, and all I had done is sudo apt update && sudo apt upgrade -y, then install ros noetic following the instructions on their official website. Maybe it comes with ros? Or preinstalled in the package

Anyway, the issue itself seems to be resolved after removing cloud-init, use it for about a day now and nothing abnormal has happened :)
