### ISSUE TITLE
Feature req: systemd in home dir 

### ISSUE THREAD

**Issue by unidef** [microsoft/WSL#11401]
Id like systemd to be in the home dir for stuff like servers or maybe even multiple low priv servers for azure or wsl, it could help on wsl desktop 

btw last time I tried online politics I made no sense lol I’m on meds

but in a container or azure it allows stuff cosmetic stuff like postfix on port 35k for stuff while stuff like spamd and imapd run on logical user accounts for testbedding 

Systemd in the home dir allows stuff like, allowing custom start files for postfix and ftpd, could help for sys admin, while a main postfix runs as root, and a gui to it all would be nice

you can setup a quick version with a daemon that elevates privilege and copies of systemd files

**Comment by OneBlue** [comment]
By 'home', do you mean usermode systemctl ? If so this is already supported. You can create and access systemd units via `systemctl --user <command> ` as long as systemd is enabled.
