### ISSUE TITLE
Error on WSL 2 Update.

### ISSUE THREAD

**Issue by LukeChagastec** [microsoft/WSL#11403]
### Windows Version

Microsoft Windows [versão 10.0.26085.1]

### WSL Version

??????

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

Open a CMD or PoowerShell with admin privileges then run wsl --install.

### Expected Behavior

Install the update to WSL 2.1.5

### Actual Behavior

Catastrophic failure.

```
C:\Windows\System32>wsl --install
Baixando: Subsistema do Windows para Linux 2.1.5
Instalando: Subsistema do Windows para Linux 2.1.5
Falha catastrófica
```

### Diagnostic Logs

[WslLogs-2024-04-01_11-10-38.zip](https://github.com/microsoft/WSL/files/14824289/WslLogs-2024-04-01_11-10-38.zip)

**Comment by LukeChagastec** [comment]
Hi.

Using with MSI Installer.
![image](https://github.com/microsoft/WSL/assets/89275370/e8de2025-2b04-4fde-862d-2d2afd177568)
[wsllogs.txt](https://github.com/microsoft/WSL/files/14824515/wsllogs.txt)

**Comment by okineadev** [comment]
Solution: https://github.com/microsoft/WSL/issues/11319#issuecomment-2024192550
