### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/WSL_E_DISK_CORRUPTED when opening Ubuntu from apps

### ISSUE THREAD

**Issue by wcardosodev** [microsoft/WSL#11400]
### Windows Version

Microsoft Windows [Version 10.0.22631.3374]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu Default Version: 2

### Distro Version

Ubuntu

### Repro Steps

From windows search menu
- search for ubuntu
- click to open ubuntu
- Get error message

### Expected Behavior

Ubuntu would start

### Actual Behavior

Get error message:

The distribution failed to start because its virtual disk is corrupted.
Error code: Wsl/Service/CreateInstance/WSL_E_DISK_CORRUPTED
Press any key to continue...

### Diagnostic Logs

[WslLogs-2024-03-30_21-25-56.zip](https://github.com/microsoft/WSL/files/14813373/WslLogs-2024-03-30_21-25-56.zip)

**Comment by OneBlue** [comment]
Unfortunately not. It could be hardware issue, bug or abrupt shutdown, but there's no easy way to tell after the fact.

**Comment by CortexM33** [comment]
this is a Chinese solution, it saved my wsl:  https://blog.csdn.net/hp884279483/article/details/140955888

**Comment by Jiuxiao-yunwai** [comment]
I also meet this error , it maybe because I use the App in the Start Menu "WSL Setting" and I wrongly chose exange file to ext4.vhdx, I have not found solution

**Comment by HiFiChang** [comment]
> I also meet this error , it maybe because I use the App in the Start Menu "WSL Setting" and I wrongly chose exange file to ext4.vhdx, I have not found solution

same with you and im afraid it is a permanent damage
