### ISSUE TITLE
docker connection is case sensitive 

### ISSUE THREAD

**Issue by ritikaguptams** [microsoft/WSL#11418]
### Windows Version

Microsoft Windows [Version 10.0.22621.3442]

### WSL Version

WSL version: 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu  20.04

### Other Software

Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Repro Steps

Docker ps - with the CAPS D doesnt work whereas docker ps does: 
- It works in powershell and CMD environment hence, the docker connection via WSL should also be case independent 

### Expected Behavior

![image](https://github.com/microsoft/WSL/assets/85255050/1a4ff762-4472-438d-a73f-8d00bdd58551)

![image](https://github.com/microsoft/WSL/assets/85255050/e53b18ff-a439-491f-981b-14a02152e195)

### Actual Behavior

Docker commands should run on wsl irrespective of case. As they currently do in powershell or cmd.

**Comment by ritikaguptams** [comment]
Attaching logs: [WslLogs-2024-04-03_12-43-23.zip](https://github.com/microsoft/WSL/files/14857590/WslLogs-2024-04-03_12-43-23.zip)

**Comment by ritikaguptams** [comment]
I guess there are no logs created for running docker via wsl, can someone from the team point me to what loags should be collected to trace docker calls via WSL ?

**Comment by zcobol** [comment]
@ritikaguptams it works as expected! When you integrate (default) WSL distro with Docker Desktop it creates the link `/usr/bin/docker` in your WSL instance. When you invoke the command with `Docker` the shell is looking for `/usr/bin/Docker` instead of  `/usr/bin/docker`. Thus the failure to launch.

```
zcobol@TEXAS:~$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
zcobol@TEXAS:~$ Docker ps

The command 'Docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/

zcobol@TEXAS:~$ file /usr/bin/docker
/usr/bin/docker: symbolic link to /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
zcobol@TEXAS:~$ ls -l /usr/bin/docker
lrwxrwxrwx 1 root root 48 Apr  3 15:10 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
```

**Comment by benhillis** [comment]
Agreed with @zcobol - Linux is case sensitive so you must match the case of the binary you are trying to run. If you don't believe me try running BASH versus bash.
