### ISSUE TITLE
Mirrored mode networking unavailable in Windows 11

### ISSUE THREAD

**Issue by rlkamalapurkar** [microsoft/WSL#11414]
### Windows Version

Microsoft Windows [Version 10.0.22000.2836]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

Add
```
[wsl2]
networkingMode=mirrored
```
to `%userprofile/.wslconfig` and start wsl. 

### Expected Behavior

WSL2.0 should start in mirrored networking mode.

### Actual Behavior

The prompt says
```
wsl: Mirrored networking mode is not supported, falling back to NAT networking
```

### Diagnostic Logs

[WslLogs-2024-04-02_16-07-28.zip](https://github.com/microsoft/WSL/files/14843862/WslLogs-2024-04-02_16-07-28.zip)

### Networking Logs
[WslNetworkingLogs-2024-04-02_16-24-57.zip](https://github.com/microsoft/WSL/files/14843947/WslNetworkingLogs-2024-04-02_16-24-57.zip)

**Comment by zcobol** [comment]
@rlkamalapurkar you need an updated version of Windows for WSL mirrored networking mode. It was introduced in build `22621.2359`
