### ISSUE TITLE
WSL2 - Where is docker desktop image location ?

### ISSUE THREAD

**Issue by craph** [microsoft/WSL#11421]
### Windows Version

Microsoft Windows [Version 10.0.22621.3296]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu

### Other Software

docker desktop : 4.28.0

### Repro Steps

docker run hello-world

Inside docker desktop I can see that the disk image is stored here : C:\Users\myuser\AppData\Local\Docker\wsl
But inside this directory I only see two folders "data" and "distro" where there is only one file `ext4.vhdx`

### Expected Behavior

I should be able to browse the docker image in Windows explorer or inside Ubuntu WSL

Inside `\\wsl$\docker-desktop-data\mnt\wsl\docker-desktop-data\data` I can see nothing. Is it normal ?

Where can I see the pulled images ?

### Actual Behavior

Inside `\\wsl$\docker-desktop-data\mnt\wsl\docker-desktop-data\data` I can see nothing. 

Is it normal ?

**Comment by zcobol** [comment]
@craph you should be able to browse the docker desktop data from you file manager or a pwsh session:

```
PS C:\Users\zcobo\AppData\Local\Docker\wsl> tree /f
Folder PATH listing for volume Texas
Volume serial number is C0BB-36FA
C:.
├───data
│       ext4.vhdx
│
└───distro
        ext4.vhdx
```

and `docker-desktop-data`:

```
PS C:\Users\zcobo> ls \\wsl.localhost\docker-desktop-data

    Directory: \\wsl.localhost\docker-desktop-data

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           1/24/2024 12:30 PM                .docker
d----           1/24/2024 12:30 PM                bin
d----           1/24/2024 12:31 PM                data
d----            4/4/2024  8:10 AM                dev
d----            4/4/2024  8:11 AM                etc
d----            4/3/2024  3:01 PM                isocache
d----           1/24/2024 12:30 PM                lib
d----           1/24/2024 12:30 PM                lost+found
d----           1/24/2024 12:30 PM                mnt
d----            4/4/2024  8:11 AM                proc
d----            4/4/2024  8:11 AM                run
d----           1/24/2024 12:30 PM                sbin
d----            4/4/2024  8:10 AM                sys
d----           1/24/2024 12:30 PM                tmp
d----           1/24/2024 12:30 PM                usr
-----           3/21/2024  2:21 PM        1930264 init
-----           12/6/2023  9:26 AM        1925984 wsl-keepalive
```

However, is not wise to mess with `docker-destop-data` or `docker-desktop` containers.
