### ISSUE TITLE
WSL2 Ubuntu 22.04.4 Can not login due login timed out

### ISSUE THREAD

**Issue by parentafossa** [microsoft/WSL#11420]
### Windows Version

Microsoft Windows [Version 10.0.22631.3374]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.4

### Repro Steps

login to wsl2 using
`wsl -d Ubuntu_Wsl2`

### Expected Behavior

display wsl2 ubuntu prompt

### Actual Behavior

resulted:
`Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

3 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

42 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm

Last login: Thu Apr  4 07:54:00 +07 2024 on pts/0
You have new mail.

Login timed out after 60 seconds.`

and return to powershell prompt, without going into wsl ubuntu prompt.
But wsl ubuntu is mounted normally.

**Comment by parentafossa** [comment]
Diagnostics logs

[WslLogs-2024-04-04_11-24-05.zip](https://github.com/microsoft/WSL/files/14861360/WslLogs-2024-04-04_11-24-05.zip)

**Comment by OneBlue** [comment]
Thank you @parentafossa. I wonder if this caused by system.

Does adding
```
[wsl2]
safemode=true
```

to .wslconfig solve the issue ?

**Comment by parentafossa** [comment]
Thank you @OneBlue.

The result still the same.

`wsl: SAFE MODE ENABLED - many features will be disabled
Sleeping for 1 second to let systemd settle
Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.146.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

42 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


21 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log

Last login: Fri Apr  5 14:36:50 +07 2024 on pts/0
You have new mail.

Login timed out after 60 seconds.`

**Comment by letian0805** [comment]
@parentafossa Did you solve this problem? How? I also encountered this problem, after upgrading ubuntu 22.04 to ubuntu 24.04 with wls2.
