### ISSUE TITLE
Incorrect WSL MSI installation via CMD and Psexec

### ISSUE THREAD

**Issue by soragXYZ** [microsoft/WSL#11432]
### Windows Version

Microsoft Windows [version 10.0.22631.3296]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Irrelevant

### Distro Version

Irrelevant

### Repro Steps

* Become admin
* Start CMD as admin
* Start powershell with Psexec:  
```powershell
Psexec -e -s -i powershell.exe
```
* In the 2nd window, execute install.cmd which installs the MSI

Here are the install scripts:  
**File install.cmd**  
```powershell
@call powershell .\installMsiWSL2.ps1
```

**File installMsiWSL.ps1**
```powershell
#Requires -RunAsAdministrator

# Variables
$MsiFile = "wsl.2.1.5.0.x64.msi"
$MsiLogFile = "C:\theLogDirectory"

$RC = (Start-Process -FilePath "msiexec.exe" -ArgumentList "/I $MsiFile /L*vx ${MsiLogFile} /qn" -Wait -PassThru).ExitCode

if (-not ($RC -eq 0 -or $RC -eq 3010)) {
    Write-Output "The msi has returned an error: ${RC}"
    Exit 1
}
```

### Expected Behavior

MSI should be installed correctly
The command ```wsl --version``` should display the installed version

### Actual Behavior

The MSI is not installed: the command ```wsl --version``` returns the help instead of the currently installed version

I have to launch the .cmd twice in a row otherwise the MSI is not installed.

For some reason, in the logs it seems like the installation was successfull, no error whatsoever.  
But the MSI is clearly not installed

### Diagnostic Logs

[install.txt](https://github.com/microsoft/WSL/files/14894926/install.txt)

**Comment by soragXYZ** [comment]
[WslLogs-2024-04-06_22-37-28.zip](https://github.com/microsoft/WSL/files/14894945/WslLogs-2024-04-06_22-37-28.zip)

**Comment by zcobol** [comment]
`For some reason, in the logs it seems like the installation was successful, no error whatsoever` indeed, the installation is successful. However, if you run any wsl command, beside `wsl --version` which returns the help output, from within that window (`In the 2nd window, execute install.cmd which installs the MSI`) it returns `Access is denied`. Open a new terminal window and run `wsl --version` and you'll see that the package was installed.

**Comment by OneBlue** [comment]
Thank you @soragXYZ. 

Looking at the logs, it looks like the registry part of the MSI is missing.

Can you try to fully installing WSL by running: `C:\Program Files\WSL\wsl.exe" --uninstall`, and reinstall the latest [MSI](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?

**Comment by soragXYZ** [comment]
Thank you @OneBlue 

I tried with the latest version of the MSI, ie *2.2.2.0*, I still have the same issue

**Comment by OneBlue** [comment]
Interesting. I'd be interested to look the MSI logs for that. 

Can you run wsl --uninstall, and then share the msiexec logs of a new installation ?

**Comment by soragXYZ** [comment]
After more testing, it seems like the command ```powershell wsl --uninstall``` partially solved my issue:

When I start a new installation by calling **install.cmd** in the 2nd window opened by PsExec, the MSI is correctly installed because I can successfully run the command ```powershell wsl --version``` in a **3rd powershell window** and get the expected output.

However, the command ```powershell wsl --version``` in the 2nd window opened by PsExec still returns the help.
Am I missing something here ? Why do I need to open a 3rd window ?
Do I have to update env var or something in the 2nd window ?

Concerning my first tests and the error, it seems like I had to install the MSI twice only because I didn't uninstall it correctly at first.  

I have an another script used for uninstallation which basically run the command ```powershell Start-Process -FilePath "msiexec.exe" -ArgumentList "/X $MsiFile /L*V ${MsiLogFile} /qn" -Wait -PassThru```
Do you recommend using ```powershell wsl --uninstall``` over ```powershell Start-Process -FilePath "msiexec.exe" -ArgumentList "/X $MsiFile /L*V ${MsiLogFile} /qn" -Wait -PassThru``` for the uninstallation ?

Thanks for your answers and your time

**Comment by OneBlue** [comment]
@soragXYZ: There is unfortunately a delay for the WSL installation to complete even after msiexec returns successfully. 

This issue is fixed in insider builds, but it's not fixed on older builds yet. This is most likely what you're experiencing

**Comment by soragXYZ** [comment]
@OneBlue thanks for the answer

Do we have a release date planned ?

**Comment by OneBlue** [comment]
Unfortunately not yet. Most likely in the coming months.

**Comment by OneBlue** [comment]
This should be now available on all recent Windows builds. Closing for now. 

Please reopen if the issue still reproduces with the latest windows builds.

**Comment by getulioanywhere** [comment]
Solution here:

[https://apps.microsoft.com/detail/9P9TQF7MRM4R](url)
