### ISSUE TITLE
Interop consumes stdin

### ISSUE THREAD

**Issue by mook-as** [microsoft/WSL#11439]
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Debian 12 (bookworm)

### Other Software

Report only requires Windows with WSL.

### Repro Steps

(From within the WSL shell)

```sh
$ cd /mnt/c ; ls / | { cmd.exe /c ver ; cat ; } ; echo Done
```

Feel free to replace the `cmd.exe` invocation with anything else, such as `reg.exe`, or manually compile a no-op executable. 

### Expected Behavior

```
$ cd /mnt/c ; ls / | { cmd.exe /c ver ; cat ; } ; echo Done

Microsoft Windows [Version 10.0.22631.2861]
bin   dev  home  lib    lost+found  mnt  proc  run   srv  tmp  var
boot  etc  init  lib64  media       opt  root  sbin  sys  usr
Done
```

(Since the interop command doesn't consume any input, I expected the `cat` to consume it instead.)

### Actual Behavior

```sh
$ cd /mnt/c ; ls / | { cmd.exe /c ver ; cat ; } ; echo Done

Microsoft Windows [Version 10.0.22631.2861]
Done
```

(Note that the `ls` output was _not_ piped to `cat`.)

### Diagnostic Logs

[WslLogs-2024-04-09_18-31-54.zip](https://github.com/microsoft/WSL/files/14924502/WslLogs-2024-04-09_18-31-54.zip)

**Comment by mook-as** [comment]
Logs uploaded ([WslLogs-2024-04-09_18-31-54.zip](https://github.com/microsoft/WSL/files/14924502/WslLogs-2024-04-09_18-31-54.zip)).

This probably _is_ a dupe of #10429, but that was closed without resolution. So I filed this one where no third-party software is needed to reproduce.

**Comment by OneBlue** [comment]
@mook-as: Unfortunately this is by design. Under the hood WSL pipes stdin the Windows side when interop commands are run, and sadly there is no way for WSL to know whether the input is consumed by the Windows command or not. 

This is a limitation of interop.
