### ISSUE TITLE
wsl does not start (only as admin)

### ISSUE THREAD

**Issue by wdoerr** [microsoft/WSL#11443]
### Windows Version

Microsoft Windows [Version 10.0.19045.4239]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop
Visual Studio Code 1.87.2

### Repro Steps

In MS-Terminal:
wsl.exe

### Expected Behavior

start of the default distribution (also without admin rights)
WSL did start some days before the installed distribution.

### Actual Behavior

- no responds from the system (even no response for waiting one night)
- with admin rights wsl starts the default distribution
- high disk activity (100 MB/s)

### Diagnostic Logs

[strace Gist](<script src="https://gist.github.com/wdoerr/4d7b31bbe6f99d22ae4bb5862007d1ba.js"></script>)

 tracert www.microsoft.com (reports 2 ms to Microsoft)

**Comment by TYehan** [comment]
@wdoerr , 
Hi, In WSL terminal (before you start the kex/TigerVNC)  type ```sudo -i``` then you will be the root user. And then do the ```kex``` command or start the GUI. 

Problem should be solved.

**Comment by wdoerr** [comment]
solved

I could start wsl with admin priviliges and export the distribution to a file and import it later as user.

**Comment by wdoerr** [comment]
solved

I could start wsl with admin priviliges and export the distribution to a file and import it later as user.
