### ISSUE TITLE
ARPSYSTEMCOMPONENT property

### ISSUE THREAD

**Issue by schenardie** [microsoft/WSL#11448]
**Is your feature request related to a problem? Please describe.**
On the last release of the MSI the property ARPSYSTEMCOMPONENT was added, resulting into the information not being displayed on Add Remove Programs (Programs and Features) for the WSL anymore.

**Describe the solution you'd like**
Having the visibility of that information is crucial for environment where applications are packaged automatically. The end user should be able to quickly identify if WSL is installed and which version is running in.

**Describe alternatives you've considered**
I'd like the ARPSYSTEMCOMPONENT to be set to no by default and allow people to decide if they want to hide by default.

Thanks

**Comment by OneBlue** [comment]
@schenardie: This is by design because WSL is a system component. 

The best way to get WSL's version information is by running: wsl --version. Also WSL can be unistalled via: wsl --uninstall, if needed
