### ISSUE TITLE
Is it WSL related? ^Space && ESC-Space don't work in Nano

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1144]
When I try to navigate between words in Nano in WSL Ubuntu 14.04 with ^Space || ESC-Space, nothing happens.

Is there an alternative key or something that needs to be activated for this navigational functionality? Thank you,

**Comment by wizardist** [comment]
Works for me in **14393.222.**

**Comment by benhillis** [comment]
@Benosika What Windows version are you running?

**Comment by sundhaug92** [comment]
Works for me in 14936.1000

**Comment by Benosika** [comment]
Sorry for not mentioning. Its Home 14393.222

**Comment by zadjii-msft** [comment]
That's curious. Esc-Spc doesn't work? I'm aware that C-Spc doesn't work correctly in WSL (C-@ doesn't  either) but Esc-@ and Esc-Spc should be fine. Alt-@ and Alt-Spc should also work, and both the Alt- and Esc- chords are mapped to the M- key chord.

**Comment by Benosika** [comment]
I am using an English-Hebrew keyboard by Logitech, I bought years ago.

**Comment by wizardist** [comment]
@zadjii-msft I tried both English (United States) and Russian keyboard layouts when I first checked. Both worked like a charm.

**Comment by sundhaug92** [comment]
Works here on norwegian keyboard. Could it be limited to hebrew keyboards?

**Comment by wizardist** [comment]
@sundhaug92 nope, just checkeed, typing Esc-Spc works in Hebrew as well.

**Comment by zadjii-msft** [comment]
I'm opening up an internal bug to track this, #9194817.

@Benosika If you're still running into this, can you show me a screenshot of what Ctrl+v, Alt+Spc outputs from a bash prompt? Also, try opening emacs, pressing Ctrl-H, K, Alt-Spc and Ctrl-H, K, Esc-Spc and see what gets output there. It should be something like this:
`M-SPC runs the command just-one-space, which is an interactive
compiled Lisp function.`

**Comment by Benosika** [comment]
The output of ctrl+v, alt+spc in a fresh bash prompt is this: `^[`.

Tried to do `Ctrl-H, K, Alt-Spc` and then `Ctrl-H, K, Esc-Spc` but niether Emacs opened nor any output was printed besdies `^[` again.

**Comment by zadjii-msft** [comment]
Okay, I can't repro this locally, so i'm going to need you to help me pin down if it's a nano problem or an actual console/WSL problem.

Can you please try the following steps?
 1. `tmux` to launch tmux (you may need to `apt install tmux`)
 2. `C-b`, `:` To open up the tmux command line
 3. `bind-key -n M-Space display Meta-Space` 
 4. `bind-key -n C-Space display Ctrl-Space` 
 5. Try pressing Alt-Space and Ctrl-Space, the bottom line should have show the corresponding messages briefly.

**Comment by Benosika** [comment]
Sadly I don't have much time to dive in to this right now. After I type tmux there appears a green status bar in the end of CMD, but no such command c-b is recognized..

**Comment by zadjii-msft** [comment]
Sorry, my mistake. I'm using emacs syntax there. I've updated the instructions.

**Comment by gczuczy** [comment]
C-Space neither works for me in emacs. I'm running: Microsoft Windows [Version 10.0.14393]

And did do-release-upgrade a week ago (when I've installed WSL)

**Comment by zadjii-msft** [comment]
@gczuczy It's a known issue that C-Space doesn't work in the initial release of WSL, which is windows 14393. As on Windows Insiders build (I actually don't know which number it is), C-Space should be re-enabled.

Esc-Space should have always worked, so I'm still not exactly sure what is causing @Benosika's bug.
