### ISSUE TITLE
Temporary Failure in Name Resolution With Docker

### ISSUE THREAD

**Issue by aldobarr** [microsoft/WSL#11445]
### Windows Version

Microsoft Windows [Version 10.0.19045.4170]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.4

### Other Software

Docker Desktop (Windows), version 4.29.0 with WSL 2 backend and integration with the distro

### Repro Steps

1. Open WSL Distro
2. Open docker desktop and give it a few seconds to initialize and all that.
4. run `ping google.com` from the wsl terminal.

### Expected Behavior

I should get something along the lines of:
```shell
$ ping google.com
PING google.com (142.250.189.142) 56(84) bytes of data.
64 bytes from mia09s26-in-f14.1e100.net (142.250.189.142): icmp_seq=1 ttl=116 time=5.39 ms
```

### Actual Behavior

```shell
$ ping google.com
ping: google.com: Temporary failure in name resolution
```

**Comment by aldobarr** [comment]
Networking works fine until docker desktop is ran on windows. After running docker desktop hostname resolution fails for the rest of the WSL session. Quitting docker does not restore hostname resolution. Only thing that works is `wsl --shutdown` and then re-opening the WSL instance. Of course, as soon as I run docker desktop again hostname resolution will resume failing.

**Comment by aldobarr** [comment]
Okay so I've been holding off on setting `generateResolvConf = false` and manually setting my nameserver because I would rather let WSL take care of that. I think that would also kill some interconnectivity between ubuntu and the windows host? Either way I just tried it.

Before and after opening docker:
![image](https://github.com/microsoft/WSL/assets/1071197/9b1e6c73-c77b-4e82-9d13-e175eabbf1a5)

**Comment by aldobarr** [comment]
While previous attempts at setting the "bip" setting in docker engine to something else as found in solutions such as this one:
https://stackoverflow.com/questions/65426891/networking-problems-with-wsl2-and-docker-desktop-for-windows/73287366#73287366

Had not worked, giving me issues like telling me "bip" must be an ipv4 address and even if I force the change in the daemon.json file myself it just didn't really resolve the issue. Today, I downgraded docker desktop to 4.24.0. Afterwards I was able to edit "bip" from docker engine in the app itself without the error. After setting bip dns in WSL is working again.

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by aldobarr** [comment]
> Hi. Can you please collect networking logs by following the instructions below? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

So, I had downgraded docker desktop to v4.24.2 and set BIP in docker engine to something as a workaround. v4.24.2 is the latest version I was able to get working without docker killing my networking.

In order to get the logs, I upgraded to 4.29.0 from the docker application. However, despite upgrading and running the new version. I was unable to reproduce the issue. I even removed BIP setting from docker engine. Restarted the app multiple times etc. Still no issue.

Then I completely uninstalled docker desktop and re-installed v4.29.0 from scratch. After which the issue returned as described above. I had the network log script running the whole time until the issue was reproduced. Logs attached.

[WslLogs-2024-05-02_15-50-00.zip](https://github.com/microsoft/WSL/files/15193407/WslLogs-2024-05-02_15-50-00.zip)

**Comment by chanpreetdhanjal** [comment]
Please follow the networking diagnostic script. https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

It should create a folder like [WslNetworkingLogs-date_ver.zip]

**Comment by aldobarr** [comment]
> Please follow the networking diagnostic script. https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues
> 
> It should create a folder like [WslNetworkingLogs-date_ver.zip]

Sorry must have c+p'd the script just below it.

Oddly enough, the moment I run the script it kills my name resolution before I even have a chance to open docker.
[WslNetworkingLogs-2024-05-02_20-26-02.zip](https://g

https://github.com/microsoft/WSL/assets/1071197/d0beaf36-ffb8-4eba-a61d-634a8062c900

ithub.com/microsoft/WSL/files/15195249/WslNetworkingLogs-2024-05-02_20-26-02.zip)

**Comment by aldobarr** [comment]
For what it's worth, I was on version 2.0.something of WSL when I installed docker and began experiencing this issue. I tried updating WSL (which put me on 2.1.5 as I currently am on now) and I also tried turning WSL off in windows features and then turning it back on which also did not help.

**Comment by aldobarr** [comment]
Okay so incidentally I'm seeing now any time I run my "default" WSL instance, it starts with no ability to resolve DNS hostnames at all. No matter what I do the default Ubuntu install will not be able to resolve hostnames. If I then run `wsl --shutdown` and open my secondary ubuntu distro (the one I use for work) it works fine until I open up my default one. At that point the secondary one's ability to resolve hostnames is gone and the default one comes in without any ability to do so from the start.

**Comment by aldobarr** [comment]
Deleting my default WSL instance and remaking it seems to have solved the issue for now.
