### ISSUE TITLE
Error code: Wsl/InstallDistro/0x80d02002 when installing Ubuntu 22.02

### ISSUE THREAD

**Issue by MNGoldenEagle** [microsoft/WSL#11453]
### Windows Version

10.0.22635.3276

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.02

### Repro Steps

1. In a Powershell prompt, run the following command:
`wsl --install Ubuntu-22.04`

### Expected Behavior

The distribution installs without error.

### Actual Behavior

```
PS C:\Users\username> wsl --install Ubuntu-22.04
The requested operation requires elevation.
Installing Windows optional component: VirtualMachinePlatform

Deployment Image Servicing and Management tool
Version: 10.0.22621.2706

Image Version: 10.0.22635.3276

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
The requested operation is successful. Changes will not be effective until the system is rebooted.
Installing: Ubuntu 22.04 LTS
Error: 0x80d02002           7.0%                           ]
Error code: Wsl/InstallDistro/0x80d02002
PS C:\Users\username>
PS C:\Users\username> wsl --install Ubuntu-22.04
Installing: Ubuntu 22.04 LTS
Error: 0x80d02002==========73.0%===========                ]
Error code: Wsl/InstallDistro/0x80d02002
```

### Diagnostic Logs

WSL logs attached.

[WslLogs-2024-04-11_20-19-38.zip](https://github.com/microsoft/WSL/files/14953517/WslLogs-2024-04-11_20-19-38.zip)

**Comment by MNGoldenEagle** [comment]
Interestingly, retrying the install several times eventually got it to install. I'll leave the ticket open for investigative purposes.

**Comment by OneBlue** [comment]
Thank you for reporting this @MNGoldenEagle.

Looking at the logs, this looks like a connectivity issue when download the distribution (0x80D02002 = DO_E_DOWNLOAD_NO_PROGRESS)

**Comment by MNGoldenEagle** [comment]
Good to know! I guess my only comment is that the reporting for the error could be made more clear so that it wouldn't be necessary to find an error code decoder in order to understand what the issue is.
