### ISSUE TITLE
sudo apt-get upgrade and sudo apt-get update both fails

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1145]
Did sag upgrade and got:

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/isc-dhcp/isc-dhcp-client_4.2.4-7ubuntu12.6_amd64.deb  404  Not Found [IP: 2001:67c:1560:8001::11 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/isc-dhcp/isc-dhcp-common_4.2.4-7ubuntu12.6_amd64.deb  404  Not Found [IP: 2001:67c:1560:8001::11 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Then did sag update and got:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com trusty
Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192

W: כשלון בהבאת http://archive.ubuntu.com/ubuntu/dists/trusty/Release

W: Some index files failed to download. They have been ignored, or old ones used instead.
Ben@DESKTOP-NJKJAQR:/$
```

I guess it's on of these rare, inevitable compatibility cases were Windows clashes with Ubuntu; It would be like doing sudo chmod on windows files under cd /mnt/c ... 

If I'm right, I think the notifications after such fail in WSL should be changed to indicate the users it's a WSL-dependant issue, as not everyone can know that when seeing this for the first time.

**Comment by russalex** [comment]
@Benosika, any chance you can provide the following: 

1) The build of Windows
2) Exact command you're running to get this error (I am looking to reproduce it)
3) If you have network connectivity (i.e. ping working on latest Insider build.  `curl www.bing.com `is also a good test) 

Asking because I run apt-get update / upgrade many times a day with no issues, but I do know that many people are having problems with connectivity, especially involving firewall settings.  It would be good to know if  we have other issues in this area.

**Comment by Benosika** [comment]
Hi, it's 14393.222 , sudo apt-get upgrade , sudo apt-get update (nothing besides these).

I did this command curl www.bing.com and got a huge screen of output so that even the vertical scrolling bar disappeared. Should I paste this one here?

**Comment by harrisonchikwe** [comment]
Hello, I am also having a similar issue on a newly installed WSL (windows build 14393.222). After installing WLS and running bash i get the following.

__NOTE:__  I am using WSL that comes with the anniversary update (not from insiders).
Below is my error output.

> Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
> Ign http://archive.ubuntu.com trusty InRelease
> Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
> Hit http://security.ubuntu.com trusty-security/main amd64 Packages
> Get:3 http://security.ubuntu.com trusty-security/restricted amd64 Packages [13.0 kB]
> Hit http://archive.ubuntu.com trusty-backports InRelease
> Get:4 http://archive.ubuntu.com trusty Release.gpg [72 B]
> Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
> Get:5 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [5,198 B]
> Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
> Get:6 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [15.9 kB]
> Hit http://security.ubuntu.com trusty-security/main Translation-en
> Get:7 http://security.ubuntu.com trusty-security/multiverse Translation-en [2,848 B]
> Get:8 http://security.ubuntu.com trusty-security/restricted Translation-en [3,206 B]
> Get:9 http://security.ubuntu.com trusty-security/universe Translation-en [82.7 kB]
> Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
> Get:10 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.0 kB]
> Hit http://archive.ubuntu.com trusty-updates/main Translation-en
> Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
> Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
> Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
> Get:11 http://archive.ubuntu.com trusty Release [11.9 kB]
> Err http://archive.ubuntu.com trusty Release
> 
> Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
> Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
> Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
> Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
> Hit http://archive.ubuntu.com trusty-backports/main Translation-en
> Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
> Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
> Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
> Fetched 282 kB in 4s (65.7 kB/s)
> Reading package lists... Done
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release
> 
> W: Some index files failed to download. They have been ignored, or old ones used instead.

Can anyone help with this problem, please?

**Comment by russalex** [comment]
This issue should not be WSL related.

Looking around I found this on the Ask Ubuntu forums.  May be of help: https://askubuntu.com/questions/710104/cant-fix-gpg-error-no-pub-key

**Comment by eliohann** [comment]
Same here ... It's antivirus related.
Once I disabled KAV10, it works

**Comment by crzidea** [comment]
Same issue, any update?

**Comment by crzidea** [comment]
I have figured out that reinstall WSL can solve this (not a smart way):

```powershell
lxrun /uninstall
lxrun /install /y
```

After that, `sudo apt update` could work for me.

**Comment by ejabu** [comment]
as for me, I run the program as an administrator. And also turned off Windows Defender Real time Protection

and it works

**Comment by tara-raj** [comment]
Closing as this issue is stale. Please re-open if you run into this again.
