### ISSUE TITLE
Wsl only starts when run elevated

### ISSUE THREAD

**Issue by JFReuter-Fin** [microsoft/WSL#11460]
### Windows Version

Microsoft Windows [Version 10.0.22621.3447]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu

### Repro Steps

On a *non-elevated* command prompt:
1) Install / Upgrade wsl using `wsl --update`
2) Install Ubuntu using `wsl --install Ubuntu`
-or-
2) If Ubuntu is already installed, start Ubuntu using just `wsl`

### Expected Behavior

Ubuntu installs and starts a shell with my user logged in.

### Actual Behavior

The install hangs with at "This may take a few minutes", but never finishes. When I just run `wsl` I get no output at all. When I run `wsl` from an elevated command prompt, it usually starts fine and I get a linux shell as root. Sometimes (cannot reliably reproduce this) this also hangs. 

Wsl used to work fine when I ran the version bundled with Windows, but the Microsoft Store version never worked on this machine.

### Diagnostic Logs

Logs from a hanging install process of Ubuntu

[WslLogs-2024-04-12_16-33-10.zip](https://github.com/microsoft/WSL/files/14963338/WslLogs-2024-04-12_16-33-10.zip)
[WslLogs-2024-04-12_16-33-10-kmesg.txt](https://github.com/microsoft/WSL/files/14963341/WslLogs-2024-04-12_16-33-10-kmesg.txt)

**Comment by OneBlue** [comment]
Thank you @JFReuter-Fin.

I'm not seeing anything abnormal in the logs. Out of curiosity, does this happen let's say with debian as well ? 

Does `wsl --install -d debian` get stuck as well ? 

If so, could you capture /dumps of when everything seems to be stuck ?

**Comment by JFReuter-Fin** [comment]
Hi @OneBlue, thank you for the quick response.

I tried to install Debian, unfortunally the issue occurs there as well. As additional background, my initial issue was Docker Desktop not working, with the same symptoms. My investigation lead me to noticing that WSL as a whole does not work properly on this machine.

I have collected dumps, but they are to large to attach here and I am blocked by company policy from sending them via email. I am trying to find a solution to that. Is there a way I can upload the zip so you can access it?

Thank you!

**Comment by OneBlue** [comment]
Thank you @JFReuter-Fin. If the dumps are too big for email you can use GDrive / Onedrive instead.

**Comment by OneBlue** [comment]
Thank you @JFReuter-Fin. We received the dumps. 

This is interesting, WSL is stuck trying to access the drive "Z:\\", what type of drive is it ? Could it be some sort of very slow network drive maybe ?

**Comment by JFReuter-Fin** [comment]
Thanks, @OneBlue Z: was indeed a broken network drive (mapping to some Azure file share) Both Explorer and Powershell would lock up when trying to access the drive, so the error was not isolated to WSLService. 

I have removed the drive mapping and **wsl works now**. This issue is resolved from my perspective. If you need anything else from me, I'd be happy to help.

Thank you very much, this has been an amazing support experience.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.2.3.
