### ISSUE TITLE
WSL2 Is bypassing windows firewall rules, acting as a Windows Firewall Backdoor (still in 2024)

### ISSUE THREAD

**Issue by rjadidi920** [microsoft/WSL#11466]
### Windows Version

Windows 10,11

### WSL Version

2

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Add a outbound blocking rule in firewall for port 22.
Use a WSL2 linux VM. SSH to a server, it doesn't get blocked by the firewall rule.

### Expected Behavior

Blocking SSH of the WSL2 VMs.

### Actual Behavior

Not blocking SSH connection of WSL2 VMs.

### Diagnostic Logs

Did the developers of WSL2 intend to make WSL2 act as a backdoor for Windows Firewall for enterprise networks, or was this by accident? And why is this not fixed yet? 

A company says we would only allow access to certain IPs/Servers no matter the role of the employee via the Windows Firewall, Microsoft WSL2 says not on my watch! (totally not a backdoor by the way)

**Comment by mars2nico** [comment]
Accordings to https://learn.microsoft.com/en-us/windows/wsl/wsl-config, the firewall of wsl2 supports for Windows 11 22H2 or higher only.
