### ISSUE TITLE
ForwardAgent in ~/.ssh/config cause higher CPU usage than usually

### ISSUE THREAD

**Issue by Canic** [microsoft/WSL#11463]
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04.4 LTS

### Repro Steps

When creating a ssh connection to a server and in the ssh config "ForwardAgent yes" is added, the cpu usage on the taskmanager goes up (starting with ~10% CPU usage on process wslhost.exe.
I am using a ryzen 3700x CPU.

Only a wsl --shutdown "cleans" the process and the  cpu usage goes back to normal.
Without ForwardAgent in the config, there is not a such high cpu usage.

I already have the problem on 2 pcs.
If you need more information, then tell it me.
![image](https://github.com/microsoft/WSL/assets/1354329/1dd2c752-1c0e-4a02-b425-3e884a619ac5)

### Expected Behavior

When connecting to host with "ForwardAgent yes", the cpu usage should not be so high.

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/1354329/1dd2c752-1c0e-4a02-b425-3e884a619ac5)

**Comment by OneBlue** [comment]
Thank you @Canic. 

I'm not seeing anything abnormal in the logs. can you try to: 

- Start WSL
- In another shell, run `wsl --debug-shell` as administrator
- Take a screenshot of `top` in that shell

And share the output here ? I'd be interested to see which process consumes the CPU.

**Comment by Canic** [comment]
I did it now, but top doesn't shows anything with high cpu usage:
![image](https://github.com/microsoft/WSL/assets/1354329/900c2a51-519e-4d2c-8331-e0039be442cf)

Any other ideas what i could do that we found out whats going on?

**Comment by OneBlue** [comment]
Interesting. It looks like the CPU is being consumed by wslservice.exe, and not the actual VM.  Let's try something: does removing: 

```
networkingMode=mirrored
```

And then running wsl --shutdown solve the issue ?

**Comment by Canic** [comment]
Hey @OneBlue ,

Your suggestion regarding networkingMode has been quite helpful and is assisting me in identifying the problem.

The issue lies in using a Yubikey as an SSH GPG Key. To transfer the key from my Windows machine to the WSL2 distro, I am using a transfer Pageant.

When I save this file (wsl2-ssh-pageant.exe) directly on the distro (for instance, ~/.ssh/wsl2-ssh-pageant.exe) and initiate it from .bashrc, the problem arises after connecting to an SSH server with ForwardAgent yes enabled.

However, when I save wsl2-ssh-pageant.exe directly on the Windows machine (for example, "/mnt/d/wsl2-ssh-pageant.exe"), the problem disappears.
