### ISSUE TITLE
Ubuntu 20.04 downloads a zero size zlib source code package

### ISSUE THREAD

**Issue by Boulder08** [microsoft/WSL#11478]
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

I'm trying to build CoreELEC (https://wiki.coreelec.org/coreelec:build_ce). The process fails because apparently the zlib source package download fails and just produces a zero byte file. The build script tries two different locations and both have the same issue. With the same Ubuntu version running in VirtualBox, there are no issues whatsoever.

Running a simple wget https://zlib.net/fossils/zlib-1.3.1.tar.gz also produces a broken file.

### Expected Behavior

The file should be about 1,5MB in size.

### Actual Behavior

Zero size file is saved to the virtual disk.

**Comment by zcobol** [comment]
```
zcobol@toto:~$ wget https://zlib.net/fossils/zlib-1.3.1.tar.gz
--2024-04-17 07:59:16--  https://zlib.net/fossils/zlib-1.3.1.tar.gz
Resolving zlib.net (zlib.net)... 85.187.148.2
Connecting to zlib.net (zlib.net)|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1512791 (1.4M) [application/x-gzip]
Saving to: ‘zlib-1.3.1.tar.gz’

zlib-1.3.1.tar.gz             100%[=================================================>]   1.44M  4.50MB/s    in 0.3s

2024-04-17 07:59:17 (4.50 MB/s) - ‘zlib-1.3.1.tar.gz’ saved [1512791/1512791]
```

Why is your download failing 🤔

**Comment by Boulder08** [comment]
It started working after I was trying to reproduce it to get a log. Weird thing because I had attempted the download numerous times yesterday and today before that. I'll have to try again later.

**Comment by Boulder08** [comment]
Unable to resolve.
