### ISSUE TITLE
Fast way to obtain the version of current WSL instance

### ISSUE THREAD

**Issue by CarterLi** [microsoft/WSL#11475]
**Is your feature request related to a problem? Please describe.**

I want to find a fast way to detect the current version of WSL for my project [fastfetch](https://github.com/fastfetch-cli/fastfetch).

**Describe the solution you'd like**

I suggest that wslinfo should introduce a new flag called `--wsl-version` to print the version of current WSL instance

```
$ wslinfo --wsl-version
2.2.2.0
```

Alternately, provide `/mnt/wsl/versions.txt` which contains the output of `wsl.exe --version`. We already have `/mnt/wslg/versions.txt`. WSL can have the same.

Alternately, provide an environment variable called `WSL_VERSION`

**Describe alternatives you've considered**

Currently I am using [`wsl.exe --version`](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/host/host_linux.c#L83-L85). This command costs about 100ms while the whole program costs only 200ms.

**Additional context**

<img width="842" alt="image" src="https://github.com/microsoft/WSL/assets/6134068/591e15d9-b299-40b7-87c4-60041d8d4bc7">

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.2.3.
