### ISSUE TITLE
Disabling interop via `/proc/sys/fs/binfmt_misc/WSLInterop` does not work

### ISSUE THREAD

**Issue by debuglevel** [microsoft/WSL#11471]
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. `echo 0 | sudo tee /proc/sys/fs/binfmt_misc/WSLInterop`
2. `cat /proc/sys/fs/binfmt_misc/WSLInterop` to ensure it is `disabled`.
3. `python3.exe --version`

### Expected Behavior

Should not work.

### Actual Behavior

Works.

**Comment by debuglevel** [comment]
The way described in #8932 works however.

**Comment by firejox** [comment]
Check the files in `/proc/sys/fs/binfmt_misc/` and make sure none of them is similar to `/proc/sys/fs/binfmt_misc/WSLInterop`.

**Comment by OneBlue** [comment]
zcobol's answer is correct. When systemd is enabled, WSL creates two binfmt_misc entries. The supported way of disabling interop is via interop.conf though: 

```
[interop]
enabled=false
```
