### ISSUE TITLE
point `bash.exe` to a different bash other than WSL2 bash

### ISSUE THREAD

**Issue by advnpzn** [microsoft/WSL#11472]
Normally, when I run `bash.exe` in PowerShell, it will open WSL by default.

So, I have MSYS2(C:\msys64\usr\bin) installed for building TensorFlow. While building, it executes `bash.exe` to run a certain snippet of script, but it is being executed by the `bash.exe` that points to the WSL2, which is causing my build to fail. I would like to switch to the `bash.exe` from MSYS2 as default.

I'm able to solve this for now by uninstalling WSL entirely. But I do not think this solution is efficient and I would lose lots of data. Is there a way to disable the `bash.exe` in WSL or change precedence of which `bash.exe` to run?

**Comment by advnpzn** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs

/question

**Comment by firejox** [comment]
Modify Windows `PATH` environment variable and put MSYS2 path in higher search order.

**Comment by OneBlue** [comment]
Indeed updating %PATH% would be the best way to solve this (make sure that the bash.exe you want is first in %PATH%).

Closing since this is something that WSL can do.

**Comment by advnpzn** [comment]
Thanks for the help guys.

Yep, moving the MSYS Env path to the top works!
