### ISSUE TITLE
Limit size of wsl disk

### ISSUE THREAD

**Issue by ppitacaneiro** [microsoft/WSL#11487]
¿It is possible to limit the maximum size that WSL disk can take?

I don't know if there's a way to do it, but I haven't found it in the official WSL documentation

[https://learn.microsoft.com/en-us/windows/wsl/disk-space](https://learn.microsoft.com/en-us/windows/wsl/disk-space)

By reading the documentation you have the options to:

- [How to check your available disk space](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-check-your-available-disk-space)
- [How to expand the size of your WSL 2 Virtual Hard Disk](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-expand-the-size-of-your-wsl-2-virtual-hard-disk)
- [How to repair a VHD mounting error](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error)
- [How to locate the .vhdx file and disk path for your Linux distribution](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-locate-the-vhdx-file-and-disk-path-for-your-linux-distribution)

I'm using docker desktop with WSL and the disk size went from 1 GB to 20 GB in a matter of hours without building any container

Thank you

**Comment by benhillis** [comment]
There's actually already an option for this, I've created a PR to add it to the docs:
https://github.com/MicrosoftDocs/WSL/pull/1951
