### ISSUE TITLE
Running WSL results in Wsl/CallMsi/ERROR_PATH_NOT_FOUND

### ISSUE THREAD

**Issue by mhekel** [microsoft/WSL#11483]
PLEASE note: i am fully aware how to enable/install wsl. I had it up and running but was having an issue that led me to uninstall it. THen thats were the problems began. So thru MULTIPLE attempts and methods listed on github, ms learn and multitude of other sites, my problem is just no where to be found. in a nutshell - 
` The system cannot find the path specified.  Error code:Wsl/CallMsi/ERROR_PATH_NOT_FOUND`

I have enabled wsl thru windows features, thru dism, installed from the store. uninstalled, cleaned registry, appdata, leftovers. i have tried to clone into both wsl and linux.. 
       
         FeatureName      : Microsoft-Windows-Subsystem-Linux
         DisplayName      : Windows Subsystem for Linux
         Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
         RestartRequired  : Possible
         State            : Enabled
        CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

Yet it says it's enabled.
I went thru the whole reinstall/reinable process, downloading Ubuntu from the store and got 
                Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.
i tried reinstalling windows and doing updates but my machine gets hung up at 88% - 3 hours it was stuck there.. 

                  Device name	Mr-Server
                  Processor	11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
                  Installed RAM	16.0 GB (15.8 GB usable)
                  Device ID	F751EC77-F5B8-436B-89EA-78E3655E8169
                  Product ID	00331-10000-00001-AA921
                  System type	64-bit operating system, x64-based processor
                   Pen and touch	Pen support
                Edition	Windows 11 Pro Version	23H2
                   Installed on	‎1/‎7/‎2024
                   OS build	22631.3447
                    Experience	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by mhekel** [comment]
[WslLogs-2024-04-17_21-22-30.zip](https://github.com/microsoft/WSL/files/15019845/WslLogs-2024-04-17_21-22-30.zip)

**Comment by mhekel** [comment]
Ok so...??

**Comment by benhillis** [comment]
@mhekel - thanks for filing the issue, the bot is just trying to add some diagnostic information to help us triage the issue.

@OneBlue - could you please take a look?

**Comment by OneBlue** [comment]
@mhekel: It looks like WSL is in a bad state. Can you try to manually install the [latest MSI package](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?

**Comment by mhekel** [comment]
good lord ive been looking for that package for a minute.. going to run it

**Comment by mhekel** [comment]
*great big hi-5* yeeeeeeeeeeeeeeesssssssssssssssssssssssss it worked.

**Comment by y0un3s3a** [comment]
Awesome sauce, thanks for the package, you predated my error with about 20 minutes

**Comment by joquiro85** [comment]
> @mhekel: It looks like WSL is in a bad state. Can you try to manually install the [latest MSI package](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?

You are the best.:)

**Comment by RishiRaajhaA** [comment]
I had this problem today and I contacted my friend about this issue. I tried these methods:

1. Go to Settings->Apps->Terminal and click Repair. If it still doesn't work, click Reset.
2. Go to Control Panel->Uninstall a program->Turn on or off Windows features->Remove the tick mark from WSL folder and again tick the box.

If still the issue isn't solved, check in the C:\Program Files folder whether it contains WSL folder. If there is no such file, use this link:
https://www.mediafire.com/file/awn7ryarh068dsk/WSL.zip/file
Extract this zip file to C:\Program Files and then restart your PC. It works perfectly now.

**Comment by RennyHarlin23** [comment]
> I had this problem today and I contacted my friend about this issue. I tried these methods:
> 
> 1. Go to Settings->Apps->Terminal and click Repair. If it still doesn't work, click Reset.
> 2. Go to Control Panel->Uninstall a program->Turn on or off Windows features->Remove the tick mark from WSL folder and again tick the box.
> 
> If still the issue isn't solved, check in the C:\Program Files folder whether it contains WSL folder. If there is no such file, use this link: https://www.mediafire.com/file/awn7ryarh068dsk/WSL.zip/file Extract this zip file to C:\Program Files and then restart your PC. It works perfectly now.

Yeah I had the same problem, it's working perfectly fine now.

**Comment by mhekel** [comment]
> @mhekel: It looks like WSL is in a bad state. Can you try to manually install the [latest MSI package](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?

--this  link fixed in one minute the problem i had spent a week trying to solve

**Comment by rupert-source** [comment]
THANKKKKK YOUUUUUUU WOWWWWW  DAMN THANKS TO WHO ASKED AND THANKS TO THE GUY WHO ANSWERED

**Comment by rupert-source** [comment]
THIS LOOKS REAL GOOD PS C:\Windows\System32> wsl --version
WSL version: 2.2.2.0
Kernel version: 5.15.150.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
PS C:\Windows\System32>****

**Comment by mhekel** [comment]
> > @mhekel: It looks like WSL is in a bad state. Can you try to manually install the [latest MSI package](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?
> 
> You are the best.:)

awww shucks.  :-) Y'all are welcome. I'm grateful that  y'all are able to get back up and running!!! I'm relieved to know  that others as well experienced this because I could not understand what I did  to break it. 

the struggle is real!  :-)  -

**Comment by omar-kll** [comment]
> [@mhekel](https://github.com/mhekel): It looks like WSL is in a bad state. Can you try to manually install the [latest MSI package](https://github.com/microsoft/WSL/releases/download/2.2.2/wsl.2.2.2.0.x64.msi) and see if that solves the issue ?

It worked for me too, thank you <3
