### ISSUE TITLE
Get the full version from WSL

### ISSUE THREAD

**Issue by 42sol-eu** [microsoft/WSL#11488]
After a `wsl --update` I want to check the full version of the WSL (x.y.z)

**Describe the solution you'd like**
`wsl --list --version` shows all x.y.z and not only x (2)

**Describe alternatives you've considered**
provide a new flag to show detailed version of a distribution.

**Additional context**
It is really hard to evaluate a upgrade it the full version is not shown.

**Comment by benhillis** [comment]
It's a little confusing, but there are two versions:
1. The version of the WSL package, this is the x.y.z version
2. The version of your distro (WSL1 uses lxcore driver, WSL2 uses a VM).

You get the former by running `wsl.exe --version` the later by running `wsl.exe --list --version`
