### ISSUE TITLE
WSL GUI not enabled

### ISSUE THREAD

**Issue by AoMYgod** [microsoft/WSL#11480]
### Windows Version

Win 10 pro 22H2 (19045.2006)

### WSL Version

1.1.1.1

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Linux version 5.10.102.1-microsoft-standard-WSL2 

### Repro Steps

Actually we runed krusader dialog to check, and WSL aborted due to qt plugin not being able to use. Simplely check if WSL could jump out of window to see if GUI enable. Use command `xeyes` to check if a pair of eyes in dialog pumps out.

and > wsl --version does not print version information but help page.

### Expected Behavior

No dialog windows being able to jump out of wsl commands.

### Actual Behavior

expected xeyes behavior

**Comment by benhillis** [comment]
If `wsl.exe --version` prints the help doc, you are running the old inbox version of WSL which does not support WSLg. Please update to the new version and see if things work `wsl.exe --update`.

Thanks!
