### ISSUE TITLE
Mounting UNC path via `/etc/fstab` doesn't work

### ISSUE THREAD

**Issue by sba923** [microsoft/WSL#11493]
### Windows Version

10.0.22621.3447

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04

### Repro Steps

`/etc/fstab` contains

```
'\\\\pnjnas\Qdownload'  /mnt/Qdownload  drvfs   defaults        0       0
```

This works from a `bash` prompt:

```
sudo mount -t drvfs '\\\\pnjnas\Qdownload' /mnt/Qdownload/
```

But processing via `/etc/fstab` fails:

```
$ sudo mount -a
mount: /mnt/Qdownload: special device '\\\\pnjnas\Qdownload' does not exist.
<3>WSL (162) ERROR: UtilCreateProcessAndWait:687: /bin/mount failed with status 0x2000
```

`dmesg` reports:

```
/mnt/Qdownload: special device '\\\\pnjnas\Qdownload' does not exist.
```

### Expected Behavior

I would expect `mount -a` to succeed in mounting the UNC path.

### Actual Behavior

```
$ sudo mount -a
mount: /mnt/Qdownload: special device '\\\\pnjnas\Qdownload' does not exist.
<3>WSL (162) ERROR: UtilCreateProcessAndWait:687: /bin/mount failed with status 0x2000
```

**Comment by sba923** [comment]
Here are the logs: 
[WslLogs-2024-04-21_19-54-22.zip](https://github.com/microsoft/WSL/files/15052947/WslLogs-2024-04-21_19-54-22.zip)

**Comment by sba923** [comment]
> Diagnostic information
> ```
> Appx package is not installed
> ```

???

**Comment by zcobol** [comment]
Don't use quotes inside fstab. Remove the single quotes around server/share.

**Comment by sba923** [comment]
This indeed works.

I feel... speechless...

I'd have sworn I'd tried all combinations of quotes / no quotes, escaping / not escaping bacsklashes...

For some reason I didn't.
