### ISSUE TITLE
WSL error Wsl/0x80070422 (still not working after tried sc.exe config LxssManager start=auto)

### ISSUE THREAD

**Issue by keranrong** [microsoft/WSL#11501]
### Windows Version

Microsoft Windows [Version 10.0.22631.3374]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Repro Steps

type "wsl" in terminal

### Expected Behavior

wsl works

### Actual Behavior

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
Error code: Wsl/0x80070422

**Comment by keranrong** [comment]
[WslLogs-2024-04-23_20-31-16.zip](https://github.com/microsoft/WSL/files/15084498/WslLogs-2024-04-23_20-31-16.zip)

**Comment by keranrong** [comment]
[WslLogs-2024-04-23_20-31-16.zip](https://github.com/microsoft/WSL/files/15103114/WslLogs-2024-04-23_20-31-16.zip)

**Comment by MethanJess** [comment]
@keranrong I had the same issue, I fixed it by, opening the the "Services" app, then look for "WSL Service" 
Double click "WSL Service" and set 'Startup type' as 'Manual'.

**Comment by OneBlue** [comment]
@keranrong: I do see that wslservice is set to `Disabled`. Does configuring it as `Manual` solve the issue ? 

You can do this via:

```
sc.exe config wslservice start= demand
```

Also FYI Antiviruses might be disabling wslservice, so you might need to add exclusion rules for that.

**Comment by keranrong** [comment]
Yes, I think it is because of my antivirus software (Avast), I just disabled part of its scanning. Thanks so much for your help, everyone!!
