### ISSUE TITLE
WSL2 gives HYPERVISOR_ERROR BSOD but WSL1 works okay

### ISSUE THREAD

**Issue by Visual917** [microsoft/WSL#11508]
### Windows Version

10.0.19045.4291

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Latest

### Distro Version

Debian

### Repro Steps

- Install Debian from the store
- Open it so it installs initially and gets ready

### Expected Behavior

It installs and runs automatically

### Actual Behavior

HYPERVISOR_ERROR BSOD immediately.

### Diagnostic Logs

[042424-8531-01.dmp](https://github.com/microsoft/WSL/files/15101391/042424-8531-01.dmp)

**Comment by Visual917** [comment]
WSL1 worked okay. Virtualization and everything like that are enabled. Windows and drivers are up-to-date.

**Comment by Visual917** [comment]
I cannot do that because it is BSOD.

**Comment by benhillis** [comment]
Please do not file security issues in this repo:
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#important-reporting-bsods-and-security-issues
