### ISSUE TITLE
several DCP_WATCHDOG_VIOLATIONS Blue-Screens-of-Death since installing WSL2 - when NOT using it

### ISSUE THREAD

**Issue by LowLevelMahn** [microsoft/WSL#11504]
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

SUSE Tumbleweed

### Other Software

Docker Desktop 4.29.0

### Repro Steps

no idea - it happens sometimes when using WSL2 or even when days of no use of it

even not using WSL2 activly - there are days were i didn't use wsl -d [distro] at all - my installed Docker is unused for month now

i saw my last Blue-Screen-of-Death years ago - since installing WSL2 several in the last days - without any other system change

### Expected Behavior

Not having serveral BSOD while in meetings with my customer - i got 2 in the last hour
when not using WSL2 at all

### Actual Behavior

BSOD with DCP_WATCHDOG_VIOLATIONS

**Comment by LowLevelMahn** [comment]
i can't log the run of WSL2 because its often not running at all when the Blue-Screen happens - but my Blue-Screen rating went from Zero over years to 10 or more in the last 2 Weeks - after installing WSL2 and there are other users having the same BSOD while NOT using WSL2

i activated the Kernel-Crash dump as explained in https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#10-reporting-a-windows-crash-bsod and wait for the next crash to the the dump

**Comment by LowLevelMahn** [comment]
analyzed the MEMORY.DMP with WinDbg

it seems that my Blutooth stack got problems - but i've didn't changed that in any form - only installing WSL2 - could that be someway related - close the issue if not


`
************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : true
   AllowNugetExeUpdate : true
   NonInteractiveNuget : true
   AllowNugetMSCredentialProviderInstall : true
   AllowParallelInitializationOfLocalRepositories : true

   EnableRedirectToV8JsProvider : false

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.000 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.125 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 41

Microsoft (R) Windows Debugger Version 10.0.27553.1004 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [D:\temp\MEMORY.DMP]
Kernel Bitmap Dump File: Kernel address space is available, User address space may not be available.

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 19041 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406
Kernel base = 0xfffff801`29e00000 PsLoadedModuleList = 0xfffff801`2aa2a790
Debug session time: Wed Apr 24 15:04:17.007 2024 (UTC + 2:00)
System Uptime: 0 days 3:31:26.687
Loading Kernel Symbols
...............................................................
.............Page 125d08 not present in the dump file. Type ".hh dbgerr004" for details
...................................................
................................................................
......................................
Loading User Symbols

Loading unloaded module list
......
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff801`2a1fda40 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffff801`28c42c90=0000000000000133
0: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

DPC_WATCHDOG_VIOLATION (133)
The DPC watchdog detected a prolonged run time at an IRQL of DISPATCH_LEVEL
or above.
Arguments:
Arg1: 0000000000000000, A single DPC or ISR exceeded its time allotment. The offending
	component can usually be identified with a stack trace.
Arg2: 0000000000000501, The DPC time count (in ticks).
Arg3: 0000000000000500, The DPC time allotment (in ticks).
Arg4: fffff8012aafb320, cast to nt!DPC_WATCHDOG_GLOBAL_TRIAGE_BLOCK, which contains
	additional information regarding this single DPC timeout

Debugging Details:
------------------

*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: TickPeriods                                   ***
***                                                                   ***
*************************************************************************

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1983

    Key  : Analysis.Elapsed.mSec
    Value: 2001

    Key  : Analysis.IO.Other.Mb
    Value: 14

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 31

    Key  : Analysis.Init.CPU.mSec
    Value: 890

    Key  : Analysis.Init.Elapsed.mSec
    Value: 35818

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 108

    Key  : Bugcheck.Code.KiBugCheckData
    Value: 0x133

    Key  : Bugcheck.Code.LegacyAPI
    Value: 0x133

    Key  : Bugcheck.Code.TargetModel
    Value: 0x133

    Key  : Failure.Bucket
    Value: 0x133_DPC_BTHUSB!WPP_RECORDER_AND_TRACE_SF_qsDd

    Key  : Failure.Hash
    Value: {1d6b9f42-9f5b-6d16-91fa-1d6f87dfbed3}

    Key  : Hypervisor.Enlightenments.Value
    Value: 68673420

    Key  : Hypervisor.Enlightenments.ValueHex
    Value: 417df8c

    Key  : Hypervisor.Flags.AnyHypervisorPresent
    Value: 1

    Key  : Hypervisor.Flags.ApicEnlightened
    Value: 0

    Key  : Hypervisor.Flags.ApicVirtualizationAvailable
    Value: 1

    Key  : Hypervisor.Flags.AsyncMemoryHint
    Value: 0

    Key  : Hypervisor.Flags.CoreSchedulerRequested
    Value: 0

    Key  : Hypervisor.Flags.CpuManager
    Value: 1

    Key  : Hypervisor.Flags.DeprecateAutoEoi
    Value: 1

    Key  : Hypervisor.Flags.DynamicCpuDisabled
    Value: 1

    Key  : Hypervisor.Flags.Epf
    Value: 0

    Key  : Hypervisor.Flags.ExtendedProcessorMasks
    Value: 1

    Key  : Hypervisor.Flags.HardwareMbecAvailable
    Value: 1

    Key  : Hypervisor.Flags.MaxBankNumber
    Value: 0

    Key  : Hypervisor.Flags.MemoryZeroingControl
    Value: 0

    Key  : Hypervisor.Flags.NoExtendedRangeFlush
    Value: 0

    Key  : Hypervisor.Flags.NoNonArchCoreSharing
    Value: 1

    Key  : Hypervisor.Flags.Phase0InitDone
    Value: 1

    Key  : Hypervisor.Flags.PowerSchedulerQos
    Value: 0

    Key  : Hypervisor.Flags.RootScheduler
    Value: 0

    Key  : Hypervisor.Flags.SynicAvailable
    Value: 1

    Key  : Hypervisor.Flags.UseQpcBias
    Value: 0

    Key  : Hypervisor.Flags.Value
    Value: 21631230

    Key  : Hypervisor.Flags.ValueHex
    Value: 14a10fe

    Key  : Hypervisor.Flags.VpAssistPage
    Value: 1

    Key  : Hypervisor.Flags.VsmAvailable
    Value: 1

    Key  : Hypervisor.RootFlags.AccessStats
    Value: 1

    Key  : Hypervisor.RootFlags.CrashdumpEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.CreateVirtualProcessor
    Value: 1

    Key  : Hypervisor.RootFlags.DisableHyperthreading
    Value: 0

    Key  : Hypervisor.RootFlags.HostTimelineSync
    Value: 1

    Key  : Hypervisor.RootFlags.HypervisorDebuggingEnabled
    Value: 0

    Key  : Hypervisor.RootFlags.IsHyperV
    Value: 1

    Key  : Hypervisor.RootFlags.LivedumpEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.MapDeviceInterrupt
    Value: 1

    Key  : Hypervisor.RootFlags.MceEnlightened
    Value: 1

    Key  : Hypervisor.RootFlags.Nested
    Value: 0

    Key  : Hypervisor.RootFlags.StartLogicalProcessor
    Value: 1

    Key  : Hypervisor.RootFlags.Value
    Value: 1015

    Key  : Hypervisor.RootFlags.ValueHex
    Value: 3f7

    Key  : SecureKernel.HalpHvciEnabled
    Value: 0

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Version
    Value: 10.0.19041.1


BUGCHECK_CODE:  133

BUGCHECK_P1: 0

BUGCHECK_P2: 501

BUGCHECK_P3: 500

BUGCHECK_P4: fffff8012aafb320

FILE_IN_CAB:  MEMORY.DMP

DPC_TIMEOUT_TYPE:  SINGLE_DPC_TIMEOUT_EXCEEDED

TRAP_FRAME:  fffff80128c329e0 -- (.trap 0xfffff80128c329e0)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=fffff80144ee0338 rbx=0000000000000000 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=fffff80144ed85e0 rsp=fffff80128c32b70 rbp=000000000000001b
 r8=0000000000000003  r9=ffff980ca253a000 r10=000000000000001b
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na po nc
BTHUSB!WPP_RECORDER_AND_TRACE_SF_qsDd+0xdc:
fffff801`44ed85e0 48ffc3          inc     rbx
Resetting default scope

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

PROCESS_NAME:  System

STACK_TEXT:  
fffff801`28c42c88 fffff801`2a234e70     : 00000000`00000133 00000000`00000000 00000000`00000501 00000000`00000500 : nt!KeBugCheckEx
fffff801`28c42c90 fffff801`2a050fdd     : 00002995`f8ddcb9d fffff801`274ed180 00000000`00000246 00000000`000c63ac : nt!KeAccumulateTicks+0x1e70b0
fffff801`28c42cf0 fffff801`2a049511     : 00000000`00000000 00000000`00076276 fffff801`274ed180 00000000`00000001 : nt!KiUpdateRunTime+0x5d
fffff801`28c42d40 fffff801`2a04b3d3     : fffff801`274ed180 00000000`00000000 fffff801`2aa31898 00000000`00000000 : nt!KiUpdateTime+0x4a1
fffff801`28c42e80 fffff801`2a0485e2     : fffff801`28c329e0 fffff801`28c32a60 fffff801`28c32a00 00000000`00000002 : nt!KeClockInterruptNotify+0x2e3
fffff801`28c42f30 fffff801`2a112d45     : 0000001d`89ddf49d fffff801`2aaf3ae0 fffff801`2aaf3b90 ffff4fe8`b939e68c : nt!HalpTimerClockInterrupt+0xe2
fffff801`28c42f60 fffff801`2a1ffa7a     : fffff801`28c32a60 fffff801`2aaf3ae0 00000000`00000000 00000000`00000000 : nt!KiCallInterruptServiceRoutine+0xa5
fffff801`28c42fb0 fffff801`2a2002a7     : 00000000`57543201 00000000`25c610b4 ffff980c`a2517010 00000000`00c18519 : nt!KiInterruptSubDispatchNoLockNoEtw+0xfa
fffff801`28c329e0 fffff801`44ed85e0     : 00000000`00000008 00000000`0000001a 00000000`00000200 fffff801`44ed84ed : nt!KiInterruptDispatchNoLockNoEtw+0x37
fffff801`28c32b70 fffff801`44ed9320     : ffff980c`b9b8fda0 00000000`00000200 ffff980c`a2517010 fffff801`28c32ca0 : BTHUSB!WPP_RECORDER_AND_TRACE_SF_qsDd+0xdc
fffff801`28c32c00 fffff801`44ed80c2     : ffff980c`a2517000 ffff980c`00000003 ffff980c`b76fa010 ffff980c`b33cddd0 : BTHUSB!BthUsb_ScoReadUrbDone+0x130
fffff801`28c32cb0 fffff801`44ed915e     : 00000000`00000001 ffff980c`a2517010 ffff980c`b9b8e420 ffff980c`b5f10010 : BTHUSB!BthUsb_ScoUrbComplete+0xfe
fffff801`28c32d20 fffff801`2a054e25     : ffff980c`b5f105ab fffff801`28c32e09 ffff980c`b5f10010 00000000`00000000 : BTHUSB!BthUsb_ScoReadTransferCallback+0xbe
fffff801`28c32d90 fffff801`2a054c67     : ffff980c`b5f10010 00000000`00000000 ffff980c`b883ca30 00000000`00000002 : nt!IopfCompleteRequest+0x1a5
fffff801`28c32e70 fffff801`2e5d81ba     : 00000000`c0000120 ffff980c`a1d88d90 ffff980c`b5f10010 fffff801`28c32f58 : nt!IofCompleteRequest+0x17
fffff801`28c32ea0 fffff801`2e5d5c5f     : ffff980c`a212dd02 fffff801`00000006 ffff980c`b5f10010 00000000`c0000120 : Wdf01000!FxRequest::CompleteInternal+0x23a [minkernel\wdf\framework\shared\core\fxrequest.cpp @ 869] 
fffff801`28c32f30 fffff801`51562a15     : 00000000`c0010002 ffff980c`ba8deaf0 ffff980c`ba8dec90 ffff980c`b883ce70 : Wdf01000!imp_WdfRequestComplete+0x8f [minkernel\wdf\framework\shared\core\fxrequestapi.cpp @ 436] 
fffff801`28c32f90 fffff801`51561237     : 00000000`00000000 ffff980c`b883ce10 fffff801`28c33090 ffff980c`ba8dec90 : USBXHCI!Isoch_Transfer_CompleteCancelable+0x215
fffff801`28c32ff0 fffff801`51561ead     : ffff980c`b883ce10 fffff801`28c33200 ffff980c`b883ce70 fffff801`2a042909 : USBXHCI!Isoch_CompleteTransfers+0x19b
fffff801`28c33050 fffff801`51562d4a     : ffff980c`b66fdbf0 fffff801`28c33220 fffff801`28c33400 ffff980c`9a0ca000 : USBXHCI!Isoch_ProcessTransferCompletion+0xed
fffff801`28c330b0 fffff801`2e5e954b     : 00000000`00000f44 00000000`00400a02 00000000`00000000 00002985`340dddff : USBXHCI!Isoch_WdfEvtDpcForTransferCompletion+0x2a
fffff801`28c330e0 fffff801`2a0c0e5e     : fffff801`274f0240 ffff980c`99fc9000 fffff801`28c333e0 ffff980c`00000002 : Wdf01000!FxDpc::FxDpcThunk+0x5b [minkernel\wdf\framework\kmdf\src\core\fxdpc.cpp @ 361] 
fffff801`28c33120 fffff801`2a0c0144     : 00000000`00000000 00000000`00000000 00000000`00140001 00000000`00000000 : nt!KiExecuteAllDpcs+0x30e
fffff801`28c33290 fffff801`2a20253e     : 00000000`00000000 fffff801`274ed180 fffff801`2ab27a00 ffff980c`b7694080 : nt!KiRetireDpcList+0x1f4
fffff801`28c33520 00000000`00000000     : fffff801`28c34000 fffff801`28c2d000 00000000`00000000 00000000`00000000 : nt!KiIdleLoop+0x9e


SYMBOL_NAME:  BTHUSB!WPP_RECORDER_AND_TRACE_SF_qsDd+dc

MODULE_NAME: BTHUSB

IMAGE_NAME:  BTHUSB.sys

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  dc

FAILURE_BUCKET_ID:  0x133_DPC_BTHUSB!WPP_RECORDER_AND_TRACE_SF_qsDd

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {1d6b9f42-9f5b-6d16-91fa-1d6f87dfbed3}

Followup:     MachineOwner
---------

`

**Comment by benhillis** [comment]
From the dump it looks like the BTHUSB driver is causing the bugcheck. Does this issue go away if you unplug your bluetooth USB device?

**Comment by LowLevelMahn** [comment]
yes it seems comming from the bluetooth USB stack - but that didn't changed for years (same Bose headset) no software updates (except from Microsoft) at all

but definitly did my BSOD rate went from Zero in years up to >15 in the last 3 weeks (excat the timespan im firstly installed and using WSL2) - very early after installation i expirenced a BSOD (always the same) while running WSL2 - the last weeks also when not starting WSL2 at all (wsl -d [distro]) i don't know if WSL2 is in someway permanently active in the background

im using my headset permanently music and Microsoft Teams sessions for the last 2 years now at least 4-6h a day - i also see no direct relation in the kernel dump to WSL but im a developer and can't ignore the correlation of installing WSL2 (im very conservative installing new software on my main C++ development machine)

lets see what the next BSOD dump will show

**Comment by LowLevelMahn** [comment]
my hyper BSOD rate went down when i unplugged a maybe broken USB-Stick - closing the issue for now
