### ISSUE TITLE
WSL window's status information dispears  when running

### ISSUE THREAD

**Issue by rogerzzl** [microsoft/WSL#11511]
### Windows Version

Microsoft Windows [Version10.0.19045.4291]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

No interaction with other applications

### Repro Steps

I used WSL's window to run my command *python My_scripts.py* and everything worked fine until the next day when I tried to check the status through the window, the WSL window I was running disappeared and a new WSL window popped up.

When I checked with *wsl -l -v*, the state showed **running**, but the window did disappear, and I wasn't sure if the running state would last until my code ran out, since my code needed to run for close to two weeks.

### Expected Behavior

How to keep the running window without opening a new window 

### Actual Behavior

nothing

**Comment by rogerzzl** [comment]
> # Logs are required for review from WSL team
> WSL 团队需要审核日志
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'.如果这是一个功能请求，请回复“/feature”。如果这是一个问题，请用“/question”回复。 **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.否则，请按照以下说明附加日志​​，除非添加日志，否则您的问题将不会被审核。这些日志将帮助我们了解您的机器中发生的情况。
> 
> How to collect WSL logs
> 如何收集WSL日志
> Download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:下载并在管理 powershell 提示符下执行collect-wsl-logs.ps1：
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.完成后，scipt 将输出日志文件的路径。
> 
> Once completed please upload the output files to this Github issue.完成后，请将输出文件上传到此 Github 问题。
> 
> [Click here for more info on logging 单击此处了解有关日志记录的更多信息](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue and reply with '/emailed-logs'. 如果您选择通过电子邮件发送这些日志而不是附加到错误中，请将它们发送至 wsl-gh-logs@microsoft.com，并在主题中注明 github 问题的编号，并在消息中提供指向您在 github 中的评论的链接使用“/emailed-logs”发出和回复。
> 
> # View similar issues 查看类似问题
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!请查看下面的问题，看看它们是否能解决您的问题，如果该问题描述了您的问题，请考虑关闭此问题并点赞另一个问题，以帮助我们优先处理它！
> 
> ### Open similar issues: 打开类似问题：
> * [wsl doesn't keep running in background after closing window (#9401)](https://github.com/microsoft/WSL/issues/9401),  similarity score: 0.76 关闭窗口后 wsl 不会继续在后台运行 (#9401)，相似度得分：0.76
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.注意：您可以通过赞成或反对此评论来向我提供反馈。

/question

**Comment by OneBlue** [comment]
@rogerzzl: This can happen if WSL gets updated by the store. If you want things to never get killed you might to disable store updates.

If this reproduces with store updates disabled, please collect /logs so we can look into it.

**Comment by rogerzzl** [comment]
> @rogerzzl: This can happen if WSL gets updated by the store. If you want things to never get killed you might to disable store updates.
> 
> If this reproduces with store updates disabled, please collect /logs so we can look into it.

Thank you for your reply, I'll try to do so.
