### ISSUE TITLE
The message "An Http proxy change has been detected on the host" repeats non-stop

### ISSUE THREAD

**Issue by ebickle** [microsoft/WSL#11523]
### Windows Version

Microsoft Windows [Version 10.0.22631.3447]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

22.04

### Other Software

Ivanti Secure Access Client 22.7.28369
Microsoft Intune Management Extension 1.78.103.0
Nexthink Collector 24.2.03002
Rapid7 Insight Agent 4.0.7.26
ZScaler 4.3.0.181
ZScaler-Network-Adapter 1.0.2.0

### Repro Steps

I can't reproduce this on my personal devices, but the issue always occurs on my work machine when ever I launch WSL - e.g. opening Ubuntu in a terminal. That's the only step necessary.

### Expected Behavior

WSL should not detect HTTP proxy changes that don't occur. Or, alternately, if the change is setting the same proxy IP and port it shouldn't trigger a notification.

### Actual Behavior

When launching WSL, WSL reports the notification "An Http Proxy change has been detected on the host. Please restart WSL to apply the change". The notification repeats forever, approximately every second, nonstop until the machine is rebooted or wsl --shutdown is run. Over the course of a few minutes, I receive thousands of notifications.

This is a corporate machine that has a corporate-inspection proxy (ZScaler) installed. ZScaler sets a machine-wide proxy for the "127.0.0.1:9000" but as far as I know that's constant and never changes. 

My ISP issues both Ipv6 and Ipv4 addresses. Due to connectivity failing with any Ipv6 host in wsl, I had to apply the following configuration to my `.wslconfig`:
```
[experimental]
networkingMode=mirrored
```

The issue still occurs even if the `.wslconfig` file is blanked out.

### Diagnostic Logs

Diagnostic logs are available at Feedback Hub item https://aka.ms/AAq6z97

**Comment by jamesmacwhite** [comment]
I would like to also add to this that I also receive the same notification from WSL regularly on a personal computer. The only thing related to a proxy I have one my network is a wpad deployment. Otherwise, there is no corporate proxy or any software to that nature deployed.

I could not find any information about what triggers this notification and any way to turn it off.

**Comment by corazza** [comment]
I use a VPN and get this notification every time I (re)-connect to it

**Comment by CatalinFetoiu** [comment]
hello @ebickle thanks for sending the logs and sorry for the delay following up on this

the logs indicate that WSL sees the PAC Url associated with the proxy keeps changing between 127.0.0.1:9000 and 127.0.0.1:62230 and this leads to WSL showing the pop-up

We need to understand if this is expected. in order to do this, can you please collect a new set of logs, using our networking logs script? https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1. This should generate a zip with name starting with "WslNetworkingLogs"

thanks!

**Comment by CatalinFetoiu** [comment]
hi @ebickle. thanks for sending the networking logs over email!

the issue is caused by the following app C:\Program Files\Zscaler\ZSATrayManager\ZSATrayManager.exe, that repeatedly enables and disables the proxy PAC configuration (http://127.0.0.1:9000/localproxy-d9aa1292.pac)

enabling and disabling the proxy PAC configuration triggers the notification that WSL shows

I recommend following up with ZScaler to understand if the behavior of their app is expected

**Comment by CatalinFetoiu** [comment]
@jamesmacwhite please open a separate issue if you still encounter the problem

@corazza does the VPN configure a proxy when it connects? if that's the case, it's expected that a proxy change will be detected and the notification will pop up. As above, please feel free to open a new issue

thanks

**Comment by jamesmacwhite** [comment]
@CatalinFetoiu Thanks. Based on the feedback from the original issue. I believe it's likely related to the use of an Automatic Proxy config i.e WPAD/PAC.

**Comment by ebickle** [comment]
Thanks @CatalinFetoiu, I'm following up with our desktop engineering team to look into potential issues with Zscaler.

I still wonder whether there's an improvement that could be made to WSL though. If WSL is already in a state of "WSL needing to be restarted due to an Http Proxy change", could additional notifications be suppressed? In other words, if WSL already needs a restart due to a proxy change, there's no need to show additional notifications for subsequent proxy changes.

That would help avoid these types of problems with badly behaving corporate agents 😊

**Comment by CatalinFetoiu** [comment]
@ebickle thanks for your feedback, we'll consider this

**Comment by rchildress87** [comment]
I am also experiencing this issue. I believe it is caused, in part, by the zScaler Internet Security client which is deployed and enforced by my company's IT department.

**Comment by danielkonecny** [comment]
I am also experiencing the same issue while running Ubuntu 22.04 under WSL 2 with ZScaler controlling my network traffic. I would like to support what @ebickle mentions about suppressing the notification while it's already shown once - this would make the user experience a lot nicer!

**Comment by vbdockers** [comment]
Hello @ebickle  @rchildress87  Did you find any workaround to the issue - I am experiencing same issue with zscaler. :)

**Comment by chrisrodrigue** [comment]
This is a super annoying issue. I'm tempted to just remove the WSL UWP app since it doesn't seem necessary to actually use WSL.

**Comment by douglasg14b** [comment]
@CatalinFetoiu Why is this closed?

It still repeats over-and-over. If if  VPN is not connected I'm finding

**Comment by CatalinFetoiu** [comment]
@douglasg14b thanks for reaching out

we found that this issue is caused by ZScaler. are you using ZScaler? If not, can you please open a separate issue and attach networking logs?

thanks

**Comment by douglasg14b** [comment]
@CatalinFetoiu I appreciate the reply.

We are using ZScaler. That said, this seems to be endemic, and many corps use ZScaler. Which means WSL is in a position to be annoying or frustrating for many of it's users.

Workarounds and discoveries as time passes tend to collect on issues like these, sometimes leading to solutions, or enough information for corrections to be made one place or another 🤔

**Comment by NBardelot** [comment]
I concur, this issue should not be closed. We also use a Zscaler agent on our windows host, and the proxy.pac being modified should not spam notifications like this. At least the issue should mention a valid workaround in order not to be spammed.

FYI as I look at the [auto-proxy](https://learn.microsoft.com/en-us/windows/wsl/networking#auto-proxy) paragraph in the WSL networking doc I see that `autoProxy=false` in the `[wsl2]` section of `%USERPROFILE%/.wslconfig` should do the trick. I'm going to test this.

**Comment by karman-docker** [comment]
Did anyone find an answer from ZScaler ? @ebickle ? Thanks for any info.

**Comment by ebickle** [comment]
> Did anyone find an answer from ZScaler ? [@ebickle](https://github.com/ebickle) ? Thanks for any info.

I haven’t found any solutions yet, unfortunately. I’ve had to mostly give up on WSL for work purposes due to the bug. Whenever I use it I have to disable all notifications and enter “do not disturb” mode, when call “wsl --shutdown” when I’m done.

A better solution on Microsoft’s side would be to avoid sending new notifications for proxy changes if WSL hasn’t been restarted. The proxy settings are already out of date - no reason to keep sending notifications.

**Comment by chrisrodrigue** [comment]
IMO there isn’t a compelling reason why WSL should send notifications or exist in the system tray at all. It’s a CLI application.

**Comment by mldisibio** [comment]
If it helps, for the same exact environment (Ivanti VPN, ZScalar, WSL) this issue only started for me after Windows 11 was pushed by corporate. Did not occur ever on Windows 10.

**Comment by lovato** [comment]
Still facing it on Win11 and ZScaler. I will try some of the recommendations listed here.
Since I am distributing a distro to co-workers, they are asking my how to solve it :-)

**Comment by lT-Tl** [comment]
The same issue with me while I do not use ZScaler, and I haven't even installed ZScaler.
Maybe some other reason without related to ZScaler.
