### ISSUE TITLE
Calling Microsoft's OpenSSH from systemd service leads to error with exit code 57

### ISSUE THREAD

**Issue by trallnag** [microsoft/WSL#11537]
### Windows Version

10.0.22631.3527

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

WSL 2.

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Debian Bookworm

### Other Software

- OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

### Repro Steps

Install the beta of Microsoft's OpenSSH.

```ps1
winget install Microsoft.OpenSSH.Beta
```

Test it with this command in PowerShell:

```ps1
> & "C:\Program Files\OpenSSH\ssh.exe" -V
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

From a WSL distribution run test it as well:

```sh
> /mnt/c/Program\ Files/OpenSSH/ssh.exe -V
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

Place following file at `/root/test.sh`:

```sh
#!/bin/sh
export PATH="/mnt/c/Program Files/OpenSSH"
ssh.exe -V
exit_code=$?
echo "EXIT_CODE=$exit_code"
exit $exit_code
```

Make file executable and run it for test:

```sh
chmod +x /root/test.sh
/tmp/test.sh
```

Place following file at `/etc/systemd/system/test.service`:

```ini
[Unit]
Description=Test

[Service]
Type=simple
ExecStart=/root/test.sh

[Install]
WantedBy=multi-user.target
```

Reload systemd, start service, check status:

```sh
systemctl daemon-reload
systemctl start test
sleep 1
systemctl status test
```

### Expected Behavior

Exit code 0.

### Actual Behavior

Exit code 57.

```txt
> systemctl status test
x test.service - Test
     Loaded: loaded (/etc/systemd/system/test.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-04-29 20:44:53 CEST; 2s ago
   Duration: 17ms
    Process: 302 ExecStart=/root/test.sh (code=exited, status=57)
   Main PID: 302 (code=exited, status=57)
        CPU: 1ms

Apr 29 20:44:53 Metro systemd[1]: Started test.service - Test.
Apr 29 20:44:53 Metro test.sh[302]: EXIT_CODE=57
Apr 29 20:44:53 Metro systemd[1]: test.service: Main process exited, code=exited, status=57/n/a
Apr 29 20:44:53 Metro systemd[1]: test.service: Failed with result 'exit-code'.
```

### Diagnostic Logs

It works perfectly fine when I call the executable at `/mnt/c/Windows/System32/OpenSSH` instead.

**Comment by trallnag** [comment]
Here are the logs.
[WslLogs-2024-04-29_20-50-26.zip](https://github.com/microsoft/WSL/files/15153597/WslLogs-2024-04-29_20-50-26.zip)

**Comment by OneBlue** [comment]
Thank you @trallnag. Can you share an strace of calling into ssh.exe from systemd ? (strace -f ssh.exe -V) 

This should help us understand why things are failing

**Comment by trallnag** [comment]
@OneBlue, here you go

`strace-ssh-as-root.txt` contains strace where I executed command as root. Here I get exit code 0.

`strace-ssh-as-systemd.txt` contains strace where command is executed from within a systemd service as root. Here I get exit code 57.

[strace-ssh-as-root.txt](https://github.com/microsoft/WSL/files/15180802/strace-ssh-as-root.txt)
[strace-ssh-as-systemd.txt](https://github.com/microsoft/WSL/files/15180803/strace-ssh-as-systemd.txt)

**Comment by OneBlue** [comment]
Ok interesting. I'm not seeing anything that jumps out in the logs. Do you see the same behavior with other Windows commands, like "cmd /c echo ok" for instance ?

**Comment by trallnag** [comment]
Here is another strace whre command is executed from within systemd service as root but against old / included OpenSSH located at `/mnt/c/Windows/System32/OpenSSH/ssh.exe` (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3).

It is extremly similar to `strace-ssh-as-systemd.txt`.

[strace-ssh-old-as-systemd.txt](https://github.com/microsoft/WSL/files/15181475/strace-ssh-old-as-systemd.txt)

> Do you see the same behavior with other Windows commands, like "cmd /c echo ok" for instance ?

No, at least I have not found another executable that behaves like that.

[strace-cmd-as-systemd.txt](https://github.com/microsoft/WSL/files/15181517/strace-cmd-as-systemd.txt)
 
Maybe if I find the time I can try older version between 8.6p1 (exit code 0) and 9.5p1 (exit code 57).

**Comment by OneBlue** [comment]
Ok interesting. 

Based on the fact this scenario works older versions of ssh.exe, this is most likely a regression in ssh.exe itself, maybe it poorly handles the case where this is no tty ? 

Either way, it's sadly not something that WSL can fix, so closing this.

**Comment by trallnag** [comment]
I tried it today again for another reason on another device and here it works. Same version.

```
○ test.service - Test
     Loaded: loaded (/etc/systemd/system/test.service; disabled; preset: enabled)
     Active: inactive (dead)

May 27 00:01:53 pringles systemd[1]: Started test.service - Test.
May 27 00:01:54 pringles test.sh[645]: OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
May 27 00:01:54 pringles test.sh[643]: EXIT_CODE=0
May 27 00:01:54 pringles systemd[1]: test.service: Deactivated successfully.
```

Weird

**Comment by Phault** [comment]
In case anybody else lands here from Google like me:

I hit this issue as well, but it was resolved after disabling OpenSSH Client from Windows' optional features and reinstalling Microsoft.OpenSSH.Beta via Winget. So a silly mistake, and I'm assuming they conflicted somehow.
