### ISSUE TITLE
 wsl --install -d kali-linux 无法从“https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json”中提取列表分发。无法解析服务器的名称或地址 Error code: Wsl/InstallDistro/WININET_E_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by diablo1897** [microsoft/WSL#11530]
### Windows Version

Microsoft Windows [版本 10.0.19045.4355]

### WSL Version

WSL 版本： 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

kali

### Repro Steps

 wsl --install -d kali-linux
无法从“https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json”中提取列表分发。无法解析服务器的名称或地址
Error code: Wsl/InstallDistro/WININET_E_NAME_NOT_RESOLVED

### Expected Behavior

 wsl --install -d kali-linux
无法从“https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json”中提取列表分发。无法解析服务器的名称或地址
Error code: Wsl/InstallDistro/WININET_E_NAME_NOT_RESOLVED

### Actual Behavior

 wsl --install -d kali-linux
无法从“https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json”中提取列表分发。无法解析服务器的名称或地址
Error code: Wsl/InstallDistro/WININET_E_NAME_NOT_RESOLVED

**Comment by diablo1897** [comment]
在cmd 下运行wsl --install -d kali-linux
无法从“[https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json”中提取列表分发。无法解析服务器的名称或地址](https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json%E2%80%9D%E4%B8%AD%E6%8F%90%E5%8F%96%E5%88%97%E8%A1%A8%E5%88%86%E5%8F%91%E3%80%82%E6%97%A0%E6%B3%95%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%8D%E7%A7%B0%E6%88%96%E5%9C%B0%E5%9D%80)
Error code: Wsl/InstallDistro/WININET_E_NAME_NOT_RESOLVED

**Comment by OneBlue** [comment]
This error code is usually transient. Can you collect /logs if this reproduces again ?
