### ISSUE TITLE
Error code: Wsl/Service/RegisterDistro/E_FAIL

### ISSUE THREAD

**Issue by InkeyP** [microsoft/WSL#11545]
### Windows Version

Microsoft Windows [版本 10.0.22621.1848]

### WSL Version

 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22

### Repro Steps

PS F:\> wsl --import Ubuntu2 F:\WSL2\Ubuntu2\ .\backup.tar --version 2
正在导入，这可能需要几分钟时间。
未指定的错误
Error code: Wsl/Service/RegisterDistro/E_FAIL

### Expected Behavior

import successful

### Actual Behavior

Error code: Wsl/Service/RegisterDistro/E_FAIL

**Comment by InkeyP** [comment]
[WslLogs-2024-05-01_08-25-29.zip](https://github.com/microsoft/WSL/files/15172435/WslLogs-2024-05-01_08-25-29.zip)

**Comment by MandyZhang4869** [comment]
想问问你解决了吗……

**Comment by InkeyP** [comment]
> 想问问你解决了吗……

no

**Comment by MandyZhang4869** [comment]
我把旧的export的那个给删了，重新export 和 import就没问题了
