### ISSUE TITLE
Networking mode does not work in mirrored mode

### ISSUE THREAD

**Issue by Marc2p** [microsoft/WSL#11540]
### Windows Version

Microsoft Windows [Version 10.0.22631.3527

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

Configure the .wslconfig file as follows:
networkingMode=mirrored
dnsTunneling=true

### Expected Behavior

Windows network interfaces are mirrored in wsl

### Actual Behavior

A notification appears saying Errors have occurred during WSL startup and it is running in nat mode

### Diagnostic Logs

[WslNetworkingLogs-2024-04-30_08-47-29.zip](https://github.com/microsoft/WSL/files/15163108/WslNetworkingLogs-2024-04-30_08-47-29.zip)

**Comment by AzureLeMoon** [comment]
do you have the "[wsl2]" tag before writing the networkingMode key ?

like below :

[wsl2]
networkingMode=mirrored

**Comment by Marc2p** [comment]
It worked for me. Thank you
