### ISSUE TITLE
WSL2-Linux-Kernel Headers

### ISSUE THREAD

**Issue by raheel103** [microsoft/WSL#11557]
I would like Headers installation option in WSL2-Linux-Kernel , I'm trying to install a module (v4l2loopback) and it requires headers installed at /lib/modules/5.15.146.1-Microsoft-standard-wsl2+ . I searched online and they say wsl2 msft linux kernel doesn't come with headers , will normal linux headers from apt work?

**Comment by zcobol** [comment]
@raheel103 you need to match the headers with the current running kernel. The easy way is to get the WSL kernel source from https://github.com/microsoft/WSL2-Linux-Kernel/releases, run `make headers_install` and supply  the correct `INSTALL_HDR_PATH`. It defaults to `INSTALL_HDR_PATH=/usr` so the kernel headers will be dropped in `/usr/include`. See details at https://www.kernel.org/doc/html/latest/kbuild/headers_install.html
