### ISSUE TITLE
Error whilst upgrading from 14.04 to 16.04

### ISSUE THREAD

**Issue by chesterm8** [Microsoft/WSL#1155]
The following was encountered whilst upgrading 14.04 to 16.04 using do-release-upgrade (on build 14936)

**package lsof 4.86+dfsg-1ubuntu2 failed to install/upgrade: unable to open '/usr/share/doc/lsof/examples/count_pf.perl.dpkg-new': Permission denied**

Ubuntu created a bugreport semi-automatically, I imagine it contains useful information to investigate the issue. [https://bugs.launchpad.net/ubuntu/+source/lsof/+bug/1629735](https://bugs.launchpad.net/ubuntu/+source/lsof/+bug/1629735)

**Comment by andylh** [comment]
I cannot upgrade at all.
on do-release-upgrade get
checking for new Ubuntu release
Get1: Upgrade tool signature [198 B]
Get2 Upgrade tool [1,262 kB]
100% working 
then:
an exit with a on-screen message saying "[screen is terminating]" I cannot do anything else.

**Comment by benhillis** [comment]
Please include the Windows build you are running. Screen is fixed in recent Windows Insider builds but not in the Anniversary Update.

**Comment by andylh** [comment]
This error is on Version 1607, build 14393-222

Every attempt to do the upgrade creates a directory in /tmp with the name
and date of the download and lots of content. The error that v. quickly
flashes on the screen before screen abruptly exits is about no such
file/directory /var/run/utmp.

Searching on the web about this gave various pointers but none corrected
the behaviour.



Andrew Hart C.Eng. MRINA
amateur radio calls G8VTV / VE3NVK / VA3AIT locator FN25bh

28, Chimo Drive, Kanata, ON, K2L 1A5 Canada

tel: 613 592 5043

The content of this message is *NOT* intended for the public, and is a
private communication.

**Comment by saivert** [comment]
You are able to run do-release-upgrade if you run a X11 server like this:

do-release-upgrade -f gtk

Altough it will still give errors about not being able to create dpkg-new files.
