### ISSUE TITLE
OneDrive shared folder and chmod

### ISSUE THREAD

**Issue by fredmo** [microsoft/WSL#11556]
### Windows Version

Microsoft Windows [version 10.0.22631.3527]

### WSL Version

2.2.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Other Software

OneDrive Windows : Build 24.076.0414.0005 (64 bits)

### Repro Steps

I have a OneDrive folder in Windows.
By using this folder in WSL2, there is no support of chmod.

=> on WSL  :
touch ~/OneDrive/test
**chmod +x ~/OneDrive/test
chmod: changing permissions of '/home/my/OneDrive/test': Operation not permitted**

=> on Native Ubuntu : 
It s disturbing because on native linux/ubuntu (24.04), I am able to mount the OneDrive with rclone, and I don't have error of chmod.
**chmod +x ~/OneDrive/test**
ls -ltr ~/OneDrive/test 
ls: /home/me/OneDrive/test: Input/output error
-rw-rw-r-- 1 sah0027 sah0027 0 May  5 17:32 /home/me/OneDrive/test
Yes, in native ubuntu the chmod is not applied , but it s not doing the error on chmod.

( ps : is there a way to have permission support enabled on a OneDrive shared folder ?) 

Regards, 

### Expected Behavior

The issue is to have a difference of behaviour,  personally i would prefer the behaviour Ubuntu native.
=> chmod ok

### Actual Behavior

=> on WSL  :
touch ~/OneDrive/test
**chmod +x ~/OneDrive/test
chmod: changing permissions of '/home/my/OneDrive/test': Operation not permitted**

**Comment by fredmo** [comment]
Ps: 
in /etc/wsl.conf  , I have :
[automount]
     options = "metadata"

**Comment by fredmo** [comment]
and with mount , I see : 

C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;metadata;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=11,wfd=11)


And in wsl,  ~/OneDrive is a symlink to : /mnt/c/XX/OneDrive - YY/

**Comment by OneBlue** [comment]
The error you're seeing is because Linux permissions don't really make sense for a OneDrive folder mounted on the Windows side. 

Accessing the files themselves should work though. Could you capture logs of the file accesses failing ? /logs
