### ISSUE TITLE
autoProxy not creating all proxy variants

### ISSUE THREAD

**Issue by Renan-Di** [microsoft/WSL#11551]
### Windows Version

Windows 11 22621.3447

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

Configure .wslconf with
[wsl2]
autoProxy=true

### Expected Behavior

WSL to configure http and https proxy variables as stated here: [WSL Troubleshoot](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#considerations-when-using-autoproxy-for-httpproxy-mirroring-in-wsl)

> When enabled, the following apply to proxy settings on your Linux distributions:
> The Linux environment variable, HTTP_PROXY, is set to the one or more HTTP proxies found installed in the Windows HTTP proxy configuration.
> The Linux environment variable, HTTPS_PROXY, is set to the one or more HTTPS proxies found installed in the Windows HTTP proxy configuration.
> The Linux environment variable, NO_PROXY, is set to bypass any HTTP/S proxies found in the Windows configuration targets.
> Every environment variable, except WSL_PAC_URL, is set to both lower case and upper case. For example: HTTP_PROXY and http_proxy.

### Actual Behavior

Only http_proxy, HTTP_PROXY and WSL_PAC_URL are being created on wsl.

**Comment by z3non** [comment]
re-filed here https://github.com/microsoft/WSL/issues/12469
