### ISSUE TITLE
WSL2 is slow and makes my computer unresponsive when running a C++ build in Debug mode inside Docker container

### ISSUE THREAD

**Issue by pksilen** [microsoft/WSL#11559]
### Windows Version

10.0.19044.4291

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Other Software
Docker 25.0.3
Gcc 13. But this problem has appeared with earlier version of Gcc also.

### Repro Steps

Inside a Docker container, compile a C++ project in Debug mode using 'make' command  e.g.
make -j 16}; \

### Expected Behavior

Normal build that takes a normal time

### Actual Behavior

Build is extremely slow and makes the whole computer unresponsive, e.g. trying to start an application takes a long time. However, CPU usage is not close to 100%.

### Diagnostic Logs

When I run the same build in Release mode, the build executes in a normal fashion (fast).

**Comment by pksilen** [comment]
I cannot upload the log file, it is 93MB, but only 25MB is allowed. Please advice

**Comment by pksilen** [comment]
Logs attached
[WslLogs-2024-05-06_12-57-22.zip](https://github.com/microsoft/WSL/files/15219158/WslLogs-2024-05-06_12-57-22.zip)

**Comment by pksilen** [comment]
The problem seems to be related to C++ Debug build only. When I run the same build in Release mode, it executes the build without problems very fast.

**Comment by pksilen** [comment]
When trying to capture the logs, I get the below message. Please advice


```
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At line:2 char:1
+ Set-ExecutionPolicy Bypass -Scope Process -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

**Comment by OneBlue** [comment]
@pksilen: Which path are you running the build from ? If it's under /mnt/, it's expect that file accesses are slower
