### ISSUE TITLE
Why is it borderline impossible to downgrade WSL2?

### ISSUE THREAD

**Issue by fabis94** [microsoft/WSL#11562]
**Is your feature request related to a problem? Please describe.**
There have been multiple times already when a WSL2 update has changed and broken some networking settings, and it will probably keep happening - no one is perfect, not even WSL2 developers. 

Thus it should be possible to install a specific WSL version (any of those from the releases page), without having to go through hoops. Previously there was a `wsl --update --rollback` option, which wasn't perfect (didn't allow you to specify a specific version), but at least rolled back a version, but then you removed it.

There was also a very hidden (took me ages to find this through google, why is it so hidden!) way to install a specific release like this:
`powershell Add-AppxPackage -Path .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle -ForceUpdateFromAnyVersion -ForceApplicationShutdown`

But as we tried this on a colleague's machine, we got this error:
`error 0x80073D27: While processing the request, the system failed to register the windows.service extension due to the
following error: The package installation failed because a version of the service exists outside of APPX packaging.
Please contact your software vendor.`

So apparently that's no longer supported either? Or at the very least it expects you to fully uninstall WSL2 (and lose your distro setup) before doing the downgrade.

Being able to downgrade is an important troubleshooting step, even if you think WSL2 releases are perfect and bugfree (have they ever been?), so this should be made as easy as possible!

**Describe the solution you'd like**
It should be easy to find docs on how to downgrade and it should be easy to do it too. There should just be a CLI flag to install a specific version: `wsl --downgrade 1.2.3`

Please for the love of god introduce this feature so troubleshooting WSL2 environments is less painful

**Describe alternatives you've considered**
There is no alternative to downgrading when you're troubleshooting issues. Sometimes WSL2 just has a buggy version out and all you can do is either downgrade or wait for the issue to be resolved (which could take weeks or months depending on how complicated the issue is).

**Comment by OneBlue** [comment]
Thank you @fabis94.

Automatically downgrading to older versions of WSL is unfortunately very difficult to achieve at the technical level, and is a relatively rare scenario.

In your case though since you appear to be downgrading from >= 2.0.0 to 1.X, here's what you were missing: 

Running: 

```
wsl --uninstall
``` 

Before installing  a version < 2.0.0 should resolve the issue.

**Comment by fabis94** [comment]
@OneBlue Fair enough. Could this information about why downgrading is not made possible and instructions on how to rollback be made more visible, tho? That's the other problem - it is very difficult to find any resources explaining what is the recommended procedure for rolling back versions, and a lot of it is outdated (pointing towards wsl --update --rollback).
