### ISSUE TITLE
wsl.exe cpu too high

### ISSUE THREAD

**Issue by paopaol** [microsoft/WSL#11569]
### Windows Version

10.0.22631.3527

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

centos7

### Other Software

WSL 版本： 2.1.5.0
内核版本： 5.15.146.1-2
WSLg 版本： 1.0.60
MSRDC 版本： 1.2.5105
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22631.3527

### Repro Steps

It happens randomly, sometimes with high frequency, sometimes with low frequency, but almost every day

### Expected Behavior

cpu normal

### Actual Behavior

cpu is abnormal

### Diagnostic Logs

![image](https://github.com/microsoft/WSL/assets/6983082/ea7333e5-bbb2-4b04-9990-4707d99994ee)

![image](https://github.com/microsoft/WSL/assets/6983082/2329ae9a-9fe6-41b2-990c-02fac95c6ab6)
![image](https://github.com/microsoft/WSL/assets/6983082/17658421-faed-476c-a69a-cdeac268fb9a)
![image](https://github.com/microsoft/WSL/assets/6983082/271fad0c-a39c-47e2-b793-b61d5f694a14)

**Comment by paopaol** [comment]
[WslLogs-2024-05-08_12-22-33.zip](https://github.com/microsoft/WSL/files/15243815/WslLogs-2024-05-08_12-22-33.zip)

**Comment by OneBlue** [comment]
Thank you @paopaol.

If wsl.exe is where the CPU is being consumed, could you share a dump of wsl.exe when you see high CPU usage ? 
Can you also share the output of running `top` inside `wsl --debug-shell` while the CPU usage is high ?

**Comment by MKN-MCI** [comment]
I experience these complete WSL lock-ups often (every second day currently) running Ubuntu in WSL.

`wsl --debug-shell` hanging (for ~10 minutes here, no hope of response, have had it sit there for whole days before reboot was convenient):
![image](https://github.com/microsoft/WSL/assets/159158343/a6d58803-ce14-48cf-b695-3852d570d3a4)

`wsl --version output` and plain `wsl` hanging (again for ~5minutes):
![image](https://github.com/microsoft/WSL/assets/159158343/4d7ca4ea-71f3-4f17-86f7-5a0b4ba7bbae)

`vmmem` hogging resources, usually 80-90% CPU and 10-15 GiB memory:
![image](https://github.com/microsoft/WSL/assets/159158343/9a2cead1-ee78-4f3b-953c-598f6d7bde25)
