### ISSUE TITLE
After installing KB5036893, WSL now logs an event regarding "Invalid networking mode 'mirrored' in C:\Users\<username>\.wslconfig"

### ISSUE THREAD

**Issue by ZenInTexas** [microsoft/WSL#11568]
### Windows Version

Microsoft Windows [Version 10.0.22631.3447]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

.wslconfig

#Entry networkingMode require Windows 11 version 22H2(or higher)
networkingMode=mirrored

### Expected Behavior

.wslconfig, networkingMode=mirrored should run

### Actual Behavior

After installation of KB, WSL now emits an event regarding mirrored

### Diagnostic Logs

Log Name:      Application
Source:        WSL
Date:          5/7/2024 7:59:07 AM
Event ID:      0
Task Category: None
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      CPU2
Description:
The description for Event ID 0 from source WSL cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Invalid networking mode 'mirrored' in C:\Users\<username>\.wslconfig

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="WSL" />
    <EventID Qualifiers="40960">0</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-05-07T12:59:07.0565641Z" />
    <EventRecordID>50723</EventRecordID>
    <Correlation />
    <Execution ProcessID="6644" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>CPU2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Invalid networking mode 'mirrored' in C:\Users\<username>\.wslconfig</Data>
  </EventData>
</Event>

**Comment by zcobol** [comment]
@ZenInTexas if you're using `wsl-2.0.0` still,  the setting must be added under `[experimental]` tag:

```
[experimental]
networkingMode=mirrored
```

The feature was promoted in a later wsl release.

**Comment by ZenInTexas** [comment]
@zcobol, thanks I moved it to under [experimental] tag, and it no longer creates an Windows Event under WSL for "Invalid networking mode 'mirrored'"

I am going to try  upgrading, with "wsl --update --web-download", which it looks like will get me to wsl 2.1.5

**Comment by ZenInTexas** [comment]
Closed

**Comment by dobrik-ardas** [comment]
In some cases it happens because /etc/resolv.conf overridden. To fix that execute following commands
`sudo rm /etc/resolv.conf
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "[network]" > /etc/wsl.conf'
sudo bash -c 'echo "generateResolvConf = false" >> /etc/wsl.conf'
sudo chattr +i /etc/resolv.conf`
