### ISSUE TITLE
Error message on `wsl --exec`  can be more informative

### ISSUE THREAD

**Issue by firejox** [microsoft/WSL#11571]
**Is your feature request related to a problem? Please describe.**

It is hard to find the root of problem when run `wsl --exec` failed. For example, run a non-exist command
`wsl --exec` will show
```
C:\Users\dell>wsl -d Ubuntu --cd ~ --exec bla
<3>WSL (1288) ERROR: CreateProcessEntryCommon:505: execvpe bla failed 2
<3>WSL (1288) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
```

However, `wsl --` will show
```
C:\Users\dell>wsl -- bla
/bin/bash: line 1: bla: command not found
```

In the first case, people only know run `bla` failed and with a number 2. And in second case, people will know `bla` is not found. 

It can save people's lives, if error message on `wsl --exec` can be as informative as `wsl --` .

**Comment by benhillis** [comment]
I don't recall what version we changed this, but in more recent versions the error message is more actionable:

C:\Users\benhill>wsl --exec bla
<3>WSL (498) ERROR: CreateProcessCommon:500: execvpe(bla) failed: No such file or directory

I'm on 2.3.4.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.3.11.
