### ISSUE TITLE
WSL doesn't source ~/.bashrc when running wsl --shell-type login xeyes

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/WSL#11579]
### Windows Version

Microsoft Windows [Version 10.0.22631.3447]

### WSL Version

 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-22621-Microsoft

### Distro Version

Ubuntu 22.04

### Other Software

x11-apps
VcXsrv

### Repro Steps

1. Install ubuntu.
2. Install vcxsrv
3. install x11-apps
4. add export DISPLAY=:0 to ~/.bashrc
5. exit wsl
6. start vcxsrv
7. run wsl --shell-type login xeyes

### Expected Behavior
It works when i run command from inside 
![image](https://github.com/microsoft/WSL/assets/8822292/804b4695-41a2-4c2f-8062-0050a1a28b73)

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/8822292/586f7e95-b3ed-44bf-933e-c7bf0efcc9a7)

**Comment by kotenok2000** [comment]
[WslLogs-2024-05-11_21-14-08.zip](https://github.com/microsoft/WSL/files/15283884/WslLogs-2024-05-11_21-14-08.zip)

**Comment by kotenok2000** [comment]
Uploading bandicam 2024-05-12 00-09-53-353.mp4…

**Comment by OneBlue** [comment]
@kotenok2000: This is by design. bash does not source .bashrc for login shells. 

If you want to have something sourced by a login shell, `.profile` would be the best place to put it
