### ISSUE TITLE
ALSA error while running pygame from WSL2 - Windows 11

### ISSUE THREAD

**Issue by DanteNahuel** [microsoft/WSL#11580]
Hi
I'm playing around with pygame using WSL2 on Windows 11. I'm using 22.04 distro and I'm using a venv specifically for this project.

When I run pygame.init(), I get ALSA errors:

pygame 2.5.2 (SDL 2.28.2, Python 3.10.12) Hello from the pygame community. https://www.pygame.org/contribute.html ALSA lib confmisc.c:855:(parse_card) cannot find card '0' ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default 

I did some googling and I found that for Windows 10, I should install something like PulseAudio in Windows and connect to it from WSL2.
However, in Windows 11 I should have native sound features. But that doesn't seem to be the case.

What am I doing wrong?

**Comment by viruscamp** [comment]
You ant least need packages below: 
libasound2
libasound2-plugins
libpulse0
