### ISSUE TITLE
du: WARNING: Circular directory structure.

### ISSUE THREAD

**Issue by Hopsakee** [microsoft/WSL#11588]
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Open Ubuntu 22.04 distro in WSL
2. run: 'sudo du -h --max-dept=1` from root folder

### Expected Behavior

Just show the size of the folders in root.

### Actual Behavior

Show the size of the folders in root with following warning:

> du: WARNING: Circular directory structure.
> This almost certainly means that you have a corrupted file system.
> NOTIFY YOUR SYSTEM MANAGER.
> The following directory is part of the cycle:
>   ./sys/kernel/debug/device_component

### Diagnostic Logs

[trace output from command](https://gist.github.com/Hopsakee/8601deb3819c275871b742eaf02c3032)

**Comment by Hopsakee** [comment]
There are several closed but not resolved issues like this one. Among those are the three the kindly bot just mentioned.

**Comment by Hopsakee** [comment]
I mailed the WSL logs to wsl-gh-logs@microsoft.com.

**Comment by zcobol** [comment]
@Hopsakee skip that folder with `--exclude` argument:

`sudo du -h --max-depth=1 --exclude=/sys/kernel/debug/device_component`

That directory is empty most likely!

**Comment by Hopsakee** [comment]
@zcobol thanks for your reply. If I understand you correctly I can ignore the "This almost certainly means that you have a corrupted file system." because it's raised by an empty directory and not an actual circular reference indicating I have somehow corrupted my file system?

In that case I'm happy to ignore the warning using --exclude.

**Comment by zcobol** [comment]
`/sys/kernel/debug` is a virtual filesystem. If you try to list any file it will show as `empty` because they are not real files but entry points into current running kernel. And is nothing unusual to have cross-references inside `sysfs`.  Unmount `/sys/kernel/debug` and run `du` again.

**Comment by Hopsakee** [comment]
Great. I understand. Thanks.
