### ISSUE TITLE
Internet in WSL2 error when using mirrored network with firewall

### ISSUE THREAD

**Issue by pengyusi** [microsoft/WSL#11585]
### Windows Version

10.0.22621.3447

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04

### Other Software

Symantec Endpoint

### Repro Steps

Since the win10 does not support mirrored network, and the Symantec Endpoint always refuses the connection between win host and wsl (as in other issues reported like #5382 ), I update my os to win11 and set the network to mirrored. But the network situation does not fixed. The problems:
__in wsl2__:
* ping www.baidu.com __success__
* nslookup www.baidu.com 
```bash 
Server:         127.0.0.42
Address:        127.0.0.42#53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com.
Name:   www.a.shifen.com
Address: 180.101.50.242
Name:   www.a.shifen.com
Address: 180.101.50.188
Name:   www.a.shifen.com
Address: 240e:e9:6002:15c:0:ff:b015:146f
Name:   www.a.shifen.com
Address: 240e:e9:6002:15a:0:ff:b05c:1278
```
* SSH user@192.168.xx.xx __timeout__
* showmount -e 192.168.xx.xx __clnt_create: RPC: Timed out__

__in win powershell:__
* nslookup get the same output
* ping normal
* ssh normal

__network settings__
* wsl2
```bash
ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.37.71  netmask 255.255.255.0  broadcast 192.168.37.255
```
* win PowerShell
```bash
ip addr  192.168.37.71
subnet mask 255.255.255.0
gateway 192.168.37.254
```

### Expected Behavior

the SSH, RPC and CURL should work normally.
in NAT, the Symantec Endpoint blocked the TCP data between wsl and host, but when using mirrored network, there shouldn't be TCP connection, so how the firewall blocks the data and how can I fix it?

### Actual Behavior

actual behaviors are like those mentioned above. 
when I set HTTP proxy, the curl works, and configuring the SSH through HTTP proxy also allows the SSH but that's not the solution

**Comment by OneBlue** [comment]
@pengyusi: The easiest way to transmit data between WSL and Windows would be to use the localhost relay. If you bind a port on either side, you can then simply connect to it via 127.0.0.1 on the other side.
