### ISSUE TITLE
Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff

### ISSUE THREAD

**Issue by penndev** [microsoft/WSL#11597]
### Windows Version

Microsoft Windows [版本 10.0.19045.4412]

### WSL Version

WSL 版本： 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Other Software

WSL 版本： 2.1.5.0
内核版本： 5.15.146.1-2
WSLg 版本： 1.0.60
MSRDC 版本： 1.2.5105
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.19045.4412

### Repro Steps

```
PS C:\WINDOWS\system32> wsl
无法配置 networkingMode Nat)(网络。若要禁用网络，请在C:\Users\Penn\.wslconfig中设置“wsl2.networkingMode=None”
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
PS C:\WINDOWS\system32> netstat -ano | findstr "UDP" | findstr -r "0.0.0.0:53"
  UDP    0.0.0.0:53             *:*                                    5796
  UDP    0.0.0.0:5353           *:*                                    19448
  UDP    0.0.0.0:5353           *:*                                    18736
  UDP    0.0.0.0:5353           *:*                                    13628
  UDP    0.0.0.0:5353           *:*                                    13628
  UDP    0.0.0.0:5353           *:*                                    3184
  UDP    0.0.0.0:5353           *:*                                    19448
  UDP    0.0.0.0:5353           *:*                                    18736
  UDP    0.0.0.0:5355           *:*                                    3184
PS C:\WINDOWS\system32> taskkill /pid 5796 /f
成功: 已终止 PID 为 5796 的进程。
PS C:\WINDOWS\system32> wsl
penn@LAPTOP-MHK154ON:/mnt/c/WINDOWS/system32$
```

### Expected Behavior

My WSL has been running well until one time when my system underwent an upgrade and rebooted. After that, WSL couldn't start until I discovered that I had to kill the process occupying UDP port 53 in Windows to restore it to normal. Now I have to do this every time to use WSL, which is very inconvenient. I want WSL to be normal right after booting up.   

### Actual Behavior

无法配置 networkingMode Nat)(网络。若要禁用网络，请在C:\Users\Penn\.wslconfig中设置“wsl2.networkingMode=None”
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff

**IF disable (Host Network Service)**

终结点映射器中没有更多的终结点可用。
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0x800706d9

**Comment by penndev** [comment]
> /question

**Comment by penndev** [comment]
Like this issue https://github.com/microsoft/WSL/issues/11334, but I can't remove the system's occupation.

**Comment by penndev** [comment]
> Like this issue #11334, but I can't remove the system's occupation.
```
[wsl2]
networkingMode=NAT
dnsTunneling=true
```

wsl: DNS 隧道不受支持
无法配置 networkingMode Nat)(网络。若要禁用网络，请在C:\Users\Penn\.wslconfig中设置“wsl2.networkingMode=None”
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff

**Comment by chanpreetdhanjal** [comment]
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by penndev** [comment]
I have upgraded to Windows 11 and resolved this issue.
