### ISSUE TITLE
WSL2 Memory Allocation Issue: Configured 55GB but Only 32GB Available

### ISSUE THREAD

**Issue by springeye** [microsoft/WSL#11595]
### Windows Version

Microsoft Windows [版本 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1

### Distro Version

Ubuntu 22.04

### Repro Steps

I have 64GB of RAM on my computer, and I want to allocate 55GB to WSL2. I configured the memory to 55GB in my .wslconfig file, but when I check the total memory using the free command in WSL, it only shows 32GB

![image](https://github.com/microsoft/WSL/assets/1314740/ff818f2e-696f-44f8-84d8-bfafdcdc8d95)

![image](https://github.com/microsoft/WSL/assets/1314740/b3a5471a-612b-4759-945c-1ada9a2c51d3)

### Expected Behavior

Running free -h in WSL2 should show a total of 55GB

### Actual Behavior

Only 32GB Available

**Comment by 0xbadfca11** [comment]
memory is not experimental feature.

**Comment by springeye** [comment]
> 记忆不是实验功能。
thk
