### ISSUE TITLE
Ubuntu-20.04.6 LTS takes 30+ minutes to boot

### ISSUE THREAD

**Issue by KiranZacharia** [microsoft/WSL#11592]
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04

### Other Software

n/a

### Repro Steps

Boot system 
From Start menu, launch Ubuntu 20.04

### Expected Behavior

Ubuntu 20.04 launches in 1-2 minutes

### Actual Behavior

Ubuntu 20.04 takes 30 to 40 minutes to launch

### Diagnostic Logs

[WslNetworkingLogs-2024-05-16_11-22-40.zip](https://github.com/microsoft/WSL/files/15337568/WslNetworkingLogs-2024-05-16_11-22-40.zip)

**Comment by OneBlue** [comment]
Thank you @KiranZacharia. I'm not seeing anything that could explain that in the logs, so I wonder if this could be caused by your shell prompt. 

Can you share the output of (powershell): 

```
Measure-Command { wsl.exe --exec echo ok }
``` 
?

**Comment by Ndiritu** [comment]
Facing this same issue.

`Measure-Command { wsl.exe --exec echo ok }` has been running from > 15 mins now without returning.

I collected some logs using `collect-wsl-logs.ps1` 
[WslLogs-2024-05-17_06-10-59.zip](https://github.com/microsoft/WSL/files/15343484/WslLogs-2024-05-17_06-10-59.zip)

**Comment by KiranZacharia** [comment]
I installed the WSL V2.2.4.0 from the release folder and it is now working normally.
