### ISSUE TITLE
MPV playback fails on WSL with various audio and video errors

### ISSUE THREAD

**Issue by dewijones92** [microsoft/WSL#11609]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

WSL version: 2.1.5.0 Kernel version: 5.15.146.1-2 WSLg version: 1.0.60 MSRDC version: 1.2.5105 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22631.3593

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Default Distribution: Ubuntu Default Version: 2

### Repro Steps

Playing an audio or video file using mpv

### Expected Behavior

I should see and hear it

### Actual Behavior

Sometimes nothing happens

### Diagnostic Logs

**Successful Playback Output:**

```
[0/0] (+) Video --vid=1 (*) (h264 1280x720 50.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Cannot retrieve DRM resources: Operation not supported
[vo/gpu/opengl] Failed to create KMS.
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
AO: [pulse] 48000Hz stereo 2ch float
VO: [wlshm] 1280x720 yuv420p
AV: 00:00:05 / 00:02:30 (4%) A-V:  0.000 Dropped: 2
```

**Failed Playback Output:**

```
[0/0] (+) Video --vid=1 (*) (h264 1280x720 50.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Cannot retrieve DRM resources: Operation not supported
[vo/gpu/opengl] Failed to create KMS.
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
[vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[ao/pulse] Init failed: Timeout
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
...
```

**Error Messages:**

* `ALSA lib confmisc.c:855:(parse_card) cannot find card '0'`
* `ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory`
* `[ao/pulse] Init failed: Timeout`
* `[ao/alsa] Playback open error: No such file or directory`
* `[ao/jack] cannot open server`
* `[ao/sdl] could not open audio: ALSA: Couldn't open audio device: No such file or directory`
* `[ao] Failed to initialize audio driver 'sdl'`

**Expected Behavior:**

The video file should play successfully with audio and video output.

**Steps to Reproduce:**

1. Open a terminal in WSL.
2. Run the command `mpv Popcorn\ -\ Guitar\ Cover\ \(Fingerstyle\)\ \[BToVP8S71Is\].mkv` to play the video file.

**Additional Information:**

Please let me know if you need any additional information to troubleshoot this issue.

**Comment by withinboredom** [comment]
`mpv` works fine, try `mpv --no-config --vo=tct https://www.youtube.com/watch\?v\=dQw4w9WgXcQ`

Your terminal program doesn't support sixel, needed to render `--vo=drm`. This has nothing to do with WSL.
