### ISSUE TITLE
dmidecode not working because /dev/mem is missing

### ISSUE THREAD

**Issue by firewave** [microsoft/WSL#1161]
/usr/sbin/dmidecode
# dmidecode 2.12

/dev/mem: No such file or directory

I think the data parsed and shown by dmidecode is available in Windows itself via WMI and there is also a gnuwin32 version of dmidecode that works natively, so the data it requires should be available.

My Windows version is Windows 10 for Enterprise Version 1607 Build 14393.222

strace

strace /usr/sbin/dmidecode
execve("/usr/sbin/dmidecode", ["/usr/sbin/dmidecode"], [/\* 17 vars */]) = 0
brk(0)                                  = 0x7fffeae74000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b540000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=21970, ...}) = 0
mmap(NULL, 21970, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1d8b548000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P \2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1d8ae30000
mprotect(0x7f1d8afea000, 2097152, PROT_NONE) = 0
mmap(0x7f1d8b1ea000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f1d8b1ea000
mmap(0x7f1d8b1f0000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b1f0000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b530000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b520000
arch_prctl(ARCH_SET_FS, 0x7f1d8b520740) = 0
mprotect(0x7f1d8b1ea000, 16384, PROT_READ) = 0
mprotect(0x7f1d8b815000, 12288, PROT_READ) = 0
mprotect(0x7f1d8b422000, 4096, PROT_READ) = 0
munmap(0x7f1d8b548000, 21970)           = 0
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(4, 1), ...}) = 0
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b510000
write(1, "# dmidecode 2.12\n", 17# dmidecode 2.12
)      = 17
brk(0)                                  = 0x7fffeae74000
brk(0x7fffeae95000)                     = 0x7fffeae95000
open("/sys/firmware/efi/systab", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/proc/efi/systab", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("/dev/mem", O_RDONLY)              = -1 ENOENT (No such file or directory)
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fstat(3, {st_mode=S_IFCHR|0600, st_rdev=makedev(4, 1), ...}) = 0
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d8b500000
lseek(3, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
write(3, "/dev/mem: No such file or direct"..., 36/dev/mem: No such file or directory
) = 36
close(3)                                = 0
munmap(0x7f1d8b500000, 4096)            = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by therealkenc** [comment]
Duping forward to #4391 as new LZ.
