### ISSUE TITLE
WSL2 corrupts the git index on a mounted file system

### ISSUE THREAD

**Issue by zlatko-michailov** [microsoft/WSL#11619]
### Windows Version

Microsoft Windows [Version 10.0.26120.670]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 24.04 (also reproes on Ubuntu 22.04, openSUSE Leap 15.4, 15.5, and Tumbleweed)

### Other Software

git

### Repro Steps

Unfortunately it doesn't repro with smaller repos. But it consistently reproes with this particular repo.
__The key part is that the repo is stored on a mounted Windows drive.__

`mkdir /mnt/c/src` - anywhere on the Windows C: drive
`cd /mnt/c/src`
`git clone https://github.com/zlatko-michailov/abc.git`  - use this particular repo

`git checkout dev`
`git status` - should be clean
`git reset --hard HEAD` - this is the one that breaks it

### Expected Behavior

`git status` - should be clean
`ls -al .git` - all files should appear normal

### Actual Behavior

`git status` - all files from the repo appear as deleted
`ls -al .git` - index (always) and ORIG_HEAD (sometimes) appear as ???????

__This doesn't repro when the repo is stored in the WSL's own Linux file system.__

**Comment by zlatko-michailov** [comment]
I should mention that the issue gets resolved (until the next corruption) after closing all WSL shells and after running `wsl --shutdown`, which makes me think that an in-memory representation of the file system is corrupted but not the file system on the disk. Hopefully this helps.

**Comment by 2-bee-or-not-2-bee** [comment]
+1 on the issue, our team started experiencing this on random repos as well in the last couple of weeks, all stored on Windows partitions (accessed with /mnt/c/...)

**Comment by zlatko-michailov** [comment]
Yes, I forgot to mention that it started happening about 2 weeks ago. Please check what flights and updates have been rolled out.

**Comment by zcobol** [comment]
Filesystems mounted under `/mnt` are owned by `root` and you can't change ownership on these filesystems. You could use `sudo` but `git` won't like it, complaining about dubious file ownership, etc. It works fine if you launch your WSL distro with `-u root` option and work under this user.

**Comment by kodtaku** [comment]
Any traction on this issue?  It's stopping me from using wsl2 effectively. back to winbash. 👎 
It even thinks the file doesn't exist.

` ls .git/index
ls: cannot access '.git/index': No such file or directory`

I tried the a shell under root still the same problem. :-(

**Comment by zlatko-michailov** [comment]
Update -
I worked with the WSL team. They located the source of the issue, which appears to be outside of WSL. The owning team confirmed they were able to repro, and they started working on a fix. 

I was able to repro the regression only on Windows Insider builds. I couldn't repro it on a regular Windows build. So, if you can use a machine with a regular Windows build, or switch Windows channels, you can continue working until a fix rolls out.

**Comment by kodtaku** [comment]
Thanks appreciate it! 

Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎2022-‎11-‎28
OS build	22621.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

corporate being corporate they no longer give us that much control without a ticket. :-p

**Comment by zlatko-michailov** [comment]
I was notified today that the bug has been fixed, and I confirm that I can no longer repro it. So, I'm closing this issue.

You may need to run `Windows Updates` to get the fix, if you haven't done so today.

**Comment by zlatko-michailov** [comment]
Closing.

**Comment by kodtaku** [comment]
installed https://www.catalog.update.microsoft.com/Search.aspx?q=KB5039212 
then from ubuntu shell
mkdir gittest
cd gittest
git init
ls -al .git/

something wrong with the properties
HEAD  ????
config ????

git checkout -b branch01
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Do you know the kb i should install for the fix?

**Comment by thomasgeens** [comment]
Confirmation that updating the **Microsoft Defender for Endpoint plug-in for Windows Subsystem for Linux (WSL)** to version `>= 1.24.605.1` solves the issue.

**Comment by atbagga** [comment]
> installed https://www.catalog.update.microsoft.com/Search.aspx?q=KB5039212 then from ubuntu shell mkdir gittest cd gittest git init ls -al .git/
> 
> something wrong with the properties HEAD ???? config ????
> 
> git checkout -b branch01 fatal: not a git repository (or any parent up to mount point /mnt) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 
> Do you know the kb i should install for the fix?

Assuming you have MDE plug-in for WSL installed. You can update to the version 1.24.605.1 or later from here to resolve the issue. https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

**Comment by kodtaku** [comment]
Thanks!  I can confirm.
- git checkout <branch>
- git init 
Working well with not corruption.  

Back to my regularly scheduled magit. :-)
