### ISSUE TITLE
Can't install any distribution on WSL2 on Windows 11 Pro

### ISSUE THREAD

**Issue by s1nyx** [microsoft/WSL#11617]
### Windows Version

Microsoft Windows [version 10.0.22631.3527]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

So a bit of context, I am on a Laptop given by my company. We use Zscaler.
I was trying to install any distribution actually with `wsl --install -d Ubuntu` (also tried with Microsoft Store and got the same error code). 

### Expected Behavior

Ubuntu to be installed

### Actual Behavior

It showed the following error: "An error occurred during installation. distribution name 'ubuntu' error code 0x80004002"

### Diagnostic Logs

- Both features "Virtual Machine Platform" and "Windows Subsystem For Linux" are enabled on the Windows
- I have a tried somethings I've seen on previous github issues which had kind of the same issue as me but didn't change anything. 
- When I do `wsl --update` I get a message "This interface is no longer in charge"
- When I do `wsl -l -v` I get (because i have docker desktop installed currently offline): 
NAME                               STATE                      VERSION
* docker-desktop            Stopped                  2 
   docker-desktop-data   Stopped                  2

**Comment by s1nyx** [comment]
> @s1nyx `wsl --install -d Ubuntu` will pull from the store, and I had issues when installing from the store also. Try `wsl --install -d Ubuntu --web-download` instead. Before installing a distro run `wsl --install --no-distribution` to make sure all the required components are there. `wsl --help` will show more information.

Hi, 

Thanks, it worked :)

**Comment by s1nyx** [comment]
> Thank you @s1nyx. I don't see any WSL activity in the log file you shared. Could you collect logs while you reproduce the problem ?
> 
> Also indeed if this is a store issue, `--web-download` is likely to solve the issue, could you try that ?

Hi,


Using web-download worked. However I would like to understand why it didn't from the store. Is it because of Zscaler?

**Comment by XtianKav** [comment]
Merci beaucoup pour cette contribution, cette solution à fonctionner après une journée de recherche

**Comment by mateusz18598** [comment]
I had a very similar problem, after enabling SR-IOV in the bios I managed to install the distro on wsl2
