### ISSUE TITLE
apt dist-upgrade is too slow - kali linux - WSL 2

### ISSUE THREAD

**Issue by VJPranay** [microsoft/WSL#11621]
### Windows Version

Version 10.0.22631.3593

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

kali linux - 2024.2

### Other Software

upon entering apt-get upgrade , terminal just says -- Nothing to restart, its been 2 hours. it doesnt do anything.

Fetched 48.0 MB in 8s (6,172 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 30058 files and directories currently installed.)
Preparing to unpack .../base-files_1%3a2024.2.0_amd64.deb ...
Unpacking base-files (1:2024.2.0) over (1:2024.1.0) ...
dpkg: warning: unable to delete old directory '/lib/systemd/system-preset': Directory not empty
Setting up base-files (1:2024.2.0) ...
(Reading database ... 30058 files and directories currently installed.)
Preparing to unpack .../libc-l10n_2.38-10_all.deb ...
Unpacking libc-l10n (2.38-10) over (2.37-12) ...
Preparing to unpack .../locales-all_2.38-10_amd64.deb ...
Unpacking locales-all (2.38-10) over (2.37-12) ...
Preparing to unpack .../libc6_2.38-10_amd64.deb ...
Checking for services that may need to be restarted...
Checking init scripts...
Unpacking libc6:amd64 (2.38-10) over (2.37-12) ...
Setting up libc6:amd64 (2.38-10) ...
Checking for services that may need to be restarted...
Checking init scripts...
Nothing to restart.

### Repro Steps

apt-get upgrade

### Expected Behavior

![sdfsdf](https://github.com/microsoft/WSL/assets/9312169/16c684c4-f432-4508-a350-10c61d7f871e)

### Actual Behavior

it should install within few mins / sec but its taking hours.

**Comment by eu4you** [comment]
I have same problem. No works for 7 hours.
I attach the log file from my pc.

[WslLogs-2024-05-29_05-56-42.zip](https://github.com/microsoft/WSL/files/15475979/WslLogs-2024-05-29_05-56-42.zip)

**Comment by eu4you** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs


I have same problem. No works for 7 hours.
I attach the log file from my pc.

[WslLogs-2024-05-29_05-56-42.zip](https://github.com/microsoft/WSL/files/15475979/WslLogs-2024-05-29_05-56-42.zip)

**Comment by Diefunction** [comment]
i think this will solve your issue https://github.com/microsoft/WSL/issues/11631#issuecomment-2143540987
