### ISSUE TITLE
HTTPS doesn't work under mirrored network mode.

### ISSUE THREAD

**Issue by xky0007** [microsoft/WSL#11629]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 24.04

### Other Software

Docker Desktop v4.30.0

### Repro Steps

1. Set WSL to use mirrored network mode
2. Deploy portainer `docker run -d -p 8000:8000 -p 9443:9443 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest`
3. Access `localhost:9000` and `https://localhost:9443`

### Expected Behavior

Both http and https portainer server should work.

### Actual Behavior

https servser shows error while http server page can be reached.
![image](https://github.com/microsoft/WSL/assets/30423949/29f4e360-4d44-4065-be68-6350430ab22a)

**Comment by xky0007** [comment]
[WslLogs-2024-05-29_10-08-33.zip](https://github.com/microsoft/WSL/files/15477864/WslLogs-2024-05-29_10-08-33.zip)

**Comment by pmartincic** [comment]
I don't see any logs inside that zip? Did you let log collection run while wsl and the web service start up?
