### ISSUE TITLE
Docker service running in wsl accessible on LAN but not host

### ISSUE THREAD

**Issue by dagarwal82** [microsoft/WSL#11620]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

1) Postgres docker running in wsl with 5432 port
2) Wsl running in mirrored mode
3) Both wsl and host (windows) has ip 192.168.0.131
4) I can connect to 192.168.0.131:5432 from other machines in LAN (That is great !) 
5) But, can not connect to 192.168.0.131:5432 (or 127.0.0.1:5432 or localhost:5432) from host . None of the other wsl IP addresses are pingable from Host either (172.*.*.*).

This happens for all the services on wsl. How do I access these from host?
Tried disabling Hyper-V firewall but in vain.
Tried adding 5432 in both Inbound/Outbound rule in Hyper-V firewall but in vain.

None of the occupied ports in wsl shows up in netstat -an | find "<port>"  in windows host.

### Expected Behavior

I should be able to access wsl services from host

### Actual Behavior

Unable to connect to port from Windows Host

**Comment by johanhammar** [comment]
I'm also seeing this. 

A simple test is to use Netcat

Run`nc -l 4444` in WSL2 and try to access it from Windows. For me it just hangs

I've also tried to Allow inbound connections following the instructions on https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking with no success

**Comment by rcastagno** [comment]
I'm having a very similar issue.

Case 1

- Docker compose up postgres
- check connection: OK
- launch `wsl`
- check connection: KO
- exit `wsl`
- check connection after a few seconds: OK

Case 2

- Docker compose up postgres
- check connection: OK
- from windows prompt launch `bash script.sh` (the bash script is in windows, but it's irrelevant
- check connection: KO
- stop the script
- check connection after a few seconds: OK
