### ISSUE TITLE
I Need help with audio in WSL, a way to get audio without using pulseaudio

### ISSUE THREAD

**Issue by Lilicogamer13** [microsoft/WSL#11638]
### Windows Version

Windows 11

### WSL Version

Recent Version

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 16.04

### Repro Steps

nothing

### Expected Behavior

audio

### Actual Behavior

nothing

### Diagnostic Logs

[Warning]: Only AMD Gpu is suported
[Error]: Audio Board not suported
[Error]: Gpu not detected

**Comment by Lilicogamer13** [comment]
If any way of get audio without using pulseaudio exist(for WSL), send as a comment PLS

**Comment by Lilicogamer13** [comment]
If any way of get audio without using pulseaudio exist(for WSL), send as a comment PLS

**Comment by Lilicogamer13** [comment]
↑ 
lol, github actions bot bugging

**Comment by OneBlue** [comment]
@Lilicogamer13: Can you provide more details ? How exactly do you want to configure audio, and why is pulseaudio not a good solution for your use case ?

**Comment by Lilicogamer13** [comment]
Pulseaudio is not good, by my bad system(not updateble system), i want to configure for my default audio in Windows to be used, sorry i not have more details

**Comment by OneBlue** [comment]
Closing since the issue doesn't have enough details to be actionable
