### ISSUE TITLE
upgrade support to wsl distros

### ISSUE THREAD

**Issue by felipefigueiredo1** [microsoft/WSL#11646]
i want upgrade my ubuntu 22.04 to 24.04, but after some searchs it's look like impossible. I know i can reinstall everything, but i dont wanna lost my files.

**Comment by craigloewen-msft** [comment]
Echoing what @tinlittle said, this is controlled in your actual Linux environment, and you solve this the same way you would on Linux proper. For Ubuntu you can run `sudo do-release-upgrade -d` to perform an upgrade.

**Comment by felipefigueiredo1** [comment]
Thanks.
