### ISSUE TITLE
Unregistered class Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG

### ISSUE THREAD

**Issue by JonasGz** [microsoft/WSL#11641]
### Windows Version

Microsoft Windows 10 (19045.4474)

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

Try installing wsl 
wsl --install

all attempts to type wsl on the command line give the same error

### Expected Behavior

wsl install

### Actual Behavior

Unregistered class Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG

### Diagnostic Logs

**Windows Features:**
WSL - Enabled
Virtual Machine Platform - Enabled
Virtualization BIOS - Enabled

**Comment by markmungaidrezz** [comment]
https://github.com/microsoft/WSL/issues/11892#issue-2453382301
how can i resolve my issue

**Comment by sureshjkb** [comment]
error code : Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG
i am unable to install. update wsl and geeting aforementioned error  .please adise for windows 11, fully updated on laptop
