### ISSUE TITLE
cannot get access to virtualbox VM with Host-Only adapter via WSL with 'mirrored' networkMode

### ISSUE THREAD

**Issue by rez23** [microsoft/WSL#11642]
### Windows Version

Microsoft Windows [Versione 10.0.22631.3593]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-microsoft-standard-WSL2

### Other Software

VirtualBox Versione 7.0.8 r156879

### Repro Steps

Attempt to ping a VirtualBox guest with a host-only network setup from a WSL2 instance with a mirrored network configuration to verify that it is unreachable.

### Expected Behavior

You can access the VBox guest machine using the host-only adapter IP address from WSL2 instances with ping or another connection utility.

### Actual Behavior

You cannot connect to a VBox guest machine using the host-only adapter IP address from WSL2 instances with ping or any other connection utility.

**Comment by petersaints** [comment]
I also notice this behavior. The VirtualBox Host Only Adapter is Mirrored (as eth2 in my case) and I am able to bring it up, give it an IP in the same 192.168.56.x range and than I'm able to connect to a VM using the correct IP.

However, if I'm on Windows I can just ping it using the VMs hostname (it resolves the IP by itself). With WSL2 in NAT Mode it also works well.

**Comment by CherryDT** [comment]
> The VirtualBox Host Only Adapter is Mirrored (as eth2 in my case) and I am able to bring it up, give it an IP in the same 192.168.56.x range and than I'm able to connect to a VM using the correct IP.

How? I tried the same but I always just get destination host unreachable or no response at all.

**Comment by CherryDT** [comment]
My solution:

[Create a network bridge](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-bridge) in Windows between the "vEthernet (Default Switch)" adapter and the VirtualBox Host-Only adapter.

As admin, run `netsh bridge show adapter`. Find the IDs for the two adapters. Then run `netsh bridge create <ID1> <ID2>`.

I had to run the command _twice_, first it would show an error on adding the second interface, then on the first, but at the end it would be OK.

As a last step, I had to assign the IP configuration to the bridge manually:

```powershell
Get-NetIPAddress -InterfaceAlias "Network Bridge" -AddressFamily IPv4 | `
  Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue

New-NetIPAddress `
  -InterfaceAlias "Network Bridge" `
  -IPAddress 192.168.56.1 `
  -PrefixLength 24
```

**Comment by rchavp** [comment]
> My solution:
> 
> [Create a network bridge](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-bridge) in Windows between the "vEthernet (Default Switch)" adapter and the VirtualBox Host-Only adapter.
> 
> As admin, run `netsh bridge show adapter`. Find the IDs for the two adapters. Then run `netsh bridge create <ID1> <ID2>`.

Wouldn't this defeat the purpose of a Host Only Network in the first place?

**Comment by CherryDT** [comment]
Depends on what the reason was to use one...

**Comment by rchavp** [comment]
I'm curious, what could be a reason to use a Host Only network if it will cease to be isolated from the outside once you bridge it?

**Comment by CherryDT** [comment]
In my case the "host-only" network is mainly a convenient private VirtualBox subnet with stable VM IPs, not a security boundary from every local virtual interface.

Bridging it to WSL/Hyper-V lets WSL reach the same lab VMs that Windows can reach, without exposing them to the physical LAN. It only defeats the purpose if your purpose was strict isolation from everything except the Windows host. If that is the requirement, then yes, bridging in WSL/Hyper-V would no longer match that model.

**Comment by rchavp** [comment]
I use Host-Only as a private network for all my VMs inside my Windows host. They all can talk to the host and they can all talk to each other, as they are all in the same subnet (usually 192.168.56.0/24). This way any VM trying to access another physical machine in the physical LAN at home will not be able to.

If I bridge the Host only subnet with the default Ethernet that will allow the VMs to reach the outside world through the bridge.

So your advice is a good workaround, and I mean it, it is good. But maybe people reading this should take a not about the isolation being broken in case they care about it.

But I get you now. Thanks for clarifying.

**Comment by CherryDT** [comment]
> If I bridge the Host only subnet with the default Ethernet that will allow the VMs to reach the outside world through the bridge.

No, I'm not bridging it to my real Ethernet interface. I bridge it to the "**v**Ethernet (Default Switch)" adapter from Hyper-V.

Also note that the "vEthernet (Default Switch)" adapter does not even have the TCP/IP service enabled. It acts as a Layer-2 switch.

So I get this:

WSL / Hyper-V side
   ↓ Ethernet frames
vEthernet (Default Switch)
   ↓ Windows bridge forwards frames
VirtualBox Host-Only Network
   ↓
My VM

---

By the way, I realized I can manually bring the interface (`eth0` in my case) up without the bridge and set the IP, and it will work for a while (<1 minute), and then Windows will automatically put it back down (see https://github.com/microsoft/wsl/issues/13960).

Having this bridge seems to somehow cure this behavior, I'm also not totally sure why.
