### ISSUE TITLE
An error occurred during make. (This is my first time, so please let me know if there are any issues.)

### ISSUE THREAD

**Issue by Slime0515** [microsoft/WSL#11663]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

git checkout linux-msft-wsl-5.15.146.1
git branch
make  menuconfig
apt install bc
make

### Expected Behavior

No errors occur

### Actual Behavior

make[2]: *** No rule to make target 'net/netfilter/xt_TCPMSS.o', needed by 'net/netfilter/built-in.a'.  Stop.
make[1]: *** [scripts/Makefile.build:552: net/netfilter] Error 2
make: *** [Makefile:1907: net] Error 2

**Comment by Slime0515** [comment]
This is the log.

[acl.txt](https://github.com/user-attachments/files/15623650/acl.txt)
[appxpackage.txt](https://github.com/user-attachments/files/15623653/appxpackage.txt)
[bcdedit.txt](https://github.com/user-attachments/files/15623655/bcdedit.txt)
[HKCU.txt](https://github.com/user-attachments/files/15623660/HKCU.txt)
[HKLM.txt](https://github.com/user-attachments/files/15623661/HKLM.txt)
[optional-components.txt](https://github.com/user-attachments/files/15623663/optional-components.txt)
[P9NP.txt](https://github.com/user-attachments/files/15623666/P9NP.txt)
[Winsock2.txt](https://github.com/user-attachments/files/15623669/Winsock2.txt)
[wpr.txt](https://github.com/user-attachments/files/15623673/wpr.txt)
[wslservice.txt](https://github.com/user-attachments/files/15623675/wslservice.txt)
[wslsupport-impl.txt](https://github.com/user-attachments/files/15623678/wslsupport-impl.txt)
[wslsupport-proxy.txt](https://github.com/user-attachments/files/15623679/wslsupport-proxy.txt)

**Comment by OneBlue** [comment]
@Slime0515: Did you make changes to the kernel config ? What's the full build output ?
