### ISSUE TITLE
Make the Windows command line more Unixy, passing .ini's and etc.

### ISSUE THREAD

**Issue by pinballelectronica** [microsoft/WSL#11662]
Not a problem so much as a better user experience:

I'd like to see configs get passed to the wsl.exe command line so we can choose unique startups including using custom kernels and etc.       eg wsl.exe -d blah -config customconfig.ini  - I'd also personally prefer it to use .ini or ideally .yaml or .json configs on the Windows side- I know it's really optics but it may drive more Unix people to wsl2... 

Alternatives-  You could hack a PowerShell script together which is what I do now (among other hacky things for mounting " bare" drives for ZFS in wsl2 and etc).  It's just so hacky and I really do want to use WSL2 as my "daily driver" so trying to true up things like that- WSL has really come along and I REALLY like it.   I'm sick of using Powershell scripts to wrap what I think is pretty basic stuff that should/could be native..(I'll still do it until then, of course)

Considered: if WSL.exe is open source, adding code to accept different configs.

Is there a WSL2 kernel hacking community somewhere?
Thanks

**Comment by RandomDSdevel** [comment]
> custom kernels 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If custom kernels stopped being only global across all WSL 2 distributions on your system (set in '`%USERPROFILE%\.wslcomfig`' on the Windows side) and became supported per-distribution (set in '`/etc/wsl.conf`' in each distribution individually) any time soon, then I'd honestly be in genuine shock and picking my jaw up off the floor.  It'd certainly be a very pleasant surprise, though.  

> I'd also personally prefer it to use .ini or ideally .yaml or .json configs on the Windows side- I know it's really optics but it may drive more Unix people to wsl2...

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There aren't any issues with the current format of '`.wslcomfig`' and '`/etc/wsl.conf`,' at least not for me personally.  It's the same format that Git uses for per-repository '`.git/config`' files and user-local and system-wide configuration, more or less, though perhaps with less or no support for any indentation of settings below their parent sections.  This is an '`.ini`' file variant already; [Wikipedia's article on '`.ini`' files](https://en.wikipedia.org/wiki/INI_file) lists GitHub configuration files one of [its examples](https://en.wikipedia.org/wiki/INI_file#Prevalence).  '`.ini`'-style files don't necessarily have to have the '`.ini`' file extension&thinsp;—&thinsp;or even any at all, really.
