### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102 Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

### ISSUE THREAD

**Issue by jkupchanko** [microsoft/WSL#11674]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

2

### Repro Steps

I have been through so many videos trying to fix this - I have downloaded Ubuntu and I get an error saying "WslRegisterDistribution failed with error: 0x80370102 - Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS." - I got into the BIOS from "Turn Windows features on or off" and turn on the new subset for Linux on Windows Home "Virtual Machine Platform". Of course, this makes me reset the computer and I check again and nothing. ..

I see one of the possible issues is of a possible CPU issue but I have a very nice computer: "LYTE Venom X PC - Ryzen 7 5700x | RTX 4070TI | 16GB DDR4 | B550 | NVME + HDD"

Also, I have turned on the hypervisor using bcdedit /set hypervisorlaunchtype auto or BCDEDIT /Set {current} hypervisorlaunchtype auto

Also, I used the "Enable virtualization on Windows 11 PC's" and I accessed the BIOS and resetted it, nothing has help.
( https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1 )

I am not sure what to do... please help!

### Expected Behavior

![issue-help](https://github.com/microsoft/WSL/assets/121833313/4e4c9565-abf3-4d04-88b7-8ce519cacf6b)

![image](https://github.com/microsoft/WSL/assets/121833313/5d0f8f82-f76c-4d72-84d3-36f39ab03024)

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...

```[tasklist]
### Tasks
```

**Comment by jkupchanko** [comment]
/question, how do I remove the "WslRegisterDistribution failed with error: 0x80370102 - Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS" to use Ubuntu.

**Comment by jkupchanko** [comment]
Sorry, that was on accident - this has NOT been resolved

**Comment by jkupchanko** [comment]
[WslLogs-2024-06-11_16-45-12.zip](https://github.com/user-attachments/files/15795810/WslLogs-2024-06-11_16-45-12.zip)


here is the logging information

**Comment by jkupchanko** [comment]
Hello,
Please see my attached WslLogs file - please help me!
    On Tuesday, June 11, 2024 at 04:55:00 PM PDT, github-actions[bot] ***@***.***> wrote:  
 
 


The log file doesn't contain any WSL traces. Please make sure that you reproduced the issue while the log collection was running.
 Diagnostic information Appx package is not installed
Found no WSL traces in the logs

**Comment by OneBlue** [comment]
@jkupchanko: You need to reproduce the issue while the log collection is running so it can capture the error.

/logs

**Comment by jkupchanko** [comment]
I showed where I am having the issue
[WslLogs-2024-06-11_17-20-55.zip](https://github.com/user-attachments/files/15796183/WslLogs-2024-06-11_17-20-55.zip)

**Comment by jkupchanko** [comment]
I ran the code and I don't see anything tripping the issue - I am not sure what you want me to do.

**Comment by jkupchanko** [comment]
@OneBlue Any updates?

**Comment by jkupchanko** [comment]
Figured it out, I needed to go into my BIOS and Enable Virtualization on my AMD (Look in the CPU settings).
 
 https://www.youtube.com/watch?v=HkI4ibCdlxg

**Comment by SebastianLasch** [comment]
**FIXED!** Same symptoms on a Lenovo ThinkBook 16 G7 (Ryzen 7735HS): BIOS showed AMD-V Enabled but firmware never passed it through. **Fixed by loading BIOS defaults + explicitly toggling AMD-V off/on to force an NVRAM rewrite.** After hours of troubleshooting, this worked for me and I wanted to share. Full writeup: https://gist.github.com/SebastianLasch/6ecc3a1ef4ffa5ec38f01b22cd7239aa
