### ISSUE TITLE
wsl is freeze on installing packages by npm install

### ISSUE THREAD

**Issue by haw0k** [microsoft/WSL#11670]
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04.3 LTS

### Other Software

NodeJS v20.14.0

### Repro Steps

1. Open `Ubuntu 22.04.3 LTS` terminal
2. `cd some_project_with_package.json`
3. `npm install`

### Expected Behavior

The terminal continuously displays the package installation process.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

### Actual Behavior

WSL terminal freezes.
The npm process won't exit by the Ctrl+C command.
```
$ rm -rf node_modules/
$ npm i
⠏^C^C
```

The npm process exists.
```
$ ps axl | grep npm
0  1000     658     375  20   0 3315272 2128964 x64_sy Sl+ pts/0    0:56 npm i
```

```[tasklist]
### Tasks
```

**Comment by haw0k** [comment]
[WslLogs-2024-06-08_13-08-35.zip](https://github.com/user-attachments/files/15747589/WslLogs-2024-06-08_13-08-35.zip)

**Comment by OneBlue** [comment]
Thank you @haw0k . Can you share an strace of the process that freezes ? (strace -f <command>)

**Comment by KyryloSWAN** [comment]
1. ```$ npm cache clean --force```
2. ```$ rm -rf node_modules/ package-lock.json```
3. ```$ npm i```
4. ```ps ax | grep npm
  56172 pts/0    Sl+    0:00 npm i```
5. ```$ strace -f -p 56172 -o strace.log```

Best environment for reproducing: The nextj
[strace.zip](https://github.com/user-attachments/files/15817053/strace.zip)
s empty project created by `npx create-next-app@latest`

**Comment by h3rmanj** [comment]
Did any of you manage to fix this? I'm getting this now, and it only happens if there is no `package-lock.json` already, so it freezes for all new projects.

**Comment by KyryloSWAN** [comment]
Newest versions, same buggy behavior.
```
> wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4317
```

**Comment by h3rmanj** [comment]
Today it worked again. Updated to latest wsl by manually downloading from releases, and installed node and npm with volta. No idea what fixed it, seems a little random.

```
> node --version
v22.11.0

> npm --version
10.9.0

> wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4317
```
