### ISSUE TITLE
Failed conversion of Ubuntu from version 1 to version 2

### ISSUE THREAD

**Issue by estebanzimanyi** [microsoft/WSL#11687]
### Windows Version

Microsoft Windows [Version 10.0.19045.4529]

### WSL Version

 2.1.5.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 20.04

### Repro Steps

Following 
https://docs.docker.com/desktop/wsl/
I ran
```
wsl.exe --set-version Ubuntu 2
```
and received the following message
```
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
```
I waited for 24 hours and then kill the process with Ctrl-C

### Expected Behavior

After relaunching the application I expected that the process restarted

### Actual Behavior

```
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion in progress, this may take a few minutes.
The supplied install location is already in use.
Error code: Wsl/Service/0x80070050
```

**Comment by estebanzimanyi** [comment]
[WslLogs-2024-06-12_19-51-30.zip](https://github.com/user-attachments/files/15808969/WslLogs-2024-06-12_19-51-30.zip)

**Comment by estebanzimanyi** [comment]
Finally ended up droping the Ubuntu version 1 and creating a new Ubuntu version 2

**Comment by WuShichao** [comment]
Same issue...
