### ISSUE TITLE
 systemd Not Booting Up in WSL 2 Despite Configuration in wsl.conf

### ISSUE THREAD

**Issue by owlcode3** [microsoft/WSL#11681]
### Windows Version

Microsoft Windows [Version 10.0.21996.1]

### WSL Version

WSL 2

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.102.1

### Distro Version

Ubuntu-22.04

### 1. Install WSL and  Ubuntu 22.04:

   - Followed the official [WSL installation guide](https://docs.microsoft.com/en-us/windows/wsl/install) to install WSL 2 and the Ubuntu 22.04 distribution.

### 2. Configure wsl.conf:

- Edited the /etc/wsl.conf file to include the following configuration:

`[boot]
systemd=true`

### 3. Restart WSL:

- Executed the following command in PowerShell as an administrator to shut down WSL:

`wsl --shutdown`

### 4. Start WSL and Verify systemd:

- Opened the Ubuntu terminal and ran:

 `ps -p 1 -o comm=`

### Expected Behavior

The command should output systemd, indicating that systemd is running as the init system.

### Actual Behavior

The output is not systemd, and running systemctl status returns the following error:

`System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down`

```[tasklist]
### Tasks
```

**Comment by owlcode3** [comment]
I can't get the log

**Comment by OneBlue** [comment]
Closing since this issue doesn't have logs

**Comment by owlcode3** [comment]
Here I've collected the logs as requested.
[WslLogs-2024-06-12_11-38-46.zip](https://github.com/user-attachments/files/15803393/WslLogs-2024-06-12_11-38-46.zip)

**Comment by owlcode3** [comment]
I've edited my last comment to include the new log file as requested. Please let me know if there are any further details needed.

**Comment by owlcode3** [comment]
Can this issue be open? I’ve added the log

**Comment by owlcode3** [comment]
@OneBlue please can you reopen the issue as I've provided the log as requested

**Comment by toshydev** [comment]
If you open the `wsl.conf` with `vim`, what is the format showing in the bottom left corner? 
If it's showing `[dos]` you need to convert it to `UNIX` format by using a tool like `dos2unix` or by deleting and rewriting it inside the wsl with `vim` or `nano`.

**Comment by m2f2liberoit** [comment]
sed -i "s/\r//g" /etc/wsl.conf
