### ISSUE TITLE
wsl2 更新失败(退出代码: 1603)。 Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE

### ISSUE THREAD

**Issue by wangjiangmin** [microsoft/WSL#11695]
### Windows Version

22631.3737

### WSL Version

2.2.4

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. install Microsoft.WSL_2.2.4.0_x64_ARM64.msixbundle
2. start wsl

### Expected Behavior

enter ubuntu

### Actual Behavior

WSL 正在完成升级...
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
Could not write value  to key \SOFTWARE\Classes\Directory\shell\WSL.   Verify that you have sufficient access to that key, or contact your support personnel.
更新失败(退出代码: 1603)。
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE

**Comment by NaroZeol** [comment]
https://github.com/microsoft/WSL/issues/11697#issuecomment-2168104220

**Comment by TrisuyaN** [comment]
Same problem. Maybe Windows update KB5039212 damaged it.

Everytime I execute wsl commands in PS, it shows
```
WSL 正在完成升级...
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
Could not write value  to key \SOFTWARE\Classes\Directory\shell\WSL.   Verify that you have sufficient access to that key, or contact your support personnel.
更新失败(退出代码: 1603)。
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE
```

and when I enter a wsl distribution, it shows
```
WSL 正在完成升级...
Could not write value  to key \SOFTWARE\Classes\Directory\shell\WSL.   Verify that you have sufficient access to that key, or contact your support personnel.
更新失败(退出代码: 1603)。
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE
```

**Comment by TrisuyaN** [comment]
> [#11697 (comment)](https://github.com/microsoft/WSL/issues/11697#issuecomment-2168104220)

It works, thanks a lot!

**Comment by jark006** [comment]
> [#11697 (comment)](https://github.com/microsoft/WSL/issues/11697#issuecomment-2168104220)

有效，谢谢

**Comment by wangjiangmin** [comment]
> [#11697 (comment)](https://github.com/microsoft/WSL/issues/11697#issuecomment-2168104220)

It works, thanks !
