### ISSUE TITLE
Cannot uninstall WSL any more

### ISSUE THREAD

**Issue by tasty0tomato** [microsoft/WSL#11699]
### Windows Version

10.0.19045.4529

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

I have disabled the Windows Subsystem for Linux in Turn Windows features on or off. 

### Expected Behavior

It should be deleted

### Actual Behavior

But WSL is not uninstalled, and I can still find it in C:\Windows\System32

**Comment by dcasota** [comment]
@tasty0tomato see https://github.com/microsoft/WSL/issues/11675#issuecomment-2172538707. It may be an issue with KB5039212. Try to uninstall it `wusa /uninstall /kb:5039212`. The files still will be present in c:\windows\system32, but `wsl -v` shows up the old version, and it should be possible to reinstall wsl.

**Comment by benhillis** [comment]
We added 'wsl.exe --uninstall` to uninstall the store version of WSL.

**Comment by dcasota** [comment]
@benhillis fyi`wsl —uninstall` does not work in some constellations as expected. One constellation is wsl version 2.1.5/2.2.4 with kb5039212. After wsl deinstallation the files still exist in system32 directory.
