### ISSUE TITLE
wsl --update错误。查看了https://github.com/microsoft/WSL/discussions/8383， 但是我无法更改系统设置

### ISSUE THREAD

**Issue by cpcgskill** [microsoft/WSL#11709]
### Windows Version

Microsoft Windows [版本 10.0.19045.2251]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu-20.04

### Repro Steps

PS C:\Users\Admin> wsl --update

### Expected Behavior

wsl 更新

### Actual Behavior

正在检查更新...
适用于 Linux 的 Windows 子系统内核可以使用“wsl --update”手动更新，但由于你的系统设置，无法进行自动更新。
 若要接收自动内核更新，请启用 Windows 更新设置:“在更新 Windows 时接收其他 Microsoft 产品的更新”。
 有关详细信息，请访问https://aka.ms/wsl2kernel。

**Comment by cpcgskill** [comment]
[WslLogs-2024-06-19_15-26-53.zip](https://github.com/user-attachments/files/15897029/WslLogs-2024-06-19_15-26-53.zip)

**Comment by OneBlue** [comment]
Thank you @cpcgskill. Does manually installing the [MSI package](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) work ?
