### ISSUE TITLE
Register WSL without importing

### ISSUE THREAD

**Issue by ronen1n** [microsoft/WSL#11708]
Current state for if you want to back up or restore WSL os

- Export your current Kali WSL distribution to a backup file:
`wsl --export kali-linux D:\backup\kali-linux.tar`

- Restore the tar file
`wsl --import kali-linux "D:\Virtual Machines\kali-linux" D:\\backup\kali-linux.tar --version 2`

- or restore vhd file (extracted from tar or from old pc)
`wsl --import kali-linux "D:\Virtual Machines\wsl-kali" "D:\Virtual Machines\wsl-kali-linux\ext4.vhdx" --version 2 --vhd`

Explanation:
`wsl --import kali-linux "<new empty folder>" "<old vhd location that will be copied to the new location>\ext4.vhdx" --version 2 --vhd`

Any better way to restore the vhdx file without it coping it again to new folder like unused `--register`?

**Comment by ronen1n** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs

/feature

**Comment by shigenobuokamoto** [comment]
How about this option?
```
--import-in-place
```

**Comment by ronen1n** [comment]
> How about this option?
> 
> ```
> --import-in-place
> ```

Sounds good
I just don't want to copy 70GB any time I import the WSL after format
