### ISSUE TITLE
SSH connection hangs and stops responding after some time, effectively freezing WSL

### ISSUE THREAD

**Issue by otaviosso** [microsoft/WSL#11710]
### Windows Version

Microsoft Windows [Version 10.0.19045.4412]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1

### Distro Version

Ubuntu 22.04

### Other Software

OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022

### Repro Steps

Default configuration and setup is being used. 

1. Use ssh to connect to a server
2. Successfully log into the server
3. Run a command on said server
4. Let WSL run on the background for some time
5. Try to run a command 

### Expected Behavior

It was expected to run the command successfully.

### Actual Behavior

You can neither type nor run anything, you have to close the window to interrupt WSL.

**Comment by otaviosso** [comment]
[WslLogs-2024-06-19_09-15-31.zip](https://github.com/user-attachments/files/15900830/WslLogs-2024-06-19_09-15-31.zip)

**Comment by otaviosso** [comment]
... And also happens on PuTTY. Seems like SSH is just broken on Windows 10.

**Comment by OneBlue** [comment]
This looks like either a networking issue, or an issue with the machine you're connecting to. Unfortunately this isn't something that can be solved from the WSL side.
