### ISSUE TITLE
Any one uses anaconda (in ubuntu) with phonopy?

### ISSUE THREAD

**Issue by YerongLi** [Microsoft/WSL#1172]
I tried to build supercell with phonopy but got a error like this:
![image](https://cloud.githubusercontent.com/assets/13112023/19182923/bce75bf2-8c2a-11e6-9454-e7b2f9c7afb4.png)

I guess it is an error caused by python-dev, has anyone has experience on this?

**Comment by fpqc** [comment]
Rerun the command with an strace.  Looks like an unimplemented syscall.

**Comment by benhillis** [comment]
Not enough info here to reproduce. Please provide repro instructions and repopen.
