### ISSUE TITLE
WSL 2 kernel file is not found - Installing: Windows Subsystem for Linux - Catastrophic failure

### ISSUE THREAD

**Issue by jbyrnescu** [microsoft/WSL#11727]
### Windows Version

Microsoft Windows [Version 10.0.19045.4529]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

not running a kernel

### Distro Version

No distro - wsl not running

### Other Software

This problem started with installing podman.

### Repro Steps

GAINWELL+jbyrne@GWT-94QB9K3 MINGW64 ~/git
$ podman machine inspect
[]
Error: podman-machine-default: VM does not exist

GAINWELL+jbyrne@GWT-94QB9K3 MINGW64 ~/git
$ podman machine init
Error: vm "podman-machine-default" already exists on hypervisor

GAINWELL+jbyrne@GWT-94QB9K3 MINGW64 ~/git
$ wsl --list --running
There are no running distributions.

GAINWELL+jbyrne@GWT-94QB9K3 MINGW64 ~/git
$ wsl --status
Default Distribution: podman-machine-default
Default Version: 2

WSL automatic updates are on.

The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl --update'.

GAINWELL+jbyrne@GWT-94QB9K3 MINGW64 ~/git
$ wsl --update
Installing: Windows Subsystem for Linux
Catastrophic failure

### Expected Behavior

wsl --update should install wsl because it's having problems.  I've turned on and off the software in the control panel and rebooted with these settings however this has not seemed to help.

### Actual Behavior

See error output of commands above.

**Comment by BuzyOwl** [comment]
I am having the same issue. Tried so many things the only thing remaining is reset
