### ISSUE TITLE
Terminal text goes invisible after running the stopping docker-compose in foreground

### ISSUE THREAD

**Issue by Andrew-InTheBox** [microsoft/WSL#11726]
### Windows Version

Microsoft Windows [Version 10.0.22631.3737]

### WSL Version

5.15.153.1-2

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1

### Distro Version

Ubuntu 22.04

### Other Software

Docker desktop for windows

### Repro Steps

Run docker-compose up (not in the background).  Exit docker by control-c.  Note if terminal text becomes invisible.

### Expected Behavior

Terminal should revert to normal behavior when docker closes.  

### Actual Behavior

Terminal text is invisible after docker stops, requires re-starting a new wsl2 terminal session.

**Comment by Andrew-InTheBox** [comment]
[WslLogs-2024-06-25_12-04-27.zip](https://github.com/user-attachments/files/15975027/WslLogs-2024-06-25_12-04-27.zip)

**Comment by zdwolfe** [comment]
I also have this issue. Has anyone found a workaround?

**Comment by OneBlue** [comment]
@Andrew-InTheBox: Could you share a video of a repro ? I'm not sure I'm following what you mean by 'invisible'
