### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80041002 Error: 0x80041002 (null)

### ISSUE THREAD

**Issue by jeyosman1** [microsoft/WSL#11744]
### Windows Version

Microsoft Windows [Version 10.0.22631.3737]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Kali Linux 1.24.2.0 (rolling)

### Repro Steps

1. Run command "wsl -install" in terminal

### Expected Behavior

An installation of WSL of either the default distro Ubuntu or Kali linux.

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/9302226/e0969fe0-35c1-4893-9af1-4e984bcfa117)
It shows this error. 
![image](https://github.com/microsoft/WSL/assets/9302226/5461f5b4-57fe-4659-8ebd-7fc93ea2d08d)
When I tried to run using microsoft store, it said installing and then I got this error.

I ran sfc /scannow but it shows that there were no problems. Virtualisation is enabled in task manager.

**Comment by jeyosman1** [comment]
[WslLogs-2024-07-03_15-04-51.zip](https://github.com/user-attachments/files/16089633/WslLogs-2024-07-03_15-04-51.zip)

**Comment by jeyosman1** [comment]
How do I install it then?

**Comment by OneBlue** [comment]
The easiest way would be to install the latest [MSI package](https://github.com/microsoft/WSL/releases/tag/2.2.4)

**Comment by Aqirito** [comment]
> The easiest way would be to install the latest [MSI package](https://github.com/microsoft/WSL/releases/tag/2.2.4)

Installing using this method works for me Thanks 👏
