### ISSUE TITLE
localhostForwarding = false has no effect

### ISSUE THREAD

**Issue by marco20240618** [microsoft/WSL#11740]
### Windows Version

Microsoft Windows [Version 10.0.22621.3810]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04.3 LTS

### Repro Steps

1. initially, the content of /etc/wsl.conf is
```
[boot]
systemd=true

[automount]
enabled = false

[interop]
enabled = false
appendWindowsPath = false
```

2.  ss -tulpn
```
Netid         State          Recv-Q         Send-Q                  Local Address:Port                  Peer Address:Port        Process
tcp           LISTEN         0              128                           0.0.0.0:33334                      0.0.0.0:*            users:(("sshd",pid=145,fd=3))
```

3. on windows
NETSTAT.EXE -ano | findstr.exe 33334
 ```
 TCP    127.0.0.1:33334        0.0.0.0:0              LISTENING       11532
 TCP    [::1]:33334            [::]:0                 LISTENING       11532
```

4. change the content of   /etc/wsl.conf to 
```
[boot]
systemd=true

[automount]
enabled = false

[interop]
enabled = false
appendWindowsPath = false

[wsl2]
localhostForwarding = false
```

5.  on windows
wsl --shutdown
wsl -d Ubuntu-22.04 --cd ~

6. on windows 
NETSTAT.EXE -ano | findstr.exe 33334
  ```
TCP    127.0.0.1:33334        0.0.0.0:0              LISTENING       11532
TCP    [::1]:33334            [::]:0                 LISTENING       11532
```

### Expected Behavior

After changing to localhostForwarding = false, there should be no localhost port openning on windows.

### Actual Behavior

But the localhost port is still listensing on windows.

The reason I want to disable the localhostForwarding thing is that it only listens on the localhost port, that is useless for me. I want it listens on all interfaces.

### Diagnostic Logs

[wsl.log](https://github.com/user-attachments/files/16078678/wsl.log)

**Comment by marco20240618** [comment]
[WslLogs-2024-07-03_15-50-01.zip](https://github.com/user-attachments/files/16078959/WslLogs-2024-07-03_15-50-01.zip)

**Comment by pmartincic** [comment]
I'm pretty sure you're editing the wrong config file. look at `.wslconfig` on the host file system.

https://learn.microsoft.com/en-us/windows/wsl/wsl-config
