### ISSUE TITLE
Where are cmd.exe/bash.exe properties saved within the registry?

### ISSUE THREAD

**Issue by gegenschall** [Microsoft/WSL#1175]
This is probably not the right place to ask this question but I couldn't find any information about it by googling and really wouldn't know where else to ask.

I recently updated to the latest Fast Ring Build from the Annivesary Build. I noticed that my console settings had been reset. So I redownloaded the registry settings for the solarized color scheme and applied them which didn't work as expected (colors did change but in a really weird way (dark blue on black, just one color, etc).

Before and with the Annivesary Build console settings were saved within HKCU\Console{Path to lnk or exe}. These settings don't seem to have any real impact now (Settings changed within any console are not reflected within this hive). Can someone explain what happened here or point me to any documentation on this or the correct registry setting where console preferences are now stored? Also, why do color schemes not work anymore?

**Comment by fpqc** [comment]
Iirc you have to set it in the properties window when you right click on the program...

**Comment by gegenschall** [comment]
Yep. Sure. You can do that, but not for the color scheme. That you have to apply via the registry, hence my question.

**Comment by singhkays** [comment]
+1 on this!! For now I"m having to set the colors manually. Here's an example

![image](https://cloud.githubusercontent.com/assets/6164178/19258379/39e18fca-8f2c-11e6-8e97-434e48d23625.png)

**Comment by detlefm** [comment]
Same issue for me - nobody has an answer?

**Comment by fpqc** [comment]
hkcu\console iirc

**Comment by detlefm** [comment]
Mmh, it seems a little more tricky.
1. I run bash.exe from the generated shortcut and changed the background color to dark blue. It remembers this decision but the registry tree of "khu\console" didn't change.
2. I tried the same with a shortcut I had created to cmd.exe on the start menu and it was the same. Even after restart the background was dark blue but nothing was changed at the console tree.
And a run of cmd.exe from Win+R offers the default black color as background.
So there must be a place (maybe in the registry) where the different colors are saved.
Maybe there are additional trees in the registry for every shortcut.

**Comment by fpqc** [comment]
It's stored as part of the shortcut.

**Comment by detlefm** [comment]
Thanks to the linux subsystem I have made some investigations with hd and diff  And it seems the things are stored inside the lnk files. The Properties window of the lnk files is showing additional tabs for color and so on. I have never seen an API for advancing lnk files. 
It looks for me like a backdoor for Microsoft products. I don't understand why they not play with open cards and give such an information to all their developers. And why is it in binary format and not something like XML, Json, ...
And the summary for me is: There is no solution. The defaults for all consoles  (hku\console are overwritten from the shortcuts properties.

**Comment by fpqc** [comment]
@detlefm Create new shortcuts from the exes directly?  Does that still overwrite the settings?

**Comment by detlefm** [comment]
I have tried it  just now. If you create 2 shortcuts (to desktop) from bash.exe (windows32) you can set different colors to each of them. 
Thanks for the link to the documentation. I will look around if there is an API to change the colors.
If there is one it might be possible to convert mintty themes into shortcut themes.
It isn't bad to have different colors for the same console program like cmd, bash, vi.

**Comment by fpqc** [comment]
yes, but I'm asking if you create a shortcut without setting the colors, does it use the registry default?

**Comment by detlefm** [comment]
yes, it seems the entries for colors are empty and the standard colors, font, windows size will be shown.

**Comment by detlefm** [comment]
There are at least 3 programs depending on the registry console branch. 
A 32-bit cmd.exe, a 64-bit cmd.exe and bash.exe.
When calling cmd or bash with Win+R the 32-bit version is used.
The entries in the console branch are the default values. 
When a shortcut is created this defaul values are copied into the link file.
After that the entries are not more used from this shortcut. Every changes to colors, font are stored inside the lnk file.
When you are calling cmd.exe (or bash.exe) from Win+R, direct or from within a batch file and make changes to the properties these properties are stored in a separate registry branch like this:

```
[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"FontFamily"=dword:00000036
"FontWeight"=dword:00000190
"FaceName"="Lucida Console"
"ScreenColors"=dword:00000017
```

So changing the initial value of cmd/bash can be done by changing values at khu\console. 
Changes to Win+R / batch file cmd.exe can be made by changing the values of  the separate brach as described above. Both changes can be made directly with regedit or copying a branch from a reg file.

For changes inside the lnk files I hadn't found anything helpful in the meantime.

**Comment by detlefm** [comment]
Ok - there is one way (a little bit like round tthe corner) which can work.

1. Save the hkui\console branch
2. set the new wanted values to the "default" branch
3. create a new shortcut
4. restore the hku\console branch
5. copy the new created shortcut over the old one.
and maybe 1 a) read out the values from the existing shortcut and merging the properties 

But dealing in this way with the heart of the windows system - the registry?

**Comment by bitcrazed** [comment]
Sorry @all - only just noticed this issue. While this was filed a while ago, we posted some articles and made some changes when we shipped Fall Creators Update that you may find useful:

1. [Understanding Windows Console Host Settings](https://blogs.msdn.microsoft.com/commandline/2017/06/20/understanding-windows-console-host-settings/)
1. [Updating the Windows Console Colors](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/)
1. [Introducing the Windows Console Colortool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/)

HOWEVER, note that these color settings and tools only modify the Console's palette colors and are usually overridden by Linux tools which define their colors using RGB VT colors.

HTH.
