### ISSUE TITLE
Docker wsl:Le fichier spécifié est introuvable.

### ISSUE THREAD

**Issue by Elit-Gaimix** [microsoft/WSL#11756]
### Windows Version

Microsoft Windows [version 10.0.22631.3810]

### WSL Version

can't see

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

don't know

### Distro Version

Don't know, i use it for docker

### Other Software

Docker desktop (Docker version 26.1.4, build 5650f9b)

### Repro Steps

Ouvrir le terminal cmd ou powershell (En administarteur ou non) et executer une commande wsl (wsl --install par exemple)

### Expected Behavior

A simple message that says either try to install it or that it is already installed

### Actual Behavior

It just returned to the terminal: "Le fichier spécifié est introuvable."

### Diagnostic Logs

I followed the Microsoft installation (https://learn.microsoft.com/fr-fr/windows/wsl/install-manual), checked the environment variables, checked that it existed in the system32 folder , uninstall restart reinstall and restart, check additional updates, check that virtualization was activated in the bios, install the wsl 2 kernel packages several times, check the Event Logs and Services, check in the list of functionality that wsl and virtualization and hyper-v was activated, perform an sfc /scannow and I think that's all

**Comment by Elit-Gaimix** [comment]
Here are the logs when I did different commands: wsl,wsl --install,wslconfig /l,wslconfig in the cmd terminal
[WslLogs-2024-07-07_23-03-54.zip](https://github.com/user-attachments/files/16120764/WslLogs-2024-07-07_23-03-54.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @Elit-Gaimix. This looks like an installation issue. Can you try to install the latest [MSI package](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) and see if that solves the issue ?

**Comment by Elit-Gaimix** [comment]
That's working thank you !
