### ISSUE TITLE
Fcitx 5 does not function normally

### ISSUE THREAD

**Issue by xuangeyouneihan** [microsoft/WSL#11752]
### Windows Version

10.0.22631.3810

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3 (Self-compiled from [microsoft/WSL2-Linux-Kernel](https://github.com/microsoft/WSL2-Linux-Kernel), and version 5.15.153.1 also has the same problem)

### Distro Version

Arch and Ubuntu 22.04

### Repro Steps

Just update all the packages to the latest versions using the package manager, and make sure `fcitx5` and `fcitx5-configtool` (or `fcitx-config-qt`) are installed, then run `fcitx5 --disable=wayland` and `fcitx5-configtool`

### Expected Behavior

Fcitx 5 functions normally, at least it should be configured by `fcitx5-configtool`

### Actual Behavior

"Cannot connect to Fcitx by DBus, is Fcitx running?" In addition, Fcitx 5 cannot be used in other apps like Firefox either
![image](https://github.com/microsoft/WSL/assets/50788434/8a9159fe-f152-41c1-99e8-f26fa1009436)

### Diagnostic Logs

Fcitx log, got in Arch with v5.15.153.1 kernel: [debug_log.txt](https://github.com/user-attachments/files/16111465/debug_log.txt)

**Comment by xuangeyouneihan** [comment]
[WslLogs-2024-07-05_23-37-17.zip](https://github.com/user-attachments/files/16111586/WslLogs-2024-07-05_23-37-17.zip)

**Comment by xuangeyouneihan** [comment]
Related to yuk7/ArchWSL#370

**Comment by OneBlue** [comment]
I don't have deep knowledge of what `fcitx5` is, but based on the error message it looks like it might need systemd support, which you can enable via: 
```
#/etc/wsl.conf

[boot]
systemd=true
```

If that doesn't solve the issue, this probably needs to be investigated on the fcitx5 side, to see what the exact problem is.

**Comment by xuangeyouneihan** [comment]
I've already enabled Systemd. `systemctl status` shows that Systemd is running. I'll submit an issue on the Fcitx 5 side
