### ISSUE TITLE
Custom kernel not being recognized.

### ISSUE THREAD

**Issue by anshium** [microsoft/WSL#11779]
### Windows Version

Microsoft Windows [Version 10.0.22631.3880]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Custom kernel located at C:\Sources\vmlinux
2. Modify .wslconfig (in C:\Users\Admin) to:
```
[wsl2]
kernel=C:\\Sources\\vmlinux
```
3. Open Powershell. 
4. `wsl --shutdown`
5. `wsl -d Ubuntu-20.04`
6. `uname -r` (in wsl)

The kernel is still the original `5.15.153.1-microsoft-standard-WSL2+`. This means that it did not pick up the custom kernel.

### Expected Behavior

I expected to see my own kernel to be listed after performing `uname -r`. 

### Actual Behavior

The actual behavior was the original kernel being listed.

**Comment by anshium** [comment]
[WslLogs-2024-07-14_20-22-15.zip](https://github.com/user-attachments/files/16227826/WslLogs-2024-07-14_20-22-15.zip)

**Comment by zcobol** [comment]
@anshium to load the new kernel a `wsl --shutdown` is required. You didn't specify this step, therefore sorry if you did restart the service already.

**Comment by 0xbadfca11** [comment]
``5.15.153.1-microsoft-standard-WSL2+`` is not original kernel.
Microsoft kernel version strings have not a `+`.

**Comment by craigloewen-msft** [comment]
@0xbadfca11  is correct! It looks like your custom kernel is being accurately loaded. You can change your kernel name to make it more obvious. 

@anshium  please confirm this is the case and I'll close this issue out. THanks for filing!

**Comment by anshium** [comment]
Thanks everyone for the insights. 

I was trying to setup a depth camera on wsl and tried to remake the kernel with after changing certain settings with the hope of it being detected. Since the name was similar and hoped that the new kernel is named as the file location, I thought it is the same as original. 

While the camera problem still exists, I think this issue is resolved.

Thanks again.
