### ISSUE TITLE
How to get the direct download link of a WSL image

### ISSUE THREAD

**Issue by D3vil0p3r** [microsoft/WSL#11778]
I would like to add a WSL image in [DistributionInfo.json](https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json) and I see several links like:
```json
            "Amd64PackageUrl": "https://wsldownload.azureedge.net/KaliLinux_1.13.1.0.AppxBundle",
            "Arm64PackageUrl": "https://wsldownload.azureedge.net/KaliLinux_1.13.1.0.AppxBundle",
```
but it is not clear to me how these download links can be retrieved. As test, I tried to use https://store.rg-adguard.net/ and insert the Kali Linux MS Store link and it returns me the link http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/878c6e65-59b1-46c5-81c2-91bafbb63097?P1=1720896697&P2=404&P3=2&P4=ITGMav5tPyOG1mwNmxxlE38GwmCdIpQDuEz66CITKIjVRa%2bCQkASMpssq7kgwqRBJqz1KxEuEg8NzvKCpxGayw%3d%3d instead of the one above on azureedge.net domain.

I would like to retrieve info of this WSL image: https://apps.microsoft.com/detail/9n1m7q4f1kqf

How can I get the one from wsldownload.azureedge.net?

**Comment by OneBlue** [comment]
@D3vil0p3r: If you want a download link for WSL itself, you can use [github releases](https://github.com/microsoft/WSL/releases) for that. For instance here's a direct download link for the latest amd64 package: https://github.com/microsoft/WSL/releases/download/2.3.17/wsl.2.3.17.0.x64.msi
