### ISSUE TITLE
Dotnet Core not working in WSL

### ISSUE THREAD

**Issue by amitdhanuka** [Microsoft/WSL#1178]
Dotnet is properly installed in WSL version 16.04.
But Dotnet core applications are not running in WSL. Compilation is Success, then it says Compilation Failed.

Same file is running in Windows.

![2](https://cloud.githubusercontent.com/assets/6891066/19215943/c9f8149e-8dc9-11e6-92bd-9a61f7f29eb1.JPG)

Windows 10 OS Build 14393.222

**Comment by fpqc** [comment]
Known issue.  The .Net Core team is working with the WSL team to get it working.

**Comment by therealkenc** [comment]
CONTRIBUTING.md.
