### ISSUE TITLE
WSL 正在完成升级... 系统无法打开指定的设备或文件。 更新失败(退出代码: 110)。 Error code: Wsl/CallMsi/Install/0x8007006e

### ISSUE THREAD

**Issue by 1095071913** [microsoft/WSL#11783]
### Windows Version

Microsoft Windows [版本 10.0.22000.1936]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

An error occurs after wsl -update is executed

WSL 正在完成升级...
系统无法打开指定的设备或文件。
更新失败(退出代码: 110)。
Error code: Wsl/CallMsi/Install/0x8007006e

### Expected Behavior

Can be used normally

### Actual Behavior

An error occurs after wsl -update is executed

WSL 正在完成升级...
系统无法打开指定的设备或文件。
更新失败(退出代码: 110)。
Error code: Wsl/CallMsi/Install/0x8007006e

### Diagnostic Logs

[WslLogs-2024-07-16_12-03-33.zip](https://github.com/user-attachments/files/16243076/WslLogs-2024-07-16_12-03-33.zip)

**Comment by 1095071913** [comment]
Attempts to manually install the latest msi also report that the system is unable to open the specified device or file

**Comment by Aster-the-Med-Stu** [comment]
Sorry to bump things up as this keeps this issue open. Mine got closed as I forgot about it..

**Comment by gamefunc** [comment]
> > Attempts to manually install the latest msi also report that the system is unable to open the specified device or file
> 
> [#11673 (comment)](https://github.com/microsoft/WSL/issues/11673#issuecomment-2205245485)
> 
> Can you confirm if my steps work at your install?
> 
> 您方便的话可以看下我在以前的 issue 下提到的方法管用吗？

这边也挂了, 刚起床开debian WSLRegisterDistribution Failed with Error: 0x8007019e;
然后尝试
wsl --update
            wsl --unregister debian
            wsl --install debian
还一样卸了重启;
之后就这个了
