### ISSUE TITLE
2.3.11 breaks USBIPD

### ISSUE THREAD

**Issue by ferrellsl** [microsoft/WSL#11795]
### Windows Version

Microsoft Windows [Version 10.0.22631.3880]

### WSL Version

Ubuntu 22.04 Version 2

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.4 LTS on Windows 11 x86_64

### Repro Steps

Run the following command:  usbipd attach --wsl --busid 2-3
My SDR dongle in on busid 2-3 and is shared.
Results in the following error:
usbipd: info: Using WSL distribution 'Ubuntu-22.04' to attach; the device will be available in all WSL 2 distributions.
usbipd: error: WSL kernel is not USBIP capable; update with 'wsl --update'.

### Expected Behavior

USB IP device successfully connects.

### Actual Behavior

Results in the following error:
usbipd: info: Using WSL distribution 'Ubuntu-22.04' to attach; the device will be available in all WSL 2 distributions.
usbipd: error: WSL kernel is not USBIP capable; update with 'wsl --update'.

```[tasklist]
### Tasks
```
[WslLogs-2024-07-17_23-49-05.zip](https://github.com/user-attachments/files/16278991/WslLogs-2024-07-17_23-49-05.zip)

**Comment by ferrellsl** [comment]
I'm unable to upload the diagnostic logs as the zip file is 38MB and the github limit is 25MB.

**Comment by ferrellsl** [comment]
[WslLogs-2024-07-17_23-49-05.zip](https://github.com/user-attachments/files/16278977/WslLogs-2024-07-17_23-49-05.zip)

**Comment by shigenobuokamoto** [comment]
@ferrellsl 
try this
```
$ sudo modprobe usbip-host
```

**Comment by ferrellsl** [comment]
> @ferrellsl try this
> 
> ```
> $ sudo modprobe usbip-host
> ```

The command completes successfully in bash with no output, but when I try to attach my device in an admin cmd shell, I get the same error message that the kernel isn't USBIPD capable

**Comment by shigenobuokamoto** [comment]
@ferrellsl 
sorry, looks like you need this module.
```
$ sudo modprobe vhci_hcd
```

**Comment by jmange** [comment]
> @ferrellsl sorry, looks like you need this module.
> 
> ```
> $ sudo modprobe vhci_hcd
> ```

For what it is worth, I was having the same issue and this solved it.  Thanks!

**Comment by ferrellsl** [comment]
> @ferrellsl sorry, looks like you need this module.
> 
> ```
> $ sudo modprobe vhci_hcd
> ```

Yes, this is working for me.  Thanks!

**Comment by lausfl** [comment]
I'm just now having this same issue after updating to Version 2.5.7.0 (I don't remember which version I had installed before), and although I can solve it by running the command mentioned above, it is only a temporary fix - I have to do it every time I restart WSL. Will this be fixed in a future update, so that USBIP works properly out of the box again?

**Comment by StefanHri** [comment]
Unfortunately, that doesn't work for me. These are my versions:
WSL version: 2.5.9.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.5472

**Comment by pfre01** [comment]
> Unfortunately, that doesn't work for me. These are my versions:
> WSL version: 2.5.9.0
> Kernel version: 6.6.87.2-1
> WSLg version: 1.0.66
> MSRDC version: 1.2.6074
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.22631.5472

Same here, updated wsl version to 2.5.9.0 and usbpid does not work anymore

**Comment by pfre01** [comment]
Been able to solve it by reinstalling https://github.com/dorssel/usbipd-win version usbipd-win 5.1.0
