### ISSUE TITLE
2.3.11 - Win11 Defender detects x64 msi as a `Trojan:Script/Wacatac.B!ml`

### ISSUE THREAD

**Issue by MrTomasz** [microsoft/WSL#11797]
### Windows Version

Microsoft Windows 11 24H2 10.0.26100.1150

### WSL Version

2.3.11

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Other Software

Windows Defender signatures version 1.415.150.0 (2024-07-17 14:08).

### Repro Steps

Download [wsl.2.3.11.0.x64.msi](https://github.com/microsoft/WSL/releases/download/2.3.11/wsl.2.3.11.0.x64.msi)

### Expected Behavior

Installer package is clean and able to be installed.

### Actual Behavior

Windows Defender detects a  `Trojan:Script/Wacatac.B!ml` in the MSI installer and removes it.

### Diagnostic Logs

```
webfile: C:\xxx\wsl.2.3.11.0.x64.msi|https://objects.githubusercontent.com/github-production-release-asset-2e65be/55626935/640d9564-e4e4-4ea5-b125-5da7bc8e825f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240718%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240718T084119Z&X-Amz-Expires=300&X-Amz-Signature=283a0eed31037353b376545ec86582cbdefefd4862eaec7f46a8a06e7d3080bc&X-Amz-SignedHeaders=host&actor_id=17730020&key_id=0&repo_id=55626935&response-content-disposition=attachment%3B%20filename%3Dwsl.2.3.11.0.x64.msi&response-content-type=application%2Foctet-stream|pid:13468,ProcessStart:133657656937118415
```

**Comment by DoctorWho8** [comment]
A false positive. Can you check with a different AV program?

**Comment by MrTomasz** [comment]
> Logs are required for review from WSL team

Not gonna provide because this is related to WSL installer, not to WSL itself.

> A false positive.
I am 99.9% sure it's false positive, but MSFT AV shall not react in that way for MSFT software. Previous versions were alright.

**Comment by newbenji** [comment]
> To be super explicit so that we're all on the same page:
> 
> The link in question: https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi
> 
> Ref: https://www.virustotal.com/gui/file/ac59215d7d723b226a6fbe9c85f88245e2d7355c7c8ec53fb8c0f1f4791d5d11/details
> 
> **Algo**	**Hash of MSI**
> MD5	`51d293f12d39aff872b805af22d8a7d9`
> SHA-1	`7a59e95038727c5f026f66618a6a01bea2400848`
> SHA-256	`ac59215d7d723b226a6fbe9c85f88245e2d7355c7c8ec53fb8c0f1f4791d5d11`
> Still hits positive as of Windows 11 Defender:
> 
> ```
> Security intelligence version: 1.415.174.0
> Version created on: 7/18/2024 3:47 AM
> ```

pretty sure its the new pre release

https://github.com/microsoft/WSL/releases/download/2.3.11/wsl.2.3.11.0.x64.msi


Thats the one testing postive in my ms defender. 

file: wsl.2.3.11.0.x64.msi
Virus: Trojan:Script/Wacatac.B!ml

**Comment by benhillis** [comment]
@davidfiala - we recently did some build system refactoring and publishing unsigned MSI files is a new regression. We're fixing that internally and will be updating our checks to make sure that doesn't happen again.

**Comment by benhillis** [comment]
I'll mark this as fixed when we push a new update.

**Comment by DoctorWho8** [comment]
> I'll mark this as fixed when we push a new update.

Great!

**Comment by MrTomasz** [comment]
I am happy now with `wsl.2.3.13.0.x64.msi`.
