### ISSUE TITLE
Kernel in 2.3.11 no longer monolithic?

### ISSUE THREAD

**Issue by polyzen** [microsoft/WSL#11792]
### Windows Version

Microsoft Windows [Version 10.0.19045.4651]

### WSL Version

2.3.11

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3

### Distro Version

Arch Linux

### Other Software

usbipd-win

### Repro Steps

1. `usbipd.exe attach --wsl --hardware-id 'blah'`
2. Receive error saying `WSL kernel is not USBIP capable`, due to `cat /sys/devices/platform/vhci_hcd.0/status` failing
3. `sudo modprobe vhci-hcd`
4. `usbipd.exe attach --wsl --hardware-id 'blah'`
5. Device attaches

### Expected Behavior

Module already loaded

### Actual Behavior

Try to attach USB device, find the vhci-hcd module needs to be loaded:
https://github.com/dorssel/usbipd-win/issues/995

**Comment by polyzen** [comment]
From usbipd-win dev:
> BTW: it worthwhile noting thay CONFIG_USBIP_HOST=m makes absolutely no sense. It used to be # CONFIG_USBIP_HOST is not set. WSL can never be a USB host. There is no physical USB, and the Linux USBIP subsystem does not allow forwarding client USB devices.

**Comment by polyzen** [comment]
Can provide the logs the bot requested, but not sure if they're necessary here.

**Comment by elsaco** [comment]
@polyzen are you using `systemd`? The `vhci_hcd` modules loads okay on a distro with `systemd=true` but won't load on a non-systemd distro. In fact no modules would load on a non-systemd WSL distro.

Look in `/lib/modules/6.6.36.3-microsoft-standard-WSL2/kernel/drivers/usb/usbip` and you'll find `vhci-hcd.ko` module.

```
ubuntu@eleven:~$ modinfo vhci-hcd
filename:       /lib/modules/6.6.36.3-microsoft-standard-WSL2/kernel/drivers/usb/usbip/vhci-hcd.ko
license:        GPL
description:    USB/IP 'Virtual' Host Controller (VHCI) Driver
author:         Takahiro Hirofuchi
depends:        usbcore,usbip-core,usb-common
retpoline:      Y
intree:         Y
name:           vhci_hcd
vermagic:       6.6.36.3-microsoft-standard-WSL2 SMP preempt mod_unload modversions
```

**Comment by polyzen** [comment]
Yes, this is with systemd. Maybe you misread, but I was able to load the module.

**Comment by polyzen** [comment]
https://github.com/microsoft/WSL/discussions/11789#discussioncomment-10083621
