### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/CreateVm/WSAENOTCONN

### ISSUE THREAD

**Issue by BurnerK** [microsoft/WSL#11807]
### Windows Version

Microsoft Windows [version10.0.26120.1252]

### WSL Version

2.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-1

### Distro Version

Ubuntu-22.04

### Other Software

WSL 版本： 2.3.11.0
内核版本： 6.6.36.3-1
WSLg 版本： 1.0.63
MSRDC 版本： 1.2.5326
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.26100.1-240331-1435.ge-release
Windows 版本： 10.0.26120.1252

### Repro Steps

I turned it off all night

### Expected Behavior

normal start

### Actual Behavior

由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
Error code: Wsl/Service/CreateInstance/CreateVm/WSAENOTCONN

```[tasklist]
### Tasks
```

**Comment by BurnerK** [comment]
[WslLogs-2024-07-19_10-27-05.zip](https://github.com/user-attachments/files/16301263/WslLogs-2024-07-19_10-27-05.zip)

**Comment by BurnerK** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs
> # View similar issues
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!
> 
> ### Open similar issues:
> * [Error code: Wsl/Service/CreateInstance/CreateVm/WSAENOTCONN Press any key to continue... (#11791)](https://github.com/microsoft/WSL/issues/11791),  similarity score: 0.87
> * [Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_SERVICE_NOT_AVAILABLE (#8693)](https://github.com/microsoft/WSL/issues/8693),  similarity score: 0.76
> 
> ### Closed similar issues:
> * [Error code: Wsl/Service/CreateInstance/0x8000ffff (#8711)](https://github.com/microsoft/WSL/issues/8711),  similarity score: 0.76
> * [wsl 启动报错 (#10213)](https://github.com/microsoft/WSL/issues/10213),  similarity score: 0.76
> * [Get a Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff when restart the WSL after shutdown (#11549)](https://github.com/microsoft/WSL/issues/11549),  similarity score: 0.75
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

[WslLogs-2024-07-19_10-27-05.zip](https://github.com/user-attachments/files/16301273/WslLogs-2024-07-19_10-27-05.zip)

**Comment by BurnerK** [comment]
> The log file doesn't contain any WSL traces. Please make sure **that you reproduced the issue while the log collection was running.**
> 
> Diagnostic information
> ```
> .wslconfig found
> Detected appx version: 2.3.11.0
> Found no WSL traces in the logs
> ```

[Uploading WslLogs-2024-07-19_10-32-15.zip…]()

**Comment by BurnerK** [comment]
help me😢

**Comment by dave-augustine** [comment]
same

**Comment by dave-augustine** [comment]
I have unchecked and check support for wsl via "Turn windows feature on and off" a couple of times
Still having issues.

**Comment by yybingyybing** [comment]
[WslLogs-2024-07-19_10-57-47.zip](https://github.com/user-attachments/files/16301524/WslLogs-2024-07-19_10-57-47.zip)
I have the same problem

**Comment by JustLookAtNow** [comment]
@yybingyybing 
@BurnerK @dave-augustine 
退回老版本即可，从github上面下载然后覆盖安装就行。
我发现一个问题，遇上这个问题的全是简中用户，隔壁issue里面也全是中国人。

**Comment by kszinhu** [comment]
@JustLookAtNow 

Could u write in English?, you comment to downgrade to the old version of what?

**Comment by JustLookAtNow** [comment]
@kszinhu Of course. What I mean is to downgrade the WSL version. You can download the 2.2.4 release version from GitHub and install it to restore normal functionality.

**Comment by nnathan** [comment]
I'm having the same issue starting up the kernel built from the WSL2 kernel source with tag `linux-msft-wsl-6.6.36.3`. I only changed the config so that everything was `=y` instead of `=m` as recommended in the README for building. My bzImage is in `c:\Users\naveen\bzImage-linux-msft-wsl-6.6.36.3` and I have the following `.wslconfig`:

```
[wsl2]
kernel=C:\\Users\\naveen\\bzImage-linux-msft-wsl-6.6.36.3
networkingMode=mirrored
```

WSL2 info:

```
wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2 (ignore this, this is the kernel I had to revert to because of the error)
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3880
```

**Comment by Pi3k-Akt** [comment]
> @yybingyybing @BurnerK @dave-augustine 退回老版本即可，从github上面下载然后覆盖安装就行。 我发现一个问题，遇上这个问题的全是简中用户，隔壁issue里面也全是中国人。

退回了老版本（甚至尝试了各种老版本），还是同样的报错

**Comment by JustLookAtNow** [comment]
@Pi3k-Akt 你是不是自定义内核了？下面这个版本是没有问题的，你自己对比下：
WSL 版本： 2.2.4.0
内核版本： 5.15.153.1-2
WSLg 版本： 1.0.61
MSRDC 版本： 1.2.5326
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.26091.1-240325-1447.ge-release
Windows 版本： 10.0.26100.1150
