### ISSUE TITLE
Kernel osrelease string breaks kernel packaging (formerly #6911)

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#11814]
### Windows Version

Microsoft Windows [Version 10.0.26120.1252]

### WSL Version

2.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.10.0-20240719-1-microsoft-custom-WSL2+ (happens on all versions, though)

### Distro Version

Debian sid

### Other Software

Linux kernel packaging scripts

### Repro Steps

1. Fetch the WSL kernel source from GitHub.
2. Copy the default config file from Microsoft/config-wsl to .config
3. make deb-pkg

### Expected Behavior

The kernel packages should have been properly built as described here:

https://debian-handbook.info/browse/stable/sect.kernel-compilation.html

### Actual Behavior

The build fails as follows:

```
sh ./scripts/package/mkdebian
  TAR     linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+.tar.gz
origversion=$(dpkg-parsechangelog -SVersion |sed 's/-[^-]*$//');\
        mv linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+.tar.gz ../linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+_${origversion}.orig.tar.gz
dpkg-buildpackage -r"fakeroot -u" -a$(cat debian/arch)  -i.git -us -uc
dpkg-buildpackage: info: source package linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+
dpkg-buildpackage: info: source version 5.10.16.3-20210504-1-microsoft-custom-WSL2+-2
dpkg-buildpackage: info: source distribution bullseye
dpkg-buildpackage: info: source changed by Alistair Young <avatar@arkane-systems.net>
 dpkg-source -i.git --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: error: source package name 'linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+' is illegal: character 'W' not allowed
dpkg-buildpackage: error: dpkg-source -i.git --before-build . subprocess returned exit status 255
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 255
make: *** [Makefile:1529: deb-pkg] Error 2
zsh: exit 2
```

For further details and discussion please see #6911, of which this is a resubmission per the microsoft-github-policy-service-bot.

**Comment by cerebrate** [comment]
Current patch for this issue is over here:

https://open.substack.com/pub/randombytes/p/building-apt-6n-kernel-packages-for

**Comment by benhillis** [comment]
@cerebrate - so just to clarify, there shouldn't be any upper-case characters in the string? @chessturo - is this something you could look into please?

**Comment by zcobol** [comment]
This is a Debian only rule:

`Package names (both source and binary, see [Package](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-package)) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.`

**Comment by cerebrate** [comment]
It also appears to be a technical limitation of the apt packaging tools, insofar as they puke when confronted with nonconforming names, and as such presumably affects every apt-using distribution, not just Debian.

**Comment by chessturo** [comment]
I can confirm that this issue exists as described, but this seems more like a bug in the upstream build scripts, rather than a WSL issue. Details on how to submit a patch upstream can be found [here](https://www.kernel.org/doc/html/latest/process/submitting-patches.html).
