### ISSUE TITLE
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE

### ISSUE THREAD

**Issue by heartacker** [microsoft/WSL#11828]
### Windows Version

11

### WSL Version

2.3.12

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu  24.10

### Repro Steps

WSL 正在完成升级...
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.IsSystemComponent' for shortcut 'WSL Settings.lnk' could not be set.
Could not write value  to key \SOFTWARE\Classes\Directory\shell\WSL.   Verify that you have sufficient access to that key, or contact your support personnel.
更新失败(退出代码: 1603)。
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE

[已退出进程，代码为 4294967295 (0xffffffff)]
现在可以使用Ctrl+D关闭此终端，或按 Enter 重新启动。

### Expected Behavior

ok

### Actual Behavior

WSL 正在完成升级...
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.IsSystemComponent' for shortcut 'WSL Settings.lnk' could not be set.
Could not write value  to key \SOFTWARE\Classes\Directory\shell\WSL.   Verify that you have sufficient access to that key, or contact your support personnel.
更新失败(退出代码: 1603)。
Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE

[已退出进程，代码为 4294967295 (0xffffffff)]
现在可以使用Ctrl+D关闭此终端，或按 Enter 重新启动。

**Comment by wwmmzz** [comment]
similar issues with `wsl.2.3.12.0.x64.msi`

run `msiexec /i <path/to/msi> /L*V .\wsllogs.txt` get log:
```
MSI (s) (B8:90) [07:50:49:824]: Note: 1: 2318 2: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WSL.lnk 
MSI (s) (B8:90) [07:50:49:825]: Note: 1: 2318 2: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WSL.lnk 
MSI (s) (B8:90) [07:50:49:825]: Executing op: ShortcutPropertyCreate(ShortcutName=WSL,PropertyKey=System.AppUserModel.ID,PropVariantValue=Microsoft.WSL)
MSI (s) (B8:90) [07:50:49:830]: Executing op: ShortcutPropertyCreate(ShortcutName=WSL,PropertyKey=System.AppUserModel.ToastActivatorCLSID,PropVariantValue={2B9C59C3-98F1-45C8-B87B-12AE3C7927E8})
MSI (s) (B8:90) [07:50:49:834]: Executing op: ShortcutCreate(Name=whinzpvc|WSL Settings,Feature=WSL,Component={AB166073-8855-492B-95C8-C6E5939B66A5}[~]2,,,,Icon=wsl.ico,,,,Description=Windows Subsystem for Linux Settings,,,,)
MSI (s) (B8:90) [07:50:49:841]: Note: 1: 2318 2: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WSL Settings.lnk 
MSI (s) (B8:90) [07:50:49:841]: Executing op: ShortcutPropertyCreate(ShortcutName=whinzpvc|WSL Settings,PropertyKey=System.AppUserModel.IsSystemComponent,PropVariantValue=true)
MSI (s) (B8:90) [07:50:49:843]: Note: 1: 1946 2: System.AppUserModel.IsSystemComponent 3: WSL Settings.lnk 4: 32811 
MSI (s) (B8:90) [07:50:49:843]: Note: 1: 2205 2:  3: Error 
MSI (s) (B8:90) [07:50:49:843]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1946 
MSI (c) (A8:DC) [07:50:49:848]: Font created.  Charset: Req=1, Ret=134, Font: Req=, Ret=宋体

MSI (c) (A8:DC) [07:50:49:849]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial

Warning 1946.Property 'System.AppUserModel.IsSystemComponent' for shortcut 'WSL Settings.lnk' could not be set. HRESULT 32811.
MSI (s) (B8:90) [07:51:05:771]: Executing op: SetTargetFolder(Folder=23)
MSI (s) (B8:90) [07:51:05:773]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
MSI (s) (B8:90) [07:51:05:773]: Executing op: ActionStart(Name=WriteRegistryValues,Description=Writing system registry values,Template=Key: [1], Name: [2], Value: [3])
MSI (s) (B8:90) [07:51:05:774]: Executing op: ProgressTotal(Total=69,Type=1,ByteEquivalent=13200)
MSI (s) (B8:90) [07:51:05:774]: Executing op: RegOpenKey(,Key=Interface\{38541BDC-F54F-4CEB-85D0-37F0F3D2617E},,BinaryType=1,ControlRegistryReflection=0,)
MSI (s) (B8:90) [07:51:05:774]: Executing op: RegAddValue(,Value=ILxssUserSession,)
```

**Comment by Stanzilla** [comment]
This can then lead to https://github.com/microsoft/WSL/issues/11827

**Comment by God-damnit-all** [comment]
Seems to happen from installing a distribution when you have no other distribution using a distro not found on the Microsoft Store.

You need to remove `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WSL Settings.lnk` (and possibly `WSL.lnk`, though probably not) and go into the Advanced security permissions for the following registry keys, enabling inheritance, hitting apply, and then removing all non-inherited permissions and hitting Okay:

`HKLM\SOFTWARE\Classes\Drive\shell\WSL`
`HKLM\SOFTWARE\Classes\Drive\shell\WSL\command`
`HKLM\SOFTWARE\Classes\Directory\shell\WSL`
`HKLM\SOFTWARE\Classes\Directory\shell\WSL\command`
`HKLM\SOFTWARE\Classes\Directory\background\shell\WSL`
`HKLM\SOFTWARE\Classes\Directory\background\shell\WSL\command`

Alternatively, you can remove these registry keys, but I don't know if they come back.

I don't know why `WSL Settings.lnk` has to be removed considering it had valid security permissions for me, maybe Windows expects the shortcut itself to be a certain way. The upgrade doesn't create a new one.
