### ISSUE TITLE
Ubuntu已安装。 正在启动Ubuntu... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xc03a0014 Error: 0xc03a0014 ???????????????????

### ISSUE THREAD

**Issue by SJ-prog** [microsoft/WSL#11831]
### Windows Version

Microsoft Windows [版本 10.0.19044.4412]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153

### Repro Steps

powershell: wsl --install

### Expected Behavior

Normal access to Ubuntu

### Actual Behavior

Ubuntu已安装。 正在启动Ubuntu... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xc03a0014 Error: 0xc03a0014 ???????????????????

### Diagnostic Logs

[WslLogs-2024-07-24_16-16-43.zip](https://github.com/user-attachments/files/16359387/WslLogs-2024-07-24_16-16-43.zip)

**Comment by SJ-prog** [comment]
I tried again
[Uploading WslLogs-2024-07-25_09-46-24.zip…]()

**Comment by flydt** [comment]
> ### Windows Version
> Microsoft Windows [版本 10.0.19044.4412]
> 
> ### WSL Version
> 2.2.4.0
> 
> ### Are you using WSL 1 or WSL 2?
> * [x]  WSL 2
> * [ ]  WSL 1
> 
> ### Kernel Version
> 5.15.153
> 
> ### Distro Version
> _No response_
> 
> ### Other Software
> _No response_
> 
> ### Repro Steps
> powershell: wsl --install
> 
> ### Expected Behavior
> Normal access to Ubuntu
> 
> ### Actual Behavior
> Ubuntu已安装。 正在启动Ubuntu... Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xc03a0014 Error: 0xc03a0014 ???????????????????
> 
> ### Diagnostic Logs
> [WslLogs-2024-07-24_16-16-43.zip](https://github.com/user-attachments/files/16359387/WslLogs-2024-07-24_16-16-43.zip)

linux sub system not enabled correctly（没正确开启 linux 子系统，打开后重启一下，再来就行了）

**Comment by OneBlue** [comment]
> I tried again Uploading WslLogs-2024-07-25_09-46-24.zip…

This link points to this page. Can you share /logs capturing the issue ?
