### ISSUE TITLE
WSL2 with /dev/dri passthrough to Docker container not working

### ISSUE THREAD

**Issue by sikhness** [microsoft/WSL#11846]
### Windows Version

Microsoft Windows [Version 10.0.22631.3880]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Verify VA-API is working within WSL2 by performing `vainfo --display drm` and all supported profiles for the video card should be published
2. Create a Ubuntu Docker container and pass through `/dev/dri` using `sudo docker run -it --privileged --name ubuntu --device /dev/dri:/dev/dri:rwm ubuntu:22.04 bash`
3. Inside the Ubuntu Docker container install vainfo and set the environment variables for d3d12 using the following commmands: `apt update; apt install vainfo -y` and `export LIBVA_DRIVER_NAME=d3d12`
4. Run `vainfo --display drm` within the Docker container

### Expected Behavior

I expected vainfo within the container to output the same information as the WSL2 host which is the following:
```
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 23.2.1-1ubuntu3.1~22.04.2 for D3D12 (NVIDIA Quadro P1000)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

### Actual Behavior

Instead what I got was a `resource allocation failed` error and I'm unable to use the `/dev/dri` device as shown below in the container output of `vainfo --display drm`:
```
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva error: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
```

**Comment by sikhness** [comment]
[WslLogs-2024-07-26_16-38-55.zip](https://github.com/user-attachments/files/16396532/WslLogs-2024-07-26_16-38-55.zip)

**Comment by onomatopellan** [comment]
I don't think that's enough. Look at the official guide to get VA-API inside the container:

https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md#containerized-applications-access-to-vgpu-accelerated-video

**Comment by sikhness** [comment]
@onomatopellan thank you so much, that was it!

I felt like I scoured the entire internet but wasn't able to find that, wished all this was documented on Microsoft's website instead of having to scrape through various Github issues/commits & blog posts.
