### ISSUE TITLE
Catastrophic failure :Error code: Wsl/Service/CreateInstance/MountVhd/HCS/0x80070570

### ISSUE THREAD

**Issue by xiezhipeng-git** [microsoft/WSL#11849]
### Windows Version

Microsoft Windows [Version 10.0.22631.3958]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04LTS

### Other Software

vscode 1.91.1

### Repro Steps

when I writecode on vscode in wsl.Then vscode crashed and restart.then the wsl can not open

### Expected Behavior

can open wsl.and can use

### Actual Behavior

can not open wsl with vscode and file manger

### Diagnostic Logs

https://github.com/user-attachments/files/16402723/WslLogs-2024-07-28_16-56-38.zip

**Comment by xiezhipeng-git** [comment]
[WslLogs-2024-07-28_18-24-26.zip](https://github.com/user-attachments/files/16402959/WslLogs-2024-07-28_18-24-26.zip)
![image](https://github.com/user-attachments/assets/9efbad70-6827-40c7-bc31-ae8786f60e1b)

**Comment by xiezhipeng-git** [comment]
@https://github.com/neokofg

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/user-attachments/assets/c550a5c7-49ea-4285-9ec8-f374c2b6af8b)

**Comment by xiezhipeng-git** [comment]
wsl status 
无法将磁盘“C:\Users\Admin\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\ext4.vhdx”附加到 WSL2： 文件或目录损坏且无法读取

**Comment by xiezhipeng-git** [comment]
PS C:\Users\Admin> wsl status
无法将磁盘“C:\Users\Admin\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\ext4.vhdx”附加到 WSL2： 文件或目录损坏且无法读取。
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/0x80070570
PS C:\Users\Admin> wsl --status
默认分发: Ubuntu-22.04
默认版本: 2

wsl status 与 wsl --status return diff result
and docker file is nomal. wsl ubuntu error

**Comment by xiezhipeng-git** [comment]
And I noticed. If I use DiskGenius
I couldn't find the image file in the corresponding directory, but the file I copied from the same path on the D drive can be found.

**Comment by xiezhipeng-git** [comment]
I already upload log
![image](https://github.com/user-attachments/assets/a65bdd8d-ba32-4c3e-98d8-60a9c40b3ec3)
and
![image](https://github.com/user-attachments/assets/1fd438a8-d315-40f6-b9ab-bd51c68a2630)
@OneBlue

**Comment by OneBlue** [comment]
You need to collect logs while you reproduce the issue so the error is captured.

/logs

**Comment by xiezhipeng-git** [comment]
@OneBlue 
https://github.com/user-attachments/files/16402959/WslLogs-2024-07-28_18-24-26.zip
The above log is obtained when opening the VSCode WSL project.
The current issue is in a permanent state. When I tried using WSL, it looked like this, and I couldn't open the folder either. I don't know what else I can do to get the logs you want. Enter WSL status? Or open the VSCode WSL project?
Below is the use of collect-wsl-logs.s1
Then the WSL status
Then collect the logs after collecting wsl-logs.ts1 again

**Comment by xiezhipeng-git** [comment]
[WslLogs-2024-08-02_20-05-54.zip](https://github.com/user-attachments/files/16470235/WslLogs-2024-08-02_20-05-54.zip)
@OneBlue 
Does this log contain the necessary information?

**Comment by OneBlue** [comment]
Thank you @xiezhipeng-git. Here's the root cause of the error you're seeing: 

```
Microsoft.Windows.Lxss.Manager	Error	08-02-2024 05:06:26.221	"	"	"code: 	
failurecount: 	13
file: 	C:\__w\1\s\src\windows\common\hcs.cpp
function: 	
hr: 	0x80070570
linenumber: 	231
message: 	""HcsWaitForOperationResult for HcsModifyComputeSystem failed ({""""ResourcePath"""":""""VirtualMachine/Devices/Scsi/0/Attachments/2"""",""""RequestType"""":""""Add"""",""""Settings"""":{""""Type"""":""""VirtualDisk"""",""""Path"""":""""C:\\Users\\Admin\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\\LocalState\\ext4.vhdx"""",""""SupportCompressedVolumes"""":true,""""AlwaysAllowSparseFiles"""":true,""""SupportEncryptedFiles"""":true}} - error string: {""""Error"""":-2147023504,""""ErrorMessage"""":""""文件或目录损坏且无法读取。"""",""""ErrorEvents"""":[{""""Message"""":""""“CA4CE02A-643B-4335-8469-4FEC048BC5A3”: 附件“C:\\Users\\Admin\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\\LocalState\\ext4.vhdx”无法打开，因为出现错误“文件或目录损坏且无法读取。”(0x80070570)。(虚拟机 ID CA4CE02A-643B-4335-8469-4FEC048BC5A3)"""",""""Provider"""":""""edacd782-2564-4497-ade6-7199377850f2"""",""""EventId"""":12140,""""Flags"""":5,""""Data"""":[{""""Type"""":""""String"""",""""Value"""":""""CA4CE02A-643B-4335-8469-4FEC048BC5A3""""},{""""Type"""":""""String"""",""""Value"""":""""CA4CE02A-643B-4335-8469-4FEC048BC5A3""""},{""""Type"""":""""String"""",""""Value"""":""""C:\\Users\\Admin\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\\LocalState\\ext4.vhdx""""},{""""Type"""":""""String"""",""""Value"""":""""%%2147943792""""},{""""Type"""":""""String"""",""""Value"""":""""0x80070570""""},{""""Type"""":""""String"""",""""Value"""":""""""""},{""""Type"""":""""String"""",""""Value"""":""""""""}]}]})""
threadid: 	13676
type: 	0
wslVersion: 	2.3.13.0"	C:\__w\1\s\src\windows\common\hcs.cpp			6172	13676	2		00000000-0000-0000-0000-000000000000		

```

The error code (0x80070570) is `ERROR_FILE_CORRUPT`, which points to filesystem corruption. One thing you can try would be to run: `chkdsk /f` and reboot, but most likely you might have to register the distribution again via `wsl --unregister <distro>` and install it again, which unfortunately means losing your files.

**Comment by xiezhipeng-git** [comment]
@OneBlue 
你的意思是我需要在cmd里尝试
chkdsk /fwsl --unregister <distro>
这个命令吗？那么这个命令会导致文件内容丢失吗？以及暂时我不能执行这个命令。因为该电脑因为英特尔的不定时蓝屏崩溃而送修了。执行这个命令的结果得之后才能了解。然后这个命令有可能会让wsl正常运行而不丢失数据吗？
还有本来就是因为vscode运行中崩溃导致的这个问题。如果你们不能解决。不就意味着任何wsl都有这种随时挂掉一切文件丢失的可能。那谁还敢用wsl啊。
并且。我发现。这个文件ext4.vhdx仍然可以通过diskgenis查看和修改.这说明如果知道是哪里的数据不对。就有可能修复。但是这里需要的内容太多太细了，我自己不能独立解决。

**Comment by xiezhipeng-git** [comment]
@OneBlue 
你的意思是我需要在cmd里尝试
chkdsk /fwsl --unregister <distro>
这个命令吗？那么这个命令会导致文件内容丢失吗？以及暂时我不能执行这个命令。因为该电脑因为英特尔的不定时蓝屏崩溃而送修了。执行这个命令的结果得之后才能了解。然后这个命令有可能会让wsl正常运行而不丢失数据吗？
还有本来就是因为vscode运行中崩溃导致的这个问题。如果你们不能解决。不就意味着任何wsl都有这种随时挂掉一切文件丢失的可能。那谁还敢用wsl啊。
并且。我发现。这个文件ext4.vhdx仍然可以通过diskgenis查看和修改.这说明如果知道是哪里的数据不对。就有可能修复。但是这里需要的内容太多太细了，我自己不能独立解决。

**Comment by xiezhipeng-git** [comment]
@OneBlue 
Do you mean I need to try the command chkdsk /fwsl --unregister <distro>in cmd?And will this command result in loss of file contents?As well as for the time being I can't execute this command.Because the computer was sent for repair due to an untimely Intel blue screen crash.The result of executing this command will have to be known later.And then is it possible that this command will allow wsl to run normally without losing data?Also it was supposed to be a crash in vscode runtime that caused this problem.If you guys can't fix it.Doesn't that mean that any wsl has this possibility of hanging up at any time and losing all files.Who would dare to use wsl then.And.I found.This file ext4.vhdx can still be viewed and modified by diskgenis.This means that if you know where the data is wrong.It would be possible to fix it.But there's too much and too much detail needed here for me to fix it on my own.</distro>

**Comment by xiezhipeng-git** [comment]
@OneBlue 
I tried this with my old cumputer wsl that had the same problem.Neither method worked.
![image](https://github.com/user-attachments/assets/f1be037d-0761-4c96-b046-dcad438b597d)

**Comment by OneBlue** [comment]
@xiezhipeng-git: The bluescreen errors are most likely what caused the disk corruption in the first place. You can try to run `chkdsk /f` and then follow [these instructions](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-repair-a-vhd-mounting-error) to try to recover the disk but based on the state of your machine I think it' unlikely to work. 


The screenshot you sent is a different error code. Can you capture /logs of that please ?

**Comment by xiezhipeng-git** [comment]
The reason for the different error codes is that the Unregister command was executed.This command directly deletes the file ext4.vhdx.I ran this command on an older computer.The computer with important data is still in the process of being sent for repair due to an error caused by an untimely Intel blue screen.Then there is no blue screen when something goes wrong, and after almost every blue screen I have tried to use chkdsk /f Each time I get 0 errors. 0 fixes.And it has no effect on the /MountVhd/HCS/0x80070570 error!

**Comment by xiezhipeng-git** [comment]
@OneBlue 
That's a different computer. And the error only occurs because the command to cancel registration has already been executed. Is submitting that error still meaningful? Additionally, I have discovered. Please take a look at this link. It seems like I was cutting something when VSCode crashed. And then it led to this problem. If you know this information. Is it still possible to fix the vhdx file? And this problem has not been solved at all. It should not have been closed
https://blog.csdn.net/ONE_SIX_MIX/article/details/119416091
