### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80072749

### ISSUE THREAD

**Issue by THZ34** [microsoft/WSL#11844]
### Windows Version

Microsoft Windows [版本 10.0.22635.3858]

### WSL Version

2.3.11.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 24.0.2, build cb74dfc

### Repro Steps

wsl.exe --install Ubuntu-22.04

### Expected Behavior

Enter the ubuntu subsystem

### Actual Behavior

正在安装: Ubuntu 22.04 LTS
已安装 Ubuntu 22.04 LTS。
正在启动 Ubuntu 22.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80072749
Error: 0x80072749 ???????????(????? sendto ???????????)???????????????????????

Press any key to continue...
分发“Ubuntu-22.04”的安装过程失败，退出代码： 1。
Error code: Wsl/InstallDistro/WSL_E_INSTALL_PROCESS_FAILED

**Comment by THZ34** [comment]
[WslLogs-2024-07-26_23-54-35.zip](https://github.com/user-attachments/files/16393972/WslLogs-2024-07-26_23-54-35.zip)

**Comment by THZ34** [comment]
[WslLogs-2024-07-26_23-57-30.zip](https://github.com/user-attachments/files/16393998/WslLogs-2024-07-26_23-57-30.zip)

**Comment by THZ34** [comment]
[WslLogs-2024-07-27_00-00-37.zip](https://github.com/user-attachments/files/16394027/WslLogs-2024-07-27_00-00-37.zip)

**Comment by benhillis** [comment]
@chessturo - another instance of a FPU-related kernel panic.

**Comment by chessturo** [comment]
Closing as a dup of https://github.com/microsoft/WSL/issues/11791. We have a temporary fix listed there --- if the fix does not work for you, please let me know.

**Comment by hecgavin94** [comment]
[WslLogs-2025-04-11_20-33-08.zip](https://github.com/user-attachments/files/19712909/WslLogs-2025-04-11_20-33-08.zip)please help me figure out the problem while initialiazing Ubuntu 22.04/24.04

**Comment by hecgavin94** [comment]
> [WslLogs-2025-04-11_20-33-08.zip](https://github.com/user-attachments/files/19712909/WslLogs-2025-04-11_20-33-08.zip)please help me figure out the problem while initialiazing Ubuntu 22.04/24.04

@github-actions
