### ISSUE TITLE
A fresh install of WSL gets the error "-bash: eval: line 136: syntax error: unexpected end of file"

### ISSUE THREAD

**Issue by NinoDLC** [microsoft/WSL#11854]
### Windows Version

Microsoft Windows [version 10.0.22631.3880]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1

### Distro Version

22.04

### Repro Steps

1/ Install WSL (`wsl --install`)
2/ Follow the [guide](https://learn.microsoft.com/en-us/windows/wsl/install), nothing too complex
3/ Reboot
4/ Use `wsl` command in Terminal (Powershell)
5/ Get the error `-bash: eval: line 136: syntax error: unexpected end of file` : 
```
C:\Work> wsl
-bash: eval: line 136: syntax error: unexpected end of file
nino@Desktino:/mnt/c/Work$
```

### Expected Behavior

Not get an error

### Actual Behavior

Got an error that I can't fix myself

**Comment by OneBlue** [comment]
@NinoDLC: This looks like an issue coming from your .bashrc. 

Can you share the content of your `.bashrc` and `.profile` ?
