### ISSUE TITLE
maxima doesn't work, "personality change failure 0"

### ISSUE THREAD

**Issue by renanbirck** [Microsoft/WSL#1185]
- A brief description
  Trying to run the Maxima computer-algebra system, it gives the error "personality change failure 0" and dies.
- Expected results
  When I run maxima, it should launch and work; the front-ends (wxMaxima, xmaxima) should work, too.
- Actual results (with terminal output if applicable)
  It says "personality change failure 0".
- Your Windows build number
  Build 14393.222
- Steps / All commands required to reproduce the error from a brand new installation 
  Install maxima (`apt-get install maxima`) and then try to run `maxima`.
- Strace of the failing command
  To not make this report too long, it's here:
  https://gist.github.com/renanbirck/c3095df655a835ab3cc49f885bb40bfe
- Required packages and commands to install
  Just maxima (apt-get install maxima).

**Comment by fpqc** [comment]
I noticed it was trying to load libX11 in the strace.  Could you install and run vcXsrv and run Maxima with:

`DISPLAY=:0 maxima`

**Comment by mobluse** [comment]
I mentioned this earlier in https://github.com/Microsoft/BashOnWindows/issues/1128#issuecomment-250190207

I now use Octave with octave-symbolic, see https://youtu.be/r3XOrW8tVSY and description.

**Comment by renanbirck** [comment]
@fpqc, unfortunately it doesn't change anything.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I took a look at the maxima repro under strace and it's trying to set a personality of STICKY_TIMEOUTS which isn't supported today in WSL.

**Comment by mobluse** [comment]
This is still a problem in the latest release (15042.0.amd64fre.rs2_release.170219-2329):
```
$ maxima
personality failure 38
```

**Comment by mobluse** [comment]
In openSUSE Leap 42.2 under Windows 10 16288.1.amd64fre.rs3_release.170909-0851 it's even worse:
`> sudo zypper install maxima`
`> maxima`
And you get a lots of errors and it's difficult to stop with Ctrl+C.

**Comment by jstarks** [comment]
I’ve got Ubuntu’s maxima working in an internal build. The fixes should be available in a future insider build.

**Comment by jstarks** [comment]
This should be fixed in [insider build 17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes).

**Comment by mobluse** [comment]
Microsoft Windows [Version 10.0.17063.1000]

The command `maxima` doesn't do anything now.  It only returns without even printing an error message.

```
$ maxima
$
```

In ordinary Ubuntu it prints version of maxima and then there is a maxima prompt. How it should be in Ubuntu 16.04 (from Lubuntu for Raspberry Pi):
```
$ maxima

Maxima 5.37.2 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.12
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1)
```

I first uninstalled maxima with:
```
$ sudo apt purge maxima
$ sudo apt autoremove
```

Then reinstalled it, but it didn't help:
`$ sudo apt install maxima`

**Comment by jstarks** [comment]
Hmm, that’s unexpected. I’ll take a look soon.

**Comment by jstarks** [comment]
Bad luck -- we are hitting a failure in the `execve` code path once it's too late to report a failure to the caller. This is due to some unrelated memory management improvements to Windows that introduced a bug. We'll get this fixed soon. Thanks for pointing it out!

**Comment by mobluse** [comment]
I just installed the latest insider Microsoft Windows [Version 10.0.17074.1002] and `maxima` is still unfixed, i.e. it is as in Microsoft Windows [Version 10.0.17063.1000].

**Comment by Brian-Perkins** [comment]
The execve failure should be fixed in Insiders Build 17083

**Comment by sangwinc** [comment]
I'm trying to set up Maxima in a docker container based on php:7.0-apache 
I'm also getting "personality failure 0" as a result.  See below!  Any suggestions please?

```
root@ad3265ff4f24:/var/data/api/stack# apt-get install maxima
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  maxima-share
Suggested packages:
  texmacs maxima-doc xmaxima maxima-emacs wish
The following NEW packages will be installed:
  maxima maxima-share
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 11.4 MB of archives.
After this operation, 58.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main armhf maxima armhf 5.38.1-8+b1 [5055 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main armhf maxima-share all 5.38.1-8 [6365 kB]
Fetched 11.4 MB in 6s (1708 kB/s)                                                                                                                                      
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package maxima.
(Reading database ... 22954 files and directories currently installed.)
Preparing to unpack .../maxima_5.38.1-8+b1_armhf.deb ...
Unpacking maxima (5.38.1-8+b1) ...
Selecting previously unselected package maxima-share.
Preparing to unpack .../maxima-share_5.38.1-8_all.deb ...
Unpacking maxima-share (5.38.1-8) ...
Setting up maxima (5.38.1-8+b1) ...
Setting up maxima-share (5.38.1-8) ...
root@ad3265ff4f24:/var/data/api/stack# maxima
personality failure 0

```
