### ISSUE TITLE
WSL 2.3.14 doesn't work on Windows 2025 (but 2.2.4 does)

### ISSUE THREAD

**Issue by joshmouch** [microsoft/WSL#11878]
### Windows Version

Windows 2025 DataCenter (10.0.26257.5000)

### WSL Version

2.3.14

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-1

### Distro Version

Any

### Repro Steps

On Windows Server 2025 DataCenter preview, upgrade to the latest preview version of WSL.

### Expected Behavior

Normal WSL behavior.

### Actual Behavior

Aside from "mirror" mode not being supported, WSL has been working well with Windows DataCenter 2025 preview.
However, I just tried upgrading the latest WSL preview (2.3.14) and nothing seems to work.
If I try to start a distro, I get:
```
PS C:\Users\administrator.MOUCH> wsl
A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
Error code: Wsl/Service/CreateInstance/CreateVm/WSAENOTCONN
```

If I try to run with `--debug-shell` then I get something close to (not exactly):
`Error code: NOT FOUND Wsl/DEBUGSHELL/...`

If I uninstall WSL and then reinstall it with the latest "stable" version (2.2.4), then everything's back to normal.

Then I tried updating to the latest preview again, with the same result.

**Comment by JustLookAtNow** [comment]
https://github.com/microsoft/WSL/issues/11791#issuecomment-2257225030 just try it!

**Comment by zcobol** [comment]
On `Server 2025 Data Center` version `10.0.26100.1150` it works as expected:

```
elsaco@PORTLAND:~$ wslinfo --networking-mode
nat
elsaco@PORTLAND:~$ wslinfo --wsl-version
2.3.14
elsaco@PORTLAND:~$ wsl.exe --version
WSL version: 2.3.14.0
Kernel version: 6.6.36.3-1
WSLg version: 1.0.64
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.1150  
```

`Desktop Experience` installed, not sure if it makes any difference.

Uses settings, mostly defaults:

```
PS C:\Users\elsaco> cat .\.wslconfig
[wsl2]
processors=4
memory=2147483648
```

**Comment by elsaco** [comment]
Using non-store upgrade it worked on `10.0.26257.5000`. The `.wslconfig` has only cpu and memory limits, no other custom settings were used:

```
PS C:\Users\Elsaco> wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.26257.5000
PS C:\Users\Elsaco> wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.3.14.
PS C:\Users\Elsaco> wsl --version
WSL version: 2.3.14.0
Kernel version: 6.6.36.3-1
WSLg version: 1.0.64
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26257.5000
PS C:\Users\Elsaco> wsl
elsaco@PORTLAND:/mnt/c/Users/Elsaco$ cd
elsaco@PORTLAND:~$ wslinfo --wsl-version
2.3.14
elsaco@PORTLAND:~$ wslinfo --networking-mode
nat
```

```
PS C:\Users\Elsaco> cat .\.wslconfig
[wsl2]
processors=4
memory=4294967296
swap=0
```

@joshmouch you could try w/out custom setting and see if it works.  It helps sometimes!

**Comment by angel00027** [comment]
porque en wsl2 tengo un problema con el soporte para cgroups v2 , antes si me deja instalar pterodactyl y funcionaba bien con las wigns y el docker pero ahora ya no
