### ISSUE TITLE
Wsl2 networking mode mirrored not supported. back to NAT #network

### ISSUE THREAD

**Issue by peilin-liu** [microsoft/WSL#11873]
### Windows Version

10.0.19045.4717

### WSL Version

2.3.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-1

### Distro Version

Ubuntu 22.04.3 LTS

### Other Software

docker desktop 4.30.0 (149282)

### Repro Steps

1. open shell
2: run wsl

error:
$ wsl
wsl: C:\Users\peili\.wslconfig:2 中的未知密钥 'boot.systemd'
wsl: 不支持镜像网络模式： Windows 版本 19045.4717 没有所需的功能。
正在回退到 NAT 网络。

### Expected Behavior

network Mirror mode works correctly。

### Actual Behavior

$ wsl
wsl: C:\Users\peili\.wslconfig:2 中的未知密钥 'boot.systemd'
wsl: 不支持镜像网络模式： Windows 版本 19045.4717 没有所需的功能。
正在回退到 NAT 网络。

### Diagnostic Logs

[WslLogs-2024-08-03_19-23-10.zip](https://github.com/user-attachments/files/16479431/WslLogs-2024-08-03_19-23-10.zip)

**Comment by Ronchy2000** [comment]
我的配置：win10 + wsl2:Ubuntu 22.04.3 LTS
This is unfortunately by design. Mirrored networking is only supported on Windows 11.

我和你的问题一模一样，都是不能开启镜像模式。因为这个模式只有win11支持，而我又不愿意升级到win11.

所以网络问题还是用端口转发的模式吧。
