### ISSUE TITLE
ReadConsoleInput doesn't return key-up events when Ctrl or Shift is held down

### ISSUE THREAD

**Issue by rossy** [Microsoft/WSL#1188]
- A brief description

A program that uses ReadConsoleInput does not receive a KEY_EVENT with .bKeyDown = FALSE when a key is released while Ctrl or Shift is held down. I think this is a regression in the new console because Windows 8.1 and Windows 10 with "use legacy console" ticked is not affected.
- Steps / All commands required to reproduce the error from a brand new installation 
1. Launch a Win32 console program that uses ReadConsoleInput to read from the console.
2. Press the Ctrl key
3. Press the 'H' key
4. Release the 'H' key
5. Release the Ctrl key
- Expected results

The program receives four input events:
1. Ctrl key pressed (.bKeyDown = TRUE, .wVirtualKeyCode = VK_CONTROL)
2. 'H' key pressed (.bKeyDown = TRUE, .wVirtualKeyCode = 'H')
3. 'H' key released (.bKeyDown = FALSE, .wVirtualKeyCode = 'H')
4. Ctrl key released (.bKeyDown = FALSE, .wVirtualKeyCode = VK_CONTROL)
- Actual results (with terminal output if applicable)

The program receives only three input events:
1. Ctrl key pressed (.bKeyDown = TRUE, .wVirtualKeyCode = VK_CONTROL)
2. 'H' key pressed (.bKeyDown = TRUE, .wVirtualKeyCode = 'H')
3. Missing event here
4. Ctrl key released (.bKeyDown = FALSE, .wVirtualKeyCode = VK_CONTROL)
- Your Windows build number

14393, 14942

**Comment by sunilmut** [comment]
@zadjii-msft @miniksa for specific guidance.
@rossy - Is this issue related to WSL (Windows Subsystem for Linux) or the "bash on Windows" feature? This git hub is reserved for that purpose.

**Comment by rossy** [comment]
Ah sorry, I don't think this issue affects WSL directly because I don't think Linux ptys have a concept of key-up events. Still, I got the impression that issues with the console can be posted to this issue tracker as well (there are a number of non-WSL-specific issues with the 'console' tag.) If this is not the case, I'm not sure where to report this.

**Comment by sunilmut** [comment]
@bitcrazed to see if he can guide you to a better place to report console related issues.

**Comment by zadjii-msft** [comment]
@rossy There are quite a bit of console related issues on here, mainly because of how big a role the console plays in a lot of this WSL stuff. Though, this does bring up a pretty good point that's been bouncing around recently on here - there's not a great forum for console specific issues or comments. @bitcrazed and the rest of the team are discussing some options.

For the time being, I opened MSFT:9311951 to track this internally

**Comment by rossy** [comment]
@zadjii-msft Thanks for looking into this and sorry again if I posted it in the wrong spot.

**Comment by bitcrazed** [comment]
@rossy Thanks for reporting this issue. 

Please bear with us just a little while longer - we're working on a place for Console-specific issues to be reported. 

Until then, please file issues here: Once we've got something sorted, we'll move this issue over to our new home.

**Comment by zadjii-msft** [comment]
@rossy I've been playing around with this today, and I can't seem to repro your behavior.

I've been using the following code to try and debug:
```C++
// System headers
#include <windows.h>

// Standard library C-style
#include <wchar.h>
#include <stdlib.h>
#include <stdio.h>

int __cdecl wmain(int argc, WCHAR* argv[])
{
    UNREFERENCED_PARAMETER(argc);
    UNREFERENCED_PARAMETER(argv);

    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    HANDLE hIn = GetStdHandle(STD_INPUT_HANDLE);

    DWORD dwOutMode = 0;
    DWORD dwInMode = 0;

    GetConsoleMode(hOut, &dwOutMode);
    GetConsoleMode(hIn, &dwInMode);

    // dwOutMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING | DISABLE_NEWLINE_AUTO_RETURN;
    // dwInMode |= ENABLE_VIRTUAL_TERMINAL_INPUT;

    SetConsoleMode(hOut, dwOutMode);
    SetConsoleMode(hIn, dwInMode);

    
    for (;;)
    {
        INPUT_RECORD rc;
        DWORD dwRead = 0;
        ReadConsoleInputW(hIn, &rc, 1, &dwRead);

        switch (rc.EventType)
        {
        case KEY_EVENT:
        {
            wprintf(L"Down: %d Repeat: %d KeyCode: 0x%x ScanCode: 0x%x Char: %c (0x%x) KeyState: 0x%x\r\n",
                    rc.Event.KeyEvent.bKeyDown,
                    rc.Event.KeyEvent.wRepeatCount,
                    rc.Event.KeyEvent.wVirtualKeyCode,
                    rc.Event.KeyEvent.wVirtualScanCode,
                    rc.Event.KeyEvent.uChar.UnicodeChar,
                    rc.Event.KeyEvent.uChar.UnicodeChar,
                    rc.Event.KeyEvent.dwControlKeyState);

            break;
        }
        }
    }
}
```

And playing around with the console modes and switching between `ReadConsoleA` with `...uChar.AsciiChar` and `ReadConsoleW` with `...uChar.UnicodeChar`.

My output for Ctrl+H Looks like this:
```
C:\conechokey.exe
Down: 1 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char:   (0x0) KeyState: 0x28
Down: 1 Repeat: 1 KeyCode: 0x48 ScanCode: 0x23 Char: (0x8) KeyState: 0x28
Down: 0 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char:   (0x0) KeyState: 0x20
Down: 0 Repeat: 1 KeyCode: 0x48 ScanCode: 0x23 Char: h (0x68) KeyState: 0x20
```
Here you can see the Ctrl+H event as 0x8 = backspace, which is pretty standard behavior (eg, Ctrl+[ -> ESC 0x1b)
**What input/output modes are you setting specifically?** Because those definitely affect the I/O.

**Comment by rossy** [comment]
@zadjii-msft Yeah, I was using something similar to debug with ReadConsoleInputW: https://gist.github.com/rossy/ca9f646c09b38e4d55e4db902f0d082e

> My output for Ctrl+H Looks like this:

That sequence of input events is slightly different to the one I was testing with. This bug only seems to happen if 'H' is released while Ctrl is down, so the sequence of events I was using was Ctrl-down H-down H-up Ctrl-up, rather than Ctrl-down H-down Ctrl-up H-up.

The reason I'm worried about these events in particular is because I'm trying to improve the console input handling in [mpv][1], which uses Ctrl and Shift as modifiers for the seek commands (on the arrow keys and PgUp/PgDn,) so a user could be expected to keep Ctrl held down while seeking around with the arrow keys and in that case, mpv won't receive the "up" events.

> What input/output modes are you setting specifically? Because those definitely affect the I/O.

I didn't think of changing the console mode, so when I was testing I guess it was set to whatever cmd.exe sets it to by default. I don't think this includes ENABLE_VIRTUAL_TERMINAL_INPUT.

[1]: https://github.com/mpv-player/mpv

**Comment by zadjii-msft** [comment]
Ah, would you look at that. That does seem to skip the key up event. I'll poke around some more, see what's happening.

ENABLE_VIRTUAL_TERMINAL_INPUT is largely irrelevant in this case, I was using that snippet to test VT input cases before, and accidentally left that in ¯\\\_(ツ)\_/¯

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
