### ISSUE TITLE
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system

### ISSUE THREAD

**Issue by Smart-Yanmeng** [microsoft/WSL#11888]
Hi, I encountered a problem while configuring nvidia.
My Windows run `nviddia-smi` correctly, but it failed in my WSL2, here are the results.

## Windows: 
![image](https://github.com/user-attachments/assets/0b0ce9bd-2297-4833-b34b-3bc37d3d6126)

## WSL2: 
![image](https://github.com/user-attachments/assets/5ca8c7e2-0bb2-4ffb-944a-77a514b7132c)

## `ldd  -v /usr/lib/wsl/lib/nvidia-smi`: 
![image](https://github.com/user-attachments/assets/89533642-e6cc-4da4-8b16-524dd2eaa5d4)

## Version of WSL2: 
![image](https://github.com/user-attachments/assets/bfba0b56-16d9-4d1d-8768-493a54f68c3b)

Have somebody met this problem? Please help me, thank you very much!

**Comment by Smart-Yanmeng** [comment]
I tried to install the nvidia-cuda-toolkit with `sudo apt install nvidia-cuda-toolkit`, and it give the wrong:
```
(base) york@MARGUERITE:~$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Comment by aalex1945** [comment]
最后你是怎么解决的呢 @Smart-Yanmeng

**Comment by Smart-Yanmeng** [comment]
@aalex1945 有点忘记了，好像修改了部分软链接，按照常理来说，重新下的话就不会出这个问题，记得要删干净
