### ISSUE TITLE
Wsl/ERROR_SERVICE_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by arundelo** [microsoft/WSL#11882]
### Windows Version

Microsoft Windows [Version 10.0.19045.4651]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. Run a `cmd` prompt as administrator.
2. `wsl --status`

### Expected Behavior

A display of the status of Windows Subsystem for Linux.

### Actual Behavior

Sixty seconds pass, then this error is printed:

```
The specified service does not exist as an installed service.
Error code: Wsl/ERROR_SERVICE_DOES_NOT_EXIST
```

This also happens if I run it in a regular (non-administrator) `cmd` prompt and it happens with most `wsl` commands, for example:

```
wsl
```

```
wsl -l -v
```

It does not happen with `wsl --help` (which prints a help message right away).

### Diagnostic Logs

I ran the [`collect-wsl-logs.ps1` script](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an admin PowerShell and ran `wsl --status` (in an admin `cmd` window) while `collect-wsl-logs.ps1` was running. It said:

```
Get-WindowsOptionalFeature : Access is denied.
At C:\Users\AaronBrown.MACALLISTER\collect-wsl-logs.ps1:56 char:1
+ Get-WindowsOptionalFeature -Online > $folder/optional-components.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

Log collection failed to start (exit code: -2147024891), trying to reset it.
Couldn't start log collection (exitCode: -2147024891)
Log collection is running. Please reproduce the problem and once done press any key to save the logs.
Saving logs...
Logs saved in: C:\Users\AaronBrown.MACALLISTER\WslLogs-2024-08-05_16-35-22.zip. Please attach that file to the GitHub issue.
```

Here is that file:

[WslLogs-2024-08-05_16-35-22.zip](https://github.com/user-attachments/files/16502650/WslLogs-2024-08-05_16-35-22.zip)

**Comment by markmungaidrezz** [comment]
[WslLogs-2024-08-05_16-35-22.zip](https://github.com/user-attachments/files/16502650/WslLogs-2024-08-05_16-35-22.zip) does anyone know how to fix this issue

**Comment by markmungaidrezz** [comment]
The specified service does not exist as an installed service.
Error code: Wsl/ERROR_SERVICE_DOES_NOT_EXIST
i have the same issue can anyone help me

**Comment by arundelo** [comment]
I've looked at the similar issues. In particular, I've tried:

- various versions of uninstalling and reinstalling as in [#8446](https://github.com/microsoft/WSL/issues/8446), [#10779](https://github.com/microsoft/WSL/issues/10779), and [#11757](https://github.com/microsoft/WSL/issues/11757)
- the workaround of [right clicking on `wsl.exe` and running as administrator](https://github.com/microsoft/WSL/issues/10475#issuecomment-1720105686) as in [#11882](https://github.com/microsoft/WSL/issues/11882)

No success.

The error message says that the service does not exist. As far as I know, the important service is "LxssManager". I have ensured that LxssManager is running (and has a startup type of "Automatic") in the Services control panel. Is there some other service I should check?

It's possible my computer has a weird permissions setup that is causing trouble. (For example, as shown above, when I ran `collect-wsl-logs.ps1` it said, "Get-WindowsOptionalFeature : Access is denied" even though I opened the PowerShell window with "Run as administrator".)

**Comment by markmungaidrezz** [comment]
how can i solve my issue
please

**Comment by arundelo** [comment]
Inspired by [this Super User dot com answer](https://superuser.com/a/1725630), I tried removing my `C:\Windows\System32\Tasks\Microsoft\Windows\Windows Subsystem For Linux` directory and reinstalling WSL.

***It did not work.*** But for what it's worth here are the details:

I renamed

`C:\Windows\System32\Tasks\Microsoft\Windows\Windows Subsystem For Linux`

to

`C:\Windows\System32\Tasks\Microsoft\Windows\Windows Subsystem For Linux.bak`

(This folder was empty anyway.)

I went to the Windows features control panel, unchecked "Windows Subsystem for Linux", and rebooted.

I ran `wsl --status` in an admin command prompt. It said:

```
This application requires the Windows Subsystem for Linux Optional Component.
Install it by running: wsl.exe --install --no-distribution
The system may need to be restarted so the changes can take effect.
Error code: Wsl/WSL_E_WSL_OPTIONAL_COMPONENT_REQUIRED
```

I ran

```
wsl.exe --install --no-distribution
```

It said:

```
The requested operation requires elevation.
Installing Windows optional component: Microsoft-Windows-Subsystem-Linux

Deployment Image Servicing and Management tool
Version: 10.0.19041.3636

Image Version: 10.0.19045.4651

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
The requested operation is successful. Changes will not be effective until the system is rebooted.
The requested operation is successful. Changes will not be effective until the system is rebooted.
```

I rebooted then ran `wsl --status`. It did the same as before (60 seconds then "Wsl/ERROR_SERVICE_DOES_NOT_EXIST").

I looked in the Services control panel and found that LxssManager was not running and its startup type was set to "Manual". I started it and ran `wsl --status` again but still got the same result.

* * *

Another weird permissions thing—when I tried to set LxssManager's startup type to "Automatic" I got "Access is denied", even when running the Services control panel as administrator. I was, however, able to change it by

1. running RegEdit as administrator

2. going to `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\LxssManager`

3. and changing "Start" from "3" to "2".

* * *

For the record, this reinstall ***did not*** recreate the `C:\Windows\System32\Tasks\Microsoft\Windows\Windows Subsystem For Linux` directory.

**Comment by arundelo** [comment]
Thanks @OneBlue. Today I did the following:

1.  Went to the Windows features control panel, unchecked "Windows Subsystem for Linux", verified that the "Hyper-V" stuff was unchecked, and rebooted.
2.  Downloaded and ran [wsl.2.3.14.0.x64.msi](https://github.com/microsoft/WSL/releases/download/2.3.14/wsl.2.3.14.0.x64.msi).

It gave me a "Confirm Execution" dialog box which I said "Yes" to. Then the installer ran but it stopped with the error: "The older version of Windows Subsystem for Linux cannot be removed. Contact your technical support group."

This is a work computer so I'm going to ask my company's helpdesk for help but I would like to keep this issue open for a little longer in case they have trouble solving the problem.

**Comment by OneBlue** [comment]
Thank you @arundelo. Let's collect MSI logs to see what's causing this. Can you run: 

```
msiexec /i <msi> /L*V C:\wsllogs.txt
```

As administrator, and share the resulting `C:\wsllogs.txt` once complete ?

**Comment by arundelo** [comment]
@OneBlue, here it is:

[wsllogs.txt](https://github.com/user-attachments/files/16604421/wsllogs.txt)

**Comment by arundelo** [comment]
@OneBlue, for what it's worth, `C:\WINDOWS\Installer\4f934.msi` is a binary file of about 135 megabytes. The timestamp is from a day a couple months ago when I installed Docker, got a bluescreen during the install, ran `wsl --install` (which gave me "Error: 0x80070424 The specified service does not exist as an installed service"), and uninstalled and reinstalled Docker.

I'll try the troubleshooter at the link you gave, thanks.

**Comment by arundelo** [comment]
@OneBlue, I believe the troubleshooter worked! I told it I was trying to uninstall WSL, it said it fixed the problem, then I was able to reinstall WSL.

A co-worker of mine pushed some security policy changes to my computer about the same time so it's also possible that had to do with it.

Now when I run `wsl --status` I immediately get "Default Version: 2". Thanks.

**Comment by centur** [comment]
Very similar problem after the recent Windows security updates
Latest installer gives:  
![Image](https://github.com/user-attachments/assets/d635cc64-22f3-4927-91b9-303c2a7157db)

**Comment by tjhowse** [comment]
@arundelo Thanks for keeping this thread up-to-date. Your most recent message solved the problem for me too. I had the same error string in the MSI install log:

```
DEBUG: Error 2203:  Database: . Cannot open database file. System error 
1: 2203 2:  3:  4:  
This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package.
C:\Windows\Installer\1f91ebac.msi
CustomAction  returned actual error code 1620 (note this may not be 100% accurate if translation happened inside sandbox)
```

The solution I followed was:

1) Download this "troubleshooter" https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d
2) Run it and tell it you're having trouble UNINSTALLING windows subsystem for linux.
3) Let it finish.
4) Download and run https://github.com/microsoft/WSL/releases/download/2.5.9/wsl.2.5.9.0.x64.msi [at time of writing]

**Comment by neilt1700** [comment]
I had this same problem following a Windows Update. The solution was simple though - I downloaded the latest release from https://github.com/microsoft/WSL/releases and ran that installer.
