### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80040321

### ISSUE THREAD

**Issue by Aroken** [microsoft/WSL#11894]
### Windows Version

Microsoft Windows [Version 10.0.20348.2582]

### WSL Version

WSL version: 2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Comand:
wsl --status

Result: 
This application requires the Windows Subsystem for Linux Optional Component.
Install it by running: wsl.exe --install --no-distribution
The system may need to be restarted so the changes can take effect.
Error code: Wsl/WSL_E_WSL_OPTIONAL_COMPONENT_REQUIRED

Comand:
 wsl --install

Result:
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80040321
Error: 0x80040321 (null)
Press any key to continue...

### Expected Behavior

Ubuntu

### Actual Behavior

WslRegisterDistribution failed with error: 0x80040321
Error: 0x80040321 (null)

### Diagnostic Logs

[WslLogs-2024-08-07_17-54-56.zip](https://github.com/user-attachments/files/16532496/WslLogs-2024-08-07_17-54-56.zip)
[WslLogs-2024-08-07_18-02-59.zip](https://github.com/user-attachments/files/16532497/WslLogs-2024-08-07_18-02-59.zip)

**Comment by Aroken** [comment]
I have Not found solution in similar issues

**Comment by Aroken** [comment]
I have Not found solution in similar issues.



I found the problem. The WSL service must only be started as Local System, not by a specific username.

Now looking for a way to run WSL with Ubuntu after the signal out.

**Comment by OneBlue** [comment]
@Aroken: Does that mean that you changed the configuration of WslService to run as a local user ? If so this is expected, since that service indeed needs to run as system.

**Comment by Nutanraju143** [comment]
how to fix the issue?

**Comment by GuiGuii28** [comment]
Error: 0x80040321 (null)

Como se puede solucionar????
