### ISSUE TITLE
Mirrored networking mode is not supported, falling back to NAT networking

### ISSUE THREAD

**Issue by trite2k3** [microsoft/WSL#11899]
### Windows Version

Microsoft Windows [Version 22631.3007]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 24.04

### Other Software

-

### Repro Steps

[boot]
systemd=true
autoProxy=true

### Expected Behavior

Network works.

### Actual Behavior

Network doesnt work, connection timed out.

**Comment by trite2k3** [comment]
I cannot provide logs since I do not have administrator priviliges.

**Comment by OneBlue** [comment]
Unfortunately without logs we can't investigate the issue. Closing for now. Feel free to reopen if you can collect logs.
