### ISSUE TITLE
Missing WSL Blobs for openSUSE Leap 15.5

### ISSUE THREAD

**Issue by henriqueccapozzi** [microsoft/WSL#11902]
Hi,

The links for the Leap 15.5 distribution is missing from here:
https://docs.microsoft.com/he-il/windows/wsl/install-manual#downloading-distributions

Manual reconstructions of the links do not work:

https://aka.ms/wsl-opensuseleap15-5

**Comment by henriqueccapozzi** [comment]
/feature

For this specific request I don't think that logs are required

**Comment by sbradnick** [comment]
I don't personally know what the update/upkeep/lifespan is for that site, but I wouldn't bother doing anything for Leap 15.4, the current offerings in the Store (or via winget) are Leap 15.5 & Leap 15.6 ; [--web-download](https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json#L104) offers Leap 15.6.

**Comment by henriqueccapozzi** [comment]
Hi @sbradnick I found it available on the store but when I try to install it from powershell it show as if the distribution doesn't exists

**Comment by sbradnick** [comment]
> Hi I found it available on the store but when I try to install it from powershell it show as if the distribution doesn't exists

You'll have to be more specific (with what you're doing) than that, Leap 15.4 isn't available from the Store anymore since it's EOL.

**Comment by henriqueccapozzi** [comment]
I overlooked that Leap 15.4 was EOL, no need to worry about it indeed
I'll update the issue description

Since Leap 15.5 is available at the store shouldn't the following command work?

![image](https://github.com/user-attachments/assets/69f2e718-b17e-4f5f-a08c-3db85a21ccb3)

Text translated to english

```
PS C:\WINDOWS\system32> wsl --install openSUSE-Leap-15.5
Invalid distribution name: ‘openSUSE-Leap-15.5’.
To get a list of valid distributions, use ‘wsl.exe --list --online’.
Error code: Wsl/InstallDistro/WSL_E_DISTRO_NOT_FOUND
```


Here's the list of available distribution returned by the suggested command

```
PS C:\WINDOWS\system32> wsl --list --online
Veja a seguir uma lista de distribuições válidas que podem ser instaladas.
Instale usando 'wsl.exe --install <Distro>'.

NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
Ubuntu-24.04                           Ubuntu 24.04 LTS
OracleLinux_7_9                        Oracle Linux 7.9
OracleLinux_8_7                        Oracle Linux 8.7
OracleLinux_9_1                        Oracle Linux 9.1
openSUSE-Leap-15.6                     openSUSE Leap 15.6
SUSE-Linux-Enterprise-15-SP5           SUSE Linux Enterprise 15 SP5
SUSE-Linux-Enterprise-Server-15-SP6    SUSE Linux Enterprise Server 15 SP6
openSUSE-Tumbleweed                    openSUSE Tumbleweed
PS C:\WINDOWS\system32>
```

**Comment by sbradnick** [comment]
openSUSE-Leap-15.5 isn't available that way (there's a 4-item limit); that list is the one you'd use like so: `wsl --install openSUSE-Leap-15.6 --web-download` (you can probably leave `--web-download` off unless there is a proxy issue w/o it (no access to the Store for example), depends on your network). 

The Store offers up 15.5 and you can use winget if you'd like to install it via the CLI.

I'm not 100% what you're trying to accomplish, if it's having 'openSUSE Leap 15.5' installed, it's certainly possible via the Store.

**Comment by henriqueccapozzi** [comment]
Closing
