### ISSUE TITLE
/mnt/z network driver mapped

### ISSUE THREAD

**Issue by aleppos** [Microsoft/WSL#1190]
when list drivers in folder mnt I can't find the mapped drivers in windows.
- Expected results
  root@EMAD2:/mnt# ls
  c x z
- Actual results (with terminal output if applicable)
  root@EMAD2:/mnt# ls
  c

**Comment by wizardist** [comment]
SMB would solve your problem but unfortunately there's #764.

**Comment by fpqc** [comment]
bydesign for now.

**Comment by benhillis** [comment]
Support for network drives was added in 16176, although they will not appear automatically.

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/
