### ISSUE TITLE
Add a configuration setting to suppress error messages

### ISSUE THREAD

**Issue by mataha** [microsoft/WSL#11919]
**Is your feature request related to a problem? Please describe.**

I share my dotfiles across several platforms, Windows 10 and 11 included. Among them is `.wslconfig` with several options that work only on Windows 11 (e.g. nested virtualization, DNS tunneling); and so, whenever I turn on WSL, I see the following (translated):

```cmd
> wsl
wsl: Nested virtualization is not supported on this machine.
wsl: DNS tunneling is not supported
user@wsl:/c/Users/user$
```

I'm perfectly aware, and I'd prefer to not be reminded every time as it's distracting (*especially* when the reminder is a native notification).

**Describe the solution you'd like**

A configuration setting that, upon starting WSL, would suppress both errors on the command line (if run through a terminal) and native notifications, similar to `--quiet`/`--silent` found in many CLI utilities. Something along those lines would be preferable:

```
# ~/.wslconfig
[wsl2]
silent = true
```

**Describe alternatives you've considered**

 - `wsl 2>nul` - suppresses all output.
 - Turning off WSL notification sender in Notifications & Actions - has no observable effect.

**Additional context**

```cmd
> ver
Microsoft Windows [Version 10.0.19045.4651]
```

/feature

**Comment by OneBlue** [comment]
@mataha: This can be done by exporting `set WSL_DISABLE_WARNINGS=1`. We can't have that in .wslconfig because warnings can be emitted during parsing. 

Closing since this can be done via an env variable.

**Comment by mataha** [comment]
That solves my problem, thanks. Is that variable documented anywhere? This is the first time I'm hearing about it.
