### ISSUE TITLE
git pull takes a long time; was fixed by turning off ipv6 using GIT_SSH_COMMAND="ssh -4"

### ISSUE THREAD

**Issue by jcrben** [microsoft/WSL#11916]
### Windows Version

Windows 11 10.0.22631.3880 (23H2)

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

### Distro Version

Ubuntu-22.04

### Repro Steps

Steps to Reproduce:

First off: I'm having trouble reliably reproducing this today. It was happening to me last night running ipv6 on WSL2 and fixed by disabling ipv6 - but today it's not happening even tho I'm connecting via ipv6 - and I'm confirming that ipv6 is being used via strace output like `271412 getsockname(3, {sa_family=AF_INET6, sin6_port=htons(60766), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "2601:648:8200:1c40::756b", &sin6_addr), sin6_scope_id=0}, [128 => 28]) = 0` (altho keep in mind I might be incorrectly reading these things).

Not using a vpn - this is my personal machine where I don't need to use a vpn.

This is my `~/.wslconfig`:

```
[wsl2]
networkingMode=mirrored
```

My `/etc/resolv.conf`:

```
[boot]
systemd=true

[interop]
appendWindowsPath = false

[network]
generateResolvConf=false
```

1. Clone down a repo which can you pull from - mine is a pretty repo in gitlab
3. Run git pull
4. notice it takes a long time - over a minute
5. `GIT_SSH_COMMAND="ssh -4" git pull` returns as fast as expected

I turned off ipv6 because I noticed it was doing an ipv6 connection when I ran `strace -v -s 1000 -f -o strace_output.txt git pull` and then `tail -f strace_output.txt` in another terminal.

I had previously not noticed this lag issue because I had included `kernelCommandLine=ipv6.disable=1` at someone's suggestion. But I recently discovered that this configuration was breaking docker desktop integration with my wsl2 ubuntu instance (see https://github.com/docker/for-win/issues/13707#issuecomment-2246778890).

References:
* [[WSL 2] Hangs forever on most network calls (like curl, git, etc.) #8358](https://github.com/microsoft/WSL/issues/8358) - mine was not hanging forever, but seems similar in that people report disabling ipv6 helps
* [WSL2 git is slow from gitlab #6602](https://github.com/microsoft/WSL/issues/6602) - focused more on dns causes; this doesn't seem to be what was happening here
* [Git pull hangs forever #985](https://github.com/microsoft/vscode-remote-release/issues/985) - different issue/cause
* https://github.com/microsoft/vscode/issues/225344 (accidentally misfiled) - triggering a link to here on that issue

### Expected Behavior

`git pull` should return the update or `Already up to date.` fairly quickly (not more than a couple seconds)

### Actual Behavior

`git pull` takes a while to return

**Comment by jcrben** [comment]
closing for now as I've had trouble replicating

**Comment by jcrben** [comment]
Reopening this as I just hit this again in another case - the vscode wsl server update which runs when you run `code` on wsl.

Attaching the logs - @OneBlue I'm hoping this is more complete than your average issue report.  Let me know if there's anything I can add.

Reproduction steps - `~/.wslconfig`  and `/etc/wsl.conf` are the same as above.

Open WSL and run `code .` - see that it hangs - strace shows that it is using ipv6 
![image](https://github.com/user-attachments/assets/0d52ff3b-fe91-4a10-9436-4fbb4748cae9)

Hangs for as long as I was willing to wait.

Disable ipv6 - I edited `/etc/gai.conf` and uncommented the `precedence ::ffff:0:0/96  100` line.

Rerun `code` and notice that it works now.

[WslLogs-2024-08-11_22-34-29.zip](https://github.com/user-attachments/files/16577731/WslLogs-2024-08-11_22-34-29.zip)
[WslNetworkingLogs-2024-08-11_22-41-55.zip](https://github.com/user-attachments/files/16577765/WslNetworkingLogs-2024-08-11_22-41-55.zip)

**Comment by CatalinFetoiu** [comment]
@jcrben thanks for reporting the issue and attaching the logs and the strace output

the logs show that the IP you are trying to connect to at port 443, 2620:1ec:bdf::69 was resolved by DNS server 8.8.4.4

I also see that your host machine only has local IPv6 connectivity, it does not have global IPv6 connectivity, which leads to connecting to global IPv6 address 2620:1ec:bdf::69 to fail

what mechanism are you using to resolve names at 8.8.4.4? I see in the /etc/resolv.conf file you have 10.255.255.254 as nameserver, which means you have DNS tunneling successfully enabled

I recommend no longer resolving names at 8.8.4.4 and instead using DNS tunneling.

this will ensure the names are resolved using the host DNS resolver, which should resolve names to IPv4 addresses (because it knows the machine does not have global IPv6 connectivity), then Linux will connect over IPv4 which should just work

**Comment by fractal80y** [comment]
Don't want to add irrelavant info. However faced same observed functioning behavior in WSL. I had ended up changing Port entry previously in /etc/ssh/ssh_config file, returning it back to 22 solved my case. Same outcome but most likely a different RC in amongst network config.

**Comment by jcrben** [comment]
@CatalinFetoiu in this case I did not have a working ipv6 connection. Thanks for digging in, you can close this
