### ISSUE TITLE
lm-sensors

### ISSUE THREAD

**Issue by rmkimathi** [Microsoft/WSL#1191]
- A brief description
  Sensors not working
- Expected results
  cpu temperature
- Actual results (with terminal output if applicable)
  sensors_init: Kernel interface error
- Your Windows build number
  14393
- Steps / All commands required to reproduce the error from a brand new installation 
  sudo apt-get install lm-sensors
  sensors
- Strace of the failing command
  sensors
- Required packages and commands to install
  lm-sensors

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@rmkimathi Thanks for your feedback and trying out WSL! Unfortunately, currently WSL does not support access to hardware devices/sensors etc. If you would like to see support for such, please help us prioritize by providing this feedback through our [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/filters/top), which we regularly look at. For example, see a [related post](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13355724-unable-to-access-usb-devices-from-bash) about accessing USB devices through WSL.

**Comment by rmkimathi** [comment]
Thank you sunilmut ...

**Comment by tara-raj** [comment]
Closing this issue as it's currently stale. Please refer above to the User Voice page [as mentioned by @sunilmut](https://github.com/Microsoft/WSL/issues/1191#issuecomment-253080970) to provide feedback on hardware device/sensor access.

**Comment by suryaprakaz** [comment]
Is there any plan for this feature to be implemented in WSL2? With all the close integration that we've seen, it would be great to see this included as many devs are driving WSL2 for their day2day, being able to monitor CPU temps through terminal would be great.

**Comment by JacopoBonta** [comment]
<img width="496" alt="Screenshot 2022-06-27 at 12 02 18" src="https://user-images.githubusercontent.com/9072396/175916590-a92ae656-166c-4d8b-9812-1776c5a01b1f.png">

The forum provided by @sunilmut is no longer available. There is any other place where I can follow the progress for this issue?

**Comment by asadMarmash** [comment]
I am kind of interested in this issue too, and the uservoice page is a 404.

**Comment by theoparis** [comment]
Any updates on this 😕

**Comment by Saya47** [comment]
uhh hello?

**Comment by renfrow** [comment]
I would like lm-sensors to work in wsl2 also!

**Comment by Jhgomez** [comment]
I would also like to have sensors in WSL2
