### ISSUE TITLE
tensorflow  matplotlib cann't work

### ISSUE THREAD

**Issue by luyahan** [Microsoft/WSL#1192]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
- Expected results
- Actual results (with terminal output if applicable)
- Your Windows build number
- Steps / All commands required to reproduce the error from a brand new installation 
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Can you please provide some additional information by filling out the above template?

**Comment by tara-raj** [comment]
Links to this issue - https://github.com/Microsoft/WSL/issues/1788 #1788
