### ISSUE TITLE
Docker dead after latest Kernel

### ISSUE THREAD

**Issue by SirLouen** [microsoft/WSL#11957]
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

2.3.17.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.6

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop: 4.33.1

### Repro Steps

1. Compile the latest WSL kernel 
https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.6.36.3
Steps to compile:
1.1 Download the WSL2-Linux-Kernel
1.2 Extract and copy the config file attached as .config in the Kernel source files [config-6.6.36.3.txt](https://github.com/user-attachments/files/16738087/config-6.6.36.3.txt)
1.3 Run commands:
```
make prepare modules_prepare -j $(expr $(nproc) - 1)
make modules -j $(expr $(nproc) - 1)
sudo make modules_install
make -j $(expr $(nproc) - 1)
sudo make install
```

2. Then copy the `vmlinux` in a place where Windows host can read it

3. Add the file it to the `.wslconfig` to run WSL with it
```
[wsl2]
kernel=C:\\Users\\user\\vmlinux
```

4. Shutdown wsl with `wsl --shutdown` to refresh with the new Kernel

5. Start a fresh installation of Docker Desktop

### Expected Behavior

Docker Desktop should run

### Actual Behavior

Throws an error, and an endless loop trying to update WSL. In the video, the administrative escalation prompt doesn't show up, but can be heard each time it pops:

https://github.com/user-attachments/assets/ce7e635a-0d30-44ab-9c80-3a8d16ae2f82

With the same WSL version, Docker Desktop version, and everything identical, if I use the standard Kernel 5.15.153.1, everything works well. But as soon I change to the new 6.6.36.6 Kernel, Docker Desktop breaks.

### Diagnostic Logs

More info can be found here.
https://github.com/docker/for-win/issues/14282

Problem here is that I'm not sure if its an issue with Docker Desktop or WSL Kernel, and since this is the issue tracker for WSL2-Linux-Kernel repo, I had to also post this here.

**Comment by SirLouen** [comment]
Some logs 
[WslLogs-2024-08-25_02-37-41.zip](https://github.com/user-attachments/files/16738458/WslLogs-2024-08-25_02-37-41.zip)

**Comment by SirLouen** [comment]
After all the evening thrown to the bin, installing, uninstalling, and testing dozens of versions of WSL & Docker Desktop, I've finally discovered the issue:

For some stupid reason WSL 2.3.17.0 DOWNGRADES default Kernel version to 5.15.153.1, because WSL 2.3.14.0 has, by default Kernel  6.6.36.3-1. Why? **Noone knows.**

So basically, I downgraded to WSL 2.3.14.0 and now everything is working well again. 

**I'm going to leave this open, because I think that the big bug here is that WSL 2.3.17.0 is being shipped with a 5.15 Kernel**

**Comment by elsaco** [comment]
@SirLouen the reason for switching back to `kernel-5.15.153.1` is spelled in the release notes:

`Revert Linux kernel to 5.15.153.1-2 while issues are being debugged`

So, now you know!

**Comment by SirLouen** [comment]
> @SirLouen the reason for switching back to `kernel-5.15.153.1` is spelled in the release notes:
> 
> `Revert Linux kernel to 5.15.153.1-2 while issues are being debugged`
> 
> So, now you know!

I can't believe I read release notes for Docker and WSL-Kernels but not for WSL itself. A massive amount of time hitting my head with the wall just for this nuance.
