### ISSUE TITLE
 wsl.exe --install Ubuntu. Error code: Wsl/InstallDistro/E_ACCESSDENIED

### ISSUE THREAD

**Issue by jeanmarieminani** [microsoft/WSL#11976]
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.153.1-2

### Repro Steps

 wsl.exe --install Ubuntu

### Expected Behavior

wsl.exe --install <Distro>
At line:1 char:19
+ wsl.exe --install <Distro>
+                   ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

### Actual Behavior

wsl.exe --install Ubuntu, Access is denied. =========90.0%=====================      ] Error code: Wsl/InstallDistro/E_ACCESSDENIED

**Comment by Ayula96** [comment]
wsl 2
