### ISSUE TITLE
(Question) How can I capture `wsl --update` (and similar) progress information programmatically?

### ISSUE THREAD

**Issue by Nick-HP** [microsoft/WSL#11977]
When running `wsl --update` (or other commands that report progress) manually in a terminal without any redirection of output, a progress bar appears and shows the percent of the update completed.

I have tried to capture and/or redirect the output in many different ways while running `wsl --update`, but I cannot seem to get the progress info programmatically when I run it as a subprocess of my program. The progress information does not seem to appear in any redirected or piped output.

I want to run WSL commands automatically and report the progress given by the CLI to the user in my UI. I would appreciate any insights or tips on how this can be accomplished, or whether it is impossible.

**Comment by OneBlue** [comment]
@Nick-HP: The easiest way to do that would be to manually download and install the latest [MSI package](https://github.com/microsoft/WSL/releases/download/2.3.17/wsl.2.3.17.0.x64.msi).

You can use the [MSI API](https://learn.microsoft.com/en-us/windows/win32/api/msi/nf-msi-msiinstallproducta) to capture the installation progress.

See https://learn.microsoft.com/en-us/windows/win32/api/msi/nf-msi-msisetexternaluia .

Good luck !
