### ISSUE TITLE
CreateProcessEntryCommon:508: Create process not expected to return

### ISSUE THREAD

**Issue by lansman** [microsoft/WSL#11985]
### Windows Version

Microsoft Windows [Version 10.0.22631.4112]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

### Distro Version

Ubuntu 22.04

### Repro Steps

I'm trying to execute sh script by wsl
hello_world.sh
```
#!/usr/bin/env sh

echo Hello world!
```

```
C:\Users\my_user\my_dir>wsl -e hello_world.sh
<3>WSL (64252) ERROR: CreateProcessEntryCommon:505: execvpe hello_world.sh failed 2
<3>WSL (64252) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
```

Entering wsl and executing there works:
```
C:\Users\my_user\my_dir>wsl.exe
$ ./hello_world.sh
Hello world!
```

Also proper WSL is selected:
```
>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop
```

### Expected Behavior

Script should run

### Actual Behavior

Script doesn't run, error appears:
```
<3>WSL (64252) ERROR: CreateProcessEntryCommon:505: execvpe hello_world.sh failed 2
<3>WSL (64252) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
```

### Diagnostic Logs
[WslLogs-2024-09-01_22-27-15.zip](https://github.com/user-attachments/files/16829910/WslLogs-2024-09-01_22-27-15.zip)

_No response_

**Comment by lansman** [comment]
The problem is still here

**Comment by DHerrmannP** [comment]
> ### Windows Version
> Microsoft Windows [Version 10.0.22631.4112]
> 
> ### WSL Version
> 2.2.4.0
> 
> ### Are you using WSL 1 or WSL 2?
> * [x]  WSL 2
> * [ ]  WSL 1
> 
> ### Kernel Version
> Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024
> 
> ### Distro Version
> Ubuntu 22.04
> 
> ### Other Software
> _No response_
> 
> ### Repro Steps
> I'm trying to execute sh script by wsl hello_world.sh
> 
> ```
> #!/usr/bin/env sh
> 
> echo Hello world!
> ```
> 
> ```
> C:\Users\my_user\my_dir>wsl -e hello_world.sh
> <3>WSL (64252) ERROR: CreateProcessEntryCommon:505: execvpe hello_world.sh failed 2
> <3>WSL (64252) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
> ```
> 
> Entering wsl and executing there works:
> 
> ```
> C:\Users\my_user\my_dir>wsl.exe
> $ ./hello_world.sh
> Hello world!
> ```
> 
> Also proper WSL is selected:
> 
> ```
> >wsl -l
> Windows Subsystem for Linux Distributions:
> Ubuntu (Default)
> docker-desktop
> ```
> 
> ### Expected Behavior
> Script should run
> 
> ### Actual Behavior
> Script doesn't run, error appears:
> 
> ```
> <3>WSL (64252) ERROR: CreateProcessEntryCommon:505: execvpe hello_world.sh failed 2
> <3>WSL (64252) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
> ```
> 
> ### Diagnostic Logs
> [WslLogs-2024-09-01_22-27-15.zip](https://github.com/user-attachments/files/16829910/WslLogs-2024-09-01_22-27-15.zip)
> 
> _No response_

I also have this problem, have you managed to fix it?

**Comment by lansman** [comment]
@DHerrmannP no

**Comment by JovannyM** [comment]
I have the same issue!
