### ISSUE TITLE
All wsl commands return Wsl/CallMsi/Install/E_INVALIDARG

### ISSUE THREAD

**Issue by kvpbldsck** [microsoft/WSL#11988]
### Windows Version

Microsoft Windows [Version 10.0.22631.4112]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. Run wsl --install --web-download
2. Restart pc
3. Run wsl -v

This command, as far as any other, return:
```
parameter is incorrect.
Error code: Wsl/CallMsi/Install/E_INVALIDARG
```

Disabling/enabling wsl feature haven't helped

Maybe helpful information: before this problem I was trying to install Docker Desktop (4.34.0) and installation process stuck at the `deploying components: install docker cli plugins` stage

### Expected Behavior

wsl commands work fine

### Actual Behavior

wsl commands fail with message:
```
The parameter is incorrect.
Error code: Wsl/CallMsi/Install/E_INVALIDARG
```

### Diagnostic Logs

[WslLogs-2024-09-02_23-34-31.zip](https://github.com/user-attachments/files/16841413/WslLogs-2024-09-02_23-34-31.zip)

**Comment by OneBlue** [comment]
Thank you @kvpbldsck. 

Does manually installing [the latest MSI](https://github.com/microsoft/WSL/releases/download/2.3.17/wsl.2.3.17.0.x64.msi) solve the issue ?

**Comment by manuth** [comment]
I have the very same issue.
@OneBlue I can confirm that this workaround fixes the issue on my machine.
