### ISSUE TITLE
On Ubuntu-24.04 distro, `sudo chown $USER -R /mnt/c/Users/user/some_dir_created_under_previous_wsl1_distro_22.04` does not have any effect

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#11987]
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #3672-Microsoft Fri Jan 01 08:00:00 PST 2016

### Distro Version

Ubuntu 24.04

### Repro Steps

- I had previous WSLv1 distro: Ubuntu-22.04
- I had created various directories with files under `/mnt/c/Users/user/some_dir`
- I installed a new distro from Microsoft Store: Ubuntu 24.04 and `--set-version`'d it to WSLv1
- The user on the new distro is `vadimkantorov`
- I want to start using the new distro, so trying to modify these files on a new distro
- They get opened as reaonly, and `ls -lah` prints `ubuntu` as owner
- I tried doing `chown -R vadimkantorov /mnt/c/Users/user/some_dir`, but this has no effect and `ls` output is unchanged
- I deleted the old profile/distro, so I only care of how to make things work on the new distro

### Expected Behavior

There should be a way to `chown` files on NTFS file systems, to make them modifiable by the new user (without being forced to use `sudo`/`su` all the time). How to solve this properly?

### Actual Behavior

Cannot modify files on `/mnt/c/Users/user/some_dir` without `sudo`

**Comment by vadimkantorov** [comment]
So I added:
```toml
[automount]
options = "metadata"
```
to /etc/wsl.conf and after this chown worked

Still quite unintuitive :(

**Comment by OneBlue** [comment]
Thank you @vadimkantorov. That's indeed the right way to solve this. Closing since the issue was self resolved.

**Comment by vadimkantorov** [comment]
I think this mode option should be default for WSLv1. Especially given that Ubuntu 24.04 upgrade is broken, people would need to migrate from one distro (and set of users) to another (a new set of users). Chown should rather work as expected...
