### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/E_ACCESSDENIED

### ISSUE THREAD

**Issue by thastad** [microsoft/WSL#11980]
### Windows Version

Microsoft Windows [Version 10.0.26100.1591]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu

### Repro Steps

C:\Windows\System32>wsl.exe

### Expected Behavior

Wsl default distro is launched.

### Actual Behavior

Kan ikke konfigurere nettverk (networkingMode Nat). Hvis du vil deaktivere nettverk, angir duwsl2.networkingMode=None i C:\Users\trond\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/E_ACCESSDENIED

Error message is in norwegian but transelate to "can not configure network (networkingMode Nat) you can disable networking in .wslconfig"

Similar error message on every distro i try to start.
WSL was working a week ago and no configuration changes since then.

The system has been updated with "Win 11 version 24H2 KB5041865" and a HP bios update since last time wsl was working

### Diagnostic Logs

[WslLogs-2024-08-30_22-04-13.zip](https://github.com/user-attachments/files/16821742/WslLogs-2024-08-30_22-04-13.zip)

**Comment by maxboone** [comment]
+1, on arm64 with Version 24H2 (Build 26100.1591)

```
PS C:\Users\micro> wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.26100.1591
```

**Comment by maxboone** [comment]
For now, locally, I'm working around this by setting the following in my `.wslconfig`. 

Maybe it helps someone:
```
[wsl2]
networkingMode=mirrored
```

**Comment by martin-labsky** [comment]
Same issue here with the [exact same versions as above](https://github.com/microsoft/WSL/issues/11980#issuecomment-2324897989), and yes `networkingMode=mirrored` did fix it for me, thanks for the hint.

**Comment by maxboone** [comment]
@martin-labsky FYI, for me switching back to nat mode worked again after working on mirrored. Might be worth the attempt, as mirrored mode is still somewhat in beta.

**Comment by thastad** [comment]
@maxboone Switching to mirrored and back to nat did the trick for me to.
Thank you

**Comment by CatalinFetoiu** [comment]
@thastad , thanks for reporting the issue. can you please collecting networking logs using instructions at https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues ?

The script will create a zip with name starting with "WslNetworkingLogs"

**Comment by thastad** [comment]
@CatalinFetoiu logs attached
As you can see from the comments the issue is no longer present after creating `.wslconfig`  with `networkingMode=mirrored` run wsl and then switch back to `networkingMode=nat`

[WslNetworkingLogs-2024-09-06_22-42-51.zip](https://github.com/user-attachments/files/16912859/WslNetworkingLogs-2024-09-06_22-42-51.zip)

**Comment by HenryGessau** [comment]
Thanks @dingwen07! Restarting the Host Network Service (`HNS`) resolves the problem (temporarily) for me too.

The error code for this issue ends with `HNS/E_ACCESSDENIED`. I wonder if some recent Windows security patches have tightened access policies that affect WSL networking.

**Comment by simonknittel** [comment]
Switching between networkingModes did not help for me. However, restarting the Host Network Service (thanks @dingwen07) did it for me.

Starting WSL the first time after the restarting the service logs these messages:
```
wsl: Failed to create virtual network with address range: '172.23.112.0/20', created new network with range: '172.20.128.0/20', Zugriff verweigert
wsl: Failed to create network endpoint with address: '172.23.122.165', assigned new address: '172.20.139.89'
```
Not sure if that's normal or not.

**Comment by Mk-rbv** [comment]
I ran into this issue after updating from Windows 11 23H2 to Windows 11 24H2. Disabling "Virtual Machine Platform" in Windows features and then re-enabling it ended up fixing this issue for me.

Interestingly enough a new virtual network adapter appeared called "vEthernet (WSL (Hyper-V Firewall))" after I did this.

**Comment by Landmine-1252** [comment]
> I ran into this issue after updating from Windows 11 23H2 to Windows 11 24H2. Disabling "Virtual Machine Platform" in Windows features and then re-enabling it ended up fixing this issue for me.
> 
> Interestingly enough a new virtual network adapter appeared called "vEthernet (WSL (Hyper-V Firewall))" after I did this.

Thank you @Mk-rbv 

I had to disable both Virtual Machine Platform and Windows Hypervisor Platform, reboot, then enable again and reboot. WSL is working again.

![image](https://github.com/user-attachments/assets/41d724ce-8ae9-432c-a24f-d18a81b9badd)

**Comment by chetgurevitch** [comment]
Another case here after updating from 23H2 to 24H2, restarting the Host Network Service did not work for me. After disabling Virtual Machine Platform, rebooting, re-enabling it, and rebooting again WSL negotiated a new address in the reserved 172.16.0.0/12 block and things are back to working. 
`wsl: Failed to create network endpoint with address: '172.XX.XXX.XX', assigned new address: '172.XX.XXX.XXX'`
Windows Hypervisor Platform doesn't need to be enabled for WSL.

**Comment by akibanator** [comment]
Any chance the issue is related to Hyper-V? I disabled the option and the issue disappears.
![Screenshot 2024-10-05 212324](https://github.com/user-attachments/assets/818fce14-d2a7-4e67-a940-7df608533c92)
And renabled Hyper-V the issue appears again

**Comment by Sam-you-el** [comment]
<img width="960" alt="Screenshot 2024-10-06 170508" src="https://github.com/user-attachments/assets/39590770-b548-4bc2-9263-305353b6c4be">


 nothing is working for me to fix the ubuntu after the H24h2 upgrade, even my system restore to H23h2 ain't working to fix that issue. I need help!

**Comment by Sam-you-el** [comment]
> Any chance the issue is related to Hyper-V? If I disable the option, the issue disappears. ![Screenshot 2024-10-05 212324](https://private-user-images.githubusercontent.com/16294766/373914390-818fce14-d2a7-4e67-a940-7df608533c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTM5MzQsIm5iZiI6MTcyODIxMzYzNCwicGF0aCI6Ii8xNjI5NDc2Ni8zNzM5MTQzOTAtODE4ZmNlMTQtZDJhNy00ZTY3LWE5NDAtN2RmNjA4NTMzYzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDExMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MmVkODRiZGIyYzNmYWRkNGJjZDNmZWU2NGM3NmVjMmZmNzA2OGJkYjI1NzUyMWUyNWE1YTJjMWM2YWE3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ekk8ck2jNKJ9TYLPO4XomCQjGCGtTxJDSP3JJmFEvhM) And renable Hyper-V the issue appears again

Hey, i had been facing the issue with Ubuntu ever since a week *ever since i accidentally upgraded to H24h2) and your suggestion helped me with it, just:

1.  **disabling "Hyper-V"** and 
2. **enabling "Virtual Machine Platform" + "Windows Hypervisor Platform"** 
fixed it for me. 

Been dreaded for a week, you helped me! Thanks a ton!

**Comment by chetgurevitch** [comment]
I only had these Hyper-V features enabled for shrinking WSL VHDs when I ran into the issue
![image](https://github.com/user-attachments/assets/6f3cc0b1-024d-4581-b487-e745cc1493a2)

**Comment by colejohnson66** [comment]
Restarting "Host Network Service" fixed it for me.

**Comment by mahtaran** [comment]
> I only had these Hyper-V features enabled for shrinking WSL VHDs when I ran into the issue, so it might specifically be the Services one. It'd be good for someone who's run into it since updating to 24H2 to [grab their logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md?rgh-link-date=2024-10-07T02%3A54%3A50Z#collect-wsl-logs-for-networking-issues) before resolving it. ![image](https://private-user-images.githubusercontent.com/25513187/374009828-6f3cc0b1-024d-4581-b487-e745cc1493a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTI4ODgsIm5iZiI6MTcyODQ1MjU4OCwicGF0aCI6Ii8yNTUxMzE4Ny8zNzQwMDk4MjgtNmYzY2MwYjEtMDI0ZC00NTgxLWI0ODctZTc0NWNjMTQ5M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA1NDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMzcwN2M0ZjdjMGUzMTI3N2I3MGRkNWI1YmE5ZjE1MmYzZDRhMjA4ZjgxYmExNGViMGJlY2M3NDNlY2M1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z1sg1WZpuH40qjUNJd5tXa-HuaMCDWXClHkUo-_78Ck)

I've been running into it since a cumulative update this morning (KB5044284). Not sure if it's entirely what you meant, but might still prove useful.

[WslNetworkingLogs-2024-10-09_08-05-33.zip](https://github.com/user-attachments/files/17302994/WslNetworkingLogs-2024-10-09_08-05-33.zip)

**Comment by yorek** [comment]
> Restarting "Host Network Service" fixed it for me.

Same here

**Comment by psynyde** [comment]
As a note from a Nix Wsl user. if anyone facing the same issue and want internet to work with it:
- create `.wslconfig` in your windows userdir. (type `cd ~` in powershell and enter)
- put the code below inside the config file:
```sh
[wsl2]
networkingMode=mirrored
```
- put the code below in your `configuration.nix`:
```nix
wsl.usbip.snippetIpAddress = "127.0.0.1";
```
- install [usbipd](https://github.com/dorssel/usbipd-win) with `winget install usbipd`
- reboot windows for good measures

**Comment by frostieDE** [comment]
I also tried all the above workarounds, none of them worked :-( 

However what worked for me (for some reason): I just installed another distro (in my case Ubuntu 24.04 LTS). The installation seems to fix the issue for me.

Hope it helps any of you guys, too :-)

**Comment by jozefizso** [comment]
After upgrade to Windows 24H2 I have this issue with wsl.

```
wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033
```

```
wsl: Access is denied.
Error code: CreateInstance/CreateVm/ConfigureNetworking/HNS/E_ACCESSDENIED
wsl: Failed to configure network (networkingMode Nat), falling back to no networking.
```

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

**Comment by inqrphl** [comment]
24H2 update broke my setup as well, before that I was using the mirrored mode without problems, including ipv6 and host dns. 

Shutting down wsl and restarting Host Network Service works. If the network does not come up first time doing it, I try until it works.

In optional windows features, I have
Hyper-V, fully on
-> Hyper-V Management Tools, fully on
-> Hyper-V Platform, fully on
Windows Machine Platform, fully on
Windows Hypervisor Platform, fully on
Windows Subsystem for Linux, fully on

```
PS C:\Users\sorus> wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033

PS C:\Users\sorus> wsl --shutdown
```

Restarting Host Network Service on Services.msc, first time

```
PS C:\Users\sorus> wsl
wsl: Access is denied.
Error code: CreateInstance/CreateVm/ConfigureNetworking/HNS/E_ACCESSDENIED
wsl: Failed to configure network (networkingMode Nat), falling back to no networking.
Welcome to Ubuntu 24.04 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Sun Oct 13 00:42:53 CEST 2024

  System load: 0.24                Memory usage: 4%   Processes:       100
  Usage of /:  4.5% of 1006.85GB   Swap usage:   0%   Users logged in: 0

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

Expanded Security Maintenance for Applications is not enabled.

171 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

3 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


This message is shown once a day. To disable it please create the
/home/user/.hushlogin file.

user@host:/mnt/c/Users/sorus$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
user@host:/mnt/c/Users/sorus$ exit
logout
PS C:\Users\sorus> wsl --shutdown
```

Restarting Host Network Service on Services.msc, second time

```
PS C:\Users\sorus> wsl
wsl: Failed to create network endpoint with address: '172.27.2.65', assigned new address: '172.24.28.102'
user@host:/mnt/c/Users/sorus$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

user@host:/mnt/c/Users/sorus$ cat /etc/wsl.conf
[boot]
systemd=true

[wsl2]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
guiApplications=true
user@host:/mnt/c/Users/sorus$
```

**Comment by Ktoto59** [comment]
It helped to create a `.wslconfig` in the root folder of a windows user with such content:
```
[wsl2]
networkingMode=mirrored
```

wsl --version
```
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26120.1843
```

**Comment by amirasyraf** [comment]
Happened to me today out of the blue. Latest Windows Update broke it, specifically "2024-10 Cumulative Update for Windows 11 Version 24H2 for x64-based Systems (KB5044284)"

`networkingMode=mirrored` fixes it for now

**Comment by lukasamd** [comment]
I had the same issue and mirrored networkingMode was fine, but only temporary - after some network issues, it stopped working at all

I've decided to try restarting Host Network Service and after that everything works fine (without mirrored)

**Comment by benhillis** [comment]
There are two workarounds for this:

1. Switch to mirrored networking or virtio proxy networking

Add one of the following to %userprofile%.\wslconfig
```
[wsl2]
networkingMode=mirroed
#or
networkingMode=virtioProxy
```

2. Uninstall KB5041865 while the fix to Windows is rolled out.

**Comment by benhillis** [comment]
This issue has been resolved.

**Comment by futuremotiondev** [comment]
I had this issue today installing WSL2. 

```
2025-06-17 18:09 C:\Users\futur\Desktop> wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
2025-06-17 18:10 C:\Users\futur\Desktop> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.
2025-06-17 18:10 C:\Users\futur\Desktop> wsl --install Ubuntu-24.04
Downloading: Ubuntu 24.04 LTS
Installing: Ubuntu 24.04 LTS
wsl: Failed to create network endpoint with address: '172.28.17.6', assigned new address: '172.25.223.252'
Distribution successfully installed. It can be launched via 'wsl.exe -d Ubuntu-24.04'
Launching Ubuntu-24.04...
Provisioning the new WSL instance Ubuntu-24.04
This might take a while...
Create a default Unix user account:...
```

After I created my account Ubuntu seems to be working fine and network access is working in WSL. But the **wsl: Failed to create network endpoint with address: '172.28.17.6', assigned new address: '172.25.223.252'** line makes me worry.

Also, in my network adapter properties, I have three adapters now:

1. My Wi-Fi Adapter from my motherboard
2. vEthernet (Default Switch) (Hyper-V Virtual Ethernet Adapter)
3. vEthernet (WSL) (Hyper-V Virtual Ethernet Adapter)

![Image](https://github.com/user-attachments/assets/d0fe726d-f51b-489a-ba17-37a74d2a011e)

However I am concerned because in all three adapters the `Hyper-V Extensible Virtual Switch` is disabled, and I cannot enable it.

![Image](https://github.com/user-attachments/assets/f739765d-d3d4-4492-b140-750dd97d60a8)

If I enable the checkbox and then click OK, I get this dialog:

![Image](https://github.com/user-attachments/assets/a4f379f3-0a79-4469-8ac1-42ba000cea5b)

Is my WSL2 installation misconfigured? From what I understand the `Hyper-V Extensible Virtual Switch` is important to proper functioning of WSL.

Can someone shed some more light on this?
