### ISSUE TITLE
How to use audio in bash on windows?

### ISSUE THREAD

**Issue by GERMANOCARELLA** [Microsoft/WSL#1200]
Please use the following bug reporting template to help produce actionable and reproducible issues. 

I tried to start espeak on my bash on windows.

I received some errors regarding pulseaudio and the fact that is not installed.
I googled and I found that pulseaudio doesn't work on bash on windows.
There is an other way can I try to use audio on my bash on windows?
I need audio in order to improve tts system such as festvox... 
Maybe I must install pulseaudio and start it as a service everytime I start bash?

**Comment by fpqc** [comment]
@therealkenc has a modified version of pulseaudio in a ppa that reconfigures it to run without an unimplemented futex.  Then you can pipe pulseaudio over tcp to the Windows version of pulse.

**Comment by saivert** [comment]
Would there be any chance of emulating an ALSA device for simple audio in/out?
Or maybe once the lxdrv is documented properly someone might implement it.
piping via pulseaudio to external server incurs some latency

**Comment by therealkenc** [comment]
User voice for this is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14017329-sound-card-support). [BTW to answer _@Admin_ over there, the "developer scenario" is [vscode-typewriter](https://marketplace.visualstudio.com/items?itemName=jasonpoon.vscode-typewriter) (_duh_).]

You could do a `lxdrv` for it, but then you still need to create a service to marshal the audio bytes to the Windows side. All you'd be doing is changing the transport mechanism, and you'll have a tough time convincing me using LxBus versus ipv4 over localhost would make any difference discernible to the senses.

Curious: Are you seeing any _actual_ latency, or did you mostly make that up. I was mildly surprised myself when video being streamed over X11 and audio over PA (completely independent software and IP channels) were in sync.

**Comment by fpqc** [comment]
@therealkenc Well, maybe if Microsoft ever decides to redo the audio device framework on Windows (*shudder*), they can also add an audio interface via lxdrv. Otherwise I don't much see the point.  Audio on Linux is always the biggest nightmare.

**Comment by fpqc** [comment]
This looks promising though: https://www.linuxmusicians.com/viewtopic.php?t=12818

From what I can gather, you can also redirect Jack2 over tcp/ip, and that can network with the Windows version of Jack, which communicates with ASIO drivers in Windows.

**Comment by therealkenc** [comment]
Yes, all of the higher quality packages like ffmpeg (and by extension everything that uses ffmpeg) support Jack. Funny [article](https://github.com/jackaudio/jackaudio.github.com/wiki/WalkThrough_User_NetJack2) referenced in your link, quote: "100mbit/s is a good start". Jesus that's sad. Goes to my comment on latency above. I can remember doing primitive VOIP around 1995 with a 28.8kbps modem and tolerable latency. These days you can probably stream 5.1 channel studio quality audio with 30ms latency with less than 500kbps if you [do it right](http://opus-codec.org/).

**Comment by saivert** [comment]
@therealkenc I'm not talking about audio sync. That is no the issue. I'm talking about the initial buffer delay from you hit play button in music player software till you can hear it. Also seeking incurs a bit of delay.
I tested this myself using Pulseaudio over TCP/IP to a local Win32 Pulseaudio instance and using Deadbeef player on Bash on Windows side.

**Comment by therealkenc** [comment]
Ahh okay thanks for clarifying. It sure isn't _TCP/IP_ latency; that's 0ms over localhost (rounded to the nearest ms). You're right, _something_ is buffering _somewhere_. Which isn't surprising, but it is weird because sync does matter. When you play a youtube video on firefox or mp4 video with VLC, your XcXsrv server _doesn't know_ what you are seeing on screen is supposed to show up at the same time as your Win32 PA server sends audio to the sound card. It gets there when it gets there. Any initial audio buffering would screw up the sync. But, the sync isn't screwed.

I haven't actually used PA since I got it to work (because of lack of sensible use cases), but if I get a chance I'll take a look at 0xdeadbeef.

**Comment by fpqc** [comment]
@saivert Supposedly the tcp loopback from WSL to Windows is actually zero-copy, if I remember correctly.  

@therealkenc I got jack-dbus installed and configured as a slave following that guide.  I did make an strace, dunno if you want to glance at it.

[stracejackcontrol.txt](https://github.com/Microsoft/BashOnWindows/files/601516/stracejackcontrol.txt)

**Comment by therealkenc** [comment]
Yeah it's zero copy which helps bandwidth, though it would still be 0ms latency even if it wasn't zero-copy on the bits.

Is that with `strace -ff`? Probably one of the AF_UNIX problems making Dbus unhappy, but that's just a guess.

**Comment by saivert** [comment]
I have been testing this on a Windows 10 VM and doing it over RDP so my experiments are invalid. I set it all up locally and no delay on start of playback.

**Comment by fpqc** [comment]
@therealkenc Yep, with -ff.

**Comment by therealkenc** [comment]
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14017329-sound-card-support

#237 for ALSA, #486 for Pulse
