### ISSUE TITLE
Nonpaged Pool Memory Leak in netio.sys When Using Mirrored Network Mode

### ISSUE THREAD

**Issue by wuxie0ne** [microsoft/WSL#12006]
### Windows Version

Microsoft Windows [Version 10.0.22631.4112]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Arch rolling

### Repro Steps

.wslconfig

```
[experimental]
networkingMode=mirrored
```

### Expected Behavior

Nonpaged Pool Memory should be a stable and low value, usually within 1G.

### Actual Behavior

Nonpaged Pool Memory will grow by 1~2 Mib per second until all memory is occupied.

![61322c64113de6b74f63f7e36da3a96](https://github.com/user-attachments/assets/1d337b53-7f74-4873-a264-54c804442c97)
![f0fd8799c05f31016ca75bbb2bd480f](https://github.com/user-attachments/assets/f0d578be-f104-4a89-9920-8a1b422f9bc1)

This problem does not occur when I set networkingMode=NAT, but only occurs when I change it to mirrored.

### Diagnostic Logs

[WslNetworkingLogs-2024-09-08_22-15-38.zip](https://github.com/user-attachments/files/16922571/WslNetworkingLogs-2024-09-08_22-15-38.zip)

**Comment by wuxie0ne** [comment]
> # Logs are required for review from WSL team
> WSL 团队需要审核日志
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'.如果这是一个功能请求，请回复“/feature”。如果这是一个问题，请用“/question”回复。 **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.**否则，请按照以下说明附加日志**​​，除非添加日志，否则您的问题将不会被审核。这些日志将帮助我们了解您的机器中发生的情况。
> 
> How to collect WSL logs
> 如何收集WSL日志
> Download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:下载并在**管理 powershell 提示符**下执行[collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) ：
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The script will output the path of the log file once done.完成后，脚本将输出日志文件的路径。
> 
> If this is a networking issue, please use [collect-networking-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1), following the instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues)如果这是网络问题，请使用[collect-networking-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1) ，按照[此处的](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues)说明进行操作
> 
> Once completed please upload the output files to this Github issue.完成后，请将输出文件上传到此 Github 问题。
> 
> [Click here for more info on logging单击此处了解有关日志记录的更多信息](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue and reply with '/emailed-logs'.如果您选择通过电子邮件发送这些日志而不是附加到错误中，请将它们发送至[wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) ，并在主题中注明 github 问题的编号，并在消息中提供指向您在 github 中的评论的链接使用“/emailed-logs”发出和回复。
> 
> # View similar issues 查看类似问题
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!请查看下面的问题，看看它们是否能解决您的问题，如果该问题描述了您的问题，请考虑关闭此问题并点赞另一个问题，以帮助我们优先处理它！
> 
> ### Open similar issues: 打开类似问题：
> * [networkingMode=mirrored doesn't work as expected (#11090)](https://github.com/microsoft/WSL/issues/11090),  similarity score: 0.72[networkingMode=mirrored 无法按预期工作 (#11090)](https://github.com/microsoft/WSL/issues/11090) ，相似度得分：0.72
> 
> ### Closed similar issues: 已关闭类似问题：
> * [Effective MTU in mirrored mode is lower than interface MTU (#11584)](https://github.com/microsoft/WSL/issues/11584),  similarity score: 0.74[镜像模式下的有效 MTU 低于接口 MTU (#11584)](https://github.com/microsoft/WSL/issues/11584) ，相似度得分：0.74
> * [Networking mode does not work in mirrored mode (#11540)](https://github.com/microsoft/WSL/issues/11540),  similarity score: 0.72[网络模式在镜像模式下不起作用 (#11540)](https://github.com/microsoft/WSL/issues/11540) ，相似度得分：0.72
> * [In Mirrored mode incoming packets from remote device on LAN are not received in WSL2 (#10535)](https://github.com/microsoft/WSL/issues/10535),  similarity score: 0.71[在镜像模式下，WSL2 中不会收到来自 LAN 上远程设备的传入数据包 (#10535)](https://github.com/microsoft/WSL/issues/10535) ，相似度得分：0.71
> * [`mpirun` hangs when `networkingMode=mirrored` (#11215)](https://github.com/microsoft/WSL/issues/11215),  similarity score: 0.71[当`networkingMode=mirrored`时`mpirun`挂起 (#11215)](https://github.com/microsoft/WSL/issues/11215) ，相似度得分：0.71
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.注意：您可以通过赞成或反对此评论来向我提供反馈。

[WslNetworkingLogs-2024-09-08_22-15-38.zip](https://github.com/user-attachments/files/16922566/WslNetworkingLogs-2024-09-08_22-15-38.zip)

**Comment by shdancer** [comment]
same problem

**Comment by Leoyoungxh** [comment]
Same problem, hope to restart the issue.
![Image](https://github.com/user-attachments/assets/5200062d-e10e-4a74-ae7d-b943a8c9ca0d)
