### ISSUE TITLE
Please update the WinGet version of Microsoft.WSL to 2.2.4.0

### ISSUE THREAD

**Issue by RobCannon** [microsoft/WSL#12012]
**Is your feature request related to a problem? Please describe.**
We use Microsoft Intune to update applications from winget.  The only way I have been able to update WSL is to use the Microsoft.WSL package from winget.

But the problem is that the current version from the winget package source is 2.1.5.0.  If you run `wsl --update`, the version is upgraded to 2.2.4.0, but Intune will downgrade that version back to 2.1.5.0 after a while.  We want the new version for the the networking fixes, especially for DNS resolution.

**Describe the solution you'd like**
I would like the winget version of Microsoft.WSL updated to match the version available via `wsl --update`.  Alternatively, please document another way to use Intune to get the latest version of WSL.

**Describe alternatives you've considered**
We currently have removed the Microsoft.WSL package from users and instructed them to manually update via `wsl --update'.   But that requires administrative access.

**Comment by RobCannon** [comment]
/feature But not really.  Logs are not applicable

**Comment by craigloewen-msft** [comment]
Created a PR here:

https://github.com/microsoft/winget-pkgs/pull/172883

And automated future releases here:
https://github.com/microsoft/WSL/blob/master/.github/workflows/winget.yml

Thanks for filing! Will close this once the PR closes.
