### ISSUE TITLE
Win11 23H2 - WSL hangs after Windows Update

### ISSUE THREAD

**Issue by t-ru** [microsoft/WSL#12024]
### Windows Version

Win 11 23H2 (10.0.22631.4037)

### WSL Version

2.2.4, 2.3.17

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

ALL DISTROS

### Repro Steps

Hello,
we've installed lastest Windows Updates on Win 11 23 H2 in this week on many laptops. After installing no Distro will be started.
Debian, Ubuntu, Thumbleweed.

WSL hangs completly.

WSL 2.2.4 and 2.3.17... same problem

### Expected Behavior

![image](https://github.com/user-attachments/assets/3f1089a4-ee7c-4d8b-aa6a-a48f215c044e)

### Actual Behavior

terminal shows no output. wsl hangs. in task manager I can't find a vmmem proc. I think this is the problem.

**Comment by ThePlenkov** [comment]
Never had issues with WSL but now I'm here too. Something happens with the system after sleep.

**Comment by aisdemogit** [comment]
I too am now experiencing this issue and am unable to perform wsl operations. I had applications working fine on WSL this morning, then in the afternoon could not get wsl to work properly on several Windows 11 machines.

**Comment by ThePlenkov** [comment]
In my case it was caused by auto memory reclaim + Docker resource saver. #12045
