### ISSUE TITLE
`wsl --mount` not working on arm64

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#12038]
### Windows Version

Microsoft Windows [Version 10.0.22631.4169]

### WSL Version

2.3.21.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

`wsl --mount`

### Expected Behavior

mounted disk

### Actual Behavior

`wsl-2.3.21` was supposed to fix #9611 on ARM64, however it still doesn't work:

```
PS C:\Users\elsaco> wsl --mount \\.\PHYSICALDRIVE2 --bare
wsl.exe --mount is not supported for ARM64 on this version of Windows.
```

**Comment by benhillis** [comment]
`wsl.exe --mount` on ARM64 requires Windows platform support which was added in version 27653.
