### ISSUE TITLE
Ubuntu stopped working with code 0x80090006

### ISSUE THREAD

**Issue by gandyli** [microsoft/WSL#12036]
### Windows Version

Microsoft Windows [Version 10.0.27686.1000]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Repro Steps

Ubuntu suddenly stopped working with code 0x80090006 and I'm not able to reinstall it.
Also tried to reinstall or update WSL but didn't help.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80090006
Error: 0x80090006 ?????

Press any key to continue...
```

### Expected Behavior

Runs normally.

### Actual Behavior

Failed.

### Diagnostic Logs

[WslLogs-2024-09-16_20-48-03.zip](https://github.com/user-attachments/files/17013312/WslLogs-2024-09-16_20-48-03.zip)

**Comment by gandyli** [comment]
It seems that I can't open other hyper-v powered applications like wsa either.

**Comment by raynet** [comment]
I have the same issue, I think I had just done 'apt upgrade' last time it worked on this machine.

**Comment by rty813** [comment]
Same Issue 
```
Invalid signature.
Error code: Wsl/Service/CreateInstance/CreateVm/HCS/0x80090006
Press any key to continue...
```

[WslLogs-2024-09-18_09-51-19.zip](https://github.com/user-attachments/files/17037478/WslLogs-2024-09-18_09-51-19.zip)

**Comment by OneBlue** [comment]
Hi @gandyli. Looking at the logs you share the root cause seems to be that the hyper-V firmware expired: 

```
Microsoft.Windows.HyperV.Worker	FallbackError	09-16-2024 05:48:09.892	"	"	"wilResult: 
{
	callContext: 	
	currentContextId: 	0
	currentContextMessage: 	
	currentContextName: 	
	failureCount: 	1
	failureId: 	21
	failureType: 	0
	fileName: 	onecore\vm\common\guestloader\lib\vmfirmwareloader.cpp
	function: 	
	hresult: 	0x80090006
	lineNumber: 	79
	message: 	signature state 2
	module: 	vmchipset.dll
	originatingContextId: 	0
	originatingContextMessage: 	
	originatingContextName: 	
	threadId: 	17912
}"	onecore\vm\common\guestloader\lib\vmfirmwareloader.cpp	79	 	6088	17912	2		00000000-0000-0000-0000-000000000000		
```

The easiest way to resolve this would be to update Windows to get a more recent Hyper-V firmware image.

**Comment by rty813** [comment]
Is there any other way besides upgrading Windows? It seems there is an issue with Windows 11 Canary version 27686, preventing the upgrade to 27695.

![image](https://github.com/user-attachments/assets/403a935e-d523-4837-8984-e5c450ba9c40)

**Comment by gandyli** [comment]
@OneBlue I had the same issue upgrading as @rty813 .

**Comment by gandyli** [comment]
@rty813 I tried manually change the system time so that it's before the expiration date showed in the command "winver", and it worked.

**Comment by rty813** [comment]
> @rty813 I tried manually change the system time so that it's before the expiration date showed in the command "winver", and it worked.

😄

**Comment by gatoniel** [comment]
> @rty813 I tried manually change the system time so that it's before the expiration date showed in the command "winver", and it worked.

To clarify on @gandyli's solution:
1. This solution works in order to start WSL2. In order to start WSL2 just manually set the time and date of your PC before the expiration date shown in the command "winver" (issued from PowerShell, Prompt or Win+R).
2. This solution does **not** solve the problem that the Windows update from version 27686 to 27695 fails with error code 0xC1900101. Is there any news on this problem?

**Comment by machineCYC** [comment]
have the sam issue, do we have any update for this issue?!

**Comment by rty813** [comment]
![image](https://github.com/user-attachments/assets/e1bfd586-8b0d-48d3-8678-609a8f088c56)
Version 27718 claims to have fixed this problem, but I still encountered the 0xC1900101 error when upgrading.

**Comment by raynet** [comment]
> have the sam issue, do we have any update for this issue?!

Latest Insider Preview update fixed this issue for me, the certificate has correct date now.

**Comment by rty813** [comment]
[Version 27723](https://blogs.windows.com/windows-insider/2024/10/09/announcing-windows-11-insider-preview-build-27723-canary-channel/)

> [NEW] We’re investigating reports that some Insiders are still experiencing rollbacks (with error code 0xc190010) when attempting to install the latest Canary builds.
