### ISSUE TITLE
Multiple numa support

### ISSUE THREAD

**Issue by muratyurdakul75** [microsoft/WSL#12044]
More than one NUMA should be supported. 

Especially in server systems, there are 2 NUMA. But WSL only uses 1 of them. And the maximum 64 processor limit should be increased.

Especially there are servers that only run WSL. And all resources are used for WSL. But since there is only one NUMA support, half of the CPU resources are wasted. Having 2 NUMA support would be very good for performance. For those who want to use single NUMA, settings can be made from the .wslconfig file.

**Comment by muratyurdakul75** [comment]
[WslLogs-2024-09-17_23-35-51.zip](https://github.com/user-attachments/files/17034740/WslLogs-2024-09-17_23-35-51.zip)

**Comment by muratyurdakul75** [comment]
[WslLogs-2024-09-17_23-54-31.zip](https://github.com/user-attachments/files/17034915/WslLogs-2024-09-17_23-54-31.zip)

**Comment by muratyurdakul75** [comment]
/feature 
[WslLogs-2024-09-18_00-00-27.zip](https://github.com/user-attachments/files/17034978/WslLogs-2024-09-18_00-00-27.zip)

**Comment by VajdikA** [comment]
Hi @muratyurdakul75 I see that you want more than 64 threads in Pi Node. I have 2 NUMA 16/32, 64T in total, so the WSL2 fix was not needed yet. My another server with more than 64T is on the way, but I already work on resolving this for >64T.
Try this and let me know your result https://github.com/xieyubo/WSL2

**Comment by muratyurdakul75** [comment]
[WslLogs-2024-09-18_18-05-19.zip](https://github.com/user-attachments/files/17046131/WslLogs-2024-09-18_18-05-19.zip)

**Comment by muratyurdakul75** [comment]
> MERHABA@muratyurdakul75Pi Node'da 64'ten fazla iş parçacığı istediğinizi görüyorum. Toplamda 2 NUMA 16/32, 64T'im var, bu yüzden WSL2 düzeltmesine henüz gerek kalmadı. 64T'den fazla iş parçacığına sahip başka bir sunucum yolda, ancak >64T için bunu çözmek için şimdiden çalışıyorum. Bunu deneyin ve sonucunuzu bana bildirin https://github.com/xieyubo/WSL2

**Comment by muratyurdakul75** [comment]
This issue has been resolved. Thank you very much for your efforts.

**Comment by VajdikA** [comment]
Hi @muratyurdakul75 , can you share how exactly was it resolved ? I'm running my app's containers in 2 NUMA config but WSL2 can access only half of my resources (One NUMA). Thanks

**Comment by muratyurdakul75** [comment]
> Hi @muratyurdakul75 , can you share how exactly was it resolved ? I'm running my app's containers in 2 NUMA config but WSL2 can access only half of my resources (One NUMA). Thanks

All you need to do is install WSL 2.4.5. This version uses all processors.
