### ISSUE TITLE
No tcp access from windows host to services running in WSL2/Ubuntu Docker-CE containers

### ISSUE THREAD

**Issue by svenczbg** [microsoft/WSL#12052]
### Windows Version

Microsoft Windows 11 Enterprise 10.0.22631

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04.02 LTS

### Other Software

Docker-CE 24.0.7-ubuntu~22.04.1

### Repro Steps

- Install Windows 365 Cloud PC (Windows 11, 2 vCPUs, 8 GB RAM, 128 GB Storage)
- - wsl --install from admin-powershell
- in Ubuntu shell: sudo apt install docker.io -y
- init docker swarm --advertise-addr <ip of eth0>
- start a docker stack with several services
- stack starts, all images loaded from docker hub and other registries
- ping from host to ubuntu and back works
- no access from host to services in wsl

After trying all recipes that google found, I tried to downgrade the Ubuntu to WSL1. Then I upgraded it back to WSL2. After that, I was able to connect to services in WSL/Ubuntu from the host.

### Expected Behavior

Access to services within WSL/Ubuntu should work out of the box.

### Actual Behavior

After installation of WSL2/Ubuntu & Docker, I had to downgrade to WSL1 and back up to WSL2 to get access from host to services in WSL/Ubuntu

### Diagnostic Logs

Please let me know which log would be helpful. I can provide you with a cloud pc for testing.

**Comment by unclemusclez** [comment]
Feel free to tell us where the WSL2 Docker logs are.
