### ISSUE TITLE
Blackscreen after running colmap with wsl

### ISSUE THREAD

**Issue by Six-Bit-TX** [microsoft/WSL#12058]
### Windows Version

Microsoft Windows [version 10.0.22621.4037]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Other Software

The default version of colmap that comes with apt. Installable via 
```
sudo apt install colmap
```
Nvidia driver, cuda

### Repro Steps

prepare a folder of random images. run 
```
colmap feature_extractor --image_path ${path to folder}
```

### Expected Behavior

colmap create a database of features extracted form the images

### Actual Behavior

Blackscreen, segfault.

**Comment by Six-Bit-007** [comment]
D3D12: Removing Device.
*** Aborted at 1726898377 (unix time) try "date -d @1726898377" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x28) received by PID 1455656 (TID 0x7f2ddf7ee640) from PID 40; stack trace: ***
    @     0x7f2e1d3bf046 (unknown)
    @     0x7f2e1b665520 (unknown)
    @     0x7f2e152bc5ab (unknown)
    @     0x7f2e14d51a43 (unknown)
    @     0x7f2e148683c4 (unknown)
    @     0x7f2e148693b6 (unknown)
    @     0x7f2e148402c7 (unknown)
    @     0x7f2e14842662 (unknown)
    @     0x564b3ac64281 GLTexInput::SetImageData()
    @     0x564b3ac56584 SiftGPU::RunSIFT()
    @     0x564b3a85641d colmap::ExtractSiftFeaturesGPU()
    @     0x564b3a8333e2 colmap::internal::SiftFeatureExtractorThread::Run()
    @     0x564b3a915786 colmap::Thread::RunFunc()
    @     0x7f2e1ba7b253 (unknown)
    @     0x7f2e1b6b7ac3 (unknown)
    @     0x7f2e1b749850 (unknown)
