### ISSUE TITLE
Set sparse to an external VHDX.

### ISSUE THREAD

**Issue by hpx502766238** [microsoft/WSL#12053]
I have set sparseVhd=true in .wslconfig
then ,copy a clean vhdx from another distribute to E:\data.vhdx
then 
```
wsl --shutdown
wsl --mount --vhd "E:\data.vhdx"
lsblk
sudo mkfs.ext4 /dev/sdc
wsl --shutdown
wsl --mount --vhd "E:\data.vhdx"
wsl --cd /mnt/wsl/Edatavhdx
```

**Then I can write files to this external vhdx in wsl,but it cannot shrunk size automally after file was deleted.**
It seems that only system vhdx was supported.
wish wsl to support setting sparseVhd to external vhdx.

**Comment by hpx502766238** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs

/feature

**Comment by OneBlue** [comment]
@hpx502766238: You mark set a vhd as sparse by calling: `fsutil sparse setFlag C:\path\to\vhd` before the disk is mounted inside WSL.
