### ISSUE TITLE
Cant start ubuntu

### ISSUE THREAD

**Issue by MrwoofGaming** [microsoft/WSL#12062]
### Windows Version

Microsoft Windows [Version 10.0.19045.4894]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 24.04

### Repro Steps

open PowerShell
run wsl --install ubuntu

### Expected Behavior

ubuntu starts and reponds

### Actual Behavior

wsl --install ubuntu
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007023e
Error: 0x8007023e {Application Error}
The exception s (0x
Press any key to continue...

**Comment by Raven-Singularity** [comment]
This line seems incomplete: "The exception s (0x"

It looks like that should say "The exception is (0xNNNNNN)", where NNN is the hex code of the error.  Was it the same code as the line above, "0x8007023e"?
