### ISSUE TITLE
nameserver got 10.255.255.254

### ISSUE THREAD

**Issue by rickywu** [microsoft/WSL#12101]
### Windows Version

Windows 11 home edition

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 24.04

### Repro Steps

cat /etc/resolv.conf got wrong server
how should I got correct one if edit manullay

### Expected Behavior

```
# generateResolvConf = false
nameserver 172.x.x.x
search lan
```

### Actual Behavior

```
generateResolvConf = false
nameserver 10.255.255.254
search lan
```

### Diagnostic Logs
[WslLogs-2024-09-29_23-49-07.zip](https://github.com/user-attachments/files/17179833/WslLogs-2024-09-29_23-49-07.zip)

**Comment by elsaco** [comment]
Disable `dnsTunneling`.  It's enabled  by default. Add `dnsTunneling=false` to your `$HOME\.wslconfig`

**Comment by zerzerzerz** [comment]
Create or edit the `.wslconfig` file in the directory `%UserProfile%` in Windows host, following [this url](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file).

**Comment by fgpzen** [comment]
My WSL2 had internet connectivity issues. Initially, I attempted to resolve it by disabling dnsTunneling, but that didn't work. Following the [official documentation](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking), I discovered the mirrored networking mode, an alternative to the default NAT networking. By configuring networkingMode=mirrored in $HOME\.wslconfig, the connectivity issue was completely resolved.

**Comment by rickleiiiii** [comment]
> My WSL2 had internet connectivity issues. Initially, I attempted to resolve it by disabling `dnsTunneling`, but that didn't work. Following the [official documentation](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking), I discovered the mirrored networking mode, an alternative to the default NAT networking. By configuring `networkingMode=mirrored` in `$HOME\.wslconfig`, the connectivity issue was completely resolved.

this works for me. my wsl works well before. but suddenly I lost the network connection. I have no idea why this happened.

**Comment by DaDecky** [comment]
all of the solutions doesn't work for me. i fix the by using the same dns server as my windows. i did it with the following steps.
1. on powershell i do `Get-NetIPConfiguration`
2. copy the value of DNSServer for the network interface i'm using
3. in wsl i replace the content of /etc/resolv.conf with `nameserver <DNSServer IP here>`
4. (optional) to persist change in /etc/wsl.conf add 
  ```
  [network]
  generateResolvConf = false
  ``` 

this is my temporary solution, because with the change of network interface the dnsserver might change
