### ISSUE TITLE
 create bridge: Netlink error: Operation not supported 

### ISSUE THREAD

**Issue by trulliandloeb** [microsoft/WSL#12108]
### Windows Version

10.0.22631.4169

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.3-microsoft-standard-WSL2

### Distro Version

Clear Linux

### Repro Steps

At .wslconfig, configure kernel:
[wsl2]
kernel=C:\\wsl\\kernel\\k-6-6-36-3-skylake

Start podman (podman run ubi8-micro date), it shows below error:
Error: preparing container 7dafe340796a932c6a07a558da67586d4dcdd0976cdf92acb368b0afcd9bd953 for attach: netavark (exit code 1): create bridge: Netlink error: Operation not supported (os error 95)

Start dockerd in Clear Linux(), it shows below error:
WARN[2024-10-01T12:07:18.520019934+08:00] Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module bridge not found in directory /lib/modules/6.6.36.3-microsoft-standard-WSL2
modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/6.6.36.3-microsoft-standard-WSL2
, error: exit status 1
INFO[2024-10-01T12:07:18.524812044+08:00] unable to detect if iptables supports xlock: 'iptables --wait -L -n': `modprobe: FATAL: Module ip_tables not found in directory /lib/modules/6.6.36.3-microsoft-standard-WSL2
iptables v1.8.10 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`  error="exit status 3"
INFO[2024-10-01T12:07:18.553228829+08:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2024-10-01T12:07:18.553506215+08:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2024-10-01T12:07:18.553519820+08:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/6.6.36.3-microsoft-standard-WSL2
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

If I comment the kernel, or use last year's 6.1.21.2-microsoft-standard-WSL2, then everything is okay.

### Expected Behavior

Should be no such issue.

### Actual Behavior

Network issue happens.

### Diagnostic Logs

[WslLogs-2024-10-01_12-37-06.zip](https://github.com/user-attachments/files/17199446/WslLogs-2024-10-01_12-37-06.zip)

### Comments
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.1.y/arch/x86/configs/config-wsl
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.6.y/arch/x86/configs/config-wsl

They have much difference, is the configuration caused module not complied into kernel?

**Comment by trulliandloeb** [comment]
[WslLogs-2024-10-01_12-37-06.zip](https://github.com/user-attachments/files/17199450/WslLogs-2024-10-01_12-37-06.zip)

**Comment by elsaco** [comment]
@trulliandloeb you're using a custom kernel and your modules aren't loading!

From https://github.com/microsoft/WSL2-Linux-Kernel/releases

`However, please be aware that when using a custom kernel, the default module support is disabled for now. If you’re using a custom kernel, we recommend you edit your kernel config file to build-in all of the modules that you need.`

**Comment by OneBlue** [comment]
Indeed @trulliandloeb, if you're using a custom kernel you need to compile in the modules you need (in this case IP_NF_IPTABLES)
