### ISSUE TITLE
The pid of the process in wsl2 differs from the pid returned in ebpf program `bpf_get_current_pid_tgid()`

### ISSUE THREAD

**Issue by Timothy-Liuxf** [microsoft/WSL#12115]
### Windows Version

10.0.26100.1742

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.36.6-microsoft-standard-WSL2+

### Distro Version

Ubuntu 24.04

### Repro Steps

I compiled the WSL2 kernel manually to get eBPF supported.
And I wrote a simple eBPF program to monitor the `getpid` syscall:
+ https://github.com/Timothy-Liuxf/ebpf-examples/blob/e82a808d7ffaab2a7091b76bdce37157bebca96c/test.bpf.c
+ https://github.com/Timothy-Liuxf/ebpf-examples/blob/e82a808d7ffaab2a7091b76bdce37157bebca96c/test.c

And I also wrote a program `main.cpp` to trigger `getpid` syscall periodically:

```cpp
#include <iostream>
#include <unistd.h>

int main()
{
    while (1)
    {
        std::cout << ::getpid() << std::endl;
        sleep(1);
    }
}
```

First, run this trigger program:

```bash
g++ main.cpp && ./a.out
```

And it will print the pid (assume it is `3826`), and compile and run the ebpf prigram:

```bash
gen.sh && make && sudo ./test 3826
```

Then mount the tracing filesystem to check the log:

```bash
sudo mount -t debugfs none /sys/kernel/debug/
sudo echo 1 > /sys/kernel/debug/tracing/events/syscalls/sys_enter_execve/enable
sudo cat /sys/kernel/debug/tracing/trace_pipe
```

### Expected Behavior

It is expected to print:

```
a.out-3826    xxxxxxxxx: bpf_trace_printk: do_sys_getpid called: pid: 3826, m_pid: 3826
```

### Actual Behavior

The `pid` returned by `bpf_get_current_pid_tgid()` is different from `m_pid`:

![1727858637064](https://github.com/user-attachments/assets/e4d3d551-1c8a-48d0-a0f4-3d695440546b)

### Diagnostic Logs

[WslLogs-2024-10-02_16-46-04.zip](https://github.com/user-attachments/files/17226615/WslLogs-2024-10-02_16-46-04.zip)

**Comment by OneBlue** [comment]
@Timothy-Liuxf: This is the expected behavior. Internally, WSL uses different PID namespaces for each distros (so each distro has init with pid=1). 

What you're most likely seeing in your eBPF program is the PID from the root namespace's perspective, which is different from the one you're seeing in the distro namespace.

**Comment by Timothy-Liuxf** [comment]
> @Timothy-Liuxf: This is the expected behavior. Internally, WSL uses different PID namespaces for each distros (so each distro has init with pid=1).
> 
> What you're most likely seeing in your eBPF program is the PID from the root namespace's perspective, which is different from the one you're seeing in the distro namespace.

Then how to get the PID of the root namespace in a WSL2 distro (since `getpid` cannot)?

**Comment by OneBlue** [comment]
By design, you can't do that from within the distribution. There's more info on how this works here: https://www.man7.org/linux/man-pages/man7/pid_namespaces.7.html .
