### ISSUE TITLE
Error : Wsl/Service/CreateInstance/CreateVm/HCS/0x80070142 after upgrading to Win11 24H2

### ISSUE THREAD

**Issue by pquiring** [microsoft/WSL#12116]
### Windows Version

Microsoft Windows [Version 10.0.26100.1742]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

All

### Other Software

none

### Repro Steps

wsl

### Expected Behavior

Get bash prompt.

### Actual Behavior

The target device has insufficient resources to complete the operation.
Error code: Wsl/Service/CreateInstance/CreateVm/HCS/0x80070142

**Comment by pquiring** [comment]
[Uploading WslLogs-2024-10-02_10-12-41.zip…]()

**Comment by pquiring** [comment]
Tried to uninstall and reinstall - no change.  (took an unusual long time to do that).

**Comment by pquiring** [comment]
Unable to start a VM in Hyper-V : same error code.

**Comment by OneBlue** [comment]
@pquiring: The above link doesn't actually point to logs.

/logs

**Comment by pquiring** [comment]
[WslLogs-2024-10-02_10-12-41.zip](https://github.com/user-attachments/files/17234590/WslLogs-2024-10-02_10-12-41.zip)

**Comment by OneBlue** [comment]
Thank you @pquiring. I wonder if the limitation is coming from CPU cores.

Can you try writing: 

```
[wsl2]
processors=1
memory=1GB
nestedVirtualization=false
```

To %USERPROFILE%/.wslconfig and collect /logs if that fails again ?

**Comment by pquiring** [comment]
[WslLogs-2024-10-02_20-04-16.zip](https://github.com/user-attachments/files/17237561/WslLogs-2024-10-02_20-04-16.zip)

.wslconfig had no effect.

**Comment by pquiring** [comment]
Found this in event log:
Virtual machine '' cannot be started on this server. The virtual machine NUMA topology requirements cannot be satisfied by the server NUMA topology. Try to use the server NUMA topology, or enable NUMA spanning. (Virtual machine ID A879800A-4440-4534-BBBD-6BE6A106AAE6).

**Comment by pquiring** [comment]
Fixed it!
Enabled NUMA spanning in HyperV management and then restarted all HyperV services.

**Comment by pormr** [comment]
I've encountered a similar issue, where both WSL and Windows Sandbox give an 0x80070142 (insufficient resources) error. I disabled then reenabled Windows Sandbox from Dev Home app and the error was gone.

**Comment by scarfacestrawberry** [comment]
I encounter the same issue when I upgraded from Win11 22H2 to Win11 24H2. I ended up having to add myself to the Hyper-V Administrators group to fix the issue. My main account is not an administrator for security reasons.

**Comment by east4ming** [comment]
[WslLogs-2025-01-03_14-54-43.zip](https://github.com/user-attachments/files/18297125/WslLogs-2025-01-03_14-54-43.zip)

I have the same problem. Please check logs.

**Comment by tiel-66** [comment]
After updating from Win11 22H2 to 24H2, both wsl and Hyper-V VM worked for me. After uninstalling the older Ubuntu-20.04 and subsequently installing Ubuntu-24.04, i encountered the error 0x80070142 for the first time. From then on, my Win10 VM also stopped working with the same error code. As it turned out, the %userprofile%\.wslconfig was missing, which was not recreated even by deactivating and reactivating the involved Windows components. Recreating the .wslconfig with the content mentioned here resolved the aforementioned problems
