### ISSUE TITLE
WSL2 Fails to Run with error code: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG

### ISSUE THREAD

**Issue by bigcat26** [microsoft/WSL#12138]
I'm having issues with running WSL2 on my system.

At first, when trying to run WSL2, I received the error Error code: Wsl/CallMsi/Install/ERROR_INSTALL_FAILURE.
I followed the solution provided in [this link](https://github.com/microsoft/WSL/issues/11697#issuecomment - 2168104220), which involved renaming a registry key. After that, when I tried to run it again, I got a new error: `Error code: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG`.

If I directly run the release - downloaded installation package, during the installation process, when it reaches about halfway, a prompt box pops up, saying: "An error occurred while attempting to create the directory: C:\ProgramData\Microsoft\Windows\Start Menu".

I also tried removing WSL from "Turn Windows features on or off", restarting my computer, and then adding it back. However, I still get the "REGDB_E_CLASSNOTREG" error.

I'm not sure what else I can do to get WSL2 to run properly. Any help or suggestions would be greatly appreciated.

[WslLogs-2024-10-06_11-27-43.zip](https://github.com/user-attachments/files/17268046/WslLogs-2024-10-06_11-27-43.zip)

**Comment by bigcat26** [comment]
solved after I assigned full control access to the SYSTEM account to the Start Menu folder and then re-install wsl2.

**Comment by CGeisler-kmccontrols** [comment]
I added `SYSTEM` to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` to get rid of this issue; I tried installing from https://github.com/Microsoft/WSL/releases but it still failed, but after I performed the action mentioned by @bigcat26 , the installer worked and then wsl.exe worked.

Thanks so much!
