### ISSUE TITLE
unable to git clone via ssh using  core.sshcommand=ssh.exe

### ISSUE THREAD

**Issue by Angada28** [microsoft/WSL#12145]
### Windows Version

Microsoft Windows [Version 10.0.22631.4249]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.153.1

### Distro Version

Ubuntu 22.04

### Other Software

Windows OpenSSH (ssh.exe)

### Repro Steps

1. clear all known hosts from C:\Users\username\.ssh\known_hosts or temporarily move known_hosts content to another file.
2. on WSL run git config --global core.sshcommand "ssh.exe"
3. try to clone a repo via ssh on wsl 

### Expected Behavior

It should show a prompt to accept or reject the unknown host key; and if you accept it, it should continue with the git clone.

Even after running `git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
` it still hangs

### Actual Behavior

It hangs forever, and there is no output.

**Comment by Angada28** [comment]
incase anyone finds this later the solution/workaround i used was setting up an alias on wsl to use git.exe instead of git.

**Comment by brnhffmnn** [comment]
> git config --global credential.provider generic git config --global core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe

`git config --global core.sshCommand /mnt/c/Windows/System32/OpenSSH/ssh.exe`
worked for me

**Comment by Angada28** [comment]
Thank you so much for that really appreciate it.
