### ISSUE TITLE
wsl2: usage of %LOCALAPPDATA%\Temp\wsl-crashes

### ISSUE THREAD

**Issue by sfoster1** [microsoft/WSL#12147]
Host OS: Windows 11 23H2 22631.4169
Guest distribution: ubuntu, kernel `5.15.153.1-microsoft-swandard-WSL2`

Something in my WSL environment is causing failed nodejs commands to write crash dumps to `%LOCALAPPDATA%\Temp\wsl-crashes` in the host fs. This is annoying because I have a lot of RAM and the crash dumps are big, and Windows gives me notifications that my disk space is running low.

I've searched for information about this, but the documentation about crash dumps refers to WSL2 subsystem crashes, and these are crash dumps from command line programs running in the guest OS.

I would like to be able to disable this behavior or relocate the directory where the crash dumps live. Is this possible? Could it be possible? Is there documentation that I am missing?

**Comment by sfoster1** [comment]
https://github.com/microsoft/WSL/issues/12032 is definitely the cause of the files that I'm seeing, but the thing I would like is the ability to change where they are written or disable them being written to the host FS.

**Comment by OneBlue** [comment]
@sfoster1: You can disable crash dump collection by setting: 

```
[wsl2]
MaxCrashDumpCount=-1
```

In `%USERPROFILE%/.wslconfig`. After WSL restarts, this will completely disable crash dump collection.

**Comment by astroboylrx** [comment]
Disable it should be the default. I have no idea a single dump can be this large.

<img width="509" height="141" alt="Image" src="https://github.com/user-attachments/assets/39a018c4-5c52-4263-b912-5b8e111ab461" />

Update: just saw #41314 , which is similar.
