### ISSUE TITLE
After 'wsl --update' : Debian 11 is still installed but expecting Debian12

### ISSUE THREAD

**Issue by pquiring** [microsoft/WSL#12158]
### Windows Version

Server 2022 : Version 10.0.20348.2762

### WSL Version

WSL version: 2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Distro Version

Debian 11/12

### Other Software

After upgrading WSL it still installs Debian 11 but expecting Debian 12 like other systems.
Is there a cache somewhere that needs to be cleaned?
I've tried to --unregister and --install again.
Deleted everything in %LOCALAPPDATA% that I could find.

### Repro Steps

wsl --update
wsl --unregister debian
wsl --install debian
wsl
cat /etc/os-release
VERSION_ID=11

### Expected Behavior

wsl --update
wsl --unregister debian
wsl --install debian
wsl
cat /etc/os-release
VERSION_ID=12

### Actual Behavior

VERSION_ID=11

### Diagnostic Logs

Just a cache issue need to understand.

**Comment by zcobol** [comment]
@pquiring it's not enough to unregister the distor only. You need to delete the appx package also.

**Comment by pquiring** [comment]
Ok, where is the appx package stored?

**Comment by pquiring** [comment]
PowerShell : Remove-AppxPackage

**Comment by pquiring** [comment]
I've figured out how to create images with docker.  Going to use that instead.

Thanks!
