### ISSUE TITLE
How can I test if a WSL distro is installed or not?

### ISSUE THREAD

**Issue by eggbean** [microsoft/WSL#12152]
How can I test if a WSL distro is installed or not? I have tried this, but nothing gives any output:

    wsl.exe --list | Select-String -Pattern "Ubuntu" -CaseSensitive:$false

    (wsl.exe --list | Out-String).Trim() | Select-String -Pattern "Ubuntu" -CaseSensitive:$false

    wsl.exe --list | ForEach-Object { $_.Trim() } | Select-String -Pattern "Ubuntu" -CaseSensitive:$false

    wsl.exe --list --verbose | ForEach-Object { $_.Trim() } | Select-String -Pattern "Ubuntu" -CaseSensitive:$false

**Comment by eggbean** [comment]
I don't think logs are relevant here.

**Comment by elsaco** [comment]
@eggbean you could query `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss` and look for `DistributionName`

**Comment by eggbean** [comment]
@elsaco Thanks, but where are the GUIDs(?) coming from? (eg. {f0a15aba-fedb-4d04-ad8d-ac69e5f073c0}). It doesn't seem to correspond with the ones used in `settings.json`.

If I do it like this, how can I grep from the list?

```
Get-ChildItem "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss" | 
    ForEach-Object { 
        Get-ItemProperty $_.PSPath
    } | 
    Select-Object DistributionName
```

**Comment by elsaco** [comment]
`req query` is overkill for this but `Select-String -SimpleMatch` will do it.

**Comment by eggbean** [comment]
Great. It works on PowerShell Core 7 but not Windows PowerShell 5. Thanks!
