### ISSUE TITLE
[RESOLVED] apt-get: relocation error on dist-upgrade to Xenial

### ISSUE THREAD

**Issue by aseering** [Microsoft/WSL#1216]
I'm creating a cross-reference for this failure:  The root cause (and the fix) is upstream, but I just hit it and looked for the solution here; I'm filing this ticket so that others who look for the fix here can find it.

WSL forum mods, feel free to close this either right away (since I think there's no action for the WSL team to take here) or once most people have upgraded to 16.04.

I recently ran `do-release-upgrade` to upgrade to Xenial.  After the upgrade, many commands, including `apt-get`, failed with:

```
$ sudo apt-get install dialog
apt-get: relocation error: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

This is caused by [Ubuntu #1572903](https://bugs.launchpad.net/ubuntu/+source/init-system-helpers/+bug/1572903).  The workaround listed there, which worked for me, is as follows:

```
wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.2_amd64.deb
sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.2_amd64.deb
```

**Comment by raymens** [comment]
I just hit this on 15063.13 after a `do-release-upgrade`. Updated workaround (package build has been updated):

```
wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb
sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb
```

**Comment by HLFH** [comment]
Thank you @raymens. It works.

We can close this issue.

**Comment by zkawan** [comment]
When I run that wget command it results into error :
Resolving security.ubuntu.com failed. Temporary failure in name resolution

**Comment by zkawan** [comment]
Now it says Error 404 not found.

**Comment by xiadingZ** [comment]
when I run `sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb`, there is a error:
`dpkg: warning: downgrading libstdc++6:amd64 from 7.2.0-1ubuntu1~14.04 to 5.4.0-6ubuntu1~16.04.4
dpkg: regarding libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb containing libstdc++6:amd64:
 libstdc++6:amd64 breaks libboost-date-time1.55.0
  libboost-date-time1.55.0:amd64 (version 1.55.0-1) is present and installed.

dpkg: error processing archive libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb (--install):
 installing libstdc++6:amd64 would break libboost-date-time1.55.0:amd64, and
 deconfiguration is not permitted (--auto-deconfigure might help)
Errors were encountered while processing:
 libstdc++6_5.4.0-6ubuntu1~16.04.4_amd64.deb`

**Comment by therealkenc** [comment]
These are user space `apt` and `dpkg` issues not WSL actionables. The above one looks like [this](https://askubuntu.com/questions/826475/cant-use-apt-libstdc-so-6-version-glibcxx-3-4-20-not-found/826482) maybe, but that's just because I Googled. Maybe someone will jump in, but you'll probably get better service in a Ubuntu forum or `libstdc++` forum.

**Comment by gumb0** [comment]
I've hit it just now, and here's the updated workaround that worked for me:
```sh
wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
```

**Comment by fabianlee** [comment]
Thanks, @gumb0 the libstdc library you referenced above resolved my upgrade from 14.04 to 16.04 (desktop was cycling through login).

**Comment by jca-agnitio** [comment]
Thanks @gumb0 , that worked for me too.

**Comment by rush5150** [comment]
I signed up just to add @gumb0  this still works.

Thank you for the help.

**Comment by Shrek-DevMasterRobo** [comment]
> I've hit it just now, and here's the updated workaround that worked for me:
> 
> ```shell
> wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
> sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
> ```

Thanks a lot for this, After going through on this for hours, finally found a solution that worked. Thanks a lot.

**Comment by ferdymercury** [comment]
Thanks a lot for the hint. I had to combine it with a bit more work to install other conflicting related packages: https://askubuntu.com/questions/1437928/problem-when-upgrading-ubuntu-14-to-ubuntu-16?noredirect=1#comment2507795_1437928
