### ISSUE TITLE
Quick Access pins broken after 24H2 update

### ISSUE THREAD

**Issue by conan** [microsoft/WSL#12173]
### Windows Version

Microsoft Windows [Version 10.0.26100.2033]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Pin folder inside `\\wsl$` to quick access in file explorer
2. Click on pinned folder

### Expected Behavior

1. Pin folder inside `\\wsl$` to quick access in file explorer
2. Click on pinned folder
3. Pinned folder opened in file explorer

### Actual Behavior

1. Pin folder inside `\\wsl$` to quick access in file explorer
2. Click on pinned folder
3. "Element not found" error shown

![Image](https://github.com/user-attachments/assets/30483306-bfe2-4ef6-a214-f38bc4c48385)

### Diagnostic Logs

[WslLogs-2024-10-16_11-25-44.zip](https://github.com/user-attachments/files/17394115/WslLogs-2024-10-16_11-25-44.zip)

**Comment by conan** [comment]
See relevant comment: https://github.com/microsoft/WSL/issues/11252#issuecomment-2413694881

**Comment by haraldger** [comment]
I'm having the same issue as OP and in the other referenced thread. Running `wsl --update` and `wsl --update --pre-release` gives me back "The most recent version of Windows Subsystem for Linux is already installed." so no help there. I first noticed the issue yesterday (2024-10-21).

**Comment by GillesJ** [comment]
Exact same issue here after updating.

**Comment by conan** [comment]
> The log file doesn't contain any WSL traces. Please make sure **that you reproduced the issue while the log collection was running.**
> 
> Diagnostic information

I did reproduce whilst the log collection was running.  This seems like the kind of issue that would be logged in Windows logs (it being an issue with File Explorer) rather than WSL logs.

**Comment by christian-at-sevenlab** [comment]
Same issue here.

Slight workaround is to map your '\\wsl.localhost' to a network drive. Pinning folders from that mapped network drive works.

For those who have a non-working Pin in their explorer stuck, I was able to remove it with;
- Workaround for removing a folder that points to the '\\wsl$' is to navigate to that folder and right button click 'Pin to quick access'

**Comment by fiathux** [comment]
Another workaround method is add network location in 'This PC' and show 'This PC' tree in navgation pane.

![Image](https://github.com/user-attachments/assets/8615584f-21bd-4624-8ba6-f2e08b37cd7f)

If use Network driver, it will failed path conversition when we open a WSL terminal from right click menu or you want start a WSL application from this location.

**Comment by ashkanr65** [comment]
Same issue here.
I tried to pin \\wsl.localhost to the quick access. But when I click on it, this error appear:
![Image](https://github.com/user-attachments/assets/fb2f2c74-9e07-45e5-a1bf-add788a80808)
And now, I cannot even unpin it. It is stuck there.
My windows updated to 24H2 W11.
![Image](https://github.com/user-attachments/assets/696f145b-7cf8-459a-8e38-9e485805f066)

**Comment by conan** [comment]
Some updates:

* It hadn't occurred to me to try to unpin my WSL quick access options, I can confirm I am unable to
* Can confirm the workaround of mapping `\\wsl$\Ubuntu` to a Network Drive worked for me

**Comment by Ravenger2709** [comment]
Same problem for me with WSL quick access dissapeared.

**Comment by fiathux** [comment]
> Same issue here. I tried to pin \wsl.localhost to the quick access. But when I click on it, this error appear: ![Image](https://github.com/user-attachments/assets/fb2f2c74-9e07-45e5-a1bf-add788a80808) And now, I cannot even unpin it. It is stuck there. My windows updated to 24H2 W11. Edition Windows 11 Pro Version 24H2 Installed on ‎25/‎10/‎2024 OS build 26100.1742 Serial number 5XA29FFT800042H Experience Windows Feature Experience Pack 1000.26100.18.0 And My WSL is updated to the latest: ![Image](https://github.com/user-attachments/assets/696f145b-7cf8-459a-8e38-9e485805f066)

Same issue here.
You can remove file to reset quick access (will remove all your custiomize icon in quick access). `C:\Users\sum\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\f01b4d95cf55d32a.automaticDestinations-ms`

If you really want add icon into quick access to open WSL path. try use network drive please. It's work to me.
However, you can not directly open WSL terminal in network drive location using right click in the Explorer. Only 'network locations' available it.

**Comment by Hofundur** [comment]
fixed in https://support.microsoft.com/pl-pl/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b

**Comment by haraldger** [comment]
Automatically started working for me with the latest fix, thanks @Hofundur

**Comment by CameronGo** [comment]
Same, updated wsl this morning and that resolved the issue.

> the issue look been fixed.
> 
> my system version:
> 
> > WSL version: 2.3.26.0
> > Kernel version: 5.15.167.4-1
> > WSLg version: 1.0.65
> > MSRDC version: 1.2.5620
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.26100.1-240331-1435.ge-release
> > Windows version: 10.0.26100.2314

**Comment by txdFabio** [comment]
Same issue, after the update to win11 24h2 all the links are gone, if I add them again they don't work with the error on explorer.exe "Element not found." and actually I'm unable to remove that broken links.
I tried both linking \\wsl.localhost\path and \\wsl$\path but doesn't work.

I have all the components updated with the same version of the last comments but it doesn't work

**Comment by zoliszabo** [comment]
I have the same issue:

```
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314
```

Installed 24H2 yesterday, the problems appeared right after.

Interestingly, I can access the files from File Explorer, double-click in them works fine, but `wslview` gives the same `Start : This command cannot be run due to the error: Element not found.` error; also, double-clicking the same files from Total Commander raise the same "Element not found." error.

**Comment by conan** [comment]
Also seems to be working for me now, although I've been using the network drive workaround so I can't pinpoint exactly when.

```
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314
```

**Comment by zoliszabo** [comment]
@conan Could you please test something for the rest of us?

1. Start PowerShell in a WSL folder or change directory to a WSL folder after starting PowerShell (e.g. `cd \\wsl$\distro\some\existing\folder`);
2. Type `Start .`, which should open the current folder in File Explorer.
3. Does it work? If yes, does it open the correct folder?

Thank you!

**Comment by Falkenjack** [comment]
I have the same WSL- and Windows versions as @conan but still have the issue with Quick Access pins to WSL directories not working. I ran the test suggested by @zoliszabo with the following result:

> PowerShell 7.4.6
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu-22.04\home\johsj47> Start .
Start-Process: This command cannot be run due to the error: An error occurred trying to start process '.' with working directory '\\wsl.localhost\Ubuntu-22.04\home\johsj47'. Element not found.

And to affirm I am running the same version as @conan :

> PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu-22.04\home\johsj47> wsl --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314

**Comment by CameronGo** [comment]
Maybe a dumb question, but did you reboot after updating wsl? I had to reboot after the update for mine to work.

> I have the same WSL- and Windows versions as [@conan](https://github.com/conan) but still have the issue with Quick Access pins to WSL directories not working. For comparison, I ran the test suggested by [@zoliszabo](https://github.com/zoliszabo) with the following result:
> 
> > PowerShell 7.4.6
> > PS Microsoft.PowerShell.Core\FileSystem::\wsl.localhost\Ubuntu-22.04\home\johsj47> Start .
> > Start-Process: This command cannot be run due to the error: An error occurred trying to start process '.' with working directory '\wsl.localhost\Ubuntu-22.04\home\johsj47'. Element not found.
> 
> And to affirm I am running the same version as [@conan](https://github.com/conan) :
> 
> > PS Microsoft.PowerShell.Core\FileSystem::\wsl.localhost\Ubuntu-22.04\home\johsj47> wsl --version
> > WSL version: 2.3.26.0
> > Kernel version: 5.15.167.4-1
> > WSLg version: 1.0.65
> > MSRDC version: 1.2.5620
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.26100.1-240331-1435.ge-release
> > Windows version: 10.0.26100.2314

**Comment by Falkenjack** [comment]
@CameronGo I have rebooted multiple times, yes. Worth mentioning is perhaps that my computer is managed by my employer. While I have some local admin rights I have little to no control over which updates are pushed and when to install them, i.e. I am somewhat limited wrt what I can do to explore this issue as far as it entails installing and/or rolling back updates.

**Comment by naourass** [comment]
Same problem after latest Windows Update. WSL folder disappeared from Network folder in File Explorer, and can't access pinned WSL folders from Quick Access in File Explorer. When I run `wsl --update` it says that the most recent version is already installed, and I also have all latest Windows Update installed, so not sure what you guys mean by it's fixed after updating.

**Comment by CptnFizzbin** [comment]
Can confirm that this is also still happening for me.

WSL Version:
```txt
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314
```

**Comment by zoliszabo** [comment]
Windows update KB5048667 was installed on my PC overnight and it fixed the issue for me.

I must note that I also clicked WSL in the start menu _by mistake_ (I almost never do that to start WSL) and it triggered the installation process of version 2.3.26.0 (the version I already had installed since weeks ago). _

Anyway, all issues seem to be gone now.

Current configuration:

> WSL version: 2.3.26.0
> Kernel version: 5.15.167.4-1
> WSLg version: 1.0.65
> MSRDC version: 1.2.5620
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.26100.2605

**Comment by dif-engine** [comment]
I've applied Windows update KB5048667 and wsl --version tells as same as zoliszabo's previous post.
But still my Quick Access pins for WSL region is broken. sad.

**Comment by kiddingbaby** [comment]
Same on 24h2, linux icon missed. 

I found a temporal solution, just updating to pre-release version：2.4.5.0

`wsl.exe --update --pre-version`

Then reboot the pc, linux icon will be displayed.

**Comment by dif-engine** [comment]
kiddingbaby, thak you. That worked.

But maybe correct command would be:
`wsl.exe --update --pre-release`

**Comment by kiddingbaby** [comment]
> kiddingbaby, thak you. That worked.
> 
> But maybe correct command would be: `wsl.exe --update --pre-release`

You're right, I edited  my comment. 

By the way, it broken again today, after reboot, the problem disappears again. I think there must be some magic that triggers it.

**Comment by naourass** [comment]
I can confirm that the trick mentioned by @zoliszabo about opening WSL app from start menu can indeed bing back the WSL folder in File Explorer by triggering some installation process and after rebooting the pc.

**Comment by txdFabio** [comment]
For me the update with --pre-release flag (and a reboot) fixed the issue

**Comment by JohnRDOrazio** [comment]
I also noticed that `Linux` had disappeared from under the `Network` entry.

But updating with --pre-release flag (which ended in an error about not being able to create a link), rebooting, launching Ubuntu from start menu, then reopening Explorer, voilà I now have `Linux` again below the `Network` entry, and the pin in Quick Access is working again, no need to map the network drive. For now at least.

**Comment by xKostmand** [comment]
i have tha same issue, i pinned "\\wsl$" to quick access and when i click it it says "Explorer.exe  Element not found." but i cant seem to unpin it.

**Comment by Sharom** [comment]
Updated with `--pre-release` to WSL 2.4.8.0.

Now I have "Linux" shortcut in the Explorer, `wslview` works fine, wslu v4.1.3-1.

**Comment by ctlila** [comment]
I've found a workaround. 
Map your WSL network drive to a local drive in windows, following [these instructions](https://support.microsoft.com/en-gb/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d).
Then your WSL directory will be accessible from the local drive letter you've assigned to it (for instance W:\).
The quick access pinning works with the local path !

**Comment by atomlin** [comment]
I am seeing same issue with my home directory pinned to Quick Access. I can use \\wsl$\ in address bar fine, but I cannot access or delete the Quick access.
I tried reinstalling from the .msi but that did not fix anything.
When will the fix be available in a non-pre-release build?

**Comment by fmeynadier** [comment]
> i have tha same issue, i pinned "\wsl$" to quick access and when i click it it says "Explorer.exe Element not found." but i cant seem to unpin it.

Trying to pin it again unpinned it for me. 

(Feels like being stuck in a 90's point'n'click game...).

**Comment by zephward** [comment]
https://github.com/microsoft/WSL/issues/12173#issuecomment-2535134210


^^^^



> Windows update KB5048667 was installed on my PC overnight and it fixed the issue for me.
> 
> I must note that I also clicked WSL in the start menu _by mistake_ (I almost never do that to start WSL) and it triggered the installation process of version 2.3.26.0 (the version I already had installed since weeks ago).
> 
> Anyway, all issues seem to be gone now.
> 
> Current configuration:
> 
> > WSL version: 2.3.26.0
> > Kernel version: 5.15.167.4-1
> > WSLg version: 1.0.65
> > MSRDC version: 1.2.5620
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.26100.1-240331-1435.ge-release
> > Windows version: 10.0.26100.2605



***********************

THIS IS THE WAY

***********************

**Comment by carlsc2** [comment]
> [#12173 (comment)](https://github.com/microsoft/WSL/issues/12173#issuecomment-2535134210)
> 
> ^^^^
> 
> > Windows update KB5048667 was installed on my PC overnight and it fixed the issue for me.
> > I must note that I also clicked WSL in the start menu _by mistake_ (I almost never do that to start WSL) and it triggered the installation process of version 2.3.26.0 (the version I already had installed since weeks ago).
> > Anyway, all issues seem to be gone now.
> > Current configuration:
> > > WSL version: 2.3.26.0
> > > Kernel version: 5.15.167.4-1
> > > WSLg version: 1.0.65
> > > MSRDC version: 1.2.5620
> > > Direct3D version: 1.611.1-81528511
> > > DXCore version: 10.0.26100.1-240331-1435.ge-release
> > > Windows version: 10.0.26100.2605
> 
> THIS IS THE WAY

Can confirm; had this issue for the last week or more - tried all kinds of solutions mentioned on other related issues to no avail, searched "wsl" in start menu, clicked it, and it fixed itself after some configuration dialog popped up.

**Comment by tjayz** [comment]
Hover over file explorer icon on taskbar and right click, unpin wsl from quick access here by clicking the thumbtack icon on right side while hovering over it. This is only thing that worked for me. Incredibly annoying, hope this helps someone.

**Comment by djam90** [comment]
> Hover over file explorer icon on taskbar and right click, unpin wsl from quick access here by clicking the thumbtack icon on right side while hovering over it. This is only thing that worked for me. Incredibly annoying, hope this helps someone.

You da GOAT

**Comment by joepaolicelli** [comment]
Just encountered this issue after updating to Windows 11. I was already on the latest stable version of WSL, so `wsl --update` did nothing, but `wsl --update --pre-release` and a reboot fixed it for me. If I had to guess, it's not a specific version of WSL that fixes the problem, but rather the process of updating it.
