### ISSUE TITLE
Can't activate distro with custom kernel built with WSL2-Linux_Kernel Project

### ISSUE THREAD

**Issue by Fang-GotATaste** [microsoft/WSL#12178]
### Windows Version

Microsoft Windows [version 10.0.26100.2033]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

I don't know.     "wsl.exe --status" return: "default distro:docker-desktop-data   default version:2"

### Distro Version

Ubuntu 22.04 LTS

### Other Software

Docker Desktop Windows,
"docker version" return "Version:25.0.3       Go version:1.21.6"
I don't know if its wanted and which helps.

### Repro Steps

In wsl I do:
"   git clone https://github.com/microsoft/WSL2-Linux-Kernel
    cd WSL2-Linux-Kernel
    cp Microsoft/config-wsl .config
    sudo apt update
    make menuconfig"
and success.

Then I configure in the menu: 
I "<m>"and"[ * ]" every options in "Network support"
and make the kernel.

I add "kernel=[address]"in file C:\Users\user\.wslconfig and it works.

Then I shutdown wsl and try activate the distro.

### Expected Behavior

the distro will be activated then I will do"make modules_install"

### Actual Behavior

the distro can't activate and the terminal just flash and disappear.(I use WSL Manager)
If i change kernel address in C:\Users\user\.wslconfig to target the old kernel, the distro work normally(at least outwardly).It doesn't work in any custom kernel I bulit. I try a few times making in configurations as above.

**Comment by Fang-GotATaste** [comment]
[WslLogs-2024-10-17_18-52-41.zip](https://github.com/user-attachments/files/17411310/WslLogs-2024-10-17_18-52-41.zip)

**Comment by sirredbeard** [comment]
The WSL config file needs to be `C:\\Users\\user\\.wslconfig`. Can you please share a copy of your `.wslconfig` file?

The 5.* branch of the WSL kernel does not support loadable modules, you need to use the experimental 6.* branch, see [docs](https://learn.microsoft.com/en-us/community/content/wsl-user-msft-kernel-v6).

> I ""and"[ * ]" every options in "Network support"

Can I ask why you are doing this? What are you actually trying to get to? That might be the underlying issue here.

**Comment by Fang-GotATaste** [comment]
@sirredbeard Thank you very much for your answer.use kernel v6(follow the docs) then rebuild with only [*] option openvswitch solve my problem.The answer to your curiosity is that I want to use Openvswitch on WSL, but it doesn’t support it directly.Then I was just following along with a not-so-reliable tutorial I found online.
