### ISSUE TITLE
The OS version I have is: 10.0.14393 corresponds to Windows 10 Anniversary Update (also known as version 1607), trying to download WSL for OpenFOAM

### ISSUE THREAD

**Issue by dsrivas1** [microsoft/WSL#12198]
So, my OS version is above and I was wondering if it's possible to even download WSL1 on it. I have Hyper-V installed and everything, but whenever I try to run the: dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart 

command, it says, that Microsoft-Windows-Subsystem-Linux is not found, I assume its because I have too old of a version right? For more context, I deployed the Windows VM on NebulaCloud.ai

**Comment by benhillis** [comment]
Correct. That version of Windows is nearly 10 years old, you will need a newer version.
