### ISSUE TITLE
Qt Installer (5.7)

### ISSUE THREAD

**Issue by kf71** [Microsoft/WSL#1219]
Try to install Qt 5.7 from qt-unified-linux-x64-2.0.3-1-online.run
(https://www.qt.io/download-open-source)

Stop installation at 59%

End with:
Error during installation process qt.5.7.gcc_64
the output /opt/Qt/5.7/gcc_64/bin/qmake -query is not parseable

Windows build number = 10.0.14393

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, there was another qt install failure posted in #838.  Can you please take a strace of the failing install so we can check if this is a known issue?

**Comment by kf71** [comment]
Same install as #838 but not the same bug.
- Xming as X server

input in the terminal:
export DISPLAY=:0.0
./qt-unified-linux-x64-2.0.3-1-online.run

output in the terminal:
[30706273] Warning: "/opt/Qt/5.7/gcc_64/bin/qmake" process is still running, need to kill it.
[30706445] Warning: QProcess: Destroyed while process ("/opt/Qt/5.7/gcc_64/bin/qmake") is still running.
3 times then
[30817619] Warning: Cannot get any query output from executable: '/opt/Qt/5.7/gcc_64/bin/qmake'
[30828292] Warning: QProcess: Destroyed while process ("/opt/Qt/5.7/gcc_64/bin/qmake") is still running.

In the output window:
Error during installation process (qt.5.7.gcc_64)
the output /opt/Qt/5.7/gcc_64/bin/qmake -query is not parseable.

**Comment by aseering** [comment]
Hi @kf71 -- thanks for posting!  Please file a separate ticket for this new issue.  You can reference the existing ticket by including the string " #1219 " in the other ticket's body or in a comment on it.

Also, when filing a ticket, please fill out the ticket template completely.  In particular, as has been requested, please include an `strace` of the failing command.  (If you're not sure how to run a command under attack, feel free to ask, or search around this bug tracker as I believe it is described on other ticket's.)

I know it's a lot of detail to provide.  But this forum is monitored by Microsoft developers, not Microsoft support personnel.  (If you want professional support, MS offers that service separately.). Those devs aren't building Qt; they're implementing syscalls, and attach tells them what syscalls are misbehaving for Qt.  If you want something that they immediately recognize and triage promptly, it helps enormously if you can translate your problem to their language.

**Comment by aseering** [comment]
Also, for what it's worth, I have successfully run the graphical Qt 5.5 installer within a much-older version of WSL.  So something changed between Qt 5.5 and 5.7, and/or WSL from months ago to WSL today.

I know one change in Qt between now and then is that it now relies on Google Chrome's rendering engine for a subset of its Web-related widgets.  I know that Chrome itself stresses a variety of things that aren't yet correctly or fully implemented in WSL.

**Comment by tiagomacarios** [comment]
I have 5.7 running under WSL. The problem is with the Qt installer. I opened a ticket with the Qt company https://bugreports.qt.io/browse/QTBUG-55149
The same problem happens when trying to use the installer on docker. So I don't think it is WSL related.

In the mean time here are instructions to get it working:
1 - Install it on another ubuntu machine and tar.gz the installation
2 - on WSL install the dependencies:
```
apt-get install -y --no-install-recommends \
    `#all below this line are QT dependencies` \
    libegl1-mesa \
    libfontconfig \
    libglu1-mesa \
    libsm6 \
    libxi6 \
    libxrender1 \
    mesa-common-dev
```
3 - install xming (or whatever Xserver floats your boat)
4 - set-p environement:
```
    echo -e '#!/bin/bash\nexport PATH=$PATH:/opt/Qt5.7.0/5.7/gcc_64/bin/\nexport DISPLAY=:0' > /etc/profile.d/qt.sh
    chmod +x /etc/profile.d/qt.sh
    source /etc/profile.d/qt.sh
```
5 - profit!
