### ISSUE TITLE
WSL2 uninstall allows distributions to run without WSL management service and therefore WSL plugins are not active

### ISSUE THREAD

**Issue by jxy-s** [microsoft/WSL#12202]
### Windows Version

10.0.22631.4317

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Install WSL using the provided MSI from https://github.com/microsoft/WSL/releases
2. Install a distribution `wsl --install -d Ubuntu`
3. Use the distribution `wsl`
4. Uninstall WSL `wsl --uninstall`
5. Use the distribution `wsl`

- Observe that the WSL2 distribution is active and useable without the `WSL Service` (`wslservice.exe`)
- Observe that the distribution version is WSL2 `wsl --list -v`
- Observe that no WSL plugins are loaded, since they are loaded and called out via the `WSL Service`.
    - https://learn.microsoft.com/en-us/windows/wsl/wsl-plugins
- In this configuration WSL plugins are not giving visibility into WSL2 activity on the system.
- Consider this a potential security vulnerability since there are security products that provide WSL plugins that give Linux integrations, WSL visibility and monitoring.
    - https://learn.microsoft.com/en-us/defender-endpoint/mde-plugin-wsl

Note: I am not sure if this is an expected configuration or state for WSL or not. I am unable to find any documentation on this. But overall it seems like undesired behavior at best or a potential security vulnerability or bypass at worst.

### Expected Behavior

When WSL2 is active on the machine and WSL plugins are registered with the Windows Subsystem for Linux. Starting virtual machines or distribution containers should result in the WSL plugin being notified of this activity.

### Actual Behavior

When WSL is "uninstalled"( `wsl --uninstall`) the WSL2 virtual machines and containers are still allowed to start despite the WSL Service not being installed and active on the system. This results in WSL plugins not being notified of WSL2 activity on the system.

```
> wsl --list -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

> sc query WSLService
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.
```

Another consequence of this state is that certain commands do not result in expected:
```
> wsl --version
[outputs help text?]

>  wsl --update
Installing: Windows Subsystem for Linux
The system cannot find the file specified.
```

**Comment by benhillis** [comment]
This is by design. If you don't want users to be able to use the inbox version of WSL (which does not support Intune policies) you must set this policy to false.

Allow the Inbox version of the Windows Subsystem for Linux
https://learn.microsoft.com/en-us/windows/wsl/intune#recommended-settings
