### ISSUE TITLE
Forced store updates crashes WSL processes

### ISSUE THREAD

**Issue by interj** [microsoft/WSL#12204]
### Windows Version

Microsoft Windows [Version 10.0.22635.4000]

### WSL Version

2.3.25.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

From time to time entire WSL is forcibly stopped by an update from Microsoft Store (automatic updates are not turned on). Windows Updates are manual due to a policy setting. 
All processes go down with
```
[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```
and "Modified minutes ago" can be seen in "Recent updates" in Microsoft Store. 

This makes WSL inherently unstable if everything can be brought down by a store-pushed update.

### Expected Behavior

Store needs to respect automatic updates settings for the critical system components. 

At the very least forced update notice allowing WSL user to take action is needed.

### Actual Behavior

WSL processes crash without any way to prevent it.

**Comment by jovere** [comment]
I've been having this exact problem with it happening twice in as many weeks. I'm fine with the update, but I'd like the ability to do a proper shutdown before it happens. This is equivalent to pulling the plug or yanking the battery on a windows machine and has led to data loss and potentially corruption.

@benhillis so you're saying that crashing all my running applications on a whim without any notification or chance to save data is a feature?

**Comment by mailinglists35** [comment]
Has something changed recently in Microsoft Store/WSL1 under Windows 10 22H2?

This issue seemed to be gone for a while, but today I found my wsl sessions closed.

I have Windows Updates turned off, Microsoft Store auto update turned off, but today I found Microsoft Store in this state and my WSL1 terminal sessions closed with message

````
$ Error: 0xd00002fe
Error code: Wsl/Service/0xd00002fe

[process exited with code 4294967295 (0xffffffff)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
````

![Image](https://github.com/user-attachments/assets/520eef0d-3257-483e-93fa-4ef368037960)

wsl logs: 

[WslLogs-2025-06-26_14-56-33.zip](https://github.com/user-attachments/files/20926007/WslLogs-2025-06-26_14-56-33.zip)

**Comment by mohag** [comment]
It is no longer possible to switch off updates to keep WSL from being restarted.

Windows Terminal no longer seems to randomly die on restarts, so it seems that it is possible...
