### ISSUE TITLE
WSL crashes with "Catastrohic Failure" when installing from a headless context

### ISSUE THREAD

**Issue by Paradoxis** [microsoft/WSL#12207]
### Windows Version

Microsoft Windows [Version 10.0.19045.2965]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

N/A

### Distro Version

N/A

### Repro Steps

Use Sysinternals' PsExec64 to elevate to `NT AUTHORITY\SYSTEM`

```
.\PsExec64.exe -accepteula -s -i \\127.0.0.1 cmd.exe
```

Run WSL

```
wsl.exe --install
```

### Expected Behavior

WSL runs normally and exits, preferably it installs something

### Actual Behavior

WSL crashes with a "a t a s t r o p h i c  f a i l u r e" message

![Image](https://github.com/user-attachments/assets/8a168ab4-1b2d-4820-bc8a-fbc756790762)

**Comment by Paradoxis** [comment]
[WslLogs-2024-10-26_11-18-12.zip](https://github.com/user-attachments/files/17531621/WslLogs-2024-10-26_11-18-12.zip)

**Comment by benhillis** [comment]
For installing from session zero could you please download the .msi from our GitHub releases and install that way?

**Comment by Paradoxis** [comment]
@benhillis installing through MSI seems to work, but when using WSL itself through session 0 I still get strange formatting errors, as well as an access denied error, although running it over SSH seems to work fine. 

Through PsExec:

![Image](https://github.com/user-attachments/assets/7bf86dd9-d896-46c7-90b5-50c202c41999)

Through SSH:

![Image](https://github.com/user-attachments/assets/178ec510-bbd9-4032-bf47-e3c88c3b6bcf)

**Comment by Elibar19** [comment]
Hi there, try this solution. Go to Win+R --> regedit  --> HKEY_CURRENT_USER/Control Panel/International/Geo and edit the value of Nation with the code of your country where you live --> https://learn.microsoft.com/es-es/windows/win32/intl/table-of-geographical-locations
