### ISSUE TITLE
WSL --class not registered

### ISSUE THREAD

**Issue by Swapnil-070904** [microsoft/WSL#12219]
I did a system reset due to some reason after that i was trying to install docker desktop but it showed some error regarding WSL when I tried to install WSL it showing class not registered I tried so many fixes from another issues and required windows features are also enabled but error still same it was working fine before system reset.

![Image](https://github.com/user-attachments/assets/1df78011-665b-4fe4-94d4-d0e48ae236c4)

```
C:\Users\ak680>wsl --install
Class not registered
Error code: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG
```
Please help me solve this issue.
[WslLogs-2024-10-31_08-19-34.zip](https://github.com/user-attachments/files/17574455/WslLogs-2024-10-31_08-19-34.zip)

**Comment by Swapnil-070904** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs
> Download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The script will output the path of the log file once done.
> 
> If this is a networking issue, please use [collect-networking-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1), following the instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues)
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here for more info on logging](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue and reply with '/emailed-logs'.
> 
> # View similar issues
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!
> 
> ### Closed similar issues:
> * [wsl not responding just saying class not registered (#11892)](https://github.com/microsoft/WSL/issues/11892),  similarity score: 0.75
> * [Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#10882)](https://github.com/microsoft/WSL/issues/10882),  similarity score: 0.73
> * [Class not registered Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11999)](https://github.com/microsoft/WSL/issues/11999),  similarity score: 0.73
> * [Class not registered Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11705)](https://github.com/microsoft/WSL/issues/11705),  similarity score: 0.72
> * [Unregistered class Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11641)](https://github.com/microsoft/WSL/issues/11641),  similarity score: 0.71
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

/question

**Comment by Swapnil-070904** [comment]
> # Logs are required for review from WSL team
> If this a feature request, please reply with '/feature'. If this is a question, reply with '/question'. **Otherwise please attach logs by following the instructions below**, your issue will not be reviewed unless they are added. These logs will help us understand what is going on in your machine.
> 
> How to collect WSL logs
> Download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The script will output the path of the log file once done.
> 
> If this is a networking issue, please use [collect-networking-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1), following the instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues)
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here for more info on logging](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue and reply with '/emailed-logs'.
> 
> # View similar issues
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!
> 
> ### Closed similar issues:
> * [wsl not responding just saying class not registered (#11892)](https://github.com/microsoft/WSL/issues/11892),  similarity score: 0.75
> * [Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#10882)](https://github.com/microsoft/WSL/issues/10882),  similarity score: 0.73
> * [Class not registered Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11999)](https://github.com/microsoft/WSL/issues/11999),  similarity score: 0.73
> * [Class not registered Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11705)](https://github.com/microsoft/WSL/issues/11705),  similarity score: 0.72
> * [Unregistered class Error code: Wsl/CallMsi/REGDB_E_CLASSNOTREG (#11641)](https://github.com/microsoft/WSL/issues/11641),  similarity score: 0.71
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

/question

**Comment by Swapnil-070904** [comment]
> Diagnostic information
> ```
> Issue was edited and new log file was found: https://github.com/user-attachments/files/17574455/WslLogs-2024-10-31_08-19-34.zip
> Detected appx version: 2.3.24.0
> Detected user visible error: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG
> Detected user visible error: Wsl/CallMsi/Install/REGDB_E_CLASSNOTREG
> ```

how can i resolve this issue

**Comment by liuzhch-Orka** [comment]
Same error code.
You can try to install the latest WSL from https://github.com/microsoft/WSL/releases
Works for me.

**Comment by benhillis** [comment]
We've recently made some changes to detect broken COM registrations, could you try a new pre-release version of WSL and see if you are able to reproduce this?
