### ISSUE TITLE
Can not access Dev Drive (ReFS) in WSL Terminal window after upgrading to 24H2

### ISSUE THREAD

**Issue by cubano100pct** [microsoft/WSL#12220]
### Windows Version

Microsoft Windows [Version 10.0.26100.2161]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04.5 LTS

### Other Software

None

### Repro Steps

Open WSL Terminal window and `cd h` or  `cd /mnt/h` to my dev drive, which is **h** and I get **Permission denied**
```
felix@FELIX-AMD:~$ ls -l
total 4
lrwxrwxrwx 1 felix felix    7 Apr 10  2024 c -> /mnt/c/
lrwxrwxrwx 1 felix felix    7 Apr 10  2024 d -> /mnt/d/
lrwxrwxrwx 1 felix felix    7 Apr 10  2024 e -> /mnt/e/
lrwxrwxrwx 1 felix felix    7 Apr 10  2024 f -> /mnt/f/
lrwxrwxrwx 1 felix felix    7 Jul 19 16:18 h -> /mnt/h/
-rw------- 1 felix felix    0 Sep 17 22:53 history.log
drwxr-xr-x 3 felix felix 4096 Aug  1 09:58 oradiag_felix
lrwxrwxrwx 1 felix felix   16 Aug  4 11:41 projects -> /mnt/h/projects/
lrwxrwxrwx 1 felix felix   12 Apr  2  2024 work -> /mnt/d/work/
felix@FELIX-AMD:~$ cd h
-bash: cd: h: Permission denied
felix@FELIX-AMD:~$ cd /mnt/h
-bash: cd: /mnt/h: Permission denied
felix@FELIX-AMD:~$

```

### Expected Behavior

I should be cd to my dev drive (H), just like can cd to my HDD (D)
```
felix@FELIX-AMD:~$ cd /mnt
felix@FELIX-AMD:/mnt$ ls -l
total 4
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 c
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 d
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 e
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 f
drwxrwxrwx 2 root  root  4096 Mar 20  2024 g
d--------- 0 felix felix    0 Dec 31  1969 h
drwxrwxrwt 2 root  root    60 Oct 30 10:23 wsl
drwxrwxrwt 7 root  root   300 Oct 30 10:23 wslg
felix@FELIX-AMD:/mnt$ cd d
felix@FELIX-AMD:/mnt/d$ ls
'$RECYCLE.BIN'  'Calibre Library'  'System Volume Information'   devdrive.vhdx   work
 3d_printer     'Stream Deck'       dev                          projects
felix@FELIX-AMD:/mnt/d$ cd ..
felix@FELIX-AMD:/mnt$
``` 

### Actual Behavior

I can not cd to my dev drive (H). If you noticed in the Expected behavior section the permissions for rwx are missing for h
```
felix@FELIX-AMD:/mnt$ cd h
-bash: cd: h: Permission denied
felix@FELIX-AMD:/mnt$
```
I tried changing the permission and it did not work
```
felix@FELIX-AMD:/mnt$ sudo chmod 777 h
[sudo] password for felix:
felix@FELIX-AMD:/mnt$ ls -l
total 4
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 c
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 d
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 e
drwxrwxrwx 1 felix felix 4096 Oct 29 09:41 f
drwxrwxrwx 2 root  root  4096 Mar 20  2024 g
d--------- 0 felix felix    0 Dec 31  1969 h
drwxrwxrwt 2 root  root    60 Oct 30 10:23 wsl
drwxrwxrwt 7 root  root   300 Oct 30 10:23 wslg
felix@FELIX-AMD:/mnt$
```

**Comment by kurikomoe** [comment]
same here, updated KB5044384 3 hours ago and found that I had no access to the ReFS disk.

![Image](https://github.com/user-attachments/assets/0b107d46-688c-469f-b6ce-9d7632ad64da)

uninstall KB5044384  got this error message:
![Image](https://github.com/user-attachments/assets/39260ff5-8e8b-43ef-8302-cc26f4da4470)

Tried to use system restore point to recovery the system, but the restore point failed with "object not found".

here is my log
[WslLogs-2024-10-31_03-18-55.zip](https://github.com/user-attachments/files/17577885/WslLogs-2024-10-31_03-18-55.zip)

**Comment by jonaslang1** [comment]
#12156 same problem described here

**Comment by clansty** [comment]
Created a vhd with NTFS to temporary bypass this issue
