### ISSUE TITLE
SSH no longer working (hangs)

### ISSUE THREAD

**Issue by seancorfield** [microsoft/WSL#12226]
### Windows Version

Microsoft Windows [Version 10.0.26120.2200]

### WSL Version

2.3.25.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 20.04

### Other Software

PS C:\Users\seanc> wsl --version
WSL version: 2.3.25.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26120.2200

### Repro Steps

Running `ssh someuser@some.server.ip` hangs. It was working fine last week.

`ssh` works in Powershell. `ssh` with the same user/ip hangs on Ubuntu 20.04 and Oracle 8.8 on multiple machines.

### Expected Behavior

`ssh` should connect on WSL2 distros, just like it does on Powershell (and like it used to just last week).

### Actual Behavior

`ssh` on WSL2 hangs. `ssh` on Powershell connects just fine.

### Diagnostic Logs

Happy to provide any/all diagnostic logging if you can let me know how to get the information.

**Comment by seancorfield** [comment]
`ssh -vvv` output (IP changed to protect server identity:
```
> ssh -vvv myuser@10.8.234.56
OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/sean/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 10.8.234.56 is address
debug2: ssh_connect_direct
debug1: Connecting to 10.8.234.56 [10.8.234.56] port 22.
```

**Comment by seancorfield** [comment]
Your email server rejected the .zip file I sent!

**Comment by seancorfield** [comment]
Gmail won't let me send you the .zip file. I don't want to attach it here.

**Comment by seancorfield** [comment]
I sent it from a different email account. Hopefully, it gets through.

**Comment by elsaco** [comment]
`It was working fine last week` does this mean it was working in `wsl-2.3.24`? Looks like you upgraded to `wsl-2.325` already and this version was released last week.

There's only one entry in the changelog of `2.3.25`:

`Automatically fall back to virtioProxy networking mode if NAT networking mode fails`

Are you using `mirrored` or `nat` mode?

Using a newer version of ssh it didn't repro on my setup:

```
elsaco@miami:~$ ssh -vvv elsaco@192.168.1.198
OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.14 4 Jun 2024
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.1.198 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/elsaco/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/elsaco/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to 192.168.1.198 [192.168.1.198] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
---cat---
```

Some WSL info:

```
elsaco@miami:~$ wslinfo --wsl-version
2.3.25
elsaco@miami:~$ wslinfo --networking-mode
nat
```

**Comment by seancorfield** [comment]
```
Thu Oct 31 14:41:38
(~)-(!2001)-> wslinfo --wsl-version
2.3.25

Thu Oct 31 14:41:40
(~)-(!2002)-> wslinfo --networking-mode
nat
```
I guess it's probably time to move to a more recent distro than Ubuntu 20.04 at this point...?

**Comment by seancorfield** [comment]
I tried it on Ubuntu 24 with a more recent OpenSSH and it still hangs:
```
OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024
```

**Comment by seancorfield** [comment]
> does this mean it was working in wsl-2.3.24?

Yes. (sorry I didn't answer that earlier)

**Comment by seancorfield** [comment]
I switched to `mirrored` networking, rebooted and retried. After a pause (at the `debug1: Connecting to 10.8.234.56 [10.8.234.56] port 22.` line), it failed with `No route to host`.

Is there any way to "downgrade" WSL to 2.3.24 to that version?

**Comment by seancorfield** [comment]
I see 2.3.26 was released. `ssh` is still broken for me in that new version too.
