### ISSUE TITLE
WSL2 driver directory is using to much disk space

### ISSUE THREAD

**Issue by jadentohjm** [microsoft/WSL#12223]
I searched Google for a solution to reduce WSL2 disk space and found a guide on shrinking the virtual disk. It helped me reduce 44GB to 32GB now.

But the main issue is that my physical disk is running low and the WSL2 driver directory uses 224GB out of 237 GB. It;'s the same as my C driver.
I can't any guide or any discussion on the WSL2 driver directory that used so much disk space.
Does anyone have any idea if it is possible to delete it or clean it up?

![Image](https://github.com/user-attachments/assets/24a247c4-a009-4fa4-8c2a-0f573af2ca95)

**Comment by sirredbeard** [comment]
`/usr/lib/wsl/drivers` is automatically mounted and linked into your WSL filesystem from your Windows DriverStore, at `C:\Windows\System32\DriverStore\`.

It is not taking up space in your WSL filesystem's virtual file system, e.g. in the Ubuntu .VHDX that contains your WSL installation.

If you notice, the used and available space listed by `df` is actually the same as `C:\`.

**Comment by OneBlue** [comment]
Indeed @jadentohjm: /usr/lib/wsl/drivers is just a mountpoint that doesn't actually take space inside WSL. If you want to know where space is being taken, running something like `du -sh` would be the easiest way.
