### ISSUE TITLE
WSL2 ERROR

### ISSUE THREAD

**Issue by lucheshidi** [microsoft/WSL#12231]
### Windows Version

Microsoft Windows [Version 10.0.19045.5011]

### WSL Version

WSL Version： 2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 24.04

### Repro Steps

%USERPROFILE%/.wslconfig:
    [experimental]
    networkingMode=mirrored
    dnsTunneling=true
    firewall=true
    autoProxy=true
    hostAddressLoopback=true

PS C:\> wsl --shutdown
8 seconds left...
PS C:\> wsl 

### Expected Behavior

ubuntu@ubuntu:~$

### Actual Behavior

wsl: Hyper-V 防火墙不受支持
wsl: 不支持镜像网络模式： Windows 版本 19045.5011 没有所需的功能。
正在回退到 NAT 网络。
wsl: DNS 隧道不受支持
ubuntu@ubuntu:~$

**Comment by zcobol** [comment]
`networkingMode=mirrored` is not supported on Windows 10.
