### ISSUE TITLE
WSL Bug with python3 and pip installation

### ISSUE THREAD

**Issue by ianparizot** [microsoft/WSL#12251]
### Windows Version

Microsoft Windows [Version 10.0.22631.4391]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

`sudo apt-get install python3 python3-pip`

### Expected Behavior

It should have installed the python3 and python3-pip

### Actual Behavior

`sudo apt-get install python3 python3-pip`
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python-pip/python3-pip_22.0.2%2bdfsg-1ubuntu0.4_all.deb  404  Not Found [IP: 91.189.91.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`apt-get update`
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
`--fix-missing`
command not found

# Resolution
I found that I hadn't enabled Linux subsystem for Windows, that's why I couldn't install with sudo

**Comment by minhaics** [comment]
hello i got the same issue, i cannot fix it
