### ISSUE TITLE
Guest shutdown command is not reliable

### ISSUE THREAD

**Issue by leonbloy** [microsoft/WSL#12252]
### Windows Version

Microsoft Windows [Versión 10.0.22631.4317]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

### Distro Version

Ubuntu-22.04

### Repro Steps

From inside my Ubuntu session, I run `sudo shutdown now` 

I get a message of process terminated with code 1, and I'm invited to either close the terminal with Ctrl-D or press Enter to reboot.

In either case, when I start again the session, different issues (not deterministic) appear. In particular, if I immediately reboot and run  ` sudo shutdown now`  again, I get

```
Failed to connect to bus: Connection refused
Failed to open initctl fifo: No such device or address
Failed to talk to init daemon.
```

### Expected Behavior

I would expect that `sudo shutdown now`  performs a complete and clean shutdown of my distro session, same as terminating the session from outside (with wsl).  The host (wsl) should somehow get notified and perform its cleanup.

That is the behaviour of typical virtual machines hosts (eg: Virtualbox).

### Actual Behavior

It seems that `sudo shutdown now` is not enough to perform a complete and clean shutdown from inside my Linux session. 

It seems I'm still required to shutdown the sesion calling the outside command, with `wsl -s DISTRO_NAME` . This is not clean or ideal, I wish to be able to shutdown my virtual machine from inside - the Windows path is not always available from inside, and it's inconvenient to have to recall the session name (especially when I started the session from the terminal, for example).

### Diagnostic Logs

_No [response_[](url)]([WslLogs-2024-11-09_17-29-09.zip](https://github.com/user-attachments/files/17689277/WslLogs-2024-11-09_17-29-09.zip)
)

**Comment by zcobol** [comment]
@leonbloy it's a container so `shutdown` won't do you any good! Just use `exit`!
