### ISSUE TITLE
Bad tcp behavior under mirrored network

### ISSUE THREAD

**Issue by LHe496** [microsoft/WSL#12269]
### Windows Version

Microsoft Windows [Version 10.0.26100.2314]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

telnet 0.17-44build1 arm64

### Repro Steps

On Windows on Arm wsl2 with a mirrored network, use telnet to connect to an unexisting port.
Suppose there is no process listening to port 8677:
telnet 127.0.0.1 8677

### Expected Behavior

Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

### Actual Behavior

Trying 127.0.0.1...

The telnet will wait for a long time to report time out.

**Comment by LHe496** [comment]
It's Windows on Arm only. It's fine on amd64 PC.

**Comment by LHe496** [comment]
The log file:
[WslLogs-2024-11-15_17-07-02.zip](https://github.com/user-attachments/files/17772481/WslLogs-2024-11-15_17-07-02.zip)

**Comment by CatalinFetoiu** [comment]
@LHe496 thanks for reporting the issue

this sounds similar to https://github.com/microsoft/WSL/issues/10855

to confirm it's the same issue, could you please collect networking logs using https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1? the script will generate a "WslNetworkingLogs" zip

It's interesting that the issue happens only on arm but not on amd

**Comment by LHe496** [comment]
Networking log:
[WslNetworkingLogs-2024-11-16_14-17-21.zip](https://github.com/user-attachments/files/17783744/WslNetworkingLogs-2024-11-16_14-17-21.zip)

**Comment by LHe496** [comment]
BTW, I've tested the procedure mentioned on #12245. It's the same to me. I think maybe it's the same problem since before updating wsl to version 2.3.26.0, I've experienced the same problem under wsl version 2.3.24.0.

**Comment by CatalinFetoiu** [comment]
thanks for sending the logs
it seems to be the same symptom as https://github.com/microsoft/WSL/issues/10855

the RST packet should have destination port same as the source port of the SYN packet (45823), but the destination port is altered (it's 60362)

14:18:27.853583 loopback0 Out ifindex 2 00:15:5d:1e:ac:f8 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 26490, offset 0, flags [DF], proto TCP (6), length 60)
    127.0.0.1.**45823** > 127.0.0.1.8677: **Flags [S]**, cksum 0xfe30 (incorrect -> 0x3579), seq 2562497111, win 64240, options [mss 1460,sackOK,TS val 764011537 ecr 0,nop,wscale 7], length 0
14:18:27.854132 loopback0 In  ifindex 2 00:15:5d:ee:ac:99 ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 128, id 45691, offset 0, flags [DF], proto TCP (6), length 40)
    127.0.0.1.8677 > 127.0.0.1.**60362**: **Flags [R.]**, cksum 0xfe1c (incorrect -> 0x7109), seq 0, ack 2562497112, win 0, length 0
14:18:28.904890 loopback0 Out ifindex 2 00:15:5d:1e:ac:f8 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 26491, offset 0, flags [DF], proto TCP (6), length 60)

**Comment by LHe496** [comment]
Something mysterious happens. After I installed wireshark to capture the traffic, it turns out to be fine that Windows seems to be able to sent back message to the right port. If I stop wireshark from capturing, it brokes again. Maybe this could be a clue.

**Comment by MichiBab** [comment]
The wireshark capturing did not fix it on my side sadly.

**Comment by shixudong2020** [comment]
it seem to hyper-v's hse-hostvnic problem,not wsl's
solution:win11 update to 24H2
temporary solution:open wireshark,no actual capture is required
