### ISSUE TITLE
Installed GPU driver in wsl by mistake, how to recover?

### ISSUE THREAD

**Issue by aalex1945** [microsoft/WSL#12272]
I installed the NVIDIA GPU driver, cudatoolkit, and cudnn on Windows. But I omitted the notice on CUDA guide page for wsl and installed all GPU driver, cudatoolkit, and cudnn in wsl too. Now I cannot use GPU in my wsl. How to recover from that? Thanks.

**Comment by OneBlue** [comment]
You would need to either follow the CUDA instructions if you installed the driver manually, or use the distribution's package manager to remove them.
