### ISSUE TITLE
WSL2 Docker Build Hangs on downloading for a long time

### ISSUE THREAD

**Issue by ismailbayram** [microsoft/WSL#12270]
### Windows Version

Microsoft Windows [Version 10.0.22631.4317]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 24.04

### Repro Steps

I don't know, it happened suddenly.

### Expected Behavior

I hope it should download and build the image under a minute like it used to be!

### Actual Behavior

WSL2 Docker Build hangs on downloading anything for a long time.
![Image](https://github.com/user-attachments/assets/48178e6e-4284-452e-9a10-f080185c8757)

**Comment by elsaco** [comment]
@ismailbayram please check the syntax, it should be `RUN apt update` instead of `RUN apk update`. See the `yellow` line in your output.

**Comment by zcobol** [comment]
@ismailbayram please check your docker networking. Looks like it's not working 😀

I did a quick test using `Docker version 27.3.1, build ce12230` running inside `WSL Ubuntu 24.04.1` and the build finishes in seconds. All the packages are pulled in. 

`Dockerfile` used for testing, running your failed command:

```
FROM alpine:latest
RUN apk update && apk add libpq-dev postgresql-dev gcc python3-dev musl-dev gettext
CMD ["/bin/ash"]
```

and `docker build` output:

```
[+] Building 9.3s (6/6) FINISHED                                                                                           docker:default
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 157B                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                     0.7s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => CACHED [1/2] FROM docker.io/library/alpine:latest@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a        0.0s
 => [2/2] RUN apk update && apk add libpq-dev postgresql-dev gcc python3-dev musl-dev gettext                                        7.1s
 => exporting to image                                                                                                               1.4s
 => => exporting layers                                                                                                              1.4s
 => => writing image sha256:1899886259178f5f17e0f69f0224e72ad12119af330225b807572712749808d9                                         0.0s

```

**Comment by ismailbayram** [comment]
@zcobol thank you for your response, i've scanned the all contents about docker networking but I've failed at fixing it.

**Comment by ismailbayram** [comment]
SOLUTION:
https://superuser.com/a/1756466
`You need to install Hyper-V Manager tools:

Hit Win+R;
Type "optionalfeatures" and hit Enter;
Search "Hyper-V" and check the checkbox;
Hit "OK" and restart computer.`
