### ISSUE TITLE
Can't install WSL on win11 family edition?

### ISSUE THREAD

**Issue by 809825706** [microsoft/WSL#12285]
### Windows Version

Microsoft Windows [版本 10.0.26100.2314]

### WSL Version

2.3.26

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

`wsl --install`

### Expected Behavior

install WSL on win11 family edition

### Actual Behavior

![Image](https://github.com/user-attachments/assets/312646a1-c062-4ace-acfd-2dac3d4b67f4)

**Comment by Sherry520** [comment]
试试看看这个https://www.zhihu.com/question/423732623
