### ISSUE TITLE
wsl --install --from-file always install in WSL 2

### ISSUE THREAD

**Issue by crramirez** [microsoft/WSL#12298]
### Windows Version

Microsoft Windows [Version 10.0.26100.2033]

### WSL Version

2.4.4

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [x] WSL 1

### Repro Steps

```
wsl --set-default-version 1
wsl --install --from-file '.\distro.tar.gz'
wsl --list --verbose
```
![Image](https://github.com/user-attachments/assets/06a7bae8-9639-4a38-b080-73cd23f13b94)

### Expected Behavior

the distro should be in WSL1

### Actual Behavior

The distro was created in WSL2 regardless of the default version

**Comment by benhillis** [comment]
Good call, I will fix this.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.4.8.
