### ISSUE TITLE
`wslvar` v3.2.3-1 no longer works after upgrading WSL to 2.4.4.0

### ISSUE THREAD

**Issue by felipecrs** [microsoft/WSL#12295]
### Windows Version

10.0.26100.2314

### WSL Version

2.4.4.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Ubuntu 24.04

### Other Software

```console
$ wslvar --version
wslu v3.2.3-1; wslvar v03
```

### Repro Steps

`wslvar`, which used to work just fine, isn't working anymore (see _Actual Behavior_).

### Expected Behavior

To work as it did before.

### Actual Behavior

```console
$ wslvar USERPROFILE
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

### Diagnostic Logs

Please let me know if you need more details.

**Comment by felipecrs** [comment]
Note this issue doesn't happen with wslu v4.1.3-1. But I'm reporting anyway in case it's a regression that needs to be fixed.

**Comment by felipecrs** [comment]
Also, I'm not sure why but the logs collector simply hangs and doesn't do anything.

![Image](https://github.com/user-attachments/assets/af3237a0-3f07-4e21-a884-08281568326e)

**Comment by benhillis** [comment]
wslu / wslvar is not maintained by Microsoft. I suggest following up with the owner of that project. Happy to help debug if we broke something, but I don't even know where to start here.

**Comment by felipecrs** [comment]
Well, my point was that WSL 2.4.4.0 broke it.

**Comment by justus-camp-microsoft** [comment]
We don't maintain the tool and don't make any guarantees about not breaking it between releases. I would recommend opening an issue against the [tool's repo](https://github.com/wslutilities/wslu).

**Comment by felipecrs** [comment]
Alright. Since it's not broken in the tool's latest version, I will not open an issue there.

For posteriority, since even the newest Ubuntu on WSL still packages `wslu` v3, the solution is to install their PPA to have `wslu` upgraded to v4.
