### ISSUE TITLE
SSH not working on Bash on Windows

### ISSUE THREAD

**Issue by JeffTTT** [Microsoft/WSL#1229]
- A brief description
- open bash on Windows
- cd to a directory which had been set up with Gitlab repository
- git pull

Previously it worked without problems, it can pull updates from the Gitlab server, however it is not working now. It always says resource not available. However if I do git pull on a Linux virtual machine (on VMWare), it works; this proves that Gitlab server is fine.

I have verified that my SSH key has been corrected added in the git server.
- Expected results
  it should pull updates from the git server.
- Actual results (with terminal output if applicable)
  Here is the error message on bash on Windows
  $ git pull
  ssh: connect to host gitlab.com port 22: Resource temporarily unavailable
  fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
- Your Windows build number
  Edition: Windows 10 Pro Insider Preview
  Version: 1607
  OS Build: 14936.1000
- Steps / All commands required to reproduce the error from a brand new installation 
- open bash on Windows
- cd to a directory which had been set up with Gitlab repository
- git pull
- Strace of the failing command
  $ strace git pull
  execve("/usr/bin/git", ["git", "pull"], [/\* 16 vars _/]) = 0
  brk(0)                                  = 0x1a63000
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a8bf90000
  access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
  open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
  fstat(3, {st_mode=S_IFREG|0644, st_size=44010, ...}) = 0
  mmap(NULL, 44010, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8a8bf94000
  close(3)                                = 0
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  open("/lib/x86_64-linux-gnu/libpcre.so.3", O_RDONLY|O_CLOEXEC) = 3
  read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\27\0\0\0\0\0\0"..., 832) = 832
  fstat(3, {st_mode=S_IFREG|0644, st_size=252032, ...}) = 0
  mmap(NULL, 2347200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8a8b9c0000
  mprotect(0x7f8a8b9fd000, 2093056, PROT_NONE) = 0
  mmap(0x7f8a8bbfc000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3c000) = 0x7f8a8bbfc000
  close(3)                                = 0
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
  read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\36\0\0\0\0\0\0"..., 832) = 832
  fstat(3, {st_mode=S_IFREG|0644, st_size=100728, ...}) = 0
  mmap(NULL, 2195784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8a8b7a0000
  mprotect(0x7f8a8b7b8000, 2093056, PROT_NONE) = 0
  mmap(0x7f8a8b9b7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f8a8b9b7000
  close(3)                                = 0
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  open("/lib/x86_64-linux-gnu/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
  read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320:\0\0\0\0\0\0"..., 832) = 832
  fstat(3, {st_mode=S_IFREG|0644, st_size=101240, ...}) = 0
  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a8bf80000
  mmap(NULL, 2206376, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8a8b580000
  mprotect(0x7f8a8b597000, 2097152, PROT_NONE) = 0
  mmap(0x7f8a8b797000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f8a8b797000
  mmap(0x7f8a8b799000, 6824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8a8b799000
  close(3)                                = 0
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
  read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) = 832
  fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
  mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8a8b360000
  mprotect(0x7f8a8b379000, 2093056, PROT_NONE) = 0
  mmap(0x7f8a8b578000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7f8a8b578000
  mmap(0x7f8a8b57a000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8a8b57a000
  close(3)                                = 0
  access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
  open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
  read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P \2\0\0\0\0\0"..., 832) = 832
  fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
  mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8a8af90000
  mprotect(0x7f8a8b14a000, 2097152, PROT_NONE) = 0
  mmap(0x7f8a8b34a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f8a8b34a000
  mmap(0x7f8a8b350000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8a8b350000
  close(3)                                = 0
  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a8bf70000
  mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a8bf60000
  arch_prctl(ARCH_SET_FS, 0x7f8a8bf60740) = 0
  mprotect(0x7f8a8b34a000, 16384, PROT_READ) = 0
  mprotect(0x7f8a8b578000, 4096, PROT_READ) = 0
  mprotect(0x7f8a8b797000, 4096, PROT_READ) = 0
  mprotect(0x7f8a8b9b7000, 4096, PROT_READ) = 0
  mprotect(0x7f8a8bbfc000, 4096, PROT_READ) = 0
  mprotect(0x779000, 4096, PROT_READ)     = 0
  mprotect(0x7f8a8be22000, 4096, PROT_READ) = 0
  munmap(0x7f8a8bf94000, 44010)           = 0
  set_tid_address(0x7f8a8bf60a10)         = 255
  set_robust_list(0x7f8a8bf60a20, 24)     = 0
  futex(0x7fffec2ced60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7f8a8bf60740) = -1 EAGAIN (Resource temporarily unavailable)
  rt_sigaction(SIGRTMIN, {0x7f8a8b3669f0, [], SA_RESTORER|SA_SIGINFO, 0x7f8a8b370330}, NULL, 8) = 0
  rt_sigaction(SIGRT_1, {0x7f8a8b366a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f8a8b370330}, NULL, 8) = 0
  rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
  getrlimit(RLIMIT_STACK, {rlim_cur=8192_1024, rlim_max=8192*1024}) = 0
  open("/dev/null", O_RDWR)               = 3
  close(3)                                = 0
  brk(0)                                  = 0x1a63000
  brk(0x1a84000)                          = 0x1a84000
  open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
  fstat(3, {st_mode=S_IFREG|0644, st_size=2919792, ...}) = 0
  mmap(NULL, 2919792, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8a8acc7000
  close(3)                                = 0
  stat(".git", 0x7fffec2cda20)            = -1 ENOENT (No such file or directory)
  access("/etc/gitconfig", R_OK)          = -1 ENOENT (No such file or directory)
  access("/home/jchang/.config/git/config", R_OK) = -1 ENOENT (No such file or directory)
  access("/home/jchang/.gitconfig", R_OK) = 0
  open("/home/jchang/.gitconfig", O_RDONLY) = 3
  fstat(3, {st_mode=S_IFREG|0666, st_size=19, ...}) = 0
  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a8bf50000
  read(3, "[color]\n\tui = auto\n", 4096) = 19
  read(3, "", 4096)                       = 0
  close(3)                                = 0
  munmap(0x7f8a8bf50000, 4096)            = 0
  access(".git/config", R_OK)             = -1 ENOENT (No such file or directory)
  pipe([3, 4])                            = 0
  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8a8bf60a10) = 256
  rt_sigaction(SIGINT, {0x4e08d0, [INT], SA_RESTORER|SA_RESTART, 0x7f8a8afc6cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fec64e26cb0}, 8) = 0
  rt_sigaction(SIGHUP, {0x4e08d0, [HUP], SA_RESTORER|SA_RESTART, 0x7f8a8afc6cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fec64e26cb0}, 8) = 0
  rt_sigaction(SIGTERM, {0x4e08d0, [TERM], SA_RESTORER|SA_RESTART, 0x7f8a8afc6cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fec64e26cb0}, 8) = 0
  rt_sigaction(SIGQUIT, {0x4e08d0, [QUIT], SA_RESTORER|SA_RESTART, 0x7f8a8afc6cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fec64e26cb0}, 8) = 0
  rt_sigaction(SIGPIPE, {0x4e08d0, [PIPE], SA_RESTORER|SA_RESTART, 0x7f8a8afc6cb0}, {SIG_DFL, [], SA_RESTORER, 0x7fec64e26cb0}, 8) = 0
  close(4)                                = 0
  read(3, "", 1)                          = 0
  close(3)                                = 0
  wait4(256, fatal: Not a git repository (or any parent up to mount point /home)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  [{WIFEXITED(s) && WEXITSTATUS(s) == 128}], 0, NULL) = 256
  exit_group(128)                         = ?
  +++ exited with 128 +++

**Comment by Manouchehri** [comment]
That strace has a different error message than the initial description.

```
wait4(256, fatal: Not a git repository (or any parent up to mount point /home)
```

What's the output of `ls -la` instead of `git pull`?

**Comment by therealkenc** [comment]
This one died on the vine in a unspoken need-repro state. The strace was:
```
wait4(256, fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
The strace wasn't threaded, but that's going to be `git` walking up the directory tree and not finding `.git`. In other words, WSL just following orders. If anyone has a set of CLI repro steps from a clean Ubuntu install from the store, and believes there is errant system call behaviour causing a problem with `git` or `ssh`, please open a new issue# following CONTRIBUTING.md.
