### ISSUE TITLE
WSL 2.4.x is not showing which is the default distro (Regression)

### ISSUE THREAD

**Issue by crramirez** [microsoft/WSL#12302]
### Windows Version

Microsoft Windows [Version 10.0.26100.2033]

### WSL Version

2.4.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

```powershell
PS > wsl echo '$WSL_DISTRO_NAME'
MyPengwin
PS > wsl --set-default WLinux
The operation completed successfully.
PS > wsl echo '$WSL_DISTRO_NAME'
WLinux

PS > wsl --list --verbose
  NAME                      STATE           VERSION
  MyPengwin                 Running         2
  WLinux                    Running         2
  docker-desktop            Stopped         2
  docker-desktop-data       Stopped         2
PS > wsl --status
Default Version: 1
```

### Expected Behavior

`wsl --list --verbose` should show an asterisk next the name of the default distro
`wsl --status` should say the name of the default distro 

### Actual Behavior

The default distro does not show neither --list or --status commands

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5.
