### ISSUE TITLE
Windows Defender Firewall does not work with WSL2

### ISSUE THREAD

**Issue by PeterTucker** [microsoft/WSL#12301]
### Windows Version

Microsoft Windows [Version 10.0.19044.5131]

### WSL Version

 2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Ubuntu 24.04

### Repro Steps

I tried to block outgoing traffic with Windows Defender for %SystemRoot%\System32\bash.exe and %SystemRoot%\System32\wsl.exe.
![Image](https://github.com/user-attachments/assets/93278fe1-f01d-434b-b9b0-a4acd4dc3b7b)

Unfortunately, it did not work. Tried pinging a local device 192.168.1.XXX, but it still sent/received packets.

### Expected Behavior

WSL should have it's packet's blocked when pinging another device on my network.

### Actual Behavior

It can ping other devices.

**Comment by OneBlue** [comment]
@PeterTucker: The network traffic doesn't actually come from wsl.exe when packets are sent out of WSL. 

If you want to do something like that, the best way would be to use [Hyper-V firewall](https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/hyper-v-firewall)
