### ISSUE TITLE
Does WSL2 plan to support dual CPUs?

### ISSUE THREAD

**Issue by hyjforesight** [microsoft/WSL#12323]
**Is your feature request related to a problem? Please describe.**
WSL2 doesn't support dual/multiple sockets of CPUs. Change settings by .wslconfig doesn't work. This issue persists and remain unsolved. See below:
https://github.com/microsoft/WSL/issues/4137
https://github.com/microsoft/WSL/issues/3314
https://github.com/microsoft/WSL/issues/5423
https://github.com/microsoft/WSL/issues/5472

**Describe the solution you'd like**
LET WSL2 SUPPORT DUAL SOCKETS OF CPUS. PLZ!

**Describe alternatives you've considered**
Give up Windows and use Ubuntu. This is definitely not what we Windows fans look forward to.

**Additional context**
AGAIN, LET WSL2 SUPPORT DUAL SOCKETS OF CPUS. PLZ!

**Comment by muratyurdakul75** [comment]
I am also expecting this. Even if it uses dual CPU, WSL does not currently support more than 64 processors. But even using dual CPUs would be a good development. Half of the server's resources are wasted right now. 1 CPU is working and the other is idle.

**Comment by sirredbeard** [comment]
This is a duplicate of [#1115](https://github.com/microsoft/WSL/issues/1115).

@muratyurdakul75 There are workaround for more than 64 cores, which is a separate issue. @xieyubo has [a solution](https://github.com/xieyubo/WSL2) and I have pre-built patched .dll for both amd64 and arm64 you can grab [on my fork](https://github.com/sirredbeard/WSL2-more-cores).

**Comment by benhillis** [comment]
> This is a duplicate of [#1115](https://github.com/microsoft/WSL/issues/1115).
> 
> [@muratyurdakul75](https://github.com/muratyurdakul75) There is a workaround for more than 64 cores, which is a separate issue. [@xieyubo](https://github.com/xieyubo) has [a solution](https://github.com/xieyubo/WSL2) and I have pre-built patched .dll's for both amd64 and arm64 you can grab [on my fork](https://github.com/sirredbeard/WSL2-more-cores).

Thanks! FYI I've sorted out a fix for this which should be coming soon.

**Comment by benhillis** [comment]
@sirredbeard and @xieyubo - after the fix goes live would you mind making a note in your project / fork that the workaround is no longer needed?

**Comment by xieyubo** [comment]
Sure.Sent from my iPhoneOn Dec 2, 2024, at 3:46 PM, Ben Hillis ***@***.***> wrote:﻿Re: [microsoft/WSL] Does WSL2 plan to support dual CPUs? (Issue ***@***.*** and @xieyubo - after the fix goes live would you mind making a note in your project / fork that the workaround is no longer needed?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you were mentioned.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyjforesight** [comment]
Hi @benhillis and @sirredbeard , thank you for making this workaround. BTW, is there any plan for supporting dual CPUs?
