### ISSUE TITLE
`wsl --install` catastrophic failure on version 2.4.4

### ISSUE THREAD

**Issue by CarlosNihelton** [microsoft/WSL#12324]
### Windows Version

Microsoft Windows [Version 10.0.26120.2415]

### WSL Version

2.4.4.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Ubuntu 24.04

### Repro Steps

Upgrade to latest pre-release (2.4.4.0) and run `wsl --install` without any more arguments.

### Expected Behavior

Some message about WSL being already installed or installing the default distro.

### Actual Behavior

```
$> wsl --install
Catastrophic failure
Error code: Wsl/InstallDistro/E_UNEXPECTED
```

### Diagnostic Logs

[WslLogs-2024-11-27_14-42-07.zip](https://github.com/user-attachments/files/17938254/WslLogs-2024-11-27_14-42-07.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @CarlosNihelton. This was indeed a regression in 2.4.4. 

Fixed by #12326 (the manifest update might take a bit to propagate),.
