### ISSUE TITLE
WIndows 11 LTSC WSL Install Airgapped

### ISSUE THREAD

**Issue by menardorama** [microsoft/WSL#12332]
Hi,

When trying to setup wsl in an airgap env, it silently fail. I have to re-enable internet to get it working.

Is there any procedure for that ? It seems that there is a userland setup  that need Internet.

Thanks a lot

**Comment by OneBlue** [comment]
@menardorama: What exactly do you mean by "silently fail" ? Can share /logs of such a failure ?
