### ISSUE TITLE
WSL distribution download shortlink for `wsl-ubuntu-1604` broken and missing shortlink for `wslubuntu2404`

### ISSUE THREAD

**Issue by Vampire** [microsoft/WSL#12336]
The WSL distribution download shortlink https://aka.ms/wsl-ubuntu-1604 points to https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx but that host seems to be down.
Using https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu_1604.2019.523.0_x64.appx instead works fine, so the shortlink should probably be updated with the new host.

Similarly, for 24.04 the shortlink https://aka.ms/wslubuntu2404 does not exist yet but the full link https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2404-240425.AppxBundle is listed on https://learn.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions, maybe it would make sense to also create such a shortlink for 24.04?

**Comment by elsaco** [comment]
@Vampire check the correct download links in https://github.com/microsoft/WSL/blob/719f865899f4c411cf6878dc15aa565753f24bd4/distributions/DistributionInfo.json

Information changes all the time, so `https://aka.ms` links must be updated.

**Comment by Vampire** [comment]
I was under the impression that this is exactly the sense of those shortlinks.
That you can use a permanent shortlink that is updated with the current actual link.
Otherwise none of those shortlinks actually makes too much sense.

**Comment by OneBlue** [comment]
Thank you for reporting this @Vampire. Those files are back online now.

**Comment by Vampire** [comment]
@OneBlue the 16.04 link is back up, thanks.
But there is still no 24.04 link. :-(
