### ISSUE TITLE
2.4.5.0 Event Log warning about number of processors (16>24)

### ISSUE THREAD

**Issue by teddy661** [microsoft/WSL#12348]
### Windows Version

Microsoft Windows [Version 10.0.19045.5131]

### WSL Version

 2.4.5.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

WSL logs an event about incorrect number of processors specified. Saying requested is greater than logical. I requested 16 I have 24. 

The description for Event ID 0 from source WSL cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

wsl2.processors cannot exceed the number of logical processors on the system (16 > 24)

The message resource is present but the message was not found in the message table

### Expected Behavior

I shouldn't get this event at all 

### Actual Behavior

Event written saying 16>24

**Comment by razielanarki** [comment]
can confirm (just installed wsl on an older Thinkpad L560, under windows 10):

```
C:\> wsl --version
WSL version: 2.4.5.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5198

C:\>wsl
wsl: wsl2.processors cannot exceed the number of logical processors on the system (1 > 4)
$
```
