### ISSUE TITLE
wsl --mount not working on arm64

### ISSUE THREAD

**Issue by etxaleku** [microsoft/WSL#12360]
### Windows Version

Microsoft Windows [Version 10.0.26100.2314]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Ubuntu 22.04

### Other Software

Existing issue #12038 was closed after waiting for logs.

WSL2 is from Windows Store and is up-to-date (ran wsl --update to be sure).
Windows 11 is up-to-date (ran Windows Update check for updates to be sure).

$ wsl.exe --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314

### Repro Steps

With WSL2 IO performance (and the Linux file security model) work much better for the native filesystem (ext4) though there is very much appreciated access to the Windows NTFS filesystems through the drvfs filesystem driver albeit at a slower IO rate. 

To reproduce:

- WIndows 11 on ARM64 machine (Microsoft Surface Pro 11 in my case).
- WSL2/Ubuntu 22.04 installed from Microsoft Store.
- Use Windows Disk Management to Create VHD outside of WSL2, in my case on external D: drive connected via USB.
- In Powershell get the physical disk number by running
`Get-Disk`
- Then try to mount the VHD by running
`wsl.exe --mount \\.\PhysicalDrive# --bare`

In my case the drive number of the new VHD was 2 so I tried running
`wsl.exe --mount \\.\PhysicalDrive2 --bare`
in a variety of contexts:
- from my normal user in Ubuntu/WSL2
- from the root user in Ubuntu/WSL2
- from an Administrator elevated Powershell

I am generally trying to follow the steps outlined in [https://joeferguson.me/adding-another-disk-to-wsl2/](https://joeferguson.me/adding-another-disk-to-wsl2/), though some of those steps are apparently outdated.  Like the process to get the VHD drive number, so I eventually figured out that (these days) a simple Get-Disk in Powershell will interactively provide the number.

### Expected Behavior

New VHD will mount into Ubuntu where an ext4 filesystem can then be created and the resultant ext4 filesystem can then be mounted and used for normal file handling from that point forward.

So basically now a `df` command in Linux would show the usual `/` (root ext4) filesystem, all the `drvfs` filesystems exposing the various NTFS Windows "drives", plus this new ext4 filesystem which happens to be on a different physical disk than the root filesystem.  Expectation is that the IO performance of the new VHD would be similar to the root filesystem (after taking into account any physical limitations due to the disk characteristics and interfaces, e.g. SSD vs spinning, USB, etc).

### Actual Behavior

`PS C:\> wsl --mount \\.\PhysicalDrive2 --bare`
`wsl.exe --mount is not supported for ARM64 on this version of Windows.`
`Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED`

also tried

`PS C:\> wsl --mount --vhd D:\media\extdisk.vhdx --bare`
`wsl.exe --mount is not supported for ARM64 on this version of Windows.`
`Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED`

### Diagnostic Logs

Since this is a WSL --mount issue, tried to follow the guidance to run the `wmic` command but looks like that has been deprecated.

Running `wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions` from an elevated command prompt resulted in -
`'wmic' is not recognized as an internal or external command, operable program or batch file.`

Attached logs from `collect-wsl-logs.ps1`.

[WslLogs-2024-12-09_19-33-42.zip](https://github.com/user-attachments/files/18070278/WslLogs-2024-12-09_19-33-42.zip)

**Comment by etxaleku** [comment]
### Powershell Get-Disk output

- Disk 0 is the internal 1TB SSD, 
- Disk 1 is an external 4TB USB disk, and 
- Disk 2 is the VHD created using Windows DIsk Management > Action > Create VHD.

The file path for the VHD is on Disk 1 (D:\media\extdisk.vhdx).

`PS C:\> Get-Disk`

`Number Friendly Name             Serial Number                    HealthStatus         OperationalStatus      Total Size Partition`
`                                                                                                                         Style`
`------ -------------             -------------                    ------------         -----------------      ---------- ----------`
`2      Msft Virtual Disk                                          Healthy              Online                     512 GB RAW`
`0      MZ9L41T0HBLB-00BMV-SAM... 0025_38E2_4100_A58A.             Healthy              Online                  953.87 GB GPT`
`1      Seagate Expansion                     NA8P86N1             Healthy              Online                    3.64 TB GPT`

**Comment by benhillis** [comment]
`wsl.exe --mount` on ARM64 requires Windows platform support which was added in version 27653.

**Comment by etxaleku** [comment]
Hmm, sounds like maybe a WIndows OS update is needed then?  And I'm guessing that that version of Windows 11 has not been released yet.  I am on the Microsoft Store version of WSL2 and thought that it was decoupled from Windows ... sounds like it was mostly decoupled but maybe not entirely (but as much as technically possible).

**Comment by christopherdec** [comment]
@benhillis so we just need to wait until version 27653 is available? Do you know if enabling the Windows Update option "Get the latest updates as soon as they're available" will install this version?

**Comment by etxaleku** [comment]
@benhillis, if you see this and have pity on a poor WSL hacker, any help/suggestions would be appreciated.

I believe I have Windows version: 10.0.**26100**.2314 so I need that to update to 10.0.**27653**.xxxx then?  (Sorry, my Windows background is a bit sketchy).

In my Windows Update I see that "2024-12 Cumulative Update for Windows 11 Version 24H2 for arm64-based Systems (KB5048667)" is pending and I'm guessing that is probably the 27653 update that I need.  Unfortunately every time I try to install it, it fails with "Install error - 0x800f0983".  In reading about that error it sounds VERY painful as it sounds like my Windows installation has become "corrupted" and I will need to wipe out my machine and re-install Windows and then everything I have...  pretty depressing.  I'm guessing that the "corruption" was caused when I created the VHD in Disk Management and then tried to mount it in WSL2.  I have since deleted the VHD but it looks like the damage has already been done.  :(  Does that sound about right?

**Comment by Jinjiang** [comment]
almost the same:

```
> wsl --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3037
```

getting errors when running docker:

```
deploying WSL2 distributions
ensuring data disk is available: exit code: 4294967295: running WSL command wsl.exe C:\Windows\System32\wsl.exe --mount --bare --vhd <HOME>\AppData\Local\Docker\wsl\disk\docker_data.vhdx: wsl.exe --mount is not supported for ARM64 on this version of Windows.
Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED
: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
```

![Image](https://github.com/user-attachments/assets/3f98ae5b-f8f4-4d82-a1d2-124cb4eec244)

I guess in this case I have to wait for the Windows 10.0.27653.xxxx official update?

**Comment by etxaleku** [comment]
@Jinjiang, have you seen/installed "2024-12 Cumulative Update for Windows 11 Version 24H2 for arm64-based Systems (KB5048667)"?  I see it pending in my Windows Update but it consistently fails to install with error "Install error - 0x800f0983".  My assumption has been that this update will bring the Windows version to the required 27653 level but it seems like the update is broken.  Hoping that Microsoft fixes it sometime this year.

**Comment by Jinjiang** [comment]
![Image](https://github.com/user-attachments/assets/c6d4a94d-ae3e-466d-b87a-a541411af204)

Yes it was well-installed. However, the Windows version printed on the terminal is still 10.0.26100.3037

**Comment by etxaleku** [comment]
@Jinjiang, I finally got my Windows 11 update to successfully install and I had the same experience as you - my Windows "version" is Windows version: 10.0.26100.3194.

After doing some more reading it looks like 10.0.27653.xxxx is only available if you switch to "Windows Insider" builds - basically beta releases of Windows.  Looks like 27653 is not going to be official for a long time (2026 maybe?).  And if you go with an "Insider" build then it looks like you have to reformat and reinstall to go back to regular production builds (ouch).

**Comment by Jinjiang** [comment]
Then I guess we still have to wait until 27653 being merged into main channel.

**Comment by hitzam** [comment]
just got the same issue after windows update 
```2025-05 Cumulative Update Preview for Windows 11 Version 24H2 for arm64-based Systems (KB5058499) ```
it worked fine before that update 2 days ago

**Comment by JeroenBer** [comment]
Same issue here, after downgrading to WSL 2.4.13 due to other issue: 

https://github.com/docker/for-win/issues/14802

**Comment by gthieleb** [comment]
Same issue here, will MS provide a fix for the incompatibilities introduced with KB5058499?

**Comment by malcolm-nitm** [comment]
Any idea on when this will be available in non-Canary builds? Currently I'm using the Canary builds for this support but using Canary builds breaks graphics and monitor drivers. This completely breaks the development use case for Surface Pro ARM64 devices.
