### ISSUE TITLE
a weird bug in wsl like wsl/080072f7d

### ISSUE THREAD

**Issue by heheally** [microsoft/WSL#12377]
### Windows Version

windows version 10.0.19045.5198

### WSL Version

wsl version 2.3.26.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [x] WSL 1

### Kernel Version

5.15.167.4-1

### Other Software

`

### Repro Steps

i just wrote any normal command line like wsl --list --online and wsl --install -d Ubuntu

### Expected Behavior

i wanted a list of linux version i could install the tried to install kali linux and ubuntu

### Actual Behavior

![Image](https://github.com/user-attachments/assets/7d505414-909a-45f4-92ab-e2a26946560b)

### Diagnostic Logs

PS C:\Windows\system32> wsl --list --online                                                                                                                                                     Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. An error occurred in the secure channel support        Error code: Wsl/0x80072f7d

**Comment by heheally** [comment]
PS C:\Windows\system32> wsl --list --online                                                                                                                                                     Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. An error occurred in the secure channel support        Error code: Wsl/0x80072f7d

**Comment by heheally** [comment]
the log system doen't work for some reson

**Comment by OneBlue** [comment]
Closing since no logs are available to root cause the issue
