### ISSUE TITLE
WSL Plugin: How to display error messages to the user

### ISSUE THREAD

**Issue by ssijbabu** [microsoft/WSL#12372]
I am currently developing a WSL plugin that needs to validate the operating system of the distribution during the onDistributionStarted event. If the OS is not authorized, the plugin should:

- Display a message to the user: "You are not authorized to use this distribution".
- Return an error during the `onDistributionStarted` event to prevent further execution.

I’m reaching out to seek your guidance on how best to achieve this functionality. Specifically, I’d like to know:
- How to display the message to the user in the console and return an error from this event?

Any advice, examples, or resources you can share would be greatly appreciated. Thank you for your time and expertise!</div>

**Comment by OneBlue** [comment]
@ssijbabu: The best way to achieve would be by calling PluginError(). Something like: 

```
HRESULT OnDistributionStarted(...)
{

if (!DistributionNotAllowed(...))
{
    g_api->PluginError(L"This distribution is not authorized");
    return HRESULT_FROM_WIN32(ERROR_ACCESS_DISABLED_BY_POLICY);
}
```
