### ISSUE TITLE
WSL Registration Error: 0x80370102

### ISSUE THREAD

**Issue by kweeks95** [microsoft/WSL#12382]
### Windows Version

Microsoft Windows 11 Version 23H2

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Ubuntu 24.04

### Other Software

[Sysinfo.txt](https://github.com/user-attachments/files/18142339/Sysinfo.txt)

### Repro Steps

PS C:\Windows\system32> wsl.exe --install Ubuntu-24.04
Ubuntu 24.04 LTS is already installed.
Launching Ubuntu 24.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...

### Expected Behavior

I was expecting that ubuntu for wsl would install and i be prompted to create a user account and password. 

### Actual Behavior

PS C:\Windows\system32> wsl.exe --install Ubuntu-24.04
Ubuntu 24.04 LTS is already installed.
Launching Ubuntu 24.04 LTS...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...

### Diagnostic Logs

[WslLogs-2024-12-15_13-51-23.zip](https://github.com/user-attachments/files/18142353/WslLogs-2024-12-15_13-51-23.zip)

**Comment by zcobol** [comment]
According to Windows API documentation error `0x80370102` means `The virtual machine could not be started because a required feature is not installed` but won't tell what feature is missing!

**Comment by kweeks95** [comment]
> # View similar issues
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it!
> 
> ### Open similar issues:
> * [WslRegisterDistribution failed with error: 0x80370102 with Virtualization enabled (#11850)](https://github.com/microsoft/WSL/issues/11850),  similarity score: 0.88
> * [WslRegisterDistribution failed with error: 0x80370102 (#9656)](https://github.com/microsoft/WSL/issues/9656),  similarity score: 0.87
> 
> ### Closed similar issues:
> * [WSL2 and Windows 11 Home (WslRegisterDistribution failed with error: 0x80370102) (#8649)](https://github.com/microsoft/WSL/issues/8649),  similarity score: 0.87
> * [The installation process for distribution 'Ubuntu' failed with exit code: 1. Error code: Wsl/InstallDistro/WSL_E_INSTALL_PROCESS_FAILED (#11895)](https://github.com/microsoft/WSL/issues/11895),  similarity score: 0.85
> * [Error 0x80370102 (#8362)](https://github.com/microsoft/WSL/issues/8362),  similarity score: 0.84
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.
> 
> Diagnostic information

I have reviewed and tried the suggested fix's from similar problems with no success. I have ensured that virtualization is enabled in bios.

**Comment by kweeks95** [comment]
> According to Windows API documentation error `0x80370102` means `The virtual machine could not be started because a required feature is not installed` but won't tell what feature is missing!
> 
> If you have VS Studio installed open a VS command prompt and enter `errlook.exe` to lookup errors.
> 
> The error definition in `winerror.h`:
> 
> ```
> //
> // MessageId: HCS_E_HYPERV_NOT_INSTALLED
> //
> // MessageText:
> //
> // The virtual machine could not be started because a required feature is not installed.
> //
> #define HCS_E_HYPERV_NOT_INSTALLED       _HRESULT_TYPEDEF_(0x80370102L)
> ```
> 
> Do you have `hyper-v` installed?
> 
> On my system I have these hyper-v features installed and WSL works okay:
> 
> ```
> FeatureName : Microsoft-Windows-Subsystem-Linux
> State       : Enabled
> 
> FeatureName : HypervisorPlatform
> State       : Disabled
> 
> FeatureName : VirtualMachinePlatform
> State       : Enabled
> 
> FeatureName : Containers-DisposableClientVM
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-All
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-Tools-All
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-Management-PowerShell
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-Hypervisor
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-Services
> State       : Enabled
> 
> FeatureName : Microsoft-Hyper-V-Management-Clients
> State       : Enabled
> ```
> 
> Maybe the developers could clarify what features are needed for WSL only instead a full hyper-v installation.

![Image](https://github.com/user-attachments/assets/6bd57a57-9a4c-4027-8bd9-ea4a7bda016a)

These are my enabled features

**Comment by OneBlue** [comment]
@kweeks95: If the feature is enabled this usually means that the hypervisor failed to launch. Can you check if virtualization is enabled on bios ? 

Also, can you create virtual machine let's say with Hyper-V ?
