### ISSUE TITLE
Leading backslash in path that includes spaces during `--import` causes help-text

### ISSUE THREAD

**Issue by jarrodsfarrell** [microsoft/WSL#12383]
### Windows Version

Microsoft Windows [Version 10.0.19045.5247]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Issue

Origin issue: nix-community/NixOS-WSL#606
```
wsl --import NixOSTest $env:USERPROFILE\NixOS\ nixos-wsl.tar.gz --version 2
[help-text output]
```
```
wsl --import NixOSTest $env:USERPROFILE\NixOS nixos-wsl.tar.gz --version 2
Import in progress, this may take a few minutes.
```
Another user was able to do it with a leading backslash, so there might be something specific on my machine that's causing this weird behavior.

PowerShell Version: `5.1.19041.5247`

**Comment by jarrodsfarrell** [comment]
[WslLogs-2024-12-15_22-56-27.zip](https://github.com/user-attachments/files/18144317/WslLogs-2024-12-15_22-56-27.zip)

**Comment by elsaco** [comment]
Didn't repro on `WSL 2.4.5`:

```
PS C:\Users\elsaco\Downloads> wsl --import NixOS $env:USERPROFILE\NixOS\ nixos-wsl.tar.gz --version 2
The operation completed successfully.

PS C:\Users\elsaco\Downloads> ls $env:USERPROFILE\NixOS

    Directory: C:\Users\elsaco\NixOS

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/15/2024  8:18 PM     2260729856 ext4.vhdx
```

**Comment by jarrodsfarrell** [comment]
@elsaco Weird. But a thing I'm noticing is everyone who offered does _not_ have a space in their `USERPROFILE` whereas mine does since it's my full name including it's space.

So I picked a path that doesn't contain a space on my other disk.
```
wsl --import NixOSTest G:\NixOS\ nixos-wsl.tar.gz --version 2
Import in progress, this may take a few minutes.
```
It's a strange edge-case which I don't think is intentional.

**Comment by jarrodsfarrell** [comment]
Shoo. Be appeased with the same file: [WslLogs-2024-12-15_22-56-27.zip](https://github.com/user-attachments/files/18144317/WslLogs-2024-12-15_22-56-27.zip)

**Comment by OneBlue** [comment]
> [@elsaco](https://github.com/elsaco) Weird. But a thing I'm noticing is everyone who offered does _not_ have a space in their `USERPROFILE` whereas mine does since it's my full name including it's space.

If $USERPROFILE has a space in it, then what you're seeing is unfortunately the expected behavior since that would split the path into two arguments before calling wsl. To work around this the simplest would be always quote arguments that might contain spaces: 

```
wsl --import NixOSTest "$env:USERPROFILE\NixOS\" nixos-wsl.tar.gz --version 2
```

**Comment by jarrodsfarrell** [comment]
@OneBlue That's the thing: I tried that in the various incantations to figure out why the command was failing. I did, verbatim, try:
```powershell
wsl --import NixOSTest "$env:USERPROFILE\NixOS\" nixos-wsl.tar.gz --version 2
```
But it still failed. It also seems like PowerShell is a bit intelligent to notice cases like `$env:USERPROFILE\NixOS\` should be concat'd as a single string since this invocation:
```powershell
wsl --import NixOSTest $env:USERPROFILE\NixOS nixos-wsl.tar.gz --version 2
```
Will work as expected.

**Comment by jarrodsfarrell** [comment]
For posterity, I did expand the variable to my `USERPROFILE` path. So this incantation will fail as well:
```powershell
wsl --import NixOSTest "C:\Users\Jarrod Farrell\NixOS\" nixos-wsl.tar.gz --version
 2
```
