### ISSUE TITLE
Documentation for LXSSManager / LxBus / /dev/lxssclient?

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/WSL#1238]
Can we have some?

(My use case: I currently have a project that manages processes running in a WSL session by, essentially, running bash.exe as a subprocess and puppeteering it via stdin/stdout.

If I could instead have it run its own WSL-side process and communicate with it over LxBus, this would get a lot cleaner and easier to make reliable.)

**Comment by fpqc** [comment]
@cerebrate If you watched the video, Benhillis said they're going to do that probably as the next blogpost.
