### ISSUE TITLE
Cannot clone WSL2-Linux-Kernel

### ISSUE THREAD

**Issue by jibnew** [microsoft/WSL#12392]
### Windows Version

Microsoft Windows [Version 10.0.22631.4602]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4

### Distro Version

Ubuntu 24.04

### Other Software

I tried (from within wsl) `git clone https://github.com/microsoft/WSL2-Linux-Kernel.git --depth=1 -b linux-msft-wsl-6.6.y` three times, it keeps failing after a while, with the message
```
git clone https://github.com/microsoft/WSL2-Linux-Kernel.git --depth=1 -b linux-msft-wsl-6.6.y
Cloning into 'WSL2-Linux-Kernel'...
remote: Enumerating objects: 86697, done.
remote: Counting objects: 100% (86697/86697), done.
remote: Compressing objects: 100% (80163/80163), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3858 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```
Last time it happened at around 98% completed.
What do I do? Just try again and again?

### Repro Steps

run `wsl.exe`
when in wsl, run `git clone https://github.com/microsoft/WSL2-Linux-Kernel.git --depth=1 -b linux-msft-wsl-6.6.y`
get
```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3858 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

### Expected Behavior

WSL2-Linux-Kernel must be cloned into the directory with the same name

### Actual Behavior

Nothing is cloned anywhere

**Comment by elsaco** [comment]
I did a quick test and the cloning worked w/out issues:

```
elsaco@texas:~/GitHub$ git clone https://github.com/microsoft/WSL2-Linux-Kernel.git --depth=1 -b linux-msft-wsl-6.6.y
Cloning into 'WSL2-Linux-Kernel'...
remote: Enumerating objects: 86697, done.
remote: Counting objects: 100% (86697/86697), done.
remote: Compressing objects: 100% (80167/80167), done.
remote: Total 86697 (delta 9273), reused 22037 (delta 5665), pack-reused 0 (from 0)
Receiving objects: 100% (86697/86697), 237.33 MiB | 8.31 MiB/s, done.
Resolving deltas: 100% (9273/9273), done.
Updating files: 100% (81819/81819), done.
```

WSL and git versions used for testing:

```
elsaco@texas:~/GitHub$ git --version
git version 2.43.0
elsaco@texas:~/GitHub$ wslinfo --wsl-version
2.4.8
```

Please check your WSL networking setup.

**Comment by sirredbeard** [comment]
I have seen this happen sporadically when cloning the kernel. Usually trying again picks up where the clone left off. 

Are you on a VPN, wireless, or other connection that may be intermittent?

Are you cloning to the WSL filesystem or do a disk on `/mnt/...`?

**Comment by jibnew** [comment]
> I have seen this happen sporadically when cloning the kernel. Usually trying again picks up where the clone left off.
> 
> Are you on a VPN, wireless, or other connection that may be intermittent?
> 
> Are you cloning to the WSL filesystem or do a disk on `/mnt/...`?

Wifi, no VPN, cloning to ~ in WSL. Actually one more attempt finally succeeded.

**Comment by jibnew** [comment]
> I have seen this happen sporadically when cloning the kernel. Usually trying again picks up where the clone left off.
> 
> Are you on a VPN, wireless, or other connection that may be intermittent?
> 
> Are you cloning to the WSL filesystem or do a disk on `/mnt/...`?

Wifi, no VPN, cloning to ~ in WSL. Actually one more attempt finally succeeded.
