### ISSUE TITLE
WSL Installs Outdated Packages Using APT

### ISSUE THREAD

**Issue by ShravannJain** [microsoft/WSL#12400]
### Windows Version

Microsoft Windows [Version 10.0.22631.4317]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

whenever i type 
sudo apt install hugo 

### Expected Behavior

installs latest version

### Actual Behavior

installs outdated version

**Comment by zcobol** [comment]
@ShravannJain please be more specific of what WSL distro name(s) and version(s) are you using. Older distros `do` have older software builds, so APT will pull whatever is available in the repo. This is not a WSL but a Linux distribution maintenance issue.
