### ISSUE TITLE
Exit Code 2 for ls /does/not/exist in WSL Instead of Expected 1

### ISSUE THREAD

**Issue by arturbagramyan1** [microsoft/WSL#12401]
### Windows Version

Microsoft Windows [Version 10.0.22631.4602]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

24.04

### Repro Steps

Open a WSL terminal on your system.
Run the following command

```
> ls /does/not/exist
> echo $?
```

### Expected Behavior

According to the documentation, the exit code should be 1 for a "file not found" error, which is the correct exit code for ls in this case.

### Actual Behavior

We get exit code 2 that according to documentation is not right 

0: Success.
1: General error.
2: Misuse of shell builtins (e.g., invalid options, missing arguments)
126: Command not found.
127: Command not found.
128: Invalid argument to exit.
130: Script terminated by Ctrl+C.

**Comment by arturbagramyan1** [comment]
[WslLogs-2024-12-22_22-36-15.zip](https://github.com/user-attachments/files/18222916/WslLogs-2024-12-22_22-36-15.zip)

**Comment by zcobol** [comment]
@arturbagramyan1 it's not a WSL issue!

Quick test on standalone Linux system, running `CachyOS` and `bash` shell:

```
[zcobol@ontario ~]$ ls /does/not/exist
ls: cannot access '/does/not/exist': No such file or directory
[zcobol@ontario ~]$ echo $?
2
```

From `man ls`:

```
   Exit status:
       0      if OK,

       1      if minor problems (e.g., cannot access subdirectory),

       2      if serious trouble (e.g., cannot access command-line argument).

```

**Comment by arturbagramyan1** [comment]
A lot of people tried it on ubuntu in community all were getting 1 same on macOs

**Comment by zcobol** [comment]
Didn't try it on Ubuntu but on an Amazon Linux 2023 cloud instance the output is the same:

```
[ec2-user ~]$ ls /does/not/exist
ls: cannot access '/does/not/exist': No such file or directory
[ec2-user ~]$ echo $?
2
```
 
I think `Not such file or directory` files under `is serious trouble` exit code.

Command version used for testing:

```
[ec2-user ~]$ ls --version
ls (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.

```
The authors of GNU `ls` are `Richard M. Stallman` and `David MacKenzie`. Please reach out to either author and ask to clarify the exit code behavior of `ls`.

**Comment by arturbagramyan1** [comment]
> @arturbagramyan1 it's not a WSL issue!
> 
> Quick test on standalone Linux system, running `CachyOS` and `bash` shell:
> 
> ```
> [zcobol@ontario ~]$ ls /does/not/exist
> ls: cannot access '/does/not/exist': No such file or directory
> [zcobol@ontario ~]$ echo $?
> 2
> ```
> 
> From `man ls`:
> 
> ```
>    Exit status:
>        0      if OK,
> 
>        1      if minor problems (e.g., cannot access subdirectory),
> 
>        2      if serious trouble (e.g., cannot access command-line argument).
> 
> ```

**Comment by arturbagramyan1** [comment]
Ls is not a builtin command. i think wsl does something between so we get exit status 2

[exit status for builtin commands](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html)
