### ISSUE TITLE
VIM does not display correctly

### ISSUE THREAD

**Issue by ep-silon** [Microsoft/WSL#1241]
- If I open a file with VIM from the "Bash on Ubuntu for Windows" terminal , it opens and shows everything from the file. When I minimize the terminal windows and then maximize it back after a while, it does not display all the text, many lines are blank. If I close the file and re-open it, all the text it is displayed again.
- Windows version: 1607; OS build: 14393.321

**Comment by ilyaglow** [comment]
Ctrl+L can be used as a temporary solution. I wonder how to deal with issues with splits and netrw - commands like :Vex etc :(

**Comment by ep-silon** [comment]
Ctrl+L actually works. I wonder what is the original purpose of Ctrl+L in the console?

**Comment by zadjii-msft** [comment]
For what I know, C-L is just the vim keybinding for redrawing the screen, like C-R is in tmux.

I can't say I've seen this reported before, does it happen with other full-screen applications, like emacs or tmux, as well? It's possible that minimizing is sending the terminal a screen-resize event (to be 0 rows tall), but then it's not getting the resize event for restoring, but I can't get the behavior to repro locally unfortunately.

**Comment by ilyaglow** [comment]
Seems like you are right. Tmux has same issue:

How my split _should_ look:
![tmux-split-how-should-lookalike](https://cloud.githubusercontent.com/assets/1165242/19659551/15365e58-9a35-11e6-8311-f74a41bc9f77.PNG)

How it looks like after minimizing:
![tmux-split-bug](https://cloud.githubusercontent.com/assets/1165242/19659549/1254b7d4-9a35-11e6-99a3-f7ef70cea22c.PNG)

`Ctrl+b r` works as expected - everything is redrawn, `Ctrl+b q` can be a workaround too. 

Actually vim combined with tmux works better in bashonwindows. 

This is how restored from minimizing vim with splits alone looks like:
![vim-issue-smaller-pane](https://cloud.githubusercontent.com/assets/1165242/19660190/733e577e-9a37-11e6-9890-c8d0e8dfe5db.PNG)

Ctrl+L will work if I am currently at pane with content fills the whole pane's height. So If I'll do Ctrl+L on the left pane trick won't work, but on the right pane will. Means that if I don't have enough content on both panes it becomes a disaster :) 

Vim inside tmux always seems to redraw nicely after Ctrl+B r

**Comment by ilyaglow** [comment]
It clears terminal and force vim to redraw the screen

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
