### ISSUE TITLE
SSH does not portforwarded from WSL2 since 24H2 update

### ISSUE THREAD

**Issue by tasoo-oos** [microsoft/WSL#12410]
### Windows Version

Microsoft Windows [Version 10.0.26100.2605]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1, 6.6.36

### Distro Version

Ubuntu noble 24.04 x86_64

### Other Software

OpenSSH-server, 1:9.6p1-3ubuntu13.5
txpdump, 4.99.4-3ubuntu4

### Repro Steps

I followed [this blog](https://www.hanselman.com/blog/how-to-ssh-into-wsl2-on-windows-10-from-an-external-machine), as always.

`wsl --install -d Ubuntu`

Then in the WSL ubuntu,
`sudo nano /etc/ssh/sshd_config`
```
Port 3456
#AddressFamily any
ListenAddress 0.0.0.0
#ListenAddress ::
```

`sudo systemctl start ssh`

Then to Adminstrative powershell,

`ipconfig`
```
이더넷 어댑터 vEthernet (WSL (Hyper-V firewall)):

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::bed1:2b9e:374b:b269%42
   IPv4 주소 . . . . . . . . . : 172.31.160.1
   서브넷 마스크 . . . . . . . : 255.255.240.0
   기본 게이트웨이 . . . . . . :
```

Checked WSL vm ip address is 172.31.160.1.

`netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=3456connectaddress=172.31.160.1 connectport=3456`
`netsh advfirewall firewall add rule name=”WSL 3456” dir=in action=allow protocol=TCP localport=3456`

```
PS D:\util> netsh interface portproxy show all

ipv4 수신 대기:             ipv4에 연결:

주소            포트        주소            포트
--------------- ----------  --------------- ----------
0.0.0.0         3456        172.31.160.1    3456
```

```
PS D:\util> Get-NetFirewallRule -DisplayName "WSL 3456"


Name                          : {E6722372-C589-45DD-A59A-6D61EB4BB314}
DisplayName                   : WSL 3456
Description                   :
DisplayGroup                  :
Group                         :
Enabled                       : True
Profile                       : Any
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LooseSourceMapping            : False
LocalOnlyMapping              : False
Owner                         :
PrimaryStatus                 : OK
Status                        : 저장소에서 규칙을 구문 분석했습니다. (65536)
EnforcementStatus             : NotApplicable
PolicyStoreSource             : PersistentStore
PolicyStoreSourceType         : Local
RemoteDynamicKeywordAddresses : {}
PolicyAppId                   :
PackageFamilyName             :
```

### Expected Behavior

My goal is to use this WSL instance as remote development enviroment, accessed via SSH.
It was doing well until last week, when I updated windows 11 to 24H2.

### Actual Behavior

SSH does not get forwarded since 24H2 update.
At first, I thought It was because of some corruption during windows update, so I clean-installed windows using newly made installation media.
But still, it does not work.

In the clean-installed windows, I tested:
`ssh tasoo1118@localhost -p 3456 -vvvv` inside of the problematic ubuntu instance -> works well.
<details>
<summary>log</summary>
<pre>
tasoo1118@tasoo-desktop:~$ ssh tasoo1118@localhost -p 3456 -vvvv
OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/tasoo1118/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/tasoo1118/.ssh/known_hosts2'
debug2: resolving "localhost" port 3456
debug3: resolve_host: lookup localhost:3456
debug3: channel_clear_timeouts: clearing
debug3: ssh_connect_direct: entering
debug1: Connecting to localhost [127.0.0.1] port 3456.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
debug1: identity file /home/tasoo1118/.ssh/id_rsa type -1
debug1: identity file /home/tasoo1118/.ssh/id_rsa-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_ecdsa type -1
debug1: identity file /home/tasoo1118/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/tasoo1118/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_ed25519 type -1
debug1: identity file /home/tasoo1118/.ssh/id_ed25519-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_ed25519_sk type -1
debug1: identity file /home/tasoo1118/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_xmss type -1
debug1: identity file /home/tasoo1118/.ssh/id_xmss-cert type -1
debug1: identity file /home/tasoo1118/.ssh/id_dsa type -1
debug1: identity file /home/tasoo1118/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
debug1: compat_banner: match: OpenSSH_9.6p1 Ubuntu-3ubuntu13.5 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to localhost:3456 as 'tasoo1118'
debug3: put_host_port: [localhost]:3456
debug3: record_hostkey: found key type ED25519 in file /home/tasoo1118/.ssh/known_hosts:1
debug3: record_hostkey: found key type RSA in file /home/tasoo1118/.ssh/known_hosts:2
debug3: record_hostkey: found key type ECDSA in file /home/tasoo1118/.ssh/known_hosts:3
debug3: load_hostkeys_file: loaded 3 keys from [localhost]:3456
debug1: load_hostkeys: fopen /home/tasoo1118/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-s,kex-strict-s-v00@openssh.com
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug3: kex_choose_conf: will use strict KEX ordering
debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:4HUxYKVjYynET/z73DF2qJ7bR32OVU4rtNGkrP39i80
debug3: put_host_port: [127.0.0.1]:3456
debug3: put_host_port: [localhost]:3456
debug3: record_hostkey: found key type ED25519 in file /home/tasoo1118/.ssh/known_hosts:1
debug3: record_hostkey: found key type RSA in file /home/tasoo1118/.ssh/known_hosts:2
debug3: record_hostkey: found key type ECDSA in file /home/tasoo1118/.ssh/known_hosts:3
debug3: load_hostkeys_file: loaded 3 keys from [localhost]:3456
debug1: load_hostkeys: fopen /home/tasoo1118/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[localhost]:3456' is known and matches the ED25519 host key.
debug1: Found key in /home/tasoo1118/.ssh/known_hosts:1
debug3: send packet: type 21
debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: Sending SSH2_MSG_EXT_INFO
debug3: send packet: type 7
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: ssh_packet_read_poll2: resetting read seqnr 3
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug3: kex_input_ext_info: extension server-sig-algs
debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256>
debug3: kex_input_ext_info: extension publickey-hostbound@openssh.com
debug1: kex_ext_info_check_ver: publickey-hostbound@openssh.com=<0>
debug3: kex_input_ext_info: extension ping@openssh.com
debug1: kex_ext_info_check_ver: ping@openssh.com=<0>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug3: kex_input_ext_info: extension server-sig-algs
debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256>
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Will attempt key: /home/tasoo1118/.ssh/id_rsa
debug1: Will attempt key: /home/tasoo1118/.ssh/id_ecdsa
debug1: Will attempt key: /home/tasoo1118/.ssh/id_ecdsa_sk
debug1: Will attempt key: /home/tasoo1118/.ssh/id_ed25519
debug1: Will attempt key: /home/tasoo1118/.ssh/id_ed25519_sk
debug1: Will attempt key: /home/tasoo1118/.ssh/id_xmss
debug1: Will attempt key: /home/tasoo1118/.ssh/id_dsa
debug2: pubkey_prepare: done
debug1: Trying private key: /home/tasoo1118/.ssh/id_rsa
debug3: no such identity: /home/tasoo1118/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_ecdsa
debug3: no such identity: /home/tasoo1118/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_ecdsa_sk
debug3: no such identity: /home/tasoo1118/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_ed25519
debug3: no such identity: /home/tasoo1118/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_ed25519_sk
debug3: no such identity: /home/tasoo1118/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_xmss
debug3: no such identity: /home/tasoo1118/.ssh/id_xmss: No such file or directory
debug1: Trying private key: /home/tasoo1118/.ssh/id_dsa
debug3: no such identity: /home/tasoo1118/.ssh/id_dsa: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
tasoo1118@localhost's password:
debug3: send packet: type 50
debug2: we sent a password packet, wait for reply
debug3: receive packet: type 52
Authenticated to localhost ([127.0.0.1]:3456) using "password".
debug1: channel 0: new session [client-session] (inactive timeout: 0)
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: filesystem
debug3: client_repledge: enter
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: client_input_hostkeys: received RSA key SHA256:Urv54YM+CsTRqdkWAcYGK/9xkJtPYc6rEXHC+9wV5/4
debug3: client_input_hostkeys: received ECDSA key SHA256:LpEXxh8ydpK1siixEuPfPeCU5Rf/Z606ecLxtMHGNrY
debug3: client_input_hostkeys: received ED25519 key SHA256:4HUxYKVjYynET/z73DF2qJ7bR32OVU4rtNGkrP39i80
debug3: put_host_port: [localhost]:3456
debug1: client_input_hostkeys: searching /home/tasoo1118/.ssh/known_hosts for [localhost]:3456 / (none)
debug3: hostkeys_foreach: reading file "/home/tasoo1118/.ssh/known_hosts"
debug3: hostkeys_find: found ssh-ed25519 key at /home/tasoo1118/.ssh/known_hosts:1
debug3: hostkeys_find: found ssh-rsa key at /home/tasoo1118/.ssh/known_hosts:2
debug3: hostkeys_find: found ecdsa-sha2-nistp256 key at /home/tasoo1118/.ssh/known_hosts:3
debug1: client_input_hostkeys: searching /home/tasoo1118/.ssh/known_hosts2 for [localhost]:3456 / (none)
debug1: client_input_hostkeys: hostkeys file /home/tasoo1118/.ssh/known_hosts2 does not exist
debug3: client_input_hostkeys: 3 server keys: 0 new, 3 retained, 0 incomplete match. 0 to remove
debug1: client_input_hostkeys: no new or deprecated keys from server
debug3: client_repledge: enter
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env SHELL
debug3: Ignored env PWD
debug3: Ignored env LOGNAME
debug3: Ignored env XDG_SESSION_TYPE
debug3: Ignored env HOME
debug1: channel 0: setting env LANG = "C.UTF-8"
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env LS_COLORS
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env LESSCLOSE
debug3: Ignored env XDG_SESSION_CLASS
debug3: Ignored env TERM
debug3: Ignored env LESSOPEN
debug3: Ignored env USER
debug3: Ignored env SHLVL
debug3: Ignored env XDG_SESSION_ID
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env SSH_CLIENT
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env PATH
debug3: Ignored env DBUS_SESSION_BUS_ADDRESS
debug3: Ignored env SSH_TTY
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug3: client_repledge: enter
debug1: pledge: fork
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
</pre>
</details>

`ssh tasoo1118@172.31.160.1 -p 3456 -vvvv` from the windows that has problematic ubuntu instance -> 
`Connection closed by 172.31.160.1 port 3456` and no packets captured from tcpdump inside ubuntu
<details>
<summary>log</summary>
<pre>
PS D:\util> ssh tasoo1118@172.31.160.1 -p 3456 -vvvv
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
debug3: Failed to open file:C:/Users/tasoo/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 172.31.160.1 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> 'C:\\Users\\tasoo/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> 'C:\\Users\\tasoo/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to 172.31.160.1 [172.31.160.1] port 3456.
debug1: Connection established.
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_rsa.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_rsa error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_rsa-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_rsa-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ecdsa error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ecdsa-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ecdsa_sk type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ecdsa_sk-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ecdsa_sk-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ed25519 error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ed25519-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ed25519_sk type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_ed25519_sk-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_ed25519_sk-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_xmss.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_xmss error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_xmss-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_xmss-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_xmss-cert type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_dsa.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_dsa error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/tasoo/.ssh/id_dsa-cert.pub error:2
debug3: failed to open file:C:/Users/tasoo/.ssh/id_dsa-cert error:3
debug1: identity file C:\\Users\\tasoo/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_9.5
kex_exchange_identification: Connection closed by remote host
Connection closed by 172.31.160.1 port 3456
</pre>
</details>

Pinging the windows machine from other devices inside LAN, including router itself -> no packets received.
Doing internet on it (Watch youtube, install tcpdump inside WSL via apt, write this, etc...) -> Done well.

I am so confused, is there any perky security feature updates or similar??

### Diagnostic Logs

```
PS D:\util> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             21 Up           00-15-5D-69-8F-36        10 Gbps
vEthernet (WSL (Hyper-... Hyper-V Virtual Ethernet Adapter #2          42 Up           00-15-5D-95-6D-F5        10 Gbps
Bluetooth 네트워크 연결   Bluetooth Device (Personal Area Netw...       7 Disconnected E8-FB-1C-7E-B5-B2         3 Mbps
Wi-Fi                     MediaTek Wi-Fi 6E MT7922 160MHz Wire...       5 Disconnected E8-FB-1C-7E-B5-B3          0 bps
이더넷                    Intel(R) Ethernet Controller I226-V           4 Up           10-7C-61-B7-41-AC         1 Gbps
```

```
tasoo1118@tasoo-desktop:~$ sudo ss -tulpn | grep ssh
tcp   LISTEN 0      4096                *:3456            *:*    users:(("sshd",pid=13082,fd=3),("systemd",pid=1,fd=61))
```

**Comment by tasoo-oos** [comment]
Status update
By wireshark installed on windows, I found that ssh packets from other machine reach to destination machine's windows, but not transferred to WSL.

**Comment by tasoo-oos** [comment]
Finally, I was able to re-esetablish the ssh enviroment.
My change was

1. Change `netsh interface portproxy`'s connectaddress, It should not the one that comes out from `ipconfig` but the one from `wsl hostname -I` as [this article](https://learn.microsoft.com/en-us/windows/wsl/networking) said.
2. Change `/etc/ssh/sshd_config` from server-side WSL, I am not sure which one affect it, but I am pretty sure that one of `PasswordAuthentication yes`, `KbdInteractiveAuthentication yes`, `AllowTcpForwarding yes` did the trick.

**Comment by wutzebaer** [comment]
i had to remove
`networkingMode=mirrored`
now i can reach my containers again

**Comment by thethiny** [comment]
Something changed with SSH over secondary adapters as they no longer work as intended. This is not only a WSL issue it's an entire Windows issue.
