### ISSUE TITLE
Wsl Kali is saying that I have 1K GB of storage!

### ISSUE THREAD

**Issue by GameLord2011** [microsoft/WSL#12413]
### Windows Version

Microsoft Windows [Version 10.0.26100.2605]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Kali Linux 2024.4

### Other Software

Apt Install

### Repro Steps

Install anything (In my case nyancat) w/ ```Sudo apt Install [package-name]```

### Expected Behavior

Installs, and says 'Storage: xxxx/256 GB'

### Actual Behavior

Installs, and says 'Storage: xxxx/>1K GB'

### Diagnostic Logs

https://gist.github.com/GameLord2011/b0e633951777930ad81ea9f4b5577a3c

**Comment by GameLord2011** [comment]
[WslLogs-2024-12-26_16-38-29.zip](https://github.com/user-attachments/files/18255568/WslLogs-2024-12-26_16-38-29.zip)

**Comment by zcobol** [comment]
@GameLord2011 I did a quick test and didn't see any storage warnings:

```
┌──(zcobol㉿eleven)-[~]
└─$ sudo apt install nyancat
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nyancat
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 15.1 kB of archives.
After this operation, 79.9 kB of additional disk space will be used.
Get:1 http://kali.download/kali kali-rolling/main amd64 nyancat amd64 1.5.2-0.3 [15.1 kB]
Fetched 15.1 kB in 1s (28.7 kB/s)
Selecting previously unselected package nyancat.
(Reading database ... 16448 files and directories currently installed.)
Preparing to unpack .../nyancat_1.5.2-0.3_amd64.deb ...
Unpacking nyancat (1.5.2-0.3) ...
Setting up nyancat (1.5.2-0.3) ...

┌──(zcobol㉿eleven)-[~]
└─$ wslinfo --wsl-version
2.4.4
```

Distro info:

```
┌──(zcobol㉿eleven)-[~]
└─$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.4"
VERSION="2024.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

Where exactly are you seeing the `Storage: xxxx/>1K GB` message?

**Comment by GameLord2011** [comment]
Command Output:
The following packages were automatically installed and are no longer required:
  fortunes-min  librecode3
Use 'sudo apt autoremove' to remove them.

Installing:
  nyancat

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 0
  Download size: 15.1 kB
  Space needed: 79.9 kB / 1,020 GB available

Get:1 http://kali.mirror.rafal.ca/kali kali-last-snapshot/main amd64 nyancat amd64 1.5.2-0.3 [15.1 kB]
Fetched 15.1 kB in 0s (38.0 kB/s)
Selecting previously unselected package nyancat.
(Reading database ... 150181 files and directories currently installed.)
Preparing to unpack .../nyancat_1.5.2-0.3_amd64.deb ...
Unpacking nyancat (1.5.2-0.3) ...
Setting up nyancat (1.5.2-0.3) ...
Processing triggers for man-db (2.13.0-1) ...
Processing triggers for kali-menu (2024.4.0) ...

**Comment by GameLord2011** [comment]
output from dylanaraps/neofetch:
..............                                     gamelord@SchoolComputer
            ..,;:ccc,.                             -----------------------
          ......''';lxO.                           OS: Kali GNU/Linux Rolling on Windows 10 x86_64
.....''''..........,:ld;                           Kernel: 5.15.167.4-microsoft-standard-WSL2
           .';;;:::;,,.x,                          Uptime: 6 mins
      ..'''.            0Xxoc:,.  ...              Packages: 1358 (dpkg)
  ....                ,ONkc;,;cokOdc',.            Shell: bash 5.2.32
 .                   OMo           ':ddo.          Theme: Kali-Dark [GTK2], adw-gtk3-dark [GTK3]
                    dMc               :OO;         Icons: Flat-Remix-Blue-Dark [GTK2/3]
                    0M.                 .:o.       Terminal: Windows Terminal
                    ;Wd                            CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.095GHz
                     ;XO,                          GPU: c9c0:00:00.0 Microsoft Corporation Basic Render Driver
                       ,d0Odlc;,..                 Memory: 359MiB / 3641MiB
                           ..',;:cdOOd::,.
                                    .:d;.':;.
                                       'd,  .'
                                         ;l   ..
                                          .o
                                            c
                                            .'
                                             .

**Comment by zcobol** [comment]
@GameLord2011 i think what you're seeing is the maximum WSL virtual disk size!

From https://learn.microsoft.com/en-us/windows/wsl/disk-space:

`by default each VHD file used by WSL 2 is initially allocated a 1TB maximum amount of disk space`

**Comment by OneBlue** [comment]
This is indeed by design. WSL's VHD's are created with a 1TB size by default. which is what the distribution sees. 

Related: #10565
