### ISSUE TITLE
Fail to enable subsystem

### ISSUE THREAD

**Issue by CicoZhang** [Microsoft/WSL#1248]
After receiving the anniversary update, I am glad to know the subsystem feature with it. However, I cannot enable it, either via GUI or via Powershell.

Could anyone shed some light on that?

![image](https://cloud.githubusercontent.com/assets/11710225/19610775/82699bd8-97de-11e6-9b3a-b8182c588029.png)

![image](https://cloud.githubusercontent.com/assets/11710225/19610801/98b12276-97de-11e6-8768-bc7893f8bdd9.png)

I tried the methods mentioned [here](https://support.microsoft.com/en-us/kb/2734782). It looks like irrelevant and indeed it doesn't help.

After receiving a fusillade of accumulative update for Windows 10, this problem is still persisting.
Has anyone encountered the similar problem?

![image](https://cloud.githubusercontent.com/assets/11710225/19610882/2261a806-97df-11e6-82ef-20d0dad9598e.png)

**Comment by benhillis** [comment]
This looks like a pretty generic failures for enabling optional components.  I'll dig around and see what I can find I might not have much luck.  Could you check in your event log for any errors that might have more information?

**Comment by CicoZhang** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-10-22T08:08:58.358751600Z" /> 
  <EventRecordID>5590</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-CICO</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>CbsPackageServicingFailure2</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>10.0.14393.350</Data> 
  <Data>Microsoft-Windows-Foundation-Package</Data> 
  <Data>10.0.14393.0</Data> 
  <Data>amd64</Data> 
  <Data>unknown</Data> 
  <Data>800f0831</Data> 
  <Data>CBS Other</Data> 
  <Data>Installed</Data> 
  <Data>Installed</Data> 
  <Data>Windows Optional Component Manager</Data> 
  <Data /> 
  <Data>C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_10.0.14393.350_239e96bd882fc1c7b664b5166838aea5bdc821d2_00000000_1e1b6553</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>c807358d-982e-11e6-9c86-90cc3d098d36</Data> 
  <Data>4100</Data> 
  <Data /> 
  </EventData>
  </Event>

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-10-22T08:08:58.362800200Z" /> 
  <EventRecordID>5591</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-CICO</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>CbsPackageServicingFailure2</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>10.0.14393.350</Data> 
  <Data>Microsoft-Windows-Foundation-Package</Data> 
  <Data>10.0.14393.0</Data> 
  <Data>amd64</Data> 
  <Data>unknown</Data> 
  <Data>800f0831</Data> 
  <Data>CBS Other</Data> 
  <Data>Installed</Data> 
  <Data>Installed</Data> 
  <Data>Windows Optional Component Manager</Data> 
  <Data>\\?\C:\WINDOWS\Logs\CBS\CBS.log \\?\C:\WINDOWS\Logs\CBS\CbsPersist_20161021202614.log \\?\C:\WINDOWS\Logs\CBS\CbsPersist_20161021183158.log \\?\C:\WINDOWS\Logs\CBS\CbsPersist_20161014170039.cab \\?\C:\WINDOWS\Logs\CBS\CbsPersist_20161012231023.cab \\?\C:\WINDOWS\Logs\CBS\CbsPersist_20161012195307.cab \\?\C:\WINDOWS\servicing\Sessions\Sessions.xml \\?\C:\WINDOWS\winsxs\poqexec.log \\?\C:\WINDOWS\inf\setupapi.dev.log</Data> 
  <Data /> 
  <Data /> 
  <Data>0</Data> 
  <Data>c807358d-982e-11e6-9c86-90cc3d098d36</Data> 
  <Data>262144</Data> 
  <Data /> 
  </EventData>
  </Event>
