### ISSUE TITLE
VIM - cursor doesn't blink

### ISSUE THREAD

**Issue by Erhie** [Microsoft/WSL#1253]
Working with VIM, the cursor does not blink and is hard to find

otherwise if VIM runs in Windows cmd.exe the cursor blinks

Why that difference?

Ubuntu 14.04.5 LTS on Windows Version 10.0.14393 Build 14393

**Comment by zadjii-msft** [comment]
I'm gonna look into this, this doesn't look right.

**Comment by zadjii-msft** [comment]
So I wrote the following script to make sure this works as it should. The only blinking sequences I'm seeing emitted by vim are `\x1b[?12l` and `\x1b[?12;25h`. The both work as intended, but it looks to me like vi also tries to turn off cursor blinking.

``` python
import sys
import time

def csi(seq):
    sys.stdout.write('\x1b[{}'.format(seq))

def main(argv):
    csi('?12l')
    print 'Blinking off'
    time.sleep(5)

    csi('?12h')
    print 'Blinking on'
    time.sleep(5)

    csi('?25;12l')
    print 'invisible'
    time.sleep(5)

    csi('?25;12h')
    print 'visible on'
    time.sleep(5)

if __name__ == '__main__':
    main(sys.argv)
```

**Comment by bubomancer** [comment]
Did anyone get it to blink?

**Comment by davidmaxwaterman** [comment]
I don't know about blinking specifically, but the cursor sure is hard to fine sometimes...for me, it just seemed to be a thick underscore that inverts the bottom part of the character it is on. It's extremely difficult to spot quickly. I guess blinking would help, but isn't it possible to invert the whole character?
I don't recall having this problem on any other platform I've used vi/vim on.

**Comment by zadjii-msft** [comment]
@davidmaxwaterman You can definitely pick to have a full block cursor if you'd like!
In the properties, select the "Large" cursor size. That will give you what you're looking for.

![image](https://user-images.githubusercontent.com/18356694/31236274-857ade72-a9a8-11e7-8890-9b452ceab0b6.png)
![image](https://user-images.githubusercontent.com/18356694/31236295-8ec5744c-a9a8-11e7-9f56-1c33285a6dea.png)

**Comment by davidmaxwaterman** [comment]
Yeah, that's much better. Thanks for that tip! :)

**Comment by Garviell** [comment]
Any news on this? 

I would rather not have cursorline on just to be able to see my cursor

**Comment by ntacus** [comment]
Changing the cursor size in the bash window properties still doesn't help the cursor in vim. I set the cursor size to Large which makes it a block cursor at the bash prompt, but in vim it returns to the small hard to find cursor. Should the cursor size have applied to the vim cursor as well?

**Comment by therealkenc** [comment]
[Migrate to windows console issue tracker.](https://github.com/microsoft/console)

**Comment by ragvri** [comment]
Any update on this issue?

**Comment by jaredkrinke** [comment]
@therealkenc any chance you could point us to the migrated issue? I couldn't find it by searching for "vim cursor blink" in the Windows Console issue tracker.

Sorry to bug you about such an old issue, but I'd like to know if this is supposed to be fixed (because I'm still seeing the same "cursor in Vim doesn't blink" issue on 10.0.19042.1237).

**Comment by tothedistance** [comment]
A temporary solution would be install neovim and alias it to vim. For me, neovim blink works fine in windows terminal after setting `:set guicursor=n-v-c:block,o:hor50,i-ci:hor15,r-cr:hor30,sm:block,a:blinkwait700-blinkon400-blinkoff250`
