### ISSUE TITLE
Link to Win32 binaries in program files folder cannot be invoked

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/WSL#1268]
- A brief description

I created links (`ln -s`) to some Win32 binaries in program files, but they do not run when invoked. 
If I directly invoke the .exe file, it will run as expected; if I create a link to something like notepad.exe, it will also work.
- Expected results

The programs should start and run in windows when I type in `./link_name`
- Actual results (with terminal output if applicable)

No program runs. The command ends in error state. This is indicated by the color change of fish terminal. No error message is shown. 
- Your Windows build number

14951.rs_prerelease.161014-1700
- Steps / All commands required to reproduce the error from a brand new installation 

``` bash

cd ~

############# These won't run ################

ln -s /mnt/c/Program\ Files\ \(x86\)/Microsoft\ VS\ Code/Code.exe vscode.exe
./vscode.exe

# with quotes in filename
ln -s "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" chrome.exe
./chrome.exe

# without .exe
ln -s "/mnt/c/Program Files (x86)/Microsoft VS Code/Code.exe" vscode
./vscode

############## All of these works: #############

/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe

/mnt/c/Program\ Files\ \(x86\)/Microsoft\ VS\ Code/Code.exe

# creating link to notepad.exe works
ln -s "/mnt/c/Windows/System32/notepad.exe" notepad           
./notepad
```
- Required packages and commands to install

Chrome and VS Code in Windows system.

**Comment by MartinLenord** [comment]
This could be because you are attempting to launch an application from within VolFs rather than DrvFs
If you look at https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/ it mentions
> NT binaries can only run out of DrvFs paths (for example: /mnt/c/Windows/System32).

**Comment by PowerSnail** [comment]
@MartinLenord If I understand VolFs and DrvFs correctly, then I do not think this is the case.

The binaries themselves are mounted both on DrvFs. Both `Program Files (x86)/` and `Windows/System32/` are in `/mnt/c/`.

The symbolic link files are stored in the same folder. I have tried several different places, including home directory and `/tmp`, but the results are the same.

If it is a problem related to file system, then `chrome.exe` and `Code.exe` should produce the same result as `notepad.exe`. 

What's really confusing is that neither symbolic link nor program files directory causes the problem. It is when they are combined that the feature stops working.

**Comment by rodrymbo** [comment]
How about a workaround: try a bash alias (or maybe the corresponding functionality in whatever shell you are using)? I just tried

`alias notepad='/mnt/c/Program\ Files\ \(x86\)/Internet\ Explorer/iexplore.exe'`

and "notepad" now works to start the windows program.

**Comment by benhillis** [comment]
@MartinLenord - What I mean by running the binary out of VolFs (or LxFs as we're referring to it now) is that the if the executable itself is in VolFs it will not work. For example /home/user/foo.exe.  If you run an exe out of /mnt/c/... with a VolFs current working directory the binary will launch, but the current working directory will not propagate.

@PowerSnail - If I understand you correctly you're only having issues with vscode.exe?  If so, I suspect you're hitting a name collision with vscode.exe.  Can you run the following command?

`which vscode.exe`

**Comment by benhillis** [comment]
It looks like this was resolved by one of @SvenGroot's symlink changes after Creator's Update.
