### ISSUE TITLE
ctrl+V does not paste into console

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/WSL#1274]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description

If I select text elsewhere the ctrl does not paste it into the console. I assume ctrl+c and ctrl-x Di not work but have not tried.
- Expected results

Windows integration should include these keyboard shortcuts at s minimum.

I guess there is scope for clashes with shells and programs so may not be possible. At least right click works and safer.
- Actual results (with terminal output if applicable)

Nothing
- Your Windows build number

14951
- Steps / All commands required to reproduce the error from a brand new installation 
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by hachre** [comment]
FYI: You can use the right mouse key to paste.

CTRL+V isn't bound because many apps on Linux expect that to be free for their own purposes. In `nano` CTRL+V does scrolling down a page for example.

**Comment by SteveALee** [comment]
So my intuition was right this time. Thanks for quick reply

**Comment by SteveALee** [comment]
So my intuition was right this time. Thanks for quick reply

**Comment by ngokevin** [comment]
GNOME terminal does `ctrl+shift+v`, can we use that? Not having a proper keyboard paste is difficult.

**Comment by hachre** [comment]
It would certainly be nice to have that as a default.

**Comment by SteveALee** [comment]
> Not having a proper keyboard paste is difficult

Totally agree as alt+space does not bring up the Bash window's system menu as it should either. That would allow keyb access, though many key strokes :(

**Comment by jarrodek** [comment]
Usability problem as well. I used to paste stuff into the terminal using CLTR + SHIFT + V on Ubuntu or Command + V when on Mac. I always missed shortcuts on Windows console. Since this is Ubuntu console on Windows it definitely should implement similar behavior.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This was fixed in a recent Insiders build: https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
