### ISSUE TITLE
Rails commands doesn't work anymore after wake up from hibernate.

### ISSUE THREAD

**Issue by kaanoo2904** [microsoft/WSL#1277]
I'm running Rails through RVM install and it works fine. But I still have this issue:

Sometimes I have to go out and hibernate PC . When I come back, Rails commands (rails console, rails server ...) just hang !
 I'm still able to check ruby and rails version through console.

![image](https://cloud.githubusercontent.com/assets/10462294/19761272/5cff638e-9c5f-11e6-8225-ef5f9fffd52a.png)

But any other Rails command doesn't work any more. `Rails console` doesn't put any output on screen:

![image](https://cloud.githubusercontent.com/assets/10462294/19761312/8a9a6abe-9c5f-11e6-9b97-af2543501d12.png)

While `rails server` command did start Puma, but navigate `localhost:3000`  also just hang there ( I've wait for 20 min+) 

![image](https://cloud.githubusercontent.com/assets/10462294/19761366/d35dcc64-9c5f-11e6-9d94-e546f2a8d664.png)

Also, I can't use `Ctrl-C` to quit rails process, instead I've to close terminal window.

![image](https://cloud.githubusercontent.com/assets/10462294/19761454/3a779b78-9c60-11e6-9096-fb8171eb8aff.png)

Terminate ruby task in windows task manager doesn't help neither.

![image](https://cloud.githubusercontent.com/assets/10462294/19761529/a012baee-9c60-11e6-9f93-5189a62089db.png)

Everytime I have this issue, my only way is to restart my PC, which's quite annoying.

I don't know if this's a Rails error, or Bash on Windows error. So I just post here and see if anyone else have this too.

p/s: sorry for my bad English :P

**Comment by benhillis** [comment]
@kaanoo2904 Can you please provide your Windows version?

**Comment by kaanoo2904** [comment]
@benhillis 

![image](https://cloud.githubusercontent.com/assets/10462294/19777031/99457be4-9ca0-11e6-9c21-730c1b2cc904.png)

**Comment by dethoma** [comment]
I tried to reproduce this on my Asus laptop through hibernate and was not able to hit this. Would you be able to try a recent insider build and let us know if you still experience this?

Alternatively when you come back from hibernate are you able to access other network resources or run a new bash window and type other commands?

**Comment by kaanoo2904** [comment]
@dethoma I have a Asus K53SV ( pretty old model). Sorry but I couldn't try insider build on this machine, currently in build 1607.

Other network resources work just fine, I only have problem with Rails on Bash :(

**Comment by nyanhacker** [comment]
Closes: #1277

**Comment by nyanhacker** [comment]
@benhillis Please Close The Issues. :+1:

**Comment by therealkenc** [comment]
Taking malwareslayer's word this was external.
