### ISSUE TITLE
Process Memory usage

### ISSUE THREAD

**Issue by clovett** [Microsoft/WSL#1279]
I have a process that is misbehaving after long running test (all night) and I want to see it's memory usage but "cat /proc/25903/status" is returning all zero's for the Vm\* stats.

This is on Windows build number 10.0.14393.0.

"ps aux" has the same problem, the size column is all zeros.

Can you fix this or provide another way I can track the memory usage of my app running in BashOnWindows ?  Unfortunately valgrind fails with " Valgrind: FATAL: aspacem assertion failed".

**Comment by misenesi** [comment]
Have you tried to run the process on the most recent Insider Build? As for memory usage, have you considered looked into perfmon?
