### ISSUE TITLE
Git commands sometimes fail while using zsh

### ISSUE THREAD

**Issue by ulyssesp** [Microsoft/WSL#1298]
1. Installed zsh and git using apt-get
2. Installed oh-my-zsh (although this still repros on vanilla zsh)
3. Updated .bashrc to `exec /bin/zsh` and `umask 022`
4. Run git command

Expected:
5. Git command succeeds consistently

Actual:
5. Git command fails sometimes with exit code 1. `GIT_TRACE` doesn't produce any extra logs.

It seems like a race condition - if I use `strace` or `bash/zsh -x -c` it succeeds every time.

Not an issue using bash. Issue appears using latest version of git from git-core ppa as well.

**Comment by ulyssesp** [comment]
Update: putting a space in front of commands seems to fix this. Still something wonky going on somewhere.

**Comment by benhillis** [comment]
Closing out old issues. If you continue to experience issues running git with zsh, please open a new issue. Thanks!
