### ISSUE TITLE
Can't install WSL - feature unchecked after each restart

### ISSUE THREAD

**Issue by afarra** [Microsoft/WSL#1304]
I am unable to install windows system on linux. Every time I check it in windows features and it promts for restart, after the restart is complete, I open the windows features dialog and it has been unchecked again. I tried this several times. I don't see lxrun.exe or bash.exe probably as a result of it being unchecked (not applied) when the restart is done, and both lxrun and bash are unrecognized commands in command prompt / power shell.

Expected result:
WSL should be enabled after restart is complete

Actual results:
WSL is unchecked again after restart

Windows build number:
14393.351

Steps required to reproduce:
Enable Developer Mode. Check WSL in windows features. Restart when prompted. When restart is done, WSL is unchecked again and bash and lxrun are unrecognized commands in command prompt / power shell

Notes:
One thing to note, as I don't know if this could be realted to this issue, is that I had it enabled a month ago and bash was installed and I could open it and run bash commands, but due to some other unrelated issue on my machine, I had to do a system restore point recovery that took me back to before I enabled WSL. Now when I enable it I have the issue above, Not sure if this system restore revert is a factor in this issue or not.

**Comment by fpqc** [comment]
There is a commandline method to enable Windows features, have you tried running the install that way (admin command prompt)?

https://technet.microsoft.com/en-us/library/hh824822.aspx

**Comment by afarra** [comment]
This is the output of running it through command line. (tl;dr - same problem)
```
PS C:\WINDOWS\system32> Dism /online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0

Feature Information:

Feature Name : Microsoft-Windows-Subsystem-Linux
Display Name : Windows Subsystem for Linux (Beta)
Description : Provides services and environments for running native user-mode Linux shells and tools on Windows.
Restart Required : Required
State : Disabled

Custom Properties:

(No custom properties found)

The operation completed successfully.
PS C:\WINDOWS\system32> Dism /online /Enable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
Restart Windows to complete this operation.
Do you want to restart the computer now? (Y/N) Y
```

...after restarting:

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Dism /online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0

Feature Information:

Feature Name : Microsoft-Windows-Subsystem-Linux
Display Name : Windows Subsystem for Linux (Beta)
Description : Provides services and environments for running native user-mode Linux shells and tools on Windows.
Restart Required : Required
State : Disabled

Custom Properties:

(No custom properties found)

The operation completed successfully.
PS C:\WINDOWS\system32>
```

**Comment by afarra** [comment]
One thing to note, is during the restart, in the Green / Blue screen when it's applying the updates, after a while showing the "Updating. Do not turn off your computer" message, it briefly shows the message "We couldn't complete the updates. Undoing changes" then it restarts again.

**Comment by benhillis** [comment]
Are there any in interesting warning or error events in your event log?

Eventvwr

**Comment by afarra** [comment]
There's Information messages in "Windows Logs\Setup"
- "Initiating changes to turn on update Microsoft-Windows-Subsystem-Linux of package Microsoft-Windows-Lxss-Optional-Package. Client id: DISM Package Manager Provider."
- "A reboot is necessary before the selectable update Microsoft-Windows-Subsystem-Linux of package Microsoft-Windows-Lxss-Optional-Package can be turned on."
- **"Update Microsoft-Windows-Subsystem-Linux of package Microsoft-Windows-Lxss-Optional-Package failed to be turned on. Status: 0x800f0922."**

**Comment by afarra** [comment]
Turns out there's several other users with this problem as well; I missed that issue when I was searching for similar issues (issue #931). It seems the one thing in common is doing a system restore after installing the feature.

**Comment by benhillis** [comment]
It seems like something is in a bad state, could you try this command line to disable the feature?

Dism /online /Disable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /Remove

**Comment by afarra** [comment]
I ran that command to disable it, then restarted, then ran the command to enable it again, then restarted, but same problem; during the restart it said couldn't complete the update, undoing changes.

**Comment by fpqc** [comment]
lol, Windows Feature Installation has always been so temperamental.  I still get a little chuckle at this project https://github.com/Microsoft/VisualStudioUninstaller/releases

**Comment by afarra** [comment]
@benhillis any suggestions of what I can do to get this working again? (other than a full Windows reinstall)

**Comment by benhillis** [comment]
@afarra - I'm sorry I do not. This is a generic deployment issue and not related to WSL, I'll see if I can find somebody who might know more.

**Comment by afarra** [comment]
Workaround is to delete the empty folder at `%windir%\System32\Tasks\Microsoft\Windows\Windows Subsystem for Linux` (see https://github.com/Microsoft/BashOnWindows/issues/931#issuecomment-265791282)

(this issue can probably be marked as duplicate of #931)

**Comment by pentacore** [comment]
I've got the same issue as TS, but im unable to do the workaround since that folder doesnt exist

**Comment by sunilmut** [comment]
Closing since this is duplicate.

**Comment by happyCodingSusan** [comment]
Hi Guys,

I encountered the same problem as @afarra. I am able to run the following 2 commands,

PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.18362.1139

Image Version: 10.0.18363.1198

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.18362.1139

Image Version: 10.0.18363.1198

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\WINDOWS\system32>

But during restarting my PC, I saw message of "we couldn't completer the updates. Undoing changes".  After PC is restarted, I check "turn windows features on or off" windows, the two boxes of "virtual machine platform" and "windows subsystem for linux" are not checked.

My PC is installed windows 10, version 1909 (OS build 18363.1198).

I wish someone can help me to solve the problem.

Many Thanks

**Comment by newgate2601** [comment]
@happyCodingSusan Have
 you resolve it ?
