### ISSUE TITLE
Intel® Memory Protection Extensions is missing in /proc/cpuinfo

### ISSUE THREAD

**Issue by ytrezq** [Microsoft/WSL#1308]
Intel mpx is a useful tool to expose overflows bugs. Detecting such bugs on Windows is better than in production.

So Please add the`mpx`entry to the`flags`entry of`/proc/cpuinfo`if the current processor support it.
Otherwise, programs complains about the processor doesn’t supporting mpx even if it does.

**Comment by therealkenc** [comment]
Unfortunately it's not just the /proc/cpuentry. Your processor supports mpx, but `prctl(PR_MPX_INIT, ...)`. It isn't even [documented](http://man7.org/linux/man-pages/man2/prctl.2.html) yet far as I can tell. Don't know how well the NT [MPX support](https://blogs.msdn.microsoft.com/vcblog/2016/01/20/visual-studio-2015-update-1-new-experimental-feature-mpx/) maps to Linux semantics.

**Comment by misenesi** [comment]
Thank you for reporting this issue! Could you please vote for this feature on our [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) formu for proper prioritization?

**Comment by ytrezq** [comment]
@misenesi : normally, the`flags`entry of `/proc/cpuinfo`should contains all features the processor supports. So I think it’s a bug, not a feature.

**Comment by benhillis** [comment]
@ytrezq I agree with your characterization of this as a bug and not a feature.

**Comment by therealkenc** [comment]
This is probably counting angels on pinheads like the `/proc/version` issue thread, but I think putting the string in `/proc/cpuinfo` has the potential to break things. The string indicates the capabilities of the _environment_, not the capabilities of a hunk of silicon on your motherboard. A userspace app sees the `mpx` string in `/proc/cpuinfo` and naturally tries to use the `prctl`, then dies horribly -- as opposed to doing whatever the tool does on non-mpx chips (which might be nothing). 

I am not 100% certain, but I don't think `mpx` shows in `/proc/cpuinfo` unless Linux is compiled with `CONFIG_X86_INTEL_MPX=y`. For the moment, WSL is emulating a Linux kernel compiled without `CONFIG_X86_INTEL_MPX`.

**Comment by benhillis** [comment]
My native Ubuntu machine is also not showing mpx in cpuinfo:
`
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm
`

**Comment by therealkenc** [comment]
I think you had the label right the first time: "feature". It doesn't even look that hard to implement, having skimmed over the interface (you're going to have basically the same NT support in there _somewhere_). Priority of which dependent on user voice upvotes, natch.

**Comment by ytrezq** [comment]
@benhillis : Because mpx is still new. Normally, all Linux kernel >3.18 will show mpx if the processor support it. And this not something you can disable in`.config`with`make menuconfig`.

This was considered as a bug of not showing it in Linux.

**Comment by therealkenc** [comment]
Yes 4.4.0-45-generic.

**Comment by Charnarongthumwan** [comment]
Good

**Comment by therealkenc** [comment]
This one was sent to User Voice but an entry never materialised. It would be "Support CONFIG_X86_INTEL_MPX=y" or somesuch.
