### ISSUE TITLE
sudo apt-get -f install Problem

### ISSUE THREAD

**Issue by next1984** [Microsoft/WSL#1314]
Im getting this Error CAn anyone help me! ?! it's important! 

`Preconfiguring packages ...
(Reading database ... 47531 files and directories currently installed.)
Preparing to unpack .../locales_2.24-5_all.deb ...
Unpacking locales (2.24-5) over (2.13+git20120306-12.1) ...
dpkg: error processing archive /var/cache/apt/archives/locales_2.24-5_all.deb (--unpack):
 trying to overwrite '/usr/sbin/update-locale', which is also in package libc-bin 2.19-0ubuntu6.9
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/locales_2.24-5_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by stehufntdev** [comment]
Can you please follow the [contributing directions ](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) and supply an strace?

**Comment by aseering** [comment]
@next1984 -- it looks to me like you or someone else manually created the file `/usr/sbin/update-locale`.  You're not supposed to create that file manually; you're supposed to let Ubuntu manage it for you.  You could try moving the file out of the way and re-running the command.
