### ISSUE TITLE
WSL - Won't open PowerShell unless sudo is used.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/WSL#1315]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
It seems after the recent update from Ubuntu 14.04 to 16.04 something impacted PowerShell.  I know is not yet totally supported but my workaround (using xterm or screen) seems work.  Unfortunately, I can only open PowerShell using sudo:

sudo powershell

This was working fine with Ubuntu 14.04.  The workaround still works except now I have to use 'sudo powershell'. 

(http://www.maxtblog.com/2016/10/running-powershell-in-windows-10-bash-workaround/ )

* Expected results
to give me the PowerShell prompt.

* Actual results (with terminal output if applicable)
maxt@MTrinidadLT2:~$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
Access to the path '/home/maxt/.local/share/powershell/Modules' is denied.
maxt@MTrinidadLT2:~$

* Your Windows build number
Windows 10 Pro Insider Preview Build 14951

* Steps / All commands required to reproduce the error from a brand new installation 
1. Open bash
2. At the bash prompt, type 'powershell'.

* Strace of the failing command
non

* Required packages and commands to install
Follow instructions at: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604 

![bashposherr_2016-11-03_10-15-43](https://cloud.githubusercontent.com/assets/19892435/19969332/8daf7c72-a1ae-11e6-896a-95c3a9190107.jpg)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Hooold on, you're doing something that you're not telling us.

You can't launch powershell like that unless you either aliased it or added something to your `PATH`

Let's begin at the beginning.

**Comment by benhillis** [comment]
@fpqc He's running the Linux version of powershell.

**Comment by MaximoTrinidad** [comment]
Yes @benhillis! You are correct.  I'm running Linux version of PowerShell (no exe included).  And, this was opening fine when using Bash (Ubuntu 14.04). 
:)

**Comment by ddfznt** [comment]
@MaximoTrinidad `sudo chown -R maxt ~/.local`

**Comment by MaximoTrinidad** [comment]
@ddfznt  Ouch!!  This will work around the issue and I don't know how much is will impact using PowerShell.  But, very interesting!

![bashposherr2_2016-11-03_10-15-43](https://cloud.githubusercontent.com/assets/19892435/19975571/d83b1f26-a1c2-11e6-82d7-661b17568006.jpg)

Thanks,
Max

**Comment by ddfznt** [comment]
@MaximoTrinidad https://github.com/Microsoft/vscode/issues/6684 take a look here!

**Comment by MaximoTrinidad** [comment]
Hi @ddfznt!  Thanks but that issue is not related.  That's on using VS Code Windows OS not BASH.  I have not problems with VS Code running PowerShell Core on either Windows 10 nor Linux.  It's just with the recent BASH update.
:)

sample "Terminal working fine".
![bashnorelated_2016-11-03_14-17-50](https://cloud.githubusercontent.com/assets/19892435/19979705/c719276a-a1d1-11e6-8088-f3b34ef43007.jpg)

**Comment by afinnell** [comment]
Am I to understand you're attempting to spawn a Powershell instance while under the WSL bash.exe instance? I'm curious what the use case is for this and if you're able to run a cmd.exe which then spawns Powershell. 

I didn't think Windows PE binaries were launchable from within WSL. Is this new or was I just blind?

**Comment by fpqc** [comment]
@afinnel it was announced to much fanfare like 2 weeks ago.

**Comment by MaximoTrinidad** [comment]
This is the thing! 

Yes, you can launch Window binaries from WSL. But, this is what I found out today.

For example, you are creating a cross-platform PowerShell script and launch Windows VS Code (from Bash) to create the file in the Linux subsystem, it won't be visible in Bash. It will be visible in Windows Explorer and Windows VS Code.  

Try to use the Nautilus to look for the file created in Windows VS Code, and you won't find it.  So, for me, I can't use the Windows Version of VS Code to create PowerShell scripts in Bash Linux subsystem.

Also, if I create a PowerShell script file using 'gedit' and then use Windows VS Code to change it., then I won't see the file in Bash again.  

Now,  back to the topic. Beside the known display issue with PowerShell, I could open it without using 'sudo' before Bash got upgraded to Ubuntu 16.04.1.  

I'm suspecting something with the user profile permission. 

:)

**Comment by fpqc** [comment]
It will work as long as it's on a volume mounted in /mnt

**Comment by MaximoTrinidad** [comment]
@fpqc 

No! I want to have a workable PowerShell Core (Linux) on Bash so I can test cross-platform PS scripts. 

Anyway,  I just tested executing the Windows PowerShell in Bash using:
**"/mnt/c/Program Files/PowerShell/6.0.0.12/powershell.exe"** 

It doesn't work. I won't use it that way but it was good to try it.

:)

**Comment by benhillis** [comment]
Can you clarify what you mean by doesn't work?

**Comment by MaximoTrinidad** [comment]
Hi @benhillis,

After you enter "/mnt/c/Program Files/PowerShell/6.0.0.12/powershell.exe", the PowerShell prompts comes up OK.  

1. Then, enter $psver -press tab and it doesn't autocomplete to $psversiontable. It just does a tab.
2.  Up arrow to get back to previous command won't work.
3. Do a "Dir c:\Windows\System32", try to do a Ctrl-C to stop the listing. it won't stop.
4. Sometimes if you mistyped a command and go back to fixed it then it still won't work.
5. In PowerShell.exe I use the 'cls' alias and got me out to the bash prompt. But, not sure where I'm at this point because it keeps jumping from PowerShell to Bash back to PowerShell. 

![wposhinbash_01_2016-11-04_10-19-22](https://cloud.githubusercontent.com/assets/19892435/20009712/ecb0aab6-a27b-11e6-869c-291dcfd0ca61.jpg)
![wposhinbash_02_2016-11-04_10-19-22](https://cloud.githubusercontent.com/assets/19892435/20009768/15d408d4-a27c-11e6-8f4e-3d0b14fe3ce8.jpg)
![wposhinbash_03_2016-11-04_10-19-22](https://cloud.githubusercontent.com/assets/19892435/20009719/f3045228-a27b-11e6-8e78-1f4000b9845e.jpg)
![wposhinbash_04a_2016-11-04_10-19-22](https://cloud.githubusercontent.com/assets/19892435/20009729/fa37f77a-a27b-11e6-8fe5-350a562e5e99.jpg)
![wposhinbash_04b_2016-11-04_10-19-22](https://cloud.githubusercontent.com/assets/19892435/20009734/ff99e4ee-a27b-11e6-8e3d-bb80fc44ee80.jpg)


At this point I rather not use Windows PowerShell.exe in Bash. 

But, I definitely have more control in PowerShell Core (Linux) when using 'xterm' in Bash using sudo.

**Comment by MaximoTrinidad** [comment]
Of course, I'm using Xming, and configure xterm to allow scrolling.  

![xterm2posh_2016-11-04_10-53-19](https://cloud.githubusercontent.com/assets/19892435/20010053/232ce70c-a27d-11e6-8351-fb1b115d29e4.jpg)

**Comment by MaximoTrinidad** [comment]
This is Awesome! Thanks.  I started to show the work around and record my UG meeting on using Bash and PowerShell Core (Linux).  I know there are limitations but at least (for me) using xterm is a winner to some UX win. I like the cross-platform collaboration. 

Again, a clean Bash installation, follow by loading PowerShell Core, there's a message coming up when executing 'powershell' (w/o sudo).  I couldn't print the screen but it seem couldn't load some modules and it looks related to user profile issue.  I will rebuild my bash on my other machine to trap the error.  

I like the direction this is heading!
:)

**Comment by fpqc** [comment]
@maximotrinidad, you should use {mintty}{wsltty} , which uses mintty

**Comment by bitcrazed** [comment]
@fpqc That's just a work around. We should also fix our stuff if possible!

**Comment by fpqc** [comment]
@bitcrazed Of course, but it is preferable to xterm over X over TCP.  It can at least use local fonts.

**Comment by MaximoTrinidad** [comment]
Thanks @fpqc for recommending wsltty.  I will check it out!
:)

**Comment by benhillis** [comment]
Closing this out as the issues with interop console handles is being tracked elsewhere.
