### ISSUE TITLE
MySql service not starting on Build 14959

### ISSUE THREAD

**Issue by kvprasoon** [Microsoft/WSL#1329]
I'm getting below error.

initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  2356 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
 * Starting MySQL database server mysqld                                                            /lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  2371 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
                                                                                             [ OK ]

![image](https://cloud.githubusercontent.com/assets/12897753/20069193/9e02dcf4-a541-11e6-9738-dc7c566e4144.png)

**Comment by jrock2004** [comment]
I am getting the same error but it seems even though its saying those things its still working. Upstart was replaced some time again with systemd. Wondering if that is the issue

**Comment by benhillis** [comment]
Closing out old issues, please reopen a new issue if you continue to have issues with MySQL in newer versions of WSL.

**Comment by therealkenc** [comment]
This one was actually `upstart` not `mysql`, which is spiritually now #994.
