### ISSUE TITLE
Ship also some rpm-based distro

### ISSUE THREAD

**Issue by stardust85** [Microsoft/WSL#1330]
Our company uses a RPM-based distro (Oracle Linux - compatible with CentOS and RHEL) and releases a lot of internal RPM packages. Supporting, let's say, CentOS, will make development on windows much easier. Now we use heavy virtualization in dev.

* Expected results: Ubuntu is not the only distribution offered in App Store
* OS Version: 1607
* OS Build: 14393.0

P.S.: Millions thanks for this WSL project, it is really THE BEST killer app which makes 
*nix developers love Microsoft and keep or bring them to Windows 👍

**Comment by stardust85** [comment]
Created also the User Voice entry to allow voting 

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16997386-ship-also-some-rpm-based-distro-centos-or-oracle

**Comment by aseering** [comment]
@stardust85 -- thanks for posting!  I agree (as a user) that having other distros, in particular CentOS, would be very useful in an enterprise environment.  Hopefully the WSL folks will comment on their plans there.

If you (or others reading this ticket) need a workaround in the meantime, though, some possible workarounds:

* Install the RPM package in Ubuntu using [alien](https://help.ubuntu.com/community/RPM/AlienHowto)
* Install CentOS in WSL using [WSL Distribution Switcher](https://github.com/RoliSoft/WSL-Distribution-Switcher)

**Comment by stardust85** [comment]
Thanks, will try. WSL Distribution Switcher looks promissing to me 👍

**Comment by fpqc** [comment]
@stardust85 Highly suggest using the newest build of Win10 insider for non-Ubuntu-14.04 distros. The WSL distro switcher has a bunch of cool fixes in the postinstall script, but some are workarounds that only pertain to the older builds (for instance, there's a chroot hack, a sudo hack, a fakeroot hack).  Roli checks for the Windows version now and his script checks which workarounds are necessary.  RPM-based ones iirc use chroot, so it's preferable to use a Win10 build that supports chroot without having to use the hack.

**Comment by stardust85** [comment]
I can confirm that CentOS:7 works well for me via WSL Distribution Switcher on Win10 build 14393.51 (non-insider). I'll try it also on insider at home..

**Comment by benhillis** [comment]
Discussion has run its course.
