### ISSUE TITLE
sysctl doesn't support fs.file-max

### ISSUE THREAD

**Issue by hughbe** [Microsoft/WSL#1333]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I'm trying to see if I can build coreclr on WSL, following the instructions [here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md)

The docs state
```
To ensure that your system can allocate enough file-handles for the corefx build run
sysctl fs.file-max. If it is less than 100000, add fs.file-max = 100000 to /etc/sysctl.conf,
and then run sudo sysctl -p.
```

* Expected results
Prints the file-max on my box

* Actual results (with terminal output if applicable)
`sysctl: cannot start /proc/sys/fs/file-max: No such file or directory`

* Your Windows build` number
14393.351

* Steps / All commands required to reproduce the error from a brand new installation 
`sudo sysctl fs.file-max`

* Strace of the failing command
N/A

* Required packages and commands to install
`sudo sysctl fs.file-max`

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
It’ſ not exactly ſyſctl, it’ſ unimplemented ſyſfſ featureſ

**Comment by hughbe** [comment]
Sorry, your message looks mangled on my Pc? I think you made a formatting error!

**Comment by fpqc** [comment]
@hughbe I was using a joke android keyboard that replaces the "short s" with the historical "long ſ".

**Comment by benhillis** [comment]
Why have one way to query something (ulimit system call) when you can have 2 or more?

This should be really quick to implement - I've filed a task to get this in.

**Comment by termanico** [comment]
I have exactly the same problem, while installing SAP HANA Express on WSL!
Any news on that? will it be fixed soon? (more sys/fs structure?)

**Comment by termanico** [comment]
I am also missing fs.aio_max_nr

**Comment by therealkenc** [comment]
> commented on 8 Nov 2016
> This should be really quick to implement - I've filed a task to get this in.

Good one. 

Duping up to #2893 where the +1 crowd hangs out.
