### ISSUE TITLE
Truncated large responses from node server

### ISSUE THREAD

**Issue by soljin** [Microsoft/WSL#1335]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
When ever I try to load a large transpiled js file from a node server for either of my two projects, they are truncated randomly.

* Expected results

get served the entire file

* Actual results (with terminal output if applicable)
```bash
jfoltz@lgwl-jfoltz:~$ wget http://localhost:4000/files/darwin/src/darwin.js
--2016-11-08 13:57:12--  http://localhost:4000/files/darwin/src/darwin.js
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:4000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6835452 (6.5M) [application/javascript]
Saving to: ‘darwin.js’

100%[==============================================================================>] 6,835,452   --.-K/s   in 0.07s

2016-11-08 13:57:13 (91.3 MB/s) - ‘darwin.js’ saved [6835452/6835452]

jfoltz@lgwl-jfoltz:~$ wget http://localhost:4000/files/darwin/src/darwin.js
--2016-11-08 13:57:16--  http://localhost:4000/files/darwin/src/darwin.js
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:4000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6798588 (6.5M) [application/javascript]
Saving to: ‘darwin.js.1’

100%[==============================================================================>] 6,798,588   --.-K/s   in 0.08s

2016-11-08 13:57:17 (79.7 MB/s) - ‘darwin.js.1’ saved [6798588/6798588]

jfoltz@lgwl-jfoltz:~$ tail darwin.js -n 3
      var scheduler = this, disposable = new SingleAssignmentDisposable();
      var id = scheduleMethod(function () {
        !disposable.isDisjfoltz@lgwl-jfoltz:~$
jfoltz@lgwl-jfoltz:~$ tail darwin.js.1 -n 3
      }
      while (++index < length) {
        key =jfoltz@lgwl-jfoltz:~$

jfoltz@lgwl-jfoltz:~$ node -v
v6.9.1
 
```
also happens with 

node -v
v4.6.1

* Your Windows build number

14931

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Thanks @soljin for reporting this!  It sounds a lot like a specific example of #610 to me.  (#610 uses a Python server, but I've seen the same thing with a node server as well.)  Does that look familiar to you as well?

**Comment by fpqc** [comment]
Any reason you don't want to use 14959?  Just curious.

**Comment by soljin** [comment]
@aseering  Yeah, I've seen this error from Chrome as well. net::ERR_CONTENT_LENGTH_MISMATCH. But I don't always see it.

@fpqc I've gotten some very unstable builds from the fast ring in the past few months and switched back to slow for stability.

**Comment by soljin** [comment]
@aseering this seems like a pretty critical bug that has gone unfixed for a long time. This is preventing me from using windows as my dev box.

Is there any chance this will get fixed? And if so do you have any idea when?

**Comment by sunilmut** [comment]
@soljin - Apologize for the delay in responding. I am actively working on a fix for #610 and #616 and will double check if it also resolves this issue or not. But, the fixes are not trivial and so I can't give you any ETA at the moment.

**Comment by sunilmut** [comment]
@soljin - Apologize for the delay in responding. I am actively working on a fix for #610 and #616 and will double check if it also resolves this issue or not. But, the fixes are not trivial and so I can't give you any ETA at the moment. I will also validate whether the fix for #610 also fixes this issue. Stay tuned and thanks for trying out WSL!

**Comment by soljin** [comment]
@sunilmut that is great news. I'm looking forward to your fix!

**Comment by sunilmut** [comment]
Please try this on 15002 and let us know if the issue persists. We have fixed a few bugs related to inconsistent data transfer on TCP sockets in [15002](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002).

**Comment by therealkenc** [comment]
Almost certainly #610. Closing until proven otherwise.
