### ISSUE TITLE
Reading child /proc/<pid>/stat after exec

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/WSL#1353]
This one is painful to look at. The test case below tries to open `/proc/<pid>/stat` on a process that is just about to die. I'd call the whole construct "broken", but [it exists](https://cs.chromium.org/chromium/src/base/process/internal_linux.cc?rcl=0&l=53). 

You can make an awfully strong case that the child process isn't guaranteed to be alive at the point the `stat` file is opened in the parent, but for reasons, this **always** seems to be the case on Real Linux™. WSL strace [here](https://gist.github.com/therealkenc/748c2e2ecca5e4c07b2cfc6ec5901d0e) and Linux strace [here](https://gist.github.com/therealkenc/fbf1af4166fd7c88e15e90f775ea9147). Don't dwell on the straces though; the error is `No such file or directory` on `/proc/pid/stat` because that process is gone.

[edit- delete poor speculation]. _Whatever_ the reason, it isn't dumb luck; you can uncomment the `sleep()` call after the `else`, but no matter how long you hang around, the `proc/<pid>` entry is still there long after the child `/bin/echo` process has had a chance to finish. 14959.
```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, char* argv[]) {    
  int pipe_fds[2];
  pipe(pipe_fds);
  
  pid_t pid = fork();
  if (pid == 0) {
    dup2(pipe_fds[1], STDOUT_FILENO);
    execl("/bin/echo", "echo", "hello", NULL);
    // notreached
  } else {
    //sleep(2);
    const size_t buf_sz = 4096;
    char output_buf[buf_sz];
    int output_nread = read(pipe_fds[0], output_buf, buf_sz);
    printf("got from child: %s", output_buf);

    char path[buf_sz];
    snprintf(path, buf_sz, "/proc/%d/stat", pid);
    int fd = open(path, O_RDONLY);
    if (fd < 0) {
      fprintf(stderr, "open %s failed: ", path);
      perror("");
      _exit(-1);
    }

    char stat_buf[buf_sz];
    ssize_t stat_nread = read(fd, stat_buf, buf_sz);
    if (stat_nread < 0) {
      perror("failed to read: ");
      _exit(-1);
    }
    printf("stat for pid %d:\n%s", pid, stat_buf);
  }

  return 0;
}
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  This is a known issue where procfs in WSL does not handle zombie processes correctly.  Can you please let us know what scenario this is blocking so we can prioritize?

**Comment by therealkenc** [comment]
I linked the scenario in [it exists](https://cs.chromium.org/chromium/src/base/process/internal_linux.cc?rcl=0&l=53) above. It's how the chromium base library gets the parent process id of a given process id, independent of parent/child relationship. [There's no explicit posix construct for such a thing.]

**Comment by therealkenc** [comment]
Brian - #2786 too then probably (it was almost duped)

**Comment by Brian-Perkins** [comment]
@therealkenc -- agreed, added a comment there as well.
