### ISSUE TITLE
Detect Conhost capabilities

### ISSUE THREAD

**Issue by melund** [Microsoft/WSL#1356]
Sorry if this is not the right place to ask. Is there a way to detect the version/capabilities of Conhost? 

Are there a way to detect that  Conhost is new enough so we can switch to a VT100 backend.

**Comment by fpqc** [comment]
The "right" way to do this is with environment vars and terminfo databases.  MS might submit conhost as a terminfo file to the distros on release, or they are aiming with 100% compatibility with xterm (VT220 anyone, where my sixels at!?)

Another option might be to ship a terminfo file with WSL that gets automatically installed in the right place like /init does and then just have WSL in conhost always launch with that that TERM variable set.

**Comment by zadjii-msft** [comment]
@melund If you're running WSL, it's going to be new enough. 90% of the VT support we added was added in the anniversary update synchronously with WSL. 

As far as a Win32 way to determine the if the console has VT capabilities, you can always try setting the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag with `SetConsoleMode`. If that fails, then you can assume your version doesn't support VT sequences.

See: https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx for an example (at the bottom)

**Comment by melund** [comment]
Fantastic. It was a way to detect capabilities from Win32 I was looking for. Thanks a lot.
