### ISSUE TITLE
Input not registering when running an interactive batch script from Bash

### ISSUE THREAD

**Issue by pradyuman** [Microsoft/WSL#1366]
* A brief description
I tried calling sbt.bat from Bash (sbt in Linux won't work for me - detailed in a previous issue) however once the batch script starts and the console is initialized, none of my input gets registered.

* Expected results
When an interactive batch script is run in bash, the input in the bash terminal is sent to the batch script.

* Actual results (with terminal output if applicable)
Whenever I press enter to enter in a command, the terminal just shows `^M` and nothing happens:
![image](https://cloud.githubusercontent.com/assets/9904569/20292832/ca023cc8-aabe-11e6-8f9f-a94ab5023853.png)

* Your Windows build number
14965

* Steps / All commands required to reproduce the error from a brand new installation 
1. Launch sbt.bat
2. Try to enter in any command (for example `help`)

* Required packages and commands to install
[sbt](http://www.scala-sbt.org/) in windows

**Comment by benhillis** [comment]
I've filed an internal task to track this issue.

**Comment by benhillis** [comment]
Fixed in 17618.
