### ISSUE TITLE
It is not possible to clear the screen and the scrollback buffer.

### ISSUE THREAD

**Issue by zjturner** [Microsoft/WSL#1369]
* **Description:** In `cmd` you can use the command `cls`.  In normal bash you can use the command `reset` or `printf "\033c"`.  Both of these commands in Windows 10 Bash clear the screen but not the scrollback.  AFAICT there is no way to achieve the same effect as `cls`.

* **Expected Result:** The screen clears and the scrollback buffer clears

* **Actual Result:** The screen clears but not the scrollback buffer.

* **Windows Build Number:** 14393

**Comment by zadjii-msft** [comment]
#1020 is the dupe you're looking for. You're correct, there is no way to clear the "scrollback" in BoW. It's on the backlog :)

**Comment by funhatch** [comment]
alias cls='clear && echo -en "\e[3J"'

**Comment by ashish2199** [comment]
clear -x works for me

**Comment by iamsangamesh** [comment]
`clear -x` worked for me. `ctrl + l` also worked like charm.

**Comment by hym3242** [comment]
may be a missing entry in the termcap/terminfo db. programs may want to make sure the terminal supports `CSI 3 J` before clearing scrollback
