### ISSUE TITLE
ReFS on WSL

### ISSUE THREAD

**Issue by caiokat** [Microsoft/WSL#1372]
* A brief description
My ReFS volume mounts as expected under /mnt, but I can't read/write any files or directories from wsl. 

* Actual results (with terminal output if applicable)
$ sudo ls -la
ls: cannot access $RECYCLE.BIN: Permission denied
ls: cannot access a.txt: Permission denied
ls: cannot access folder: Permission denied
ls: cannot access System Volume Information: Permission denied
total 0
drwxrwxrwx 2 root root 0 Nov 16 04:39 .
drwxr-xr-x 2 root root 0 Dec 31  1969 ..
-????????? ? ?    ?    ?            ? a.txt
d????????? ? ?    ?    ?            ? folder
d????????? ? ?    ?    ?            ? $RECYCLE.BIN
d????????? ? ?    ?    ?            ? System Volume Information

* Your Windows build number
14393.477

**Comment by fpqc** [comment]
Does your windows user have permission to the ReFS files?

**Comment by caiokat** [comment]
Yes.

I've tried running bash as admin and using sudo, but it still doesn't work.

**Comment by 0xbadfca11** [comment]
Are you using the mounted VHD or VHDX? Even if you are using through the storage spaces. #1199

**Comment by caiokat** [comment]
I was using Storage Spaces with VHDs.

I just tried it with physical drives and it seems to be working.

**Comment by tara-raj** [comment]
Closing this issue. Please re-open if you are experiencing this issue on a more recent version of WSL.
