### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by Ayzak** [Microsoft/WSL#1374]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* I can't install or uninstall or upgrade anything.

* Expected results is an apt-get upgrade.

* Actual results :
root~#[0]> apt-get upgrade                                                                                                                                 Lecture des listes de paquets... Fait                                                                                                                      Construction de l'arbre des dépendances                                                                                                                    Lecture des informations d'état... Fait                                                                                                                    Calcul de la mise à jour... Fait                                                                                                                           Les paquets suivants seront mis à jour :                                                                                                                     accountsservice apt apt-transport-https apt-utils bind9-host cloud-init dbus                                                                               dnsutils gnupg isc-dhcp-client isc-dhcp-common libaccountsservice0                                                                                         libapt-inst1.5 libapt-pkg4.12 libbind9-90 libdbus-1-3 libdns100 libisc95                                                                                   libisccc90 libisccfg90 liblwres90 linux-libc-dev lsb-base lsb-release                                                                                      ntpdate openssh-client openssh-server openssh-sftp-server openssl pollinate                                                                                sudo tzdata                                                                                                                                              32 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.                                                                                  16 partiellement installés ou enlevés.                                                                                                                     Il est nécessaire de prendre 0 o/8 319 ko dans les archives.                                                                                               Après cette opération, 28,7 ko d'espace disque supplémentaires seront utilisés.                                                                            Souhaitez-vous continuer ? [O/n]                                                                                                                           Extraction des modèles depuis les paquets : 100%                                                                                                           Préconfiguration des paquets...                                                                                                                            (Lecture de la base de données... 30868 fichiers et répertoires déjà installés.)                                                                           Préparation du dépaquetage de .../lsb-release_4.1+Debian11ubuntu6.2_all.deb ...                                                                            Traceback (most recent call last):                                                                                                                           File "/usr/bin/pyclean", line 31, in <module>                                                                                                                from debpython import files as dpf                                                                                                                     ImportError: No module named debpython                                                                                                                     dpkg : avertissement : le sous-processus ancien script pre-removal a retourné une erreur de sortie d'état 1                                                dpkg: tentative d'exécution du script du nouveau paquet à la place...                                                                                      Traceback (most recent call last):                                                                                                                           File "/usr/bin/pyclean", line 31, in <module>                                                                                                                from debpython import files as dpf                                                                                                                     ImportError: No module named debpython                                                                                                                     dpkg: erreur de traitement de l'archive /var/cache/apt/archives/lsb-release_4.1+Debian11ubuntu6.2_all.deb (--unpack) :                                      le sous-processus nouveau script pre-removal a retourné une erreur de sortie d'état 1                                                                     Traceback (most recent call last):                                                                                                                           File "/usr/bin/pycompile", line 35, in <module>                                                                                                              from debpython.version import SUPPORTED, debsorted, vrepr, \                                                                                           ImportError: No module named debpython.version                                                                                                             dpkg : erreur lors du nettoyage :                                                                                                                           le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1                                                              Des erreurs ont été rencontrées pendant l'exécution :                                                                                                       /var/cache/apt/archives/lsb-release_4.1+Debian11ubuntu6.2_all.deb                                                                                         E: Sub-process /usr/bin/dpkg returned an error code (1)        

* Your Windows build number
Windows 10 Home
Build 1607

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @Ayzak -- based on your shell prompt, it looks like you've made some changes to your environment.  Do you experience this issue on a stock WSL installation?  (Ticket #4 discusses how to uninstall and reinstall WSL.)

It looks to me like your local Python package directory has gotten corrupted somehow -- either you have deleted the "debpython" module or you have installed a new version of an existing module that depends on it.

If you're encountering this issue because of changes that you have made to your local Linux environment, or because of localization/language issues (for example a bug in Ubuntu that only manifests when Ubuntu is configured to use a non-English language), you may have more success asking for help on an Ubuntu forum.

**Comment by aseering** [comment]
Also -- just so you know, when pasting large blocks of text into a Github bug report, it's much more readable if you surround that text with three backticks.  For example,

\`\`\`
Some text
\`\`\`

becomes

```
Some text
```

And your terminal output above becomes:

```
root~#[0]> apt-get upgrade                                                                                                                                 Lecture des listes de paquets... Fait                                                                                                                      Construction de l'arbre des dépendances                                                                                                                    Lecture des informations d'état... Fait                                                                                                                    Calcul de la mise à jour... Fait                                                                                                                           Les paquets suivants seront mis à jour :                                                                                                                     accountsservice apt apt-transport-https apt-utils bind9-host cloud-init dbus                                                                               dnsutils gnupg isc-dhcp-client isc-dhcp-common libaccountsservice0                                                                                         libapt-inst1.5 libapt-pkg4.12 libbind9-90 libdbus-1-3 libdns100 libisc95                                                                                   libisccc90 libisccfg90 liblwres90 linux-libc-dev lsb-base lsb-release                                                                                      ntpdate openssh-client openssh-server openssh-sftp-server openssl pollinate                                                                                sudo tzdata                                                                                                                                              32 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.                                                                                  16 partiellement installés ou enlevés.                                                                                                                     Il est nécessaire de prendre 0 o/8 319 ko dans les archives.                                                                                               Après cette opération, 28,7 ko d'espace disque supplémentaires seront utilisés.                                                                            Souhaitez-vous continuer ? [O/n]                                                                                                                           Extraction des modèles depuis les paquets : 100%                                                                                                           Préconfiguration des paquets...                                                                                                                            (Lecture de la base de données... 30868 fichiers et répertoires déjà installés.)                                                                           Préparation du dépaquetage de .../lsb-release_4.1+Debian11ubuntu6.2_all.deb ...                                                                            Traceback (most recent call last):                                                                                                                           File "/usr/bin/pyclean", line 31, in                                                                                                                 from debpython import files as dpf                                                                                                                     ImportError: No module named debpython                                                                                                                     dpkg : avertissement : le sous-processus ancien script pre-removal a retourné une erreur de sortie d'état 1                                                dpkg: tentative d'exécution du script du nouveau paquet à la place...                                                                                      Traceback (most recent call last):                                                                                                                           File "/usr/bin/pyclean", line 31, in                                                                                                                 from debpython import files as dpf                                                                                                                     ImportError: No module named debpython                                                                                                                     dpkg: erreur de traitement de l'archive /var/cache/apt/archives/lsb-release_4.1+Debian11ubuntu6.2_all.deb (--unpack) :                                      le sous-processus nouveau script pre-removal a retourné une erreur de sortie d'état 1                                                                     Traceback (most recent call last):                                                                                                                           File "/usr/bin/pycompile", line 35, in                                                                                                               from debpython.version import SUPPORTED, debsorted, vrepr, \                                                                                           ImportError: No module named debpython.version                                                                                                             dpkg : erreur lors du nettoyage :                                                                                                                           le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1                                                              Des erreurs ont été rencontrées pendant l'exécution :                                                                                                       /var/cache/apt/archives/lsb-release_4.1+Debian11ubuntu6.2_all.deb                                                                                         E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Ayzak** [comment]
oooh ok, I'm sorry I didn't know this ^^ thank you :)

**Comment by Boddlnagg** [comment]
I got a similar error with a `sudo apt-get upgrade` today. The full output is in a [gist](https://gist.github.com/Boddlnagg/761bd946ca6d43706cd55b391c692e0e) (German locale unfortunately), but I think the relevant lines are:
```
Entpacken von accountsservice (0.6.35-0ubuntu7.3) über (0.6.35-0ubuntu7.2) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/accountsservice_0.6.35-0ubuntu7.3_amd64.deb (--unpack):
 »/usr/lib/accountsservice/accounts-daemon.dpkg-new« kann nicht geöffnet werden: Keine Berechtigung
dmesg: klogctl failed: Die angeforderte Funktion ist nicht implementiert
                                                                        Vorbereitung zum Entpacken von .../libaccountsservice0_0.6.35-0ubuntu7.3_amd64.deb ...

...

Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/accountsservice_0.6.35-0ubuntu7.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Afterwards every `apt-get` command failed due to unresolved dependencies:
```
Probieren Sie »apt-get -f install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 accountsservice : Hängt ab von: libaccountsservice0 (= 0.6.35-0ubuntu7.2) aber 0.6.35-0ubuntu7.3 ist installiert
E: Unerfüllte Abhängigkeiten. Versuchen Sie, -f zu benutzen.
```
... until I did `sudo apt-get -f install accountsservice`, which lets me use `apt-get` again, but I'm not sure if everything is installed correctly now.

My Windows version is 1607 (Build 14393.447), not on Insider Preview.

**Comment by Ayzak** [comment]
I found a solution here : http://www.linuxquestions.org/questions/debian-26/sub-process-usr-bin-dpkg-returned-an-error-code-1-a-171107/

For me it's work.
Can you tell me if it's work for you @Boddlnagg ? :)

````
#!/bin/sh                                                                                                                                                2
#if "E: Sub-process /usr/bin/dpkg returned an error code (1)" error.
 
rm -f /var/lib/dpkg/info/*
rm -rf /var/cache/apt/archives/*
```
