### ISSUE TITLE
bash.exe is not in PATH for 32-bits cmd.exe sessions

### ISSUE THREAD

**Issue by xilun** [microsoft/WSL#1376]
* A brief description

I was just trying VS17 RC and at a point launched a dev cmd line from the GUI. devenv being stubbornly 32-bits (bouuuuu!) , it launches a 32-bits cmd.exe. Therefore, no bash.exe in PATH in this context.

* Expected results

bash.exe should be invoked when I type "bash" in cmd, even if its a 32-bits cmd.exe for some kind of reactionary reasons ;)

* Actual results (with terminal output if applicable)

bash.exe is not in PATH in this case, therefore on my French install:

    'bash' n’est pas reconnu en tant que commande interne
    ou externe, un programme exécutable ou un fichier de commandes.

(I know I can find it in sysnative but I'm way too lazy to type so many characters :p )

* Your Windows build number

14965

* Steps / All commands required to reproduce the error from a brand new installation 

Launch a 32-bits cmd. Type bash \<enter>

**Comment by therealkenc** [comment]
Forward /dupe #4660 #223
