### ISSUE TITLE
Problem with recompiling LaTeX-PDFs

### ISSUE THREAD

**Issue by peppegubben** [Microsoft/WSL#1379]
* A brief description
When compiling a LaTeX that has previously already been compiled, the `pdflatex`-command won't work. That means that I have to remove the file every time. Witch is not only time consuming, it also makes the referencing system in LaTeX practicly impossible to use.

* Expected results
The pdf and log-files should be regenerated

* Actual results (with terminal output if applicable)
The LaTeX compiler asks me to change the name of the file I'm trying to generate:
`Jesper@MSI:/mnt/d/skola/LinjärAlgebraOchFunktionslära/LinjärAlgebra/test$ pdflatex LinjärAlgebra2016-11-14.tex                                                                                This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)                                                                                                                           restricted \write18 enabled.                                                                                                                                                                 entering extended mode                                                                                                                                                                        (./LinjärAlgebra2016-11-14.tex                                                                                                                                                                LaTeX2e <2011/06/27>                                                                                                                                                                          Babel <3.9h> and hyphenation patterns for 2 languages loaded.                                                                                                                                 (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls                                                                                                                                     Document Class: article 2007/10/19 v1.4h Standard LaTeX document class                                                                                                                        (/usr/share/texlive/texmf-dist/tex/latex/base/size12.clo))                                                                                                                                    (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty                                                                                                                                    (/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def                                                                                                                                        (/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)                                                                                                                                      (/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)                                                                                                                                     (/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))                                                                                                                                   (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty                                                                                                                                  For additional information on amsmath, use the `?' option.                                                                                                                                    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty                                                                                                                                  (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))                                                                                                                                 (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)                                                                                                                                  (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))                                                                                                                                 (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty                                                                                                                                 (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))                                                                                                                              (/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)                                                                                                                                        (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty                                                                                                                                (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)                                                                                                                                 (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty                                                                                                                                (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)                                                                                                                                   (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)                                                                                                                            (/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def                                                                                                                                (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)                                                                                                                            (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))                                                                                                                           (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty                                                                                                                                   (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))                                                                                                                              (./LinjärAlgebra2016-11-14.aux)                                                                                                                                                               (/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii                                                                                                                                 [Loading MPS to PDF converter (version 2006.09.02).]                                                                                                                                          ) (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty                                                                                                                          (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty)                                                                                                                             (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty))                                                                                                                               (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty                                                                                                                           (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty                                                                                                                                  (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))                                                                                                                        (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty                                                                                                                               (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty                                                                                                                             (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty)))                                                                                                                           (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))                                                                                                                       (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)                                                                                                                                    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)                                                                                                                                    ! I can't write on file `LinjärAlgebra2016-11-14.pdf'.                                                                                                                                        (Press Enter to retry, or Control-D to exit; default file extension is `.pdf')                                                                                                                Please type another file name for output:       `

* Your Windows build number
143993447

* Steps / All commands required to reproduce the error from a brand new installation 
1. install the texbase-package
2. create a compilable .tex-file
3. pdflatex filename.tex
4. pdflatex filename.tex

* Strace of the failing command
There where hundreds of lines, it would probably take me half an hour or so to copy the entire output.

* Required packages and commands to install
to get the compiler:
sudo apt-get install texlive-latex-base

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by 0xabu** [comment]
FWIW, I've been using pdflatex under WSL and haven't seen anything like this. Maybe something on the Windows side (AV? file sync?) is grabbing a lock on the file right after it is closed (the first time), and preventing it from being opened a second time? Maybe you have an ACL problem?

I suggest trying in a different directory. If all else fails, you might be able to compile on VolFs (e.g. /home/...) and then copy the pdf back over to /mnt when you're done.

**Comment by pikachuyann** [comment]
You should probably either use MikTeX to compile directly from Windows, or copy your source files to the linux home _through Bash on Windows_. 

As the name of the folder suggests, /mnt/c is «mounted» as a separate partition in the Linux subsystem and it is not guaranteed you have all the writing permissions on that mounted disk.
Also, avoid directly accessing Linux folders from Windows as doing changes from Windows may break the Ubuntu-on-Windows filesystem.

**Comment by benhillis** [comment]
Much has changed since 2016, please open a new issue if you continue to have issues on newer Windows builds.
