### ISSUE TITLE
File system gets corrupted during the normal use

### ISSUE THREAD

**Issue by nkakuev** [Microsoft/WSL#1381]
Sometimes performing regular actions - like writing to files or unlinking them leads to file system corruption.

It seems like directory entries are still there, but the inodes are already gone.
Here is how the `ls` output looks like for a directory with corrupted files:
```
$ ll
ls: cannot access print_file: No such file or directory
ls: cannot access track_fds.c: No such file or directory
ls: cannot access track_fds.c~: No such file or directory
total 4
drwxrwxrwx 2 root root 0 Nov 13 22:52 ./
drwxrwxrwx 2 root root 0 Nov 18 00:29 ../
-????????? ? ?    ?    ?            ? print_file
-????????? ? ?    ?    ?            ? track_fds.c
-????????? ? ?    ?    ?            ? track_fds.c~
```

`ls` successfully gets dentries:
`getdents(3, /* 5 entries */, 32768)     = 136`

But cannot `stat` any files:
`lstat("track_fds.c", 0x2483ec0)         = -1 ENOENT (No such file or directory)`

Unlinking such files also fails with `NOENT`:
`unlinkat(4, "print_file", 0)            = -1 ENOENT (No such file or directory)`

Sometimes "broken" files automagically disappear after a certain amount of time. Other times they persist between reboots.

I couldn't find a reliable way to reproduce this issue. It seems to happen randomly.

Files are located on an NTFS partition.
Microsoft Windows [Version 10.0.14393]

**Comment by benhillis** [comment]
@nkakuev - Would it be possible to provide some reproduction steps how you got into this state?

**Comment by fpqc** [comment]
Let me guess, were you opening files in LXSS with Win32 applications?

**Comment by nkakuev** [comment]
@benhillis I cannot reliably reproduce the issue. Last time it happened I issued a simple `rm` command:
`rm -rf CMakeCache.txt CMakeFiles/ cmake_install.cmake compile_commands.json  Makefile TidyTest`

@fpqc Both times this happened I was either `mv`ing or `rm`ing files.

**Comment by benhillis** [comment]
We have fixed a myriad of issues since 2016, if you continue to experience this issue please reopen.
