### ISSUE TITLE
bash does not go to corresponding windows directory anymore

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/WSL#1389]
After upgrading to Insider Version 14965, it seems like after entering the bash shell through a Windows directory in the command prompt, the bash shell automatically goes to home, instead of the corresponding linux directory. I think this change should be reverted, if it was intentional, as this was an easy way of switching directories in WSL, given that it is hard to convert windows path names to linux path names.

**Comment by benhillis** [comment]
Can you provide some more repro steps? This is unexpected unless you are launching with bash.exe ~ or the shortcut. 

Does this happen for all paths?

**Comment by alexanderwhatley** [comment]
I'm not sure what repro steps I could give you other than just typing "bash" in the command prompt, but it seems like it started happening as soon as I updated to 14965. Attached is a screenshot:

![image](https://cloud.githubusercontent.com/assets/14192598/20452461/300cee16-add8-11e6-9d2b-b5a2c9168866.png)

**Comment by benhillis** [comment]
Sorry for my terseness, that's what I get when I try to respond to GitHub posts while walking the dog :)

That's what I was looking for, an example path. The was previously an issue with UTF-8 paths but yours looks normal. Would you be able to take a trace for me?

	1. Download the below two .txt files and rename them .cmd
	2. Run start_lxcore_trace.cmd from an admin command prompt
	3. Launch bash.exe
	4. Type 'exit'
	5. Run stop_lxcore_trace.cmd from an admin command prompt
	6. You should now see three .etl files in the directory you ran the script from.
	7. Post the files here.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by alexanderwhatley** [comment]
@benhillis I see four .etl files not three, but here they are. 


[ETL Files.zip](https://github.com/Microsoft/BashOnWindows/files/601274/ETL.Files.zip)

**Comment by alexanderwhatley** [comment]
Also interesting - as soon as I opened the Administrator Command Prompt, it started working correctly again. I wonder if this has something to do with permissions....

**Comment by S-ed** [comment]
Unicode is not the issue.
![screenshot 1479550473](https://cloud.githubusercontent.com/assets/3008353/20454743/c687be16-ae5a-11e6-9c9e-a9dd36d7d6f8.png)
Probably the issue with permissions. Not sure why exactly (I've tried to reproduce but had no success).

**Comment by benhillis** [comment]
@alexanderwhatley  - Just to confirm, was the translation successful during the trace you took?  If so unfortunately they wont' be useful.

If that is the case you'll have to start the trace in an admin cmd prompt, and run bash.exe out of a different non-admin.

**Comment by benhillis** [comment]
@alexanderwhatley  - Looked through the trace and for some reason when translating is returning 0x80070003 (2147942403) - The system cannot find the path specified.

If you could provide any more information about your configuration, specifically permissions on you drives, that would be very useful as I'm unable to reproduce this locally.

**Comment by alexanderwhatley** [comment]
@benhillis As far as I know, the permissions on my drives should all be fine. I can't think of anything I did that could cause permission issues
[Debug.zip](https://github.com/Microsoft/BashOnWindows/files/601831/Debug.zip)
. I ran into this same problem again today, and ran the trace while the problem occured, and hopefully the debug information is more useful now.

**Comment by alexanderwhatley** [comment]
Another thing to note is that as soon as I ran the trace, the problem went away.

**Comment by benhillis** [comment]
Thanks for the additional trace. This is mysterious, the error is coming up as a "file not found" error when trying to open a handle to your NT current working directory. Something on your machine is causing 

Can you tell me more information about your device?
1. Are you running bitlocker or some third party encryption / virus scanner?
2. Could you share the output of `cmd.exe /c "echo %PATH%"`

**Comment by alexanderwhatley** [comment]
1. I am not running bitlocker or any other encryptor, and I don't believe I'm running any virus scanner. 
2. C:\Users\Alexander>cmd.exe /c "echo %PATH%"
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Java\jdk1.7.0_55\jre\bin;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\Program Files (x86)\Java\jdk1.7.0_55\bin;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\apache-ant-1.9.3\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\WINDOWS\system32;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Users\Alexander\Anaconda3;C:\Users\Alexander\Anaconda3\Scripts;C:\Users\Alexander\Anaconda3\Library\bin;C:\Users\Alexander\Anaconda;C:\Users\Alexander\Anaconda\Scripts;C:\Users\Alexander\Anaconda\Library\bin;C:\Users\Alexander\.dnx\bin;C:\mongodb\bin\mongo.exe;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\MongoDB\Server\3.0\bin;C:\Users\Alexander\AppData\Roaming\npm;C:\Users\Alexander\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Java\jre1.8.0_74\bin\server;C:\Program Files (x86)\Tesseract-OCR/tesseract.exe;c:\program files\java\jre1.8.0_77\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\Alexander\Documents\dos2unix-7.3.3-win32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Alexander\Downloads\mingw-w64\x86_64-5.3.0-win32-seh-rt_v4-rev0\mingw64\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\scala\bin;C:\Program Files\MATLAB\R2016a\runtime\win64;C:\Program Files\MATLAB\R2016a\bin;C:\Program Files (x86)\PuTTY\;C:\Users\Alexander\Anaconda3;C:\Users\Alexander\Anaconda3\Scripts;C:\Users\Alexander\Anaconda3\Library\bin;C:\Users\Alexander\.dnx\bin;C:\mongodb\bin\mongo.exe;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files (x86)\Git\bin;C:\Program Files\MongoDB\Server\3.0\bin;C:\Users\Alexander\AppData\Roaming\npm;C:\Users\Alexander\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Java\jre1.8.0_74\bin\server;C:\Program Files (x86)\Tesseract-OCR/tesseract.exe;C:\Users\Alexander\Anaconda;C:\Program Files\Git\bin;C:\Users\Alexander\AppData\Local\Microsoft\WindowsApps;
