### ISSUE TITLE
Till now I used Putty, but if I move to openSSH and mistakenly closing WSL CMD connection lost?

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1396]
Till now I used Putty, and I consider moving to use openSSH with WSL. Now, as You know, when you run Putty's Pageant to load your private keys, it's just running as a background task, "well hidden" in the system tray so you can't quite elusively close it by mistake.

But what if I'll use SSH-agent of OpenSSH via the WSL on CMD or Powershell? These are part of task bar, not of the system tray, as you well know, so If I mistakenly close the window the connection lost and I'll need to load **all keys** each time a new... Even with a script it could be a bit annoying as entering both the Unix password and the passphrase each time can take some time especially if it happened twice or more in one day.

You might have any thought on how to better prepare for such problem or just how would you prevent it ahead?

**Comment by ginto-sakata** [comment]
This will help you: https://github.com/cerebrate/wabash

**Comment by therealkenc** [comment]
This one was obscured by the wording chosen in the OP. `ssh-agent` should run fine on WSL; if it does not please open a bug report following the template. Auto-startup of services (`ssh-agent` or otherwise) is covered in #709 (among others) and has improved quite a bit as of 17046.
