### ISSUE TITLE
Random "socket hang up" with node.js while testing code locally

### ISSUE THREAD

**Issue by vinz243** [microsoft/WSL#1418]
I have a nodejs server with Koajs. When I try to run test on endpoints using supertest, I get random `socket hang up` errors:

    failed with "socket hang up"
          createHangUpError (_http_client.js:254:15)
        Socket.socketOnEnd (_http_client.js:346:23)
        endReadableNT (_stream_readable.js:974:12)
        _combinedTickCallback (internal/process/next_tick.js:74:11)
        process._tickCallback (internal/process/next_tick.js:98:9)
        From previous event:
            Test.toPromise (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest-as-promised/index.js:16:12)
            Test.then (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest-as-promised/index.js:34:17)

Those happens on random test, they may later be working fine when other do not work.

I also get some errors like this:

    failed with "Cannot read property 'status' of undefined"
          Test._assertStatus (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest/lib/test.js:263:10)
        Test._assertFunction (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest/lib/test.js:281:11)
        Test.assert (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest/lib/test.js:171:18)
        assert (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest/lib/test.js:131:12)
        /mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest/lib/test.js:128:5
        Test.Request.callback (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/superagent/lib/node/index.js:615:12)
        ClientRequest.<anonymous> (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/superagent/lib/node/index.js:567:10)
        Socket.socketOnEnd (_http_client.js:346:9)
        endReadableNT (_stream_readable.js:974:12)
        _combinedTickCallback (internal/process/next_tick.js:74:11)
        process._tickCallback (internal/process/next_tick.js:98:9)
        From previous event:
            Test.toPromise (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest-as-promised/index.js:16:12)
            Test.then (/mnt/d/Users/Vincent/Documents/Developement/cassette/node_modules/supertest-as-promised/index.js:34:17)

Here is a single test ran with `NODE_DEBUG=net`: 
<kbd>[Haste bin][1]</kbd>

**I am running Windows Subsystem for Linux** on a HP Pavilion Gaming 15 AK 100NF (i5 6300HQ, 6B of RAM).

**Travis tests** work just fine. On another Windows Machine with WSL it works great too.

<kbd>[Full source][2]</kbd>

I am not the only one having this issue, also happens in python https://github.com/gevent/gevent

  [1]: http://hastebin.com/utedosohek "hastebin"
  [2]: http://github.com/vinz243/cassette

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Which Windows version are you using?

**Comment by vinz243** [comment]
It's Windows 10 Entreprise 1607 14393.447

**Comment by stehufntdev** [comment]
Great, thanks.  There have been a number of socket fixes in the insider builds so this may already been fixed.  Adding @sunilmut to see what he thinks.

**Comment by vinz243** [comment]
Ok thanks, looking forward for updates :)

**Comment by sunilmut** [comment]
Thanks @vinz243 for running these tests and reporting issues. We greatly appreciate it. Thanks @stehufntdev for chiming in. As @stehufntdev points out, we have made considerable improvements in the socket code base, which are not available in the RS1 updates. There are still some known issues with sockets, such as hangs #616  and data loss #610. Both these issues are actively being worked on as we speak and we expect a fix soon. But, all of these goodness (fixes) are only available through the Windows Insider builds. We would love if you can try your workflows on the Insider builds (if you cant afford these builds on your main box, maybe use a VM?), and give us the feedback, report issues.

**Comment by tlrdstd** [comment]
I know this issue is four years old, but it bit me today. I moved some node code that hits Google Cloud Platform from my Ubuntu VM to my WSL. Everything works, except roughly 1 call in 10 crashes with `socket hung up`:

```
[start] FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/xuor/dev/redeemer/sync-calendars-on-demand/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketOnEnd (_http_client.js:435:9)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Luis-Palacios** [comment]
I'm having a similar issue, on current build of WSL 2, did anybody find a solution for this?

**Comment by therealkenc** [comment]
This is worth rebooting under a new issue for "similar issues" on WSL2. As [noted](https://github.com/microsoft/WSL/issues/1418#issuecomment-264589199) there were #616 #610 improvements back in the day for WSL1, but whether the problem (such that it is) was addressed we'll never know. There was a dearth of likes on the OP. A new submission really would need a clear set of CLI steps that demonstrate a reproducible fail (contrast random) though, or it will probably have about as much chance as in 2016. It would be worth tracking down the problem if there _is_ a repro.
