### ISSUE TITLE
100% disk usage when compiling with g++

### ISSUE THREAD

**Issue by srinath29** [Microsoft/WSL#1438]
* A brief description
I have installed g++ 4.9.4 from [this](http://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu)
Installed boost libraries regularly like 
`sudo apt-get install libboost-all-dev` 

Now I am running the code which is using ptree from boost::property_tree

When I am trying to compile, I am getting 100% disk usage with 0 KB/s Read and 0KB/s write (From task manager) 
* Expected results
To compile without high disk usage activity
* Actual results (with terminal output if applicable)
System getting stuck
* Your Windows build number
14393.477

**Comment by benhillis** [comment]
Compiling tends to be a very IO heavy operation so 100% disk usage isn't entirely surprising.  Can you go into a bit more detail about the read / write statistics?  Is the operation hung or are you seeing a prolonged 0 KB/s Read / Write value in task manager?

**Comment by aseering** [comment]
@benhillis -- my sense of the expectations of the community that builds for C++/Linux/gcc is that those builds are *highly* CPU-bound, even on the fastest multi-core workstations with the slowest of local disks.  (Doubly so with Boost, as in this example -- `boost::property_tree` is not the worst offender, but many of Boost's sub-packages have headers that use creative language features so are very computationally intensive to `#include`.)  I think this is very different than, for example, C# on Windows -- for one thing, C# turns out to be a dramatically cheaper language to parse.

**Comment by srinath29** [comment]
Actually, when I am trying to compile a code which doesn't have dependency on boost, it sometimes works and sometimes not (100% disk usage, everything freezes). But with boost, it always happens. In previous builds this was not happening. Actually the 100% disk usage is a windows 10 issue . Lot of my friends are facing the same issue. Old laptops upgraded to windows 10 are often having 100% disk usage even though nothing is being done. I don't know whether that bug is affecting bash here.

**Comment by yorickdowne** [comment]
@srinath29 Can you provide sample code to compile and exact steps to reproduce? I'd like to see how it behaves on my end. For no good reason other than that I'm curious and would like to help. 

Also, have you checked:
- Any storage driver interrupts in event log?
- https://support.microsoft.com/en-us/kb/3083595 applies?
-  Running Intel RST? Current version?
- Link state power management an issue? https://blogs.technet.microsoft.com/kevinholman/2013/06/21/event-id-129-storachi-reset-to-device-deviceraidport0-was-issued/
- Is this relevant? 
"If you still have random freezing u/rucosmer has a possible solution: "Who has Intel AHCI driver (iaStorA.sys, latest version on my system is 14.8.12.1059) please try to set all kind of Controller0Phy0DIPM and Controller0Phy0HIPM settings to "0": HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\iaStorA\Parameters\Device""

**Comment by srinath29** [comment]
@yorickdowne My laptop broke, for some reason the disk load was at 99% and suddenly stopped working and not even booting. I think I cannot share the other questions except code with you. 

```
#include<iostream>
#include<vector>
#include<boost/any.hpp>
#include<algorithm>
#include<typeinfo>
#include "csv/typename.hpp"

typedef void* Handle;
using namespace std::literals::string_literals;
int main(){
    std::vector<boost::any> v;
    v.push_back("Char"s);
    //v.push_back("hk");

    //std::cout<<type_name(boost::any_cast<std::string>(&v[0]));
    //std::cout<< reinterpret_cast<std::vector<int>>(h)[0];
    std::cout<<boost::any_cast<std::string>(v[0])<<"\n";
}
```
This works sometimes and sometimes not.

**Comment by yorickdowne** [comment]
That won't compile here, too many dependencies I don't have. I used the code from http://www.cppsamples.com/common-tasks/choose-random-element.html and compiled it with `g++ -c -std=c++11 test.c` and that was quick, no 100% disk usage.

I think you have an issue with your laptop, not with WSL. This doesn't look like a WSL bug.
