### ISSUE TITLE
What is the use of all the scripts in /etc/cron.daily?

### ISSUE THREAD

**Issue by gaia** [Microsoft/WSL#1449]
Since cron does not run if the bash window is closed, why are there no many scripts in cron.daily? Would they only execute if bash is open at the time they are supposed to execute or ... ?

```
>ll
total 56
drwxr-xr-x 2 root root     0 Oct 22 07:07 ./
drwxr-xr-x 2 root root     0 Dec  2 11:27 ../
-rwxr-xr-x 1 root root   376 Apr  4  2014 apport*
-rwxr-xr-x 1 root root 15481 Apr 10  2014 apt*
-rwxr-xr-x 1 root root   314 Feb 17  2014 aptitude*
-rwxr-xr-x 1 root root   355 Jun  4  2013 bsdmainutils*
-rwxr-xr-x 1 root root   256 Mar  7  2014 dpkg*
-rwxr-xr-x 1 root root   372 Jan 22  2014 logrotate*
-rwxr-xr-x 1 root root  1261 Sep 23  2014 man-db*
-rwxr-xr-x 1 root root   435 Jun 20  2013 mlocate*
-rwxr-xr-x 1 root root   249 Feb 16  2014 passwd*
-rw-r--r-- 1 root root   102 Feb  8  2013 .placeholder
-rwxr-xr-x 1 root root  2417 May 13  2013 popularity-contest*
-rwxr-xr-x 1 root root   214 Oct  6  2014 update-notifier-common*
-rwxr-xr-x 1 root root   328 Jul 18  2014 upstart*
```

**Comment by fpqc** [comment]
They're all part of an ubuntu docker image install I thinik

**Comment by sunilmut** [comment]
Yes, they are part of the Ubuntu user mode image, which is largely untouched in WSL. We do have a custom `init` and we modify couple of networking related files such as `/etc/hosts` and `/etc/resolv.conf`. But, everything else is untouched. `cron` jobs are not officially supported on WSL, currently. If you would like to see better support for it in the future, please help us prioritize it be heading to our user voice page and casting your vote. [Here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-background) is the ticket for it.

**Comment by gaia** [comment]
Thank you, @sunilmut - it is clear now.

**Comment by gaia** [comment]
If anyone cares to comment here, thank you: http://askubuntu.com/questions/857140/how-to-use-windows-task-scheduler-to-run-updatedb

**Comment by therealkenc** [comment]
The OP in this one was a question with an answer. For more on `cron` see #344.
