### ISSUE TITLE
Add vulkan support with BashOnWindows

### ISSUE THREAD

**Issue by lygstate** [Microsoft/WSL#1457]
And with this support, I believe we could gain Wayland support, and then X support, and others.

**Comment by fpqc** [comment]
The problem isn't supporting vulkan, per se.  It's making the graphics card available to the lxss environment, which is not an easy task (though it seems they are working on it).

**Comment by lygstate** [comment]
I mean not add graphics card， but redirect the vulkan API calls to winddows driver

**Comment by lygstate** [comment]
and implement a virtual wayland display server not depends on hardware

**Comment by fpqc** [comment]
@lygstate Vulkan is not transmitted over a network-transparent protocol, so it still needs to ultimately be implemented by sending ioctls to the graphics card driver.  This means writing a compatibility layer between the Linux graphics drivers in usermode and the Windows kernel drivers in kernelmode.

**Comment by lygstate** [comment]
yes we need wsl team's help about how to redirect API calles from Linux to Windows

**Comment by fpqc** [comment]
@lygstate If that will ever happen, it will be a long time from now. The kernel-facing API (for WSL drivers) is not stable now, and I have no idea if they will ever version it.

**Comment by therealkenc** [comment]
In the mean time you can upvote [CUDA](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support), which is on the backlog.

**Comment by lygstate** [comment]
I do not upvote cuda because Mobile phone doesn't support it properly

**Comment by gnsmrky** [comment]
@lygstate @fpqc Just found a way to run vulkan in WSL1 using software renderer in mesa 20.3.  If you would still like to try vulkan in WSL, give it a shot.

[wsl-vulkan-mesa repo](https://github.com/gnsmrky/wsl-vulkan-mesa)
