### ISSUE TITLE
Graphical glitches with spacemacs

### ISSUE THREAD

**Issue by mimischi** [Microsoft/WSL#1461]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

This issue arises from both the stable emacs24 version, as well as emacs25. I can't test emacs-snapshot (emacs26?) as, it will start with a blank window and throw me some libgl errors. Building emacs from source does not work, just a was described in #236.

Currently using Ubuntu 16.04 with VcXsrv.

* A brief description

spacemacs shows graphical glitches when using auto-complete or the lint features.

* Actual results (with terminal output if applicable)

This GIF demonstrates the problem. The window looks as it should until I hover over the unused import statement, which triggers that small tooltip to show up. After that I get graphical glitches all over.

![display-bug](https://cloud.githubusercontent.com/assets/1052860/20879305/6bebc792-bad3-11e6-9c4a-c9faf3672d68.gif)

* Your Windows build number
14965.1001

**Comment by mimischi** [comment]
Looks like it is some issue with the Gtk version of emacs. Installing emacs24-lucid with ``apt install emacs24-lucid`` and choosing that as a default with ``update-alternatives --config emacs`` actually gets rid of this display error.

**Comment by therealkenc** [comment]
Might be worth adding a github label "**linux-behavior**", which fits the bill for a countable segment of issues posted. If it can't be "fixed" in WSL then it isn't an open WSL issue. If there's a workaround for WSL that might not be necessary in the future, it's a WSL bug or a feature, depending on one's disposition.

**Comment by sunilmut** [comment]
@therealkenc Label created and added.
