### ISSUE TITLE
password does not protect ssh access

### ISSUE THREAD

**Issue by meoso** [Microsoft/WSL#1465]
* A brief description:
ssh login security is simply bypassed:  I installed/enabled developer mode bash.  I ssh'd from another client and pressed enter to bypass my password and got a command prompt.  i was able to see full DIR listings and TYPE text files.  I could not create/delete files however.

* Expected results:
no access whatsoever. no bypass of password.

* Actual results (with terminal output if applicable)
http://pastebin.com/T55yB6BD

* Your Windows build number:
14393.447.amd64fre.rs1_release_inmarket.161102-0100

* Steps / All commands required to reproduce the error from a brand new installation 
Settings>Update & Security>For Developers>Developer Mode.
Turn Windows Features On or Off>[enable]Windows Subsystem for Linux (beta).
ssh from any *nix client, press enter or use an incorrect password to bypass login security.

**Comment by fpqc** [comment]
Isn't this the experimental SSH server that runs on port 22 when dev mode is on and is firewalled?

**Comment by aseering** [comment]
Hm, that's not good...  How did you set up ssh access?

WSL doesn't come with SSH access.  You have to set it up; doing so is actually [kind of a pain](https://wsl-forum.qztc.io/viewtopic.php?f=6&t=10) right now, and it's not supported, and in build 14393 it doesn't support giving you a Windows command prompt at all (though it should be possible in more-recent [Insider builds](https://insider.windows.com/)).

I guess I mean to say -- are you sure that you're seeing an ssh service provided by WSL?  Could it be an ssh service provided by some other app that has somehow gotten installed on your machine?  (This has happened to several other people in this bugtracker.)

**Comment by aseering** [comment]
@fpqc -- when was that server added?  I thought it was after the Anniversary Edition, but I could be mistaken.

**Comment by fpqc** [comment]
@aseering This is a devmode thing.  Remember why you need to run sshd on a diff port?  22 is already bound to this.

**Comment by aseering** [comment]
@fpqc I always ran WSL on port 22 :-)  Though, it's been a long time since I tried.

**Comment by benhillis** [comment]
@fpqc - Oh man, don't get me started on our experimental ssh sever...

**Comment by fpqc** [comment]
@benhillis Is that part of your team's work, or some other team?

**Comment by benhillis** [comment]
@fpqc - Some other team.

**Comment by meoso** [comment]
This is a fresh VM installed from `SW_DVD5_Win_Pro_10_64BIT_English_MLF_X20-25557.ISO` , nothing installed except Firefox, VLC, & devmode-linux-bash.  joined to domain.

**Comment by fpqc** [comment]
@meoso don't worry (maybe worry) about it.

**Comment by therealkenc** [comment]
Marking this as question for want of a better tag. The OP does not appear related to `sshd` on Ubuntu on WSL. The OpenSSH Beta in Windows 10 Fall Creators Update blog post is [here](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/) just as a reference.
