### ISSUE TITLE
Paste via keyboard, not via right mouse cursor

### ISSUE THREAD

**Issue by jepster** [Microsoft/WSL#1471]
* A brief description

Right now I can only paste text into the bash via the right mouse button. I would like to be able to do it like on Linux by "CTRL + V" (paste). How can I accomplish this in the WSL?

* Expected results

I can paste text via keyboard shortcuts.

* Your Windows build number

14393.0

**Comment by zadjii-msft** [comment]
oh god not this discussion again

**Comment by zadjii-msft** [comment]
For Context:

We at the console team have been _vigorously_ discussing this over the last week especially. It's unfortunately not a simple fix, so it's definitely not coming in the next release. @bitcrazed assures me it's on his hi-pri list for the next release (after the Creator's Update), so look for news on this some time after that.

I can assure you, this is most definitely something on the backlog.

**Comment by fpqc** [comment]
Please don't do this!!!  Actual Linux clipboard behavior is completely mad.

**Comment by jepster** [comment]
I am glad to read, that you are on this and we are in the same picture.

**Comment by zadjii-msft** [comment]
@fpqc Ideally, what I'd like to have happen is allow for the user to pick which buttons they'd like to be the copy-paste actions, whether it be Ctrl+C/V, Ctrl+Shift+C/V, Right click, middle click, whatever. That way each user can set it to exactly what they'd like it to be, and they know then that C-c isn't going through to kill the process because it's mapped to Copy, or C-v doesn't `scroll-up-command` in emacs because it's enabled as the paste key. 

User choice is key here, and making it configurable is the goal, and making it configurable requires a lot more than a week of dev time.

**Comment by fpqc** [comment]
@zadjii-msft What about select-to-copy-mode like barebones X does?  Also related, Shift+arrowkeys drops you into selection mode right now.  I hope that might be able to be disabled, as I use it for tmux.  I noticed that you did fix control+arrowkeys already!  Thanks!

**Comment by MikeGitb** [comment]
@zadji-msft: Making it configurable would certainly be nice (I like the right click though). But I'd really prefer, if you'd NOT copy the Linux semantics by default, where a mouse click doesn't paste the content in the clipboard, but whatever is currently highlighted.

**Comment by jepster** [comment]
Does anybody know alternative terminal programs which are adapting the functionality from the Bash and allow a functionality like this?

**Comment by fpqc** [comment]
@jepster [wslttt](/mintty/wsltty) and [wsl-terminal](/goreliu/wsl-terminal) both use mintty as the terminal emulator, which I think may support a keyboard-paste.

**Comment by krzysztofantczak** [comment]
Just a hint. Pretty old school shortcut, which is SHIFT + INS, works almost everywhere ;-) Including original cmd.exe and other kinds of terminals.

**Comment by clounie** [comment]
Just copy OS X's behavior, replacing Cmd with Alt...they got it right on that front.

**Comment by thenitai** [comment]
Coming from Linux, I'm REALLY missing ctrl+shift+c/v. This right click business is just awkward

**Comment by clounie** [comment]
Where did this get fixed?

**Comment by onomatopellan** [comment]
@clounie https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/
Regular user will get this on the next Feature Update. (~September)

**Comment by timrae** [comment]
Is there a good reason to not enable it by default other than "just in case"? Considering it's enabled by default in bash on Ubuntu, I find it hard to imagine enabling by default being an annoyance for more than a tiny handful of people. Conversely, not having it "just work" was most likely an annoyance for everyone who is subscribed to this issue. Please consider enabling by default in the very near future.
