### ISSUE TITLE
Piping arguments to an editor via xargs renders shell unusable after quitting the editor

### ISSUE THREAD

**Issue by nernst** [microsoft/WSL#1474]
**A brief description**
Executing a command like:
    find . -name "*.h" -o -name "*.cpp" | xargs vim
or
    ls *.py | xargs vim

results in the current shell being unusable after you quit vim. It appears mostly that characters are not being echo'd to the terminal properly. After quitting vim, if you type "exit" (and return) twice, usually, but not always, the shell quits.

**Expected results**
I would expect the bash shell to continue to function as normal. i.e. key strokes are properly echo'd to stdout.

**Actual results (with terminal output if applicable)**
Not possible, because the problem is that there is no output.

**Your Windows build number**
Version 10.0.14971

**Steps / All commands required to reproduce the error from a brand new installation** 
See description

**Strace of the failing command**
Not currently available, I could attempt to generate one if needed.

**Required packages and commands to install**
Everything required to reproduce should be included with default install.

**Comment by jackchammons** [comment]
I can reproduce this on 14986

**Comment by bitcrazed** [comment]
Still repro's on RS5/17672!

**Comment by therealkenc** [comment]
Can't repro here in 2004.
