### ISSUE TITLE
vim/vim-go ":GoInstallBinaries" Blue Screen

### ISSUE THREAD

**Issue by sywesk** [Microsoft/WSL#1481]
## A brief description

When asking vim's plugin vimgo to install the go binaries it needs, the system crashes.

## Expected results

Everything goes silky smooth.

## Actual results (with terminal output if applicable)

Blue screen of death.

## Your Windows build number

14965 (slow ring)

## Steps / All commands required to reproduce the error from a brand new installation 

Install the packages from the package section.
 - run vim
 - type :GoInstallBinaries and press enter

## Strace of the failing command

Not really applicable. But i have the minidump crash file. I can't find the symbols to analyse it windbg64 (getting 404 from the public symbol repo). But i could still find some interesting informations in the dump. Looks like a null pointer in getting dereferenced. I think with the address in Arg2, and a bit of reverse, you might find the function linked to it in your source. 

```
SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M (1000007e)
Arg1: ffffffffc0000005, The exception code that was not handled
Arg2: fffff8080198654c, The address that the exception occurred at
Arg3: ffff9d00f30da8e8, Exception Record Address
Arg4: ffff9d00f30da120, Context Record Address

FAULTING_IP: 
LXCORE+654c
fffff808`0198654c 488b01          mov     rax,qword ptr [rcx]

EXCEPTION_RECORD:  ffff9d00f30da8e8 -- (.exr 0xffff9d00f30da8e8)
ExceptionAddress: fffff8080198654c (LXCORE+0x000000000000654c)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

CONTEXT:  ffff9d00f30da120 -- (.cxr 0xffff9d00f30da120)
rax=ffffd00f221d8500 rbx=0000000000000000 rcx=0000000000000000
rdx=ffffd00f16e5c040 rsi=ffff8b05f16c9ed8 rdi=ffffd00f183fc4d0
rip=fffff8080198654c rsp=ffff9d00f30dab20 rbp=ffff8b05f16c9ef8
 r8=ffff8b05f16c9ed8  r9=0000000000000000 r10=7fff8b05f16c9ed8
r11=7ffffffffffffffc r12=ffff9d00e3ab10d2 r13=ffff8b05f16c9ed0
r14=ffffd00f183fc508 r15=ffffd00f15e63060
iopl=0         nv up ei ng nz na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010286
LXCORE+0x654c:
fffff808`0198654c 488b01          mov     rax,qword ptr [rcx] ds:002b:00000000`00000000=???????????????

```

## Required packages and commands to install

On a brand new bash subsystem : 

 - install go 
 - install the latest vim (that supports plugins by itself)
 - install https://github.com/fatih/vim-go

**Comment by fpqc** [comment]
They just fixed two known bsods in 14986.  Could you retest in the fast ring?

**Comment by sywesk** [comment]
@fpqc, well this is my main laptop, i put it on the slow ring so that some blocking bugs would be solved for me (restart system calls). But i don't really wish to go on the fast ring :/ 
But you got me really curious when you said "It is ostensibly more stable than the slow ring build on this account anyway". Can you explain me a bit more if you have some time ? :)

**Comment by fpqc** [comment]
The slow ring build contains at least two WSL-related BSODs (the most serious kind of bug, aka a kernel panic/bugcheck) that were fixed in the latest fast-ring build.  If you switch to the fast ring, you can switch back to the slow ring afterwards in the preferences, but 14986 is imo much better than 14965 (I bet it will be a slow-ring candidate).

**Comment by sywesk** [comment]
@fpqc it happens that you're right, this build is so unstable .. I got locked out of my laptop (and trust me i spent 2 hours digging with the safe mode to find the issue), ended up resetting. I had to stop using WSL, it was just BSOD over BSOD, i had 3 yesterday. I even got one while wget'ing some file on github. Before upgrading to the 14965, i was on the rtm, and i had 3 weeks of uptime, never got any problem.

So for me it looks more of an issue of this build than something else. I'll wait for the next one.

**Comment by fpqc** [comment]
@sywesk sounds like a driver problem.

**Comment by sywesk** [comment]
@fpqc do you know where to get the symbols for insider builds ? i can't find them.

**Comment by S3curityPlu5** [comment]
Most likely those symbols are private only to microsoft.  Sometimes microsoft release a new sdk that will align with newer insider builds, but the symbols I'm pretty sure can only be downloaded from msdl.microsoft.com/download/symbols

**Comment by fpqc** [comment]
@S3curityPlu5 Under certain agreements with MS, you can get more symbols (there is another private symbol server for that).  Not sure if it's an NDA wot's needed.

**Comment by bitcrazed** [comment]
@sywesk Could you let us know if this issue still affects you on Creators Update and/or Insiders? If not, please close, with our thanks for reporting.

**Comment by S3curityPlu5** [comment]
Just tried it on build 10563 and it now says "GOINSTALLBINARIES NOT AN EDITOR COMMAND"
