### ISSUE TITLE
unable to install pillow from openai's universe

### ISSUE THREAD

**Issue by hiteshvaidya** [Microsoft/WSL#1483]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I am trying to run openai's universe on WSL. But while installing the dependencies I faced an error. You may refer to its github repo, https://github.com/openai/universe

* Expected results
I don't know the expected results because I am running this for the first time.

* Actual results (with terminal output if applicable)
There were many packages installed. Among them was pillow. Following was the error in WSL which I got
Downloading/unpacking Pillow (from universe==0.20.4)
  Downloading Pillow-3.4.2.tar.gz (10.8MB): 7.8MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

Storing debug log for failure in /home/vaidyalabs/.pip/pip.log

* Your Windows build number
Windows 10 pro 1607 

* Steps / All commands required to reproduce the error from a brand new installation 
Following is the process given on universe's README. Since my WSL has ubuntu 14.04, I used corresponding commands,

Install Universe
To get started, first install universe:
git clone https://github.com/openai/universe.git
cd universe
pip install -e .

If this errors out, you may be missing some required packages. Here's the list of required packages we know about so far (please let us know if you had to install any others).

On Ubuntu 16.04:
pip install numpy
sudo apt-get install golang libjpeg-turbo8-dev make

On Ubuntu 14.04:
sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable  # for newer golang
sudo apt-get update
sudo apt-get install golang libjpeg-turbo8-dev make

* Strace of the failing command

* Required packages and commands to install
numpy
golang
golang libjpeg-turbo8-dev

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by hiteshvaidya** [comment]
Also how to give permissions to WSL username to read/write the home directory of WSL?

**Comment by aseering** [comment]
Hi again @hiteshvaidya -- I'm curious, if you retry this a few times, will it eventually work?

There are some known network bugs in the release that you are running, at least one of which ( #610 ) will sometimes cause network sends to hang, which would could cause an error message like the one that you are seeing.

We're told that Microsoft has the fix in-house and is working on releasing it as part of an [Insider build](https://insider.windows.com/).  In the meantime, all you can do is either retry the download, or download the file in Windows and access it from WSL and install it manually.

**Comment by aseering** [comment]
Regarding "the home directory of WSL" -- what directory are you referring to?  Do you mean the `/home/<username>/` directory in the Linux filesystem?  Your default WSL (Linux) user should automatically have full read/write/execute access to that directory.
