### ISSUE TITLE
how I can know if it has hanged out?

### ISSUE THREAD

**Issue by tyoc213** [Microsoft/WSL#1484]
I mean, I'm running `$ sudo apt-get install python-pip python-dev` but it has taked a lot of time... then when I click on the bash window to copy the command it started to run... so I dont know it was freezed, doing something or nothing at all untill I interacted with the terminal.

So, how I can know if something has hanged out or if it is "working" "slow but working"??? (even that I have ssd and a "good computer").

**Comment by benhillis** [comment]
Did you perhaps have the console selected?  The Windows console stops displaying output if you have
