### ISSUE TITLE
[bug] hdds mounted as a folder aren't accessible 

### ISSUE THREAD

**Issue by ioweb-gr** [Microsoft/WSL#1485]
Having a disk mounted at a folder point instead of using a drive letter makes the drive inaccessible. 
For example this disk

![image](https://cloud.githubusercontent.com/assets/20220341/21071991/057526ce-bebc-11e6-9427-5ca8b5ec1d66.png)

* Expected results
The disk should be accessible under /mnt/c/mnt/Backup/

* Actual results (with terminal output if applicable)
```bash
root@LUCIANO-PC:~# ls /mnt/c/mnt/Backup/
ls: cannot access '/mnt/c/mnt/Backup/': Input/output error
root@LUCIANO-PC:~# ls /mnt/c/mnt/
root@LUCIANO-PC:~#
```
![image](https://cloud.githubusercontent.com/assets/20220341/21072004/7b2179f4-bebc-11e6-9989-cb5cf35de937.png)

* Your Windows build number
14965

**Comment by fpqc** [comment]
Confirmed for 14986.

**Comment by tara-raj** [comment]
Please see our [blog post on drive mounting](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/)
