### ISSUE TITLE
[Question] How to remove Windows pathes from WSL PATH?

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/WSL#1493]
Is there any way to remove Windows pathes from my WSL PATH? Like some statement in some startup script or something.

**Comment by ddfznt** [comment]
```
echo "export PATH=`echo $PATH | tr ':' '\n' | grep -v /mnt/ | tr '\n' ':'`" >> ~/.bashrc
```

**Comment by fpqc** [comment]
There is also a registry key that just disables it entirely.

**Comment by benhillis** [comment]
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"AppendNtPath"=dword:00000000
```

**Comment by lilred** [comment]
That's a super interesting feature, I'm surprised at how little it's been advertised.

**Comment by MrCroft** [comment]
@benhillis I've just tried that registry key. It doesn't seem to be working anymore 😞. Closed/reopened _Bash on Ubuntu on Windows_ after adding the key and `echo $PATH` still spits out the same as before, a lot of `/mnt/c/Program Files/...`
Any change on that?
I've finally decided to give up WSL after struggling with it for so long, and installed Node on Windows to be able to work. Because it is impossible to work on some projects (depending on what packages/dependencies they have, I guess).

**Comment by MikeGitb** [comment]
Can we please have a fix for this issue (preferably one, that doesn't invole making changes to the registry)? I understand that interop might be useful for some people, but for me it just clutters up the PATH variable (and consequently auto complete in bash and leads to occasional issues when linux tools get confused. 

The way I see it, running windows binaries from inside Linux is the exception and not the rule, so I don't understand, why those paths get appended by default.

As a general comment: It would be nice to have a more extensive configuration tool in which I can set such things on a per distribution basis and which preferably has a gui to it.

**Comment by fpqc** [comment]
There is a solution now in wsl.conf.

**Comment by Brian-Perkins** [comment]
See [WSLENV](https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl) usage.

**Comment by TickleThePanda** [comment]
I've tried to look at the WSLENV usage or at `wsl.conf` but I'm struggling to understand what I need to do to remove these paths. Can somebody point me in the right direction, please?

**Comment by benhillis** [comment]
Manually setting your path in your bashrc is probably your best bet. I am working on a change now to add this option to wsl.conf.

**Comment by TickleThePanda** [comment]
I went with @ddfznt's override as it works well for me but it would be nice to see something elegant! :smile:

**Comment by yshterev** [comment]
If you use `root = /`

```
PATH=$(/usr/bin/printenv PATH | /usr/bin/perl -ne 'print join(":", grep { !/\/(c|d)\// } split(/:/));')
```

**Comment by ysc3839** [comment]
[WSL_DISTRIBUTION_FLAGS](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826872)
```
typedef enum _WSL_DISTRIBUTION_FLAGS { 
  WSL_DISTRIBUTION_FLAGS_NONE                   = 0,
  WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP         = 1,
  WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH         = 2,
  WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING  = 4
} WSL_DISTRIBUTION_FLAGS;
```
This flag is stored in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\Flags`. It's default value is 7.

**Comment by Biswa96** [comment]
There is another DWORD registry `InteropEnable`. Does that work on Store WSL apps? @benhillis

**Comment by benhillis** [comment]
We are not documenting the registry keys themselves, just the flags to the configure API. The keys are subject to change.

**Comment by ysc3839** [comment]
@benhillis Should add a command to change this flag in wslconfig.

**Comment by benhillis** [comment]
As I said above, I will be adding this flag to wsl.conf.

**Comment by Biswa96** [comment]
@Brian-Perkins Just a question, isn't WSL getting too dependent on WSL.conf file. Isn't it takes some time to open that file and parsing all the options?

**Comment by benhillis** [comment]
The amount of time parsing wsl.conf is negligible considering everything else that is done during a WSL instance "boot".

**Comment by m00head** [comment]
Fixed it by using a workaround taken from here: https://github.com/Microsoft/WSL/issues/1493#issuecomment-396299826

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\Flags`

Change `Flags` from `7` to `5` in order to exclude the `WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH` enum.

Now my path looks like this:
`PATH="/home/<user>/.local/bin:/home/<user>/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"`

**Comment by m00head** [comment]
@mkarpoff This only works with current Insider builds of Windows, not the stable release build.

**Comment by uriux-andrewd** [comment]
This works for me

1.  add base path to /etc/environment

cat /etc/environment (using the default path provided by a fresh install of Ubuntu bionic WSL)

`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"`


2. source /etc/environment at end of /etc/profile

`sudo bash -c "echo 'source /etc/environment' >> /etc/profile"`

Alternately, you can choose not to source the entire global environment and  just define path at the end of /etc/profile 

3. If you want to extend path in ~/.bash_profile do it the usual way:

nano ~/.bash_profile

`export PATH=/usr/testpath:$PATH`

**Comment by ericblade** [comment]
> ```
> echo "export PATH=`echo $PATH | tr ':' '\n' | grep -v /mnt/ | tr '\n' ':'`" >> ~/.bashrc
> ```

i would like to point out that @ddfznt solution is interesting because it gives a quick way to simply strip the relevant parts of path that may occasionally cause issues for some Linux tools.  Rather than outputting it to bashrc, you can just run it one-shot in a particular shell, before running a command that fails due to paths having spaces or parenthesis or whatever other special character in the Windows path is blowing up some misinformed shell script :)

**Comment by haselton** [comment]
Currently running version 1803 build 10.0.17134.523 and none of the registry options turn off appending the NT path.

Is there any way to turn this off for the current release build?

**Comment by benhillis** [comment]
@haselton - Version [17713](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/) has an option in wsl.conf, but for the version you are on, probably the easiest thing to do is to manually set up your path in your .bashrc file.

**Comment by CyrusNajmabadi** [comment]
@mkarpoff 

> @m00head The correct (through wsl configuration) is to edit the file `/etc/wsl.conf` in there put in the following line of code

```
appendWindowsPath=False
```

I've tried this, using the information here: https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/

My wsl.conf looks like this:

```
cyrusn@DESKTOP-3IRRNND ~> cat /etc/wsl.conf
[interop]
appendWindowsPath = false
cyrusn@DESKTOP-3IRRNND ~>
```

however, even after adding this, and relaunching wsl, i end up with a path that contains goop like this:

```
:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin
```

This ends up breaking several of our tools.  I'm currently on 1809.  Can you please advise?  Thanks!

**Comment by MrCroft** [comment]
@CyrusNajmabadi @mkarpoff even if that would work, that's not a solution. We only need to exclude node/npm stuff, not everything.
We still need commands like "code ." (launch VSCode) to work. And I believe that wouldn't work anymore, if we'd drop the entire Windows path, right?

**Comment by m00head** [comment]
> My wsl.conf looks like this:
> 
> ```
> cyrusn@DESKTOP-3IRRNND ~> cat /etc/wsl.conf
> [interop]
> appendWindowsPath = false
> cyrusn@DESKTOP-3IRRNND ~>
> ```
> however, even after adding this, and relaunching wsl, i end up with a path that contains goop like this:
> 
> ```
> :/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin
> ```
> This ends up breaking several of our tools. I'm currently on 1809. Can you please advise? Thanks!

@CyrusNajmabadi The behavior you are describing matches the `Section: automount` under `Configuration Options` here:
https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/

Therefore, you also need to add the following lines to your `wsl.conf` file:
```
[automount]
enabled = false
mountFsTab = false
```

> **Key:** enabled **Default:** true
> Setting to true causes your fixed drives (i.e C:/ or D:/) to be automatically mounted with DrvFs under “/mnt”. Setting to false means they won’t be mounted automatically—but you could still mount them manually or via fstab.

> **Key:** mountFsTab **Default:** true 
> Setting to true causes the file /etc/fstab to be processed on WSL start. /etc/fstab is a file where you can declare other filesystems, like an SMB share. Thus, you can mount these filesystems automatically in WSL on start up.

**Comment by benhillis** [comment]
@MrCroft - It seems like you want some fine granularity over your $PATH variable.  The best support for that would be to set up your path the way you want it in your .bashrc file which is processed after anything WSL does to the path.

**Comment by m00head** [comment]
@CyrusNajmabadi https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

> ## File systems in WSL
> ### DrvFs
> To facilitate interoperability with Windows, WSL uses the DrvFs file system. WSL automatically mounts all fixed drives with supported file systems under /mnt, such as /mnt/c, /mnt/d, etc. Currently, only NTFS and ReFS volumes are supported.

**Comment by CyrusNajmabadi** [comment]
@MostafaOkasha 

> @CyrusNajmabadi The behavior you are describing matches Section: automount under Configuration Options here:

Unfortunately, i even see other windows $PATH entries with spaces placed in my bash path.  

> @CyrusNajmabadi @mkarpoff even if that would work, that's not a solution. We only need to exclude node/npm stuff, not everything.

I just don't want path entries added.  I set `appendWindowsPath` to false, and it's simply not working.

**Comment by skalinets** [comment]
I just added export PATH="$PATH:/usr/bin" to the end of `~/.bashrc`, so that `usr/bin` takes precedence over windows' apps.

**Comment by CyrusNajmabadi** [comment]
@MostafaOkasha I think there's a disconnect here:

1. i *do* want drives mounted.  I make use of this heavily.
2. i do *not* want windows PATH entries added to the environment.  Not only does it not help me with anything, but it actively breaks thigns on our end as the spaces you insert in the path break many tools that do not expect spaces there.

**Comment by m00head** [comment]
> I just don't want path entries added. I set `appendWindowsPath` to false, and it's simply not working.

You need to restart the WSL console window for it to pick up the new setting in `wsl.conf` - better still reboot your computer or restart your virtual machine.

Using Registry Editor, navigate to the following key:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\Flags`

 What is the `WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH` value set to, assuming it is present?

Have you tried the registry workaround I posted here? https://github.com/Microsoft/WSL/issues/1493#issuecomment-417639271

> This ends up breaking several of our tools. I'm currently on 1809. Can you please advise? Thanks!

Which OS build version of Windows 10 1809 are you on? e.g. `17763.316`
**Which Windows operating system am I running?** - Windows Help
https://support.microsoft.com/en-gb/help/13443/windows-which-operating-system

**Comment by CyrusNajmabadi** [comment]
> You need to restart the WSL console window for it to pick up the new setting in wsl.conf - 

Done.  It didn't help.

> better still reboot your computer or restart your virtual machine.

Didn't help.

These are the only values set:

![image](https://user-images.githubusercontent.com/4564579/54064105-3a5cc880-41c6-11e9-87ec-3e6f9061b146.png)

>Have you tried the registry workaround I posted here previously? #1493 (comment)

I have not.  SHouldn't wsl.conf work here?

> Which OS build version

I'm on this:

![image](https://user-images.githubusercontent.com/4564579/54064113-56f90080-41c6-11e9-8c91-477d78432b5f.png)

**Comment by m00head** [comment]
@CyrusNajmabadi 

> > Have you tried the registry workaround I posted here previously? #1493 (comment)
> 
> I have not. Shouldn't wsl.conf work here?

Setting `appendWindowsPath` to false in your `wsl.conf` file doesn't seem to be working for you - the `Flags` registry value should be changed from `7` to `5` as a result.

This may be because the location of your `wsl.conf` file is not correct, or the file is corrupt.

You should NOT edit this file from Windows because this will [cause it to become corrupted](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/):
`C:\Users\<USERNAME>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuOnWindows\LocalState\rootfs\etc\wsl.conf` (see #1662 and #3536)

Instead, edit the file from within the WSL console window using `nano` or `vi`:
`/etc/wsl.conf`

Otherwise, try changing it manually from `7` to `5`, then restart the WSL console window.

**Comment by maxsu** [comment]
What's the status on wsl.conf for (not-insider) Build 17134 and friends?

I am by all means updating to insider build, as this seems like part of WSL best practices for now. But it would be nice for a more out of box experience (for clueless users such as your truly.)

_Side note: For those arriving from [this Stack/Exchange post](https://askubuntu.com/questions/1066100/is-path-in-wsl-supposed-to-be-very-long) looking for a registry hack - setting `appendWindowsPath` in `wsl.conf` is the cleaner solution._

_Looks like the wsl docs' [Distro Management Section](https://docs.microsoft.com/en-us/windows/wsl/wsl-config) should have been my go-to. The docs are clean + well written, and mention Insider Build, `wsl.conf` and `appendWindowsPath`._

**Comment by ChinouneMehdi** [comment]
After configuring ```wsl.conf``` 
```
[Interop]
appendWindowsPath = False
```
don't forget to open Powershell and put this command:
```SHELL
Restart-Service LxssManager
```

**Comment by SaeedShariati** [comment]
I just installed wsl2 and now the flag's value is 15 not 7. what should I do?

**Comment by benhillis** [comment]
@SaeedShariati - use the /etc/wsl.conf method. The registry key method is unsupported.

**Comment by santiagoluz** [comment]
> don't forget to open Powershell and put this command:
> 
> ```shell
> Restart-Service LxssManager
> ```

Thanks @ChinouneMehdi 

Note that you need to execute PowerShell as Administrator in order to be able to restart this service.

**Comment by airtonix** [comment]
changed the registry key because the wl.conf didn't work....


now the distribution is gone. so is the registry entry.

**Comment by airtonix** [comment]
> @CyrusNajmabadi
> 
> > > Have you tried the registry workaround I posted here previously? #1493 (comment)
> > 
> > 
> > I have not. Shouldn't wsl.conf work here?
> 
> Setting `appendWindowsPath` to false in your `wsl.conf` file doesn't seem to be working for you - the `Flags` registry value should be changed from `7` to `5` as a result.
> 
> This may be because the location of your `wsl.conf` file is not correct, or the file is corrupt.
> 
> You should NOT edit this file from Windows because this will [cause it to become corrupted](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) (see #1662 and #3536)
> 
> Instead, edit the file from within the WSL console window using `nano` or `vi`:
> `/etc/wsl.conf`
> 
> Otherwise, try changing it manually from `7` to `5`, then restart the WSL console window.

only do this if you want all your stuff deleted.

**Comment by adamralph** [comment]
Has the method to do this been documented anywhere?

**Comment by syleishere** [comment]
in .bash_profile add:
alias wsl='/mnt/c/Windows/System32/wsl.exe'

then to restart it simple as:
wsl --shutdown

(then just reconnect)

**Comment by adamralph** [comment]
> Has the method to do this been documented anywhere?

I guess the answer is no.

**Comment by syleishere** [comment]
echo 'appendWindowsPath=False' > /etc/wls.conf
/mnt/c/Windows/System32/wsl.exe --shutdown

**Comment by Aschay** [comment]
This happened to me after installing nvm ! Please document the right answer

**Comment by iuliandita** [comment]
I just changed the Flags in the registry and my Ubuntu WSL is completely gone. Reset.

I got this message:
![image](https://user-images.githubusercontent.com/4585657/125179007-84b54080-e1ea-11eb-9447-9de91e831721.png)

The VHDX file with the disk drive has been completely erased. The folder C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState is empty.

I think I am going to pass out...
All my files are gone. All the code was committed, but my notes and my dotfiles are gone, all the hours spent setting up the environment, wasted... WT actual F??

The initial flag value was 15. I did test it out again, after setting up a new ubuntu wsl, and the same thing happened.

**Comment by liudonghua123** [comment]
> After configuring `wsl.conf`
> 
> ```
> [Interop]
> appendWindowsPath = False
> ```
> 
> don't forget to open Powershell (as administrator) and put this command:
> 
> ```shell
> Restart-Service LxssManager
> ```
> 
> Windows-10 1809

I use `wsl --terminate distribution-name`(eg `wsl --terminate kali-linux`) instead of `Restart-Service LxssManager`
