### ISSUE TITLE
How to change /etc/hosts?

### ISSUE THREAD

**Issue by andyj513** [Microsoft/WSL#1495]
The top of the /etc/hosts file says:
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.

Can I modify the process to add my own things (without turning off the automatic generation)?  Is there a way to get it to pick up my Windows Hosts file (C:\Windows\System32\Drivers\Etc\HOSTS)?

**Comment by benhillis** [comment]
Not currently. We have a task on our backlog to automatically generate this file with the content of the Windows hosts file.

**Comment by therealkenc** [comment]
Bonus points if you _overlay_ it with the Windows hosts file. Or symlink `/etc/hosts` to `/proc/win/hosts`.

**Comment by jazoom** [comment]
I removed that top line and the file was regenerated. Fresh install of Creator's Update. Are we still going to get the windows hosts file overlaid on /etc/hosts? I keep having to re-add these lines to /etc/hosts.

**Comment by benhillis** [comment]
@jazoom - this functionality was added in Insider build 16184.

**Comment by jazoom** [comment]
If the functionality doesn't exist in my build why does that comment exist in my build?

**Comment by benhillis** [comment]
Which comment do you mean?

**Comment by jazoom** [comment]
#This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.

**Comment by jazoom** [comment]
Sorry, I mixed up 2 issues. When I remove that line it still auto-generates.

**Comment by treysis** [comment]
Is there now an option to add information to /etc/hosts and also including the Windows hosts file, i.e. to edit the template or something like this?
