### ISSUE TITLE
Editing keystrokes don't work correctly

### ISSUE THREAD

**Issue by michaelveloz** [Microsoft/WSL#1497]
I often use Ctrl-R (followed by some number of keystrokes) to find and replay previously entered commands. This does not work correctly with BOW.  The cursor placement is wrong, old characters are left displayed under new ones, etc.

Also, "editing" keystrokes such as insert and backspace do not work in all cases. For example, if I use the Up Array to re-display the last command, neither the backspace nor the insert key work correctly to let me edit that command

I would tell you my Build Number, but the Windows 10 Settings app keeps crashing :) so I can't find out what it is.

**Comment by fpqc** [comment]
run winver.exe....

**Comment by zadjii-msft** [comment]
@michaelveloz any way I can get a video of all the behavior you're describing? It sounds like a multitude of issues which I've heard of, but I think a lot of them have also already been resolved. It's hard to know for sure. 

Any chance that this behavior repros for you on a fresh console launch? There's a know issue with `apt` right now that can corrupt a conhost WSL window. That could be the cause of a lot of this.

**Comment by lilred** [comment]
To add: [ShareX](https://getsharex.com/) is a great tool for recording video and screen captures. I used it to record [this video](https://www.youtube.com/watch?v=eDd9A8YJCH8) for issue #1307.
