### ISSUE TITLE
Unable to launch Sublime Text 3 on WSL

### ISSUE THREAD

**Issue by azuryel** [Microsoft/WSL#1499]
hello everyone, 

Today i got a problem, when i tried to install sublime text on WLS, I got an error by this command 

```
`sudo add-apt-repository ppa:webupd8team/sublime-text-3`
`sudo apt-get update`
`sudo apt-get install sublime-text-installer`
```

and I got in first this 

`Unable to load libgdk-x11-2.0.so` and some other basic libraries for GUI support 

so I did this : 

`sudo apt-get install -y xbase-clients libgtk2.0-0 libgdk-pixbuf2.0-0 libfontconfig1 libxrender1 libx11-6 libglib2.0-0  libxft2 libfreetype6 libc6 zlib1g libpng12-0 libstdc++6-4.8-dbg-arm64-cross libgcc1`

and this 

`ln -s /opt/sublime_text/sublime_text /usr/local/bin/sublime_text`

but now, when I do 

`sublime_text myfile.rb` or just `subl myfile.rb` nothing's going on, no error returned the sublime window doesn't pop 

thank :)

**Comment by fpqc** [comment]
You need a Windows xorg server and to tell sublime to display on it...

**Comment by azuryel** [comment]
oh yes, true that working well thank for the fast answering !

**Comment by lilred** [comment]
To add: graphical applications are not officially supported by WSL. Some stuff may not work, and some stuff that currently works might break in future updates.

**Comment by mbuguaWanjiku** [comment]
just to add on shoulf finally run (DISPLAY=:0 /opt/sublime_text/sublime_text)  instead of(ln -s /opt/sublime_text/sublime_text /usr/local/bin/sublime_text). worked for me

**Comment by clumsymass64** [comment]
Sorry for opening this issue again, how to do the thing with the Windows xorg server?

**Comment by DarthSpock** [comment]
See #637
