### ISSUE TITLE
When pressing a button before Emacs finishes loading, a letter appears

### ISSUE THREAD

**Issue by ArchKevin22** [Microsoft/WSL#1505]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
When using Emacs (the nox version at least), pressing the arrow key during the loading sequence
makes a letter added where it shouldn't be. This causes many headaches when trying to
find compilation errors. Not sure if bug on Bash on Windows or on Emacs.

* Expected results
Pressing the arrow keys should not have letters added.

* Actual results (with terminal output if applicable)
Pressing an arrow key makes a letter appear. For example, the down key appends 'B' to the beginning
of the file.

* Your Windows build number
14393.479

* Steps / All commands required to reproduce the error from a brand new installation 
1. Open a file in Emacs
2. While it's loading, press an arrow key

* Strace of the failing command
n/a

* Required packages and commands to install
emacs24-nox
"emacs (anything.txt)" to open a file

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by zadjii-msft** [comment]
@ArchKevin22 If I'm not mistaken, is this not the same behavior you'd normally get in emacs on pure Ubuntu?

![screenshot 10](https://cloud.githubusercontent.com/assets/18356694/21272299/751e05d4-c373-11e6-827c-8ff5d92b8640.png)

That's what I got by spamming the right arrow on loading emacs. Which is pretty similar to what I got with my WSL emacs (albeit, with more escape sequences on Ubuntu).

**Comment by ArchKevin22** [comment]
Yeah that looks like what I'm talking about (if the 'C' wasn't already there)
Here is a picture that makes the bug more obvious (I think it appears when pressing before vc-git is loaded?).
![bug](https://cloud.githubusercontent.com/assets/19791612/21275168/5a503238-c380-11e6-965a-bbf3b7ad7416.jpg)

Who would I take this bug report to if it's not a bug with WSL? I have a very difficult time reproducing the bug on the Mac, so it leads me to believe that it's not a problem on the Mac version.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
