### ISSUE TITLE
Not working Apache VirtualHost after reboot?

### ISSUE THREAD

**Issue by stasionok** [Microsoft/WSL#1510]
Windows Build: 14965

I have installed:
1. clear Windows10 InsiderPreview build 14965
2. setup apache+mysql+php7.0
3. configure few VirtualHosts on it (as example work.loc and oc.loc)
4. replace /var/www with ln -s /mnt/c/www /var/www
5. Add record to /etc/hosts and hosts file on windows

And all works fine, just before i have rebooted computer.
After reboot:
- I can access to http://localhost php file
- I can NOT open any VirtualHost domain. I got just white screen without any errors in apache logs.

I spent all day to try different builds and to try fix issue and without results.

**Comment by stasionok** [comment]
Add: if i send computer to sleep mode and wake it up, VirtualHosts start working fine.
So, i turn computer ON. Wait for loading system, open bash. Start apache2 and mysql services.
After that send computer to sleep. Wake it up. And all work fine.

**Comment by aseering** [comment]
Well, that's new...  Hopefully someone else here will have some ideas?

Could you verify that your `/etc/hosts` file (specifically on the Linux side) is the same after you reboot?  I know that WSL has some logic at startup that tries to manage that file.

If that's not it, can you try to narrow this down a bit?  For example, does this only happen if you link `/var/www` into Windows drvfs or does it still happen if that path is a normal directory?  Do you need the full LAMP stack or does it happen if you're just serving flat files to multiple vhosts from Apache?

**Comment by stasionok** [comment]
You right, /etc/hosts clean without my lines.
And i tried reboot with native /var/www folder and VirtualHosts and have same behavior - need sleep and wake up.
