### ISSUE TITLE
disowned XTerm process should remain running when 1st bash exits

### ISSUE THREAD

**Issue by jamesdavidhoward** [Microsoft/WSL#1511]
After starting a process from the 1st (& only) running `bash` shell, I can use the `disown` built-in shell command to (supposedly) divorce the 2nd process from the 1st and make it immune from the termination of the 1st `bash` process.  (This works OK on "real" Linux.)  However, it appears that in WSL, that the whole subsystem is terminated when this 1st `bash` shell is killed (as by `exit`).

I understand that there is arguably little reason to continue the life of the WSL subsystem after the _very last_ Linux process has `exit`ed.  However, any started, then `disown`ed, process is _still_ a working, valid Linux process.  (In this case, it was `xterm`, talking to a local Windows-native X11 Server, and displaying on-screen as a command line window - itself running its own `bash` shell.)  When the `bash` shell running in a WSL console command-line window `exit`s, it **_should not_** take the `xterm` with it!

The still-running `xterm` should be enough to keep the WSL subsystem aware it is needed, and to be kept running, supporting the `xterm` (and any other processes that have been started).

**Comment by fpqc** [comment]
This is how the system works right now by design, although they have fixes on the backlog. The workaround is using something called run.exe (search the issues page).  Please close.

**Comment by jamesdavidhoward** [comment]
That is not my understanding; the lifetime of the Linux-supporting WSL subsystem was supposed to run as long as there were running Linux processes.  (The issue of starting daemons or other services, without 1st invoking a `bash` shell is a different thing.  That daemon/services issue is what I understood to be **Backlog**ged.)

**Comment by fpqc** [comment]
Nope, you need to have at least one Linux process attached with active io handles to at least one Windows console.

**Comment by aseering** [comment]
@jamesdavidhoward -- my understanding matches that of @fpqc .

There's a UserVoice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13301121-let-bash-continue-running-even-when-the-terminal-h) requesting the behavior that you are assuming, as well as proposing some workarounds.

**Comment by Efreak** [comment]
A shortcut to the .vbs file below with the command you want to run (I suggest a shortcut to `wscript.exe script.vbs bash -c 'sleep Infinity'`) as an argument will run the command prompt hidden.

```CreateObject("Wscript.Shell").Run """" & WScript.Arguments(0) & """", 0, False```

Alternatively, you can use either [cerebrate/wabash](https://github.com/cerebrate/wabash), the [run.exe](http://www.straightrunning.com/XmingNotes/#head-148) mentioned by @fpqc, or something like my [startwsl.vbs](https://gist.github.com/Efreak/50f18b896426ad958efbaa0e058cb3f7). Any of these will give you a persistent session, which will allow you to run processes in the background, though I recommend a vbs script as it's a single-file that's easier to modify and copy to other computers.

**Comment by fpqc** [comment]
@Efreak If you're on 14986, you can do your session as opening tmux maximized (not suggested on earlier builds due to pty bugs).

**Comment by Brian-Perkins** [comment]
Windows Insider Build 17046 allows programs to execute without an active terminal.
