### ISSUE TITLE
tcpflow does not work in bash

### ISSUE THREAD

**Issue by xplicit** [microsoft/WSL#1515]
* A brief description

While `ifconfig` was fixed in latest insider preview, `tcpflow` still does not work. Trying to run `sudo tcpflow -i lo port 20000` shows error:
tcpflow: lo: socket: Invalid argument

* Expected results
it should start to listen tcp traffic on port 20000

* Actual results (with terminal output if applicable)
tcpflow: lo: socket: Invalid argument

* Your Windows build number
version 1607 build 14986.1000

* Steps / All commands required to reproduce the error from a brand new installation 
Run bash as administrator, then type:
`sudo tcpflow -i lo port 20000`

* Strace of the failing command

```
socket(PF_PACKET, SOCK_RAW, 768)        = -1 EAFNOSUPPORT (Address family not supported by protocol)
socket(PF_INET, SOCK_PACKET, 0x300 /* IPPROTO_??? */) = -1 EINVAL (Invalid argument)
write(2, "tcpflow: ", 9tcpflow: )                = 9
write(2, "lo: socket: Invalid argument", 28lo: socket: Invalid argument) = 28
write(2, "\n", 1
```

* Required packages and commands to install
`tcpflow`

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Does it work on the non-loopback ifaces?

**Comment by xplicit** [comment]
@fpqc it does not work on all interfaces (I tried `sudo tcpflow -i eth1 port 20000` and `sudo tcpflow -i any port 20000`)

**Comment by aseering** [comment]
This sounds related to @JasonLinMS 's final comment on #1451 , regarding `SOCK_RAW` support.

**Comment by JasonLinMS** [comment]
@sunilmut Yeah, unfortunately, we don't support `SOCK_PACKET` yet either.

**Comment by sgf** [comment]
Why ppl like Linux because Linux has fewer restrictions, people can do more what they want to do.
Please don't bring the limit from windows to the WSL.if only can do the windows can do,why we should be use WSL?

Soo,when could be the problem soloved?

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar

that has 1426 votes now ?
how many votes need ?

**Comment by hackdefendr** [comment]
More than a year later and still no progress?  Seriously, what is it going to take to prioritize supporting AF_PACKET and RAW SOCKETS.

**Comment by therealkenc** [comment]
Dunno. I do know what it is [going to take](https://github.com/Microsoft/WSL/issues/1349#issuecomment-405705133) to dupe this into #1349 though.

**Comment by Blizzardo1** [comment]
Is there any update to this issue? I'm unable to run any network related programs other than ping or curl really...

**Comment by nubix** [comment]
Is there still no fix for the missing compatibility with AF_SOCKET etc.?

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/87027700-68736380-c192-11ea-9569-69fd25c14bd3.png)

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/88902792-866b3b80-d207-11ea-92ad-20ae0f4a0a8c.png)

**Comment by xplicit** [comment]
Just a note: for me the reason of trying to use tcpflow in WSL was the ability to launch server in windows and use tcpflow to capture traffic from windows. Unfortunately in WSL2 it's still impossible.
