### ISSUE TITLE
Cannot launch Win32 executable stored in VolFS

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/WSL#1516]
Windows executables stored in VolFS folders do not run (via interop) when executed from a WSL shell, instead erroring out with exit code 1. See attached screenshot.

![image](https://cloud.githubusercontent.com/assets/371623/21290297/9e8140c8-c47a-11e6-998b-6bd57f4d70bc.png)

* Expected results

Executable should... execute.

* Your Windows build number

14965

* Steps / All commands required to reproduce the error from a brand new installation 

1. cp any Windows executable file into an arbitrary VolFS folder.
2. Run it.

While an odd use case, incidentally, this case is relevant to me because I'm putting together helper utilities which operate across the Windows/WSL border, and it would be much cleaner if the [minimal] Win32 helper executables could be included in the same apt package as the Linux executables/scripts that call on them, rather than requiring a separate installation on the Win32 side and a config file to identify their location.

**Comment by therealkenc** [comment]
I noticed this too but didn't post because I didn't know whether that was considered a "feature" or not. Hit it when cross compiling a PE binary on WSL. I'm curious about the intent here also.

**Comment by benhillis** [comment]
This was by design. Since Win32 apps creating or modifying files inside of VolFs causes issues with the alternate data stream of the files. I see this as a symptom of that issue, and when we come up with a better solution for Win32 apps modifying files in VolFs this can be changed.

**Comment by cerebrate** [comment]
Hm. Not sure an .exe stored in VolFS would be any more likely to than running an exe from DrvFS with a VolFS pwd, say, but I guess I can see that.

Guess I'll need to find a different workaround. :(

**Comment by therealkenc** [comment]
Working on it. 😉

**Comment by fpqc** [comment]
@benhillis When I ran the powershell cmdlet

`Get-Item %localappdata%\lxss\home\fpqc\lol.file -Stream *`

command, I didn't see any alternate data streams.  According to the docs, there should be a stream of extended attributes (type `$EA`) where these should live, but I couldn't see them.

**Comment by benhillis** [comment]
@cerebrate - I disagree. Programs that write or modify files in the current working directory is a *very* common pattern. For example a compiler. Using a Win32 compiler from VolFs would result in output files that were not visible from within WSL.

**Comment by cerebrate** [comment]
@benhillis - Yeah, I understand that, but why doesn't the same argument apply in equal force to all the Win32 executables, say csc.exe, that are on my PATH and that Win32 interop is more than happy to execute with a VolFS current working directory?

Addendum: Okay, so on checking, I note that while Win32 executables on DrvFS seem to inherit the WSL cwd only if it's in DrvFS, and if it's in VolFS get a cwd on DrvFS instead - looks like the executable's directory from the limited sample I've tested - presumably as a safeguard against exactly this. In which case, how about assigning Win32 executables stored in VolFS an arbitrary DrvFS cwd when invoked (from an inside-VolFS pwd), say the user's temp folder or the root?

That'd cover the trivial (non-file modifying) case just fine, and in the other cases, it's not going to generate any file-not-found errors that its DrvFS-stored counterpart wouldn't have anyway.

**Comment by fpqc** [comment]
Cerebrate, yeah, it works very very very similarly how Xilun's project works.  It sets the working directory to your %userprofile% if a Windows program is launched while your PWD is in volfs.

**Comment by benhillis** [comment]
@fpqc - It actually inherits the CWD from bash.exe (whatever directory bash.exe was launched out of).

**Comment by fpqc** [comment]
Even better!

**Comment by tara-raj** [comment]
Closing as this conversation is stale. If you would like to request this as a feature please add this ask to [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l)
