### ISSUE TITLE
vagrant can be used, but not vagrant ssh

### ISSUE THREAD

**Issue by const-g** [Microsoft/WSL#1518]
Hi, with latest build (14986) I can finally use vagrant from wsl. Great job thanks!

It works well for `vagrant.exe up`, `vagrant.exe reload`, `vagrant.exe halt`, but not for `vagrant.exe ssh`

The terminal does ... nothing. I waited for a few minutes to be sure, for nothing.

here is the output of `vagrant.exe ssh-config` if it can help:

```
$ vagrant.exe ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile [EDITED]/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**Comment by Cog-g** [comment]
Hi,are you sure you use the latest insider preview build?

**Comment by krzysztofantczak** [comment]
Hey,

Version 1607 (OS Build 14986.1001)

**Comment by const-g** [comment]
> is this also the case with Your setup?
Hi yes it is

**Comment by tara-raj** [comment]
Closing this issue for now. Please re-open if you hit this issue in a more recent Insiders build. Thanks!
