### ISSUE TITLE
Failed to run pip3 command

### ISSUE THREAD

**Issue by kozo2** [Microsoft/WSL#1519]
* A brief description

Sometimes pip command fails, sometimes does not fail in WSL.
Troublingly this does not always happen...

```
~# pip3 install -U pip
python3: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
```

* Expected results

No core dump

* Actual results (with terminal output if applicable)

```
~# pip3 install -U pip
python3: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
```

* My Windows build number

14986.1000

* Steps / All commands required to reproduce the error from a brand new installation 

```
sudo su
apt update
apt install python3 wget
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip3 install -U pip
```

* Strace of the failing command

https://gist.github.com/kozo2/5dcb761b828998d4562cba4af8e56ef6

* Required packages and commands to install

python3 and pip
```
sudo su
apt install python3 wget
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
```

**Comment by kozo2** [comment]
It seems that this can by occasionally fixed by reboot.

**Comment by coffeetocode** [comment]
I'm seeing repro as well, exact same error and file/line, this time related to apt-get, not pip. Likewise inconsistent. Will fail to work, but can then start working.

```
patrickt@DESKTOP-3F5IQKD:~$ sudo apt-get update
[sudo] password for patrickt:
0% [Working]http: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Reading package lists... Done
E: Method http has died unexpectedly!
E: Sub-process http received signal 6.
```

One other observation: Once it starts working, the error does not appear to recur for a while (haven't found a good bound on this time). Eg, if run in a loop, once the command succeeds it will reliably succeed after.

**Comment by kozo2** [comment]
This error also occured with
```
knishida@DESKTOP-ETL8RDS ~/ipynb> nb --no-browser --ip='*'
[W 15:02:36.278 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
python3: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
knishida@DESKTOP-ETL8RDS ~/ipynb>
```

**Comment by garyng** [comment]
Disabling IPv6 as mentioned in #2142 works.

**Comment by therealkenc** [comment]
#508 is one of the earlier cites
