### ISSUE TITLE
Super User's Password Must Be Inserted Multiple Times In a Row (sudo) via Phing build.xml Target

### ISSUE THREAD

**Issue by jepster** [Microsoft/WSL#1525]
* A brief description
If I execute sudo-commands via Phing, which is a build-tool, that runs bash commands via a XML file config, I need to insert the sudo user's password each time a sudo-command is being executed. If a "build target" is requiring 3 sudo-commands, I need to insert the sudo user's password 3 times. This is annoying and is not the case on Linux outside of the WSL. I use Phing on multiple machines and only the WSL has this issue.

Phing is a popular build-tool in the PHP community. Like Ant in the Java community.

* Expected results
After I have inserted the sudo user's password once, I do not need to insert it again for a certain time (e.g. 15 minutes). Like it works if I combine multiple sudo commands like this:

> sudo service mysql restart && sudo service mysql stop && sudo service apache2 start

* Actual results (with terminal output if applicable)

See the terminal output, where I am asked three times for the sudo user's password:

> peter@DESKTOP-UNMGSSF:/mnt/c/Users/peter/Dev/pbt-d8/modules/permissions_by_term$ phing -f ~/build.xml disApacheRemoteXdebug
> Buildfile: /home/peter/build.xml
> 
> DevOps > disApacheRemoteXdebug:
> 
>      [echo] Disabling Xdebug for Apache.
> [sudo] password for peter:
> [sudo] password for peter:
> [sudo] password for peter:
>  * Restarting web server apache2
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
> [Tue Dec 20 22:16:44.443975 2016] [core:warn] [pid 2490] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
>    ...done.
> 
> BUILD FINISHED
> 
> Total time: 9.2979 seconds
> 
> peter@DESKTOP-UNMGSSF:/mnt/c/Users/peter/Dev/pbt-d8/modules/permissions_by_term$

* Your Windows build number

14393.576

* Steps / All commands required to reproduce the error from a brand new installation 

1. Install Phing (https://www.phing.info/ -  a popular tool in the PHP developer community)
2. Setup a build.xml file with several sudo user commands inside a build-target and execute it
3. You will be asked each time for your password.

* Required packages and commands to install

- Install PHP CLI (sudo apt install php5-cli) 
- and the Apache webserver (sudo apt install apache2) 
- Download Phing by "wget http://www.phing.info/get/phing-latest.phar"
- create a build.xml file with this content:

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="DevOps" default="" basedir="/">

    <property name="php_apache_conf_dir" value="/etc/php5/apache2"/>
    <property name="php_cli_conf_dir" value="/etc/php5/cli"/>

    <target name="disApacheRemoteXdebug">
        <echo msg="Disabling Xdebug for Apache." />
        <exec command="sudo sed -i '/xdebug.remote_autostart=true/c\xdebug.remote_autostart=false' ${php_apache_conf_dir}/php.ini"
              passthru="true"
              checkreturn="true" />
        <exec command="sudo sed -i '/xdebug.remote_enable=true/c\xdebug.remote_enable=false' ${php_apache_conf_dir}/php.ini"
              passthru="true"
              checkreturn="true" />
        <exec command="sudo service apache2 restart"
              passthru="true"
              checkreturn="true" />
    </target>
</sudo>
```

- Then run 
> php phing-latest.phar -f ~/build.xml disApacheRemoteXdebug

-> You will be asked 3 times for the sudo user's password.

**Screencast**
I have created a screencast of this faulty behavior here: https://drive.google.com/file/d/0B5vmNAcUsVUgYTNuY1RRdlh5WUE/view

**Comment by fpqc** [comment]
You went to a great deal of trouble submitting this report. Did you try on the latest insider build?

**Comment by jepster** [comment]
Thanks for your quick reply. No, I have not checked the insider build yet.

fpqc <notifications@github.com> schrieb am Di., 20. Dez. 2016 23:11:

**Comment by fpqc** [comment]
The reason I mention it is that there was a fix involving sudo in 145xx (first round of RS2 insider builds).  Sometimes an insider will pop in and test for you, but for something with some setup like this, your best bet is to test yourself. You could spin up a VM with a fast-ring build if you are reluctant to run it on your bare metal system

**Comment by rodrymbo** [comment]
I suppose a workaround would be to create entries in sudoers for those commands with the NOPASSWD: option. Or check the sudoers file to make sure the `timestamp_timeout` option hasn't been tweaked. Or perhaps try setting it?

I'm not saying this isn't an issue to be reported, just noting how one could get work done without being annoyed. ;)

**Comment by jepster** [comment]
Thanks for your hints. Funny that you have interpreted, that I have been annoyed. You've been right. ;)

My answers on your hints:

## Try Windows 10 insider build
-> Here I have two problems: 
1. I have no second Windows 10 license to try it in a VM. 
2. As a full-time employee I have not enough time to setup my entire system in the VM to try there something.

## NOPASSWD option in sudoers file
-> That would be quite a few options there, since I have variables. There would not be mush typing saved, compared to the way I describe below.

## timestamp_timeout
-> I have tried to set it. It did not worked.

# What was now my solution or more precise "workaround"?
I have moved the commands from my Phing PHP build-tool into bash-functions.

Firstly I am sourcing (including) a file in my **.bashrc** file. Since this is the file which is sourced in WSL when I log in into the Bash (not .bash_profile). To be in the namespace of the proper context, I have named the file ".bashrc_xdebug_shortcuts". This is the 1 line added into the .bashrc file:

`source ~/.bashrc_xdebug_shortcuts`

Then I have defined a few Bash variables and shortcuts for my comfort. This are the contents of the .bashrc_xdebug_shortcuts file:

```
alias axd=disApacheRemoteXdebug
alias cxd=disCliRemoteXdebug
alias cxe=enCliRemoteXdebug

function disApacheRemoteXdebug {
  echo 'Disabling Xdebug for Apache.'
  sudo sed -i '/xdebug.remote_autostart=true/c\xdebug.remote_autostart=false' ${php_apache_conf_dir}/php.ini
  sudo sed -i '/xdebug.remote_enable=true/c\xdebug.remote_enable=false' ${php_apache_conf_dir}/php.ini
  sudo service apache2 restart
}

function enApacheRemoteXdebug {
  echo 'Enabling Xdebug for Apache.'
  sudo sed -i '/xdebug.remote_autostart=false/c\xdebug.remote_autostart=true' ${php_apache_conf_dir}/php.ini
  sudo sed -i '/xdebug.remote_enable=false/c\xdebug.remote_enable=true' ${php_apache_conf_dir}/php.ini
  sudo service apache2 restart
}

function disCliRemoteXdebug {
  echo 'Disabling Xdebug for CLI.'
  sudo sed -i '/xdebug.remote_autostart=true/c\xdebug.remote_autostart=false' ${php_cli_conf_dir}/php.ini
  sudo sed -i '/xdebug.remote_enable=true/c\xdebug.remote_enable=false' ${php_cli_conf_dir}/php.ini
}

function enCliRemoteXdebug {
  echo 'Enabling Xdebug for CLI.'
  sudo sed -i '/xdebug.remote_autostart=false/c\xdebug.remote_autostart=true' ${php_cli_conf_dir}/php.ini
  sudo sed -i '/xdebug.remote_enable=false/c\xdebug.remote_enable=true' ${php_cli_conf_dir}/php.ini
}
```

Now I am able to execute the commands which I have executed by Phing before. So I simply do not need Phing anymore and I do not need to insert a password for every command which is being executed via sudo.

It would be nice, if someone stumbles upon my post and finds it somehow useful. ;)

**Comment by fpqc** [comment]
Pretty sure you can pull up a VM for testing using the 30-day trial period, dunno if that allows an upgrade to insider builds.

**Comment by aseering** [comment]
@fpqc -- yes, you can download a free VM from Microsoft here:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

The license runs out after a few weeks; you can download a new one when it does.

Of course, @jepster would still have to set up the VM.  Which would take time, etc.
