### ISSUE TITLE
Entering special characters

### ISSUE THREAD

**Issue by lucvdv** [Microsoft/WSL#1536]
This may not necessarily be a bug, could be so-far incomplete implementation, or something I just didn't find yet.

Entering special characters from the keyboard can usually be done in Windows by Alt+numeric keypad, or in Linux by Shift+Ctrl+U hexvalue.

I can't get either method to work in Bash on Ubuntu on Windows.
I *can* paste those characters into the console if I first copy them to the clipboard in another application.

Code page of the Bash window is set to 65001 (UTF-8).

When I open a standard console (cmd) window, I can use Alt+Number to enter unicode characters. When I execute C:\Windows\System32\bash.exe in that window, it stops working. After exiting bash, it works again.

Has anyone found a way to make it work from the keyboard, so I don't have to resort to copy/paste?
If only to allow me to play around with Gnu APL, probably the least human-readable programming language ever invented ;)

**Comment by CastenettoA** [comment]
I have the same problem.
I can't find a way to insert the tilde "~" character on the shell.

**Comment by sunilmut** [comment]
@zadjii-msft, @bitcrazed can you please help with this?

**Comment by zadjii-msft** [comment]
@adiviness who can comment more

**Comment by adiviness** [comment]
I need to look more into why the input doesn't work with bash, but I do know why it works when the text is pasted. Text pasted from the clipboard into the console window undergoes some additional processing, some of which is converting characters in the pasted text to different values depending on the current code page and keyboard layout.

**Comment by mlocati** [comment]
> I can't find a way to insert the tilde "~" character on the shell.

@CastenettoA In my case, pressing `PageDown` inserts `~` in the shell

**Comment by lucvdv** [comment]
PgDn shows up as a tilde in bash, but I wouldn't trust that to be the only code it emits, and YMMV in other programs. The default PgDn code in Linux is an Escape (Esc) followed by three more codes, the last of which is a tilde.
Actually, it is listed as emitting hex codes 1b 5b 36 7e, or \<Esc\>[6~ on this site: [http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html](http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html)

**Comment by mlocati** [comment]
@lucvdv I don't know the emitted codes, but `cd ~` is working (and I don't have any other alternative to enter `~` except with `PgDn` - I have an Italian keyboard)

**Comment by lornova** [comment]
Same problem here: I'm unable to enter ~ in WSL.
My keyboard layout has no physical ~ key, and the special keys <ALT>+0126 and <PgDn> don't work.
If ~ is in the clipboard it is lost pasting with a right mouse click.
So there is no way to input ~ right now.

**Comment by AndreaOmodeo** [comment]
I have the same problem
Windows X 1709 Pro x64 (italian)
With the italian keyboard layout it's impossible to enter the tilde (~) in wsl bash.
ALT+126 works in all programs but not on the wsl shell
It's also impossible to cut-and-paste the tilde character from a text editor.

If I temporarily switch to the english layout, I can normally enter the tilde character (upper left key near the 1) and the copy-and-paste WORKS! 
(never seen a bug where the keyboard layout affects the contents of what can be pasted)

**Comment by miniksa** [comment]
This is not reproducing for me on either the Fall Creators Update (1709 release, build 16299.15) or on the recent builds of Windows 10 (build 17046) with an it-IT language system or with an en-US system with an it-IT keyboard added or with an en-US system with the system locale for non-Unicode applications changed to Italian (Italy).

I can use ALT+126 in Ubuntu bash, cmd, powershell, or any other application to get a tilde (~) character.

**Comment by lucvdv** [comment]
Same observation as miniksa, it works in 1709. I have another machine that hasn't had the update yet, still 1703, and there it doesn't work.
I'm using US International keyboard layout.

Thanks to the development team for fixing this, and to miniksa for noticing it (I hadn't tried yet, as APL, where I ran into the problem, is installed only on the older machine).

**Comment by AndreaOmodeo** [comment]
Yes, it works for me too.
It was my fault, I believed to be on 1709 but the defective machine was really on 1703.
After the upgrade ALT+126 works and copy-and-paste works too.

**Comment by zadjii-msft** [comment]
Awesome. Glad to help!

**Comment by Gnafu** [comment]
Still an issue with Windows 1803

**Comment by fliespl** [comment]
Is there a way to map tilde from PgDn to normal tilde button?
