### ISSUE TITLE
Might there be any problem tunneling port 80 from the current version of WSL?

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1548]
I was recommended to use OpenSSH via WSL not only to authenticate to my VPS, but also to tunnel actions I do from my browser via port 80, such as PHPmyadmin actions - Several information security experts recommended me of doing so (I already closed port 3306).

I use this command to both authenticate and tunnel port 80:

`ssh user@1.1.1.1 -L 22:localhost:22 -L 2222:localhost:80 -i ~/.ssh/key`

Yet I ask if should there be any problem tunneling port 80 from the current version of WSL, also because I [might have a small problem tunneling it](http://security.stackexchange.com/questions/146578/how-could-i-tunnel-all-actions-i-do-in-my-vps-from-my-browser-like-phpmyadmin-a), which might not be WSL related at all, I really have no idea and ask only make sure as I'm not a OS developer.

I would thank you dearly for sharing your experience.

**Comment by lefty-kreouzis** [comment]
Hi Benosika - it could be related to the issue #1554 that I just opened 
there seems to be a problem with implementing servers in WSL

**Comment by sunilmut** [comment]
@lefty-kreouzis - I don't see any WSL specific issue reported by @Benosika in this post. It seems like he is asking for general guidance. There shouldn't be any general problems of implementing servers on WSL and people have been successfully able to do it. Although, some users are experiencing issues with it (sometimes it's an issue with the AV blocking access). Do let me know if I am missing something.
