### ISSUE TITLE
List of Implemented Syscalls

### ISSUE THREAD

**Issue by doublez13** [Microsoft/WSL#1551]
I definitely may have missed it somewhere, but if not, I think it'd be great to have a status table for which of the Linux kernel's syscalls have been implemented in WSL. Just an idea :)

**Comment by sunilmut** [comment]
There is also a **running** list of syscalls that are implemented in our [release notes page](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes). The first list was compiled for build [14328](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14328) and for every build we mention the additional syscalls that were supported ex: [14986](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14986).

**Comment by EricGT** [comment]
Of interest: [Test cases for WSL system calls ](https://github.com/Microsoft/BashOnWindows/issues/957)

Includes section: How to install and run Linux Test Project (LTP) on WSL

**Comment by sunilmut** [comment]
This is great, @EricGT. We want to encourage all different kinds of tests runs on WSL and are interested in the reports/issues etc.. Thanks for taking the initiative.

**Comment by russalex** [comment]
Quick follow-up.  We added a new syscall list for build 15014 [here](https://github.com/Microsoft/CommandLine-Documentation/blob/live/LTP_Results/15014/Syscalls.txt).  We will be adding the Syscalls.txt file to more builds in the future.

**Comment by doublez13** [comment]
Perfect! Thanks!
