### ISSUE TITLE
open file descriptor limits not updating or being overridden

### ISSUE THREAD

**Issue by JKhawaja** [microsoft/WSL#1576]
Windows Version: `Microsoft Windows [Version 10.0.14393]`

Appending `session    required   pam_limits.so` to the `/etc/pam.d/common-session` and `/etc/pam.d/common-session-noninteractive` files, and then updating the `/etc/security/limits.conf` by appending:

```
*              soft     nofile          35000
*              hard     nofile          35000
```

and restarting Windows, still does not actually update the `ulimit -n` value (or `ulimit -Hn`). It is stuck at `2048` and I am wondering if it can even be changed or if it is being overridden by some process manager, script, or the like?

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Most of the limits are not currently supported, but we are tracking the work.  Please give us feedback for this scenario on uservoice so we can prioritize - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash.

**Comment by ddumontatibm** [comment]
So I just ran into this today as well.

I found that with those settings, I could do 
````
su - myusername
````
and for that session the ulimit would be set according to limits.conf

I don't want to have to do that all the time though...

**Comment by JKhawaja** [comment]
Starting a session with `su - myusername` only allowed me to change `ulimit -n` if I decreased it less than it's current value (whatever it's current value is set at). I was not able to ever increase the value. So, this must be some sort of bug? 

For example, `ulimit -n` defaults at `2048`, but after setting `ulimit -n 2000` I am no longer able to change the value to anything greater than `2000`.

**Comment by sunilmut** [comment]
@ddumontatibm - Thanks for your post. Can you please describe your scenario that is blocked by this? Also, as per @stehufntdev, please open a user voice ticket if you would like us to prioritize it.

**Comment by ddumontatibm** [comment]
@sunilmut Sure.

I'm using bash on windows to try to build a project with node and webpack.   There are many file that are opened during that process.   Even with my workaround to set limits in conf files and use su, I was unable to complete the build due to file limit.

**Comment by DachuanZhao** [comment]
any processing ?

**Comment by pecigonzalo** [comment]
@stehufntdev that link no longer works, could you update on the status of this? Its related to https://github.com/microsoft/WSL/issues/633.

**Comment by pecigonzalo** [comment]
I just found a "better" workaround.

We can use `prlimit -p PID` to set limits for other processes, if we allow that command (or wrap it in a script to further secure it) and execute it with `sudo` at init, we can effectively change the limits for the running shell.

EG:
```
❯ prlimit -p "$$"
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
AS         address space limit                unlimited unlimited bytes
CORE       max core file size                         0 unlimited bytes
CPU        CPU time                           unlimited unlimited seconds
DATA       max data size                      unlimited unlimited bytes
FSIZE      max file size                      unlimited unlimited bytes
LOCKS      max number of file locks held      unlimited unlimited locks
MEMLOCK    max locked-in-memory address space     65536     65536 bytes
MSGQUEUE   max bytes in POSIX mqueues            819200    819200 bytes
NICE       max nice prio allowed to raise             0         0
NOFILE     max number of open files                1024      4096 files
NPROC      max number of processes                31823     31823 processes
RSS        max resident set size              unlimited unlimited bytes
RTPRIO     max real-time priority                     0         0
RTTIME     timeout for real-time tasks        unlimited unlimited microsecs
SIGPENDING max number of pending signals          31823     31823 signals
STACK      max stack size                       8388608 unlimited bytes
```
_`$$` resolves to the current process PID_

Then change it
```
sudo prlimit -p "$$" --nofile=10000:10000
```

And "reload" the shell
```
exec zsh -l
```

Verify
```
❯ prlimit -p "$$"
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
AS         address space limit                unlimited unlimited bytes
CORE       max core file size                         0 unlimited bytes
CPU        CPU time                           unlimited unlimited seconds
DATA       max data size                      unlimited unlimited bytes
FSIZE      max file size                      unlimited unlimited bytes
LOCKS      max number of file locks held      unlimited unlimited locks
MEMLOCK    max locked-in-memory address space     65536     65536 bytes
MSGQUEUE   max bytes in POSIX mqueues            819200    819200 bytes
NICE       max nice prio allowed to raise             0         0
NOFILE     max number of open files               10001     10001 files
NPROC      max number of processes                31823     31823 processes
RSS        max resident set size              unlimited unlimited bytes
RTPRIO     max real-time priority                     0         0
RTTIME     timeout for real-time tasks        unlimited unlimited microsecs
SIGPENDING max number of pending signals          31823     31823 signals
STACK      max stack size                       8388608 unlimited bytes
```

**Comment by therealkenc** [comment]
Support for `ulimit -n` was improved in [16257](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-16257). Full support for `ulimit` and `prlimit` is available in WSL2. Ref #4575.

**Comment by istvan-ujjmeszaros** [comment]
@therealkenc if I run `ubuntu2004 run "ulimit -n"` then the result is still 1024 despite I have edited all the files that are mentioned in all the other related threads. I am on the Release Preview Channel. Can you double-check if this really is resolved?

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/98761882-3d409100-238b-11eb-8a8a-d4f03ece2852.png)

**Comment by istvan-ujjmeszaros** [comment]
Doesn't seem to have an effect on `ubuntu2004 run` (unfortunately RubyMine is using this way to work with WSL and ending up in the Too many open files exception).
![image](https://user-images.githubusercontent.com/1273763/98762328-b1088b00-23d7-11eb-9702-61a9eb37615a.png)

**Comment by therealkenc** [comment]
> `ubuntu2004 run "ulimit -n"`

That outputs the limit of a different shell (with a different `PID`) than the one where you changed the limit with `prlimit(1)`. That much is linux-behavior.

Assuming setting the limit in `.profile`, newspeak would be something like:

```
C:\> wsl.exe -d Ubuntu /bin/bash -lc "ulimit -n"
```

Some kind of placeholder feature request to make the default `unlimited` would probably not be out of line. Or yet another `wsl.conf` thingy. Absent a more complete resolution #994, anyway.

**Comment by istvan-ujjmeszaros** [comment]
That's looking like a possible workaround! But I am not sure if I can alter RubyMine to do the calls with these arguments. I will open a ticket at Jetbrains but it would be great if this hard-coded value could be changed somehow. Is it possible to rebuild the kernel or something like that?
![image](https://user-images.githubusercontent.com/1273763/98810351-66126600-241f-11eb-90e2-01f648bcab36.png)
