### ISSUE TITLE
connect() should return EINPROGRESS if a non-blocking connection is refused

### ISSUE THREAD

**Issue by aseering** [Microsoft/WSL#1584]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
The scenario is, I'm trying to open a non-blocking socket to a port that is not listening.  This should (and does) produce an error.

On WSL, `connect()` returns `ECONNREFUSED` in this scenario.

On an Ubuntu Linux machine, `connect()` on this socket does not return `ECONNREFUSED`.  Instead, it returns `EINPROGRESS`.

The `connect()` [man page](http://man7.org/linux/man-pages/man2/connect.2.html) is somewhat ambiguous on the subject, but it seems to imply that `ECONNREFUSED` is at least a valid return code in the special case of a non-blocking connection being unable to connect.

Many simple command-line socket-based tools use non-blocking sockets; for example, `nc`, `telnet`, and `curl`.  Most of them handle either error code just fine, so this isn't a big deal.

* Expected results
(Note:  For all of the examples below, I'm connecting to port 12345 but I deliberately have no program actually listening on port 12345.)

```
Linux$ curl http://localhost:12345
curl: (7) Failed to connect to localhost port 12345: Connection refused
Linux$ strace curl http://localhost:12345
...
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 5
setsockopt(5, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(5, SOL_TCP, TCP_KEEPIDLE, [60], 4) = 0
setsockopt(5, SOL_TCP, TCP_KEEPINTVL, [60], 4) = 0
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(5, {sa_family=AF_INET, sin_port=htons(12345), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
...
```

* Actual results (with terminal output if applicable)

```
WSL$ curl http://localhost:12345
curl: (7) Couldn't connect to server
WSL$ strace curl http://localhost:12345
...
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPIDLE, [60], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPINTVL, [60], 4) = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
clock_gettime(CLOCK_MONOTONIC, {85031, 861028000}) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(12345), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
...
```

* Your Windows build number
15002

* Steps / All commands required to reproduce the error from a brand new installation 
See above.  Let me know if more detail is needed.

* Strace of the failing command
See above.  Let me know if more detail is needed.

* Required packages and commands to install
I think `curl` is installed by default?  If not, `sudo apt-get -y install curl`

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
I hit this while playing around with some code that I can now run under WSL because #616 has been resolved.  (Incidentally, thanks!  I'm still playing with the new build, but it looks like a huge improvement so far.)  There's no behavioral problem as a result of this; it just affects the default error-message text in some cases.

**Comment by sunilmut** [comment]
@aseering - Thanks for the report and thanks all the details, as always. WSL currently does not support non-blocking connect. All `connect` request are treated as blocking. This will be a good test case to add for non-blocking connect. I have taken a note of it.

Glad to know that #616 hasn't repro'd for you so far.

**Comment by sunilmut** [comment]
I have opened a feature request for non-blocking `connect`. Will most probably land after this release, given that this is not really blocking anything at the moment.

**Comment by aseering** [comment]
@sunilmut -- thanks!  Good to know regarding non-blocking `connect`.

**Comment by IsaacABrown** [comment]
I'd like to add that this behavior essentially prevents the use of knocking and knockd in WSL since it will continue to try to establish the connection instead of moving on to succeed with the knock pattern.

**Comment by sunilmut** [comment]
Just an update that `non-blocking connect` is on it's way and will also be available on Fall Creators Update.

**Comment by Yay295** [comment]
The Fall Creators Update is out now. Has this issue been fixed as well?

**Comment by sunilmut** [comment]
@Yay295 - Yes, it is. Please try the scenario out and let us know if it is not working for you.
