### ISSUE TITLE
When i close bash on windows does not keep what i've done

### ISSUE THREAD

**Issue by Heerou** [Microsoft/WSL#1616]
I use sudo update command and everything it's fine, but when i close the terminal it resets, it doesn't keeps what i have done and it's really weird.
It happened too when i tried to use rvm and i lost all my gemsets.

**Comment by aseering** [comment]
Hi @Heerou -- that is indeed really weird, and not as expected if you're losing files on disk.  Could you please post the output of a simple example shell session where you set things up using `sudo` and show that they're there; then close that shell, open up a new one, and post the output from looking around in this new shell and finding that your stuff is no longer there?

**Comment by aseering** [comment]
If you are starting processes, then that is expected -- WSL "shuts down" and all Linux processes exit when the last bash window closes.

**Comment by therealkenc** [comment]
WSL no longer kills processes unattached to a tty on exit of the last open console.
