### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by flamecopper** [microsoft/WSL#1622]
Linux ECOPSGN102 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 GNU/Linux

perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 80763 files and directories currently installed.)
Preparing to unpack .../archives/bash_4.4-2_amd64.deb ...
bash.preinst: cannot run dpkg-query: Invalid argument
dpkg: error processing archive /var/cache/apt/archives/bash_4.4-2_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
update-alternatives: error: alternative path /usr/share/man/man7/bash-builtins.7.gz doesn't exist
Errors were encountered while processing:
 /var/cache/apt/archives/bash_4.4-2_amd64.deb
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
update-kali-menu: error: can't open /usr/share/applications/byobu.desktop: No such file or directory
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: Problem executing scripts DPkg::Post-Invoke '[ ! -x /usr/share/kali-menu/update-kali-menu ] || /usr/share/kali-menu/u
pdate-kali-menu wait_dpkg'
E: Sub-process returned an error code
root@ECOPSGN102:/mnt/c/Users/derek.lim/Desktop# uname -a

FYI we have tried:
sudo dpkg --configure -a
sudo apt-get -f upgrade
sudo apt-get install -f

**Comment by aseering** [comment]
Hi @flamecopper -- could you describe your environment in more detail?  For example, are you running Windows build 14393 (the current stable build), or are you running an Insider pre-release build?  If Insider, what build number?

Also, could you please post the output of `apt-cache policy bash`?

Your environment is configured in an unusual way; I'm trying to understand it:  Your system is stuck installing a very new third-party bash package.  (Or perhaps you are attempting to test a very early / unsupported pre-release version of Ubuntu Zesty?  Either way, it's not a package that's available for stock Ubuntu Linux, nor for stock WSL.)  I'm trying to figure out where it's coming from, and whether it's most likely a WSL bug or limitation or more likely an issue with the package.

**Comment by therealkenc** [comment]
I haven't tried to repro (no steps were actually provided), but @aseering's "a very new third-party bash package" comment was a good tip-off. The `invalid argument` is probably #1005, which causes known problems with locale. Some discussion in #482 [message](https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-243012795).

**Comment by flamecopper** [comment]
Hi All,

denny@Ey:/mnt/c/Users/alvin.oo/Desktop$ apt-cache policy bash
bash:
  Installed: 4.3-7ubuntu1.5
  Candidate: 4.4-2
  Version table:
     4.4-2 500
        500 http://http.kali.org/kali kali-rolling/main amd64 Packages
 *** 4.3-7ubuntu1.5 500
        500 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64
Packages
        500 http://security.ubuntu.com/ubuntu trusty-security/main amd64
Packages
        100 /var/lib/dpkg/status
     4.3-6ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu trusty/main amd64 Packages

Alvin Oo,Tel:(65)91172830

**Comment by ahennar** [comment]
I faced with the same issue. Is there a way to fix it?
bash:
  Installed: 4.3-15ubuntu1
  Candidate: 4.4-2ubuntu1
  Version table:
     4.4-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages
 *** 4.3-15ubuntu1 100
        100 /var/lib/dpkg/status

**Comment by noahzaozao** [comment]
noah@DESKTOP-KH7TO2T:~$ apt-cache policy bash
bash:
  Installed: 4.3-7ubuntu1.7
  Candidate: 4.4-2ubuntu1.1
  Version table:
     4.4-2ubuntu1.1 0
        500 http://cn.archive.ubuntu.com/ubuntu/ zesty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ zesty-security/main amd64 Packages
     4.4-2ubuntu1 0
        500 http://cn.archive.ubuntu.com/ubuntu/ zesty/main amd64 Packages
 *** 4.3-7ubuntu1.7 0
        100 /var/lib/dpkg/statu

**Comment by mikekosulin** [comment]
$ apt-cache policy bash
bash:
  Installed: 4.3-14ubuntu1.2
  Candidate: 4.3-14ubuntu1.2
  Version table:
 *** 4.3-14ubuntu1.2 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4.3-14ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by 1122Dipak** [comment]
apt-cache policy bash
bash:
  Installed: 4.4.18-2ubuntu1.1
  Candidate: 4.4.18-2ubuntu1.1
  Version table:
 *** 4.4.18-2ubuntu1.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     4.4.18-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
Problem in installing packages

**Comment by therealkenc** [comment]
Notice this one because of the necropost. The [OP](https://github.com/microsoft/WSL/issues/1622#issue-202173267) fail was:

> Preparing to unpack .../archives/bash_4.4-2_amd64.deb ...
> bash.preinst: cannot run dpkg-query: Invalid argument

Which never had an [`strace(1)`](http://man7.org/linux/man-pages/man1/strace.1.html) or anything else to go on (even the command being run). There has been much water under the bridge since then. The follow-up  post asking for `apt-cache policy bash` was well meaning, but doesn't actually move the issue any further to resolution to why the OP's `dpkg-query` failed on `EINVAL`.

From a May 2017 [post](https://github.com/microsoft/WSL/issues/1622#issuecomment-300788514):
> I faced with the same issue. Is there a way to fix it?

There isn't any idication what "it" is here, because there is no repro. If folks are still seeing fails (whatever the fail may be) with whatever folks are doing here (whatever "here" means) feel encouraged to open a new issue following the [template](https://github.com/microsoft/WSL/blob/master/ISSUE_TEMPLATE.md), paying particular attention to including all CLI steps necessary to induce the fail from a clean install.
