### ISSUE TITLE
Transferring quotes from bash to windows app doesn't work as expected

### ISSUE THREAD

**Issue by vacore** [Microsoft/WSL#1625]
hello.c
`#include <stdio.h>`
`int main (void) { `
 ` printf (INIT_VER_STR);`
`}`
`user@machine:/mnt/d/code$ gcc -c hello.c -DINIT_VER_STR="\"Hello, world\"" -e`
output >>
...
`int main (void) { `
`  printf ("Hello, world"); `
`}`
<<
Note: gcc is Ubuntu app

`user@machine:/mnt/d/code$ armcc.exe -c test.c -DINIT_VER_STR="\"Hello, world\"" -e`
output >>
...
`int main (void) { `
`  printf (Hello,); `
}`
<<
Note: armcc.exe is Windows app

Windows build number .15007
Note: running armcc.exe under cygwin yeilds expected results.

**Comment by leojbgiusti** [comment]
I am experiencing this issue when trying to build TTDPatch using the cygwin copy of nasm.exe included in the TTDPatch source.

**Comment by leojbgiusti** [comment]
An update on this issue from the Microsoft developers would be greatly appreciated. I can try to provide output of the build system the project I am trying to build and is failing if that would be helpful.

**Comment by TSlivede** [comment]
I think the titles of both this issue and https://github.com/Microsoft/BashOnWindows/issues/2164 could be renamed to "WSL interop doesn't follow typical windows CommandLine quoting".

A reference to [MS rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) could be added to the description and https://github.com/Microsoft/BashOnWindows/issues/2164 could be closed as duplicate.

Apps that don't follow the typical rules must be considered - but even with the current behaviour, it's really hard to correctly call an app, that doesn't follow [these rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx).  
As a suggestion to allow a custom CommandLine:  
Let WSL check a "magic" environment variable (e.g. `WINDOWS_COMMANDLINE_FLAT`) and if it is set to `1` don't do any processing with arguments - just append them all to the CommandLine, without even adding quotes (Some strange executables might not like `"`).

If you think changing the behaviour is not the right way, maybe this is interesting:
(From my own comment: https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-251116447)

>on windows, the current behavior is inconsistent:
If an argument contains no spaces, it is passed unchanged.
If an argument contains spaces, if it will be surrounded by quotes, to keep it together through CommandLineToArgvW call. => Argument is changed to meet CommandLineToArgvW requirement.
But if argument contains quotes, those are not escaped. => Argument is not changed, although CommandLineToArgvW requires this.
>
>I think arguments should either never be changed, or always be changed to meet CommandLineToArgvW requirements, but not in half of the cases.

**Comment by TSlivede** [comment]
@benhillis As you published a [blog post](https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/) about WSL interop, could you elaborate on whether it was intetional not to follow [these rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) (if so: why?) or if it was implemented this way by accident.

**Comment by benhillis** [comment]
@TSlivede - I didn't make this original design decision but I can speak to the goal.  The goal was to pass the entire command line to /bin/bash as a single argument so bash would be in charge of command line parsing using the Linux rules.  Since the commands being run are Linux commands it made sense to use Linux argument parsing rules.

**Comment by TSlivede** [comment]
@benhillis - Thank you very much for the quick response!

If I understand you correctly, you are talking about https://github.com/Microsoft/BashOnWindows/issues/1746, I'll respond there.

What I tried to ask, was If it was intentional not to follow [these rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx), when calling a Windows executable from within WSL. ("Launching Win32 applications from within WSL" in [your post](https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/))

When calling Windows executable from within WSL, WSL has to create a single CommandLine from the argv-array. This should IMHO be done in a way, such that any executable that uses [these rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) gets the same argv array as originally given from within WSL. (AFAIK, `CommandLineToArgvW`, Visual Studio, mingw and .net startup code all follow these rules.)

**Comment by benhillis** [comment]
@TSlivede - Oh sorry, I misunderstood your question.  Our binfmt interpreter receives the arguments via the the argument to the main method.  At this point Linux usermode (the shell) has already done some argument parsing according to Linux rules, so it may not be possible to 100% conform to the rules you link.  I'm marking this issue as a bug so I can investigate later if anything else can be done.

**Comment by TSlivede** [comment]
>At this point Linux usermode (the shell) has already done some argument parsing

And this is great: The parsing is consistant and does not depend on the called executable. On Windows arguments are sadly not transferred as an array but as a single CommandLine String that must be split by the target executable. Therefore the array must be converted into one single string. This could be done in multiple different ways:

* Only allow one argument in argv-array and use this as the CommandLine
   * Pro: Absolutely **consistent**, no magic involved, no surprises
   * Con: Absolutely annoying and unexpected for users who don't know that windows only knows about a single CommandLine
* Join all argv-elements by inserting spaces between argv-elements
   * Pro: **Consistent** with [MS _spawn functions](https://msdn.microsoft.com/en-us/library/20y988d2.aspx#Anchor_1)
   * Con: Even more surprising for users who don't know about the single windows CommandLine
* Join all argv-elements by adding `"` before and after each argv-element and then join them with spaces in between
   * Pro: At least somewhat predictable and therefore consistent.
   * Con: It's very easy to forget escaping `"` (and `\` at the end of each argument) when calling windows executables, that follow the common rules
* Join all argv-elements by adding `"` before and after argv-elements *only if they contain spaces* and then join them with spaces in between (currently done by WSL)
   * Pro: ???
   * Con: Same as previous option, but less consistant than previous option.
* Assume that the windows executable will split the CommandLine according to [these rules](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) and build the CommandLine accordinly. (done by cygwin, python, ...)
   * Pro: Almost all Windows applications will get exactly that content in their argv-array that was specified by the calling process. This option is **consistent** as it follows well documented rules.
   * Con: Fails in rare cases, when the target executable doesn't follow these rules. (Sadly `cmd.exe` is one of these cases - cygwin actually has a special case: if the executable is `cmd.exe` the CommandLine is generated differently)

This last one is in my opinion the best way, as it's the only way that actually treats the argv-array the same as linux executables. 

<sub>This is currently also discussed for [powershell](https://github.com/PowerShell/PowerShell/issues/1995) (same problem: convert argument array to CommandLine)</sub>

**Comment by sunjoong** [comment]
> Our binfmt interpreter receives the arguments via arguments to the main() method

@benhillis - strace of `armcc.exe -c test.c -DINIT_VER_STR="\"Hello, world\"" -E` might be...
`execve("<path of armcc.exe>", ["armcc.exe", "-c", "test.c", "-DINIT_VER_STR=\"Hello, world\"", "-E"], [/* 14 vars */]) = 0`
Untile execve(), "some argument parsing according to Linux rules", but after binfmt interpreter, arguments of `/init' could lose their arg order unless proper encoding/decoding of escape characters, I guess.

**Comment by benhillis** [comment]
I have a fix for this issue and #2164 in code review currently.

**Comment by sunilmut** [comment]
The fix is available in Fall Creators Update.

**Comment by raymod2** [comment]
What was the fix?  Previously the following command worked for me:

cmd /c "dir \"C:\Program Files (x86)\""

Now, with the Fall Creator's Update, this command fails.

**Comment by raymod2** [comment]
Upon further inspection it appears that Ben's fix has broken this use case.  Worse, I don't see a way to circumvent the new bug.  Consider the following program compiled to args.exe:

`
#include <stdio.h>

int main(int argc, char **argv)
{
   int i;

    printf("\nCommand-line arguments:\n");

    for (i = 0; i < argc; i++)
    {
       printf("  argv[%d]   %s\n", i, argv[i]);
    }
}
`

Here is the output from a Windows shell:

`
C:\Users\Dan>cmd /c "z:\bin\args.exe "foo bar""

Command-line arguments:
  argv[0]   z:\bin\args.exe
  argv[1]   foo bar

C:\Users\Dan>cmd /c "z:\bin\args.exe \"foo bar\""

Command-line arguments:
  argv[0]   z:\bin\args.exe
  argv[1]   "foo
  argv[2]   bar"
`

Note that the inner quotes cause foo and bar to be treated as a single argument unless you escape those quotes.  Here is from a WSL session:

` 
root@DESKTOP-MVKOR9S:~# cmd /c "z:\bin\args.exe "foo bar""

Command-line arguments:
  argv[0]   z:\bin\args.exe
  argv[1]   foo
  argv[2]   bar
root@DESKTOP-MVKOR9S:~# cmd /c "z:\bin\args.exe \"foo bar\""

Command-line arguments:
  argv[0]   z:\bin\args.exe
  argv[1]   "foo
  argv[2]   bar"
`

Here foo and bar are treated as separate arguments whether you use quotes or not.

**Comment by therealkenc** [comment]
@raymod2  - Good report. Since the change made it into the wild (Fall Creators) and this issue is closed, it would probably be worth opening a new issue# to track -- however it plays out.

**Comment by sunilmut** [comment]
@raymod2 - Aggred with @therealkenc that this is worth a new ticket.
