### ISSUE TITLE
Unsupported Packet socket and Socket Filtering(when trying to run dhcpd)

### ISSUE THREAD

**Issue by crashtua** [Microsoft/WSL#1628]
* A brief description
Trying to start isc-dhpc-server results in messages about unsupported Packet socket and Socket Filtering
* Expected results
Everything working fine and dhcp-server giving ips to clients
* Actual results (with terminal output if applicable)
Internet Systems Consortium DHCP Server 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/dhcp/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 0 leases to leases file.
socket: Address family not supported by protocol - make sure
CONFIG_PACKET (Packet socket) and CONFIG_FILTER
(Socket Filtering) are enabled in your kernel
configuration!
* Your Windows build number
15014
* Steps / All commands required to reproduce the error from a brand new installation 
-- run bash as Administrator
-- create subnet in dhcpd.conf for your adapter
-- run dhcpd eth0
* Strace of the failing command
http://pastebin.com/DmiTxGAx

**Comment by therealkenc** [comment]
```
...
socket(PF_PACKET, SOCK_RAW, 768)        = -1 
    EAFNOSUPPORT (Address family not supported by protocol)
...
```

#1515 ([message](https://github.com/Microsoft/BashOnWindows/issues/1515#issuecomment-267736989))

**Comment by sunilmut** [comment]
Thanks, @crashtua for the post and @therealkenc for the diagnosis. Yes, currently, WSL does not has support for `AF_PACKET` address family. If you can open a [user voice ticket](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) for this, it will help us prioritize it.

**Comment by gpotter2** [comment]
This feature would be great if implemented ! https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817211-support-af-packet-address-family-and-raw-sockets

**Comment by sunilmut** [comment]
@gpotter2 - Thanks for opening the user voice ticket. Just FYI that SOCK_RAW is currently supported for RAW, UDP and ICMP(V6) protocols. TCP can follow without much problem. So, I would restrict the user voice ticket for `AF_PACKET` and also add what applications are dependent on it. Now, let's get some votes behind it.

**Comment by gpotter2** [comment]
@sunilmut Edited :)

**Comment by Biswa96** [comment]
@sunilmut `socket(AF_INET,SOCK_DGRAM,IPPROTO_ICMP);` also shows Permission denied with root user.

**Comment by sgf** [comment]
Why ppl like Linux because Linux has fewer restrictions, people can do more what they want to do.
Please don't bring the limit from windows to the WSL.if only can do the windows can do,why we should be use WSL?

Soo,when could be the problem soloved?

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar

that has 1426 votes now ?
 how many votes need ?

**Comment by therealkenc** [comment]
dupe #1515
