### ISSUE TITLE
Bash.exe to accept Windows file path as parameter

### ISSUE THREAD

**Issue by vovcacik** [Microsoft/WSL#1629]
I would like the `bash.exe` to accept filepath to a script file in windows form, and not just in the unix form.

This works now:
```
bash "/mnt/c/Users/Admin/Desktop/test.bash"
```

But this will fail with `Directory or file does not exist`:
```
bash "C:\Users\Admin\Desktop\test.bash"
```

Besides the added comfort when I am invoking bash from batches, this also opens the option to make `*.sh` or `*.bash` filetype double clickable.

Thanks

**Comment by Herst** [comment]
This mapping should only happen if invoked from a non-WSL place (e.g. `cmd.exe` or a Windows Shortcut [`.lnk`]), right?

**Comment by sunilmut** [comment]
Thanks @vovcacik for the feedback. This is a good candidate for a [user voice request](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash).

**Comment by vovcacik** [comment]
Remotely related: bmatzelle/gow#244

**Comment by tara-raj** [comment]
You can use the [wslpath](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046)  tool to convert the filepath for you. Please try this solution
