### ISSUE TITLE
perl: warning: Please check that your locale settings:

### ISSUE THREAD

**Issue by flamecopper** [Microsoft/WSL#1656]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Warning when I try to execute commands

* Expected results

I am not expecting to see the locale warning

* Actual results (with terminal output if applicable)

perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US.UTF-8"

* Your Windows build number

root@ECOPSGN102:/mnt/c/Users/alvin.oo/Desktop# uname -a
Linux ECOPSGN102 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 GNU/Linux

Windows 10 107

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
No repro provided; but [set your locale](https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu).
