### ISSUE TITLE
Long delay before some host connected (particularly during apt update)

### ISSUE THREAD

**Issue by ifree92** [Microsoft/WSL#1663]
When I try to update packages lists and update packages I have too long delay before server will respond.

My windows version: _Microsoft Windows [Version 10.0.14393]_
with all installed updates at moment this post.

When I type the command:

```
ifree@DESKTOP-VRM7SQQ:~$ LC_MESSAGES=C sudo apt update
0% [Connecting to archive.ubuntu.com (2001:67c:1560:8001::11)] [Connecting to s
```
And I waiting when command continue to work about 30-40 seconds before command continue to work.

small additional information about BashOnWindows.
```
ifree@DESKTOP-VRM7SQQ:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
ifree@DESKTOP-VRM7SQQ:~$ uname -a
Linux DESKTOP-VRM7SQQ 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
```

The same problem I have on my laptop with the same Windows version and the same version of BashOnLinux.

I tried to reinstall using lxrun utility (fully removed lxss folder with distributive, and fully new installing), but problem continue to be. Earlier I didn't have this problem but last month this occurs.

**Comment by tara-raj** [comment]
Linking to this issue https://github.com/Microsoft/WSL/issues/2477 and closing.

**Comment by therealkenc** [comment]
FWIW I think there is something to this one related to ipv6 (specifically, if you have lackthereof -- which you won't see in Redmond). I have been meaning to come up with a test case but _effort_. #2477 is about the _rate_ of transfer, which happens after the resolver.
