### ISSUE TITLE
Segmentation fault when dumping (building emacs)

### ISSUE THREAD

**Issue by csant** [Microsoft/WSL#1664]
Trying to build emacs-25.1.

$ ./configure --prefix=/usr
$ make
[...] building, loading everything, then:
Dumping under the name emacs
**************************************************
Warning: Your system has a gap between BSS and the
heap (28591512 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [bootstrap-emacs] Segmentation fault (core dumped)
make[1]: Leaving directory `/home/csant/src/emacs/emacs-25.1/src'
make: *** [src] Error 2

All build tools have been installed via apt-get install.

Microsoft Windows [Version 10.0.14393]

$ strace make
[...]
Dumping under the name emacs
**************************************************
Warning: Your system has a gap between BSS and the
heap (14849432 bytes).  This usually means that exec-shield
or something similar is in effect.  The dump may
fail because of this.  See the section about
exec-shield in etc/PROBLEMS for more information.
**************************************************
make[1]: *** [bootstrap-emacs] Segmentation fault (core dumped)
make[1]: Leaving directory `/home/csant/src/emacs/emacs-25.1/src'
[{WIFEXITED(s) && WEXITSTATUS(s) == 2}], 0, NULL) = 16728
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=16728, si_status=2, si_utime=0, si_stime=0} ---
rt_sigreturn()                          = 16728
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbc1c950000
read(3, "# Locale name alias data base.\n#"..., 512) = 512
read(3, "PURPOSE.  See the\n# GNU General "..., 512) = 512
read(3, " entries are case independent.\n\n"..., 512) = 512
read(3, "859-1\nfinnish         fi_FI.ISO-"..., 512) = 512
read(3, "R\nko_KR\t\tko_KR.eucKR\nlithuanian "..., 512) = 512
read(3, "SO-8859-9\n", 512)             = 10
read(3, "", 512)                        = 0
close(3)                                = 0
munmap(0x7fbc1c950000, 4096)            = 0
open("/usr/share/locale/en_US.UTF8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.UTF8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "make: ", 6make: )                   = 6
write(2, "*** [src] Error 2", 17*** [src] Error 2)       = 17
write(2, "\n", 1
)                       = 1
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
chdir("/home/csant/src/emacs/emacs-25.1") = 0
close(1)                                = 0
munmap(0x7fbc1c960000, 4096)            = 0
exit_group(2)                           = ?
+++ exited with 2 +++

**Comment by csant** [comment]
A solution is referred to in etc/PROBLEMS:
echo 0 > /proc/sys/kernel/randomize_va_space

But WSL doesn't allow you to do this, not even with sudo.

Solution is to
lxrun /setdefaultuser root
in a Powershell, then start WSL again, `make' to finish compilation, in Powershell switch back to your usual user, `chown' the binaries to match your user, and `make install'...

**Comment by therealkenc** [comment]
Appears to work on 15025. (I forgot the `bash -c` recently in another context too.)

`$ sudo bash -c "echo 0 > /proc/sys/kernel/randomize_va_space"`

**Comment by csant** [comment]
Ah, with 'sudo bash -c' it allows the operation, without, however, it doesn't.  Still getting a hang of the system's glitches :)  Thanks! Dumping shouldn't crash in a first case, however - and that's what the report is about.

**Comment by therealkenc** [comment]
The `sudo bash -c` thing is a feature. Does the same on Real Linux™.

On a lark I just tried building 25.1 on native Ubuntu (happened to be 16.10). It segfaults the same there too.

**Comment by therealkenc** [comment]
Appears to be:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24682

**Comment by therealkenc** [comment]
Me:

> Appears to work on 15025. (I forgot the bash -c recently in another context too.)

This issue was just never closed out. This one, oddly enough, was linux-behavior.

**Comment by BelfordZ** [comment]
I had to `sudo su` before  `echo 0 > /proc/sys/kernel/randomize_va_space` was allowed.

afterwards, make works. ty @csant
