### ISSUE TITLE
Tmux has rendering issues with Vim under windows bash (conEmu)

### ISSUE THREAD

**Issue by alex-shamshurin** [Microsoft/WSL#1668]
First of all I'm not shure where to post, to conEmu or here.

* Screen painting is corrupt when started via conEmu (under powershell all is ok)

* My setup Instruction are here https://conemu.github.io/en/BashOnWindows.html
(wslbridge) via `wsl-con.cmd` file.

* then run `tmux`

* then run vim

The result is here
![pqvwr2ypbj](https://cloud.githubusercontent.com/assets/1595209/22626743/dd323c9c-ebc5-11e6-9d1e-c29ed9665f2a.gif)

**Comment by zadjii-msft** [comment]
@alex-shamshurin could you share what build of windows you're on? (you can find this by opening a plain cmd.exe window, the part that says "Microsoft Windows [Version 10.0.14983]")

also @Maximus5 for visibility

**Comment by Maximus5** [comment]
And what ConEmu build you are trying?

**Comment by alex-shamshurin** [comment]
windows 10.0.14393 x64 
conEmu 170118 [64]

**Comment by Maximus5** [comment]
What keys you are pressing? Need to know to reproduce.

**Comment by alex-shamshurin** [comment]
just "i" to enter into edit mode and then enters to shift down strings

**Comment by Maximus5** [comment]
Not "just". Vim doesn't have splitter after startup.

**Comment by alex-shamshurin** [comment]
It's nerdTree panel. I use popular spf13 vim config https://github.com/spf13/spf13-vim

**Comment by alex-shamshurin** [comment]
Rendering issues are everywhere, not only when I do pasting strings. Only under tmux

**Comment by zadjii-msft** [comment]
I don't know too much about ConEmu, but does the same scenario repro in just a plain old conhost window?

I know for a fact that I fixed a bug where if the viewport wasn't at 0,0, some Insert Line / Delete Line functions (which vim/tmux use extensively) could cause a rendering issue. Typically, vim and tmux should go to the alternate buffer, which wont have this issue, but there are ways to disable the alt-buffer.

Could you paste the output of `infocmp` from inside tmux? If there's no `smcup`/`rmcup` entries, then that could cause this.

**Comment by alex-shamshurin** [comment]
```salex@SALEXHOME:~$ infocmp
#       Reconstructed via infocmp from file: /lib/terminfo/s/screen
screen|VT 100/ANSI X3.64 virtual terminal,
        am, km, mir, msgr, xenl,
        colors#8, cols#80, it#8, lines#24, ncv@, pairs#64,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
        dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K, enacs=\E(B\E)0,
        flash=\Eg, home=\E[H, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=^J, is2=\E)0, kbs=\177,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,
```

**Comment by alex-shamshurin** [comment]
BTW, pasting into console under tmux is also slow, Seems like I'm behind old 5kb/s modem.

**Comment by aligit** [comment]
ConEmu has very poor integration with Windows Bash. After 3 painful months, I have switched to terminator console. You need to install VcXsrv and configure X11 to display windows apps

**Comment by alex-shamshurin** [comment]
But I use proxy via wsl. Everything works fine except under tmux

**Comment by Maximus5** [comment]
I think this issue may be closed?

**Comment by sc0ttwad3** [comment]
@aligit Any example integration pain points you ran into? 

I've found [Cmdr using ConEmu-maximus5](http://cmder.net/) 171025 [64] {alpha} to be the best terminal so far running wsl with both the bash and zsh shells. I've also run Terminator (and some of the other terminals, rxvt, etc.) via running an X server on Windows and feel crippled in the terminal whenever I do so.

@Maximus5 Many thanks for your work on ConEmu, BTW. I couldn't live without it!

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
