### ISSUE TITLE
WSL - screen application behavior change

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/WSL#1674]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
After latest upgrade of Windows 10 build, when executing 'sudo screen' app in WSL is not working correctly. The screen welcome page doesn't come up and the it resize the console prompt. 
Also, it's making hard to work with PowerShell.

* Expected results
To keep the console size as it opens, the "Welcome Screen" shows up, and PowerShell will work.

* Actual results (with terminal output if applicable)
Characters junk on the right of the console prompt, Cursor jumps from original location.

* Your Windows build number
Windows 10 Pro Insider Preview 15007.rs_prelrelease.170107-1846

* Steps / All commands required to reproduce the error from a brand new installation 
open 'Bash On Ubuntu On Windows'
sudo screen
powershell

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.
![screeb_01_2017-02-06_11-59-11](https://cloud.githubusercontent.com/assets/19892435/22657861/fb4de5c8-ec65-11e6-9075-5c20e4ac1b5b.jpg)
![screeb_02_2017-02-06_11-59-11](https://cloud.githubusercontent.com/assets/19892435/22657876/0062c2fe-ec66-11e6-8e67-cec90d96fb9d.jpg)
![screeb_03_2017-02-06_11-59-11](https://cloud.githubusercontent.com/assets/19892435/22657884/057a032e-ec66-11e6-877a-92d096b28802.jpg)

**Comment by benhillis** [comment]
@zadjii-msft - can you take a look at this? This still seems to be broken on the most recent internal build.

**Comment by MarioMaster100** [comment]
Screen command doesn't work for me. I set up the /var/run/screen directory and ran chmod 777 /var/run/screen and after I load it, it immediately terminates.

**Comment by MaximoTrinidad** [comment]
FYI

If you install "Ubuntu Desktop" then screen command will work as expected.  But, this was working fine on older build.
:)

**Comment by zadjii-msft** [comment]
@MaximoTrinidad Is this fixed for you in Creator's Update? I believe it should be.

**Comment by MaximoTrinidad** [comment]
Hi @zadjii-msft,

Which build is that one?  Because before version of Windows Insider version Build 16170.rs_prerelease.170331-1532 it was working now and not it isn't.

:)

**Comment by zadjii-msft** [comment]
@MaximoTrinidad I believe it's 10.0.15063

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
