### ISSUE TITLE
Set cursor style (DECSCUSR)

### ISSUE THREAD

**Issue by laktak** [Microsoft/WSL#1676]
* A brief description

Changing the cursor style in the terminal is very useful in VIM or Bash vi to show what mode you are in. E.g. a beam cursor for insert mode or a block cursor for normal mode.

* Expected results

The cursor should change the style.

* Actual results (with terminal output if applicable)

The cursor style stays as defined by the console window.

* Your Windows build number

15025

* Steps / All commands required to reproduce the error from a brand new installation 

```
# change to block cursor
echo -ne "\e[2 q"
# change to beam cursor
echo -ne "\e[6 q"
```

or for VIM:
```
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
```

* DECSCUSR

```
CSI Ps SP q
          Set cursor style (DECSCUSR, VT520).
            Ps = 0  -> blinking block.
            Ps = 1  -> blinking block (default).
            Ps = 2  -> steady block.
            Ps = 3  -> blinking underline.
            Ps = 4  -> steady underline.
            Ps = 5  -> blinking bar (xterm).
            Ps = 6  -> steady bar (xterm).
```

**Comment by damekr** [comment]
Hi,have you tried use cmder for Bash on Linux? It has plenty of very useful options. This is not answer for your issue, but some workaround :)

**Comment by laktak** [comment]
@damekr cmder is based on ConEmu? It doesn't support this yet either.

**Comment by zadjii-msft** [comment]
Don't you worry, this is already on the backlog. Way, way down on the backlog, but it's there, MSFT:7633943.

Unfortunately, it's pretty low priority, so I doubt it would get done soon :(

**Comment by laktak** [comment]
Thanks for the information. Is there anything we can do to bump the priority?

**Comment by kursion** [comment]
Any chance to have a block cursor in vim ?

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/39201705-a8e991d8-47a4-11e8-8226-207e745e9c38.png)
![image](https://user-images.githubusercontent.com/18356694/39201728-b62c6c94-47a4-11e8-88b5-d331f5062586.png)

Might actually already be in Insiders builds :)

**Comment by sc0ttwad3** [comment]
In addition to @laktak insightful comment, I also found [this discussion on stackexchange](https://unix.stackexchange.com/questions/3759/how-to-stop-cursor-from-blinking) to offer a number of techniques for setting and maintaining one's preferred terminal cursor style (blinking, underline, and block) issues (not specific to vim).

**Comment by therealkenc** [comment]
Right; I didn't check the date on that fixedinsiderbuilds transition on (Apr 24). We have a set of fixedinsiderbuilds tags that are in 1803 and a set that isn't. This one got miscategorized. Appreciated the heads up.
