### ISSUE TITLE
"_runner" Bash on Windows

### ISSUE THREAD

**Issue by Christian-Hill** [Microsoft/WSL#1694]
I am using the latest vs code with bash on windows as my terminal, and trying to use the "_runner": "terminal" in the tasks.json to try and execute my python code directly into the terminal, but upon running this code, I am faced with this message each time:

/bin/bash: /d: No such file or directory
Press any key to close the terminal

or

returned with exit code 1

Not only this but is there a way of getting code to recognize a linter installed on WSL?

I have all the right commands and setting but cannot get this to work, any help much appreciated.

**Comment by benhillis** [comment]
Could you give a bit more detail as to what you're trying to do?  If you're trying to launch a Linux binary form WSL try using bash.exe -c "binary"

**Comment by Christian-Hill** [comment]
I have tried this previously and the command does not transfer to the terminal, hence why I am using the task runner but still no luck?

**Comment by fpqc** [comment]
@Christian-Hill give the following path to the bash executable

`C:\Windows\sysnative\bash.exe" instead of just bash.exe.  There's a thing that is weird because vscode is 32-bit.

**Comment by Christian-Hill** [comment]
I have already done this

**Comment by aseering** [comment]
@Christian-Hill -- could you please copy&paste the full text of the exact command that you are running?

**Comment by aseering** [comment]
Specifically, the exact command using bash.exe -- you will need to call bash.exe explicitly if you want a Windows tool to invoke a Linux binary.

**Comment by Christian-Hill** [comment]
simply
"_runner":"terminal"
and "command" : "python"
with the file name as the argument in the build task

**Comment by aseering** [comment]
How have you configured Bash on Windows as your terminal?  (Sorry, I'm not that familiar with VS Code.  If it has an explicit option in the GUI for "Bash On Windows", then I would encourage asking them on the [VS Code Github page](https://github.com/Microsoft/vscode).)

**Comment by Christian-Hill** [comment]
Yes, it is configured as my terminal and the new runner command should redirect the tasks to the bash terminal to execute code, like the python command to run a python file but I only produces the errors and messages as mentioned above.

**Comment by aseering** [comment]
@Christian-Hill -- thanks for the reply, but that reply did not answer my question.

**Comment by Christian-Hill** [comment]
Bash is configured in the vs code settings to run as the terminal and process all the commands going through vs code

**Comment by aseering** [comment]
Remember that I don't know much about VS Code.  So my question was -- how did you do that?  For example, where is the "Settings" window?  Which settings, precisely, did you set?  And to exactly what values?

If you're willing to take the time, for what it's worth, I've often found that a couple quick screen shots of the settings window can clarify things in a hurry.  Alt-PrintScreen will capture just the current window on Windows, and you can drag'n'drop the resulting screen shot into the GitHub comments box to add the image.

One observation:  The error message in your original post mentions `/d`.  That flag is specific to `cmd.exe`; it tells cmd to skip some registry-related initialization.  The flag is an invalid argument for bash; it is also an invalid argument for python.  You're saying that python works but bash doesn't.  That implies to me that either you are configuring python differently from bash somehow, or VS Code is internally trying to treat python and bash differently and is doing so in a buggy way.

**Comment by Christian-Hill** [comment]
![image](https://cloud.githubusercontent.com/assets/8225835/23587640/bde2ac3e-01a8-11e7-8467-8f2c850e294f.png)
![image](https://cloud.githubusercontent.com/assets/8225835/23587647/d6e8bf52-01a8-11e7-8f36-93f1d150de85.png)
![image](https://cloud.githubusercontent.com/assets/8225835/23587649/e0555348-01a8-11e7-90f8-8ec4482b4f8b.png)

**Comment by benhillis** [comment]
VsCode integration has changed substantially over the last year, please reopen if you continue to have issues.
