### ISSUE TITLE
New User Fails - Error Code 10

### ISSUE THREAD

**Issue by picocms** [Microsoft/WSL#1704]
I am unable to get a user setup.
After install BashOnWindows I got the following error message:
`Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser`

After running the command above I get this error:
```
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: steve
groupadd: cannot open /etc/group
adduser: `/usr/sbin/groupadd -g 1000 steve' returned error code 10. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
```

Windows 10 Pro
OS Build: 14393.693
64-bit

**Comment by benhillis** [comment]
Interesting - I have not seen this before.  It looks like the permissions of your /etc/group file got messed up somehow.  Could you share the output of the below command for me?

`bash.exe -c "ls -al /etc/group"`

Also, does this issue persist if you do a reinstall?
lxrun.exe /uninstall
lxrun.exe /install

**Comment by PGScully** [comment]
I'm getting this, too.  As far as I can tell, it's a problem with mv.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> lxrun /uninstall /full /y
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Uninstalling...
PS C:\WINDOWS\system32> lxrun /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Would you like to set the Ubuntu locale to match the Windows locale (en-AU)?
The default locale is en_US.
Type "y" to continue: y
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: peter
groupadd: failure while writing changes to /etc/group
adduser: `/usr/sbin/groupadd -g 1000 peter' returned error code 10. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
Installation successful!
PS C:\WINDOWS\system32> lxrun /setdefaultuser
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: peter
groupadd: cannot open /etc/group
adduser: `/usr/sbin/groupadd -g 1000 peter' returned error code 10. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
PS C:\WINDOWS\system32>
```

I'm able to start bash, and:
```
groups: cannot find name for group ID 0
root@Lightsong:~# id
uid=0(root) gid=0 groups=0
root@Lightsong:~# pwd
/root
root@Lightsong:~# cd /etc
root@Lightsong:/etc# ls group*
group-  group+
root@Lightsong:/etc# ls -lAsF group*
4 -rw------- 1 root 0 707 Dec 21 21:43 group-
4 -rw-r--r-- 1 root 0 721 Apr  7 13:01 group+
root@Lightsong:/etc# diff group- group+
54a55
> peter:x:1000:
root@Lightsong:/etc# mv group+ group
mv: cannot move 'group+' to a subdirectory of itself, 'group'
root@Lightsong:/etc# mv group\+ group
mv: cannot move 'group+' to a subdirectory of itself, 'group'
root@Lightsong:/etc# cd
root@Lightsong:~# touch file1
root@Lightsong:~# mv file1 file2
mv: cannot move 'file1' to a subdirectory of itself, 'file2'
root@Lightsong:~#
```

**Comment by bftcpa** [comment]
I have the same issues, plus I get an invalid argument error (22) when I run apt-get update and it tries to overwrite the old srcpkgcache.bin and pkgcache.bin files.

**Comment by PGScully** [comment]
@benhillis Is there anything more you need from us?

**Comment by benhillis** [comment]
@PGScully - can you please confirm your build number?  Are you also on Anniversary Update like @picocms?

**Comment by PGScully** [comment]
@benhillis I just now replicated this running Win10 Pro, 1703, 15063.138.  It was also happening with the Anniversary Update, and like @bftcpa apt-get update has been failing for a month or two.

**Comment by bftcpa** [comment]
I have uninstalled and reinstalled 3x, go I avail.  Was able to manually
use cp to copy /etc/groups+ to /etc/groups, and could then set a used (bob)
as the default BASH user, and was able to run apt-get update and apt-get
upgrade, but the next time after setting bob as default user when I ran
apt-get update or apt-get upgrade after making those changes, they both
failed and the issue came resurfaced.  Very frustrating.

**Comment by bftcpa** [comment]
I'm on build 10.0.15063.

So I deleted c:\users\brian\appdata\local\microsoft\lxss, rebooted, then uninstalled the Linux Subsystem for Windows, removed the feature from Windows using the Control Panel/Programs, rebooted, then reinstalled the feature in Windows using Control Panel/Programs, and then did the following at a CMD prompt:

> lxrun /install
> Type "y" to continue: y
> Downloading from the Windows Store... 100%
> Extracting filesystem, this will take a few minutes...
> ^@^[[1;3DPlease create a default UNIX user account. The username does not need to match your Windows username.
> For more information visit: https://aka.ms/wslusers
> Enter new UNIX username: bob
> **groupadd: failure while writing changes to /etc/group
> adduser: `/usr/sbin/groupadd -g 1000 bob' returned error code 10. Exiting.
> Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
> Installation successful!**
> 
**> C:\Users\Brian>lxrun.exe /setdefaultuser bob
> groupadd: cannot open /etc/group
> adduser: `/usr/sbin/groupadd -g 1000 bob' returned error code 10. Exiting.
> Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser**
> 
> C:\Users\Brian>bash
> groups: cannot find name for group ID 0
> root@BFTSurfaceBook:/mnt/c/Users/Brian# cd /etc
> root@BFTSurfaceBook:/etc# cp group+ group
> root@BFTSurfaceBook:/etc# rm group-
> root@BFTSurfaceBook:/etc# rm group+
> root@BFTSurfaceBook:/etc# apt update
> Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
> Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
> Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
> Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [255 kB]
> Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [521 kB]
> Get:6 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [108 kB]
> Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [109 kB]
> Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [55.8 kB]
> Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [210 kB]
> Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [2,748 B]
> Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [459 kB]
> Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [179 kB]
> Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [8,916 B]
> Fetched 2,113 kB in 8s (263 kB/s)
> Reading package lists... Error!
**> E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_main_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
> E: Problem renaming the file /var/cache/apt/srcpkgcache.bin.lQgOvO to /var/cache/apt/srcpkgcache.bin - rename (22: Invalid argument)
> E: Problem renaming the file /var/cache/apt/pkgcache.bin.3tCC7u to /var/cache/apt/pkgcache.bin - rename (22: Invalid argument)
> W: You may want to run apt-get update to correct these problems
> E: The package cache file is corrupted**
> root@BFTSurfaceBook:/etc#

**Comment by msdiniz** [comment]
I'm having this issue too -code 10 and no user created; cannot add user after boot too; mine is Windows 10 Pro build 10.0.14393; language Brazil Portuguese.
Tried to uninstall, as per instructions
```
C:\Windows\system32>lxrun.exe /uninstall
Isso desinstalará o Ubuntu no Windows.
Isso removerá o ambiente Ubuntu, bem como quaisquer modificações e novos aplicativos, exceto:
C:\Users\Marcelo\AppData\Local\lxss\início
C:\Users\Marcelo\AppData\Local\lxss
Raiz
Digite "y" para continuar: y
Desinstalando...
```
But nothing happened; I had to delete lxxx folder by myself.
Any suggestions?

**Comment by djordjen** [comment]
Same thing happening here.
When I try to run: 
**bash.exe -c "ls -al /etc/group"** 

it returns:
**O p e r a t i o n   n o t   s u p p o r t e d . 
P r e s s   a n y   k e y   t o   c o n t i n u e .**

**Comment by brettwhitty** [comment]
I have two machines running Win 10 and have been having this problem on one of them (but frustratingly not the other!!!) since WSL was introduced as beta.

I also happen to use Acronis True Image, and just found this post in their support forum which implicates 'acronis_drive.exe' in causing this issue:
https://forum.acronis.com/forum/acronis-true-image-2017-forum/acronisdriveexe-causes-issues-windows-10-subsystem-linux-bash

Just tried this out myself by ***killing the 'Acronis Drive' background process** that was running on my machine and look what happens:

```
C:\Users\Brett>lxrun /install
...
Enter new UNIX username: brett
groupadd: failure while writing changes to /etc/group
adduser: /usr/sbin/groupadd -g 1000 brett' returned error code 10. Exiting.
Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser
Installation successful!
```

```
C:\Users\Brett>lxrun /uninstall
...
Uninstalling...
```

**Opened Task Manager, Killed 'Acronis Drive' background process**

```
C:\Users\Brett>lxrun /install
...
Enter new UNIX username: brett
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Installation successful!
```
I'm running the Win 10 Pro Insider Preview Build 16251.rs3_release.170721-2122 with Acronis True Image 2017 installed.

**Comment by PGScully** [comment]
I also use Acronis True Image, and remember disabling/unconfiguring a feature I wasn't using, and sometime later retried bash, and it worked.

**Comment by peci1** [comment]
I haven't ever installed Acronis True Image, and still this issue applies to me.

**Comment by dugjohn** [comment]
@brettwhitty - I ended up adding the following to my .bashrc file.  It will then automatically kill the process every time you start the bash shell. 

/mnt/c/./Windows/System32/taskkill.exe /f /IM acronis_drive.exe

**Comment by N0153** [comment]
I tried killing the Acronis Drive process (actually I stopped all Acronis Services and killed all its processes), but to no avail.
The issue still applies to me (Windows 10 Pro 1703 Build:15063.632)

**Comment by claudemartin** [comment]
I had the same problem. `/mnt/c/./Windows/System32/taskkill.exe /f /IM acronis_drive.exe` worked for me. I hope they will fix this so Acronis can be used with Ubuntu.

**Comment by dugjohn** [comment]
@N0153 - When I was originally tracking down this issue, occasionally I needed to do a fresh boot, then stop the process after the reboot.  I haven't quite figured out why that was happening in that scenario.  Most of the time just killing the process worked right away regardless of how long the system had been without a reboot.  But it still happens from time to time.

**Comment by N0153** [comment]
@dugjohn I tested that too, but it hasn't worked. I even tried in Safe Mode (with and without network connection and with just the command prompt), but I only obtained a different error message, probably due to the fact that the feature was disabled in that state. I also tried to disable the readonly permission on the lxss hidden folder (and its subfolders and files), but again with no effect.
Side note: after the latest Acronis True Image update (build 9660) there is no process called "acronis_drive.exe" anymore.

**Comment by heldchen** [comment]
this workaround still works for me: https://github.com/Microsoft/BashOnWindows/issues/2437#issuecomment-325058101
also, the acronis dev seem to be trying to fix the bug.

**Comment by therealkenc** [comment]
`lxrun` is depreciated, and there was never a solid repro for the behaviour. Fingering Acronis True Image. If the problem persists on the April 2018 update (aka RS4 aka 1803 aka 17134) please reboot with a new issue.

**Comment by mascondante** [comment]
If it helps anyone I figured out my issue. It was the AV. [https://imgur.com/h1HGZtf](url)

**Comment by lucubrator** [comment]
I managed to get it to work by completely removing all traces of legacy WSL, updating Windows 10 to 1803, then reinstalling using the Microsoft Store. While doing this I ended all tasks relating to Acronis True Image. I posted [an answer on SO](https://superuser.com/a/1367878/533655) with a detailed step-for-step explanation.

**Comment by Akito13** [comment]
> [https://imgur.com/h1HGZtf](url)

That was my issue, as well. Weirdly, it happened only on 1 of 2 machines, even though both had the exact same set up with the exact same AV. All you have to do is _unblock everything WSL-related for all security components_.
