### ISSUE TITLE
Bash uninstall/install gives error: 0x80080005

### ISSUE THREAD

**Issue by sxu2583** [Microsoft/WSL#1708]
I just download git and was working on a project when Bash started not running my commands. Now when restarting it all there is is a blank screen. So instead I wanted to reinstall but I get an error code.

* Expected results
Reinstall would wipe the bash back to its defaults will keeping my home folder

* Actual results (with terminal output if applicable)
Uninstalling...
Error: 0x80080005

* Your Windows build number
Os Build:  14393.693

* Steps / All commands required to reproduce the error from a brand new installation 

PS C:\WINDOWS\system32> lxrun /uninstall
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications and new applications with the exception of:
C:\Users\shiha\AppData\Local\lxss\home
C:\Users\shiha\AppData\Local\lxss\root
Type "y" to continue: y
Uninstalling...
Error: 0x80080005

**Comment by benhillis** [comment]
Could you try running lxrun.exe /uninstall from an admin command prompt?

**Comment by jcollum-cambia** [comment]
I did a capture and sent it to you @benhillis

**Comment by benhillis** [comment]
@jcollum-cambia - Thanks for the trace.  I have not seen this previously, the only events in the trace are some coming from the LxssManager's ServiceMain method.  I'm seeing a bunch of SERVICE_CONTROL_INTERROGATE controls that I have never seen before.  Looking into this it looks like when our service receives this event we should be responding to SCM, but we currently aren't.  Marking this as a bug so I can get this fixed.

**Comment by jcollum-cambia** [comment]
Progress! Thanks.

**Comment by benhillis** [comment]
This issue has been resolved and lxrun is deprecated.
