### ISSUE TITLE
On BoUoW Antimalware Service Executable goes hot when trying to do an npm install and slows down npm install

### ISSUE THREAD

**Issue by sandeepzgk** [microsoft/WSL#1709]
* Description
I run Bash on administrative mode (to get ping access and other needs for elevation), and recently ive noticed that npm installs takes much much longer than before and trying to investigate it, i couldnt find the root cause but Antimalware service runs hot. Actually it takes more of my CPU than node.

* Expected results
Ideally it should be a smooth running and not taking up so much CPU cycles.

* Actual results (with terminal output if applicable)
![antimalware](https://cloud.githubusercontent.com/assets/274271/23096190/fd804986-f63c-11e6-9423-917c27e89f96.png)

* Your Windows build number
14393.693 / 14.04.5 LTS

* Steps / All commands required to reproduce the error from a brand new installation 
command run: ng new testapp

* Strace of the failing command
runs as expected, but causes other concerns.

* Required packages and commands to install
Node:6.9.5 
NPM: 3.10.10
@angular/cli: 1.0.0-beta.32.3

**Comment by bmayen** [comment]
Try excluding `bash.exe` and `Windows\System32\lxss` from Windows Defender

**Comment by Gabrielcarvfer** [comment]
Same thing happens with Windows installers. Disable Windows Defender real-time protection and try again.

**Comment by heldchen** [comment]
excluding bash.exe / the lxss folder(s) does not help as Windows Defender seems to be scanning the actual processes within BOW (build 15042), for example during some `apt-get install`-postprocessing

**Comment by megakoresh** [comment]
1 year later same issue. Please look into this, there is no Github issues for Windows Defender to post this to.

**Comment by danilaml** [comment]
Can Windows Defender even defend against stuff from WSL? Does it need to? Is there a purpose? Obviously a native linux application can't be a windows virus (though it's probably possible to create one that might try to read/corrupt sensitive info).

**Comment by gaving** [comment]
Anybody out there? My 45 minute yarn install is caused by this. 😭

**Comment by gaving** [comment]
Related:- https://github.com/microsoft/WSL/issues/1932
