### ISSUE TITLE
Compiling latest GIT from source on WSL bash

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/WSL#1711]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I'm trying to build GIT from source code downloaded from [GIT ](https://github.com/git/git/releases/tag/v2.11.1)

* Expected results
Build and installation successful.

* Actual results (with terminal output if applicable)
    SUBDIR git-gui
    SUBDIR gitk-git
    SUBDIR perl
Manifying 8 pod documents
Can't write-open blib/man3/Git::I18N.3pm: Invalid argument at /usr/share/perl/5.22/ExtUtils/Command/MM.pm line 147.
perl.mak:472: recipe for target 'manifypods' failed
make[2]: *** [manifypods] Error 22
Makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:1706: recipe for target 'all' failed
make: *** [all] Error 2

* Your Windows build number
10.0.15031

* Steps / All commands required to reproduce the error from a brand new installation 
make configure
./configure --prefix=/usr
make all doc info

* Strace of the failing command
    SUBDIR git-gui
    SUBDIR gitk-git
    SUBDIR perl
Manifying blib/man3/Git::I18N.3pm
Can't write-open blib/man3/Git::I18N.3pm: Invalid argument at /usr/share/perl/5.18/ExtUtils/Command/MM.pm line 141.
make[2]: *** [manifypods] Error 22
make[1]: *** [all] Error 2
make: *** [all] Error 2

* Required packages and commands to install
dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev
asciidoc xmlto docbook2x

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @n3rd4i -- thanks for reporting this!  I see that you've included a log of the program's output in the "strace" section above.  Would it be possible for you to include an actual strace of the failing command?  You can gather an strace by finding the specific command that causes this error and running `strace -o strace.out.txt -ff <command>`.  This will generate one or more files in the current directory named "strace.out.txt.*"; either find the most-recent interesting unexpectedly-failing syscall, or if you're not sure how to do that, just upload the whole thing and post it.

**Comment by n3rd4i** [comment]
Hello @aseering 
Just to be sure I've created a zip file with all the "strace.out.txt.#" files and the one I believe if most relevant (last one)

[strace.out.txt.229.txt](https://github.com/Microsoft/BashOnWindows/files/785945/strace.out.txt.229.txt)
[strace.out.txt.zip](https://github.com/Microsoft/BashOnWindows/files/785946/strace.out.txt.zip)

Thanks for fast reply.

**Comment by therealkenc** [comment]
```
open("blib/man3/Git::I18N.3pm", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EINVAL (Invalid argument)
```
Colons the in filename again. #1514. You need to build it on VolFS (`/home/you` not `/mnt/c/Users/you`).

Even on VolFS (and I am sure Real Linux™) you'll get a nonfatal warning:
```
user-manual.texi:3202: warning: @ref cross-reference name should not contain `:'
```

**Comment by n3rd4i** [comment]
I've moved the tar content to linux file system and then I worked like a charm.

Thanks for the responses

**Comment by mgiuffrida** [comment]
in terms of steps, `make` is sufficient to repro. +1 for the workaround in #1514 of moving to `/home/me`.
