### ISSUE TITLE
Segfault when debugging multithreaded async-IO process

### ISSUE THREAD

**Issue by aseering** [Microsoft/WSL#1731]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

When I try to debug a nontrivial asynchronous network network app with `gdb`, I find that the app always terminates with a segfault when it receives a connection.  The same application works just fine when it is not being debugged by gdb.

* Steps / All commands required to reproduce the error from a brand new installation 

Reproducer using [Simple-Web-Server](https://github.com/eidheim/Simple-Web-Server):

In one terminal:

```
git clone https://github.com/eidheim/Simple-Web-Server.git
cd Simple-Web-Server
cmake .
make
./http_examples
```

Then, in a second terminal, open up gdb, and tell it to continue (so execution is allowed to proceed):

```
gdb -p $(pgrep http_examples)
c
```

Then, open up a third terminal window and do:

```
curl http://localhost:8080
```

* Expected results

* The `http_examples` binary should serve an HTTP response
* `gdb` should not observe any issues
* `curl` should receive the HTTP response

This is what happens if you skip setting up gdb, and try to download an HTTP response from `http_examples` without debugging it.

* Actual results (with terminal output if applicable)

* `http_examples` segfaults
* `gdb` observes the segfault as a stack trace in boost::asio
* `curl` doesn't get a response

Reading at the code around the segfault, it looks like it's doing something like:

```
epoll_events events[128];
int num_events = epoll_wait(..., events, ...);
for (int i = 0; i < num_events; i++)
{
    ... handle each events[i] ...
}
```

And, while I haven't actually built a Boost with debug symbols, nor dug into the disassembly in much detail, it looks to me like the code is segfaulting when it indexes off the end of `events`.  Which makes me suspicious that `epoll_wait()` is returning something bogus for a process that is being debugged with gdb.

If the cause of this issue is not obvious based on the above information and code inspection on y'all's end, let me know; I can go build a debug Boost with extra debug output or something.

* Your Windows build number

15042

* Strace of the failing command

n/a -- unfortunately, gdb can't debug a process that is already being strace'd.  I've tried to strace gdb itself, but gdb hangs.

* Required packages and commands to install

```
sudo apt-get install build-essential git cmake libboost-all-dev
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by stehufntdev** [comment]
We have some known issues with the ptrace syscall correctly handling signals which is likely related.  Will follow-up to see how that work is coming along.

**Comment by aseering** [comment]
Cool, thanks!  It'd be really useful if this worked.

By the way, I'm impressed that things work well enough these days for me to have hit this in my normal workflow.  (I only noticed this because I've done a bunch of real dev work on nontrivial multi-binary multi-language applications within WSL, and I finally hit a bug in my own code that really wanted me to run gdb with a whole stack running.)

**Comment by therealkenc** [comment]
A big push on `ptrace()` and `gdb` in general (maybe after Creators) would be greatly appreciated. If you're staring at an `EINVAL` or `ENOSYS` it's easy to track a problem. For segfaults and syscalls which succeed but behave incorrectly (like #1326), you're pretty much reduced to caveman debugging. I could probably tell you why VSCode is failing in 20 minutes with a functioning `gdb`. Working on `gdb` will pay dividends beyond just the WSL bug of the day.

**Comment by benhillis** [comment]
@therealkenc - agreed. Ptrace is an invaluable tool for the reasons you stated.  strace and gdb support makes our life much easier.

**Comment by therealkenc** [comment]
Adam's OP test case repros on 17713. Thought I'd get lucky and score an easy close because `gdb` has improved considerably since Feb 2017. But for this one notsomuch.

**Comment by benhillis** [comment]
Should be fixed in [17728](https://github.com/MicrosoftDocs/WSL/releases/tag/17728).
