### ISSUE TITLE
Bash extremely slow in 15046

### ISSUE THREAD

**Issue by thenitai** [Microsoft/WSL#1739]
Bash is extremely slow in the latest build. I'm doing some removal of a directory or even just starting up and switching to the ZSH shell takes well over 6 seconds.

Some examples:

Removing a node_modules directory:
```
#  rm -rf node_modules
0.12s user 13.91s system 84% cpu 16.662s total
0.09s user 3.42s system 115% cpu 3.054s total
0.00s user 0.00s system 0% cpu 3.048s total
0.09s user 3.28s system 120% cpu 2.796s total
```
On Windows removing the SAME directory takes like 4 seconds

Switching to ZSH:
```
3.97s user 4.22s system 121% cpu 6.758s total
0.06s user 3.52s system 118% cpu 3.012s total
```

**Comment by benhillis** [comment]
I've seen cases where node adds some things to .bashrc that really slow us down.  Could you try creating a new user account to see if that is also slow?

close bash.exe
lxrun.exe /setdefaultuser newuser
bash.exe

restore your old user with
lxrun.exe /setdefaultuser oldusername

**Comment by thenitai** [comment]
What kind of "things" does node add? I don't see anything out of the ordinary in .bashrc

**Comment by benhillis** [comment]
I'm not sure if it's node, npm, or nvm but one of them adds a bunch of commands to bashrc.  Would you mind sharing yours out?

**Comment by thenitai** [comment]
```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything

[ -z "$PS1" ] && return


if test -t 1; then
    # ...start zsh
    exec zsh
fi

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi
```

**Comment by bmayen** [comment]
@thenitai, were you not seeing this same slowness in previous versions? Seems the same to me. Which is to say, it's still slow as ever. But slow filesystem IO is a well-known and documented issue with WSL.

**Comment by thenitai** [comment]
@bmayen Bash in previous builds wasn't so slow. Else, I wouldn't waste time to comment on here.

**Comment by sunilmut** [comment]
@thenitai - Thanks for your post. I am not entirely sure if it is your `.bashrc` that is causing the bash launch to be slow. I copied it over to my setup and it didn't seem to affect bash launch at all. But, slow bash launch seems to be documented [elsewhere](https://github.com/davatron5000/can-i-subsystem-it) too. See the section on `nvm`.

**Comment by thenitai** [comment]
I know that it is slower than native. However, as the title says, in the recent two builds it has become even slower. There is no NVM and nothing else running. On Windows side, nothing changed either.

**Comment by benhillis** [comment]
Recent insider builds should have a few changes that make both of these scenarios much faster. If you could retry on a recent Insider build it would be much appreciated.

**Comment by thenitai** [comment]
I'm on the latest builds and honestly, do not see much speed improvements. I mainly use node (node-dev) that watches the file system for changes and it just seems slow (I mean compared to a Mac or Linux machine).

**Comment by liias** [comment]
sdkman also adds two lines to .bashrc which added additional 1-2 seconds for me. Removed it, now is quite instant.

**Comment by thenitai** [comment]
I'm using fish instead of zsh now.  Startup is faster. However, node operation is still quite slow.

**Comment by thenitai** [comment]
Update: I've been using Cmder most of the time. It turns out that thing is extremely slow. I'm working with the "official" shell now. 

Things are faster, but node-dev and all apps that need to watch the file system are still kinda slow.

**Comment by thisguychris** [comment]
I'm on the fast ring Insider build.  just doing `rm-rf` takes 40 seconds, while takes 2seconds on a mac

![slow](https://uoqsga-ch3302.files.1drv.com/y4mPiVNcx2Xsw5aEyAt7yuNLdeiqBD7EGIxEeW0OSA4b71Nn2E4-eH4d13Rzi0AlnvpxLazLzLaMgQAllR4qZ4F9Lvq9Bol5icr-r6QSwn6o5ClkX4SJU1W7EjXP_bOygaJ5wTTruQ2CwSPlbSkMmy5QL2j2VHLkWsXGPygVWrcQs0j9Q_LgxsB2WMmbphD0nHST3KClllrex68Tu-InxHn_g/slow-on-bash.jpg?psid=1)

**Comment by thisguychris** [comment]
I just tried it in a VM, in Ubuntu in VirtualBox, `rm -rf` those 220mb worth of files in node_modules takes sub-second speed, `0.4sec`

so WSL is 100x slow. 😢

**Comment by benhillis** [comment]
@thisguychris - And how long does `rmdir /s /q` take from Windows?

**Comment by thisguychris** [comment]
rmdir /s /q on the node_modules folder?  I had it cloned /home/user and not in mount, since I'm seeing performance regression on /mnt folder?

**Comment by benhillis** [comment]
@thisguychris - yep. Would be interesting to compare Windows versus Mac natively.  Creating and deleting files is something NTFS is not very fast at.

**Comment by thisguychris** [comment]
@benhillis what about win rfs would that bring windows comparable to *nixes?

**Comment by benhillis** [comment]
@thisguychris - The rmdir /s /q command must be run from a windows command prompt, not bash.

**Comment by thisguychris** [comment]
how do you time it? its pretty slow too? maybe 10 to 15 seconds?

**Comment by benhillis** [comment]
`powershell Measure-Command { rm /s /q node_modules }`

**Comment by thisguychris** [comment]
```
Remove-Item : A positional parameter cannot be found that accepts argument '/q'.
At line:1 char:19
+ Measure-Command { rm /s /q node_modules }
+                   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand



Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 122
Ticks             : 1226067
TotalDays         : 1.41905902777778E-06
TotalHours        : 3.40574166666667E-05
TotalMinutes      : 0.002043445
TotalSeconds      : 0.1226067
TotalMilliseconds : 122.6067

```

**Comment by benhillis** [comment]
@thisguychris  - sorry it should be "rmdir"

**Comment by thisguychris** [comment]
```
Remove-Item : A positional parameter cannot be found that accepts argument '/q'.
At line:1 char:19
+ Measure-Command { rmdir /s /q node_modules }
+                   ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand



Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 150
Ticks             : 1500664
TotalDays         : 1.73687962962963E-06
TotalHours        : 4.16851111111111E-05
TotalMinutes      : 0.00250110666666667
TotalSeconds      : 0.1500664
TotalMilliseconds : 150.0664
```

Still getting the error, I timed it though by checking the time. manually, its around 15seconds,

**Comment by therealkenc** [comment]
This was deemed fixininsiders back in Summer 2017. If there are outstanding problems, reboot under a new issue following CONTRIBUTING.md.

**Comment by vatshat** [comment]
Node and WSL don't play nice together! Uninstall anything that has to do with Node on WSL, it makes PAINFULLY SLOW. If you really need it use a VM and spare yourself the headache

**Comment by Nilpo** [comment]
> Node and WSL don't play nice together! Uninstall anything that has to do with Node on WSL, it makes PAINFULLY SLOW. If you really need it use a VM and spare yourself the headache

Actually, I'm running them just fine. What I did find useful was adding the distribution directories to my AV exception list and in Windows Defender.

You can find them under %userprofile%\AppData\Local\Packages. Add the entire app directory as an exception. It even speeds up regular updates and upgrades.

Obviously since this disables real-time scanning, use at your own risk. You may want to drill down and just add the node modules directory.

**Comment by tmilar** [comment]
Solution that worked immediately for me:

> Disabling AMD Radeon graphics driver in the Windows device manager and switching to integrated Intel HD graphics worked for me - for whatever reason.

I keep doing this a few times per year since it seems Windows updates resets this to default... 

(credits: https://stackoverflow.com/a/43762587/6279385)

**Comment by trusktr** [comment]
`rm -rf` is _so slow_ in WSL Bash. Something that takes 1 or 2 seconds on my regular Linux machine takes minutes in WSL Bash.

I really hope this will be improved!

**Comment by Nilpo** [comment]
> `rm -rf` is _so slow_ in WSL Bash. Something that takes 1 or 2 seconds on my regular Linux machine takes minutes in WSL Bash.
> 
> I really hope this will be improved! Linux integration is such a wonderful feature for Windows to have now.

Make sure your files are in a Linux directory and not on a Windows mount.
