### ISSUE TITLE
Copy Files from Windows to the Ubuntu Subsystem

### ISSUE THREAD

**Issue by JordanGS** [Microsoft/WSL#1745]
I have enabled developer mode and installed Bash on Ubuntu on Windows.

My home directory can be found under `%localappdata%\Lxss\home\<ubuntu.username>\`, i have created a sub-directory called Pictures such that the full path should be

on windows: `C:\Users\<windows.username>\AppData\Local\lxss\home\<ubuntu.username>\Pictures`

on bash: `/home/<ubuntu.username>/Pictures`

if i create a file from bash using the command `touch hello.txt` i can freely see this file in the windows UI and copy it to my Desktop. However, if i create a new text file from the windows UI and save it in `C:\Users\<windows.username>\AppData\Local\lxss\home\<ubuntu.username>\Pictures`, even if i restart bash or windows, the file is not visible when i do `ls -l`.

Why can't bash see files created from the Windows side in it's own home directory?

Using `/mnt/c` is not a solution, i am trying to understand why it doesn't see those files and if there is a remedy to that so that it will be able to see UI created files, rather than trying to use the terminal to copy-paste or move files over.

**Comment by tucker973** [comment]
The short answer is don't modify anything in the Linux filesystem (aka `%localappdata%\Lxss\*`). See the following: https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

If you really must read from "within" the filesystem instead of mount, I've found it works rather well to symlink the 'mounted' Windows path. In your case, it would be prudent to do something along the lines of:

`sudo ln -s /mnt/c/Users/<windows.username>/<path-to-pictures>/ ~/Pictures`

**Comment by JordanGS** [comment]
@tucker973 so if i understood that correctly. If i have a folder in windows, say `/mnt/c/Users/Goran/Pictures/myPics`, i can now do any edits from bash on the files in this folder and it should be okay without having data corruption?

**Comment by tucker973** [comment]
Precisely! I can't speak to the intricacies of the filesystem, but that should work properly for you without having to use the longer path. The symlink will behave like any other path in Bash.

**Comment by therealkenc** [comment]
See also #1740. @steveklabnik from that thread is right. This demonstrably needs to be made clearer (and louder) in the [FAQ](https://msdn.microsoft.com/en-us/commandline/wsl/faq), or it is going to be six more months of these after Creator's Update. User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13856379-make-wsl-filesystem-accessible-from-windows).

**Comment by JordanGS** [comment]
@tucker973 @therealkenc thanks, you both saved me a ton of headaches with this.
