### ISSUE TITLE
Missing "/proc/sys/kernel/threads-max"

### ISSUE THREAD

**Issue by aseering** [Microsoft/WSL#1753]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Title says it all.  The aforementioned file is present on Ubuntu 16.04 (probably older versions too?); not in WSL.

The file's behavior and defaults are documented towards the bottom of this file (just search for "threads-max"):

https://www.kernel.org/doc/Documentation/sysctl/kernel.txt

* Expected results

```
$ cat /proc/sys/kernel/threads-max
31481
```

(File should also be writeable.)

* Actual results (with terminal output if applicable)

```
$ cat /proc/sys/kernel/threads-max
cat: /proc/sys/kernel/threads-max: No such file or directory
```

* Your Windows build number

15046

* Steps / All commands required to reproduce the error from a brand new installation 
* Strace of the failing command

Happy to post if you need these.  But I bet you don't :-)

* Required packages and commands to install

None.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
I hit this problem while trying to run the free-with-registration Community Edition of [HP Vertica 8.0](https://my.vertica.com/) on Windows.  Vertica actually crashes rather horribly:

```
$ /opt/vertica/bin/vertica --version
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)
```

Comparing an strace of the binary on Windows/WSL vs Linux, the traces diverge on the following syscall:

```
open("/proc/sys/kernel/threads-max", O_RDONLY) = -1 ENOENT (No such file or directory)
```

(WSL prints the above.  Interestingly, Linux doesn't attempt to open this file at all.  Maybe it's succeeding in learning what it needs from somewhere that doesn't require a syscall?)

It doesn't actually dump core (due to #1754 ), but according to gdb, the crash is occurring in `Util::SysInfo::getLimits()` while attempting to format an error message.  The failing `open()` occurs in the same function.  @bvandiver (hi Ben!) for amusement :-)

**Comment by therealkenc** [comment]
Going through [/proc](http://man7.org/linux/man-pages/man5/proc.5.html) and stubbing implementations would yield a big bang for the buck, development effort wise. `/proc/sys/kernel/threads-max` is a textbook example. `/proc/sys/kernel/shmmax` is another I've hit. So for example, just have `threads-max` return some reasonable number (it is 160267 on my VM). Black hole anything written to it. A real implementation can be done later (maybe _much_ later), but in the mean time, returning something solves a hard fail and moves the ball forward. The real implementation moves the ball across the finish line, but practically speaking, accomplishes much less more greater effort.

**Comment by sunilmut** [comment]
Added
/proc/sys/kernel
- /shmmax
- /shmmni
- /threads-max

**Comment by therealkenc** [comment]
@sunilmut -- this addresses #2080 too if you allow writes to `shmmax`.

**Comment by sunilmut** [comment]
thanks @therealkenc. But, allowing writes through requires more plumbing, for which there is not enough bandwidth in this release cycle. It's still in our backlog though.

**Comment by therealkenc** [comment]
Even a no-op? Proxy `/dev/null`.

**Comment by sunilmut** [comment]
Let me take a look at stubbing write out.

**Comment by sunilmut** [comment]
Hopefully this unblocks few things:

```
root@:/proc/sys/kernel# cat threads-max
32768
root@:/proc/sys/kernel# cat shmmni
4096
root@:/proc/sys/kernel# cat shmmax
4294967295
root@:/proc/sys/kernel# echo 1234 > shmmax
root@:/proc/sys/kernel# cat shmmax
4294967295
root@:/proc/sys/kernel#
```

On my Linux box, `shmmax` is set to something HUGE. Hopefully, the value above is big enough or the apps are not too sensitive about the value here.

```
root@Linux:# cat /proc/sys/kernel/shmmax
18446744073692774399
```

**Comment by therealkenc** [comment]
That's the way. 💯

**Comment by sunilmut** [comment]
This is fixed in Fall Creators Update and any build > [16273](https://msdn.microsoft.com/en-us/commandline/wsl/release-notes#build-16273).
