### ISSUE TITLE
Windows 1607 CJK System not display Lucida Console

### ISSUE THREAD

**Issue by fcharlie** [Microsoft/WSL#1758]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

![snip_20170307230116](https://cloud.githubusercontent.com/assets/6904176/23662279/046a3ffe-038a-11e7-8c27-27daf9c75213.png)

* Expected results

And other font cannot set,

* Actual results (with terminal output if applicable)

* Your Windows build number
10.0.14393

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command
change codepage to 936, change console font to Lucida Console

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**New Arial is a disgusting font**

**Comment by benhillis** [comment]
@fcharlie - Thanks for posting. It doesn't look like this has anything to do with Windows Subsystem for Linux.  Could you please clarify?

**Comment by zadjii-msft** [comment]
@paulcam206 (the font expert)

**Comment by paulcam206** [comment]
This is due to being in codepage 936 - since `Lucida Console` doesn't support codepage 936, we fall back to whatever the system provides.

**Comment by fcharlie** [comment]
@benhillis  This is console bug

**Comment by fcharlie** [comment]
@paulcam206 Since Windows 10.0.14393 update, like Lucia Console, Inziu Iosevka cannot be set to the default font for console, PowerShell, cmd, and other console programs, not including the bash.

No one will like the default font of cmd in CJK system.

In the circle of our programmers, someone came up with the questions：

[Windows cmd why fonts look ugly?](https://www.zhihu.com/question/55272504)

**Comment by be5invis** [comment]
Lucida Console is not suitable for CJK, because it is TOO WIDE.
Yes, too wide.
You would see ideographs being stretched.

**Comment by fcharlie** [comment]
@be5invis Now, I replace all Console Font to Iosevka

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing. If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
