### ISSUE TITLE
On the fly *nix path translation

### ISSUE THREAD

**Issue by Swoorup** [Microsoft/WSL#1773]
When launching a win32 executable, Is it possible to translate, nix path to windows path? `/mnt/c` to `C:`

This is how msys2 and cygwin I think supports it.

**Comment by fpqc** [comment]
actually I experimented a bit and support was actually quite poor.

**Comment by benhillis** [comment]
wslpath was added in 1803.

**Comment by Swoorup** [comment]
Is there any documentation on using wslpath?

```
-h
/? 
--help 
```

None of the args work

**Comment by onomatopellan** [comment]
@Swoorup They are aware of that. Meanwhile you can read the [Release Notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046).
