### ISSUE TITLE
Network Connectivity

### ISSUE THREAD

**Issue by rptr94** [Microsoft/WSL#1784]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
**_Impossible to update/install packges via wired connection. Only wireless._**
* Expected results

* Actual results (with terminal output if applicable)

* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@rptr94 - Thanks for the post. Can you please fill up the additional fields in the above template? Especially, which Windows build you are on (you can find that out using the `ver` command). Also, can you paste your `/etc/hosts` file here?

**Comment by rptr94** [comment]
![aaa](https://cloud.githubusercontent.com/assets/26417019/24061174/42f61394-0b4e-11e7-823c-9a2313810e70.png)
done. now, neither wired neither wireless (i already reeinstall several times)

**Comment by sunilmut** [comment]
@rptr94 - Thanks. Still need the Windows build number. Can you please share that as well? Paste the output of the the Windows `ver` command.

Also, strace of a failing network access command. Example:
`strace -o <trace_file> -ff curl www.microsoft.com`

And share the `trace_file`

**Comment by rptr94** [comment]
No problem, the build number is: _**Microsoft Windows [Version 10.0.14393]**_
the  "strace -o <trace_file> -ff curl www.microsoft.com" totally freezes.

**Comment by sunilmut** [comment]
@rptr94 - Thanks for the info. I think the command would have still generated the trace files. Anyways, see if you are running into #475? Do you have a firewall or AV software installed on your box?

**Comment by rptr94** [comment]
i have two files but i cant upload. 
Yes i have bitdefender.

**Comment by sunilmut** [comment]
See, if upgrading bitdefender helps. Or, try disabling it.

**Comment by rptr94** [comment]
Nop, no sucess...

**Comment by sunilmut** [comment]
Just to be sure, the following sequence does not work?

1. disabling bitdefender
2. reboot
3. bash, `wget www.microsoft.com`

**Comment by tara-raj** [comment]
Please try this again on a more recent build and reopen if you still hit this issue
