### ISSUE TITLE
Pooltag information

### ISSUE THREAD

**Issue by dmex** [microsoft/WSL#1786]
Hello,

Is there a reason the pooltag.txt file doesn't have the tag names, binary names or descriptions for pool allocations by the WSL kernel mode driver(s)?

For example:
"C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\triage\pooltag.txt"
"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\triage\pooltag.txt"

Expected results:
http://i.imgur.com/tPLeRHG.png
http://i.imgur.com/7jg2FLu.png

Actual results:
http://i.imgur.com/Dns1r9Z.png
http://i.imgur.com/cIhOMhN.png

Microsoft programs are also affected:
* Windows Performance Recorder
* Poolmon -g
* Windbg !poolused

This is really a cosmetic issue more than actual bug considering you can also always identify the driver using a kernel debugger but it does save time identifying components with memory leaks (especially on servers where installing debuggers or even rebooting can be nearly impossible).

Thanks,
dmex

**Comment by jackchammons** [comment]
@dmex Which version of Windows are you running? Run `ver` in CMD.

**Comment by benhillis** [comment]
Sorry for the delay, following up with the debuggers team to see what we need to add here.
