### ISSUE TITLE
Question: Can't set home directory to mnt/c/.../somefolder. Tried everything. Help?

### ISSUE THREAD

**Issue by MostafaOkasha** [Microsoft/WSL#1793]
Basically, every-time I run Bash I don't want to have to cd to a specific directory in my mnt/c that I want to use as my home directory where I can easily interact with it through windows. Is there a way to change the settings so that every-time I run Bash I am automatically taken to that directory? Thanks!

**Comment by MostafaOkasha** [comment]
I tried adding cd mnt/c/.../somefolder to the end of my .bashrc file but to no success.

**Comment by iz0eyj** [comment]
It would not be a bad idea, especially for people like me who uses a mixed environment GUI Win + Xfce.

**Comment by benhillis** [comment]
Usermod allows you to do this:

```
usermod -m -d /mnt/c/foo username
cp -r /home/username /mnt/c/foo
```

Keep in mind, this will effectively make home a DrvFs location, which may cause issues due to it not fully emulating the Linux file system (like LxFs).
