### ISSUE TITLE
Make ssh-agent private keys comptaible with WinSCP and similar software

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1796]
I suggest with much humbleness to make private keys loaded to ssh-agent accessible to WinSCP (and other similar software) as it would release users from having to convert keys to ppk and storing extra files (Putty bundle and at least 2 keys for root and usual user in the same dir). 

This would result in more minimal and comfortable desktops and will ease WinSCP developers in making it compatible with WSL as well.

**Comment by SRGOM** [comment]
Very cool suggestion but I think this functionality may create security nightmares if baked in. 

It's technically already available if you are willing to do some heavy lifting- 

We have  https://github.com/xilun/cbwin to run a windows program from WSL.

Modify your ssh-agent program to run use cbwin to launch pagent (putty-agent?) with the right credentials.

**Comment by lilred** [comment]
@Benosika, I would suggest updating your title to reflect the nature of your feature request!

**Comment by Benosika** [comment]
Done.

**Comment by fpqc** [comment]
I just wanted to let you know: the Win32-openssh project of the powershell team does integrate into the native Windows keyring for single sign-on. It was actually pretty annoying for them to rewrite the whole backend of openssh to support this integration with the Win32 crypto API. 

This idea is a nonstarter for WSL. You'd be better off asking the PuTTY and WinSCP guys to support the openssh key format.

**Comment by tjmidnight** [comment]
Nevermind the fact that the openssh key format is the standard format and ppk is not.
