### ISSUE TITLE
POSIX permissions on DrvFs as per Services for UNIX

### ISSUE THREAD

**Issue by billziss-gh** [Microsoft/WSL#1799]
## Brief description

Currently POSIX permissions do not seem to be supported on DrvFs. For example, the `chmod` command does not seem to work. POSIX permissions should be supported on DrvFs and they should be compatible with Microsoft Services for UNIX (SFU) and Cygwin.

https://technet.microsoft.com/en-us/library/bb463216.aspx

## Expected results

From Cygwin (which supports the SFU standard for POSIX permissions):

    billziss@windows:~$ touch foobar
    billziss@windows:~$ ls -l foobar
    -rw-r--r--+ 1 billziss None 0 Mar 22 12:25 foobar
    billziss@windows:~$ cacls foobar /S
    C:\Users\billziss\foobar "D:P(D;;WPDTRC;;;S-1-0-0)(A;;0x1f019f;;;S-1-5-21-XXXX-1001)(D;;WP;;;SY)(D;;WP;;;BA)(A;;FR;;;S-1-5-21-XXXX-513)(A;;0x1201bf;;;SY)(A;;0x1201bf;;;BA)(A;;FR;;;WD)"

    billziss@windows:~$ chmod 770 foobar
    billziss@windows:~$ ls -l foobar
    -rwxrwx---+ 1 billziss None 0 Mar 22 12:25 foobar
    billziss@windows:~$ cacls foobar /S
    C:\Users\billziss\foobar "D:P(D;;SWRPWPDTRC;;;S-1-0-0)(A;;FA;;;S-1-5-21-XXXX-1001)(A;;0x1201bf;;;S-1-5-21-XXXX-513)(A;;0x1201bf;;;SY)(A;;0x1201bf;;;BA)(A;;0x120080;;;WD)"

    billziss@windows:~$ rm foobar
    billziss@windows:~$ pwd -P
    /cygdrive/c/Users/billziss

## Actual results (with terminal output if applicable)

From WSL bash:

    billziss@WINDOWS:/mnt/c/Users/billziss$ touch foobar
    billziss@WINDOWS:/mnt/c/Users/billziss$ ls -l foobar
    -rwxrwxrwx 1 root root 0 Mar 22 12:27 foobar
    billziss@WINDOWS:/mnt/c/Users/billziss$ chmod 770 foobar
    billziss@WINDOWS:/mnt/c/Users/billziss$ ls -l foobar
    -rwxrwxrwx 1 root root 0 Mar 22 12:27 foobar
    billziss@WINDOWS:/mnt/c/Users/billziss$ rm foobar
    billziss@WINDOWS:/mnt/c/Users/billziss$ pwd -P
    /mnt/c/Users/billziss

Running `cacls` on this file from a different prompt:

    billziss@windows:~$ cacls foobar /S
    C:\Users\billziss\foobar "D:(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;S-1-5-21-XXXX-1001)"

## Windows build number

14393

**Comment by billziss-gh** [comment]
Ping @github-cygwin who may have an interest in this.

**Comment by rustyx** [comment]
Neither do UNIX permissions work when you mount an NTFS partition inside a real Linux.

Please please don't re-implement the Cygwin ACL rewriting approach, it screws up everything! It's horrible.

**Comment by billziss-gh** [comment]
> Please please don't re-implement the Cygwin ACL rewriting approach, it screws up everything! It's horrible.

@rustyx can you please explain how it is horrible? Can you provide a better alternative?

**Comment by rustyx** [comment]
The Cygwin ACLs is a hack, there's no other way to call it. From the official [cygwin docs](https://cygwin.com/cygwin-ug-net/ntsec.html):

> _Unfortunately the security tab in the file properties dialog of the Windows Explorer insists to rearrange the order of the ACEs to canonical order before you can read them. Thank God, the sort order remains unchanged if one presses the Cancel button. But don't even think of pressing OK..._

Or [this](https://cygwin.com/ml/cygwin/2016-02/msg00158.html):

> > > _They are not supposed to be modifiable in Explorer.  If you want to change permissions on a Cygwin ACL, use chmod or setfacl._
> >
> > Is this a joke?
> 
> _No._
> 

So it's not really _interoperating_ with Windows ACL, it's taking it over.

Also don't forget the poor souls who end up with unchangeable [cygwin 000 permissions](http://stackoverflow.com/questions/5828037/cygwin-sets-file-permission-to-000) as soon as the ACL becomes just slightly complicated, and any attempt to `chmod` it making the ACL unchangeable in Windows as well.

I'm not suggesting to not do anything, I'm just saying don't do it _this_ way.

**Comment by billziss-gh** [comment]
[Disclaimer: I am not affiliated with Cygwin other than as a user, despite the Cygwin badge on my GitHub profile.]

I think there are a few issues here:

1. Services for UNIX (SFU) uses Windows ACL's to simulate POSIX permissions. Cygwin implements the SFU mechanism.
2. Cygwin "extends" the SFU mechanism to store bits like setuid/setgid in ACL's.
3. Cygwin also uses Windows ACL's to simulate POSIX ACL's.

To clarify I am only asking for (1).

> The Cygwin ACLs is a hack, there's no other way to call it.

I think the issue is subtle. I do not agree that taken as a whole Cygwin's use of ACL's is a hack. However I do agree that there are some aspects of Cygwin's use of ACL's that could be considered a hack (point (2) above).

Regarding point (2): you can read my sentiments in the post below where I effectively say that Cygwin subverts the Windows ACL mechanism to store permissions bits that it should not:
http://cygwin.1069669.n5.nabble.com/POSIX-permission-mapping-and-NULL-SIDs-td127833.html

> From the official cygwin docs:
> 
> Unfortunately the security tab in the file properties dialog of the Windows Explorer insists to rearrange the order of the ACEs to canonical order before you can read them. Thank God, the sort order remains unchanged if one presses the Cancel button. But don't even think of pressing OK...

Microsoft has effectively defined a standard for ACL's within their OS. That standard allows for ACL's like the ones that SFU and Cygwin create. [I note here that SFU was a Microsoft product.] While it is a fact that Windows Explorer does not always work well with those ACL's, this is a failing of Explorer and not SFU or Cygwin.

It could be argued that if Explorer does not support those ACL's well, then they should be considered "discouraged". I am sympathetic to that view. Implementations often create de-facto standards and Windows Explorer is one of the most widely used implementations in existence.

OTOH it could also be argued that Windows Explorer can be fixed to support all legal ACL's and that Microsoft may have an incentive to do so if they decide to implement POSIX permissions as per SFU (and this issue).

**Comment by tara-raj** [comment]
Please see the changes that were made in [Insiders Build 17063](https://docs.microsoft.com/en-us/windows/wsl/install-win10) in DrvFS to support additional Linux metadata

**Comment by billziss-gh** [comment]
@tara-raj  thanks for you response. Your link takes me to an installation guide, but I was able to find the release notes here:

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063

From the link above:

> DrvFs supports additional Linux metadata. This allows setting the owner and mode of files using chmod/chown, and also the creation of special files such as fifos, unix sockets and device files. This is disabled by default for now since it's still experimental. Note: We fixed a bug in the metadata format used by DrvFs. While metadata works on this build for experimentation, future builds will not correctly read metadata created by this build. You might need to manually update owner for modified files and devices with a custom device ID will have to be recreated.

Unfortunately it is not explained how this metadata is being stored. Furthermore the term "metadata" leads me to believe that it may not be using ACL's like Cygwin and Microsoft' own past products (SFU).

Microsoft may of course implement file metadata any way it sees fit. However I am unclear on what the resolution of this issue is.
