### ISSUE TITLE
Trying to run XFCE4 on WSL 

### ISSUE THREAD

**Issue by ar94952** [Microsoft/WSL#1800]
I'm trying to run XFCE on Windows Subsystem Linux, but I get this:

```
user@DESKTOP-0ARM9IQ:~$ xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
user@DESKTOP-0ARM9IQ:~$
```

VcXsrv is installed and running - set to full screen
Xubuntu installed and updated

What am I doing wrong?

**Comment by SRGOM** [comment]
I think it's unfair to the WSL team (and their target audience) to file bugs related to graphical applications at this stage * when they have explicitly stated that this project is for command line developers.

* Hopefully forever. I hope they stay focussed on the CLI aspects

**Comment by iz0eyj** [comment]
@ar94952:
export DISPLAY=:0.0
startxfce4

You can also configure VcXsrv with Multiple windows to obtain a mixed desktop.

**Comment by iz0eyj** [comment]
@SRGOM:
What I remember the team has always said that the graphics are not a priority, but I do not remember any post in which it was said not to use it and/or do not post problems highlighted by it.
Instead, I have seen many posts of team members within thread regarding graphics applications, browser, desktop manager etc etc.
I am to have lost something? of course this is possible.
I would also say that both developers and the super user / admin now use graphics applications and then it becomes really difficult to separate the problems of ordinary users from those of developers.

**Comment by therealkenc** [comment]
Yes, but it has to be a _WSL issue_. There many other groups for getting information about running X11 remotely to VcXsrv on Linux. Or running X11 apps with CONFIG_DRM=n. Otherwise this github repository becomes a Linux troubleshooting group. The label here is linux-behavior, not feature. `xfce4` runs fine on WSL.

**Comment by aseering** [comment]
So, I can't speak for the WSL team, but I would very much advocate that people be allowed and encouraged to post here about WSL bugs/limitations that affect any application, graphical or otherwise.  The WSL team may not prioritize some bugs :-)  But if, say, Firefox depends on some file in`/proc`, I for one want to at least know that the file is missing and useful.

I would draw some lines, though:  I don't think, for example, that this is the best place to ask for support for VcXsrv :-)  VcXsrv is a third-party Windows app.  Some people here do use it, but if you really want help setting it up, I would ask on a VcXsrv forum.  Or on a public forum (one of the StackOverflows, maybe?), where there are probably many more VcXsrv users.

If you find a bug in WSL's TCP implementation that's breaking X11 applications (which has happened in the past), that would be a good thing to post about here, I think.  Such a post should include TCP dumps or a small standalone Linux sockets app that reproduces the issue, or something else more technically specific.

Regardless -- we do seem to have answered the OP's question :-)

**Comment by iz0eyj** [comment]
@therealkenc:
I think that they intended to report a bug on Xfce start

**Comment by iz0eyj** [comment]
There is also to say that the use of graphic software involves a considerable workload for the machines, and often the API call is not widely used.
This allows you to identify bugs and limitations that difficult to emerge with the use of only the console software.
I believe that the intention is to provide a layer for the complete execution of ELF-64, or at least as close as possible to it, not a layer that performs some things and not others.

**Comment by ar94952** [comment]
workload isn't the issue.  i have a massive pc that can handle 2 assasins creed game at once...  

I was doing a bit of digging and Win10 WSL isn't fully developed and I just have to remind everyone that even if we are running Linux user interface directly on top of NT kernel, some hardware may not be supported....

**Comment by JuergenKosel** [comment]
Hello,

beside xfce4 you need to install some kind of X11 server.
For example you could install xvnc4server or xrdp.
If you have installed xrdp and started it, than you could connect with the Windows Remote-Desktop Application to the X11 server on localhost.
If your Windows PC is already running a Remote-Desktop Server, than you need to specify another port for xrdp.

Greetings
 Juergen

**Comment by therealkenc** [comment]
Merging into #637 hangout.

**Comment by Toninoso** [comment]
Run your VcxXsrv and look at the window title.
It will likely say "VcXsrv Server - Display:MACHINENAME:0.0"
In WSL bash run: xfce4-session --display=MACHINENAME:0.0
Optionally put that line in bashrc

**Comment by Dansheng** [comment]
> @ar94952:
> export DISPLAY=:0.0
> startxfce4

It works! Thanks for your help!

**Comment by YosefBayoude** [comment]
Anyone still facing this issue, I found one solution, don't know why or how...
To solve it go to Powershell and type :
`wsl -l -v` if you have version 2, the goal is to change it to v. 1

To do so type :
` wsl --set-version <distro> 1` replace `<distro>` with the name you had in `wsl -l`
More [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)

**Comment by adityapatnaik** [comment]
After doing this:
```
export DISPLAY=:0.0
startxfce4
```
it gives this
```
/usr/bin/startxfce4: X server already running on display :0.0
xrdb: Connection refused
xrdb: Can't open display ':0.0'
Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```
Any help?

**Comment by ARunningPig** [comment]
> After doing this:
> 
> ```
> export DISPLAY=:0.0
> startxfce4
> ```
> 
> it gives this
> 
> ```
> /usr/bin/startxfce4: X server already running on display :0.0
> xrdb: Connection refused
> xrdb: Can't open display ':0.0'
> Unable to init server: Could not connect: Connection refused
> xfce4-session: Cannot open display: .
> Type 'xfce4-session --help' for usage.
> ```
> 
> Any help?

I get the same error

**Comment by cppdvl** [comment]
> > After doing this:
> > ```
> > export DISPLAY=:0.0
> > startxfce4
> > ```
> > 
> > 
> > it gives this
> > ```
> > /usr/bin/startxfce4: X server already running on display :0.0
> > xrdb: Connection refused
> > xrdb: Can't open display ':0.0'
> > Unable to init server: Could not connect: Connection refused
> > xfce4-session: Cannot open display: .
> > Type 'xfce4-session --help' for usage.
> > ```
> > 
> > 
> > Any help?
> 
> I get the same error

export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1

rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex. 
and you know sw eng love to do this harder.

**Comment by zepang** [comment]
> > > After doing this:
> > > ```
> > > export DISPLAY=:0.0
> > > startxfce4
> > > ```
> > > 
> > > 
> > > it gives this
> > > ```
> > > /usr/bin/startxfce4: X server already running on display :0.0
> > > xrdb: Connection refused
> > > xrdb: Can't open display ':0.0'
> > > Unable to init server: Could not connect: Connection refused
> > > xfce4-session: Cannot open display: .
> > > Type 'xfce4-session --help' for usage.
> > > ```
> > > 
> > > 
> > > Any help?
> > 
> > 
> > I get the same error
> 
> export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
> export LIBGL_ALWAYS_INDIRECT=1
> 
> rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex.
> and you know sw eng love to do this harder.

I running it on wsl2 according to your configuration, but I got the following logs:
```
/usr/bin/startxfce4: X server already running on display 172.30.80.1:0
xrdb: Connection timed out
xrdb: Can't open display '172.30.80.1:0'
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```

**Comment by Anurag-117** [comment]
> export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0

THIS WORKS!!

**Comment by candianatan** [comment]
I found a possible solution. In my case I just checked the "Disable access control" option from the XLaunch settings and now it works.
![image](https://user-images.githubusercontent.com/55251304/96376352-e1506700-1154-11eb-8fe8-48d5bd6f6ab0.png)

**Comment by AlphonsGwatimba** [comment]
> I found a possible solution. In my case I just checked the "Disable access control" option from the XLaunch settings and now it works.
> ![image](https://user-images.githubusercontent.com/55251304/96376352-e1506700-1154-11eb-8fe8-48d5bd6f6ab0.png)

This worked, thank you for replying to this post

**Comment by matthieudesprez** [comment]
If all above solutions didn't work, think also about you windows firewall settings, if when prompted for the first time by your X server application you didn't enable public network, WSL won't be able to connect to it.

You can edit those settings afterward going Windows + R > wf.msc > Inbound Rules > VcXsrv (or Xming or whatever is you X server) > and allow public.

Note that it's not super safety to allow all public traffic to access your X servser, I have found a more grained solution here : https://github.com/cascadium/wsl-windows-toolbar-launcher/blob/master/README.md#troubleshooting

**Comment by jonnyasmar** [comment]
Thank you @matthieudesprez ! That did it for me.

**Comment by hyoretsu** [comment]
> > > After doing this:
> > > ```
> > > export DISPLAY=:0.0
> > > startxfce4
> > > ```
> > > 
> > > 
> > > it gives this
> > > ```
> > > /usr/bin/startxfce4: X server already running on display :0.0
> > > xrdb: Connection refused
> > > xrdb: Can't open display ':0.0'
> > > Unable to init server: Could not connect: Connection refused
> > > xfce4-session: Cannot open display: .
> > > Type 'xfce4-session --help' for usage.
> > > ```
> > > 
> > > 
> > > Any help?
> > 
> > 
> > I get the same error
> 
> export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
> export LIBGL_ALWAYS_INDIRECT=1
> 
> rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex.
> and you know sw eng love to do this harder.

For whoever gets here. This man is a god and this works, at least with VcXsrv

**Comment by pavlidic** [comment]
> 
> 
> > > > After doing this:
> > > > ```
> > > > export DISPLAY=:0.0
> > > > startxfce4
> > > > ```
> > > > 
> > > > 
> > > > it gives this
> > > > ```
> > > > /usr/bin/startxfce4: X server already running on display :0.0
> > > > xrdb: Connection refused
> > > > xrdb: Can't open display ':0.0'
> > > > Unable to init server: Could not connect: Connection refused
> > > > xfce4-session: Cannot open display: .
> > > > Type 'xfce4-session --help' for usage.
> > > > ```
> > > > 
> > > > 
> > > > Any help?
> > > 
> > > 
> > > I get the same error
> > 
> > 
> > export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
> > export LIBGL_ALWAYS_INDIRECT=1
> > rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex.
> > and you know sw eng love to do this harder.
> 
> I running it on wsl2 according to your configuration, but I got the following logs:
> 
> ```
> /usr/bin/startxfce4: X server already running on display 172.30.80.1:0
> xrdb: Connection timed out
> xrdb: Can't open display '172.30.80.1:0'
> xfce4-session: Cannot open display: .
> Type 'xfce4-session --help' for usage.
> ```

Did you find a solution?

**Comment by venimus** [comment]
> > > > > After doing this:
> > > > > ```
> > > > > export DISPLAY=:0.0
> > > > > startxfce4
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > it gives this
> > > > > ```
> > > > > /usr/bin/startxfce4: X server already running on display :0.0
> > > > > xrdb: Connection refused
> > > > > xrdb: Can't open display ':0.0'
> > > > > Unable to init server: Could not connect: Connection refused
> > > > > xfce4-session: Cannot open display: .
> > > > > Type 'xfce4-session --help' for usage.
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Any help?
> > > > 
> > > > 
> > > > I get the same error
> > > 
> > > 
> > > export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
> > > export LIBGL_ALWAYS_INDIRECT=1
> > > rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex.
> > > and you know sw eng love to do this harder.
> > 
> > 
> > I running it on wsl2 according to your configuration, but I got the following logs:
> > ```
> > /usr/bin/startxfce4: X server already running on display 172.30.80.1:0
> > xrdb: Connection timed out
> > xrdb: Can't open display '172.30.80.1:0'
> > xfce4-session: Cannot open display: .
> > Type 'xfce4-session --help' for usage.
> > ```
> 
> Did you find a solution?

Try using `exec startxfce4`

**Comment by frenchiveruti** [comment]
Hello, I come here after running wls2 solution, `xfce-session` no longer says "connection refused" but instead now it just "does nothing", no output or anything.
![imagen](https://user-images.githubusercontent.com/1095997/124385414-df5f1180-dcab-11eb-9be8-864206021e9d.png)

I ran the commands here because I was trying to find a solution, but I don't know how to "roll" them back.  
https://bbs.archlinux.org/viewtopic.php?pid=1696492#p1696492

**Comment by frenchiveruti** [comment]
It was the firewall inbound rules.  
Is there a way to specify it so it doesn't open my network to the whole internet?

**Comment by frenchiveruti** [comment]
Ok I managed to open the xfce4-session just one time and now I'm getting this error:
![imagen](https://user-images.githubusercontent.com/1095997/124386298-2c44e700-dcb0-11eb-8d66-54227cf7c4c0.png)

**Comment by Kuo-TingKai** [comment]
> > > After doing this:
> > > ```
> > > export DISPLAY=:0.0
> > > startxfce4
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it gives this
> > > ```
> > > /usr/bin/startxfce4: X server already running on display :0.0
> > > xrdb: Connection refused
> > > xrdb: Can't open display ':0.0'
> > > Unable to init server: Could not connect: Connection refused
> > > xfce4-session: Cannot open display: .
> > > Type 'xfce4-session --help' for usage.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Any help?
> > 
> > 
> > I get the same error
> 
> export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0 export LIBGL_ALWAYS_INDIRECT=1
> 
> rather than the simpler export DISPLAY:=0.0, why? WSL2 networking is more complex. and you know sw eng love to do this harder.

It works! 
Thanks a lot!

**Comment by LiamKarlMitchell** [comment]
Could not figure out on display 0 but got it to run

~/xfce
```sh
#!/usr/bin/sh
Xwayland :1 &
xw_pid=$!
WAYLAND_DISPLAY= DISPLAY=:1 dbus-launch startxfce4
kill $xw_pid
```

```
./xfce
```

<img width="627" height="297" alt="Image" src="https://github.com/user-attachments/assets/2d082065-c7d5-41ea-9a91-d4f801453412" />
