### ISSUE TITLE
Wireshark fails to open socket

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/WSL#1802]
A friend (system administrator) has told me of the problems of the network analyzer Wireshark.
I installed it to test and this is the result:
The command line reports the following error:

```
federico@Bestia:~$ sudo wireshark
Failed to connect to generic netlink.
```
![cattura](https://cloud.githubusercontent.com/assets/6331284/24244720/5df1052a-0fc0-11e7-9055-698b89307c7d.JPG)
The build of the Win 10 is 15063

**Comment by jackchammons** [comment]
@iz0eyj please edit your issue to include the items mentioned in our [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)

**Comment by Samsongff** [comment]
I am still facing this exact problem, and https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar is no longer a valid link...

**Comment by Vinayak312019** [comment]
Have an issue with http port caturing
