### ISSUE TITLE
POSIX filenames and invalid characters on DrvFs

### ISSUE THREAD

**Issue by billziss-gh** [Microsoft/WSL#1804]
## A brief description

POSIX allows all characters in filenames except `/` and `\0`. However WSL follows Windows guidelines on DrvFs and cannot create filenames that contain any of the NTFS invalid characters:  `< > : " / \ | ? *` or those with values in the range `[0, 31]`.

POSIX filenames should be fully supported. This should be done in a backwards compatible manner as this has been done before by Cygwin and (I believe?) by Services for UNIX: https://www.cygwin.com/cygwin-ug-net/using-specialnames.html

[NOTE: despite my GitHub badge I am not affiliated with Cygwin other than as a user.]

I am aware of #1514.

## Expected results

From a Cygwin prompt:

    billziss@windows:~$ touch CON
    billziss@windows:~$ ls -l CON
    -rw-r--r--+ 1 billziss None 0 Mar 23 10:51 CON
    billziss@windows:~$ rm CON
    billziss@windows:~$ touch C:
    billziss@windows:~$ ls -l C:
    -rw-r--r--+ 1 billziss None 0 Mar 23 10:51 C:
    billziss@windows:~$ rm C:

## Actual results (with terminal output if applicable)

From a WSL prompt (on DrvFs):

    billziss@WINDOWS:/mnt/c/Users/billziss$ touch CON
    billziss@WINDOWS:/mnt/c/Users/billziss$ ls -l CON
    -rwxrwxrwx 1 root root 0 Mar 23 10:48 CON
    billziss@WINDOWS:/mnt/c/Users/billziss$ rm CON
    billziss@WINDOWS:/mnt/c/Users/billziss$ touch C:
    touch: setting times of ‘C:’: No such file or directory

## Your Windows build number

14393

**Comment by therealkenc** [comment]
Same as #1514

**Comment by billziss-gh** [comment]
@therealkenc thanks.

I am aware of #1514. However this issue is specifically about using the same filename mapping as Cygwin (and SFU?).

**Comment by billziss-gh** [comment]
Is there an actual resolution to this?

**Comment by benhillis** [comment]
@billziss-gh - Yes. Judging by the duplicate item linked this is fixed in 1803.
