### ISSUE TITLE
Bash does not remember my password (for some time)

### ISSUE THREAD

**Issue by aurimus** [Microsoft/WSL#1808]
On Ubuntu, I expect bash to remember my sudo password for some time (minutes).

I have to type it in wsl all the time.

Windows version: 1607, 14393.1066

**Comment by aseering** [comment]
Hi @aurimus -- `sudo` remembers my password just fine in WSL.  Perhaps you have something misconfigured somehow?  Ubuntu's sudo tracks login information in `/var/run/sudo/ts`; perhaps something is wrong there?

(To be precise:  `bash` doesn't remember your password.  WSL just runs the `sudo` binary provided by Ubuntu.  `sudo` doesn't remember your password, either, but it does remember when you last typed in your password, and if you did so recently enough, it has permission to let you log in without a password.)

**Comment by aurimus** [comment]
@aseering hm... everything default really.

**Comment by benhillis** [comment]
This is 100% handled by usermode Ubuntu bits.  You should be able to increase the timeout by following these instructions: https://itsfoss.com/change-sudo-password-timeout-ubuntu/

**Comment by aurimus** [comment]
I think it works, thanks.

**Comment by aurimus** [comment]
Actually, after setting the required params from the guide, it still doesn't work :/ I checked the file and it's saved correctly, so it must be something wrong with WSL

**Comment by therealkenc** [comment]
Works here. In the OP it appears the sudo password isn't being held _at all_; so changing default timeout (which is five minutes) wouldn't have any effect. I can't speculate on how you got in that state, but like Ben was saying the feature isn't handled by WSL (the kernel).
