### ISSUE TITLE
much /proc/sys/net/* missing

### ISSUE THREAD

**Issue by lscgzwd** [microsoft/WSL#1809]
root@LUSHUNCHENG:/mnt/c/Windows/System32# sysctl -p
sysctl: cannot stat /proc/sys/net/unix/max_dgram_qlen: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_mem: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_wmem: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_rmem: No such file or directory
sysctl: cannot stat /proc/sys/net/core/wmem_default: No such file or directory
sysctl: cannot stat /proc/sys/net/core/rmem_default: No such file or directory
sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory
sysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_syncookies: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_max_syn_backlog: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_synack_retries: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_syn_retries: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_fin_timeout: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_keepalive_time: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_reuse: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/ip_local_port_range: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_max_tw_buckets: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/route/max_size: No such file or directory

**Comment by aseering** [comment]
Hi @lscgzwd -- You're correct in some sense that `sysctl` is not supported:  First, sysctl.conf is not loaded at boot because WSL does not boot (not in the traditional sense at least).  Second, many files under `/proc` have not yet been implemented, so you can't set those things yet.  However, some have been implemented (more in recent [Insider builds](https://insider.windows.com)), and I imagine (though I haven't tested) that you could manage any that have been implemented using `sysctl`.

**Comment by lscgzwd** [comment]
Thanks for you answer, I'm already have the latest build.

**Comment by therealkenc** [comment]
No come on. Repro is `cat /proc/sys/net/ipv4/max_dgram_qlen` etc. They all need to be [stubbed](https://github.com/Microsoft/WSL/issues/1006#issuecomment-292677564). This blocks all manner of networking things.
