### ISSUE TITLE
socket can't bind to 255.255.255.255

### ISSUE THREAD

**Issue by scriptkitz** [microsoft/WSL#1816]
socket can't bind to "255.255.255.255"

**Comment by benhillis** [comment]
Hi @scriptkitz - thanks for posting. Can you please provide some more context? Also, when filing issues please try to follow our [contribution instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md).

**Comment by scriptkitz** [comment]
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
>>> s.bind(("255.255.255.255",0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address



In real linux,  work fine!

**Comment by scriptkitz** [comment]
@benhillis

**Comment by therealkenc** [comment]
For the sake of getting this closed, by-design.
```
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("255.255.255.255")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
```
Rehash of [this](https://serverfault.com/questions/72112/how-to-alter-the-global-broadcast-address-255-255-255-255-behavior-on-windows/72152#72152). I should have spoke up last year.

**Comment by therealkenc** [comment]
The OP ask takes on WSL2.

![image](https://user-images.githubusercontent.com/7049700/90660161-69200080-e1fa-11ea-9f2b-b5420a5a493d.png)
