### ISSUE TITLE
syscall( SYS__sysctl, &args ) return -1;

### ISSUE THREAD

**Issue by scriptkitz** [microsoft/WSL#1818]
int varName[] = { CTL_NET, NET_CORE,
			(optname == SO_RCVBUF) ? NET_CORE_RMEM_MAX : NET_CORE_WMEM_MAX };
	int varValue;
	size_t varLength = sizeof(varValue);

	struct __sysctl_args args;
	args.name = varName;
	args.nlen = sizeof(varName) / sizeof(varName[0]);
	args.oldval = &varValue;
	args.oldlenp = &varLength;
	args.newval = NULL;
	args.newlen = 0;

	int error = syscall( SYS__sysctl, &args );

**Comment by aseering** [comment]
Hi @scriptkitz -- thanks for posting a bunch of specific technical issues.  Are you hitting these while trying to run a particular application?  Or are you just playing around?  In general could you please fill out a little more of the issue template?

The WSL team is well aware that WSL isn't complete yet :-)  They have a long ToDo list; it will surely take them years to finish everything on it.  Many of those things are rarely used; some are much more commonly used.  The immediately interesting question is therefore not "what is broken?", but rather "which thing should get fixed next?"

**Comment by rustyx** [comment]
This is about sysctl net.core.rmem_max and net.core.wmem_max.
Bad news: none of net.* sysctls seem to be supported. So this is a feature request (for which application?)

**Comment by therealkenc** [comment]
Would have bet a fiver this was going to be a close by-design. From [`sysctl(2)`](https://man7.org/linux/man-pages/man2/sysctl.2.html):
```
       Use of this system call was long discouraged: since Linux 2.6.24,
       uses of this system call result in warnings in the kernel log, and in
       Linux 5.5, the system call was finally removed.  Use the /proc/sys
       interface instead.
````

Nevertheless:

![image](https://user-images.githubusercontent.com/7049700/93963673-abb18d00-fd12-11ea-9278-7c7f31448721.png)

So:

![image](https://user-images.githubusercontent.com/7049700/93963759-e61b2a00-fd12-11ea-924f-c51bfa88d1d4.png)

Fixed-in-wsl2. Until it isn't.
