### ISSUE TITLE
How to copy files over to use in Bash 

### ISSUE THREAD

**Issue by tapotter2** [Microsoft/WSL#1830]
I am moving C files from my school's server to my computer and I put the file in \mnt\c. How do I get to root and open in Bash so that I can see and modify these files?

**Comment by aseering** [comment]
Hi @tapotter2 -- `\mnt\c` is not a valid Linux path.  Did you mean either `/mnt/c` or `C:\`?

If you want to get to that directory in Linux, simply type `cd /mnt/c`.  If you want to get to that directory in Windows, open up File Explorer and type `C:\` into the path bar at the top of the window.  You will not need Linux root permissions to edit the files.

If you need Windows Administrator permissions to edit the files, then you will need to launch bash as a Windows Administrator to do that.  But it would be better if you put the files somewhere, such as your Windows home directory, that doesn't require Windows Administrator permissions to modify.

If that's not what you are trying to do, could you clarify what you are trying to do?

**Comment by tapotter2** [comment]
Okay Yes that is what I meant, I am sorry. But thank you I found where I need to go but now it is saying that permission is denied does that mean that I need to run as Admin?

**Comment by mateusmedeiros** [comment]
@tapotter2 You probably don't have permission to edit files on C: (which is the usual). 

In that case, you need to close all bash instances and open it as administrator, or else anything inside the linux subsystem will fail with permission denied when trying to modify the file.

It's usually recommended though that you move those files to some folder under `C:\Users\YourUser`. Inside that folder, your user has write permissions even without elevating to Administrator, which means that bash and anything you open from there will be able to modify the files without you having to open bash as Administrator.

**Comment by tapotter2** [comment]
Got it thanks
