### ISSUE TITLE
bash crashed when download Ubuntu from store

### ISSUE THREAD

**Issue by cokkiy** [Microsoft/WSL#1833]
Bash window auto closed when download Ubuntu from App Store at 10% or more.

My windows version is 1607, 14393.953 64bit

**Comment by aseering** [comment]
Hi @cokkiy , thanks for posting!  Could you try the following:

* Open a Windows command prompt
* Type `bash.exe`

This should cause bash to try to install again.  If it fails, it should print some error/debug output.  In that case, could you copy&paste that output here?

**Comment by cokkiy** [comment]
It's said network error after some period of time when start downloading. Maybe no mirror or CDN in China cause this problem. It's spend too long to download.
But every time I restart, It's always start from the beginning. It's can't resume from the break point.

**Comment by jackchammons** [comment]
@cokkiy Could you grab some traces for us? Follow step 9 on our [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)

**Comment by benhillis** [comment]
Distributions are now downloaded via the Microsoft Store.
