### ISSUE TITLE
Convert Unix path to Windows path in a custom function?

### ISSUE THREAD

**Issue by JacobDB** [Microsoft/WSL#1834]
I'm trying to write an "open" function that opens a given directory in File Explorer, but I'm running in to a semi-major issue. Specifying paths to explorer.exe is a pain, because it doesn't accept relative paths (you can enter `explorer.exe example-folder`, but not `explorer.exe example-folder/test`).

My idea is to take a given Unix path, expand it to it's full path, and then convert it to a Windows path to pass to explorer.exe. For example, `open ../example-folder` may expand to `open /mnt/c/Users/Jacob/example-folder`, which would get converted to `C:\Users\Jacob\example-folder` and passed to explorer.exe.

I see in some cases Bash on Windows says something along the lines of "Could not convert to Windows path, using C:\Users\Jacob instead." Clearly there must be some function that converts Unix paths to Windows paths; is this something I could access in a shell script, or would I need to write my own custom logic to achieve this?

**Comment by fpqc** [comment]
@JacobDB Yeah, you could probably write a tool that translates it out.

**Comment by JacobDB** [comment]
@fpqc ah, alright, thanks. I'll try and write my own.

**Comment by fpqc** [comment]
@JacobDB Make sure you write it so it only works for /mnt though.  If you try to edit files in lxfs from windows, it will break.

**Comment by benhillis** [comment]
Such functionality exists in our driver for translating the %PATH% environment variable and current working directories but it isn't exposed via a documented API.  I have a work item on my plate to look into exposing this via a documented API both for NT callers and WSL callers.

It should be simple to do something that does a simple string translation, I think there's actually a script on this GitHub that already does that.  Where things get interesting is dealing with case-sensitivity etc.

**Comment by JacobDB** [comment]
@fpqc I mean, it'd probably work like it does now in those cases, so I'm not too concerned about that. I'll try and built that in though, thanks.

@benhillis that's awesome to hear, will try and keep an eye out for that :) Do you know what I would search to find that script you mentioned?

**Comment by benhillis** [comment]
Shoutout to @aseering - https://gist.github.com/aseering/a06219e74c7f96ccea5ec65d5b2483b5

**Comment by JacobDB** [comment]
@benhillis fantastic, thanks much :)

**Comment by fpqc** [comment]
@JacobDB I think you might need the inverse transformation though.

**Comment by JacobDB** [comment]
@fpqc yea, you're right. I was able to get it figured out though!

https://gist.github.com/JacobDB/e71e22c3663175b2369211aeb54362fe

Only remaining thing for this is that I'd like `~` to work like it does on Unix, pointing to `%HOMEPATH%` on Windows. Will try and sort that out tonight. Thanks for the info guys, it was really helpful!

**Comment by JacobDB** [comment]
Ugh, I'm stuck on this last thing, mapping `~` to `/mnt/c/Users/[username]/`. You can see the progress I've made in [my gist](https://gist.github.com/JacobDB/e71e22c3663175b2369211aeb54362fe) (lines 8-11), but I just can't finalize it for some reason. Everything I try with the variable at the end of the `sed`, it either outputs nothing, removes the slashes, doesn't change at all, or outputs the variable name...

Would appreciate some help getting this last little thing sorted!

**Comment by JacobDB** [comment]
Got it figured out! I was hitting a weird issue with CMD outputting Windows-style line endings I guess; I kind of assumed that WSL would take care of that conversion, but I guess it makes sense that it doesn't. Anyway, final code:

https://gist.github.com/JacobDB/e71e22c3663175b2369211aeb54362fe

**Comment by zerocool4u2** [comment]
there is a project called outbash, https://github.com/xilun/cbwin basically you call outbash  and this one handles bash and cmd, this allows you to use 3 new commands. wstart wcmd and wrun, for example I have an alias "subl" for "wstart subl" this calls subl like in cmd and translate the path, I can use "subl ." now and many others working as expected.
Currently I have ConEmu calling Outbash calling Bash for several months and works pretty well, when wsl has their own implementation of current path translation as arguments it would be nice to let outbash go, for conemu just waiting for a fix on the fonts to return the stock terminal :P

**Comment by fpqc** [comment]
@zerocool4u2 it's not being maintained anymore because it's integrated in wsl with the interop functionality.

**Comment by darealshinji** [comment]
Here's a script that works similar to cygpath, which means it will convert `/home` to `C:\Users\<USER>\AppData\Local\lxss\home`, and so on:
https://gist.github.com/darealshinji/61d97abf462c1dff9c582f3d94e16c58

**Comment by darealshinji** [comment]
Can we assume that the path to the Linux filesystem stuff will remain being `%LOCALAPPDATA%/lxss` and not change in future? Because I haven't figured out any way to obtain that path (i.e. reg.exe, or via `/proc` or `/sys`). But if it won't change `cmd.exe /C echo %LOCALAPPDATA%\\lxss 2>/dev/null | tr -d '\r'` can be used to get it.
I guess the content of `/proc/mounts` can then be used to figure out which sub-directory of `%LOCALAPPDATA%/lxss` is mounted where within `/`.
And the Windows drives will always be mounted with the lowercase letter in `/mnt` (`D:\` -> `/mnt/d/`)?

**Comment by Brian-Perkins** [comment]
Windows Insider Build 17046 contains new 'wslpath' functionality that supports path translations. See the [release notes](https://github.com/MicrosoftDocs/WSL/releases/tag/17046) for more details.

**Comment by DDoSolitary** [comment]
@Brian-Perkins Hello, I couldn't find it on build 17093. Has it been removed?

**Comment by Brian-Perkins** [comment]
It should be at /bin/wslpath. It is created on startup by init (currently as a symlink to /init).

**Comment by RichardBronosky** [comment]
`wslpath` is a real time saver. Thanks @Microsoft! Here are a few things to go along with it:

    # Assuming ~/bin is in your $PATH (default for Ubuntu), but you may need to create the directory
    mkdir -p ~/bin

    # Make where.exe (like `which` in linux) easy to find/use
    ln -s /mnt/c/Windows/System32/where.exe ~/bin/where

    # Run a windows executable without knowing its exact path
    cat > ~/bin/wrun <<EOF
    #!/bin/bash
    $(wslpath $(where "$@") | sed 's/\r//')
    EOF

    # Unfortunately, most Windows executables output `\r\n` line separators. `der` (or de-r) is a handy tool to strip them
    cat > ~/bin/der <<EOF
    sed 's/\r//'
    EOF

**Comment by MathiasBaumgartinger** [comment]
For anyone interested, i created a small python script which can open any path (file/directory) from the WSL: https://gist.github.com/MathiasBaumgartinger/1f607cbf75203bd47c9fb0713741cf15

**Comment by darealshinji** [comment]
@MathiasBaumgartinger That inspired me to quickly write a wrapper around the wslpath command in C: https://gist.github.com/darealshinji/ac17471848c57438f772c4808dec019e

**Comment by darealshinji** [comment]
Did some tests and wslpath seems to do only some very simple path conversions:

A Unix path inside the "virtual" root filesystem is translated to a network address and vice versa:
i.e. "/usr" will be resolved as "\\wsl$\${WSL_DISTRO_NAME}\usr" with ${WSL_DISTRO_NAME} being set as an environment variable (i.e. "Ubuntu");
if ${WSL_DISTRO_NAME} is empty the path will be "\\wsl$\\usr";
a path inside "/" is checked if it exists, an address under "\\wsl$\" is resolved even if it doesn't exists.

Anything inside a Windows partition label such as "C:\" is translated as being mounted inside "/mnt/":
i.e. "C:\Windows" will be resolved as "/mnt/c/Windows" and vice versa (path must exist)

The actual location of "/" is at "%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs".

wslpath, is a symbolic link to "/init", a statically linked binary that appears to be built as a C++ program compiled with Clang. It also checks the virtual filesystem on "/sys" (I think) if interoparability is supported and enabled by the kernel. I cannot find any source code for "/init" though (closed-source?).
