### ISSUE TITLE
Ejecting ReFS drive during bash running cause BSOD.

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#1835]
* A brief description
Referencing ReFS volume after ejected that drive, cause BSOD.
It does not happen on NTFS.

* Expected results
Only I/O error.

* Actual results (with terminal output if applicable)
Stop error with random stop code.

* Your Windows build number
Microsoft Windows [Version 10.0.15063]

* Steps / All commands required to reproduce the error from a brand new installation 
1. Close all bash.
2. Connect ReFS formatted drive, or format a drive to ReFS.
3. Lanuch bash.
4. Eject by Safely Remove Hardware, or re-format that drive, or disconnect drive any way.
5. In bash, ``$ while true; do df; done``

* Strace of the failing command

* Required packages and commands to install
None.

I already send mail to secure@microsoft.com on February 03, but the reply is not a vulnerability. This bug has not been fixed yet.

**Comment by fpqc** [comment]
@0xbadfca11 I think when you send to secure@microsoft.com, you need to attn: ben hillis or someone else on the WSL team.

**Comment by jackchammons** [comment]
@0xbadfca11 This is definetely something that we'd like to take a look at. Please resend your email to secure@microsoft.com and Ben Hillis and the WSL team mentioned.
