### ISSUE TITLE
rpm --initdb always segfault if there’s no existing databases

### ISSUE THREAD

**Issue by ytrezq** [Microsoft/WSL#1846]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* Actual results (with terminal output if applicable)
core dump
* Your Windows build number
10.0.14393.447
* Steps / All commands required to reproduce the error from a brand new installation 
install rpm with an rpm based distribution *(not the default shipped ubuntu)* and create `/var/lib/rpm` as root.
Then just create an empty database with `rpm --initdb`
* Strace of the failing command
due to #1148 I can’t use the strace command.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  #1148 shouldn't impact strace, can you please clarify that part?  Also, could you give this a try in the Creator's update since there have been a number of fixes since the Anniversary build including #1148.

**Comment by ytrezq** [comment]
@stehufntdev : In fedora, all executables are address independant, so this impact strace.
I confirm this affect`10.0.16232`. I also confirm I can no longer install strace because of this.

**Comment by mscraigloewen** [comment]
Can you please try this on a more recent build and re-open if you still hit this issue. Thanks!

**Comment by therealkenc** [comment]
The OP was running an unsupported distribution (Fedora) which is why this one went chirping crickets. The problem is almost certainly variation "mmap's problems" and will likely suffer in current releases like ref #3493.
