### ISSUE TITLE
Please document error codes of bash.exe

### ISSUE THREAD

**Issue by ytrezq** [Microsoft/WSL#1848]
Ok, I recognize this might not be a bug, but what does the`0x8007054f` error code stand for when running `C:\Windows\System32\bash.exe ~` ? How to fix it ?

More generally, would it be possible to know each kind error code corresponds to like with Windows® blue screens ?

**Comment by poizan42** [comment]
0x8007054f is HRESULT_FROM_WIN32(ERROR_INTERNAL_ERROR), which has the description "An internal error occurred.". The error codes are standard HRESULT values. You can read about their structure [here](https://msdn.microsoft.com/en-us/library/cc231198.aspx). Specifically if it is of the form 0x8007xxxx then it encodes a win32 "system" error, you can find the list of those [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681381(v=vs.85).aspx).

Of course in the case the error is quite useless, I think there might be a log somewhere that says something a bit more in depth.

**Comment by ytrezq** [comment]
It happened after overwriting some files in`/lib64`with rpm -Uvh. All opened programs crashed.
I looked in lxss/rootfs/lib64 and I saw nothing special…

As you know, simply copying files in the hidden`lxss`directory doesn’t make them appear in bash. Where is stored the index of files recognized by bash on Windows ?

**Comment by poizan42** [comment]
@ytrezq it's not an index... The files needs some NTFS Extended Attributes, see https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

**Comment by ytrezq** [comment]
@poizan42 : so only the extended attributes are neeeded ?

**Comment by MikeGitb** [comment]
@ytrezq: In short, we are not supposed to copy/ modify any files in the lxss directory with windows tools, including the windows explorer. Any reason you can't use bash's own tools for whatever you are trying?

**Comment by ytrezq** [comment]
@MikeGitb : `Any reason you can't use bash's own tools for whatever you are trying?`
As far I know,`%systemroot%\system32\bash.exe`is the only way to start a Linux program, isn’t it ?
I have lot files in $HOME, reinstalling would probably mean loosing unix permissions on my personal files : something I can’t do.

**Comment by SRGOM** [comment]
`Error: 0x8007054f `

From: https://www.variantweb.net/blog/running-fedora-on-windows-10-using-wsl/ a commenter claims that this happens when you copy & paste the rootfs files instead of moving or cut-pasting them. 

I faced it myself and I did copy-paste stuff. So this may be treu.

**Comment by chx** [comment]
Note: even `robocopy` will break lxss. D'oh.

**Comment by mscraigloewen** [comment]
We've made many improvements to error reporting which produces strings along with the codes. Hopefully that helps with your issue
