### ISSUE TITLE
ioctl(0,TIOCSTI,"...") fails w/ ENOTTY

### ISSUE THREAD

**Issue by dvorka** [Microsoft/WSL#1863]
* A brief description

I use `ioctl()` function with `TIOCSTI` to send commands to terminal in C. In particular it's used
by an utility improving use of `history` in Bash - https://github.com/dvorka/hstr 

* Expected results

Command - `ioctl()` 3rd parameter content - should be passed to terminal's stdin.

* Actual results (with terminal output if applicable)

I get error (-1) from `ioctl()` and `errno` (25) set to `ENOTTY`.

* Your Windows build number

14393.953

* Steps / All commands required to reproduce the error from a brand new installation 

Save C source code below as `test.c` (I intentionally left commented various devices I tried):
```
#include <stdio.h>
#include <sys/ioctl.h>
#include <errno.h>
#include <fcntl.h>

int main(int argc, char *argv[])
{
  //int fd = 0;
  //int fd = open("/dev/pts/0", O_WRONLY);
  //int fd = open("/dev/tty1", O_WRONLY|O_NONBLOCK);
  //int fd = open("/dev/stdin", O_WRONLY|O_NONBLOCK);

 int a,c;
 for (a=1, c=0; a< argc; c=0 ) {
    while(argv[a][c]) {
        int error=ioctl(0, TIOCSTI, &argv[a][c++]);
        if(error) {
          printf("%d >>> %d\n",error,errno);
        }
    }
    if (++a < argc) {
      ioctl(0, TIOCSTI," ");
    }
  }

  //close(fd);
  return 0;
}
```
Compile it:
```
gcc -o test test.c
```
Run it:
```
./test ls
```

* Strace of the failing command

Program doesn't fail - instead of printing command to terminal it does nothing - reports error described above:
```
-1 >>> 25
-1 >>> 25
```

**Comment by aseering** [comment]
Hi @dvorka -- I haven't had a chance to try this myself yet, but I would be curious whether this is fixed in the recently-released Creators update (build 15063).  I know a lot of other console (and other) issues have been fixed in the update.

You can download the update here:

https://www.microsoft.com/en-us/software-download/windows10ISO

Alternatively, it will supposedly be released via Windows Update next Tuesday.

**Comment by therealkenc** [comment]
This one hasn't come up before. I thought that ioctl had been abandoned decades ago. Best I can tell there isn't even an [LTP](https://github.com/linux-test-project/ltp) test case for it. So props for providing one. Anyway, `strace` on 15063 below for the pedantry of it; though it just shows exactly what the OP was saying. 
```
open("/dev/tty1", O_WRONLY|O_NONBLOCK)  = 3
ioctl(0, TIOCSTI, "l")                  = -1 ENOTTY (Inappropriate ioctl for device)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
brk(NULL)                               = 0xfc1000
brk(0xfe2000)                           = 0xfe2000
write(1, "-1 >>> 25\n", 10)             = 10
ioctl(0, TIOCSTI, "s")                  = -1 ENOTTY (Inappropriate ioctl for device)
write(1, "-1 >>> 25\n", 10)             = 10
exit_group(0)                           = ?
```
Works on Real Linux, natch.

**Comment by dvorka** [comment]
Thank you  @therealkenc for adding `strace`! 

Ad `ioctl`: true, however, IMO its use is mainly discouraged for new user/kernel space calls (simplest way, but obviously difficult to maintain) - specific protocols to be written instead (and used IF exist). AFAIK there is no other way/protocol to do what I need. **If there is a better and portable solution - passing input to terminal - please let me know and I will be happy to use it.**. I just need [hstr](https://github.com/dvorka/hstr#installation) to work across Linux distributions (+MacOS and +Cygwin)... and add Bash@Windows. Bash@Windows specific solution would help as well (conditional compilation).

**Comment by dvorka** [comment]
@aseering thank you for quick response! Ad console fixes - it's a great news. I will let you know as soon as I do the test.

**Comment by therealkenc** [comment]
@dvorka -  My `strace` above is on Creators (aka 15063) so unfortunately you won't find joy on this specific issue there. I thought for five minutes about a "better and portable solution" when I wrote that abandoned quip, and should have conceded I don't have one. No solution that doesn't resort to extreme measures, anyway, and even then I'd be hand-waving. You've obviously put considerable thought into the problem. The WSL guys will have to look to see what it will take to add support for `TIOCSTI`. Maybe it won't be too bad. At least you've put it on the books, and that's great. Clever package, by the way.

**Comment by dvorka** [comment]
@therealkenc thank you for testing it on Creators, your comments and thinking about a workaround!

**Comment by dvorka** [comment]
For anybody who might be interested - you may find workaround for `ioctl()/TIOCSTI` in https://github.com/dvorka/hstr/issues/186.

**Comment by rickywu** [comment]
Any update for this issue?

**Comment by Matheus-Garbelini** [comment]
????? we need this urgent

**Comment by Matheus-Garbelini** [comment]
@Brian-Perkins oh my god thank you so much, I was almost with no hope :-)

**Comment by filimonic** [comment]
So this is not working in 
Linux DESKTOP-OSK7EIM 4.4.0-17763-Microsoft #1-Microsoft Fri Sep 14 14:34:00 PST 2018 x86_64 GNU/Linux

**Comment by therealkenc** [comment]
> So this is not working in ... 17763

This got a 'fixedininsiders' tag in 17713 ( < 17763) so be best to spawn a new issue# with the specifics; notably a do-over of the test case in the OP with `/dev/ttyS?` (if that is what you are doing).  _Whatever_ was deemed fixed here shipped in 1809 aka 17763, so we'll call whatever you are experiencing "new".

**Comment by rickywu** [comment]
I use https://github.com/junegunn/fzf to complete bash history and files/folders etc.., much better
