### ISSUE TITLE
scp from WSL SSH tunnel deletes /mnt/c

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1868]
My build is 10.0.14393 and my c drive's file system is NTFS and I think I found a bug:

I SSH tunnel to my VPS from WSL. Now, if I scp to `/mnt/c/`, it is being deleted. The very act of using cp or scp in `/mnt/c/` seems to make it to be deleted.

Rebooting Windows itself doesn't help in getting it back but rebooting WSL with a simple `reboot` command does brings back `/mnt/c`. Yet, the scp part of the following crucial command set deletes it the moment it is done from my VPS:

	(
	cd /var/www/html
	mysqldump -u root --password --all-databases > ./db.sql
	zip -r ./html.zip ./
	cp db.sql html.zip /mnt/c/Users/USER/Desktop # Verify path!
	rm ./html.zip ./db.sql
	)

**Comment by bitcrazed** [comment]
I think you're misunderstanding - when you ssh into a remote machine, you're operating as if logged into the remote machine.

This is why, when you, for example, `ls /mnt/`, you should see `No such file or directory` - this is correct, because your remote server has no C: drive mounting.

**Comment by Benosika** [comment]
Okay even then, it raises 2 questions:

1. Why would the action actually make /mnt/c to be deleted?

2. How than one could download files from its VPS to Windwos when tunneled from WSL?

**Comment by Benosika** [comment]
I now saw you answered in a QA session regarding backuping via WSL I opened in StackEchange:

https://superuser.com/questions/1195927/windows-subsystem-for-linux-how-to-download-document-root-and-database-backups/1198087?noredirect=1#comment1741877_1198087
