### ISSUE TITLE
DISPLAY for X11

### ISSUE THREAD

**Issue by luismoralesphysics** [Microsoft/WSL#187]
export DISPLAY=:0.0

is what have to do so that ROOT.Cern would launch X11 visual.

**Comment by kazi11** [comment]
This does not work for me. Can't seem to launch `xeyes` as a test despite having X11 installed and both `export DISPLAY=:0.0` and `export DISPLAY=:0` do not work. I just get the standard error:

```
root@localhost:~# export DISPLAY=:0.0
root@localhost:~# xeyes
Error: Can't open display: :0.0
```

I also get this error when trying to check my x11-apps install:

```
root@localhost:~# apt install x11-apps
Reading package lists... Done
Building dependency tree
Reading state information... Done
x11-apps is already the newest version.
x11-apps set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)
Setting up modemmanager (1.0.0-2ubuntu1.1) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
invoke-rc.d: unknown initscript, /etc/init.d/modemmanager not found.
runlevel:/var/run/utmp: No such file or directory
dpkg: error processing package modemmanager (--configure):
 subprocess installed post-installation script returned error exit status 100
Setting up whoopsie (0.2.24.6ubuntu2) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
invoke-rc.d: unknown initscript, /etc/init.d/whoopsie not found.
runlevel:/var/run/utmp: No such file or directory
dpkg: error processing package whoopsie (--configure):
 subprocess installed post-installation script returned error exit status 100
Errors were encountered while processing:
 modemmanager
 whoopsie
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Aneurin** [comment]
What X server are you using? If it's Cygwin's, you will need to run it with `-listen tcp` as TCP connections are disabled by default.

**Comment by luismoralesphysics** [comment]
I am using the windows Xming. I get it to work and display things and it works for a bit, but it then freezes up.

**Comment by xarthurx** [comment]
@Aneurin 
Do you know why emacs cannot be resized?
For other gui apps like galculator, if I resize the window, the interface will be resized.
But for emacs, if I resize the border of the window, there will be a blank space between the original emacs and the new border, the content of emacs will not be resized...

![unnamed qq screenshot20160614171750](https://cloud.githubusercontent.com/assets/1921878/16060079/00b70b60-3254-11e6-8e57-b6d987b1e9e0.png)

**Comment by aseering** [comment]
Ooh, that's farther than I get.  When I run `emacs`, I get a window that looks like your screen shot above, except with a blank white box where you have the main buffer and the minibuffer.  The process appears to have gone into an infinite loop with the following `strace`:

```
(...)
poll([{fd=3, events=POLLIN}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\1\1m1\0\0\0\0\22\0\240\0\0\0\0\0\1\0\0\0\200\4\0\0P\373\210\2\4\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7fffc0a12c70, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7fffc0a12c70, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7fffc0a12c80, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{"+\0\1\0", 4}, {NULL, 0}, {"", 0}], 3) = 4
poll([{fd=3, events=POLLIN}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\1\1n1\0\0\0\0\22\0\240\0\0\0\0\0\1\0\0\0\200\4\0\0P\373\210\2\4\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7fffc0a12c40, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7fffc0a12c40, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{"+\0\1\0", 4}, {NULL, 0}, {"", 0}], 3) = 4
poll([{fd=3, events=POLLIN}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\1\1o1\0\0\0\0\22\0\240\0\0\0\0\0\1\0\0\0\200\4\0\0P\373\210\2\4\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7fffc0a12c70, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7fffc0a12c70, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7fffc0a12c80, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=3, revents=POLLOUT}])
(...)
```

**Comment by keynan** [comment]
Ditto the blank emacs window, I think this might just be emacs not getting along with Xming though. I imagine that a native X Server might be a big as, but please MS, can has?

**Comment by JuergenKosel** [comment]
Hello,

I was successfull to connect xterm with cygwin X11 Server as follows:

start X11 Server in cygwin shell:
 `startxwin -- -listen tcp`

In cygwin xterm allow X11 Connections from localhost:
 `xhost +localhost`

In ubuntu bash start xterm:
 `export DISPLAY=localhost:0`
 `xterm`

**Comment by ssokolow** [comment]
Another option to be aware of is VcXsrv.

https://sourceforge.net/projects/vcxsrv/

**Comment by JuergenKosel** [comment]
Hello,

I have found a way to run X11 / xfce4 without outside (cygwin or other) X11 server:
```
sudo apt-get install xrdp xfce4
sudo /etc/init.d/xrdp restart

```
Then connect to the X11 / xfce session on localhost with the remote desktop client, which is already installed in Windows.
Maybe you need to reconfigure the port used by xrdp to avoid collision with the remote desktop server of Windows.

**Comment by mizzao** [comment]
For anyone who stumbled upon @xarthurx's problem, emacs 24 and later resizes properly (emacs 23 doesn't).

**Comment by therealkenc** [comment]
This discussion is pretty stale, and has morphed from "what have to do so that ROOT.Cern would launch X11 visual" and "`Error: Can't open display: :0.0`" to an X11 emacs problem thread. Going to close out as having run its course, but if anyone out there who runs X11 emacs regularly and finds any issues with WSL _that differs_ from running launching graphic emacs on Real Linux remotely to VcXsrv/Xming/xrdp/Xwhatever, do open a new issue# because it might be bugworthy as opposed to just discussion.
