### ISSUE TITLE
lxrun /uninstall /full quiet fails

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/WSL#1875]
I ran the `lxrun /uninstall /full` command, and all I saw was this:

```
C:\WINDOWS\system32>lxrun /uninstall /full
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
```

Followed by a normal prompt.

It turns out, I had an explorer window open and pointing to the `lxss` folder, and the uninstall had quietly failed without an error message.

I tried it again after closing the explorer window, and the console output is actually identical to a failed uninstall, so I'd suggest two minor changes:

1. Confirm with a success error-message at the end of uninstall.
2. Fail with an error status-code and display an error message.

Note that this happened on a system that does not yet have the Creators update - I was preparing to tear down my current UOW so I can get a fresh one after upgrading. I can't say if this works differently in the latest version.

**Comment by benhillis** [comment]
lxrun.exe is deprecated.
