### ISSUE TITLE
Cannot install windows subsystem for linux, error code: 0x800F0831

### ISSUE THREAD

**Issue by inondle** [microsoft/WSL#1888]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I've tried turning on the subsystem but every time it gives me the same error code and prompts me to reboot my computer. Rebooting doesn't help or change the error code. 
* Expected results
Should install correctly
* Actual results (with terminal output if applicable)
An error message with the error code 0x800F0831
* Your Windows build number
Version	10.0.14393 Build 14393
* Steps / All commands required to reproduce the error from a brand new installation 
Try to install 
* Strace of the failing command
N/A
* Required packages and commands to install
N/A

**Comment by benhillis** [comment]
@inondle - Do you happen to be on an LTSB version of Windows?
