### ISSUE TITLE
vi display is garbled

### ISSUE THREAD

**Issue by raymod2** [Microsoft/WSL#1895]
* A brief description

When editing a file in bash using vi the screen becomes garbled.  This appears to happen when you first open a bash window.  If you change the window height vi starts working correctly until you open a new bash window.

* Expected results

The screen displays the file correctly.

* Actual results (with terminal output if applicable)

The screen is garbled.

* Your Windows build number

Version 1703 (OS Build 15063.0)

* Steps / All commands required to reproduce the error from a brand new installation

Open a bash window.  Right-click the title bar and select properties.  Click the "Layout" tab and set "Height" to 40 in the "Window Size" size section.  Click OK.  Close the bash window.  Open a new bash window (it should have a height of 40).  Now open a vi instance.  For example, type 'sudo visudo'.  The first thing you will notice is that line 1 is not visible.  Only lines 2 through 30 are displayed.  If you press the up arrow key to scroll to line 1 nothing will happen.  As you try to edit the file things get worse.  Press 'o' to insert a new line.  Now line 1 appears but it is labeled line 3.  The new line you have created is labeled line 4 (but it should be line 2).  The rest of the lines also have incorrect line numbers.  Start entering text (type "foo").  The 'f' appears in the top line (now labeled line 4) and the "oo" appears in the second line (now labeled line 5) but interspersed with text from another line.  As you can see everything is hopelessly garbled.

![vi_garbled](https://cloud.githubusercontent.com/assets/3221147/24968690/49b8e04a-1f6b-11e7-9550-b4f2987890cc.png)

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by Shadowys** [comment]
I tested this. I do not have this problem.

**Comment by zadjii-msft** [comment]
@raymod2 Is this consistently repro'ing for you? I can't seem to replicate that behavior. 

Is it possible that you made any changes to something like your `.inputrc`, `infocmp` or your `TERM`?

**Comment by raymod2** [comment]
Yes, I can reproduce it consistently.  I didn't touch any of those files or environment variables you mentioned.  I did install a few packages including gvim-gtk3 that might have changed something.

**Comment by zadjii-msft** [comment]
@raymod2 I tried installing vim-gtk3 and i still couldn't get this behavior to repro. Do you have any vim plugins installed that might be causing this?

What does your `.vimrc` look like?

**Comment by raymod2** [comment]
```
set lines=40
set columns=108
set nobackup
set nowritebackup
set whichwrap=      " do not wrap to next/previous line when using arrow keys
set nu              " show line numbers in the left column
set autoindent      " autoindent to the same level as the previous line
set copyindent      " autoindent copies structure of previous indent (prevents TABS)
set guioptions+=a   " selecting text automatically places it in the clipboard
set incsearch       " incremental search (find nearest match as you type search term)
set hlsearch        " highlight search terms
filetype plugin indent off  " suppress cindent and comments settings
set tags=./tags;    " search for 'tags' in parent directories of current file
" If only one tag matches jump directly to it, otherwise present a list of tags
map <C-]> g<C-]>
" Suppress pop-up dialog when file changes outside of VIM (print to status bar instead)
autocmd FileChangedShell * echohl WarningMsg | echo "File changed shell." | echohl None
" jump to the last position when reopening a file
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
```

**Comment by raymod2** [comment]
The .vimrc does seem to be related to this issue.  I started with a fresh Windows installation and ran 'sudo vi /etc/sudoers' and there were no issues.  Then I created the .vimrc as above and ran the same command.  Now I am seeing issues similar, but not identical, to the above description.

**Comment by raymod2** [comment]
On another note, it seems bizarre that a command named 'visudo' would use 'nano' as the default editor instead of 'vi'!  I noticed that installing vim-gtk3 changes the default editor in 'visudo' from 'nano' to 'vim'.  But vim-gtk3 is not necessary to reproduce this issue if you use 'sudo vi /etc/sudoers' instead.

**Comment by raymod2** [comment]
@zadjii-msft - Were you able to reproduce this?

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#116
