### ISSUE TITLE
WSL prefers NodeJS executable in Program Files over /usr/bin

### ISSUE THREAD

**Issue by Entroper** [microsoft/WSL#1896]
I've just tried installing NodeJS on WSL, after running the Creators Update and doing a fresh WSL install to get 16.04.

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

    $ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    $ sudo apt-get install -y nodejs

Running node works fine:

    $ node -v
    v6.10.2

But npm doesn't work:

    $ npm -v
    : not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm:
    : not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm:
    /mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")

It seems to be trying to run the npm executable from Windows.  I tried some other things:

    $ whereis npm
    npm: /usr/bin/npm /mnt/c/Program Files/nodejs/npm /mnt/c/Program Files/nodejs/npm.cmd /mnt/c/Users/Entroper/AppData/Roaming/npm/npm /mnt/c/Users/Entroper/AppData/Roaming/npm/npm.cmd
    $ which npm
    /usr/bin/npm
    $ /usr/bin/npm -v
    3.10.10
    $ whereis node
    node: /usr/bin/node /usr/include/node /mnt/c/Program Files/nodejs/node.exe /usr/share/man/man1/node.1.gz
    $ which node
    /usr/bin/node

So it obviously knows where the Linux npm is, and it seems to think that's the preferred one, but it doesn't run that one for some reason.  And it clearly works if I specify the absolute path to npm.

**Comment by benhillis** [comment]
It looks like you're running into similar issues as #1890.  I'd suggest overwriting your $PATH environment variable in your .bashrc file or setting the registry key that disables appending the NT path.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"AppendNtPath"=dword:00000000

```

I'll try to set this up locally. Could you share the output of the below command?
`strace -v npm -v`

**Comment by Entroper** [comment]
Amusingly, the strace command worked perfectly -- it ran the Linux npm.  I can attach the debug output, but it probably isn't useful.  I'll give the $PATH thing a try.

**Comment by Entroper** [comment]
Since I can no longer reproduce the problem, and pathing issues are being looked into, I'll close this.

**Comment by ncla** [comment]
Had the same issue, and closing and opening bash solved that problem. Weird. I did uninstall Node from Windows before-hand.

**Comment by samplefrequency** [comment]
I'm running into the exact same issue.

I made sure Node was not installed under Windws and installed Node LTS under WSL. Everything worked perfectly. I was able to run my servers and builds while editing under the Windows environment. Problem is that my IDE has integrations that I would like to be able to use which requires Node for Windows.

I installed Node LTS For Windows and it gets added to the Windows path. Everything works fine under Windows but once I re-open a Bash on Windows instance, NPM utterly fails. Uninstalling Node for Windows and everything under WSL works again. 

May someone post the $PATH workaround?

I may try the registry key just to keep the environment paths completely separate as at the moment I don't have a need to launch Windows executables via WSL.

**Comment by Entroper** [comment]
I'll reopen this since others are still seeing this issue.

**Comment by samplefrequency** [comment]
Re-installed Node for Windows (6.10.2) and this time, I set the installer to not add node and npm to the Windows path. I set my IDE to access the path to Node it requires (c:\program files\nodejs\node.exe) and invoke npm.cmd directly as well if I need to install npm modules in the Windows environment. Not ideal but seems to work for the moment.

**Comment by dfbaskin** [comment]
Same thing, closing Bash and reopening fixed the issue.

**Comment by smalike** [comment]
Windows change npm to npm.exe fixed the issue.

**Comment by samplefrequency** [comment]
@smalike Do you mean you changed npm.cmd to npm.exe?

**Comment by jmalczak** [comment]
@samplefrequency rename npm to npm_cygwin, since npm in program files is a bash script targeted for cygwin

**Comment by samplefrequency** [comment]
@jmalczak I ended up simply overriding the PATH variable in WSL and everything is working well now.

**Comment by dacp** [comment]
Same, closing and re-opening fixed the issue.

**Comment by larscmagnusson** [comment]
alias npm=path-to-npm-bin-in in your .bash_rc works fine for me :)

**Comment by Joseph211219479** [comment]
from this post I : uninstalled node from windows, open bash as administer, reinstall node in bash. Thanks  all above.

**Comment by cenyG** [comment]
Use [nvm ](https://github.com/creationix/nvm) for Ubuntu subsystem and all will be cool

**Comment by danieliser** [comment]
Haha found this via google again. Will re-iterate, this isn't a valid issue. PATH variables are cached when terminal/bash/cmd loads, so if you update them you always need to close the open window and open a new bash to access new commands.

Close this.

**Comment by hcervantes** [comment]
Simply set your path in WSL
`export PATH=/usr/bin:$PATH`

**Comment by vontend** [comment]
just `sudo ln -s /usr/bin/npm /bin/npm` and it work

**Comment by therealkenc** [comment]
The OP is missing `sudo apt install npm`. The `npm` package is not a dependency of `nodejs`. On Real Linux people notice this right away (because `npm` is missing), install `npm`, and move on. On WSL, if you've installed `npm` on Windows, but not on your WSL distro, the Windows `npm` is the one you'll get (because Windows `npm` is in your `$PATH`). Same #3882 #1512, others. Pedantically the `Syntax error` in the OP is linux-behavior `/bin/bash` like #2365.

There are some suggestions on using node with WSL [here](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2).
