### ISSUE TITLE
stat returns size 0 for /sys/class/net/<iface>/address

### ISSUE THREAD

**Issue by Fukkei** [microsoft/WSL#1920]
`stat` syscall returns wrong size for /sys/class/net/<iface>/address files
```
max@DESKTOP-NKSVSMH:~$ stat /sys/class/net/eth0/address
  File: '/sys/class/net/eth0/address'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 6h/6d   Inode: 34          Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-04-14 22:00:30.102866800 +0300
Modify: 2017-04-14 22:00:30.102866800 +0300
Change: 2017-04-14 22:00:30.102866800 +0300
 Birth: -
max@DESKTOP-NKSVSMH:~$ cat /sys/class/net/eth0/address
00:ff:26:dd:2a:9a
max@DESKTOP-NKSVSMH:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
strace output: [https://gist.github.com/Fukkei/d06c593f354a284d83c3fc68248dc794](url)
Microsoft Windows [Version 10.0.15063]

**Comment by benhillis** [comment]
Thanks for reporting this. Is this breaking anything or just something you noticed?

**Comment by Fukkei** [comment]
Hi, thanks for responce. We have code that reads interfaces list, it requests file size to allocate proper buffer size. Not a big deal to fix that, but the behavior itself is quite unexpected

**Comment by therealkenc** [comment]
Better in WSL2. Oddly, Real Linux reports a file size `0` across all of `/proc` (with a few exceptions) but `4096` on `/sys`. Guess the subtle `/sys` difference on WSL1 never took down anything particularly visible, given the quiet.

![image](https://user-images.githubusercontent.com/7049700/90665694-404f3980-e201-11ea-883c-3af9c461cdb1.png)
