### ISSUE TITLE
Apache start error in  Windows Creator update.

### ISSUE THREAD

**Issue by Djaconda** [Microsoft/WSL#1921]
install bash

sudo apt update
sudo apt dist-upgrade

sudo apt install apache2 

 sudo service apache2 start
 * Starting Apache httpd web server apache2
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.

Windows 10 Pro 1703

**Comment by Djaconda** [comment]
I've fixed it. 

Firstly I've turn off checkbox of Skype that uses 80 and 443 port from additional incoming connections.
Than I've turn off "Web Publishing Service" Microsoft Windows service.

**Comment by alanaasmaa** [comment]
I could't find service "Web Publishing Service" in task manager.

But i found out running `net stop was /y` in cmd fixed the problem for me. 

It disabled
 - Wold Wide Web Publishing Service
 - Net.Pip Listener Adabter 
 - Net.Msmq Listener Adapter
 - Windows Process Activation Service

**Comment by MarkusBarthlen** [comment]
Note that may also need to disable SQL Server Reporting Services.
