### ISSUE TITLE
Resizing the terminal to one row with Midnight Commander open crashes conhost

### ISSUE THREAD

**Issue by zadjii-msft** [Microsoft/WSL#1938]
This doesn't seem to repro in `tmux` or `byobu`. More investigation needed as far as what is specifically causing this crash.

**Comment by zadjii-msft** [comment]
This is MSFT:11686944

**Comment by zadjii-msft** [comment]
Checked in with OS repo PR#496484

**Comment by benhillis** [comment]
Lol @zadjii-msft, don't tease the nice folks with pull requests and bug numbers they can't see.

**Comment by zadjii-msft** [comment]
¯\\\_(ツ)\_/¯

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#114
