### ISSUE TITLE
How to add or use php with Windows code editors.

### ISSUE THREAD

**Issue by erdemece** [Microsoft/WSL#1946]
Hi,

With the creator update we can use linux programs from windows. if you type bash -C "php -v" (if I remember correctly) but it's not enough.

I use vscode with a extension called intelliSense. This is pretty much standard with all other text editors on windows. We need to add php to environment path on Windows.

Since bash is on the environment path anyway but how can I use php with these code editors.

This is message is from my code editor;
"You need at least PHP 7 installed for the extension to work. You can either add it to your PATH or set the php.executablePath setting."

Is there anyway to add php from ubuntu to environment path? 
if not is there way to add the path to the code editor settings? 

If I have to install php for windows, ubuntu on bash is useless for me.

Thanks for help.

**Comment by Line117** [comment]
Use SSH connent in IDE.

**Comment by aseering** [comment]
You could also try calling the command through bash.  For example, add `bash.exe -c php` as your PHP interpreter.

Bottom line is, Windows and Linux versions of programs are not the same.  Sometimes the same program will deliberately behave differently on Windows and on Linux.  So your plugin has to know to speak Linux on a Windows host.  WSL makes this hugely easier, and sometimes it Just Works(tm), but if it doesn't work then you might have to post to the VSCode IntelliSense devs to ask how to get at Linux interpreters in their configuration UI.

**Comment by xtoolkit** [comment]
hi
copy this code in a **php.bat** file, and add your folder in `%PATH%` in _Edit environment variables for your account_ .

``` cmd
@echo off
set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:c:=/mnt/c%
set v_params=%v_params:"=\"%
@bash -c "php %v_params%"
```

and use php in %PATH% in cmd :D
i create `.bat` for java, javac, git, php and ll. and u can download from [this link](http://cdn.arshen.ir/fixwsl/1.0.0/w2w.zip)

**Comment by erdemece** [comment]
@xtoolkit thank you. can you please explain little bit better if you have time? thanks.

**Comment by therealkenc** [comment]
Looks like this question was answered to the best of people's ability back in the spring of last year. You can probably find the best insight in the PHP community.
