### ISSUE TITLE
Boehm gc fails on "Absurd stack bottom value"

### ISSUE THREAD

**Issue by carlokok** [microsoft/WSL#1947]
Microsoft Windows [Version 10.0.15063]

What I'm doing: Run an app that uses the Boehm gc.

What happens: 
- abort with: Absurd stack bottom value
What should happen:
- Should just run
Why this happens:
Boehm gc reads "/proc/self/stat" and extracts field 28 and uses that for stack scanning (field 28 is the start of the main thread's stack, see http://man7.org/linux/man-pages/man5/proc.5.html) . On Bash On Windows however this field is 0:
```
113 
(nil) 
26 
(ConsoleApplicat) 
R 
2 
26 
2 
1025 
0 
0 
0 
0 
0 
0 
0 
0 
0 
0 
20 
0 
1 
0 
135358 
917513588736 
321 
18446744073709551615 
0  <<<<<< 
0 
0
```

I don't see any alternative way to get the start of the stack on Linux/Bash on Windows either.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue!  Marking this as a bug so we can track fixing this up.

**Comment by seanofw** [comment]
For what it's worth, I ran into this today, and I managed to fix it for a single broken app by recompiling it with `-DUSE_LIBC_PRIVATES`, which forces Boehm to use a different algorithm to guess the stack bottom.  It'd still be better if WSL's `/proc/stat` had the right data in it, but at least in my case, the above workaround works.

**Comment by therealkenc** [comment]
Field 28 of `/proc/<PID>/stat` still zero on WSL 1 build 19551. Addressed in WSL2.
