### ISSUE TITLE
Syntax coloring not working in Vim

### ISSUE THREAD

**Issue by ep-silon** [Microsoft/WSL#1950]
* Your Windows build number:  10.0.15063
* What you're doing and what's happening:  after updating to Creators Update and upgrading Bash on Ubuntu for Windows to Ubuntu 16.04 by using "sudo do-release-upgrade" syntax color is not working anymore in Vim. If I type inside a vim file ":colo evening", then colors reappear, but only for that session. I added this command to ~/.vimrc file, but this does not work. Apparently .vimrc file is ignored.

**Comment by zadjii-msft** [comment]
Does doing anything else in your .vimrc work? For example does adding `set number` to your .vimrc add line numbers?

Does adding `set t_Co=256` fix it by any chance?

What is the value of your TERM environment variable?

**Comment by ep-silon** [comment]
set number is working.
set t_Co=256 did not solve the problem.
Please see attached my vimrc file.
[vimrc.txt](https://github.com/Microsoft/BashOnWindows/files/936498/vimrc.txt)

**Comment by zadjii-msft** [comment]
Is it possible that you've installed some package that may have changed you vim configuration in another way? 
I can verify that in a fresh install, vim faithfully loads your .vimrc, so I'm fairly certain this has to do with another package that was installed afterwards or some other modification.

**Comment by ep-silon** [comment]
I haven't installed any package myself, I just upgraded Ubuntu. Maybe during the upgrade process some packages were installed automatically. Is it there anyway how could I fix this problem without a clean install?
