### ISSUE TITLE
APR_TCP_DEFER_ACCEPT error when starting Apache2

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/WSL#1953]
> Logging this issue here as information for others. Issue is benign and can be ignored.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Starting Apache2 with:

```
$ sudo service apache2 restart
```

* What's wrong / what should be happening instead:
Following error message is displayed:

```
* Restarting Apache httpd web server apache2
[Tue Apr 18 18:50:52.618691 2017] [core:warn] [pid 546:tid 140453865195392] (92)Protocol not available: 
AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
```

**Comment by bitcrazed** [comment]
The TCP_DEFER_ACCEPT socket option is not natively supported by Windows. 

WSL team are working with Windows networking team on this issue, but fix likely won't make it in RS3. 

Doesn't block Apache2 from starting, just a warning. Pile-on below if otherwise.

**Comment by sunilmut** [comment]
Thanks @bitcrazed for reporting the issue. Your analysis above seems spot on.

**Comment by namiltd** [comment]
Add the following line to the end of the /etc/apache2/apache2.conf file:
AcceptFilter http none

**Comment by Jduret** [comment]
If you have this warning after enabling SSL (https), just add the following line  to the end of the file :

> /etc/apache2/apache2.conf

`AcceptFilter https none`

**Comment by JeyKeu** [comment]
I have added both `http` and `https`

`AcceptFilter https none`
`AcceptFilter http none`

**Comment by solracfirst** [comment]
Hello,

I have added 
```
AcceptFilter https none
AcceptFilter http none
```


AcceptFilter https none
AcceptFilter http none
```

This worked on start, however, when I give restart it continues with the same error.

**Comment by jp-harvey** [comment]
@bitcrazed is there an issue somewhere open for the fix that can be tracked / voted on or is this it? Applications based on [Apache Thrift](https://thrift.apache.org/) currently do not work on WSL due to TCP_DEFER_ACCEPT not being available, eg. [MapD](https://github.com/mapd/mapd-core)

https://github.com/Microsoft/WSL/issues/1953#issuecomment-295353694

> The TCP_DEFER_ACCEPT socket option is not natively supported by Windows.
>
> WSL team are working with Windows networking team on this issue, but fix likely won't make it in RS3.

**Comment by bitcrazed** [comment]
This is one of the main issues tracking this problem, so please subscribe to this issue if you're interested in future progress. @tara-raj will triage with the team and get back to you.

**Comment by jp-harvey** [comment]
Hi @tara-raj, has there been any progress on this issue internally?

**Comment by therealkenc** [comment]
This is another one that should have been stubbed to do nothing back in 2016 (like every GNU/FOSS `configure` script on the planet does). Question rhetorical natch. Pretty sure it can be [configured away](https://httpd.apache.org/docs/2.4/mod/core.html) with `AcceptFilter http none` but I haven't tried.

**Comment by jp-harvey** [comment]
@therealkenc there does indeed appear to be a way to configure Apache to work around it, however, it's not Apache specific.

**Comment by therealkenc** [comment]
> it's not Apache specific

That's rhetorical also.

Identifying other use-cases here is always good. Or at least, it never hurts.

**Comment by jp-harvey** [comment]
> That's rhetorical also.

Yes, although the fact that MapD (OmniSci) does not work due to Apache Thrift not working because of this is not rhetorical

**Comment by therealkenc** [comment]
> due to Apache Thrift not working

Add `#undef TCP_DEFER_ACCEPT` [here](https://github.com/apache/thrift/blob/cbcfb2573f924cb051b7678b5cb4f7ef7138be49/lib/cpp/src/thrift/transport/TServerSocket.cpp#L357) should make it go.

**Comment by lion-wang** [comment]
Is there plan to fix this?

**Comment by jp-harvey** [comment]
Thanks @therealkenc this is great, we are going to try this as a workaround.

(the point remains though - `instead of every dependent project having to do so` ~ `instead of every user having to modify their system`)

**Comment by odeciojunior** [comment]
Same problem here...

**Comment by thevictor13** [comment]
Well it did not seem to have made it to 1903

**Comment by jp-harvey** [comment]
@thevictor13 I suppose there's a possibility that "Full System Call Compatibility" will fix this issue (although, what do I know?) in WSL2: https://devblogs.microsoft.com/commandline/announcing-wsl-2/. This may be (part of) the reason this issue has not had any love from MS.

**Comment by thevictor13** [comment]
Hmm, makes sense. Thanks for the link! I'll keep an eye on it.

**Comment by Superdrac** [comment]
Just updated to WSL2 and no more error.

**Comment by BenMorel** [comment]
Still have it on WSL 2.

**Comment by vintprox** [comment]
Yeah, make as @BenMorel said, if you have Windows 10 Build 18917 or higher. [Other requirements.](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)

**Comment by bluepioupiou** [comment]
> set-version

unknown command : --set-version

**Comment by coltongit** [comment]
> 
> 
> > set-version
> 
> unknown command : --set-version



> 
> 
> Yeah, make as @BenMorel said, if you have Windows 10 Build 18917 or higher. [Other requirements.](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
> Otherwise you have an option to ignore warning.

**Comment by diveshdc** [comment]
AcceptFilter https none
AcceptFilter http none
