### ISSUE TITLE
Configure fails to detect cross compilation for android

### ISSUE THREAD

**Issue by DelusionalLogic** [microsoft/WSL#1964]
Windows version: Microsoft Windows [Version 10.0.14393]

I'm compiling a standard C project for an android project. To do so I'm using the android standalone toolchains, one of those is for x86_64. The project is using GNU Autotools. The combination of those two factors is a problem. The triplets of the two systems are as follows: ```x86_64-none-linux-androideabi``` and ```x86_64-unknown-linux-gnu```.

GNU Autotools tries to detect whether it's cross-compiling. In this case it incorrectly detects that it isn't, but Linux correctly detects that it is cross-compiling.

Speculation
------------
Now I don't know for sure what the problem is, but this is my guess:

Since the first two parts of the triplets are compatible, autotools tries to detect cross-compilation by actually doing the compilation and running the program. On linux, running a program compiled against the android abi gives and error. While on windows, the program does nothing, but doesn't return any error code.

Repro
------
I'm going to assume you have a standalone android compiler for ```x86_64``` as described in: https://developer.android.com/ndk/guides/standalone_toolchain.html, located in ```/compiler/```

The test program, located in ```test.c```:

    include <stdlib.h>
    
    int main() {
        printf("Hello world");
        return 0;
    }

The compilation command is: ```/compiler/bin/clang test.c```, producing ```a.out```.

Executing ```./a.out``` on linux results in an error as expected, but in WSL it fails silently.

**Comment by fpqc** [comment]
Update Windows to the 1703 release and update this info. Your errors and blockers are likely out of date.

**Comment by DelusionalLogic** [comment]
I updated to Microsoft Windows [Version 10.0.15063]. The issue is still present and identical.

**Comment by fpqc** [comment]
Thanks!

**Comment by therealkenc** [comment]
> I'm going to assume you have a standalone android compiler for x86_64 as described in:

This submission was skipped on an incorrect assumption. The `ENOENT` is cited because the dynamic linker for the ELF binary does not exist. 

> I should note that "No such file or directory" is the error i get when I run a.out on a real linux machine.

Correct.

Fails silently fixed in 15063. `ENOENT` is linux-behavior.
