### ISSUE TITLE
MOTD support

### ISSUE THREAD

**Issue by gpotter2** [Microsoft/WSL#1966]
* __Your Windows build number:  (Type `ver` at a Windows Command Prompt)__

Microsoft Windows [version 10.0.16176]

* __What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)__

Please add a MOTD (message of the day) = logging in message !
There are quite a lot of ways MOTD messages are setup (/etc/motd, /etc/motd.tail, default...) but it would be so cool !

It shouldn't be too hard to do, but because of that, BashOnWindows doesn't looks as good as a normal shell would look...

Thanks for the great WSL & good luck !

**Comment by jackchammons** [comment]
This is something that we are looking into. As a work around you could invoke the MOTD via your .bashrc

**Comment by simonbuchan** [comment]
I run with zsh by running login - basically configure lxss to run as root then editing the Ubuntu shortcut target to `C:\Windows\System32\bash.exe ~ -c "/bin/login -p -f simon"` where `simon` is my Ubuntu account name. With this setup, I get the default MOTD message:

```
Last login: Mon Apr 24 09:55:09 STD 2017 on tty1
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-43-Microsoft x86_64)

0 packages can be updated.
0 updates are security updates.


0 ~ 0 %
```

Note that by default Xenial installs `landscape`, and that spits out an error in this setup, easy enough to uninstall it though.

**Comment by gpotter2** [comment]
Has it been fixed ?

**Comment by benhillis** [comment]
A couple of workaround are available, I'm working on something that will allow you to do this more easily.

**Comment by therealkenc** [comment]
Let's keep it in one place, which is #352

**Comment by Alex6357** [comment]
It seems that pam modules are (partly) still not functioning. MOTD is not correctly shown.
