### ISSUE TITLE
Unable to install perl, or postgresql. Using linuxbrew

### ISSUE THREAD

**Issue by sudhirj** [microsoft/WSL#1967]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  Microsoft Windows [Version 10.0.16179]

* What you're doing and what's happening: 
Install linuxbrew (http://linuxbrew.sh/)
`brew install perl`

Lots of error messages, but the important bits seem to be 
```
dist/Net-Ping/t/510_ping_udp .................................. #   Failed test at t/510_ping_udp.t line 25.
#          got: '0'
#     expected: '1'
# Looks like you failed 1 test of 2.
FAILED at test 2
dist/Net-Ping/t/520_icmp_ttl .................................. ok
```

* What's wrong / what should be happening instead:
Perl ought to install.

This this related to `ping` being implemented only for TCP and not UDP?

Also, it would be great if the team could set up a compatibility table for which packages on Linuxbrew will install on WSL - for me at least, that's the yardstick on whether WSL is mature enough to use - my ritual for the last few months has been installing the latest insider build and hitting `brew install git ruby-build rbenv openssl postgres node redis` and see how far it goes.

**Comment by bluppfisk** [comment]
not entirely sure, but WSL on Windows 10 build 16179 has been quirky for me. Everything loads very slowly and composer (package manager) cannot decode responses. So I think something may have changed in the networking layer for WSL in this build of win10

**Comment by bgilbank** [comment]
I can install Postgres but I can't create a user or start the server. Too many errors, so I just installed Postgres on the windows side for now. 

Error: 
# username is not in the sudoers file. This incident will be reported.

**Comment by bluppfisk** [comment]
you may want to put your username in the sudoers file or log in as root.

**Comment by bgilbank** [comment]
Ah, my Rails set up works fine on the Windows side as long as I run the app on a Windows folder, not inside WSL. 

I tried a bunch of fixes including logging in as the root, but new problems kept popping up. There is a huge post on this issue here: https://github.com/Microsoft/BashOnWindows/issues/61

Hopefully, Microsoft fixes it soon.

**Comment by shevegen** [comment]
I just compiled perl from source on my win 10 laptop (ubuntu as base system but I already recompiled most stuff from source).

Perl itself works fine here.

What are the "dist/Net-Ping/t/510_ping_udp .................................. # " lines? Does homebrew generate them?

> it would be great if the team could set up a compatibility table for which packages on
> Linuxbrew will install on WSL - for me at least, that's the yardstick on whether WSL
> is mature enough to use 

I guess it's a bit overkill for them to keep track of what all works and des not work on every different system per se. The reference also refers to brew again. Are you guys really sure that this is not something that brew does on its own?

**Comment by therealkenc** [comment]
`brew install perl` takes on WSL1 20H1.

![image](https://user-images.githubusercontent.com/7049700/95174342-c9e5a700-076e-11eb-91af-938ec834763b.png)

> This this related to ping being implemented only for TCP and not UDP?

_Possible_ that there was a UDP socket bug fix along the way (though nothing rings a bell). The curious thing about this one is UDP ping is [really an echo](https://perldoc.perl.org/Net::Ping#DESCRIPTION), and Windows doesn't respond to `port 7` echo request unless you install the Simple TCP/IP Services as an optional component. I could not isolate the source code in Perl's universe to confirm what syscalls the test is/was actually performing. It is also possible the perl brew package moved and is now simply more forgiving. Will take the win either way.
