### ISSUE TITLE
SABnzbd Hangs on OS Memory Allocation Error

### ISSUE THREAD

**Issue by nosajthenitram** [microsoft/WSL#1970]
Microsoft Windows [Version 10.0.16176]

Steps to reproduce:

* Clone sabnzbd: git clone https://github.com/sabnzbd/sabnzbd.git
* Run sabnzbd: python SABnzbd.py
* Configure sabnzbd
* Navigate to: sabnzbip:sabnzbport/config/general/
* click restart SABnzbd button

Restarting the SABnzbd server from the web interface results in this hanging crash.

Output from console: 

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/public/sabnzbd/sabnzbd/__init__.py", line 478, in trigger_restart
    cherrypy.engine._do_execv()
  File "/home/public/sabnzbd/cherrypy/process/wspbus.py", line 408, in _do_execv
    os.execv(sys.executable, args)
OSError: [Errno 12] Cannot allocate memory

Not enough scroll to capture useful strace output.

**Comment by benhillis** [comment]
@nosajthenitram - Thanks for posting.  Could you please follow the instructions in our [issue template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)?

**Comment by benhillis** [comment]
Closing issue, feel free to reopen after adding the required info from the template.

**Comment by nosajthenitram** [comment]
@benhillis Unable to reopen an issue closed by you. Can you please reopen this issue if you feel as though it's adequately updated?

**Comment by therealkenc** [comment]
@nosajthenitram - You can help Ben with:
```
strace -ff python SABnzbd.py 2> SABnzbd.strace
# do whatever 'Configure sabnzbd' means. I quit at:
#    "Please enter in the details of your primary usenet provider."
# ...watch it crash, kill the `strace` with ctrl-c if necessary, then:
gzip SABnzbd.strace
```
Attach `SABnzbd.strace.gz` to this github issue.

**Comment by 1wayjonny** [comment]
Hi I am having this issue how can I help?

I have seen this over the years but I can reproduce this almost all the time with a specific setup I have been testing over years. Now I am switched over to this set up and been using it fine but have this issue.

I am using Windows for Linux Sub-system (WSL) and I am running SAB, SickRage and Couch from the Ubuntu bash and all works well and is much fast then older methods I used to run phython source from Windows. Windows was slower but I never had issues.

WSL is so much fast and I have good support for my 60+TB Raid for my media. Believe it or not the driver support is a pain in the butt in Linux so my server runs Windows and WSL is a blessing!

That being said let me know what I can I can capture or help to potentially fix. I get this 100% of the time when I restart using the GUI. It then hands until I break the command line and then I re-run and life is good as long as I do not restart.

Hope I can help, cheers.

**Comment by therealkenc** [comment]
Assuming...:
```
$ sudo apt install python3 python3-cheetah python3-feedparser python3-cherrypy3 python3-portend python3-sabyenc \
    unrar par2 git # probably else
$ git clone https://github.com/sabnzbd/sabnzbd.git
$ cd sabnzbd
$ python3 SABnzbd.py
```

"Click restart SABnzbd button" takes on recent WSL1 (sic). If the scenario was once not working, it appears to be now (call it 19042).

![sabnzbd-restart](https://user-images.githubusercontent.com/7049700/93947034-9aa35480-fcef-11ea-812c-3b7f9abbcf9d.gif)
