### ISSUE TITLE
lxrun /uninstall /full fails silently if you're not a local admin

### ISSUE THREAD

**Issue by oulman** [Microsoft/WSL#1974]
* Your Windows build number:  

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening: 

 lxrun /uninstall /full /y

* What's wrong / what should be happening instead:

Running as a user account that is not a local administrator, lxrun appears to uninstall successfully; however, it doesn't. After adding the account to local administrators the uninstall completes. 

What further confused me is running the same command as a different local admin also fails silently - I'm assuming because lxss installation is not stored in that accounts AppData folder? 

It would be helpful if lxrun /uninstall identified that you are not an administrator and threw a useful error message.

Thanks!

**Comment by benhillis** [comment]
@oulman - Thanks for the feedback. We're looking at some improvements for our install / uninstall story and I'll take this into consideration.

**Comment by darealshinji** [comment]
This may be a duplication of https://github.com/Microsoft/BashOnWindows/issues/1875

**Comment by benhillis** [comment]
Lxrun is deprecated.

**Comment by darealshinji** [comment]
@benhillis you should then close #1875 too.
