### ISSUE TITLE
ruby-build quits with some unexpected errors on WSL

### ISSUE THREAD

**Issue by aurimus** [microsoft/WSL#1976]
Installing Ruby version with ruby-build fails with following:

	$ rbenv install 2.3.4
	: invalid optionbenv/plugins/ruby-build/bin/rbenv-install: line 26: set: -
	set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
	/home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 28: $'\r': command not found
	: invalid shell option names/ruby-build/bin/rbenv-install: line 31: shopt: nullglob
	/home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 32: syntax error near unexpected token `$'do\r''
	'home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 32: `for plugin_path in "$RBENV_ROOT"/plugins/*/share/ruby-build; do

which is I guess due to line endings incompatibility... however, this happened after I checked out a fresh copy of ruby-build repository, also tried checking out some stable version releases and it gives the same error, so I can't tell why.

I ran the command with `strace` and it output a couple of files:

[strace_ruby_build80.txt](https://github.com/Microsoft/BashOnWindows/files/948821/strace_ruby_build80.txt)
[strace_ruby_build81.txt](https://github.com/Microsoft/BashOnWindows/files/948819/strace_ruby_build81.txt)
[strace_ruby_build82.txt](https://github.com/Microsoft/BashOnWindows/files/948820/strace_ruby_build82.txt)
[strace_ruby_build83.txt](https://github.com/Microsoft/BashOnWindows/files/948818/strace_ruby_build83.txt)
[strace_ruby_build84.txt](https://github.com/Microsoft/BashOnWindows/files/948817/strace_ruby_build84.txt)

Windows version: 1607, 14393.1066

**Comment by aseering** [comment]
Hi @aurimus , thanks for posting!  Could you please fill out the issue template?  The symptoms that you describe are not generally a problem; I can try to guess what's unusual about what you're doing, but it'd be better if you could provide more detail.

**Comment by aurimus** [comment]
Please see this issue on rbenv build, thanks! Using latest stable version of Windows 10 v 14393.1066
https://github.com/rbenv/ruby-build/issues/1077

**Comment by benhillis** [comment]
@aurimus - Please use our issue template when filing issues, it has lots of information we need to diagnose the problem.

Looks like an issue with mixed Windows / Unix line endings.  Does the error message tell you which source file it's complaining about?  Could you ensure that file has uniform line endings?  The dos2unix package may be useful for converting all of the line endings to Unix.

**Comment by aurimus** [comment]
@benhillis , not sure, it would probably be good question to ask the guys at https://github.com/rbenv/ruby-build not sure how to debug it myself to find which file it might be.. .. I'm using git on WSL to clone fresh repository, so in theory it should be ok, but somehow it's not..

**Comment by benhillis** [comment]
Looks like things start to fall over at line 28 of rbev-install:

```
home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 28: $'\r': command not found
: invalid shell option names/ruby-build/bin/rbenv-install: line 31: shopt: nullglob
/home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 32: syntax error near unexpected token `$'do\r''
'home/aurimus/.rbenv/plugins/ruby-build/bin/rbenv-install: line 32: `for plugin_path in "$RBENV_ROOT
```

**Comment by aurimus** [comment]
@benhillis why would line endings be wrong if I just clone it with git on WSL bash? .. I can try cloning it with cmd into lxss dir, but that would be some violation of WSL, no?

**Comment by benhillis** [comment]
@aurimus - good question, I can assure you WSL isn't messing with line endings during a git clone.  Have you tried your same steps on a real Linux box? I suspect you'll hit the same issue.

**Comment by aurimus** [comment]
I don't think it would hit the same error, because I am cloning and
checking out a stable release, which shouldn't have issues. Don't have real
Linux to test it though (Ubuntu broke a few months ago, that's actually the
reason I am trying to switch to Windows and WSL for a year or so.. and with
recent developments in Ubuntu dropping Unity, thinking of staying also)

**Comment by aurimus** [comment]
@benhillis  I don't think it would hit the same error, because I am cloning and
checking out a stable release, which shouldn't have issues. Don't have real
Linux to test it though (Ubuntu broke a few months ago, that's actually the
reason I am trying to switch to Windows and WSL for a year or so.. and with
recent developments in Ubuntu dropping Unity, thinking of staying also)

**Comment by aurimus** [comment]
@aseering @benhillis not sure if it's useful, but I added `strace`

**Comment by aurimus** [comment]
Tried RVM, works for now, though I prefer rbenv for it is lighter..

**Comment by naven87** [comment]
I have issues with RVM, RVM installs fine, but trying to install ruby errors.  This is a very generic setup, nothing special.  I am in the user account, and i have tried with sudo but both fail with similar error
mv: cannot move '/home/johnsond/.rvm/rubies/ruby-2.4.0/ruby-2.4.0//lib' to '/home/johnsond/.rvm/rubies/ruby-2.4.0/lib': Permission denied

I have tried with and without sudo.  Any call for 'sudo rvm install xxx' complains that rvm unknown, all install provide the above error that if can't move things.  Is it possible the the double "/" creates a problem in WSL?

**Comment by starburst997** [comment]
Check in your git global config if you have `core.autocrlf=true`

If you do, change it to `false`, `git config --global core.autocrlf false`

Delete repo, clone again

**Comment by therealkenc** [comment]
`renv install 2.7.2` takes on WSL1 20H1. [OP `2.3.4` is end of life, and fails because `gcc` is not tolerant enough these days to compile the source.]

![image](https://user-images.githubusercontent.com/7049700/95180585-07e6c900-0777-11eb-9131-ea435dddaf98.png)

The fail in the OP is near certainly some component being picked up from the Windows `%PATH%`. The chances of the problem being `git` are pretty small, given Linux `git` doesn't muck crlf unless you try hard to make it do that (allowing for the possibility Windows `git` was being picked up). As mentioned up-thread, WSL proper is not capable of changing the line endings. Big hammer way to avoid this sort of thing is to turn off interop, or set the Linux `$PATH` explicitly.

_Whatever_ the reason `/ruby-build/bin/rbenv-install` ended up with Windows crlf endings, the way Linux `/bin/bash` interpreted that file is linux-behavior.
