### ISSUE TITLE
AZ CLI 2.0 has to be installed every time bash opens

### ISSUE THREAD

**Issue by Teodelas** [microsoft/WSL#1992]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
[Version 10.0.15063
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
- Trying to run Azure CLI 2.0
* What's wrong / what should be happening instead:
Azure CLI doesn't work after restarting BashOnWindows.  I have to reinstall it.  In other words, I can install AZ CLI, it works fine, but if I close and restart Bash, az is not available.
Error: /usr/bin/python: No module named azure
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

**Comment by benhillis** [comment]
@Teodelas - After installing Azure CLI could you run `which az` and tell me the path?  I think what's happening is Azure is not being removed but the path entry is getting overwritten.  Possibly because of #816.

**Comment by Teodelas** [comment]
Here it is:
/mnt/c/Users/teodelas/AppData/Local/Programs/Python/Python35/Scripts/az

**Comment by benhillis** [comment]
Interesting, it looks like we're picking up the Windows version of az through interop.

**Comment by Teodelas** [comment]
The instructions to download and install the CLI are the same as windows btw…not apt-get…just curl …

Teo
