### ISSUE TITLE
How to create a directory link under /mnt that works in both bash and windows

### ISSUE THREAD

**Issue by SteveALee** [microsoft/WSL#1995]
Is there anyway to make a directory link that can be followed on both sides?

My use case is developing a npm package (actually typescript) and I want to use it from another package without publish/install for every change as I develop. The easiest way is to create as ln -s / Junction from the consuming packages node_module folder to the package. 

I'm compiling etc in WSL and using @code on the windows side as by dev env

I can't get it to work. I ether tried creating a Junction AND and ln but get errors.

Thanks

**Comment by benhillis** [comment]
@SteveALee - Thanks for the feedback. We are currently looking at ways to improve our symlink support to light up this exact scenario.  The changes are in progress so not firm ETA currently.

**Comment by SteveALee** [comment]
FYI @code language engines don't work with junction links - see https://github.com/Microsoft/vscode/issues/25312
