### ISSUE TITLE
Failed to run sudo apt update

### ISSUE THREAD

**Issue by lichao0x7cc** [Microsoft/WSL#1997]
Windows build number: Microsoft Windows [Version 10.0.15063]

> chao@DESKTOP-NG9U46H:~$ sudo apt update
> [sudo] password for chao:
> 0% [Working]http: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
> Reading package lists... Done
> E: Method http has died unexpectedly!
> E: Sub-process http received signal 6.

**Comment by therealkenc** [comment]
#1519
