### ISSUE TITLE
Unknown encoding: 65001

### ISSUE THREAD

**Issue by PetaPetaPeta** [microsoft/WSL#2009]
I am attempting to run docker-compose.exe from Windows in BashOnWindows. Specifically I am running `docker-compose.exe --version` to verify that it can correctly output data. When doing this I am receiving the following error:
```
~ # docker-compose.exe --version                                                                                                                                                                                                  
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 66, in main
  File "compose\cli\main.py", line 98, in dispatch
  File "compose\cli\docopt_command.py", line 25, in parse
  File "compose\cli\docopt_command.py", line 12, in docopt_full_help
  File "site-packages\docopt.py", line 575, in docopt
  File "site-packages\docopt.py", line 484, in extras
LookupError: unknown encoding: cp65001
Failed to execute script docker-compose
------------------------------------------------------------
```

I can see that codepage 65001 is the Windows codepage for UTF-8 encoding, but that this is not supported in Unix systems. A solution to this is to run the command `chcp.com 437` to change to a different codepage. This solution is however not good as it removes the support for UTF-8 in the terminal.
The issue should be persistent across different Windows applications that attempt to output any text in encoding 65001.

**Windows build number:**  Microsoft Windows [Version 10.0.15063]

**Comment by sunjoong** [comment]
This looks like python problem in Windos side; See http://stackoverflow.com/questions/35176270/python-2-7-lookuperror-unknown-encoding-cp65001 and http://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash .

**Comment by sgtoj** [comment]
Now that we understand the problem is encoding related. I am not sure if this an issue with the Windows Console, WSL, Python, or Docker Compose (which is compiled Py 2/3 code)?

**Comment by CherryDT** [comment]
This issue also causes display issues with programs run from within bash.

![image](https://cloud.githubusercontent.com/assets/6010463/25484709/5e9237c2-2b5b-11e7-8e26-28ad0a06ec4f.png)

My codepage is 850, but the inner cmd.exe's (ran from bash) is 65001.

Running `chcp 850` in the inner cmd fixes it.

What is strange though is this, why is it so?
* Open cmd
* Run chcp - output: 850
* Run bash
* Run cmd.exe /c chcp - output: 65001
* Run cmd.exe
* Run chcp - output: 65001 (expected)
* Run chcp 437
* Run chcp - output: 437 (expected)
* Run exit (back to bash)
* Run cmd.exe /c chcp - output: 437 (why did the chcp inside the child process have an effect on future child processes spawned by its parent?)
* Run exit (back to outer cmd)
* Run chcp - output: 850 (looking at the previous unexpected 437 output, why is it not changed here as well?)

**Comment by sgtoj** [comment]
Oddly, it says `cmd.exe` doesn't exists on Windows 10.0.16179.

![](http://i.imgur.com/fWtxazL.png)

**Comment by sunjoong** [comment]
@sgtoj - cmd.exe shoud exist, but stragne if not exist!! "ls /mnt/c/Windows/System32/cmd.exe".

**Comment by PetaPetaPeta** [comment]
@sgtoj From my investigations the issue is that the Python installed in WSL does not support the code page 65001. You can see this if you dig around a bit in `/usr/lib/python2.7/encodings/`. 

I am using cmder and the program can be run in the same terminal if I set it to use powershell. It is thus not isolated to `docker-compose` and I suspect it will be like this for any program that is compiled using codepage 65001. 
That leaves it to whether it is a thing that should be supported in WSL. My opinion on this matter is that it should as one of the features of WSL is running Windows programs in bash.

**Comment by MZAWeb** [comment]
+1 here with the same issue

**Comment by sunjoong** [comment]
![chcp](https://user-images.githubusercontent.com/2748000/27000450-67aa5bdc-4ded-11e7-83a4-bd6256624c29.png)

**Comment by BennettStaley** [comment]
+1 here with the same issue. Cant compose anything.

**Comment by sunjoong** [comment]
I had shown you can run `docker-compose.exe --version` on WSL on the previous comment. I'm not a docker user, so I did not go further, but I'm curious that works for you and why you do not use https://github.com/docker/compose/releases/download/1.14.0/docker-compose-Linux-x86_64 .

**Comment by whitecolor** [comment]
I run such thing using custom linux executables that contain code like this:
`cmd.exe /c "chcp 850 >> null && docker-compose $@"`

The same thing goed for multipe python based apps

**Comment by CherryDT** [comment]
@whitecolor That will create a file called `null` in the current directory. What you want is `nul` with single `l`.

**Comment by whitecolor** [comment]
Yes, was mistype

**Comment by lfurzewaddock** [comment]
OS: MS Windows 10 Pro - Version: 10.0.15063 Build 15063 - Bash on Ubuntu on Windows (WSL)
Docker CE for Windows - Version 17.06.0-ce-win19 (12801) - Channel: stable c98c1c2
ConEmu console emulator: 161206 [64] {Stable}

To determine what 'active code page' the standard MS Windows CMD console is using, open an MS Windows CMD prompt, then type: 

`chcp`

My machine (British English) returned: 

`Active code page: 850`

After discovering the current 'active code page' is 850 in the ConEmu console emulator type:

`cmd.exe /c chcp`

This verified the current 'active code page' the ConEmu console emulator is using to be:

`Active code page: 65001`

To set the 'active code page' to be 850 in the ConEmu console emulator type;

`cmd.exe /c chcp 850`

Which responds with;

`Active code page: 850`

Finally the command...

`docker-compose -version`

...responds as expected with;

docker-compose version 1.14.0, build c7bdf9e3

Although, I haven't yet worked out how to make this permanent as I expect the next time I restart I will have to repeat the previous steps?

**Comment by sunjoong** [comment]
> I will have to repeat the previous steps?

@PetaPetaPetalfurzewaddock - I think so.

**Comment by veqryn** [comment]
I've added `cmd.exe /c chcp 437 > /tmp/chcp 2>&1` to my `.bashrc` file in WSL as a workaround until this is fixed.  (437 being what `cmd.exe` prints out when it runs `chcp` on my laptop)

**Comment by veqryn** [comment]
Nevermind, it seems that workaround has its own issues: It messes up characters.

```bash
11:58:02 ~$ cmd.exe /c chcp 437 > /tmp/chcp 2>&1
11:58:06 ~$ sudo find / -iname "pkg.?config"
find: ΓÇÿ/mnt/c/$Recycle.Bin/S-1-5-18ΓÇÖ: Permission denied

11:58:12 ~$ cmd.exe /c chcp 65001 > /tmp/chcp 2>&1
11:58:19 ~$ sudo find / -iname "pkg.?config"
find: ‘/mnt/c/$Recycle.Bin/S-1-5-18’: Permission denied

11:58:23 ~$ docker-compose stop
Traceback (most recent call last):
  File "logging\__init__.py", line 872, in emit
LookupError: unknown encoding: cp65001
Logged from file main.py, line 74
```

**Comment by veqryn** [comment]
Anyone know how to hook the linux version of docker-compose up to the windows version of docker?
Even if I put them in the same directory (in the mnt) I get this:
```
12:04:02 ~$ docker-compose logs
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

**Comment by veqryn** [comment]
Nevermind, its bash so I just made a function to pipe the output to cat.
Turns out as long as stdout and stderr go to something else before they go to the console, python doesn't complain.

```bash
docker-compose() {
  command docker-compose.exe "$@" 2>&1 | cat
}
```

**Comment by whitecolor** [comment]
I would really recommend using Linux native clients for docker and docker-compose, they are easy to install and it will keep you from many problems with executing windows natives in WSL.

**Comment by veqryn** [comment]
@whitecolor besides issues with the console (ie: https://github.com/Microsoft/BashOnWindows/issues/2379), what issues are there with running windows executables from inside WSL?
My plan is to do everything from inside wsl/bash...

**Comment by MatthewMiele** [comment]
@whitecolor the only issue with running native Linux version on WSL is the issue with paths. This is the original issue I raised before I realised it isn't actually a 'bug'. https://github.com/docker/for-win/issues/298

@veqryn I need to try again but I seem to remember having performance issues when trying to use docker-compose.exe from WSL. It took several seconds for the commands to respond.

**Comment by veqryn** [comment]
I remount the `/mnt/c` to `/c` and that solves the issues with docker & compose mounting volumes.

**Comment by mcuyar** [comment]
For anyone who might run into this, I was able to find a work around using WSL. I use zsh, and added this to my .zshrc, but it should work equally as well in .bashrc

``
function docker_compose() {
    echo "$(docker-compose.exe ${@})"
}

alias=docker-compose="docker_compose ${@}"

**Comment by gempir** [comment]
My workaround for this: Create a file at /usr/bin/docker-compose
and put this in:

```
#!/usr/bin/env bash

trap "/mnt/c/Windows/System32/cmd.exe /C chcp 65001" INT

/mnt/c/Windows/System32/cmd.exe /C chcp 850

/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe "$@"

/mnt/c/Windows/System32/cmd.exe /C chcp 65001
```
now I can run docker-compose from Bash on Ubuntu on Windows without any encoding issues.

**Comment by sahil2629** [comment]
#7292
