### ISSUE TITLE
Different keyboard layout when using Bash on Windows console VS connecting through SSH.

### ISSUE THREAD

**Issue by jpbarrios** [Microsoft/WSL#2014]
I've started noticing this issue since I installed Ubuntu 16.04 after getting the Windows Creators Update (Version 10.0.15063).  I'm pretty sure this didn't happen before the update with the previous Ubuntu 14.04.

So, what happens is this:
If I use Bash through the "Bash on Ubuntu on Windows" icon my keyboard layout matches my Spanish keyboard and I can type any Spanish character or symbol such as ñ, á, é, í, ó, ú, ¡, ¿, etc., but when I access Bash through SSH to take advantage of a more powerful terminal emulator the keys for the Spanish characters are either unresponsive (nothing happens) or turn the shell prompt from "root@Desktop-JP:~#" to "(arg: 1)".

I've tried connecting through SSH with Cygwin Mintty, and also proper Linux machines (an Ubuntu laptop and a Manjaro desktop) and the same happens in all cases: I can't input Spanish characters when conected to Bash on Windows through SSH.  Those terminal clients don't have this issue locally nor when connected to any other SSH server except Bash on Windows on my Windows 10 Desktop.  I currently don't have another Windows 10 box at hand to test if this is a general issue.

I understand there's no SSH specific keyboard layout or setting so I don't know where to begin to troubleshoot this.

Thanks!

**Comment by sunjoong** [comment]
@jpbarrios  - I guess... When you access bash through  "Bash on Ubuntu on Windows" icon, i.e., bash shortcut, the console loccale is CP65001 (UTF-8). But if you access through other program, for example bash command in cmd window or ssh client like putty, the console locale might be different. I'll begin to test with checking propery of console program and linux locale in your shoes.

**Comment by jpbarrios** [comment]
@sunjoong - You hit it on the head.  Through the Bash on Windows icon the locale was "en_US.UTF8" but through SSH it was "POSIX".  So I ran "dpkg-reconfigure locales" on the SSH session and changed the locale to "en_US.UTF8" as well and issue solved.  Thanks!

**Comment by sunjoong** [comment]
@jpbarrios - Sound good to hear that solved. But... you look set linux locale to English following console. I thoght you are Spanish user. If linux locale be English, not Spanish, somehow.... Hmm.... I think, you could better to fit console property, not linux locale, if you can.

**Comment by ErvalhouS** [comment]
I have run into this problem when using Xserver simulated terminal. I have ran the Xserver while a different keyboard layout was selected on Windows and changed it. The change didn't reflect into WSL until I restarted the Xserver.

**Comment by therealkenc** [comment]
This one fell trough the cracks it seems. WSL has no idea about "keyboards" (as of this writing). Anything keyboard related is on the Windows side (or some other remote OS for that matter). 

Separately there is the glibc [`locale(7)`](http://man7.org/linux/man-pages/man7/locale.7.html), which isn't strictly speaking a keyboard thing either. Regardless locales work the same as Real Linux™ so no WSL actionable. To the extent there are problems/questions about the keyboard (sic) behavior it would be a [console thing](https://github.com/microsoft/console) (or the third party terminal emulator of choice, or third party X server of choice).
