### ISSUE TITLE
Weird hang in msys2 makepkg after any interop in PKGBUILD

### ISSUE THREAD

**Issue by fpqc** [microsoft/WSL#2018]
I have both msys2 and WSL installed, and I was creating a pkgbuild for the wslbridge in msys2:

https://ptpb.pw/1eW1

This PKGBUILD clones the wslbridge repo in the msys2 environment, then builds the frontend in msys2 and the backend in WSL.  However, I found that this hangs when checking the package.  If you kill msys2 and then enter the directory and do makepkg -R (which skips the build step), the part that was hanging works and the final package is built.  I also tried changing it to use any wsl command, not even `make`, and it still failed the packaging check.

To reproduce, install msys2, and in the msys shell, run the commands
```
pacman -Syu
pacman -S gcc mingw-w64-x86_64-gcc git curl
mkdir wslbridge
cd wslbridge
curl https://ptpb.pw/1eW1 > PKGBUILD
makepkg
```

It's not clear to me if this is a bug in the redirection code in WSL or some bug in msys2, or even in makepkg, but something is locking up, and it only happens after a WSL command is run in the build() section of the pkgbuild.

Windows 10 build 16179

PS This is definitely a case of a devtool failing in a crossplatform compilation scenario, so it seems exactly the kind of problem you'd like to look into.  As I mentioned earlier, the packaging step fails even if you just have WSL bash echo anything.

**Comment by sunjoong** [comment]
@fpqc - That weird hang occurs in "if find "${pkgdir}" -type f -print0 | xargs -0 grep -q -I "${srcdir}" ; then" line of /usr/share/makepkg/lint_package/build_references.sh file.

More strange thing is... if you split this make package job by "makepkg --noarchive" and "makepkg -R", building and packaging, there is no hang. I guess hidden something (maybe bash.exe? or cache?) hold the compiled binary.

BTW, there need not mingw-w64-x86_64-gcc depencancy in your package, so "makedepends=('gcc' 'make')" be more sutable.

**Comment by fpqc** [comment]
@sunjoong Yeah, I realized it didn't require the mingw64 compiler after i made the pkgbuild but before I made this topic, and I didn't change it haha, but yeah, here's the weirdest part:

Even if the line that builds via WSL, 
```
"$(cygpath -u "$SYSTEMROOT")/System32/bash.exe" -c "make"
```
is changed to

```
"$(cygpath -u "$SYSTEMROOT")/System32/bash.exe" -c "echo foo"
```
and the install line for wsl-backend is commented out, it still hangs in the same place, which makes me think it has something to do with the passing back and forth of the handle.

**Comment by sunjoong** [comment]
@fpqc - hang point is xarg program.
```
pkgname=dummy
pkgver=1
pkgrel=0
pkgdesc=dummy
arch=('any')

build() {
        echo "Hang?"
        $(cygpath -u "$SYSTEMROOT")/System32/bash.exe -c "echo foo"
        echo bar | xargs echo
        echo "If not, will hang."
}

package() {
        touch "${pkgdir}"/dummy
}
```

Above package source will hang in build(). If change "echo bar | xargs echo" line to "echo bar", hang occurs before package().

**Comment by benhillis** [comment]
Could this be the same issue as #1973?

**Comment by fpqc** [comment]
not sure. I don't think so because I think it still fails even when no file i/o happens at all, see @sunjoong 's minimal example above.  The WSL operation completes fine, but for some reason it messes up the subsequent xargs operation.

It's not clear to me or the msys2 devs why it's doing that (their bug or yours), but it only seems to be happening in scripts making use of WSL interop.

**Comment by sunjoong** [comment]
```
#!/bin/sh
/c/Windows/System32/System32/bash.exe -c "echo foo"
echo bar | xargs echo
```
Above script has hang. Below script do almost same thing but no hang;
```
#!/bin/sh
/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -command "bash.exe -c 'echo foo'"
echo bar | xargs echo
```

**Comment by sunjoong** [comment]
@fpqc - this emergancy PKGBUILD will work;
```
# Maintainer: mar77i <mar77i at mar77i dot ch>
# Past Maintainer: Gaetan Bisson <bisson@archlinux.org>
# Contributor: Scytrin dai Kinthra <scytrin@gmail.com>

pkgname=wslbridge
_pkgname=wslbridge
pkgver=0.2.1.1.g744be74
pkgrel=1
pkgdesc='MSys2 Bridge for Windows Subsystem for Linux'
url='https://github.com/rprichard/wslbridge'
arch=('i686' 'x86_64')
license=('MIT')
makedepends=('gcc' 'make')
epoch=1
source=('git://github.com/rprichard/wslbridge')
sha1sums=('SKIP')

provides=("${_pkgname}")
conflicts=("${_pkgname}")

pkgver() {
        cd "${_pkgname}"
        git describe --tags |sed 's/-/./g'
}

build() {
        cd "${_pkgname}"
        cd frontend
        make
        cd ../backend
        bash -c "bash.exe -c make"
}

package() {
        cd "${_pkgname}"
        install -Dm755 out/wslbridge.exe "${pkgdir}"/usr/bin/wslbridge.exe
        install -Dm755 out/wslbridge-backend "${pkgdir}"/usr/bin/wslbridge-backend
}
```

BTW, what can we do with this bridge? Some example?

**Comment by fpqc** [comment]
@sunjoong You can use the bridge to launch WSL with the Mintty terminal emulator or msys2-xterm  instead of conhost.exe (for various reasons, mainly buggy or not-yet-implemented control sequences, or problems passing keyboard commands when running in ConEMU).

**Comment by benhillis** [comment]
The underlying issue with #1973 has to do with processes being terminated racing with signal delivery. It doesn't rely on input / output.

**Comment by fpqc** [comment]
@benhillis It seems like pulling the output stream through an additional instance of (msys2) bash -c is fixing it, so maybe it's some kind of subtle incompatibility between their implementation of pipes and the WSL one?

**Comment by benhillis** [comment]
@fpqc Could be, we'd have to debug this locally to see what's going on.

**Comment by fpqc** [comment]
@benhillis @sunjoong By the way, sunjoong's fix doesn't actually seem to help. The reason why it worked is that it's actually not calling the WSL bash at all.

**Comment by sunjoong** [comment]
@fpqc - My bad.  I forgot there is also bash.exe in Msys2! Sorry.

**Comment by sunjoong** [comment]
@fpqc @benhillis - New script having no hang;
```
#!/bin/sh
echo | /c/Windows/System32/bash.exe -c "echo foo"
echo bar | xargs echo
```
It looks like __magic__.

@fpqc - New PKGBUILD;
```
# Maintainer: mar77i <mar77i at mar77i dot ch>
# Past Maintainer: Gaetan Bisson <bisson@archlinux.org>
# Contributor: Scytrin dai Kinthra <scytrin@gmail.com>

pkgname=wslbridge
_pkgname=wslbridge
pkgver=0.2.1.1.g744be74
pkgrel=1
pkgdesc='MSys2 Bridge for Windows Subsystem for Linux'
url='https://github.com/rprichard/wslbridge'
arch=('i686' 'x86_64')
license=('MIT')
makedepends=('gcc' 'make')
epoch=1
source=('git://github.com/rprichard/wslbridge')
sha1sums=('SKIP')

provides=("${_pkgname}")
conflicts=("${_pkgname}")

pkgver() {
        cd "${_pkgname}"
        git describe --tags |sed 's/-/./g'
}

build() {
        cd "${_pkgname}"
        cd frontend
        make
        cd ../backend
        echo | /c/Windows/System32/bash.exe -c make
}

package() {
        cd "${_pkgname}"
        install -Dm755 out/wslbridge.exe "${pkgdir}"/usr/bin/wslbridge.exe
        install -Dm755 out/wslbridge-backend "${pkgdir}"/usr/bin/wslbridge-backend
}
```

I checked it in WSL like this;
```
SUNJOONG-DESKTOP bin # file *
wslbridge-backend: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
wslbridge.exe:     PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
SUNJOONG-DESKTOP bin #
```

**Comment by therealkenc** [comment]
Taking word "better now". If there are other problems related to pipes and msys2 feel encouraged to reboot under a new issue.
