### ISSUE TITLE
Lxrun doesn't support dots in usernames while the subsystem does

### ISSUE THREAD

**Issue by debo** [Microsoft/WSL#2029]
Windows build number:  1703 OS Build 15063.138

After I modify the bash user to be the same as the windows one in the format forename.surname when I try to set that user as the default login one with command:
```bash
lxrun /setdefaultuser forename.surname
```
it fails saying:
```bash
PS C:\Users\marco.debortoli> lxrun /setdefaultuser forename.surname
Invalid user name.
Enter new UNIX username:
```
I would expect the command to succeed and be able to use an username with a dot in it. I really don't understand why that should fail being such a format a completely valid one in many other *nix like systems.

**Comment by fpqc** [comment]
Is there any time you would want to do this on WSL? If you are sshing in, it doesn't matter, and if you are directly at the console, you wouldn't want to set up tons of users on your own windows user as defaults.

**Comment by debo** [comment]
Well basically yes, I'd like this all the time mostly because I would like my WSL user to be the same as the Windows one because reasons. It's also quite counter intuitive that I can amend my user name withing the WSL environment but then `lxrun` doesn't recognise it.

Moreover, in my opinion, why a subset of the system should have a different user? From a user perspective I see WSL the same as say PowerShell or the command prompt and in those the user is the system user.

I hope my rationale makes a bit of sense. To be honest, if there is a workaround in which I can setup the default user manually I am happy to use that.

Where does lxrun stores the startup options for WSL?

**Comment by benhillis** [comment]
@debo - First: I want to be clear this isn't officially supported and do not take this statement as me documentation (vague as it may be). It would be possible for somebody to configure a user account and update some registry keys to make it the default.

**Comment by debo** [comment]
@benhillis I appreciate it might be officially supported by `lxrun` but it is supported by everything else around it so I guess I'm willing to take the risk :-) any chance you know where lxrun stores its data?

**Comment by benhillis** [comment]
@debo - You are entering unsupported waters, be careful when modifying registry keys.

That being said...
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss`

**Comment by debo** [comment]
@benhillis I know and I take full responsibilities, also it's a VM so worst case scenario I'll start from scratch or just recover from the restore point. Thanks for sharing the information, very much appreciated.

**Comment by benhillis** [comment]
@debo - you are welcome. I'm sorry for being vague, I want to help you but don't want to unintentionally document something we'll likely be changing in the future.

**Comment by debo** [comment]
@benhillis not a problem, I do perfectly understand and in all honestly in the long term a seamless solution where the default OS user is inherited would be my preferred choiche if possible, especially considering that Windows doesn't have such limitation and nor does Linux so there is no real technical limitation that I am aware of to prevent such a behaviour.

**Comment by WeyldFalcon** [comment]
@debo  Did the reg change work for you? I change the key and still am logged into the old account when opening Bash.

**Comment by debo** [comment]
@WeyldFalcon yes, it worked like a charm and no problem to report to date. Did you make sure the bash user is setup properly and that the home folder is updated accordingly?

**Comment by WeyldFalcon** [comment]
@debo pretty sure, a home folder exists for the new user. Did you need to restart your windows machine?

**Comment by debo** [comment]
@WeyldFalcon I might have yes, I don't remember now, but it's windows after all :)

One question though, can you login with the new user? In order to test that set the default user as the root one and then from bash run `su [new user]`

**Comment by WeyldFalcon** [comment]
@debo yes I am able to login as the new user with su. I stay in the same home folder so I have to change directory to the new user name's home but it exists. I will try restarting tonight.

**Comment by jeffvandyke** [comment]
I just renamed my Linux username to match my windows one (with a dot character) using `/setdefaultuser root` and usermod, and I also updated the registry to force the default username, uid, and gid to be my new username with a dot character. So far, working fine, and I think it would be nice if lxrun allowed this directly, since this is definitely supported by Linux.
