### ISSUE TITLE
Cannot see mounted-to-folder volumes in `/mnt`

### ISSUE THREAD

**Issue by qinq-net** [Microsoft/WSL#2034]
* Your Windows build number: 10.0.15063

* What you're doing and what's happening: Cannot find volume mounted to an empty NTFS folder

* What's wrong / what should be happening instead: Should be able to access the volume through `/mnt/c/folder/mountpoint`

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
N/A

**Comment by fpqc** [comment]
Reread the blog post:
https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

The _only_ drives that will be automounted by WSL are _fixed NTFS drives with an assigned drive letter_.  Mounted-on-empty-folder mounts have to be mounted in WSL as per the blog post.

**Comment by benhillis** [comment]
Question has been answered.
