### ISSUE TITLE
ufw returns errors

### ISSUE THREAD

**Issue by BaranCODE** [Microsoft/WSL#2042]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Typing the command "ufw status" returns the following error:
"ERROR: problem running iptables: iptables v1.6.0: can't initialize iptables table 'filter': Table does not exist (or do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded."

* What's wrong / what should be happening instead:

Command should be returning "Status: inactive" instead. The ufw enable and disable commands don't work either.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Running "strace -o strace.txt -ff ufw status" produces the following files (renamed to be uploadable):
[strace.366.txt](https://github.com/Microsoft/BashOnWindows/files/967392/strace.366.txt)
[strace.367.txt](https://github.com/Microsoft/BashOnWindows/files/967393/strace.367.txt)
[strace.368.txt](https://github.com/Microsoft/BashOnWindows/files/967394/strace.368.txt)

**Comment by fpqc** [comment]
iptables has both userspace and kernelspace components.  The kernel module part of iptables does not exist in WSL (which is why it asks you to run insmod, since it's not detecting the expected module).  I think it will be neat if MS decides to support something like IPtables though.

**Comment by therealkenc** [comment]
#767
