### ISSUE TITLE
Bash not starting in current directory for virtual drive

### ISSUE THREAD

**Issue by amiram** [Microsoft/WSL#2043]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063
Ubuntu 16.04.2 LTS

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
C:\Windows\System32>cd \
C:\>bash
user@pc:/mnt/c$ exit
C:\>A:
A:\>bash
user@pc:~$
```

* What's wrong / what should be happening instead:
bash should start in /mnt/a
A is a virtual drive created by veracrypt. It is working fine for D:.
It worked fine in ubuntu 14 before the creators update. Now I use ubuntu 16.

**Comment by fpqc** [comment]
WSL doesn't currently support all kinds of virtual drives.

First of all: The only volumes that are automatically mounted nowadays are _fixed ntfs volumes with an assigned drive letter_.

All other mounts, including mounts of volumes on empty directories, must be manually set with the mount command in WSL: 

This blogpost explains exhaustively all the current supported filesystems.

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

**Comment by amiram** [comment]
The drive is auto-mounted. If I type "cd /mnt/a" in bash it is working. The only thing that doesn't work is going there automatically when I start bash in "A:". It was working in ubuntu 14.04 before the creators update.

**Comment by fpqc** [comment]
Weird

**Comment by benhillis** [comment]
Could you take ba trace for us? Instructions are on our readme.

**Comment by amiram** [comment]
Do you mean the logman command?

**Comment by benhillis** [comment]
@amiram - correct, the logman command to collect .etl traces.  Thanks in advance!

**Comment by amiram** [comment]
``



[etl.zip](https://github.com/Microsoft/BashOnWindows/files/981334/etl.zip)

**Comment by FHTheron** [comment]
Also found this to be the case, but with a `subst` mounted virtual drive. In my case, `subst W: C:\Work` and I then mount it in WSL with `mount --bind /mnt/c/Work /mnt/w` since `mount -t drvfs W: /mnt/w` doesn't work (wrong fs type).

The above `bind` mount results in:
```
$ mount
C: on /c type drvfs (rw,noatime,uid=1000,gid=1000)
C: on /mnt/w type drvfs (rw,noatime,uid=1000,gid=1000)
```

Then trying to start bash/WSL from a normal command prompt while on the virtual drive doesn't find `/mnt/w` and just drops into `~`.

**Comment by benhillis** [comment]
This is the same issue as #3246, for which a fix is inbound.

**Comment by rjlee0** [comment]
I have a solution with the help of busybox "realpath"
The command line like this:
cmd.exe / c pushd "% V" && c:\tools\busybox\bash -c "relp =` realpath .`; cd $ {relp}; wsl "

> * Your Windows build number:  (Type `ver` at a Windows Command Prompt)
>   10.0.15063
>   Ubuntu 16.04.2 LTS
> * What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
> 
> ```
> C:\Windows\System32>cd \
> C:\>bash
> user@pc:/mnt/c$ exit
> C:\>A:
> A:\>bash
> user@pc:~$
> ```
> 
> * What's wrong / what should be happening instead:
>   bash should start in /mnt/a
>   A is a virtual drive created by veracrypt. It is working fine for D:.
>   It worked fine in ubuntu 14 before the creators update. Now I use ubuntu 16.
