### ISSUE TITLE
Background-coloring of directories is awful

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#2044]
I use CMD and When `ls -l`, the default directory name text-background always appear awful. Can someone please change it?

Examples from Windows-Blue, Black, and Ubuntu Purple-Red backgrounds (the images you will see might be enlarged a bit so it will look less awful but try to imagine this with smaller text):

![1](https://cloud.githubusercontent.com/assets/13021900/25578088/1646bb98-2e74-11e7-8c83-fe6f789bd259.PNG)
![11](https://cloud.githubusercontent.com/assets/13021900/25578090/167121e4-2e74-11e7-9c5b-2b844580419e.PNG)
![111](https://cloud.githubusercontent.com/assets/13021900/25578146/788690a8-2e74-11e7-8be1-11de1dce1e10.PNG)

**Comment by fpqc** [comment]
That's because the 'popup text' color is not set correctly.

**Comment by sillyousu** [comment]
You can try this color scheme https://github.com/neilpa/cmd-colors-solarized

**Comment by benhillis** [comment]
Console issue, not specific to WSL.
