### ISSUE TITLE
Return to git slow

### ISSUE THREAD

**Issue by eygraber** [Microsoft/WSL#2045]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) - Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  When I run a git command that starts a new process (`log`, `commit --amend`, etc...) it takes 3-5 seconds to get back to the shell after killing it (`:q`, etc...)

* What's wrong / what should be happening instead: Running the same command in `cmd` gets me back to the shell instantly

**Comment by nlogozzo** [comment]
What version of WSL are you running? On the bash shell use `lsb_release -a`. Since you are using the new creators update, if you are on 14.04 of ubuntu you are running an outdated version. The creators update supports the new version 16.04. Use the link to update your terminal and try again https://www.howtogeek.com/278152/how-to-update-the-windows-bash-shell/

**Comment by eygraber** [comment]
@nlogozzo 

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by josephbergevin** [comment]
I have the same build. Git is very slow for me as well in the Windows bash shell. When I run `git status`, at best it will take about 3 seconds to complete. But it can much longer. When I run the same command on the same exact repo from cmd.exe it executes immediately.

I was on Git version 2.7.1 and I have upgraded to 2.11. Nothing has changed with the speed though. Any suggestions?

**Comment by therealkenc** [comment]
#1305 #981 and friends. User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system).

**Comment by joshirashmics** [comment]
Can confirm this. git is slower than tortoise.

**Comment by tony1223** [comment]
I got same issue when running  git status,too.

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by tifabien** [comment]
Same for me
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by therealkenc** [comment]
Dupe #981.
