### ISSUE TITLE
Allow using the ssh-agent from PowerShell/Win32-OpenSSH

### ISSUE THREAD

**Issue by chx** [microsoft/WSL#2058]
There's a wonderful [ssh port](https://github.com/PowerShell/Win32-OpenSSH/) by ... um... Microsoft :) Could the two talk to each other please?

**Comment by fpqc** [comment]
One way to maybe do this could be with a virtual smartcard device in /dev that connects to lsass or ssh-agent, since openssh supports storing keys on smartcards.

**Comment by lediur** [comment]
Now that the OpenSSH beta client is publicly available, is there any news around making this possible? Would love to see this use case so ssh key management gets a lot simpler across the Windows / WSL boundary.

**Comment by rupor-github** [comment]
Something like this: https://github.com/rupor-github/ssh-agent-wsl?

**Comment by fpqc** [comment]
@rupor-github yeah, but I think it could be made even more streamlined now with the WSL-windows direct socket connections added in 1803.

**Comment by rupor-github** [comment]
You may be right - but it will require changes in openssh-portable. Also, from https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/ :

"A WSL Unix socket can only communicate with a Win32 Unix socket OR with a WSL Unix socket, but not both. For instance, a WSL Unix socket server can only accept connections from either WSL Unix socket(s) OR Win32 Unix socket(s). So, how is it determined which one is it? It’s based on the path the socket is bound to or connecting to, as specified in the `bind` or `connect` syscall. If the Unix socket path is a DrvFS path (i.e your system volumes mounted within WSL, ex: /mnt/c, /mnt/d etc.) then it can only communicate to a Windows Unix socket. If the path is a LxFS path (i.e Linux mounted volume within WSL, ex: /home, /var, /usr etc.) then it can only communicate with WSL Unix sockets." 

Not sure how this will work...

**Comment by Rondom** [comment]
PowerShell/Win32-OpenSSH#1024

**Comment by therealkenc** [comment]
The OP ask, at least as imagined sharing `AF_UNIX` interop, is combination prerequisite #5961 and the above referenced external ask PowerShell/Win32-OpenSSH#1024. There is also PowerShell/Win32-OpenSSH#1461 on the books, which would get you there. In the meantime one can set up a proxy like `ssh-agent-wsl` mentioned above, or maybe creative use of [jstarks/npiperelay](https://github.com/jstarks/npiperelay) on `\\.\pipe\openssh-ssh-agent` might work.

Notwithstanding open #5961 there is no WSL actionable "could the two talk to each other". Porting over to discussion forum for tips/tricks.
