### ISSUE TITLE
PHP command line app is very slow (stat syscall suspected)

### ISSUE THREAD

**Issue by chx** [Microsoft/WSL#2060]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Version 10.0.15063. lsb_release -a reports Ubuntu 16.04.2 LTS.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am running a PHP command line application. 

* What's wrong / what should be happening instead:

It's slow as molasses.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

It's not failing, it's just slooooow. I'd rather not post the whole thing, I sorted out the syscalls for you: 1984 read, 2043 mmap, 4182 access, 8541 open, 8643 close, 12291 fstat, 12990 getdents, 57261 stat, 66285 lstat calls, the entire syslog is 191371 lines long (if you need the whole log, email me chx1975 gmail and I will send it over). Yeah, that's a lot but then again I have an SSD and 24GB of RAM and the Xeon E3 equivalent of an i7 2600 so I expect it to be quite fast which on Linux it is. Perhaps the results of `{l,f,}stat` is not cached...? There are only 11917 files in the entire tree. How can I help? I am an expert in PHP and if badly pushed, I can use gdb :) (I wrote the [answer](http://stackoverflow.com/a/31240030/308851) on SO on how to use them together. That was hard.)

On a whole another note, mongodb is slow as well. Should I file a separate issue?

**Comment by therealkenc** [comment]
#1305 ([message](https://github.com/Microsoft/BashOnWindows/issues/1305#issuecomment-257742979)) #981 and friends. User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system).

**Comment by chx** [comment]
But that's git and seeking? Or is it the same issue?

**Comment by therealkenc** [comment]
Seek in the issue title was speculation by the OP. The problem is `rsync`, `git`, and your PHP script crap all over `stat`/`lstat`, which is not handled well per the [message](https://github.com/Microsoft/BashOnWindows/issues/1305#issuecomment-257742979) I linked. `getdents` is probably bad too because Windows doesn't have dents.
