### ISSUE TITLE
Cannot connect with ssh ipv4 however can connect with ipv6

### ISSUE THREAD

**Issue by zkrr01** [microsoft/WSL#2063]
When I attempt to connect via ssh with a ipv4 address, I get the message "Invalid SSH exchange identification!".  However if I try an ipv6 address I can connect.  I am currently on 16188 however this has been happening for the last two weeks.  The strange thing is if I try to connect using an ipv4 address on a hyper-v machine Windows 10 machine running the bash instance, both the ipv4 and ipv6 ssh connections works.

**Comment by fermigas** [comment]
You're likely running into an issue that started in build 16176.  Here's a thread on it:

https://github.com/Microsoft/BashOnWindows/issues/1958

The easy fix is to wait as it's a known issue with the way IP_OPTIONS are handled in the latest builds.   

The hard way is to build your own OpenSSH with a fix to the code as kbalint suggests in the above thread. I tried it and it works.   Search the code for #ifdef IP_OPTIONS and comment the section out, then rebuild.

You can get the code here:  

http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable 

Here's how to build and install your new sshd:

http://www.linuxfromscratch.org/blfs/view/8.0/postlfs/openssh.html

Along the way, you'll need the OpenSSL includes which you can get with 

sudo apt-get libssl-dev


A good way to troubleshoot these kinds of errors is to run sshd from the command line.  First, make sure the service is stopped:

sudo service ssh stop

then run the daemon:

sudo $(which sshd) -Dddd

ssh into it from another box with something like

ssh -vvv -p 2200 you@somehost

The -ddd and -vvv options will emit more information about the error you're seeing.
