### ISSUE TITLE
WSL doesn't "remember" last session commands

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#2066]
My build is 15063.158.

I ran different commands like ssh user@ip, I do some other actions, close the session and start another one later in that day but can't print commands from previous session with the arrows (top/button).

For some reason, WSL doesn't remember the commands from previous sessions.

I should note that I didn't felt such behavior in the last versions of Bash...

**Comment by CherryDT** [comment]
Did you happen to have multiple terminals open in parallel? In that case see https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows

Did you happen to close bash in a non-graceful way, e.g. closing the window instead of writing `exit`? This could also be the issue.

In any event it is bash which is managing the history, not WSL.

**Comment by aseering** [comment]
@CherryDT , "it is bash which is managing the history, not WSL" -- that's true, but WSL is managing bash :-)  For example, WSL could attempt to close bash gracefully when the window is closed, so that it has a chance to save its history.

**Comment by therealkenc** [comment]
>WSL is managing bash

This all goes to #834 (and many friends). Every bash session _except the last one_ cleans up correctly (saves history) when the window closes. The last one does not, because the last bash session dies by kernel panic.

**Comment by fabd** [comment]
@therealkenc Thank you.

For anybody reading this, typing `exit` appears to work as a workaround.

**Comment by therealkenc** [comment]
It appears from a cursory test that this was addressed as a happy side-effect of "Allow processes to run without an active terminal" (#709 et al) and possibly #2496. Going to mark as fixedinsiderbuilds 17046. If anyone is still seeing the lost history problem on insiders, ping the thread and I'll take a second look.
