### ISSUE TITLE
warning while starting apache server

### ISSUE THREAD

**Issue by bensonshaji** [Microsoft/WSL#2071]
Just getting this weird warning when I start apache2 server (but server is up and running)

* Your Windows build number:  10.0.15063

* What you're doing and what's happening:  sudo service apache2 start

* What's wrong / what should be happening instead: getting this warning
[Sat May 06 20:46:15.177529 2017] [core:warn] [pid 544:tid 139849605318528] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

**Comment by namiltd** [comment]
https://github.com/Microsoft/BashOnWindows/issues/1953#issuecomment-295370994
