### ISSUE TITLE
Ruby rbenv: error when running 'gem install bundler'

### ISSUE THREAD

**Issue by jc184** [Microsoft/WSL#2074]
I'm running Windows 10 CU build number 10.0.15063.
I'm trying to install Ruby on Rails on a freshly installed Ubuntu 16.04 WSL according to this tutorial: [https://gorails.com/setup/windows/10](url)
and I have installed rbenv and ruby-build. My Ruby version is 2.4.0. When I run the bash command `gem install bundler` I get the following error instead of a successful install: `/home/james/.rbenv/versions/2.4.0/bin/ruby: symbol lookup error: /home/james/.rbenv/versions/2.4.0/lib/ruby/2.4.0/x86_64-linux/socket.so: undefined symbol: parse_numeric_port`, so I can't proceed and install Rails. Any gem commands produce exactly the same error. There is very little on the web on this, so I assume it must be unusual. The alternative 'rvm' method installs bundler with no problems.
I'm using rbenv version 1.1.0-2-g4f8925a.
Any help is appreciated.

**Comment by bmassarelli** [comment]
This is another way to install: 

sudo apt-get install rubygems
sudo apt-get install bundler
sudo apt-get install rails

For me works fine!

**Comment by therealkenc** [comment]
> /home/james/.rbenv/versions/2.4.0/bin/ruby: symbol lookup error: /home/james/.rbenv/versions/2.4.0/lib/ruby/2.4.0/x86_64-linux/socket.so: undefined symbol: parse_numeric_port

This one looks like this one was lost in the noise. That's got to be a userspace kind of problem. It would take some Ruby implementation debugging to figure out why it is missing, mind; but it seems pretty academic at this point. Thanks for the follow-up @bmassarelli.
