### ISSUE TITLE
setting shmmax value permission denied (windows 10 creator update)  Solved!

### ISSUE THREAD

**Issue by yubaub** [Microsoft/WSL#2080]
New features at windows 10 creator update page, shows : Shared memory support required by PostgreSQL & other tools

So I updated to Windows 10 creator update. But still I am not able to set shmmax value.
Error msg:
"cannot create /proc/sys/kernel/shmmax: Operation not permitted"

Is this feature not supported yet? I have to run a specific program on linux environment and it only opens with shared memeory allocation. If I am able to run it in my laptop, that will be great to me.

Any help will be highly appreciated.

**Comment by benhillis** [comment]
@yubaub - Could you please provide a little bit more information about what binary you are running by filling out the Issue Template?

Shared memory itself is implemented but not all of the associated procfs files.

**Comment by yubaub** [comment]
Hi benhillis, to run that program, I have to  edit /etc/init.d/rc.local by inserting following lines -

SHMMAX = (same value)
echo Setting up shmmax:
echo ${SHMMAX} >> /proc/sys/kernel/shmmax

and then do ./rc.local start

**Comment by stehufntdev** [comment]
/proc/sys/kernel/shmmax isn't currently supported, and it looks like no maximum is currently enforced.  Is the lack of the file preventing a program from running?  If so, what is the application?

**Comment by yubaub** [comment]
@stehufntdev: Its scientific data analysis program. NSCL SpecTcl.  Is there
other way to set SHMMAX value?

**Comment by stehufntdev** [comment]
Thanks for the additional details.  SHMMAX value can't be set today, but as I mentioned it is already at the maximum value.  Marking this as a bug so we can track a fix.

**Comment by therealkenc** [comment]
`/proc/sys/kernel/shmmax` did come up previously with Chrome, but Google [dropped](https://github.com/Microsoft/BashOnWindows/issues/648#issuecomment-261699313) reading the entry some time ago (thus I never filed a github issue). On earlier releases I had worked around the gap with a patch.

While I haven't tried (my nuclear reactor is offline), something like NSCL SpecTcl, as with Chrome, will almost certainly unblock if `shmmax` returned 18446744073692774399 (0xffff ffff feff ffff) on read and acted like `/dev/null` on write.

**Comment by yubaub** [comment]
@therealkenc  The program will run if shmmax value is set (even if around few tens of MB) as it is also the case with linux.

**Comment by therealkenc** [comment]
Yes but you might want to check: what is the fail if you don't set it to anything. That `echo ${SHMMAX} >> /proc/sys/kernel/shmmax` fails with `Operation not permitted` because `/proc/sys/kernel/shmmax` simply doesn't exist. But given that NSCL SpecTcl _doesn't actually care_ (it could be a few tens of MB), does the actually app fail somewhere trying to _read_ that value back if it is not set at all in your rc.local script? I wouldn't be surprised if there is a later fail on the read, but it doesn't hurt to try if you haven't already.

**Comment by yubaub** [comment]
magically, I just  tried the opened the program and it worked. May be they fixed the bug. 

BTW, how much shared memory is allocated for linux system? or it is adjusted to memory dynamically. (if the program demands more memory, it will be allocated)

**Comment by therealkenc** [comment]
> magically, I just tried the opened the program and it worked. May be they fixed the bug.

No the bug (if you can call it that) is that `/proc/sys/kernel/shmmax` doesn't exist in WSL; it still does not in 16193. NSCL SpecTcl just doesn't actually care that it is missing. The entry is just a limit value, which I gather can in theory be set for reasons. On my 64-bit Linux 4.8 kernel VM it defaults to the ridiculously large number cited earlier, which in effect means "however much shared memory you want if it is available".

**Comment by therealkenc** [comment]
Sunil addressed this in #1753. Fix is in FCU.
