### ISSUE TITLE
Inconsistent Color in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by computersarecool** [Microsoft/WSL#2089]
I am using `Microsoft Windows [Version 10.0.16188.1000`

There is a very strange color issue. I am using `Emacs` and for one of my themes, the colors are not being displayed at all.  I am using the [Cyberpunk Emacs theme](https://github.com/n3mo/cyberpunk-theme.el) which is normally very colorful but basically no colors are rendered.

Here is a picture:

![color issues in Bash for windows](https://cloud.githubusercontent.com/assets/5414692/25981965/75f7a2fc-368d-11e7-874a-b1345db8a56b.png)

What is strange is that, when I Alt-Tab (and the many smaller windows appear) you can actually see the colors.

I know that the other colors work because  other colors work and when I preview colors within Emacs, I see all other 256 colors
![all colors in emacs](https://cloud.githubusercontent.com/assets/5414692/25981987/a49ea358-368d-11e7-9f9a-2d7bc793f210.png)

The above image was taken on the same machine.

I know that this theme works because on my Linux partition, all colors are shown. 

Thanks for any insight

**Comment by Line117** [comment]
Sorry for the answer is not to the point.
Try using this (http://conemu.github.io/ Preview Version) console emulator. He solves many problems.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#108
