### ISSUE TITLE
Replace SimSun, MingLiu, MSGothic, GulimChe with one (or four?) decent monospace fonts.

### ISSUE THREAD

**Issue by be5invis** [Microsoft/WSL#2091]
**THEY ARE UGLY, REALLY**.

The new font(s) should be:

 - Exact half-width monospace, to prevent full-width glyphs being stretched or alignment being broken.
 - No bitmap. In vector.
 - Well hinted.
 - Follows regional (CCJK) orthographic standards and aesthetic habits.

**Comment by SRGOM** [comment]
I want this too but I highly doubt anyone would (or could) help you here. If you're looking for a font that works well in the X env, I doubt this team will tries to mess too much with the ubuntu userland. Even if they did, their expertise is very far from understanding fonts. 

Outside X env, I doubt their team can touch much anway. This belongs to a different team.

I just noted that you're at MS yourself. It looks to me like you're closer to help solve this problem than anybody else. And while you're at it, can you have MS remove all the "Ming" fonts from the following: "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink\"? 

It's almost universally accepted that Ming fonts are not suitable for screen. So I would like them not being linked by default

**Comment by SRGOM** [comment]
Oh, and while you're at it, can you ask MS to comission someone to make a good non-Ming font that covers CJK-ext-2? 

Hanazono and MingLiu_HKSCS-ExtB both look horrible.

Thanks!

**Comment by zadjii-msft** [comment]
@be5invis Hey, could you open a mail thread with richturn AKA @bitcrazed (he'll CC the rest of the team) on this? I'm sure we'd be more than happy to get some help getting better fonts in the console by default :)

**Comment by be5invis** [comment]
@SRGOM Cover Ext BCD? This may take $10M and 5 years to make that font.

**Comment by SRGOM** [comment]
@be5invis: I am not arguing with you, I'm only trying to understand-  but do you guys not use Chise IDs or cjk decomposition or something similar for making fonts? In that case wouldn't the work be greatly reduced? 

I know 42000 is a large number and I have no clue about how typefaces are designed but 15 expert-man-minutes for a symbol would give the impression that you manually-design every single symbol.

**Comment by be5invis** [comment]
@SRGOM 
Using IDS cannot create a typeface fitting the quality requirements of type designers.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#107
