### ISSUE TITLE
Unable to change home directory

### ISSUE THREAD

**Issue by hippyjim** [Microsoft/WSL#2094]
Changing the user home directory to another location - such as another drive where work files are stored - means you can no longer control file permissions as they are outside of the fake Linux filesystem.

**Comment by benhillis** [comment]
This is a current limitation of DrvFs (/mnt/c/... etc).  We are looking at ways to improve DrvFs support for Linux metadata.

**Comment by benhillis** [comment]
DrvFs now supports mounting with metadata, so this is now possible.
