### ISSUE TITLE
[Interop] cmd.exe from clean bash install results in Input/Output error

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#2096]
Build 16193

Installed a clean instance of Ubuntu 16.04, in WSL to test this (see the log), and launching

`/mnt/c/Windows/System32/cmd.exe`

fails with 
```
fpqc@FPQC-PC:/mnt/c/Users/fpqc$ /mnt/c/Windows/System32/cmd.exe
-bash: /mnt/c/Windows/System32/cmd.exe: Input/output error
```

[log.txt](https://github.com/Microsoft/BashOnWindows/files/998124/log.txt)

I did it from `wsl.exe`, but it does the same exact thing with `bash.exe`

```
C:\Users\fpqc>bash
fpqc@FPQC-PC:/mnt/c/Users/fpqc$ /mnt/c/Windows/System32/cmd.exe
-bash: /mnt/c/Windows/System32/cmd.exe: Input/output error
fpqc@FPQC-PC:/mnt/c/Users/fpqc$
```

**Comment by 0xbadfca11** [comment]
I feel same as my issue #1877.
Try run ``compact /compactos:query`` outside of bash.
If "The system is in the Compact state." is shown, this.

**Comment by benhillis** [comment]
@0xbadfca11 - I think you may be correct.  I installed the most recent prerelease build that has not yet been released (16197) and interop is working again.  It's possible the most recent insider build has a bug with compact mode that has been fixed since the build snapped.

**Comment by fpqc** [comment]
@benhillis I turned off compactos and it worked (ssd is big enough, didn't need the 3gb of extra space, plus boot from nvme seems to be faster w compactos off).

Was the problem that you were not checking for transparent compression before executing the file, so it was detecting the compressed binary as an invalid PE file?

**Comment by benhillis** [comment]
There are actually no changes from our driver in the past two Windows Insider builds.  I'll sync up with @SvenGroot next week to make sure we're handling compact OS stuff correctly, since I believe it's implemented as a reparse point.
