### ISSUE TITLE
Killing processes with Task-Manager leads to bugs

### ISSUE THREAD

**Issue by florianluediger** [Microsoft/WSL#2105]
My build number: 15063

When running an interactive program like nano or htop inside of bash, killing it with the Windows Task-Manager leads to the following bugs:
1. The console screen does not get cleared and it stays in the background (in this example htop)
2. Clicking with the mouse inside of the bash window prints unexpected strings into the command line. These strings depend on what you do with your mouse (click-drag or click)
![image](https://cloud.githubusercontent.com/assets/7590163/26036215/d4c225b6-38d9-11e7-84fe-fd29e2bb89af.png)

Steps to reproduce:
1. Start htop
2. Kill it from the Windows Task-Manager
3. Click inside of the Bash window

**Comment by benhillis** [comment]
I tried this locally and I'm seeing the same behavior even when I kill processes from within wsl (by using kill -9 to kill htop).

**Comment by BenGoldberg1** [comment]
Most terminal user interface programs (TUIs) try to intercept signals sent to them, and then reset the terminal using 'stty sane' when a signal is gotten.  Signal SIGKILL cannot be intercepted, and the program exits without resetting the terminal.

The solution is to use a lesser signal, such as SIGINT, which is interceptable, and which will allow the TUI to clean up after itself.

Or, if you **must** use SIGKILL (aka kill -9), or the windows task manager, then in the bash window, manually type 'stty sane'.

**Comment by therealkenc** [comment]
This got marked discussion somehow. Much water under the bridge since May 2017, but I just tried killing `nano` from the task manager and the behaviour is much better in recent releases. Too lazy to dig up the bug/dupe/release that actually addressed it. My experiment was on 17672 but I wager it was addressed in FCU.
