### ISSUE TITLE
Use my Windows profile as Linux home

### ISSUE THREAD

**Issue by gmmedia** [Microsoft/WSL#2108]
Hello,
is it possible to use my Windows profile folder as my home directory in the BashOnWindows?
I have all my files there an see no sense of having a second home directory.

thanks
Jochen

**Comment by sunjoong** [comment]
@gmmedia - No, you can't do it as I had heard; #449.

**Comment by fpqc** [comment]
This can screw up things that rely on linux semantics and permissions.  Also, your profile will be world-readable, writable, and executable to all Lx users associated to your windows user instance.

**Comment by gmmedia** [comment]
Thank you for your answers. I have no other users on my computer, so the file permissions are not really a problem.
But I think Microsoft have to come with a supported feature for that.

**Comment by sunjoong** [comment]
@gmmedia - Well... That's somehow a cheat, not a standard, and will never be a regular feature because so many side-effects may occur, I think. @fpqc mentioned permission issue. I'd like to point other one, #2025; At this point, you might not use `make` utility because of incorrect timestamp. Someday, MS could fix that, but there will be so many traps we don't know yet.

**Comment by aseering** [comment]
@gmmedia -- regarding permissions, for what it's worth, even if you don't think you need file permissions, your software may beg to differ :-)  For example, `ssh` will refuse to use keys that are world-readable, even on a single-user machine.

Also, note that Linux uses file permissions to determine whether a file is an executable program.  That functionality doesn't work either, in DrvFs right now.  If you (or tools that you use) try to install Linux programs within your home directory, the installation may fail and/or have weird side effects.

**Comment by sunjoong** [comment]
@gmmedia - You said "I have all my files there" and... that was just why you wanted to "Use Windows profile as Linux home"... If so, to use https://github.com/goreliu/wsl-terminal might be a way, I think; In 
the Usage section of wsl-terminal Readme.md, there is written as "3. Run tools/add-open-wsl-here-menu.js to add a Open WSL Here context menu to explorer.exe". That means... you can open bash terminal by mouse right button after openning folder what you want with windows file explorer.

**Comment by gmmedia** [comment]
I like the terminal that comes with Windows.
So I have used that doku to add the the Bash to my Explorers context menu: https://www.howtogeek.com/270810/how-to-quickly-launch-a-bash-shell-from-windows-10s-file-explorer/

**Comment by fpqc** [comment]
@gmmedia easiest thing to do is 

`ln -s ~/files /mnt/c/Users/%yourwindowsuser%`

so you can cd files and get to your windows user profile  directory

**Comment by gmmedia** [comment]
Sure, thats an easy way to cd to my files.
Will will also do backup of my home directory to Onedrive

**Comment by JoBrad** [comment]
I have certain directories (like .ssh) symlinked to my Windows user home. But this seems like a good way to screw up both the Linux and Windows user accounts. I value my ability to simply blow the Linux distro away and re-install with minimal effort.

**Comment by therealkenc** [comment]
This scenario is supported in the 1803 April Update ([17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063)) via the metadata mount [option](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/). Ref #2612.
