### ISSUE TITLE
UPnP-IGD using the miniupnpc python package doesn't work.

### ISSUE THREAD

**Issue by zadjii** [microsoft/WSL#2119]
15063 - Creator's Update

I'm trying to use the python version of [miniupnp](https://github.com/miniupnp/miniupnp) for IGD (port forwarding), and it seems as though it isn't working when hosted in WSL. 

They have a test script here: [link](https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/testupnpigd.py)

Installation of the test script:
``` bash
sudo pip install minipnpc
curl https://raw.githubusercontent.com/miniupnp/miniupnp/master/miniupnpc/testupnpigd.py > main.py
python main.py
```
This should print an address, eg `http://67.171.123.456:12345`
In another terminal, run `curl http://67.171.123.456:12345` with the address from before. Or you can open it up in your browser. Or whatever you want - though my Android phone doesn't seem to be able to get the page.

Expected output:
![image](https://cloud.githubusercontent.com/assets/534075/26139512/f9e338b4-3a85-11e7-9c2f-a466b4b80108.png)
(with your IP though)

What actually happens:
The curl just hangs. 

I can see that the port is forwarded in the router's UPnP settings just the same as it is from the working version on my linux box on my desk, so I figure there's a chance there's some WSL has a part to play.

**Comment by sunjoong** [comment]
@zadjii - Does your port, i.e., 12345, listen? I think you could check it by "`netstat -aq`" command. Open bash console and cmd console. Command "`python main.py`" in bash console and "`netstat -aq | 12345`" in cmd console. In my case, https://github.com/Microsoft/BashOnWindows/issues/1498#issuecomment-300194700 , "It looks like your Anti-Virus was blocking the program from listening." You might not be in a similar case but... it could be better to check tcp port listen or not.

**Comment by zadjii** [comment]
![image](https://cloud.githubusercontent.com/assets/534075/26160328/d03c8434-3ad5-11e7-9d6f-6aed85ea5f36.png)
Curiously enough, netstat didn't show *anything*, though I was able to curl the tester using the internal port.

**Comment by sunjoong** [comment]
@zadjii - I said command `netstat` in cmd.exe console. There is an another issue of `netstat`, #1488, that I cannot be sure whether it be fixed. There seems many network related issues like #1554, #1498, #1385 and more. It could be helpful to collect log following https://github.com/Microsoft/BashOnWindows/issues/1853#issuecomment-301176037 for clarifying issue; In that comment, @sunilmut said the command "`nc -4 -l 127.0.0.1 8000`" but your tcp port is not 8000, so command like this - "`netstat -qp tcp | findstr 12345`" in cmd.exe console if your port be 123435.

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
