### ISSUE TITLE
PowerShell 6.0.0-beta hung up in Windows 10 Bash Console.

### ISSUE THREAD

**Issue by MaximoTrinidad** [microsoft/WSL#2124]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
C:\Users\mtrinidad> ver

Microsoft Windows [Version 10.0.16193.1001]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I recently upgraded Windows 10 Insider build with Bash already been installed.  Then, after installing .NET Core 2.0 Preview, PowerShell stopped working (no errors).

I got an issue with PowerShell6.0.0-beta that gets hung up in Bash Console (only) after Installed .NET Core Preview 2.0.  But using Ubuntu Desktop in X-Server work good.

So, I'm wondering if my Bash installation gets also update or should I uninstalled then reinstall Bash again.  If this could help clear the issue. 

* What's wrong / what should be happening instead:
Type: powershell 
##> expected result is to open powershell in bash console.
 
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

![poshbeta_bashconsole_2017-05-17_10-28-40](https://cloud.githubusercontent.com/assets/19892435/26162201/185a3a18-3af4-11e7-9de7-38baab5cc2d9.jpg)

![poshbeta_bashgui_2017-05-17_10-28-40](https://cloud.githubusercontent.com/assets/19892435/26162228/27f6342c-3af4-11e7-90ae-ddbb47412a7c.jpg)

**Comment by fpqc** [comment]
This is linux powershell, not windows powershell, right?

**Comment by MaximoTrinidad** [comment]
@fpqc, 

Yes! In the first image, I opened Bash console, and the second I have Ubuntu Desktop loaded.  By the way, Windows 10 PowerShell 6.0.0-beta is working fine wit .NET Core 2.0 Preview.

:)

**Comment by fpqc** [comment]
Yeah, the Microsoft .net Core team and powershell team have active bugs listed on this github repo.

**Comment by MaximoTrinidad** [comment]
@fpqc,

I'm tempted to do a clean Bash setup, then do a PowerShell Beta install to see if the .NET Core 2.0 Preview had something to do with PowerShell not opening.

I will try this on my VM at home this evening.  I got to try it!

**Comment by MaximoTrinidad** [comment]
FYI 

I completed testing PowerShell 6.0.0-beta on my Window 10 Bash Console. I uninstall and did a clean Bash installation **without** .NET Core 2.0 Preview 1 and PowerShell is getting hung.

1. lxrun /uninstall /full
2. lxrun /install
3. Open Bash Console.
4. sudo su  ##-> Prepare for PowerShell Beta Install
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
    exit
5. sudo apt update
6. sudo apt upgrade ##-> This command will also install PowerShell
7. Open PowerShell ##-> But it hungs, the prompt won't come up.

![powershellhungbash](https://cloud.githubusercontent.com/assets/19892435/26181329/387f8f02-3b3d-11e7-85bf-6400e2491bf5.PNG)

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/117182659-7d595d00-ad8b-11eb-8470-594876483836.png)
