### ISSUE TITLE
Infinity ...

### ISSUE THREAD

**Issue by Luuk34** [microsoft/WSL#2139]
With the example code found here (C#):
https://msdn.microsoft.com/en-us/library/system.dividebyzeroexception(v=vs.110).aspx

I created a console application, and found this to be the output:

`D:\Documents\Visual Studio 2015\Projects\DivisionByZero\DivisionByZero\bin\Debug>DivisionByZero.exe | bash -c "hexdump -C"
00000000  38 0d 0a                                          |8..|
00000003

D:\Documents\Visual Studio 2015\Projects\DivisionByZero\DivisionByZero\bin\Debug>subst z: .

D:\Documents\Visual Studio 2015\Projects\DivisionByZero\DivisionByZero\bin\Debug>z:

Z:\>DivisionByZero.exe | bash -c "hexdump -C"
00000000  e2 88 9e 0d 0a                                    |.....|
00000005

Z:\>DivisionByZero.exe | bash -c "hexdump -C"
00000000  38 0d 0a                                          |8..|
00000003

Z:\>
`

I'm confused with this output...

I know the output should be eight ('8') but sometimes it looks like infinity (or the other way around ... ;)

**Comment by poizan42** [comment]
The example code in the link you have provided should print "Division of 3000 by zero.". The code in the remarks section prints "Infinity" - or possibly "infinity" translated to your current locale. None of these should output 8.

Maybe you should tell what code you are actually running, and what the output is before piping it through hexdump?

**Comment by 9-11** [comment]
In my case it prints only 
00000000  e2 88 9e 0d 0a  |.....|
00000005
It is a utf8 representation of U+221E (infinity)

**Comment by Luuk34** [comment]
I am talking about this code:
`using System;

public class Example
{
   public static void Main()
   {
      int number1 = 3000;
      int number2 = 0;

      Console.WriteLine((double)number1 / number2);
   }
}
`

Compiled with Target framework '.NET Farmawork 4' .

When i'm compiling wit lower framework, i see 'infifinty'

Im still search for why i sometime get '8'as response...

**Comment by therealkenc** [comment]
The code prints '`8`' in Windows, nevermind what WSL interop or `hexdump` does with the output. This is with dotnet core 3.1 (though but that's sort of beside the point in the context). Possibly by-design "don't divide by zero that doesn't make sense", but either way not WSL actionable.

![image](https://user-images.githubusercontent.com/7049700/73115648-cf030e80-3edd-11ea-97ad-42068cb57445.png)
