### ISSUE TITLE
access to mapped network driver or shared folders?

### ISSUE THREAD

**Issue by Skye347** [Microsoft/WSL#214]
I got some shared folders and 
1) map them to network drivers. But I cannot find these drivers in /mnt .Is there something i missed?
2) use mklink, then I got  ' bash: cd: main: Input/output error '
Is there any way to use them in bash?

**Comment by mphaney** [comment]
There is also a UserVoice topic related to this.  I've voted for it because this is most definitely something I'll be needing as well.

[https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13313280-access-to-network-shares-and-removable-drives](url)

**Comment by TheAggressive** [comment]
It would be nice to see added Network Drives listed in the `/mnt` directory. So once you add a network drive on the windows side, its configured to pull in the new added drive in the `/mnt` directory.

**Comment by cerebrate** [comment]
While it's only a partial workaround (since cifs-utils doesn't succeed in mounting the drive), in the interim it's worth noting that Samba (the smbclient package) works perfectly under WSL and will let you at least move files back and forth from SMB/CIFS network shares.

**Comment by pvenky** [comment]
I've found two places (@cerebrate's comment included) that say smbclient works perfectly. This is not the case for me. I get the following error when I try smbclient:
`ERROR: Could not determine network interfaces, you must use a interfaces config line`
Any ideas on how to fix this?

**Comment by pvenky** [comment]
Wait... seems like I may have just found the answer. A line in `/etc/samba/smb.conf` that declares the default interface to use just had to be uncommented.

**Comment by acastaner** [comment]
Just out of curiosity @pvenky, what interface name did you use? I tried eth0 because I can't seem to list my network interfaces (ifconfig or ip link return errors) and that still doesn't work.

**Comment by pvenky** [comment]
@acastaner I can't use `ifconfig` either (and I think that is a known limitation). However, the line in `smb.conf` does say eth0. This is the line
```
interfaces = 127.0.0.0/8 eth0
```

**Comment by Ferrisbane** [comment]
I'm having the same issue with mounting a share.

**Comment by cerebrate** [comment]
For reference, my interfaces line is:

interfaces = lo eth0 eth1

(Both eth0 and eth1 since my machine has two network cards, one wired, one wireless.) I believe that including the loopback interface, lo, is necessary for this to work properly - if you haven't included it by name, try that?

**Comment by acastaner** [comment]
I have tried both ``127.0.0.0/8 eth0`` and ``lo eth0``, but when I run smbclient the OS still tells me it can't find any network interface:

> arnaud@CLAVAIN:~$ smbclient
> WARNING: The "syslog" option is deprecated
> WARNING: no network interfaces found

So not sure what's happening here or how to troubleshoot.

**Comment by cerebrate** [comment]
Oh! Have you tried using smbclient to connect to a server anyway, though? You'll always get the no-network-interfaces-found warning (since the relevant ways to find them aren't yet part of WSL), but if you specify the interfaces explicitly, that doesn't matter and you can safely ignore the warning. My setup produces those same warnings every time I run smbclient, but it connects and moves files about just fine.

**Comment by acastaner** [comment]
Ah, right, actually trying to connect and ignore the error seems to work, I can ``ls`` the files. Nice. Still doesn't solve my issue though since I need to be able to rsync, but it's good to know this works.

**Comment by cerebrate** [comment]
@acastaner Hm. You could work around that by running rsync as a daemon at one end or the other, maybe? I believe both cwRsync and DeltaCopy can support that for Windows.

**Comment by hifi** [comment]
I also need this. Can't use WSL at work until network drives can be accessed directly. As a workaround, cygwin works for now but the performance is horrible compared to WSL.

**Comment by GSam** [comment]
smbclient -L localhost --option='interfaces = eth0' works fine for me. 

I can't seem to connect to the administrative shares (C$, Admin$) but this is probably some other registry or configuration issue. If I share a folder on the same machine, I can access it (this would be more interesting the other way around, having a Samba share accessed through Windows).

**Comment by Ferrisbane** [comment]
@GSam That command works for me, I am also able to browse the shares apart from the windows shares C$, Admin$ etc.

I just need to be able to mount the share then I would be able to actually use Bash On Windows, at this point it's useless for me as all development files are on a shared raid server.

Currently using cygwin however having some issues with that, something I believe Bash on Windows would fix.

**Comment by GSam** [comment]
@Ferrisbane I seem to have just figured out how to get the Samba file server somewhat working in Bash on Windows. That may very well be a plausible alternative to mounting the shares.

**Comment by willauld** [comment]
Just tried mapping a network drive and looking for it in /mnt. It is not working properly (as expected since this item is still open). Any idea of when this might be fixed?

**Comment by immunochomik** [comment]
+ 1

**Comment by Ferrisbane** [comment]
I can **not** see any interest from MS in this...

All they have said (about half a year ago - see link below):
> "on our backlog, but not currently scheduled"

This feature is (in my eyes) the **most** important,
forget tabbed windows (currently voted higher than this)... that's just nice to have.

The ability to mount network shares is **required** for most people Bash on Windows is aimed at (Developers), without this feature bash on windows is **completely useless**.

You can view/vote on the feature here:
[uservoice - mount-nfs-sshfs-samba-smb-network-drives](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13600230-mount-nfs-sshfs-samba-smb-network-drives)

**Comment by benhillis** [comment]
@Ferrisbane - a lot can change in a year.  We understand that this is a required scenario for many of our users and are looking at adding this support soon.

**Comment by MrObvious** [comment]
That would be awesome! Even if we just had fuse support, I think we could make everything else happen.

**Comment by GenesisCraig** [comment]
Here's another vote for this feature.  Having bash access to CIFS mounted filesystems will be great for Sysadmins as well.

Thanks for the great work WSL team.

**Comment by mattjanssen** [comment]
Looks like this feature is happening! [Insider Build 16176](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176) says it can [mount network drives and network locations](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) using the `drvfs` in WSL. I'm assuming this will work for NFS drive mounts, too.

```
$ sudo mkdir /mnt/d
$ sudo mount -t drvfs D: /mnt/d
```

**Comment by laktak** [comment]
@mattjanssen yes but it does not yet work for shared folders (vmware).

**Comment by andyrichardson** [comment]
@mattjanssen Any ideas on when that insider build will go public/beta?

**Comment by laktak** [comment]
You can vote on the UserVoice issue for [shared folders here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/19746880-drvfs-support-for-shared-folders-in-virtual-mach)

**Comment by andyrichardson** [comment]
@laktak That looks like a different issue altogether.

**Comment by pavila10** [comment]
@mattjanssen's tip works for me, but I unfortunately get the following error `fatal: Not a git repository (or any parent up to mount point /mnt/z) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)` when trying to even run git status. Have to use Git Bash CLI or Cygwin (like @hifi suggested) as a work around for now unless someone has a suggestion.

**Comment by therealkenc** [comment]
The OP here was:

> I got some shared folders and map them to network drivers. But I cannot find these drivers in /mnt .Is there something i missed?

Mounting CIFS shares was added in Insider Build 16176 and released Fall Creators Update 16299. The blog post is [here](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/). For other scenarios (meaning different Windows filesystem drivers) see #579 #2896 #2999 #2163 and the like.
