### ISSUE TITLE
Socket error at Rabbitmq-c client

### ISSUE THREAD

**Issue by EugKar** [microsoft/WSL#2143]
* Windows build number:  Version 10.0.15063

* I'm using [Rabbitmq C client](https://github.com/alanxz/rabbitmq-c.git) library with my platform-independent application, so I use Bash for Windows to debug it on Linux. I tried it with both latest revision of rabbitmq-c, and on some August 2016 revision. The same socket error occurred at both my application and library's example from repo. Commands to reproduce the issue at amqp_producer example:
`mkdir build && cd build`
`cmake -DENABLE_SSL_SUPPORT=OFF ..`
`cmake --build .`
`cd examples`
`./amqp_producer localhost 5672 10 5`
assuming that RabbitMQ server is running on localhost.
* What's wrong / what should be happening instead:
I get the following output:
`Publishing: a socket error occurred`.
The expected output is (on Ubuntu 17.04):
`PRODUCER - Message count: 5`
`Total time, milliseconds: 400`
`Overall messages-per-second: 12.4772`

**Comment by bssatya** [comment]
I Am also seeing similar error 
/rabbitmq-c/build/examples# ./amqp_sendstring 127.0.0.1 5672 amq.direct test "hello"
Publishing: a socket error occurred

**Comment by wpycs** [comment]
@bssatya @EugKar  you can modify rabbitmq.config，Listening ports Bound to 127.0.0.1. 
I'm using C# client,it worked. 
But I found a other problem,about few hours, rabbitmq like auto stoped. I can't be connection，Do you have this problem?

**Comment by therealkenc** [comment]
If the `a socket error occurred` error persists on 19043 please open a new ticket with CLI reproduction steps. There is a possibility the error may persist on WSL1 depending on the error. If it does, try WSL2, but note you'll probably (possibly?) need to configure rabbitmq to listen on `0.0.0.0` rather that `127.0.0.1`.
