### ISSUE TITLE
CIFS / symbolic links

### ISSUE THREAD

**Issue by strarsis** [microsoft/WSL#2144]
* Your Windows build number:
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  
````
$ ln -s a b
ln: failed to create symbolic link 'b': Operation not supported
````

* What's wrong / what should be happening instead:
Working symbolic link is created.

A Windows shared folder is mounted in an Ubuntu system (CIFS). 
Creating a symlink inside the mounted shared folder fails.
Can support for symbolic links over network enabled in the new Windows Subsystem for Linux?
CIFS supports Unix Extensions for supporting symbolic links among other Unix typical features.

**Comment by darkguy2008** [comment]
I'm having the same issue and this is important for me :(

**Comment by davidmaxwaterman** [comment]
I hit this trying to do web development where I am using `bower link`. It works in WSL, but I am using VSCode in Windows and so all my code is in `/mnt/c/...`. Since this doesn't work, VSCode gives an error:

```
Error: A system error occured (UNKNOWN: unknown error, stat 'c:\....')
```

I imagine I'd get the same problem with `npm link` (and I wonder if yarn has a similar mechanism).

[paths removed because they're irrelevant]

**Comment by strarsis** [comment]
I access a shared folder on Windows using a Linux VM.
Currently I have to use a workaround which lets specific folders outside of the folder on a Linux file system that supports symbolic links: https://medium.com/@dtinth/isolating-node-modules-in-vagrant-9e646067b36

**Comment by sunilmut** [comment]
Adding @SvenGroot to see if he can help out here.

**Comment by SvenGroot** [comment]
There seem to be two different issues in this thread. The original poster is talking about creating symbolic links on an SMB shared mounted on real Ubuntu Linux with CIFS. SMB does allow the creation of NT symbolic links, but they can't be followed after creation using the default security policy (which I believe can be turned off, but in that case the links are followed on the server, which is very different than how Linux symlinks behave on network shares). SMB does not support creating the type of symbolic links that DrvFs in WSL uses, and that's not something I expect will change in the near future.

@davidmaxwaterman is describing a different problem, namely that WSL symlinks can't be followed by regular Windows applications. This is a problem we are looking at addressing in the future.

**Comment by strarsis** [comment]
@SvenGroot: Concerning symlinks on SMB share - 
creating them doesn't seem to be supported at all, not only following them after their creation:
````
ln: failed to create symbolic link 'b': Operation not supported
````

**Comment by SvenGroot** [comment]
I was talking about NT symbolic links, created with "mklink" from the Windows Command Prompt. I don't think you can create those with CIFS.

**Comment by strarsis** [comment]
On recent WSL (1) this works perfectly. I can create (soft) symlinks on native file system and on the *nix file system without any issues.
