### ISSUE TITLE
Masscan not working.

### ISSUE THREAD

**Issue by megapro17** [microsoft/WSL#2150]
Microsoft Windows [Version 10.0.15063]

sudo apt-get install masscan
masscan -p80 192.168.1.0/24 
```
mega@DESKTOP:/$ sudo masscan -p80 192.168.1.0/24
FAIL: eth0: socket: Invalid argument
adapter[eth0].init: failed
```

Strace log:
https://gist.github.com/megapro17/5f6b1c37ebc43a2436416ad050377e28

**Comment by sunjoong** [comment]
@megapro17 - I saw this line in your log;
> socket(PF_PACKET, SOCK_RAW, 768)        = -1 EAFNOSUPPORT (Address family not supported by protocol)

In https://github.com/Microsoft/BashOnWindows/issues/1515#issuecomment-267736989,
>  Yeah, unfortunately, we don't support SOCK_PACKET yet either.

**Comment by sunilmut** [comment]
@megapro17 - Thanks for your post. [Here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) is the user voice ticket for `AF_PACKET`. If you would like us to prioritize this, please up vote the ticket.

@sunjoong - Thanks for the diagnosis.

**Comment by megapro17** [comment]
I guess this would work in 2004 build. Three years, time passes so fast

**Comment by billswearingen** [comment]
I just tried in the 2004 build, no go :(

**Comment by megapro17** [comment]
> I just tried in the 2004 build, no go :(

Follow these instructions, it works for me
https://docs.microsoft.com/ru-ru/windows/wsl/wsl2-install
https://docs.microsoft.com/ru-ru/windows/wsl/wsl2-kernel

**Comment by billswearingen** [comment]
English Links (Thank you @megapro17 !!)
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
