### ISSUE TITLE
cannot use PATH/LD_LIBRARY_PATH for Windows binaries

### ISSUE THREAD

**Issue by darealshinji** [microsoft/WSL#2167]
Microsoft Windows: Version 10.0.15063

On command prompt I can set `PATH` to make binaries search for DLLs in other directories. But doing the same in bash doesn't work. Setting `LD_LIBRARY_PATH` doesn't work either. It can't find the required DLLs unless I change the working directory.

Here's an example:
```
C:\>cd C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64_x86

C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64_x86>cl.exe

C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64_x86>set PATH=C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64;%PATH%

C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\amd64_x86>cl.exe
Microsoft (R) C/C++-Optimierungscompiler Version 19.00.24218.2 für x86
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Syntax: cl [ Option... ] Dateiname... [ /link Linkeroption... ]
```
The same in bash:
```
djcj@DESKTOP-J6KIB79:~$ cd "/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86"
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$ ./cl.exe
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$ export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64:$PATH"
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$ ./cl.exe
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$ export LD_LIBRARY_PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64"
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$ ./cl.exe
djcj@DESKTOP-J6KIB79:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64_x86$
```

In this example I was expecting `./cl.exe` to find the DLLs from the other directory and to run properly.

**Comment by sunjoong** [comment]
@darealshinji - Try like this;
```
djcj@DESKTOP-J6KIB79:~$ export PATH='/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/amd64':$PATH
djcj@DESKTOP-J6KIB79:~$ cl.exe
```

**Comment by darealshinji** [comment]
Let me give you a better example: I have `yasm.exe` which requires `yasm.dll` and `yasmstd.dll`.
Let's assume I put the DLLs into the sub-directory `dlls`:
in command prompt I can add this directory to PATH with `set PATH=%CD%\dlls;%PATH%` and then yasm.exe will work.
However, when I try the same in Bash with `export PATH="$PWD/dlls:$PATH"` or `export LD_LIBRARY_PATH="$PWD/dlls"` it won't work.

**Comment by sunjoong** [comment]
> However, when I try the same in Bash with export PATH="$PWD/dlls:$PATH" or export LD_LIBRARY_PATH="$PWD/dlls" it won't work.

@darealshinji - Yes, I could not find the way how to set `windows` PATH environment variable `within WSL` too. In this condition, the most simplest way is to set windows PATH environment variable on windows using control pannel-user account-user account-environment variable before launching WSL.

I coppied C:\msys64\usr\bin\bsdtar.exe to C:\Users\sunjoong\Desktop directory, and bsdtar.exe need msys-2.0.dll (and more dlls) but there were no such dlls in that directory.
![ldd](https://user-images.githubusercontent.com/2748000/26945774-d3e240d4-4cc7-11e7-8f4d-d2c29d2c95b5.png)
I could run C:\Users\sunjoong\Desktop\bsdtar.exe becasue I had appended C:\msys64\usr\bin to `windows` Path environment variable.

**Comment by davidhunter22** [comment]
The cmd.exe /C 'set PATH...' worked great for me. In my ideal world though be able to use PATH and LD_LIBRARY_PATH in a bash shell for a Windows binary in the same way as I would for a Linux binary. Note that the title of this article is about PATH but LD_LIBRARY_PATH is as important. If getting PATH and LD_LIBRARY_PATH to work right is hard for Windows binaries would something like a WINDOWS_PATH in bash to mean "append this to the Windows PATH before executing a Windows binary" be easier?

**Comment by therealkenc** [comment]
> In this example I was expecting ./cl.exe to find the DLLs from the other directory and to run properly.

It is possible to get `cl.exe` (or anything else) to run via interop, but you'll need everything typically set up by `vcvars.bat` set up. Linux `LD_LIBRARY_PATH` is unrelated. The Linux loader doesn't know how to load those dlls, and `cl.exe` isn't running in the WSL environment.
