### ISSUE TITLE
Telnet to mapscii.me doesn't work (not enough xterm features)

### ISSUE THREAD

**Issue by timfel** [Microsoft/WSL#2173]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Type `telnet mapscii.me`. This will connect to the server of this project: https://github.com/rastapasta/mapscii. The expectation is to see an ASCII map of the world.

* What's wrong / what should be happening instead:
Expected:
![image](https://cloud.githubusercontent.com/assets/46235/26577534/f23024f4-452c-11e7-873c-be6a9142a62c.png)

Got:
![image](https://cloud.githubusercontent.com/assets/46235/26577499/db5b4c04-452c-11e7-9144-1e7757f7dcef.png)

**Comment by therealkenc** [comment]
It's okay with cmd console here. 16199.

![mapascii](https://cloud.githubusercontent.com/assets/7049700/26582118/bb969f0a-44f4-11e7-8c5c-579f11b40d4a.png)

**Comment by sunjoong** [comment]
@timfel - I'm using `Gentoo`, not Ubuntu, on WSL, and got an interesting screen(?); it looks like to be able to draw shape of land but not to print names in my case.
![map](https://cloud.githubusercontent.com/assets/2748000/26585918/9520de8c-4588-11e7-857f-f15a6bedea4a.png)

**Comment by zadjii-msft** [comment]
@timfel what font & size are you using? I believe that on Insider's builds, it works fine

![image](https://user-images.githubusercontent.com/18356694/28190476-ea49055a-67df-11e7-8781-a62e5c69aff2.png)

Albeit, I couldn't find a font with the right characters

**Comment by shanselman** [comment]
@tara-raj good test case for font fallback.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#104
