### ISSUE TITLE
Un-Bold/-Dim completely absent from ANSI escape codes

### ISSUE THREAD

**Issue by Qix-** [Microsoft/WSL#2174]
It appears `[21m` and `[22m` are _completely_ absent from the [list of supported render mode escapes](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032.aspx) in the new VT-like functionality Windows supports.

You have `[24m` and `[27m`, but no way to reset bold at all. This _needs_ to be fixed because it's breaking a ton of people trying to run Node.js without LibUV's Windows TTY fallback, and I'm sure it'll break a much larger crowd as adoption rises.

Ref chalk/chalk#145 // cc @sindresorhus

**Comment by zadjii-msft** [comment]
I've already got this on the backlog :)
MSFT:9553354

https://github.com/libuv/libuv/issues/438
https://github.com/libuv/libuv/issues/439
https://github.com/chalk/chalk/issues/76

**Comment by Qix-** [comment]
Thank you @zadjii-msft, I appreciate that. Any estimate on ETA? I'd rather not have to write a workaround for chalk if I can have downstreamers hold off for a while longer.

**Comment by zadjii-msft** [comment]
@Qix I'd say it's probably not a very high priority to get into this release unfortunately. I can add it to my bug backlog, but I'd say it's not likely :/

**Comment by therealkenc** [comment]
#2027

**Comment by Qix-** [comment]
@therealkenc That's unrelated.

**Comment by zadjii-msft** [comment]
I just submitted the fix for this :)

... well okay, I submitted the fix for UnBold. Double underline would require a lot more work to support, and that won't make the cut for Fall Creator's Update. But UnBold should be out to insiders in the next few weeks.

**Comment by Qix-** [comment]
@zadjii-msft Thank you <3 I know a lot of people will appreciate this.

**Comment by alancnet** [comment]
@Qix- @zadjii-msft Thank you! I'm very happy to see [the issue I opened back in March](https://github.com/chalk/chalk/issues/145) has seemed to take on a life of its own which ultimately made its way back to Microsoft for a fix. I really appreciate your efforts! Truly!

**Comment by Qix-** [comment]
@zadjii-msft Hey! Just checking in - has this been released? :)

**Comment by zadjii-msft** [comment]
@Qix- I'm pretty sure it's in Fall Creator's Update, yea.

![image](https://user-images.githubusercontent.com/18356694/32671910-0236520e-c5fe-11e7-8069-9293f508ee37.png)


``` python
import sys
import time

def csi(seq):
    sys.stdout.write('\x1b[{}'.format(seq))

def write(s):
    sys.stdout.write(s)

if __name__ == '__main__':
    print('this first test is the unbold test')
    print('Make sure the foo is bright, the bar is not')
    print('\E[1;32mfoo\E[22mbar\E[mTest')

    csi('1;32m')
    write('foo')
    csi('22m')
    write('bar')
    csi('m')
    write('Test')
    print('')

    csi('1;33m')
    write('foo')
    csi('22m')
    write('bar')
    csi('m')
    write('Test')
    print('')

    csi('1;34m')
    write('foo')
    csi('22m')
    write('bar')
    csi('m')
    write('Test')
    print('')
```

**Comment by Qix-** [comment]
Awesome - thanks so much @zadjii-msft <3
