### ISSUE TITLE
Error upon waking from sleep

### ISSUE THREAD

**Issue by prov2433** [microsoft/WSL#2176]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.14393

* What you're doing and what's happening:  
Upon waking up from sleep, the following errors occur when I use Maven (issuing mvn install):
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project urArtId: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

```

**Comment by stehufntdev** [comment]
There's been a number of fixes since the Anniversary Update, can you please try again in the Creator's update or insider builds?
