### ISSUE TITLE
Bash freezes when ssh connection reset due to inactivity

### ISSUE THREAD

**Issue by Kangaroux** [Microsoft/WSL#2184]
**Version**: 15063

**Issue**: If you use `ssh` and then your connection gets dropped for inactivity, bash becomes unresponsive, and you don't receive the expected `Write failed: Connection reset by peer` message. It ignores all input and looks like you're still connected to the server.

**Comment by fpqc** [comment]
This happens on Linux too, doesn't it?  That's why there's an ssh escape key:

https://askubuntu.com/questions/29942/how-can-i-break-out-of-ssh-when-it-locks

press the enter key to clear the hidden line entry, then enter

`~.`
