### ISSUE TITLE
additional symbols are pasted (ref. to issue 2131)

### ISSUE THREAD

**Issue by alexeyshishkin01** [Microsoft/WSL#2204]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
D:\>ver
Microsoft Windows [Version 10.0.15063]
root@Alexey-HP:~# az --version | head -1
azure-cli (2.0.7)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I copy-paste a command into BashOnWindows and additional symbols are pasted:
- what was copied is:
az vm image list-publishers \
> --location northeurope \
> --query "[?starts_with(name, 'Microsoft')]"

- what was pasted is:
root@Alexey-HP:~# az vm image list-publishers \
ion> --location northeurope \
> --query "[?starts_with(name, 'Microsoft')]"

* What's wrong / what should be happening instead:
- additional symbols are pasted
- no additional symbols are expected

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunjoong** [comment]
@alexeyshishkin01 - I think.... Screenshots of `Get-Clipboard` on windwos PowerShell and output of paste like below;
![get-clipboard](https://user-images.githubusercontent.com/2748000/26966985-6683fdaa-4d37-11e7-9d31-0b2d3f4cccc4.png)
Hmm.... and ignore the conents of above screenshots; In there, I pasted "`>`" to show the output of "`i> > --location northeurope`".

**Comment by alexeyshishkin01** [comment]
I'm attaching the screens from:
- notepad
![3](https://user-images.githubusercontent.com/28735514/26970436-1a32f764-4d12-11e7-9452-f1b159ceeec1.jpg)
- power shell
![1](https://user-images.githubusercontent.com/28735514/26970467-320f218c-4d12-11e7-9fd9-b40866303293.jpg)
- bash-on-windows
![2](https://user-images.githubusercontent.com/28735514/26970499-4982b932-4d12-11e7-8b4c-c27b3581e436.jpg)
the main issue it doesn't repeat all the times - sometimes it does happen, the other time it doesn't

**Comment by alexeyshishkin01** [comment]
additional symbols also vary

**Comment by sunjoong** [comment]
@alexeyshishkin01 - I see. You said "ion" of your description and "_" of your bash-on-windows screenshot before ">", like "li" and "u" of below mine;
![ls](https://user-images.githubusercontent.com/2748000/26971550-92cc57fc-4d48-11e7-860b-e6177b5660b4.png)

**Comment by alexeyshishkin01** [comment]
exactly, I also noticed that searching through commands history by pressing up and down arrows can also make additional symbols to appear - it doesn't happen all the time, only from time to time

**Comment by sunjoong** [comment]
@alexeyshishkin01 - Hmm.... "garbage characters display" problem.... I prefer "garbage characters" to "additional symbols". I guess it might be related to terminfo database, but think we'll wait Mike as like before.

**Comment by alexeyshishkin01** [comment]
ok, let's wait for Mike

**Comment by zadjii-msft** [comment]
I'll mark it as a bug, this looks liker it's probably related to the other two bugs, #2131 and #2149.

**Comment by alexeyshishkin01** [comment]
thanks, waiting for the fix

**Comment by sunjoong** [comment]
> it's probably related to the other two bugs, #2131 and #2149.

@zadjii-msft - I feel... this might be from other source. I think this is a "garbage characters display" problem. So, this might be rather related with #1436 or #27, I think. Especially from middle of #27 thread, they discussed garbage charachters of history using up-arrow key that @alexeyshishkin01 said "commands history by pressing up and down arrows can also make additional symbols to appear". #1436 also look like to be realted to terminfo database, but  #2131 and #2149 did not seem to, I guess.

**Comment by alexeyshishkin01** [comment]
ok, pls. don't suggest to install newer OS version this time :-)

**Comment by alexeyshishkin01** [comment]
any news?

**Comment by sunilmut** [comment]
Will have to defer to @zadjii-msft on any update here. But, #2131 is marked fixed in Creators Update (which is what you are running) and #2149 is marked fixed in Windows Insider build 16234 (which is available now if you are on Insider build) or will be eventually on Fall Creators Update.

**Comment by zadjii-msft** [comment]
Okay I've taken a look. It's not the other bugs I linked, that's for sure. I'm not really sure how it's happening yet, but I am assuming it has something to do with the way we're delivering pasted text to the buffer. 

For my own records, the test text is this:
```
az vm image list-publishers \
--location northeurope \
--query "[?starts_with(name, 'Microsoft')]"
```

I don't see any weird VT sequences appearing in the output, so it's not that. Just looks like a character showing up in the output out of order. Strange that it's not consistent, nor is it a consistent char from the output either. 

Still on the backlog, but it's not making Fall Creator's Update.

**Comment by alexeyshishkin01** [comment]
simple test with your 'az' command on my machine:

root@Alexey-HP:/root# az --version | head -1
azure-cli (2.0.10)
root@Alexey-HP:/root# az vm image list-publishers \
 > --location northeurope \
ft> --query "[?starts_with(name, 'Microsoft')]"
Name                                                  Location
----------------------------------------------------  -----------
Microsoft                                             northeurope
Microsoft.Azure.Applications                          northeurope
Microsoft.Azure.Backup.Test                           northeurope
...

you see additional symbols are pasted, next run is different:

root@Alexey-HP:/root# az vm image list-publishers \
> --location northeurope \
i> --query "[?starts_with(name, 'Microsoft')]"
Name                                                  Location
----------------------------------------------------  -----------
Microsoft                                             northeurope
Microsoft.Azure.Applications                          northeurope
Microsoft.Azure.Backup.Test                           northeurope
...

**Comment by benhillis** [comment]
Fixed in 16257.

**Comment by alexeyshishkin01** [comment]
thanks, how to grap the fix?

**Comment by benhillis** [comment]
@alexeyshishkin01 - Installing the most recent Windows Insider Fast build: https://blogs.windows.com/windowsexperience/2017/08/02/announcing-windows-10-insider-preview-build-16257-pc-build-15237-mobile/

**Comment by alexeyshishkin01** [comment]
got it, installed it, windows rebooted, start testing:

root@Alexey-HP:/root# az vm create \
ev> --name imagevm \
> --resource-group centosresourcegroup \
> --image "$imageid" \
> --location northeurope \
> --size Standard_DS1 \
--> --ssh-key-value ~/.ssh/id_rsa.pub \
> --admin-username azureuser \
> --authentication-type ssh \
> --public-ip-address-dns-name imagevm-dnsname \
> --os-disk-name imagevm-osdisk \
> --storage-sku Standard_LRS

**Comment by alexeyshishkin01** [comment]
got some more update of Windows Insider Fast build
restarted Windows
started testing the fix

Microsoft Windows [Version 10.0.16257.1]
(c) 2017 Microsoft Corporation. All rights reserved.

**Comment by alexeyshishkin01** [comment]
no issues so far, still testing

**Comment by alexeyshishkin01** [comment]
hello, all!
no issues since the Windows update.

**Comment by bitcrazed** [comment]
Thanks for testing & confirming. Looks like this is fixed so closing for now.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#92
