### ISSUE TITLE
SystemCTL doesnt work

### ISSUE THREAD

**Issue by Arios509** [Microsoft/WSL#2209]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

![image](https://user-images.githubusercontent.com/14862187/27022849-69c74f7e-4f82-11e7-8690-e775917ac8c9.png)

* What's wrong / what should be happening instead:
I wish to run a self host server with using the bash, but it couldnt use systemctl and enable it so everytime i start the PC and dont need to self type it again.
I wish this could add in it as soon as possible, cause it really helpful.

**Comment by sunjoong** [comment]
@Arios509 - It looks like a regular issue of systemd. In short.... (quote from old comment https://github.com/Microsoft/BashOnWindows/issues/1990#issuecomment-296484839 )
> I think, "/etc/init.d/apache2 restart" or alike might be helpful; traditional service start/stop/restart method.

And... https://github.com/Microsoft/BashOnWindows/issues/1579#issuecomment-271555310
> Starting dbus (sudo service dbus start) will get you a little further but in short no systemd no systemctl

And... #994

**Comment by Arios509** [comment]
@sunjoong But i would rather systemctl add in, it make things easier.

**Comment by sunjoong** [comment]
@Arios509 - I mean... You could vote https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16571479-support-for-running-systemd or join discussion of #994, but you cannot use systemd now and before in current WSL.

**Comment by seadonfrank** [comment]
You may want to try using Upstart to run and manage third-party services
Also, Follow me on [linkedIn](https://www.linkedin.com/in/seadonfrank/) , I am going to publish an article very soon on WSL and running opensource project with WSL. Hopefully, it should give you a comprehensive guide while you start working with WSL

**Comment by therealkenc** [comment]
#1579

**Comment by fenchu** [comment]
service works (/etc/init.d/*), but does autostart after reboot, so you need to manually start everything.

**Comment by JacobDB** [comment]
@fenchu couldn't you write a script that runs at startup to do this?

**Comment by guillaumecauchois** [comment]
A solution for this problem has been found ?

**Comment by gmanroney** [comment]
has a solution for this been found? experiencing problem on ubuntu WSL on Windows 10 
Linux DESKTOP-0JO2PLS 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stevensjared4** [comment]
no solution from what I have seen as of today. using debian subsystem on windows 10 dell pc

**Comment by hshar7** [comment]
Please fix systemd! Really would make Wsl more useful!

**Comment by Oxfos** [comment]
Same problem here when trying to create systemd socket and service files for gunicorn (I'm working on Django projects in WSL):
```
$ sudo systemctl start gunicorn.socket
System has not been booted with systemd as init system (PID 1). Can't operate.
```

**Comment by anandejju** [comment]
this is still problem  , on window 10 Dell , ubuntu subsystem 
systemctl status jenkins
System has not been booted with systemd as init system (PID 1). Can't operate.

**Comment by rayj00** [comment]
I would really like to run LXD on WSL.   Please don't suggest HyperV or vBox.  I am working on an application that uses LXD on my VPS under Ubuntu 16.04 and I can at least run LXD and create containers.  On WSL, I can't do squat as LXD will not start because of that systemd issue!  Please fix!

**Comment by therealkenc** [comment]
> LXD will not start because of that systemd issue

Actually lxd has bigger problems than that. But yes. `systemd` would be a start, assuming the distro in the container required `systemd`.

**Comment by samayo** [comment]
Any news on this?

**Comment by hshar7** [comment]
I think even in wsl2 it won't work..

**Comment by samayo** [comment]
I got it working using this https://github.com/microsoft/WSL/issues/1579#issuecomment-525917575 but nginx and php refused to work together in WSL so at the end, I say stay away from WSL

**Comment by rosalesjahaziel** [comment]
There is a workaround for WSL2 using [genie](https://github.com/arkane-systems/genie)
