### ISSUE TITLE
/sys/devices/system/cpu/cpu0/cpufreq permissions

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/WSL#2214]
Forward of [KittyKatt/screenFetch#467](https://github.com/KittyKatt/screenFetch/issues/467). You'll want this for pretty multi-distro [screencaps](https://blogs.msdn.microsoft.com/commandline/2017/05/11/new-distros-coming-to-bashwsl-via-windows-store/), without cheating by scrolling the error away. This is on 16215.
```
$ ls -l /sys/devices/system/cpu/cpu0/cpufreq
total 0
-r--r--r-- 1 root root 0 Jun 13 10:21 cpuinfo_max_freq
-rw-rw---- 1 root root 0 Jun 13 10:21 scaling_max_freq
```
Perms on `scaling_max_freq` should probably default to 0664 on WSL instantiation. This was previously reported in #1439 but got lost when the issue was conflated with an inability to persist permission changes in `/sys`.

Repro:
```
$ sudo apt-get install screenfetch
$ screenfetch
[[ ! ]] awk: fatal: cannot open file `/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq' for reading (Permission denied)
...
```

**Comment by benhillis** [comment]
Good catch, I'll get this fixed for Fall Creators Update.

**Comment by Oxicode** [comment]
+1

**Comment by benhillis** [comment]
This was fixed in 16273.
