### ISSUE TITLE
invoking bash from jenkins ci job blocks forever

### ISSUE THREAD

**Issue by jv74** [microsoft/WSL#2217]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 Enterprise 1703, Build 15063.322

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I have a working bash environment. I can invoke it when I log in as a regular user.
I already have a Jenkins CI installation. I configured it to run as a service with the same user I use to log in the system.
I created a job including a shell script (batch) calling bash as: 
C:\windows\sysnative\bash -c pwd

* What's wrong / what should be happening instead:
The job blocks trying to call bash, but it never ends and no output is shown. The same happens when redirecting either stdin or stdout to a pipe or file. It runs correctly when invoked interactively (changing sysnative by system32).

![image](https://user-images.githubusercontent.com/29413401/27103991-000e8f20-508b-11e7-81c0-34d9722c03d8.png)

**Comment by SeatherMarqx0** [comment]
Running into the exact same issue. Same Windows 10 Version.

**Comment by SeatherMarqx0** [comment]
This issue seems to be resolved with Windows Insider Build 17025. I wish that the WSL fix can be patched into stable releases though.

**Comment by ben-may** [comment]
Anyone found a workaround for this?  our CI is running win10 10.0.16299.492 so would like to know if there is an alternative to upgrading windows version

**Comment by luzlab** [comment]
I wrote a small wrapper that lets jenkins call WSL using the "shell" step. It works for simple `sh` scripts, but it seems like some plugins (eg. Docker Pipeline) call `sh` directly, bypassing the wrapper, and still don't work.

![Screen Shot 2019-03-21 at 5 18 51 PM](https://user-images.githubusercontent.com/9924835/54792982-a1827000-4bfd-11e9-9d86-2e7bbf2e7358.png)

![Screen Shot 2019-03-21 at 5 18 36 PM](https://user-images.githubusercontent.com/9924835/54792992-ae06c880-4bfd-11e9-93dc-23eafe6fb6d4.png)

You setup the wrapper in Manage Jenkins -> Configure System " by setting the default shell to the wrapper.
![Screen Shot 2019-03-21 at 5 19 51 PM](https://user-images.githubusercontent.com/9924835/54792996-b3641300-4bfd-11e9-9444-c5b49e0ece40.png)

Here's the code for `unixLauncher.cmd`
```cmd
@echo OFF
set options=%1 
set scriptPath=%2
REM echo options = %options%
REM echo script = %scriptPath%
set scriptPathFixed=%scriptPath:\=/%
REM echo fixedPath = %scriptPathFixed%
wsl.exe dos2unix %scriptPathFixed%
bash.exe %options% %scriptPathFixed%
```
You have to run `sudo apt install dos2unix` in WSL for this to work.

**Comment by winthrop-polk** [comment]
I struggled with related issues for quite a while. Best solution I found, Modify Jenkin agent file, jenkins-slave.xml so it used jre x64 (Program Files) rather than x32 (Program Files (x86)). Restart the Jenkins agent service. This is the best way to allow Jenkins to use the bash terminal without worrying about 32/64 bit issues.

**Comment by luzlab** [comment]
If Jenkins can't find C:\Windows\System32\bash.exe, you will find it at C:/Windows/SysNative/bash.exe.

**Comment by therealkenc** [comment]
> This issue seems to be resolved with Windows Insider Build 17025

There is no repro in the OP; take word for fix above [17025](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17025) "More interop stdout/stderr pipe fixes". If issues persist with "job blocks trying to call [wsl.exe]", please submit under a new cover.
