### ISSUE TITLE
General Hanging issues

### ISSUE THREAD

**Issue by stevechilds** [Microsoft/WSL#2224]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.15063

* What you're doing and what's happening:  
Ok, various issues, all have the same symptom. Before I had the creators update bash worked ok - there was an issue with symlinked folders which stopped me using it, but I started again as it was fixed in the creators update. However now its pretty much unusable.

Running redis-cli within bash (talking to the windows based Redis server, as running redis-server in ubuntu would also cause a hang) would cause input to stop working so you couldn't type anything into the window. You also can't close the window or terminate any of the processes as they'd be 'suspended' in Task Manager.
Running telnet to test a memcached server (also running on windows via Couchbase) stopped responding to ^C, so I couldn't quit (although that may have been fixed from other issues I've read on here)
Generally, sooner or later Bash would simply lock up and stop responding, but there was no way to close it without rebooting.

However, the simplest one to demonstrate is sshd. I removed ubuntu and reinstalled it and immediately logged in and installed ssd via apt. It installed fine, heck I even got a login prompt, however after entering my username I then got no more response in the putty window. Trying to stop & start sshd in bash made no difference, it simply wouldn't connect any more.

* What's wrong / what should be happening instead:
They should work, not simply stop responding.

Sorry, I know its a wooly bug report, but the ssh install from scratch is so easy to demonstrate and replicate, anyone should be able to replicate it. 

Its a shame as you fixed some issues that stopped me using it before the Creators update and now it seems more broken than ever - at least on this pc.

**Comment by therealkenc** [comment]
This one died on vine without a repro.

**Comment by stevechilds** [comment]
To be fair, its working now anyway, whatever the issue was, its been fixed at some point.
