### ISSUE TITLE
How can I edit my Windows hosts file without having to re-open Bash as an administrator?

### ISSUE THREAD

**Issue by JacobDB** [microsoft/WSL#2228]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) 15063.413

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots) I'm trying to add a new record in my Windows hosts file from Bash. I can do this if I run Bash elevated, but I don't want to have to run Bash elevated at all times. Is there a way to trigger a UAC prompt when trying to edit a protected file like this? See example command below.

`echo "127.0.0.1    $domain" >> /mnt/c/Windows/System32/drivers/etc/hosts`

* What's wrong / what should be happening instead: Receiving error `/mnt/c/Windows/System32/drivers/etc/hosts: Permission denied`. Should prompt for UAC to gain permissions, then write to file

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
It's not possible right now, but Rich Turner told me a while ago on twitter that he was looking into something like a 'sudo' feature for Windows.  There's no easy way right now to pipe back  the admin prompt through conhost (I have an idea how to write something that might do it in a really ugly and possibly insecure way, by copying how WinPTY and ConEMU work (create a console application that creates an admin console window, sets up a listener, and hides the admin console window, which it polls and syncs exactly like WinPTY and ConEMU. ).  If you call the caller winsudo or something, you would do it like this:

`winsudo admin command`,

which would pop up a UAC prompt, and after you allowed/entered password, would then show the results as they look in the hidden console window

I'm hoping that MS comes up with something better than that ugly hack

**Comment by JacobDB** [comment]
Thanks for the info, I hope they come up with something decent as well!

**Comment by JacobDB** [comment]
Any update on this with the recent release of 1709?

**Comment by mortenscheel** [comment]
In case anyone is still looking for a solution, you can use https://github.com/gerardog/gsudo to run a Windows command with elevated permissions, even from WSL.

So adding an entry to the hosts file can be done like this:
```bash
/mnt/c/path/to/gsudo.exe cmd.exe /c "echo 127.0.0.1 hostname.tld" >> C:\Windows\System32\drivers\etc\hosts"
```

**Comment by vielhuber** [comment]
> In case anyone is still looking for a solution, you can use https://github.com/gerardog/gsudo to run a Windows command with elevated permissions, even from WSL.
> 
> So adding an entry to the hosts file can be done like this:
> 
> ```shell
> /mnt/c/path/to/gsudo.exe cmd.exe /c "echo 127.0.0.1 hostname.tld" >> C:\Windows\System32\drivers\etc\hosts"
> ```

The command that worked for me was slightly different:

```
gsudo -d "echo 127.0.0.1 hostname.tld >> %windir%\System32\drivers\etc\hosts"
```
