### ISSUE TITLE
pipe2(..., O_DIRECT) not supported

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/WSL#2238]
* Your Windows build number:  16215
* What you're doing and what's happening:

```c
int fds[2];
pipe2(fds, O_DIRECT);
perror("pipe2");
```

* What's wrong / what should be happening instead:

Result
```
pipe2: Invalid argument
```

Switching from `O_DIRECT` to 0 allows pipe2 to work.

* Strace of the failing command, if applicable:

### Failing
```
pipe2(0x13c2df0, O_DIRECT)              = -1 EINVAL (Invalid argument)
```

### Successful

```
pipe2([3, 4], 0)                        = 0
```

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, I took a look at the code and confirmed O_DIRECT is not currently supported from pipe2 and EINVAL is the expected error code from the man pages.  Is this blocking a particular scenario or just something that was noticed during testing?

http://man7.org/linux/man-pages/man2/pipe.2.html:
              "Older kernels that do not support this flag will indicate this
              via an EINVAL error."

**Comment by DHowett-MSFT** [comment]
I encountered this during a development scenario. I can work around it, but the guarantees it provides would have been nice.

For what it's worth, that page also indicates that it is supported on 3.4+, and WSL mimes 4.4. I agree that `EINVAL` is the appropriate return value, in any case.

**Comment by therealkenc** [comment]
You can get pretty similar with `socketpair(PF_LOCAL, SOCK_SEQPACKET, pair[])`, which is supported on WSL. You probably already knew that, but I figured it was worth honorable mention.

**Comment by therealkenc** [comment]
Looks like `O_DIRECT` on `pipe2(2)` never made WSL1. Better in WSL2, natch.

![image](https://user-images.githubusercontent.com/7049700/117188347-d1674000-ad91-11eb-9dff-4df35786ed18.png)
