### ISSUE TITLE
Tab completion on arguments not working with some commands...

### ISSUE THREAD

**Issue by adueck** [Microsoft/WSL#2241]
On Windows version number 10.0.15063

When I try to use tab completion when looking to open a file in vim, this happens...

I type `vim file-i-want-to-ope`

Then I press <kbd>Tab</kbd>...

and I get 

```
bash: command substitution: line 900: syntax error near unexpected token `done'
bash: command substitution: line 900: `        done'
```

With other commands this doesn't happen, but it does happen with at least `vim` , `vi`

**Comment by therealkenc** [comment]
https://askubuntu.com/questions/793376/tab-autocomplete-command-substitution-error

**Comment by adueck** [comment]
I checked my bash-completion file as suggested in the file and put in the `_ip_addresses` section exactly as suggested, but the same problem is happening.

**Comment by therealkenc** [comment]
That link isn't a fix to your specific problem. It just a good launch point regarding fixing bash completion script errors. In that link's instance it was a syntax error near token token `}`. You have a syntax error near token `done` at around line 900 that requires attention.

**Comment by sunilmut** [comment]
This doesn't look like a WSL specific issue. Marking it as such.

**Comment by adueck** [comment]
@sunilmut I've used many different real Linux environments and I've never had this issue before. Are you sure this not a WSL specific issue? Is anybody able to reproduce this in a non-WSL environments?

**Comment by therealkenc** [comment]
> Is anybody able to reproduce this in a non-WSL environments?

Sure, [this guy](https://www.questarter.com/q/bash-throws-error-when-tab-for-file-name-auto-complete-when-trying-to-open-vim-3_678160.html) in 2015.

**Comment by tamuhey** [comment]
@adueck I encountered same problem but solved!
I removed the following line in .bashrc
```
alias do="docker.exe" # this line caused the problem
```
I think the alias `do` conflicted the  `done` in bash_complete.

**Comment by sadicLiu** [comment]
> @adueck I encountered same problem but solved!
> I removed the following line in .bashrc
> 
> ```
> alias do="docker.exe" # this line caused the problem
> ```
> I think the alias `do` conflicted the `done` in bash_complete.

This is the right answer
