### ISSUE TITLE
npm: SHA checksum fails

### ISSUE THREAD

**Issue by nighto** [microsoft/WSL#2247]
* Your Windows build number: `10.0.14393`

* What you're doing and what's happening: After cloning [my project repository](https://github.com/MinisterioPublicoRJ/inLoco-2.0), running `npm install` fails. Here's the npm debug log: https://pastebin.com/xtHDj4ME

* What's wrong / what should be happening instead: `npm install` runs fine on Windows 7 (git bash) and MacOS.

Seems to be related with #348, but couldn't reopen that issue and I'm running a newer version then 14352.

**Comment by fpqc** [comment]
Could you instead update the Creators' update (1703, build 15063).  14393 is already over a year old.

**Comment by nighto** [comment]
Hi, just updated to Creators' update (1703, build 15063), did a `npm cache clean --force` and run `npm install` again. It outputs the exact same error.

**Comment by fpqc** [comment]
Thanks, this makes the report more useful.
