### ISSUE TITLE
When I execute "./servo"

### ISSUE THREAD

**Issue by Verld** [Microsoft/WSL#2254]
Xlib: Extension "XFree86-VidModeExtension" missing on display ":0.0".
Failed to create window.: OsError("GL context creation failed") (thread main, at /checkout/src/libcore/result.rs:860)
I installed the Rust programming language with apparent success.
I am using Ubuntu Unity in VCXSrv on Windows 10 on a Dell Inspiron 1545.
Yes I have been told that that Dell product is not tested for Windows 10 upgrade.

**Comment by sunjoong** [comment]
@Verld - I guess it might be related to https://github.com/servo/servo/issues/13018, or... might be the OpenGL support of VcXsrv. Hmm.... If it be a VcXsrv problem, you could test it with Cygwin/X, but if it be a servo problem... I'm afraid there might be no workaround just now.

**Comment by SRGOM** [comment]
@aseering  can you link me to your forum again, please? Maybe we should this github repo in there...

**Comment by aseering** [comment]
Hey @SRGOM -- sure:  https://wsl-forum.qztc.io/

**Comment by therealkenc** [comment]
This appears to be a problem that would manifest on Real Linux connecting to VcXsrv. Per the linked [Servo#13018](https://github.com/servo/servo/issues/13018#issuecomment-242119838):

> I think we should fix bugs in our use of libGL if possible, but we should probably not go out of our way to make networked display work. 

Closing for now as linux-behavior.
