### ISSUE TITLE
After install OpenSuse, bash on Ubuntu pin on taskbar no longer points to Ubuntu but OpenSuse

### ISSUE THREAD

**Issue by JimSEOW** [microsoft/WSL#2256]

**Comment by sunjoong** [comment]
@JimSEOW - I heard wslconfig has these options;
```
wslconfig /?
Performs administrative operations on Windows Subsystem for Linux

Usage:
    /l, /list [/all] - Lists registered distributions.
        /all - Optionally list all distributions, including distributions that
               are currently being installed or uninstalled.
    /s, /setdefault <DistributionName> - Sets the specified distribution as the default.
    /r, /register <Appx> - Registers a new distribution.
    /u, /unregister <DistributionName> - Unregisters a distribution.
```
Hmm... what if `wslconfig /l` and does that have any chance of being related to setdefault option of wslconfig?

**Comment by shevegen** [comment]
I did not know about wslconfig, thanks for the info.

**Comment by zadjii-msft** [comment]
@benhillis for more investigation. I believe this should still open your default distro, and I don't think installing OpenSuse should have changed that from the legacy instance, but I could be wrong.

**Comment by benhillis** [comment]
Not a lot of detail in the bug description, but @zadjii-msft is correct.
