### ISSUE TITLE
Exiting n with Ctrl+C messes up terminal

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/WSL#2257]
![Image](http://g.recordit.co/9NYVoMRDEO.gif)

I'm on 15036.

1. Make sure node is installed
2. Install [`n`](https://github.com/tj/n): `sudo npm i -g n`
3. Install some node version in `n`: `sudo n latest`
4. Enter `n`
5. Quit by pressing Ctrl+C (note that the bug does not occur when pressing Enter)
6. Try using the terminal. You will see that what you are typing is no longer echoed, and pressing Enter does not move to the next line. This behavior is almost the same as I observed in the case of the failing `script` command in https://github.com/Microsoft/BashOnWindows/issues/2053#issuecomment-311015109 with the difference that here, Ctrl+C in the shell _does_ reset the column.

This issue does not occur on real linux. Note that on real linux, the line `Terminated` is printed in the terminal after the Ctrl+C press, which does not happen here.

Strace of `n` attached.
[n_strace.txt](https://github.com/Microsoft/BashOnWindows/files/1101810/n_strace.txt)

EDIT: Something very strange: I tried to get an strace on real linux as well, for comparison, and I noticed that when using `strace n 2> trace.txt` on linux, *the same problem occurs* as it does in WSL! The difference is that in WSL it always happens, while in real linux it happens only under `strace` for some reason, and that in WSL it clear the version list after pressing Ctrl+C and restores the shell screen buffer but then bugs around, while in real linux under `strace` it just adds a shell prompt below the version list.

Linux strace attached for completeness (the filename contains "ubuntu" but that was my mistake, the linux I tested it on was actually Debian Wheezy).
[n_strace_ubuntu.txt](https://github.com/Microsoft/BashOnWindows/files/1101827/n_strace_ubuntu.txt)

**Comment by benhillis** [comment]
It looks like n is not restoring your terminal state when killed via ctrl-c.  You can reset your terminal by running "reset".
