### ISSUE TITLE
How can I integrate bash into VSCode?

### ISSUE THREAD

**Issue by thelastfantasy** [Microsoft/WSL#2262]
I found [this](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows) guide, but after I installed the Linux Subsystem I cannot find neither of the `bash.exe` or `sysnative` directory in my system drive, what should I do next?

**Comment by sunjoong** [comment]
@thelastfantasy - You said you had installed WSL, so how to launch that? If you using a shortcut named "Bash on Ubuntu on Wondows" on start menu, you could check that's property. I think... you might see that's target property is `C:\Windows\System32\bash.exe ~`. If then, you could find bash.exe on C:\Windows\System32 directory.

**Comment by thelastfantasy** [comment]
![image](https://user-images.githubusercontent.com/6077584/27590035-ebbf91c2-5b7f-11e7-8295-e95169771c57.png)
![2017-06-27_19](https://user-images.githubusercontent.com/6077584/27590197-7db48e0c-5b80-11e7-9ec8-a84b49146dfe.png)
I find it in the explorer, but my Everything program cannot find it, and when I set it in VSCode, it seems not to work.

**Comment by thelastfantasy** [comment]
Oh, I just set the the value to `"C:\\Windows\\sysnative\\bash.exe"` and it works. It seems the `sysnative` directory is like a symbol link only for 32bit applications so it can be accessed by VSCode but cannot be visited in explorer.

**Comment by CherryDT** [comment]
@thelastfantasy Exactly.

|Application bitness|Path to 32-bit system folder|Path to 64-bit system folder|
|-|-|-|
|32-bit|`C:\Windows\System32`|`C:\Windows\Sysnative`|
|64-bit|`C:\Windows\SysWOW64`|`C:\Windows\System32`|
