### ISSUE TITLE
strange cursor when using tmux

### ISSUE THREAD

**Issue by candywater** [microsoft/WSL#2266]
* **Windows build number**: Microsoft Windows [Version 10.0.15063]
* **What you're doing and what's happening**：
	+ environment:
		- tmux(2.x), zsh
		- add this to .zshrc " export TERM='screen-256color' "
		- vim with a colorscheme (e.g.:vim-deus)
		- add this to .bashrc "if [ -t 1 ]; then exec zsh fi"
		- terminal  character encoding: 65001(UTF-8)
	+ environment example:
		-  [.zshrc file](https://gist.github.com/candywater/158b57212d6f8a055fbaa69f5d75af0e)
		-  [.vimrc file](https://gist.github.com/candywater/5948198abfa5621f7aa141cd1bfc62b0)
		- [.bashrc file](https://gist.github.com/candywater/98b98e5ed0ab3e9a8abf0acfb073fa6c)
	+ what you need to do:
		- start bash on ubuntu on windows
		- command: tmux -2
		- use ls or vi, and tab to auto-complete, see cursor
		- open vim, see cursor
	+ what is happending:
		- situation1: use auto-complete
![line_p2017628_161432](https://user-images.githubusercontent.com/12393438/27641751-c08aa55e-5c57-11e7-8aa7-e388b2b4ef9d.jpg)
cursor became a "・" instead of "_" or "■"

		- situation2: when using vim
![line_p2017628_161429](https://user-images.githubusercontent.com/12393438/27641824-f79f399c-5c57-11e7-8b4d-ae71153f08a3.jpg)
and then change the font
![1498658102093](https://user-images.githubusercontent.com/12393438/27641819-f35152b2-5c57-11e7-962a-4d306566dddf.jpg)
change another font
![1498658069380](https://user-images.githubusercontent.com/12393438/27641803-eba3851c-5c57-11e7-9c6e-69576201c1d7.jpg)
cursor became a strange char, and transform the other char where the cursor stayed into that char

* **What's wrong / what should be happening instead**:
    + situation1:use auto-complete (without tmux)
![line_p2017628_161434](https://user-images.githubusercontent.com/12393438/27641754-c3d21012-5c57-11e7-888d-d6348c241e66.jpg)

    + situation2:when using vim (without tmux)
![1498634388891](https://user-images.githubusercontent.com/12393438/27641913-3a32fc94-5c58-11e7-9385-b3331d6265e9.jpg)

---
* **what I did**

	+ I add a issue at [tmux's github] (https://github.com/tmux/tmux/issues/986)

	and I got that the log seems correct, it seems something wrong with terminal or tmux.

**Comment by sunjoong** [comment]
@candywater - It looks like... Hmm... I think your TERM environment variable might be related to that. I did very simple test to set TERM variable befor running tmux and saw the strange ring like sun. Even though that was not a repo of yours, I suspect that might be related to.
![term](https://user-images.githubusercontent.com/2748000/27648007-243079e8-5c68-11e7-922d-781e9831fb6a.png)

**Comment by candywater** [comment]
@sunjoong  thanks for your comment
but my terminal has the different response.

- without tmux
  
![1498670660645](https://user-images.githubusercontent.com/12393438/27651750-543400cc-5c74-11e7-9543-25c1f321a1db.jpg)
![1498670698009](https://user-images.githubusercontent.com/12393438/27651752-569d355e-5c74-11e7-92de-fb4a0ef916de.jpg)
![1498670758207](https://user-images.githubusercontent.com/12393438/27651755-59dd2526-5c74-11e7-9455-8847cdf888a0.jpg)
![1498670749859](https://user-images.githubusercontent.com/12393438/27651759-5c3966d6-5c74-11e7-85f5-9bd0eef9f571.jpg)
![1498670770807](https://user-images.githubusercontent.com/12393438/27651764-5f77dca6-5c74-11e7-9eb2-d9a1423326a8.jpg)

- with tmux
whatever you set $TERM is,
tmux returns me this 
![1498670838573](https://user-images.githubusercontent.com/12393438/27651788-6dabbd60-5c74-11e7-8f66-7adbf6b2a0b7.jpg)

something with that "・"

**Comment by sunjoong** [comment]
@candywater - abcdf is not a terminfo item, but screen, screen-256color, xterm and xterm-256color are terminfo items. I have a curiosity what if you comment out "export TERM=screen-256color" in your .zshrc file.

**Comment by candywater** [comment]
@sunjoong 
if I comment out "export TERM=screen-256color", everything will turn out to be fine.
but the darkblue will be invisible (though I can fix it),
and the most important problem is it is hard to set the font color of vim.
( vim-deus and many vim color packages don't work well)
I want to use vim-deus so that I add "export TERM=screen-256color" to .zshrc file.

**Comment by sunjoong** [comment]
@candywater - So, you're using screen-256color because xterm-256color did not support your color scheme, but found screen-256color have a compatible issue of cursor on WSL and terminfo.

**Comment by candywater** [comment]
@sunjoong  
actually, using xterm-256color will cause the same issue -- works well with terminal , but has a issue of cursor via tmux. 
I'm sorry I don't know what WSL is ....

**Comment by sunjoong** [comment]
@candywater - Good. That's why people use wsl-terminal :). But the issue itself still looks like to remain on conhost of WSL.
