### ISSUE TITLE
Java JVM dynamic attach attach_pids created under /mnt/c/ cause malfunctions

### ISSUE THREAD

**Issue by nevhan** [microsoft/WSL#2270]
* Your Windows build number:
Microsoft Windows [Version 10.0.16232.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am attempting to build & test a Java project using Maven which uses JUnit and JMockIt.
Under ~/ in the linux filesystem this works completely fine.

* What's wrong / what should be happening instead:
Under /mnt/c/ ntfs filesystem the unit tests fail due to exception: 

> com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded

I have traced the problem to the following...
OpenJDK source code: hotspot/src/os/linux/vm/attachListener_linux.cpp ~ 505:
```c
// If the file .attach_pid<pid> exists in the working directory
// or /tmp then this is the trigger to start the attach mechanism
bool AttachListener::is_init_trigger() {
  if (init_at_startup() || is_initialized()) {
    return false;               // initialized at startup or already initialized
  }
  char fn[PATH_MAX+1];
  sprintf(fn, ".attach_pid%d", os::current_process_id());
  int ret;
  struct stat64 st;
  RESTARTABLE(::stat64(fn, &st), ret);
  if (ret == -1) {
    snprintf(fn, sizeof(fn), "%s/.attach_pid%d",
             os::get_temp_directory(), os::current_process_id());
    RESTARTABLE(::stat64(fn, &st), ret);
  }
  if (ret == 0) {
    // simple check to avoid starting the attach mechanism when
    // a bogus user creates the file
    if (st.st_uid == geteuid()) {
      init();
      return true;
    }
  }
  return false;
}
```

Specifically, the **::stat64** call returns successfully however the result field **st_uid** does not match **geteuid()**, I guess the fstat call translation is causing issues as it comes back with uid 0 ?

* From strace of the above code snippet:
```c
stat(".attach_pid4562", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
geteuid()                               = 1000
```

* From strace of the thread that creates the attach_pid:
```
open("/proc/4562/cwd/.attach_pid4562", O_RDWR|O_CREAT|O_EXCL, 0666) = 23
fstat(23, {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
close(23)                               = 0
```

* Stat of offending attach_pid:
```
stat .attach_pid2939
  File: '.attach_pid2939'
  Size: 0               Blocks: 0          IO Block: 512    regular empty file
Device: 11h/17d Inode: 13792273859170191  Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-06-30 10:13:39.144976600 +1000
Modify: 2017-06-30 10:13:39.144976600 +1000
Change: 2017-06-30 10:13:39.144976600 +1000
 Birth: -
```

**Comment by nevhan** [comment]
1. Running as root circumvents the issue (as the UID happens to match up)
2. The JVM will create the attach pid in /tmp if it cannot be created in the current directory if there is a way to block these files from the windows side

**Comment by therealkenc** [comment]
This submission went chirping crickets on lack or repro steps to manifest the error. Given the description the incorrect `stat64` UID will be addressed by [enabling metadata](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options) on `/mnt/c`, which became circa 17063.
