### ISSUE TITLE
Hang using TTY to program MCU (ESP8266)

### ISSUE THREAD

**Issue by Petezah** [microsoft/WSL#2273]
* Your Windows build number:  16226.1000

* What you're doing and what's happening:  
I am trying to use esptool.py (from esp_open_sdk: https://github.com/pfalcon/esp-open-sdk) to flash an ESP8266 module.  I am able to see output from the module over UART, but the esptool hangs while trying to flash the module.  For a repro, build any of the examples from https://github.com/SuperHouse/esp-open-rtos and flash with: (from within the example directory)
```
make flash -j4 ESPPORT=/dev/ttyS3
```
In this case, I am using a Prolific USB to serial adapter which shows up on COM3.

* What's wrong / what should be happening instead:
It should successfully write the flash of the ESP8266 module.  Instead, it hangs.

* Strace of the failing command, if applicable:  
[strace.zip](https://github.com/Microsoft/BashOnWindows/files/1116469/strace.zip)

**Comment by dhalbert** [comment]
May be related to issues raised in #1929. Awaiting support for `ioctl` functionality for COM ports.

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
