### ISSUE TITLE
Cyrilic font issue in ohmyzsh

### ISSUE THREAD

**Issue by casufi** [Microsoft/WSL#2275]
I set Zsh as my default shell for bash for Windows after that I installed "oh my zsh" as default theme for Zsh https://github.com/robbyrussell/oh-my-zsh
I am using default theme "rubyshell" for command prompt  but I have some issue with the unicode characters and me unable to set "Ubuntu" as default font for the bash for windows

![bash](https://user-images.githubusercontent.com/9831298/27762745-7b16015a-5e80-11e7-9bd8-e34e875c8720.png)

https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme

**Comment by fpqc** [comment]
You can't use opentype fonts in conhost right now.

**Comment by SummerSad** [comment]
You can change the default font in CMD with fonts here https://github.com/powerline/fonts

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#90
