### ISSUE TITLE
Performing rm-rf on OneDrive files from WSL causes sync loss forcing to reconfigure OneDrive

### ISSUE THREAD

**Issue by Jubijub** [microsoft/WSL#2276]
* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  
** I work on a git project stored on my OneDrive folder (c:\Users\Jubijub\OneDrive\Projects\blog)
** I tried to remove a folder by doing rm -rf <that folder> (I use WSL with ZSH)

* What's wrong / what should be happening instead:
** the folder didn't remove properly (ls -la shows the file as d????????? )
** I get a windows popup saying OneDrive cannot locate the folder, with two options : reconfigure OneDrive, or simply quit
** at this point OneDrive is off on my computer, I have to launch the configuration wizard again

Expected behavior : the file is deleted, and appear as such on WSL / windows, OneDrive remains configured and doesn't lose sync.
This happened 3 times today, every time I used rm on a file stored on OneDrive

Note : I use WSL since anniversary update, always with Zsh as my main shell. It's the first time I use it again since Creator update, and I am pretty sure this didn't happen before. This is thus either a regression from WSL, or from OneDrive.

Edit : same happens with rename

**Comment by benhillis** [comment]
If possible could you try this on a recent Windows Insider build (16237 or later)?  @SvenGroot has greatly improved the experience of symlinks / reparse points in DrvFs recently.

**Comment by therealkenc** [comment]
This problem was not reproduced locally. If the problem persists on 19043 please open a new ticket.
