### ISSUE TITLE
arp command not working at all - /proc/net/arp: No such file or directory

### ISSUE THREAD

**Issue by takenek** [microsoft/WSL#2279]
root@SERWER:~# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=1.90 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=1.93 ms
--- 192.168.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 1.900/1.915/1.931/0.046 ms

root@SERWER:~# arp -a
/proc/net/arp: No such file or directory

root@SERWER:~# arp
/proc/net/arp: No such file or directory

arp command not working at all.

**Comment by apadin1** [comment]
Same problem. Using whereis arp shows this:

`/usr/sbin/arp /usr/share/man/man7/arp.7.gz /usr/share/man/man8/arp.8.gz`

But running `/usr/sbin/arp` again just prints:

`/proc/net/arp: No such file or directory`

**Comment by hamaney** [comment]
I am having the same issue when I run arp command on "Bash on Ubuntu on Windows"

**Comment by DarthSpock** [comment]
First, you didn't fill out the template so we don't know what version you are running for starters, there's also no strace. Do a `sudo mkdir /proc/net/arp` and then see if ARP works then. If it doesn't, probably [69](https://github.com/Microsoft/WSL/issues/69). Also check out [2621](https://github.com/Microsoft/WSL/issues/2621). If it does work, then is probably part of [2530](https://github.com/Microsoft/WSL/issues/2530). @therealkenc or @sunilmut should probably steer you better though.

**Comment by therealkenc** [comment]
This issue is about as good a landing zone for `/proc/net/arp` as any. #69 is closed. [`ARP/wARP`](https://www.embl-hamburg.de/ARP/Manual/UserGuide7.6.html#x1-30001.1) is a protein modeling system not [`arp(8)`](http://man7.org/linux/man-pages/man8/arp.8.html). `strace` would be superfluous on this one because `/proc/net/arp` isn't a thing on WSL (in any version) right now. [It is of course a good idea to follow the issue template in any case because you get better service that way.]

**Comment by SergeiZiuz** [comment]
I've some issue 
`arp 10.23.171.25
/proc/net/arp: No such file or directory`

**Comment by therealkenc** [comment]
> /proc/net/arp: No such file or directory

^--- Probably "try WSL2" in this case. Announcement [here](https://devblogs.microsoft.com/commandline/announcing-wsl-2/). Information on how to get on Windows 10 Insiders [here](https://insider.windows.com/en-us/). Waiting for Spring 2020 is a reasonable too, for the patient.

**Comment by feland207** [comment]
No workaround for this issue? 
I'm running WLS this version

uname -a
Linux N-20L6PF1PZ148 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

fandre@N-20L6PF1PZ148:/mnt/c/Users/$ arp
/proc/net/arp: No such file or directory

Have this issue

sudo mkdir /proc/net/arp
mkdir: cannot create directory ‘/proc/net/arp’: Operation not permitted

If creating the folder was the solution... but does anybody fixed arp issue? 

Any comment is welcome.

**Comment by IyadKhuder** [comment]
> No workaround for this issue?
> I'm running WLS this version
> 
> uname -a
> Linux N-20L6PF1PZ148 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
> 
> fandre@N-20L6PF1PZ148:/mnt/c/Users/$ arp
> /proc/net/arp: No such file or directory
> 
> Have this issue
> 
> sudo mkdir /proc/net/arp
> mkdir: cannot create directory ‘/proc/net/arp’: Operation not permitted
> 
> If creating the folder was the solution... but does anybody fixed arp issue?
> 
> Any comment is welcome.

I have exactly the same situation and have tried sudo mkdir /proc/net/arp to no avail!

**Comment by AdrienEdoukou** [comment]
Same, arp command still doesn't work, mkdir didn't change anything

**Comment by vonmoraes** [comment]
try using arp.exe -a on WSL.

**Comment by risinek** [comment]
> try using arp.exe -a on WSL.

this is simple but working solution! thanks.

**Comment by robbhaker** [comment]
> try using arp.exe -a on WSL.

thanks for the solution.

**Comment by caowenbo2000** [comment]
> try using arp.exe -a on WSL.

thinks

**Comment by bvandenbon** [comment]
running `arp.exe` from wsl is a weird thing to do.
You're cheating yourself.

The result is the same as running `arp.exe` directly from your windows terminal.
WSL has nothing to do with this at all.

By contrast if you want to run the linux version of the arp command, then you're still stuck.

**Comment by BurgessX** [comment]
I have the same issue, and maybe it's worth noticing that command `arp --help` works.

**Comment by bvandenbon** [comment]
Indeed, and a `whereis arp` lists `arp: /usr/sbin/arp` as its first result.

**Comment by JaK0B-Pro** [comment]
> try using arp.exe -a on WSL.



> try using arp.exe -a on WSL.

Thaks it's working 💯

**Comment by rakgup** [comment]
> try using arp.exe -a on WSL.

Works on Bash on Ubuntu on Windows too. thanks

**Comment by becomesaflame** [comment]
Why is this closed? The issue is not resolved. Running `arp.exe` from WSL is not the same as fixing the WSL arp installation.

**Comment by jsotopian-chwy** [comment]
Did anyone find a solution for this? I am having the same issue.

**Comment by Switch-H** [comment]
alias arp="arp.exe"

**Comment by eggbean** [comment]
> running `arp.exe` from wsl is a weird thing to do. You're cheating yourself.
> 
> The result is the same as running `arp.exe` directly from your windows terminal. WSL has nothing to do with this at all.
> 
> By contrast if you want to run the linux version of the arp command, then you're still stuck.

@bvandenbon `arp` can only get MAC addresses within the same Layer 2 network. WSL2 works within its own subnet, so `arp` on WSL can only work within that subnet. You need to use the Windows `arp.exe` only because the host Windows network is on the same network as the device you are trying to get the MAC address from.
