### ISSUE TITLE
md5sum fails with listed files could not be read (works on Ubuntu)

### ISSUE THREAD

**Issue by mloskot** [microsoft/WSL#2283]
TL;TR: While investigating an issue in https://github.com/Project-OSRM/osrm-backend/issues/4229, I realised `md5sum -c sums.txt` is not able to find, open and read files listed in `sums.txt`, despite the files are in current folder. The problem seems specific to BashOnWindows.

------

* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:

```
$ cd /mnt/d/dev/osrm-backend/test/data
$ ls monaco.osm.pbf monaco.poly data.md5sum
data.md5sum  monaco.osm.pbf  monaco.poly
$ md5sum -c data.md5sum
: No such file or directory
: FAILED open or read
: No such file or directory
: FAILED open or read
md5sum: WARNING: 2 listed files could not be read
```

On plain Ubuntu 16.04, everything works as expected:

```
$ cd ~/dev/osrm-backend/test/data
$ ls monaco.osm.pbf monaco.poly data.md5sum
data.md5sum  monaco.osm.pbf  monaco.poly
$ md5sum -c data.md5sum 
monaco.osm.pbf: OK
monaco.poly: OK
```

* What's wrong / what should be happening instead:

`md5sum` on BashOnWindows does not find the files, but it should as it does on plain Linux.

**Comment by sunjoong** [comment]
@mloskot - Hmm... what's the contents of data.md5sum file? Does it look like this?
```
sunjoong@SUNJOONG-DESKTOP ~/temp $ cat data.md5sum
2b8dd9343d5e615afc9c67bcc7028a63  monaco.osm.pbf
b0788991ab3791d53c1c20b6281f81ad  monaco.poly
sunjoong@SUNJOONG-DESKTOP ~/temp $
```
And... what if test under your home directory like ~/dev/osrm-backend/test/data directory, not /mnt/d/dev/osrm-backend/test/data directory. Is that different?

**Comment by mloskot** [comment]
@sunjoong Here is the file https://github.com/Project-OSRM/osrm-backend/blob/master/test/data/data.md5sum

I think you've diagnosed my problem:
```
mloskot@DEV604:~/dev/osrm-backend/test/data$ cat data.md5sum
2b8dd9343d5e615afc9c67bcc7028a63  monaco.osm.pbf
b0788991ab3791d53c1c20b6281f81ad  monaco.poly
mloskot@DEV604:~/dev/osrm-backend/test/data$ md5sum -c data.md5sum
monaco.osm.pbf: OK
monaco.poly: OK
mloskot@DEV604:~/dev/osrm-backend/test/data$
```

Is that expected?

**Comment by sunjoong** [comment]
@mloskot - If it works under your home directory but not under /mnt directory, that might be a issue of DrvFS. I had seen many issues related DrvFS on here :). You know, DrvFS (i.e., under /mnt directory) is for windows filesystem, so we could expect thare are not compatible stuffs yet. If that happens, it's the easist way to compair that with VolFS (for example, under home directory) and then with real linux box. I guessed some procedure didn't make a working data.md5sum on DrvFS becaue of its limitation but could do on VolFS :).

**Comment by mloskot** [comment]
@sunjoong Thanks for pointing out the DrvFS issues. 

I confirm your variant works.

I will leave decision about closing this issue to the project maintainers.

**Comment by sunilmut** [comment]
@mloskot - Thanks for your post and thanks @sunjoong for diagnosing the issue. Adding @SvenGroot, as another divergence of behavior between DrvFS and LxFS.

**Comment by mloskot** [comment]
@sunilmut, @SvenGroot Thanks. Any news?

**Comment by sunilmut** [comment]
@mloskot - As you can see in the release notes of [17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063), with metadata support now in DrvFS, the differences between DrvFS (ex: /mnt) and LxFS (ex: ~) are diminishing. We expect issues like this one to go away eventually. If you are able to try to the above repro on 17063, that would be great.

**Comment by therealkenc** [comment]
Metadata _probably_ isn't going to squash "No such file or directory". It isn't there, or, it is there, and WSL thinks it isn't. This went stale because no repro steps, which might look like "unzip this, run md5sum". That and/or an `strace`.

**Comment by therealkenc** [comment]
This submission did not have a repro. If the problem persists on 19043, please open a new ticket with the details.
