### ISSUE TITLE
Cannot paste non-ascii data to command line

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2286]
* Your Windows build number:  10.0.0.15063

* What you're doing and what's happening:
I'm attempting to paste non-ascii data from the clipboard to the WSL shell (bash). Copying regular text under Windows (e.g. ctrl-c from some plain-text application) and pasting it into a WSL bash session (shift+right-click) works fine.

However, attempting this with non-ascii/unicode characters fails (nothing is pasted). You can try it by trying to copy-and-paste this symbol to a bash prompt: →

Pasting the same data to a regular cmd/powershell instance (non-WSL) works fine.

* What's wrong / what should be happening instead:

Non-ascii data is not pasted to the WSL shell. Nothing happens.

**Comment by sunjoong** [comment]
@mqudsi - I copied → character to clipboard by ctrl+c and checked it copied using "Get-Clipboard" command on PowerShell, and then pasted it on bash console by mouse right click;
![paste](https://user-images.githubusercontent.com/2748000/27844510-b4bfecb0-615d-11e7-8f77-5210f20397a9.png)
I myself could not reproduce yours, but it could be affected by others. What's your language environment? If you don't understand that, what's the result of "chcp" command on cmd.exe? What font do you use? You could check it by mouse right click on title bar of bash console and select properies. And... How to launch bash? "Bash on Ubuntu on Windows" in start menu? Or "bash" command on cmd.exe? I think... these informations are maybe needed for whom to try to figure it out.

**Comment by mqudsi** [comment]
I have no problem getting the copied character via the `Get-Clipboard` cmdlet. Bash is run by executing `bash.exe` from within either cmd.exe or powershell.exe (makes no difference).

I didn't change the keyboard layout at any point, it is always "ENG - DV" (Dvorak).

**Comment by JoshNoel** [comment]
+1,
I am using DejaVu Sans Mono on Windows Build: 14393.1358
I can use any unicode symbol supported by the font in cmd.exe even with code page 437, but I cannot get any "non-standard" characters to appear in bash.exe.

**Comment by zadjii-msft** [comment]
I'm fairly certain we fixed something like that recently. I'll bring it up with the rest of the team and make sure this is the same issue

**Comment by sunilmut** [comment]
@zadjii-msft - Thanks. Additionally, you can follow the repro steps with (and without) you fix and see if the issue is resolved.

**Comment by alistair23** [comment]
Are there any updates on this?

**Comment by zadjii-msft** [comment]
It's been so long that there's very little chance of me being able to find the original bug now... That being said, it looks like it's resolved to me:
![image](https://user-images.githubusercontent.com/18356694/32740816-024c7324-c859-11e7-83e2-90af82ed774b.png)

If @mqudsi is still having issues with this, then it might be a weird codepage issue? We'd have to follow up and get more details.

**Comment by mqudsi** [comment]
Thanks for the heads-up, it seems to indeed be working under 16299+

(glad to see a `$` user in the wild, btw! 😸 )

**Comment by shogerr** [comment]
Issue still persists.
