### ISSUE TITLE
assignment of the result of a subprocess to a variable hangs

### ISSUE THREAD

**Issue by areman** [Microsoft/WSL#2294]
```
> ver
Microsoft Windows [Version 10.0.15063]
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

I installed the oracle instant client
```
sudo apt-get install -y alien
alien -i oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm 
alien -i oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
```
  
sqlplus itself works fine. I can connet to databases without any problem.

But when I try to assign the result of a sqlplus command to a variable the bash hangs.

```
value=$( sqlplus -s user/password@DB <<SQL
select 1 from dual;
exit;
SQL
)
```
The sqlplus call itself finished successful and the subshell finished. But something hangs and the calling bash doesn't get the "focus" back.

Without a variable assignment it works.
```
( sqlplus -s user/password@DB <<SQL
select 1 from dual;
exit;
SQL
)
```

It seems the problem has something to do with the output streams. Add a simple pipe and it works.

```
echo $( sqlplus -s user/password@DB <<SQL 2>&1 | cat
select 1 from dual;
SQL
)
```

**Comment by ethanherbertson** [comment]
I see something very similar happening in Perl.

Doing something like

    my $output = `sqlplus -S /nolog \@define.sql`;

causes a "hang", where the statement never finishes executing. However, doing something like

    exec `sqlplus -S /nolog \@define.sql`;

behaves correctly.

If I do a "streaming" version of the same thing, I can confirm that the sqlplus command itself does in fact complete:

    open my $cmd_fh, '-|', 'sqlplus -S /nolog @define.sql 2>&1 && echo \'done\'';
    print "Line: $_" while (<$cmd_fh>);
    close $cmd_fh;

prints:

    → perl thing.pl
    Line: DEFINE _SQLPLUS_RELEASE = "1202000100" (CHAR)
    Line: done

And then hangs.

**Comment by therealkenc** [comment]
Not sure how this one got lost in the noise and wasn't marked need-repro from the get-go. If you are experiencing the problem in 1809 (aka 17763 aka RS5 aka October 2018 update) you can try rebooting the issue following CONTRIBUTING.md with particular attention to pasteable CLI repro steps from clean install and an strace log.

**Comment by ethanherbertson** [comment]
> Not sure how this one got lost in the noise and wasn't marked need-repro from the get-go. If you are experiencing the problem in 1809 (aka 17763 aka RS5 aka October 2018 update) you can try rebooting the issue following CONTRIBUTING.md with particular attention to pasteable CLI repro steps from clean install and an strace log.

I can't get away with clean-slating my current setup, but I"ll see what I can do.
