### ISSUE TITLE
openssl typed password is visible

### ISSUE THREAD

**Issue by kuklis** [Microsoft/WSL#2298]
* Your Windows build number: 10.0.14393

* What you're doing and what's happening:  
Encrypting file with openssl:
$ openssl aes-256-cbc -in myfile.txt -out myfile.txt.enc
enter aes-256-cbc encryption password:aa
Verifying - enter aes-256-cbc encryption password:aa

* What's wrong / what should be happening instead:
My typed password "aa" is printed on the screen, it should not be visible

**Comment by sunjoong** [comment]
> My typed password "aa" is printed on the screen, it should not be visible

@kuklis - In my case, password was not visible. Hmm... Is there other program influence on your screen?

**Comment by kuklis** [comment]
@sunjoong How can I check?

**Comment by sunjoong** [comment]
@kuklis - Well... I mean...
![password](https://user-images.githubusercontent.com/2748000/27977071-245fb29c-63a4-11e7-97f1-97f418b9e2ba.png)
There was not visible password string. Even though using screen wrapper programs like screen or tmux, those programs have a stuff to prevent visible password string, I think. So... I have no idea about that;  sorry.

**Comment by kuklis** [comment]
OK @sunjoong - I do not use screen or tmux, my WSL is pretty much the std - I wonder why this is happening. Maybe someone else has an idea...
This is not the latest image having a corporate Windows install. Maybe it is fixed in the new release of yours?
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Comment by sunjoong** [comment]
@kuklis - Oh, you edited your previous comment, I missed it. BAC, I'm using on windows build number 15063, ubuntu 16.04 or gentoo.

**Comment by sunilmut** [comment]
@kuklis - Thanks for your post. Windows build 14393 (a.k.a Anniversary Update) is pretty old as far as WSL is considered. Significant changes have gone in WSL since. If you can move to 15063 (a.k.a Creators Update) or newer and try your scenario again, that would be better.

**Comment by kuklis** [comment]
I'm not in a position to upgrade my OS (having a corporate install) - I'm happy to get Anniversary Update at all to use WSL...
I'm interested if anyone on build 14393 is experiencing the same issue or it's only on my local issue.

**Comment by therealkenc** [comment]
It is unclear on this one whether there was a console issue with 14393 (which was subsequently addressed), or whether the problem was something else entirely. Since 14292 WSL was still in beta and no one above actually reproduced the problem, it is pretty much water under the bridge at this point. If the problem persists, it would certainly be worth a new post.

**Comment by sethniels** [comment]
I am having this exact same issue; when I try to encrypt a file using openssl, it echoes the password as I type it. In fact, it occurs when decrypting as well. I even upgraded openssl using apt-get, but that made no difference. I'm on OS Build 17134.885.

``` bash
~/temp$ openssl aes-256-cbc -in blah.txt -out blah.txt.enc
enter aes-256-cbc encryption password:abc

Verifying - enter aes-256-cbc encryption password:abc

~/temp$ openssl aes-256-cbc -d -in blah.txt.enc -out blah.txt.dec
enter aes-256-cbc decryption password:abc

~/temp$
```

**Comment by latepaul** [comment]
Hitting the same problem

Windows 10 version 1903 (OS Build 18362.720)

WSL OpenSuse 15.1, openssl version reports  "OpenSSL 1.1.0i-fips"
