### ISSUE TITLE
Deletion of file on Windows on DrvFs results in odd behavior

### ISSUE THREAD

**Issue by WhipeeDip** [microsoft/WSL#2300]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening: 
I'm using [chokidar](https://github.com/paulmillr/chokidar), which is wrapped around Node's fs system. (v6.11.0, LTS). This is being run on Node through WSL. I'm watching a JSON file in /mnt/c/somefolder/[...] to check for changes and deletions. Tracking changes works well, but tracking deletions does not. However, when using del through the Windows Command Prompt or rm through WSL, the file does not seem to get deleted. Both Windows and WSL will report the file as existing with actual properties such as file size; however, in both systems the file is seemingly empty and I am unable to use the file in any way. Permissions are denied when I try to edit/overwrite on both systems. When Node ends, the file will properly disappear. On the other hand, deleting this file through Windows's File Explorer works fine with no issues whatsoever, and I am able to track deletions, etc.

* What's wrong / what should be happening instead:
I'm not super familiar with the file systems and how they're tracked, but it does seem that no WSL process has the file opened during the deletion issue. Likewise, it would appear no Windows process has the file open as well. I tried my same program on an actual installation of Xubuntu 16.04.2, and deletions work fine and I am able to track them.

**Comment by sunjoong** [comment]
@WhipeeDip - Hmm... This looks like #2152, I think :)

**Comment by WhipeeDip** [comment]
Appears to be so, thanks! Although out of curiosity, is deletion handled differently through cmd's del vs File Explorer?

**Comment by sunilmut** [comment]
@WhipeeDip - Thanks for your post. Does the issue reproduce for you if you try it in your ~ directory i.e LxFS?

Adding @SvenGroot to see if anything funky is going on with the delete on DrvFS.

**Comment by WhipeeDip** [comment]
I can delete the same file fine under LxFS, with chokidar correctly emitting an unlink event.

**Comment by sunjoong** [comment]
> is deletion handled differently through cmd's del vs File Explorer?

@WhipeeDip - Well... it looks like for me but I'm not sure. Maybe... some expert like @SvenGroot could tell it, I hope :)

**Comment by fpqc** [comment]
@sunjoong I think they changed it to LxFS in the last series of insider builds because VolFS and DrvFS were confusing.

**Comment by sunjoong** [comment]
@fpqc - Ah... Thanks. Then, LxFS might be a proper term :)

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
