### ISSUE TITLE
i could not connect wifite on bash windows 10

### ISSUE THREAD

**Issue by alifin77buamona** [Microsoft/WSL#2301]
hello everyone. and dear all

i need help for my bash on windows 10. my question is below..

[+] scanning for wireless devices...
 [!] no wireless interfaces were found.
 [!] you need to plug in a wifi device or install drivers.
 [+] quitting
Does bash on windows have any direct access to physical hardware like wireless card?
Running parted too has its own errors.

**Comment by sunjoong** [comment]
> Running parted too has its own errors.

@alifin77buamona - #689.

**Comment by therealkenc** [comment]
#1077

**Comment by eaglegeek-cts** [comment]
Lots of people need this for legitimate reasons. Many work in computer security, or simply wish to test their own networks. Very important for lots of people, and should be added to make windows competitive for development work. Specifically AF_PACKET and direct hardware access (for things like CUDA acceleration) is important.
