### ISSUE TITLE
knock utility from knockd not functioning correctly

### ISSUE THREAD

**Issue by CapinWinky** [microsoft/WSL#2306]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening:  
knock -v -d 1000 <knockserverIP> [port sequence to knock]

* What's wrong / what should be happening instead: 
It should knock the ports in order with 1000ms between.
Instead wireshark shows it knocks a port, then retransmits the same knock two more times to the same port with several seconds between retransmissions, then finally times out and does the second knock. It must be waiting for acknowledgement from the knockd server but that's not how knocking works!

In my wireshark, I show the initial knock, then 3 seconds later a retransmission, then 6 seconds later another retransmission, then 13 seconds later it does the second knock. So instead of 1 second between knocks, I have 22 seconds between knocks! That 13 seconds between the last retransmission and the next knock is actually 12 seconds + the delay from the knock command, so it's some kind of doubling delay (3, 6, 12) waiting for an acknowledgement of the packet. Again, knocking should not wait for any kind of response.

**Comment by sunjoong** [comment]
@IsaacABrown - I saw you had left comment on #1584; Maybe... for https://github.com/Microsoft/BashOnWindows/issues/1584#issuecomment-272293076 :)

**Comment by sunilmut** [comment]
@IsaacABrown - Thanks for the post. Can you please collect a strace and share it out?

`strace -r -o <trace_file> -ff <trace_cmd>`

**Comment by therealkenc** [comment]
Tested `knock` on recent (20H1) WSL1 and it appears okay with caveat below. This is/was /dupe #1584.

The caveat: In testing, the `knock` client on WSL1 appeared to be unreliable, while on WSL2 it is perfectly reliable. With WSL1, `knockd` on the receiving end would sometimes get stuck at `Stage 1`. But unlike the OP, the knock tests I was doing had no delay (`-d <milliseconds>`). There is a better than zero chance there is still some incredibly subtle behavioral diverge in WSL1. With a `-d 100`, `knock` is reliable on WSL1, but (as far as I can tell) it _should_ work reliably without delay too. The symptoms strongly suggest the connects arriving in the wrong order, but I didn't pursue enough to confirm. Academic; I can't think of any use-cases _other than_ `knock` where the order would matter.

Long-short, if you use `knock` on WSL1, make sure to include a small delay.
