### ISSUE TITLE
lxrun error popup

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/WSL#2313]
Windows 10.0.14393
  
I see this popup every so often (when I'm not even using BashOnWindows):  
![image](https://user-images.githubusercontent.com/12904270/28067110-13eeb34e-65fd-11e7-9824-f89ea1e1064f.png)

**Comment by benhillis** [comment]
Interesting, I imagine this is coming from there maintenance task that has been removed recently. Did your WSL optional component get disabled?

**Comment by garfieldbanks** [comment]
Nope.
![image](https://user-images.githubusercontent.com/12904270/28070532-777e0a10-660a-11e7-98be-672a68259c2e.png)

**Comment by benhillis** [comment]
Interesting... And that file exists I take it?

**Comment by garfieldbanks** [comment]
Yup.
![image](https://user-images.githubusercontent.com/12904270/28070848-8ed2f8d2-660b-11e7-8352-24f6188ac46c.png)

**Comment by 0xbadfca11** [comment]
The title bar of the console window is "C:\\Windows\\**SysWOW64**\\cmd.exe".
This means caller process may 32-bit. And may be using batch file.

AptPackageIndexUpdate task calls %windir%\\system32\\lxrun.exe directly.
It is strange that the title bar of the console window is set to "cmd.exe" even if an error has occurred.
There is no room for a 32-bit process to intervene, too.

I think that you can see who is doing by checking process tree in [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx).

**Comment by benhillis** [comment]
This task was removed long ago.
