### ISSUE TITLE
Open a child instance of bash in a new window

### ISSUE THREAD

**Issue by camsteffen** [Microsoft/WSL#232]
Is this possible? Basically, I just want to run ssh-agent and then open a new window.

**Comment by benhillis** [comment]
Does it have to strictly be a child of the other process? If not you can just launch two instances of bash.exe.

**Comment by camsteffen** [comment]
If it is a child, then I would not have to log in to ssh-agent twice.

**Comment by benhillis** [comment]
Could your run ssh-agent in the background?

**Comment by camsteffen** [comment]
how? have you ever used ssh-agent?

**Comment by benhillis** [comment]
Yes I've used ssh-agent before - I'm just trying to understand what you're asking.

If you're talking about spawning a new version of bash.exe from inside bash.exe (similar to typing 'start' in cmd.exe) that is not currently supported.

This would be a good candidate for a feature request on our [user voice page](http://aka.ms/winbashuv).

**Comment by therealkenc** [comment]
The OP request here was to launch a new console window from within WSL. 
```
$ cmd.exe /c start cmd.exe /c wsl.exe
```
Interop support was added in Creators Update 15063.

**Comment by notAxion** [comment]
even better one if you want to open a certain distro
go to the explorer type `shell:AppsFolder`
find your distro make a shortcut to your desktop
and do this within your wsl 
```
$ wsl.exe /c <distro name you can find on the desktop>.lnk
```
you can also copy the shortcut to somewhere and use the absolute path instead of only distro name you might need to use `""` enclosing the path
