### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create!

### ISSUE THREAD

**Issue by mcandre** [microsoft/WSL#2324]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```console
Microsoft Windows [Version 10.0.15063]
```

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Trying to launch WSL bash.exe.

* What's wrong / what should be happening instead:

Shouldn't be seeing any warnings or errors on launch.

By the way, `/tmp` does appear to in fact exist once in bash.exe. Something about how WSL bash launches makes it confused.

**Comment by benhillis** [comment]
@mcandre - thanks for posting. Could you provide a little bit more information on where this error is coming from?  What are you running that's displaying this message?

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
