### ISSUE TITLE
Python3 -m venv doesn't work properly and keeps giving 'not installed' error message

### ISSUE THREAD

**Issue by chxzqw** [microsoft/WSL#2326]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
* What's wrong / what should be happening instead:
Basically I try to build virtual environment by 'python3 -m venv [foldername]', which keeps saying the venv module is not installed even it is definitely installed.
![bashonwindows_python](https://user-images.githubusercontent.com/2109330/28150322-3da01c7e-67d7-11e7-839e-125234c285e2.jpg)
It actually creates the folder however lacks of some core files like ./bin/activate.sh ,etc..

**Comment by jakegt1** [comment]
I've just tried this on my version, works fine, but I do remember having this issue at some point.. I think I was still running 14.04 at that time?

Are you running 16.04 or 14.04?

**Comment by chxzqw** [comment]
Yep my one is 16.04. Sorry about not mentioning that.

**Comment by jakegt1** [comment]
Not really sure what's wrong then: 
![vcxsrv_2017-07-14_16-17-49](https://user-images.githubusercontent.com/6144562/28218298-06ddb42e-68b0-11e7-80eb-cefc776401ec.png)

**Comment by chxzqw** [comment]
Yes. I did.

**Comment by jakegt1** [comment]
That will likely be the reason, if you upgrade form 14.04 it can cause odd bugs like that.

I'd recommend you do a full reinstall using lxrun, will mean you will lose your data inside of bash for windows though. May be worth copying it somewhere.

**Comment by chxzqw** [comment]
Thanks for that. Will give it a try.

**Comment by chxzqw** [comment]
Yep I did the Ubuntu upgrade by 'do-release-upgrade' which is probably the cause.
This time I just use lxrun/uninstall and lxrun/install to get a clean 16.04 distro and the python module works fine though I got some ipv6 issues during apt operations.

So should I close this ticket or just leave it ?

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
