### ISSUE TITLE
Memory usage info does not work properly (/proc/[PID]/status)

### ISSUE THREAD

**Issue by mloskot** [microsoft/WSL#2328]
* Your Windows build number: Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:

```
$ cat /proc/self/status | grep VmPeak
VmPeak: 0 kB
```

and same for any `/proc/[PID]/status`.

Is this expected?

I suspect, this may be known limitation of WSL but I've failed to find it documented or confirmed.

* What's wrong / what should be happening instead:

I'd expect `VmPeak > 0`

**Comment by mvlabat** [comment]
The problem still exists in Windows 10 1903 18362.239
