### ISSUE TITLE
TIOCSTI ioctl not supported on stdin

### ISSUE THREAD

**Issue by thomasbrandon** [Microsoft/WSL#2332]
**Version:** Microsoft Windows [Version 10.0.16237.1001]

The TIOCSTI ioctl is not supported by stdin on WSL. For context I am trying to use the [esp-idf IoT SDK](https://github.com/espressif/esp-idf) for the ESP32 chip where the serial monitor tool uses the pyserial miniterm.py library which uses this ioctl [here](https://github.com/pyserial/pyserial/blob/master/serial/tools/miniterm.py#L165).

## WSL Output
```
$ python -c "import sys, fcntl, termios; fcntl.ioctl(sys.stdin.fileno(), termios.TIOCSTI, b'\0')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 25] Inappropriate ioctl for device
```

## Ubuntu output
```
$ python -c "import sys, fcntl, termios; fcntl.ioctl(sys.stdin.fileno(), termios.TIOCSTI, b'\0'); print 'OK'"
^@OK
```

**Comment by therealkenc** [comment]
#1863

**Comment by thomasbrandon** [comment]
Thanks for the link, should have done better searching it looks. After looking at those issues I'm not sure on the best option here.
TIOCSTI doesn't look like a great ioctl to implement in WSL given security issues and general lack of use so perhaps better fixed in pyserial (above issue added).
I'm happy to hack at it but welcome any suggestions as not familiar with the details.

**Comment by therealkenc** [comment]
Dvorka seems to have found a solution which might or might not apply to your use case. He seems like a friendly guy; if you head over to [dvorka/hstr#186](https://github.com/dvorka/hstr/issues/186) I am sure he'd be happy to help.

I hope the WSL team implements the feature; and, on the premise that eventual Linux kernel parity is the goal, eventually they will. But lack of use is really the gate here. It's hard to imagine someone picking that ticket off the scrum wall given the nearly bottomless list of other stuff on offer.

As a comedic aside, it occurred to me early in the project that there is a way to game the system. Find someone with a popular package to use the feature. 😉

Bonne chance.

**Comment by fpqc** [comment]
@therealkenc Slightly offtopic, I was trying to do this with OSC52 support, but I couldn't figure out who to contact to submit patches to libvte and gnome-terminal.  suckless st finally supported it after an IRC war with the devs and my patch being initially rejected.  Right now I think it's supported only by `tmux` (internally and externally), `vim`, `st`, `xterm`, and `mintty` (on Windows), but I think that getting support into libvte and gnome-terminal would finally make it mainstream.

**Comment by therealkenc** [comment]
This was a dupe of #1863.
