### ISSUE TITLE
Cannot execute symlink'd binaries

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2335]
Under Windows 15063.483:

C:\Users\Mahmoud\bin\ is in my path

```
> mklink C:\full\path\to\binary.exe C:\Users\Mahmoud\bin\binary.exe
> binary.exe #verify it works
> bash
mqudsi@ZBook /m/c/U/Mahmoud> binary.exe
Failed to execute process '/mnt/c/Users/Mahmoud/bin/binary.exe'. Reason:
exec: Exec format error
The file '/mnt/c/Users/Mahmoud/bin/binary.exe' is marked as an executable but could not be run by the operating system.
```

**Comment by therealkenc** [comment]
See also #1475, which is now complicated by the fact that WSL is available in non-developer mode. Blog post [here](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/). User Voice [here](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/).

**Comment by sunjoong** [comment]
@therealkenc - User Voice link on your comment is same to that of Blog post :)

**Comment by therealkenc** [comment]
Oops. Bad cut-and-paste. Fixed up, plus added a duplicate. Because UserVoice.

**Comment by sunilmut** [comment]
@mqudsi - This should work starting build [16193](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16193) with `Added support in DrvFs for following NT symlinks.`. I tried it and it works fine (with symlink to notepad.exe). Currently, DrvFS is also case-sensitive. And, so, just be careful while creating the symlink to use proper case.

**Comment by mqudsi** [comment]
Awesome, thanks @sunilmut !
