### ISSUE TITLE
 win32 "os.networkInterfaces()" does not support

### ISSUE THREAD

**Issue by zengquan** [Microsoft/WSL#2337]
Recently learning weex , Run on the server side
`cd weex-dingtalk-todo\todo-server`
`npm run serve`

Reported error：
`2017-07-16 09:37:12:511 - error: win32 "os.networkInterfaces()" does not support`

My computer development environment：
`Windows10 64 bit`
`node  => v6.10.2`
`npm   => 3.10.10`

The port is closed when WannaCry（Wanna Decryptor） occurs
`135 port`
`137 port`
`138 port`
`139 port`
`445 port`

project address：
https://github.com/open-dingtalk/weex-dingtalk-todo

Email：1069064283@qq.com

**Comment by MikeGitb** [comment]
Just to make sure: you are trying to run this from within the wsl (windows subsystem for linux) bash shell, not from a normal windows command line, right?

**Comment by zengquan** [comment]
I was running in the windows command line

**Comment by MikeGitb** [comment]
Then this is probably the wrong repository to report this issue. From the readme:

> This repo is for the reporting of issues found within and when using Bash on Ubuntu on Windows.
