### ISSUE TITLE
Yarn doesn't work

### ISSUE THREAD

**Issue by dmdnkv** [Microsoft/WSL#2341]
Ubuntu Bash 16.04.2 LTS (clean installation after Windows Creators Update)
Microsoft Windows [Version 10.0.15063]
Any `yarn add` command doesn't work, gulp installation is here for example only.

```
/$ yarn global add gulp
yarn global v0.27.5
nodejs: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
```

**Comment by therealkenc** [comment]
#2120 #2142 #2563 etc
