### ISSUE TITLE
Inbound ports behind Windows Firewall not open

### ISSUE THREAD

**Issue by JoeMShanahan** [Microsoft/WSL#2342]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Attempting to run a web server within a Bash on Windows terminal. I can only access this webserver from my local machine.

* What's wrong / what should be happening instead:

Machines on my network should be able to enter `http://hostname:port/path` address and access the server  but they can't. If I completely disable Windows Firewall (ugh!) then my server _is_ accessible externally.

**Comment by JoeMShanahan** [comment]
Worth noting - I've tried adding inbound/outbound accept-all rules for `C:/system32/bash.exe` but this did not work.

**Comment by therealkenc** [comment]
`bash.exe` isn't the program that is accepting connections (that would be akin to accept-all for `cmd.exe`). Just punch a hole in the ports you want open (80, 8080, 3000, 5555, whatever). This is no different than if you had your server running in a VM instead of WSL.

**Comment by fpqc** [comment]
@therealkenc for what it's worth, hyper-V uses a virtual switch and doesn't firewall VMs.  It firewalls only the virtual adapter that the host pc uses to connect to the vswitch

**Comment by JoeMShanahan** [comment]
All the VMs I've used self-manage connections which goes contrary to what you're saying @therealkenc 

I appreciate this is a different situation though.

**Comment by therealkenc** [comment]
Yes ack that my "no different than" was at best confusing. I had keyed in on the words in the OP saying "my server is accessible externally" to mean over the wire to another machine on the local network. Appreciate the clarification on VM behaviour, which is of course correct.

**Comment by therealkenc** [comment]
#1852
