### ISSUE TITLE
dnf metalink mirror update regression

### ISSUE THREAD

**Issue by ytrezq** [microsoft/WSL#2349]
Since I updated to 10.0.15063 I’m no longer able to update packages because dnf print an error message telling it fails to synchronize cache *(without explaining why)*.

This affect all version of fedora. It previously worked under 10.0.14393

**Comment by fpqc** [comment]
If you get a fedora docker image, untar it, and chroot into it, does dnf work?

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
