### ISSUE TITLE
Increase compatibility with xterm's supported terminfo capabilities

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2350]
I know that conhost has recently undergone a great number of improvements to improve the compatibility with WSL applications, and really appreciate the dramatic changes and increased capabilities in 15063 as compared to the initial release.

If it's not out of the question, these are some useful xterm key mappings that are missing in `15063.483`. This isn't by any means an exhaustive list, but just a few that I've run into:

* `back tab` (shift + tab). Should be `\E[Z`, currently returns `^I` (regular tab). Supporting this enables backwards navigation in any command line interface presenting lists (shell completions, vim, etc)
* `ctrl + bkspc`: as far as I can tell, this should generate the value in (`^H`, `^?`) that is not generated by bkspc (currently bkspc generates `^?`, so ctrl+bkspc should generate `^H`. This will allow Windows-compatible delete-previous-word operations. Currently, `ctrl+bkspc` returns the same thing as `backspace`.
* `ctrl+/` currently generates (as far as I can tell) no codes at all. It should return the same as `^_` (`0x1f`). This is mapped to undo for a lot of console applications (emacs-compatible) and is a common user shortcut in vim.

An awesome one to have would be `<ctrl+tab>`, but there's no agreed upon code for that, as far as I can tell.

Some references:

* http://invisible-island.net/xterm/terminfo.html
* http://pubs.opengroup.org/onlinepubs/7908799/xcurses/terminfo.html
* ftp://invisible-island.net/shuford/terminal/swedish_vt102_codes.txt
* http://www.ibb.net/~anne/keyboard.html

**Comment by zadjii-msft** [comment]
Lemme take a look, I thought we implemented those, but they may have regressed when I added support for arrows+modifier.

**Comment by zadjii-msft** [comment]
> back tab (shift + tab). Should be \E[Z, currently returns ^I (regular tab). Supporting this enables backwards navigation in any command line interface presenting lists (shell completions, vim, etc)

Whoops, looks like I only added support for parsing a `\E[Z`, but not also sending it.

> ctrl + bkspc: as far as I can tell, this should generate the value in (^H, ^?) that is not generated by bkspc (currently bkspc generates ^?, so ctrl+bkspc should generate ^H. This will allow Windows-compatible delete-previous-word operations. Currently, ctrl+bkspc returns the same thing as backspace.

I concur that we're not sending `C-h` on `Ctrl+Bkspc`, which is different from xterm et al. Though, I don't think that `Ctrl+Bkspc` is usually bound to delete-previous-word (or `backward-kill-word`). It does appear that typically `Alt+Bkspc` is commonly also bound to delete-previous-word, and that does work. 

> ctrl+/ currently generates (as far as I can tell) no codes at all. It should return the same as ^_ (0x1f). This is mapped to undo for a lot of console applications (emacs-compatible) and is a common user shortcut in vim.

I was not aware of that.  Seems pretty straightforward to me.

<hr>

These all look like pretty reasonable requests to me. I'll get started on them, but I'm not sure they'll be able to get in for this release.

**Comment by mqudsi** [comment]
@zadjii-msft thanks a bunch! Really appreciate it!

**Comment by mqudsi** [comment]
@zadjii-msft could we possibly add alt+del to that list? The delete key sends `\e\[3~`, alt-del under xterm sends `\e\e\[3~` (you can try it out under putty with, I think, the default key bindings).

**Comment by zadjii-msft** [comment]
No problem! That should have probably bee added a while ago, my bad. Added to the others.

**Comment by mqudsi** [comment]
@zadjii-msft  Thanks a bunch. Additionally, `ctrl+w` does not seem to be sent; it seems to only send `w` in my testing.

**Comment by zadjii-msft** [comment]
@mqudsi  Well that's odd. Ctrl+W seems to be just fine on mine end. I just tested in bash and emacs and both seemed to pick it up just fine. Are you sure there's nothing in a configuration somewhere (.inputrc, .tmux.conf, .vimrc, etc) that might be eating the C-w?

Pressing Ctrl+V, Ctrl+W in bash:
![image](https://user-images.githubusercontent.com/18356694/30553149-2367773c-9c55-11e7-8496-f5495ea7882a.png)


Pressing Ctrl+H, k, Ctrl+W in emacs:
![image](https://user-images.githubusercontent.com/18356694/30553177-3da207ac-9c55-11e7-9bc1-789f3359c4e4.png)

**Comment by mqudsi** [comment]
I can't get it to work in even in bash, launched directly without any customization. I thought maybe it was related to "insert mode" or "enable ctrl key shortcuts" but that does not seem to be the case.

I'm still on Creators Update, perhaps this was fixed in a build since then? (Presuming you're running something more recent.)

I use demo_altkeys from the ncurses-examples package (not installed to PATH by default, found under `/usr/lib/ncurses/examples/demo_altkeys`) to test key sequences; I've found it to be a reliable alternative to `showkeys` (which is broken under WSL because of its incorrect tty tests).

**Comment by mqudsi** [comment]
I apologize, the `ctrl+w` issue was due to a Windows program running in the background that was globally intercepting (and then selectively forwarding) that particular key sequence.

**Comment by chradcliffe** [comment]
I am experiencing a similar issue with `Alt-Backspace` in terminal emacs on WSL.

In emacs, `C-h k Backspace` shows `Backspace` bound to `DEL` (i.e. `^?`), but `C-h k Alt-Backspace` shows `Alt-Backspace` bound to `Ctrl-Alt-h`. 

`Alt-Backspace` works fine in the shell, since `Ctrl-h` is interpreted as traditional Backspace (delete previous char), but in emacs (where the delete sequence is `^?` and distinct from `Ctrl-h`) it seems to fall down.

I was wondering if this ticket is intended to cover the `Alt-Backspace` issue as well -- I was thinking it might be related to the `Ctrl-Backspace` issue mentioned above.

**Comment by zadjii-msft** [comment]
I just checked in some code to add support for these keystrokes. Should be on the way out to insiders over the next month.


@chradcliffe I believe the fix I checked in should also address `M-Bksp` as well as `C-Bksp`

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#86
