### ISSUE TITLE
Firefox unable to install extensions. 

### ISSUE THREAD

**Issue by SRGOM** [microsoft/WSL#2353]
Low priority since this is not a dev scenario and I haven't even attached an strace but I'm mentioning it here so in case devs decide to support GUI Apps, they can see that this is a problem. 

* winver -> 15063.483 

* What's happening: Open WSL -> Open Firefox -> Install Extension -> See extension "installing" for days. 

* What should happen: It should be able to install the extension after a reasonable period of time. 

* Strace, I can't get strace to attach to Firefox!

**Comment by SRGOM** [comment]
Workaround- copy a working profile. I copied from Linux but maybe a Windows profile would work too.

**Comment by hungsh** [comment]
Any update on this issue? I encountered the same problem and it seems to be easy to reproduce it in build 16299.64 too. I got the following error message when trying to install an addon:
```
1511285980310       addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1511285980319   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing permissions.7: Unknown permission "unlimitedStorage"
1511285980321   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing devtools_page: An unexpected property was found in the WebExtension manifest.
1511285980322   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing minimum_opera_version: An unexpected property was found in the WebExtension manifest.
1511285980328   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.
```

**Comment by therealkenc** [comment]
Unless you get lucky, generally for unsupported graphics stuff you'll have to track it to an actionable WSL issue (failing or misbehaving Linux kernel surface) with `gdb` and `strace`. Like SRGOM intimated there is no real use case so no one has jumped in to look.

**Comment by hdadhich01** [comment]
Still persists

**Comment by alanlivio** [comment]
Still persists
