### ISSUE TITLE
Corrupt entries in FS on Windows Side

### ISSUE THREAD

**Issue by SRGOM** [microsoft/WSL#2355]
* winver -> Current Stable (15063.483)

* What did you do -> I copied a directory to Windows (outside of lxss directory) and shared it between Linux install and WSL install. Don't recall the entire sequence of commands but to my best recall the folder was never in the Linux Share. I think I only ever accessed Windows side filesystem from Windows/Linux/WSL so stuff shouldn't be corrupted.

* What happens -> Corrupted directory. `ls` from WSL fails. `ls` from Windows lists a few files and then fails. More on what happens below

* Strace -> NA

```
[~/.ivy2/cache/com.typesafe.play/twirl-parser_2.10/docs]ls -al
total 215M
drwxrwxrwx 0 root root 4.0K Aug 22  2016 .
drwxrwxrwx 0 root root 4.0K Mar 16 00:16 ..
-rwxrwxrwx 1 root root 423K Aug 21  2016 twirl-parser_2.10-1.0.2-javadoc.jar
[~/.ivy2/cache/com.typesafe.play/twirl-parser_2.10/docs]du -h
213M	.
[~/.ivy2/cache/com.typesafe.play/twirl-parser_2.10/docs]

```

I'm noting this in case you guys want to look into it, I currently have no problems. This btw, happened when i was running on WSL. The shared directory's actual location is Windows.

**Comment by benhillis** [comment]
@SRGOM - will you please fill out our issue template?

**Comment by SRGOM** [comment]
@benhillis Oops updated.

On second thoughts, while I'm  almost certain that the directory was never inside lxss folder, I don't know if this issue helps you in any way since the instructions to reproduce are absent. Feel free to close if this is distracting. I only wanted to note so you can keep an eye out.

**Comment by shevegen** [comment]
I think they need to be able to reproduce it.
