### ISSUE TITLE
qemu-i386 pthread_create segmentation fault

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [microsoft/WSL#2357]
### Windows version / build number
```
C:\Users\Artem>ver

Microsoft Windows [Version 10.0.15063]
```
### Steps required to reproduce
```
$ sudo apt-get install qemu
$ gcc testqemupthread.c -o testqemupthread -lpthread -m32
$ qemu-i386 testqemupthread
```
[`testqemupthread.c` contents](https://gist.github.com/WPMGPRoSToTeMa/9f4e35a1d5a507d5bc77136e9aba8219)
### Copy of the terminal output
```
artem@DESKTOP-772DMBE:~$ qemu-i386 testqemupthread
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```
### Expected Behavior
The order of lines can change. It runs normally on `Ubuntu 16.04.2 LTS`.
```
Thread 1
pthread_create() for thread 1 returns: 0
pthread_create() for thread 2 returns: 0
Thread 2
```
### Strace of the failing command
https://gist.github.com/WPMGPRoSToTeMa/02ed118afa9fbccd20eb541247667c36

**Comment by fpqc** [comment]
The environment does not support 32-bit linux programs and also probably does not support running them through qemu.

**Comment by WPMGPRoSToTeMa** [comment]
@fpqc yeah I know about it, that is why I'm trying to run them through qemu. I also have problems with `stat`, but I just changed it to `stat64`.

**Comment by shelru** [comment]
@WPMGPRoSToTeMa pidor!

**Comment by shelru** [comment]
@WPMGPRoSToTeMa skolko eshe jdat? Kogda tu yje zaymesha delom?A?A?A?

**Comment by poizan42** [comment]
@fpqc I don't think that makes sense, as far as I know qemu interprets the machine code by default so it should never execute any 32-bit code on the cpu.

**Comment by fpqc** [comment]
@poizan42 No, it attempts to use native syscalls if they are available to my knowledge.  There is another software called unicorn that emulates the architecture for use in reverse engineering and doesn't use any kind of speedup.

**Comment by therealkenc** [comment]
Addressed in WSL1 somewhere along the way.

![image](https://user-images.githubusercontent.com/7049700/117202351-902b5c00-ada2-11eb-8f15-e1dc4f82b5b3.png)
