### ISSUE TITLE
WSL & Bitdefender 2018 network connectivity issue / clarrification?

### ISSUE THREAD

**Issue by Ncage1974** [Microsoft/WSL#2360]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt): 1703 (creators update)

* What you're doing and what's happening:  absolutely no network connectivity

Guys i've seen similar issues created. I'm running Bitdefender Total Security 2018 and have absolutely no network connectivity. Its bitdefender's firewall because if i turn it off everything works fine. Unfortunately other than totally turning it off is the only solution. If i turn it off bitdefender constantly screams at me that i'm insecure which i of course don't want.  

I've set my network adapter to be "Home/Office" which is the weakest settings (other being public).  I've turned off "Stealth Mode". "Default application behavor" is set at "allow".  Unless there are some rules i can create.  Bitdefenders settings are that granular like kasperskys are.

What i'd also really like to know is this a WSL issue or is this a bitdefender issue. I'm wondering if i should be trying to press bitdefender to fix it or maybe this is something what will be fixed with an upcoming release of WSL?

**Comment by sunilmut** [comment]
@Ncage1974 - Thanks for your post and sorry to hear that Bitdefender and bash still do not not work in tandem. You can read through the long thread #475, which is essentially the same. In short, there is some work that AV vendors need to do to support WSL processes. In RS2 (a.k.a Creators Update), Windows released some API's that allows AV/firewall vendors to get notifications for WSL processes. Now, they need to do the work to hook it up to their software. They should already have the doc from our side, but, if not, if you talk to them, you can tell them to contact the WSL/bash team at Windows. And, we will get them the information they need.

**Comment by sunilmut** [comment]
Alternatively, you can point them to this blog post
https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/

**Comment by E14** [comment]
I've been in contact with BitDefender support about this issue. They're investigating / trying to fix the issue, but for now it seems there is a workaround:

You can set the adapter to **Public** [`BD => View Features => Firewall Settings => Network Adapters`], and for me, Bash was instantly able to access the internet, without even restarting Bash or anything.

Maybe that will help someone.

**Comment by YvanDaSilva** [comment]
Thank you @E14 !

**Comment by sunilmut** [comment]
Thanks, @E14 for following up with BitDefender. I am closing this issue out here.
