### ISSUE TITLE
All commands goes error when running shell files

### ISSUE THREAD

**Issue by wanglovesyang** [Microsoft/WSL#2361]
Everything seems good when I was typing the command in the bash prompt, however thing goes wrong when I execute a shell file.

The file looks like this:

cd ../../..
export GOPATH=`pwd`
cd -

and the error goes this way

: not found: build.sh:
build.sh: 3: cd: can't cd to ../../..
build.sh: 5: cd: Illegal option -
: not found: build.sh:

even cd command does not work in shell file mode.

**Comment by benhillis** [comment]
@wanglovesyang - Could you please fill out the issue template?  I'm not able to reproduce this.

```
benhill@BENHILL-DELL:~$ cat foo2.sh
cd ../../..
export GOPATH=pwd
cd -
benhill@BENHILL-DELL:~$ ./foo2.sh
/home/benhill
benhill@BENHILL-DELL:~$
```
