### ISSUE TITLE
File/Directory handles opened and closed by bash or linux tools are accumulating in System process [PID 4]

### ISSUE THREAD

**Issue by 4creators** [microsoft/WSL#2362]
Windows version - Microsoft Windows [Version 10.0.15063] x64 base lang pl-PL, uses lang pack en-US
Installed: VS 2015, VS 2017 RTM, VS 2017 15.3 preview4, Intel Parallel Studio Cluster Edition 2017 v4, 
Installed Windows Kits: 10150, 10240, 10586, 14393, 15063 (latest)

Problem description:

After building dotnet/coreclr repo in WSL bash seems that all files which were opened during build, including temporary ones, despite being closed from bash perspective (build tools or bash scripts are no longer executing and processes have already exited cleanly - build succeed) they handles are dangling in System process [PID 4] as reported by processexplorer64 by Sysinternals. In my case search  for handles containing coreclr string returned 10 000 handles located in coreclr repo `C:\Users\developer\AppData\Local\lxss\home\developer\git\coreclr\` and stopped enumerating most probably due to reaching max number of search results displayed. I have checked this after navigating with bash away to windows file system under /mnt/ directory.

Below are same examples of opened handles.
```
System	4	File	C:\Users\developer\AppData\Local\lxss\home\developer\git\coreclr\src\mscorlib\shared\System\Globalization\JapaneseCalendar.Unix.cs
System	4	File	C:\Users\developer\AppData\Local\lxss\home\developer\git\coreclr\Tools\dotnetcli\shared\Microsoft.NETCore.App\2.0.0-preview1-001913-00\System.Security.Cryptography.Native.OpenSsl.so
System	4	File	C:\Users\developer\AppData\Local\lxss\home\developer\git\coreclr\Tools\dotnetcli\sdk\2.0.0-preview1-005724

```
 

Steps to reproduce:

Build [dotnet/coreclr](https://github.com/dotnet/coreclr/) following linux build instructions.
Verify how many handles remained open in System process using any relevant tools.

**Comment by benhillis** [comment]
@4creators - thanks for filing. Is this causing issues in your scenario or just something that you noticed?  We do keep some handles open in our LxFs inode cache.

**Comment by 4creators** [comment]
There were some problems to delete another unrelated directory `e:\coreclr -> /mnt/e/coreclr` which I have used for windows based coreclr build before I have built WSL repo. Another problem is that git commands involving large number of files are very slow in comparison to git commands run under windows - 2 - 3 x slower (git clone, changing branch with git checkout). 

Handles for WSL based repo were checked about 3 hours after WSL build, but immediately after `/mnt/e/src/ms/dotnet/coreclr` repo build. There were no open handles for `/mnt/e/src/ms/dotnet/coreclr` or `e:\src\ms\dotnet\coreclr` at that time (probably due to enumeration limit). Now after next 2 hours there are 2891 handles containing `coreclr` string still open but only 1 points to `e:\src\ms\dotnet\coreclr` all others point to `C:\Users\developer\AppData\Local\lxss\home\developer\git\coreclr\`.

**Comment by sunilmut** [comment]
@4creators - Thanks for the details. As @benhillis points out and as you noticed, WSL does some caching in LxFS (~), but there is no caching in DrvFS (/mnt/c). You should not have any problems deleting files. If you have repro, we would like to know.

Just for clarification:
> Another problem is that git commands involving large number of files are very slow in comparison to git commands run under windows - 2 - 3 x slower (git clone, changing branch with git checkout).

By `git commands run under windows`, do you mean git commands run in WSL on DrvFS (/mnt/c) or on `git for Windows`?

**Comment by 4creators** [comment]
> By git commands run under windows, do you mean git commands run in WSL on DrvFS (/mnt/c) or on git for Windows?

I mean `git for Windows`

**Comment by sunilmut** [comment]
@4creators - Thanks for the clarification.

Yes, filesystem perf issue is a well established thing now, see #873. We are looking into it, but you can also help us prioritize it by casting your vote in the [user voice ticket](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system).

Meanwhile, if you have a repro for this particular issue, please share it out.

**Comment by Gamberoni** [comment]
Got a Windows NT Server SP6 installed in 1996, and still in production, that has this behavior.
Please, be respectful of old people.
Exact way of replicating the bug, here, is:
 1 - mount a share from the windows server on a linux machine, chmod a file there.
`   $ sudo mount --verbose -t cifs "//nt1/test" ./mnt -o user=marco,domain=ufficio,vers=1.0,uid=marco
    $ touch mnt/afile
    $ chmod +x mnt/afile`
Now the System process on the server has an open handle to the chmodded file.

**Comment by therealkenc** [comment]
The repro above is on "a Linux machine" not WSL. The OP did not have a repro.
