### ISSUE TITLE
Visual Studio include path can't see into /mnt/

### ISSUE THREAD

**Issue by haydentech** [microsoft/WSL#2371]
Launching a compile with Visual Studio's command-line compiler, and using a full include path into /mnt, produces an error:

```
cl.exe -c -I/mnt/c/git/foo/include test1.c
test1.c(11) : fatal error C1083: Cannot open include file: 'includes.h': No such file or directory

```

The file does exist:
```
ls -l /mnt/c/git/foo/include/includes.h
-rwxrwxrwx 1 root root 56212 Jul 21 13:44 include/includes.h
```

However, if I use relative paths when I run the command, it works:

`cl.exe -c -I../include test1.c
`
Versions Used:
Microsoft Windows [Version 10.0.15063]
Visual Studio 2013

This same compilation run works successfully under Cygwin, for whatever that's worth.

**Comment by therealkenc** [comment]
This is #1397 ([message](https://github.com/Microsoft/BashOnWindows/issues/1397#issuecomment-262104409), "This one is more complicated" part) and #1243 ([message](https://github.com/Microsoft/BashOnWindows/issues/1243#issuecomment-255571288)). Try:
```
$ cl.exe -c -IC:git/foo/include test1.c
```

**Comment by haydentech** [comment]
@therealkenc You were on the right track.  This is what eventually worked:

`$ cl.exe -c -IC:/git/foo/include test1.c`

This will require changes to our build process though.  If we could use /mnt/c/... it would "just work" in the same way it does for all other platforms (including win32 under cygwin).

Thanks!

**Comment by therealkenc** [comment]
Yeah sorry I cut-paste-edited from your message blind 😳.  Those links above have some expository on why it is difficult/problematic to implement. I maintain it is doable with a big enough hammer. But it's a big hammer that certainly isn't destined for the Fall Update.

**Comment by benhillis** [comment]
This is definitely an area I would like to improve in the future.

**Comment by haydentech** [comment]
So we've discussed Windows program using WSL paths.  Is there any hope for the inverse functionality, where the Linux environment could use Windows paths?  As a simple example, this command works fine in cygwin, but fails in Ubuntu-on-Windows:
`cd C:`

**Comment by sunilmut** [comment]
@haydentech 
> Is there any hope for the inverse functionality, where the Linux environment could use Windows paths?

There are no plans for that right now. But, if there is a scenario that interests you and is not currently implemented, you can help us prioritize it by voicing your opinion through the [user voice portal](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/).

**Comment by therealkenc** [comment]
> Is there any hope for the inverse functionality, where the Linux environment could use Windows paths?

The problem isn't even really the "no plans" part. The problem (if that is the right word) is `bash` uses colon as the path separator. You can make `C:` a symlink to `/mnt/c` right now. So even if you vote this though the roof, you still need to patch `bash` not WSL. The '`\`' '`/`' difference is mostly (though not entirely) a non-issue because the Windows side is okay with both already, and you'd be going out of your way to escape backslash in WSL. There is a similar post related to `git` #1855 ([message](https://github.com/Microsoft/BashOnWindows/issues/1855#issuecomment-291963504)).

**Comment by therealkenc** [comment]
Well, what have we here that I never noticed..... 16257

```
root@WinDev1612Sys:/home/ken/Devel/alpine-chroot# mount
rootfs on / type lxfs (rw,noatime)
root on /root type lxfs (rw,noatime)
home on /home type lxfs (rw,noatime)
[...]
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /mnt/c type drvfs (rw,noatime)    <---- Was ist das?
```
