### ISSUE TITLE
Can not Rails s -b 0.0.0.0

### ISSUE THREAD

**Issue by oHoVietTuan** [Microsoft/WSL#2373]
* Your Windows build number:  Microsoft Windows [Version 10.0.14393]  

* What you're doing and what's happening:  I ran `rails s -b 0.0.0.0` to run rails project for another computer via Lan using IPv4. If I type IPv4 from `ipconfig` in this computer I can join, but another computer can not; althought join same network

* What's wrong / what should be happening instead: I think the problem is WSL can not support ip for another computer join this. Or something like that

**Comment by ztolley** [comment]
This worked fine for me, I had to open the port on windows firewall

**Comment by nguyenbathanh** [comment]
Rails works fine for me. I haven't got any problem with it.
