### ISSUE TITLE
SSHD server is running but Connection refused on WSL

### ISSUE THREAD

**Issue by Brandon-Xu** [Microsoft/WSL#2376]
I have done everything I could do, with this document help
 [https://superuser.com/questions/1111591/how-can-i-ssh-into-bash-on-ubuntu-on-windows-10/1114162#1114162](url) 

I had apt remove --purge openssh-server and install this.
But when I full-restart sshd, the process is running
![kik9 dj 052m n 0a jt](https://user-images.githubusercontent.com/2850261/28723218-aa4da5ea-73e8-11e7-86e7-8caa5c30f750.jpg)
And the process is running in windows too.
![2 jqmczaa 2wzuwypt6dv3](https://user-images.githubusercontent.com/2850261/28723258-c7f69ff2-73e8-11e7-8da1-1991ff31588a.png)

But I can't find the port bind in netstat -a, my port is set to 2222
this is TCPView's result
![9e wtwxn_c d36v n 4ndmm](https://user-images.githubusercontent.com/2850261/28723443-54f7a75c-73e9-11e7-8c1c-a3eb0024ddc2.jpg)

I have added the rule in my windows firewall (I am Chinese :P)
![ez ugxypti76_lalx do vv](https://user-images.githubusercontent.com/2850261/28723643-f0a87d98-73e9-11e7-86a9-b21dfaa73540.jpg)
And also added the rule in my antivirus's IP connection controller 
![_ _5 qlz8 d5 m _ ftu w](https://user-images.githubusercontent.com/2850261/28723706-2af3fafe-73ea-11e7-8183-abc3c5f2fc39.png)

BUT！！！
![w x6ja cwoqewhv y4hqqj7](https://user-images.githubusercontent.com/2850261/28723733-42fb429c-73ea-11e7-9c1f-5357d537edb1.png)

this is when I use < /usr/sbin/sshd -d > show me the log.
![ymqbpvcem vjuxg71t5o dd](https://user-images.githubusercontent.com/2850261/28723884-d1c022ae-73ea-11e7-9540-832dca53e1bd.png)

this is my conf
![dn39tl4ctta smuz s 7](https://user-images.githubusercontent.com/2850261/28723996-2e89717a-73eb-11e7-858c-b05d5967a3af.jpg)

I have no idea about this...
sssssome one can help me ?  `_(:з」∠)_`

`！！（╯' - ')╯︵ ┻━┻ `     Overturned the table
`┬─┬ ノ( ' - 'ノ)  `            Take it back.
.
..
...
....
# `(╯°Д°)╯︵ ┻━┻ `   AND DO IT AGAIN !!!

emm.. my English is not really good, never mind the syntax error  `╮(╯_╰)╭`, and thank your help.

**Comment by benhillis** [comment]
Please mind your language, I have edited your post to remove the offending word.

**Comment by Brandon-Xu** [comment]
@benhillis Ohh, sorry, I'm first push issue in github, don't know the rule.

**Comment by therealkenc** [comment]
> Ohh, sorry, I'm first push issue in github, don't know the rule.

或者在官话中说话，所以他们不知道。😉

This looks a lot like #1554. There is also some Chinese speakers over there who might be able to help. Good luck.

**Comment by SRGOM** [comment]
Come on @therealkenc ! You of all people? 

https://www.bing.com/translator/?&text=%E6%88%96%E8%80%85%E5%9C%A8%E5%AE%98%E8%AF%9D%E4%B8%AD%E8%AF%B4%E8%AF%9D%EF%BC%8C%E6%89%80%E4%BB%A5%E4%BB%96%E4%BB%AC%E4%B8%8D%E7%9F%A5%E9%81%93&from=zh-CHT&to=en

**Comment by Brandon-Xu** [comment]
Give up...

**Comment by DDoSolitary** [comment]
@Brandon-Xu Try turning off your Windows Firewall and your antivirus software completely?

**Comment by Brandon-Xu** [comment]
@DDoSolitary 全部都关掉，还有添加准许通过的端口都试过，都不行，我已经放弃了 ㄟ( ▔, ▔ )ㄏ

**Comment by DDoSolitary** [comment]
@Brandon-Xu 嘛，走好。。讲道理就目前来说WSL跑服务器相关功能还是不太合适啊。。毕竟不能后台进程。。

**Comment by Brandon-Xu** [comment]
@DDoSolitary 嗯，但是额外开个虚拟机么有感觉浪费资源，蓝瘦，我只是想搭个速度快一点的家庭文件夹共享而已，想用ssh挂载成磁盘的方式，现在只能凑合用smb了，慢的丫皮。

**Comment by nanhuayu** [comment]
连上倒是能连上，但是过好久才反应过来，速度有点慢。。。
话说你是1703版的吗？

**Comment by Brandon-Xu** [comment]
@nanhuayu 是的呀

**Comment by nanhuayu** [comment]
@Brandon-Xu 之前的版本升级到Ubuntu 16.04管理员权限好像还可以用，这个版本好像延迟很严重。。。并不知道原因。。。很快秋季red stone 3出来了，希望能好用一点😉

**Comment by Brandon-Xu** [comment]
@nanhuayu 我已经 give up 了，烦死了 ㄟ( ▔, ▔ )ㄏ，已经过了喜欢瞎J8折腾的年纪

**Comment by nanhuayu** [comment]
看这个网页还是蛮有希望的，虽然没有修复的bug还是少折腾。。。https://msdn.microsoft.com/zh-cn/commandline/wsl/release_notes

**Comment by Brandon-Xu** [comment]
@nanhuayu 我的家庭云盘计划就指望这个了呀！！！(┬＿┬)

**Comment by nanhuayu** [comment]
对了，你的电脑在升级之后是否有过重置所有文件的操作？
升级之后会造成很多驱动无法正常工作。。。
我的ssh虽然缓慢，但确实能够使用。
而且也有人有过同样经历。。。
https://github.com/Microsoft/BashOnWindows/issues/1554

![image](https://user-images.githubusercontent.com/18118017/30513136-a77f6186-9b30-11e7-9edd-5e8f93abd013.png)

**Comment by Brandon-Xu** [comment]
@nanhuayu 没有，我电脑自己做了很多设置的（洁癖），重置了又一大堆东西要重新设置，这个#issue我那时候看过，卸了tcp还是不行，哎，然后就放弃了，要我重置是不可能的，这辈子不想再把软件一个个安装一遍……

**Comment by suds123** [comment]
I reset-ed windows, at the same time upgraded to Fall Creators and it works now!

on bash:
$ nc -l 127.0.0.1 4444

on powershell:

netstat -a -n -q | findstr "4444"
TCP 127.0.0.1:4444 0.0.0.0:0 LISTENING

**Comment by therealkenc** [comment]
> I reset-ed windows, at the same time upgraded to Fall Creators and it works now!

Let's call this TDI filter driver grief per #1554 ([message](https://github.com/Microsoft/WSL/issues/1554#issuecomment-340530833)).

**Comment by jim168chang** [comment]
@Brandon-Xu 

I have an alternative solution for your reference.

I got this same issue on my PC yesterday, and could not find any solution for about 24 hours.

Then I realized that "git bash" on Windows has an "sshd" in it, so I tried to copy those 8 key files (/etc/ssh/ssh_host*) from WSL to /etc/ssh directory of "git bash", and then execute "/usr/bin/sshd" on "git bash". Now this sshd can got 22 port (or 2222 port if you set it in /etc/ssh/sshd_config), and I can ssh to my PC from my Mac laptop, and even scp files from/to my PC.

Btw, you can get git client for Windows from https://git-scm.com/ . After install it, you will get a "git bash".

Enjoy!
Jim

**Comment by xenonz95** [comment]
虽然不知道你的问题到底是啥样的，但是建议你删除各种游戏加速器和TGP（腾讯的那个）以及TGP的新版本WEGAME

**Comment by 1-riverfish** [comment]
I have the same problem,so what's the solution?一点法子么的

**Comment by adamvm** [comment]
Is there a solution to use native sshd without doing sudo service ssh --full-restart before connection?
I use binding to port 2200. After a restart with mentioned command connection works right.
