### ISSUE TITLE
SSH not working anymore

### ISSUE THREAD

**Issue by codeninja55** [Microsoft/WSL#2377]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Attempted to ssh connect to multiple devices inside the network such as router and Ubuntu server. I know all the ports and hosts are correct as I can connect to them from another Linux laptop and have previously connected to them with the the Bash on Windows system a few days ago. 

Receiving these responses after attempting to connect to 3 different devices:
`ssh: connect to host 192.168.x.x port xxxx: Permission denied`
`ssh: connect to host 192.168.x.x port xx: Permission denied`
`ssh: connect to host 192.168.x.x port xxxx: Permission denied`

Note: x's added 

* What's wrong / what should be happening instead:
Should be connecting with devices with ssh tunnel.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

open("/home/codeninja/.ssh/config", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/etc/ssh/ssh_config", O_RDONLY)   = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1756, ...}) = 0
read(3, "\n# This is the ssh client system"..., 512) = 512
read(3, "defaults at the end.\n\n# Site-wid"..., 512) = 512
read(3, "   CheckHostIP yes\n#   AddressFa"..., 512) = 512
read(3, "itLocalCommand no\n#   VisualHost"..., 512) = 220
read(3, "", 512)                        = 0
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
poll([{fd=3, events=POLLIN}], 1, 10)    = 1 ([{fd=3, revents=POLLIN}])
read(3, "\310\2547J\314D?b\\\276\17;\354r\355)NV\332\214!\235\353\375\263\10\34\345\352\34$:", 32) = 32
close(3)                                = 0
getuid()                                = 1000
time(NULL)                              = 1501260686
uname({sysname="Linux", nodename="CN55-SurfaceBk", ...}) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
gettimeofday({1501260686, 378294}, NULL) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(xxxx), sin_addr=inet_addr("192.168.x.x")}, 16) = -1 EACCES (Permission denied)
close(3)                                = 0
write(2, "ssh: connect to host 192.168.x.x"..., 63ssh: connect to host 192.168.x.x port xxxx: Permission denied
) = 63
exit_group(255)                         = ?
+++ exited with 255 +++

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Line117** [comment]
/etc/ssh/sshd_config
```
ListenAddress 127.0.0.1
Port 22
RSAAuthentication yes
PubkeyAuthentication yes
#AuthorizedKeysFile %h/.ssh/authorized_keys #<-/home/YourName/.ssh
![wsl_ssh_1](https://user-images.githubusercontent.com/22454101/28732086-3fe5bc28-73df-11e7-8ab5-21de119e7ef8.png)
![wsl_ssh_2](https://user-images.githubusercontent.com/22454101/28732087-3fe68c98-73df-11e7-8c6d-7c7317d6f27e.png)
![wsl_ssh_3](https://user-images.githubusercontent.com/22454101/28732089-3feaa8be-73df-11e7-898f-0fd114522a67.png)
![wsl_ssh_4](https://user-images.githubusercontent.com/22454101/28732088-3fea7db2-73df-11e7-8334-48bf46f364d8.png)




```
service ssh restart

**Comment by therealkenc** [comment]
Fire up [`PuTTY`](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) on Windows on the same machine and see if that connects. `ssh` works on 10.0.15063, as far as it goes. Murder would have been cried three months ago if it didn't. If `PuTTY` works but WSL doesn't we can start speculating on other causes.

**Comment by codeninja55** [comment]
@therealkenc, that's the first thing I tried and PuTTY works fine.

**Comment by therealkenc** [comment]
Someone more in the Bitdefender loop will have to jump in, but my understanding is that is still a No Fly Zone. #2360, #475, and many friends. It sounds like you had it running once, because you said "anymore". But unfortunately this isn't a single variable fail due to an upgrade (at least not the upgrade alone).

**Comment by therealkenc** [comment]
Duping into the bitdefender woe threads #2377 #2360 #475.
