### ISSUE TITLE
Support for Darling project in WSL (ability to run Mac apps on Linux)

### ISSUE THREAD

**Issue by oscarbg** [microsoft/WSL#2385]
Hi,
in my try to compile iOS Metal apps from Windows (I use http://www.pmbaty.com/iosbuildenv/ that supports iOS compilation on Windows for example OpenGL apps) I see that for Linux we have:
https://github.com/darlinghq

which can run Metal shader compilers (macos command line binaries) on Linux 
(see for success: https://github.com/darlinghq/darling/issues/326)
so can support ios Metal apps compilation (http://www.pmbaty.com/iosbuildenv provides Linux support also)..

so I asked Darling developers WSL support and pointed me to:
https://github.com/darlinghq/darling/issues/260

they say:

As of now, it's impossible to run Darling in WSL for various reasons, the two most important ones being:
1)Darling needs to load its own kernel module. Since there's no Linux kernel in WSL, it's impossible to use our module there. To make it work, the functionality would need to be reimplemented in some other way.

2)We make use of various features that WSL does not support, such as mount namespaces (last time I checked, WSL didn't have any support for mounting anything, let alone namespacing that).

From:
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes
seems mount namespaces is implemented now..

how can they workaround "kernel module" support..

would be nice if Microsoft devs explore Darling Project support under WSL so make command line binary macos apps runnable on Windows via Darling+WSL..

thanks..

**Comment by fpqc** [comment]
I commented over there the difficulties, but as long as it relies on a module, it's not going to be possible _for now_.  We'll see in the future.

**Comment by therealkenc** [comment]
Depends a lot on the nature of the kernel module and what functionality it provides; contrast with say WINE (which is the spiritual reverse of Cygwin). You can do a Metal compiler on Linux just fine. What you would do with the result is another matter. The request is not dissimilar to #1783.

**Comment by FIREFOXCYBER** [comment]
Since WSL2 early preview released today, Can anyone confirm if it works with WSL2?

**Comment by niutech** [comment]
Yes, Darling seems to [work in WSL 2](https://github.com/darlinghq/darling/issues/260#issuecomment-530184521).

**Comment by therealkenc** [comment]
Thanks. This one was submitted before loading kernel modules was in the cards, and back then probably should have been punted user voice or closed tag 'discussion'. Since it is still open we'll chalk this fixed-in-wsl2. 

If there are remaining gaps in the scenario (and I am sure there are) they _probably_ wouldn't fall into the WSL actionable sphere. Once you are compiling your own kernel and/or loading modules, that is pretty off road. But if something comes up feel free as always to open a new issue.
