### ISSUE TITLE
Reprise License Manager (rlm) client licensing library does not work with floating license server

### ISSUE THREAD

**Issue by wkbrd** [Microsoft/WSL#2386]
* Your Windows build number:  10.0.15063 (15063.332) and Insider build 16251.0

* What you're doing and what's happening:  

Reprise License Manager (RLM) licensing tool does not work for accessing a network license server.  As such, products that are developed (or being developed) against the RLM library cannot run with a floating license configuration.  Some products are only available in a floating capacity and therefore cannot be used due to this issue.

1. Downloaded RLM toolkit from http://www.reprisesoftware.com.
2. Installed organization's RLM license keys.
3. Compiled source code.
4. Set RLM_LICENSE variable to point to a running RLM server.
5. Run ./rlmclient
6. See the following error message:

```
Error checking out rlmclient license
Communications error with license server (-17)
Read error from network (-105)
```

* What's wrong / what should be happening instead:

```
Error checking out rlmclient license
License server does not support this product (-18)
```

(This is expected since the server does not have a license configured for the rlmclient).

**Comment by wkbrd** [comment]
This problem was shared with the Reprise Software team.  The ticket has since been closed.  Please contact me for more info or for me to run any other diagnostic tools.

**Comment by wkbrd** [comment]
A full strace of the rlm test client "rlmclient" is attached.  Please let us know if you need further information to troubleshoot.

[rlmclient.strace.log.zip](https://github.com/Microsoft/BashOnWindows/files/1257881/rlmclient.strace.log.zip)

**Comment by sunilmut** [comment]
I am submitting a fix for this. It should soon hit insider builds.

**Comment by therealkenc** [comment]
No indication here what was broken or what was fixed, but whatever it was, it is fixedinsiders now since 14 Sep 2017 was after Fall Creators. Possibly something to do with select() on ipv6, shrug.
```
select(16384, [3], NULL, NULL, {5, 0})  = -1 EINVAL (Invalid argument)
```
