### ISSUE TITLE
Operation not permitted when file in use in WSL

### ISSUE THREAD

**Issue by alanzanattadev** [Microsoft/WSL#2401]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
yarn run storybook (front-end javascript development) or run anything that uses the filesystem (unit tests in watch mode, server, anything).

* What's wrong / what should be happening instead:
If you try to replace files, for example with an install of new version of a library you're using (and which is used by the program currently using the filesystem), it will result in a Operation Not permitted. You have to close the program, rerun the update of the files, and rerun the program.

This limit is not present if the tool (storybook, jest) is launched from powershell. It's only happening when using WSL.

It would be great if it was not blocking the update, it's not the case on Powershell and Linux, so it shouldn't be the case on WSL.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\alanz\\Documents\\Veyo\\veyo-react-fronten
d\\websites\\recare\\app\\node_modules\\.bin\\start-storybook'".

(from yarn upgrade library).

**Comment by therealkenc** [comment]
No `strace` provided, but on a hunch: Is `start-storybook` a file or a directory? If it is a directory you are probably looking at perennial #1529,  #2243 (because `EPERM` on `unlink`). If it is a file then post a [gist](https://gist.github.com/) of `yarn.strace` from the following:
```
$ strace -ff yarn run storybook 2> yarn.strace
```
Or better yet post the `strace` either way....

**Comment by alanzanattadev** [comment]
I've tried, but storybook can't be used with strace, it's becoming too slow for the webpage to load and it's preventing it from accessing to the point where it "requires" files. How can I help without doing this command ? I've encountered the issue also by doing a git stash when files being stashed are used by storybook. So it's a file issue, not folders apparently. The worst part is the file is removed when there is this issue.

**Comment by therealkenc** [comment]
Repro steps and someone might pick it up.

**Comment by alanzanattadev** [comment]
The repro is super simple, that's a good thing:
  - Get any linux tool that watch the file system (Jest in watch mode for testing javascript, a webpack-dev-server, anything that watch for files to change)
  - launch it
  - create a file BEING USED by the tool, for example a unit test file for Jest.
  - git init
  - git stash
  - It will throw an error saying permission denied, because the file is in use. If you stop the watching tool, you can git stash. Sometimes the file is even deleted for some reason.

**Comment by therealkenc** [comment]
Ah. #1956, #2086
