### ISSUE TITLE
Error: 0x8007008e when launching app downloaded from store

### ISSUE THREAD

**Issue by canonical-cgregan** [Microsoft/WSL#2402]
Your Windows build number: 10.0.16257.1

* Description:
After installing the latest store version of the Ubuntu App it fails to launch.

* What's wrong / what should be happening instead:
Installation Failed!
Error: 0x8007008e

**Comment by benhillis** [comment]
That is a bizarre error code:
`Error code: (HRESULT) 0x8007008e (2147942542) - The system cannot perform a JOIN or SUBST at this time.`

Could you collect logs while trying to launch the app?
https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by canonical-cgregan** [comment]
Strange...those logs came out as empty 8k files. I'm sifting through the Event Viewer now to see if anything jumps out.

**Comment by benhillis** [comment]
@canonical-cgregan - Seems like something is falling over before it gets to our component yet.  Looking at this a bit more 0x8007008e maps to ERROR_BUSY_DRIVE.

**Comment by benhillis** [comment]
Adding @zadjii-msft and @bitcrazed to see if they've ever seen this error before.

**Comment by canonical-cgregan** [comment]
Busy drive..that is interesting...this is a Virtualbox install.

**Comment by canonical-cgregan** [comment]
Found this in logs:

Failed with 0x490 modifying AppModel Runtime status for package CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc for user DESKTOP-GQQI2GV\cgregan (current status = 0x0, desired status = 0x20).

**Comment by purplefeetguy** [comment]
I am also getting this error as of today, right after I downloaded the store based ubuntu install to replace my older, command line based install. My previous install worked fine for weeks. Then I decided to use the Windows Store app/install. The install failed, it hung and after over an hour I killed the install and tried again. I have rebooted, removed the feature, rebooted, added the feature, rebooted, Nothing. When I try to run "Ubuntu" from the Start menu...

Error: 0x80070040

When I try to uninstall from the command line:

C:\Users\jdcasthg\Development
> lxrun /uninstall /full
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
The Windows Subsystem for Linux has an install or uninstall operation pending.
C:\Users\jdcasthg\Development
>


really would like to keep working with this, but I don't want to have to reinstall windows.

**Comment by purplefeetguy** [comment]
Funny, minutes after I write this, I tried a command line based install and it seems to be working...

**Comment by purplefeetguy** [comment]
Looks like removing and adding the WSL feature 2 times did the trick. I seem to be back in business.

**Comment by kensel** [comment]
Not sure if it is the same issue but I also had the old wsl before installing from the store and recive the same error when trying to run bash.exe from powershell\cmd and the start menu button "Bash on Ubuntu on Windows".  I found that if I start bash from the Microsoft Store or the Ubuntu start menu item that bash starts without issue.

I have attached 2 zip with the lxcore tool one with bash in cmd and the other using the Ubuntu start button.
[lxcore_bash.zip](https://github.com/Microsoft/WSL/files/1660142/lxcore_bash.zip)
[lxcore_Ubuntu.zip](https://github.com/Microsoft/WSL/files/1660157/lxcore_Ubuntu.zip)

It might be that more clean up needs to occur when installing the windows store app.

**Comment by benhillis** [comment]
@kensel - I took a look at your trace and... I'm rather confused.  Somehow your init binary is hitting an exception while launching.  Could you provide me with the output of this windows command:

`wslconfig.exe /list /all`

**Comment by kensel** [comment]
@benhillis 
The output is as follows:

C:\WINDOWS\system32> wslconfig.exe /list /all
Windows Subsystem for Linux Distributions:
Legacy (Default)
Ubuntu
C:\WINDOWS\system32>

**Comment by benhillis** [comment]
@kensel - Thanks, that is what I was expecting to see.  As I mentioned above it looks like your legacy distro has been corrupted somehow.  I suggest uninstalling it:

`wslconfig.exe /unregister Legacy`

**Comment by kensel** [comment]
@benhillis after executing your command from an Administrative PowerShell bash now works as expected.

Thank you, hopefully this helps someone else also.
