### ISSUE TITLE
ps -ef segfaults after weird Java-related slowdown

### ISSUE THREAD

**Issue by pickypg** [Microsoft/WSL#2403]
This issue presented itself after my monitors were sleeping (Windows is configured to not sleep, but to allow the monitors to sleep). When I sat down to start working again, it took awhile for the monitors to wake and it was because the CPUs (4 physical / 8 logical cores) were pinned by three Java processes that I was running via WSL (3 separate Elasticsearch instances). All three of the instances were eating up about a third of the processors by percentage, which was starving the rest of my PC, which is extremely abnormal especially since they were mostly idle.

While killing those instances, they became unresponsive in their own shutdown process while trying to shutdown the co-process that they startup. This seems related to the problem that I have noticed since then, `ps -ef` seg faults every time:

```
$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Sep26 ?        00:00:00 /init
pickypg   6423     1  0 Sep26 tty2     00:00:00 /bin/bash
pickypg  13009     1  0 Sep27 tty3     00:00:00 /bin/bash
pickypg  17272     1  0 Sep28 tty4     00:00:00 /bin/bash
pickypg  19903     1  0 Sep28 tty5     00:00:00 /bin/bash
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
pickypg   9458     1  0ps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

When waiting for the instances to stop themselves, I checked `ps -ef` to see what was running (to see if the co-process was already dead):

This is what it looked like

```
^C[2017-08-08T16:20:40,856][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
[2017-08-08T16:20:42,346][INFO ][o.e.n.Node               ] [node1] stopping ...
Killed
```

This is what it should look like (note: that was from Windows at the same time and it shutdown cleanly -- I just noticed that the timestamps were 4 hours apart even though both should be in UTC):

```
[2017-08-08T12:20:56,263][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
[2017-08-08T12:21:08,450][INFO ][o.e.n.Node               ] [node1] stopped
[2017-08-08T12:21:08,787][INFO ][o.e.n.Node               ] [node1] closing ...
[2017-08-08T12:21:10,352][INFO ][o.e.n.Node               ] [node1] closed
```

```
$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Sep26 ?        00:00:00 /init
pickypg      2     1  0 Sep26 tty1     00:00:01 /bin/bash
pickypg   6423     1  0 Sep26 tty2     00:00:00 /bin/bash
pickypg  12693     2  0 Sep27 tty1     15:13:28 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiating
pickypg  13009     1  0 Sep27 tty3     00:00:00 /bin/bash
pickypg  13021 13009  0 Sep27 tty3     09:28:55 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiating
pickypg  17272     1  0 Sep28 tty4     00:00:00 /bin/bash
pickypg  18514  6423  0 Sep28 tty2     10:13:18 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiating
pickypg  19903     1  0 Sep28 tty5     00:00:00 /bin/bash
pickypg  19916 19903  0 Sep28 tty5     8-07:19:33 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiati
pickypg  19977 19916  0 Sep28 tty5     00:00:00 /mnt/c/Users/pickypg/Downloads/es-7/plugins/x-pack/platform/linux-x86_64/bin/controller
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
pickypg   9426 17272  0ps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

The first thing I noticed was the `8-07:19:33` in the `TIME` column. It also was missing the other co-processes (the `controller` listed once should be listed by the other ones). It's possible that they _were_ killed by Elasticsearch when I asked Elasticsearch to stop, but it should have then shutdown itself (possibly pointing to Java being the culprit here).

After waiting a minute, my machine was still unusable due to 99% CPU usage, so I `kill -9`ed each Java process. Once they were all killed, CPU usage returned to normal. Interestingly, each dying Java process' CPU usage was then consumed by the other Java processes.

I have not restarted my computer yet, but now I cannot start Elasticsearch via Bash. It simply does not seem to be able to start Java since the issue happened (I _assume_ a reboot will fix this). Even a simple Java command like

```
$ java -version
```

does not print anything, nor does it exit. `ps -ef` is still broken as shown initially in this issue. Exiting bash and reentering it does not seem to make any improvement.

---------------------

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

C:\Users\pickypg>ver

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

(Described above)

* What's wrong / what should be happening instead:

Bash is in a corrupted state.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

```
$ strace -o strace.txt -ff ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Sep26 ?        00:00:00 /init
pickypg   6423     1  0 Sep26 tty2     00:00:00 /bin/bash
pickypg  13009     1  0 Sep27 tty3     00:00:00 /bin/bash
pickypg  19903     1  0 Sep28 tty5     00:00:00 /bin/bash
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
pickypg   9458     1  0ps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

[strace.txt](https://github.com/Microsoft/BashOnWindows/files/1209076/strace.txt)

`ps` does not complain about seg faulting.

I decided to also run `strace` against `java -version`. It provided two separate files:

```
$ strace -o strace.txt -ff java -version
^C
```

[strace.txt.9541.txt](https://github.com/Microsoft/BashOnWindows/files/1209113/strace.txt.9541.txt)
[strace.txt.9542.txt](https://github.com/Microsoft/BashOnWindows/files/1209112/strace.txt.9542.txt)

**Comment by pickypg** [comment]
It's worth noting that it did _not_ require a reboot. Simply exiting all running WSL sessions and then reopening them got it back working.

**Comment by marc2982** [comment]
I just hit this or at least something similar. My symptom was some git commands were hanging, so I ran "ps aux" to see what was running and it segfaulted. Closing all bash shells resolved the problem but unfortunately wiped any helpful output.

**Comment by benhillis** [comment]
I suspect this is the same issue as #3252, fix will be in an Insiders build soon.
