### ISSUE TITLE
0x8007000e when opening Ubuntu app without WSL feature installed 

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/WSL#2407]
* Your Windows build number:  16257

* What you're doing and what's happening:  Installing and running Ubuntu app from Windows Store produces error 0x8007000e after "Installing..." message on CLI window.

* What's wrong / what should be happening instead: 0x8007000e message is not human readable, it should say "WSL is not installed, please install it first before running Ubuntu" or something.

**Comment by benhillis** [comment]
Are you certain that the WSL feature is not installed?  That error message has to do with running out of disk space:

0x8007000e - Not enough storage is available to complete this operation.

**Comment by benhillis** [comment]
This has been fixed.

**Comment by hmartinez82** [comment]
It's back :( 
![image](https://user-images.githubusercontent.com/1100440/82294428-21c87080-997c-11ea-9a72-db7d5af36723.png)
