### ISSUE TITLE
GetKeyboardLayout is not updated during a console session

### ISSUE THREAD

**Issue by matial** [Microsoft/WSL#2418]
* Your Windows build number:  version 10.0.14393

* Calling GetKeyboardLayout(0) periodically within a console application returns the handle of the keyboard layout active when starting the console. If the keyboard layout is changed while the console app is running, subsequent calls to GetKeyboardLayout do not reflect the new active layout.

* What's wrong / what should be happening instead: GetKeyboardLayout should return the handle of the last activated keyboard layout.

**Comment by sunilmut** [comment]
@matial - Thanks for your post. Is this a WSL/bash on Windows specific issue? Looks like a concern with the generic console API.

**Comment by matial** [comment]
@sunilmut - Yes it is a generic console API problem.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#83
