### ISSUE TITLE
NPM Install node_modules Error(s) from package.json

### ISSUE THREAD

**Issue by nhterry** [Microsoft/WSL#2419]
* Your Windows build number:  Microsoft Windows [Version 10.0.16257.1]

* What you're doing and what's happening:  `npm install` or `sudo npm install`

* What's wrong / what should be happening instead: 

I'm having a hard time installing the node_modules on a project. A '.staging' dir is being created with some modules to be installed and then seems to be running into an error not being able to unlink or delete the directory and hangs. I have the same project on my Mac and npm install seems to be working fine. I've tried manually installing each module, as well as deleting the '.staging' directory and continuing, but nothing seems to be working. I mainly get the unlink errors, but have also received `npm ERR! ENOTDIR: not a directory, lstat....` and `npm ERR! EEXIST: file already exists, mkdir....` when trying to install individual modules.

```
username@DESKTOP-3CO53BV:/mnt/c/Users/username/project$ sudo npm install

npm ERR! path /mnt/c/Users/username/project/node_modules/.staging/ast-types-283461ee/def
npm ERR! code EINVAL
npm ERR! errno -22
npm ERR! syscall unlink
npm ERR! EINVAL: invalid argument, unlink '/mnt/c/username/project/node_modules/.staging/ast-types-283461ee/def'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2017-08-14T09_51_33_514Z-debug.log
```
When I delete the '.staging' dir and try the install again or manually install a module, often the unlink error then has a problem with a different module.

The contents of the end of the debug file:
2017-08-14T09_51_33_514Z-debug.log
```
16955 verbose correctMkdir /home/username/.npm/_locks correctMkdir not in flight; initializing
16956 verbose lock using /home/username/.npm/_locks/staging-a05b3eeada678bcc.lock for /mnt/c/Users/username/project/node_modules/.staging
16957 verbose unlock done using /home/username/.npm/_locks/staging-a05b3eeada678bcc.lock for /mnt/c/Users/username/project/node_modules/.staging
16958 warn graphiql@0.5.0 requires a peer of react@^0.14.0 but none was installed.
16959 warn graphiql@0.5.0 requires a peer of react-dom@^0.14.0 but none was installed.
16960 warn react-addons-perf@15.4.2 requires a peer of react-dom@^15.4.2 but none was installed.
16961 warn react-addons-test-utils@15.4.2 requires a peer of react-dom@^15.4.2 but none was installed.
16962 verbose stack Error: EINVAL: invalid argument, unlink '/mnt/c/Users/username/project/node_modules/.staging/ast-types-283461ee/def'
16963 verbose cwd /mnt/c/Users/username/project
16964 verbose Linux 4.4.0-43-Microsoft
16965 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
16966 verbose node v8.3.0
16967 verbose npm  v5.3.0
16968 error path /mnt/c/Users/username/project/node_modules/.staging/ast-types-283461ee/def
16969 error code EINVAL
16970 error errno -22
16971 error syscall unlink
16972 error EINVAL: invalid argument, unlink '/mnt/c/Users/username/project/node_modules/.staging/ast-types-283461ee/def'
16973 verbose exit [ -22, true ]
```

I have also tried upgrading and downgrading node and npm with nvm.

Thanks for any help! :-D

**Comment by nhterry** [comment]
I just rolled back Windows to a previous Build and everything seems to work again. It looks like an issue with the current build.

I also was having issues with Git commands.

**Comment by heldchen** [comment]
it's issue #2392 - hopefully the next build contains the fix.

**Comment by sidrakshe28** [comment]
I'm  getting this error .can someone help me with this ?
C:\Users\Admin pc>npx create-react-app delish
npm ERR! code EINVAL
npm ERR! syscall mkdir
npm ERR! path C:\Users\Admin pc\.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global\_cacache\tmp
npm ERR! errno -4071
npm ERR! EINVAL: invalid argument, mkdir 'C:\Users\Admin pc\.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global\_cacache\tmp'

**Comment by Biswa96** [comment]
Try to move the project to WSL user's home folder aka. `~`.

**Comment by gajanannagare** [comment]
> I'm getting this error .can someone help me with this ?
> C:\Users\Admin pc>npx create-react-app delish
> npm ERR! code EINVAL
> npm ERR! syscall mkdir
> npm ERR! path C:\Users\Admin pc.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global_cacache\tmp npm ERR! errno -4071 npm ERR! EINVAL: invalid argument, mkdir 'C:\Users\Admin pc.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global_cacache\tmp'

I am having same issue.
