### ISSUE TITLE
Running ngrok.exe from WSL hangs

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/WSL#2428]
Windows build number:  15063.540

I have the Windows version of [ngrok](https://ngrok.io) stored in a folder in DrvFS.

When I run ngrok.exe in Windows as `ngrok.exe http 3000`, it instantly connects and displays the status.
When I run it in WSL, it appears to hang and do nothing. (Ctrl+C will go back to bash but not close ngrok.exe, but that's probably due to #1614.) Running only `ngrok.exe` which just outputs the usage help works fine.

**Comment by benhillis** [comment]
Thanks for reporting this.  It looks like ngrok doesn't handle redirected output (when the output of the program is a file or a pipe).  We have some plans to make our tty / pty file descriptors behave like Windows console handles in the future.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#82
