### ISSUE TITLE
Issues with QT Paint Device and the Platform plugin.

### ISSUE THREAD

**Issue by kenshen112** [microsoft/WSL#2429]
Window's Version: 16257
OS: Open Suse

When I try to use QT apps I sometimes get Errors related to the QT paint device. As well a subsequently related error is error can't load Platform Plugin. 
Could not find any platform plugin - This occurs with kwin_wayland, but occurs with other QT apps as well 

The Strace: https://gist.github.com/kenshen112/86bf48fa26ca7aa8028b1e3d4bc7db39#file-kwin-strace

**Comment by therealkenc** [comment]
Link a [gist](https://gist.github.com/). But reading the tea leaves above, [KGlobalAccel](https://api.kde.org/frameworks/kglobalaccel/html/index.html) is probably looking for a raw keyboard device that doesn't exist (guess). EWONTWORK. Way forward would be to turn it off, if there is such a thing in KDE.

**Comment by kenshen112** [comment]
@therealkenc that was because I hadn't installed plasma session5. I have updated the strace

**Comment by therealkenc** [comment]
That weird. The `strace` isn't showing path names:
```
[pid    38] open(0x1eff718, O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    38] stat(0x1eff648, {...})      = 0
```
Haven't seen that before. 

Often those open/access/stat fails are by design; files get looked up, don't exist, and then the program looks for another (think $PATH walking for example). The ones closer to the bottom, like line 2300 onward (pid 88) are probably fatal. I just can't tell you _what_ it can't find because the path is missing. There is also an `ENOSYS` in there, but that isn't your problem.

I'd be mildly (but only very mildly) curious if this works in a remote X session with Real SUSE, given the nature of KGlobalAccel. Path forward would be to post repro steps and maybe someone will bite.

**Comment by therealkenc** [comment]
Working under the assumption that kernel developers are going to look up how to install "plasmasession5" is one way to go I guess. It could happen.

**Comment by therealkenc** [comment]
> run kwin_wayland --drm --windowed

That won't fly because there is no DRM in WSL. You could try `--xwayland --x11-display=localhost:0` with VcXsrv and see if that gets you further. You'll probably also have to have your dbus session ducks in line.

**Comment by kenshen112** [comment]
@therealkenc https://www.reddit.com/r/bashonubuntuonwindows/comments/6ndity/z/dk96aam?context=3&sort=confidence

I made a post awhile back, that also doesn't work, xwayland won't start

**Comment by therealkenc** [comment]
```
strace -ff kwin_wayland --windowed --xwayland --x11-display=localhost:0 2> kwin_wayland.strace
```

[Assuming that's the right way to start kwin_wayland to run in a remote X session.]

**Comment by therealkenc** [comment]
```
'libQt5WaylandCompositor5' not found in package names. Trying capabilities.
No provider of 'libQt5WaylandCompositor5' found.
Resolving package dependencies...

Problem: plasma5-session-5.8.6-7.1.noarch requires plasma5-workspace >= 5.8.6, but this requirement cannot be provided
  uninstallable providers: plasma5-workspace-5.8.6-8.1.x86_64[oss_update]
 Solution 1: Following actions will be done:
  do not install plasma5-session-5.8.6-7.1.noarch
  do not install kwin-4.11.22-3.24.x86_64
 Solution 2: deinstallation of krb5-mini-1.12.5-5.2.x86_64
 Solution 3: break plasma5-session-5.8.6-7.1.noarch by ignoring some of its dependencies
```
...which is where I stopped.

**Comment by kenshen112** [comment]
https://gist.github.com/kenshen112/6d616618d1edf7cc64b6d75d3fe2f96e - xwayland strace

**Comment by therealkenc** [comment]
> run kwin_wayland --drm --windowed

There is no DRM on WSL1 (or strictly speaking, WSL2 either). This is /dupe #882.
