### ISSUE TITLE
Disabling network from WSL

### ISSUE THREAD

**Issue by dezza** [microsoft/WSL#2438]
Microsoft Windows [Version 10.0.16251.0]

Trying to disable a network adapter with
```sh
sudo ifconfig wifi0 down
sudo ifdown wifi0
```
or
```sh
sudo service networking stop
```
does not have any effect.

Rarely I need to diable network to test a network problem or develop for this

strace of ```ifconfig wifi0 down```
execve("/sbin/ifconfig", ["ifconfig", "wifi0", "down"], [/* 42 vars */]) = 0
brk(NULL)                               = 0x1e36000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fabac010000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=48386, ...}) = 0
mmap(NULL, 48386, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fabac004000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fabab830000
mprotect(0x7fabab9ef000, 2097152, PROT_NONE) = 0
mmap(0x7fababbef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7fababbef000
mmap(0x7fababbf5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fababbf5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fabac000000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fababff0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fababfe0000
arch_prctl(ARCH_SET_FS, 0x7fababff0700) = 0
mprotect(0x7fababbef000, 16384, PROT_READ) = 0
mprotect(0x60e000, 4096, PROT_READ)     = 0
mprotect(0x7fababe25000, 4096, PROT_READ) = 0
munmap(0x7fabac004000, 48386)           = 0
brk(NULL)                               = 0x1e36000
brk(0x1e57000)                          = 0x1e57000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1668976, ...}) = 0
mmap(NULL, 1668976, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fababe48000
close(3)                                = 0
uname({sysname="Linux", nodename="adrafinil", ...}) = 0
access("/proc/net", R_OK)               = 0
access("/proc/net/unix", R_OK)          = -1 ENOENT (No such file or directory)
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
access("/proc/net/if_inet6", R_OK)      = 0
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 4
access("/proc/net/ax25", R_OK)          = -1 ENOENT (No such file or directory)
access("/proc/net/nr", R_OK)            = -1 ENOENT (No such file or directory)
access("/proc/net/rose", R_OK)          = -1 ENOENT (No such file or directory)
access("/proc/net/ipx", R_OK)           = -1 ENOENT (No such file or directory)
access("/proc/net/appletalk", R_OK)     = -1 ENOENT (No such file or directory)
access("/proc/sys/net/econet", R_OK)    = -1 ENOENT (No such file or directory)
access("/proc/sys/net/ash", R_OK)       = -1 ENOENT (No such file or directory)
access("/proc/net/x25", R_OK)           = -1 ENOENT (No such file or directory)
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(5, "# Locale name alias data base.\n#"..., 512) = 512
read(5, "See the\n# GNU General Public Lic"..., 512) = 512
read(5, "nd for the time being for\n# back"..., 512) = 512
read(5, "hese lines were removed\n# becaus"..., 512) = 512
read(5, "8859-1\ngalego\t\tgl_ES.ISO-8859-1\n"..., 512) = 512
read(5, "O.ISO-8859-1 nb_NO.ISO-8859-1\nno"..., 512) = 435
read(5, "", 512)                        = 0
close(5)                                = 0
open("/usr/share/locale/en_US.UTF8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.UTF8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/net-tools.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(3, SIOCGIFFLAGS, {ifr_name="wifi0", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
ioctl(3, SIOCSIFFLAGS, {ifr_name="wifi0", ifr_flags=IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by sunilmut** [comment]
@dezza - Thanks for your post and the trace. WSL currently ignores the call (which was intentional at the time of the design) to set interface properties. Specifically, from your trace
`ioctl(3, SIOCSIFFLAGS, {ifr_name="wifi0", ifr_flags=IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0`

I have marked this as a bug to see if this can be enhanced in the future.

**Comment by dezza** [comment]
It would be nice if this could be as transparent and close to the real experience as possible.

**Comment by PieterT2000** [comment]
+1

**Comment by Resurrection2981** [comment]
+1

**Comment by mehiatt** [comment]
+1
