### ISSUE TITLE
Executable files are hidden after deduplication optimization job runs

### ISSUE THREAD

**Issue by Rainmaker52** [Microsoft/WSL#2439]
* Your Windows build number: Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:
I am not sure whether this is a valid bug, as deduplication is not really part of standard Windows 10. However, it is strange and unexpected behaviour. Therefore, I decided to report it.
It seems to be like this is not really a bug in bash, but somewhere in the "drvfs" module, or some VFS component which is used to access the NTFS filesystems.

If you have files on a deduplication NTFS volume, .exe and .dll files can no longer be viewed from bash after the deduplication Optimization phase completes.

As a screenshot says more than 1000 words; the first ls is just after I copied the files to the volume. The second ls is after running "Start-DedupJob -Type Optimization -Volume D:" and waiting for it to complete. 
![image](https://user-images.githubusercontent.com/537352/29490528-7918787a-853f-11e7-928e-d625f382c41e.png)

The UsageType for the volume is set to "Hyper-V". Deduplication module is version 2.0.0.

I have enabled deduplication using the instructions on this site: http://myitworld.azurewebsites.net/2016/10/14/enable-deduplication-windows-10/

* What's wrong / what should be happening instead:
Files should be visible.

**Comment by 0xbadfca11** [comment]
As Reparse Point handling fixes are taking place [in build 16226](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16226), it probably will fix in the next release.  
It did not happen in Windows Server Insider Preview build 16257.

**Comment by Rainmaker52** [comment]
I can confirm that this issue seems to be resolved in Windows 10 1803, build 17134.112.

Thank you for commenting
