### ISSUE TITLE
Consider improving console transparency

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/WSL#244]
As reported on [this twitter thread](https://twitter.com/w4rchylde/status/722886643951083522), consider improving how the Windows Console renders background transparency by making the background transparent, but not the text itself.

Here's an example of where the text is a little difficult to read since its slightly affected by the luminance of the background image:

![warchylde s photo](https://cloud.githubusercontent.com/assets/961950/14731058/c17aa3e8-0801-11e6-90d2-09ad23abeeb0.jpg)

**Comment by DrPizza** [comment]
Probably be nice to also be able to do the same effect as text on the Windows desktop; white on black, to ensure contrast whatever the background.

**Comment by marcogroppo** [comment]
The title bar should be opaque, too (IMHO)

**Comment by LFBernardo** [comment]
It already is Marcogroppo.

**Comment by bitcrazed** [comment]
Thanks for the ask. Closing since this is now on our feature backlog which will be dealt with when we get around to overhauling the Console rendering engine.

Closing. If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
