### ISSUE TITLE
rsync: mkstemp [...] failed: Invalid argument (22)

### ISSUE THREAD

**Issue by strarsis** [Microsoft/WSL#2441]
When running rsync in Bash on Windows/WSL I get error messages:
`rsync: mkstemp [...] failed: Invalid argument (22)`

How can I get around this issue?

**Comment by heldchen** [comment]
difficult to guess as you're not following the issue template - it's there for good reasons...

you probably have owner/group/permission problems, play around with the  `--no-owner`, `--no-group`, `--no-perms` and/or `--inplace` rsync options.

**Comment by strarsis** [comment]
````
rsync: copy "/tmp/1554799009.M827486P27253.thehost,S=26555,W=26983:2,.gao4TF" -> "example.com/info/Maildir/cur/1554799009.M827486P27253.thehost,S=26555,W=26983:2,": Invalid argument (22)
````
