### ISSUE TITLE
[Bug] Bash prompt disapper. Hostname disapper. 

### ISSUE THREAD

**Issue by Hypnoes** [microsoft/WSL#2442]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
__Microsoft Windows [Version 10.0.15063]__
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1. Set your computer name with special character (For example some emoji character, in my case 🛰).
2. Restart Computer.
3. Open bash shell.
* What's wrong / what should be happening instead:
    * It should be 

![1](https://user-images.githubusercontent.com/13956546/29522656-7f6ca826-86bc-11e7-912b-88c3f6dab304.PNG)
![2](https://user-images.githubusercontent.com/13956546/29522654-7f6b4e5e-86bc-11e7-90c3-66743b068ddb.PNG)

    * Infect it is 

![3](https://user-images.githubusercontent.com/13956546/29522655-7f6c2a7c-86bc-11e7-843b-3ff66b8e4326.PNG)
![4](https://user-images.githubusercontent.com/13956546/29522653-7f6ab304-86bc-11e7-8742-4a2e0c13a5bf.PNG)
![5](https://user-images.githubusercontent.com/13956546/29522657-7f7edbe0-86bc-11e7-9ab8-757566c7a084.PNG)

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Hypnoes** [comment]
__Rename the computer__ can let bash work correct again. 
![default](https://user-images.githubusercontent.com/13956546/29523316-3a5685a6-86bf-11e7-82a9-1a9f32346009.PNG)

I'm not sure if you treat it as a 'feature' not a 'bug'... 😆

**Comment by shevegen** [comment]
> I'm not sure if you treat it as a 'feature' not a 'bug'

This is most definitely a bug since the prompt being gone means that bash can not really work. (I actually have had this in kde konsole on windows +xming or whatever was the name, but I doubt that it was caused by the underlying code on win10).

How did you get to this bug though?

PS: Fallout fan eh? ;)

**Comment by benhillis** [comment]
Interesting, frankly I'm surprised Windows allows these types of special characters in machine names.  I've filed a bug to take a look at this but it's unlikely to meet the bar for Fall Creator's Update.

**Comment by Hypnoes** [comment]
@shevegen ~~Hello wastelander!~~
First it's easy to reproduce this bug, just go "settings -> system -> about" page and rename your computer name with emoji like 📦 . Then restart your computer.  Then open bash.exe. 
Infect by last pic we can find the problem is caused by the coding of windows. Windows using UTF-16 to encode the filename and other characters. But bash using UTF-8 by default. ~~(Search the Unicode table, you can find the \d83d\def0 represent the satellite 🛰 in utf-16 format)~~ And when the bash start, it will try to parse the prompt string, ~~(environment variable $PS1, $PS2..., you can see it by ```echo $PS1  $PS2```)~~ which usually like _user@host_ . The error occurred when it parse the hostname, it can't decode utf-16 characters, so the $PS1 eq to null, as the prompt disappear as we see. 
And if you mean how to put 🛰... emm... Acopy and paste is just ok. 😃

**Comment by therealkenc** [comment]
> frankly I'm surprised Windows allows these types of special characters

But are they actually special? [RFC3490](http://www.ietf.org/rfc/rfc3490.txt) has been around for almost 15 years. If you can't have a 🐱‍👤Ninja Cat emoji in your machine name, wouldn't that break any string with precomposed characters (Arabic, Tamil, Sweedish, whatever)? I assume it would break [Åström](https://r12a.github.io/uniview/?charlist=A%CC%8Astro%CC%88m) too.

Not that it is some showstopper. I'm just curious whether they are actually "special".

**Comment by benhillis** [comment]
@therealkenc - True, just seems like a can of worms. Clearly not something Linux supports since sethostname takes single-byte character strings: https://linux.die.net/man/2/sethostname

**Comment by therealkenc** [comment]
@benhillis - You are thinking in win32 terms. `hostname(2)` takes an opaque buffer whose glyph representation to humans is not the kernel's problem. It is a function whose purpose is to set a buffer later returned by `gethostname()`. It isn't ASCII. It doesn't even need a trailing null.

```
#include <unistd.h>
#include <stdio.h>

int main(int argc, int argv[])
{
    char hostname[] = "AÌŠstroÌˆm";
    int ret = sethostname(hostname, sizeof(hostname));
    if (ret == 0) {
        printf("hostname set\n");
    }
}
```
Then:
```
ken@zesty:~/Devel/utf8$ gcc utf8test.c -o utf8test
ken@zesty:~/Devel/utf8$ sudo ./utf8test 
hostname set
ken@zesty:~/Devel/utf8$ hostname
Åström
```
But:

w͢͢͝h͡o͢͡ ̸͢k̵͟n̴͘ǫw̸̛s͘ ̀́w͘͢ḩ̵a҉̡͢t ̧̕h́o̵r͏̵rors̡ ̶͡͠lį̶e͟͟ ̶͝in͢ ͏t̕h̷̡͟e ͟͟d̛a͜r̕͡k̢̨ ͡h̴e͏a̷̢̡rt́͏ ̴̷͠ò̵̶f̸ u̧͘ní̛͜c͢͏o̷͏d̸͢e̡͝?͞

**Comment by benhillis** [comment]
Gotta love Linux sometimes... If the argument is an opaque buffer then why not a void* instead of char*.

**Comment by therealkenc** [comment]
Because POSIX. 🙄 Many years back a bunch of people from DEC, SUN, Silicon Graphics, and Santa Cruz got together and made rules people still pay attention to for reasons I've never fully understood.

**Comment by AdFad666** [comment]
Bump.

I got hit by this bug today on 16299.192. I renamed my PC to 🚀 and my GNU/NT world ended.

I was sad.
