### ISSUE TITLE
I cannot connect anymore to my servers by ssh

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/WSL#2446]
Hello,

* Your Windows build number:  Microsoft Windows [version 10.0.15063]

* What you're doing and what's happening: 
actual windows bash:
![image](https://user-images.githubusercontent.com/331816/29658034-c3ca48ee-88b9-11e7-9c10-1b68f5a4f177.png)
with kitty/putty:
![image](https://user-images.githubusercontent.com/331816/29658040-d00a55fe-88b9-11e7-9ae5-1f2dc3091e89.png)

* What's wrong / what should be happening instead:
Since 2 days, I cannot use ssh in windows bash to connect to my servers

Thanks.

**Comment by therealkenc** [comment]
Same symptoms as #2377

**Comment by Xarkam** [comment]
Hello, 

Yes I have Bitdefender 2018. I check in my AV.
