### ISSUE TITLE
Ubuntu process freeze cause WSL to hung

### ISSUE THREAD

**Issue by adaroobi** [microsoft/WSL#2449]
Build: 10.0.15063

Any process hung on the subsystem cause the entire bash to hung.
For instance, I tried to run `wget` with an invalid resource. When I cancel `ctrl+c` it just no more responding.
I tried to close and reopen bash but it just showing blinking underscore and stays forever...

And so happens with any other process with similar circumstances and will not resolve until a Windows reboot.

**Comment by fpqc** [comment]
@adaroobi Hey, would you mind testing this in the latest Windows Insider build?  A bunch of deadlock bugs have been fixed.

**Comment by adaroobi** [comment]
@fpqc Sorry for the delay...
Unfortunately, I don't have insider build installed somewhere so I would not be able to verify.

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
