### ISSUE TITLE
Consider adding padding and line height options

### ISSUE THREAD

**Issue by antcook** [Microsoft/WSL#245]
![bash](https://cloud.githubusercontent.com/assets/4984792/14739753/a492c636-0881-11e6-9e0c-f9eacbc7d322.jpg)

I think text can sometimes be hard to read as it's nearly flush with the left edge of the window. (see red) Also text can be hard to read because it is too close together (see green).

To combat these issues and improve accessibility, a lot of terminals have padding and line height options. I think this will be a great addition and help readability for both visual impaired and non-visual impaired users alike, especially when using for long periods..

**Comment by LFBernardo** [comment]
maybe add the option to modify the visual profile like on Ubuntu itself? adjustable fonts, text size etc...

![image](https://cloud.githubusercontent.com/assets/18407412/14740182/5b392492-088d-11e6-8934-cc45d248b9e0.png)

**Comment by antcook** [comment]
I like this idea, but if this isn't feasible, some sort of config file would do trick also, kinda like how text editors do it, for example:

```
{
 "text-size": 16,
  "padding": 10,
  "line-height": 1.5
}
```

Maybe not in JSON format, but you get the idea, there are certainly multiple ways of going about implementing this.

**Comment by LFBernardo** [comment]
that could work as well, should be easy enough to create a wrapper for a conf file like that for the plebs that don't understand it as well....

**Comment by mgleadow** [comment]
On a related theme the ability to change colour palettes as per the Ubuntu terminal screenshot above would also be valuable

**Comment by bitcrazed** [comment]
Many great ideas here. Parking this in our backlog for future consideration for now.

**Comment by bitcrazed** [comment]
Thanks for your suggestions, we've taken them on-board and will incorporate into our future Console improvements.

Closing for now because 
1. This is the WSL repo and we now have a [Console issues repo](https://github.com/microsoft/console)
1. GitHub doesn't enable issues to be migrated between repo's while preserving poster's identity, etc.
