### ISSUE TITLE
Sysvipc message queues and fakeroot

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#2465]
Build 16278 

I figured I'd make an issue for this since there are no open issues mentioning it.  I know the devs are aware.

The lack of Sysvipc message queues breaks fakeroot and therefore breaks Arch's makepkg unless fakeroot is recompiled to use tcp instead of sysvipc (and without a working makepkg, this means you either have to comment out the uid check in makepkg and compile fakeroot-tcp as root or alternatively compile fakeroot-tcp on a separate machine running Linux).

**Comment by therealkenc** [comment]
Same as #2013 which was closed (likely due to the choice of issue title), just to add the ref.

**Comment by fpqc** [comment]
yep! that was the motivation

**Comment by slaadvak** [comment]
I'd be really interested in having this issue resolved, as I ran into this problem while trying to build buildroot  on Ubuntu for Windows (Windows Subsystem for Linux) 20170711 - Ubuntu 16.04 LTS:
```
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
fs/ext2/ext2.mk:45: recipe for target '/home/slaadvak/buildroot/buildroot-2017.02.5/output/images/rootfs.ext2' failed
make[1]: *** [/home/slaadvak/buildroot/buildroot-2017.02.5/output/images/rootfs.ext2] Error 1
Makefile:79: recipe for target '_all' failed
make: *** [_all] Error 2
```

**Comment by therealkenc** [comment]
There is a straightforward work-around: don't fake it. `dpkg-buildpackage -rsudo`.

**Comment by dlech** [comment]
Related: https://github.com/Microsoft/BashOnWindows/issues/1443#issuecomment-313254655

**Comment by yecril71pl** [comment]
`-rsudo` does not fly because that requires `--add-depends=sudo`, configuring transparent sudo in chroot because otherwise `sudo `does not work missing `askpass`.  It is easier to say `-rfakeroot -faked faked-tcp`, which is clumsy as can be but works with no additional preparations.  Of course, this horrible syntax is Debian’s fault, not Microsoft’s.

**Comment by Zenexer** [comment]
The command from @yecril71pl is missing a hyphen.  It should be `-r'fakeroot --faked faked-tcp'`.  Just in case anyone else runs into the same issue.

**Comment by therealkenc** [comment]
Didn't realise Ben [re-opened](https://github.com/Microsoft/WSL/issues/1443#issuecomment-313254655) #1443 per dlech. The one was filed initially because it appeared all of the sysv mqueue issues were closed at the time. Affects `fakeroot` and anything else that uses them, natch.

**Comment by WayneD** [comment]
The easiest fix at the moment is to set the tcp alternative:
sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp

That way "fakeroot" works fine without options.  I'm using Ubuntu 16.04.3 LTS (Xenial Xerus).

**Comment by teras** [comment]
So, the original bug report was about arch linux and fakeroot, the solutions here are only for Ubuntu.
Any workaround for arch linux package creation?

**Comment by dudeofawesome** [comment]
@teras If you're still having this issue on Arch, you might try these steps:

1. Build `fakeroot-tcp` from [here](http://ftp.debian.org/debian/pool/main/f/fakeroot) (latest `.orig.tar.gz`)
	1. `./bootstrap`
	1. `./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp`
	1. `make`
	1. `sudo make install`
1. Add `/opt/fakeroot/bin/` to your path
1. [Install `yay`](https://github.com/Jguer/yay#installation)
1. Install `fakeroot-tcp` from the AUR.
	```bash
	yay -Syu fakeroot-tcp
	```

**Comment by meytin1337** [comment]
> @teras If you're still having this issue on Arch, you might try these steps:
> 
> 1. Build `fakeroot-tcp` from [here](http://ftp.debian.org/debian/pool/main/f/fakeroot) (latest `.orig.tar.gz`)
>    
>    1. `./bootstrap`
>    2. `./configure — prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp`
>    3. `make`
>    4. `sudo make install`
> 2. Add `/opt/fakeroot/bin/` to your path
> 3. [Install `yay`](https://github.com/Jguer/yay#installation)
> 4. Install `fakeroot-tcp` from the AUR.
>    ```shell
>    yay -Syu fakeroot-tcp
>    ```

The solution did not work for me. The configure command gave the message `checking build system type... Invalid configuration '—': machine '—-unknown' not recognized`.
 Running `./configure` without any options fixed the command for me.

**Comment by tbkj98** [comment]
Hi @meytin1337 
The command you are using is wrong. Try

`./configure --prefix=/opt/fakeroot --libdir=/opt/fakeroot/libs --disable-static --with-ipc=tcp`

This works without any issue.

**Comment by ukaszogi** [comment]
Couldn't get it to work, i guess i'm just build different. 
Linking this cool script:

https://gist.github.com/tytydraco/df14e4f7af737e7b51ba35842f75342b
