### ISSUE TITLE
samba linux server share cannot be accessed from windows10rs3 build16273

### ISSUE THREAD

**Issue by Shivappa** [Microsoft/WSL#2472]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16273.1000.rs3_release.170819-1253
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
-Access Linux samba server (\\IPAddressOfsambaserver) with above build version with SMB2 or SMB3.
Below quoted error is thrown.
"You can't access this shared folder because your organization's security policies block unathenticated guest access. These policies help protect your PC from unsafe or malicious devices on the network."

But with SMB1 shares are accessed without issues.

* What's wrong / what should be happening instead:
It should display linux samba server shared folders.
Other info: until build16257 there was no issues.

Always reproducing from build16273 (including build16278, build16281)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Are you talking about a Samba server running on a native Linux box / VM, or WSL? I think there was no response here because it isn't clear. If you have a regression with the Windows CIFS client connecting to your Samba server, the best place to find help would be in the Samba community.
