### ISSUE TITLE
peculiar problem running same python script in two folder

### ISSUE THREAD

**Issue by simonnier** [microsoft/WSL#2473]
My Windows build number:  Microsoft Windows [版本 10.0.15063]

This is what I am doing. I am testing a python script. I found peculiar things. 

I can reproduce this, by following three steps, see picture below

https://pasteboard.co/GJbPkYf.png

I am not sure whether it is the python problem or the bash problem.

But I tried further

1.  I tried to copy this py to other folder, they all works
2. I tried to close all bash window, and enter bash again and run py in learning folder, still fail.
3. I tried to run this script in learning folder in windows cmd's python, it works

So this is really wierd. What is the problem with this folder?

**Comment by therealkenc** [comment]
You can try posting a [gist](https://gist.github.com/) of the output of `strace -ff python test.py 2> pythontest.strace`. That it works in Windows python isn't _necessarily_ weird, depending on where Windows python is picking up that missing name. But before you go the `strace` route, check out [google](https://goo.gl/X9mAbE) and see if any of those hits shed any light.

**Comment by balabi0github** [comment]
@therealkenc Thank you for quick reply. Here is the strace  https://gist.github.com/balabi0github/078dcb89b3921b63956f6015b95ec84d

**Comment by therealkenc** [comment]
If I had to guess (and it is a guess), you've something missing in your python universe. Just before the fail you've got a tonne of:
```
[pid   183] stat("/mnt/e/w/WORK/python/learning/shutil", 0x7fffce58da30) = -1 ENOENT (No such file or directory)
[pid   183] open("/mnt/e/w/WORK/python/learning/shutil.x86_64-linux-gnu.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[...etc tec]
[pid   183] open("/mnt/e/w/WORK/python/learning/shutil.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
```
Don't concentrate on the 'learning' part; there is plenty more where that came from. Python never finds what it is looking for in `/mnt/e/w/WORK`, but I bet it does on Windows. Do a search on `/mnt/e/w/WORK` in the `strace` and you can find all the examples.

So, take a look and see if those files exist, looking from the WSL side. It looks like a config issue from here, but note I am no python expert. Bonne chance.

**Comment by tdsmith** [comment]
I'm just a rando, but: the ENOENTs don't worry me; Python tries a few names for the things it imports and most of them won't exist.

If you run `/usr/bin/python2.7 -c 'import subprocess; print subprocess.__file__; import sys; print sys.path'` from the same directory, maybe that'll help diagnose from where you're getting a subprocess module that's missing that function.

**Comment by therealkenc** [comment]
This submission could not be reproduced locally (the pastebin in the OP was run against an undisclosed `test.py`). If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
