### ISSUE TITLE
running binaries through drvfs nfs mount gives intermittent 'Input/output error'

### ISSUE THREAD

**Issue by eroller** [microsoft/WSL#2480]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16251.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have mapped an NFS share (Isilon storage) to drive I:  Then on WSL Ubuntu:
sudo mkdir /mnt/i
sudo mount -t drvfs I: /mnt/i

Then I try to run dotnet installed on the mounted drive
/mnt/i/sync/software/unofficial/Isas/packages/dotnet-1.1.2/dotnet

* What's wrong / what should be happening instead:
Sometimes it works and I get the dotnet command line options as expected. However sometimes it gives error:
/mnt/i/sync/software/unofficial/Isas/packages/dotnet-1.1.2/dotnet: Input/output error

I am accessing the NFS share behind a VPN so it is not the fastest connection, but it is a stable connection. I suspect the delay is causing the intermittent behavior.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

~$ strace -o strace.txt -ff /mnt/i/sync/software/unofficial/Isas/packages/dotnet-1.1.2/dotnet
strace: exec: Input/output error
~$ cat strace.txt.120
execve("/mnt/i/sync/software/unofficial/Isas/packages/dotnet-1.1.2/dotnet", ["/mnt/i/sync/software/unofficial/"...], [/* 16 vars */]) = -1 EIO (Input/output error)
write(2, "strace: exec: Input/output error"..., 33) = 33
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by ericblade** [comment]
i thought i'd give mounting a nfs share in windows then in wsl a spin, so I did from cmd

````mount -o anon \\192.168.0.242\path\to\mount x:````
then followed it up in wsl with
````sudo mkdir -p /mnt/x
sudo mount -t drvfs X: /mnt/x
````
and the mount is successful, but attempting to read anything on it just results in "Invalid argument".  Any ideas?
