### ISSUE TITLE
Windows "touch" keyboard does not work with "password"-like input (sudo, passwd...)

### ISSUE THREAD

**Issue by PHubaut** [Microsoft/WSL#2483]
**Windows build number:  (Type `ver` at a Windows Command Prompt)**
Microsoft Windows [version 10.0.16278.1000]
WSL/Linux:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**What's happening:**
When using a Win10 tablet and the touch screen virtual keyboard, I am, as expected, able to enter bash console commands and work normally. However, when I use a command like "sudo ..." or "passwd" and system requires password-like input it fails as if input was not expected one. Below is what happened with "sudo ps" when trying to type my password:
_Using on-screen touch keyboard (password-input fails)..._
`Pierre@PierreTAB1:~$ sudo ps`
`[sudo] password for Pierre:`
`Sorry, try again.`
_Using standard physical keyboard ((password-input works)..._
`[sudo] password for Pierre:`
`  PID TTY          TIME CMD`
`   16 tty1     00:00:00 sudo`
`   17 tty1     00:00:00 ps`
`Pierre@PierreTAB1:~$`

**What's wrong / what should be happening instead:**
This is repeatable and has nothing to do with wrong user input - I expect on-screen touch keyboard work exactly like physical one. I am configured with French / French (Belgium) locale/keyboard layout but also tried with plain English / English (US) and there is no difference in behavior.
Of course, bypass is easy, just use a physical keyboard.

**Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)**
Not applicable

**Comment by benhillis** [comment]
Unfortunately I'm not able to reproduce this on a very recently build. The touch keyboard worked just fine for entering my password.  Does your machine have any interesting locale options?

**Comment by PHubaut** [comment]
I am now Windows 10 16288.1 and still get the issue.
My device is a Microsoft Surface Pro 3.
The physical keyboard is a Microsoft Surface Pro 4 Type Cover, french(Belgium) layout.
My Windows language is French, locales Belgium.
I have 4 keyboards/languages installed - see snapshots below for touch screen keyboard and physical keyboard layouts installed.
I see nothing special here but it is not, indeed a plain US English machine.
<img width="1080" alt="2017-09-20" src="https://user-images.githubusercontent.com/22426791/30663708-d5f4413a-9e4b-11e7-9135-97c5d7a345df.png">
<img width="224" alt="2017-09-20 1" src="https://user-images.githubusercontent.com/22426791/30663707-d5f3da88-9e4b-11e7-8a66-f93584098529.png">

**Comment by benhillis** [comment]
@PHubaut - Can you verify that if you type your password into notepad with onscreen keyboard and your physical keyboard that the characters are identical?

**Comment by PHubaut** [comment]
@benhillis - did it already and, strange, I can't see any difference.
Below are two lines - top is written using onscreen keyboard, bottom with physical keyboard - no diff.
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&()-_~=+\;:"?*/µ<>[]{}|°^.
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&()-_~=+\;:"?*/µ<>[]{}|°^.
Note: my password contains upper cases, lower cases, digits and ponctuation marks.

As indicated, I noticed the issue with `sudo` and `passwd` which both request user input in concealed mode. It would be interesting just to have a tiny C program that ask for two strings in concealed mode then just compare them and display result - I am not that familiar with this but will try to extract code from `sudo`, `su` or `passwd` sources and see what's happening.

**Comment by PHubaut** [comment]
@benhillis - GOT IT. There is a difference, but not at consoled bash prompt level, it really needs user input (concealed or not). The "SHIFT" key on the onscreen keyboard produces some code (displayed as "^@"). This makes the difference.

Note/bypass(for me): my password has a upper case as first character. When the onscreen keyboard is activated, it defaults to lower case. I press "SHIFT", I get the "^@" - if I now hit the "backspace" key, upper case are still engaged on the onscreen keyboard and after typing the first letter, it reverts to lower case which is fine for my current password :-).

No issue at bash command entry level, "SHIFT" key behaves normally; anyway, most commands are lower case.

**Comment by PHubaut** [comment]
Requalification of the issue -

Title should be: "**Windows onscreen "touch" keyboard generates extra codes with SHIFT and CTRL-...**"

The following `cat >test` followed by `hd test` using the onscreen touch keyboard demonstrates the issue:
```
Pierre@PierreTAB1:~$ cat >test
shift key produces 0x00 codes: ^@^@^@^@^@
ctrl- combinations also (e.g. ctrl- a, b, d, e, f): ^@^A^@^B^@^@^E^@^F
requires ctrl-c to exit.
^@^C
Pierre@PierreTAB1:~$ hd test
00000000  73 68 69 66 74 20 6b 65  79 20 70 72 6f 64 75 63  |shift key produc|
00000010  65 73 20 30 78 30 30 20  63 6f 64 65 73 3a 20 00  |es 0x00 codes: .|
00000020  00 00 00 00 0a 63 74 72  6c 2d 20 63 6f 6d 62 69  |.....ctrl- combi|
00000030  6e 61 74 69 6f 6e 73 20  61 6c 73 6f 20 28 65 2e  |nations also (e.|
00000040  67 2e 20 63 74 72 6c 2d  20 61 2c 20 62 2c 20 64  |g. ctrl- a, b, d|
00000050  2c 20 65 2c 20 66 29 3a  20 00 01 00 02 00 00 05  |, e, f): .......|
00000060  00 06 0a 72 65 71 75 69  72 65 73 20 63 74 72 6c  |...requires ctrl|
00000070  2d 63 20 74 6f 20 65 78  69 74 2e 0a              |-c to exit..|
0000007c
Pierre@PierreTAB1:~$
```

**Comment by d20chick** [comment]
I thought I was having this issue but it turns out that the password input is invisible, like, it gives me no indication it recognizes my attempt to input a password

**Comment by PHubaut** [comment]
>           I thought I was having this issue but it turns out that the password input is invisible, like, it gives me no indication it recognizes my attempt to input a password

indeed, password input is concealed.

But nevertheless, do you have any character in your password that would that would requires the SHIFT key to be used? Because this is when the problems occurs.
Problem still exists for me -
I am at version Windows 10 17134.285
Ubuntu 18.04.1 LTS
Pierre

**Comment by ns740** [comment]
agree (that this is far from critical) - but please note this problem also (adversely) affects using programs like vim and tmux with the touch keyboard.

**Comment by therealkenc** [comment]
This one went dark because it couldn't be reproduced by the devs. This was back in 2017 before the [console tracker](https://github.com/microsoft/console) was forked. Give a shout over there because whatever the problem is, it almost has to be on that side of the fence. WSL is just pulling characters off of `/dev/tty` and has no idea about the nature of the keyboard. You can confirm this by trying another terminal emulator like [`wsltty`](https://github.com/mintty/wsltty), or ssh into WSL with [`PuTTY`](https://www.putty.org/), [`ttyd`](https://tsl0922.github.io/ttyd/) or whatever. I don't rate a Surface Book to repro this, sadly. But even if I'm wrong, at least you'll have a snowballs chance over there.

**Comment by pirachute** [comment]
I found a way to make it work:

If you first press Shift, then the letter you want in caps, it doesn't work.

If you do like in a physical keyboard: Keep Shift pressed while pressing the letter in caps, then it works!

**Comment by PHubaut** [comment]
> I found a way to make it work:
> If you first press Shift, then the letter you want in caps, it doesn't work.
> If you do like in a physical keyboard: Keep Shift pressed while pressing the letter in caps, then it works!
Thanks @pirachute for the trick.
Actually, I am now on WSL version 2, Windows 10 (19045.3031) and even when I first press Shift then the letter I want (not keeping shift key pressed), it works. But I can see that the virtual keyboard is maintaining the Shift state engaged even when I do not keep the Shift key pressed. So for me, at present, it works as I expected.
