### ISSUE TITLE
try to build mplayer fail on configure required for some header file

### ISSUE THREAD

**Issue by toiiggww** [microsoft/WSL#2488]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [版本 10.0.16281.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
@DESKTOP-4CUDPAI:/mnt/d/Documents/GitHub/mplayer$ ./configure 

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

============ Checking for inet6 ============

#include <sys/types.h>
#if !defined(_WIN32)
#include <sys/socket.h>
#include <netinet/in.h>
#else
#include <ws2tcpip.h>
#endif
int main(void) { struct sockaddr_in6 six; socket(AF_INET6, SOCK_STREAM, AF_INET6); return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp -lws2_32 -lm
/tmp/mplayer-configure--5201/tmp.c: In function 'main':
/tmp/mplayer-configure--5201/tmp.c:8:38: warning: unused variable 'six' [-Wunused-variable]
 int main(void) { struct sockaddr_in6 six; socket(AF_INET6, SOCK_STREAM, AF_INET6); return 0; }
                                      ^
/usr/bin/ld: cannot find -lws2_32
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

Result is: no 
##########################################

============ Checking for gethostbyname2 ============

#define _BSD_SOURCE
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
int main(void) { gethostbyname2("", AF_INET); return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

Result is: no 
##########################################

============ Checking for SCTP ============

#include <netinet/sctp.h>
int main(void) { return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/tmp/mplayer-configure--5201/tmp.c:1:26: fatal error: netinet/sctp.h: No such file or directory
compilation terminated.

Result is: no 
##########################################

============ Checking for sys/un.h ============

#include <sys/un.h>
int main(void) { return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

Result is: no 
##########################################

============ Checking for sys/poll.h ============

#include <sys/poll.h>
int main(void) { return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

Result is: no 
##########################################

============ Checking for inttypes.h (required) ============

#include <inttypes.h>
int main(void) { return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

Result is: no 
##########################################

============ Checking for sys/bitypes.h (inttypes.h predecessor) ============

#include <sys/bitypes.h>
int main(void) { return 0; }

cc -Wundef -W -Wall -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99 -Werror-implicit-function-declaration -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ISOC99_SOURCE -I. -Iffmpeg -O2 -march=x86-64 -mtune=generic -pipe -g3 -p -fno-tree-vectorize -fno-asynchronous-unwind-tables /tmp/mplayer-configure--5201/tmp.c  -fpie -DPIC   -ffast-math -fpie -pie -lws2_32   -o /tmp/mplayer-configure--5201/tmp  -lm
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by onomatopellan** [comment]
>fatal error: netinet/sctp.h: No such file or directory

try `sudo apt-get install libsctp-dev`

>/mnt/d/Documents/GitHub/mplayer

You will have better luck if you download the mplayer sources on a LxFs folder like `/home/username/mplayer`.

**Comment by toiiggww** [comment]
sctp can skip but inttypes.h or bitypes.h

**Comment by onomatopellan** [comment]
>/usr/bin/ld: cannot find -lws2_32
Something is missing in your Mingw toolchain.

You should try another guides. I didn't have problems compiling 64bit mpv for Windows following the steps in this repo. https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by toiiggww** [comment]
the reason is as fllow :
Checking for inttypes.h (required) ... no
Checking for sys/bitypes.h (inttypes.h predecessor) ...
Error: Cannot find header either inttypes.h or bitypes.h. There is no chance for compilation to succeed.
so ....

**Comment by therealkenc** [comment]
> /tmp/mplayer-configure--5201/tmp.c:1:26: fatal error: netinet/sctp.h: No such file or directory

This error is from userspace.
