### ISSUE TITLE
can't chmod a socket created by socketpair()

### ISSUE THREAD

**Issue by cbosdo** [Microsoft/WSL#2490]
openSUSE and SLES man tool calls the `socketpair()` function instead of `pipe()`. However running such a man tool as non root fails with operation not permitted. Here is the fragment of `strace man man` showing the problem:

    socketpair(PF_LOCAL, SOCK_STREAM, 0, [4, 5]) = 0
    shutdown(5, SHUT_RD)              = 0
    fchmod(5, 0200)                   = -1 EPERM (Operation not permitted)

Running man as root works just fine. Note that the currently published openSUSE / SLES appx files have some other man pages related bugs. I can provide development builds fixing those to help reproduce this bug. 

Windows build number:  10.0.16275.1000

**Comment by benhillis** [comment]
This issue is fixed in 16288.

**Comment by felmoreno1726** [comment]
Where is the 16288 issue?

**Comment by benhillis** [comment]
16288 is a build number not an issue number.

**Comment by felmoreno1726** [comment]
Sorry to be ignorant, but what does that mean? And how can that help me fix the issue?

**Comment by benhillis** [comment]
The build number you posted in the other thread:

Microsoft Windows [Version -10.0.16278.1000]

The build this is fixed in:

Microsoft Windows [Version -10.0.16288.1000]

**Comment by sunilmut** [comment]
@felmoreno1726 - If you run the `ver` Windows command, you can see the build number that @benhillis is referring to above.
