### ISSUE TITLE
sometimes I have to invoke the command twice to register

### ISSUE THREAD

**Issue by thisguychris** [microsoft/WSL#2494]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16278.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
`$ hub clone username/repo`  (nothing happens)
`$ hub clone username/repo` (now something happens)

* clone failure:
 ![clone fail](https://monosnap.com/file/jhZjzqO0UnBlgZj3hXeqPsbVjpck16.png)

* What's wrong / what should be happening instead:
cloning should happen the first time

**Comment by thisguychris** [comment]
more observations, here as you can see, first 2 commands does nothing. And the 3rd one finally invoke the command.  This is under `~/` and not in `/mnt/`         

![have to click 3x](https://monosnap.com/file/WFkBP9mhvtaTmVfm5D7nzCxqMdJKrt.png)

**Comment by benhillis** [comment]
@thisguychris - Can we get a little bit more information about your environment?  Are you using the inbox windows console or a replacement?

**Comment by thisguychris** [comment]
what's "inbox windows console"? 🤔 

If when you say inbox, you mean built in.  I'm using Ubuntu bash, the one that get installed when I install Ubuntu from the Store.

**Comment by DancingQuanta** [comment]
Related to https://github.com/github/hub/issues/1310

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
