### ISSUE TITLE
fastdebug openjdk builds exits during startup

### ISSUE THREAD

**Issue by Maldivia** [microsoft/WSL#2498]
OpenJDK builds compiled with fastdebug fails during startup (java -version simply exits) where as the same build compiled as release starts up fine. Both versions start up correctly on Ubuntu.

Example builds can be downloaded from (tested with 2017-09-15 versions):
https://builds.shipilev.net/openjdk-valhalla-mvt-jdkN-fastdebug/
https://builds.shipilev.net/openjdk-valhalla-mvt-jdkN-release/

Perhaps related, the OpenJDK+OpenJ9 builds from AdoptOpenJDK also fails to start, but unlike the fastdebug, it hangs during startup. Build available from:
https://github.com/AdoptOpenJDK/openjdk9-openj9-releases/releases/tag/jdk-9+181

ver: `Microsoft Windows [Version 10.0.15063]`

When running the fastdebug version:
```
michael@Culprit:~$ ./jdk-10/fastdebug/bin/java -version
michael@Culprit:~$
```

Running the release version:
```
michael@Culprit:~$ ./jdk-10/bin/java -version
openjdk version "10-internal"
OpenJDK Runtime Environment (build 10-internal+0-adhoc.jenkins.openjdk-valhalla-mvt-jdkN-release)
OpenJDK 64-Bit Server VM (build 10-internal+0-adhoc.jenkins.openjdk-valhalla-mvt-jdkN-release, mixed mode)
michael@Culprit:~$
```

Running the OpenJDK+OpenJ9 version:
```
michael@Culprit:~$ ./jdk-9+181/bin/java -version
(... hangs ...)
```

strace -ff output from the above 3 commands available at:
https://gist.github.com/anonymous/a99415cea2f6554be986c4bf394688e4
Naming: 
* strace-10-fastdebug.txt.*
* strace-10-release.txt.*
* strace-j9.txt.*

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
