### ISSUE TITLE
Slow connection in apt-get

### ISSUE THREAD

**Issue by vinibudd** [Microsoft/WSL#2502]
I have 20 mega of download in the cable and the downloads of the mirrors download to 120kbps and sometimes take a lot to download

I'm from Brazil, I switched to the mirrors here
The standard mirrors were also very slow, so some problem I can not understand

My mirror
http://br.archive.ubuntu.com/

Windows 10 1703 (64bits - 15063.608)

![image](https://user-images.githubusercontent.com/24849260/30517508-26a3a484-9b38-11e7-98fd-c0e0f8e5db1e.png)

**Comment by therealkenc** [comment]
#2477

**Comment by Gabrielcarvfer** [comment]
Have the same problem, but you can use apt-metalink as a workaround.
https://github.com/tatsuhiro-t/apt-metalink

**Comment by therealkenc** [comment]
Dupe into #2477 so people experiencing `apt` slowness can share in one place.
