### ISSUE TITLE
lxrun /uninstall /full - question

### ISSUE THREAD

**Issue by Zingam** [Microsoft/WSL#2513]
This command is supposed to remove the Ubuntu image:
lxrun /uninstall /full
I ran it but I don't see that any space was freed on the drive. Where is the Ubuntu image located? How can I make sure that there are no residual files remaining on my system?

Also it is not clear if I can have just bash without installing the full Ubuntu image and use it as a alternative Windows shell. Is that possible?

**Comment by sunilmut** [comment]
@Zingam - If you installed WSL using `lxrun /install` in the first place, then all of your files should be under `%localappdata%\lxss`

**Comment by benhillis** [comment]
@Zingam - Did you install the Ubuntu app from the store?  If so the way to remove that distribution is to uninstall the store application.
