### ISSUE TITLE
Strange output of `ip route get` command

### ISSUE THREAD

**Issue by strangeman** [microsoft/WSL#2516]
* Your Windows build number:  Version 10.0.15063

* What you're doing and what's happening:  
  1. Launch BASH
  1. Run command `ip -4 route get 8.8.8.8`
  1. Get result:
```
none 8.8.8.8 via 192.168.1.1 dev eth1  proto none  src 192.168.1.172
```

* What's wrong / what should be happening instead:
On 'normal' Ubuntu, command `ip -4 route get 8.8.8.8` get the following output (without strange `none` words):
```
8.8.8.8 via 192.168.0.1 dev wlan0 src 192.168.0.102 
    cache
```
That behavior of `ip route` in WSL causes bug in Ansible: https://github.com/ansible/ansible/issues/30603

**Comment by therealkenc** [comment]
Might try Insiders, or wait for Fall Update on October 17th. Seems to be okay on 16294.

**Comment by heldchen** [comment]
are you sure, @therealkenc? getting similar output as @strangeman in 16296 
`none 8.8.8.8 via 192.168.1.1 dev wifi0 proto none src 192.168.1.229`

**Comment by therealkenc** [comment]
Yes you are both right. I must have pasted into the wrong window or something 🙄. Total brain fart; please disregard my noise.

**Comment by sunilmut** [comment]
@strangeman - Thanks for the post. Marking it as a bug.
