### ISSUE TITLE
Missing boot_id

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/WSL#2518]
Build: 16296
To repro, install flatpak then:
```
federico@Bestia:~$ sudo flatpak update
error: Failed to open file '/proc/sys/kernel/random/boot_id': File o directory non esistente

federico@Bestia:/proc/sys/kernel/random$ ls -al
totale 0
dr-xr-xr-x 2 root root 0 set 23 12:35 .
dr-xr-xr-x 4 root root 0 set 23 12:35 ..
-r--r--r-- 1 root root 0 set 23 14:04 uuid
``` 
From the web (I'm not a great Linux user):

> /proc/sys/kernel/random/boot_id: A random ID that is regenerated on each boot. As such it can be used to identify the local machine's current boot. It's universally available on any recent Linux kernel. It's a good and safe choice if you need to identify a specific boot on a specific booted kernel.

**Comment by samdmpr** [comment]
@benhillis is there any workaround available for this issue on fall creators build(1709).

**Comment by benhillis** [comment]
@samdmpr - Unfortunately not, this fix will be available in the next release of Windows coming this spring.

**Comment by therealkenc** [comment]
> Unfortunately not,

```
$ cd /proc/sys/kernel
$ sudo mkdir /tmp/proc
$ sudo mount -t procfs none /tmp/proc
$ sudo mount -t tmpfs none ./random
$ cd random
$ sudo ln -s /tmp/proc/sys/kernel/random/uuid uuid
$ sudo ln -s /tmp/proc/sys/kernel/random/poolsize poolsize
$  sudo ln -s /tmp/proc/sys/kernel/random/entropy_avail entropy_avail
$ echo 60287c01-cb1b-4faa-b99c-f6ae4b14d9b6 >> boot_id
$ cat /proc/sys/kernel/random/boot_id
60287c01-cb1b-4faa-b99c-f6ae4b14d9b6
```

Just sayin. 😉

**Comment by benhillis** [comment]
@therealkenc - Didn't think of that, haha.
