### ISSUE TITLE
Escape problems when cd to environment var

### ISSUE THREAD

**Issue by JoeCodeswell** [Microsoft/WSL#2531]
Hi folks,

This seems like a basic bug to me or am I not understanding something?

Expected result: bash should cd to the value of the environment var
Actual result: bash-cd doesn't recognize the escapes in the value string!

Here's the code.

    joebash@joethinks:~$ cd $BROWPATH00
    bash: cd: /mnt/c/Program\: No such file or directory
    joebash@joethinks:~$ echo $BROWPATH00
    /mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application
    joebash@joethinks:~$ cd /mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application #copied above
    joebash@joethinks:/mnt/c/Program Files (x86)/Google/Chrome/Application$

Thanks for the great work and the help.

Love and peace,

Joe

This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
```
cd "$BROWPATH00"
```

**Comment by benhillis** [comment]
@therealkenc is correct, spaces are paths are not very common in Linux but are not illegal either.  When dealing with paths in scripts it's best to wrap them in quotes.
