### ISSUE TITLE
`ubuntu.exe run` is glitchy

### ISSUE THREAD

**Issue by leongrdic** [microsoft/WSL#2532]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.0]

* What you're doing and what's happening:

I created a script `test.sh` in my linux home dir that prints out the first two arguments sent to it:
```
#!/bin/bash
echo "$1"
echo "$2"
```
Next I tried calling from Windows:
```
ubuntu run ~/test.sh "this is argument1" "this is argument2"
```
The output I received was:
```
this
is
```

* What's wrong / what should be happening instead:

The output I was expecting is:
```
this is argument1
this is argument2
```

On the contrast, when I run:
```
wsl ~/test.sh "this is argument1" "this is argument2"
```
I get the expected output.

So the way `ubuntu run` and `wsl` process their arguments must be different in some way. I'm guessing the quotes `"` are getting ignored for `ubuntu run`

**Comment by therealkenc** [comment]
#2348 ([message](https://github.com/Microsoft/BashOnWindows/issues/2348#issuecomment-318210848)).  [The actual bug is that `ubuntu.exe` and `openSUSE-42.exe` exist, but I digress.]

**Comment by zadjii-msft** [comment]
Filed MSFT:14049024 to investigate on my end. This is the expected behavior with the way it's written today, but I'm not sure quite yet the right way to fix this, if it should be fixed.

**Comment by benhillis** [comment]
@zadjii-msft - It should probably perform command line parsing the same way that wsl.exe and bash.exe do.
