### ISSUE TITLE
WSL sockets paged pool memory leak

### ISSUE THREAD

**Issue by dmex** [Microsoft/WSL#2535]
I was looking into a potential bug with our Windows application ([Process Hacker](https://github.com/processhacker2/processhacker)) and was using WSL to simulate large numbers of network connections with nginx and discovered a lxcore.sys paged pool memory leak. 

After about 16,000 connections have been created and closed WSL still continued to consume 10GB paged pool memory and does not release the memory until the console session itself has exited.

* Your Windows build number: 
10.0.16299.0

* What you're doing and what's happening:  

sudo apt install nginx
sudo nginx
A basic Windows project that spawns threads, creates sockets and connects to the local nginx server inside a loop should be enough to reproduce the leak.

* What should be happening:

WSL should free paged memory when the socket has closed.

* What's wrong:

lxcore.sys/lxss.sys driver memory leak:
https://i.imgur.com/oOBJPaE.png

nginx processes:
https://i.imgur.com/J3a1N4D.png

Killing the nginx processes didn't help:
https://i.imgur.com/ntPbvel.png
https://i.imgur.com/RhP5cnY.png

After closing the console window:
https://i.imgur.com/s0WmPqQ.png
https://i.imgur.com/ZD54gj3.png

This is also somewhat related to #1786 😄

**Comment by Yay295** [comment]
Do you know if this has been fixed with the Fall Creators Update?

**Comment by dmex** [comment]
@Yay295 

Yeah. I can't reproduce the issue on build 16299.19 👍

**Comment by therealkenc** [comment]
I guess we call this one silently fixed in 16299.19 unless/until someone says otherwise. Would feel better knowing if the leak existed in 15063 Creator's Update or if this was just some transient thing, but it is kind of academic.
