### ISSUE TITLE
How to Integrate Linux into Windows

### ISSUE THREAD

**Issue by zjjpp** [Microsoft/WSL#2537]
Using the latest version of Ubuntu from the Windows Store, you can easily integrate Linux into Windows.
First, install VcXsrv or XMing. Set it to separate windows and run `export DISPLAY=localhost:0`, then follow these directions.
In a fresh install, simply type `sudo apt update && sudo apt install xfce4` and when it is installed, run `xfce4-session`.  Instead of taking up the entire screen with the desktop, it becomes transparent and gives you the dock and the top bar. Right-click the top panel and set it to autohide, or it will interfere with maximized windows. That is pretty much all, and you can run all the linux programs you want.
There may be lag at first, but it will go away.
(tested with XMing)
If you want to make it auto-start on login, make a batch file with the following commands and use task scheduler to make it auto run:
`@echo off`
`start "XMING" "C:\Program Files (x86)\Xming\Xming.exe" :0 -clipboard -multiwindow`
`start "WSL" wsl xfce4-session --display localhost:0`

**Comment by iz0eyj** [comment]
I use the mixed desktop from  very long time and I think it is the real power of WSL.

**Comment by spences10** [comment]
Wait, so what @iz0eyj has pictured is a Windows window with Linux running in it?

**Comment by iz0eyj** [comment]
@spences10 
I'm late, sorry.
This is the normal W10 Desktop integrated with xfce4 (menù on the right, now opened) running on WSL 
as described by @zjjpp 
The browser is the Linux version of Vivaldi.

**Comment by spences10** [comment]
This yes?

![screenshot_20171009-141127](https://user-images.githubusercontent.com/234708/31339749-c9f88e0e-acfb-11e7-8802-f0673bc389a9.jpg)

Is there documentation for this? So I can educate myself 😀

I use Vivaldi too 👌

Thanks

**Comment by iz0eyj** [comment]
Yes, this.
No doc because at the moment microsoft don't supports GUI software on WSL, but it is simple.
You can begin installing VcXsrv on Windows (free software), then follow the post of @zjjpp to get a first running environment.

**Comment by iz0eyj** [comment]
@spences10 @therealkenc 
Vivaldi's HTML5 score.
WSL version is the foreground window.
Please @benhillis ... a bit of work on audio support and dbus :)

![snip_20171011105537](https://user-images.githubusercontent.com/6331284/31432896-17314404-ae78-11e7-8b6a-d22648b63f5b.jpg)

**Comment by PhMajerus** [comment]
@spences10 
I have an incomplete document I started writing about this if you want.
It doesn't have everything I wanted and isn't updated for the Fall Creators Update yet, but will give you all the information about how WSL works and how to get GUI apps running:
https://docs.com/majerus/8108/windows-nt-lxss

**Comment by spences10** [comment]
Wow, ok, thanks @PhMajerus 👍

**Comment by ntklotz** [comment]
@PhMajerus Great guide! I know you haven't updated for FCU yet but do you have anything for dbus support? Also, like so many others, I'm a fan of the Plasma Desktop and would prefer to utilize that if possible, I've tried playing around with it before with CU and AU but I've never managed to get the desktop environment to display properly. Also FCU specific, I had to uninstall, reinstall my Ubuntu instance utilizing the Windows Store and now my workarounds to upgrade from LTS no longer work (modifying the conf file to switch from lts has no joy now it seems). If there's a new workaround to allow updates to the developmental release that you know of or know somebody who has one, I would greatly appreciate seeing it in your guide. I usually beta test new OS builds in my spare time and not having the latest Ubuntu build (17.10 as of now) is very frustrating. Lastly, now that we have OpenSuse available, getting the OpenSuse commands to do everything you've listed in your guide available so we can recreate the same experience using that distro would be great. I've never worked with that distro before so having some starting point for configuring it would help immensely. So far I've only manager to figure out the zypper commands (so weird compared to Get commands for Powershell and APT.)

**Comment by styfle** [comment]
@PhMajerus That document is going to get deleted soon when docs.com is decomissioned. You should move it to a GitHub README.md or simply a [gist](https://gist.github.com).

**Comment by PhMajerus** [comment]
@styfle I know, I have a local copy for when docs.com goes offline.
I just haven't decided yet if it will be on GitHub, OneDrive, or personal blog... I'll probably keep writing in Word because it's faster and export as PDF though.

**Comment by benhillis** [comment]
Thanks for the discussion.
