### ISSUE TITLE
arping fails with error 'Address family not supported by protocol'

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/WSL#2538]
* Your Windows build number:  10.0.15063

From bash (run as administrator :

    $ sudo apt install arping
    $ sudo apt-get update
    $ sudo apt-get upgrade
    $ sudo arping 192.168.1.1
    arping: libnet_init(LIBNET_LINK, eth1): socket: Address family not supported by protocol

also arp -d does not work:

    $ sudo arp -d 192.168.1.1
    SIOCDARP(dontpub): Invalid argument

**Comment by ThomasHabets** [comment]
Does Windows support raw sockets nowadays?

**Comment by Yay295** [comment]
I can confirm this still fails after the Fall Creators Update.

**Comment by PalmerCurling** [comment]
Still failing 3/9/2018.

`sudo arping -i eth0 d0:50:99:38:d1:7a
arping: libnet_init(LIBNET_LINK, eth0): socket: Address family not supported by protocol`

**Comment by ThomasHabets** [comment]
Please don't use middle-endian date format. ISO8601/RFC3339 are unambiguous. If you really hate proper date formats then spell out the month name. 95% of the world will misread US date formats.

For posterity: That was 2018-03-09.

**Comment by therealkenc** [comment]
For posterity, the date is right beside his name. Also for posterity, an 18 trillion dollar economy does not care what RFC3339 says. If 95% of the world can't figure out when that was posted, I have my doubts on 95% of the world's powers of deductive reasoning. Concede you might be right on that point, though. Also posted on 9/3/18.

**Comment by ThomasHabets** [comment]
@therealkenc hello troll.

**Comment by Alysko** [comment]
Same with etherwake and many others. Very sad :'(

**Comment by Yay295** [comment]
Still fails after the April update (Redstone 4).

```
$ sudo arping 192.168.1.1
arping: lookup dev: No matching interface found using getifaddrs().
arping: Unable to automatically find interface to use. Is it on the local LAN?
arping: Use -i to manually specify interface. Guessing interface wifi0.
arping: libnet_init(LIBNET_LINK, wifi0): socket: Address family not supported by protocol
```

**Comment by Philipnah** [comment]
still doesn't work in january 2019!

**Comment by ThomasHabets** [comment]
> Still failing 3/9/2018.

Please don't use US-only date formats.

**Comment by ThomasHabets** [comment]
I don't code on Windows. I'll very happily accept patches or documentation for how to get it working, but I'm not going to work on it.

**Comment by Biswa96** [comment]
@ThomasHabets Your program is OK. The issue in the kernel mode drive aka. `LxCore.sys`. The event tracing shows `Function:LxpSocketGetDispatchTable Line:1148 Message:Socket: Unsupported socket family:17`, where 17 is `AF_PACKET`. LxCore has only 1, 2, 10, 16 socket protocol family/domain. 

Hence we've to wait until MS add that socket family.

**Comment by tsk1996** [comment]
Hi Guys,
I am experiencing a similar issue while using arpspoof .  [https://github.com/tsk1996/Arpspoof/issues/1#issue-466398714](url)
Error: 
root@TS:/home/user# arpspoof
arpspoof: socket: Address family not supported by protocol

So isn't there a proper solution for this?

**Comment by Biswa96** [comment]
Workaround: WSL2 (aka. the Linux kernel) supports that socket family AF_PACKET (17).

**Comment by ahmed6shoshan** [comment]
still doesn't work in 2020 ):

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/84444609-08bb8400-abf7-11ea-8878-ce1ec0b47c46.png)

**Comment by Yay295** [comment]
therealkenc strikes again...

**Comment by cbesot** [comment]
forget wsl! Use wsl2 (windows >= 2004).

**Comment by comodoro** [comment]
Label fixed-in-wsl2 says it all: a useful tool goes to bust because of Microsoft's vain attempt to monopolize virtual machine industry with intolerant Hyper-V
