### ISSUE TITLE
0x80070070

### ISSUE THREAD

**Issue by roschacker** [microsoft/WSL#2540]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Executed 
`bash.exe`

Expected Ubuntu command prompt

* What's wrong / what should be happening instead:
```
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070070
```

[lxcore.etl.zip](https://github.com/Microsoft/BashOnWindows/files/1357194/lxcore.etl.zip)

**Comment by roschacker** [comment]
```
lxcore_service.etl	32.00 k
lxcore_user.etl	16.00 k
lxcore_adss.etl	8.00 k
lxcore_kernel.etl	8.00 k
```
files attached in zip:
https://github.com/Microsoft/BashOnWindows/files/1357194/lxcore.etl.zip

**Comment by melanie-idl** [comment]
Ever find a fix @roschacker ?

**Comment by roschacker** [comment]
> 
> 
> Ever find a fix @roschacker ?

it works now
but i don't remember the solution

**Comment by tara-raj** [comment]
The error you're running into means WSL failed to register. Usually you can resolve this issue as described here - https://github.com/Microsoft/WSL/issues/2980. Using the wslconfig tool is a nice way to manage your distributions and registrations when you hit this type of error.
