### ISSUE TITLE
Unable to install extra packages on Bash

### ISSUE THREAD

**Issue by joetidee** [Microsoft/WSL#2549]
I have been following this documentation in order to install Docker on Bash:
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#uninstall-old-versions

When I get to the step that asks me to install the extra packages:
`sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual`

it says:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-image-extra-4.4.0-43-Microsoft
E: Couldn't find any package by regex 'linux-image-extra-4.4.0-43-Microsoft'
```

**Comment by therealkenc** [comment]
#2363. The Ubuntu package `linux-image-extra-4.4.0-43-Microsoft` does not exist, natch. There is no linux kernel image in WSL. Also #85, #2114, and user voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker).
