### ISSUE TITLE
shell script - cannot create files (touch/echo)

### ISSUE THREAD

**Issue by ShelbyZ** [Microsoft/WSL#2551]
* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:
I have an existing shell script which creates a few files using the output redirection operator to send command output and when running the commands via WSL I receive the following errors (on simpler examples):

```
#!/bin/bash
touch file.name
```

> touch: cannot touch 'file.name'$'\r': No such file or directory

```
#!/bin/bash
echo "" > file.name
```

> : Directory nonexistentnnot create file.name

* What's wrong / what should be happening instead:
I would expect that the file be created.  It is possible to run both commands outside of a shell script and have the files properly created.  I did also run the commands using sudo with the same end result.

* Strace of the failing command, if applicable:
[touch.zip](https://github.com/Microsoft/BashOnWindows/files/1366604/touch.zip)
[echo.zip](https://github.com/Microsoft/BashOnWindows/files/1366605/echo.zip)

**Comment by 0xbadfca11** [comment]
That shell script has [CRLF end of line](https://en.wikipedia.org/wiki/Newline#Common_problems).

**Comment by therealkenc** [comment]
More expository in #2365 ([message](https://github.com/Microsoft/BashOnWindows/issues/2365#issuecomment-317526788)).

**Comment by ShelbyZ** [comment]
It is definitely a line-endings issues as my GIT was setup with windows-style line endings and not unix which should have clicked, but it didn't.  I can create a file via nano and have the correct line-endings and have it execute correctly.  Line-endings do make some actions a bit more difficult in a shared environment.
