### ISSUE TITLE
Joining your Linux instance to AD?

### ISSUE THREAD

**Issue by jdkruzr** [Microsoft/WSL#2554]
This does not work, in part because the hostname for the Linux instance is the same as your machine, and I think in part because of other failures. The last time I tried to do this I broke a lot of things so I'm reticent to try it again. Basically, I'd like to be able to use/log in as the same AD accounts I use in Windows as I do in Ubuntu on my machine, but sssd, etc. can't join correctly. Is there a plan to make this work or is there some other way of making it work that I'm not seeing?

* Your Windows build number:  10.0.16299.15

**Comment by jakegt1** [comment]
If it's a hostname problem i'm pretty sure you can just use hostname to change it?
