### ISSUE TITLE
Dir sync fails with DrvFs and samba  share -> report as "invalid" (EINVAL), but not "I/O error" (EIO).

### ISSUE THREAD

**Issue by theChaosCoder** [microsoft/WSL#2557]
It seems that dir sync is not working when mounting a network share via DrvFs. 
I encountered this error with BorgBackup https://github.com/borgbackup/borg/issues/1961#issuecomment-335491180

The error is:  **OSError: [Errno 5] Input/output error**

**I think you should either support dir sync or say "invalid" (EINVAL), but not "I/O error" (EIO).**

Sample code to reproduce the error: 

```
import errno
import os
import sys

def sync_dir(path):
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    except OSError as os_error:
        # Some network filesystems don't support this and fail with EINVAL.
        # Other error codes (e.g. EIO) shouldn't be silenced.
        if os_error.errno != errno.EINVAL:
            raise
    finally:
        os.close(fd)

if __name__ == '__main__':
    path = sys.argv[1]
    print("Syncing dir %s" % path)
    sync_dir(path)
```
Usage:

`python3 syncdir.py somedirectory`

> sudo mount -t drvfs D: /mnt/Ddrive/ <-- dir sync OK
> sudo mount -t drvfs F: /mnt/usbstick/ <-- dir sync OK
> sudo mount -t drvfs '\\\synology\Backups' /mnt/borgBackup/ <-- sync Fail 
> (also fails if mounted in Win as a Network Drive z: )

"\\\synology\Backups" is a samba v3 share

Tested with Windows Build  16299.15.170928-1534.rs3_release & Ubuntu from the Store

**Comment by enkore** [comment]
Since FlushFileBuffers (on the Win32 side of things) does not support directory handles, I'd guess that the kernel doesn't contain that functionality. This looks like an incorrect mapping of error codes (ERROR_INVALID_HANDLE to EIO instead of EINVAL or EBADF).

**Comment by benhillis** [comment]
We've adjusted our error mappings in recent versions of Windows.  Please reopen a new issue if you see issues on 19042.

**Comment by theChaosCoder** [comment]
Seems to be fixed (tested on 20H2). Thx.
