### ISSUE TITLE
Unable to startproject on scrapy

### ISSUE THREAD

**Issue by sasikp** [microsoft/WSL#2561]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I'm new to installing packages in unix and python. I'm working on Bash on Ubuntu on Windows. I wanted to start learning Scrapy, which I installed using:

> apt-get install scrapy

When I'm trying to create a project, I'm getting the following error:

> root > scrapy startproject tutorial
> Traceback (most recent call last):
>   File "/usr/local/bin/scrapy", line 11, in <module>
>     sys.exit(execute())
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 128, in execute
>     cmds = _get_commands_dict(settings, inproject)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
>     cmds = _get_commands_from_module('scrapy.commands', inproject)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
>     for cmd in _iter_command_classes(module):
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 19, in _iter_command_classes
>     for module in walk_modules(module_name):
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 71, in walk_modules
>     submod = import_module(fullpath)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/version.py", line 6, in <module>
>     import OpenSSL
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 16, in <module>
>     from OpenSSL._util import (
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
>     from cryptography.hazmat.bindings.openssl.binding import Binding
>   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
>     from cryptography.hazmat.bindings._openssl import ffi, lib
> ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument
> root >

I verified that the above file is available. I'm trying to understand if there is any prerequisite(s) I missed to install (which I doubt, as I understand that they are handled during installation - please correct me if I'm wrong), or is there anything I need to enable.

Thanks, Sasi

* What's wrong / what should be happening instead:
I'm supposed to be able to start with scrapy, which I'm unable to.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

> root > strace -o strace.txt -ff scrapy startproject tutorial
> Traceback (most recent call last):
>   File "/usr/local/bin/scrapy", line 11, in <module>
>     sys.exit(execute())
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 128, in execute
>     cmds = _get_commands_dict(settings, inproject)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
>     cmds = _get_commands_from_module('scrapy.commands', inproject)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
>     for cmd in _iter_command_classes(module):
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 19, in _iter_command_classes
>     for module in walk_modules(module_name):
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 71, in walk_modules
>     submod = import_module(fullpath)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/version.py", line 6, in <module>
>     import OpenSSL
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 16, in <module>
>     from OpenSSL._util import (
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
>     from cryptography.hazmat.bindings.openssl.binding import Binding
>   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
>     from cryptography.hazmat.bindings._openssl import ffi, lib
> ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument
> root >

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> `ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument`

I'm guessing everyone's crypto libraries must have levelled recently (for some value of recent). #2561, #2553, #916, #442, #286 et al.

**Comment by therealkenc** [comment]
> `ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument`

I'm guessing everyone's crypto libraries must have levelled recently (for some value of recent). #2562, #2553, #916, #442, #286 et al.

**Comment by sasikp** [comment]
Hi, is there any solution available for this issue?
