### ISSUE TITLE
Can't start ssh in WSL : Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.

### ISSUE THREAD

**Issue by Blazero** [Microsoft/WSL#2563]
* Your Windows build number:  10.0.15063

* What you're doing and what's happening:  
input:
`sudo service ssh start`
output:
```
sshd: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
                                                                                                                 [fail]
```
See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Blazero** [comment]
When I googled it, many people say this has been solved already. Why would I meet it today?

**Comment by therealkenc** [comment]
> many people say this has been solved already. Why would I meet it now?

Likely because #2142, #2120, or to quoth Sunil #508 ([message](https://github.com/Microsoft/BashOnWindows/issues/508#issuecomment-306630069)):

> Basically, its some anti-virus (or VPN) software interfering.

**Comment by Blazero** [comment]
I've already uninstalled my anti-virus software and reset my network, the problem remains.

**Comment by razvan-panda** [comment]
I thought it might be the antivirus or Networx. I disabled both of them and the issue still persists.

**Comment by razvan-panda** [comment]
I think the problem was caused by WinPcap https://www.winpcap.org/ most probably
`WinPcap is the industry-standard tool for link-layer network access in Windows environments`
^ industry standard in making WSL not work heh

**Comment by therealkenc** [comment]
Nah I have winpcap installed for Wireshark since forever and WSL is fine... Could be some combination or config thing I don't happen to be tripping though, I suppose.

**Comment by razvan-panda** [comment]
Well, what we know with extremely high certainty is that WinPcap was causing the issues. After uninstalling it those errors stopped completely.

**Comment by sunilmut** [comment]
@razvan-panda - Good to know you could resolve the issue. Could you check `WinPcap` install a TDI filter driver by any chance? See [this](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927) post (and the one below) for details.

**Comment by razvan-panda** [comment]
@sunilmut From what I recall it might have asked for a TDI filter. I haven't reinstalled it.

**Comment by Blazero** [comment]
@sunilmut Thank you very much, yours is the first truly helpful answer. 
When I check event 16001, I found there is a TDI filter driver (\Driver\QqGameMasterControl) from a software which I uninstalled six months ago. I would never think about that without your reply.
After I delete it (sc delete QqGameMasterControl), the problem is gone.
