### ISSUE TITLE
WSL not working only with _

### ISSUE THREAD

**Issue by whw19950510** [microsoft/WSL#2565]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Win10 pro latest
![image](https://user-images.githubusercontent.com/18900579/31566555-cb1534b2-b030-11e7-9f4c-d15a883aeb7f.png)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Run bash 
* What's wrong / what should be happening instead:
No response, I can' t even uninstall it. When I uninstall, the prompt just hang there with no response.
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by whw19950510** [comment]
I have just updated win10 to latest version, and after I reinstall WSL, it doesn' t work anymore. I have used it in the older version...

**Comment by rowanG077** [comment]
You have no provided your windows version.

**Comment by whw19950510** [comment]
It's 10.0.15063. Sorry for the ommision.
