### ISSUE TITLE
How to system backup for WSL?

### ISSUE THREAD

**Issue by bluesky2003** [Microsoft/WSL#2567]
Sorry, i did not find the answer on web, so that, i post this question here. Hope suggestion for me. Many thanks!

**Comment by tara-raj** [comment]
My suggestion is to backup to a tar file. You can backup using tar as you would in a native Linux environment. This is a good reference - [https://help.ubuntu.com/community/BackupYourSystem/TAR]Ubuntu system backup. Be sure to refer to your Windows OS using the “/mnt/c” prefix (for the C: system drive). You can then load up and unpack that tar.gz on a new distro using that same reference paradigm. Backing up to a USB is also possible as long as the USB is FAT/NTFS-formatted.
