### ISSUE TITLE
USB Yubikey smartcard support

### ISSUE THREAD

**Issue by Sekanato** [Microsoft/WSL#2568]
* I'm running:
`Microsoft Windows [Version 10.0.16299.15]`

* In fresh Ubuntu instance with pcscd scdaemon and supplement libraries installed I'm getting:
```
user@machine:~$ gpg -vvv --card-status
gpg: using character set `utf-8'
gpg: pcsc_establish_context failed: no service (0x8010001d)
gpg: card reader not available
gpg: OpenPGP card not available: general error
```
* Should be like:
```
user@machine:~$ gpg --card-status
Reader ...........: Yubico Yubikey 4 OTP U2F CCID 0
Application ID ...: D*************************
Version ..........: 2.1
Manufacturer .....: Yubico
Serial number ....: ****************
Name of cardholder: John Doe
Language prefs ...: en
Sex ..............: male
URL of public key : http://example.com/key.asc
Login data .......: john_doe
Signature PIN ....: forced
Key attributes ...: rsa4096 rsa4096 rsa4096
Max. PIN lengths .: 1
27 127 127
PIN retry counter : 3 0 3
Signature counter : 999
Signature key ....: ***
      created ....: 1917-08-06 12:00:00
Encryption key....: ***
      created ....: 1917-08-06 12:00:00
Authentication key: ***
      created ....: 1917-08-06 12:00:00
General key info..: sub  rsa4096/*** 1917-08-06 John Doe <john_doe@example.com>
sec#  rsa4096/***  created: 1917-08-06  expires: never
ssb>  rsa4096/***  created: 1917-08-06  expires: 1938-08-06
                                card-no: *** ****
ssb>  rsa4096/***  created: 1917-08-06  expires: 1938-08-06
                                card-no: *** ****
ssb>  rsa4096/***  created: 1917-08-06  expires: 1938-08-06
                                card-no: *** ****
```

* With native `gpg` in `cmd` the behavior is normal and command `gpg --card-status` gives expected result but not in WSL Ubuntu instance.

**Comment by therealkenc** [comment]
#1521, #412, #2287, #2185 et al.

**Comment by Sekanato** [comment]
@therealkenc It seems that all those issues are for an earlier build. The one I'm at supposed to support usb devices as stated [here](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/).

**Comment by DHowett-MSFT** [comment]
I believe that only applies to USB devices that present as serial devices, not all USB devices.

**Comment by Sekanato** [comment]
@DHowett-MSFT Thanks for the reply! Indeed. In [this](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/#comment-34136) comment @bitcrazed said that security devices are not supposed to work yet. Maybe I've misunderstood the announcement.
It's a shame that those are not implemented yet though. [This](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16759696-add-usb-device-support) uservoice marked complete threw me off, because there was stated specifically USB devices support and not just serial and/or storage mounting.
So if that is the case, then that uservoice should be unmarked as complete and this issue should remain open as a stand in for all those about smartcards, that were closed like #1521 when USB serial and storage was announced, or those reopened. Just an opinion, though.

**Comment by therealkenc** [comment]
>  then that uservoice should be unmarked as complete and this issue should remain open as a stand in for all those about smartcards

The suggestion in #2185 ([message](https://github.com/Microsoft/BashOnWindows/issues/2185#issuecomment-307191568)), for what it is worth, has been to re-open a new User Voice. This is about support for [libusb](https://github.com/libusb/libusb); which applies to anything that wants raw access to a USB bitstream, be it a smart card reader, jtag dongle, or whatever.

**Comment by Sekanato** [comment]
Ok, sounds reasonable. I've looked at uservoice and didn't find any libusb posts, so posted [new one](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/31920928-add-libusb-support-to-wsl). Hope it's clear enough this time 😄 
Should this issue remain open?

**Comment by therealkenc** [comment]
Let's dupe it, since that's what happened with #1521, and there is really only one actionable here. Subscribe to #412, and if the status flips, try your scenario again. If `libusb` support gets added but Yubikey readers _still_ don't work, that would certainly be postworthy.

**Comment by svrooij** [comment]
The uservoice is closed referring to this issue tracker.
I would still like to be able to use my yubikey (for ssh authentication) inside wsl

Any updates???
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/31920928-add-libusb-support-to-wsl

**Comment by thisguychris** [comment]
@svrooij looks like this was closed because of similar issue #412.

**Comment by thisguychris** [comment]
Issue forwarded here (for libusb): https://github.com/microsoft/WSL/issues/2195

**Comment by jamiehankins** [comment]
> The uservoice is closed referring to this issue tracker.
> I would still like to be able to use my yubikey (for ssh authentication) inside wsl
> 
> Any updates???
> https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/31920928-add-libusb-support-to-wsl

Have you tried this?
https://polansky.co/blog/a-better-windows-wsl-openssh-experience/
