### ISSUE TITLE
Interactive bash does not start properly in Windows Insider's built-in SSH shell

### ISSUE THREAD

**Issue by rbalint** [microsoft/WSL#2572]
* Your Windows build number:  Microsoft Windows [Version 10.0.17017.1000]                                                                                                                    

* What you're doing and what's happening:
Enabled built-in SSH server, then:
```
ssh user@windows-host
user@windows-host's password
Microsoft Windows [Version 10.0.17017.1000]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\Users\user>bash -c "echo hello"
hello
C:\Users\user>bash
]0;user@DESKTOP-XXXXXX: /mnt/c/Users/user[01;32mrbalint@DESKTOP-TL0ATTV[00m:[01;34m/mnt/c/Users/user[00m$
```
Here i can't type anything and the shell does not respond

* What's wrong / what should be happening instead:
The interactive shell should work like when just executing commands with the -c option.

**Comment by xyzith** [comment]
Got same issue here.
It seems win 10 host its own ssh service for all insider version user.
Disable these 2 service on win10:
SSH Server Broker
SSH Server Proxy

It's not related to WSL, but it's really dumb to enable SSH service( with cmd ) to all userㄡ

**Comment by benhillis** [comment]
I tried this on a new build and it worked for me, can you reopen a new issue if you're still having issues?
