### ISSUE TITLE
Git clone of some repos with symlinks shows modified state for them

### ISSUE THREAD

**Issue by redbaron** [microsoft/WSL#2579]
* Your Windows build number:  Microsoft Windows [Version 10.0.17017.1000]

* What you're doing and what's happening:  
```
$ cd ~
$ git init kubernetes; cd kubernetes
$ git remote add origin https://github.com/kubernetes/kubernetes
$ git fetch
$ git checkout 0b9efaeb34
$ git status
HEAD detached at 0b9efaeb34
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .bazelrc
        modified:   .kazelcfg.json
        modified:   BUILD.bazel
        modified:   Makefile
        modified:   Makefile.generated_files
        modified:   WORKSPACE
        modified:   cluster/gce/cos
        modified:   cluster/gce/ubuntu
        modified:   cluster/juju/layers/kubernetes-master/actions/namespace-delete
        modified:   cluster/juju/layers/kubernetes-master/actions/namespace-list
        modified:   vendor/k8s.io/api
        modified:   vendor/k8s.io/apiextensions-apiserver
        modified:   vendor/k8s.io/apimachinery
        modified:   vendor/k8s.io/apiserver
        modified:   vendor/k8s.io/client-go
        modified:   vendor/k8s.io/code-generator
        modified:   vendor/k8s.io/kube-aggregator
        modified:   vendor/k8s.io/metrics
        modified:   vendor/k8s.io/sample-apiserver

$ git diff Makefile
diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -1 +0,0 @@
-build/root/Makefile
\ No newline at end of file
```

* What's wrong / what should be happening instead:
there should be no changes detected in a freshly cloned repo.

I wasn't able to reproduce this bug by creating an empty repo myself and committing a symlink. Both lxfs and drvfs are affected.

**Comment by Relequestual** [comment]
This appears to be due to the following (https://stackoverflow.com/a/56508009/89211):


> 
> This issue occurs because Windows and Linux (or at least the emulated version) disagree about the size of a symlink. On Windows, a symlink's size is in blocks, so a 6-character symlink will be 4096 bytes in size. On Linux, a symlink's size is the number of bytes it contains (in this example, 6).
> 
> One of the things that Git writes into the index to keep track of whether a file has changed is the size. When you perform any sort of update of the index, such as with git reset --hard, Git writes all of this metadata into the index, including the size. When you run git status, git checks this metadata to determine if it matches, and if not, it marks the file as modified.
> 
> It is possible to control whether certain information is checked in the index, since some tools can produce bogus info (for example, JGit doesn't write device and inode numbers), but size is always checked, because it is seen as a good indicator of whether a file has changed.
> 
> Since this is a fundamental disagreement between how Windows and how WSL see the symlink, this really can't be fixed. You could try asking the Git for Windows project if they'd be willing to work around this issue in Git for Windows, but I suspect the answer is probably going to be no since changing it would likely have a performance impact for all Windows users.


I don't know what the correct resolution is here =/ But it's a real pain.
