### ISSUE TITLE
setting username to admin causes ubuntu to print please input password in a loop

### ISSUE THREAD

**Issue by ndc** [Microsoft/WSL#2580]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.15]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have just installed Windows 10 Pro Fall Creators Update, activated windows subsystem for linux feature, installed ubuntu from the app store, and ran ubuntu for the first time. It asked for a username.

* What's wrong / what should be happening instead:

I put 'admin' as username. The console said that 'admin' already exist, and then print 'please enter password' in a loop. I closed the bash window. I then reopened the bash window and the console said that I logged in as root (prompt is `root@mycomputername:~#`).

I didn't want to log in as root, so I googled how to change default user for login. Found some article telling to run `lxrun /setdefaultuser myusername` in the host command prompt. I tried but got error 0x80070002, saying that lxrun is only for legacy wsl.

**Comment by heldchen** [comment]
try `ubuntu config --default-user ndc`

**Comment by ndc** [comment]
Well I nuked it from orbit and reinstalled the ubuntu app. Thanks for the info, I'll use `ubuntu config` and `ubuntu clean` next time.

**Comment by cheshrkat** [comment]
I had a very similar thing happen in openSUSE, although I entered a different username. I forget the precise error message, but I'm pretty sure it was "does not exist" or something about it being invalid. Then it just printed `please enter password` over and over.

I did exactly the same as @ndc - killed the window, reopened to find `root@mycomputername:~#`, and then deleted and reinstalled :)

**Comment by DSakura1987** [comment]
I have exactly the same issue. Please fix it!

**Comment by benhillis** [comment]
@DSakura1987 - FYI: This issue has been fixed in the updated distribution launcher sample.

**Comment by DSakura1987** [comment]
@benhillis Sounds great. Where can I find the updated package? https://aka.ms/wsl-ubuntu-1604 has the issue. I am on Windows Server Version 1709, which is Server Core, so I have to do everything on command line.

**Comment by benhillis** [comment]
@DSakura1987 - Ubuntu needs to update their package, I do not think they have done so yet.  In the meantime do not specify "admin" as the user during install.

**Comment by benhillis** [comment]
This is resolved in the updated distro launcher sample.
