### ISSUE TITLE
Add optional margins to Windows console to improve readability.

### ISSUE THREAD

**Issue by PhMajerus** [Microsoft/WSL#2589]
This is a very simple suggestion, and should be easy to implement while providing great benefits.

Text flush with windows borders are not great for readability (I remember the Microsoft Reader or Typography team ran experiments on this years ago, deciding to include margins to ebooks on Pocket PC screens), and most CUI apps do not spare characters around their display to provide a margin.

So how about adding configurable margins in conhost?
This would be part of the layout options, defining a number of pixels width (left & right) and height (top & bottom). Conhost would then extend the window client area by these margins, using the current console background color but centering the buffer display within it.

This small modification would have no impact unless a user sets margins other than 0, and would greatly improve readability in the console.
For greater customization, you could even allow different margins for main and alternate buffer modes, making the interactive/buffer-log mode different from the one of CUI-apps that control their display precisely.

After all, if the goal is to make Windows the best workstation OS for cross-platform development, we shouldn't settle for just usable, we should aim for comfort and differentiate from the others in that area.

![conhost margins](https://user-images.githubusercontent.com/25664275/31866497-84d1b6cc-b780-11e7-962c-165d02c9bf20.png)

**Comment by zadjii-msft** [comment]
Already on the backlog :)

**Comment by Oeffner** [comment]
Better still would be to reinstate the option of setting window border thickness to something else than 0 pixel width from the control panel. This would have a similar effect as adding a marging within the window. This was possible in Windows 7 and earlier. With the current zero border width it takes a lot of time to correctly position the mouse on the border when attempting to resize a windows. This generally reduces productivity of the desktop.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#76

**Comment by Mickelodian** [comment]
In C:\Users\<USER>\Documents\PowerShell\profile.ps1 you can add the following:

function prompt {
    $host.ui.rawui.WindowTitle = "Custom Prompt"
    $padding = " " * 1
    "$padding PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "

}

This will indent the PROMPT by 1 (    $padding = " " * 1) but not the output... I'm still looking for the pipeline that formats that... but Microsoft could have formatted this properly as early as the late 1970's, seemingly tens of thousands of employees have better things to do than bother with making things look professional.

**Comment by zadjii-msft** [comment]
@Mickelodian We actually added support for margins in the Windows Terminal, like, 5 years ago. It was one of the earliest features. IIRC, it even predates the terminal code being open-source. 

See: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#padding
