### ISSUE TITLE
[lxrun /uninstall /full] The Windows Subsystem for Linux has an install or uninstall operation pending.

### ISSUE THREAD

**Issue by deerchao** [Microsoft/WSL#2590]
I installed "Bash on Ubuntu on Windows" and used it for months.
Then there comes the store app "Ubuntu", which I installed, and worked.
Now I want to uninstall the old "Bash on Ubuntu on Windows", so I run:

> C:\WINDOWS\system32>lxrun /uninstall /full
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore
>
> This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
The Windows Subsystem for Linux has an install or uninstall operation pending.

Tried rebooting, which doesn't work. So, how do I know which operation is pending and finish it so I can proceed?
Thanks!

**Comment by clu8** [comment]
I had the same issue. Try `lxrun /install` to set it up again and then `lxrun /uninstall /full` again.

**Comment by pleunv** [comment]
That does the job, thank you!

**Comment by ejbolt** [comment]
This does not fix the issue for me.  If I type bash after, it will say Error: 0x80070002.  I've tried uninstalling several times.

**Comment by baclv** [comment]
I had the same issue

**Comment by ejbolt** [comment]
Do you have the legacy version of bash and Ubuntu installed at the same time?  That's what broke for me. Uninstalled the Ubuntu app, did lxrun /uninstall /full and everything worked

**Comment by BhaveshSGupta** [comment]
I have same issue I have not installed Ubuntu yet,

**Comment by kirkone** [comment]
I can confirm the method from @ejbolt worked for me.

**Comment by orthros** [comment]
Can we confirm if @ejbolt 's method is the preferred method? I've spent a fair amount of time setting up my new Ubuntu system and I'd rather not have to re-setup

**Comment by ejbolt** [comment]
I would say that, if you're moving from the Bash on Ubuntu on Windows
installation to Ubuntu or SUSE, you should fully uninstall Bash on Ubuntu
on Windows, reboot, *then* install Ubuntu (or other distro) on Windows.
Prevents things from clashing.  Good news is, you can actually change your
shell like you would on Linux, instead of having your .bashrc file execute
the shell you want :) (I use zsh so I was very happy about this).

**Comment by molxyz** [comment]
@ejbolt  >Do you have the legacy version of bash and Ubuntu installed at the same time? That's what broke for me. Uninstalled the Ubuntu app, did lxrun /uninstall /full and everything worked
Hi, how do you uninstall the Ubuntu app?  I've looked everywhere and tried everything but I can't uninstall the Ubuntu app or the bash on cmd.exe.  Would appreciate for any help. Thank you.

**Comment by ejbolt** [comment]
You'll right click the Ubuntu app in your start menu and it should give you the option to uninstall.  Reboot, then run the above command on your command prompt, reboot.  Rebooting just to make sure everything gets deleted

**Comment by molxyz** [comment]
Oh I've found the answer... "Ubuntu clean" and I've got this solved, also reinstalled Ubuntu from the Windows Store.  Cool.

**Comment by molxyz** [comment]
@ejbolt 
>You'll right click the Ubuntu app in your start menu and it should give you the option to uninstall. Reboot, then run the above command on your command prompt, reboot. Rebooting just to make sure everything gets deleted

Thanks for your reply, didn't see before I wrote the comment above.  What I did was i kept searching and found this link: https://www.scivision.co/install-windows-subsystem-for-linux/  So all I did was "Ubuntu clean" on the windows command prompt and it uninstalled the app for me.  Then I reinstalled the app from the Windows Store and now it seems working. I didn't restart the computer, however.  Will keep an eye to see if I have any issue with this again and if so will try your solution next time.  Thank you.

**Comment by insetavijit** [comment]
go to seeting -> apps and fetaures -> ubuntu -> uninstall

**Comment by evil-shrike** [comment]
Nothing mentioned works for me (`lxrun /uninstall /full` fails with `Error: 0x80070002`):
* Removing Ubuntu Store App didn't help.
* Trying to run `lxrun /install` didn't help - it produces another error:
```
Downloading from the Microsoft Store... 0%
Error: 0x800703ee
```

**Comment by DarthSpock** [comment]
Lxrun is deprecated. It shouldn't be used since build 16299. The Store App version has a separate issue on build 17134.

**Comment by mlim1972** [comment]
After installing April's Creator Update, running Bash caused Blue Screen.  I uninstalled and when trying to install I got another blue screen.  Now, when trying to uninstall, I get the same message.  If I try to install, it says the system is already installed.  I disabled and enabled Linux subsystem through "Turn Windows Features on/off" without any success.

```
lxrun /uninstall
...
...

Type "y" to continue: y
Uninstalling...
The Windows Subsystem for Linux has an install or uninstall operation pending.
```

```
lxrun /install
...
...

Type "y" to continue: y
The legacy Windows Subsystem for Linux distribution is already installed.
```

**Comment by benhillis** [comment]
@mlim1972 - lxrun is no longer the supported way to install distributions. You can find your choice of Linux distributions in the Microsoft Store.

**Comment by oparoz** [comment]
Regarding `Error: 0x80070002`, you can only uninstall as the user, do not open a command prompt as an administrator and it should work.

**Comment by wolf99** [comment]
I'm seeing the `0x80070002` error. It seems I may have installed the Ubuntu Windows Store app over older non-store WSL. I've removed the store app and rebooted. I've tried 

- `Ubuntu clean` in the command prompt - it doesn't recognise Ubuntu as a command
- `lxrun /uninstall /full` but still get numbered error as above (as either user or administrator)

The Store app does seem to be gone but typing `wsl` in the "Run" box still launches a terminal (although it does tell me that there is no release installed)... shouldn't this be gone too?

**Comment by ejbolt** [comment]
To be honest, I've taken to dual booting Linux and windows on all my
machines. For me, the whole not being able to run 32 bit programs was a
deal breaker, along with just still not having the same terminal
integration with other apps such as vs code.  Can get it to work but was
still temperamental.

So I'm not much help on WSL issues anymore.

**Comment by bugeaud** [comment]
@benhillis
I do understand lxrun is non more the canonical way of doing things. But at a point of time, it was so. For the sake of people that were early adopters, MS shall have given a proper solution as an answer before closing the issue.

This issue is a real one and still existing until someone gives a proper solution to it. It should not have been closed as-is unless MS consider an untidy room as the new default cleaning standard.

Please reopen the issue as a consequence.

**Comment by NoSubstitute** [comment]
lxrun /uninstall /full
Ran as user in PowerShell, worked for me. On 17134 today, but have run WSL from early beta.
Updated to 18.04 with _do-release-upgrade_ which totally broke too many things to continue, so had to remove and restart.

**Comment by Almenon** [comment]
I've tried lxrun /uninstall both as admin and non-admin and neither worked.

Windows version 1803 build 17134.472

**Comment by Oxicode** [comment]
> go to seeting -> apps and fetaures -> ubuntu -> uninstall

🥇

**Comment by woozyking** [comment]
If you have tried to do `lxrun /uninstall` but failed with an error (in my case it was `0x800706f7`), then what worked for me eventually was to completely disable WSL (after uninstalled the store version of the distro) by going to 

```
control panel - programs - turn windows features on or off
``` 

and disable WSL

(I'm writing this without using the English version of Windows, so the terms/phrases above may vary but you get the gist)

**Comment by liujinliang01** [comment]
I succeeded in uninstalling WSL Ubuntu 18.04 from Win10 by issuing this command in cmd: 
wslconfig /unregister ubuntu
