### ISSUE TITLE
Unable to install gcc dev tools

### ISSUE THREAD

**Issue by wkbrd** [microsoft/WSL#2591]
gcc dev tools are not able to be installed on computers that are within our corporate domain.  Our IT department uses various security products made by Altiris and Sophos.  Systems within our environment on developer networks where these tools are not installed and corporate GPOs are not in effect are able to download and use the tools as expected.

* Your Windows build number:  10.0.16299.19 (was also a problem on Creators Update)

* What you're doing and what's happening:  
Initially, tried install gcc using: # apt-get install gcc 
Then ran: dpkg -i /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb

```
(Reading database ... 31603 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_4.4.0-97.120_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.4.0-97.120) ...
dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb (--install):
unable to create '/usr/include/linux/netfilter/xt_mark.h.dpkg-new' (while processing './usr/include/linux/netfilter/xt_mark.h'): Input/output error
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
/var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb
```

* What's wrong / what should be happening instead:
The software should have installed without any error messages.

* Strace of the failing command, if applicable: 
See [dpkg-trace.txt](https://github.com/Microsoft/BashOnWindows/files/1408021/dpkg-trace.txt)

**Comment by chervaliery** [comment]
I have the same problem here.
```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 libc6-dev : Depends: linux-libc-dev but it is not installed
E: Unmet dependencies. Try using -f.
```

And when I run `apt-get -f install` : 
```
Preparing to unpack .../linux-libc-dev_4.4.0-97.120_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.4.0-97.120) ...
dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb (--unpack):
 unable to create '/usr/include/linux/netfilter/xt_mark.h.dpkg-new' (while processing './usr/include/linux/netfilter/xt_mark.h'): Input/output error
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by wkbrd** [comment]
Hi @chervaliery!  Is this problem happening on a computer that is running anti-virus or corporate management software?  If so, what apps are running?

Could you also see if you can reproduce issue #2593?  I am interested in knowing if #2593 is related to this issue.

Thanks!

**Comment by chervaliery** [comment]
Hi @wkbrd , yes I can reproduce #2593 

```
$ touch lower.txt
$ touch Lower.txt
touch: cannot touch 'Lower.txt': Input/output error
```

Yes it's a corporate computer, I have Windows Defender Running but even turned off, I got the same error:
```
Preparing to unpack .../linux-libc-dev_4.4.0-97.120_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.4.0-97.120) ...
dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_
amd64.deb (--unpack):
 unable to create '/usr/include/linux/netfilter/xt_mark.h.dpkg-new' (while processi
ng './usr/include/linux/netfilter/xt_mark.h'): Input/output error
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/linux-libc-dev_4.4.0-97.120_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'll try tonight on my personal computer to see if I got the same error.

**Comment by chervaliery** [comment]
After the windows update, it works like a charm for me.

**Comment by nernst** [comment]
I'm also seeing a similar issue. For me, I was trying to install pip via "sudo apt-get install pip".  (Maybe relevant, I was also trying to simultaneously install pip3). After trying to clean up the install before searching for errors, I trying cleaning up the package installs by running "sudo apt-get -f install", which leads to this:

> 
> sudo apt-get install -f
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Correcting dependencies... Done
> The following additional packages will be installed:
>   libasan2
> The following NEW packages will be installed:
>   libasan2
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> 7 not fully installed or removed.
> Need to get 0 B/264 kB of archives.
> After this operation, 1,084 kB of additional disk space will be used.
> Do you want to continue? [Y/n] Y
> (Reading database ... 31651 files and directories currently installed.)
> Preparing to unpack .../libasan2_5.4.0-6ubuntu1~16.04.5_amd64.deb ...
> Unpacking libasan2:amd64 (5.4.0-6ubuntu1~16.04.5) ...
> dpkg: error processing archive /var/cache/apt/archives/libasan2_5.4.0-6ubuntu1~16.04.5_amd64.deb (--unpack):
>  trying to overwrite '/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0', which is also in package binutils 2.26.1-1ubuntu1~16.04.5
> dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
> Processing triggers for libc-bin (2.23-0ubuntu9) ...
> Errors were encountered while processing:
> E: Sub-process /usr/bin/dpkg returned an error code (1)

I'm on Version 10.0.17025.1000

For what it's worth, I tried to "reinstall" by removing WSL from Windows Features, rebooting, enabling, rebooting again and I immediately hit this. Guess removing WSL as a feature doesn't remove it completely like it did earlier.

I've attached an strace of the failed apt-get command.
[apt-get-trace.txt](https://github.com/Microsoft/WSL/files/1448286/apt-get-trace.txt)

I can provide any other diagnostic info requested.

**Comment by nernst** [comment]
I just tried to uninstall/reinstall manually using "lxrun /uninstall /full" followed by "lxrun /install" and I immediately ran into the exact same error as above when running "sudo apt-get install python-pip". 

Additionally, I'm not being prompted for a password when I sudo, so I don't think the "/full" switch does as advertised - I'd added myself to the sudo previously, but was added to it after a reinstall, so there are artifacts lingering after uninstall.

**Comment by PaulHiemstra** [comment]
I have a very similar problem with Ubuntu on Windows. As the OP, I run the computer in a corporate network with probably a lot of stuff installed. I have tried running the Bash terminal as Admin, but this did help at all.

@chervaliery do you have any idea what fixed the issue?

```
root:~# sudo apt-get install linux-libc-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  linux-libc-dev
0 upgraded, 1 newly installed, 0 to remove and 73 not upgraded.
5 not fully installed or removed.
Need to get 0 B/768 kB of archives.
After this operation, 3,950 kB of additional disk space will be used.
(Reading database ... 27735 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_3.13.0-135.184_amd64.deb ...
Unpacking linux-libc-dev:amd64 (3.13.0-135.184) ...
dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_3.13.0-135.184_amd64.deb (--unpack):
 unable to install new version of `/usr/include/linux/netfilter_ipv6/ip6t_HL.h': File exists
Errors were encountered while processing:
 /var/cache/apt/archives/linux-libc-dev_3.13.0-135.184_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by wkbrd** [comment]
@chervaliery, what version of Windows are you now running where it is now working?  Is this an Insider build? 

This problem is not working on select systems running the Fall Creators Update (Version 10.0.16299.19)

**Comment by PaulHiemstra** [comment]
@wkbrd I run a quite old version of Windows (10.0.14393). Did an update fix this issue for you?

**Comment by wkbrd** [comment]
Hi @PaulHiemstra, unfortunately, on systems that exhibit this problem it is still reproducing on 10.0.16299.64

**Comment by chokn** [comment]
I'm seeing this exact issue as well, but I cannot recreate issue #2593. I'm running Windows version 1703, build 15063.1029. I'm running in a corporate environment with McAffee antivirus among other things.

**Comment by DDvO** [comment]
I had the same problem and found that it is triggered simply because, for some unfortunate and weird reason, that Ubuntu `.deb` package contains a handful of (header) files with names that are distinct only by letter case, e.g., `/usr/include/linux/netfilter_ipv4/ipt_ttl.h` and `/usr/include/linux/netfilter_ipv4/ipt_TTL.h`. 

The issue has nothing to do with antivirus or the like, but is due to some silly behavior of the WSL file system, namely an inconsistency regarding case sensitiveness: when in some directory there is a file and you want to create in the same directory a further file with a name that is the same except for case, this fails, and even worse produces a misleading I/O error:

```
touch a.txt
touch A.txt
  touch: cannot touch 'A.txt': Input/output error
```

Here is a workaround for packages with names like `linux-libc-dev_4.4.0-97.120_amd64.deb`:

    cd any-temp-dir
    
    apt-get download linux-libc-dev
    ar x linux-libc-dev*deb
    tar xJf data.tar.xz # ignore all erors like ./usr/include/linux/netfilter_ipv4/ipt_ttl.h: Cannot open: Input/output error
    tar cJf data.tar.xz ./usr
    ar rcs linux-libc-dev*.deb debian-binary control.tar.gz data.tar.xz 
    
    dpkg -i linux-libc-dev*.deb

**Comment by PythonLover336** [comment]
I have a totally different problem, 404 URL not found.
Tried updating the system, but the same error kept popping up again.

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
