### ISSUE TITLE
Starting from java causes ubuntu wait for input

### ISSUE THREAD

**Issue by hurricup** [Microsoft/WSL#2592]
```
Microsoft Windows [Version 10.0.16299.19]
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

Following example shoud start `ubuntu run env`, echo output and quit. However, `ubuntu.exe` waiting for input. 
Changing ProcessBuilder constructor params to just `env` will launch local `env` command, echo and quit as expected.

```java
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;

public class UbuntuHang {
  public static void main(String[] args) throws IOException, InterruptedException {
    ProcessBuilder builder = new ProcessBuilder("ubuntu", "run", "env");
    Process process = builder.start();

    try (BufferedReader in = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
      String s;
      while ((s = in.readLine()) != null) {
        System.out.println(s);
      }
    }

    System.exit(process.waitFor());
  }
}
```
Same behavior with legacy bash.exe

**Comment by Brian-Perkins** [comment]
There were some interop stdout/stderr fixes in the last couple of builds. Could you try build 17025 and see if this works better for you now?

**Comment by hurricup** [comment]
Have no access to machine with insider atm. Any chance this gonna make it to release soon? Kinda hotfix maybe?

**Comment by riartem** [comment]
Very need that hotfix! Hope for a quick solution.

**Comment by mhofman** [comment]
A hotfix is very much needed for this, WSL is of of beta so users shouldn't be required to run insider builds to get major fixes likes this.

It also sounds like this would be entirely userland, so no major risk for a windows update release.

**Comment by Muttsu** [comment]
@jstarks What is the build that fixed this issue?

**Comment by alexign** [comment]
Any news on that issue?

**Comment by therealkenc** [comment]
I don't have a Java environment handy to confirm, but this scenario should be better in 1803 aka 17134. If it isn't, please open a new issue#.

**Comment by throwable-one** [comment]
@therealkenc we reproduced it with C/Win32Api and C#/.NET.
the problem is when you redirect stdin for WSL2, it's handler never releases.
Please see my comments with apps to reproduce
https://github.com/microsoft/WSL/issues/4424
