### ISSUE TITLE
Unable to create files with same name (other than case)

### ISSUE THREAD

**Issue by wkbrd** [microsoft/WSL#2593]
Unable to create files with the same name other than case on computers that are within our corporate domain. Our IT department uses various security products made by Altiris and Sophos. Systems within our environment on developer networks where these tools are not installed and corporate GPOs are not in effect are able to create files differing only by case as expected.

* Your Windows build number:  10.0.16299.19 (was also a problem on Creators Update)

* What you're doing and what's happening:  
```
touch lower.txt
touch Lower.txt
touch: cannot touch 'Lower.txt': Input/output error
```

* What's wrong / what should be happening instead:
File should have been created without an error message.

* Strace of the failing command, if applicable:  
See [touch-trace.txt](https://github.com/Microsoft/BashOnWindows/files/1408039/touch-trace.txt)

**Comment by erkinalp** [comment]
This is a system-wide setting. You can full case sensitivity with a registry change, but only for whole OS.

**Comment by wkbrd** [comment]
Hi @erkinalp!  Can you share what registry entry you mention?

**Comment by erkinalp** [comment]
"HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\ dword:ObCaseInsensitive"=0
Source:
https://superuser.com/questions/266110/how-do-you-make-windows-7-fully-case-sensitive-with-respect-to-the-filesystem#answer-842670

**Comment by wkbrd** [comment]
This still reproduces with 10.0.16299.309.  Reproduces in multiple shells, including Ubuntu and SuSE.
