### ISSUE TITLE
Controlled Folder Access

### ISSUE THREAD

**Issue by jwhipp** [microsoft/WSL#2594]
Microsoft Windows [Version 10.0.16299.19]

When enabling controlled folder access and allowing bash.exe, the WSL environment is not able to access controlled folders.

Need a way to allow WSL to access controlled access folders/dirs or documentation on the subject. The controlled folder access only allows you to select executable files present on the Windows filesystem so it's unclear what you would "allow" here for the WSL to work with protected folders.

**Comment by joels94** [comment]
I tried using `nano` to edit a file inside protected folder and to my surprise I was able to edit and save the file even though I get a notification "Unauthorized changes blocked.." Now isn't that security risk? Does this mean any Linux based malwares can still access my files in protected folders?

**Comment by jwhipp** [comment]
You sure it wrote the file? I've tried with vim, touch, cp, etc.   When I protect a folder, WSL can't write to it even when I select the binary as an exclusion from the Ubuntu package in my home dir under AppData.

**Comment by joels94** [comment]
Microsoft Windows [Version 10.0.16299.19] - Fall Creators Update

I checked again. As you mentioned vim, touch and cp didn't work. 
With vim, I got "FSync failed".
With touch and cp, I got "No such file or directory".  
With nano, when creating new file, I got same error "No such file or directory".

However, when I create the file inside Controlled Folders in windows using Notepad. 
Then in WSL, using nano, I can successfully edit and save the file.
I can also view the updated file when I open again in Notepad.

**Comment by JadeMaveric** [comment]
Has there been any work done on this? I'd really like to get WSL working...

**Comment by philosophicles** [comment]
I just tried this. With each of `touch`, `vi` and `nano`, I got CFA-related errors (and alerts from the Windows Security system) on first attempt at writing new files, then everything worked subsequently. 

That's not ideal but not a show-stopper.

**Comment by Aduboahen** [comment]
Use the command it shouldn’t work, check controlled folder access settings and add it from recently blocked apps.

**Comment by Zweihander-Main** [comment]
In case it helps anyone, you can use Powershell (as Admin) to add exclusions manually. For example, for an emacs installation in a Debian WSL, you can use something like:
```
Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Users\USER\AppData\Local\Packages\TheDebianProject.DEBIANFOLDER\LocalState\rootfs\usr\local\bin\emacs-26.3" 
```
