### ISSUE TITLE
Bash history line numbers

### ISSUE THREAD

**Issue by ICasula** [Microsoft/WSL#2596]
Microsoft Windows [Versión 10.0.16299.19]

I updated to this version 2 days ago. Now when I try to recover some command from my bash history using the "up" key, i get something like this: 

"icasula@26-PC:~$   872  sudo apt-get dist-upgrade"

That 872 is some kind of line number that appeared in my .bash_history file. I know that, in some cases, it can appear reading that file, but that number should never show up using the "up" arrow.

This is a peek of my .bash_history file:

   39  ping 8.8.8.8
   40  ping 127.0.0.1
   41  sudo apt-get update
   42  ping 8.8.4.4
   43  ping 8.8.8.8

I tried to remove those line numbers but every time I do it and then close "bash" it shows up again, even duplicated, like this:

   39     39  ping 8.8.8.8
   40    40  ping 127.0.0.1
   41     41  sudo apt-get update
   42     42  ping 8.8.4.4
   43     43  ping 8.8.8.8

Can someone help me? It's really annoying and was working perfectly fine last week.
When I try to search for an old command using CTRL + R it also includes that line number, hence I cannot run it right away, but I'm forced to go to the start of the command and manually delete that number.

Thank you!

**Comment by Biswa96** [comment]
Delete the file with comand `rm .bash_history`

**Comment by ICasula** [comment]
If I delete it it appears again.

**Comment by therealkenc** [comment]
There wasn't enough to go on in this one for anyone to jump in I guess.
