### ISSUE TITLE
airmon-ng doesn't show laptop's WiFi adapter 

### ISSUE THREAD

**Issue by abaska** [Microsoft/WSL#2598]
It's a blessing that i can now run linux scripts and apps inside windows,
however it seems that every wifi related apps that i know doesn't work.
airmon-ng start / macchanger / airodump-ng / etc.
i ran all commands with "sudo" to get root access.
macchanger says unable to get permenant mac address.
airmon-ng doesn't show any wifi device, it just appears blank.
airodump-ng needs monitor mode to work which unfortunately doesn't work right now.

**Comment by abaska** [comment]
when i type ifconfig i get the wifi0 device but airmon doesn't show wifi0 for some odd reason.

**Comment by therealkenc** [comment]
#1077 ([message](https://github.com/Microsoft/WSL/issues/1077#issuecomment-296085572))
