### ISSUE TITLE
Lxss folder is not in the place (disappeared), but Ubuntu is working 

### ISSUE THREAD

**Issue by rivaros** [Microsoft/WSL#2599]
Cannot find the folder C:\Users\<my_username>\AppData\Local\Lxss any longer.
I show system hidden files and anything. Also cannot reach it by directly typing in Windows Explorer.

But nevertherless Ubuntu can be started and used fine. So looks weird. Did the location of fodler changed?

I am using Windows 10 16299.19 (upgrade install from Win7 preserving only user files).
Already did all possible DISM and scf checks.

**Comment by poizan42** [comment]
See #2578

**Comment by rivaros** [comment]
@poizan42 Thank you man
I upgraded one of my machines to fall edition and it preserved the old location. Then did new clean install - and already thought that something screwed up.
