### ISSUE TITLE
Jupyter notebook servers not being killed on window close

### ISSUE THREAD

**Issue by lauhayden** [Microsoft/WSL#2601]
I'm running Jupyter notebook servers (installed through Anaconda) on WSL. For the main part, this works, but when directly closing the Bash terminal window (as opposed to stopping the server via ctrl+c), the Jupyter server does not get killed - it continues to run in the background. This is different from the behaviour on both OSX and on Linux, where the server is killed as soon as the terminal window is closed. Only when all Bash terminal windows are closed (i.e. the WSL subsystem itself is killed), will the Jupyter server be stopped.

Windows build:
Version 10.0.16299.15

**Comment by therealkenc** [comment]
Sounds like #2496 which did not make FCU.

**Comment by Brian-Perkins** [comment]
I agree this sounds like #2496. If you have the opportunity to test build 17025 it should be easy to confirm if it also addresses this scenario.

**Comment by lauhayden** [comment]
Finally got around to testing this in build 17025 - confirmed that it addresses this scenario.
