### ISSUE TITLE
Symlink in windows mount does not translate to Windows junction

### ISSUE THREAD

**Issue by acepace** [Microsoft/WSL#2602]
* Your Windows build number: Microsoft Windows [Version 10.0.17017.1000]

* What you're doing and what's happening:  Installing a linux package that creates a symbolic link between two files on a NTFS mounted partition creates broken junction points.

Example
echo "aaa" > /mnt/c/temp/test
ln -s test test2

Trying to access test2 from cmd leads to the following error
type test2
The file cannot be accessed by the system.

* What's wrong / what should be happening instead: The data should be displayed. Since windows understands there's a junction point there.

**Comment by therealkenc** [comment]
#1475

**Comment by therealkenc** [comment]
The cool kids seem to be hanging out on #353 for this issue.

**Comment by Brian-Perkins** [comment]
Windows Insider Build 17046 contains some improvements for symlink compatibility. See the full description in the [release notes](https://github.com/MicrosoftDocs/WSL/releases/tag/17046)
