### ISSUE TITLE
WSL Release Notes Page Down?

### ISSUE THREAD

**Issue by MrObvious** [Microsoft/WSL#2604]
URL I usually use: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes
URL changes to: https://msdn.microsoft.com/en-us/commandline/wsl/release-notes.md

Gives me this:
We're sorry, the page you requested cannot be found.

 

The URL might be misspelled, or the page you're looking for is no longer available.

 

TIPS

 

If you entered the web address, check that it doesn't contain a typo.
Use the MSDN-specific search box at the top of the page to try to locate the page.
Check out the list of common destinations below.

**Comment by jack775544** [comment]
Works fine for me

**Comment by MrObvious** [comment]
Nevermind. Bad browser cache issue.
