### ISSUE TITLE
Screwed permissions on files edited on Windows (not inside WSL folder)

### ISSUE THREAD

**Issue by rivaros** [Microsoft/WSL#2605]
I have a project folder located in C:\PROJECTS with some code inside, and using SmartGit GUI to manage versioning on it (all on Windows).

Recently it was mapped into my WSL home folder (ln -s /mnt/c/PROJECTS ~/projects), so it's possible to run some bash scripts inside WSL.

After this strange things start happening with file permissions on C:\PROJECT.  Ended up with some files totaly unaccessible (cannot even change owner with local windows administrator). Folder cannot be deleted on Windows and also cannot be removed under WSL (rm -rf). It just stays there.

Solutions from here https://answers.microsoft.com/en-us/windows/forum/windows_8-security/you-do-not-have-permission-to-view-this-objects/5939dbf4-ca81-4f14-b455-ede115af924e?auth=1 do not work either.

**Comment by Biswa96** [comment]
Can you change the permission with chmod? As you open Git client in Windows then why did you create the symlink?

**Comment by ishraqiyun77** [comment]
I am having the same issues ever since the Fall Update was applied to my computer Tuesday. Can't install `pip` and `npm` packages on C:\ whereas I had zero issues before the update. Deleting files on the Windows side as admin sometimes results in "no permission". Pretty sure I read that link earlier trying to resolve the issue and it didn't help.

**Comment by ganeshkrishnan1** [comment]
Permission for files in /mnt cannot be changed via wsl. Copy them to ~ folder and change the permission there.

**Comment by DarthSpock** [comment]
> Permission for files in /mnt cannot be changed via wsl. Copy them to ~ folder and change the permission there.

They can be changed with the latest Insiders (therefore the upcoming release) using the `-o metadata` option on your mount points. See this WSL [blog](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/). There's also a `wsl.conf` to more easily configure this. See this [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/)

**Comment by therealkenc** [comment]
This issue died on the vine in an unspoken need-repro state. The OP here relates to something that worked in (presumably) Creator's Update but failed in (according to the second post) Fall Update. Whatever the problem, it might well be better post- [Chmod/Chown WSL Improvements](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/), or post- symlink improvement, or post- whatever improvements. If further problems are found with SmartGit GUI to manage versioning on all of it, please open a new issue with a CLI repro.

**Comment by rainabba** [comment]
Related? https://github.com/Microsoft/WSL/issues/1088#issuecomment-428636873
