### ISSUE TITLE
gdb watch point doesn't work

### ISSUE THREAD

**Issue by lili2012** [microsoft/WSL#2609]
using gdb to set watch point like this : watch \*(long\*)var, gdb prompts me I set watch point successfully. But the program won't stop when var value change. While Ubuntu doesn't have this problem. I think it is a WSL bug!

**Comment by PeterFeicht** [comment]
I encountered this as well just now...

GDB claims it has set a hardware watchpoint but it never triggers. In a VirtualBox VM the same watchpoint works fine.

**Comment by mcninja97** [comment]
I'm having problems with hardware and software watchpoints

**Comment by therealkenc** [comment]
This one got chirping crickets since last fall. If someone has the assembly-fu to work up a test case setting `DR*` that would be informative (I haven't looked at that stuff in a decade or more). I wonder idly if the problem is tangentially related to #2555 ([message](https://github.com/Microsoft/WSL/issues/2555#issuecomment-335657456)). Even if we got a trap, maybe we don't know WTF happened. With a good chance I am talking out of my butt.

I'd direct you to the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17133337-support-software-debugging-tools), but you know....

**Comment by lili2012** [comment]
I encounter this problem long before I post this issue and this is the main reason I can't use WSL. I hope it will be fixed by next year's windows update.

**Comment by therealkenc** [comment]
> I hope it will be fixed by next year's Windows 10 update.

Spring of 2019? Well we can always remain hopeful. Better to light a candle than to curse the darkness. 😉

**Comment by BullyWiiPlaza** [comment]
Please don't ignore this issue. Here is a related StackOverflow question:
https://stackoverflow.com/questions/51610452

**Comment by lili2012** [comment]
gdb watch point works now and I tried it in windows 10 1809 ubuntu 16.05. Thanks therealkenc!

**Comment by therealkenc** [comment]
Made me look, but watchpoints don't apear to take here on 18298.
```
#include <stdio.h>

int main(int argc, char **argv)
{
  int x = 30;
  int y = 10;

  x = y;

  return 0;
}
```

![image](https://user-images.githubusercontent.com/7049700/50184725-bed83300-02ca-11e9-8905-07ff58f52d1a.png)

That should have held up at `x=30` and `x=y`.

**Comment by lili2012** [comment]
I tried your code. not work. I tried my assignment it worked. 

![image](https://user-images.githubusercontent.com/14124820/50228745-a7409d80-03e3-11e9-8371-3265933e885b.png)

**Comment by lili2012** [comment]
I know they made a little progress so far. this issue will not be closed!

**Comment by lili2012** [comment]
cv point to a block of memory in the heap, so maybe watch point works for heap.

**Comment by kashperanto** [comment]
I also ran into this limitation using GDB within WSL Ubuntu 16.04.3 LTS, but I'm stuck on build 1709 at work.  Looks like I'll have to resort to breakpoints and manual watching.  Software watchpoints appear to work, but they are ridiculously slow.  Setting a watchpoint right before continuing into a READ() command (gfortran) took a solid minute to hit the variable that was read in by the command only 3 lines down.

**Comment by therealkenc** [comment]
Better in WSL2

![image](https://user-images.githubusercontent.com/7049700/89815721-1c517100-dafa-11ea-962f-4c271c882515.png)

**Comment by lili2012** [comment]
I tried it on my computer (windows 10 20H2 ubuntu 20.04) and and this issue remains and the same code work on virtual box ubuntu 20.04
