### ISSUE TITLE
`~/.bashrc` is no longer loaded automatically after moving my home directory

### ISSUE THREAD

**Issue by joe-askattest** [Microsoft/WSL#2612]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.19]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

 - I have changed my home address to `/mnt/c/Users/<my username>`.
 - My `.bashrc` file is located at `/mnt/c/Users/<my username>/.bashrc`.
 - When I open up a new bash it does not load my `.bashrc` file.

* What's wrong / what should be happening instead:

It should be loading my `.bashrc` file at `~/.bashrc`. It worked before updating Windows today.

To labour the point; the home directory contains a `.bashrc` file. You can get the home directory for a user using `eval echo ~$USER` and so running ```ls "`eval echo ~$USER`"/.bashrc``` shows that the file exists.

As a workaround:

 - After opening up `bash on Ubuntu on Windows`, and then manually run `bash` in the terminal, then it does get loaded correctly. 
 - Edit the `bash on Ubuntu on Windows` shortcut and add `--rcfile ~/.bashrc` to the end of the command. For example: `C:\Windows\System32\bash.exe ~ --rcfile ~/.bashrc`

**Comment by 0xbadfca11** [comment]
Before updating is build 15063 (Creators Update, version 1703), is not it?
Does ```~/.bash_profile``` or ```~/.bash_login```, that doesn't load ```~/.bashrc``` exist?
See https://github.com/Microsoft/WSL/issues/2067#issuecomment-299622057

**Comment by joe-askattest** [comment]
Previously it would source the `.bashrc` always when the terminal was opened. Now it does not.

`.bash_profile` is sourced so I can also add `source ~/.bashrc` from there.

**Comment by RajendrasinhParmar** [comment]
Facing the same issue.

**Comment by evancox10** [comment]
I also have the same problem. I changed my home directory to a symlink to /mt/c/Users/username , now .bashrc is not source on start up

**Comment by therealkenc** [comment]
```
$ sudo adduser newuser # new user to play with, creates in /home/newuser like your default
$ sudo cp -aR /home/newuser /mnt/c/Users/<you>
$ sudo echo "echo 'running bashrc'" >> /mnt/c/Users/<you>/newuser/.bashrc
$ sudo usermod -d /mnt/c/Users/<you>/newuser newuser
```
From Windows commandline:
```
C:\> ubuntu.exe config --default-user newuser
C:\> ubuntu.exe
```
You don't need to create a new user; you can do the above with your existing default. The above just illustrates getting your paths and perms correct.

exi

**Comment by zeroterminal** [comment]
@joe-askattest 
Thank you !
