### ISSUE TITLE
Will Windows Subsystem for Linux be switched on from start?

### ISSUE THREAD

**Issue by mobluse** [Microsoft/WSL#2616]
Microsoft Windows [Version 10.0.16299.19]

Will Windows Subsystem for Linux be switched on from start in future releases of Windows so you can install Ubuntu, openSUSE etc. from Store directly? Now, some organizations (e.g. a local university) allow installing apps from Store, but does not allow you to switch on WSL, and they don’t switch it on because there are too few that request it, because most students studying CS have their own laptops. They have Git Bash from git-scm.com, but that doesn’t include gcc, which I need. I have a 9″ laptop with Elementary OS Luna Linux, but I prefer using the much bigger screens of the university’s computers which have the latest Windows and Intel Core i7 processors.

**Comment by zadjii-msft** [comment]
@bitcrazed or @tara-raj might be able to comment more, but I don't think there any plans to have WSL be on by default.

**Comment by sunilmut** [comment]
@mobluse - Thanks for the input. There are no current plans to enable the WSL feature by default, for similar reasons you mention above; majority of the total Windows user base doesn't need it. If your school is able to provision Windows image, then they can do this be default. You might have to show them what they gain out of this, before they agree :).

**Comment by bitcrazed** [comment]
Hey @mobluse - we have no plans to pre-install WSL by default in standard Windows builds.

However, we are looking into how we can improve the enablement & acquisition process in future Windows releases.

Also, if your school is unwilling to enable WSL, you should be able to download & install gcc etc. onto any Windows machine as part of the [MinGW toolset](http://mingw.org/wiki/InstallationHOWTOforMinGW).

HTH.

**Comment by mobluse** [comment]
Microsoft Windows [Version 10.0.15063]

I could install Cygwin with GCC, Git and Python3 here at the local university with:
`setup-x86_64.exe --no-admin`
See https://www.cygwin.com/faq.html#faq.setup.noroot
But it would be easier and faster if I could use WSL and Ubuntu since I'm more used to Ubuntu and it has more packages that are easier to install.

**Comment by bitcrazed** [comment]
While WE (Microsoft) won't be installing WSL by default, there's nothing to stop a user / org-admin from creating & deploying a sysprepped desktop OS image with WSL pre-enabled!

**Comment by zhenruyan** [comment]
So how do I create an installation image that contains WSL, I tried to package it, but because of the WSL file naming problem, it caused an ESD error

**Comment by bitcrazed** [comment]
Please bear-with us; we're working on some stuff ;)

**Comment by bitcrazed** [comment]
@zhenruyan You can enable/disable the WSL feature itself using the following PowerShell command:

    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

If you enable WSL in your base image and then sysprep, it should remain selected when installed.

What ESD error are you seeing? /cc @tara-raj

**Comment by zhenruyan** [comment]
@bitcrazed   An ESD mirror is releasing an exception because of an incorrect character encoding

**Comment by bitcrazed** [comment]
Could you share specific error text?

**Comment by zhenruyan** [comment]
@bitcrazed   I'd love to, I'll try to reproduce the mistake
