### ISSUE TITLE
Question regarding relationship with upstream Ubuntu releases

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2617]
Can someone from the WSL team please comment on the exact nature of the relationship between WSL Ubuntu releases and upstream Ubuntu releases? Is there a commitment to remain in-step with the current Ubuntu generation or is Ubuntu 16.04 expected to be the WSL base install for some time? Are there any plans to upgrade to Ubuntu 17.04 LTS zesty at this time?

**Comment by Herst** [comment]
17.04 is not a LTS release but 18.04 will be.

**Comment by sunilmut** [comment]
We do try to keep the new store installations to a recent version of the distro. But, for existing installations, the users are expected to manage their distro versions just as they would on a native Linux installation.
