### ISSUE TITLE
Unknown Error for apt-check in WSL Ubuntu

### ISSUE THREAD

**Issue by jacoby** [Microsoft/WSL#2619]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17017.1000]

$ uname -a
Linux Lion 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

In apt-using distros, the command `/usr/lib/update-notifier/apt-check` is used to show the number of available updates and the number of available security updates, in STDERR and normally in 0;0 format, but there's a flag for human readable.

With WSL, I get
$ /usr/lib/update-notifier/apt-check 2>&1
E: Unknown Error: '<class 'PermissionError'>' ([Errno 1] Operation not permitted)

* What's wrong / what should be happening instead:

🔥 ✔ jacoby@oz 09:41 37°F No coffee ~ 
$ /usr/lib/update-notifier/apt-check
0;0

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

[strace.txt](https://github.com/Microsoft/WSL/files/1431250/strace.txt)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
```
getpriority(PRIO_PROCESS, 0)            = 20
setpriority(PRIO_PROCESS, 0, 19)        = -1 EACCES (Permission denied)
```
Same as #1838
