### ISSUE TITLE
ioncube encoder binaries did not work

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/WSL#2622]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.19]
WSL: Ubuntu 16.04.3 LTS

* What you're doing and what's happening: Trying to run ioncube encoder and make_license binaries. Steps:

  - download trial binaries from http://downloads3.ioncube.com/eval_download_packages/ioncube_encoder/linux_i686/en/ioncube_encoder_evaluation.tar.gz
  - extract `make_license`, `make_license_64`, `ioncube_encoder71_10.0` and `ioncube_encoder71_10.0_64`
  - try to exec from bash these scripts

* What's wrong / what should be happening instead: Should output help info or ask correct command line. Actual I have:

  - `make_license` = cannot execute binary file: Exec format error
  - `make_license_64` = Segmentation fault
  - `ioncube_encoder71_10.0` = cannot execute binary file: Exec format error
  - `ioncube_encoder71_10.0_64` = looks like work

* Strace of the failing command:  

> make_license:
```
execve("./make_license", ["./make_license"], [/* 13 vars */]) = -1 ENOEXEC (Exec format error)
write(2, "strace: exec: Exec format error\n", 32) = 32
exit_group(1)                           = ?
+++ exited with 1 +++
```
> make_license_64:
```
execve("./make_license_64", ["./make_license_64"], [/* 13 vars */]) = 0
uname({sysname="Linux", nodename="ADG-02", ...}) = 0
brk(NULL)                               = 0x1b6b000
brk(0x1b6c180)                          = 0x1b6c180
arch_prctl(ARCH_SET_FS, 0x1b6b860)      = 0
brk(0x1b8d180)                          = 0x1b8d180
brk(0x1b8e000)                          = 0x1b8e000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600400} ---
+++ killed by SIGSEGV (core dumped) +++ 
```
> ioncube_encoder71_10.0:
```
execve("./ioncube_encoder71_10.0", ["./ioncube_encoder71_10.0"], [/* 13 vars */]) = -1 ENOEXEC (Exec format error)
write(2, "strace: exec: Exec format error\n", 32) = 32
exit_group(1)                           = ?
+++ exited with 1 +++ 
```

**Comment by therealkenc** [comment]
`make_license` is #228

`make_license_64` is #1462
