### ISSUE TITLE
How to set "lxrun /setdefaultuser root" when I install WSL from Microsoft Store?

### ISSUE THREAD

**Issue by peaceshi** [Microsoft/WSL#2623]
Windows tell me that "lxrun" should be used to old version of WSL.
So how to set default user "root" now?

**Comment by onomatopellan** [comment]
Every distro has its rules. On Ubuntu now it would be `ubuntu.exe config --default-user root`
Type `ubuntu.exe /?` for more info.

**Comment by Biswa96** [comment]
Both run same binary from linux `/usr/sbin/adduser` and `/usr/sbin/addgroup`.

**Comment by peaceshi** [comment]
thanks everyone.
