### ISSUE TITLE
Postgresql issues a lot a warning when creating a database

### ISSUE THREAD

**Issue by espositofulvio** [Microsoft/WSL#2628]
**OS**: Windows 10 Home
**Build**: 16299.19
**WSL Linux Distro**: Ubuntu (installed from the Store)

Installed PostgreSQL 9.6, using the [timescale](https://www.timescale.com) repository, and tried to create a db from psql in a shell:

```bash
> psql -U postgres
psql (9.6.3)
Type "help" for help.

postgres=# CREATE DATABASE tutorial;
WARNING:  could not flush dirty data: Function not implemented
WARNING:  could not flush dirty data: Function not implemented
WARNING:  could not flush dirty data: Function not implemented
WARNING:  could not flush dirty data: Function not implemented
WARNING:  could not flush dirty data: Function not implemented
WARNING:  could not flush dirty data: Function not implemented
[...]
```
At the end the database is indeed created but I'm not sure everything will work correctly. Are there still issues running prostgres on WSL? Surprisingly I was running it before the last Fall creator update and didn't recall I had any of those warnings when creating databases (but I might recall wrong as usually I do it via pgAdmin). I tried to search other issues for similar things but everything seemed to suggest that a Windows build after 15025 should work fine without this warning? Is it a regression?

**Comment by therealkenc** [comment]
#645 ([message](https://github.com/Microsoft/WSL/issues/645#issuecomment-295276937))

**Comment by espositofulvio** [comment]
Wow, I didn't found that issue! Thanks a lot 👍

**Comment by dcayme** [comment]
Do anyone know if this issue will be fixed?
