### ISSUE TITLE
WSL's /etc/hosts isn't populated from system32/drivers/etc/hosts and servers in Windows hosts aren't visible to WSL

### ISSUE THREAD

**Issue by vadimkantorov** [Microsoft/WSL#2630]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Build 15063.674

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Pinging a server, named in system32/drivers/etc/hosts

* What's wrong / what should be happening instead:
Instead of using the server's IP from the Windows hosts, file, the ping attaches the nasty internet provider's DNS suffix. WSL's /etc/hosts doesn't contain the server listed in system32/drivers/etc/hosts

My first time using WSL. A quick search in issues didn't find this particular one, though other people seem to complain that the WSL's hosts file gets overwritten by Windows hosts file. For me, the servers from Windows hosts file aren't being known to WSL. Thanks!

**Comment by mateusmedeiros** [comment]
As per [this comment](https://github.com/Microsoft/WSL/issues/1495#issuecomment-299518081), this feature seems to have been added on the Fall Creators Update (the stable build is 16299), but it seems you're still on the Creators Update (build 15063).

**Comment by vadimkantorov** [comment]
Got it. Thanks!
