### ISSUE TITLE
Access packages installed in Ubuntu in Windows

### ISSUE THREAD

**Issue by skippednote** [Microsoft/WSL#2632]
_I'm sorry if I'm opening an already existing issue. I tried to find something similar but I failed._

I installed `node` on Ubuntu using `nvm` and it works fine there. However, I have VSCode installed on Windows. I also have a few node packages installed globally like eslint, prettier, etc. 

I'm trying to hook up `eslint` installed in Ubuntu with VSCode but it doesn't seem to be working. I tried updating the eslint nodepath but that doesn't work. Is this even possible? Should I just install `node` on Windows?

**Comment by razvan-panda** [comment]
@skippednote See: https://msdn.microsoft.com/en-us/commandline/wsl/interop?f=255&MSPPError=-2147217396

**Comment by therealkenc** [comment]
Keep an eye on the [useWSL flag](https://code.visualstudio.com/updates/v1_17#_first-steps-towards-wsl-support) and [VSCode#25033](https://github.com/Microsoft/vscode/issues/25033) too (but it's early).

**Comment by therealkenc** [comment]
You'll probably get better service on this one over in the [VS Code Community](https://code.visualstudio.com/community). There is a WSL actionable on this one, and if you find answers about VS Code or eslint here it would be by luck not design. Perfectly good question though.

**Comment by duttaditya18** [comment]
Really want this to work. I have my whole setup going in wsl and use VSCode. But I can't get Linting on my Node.js code.

Has anyone figured this out yet?
