### ISSUE TITLE
CDROM device available?

### ISSUE THREAD

**Issue by res0nat0r** [Microsoft/WSL#2633]
Thanks to the latest build I'm able to mount my cdrom like:

`mount -t drvfs f: /mnt/f`

Is it possible to access this via a device in /dev? I'm looking to use cdparaonia/abcde to rip my cd's but don't have access to the raw /dev device.

**Comment by therealkenc** [comment]
#689 et al

**Comment by res0nat0r** [comment]
Thanks!
