### ISSUE TITLE
Error 0x80070422 when starting Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by ptopalis** [microsoft/WSL#2637]
[lxcore_files.zip](https://github.com/Microsoft/WSL/files/1446053/lxcore_files.zip)

**Comment by ibbyvk** [comment]
Yep, me too with Debian GNU/Linux.

**Comment by benhillis** [comment]
0x80070422 is service disabled, please make sure the "Lxss Manager" service is not set to disabled.
