### ISSUE TITLE
Loop when trying to create a shortcut on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by carpben** [Microsoft/WSL#2638]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

I just tried to create a shortcut to my project folder. It creates a loop, and does not represent the actual folder. The bug can best be understood by looking and comparing both screenshots. 
![image](https://user-images.githubusercontent.com/13496178/32445564-ceffcdbc-c30e-11e7-94ef-a11d62a9d900.png)
![image](https://user-images.githubusercontent.com/13496178/32445718-5a0de52e-c30f-11e7-9540-3164842bc51f.png)

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.16299.19

**Comment by Biswa96** [comment]
Use `/home` in destination of that symbolic link.
