### ISSUE TITLE
Backspace = CTRL+Backspace?

### ISSUE THREAD

**Issue by andb0t** [Microsoft/WSL#2639]
> * Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.19]

> * What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am running zshell on WSL where I bind widgets to key combinations with `bindkey <combination> <function>`. All kinds of [CTRL, ALT]+[anykey] combinations work fine but for anykey = Backspace. I tried to find the escape sequence but
  * Using `CTRL+v` to check what they are bound to shows no output for it
  * Using `sed -n l` shows nothing as well, except that it deletes one char of any other previously tried combination, just as one would naively expect from a backspace stroke.

Using `bindkey '^?' backward-delete-word` I manage to bind the regular Backspace stroke to deleting a full word, but this is of course not what I want since I loose the single char deletion this way. The usual shell way of hitting CTRL+w to delete backwars-delete a full word works, but I would like to bind it to CTRL+Backspace since this is what I'm used to in most other editors. Is there any way how I can achieve this? Could I somehow map the CTRL+W key to CTRL+Backspace?

> * What's wrong / what should be happening instead:

I would have expected to be able to bind the backspace key in a similar fashion as all the other keys

**Comment by zadjii-msft** [comment]
Oh this is related to #2350.

On the backlog for this next release :)

**Comment by andb0t** [comment]
> Oh this is related to #2350.
Thanks for spotting this and sorry for the dup! Looking forward to seeing this solved! Keep up the good work!
