### ISSUE TITLE
Random npm intall issues

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/WSL#2640]
* Your Windows build number:  Microsoft Windows [Version 10.0.17025.1000]

* What you're doing and what's happening:  Various npm i commands in an project.

* What's wrong / what should be happening instead: I get a failure at the end.

![image](https://user-images.githubusercontent.com/393660/32465113-fa680b38-c307-11e7-9943-12060890519f.png)

Note that this is random, and repeating the command normally works.

* Strace of the failing command, if applicable:  As I can't repeat this consistently, not sure this will work.

As an FYI, this behavior seems to have started with the last big update. I think I've seen it before that, but it seems much worse now.

**Comment by cfjedimaster** [comment]
So in this project, I've done 3 or 4 more npm installs since the bug occurred that have worked fine. Now another one failed. 

![image](https://user-images.githubusercontent.com/393660/32466163-9ac2449c-c30b-11e7-918b-87b6a3d13787.png)

Ran the command again and it worked.

**Comment by onomatopellan** [comment]
Make sure it's not the same as #2448. There is a workaround available.

**Comment by cfjedimaster** [comment]
I'll try - thanks. I hope this is fixed soon. It's made me dread typing npm.

**Comment by sunilmut** [comment]
Closing this out as duplicate. If the issue still persists on the build with the fix, we can reopen.
