### ISSUE TITLE
st_size of symlink on DrvFs wrong to 0

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#2641]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17025.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```sh
$ cd /mnt/c/some/where
$ ln -s anywhere a
$ stat a -c %s
0
```
* What's wrong / what should be happening instead:
Will shown 0.
stat(2) defines ```The size of a symbolic link is the length of the pathname it contains, without a terminating null byte.```.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

**Comment by jstarks** [comment]
Yes, we discovered this internally as well. @SvenGroot is working on a fix.

**Comment by SvenGroot** [comment]
This has been fixed internally, and will be making its way to an insider build in the near future.

**Comment by jstarks** [comment]
This should be fixed in [insider build 17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes).

**Comment by 0xbadfca11** [comment]
Confirmed.
