### ISSUE TITLE
bash.exe/ubuntu.exe does not terminate when called from php, python, java or C++

### ISSUE THREAD

**Issue by sz5000** [Microsoft/WSL#2642]
Invoking e.g. bash.exe -c ls within a cmd.exe Console works like a charm and does terminate the bash command, but invoking this command from PHP, python, java or C++ results in an hanging process. The output of the ls command appers, but after that the proces does not terminate. 

This worked before the last Windows Update to the version shown below. What could this be and how can this problem be fixed?

The test under c++ with CreateProcess prints: Fehler: 0x80070057

After excecuting _ls_ in _bash_, I can see two running _init_ processes and one running _ls_ process in the task manager which terminates, when I close the application which starts the command.

**My windows Version:**
`X64, Windows 10, Version 1709 Build 16299.19`

**With PHP:**
`system('ubuntu.exe -c ls');`

**With Java:**
```
final Process p = Runtime.getRuntime().exec(new String[] {
	"ubuntu.exe", "-c", "ls"
});
while(true) {
	try {
		Thread.sleep(1000);
	} catch (InterruptedException e) {
	}
	System.out.println(p.isAlive());
}
```

**With C++:**
```
PROCESS_INFORMATION pi = {0};

SECURITY_ATTRIBUTES attribs = { 0 };
attribs.bInheritHandle = TRUE;

HANDLE hread, hwrite;
CreatePipe(&hread, &hwrite, &attribs, 2048);

STARTUPINFO	StartupInfo = { 0 };
StartupInfo.cb = sizeof(STARTUPINFO);
StartupInfo.dwFlags = STARTF_USESHOWWINDOW | STARTF_USESTDHANDLES;
StartupInfo.wShowWindow = SW_SHOW;
StartupInfo.hStdOutput = hwrite;
StartupInfo.hStdError = hwrite;

ZString cmd = L"ubuntu.exe -c \"ls\"";

if (!CreateProcess(NULL, (TCHAR*) cmd.toCStr(), NULL, NULL, TRUE, CREATE_UNICODE_ENVIRONMENT, NULL, NULL, &StartupInfo, &pi)) {
	printf("Error: %x\n", GetLastError());
	return 0;
}

BYTE buffer[2048];
HANDLE hw = GetStdHandle(STD_OUTPUT_HANDLE);
DWORD bytesRead, bytesWritten;
while (ReadFile(hread, buffer, 2048, &bytesRead, NULL)) {
	WriteFile(hw, buffer, bytesRead, &bytesWritten, NULL);
}
```

**Comment by sz5000** [comment]
Windwos Build 17025 seems to fix this issues on my PC.

**Comment by hurricup** [comment]
Guess it's #2592

**Comment by sz5000** [comment]
Seems to be. Can be do something to fix this issue in the Windows Build 16299?

**Comment by Biswa96** [comment]
Did you try to call the [`WslLaunchInteractive`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826869(v=vs.85).aspx) function from wslapi.dll to start `/bin/bash`? I can terminate it with C# but can't C++.
