### ISSUE TITLE
Kernel driver build fails under /mnt/c/Users with "Input/output error"

### ISSUE THREAD

**Issue by ctuffli** [Microsoft/WSL#2644]
Building a kernel driver will fail when done under `/mnt/c/foo` but the same build does not fail when done under `~/foo`.

To setup, install the following:
```
sudo apt-get intall build-essentials
sudo apt-get install linux-headers-4.4.0-75
sudo apt-get install gcc-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
sudo update-alternatives --config gcc
```
Extract the attached tar-ball (`tar xf khello.tar.gz`) and build (see below).

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.19]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
$ pwd
/mnt/c/Users/User/khello
$ make KVER=4.4.0-75-generic
make -C /lib/modules/4.4.0-75-generic/build M=/mnt/c/Users/User/khello modules
make[1]: Entering directory `/usr/src/linux-headers-4.4.0-75-generic'
  CC [M]  /mnt/c/Users/User/khello/khello.o
  CC [M]  /mnt/c/Users/User/khello/kbye.o
/mnt/c/Users/User/khello/kbye.o: Input/output error
/mnt/c/Users/User/khello/kbye.o: failed
make[2]: *** [/mnt/c/Users/User/khello/kbye.o] Error 1
make[1]: *** [_module_/mnt/c/Users/User/khello] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-4.4.0-75-generic'
make: *** [all] Error 2
```
* What's wrong / what should be happening instead:
```
$ pwd
/home/user/dev/khello
$ make KVER=4.4.0-75-generic
make -C /lib/modules/4.4.0-75-generic/build M=/home/user/dev/khello modules
make[1]: Entering directory `/usr/src/linux-headers-4.4.0-75-generic'
  CC [M]  /home/user/dev/khello/khello.o
  CC [M]  /home/user/dev/khello/kbye.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /home/user/dev/khello/kbye.mod.o
  LD [M]  /home/user/dev/khello/kbye.ko
  CC      /home/user/dev/khello/khello.mod.o
  LD [M]  /home/user/dev/khello/khello.ko
make[1]: Leaving directory `/usr/src/linux-headers-4.4.0-75-generic'
```
* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Running `strace -o strace.txt -ff make KVER=4.4.0-75-generic` produces 327 files. Posting them here seems problematic ...

**Comment by ctuffli** [comment]
[khello.tar.gz](https://github.com/Microsoft/WSL/files/1455490/khello.tar.gz)

**Comment by therealkenc** [comment]
Yeah the current `strace` guidance is problematic. Use `strace -ff KVER=4.4.0-75-generic 2> khello.strace`. Possibly (probably) #2593 and friends. Let us know if "same filename different case" rings a bell in your scenario; if so the `strace` probably isn't strictly necessary but never hurts either.

**Comment by ctuffli** [comment]
Thanks @therealkenc, that was a good suggestion. The strace output contains the following:
```
$ grep EIO khello.strace
[pid 15717] rename("/mnt/c/Users/User/khello/kbye.o.rc", "/mnt/c/Users/User/khello/kbye.o") = -1 EIO (Input/output error)
```
So, not a "same name, different case", but it only modifies the file extension. The full strace output is large, but I can try emailing it to secure@microsoft.com if that is useful.

**Comment by ctuffli** [comment]
Curiously, a simple case using rename() is fine:

```
$ touch foo.o.rc
$ strace rename 's/\.rc$//' /mnt/c/Users/User/khello/foo.o.rc 2> rename.strace
$ grep rename rename.strace
execve("/usr/bin/rename", ["rename", "s/\\.rc$//", "/mnt/c/Users/User/khello/foo.o.r"...], [/* 16 vars */]) = 0
open("/usr/bin/rename", O_RDONLY)       = 3
rename("/mnt/c/Users/User/khello/foo.o.rc", "/mnt/c/Users/User/khello/foo.o") = 0
```

**Comment by therealkenc** [comment]
Thanks for the follow-up. You could `gzip` the `strace` output and attach it to a [gist](https://gist.github.com/). Or just link a gist with the couple thousand lines that has _any snowballs chance_ of really being related. Or glance up from the fail point yourself and see what activity is happening on `.../khello/...` that is different than a bog-straightforward `rename(1)`. 

If you are feeling highly motivated that is. Best evidence is that this is an introduced regression, and there will be a pending (for some value of pending) fix. I have an Internet nickle that says #2593 will flip and this will too. You've already posted a repro; which is great, thanks. You really ought to be doing this kind of build on DrvFs (`/home`) anyway, which will save you all manner of grief overall. If you need to do active development editing, use Sublime on VcXsrv. Or, that's what I do, anyway.

**Comment by ctuffli** [comment]
After updating to version 
    Microsoft Windows [Version 10.0.17134.48]
this appears to work in both the simplified case posted here as well as my real-world issue.
