### ISSUE TITLE
Ubuntu 17.10 issues with Locale's 

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/WSL#2646]
after upgrading wsl to ubuntu 17.10 several unfixable error's have been plaguing the terminal. 
 perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = ""en_US.UTF-8""
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = ""en_US.UTF-8""
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

**Comment by heldchen** [comment]
see https://github.com/Microsoft/WSL/issues/1878#issuecomment-294203566 for a temporary workaround until this known problem is fixed. after unzipping, regenerate the locale.

```
sudo gunzip --keep /usr/share/i18n/charmaps/UTF-8.gz
sudo dpkg-reconfigure --frontend=noninteractive locales
```

**Comment by kenshen112** [comment]
That works for now :)
