### ISSUE TITLE
Nginx can't access local drive /mnt

### ISSUE THREAD

**Issue by markbratanov** [Microsoft/WSL#2647]
I am trying to set up a dev environment where I can edit my files on my local machine while WSL runs as a dev server. 

While configuring my site root on Nginx, I receive a 403 in the browser, and the following error message in the error logs:

`2017/11/09 17:24:24 [error] 762#762: *4 directory index of "/mnt/c/Users/mark/Documents/Nix/lms/" is forbidden, client: 127.0.0.1, server: lms.local, request: "GET / HTTP/1.1", host: "lms.local"`

Is there a way to modify the permissions of that folder to add WSL?

Any help would be appreciated.

**Comment by snobu** [comment]
Same problem if you point to something more permission friendly like a `c:\something`?

**Comment by Line117** [comment]
I do not know the answer, just advise you to do this:
/var/www/site.loc/ (site.loc is symlink to windows folder /mnt/c/web/site.loc

**Comment by therealkenc** [comment]
This would get into Nginx configuration weeds real fast, but long story short you'd get the same error on a 777 root:root path on Real Linux too. Or in a VM with a Windows share. If the symlink trick works, great (thanks @Line117), but you are setting yourself up for a lot of unnecessary grief with the approach. Which is not to imply it isn't doable; but the best place to find advice would be with Nginx configuration experts, which don't necessarily hang out here.

**Comment by Line117** [comment]
> but you are setting yourself up for a lot of unnecessary grief with the approach
Not any "unnecessary grief". Absolutely.
You using linux path in linux, and windows path in windows.
