### ISSUE TITLE
kernel headers

### ISSUE THREAD

**Issue by mahmoodn** [Microsoft/WSL#2649]
Hi,
I see some topics in this github regarding the *-Microsoft kernel package which is not available in the apt repository.

```
root@DESKTOP-3PC1SHI:/# uname -r
4.4.0-43-Microsoft
root@DESKTOP-3PC1SHI:/# apt-get install linux-headers-4.4.0-43
linux-headers-4.4.0-43             linux-headers-4.4.0-43-generic     linux-headers-4.4.0-43-lowlatency

```

However, I didn't fully conclude what is the issue and if that is possible or not. Can someone help me?

**Comment by therealkenc** [comment]
That's #2363. What is the "that" in "if that is possible" you are looking for? There is no Linux kernel in WSL (but you know that already). If you are looking for the headers (say for API constants) you've found them. Let us know what you are trying to do and we can try to help.

**Comment by mahmoodn** [comment]
I want to install the cuda toolkit and it requires the kernel source

**Comment by therealkenc** [comment]
#327. [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support).

**Comment by jstarks** [comment]
Right, please vote on the user voice for CUDA support. Thanks!
