### ISSUE TITLE
.bash_profile called instead of .bashrc after running 'bash' from powershell

### ISSUE THREAD

**Issue by Naadwo** [microsoft/WSL#2650]
I've read other (similar) issues but this seems to be something else. First I thought that is is feature - but after investigation it looks more like a bug. 

* Your Windows build number:  
   * Version with issue: Microsoft Windows [Version 10.0.16299.15] 
   * Version working properly Microsoft Windows [Version 10.0.15063]
   * **Both were installed version 1709 (with issue) was installed not upgraded from previous one.**

* What you're doing and what's happening: I'm starting bash from powershell (or any other way)
   * Previously:
      * running _bash_, caused including .barshrc (the same from bash)
      * running _bash -l_, caused including .bash_profile (the same from bash)
   * Now:
      * running both commands from powershell causes including .bashprofile
      * running same commands from bash works fine
* What's wrong / what should be happening instead: 
   * When running _bash_ from powershell (or cmd, or menu start) wrong file is included

* Extra information
   * On both machines I have exactly the same version of bash ( 4.3.48(1)-release )

**Comment by onomatopellan** [comment]
I think that was discussed here #816

**Comment by Owdaan** [comment]
It is probably, I have overlooked it. But now both .profile and .bashrc are never loaded (no matter if -l is added), I doubt if that is really feature, rather a bug..

**Comment by benhillis** [comment]
We've refined this behavior, will be available in an Insider Dev build soon.
