### ISSUE TITLE
Compilation of OpenModelica is failing after upgrading WSL

### ISSUE THREAD

**Issue by lochel** [microsoft/WSL#2651]
I try to build [OpenModelica]( https://openmodelica.org/) on a clean WSL installation (Ubuntu 16.04, Microsoft Windows [Version 10.0.16299.19]). [Here](https://openmodelica.org/download/download-linux) is a description of how to install all build dependencies.
The build procedure can be configured using the following commands:
```
> git clone https://openmodelica.org/git-readonly/OpenModelica.git
> cd OpenModelica
> git submodule update --init --recursive libraries testsuite OMCompiler common
> autoconf
> ./configure CC=clang CXX=clang++
```

Then the actual build process can be triggered using this command: `make -j8`.

The make command is failing at random stages of the build procedure and often even failing with a Windows blue screen. [I noticed blue screens only if running make with multiple jobs.]

This is extremely disappointing since everything worked fine using the WSL beta version and Ubuntu 14.04.

**Comment by benhillis** [comment]
I suspect this has been resolved - please reopen if you still hit this on 19042 or newer.

**Comment by lochel** [comment]
Yes, it has been resolved :+1:
