### ISSUE TITLE
Upgrading the WSL without upgrading Windows build

### ISSUE THREAD

**Issue by OmriSama** [Microsoft/WSL#2654]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
14393

Is it possible to upgrade WSL and Bash on Windows without upgrading to the latest build of Windows? Just wondering; I'd prefer not to if possible.

**Comment by therealkenc** [comment]
WSL is Windows. `lxcore.sys` and `lxss.sys` are kernel drivers, not unlike `ntfs.sys` or `tcpip.sys`. So short answer, no.

**Comment by OmriSama** [comment]
Thanks dude!

**Comment by Biswa96** [comment]
@OmriSama Are you taking about upgrading the Ubuntu UserSpace or the Linux driver (lxss.sys and lxcore.sys) i.e Linux compatibility layer?
