### ISSUE TITLE
command not found: getopt

### ISSUE THREAD

**Issue by thecodejunkie** [microsoft/WSL#2655]
Not sure if this should be filled here on WSL or the oh-my-zsh/wd repositories, but since it works fine on a MBP and against a WSL folder I thought I'd start here

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.19]

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have `oh-my-zsh` installed and try to use the [wd](https://github.com/mfaerevaag/wd) plugin.

If I create a warp directory against a path inside WSL, for example

- `cd ~/projects/code`
- `wd add code`

And then try to warp to it when I'm at some other location

- `cd ~`
- `wd code`

then I end up in the `~/projects/code` folder as expect

However if I add a warp directory to a path that is on a mounted windows 10 drive

- `cd /mnt/d/some/folder`
- `wd foo`

And try to warp to it from some other location

- `cd ~`
- `wd foo`

Then it crashes and pretty much requires me to restart my session for the terminal to function properly

* What's wrong / what should be happening instead:

The error message I am seeing is

```
/home/myusername/.oh-my-zsh/plugins/wd/wd.sh:382: command not found: getopt
wd_print_usage:2: command not found: cat
prompt_status:5: command not found: wc`
```

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

**Comment by agross** [comment]
```sh
$ which getopt
/usr/bin/getopt
$ getopt --version
getopt from util-linux 2.27.1
$ apt search util-linux
Sorting... Done
Full Text Search... Done
mingetty/xenial 1.08-2 amd64
  Console-only getty

python-unshare/xenial 0.1-3 amd64
  Python bindings for the Linux unshare() syscall

util-linux/xenial-updates,now 2.27.1-6ubuntu3.3 amd64 [installed]
  miscellaneous system utilities

util-linux-locales/xenial-updates 2.27.1-6ubuntu3.3 all
  locales files for util-linux
```

**Comment by thecodejunkie** [comment]
@agross seeing the same

```
$ which getopt
/usr/bin/getopt

$ getopt --version
getopt from util-linux 2.27.1

$ apt search util-linux
Sorting... Done
Full Text Search... Done
mingetty/xenial 1.08-2 amd64
  Console-only getty

python-unshare/xenial 0.1-3 amd64
  Python bindings for the Linux unshare() syscall

util-linux/xenial-updates,now 2.27.1-6ubuntu3.3 amd64 [installed]
  miscellaneous system utilities

util-linux-locales/xenial-updates 2.27.1-6ubuntu3.3 all
  locales files for util-linux
```

**Comment by agross** [comment]
If `getopt` wasn't found by script, then I guess something is messing with your `$PATH`. I couldn't find anything related to it in `wd` itself, though. It probably helps to `set -x` inside `wd` and probably also to print the `$PATH` right before `getopt` is called.
