### ISSUE TITLE
firebase via node unusably slow only on WSL

### ISSUE THREAD

**Issue by dontsave** [microsoft/WSL#2657]
[win ver 10.0.16299.19 running Ubuntu Xenial installed from the windows store]

I was following this quick getting started tutorial with Firebase/Firestore for Node JS:
https://firebase.google.com/docs/firestore/quickstart?authuser=0 

and noticed that queries to the database were painfully slow specifically in WSL, but not in Windows Node (both versions of node are the same: 8.9) or in a native Ubuntu Node environment

Steps:
initialize the app for your own server:

```
const admin = require('firebase-admin');

var serviceAccount = require("path/to/serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

var db = admin.firestore();
```

this requires installing firebase-admin to communicate with a firestore database. 

then run a very simple example query:

```
var docRef = db.collection('users').doc('alovelace');

var setAda = docRef.set({
    first: 'Ada',
    last: 'Lovelace',
    born: 1815
});
```

this takes around 20 seconds in my WSL environment. In Windows node and native Ubuntu node it is instantaneous. Executing the same query in the web browser version of the tutorial, as opposed to the node version, in WSL runs instantaneously. Maybe this slowness might be due to the apparent dependency on grpc by firebase-admin-node? I can't find any WSL issues mentioning grpc, but would there be any reason grpc would run much slower in WSL than elsewhere?

**Comment by nicobrinkkemper** [comment]
Yes, I  ditched WSL2 for powershell. After running `firebase serve` in WSL it takes multiple seconds just to send a request back and forth. File downloads/uploads take even longer. I wouldn't advice running the emulators in WSL.

**Comment by craigloewen-msft** [comment]
@nicobrinkkemper was your project stored in your Windows drive? WSL2 has faster file system performance than WSL 1 as long as you are running inside of your Linux root file system. Check our [docs page](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#place-your-linux-files-in-your-linux-root-file-system) for more info. 

@dontsave in general this seems related to file system performance in WSL1, which we're tracking on issue https://github.com/microsoft/WSL/issues/873. [WSL2](https://aka.ms/wsl2) is aimed at fixing this issue.

**Comment by yoannes** [comment]
Old and closed issue, but I'll leave my comment. 

After removing `firebase-tools` from windows and installing only on WSL2 everything worked like a charm.
