### ISSUE TITLE
Debugging with visual code using `"useWSL":true`, works the first time, but hangs on the next run

### ISSUE THREAD

**Issue by alanosman** [microsoft/WSL#2662]
I recently tried out the new feature `"useWSL":true` for debugging Node applications through Visual Code, but using WSL bash session.  It all works perfectly the first time, but after you stop debugging (by clicking stop in the debugger), the process that was launched in WSL to run node is not terminated.  The workaround is to find the offending node process using `ps -ef` and terminate it.  

Subsequent attempts at rerunning the debugger without terminating the process result in duplicate processes being started, and if you are working on a web app, blocking of ports.

* Windows build number:  Version 10.0.16299.19

**Comment by benhillis** [comment]
Have you tried this recently? I know the VSCode stuff has changed a lot since this was filed.

**Comment by alanosman** [comment]
@benhillis I have not had this issue since. Though to be honest, I have been out of coding this last few months.  Thanks for checking!

**Comment by benhillis** [comment]
@alanosman - thanks! Doing a bit of spring cleaning on our GitHub...
