### ISSUE TITLE
we very very need support for 32 bit executables!

### ISSUE THREAD

**Issue by imagecser** [Microsoft/WSL#2663]
Windows build number:  10.0.17035.1000
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

we very very need support for 32 bit executables!
I really wonder when the great WSL can make it 'cause we can't WAIT for it any more!

**Comment by Biswa96** [comment]
Many distribution now does not or will not release 32 bit os. Why did you want 32 bit support?

**Comment by jstarks** [comment]
Thanks for the feedback. This is covered by #711.

You can also vote here on this feature: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel.

**Comment by imagecser** [comment]
sorry but i'm still a student. WSL is really convenient and i really like it. Howevet
r, when we learn the course, ICS, we need to run the 32 bit executables to learn what happened to the computer.
