### ISSUE TITLE
Need help making mDNS work

### ISSUE THREAD

**Issue by anohren** [microsoft/WSL#2664]
I can't figure out how to do it. I can't ssh into my .local address because it can't resolve the name.

I also have this unanswered question on Superuser: 
https://superuser.com/q/1262998/36197

I've followed the last example in this thread:

[https://github.com/Microsoft/WSL/issues/384][1]

In other words:

    ~$ sudo service dbus start
     * Starting system message bus dbus                                                                                                                    [ OK ]
    ~$ sudo service avahi-daemon start
     * Starting Avahi mDNS/DNS-SD Daemon avahi-daemon                                                                                                      [ OK ]
    ~$ avahi-resolve --name rpi.local
    Failed to resolve host name 'rpi.local': Timeout reached

This was done after installing the packages listed [in this answer][2].

`rpi.local`can be resolved by Windows.

Windows 10 Version	10.0.16299 build 16299

`~$ lsb_release -a`

    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:        16.04
    Codename:       xenial

  [1]: https://github.com/Microsoft/WSL/issues/384
  [2]: https://superuser.com/a/1218685/36197

**Comment by therealkenc** [comment]
#384 says `SO_REUSEPORT` was stubbed, but it isn't immediately obvious to me whether stubbing `SO_REUSEPORT` would address the problem. Windows _already has_ a service listening on 5353. You fired up another service on the same port under WSL, but that doesn't mean the WSL service is going to get the request. Maybe someone out there could confirm they have actually got `avahi-daemon` running satisfactorily, because #384 technically only [says](https://github.com/Microsoft/WSL/issues/384#issuecomment-320132942) the `Protocol not available` error was squashed, not that `avahi-daemon` actually does what people are expecting.

I could be talking out of my butt. Haven't tried it. But essentially you've set up (in principal) a load-balanced mDNS with two services on your box, and tilts my head to the left. YRMV.

**Comment by anohren** [comment]
Ok, I see. I was led to believe that these lines from #384 was an indication that avahi was doing something useful:

```
:~# avahi-resolve-address 192.168.0.52
192.168.0.52    xxxxx.corp.microsoft.com
```

**Comment by therealkenc** [comment]
To be clear, I don't specifically know that it _isn't_ doing something useful. I just did a `netstat.exe -na | find "5353"` and know Windows is already there; which is "unusual" compared to what would be the case on a Real Linux box. My November post was fishing for someone to say "yep avahi-daemon is working great on WSL here", in which case we could wander down the path of figuring out why it is working for them but not you. It was more of a question than a statement.

If you are feeling motivated you can try posting a concise CLI repro from clean Ubuntu / unadulterated Windows and see if you get a bite.

**Comment by anohren** [comment]
Thanks for the clarification

**Comment by OhMeadhbh** [comment]
please see https://github.com/Microsoft/WSL/issues/384 for a concise CLI repro from WSL and native Ubuntu.

**Comment by n3dst4** [comment]
I see #384 has been closed but this is still a problem for me. I don't mind *how* mDNS gets resolved in WSL, I just care that it *should*. 

Here are ground-up repro steps to make the problem clear:

1. Set up a computer on your network running actual Ubuntu. Let's it `bunty`. 🐧
2. Make sure avahi-daemon in installed: `sudo apt install avahi-daemon`
3. Make sure avahi-daemon is started: `sudo systemctl start avahi-daemon.service`
4. Test that this ubuntu box can resolve its own mDNS name: `ping bunty.local`
5. For extra certainty, run `avahi-browse -a` to get a list of all the local mDNS info. It should contain `bunty` somewhere. 
4. Go to a Windows box with WSL installed. 🗔
5. Open a CMD prompt and enter `ping bunty.local`
6. You should see it pinging the IP address of the Ubuntu box from step 1, indicating that Windows 10's built-in mDNS resolution is working 👌
7. Now pop open a WSL prompt and enter the same command `ping bunty.local`

Expected: it should be able to resolve the name like everything else on the network ✨
Actual: it has no clue 😢

**Comment by n3dst4** [comment]
@anohren I had that too, but it turned out I had my work VPN up at the time and it was finding a  r`aspberrypi.local` on the office LAN. Any chance you were doing something similar?

**Comment by n3dst4** [comment]
@anohren Windows VPN, no idea what crazy network config they had but it was making their .local addresses resolvable over regular DNS. I was just throwing that out there because there's no way a .local address should be resolvable over the public internet.

**Comment by Coder-256** [comment]
This is still an issue on Windows 1903.

**Comment by strarsis** [comment]
+1! System `ping` in `cmd.exe` resolves correctly, but in WSL either with `System error` (when some unsupported resolver is used in `/etc/nsswitch.conf; hosts`) or just not being able to resolve.

**Comment by hovissimo** [comment]
Still not working in Version 10.0.17763 Build 17763

**Comment by daler-rahimov** [comment]
not working on winver 19041.1

**Comment by ma2shita** [comment]
Wrote how to use powershell.exe. It is not cool, but worked.
I pray for COOL improvements.
https://github.com/microsoft/WSL/issues/384#issuecomment-571566111

**Comment by therealkenc** [comment]
Ref #3365 `avahi-daemon` is better on WSL2

**Comment by nnp19111990** [comment]
Hello Guys,
I am running the below command on my one of the board having custom linux OS ,
**avahi-daemon --file=/system/etc/avahi/avahi-daemon.conf&**
the avahi-daemon started on my board and I am able to ping the Host Name on one of the windows PC available with me , using commnad ping **Ingenic.local**
The only issue is i am not able to see the host name on bonjour application(add-on) running on Internet Explorer.
what is missing?

**Comment by dlamblin** [comment]
Well, the m in mDNS is multicast... And I noticed there's comment in WSL2 docs about mirrored networking mode allowing multicast to work. Maybe that's what you want? https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking ; I didn't really check if it is, but I was searching why a zeroconf name wasn't working for a host on a WSL2 instance, and this old closed issue came up and later I found that mirrored mode addressed my issue, so I thought there may be others reading this with a similar situation.

**Comment by zekageri** [comment]
I also have mdns problems in 2025.
WSL can't resolve mdns names but I can ping the ip addresses of my local devices.

- Windows 10 Pro 10.0.19045 N/A Build
- Ubuntu 24.04.1 LTS
- WSL 2..4.12.0
- WSL Kernel 5.15.167.4-1

Any solution to this?
