### ISSUE TITLE
Copy and paste no longer works in WSL -  as of 11/9

### ISSUE THREAD

**Issue by neovaldivia** [Microsoft/WSL#2667]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
version 10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Copy and paste is not working in any console drive app: WSL, cmd, GitBash

* What's wrong / what should be happening instead:
I have tried hotkeys (enabled in Properties/Quick Edit mode), With no result at all
I have tried using the menu at the title bar, with no result.
Copy and paste work for all other GUI apps but not in console, it does produce any result.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
There is no command to run so I can't provide a strace

**Comment by jstarks** [comment]
@bitcrazed This sounds like a console issue, not a WSL issue specifically. Can you help?

**Comment by zadjii-msft** [comment]
Does copying text from somewhere, then pasting with right-click work in cmd, powershell, or bash? How about Shift-Insert?

Can you paste a screenshot of both the cmd and wsl properties sheet, on the "Options" tab? It should look like this:
![image](https://user-images.githubusercontent.com/18356694/32906372-8f79abf4-cab1-11e7-9d45-c987f56eb8c9.png)


Ctrl-V to paste *never* worked in WSL/bash, but I want to figure out what scenarios exactly do/don't work.

**Comment by neovaldivia** [comment]
hey,
I found the issue is due to a incompatibility with Chrome for all console driven tools in the above Win version.
Current Chrome version: Version 62.0.3202.94 (Official Build) (64-bit)

Restarting chrome (killing all processes) allows to do all the Copy+Paste commands by design in each tool.

cheers

**Comment by bitcrazed** [comment]
@neovaldivia Also, Windows Console does not support pasting into a Linux distro using CTRL + V - this is something we're working on fixing, but we're confused as to how this is suddenly working for you, if you ARE running Windows Console.

Are you running a 3rd party terminal/console app?

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#74
