### ISSUE TITLE
bash.exe change target distro.

### ISSUE THREAD

**Issue by ProIcons** [Microsoft/WSL#2668]
Hello today i uninstalled from lxss the ubuntu distro. And installed both openSUSE and Ubuntu from Microsoft store. Running bash tho, from System32, points to openSUSE's Bash. Is there any way changing this behavior? Maybe selecting to which distro should the bash.exe points to?

**Comment by therealkenc** [comment]
[`wslconfig`](https://msdn.microsoft.com/en-us/commandline/wsl/wsl-config)

**Comment by ProIcons** [comment]
Thanks, that's what i was looking for.
