### ISSUE TITLE
Automount/AutoFS Not Working

### ISSUE THREAD

**Issue by MrObvious** [Microsoft/WSL#267]
root@PSTEJSKA1-PC:/var/run# automount
automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.

**Comment by russalex** [comment]
Thanks for the feedback.  We do not support mount in general at this time.  This will extend over to Autofs.  Suggestion here would be to file feedback over at our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to help us prioritize what we tackle in the future.
