### ISSUE TITLE
E: Unable to locate package libc6-dev-amd64

### ISSUE THREAD

**Issue by leisiji** [Microsoft/WSL#2671]
Window ver:
Microsoft Windows [Version 10.0.16299.19]
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS
Release: 16.04
Codename: xenial

When I try "apt-get install vim git libc6-dev-amd64", the system cannot install libc6-dev.
The bash shows me:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libc6-dev-amd64

**Comment by onomatopellan** [comment]
on Xenial it's called libc6-dev
https://packages.ubuntu.com/xenial-updates/amd64/libc6-dev/filelist

**Comment by onomatopellan** [comment]
https://packages.ubuntu.com/xenial/libc6-dev-amd64

It seems libc6-dev-amd64 is needed only in a 32bit system. WSL is 64bit only.

**Comment by therealkenc** [comment]
> It seems libc6-dev-amd64 is needed only in a 32bit system.

...~~needed~~ available...

Like [this](https://unix.stackexchange.com/questions/316178/why-cant-i-install-libc6-dev-amd64-using-the-official-online-repositories). I would cite #228 and the rest, but here you're actually _asking_ for `libc6-dev` targeting arch amd64. Which is just `apt install libc6-dev`.
