### ISSUE TITLE
WSL docker volumes - file change not working

### ISSUE THREAD

**Issue by efortes** [Microsoft/WSL#2672]
**Windows build number**: Microsoft Windows [Version 10.0.16299.19]
 
I use docker on  WSL and use the client to connect to the windows 10 docker (`export DOCKER_HOST='tcp://0.0.0.0:2375'`).

On native ubuntu i'm able to run an application inside docker and mount my nodejs project to the docker container as a volume. When I change a file on my host computer the docker container gets a file update notification and the files can be refreshed with tools like nodemon ( https://www.npmjs.com/package/nodemon )

When I use WSL docker is not aware of the file changes. How can this be fixed?

**Comment by jstarks** [comment]
I believe this is an issue with Docker for Windows, not with WSL. Docker for Windows does not support filesystem notifications when running Linux containers; this is true whether you are using WSL or regular Windows as the Docker client.

See https://github.com/docker/for-win/issues/56.
