### ISSUE TITLE
bash.exe hangs when piping output to Windows applications

### ISSUE THREAD

**Issue by ardevd** [Microsoft/WSL#2673]
* Windows build number: Version 10.0.16299.19

After upgrading to Windows 10 Fall Creators Update my [GitWrap ](https://github.com/ardevd/gitwrap)app has issues when used with other software such as IDE's, etc.

Put it simply, GitWrap simply acts as a wrapper for git in WSL and hence mimics the behavior of Git.exe. I can have Android Studio use GitWrap.exe as its git binary and when Android Studio does a "GitWrap.exe pull" GitWrap will call bash.exe -c "git pull" and write the result to the console. 

This worked perfectly fine with previous versions of WSL but after installing the Fall Creators Update the Process (bash.exe) never exits when Android Studio executes GitWrap. GitWrap just hangs on WaitForExit(). However, it still works fine from cmd which baffles me a bit. However, I have done troubleshooting with multiple versions of IDEA based IDE's and the issue is consistent across versions so the problem here must be WSL.

[Here](https://github.com/ardevd/gitwrap/blob/master/GitWrap/GitWrap/Program.cs) is the relevant code.

**Comment by ardevd** [comment]
Is this possibly a duplicate of #2592?

**Comment by hurricup** [comment]
Guess it is. You may add a temporary hack to your wrapper. Just close the pipe from wrapper to bash after process start. Should work. As far as I know there is no interactivity with git client.
