### ISSUE TITLE
Very slow go build

### ISSUE THREAD

**Issue by radu-matei** [Microsoft/WSL#2674]
Windows version: Microsoft Windows [Version 10.0.16299.19]
Go version: go version go1.9.2 linux/amd64

`go build ` takes significantly more time to complete on WSL compared to the same Go version on Windows.

Not sure if it relates to any of the other issues, thought might be useful to share here.

Thanks!

**Comment by therealkenc** [comment]
No strace but surely #1671 ([message](https://github.com/Microsoft/WSL/issues/1671#issuecomment-281205425))

**Comment by jstarks** [comment]
Yes, this is either that bug or a filesystem performance problem, both of which are known issues. I think we can close this for now.
