### ISSUE TITLE
error creating virtual interface - RTNETLINK answers: Permission denied

### ISSUE THREAD

**Issue by kbron** [microsoft/WSL#2675]
.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17035.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
cmd: ip link add jumo0 link eth0 address 94:cc:b9:82:4a:73 type b
response: RTNETLINK answers: Permission denied

* What's wrong / what should be happening instead:
I should have permission, right?

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

execve("/sbin/ip", ["ip", "link", "add", "jumo0", "link", "eth0", "address", "94:cc:b9:82:4a:73", "type", "bridge"], [/* 14 vars */]) = 0
brk(NULL)                               = 0x146f000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbc8ceb0000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=69353, ...}) = 0
mmap(NULL, 69353, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbc8ce9f000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14608, ...}) = 0
mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbc8c9f0000
mprotect(0x7fbc8c9f3000, 2093056, PROT_NONE) = 0
mmap(0x7fbc8cbf2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fbc8cbf2000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbc8c620000
mprotect(0x7fbc8c7e0000, 2097152, PROT_NONE) = 0
mmap(0x7fbc8c9e0000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7fbc8c9e0000
mmap(0x7fbc8c9e6000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbc8c9e6000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbc8ce90000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbc8ce80000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbc8ce70000
arch_prctl(ARCH_SET_FS, 0x7fbc8ce80700) = 0
mprotect(0x7fbc8c9e0000, 16384, PROT_READ) = 0
mprotect(0x7fbc8cbf2000, 4096, PROT_READ) = 0
mprotect(0x656000, 4096, PROT_READ)     = 0
mprotect(0x7fbc8ce25000, 4096, PROT_READ) = 0
munmap(0x7fbc8ce9f000, 69353)           = 0
socket(PF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 3
setsockopt(3, SOL_SOCKET, SO_SNDBUF, [32768], 4) = 0
setsockopt(3, SOL_SOCKET, SO_RCVBUF, [1048576], 4) = 0
bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
getsockname(3, {sa_family=AF_NETLINK, pid=14653, groups=00000000}, [12]) = 0
time(NULL)                              = 1510787325
sendto(3, " \0\0\0\20\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32, 0, NULL, 0) = 32
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"4\0\0\0\2\0\0\0\0\0\0\0=9\0\0\355\377\377\377 \0\0\0\20\0\5\0\0\0\0\0"..., 16384}], msg_controllen=0, msg_flags=0}, 0) = 52
access("/proc/net", R_OK)               = 0
access("/proc/net/unix", R_OK)          = -1 ENOENT (No such file or directory)
socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="jumo0"}) = -1 ENODEV (No such device)
close(4)                                = 0
socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="eth0", }) = 0
close(4)                                = 0
brk(NULL)                               = 0x146f000
brk(0x1490000)                          = 0x1490000
open("/usr/lib/ip/link_bridge.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
sendmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"P\0\0\0\20\0\5\6\376\310\fZ\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 80}], msg_controllen=0, msg_flags=0}, 0) = 80
recvmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"d\0\0\0\2\0\0\0\376\310\fZ=9\0\0\363\377\377\377P\0\0\0\20\0\5\6\376\310\fZ"..., 32768}], msg_controllen=0, msg_flags=0}, 0) = 100
write(2, "RTNETLINK answers: Permission de"..., 37) = 37
exit_group(2)                           = ?
+++ exited with 2 +++

**Comment by Brian-Perkins** [comment]
First note that the support here is currently very limited, so unless your scenario is very basic you will likely run into other blockers shortly. With that caveat in place: this request is proxied to equivalent Windows functionality which requires elevation (and root/sudo within WSL).

**Comment by Brian-Perkins** [comment]
So you will just need to make sure you launch the Windows app (Ubuntu.exe, et al) elevated. You can do this by right-clicking it and selecting "Run as Administrator" or you can hold Ctrl-Shift down while you click on it.

**Comment by kbron** [comment]
good, that was it
thank you

**Comment by kbron** [comment]
now I´m having trouble running dhclient on this new created vlan

```
cmd: sudo dhclient jumo0 -v  (i´m running bash as admin)
response: 

Internet Systems Consortium DHCP Client 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

socket: Address family not supported by protocol - make sure
CONFIG_PACKET (Packet socket) and CONFIG_FILTER
(Socket Filtering) are enabled in your kernel
configuration!

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.
```


#########################################

how to enable that?
socket: Address family not supported by protocol - make sure
CONFIG_PACKET (Packet socket) and CONFIG_FILTER
(Socket Filtering) are enabled in your kernel configuration!

**Comment by eric-gitta-moore** [comment]
same here.
WSL2, Docker Desktop, https://github.com/lukaszlach/docker-tc

```log
Starting Docker Traffic Control 18.12

[https://github.com/lukaszlach/docker-tc⁠](https://github.com/lukaszlach/docker-tc)


[2025-06-03T17:12:31+00:00] [7a7ecd6f5826] Set delay=100ms, loss=50%, corrupt=10%, duplicate=50% on vethd6255d5

RTNETLINK answers: No such file or directory
```
