### ISSUE TITLE
Microsoft-Windows-Subsystem-Linux Feature enable failed.

### ISSUE THREAD

**Issue by calmzealA** [Microsoft/WSL#2676]
Following this article:
[https://msdn.microsoft.com/en-us/commandline/wsl/install-win10](url)

But i get a error:

`
PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
`
Enable-WindowsOptionalFeature : 参数错误。
所在位置 行:1 字符: 1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

`
PS C:\Windows\system32> dism /Online /Enable-Feature /All  /FeatureName:Microsoft-Windows-Subsystem-Linux
`

部署映像服务和管理工具
版本: 10.0.14393.0

映像版本: 10.0.14393.0

启用一个或多个功能
[==========================100.0%==========================]

错误: 87

处理命令时出错。
确保命令行参数有效。有关详细信息，请查看日志文件。

可以在 C:\Windows\Logs\DISM\dism.log 上找到 DISM 日志文件

The log file has sent to secure@microsoft.com;

OS is win 10 professional x64 (1607), build 14393.953.

**Comment by Biswa96** [comment]
Did you enable developer mode?

**Comment by calmzealA** [comment]
@Biswa96 Thank you for reply . I did enable developer mode.

Finally i solved it by updating OS to build 15063.726.

**Comment by Biswa96** [comment]
Why not update to 1709 Fall CU? It has more features.
