### ISSUE TITLE
rsync: rsync_xal_set: lsetxattr(...,"security.selinux") failed: Operation not supported (95)

### ISSUE THREAD

**Issue by JackieKu** [microsoft/WSL#2677]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

17025
With clean installation of Ubuntu from the Store.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Use rsync to fetch files that contains "security.selinux" xattr (SELinux).
`rsync rsync://nexus9/r/sdcard/Download/ ./  -aX -sxzPF --inplace --numeric-ids`

On the WSL side rsync failed to set "security.selinux" xattr with the following error messages.
> rsync: rsync_xal_set: lsetxattr(...,"security.selinux") failed: Operation not supported (95)

* What's wrong / what should be happening instead:

It should work without errors, the xattrs should be copied and preserved.
The release notes of Build 16226 says this should have been supported.
Note I don't expect SELinux to be functional in WSL, but it should allow the data to be stored without problems.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

[rsync-strace.txt](https://github.com/Microsoft/WSL/files/1477257/rsync-strace.txt)

**Comment by jstarks** [comment]
@SvenGroot, is this expected?

**Comment by benhillis** [comment]
@jstarks - yes. Only a few attributes in the security namespace are implemented and this is not one of them.

**Comment by rbalint** [comment]
@benhillis It would be really helpful to have a list of implemented attributes with the Windows build numbers they were introduced in.
At the moment https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-root.tar.xz needs to be repacked removing system.posix_acl_* attributes to let install.tar.gz register successfully.

**Comment by benhillis** [comment]
@rbalint - Build 16237 added some initial xattr support, no other support has been added since then. However, none of the attributes in the system namespace are currently supported (only security.capability is fully supported).

**Comment by therealkenc** [comment]
> to be repacked removing system.posix_acl_* attributes to let install.tar.gz register successfully

Balint when you say "repacked" do you mean you un-`tar` it with `--no-xattrs` and then `tar` it back up without `--xattrs` (say piped), or is the repackaging more elaborate and involve other steps to work-around the missing attributes? This is a different way of asking, if `lxsetattr()` no-opped on unknown attributes (read: ignored fails) would that be equivalent to your repackaging process. I have a glibc shim in the can that works around various missing WSL surface to make stuff run, but my `bsdtar` is static.

**Comment by benhillis** [comment]
@therealkenc - I believe his issue is that the base tar.gz contains system namespace attributes, and when the distro is installed our bsdtar attempts to write the attributes, which fails and makes bsdtar return a non-zero exit code.

**Comment by therealkenc** [comment]
Yes exactly, I know (all too well). I am asking Balint if me stubbing out the fail in is sufficient, or necessary but insufficient. [Subtext being my trees are installed with a [static tar](https://gist.github.com/therealkenc/10b2f8dd5c7a8b08e74a4f4a889be3dd)]

**Comment by therealkenc** [comment]
> We ... keep it simple

Thanks for the details, appreciated.

> AFAIK that would only help going forward and not with older Windows builds

Good point. Depends on whether one continues to use MSFT's internal bsdtar on those older builds, or do it another way, 'spose [inside voice]. But yeah, understand. I think (?) you run into the same kind of problem even if you were armed with a helpfully documented table of supported xattrs versus build number though. Assuming you want to want to continue supporting (say) pre-16237. Conversely, if (hypothetically) you decided to start bumping the minimum target version supported, it wouldn't matter.
