### ISSUE TITLE
Visual bells do not work

### ISSUE THREAD

**Issue by yoctozepto** [Microsoft/WSL#2678]
As mentioned in #715 - visual bells do not work - the terminal does not blink.

### How to reproduce?

Enable visual bells either in bash:
`set bell-style visible`
in
`~/.inputrc`
or vim:
`set visualbell`
in
`~/.vimrc`
and execute any action triggering a bell (e.g. walking past the buffer).

The terminal should blink but it does not.

### Extra info

Sound bells do work (the beeping) when enabled (by default).

This functionality is useful for people disabling sounds and still hoping to get some feedback that they are doing something wrong. :-)

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#72
