### ISSUE TITLE
Bash processes executed in parent directory and not in current directory when following symlink

### ISSUE THREAD

**Issue by akehir** [microsoft/WSL#2679]
If I follow a symlink from the linux home dir to a directory on the Windows file system, any processes spawned in that bash will not be executed in the correct directory, but in a parent directory.

* Your Windows build number:  
Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  
Processes (git, npm install, ls, etc) are executed in the parent directory of the current directory.

Error can be shown by executing pwd and ls / ls . in the same directory:

`
akehir@DESKTOP-FR6I5LL:~/ake/repository$ pwd
/home/akehir/ake/repository

akehir@DESKTOP-FR6I5LL:~/ake/repository$ ls
nvm  package-lock.json  repository  viu
`

I changed to the dir by creating a symlink (ln -s ) from ~/ake to /mnt/c/ake:
`
akehir@DESKTOP-FR6I5LL:~$ ls -ll
total 0
lrwxrwxrwx 1 akehir akehir 11 Nov 17 09:53 ake -> /mnt/c/ake/
`

![image](https://user-images.githubusercontent.com/1078202/32942740-2b887ede-cb8a-11e7-879c-d31185ed605c.png)

* What's wrong / what should be happening instead:
Processes should not be executed in parent folder of current folder. The symlink from ~/ake/ to /mnt/c/ake/ is broken, and following it (cd ~/ake screws up the bash directory.

**Comment by therealkenc** [comment]
> Microsoft Windows [Version 10.0.14393]

#650. This was addressed in 14905 and you are on 14393. Fall Creators Update (16299) was released recently. Please give that a try.
