### ISSUE TITLE
Light red (color 12) text is rendered in white (color 15) in the Command Prompt window

### ISSUE THREAD

**Issue by color12** [Microsoft/WSL#2681]
I mistakenly posted this in the wrong forum, but I don't know how to delete the post:
  
Running the following program in a Command Prompt (on Windows 10 Home) outputs "LIGHT RED ( 12 )" in a white color instead of the expected light red color:

```
#include <windows.h>
#include <stdio.h>

int main(int argc, char* argv[])
{
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), 12);
	printf("LIGHT RED ( 12 )\n");

        return 0;
}
```

Text is displayed in the other 15 colors as expected.

How might the mapping have changed?  Is there some way to reset it so that color 12 will be light red again?

**Comment by jstarks** [comment]
@zadjii-msft Can you help for this console issue?

**Comment by zadjii-msft** [comment]
@color12 can you post a screenshot of your console properties sheet? Specifically the "Colors" tab?

![image](https://user-images.githubusercontent.com/18356694/33035168-0b7b9778-cddf-11e7-919e-2cdba8537938.png)

![image](https://user-images.githubusercontent.com/18356694/33035172-11946ffe-cddf-11e7-80b3-c3e9b5cbe679.png)

The properties sheet is super finnicky, so it's very possible that by trying to change another color's value, you may have accidentally changed the value of LIGHT_RED by mistake.

**Comment by color12** [comment]
Thanks, that was the problem.  I had set the RGB values for the Screen Text while the color 12 square was selected in the palette.

**Comment by zadjii-msft** [comment]
@color12 yep, that'll do it. It really sucks how easily that is to do accidentally, but it's unfortunately *really* hard to fix. 

Glad we could solve your problem!
