### ISSUE TITLE
How to install WSL into other disk?

### ISSUE THREAD

**Issue by Ferouden** [Microsoft/WSL#2682]
I don't want it be installed at %localappdata%\Packages.

In the past I could mount it to a VHD file, but now I can't.

So what should I do to manage it?

**Comment by therealkenc** [comment]
#449

**Comment by Biswa96** [comment]
@Ferouden you can easily do that with [WslRegisterDistribution](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826870(v=vs.85).aspx) function. Make a executable with that and you can install it anywhere. The installed path is saved in registry  path `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}` and registry key is REG_SZ `BasePath`.

**Comment by Ferouden** [comment]
@therealkenc I have read that, and every method invovled in that issue I tried is no use.

**Comment by Ferouden** [comment]
@Biswa96 I found a Tool is written with method you explained. [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline). 
And it works. THX.

**Comment by Biswa96** [comment]
Ya, I know `Directory.Move()` method does that. Also you may do that manually as I said.
I'm contributing to that repo. You may see wiki page of LxRunOffline to install many distros.
You may close this issue if your problem was solved.
