### ISSUE TITLE
WSL symlinks can be seen by Windows file explorer, but cannot be seen/opened by VS Code / Notepad++

### ISSUE THREAD

**Issue by davecan** [Microsoft/WSL#2683]
**NOTE:** After submitting this I found other issues regarding symlink visibility, namely #353 which was updated in the past few weeks. If this is being dealt with under it then please close this issue and I apologize for the spam. (I cannot delete this issue)

Ran into this odd situation while working through a JS dev environment tutorial from Pluralsight. I just installed WSL last night. This issue is unlike the red-text warning against modifying Linux files, as all of these files are in the `/mnt/...` path i.e. they are in the Windows filesystem shared with WSL.

Basically, running a package install command in node under WSL in the folder `/mnt/f/Development/jsdevenv/bash` resulted in the creation of some symlinks that are visible to WSL and to the Windows file explorer, but are invisible to and cannot be opened by VS Code and Notepad++ on the Windows side. VS Code's file browser shows the folder is empty, but selecting "Reveal in Explorer" opens a new file explorer window showing the files exist.

**Windows build number:** 10.0.14393 (Win10 Home)

**To Reproduce:**

1. Installed WSL.
2. Installed node and npm under WSL.
3. Copied [this package.json file](https://gist.github.com/coryhouse/29bd1029b623beb4c7f79b748dcba844) into my new project root.
4. Ran `npm install` in the project root under WSL.
5. `node_modules` folder is created and populated with downloaded libraries from the `package.json` file, and the subfolders and files all appear to be visible/openable in VS Code/etc. with one exception.....

**Expected Behavior:** `node_modules\.bin` is populated by the `npm install` command, links in this folder are visible in Windows (e.g. in VS Code, file explorer, etc), and can be opened/edited/etc in Windows.

**Actual Behavior:** `node_modules\.bin` folder is empty in VS Code, but the link files appear correctly under WSL as a simple `ls` command verifies. Checking the folder in Windows file explorer shows the files are there, but attempting to open the files with VS Code or Notepad++ returns an error stating the files do not exist.

**Comment by therealkenc** [comment]
Yeah this is #353 and #1475. No worries.
