### ISSUE TITLE
Errors when starting/stopping apport service (missing /proc/sys entries)

### ISSUE THREAD

**Issue by firewave** [Microsoft/WSL#2686]
I am using 1709 (OS Build 16299.64) with Ubuntu 16.04.3.

Starting/stopping gives some errors since some entries in /proc/sys are missing.

```
service apport start
 * Starting automatic crash report generation: apport
chmod: changing permissions of '/var/crash': Operation not permitted
/etc/init.d/apport: 53: /etc/init.d/apport: cannot create /proc/sys/kernel/core_pattern: Operation not permitted
/etc/init.d/apport: 54: /etc/init.d/apport: cannot create /proc/sys/fs/suid_dumpable: Operation not permitted
                                                                                                                 [fail]
```

The /var/crash error disappears when starting the service with sudo (not sure if that is expected - don't have a real Ubuntu system to test with at the moment)

```
sudo service apport stop
 * Stopping automatic crash report generation: apport
/etc/init.d/apport: 68: /etc/init.d/apport: cannot create /proc/sys/fs/suid_dumpable: Operation not permitted
                                                                                                                 [ OK ]
```

**Comment by firewave** [comment]
The missing /proc/sys/kernel/core_pattern is already tracked via #2408.

**Comment by therealkenc** [comment]
Yeah the earliest is #1262. Going to keep the requests together since core dump related infrastructure pretty much has to be done as a set. If it ends up being the case that some core dump features are implemented piece-wise we can do narrow entries later.
