### ISSUE TITLE
Bash error on launch: Error: 0x80070005 Press any key to continue...

### ISSUE THREAD

**Issue by jtbarker** [microsoft/WSL#2687]
[lxcore_adss.zip](https://github.com/Microsoft/WSL/files/1492231/lxcore_adss.zip)

**Comment by Biswa96** [comment]
Try both `wsl.exe` and `bash.exe` to launch Linux terminal.

**Comment by jtbarker** [comment]
Same error for both swl.exe and bash.exe @Biswa96

**Comment by Biswa96** [comment]
That specific error `0x80070005` means _General access denied_. Try to run those with administrator priviledge. Did you install distribution correctly? Or uninstall and reinstall it.

**Comment by jtbarker** [comment]
Strangely when I launch Bash on Windows from Microsoft Store (already installed), it works fine.  Still have the error when starting from the start menu.

**Comment by jtbarker** [comment]
@Biswa96 uninstall/reinstall did not resolve the issue.

**Comment by rparolin** [comment]
The Windows Linux Subsystem throws an error under cmder/ConEmu. In a regular console bash.exe runs correctly.

![image](https://user-images.githubusercontent.com/1320845/35012761-c4b23cc6-fabf-11e7-9713-e3e4047ca8fe.png)

![image](https://user-images.githubusercontent.com/1320845/35012776-cd7f8e26-fabf-11e7-9a89-68d454fd7db0.png)

I originally reported the issue to the Conemu list.
https://github.com/Maximus5/ConEmu/issues/1394

**Comment by carlsagan21** [comment]
Same problem here. Any advance?

**Comment by Biswa96** [comment]
Launch it as administrator.
