### ISSUE TITLE
Yarn and NPM installation takes more than 20 minutes on WSL.

### ISSUE THREAD

**Issue by awidjaja** [Microsoft/WSL#2695]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

> Microsoft Windows [Version 10.0.15063] 64-bit
CPU Intel i7, 4 cores, 4GB RAM 

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

```
$ yarn global list
Done in 1403.72s.

$ yarn global add eslint-config-airbnb
Done in 1710.22s.
```

* What's wrong / what should be happening instead:

> It is more than 5 times longer than if the same command was directly run on windows (which took less than 5 mins).

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

> No system trace available. 
Additional info: the directory is on a separate partition of the same SSD (/mnt/d/...)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by jstarks** [comment]
It would be good to compare with FCU2 (10.0.16299) to see if there is any improvement.

**Comment by awidjaja** [comment]
@jstarks 

Thank you...I have installed the Windows Creator update and the result is amazing...

```
$ yarn global list
Done in 233.34s.
( from 1403.72s)

$ yarn global add eslint-config-airbnb
Done in 211.64s.
(from 1710.22s)
```

**Comment by jstarks** [comment]
Great! Glad to hear it.

**Comment by spences10** [comment]
I'm having a similar issue:

* Microsoft Windows [Version 10.0.16299.98]

Although, I tried running the same commands as OP and got:
```
⟩ yarn global list
Done in 0.06s.

⟩ yarn global add eslint-config-airbnb
Done in 0.84s.
```

🙃 

I run those commands in an empty folder, however it was taking a really long time yesterday evening:

![image](https://user-images.githubusercontent.com/234708/33793145-9c4feaaa-dca9-11e7-93b3-4aad381b53fd.png)

![image](https://user-images.githubusercontent.com/234708/33793149-aa314178-dca9-11e7-9288-93e54193ac54.png)

![image](https://user-images.githubusercontent.com/234708/33793154-bc433be6-dca9-11e7-9d0f-98d89e3a4647.png)

# BUT

I ran `yarn` on the same project this morning and it completed in 15 seconds.

Let me know if you want any more information from me.

One thing I did notice from yesterday whilst waiting for yarn to finish was that there was barely any disk IO, this morning it showed some activity - could it be hardware related and not WSL??


Thanks

**Comment by awidjaja** [comment]
Not particularly sure, it seems in my case yarn always re-download and re-linking all dependencies but at least now the speed is comparable to npm.

**Comment by awidjaja** [comment]
yarn is ok now with latest version of WSL
