### ISSUE TITLE
WslRegisterDistribution Returns ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ProIcons** [Microsoft/WSL#2696]
Microsoft Windows [Version 10.0.16299.64]

So i was experimenting with C#, importing native wslapi.dll (executing it in x64 bit)

```csharp
        public enum HRESULT : uint
        {
            S_OK = 0x00000000,
            E_ABORT = 0x80004004,
            ERROR_ALREADY_EXISTS = 0x000000B7,
            ERROR_FILE_NOT_FOUND = 0x80070002,
            E_NOTIMPL = 0x80004001,
            E_INVALIDARG = 0x80070057,
            E_FAIL = 0x80004005
        }

        [DllImport("c:\\windows\\system32\\wslapi.dll", CharSet = CharSet.Unicode)]
        public static extern HRESULT WslRegisterDistribution(String distName, String fileName);

        [DllImport("c:\\windows\\system32\\wslapi.dll", CharSet = CharSet.Unicode)]
        public static extern HRESULT WslUnregisterDistribution(String distName);

        [DllImport("c:\\windows\\system32\\wslapi.dll", CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool WslIsDistributionRegistered(String distName);
```

And i found the rootfs of centos, through the https://github.com/RoliSoft/WSL-Distribution-Switcher
it was compressed in "xz" format, so through my ubuntu i extracted it

`tar -xf rootfs_centos_latest.tar.xz -C rootfs`

and then compressed it to gz

```bash
cd rootfs/
tar -czvf ../rootfs_centos_latest2.tar.gz *
```

But when i ran my program to register the new Distro, while it was extracting just fine the rootfs on my drive (as i could see)...

I got

```
E:\>wsldi centos-6 rootfs_centos_latest2.tar.gz
ERROR_FILE_NOT_FOUND=>0x80070002
centos-6 Is Installed: False
```

Any ideas?

**Comment by 0xbadfca11** [comment]
One, exe file must on the C: drive.
rootfs folder is created in the folder where the exe file is located.
It's the same restriction as other store versions.

Two, path inside tar must not begin with ``./``.
This is not documented, but WslRegisterDistribution rejects.

**Comment by ProIcons** [comment]
```
C:\CentOS>wsldi CentOS-6 C:\CentOS\rootfs_centos_latest2.tar.gz
ERROR_FILE_NOT_FOUND=>0x80070002
CentOS-6 Is Installed: False
```

![image](https://user-images.githubusercontent.com/3339081/33268827-4ad8b6f0-d387-11e7-829d-071ebdea351f.png)

**Comment by 0xbadfca11** [comment]
Because my answer was wrong, deleted.

**Comment by onomatopellan** [comment]
Are the contents of that rootfs file correct? `bin` should be a real folder not a file.

**Comment by ProIcons** [comment]
They are symlinks, and windows can't understand them.

**Comment by onomatopellan** [comment]
I guess `bash` inside `bin` folder is the minimum it needs in order to work.

**Comment by ProIcons** [comment]
I converted every symlink to static folder, having more than 150 mb of archive and tried it again. Same issue.

**Comment by 0xbadfca11** [comment]
I found by using Process Monitor that WslRegisterDistribution() is trying to unpack a file that does not exist in tar.
I think the cause was neither rootfs.tar nor your app.
![image](https://user-images.githubusercontent.com/7390559/33302440-68358d96-d43f-11e7-8a33-e6f26a6a60ee.png)
![image](https://user-images.githubusercontent.com/7390559/33302506-f280b5e8-d43f-11e7-8894-f379230d0d02.png)

**Comment by NablaCFD** [comment]
I guess the bug steps from the packing process of CentOS 7，not wsl side problem.

**Comment by Biswa96** [comment]
CentOS and Mageia does not work with WSL. When I'm trying to install them, the HRESULT coming from `WslRegisterDistribution()` function, `0x80070002` is not documented. See the list of Hresults in https://msdn.microsoft.com/en-us/library/cc704587.aspx

**Comment by NablaCFD** [comment]
we have tested several CentOS versions, the clue is that centos-7.2.1511-docker.tar.xz can normally work, while CentOS latest versions did not. Thus I think the problem maybe steps from a bug during the packing into docker.tar.xz processes of  latest CentOS vers.

**Comment by 0xbadfca11** [comment]
Use ``--hard-dereference`` when repacking, the installation was successful.
Hmm.

**Comment by Biswa96** [comment]
Thanks @0xbadfca11, your idea works. Now **all versions of CentOS and Mageia both works** with WSL. 

* How do you think that `--hard-dereference` option will work?
* Also why that option does not require for other distros except CentOS and Mageia?

@ProIcons Use the following commands to convert .tar.xz to .tar.gz for CentOS and Mageia:
```
tar -xf CentOS.tar.xz -C ~/CentOS/
cd CentOS/
tar -czf ../CentOS.TGZ --hard-dereference *
cd
mv CentOS.TGZ /mnt/c/
```
