### ISSUE TITLE
BSOD in LXCORE!LxpFutexFindWaitQueue since Windows 10 Fall Creators Update when building mono

### ISSUE THREAD

**Issue by ntherning** [Microsoft/WSL#2697]
* Your Windows build number:
```
C:\> ver
Microsoft Windows [Version 10.0.16299.64]
```

* What you're doing and what's happening:

I'm building [mono](https://github.com/mono/mono) inside Ubuntu 16.04.3 on WSL. I installed Windows 10 Fall Creators Update a couple of days ago and since then building mono causes a `KERNEL_SECURITY_CHECK_FAILURE` in `LXCORE!LxpFutexFindWaitQueue` and BSOD.

Here's how to reproduce: 

```
sudo apt-get install build-essential automake autoconf libtool cmake
git clone https://github.com/mono/mono.git
cd mono/
git submodule update --init --recursive
./autogen.sh --enable-nls=no --enable-maintainer-mode --with-mcs-docs=no --disable-boehm --enable-minimal=com,remoting
make -j12 V=1
```

This BSOD occurs both on my physical machine (Dell Precision 5520) and in a VMware virtual machine running Windows 10 Fall Creators Update.

I will send a minidump to secure@microsoft.com.

**Comment by alexrp** [comment]
Some extra context: The issue occurs when building the class libraries, i.e. if you do:

```
./autogen.sh ...
make -C mono
```

Everything is fine. But if you then do:

```
make -C mcs
```

You get the BSOD.

**Comment by ColinChargyBentley** [comment]
Hello,
I also had multiple times the same issue when making incremental C++ build code with GCC/G++ launch by make, launch by a BuildBot slave (ie python). I'm unable to narrow this down more. I'm also sending the dump to secure@microsoft.com. I'm using Windows 10.0.16299.15 . I'm posting this here and in https://github.com/Microsoft/WSL/issues/2648 as I think that could be the same issue.
Regards,
Colin Chargy

**Comment by bitcrazed** [comment]
Just checked with WSL team - this BSOD should be fixed in recent Insider Fast Ring builds. Could you try on a recent build and let us know if you're able to repro?

/cc @Brian-Perkins @benhillis @benaadams

**Comment by benaadams** [comment]
Seems to work fine :)

**Comment by bitcrazed** [comment]
Great to hear - thanks for checking & confirming Ben. Owe you another beer :D

**Comment by Brian-Perkins** [comment]
Fixed in RS3 with [KB4058258](https://support.microsoft.com/en-us/help/4058258/windows-10-update-kb4058258).

**Comment by rdp** [comment]
Seems to fix my crystal compilation failures (after manually installed that KB into a normal win10), thanks!

**Comment by ntherning** [comment]
Seems to be fixed now since a few weeks in my Windows 10 after automatic updates. As far as I'm concerned this issue can be closed now. Thanks!

**Comment by benhillis** [comment]
@ntherning - Thanks for the confirmation, closing.

**Comment by rdp** [comment]
Yeah not sure why but windows update said "nothing to update" so I manually applied it (even though it's released).  I assume/hope that eventually it would have automatically done so... :)

**Comment by benhillis** [comment]
@rdp - Windows update sometimes rolls out patches in batches, perhaps that's why you didn't see anything.

**Comment by mderoy** [comment]
I can confirm this is fixed for me as well
