### ISSUE TITLE
Communication with FTDI COM port

### ISSUE THREAD

**Issue by moisejbraver** [Microsoft/WSL#2698]
I am running WSL on Microsoft Windows [Version 10.0.16299.64].

I am trying to communicate with an FTDI COM port. It is mapped to COM4 on Windows, so I assume it corresponds to ttyS4. After setting the correct port settings 

`stty -F /dev/ttyS4 speed 2000000`

I start listening to it

`cat < /dev/ttyS4`

and then write to the port 

`echo '??' > /dev/ttyS4`

This is supposed to print "help" info of the devise, but no response is received.

On a real Linux system the device is mapped to ttyUSB0 (which is not present in WSL) and I am able to successfully establish the connection and communicate with the device. Am I doing something wrong, or is FTDI still not fully supported in WSL?

**Comment by frozenskys** [comment]
I'm having the identical problem - FTDI COM Port on COM4 device works in windows and native ubuntu but not WSL. Is there a solution for this?

**Comment by therealkenc** [comment]
Interestingly this was reported recently. Duping forward (entirely arbitrarily) to the newer one. #3422
