### ISSUE TITLE
Binary that runs specific distribution.

### ISSUE THREAD

**Issue by ProIcons** [Microsoft/WSL#2699]
Is there any way of generating a binary such as ubuntu.exe or opensuse-42.exe, to run a specific distribution? As far i looked it up they are running the same wrapper

```
C:\>ubuntu /?
Launches or configures a linux distribution.

Usage: ...

C:\>opensuse-42 /?
Launches or configures a linux distribution.

Usage: ...
```

Is there anyway for example a template for this kind of executable?

I'm aware that there's a routine called WslLaunch on wslapi.dll, but i was wondering if there was a file template

**Comment by Biswa96** [comment]
I'm working on that. See my repo. I only provide the way to install and configure users, the rest of the process is on the way. There is also other repos, see my stars list. IDA pro really helps me.

**Comment by tara-raj** [comment]
Good question. We're currently working on a distro launcher app with our Linux partners. Once that is sufficiently stable and complete, we'll release the code so people can create their own custom distros for side-loading/experimentation

**Comment by Biswa96** [comment]
@tara-raj Two suggestions: 

1. All the WSL functions are in Ubuntu.exe, replace those in WSL.exe. So that no exe to be shipped with appx  pacakge.

2. Replace `install.tar.gz` string with command arguments. So that any distro with any file name (i.e. tar.xz) can be install.

**Comment by ProIcons** [comment]
@Biswa96 only if i could see your repo 3 hours earlier. I really made a C# wrapper arround WSLApi. I implemented everything if wslapi. 😢

Also the only way changing default distro and see installed distros is wslconfig. It would be ideal all these routines to be public exposed by wslapi.dll

**Comment by Biswa96** [comment]
@ProIcons Those settings are configured in registries by LxssManager.dll. You can easily do that with simple regedit tool. Wslapi.dll is just a exposure of LxssManager.dll.

**Comment by therealkenc** [comment]
> Also the only way changing default distro and see installed distros is wslconfig.

It's in the registry. See also [WSLEnum](https://github.com/therealkenc/EnumWSL).

**Comment by therealkenc** [comment]
`wsl.exe` has an `--distribution` option as of [17666](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17666). `wslconfig /l` lists the installed distros.
