### ISSUE TITLE
Apache start error in Windows Creator update

### ISSUE THREAD

**Issue by fokumdt** [Microsoft/WSL#2700]
Hello,

I am using Windows 10 Home Version: 1709; Build: 16299.64. I have successfully installed apache2 and mysql, but when I try to start apache2, I get the following output:

```
sudo service apache2 start
 * Starting web server apache2
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
```
I have also found issue #1921, but I am unable to resolve my issue as documented there.

Similarly, when I try to start mysql I am also unable to get it to start. Terminal output is shown below:
```
 sudo service mysql start
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  5439 Aborted
(core dumped) plymouth --ping > /dev/null 2>&1
 * Starting MySQL database server mysqld
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  5454 Aborted
(core dumped) plymouth --ping > /dev/null 2>&1
```

**Comment by therealkenc** [comment]
> but when I try to start apache2, I get the following output:
> (13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
> (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80

That the same spirituality as #1921. Likely you've got something already listening on port 80. Try starting Apache on another port like 8080 or 3333 or something to confirm. Over there it was Skype, but it could be anything already hogging the port. This is Linux behaviour, similar to trying to run Apache and say Node on port 80 at the same time.

>Similarly, when I try to start mysql I am also unable
>initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

This is #1332. Someone who has gotten mysql running on WSL might be able to help you out over in that thread. Or you might consider running mysql on Windows for now.
