### ISSUE TITLE
Can't debootstrap Ubuntu precise (12.04)

### ISSUE THREAD

**Issue by johnv-valve** [microsoft/WSL#2705]
debootstrap fails trying to install Ubuntu Precise (12.04) from within the standard Ubuntu Xenial release.

    C:\Users\johnv>ver
    
    Microsoft Windows [Version 10.0.16299.64]

Repro:

    #~ debootstrap --arch=amd64 precise ./precise-root http://archive.ubuntu.com/ubuntu/    
    *many lines of output...*
    I: Extracting util-linux...
    I: Extracting xz-utils...
    I: Extracting zlib1g...
    W: Failure trying to run: chroot /home/johnv/precise-root mount -t proc proc /proc
    W: See /home/johnv/precise-root/debootstrap/debootstrap.log for details

Contents of deboostrap.log

    gpgv: Signature made Wed Apr 25 15:49:42 2012 DST using DSA key ID 437D05B5
    gpgv: Good signature from "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>"
    Segmentation fault (core dumped)

If you try to run the failed command manually, it crashes with a segfault

    #~ chroot /home/johnv/precise-root mount -t proc proc /proc
    [1]    7540 segmentation fault (core dumped)  chroot /home/johnv/precise-root mount -t proc proc /proc

It works with Ubuntu Trusty and Debian Jessie.

**Comment by johnv-valve** [comment]
Debian "wheezy" also fails, although in a slightly different way

    #~ debootstrap wheezy ./wheezy-root http://httpredir.debian.org/debian/
    ...
    I: Extracting zlib1g...
    I: Installing core packages...
    W: Failure trying to run: chroot /home/johnv/wheezy-root dpkg --force-depends --install 
    /var/cache/apt/archives/base-passwd_3.5.26_amd64.deb

Contents of debootstrap.log

    dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
     missing description
    dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
     missing architecture
    Segmentation fault (core dumped)

**Comment by Biswa96** [comment]
Do you want to install Debian rootfs in WSL?

**Comment by johnv-valve** [comment]
My main goal is to enable developers to build against the Steam runtime on their Windows machines. https://github.com/ValveSoftware/steam-runtime#building-in-the-runtime. Currently this does not work because of the Precise deboostrap error described above.

**Comment by jstarks** [comment]
If you can get an strace leading up to the segfault we may be able to determine what’s happening.

**Comment by therealkenc** [comment]
I am thinking it doesn't like something about the contents of `/proc` but that's just a guess. Getting in there with `gdb` would take some effort because it is late in a long/complicated bash script.

FWIW if you run the `debootstrap` again (ie twice) it will continue maybe resolves itself. But for people wanting to do these types of scenarios you are probably better off just grabbing the cloud tarball and manually doing the `chroot` yourself old school.

Steam runtime may not fly for other reasons. Last time I checked it needs multilib, but that was a long time ago (last year), and I only had a cursory look at that. Maybe something changed since then, or I could be wrong.

```
17325 execve("/usr/local/sbin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
17325 execve("/usr/local/bin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
17325 execve("/usr/sbin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
17325 execve("/usr/bin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
17325 execve("/sbin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
17325 execve("/bin/readlink", ["readlink", "-f", "/proc"], [/* 31 vars */]) = 0
17325 brk(NULL)                         = 0x1672000
17325 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xaf8} ---
17325 +++ killed by SIGSEGV (core dumped) +++
17324 <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV && WCOREDUMP(s)}], 0, NULL) = 17325
17324 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=17325, si_uid=0, si_status=SIGSEGV, si_utime=0, si_stime=0} ---
17324 rt_sigreturn({mask=[]})           = 17325
17324 write(2, "Segmentation fault (core dumped)"..., 33) = 33
17324 dup2(11, 2)                       = 2
17324 close(11)                         = 0
17324 exit_group(0)     
```
