### ISSUE TITLE
Angular / React / Node / Webpack not reloading files after change.

### ISSUE THREAD

**Issue by atasanchez** [microsoft/WSL#2709]
Windows Version: 1709
Widows Compilation Version: 16299.64

Cli Angular Version: 1.5.5
create-react-app Version: 1.4.3

I development on web technologies, I was installing WSL on my Windows system. Everything works correctly, except that when I run for example applications that use the inotify service do not perform the surcharge of the files that were modified.
This happens with **Angular / Cli** as well as **create-react-app** and I suspect that in any other application that uses the **inotify** service.
Review the previous issues and this should have been resolved in a previous build, but in my system it just does not work. Try formatting the machine and reinstalling and it still does not work.

Try to solve it with the following command:

`echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`

I received the following reply:

> tee: /proc/sys/fs/inotify/max_user_watches: Operation not permitted
65536

I'm not sure what other information would be needed for this issue.

**Comment by SanchezAta** [comment]
Today check that inotify is working correctly, however this type of features is not working by doing a test with the consoles and a text file, but what is webpack does not work directly.

**Comment by apostolos** [comment]
Confirmed fixed in WSL 2
