### ISSUE TITLE
Microsoft Windows Server 2016 Datacenter 

### ISSUE THREAD

**Issue by fenchu** [Microsoft/WSL#2711]
Is there a way to get it working here?
(I hate to go back to cygwin)

I'm not at the liberty to choose server here: (I would have used a Windows10pro)
```
systeminfo | Select-String "^OS Name","^OS Version"
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
```

```
Get-WindowsOptionalFeature -Online | Select-string "Linux"
<nothing>
```

```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

```

Is there a way to locally download this feature and install it?

**Comment by Biswa96** [comment]
Did you enable developer mode?

**Comment by fenchu** [comment]
Yes. but I havent rebooted. the server is a production server. But I was able to install cygwin without any reboot.

**Comment by onomatopellan** [comment]
"WSL did not come to server until Windows Server Build 16237, see post. You are running 14393, which is way older."
https://github.com/Microsoft/WSL/issues/931#issuecomment-331588788

**Comment by charry223** [comment]
I would like to share with you my experience, I went to [](https://www.vanskeys.com/)  to buy a key, to my surprise, their attitude is very good, but the key work is normal, there is very little money I spent, very happy the first purchase and recommend it to you.
