### ISSUE TITLE
Line wrapping visual issue (eats itself from behind)

### ISSUE THREAD

**Issue by sigurof** [Microsoft/WSL#2713]
* Windows build number: Build 16299
Microsoft Windows [version 10.0.16299.98]

* What I am doing and what's happening:  
 - Open cmd
 - Type "bash", hit Enter
 - Type any text whatsoever until it hits the right edge of the window. 
Actually, the text does not even hit the right edge of the window! Upon hitting some invisible border, the line wraps around on itself without changing lines, and consequently anything on the beginning of the line will be "eaten" up by what comes after passing the point of line wrapping.
![image](https://user-images.githubusercontent.com/23652922/33476968-30452058-d684-11e7-9c97-e3c298174b6a.png)

![image](https://user-images.githubusercontent.com/23652922/33476994-43efbb22-d684-11e7-9496-23c2e9a17973.png)

 - After line wrapping has failed miserably, hit Backspace once, and the entire row of text input before line wrapping will disappear.
![image](https://user-images.githubusercontent.com/23652922/33477006-4d5b90b4-d684-11e7-85be-7371f8f16e36.png)

* What's wrong / what should be happening instead:
The line should perform a line change. 
All the text should not disappear by one press of Backspace

* Comments:
- I performed "sudo apt-get update" and "sudo apt-get upgrade" right before posting this issue, so everything should be up to date.
- This seems to be a purely visual effect. The command:
echo "This is a line that will wrap around on itself, erasing the text at the beginning of the line"
will still output "This is a line that will wrap around on itself, erasing the text at the beginning of the same line"
even though "same line" erases the characters "echo "This"
![image](https://user-images.githubusercontent.com/23652922/33477289-6fa88130-d685-11e7-88dc-35bd8adaa6aa.png)
-After wrapping around once, and eating itself up completely, the line correctly hits the right edge of the window and wraps around, changing lines and performs line wrapping normally.

**Comment by zadjii-msft** [comment]
@sigurof 
What's the value of `PS1` you've set in your .bashrc?

What's the output of `stty -a`? 

Does this happen on all new bash consoles that you create?

**Comment by sigurof** [comment]
The following three quotes are all occurences of PS1 in my .bashrc in order first to last:
```
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\
]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
```
```
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```
```
PS1='\e[37;1m\u@\e[35m\W\e[0m\$ '
```

output of stty -a (with a larger cmd window than in the screenshots above):
`sigurof@Sigurd$ stty -a
speed 38400 baud; rows 62; columns 156; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = M-^?; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc`

Yes, it always happens if I write "too much" text in the terminal.

**Comment by zadjii-msft** [comment]
Try replacing that last PS1 with this:
`PS1='\[\e[37;1m\]\u@\[\e[35m\]\W\[\e[0m\]\$ '`

You need to surround escape sequences with `\[` and `\]`, otherwise bash won't know how long the actual prompt is.

**Comment by sigurof** [comment]
Thank you. That solved the problem.

**Comment by zadjii-msft** [comment]
@sigurof Glad to help!

**Comment by gwd666** [comment]
same issue popped up a couple of weeks ago in my WLS2 Ubuntu 20.04 bash  - none of the above works as a fix

**Comment by gwd666** [comment]
@zadjii-msft will do as soon as I can - ie in next couple of days ... promise

**Comment by gwd666** [comment]
@zadjii-msft sorry for the delay - I am using a `liquidprompt` (https://github.com/nojhan/liquidprompt) prompt
here is the part of my `.bashrc` that pulls it in
```
# Only load Liquidprompt in interactive shells, not from a script or from scp
[[ $- = *i* ]] && source ~/liquidprompt/liquidprompt

[[ $- = *i* ]] && source ~/liquidprompt/themes/powerline/powerline.theme
[[ $- = *i* ]] && source ~/liquidprompt/themes/alternate_vcs/alternate_vcs.theme
```
