### ISSUE TITLE
Cannot enable WSL feature through Powershell

### ISSUE THREAD

**Issue by Po-wei** [microsoft/WSL#2719]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.64]
Windows10 1709 enterprise version

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Cannot activate WSL feature through power shell command(elevated)
![image](https://user-images.githubusercontent.com/17596021/33517563-688d42ae-d7c1-11e7-8a4e-1d6e033936ee.png)

**Comment by HankelBao** [comment]
I met the same problem and linux subsystem is quite important for me.
Waiting for solutions...

**Comment by jstarks** [comment]
Hmmm. To diagnose this, you should probably look at the log files in c:\windows\logs\cbs. See if there are any log files with lines containing Error.

**Comment by sunilmut** [comment]
The other option is to go to the add/remove UI and try it out from there and see if it makes any difference.

**Comment by nikclayton** [comment]
Following the fix in https://github.com/Microsoft/WSL/issues/3925 resolved this for me. For some reason my system hadn't automatically picked up the 1809 update.
