### ISSUE TITLE
VTune Amplifier command line does not work

### ISSUE THREAD

**Issue by edbennett** [Microsoft/WSL#2725]
* Microsoft Windows [Version 10.0.17046.1000]
* I'm attempting to run the VTune Amplifier command-line tool (part of the Intel Parallel Studio). I've successfully installed Parallel Studio, and as of upgrading to the Insider build I'm successfully able to run the compilers. However, running `amplxe-cl` returns the error: `amplxe-cl: error while loading shared libraries: libamplxe_dicer2_plugin_tpss_2.20.so: cannot enable executable stack as shared object requires: Invalid argument`. 
* Repro steps
    * Install Intel Parallel Studio 2018
    * Source the relevant variables (`source ~/intel/vtune_amplifier/amplxe-vars.sh intel64`)
    * Run `amplxe-cl`
* What happens:
    * The error message `amplxe-cl: error while loading shared libraries: libamplxe_dicer2_plugin_tpss_2.20.so: cannot enable executable stack as shared object requires: Invalid argument` appears.
* What's wrong / what should be happening instead:
    * A usage message appears detailing the options available
* [Strace](https://gist.github.com/edbennett/c2b086ac08817b68f6232c9385e2b34b)

**Comment by therealkenc** [comment]
#286 #916 #2553 #2562 ([message](https://github.com/Microsoft/WSL/issues/2553#issuecomment-335201548))
