### ISSUE TITLE
Black Screen and Lxssmanager Service Failure

### ISSUE THREAD

**Issue by ideal2545** [Microsoft/WSL#2726]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  1709 (16299.64)

* What you're doing and what's happening:  Trying to run BASH

* What's wrong / what should be happening instead: I get a black screen an then a crash. I tried uninstalling and reinstalling the linux feature, disabling and enabling developer mode. I have no anti-virus besides windows defender. I think it has something to do with the lxssmanager service. When I try to start it manually it gives an error: 

"Windows could not start the LxssManager service on Local Computer".
"Error 577: windows cannot verify the digital signature for this file..."

Any help is appreciated!

**Comment by Biswa96** [comment]
Check if lxcore.sys and lxss.sys drivers are in right place C:\Windows\System32\drivers and also LxssManager.dll in system32 folder. Try to disable/enable test signing mode with bcedit command `Bcdedit.exe -set TESTSIGNING OFF`. Then try to maually start/stop that service with `sc start LxssManager` or `net start LxssManager`.

**Comment by Brian-Perkins** [comment]
You can use [signtool.exe](https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx) to get an idea what is wrong: signtool verify /a /v %systemroot%\system32\lxss\lxssmanager.dll

**Comment by Brian-Perkins** [comment]
This may be related to a certificate expiration issue discussed [here](https://aka.ms/Cabs80096004). The next Insider build will have a fix. This is a problem on most Insider builds but it didn't trigger until early December when the expiration date was hit.
