### ISSUE TITLE
Path length

### ISSUE THREAD

**Issue by FrodeHus** [Microsoft/WSL#2727]
* Your Windows build number:  
Microsoft Windows [Version 10.0.16299.98]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Tried 'npm install -g azure-functions-core-tools@core' and 'docker push xxxx' (latter using Docker4Win with WSL)

First gave: 
mkdir: cannot create directory ‘/usr/lib/node_modules/azure-functions-core-tools/bin’: No such file or directory
Second resulted in:
open \tmp\afba2e5b372dfecad66abccf3641a55b0fa155ed72f0f1df686526aa40cfe994-mount\home\site\wwwroot\.git\HEAD: The system cannot find the path specified.

* What's wrong / what should be happening instead:
I suspect this is due to Windows path length restrictions.

**Comment by therealkenc** [comment]
You don't have access rights to `/usr` without `sudo`. Suggest using [`nvm`](https://github.com/creationix/nvm).
