### ISSUE TITLE
Unable To SSH Localhost

### ISSUE THREAD

**Issue by gulshanmudgal** [Microsoft/WSL#2729]
* Windows build number :  Microsoft Windows [Version 10.0.16299.64]

* hadoop@Gulshan:/home/gulshan$ ssh-keygen -t rsa -P ""
Generating public/private rsa key pair.
Enter file in which to save the key (/home/hadoop/.ssh/id_rsa):
Created directory '/home/hadoop/.ssh'.
Your identification has been saved in /home/hadoop/.ssh/id_rsa.
Your public key has been saved in /home/hadoop/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:QxD3My4v9G48bIFla6q95HS2QM1pV/56m1kAJkCCfuU hadoop@Gulshan
The key's randomart image is:
+---[RSA 2048]----+
|     .+o+        |
|    .  +.o       |
|   .   o. = o .  |
|    . ..E+o* +   |
|     .  S+*.. o  |
|       o.*+.   o |
|        ===.    o|
|       =.**.   .=|
|      ..++o.  .=.|
+----[SHA256]-----+
hadoop@Gulshan:/home/gulshan$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
hadoop@Gulshan:/home/gulshan$ ssh localhost
The authenticity of host 'localhost (127.0.0.1)' can't be established.
RSA key fingerprint is SHA256:P5ZHB0LmP1xYfo/MjGw7qbyNvLtLan+n7hKWEZhQvfk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (RSA) to the list of known hosts.
hadoop@localhost's password:
Permission denied, please try again.
hadoop@localhost's password:
Permission denied, please try again.
hadoop@localhost's password:
Received disconnect from 127.0.0.1 port 22:14:
Connection to localhost closed by remote host.
Connection to localhost closed.

* i have created ssh key for password less access, but still it's asking for password.

i would like to add that i am running ssh as Admin

![capture](https://user-images.githubusercontent.com/11193392/33698868-5d7babe0-db35-11e7-9033-8e71db448ce1.PNG)

(https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Probably the same problem as the person in #2505. Start up `sshd` with `sudo /usr/sbin/sshd -d -p 2222` and connect with `ssh localhost -p 2222` to see if that is the case.

**Comment by gulshanmudgal** [comment]
getting this.
![capture1](https://user-images.githubusercontent.com/11193392/33749649-e3f7f146-dbf4-11e7-9430-195b88ec9fd6.PNG)

**Comment by therealkenc** [comment]
```
hadoop@Gulshan:/home/gulshan$ sudo /usr/bin/sshd -d -p 2222
[sudo] password for hadoop:
debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
...blah blah blah...
Missing privilege separation directory: /var/run/sshd
```
I don't think your `sshd` even started there, because you ended back at the command prompt. Per #2505 ([message](https://github.com/Microsoft/WSL/issues/2505#issuecomment-330809803)), in `/etc/sshd/sshd_config` make sure you have:

```
ListenAddress 0.0.0.0
UsePrivilageSeparation no          <--- that
PasswordAuthentication yes
```

**Comment by SchizoDuckie** [comment]
Shut down the windows internal ssh server in services.msc.

![image](https://user-images.githubusercontent.com/111710/33768364-fbea98f4-dc25-11e7-849c-1b668eee59c6.png)

Yes. That is a thing these days.
You cannot authenticate because you're connecting to the windows version of the sshd! Try eintering your windows password just for kicks.

**Comment by gulshanmudgal** [comment]
Thanks to Both of You.
Finally got it working.

**Comment by xiligey** [comment]
Can you tell me how you fix it finally? Thanks! @gulshanmudgal

**Comment by xiligey** [comment]
After experiencing many failures, I finally succeeded！ @gulshanmudgal 

See [issue3173](https://github.com/Microsoft/WSL/issues/3173)

**Comment by gobbedy** [comment]
@gulshanmudgal could you please share with others how you solved it?

**Comment by lovejavaee** [comment]
> hadoop@Gulshan:/home/gulshan$ sudo /usr/bin/sshd -d -p 2222
> [sudo] password for hadoop:
> debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
> ...blah blah blah...
> Missing privilege separation directory: /var/run/sshd
> 
> I don't think your sshd even started there, because you ended back at the command prompt. Per #2505 (message), in /etc/sshd/sshd_config make sure you have:
> ListenAddress 0.0.0.0
> UsePrivilageSeparation no          <--- that
> PasswordAuthentication yes

--> UsePrivil**e**geSeparation

**Comment by lovejavaee** [comment]
> hadoop@Gulshan:/home/gulshan$ sudo /usr/bin/sshd -d -p 2222
> [sudo] password for hadoop:
> debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
> ...blah blah blah...
> Missing privilege separation directory: /var/run/sshd
> 
> I don't think your sshd even started there, because you ended back at the command prompt. Per #2505 (message), in /etc/sshd/sshd_config make sure you have:
> ListenAddress 0.0.0.0
> UsePrivilageSeparation no          <--- that
> PasswordAuthentication yes

UsePrivilageSeparation -> UsePrivilegeSeparation

**Comment by iptoux** [comment]
> `UsePrivilageSeparation` is deprecated, any workarounds?

Yep, just create directroy "/var/run/sshd" or "/run/sshd" on sshd server, then it's working.

**Comment by YanMiaoW** [comment]
> > `UsePrivilageSeparation` is deprecated, any workarounds?
> 
> Yep, just create directroy "/var/run/sshd" or "/run/sshd" on sshd server, then it's working.

It'work ! thanks, also remember to restart ssh service , mkdir /var/run/sshd , service ssh restart, and it's work!
