### ISSUE TITLE
Homepage is 404

### ISSUE THREAD

**Issue by koppor** [Microsoft/WSL#2733]
The repository homepage on GitHub is rendered as follows:

![grafik](https://user-images.githubusercontent.com/1366654/33755388-cc4da1de-dbf0-11e7-9d81-8843485663f1.png)

The blue link is <https://msdn.microsoft.com/commandline/wsl>.

When clicking this link in Germany, following page appears:

![grafik](https://user-images.githubusercontent.com/1366654/33755405-e112f844-dbf0-11e7-8035-48b86972265c.png)

This is a 404 page, isn't it?

I suggest to change the link to something more fitting or bring back the WSDL homepage on msdn.

**Comment by Brian-Perkins** [comment]
The docs were moved, and are supposed to [redirect](https://msdn.microsoft.com/commandline/wsl/about) but apparently not all are working properly. The new start page is [here](https://docs.microsoft.com/windows/wsl)

**Comment by jstarks** [comment]
I've updated the link to the new site.

@scooley Do you know why the redirect is apparently not working for our German users?

**Comment by jstarks** [comment]
Thanks for point this out, @koppor.

**Comment by scooley** [comment]
Fixed!  Thank you again for reporting.
