### ISSUE TITLE
Ubuntu running under WSL doesn't auto-select a local apt mirror

### ISSUE THREAD

**Issue by VirtualSatai** [microsoft/WSL#2735]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.64]

* What you're doing and what's happening:  After a regular install following https://docs.microsoft.com/en-us/windows/wsl/install-win10 

* What's wrong / what should be happening instead: After using Ubuntu the mirror was set to http://archive.ubuntu.com/ubuntu/ instead of a mirror more local such as http://dk.archive.ubuntu.com/ubuntu/ (for me in Denmark)

**Comment by jstarks** [comment]
@tara-raj, can you help get this feedback to Canonical?
