### ISSUE TITLE
Existing text overwritten when writing text during ssh session started from WSL Ubuntu

### ISSUE THREAD

**Issue by msundin** [Microsoft/WSL#2740]
* Your Windows build number:  10.0.16299.64

Same error as here: https://github.com/Microsoft/WSL/issues/1307 but now only when using ssh. Not happening before the ssh session in WSL (Ubuntu).

* What you're doing and what's happening: I use ssh from WSL Ubuntu to login to a FreeNAS jail where I use bash shell. When writing text in the jail, the existing text is overwritten. This does not happen if I login to the same FreeNAS jail using Putty. 

* What's wrong / what should be happening instead: Existing text should not be overwritten.

Maybe this is a problem for all ssh sessions from WSL? Unfortunately I cannot test ssh to e.g. a Linux machine but maybe someone else can.

**Comment by therealkenc** [comment]
This (relatively old) one should have been duped down to #1307 but appears to have fallen between the cracks. Per the [last post](https://github.com/Microsoft/WSL/issues/1307#issuecomment-350319200) in the aforementioned issue best chance is with a detailed repro. Console issues have moved over to the [Windows Console issue tracker](https://github.com/microsoft/console).
