### ISSUE TITLE
File naming incompatibilities in mounted folders

### ISSUE THREAD

**Issue by marcelgwerder** [Microsoft/WSL#2741]
I do have a PHP application that tries to create filenames including `\`. It actually has a fallback for Windows, however it thinks it's running on Linux which is correct. I want to edit the code of the application in my Windows editor of choice (vscode) and therefore I have to leave the code on Windows. 

I guess this applies to all [limitations in Windows ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#naming_conventions) that are not present in Linux.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.16299.98]
```
(I unfortunately can't get the insider preview to send me updates and therefore can't test in newer builds right now)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
dev@DESKTOP-7I2RG9D:/mnt/c$ touch \\random\\file
touch: setting times of '\random\file': No such file or directory
```
* What's wrong / what should be happening instead:
The file is not created because windows doesn't allow it to. The following happens in a not mounted directory:
```
dev@DESKTOP-7I2RG9D:/tmp$ touch \\random\\file
dev@DESKTOP-7I2RG9D:/tmp$ ls
\random\file
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
https://gist.github.com/marcelgwerder/43d5e98b92af374f8556cccb48443e7a#file-touch-strace

It's not that I really would expect this to work but I can only see three solutions for me as a developer. 

1. Microsoft makes it somehow work anyway.
2. Microsoft makes the linux files accessible so that I don't have to leave my code on Windows.
3. I can't really use WSL because some code that assumes to be on Linux will randomly fail.

**Comment by therealkenc** [comment]
> do have a PHP application that tries to create filenames including `\`

_"well, there's your problem"_

That said, you're correct. This is fundamentally the same request as #1514 ([message](https://github.com/Microsoft/WSL/issues/1514#issuecomment-299661441)) and #2070 which was closed for reasons unknown. Cygwin does the Right Thing™ IIRC.

**Comment by marcelgwerder** [comment]
I certainly agree that the application shouldn't do this and it's weird, unfortunately this is part of the core of a CMS and I'm stuck with it for now. However I don't think that this will be the only example out there so WSL should be able to handle it one way or another. 

I didn't see those closed issues, probably focused on the open ones. Anyway this doens't look like it is solved.

**Comment by therealkenc** [comment]
> I didn't see those closed issues, probably focused on the open ones.

No worries. This is hard to label this a duplicate anyway because it is a stretch for people to assume `\` should be lumped in with say `:` or `?`.

Don't know your exact situation, but if you have complete control over the PHP script (but not the CMS) then you might consider factoring out the create/open code and substitute the `\` character with something else like `%` or `@`. If `%` is legal in your CMS too, escape it with `%%`. Or do something like URI normalisation %5C. _Effort_, yeah, but pretty standard fare. If it isn't code you have control over or don't want to change it for _reasons_ (common situation) then yeah...

**Comment by therealkenc** [comment]
#1514, should be better as of as of Insiders Build 17101.
