### ISSUE TITLE
Undocumented 0x07 WSL flag in registry

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#2744]
When I install any distribution using Windows Store provided Appx packages, it saves `Flags` DWORD registry with `0x07` value in registry path `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{LxUID}`. But the value is not documented in this [WSL_DISTRIBUTION_FLAGS enumeration](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826872(v=vs.85).aspx) link. The flags are:
```
  WSL_DISTRIBUTION_FLAGS_NONE                   = 0,
  WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP         = 1,
  WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH         = 2,
  WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING  = 4
```
Does the executable file sum all the flags (0+1+2+4=7) to enable all features in installed distro?

**Comment by jstarks** [comment]
Yes, the flags are bits, so they are or'ed or added together.

Please keep in mind that the registry format is not documented and is subject to change.

**Comment by therealkenc** [comment]
My idle hope is the registry format is subject to disappearance. The death march to `chroot.exe` is taking longer than expected. 😉

**Comment by Biswa96** [comment]
>the registry format is not documented

@jstarks But when I use [`WslConfigureDistribution`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826865(v=vs.85).aspx) function with any value of WSL_DISTRIBUTION_FLAGS, then it gives same value in `flags` registry.

**Comment by Biswa96** [comment]
Is there any relation between WSL flags an Linux file permission?
Linux file permission:
```
0 = No Permission
1 = Execute
2 = Write
4 = Read
```

**Comment by benhillis** [comment]
@Biswa96 - No.

**Comment by Biswa96** [comment]
@benhillis @therealkenc  With Procmon, I find that LxssManager service searches (RegQueryValue) two same registry value (0x07 to enable all) in different keys:
1. HKLM\System\CurrentControlSet\services\LxssManager --> DistributionFlags --> REG_DWORD --> 0x07
2. HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{LxUid} --> Flags --> REG_DWORD --> 0x07

Is there any relation between them? I'm using Version 10.0.17627.1000.

**Comment by benhillis** [comment]
@Biswa96 - HKLM\System\CurrentControlSet\services\LxssManager is a global override.

**Comment by Biswa96** [comment]
Are `AppendNtPath` and `InteropEnabled` registries require if I add `Flags` value as `0x07`?

**Comment by Biswa96** [comment]
@benhillis Is there any hidden flag in build 17666? I saw that in wsl.exe. When I change `Flags` registry from `0x07` to `0x08` wsl.exe opens home directory (`~/`) at first run.
