### ISSUE TITLE
Cannot open a file with a space in it's filename using `cmd.exe \C start "file name.txt"`

### ISSUE THREAD

**Issue by dalyIsaac** [Microsoft/WSL#2745]
Version: `Windows 10 build 17046.1000`  
Distribution: `Ubuntu 16.04 xenial`  
Kernel: `x86_64 Linux 4.4.0-43-Microsoft`

# Repro:  
1. Create a file named "test-no-spaces.txt" in a Windows directory
2. Create a file named "test spaces.txt" in the same directory
3. Open "test-no-spaces.txt" with the default Windows application using  
`cmd.exe /C start test-no-spaces.txt`
4. Attempt to open "test spaces.txt" with the default Windows application using  
`cmd.exe /C start "test spaces.txt`

# Expected Results
1. "test-no-spaces.txt" opens with the default Windows application
2. "test spaces.txt" opens with the default Windows application

# Actual Results
1. "test-no-spaces.txt" successfully opens with the default Windows application
2. `cmd.exe /C start "test spaces.txt"` opens `cmd.exe` in a new window in the directory of "test spaces.txt"

This only occurs with the `cmd.exe /C start "test spaces.txt"` command. If I directly specify the Windows application, like `code "test spaces.txt"` this works fine. 

# `strace`
https://gist.github.com/dalyIsaac/d1ed323b39601405e1fbbf9aee2ed879

**Comment by 0xbadfca11** [comment]
Reason 1:
First double quoted string is specification of console window title. (See ```start /?```)
The command that needs to be quoted must be second.
```cmd
C:\>start "<title>" "a b.txt"
```

Reason 2:
Quotation marks are not passed to execve(), and WSL interop re-add **if necessary**.
`$ cmd.exe /C start test-no-spaces.txt` will work. Does not specify a title.
`$ cmd.exe /C start "test-no-spaces.txt"` will work unexpectedly. "" has gone. Interpreted as title not specified.
`$ cmd.exe /C start "test spaces.txt"` will interpreted as specify a title.
**`$ cmd.exe /C start "" "test spaces.txt"` will work. Title specified to "". Empty string have to enclosed in "".**
`$ cmd.exe /C start "abc" test-no-spaces.txt` will not work. "" has gone. Interpreted as `start abc test-no-spaces.txt`

**Comment by dalyIsaac** [comment]
Thanks @0xbadfca11
