### ISSUE TITLE
du -k gives incorrect result

### ISSUE THREAD

**Issue by Dr-Irv** [Microsoft/WSL#2747]
* Your Windows build number: 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
(echo "s='a'*(1024*12)" ; echo "print s") | python > foo.out
ls -l foo.out ; du -k foo.out ; du -b foo.out
```
yields
```
-rwxrwxrwx 1 root root 12289 Dec 11 16:03 foo.out
8193    foo.out
12289   foo.out
```

* What's wrong / what should be happening instead:
The output should be (determined by using cygwin):
```
-rwxrwx---+ 1 (Omitted) 12289 Dec 11 16:03 foo.out
16      foo.out
12289   foo.out
```

So with the "-k" option, it is not computing the correct value of the number of kilobytes.

**Comment by therealkenc** [comment]
Well it was a good run.  #2517, #2500, #2440, #2434, #2400, #2347, #2211, #1894. Fixed in 16237.
