### ISSUE TITLE
WSL Bash.exe hangs when run remotely by Buildbot

### ISSUE THREAD

**Issue by Wolf-H** [Microsoft/WSL#2748]
* Windows build number:  [Version 10.0.16299.64]

* What we're doing and what's happening:
We are trying to replace CygWin in our Build Environment with WSL, using Buildbot as our Continuous Integration Server (running on Windows Server 2008 R2 Enterprise), with a Windows 10 VM as our Build Server.
Bash.exe commands run via a Remote Desktop session on the Build Server VM run perfectly, but when we try to run the same commands remotely from Buildbot (as the exact same User), bash.exe hangs indefinitely (it can be seen in Task Manager consuming 0% CPU).

* What's wrong / what should be happening instead:
Bash.exe should execute the passed-in commands and exit normally. This fails even for very simple commands such as ">bash.exe -c ls".

* Strace of the failing command, if applicable:
A DMP of bash.exe examined with VS2017 shows the following Call Stack:
 	ntdll.dll!NtDeviceIoControlFile() + 20 bytes	Unknown	No symbols loaded.
 	KERNELBASE.dll!WriteConsoleW() + 429 bytes	Unknown	No symbols loaded.
 	KERNELBASE.dll!PeekConsoleInputW() + 233 bytes	Unknown	No symbols loaded.
 	KERNELBASE.dll!ReadConsoleInputW() + 21 bytes	Unknown	No symbols loaded.
 	ucrtbase.dll!_ungetwch_nolock() + 781 bytes	Unknown	No symbols loaded.
 	ucrtbase.dll!_getwch_nolock() + 239 bytes	Unknown	No symbols loaded.
 	ucrtbase.dll!_getwch() + 25 bytes	Unknown	No symbols loaded.
 	ucrtbase.dll!00007ff9ce1b47ac()	Unknown	No symbols loaded.
	bash.exe!00007ff6355a4515()	Unknown	No symbols loaded.
 	bash.exe!00007ff6355a43dd()	Unknown	No symbols loaded.
 	bash.exe!00007ff6355aa505()	Unknown	No symbols loaded.
 	kernel32.dll!BaseThreadInitThunk() + 20 bytes	Unknown	No symbols loaded.
 	ntdll.dll!RtlUserThreadStart() + 33 bytes	Unknown	No symbols loaded.

I can provide the DMP file if required.

**Comment by Wolf-H** [comment]
A further clue:
The Windows System Log contains the following Error that coincides exactly with occurrences of the problem:
Source = DistributedCOM; Event ID = 10016
"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{4F476546-B412-4579-B64C-123DF331E3D6}
 and APPID 
{E82567AE-2EA4-4DBC-BC68-8B0A0526D8D5}
 to the user HAMJET\Builder.service SID (S-1-5-21-149124745-881731170-1629300891-10165) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool."

EventData:
  param1 application-specific 
  param2 Local 
  param3 Activation 
  param4 {4F476546-B412-4579-B64C-123DF331E3D6} 
  param5 {E82567AE-2EA4-4DBC-BC68-8B0A0526D8D5} 
  param6 HAMJET 
  param7 Builder.service 
  param8 S-1-5-21-149124745-881731170-1629300891-10165 
  param9 LocalHost (Using LRPC) 
  param10 Unavailable 
  param11 Unavailable

**Comment by Brian-Perkins** [comment]
This is related to #777 and #1602 among others. Support was added for this starting with Insiders Build 17017, so you can try a new Insiders Build to see if this scenario starts working.

**Comment by Wolf-H** [comment]
Thanks Brian.
I managed to resolve the issue by following the steps outlined here:
http://www.itexperience.net/2010/10/29/event-10016-the-application-specific-permission-settings-do-not-grant-local-launch-permission-for-the-com-server-application-with-clsid-c97fcc79-e628-407d-ae68-a06ad6d8b4d1/

With changes for the specific GUIDs in this case.

Everything working just great now :-)
