### ISSUE TITLE
ifconfig no longer lists SonicWall network interface

### ISSUE THREAD

**Issue by marc-lang** [Microsoft/WSL#2752]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.64]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Before the fall update, when connected to a Sonicwall Netextender VPN, an ifconfig command listed the network interface like so:

SonicWALL NetExtender
        Link encap: PPP
        inet addr:172.xx.xx.x Mask: 255.255.255.255
        MTU: 1500 Speed:144.40 Mbps
        Admin status:UP Oper status:OPERATIONAL
        RX packets:44073 dropped:0 errors:0 unkown:0
        TX packets:41106 dropped:0 errors:0 txqueuelen:0

Following the fall update, this network interface doesn't show in ifconfig, although it still shows in Cygwin terminals, such as Mobaxterm

**Comment by therealkenc** [comment]
#2685
