### ISSUE TITLE
Have the issues from the Fall Update been fixed that prevented dependencies from being installed on the Windows mount?

### ISSUE THREAD

**Issue by ishraqiyun77** [Microsoft/WSL#2753]
I keep things like `node_modules` and Python `virtualenv` in the project I am working on and the projects are on Windows mount. 

When the Fall Update update was installed on my computer back in October my dev environment quit, so I had to reconfigure it. Despite ultimately granting everyone all permissions to get around the issue, I could never `npm install`. nor `pip install -r requirements.txt`, onto the  Windows mount due to "permission errors". 

It took me several days (of lost work) to figure out it was the Update causing the issue as my personal laptop hadn't received it and still worked fine. Ultimately had to restore from a disk image back to version `10.0.15063`--I forget what the Fall Update version number is--and turn off updates.

I don't like my computer not being up-to-date, so I am wondering if this issue is now fixed.

#2610

**Comment by DarthSpock** [comment]
You can get updates without upgrading to the next Build version. See Microsoft's Lifecycle page for Windows 10. This means you can keep security and performance updates coming until that version of Win 10 is end of life.
