### ISSUE TITLE
WSL launching windows ssh.exe returns GetFileType as FILE_TYPE_PIPE

### ISSUE THREAD

**Issue by bagajjal** [Microsoft/WSL#2755]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17025.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
This issue is not a bug, rather need confirmation.

**steps to reproduce,**
1) Launch WSL bash from cmd.exe
2) From WSL bash, launch windows ssh.exe client.
3) ssh.exe failed to allocate pty session because GetFileType(STD_INPUT_HANDLE) returns FILE_TYPE_PIPE.
since ssh.exe is launched from cmd.exe console, user expects it to return FILE_TYPE_CHAR.
FYI, ssh.exe need to have control over the console as it need to update console settings, move the cursor to anywhere as instructed by sshd side server component.

I think this is an expected behavior as the ssh.exe is launched from WSL and ssh.exe STDIN/OUT will be pipes to WSL.

Is there a way to make this work so that the launched windows ssh.exe can have control over the terminal?

![image](https://user-images.githubusercontent.com/23668037/34020242-f4878358-e0e7-11e7-96cd-a92f76eefe5a.png)

For more information -
https://github.com/PowerShell/Win32-OpenSSH/issues/990

FYI, I am from Microsoft openssh team. You can ping me if required.

**Comment by therealkenc** [comment]
#2406 ([message](https://github.com/Microsoft/WSL/issues/2406#issuecomment-321603670)) etc
