### ISSUE TITLE
Cannot access Windows environment variables from bash

### ISSUE THREAD

**Issue by AndrewPardoe** [Microsoft/WSL#2756]
Label: Interop

Sorry for not filling out the form, but this problem/request is well-known by members of the WSL team. There are a lot of Issues that touch on similar interop problems but I can't find one that is narrowly defined to this request.

I would like to be able to access a Windows environment variable from bash. For example, %TEMP%.

Scenario: I maintain a port of [Matt Godbolt's Compiler Explorer](https://github.com/mattgodbolt/compiler-explorer) for WSL. I need to work in the Windows volume, and would like to work in a temporary directory, but I can't determine where the Windows temporary directory is located. 

See this snippet from [app.js](https://github.com/mattgodbolt/compiler-explorer/blob/master/app.js)

```
// AP: Allow setting of tmpDir (used in lib/base-compiler.js & lib/exec.js) through
// opts. WSL requires a tmpDir as it can't see Linux volumes so set default to c:\tmp.
if (opts.tmpDir)
    process.env.tmpDir = opts.tmpDir;
else if (process.env.wsl)
    process.env.tmpDir = "/mnt/c/tmp";
```

https://github.com/mattgodbolt/compiler-explorer/pull/603 is a command-line option workaround I had to introduce because of this.

**Comment by therealkenc** [comment]
Ref #2145 #2128

**Comment by jstarks** [comment]
We have a feature coming that might help here, but I don’t know if it will work for your specific situation. Can you explain the back-and-forth between WSL and Win32 a little more? I.e. who launches who?

I suspect in your situation you may just need to launch a subshell and run `cmd.exe /c echo %TEMP%` to retrieve the Windows temporary directory.

**Comment by AndrewPardoe** [comment]
Thanks for the suggestion @jstarks, I'll try that. 

In this scenario, the Compiler Explorer is a node.js app running in WSL. It invokes the MSVC compiler running in Win32. Because MSVC needs to read/write files, I have to give it a Windows-volume directory to do its work. Thus, the hardcoded `c:\tmp`.

**Comment by AndrewPardoe** [comment]
That does work, thank you! 

For posterity, here's the code to grab %TEMP% and unixify it:
```
// AP: Allow setting of tmpDir (used in lib/base-compiler.js & lib/exec.js) through
// opts. WSL requires a tmpDir as it can't see Linux volumes so set default to c:\tmp.
if (opts.tmpDir)
    process.env.tmpDir = opts.tmpDir;
else if (process.env.wsl) {
    // Example %TEMP% is C:\Users\apardoe\AppData\Local\Temp
    var windowsTemp = child_process.execSync('cmd.exe /c echo %TEMP%').toString().replace(/\\/g, "/");
    var driveLetter = windowsTemp.substring(0, 1).toLowerCase();
    var directoryPath = windowsTemp.substring(2).trim();
    process.env.tmpDir = "/mnt/".concat(driveLetter).concat(directoryPath);
    //process.env.tmpDir = "/mnt/c/tmp";
}
```

**Comment by jstarks** [comment]
Glad that works. On the newest insider builds, there is a tool called wslpath that can do the Win32 -> WSL path conversion for you (and will be correct even if the user changed their drvfs mounts to be somewhere else). If you want to use that, you would run wslpath on the result of the cmd invocation.

This would be more correct but only works in newer builds. You may need to detect this case by seeing if /bin/wslpath exists. I’m not sure if it’s worth the trade off for you.

**Comment by benhillis** [comment]
Wslpath and wslenv are in 1803.
