### ISSUE TITLE
Pasting unicode characters not supported by font into conemu results in invalid raw data

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2765]
Following up on #2286, there is another issue where pasting content that is not supported by the current console font results in invalid data being transferred to WSL.

Note that this is _not_ a report about broken _rendering_ of unicode/emoji glyphs, etc. This is about the raw data that is being transferred become corrupt on paste.

As an example, copy this emoji to the clipboard 🤷 then follow the steps below:

```bash
$ cat | hexdump -C
```
At the `cat` prompt, paste the emoji from the clipboard, press `Enter`, then hit `ctrl+D` to end the `cat` read from stdin. 

The results are 

```bash
mqudsi@Blitzkrieg /m/d/G/paypal> cat | hexdump -C
��
00000000  ef bf bd ef bf bd 0a                              |.......|
00000007
```

While the 🤷 cannot be rendered by my console font, that should not preclude it from being used (though not correctly represented). However, in this case the "symbol not found" unicode character is put in its place, and that is what comes out in the resulting hex dump.

**Comment by zadjii-msft** [comment]
I've filed a bug to investigate this more, but this might end up being a feature request.

**Comment by Brian-Perkins** [comment]
This should be resolved as of Insiders Build [17101](https://github.com/MicrosoftDocs/WSL/releases/tag/17101).
