### ISSUE TITLE
Visual Studio 2015 on Windows 8.1 Connection Failure

### ISSUE THREAD

**Issue by pattydl** [Microsoft/WSL#2766]
am having an issue with "Connect to Linux" on Windows 8.1 (version 6.3.9600 - no WSL) and VS 2015 (version 14.0.25431.01 Update 3). I installed this: https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment and followed these instructions: https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#installation.

I can Putty to the Linux SuSe system just fine (SUSE Linux Enterprise Server 12 SP3 64-bit) using the same IP address, port, and username/password settings, but not using the "Connect to Linux" dialog. I created a private key using PuttyGen (as the demo uses), and also using "ssh-keygen -t rsa" and copied the files over using winscp, but neither worked. I get "Authentication failure: Please make sure credentials are correct" using the user/password, and "An error occurred using private key 'c:\x.ppk'. Please make sure you are using an openssh format compatible private key."

**Comment by pattydl** [comment]
I am having an issue with "Connect to Linux" on Windows 8.1 (version 6.3.9600 - no WSL) and VS 2015 (version 14.0.25431.01 Update 3). I installed this: https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment and followed these instructions: https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#installation.

I can Putty to the Linux SuSe system just fine (SUSE Linux Enterprise Server 12 SP3 64-bit) using the same IP address, port, and username/password settings, but not using the "Connect to Linux" dialog. I created a private key using PuttyGen (as the demo uses), and also using "ssh-keygen -t rsa" and copied the files over using winscp, but neither worked. I get "Authentication failure: Please make sure credentials are correct" using the user/password, and "An error occurred using private key 'c:\x.ppk'. Please make sure you are using an openssh format compatible private key."

**Comment by therealkenc** [comment]
> Windows 8.1 (version 6.3.9600 - no WSL)

You probably want [over here](https://github.com/Microsoft/VSLinux).
