### ISSUE TITLE
Fork bomb causes GSOD

### ISSUE THREAD

**Issue by fox8091** [Microsoft/WSL#2767]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17046.1000
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
:(){ :|:& };:
* What's wrong / what should be happening instead
A process limit should be implemented

**Comment by erkinalp** [comment]
You have learned Windows lacks a OOM killer the hard way.

**Comment by erkinalp** [comment]
@Microsoft can you close this?

**Comment by sunilmut** [comment]
I cannot repro this on SCU (Spring Creators Update) [build](https://blogs.windows.com/windowsexperience/2018/03/27/announcing-windows-10-insider-preview-build-17133-for-fast/).
