### ISSUE TITLE
After sign-out and sign-in, LxssManager will stall.

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#2768]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17063.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1. Launch Ubuntu.
2. Sign-out from Windows.
3. Sigin-in Windows, again.
4. Launch Ubuntu, again.

* What's wrong / what should be happening instead:
Ubuntu has hang up.
LxssManager service will high CPU load.

[lxcore.zip](https://github.com/Microsoft/WSL/files/1575290/lxcore.zip)

**Comment by Biswa96** [comment]
I analyze those event logs and find two errors:
1. lxcore_kernel: Frame 30: `lsLxpSysFsUnexpectedLookupError.....Sysfs: Unsupported file /sys/fs/selinux`
2. lxcore_service: Frame 18: `VerboseLog.file..linenumber..failurecount..threadid..hr..message..code..function..base\subsys\wsl\lxss\service\lib\lxssiptables.cpp`

Is there any problem with networking or file system? Did you try with a new Ubuntu installed one?

**Comment by 0xbadfca11** [comment]
@Biswa96 Does not solved.
Chkdsk reports problem not found.
Uninstall Ubuntu, and confirm ``CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc`` folder deleted definitely, re-install Ubuntu.
And the problem will be reproduced.

**Comment by onomatopellan** [comment]
I can reproduce the problem too. It works well if you manually stop lxss service before login out. When it hangs it looks like a deadlock, and `sc query lxss` shows service is NOT_STOPPABLE.

**Comment by Biswa96** [comment]
I didn't see any of the problem. I have not the Insider version installed. And I installed Ubuntu with the WSL functions. 
@0xbadfca11Can you try to install a normal distribution without from Windows store? May be the problem only for insider windows. Can anyone try without insider versions?

**Comment by 0xbadfca11** [comment]
@Biswa96 Legacy Ubuntu will also not work too. However, the error 0x800703fa is returned immediately, and LxssManager does not get high CPU utilization.
On build 16299.192 is works well.

**Comment by benhillis** [comment]
I've identified a race condition that could explain LxssManager getting deadlocked during a logoff / login.  I'm working on a fix.

**Comment by 0xbadfca11** [comment]
Not fixed yet in clean installed 17134.5.
A 0x800703fa error occurs until 5 minutes elapse since re-signin or until stop the LxssManager service.

**Comment by 0xbadfca11** [comment]
Treat this issue as duplicate https://github.com/Microsoft/WSL/issues/2576.
