### ISSUE TITLE
Couldn't update wsl (problems with perl)

### ISSUE THREAD

**Issue by dukebarman** [microsoft/WSL#2769]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Try to upgrade wsl

* What's wrong / what should be happening instead:
```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 perl : Depends: perl-modules-5.22 (>= 5.22.1-9ubuntu0.2) but 5.22.1-9 is installed
        Depends: libperl5.22 (= 5.22.1-9ubuntu0.2) but 5.22.1-9 is installed
E: Unmet dependencies. Try using -f.
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libperl5.22 perl-modules-5.22
The following packages will be upgraded:
  libperl5.22 perl-modules-5.22
2 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
2 not fully installed or removed.
Need to get 0 B/6,053 kB of archives.
After this operation, 12.3 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 25474 files and directories currently installed.)
Preparing to unpack .../perl-modules-5.22_5.22.1-9ubuntu0.2_all.deb ...
Unpacking perl-modules-5.22 (5.22.1-9ubuntu0.2) over (5.22.1-9) ...
dpkg: error processing archive /var/cache/apt/archives/perl-modules-5.22_5.22.1-9ubuntu0.2_all.deb (--unpack):
 unable to stat './usr/share/perl/5.22.1/pod' (which I was about to install): Permission denied
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/perl-modules-5.22_5.22.1-9ubuntu0.2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Try to change permissions but it didn't help. Here someone described same problem: https://ubuntuforums.org/showthread.php?t=2378749

**Comment by therealkenc** [comment]
https://ubuntuforums.org/showthread.php?t=2378749

**Comment by dukebarman** [comment]
@therealkenc why did you post same link? This link hasn't got a solution.

But I found the working solution for me. If you see an error like this `unable to stat './usr/share/perl/5.22.1/pod' (which I was about to install): Permission denied` in process of update, you can delete problem files from host Windows. For this case path is:

    C:\Users\WindowsUsername\AppData\Local\lxss\rootfs\usr\share\perl\5.22.1\pod

After delete you can continue updating from WSL shell.

**Comment by therealkenc** [comment]
> @therealkenc why did you post same link?

Because it was the basis for closing.

>  This link hasn't got a solution.

Indeed it doesn't. I did not read [down to](https://ubuntuforums.org/showthread.php?t=2378749&p=13715905#post13715905) "i don't think so... i didn't mention (kinda intentionally) that this is not a real ubuntu distro, but Linux Subsystem for Windows". That was a most unfortunate decision on the part of the issue submitter.

If you post repro steps from a clean install and an strace someone might have a look.
