### ISSUE TITLE
NTFS Extended attributes usage for DrvFs metadata incompatible with Windows API

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#2777]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17063.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
DrvFs with the metadata uses incorrect layout of [FILE_FULL_EA_INFORMATION](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545793.aspx).
Below image is on-disk data.
The UID I use is 290848682 (==0x1155FFAA). And the GID is 1149763686 (==0x44880066).
WSL is reading position that has deviated by 1 byte.
![image](https://user-images.githubusercontent.com/7390559/34262663-5db3901a-e6b0-11e7-84c2-0917d072630b.png)
The image below is read by ZwQueryEaFile().
Can not read data with 1 byte deviated using ZwQueryEaFile(). Windows will replace that with 0x00.
![image](https://user-images.githubusercontent.com/7390559/34262671-6270bbdc-e6b0-11e7-94a3-27ce6143e123.png)

**Comment by SvenGroot** [comment]
Looks like you are correct, unfortunately. We will fix this issue, which unfortunately means that any metadata created by this build will not show up correctly once the bug is fixed.

Sorry for the inconvenience!

**Comment by therealkenc** [comment]
Great find @0xbadfca11

**Comment by 0xbadfca11** [comment]
https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17074
