### ISSUE TITLE
clone() fails with CLONE_UNTRACED or without SIGCHLD

### ISSUE THREAD

**Issue by zeux** [Microsoft/WSL#2781]
This came out of #121 where leak sanitizer part of address sanitizer doesn't work under WSL. To reproduce this in a standalone sample, I extracted this code from lsan:

```
#include <assert.h>
#include <sys/mman.h>
#include <unistd.h>
#include <sched.h>
#include <stdio.h>
#include <errno.h>

int TracerThread(void *)
{
	return 0;
}

int main()
{
	const unsigned kStackSize = 2 * 1024 * 1024;
	void* stack = mmap(0, kStackSize, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
	printf("stack ptr: %p\n", stack);
	pid_t tracer_pid = clone(TracerThread, (char*)stack + kStackSize, CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_UNTRACED, 0);
	printf("tracer pid: %d\n", int(tracer_pid));
	printf("errno: %d\n", errno);
}
```

Compiling & running this under regular Linux makes clone() return a positive PID; running under WSL however returns PID -1:

```
stack ptr: 0x7f3763820000
tracer pid: -1
errno: 22
```

This happens in build 17063

**Comment by jstarks** [comment]
I suspect we don’t yet handle CLONE_UNTRACED.

**Comment by therealkenc** [comment]
I thought that too, but oddly the test case fails even if you drop `CLONE_UNTRACED` from the set.

**Comment by jstarks** [comment]
Oh. Looks like we also don't support non-SIGCHLD signaling without CLONE_THREAD. Which is odd because I added support for that weeks ago. But it turns out it was never merged!

So we'll fix that first, and then we can see if we have time for CLONE_UNTRACED.

**Comment by benhillis** [comment]
Fixed in 17093.

**Comment by zeux** [comment]
Confirmed - this works in 17127.
