### ISSUE TITLE
Failure to update with warning : default stop runlevel arguments do not match rsync Default-Stop values

### ISSUE THREAD

**Issue by AreDubya** [Microsoft/WSL#2782]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
 10.0.16299.125
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

On running `sudo apt-get update` then `sudo apt-get upgrade`, the upgrade fails when setting up rsync.

```Setting up iproute2 (3.12.0-2ubuntu1.1) ...
Setting up rsync (3.1.0-2ubuntu0.3) ...
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match rsync Default-Stop values (none)
 System start/stop links for /etc/init.d/rsync already exist.
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up landscape-common (14.12-0ubuntu6.14.04.1) ...
Setting up landscape-client (14.12-0ubuntu6.14.04.1) ...
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
```

* What's wrong / what should be happening instead:

Update should finish normally.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

[Strace gist](https://gist.github.com/AreDubya/67662e82fe7a4da4b4c834538a85f395)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
#2288 #2702 #2291

**Comment by AreDubya** [comment]
@therealkenc Sorry, I'm not seeing the correlation. Those tickets fail on apt-get upgrade, but they all involve docker and produce different errors. What's the connection? invoke-rc.d?

**Comment by therealkenc** [comment]
Yeah I was looking at `invoke-rc.d`, which is unhappy about runlevels. But you are right, that is just a warning. The hard fail in the `strace` output is:

```
socket(PF_NETLINK, SOCK_RAW, 9)   = -1 EPROTONOSUPPORT (Protocol not supported)
```

Which is #717 #2249 #1383 and many friends. Apologies for the misfire and appreciate the follow up. I should have looked at the `strace` more closely instead of pattern matching on the runlevel warning.

**Comment by therealkenc** [comment]
I'll hold it open since you are just doing an `apt upgrade`, and maybe someone else will hit this. I can't repro here even though I have rsync (plus the kitchen sink) installed. The `SOCK_RAW` fail is clear enough. But scratching my head for a guess on a cause that got you there, and coming up empty.

Suggestion is to start purging stuff you've installed since `apt upgrade` last worked. Maybe it is `landscape`, for example. Or go the other direction from a clean install.

**Comment by AreDubya** [comment]
@therealkenc Thanks for the info and follow up. At the moment I have a fairly fresh install so I don't mind going the clean install route, but I am also curious as to what happened. Thanks for holding this open, I'll update here after trying a couple of things in the hopes the info is helpful for someone. 

I really appreciate the suggestions, I will let you know what happens.

**Comment by AreDubya** [comment]
In the end an uninstall / reinstall was the way to go. I hit an error when trying to uninstall initially, but I performed an install (before completing the uninstall) of the Ubuntu package from the Windows store, then did an uninstall. After that everything seems to be back to normal.

**Comment by therealkenc** [comment]
Thanks for the update. Do keep an eye out for possible reproduction steps, which would probably look something like: "after installing package blah blah, get `policy-rc.d denied execution of start error` during the postinstall scripts". It is a legit enough problem, even if it is ultimately a dupe of one of those cited above. Glad you're up and running though.

**Comment by Davidrjx** [comment]
i have same problem but only warning below in my ubuntu trusty container ,
```
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match rsync Default-Stop values (none)
 Adding system startup for /etc/init.d/rsync ...
   /etc/rc0.d/K20rsync -> ../init.d/rsync
   /etc/rc1.d/K20rsync -> ../init.d/rsync
   /etc/rc6.d/K20rsync -> ../init.d/rsync
   /etc/rc2.d/S20rsync -> ../init.d/rsync
   /etc/rc3.d/S20rsync -> ../init.d/rsync
   /etc/rc4.d/S20rsync -> ../init.d/rsync
   /etc/rc5.d/S20rsync -> ../init.d/rsync
```
is there any solution resolving this?
