### ISSUE TITLE
large mmap() with MAP_NORESERVE fails unless overcommit_memory is 1

### ISSUE THREAD

**Issue by zeux** [Microsoft/WSL#2784]
This came out of #121 where address sanitizer doesn't work out of the box under WSL, requiring setting `/proc/sys/vm/overcommit_memory` to 1. This is because asan tries to map a large memory region with MAP_NORESERVE and PROT_READ|PROT_WRITE and this map fails (curiously, mapping the region with PROT_NONE and doing a following mprotect succeeds).

This program:

```
#include <sys/mman.h>
#include <stdio.h>

int main()
{
	size_t size = 0xdfff0001000;

	void* ptr = mmap(0, size, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0);
	printf("mmap => %p\n", ptr);
}
```

Prints a valid pointer on a real Linux system with overcommit_memory set to 0. Under WSL, mmap returns -1. Setting overcommit_memory to 1 fixes this but the expected behavior is that this code works without changes under WSL.

**Comment by jstarks** [comment]
This should be simple to fix.

**Comment by benhillis** [comment]
Fixed in 17093.

**Comment by zeux** [comment]
Confirmed - this is fixed in 17127.
