### ISSUE TITLE
After switching user unable to launch visual studio code from terminal.

### ISSUE THREAD

**Issue by gulshanmudgal** [Microsoft/WSL#2785]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  switched to a different user and tried to launch visual studio code from terminal by typing the command "code" at the terminal but it's not launching.

* when i run the code without switching any user it works just fine but when i try to run code after switching it doesn't work.

* gulshan@Gulshan:~$ code

gulshan@Gulshan:~$ su hadoop
Password:
hadoop@Gulshan:/home/gulshan$ code
No command 'code' found, did you mean:
 Command 'tcode' from package 'emboss' (universe)
 Command 'node' from package 'nodejs-legacy' (universe)
 Command 'cobe' from package 'python-cobe' (universe)
 Command 'cde' from package 'cde' (universe)
 Command 'cdde' from package 'cdde' (universe)
 Command 'ode' from package 'plotutils' (universe)
code: command not found
hadoop@Gulshan:/home/gulshan$

![image](https://user-images.githubusercontent.com/11193392/34320993-cfafc51e-e82a-11e7-9f45-019670db496e.png)

(https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
`code` is not in your $PATH for that user. Do:
```
$ su hadoop
$ whereis code  # this will come up empty
$ echo $PATH
```

**Comment by gulshanmudgal** [comment]
got this:

hadoop@Gulshan:/home/gulshan$ whereis code
code:
hadoop@Gulshan:/home/gulshan$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/java/jdk1.8.0_151/bin:/usr/local/hadoop/bin:/usr/local/hadoop/sbin
hadoop@Gulshan:/home/gulshan$

**Comment by therealkenc** [comment]
Okay that's at least a little unusual. How about:
```
$ ls -l /usr/bin/code
```

**Comment by gulshanmudgal** [comment]
ls: cannot access '/usr/bin/code': No such file or directory

**Comment by therealkenc** [comment]
There's your problem. Code is not in:

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/java/jdk1.8.0_151/bin:/usr/local/hadoop/bin:/usr/local/hadoop/sbin`

**Comment by gulshanmudgal** [comment]
so what is the solution?

**Comment by therealkenc** [comment]
Probably the simplest would be to add the path to your `code` executable to `$PATH` for user hadoop. Have a look at your default user's `$PATH` to see what was pulled in. Something like:
```
export PATH="$PATH:/mnt/c/Program Files/Microsoft VS Code/bin"
```

If you want to get fancy there is a discussion on Stack Exchange about `sudo`/`su` and paths [here](https://unix.stackexchange.com/questions/8646/why-are-path-variables-different-when-running-via-sudo-and-su).

**Comment by gulshanmudgal** [comment]
i need to launch it as Sudo Code

any solution?

**Comment by liyunchou** [comment]
The problem seems still exists in WSL2. After add VS Code path to /env/environment, root user can run 'code . ' command but ‘sudo code .’ still throws command not found

**Comment by betoxx** [comment]
how does you solve it? I have the same issue after su
