### ISSUE TITLE
setpgid() fails with EPERM if pgid is exited but not reaped (it should succeed)

### ISSUE THREAD

**Issue by ridiculousfish** [Microsoft/WSL#2786]
This is a reduced test case for some behavior that we're seeing in the fish shell. [One issue in fish](https://github.com/fish-shell/fish-shell/issues/4235), [previous WSL issue](https://github.com/Microsoft/WSL/issues/1210) which was considered fixed but is not.

fish handles pipeline jobs by making the first process the group leader for all processes in the job, via `setpgid`. However if the group leader has exited (but not yet been reaped), the `setpgid()` call fails with EPERM on WSL, where AFAICT it ought to succeed (it does on macOS and Linux).

Tested on Win10 build 16299.rs3_release.170928-1534.

To reproduce: compile and run [run.c](https://github.com/ridiculousfish/wsl-pgrp-race/blob/master/run.c) as `cc run.c; ./a.out` On WSL this will output some errors and hang. On macOS and Linux it succeeds.

You can simulate fish's ugly workaround by running `./a.out keepalive`. This keeps the parent process alive until the child has joined it, which prevents the error.

**Comment by therealkenc** [comment]
I call this the Rick Grimes problem. Like #1353 ([message](https://github.com/Microsoft/WSL/issues/1353#issuecomment-260401046)). From `ps` on Real Linux:

```
11006 pts/0    S+     0:00 ./a.out
11007 pts/0    Z      0:00 [a.out] <defunct>
```

**Comment by ridiculousfish** [comment]
![21niaq](https://user-images.githubusercontent.com/920838/34332190-e74e29fa-e8e2-11e7-80a7-870312e8b13f.jpg)

**Comment by Brian-Perkins** [comment]
This should work better starting in Insider Build [17713](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17713)
