### ISSUE TITLE
sysctl failed to get properties no such interface 

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/WSL#2787]
Build: 17063 

any sysctl command is met with sysctl failed to get properties no such interface

Sysctl should allow me to see the status of services without error as well as modify and enable

sort of work around
 sudo rsync -a /lib/systemd/system/  /etc/systemd/system/

all .service files in wsl are by default located in the /lib folder mentioned above whilst they should be in the /etc equivalent. doing the above command fixes the above initial error but we are instead met with   

when running systemctl status
Failed to read server status: Operation not permitted
regardless of whether I run as sudo or not.

subsequently attempting to work with properties gives a subsequent error
Failed to get properties: Access denied
most work around's suggest setenforce 0 to get past said permission error but Selinux is inoperable at this time in wsl. 

If the wsl team could move the file locations and fix permissions we might see systemd start.

**Comment by therealkenc** [comment]
> If the wsl team could move the file locations and fix permissions we might see systemd start.

There is an open issue on `systemd` #994. I'll get you over there.
