### ISSUE TITLE
WSL/Ubuntu : Can't Run Build Task for GCC 7.2.0 Compiler.

### ISSUE THREAD

**Issue by sus007** [Microsoft/WSL#2792]
* Operating System and version: **Windows 10 Pro Insider Preview / Version: 1709 / OS-BUILD: 17025.1000**
* VS Code version: 
    * **Version 1.20.0-insider**
    * Commit f9115349ef09cfef2bed669680d10ac58b490dce
    * Date 2017-12-21T16:36:58.030Z
    * Shell 1.7.9
    * Renderer 58.0.3029.110
    * Node 7.9.0
    * Architecture x64
* C/C++ extension version: **Version 0.14.5: December 18, 2017**  
#### As you can see I've both versions of the GCC compiler installed, GCC 5.4 (Default) and GCC 7.2 (Newer), 
![image](https://user-images.githubusercontent.com/7630815/34403352-cb8344d6-ebcf-11e7-82d6-ac201a9139b5.png)  

#### But, still I couldn't **Run Build Task** with my GCC 7.2 from within my VSCode. 
![image](https://user-images.githubusercontent.com/7630815/34403448-6a8dd564-ebd0-11e7-9c31-1ee7dd3585c3.png)

#### My **`tasks.json`** file looks like this
![image](https://user-images.githubusercontent.com/7630815/34403513-bb09a2d4-ebd0-11e7-9762-57a0fe36f23e.png)

**Comment by sus007** [comment]
I've set `bash.exe` as my default terminal for VSCode. I can execute both of the commands `g++` & `g++-7.2` from my Ubuntu/Bash Terminal, but only `g++` command from within my VSCode. Why's that ?
> #### With only `g++` command in `tasks.json`
![image](https://user-images.githubusercontent.com/7630815/34424201-fae78ef6-ec49-11e7-9cef-3d28f416ad16.png)  

> #### With `g++-7.2` command in `tasks.json`
![image](https://user-images.githubusercontent.com/7630815/34424264-664cfbb8-ec4a-11e7-92e8-1f8cbddf7425.png)

> #### Both commands in `bash.exe`
![image](https://user-images.githubusercontent.com/7630815/34424412-727456ba-ec4b-11e7-81e7-a5831d3b0ba2.png)

**Comment by onomatopellan** [comment]
You should try to upgrade to build 17063 first.

What does console show if you type this?
`ll $(which g++)*`

**Comment by sus007** [comment]
@onomatopellan  Since I've my **Ubuntu bash/console** as the default terminal for **VSCode**, it doesn't matter. They both display the same result. 
![image](https://user-images.githubusercontent.com/7630815/34450678-dc448474-ed37-11e7-8cf6-90cfd3fe5932.png)
The thing is that VSCode's task runner **(`tasks.json`)** isn't allowing me to **`Run Build Task`** with the **latest** GCC Compiler(7) for some reason. Which terminal/bash does **VSCode's Task Builder** use to run/build the task ?

**Comment by therealkenc** [comment]
It doesn't look like your `g++-7` is not in `usr/bin`. You should be seeing something like:
```
$ ll $(which g++)*
lrwxrwxrwx 1 root root      5 Feb 11  2016 /usr/bin/g++ -> g++-5*
-rwxr-xr-x 1 root root 919832 Sep 13 20:35 /usr/bin/g++-5*
lrwxrwxrwx 1 root root     22 Aug 20 12:21 /usr/bin/g++-7 -> x86_64-linux-gnu-g++-7*
```

You can install g++7 with...
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt install gcc-7 g++-7
```
... and you should get the correct config automatically. If not use [`update-alternatives`](http://man7.org/linux/man-pages/man1/update-alternatives.1.html) or just set up the symlinks yourself.

**Comment by sus007** [comment]
@therealkenc I've actually installed the GCC 7.2 by externally downloading a tar file, not through aptitude so, will I still be able to `Run Build Task` from within the VSCode if I set up the symlinks properly ? If it's that then can you tell me what exactly should I do ?

**Comment by onomatopellan** [comment]
@sus007 If you already have GCC 7.2 in the PATH you can create a symlink like this
`sudo ln -s $(which g++-7.2) /usr/bin/g++-7`
then you should can use `g++-7` from Vscode

**Comment by therealkenc** [comment]
That should work. Alternately you can set up your custom environment in `tasks.json`. Lots about that and more [over here](https://code.visualstudio.com/community). But your smart play is still to install it from the PPA before getting fancy. Bonne chance.

**Comment by sus007** [comment]
@therealkenc Can you tell me how to **completely uninstall** the GCC-7.2 that I installed by building a makefile from a downloaded zip file ?

**Comment by therealkenc** [comment]
> Can you tell me how to completely uninstall the GCC-7.2 that I installed by building a makefile from a downloaded zip file ?

`sudo rm -fr /usr/local/gcc-7.2.0`, or whatever path you put it. Then undo whatever you might have done to your `.bashrc` with `vim` or `nano`. But that question is better asked in the comment section of the page you linked because it is their instructions not mine.

> But I can't still figure out how to purge this installation entirely so that I can install GCC as you previously described.

You probably don't _strictly speaking_ need to purge it in order to install the PPA. In your vscode tasks scenario, the task runner isn't finding your custom g++-7 anyway. But yes, you'll probably have less grief in the long run if you don't have `$PATH` and `$LD_LIBRARY_PATH` modifications competing with the installation in `/usr/bin`.
