### ISSUE TITLE
WslRegisterDistribution() creates init with empty .tar.gz file

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#2794]
Windows version 10.0.16299.15.

* **Steps to reproduce:** 
 1. At first, one needs a Linux environment or simply a TAR command line tool (or Busybox or Cygwin). Then create an empty `.tar.gz` file with this command: `tar -czf /mnt/d/empty.tar.gz --files-from=/dev/null`. You may change the file path of the created `.tar.gz` file .But it important to use `-z` option for gzip. 
 2. Make a program with [WslRegisterDistribution()](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826870(v=vs.85).aspx) function. Use that `empty.tar.gz` in 2nd parameter of that function. Run that program.
 3. After one second, register that distribution as default with `wslconfig /s distro_name`. Run `wsl` command to start that, output will be `Error: 0x80070002`. 
 4. Open the `rootfs` folder where you install it. You can see a `init` file (~50 KB) in `rootfs` folder. 

* **Expected result:** That function should be somehow check the validity of that .tar.gz file.

* Download `init` file: [init.zip](https://github.com/Microsoft/WSL/files/1594257/init.zip)
SHA1 of init.zip file:  EE6008A77DC02D0743FD862993318F039CB949D6
SHA1 of init file: 16D2B5AA911C1196BA6A5F53B965C0269C170064

**Comment by therealkenc** [comment]
Seems like bydesign from here. Your distribution is perfectly valid; which is to say, it is a well formed tarball.

> That function should be somehow check the validity of that .tar.gz file.

No, _you_ should check the validity of your `.tgz` before calling it, if _you_ consider an empty tarball invalid. `WslRegisterDistribution()` has no idea whether the distro given is valid or not; or how to define valid and invalid. I might want an empty distribution registered. Or maybe my distro consists of one statically linked program `/kitties` that streams cat pictures out port 80, and does nothing else.

> Run wsl command to start that, output will be Error: 0x80070002.

Granted this error from `wsl.exe` leaves a lot to be desired. `wsl.exe` should propagate a meaningful error string from WSL `init` to `stderr`, much like analogous `ssh`/`sshd` (or `rsh`/`rshd` and `telnet`/telnetd` in simpler times). There is a side discussion about that in some early-ish issue# but I can't find it. Though, different ask. 🐱

**Comment by Biswa96** [comment]
>distribution is perfectly valid; which is to say, it is a well formed tarball.

That's not a distribution, the .tar.gz file is empty fill with `NULL` bytes 🤭. Is it normal that the function allow empty tarballs?
The `Error: 0x80070002` may be occurred due to failure of finding any file. With process monitor, I use `Result: NAME NOT FOUND` as a filter and find that `wsl.exe` fetches `lib64` directory at runtime. 

BTW, I find an interesting fact. When I install SUSE or SLES ( or distros other than Ubuntu) from Store, the `init` file always contains `GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609` in `.comment` section. What's that?

**Comment by therealkenc** [comment]
> That's not a distribution, the .tar.gz file is empty fill with NULL bytes 🤭.

Actually it is a well formed tarball with zero files, but why quibble.

> Is it normal that the function allow empty tarballs?

Depends on your definition of normal. `tar(1)` likewise does not report an error if you try to unpack an archive with no files. `WslRegisterDistribution()` _could_ look at the archive and throw an error if it contains no files (contrary to `tar(1)`), and succeed if it contained say one file. But in either scenario, calling `wsl.exe {UID}` on the resulting registered installation would probably error out.

> The Error: 0x80070002 may be occurred due to failure of finding any file.

Correct.

**Comment by Biswa96** [comment]
Oh, I see that `init` was statically linked in insider build and I'm using the normal one. I'll try that. @jstarks Can you mention which insider build?
But what about the `GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609` in `.comment` section? See this screenshot which shows _both LxssManager.dll` and `init`_ has that comment. May be that DLL is responsible for creation of that `init` file.

![lxssmanager_and_init](https://user-images.githubusercontent.com/31443074/34459785-fd48d416-ee1f-11e7-8b83-0a20be79a23e.PNG)

**Comment by therealkenc** [comment]
> Can you mention which insider build?

A user [confirmed](https://github.com/Microsoft/WSL/issues/229#issuecomment-342817247) the change on "the latest" Insider Build on Nov 8. So something like 17025 or 17035. Academic.

> May be that DLL is responsible for creation of that init file.

Correct. The service creates WSL `init` on instantiation. If you `sudo rm /init` (unlink it), it will magically reappear the next time WSL is instantiated.

**Comment by Biswa96** [comment]
I find another way to create empty distribution. This procedure tricks LxssManager.dll to create a `init` file. I think LxssManage.dll has an `init` file built-in its source code (by-design). I ran these commands:
```
set X=HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
set Y={12345678-1234-5678-0123-456789abcdef}
reg add "%X%" /V "DefaultDistribution" /T REG_SZ /D "%Y%" /F
reg add "%X%\%Y%" /V "DistributionName" /D "empty" /F
reg add "%X%\%Y%" /V "BasePath" /D "C:\MyFiles" /F
reg add "%X%\%Y%" /V "State" /T REG_DWORD /D "1" /F
wsl.exe
explorer.exe "C:\MyFiles\rootfs"
```

OK, I found my issue answer in your previous comment. Closing...

**Comment by Biswa96** [comment]
@therealkenc I've tested the new insider build now. The LxssManager.dll gets bigger in size. Also `init` file becomes ~81KB whereas the old one was ~51KB. 

🔊 BTW, the new LxssManager.dll contains `bsdtar`. I opened that DLL with Resource Hacker, extarct the resource from RCDATA, run the bsdtar in WSL and it works.

**Comment by jstarks** [comment]
Yes, we now use bsdtar to extract the distribution tar rather than our own tar implementation.

**Comment by therealkenc** [comment]
@jstarks - I have been meaning to ask, what is the magic commandline switch?

```
C:\Users\ken\source>tar xpf dev.tar
dev/fd: Can't create '\\\\?\\C:\\Users\\ken\\source\\dev\\fd'
dev/kmsg: Can't create '\\\\?\\C:\\Users\\ken\\source\\dev\\kmsg'
dev/lxss: Can't create '\\\\?\\C:\\Users\\ken\\source\\dev\\lxss'
dev/lxssclient: Can't create '\\\\?\\C:\\Users\\ken\\source\\dev\\lxssclient'
...
```

**Comment by jstarks** [comment]
Ah, the bsdtar in Win32 (tar.exe) isn’t capable of that (yet?). We use a separate Linux-compiled bsdtar inside WSL to extract the distribution.

**Comment by Biswa96** [comment]
@therealkenc You can do that with the bsdtar extracted from LxssManager.dll. Open that dll in [Resource Hacker](http://www.angusj.com/resourcehacker/), extract two files from RCData folder, the bigger one is bsdtar and the smaller one is new init file. Run that bsdtar with wsl.exe.

@jstarks Can I replace the old LxssManager.dll with the newer one from an insider builds?

**Comment by therealkenc** [comment]
> You can do that with the bsdtar extracted from LxssManager.dll.

No not _that_ `tar`.... We are talking about [Win32 `tar`](https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/). If I wanted an ELF-64 `tar` I would compile or download one, not dig it out of a dll. The question was mostly trolling in jest (I should have winked). Obviously there is no magic commandline switch for Win32 `tar`. Yet.

**Comment by benhillis** [comment]
@Biswa96. No, if you want the new service dll you will need to upgrade your entite windows build.

**Comment by Biswa96** [comment]
>our own tar implementation
@jstarks Can you metion with which API I can extract tat.gz file in Windows?
