### ISSUE TITLE
Launching process under lldb fails in WSL

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/WSL#2796]
Microsoft Windows [Version 10.0.16299.125]

I have lldb 3.8.0 installed

On regular Ubuntu, I can use it successfully to run a process, eg:

![image](https://user-images.githubusercontent.com/6385855/34471585-5fa4e180-ef02-11e7-9015-5b213832c8a1.png)

On WSL Ubuntu doing the same thing seems to hang ... Ctrl C and Ctrl Break do not do anything, hitting enter just moves the cursor down. I have to pkill lldb from another terminal:

![image](https://user-images.githubusercontent.com/6385855/34471596-94565e36-ef02-11e7-8a6e-dc27169ade4b.png)

strace suggests it's a process launch issue:
```
dan@danmose2:~/dotnetU$ strace -o lldb.strace -f lldb echo 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/lldb/__init__.py", line 123, in <module>
    import six
ImportError: No module named six
(lldb) target create "echo"
Current executable set to 'echo' (x86_64).
(lldb) settings set -- target.run-args  "1"
(lldb) run
error: process launch failed: 'A' packet returned an error: 8
```

Is this scenario supported on WSL?

**Comment by therealkenc** [comment]
#2028 `PTRACE_TRACEME`

**Comment by danmosemsft** [comment]
Thanks, don't know how I didn't see that one.
