### ISSUE TITLE
Error 0x80070005 when %LocalAppData% encrypted with EFS

### ISSUE THREAD

**Issue by MarkCallow** [microsoft/WSL#2797]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Installing Ubuntu (just after entering the requested user name for Ubuntu) or, later, running Ubuntu (bash.exe).

* What's wrong / what should be happening instead:
I get error 0x80070005 instead of a bash command prompt.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
Not sure how to do this when I can't get a command prompt in the first place.

After reading some other threads about error 0x80070005 I got suspicious that it might be because I had my %AppData% and therefore %LocalAppData% encrypted with EFS. I unencypted it and after that bash runs and gives me a command prompt.

It looks like Ubuntu must be accessing the file system at a level below the Windows NTFS driver and therefore getting confused by EFS'ed files. This raises the question, will WSL work on a BitLocker encrypted volume? How can I have my files encrypted and use WSL?

**Comment by msc-** [comment]
There is no `%LocalAppData%\lxss` folder. Where does WSL now store the user data? I was thinking to rencrypt `%AppData% except for the WSL folder.

**Comment by DarthSpock** [comment]
Did you enable WSL in Programs and Features? If you haven't, enable it and then install Ubuntu from the Store. If there is still an issue with EFS and Bitlocker (haven't really noticed any utilizing EFS myself, haven't tried using Bitlocker) then create a new issue.

**Comment by msc-** [comment]
Yes. I did exactly that: enabled WSL then installed Ubuntu from the store.

Haven't tried BitLocker yet for various reasons.  (This question is now one of the reasons.)

Why should I create a new issue? This _is_ a new issue specific to EFS.

**Comment by DarthSpock** [comment]
Error code usually means bad install so I assumed you forgot to enable it.
You also are supposed to reboot after enabling before installing distros.
If you did this as well, I'd try an app repair and relaunch from Ubuntu.
Worse case scenario you can run lxrun /uninstall and remove all data and
reinstall. There is an offline version you can use if the Store version
isn't working and see if that works. Just get it linked to the Store as
soon as able to ensure updates. I recommend disabling EFS when you
reinstall for your entire C:/ drive as appdata isn't where distros install
to but the drive is. You can turn on EFS again and see if you're still
having issues.

On Jan 2, 2018 15:the 59, "Mark Callow" <notifications@github.com> wrote:

Yes. I did exactly that: enabled WSL then installed Ubuntu from the store.

Haven't tried BitLocker yet for various reasons. (This question is now one
of the reasons.)

Why should I create a new issue? This *is* a new issue specific to EFS.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/WSL/issues/2797#issuecomment-354873809>, or mute
the thread

**Comment by msc-** [comment]
I did not forget to enable WSL. I rebooted after enable and before install. I have twice removed (using Start->Settings->Apps) and reinstalled Ubuntu from the store. It was broken after each install. It only started functioning after I removed encryption from %AppData%. It started working immediately after I had done that. Nothing else on the system was changed. No reinstall or reboot was necessary.

I can't see any point to trying `lxrun /uninstall` as Ubuntu is now working except for " cannot read symbolic link" errors on links, e.g. `My Documents`  when I do `ls /mnt/c/Users/<My Windows User name>`. I also can't afford to keep "disabling" and enabling EFS. It took about 30 minutes just to "disable EFS", i.e. decrypt, %AppData%. If someone answers my question about the current location of the `lxss` folder (whatever its current name) I am willing to encrypt all of %AppData% but that and try that. I am not prepared to re-encrypt the whole of %AppData% as I am nearly certain Ubuntu will stop working again. 

I had %USERPROFILE% encrypted not the whole of the C drive. I now have %USERPROFILE% encrypted not including %AppData%. So I do not think distro installation will be a problem.

ISTM that WSL/Ubuntu is broken in the face of EFS. If it won't work with all but the `lxss` folder of %AppData% encrypted I will have to give up on WSL.

I believe this is a real bug.

**Comment by msc-** [comment]
I tried again to find the files in %AppData%. I realized that as well as unchecking "Hide protected system files", I needed to click the "Apply to all Folders button". After that a search for "lxss" found results: files called `lxss` and `lxssclient` in

`C:\Users\mark\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\temp\{2b2acd24-f7ae-4dba-a0c3-bcfc140e679d}\0000000000000002_tmpfs`

So I reencrypted my `%AppData%` folder. I ran Ubuntu which quit with a "System cannot open the file or device specified error".  I then decrypted all of

`C:\Users\mark\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc`

After that Ubuntu runs.

Conclusion WLS/Ubuntu does not work when its own files are EFS encypted. Whether this is a bug or an unfixable design flaw I don't know.  Presumably this means anything saved in my Ubuntu home directory will not be encrypted.

I would love a definitive answer about BitLocker.

**Comment by jstarks** [comment]
We will look into this. Although this is not expected, I can think of a few reasons EFS may have problems.

The good news is that Bitlocker is fully tested and supported. We use Bitlocker on our development machines.

**Comment by msc-** [comment]
Thanks for the answer about BitLocker. Now if I could just find an easy way to make it work with BootCamp ...

**Comment by istvan-ujjmeszaros** [comment]
I have the same issue. WSL worked fine, but I have enabled encryption on my user directory yesterday (by right clicking on my user folder and then select Properties, and then "Advanced..." on the General tab, and then checking "Encrypt contents to secure data"), and now getting "Access is denied." error when trying to run wsl so I can't use it anymore.
Do we need to add a new user under Security to be able to access the encrypted CanonicalGroupLimited.Ubuntu18.04onWindows_xxxxxxxxxxxxx folder with WSL? Or do we have to skip this entire folder from the encryption for wsl to work properly?
