### ISSUE TITLE
Random bugcheck in LXCORE every 3-6 days during idle time (night)

### ISSUE THREAD

**Issue by heldchen** [Microsoft/WSL#2798]
**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

ideling during night-time, lxcore bugchecks and pc reboots

* What's wrong / what should be happening instead:

shouldn't bugcheck :)

3 minidumps (26.12., 31.12., 02.01.) sent to secure@microsoft.com referencing this github issue. coincidentially the evening before I noticed NisSrv.exe starting to leak memory (commit size > 5gb and increasing). IIRC noticed the same thing before the dec 26th crash.

**Comment by sunilmut** [comment]
@heldchen -  Thanks for sending over the dump. This is duplicate of #2801. Using that as base since it has detailed repro steps. We have a local repro and should have a fix soon.

**Comment by heldchen** [comment]
thanks, will watch the other issue!
