### ISSUE TITLE
Possible to mount multiple drives on the same mount point; should fail

### ISSUE THREAD

**Issue by cerebrate** [Microsoft/WSL#2800]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.17063.0

* What you're doing and what's happening: 

It is possible to mount a drive - even the same drive - multiple times on the same mount point, thus:

```
# avatar @ ATHENA in ~ [7:33:10] C:1
$ mount
rootfs on / type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
A: on /mnt/a type drvfs (rw,noatime,uid=1000,gid=1000)
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
D: on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000)
\\calmirie\home\avatar on /mnt/z type drvfs (rw,relatime,uid=1000,gid=1000,umask=22,fmask=111)
\\calmirie\Our on /mnt/y type drvfs (rw,relatime,Documents)
\\calmirie\Folders on /mnt/x type drvfs (rw,relatime,umask=22,fmask=111)

# avatar @ ATHENA in ~ [7:40:33]
$ sudo mount -t drvfs '\\calmirie\Folders' /mnt/x -o metadata,umask=22,fmask=111

# avatar @ ATHENA in ~ [7:40:55]
$ mount
rootfs on / type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
A: on /mnt/a type drvfs (rw,noatime,uid=1000,gid=1000)
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
D: on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000)
\\calmirie\home\avatar on /mnt/z type drvfs (rw,relatime,uid=1000,gid=1000,umask=22,fmask=111)
\\calmirie\Our on /mnt/y type drvfs (rw,relatime,Documents)
\\calmirie\Folders on /mnt/x type drvfs (rw,relatime,umask=22,fmask=111)
\\calmirie\Folders on /mnt/x type drvfs (rw,relatime,umask=22,fmask=111)
```

After doing so, the mount point functions normally; if two different drives are mounted, the contents of later one is shown at the mount point, and the previous one is ignored. This can be repeated for an arbitrary number of mounts on the same mount point.

If `umount /mnt/x` is then run, only the latest of the mounts disappears, and the mount point continues to function displaying the contents of the most recently mounted drive at that point. To return to an unmounted state, umount must be run for that mount point as many times as mount was,

* What's wrong / what should be happening instead:

Attempting to mount a drive on an mount point currently in use should return EBUSY, per the mount(2) documentation.

**Comment by SvenGroot** [comment]
This is expected behavior; real Linux allows this despite what the mount(2) man page says.

In reality, EBUSY is only returned if you try to mount the exact same file system instance on the same mount point. This can happen e.g. with single instance file systems such as sysfs and devpts. DrvFs reuses the same instance when possible if you mount a local drive, but for UNC paths a new instance is always created so you can in fact mount it multiple times on the same mount point.

This is not a bug; whenever the tested behavior of real Linux diverges from the documentation, we always do what Linux does.
