### ISSUE TITLE
GSOD when installing ghc-mod

### ISSUE THREAD

**Issue by n3dst4** [Microsoft/WSL#2801]
* Your Windows build number:  
    ~Microsoft Windows [Version 10.0.17063.1000]~ 
    ~Microsoft Windows [Version 10.0.17074.1000]~
    Microsoft Windows [Version 10.0.17074.1002]

* What you're doing and what's happening: 

I'm trying to install and run the Haskell IDE-integration tool `ghc-mod`, using the Haskell build tool "stack".

1. Open Ubuntu 16.04 from Microsoft Store
2. Run
    ```
    sudo apt-get update
    sudo apt-get upgrade
    ```
3. Install [stack, the Haskell build tool](https://docs.haskellstack.org/en/stable/README/), by running 
    ```
    wget -qO- https://get.haskellstack.org/ | sh
    ```
4. Create a dummy project and build it
    ```
    stack new foo simple --resolver=lts-9.3
    cd foo
    stack setup # this will take a long time, like 20 mins
    stack build
    ```
5. If all has worked so far, make sure you've saved your work and closed any other windows, and then run:
    ```
    stack build ghc-mod
    ```

* What's wrong / what should be happening instead:
![img_0327](https://user-images.githubusercontent.com/280206/34491206-7bb133d2-efda-11e7-9fd4-cc9bde026f9b.jpg)

Windows crashes (green screen of death). I have replicated this on two machines.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

N/A

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@n3dst4 - Thanks for the detailed repro steps. I have a local repro. We will be submitting a fix for this soon.

**Comment by n3dst4** [comment]
Just to confirm, this crash is still present in 17074 (I wasn't expecting a fix yet, just updating the build number.)

**Comment by n3dst4** [comment]
@benhillis and @sunilmut Thank you. I just tried this on 17083 and it works great 👍

**Comment by Brian-Perkins** [comment]
Fixed for RS3 with [KB4058258](https://support.microsoft.com/en-us/help/4058258/windows-10-update-kb4058258).
