### ISSUE TITLE
GSOD on build 17063 while running CLion on WSL

### ISSUE THREAD

**Issue by Gabrielcarvfer** [Microsoft/WSL#2802]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17063.1000]

* What you're doing and what's happening
I'm not sure on how to reproduce it yet, but got 3 GSODs while running JetBrain's CLion on WSL, that worked just fine on previous builds. Tried on a different machine, and got the same GSOD.

I've sent 3 minidumps to secure@microsoft.com.

**Comment by sunilmut** [comment]
@Gabrielcarvfer - Thanks for sending over the dumps. We have received them.

**Comment by sunilmut** [comment]
This is duplicate of #2801
