### ISSUE TITLE
Credentials used to access network shares and install dependencies

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#2803]
Using Ubuntu 16.04 TLS from Microsoft Store and Windows version is 10.0.16299.125.

I can mount a NTFS network drive using:

`sudo mount -t drvfs '\\server\share\' /mnt/x`

I can navigate through it just fine and to the project I am working on.

However, for example, when I try to add a `virtualenv` to it I run into permission errors (this problem is not specific to `virtualenv` as it occurs with `npm install` too):

`virtualenv -p python3.6 .venv`
`sudo virtualenv -p python3.6 .venv`

I get the following:

```
Already using interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local'
New python executable in /mnt/x/webapps/current/client/.venv/bin/python3.6
Also creating executable in /mnt/x/webapps/current/client/.venv/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 1370, in install_python
    os.symlink(py_executable_base, full_pth)
PermissionError: [Errno 1] Operation not permitted: 'python3.6' -> '/mnt/x/webapps/current/client/.venv/bin/python'
```

The directory being installed to has Everyone with read, write, modify, etc. (but not full control).

Do not run into this issue when running the same commands on `C:\`. 

For both mounts, it has user:group as `root` and `sudo chown -R` does not do anything.

Anyway, I guess I am curious what credentials are being used by WSL to install dependencies. Seems like it would just be the same I use to login to the workstation, but not sure.

There is this bit regarding the filesystem in WSL:

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

> WSL does not have any way to specify which credentials to use to connect to a network share. If you need to use different credentials to connect to the server, specify them in Windows by navigating to the share in File Explorer, using the Windows Credential Manager, or the net use command. The net use command can be invoked from inside WSL (using net.exe use) via interop. Type net.exe help use for more information on how to use this command.

Not entirely clear how I would use it to change credentials (if I even need to).

Since upgrading to Windows version 10.0.16299.125. NPM is even having issues installing on `C:\` where as it did not before and it is related to `acorn`. On the network share the error is the following:

```
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall symlink
npm ERR! Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/mnt/x/webapps/current/client/node_modules/.bin/acorn'
npm ERR!  { Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/mnt/x/webapps/current/client/node_modules/.bin/acorn'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, symlink '../acorn/bin/acorn' -> '/mnt/x/webapps/current/client/node_modules/.bin/acorn'
npm ERR!      errno: -1,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../acorn/bin/acorn',
npm ERR!      dest: '/mnt/x/webapps/current/client/node_modules/.bin/acorn' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, symlink \'../acorn/bin/acorn\' -> \'/mnt/x/webapps/current/client/node_modules/.bin/acorn\'',
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../acorn/bin/acorn',
npm ERR!   dest: '/mnt/x/webapps/current/client/node_modules/.bin/acorn',
npm ERR!   parent: 'ClientPortal' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ishraqiyun77/.npm/_logs/2018-01-02T23_13_55_760Z-debug.log
```

On the `C:\`, now it is:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, rename '/mnt/c/dev/current/client/node_modules/.staging/fsevents-7cb9deb9/node_modules/asynckit' -> '/mnt/c/dev/current/client/node_modules/.staging/asynckit-8e696cb5'

npm ERR! path /mnt/c/dev/current/client/node_modules/acorn
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/c/dev/current/client/node_modules/acorn' -> '/mnt/c/dev/current/client/node_modules/.acorn.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ishraqiyun77/.npm/_logs/2018-01-02T23_27_29_574Z-debug.log
```

Not sure what broke between Windows `10.0.16299` and `10.0.15063`. Never had issues with the latter although of course couldn't mount a network share.

**Comment by bpulliam** [comment]
Much has changed in the WSL world since this was filed.  If you still see this issue, please file a new one. Thanks!
