### ISSUE TITLE
Accesssing the Linux file-system from Windows

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/WSL#2804]
I'm using PHP Storm on Windows.

I have a PHP environment running on the Linux subsystem, with SSH configured, so that Storm can launch PHP to run my test-suites, etc.

This has all been working quite nicely for some months now, but I recently had to write a test that involves setting/checking the permission mask on folders/files from PHP, which brought me to the realization that files on my Windows `C:\` drive, which I access via `/mnt/c` on Linux, does not really support setting the permission mask - so I can't run that part of my test-suite.

This lead me to try another option - I moved my project from `/mnt/c/workspace/my_project` to `~/workspace/my_project`, so now it's on the emulated Linux file-system, and I'm able to run the test-suite without problems.

The problem now is how to connect Storm to the Linux file-system, and the first thing I attempted was to access it from the `Lxss` folder on Windows, which turned out to be a [very bad idea](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/)! Lesson learned 🙄

I then attempted to connect Storm via SFTP to the Linux file-system - this does absolutely *not* work: flashing icons in the folder view and toolbar, constant re-indexing, CPU running at 100%.

That's obviously not what I want in the first place - it means Storm has to clone the entire project folder locally first, which is horribly slow, and changes (such as updating vendor depedencies, etc.) won't get picked up via SFTP, since it has no way to monitor the file-system.

It seems I have to choose between the Linux file-system with no real support for Windows apps - or the Windows file-system with no real support for Linux file-system permissions.

So I'm not sure where to go from here.

Can you suggest any approach that would work at this time?

Or do you have anything planned that will provide two-way file-system integration?

Is it perhaps possible to mount the Linux drive in Windows (with proper support for file-system change notification, permission bits and write-operations) somehow?

Can I have my cake and eat it too? 😸

**Comment by therealkenc** [comment]
#1524. User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341279-a-file-created-in-c-users-user-appdata-local-lx).
