### ISSUE TITLE
'who' command on my WSL Ubuntu 16.04 LTS is not showing anything  

### ISSUE THREAD

**Issue by evanchime** [Microsoft/WSL#2806]
> myusername@DESKTOP-*******:/mnt/c/advanced_programming_in_the_unix_enviroment$ who
myusername@DESKTOP-*******:/mnt/c/advanced_programming_in_the_unix_enviroment$

The above is what I get when I type 'who'. Please, can anyone explain? I asked the question on 'ask Ubuntu', and I was told this was a known issue, and that I should file a bug report here. Cheers

**Comment by therealkenc** [comment]
#573 #913.
