### ISSUE TITLE
Artist here looking for some information on compatibility with Linux based neural network projects

### ISSUE THREAD

**Issue by thedonquixotic** [Microsoft/WSL#2809]
This is a very broad question I realize but I'm hoping someone here can answer it. I'm an artist/designer interested in the technical innovation of art, and I've been experimenting for the last year with neural networks. [My first article was published here](https://artplusmarketing.com/how-artists-can-use-neural-networks-to-make-art-714cdab53953?gi=77f50d314dc6). 

I use Windows for most of my everyday work. Previously I had installed an Ubuntu partition on my computer but since then I've had to reformat my drive etc. I'm fixing to write up a couple more articles on the topic and since I was already installing WSL and Hyperterm on my machine for one of my development classes, I thought maybe it would be a good idea to give WSL a try for running the neural network. 

Would this work? When I first learned about Cygwin last year and was using it for work, I had inquired about using one of these neural networks on the github page for the neural network Neural-Style https://github.com/jcjohnson/neural-style/issues/356 Apparently the WSL couldn't at the time run the neural network operations because it relied on some part of the Linux kernel that was not in WSL?

I'm an artist. I'm more technical than most artists but when stuff gets into kernels and other lower level aspects of computer science I'm pretty much loss. I could of course just try to install and run Neural-Style on my WSL, but I could very well mess it up, not because it doesn't work but because I'm a doofus who doesn't know what he's doing in the CLI. 

From my understanding the WSL doesn't contain any of the Linux kernel, but it offers a compatibility layer that enables basically the same things? I'm not real clear on what the limitations or definitions of those compatibilities are though. How would I be able to tell definitively if Neural-Style works on WSL or not? Or any other neural network that I might decide to download and use?

**Comment by therealkenc** [comment]
> How would I be able to tell definitively if Neural-Style works on WSL or not?

Short answer is no. User [voice here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support). Dupe #327 #829. 

[Academically, looking at the dependencies for neural-style and [torch7](https://github.com/torch/torch7), I wonder if it could be coerced into running very slowly. But pretend I didn't say that. You want the short answer.]

**Comment by thedonquixotic** [comment]
Excellent thank you very much!

**Comment by thedonquixotic** [comment]
Also yeah, I could probably get it to work without GPU, it can do CPU processing, it would just take forever. Well looks like I'm going to be installing Ubuntu again! Hopefully will be easier now that I've gotten my OS agnostic tools pipeline kind of up and going.
