### ISSUE TITLE
32-bit Support

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/WSL#281]
When will we be seeing an Ubuntu on Linux 32-bit release?

**Comment by russalex** [comment]
We have heard a couple of requests for this but not too much.  At this time the User Voice page has one of these with a little bit of support ([here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel)).

**Comment by bazhenov-dn** [comment]
Would be nice having 32-bit support in bash on Windows-64

**Comment by leovarmak** [comment]
I updated to AU only for the sake of Bash and it isnt available of 32Bit, too bad

**Comment by neatville** [comment]
Some modern 2 in 1 Windows tablets come with 32 bit windows, so I would also like to see this happen.

**Comment by markusschaber** [comment]
I think this are somehow 2 (related) issues:

- WSL Support on 32 bit Windows (obviously limited to 32 bit Linux processes)
- Support for 32 bit Linux processes on 64 bit Windows (possibly including multiarch support)

I see use cases for both.

**Comment by therealkenc** [comment]
Landing zone for i386 on WSL is now #2468.

**Comment by phillipmacon** [comment]
You got to set up your virtual machine for x86 to get 32 bit then you got to set up your virtual machine for x64 then 32 bit and then you run a 64 bit UEFI and you should know that the x86 is a desktop the x64 is a Workstation and then you have high as a file server

**Comment by phillipmacon** [comment]
Say you do it like this you have x86 and that's going to run a desktop all day for any Windows home or educational to receive media from x64 which is the workstation that allows you to connect cloud to terminal and develop apps for x86 and build developers tools for x64 then you have UEFI which is a mobile laptop server so that you can remote desktop when accessing Cloud tier of government storage of David

**Comment by phillipmacon** [comment]
Here's the thing WSL is done in fat and ex fat but if you formatted to NTFS it won't run it's nothing but a dominant system so what I did is the first one since it ran in fat and he acts fat I knew I needed a stable kernel and it's either NTFS or Xbox so for WSL I chose Xbox so the kernel of NTFS can stay windows cuz Xbox throw it in a container

**Comment by phillipmacon** [comment]
So WSL is a fat format with an Xbox kernel so xqemu you can throw in the bios Bill Gates had in school when I worked Youth Services educational curriculum constructive activity games and simulations on the work environment

**Comment by phillipmacon** [comment]
You probably wouldn't get a 32-bit Linux too load without ntdvm running a Dos subsystem for unix

**Comment by phillipmacon** [comment]
32 bit run newer as Xp mode on virtual pc Microsoft virtual server run those for 16 bit device

**Comment by phillipmacon** [comment]
Windows 10 32 bit Ntvdm run with virtual pc Microsoft server windows 2019 32 bit for Unix windows 7 windows subsystem for Unix but want windows 10 32 bit

**Comment by phillipmacon** [comment]
Unix is shell for instruction set

**Comment by phillipmacon** [comment]
All in windows 11  hyper v is replacement of virtual pc and Microsoft server provide Xbox 360

**Comment by phillipmacon** [comment]
Xp to xna to Vista to xna to win7 to xna to win 8 to fna to xna to win8.1 to xna-fna to win10 32 bit migration 64 bit build to run the past of last future on windows

**Comment by phillipmacon** [comment]
It would be 32 bit and that wasn't really just a color that it is cuz it supports it you can run 32-bit files you just have to do them with inside of the developer if you're not making a virtual machine around 32 bit and hyper virtualization it's not going to run it

**Comment by phillipmacon** [comment]
You developed in hyperversialization to run with inside windows subsystem for Linux 2 it's just when you look at the binary it's still elf 64 and we built the binary for upscaling

**Comment by phillipmacon** [comment]
What you're looking for is another Dos

**Comment by phillipmacon** [comment]
We migrated Dos2unix for sudo

**Comment by phillipmacon** [comment]
Dos subsystem for Linux got be Ntvdm is google

**Comment by phillipmacon** [comment]
Google the 16 bit is right now at the TV is running only about eight bit that's why I really doesn't want to run on Windows without saying it's on the upscale with the option the down size without losing scale is it monitor issue for display if you want to use 32 bit it's got to be Windows 10 32 bit and you got to upgrade that to Windows 11

**Comment by phillipmacon** [comment]
Yes you can install it on the 11th generation Intel Windows 10 32 bit and build another Linux when it upgrades to Windows 11 and then you'll see it runs Dos with Google IBM instead 64 bit Dosbox with Amazon on AMD

**Comment by phillipmacon** [comment]
I just learned you cannot see no better than 32 bed and you can't hear no better than 64 bit on down the one bit but you always have to see 32 bit

**Comment by phillipmacon** [comment]
32 bits going to run your monitor display on Raspberry Pi for Android the Android runs different than on AMD or Intel

**Comment by phillipmacon** [comment]
Pentium 32 bit Dos protect NTFS for wsu and ntdvm open dsl for doshell to Darwin for windows Google ios

**Comment by phillipmacon** [comment]
Migration android pc 32 bit playstore

**Comment by phillipmacon** [comment]
Leave Amazon 64 bit for app store

**Comment by phillipmacon** [comment]
32 bit Google iOS CLI

**Comment by phillipmacon** [comment]
WSL cross linux wsa

**Comment by phillipmacon** [comment]
You would have to have 32-bit windows wsl2 to get 32-bit

**Comment by phillipmacon** [comment]
Have you support 32 bit you'll get unix to get Android and you get your Dos migration

**Comment by phillipmacon** [comment]
Dos/Mac OS X Server

**Comment by phillipmacon** [comment]
For your parallels you will find it and device peripherals

**Comment by ylluminate** [comment]
@phillipmacon not sure if you're understanding what you're doing, but you are not using comments properly here. Please copy all of your comments into your single first comment and then delete the rest.

**Comment by phillipmacon** [comment]
https://quasar.dev/start/quick-start

**Comment by phillipmacon** [comment]
32 bit app support
