### ISSUE TITLE
Link putty, showing Access denied but my password is correct.

### ISSUE THREAD

**Issue by GitHublilei** [Microsoft/WSL#2810]

**Comment by sunilmut** [comment]
@GitHublilei - Please follow the issue [template](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) while opening a new issue. Otherwise there is not enough information to provide any support and we will have to close the issue out.

**Comment by therealkenc** [comment]
Nada. But based on issue title alone, you're looking at #2505.

**Comment by GitHublilei** [comment]
this issue is solve,but I can't type Chinese in xshell.Using vim to open a file can be entered but it can be scrambled.I set the format utf-8.But ubuntu can enter Chinese.
