### ISSUE TITLE
About WSL'ssh

### ISSUE THREAD

**Issue by AberSheeran** [Microsoft/WSL#2811]
I activated ssh...but when I try to connect, I find that port doesn't seem to be listening. 

> root@CHEN:/etc/ssh# /usr/sbin/sshd -d
debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: private host key #0: ssh-rsa SHA256:P88WELrm4g0/Pv3ptm0xGxcBlUnhGhE3lH40Fc+XAW4
debug1: private host key #1: ssh-dss SHA256:R/54n/q1M8qY97SGkbPlADkKBAJBj6/H9BtBqSLHBK8
debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:t/oQXMpY/56YCHI3OhVHxHxIoGANRNuiIK1G8rIGNjA
debug1: private host key #3: ssh-ed25519 SHA256:SV7HpPD44mHPcbI8IgDPDbtI1/CLwqJnGFDdm40fwCQ
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 23456 on 0.0.0.0.
Server listening on 0.0.0.0 port 23456.

> Connecting to 127.0.0.1:23456...
Could not connect to '127.0.0.1' (port 23456): Connection failed.

I need your help. T_ T

**Comment by DarthSpock** [comment]
You didn't manually start the sshd service. Do a `sudo service sshd start` then try again.

**Comment by AberSheeran** [comment]
I tired it before, but it didn't work. Thanks.

**Comment by DarthSpock** [comment]
I would recommend you fill out the template for posting new issues then.

**Comment by AberSheeran** [comment]
Sorry, I didn't see this template before. I will do it. Thanks.

**Comment by DarthSpock** [comment]
You can still use this issue and just edit your original comment using the template format. I don't know why you closed it.

**Comment by therealkenc** [comment]
>  I don't know why you closed it.

Because it's a dupe of many. `ssh`/`sshd` has worked in WSL since the summer of 2016. Any posts related to `ssh`/`sshd` are one of either (a) linux-behavior, (b) amorphous 3rd party firewall/vpn/antivirus issues which I think might be a little better since the TDI filter bypass changes made it into 17046.

**Comment by DarthSpock** [comment]
@therealkenc He only closed it because he didn't fill out the template. I was going to reference whatever issue he is experiencing after getting more details.

**Comment by AberSheeran** [comment]
Thanks to Both of You. Finally got it working.
So I closed this issue.
Solution in [#1554](https://github.com/Microsoft/WSL/issues/1554)
