### ISSUE TITLE
Bash For windows .bashrc not loading

### ISSUE THREAD

**Issue by Bilal092** [Microsoft/WSL#2812]
![question](https://user-images.githubusercontent.com/34689025/34604636-8c3ee26a-f243-11e7-8b27-57171db722b1.JPG)
I am having problem in loading Python in Linux tools for Windows, When I load Python from cmd after loading bash it open python 2.7 whereas I have already installed anaconda with python 3.6, if I load bash again from within bash it loads Anaconda version of python, I think above image clearly describe the issue, I have already modified home/username/.bashrc by adding path of my installation, please help  me with this issue

**Comment by Bilal092** [comment]
![question](https://user-images.githubusercontent.com/34689025/34604636-8c3ee26a-f243-11e7-8b27-57171db722b1.JPG)
I am having problem in loading Python in Linux tools for Windows, When I load Python from cmd after loading bash it open python 2.7 whereas I have already installed anaconda with python 3.6, if I load bash again from within bash it loads Anaconda version of python, I think above image clearly describe the issue, I have already modified home/username/.bashrc by adding path of my installation, please help  me with this issue

**Comment by therealkenc** [comment]
If you want to reload `.bashrc` you want `bash -l` (`bash --login`). That might or might not be how you want to do things, but not a WSL thing.
