### ISSUE TITLE
parallel execution of cmd.exe gets random EINVAL

### ISSUE THREAD

**Issue by rkwwgit** [Microsoft/WSL#2813]
Windows version is 10.0.16299.192

I'm using gnu make in the Ubuntu environment to launch Windows commands - this works fine without any parallel compilation but if I use e.g. 'make -j2' commands sometimes fail and make reports 'Invalid argument'.

The attached makefile illustrates the issue. You'll need to 'apt-get make'

--

More details:

This was originally seen launching cl.exe but a simple cmd.exe 'copy' fails too... time passes... in fact it turns out you don't even need the copy. A simple 'echo' suffices. Much-simplified makefile attached.

--

Reproduction steps:

$ cd /mnt/c/Users/me/test
$ # copy Makefile.txt Makefile
$ make create
$ make -j2
...
/mnt/c/Windows/System32/cmd.exe /c echo 779.cpp
541.cpp
/mnt/c/Windows/System32/cmd.exe /c echo 244.cpp
779.cpp
/mnt/c/Windows/System32/cmd.exe /c echo 269.cpp
/mnt/c/Windows/System32/cmd.exe: Invalid argument
Makefile:4: recipe for target '244.obj' failed
make: *** [244.obj] Error 1
make: *** Waiting for unfinished jobs....
269.cpp

--

Expected behaviour: make completes successfully

[Makefile.txt](https://github.com/Microsoft/WSL/files/1607281/Makefile.txt)

**Comment by therealkenc** [comment]
Likely #2448 and friends. On 16299 try the [workaround](https://github.com/Microsoft/WSL/issues/2448#issuecomment-342254181), or try Insiders 17035+ and see if that resolves.

**Comment by rkwwgit** [comment]
As per the original bug report, this is 16299.192 which as per workaround Update 2 should already contain a fix for #2448. 

I unmounted and remounted C: so I have the 'fallback=1' mount option enabled, but the 'make' problem still occurs.

**Comment by therealkenc** [comment]
Right; I the repro is about firing off `cmd.exe` so yeah different. Thanks.

**Comment by rkwwgit** [comment]
$ strace -o /home/me/strace.txt make -j30
fails almost immediately, but there's nothing useful in the trace (the error message is read from a pipe)

$ strace -f -o /home/me/strace.txt make -j30
runs to completion.

Note that this is a 32-processor virtual machine but we see the same error on real hardware.

**Comment by rkwwgit** [comment]
Replaced SHELL with a wrapper script to launch sub-commands using strace, and caught the EINVAL (= 026) error in the leaf process:

22167 execve("/mnt/c/Windows/System32/cmd.exe", ["/mnt/c/Windows/System32/cmd.exe", "/c", "echo", "999.cpp"], [/* 21 vars */]) = 0
...
22167 getcwd("/mnt/c/Users/roger/test", 4096) = 24
22167 open("/dev/lxssclient", O_RDWR)   = 3
22167 ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7fffec221db0) = 0
22167 open("/mnt/c/Windows/System32/cmd.exe", O_RDONLY) = 5
22167 ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffec221c60) = 0
22167 close(5)                          = 0
22167 open("/mnt/c/Users/roger/test", O_RDONLY) = 5
22167 ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffec221c60) = 0
22167 close(5)                          = 0
22167 ioctl(4, _IOC(0, 0x00, 0x97, 0x22), 0x7fffec221d10) = 0
22167 ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffec221d08) = 0
22167 ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffec221d08) = 0
22167 ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffec221d08) = 0
22167 write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\264}\5\0\0\0\0\0"..., 180) = 180
22167 read(4, "\26\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 16
...
22167 write(2, "/mnt/c/Windows/System32/cmd.exe:"..., 50) = 50
22167 close(3)                          = 0
22167 close(4)                          = 0
22167 exit_group(1)                     = ?
22167 +++ exited with 1 +++

In threads which don't fail, the pattern is:

22178 write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\303}\5\0\0\0\0\0"..., 180) = 180
22178 read(4, "\0\0\0\0\0\0\0\0\2\251\3\0\0\0\0\0", 16) = 16
22178 ioctl(4, _IOC(0, 0x00, 0x9b, 0x22), 0x7fffd34ba1d8) = 0
22178 write(4, "\0\0\0\0\0\0\0\0\2\251\3\0\0\0\0\0", 16) = 16
22178 ioctl(5, _IOC(0, 0x00, 0xbf, 0x22), 0x7fffd34ba1d0) = 0
22178 close(3)                          = 0
22178 close(4)                          = 0
22178 close(5)                          = 0
22178 exit_group(0)                     = ?
22178 +++ exited with 0 +++

**Comment by rkwwgit** [comment]
Here's an even simpler reproducer - a simple bash script:

--<snip>--
#! /bin/bash
while true; do
    for n in $(seq 1 10); do
	/mnt/c/Windows/System32/cmd.exe /c echo $n &
    done
    wait
done                                                                                               
--<snip>--

run this script and cmd.exe will fail about one time in a thousand (on average) with '/mnt/c/Windows/System32/cmd.exe: Invalid argument' 

Changing the command to:
    /bin/bash -c "/mnt/c/Windows/System32/cmd.exe /c echo $n" &

causes cmd.exe to fail about ten times more often.

**Comment by rkwwgit** [comment]
Change the command to:
    /init /mnt/c/Windows/System32/cmd.exe /c echo $n &

and the errors go away.

**Comment by benhillis** [comment]
I've been digging into this the past couple of days and have identified the issue, working on a fix now.

@rkwwgit - You're right, that should work as a workaround.

**Comment by benhillis** [comment]
A fix has been submitted and should be available in an Insider build soon.

**Comment by Brian-Perkins** [comment]
This should be fixed in Insider Build [17107](https://github.com/MicrosoftDocs/WSL/releases/tag/17107).

**Comment by rkwwgit** [comment]
That seems to have done the trick, thanks
