### ISSUE TITLE
Can't install Ubuntu: error 0x87E10BC6

### ISSUE THREAD

**Issue by AshleyScirra** [microsoft/WSL#2818]
* Your Windows build number:  16299.192

* What you're doing and what's happening:
I want to move from the legacy WSL to the new Windows Store version. So I ran lxrun /uninstall /full, rebooted, opened the Windows Store, found Ubuntu, and clicked install. When it says "Acquiring license", it then fails with error 0x87E10BC6. I've tried searching for this and I have no idea what it means. I already have the WSL feature enabled in "Turn Windows features on or off".

* What's wrong / what should be happening instead:
I expected the install to succeed. I'm having to go back to the legacy system now. lxrun /install looks like it's still working.

**Comment by sunilmut** [comment]
@AshleyScirra - Can you confirm that your Windows is Activated? You can check that by running `slmgr /xpr` from cmd.exe.

**Comment by AshleyScirra** [comment]
When I run that a popup message appears which says:

---------------------------
Windows Script Host
---------------------------
Windows(R), Professional edition:

    The machine is permanently activated.


---------------------------
OK   
---------------------------

**Comment by drooxifer** [comment]
same problem. somebody managed to solved this?

**Comment by benhillis** [comment]
Seems like a Microsoft Store issue, please let us know if you're still seeing this.
