### ISSUE TITLE
Launching VS code causes pulse audio error

### ISSUE THREAD

**Issue by mredbishop** [Microsoft/WSL#2819]
I have been using VS Code for Linux in WSL for a few weeks now, very successfully as per my previous issue #2760 

Suddenly this morning I started getting the following error:
```
ed@ed-surface-book:~$ code --verbose
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
```
Has something changed in terms of Windows Insiders builds of the WSL that might cause this?

Cheers,

Ed

**Comment by therealkenc** [comment]
#2760

**Comment by mredbishop** [comment]
@therealkenc This isn't a duplicate, #2760 was resolved just waiting for a release of WSL to reach production. This issue just started happening today.
