### ISSUE TITLE
Vim Cursor shape stays underscore. Not able to change it

### ISSUE THREAD

**Issue by ponegan** [Microsoft/WSL#2821]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening / What's wrong / what should be happening instead:
I'm using xterm-256color. 
I had been tried to change the shape of my vim cursor. I tried lots of different configuration for cursor shape (to be block) but none of them works as I put them in my .vimrc.

For example I tried some of these:
http://vim.wikia.com/wiki/Configuring_the_cursor

In the terminal I was able to change the shape of cursor to block by selecting 'large' in property as @zadjii-msft suggested in  #1253. But the same trick won't work for vim. Well.... it will work at the moment I set it to 'large'. But it will reset back to underscore every time I open another file.

As this:
![image](https://user-images.githubusercontent.com/35251149/34707886-e4900eb6-f4c4-11e7-89a1-8441d7c86300.png)

Anyone got a good approach on this cursor configuration?

**Comment by parkovski** [comment]
I don't think this is possible right now - the console needs to understand a cursor escape, like `^[n q` with n from 0-6, which it doesn't. The only way I know to change it right now is with console APIs that are not available within WSL. Hopefully this functionality will get implemented soon.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#68
