### ISSUE TITLE
Unable to enter Chinese after link xshell.

### ISSUE THREAD

**Issue by GitHublilei** [microsoft/WSL#2824]
Open xshell, I can enter Chinese, but cannot enter Chinese after SSH, and the Chinese file name will be displayed as??

Opening the utf-8 file with vim will also show the code, but my xshell code is set to utf-8.

When you open the file with vim, you can type in Chinese but it will appear scrambled.

**Comment by mingl0280** [comment]
自己装一下语言支持……

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
