### ISSUE TITLE
Infrequent blue screens after upgrading to 1709

### ISSUE THREAD

**Issue by straight-shoota** [Microsoft/WSL#2831]
I have been using WSL for quite some time without any issues. It's a great tool!
Three days ago I finally updated to 1709 (was 1603 (?) until then).

Pre-story: Immediately after the update bash started to seemingly randomly crash. It was really infrequent, somtimes I didn't catch the error code because the window was closed too fast, but I saw `Error 0x80070040` a few times. This partly happend while I was not actively working in bash (it was still open but I didn't do anything). I found some dated issues on that error suggesting something at fault with `/etc/resolv.conf`. I deleted that file but that didn't seem to help.

But now I haven't seen any of that since yesterday. Instead I've got a few blue screens. They seem to be less frequent at least. The last one happend while compiling [the Crystal compiler](https://github.com/crystal-lang/crystal).
Minidump sent to secure@microsoft.com

Windows build number:  10.0.16299.192

**Comment by benhillis** [comment]
I received your dumps, this is the same issue as #2648.  A fix should be coming soon, thanks for reporting!

**Comment by straight-shoota** [comment]
@benhillis I'm not sure if it matters or is completely unrelated: I haven't seen a blue screen since creating this issue, but now I got `Error: 0x80070040` again.

**Comment by rdp** [comment]
I also get "infrequent but reproducible" KERNEL_SECURITY_CHECK_FAILURE when compiling with crystal on one box but not another.  Both on 1709.  I'll await an update to that other ticket, thanks for looking at this.
