### ISSUE TITLE
Unable to enable Windows Susbsystem Linux in the Enable Features dialog or through PS command

### ISSUE THREAD

**Issue by dariuspranskus** [microsoft/WSL#2832]
Hi

I am trying to install Microsoft Windows Subsystem Linux on Windows 10 Home (ver 10.0.16299.15)

For That I am trying to enable optional feature through "Programs and Features" dialog or running PS command 
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
`
I am getting the following error message
```
Enable-WindowsOptionalFeature : One or several parent features are disabled so current feature can not be enabled.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

```
Also when I look at the feature list after the restart  in the Programs and Features, it is still disabled.

What might be a problem?

Thanks
Darius

**Comment by githubfoam** [comment]
Verify if your windows 10 home is 64-bit.  Screen tells the problem.It does not give directions though, like how you can enable this feature.Moreover I guess there is dependency issue among features which is missing, like what feature depends on what feaure.

"Enable-WindowsOptionalFeature : One or several parent features are disabled so current feature can not be enabled."

I guess you should find a way to enable this feature "Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand"

if you sort it out share svp.

**Comment by sunilmut** [comment]
@dariuspranskus - What do you see if you try to enable the WSL feature through the `turn on/off features` UI.

**Comment by therealkenc** [comment]
I'm no expert on the subject (rather opposite), but I think he might need `-All`.
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -All
```
Without `-All` you don't get the dependencies. That is absurd default behaviour of course (imagine `apt` requiring `--with-dependencies`). And the "`One or several parent features`" is plain lazy. But I digress.

**Comment by samcarlinone** [comment]
This is also happening to me (I tried with -All and without). Using the Features UI prompts for restart, and upon restarting the box is unchecked.

**Comment by Morthy** [comment]
I'm having the same problem on Windows 10 Pro, version 1709

**Comment by jmichaux** [comment]
@samcarlinone I was having the same issue. I _think_ part of the problem was some missing update somewhere.  Since I was having a hard time forcing Windows to update, I downloaded the [Windows Media Creation Tool](https://www.microsoft.com/en-us/software-download/windows10) and re-installed Windows.  I should note that I didn't delete any of my personal files, apps, etc.

**Comment by benhillis** [comment]
Could people encountering this issue ensure that the trustedinstaller service is set to autostart?

`SC config trustedinstaller start= auto `

**Comment by Morthy** [comment]
For me this was also caused by a different problem where a fresh Windows install wouldn't install the latest cumulative updates, getting in an infinite loop of requiring a restart for updates that wouldn't go through. The fix was reinstalling Windows.

**Comment by arnaudoisel** [comment]
Running PowerSheel "as Administrator" solved the problem for me

**Comment by therealkenc** [comment]
> getting in an infinite loop of requiring a restart for updates that wouldn't go through

I hit that too in early January and a total wipe ended up being the only path to salvation, despite my considerable best efforts to solve it otherwise.

> Running PowerShell "as Administrator" solved the problem for me

@dariuspranskus  can you confirm you were running an elevated Powershell? That was kind of taken as a given in this thread. I think you probably were, because I'd expect a different mode of failure if you weren't. But "solved **the** problem for me" (emphasis on definite article mine) loose end above needs tidying up. Running elevated will definitely solve **a** problem, but not necessarily **your** problem.

**Comment by Groumy** [comment]
Hi

I had the same issue (the `One or several parent features are disabled so current feature can not be enabled.` one).

In my case it was that the Trusted Installer service wasn't up. I started it and set it to run automatically and than wait a cople of minutes and try again to activate the feature and then it works.

Hope it helps other people.

**Comment by rav345** [comment]
Same problem

PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : One or several parent features are disabled so current feature can not be enabled.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

I turned the TrustedInstaller to Auto and restarted and everything. Just don't understand what does it want me to do!
If I try to turn on WSL via GUI it say finished doing requested changes and restarts. But when I check it again after restart, the box is unchecked!
Please help

**Comment by hhalim** [comment]
Same problem, same error COMException.

OS: Windows 10 x64
Build: 16299

**Comment by stensson** [comment]
Same issue here, brand new machine. 
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
```

**Comment by SimLoads** [comment]
Same issue again, I'm led to believe it's a problem with version 1709. Restarts do nothing, no system changes are saved, no updates going through. Any solutions? I've tried everything _but_ the media creation tool, trying to avoid a fresh install.

**Comment by Jhony33** [comment]
Same issue here

**Comment by dmonco** [comment]
![2](https://user-images.githubusercontent.com/2096773/38538736-cb22d474-3c9d-11e8-9355-3e4d80f6fb33.png)
The same issue with Windows 10 Home (1709) - 64

**Comment by stensson** [comment]
After applying the April update for Windows 10: https://support.microsoft.com/en-us/help/4093112 this issue was resolved for me.

**Comment by tanjakantola** [comment]
The same issue. I tried installing the update recommended by stensson, but ended up in the "infinite loop of requiring a restart for updates" as described by Morthy

**Comment by stensson** [comment]
@tanjakantola Have you also tried starting Windows in recovery mode and choosing to repair the installation? I believe that fixed my infitite loop issue, together with 4093112. Can't remember all details on which sequence i did this though.

**Comment by CapsuleID** [comment]
![screenshot 45](https://user-images.githubusercontent.com/27888891/39054694-e548ec72-44e4-11e8-9afc-d193ef875547.png)

![screenshot 44](https://user-images.githubusercontent.com/27888891/39054706-ec8ef530-44e4-11e8-8553-d74a4aab9111.png)

**Comment by Miminoux** [comment]
@Groumy , the trusted installer service set to up fixed the thing.
When typing "Enable-WindowsOptionalFeature -Online -FeatureName TelnetClient" (or whatever feature) I was having "Enable-WindowsOptionalFeature: Impossible de lire la clé du Registre de configuration" (Enable-WindowsOptionalFeature : Impossible to read Configuration regitry key).
Turning on and automatic start the "Programme d'instalaltion pour les module Windows" service which I think correspond in english to the Trusted installer has solved the problem.

@Groumy : you saved me...

**Comment by McMcGurk** [comment]
@therealkenc Sorry for coming in so late to this, is "Running an elevated Powershell" different than running PS on an administrator account? Thanks!

**Comment by jlab55** [comment]
I had the same problem as everyone else. My solution was disabling firewall / antivirus software before installing WSL from the PowerShell. The logs of the security software showed it was preventing a registry update from being completed at around the same time as running the install.

**Comment by tbc** [comment]
Giving @arnaudoisel kudos for February answer. My problem, too, was solved simply by running PowerShell as Administrator.

**Comment by wvdschel** [comment]
I am still running into this problem. I'm running PS as Administrator, and according to the graphical Windows feature installer, WSL is active. However, upon trying to start Ubuntu, I'm running into the familiar error message. I'm also positive I'm running a 64-bit Windows.

![capture](https://user-images.githubusercontent.com/76032/44954610-c6530800-aea4-11e8-9625-a1034d391ce7.PNG)

I'm assuming this is a different problem, but with similar symptoms. Can anyone help?

**Comment by ChandanKSahu** [comment]
I also have the exact problem as @wvdschel commented. In addition, if I try to enable the windows feature 'Windows Subsystem for Linux' it shows the error code 0x70083701. I tried to resolve it using the Microsoft support threads. But they are of no help.

**Comment by VoQZHD** [comment]
Same problem.

**Comment by RomainSanchez** [comment]
+1

**Comment by raghavddps2** [comment]
Running power shell as admin solved the problem for me as well. Thank you!
