### ISSUE TITLE
select() on /proc/cpuinfo fd incorrectly fails with EPERM

### ISSUE THREAD

**Issue by franzinc** [Microsoft/WSL#2838]
The following program fails on WSL but not on a real Linux system:

Save as select-bug.c, then 'make select-bug', then './select-bug'.
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/fcntl.h>
#include <sys/select.h>


int main() {
  int fd=open("/proc/cpuinfo", O_RDONLY);
  
  if (fd < 0) {
    perror("open /proc/cpuinfo");
    exit(1);
  }
  
  fd_set readset;

  FD_ZERO(&readset);
  FD_SET(fd, &readset);

  int res=select(fd+1, &readset, NULL, NULL, NULL);

  if (res < 0) {
    perror("select");
    exit(1);
  }

  printf("%d ready fds\n", res);

  close(fd);

}
```

**Comment by jstarks** [comment]
Fair bug, but just curious where you ran into this!

**Comment by franzinc** [comment]
Hi jstarks.  We ran into this while trying to use Allegro Common Lisp in WSL.  Allegro Common Lisp uses select() before all stream reads to avoid blocking.

**Comment by Brian-Perkins** [comment]
This should be resolved as of Insiders Build [17101](https://github.com/MicrosoftDocs/WSL/releases/tag/17101).
