### ISSUE TITLE
on centos - systemctl start firewalld.service - error Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by rivetweb** [Microsoft/WSL#2839]
* What you're doing and what's happening:  `systemctl `
or
`systemctl start firewalld.service`

* What's wrong / what should be happening instead:

`Failed to get D-Bus connection: Operation not permitted`

**Comment by therealkenc** [comment]
#994 #1579 ([message](https://github.com/Microsoft/WSL/issues/1579#issuecomment-271555310)) #2209  etc

**Comment by wallysonn** [comment]
> * What you're doing and what's happening:  `systemctl `
>   or
>   `systemctl start firewalld.service`
> * What's wrong / what should be happening instead:
> 
> `Failed to get D-Bus connection: Operation not permitted`

mv /usr/bin/systemctl /usr/bin/systemctl.old
curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py > /usr/bin/systemctl
chmod +x /usr/bin/systemctl
