### ISSUE TITLE
Cmd.exe colors are not propagated to WSL

### ISSUE THREAD

**Issue by dulakm** [Microsoft/WSL#2843]
Hello, 

I'm not sure if this is a bug or a feature request. I hope this is the right place to ask about it.

* Your Windows build number:  
10.0.16299.125

* What you're doing and what's happening:
When I run command `gradle tasks` or even `cmd.exe /c gradle.bat tasks` in CMD I get colorful output:
![image](https://user-images.githubusercontent.com/4852580/34915742-9c8664f6-f92b-11e7-9dbe-ff7b74828805.png)
When I do the same from WSL (`cmd.exe /c gradle.bat tasks`), the output looses the color:
![image](https://user-images.githubusercontent.com/4852580/34915754-b5a60eb4-f92b-11e7-9b1c-eaac8479c048.png)

Please, can you help me with the issue?

Thank you,
Martin

**Comment by zadjii-msft** [comment]
This is unfortunately a known issue with interop as it exists currently. Only the text emitted by Windows executables will be displayed via interop, any API calls they make (such as setting the colors of text) unfortunately won't work.

The good news: @benhillis and I are sitting down today to discuss just this issue :)

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#67
