### ISSUE TITLE
fstat st_blocks is wrong, results in failure of many IO functions

### ISSUE THREAD

**Issue by quiret** [Microsoft/WSL#2844]
* **Your Windows build number:**  Build 16299.129

* **What you're doing and what's happening:**
I am working on a 512 bytes sectored filesystem (Windows and Linux).
Download bytes testfiles here: [bytes_testfiles.zip](https://github.com/Microsoft/WSL/files/1629806/bytes_testfiles.zip)
Copy into Win32 "C:/testdir" (adjust if necessary)
```
stat /mnt/c/testdir/504_bytes_testfile
stat /mnt/c/testdir/505_bytes_testfile
```
The 504_bytes_testfile returns a block size of 0, but the 505_bytes_testfile returns a block size of 1.
![bad_block_sizes_wsl](https://user-images.githubusercontent.com/7682485/34920648-2603e736-f976-11e7-9c83-70d5fc6adf6d.png)

* **What's wrong / what should be happening instead:**
On Real Linux(tm), the blocks size for both files is always 1.
![good_block_sizes_real_linux](https://user-images.githubusercontent.com/7682485/34920622-c00089f8-f975-11e7-9118-1e2b50c3ff78.png)

* **How to reproduce on Real Linux(tm):**
1. **Creating the 512 bytes sectored partition**
Plug in a HDD that has free space. Then open gparted to initialize that empty drive unformatted.
Assuming that the new partition device is located at /dev/sdb1 ...
```
mkfs -t ntfs -s 512 -c 512 /dev/sdb1
mkdir /mnt/test
mount /dev/sdb1 /mnt/test
cd /mnt/test
```
2. Place the 504 and 505 bytes testfiles into /mnt/test
3. execute the stat commands as described above on them
```
stat /mnt/test/504_bytes_testfile
stat /mnt/test/505_bytes_testfile
```

* **Strace of the failing command, if applicable:**  is this required? please post if yes.

Helpful links: https://linux.die.net/man/2/fstat
Funny related issue of wxWidgets: https://github.com/wxWidgets/wxWidgets/commit/a03ece4880d68743f0a40710f00b82da223c870f

This causes issues in many Linux IO libraries. pls fix, pls fast
Code::Blocks build scripts do not work otherwise.

**Comment by poizan42** [comment]
Small files can be embedded directly in the MFT so blkcnt_t  should be able to be zero even if the file is non-empty. A zero byte and one byte file takes up exactly the same amount of space on NTFS, but ntfs-3g report the former as zero blocks and the latter as one block. Arguably ntfs-3g is the one that is wrong here, but they might have done this to work around buggy software.

Really the IO libraries in question should fix this, the man page even points out not to rely on it:
> Use of the st_blocks and st_blksize fields may be less portable. (They were introduced in BSD. The interpretation differs between systems, and possibly on a single system when NFS mounts are involved.)

**Comment by quiret** [comment]
@poizan42 Thank you for your professional insight, poizan42! To be honest I was split between the issue being in WSL or in Linux libraries (I was once convinced of either). I will point library users to this thread to make them update their code I guess, if WSL is right (most likely).

**Comment by SvenGroot** [comment]
@poizan42 is correct. If a file is small enough, NTFS embeds it directly in the MFT in which case it literally takes up 0 blocks. If you show the properties for these files in Windows Explorer, you'll see that their "size on disk" is also reported as 0.

WSL uses the "size on disk" to calculate the block count; if Windows tells us the file takes up 0 bytes, we report 0 blocks. If we did not do this, tools like `du` would over-estimate the space used by set of files.

**Comment by benhillis** [comment]
@quiret - You mention this behavior "causes issues in many Linux IO libraries."  Could you elaborate?

**Comment by therealkenc** [comment]
Hope we get a well defined answer to which libraries/packages depend on the behaviour. But even if we don't, it seems the open question here is whether DrvFs is _striving_ for `ntfs-3g` equivalence, or whether you point at the man page (which is authoritative in the same way that Wikipedia is authoritative) and say, nah, DrvFs is Right™. `ntfs-3g` has been around for a long time and they didn't choose how it behaves for their health. They presumably did it that way because it makes `ntfs-3g` fit into the Linux ecosystem better.

**Comment by therealkenc** [comment]
This was marked by-design which is pretty much a flow chart terminus. If there exists in the wild an example of a specific scenario that breaks on WSL but works on on Real Linux with ntfs-3g or say a NFS/SMB mount that would be worth opening a new issue. "Breaks" (contrast: reports a different number up for interpretation) is a pretty high bar but it might exist.
