### ISSUE TITLE
Bugcheck in LxCore

### ISSUE THREAD

**Issue by heldchen** [Microsoft/WSL#2845]
**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number.

this might be the same issue as #2801 / #2798, but this time the minidump stacktrace referred to a different LxCore operation than the previous minidumps so just to be sure I sent the dump to secure@microsoft.com

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

17074

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

left the notebook running while being away for a few mins. notebook had restarted when returning to my desk.

* What's wrong / what should be happening instead:

shouldn't bugcheck :-)

**Comment by benhillis** [comment]
Thanks for reporting, I received your dumps and verified that the bug has been fixed and will be available in an Insider build soon.
