### ISSUE TITLE
Build 16184

### ISSUE THREAD

**Issue by strarsis** [Microsoft/WSL#2847]
In system information `Build 15063.786` is shown as the build of my Windows 10 Home system.
How can I upgrade to/install at least build `Build 16184`? Since this build `/etc/hosts` is synced.

**Comment by poizan42** [comment]
https://www.microsoft.com/en-us/software-download/windows10 ?

**Comment by strarsis** [comment]
@poizan42: Can the automatic Windows Update download and install this update on an existing Windows 10 system?

**Comment by poizan42** [comment]
I think it normally should offer you the update, but if it doesn't work you can just download the update tool.

**Comment by benhillis** [comment]
Updates are pushed gradually, if you want the newest update I suggest installing manually.

**Comment by strarsis** [comment]
@benhillis, @poizan42:
The update requires 'Services for Unix 3.5' to be uninstalled.
I cannot even find it listed in 'Turn Windows features on and off'.
I also uninstalled the 'Windows-Subsystem for Linux (Beta)'.
Setup is unsuccessful uninstalling it by itself, so I cannot proceed updating. 
This blocks any further updates for me (Windows Home x64).

**Comment by benhillis** [comment]
Can you post a screenshot of the exact error you are seeing?  That is very string.

**Comment by strarsis** [comment]
@benhillis: The language is not in English unfortunately, but here is a screenshot:
![error](https://user-images.githubusercontent.com/9271436/34963107-0516fa46-fa47-11e7-9350-31b73d6a5322.png)

**Comment by benhillis** [comment]
@strarsis - Thanks, so you were able to update?

**Comment by strarsis** [comment]
@benhillis: Yes, after moving the files "out of sight", the update was able to continue.

**Comment by benhillis** [comment]
Glad to hear it!
