### ISSUE TITLE
INITCTL upstart linux beginner needs help

### ISSUE THREAD

**Issue by drc85** [Microsoft/WSL#2848]
hi
i wanted to use hyperion service on windows linux subsystem.
i run windows insider preview 17063. im pretty new to linux .

if i run ubuntu as administrator and type
curl -k -L --output install_hyperion.sh --get https://raw.githubusercontent.com/hyperion-project/hyperion/master/bin/install_hyperion.sh
it downloads a 20519 big file.

when typing
chmod +x install_hyperion.sh
nothing happes it jumps back to normal input in bash

when typing
sudo sh ./install_hyperion.sh

it takes a while and i get this
---> Installing initctl script
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
---> Starting Hyperion
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

when trying to start it:
sudo service hyperion start
i get a ok but im not sure if it is running or whats going on ?

how can i check if the service is running? and how do i get rid of the innitctl upstart error?
i found an interessting aricle online wich says linux sub can show the services in the taskmanager and run in background.
https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl/
but i cant find the hyperion service after starting it?

thx
greetings

**Comment by therealkenc** [comment]
WSL doesn't have `upstart`/`systemd`, so no [`initctl`](http://man7.org/linux/man-pages/man8/systemd-initctl.8.html). That is #2209, #1579, #994 and the rest. 

I don't run (haven't installed) `hyperion`, but `sudo service hyperion start` like you mentioned is probably as good plan as any. Or run `/etc/init.d/hyperion`. Or start it manually, which looks like it might be (from an unreliable Google search):
```
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json
```

You can see if it is running with `ps ax`. If you don't see it running, or if it is running but "doesn't work", that will require an `strace` per the issue template you deleted. But you'll be treading a little out of beginner territory if you end up down the "debug why hyperion isn't working" road. Bonne chance.
