### ISSUE TITLE
The mv strikes back (windows symlinks)

### ISSUE THREAD

**Issue by 0x5c** [Microsoft/WSL#2849]
* Windows build number:  `10.0.16299.125`

* Repro:  
  * Store-installed Ubuntu.
  * Windows symlink: `C:\utemp` to `C:\Users\[user]\Desktop\temp\`
  * Commands:
```
root@GLaDOS:~# ls /mnt/c/utemp
[files in 'C:\Users\[user]\Desktop\temp\']

root@GLaDOS:~# touch testfile
root@GLaDOS:~# mv testfile /mnt/c/utemp/

[WSL hangs]
```

* Expected behaviour:
`mv` copies `testfile` to `/mnt/c/utemp` (`C:\utemp` to `C:\Users\[user]\Desktop\temp\`)

* Strace:
No trace, but I was able to extract the stack: https://gist.github.com/0x5c/84144b4a8e8dad0860726b526a0aec4f

**Comment by SvenGroot** [comment]
Thanks for reporting this!

As a workaround, as long as the source and target are on the same drive, if you make the link relative (don't include the drive letter in the target) this problem doesn't occur.

**Comment by 0x5c** [comment]
@SvenGroot
You mean `\path\on\c\` instead of `C:\path\on\c\` in the windows symlink? (`C:\> mklink /D`) 

Also, `mv` works normally in any other use case that I could try.

**Comment by SvenGroot** [comment]
Just `path\on\c`, without the leading slash. The path should be relative from the symlink's location.

This particular deadlock is unique to resolving the target of an absolute NT symlink.

**Comment by 0x5c** [comment]
@SvenGroot
That's a reasonable work-around. Thanks!

**Comment by SvenGroot** [comment]
We've fixed this issue and will update when it reaches an insider build.

**Comment by therealkenc** [comment]
Call it 17093 or 17101 for the sake of argument.
