### ISSUE TITLE
Virtual memory size is wrong in /proc/<pid>/stat

### ISSUE THREAD

**Issue by czfhhh** [microsoft/WSL#2853]
* Your Windows build number:  10.0.16299.192

* What you're doing and what's happening: 

$ cat /proc/1/status
...
VmSize: 10432 kB
...
$ cat /proc/1/stat
1 (init) S 0 1 1 0 0 0 0 0 0 0 0 9 0 0 20 0 1 0 0 _**362160046080**_ 24 18446744073709551615 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

* What should be happening instead:

$ cat /proc/1/stat
1 (init) S 0 1 1 0 0 0 0 0 0 0 0 9 0 0 20 0 1 0 0 _**10682368**_ 24 18446744073709551615 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

----------------------------------------------------------

Because I am new in linux, I do not know if there are more errors in this file.

**Comment by poizan42** [comment]
It matches the actual allocation from the point of view of the Windows kernel:
![image](https://user-images.githubusercontent.com/308129/35129665-db2bbe6a-fcbc-11e7-85ea-c7d02075c8f5.png)
![image](https://user-images.githubusercontent.com/308129/35129704-0df80a2e-fcbd-11e7-8a80-b7ff3373e4a3.png)

Now why that allocation is counted in stat but not status and maps is a good question, as well as what the point of reserving over 300 GB.

**Comment by therealkenc** [comment]
> as well as what the point of reserving over 300 GB.

Only 300? Pffft.
```
ken@DESKTOP-4UTIQSF:~/tmp$ cat /proc/1/stat
1 (init) S 0 1 1 0 0 0 0 0 0 0 0 32 0 0 20 0 1 0 1 903141289984 34 18446744073709551615 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```
