### ISSUE TITLE
Does WSL support openGL?

### ISSUE THREAD

**Issue by littlepi** [Microsoft/WSL#2855]
I am running a linux software on WSL. The program crashes every time I try to make some drawings with the openGL option. I know that the WSL is not a full linux and is intended to do command line tasks. In my case, I have installed the openGL libararies and everything seems OK. I am wondering if my problem is because of the WSL is incompatible with openGL.

**Comment by therealkenc** [comment]
WSL runs OpenGL alright, but it is not a supported scenario. You didn't follow the issue template, but in general from a clean Ubuntu install from the store do:
```
$ sudo apt install ubuntu-desktop mesa-utils
$ export DISPLAY=localhost:0
$ glxgears
```
On the Windows side, install [VcXsrv](https://sourceforge.net/projects/vcxsrv/), choose multiple windows, display 0, start no client, disable native opengl (sic). The hang out for this stuff is generally #637, but if you have a specific scenario I'll hold this open for a bit. It might be your scenario works. It might not.

**Comment by setten** [comment]
solved my problem running quantumatk in wsl it was the disable native opengl part

**Comment by NoxFly** [comment]
> 
> 
> WSL runs OpenGL alright, but it is not a supported scenario. You didn't follow the issue template, but in general from a clean Ubuntu install from the store do:
> 
> ```
> $ sudo apt install ubuntu-desktop mesa-utils
> $ export DISPLAY=localhost:0
> $ glxgears
> ```
> 
> On the Windows side, install [VcXsrv](https://sourceforge.net/projects/vcxsrv/), choose multiple windows, display 0, start no client, disable native opengl (sic). The hang out for this stuff is generally #637, but if you have a specific scenario I'll hold this open for a bit. It might be your scenario works. It might not.

Is there the same for `debian-desktop` ?
I've the same probleme but with debian application

**Comment by francescoboc** [comment]
> WSL runs OpenGL alright, but it is not a supported scenario. You didn't follow the issue template, but in general from a clean Ubuntu install from the store do:
> 
> ```
> $ sudo apt install ubuntu-desktop mesa-utils
> $ export DISPLAY=localhost:0
> $ glxgears
> ```
> 
> On the Windows side, install [VcXsrv](https://sourceforge.net/projects/vcxsrv/), choose multiple windows, display 0, start no client, disable native opengl (sic). The hang out for this stuff is generally #637, but if you have a specific scenario I'll hold this open for a bit. It might be your scenario works. It might not.

For me, to make things work properly, I also had to set `export LIBGL_ALWAYS_INDIRECT=0` (which I find a bit strange... so who's doing the rendering now, if also the `wgl` flag in VcXsrv is off?), otherwise glxgears would be slow and jerky. I found this solution from [this superuser question](https://superuser.com/questions/1487555/how-to-troubleshoot-opengl-on-ubuntu-under-windows-10-wsl).

**Comment by therealkenc** [comment]
> I also had to set export LIBGL_ALWAYS_INDIRECT=0

That's correct. [For one sensible definition of correct.]

> so who's doing the rendering now, if also the wgl flag in VcXsrv is off?)

[LLVMpipe](https://www.mesa3d.org/llvmpipe.html)

![image](https://user-images.githubusercontent.com/7049700/79377418-7d808380-7f10-11ea-9a43-d9b6aaf6013a.png)

**Comment by lohhans** [comment]
> WSL runs OpenGL alright, but it is not a supported scenario. You didn't follow the issue template, but in general from a clean Ubuntu install from the store do:
> 
> ```
> $ sudo apt install ubuntu-desktop mesa-utils
> $ export DISPLAY=localhost:0
> $ glxgears
> ```
> 
> On the Windows side, install [VcXsrv](https://sourceforge.net/projects/vcxsrv/), choose multiple windows, display 0, start no client, disable native opengl (sic). The hang out for this stuff is generally #637, but if you have a specific scenario I'll hold this open for a bit. It might be your scenario works. It might not.

WORKS! Thanks.

In addition, in WSL Ubuntu I had to add the following arguments to my .bashrc (before performing the steps above):

```bash
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1
```
[LINK OF SOLUTION 1](https://stackoverflow.com/a/68341165)
[LINK OF SOLUTION 2](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999)

**Comment by mdabdk** [comment]
Here is what worked for me in case anyone needs it. I am currently running Ubuntu 20.04.4 LTS on WSL2.

Step 1: Run
```console
$ sudo apt install ubuntu-desktop mesa-utils
```
Step 2: Follow the instructions in this [comment](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999) regarding installing VcXsrv, **BUT** replace
```console
$ export DISPLAY=192.168.1.3:0.0
```
with
```console
$ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
```
which was obtained from this [comment](https://github.com/microsoft/WSL/issues/6430#issuecomment-785667707).

Step 3: Follow the instructions [here](https://github.com/microsoft/WSL/issues/6430#issuecomment-760989910) regarding setting up your firewall for VcXsrv.

Step 4: Run
```console
$ glxgears
```
to test OpenGL.

**Comment by NoxFly** [comment]
> Here is how I got this to work to use OpenGL to open GUI's (e.g. Open3D and matplotlib) in VS code. I am currently running Ubuntu 20.04.4 LTS on WSL2.
> 
> Step 1: Run
> 
> ```
> $ sudo apt install ubuntu-desktop mesa-utils
> ```
> 
> Step 2: Follow the instructions in this [comment](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999) regarding installing VcXsrv, **BUT** replace
> 
> ```
> $ export DISPLAY=192.168.1.3:0.0
> ```
> 
> with
> 
> ```
> $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> ```
> 
> which was obtained from this [comment](https://github.com/microsoft/WSL/issues/6430#issuecomment-785667707).
> 
> Step 3: Follow the instructions [here](https://github.com/microsoft/WSL/issues/6430#issuecomment-760989910) regarding setting up your firewall for VcXsrv.
> 
> Step 4: Run
> 
> ```
> $ glxgears
> ```
> 
> to test OpenGL.
> 
> To get this working with VS code, in a terminal window in VS code, run
> 
> ```
> $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> $ export LIBGL_ALWAYS_INDIRECT=1
> ```
> 
> and then start running your code.

And after running `glxinfo | grep "OpenGL version"`
You'll see that you're running OpenGL 1.4.2 or something like that, instead of 4.6.0.
Your terminal will also show you this version, but to indicate you that your hardware __can__ run 4.6.0, but because it's an __indirect display port__, you cannot use a higher version than 1.4.2.
Hence you'll be blocked when you'll try new bigger things. It's a version gap. It's why I stopped WSL.

**Comment by mdabdk** [comment]
> > Here is how I got this to work to use OpenGL to open GUI's (e.g. Open3D and matplotlib) in VS code. I am currently running Ubuntu 20.04.4 LTS on WSL2.
> > Step 1: Run
> > ```
> > $ sudo apt install ubuntu-desktop mesa-utils
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step 2: Follow the instructions in this [comment](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999) regarding installing VcXsrv, **BUT** replace
> > ```
> > $ export DISPLAY=192.168.1.3:0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> > $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which was obtained from this [comment](https://github.com/microsoft/WSL/issues/6430#issuecomment-785667707).
> > Step 3: Follow the instructions [here](https://github.com/microsoft/WSL/issues/6430#issuecomment-760989910) regarding setting up your firewall for VcXsrv.
> > Step 4: Run
> > ```
> > $ glxgears
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to test OpenGL.
> > To get this working with VS code, in a terminal window in VS code, run
> > ```
> > $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> > $ export LIBGL_ALWAYS_INDIRECT=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then start running your code.
> 
> And after running `glxinfo | grep "OpenGL version"` You'll see that you're running OpenGL 1.4.2 or something like that, instead of 4.6.0. Your terminal will also show you this version, but to indicate you that your hardware **can** run 4.6.0, but because it's an **indirect display port**, you cannot use a higher version than 1.4.2. Hence you'll be blocked when you'll try new bigger things. It's a version gap. It's why I stopped WSL.

Interesting. So what do you use instead? Do you dual-boot?

**Comment by NoxFly** [comment]
> > > Here is how I got this to work to use OpenGL to open GUI's (e.g. Open3D and matplotlib) in VS code. I am currently running Ubuntu 20.04.4 LTS on WSL2.
> > > Step 1: Run
> > > ```
> > > $ sudo apt install ubuntu-desktop mesa-utils
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Step 2: Follow the instructions in this [comment](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999) regarding installing VcXsrv, **BUT** replace
> > > ```
> > > $ export DISPLAY=192.168.1.3:0.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with
> > > ```
> > > $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > which was obtained from this [comment](https://github.com/microsoft/WSL/issues/6430#issuecomment-785667707).
> > > Step 3: Follow the instructions [here](https://github.com/microsoft/WSL/issues/6430#issuecomment-760989910) regarding setting up your firewall for VcXsrv.
> > > Step 4: Run
> > > ```
> > > $ glxgears
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to test OpenGL.
> > > To get this working with VS code, in a terminal window in VS code, run
> > > ```
> > > $ export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
> > > $ export LIBGL_ALWAYS_INDIRECT=1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and then start running your code.
> > 
> > 
> > And after running `glxinfo | grep "OpenGL version"` You'll see that you're running OpenGL 1.4.2 or something like that, instead of 4.6.0. Your terminal will also show you this version, but to indicate you that your hardware **can** run 4.6.0, but because it's an **indirect display port**, you cannot use a higher version than 1.4.2. Hence you'll be blocked when you'll try new bigger things. It's a version gap. It's why I stopped WSL.
> 
> Interesting. So what do you use instead? Do you dual-boot?

Dual boot yes, but because it takes a consequent part of your disk, another option, with negative points too, can be USB booting with consistence. Because it's an external booter, you have to disable the UEFI security check, and it's not really a good idea. Also, for the same reason, a USB with 300-400Mo/s on R/W is usually good to keep correct performances.
