### ISSUE TITLE
GSOD when debugging python programs

### ISSUE THREAD

**Issue by mjoppich** [Microsoft/WSL#2857]
**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  Microsoft Windows [Version 10.0.17074.1000]

* What you're doing and what's happening:  Running jetbrains/spyder3 and trying to debug a python 3 script. Either I get a GSOD when just jetbrains is open, or while trying to debug a program in spyder

This might be related with issue #2801 .

* What's wrong / what should be happening instead:

no GSOD :)

I have/will send the minidump file to soon.

**Comment by sunilmut** [comment]
@mjoppich - Thanks for sending over the dumps. The bug was already known to us and the fix is making it's way out. Appreciate it!

**Comment by Brian-Perkins** [comment]
This should be addressed in the 17083 Insider Build.

**Comment by Brian-Perkins** [comment]
Fixed for RS3 with [KB4058258](https://support.microsoft.com/en-us/help/4058258/windows-10-update-kb4058258).
