### ISSUE TITLE
Error Running WSL Ubuntu SSH from a Windows Service

### ISSUE THREAD

**Issue by mattmon1** [Microsoft/WSL#2858]
Greetings Microsoft/WSL:

Just want the community to know that I'm enjoying using WSL Ubuntu on my Windows 10 machine. It's great having the capability to use Windows and Ubuntu together on the same platform.

I've build a .NET 4.7 console application that uses WSL Ubuntu to establish a SSH tunnel. The app creates a commandprocess that executes 'ubuntu run ssh <args...>' to establish a SSH tunnel and capture standard output. Everything works fine as a console application - WSL runs better than expected, the ssh tunnel performs well and I can capture SSH standard out and err.

When I wrap the app as a windows service, I'm getting the following application error in the event log. 
It seems that the windows service is attempting to invoke the canonical ubuntu.exe after I instantiate the commandprocess and execute the 'ubuntu run ssh <args...>' command. Unfortunately, the 'ubuntu run ssh <args...>' command never runs and the application error is logged instead. The windows service is installed using the same user account that was used to install ubuntu from the marketplace.

Just posting to the community to share my experiences and to see if you have any insights about how to get the windows service running. I look forward to hearing from you and to reviewing your suggestions.

Regards,
Matt

Application Error
Event ID: 1000
Description:
	Faulting application name: ubuntu.exe, version: 0.0.0.0, time stamp: 0x59ca645d
	Faulting module name: wslapi.dll, version: 10.0.16299.15, time stamp: 0xcc4bfe99
	Exception code: 0xc0000409
	Fault offset: 0x0000000000002045
	Faulting process id: 0x2210
	Faulting application start time: 0x01d38fd36aee7614
	Faulting application path: C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc\ubuntu.exe
	Faulting module path: C:\WINDOWS\SYSTEM32\wslapi.dll
	Report Id: 81107199-26d2-40c5-a0fe-66d6e4daef50
	Faulting package full name: CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc
	Faulting package-relative application ID: ubuntu

**Comment by therealkenc** [comment]
No idea, but try launching `C:\Windows\System32\wsl.exe {588e8218-d032-4f27-a7de-a0e06bdff217}` just to see if that changes anything.

Off my chest: It might work, but this is a bog-strange way to open a SSH tunnel from `.NET`. There's [SSH.NET](https://github.com/sshnet/SSH.NET). [Mostly inside voice. Not your ask. Pretend I didn't say it.]

**Comment by benhillis** [comment]
@mattmon1 - I think your issue is around running as a Windows service.  What user context is the service running as?  WSL distributions are per-user so if you're running the service in session 0 or as a different user you're going to run into issues.

**Comment by mattmon1** [comment]
Thanks for the thoughts Ben. Your are right that the issue only occurs when running as a windows service. I've two application wrappers - console app and windows service.

The console app version runs fine when run in a command window with administrator perms using the same user with which WSL ubuntu was installed.  

I've tried installing the windows service two ways - using the user credentials that were used for the WSL ubuntu install and using Local System credentials. The windows service fails with the same application error for both sets of credentials. For both sets of credentials, I made sure that the user had full control privileges for both the "AppData Local" and "Program Files Canonical" versions of ubuntu.exe.

Please let me know your thoughts. I agree that this issue seems to be session/user/privilege related.

Regards,
Matt

**Comment by benhillis** [comment]
@mattmon1 - What windows version are you using?  Launching WSL from a non-interactive user context was added in a fairly recent insider build (17046).

**Comment by mattmon1** [comment]
That could be it. I'm running 16299. Not in the insiders program at the moment - can I still upgrade or do I need to sign-up?

![winver 2018-01-22_13-13-21](https://user-images.githubusercontent.com/35613928/35239524-a0b12c36-ffa8-11e7-89eb-1081953cf897.png)

**Comment by benhillis** [comment]
You can join the Insider program at any time: https://insider.windows.com/en-us/

If you don't want to join and can wait a few months, the change in question will be available in the next cumulative Windows Update, due this Spring.

**Comment by mattmon1** [comment]
@benhillis  Thanks for the guidance. I'll go ahead, join the program, update and test - to prove that the new build works and post the results on this thread.

What level of confidence do you have that build 17046 will fix this issue?

**Comment by benhillis** [comment]
Fairly high :)

**Comment by mattmon1** [comment]
@benhillis - Fairly high is spot on! :-) 

I joined the insider program and updated to build 17074. The service installs cleanly, starts and has successfully run all day. I've tried a battery of integration tests - both positive and negative and all seems well.

Please let me know if you can provide more exact guidance for the cumulative Windows Update due this Spring. e.g. Will the update happen at the end of March or is June a more likely target?

Thank you for the guidance in resolving this issue.

Regards,
Matt

![winver insiders prog - 2018-01-23_17-11-40](https://user-images.githubusercontent.com/35613928/35306280-c63f521a-0094-11e8-988d-e7c387274371.png)

**Comment by benhillis** [comment]
@mattmon1 - I'm glad to hear it's working for you.  An exact release date has not been announced, but I suspect it will arrive before June.

**Comment by therealkenc** [comment]
No version identified but we'll assume this made it into the Spring Update.
