### ISSUE TITLE
Linux subsystem takes forever to search for required components

### ISSUE THREAD

**Issue by Zedonboy** [microsoft/WSL#2861]
Hi tried this commmand
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

it outputs error 
`Enable-WindowsOptionalFeature : Enable-WindowsOptionalFeature failed. Error code = 0x8000ffff
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand`

I tried turning on Linux Subsystem feature but it takes forever to search for components

I have checked all the specs, i ticked all 'em

Can please tell whats wrong?

**Comment by benhillis** [comment]
Have you tried enabling the feature via the "Turn Windows features on or off" setting page?

**Comment by Zedonboy** [comment]
Actually its not an issue,  just that after trying to on the Subsystem
feature.....  error 0x8000fff pops up after a long session of searching for
required components.

**Comment by benhillis** [comment]
Could you ensure that the trustedinstaller service is set to auto?

`SC config trustedinstaller start= auto `
