### ISSUE TITLE
If I update  my win10,dose it will update the WSL together?

### ISSUE THREAD

**Issue by futureproperty** [Microsoft/WSL#2862]
In [wsl Release Notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes),the update of windows will also update the WSL. 
But I have installed WSL before windows update.So if I want to experience the update of WSL,need I reinstall my WSL after updating My windows?
Sorry for my bad English.

**Comment by Biswa96** [comment]
Updating Windows will updates the components which run WSL in Windows system (e.g. lxcore.sys, LxssManager.dll etc.) but does not update the GNU/Linux userspace.
