### ISSUE TITLE
Performance issue when serving Python3.5 scripts through Apache + WSGI

### ISSUE THREAD

**Issue by dandrei** [Microsoft/WSL#2863]
Windows build number: `10.0.16299.192`

Hardware configuration:
```
Processor: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2808 Mhz
Total Physical Memory:     8,072 MB
SSD
```

Applications involved:
- `apache2/xenial-updates,xenial-security,now 2.4.18-2ubuntu3.5 amd64`
- `python3/xenial,now 3.5.1-3 amd64`
- `libapache2-mod-wsgi-py3/xenial,now 4.3.0-1.1build1 amd64`

What I'm doing:
- Serving a Python script from `/var/www/html` using Apache and WSGI
- Dependencies are installed inside a `virtualenv`

Relevant section from Apache's `000-default.conf` site configuration:
```
WSGIDaemonProcess test_app user=www-data group=www-data processes=1 threads=5 python-home=/var/www/html/venv/lib/python3.5/site-packages/ request-timeout=1
WSGIScriptAlias / /var/www/html/wsgi.py

<Directory /var/www/html>
   WSGIProcessGroup test_app
   WSGIApplicationGroup %{GLOBAL}
   Require all granted
</Directory>
```

What's wrong:
- Even with `request-timeout=1`, processing still takes as long as 10 seconds.
- Without specifying `request-timeout`, processing hangs indefinitely.

What should be happening instead:
- Processing should be significantly faster, to aid in development.
- Identical configuration tested on a native Linux, there are no delays.

Hypothesis:
- The output is possibly generated, but fails to be delivered, that's why the timeout makes it work.

**Comment by therealkenc** [comment]
[CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). Probably #1671 et al given the nature of the pause, but who knows.
