### ISSUE TITLE
Internet connection extremely slow

### ISSUE THREAD

**Issue by xama5** [Microsoft/WSL#2864]
I have a 300/20 internet connection which I can fully max out on Windows. On the WSL (Ubuntu) I only get 0.04/0.08. (Both tested with speedtest)

APT and NPM perform even worse and are barely usable at this point. Adding mirrors to APT helped a little: https://askubuntu.com/questions/37753/how-can-i-get-apt-to-use-a-mirror-close-to-me-or-choose-a-faster-mirror (it went from a couple Bytes/s to 10 Kilobytes/s)

WSL is a fresh install. Enabled it in the Windows Features and installed the Ubuntu App from the Windows App Store.

I already added the AppData-folder for WSL to the Windows Defender exception list. Turning Defender completely off didn't help either.

* Windows build number:  10.0.16299.192

* ~$ uname -a
Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

I know I won't get the same connection speed as I do in Windows, but is it really this bad?

**Comment by therealkenc** [comment]
Duping into #2477 since it is the same discussion.
