### ISSUE TITLE
/dev/tty default 600 permissions prevents ssh with passphrase for user

### ISSUE THREAD

**Issue by jmzagorski** [Microsoft/WSL#2865]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 Version 1607 (OS Build 14393.1715)

* What you're doing and what's happening:

1. Hit Window Key and type bash and run Bash.exe, by default logs you in as root
3. Create a new user `useradd -m -g users -G "adm,tty,floppy,sudo,audio" -s /bin/bash jeremy && chown -R jeremy:users /home/jeremy`
4. Add `exec su jeremy` to top of root's .profile file 
5. Type `exit` to leave bash
6. Create a shortcut target `%windir%\system32\bash.exe --login`
7. Run the new shortcut as admin. You should now be logged in as jeremy
9. Run `ssh -vT <your host here>`
10. Towards the bottom of the debug messages, you should see  `debug1: read_passphrase: can't open /dev/tty: Permission denied`
11. To confirm error in prior step, run `ls -l /dev` to see that /dev/tty has root:tty 600 permissions
13. Run `chmod 660 /dev/tty`
14. Rerun `ssh -vT <your host here>` and it should prompt you for passphrase and you can ssh into host

* What's wrong / what should be happening instead:

1. What's wrong - the default 600 permissions prevents ssh access for users
2. What should be happening - /dev/tty should have 660 permissions so ssh does not fail by default with passphrase for users in tty group.

* It seems this was an issue back in 2016 in https://github.com/Microsoft/WSL/issues/617 and was updated to 660, but that has since changed back to 600.

**ssh is just one example, but of course affects other programs in a similar manner**

**Comment by benhillis** [comment]
You are still running Anniversary update (14393), this is fixed in a later version (Creators Update I believe).

**Comment by ChuckM** [comment]
Not fixed for the USB ttys (/dev/ttyS*)

**Comment by benhillis** [comment]
@ChuckM  - That is #3042.

**Comment by ChuckM** [comment]
Thank you @benhillis added my comment to #3042
