### ISSUE TITLE
sslyze nassl error

### ISSUE THREAD

**Issue by bennysp** [Microsoft/WSL#2866]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.192]
(this is a fresh install of both OS and subsystem)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. `apt-get install python-pip -y`
1. `pip install --upgrade setuptools`
1. `pip install sslyze`
1. *`sslyze`* hit [ENTER]

You will get the following error:
`
Traceback (most recent call last):
  File "/usr/local/bin/sslyze", line 7, in <module>
    from sslyze.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/sslyze/__main__.py", line 12, in <module>
    from sslyze.concurrent_scanner import ConcurrentScanner
  File "/usr/local/lib/python2.7/dist-packages/sslyze/concurrent_scanner.py", line 9, in <module>
    from sslyze.plugins.plugin_base import PluginScanResult
  File "/usr/local/lib/python2.7/dist-packages/sslyze/plugins/plugin_base.py", line 12, in <module>
    from sslyze.server_connectivity import ServerConnectivityInfo
  File "/usr/local/lib/python2.7/dist-packages/sslyze/server_connectivity.py", line 13, in <module>
    from nassl.ssl_client import ClientCertificateRequested, OpenSslVersionEnum
  File "/usr/local/lib/python2.7/dist-packages/nassl/ssl_client.py", line 7, in <module>
    from nassl import _nassl
ImportError: /usr/local/lib/python2.7/dist-packages/nassl/_nassl.so: cannot enable executable stack as shared object requires: Invalid argument
`

* What's wrong / what should be happening instead:

I should get the sslyze help screen.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

[sslyze.zip](https://github.com/Microsoft/WSL/files/1650611/sslyze.zip)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> in <module> from nassl import _nassl ImportError: /usr/local/lib/python2.7/dist-packages/nassl/_nassl.so: cannot enable executable stack as shared object requires: Invalid argument

#286 #916 #2553 #2562 ([message](https://github.com/Microsoft/WSL/issues/2553#issuecomment-335201548)) etc etc

**Comment by koczkatamas** [comment]
I think the executable stack is unnecessary for NASSL, it is only enabled by mistake. After turning it off, sslyze seemingly works on WSL:
```
sudo apt install execstack
sudo execstack -c /usr/local/lib/python2.7/dist-packages/nassl/_nassl.so
sudo execstack -c /usr/local/lib/python2.7/dist-packages/nassl/_nassl_legacy.so
sslyze ... => works
```

**Comment by bennysp** [comment]
Thank you @koczkatamas .  This worked for me!

**Comment by koczkatamas** [comment]
@bennysp meanwhile I reported the issue to the author of `sslyze` (see the linked issue above), and it has been fixed.

Hopefully there will be a new release soon, so it won't be necessary to modify the files manually.
