### ISSUE TITLE
Using a Windows GUI editor launched from WSL as git core.editor doesn't work

### ISSUE THREAD

**Issue by kallja** [Microsoft/WSL#2867]
I'm running Microsoft Windows [Version 10.0.16299.192]

I've set up git editor under WSL with the following comand:
`git config --global core.editor "'/mnt/c/Program Files/Sublime Text 3/subl.exe' -w"`

I then `cd` myself into a local git repository in `/mnt/c/Users/username/git/repo` and run:
`git rebase -i`

Sublime Text 3 is launched, but WSL hands it a path argument it can't work with:
`/mnt/c/Users/username/git/repo/.git/rebase-merge/git-rebase-todo`
instead of the expected:
`C:\Users\username\git\repo\.git\-rebase-merge\git-rebase-todo`.
![subl](https://user-images.githubusercontent.com/4089904/35220874-bcf2deee-ff80-11e7-83b1-d1d317370514.png)

Is there a facility to translate paths in WSL to their Windows counterparts dynamically?

**Comment by benhillis** [comment]
Yes, there is a tool called wslpath that should be available in your build. /bin/wslpath

**Comment by imrimt** [comment]
@benhillis I'm unclear on what are you suggesting here? I'm running into this as well and would love to understand what the workaround is

**Comment by yincrash** [comment]
@imrimt 

1. Create a shell script named `wsl_git_editor.sh` containing:
```
#!/bin/bash

WINDOWS_PATH=$(wslpath -w "$1")

"/mnt/c/Program Files/Sublime Text/subl.exe" -w "$WINDOWS_PATH"
```
2. Make the script executable with `chmod +x wsl_git_editor.sh`.
3. Add the script to your global config: `git config --global core.editor <file-location>/wsl_git_editor.sh`
