### ISSUE TITLE
.NET Core throws NetworkInformationException because of missing files on WSL

### ISSUE THREAD

**Issue by jakubsuchybio** [microsoft/WSL#2868]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening:
When I start .NET Core project, that calls ```NetworkInterface.GetAllNetworkInterfaces()``` then on WSL it throws ```NetworkInformationException```. See more info here: https://github.com/dotnet/corefx/issues/26476

* What's wrong / what should be happening instead:
From my understanding of the communication on corefx repo. There are missing files of network adapters, that should be there, but are not on WSL. Again more info in corefx issue.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
I think this is not applicable I think?

**Comment by danmosemsft** [comment]
Specifically if I call getifaddrs it gives me a series of interfaces, here listed by ifa_name and ifa_addr->sa_family for example:
```
eth0   AF_PACKET1
lo   AF_PACKET1
wifi0   AF_PACKET1
wifi1   AF_PACKET1
wifi2   AF_PACKET1
eth0   AF_INET
eth0   AF_INET6
lo   AF_INET
lo   AF_INET6
wifi0   AF_INET
wifi0   AF_INET6
wifi0   AF_INET6
wifi0   AF_INET6
wifi0   AF_INET6
wifi0   AF_INET6
wifi1   AF_INET
wifi1   AF_INET6
wifi2   AF_INET
wifi2   AF_INET6
```

.NET Core is expecting sub directories of `/proc/sys/net/ipv4/conf/` and a file within them named `forwarding` to exist for all names of family AF_INET. For example it expects `/proc/sys/net/ipv4/conf/eth1/forwarding` as in this case `eth1` is reported as `AF_INET`.

As far as I understand it, WSL should have those folders if it reports those interfaces.

**Comment by therealkenc** [comment]
> `(Could not find a part of the path '/proc/sys/net/ipv4/conf/eth0/forwarding'.) (Could not find a part of the path '/proc/sys/net/ipv4/conf/eth1/forwarding'.)`

Oddly I can't find a dupe that is precisely on message. Another `/proc` entry I hope gets stubbed. The file needs a `0`, contrast "implement IP forwarding".

As an experiment you could try a trick [like here](https://github.com/Microsoft/WSL/issues/2518) and stub it yourself, just to see what happens. Not recommending it as a work-around, mind.

**Comment by danmosemsft** [comment]
`forwarding` is just what happens to be hit first. The whole ipv4, ipv6, etc folders are missing.

**Comment by therealkenc** [comment]
Oh yeah I realise that 🙂. Take about 20 minutes to write a script to populate `log_martians` and the rest return zero or whatev. It isn't a work-around. It is barely an experiment. Call it a thought experiment.
