### ISSUE TITLE
Segmentation fault when calling "rpm --initdb --dbpath" on Ubuntu for Windows

### ISSUE THREAD

**Issue by sealor** [Microsoft/WSL#2871]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.15063]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I'm trying to run `rpm --initdb --dbpath`. But it segfaults.
```
root@computer:~# apt-get install rpm
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  debugedit libarchive13 liblua5.2-0 libnspr4 libnss3 libnss3-nssdb librpm3 librpmbuild3 librpmio3 librpmsign3 rpm-common rpm2cpio
[...]
Setting up rpm (4.12.0.1+dfsg1-3build3) ...
Processing triggers for libc-bin (2.23-0ubuntu7) ...
root@computer:~#
root@computer:~# mkdir local
root@computer:~# rpm --initdb --dbpath $PWD/local
Segmentation fault (core dumped)
```

* What's wrong / what should be happening instead:
It should create a local RPM database.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

-> [rpm.strace gist](https://gist.github.com/sealor/3851222156166ce080a53285d4d405f0)

**Comment by therealkenc** [comment]
> 10.0.15063

You are on Creators Update so you are probably looking at #658 "mmap's problem". On 17074 `rpm --initdb` runs and populates directory `local` with `__db.001` and plausible looking files. Try upgrading to Fall Creators Update 16299 and see how that fares. Ref #2852 just as a heads up.

**Comment by hickeng** [comment]
@therealkenc I'm still hitting this issue with`Microsoft Windows [Version 10.0.17123.1]`

@sealor See #1812 for a similar issue (although with yum) and https://github.com/Microsoft/WSL/issues/1812#issuecomment-290399704 for a work around.

**Comment by therealkenc** [comment]
No segfault here with the simple three line repro in the OP. Same result as previously. This is on 17623. Most unfortunate that no one replied to confirm or deny whether #1812 was fixed or not for nearly a year. Per mmap's problem, note that #902 was de-duped; don't know if it matters to `rpm`'s grief. But again, that `rpm --initdb --dbpath $PWD/local` does not dump here, for me, in January or as of this writing.

**Comment by hickeng** [comment]
@therealkenc apologies for the delay in confirmation/refutation. I've been running with the aforementioned workaround for that time, and it's only when initializing a new system where I've hit it again.
Sounds like this behaviour is as expected given https://github.com/Microsoft/WSL/issues/1812#issuecomment-293640056 .

**Comment by therealkenc** [comment]
Okay let's call this a dupe then (without prejudice). If the problem turns out to be #902 that's okay. The nature of work-around (making the file size nonzero) implies to me there might still be goblins; but if there are goblins it is #902.
