### ISSUE TITLE
how to format command line?

### ISSUE THREAD

**Issue by anlexN** [Microsoft/WSL#2878]
Now command like this:
![image](https://user-images.githubusercontent.com/8686739/35426640-75aafc5c-029f-11e8-86dd-3068b7c84d29.png)

I expect like this:
```
anlex_N@N-Acer:/mnt/c/Users/gwq19/Desktop/expressjs/express-locallibrary-tutorial `
$ 
```
how to set?

**Comment by therealkenc** [comment]
You can find information on setting the bash prompt (`$PS1`) in places like [here](https://help.ubuntu.com/community/CustomizingBashPrompt), [here](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html), [here](https://wiki.archlinux.org/index.php/Bash/Prompt_customization), [here](https://www.digitalocean.com/community/tutorials/how-to-customize-your-bash-prompt-on-a-linux-vps), and elsewhere.
