### ISSUE TITLE
Can I run gui softwares (except terminal-gui like midnight commander) on WSL ?

### ISSUE THREAD

**Issue by arjunkravi** [Microsoft/WSL#2879]
I'm just a beginner . I tried to run synaptic from bash (wsl) but was unsuccessful . Is that possible? .

**Comment by sunilmut** [comment]
@arjunkravi - Thanks for your interest in WSL. Yes, it is "possible" to run GUI applications on WSL using x-server, but, it's **not** an officially supported scenario. But, having said that people have had good success with it. Just search online on how to run GUI application on WSL and you will find many resources. Here is [one](http://blog.sqlyog.com/how-to-add-a-gui-to-the-new-bash-console-in-windows-10/) for example.
