### ISSUE TITLE
folders showing 4096KB

### ISSUE THREAD

**Issue by arjunkravi** [Microsoft/WSL#2880]
https://github.com/arjunkravi/images.git .. PLEASE VISIT AND VIEW THE IMAGE . ALL THE FOLDERS ARE SHOWING 4096 IN SIZE COLUMNS ... VIEWED IN MIDNIGHT COMMANDER FILE MANAGER

**Comment by benhillis** [comment]
Please fill out the issue template. WHY ARE WE SHOUTING?!
