### ISSUE TITLE
Can't fully uninstall wsl

### ISSUE THREAD

**Issue by benqzq** [Microsoft/WSL#2881]
I uninstalled WSL from Powershell with:

    lxrun /uninstall

I then reinstalled with

    lxrun /install

Yet I still had some files from the previous install. I hoped that the uninstall would remove these files but it didn't.

---

Given that `lxrun /uninstall /full` is deprecated, how can one fully uninstall WSL and delete all it's files so the next install will be a "pure WSL" without files from previous installs?...

**Comment by Biswa96** [comment]
Use wsl command: `wsl.exe /u <distro_name>`

**Comment by benqzq** [comment]
Doesn't work:

`wsl.exe /u ubuntu`

**Comment by scooley** [comment]
Which files are you noticing?

**Comment by benqzq** [comment]
IIRC, these were files in my home directory and under /var/www/html.

**Comment by benhillis** [comment]
lxrun.exe is in maintenance mode, the new install mechanism is via the Microsoft Store.  I suggest deleting the files manually.

**Comment by therealkenc** [comment]
Nah that doesn't work either. Just sayin'. 

![wsl-ubuntu-uninstall-fail](https://user-images.githubusercontent.com/7049700/35542306-2de73148-0514-11e8-8bf3-1b7744cc0f22.png)

**Comment by benhillis** [comment]
@therealkenc - The user seems to be talking about the legacy install mechanism yet your screen shot has ubuntu.exe in it?

**Comment by therealkenc** [comment]
It was meant as a wry observation on "[un]install mechanism is via the Microsoft Store". Uninstalling via the Windows Store errors out for me. But disregard; it is not worth pursuing.

**Comment by benhillis** [comment]
@therealkenc - Oh interesting, I have not had issues with windows store uninstallation, I'll see if I can get a repro.

**Comment by benqzq** [comment]
I personally would prefer to install/uninstall only from CLI...

**Comment by benhillis** [comment]
@benqzq - You can also unregister distros via wslconfig.exe
