### ISSUE TITLE
rm hangs when operating on directory under /mnt/c

### ISSUE THREAD

**Issue by purag** [microsoft/WSL#2882]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

**Microsoft Windows [Version 10.0.16299.192]**

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

When trying to use my Linux installation of `git` (`/usr/bin/git`) on a repo inside `/mnt/c/Users/`, I got this error:

```
purag › git add
fatal: Unable to create '/home/purag/projects/grahe/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

A week or so ago, this was working okay; I occasionally had this problem before but removing `index.lock` worked. Other times, I wouldn't encounter this specific problem, but other things would hang (i.e. `cd`ing into the git repo since my PS1 runs git commands), but a restart fixed the problem every time.

So today I had the `index.lock` problem, and every time I tried to remove the file Bash would hang (and stay in the unkillable state; I couldn't even close the Bash window using the title bar).

To clarify the series of commands:

```
> cd ~/projects/grahe
> git add
 # index.lock error
> rm .git/index.lock

```

**Note:** I symlinked `~/projects/grahe` to `/mnt/c/Users/Purag/AndroidStudioProjects/GRAHE`, but the problem occurs no matter how I access the directory in question.

* What's wrong / what should be happening instead:

I'm not sure if this is actually supported (using Linux git in a Windows directory), but it worked fine before and I would like to continue using this functionality since I plan on installing any IDEs/GUI apps on Windows, and it would be really nice to not have to duplicate my configuration (I also use gpgsign which would mean keeping my keys on both the Linux and Windows side).

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

**[gist](https://gist.github.com/purag/984611bccf55cd3f4f7871778c1128a2)**

**Comment by juhap** [comment]
I have seen few hangs when I do certain git operations (I think it was git commit) from bash in my Dropbox directory hosted in Windows drive and accessed through a link(1). This did not happen when I accessed the directory without symlink. 

The result is similar unkillable state for bash. Can't kill the process and can't open another bash Window. Only remedy seems to be reboot. 

I was not able to replicate this with a link I had manually created with mklink command. Haven't yet figured out what is special with the link created by Dropbox. 

(1) Linked directory is "c:\users\username\Dropbox" while real directory is "c:\users\username\Dropbox (Personal)". Dropbox (annoyingly) forces this naming convention when you have both personal and business account on the same machine.

**Comment by yamalight** [comment]
Experience exactly same issue with node/npm under WSL. 
Typically first I get `Unable to create './node_modules/somefile': File exists.`, after either trying to re-run install or execute `rm -rf ./node_modules` (or `~/.npm/cache`) - windows BSODs and reboots immediately after running `rm` command.
This does not happen consistently - sometimes everything seems to work perfectly fine, which makes it even weirder.

**Comment by tony** [comment]
@yamalight I am experiencing the exact same issue. Except no BSOD, ultimately i need to restart to get access to run `npm install` again since `node_modules` has undeletable/unmodifiable files.

Do you have your `ver` (from inside `cmd`?)

Mine:

Ubuntu WSL

Microsoft Windows [Version 10.0.17763.475]  

npm 6.9.0

Situation:

I have my project (including node_modules) in windows. I symlink it inside WSL, e.g. `~/work -> /mnt/c/Users/tony/source/repos/`

I can't `rm -rf node_modules`. Sometimes I can't even do it via `Shift+delet` in explorer. No permissions

`sudo rm -rf node_modules` also won't work

I have to restart to delete it

**Comment by yamalight** [comment]
@tony had that with ubuntu / node 11 / npm 6.8.x. though it might be distro-related, so tried wiping ubuntu and installing debian (with node 12 / npm 6.9.x) - it did help for some time, but after win10 update it started randomly BSODing again.
I'm thinking about just waiting for WSL2 at this point because I'd already lost some (luckily minor bit of) work due to this issue 😢

**Comment by tony** [comment]
@yamalight Thanks for the response

Yeah maybe it will entail a new WSL release (perhaps even WSL2)

If anyone else chimes in, please respond to the thread if you have a workaround for this.

**Comment by ashenwgt** [comment]
OS needs a reboot to clean corrupted files sometimes (e.g. above scenario - when link count gets zero).

Detailed explanation here: https://superuser.com/a/1441014/629535

**Comment by WMeldon** [comment]
If you want to avoid rebooting your machine, just restarting just the WSL service fixes this for me.  You can do this by going to the Services tab in the Windows Task Manager and then restarting LxssManager.
