### ISSUE TITLE
Bash occasionally runs in the background at 100% CPU load,

### ISSUE THREAD

**Issue by EricPell** [Microsoft/WSL#2883]
Bash occasionally runs in the background at 100% CPU load. This seems to happen for a variety of reasons, and I have not been able to pin down why. When this occurs the WSL becomes unresponsive and I can not open another terminal to obtain information on what is being run, or attempt to stop it.

From Windows Task Manager, all that shows as a process is "bash". The process is not responsive to attempts to kill it.

This occurs on current flights, and as recently as 17083. 

The only solution I have found is to restart the computer.

**Comment by sunilmut** [comment]
@EricPell - Agh. Can you please follow the instructions for "Bash is hung" from [here](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting) and send the dumps over to secure@microsoft.com with reference to the GitHub issue.

**Comment by mqudsi** [comment]
Have you checked with `sudo top -S` from another WSL shell to see if that shows anything more?

**Comment by benhillis** [comment]
We're going to need some additional information to diagnose what is happening.  Please reopen a new issue following the issue template if you continue to experience this issue.

**Comment by xarthurx** [comment]
I also encounter this.

I'm using zsh as my shell.
The following steps are reproducible on my laptop:

1. type `zsh`
2. run some commend, like `cd ..` etc.
3. exit zsh

repeat the above steps for several times, then open task manager.
There'll be around 2-5 zsh sessions with CPU 100% usage there.

**Comment by therealkenc** [comment]
ref #3914

**Comment by jdukleth** [comment]
![image](https://user-images.githubusercontent.com/15095818/75489335-a906d900-5977-11ea-9865-3b94f1b48f8d.png)

Same thing happens to me with bash. 100% CPU load and I can't even force quit the processes. I just reinstalled Windows 10 and WSL. Installed WSL through "turn features off/on", turned developer mode on, installed ubuntu from Windows store.
