### ISSUE TITLE
cd into folder really slow.

### ISSUE THREAD

**Issue by masters3d** [Microsoft/WSL#2885]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.16299.125]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am 'cd' into a big folder that lives on the windows side.  

`git version 2.15.1`  

`find . -type f | wc`:   
`  15789   16064 1321131`  

It takes 1+ minutes to complete operation.   

* What's wrong / what should be happening instead:

It is way too long. Other folders 'cd' are almost instant.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

Not sure how to stance built in command 'cd'

**Comment by masters3d** [comment]
Closing. This seems to only happen the first time you switch into a big folder with a ton of files

**Comment by masters3d** [comment]
Nope. This comes back after closing the bash window.

**Comment by masters3d** [comment]
Sometimes `control + c` allows you to see the target folder

**Comment by masters3d** [comment]
Seem to only manifest when running in Legacy mode

```
>wslconfig.exe /list
Windows Subsystem for Linux Distributions:
Legacy (Default)
Ubuntu
```

**Comment by xarthurx** [comment]
I also notice that when opening a large file for the first time, it is very slow.
Opening again while the bash.exe is open will be fast.
But once the bash.exe is closed and re-open again, everything start again. (opening for the first time will be painfully slow.)

**Comment by masters3d** [comment]
sad state of things. I was hoping to use bash for all git related things but Mubarak’s repo is really big. I am forced to use git windows.

**Comment by therealkenc** [comment]
#981 and #873 are the landing zones.
