### ISSUE TITLE
Execute binary without registering/installing any distro

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#2886]
* Windows build number:  Windows 10 Pro Insider Preview build 17083

When I install any distribution from Windows Store or with `WslRegisterDistribution()` I see a strange list of processes in Process Monitor. Let, the path is "C:\MyFiles" where the distro will be installed.

* First, LxssManager service creates `bsdtar` file in "C:\MyFiles\rootfs" and set it to read-only.

![bsdtar_create](https://user-images.githubusercontent.com/31443074/35562058-3a2a6a8c-05d8-11e8-9270-7f4ca9348081.PNG)

* Then, the `bsdtar` (may be) is loaded as PicoProcess by Lxcore.sys driver. The driver execute the `bsdtar` to extract the compressed tarball. Here it creates `bash` after creating `bsdtar`. See the time difference.

![bash_create](https://user-images.githubusercontent.com/31443074/35562212-b1f1b106-05d8-11e8-9450-3ec2fa04e291.PNG)

* So, my question is, Can any single binary be executed (with init) without installing whole distribution or creating registry of that distro?

**Comment by Biswa96** [comment]
>launch bsdtar as the init process

Yes, I found that in LxssManager.dll as `"init=/bsdtar -x --xattrs -f -"` after CreateJobObject() and CreateFile(). But how can an ELF binary be run as init process? Please forgive me if I asked a stupid question. I had read that after booting Linux kernel first loads the `/init` binary then forks other processes.

>The reason is unless the binary is statically linked it is going to rely on libraries etc.

I compiled a static linked `busybox` and can be run with `LXATTRB` attribute in WSL. Hence I thought if it can run without making a registry.

**Comment by therealkenc** [comment]
> Hence I thought if it can run without making a registry.

I still [hold out hope](https://github.com/Microsoft/WSL/issues/2744#issuecomment-350513447)....

**Comment by Biswa96** [comment]
I find that every time when I launch WSL, LxssManager.dll spits out `init` file from it's resource and places in `rootfs` folder. 
What happen if I replace that `init` binary resource with static linked `busybox`in that DLL file?

**Comment by therealkenc** [comment]
> What happen if I replace that init binary resource with static linked busyboxin that DLL file?

Won't work because WSL `init` does stuff required by `LxManager`, notably talk to `/dev/lxss`; which busybox `init` has never heard of. Because `/dev/lxss` is Not Linux™. That's if LxManager starts at all. I think (?) `LxssManager.dll` is a signed system file that can't be swapped out without a lot of deep wizardry. If it is possible at all.

But that is so much talk. The way to find out what will happen if you replace the resource in that binary is.......

Skip the follow-up saying `wsl.exe` fails then with error `0x80632841` (I made that number up by smashing my keyboard). You are getting warmer though.

**Comment by Biswa96** [comment]
>Won't work because WSL init does stuff required by LxManager, notably talk to /dev/lxss

@therealkenc  During tarball extraction, `init` is not added to `rootfs` folder. `bsdtar` is created before `init` file and executed without `init`. So, I thought if it is possible to replace that `bsdtar` with a static compiled `busybox` binary. 
>without a lot of deep wizardry.

Ya, replacing resources of `LxssManage.dll` does not work. Do you know that "wizardry"? :wink: 

@benhillis By the way, why `init` is always created with `1970-01-01 05:30:00` date & time? `time(0)` can be added in `ZwSetEaFile ()` to set it current time. & Is there any documentation of what value associated after `LXATTRB` EaName? **

<sub><sup>** See remarks of [_FILE_FULL_EA_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_file_full_ea_information) struct.</sup></sub>

**Comment by benhillis** [comment]
@Biswa96 - Not currently. Those are internal implementation details that are subject to change.

**Comment by therealkenc** [comment]
> Ya, replacing resources of LxssManage.dll does not work. Do you know that "wizardry"? 😉

As I said it wouldn't matter if you possessed said wizardry. Because busybox init is going to spawn something that wants to talk to a tty. And that will almost certainly fall on it's face because `init` hasn't said hello to LxssManager. But you are getting warmer.

**Comment by Biswa96** [comment]
Closing temporarily.....

**Comment by Biswa96** [comment]
@benhillis Why are these values being queried from `HKLM\System\CurrentControlSet\Services\lxss` registry key during distro installation? Are they for future use? Or can these be configured to do some magic in WSL?
```
PrintSysLevel
PrintLogLevel
KdBreakPointErrorLevel
TraceloggingLevel
KdBreakOnSyscallFailures
TraceLastSyscall
WalkPicoUserStack
RootAdssbusAccess
DrvFsFallback
OvFsUnstableInode
 ```
