### ISSUE TITLE
Memory leak repeatedly unzipping archive: 3G in 1h

### ISSUE THREAD

**Issue by BobBall** [Microsoft/WSL#2887]
Microsoft Windows [Version 10.0.16299.192], Ubuntu 14.04.5 LTS

Repeatedly extract an archive and watch the in-use memory (both under resource monitor + "free -m" from bash) increase, using 2.5-3G in an hour
Test used:
for n in $(seq 1 50000); do unzip -q /tmp/test/test_archive.zip; rm -rf /tmp/test/unzipped/*; done
Archive available from https://citrix.sharefile.com/d-s769596323f24b4fa

Tue Jan 30 12:00:07 2018
Resource Monitor shows "In use" 6950
             total       used       free     shared    buffers     cached
Mem:         12232       7009       5222         17         33        184
-/+ buffers/cache:       6792       5439
Swap:        31823         35      31787

Tue Jan 30 13:04:37 2018
Resource Monitor shows "In use" 10554
             total       used       free     shared    buffers     cached
Mem:         12232      10587       1644         17         33        184
-/+ buffers/cache:      10370       1861
Swap:        31823         48      31774

I have not yet found a way to release the memory used (e.g. closing bash does not release the memory - only a reboot appears to release it, hence the belief it's a leak)

I *believe* this is a regression.  I have a script which routinely unzips thousands of archives and I believe I was not seen this issue late last year, but my script now routinely runs out of memory.
Updates recently installed include KB4056892, W10 1709 (KB4058043).  I don't know if it worked after KB4058043 as that was installed mid-december and I may not have run the script since.

**Comment by benhillis** [comment]
@BobBall - I ran your repro a bunch this morning and all I see all of the outstanding allocations go away when I stop the lxss manager service (which will happen automatically 5 minutes after your last wsl process exits).  I do not think there is a memory leak here, just some state that gets cleaned up with the instance is torn down.

**Comment by therealkenc** [comment]
> I do not think there is a memory leak here, just some state that gets cleaned up with the instance is torn down.

It sounds from the description the state keeps growing, contrast say some cache which tops out and is re-used. If it keeps growing indefinitely, that's a bit like saying a program isn't leaking memory because it gets freed when the program exits. The instance might not get torn down for months, because `sshd` or `dbus` or whatever never exits. Maybe it has always leaked and this is just manifesting because the instances aren't as transient anymore?

**Comment by BobBall** [comment]
I used to leave my Bash open for days; is the implication here that I should only be using bash for very short-lived tasks (i.e. ones that take less than a few hours)?

Note that if I run my real script (I created a simple reproduction case for the ticket) on a fresh system it will consume all 12GB of host RAM in just a few hours.  If there is state being held then I'm guessing it's being held for too long; repeatedly unzipping files shouldn't cause the system to run entirely out of memory.

I did also try stopping the LXSSMANAGER service as well - that does not appear to release the memory for me, neither does waiting for 15 minutes after closing bash (I'm not aware of any other wsl processes running, and I assume that closing the last bash will close the last process? - note that the LXSS manager service did not seem to automatically stopped after 5 minutes)
It sounds that perhaps your repro does not have had the same symptoms as mine - is there any additional information I can capture on my side?

**Comment by sunilmut** [comment]
@BobBall - Given that @benhillis could not repro it (assuming he tried on an insider build), if you have a VM or any machine hooked up to Windows Insider builds, can you give that a try and see if the issue still persists?

**Comment by BobBall** [comment]
I'll try and find an insider build I can use

**Comment by benhillis** [comment]
@therealkenc - Any caches we have sound be bounded (start evicting the oldest entry after the max size is exceeded).  I'll continue to look at this and see if I can identify anything, but I wasn't even seeing my used memory numbers fluctuate much after running the repro for a few hours.

**Comment by BobBall** [comment]
Am setting up some VMs to try a repro on insider build 17083 and a clean W10 1709 build as well.

**Comment by therealkenc** [comment]
> @therealkenc - Any caches we have sound be bounded

Thanks Ben that's why I pulled the post -- it wasn't clear whether it was growing indefinitely or not. Worth observing that 2.5-3GB sounds like an awful lot of "state" for a 30kb zip file though. If someone did this test on Real Linux and committed memory blew up to 3GB, people would have a hairy ****. [I accept that is kind of the new normal, granted. No one seems to care when their Web Browser or Visual Studio does that.]

**Comment by BobBall** [comment]
Very unfortunately I can't reproduce either on a the insider build 17083 or a fresh W10 with 1709 installed :/
This ties up with @benhillis's observations but leaves me with no clue why I run out of memory on my production system...
I'm guessing a full reinstall might be needed to fix it

**Comment by benhillis** [comment]
It could very well be a bug that we fixed since Fall Creators Update.

**Comment by BobBall** [comment]
Except I also tested on a fresh fall creators update as well and couldn't reproduce there
I suspect we'll just have to close this bug as can't reproduce

**Comment by benhillis** [comment]
Shrug, thanks for reporting. I'll keep an eye out for memory leaks when I'm doing internal testing. We have some cool tooling that makes then easy to track down.

**Comment by BobBall** [comment]
Thanks for the reference to #2917 - I think it is very likely to be the same issue.
I am also using McAfee, using RamMap shows that this is also the Nonpaged Pool.

McAfee was not installed on either of the reproduction machines I attempted.

I also came to the conclusion today (hence was about to post on the ticket) that this could be related to writing files rather than specifically unzipping - which would be supported by McAfee scanning

**Comment by therealkenc** [comment]
Okay let's dupe in that direction then since McAfee was raised over there with a McAfee community ticket, and the variable seems pretty conclusive. In a idealised world, `unzip`, `gcc`, and `cat` are all the same program as far as the kernel is concerned. `cat` is just the least creative about what it does in userspace unbeknownst to the kernel between reading and writing.
