### ISSUE TITLE
Can't install WSDL distribution in WinRM session

### ISSUE THREAD

**Issue by dermeister0** [Microsoft/WSL#2888]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

    WindowsProductName             : Windows Server Datacenter
    WindowsBuildLabEx              : 16299.15.amd64fre.rs3_release.170928-1534

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I try to install Ubuntu in WinRM session to Windows Server 2016.

    [myserver]: PS C:\Distr\UbuntuInstall> .\ubuntu.exe
    [myserver]: PS C:\Distr\UbuntuInstall> $LASTEXITCODE
    -1073740791

* What's wrong / what should be happening instead:

An error returned: 0xC0000409
I expect the installer to work correctly via WinRM.

**Comment by 0xbadfca11** [comment]
Looks like same as #2858 that fixed in build 17017.
> Allow LxssManager to create WSL instances for non-interactive users (ssh and scheduled task support) [GH 777, 1602].
> https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17017

**Comment by dermeister0** [comment]
@0xbadfca11 
Thanks, I will try in newer build.
