### ISSUE TITLE
wsl.exe is not found when run from Jenkins

### ISSUE THREAD

**Issue by dermeister0** [Microsoft/WSL#2889]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

WindowsProductName : Windows Server Datacenter
WindowsBuildLabEx : 16299.15.amd64fre.rs3_release.170928-1534

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I try to run **wsl ansible-playbook** command from Jenkins which is running as Windows service.

However, wsl.exe is not visible to it.

    bat script: 'cd C:\\Windows\\System32 && dir ws*.exe'
    bat script: 'cd C:\\Windows\\SysWOW64 && dir ws*.exe'
    bat script: 'C:\\Windows\\System32\\wsl.exe ansible-playbook nginx.yml'

----

    C:\Program Files (x86)\Jenkins\workspace\Test>cd C:\Windows\System32   && dir ws*.exe
    Volume in drive C has no label.
    Volume Serial Number is 361E-057F

    Directory of C:\Windows\System32

    09/29/2017  04:25 AM           147,456 wscript.exe
    09/29/2017  04:25 AM            32,768 WSManHTTPConfig.exe
    09/29/2017  04:25 AM            38,400 wsmprovhost.exe
                3 File(s)        218,624 bytes
                0 Dir(s)  24,230,686,720 bytes free
    [Pipeline] bat
    [Test] Running batch script

    C:\Program Files (x86)\Jenkins\workspace\Test>cd C:\Windows\SysWOW64   && dir ws*.exe
    Volume in drive C has no label.
    Volume Serial Number is 361E-057F

    Directory of C:\Windows\SysWOW64

    09/29/2017  04:25 AM           147,456 wscript.exe
    09/29/2017  04:25 AM            32,768 WSManHTTPConfig.exe
    09/29/2017  04:25 AM            38,400 wsmprovhost.exe
                3 File(s)        218,624 bytes
                0 Dir(s)  24,230,682,624 bytes free
    [Pipeline] bat
    [Test] Running batch script

    C:\Program Files (x86)\Jenkins\workspace\Test>C:\Windows\System32\wsl.exe ansible-playbook nginx.yml
    'C:\Windows\System32\wsl.exe' is not recognized as an internal or external command,
    operable program or batch file.

The application exists in the directory when I check it as normal user.

    [myserver]: PS C:\windows\system32> dir ws*.exe

        Directory: C:\windows\system32

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----        9/29/2017   5:25 AM         164864 wscript.exe
    -a----        1/30/2018   2:59 AM          72704 wsl.exe
    -a----        1/30/2018   2:59 AM          41984 wslconfig.exe
    -a----        9/29/2017   5:25 AM          32256 WSManHTTPConfig.exe
    -a----        9/29/2017   5:25 AM          36864 wsmprovhost.exe
    -a----        9/29/2017   5:25 AM          91136 wsqmcons.exe

* What's wrong / what should be happening instead:

wsl.exe started correctly by Jenkins.

**Comment by thkrishn** [comment]
what is the difference between wsl.exe and bash.exe

**Comment by dermeister0** [comment]
@benhillis 
Thanks, *Sysnative* is the correct directory. However, I did not find any documentation about it on docs.microsoft.com site, only one comment by community member.

I got another problem - the command never completes:

    bat script: 'C:\\Windows\\Sysnative\\wsl.exe ls'

Probably, WSL does not work in non-interactive mode in my build.

**Comment by dermeister0** [comment]
@thkrishn 
Possibly wsl uses bash internally.

```
    C:\inetpub>wsl ls
    custerr  history  logs  temp  wwwroot

    C:\inetpub>bash ls
    /bin/ls: /bin/ls: cannot execute binary file

    C:\inetpub>bash -c ls
    custerr  history  logs  temp  wwwroot
```

https://docs.microsoft.com/en-us/windows/wsl/interop#run-linux-tools-from-a-windows-command-line

**Comment by philipogorman** [comment]
@dermeister0 did you figure out how to call wsl? I'm trying to figure this out too, the wsl version I have is 10.0.17134.1

**Comment by dermeister0** [comment]
@philipogorman 
No, I had to set up a virtual machine with Linux.

**Comment by luzlab** [comment]
I got WSL working inside of Jenkins. See my response [here](https://github.com/Microsoft/WSL/issues/2217). It works for scripts, but unfortunately plugins like the Docker Pipeline try to call `sh` directly and break...

**Comment by tapika** [comment]
Just in case if someone might wonder why bash or wsl is not seen by your build application - they are 64-bit and any 32-bit application (Jenkins or any other) will not be able to see those files.

```
C:\Users\user>dir /b c:\windows\system32\bash.exe
bash.exe

C:\Users\user>C:\Windows\SysWow64\cmd.exe
Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\user>dir /b c:\windows\system32\bash.exe
File Not Found


```

**Comment by luzlab** [comment]
If you check `c:\windows\sysnative\bash.exe` you'll find it. Windows does some magic behind the scenes with the [System32/SysNative folders](https://www.samlogic.net/articles/sysnative-folder-64-bit-windows.htm).

**Comment by winthrop-polk** [comment]
> Just in case if someone might wonder why bash or wsl is not seen by your build application - they are 64-bit and any 32-bit application (Jenkins or any other) will not be able to see those files.
> 
> ```
> C:\Users\user>dir /b c:\windows\system32\bash.exe
> bash.exe
> 
> C:\Users\user>C:\Windows\SysWow64\cmd.exe
> Microsoft Windows [Version 10.0.17134.472]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\Users\user>dir /b c:\windows\system32\bash.exe
> File Not Found
> ```

I see the top response when I run it from inside the server and the second response while running it via jenkins build. I can't tell what the Jenkins server is running as but I think ubuntu is 64 bit by default... are you suggesting that this will work if we make sure our Jenkins server is 64 bit? Any help is appreciated.

**Comment by winthrop-polk** [comment]
Best solution:
Modify Jenkin agent file, jenkins-slave.xml so it used jre x64 (Program Files) rather than x32 (Program Files (x86)). Make sure Java 64 is installed. Restart the Jenkins agent service. This is the best way to allow Jenkins to use the bash terminal.

**Comment by luzlab** [comment]
If Jenkins can't find `C:\Windows\System32\bash.exe`, you will find it at `C:/Windows/SysNative/bash.exe`.

I've had Jenkins running on Windows, running both sh, cmd and powershell steps, including using docker under linux for a few months now. It's fairly stable, but it feels like a massive hack. I'm looking forward to the new WSL coming out which should make it a little smoother...

**Comment by trashbat** [comment]
I didn't expect this to work as I likewise couldn't see a `C:\Windows\Sysnative` directory, either in a command prompt or Windows Explorer. But this is (presumably) because cmd.exe is 64-bit, whereas the Sysnative directory is only visible to 32-bit applications. It works fine when I specify `C:\Windows\Sysnative\wsl.exe` in my Jenkins pipeline.
