### ISSUE TITLE
"bash.exe" does not start 

### ISSUE THREAD

**Issue by thkrishn** [Microsoft/WSL#2891]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  
Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening: 
1. bash launcher does not show the bash command prompt 
2. I have tried to launch the bash.exe from powershell/cmd as well , it does not start 

* What's wrong / what should be happening instead:
I am suspecting the .bashrc i suppose , but I cant access the home dir of the subsytem 

* Strace of the failing command, if applicable:  this is before the subsystem starts, cant run strace  

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Could you try to run the following?

`wsl.exe /bin/sh`

**Comment by thkrishn** [comment]
-- I had to reboot my machine and then it started working, since then its working 

** there is another similar issue though, if a bash terminal window was left open (not measured the exact duration) and unused , the terminal becomes unresponsive and have to closed down and then reopened again , I couldn't find a solution for that

**Comment by benhillis** [comment]
Thanks for the additional information.  I recently fixed a bug that would look like bash.exe hanging on launch, I suspect you were running into that.  If you can lock down some repro steps for the other issue you are hitting please file a new issue. Thanks!

**Comment by thkrishn** [comment]
cool .... I can open a bug for that, I was suspecting they could be related.

**Comment by thkrishn** [comment]
Sorry I did not want to open a bug for this, if some fixes were added.... apt update / upgrade will make sure I get the latest fixes?
Or it comes with windows update?

**Comment by thkrishn** [comment]
C:\WINDOWS\system32>lxrun /update
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Sets the default subsystem user. If the user account does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
