### ISSUE TITLE
/proc/sys/fs/file-max not present

### ISSUE THREAD

**Issue by jacobkimmel** [Microsoft/WSL#2893]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Build Number: 10.0.16299.192

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am attempting to run a data processing pipeline using WSL. 

This pipeline relies on information within `/proc/sys/fs/file-max`. 

On standard Linux distros, this file is a plain text buffer containing an integer. WSL does not appear to have this file and adding a buffer to `/proc` the traditional way with `create_proc_read_entry()` relies on Linux header modules which do not seem to be present in WSL.

Reproduce by running the following command on WSL and compare to a Linux system.

```
$ cat /proc/sys/fs/file-max
```

* What's wrong / what should be happening instead:

File does not exist.
A plain text buffer containing an integer should be present.

**Comment by leixu2txtek** [comment]
+1

**Comment by hubcio** [comment]
+1

**Comment by bbsunchen** [comment]
+1

**Comment by shoffmeister** [comment]
Perhaps "a data processing pipeline" can be expanded a little bit? Does that come from a large framework?

This would help the developers understand the use cases of `/proc/sys/fs/file-max` and define the priority of addressing this.

(FWIW, `create_proc_read_entry` is a Linux kernel API function, and creating a proc entry would imply building a Linux kernel module. WSL is not a / the Linux kernel, and does not have the notion of Linux kernel modules. WSL is a shim which presents a lot of a Linux kernel ABI to the outside world.)

**Comment by jacobkimmel** [comment]
> Perhaps "a data processing pipeline" can be expanded a little bit? Does that come from a large framework?

I don't remember the original context, but I think looking at `/proc/sys/fs/file-max` is pretty standard. This may have been one of: (1) an image analysis and processing pipeline (converting file formats, rescaling intensities, etc., (2) an RNA-sequencing pipeline (sorting BAM files, working with FASTQs, etc), or (3) some sort of matrix algebra.

> e. WSL is not a / the Linux kernel, and does not have the notion of Linux kernel modules. WSL is a shim which presents a lot of a Linux kernel ABI to the outside world.

Got it, was just trying to see if it would fit a standard use case at work and came across this. 

Hopefully this sort of bug could be solved by pre-populating some of the `proc` buffers given whatever restrictions exist in the host NT kernel.

**Comment by xumo** [comment]
+1

**Comment by fdeutschow** [comment]
Any ETA for this? Also include fs.aio_max_nr please

**Comment by benhillis** [comment]
Fixed in 17723.

**Comment by therealkenc** [comment]
I guess `/proc/sys/fs/aio_max_nr` will have to be spawned as another issue.
