### ISSUE TITLE
Whether to provide an installation image with WSL  

### ISSUE THREAD

**Issue by zhenruyan** [Microsoft/WSL#2895]
Whether to provide an installation image with WSL
 It's very desirable to install it and use it in a network-free environment, which will be easier to deploy in a teaching environment

**Comment by Biswa96** [comment]
See #2616

**Comment by Biswa96** [comment]
@therealkenc you may close this thread as duplicate because OP has moved to the thread I've mentioned.

**Comment by therealkenc** [comment]
Thanks.
