### ISSUE TITLE
Nodes symlink creates file instead of directory

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/WSL#2898]
**Update**

This was previously reported as a Node-specific issue and an issue with directory names which contain a ".", but as it turned out it is more generic and can be reproduced by these steps:

```
$ cd /mnt/c/Users/foo
$ mkdir someotherdir
$ ln -s someotherdir someotherdirlnk # creates "Super Special™ WSL junctions" which are shown as files
```

**Below is the original issue**

This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

```
$ node -v
v9.4.0

$ node
>  require('fs').symlinkSync('/mnt/c/Users/foo/path-to-some-dir', '/mnt/c/Users/foo/foo.bar', 'file')
>  require('fs').symlinkSync('/mnt/c/Users/foo/path-to-some-dir', '/mnt/c/Users/foo/foo.bar2', 'dir')
>  require('fs').symlinkSync('/mnt/c/Users/foo/path-to-some-dir', '/mnt/c/Users/foo/foo.bar3', 'junction')
```

(Note: The third param is only for Windows and should not change Unbuntu behavior. This is true: It _always_ creates a file, but it should create three directories instead.)

* What's wrong / what should be happening instead:

Wrong: 
I have three files in `/mnt/c/Users/foo` all called `foo` with the file extensions `bar`, `bar2` and `bar3`.

What should happen:
I have three directories in ` /mnt/c/Users/foo/path-to-some-file` called `foo.bar`, `foo.bar2` and `foo.bar3`.
 
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

**TODO** for me.

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

--- 

First noticed while using `yarn`: https://github.com/yarnpkg/yarn/issues/5302

**Comment by therealkenc** [comment]
I tried your repro and it creates Windows junctions not files (regardless of third param, natch). This was on 17083, but I don't think anything changed since 16299. 

Simpler repro because you are going to find the `strace` just calling [symlink(2)](http://man7.org/linux/man-pages/man2/symlink.2.html).
```
$ mkdir /mnt/c/Users/you/somedir
$ ln -s /mnt/c/Users/you/somedir /mnt/c/Users/you/somedirlnk
```

The junctions are by-design. You are probably wanting #1475.

**Comment by donaldpipowitch** [comment]
Strange. It looks like even `ln -s` creates a file for me, not a junction:

```
$ mkdir /mnt/c/Users/you/somedir
$ ln -s /mnt/c/Users/you/somedir /mnt/c/Users/you/somedirlnk
``` 

> This was on 17083, but I don't think anything changed since 16299.

This comment (https://github.com/Microsoft/WSL/issues/1475#issuecomment-346443150) says "Windows Insider Build 17046 contains some improvements for symlink compatibility". Maybe I need this update. 🤔

**Comment by therealkenc** [comment]
Okay cool, it changed. But we're still looking at by-design (before and after), or dupe #1475 if you prefer, right?

**Comment by donaldpipowitch** [comment]
Hi again. I tested this now on the computer of a colleague which has the Insiders 17074 installed. When we run `$ mkdir foo && ln -s foo bar` there inside  `/mnt/c/Users/you` the `bar` is also shown as a file inside the file explorer.

![image](https://user-images.githubusercontent.com/1152805/35721965-bfe57ec8-07f4-11e8-887a-38bd3783b30f.png)

I'd expect the command to behave like (run inside `cmd.exe` - it looks like the arguments for `mklink` are in a switched order?): `>mklink /J C:\Users\you\bar C:\Users\you\foo`

![image](https://user-images.githubusercontent.com/1152805/35722209-aee6699c-07f5-11e8-8e67-26a8a84b53fb.png)

I don't know if this is a dupe of #1475, because I have to say that I don't really understand what #1475 is about. The title and description are quite hard to understand for me. Probably a mix of not being familiar with Windows, file systems and being a non-native speaker. Sorry. So I added the screenshots, which probably makes it a little bit easier to illustrate my problem.

**Comment by therealkenc** [comment]
It looks like that for me in Explorer too. Ben or Sven will have to confirm, but I believe it is a Super Special™ WSL junction, which is just confusing Explorer. If you look at the file with `dir` in `cmd.exe` it is reported as a `<JUNCTION>`.

One thing you might try is turning on [Developer Mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development) in you colleague's 17074. From the [release notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046) it will use ntfs symlinks and will show as type `.symlink` in explorer and `<SYMLINK>` in `cmd.exe`. But note you have to use relative paths, which precludes using `/mnt/c/...`. Or at least that's what I am finding. Ie:
```
cd /mnt/c/Users/foo
mkdir someotherdir
ln -s someotherdir someotherdirlnk
```

> I don't know if this is a dupe of #1475, because I have to say that I don't really understand what #1475 is about.

That's pretty fair assessment and it isn't your English 🙂. It was an open question.

**Comment by donaldpipowitch** [comment]
> which is just confusing Explorer

Is the by design or will this be fixed in the future? How should other applications handle this? E.g. VS Code can't see some of my packages, because `yarn link`/`npm link` (or just `yarn` in workspace based projects) create these "Super Special™ WSL junctions".

> One thing you might try is turning on Developer Mode in you colleague's 17074.

We'll try that. (But I think it was already enabled 🤔.)

Thank you for all the work and responses so far!

**Comment by therealkenc** [comment]
> Is the by design or will this be fixed in the future?

I suppose you could call it by design (but not ideal) in 16299, but "better" since 17046, because creating NTFS symlinks (contrast WSL junctions) is now supported. Whether it will be "even better" in the future I can't tell you, except to say no one closed #1475.

> We'll try that. (But I think it was already enabled 🤔.)

If you have Developer Mode enabled, you are probably seeing `<JUNCTION>` because you have a `/mnt/c/Users/foo` absolute path, not a `foo` path relative to a working directory. That threw me for a minute as well. This could be a problem if your absolute path came from deep down inside `yarn`, of course. There is more discussion in #353 starting [here](https://github.com/Microsoft/WSL/issues/353#issuecomment-340913146). Hopefully you can get a definitive answer from the team on how "`ln -s /mnt/c/Users/you/somedir /mnt/c/Users/you/somedirlnk`" should behave (by design or otherwise).

**Comment by donaldpipowitch** [comment]
It seems to work if you have a recent Insiders version _and_ developer mode activated. Thank you.

**Comment by MrBlenny** [comment]
Same for me - updated to **Windows 10 Insider Preview build 17074**  (from 16299) - now it works.

**Comment by mloskot** [comment]
AFAIU, the [developer mode is no longer required](https://blogs.msdn.microsoft.com/commandline/2017/06/08/developer-mode-no-longer-required-for-windows-subsystem-for-linux/).

Could anyone clarify what Windows build or WSL version do I need to get this 'symlinks situation' fixed?

**Comment by therealkenc** [comment]
> AFAIU, the developer mode is no longer required (since mid 2017)

Developer mode isn't required for WSL [anymore](https://blogs.msdn.microsoft.com/commandline/2017/06/08/developer-mode-no-longer-required-for-windows-subsystem-for-linux/). But it is (irritatingly) still required for [symlinks](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#V5Kprec3eaKlRosz.97) AFAIU.

Yes, confusing.

**Comment by mloskot** [comment]
@therealkenc Got it. Thanks!

**Comment by therealkenc** [comment]
> because it fires services occupying port 22 what is quite unhelpful

Yeah, there is also some pithy commentary on that [here](https://github.com/Microsoft/WSL/issues/2505#issuecomment-330063913) just for ref. Bonne chance.

**Comment by thsyd** [comment]
Try running as sudo. Seemed to work for me (running without sudo did not)
`sudo ln -s /mnt/c/XXXXX .`
(Where XXXXX is the rest of my directory structure)

Windows 10 Enterprise built 16999
WSL with Ubuntu 16.04

**Comment by MrBlenny** [comment]
Unfortunately this has started happening to me again. It was fixed for me on a different computer with an older version of Insider preview.

Now:
* Windows 10 Insider Preview build 17682.1000
* Node v8.11.2 (installed in WSL)
* npm v6.1.0 (installed in WSL)

Running `npm link` creates a symlink which appears as a file instead of folder. The link itself seems to work in the WSL world. Doesn't work in windows.

**Comment by snooopcatt** [comment]
same here, I have two machines, problem is on both:

* Windows 10 1803, node 8.9.4, Ubuntu
* Windows 10 1809, node 8.9.4, Ubuntu

running `ln -s /mnt/d/foo/bar /mnt/d/buz` produces link accessible with WSL but inaccessible in windows explorer

**Comment by concerned3rdparty** [comment]
Trying to create symlink under a different directory than pwd also not working. I'm in developer mode.

 `ln -sf ./test/build/ artifacts` works but these ones
 `ln -sf ./test/build/ ./randomdir/artifacts`,
`ln -sf ./test/build/ randomdir/artifacts` ,
`ln -sf ./test/build/ ../anotherrandomdir/artifacts` , 
don't work
