### ISSUE TITLE
Problem to install bin program on WSL

### ISSUE THREAD

**Issue by tiagogl** [Microsoft/WSL#2901]
Configuring the installer for this system's environment...

Launching installer...

failed to open </tmp/install.dir.30/Linux/resource/jre/jre/lib/amd64/default/libjvm.so> - reason: </tmp/install.dir.30/Linux/resource/jre/jre/lib/amd64/default/libjvm.so: cannot enable executable stack as shared object requires: Invalid argument>
Failed to find VM - aborting

I installed JVM , JDK and JRE. Tried install using root too. Anyone can help me?

**Comment by therealkenc** [comment]
That's #2553 ([message](https://github.com/Microsoft/WSL/issues/2553#issuecomment-335201548)) #286 and many friends. You can contact your `libjvm.so` vendor and see if they have any suggestions, or join the landing zone in #286 for general execstack discussion. Proposed work around for some packages has been:
```
$ apt install execstack 
$ execstack -s thing_you_ran  # you deleted the issue template and didn't say
```
