### ISSUE TITLE
singularity execution error

### ISSUE THREAD

**Issue by ct-clmsn** [Microsoft/WSL#2902]
2) Windows Version/build number

* Windows 10 CLI ver output

MS Windows [Version 10.10.15063]

* WSL "gcc --version" output

(Ubuntu5.4.1-2ubuntu~14.04) 5.4.1 20160904

* WSL "uname -a" output

Linux hostname 4.4.0-43-Microsoft \#1-Microsoft Wed Dec31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

3) Steps required to reproduce

 git clone https://github.com/singularityware/singularity.git
    cd singularity
    ./autogen.sh
    ./configure
    make
    sudo make install
    sudo singularity run shub://vsoch/singularity-images

4) Copy of terminal output

$ sudo singularity run shub://vsoch/singularity-images

Progress |===================================| 100.0%
ERROR  : Could not virtualize file system namespace: Function not implemented
ABORT  : Retval = 255

5) Expected behavior

The sun is shining, the weather is sweet...
You say please, but all I see is pizza..

6) Strace (running `strace -ff`)

https://gist.github.com/ct-clmsn/25761696b27a32e553b1577b2f30b7c1

7)

Attempted to run the [singularity container](https://github.com/singularityware/singularity) software. The software compiles successfully. But, has runtime execution errors - specifically running the [introductory tutorial](http://singularity.lbl.gov/singularity-tutorial).

8)

Detailed logs emailed to support

**Comment by therealkenc** [comment]
fail from your `strace` (appreciated) is:
```
unshare(CLONE_FS)                       = -1 ENOSYS (Function not implemented)
```
Which was implemented somewhere along the way per message [here](https://github.com/Microsoft/WSL/issues/2242#issuecomment-319516490), but I can't find a dupe issue# for it or an entry in the release notes. You are on 15063. Try FCU 16299 and you'll probably be alright; or at least get over that fail.

**Comment by ct-clmsn** [comment]
@therealkenc thanks for the quick turn-around! what's the best way to do that update/patch?

**Comment by benhillis** [comment]
Install Windows 10 Fall Creators Update.

**Comment by ct-clmsn** [comment]
@benhillis @therealkenc ran the update - got a new error. will submit a new issue and close this one.
