### ISSUE TITLE
Issue in executing bash commands over command prompt

### ISSUE THREAD

**Issue by Gowdakavya** [Microsoft/WSL#2903]
installed win-bash to my windows 7 operating system after all successful installation,but unable to execute any of the shell commands in command prompt
In command prompt screen displaying it as  C:/bash>
instead of bash $

I am beginner to this expecting help from all thanks in advance!!!!!!!!!!!!!!!!!!!!

**Comment by benhillis** [comment]
This GitHub is for Windows Subsystem for Linux which is only available in Windows 10 Anniversary update or newer versions. Winbash is a different product not created by Microsoft.
