### ISSUE TITLE
Is Hadoop Installation Possible?

### ISSUE THREAD

**Issue by gulshanmudgal** [Microsoft/WSL#2905]
Your Windows build number: Microsoft Windows [Version 10.0.16299.192]

can i use WSL to install single node Hadoop cluster?

**Comment by gulshanmudgal** [comment]
Any Solution for this?

**Comment by PastorGL** [comment]
Yes, that's possible but it is not as reliable as native and runs much slower. For local experimenting and development I'd rather recommend to deploy a dockerized HDP bundle from Hortonworks.
