### ISSUE TITLE
SSE4A support

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#2906]
Just a heads-up: similar to [the missing AVX2 support](https://github.com/Microsoft/WSL/issues/2234), WSL under Windows 10 on a PC with SSE4A support does not list `sse4a` under `/proc/cpuinfo`

**Comment by therealkenc** [comment]
[this](https://github.com/Microsoft/WSL/issues/2234#issuecomment-331954892)

**Comment by mqudsi** [comment]
I'm not sure why you're linking to that particular comment? I had already seen that discussion (and linked to it in my post). As I said, just a heads-up so it's on someone's to-do list. Not a major issue at all. No breakage as a result.

**Comment by therealkenc** [comment]
Because I wanted to give the issue a chance to follow posting guidelines before duping; it was benefit of the doubt. Heads up appreciated. There is no need to give a heads up on say `3dnowprefetch`. #2234
