### ISSUE TITLE
Tmux new-window -c not starting in new dir

### ISSUE THREAD

**Issue by johnny88** [Microsoft/WSL#2907]
**Behavior**

Calling the command `tmux new-window -c <some path>` creates a new window in the home directory.

**Expected Behavior**

Calling the command `tmux new-window -c <some path>` creates a new window in the <some path> directory.

**Note:** This also seems to effect split window.

Running Windows 10 Pro Insider Preview Version 1709 OS build 17074.1002
WSL 20170830.1 build of Ubuntu 16.04 LTS
Tmux version: 2.1

Any help with this issue would be greatly appreciated. I am really enjoying WSL, you all are doing a great job!

Oh and also let me know if you need any further information.

**Comment by Brian-Perkins** [comment]
I tried this on a recent build and it seems to work OK. Are you able to try a newer Insider Build (i.e. 17083 or newer) and confirm?

**Comment by johnny88** [comment]
Yeah I can try that and let you know.

**Comment by johnny88** [comment]
So I tried a fresh install and it seemed to work fine, not sure if it's the fresh ubuntu install or something about my tmux conf. Sorry about that and thanks for your time!
