### ISSUE TITLE
need some improvement on changelogs and docs

### ISSUE THREAD

**Issue by jeffguorg** [Microsoft/WSL#2908]
Hey dudes,

it's a doc issue.

I'm using 17074 and WSL when having a need to debug my scripts, and i'm using RoliSoft's WSL-Distribution-Switcher to add a diy Linux image. But there is a problem that i found %LOCALAPPDATA%\lxss is absent after i added the wsl feature and installed ubuntu. 

so...i think we need detailed and more readable changelogs to know what changed and when, to improve support for these features even if they are still in development

thanx for your work!

**Comment by Biswa96** [comment]
Did you install Ubuntu with `LxRun.exe` or from Windows Store?

**Comment by jeffguorg** [comment]
@Biswa96 
Yes, I have lxrun and that is not the problem.

The problem is that I'm not sure which to use,  %LOCALAPPDATA%\lxss or other location, and from which version this change took place. so I can't improve my script to intelligently determine where to find or place the binary and data.

**Comment by HSuke** [comment]
I'm using the Windows Store version of Ubuntu. Same problem.

"%LOCALAPPDATA%\lxss" doesn't exist. It's not a hidden or system folder either. On the Linux side, I can use /mnt/c/ to access the Windows folders, but it would be good to know how to do the opposite.

**Comment by Biswa96** [comment]
LxRun.exe is now deprecated. Move on to the new Windows Store distributions.
BTW, @benhillis Why there there are some "Legacy" registries left over in LxssManager.dll?

**Comment by jeffguorg** [comment]
so, what replaced %LOCALAPPDATA%\lxss in the new windows store distros

**Comment by Biswa96** [comment]
The new installation path is C:\WindowsApps\DistroName and the distribution installed in AppData\Local\DistroName.
