### ISSUE TITLE
Win32 executable launched via NTFS symlink doesn't respect symlink name

### ISSUE THREAD

**Issue by awson** [Microsoft/WSL#2909]
Windows build 10.0.16299.214.

Let's we have some native win32 executable named `foo.exe` built from the following C code:
```
int main(int argc, char * argv[]){
  puts(argv[0]);
  return 0;
}
```
Let's we also have an NTFS symlink `bar.exe` pointing to this `foo.exe`.

CMD shell:
```
C:\test>bar.exe
bar.exe
```

WSL bash:
```
baz@qux:/mnt/c/test$ ./bar.exe
C:\test\foo.exe
```

**Comment by SvenGroot** [comment]
I suspect this is because WSL's path resolution follows the symlink, so what we end up passing to CreateProcess is the symlink's target and not the symlink itself. Likely we could be smarter about this. Thanks for reporting!

**Comment by benhillis** [comment]
Thanks for opening, drafting a fix for this now.
