### ISSUE TITLE
Trouble launching a WSL / Ubuntu driven task using the Windows Task Scheduler

### ISSUE THREAD

**Issue by nickjj** [microsoft/WSL#2912]
While creating an automated backup solution for myself I ran across a couple of interesting issues when calling out to WSL tasks using the Windows Task Scheduler and I haven't been able to solve them all.

The main problem is that WSL tasks will not run unless you specifically set "Run only when user is logged in", however this constraint is unreasonable because let's say you want a task to run at 3am, but you have a lock screen come on after 30 minutes of inactivity. Now you're considered logged out, so it won't run.

To combat that, MS has a task option "Run whether user is logged on or not", and then it saves your password along with the task. However, when this is enabled, WSL driven tasks fail with exit code 2 which is "the system cannot find the file".

My task's action is: `C:\Users\Nick\AppData\Local\Microsoft\WindowsApps\ubuntu.exe`
My task's arguments are: `run ~/src/scripts/backup`

The path to `ubuntu.exe` exists and the task works correctly when I set the task to run when logged in but the same task fails when it is set to run without the user being logged in. It even fails if I'm logged in and manually run the task with the "Run whether user is logged on or not" option enabled but works as soon as I switch to "Run only when user is logged in" and re-run the task.

Using `bash.exe` and setting `-c ...` doesn't work because then environment variables such as `$HOME` get resolved to the Windows version instead of WSL inside of the script.

Any ideas on how to get around this? Thanks.

I'm using Windows 10 Pro (1709), build 16299.125.

**Comment by benhillis** [comment]
@nickjj - $HOME will always be your user's home directory.  However the current working directory will be a Windows (DrvFs) path.  I suspect your script is using relative paths.

You can use wsl.exe ~ or bash.exe ~ to launch a command in your user's home directory.

**Comment by nickjj** [comment]
My script uses $HOME as the start of the path for some of my WSL paths (such as dotfiles and folders) and everything else is absolute paths.

**Comment by benhillis** [comment]
I think I'm confused in what you're reporting.  Are you saying ubuntu.exe doesn't work but bash.exe or wsl.exe works but the $HOME variable is wrong?

**Comment by nickjj** [comment]
The main issue is that the Windows task scheduler seems to have issues trying to run a WSL driven task when the user is not logged in.

Let's ignore the ubuntu.exe vs bash.exe differences for now.
