### ISSUE TITLE
apt-get install and zypper install can't connect 

### ISSUE THREAD

**Issue by JohnGriffiths** [Microsoft/WSL#2914]
Hi. 

I've been wrestling with this problem for a while and have tried multiple solutions suggested in similar posts, but none fix the problem in my case. So am asking directly:

I have just installed ubuntu bash for windows, and am having trouble with accessing sources for package installation. Example:

```
sudo apt-get install gcc
...
...
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libmpc3 amd64 1.0.3-1
  Connection failed [IP: 91.189.88.162 80]
```

Additional notes: 

- Windows Version	10.0.16299 Build 16299
- Installed using app store rather than lxsrun
- No antivirus running. Just windows defender. 
- `ping www.google.com` gives result; but `ping http://archive.ubuntu.com` gives `unknown host` error
- Installed opensuse also through app store and have save problem: `sudo zypper install gcc` gives `Error message: empty reply from server`

Please help!

Thanks,

john

**Comment by Brian-Perkins** [comment]
Often you need to refresh the list of servers via 'sudo apt update'. Try that and see if you have better luck.

**Comment by therealkenc** [comment]
Stale on repro.
