### ISSUE TITLE
[BUG]reboot doesn't turn on the WSL feature

### ISSUE THREAD

**Issue by DanielWLam** [microsoft/WSL#2916]
I follow the instruction to try to turn on the WSL, however, no matter how many times I reboot my computer. The WSL just dont turn on.
Here is some information of my PC:
![image](https://user-images.githubusercontent.com/8369212/35788569-ed59f270-0a70-11e8-9789-9ce7edf442d9.png)

![image](https://user-images.githubusercontent.com/8369212/35788562-e1946e52-0a70-11e8-8d9f-eea7644762a4.png)

**Comment by Biswa96** [comment]
Try to enable that feature with Command prompt or Powershell. See this article:
https://docs.microsoft.com/en-in/windows/wsl/install-on-server

**Comment by DanielWLam** [comment]
Well, I've  already try on command line on the first time. However, it didn't work either.

**Comment by benhillis** [comment]
Will you double check that your trustedinstaller service is set to autostart?

**Comment by DanielWLam** [comment]
@benhillis Hi, I try to set trustedinstaller to auto, however, everytime I reboot the computer, it will be automaticly set to mannual  
![image](https://user-images.githubusercontent.com/8369212/36060934-c1d29be0-0e8d-11e8-82c5-2f30ac416704.png)
