### ISSUE TITLE
Error `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)` Failed

### ISSUE THREAD

**Issue by mingl0280** [Microsoft/WSL#2918]
* Your Windows build number: 10.0.16299.214

* What you're doing and what's happening:  
```
root@PC-MING:~/WinLinks/M/tmp/sshdiag# strace -ff -v -o sshdiag -r service ssh --full-restart
 * Stopping OpenBSD Secure Shell server sshd                                                                              [ OK ]
 * Starting OpenBSD Secure Shell server sshd                                                                                     
sshd: ../sysdeps/posix/getaddrinfo.c:2555: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
                                                                                                                          [fail]
```
* What's wrong / what should be happening instead: sshd service could not be started.

* Strace of the failing command, if applicable: 
https://gist.github.com/mingl0280/a728b9d18d634cfe00b985eee5ff4198

This also happens to other packages such as apt while downloading a new package, or apache2 while starting the service. 

I've already read issues such as #2142 but with no luck, and I can also rule out the impact from antivirus software or IPv6 since the IPv6/Anti-Virus was enabled and the whole system was running without any problem before this issue happens. 

Here's a copy of my ifconfig:
eth0      Link encap:Ethernet  HWaddr f8:32:e4:be:cf:ef
          inet addr:192.168.1.199  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: 2601:8c0:4280:48c4:8dd0:51d0:27a6:8f1a/64 Scope:Global
          inet6 addr: 2601:8c0:4280:48c4:357f:cc33:5002:7fe1/128 Scope:Global
          inet6 addr: fe80::8dd0:51d0:27a6:8f1a/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Global
          UP LOOPBACK RUNNING  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by therealkenc** [comment]
#508 has been the de-facto landing zone for `Error IN6_IS_ADDR_V4MAPPED`, but it is closed. The remaining open one (by pure chance) is #2918. Duping there.
