### ISSUE TITLE
Passing a number >1024 as nfds to a select call causes EINVAL

### ISSUE THREAD

**Issue by Muzer** [Microsoft/WSL#2919]
According to the Linux manpage:

           EINVAL nfds  is negative or the value contained within timeout is invalid.

...and according to a POSIX manpage I found, EINVAL should be returned in this case, or if EINVAL exceeds RLIMIT_NOFILE (which appears to be set to 2048 - I'm not sure whether that's a property of my distro or a property of WSL).

However, select returns EINVAL if a value above 1024 is passed for nfds. I am trying to use a proprietary library which appears to be doing this (it's passing the value of RLIMIT_NOFILE), but I have a simple example here:

    #include <stdio.h>
    #include <sys/resource.h>
    #include <sys/select.h>
    #include <unistd.h>

    int main()
    {
        fd_set read_fds;
        FD_ZERO(&read_fds);
        FD_SET(STDIN_FILENO, &read_fds);

        struct rlimit foo;
        getrlimit(RLIMIT_NOFILE, &foo);

        printf("%i %i %i", foo.rlim_cur, foo.rlim_max, select(1025, &read_fds, NULL, NULL, NULL));
        perror("SELECT!");
    }

Run this and then press enter. On my WSL system, foo.rlim_cur and foo.rlim_max both come out as 2048. Tweak the values of the first argument to select() to see success when it's 1024 and failure when it's 1025.

I don't know whether the bug here is in select() or in the default RLIMIT_NOFILE being too high compared to what WSL can actually cope with.

**Comment by benhillis** [comment]
Please fill out the issue template, what build are you running?

**Comment by Muzer** [comment]
Apologies, I somehow missed that.

Windows build: 10.0.15063

**Comment by therealkenc** [comment]
Can't repro here on 17083. I get:
```
1024 65536 1
SELECT!: Success
```
That is, my `rlim_cur` is 1024. It starts to fail at `select(1030, ...)`.

Real Linux does behave a little different though. On Linux `rlim_cur` is 1024 and `rlim_max` is 4096, but even `select(8192, ...)` succeeds.

**Comment by Muzer** [comment]
OK, it's potentially already been fixed which is good, if so! What happens if you use `ulimit -n` to up rlim_cur?

**Comment by therealkenc** [comment]
The value appears to take, but doesn't appear to be respected. This is with `select(2048, ....)`:
```
ken@DESKTOP-4UTIQSF:~/Devel/rlimit$ gcc -w rlimit.c
ken@DESKTOP-4UTIQSF:~/Devel/rlimit$ prlimit --nofile=8192 ./a.out
8192 8192 -1
SELECT!: Bad file descriptor
```
Not really applicable on Real Linux because `select(2048, ....)` doesn't return an error in the first place regardless of `rlim_cur`.

**Comment by therealkenc** [comment]
Calling this fixedin1803 per tests performed [back](https://github.com/Microsoft/WSL/issues/2919#issuecomment-363561061) in February. 

There is still a gap here: On Real Linux `select` succeeds regardless of `rlimit_cur`. Someone highly motivated could wrap my previous post into a new issue, as not to conflate with the OP test case, which succeeds. But absent some real world failure condition triggered by the difference it is pretty academic.
