### ISSUE TITLE
Windows Defender Usage keeps high when a tmux theme is used

### ISSUE THREAD

**Issue by MichaelTong** [microsoft/WSL#2920]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.214]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Running tmux with a customized theme, Windows Defender keeps very high CPU usage all the time(See screenshot).
If tmux exits or use tmux without a theme, it will be fine.
![capture](https://user-images.githubusercontent.com/3312753/35883878-6f05cc58-0b4e-11e8-9144-52ae1ac7f4a2.PNG)

tmux version: 2.1
tmux theme repo: https://github.com/gpakosz/.tmux

* What's wrong / what should be happening instead:
like normal windows file usage, Windows Defender shouldn't keep scanning those files.

**Comment by MTNTheCompWiz** [comment]
I'm seeing the same thing.  I also would like more info.  I'm using tmux 2.7.

**Comment by robertorussobob** [comment]
I'm experiencing the same issue.
Having tmux running triggers a periodic MsMpEng.exe spike about every 10 seconds:

![image](https://user-images.githubusercontent.com/29973889/43090075-abbc7bde-8ea6-11e8-910b-f18b7b805f8e.png)
