### ISSUE TITLE
Script function to record bash sessions not working on version 16.04

### ISSUE THREAD

**Issue by D0radus** [Microsoft/WSL#2921]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.214]
Bash version: 16.04.2

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

When trying to run the 'script' command to make a typescript to record the bash session I get the error, "script: cannot set signal handler: Function not implemented". Then you cannot see what you type and the only way to exit is to type 'exit', which ends up closing the bash session. (see: https://imgur.com/a/230mT).

* What's wrong / what should be happening instead:

What should happen when typing script is that it should say "Script started, file is 'whatever file you named it'. Then the bash terminal should operate like normal until the user types 'exit' (note that the terminal should not close). At this point whatever was recorded in the terminal is put into a text file and the user may use the bash terminal like normal. Also I believe in the previous bash version 14.04 the script function worked fine.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
N/A

**Comment by therealkenc** [comment]
#2053 #129 

> Strace of the failing command, if applicable
> N/A

_Really???_
