### ISSUE TITLE
apache2 server under wsl can't be accessed from the web

### ISSUE THREAD

**Issue by nickweavers** [Microsoft/WSL#2923]
* Your Windows build number:  Version 10.0.17074.1002

* What you're doing and what's happening:  Trying to allow my wsl apache2 server to be accessed from the web

* What's wrong / what should be happening instead: The webbsite is configured via apache vhost and I can access it locally by using the host file to resolve the registered domain name to my local servers IP address, but when I try to check the server is accessible using http://downforeveryoneorjustme.com it reports that it is not up for anyone. The web server is set up in the vhosts file to use port 80  as follows:

 Listen 80
<VirtualHost *:80>
        ServerName nhw.foobar.co.uk
        ServerAdmin webmaster@localhost
        # NB: The DocumentRoot path name needs quoutes around it, whilst the Directory
        # path doesn't
        DocumentRoot "/mnt/i/var/www/vhosts/dev.foobar.co.uk/httpdocs"
        <Directory /mnt/i/var/www/vhosts/dev.foobar.co.uk/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

The site has been enabled (a2ensite) and the apache2 service has been restarted.

I have a Windows Defender firewall rule set up for incoming on port 80

I have set up a port forwarding rule on my netgear router to forward incoming traffic on port 80 to my local machine at 10.0.0.100 that is has apache listening on port 80.

If I create a record in the windows host file for the registered domain name and ip 10.0.0.100 the server is accessible from my PC, so I know the apache config is good and the site works.

**Comment by nickweavers** [comment]
If I turn off the Windows Defender Firewall for Guest or public networks, the website can be reached from the web. However, I already have the incoming rile defined to allow the port be be opened for incoming TCP/IP traffic. 
I'll try a a reboot of my PC to make sure the incoming rule is in force.

**Comment by nickweavers** [comment]
A reboot didn't help... so how do I open up the Firewall for WSL's Apache2 server?

Here's the incoming rule I defined:

![image](https://user-images.githubusercontent.com/194136/35927725-4f5d51ac-0c23-11e8-8497-d33aa9ce6015.png)

Can anyone advise?

**Comment by xama5** [comment]
You need to open the outgoing port too.

**Comment by nickweavers** [comment]
Sadly @xama5 it made no difference:
![image](https://user-images.githubusercontent.com/194136/35930378-a5b6b600-0c29-11e8-958b-1272c3c98113.png)

**Comment by Brian-Perkins** [comment]
Your rule is currently restricting the remote port to 80 as well. Try changing this to 'Any'.

**Comment by nickweavers** [comment]
Thanks for the suggestion Brain, but this also made no difference:
![image](https://user-images.githubusercontent.com/194136/35935272-e0f15b9a-0c37-11e8-8c84-a2dc09d9c48e.png)

**Comment by Brian-Perkins** [comment]
@nickweavers Sorry, I was referring to your original inbound rule.

**Comment by nickweavers** [comment]
I do actually only want to open up port 80 in both directions since It's just for http traffic , but I tried your suggestion of relaxing it to any ports both incoming and outgoing Brian. It made no difference. Thanks for the suggestion though.

**Comment by therealkenc** [comment]
Correction just so it is on the books; you don't need to open the "outgoing port too" as suggested. Nothing is outgoing port 80 here. Which is probably why Brian took as given he meant the incoming rule. The problem is you restricted the remote port (the one Chrome or Firefox or Edge got) on the incoming connections to port 80.

**Comment by nickweavers** [comment]
Thanks @therealkenc, I thought that too, but am willing to try anything in a quest for an answer. So are you saying by restricting the remote incoming port to 80, if I was visiting a website with an SSL certificate that expects to use 443 I would have blocked it? I had the idea that a state-full firewall would only block unsolicited packets coming in, so anything coming back to my browser as a response would be allowed through despite what a rule says, since I effectively sanctioned it by making a request - something reflected in the packets state? I'm not much of an expert though.

**Comment by therealkenc** [comment]
We're treading way out of WSL territory here, but if you are using `https` then you need to open incoming _local port_ 443. And do some other stuff. The _remote port_ needs to be Any regardless, except under special circumstances which wouldn't apply to you. There isn't any "despite what the rule says" -- there are incoming ports, and there are outgoing ports. You have an incoming port. I don't know what else to tell you other than I assure you [it works](http://172.103.230.15). If it didn't then people's heads would explode.

![firewallports](https://user-images.githubusercontent.com/7049700/35939377-d14cc922-0c00-11e8-8406-0593980c6665.png)

**Comment by nickweavers** [comment]
I believe that it works in 99.9999% of cases. I'm just trying to understand why it doesn't in the case I have here with an apache web server running under wsl and if it's my fault (misconfigurartion) which is most likely. 

So here's where I'm at:

1) **With the Windows Defender Firewall for Guest or public networks turned OFF**, the website **CAN** be reached from the web.

2) With **incoming rules defined for HTTP and HTTPS** and  **Windows Defender Firewall for Guest or public networks** turned **ON**, the  site and **CANNOT** be reached from the web.

![image](https://user-images.githubusercontent.com/194136/35965633-6fe26a08-0cb3-11e8-9840-d560d5d1df8d.png)

**Comment by nickweavers** [comment]
My bad, it is now working... just forgot to restart apache after reboot. Doh!

Thanks to @therealkenc and everyone else for helping out.
