### ISSUE TITLE
'mv' and 'cp' won't move/copy files prefixed with a dot ('.')

### ISSUE THREAD

**Issue by xama5** [Microsoft/WSL#2924]
# Windows build number

Microsoft Windows [Version 10.0.16299.192]

# What you're doing and what's happening

## Example 1 (unprefixed and prefixed)

```
cd
mkdir -p test
touch ./test/.foo
touch ./test/bar
mv ./test/* ./
```

This will only move `bar` to the current directory, but not '.foo'.

## Example 2 (prefixed)

```
cd
mkdir -p test
touch ./test/.foo
mv ./test/* ./
```

The 'mv' command produces the following error:

> mv: cannot stat './test/*': No such file or directory

# What's wrong / what should be happening instead:

Files prefixed with a dot ('.') should be moved.

'mv' as well as 'cp' fail with the same behaviour.

# Strace

This is the strace for: `strace -o mv.strace -f mv ./test/* ./` (taken from the **second** example, the first example does not throw an error)

https://gist.github.com/xama5/c710190db4214274a28902524c91630c

**Comment by therealkenc** [comment]
```
$ echo .test/*
./test/*
```
Asterisk (`*`) is not a file in your `./test/` directory, so the move fails. Though, a file named `*` could be in that directory. This is glob expansion behaviour. There is more about it on the [Interwebs](https://askubuntu.com/questions/259383/how-can-i-get-mv-or-the-wildcard-to-move-hidden-files). Please use those resources when you can.
