### ISSUE TITLE
Restart WSL instance

### ISSUE THREAD

**Issue by parkovski** [Microsoft/WSL#2928]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17074.1002

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
After running `do-release-upgrade`, the installer attempts to reboot the "system" (WSL instance). Now that daemons are supported, `init` and several other processes are still running after closing my WSL windows, and they are not killable through task manager or PowerShell, at least as far as I could tell.

* What's wrong / what should be happening instead:
The reboot syscall should restart `init`, and I'd personally like to see a `/reboot` option for `wslconfig.exe` as a virtual "hold down the power button".

**Comment by benhillis** [comment]
WSL processes should definitely be killable through task manager or powershell, if they are not it' bug.  Our implementation of the reboot syscall *does* terminate the instance, however I think they problem you are running into is the reboot command attempts to talk to the init daemon to issue the reboot which isn't running.  If you write a binary that calls the syscall directly (and with the correct arguments, cheeky Linus) it should work.

If you want a heavy hammer you can stop the LxssManager service to stop the instance.  Note that will terminate all running instances on the machine.

You do raise a valid point that there should be a better way to terminate a specific instance.  I'll add that to our backlog.

**Comment by parkovski** [comment]
Hmm, even with an admin PowerShell window I'm getting an access denied error trying to kill init. I tried `kill -n init` and `kill -id (init's pid)`.

I misunderstood about the syscall. Is there any chance of getting a reboot binary that works?

**Comment by parkovski** [comment]
Sorry for the confusion. It did eventually terminate and it restarts fine now.

**Comment by benhillis** [comment]
Dug into this and found an issue that would prevent init from being killed in a timely manner.  Working on a fix now.

**Comment by Brian-Perkins** [comment]
This should be resolved in Insider Build [17110](https://github.com/MicrosoftDocs/WSL/releases/tag/17110).
