### ISSUE TITLE
kernel headers

### ISSUE THREAD

**Issue by keystroke33** [Microsoft/WSL#2932]
I have installed Kali Linux in WSL. Some of the tools, like aircrack-ng require that I have the a wifi card installed. Here are some results of commands:
iwconfig 
eth0      no wireless extensions.
eth1      no wireless extensions.
lo        no wireless extensions.
wifi0     no wireless extensions.                               
wifi1     no wireless extensions.

ip a
DONE truncated
Dump terminated

lspci
pcilib: cannot open /proc/bus/pci
lspci:cannot find working access method

Ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x0<global>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wifi0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.6  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::7884:c9f8:373b:37c9  prefixlen 64  scopeid 0x0<global>
        unspec C8-3D-D4-EC-A2-6F-00-00-00-00-00-00-00-00-00-00  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

airmon-ng start wifi0
ls: cannot access '/sys/class/ieee80211/': No such file or directory.
How do I get past this?

**Comment by therealkenc** [comment]
Same as #1104 #2598, #1077 ([message](https://github.com/Microsoft/WSL/issues/1077#issuecomment-296085572)), plus #1349 and friends. There is no raw access to AF_PACKET, let alone the underlying WiFi hardware on WSL.

The first fail is missing `/proc` and `/sys` entries, which I would sure like to see stubbed for unrelated reasons. But stubbing them won't help the `aircrack-ng` ask. It would just make it fail more gracefully (along with many other things).

You can up-vote the UserVoice entries [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) and [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/17268656-add-wireless-device-support).
