### ISSUE TITLE
Please fix default colors. They are hard to work with.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/WSL#2934]
![powershell-hard-to-read](https://user-images.githubusercontent.com/297678/36077425-8e649438-0f1f-11e8-8b79-8fb000462cb3.PNG)

That's the default color, in PowerShell. Can you please just fix the color to make it readable by default?

**Comment by trusktr** [comment]
The output of `ls` is all green too, which is horrible. Please, do a little UX on WSL.

**Comment by Biswa96** [comment]
You may change the background colour in powerhsell settings? Or try command prompt for black background?

**Comment by trusktr** [comment]
Yeah, I know I can change the colors, but some good defaults would be nice out of the box, for both CMD and PowerShell. Even in CMD that dark blue is low contrast with the black background.

**Comment by therealkenc** [comment]
#2515 #81
