### ISSUE TITLE
Possible to use NTFS-3G on /mnt/d/ ?

### ISSUE THREAD

**Issue by trusktr** [Microsoft/WSL#2935]
I put stuff on `D:` (an NTFS partition), because it's bigger, to keep Windows `C:` just for the OS. But when I access `/mnt/d` in Bash, all files are green (basically all `777` permissions).

Is it possible to fix this with ntfs-3g, or some other way? What is recommended?

**Comment by Biswa96** [comment]
Doesn't the `777` mean it has execute permission? Did you try chmod +x ?

**Comment by therealkenc** [comment]
> Possible to use NTFS-3G on /mnt/d/ 

No. Setting aside that the files are green on ntfs-3g as well because the exec bit is set and that is the default. 

You can change the mode of file/directories in DrvFs as of Insider 17063. You can customise the colors GNU `ls`uses with the `$LS_COLORS` environment.

**Comment by trusktr** [comment]
Updated my OP to say that `D:` is an NTFS partition, and that I just started using WSL, and I'm accessing files on `D:`, which are all 777/green and owned by root:root. `chmod`/`chown` doesn't do anything; I'd like for them to work. Can I do that by configuring ntfs-3g from inside WSL? I'm just trying to understand what path to take to make permissions/ownership work like in Linux.

**Comment by DarthSpock** [comment]
Use wsl.conf that comes with 17093 to enable fstab and metadata attributes on mounts (or do this manually if you prefer, metadata doesn't require 17093 but you would need to be on the Slow-Ring at least.) 

> Can I do that by configuring ntfs-3g from inside WSL? 

Short answer is no.

Longer answer is Windows doesn't support FUSE therefore trying to use NTFS-3G on Windows directories will fail. It's not the only thing affected by lack of FUSE. See the Uservoice page and add your vote (not that it seems to be getting any acknowledgement by MS).

**Comment by therealkenc** [comment]
> chmod/chown doesn't do anything; I'd like for them to work

That is #81.

> Longer answer is Windows doesn't support FUSE 

Well that's a thread killer right there. List stuff would be green even if you had ntfs-3g.

[With a nod to Godwin] Ken's Law: As a WSL discussion grows longer, the probability of a commenter mentioning FUSE approaches 1.

**Comment by DarthSpock** [comment]
We've had prior discussion about NTFS-3G and Fuse. So I gave the summed up version of what he asked about using ntfs-3g. The list stuff was the obvious part. Plus I short answered his headline "Possible to use NTFS-3G on /mnt/d/ ?"

**Comment by trusktr** [comment]
Alright, maybe I asked the wrong question. New one: how do I get around the problem that C drive is not so big, just for Windows, and I was to keep all my Linux content on the Doors: NTFS drive? Is there a way to move lxss to D: to take advantage of that huge partition?

**Comment by trusktr** [comment]
That autocorrect isn't smart enough. I meant, I _want to keep_ all my content on the big _D: NTFS drive_.

**Comment by benhillis** [comment]
@trusktr - we're working on this.  Some of the store infrastructure doesn't play nicely case-sensitivity and our Linux metadata.  We're working with them to get the issues fixed so you will be able to install distributions on your non-system drives.

**Comment by DarthSpock** [comment]
I believe this should be getting tracked in #449 Great to hear some update about this though!

**Comment by trusktr** [comment]
Looks like quickest solution may be to move my entire user folder to D:

**Comment by DarthSpock** [comment]
Actually that won't change the dependency for system drive to install Ubuntu or OpenSuse. Has to be the drive you boot from currently. Not endorsing but you may find [WSL-Distribution-Switcher](https://github.com/RoliSoft/WSL-Distribution-Switcher) to be what you're looking for as a workaround.
