### ISSUE TITLE
Installing sbt

### ISSUE THREAD

**Issue by Starofall** [Microsoft/WSL#294]
While installing SBT I get the following error.
It also happened to non BashOnWindows users but might be reproduceable.

```
Getting org.scala-sbt sbt 0.13.11 ...
[thread 140694536718080 also had an error]#

# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:308), pid=2961, tid=140694473082624
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: /root/sbt/bin/core or core.2961
#
# An error report file with more information is saved as:
# /root/sbt/bin/hs_err_pid2961.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
/root/sbt/bin/sbt-launch-lib.bash: line 41:  2961 Aborted                 (core dumped) "$@"
```

**Comment by rs6g10** [comment]
I could go a bit further but it hangs out at this:
![image](https://cloud.githubusercontent.com/assets/1889234/15058986/8c006d4e-1317-11e6-9129-75269dadddf3.png)

**Comment by sundhaug92** [comment]
Tried to strace it?

**Comment by Starofall** [comment]
It still stucks with this strace:

```
stat("/usr/bin/java", {st_mode=S_IFREG|0755, st_size=7734, ...}) = 0
geteuid()                               = 0
getegid()                               = 0
getuid()                                = 0
getgid()                                = 0
access("/usr/bin/java", R_OK)           = 0
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [INT CHLD], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT CHLD], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6c62bf0a10) = 832
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {0x4438a0, [], SA_RESTORER, 0x7f6c62026cb0}, {SIG_DFL, [], SA_RESTORER, 0x7f6c62026cb0}, 8) = 0
wait4(-1, Getting org.scala-sbt sbt 0.13.11 ...
```

**Comment by funky81** [comment]
Hi Guys, anyone that successfuly install sbt within bash for Windows?
I've got this kind of error

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:318), pid=1365, tid=140473298388736
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: Java(TM) SE Runtime Environment (7.0_80-b15) (build 1.7.0_80-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b11 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: /root/spark/spark-1.6.2/core or core.1365
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by glenstarchman** [comment]
Copying over your `~/.ivy2` directory from a working installation works, with the caveat that `sbt` just hangs after it completes and you need to `ctrl-z` the process and then kill it. Another issue is that is makes sbt on a linux platform look like a speed demon... I am seeing sbt running on BoW running 20-25x slower.

**Comment by glenstarchman** [comment]
And strike that...  it suddenly stopped working.

**Comment by SRGOM** [comment]
@glenstarchman Did it manage to ever resolve a dependency for you? Or did it need everything to be available in the .ivy directory beforehand?

**Comment by SRGOM** [comment]
Fix incoming here: https://github.com/Microsoft/BashOnWindows/issues/813

**Comment by jackchammons** [comment]
@all Significant fixes have been made to support additional JRE scenarios. Are people still seeing problems with JBT on recent Insider builds?

**Comment by therealkenc** [comment]
Died in need-repro state. If there are remaining fails with `sbt` please re-file following the issue template.
