### ISSUE TITLE
Please negotiate with canonical to add dos2unix into Ubuntu

### ISSUE THREAD

**Issue by benqzq** [Microsoft/WSL#2942]
Please negotiate with canonical to add `dos2unix` into Ubuntu

[Adding it should improve comfortability](https://github.com/Microsoft/WSL/issues/2939#issuecomment-365170942).

**Comment by therealkenc** [comment]
It already is. [Here](https://packages.ubuntu.com/xenial/dos2unix).

**Comment by benqzq** [comment]
I just created a new Ubuntu server 16.04.3 (xenial) VPS machine in DigitalOcean, executed `dos2unix` and got:

```
The program 'dos2unix' is currently not installed. You can install it by typing:
apt install dos2unix
```

I cannot explain that. A problem unique to DigitalOcean? I don't believe...

![1](https://user-images.githubusercontent.com/31392185/36164496-2ac7baa4-10f5-11e8-994f-79783c8e49de.PNG)

Please re-open.
