### ISSUE TITLE
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.

### ISSUE THREAD

**Issue by windrunner414** [Microsoft/WSL#2943]
Windows build 17093.
I try to run vscode and it prints:
`Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.`
And I install archlinux in WSL,vscode is work.
But i met another trouble:
 i install latte-dock or plasma and run it,it say libQt5Core.so.5 not found but I can find it in /usr/lib

**Comment by windrunner414** [comment]
It's strange that archlinux can run normally but Ubuntu can't

**Comment by windrunner414** [comment]
I upgrade to ubuntu 17.10 and it can run vscode...... why ubuntu 16.04 can't?

**Comment by windrunner414** [comment]
now i can run vscode successfully.
i only reinstall wsl...

**Comment by therealkenc** [comment]
#2819 #2760 ([message](https://github.com/Microsoft/WSL/issues/2760#issuecomment-356062135)) #1006 #648
