### ISSUE TITLE
Copying multi-line text and pasting to a file puts all text onto single line

### ISSUE THREAD

**Issue by DeeToTheVee** [Microsoft/WSL#2945]
**Your Windows build number**: 
     Microsoft Windows [Version 10.0.16299.192]

**What you're doing and what's happening:**  
     When copying a few lines from the centre of a file with Ctrl + Shift + C I'm getting multi-line text put onto a single line.

So in my scenario:
  1. I ssh'd onto a Linux server using the bash for windows terminal.
  2. I'd cat or vim, in this case, a JSON file as there are 6-7 lines I need from the centre of the file.
  3. I then highlight and copy the lines I need with the mouse and Ctrl +Shift + S
  4. I paste it into a file (middle mouse click as Ctrl + Shift + V does not work in insert mode in vim when using WSL)

The issue is that it puts all the multi-line text onto one single line separated by large amounts of white-space rather than discovering the line endings and breaking as required.

This is obviously not expected behaviour and appears to have something to do with the Windows line endings though I can only speculate this based on what I've seen and how I do not see this behaviour happen on my native Linux system.

This happens with or without "Enable 'line wrapping selection" checked and unchecked.
It seems like it is copying all of the white-space around the text even though there is non in the file.

I should note that if, for example, I copy and paste everything I'm writing here right now, it works fine.
It only seems to be when I'm in bash itself and working within that environment.

I've recorded a video of this happening too: https://youtu.be/Z-M5P7ZTJqs

**What's wrong / what should be happening instead:**
It should paste the multi-line content as multiple lines, not a single long line with lots of white-space.

**Comment by DarthSpock** [comment]
This is a console issue. You should file there.

**Comment by DeeToTheVee** [comment]
Valid point, my bad. I'll close and move :-)
