### ISSUE TITLE
Windows 10 without Microsoft Store (Business) can't install Microsoft-Windows-Subsystem-Linux

### ISSUE THREAD

**Issue by array42** [Microsoft/WSL#2946]
Following https://docs.microsoft.com/en-us/windows/wsl/install-win10 and https://superuser.com/questions/1217167/cant-find-windows-subsystem-for-linux-feature-to-install-bash-for-windows I enabled the Developer Mode.
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
fails with unknown Feature error
```
DISM.exe /Online /Enable-Feature /All /FeatureName:Microsoft-Windows-Subsystem-Linux /NoRestart
```
fails with Error: 0x800f080c

**Comment by fpqc** [comment]
LTSB and Business Branch versions will not have WSL, since the latest editions of those editions precede the FCU, when the feature came out of beta.

**Comment by lewisdonofrio** [comment]
LxRunOffline works quite nice without the store ;)

**Comment by therealkenc** [comment]
> LxRunOffline works quite nice without the store ;)

That is because you already enabled the WSL feature in Windows. The OP in this thread doesn't even mention the word "Store". Seriously.

**Comment by lewisdonofrio** [comment]
removed my comment....still learning just trying to help

**Comment by benhillis** [comment]
Closing because this has been answered.
