### ISSUE TITLE
Git is showing different outputs in cmd and bash

### ISSUE THREAD

**Issue by j4in** [Microsoft/WSL#2947]
The following is the CMD output
```
C:\Users\***\express>git status
On branch iss#13
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/src/buy.js
        modified:   app/src/common.js
        modified:   app/src/sell.js

no changes added to commit (use "git add" and/or "git commit -a")

C:\Users\***\express>cat app\src\buy.js
cat: 'app\src\buy.js': Permission denied

C:\Users\****\express>git checkout app/src/sell.js
fatal: failed to stat 'app/src/sell.js': Permission denied

C:\Users\***\express>
```
Here is the bash output
```
j4in@DESKTOP:/mnt/c/Users/***/express$ git status
On branch iss#13
nothing to commit, working directory clean
```
Attaching the VSCode screenshot as well
![sc](https://user-images.githubusercontent.com/9267856/36152691-da279b08-10f1-11e8-85d5-5ac5b6c2a099.png)

Any idea why?

**Comment by j4in** [comment]
When I logged out and logged in again to windows, git showed these files as removed, and when I did a `Discard all changes`, it worked fine...
VSCode Executed the following git command 
`git checkout -q -- c:\Users\***\express\app\src\buy.js`

What is causing this issues.?

I'm using window version `Microsoft Windows [Version 10.0.17074.1002]`

**Comment by Biswa96** [comment]
Does this error happen only for that repository? Try your procedure with a dummy repo. 
Make a repo with a single `abc.txt` file and reproduce your steps.

**Comment by diablodale** [comment]
@j4in , your CMD output in your original post is unusual. For example, there is no `cat` command or program in the CMD shell. Yet, your post shows a `cat` program ran and produced output (the error).

This suggests to me that you have some binaries/exes in your CMD path that you have installed and are being used. It is those binaries which are having the error, not WSL.

Add to that, it is possible that the git config for those binaries is different than the git config in WSL. Simple git config differences like settings for line endings can immediately cause git status to report differences.

Last, Visual Studio Code does not have built-in support to use the git in WSL. VS Code does not include git itself. And, git does not come with CMD. That means VS Code is using some unknown git that you have installed. It is that unknown git install that is having problems, not WSL.

If you want to use the WSL git in VS Code, you need to use tools like https://github.com/andy-5/wslgit

**Comment by DarthSpock** [comment]
> If you want to use the WSL git in VS Code, you need to use tools like https://github.com/andy-5/wslgit

@diablodale Not exactly true. If he upgrades to at least 17093, then he gets the follow benefits: 

> improved case sensitivity support in DrvFs.

See details in release notes for options.
    
> You can now use forward slashes in Windows paths when mounting DrvFs, e.g.: sudo mount -t drvfs //server/share /mnt/share

Thus defeating purpose of that project as it's whole point is the translation of paths. Just install the git plugins on the VSCode Marketplace (they're free).

**Comment by diablodale** [comment]
@DarthSpock , I think you went off topic.   OP, please keep that in mind.
The OP is trying to run git from the CMD prompt and from VS Code (likely win32 or win64).
The feature on which you write has no benefit for the OP for this case.
The feature you reference benefits someone already within WSL using paths. Which is cool. But doesn't benefit the OP.
If the OP wants to run the WSL git from Win32/64, then they need an Win32/64 exe which both translated paths *and* launches the WSL subsystem and within it a new ELF git process using the translated paths.
That's what the project I linked does.

Eventually, I suspect VS Code will enable launching a WSL git. That's a VS Code feature not WSL.

**Comment by DarthSpock** [comment]
I was suggesting that he upgrades to the latest Insider and see if he still has issues (after performing the new mount scheme) Also you were specifically saying he was using an unknown git, which is possible, but most likely is using from the Marketplace as they're designed specifically for use in VSCode. His issue is using git for both CMD and WSL. Therefore what I said has relevance to this issue as it gives an possible solution.

**Comment by diablodale** [comment]
How specifically? Be technical.
Installing a newer WSL will do nothing for VS Code nor the CMD prompt. Neither of those environments have any access to the slash/backslash/case new mount feature. Mounts are within WSL only. Win32 never sees them and Win32 cannot access a path like '/mnt/c/xxxx'. Nor does a newer Windows build include a Win32 version of git and cat.
If you have a specific install procedure and technical explanation how it will work. Great. Write here so the OP and I can review it. Otherwise, you are adding confusion to this thread. We are help to help and clarify for the OP and all those that read this after.

**Comment by therealkenc** [comment]
Stale on absent set of CLI steps to generate "`fatal: failed to stat 'app/src/sell.js': Permission denied`" from some common starting point.
