### ISSUE TITLE
dex2oat hangs

### ISSUE THREAD

**Issue by Uldiniad** [microsoft/WSL#2948]
* Windows build number:  Microsoft Windows [Version 10.0.16299.192]

* Steps to reproduce:
1. Get dex2oat source files from the following repository: https://github.com/LineageOS/android_art/tree/lineage-15.1/dex2oat
2. Make dex2oatd
3. Run dex2oatd against a test file
* What's wrong / what should be happening instead:
execution should complete successfully instead of crashing. completes successfully when running single-threadedly

* Strace of the failing command:
https://gist.github.com/Uldiniad/12d1d1ce25dd78a2cdc10bb6b7ab0ac2

* Related workaround
https://review.lineageos.org/#/c/LineageOS/android_build/+/214842/

**Comment by Uldiniad** [comment]
someone pointed out that on line 1 profile.prof is preceded by // on the path. I am currently trying to manually launch the command with a single / to see if there is any difference

**Comment by therealkenc** [comment]
[CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md)

**Comment by Uldiniad** [comment]
@therealkenc I've modified my OP to be more specific. I've looked at the md. What do you want me to add/modify?

**Comment by therealkenc** [comment]
Thanks. Generally speaking you get better service with repro steps rather than a link to a website, because the probability of someone clicking through to the site are mixed at best. If you link the output of a threaded [`strace`](http://man7.org/linux/man-pages/man1/strace.1.html) it might show something. Ref #1771 #2334.

**Comment by Uldiniad** [comment]
Closing because error does not happen consistently.

**Comment by Uldiniad** [comment]
@therealkenc this issue can be marked as solved. I will post a link to an XDA tutorial I'm making for the steps to follow to compile lineage-15.1 on windows 10 via WSL. thanks for your help and suggestions (it helped me find that I could replace the command with another similar command that didn't cause any hanging)

**Comment by therealkenc** [comment]
There isn't really a "solved" tag. In this context closed=solved. If you can reproduce a hang on WSL with (ideally a minimal) set of repro steps using whatever a command that behaves differently than on Real Linux™  (which doesn't hang), that would be a bug tag candidate probably with a "workaround-available" tag. Someone would (ideally) then look at the strace of the hanging command and go "yep it's hanging right there because _reason_" and start looking into a fix. Glad you got it working either way though 👍.

**Comment by Uldiniad** [comment]
The hang happens when using the brunch command (a custom command from the LineageOS team). Not sure what is the difference between breakfast and make combo vs brunch. I put the output of the brunch command in the OP.
Here is my tutorial for whoever is interested in building lineage-15.1 on WSL: https://forum.xda-developers.com/android/software-hacking/guide-how-to-build-lineageos-15-1-t3750175

**Comment by Uldiniad** [comment]
My workaround doesn't work universally as pointed out by a user on xda, so until this is fixed or a universal workaround is found, I'll leave this issue opened.

**Comment by Uldiniad** [comment]
@therealkenc I've added the complete repro steps on the OP. strace -ff brunch klte > strace.build showed the same as the gist

**Comment by Uldiniad** [comment]
we know the culprit is dex2oat. we can successfully build even with brunch by disabling it (it is a workaround but not acceptable for the long run).
relevant files: https://github.com/aosp-mirror/platform_build/blob/master/core/dex_preopt.mk
https://android.googlesource.com/platform/art/+/android-8.1.0_r14/dex2oat/dex2oat.cc
https://android.googlesource.com/platform/build/+/android-8.1.0_r14/core/dex_preopt.mk
https://android.googlesource.com/platform/build/+/android-8.1.0_r14/core/dex_preopt_odex_install.mk
https://android.googlesource.com/platform/build/+/android-8.1.0_r14/core/dex_preopt_libart_boot.mk
https://android.googlesource.com/platform/build/+/android-8.1.0_r14/core/dex_preopt_libart.mk

**Comment by akashgalaxy07** [comment]
@Uldiniad
Thanks for pointing out this issue and creating the tutorial. It will be very good if this bug gets fixed as soon as possible.

**Comment by therealkenc** [comment]
Thanks for updating the OP with repro steps and keep at this. Please post a link to the `brunch.strace` from `strace -f -o brunch.strace brunch _device codename_`. Most of whatever `brunch` is doing is going to be unrelated to the fail. But you might get lucky if there is something obvious enough in the trace near the bottom. It is going to be large. Very large. Which is why a minimal repro has better chances. Here that might be `strace -f -o dex2oat.strace dex2oat input_dex2oat_should_eat_but_doesn't`. Or whatever is customary with `dex2oat`. If that is the problem. 

I looked at the backtrace you linked; sometimes that's enough for a guess. The best hint is:
```
dex2oatd E 02-12 23:21:25 14720 14722 thread-inl.h:154] holding "abort lock" at point where thread suspension is expected
dex2oatd E 02-12 23:21:25 14720 14722 mutex.cc:257] Holding "abort lock" (level AbortLock) while performing wait on "GC barrier lock" (level ThreadSuspendCountLock)
```
Any conjectures I might make on that would be fairly reckless.

You are also on 16299, and trying Insiders is always a good first step. I don't necessarily think it will help, mind, but it eliminates the possibility. Bonne chance.

**Comment by Uldiniad** [comment]
thanks for the suggestions and the helpfulness, I will run straces throughout the week and post the updates as I go. :)

**Comment by Uldiniad** [comment]
@therealkenc No matter what I do it ain't cutting it. This is the command I'm running: strace -f -o dex2oat.strace ./dextest
This is the output:
./dextest: line 2: --boot-image=/home/Uldiniad/android/lineage/out/target/product/klte/dex_bootjars/system/framework/boot.art: No such file or directory
This is the dex2oat test script:
#!/bin/bash
/home/Uldiniad/android/lineage/out/host/linux-x86/bin/dex2oatd --runtime-arg -Xms64m --runtime-arg -Xmx512m --class-loader-context=& --boot-image=/home/Uldiniad/android/lineage/out/target/product/klte/dex_bootjars/system/framework/boot.art --dex-file=/home/Uldiniad/android/lineage/out/target/common/obj/JAVA_LIBRARIES/wifi-service_intermediates/javalib.jar --dex-location=/system/framework/wifi-service.jar --oat-file=/home/Uldiniad/android/lineage/out/target/product/klte/obj/JAVA_LIBRARIES/wifi-service_intermediates/oat/arm/javalib.odex --android-root=/home/Uldiniad/android/lineage/out/target/product/klte/system --instruction-set=arm --instruction-set-variant=krait --instruction-set-features=default --runtime-arg -Xnorelocate --compile-pic --no-generate-debug-info --generate-build-id --abort-on-hard-verifier-error --force-determinism --no-inline-from=core-oj.jar --compiler-filter=speed --generate-mini-debug-info --app-image-file=/home/Uldiniad/android/lineage/out/target/product/klte/obj/JAVA_LIBRARIES/wifi-service_intermediates/oat/arm/javalib.art --image-format=lz4 --profile-file=/home/Uldiniad/android/lineage/out/target/product/klte/obj/JAVA_LIBRARIES/wifi-service_intermediates//profile.prof

Looks like the file it is taking as input and not finding is generated every time brunch is launched and removed otherwise. So my script is useless. But changing the script to track brunch make a file that is way too large (multiple GB). Suggestions?

**Comment by therealkenc** [comment]
I don't know dex2oat from a hole in the ground so no concrete suggestions on how to isolate it.

You could try doing the `brunch` run _without_ `strace -f` into a directory. It will still be multiple GB, but it will split up into lots of files, nearly all of them not relevant. Then start tracking down the one that hangs.

The other thing you could try is modify the `brunch` script (again, whatever a "brunch" is) and put the `strace` lines in there. For example, if it were a makefile (in a saner world long lost) and it was hanging at some point deep in the build, you'd modify the problematic target to call `strace whatever` instead of `whatever`. Bonne chance.

**Comment by Uldiniad** [comment]
Thanks for the suggestion. I finally got dex2oat to hang on strace now (should take an hour before it decides to crash). Will post an update later. I've noticed lots of calls to munmap and I know that WSL had issues with it (ijar had to be modified for it). I've also seen lots of CLOCK_MONOTONIC stuff, and I know that there were issues related to it in the past: https://review.lineageos.org/#/c/1076/
Something else that seems possibly related: https://review.lineageos.org/#/c/160898/

**Comment by therealkenc** [comment]
That's actually the biggest hurdle on following a terrible test case like a huge build ("VS Code doesn't work but is sooo close" is similar). So you track down the cause, but it turns out to be something already reported on github, or worse, known internally at MSFT but _not_ on github. Which makes for a lousy time sink. Hope you find what you are looking for 👍.

**Comment by Uldiniad** [comment]
updated OP with full strace of the dex2oat command that is hanging

**Comment by therealkenc** [comment]
> updated OP with full strace of the dex2oat command that is hanging

Nice. So does it spin forever or does it actually "stop" (just sits there) on that last [`clock_gettime()`](https://gist.githubusercontent.com/Uldiniad/12d1d1ce25dd78a2cdc10bb6b7ab0ac2/raw/d29f096d11d1d5edf537a1ee628eaf1f3165d62d/dex2oat.strace)?

Also confirm, are you doing this on the latest insiders. 17110 or thereabouts, the exact version doesn't matter). The OP still says 16299. You're repro steps look pretty good though, so thanks for that.

I gather there is a service involved here (`dex2oatd`?). To find out what is actually failing you'll need both sides of the interprocess mechanism (whatever IPC mechanism they are using). That is not straightforward.

**Comment by Uldiniad** [comment]
OP has latest info. I didn't try going to insider builds. It does stop after about an hour of hanging. I thought dex2oatd was dex2oat in debug mode. I may be wrong. And I'm unsure of how to proceed with IPC stuff.

**Comment by therealkenc** [comment]
>  I thought dex2oatd was dex2oat in debug mode.

Ah, alright. `d` screamed **d**aemon without my knowing any better. 

But it is trying to communicate with _something_ on `tmp/android-ashmem-23-XXX1pweWT`, even if it is talking to itself. If it is talking to itself, "easier", and you'd done about as much as you can do short of digging into `dex2oatd` with `gdb`. Trying Insiders remains your first step though. It would be surprised if it works (pleasantly so, of course), but there `clone()` CLONE_VM in there (for example) where there have been changes. To the improbable extent anyone has read down this far, that's the `strace` they'll want to see. And who knows, maybe you'll get lucky.

**Comment by Uldiniad** [comment]
Same result on build 17123

**Comment by AngryGami** [comment]
I have same "hang" behavior with dex2oatd and track this down to following command (generated by ninja):

``
/bin/bash -c "(ANDROID_LOG_TAGS=\"*:e\" out/host/linux-x86/bin/dex2oatd --runtime-arg -Xms64m --runtime-arg -Xmx512m --class-loader-context=\"&\" --boot-image=out/target/product/kugo/dex_bootjars/system/framework/boot.art --dex-file=out/target/common/obj/JAVA_LIBRARIES/services_intermediates/javalib.jar --dex-location=/system/framework/services.jar --oat-file=out/target/product/kugo/obj/JAVA_LIBRARIES/services_intermediates/oat/arm64/javalib.odex --android-root=out/target/product/kugo/system --instruction-set=arm64 --instruction-set-variant=cortex-a53 --instruction-set-features=default --runtime-arg -Xnorelocate --compile-pic --no-generate-debug-info --generate-build-id --abort-on-hard-verifier-error --force-determinism --no-inline-from=core-oj.jar  --compiler-filter=speed --generate-mini-debug-info --app-image-file=out/target/product/kugo/obj/JAVA_LIBRARIES/services_intermediates/oat/arm64/javalib.art --image-format=lz4 --profile-file=out/target/product/kugo/obj/JAVA_LIBRARIES/services_intermediates//profile.prof )"
``

When it starts executing it consumes 400% cpu and eventually drop down to 0% but never ends and I thought that this might be multi threading related issue so I ran same command but with -j1 flag added and it successfully finished. I have no idea thought how to set this flag globally for android build...

**Comment by Uldiniad** [comment]
@AngryGami if I could buy you a beer I would! I'm surprised I hadn't thought about it before. The issue still stands, but the workaround is good.
To build with only one thread I believe it is a matter of launching `breakfast _codename_ && make bacon -j 1`

**Comment by Uldiniad** [comment]
@therealkenc label workaround available can be put on the issue :) hopefully microsoft will still look into improving this stuff (my suspicions are that munmap, I/O and multithreading are all part of this issue)

**Comment by therealkenc** [comment]
>label workaround available can be put on the issue

Sure why not. I hope it gets looked at too because the underlying problem is certainly to trip anything that uses a similar pattern. But like I was mentioning in February, it makes for the _worst test case ever_ which is probably why all the crickets. Happy you found a way to limp along.

**Comment by AngryGami** [comment]
I'm already running my build with ``make -j 1`` and this have no impact on dex2oatd unfortunately.

**Comment by AngryGami** [comment]
Exactly as above just with -j1 for dex2oatd, which apparently also have option to run single threadedly:
``/bin/bash -c "(ANDROID_LOG_TAGS=\"*:e\" out/host/linux-x86/bin/dex2oatd **-j1** --runtime-arg... ```

**Comment by Uldiniad** [comment]
@AngryGami https://forum.xda-developers.com/android/software-hacking/guide-how-to-build-lineageos-15-1-t3750175 :)

**Comment by AngryGami** [comment]
Nice :)

**Comment by AngryGami** [comment]
Can we make this flag depend on HOST_OS_IS_LXSS?

**Comment by Uldiniad** [comment]
@AngryGami what flag exactly? I'm not very good with makefiles. And I don't think I can make the process much simpler than it is without asking LineageOS to merge workarounds which I don't think I want to do

**Comment by Uldiniad** [comment]
closing since I'm not using wsl 1.0 anymore
