### ISSUE TITLE
WSL "get-prebuilt.py" syntax error

### ISSUE THREAD

**Issue by Schism082** [Microsoft/WSL#2951]
Hello, I just installed Windows Subsystem for Linux and have a problem. I installed the Ubuntu version from the App Store. I'm on Build 17093. Everything went fine. Now, I'd like to change distro to Kali Linux. I read to enter the following:
lxrun /install
git clone https://github.com/RoliSoft/WSL-Distribution-Switcher.git
cd WSL-Distribution-Switcher
python get-prebuilt.py kalilinux/kali-linux-docker
python install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz
lxrun /setdefaultuser root
 bash
export LANG=C
apt-get update
apt-get dist-upgrade 

My problem is, after cd'ing to WSL-Distribution-Switcher, I enter:
python get-prebuilt.py kalilinux/kali-linux-docker
I get an error saying to change line 7 of get-prebuilt.py (in WSL folder.) It says it's a syntax error. I'm not good with syntax so I don't know how to fix this. I read online it's a problem with python 2 and 3...
The urllib.request module is part of the Python 3 standard library; in Python 2 you'd use urllib2 here.
I changed to "urllib2" but get an error about line 8 saying:
"from utils import Fore, parse_image_arg, chunked_copy, clear_progress, handle_sigint, ensure_ca_load"
 I compared line 8 to the "get-prebuilt.py" on GitHub and they look the same. Can anyone help me get the syntax right on line 8 so I can continue? Do I put spaces or periods or commas? Also, I have python 3 and minimal installed. Thanks

**Comment by DarthSpock** [comment]
Because you are mentioning Kali specifically, I did see their Twitter post that links to their instructions on how to get it working using WSL-Distribution-Switcher. Seeing that they were advertising it, I got Kali to begin talks to get their distro into the Windows Store. Considering it's been almost a month since those talks began, I don't think they're near ready but hopefully by the spring release they will be. There are some networking utilities of Kali that still need working on to get working in WSL (AF_Packet for example). I'm actually hoping getting Kali into the WSL fold will help prioritize that support as it's a dependency to fully run Kali the way it's meant to.

**Comment by Biswa96** [comment]
Is there any compressed rootfs tarball for Kali Linux?

**Comment by DarthSpock** [comment]
That would be a affirmative. If you're not sure, check out the new chroot page Offensive Security [made](https://github.com/offensive-security/Kali-WSL-chroot). They specifically call out install.tar.gz in their install steps.

**Comment by benhillis** [comment]
You'll probably have better luck with this question on the WSL distribution switcher GitHub.

**Comment by DarthSpock** [comment]
@benhillis *coughs* what support...? There are only other users of the distro switcher answering these issues if anybody is answering at all. Not saying it's MS's job to fix this per se, especially as this method will eventually be replaced with installing via Store but a workaround would certainly be nice.

**Comment by RoliSoft** [comment]
@Schism082 The scripts require at least Python 3.6 in order to run, please make sure to install a Windows version of it, and also make sure you use that when you invoke the scripts.

@DarthSpock [regarding your deleted comment] Unfortunately I was unable to dedicate as much time as I had hope to the project due to other priorities, but fortunately I will now be able to resume working on it.

**Comment by RoliSoft** [comment]
He can't use the the Python binary under WSL, since WSL will be stopped during the switch.

However, with the new WSL behavior, which supports running multiple distributions at once, it might be possible to leverage this. I'll have to look into it.

**Comment by Schism082** [comment]
Hi, me again...I installed Python 3.6.4 64-bit on Windows. Then I couldn't get it to work on Ubuntu app from the Store. So I opened Powershell and tried installing it there. I ran: 
git clone https://github.com/RoliSoft/WSL-Distribution-Switcher.git
cd WSL-Distribution-Switcher
python3.6 get-prebuilt.py kalilinux/kali-linux-docker
and everything worked fine. Now I get an error on Powershell after running:
python install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz
[*] Probing the Linux subsystem...
Traceback (most recent call last):
  File "install.py", line 48, in <module>
    basedir, lxpath = probe_wsl()
  File "/mnt/c/Windows/System32/WSL-Distribution-Switcher/utils.py", line 185, in probe_wsl
    basedir = os.path.join(os.getenv('LocalAppData'), 'lxss')
  File "/usr/local/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
Do you know how I can fix this? Or, how do I get Kali on Ubuntu App and not Powershell? Or how do I use the Windows Version of Python 3.6.4? Thank you for the help so far. Python 3.6 worked. I'll wait for replies.

**Comment by Schism082** [comment]
Hi, me again...Would it be easier for me to install the Kali rootfs tarball listed above? I'd like to have a Kali App on Windows. Are there install directions?

**Comment by Schism082** [comment]
Hi, I got it to work. I watched a video on YouTube. It showed me how to download and install Python 3.6.4 for Windows. And git for Windows. It explained it for me. I know have Kali GNU/Linux Rolling \n \l on CMD. Is there anyway to get it on Ubuntu App? Do I have to be in "cd WSL" to start it in CMD? And what about that App above chroot? Is that better? Please reply. Thanks

**Comment by DarthSpock** [comment]
@Schism082 It's not in the Store yet. I was saying that the talks to get it into the Store have started. There's some work on both ends (MS and Offensive Security) to support being put into the Store. For now you'll have to do an unofficial method if you want to run Kali on Windows 10. If you don't mind using chroot in Ubuntu vice installing directly via WSL-Distribution-Switcher, Lxrunoffline, etc. then following the build instructions from the Kali WSL Chroot page I linked above would be a good option.

**Comment by DarthSpock** [comment]
Also since your original issue was getting python working, this can technically be closed though the discussion can still continue.

**Comment by Schism082** [comment]
Ok, that makes sense. I'll stay with Ubuntu and WSL. It works. I'll continue watching for a Kali App in the Store. Thanks again. I'll close this.

**Comment by DarthSpock** [comment]
@Schism082 

> I'll continue watching for a Kali App in the Store.

It's there and so is Debian! Enjoy.

**Comment by ejaysss** [comment]
Try this.

1.) pip install request
2.) pip install client

After this try

get-prebuilt.py kalilinux/kali-linux-docker
