### ISSUE TITLE
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.

### ISSUE THREAD

**Issue by windrunner414** [Microsoft/WSL#2953]
Build 17092.
I install vscode on ubuntu and i run it successfully.But when i reboot windows,I run vscode and it prints 
`Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.`
Why?i can run it before.
I've already used the latest windows insider preview

**Comment by therealkenc** [comment]
#2819 #2760 ([message](https://github.com/Microsoft/WSL/issues/2760#issuecomment-356062135)) #1006 #648

**Comment by windrunner414** [comment]
@therealkenc But I've already update windows.And I can run it.

**Comment by windrunner414** [comment]
@therealkenc And when i restart it,and 'Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting......'

**Comment by therealkenc** [comment]
#1006 and #486 are still open so updating Windows will not address your error. Your [options](https://github.com/Microsoft/vscode/issues/13138#issuecomment-352995770) are (1) don't install PulseAudio, (2) `sudo apt purge libpulse0`, (3) install the WSL PulseAudio [PPA](https://launchpad.net/~therealkenc/+archive/ubuntu/wsl-pulseaudio). If you have further questions regarding pulsaudio you can ask in #646 and someone may jump in to help. There is also discussion thread on VSCode at #2760.

**Comment by windrunner414** [comment]
@therealkenc ok,thank u

**Comment by cuprousoxide** [comment]
@therealkenc hey pardon the noob question, what do I do after I add the PPA and your repository to apt?
