### ISSUE TITLE
MySQL upgrade fails

### ISSUE THREAD

**Issue by chx** [Microsoft/WSL#2956]
Running apt-get upgrade:
```
Setting up mysql-server-5.7 (5.7.21-0ubuntu0.16.04.1) ...
invoke-rc.d: could not determine current runlevel
 * Stopping MySQL database server mysqld                                                                 [ OK ] invoke-rc.d: could not determine current runlevel
invoke-rc.d: could not determine current runlevel
 * Stopping MySQL database server mysqld                                                                 [ OK ] invoke-rc.d: could not determine current runlevel
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
```
Well, of course it can't connect because it just stopped it, silly goose.

**Comment by guijianchou** [comment]
have u try fully uninstalled after backup u date, and newly install it ?

**Comment by chx** [comment]
If  you uninstall it and reinstall it that's not an update. It's a solution but a rather poor one.

The issue truly is trivial: the mysql script in the deb package wants something from the init system but there's no init system. This will require  Microsoft cooperate  with upstream so they check for restart differently. Might as well lock this thread because we can't do a heckuva lot unless someone wants to maintain a PPA with the deb package fixed.

**Comment by w-biggs** [comment]
Having this issue as well.

**Comment by Rican7** [comment]
Only way I was able to get it to work was through the nuclear option as mentioned in https://github.com/Microsoft/WSL/issues/1332#issuecomment-320469132

**Comment by moye2014** [comment]
@chx @Rican7 The other way i tried is ok。First, I opened the window (a) and typed "apt-get upgrade", then opened a new window (b) type "service mysql start", then enter the confirmation option ('Y') in the window (a), then look Continued to upgrade and finally succeeded。You can also try other step sequences like "2-1-3" or "1-3-2" (note：step number is marked in the screenshot )。Wish you
success!! 
![clipboard](https://user-images.githubusercontent.com/9715489/47904689-6686d680-dec0-11e8-9c26-e50a2344117f.png)

**Comment by chx** [comment]
this issue is obsolete, bionic fixed it.
<img width="789" alt="2018-11-02 02_05_26-strokesplus" src="https://user-images.githubusercontent.com/193045/47905239-d4d98380-de43-11e8-9f0c-14f442cd4167.png">
