### ISSUE TITLE
Please add an option to install or full uninstall from CLI

### ISSUE THREAD

**Issue by benqzq** [Microsoft/WSL#2957]
I use Windows for about 25 years now but I never used the Windows store. Never had a reason to. I don't want to install and uninstall WSL form Windows store.

I'd like to install it, or fullly uninstall WSL (Ubuntu in my case) directly form CLI. I assume I'm not the only one.

By "full uninstall" I mean to delete all the file system, including files that were created customly , like som `.sh` files in the user's directory.

Thanks, Ben.

**Comment by fpqc** [comment]
If you are so insistent on doing so, track down the appx file and manual install the appx. There's nothing stopping you.

**Comment by fpqc** [comment]
https://www.maketecheasier.com/download-appx-files-from-windows-store/

**Comment by fpqc** [comment]
Also, it's no longer supported, but you can do 

`lxrun /install` if you wish to install a copy of the legacy version. I don't know how much longer this will be available.

**Comment by therealkenc** [comment]
This is pretty clearly a [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l) thing. You can back-link the submission to this issue. I suspect as a practical matter this gap will be filled in by third parties unless or until sentiment on the Store idea shifts strongly.
