### ISSUE TITLE
Ubuntu 18.04 update errors

### ISSUE THREAD

**Issue by lewisdonofrio** [Microsoft/WSL#2960]
in build 1709 I have Ubuntu 18.04 installed from core/docker tar then added packages till normal usable install like www.tinyurl.com/donofrioworkdesk except I am using lxrunoffline w/18.04 and I'm getting a few errors when I do apt-get upgrade: https://github.com/DDoSolitary/LxRunOffline/issues/21#issuecomment-366490465 I'm getting (https://1drv.ms/u/s!AsBlZbBf72iNoL80WYzed14twrwo0Q #ignoreonedrivelogin) "cp: '/etc/resolv.conf' and '/run/systemd/resolve/stub-resolv.conf' are the same file" and "Failed to replace specifiers: /tmp/systemd-private" please advise.

**Comment by lewisdonofrio** [comment]
I'm stuck here as packages will not complete installing, help.....

**Comment by lewisdonofrio** [comment]
How can I resolve this:

same exact error when I go (do-release-update) from 16.04 to 18.04 I get these "Failed to replace specifiers: /tmp/systemd-private-%b-*" any thoughts on why "Executing: /lib/systemd/systemd-sysv-install enable ondemand" cannot deal with these files if they exist already?

**Comment by Biswa96** [comment]
I'm running Bionic in WSL. Never seen that problem. The files that you've mentioned are same. Try to reinstall Bionic.

**Comment by lewisdonofrio** [comment]
How did you get bionic on WSL?  I had to use core file from https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz because I do not have the store on corp 1709 build.

**Comment by Biswa96** [comment]
Download the SquashFS file from https://cloud-images.ubuntu.com/bionic/current/ and convert .squashfs to tar.gz.

**Comment by lewisdonofrio** [comment]
@Biswa96 is this looking correct?
https://apaste.info/pFAD I guess I need to rename tar to  install.tar.gz because that is all that ubuntu.exe knows how to see?

**Comment by Biswa96** [comment]
See my repository named WSLInstall. You get the command in a .MD file.

**Comment by lewisdonofrio** [comment]
where is this repo located?

**Comment by lewisdonofrio** [comment]
I was  able to do the squish to tar and 7zip out the ubuntu.exe from the appx and renaming the file to install.tar.gz and it worked perfectly (we so far now on to adding my needed 1k packages) thank you for your help so far.

**Comment by Biswa96** [comment]
If your problem solved. You may close this issue.

**Comment by lewisdonofrio** [comment]
still seeing got lots of packages to install then well see how it goes when it tries to update systemd

**Comment by ElTopo** [comment]
I recently hit this issue too, ended up backing up all my SSH keys and other personal files, then did a clean re-installation. I will stay with 16.04.

**Comment by lewisdonofrio** [comment]
so much better once you do the squish to tar when you reinstall the wsl instance.  I have 18.04 working on my left desktop now I used the squash file from https://github.com/Microsoft/WSL/issues/2618 and the ubuntu.exe 7ziped from https://github.com/Microsoft/WSL/issues/2618 (grabbed the ubuntu.exe only and the new renamed install.tar.gz file and it worked like it should!! #sohappy!)

**Comment by heldchen** [comment]
anyone got around `add-apt-repository` (or rather the underlying `apt-key`) failing in 18.04 with `IPC connect call failed` due to a non-running dirmngr?

```
root@devbox:~# add-apt-repository -y ppa:ondrej/apache2
gpg: keybox '/tmp/tmp1dxzjlmo/pubring.gpg' created
gpg: connecting dirmngr at '/tmp/tmp1dxzjlmo/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
Failed to add key.
root@devbox:~# apt-key adv --receive-key 0x4F4EA0AAE5267A6C
Executing: /tmp/apt-key-gpghome.26gIc3RU5y/gpg.1.sh --receive-key 0x4F4EA0AAE5267A6C
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.26gIc3RU5y/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
root@devbox:~#
```

manually adding the key works, but that feels dirty:
```
root@devbox:~# curl -s "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C" | sudo apt-key add -
OK
root@devbox:~#```

**Comment by lewisdonofrio** [comment]
I need to try that manual method because I need xfwm4.13 for the opengl support and right now I just get the same dirmngr ipc issue, I've tried to start it manually and no difference....how did you get the receive-key

**Comment by lewisdonofrio** [comment]
how did you get the "receive-key?"

**Comment by lewisdonofrio** [comment]
how did you get the "receive-key?"

**Comment by therealkenc** [comment]
> IPC connect call failed due to a non-running dirmngr?

Possibly. The lxrunoffline issue tracker is [here](https://github.com/DDoSolitary/LxRunOffline/issues). If you have a repro for the `dirmngr` IPC fail under a supported platform (note: this is entirely doable) please open a new issue following [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). Whether doing so will be constructive for the effort or not I can't say; there is a higher than zero chance it is a dupe.

**Comment by lewisdonofrio** [comment]
I need to try that manual method because I need xfwm4.13 for the opengl support and right now I just get the same dirmngr ipc issue, I've tried to start it manually and no difference....how did you get the receive-key - please email me lewis.donofrio@gmail.com how you got the key for that repo?

**Comment by lewisdonofrio** [comment]
@heldchen  tried gpg --recv-keys key-id but nope....@therealkenc (I'm not using the lxoffline method)

**Comment by heldchen** [comment]
@lewisdonofrio just let the `add-apt-repository` run and fail, then execute `apt-get update`, look for the failing key's id, use that key id with the curl workaround to manually add the gpg key. afterwards, `apt-get update` will run.

@therealkenc seems like it's a bionic issue - have not had this problem in 17.10 from a manually converted squashfs. possibly a changed gnupg/dirmngr default... will try a gnupg update to 18.04's version later on

**Comment by lewisdonofrio** [comment]
@heldchen bingo, that apt-update to get key worked...

**Comment by DarthSpock** [comment]
I hit the gnupg/dirmngr error with Debian Testing (Codename: Buster) as well. It's odd that on Stretch, I can add whatever repos I want and the keys are fine and the repos are added and when shifted to Buster the keys are retained along with the repos but adding a repo on Buster gets this error.

**Comment by heldchen** [comment]
it's due to the updated gnupg and friend's packages. you can replicate it on stretch/ubuntu 16:04 by just upgrading those packages to the next versions.

**Comment by lewisdonofrio** [comment]
life with xfce 4.12 and xfwm-4.13 (with now working experimental repo) is going good, nice workaround to this add-repo issue.
![w10-1709-ubuntu1804-xfce4](https://user-images.githubusercontent.com/3161117/38196717-8df5afe6-3652-11e8-83d9-02f5e1e1468a.PNG)

**Comment by DarthSpock** [comment]
@heldchen Since you've already done to work of repro gnupg/dirmngr error, can you post an issue for it? Not sure if it'll be a WSL specific or if the package maintainer needs to fix something.

**Comment by heldchen** [comment]
@DarthSpock the last 18.04 issue I posted on a maintainers github got closed with the comment `18.04 is not yet stable`... so it seems unlike with Debian, in Ubuntu a beta release is not supposed to be usable...  ¯\_(ツ)_/¯

I've since switched to the Debian distro.

**Comment by DarthSpock** [comment]
@heldchen 18.04 isn't stable yet but they are very close to releasing the LTS version later this month. So it will become more and more stable but yes Debian Testing vs Ubuntu betas do have moderate different. Debian is supposed to be one of the most stable distros available. Kali is based on Debian Testing and is quite stable after the work the Kali team does so it would make sense that Debian Testing itself would be more usable than an Ubuntu beta, especially since Ubuntu is based on Debian as well. As far as I understand it, majority of packages made for Debian-based distros release in Debian first, which puts the other distros a little behind, which means they will be more buggy when using a non-stable version of say Ubuntu in this case.

Side note: Ironically even the Debian Stable: Stretch is ahead of 16.04 Ubuntu. Biggest teller is the version of `glibc` being used and you know how many dependencies there are on that one thing, which of course removes the issue people were experiencing since it's a newer version than the bug exists in 2.23 that wasn't patched by Ubuntu LTS for some reason.

**Comment by lewisdonofrio** [comment]
@heldchen do you have the github link where they say that, because 17.04 is out of support they say " Ubuntu 17.04 (Zesty Zapus) was the 26th release of Ubuntu. Support ended on January 13th, 2018. See !eol and https://lists.ubuntu.com/archives/ubuntu-announce/2018-January/000228.html" and 18.04 will be released in two weeks'ish on April 27th so yah I'm saying with stable goodness of ubuntu 18.04 the add-repo workaroudd works fine for me for now...

**Comment by heldchen** [comment]
>  18.04 isn't stable yet but they are very close to releasing the LTS version later this month. 

I know. that's why I was surprised to learn that an issue reported with some package files a few days ago was just closed. as we're using Debian in production anyway, I felt that this was the right time to also switch my local WSL dev env to Debian.

**Comment by lewisdonofrio** [comment]
Yes use what you need, I just needed basic linux/gui/bash/remmina setup others will need moar.  Outline your debian adventures - we're all interested.

**Comment by bterrier** [comment]
For people having the "`Failed to replace specifiers: /tmp/systemd-private-%b-*`" issue. It is a bug in systemd. This is being fixed by the Ubuntu team (see https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1758865).

They have a working package (`234-2ubuntu12.4`) in "_artful-proposed_", so it is not published yet. But it is possible to install this package and fix the issue.

For the ones who will go through this, they will likely then encounter an error during bash upgrade. The pre install script crashes. The fix is already available in glibc but you need to force glibc to update before bash: `sudo apt install libc6`.

**Comment by lewisdonofrio** [comment]
I do not know if you can safely mix artful and bionic source's together?

Here are my repo's http://paste.ubuntu.com/p/ZzTrq3DRWF/

**Comment by lewisdonofrio** [comment]
How did you get that message I have yet to see it my console when I startxfce4 https://paste.ubuntu.com/p/SVBKczdbdh/

**Comment by lewisdonofrio** [comment]
![xfce4-up-capture](https://user-images.githubusercontent.com/3161117/39392529-56343608-4a85-11e8-8b07-6f3aa8ce177d.PNG)

**Comment by bterrier** [comment]
@lewisdonofrio 

No, you should not mix artful and bionic repos. But the systemd error happens also when people try to upgrade to 17.10.

For 17.10 there is a fix in the artful-proposed repo. For 18.04 I do not know if the fix is already available or if it is in the bionic-proposed repo or not yet available at all.

I do not understand what you are talking about with xfce. The errors are happening when you run `apt` from the Ubuntu WSL console. You do not need to start any x server or session.

**Comment by lewisdonofrio** [comment]
Yah I don't mix just seen your post and wondered because this post was only about 18.04/bionic.

**Comment by lewisdonofrio** [comment]
these messages were from the bash.exe console messages when I start xfce4 (I live in xfce4/ubuntu 18.04 at work with my daily driver - basically use w10 as a 15gb bootloader lol)
