### ISSUE TITLE
Running SCP causes BSODs.

### ISSUE THREAD

**Issue by zhang1813023404** [Microsoft/WSL#2962]
~~~English is what I translated like from Bing, I can't write English.~~~
Like  title. I run "SCP -P▇▇   ▇▇   ▇@▇▇" in WSL and causes to the "green screen".
The black square character is the content that I shield, I don't want my server address to be exposed to everyone.
The file size of the transmission is 6.68 MB. The BSOD ~~~GSOD~~~ happened immediately after I entered the password, And This problem is not the first time.

I don't know whether this problem has already existed in issues. I searched SCP for no similar events.
WIndows produced Minidump, and I think it's necessary to send it to you.

Windows Version:
Microsoft Windows [版本 10.0.17074.1002]
64 Bits

Linux Kernel Version:
Linux version 4.4.0-17074-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1002-Microsoft Thu Jan 01  PST 2016

Target Release Version:
Ubuntu 16.04.3 LTS

Expected :
BSOD

**Comment by lewisdonofrio** [comment]
I'm wondering if something else is causing this cause I scp all the time on my daily work driver workstation with 17.04.....

**Comment by mqudsi** [comment]
There was a crypto-related GSOD on a previous RS4 seed, it would cause a GSOD on unlock of 1Password archive (but I did not experience that with 17074, tbh). Have you tried upgrading to 17101?

**Comment by zhang1813023404** [comment]
It has not yet been upgraded to Windows10 17101. Because my device driver compatibility is low, I think the upgrade is likely to affect my use.

If you see the minidump I sent to secure@microsoft.com, it should be valuable information.

In fact, prior to the execution of the SCP, the system is running apacheserver. But I don't think this is the cause of BSOD.

**Comment by geekifier** [comment]
I can consistently reproduce this issue in wsl.exe using Hyper.JS terminal and copying a firmware tarball to a router using scp. During the copy, my system will green screen. After a few of these, I actually had to boot from a Windows installer and perform startup repair, as my system was boot looping.

**Comment by sunilmut** [comment]
I believe this issue is fixed in the insider builds. Let us know if it repro's an a newer insider build.

**Comment by zhang1813023404** [comment]
Thanks you for fix the issue.

My Windows is upgraded in Yesterday.

Now Windows Version is 17115.1,and I try to scp a large large file.  It is not exception.
