### ISSUE TITLE
Directory symlink created in Windows does not work in WSL

### ISSUE THREAD

**Issue by szilvaa** [Microsoft/WSL#2965]
* Your Windows build number:  
```
Microsoft Windows [Version 10.0.16299.248]
```
* What you're doing and what's happening:  

In Windows cmd.exe shell:
```
C:\>mklink /d AppData c:\Users\szilv\AppData
symbolic link created for AppData <<===>> c:\Users\szilv\AppData
```
Then in WSL (Ubuntu 16.04) shell:
```
$ls -l /mnt/c/AppData
ls: cannot read symbolic link '/mnt/c/AppData': Input/output error
lrwxrwxrwx 0 root root 0 Feb 19 14:19 /mnt/c/AppData
```
* What's wrong / what should be happening instead:

The directory symbolic link created in Windows does not work. Regular symbolic links (i.e. files) work.

* Strace of the failing command, if applicable: 

https://gist.github.com/szilvaa/15eedc81323b9669acddf53c843f7052

**Comment by therealkenc** [comment]
> Version 10.0.16299.248

#2898
