### ISSUE TITLE
 rsyslogd: set SO_TIMESTAMP failed on '/dev/log': Invalid argument [v8.16.0]

### ISSUE THREAD

**Issue by steowens** [Microsoft/WSL#2966]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I am looking at /var/log/syslog after restarting rsyslog distribution obtained in WSL by running
sudo apt-get rsyslog

When this software starts up the following error is written to /var/log/syslog:
Feb 19 20:00:31 LAPTOP-xxxxxxxx rsyslogd: set SO_TIMESTAMP failed on '/dev/log': Invalid argument [v8.16.0]

* What's wrong / what should be happening instead:
This error should not appear unless syslog is not properly configured which evidently it is not.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
The Strace is not feasible ,the command sequence is:
sudo -i
service rsyslog restart
tail -f /var/log/syslog

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
#534
