### ISSUE TITLE
wsl run error 0x80070002, system error log event ID 10005 and 7000

### ISSUE THREAD

**Issue by Justsoos** [microsoft/WSL#2968]
(some Chinese characters from win10 itself below, no affection of reading: )
Windows build number: 
Microsoft Windows [版本 10.0.16299.192]
wsl ver ubuntu 16.04

I've searched this issue with prompt `0x80070002` and windows error log event ID `10005 & 7000`, I have not found similar before posting here, so.

I ran some system clean software, might del some dll registries or wsl files, then wsl can not run, and prompt:
`error 0x80070002`

**Is there any way by minimum damage to repair my wsl, instead of some lxss /uninstall re-install** ??

and win 10 system error log, two pieces:

```
日志名称:          System
来源:            Microsoft-Windows-DistributedCOM
日期:            2018/2/21 13:12:44
事件 ID:         10005
任务类别:          无
级别:            错误
关键字:           经典
用户:            DESKTOP-PNG6623\Mypc
计算机:           DESKTOP-PNG6623
描述:
DCOM 在尝试使用参数“不可用”启动服务 LxssManager 以运行服务器:
{4F476546-B412-4579-B64C-123DF331E3D6} 时遇到错误“2”
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10005</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2018-02-21T05:12:44.118575500Z" />
    <EventRecordID>28203</EventRecordID>
    <Correlation />
    <Execution ProcessID="780" ThreadID="7260" />
    <Channel>System</Channel>
    <Computer>DESKTOP-PNG6623</Computer>
    <Security UserID="S-1-5-21-1080095326-2393639320-2566535045-1000" />
  </System>
  <EventData>
    <Data Name="param1">2</Data>
    <Data Name="param2">LxssManager</Data>
    <Data Name="param3">不可用</Data>
    <Data Name="param4">{4F476546-B412-4579-B64C-123DF331E3D6}</Data>
  </EventData>
</Event>


日志名称:          System
来源:            Service Control Manager
日期:            2018/2/21 13:12:44
事件 ID:         7000
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-PNG6623
描述:
由于下列错误，LxssManager 服务启动失败: 
系统找不到指定的文件。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2018-02-21T05:12:44.117575800Z" />
    <EventRecordID>28202</EventRecordID>
    <Correlation />
    <Execution ProcessID="604" ThreadID="4820" />
    <Channel>System</Channel>
    <Computer>DESKTOP-PNG6623</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">LxssManager</Data>
    <Data Name="param2">%%2</Data>
    <Binary>4C007800730073004D0061006E0061006700650072000000</Binary>
  </EventData>
</Event>

```

**Comment by Justsoos** [comment]
found too many disparate problems of wsl corresponding to SAME error `0x80070002` prompt, could u pls submit formal application for more error codes with MicroSoft.... just a joke :p

**Comment by Justsoos** [comment]
or, guys, does have some wsl integrity checking & repair tools?? as you know, the wsl file system is totally incompatible with windows, ordinary users have no abilities to repair wsl. I checked many posts of this github issues page, the most resolve way is uninstall & re-install ...

**Comment by Justsoos** [comment]
update:
as someone told, I check my computer,the directory tree missing:
`X:\Users\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_(??)\LocalState\rootfs`
only to deep `X:\Users\AppData\Local\Packages\`

**Comment by Justsoos** [comment]
update again:
clue from someone and google, my wsl install on `X:\Users\USERNAME\AppData\Local\lxss` , I can check my personal files and dir tree, still here.

**Comment by therealkenc** [comment]
This issue went stale on without a repro. If the problem persists on Windows 20H2 aka 19042, please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), plus any repro steps leading up to the failure involving "`X:\`".
