### ISSUE TITLE
Cannot run a shell script on a mounted network drive

### ISSUE THREAD

**Issue by typeless** [Microsoft/WSL#2969]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [版本 10.0.16299.248]
```

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
$ cat a.sh
#!/bin/dash
echo hello 
$ ./a.sh
bash: ./a.sh: /bin/dash: bad interpreter: Input/output error
```

* What's wrong / what should be happening instead:
The script `a.sh` should print 'hello'.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

```
$ strace a.sh
execve("./a.sh", ["./a.sh"], [/* 21 vars */]) = -1 EIO (Input/output error)
write(2, "strace: exec: Input/output error"..., 33strace: exec: Input/output error
) = 33
exit_group(1)                           = ?
+++ exited with 1 +++
```

Note that the script `a.sh` is stored in a mounted network drive.
It runs correctly at other local directories.
The `mount` command I use is as follows:
```
sudo mount -t drvfs '\\192.168.100.106\my' /mnt/z
```

**Comment by benhillis** [comment]
I tried this on 17711 and this appears to be resolved.
