### ISSUE TITLE
Bash is unresponsive after more than an hour of inactivity

### ISSUE THREAD

**Issue by thkrishn** [Microsoft/WSL#2971]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  

Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening: 
If the bash terminal window was left open ( more than an hour) and unused , the terminal becomes unresponsive and have to closed down and then reopened again

* What's wrong / what should be happening instead:
Bash should be responsive 

* Strace of the failing command, if applicable: 

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Possibly #2519 related. Won't dupe outright just now because there was no response from anyone on that issue, and in that issue a reboot was the only way out not just restarting bash.

**Comment by someniatko** [comment]
I also have this issue

**Comment by mqudsi** [comment]
@therealkenc given the lack of response in both issues, maybe close one in favor of the other? Because I'm not sure where to follow up on this conversation.

**Comment by therealkenc** [comment]
Yeah this went chirping crickets for long enough, and there is much water under the bridge since 16299.
