### ISSUE TITLE
FTP gives "425 Can't open data connection"

### ISSUE THREAD

**Issue by mobluse** [Microsoft/WSL#2973]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17101.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
In WSL Ubuntu from Microsoft Store:
```
$ ftp ftp.a-one-domain.se
Connected to accessproxy.webpod4-cph3.one.com.
220 Welcome to One.com FTP.
Name (ftp.a-one-domain.se:winuser): a-one-domain.se
331 User a-one-domain.se OK. Password required
Password: ***************
230 OK. Current restricted directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
200 PORT command successful.
425 Can't open data connection.
ftp>
```

* What's wrong / what should be happening instead:
It's wrong that I get this after ls and long wait: `425 Can't open data connection.`
It works in Cmd.exe, i.e. the same commands logs in and gives the listing of files. The first time I run it in Cmd.exe I got a popup dialog about the firewall (I just have the normal Windows 10 firewall). In Ubuntu I didn't get this question and also not in Explorer. It was because FTP didn't work in Explorer that I started to investigate using Ubuntu. After firewall override in Cmd.exe FTP started to work in Explorer, but still doesn't work in WSL Ubuntu. openSUSE Leap 42.2 have the same problem:
```
ftp> ls
200 PORT command successful.
425 Can't open data connection.
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

For security reasons I can't do this since the strace might contain addresses and passwords. Anyway, this doesn't crash -- it's probably some problem with the built-in firewall and WSL.

**Comment by therealkenc** [comment]
> 425 Can't open data connection.

That quirky `ftp` protocol behaviour. See for example [this](https://www.techrepublic.com/article/how-ftp-port-requests-challenge-firewall-security/). You'll need to pretend this is 1993 and use passive mode.

> After firewall override in Cmd.exe FTP started to work in Explorer

Windows firewall makes special allowances for the incoming connection on a per-process per-session basis.

> For security reasons I can't do this since the strace might contain addresses and passwords

Use an anonymous ftp site for testing, like `ftp.gnu.org`. It'll behave the same. But an `strace` probably isn't necessary here.

```
ken@DESKTOP-4UTIQSF:~$ ftp ftp.gnu.org
Connected to ftp.gnu.org.
220 GNU FTP server ready.
Name (ftp.gnu.org:ken): anonymous
230-NOTICE (Updated October 13 2017):
230-
[.... blah blah blah sound of our own voice]
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> passive
Passive mode on.
ftp> ls
227 Entering Passive Mode (208,118,235,20,83,202).
150 Here comes the directory listing.
lrwxrwxrwx    1 0        0               8 Aug 20  2004 CRYPTO.README -> .message
-rw-r--r--    1 0        0           17864 Oct 23  2003 MISSING-FILES
-rw-r--r--    2 0        0            4178 Aug 13  2003 MISSING-FILES.README
-rw-r--r--    1 0        0            2509 Oct 13 21:33 README
[blah blah...]
drwxr-xr-x    2 0        0            4096 May 07  2013 video
-rw-r--r--    1 0        0            1344 Oct 13 21:33 welcome.msg
226 Directory send OK.
```

**Comment by mobluse** [comment]
It worked with `passive` in WSL Ubuntu. It's strange that it works without passive in Cmd.exe after some firewall question, and that it after answering that works in Explorer.

I close this now since it is not a bug in WSL.

**Comment by mobluse** [comment]
I tested to log in on the same server from Lubuntu 16.04 for Raspberry Pi 2 in the same network as the WSL Ubuntu X64-computer, and there it worked without `passive`. It's strange that `passive` is needed in `ftp` for WSL Ubuntu 16.04, but not for Lubuntu 16.04. Maybe it's a bug after all.

**Comment by DarthSpock** [comment]
> FTP has been a hard protocol to kill, because pushing websites around with FTP instead of alternatives like rsync or git is still such common procedure.

 SFTP, FTP-S, or even better SCP ought to be getting used instead. I find it particularly irksome hearing of an extremely known vulnerable protocol like FTP still being used when there are secure substitutes. I haven't seen a test case here for using one of the secure methods I mentioned.

Case in point: 

> For security reasons I can't do this since the strace might contain addresses and passwords

It's being exposed regardless to anyone who manages to put a listener into the network and that was just advertised here. Defender is blocking the connection because port 23 should NEVER be used. By explicitly allowing it for CMD, you just opened your computer up for all manner of wrong doing. 

From that security perspective, I'd say this isn't a bug but by-design.

**Comment by therealkenc** [comment]
> I tested to log in on the same server from Lubuntu 16.04 for Raspberry Pi 2 in the same network as the WSL Ubuntu X64-computer, and there it worked without passive. It's strange that passive is needed in ftp for WSL Ubuntu 16.04, but not for Lubuntu 16.04. 

You mean Native Lubuntu? That's because you have ports 1040-65535 open. If you open those ports on Windows it will work too. 

> Defender is blocking the connection because port 23 should NEVER be used.

You can safely disregard that.
