### ISSUE TITLE
WSL slow to create user account fresh install. Very slow updating

### ISSUE THREAD

**Issue by gmcclins** [Microsoft/WSL#2976]
* Your Windows build number:  

Windows 10 Pro Version 1709 (OS Build 16299.248) 
Insider Program: Just fixes, apps, and drivers.

* What you're doing and what's happening 

WSL extremely slow. Once installed and opened the app it took about 15 minutes before it to ask me for what username/password to use. Once I got past this, it then took over an hour to install updates. Fresh install of Windows 10 Pro and WSL.

The actual download went quickly, it's just the applying of the updates that take so long. The first 3% took about 10 minutes. At the very end, I actually had to type in the sudo password again because it took so long it timed out. I noticed that while it is going slow, per task manager my disk usage is at 100% the whole time.

`sudo apt update && sudo apt upgrade && sudo apt dist-upgrade`.

* What's wrong / what should be happening instead: 

A much quicker install/update. In the past, it was a lot quicker. Not sure when the change happened as I haven't been in WSL for about a month. 

Again, `sudo apt update` does its work as expected. It slows once it gets to `sudo apt upgrade`

Edit: I have tried both repair and reset under Settings/Apps/Ubuntu/Advanced Options. When I reset and open the app again I get the message about it installing, which is normal, but it takes a good 15 minutes of this before it will ask for my username/password to be created. Used to be like 3 minutes or so, if that.

**Comment by therealkenc** [comment]
#2721 #1932 #1305 #981

**Comment by jarvis123kiran** [comment]
use the real linux

more faster or dual boot

**Comment by rban123** [comment]
> use the real linux
> 
> more faster or dual boot

Comments like this are unrelated to the proposed issue and are completely useless.
