### ISSUE TITLE
Installation Failed with Error 0x8007019e

### ISSUE THREAD

**Issue by 0NG** [Microsoft/WSL#2982]
* Your Windows build number: 
Microsoft Windows [版本 10.0.17107.1000]

* What you're doing and what's happening:  
```
D:\>ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x8007019e
Press any key to continue...
```

* What's wrong / what should be happening instead:
Cannot run ubuntu and opensuse

I have tried Repair, Reset and reinstall these two apps, but the problem is still there. Is there anything I can do to check the detail of the problem?

**Comment by benhillis** [comment]
Could you please collect traces while trying to install?

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by 0NG** [comment]
I have collected some yesterday (if no mistake). However, ubuntu works again today. Sorry for I cannot reproduce it now.
[detail.zip](https://github.com/Microsoft/WSL/files/1761039/detail.zip)

**Comment by ItaiSent** [comment]
@0NG Make sure *Windows Subsystem for Linux* is checked.
![image](https://user-images.githubusercontent.com/16288930/36849844-c57abd74-1d6d-11e8-9e05-d01e5e10073d.png)

**Comment by 0NG** [comment]
Yes, it was checked at first, since I have used WSL for a long time. When the problem occured but I couldn't find any solution, I tried to uncheck it, test if ubuntu work, and then checked it again, but the problem was still there. I think it may not because of this Windows feature unchecked.

**Comment by benhillis** [comment]
Yep somehow the WSL feature was disabled, that's what error 0x8007019e means.

**Comment by 0NG** [comment]
Thanks!

**Comment by krysjez** [comment]
In case it helps someone, I had the same error despite having WSL **checked**.
Unchecking it, rebooting, checking it, rebooting again, and running Ubuntu install worked for me.

**Comment by NoahNye** [comment]
@ItaiSent 
thanks ,it's working

**Comment by michellaevens** [comment]
Same issue here. The Windows Susbsystem for Linux feature was turned off. I guess that happened during a Windows update. However, I had another error : 0x800700b7. I could fix it by reinstalling the Ubuntu app from the store.

**Comment by janbernloehr** [comment]
I am not so happy with this having been closed without any changes. Can't we add a more descriptive error message which points the user into the right direction?

**Comment by psychohamster** [comment]
I have a similar scenario to @michellaevens except instead of a second error code, I get a GSOD - depending on the exact invocation means, it's either a SYSTEM_SERVICE_EXCEPTION in hbflt.sys or a SYSTEM_THREAD_EXCPEPTION_NOT_HANDLED in fltmgr.sys
This has been happening for the last several slow ring builds, plus the official release on Monday. 
Anyone else seeing the same thing?

**Comment by psychohamster** [comment]
@Brian-Perkins - Aha - You are correct! Uninstalling BitDefender allowed WSL to run. I'll work on seeing if there is an updated version of it available to get pushed out to our dev machines. Had been working until roughly mid-march builds, if I recall correctly.

**Comment by AGiantSquid** [comment]
In case this helps anyone else, I had this problem show up today after using WSL for months with no problems. I recently changed my startup to automatically open ConEmu on system boot. All I did to rectify this was to close all open terminals. I reopened ConEmu and now it seems to be working fine.  Perhaps trying to open WSL too early in the boot process can cause this error.

**Comment by AnthonySteele** [comment]
The happened to me today. I have been using WSL daily, suddenly it does not work. The Widows feature is _checked_.

**Comment by JuKu** [comment]
I get the same error, but my linux subsystem is already installed and enabled.

**Comment by AnthonySteele** [comment]
This comes and goes on mine.

**Comment by JuKu** [comment]
@benhillis Maybe this issue should be reopened?

**Comment by git58** [comment]
I don't know... I will be wait for bugfix... 

⁣Отправлено с помощью BlueMail ​

На 3 июля 2018 г., 22:46, в 22:46, JuKu <notifications@github.com> написал:п>@benhillis Maybe this issue should be reopened?

**Comment by molnare** [comment]
@AnthonySteele this reminds me of The IT Crowd: "Have you tried turning it off and on again?"
But I must say... It worked! 👍

**Comment by AnthonySteele** [comment]
I have seen a similar error a few more times, usually right after the machine was started up.
In those cases, I tried again 5 minutes later and it worked then. Without a re-install.

**Comment by OrekiDawson** [comment]
你需要在"开启/关闭Windows功能"处启用WSL。

**Comment by checor** [comment]
I think this should to the common troubleshooting on: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by stsands** [comment]
@krysjez, thank you!

**Comment by SalamiArmy** [comment]
I think I'm the first person in this thread for whom  unchecking and re-checking didn't work. I've tried Ubuntu 18, OpenSuse and Debian

**Comment by JuKu** [comment]
@SalamiArmy This didn't work for me, too.
But after a while (and many windows updates) it works now without doing anything.

**Comment by CarlosOrtiz4200** [comment]
> @0NG Make sure _Windows Subsystem for Linux_ is checked.
> ![image](https://user-images.githubusercontent.com/16288930/36849844-c57abd74-1d6d-11e8-9e05-d01e5e10073d.png)

i love you bro

**Comment by nuno-andre** [comment]
Rebooting only after enabling worked for me:

1.  Run as administrator:
    ```
    disable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
    enable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online 
    ```

2. Reboot.

Or as a script:
```
#requires -runasadministrator
disable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
enable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
restart-computer -force
```

**Comment by dksadiq** [comment]
> Rebooting only after enabling worked for me:
> 
> 1. Run as administrator:
>    ```
>    disable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
>    enable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online 
>    ```
> 2. Reboot.

Running the second line of this as Admin on PowerShell and then rebooting right afterwards also worked for me.

**Comment by lawrencekiba** [comment]
> @0NG Make sure _Windows Subsystem for Linux_ is checked.
> ![image](https://user-images.githubusercontent.com/16288930/36849844-c57abd74-1d6d-11e8-9e05-d01e5e10073d.png)

This worked like a charm for me for now.

**Comment by viltiki813196** [comment]
@Juku Did you discover what the problem was?
I currently have the same issue

**Comment by pra17dod** [comment]
> @0NG Make sure _Windows Subsystem for Linux_ is checked.
> ![image](https://user-images.githubusercontent.com/16288930/36849844-c57abd74-1d6d-11e8-9e05-d01e5e10073d.png)

Thanks man!! It worked

**Comment by KasperKivimaeki** [comment]
I had this error after WSL had crashed/frozen.

My wsl crashed after I had opened two Ubuntu wsl terminals and moved some files to its filesystem with file explorer. Afterwards I got this error everytime I opened WSL. I had used Ubuntu WSL previously for years. I hope to find out how to properly reproduce this.

I solved this problem by disabling and enabling the feature and then rebooting.

**Comment by anony436** [comment]
> In case it helps someone, I had the same error despite having WSL **checked**.
> Unchecking it, rebooting, checking it, rebooting again, and running Ubuntu install worked for me.

I have an issue of automatically unchecking wsl after restart. Error when restart: we couldn't complete the features undoing changes..

**Comment by anony436** [comment]
I have an issue of automatically unchecking wsl after restart. Error when restart: we couldn't complete the features undoing changes..

**Comment by anony436** [comment]
> In case it helps someone, I had the same error despite having WSL **checked**.
> Unchecking it, rebooting, checking it, rebooting again, and running Ubuntu install worked for me.

I have an issue of automatically unchecking wsl after restart. Error when restart: we couldn't complete the features undoing changes..

**Comment by anony436** [comment]
> I think I'm the first person in this thread for whom unchecking and re-checking didn't work. I've tried Ubuntu 18, OpenSuse and Debian

I have an issue of automatically unchecking wsl after restart. Error when restart: we couldn't complete the features undoing changes..

**Comment by greatestpythoncoder** [comment]
> In case it helps someone, I had the same error despite having WSL **checked**.
> Unchecking it, rebooting, checking it, rebooting again, and running Ubuntu install worked for me.
Thank You So Much... This fixed my error

**Comment by yaoayh** [comment]
It's helped for Me also, just checked it and restart pc. 
I used UbuntuLTD20.4
Thx

**Comment by catafest** [comment]
Windows Subsystem for Linux is checked if is , uncheck and check again ... then need to be restart in order to have LxssManager on Services.msc, then install Ubuntu app from ms store ...

**Comment by meashsim** [comment]
> 
> 
> @0NG Make sure _Windows Subsystem for Linux_ is checked.
> ![image](https://user-images.githubusercontent.com/16288930/36849844-c57abd74-1d6d-11e8-9e05-d01e5e10073d.png)

It works for me thank

**Comment by tuanluu-agilityio** [comment]
> In case it helps someone, I had the same error despite having WSL **checked**. Unchecking it, rebooting, checking it, rebooting again, and running Ubuntu install worked for me.

Work like a charm!

**Comment by Newtoxton** [comment]
> Rebooting only after enabling worked for me:
> 
> 1. Run as administrator:
>    ```
>    disable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
>    enable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online 
>    ```
> 2. Reboot.
> 
> Or as a script:
> 
> ```
> #requires -runasadministrator
> disable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
> enable-windowsoptionalfeature -featurename 'microsoft-windows-subsystem-linux' -online -norestart
> restart-computer -force
> ```

This worked for me

**Comment by Vasavi00** [comment]
Have the virtual machine checked... This helped

**Comment by adib-enc** [comment]
thank you @ItaiSent

**Comment by firefighter-19** [comment]
Windows 11. All of the suggestions above didn't help -_- still error.

**Comment by starktonys** [comment]
1.win+x，choose  Windows PowerShell（admin）
2. input that     Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
3. choose Y wait reboot

**Comment by slyfox1186** [comment]
I have tried everything suggested on here and nothing works. I reset my PC due to terrible performance and webpages not loading anymore and now I can not longer use WSL.

This really can not be closed until this is fixed as this is a level I would call OS BREAKING.

**Comment by lukethomas1** [comment]
Tried unchecking, rebooting, re-checking, didn't work.

Tried @Newtoxton 's method, didn't work.

Finally, tried @slyfox1186 's method, and it immediately started working, no reboot needed.

**Comment by Strafe153** [comment]
@slyfox1186 I've been trying to fix the issue after the complete PC reset for about an hour and nothing had helped, until I found your solution and it worked. Liked the comment, lifesaver

**Comment by frostchain** [comment]
I tried the suggested fixes but the problem still occurs. I'm running Windows 11.

**Comment by V-Hoesein** [comment]
@slyfox1186 ahhh its worked
