### ISSUE TITLE
Error 0x803FB005 Downloading Ubuntu from the store

### ISSUE THREAD

**Issue by zamadatix** [Microsoft/WSL#2985]
I am having an issue installing Ubuntu on Insider build 17604. Supposedly "Error 0x803FB005" was fixed in a recent build but I still have it when trying to install Ubuntu. I have run WSReset.exe, uninstalled/reinstalled the subsystem, and checked with wslconfig but nothing apparent is appearing:

`PS C:\WINDOWS\system32> wslconfig /list /all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore`

`PS C:\WINDOWS\system32> dism /Online /Get-Features /Format:Table | Select-String "Linux"
Microsoft-Windows-Subsystem-Linux                     | Enabled`

Installing SUSE via the store seems to work fine but when starting the "download" stage on the Store for Ubuntu I get the 0x803FB005 error. All other Store apps work fine.

**Comment by benhillis** [comment]
This seems to be a Microsoft Store issue, I suggest running wsreset agaun and rebooting your machine before trying again.

**Comment by zamadatix** [comment]
Issue resolved itself on a newer Insider build.
