### ISSUE TITLE
bash on WSL cannot be run (ErrorCode 0x80004002)

### ISSUE THREAD

**Issue by wooksini** [Microsoft/WSL#2987]
I cannot run bash.exe on my Windows 10 64bit Machine.
below is my log file using start_lxore_trace command.

Thanks in advance.

[Downloads.zip](https://github.com/Microsoft/WSL/files/1761095/Downloads.zip)

**Comment by larsw** [comment]
Same problem here after an upgrade :-(

Error: 0x80070002

**Comment by Owdaan** [comment]
I have encountred this error, while I killed installation in the middle (it is related to broken instalation). Usually simple reinstall helps, but if it fails you have to download manually archive with ubuntu and try to (re)install.

**Comment by nereusuj** [comment]
I have same issue.

**Comment by nereusuj** [comment]
I observed that when I manually started LxssManager service from service manager, it stop with following message.
"The LxssManager service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other service or programs"

There was no problem with windows 1706. but it happened after upgraded to 1709.

**Comment by benhillis** [comment]
Is anybody experiencing this issue?  I suspect that the Windows Subsystem for Linux optional component was disabled during the upgrade.
