### ISSUE TITLE
"Permission denied" error accessing cifs through drvfs in VirtualBox

### ISSUE THREAD

**Issue by gregsharp** [Microsoft/WSL#2988]
I have downloaded the Windows 10 evaluation VirtualBox Virtual Machine from modern.ie (Microsoft Windows [Version 10.0.16299.248]), and am trying to access files stored on my linux host, using the WSL.  The linux host exports a directory using samba.  This directory is mounted to a drive letter using "net use".  The drive letter is mounted in WSL using "mount -t drvfs".

Windows shows full permission for all pre-existing files.  See link for details:

https://gist.github.com/gregsharp/65915f9ed9ff3ac24c9d036b15d26dcc

In bash, I do not have read permission on pre-existing files.  But I can create new files and manipulate them correctly.  See link for details:

https://gist.github.com/gregsharp/657c3440e3feba2b962c795971309657

I have expected the WSL to have same permissions as the windows user.

**Comment by gregsharp** [comment]
After a little more digging, I found that if I give a file execute permission on the linux host, it gains read permission on the WSL within the VM.  Is this an expected behavior?

**Comment by DarthSpock** [comment]
Windows ACLs ≠ Linux permissions. You'll need to be on an Insider build to map Linux to Windows permission via enabling metadata feature. Going to the "Fast Ring" will allow you to use wsl.conf to easily configure metadata, mounting of fstab, and populating /etc/host (choose your options). 

Running Windows in a VM or native to the box makes no difference to WSL. 

> I found that if I give a file execute permission on the linux host, it gains read permission on the WSL

If by WSL you mean your Linux instance (Ubuntu or OpenSuse), then this is native Linux behavior. Really behavior of permissions for all platforms. You need to have read privilege to execute a file but you don't need execute privilege to read a file if that makes sense to you.

**Comment by gregsharp** [comment]
Thank you.  Yes, I mean the linux instance.  Please forgive me to repeat: if I gave **execute** permission in the host it allowed **read** permission in the linux instance client.  The windows native client does not need execute permission on the host to have read permission.

Nevertheless, I agree it is good to attempt to use the insider build.  My issue might be obsolete because of the new changes to permissions.

**Comment by therealkenc** [comment]
@gregsharp - If you remove execute permission on the Samba host (ie your failing condition) what the following give you:

```
$ ls -l /mnt/x/hello.world
$ stat /mnt/x/hello.world
```

**Comment by gregsharp** [comment]
The file has permission 0644 on the host.
```
dev@MSEDGEWIN10:~/build$ ls -l /mnt/x/hello.world
-rwxrwxrwx 1 root root 3 Feb 27 11:24 /mnt/x/hello.world
dev@MSEDGEWIN10:~/build$ stat /mnt/x/hello.world
  File: '/mnt/x/hello.world'
  Size: 3               Blocks: 2048       IO Block: 512    regular file
Device: dh/13d  Inode: 99108495    Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-27 11:26:29.045872800 -0800
Modify: 2018-02-27 11:24:39.720156000 -0800
Change: 2018-02-27 11:24:39.720156000 -0800
 Birth: -
dev@MSEDGEWIN10:~/build$ cat /mnt/x/hello.world
cat: /mnt/x/hello.world: Permission denied
```

**Comment by gregsharp** [comment]
For completeness, here is the same, with permission 0744 on the host. 
```
dev@MSEDGEWIN10:~/build$ ls -l /mnt/x/hello.world
-rwxrwxrwx 1 root root 3 Feb 27 11:24 /mnt/x/hello.world
dev@MSEDGEWIN10:~/build$ stat /mnt/x/hello.world
  File: '/mnt/x/hello.world'
  Size: 3               Blocks: 2048       IO Block: 512    regular file
Device: dh/13d  Inode: 99108495    Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-27 11:26:29.045872800 -0800
Modify: 2018-02-27 11:24:39.720156000 -0800
Change: 2018-02-27 11:24:39.720156000 -0800
 Birth: -
dev@MSEDGEWIN10:~/build$ cat /mnt/x/hello.world
Hi
```

**Comment by therealkenc** [comment]
> The file has permission 0644 on the host.
>
> `dev@MSEDGEWIN10:~/build$ ls -l /mnt/x/hello.world`
> `-rwxrwxrwx 1 root root 3 Feb 27 11:24 /mnt/x/hello.world`
> `[....]`
> `dev@MSEDGEWIN10:~/build$ cat /mnt/x/hello.world`
> `cat: /mnt/x/hello.world: Permission denied`

That's on WSL and the perms are 0777 (maybe fix up your post to avoid confusion).

That's incorrect behaviour with 0777 perms. Unfortunately DarthSpock's post relegated this issue# to the  bikeshed pile faster than I could get to it.

Not sure if the issue can be recovered at this point, but to get looked at you'll need a really really tight repro, and that's not a small task. "Set up a VirtualBox VM and export a Samba share" is too hand-wavy even though it is clear what you are doing. No one is going to guess your exact Samba setup, or even, necessary, _has_ a Samba setup. So you'll need something like an exact list of CLI (!) actions to perform on the Real Linux side and exact list of CLI actions to perform on the WSL side to reproduce the behaviour. Something that can be cut-and-pasted without grief. And even then....

Or, set the execute bit as a work-around. Or do the share in the other direction. Bonne chance.

**Comment by gregsharp** [comment]
Hi, thank you.  I don't understand what you mean about fixing my post, can you explain?  

I agree it is strange that WSL permissions don't match host.  But I am not totally sure.  Since I was unable to directly mount cifs or vboxfs from WSL, my next attempt was to mount with cifs with windows and then devfs the drive letter.  (This workaround was mentioned already in #2896).  What permissions should one expect from this?

The execute bit is a good workaroud.  When I get some free time (hah!) I'll try to sign up and try the insider build.  Using WSL is a great help to speed up development and testing, and happy to do my part.

**Comment by gregsharp** [comment]
@sunilmut With your permission, I will delete your "question" tag.  Or is there something else I should to add to this report?

**Comment by therealkenc** [comment]
>  I don't understand what you mean about fixing my post, can you explain?

You need a repro. A list of command line steps to take. Don't assume the reader has Samba installed or has VirtualBox VM installed. You can assume the reader has a clean install of Real Ubuntu somewhere accessible to WSL. That list of steps will not be trivial and means you'll need config files set up to `wget`  and `cp` (contrast: "Follow Samba setup instructions at \<link\>"), but it is doable. Bearing in mind the effort might result in a reply along the lines of "Samba shares are not a supported scenario at this time". Or no reply at all.

> I agree it is strange that WSL permissions don't match host.

No the permissions are whatever you tell `mount` to make them; normally with `mount -t cifs -o uid=0,gid=0,file_mode=0777,dir_mode=0777` (for example) on Real Linux. CIFS has no idea (and does not care) what the permissions of those files are on the host.

The curiosity here is that the permissions are `0777` on WSL but you are still getting a permission denied on a _read_.

> (This workaround was mentioned already in #2896). What permissions should one expect from this?

Yeah that was me. You'd expect `0777`, just like any DrvFS mount in Fall Creators 16299.
