### ISSUE TITLE
Windows WSL Ubuntu opening PowerShell doesn't have autocomplete

### ISSUE THREAD

**Issue by J0rdyV** [Microsoft/WSL#2990]
I configured my ubuntu terminal in *~/.bash_aliases* with
```
alias powershell="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
```
So that when i'm in a folder an quickly want to execute a PowerShell command, i can do so with just typing powershell, and a it opens inside the folder.

This works perfectly, commands also execute like i want, no problems there.
But i don't have autocomplete.
Also arrow up, for last commands doesn't work.
Autocomplete is enabled in *~/.bashrc* and works for linux commands.

Is this issue because i'm opening it from bash?
Or can i configure this option somewhere so powershell opens in a different mode when i can use the arrow keys, autocomplete, ...

First time opening a ticket ever, 
so please say so if i did something wrong/didn't give enough info
😄

**Comment by DarthSpock** [comment]
@J0rdyV Can't help you with the autocomplete for Windows Powershell but if all you care about is running Powershell, have you tried using the [Linux version](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604)?

**Comment by J0rdyV** [comment]
Windows Powershell works with the shortcut.

I will try the linux version but i don't think that would be the best option.

**Comment by J0rdyV** [comment]
Tested the linux version but this is not the sollution because i can't use most of the commands i use from the windows powershell, for example Connect-SPOService.
This does work with the windows powershell shortcut in ~/.bash_aliases but like i said,
the autocomplete, arrow keys, ... don't work.

**Comment by DarthSpock** [comment]
Yes there are some Windows specific modules that were stripped from Linux and there are other projects to restore some of that functionality, I was just curious if it would resolve the auto-complete issue. You will need to file this as a [Windows Console](https://github.com/Microsoft/console) issue. Be sure to provide your Windows version. If you aren't running 16299 at a minimum, your issue may not be able to be resolved quickly.

**Comment by benhillis** [comment]
There is functionality on the way to skip-ahead Insider builds that will make this issue (and half of the issues tagged with the "interop" label) go away.

**Comment by fpqc** [comment]
@benhillis pull some strings to get me into skip ahead 😭

**Comment by benhillis** [comment]
Fixed in 17618.

**Comment by l13rb4git** [comment]
> alias powershell="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
Thanks for that alias!

**Comment by ranjanified** [comment]
> alias powershell="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"

@J0rdyV  This saved my day. Thanks a lot. My WSL was saying powershell.exe: command not found.
