### ISSUE TITLE
gcc make check in fixincludes fails because it can't create directory "*"

### ISSUE THREAD

**Issue by jaykrell** [Microsoft/WSL#2991]
You saw this coming.
Get gcc source.
configure (out of tree)
make
cd fixincludes
make check

It fails, because it, perhaps inadvertently, tries to create a directory named "*".

This is probably a mistake on their part, probably meaning star to be a wildcard but when it matches nothing, it ends up as itself.

This is on NTFS of course. I imagine if I SMB to ext it might work.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84631

Basically every character except forward slash and nul need to work for compatibility.
Also question marks and backward slashes -- they work on my Mac.

What Cygwin does is tunnel "invalid low ascii" through as "valid high Unicode" or somesuch. However, ideally, I power down Windows, and boot up Linux and look at the NTFS volume and see the expected valid low ASCII. Hopefully the special casing of * can be limited to Win32 and not invade NTFS. Sure, FindFirstFile's implementation will understand it, but open need not. (except then directory enumeration from Win32 becomes ambiguous -- is * a wildcard or exact match? No matter, I don't think Win32 needs to read these files correctly.)

**Comment by therealkenc** [comment]
[CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). But assuming fixincludes really is creating `*` files, that's #1514 et al and should be addressed in [17101](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17101).
