### ISSUE TITLE
Issue while installing gitlab package in Ubuntu

### ISSUE THREAD

**Issue by jthirupa** [microsoft/WSL#2992]
While upgrading the package, i am facing the below error and it is not progressing after this.

$ sudo dpkg --configure -a
Setting up gitlab-ce (10.5.2-ce.0) ...
[2018-03-02T01:06:27+00:00] WARN: Port 8889 not available
[2018-03-02T01:06:27+00:00] WARN: Port 8890 not available
[2018-03-02T01:06:27+00:00] WARN: Port 8891 not available
[2018-03-02T01:06:27+00:00] WARN: Port 8892 not available

Please provide the steps to resolve the issue

**Comment by Biswa96** [comment]
Check firewall rules if it blocks WSL.

**Comment by therealkenc** [comment]
There's [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/13398) and [this](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/707). Check if you've got something happening on those ports with `netstat.exe -n` before running `dpkg`.

**Comment by therealkenc** [comment]
Assuming external, ref the links above.
