### ISSUE TITLE
WSL green screen during file transfer

### ISSUE THREAD

**Issue by ascendo** [Microsoft/WSL#2994]
When I tried to transfer the file to another server, it gives me green screen.

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

[minidump.zip](https://github.com/Microsoft/WSL/files/1776379/minidump.zip)

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17074.1002]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

WSL green screen during file transfer
When I tried to use scp / Rsync to upload or download, it will give me the green screen.

* What's wrong / what should be happening instead:

Green screen
![img_20180228_110331](https://user-images.githubusercontent.com/907041/36918397-a8321522-1e0e-11e8-944e-f4404b9ab63d.jpg)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

If I use strace, it will not happened. But without strace, it makes green screen.

 strace -o scp.strace -f scp /home/wyim/scratch/g/IAP/Sbicolor_255_v2.1.transcript_primaryTranscriptOnly.fa unr:/home/wyim/scratch/

 scp /home/wyim/scratch/g/IAP/Sbicolor_255_v2.1.transcript_primaryTranscriptOnly.fa unr:/home/wyim/scratch/

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Brian-Perkins** [comment]
This should be fixed in Insider Build 17083 or later. It is difficult to dupe these without having access to the various memory dumps, but this is #2857
