### ISSUE TITLE
symbolic links that work with UNIX and Windows

### ISSUE THREAD

**Issue by LewisPringle** [Microsoft/WSL#2995]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
in a directory which is mounted drivefs (e.g. /mnt/c/Sandbox/a/b/c)
ln -s ../../Builds  

* What's wrong / what should be happening instead:
It works FINE in the unix shell
but when I use a windows cmd shell I see
dir
...
03/01/2018  11:02 PM    &lt;JUNCTION&gt;     Builds [...]
...
and cd Builds produces:
The directory name is invalid.

 * WSL, cygwin, and mklink all provide windows ways to create symbolic links. And NONE of them work with any of the others. This makes software development still quite painful, and hard to share a code base across different tool sets. In my view - this is the largest remaining impediment to using Windows for UNIX development.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by LewisPringle** [comment]
OK - now I see this MAYBE fixed in 
     https://github.com/MicrosoftDocs/WSL/releases/tag/17046

So wondering when that will be released to the general public?

**Comment by onomatopellan** [comment]
Next update is called 1803 so if nothing weird happens it should be released next month.

**Comment by therealkenc** [comment]
#353 #1475 #2898

**Comment by fatfatson** [comment]
confirmed! the insider build 17120 is ok

**Comment by bclay1297** [comment]
Using most recent version of ms4w on windows 10 system, 
  
I am trying to use symbolic links connect to data on a NAS.  They appear to be ignored.  The only error message says path is not found.  The link was create with mklink /d.  When I dir the path / link I see all of the data.
