### ISSUE TITLE
While installing npm for node.js i have this error Anybody having any idea please leave it in comment.. 

### ISSUE THREAD

**Issue by FrancisJebarson** [Microsoft/WSL#3002]
E:\NODE>npm start
npm ERR! path E:\NODE\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'E:\NODE\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francis\AppData\Roaming\npm-cache\_logs\2018-03-07T12_24_54_354Z-debug.log

**Comment by Biswa96** [comment]
Did you do it in WSL environment? This repo is for WSL only.

**Comment by FrancisJebarson** [comment]
brother i have solved that one .. but now have an another one. will you help me to solve

**Comment by benhillis** [comment]
Closing, this is not WSL related.
