### ISSUE TITLE
Getting WaitForExitWithTimeoutImpl when building skia with GN

### ISSUE THREAD

**Issue by mattleibow** [Microsoft/WSL#3005]
* Your Windows build number: 10.0.16299.248

* What you're doing and what's happening: 
I am busy trying to build the SkiaSharp library - and at this stage I am at the build for the native `skia.a`. When I run GN normally (no verbosity args) or with `-q`, then I this message:
```
[0309/044708.104294:ERROR:process_posix.cc(192)] Not implemented reached in bool (anonymous namespace)::WaitForExitWithTimeoutImpl(base::ProcessHandle, int *, base::TimeDelta)
```

Interestingly, if I run it normally, this line appears twice, with `-q` it appears only once. However, if I run it with `-v`, then this does not appear. Also, interesting, the build still continues just fine.

* What's wrong / what should be happening instead:
That line doesn't look like it should appear :)

* Strace of the failing command, if applicable:
```
./bin/gn gen out/linux/x64 -q --args="is_official_build=true skia_enable_tools=false target_os=\"linux\" target_cpu=\"x64\" skia_enable_gpu=false skia_use_system_freetype2=false skia_use_icu=false skia_use_sfntly=false skia_use_piex=true skia_use_dng_sdk=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags=[ \"-DSKIA_C_DLL\" ] extra_ldflags=[  ]"
```
https://gist.github.com/mattleibow/b5b85d49566feb7418d48082c6801f29

**Comment by therealkenc** [comment]
That's #1353 aka #2786 aka the Rick Grimes problem. The library is trying to get the parent process id of a given process id [here](https://cs.chromium.org/chromium/src/base/process/process_posix.cc?type=cs&q=WaitForExitWithTimeoutImpl&sq=package:chromium&l=190). You're correct, best evidence is it is only a soft fail.

**Comment by mattleibow** [comment]
Ah, thanks. So far this WSL thing has been going very well 😸  Thanks for your hard work guys!
