### ISSUE TITLE
WSL Shell doesn't load when computer is named with emoji characters

### ISSUE THREAD

**Issue by DrDrrae** [Microsoft/WSL#3009]
I'm running Win 10 16299.248 64 bit currently.

I've changed the name of my conputer to an emoji character and I cannot launch WSL shell.  I've installed both Ubuntu and Debian and the issue remains the same.  The console window opens but never loads anything.

<img width="961" alt="wsl bacon emoji" src="https://user-images.githubusercontent.com/672350/37208442-72ee672e-236f-11e8-9e77-ef9a72a0a8df.png">

**Comment by Biswa96** [comment]
Can you open CMD or Powershell? Is there any problem with those?

**Comment by DrDrrae** [comment]
Same issue happens if launching from CMD or Powershell.

**Comment by Biswa96** [comment]
@benhillis Seems to be with a `console` tag!

**Comment by therealkenc** [comment]
#2442
