### ISSUE TITLE
traceroute command from inetutils-traceroute does not return any results

### ISSUE THREAD

**Issue by aydeisen** [Microsoft/WSL#3010]
Windows Build: Microsoft Windows [Version 10.0.16299.192]

What am I doing:
I'm trying to execute a traceroute included in the GNU inetutils-traceroute package, nothing resolves.  The same address resolves successfully using ping.

aydeisen@AEISEN-NBK3:~$ sudo apt-get install inetutils-traceroute
aydeisen@AEISEN-NBK3:~$ ping www.google.com
PING www.google.com (74.125.68.99) 56(84) bytes of data.
64 bytes from sc-in-f99.1e100.net (74.125.68.99): icmp_seq=1 ttl=39 time=213 ms
64 bytes from sc-in-f99.1e100.net (74.125.68.99): icmp_seq=2 ttl=39 time=212 ms
64 bytes from sc-in-f99.1e100.net (74.125.68.99): icmp_seq=3 ttl=39 time=212 ms
64 bytes from sc-in-f99.1e100.net (74.125.68.99): icmp_seq=4 ttl=39 time=212 ms
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3001ms
rtt min/avg/max/mdev = 212.869/212.953/213.176/0.350 ms
aydeisen@AEISEN-NBK3:~$ traceroute www.google.com
traceroute to www.google.com (74.125.68.147), 64 hops max
  1   *  *  *
  2   *  *  *
  3   *  *  *
  4   *  *  *
  5   *  *  *
  6   *  *  *
  7   *  *  *
  8   *  *  *
  9   *  *  *
 10   *  *  *
 11   *  *  *
 12   *  *  *
 13   *  *  *
 14   *  *  *
 15   *  *  *
 16   *  *  *
 17   *  *  *
 18   *  *  *
^C

What should be happening instead:
Traceroute should function as it would when running in a native Ubuntu instance, or at least in a fashion comparable to running tracert in Windows Console

STrace of the failing command attached
[traceroute.zip](https://github.com/Microsoft/WSL/files/1797736/traceroute.zip)

**Comment by Biswa96** [comment]
Can you traceroute in Command prompt wth `tracert` command? If not then the problem may be in your network.

**Comment by therealkenc** [comment]
#2742 #1979
