### ISSUE TITLE
go get can't find a GOPATH directory if I set the GOPAH on a windows directory

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/WSL#3011]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Windows

```
Microsoft Windows [Version 10.0.16299.125]
```

Linux subsystem on windows

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

```
export GOPATH=/mnt/c/Users/tsushi/Codes/Project/OpenHackDevOps/tools
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
go get -u github.com/golang/dep/cmd/dep
: no such file or directoryep/cmd/dep: mkdir /mnt/c/Users/tsushi/Codes/Project/OpenHackDevOps/tools
```

* What's wrong / what should be happening instead:

I expect go get successfully fetch the library.  However, if I set the GOPATH to the non-windows directory, it works fine.

```
GOROOT=/usr/local/go
GOPATH=/home/ushio/projects/go
go get -u github.com/golang/dep/cmd/dep
```

Strace: 

[go.strace](https://gist.github.com/TsuyoshiUshio/3aa6685a2b0a477c9424a49c3e579a8b)

**Comment by therealkenc** [comment]
No repro offered, but you've got a carriage return being injected somewhere along the way in your development process. From the `strace` output, note the `\r` in the path name. This is usually caused by editing something or another with a win32 editor not configured for Unix EOL convention. Variation #2365 #2551.

```
stat("/mnt/c/Users/tsushi/Codes/Project/OpenHackDevOps/tools\r/src/github.com/golang/dep/cmd/dep", 0xc420291e48) = -1 ENOENT (No such file or directory)
```

**Comment by TsuyoshiUshio** [comment]
Thank you very much, @therealkenc  It is the problem. I create a shell file which set the environment variables on Git Bash (windows).  The file was not LF.
