### ISSUE TITLE
WSL Distro Launcher?

### ISSUE THREAD

**Issue by christian-korneck** [Microsoft/WSL#3012]
Just out of interest: Are there any plans to make the WSL Distro Launcher sample project + docs available publicly?
https://github.com/Microsoft/WSL-DistroLauncher

There are forks by the various Linux distro projects on the public Internet, i.e.
https://salsa.debian.org/rhaist-guest/WSL

However, wouldn't it be better to make the original repo public instead of having people use i.e. the Debian WSL launcher as a base for their own launcher app?

**Comment by Biswa96** [comment]
You can make your own distribution launcher using the [WSL Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826874(v=vs.85).aspx). The published repo just imports those functions.

**Comment by christian-korneck** [comment]
> The published repo just imports those functions. See the issue number 2635.
@Biswa96 Thanks for your response. The WSL Distro Launcher sample would still be interesting (i.e. implementing a launcher according to "best practice"). There also seems to be some documentation that isn't present in the Debian fork, i.e.:
https://github.com/Microsoft/WSL-DistroLauncher/wiki/Notes-for-uploading-to-the-Store

**Comment by benhillis** [comment]
I recently rewrote the sample and yes we are planning on open sourcing it soon.

**Comment by christian-korneck** [comment]
@benhillis thanks a lot for the feedback! Looking forward to the release.

**Comment by christian-korneck** [comment]
@benhillis Thanks!!
