### ISSUE TITLE
Not able to navigate into Windows created symlink'd directories in WSL bash?

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/WSL#3013]
While using `bash` in WSL (Ubuntu) I try to navigate to /mnt/c/Users/username/symlink_dir (symlink created in Windows `cmd.exe` with `mklink /D`), I get an error: 
`-bash: cd: symlink_dir: Input/output error`

Is this a known issue and is there a way around this?

**Comment by therealkenc** [comment]
#2965 #2898 ([message](https://github.com/Microsoft/WSL/issues/2898#issuecomment-363678843)) #1475 #353
