### ISSUE TITLE
Different vfork() Result Between Linux and WSL

### ISSUE THREAD

**Issue by panda361** [Microsoft/WSL#3015]
* Your Windows build number:  
    Windows Version: 10.0.16299.248
    Linux Version: Ubuntu 16.04.4 LTS ( Linux version 4.4.0-43-Microsoft)

* What you're doing and what's happening:  
    
    When I am trying to use vfork() like codes below, it returned strange results.
```
int count = 1;
int child;
printf("Before create son, the father's count is:%d\n", count);
if ((child = vfork())< 0)
	perror("fork error : ");
else if (child == 0)     //  fork return 0 in the child process because child can get hid PID by getpid( )
{
	printf("This is son, his count is: %d (%p). and his pid is: %d\n", ++count, &count, getpid());
	exit(0);
}
else                    //  the PID of the child process is returned in the parent’s thread of execution
{
	printf("After son, This is father, his count is: %d (%p), his pid is: %d\n", ++count, &count, getpid());
	exit(0);
}

```
* What's wrong / what should be happening instead:

When the program execute vfork(), the father process should be blocked normally.
However the father process execute the following code, it returns:
```
Before create son, the father's count is:1
After son, This is father, his count is: 2 (0x7ffffea81630), his pid is: 5331
This is son, his count is: 2 (0x7ffffea81630). and his pid is: 5332
```
On Linux Virtual Machine, I get the right result:
```
Before create son, the father's count is:1
This is son, his count is: 2 (0x7ffff1e53508). and his pid is: 6707
After son, This is father, his count is: 3 (0x7ffff1e53508), his pid is: 6706
```

**Comment by benhillis** [comment]
This behavior has been fixed in insider builds.

**Comment by therealkenc** [comment]
#2615 ([message](https://github.com/Microsoft/WSL/issues/2615#issuecomment-346509481)). Insider [17046](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046) and the Spring Creators Update RSN.
