### ISSUE TITLE
How do I change the default permissions for new folders under ~/?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/WSL#3016]
Whenever I create a new folder these are the default permissions:

```
Amaral@NAZBOX:~$ mkdir test1
Amaral@NAZBOX:~$ ls -l
total 0
drwxrwxrwx 1 Amaral Amaral 512 Mar 11 10:57 test1
```

How do I changes these default permissions?

**Comment by therealkenc** [comment]
Put `umask 0022` in your `.profile`. This is #352, which I only just noticed got relegated to the 'discussion' doghouse.
