### ISSUE TITLE
bash opens in cwd but ubuntu always opens in ~

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/WSL#3017]
Windows build number:  10.0.16299.248

What you're doing and what's happening:

- `ubuntu` and then `pwd` gives me the value of `~`
- `bash` and then `pwd` gives me the path to the directory in which I started `bash`

* What's wrong / what should be happening instead:

Both should `cd` to from wherever I invoke them in Windows.

**Comment by fpqc** [comment]
This is actually the one part under Ubuntu's control

**Comment by TomasHubelbauer** [comment]
@fpqc I was worried that was the case, but I don't understand why it works with `bash`. Can you try explain the difference in invocation that allows the difference?

**Comment by benhillis** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/mt826868(v=vs.85).aspx

ubuntu.exe is passing false for the useCurrentWorkingDirectory argument. Bash.exe passes true, unless you use the ~ argument (bash.exe ~).

**Comment by TomasHubelbauer** [comment]
@benhillis I don't suppose there is a switch for `ubuntu` I could use to get it to pass `true`?

**Comment by benhillis** [comment]
@TomasHubelbauer - It doesn't look like it.  I recently rewrote the sample they based their binary off and in the new version there is.  Is there a specific reason you don't want to just use wsl.exe?

**Comment by TomasHubelbauer** [comment]
@benhillis I don't keep up with the project that much, so I was confused at what's the best practice when it comes to invoking the distros. I assumed the only supported way was through the name as `bash` and `lxrun` seem to be deprecated, but I didn't realize I could use `wsl` which seems to be supported and map to the default distro. Thank you.

**Comment by therealkenc** [comment]
> Is there a specific reason you don't want to just use wsl.exe?

Excellent question; but not for Tom.

**Comment by fpqc** [comment]
@TomasHubelbauer bash.exe is not deprecated either. The main diff between bash.exe and wsl.exe is that wsl.exe opens your default shell while bash.exe opens specifically bash.

**Comment by TomasHubelbauer** [comment]
@fpqc [This](https://docs.microsoft.com/en-us/windows/wsl/reference) seems to suggest otherwise.

**Comment by benhillis** [comment]
@TomasHubelbauer - Documentation was incorrect, I've fixed it.
