### ISSUE TITLE
WSLENV=LANG with no LANG set -> clears default locale leading to POSIX

### ISSUE THREAD

**Issue by diablodale** [microsoft/WSL#3018]
Some Windows 10 apps (like Visual Studio Code + GitLens) set environment variables like `LANG` and `LC_ALL` when spawning child processes. They do this because they need a child process to output in a specific lang/locale. When the child process is a WSL executable (like Git, Bash, diff, etc.), these environment variables need to be passed into WSL so the executable within can act on them.

The mechanism to do this in recent Windows 10 builds is to set `WSLENV` and list the variables to pass. Unfortunately, setting `WSLENV=LANG` causes an interaction such that when no Windows environment variable `LANG` is set (the default case), the WSL locale is reset to POSIX rather than the locale configured in WSL.

## Setup

Microsoft Windows [Version 10.0.17115.1]
Windows region/locale set to English (US)
WSL Ubuntu 16.04 installed and defaulted to English (US) UTF-8

## Repo

1. Ensure you have no Windows environment variable `LANG`
1. Edit Windows environment variable for the user using the Windows System Properties and set `WSLENV` to the value `LANG`
2. Start Ubuntu by pressing the Windows key, typing `Ubuntu`, and choosing to run the Ubuntu app
3. At the Ubuntu prompt, type `locale`

## Result

The locale is POSIX

## Expected

The locale is en_US.UTF-8

## Workaround

Manually set `LANG` using Windows System Properties so there is always a value for it.

**Comment by therealkenc** [comment]
Different example but with humor value:

![wslenv](https://user-images.githubusercontent.com/7049700/37307338-d99aa426-25f7-11e8-8816-570379557a49.png)

**Comment by therealkenc** [comment]
WSL implemented the requested behavior somewhere between 17115 and "recent". The locale with the OP repro steps is now `en_US.UTF-8` not `POSIX`. As a bonus `TERM=` is passed through.

![image](https://user-images.githubusercontent.com/7049700/117368131-f3d38900-ae77-11eb-97f2-979a03386ea9.png)
