### ISSUE TITLE
How to start WSL in certain startup directory in linux FS?

### ISSUE THREAD

**Issue by Maximus5** [Microsoft/WSL#3025]
Windows 10 1709 (10.0.16299.248)

ConEmu user asked for a way to start bash in its home directory (linux side, `~/folder`).
Seems like it [worked before](https://askubuntu.com/a/868941/361320), you had ability to run `wsl.exe` in the `C:\Users\<YourUserName>\AppData\Local\lxss\home` and voila.

But things were changed, and in my 1709 I see lxss FS here: `C:\Users\win-user-name\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\linux-user-name\`.

The problem is that when I try to run `wsl.exe` (just open `cmd.exe`, `cd` to folder and run `wsl`), it starts in the root of linux FS (`/`) instead of home directory (`~`).

Is that a regression? How we may start wsl in `~`?

**Comment by Biswa96** [comment]
Use `wsl ~` command
