### ISSUE TITLE
build kernel failed Input/Output Error

### ISSUE THREAD

**Issue by kingxf1995** [Microsoft/WSL#3026]
* Your Windows build number:  10.0.16299.251

* What you're doing and what's happening:  occur Input/Output Error on /mnt/e when I build kernel, E drive is a NTFS partition of my removable hard disk

* Strace of the failing command: [strace.5593.txt](https://gist.github.com/kingxf1995/233550db1c88a14976496c2b8653528c)(too many log file generate, I pick out a log file to show the error)

``` shell
$ grep -r EIO
strace.txt.5593:rename("arch/arm/vfp/vfpsingle.o.rc", "arch/arm/vfp/vfpsingle.o") = -1 EIO (Input/output error)
strace.txt.5612:rename("arch/arm/vfp/vfpmodule.o.rc", "arch/arm/vfp/vfpmodule.o") = -1 EIO (Input/output error)
strace.txt.5627:rename("arch/arm/kernel/elf.o.rc", "arch/arm/kernel/elf.o") = -1 EIO (Input/output error)
strace.txt.5648:rename("arch/arm/mm/extable.o.rc", "arch/arm/mm/extable.o") = -1 EIO (Input/output error)
strace.txt.5657:rename("init/do_mounts.o.rc", "init/do_mounts.o") = -1 EIO (Input/output error)
strace.txt.5661:rename("init/main.o.rc", "init/main.o") = -1 EIO (Input/output error)
strace.txt.5666:rename("arch/arm/mm/fault.o.rc", "arch/arm/mm/fault.o") = -1 EIO (Input/output error)
strace.txt.5669:rename("arch/arm/mm/dma-mapping.o.rc", "arch/arm/mm/dma-mapping.o") = -1 EIO (Input/output error)
strace.txt.5678:rename("arch/arm/mm/init.o.rc", "arch/arm/mm/init.o") = -1 EIO (Input/output error)
$ cat linux-3.4.113/arch/arm/mm/init.o
cat: write error: Input/output error
$ echo 1 > linux-3.4.113/arch/arm/mm/init.o
$ cat linux-3.4.113/arch/arm/mm/init.o
1
```

Some file cannot read on wsl, but on win32 environment it is readable. If I delete or rewrite the error file on wsl, it is okay, and the file will readable now. The issue is look like #2644

**Comment by therealkenc** [comment]
> The issue is look like #2644

Pretty much. Be interesting to know if this is better on Insiders, under the theory it is somehow case related per #2593 (though not in an obvious way).
