### ISSUE TITLE
mysql installed few minutes ago somehow , ubuntu bash thinks its not installed.

### ISSUE THREAD

**Issue by mithuns** [Microsoft/WSL#3027]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Trying to run a rails server, installed mysql 10 minutes ago, then rebooted laptop, and now bash says mysql not installed.
```
~$ mysql -u root
The program 'mysql' can be found in the following packages:
 * mysql-client-core-5.7
 * mariadb-client-core-10.0
Try: sudo apt install <selected package>
```
* What's wrong / what should be happening instead:
mysql should be there, if not started, it should atleast be there. I followed these steps to install mysql 
From this [link](https://github.com/Microsoft/WSL/issues/1332)
```
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server
# this skips all of the interactive menus, thereby
# creating a user `root` with empty password;
# you may not actually want to do this for
# your own setup, but I put it here for ease of duplication

mysql -u root # fails bc mysql service isn't running yet
sudo service mysql start
mysql -u root # works!
```
What am I doing wrong, is there a setting to make things persistent ?

**Comment by mithuns** [comment]
I think I know the reason, there is a bash for ubuntu and then there is a ubuntu on my windows, when I open ubuntu, it has my user that I remember creating, and the bash does not know about my user, it is still working on my windows userid, so may be thats why ? 
That raises the question how come the bash for ubuntu does not know of the user I created for ubuntu ?

**Comment by benhillis** [comment]
@mithuns - sounds like you have multiple distributions installed. Ubuntu.exe launches Ubuntu. Bash.exe launches your default distro.

**Comment by mithuns** [comment]
So, how can I get rid of the bash then, since the ubuntu.exe is all I care about.

**Comment by benhillis** [comment]
@mithuns `wslconfig.exe /u Legacy`

**Comment by mithuns** [comment]
Ran in a an administrative console

```
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wslconfig /u Legacy
Unregistering...
Error: 0x80070003

C:\WINDOWS\system32>
```

But, I think it worked just fine, because now when I run the bash, it starts me with the user I created in ubuntu.
Thanks
We can close this.
