### ISSUE TITLE
rename() regular file to non-existent directory doesn't error out

### ISSUE THREAD

**Issue by inoue-katsumi** [microsoft/WSL#3028]
The command below should error out but creates '/tmp/non_existent_dir' file instead.

$ mv  file1.txt  /tmp/non_existent_dir1/ 

I confimed both with 'mv' command and code below.

```
#include <err.h>
#include <errno.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

int main(void)
{
        fopen("file1", "w");

    if (rename("file1", "non_existent_dir1/") != 0)
        err(1, "rename errno %d", errno);

    return 0;
}

```

Below is "strace ./a.out" log on Redhat linux
```
open("file1", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
rename("file1", "dir2/")                = -1 ENOTDIR (Not a directory)
```

Below is "strace ./a.out" on WSL.
```
open("file1", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
rename("file1", "dir2/")                = 0
```

**Comment by therealkenc** [comment]
You didn't state your version number. Works as expected here on 17618.
```
ken@DESKTOP-4UTIQSF:~$ touch foo
ken@DESKTOP-4UTIQSF:~$ mv foo /tmp/foo/
mv: failed to access '/tmp/foo/': Not a directory
```
#1008 if you go far back enough.

**Comment by inoue-katsumi** [comment]
Thanks. My version is 16299.

**Comment by therealkenc** [comment]
Appreciate following up with your version number. #1008 was addressed a long time ago in Creator's Update, which made me double-check (16299 would be okay). You're onto something and I have to walk this back. Sigh.
```
$ rm -fr /tmp/foo
$ touch foo
$ mv foo /tmp/foo/   # no error on 17618
$ ls -l /tmp/foo
ken@DESKTOP-4UTIQSF:~$ ls -l /tmp/foo
-rw-rw-rw- 1 ken ken 0 Mar 15 02:12 /tmp/foo
```

**Comment by therealkenc** [comment]
> $ mv foo /tmp/foo/   # no error on 17618

Appears resolved somewhere between 17618 and recent. WSL1 with wslfs (aka `/home`).

![image](https://user-images.githubusercontent.com/7049700/117364247-840ecf80-ae72-11eb-9b28-87bfa6d1fc91.png)
