### ISSUE TITLE
Show current command in bash on window title

### ISSUE THREAD

**Issue by elig0n** [Microsoft/WSL#3029]
Hello, Is it possible to have Bash on Ubuntu show the current running app executable name in the window title bar ?

**Comment by therealkenc** [comment]
Try:
```
$ trap 'echo -ne "\033]0;$BASH_COMMAND\007"' DEBUG         
$ sleep 2
```
That will change your Windows Console title to "sleep 2" for the duration of the command. If you want something more fancy, the place to ask would be in a shell community (bash, zsh, fish). It isn't really a WSL question. For example the [Oh-My-Zsh](http://ohmyz.sh/) people are partial to this kind of stuff.
