### ISSUE TITLE
Ubuntu Shell Hangs and Doesn't start on Windows 10 1709

### ISSUE THREAD

**Issue by donwlewis** [Microsoft/WSL#3030]
Upgraded from Build 1607 to 1709, and installed Ubuntu from app store.  Ubuntu shell just hangs at launch:

![image](https://user-images.githubusercontent.com/16139164/37504722-8c318ca6-289d-11e8-947d-2cffb3541b3d.png)

Get the following error after a period of time:

![image](https://user-images.githubusercontent.com/16139164/37504769-d7ccd652-289d-11e8-9582-61e69a653ca6.png)

I see this error in the system logs:

The LxssManager service terminated with the following error: 
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

Any help would be appreciated.

**Comment by Biswa96** [comment]
Did you change the LxssManage.dll file in System32\lxss folder?

**Comment by Biswa96** [comment]
Did you change the LxssManager.dll or LxssManagerProxy.dll file in System32\lxss folder?

**Comment by DarthSpock** [comment]
> Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

Last time I had this error, it was for a different Win32 program and the issue was with `Trusted Installer` (I had removed Trusted Installer from my ACLs, painful lesson learned that day. )This was on Windows 8.1 mind you, but nothing really changed regarding `Trusted Installer` with Win 10. Try uninstalling Ubuntu, restarting the Windows Module Installer service (if it's running), otherwise start it and see if an error appears. If it does, it will probably affect other Win32 programs as well. What's odd is `Trusted Installer` shouldn't of had any issues when upgrading versions. The issue may be a corrupt image from when you downloaded the new version. It may simply just be easier to revert back from backup to 1607 and use the Windows Media Creation tool to download and install 1709 (vice using Windows Updates). If that fails, then there's always the option to download the .iso file directly and manually install (you're able to mount .iso in Win 10 without third party apps.) At this point though, if you're doing this much work, you might as well wait for 1803 to come up in a couple weeks and upgrade to that and see if it has the same issue.

**Comment by donwlewis** [comment]
@Biswa96 I made no changes to the DLL myself.

@DarthSpock I would try this approach, the issue I have with that though is that this machine happens to be a company managed machine, therefore I don't really have the means to reimage the machine myself.

**Comment by donwlewis** [comment]
@DarthSpock tried your recommendation, but still have the same issue.  I guess I will have to look at getting my machine re-imaged, but that is going to take awhile.  I appreciate the help.

**Comment by DarthSpock** [comment]
Ah yes painful. A re-image will do the trick if you can verify the image is clean. I'd hate for you to go through that, only to find out the image used was corrupt.

**Comment by DarthSpock** [comment]
Can you factory default instead? or is it you have no workstation admin privileges?

**Comment by donwlewis** [comment]
Will a factory default kick me off the company domain?  That is the pain when dealing with company machines...but yes I do have admin privs on the machine.

**Comment by Biswa96** [comment]
Can you run bash.exe or wsl.exe from command prompt? Or open service manager (services.msc) and try to start LxssManager service.

**Comment by donwlewis** [comment]
Nope.  Both bash.exe and wsl.exe just hang, and if I attempt to run the LxssManager service, I get the following error:

![image](https://user-images.githubusercontent.com/16139164/37529971-bb1455be-28f5-11e8-9848-9a1e4f6d169e.png)

**Comment by benhillis** [comment]
@donwlewis - Yeah unfortunately looks like something corrupted your LxssManager.dll file.  Have you tried adding and removing the optional component?

**Comment by Biswa96** [comment]
I'm definitely sure that your DLL files may be changed.
I've some dangerous steps to solve this issue. Beware of these steps. First backup `System32\lxss` folder. Take ownership of that folder. Search LxssManager.dll and LxssManagerProxy.dll in `System32\WinSxS` folder and copy those in lxss folder.

**Comment by donwlewis** [comment]
@benhillis yes I have removed and re-added the Linux subsystem feature multiple times with no luck.

@Biswa96 what kind of danger?  Security issue or breaking LXSS?

**Comment by Biswa96** [comment]
The second  one.

**Comment by donwlewis** [comment]
@Biswa96 tried you fix, but didn't help.  At this point most likely dealing with a bad image.  Was hoping to get this resolved without a reimage, but looking less likely.  WSL was one of the main reasons I upgraded, so its kinda a bummer, but I appreciate everyone's help with trying to get this working.

**Comment by DarthSpock** [comment]
Do you have a clean image for 16299? Also, a culprit to always consider with updates/upgrades is A/V, host based FW, IPS, etc. getting in the way. They will cause data corruption if not configured correctly. So if you have the older version for your image, try manually upgrading with those security features disabled. Obviously re-enable after the upgrade is complete (if they don't enable themselves after the reboot). Follow these [steps](https://docs.microsoft.com/en-us/windows/wsl/install-on-server) to enable WSL and install Ubuntu via Powershell.

**Comment by donwlewis** [comment]
Most likely has to do with my personal image.  Going to go ahead and close the issue.  Thanks for the help everyone!
