### ISSUE TITLE
PTRACE_SEIZE not supported

### ISSUE THREAD

**Issue by luser** [microsoft/WSL#3031]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:

The `PTRACE_SEIZE` request to the `ptrace` syscall is not supported. Example program:
```c
/* gcc -o ptrace-test ptrace.c */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char** argv) {
  pid_t pid = fork();
  if (pid == 0) {
    sleep(60);
    exit(0);
  }
  if (ptrace(PTRACE_SEIZE, pid, NULL, 0) == 0) {
    printf("ptrace succeeded\n");
  } else {
    perror("ptrace failed");
  }
  return 0;
}

```

Example output:
```
luser@DESKTOP-32V9ND8:/mnt/c/build$ gcc -o ptrace-test ptrace.c
luser@DESKTOP-32V9ND8:/mnt/c/build$ ./ptrace-test
ptrace failed: Invalid argument
```

* What's wrong / what should be happening instead:
`PTRACE_SEIZE` should work similarly to `PTRACE_ATTACH` (which does work). Per [the man page](http://man7.org/linux/man-pages/man2/ptrace.2.html):
```
PTRACE_SEIZE (since Linux 3.4)
              Attach to the process specified in pid, making it a tracee of
              the calling process.  Unlike PTRACE_ATTACH, PTRACE_SEIZE does
              not stop the process.
```

This prevents `rr` from working, and I'm sure it impacts other programs as well.

**Comment by therealkenc** [comment]
Thanks for the excellent repro on `PTRACE_SEIZE`, since you weren't thanked earlier (we don't get enough of them). Better in WSL2.

![image](https://user-images.githubusercontent.com/7049700/89482123-0d5f6d00-d74e-11ea-94ac-18e85f98183f.png)

**Comment by vishwaraj101** [comment]
Getting error while using frida python inside wsl 2:

➜  testbed ./fuzz.py 
Traceback (most recent call last):
  File "./fuzz.py", line 62, in <module>
    session = frida.attach(pid)
  File "/home/raj/.local/lib/python3.8/site-packages/frida/__init__.py", line 62, in attach
    return get_local_device().attach(target, **kwargs)
  File "/home/raj/.local/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/home/raj/.local/lib/python3.8/site-packages/frida/core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.NotSupportedError: unexpected error while attaching to process with pid 634 (PTRACE_SEIZE returned 'Invalid argument')
