### ISSUE TITLE
Problems Concerning sshd service

### ISSUE THREAD

**Issue by dingyx99** [Microsoft/WSL#3032]
This is not a issue of **bug**.
Cause I'm not able to open `ubuntu` or `bash` in XShell directly(It reported `Command Not Found`, even if I type `powershell` to enter Powershell instead of its build-in shell),so I tried to use SSH in XShell.
However, when I close the Command Promopt, the sshd-sevice kills together.
So if there's a way to keep sshd service at the background?
Or if there's a way to use WSL directly in XShell?
(Maybe I should report this issue to XShell too 😂)
Version: Windows 10 16299.309,XShell 5 (Build 1339)

**Comment by therealkenc** [comment]
> Windows 10 16299.309

That's prior to [17046](Windows 10 16299.309) "Allow processes to run without an active terminal". #709 et al.
