### ISSUE TITLE
Allow WSL programs through firewall

### ISSUE THREAD

**Issue by coolreader18** [Microsoft/WSL#3033]
I've been looking for an answer to this for a bit, and I've come upon a few things, #2064, https://stackoverflow.com/questions/43808089/add-wsl-to-windows-firewall, but they didn't really answer my question. Basically, is there a way that you can whitelist any inbound network traffic through to a WSL program? Yeah, you can do it with opening a single port, but is there any way to enable it for all of bash/WSL? Whitelisting C:\Windows\System32\bash.exe doesn't work, is there some other program or another method to allow this?

**Comment by therealkenc** [comment]
#1852 ([message](https://github.com/Microsoft/WSL/issues/1852#issuecomment-371605730)).

**Comment by coolreader18** [comment]
Alright, thank you.
