### ISSUE TITLE
file corruption for vfat usb drives mounted under drvfs

### ISSUE THREAD

**Issue by HinTak** [microsoft/WSL#3037]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I did

sudo mount -t drvfs F: /mnt/f

to mount a USB drive formatted with fat, to make it accessible under WSL. 

* What's wrong / what should be happening instead:

after using it for a few days, I found three files are corrupted on it. One is generated by simply

cp <elsewhere> /mnt/f

the other two are both with imagemagick's convert:

convert a.png /mnt/f/a.eps
convert b.png /mnt/f/b.eps

unfortunately I don't have an exact recipe for reproducing it. I started to umount under WSL then eject under windows properly before I shut down these days, to avoid seeing this problem again.

I only noticed the problem as the generated eps's causes ghostscript's ps2pdf to choke, after inclusion in a latex document. 

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

I don't have one.

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by HinTak** [comment]
I should also mention that the files are not truncated - it looks like a few k in the middle are corrupted in all 3 cases. In particular, the pdf opens fine except for two slides in 82 pages. (41, 42 or something, so logically in the middle - but in any case, the xref at the end with file offsets are okay).

**Comment by HinTak** [comment]
In the case of the pdf I had the original to compare with. The eps were generated, but 2nd try are largely the same except a block in the middle.

**Comment by HinTak** [comment]
Found 5 files broken in total. two of them were generated directly on the thumb drive; the other 3 copied from a tar ball extracted to /tmp (i.e. ntfs underneath).

6331134 size CaptureFV2.eps, broken in  4868045 - 4865998 - almost exactly 2k
8736111 size otvo_fig2.eps,  broken in 2751497 - 2752498 , 2755592  - 2756606, 8602632 - 8603644 - 3 1k blocks
2922695 Screenshot-from-2016-04-04-02-18-57.eps, 1456131- 1458155 - 2k
2116797 Screenshot-from-2016-04-04-23-56-42.eps, 691218 - 692219 - 1k
3250484 Screenshot-from-2016-04-05-00-10-43.eps, 832514 - 833534 - 1k

**Comment by HinTak** [comment]
Found another 5 files corrupted, which I am fairly sure they were not when the drive was unplugged from my Linux machine last night. I was using them last night - read-only, eps files inserted into a ps file before ps2pdf - if they were corrupted last night, ghostscript would have got confused and choked.

Also found another file which has gone corrupted at some point. It was simply

```
cp /mnt/c/Windows/Fonts/msmincho.ttc /mnt/f
```

I have been using it to get some bitmaps of some glyphs and don't notice it has gone corrupted until I compare the md5sum with the original.

This is a bit worrying as it basically makes it impossible to work on the same files (on the USB drive) between two different machines, one running WSL and the other Linux. Files get corrupted somehow and so far there is not pattern.

All the files which have gone corrupted are basically generated or copied one-off onto the drive and then used read-only afterwards. They somehow get corrupted.

**Comment by HinTak** [comment]
I am completely baffled by this bug. Last night, I copied back all the original versions of eps's onto my USB drive from Linux. Then just do an in-place tar to tar the version of the files on the usb drive all up, and put an md5sum of the tar ball next to it also.

So the tar ball survives re-plugging into windows 10. But two of the eps files have gone corrupted again.

one of the corrupted files is  662802 in size, 563209 - 564202 got corrupted. The other is size 3063679 and corrupted between 2128903 - 2129920 .

The curious thing is that the tar ball is written by tar'ing up the files on the drive itself. So the two files were definitely okay when the drive was unplugged from Linux last night.

This problem is making copying files between Linux boxes and WSL undo'able. ...

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
