### ISSUE TITLE
Gnumeric has rounding issues in WSL/ubuntu

### ISSUE THREAD

**Issue by parrenin** [Microsoft/WSL#3044]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [version 10.0.16299.125]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I am using the Gnumeric spreadsheet and there are some rounding issues which are not seen in a standard ubuntu.
See this bug filled with respect to Gnumeric:
https://bugzilla.gnome.org/show_bug.cgi?id=794515

* What's wrong / what should be happening instead:
There should not be any rounding issues.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
This is likely #830.

**Comment by therealkenc** [comment]
Can't be much else _assuming_ "pure debian 9" userspace (per Gnumeric tracker) is truly identical to WSL userspace. Duping out of it's misery unless someone actually wants to run Gnumeric under `gdb` and identify a diverge. If #830 flips status and the problem persists, do re-file. Recompiling gnumeric with the `_FPU_SETCW()` work-around placed judiciously might work.
