### ISSUE TITLE
Moving a file with `mv` between /mnt/c and ubuntu makes it invisible

### ISSUE THREAD

**Issue by BookOfGreg** [Microsoft/WSL#3045]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```bash
cd /mnt/c/source
touch foo
mv foo ~/foo
mv ~/foo .
```
Foo becomes invisible to the File Explorer, and will not show in `ls -al` but it does exist and can be MV'ed, RM'ed etc.

* What's wrong / what should be happening instead:
I should be able to see my files from WSL or Windows explorer

**Comment by benhillis** [comment]
I'm not able to reproduce this.

**Comment by BookOfGreg** [comment]
Shortly after this, my Ubuntu would not load the terminal, then would not uninstall.
From there I disabled WSL, deleted the canonical directory from Packaged by hand, and reinstalled it, and I can no longer replicate this.
If it happens again I'll re-open this.
Thanks.

**Comment by mikemasam** [comment]
happened to me today, i had to rewrite the whole file, which was readme.md , now i have to commit and piush every time i save a file, i loosing trust.
