### ISSUE TITLE
Ctrl-] (ASCII 29 dec.) cannot be generated by WSL console using german keyboard

### ISSUE THREAD

**Issue by mc-hof** [Microsoft/WSL#3047]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:  I am using Ubuntu on WSL. I have to use a monitor program belonging to the Espressif ESP-IDF development system. The Monitor is invoked on the command line by "make monitor" and it should be terminated by entering the key combination Ctrl-]. On the german Keyboard, the ] character is generated by pressing AltGr-9. So, Ctrl-] should be generated by pressing Ctrl-AltGr-9. But it isn't.

* What's wrong / what should be happening instead:
Instead, Ctrl-] (ASCII 29 dec.) should be generated by the console and as a result the Monitor program should terminate.

I analyzed the issue further using the standard Linux program "showkey". When I start "showkey -a" and enter the key combination Ctrl-AltGr-9 on the german Keyboard, the console generates ] (ASCII 93 dec.) instead of the expected Ctrl-] (ASCII 29 dec.).
If instead I press Ctrl and the key which generates ] on american Keyboards (the key left to the Enter key), the console generates Ctrl-].

BTW the same holds true for Ctrl-[ and Ctrl-\ and maybe other keys.

This bug may be related to bug #728 "can not use ctrl+/ (undo) in bash".

**Comment by heldchen** [comment]
seems to be all keyboards that do not have a dedicated `]` key. I'm getting `]        93 0135 0x5d`  (keys `ctr`+`altgr`+`¨`) on a swiss-german keyboard on 6299.309, too. this applies to both console connection as well as ssh connections tho...

**Comment by morgan-greywolf** [comment]
Have you tried using wsltty? It’s based on the PuTTY code and I suspect it will work better there than in the native console.
