### ISSUE TITLE
WSL appears to leak memory in a way that even after exiting, the memory is not recoverable by Windows.

### ISSUE THREAD

**Issue by nernst** [Microsoft/WSL#3049]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I was attempting to build a moderately sized C++ project using make/autotools

* What's wrong / what should be happening instead:
While attempting to build, memory appears to be leaking at an alarming rate. At the time I'm writing this issue, I've completely frozen my PC twice today.  The build takes a lot of memory - each instance cc1plus may hit between 600-800 MB before it's done. Parallelizing the build (e.g. make -j8) exacerbates the problem.

On my 3rd attempt at this build, I kept an eye on task manager and killed the build when memory usage hit ~95%. At this point, I killed make (via SIGINT), and exited bash, expecting memory usage to return to the baseline of ~20% utilized.  I have 16 GB of RAM, so parallelizing by 8 shouldn't put too much memory pressure - and it doesn't on an actual linux box of similar specs.

It appears WSL is leaking memory in a way that Windows cannot reclaim it, even after the last bash session is closed.  I cannot even see what is consuming the memory in Task Manager. As I write this (from a separate PC), the largest program across all users is only using ~66.5 MB

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
Not applicable here, I don't think. I can produce one, if desired.

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Are you running McAfee?

**Comment by nernst** [comment]
Yes...McAfee Enterprise.

**Comment by therealkenc** [comment]
#2917

**Comment by nernst** [comment]
Erg. Sorry, I promise I did search for similar, but I didn't suspect McAfee, so didn't include it in my search.

**Comment by nernst** [comment]
Also, thanks for the quick response.
