### ISSUE TITLE
fish not working on WSL with blank output

### ISSUE THREAD

**Issue by gyroknight** [Microsoft/WSL#3050]
Having trouble with fish on the latest Windows 10 Pro Insider Preview. Trying to run it causes nothing to be rendered; text can be still entered into the prompt but nothing else is shown.

Steps to reproduce:

* Have at least Insider build 17127

* Install any distro of Linux on WSL (tried with both Ubuntu and openSUSE)

* Install any version of fish 2.2+ (tried the default fish 2.2.0 xenial package on Ubuntu, 2.7.1 on both openSUSE and Ubuntu, and compiling 3 directly from source, all same result)

* run fish

Here's an example of fish's output:
![fish](https://user-images.githubusercontent.com/8902299/37871983-bac0936c-2fca-11e8-89f4-94524e46cb46.PNG)

I've also tried a fresh install of 10 Insider build 17115, fish works as expected there. Once I upgraded it to 17127, it stopped displaying properly. strace gave me nothing useful, only a blank file. Not sure if this is related, but I also can't terminate any instances, both fish and strace with fish once they're started. I've tried:

* killall fish

* Task Manager (click End task > End process seems to have no effect)

* taskkill /im fish /f in Admin CMD (gives Access is denied error for processes)

**Comment by therealkenc** [comment]
> build 17127

This is likely related to #3034 and #3039 like the one below you.

**Comment by gyroknight** [comment]
The unkillable processes definitely looks similar to those issues; I was getting high CPU usage as well. Are the rendering issues related as well?

**Comment by mqudsi** [comment]
Yeah, it's #3036 which first manifested when I was trying to get fish working under 1723.
@gyroknight roll back to 1720.
