### ISSUE TITLE
Unable to build webOS Open Source Edition

### ISSUE THREAD

**Issue by kITerE** [microsoft/WSL#3051]
* Windows build number:  10.0.16299.309 (AMD64)

* What you're doing and what's happening:  [Building webos-image-devel](http://webosose.org/discover/setting/building-webos-ose//#building_webos-image-devel)

`ar@<machine>:~/build-webos$ bitbake webos-image-devel`

* What's wrong:
`
Exception: subprocess.CalledProcessError: Command 'cp -afl --preserve=xattr ./* /home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split' returned non-zero exit status 1
`

`
Subprocess output:
cp: cannot create hard link â€˜/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/glibc-binary-localedata-ks-in/usr/lib/locale/ks_IN/LC_MEASUREMENTâ€™ to â€˜./glibc-binary-localedata-ks-in/usr/lib/locale/ks_IN/LC_MEASUREMENTâ€™: Invalid argument
cp: cannot create hard link â€˜/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/glibc-binary-localedata-ks-in+devanagari/usr/lib/locale/ks_IN@devanagari/LC_MEASUREMENTâ€™ to â€˜./glibc-binary-localedata-ks-in+devanagari/usr/lib/locale/ks_IN@devanagari/LC_MEASUREMENTâ€™: Invalid argument
<...>
`

[Full log file](https://gist.github.com/kITerE/b5aec343bdb2b8b17db4326a9526820a)

* Strace of the failing command, if applicable:  
`
ar@<machine>:~/build-webos$ cd /home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/glibc-binary-localedata-ks-in/usr/lib/locale/ks_IN/
ar@<machine>:~/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/glibc-binary-localedata-ks-in/usr/lib/locale/ks_IN$ strace -o cp.strace -f cp -afl --preserve=xattr ./* /home/ar/build-w
ebos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-splitttttttttttt
cp: cannot create hard link ‘/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/LC_PAPER’ to ‘./LC_PAPER’: Invalid argument
`

[cp.strace](https://gist.github.com/kITerE/7f2faef3869ff096745dfb4a6b16e06b)

**Comment by therealkenc** [comment]
You don't have repro steps leading up to `bitbake webos-image-devel`, but anyway:
```
17788 getxattr("./LC_MESSAGES", "system.posix_acl_access", 0x7ffff0bdcac0, 132) = -1 EOPNOTSUPP (Operation not supported)
17788 setxattr("/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/LC_MESSAGES", "system.posix_acl_access", "\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff", 28, 0) = -1 EOPNOTSUPP (Operation not supported)
```
That's a bad start, because WSL does not support "`system.posix_acl_access`". That much is dupe #2750.

But the fatal is:
```
17788 lstat("/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/LC_PAPER", 0x7ffff0bdcdf0) = -1 ENOENT (No such file or directory)
17788 lstat("/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/LC_PAPER", 0x7ffff0bdcf10) = -1 ENOENT (No such file or directory)
17788 linkat(AT_FDCWD, "./LC_PAPER", AT_FDCWD, "/home/ar/build-webos/BUILD/work/cortexa7hf-neon-vfpv4-webos-linux-gnueabi/glibc-locale/2.24-r0/sstate-build-package/packages-split/LC_PAPER", 0) = -1 EINVAL (Invalid argument)
```

The `EINVAL` seems pretty weird. An `ENOENT` I would understand, but there aren't any invalid arguments I can see on that `linkat()`. `AT_FDCWD` is supported.

[Ref #2665 because webOS]
