### ISSUE TITLE
WSL hangs when running configure scripts generated by autoconf

### ISSUE THREAD

**Issue by mxalbert1996** [Microsoft/WSL#3052]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17128.1
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
![2018-03-25](https://user-images.githubusercontent.com/9391933/37874302-732244f2-305f-11e8-807c-1e18d8a31a5b.png)
Every time I run configure scripts generated by autoconf, it hangs at "checking whether make sets $(MAKE)..." with a relatively high CPU usage (~20% on my i7-7700HQ). The `bash` process cannot be terminated even in Task Manager. Only restarting works.
* What's wrong / what should be happening instead:
Scipts run without problem.
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
None

By the way this problem didn't exist before 17120 (and I'm not sure what the first bad build exactly is).

**Comment by therealkenc** [comment]
> 10.0.17128.1

This is likely related to #3034 and #3039. Fix won't be until at least 17131 or better.
