### ISSUE TITLE
Ubuntu Subsystem for Windows Traffic control (tc) Commands do not Execute

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/WSL#3055]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.334]

* What you're doing and what's happening:
Run the following command `tc qdisc show`

* What's wrong / what should be happening instead:
The command hangs and never executed.

[tc.strace gist here](https://gist.github.com/Jonatino/f49bac5ff75a35e724e1558214f25a7e)

Currently causing an issue with flent on Windows Linux Subsystems: https://github.com/tohojo/flent/issues/130

**Comment by therealkenc** [comment]
#2026.

**Comment by chenyang399** [comment]
how to fix it?
