### ISSUE TITLE
Why did ss report errors?

### ISSUE THREAD

**Issue by cdxdpeng** [Microsoft/WSL#3056]
root@MY20171111:~# ss
Netid  State      Recv-Q Send-Q          Local Address:Port                           Peer Address:Port
Cannot open netlink socket: Protocol not supported
Cannot open netlink socket: Protocol not supported
Cannot open netlink socket: Protocol not supported
Cannot open netlink socket: Protocol not supported

**Comment by therealkenc** [comment]
#2249
