### ISSUE TITLE
NASM in Ubuntu

### ISSUE THREAD

**Issue by Anding** [Microsoft/WSL#3057]
```
$ sudo apt-get install nasm
```
works fine in the Ubuntu VM, but in WSL 
```
$ sudo apt-get install nasm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nasm
```
I'm a novice at Linux, so it may well be my error

**Comment by therealkenc** [comment]
Probably just missing `sudo apt-get update`

**Comment by Anding** [comment]
Thank you, that has fixed it.  Sorry for the distraction...
