### ISSUE TITLE
BSOD on dist-upgrade

### ISSUE THREAD

**Issue by jstelzer** [Microsoft/WSL#3060]
* Your Windows build number:  10.0.16299.248

* What you're doing and what's happening:  fresh ubuntu 10.04.4 LTS install. Initial "apt-get dist-upgrade" 

* What's wrong / what should be happening instead: Dist upgrade fails part way through package instalation due to blue screen. Upon reboot, I'm left in a state where it wants me to run "dpkg --configure -a" to complete the upgrade, but that just causes BSOD. Additionally some linux filesystem corruption is occuring. First time I lost my $HOME, second time the dpkg info under /var was corrupted. Removed linux, tried again. Can't dist-upgrade.

* Strace of the failing command, if applicable: BSOD makes this impractical

I suspect it's my antivirus software (sophos 10.7) doing the wrong thing as it monitors disk IO. But that's a guess. Minidump for this issue forthcoming.

**Comment by jstelzer** [comment]
I had our IT staff remove our sophos AV with the provision that the laptop doesn't leave the building. The problem went away. It's either a bug in our profile, or the AV software itself. All we're doing is using the AV to enforce that drives are encrypted via bitlocker. The working suspicion is that this is a bug with the policy. We'll contact the vendor and work through it.

**Comment by sundhaug92** [comment]
Strange. What error-code are you getting?

**Comment by omgftw** [comment]
I can confirm the issue is Sophos. I was having the same issues until uninstalling it.

Minidump shows the crash was caused by lcencvm.sys

**Comment by sundhaug92** [comment]
@benhillis @-ed them on twitter, with link to this thread

**Comment by sundhaug92** [comment]
Sophos looking into it https://twitter.com/SophosSupport/status/981208216552996864

**Comment by wkbrd** [comment]
I have experienced a different BSOD related to lcencvm.sys.  I updated to Sophos SafeGuard Client version 8.0.4.8 (which delivers that file) and the problem did not resolve.  If anybody would like me to provide any details, please let me know.  I wrote this up as WSL GitHub issue #3168 and provided a bugcheck to secure@microsoft.com.  Thanks!

**Comment by eliuha** [comment]
I am facing this issue and I don't have sophos, but SEP and ideas ?

**Comment by benhillis** [comment]
Forward the memory dump to secure@microsoft.com and we can take a look.

**Comment by eliuha** [comment]
The dump file is 1.3Gb, I am not sure that you need all of this, and it will be hard for me for send it via email. Can you suggest something ?

**Comment by sundhaug92** [comment]
@eliuha I think their inboxes can take quite big files but 1.3 Gb might be a bit much. Got a minidump (should be ~1 MB) or something? Alternatively, setting the dump-type to "small memory dump" should give you something mail-able.

**Comment by wkbrd** [comment]
If you are still experiencing this problem, please try installing an updated Sophos SafeGuard Client, version 8.10 or newer.  The latest version appears to have fixed this issue.
