### ISSUE TITLE
Performing operations on files that do not exist, successfully.

### ISSUE THREAD

**Issue by mikabre** [Microsoft/WSL#3061]
* **Your Windows build number:**  Microsoft Windows [Version 10.0.16299.309]

* **What you're doing and what's happening:** 
Create a directory anywhere using Bash or Windows Explorer (for this example I will use /mnt/c/Users/testuser/testdir) with any number of files in it (for this example I will use 1.txt, 2.txt, and 3.txt)
Create a new directory to the same parent as testdir, naming it 'testdir2' using Bash or Windows Explorer.
In Bash, navigate to /mnt/c/Users/testuser/testdir
In Windows Explorer, navigate to C:\Users\testuser
In Windows Explorer, delete testdir.
In Windows Explorer, rename testdir2 to testdir.
In Bash, without entering other commands, enter 'ls'
The output will be: 1.txt 2.txt 3.txt

* **What's wrong / what should be happening instead:**
The output of the ls command is incorrect. It should either display the correct information, or fail.

Additional notes: Until you navigate away from the testdir folder, you can perform any operations on these deleted files, including cat, grep, and others.

**Comment by therealkenc** [comment]
Deleting a file in explorer doesn't delete the file. It moves the file to the trash.

**Comment by mikabre** [comment]
**Revising the reproduction instructions to not include any deletion produces the same results.**
@therealkenc 

Create a directory anywhere using Bash or Windows Explorer (for this example I will use /mnt/c/Users/testuser/testdir) with any number of files in it (for this example I will use 1.txt, 2.txt, and 3.txt)
Create a new directory to the same parent as testdir, naming it 'testdir2' using Bash or Windows Explorer.
In Bash, navigate to /mnt/c/Users/testuser/testdir
In Windows Explorer, navigate to C:\Users\testuser
In Windows Explorer, rename testdir to testdir3.
In Windows Explorer, rename testdir2 to testdir.
In Bash, without entering other commands, enter 'ls'
The output will be: 1.txt 2.txt 3.txt

Expected output is a zero length string.

**Comment by therealkenc** [comment]
> Expected output is a zero length string.

No, it isn't. You still have the original testdir inode as your PWD. The new testdir (renamed from testdir2) is a different inode with the same name.

That enough for today. I you believe you have found a diverge in [rename(2)](http://man7.org/linux/man-pages/man2/rename.2.html) or [rmdir(2)[(http://man7.org/linux/man-pages/man2/rmdir.2.html) try the scenario under Real Linux in a VM first, and post the repro steps as CLI commands (mkdir, touch, mv) following CONTRIBUTING.md. You can use interop under WSL for the windows side.
