### ISSUE TITLE
Cannot change case of file in NTFS or Fat32 formatted drives

### ISSUE THREAD

**Issue by lilggamegenius** [Microsoft/WSL#3065]
Build: Microsoft Windows [Version 10.0.17128.1]

If you try to rename a file or directory on NTFS or Fat devices with mv, the command will fail claiming its the same file.
For example:
```console
$ touch Foo
$ mv Foo foo
mv: 'Foo' and 'foo' are the same file
```
This also affects folders too.
```console
$ mkdir Foo
$ mv Foo foo
mv: cannot move 'Foo' to a subdirectory of itself, 'foo/Foo'
```
This seems like a file system issue though as cygwin has this problem too.

**Comment by therealkenc** [comment]
Blog post is [here](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/).
