### ISSUE TITLE
Symlinked ~/.ssh folder - cannot change permissions

### ISSUE THREAD

**Issue by timelf123** [Microsoft/WSL#3067]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening: 
`ln -s /mnt/c/Users/Tim/.ssh ~/.ssh`
`sudo chown tim:tim -R ~/.ssh/*`
```
ls -la /mnt/c/Users/Tim/.ssh/
drwxrwxrwx 0 root root   512 Mar 28 09:58 .
drwxrwxrwx 0 root root   512 Mar 26 15:41 ..
-rwxrwxrwx 1 root root  1034 Mar 16 12:00 config
```

Ssh reports: `Bad owner or permissions on /home/tim/.ssh/config`

* What's wrong / what should be happening instead:
Permissions should be changing

**Comment by therealkenc** [comment]
> [Version 10.0.16299.248]

You want the metadata option added in 17063. #81

**Comment by timelf123** [comment]
Thank you
