### ISSUE TITLE
Registering sigaction on SIGCONT causes a bug in stdout

### ISSUE THREAD

**Issue by duvni** [Microsoft/WSL#3068]
I have two programs, the first one called child is supposed to register a handle for SIGCONT, print a message, stop itself, and wait for someone to start it, then print another message and exit.
The code for child.c is:

```
#include <stdio.h>
#include <signal.h>
#include <string.h>

void continue_handler(int signal, siginfo_t* info, void* pointer){
    printf("Process continues, called by: %lu\n", (unsigned long) info->si_pid);
}

int main() {
    struct sigaction continue_action;
    memset(&continue_action, 0, sizeof(continue_action));
    continue_action.sa_sigaction = continue_handler;
    continue_action.sa_flags=SA_SIGINFO;

    if (sigaction(SIGCONT, &continue_action, NULL) == -1) {
        perror("Failed registering handle");
	return 1;
    }

    printf("Child about to stop\n");
    raise(SIGSTOP);
    printf("Child woke up\n");
	
    return 0;
}
```

The second program will execute child (in a separate process), wait a second for it to stop, and then signal it to continue with SIGCONT
The code for parent.c:

```
#include <stdio.h>
#include <unistd.h>
#include <sys/wait.h>

int main() {
    int child_pid = fork();
    if (child_pid == 0) {
        // Child
        char *arguments[] = { "./child", NULL };
        if (execvp("./child", arguments) == -1) {
            perror("failed executing child");
            return 1;
        }
    }
	
    // Parent
    // Wait for child to stop
    sleep(1);

    // Continue child process
    kill(child_pid, SIGCONT);
    waitpid(child_pid, NULL, 0);

    return 0;
}
```

When executing parent, the out is:

_Child about to stop
Child woke up
Child woke up
Process continues, called by: 210_

Note that "Child woke up" is printed twice, this should never happen and indicates some buffering issue in the kernel code.

Also note that the parent is not necessary here, I just used it for convenience, you can also just execute the child process and manually continue the process with something like
kill -SIGCONT [pid]
And the double "Child woke up" will be printed as well.

My windows build number is:
10.0.16299.334

**Comment by therealkenc** [comment]
Can't prove it, but I think there is some `tmux` heisenbugs because of this one. Maybe motivating.

**Comment by Brian-Perkins** [comment]
This is an issue with the delivery of SIGCONT and resuming of the thread. The SIGCONT signal should arrive before the thread starts running again, but currently this is not always the case. The double prints are an artifact of getting the signal while in the write() call of the printf. I didn't look through the glibc code but I suspect the assumption is that there is just unflushed data and the second printf appends to it. In reality of course the write() triggered by the first printf was already processed -- it just hasn't returned yet.

**Comment by Gabrielcarvfer** [comment]
Seems fixed in 17713.

**Comment by therealkenc** [comment]
Nothing discernible in the release notes but when it works it works...
