### ISSUE TITLE
Solr process hangs WSL

### ISSUE THREAD

**Issue by eiva** [microsoft/WSL#3070]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Solr freezing in a way that it could not be killed except reboot, when a lot of network traffic is generated (in example loading data). The same is not reproducible on 4 versions of real Linux I tested.

To reproduce:
- In first bash
0. `sudo apt-get install default-jre`
1. Download latest solr i.e. http://apache.claz.org/lucene/solr/7.2.1/solr-7.2.1.tgz
2. Unpack, create default core with default config and simple schema:
```xml
....
<uniqueKey>id</uniqueKey>
<field name="id" type="tlong" multiValued="false" indexed="true" required="true" stored="true"/>
<field name="_version_" type="long" indexed="true" stored="true"/>
<field name="start" type="tint" multiValued="false" indexed="true" required="true" stored="true"/>
<field name="data" type="pint" multiValued="false" indexed="true" required="true" stored="true"/>
```
- In second bash
3. Use bulk load
```python
import requests
import json
from random import randint, choice

url = 'http://localhost:3088/solr/test/'

__solr_headers = {
            'Content-type': 'application/json',
            'Accept': 'application/json'}

def insert(doc):
    insert_url = url + 'update/json/docs'

    r = requests.post(insert_url, data=doc, headers=__solr_headers)

    if r.status_code != 200:
        raise Exception("Failed", r.status_code, r.content.decode('utf-8'))

doc_str = ""
for id in range(1, 25000000):

    doc = {
        'id': id,
        'start': randint(0,250000000),
        'data': randint(0, 3000000000) }
    
    doc_str += json.dumps(doc) + '\n'
    
    if id % 100000 == 0:  # As bigger this number as faster you will see freezing
        print('Dumping:', id)
        insert(doc_str)
        doc_str = ""
        print('Done')  # In most cases you will never see this.
```

Wait for a really short time and solr (on first bash) will permanently stuck in a way as it could not be killed: I could close bash window, but there few possible cases:
1. Solrs process 'java' will be visible in task lists and could not be killed.
2. Process will not be visible. Port is still in use.
3. Same as 1 or 2 and when you try to run another 'bash' it will stuck on loading.
    In this case on reboot system will fail to *BSOD*

Some notes:
- I facing this bug since the beta of WSL and it happening "always" I'm trying to make "serious load on solr".
- Once I run into same situation with "influxDB" but didn't tried to reproduce it.

P.S.
It is really easy to say that it is a solr of java bug, but I don't think so: as I told I've tested same code on *much more complex* schemas intensively loading files ~ 1TB on CentOS and on Ubuntu - on different versions of solr - and I had never see this...
[solrconfig.zip](https://github.com/Microsoft/WSL/files/1866064/solrconfig.zip)

**Comment by sundhaug92** [comment]
Interesting. Do you have a trace?

**Comment by eiva** [comment]
Curious:
Just tried to use `strace` to grab trace of freezed java process and this lead to hanged strace...
More curious that when I lunched solr under `strace`  bug didn't reproduce... Will try to run it further and will see.

**Comment by stevenao** [comment]
i too face the same problem with running aws's dynamodb-local (which is java program using sql-lite). It wasn't under heavy load at all. It was just doing some small data seeding and light read and write.

**Comment by sunilmut** [comment]
Are you able to kill the `hung` strace process? That might be sufficient. The idea is to see which syscall is hanging, which is usually the case.

**Comment by stevenao** [comment]
i am not familiar with the `strace` tool. My experience is that once the app becomes unresponsive. It can't be killed and I can't even restart WSL/bash.

**Comment by eiva** [comment]
Same for me: when it freezes it is not possible to open another WSL window.
But even when I open 2 windows before strace don't work: it just freezes until you terminate it and shows nothing.
When I'm running the app under strace problem not reproducing.
I've tried to use Process Explorer to see stack traces, but result not looking good.

**Comment by daneelgiskard** [comment]
Just to chime in to say I have the same issue with Solr (Rails Sunspot gem in my case). I need to reboot my computer to get WSL working again.

**Comment by eiva** [comment]
Yes the problem is still reproducible - it looks like some kernel or WSL internals problem - debgging does not work, process is unkillable.

**Comment by BryanJin** [comment]
I met the same problem and struggled for weeks.

**Comment by BryanJin** [comment]
upgrade to WSL2 will fix this problem
