### ISSUE TITLE
terminal print cannot allocate memory when i sync google chromium source code

### ISSUE THREAD

**Issue by CaiHuan** [Microsoft/WSL#3072]
windows_version:Microsoft Windows [Version 10.0.16299.334]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:   xenial

typing command gclient sync --reset --with_branch_heads the terminal print
Running hooks:  50% (27/54) luci-go_linux
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-luci -d src/tools/luci-go/linux64' in '/mnt/f/android/chromium'
panic: failed to execve "/home/daniel/.vpython-root/758a9e/bin/python": cannot allocate memory

free command show subsytem memory 3.2G~can i make the memory larger?
daniel@DESKTOP-7K3VVG7:/mnt/f/android/chromium/src$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32645       14634       17780          17         230       17873
Swap:         29738         307       29431

**Comment by therealkenc** [comment]
#2959
