### ISSUE TITLE
/usr/bin/git calling git-credential-manager.exe via pipe hangs.

### ISSUE THREAD

**Issue by notlaforge** [Microsoft/WSL#3078]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.309]

In order to use git both in WSL and in Windows with the same auth credentials, I tried to install https://github.com/Microsoft/Git-Credential-Manager-for-Windows and then point both gits to it.

The way this works is that one adds this to `~/.gitconfig`:

```ini
[credential]
        helper = manager
```

Git will then communicate with `git-credential-$HELPER` via pipe. In my `$PATH` in WSL I have a link to `git-credential-manager.exe` so that `/usr/bin/git` can execute it. When it does run it (say, when I do `git push`) it jugs hangs there.

As a workaround I've replaced the `~/bin/git-credential-manager -> /mnt/c/.../git-credential-manager.exe` symlink with the following shell script:

```bash
#!/bin/sh
tee .git/creds | powershell.exe /c "Start-Process -Wait -FilePath 'C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager.exe' -NoNewWindow -ArgumentList $@ -RedirectStandardInput .git/creds"
rm -f .git/creds
```

This seems to work just fine (at the expense of temporarily keeping the credentials on disk).

I am at a loss as to why the pipe doesn't cross the interop. Help?

Due to the nature of the strace output, I'll send it over to the secure@ address.

**Comment by therealkenc** [comment]
> 16299

That's #2370 #2406 et al. Addressed in [17618](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17618-skip-ahead).
