### ISSUE TITLE
Files with ".magic" extension can't be created

### ISSUE THREAD

**Issue by simonchatts** [Microsoft/WSL#3079]
If I try to create a file named something like `foo.magic` within the WSL file system (eg $HOME or /tmp, not /mnt/c) then it always fails with EACCESS:

```
$ > foo.magi
$ > foo.magics
$ > foo.magik
$ > foo.magic
-bash: foo.magic: Permission denied
```

Strace shows the `open` returns EACCESS, no matter what the directory or user permissions are.

This is Windows 10.0.15063.

**Comment by benhillis** [comment]
I'm not able to reproduce this and 15063 is a rather old build. Is upgrading to a more recent version of Windows an option?

**Comment by simonchatts** [comment]
Not for me unfortunately (this is a corporate machine whose image I don't control).

Since the symptom is so blatant, if you can't repro, then my suspicion is something particular to this machine. From a quick search now I think of it, there does seem to be ransomware associated with this file extension, so it's possible some IT-managed anti-malware is involved.

If nothing else comes to mind, I'll assume it probably isn't WSL's fault, and assume the best course of action is to close this issue tomorrow and take it up with my IT team.

**Comment by therealkenc** [comment]
Touching `foo.magic` is going to be fine in 15063 (or 14393). It is going to be _something_ environmental. Confirm `touch foo` works and `touch foo.moo` works, but not `foo.magic`?

**Comment by simonchatts** [comment]
That's correct. But I've also checked, and I can't create `.magic` files in the regular Windows filesystem outside of WSL either. So probably local anti-malware, but definitely not WSL. Apologies for the noise - thanks for the help!
