### ISSUE TITLE
WSL apt-get upgrade failed with error saying systemd-private-%b-* cannot be replaced

### ISSUE THREAD

**Issue by cpei-avalara** [Microsoft/WSL#3080]
Windows version Microsoft Windows [Version 10.0.16299.125]

Error message

sudo apt-get upgrade
Calculating upgrade... Done
The following packages have been kept back:
  bash
The following packages will be upgraded:
  firefox hdparm icu-devtools libavahi-client3 libavahi-common-data libavahi-common3 libicu-dev libicu57 libplymouth4 libssl1.0.0 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3
  linux-libc-dev lshw openssl plymouth plymouth-theme-ubuntu-text systemd-sysv zsh zsh-common
22 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
6 not fully installed or removed.
Need to get 1,555 kB/76.9 MB of archives.
After this operation, 18.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 hdparm amd64 9.51+ds-1ubuntu0.1 [94.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 libplymouth4 amd64 0.9.2-3ubuntu18 [85.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 lshw amd64 02.18-0.1ubuntu4.1 [231 kB]
Get:4 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 plymouth amd64 0.9.2-3ubuntu18 [108 kB]
Get:5 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 plymouth-theme-ubuntu-text amd64 0.9.2-3ubuntu18 [8,966 B]
Get:6 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 libavahi-common-data amd64 0.6.32-1ubuntu1.1 [22.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 libavahi-common3 amd64 0.6.32-1ubuntu1.1 [21.6 kB]
Get:8 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 libavahi-client3 amd64 0.6.32-1ubuntu1.1 [25.2 kB]
Get:9 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 linux-libc-dev amd64 4.13.0-38.43 [958 kB]
Fetched 1,555 kB in 7s (202 kB/s)
Preconfiguring packages ...
Setting up systemd (234-2ubuntu12.3) ...
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
[/usr/lib/tmpfiles.d/tmp.conf:15] Failed to replace specifiers: /tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:16] Failed to replace specifiers: /tmp/systemd-private-%b-*/tmp
[/usr/lib/tmpfiles.d/tmp.conf:17] Failed to replace specifiers: /var/tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:18] Failed to replace specifiers: /var/tmp/systemd-private-%b-*/tmp
dpkg: error processing package systemd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by therealkenc** [comment]
> 0.9.2-3ubuntu18 

No, `sudo apt-get upgrade` is not a repro for that. Seriously. 

Duping into one discussion thread for Bionic/Artful. #2960

**Comment by bterrier** [comment]
There is a fix that _will_ be available for this issue.
To get the fix right now, one need to use the _artful-proposed_ repo to get the not-yet-released systemd package.

Please see [my comment](https://github.com/Microsoft/WSL/issues/2960#issuecomment-385110719) in #2960 for more info. I am just posting here, because this issue is easier to find in the search engines.
