### ISSUE TITLE
Kali XFCE connects but then has a problem

### ISSUE THREAD

**Issue by pnelsonsr** [Microsoft/WSL#3082]
Just installed Kali on Windows 10 WSL and updated everything.

Followed the directions [here](https://vimeo.com/255052199) to install XFCE.  All went well.  Here is the problem that happens:

-I start an administrative command prompt and start kali
-I start the xfce service and capture the port number
-I start RDP and put 127.0.0.1:`<captured port number>`
-I get the Kali XFCE login window and enter my credentials
-The login window disappears 
-after a few minutes, I get a connection log window that has the following information:
connection to sesman ip 127.0.0.1 port `<captured port number>`
sesman connect ok
sending login info to session manager, please wait:
login successful for display 10
starting connection
connection problem, giving up
som problem
-I click on OK button (only one in the window)
-I get the Kali XFCE login window again

Did a bunch of searching and tried many things (like turning off firewall and AV) but nothing seems to help this to work.  Any suggestions?

**Comment by pnelsonsr** [comment]
Yes ran
/etc/init.d/xrdp start
I turned off AV and FW when I ran into problems.  I do get the initial login screen so I don't think AV/FW are problems.

Did the exception with no different result.

Will move to #637

**Comment by pnelsonsr** [comment]
@therealkenc what is this a duplicate of?

**Comment by therealkenc** [comment]
Anything desktop related. [`ENOTSUPPORTED`](https://docs.microsoft.com/en-us/windows/wsl/faq) so one place is one place enough. That said, there's a big loophole in this system. Track down the problem with gdb and make a CLI repro. Bonne chance.
