### ISSUE TITLE
Font files created in WSL directory cannot be opened

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#3084]
I'm not sure what exactly happens here, but font files in some directories that have been created from WSL (17133) cannot be opened from within Windows (same machine). The same file, once copied to a new location, can be opened.

I have created a very simple test case (repo is public):

Under WSL:
```fish
~> git clone https://git.neosmart.net/mqudsi/wslbugs wsl_wslbugs
~> cd wsl_wslbugs/fonts/Segoe\ UI/
~> open segoeui.ttf
```

Results in the following:

![image](https://user-images.githubusercontent.com/606923/38472368-99f9dd84-3b44-11e8-8c6f-33969664c13a.png)

> ---------------------------
> Windows Font Viewer 
> ---------------------------
> The requested file C:\Users\Mahmoud\Downloads\wsl_wslbugs\fonts\Segoe UI\segoeui.ttf is not a valid font file. 
> ---------------------------
> OK   
> ---------------------------
> 

Under cmd.exe:
```batch
> git clone https://git.neosmart.net/mqudsi/wslbugs win_wslbugs
> cd win_wslbugs/fonts/"Segoe UI"
> open segoeui.ttf
```

This opens the font file just fine.

Comparing the two files:

```fish
~> openssl sha1 wsl_wslbugs/fonts/Segoe\ UI/segoeui.ttf
SHA1(wsl_wslbugs/fonts/Segoe UI/segoeui.ttf)= 4f56ca88f85051b935da38fae3207c34af3a6fb7
~> openssl sha1 win_wslbugs/fonts/Segoe\ UI/segoeui.ttf
SHA1(win_wslbugs/fonts/Segoe UI/segoeui.ttf)= 4f56ca88f85051b935da38fae3207c34af3a6fb7
```

ok, maybe it's an alternate streams issue:

```batch
> streams.exe -s -d wsl_wslbugs
Copyright (C) 2005-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

```

(no alternate streams detected)

Now for the weird part:

```fish
~> cd wsl_wslbugs/fonts/Segoe\ UI/
~> cp segoeui.ttf ./wsl_segoeui.ttf
~> open wsl_segoeui.ttf
~> # error about invalid font file
~> # maybe try copying it to a path that doesn't contain spaces?
~> cp ./wsl_segoeui.ttf ../
~> cd ../
~> open ./wsl_segoeui.ttf
~> # error about invalid font file in this space-free path
~> cp ./wsl_segoeui.ttf ../
~> cd ../
~> # back in original directory
~> open wsl_segoeui.ttf
```

![image](https://user-images.githubusercontent.com/606923/38472420-6c11cbf6-3b45-11e8-970a-70e8ff9180f1.png)

Directory permissions are the same on both directories:

```fish
~> stat ./
  File: './'
  Size: 512             Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 281474976799494  Links: 1
Access: (0777/drwxrwxrwx)  Uid: ( 1000/  mqudsi)   Gid: ( 1000/  mqudsi)
Access: 2018-04-08 15:59:45.644355500 -0500
Modify: 2018-04-08 15:59:45.644355500 -0500
Change: 2018-04-08 15:59:45.644355500 -0500
 Birth: -
~> stat wsl_wslbugs/fonts/Segoe\ UI/
  File: 'wsl_wslbugs/fonts/Segoe UI/'
  Size: 512             Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 7599824372285175  Links: 1
Access: (0777/drwxrwxrwx)  Uid: ( 1000/  mqudsi)   Gid: ( 1000/  mqudsi)
Access: 2018-04-08 15:59:25.862235300 -0500
Modify: 2018-04-08 15:59:25.862235300 -0500
Change: 2018-04-08 15:59:25.862235300 -0500
 Birth: -
```

![image](https://user-images.githubusercontent.com/606923/38472510-9e2685ae-3b46-11e8-8d29-337f99f9d45c.png)

**Comment by therealkenc** [comment]
Wild Ass Guess, but check `fsutil.exe file queryCaseSensitiveInfo` on the working and nonworking directories. Start from scratch, deleting the directories in question and running the `fsutil.exe` command at each step. On WSL, `git` is going to mess with the flag and Windows `git` will not. When you copied that file up one, you copied it to an unadulterated directory. 

This is _just a guess_ though; it could be a goose chase. I didn't try your repro. Your repro says "under cmd.exe ... `open segoeui.ttf`" which doesn't make sense because `open` isn't a Windows command nor a `cmd.exe` shell builtin. Also didn't try because because the per directory case sensitivity flag makes me feel sad inside.

**Comment by mqudsi** [comment]
Sorry, `open` [is this](https://github.com/neosmart/open). You could just double-click the file in question, or else run `start "" TARGET` instead.

**Comment by therealkenc** [comment]
> Sorry, open [is this](https://github.com/neosmart/open).

No worries.

> You could just double-click the file

So, I _just_ (cough) tried that and managed to reproduce your error.

`Fontview.exe iamnotafont.ttf` from `cmd.exe` pops up the same error message. Which is the same as "`No such file or directory`" on `cl.exe`. I also _just_ tried [quoth](https://github.com/Microsoft/WSL/issues/2937#issuecomment-365039374) "re-mounting /mnt/c with -o case=off". 

```
$ sudo umount /mnt/c
$ sudo mount -t drvfs -o metadata,case=off C: /mnt/c
```

Cloned your git repo again. Double-click on the font file from Explorer succeeds. #2937

**Comment by mqudsi** [comment]
Thanks, @therealkenc

**Comment by mqudsi** [comment]
Wait, how did you remount? 

```
mqudsi@ZBook ~> sudo mount -o remount,case=off C: /mnt/c
mount: /mnt/c not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
mqudsi@ZBook ~> sudo umount -f C:
umount: /mnt/c: not mounted
mqudsi@ZBook ~> sudo umount -f /mnt/c
umount: /mnt/c: not mounted
mqudsi@ZBook ~> mount
rootfs on / type lxfs (rw,noatime)
root on /root type lxfs (rw,noatime)
home on /home type lxfs (rw,noatime)
data on /data type lxfs (rw,noatime)
cache on /cache type lxfs (rw,noatime)
mnt on /mnt type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
```

It also doesn't appear in `/etc/fstab` so I can't just add an option and reboot..
