### ISSUE TITLE
/usr/bin/logname do not return proper login name

### ISSUE THREAD

**Issue by rigarash** [Microsoft/WSL#3085]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.334]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
$ /usr/bin/logname
logname: no login name

* What's wrong / what should be happening instead:
$ /usr/bin/logname
rigarash

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
not applicable since the command at least runs smoothly.

**Comment by therealkenc** [comment]
> not applicable since the command at least runs smoothly.

If it was running smoothly you'd get the correct output.

```
open("/proc/self/loginuid", O_RDONLY)   = -1 ENOENT (No such file or directory)
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
readlink("/proc/self/fd/0", "/dev/pts/0", 511) = 10
stat("/dev/pts/0", {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
access("/var/run/utmpx", F_OK)          = -1 ENOENT (No such file or directory)
open("/var/run/utmp", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
access("/var/run/utmpx", F_OK)          = -1 ENOENT (No such file or directory)
open("/var/run/utmp", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Fundamentally dupe #888 and #1761 (no `/var/run/utmp`)
