### ISSUE TITLE
turn down internet connection

### ISSUE THREAD

**Issue by eljuligallego** [Microsoft/WSL#3087]
Hi,
I want to be able to turn down the internet connection of my ubuntu bash for windows while the windows part still has internet.
I tried the ifconfig eth0 down but nothing happens and the command run without any output.
Other commands like nmcli doesn't work.

Any ideas?.
Thanks,
regards

**Comment by Biswa96** [comment]
Block the internet connection with Firewall of that specific binary.

**Comment by therealkenc** [comment]
#2438
