### ISSUE TITLE
Cant not connect J-Link debug probe via USB

### ISSUE THREAD

**Issue by 453jerry** [Microsoft/WSL#3088]
Hi I am try to developing embedded application for ARM Cortex microcontrollers in Ubuntu on Windows.
I use J-Link command tool to access J-Link debug probe to flash the image to the connected hardware.

When I try to run JLinkExe in Ubuntu on Windows, It's pirnt "Connecting to J-Link via USB...FAILED: Cannot connect to J-Link via USB."

![default](https://user-images.githubusercontent.com/15866475/38557450-ad77e7fe-3cff-11e8-9492-193bf2c93812.PNG)

But in Windows the connect is OK

My OS version is : Windows 10 Pro 1709

**Comment by weirdal3333** [comment]
Not only does this fail on his hardware, it fails on ANY hardware. I've tried to use multiple devices through the WSL system, and none of them show up. 
I've tried a USB printer, a Logitech camera, a Movidius NCS, a phone in adb mode, and an Xbox controller.
I also get errors when running several programs saying: `ERROR: Could not get I/O privileges (Function not implemented).`

**Comment by abeck70** [comment]
+1
I come from a seamless OSX based embedded development environment. JLink, Eclipse, gnu arm, makefiles.

I am struggling to achieve this with WSL/Windows

**Comment by Pyponou** [comment]
Does anyone found the solution ?

**Comment by therealkenc** [comment]
Duping #2185 for lack of repro.

**Comment by mike-newhall-juul** [comment]
I am having the same problem.  If you need any proof of a repro to re-open / not re-close this, please let me know. IoT dev is impossible on WSL without it.
