### ISSUE TITLE
Add a argument to specific user in wsl.exe/ubuntu.exe command

### ISSUE THREAD

**Issue by digovc** [Microsoft/WSL#3090]
The cmd command to open the distro allow I config the default user (--default-user user_name), but a argument to specific user in connection would be a good option.

Exemple:

```
C:\>ubuntu my_user_name
$
```

**Comment by therealkenc** [comment]
Or rather `wsl.exe username@distrname [command]`. We can dream.

Anyway, you can do:
```
wsl.exe sudo /bin/login -f [user]
```
If you don't like the password prompt put login in your sudoers. All part in parcel of low-digit issue #352.

**Comment by benhillis** [comment]
This functionality was added in Insider Build [17704](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17704)

**Comment by Biswa96** [comment]
There should be a documentation of the options in wsl.exe and wslconfig.exe.

**Comment by benhillis** [comment]
There is...

```
C:\Users\benhill>wsl --help
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
```

**Comment by Biswa96** [comment]
Not the wsl.exe.mui file. I mean docs.microsoft.com.

**Comment by benhillis** [comment]
@Biswa96 - Those will be updated / added once we ship the next release of Windows.
