### ISSUE TITLE
Bug in timerfd_settime

### ISSUE THREAD

**Issue by TvKorbi** [Microsoft/WSL#3091]
Hello, 
I think most probably we found a bug in the timerfd_settime function.

* Your Windows build number:  Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening: 
Overall I tried to use the boost::deadline timer, which did not behave like they should do. We already were able to boil it down to an easy to reproduce scenario. Take the example code of the documentation of the [ timefd_settime](https://linux.die.net/man/2/timerfd_settime). At the end of this page there is code. When you build and run it you will get different behavior when you run it on the WSL compared to a  Debian. Important is that you have to call this code with the parameter 0 or any negative value.  ( I just tested it on Debian).  On the WSL the program hangs and never returns.

* What's wrong / what should be happening instead:
The program should return. The 0 or negative value should notify the kernel to intermediately fire up the timer event. The problem is, that on the WSL this event will never be fired.  The timerfd_settime function will be called with the Flag TFD_TIMER_ABSTIME with new values of 0,0. On the Debian that will intermediary fire the timer event and the program returns. On WSL it doesn't do that. 
The whole thing can be seen in the attached straces. 

* Strace of the failing command, if applicable: 
Both straces are the result of calling the mentioned [example code](https://linux.die.net/man/2/timerfd_settime) with the parameter 0
## Strace of WSL

> execve("./a.out", ["./a.out", "0"], [/* 19 vars */]) = 0
brk(NULL)                               = 0x7fffc74dd000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ebc730000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=20807, ...}) = 0
mmap(NULL, 20807, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0ebc738000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0ebc030000
mprotect(0x7f0ebc1ef000, 2097152, PROT_NONE) = 0
mmap(0x7f0ebc3ef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f0ebc3ef000
mmap(0x7f0ebc3f5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0ebc3f5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ebc720000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ebc710000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0ebc700000
arch_prctl(ARCH_SET_FS, 0x7f0ebc710700) = 0
mprotect(0x7f0ebc3ef000, 16384, PROT_READ) = 0
mprotect(0x7f0ebca01000, 4096, PROT_READ) = 0
mprotect(0x7f0ebc625000, 4096, PROT_READ) = 0
munmap(0x7f0ebc738000, 20807)           = 0
clock_gettime(CLOCK_REALTIME, {1523426869, 19604000}) = 0
timerfd_create(CLOCK_REALTIME, 0)       = 3
**timerfd_settime(3, TFD_TIMER_ABSTIME, {it_interval={0, 0}, it_value={1523426869, 19604000}}, NULL) = 0**
clock_gettime(CLOCK_MONOTONIC, {433044, 174913000}) = 0
clock_gettime(CLOCK_MONOTONIC, {433044, 175644000}) = 0
fstat(1, {st_mode=S_IFCHR|0640, st_rdev=makedev(4, 2), ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
brk(NULL)                               = 0x7fffc74dd000
brk(0x7fffc74fe000)                     = 0x7fffc74fe000
write(1, "0.001: timer started\n", 210.001: timer started
)  = 21
read(3, ^Cstrace: Process 1148 detached
 <detached ...>

## Strace of the Debian machine

> execve("./a.out",
 ["./a.out", "0"], [/* 54 vars */]) = 0
brk(NULL)                               = 0x5639c484c000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f005040b000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=154676, ...}) = 0
mmap(NULL, 154676, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f00503e5000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\3\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1689360, ...}) = 0
mmap(NULL, 3795360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f004fe4c000
mprotect(0x7f004ffe1000, 2097152, PROT_NONE) = 0
mmap(0x7f00501e1000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x195000) = 0x7f00501e1000
mmap(0x7f00501e7000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f00501e7000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f00503e3000
arch_prctl(ARCH_SET_FS, 0x7f00503e3700) = 0
mprotect(0x7f00501e1000, 16384, PROT_READ) = 0
mprotect(0x5639c2c80000, 4096, PROT_READ) = 0
mprotect(0x7f005040e000, 4096, PROT_READ) = 0
munmap(0x7f00503e5000, 154676)          = 0
timerfd_create(CLOCK_REALTIME, 0)       = 3
**timerfd_settime(3, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=1523426815, tv_nsec=366196294}}, NULL) = 0**
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 25), ...}) = 0
brk(NULL)                               = 0x5639c484c000
brk(0x5639c486d000)                     = 0x5639c486d000
write(1, "0.000: timer started\n", 210.000: timer started
)  = 21
read(3, "\1\0\0\0\0\0\0\0", 8)          = 8
write(1, "0.001: read: 1; total=1\n", 240.001: read: 1; total=1
) = 24
exit_group(0)                           = ?
+++ exited with 0 +++

Thanks for your support. If there are further questions or more details needed, don't hesitate to ask. 

regards 
Korbi

**Comment by benhillis** [comment]
Thanks for filing this.  Looks like a problem with the way our driver handles setting timers with absolute times in the past.  In that case the timer should fire immediately but that isn't happening currently.  I am testing a fix for this now.

**Comment by benhillis** [comment]
This is resolved in 17686.
