### ISSUE TITLE
Q: Best practice for managing links (Boost development use case)

### ISSUE THREAD

**Issue by mloskot** [Microsoft/WSL#3093]
* Your Windows build number: Windows 10 Version 1709 (Build 16299) with latest Ubuntu installed from the Microsoft Store.

**TL;TR:** Shall I `mklink` in Windows or `ln -s` in WSL to get links right for development of a (C/C++) project?

## Goal

I aim to set up for Boost C++ libraries development workflow with support
for building inside both environments, Windows and WSL. Specifically, to target

- Windows building from VS2017 (MSVC) and CLion (MinGW)
- WSL building from VS2017 (GCC) and CLion (GCC) - 

I will maintain separate parallel clonse of Boost git repositoru:

- `d:\boost.win` - for the Windows builds
- `d:\boost.wsl` - for the WSL builds

Although, single source tree might work well, who knows, I feel like it is cleaner and safer way to go.

## Preparation

The Boost [getting started](https://github.com/boostorg/boost/wiki/Getting-Started) shows the following
steps to clone and prepare the Boost source code tree:

```shell
git clone --recursive https://github.com/boostorg/boost.git
cd boost
git checkout develop # or whatever branch you want to use
bootstrap            # ./bootstrap.sh or .\bootstrap.bat, builds b2 program
b2 headers           # fills virtual /boost directory with links to libraries/headers
```

The **interesting part** is the last step: `b2 headers`.

What it does is also explained in the [getting started](https://github.com/boostorg/boost/wiki/Getting-Started):

> /boost sub-directory is now a "virtual" directory, containing links to the headers.
> The command b2 headers creates or recreates the contents of this /boost directory.

So, `b2 header` creates **links** using [mklink or ln -s](https://github.com/boostorg/build/blob/b000980cd3d4ae1760ef226e19c2a121cf11d820/src/tools/link.jam#L273-L291), depending on OS:

```shell
mklink-or-dir boost\numeric\ublas
symbolic link created for boost\numeric\ublas <<===>> ..\..\libs\numeric\ublas\include\boost\numeric\ublas
```

## Questions

Given that `b2 headers` manages the links:

1. Shall I prepare both of the source trees in Windows?

```cmd
d:
cd \

git clone --recursive https://github.com/boostorg/boost.git boost.win
cd boost.win & b2 headers

git clone --recursive https://github.com/boostorg/boost.git boost.wsl
cd boost.wsl & b2 headers
```

2. Or, Shall I prepare the `boost.wsl` tree in WSL?

```cmd
c:\> ubuntu.exe
cd /mnt/d
git clone --recursive https://github.com/boostorg/boost.git boost.wsl
cd boost.wsl & b2 headers
```

3. Which option is best for **using IDE in Windows to cross-platform build, browse code, etc.** in WSL?
Mainly, for [Targeting the Windows Subsystem for Linux from Visual Studio](https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/) based on the VS "Linux development with C++" feature.

-----

If I go for the **option 1.** all the links are correctly visible and resolved for both environments:

- Windows - all good

```cmd
D:\boost.wsl> dir boost
 Volume in drive D is Data
 Volume Serial Number is 1CFA-E5AD

 Directory of D:\boost.wsl\boost

2018-04-08  12:00    <DIR>          .
2018-04-08  12:00    <DIR>          ..
2018-04-08  11:59    <SYMLINKD>     accumulators [..\libs\accumulators\include\boost\accumulators]
2018-04-08  11:59    <SYMLINKD>     algorithm [..\libs\algorithm\include\boost\algorithm]
...

D:\boost.wsl> dir boost\core\
 Volume in drive D is Data
 Volume Serial Number is 1CFA-E5AD

 Directory of d:\boost.wsl\boost\core

2018-04-09  15:25    <DIR>          .
2018-04-09  15:25    <DIR>          ..
2018-04-09  15:25             6,149 addressof.hpp
2018-04-09  15:25             1,588 checked_delete.hpp
...
```

- WSL - all good too

```shell
$ ls -l /mnt/d/boost.wsl/boost
total 0
lrwxrwxrwx 0 root root   0 Apr 8 11:59 accumulators -> ../libs/accumulators/include/boost/accumulators
lrwxrwxrwx 0 root root   0 Apr 8 11:59 algorithm -> ../libs/algorithm/include/boost/algorithm
...

$ ls -1 /mnt/d/boost.wsl/boost/core
addressof.hpp
checked_delete.hpp
...
```

-----

If I go for the **option 2.** then the links created in WSL are `JUNCTIONS`-s visible in the Explorer as flat files (same as in https://github.com/Microsoft/WSL/issues/2898#issuecomment-362511510) and there seem to be problem with accessing them from Windows:

- Windows

```cmd
D:\boost.wsl> dir boost
 Volume in drive D is Data
 Volume Serial Number is 1CFA-E5AD

 Directory of D:\boost.wsl\boost

2018-04-08  12:13    <DIR>          .
2018-04-08  12:13    <DIR>          ..
2018-04-08  12:13    <JUNCTION>     accumulators [...]
2018-04-08  12:13    <JUNCTION>     algorithm [...]


D:\boost.wsl> dir boost\core\
 Volume in drive D is Data
 Volume Serial Number is 1CFA-E5AD

 Directory of d:\boost.wsl\boost\core

File Not Found

D:\boost.wsl> cd boost\core\
The directory name is invalid
```

- WSL - of course, all good as expected

-----

Possibly, those questions are also relevant for use case of git-managed symlinks: `git clone -c core.symlinks=true --recursive ...`.

**Comment by DarthSpock** [comment]
With the upcoming release of SCU, you will be able to launch VS Code from WSL if you want to go down that path noting GUI is still not officially supported. Since MS has done some work for Windows VS Code interop with WSL, I think this will be your best bet. You can even bring up the VS Code CLI for whichever WSL distribution you are working in and works better than the default console at this point in time. Also, should you ever need to reinstall a distro to resolve an issue, having the project stored on Windows side will prevent it from being removed when you uninstall and save you time and effort of backing up your data before hand if it's even possible for you to do so. Also, interop has greatly improved with SCU so I recommend upgrading once it's released. There may still be issues but at that point, an strace would determine where the issue lies and is most likely already known if it's similar to git-managed symlinks. I would check out the [developer blogs](https://blogs.msdn.microsoft.com/commandline/) to see what's new with SCU.

**Comment by mloskot** [comment]
@DarthSpock 
> With the upcoming release of SCU, you will be able to launch VS Code from WSL if you want to go down that path noting GUI is still not officially supported

I do not require running any editor from inside WSL.

I clearly stated I'm aiming at the VS2017, that is the [Targeting the Windows Subsystem for Linux from Visual Studio](https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/), ie. the "Linux development with C++" feature. Although the CLion use case I mentioned is exactly the same, let's forget about CLion to keep the issue foused.

Please, let's forget the VS Code.

**Comment by DarthSpock** [comment]
VS2017 is available for both and I was addressing your number 3 for IDE. Sorry for providing a tidbit that may or may not be useful to you. There are many things in the blogs that could prove useful to your case. For example, with symlinks, there is much improved support such as / vs \ not being a factor. Another is Linux permissions being preserved on Windows from WSL. Case sensitivity on a per directory level is also available. 

So shorter answer, which I probably should of done in first place:

> Shall I prepare both of the source trees in Windows?

Yes

`Or, Shall I prepare the boost.wsl tree in WSL?`

No, and I was trying explain benefits of 1 vice 2 in less-technical terms. I won't make that mistake again.

> If I go for the option 2. then the links created in WSL are JUNCTIONS-s visible in the Explorer as flat files 

Per the referenced issue: 

> It seems to work if you have a recent Insiders version and developer mode activated. 

SCU contains all fixes and features from Insiders obviously so therefore as stated above, upgrade and enable developer mode.

**Comment by therealkenc** [comment]
It appears no one has a particular opinion on how you should approach your scenario.
