### ISSUE TITLE
Can't get the pid of the holder of a lock from a fd. 

### ISSUE THREAD

**Issue by TvKorbi** [microsoft/WSL#3094]
Hello,
I have problem with the _fcntl_ command, as it does not behave like i would expect.

* Your Windows build number: Microsoft Windows [Version 10.0.16299.248]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I had to test the usage of the _fcntl_ command regarding the set and read of locks on a fd. 
For that I created an file in /run/testapp.pid and the following two executables:

## Acquirement of the Lock: 
` int main(int argc, char *argv[])
{
	int errorCode = 0;

	int fdLOCK = open("/run/testapp.pid", O_WRONLY | O_CREAT | O_CLOEXEC, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

	//-------------LOCK---------------------

	struct flock fileLockLock = {F_WRLCK, SEEK_SET, 0, 0, 0};

	if (fcntl(fdLOCK, F_SETLK, &fileLockLock) == -1)
	{
		errorCode = errno;
		return 1;
	}

	int blubber = 0;
	std::cin  >> blubber;
	return blubber;
}`

## Try the lock
` int main(int argc, char *argv[])
{
	int errorCode = 0;

	struct flock fileLock = {F_WRLCK, SEEK_SET, 0, 0, 0};
	int fdREAD = open("/run/testapp.pid" , O_WRONLY | O_CREAT | O_CLOEXEC, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

	if (fcntl(fdREAD, F_GETLK, &fileLock) == -1)
	{
		errorCode= errno;
		std::cout << "Error of fcntl" << errorCode << std::endl;
	}

	if (fileLock.l_type != F_UNLCK)
	{
		std::cout << "Pid of locking process is:" <<fileLock.l_pid << std::endl;
	}
	else
	{
			std::cout << "l.type is not F_UNLCK" << std::endl;
	}
} `

The Acquirement  will get hte lock and the tryLock will also be to set the lock. Same thing can also be tested by just calling the  Acquirement  twice and both executable will be able to get the lock. 

* What's wrong / what should be happening instead:
only one Executable should be able to set the lock. The TryLock should return the pid of the process, which currently holds the lock.

* Strace of the failing command, if applicable: 
## Acquirement of the Lock: 
> execve("./lock", ["./lock"], [/* 19 vars */]) = 0
brk(NULL)                               = 0x7fffd6305000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8981bd0000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=20807, ...}) = 0
mmap(NULL, 20807, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8981bda000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \235\10\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1566440, ...}) = 0
mmap(NULL, 3675136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8981470000
mprotect(0x7f89815e2000, 2097152, PROT_NONE) = 0
mmap(0x7f89817e2000, 49152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x172000) = 0x7f89817e2000
mmap(0x7f89817ee000, 13312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f89817ee000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f89810a0000
mprotect(0x7f898125f000, 2097152, PROT_NONE) = 0
mmap(0x7f898145f000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f898145f000
mmap(0x7f8981465000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8981465000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0V\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1088952, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8981bc0000
mmap(NULL, 3178744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8980d90000
mprotect(0x7f8980e98000, 2093056, PROT_NONE) = 0
mmap(0x7f8981097000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x107000) = 0x7f8981097000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=89696, ...}) = 0
mmap(NULL, 2185488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8980b70000
mprotect(0x7f8980b86000, 2093056, PROT_NONE) = 0
mmap(0x7f8980d85000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f8980d85000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8981bb0000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8981ba0000
arch_prctl(ARCH_SET_FS, 0x7f8981ba0740) = 0
mprotect(0x7f898145f000, 16384, PROT_READ) = 0
mprotect(0x7f8981097000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8981b90000
mprotect(0x7f89817e2000, 40960, PROT_READ) = 0
mprotect(0x7f8981e00000, 4096, PROT_READ) = 0
mprotect(0x7f8981a25000, 4096, PROT_READ) = 0
munmap(0x7f8981bda000, 20807)           = 0
brk(NULL)                               = 0x7fffd6305000
brk(0x7fffd6337000)                     = 0x7fffd6337000
open("/run/teamviewer-iot-agent-test.pid", O_WRONLY|O_CREAT|O_CLOEXEC, 0644) = 3
**fcntl(3, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0**
fstat(0, {st_mode=S_IFCHR|0640, st_rdev=makedev(4, 2), ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
read(0, v
"v\n", 512)                     = 2
lseek(0, -2, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
exit_group(0)                           = ?
+++ exited with 0 +++

## Try the lock

> execve("./tryLock", ["./tryLock"], [/* 19 vars */]) = 0
brk(NULL)                               = 0x7fffd056b000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7018060000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=20807, ...}) = 0
mmap(NULL, 20807, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f7018069000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \235\10\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1566440, ...}) = 0
mmap(NULL, 3675136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7017a70000
mprotect(0x7f7017be2000, 2097152, PROT_NONE) = 0
mmap(0x7f7017de2000, 49152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x172000) = 0x7f7017de2000
mmap(0x7f7017dee000, 13312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7017dee000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f70176a0000
mprotect(0x7f701785f000, 2097152, PROT_NONE) = 0
mmap(0x7f7017a5f000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f7017a5f000
mmap(0x7f7017a65000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7017a65000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0V\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1088952, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7018050000
mmap(NULL, 3178744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7017390000
mprotect(0x7f7017498000, 2093056, PROT_NONE) = 0
mmap(0x7f7017697000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x107000) = 0x7f7017697000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=89696, ...}) = 0
mmap(NULL, 2185488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7017170000
mprotect(0x7f7017186000, 2093056, PROT_NONE) = 0
mmap(0x7f7017385000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f7017385000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7018040000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7018030000
arch_prctl(ARCH_SET_FS, 0x7f7018030740) = 0
mprotect(0x7f7017a5f000, 16384, PROT_READ) = 0
mprotect(0x7f7017697000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7018020000
mprotect(0x7f7017de2000, 40960, PROT_READ) = 0
mprotect(0x7f7018401000, 4096, PROT_READ) = 0
mprotect(0x7f7018025000, 4096, PROT_READ) = 0
munmap(0x7f7018069000, 20807)           = 0
brk(NULL)                               = 0x7fffd056b000
brk(0x7fffd059d000)                     = 0x7fffd059d000
open("/run/teamviewer-iot-agent-test.pid", O_WRONLY|O_CREAT|O_CLOEXEC, 0644) = 3
**fcntl(3, F_GETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=4294967296, l_pid=0}) = 0**
fstat(1, {st_mode=S_IFCHR|0640, st_rdev=makedev(4, 3), ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "Pid of locking process is:0\n", 28Pid of locking process is:0
) = 28
exit_group(0)                           = ?
+++ exited with 0 +++

I also found some other bug reports which may can fit, but they where already a year old, so I'm not quite sure of they are connected. 

In any case, thanks in advanced for your support.

Regards
Korbi

**Comment by huww98** [comment]
I also found the same problem. In my case, I'm locking on stdout file descriptor, and I'm using `lockf` API. Two process can get the lock simultaneously.

Here is my test code.

```c++
#include <iostream>
#include <string>
#include <thread>
#include <unistd.h>
#include <stdlib.h>

using namespace std;

void throwIfError(int ret, string errorMessage)
{
    if (ret != 0)
        throw new runtime_error(errorMessage);
}

void output(string msg)
{
    throwIfError(lockf(STDOUT_FILENO, F_LOCK, 0), "lockf failed");
    for (char c : msg)
    {
        cout << c << flush;
        this_thread::yield();
    }
    cout << endl;
    throwIfError(lockf(STDOUT_FILENO, F_ULOCK, 0), "lockf unlock failed");
}

void childProcess(string msg)
{
    pid_t pid = fork();
    if (pid > 0)
    {
        return;
    }
    else if (pid == 0)
    {
        output(msg);
        exit(0);
    }
    else
    {
        cerr << "error while fork" << endl;
        exit(1);
    }
}

int main()
{
    childProcess("this is from process B. A very loooooooooooooooog sentence.");
    childProcess("this is from process C. A very loooooooooooooooog sentence.");
    output("this is from process A. A very loooooooooooooooog sentence.");
    return 0;
}
```

The output is not expected to be messed up, however, it does.

**Comment by remisharrock** [comment]
linked to https://github.com/microsoft/WSL/issues/1927
