### ISSUE TITLE
mu4e - can't open "new" message  due to rename file with : in name 

### ISSUE THREAD

**Issue by joefromct** [Microsoft/WSL#3096]
_Your Windows build number:  (Type `ver` at a Windows Command Prompt)_
`Microsoft Windows [Version 10.0.16299.125]`

_What you're doing and what's happening:_

Pretty simple; Emacs 25.2.2 with a maildir in my linux home, and trying to open an unread message in `mu4e`.  
Upon opening an unread maildir message mu4e attempts to move the message from `new` to  `cur` and responds with this message:

> error in process filter: Error 70: error moving
> /mnt/c/Users/me/Maildir/inbox/new/1523500311.4945_54.hostname,U=55.2,
> to
> /mnt/c/Users/me/Maildir/inbox/cur/1523500311.4945_54.hostname,U=55.2,:2,S

It's clear mu4e is just trying to put a `:` in the filename, which i've learned is a no-go on wsl. 

Mu4e isn't planning on changing this as of july last year:  djcb/mu#1112

Is there any wsl workarounds to allow `:` in filenames, if i promise not to use my windows folders?

Or should I attempt to patch/fix mu4e?

**Comment by ax0** [comment]
Based on those messages it seems your maildir is actually on the Windows side (``/mnt/c/Users/...`` rather than ``/home/...``), so perhaps you could try moving your maildir. I've been managing my maildir on the Linux side without encountering this issue.

**Comment by therealkenc** [comment]
#1514. `ax0` answer, even better.

**Comment by ax0** [comment]
Actually, there is something peculiar about the behaviour of files with `:` in their names on the Windows side, at least on build 17133.73. For instance, `touch a\:b` and `echo x > a\:b` work fine, but:
```
$ touch a
$ mv a a\:c
mv: cannot move 'a' to 'a:c': No such file or directory
```
...which is what @joefromct is experiencing. Also, if `a:c` exists, the output is the same, but then `a:c` disappears!
