### ISSUE TITLE
install debian on a server without a store

### ISSUE THREAD

**Issue by encodeering** [Microsoft/WSL#3098]
Hi, 

found a blogpost to install linux on a server, but couldn't find a direct link for debian:
https://docs.microsoft.com/en-us/windows/wsl/install-on-server

I've tried to guess a few links without success. Anyhow, it would be great if you could provide a comment or update the description.

Cheers

**Comment by DarthSpock** [comment]
@rhaist should be able to help you.

**Comment by Biswa96** [comment]
You can make  your own debian rootfs tarball and install it. Just need a C compiler and 5 lines of code.

**Comment by encodeering** [comment]
@Biswa96 Thanks for your answer. I would currently prefer a solution that doesn't require manual compilation steps and rather use something existing. May I still ask you to post those lines or some additional reading in case I have to?

**Comment by Biswa96** [comment]
Here is the simplemcode for the installer:
```
#include <Windows.h>
#include <stdio.h>
    
typedef HRESULT (WINAPI* RegisterDistro)(PCWSTR distroName, PCWSTR tarGzFilename);
    
int main() {
    int wargc;
    wchar_t** wargv;
    wargv = CommandLineToArgvW(GetCommandLineW(), &wargc);
    HMODULE dll = LoadLibraryExW(L"wslapi.dll", NULL, LOAD_LIBRARY_SEARCH_SYSTEM32);
    RegisterDistro func = (RegisterDistro)GetProcAddress(dll, "WslRegisterDistribution");
    HRESULT result = func(wargv[1], wargv[2]);
    (result == S_OK) ? printf("Distribution '%ls' is successfully installed\n", wargv[1]) : printf("Error: 0x%x\n", result);
}
```
And you can build the debian rootfs tarball using this shell script: https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh

**Comment by encodeering** [comment]
@Biswa96 thank you for the posting. I thought that I could cross compile it from linux, but them stumbled upon the 'Windows.h' include ;), so its ages ago since I had to setup this kind of toolchain for any OS.

I'am not in hurry at the moment and will simply wait for an official link, but anyhow, your description and link might be helpful for others.

Cheers

**Comment by Biswa96** [comment]
You have not to include Windows.h. iostream/stdio.h will do the work. Do you have any other PC or laptop where you can download debian from store? I've an idea.

**Comment by DDoSolitary** [comment]
@encodeering You can try my project https://github.com/DDoSolitary/LxRunOffline 😃

**Comment by rhaist** [comment]
There will be an update of the store app soon and I will work with the MSF team to get the Debian appx to the server page. Sorry for the delay and thank you for using Debian :)

**Comment by rhaist** [comment]
@Biswa96 I am creating the install.tar.gz file using the following script:

https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh

the script needs the files also present in the same repository:

https://salsa.debian.org/rhaist-guest/WSL/tree/master/linux_files

**Comment by rhaist** [comment]
@encodeering the app is available for download now. This issue can probably be closed.

**Comment by encodeering** [comment]
@rhaist @Biswa96 that's cool, just tried it, thank you for this!

**Comment by Biswa96** [comment]
@rhaist Some questions about that [create-targz.sh](https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh) script:
1. Will there be any difference if I choose `DIST="stable"` instead of a specific release (e.g. `DIST="stretch"`)?
2. If I only use `cdebootstrap` and `tar` commands without any other chroot and linux_files then WSL installation works fine. Are those `chroot` commands optional?
