### ISSUE TITLE
socketpair() syscall ignores non-blocking request (SOCK_NONBLOCK, O_NONBLOCK)

### ISSUE THREAD

**Issue by christianparpart** [Microsoft/WSL#3100]
Hi,

**(windows version: 10.0.17133.73)**

I found out that the syscall `socketpair` is litereally ignoring the `SOCK_NONBLOCK` argument.
Also is `fcntl`'s attempt to make `socketpair`'s sockets non-blocking ignored.

Here's a minimal example program that proofs both cases. On original Linux it immediately quits as expected with the appropriate error message (`EAGAIN`), but on WSL/Linux it freezes after having filled one end with `163840` bytes.

```cpp
#include <sys/socket.h>
#include <sys/types.h>
#include <fcntl.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>

int reportError(const char* syscall, int ec) {
  printf("%s: %s\n", syscall, strerror(ec));
  return 1;
}

int main(int argc, const char* argv[]) {
  int sv[2];
  int typeMask = 0;
  int flags = 0;

  if (argc == 2 && strcmp(argv[1], "-f") == 0) {
    flags |= O_NONBLOCK;
  } else {
    typeMask |= SOCK_NONBLOCK;
  }

  if (socketpair(PF_LOCAL, SOCK_STREAM | typeMask, 0, sv) < 0)
    return reportError("socketpair", errno);

  if (flags) {
    if (fcntl(sv[0], F_SETFL, flags) < 0)
      return reportError("fcntl", errno);
    if (fcntl(sv[1], F_SETFL, flags) < 0)
      return reportError("fcntl", errno);
  }

  static const char buf[4096] = {0};
  for (;;) {
    int rv = write(sv[0], buf, sizeof(buf));
    if (rv < 0) {
      reportError("write", errno);
      break;
    }
  }
  close(sv[0]);
  close(sv[1]);
  return 0;
}
```

**Comment by Biswa96** [comment]
Mention Windows build version.

**Comment by christianparpart** [comment]
@Biswa96 added. thx!

**Comment by christianparpart** [comment]
That is why u am dog-clear in subject and description, including example-cide to reproduce. No other ticket came close to it, that's why I created a dedicated one.

**Comment by therealkenc** [comment]
It's #2949, I think (right?). Don't quibble on the flags. Won't dupe ya.

**Comment by Brian-Perkins** [comment]
This should be fixed in build [17666](https://github.com/MicrosoftDocs/WSL/releases/tag/17666).
