### ISSUE TITLE
WSL apt-get upgrade not working anymore

### ISSUE THREAD

**Issue by cpei-avalara** [microsoft/WSL#3102]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
sudo apt-get upgrade

error message
The following packages will be upgraded:
  apport firefox hdparm icu-devtools libavahi-client3 libavahi-common-data libavahi-common3 libicu-dev libicu57 libplymouth4 libssl1.0.0 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3
  libwayland-client0 libwayland-cursor0 libwayland-server0 linux-libc-dev lshw nplan openssl patch plymouth plymouth-theme-ubuntu-text python3-apport python3-distupgrade
  python3-problem-report systemd-sysv ubuntu-release-upgrader-core zsh zsh-common
32 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
2 not fully installed or removed.
Need to get 0 B/77.4 MB of archives.
After this operation, 20.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Extracting templates from packages: 100%
Preconfiguring packages ...
Setting up systemd (234-2ubuntu12.3) ...
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
[/usr/lib/tmpfiles.d/tmp.conf:15] Failed to replace specifiers: /tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:16] Failed to replace specifiers: /tmp/systemd-private-%b-*/tmp
[/usr/lib/tmpfiles.d/tmp.conf:17] Failed to replace specifiers: /var/tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:18] Failed to replace specifiers: /var/tmp/systemd-private-%b-*/tmp
dpkg: error processing package systemd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

* What's wrong / what should be happening instead:

There should be no errors

**Comment by Biswa96** [comment]
Try to fix with this commands:
```
sudo apt-get update –fix-missing
sudo apt-get update
sudo apt-get upgrade
```

**Comment by Biswa96** [comment]
Try to fix with this commands:
```
sudo apt-get install --fix-missing
sudo apt-get update
sudo apt-get upgrade
```
