### ISSUE TITLE
Failure trying SSHFS. Alternatives?

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3103]
I have a MacBookPro (MBP) with a folder `/opt/tlrepo` which I have "mouned" on GNU/Linux Mint with

`sshfs utente@MBP:/opt/tlrepo /mnt/tlrepo`

and I can use it [BTW, /opt/tlrepo is a local mirror of TeXLive (TL) distribution and I can install TL on GNU/linux using the same repo I have used on MBP.]

Trying the same on WSL fails:

`fuse: device not found, try 'modprobe fuse' first`

I have seen that this is not yet supported by WSL and that many users want that.

Meanwhile, How I can "mount" that folder in WSL? Which alternatives? [BTW, I have to copy tlrepo on an USB key to install TL on WSL. ALL this works just fine, but to maintain the installation it would be very useful to have only one tlrepo.]

Here is Win 10 Pro 64b 10.0.16299.371 and WSL:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

(SSHFS package installs on WSL without issues using `sudo apt install...`)

Thanks.

**Comment by fpqc** [comment]
SSHFS uses FUSE, which is not supported atm.

**Comment by angelog0** [comment]
@fpqc wrote:
> SSHFS uses FUSE, which is not supported atm.

Yes, I know and suggest, as others, to add that... but I asked also for alternatives...

How can I do that job ("mounting" a utente@MBP:/opt/tlrepo) on WSL? Notice that

`ssh utente@MBP`

(and `scp to/from MBP`) already works on WSL..

Thanks.

**Comment by christianparpart** [comment]
@angelog0 alternative: http://www.secfs.net/winfsp/blog/files/winfsp-2017.html

@angelog0 scp is a completely different thing that sshfs (which is on top of FUSE). So what you're basically asking in that ticket (or should), is to please implement FUSE related syscalls.

**Comment by angelog0** [comment]
@christianparpart wrote:

> alternative: http://www.secfs.net/winfsp/blog/files/winfsp-2017.html

I don't understand how to use it in relation with WSL. 

Do you mean that after I have installed it I can use in WSL

`sshfs utente@MBP:/opt/tlrepo /mnt/tlrepo`

?

Do you mean that WinFsp will work with sshfs from WSL package? I am reading this page [WinFsp](http://www.secfs.net/winfsp/download) and it seems that if I run

`memfs-x64 -u \memfs64\share2 -m *`

it will create a shared `Y:` drive. But with which machine?

Please, may you elaborate? How can I "mount" the MBP folder `utente@MBP:/opt/tlrepo` in WSL `/mnt/tlrepo` folder? Maybe you need to re-read my OP.

Thanks.

**Comment by fpqc** [comment]
It's not just FUSE syscalls. FUSE needs to be added at the Windows driver level

**Comment by angelog0** [comment]
@fpqc wrote:

> FUSE needs to be added at the Windows driver level

So, I download WinFsp MSI file, install it, install the sshfs WSL package and than I can use `sshfs utente@MBP:/opt/tlrepo /mnt/tlrepo` in WSL?

Please, clarify. Thanks.

**Comment by angelog0** [comment]
Ok, with `winfsp` and `sshfs-win` I managed to mount the Mac Book Pro (MBP) repo on Windows as drive `Z:` and then I mounted this drive to WSL (`sudo mount -t drvfs z: /mnt/z`) but ALL THIS didn't solve my problem: using a TeXLive (TL) repo on  MBP to install and maintain it on other PCs (Windows, GNU/Linux) in the LAN. 

Even if I can read and write the /mnt/z, when I try to update the TL installation, it fails because it does not understand some /mnt/z/tlrepo files. May be they are symlinks on MBP and GNU/Linux but /mnt/z sees them as simple text files. It is a pity.

Let's see if WSL will acquire the FUSE support...

Thanks.

**Comment by heldchen** [comment]
create a samba mount on your MBP, mount it at least once in windows 10 to save the credentials. after that you will be able to mount the UNC path in WSL directly using `drvfs`

**Comment by therealkenc** [comment]
Discussion ran course.

**Comment by Hug0Albert0** [comment]
fuse: device not found, try 'modprobe fuse' first


Is anyone having the same problem?

**Comment by Dibbyo456** [comment]
> fuse: device not found, try 'modprobe fuse' first
> Is anyone having the same problem?

@Hug0Albert0 Having the issue. Any fix?

**Comment by boemska-nik** [comment]
@Hug0Albert0 @Dibbyo456 The answer is in @fpqc 's comment, the first comment on this issue. The various solutions are the rest of this comment thread.

**Comment by carlosdelfino** [comment]
Keybase also needs Fuse to mount its encrypted and distributed file system, the same problem occurs. Is there any possibility of this being solved?
