### ISSUE TITLE
Modifying a file in windows while it is being watched in WSL causes split personality

### ISSUE THREAD

**Issue by LongJohnCoder** [microsoft/WSL#3104]
* Your Windows build number:  **10.0.17133.73**

* What you're doing and what's happening:  **While editing a file in gVIM (Windows) I am using nodemon to automatically restart node after each modification. The changed file is saved, but the change is not reflected in the WSL session, it retains the old version until the file is saved a second time or nodemon is restarted (perhaps a new inotify request in both instances?).** 

![image](https://user-images.githubusercontent.com/108511/38774753-a0777d62-4024-11e8-820c-9569b568e26a.png)

* What's wrong / what should be happening instead: **As shown in the screenshot, if the file is examined in windows (via cmd prompt), it shows the new contents. If the file is examined in WSL (via bash prompt), it shows the old contents. This occurs even if you transition from cmd.exe to bash. Windows/WSL should always reflect the same contents for files. Nodemon (or  I suspect anything using inotify) should not prevent the file from being synchronized between worlds.**

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
