### ISSUE TITLE
BASH stays frozen until Windows restart

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#3105]
* Your Windows build number:  10.0.16299

* What you're doing and what's happening:  ran this ruby [script](https://github.com/janus0/top_course_work/blob/master/ruby/project_hangman/lib/hangman.rb), which became unresponsive. Used ctrl + c to terminate, but bash stayed frozen. Killed terminal, restarted, vs code, and still frozen.

* What's wrong / what should be happening instead: Ctrl + c should stop the current script and go back to the BASH prompt.

**Comment by khe817** [comment]
I have the same problem with bash sometimes hangs then become unresponsive. I cannot kill the running process in windows task manager, or send `Ctrl + C`/`Ctrl + X` signal to the bash terminal. Any other bash windows opened after that is unresponsive as well. The only way I could get the bash terminal back is restarting windows.

This happens often when I leave the java Spring Boot server up long enough. Starting command for Spring Boot: `$mvn spring-boot:run`.

**Comment by DarthSpock** [comment]
Upgrade to build 17134. 
> cannot kill the running process in windows task manager, or send Ctrl + C/Ctrl + X signal to the bash terminal

`init` and friends can be killed in this build and you can also use Ctrl + C/ V (copy/paste). Other Ctrl functions are being tracked in https://github.com/Microsoft/Console.

**Comment by khe817** [comment]
After upgrading windows to build 17134, I can kill WSL bash after it becomes unresponsive.

Thank you very much for your help!

**Comment by bpulliam** [comment]
Much has changed in the WSL world since this was filed.  If you still see this issue, please file a new one. Thanks!
