### ISSUE TITLE
apt-get update error

### ISSUE THREAD

**Issue by wqk317** [microsoft/WSL#3106]
`apt-get update
...
...
已下载 28.5 MB，耗时 51秒 (556 kB/s)

(appstreamcli:702): GLib-CRITICAL **: 08:15:18.930: g_strchug: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:18.931: g_strchomp: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:18.986: g_strchug: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:18.987: g_strchomp: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:19.030: g_strchug: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:19.031: g_strchomp: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:19.127: g_strchug: assertion 'string != NULL' failed

(appstreamcli:702): GLib-CRITICAL **: 08:15:19.127: g_strchomp: assertion 'string != NULL' failed

** (appstreamcli:702): CRITICAL **: 08:15:23.160: Error while moving old database out of the way.
AppStream cache update failed.
正在读取软件包列表... 完成
W: https: aptMethod::Configuration: could not load seccomp policy: 无效的参数
W: store: aptMethod::Configuration: could not load seccomp policy: 无效的参数`

**Comment by Biswa96** [comment]
Provide Windows version and which Distribution are you running?

**Comment by wqk317** [comment]
Windows: 1709  16299.371

Distributor ID: Ubuntu
Description:    Ubuntu Bionic Beaver (development branch)
Release:        18.04
Codename:       bionic

**Comment by Alternate-Egoist** [comment]
no wsl is only containers, there's no issues about appstream and seccomp. i suggest to remove appstream, since it's bionic you don't have worry about seccomp policy
