### ISSUE TITLE
install fish failed

### ISSUE THREAD

**Issue by wqk317** [Microsoft/WSL#3108]
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
正在计算更新... 完成
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
有 11 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
您希望继续执行吗？ [Y/n] Y
正在设置 python3 (3.6.5-3) ...
running python rtupdate hooks for python3.6...
dpkg-query: 软件包 rhythmbox-plugin-zeitgeist 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugin-zeitgeist
error running python rtupdate hook rhythmbox-plugin-zeitgeist
dpkg-query: 软件包 rhythmbox-plugins 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugins
error running python rtupdate hook rhythmbox-plugins
dpkg-query: 软件包 sosreport 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of sosreport
error running python rtupdate hook sosreport
dpkg-query: 软件包 ubuntu-drivers-common 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ubuntu-drivers-common
error running python rtupdate hook ubuntu-drivers-common
dpkg: 处理软件包 python3 (--configure)时出错：
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: 依赖关系问题使得 fish 的配置工作不能继续：
 fish 依赖于 python3；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 fish (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 hplip-data 的配置工作不能继续：
 hplip-data 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 hplip-data (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-gi 的配置工作不能继续：
 python3-gi 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-gi (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-uno 的配置工作不能继续：
 python3-uno 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-uno (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus 的配置工作不能继续：
 ibus 依赖于 python3-gi；然而：
  软件包 python3-gi 尚未配置。
 ibus 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-lib2to3 的配置工作不能继续：
 python3-lib2to3 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-lib2to3 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-lib2to3 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 dh-python 的配置工作不能继续：
 dh-python 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 dh-python (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-distutils 的配置工作不能继续：
 python3-distutils 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3-lib2to3 (>= 3.6.4)；然而：
  软件包 python3-lib2to3 尚未配置。

dpkg: 处理软件包 python3-distutils (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 gir1.2-ibus-1.0:amd64 的配置工作不能继续：
 gir1.2-ibus-1.0:amd64 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 gir1.2-ibus-1.0:amd64 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus-table 的配置工作不能继续：
 ibus-table 依赖于 ibus (>= 1.5.0)；然而：
  软件包 ibus 尚未配置。
 ibus-table 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus-table (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 python3
 fish
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Biswa96** [comment]
Your installed WSL distribution has some problems with package manager and package installation. Try to fix with commands:
 ```
sudo apt-get autoremove
sudo apt-get --fix-broken
sudo apt-get --fix-missing
```

**Comment by wqk317** [comment]
@Biswa96 
it's useless...
`# **apt-get autoremove**
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
下列软件包将被【卸载】：
  libargon2-0 libcryptsetup12 libdevmapper1.02.1 libip4tc0 libjson-c3 libkmod2 systemd
升级了 0 个软件包，新安装了 0 个软件包，要卸载 7 个软件包，有 0 个软件包未被升级。
有 12 个软件包没有被完全安装或卸载。
解压缩后将会空出 13.9 MB 的空间。
您希望继续执行吗？ [Y/n] y
(正在读取数据库 ... 系统当前共安装有 36373 个文件和目录。)
正在卸载 systemd (237-3ubuntu8) ...
正在卸载 libcryptsetup12:amd64 (2:2.0.2-1ubuntu1) ...
正在卸载 libargon2-0:amd64 (0~20161029-1.1) ...
正在卸载 libdevmapper1.02.1:amd64 (2:1.02.145-4.1ubuntu3) ...
正在卸载 libip4tc0:amd64 (1.6.1-2ubuntu2) ...
正在卸载 libjson-c3:amd64 (0.12.1-1.3) ...
正在卸载 libkmod2:amd64 (24-1ubuntu3) ...
dpkg: 警告: 卸载 libkmod2:amd64 时，目录 /usr/share/doc/libkmod2 非空，因而不会删除该目录
正在设置 python3 (3.6.5-3) ...
running python rtupdate hooks for python3.6...
dpkg-query: 软件包 rhythmbox-plugin-zeitgeist 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugin-zeitgeist
error running python rtupdate hook rhythmbox-plugin-zeitgeist
dpkg-query: 软件包 rhythmbox-plugins 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugins
error running python rtupdate hook rhythmbox-plugins
dpkg-query: 软件包 sosreport 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of sosreport
error running python rtupdate hook sosreport
dpkg-query: 软件包 ubuntu-drivers-common 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ubuntu-drivers-common
error running python rtupdate hook ubuntu-drivers-common
dpkg: 处理软件包 python3 (--configure)时出错：
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: 依赖关系问题使得 fish 的配置工作不能继续：
 fish 依赖于 python3；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 fish (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 hplip-data 的配置工作不能继续：
 hplip-data 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 hplip-data (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-gi 的配置工作不能继续：
 python3-gi 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-gi (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-uno 的配置工作不能继续：
 python3-uno 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-uno (--configure)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 libc-bin (2.27-0ubuntu3) 的触发器 ...
dpkg: 依赖关系问题使得 ibus 的配置工作不能继续：
 ibus 依赖于 python3-gi；然而：
  软件包 python3-gi 尚未配置。
 ibus 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus (--configure)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 man-db (2.8.3-2) 的触发器 ...
apt-get --fix-broken
正在处理用于 dbus (1.12.2-1ubuntu1) 的触发器 ...
dpkg: 依赖关系问题使得 python3-lib2to3 的配置工作不能继续：
 python3-lib2to3 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-lib2to3 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-lib2to3 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 dh-python 的配置工作不能继续：
 dh-python 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 dh-python (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-distutils 的配置工作不能继续：
 python3-distutils 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3-lib2to3 (>= 3.6.4)；然而：
  软件包 python3-lib2to3 尚未配置。

dpkg: 处理软件包 python3-distutils (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 gir1.2-ibus-1.0:amd64 的配置工作不能继续：
 gir1.2-ibus-1.0:amd64 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 gir1.2-ibus-1.0:amd64 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus-table 的配置工作不能继续：
 ibus-table 依赖于 ibus (>= 1.5.0)；然而：
  软件包 ibus 尚未配置。
 ibus-table 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus-table (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 python3
E: Sub-process /usr/bin/dpkg returned an error code (1)
**root# apt-get install --fix-broken**
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
有 11 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
正在设置 python3 (3.6.5-3) ...
running python rtupdate hooks for python3.6...
dpkg-query: 软件包 rhythmbox-plugin-zeitgeist 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugin-zeitgeist
error running python rtupdate hook rhythmbox-plugin-zeitgeist
dpkg-query: 软件包 rhythmbox-plugins 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugins
error running python rtupdate hook rhythmbox-plugins
dpkg-query: 软件包 sosreport 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of sosreport
error running python rtupdate hook sosreport
dpkg-query: 软件包 ubuntu-drivers-common 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ubuntu-drivers-common
error running python rtupdate hook ubuntu-drivers-common
dpkg: 处理软件包 python3 (--configure)时出错：
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: 依赖关系问题使得 fish 的配置工作不能继续：
 fish 依赖于 python3；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 fish (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 hplip-data 的配置工作不能继续：
 hplip-data 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 hplip-data (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-gi 的配置工作不能继续：
 python3-gi 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-gi (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-uno 的配置工作不能继续：
 python3-uno 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-uno (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus 的配置工作不能继续：
 ibus 依赖于 python3-gi；然而：
  软件包 python3-gi 尚未配置。
 ibus 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-lib2to3 的配置工作不能继续：
 python3-lib2to3 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-lib2to3 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-lib2to3 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 dh-python 的配置工作不能继续：
 dh-python 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 dh-python (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-distutils 的配置工作不能继续：
 python3-distutils 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3-lib2to3 (>= 3.6.4)；然而：
  软件包 python3-lib2to3 尚未配置。

dpkg: 处理软件包 python3-distutils (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 gir1.2-ibus-1.0:amd64 的配置工作不能继续：
 gir1.2-ibus-1.0:amd64 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 gir1.2-ibus-1.0:amd64 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus-table 的配置工作不能继续：
 ibus-table 依赖于 ibus (>= 1.5.0)；然而：
  软件包 ibus 尚未配置。
 ibus-table 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus-table (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 python3
 fish
 hplip-data
 python3-gi
 python3-uno
 ibus
 python3-lib2to3
 dh-python
 python3-distutils
 gir1.2-ibus-1.0:amd64
 ibus-table
E: Sub-process /usr/bin/dpkg returned an error code (1)
**root# apt-get install --fix-missing**
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
有 11 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
正在设置 python3 (3.6.5-3) ...
running python rtupdate hooks for python3.6...
dpkg-query: 软件包 rhythmbox-plugin-zeitgeist 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugin-zeitgeist
error running python rtupdate hook rhythmbox-plugin-zeitgeist
dpkg-query: 软件包 rhythmbox-plugins 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of rhythmbox-plugins
error running python rtupdate hook rhythmbox-plugins
dpkg-query: 软件包 sosreport 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of sosreport
error running python rtupdate hook sosreport
dpkg-query: 软件包 ubuntu-drivers-common 没有被安装
使用 dpkg --info (= dpkg-deb --info) 来检测打包好的文件，
还可以通过 dpkg --contents (= dpkg-deb --contents) 来列出它们的内容。
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ubuntu-drivers-common
error running python rtupdate hook ubuntu-drivers-common
dpkg: 处理软件包 python3 (--configure)时出错：
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: 依赖关系问题使得 fish 的配置工作不能继续：
 fish 依赖于 python3；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 fish (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 hplip-data 的配置工作不能继续：
 hplip-data 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 hplip-data (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-gi 的配置工作不能继续：
 python3-gi 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。
 python3-gi 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-gi (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-uno 的配置工作不能继续：
 python3-uno 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (<< 3.7)；然而：
  软件包 python3 尚未配置。
 python3-uno 依赖于 python3 (>= 3.6~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-uno (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus 的配置工作不能继续：
 ibus 依赖于 python3-gi；然而：
  软件包 python3-gi 尚未配置。
 ibus 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-lib2to3 的配置工作不能继续：
 python3-lib2to3 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-lib2to3 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 python3-lib2to3 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 dh-python 的配置工作不能继续：
 dh-python 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 dh-python (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python3-distutils 的配置工作不能继续：
 python3-distutils 依赖于 python3 (>= 3.6.4-1~)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3 (<< 3.8)；然而：
  软件包 python3 尚未配置。
 python3-distutils 依赖于 python3-lib2to3 (>= 3.6.4)；然而：
  软件包 python3-lib2to3 尚未配置。

dpkg: 处理软件包 python3-distutils (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 gir1.2-ibus-1.0:amd64 的配置工作不能继续：
 gir1.2-ibus-1.0:amd64 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 gir1.2-ibus-1.0:amd64 (--configure)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 ibus-table 的配置工作不能继续：
 ibus-table 依赖于 ibus (>= 1.5.0)；然而：
  软件包 ibus 尚未配置。
 ibus-table 依赖于 python3:any (>= 3.3.2-2~)；然而：
  软件包 python3 尚未配置。

dpkg: 处理软件包 ibus-table (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 python3
 fish
 hplip-data
 python3-gi
 python3-uno
 ibus
 python3-lib2to3
 dh-python
 python3-distutils
 gir1.2-ibus-1.0:amd64
 ibus-table
E: Sub-process /usr/bin/dpkg returned an error code (1)
root#`

**Comment by Biswa96** [comment]
**DON'T MESS UP THIS ISSUE WITH LONG COMMAND OUTPUT. REMOVE THOSE EXTRA LINES. OR PUT THESE IN A GIST FILE.**

**Comment by wqk317** [comment]
sorry, I'm not very good at describing this，my English is poor

**Comment by wqk317** [comment]
我已经卸载重新安装了, systemd还是报错, 不知道是什么原因, 错误输出如下:
=====================
Setting up systemd (237-3ubuntu8) ...                                                                          
Synchronizing state of ondemand.service with SysV service script with /lib/systemd/systemd-sysv-install.       
Executing: /lib/systemd/systemd-sysv-install enable ondemand                                                   
[/usr/lib/tmpfiles.d/tmp.conf:15] Failed to replace specifiers: /tmp/systemd-private-%b-*                      
[/usr/lib/tmpfiles.d/tmp.conf:16] Failed to replace specifiers: /tmp/systemd-private-%b-*/tmp                  
[/usr/lib/tmpfiles.d/tmp.conf:17] Failed to replace specifiers: /var/tmp/systemd-private-%b-*                  
[/usr/lib/tmpfiles.d/tmp.conf:18] Failed to replace specifiers: /var/tmp/systemd-private-%b-*/tmp              
dpkg: error processing package systemd (--configure):                                                          
 subprocess installed post-installation script returned error exit status 1                                    
Processing triggers for dbus (1.10.6-1ubuntu3.3) ...                                                           
Setting up bsdmainutils (11.1.2ubuntu1) ...                                                                    
Setting up locales (2.27-0ubuntu3) ...                                                                         
Installing new version of config file /etc/locale.alias ...                                                    
Generating locales (this might take a while)...                                                                
  en_US.UTF-8... done                                                                                          
Generation complete.                                                                                           
Setting up git (1:2.17.0-1ubuntu1) ...                                                                         
Setting up netbase (5.4) ...                                                                                   
Installing new version of config file /etc/services ...                                                        
dpkg: dependency problems prevent configuration of libpam-systemd:amd64:                                       
 libpam-systemd:amd64 depends on systemd (= 237-3ubuntu8); however:                                            
  Package systemd is not configured yet.                                                                       
                                                                                                               
dpkg: error processing package libpam-systemd:amd64 (--configure):                                             
 dependency problems - leaving unconfigured                                                                    
Setting up libpython3.6-minimal:amd64 (3.6.5-3) ...                                                            
Processing triggers for man-db (2.7.5-1) ...                                                                   
Setting up python3.6-minimal (3.6.5-3) ...                                                                     
Processing triggers for libc-bin (2.27-0ubuntu3) ...                                                           
Processing triggers for ureadahead (0.100.0-19) ...                                                            
Errors were encountered while processing:                                                                      
 systemd                                                                                                       
 libpam-systemd:amd64                                                                                          
                                                                                                               
Upgrade complete                                                                                               
                                                                                                               
The upgrade has completed but there were errors during the upgrade                                             
process.                                                                                                       
                                                                                                               
To continue please press [ENTER]                                                                               
=== Command terminated with exit status 1 (Wed Apr 18 08:51:16 2018) ===

**Comment by Immortalin** [comment]
Try running `sudo apt-get install -f`

**Comment by sirredbeard** [comment]
What is the specific command you are running to install fish?

Are you on Ubuntu 16.04 or 18.04?

Have you run:
`sudo apt-get update ; sudo apt-get upgrade -y`?

**Comment by in3omnia** [comment]
```
cd /var/lib/dpkg  
sudo mv info info.bak  
sudo mkdir info
```
