### ISSUE TITLE
/etc/timezone is not a symlink - breaks .NET TimeZoneInfo API

### ISSUE THREAD

**Issue by bruno-garcia** [Microsoft/WSL#3109]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.309] 

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

[CoreFX relies on /etc/timezone being a symlink](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs#L360) to work properly. 
Calling `TimeZoneInfo` API gives the wrong output:

*On Kali under WSL*

Linux FLORIPA 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

```
// .NET Core 2.0.6:
TimeZoneInfo.Local.DisplayName:                          GMT
TimeZoneInfo.Local.Id:                                   Msft/localtime
```

**The same program gives different results on macOS and Linux:**

*On macOS 10.12.2*

Darwin Brunos-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

```
// .NET Core 2.0.6:
TimeZoneInfo.Local.DisplayName:                       GMT+01:00
TimeZoneInfo.Local.Id:                                Europe/Vienna
```

*On CentOS 7*
Linux centos-7.shared 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
// .NET Core 2.0.6:
TimeZoneInfo.Local.DisplayName:                       Central European Standard Time
TimeZoneInfo.Local.Id:                                Europe/Vienna
```

* What's wrong / what should be happening instead:

The correct timezone information should be returned like exampled above with CentOS (outside WSL) and macOS.

**Comment by Brian-Perkins** [comment]
This is discussed in #856. The issue here is that by default we add private timezone data that reflects Windows settings (timezone file is written as needed when a WSL instance is started). Normally when you setup timezone information (e.g. sudo dpkg-reconfigure tzdata) it creates a symlink to the appropriate tzdata file. This is so common that many tools, setup scripts, etc. have taken a dependency on it. Apparently not a lot of people are creating private timezone files. The easiest fix is just to setup standard timezone information. This means you will decouple from the Windows timezone information, but for most scenarios this is fine -- you will just need to adjust timezone information inside of WSL manually as needed, but this will not be that surprising for many *nix users.

**Comment by bruno-garcia** [comment]
Thanks for your quick reply!

Although I can fix my own instance, the code I'm writing (which depends on TimeZoneInfo.Local) is part of a NuGet library which is used in a variety of applications and platforms. 

Any application running on WSL (I'm hoping there'll be many) will end up with the wrong behaviour.

I believe this is an issue and should be solved somehow. If it's decided that there is no way WSL can resolve this, perhaps the CoreFX team would consider having a special handling for WSL, having support to whatever way Windows passes on the value to Linux. 

I do believe `/etc/timezone` not being a symlink will end up giving other problems anyway so worth investing time in changing this approach.

**Comment by fpqc** [comment]
MS could put their dynamic files in /wsl/ and symlink them, Brian?

**Comment by Brian-Perkins** [comment]
I think it would be ok to symlink /etc/localtime, but /etc/timezone I am less confident of. The original implementation of our private timezone information did add a /etc/timezone, but it broke when tzdata was updated (if I recall the update script used the contents, assuming they were written by tzdata). So we backed off to the bare minimum update of /etc/localtime (and no symlinks). I am not sure if just updating /etc/localtime to a symlink would be of any value, but it would certainly be something we could do, were it to be beneficial.

**Comment by pjanotti** [comment]
Per [manual pages](http://man7.org/linux/man-pages/man5/localtime.5.html) it seems reasonable to make `/etc/localtime` a symlink as described above. So the quick procedure described on the man pages to get a timezone identifier is not available by default, of course one could use the workaround described at https://github.com/Microsoft/WSL/issues/1392 but things that use the symlink may have trouble on WSL while working just fine on Ubuntu.

**Comment by andyneff** [comment]
@bruno-garcia According to [this line](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs#L311), `/etc/localtime` was expected to be a symlink, not `/etc/timezone`. Do you agree?

@Brian-Perkins,@pjanotti at least in build 17134, I noticed that `/etc/localtime` is already hardlinked to `/usr/share/zoneinfo/Msft/localtime`, and that `/usr/share/zoneinfo/Msft/localtime` is the file that `wslhost`. writes to while you run "Bash for Windows". In that case, I believe it is highly useful to make `/etc/localtime` symlink to `/usr/share/zoneinfo/Msft/localtime` as the original default behavior instead. This will benefit the many programs that expect `/etc/localtime` to be a symlink, mentioned here and in #1392). (Or course that won't have any affect on the `TimeZoneInfo.Local.Id` saying `Msft/localtime`.) 

I think all mention of symlinking `/etc/timezone` is a typo.

**Comment by mj1856** [comment]
Note - Since Windows already has facilities for mapping to IANA time zones (see #3747), this should be easily solvable by the WSL team.

**Comment by therealkenc** [comment]
Will these up to #3747 as the new landing zone since it is a detailed write-up of the problem and solution. Thanks for that. This said, I fear you have irreparably jinxed it with the "easily solvable" part. I've been waiting for "easily solvable" bugs that are still on the backlog to be closed since 2016.....
