### ISSUE TITLE
Colors break when there is a ~/.bash_profile file

### ISSUE THREAD

**Issue by FayneAldan** [Microsoft/WSL#3110]
* Your Windows build number: 10.0.17133.73

* What you're doing and what's happening:
1. Create the `~/.bash_profile` file, which can be done with: `echo '' >> ~/.bash_profile`
2. Restart WSL.
The terminal ends up colorless: ![Colorless Terminal](https://i.imgur.com/BFFas1W.png)

* What's wrong / what should be happening instead:
The terminal should be in color, like normal: ![Terminal with Color](https://i.imgur.com/V7R10qE.png)

**Comment by DarthSpock** [comment]
I would file that here: https://github.com/Microsoft/console

**Comment by 0xbadfca11** [comment]
Expected behavior. Should load ``.bashrc`` from ``.bash_profile`` when you manually create ``.bash_profile``.
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

**Comment by zadjii-msft** [comment]
@0xbadfca11 is correct. This is working as expected.
