### ISSUE TITLE
Installing Node and NPM. Need to confirm Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by carpben** [Microsoft/WSL#3111]
I need to install Node and NPM, and on the [download page ](https://nodejs.org/en/download/)for unix I need to choose between 5 different options: 32bits, 64 bits, ArmV6, ArmV7, Armv8.  I couldn't find Bash/Ubuntu in any directory, and not in the 64 bit program directory. If my Windows is 64 bit, can I assume that Bash/Ubuntu will be 64 bits as well, and that that is the right file to download?

Arms themselves are either 32 or 64 bit so this left me a confused. Are Arm versions meant for mobile devices?

**Comment by DarthSpock** [comment]
@carpben Just choose the 64 bit Linux binary. WSL is built on top of a x64 archecture (you need a 64 bit Windows to run WSL). ARM is typically refers to mobile or embedded systems. WSL isn't ARM based, so distros you install wouldn't have the support by default.

**Comment by therealkenc** [comment]
@heldchen's reply closely a month ago. His answer is nodejs.org's official [direction](https://nodejs.org/en/download/package-manager/) (if there is such a thing).

**Comment by logicware** [comment]
I installed node 10.12.0, but on `npm -v` I am getting
```
net.js:215
    this._handle.open(fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:215:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:249:38
    at NativeModule.compile (bootstrap_node.js:613:7)
    at Function.NativeModule.require (bootstrap_node.js:558:18)
    at setupGlobalConsole (bootstrap_node.js:327:41)
    at startup (bootstrap_node.js:80:7)
    at bootstrap_node.js:625:3
```

**Comment by logicware** [comment]
@nicowernli 
You have to install npm separately. It does not get installed with nodejs.

**Comment by luchillo17** [comment]
Use NVM, easiest setup for both npm & node out there.

**Comment by danielbonifacio** [comment]
In my case, I needed to separately install npm with
``` bash
sudo apt install npm
```
restart my shell and update npm with
``` bash
sudo npm i -g npm@latest
```
then restart my shell again to get it updated

**Comment by TeAmP0is0N** [comment]
> please follow the issue reporting template as specified by the WSL team.
> 
> nodejs provides packages for ubuntu that you can easily install either via their setup script (https://github.com/nodesource/distributions#debinstall) or manually (https://github.com/nodesource/distributions#debmanual).
> 
> ```
> curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```

but npm is not working. I am getting this: 
```bash
npm --version : not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm: : not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm: /mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")
```
