### ISSUE TITLE
[help] Mount qemu image with nbd - modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open 

### ISSUE THREAD

**Issue by mfe-** [Microsoft/WSL#3113]
Hi,
currently I'm using the command `qemu-system-sparc -hda readynas_compile_environment.qcow2 -nographic` for my virtual sparc machine. My next step would be to mount the qcow/qcow2 image. I tried to follow this [guide](https://www.kumari.net/index.php/system-adminstration/49-mounting-a-qemu-image).

Executing the command `sudo modprobe nbd max_part=8` tells me that the module could not be found. So I installed

```
sudo apt-get install qemu-block-extra
sudo apt-get install qemu-utils 
```
I get still the same error message. I'm wondering if this is possible with the current state of WSL or whether I missed something else? Thanks for any help.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.371]   

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

```
sudo apt-get install nbd-client 
sudo modprobe nbd max_part=8                                 
[sudo] password for m:
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-43-Microsoft/modules.dep.bin'                                                                                                     modprobe: FATAL: Module nbd not found in directory /lib/modules/4.4.0-43-Microsoft 
```

* What's wrong / what should be happening instead:
The module should be available

**Comment by therealkenc** [comment]
Same in spirit as #845. There are no Linux kernel modules in WSL because there is no Linux kernel. I don't think `nbd` specifically come up before; in theory you could ask for support over in [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l).
