### ISSUE TITLE
provide option for "normal" mouse selection in WSL console

### ISSUE THREAD

**Issue by lqueryvg** [Microsoft/WSL#3116]
Microsoft Windows [Version 10.0.16299.125]

Mouse selection has always been "special" in Windows terminals. For some reason its eccentric behaviour has been "ported" through to all it's relatives (ConEmu, Cmder etc) rather than being properly fixed.

Try mouse selection in your web browser to see how it should work:

Double left-click a word (on this page) then on the second click keep the left mouse button down and drag over other words. The selection will be extended to included entire words.

Triple-click should do similar for whole lines.

This works in all GUI applications on Mac, Linux & Windows and is an accepted and expected idiom. But not in a Windows command prompt !

If Microsoft really want to embrace unix, I suggest they take a look at the rich set of mouse selection features available in Putty (where you can even choose your own character selection classes) and use that as their benchmark. Also take look at iTerm2 on Mac.

mintty - wsltty seems to be the only viable option right now.

**Comment by fpqc** [comment]
This is on the wrong repository.

[here instead](../console)

**Comment by lqueryvg** [comment]
@fpqc , thanks.

I have logged the issue with the Windows Console but I expect a rather swift rebuttal (along the lines of "why should the Windows Console change for the sake of Unix?").
https://github.com/Microsoft/console/issues/157

However I think I need to clarify...

I am on Windows 10 and opening up the "Ubuntu" shell prompt, and with blind optimism expecting WSL to be some kind of Unix-like experience which integrates with Windows in some way. I thought that WSL might be using it's own terminal emulator to help do this, hence why I logged the issue here, but as you've pointed out it's just using the standard Windows console.

Maybe I'm wrong, maybe they will add options to the Windows Console, but if not my issue is still **here** with WSL - you need to provide a default terminal emulator that has a sensible Unix-like selection mechanism otherwise people from the Unix world will not want to use it, and I don't think that's what Microsoft want right now.

**Comment by fpqc** [comment]
You're mistaken. WSL and console used to be under a single unified project manager, and they were only split up less than a year ago.   They have very good communication with the WSL team and community.

**Comment by lqueryvg** [comment]
@fpqc, you might be right, but I've seen no significant change in the Windows console for well over 10 years (maybe 15?). I will put an old hat to one side, ready for eating.

I guess we will soon find out :smile:

**Comment by fpqc** [comment]
Tons of changes under the hood. Ask any regular on this board.

**Comment by fpqc** [comment]
https://github.com/Microsoft/WSL/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aconsole

**Comment by lqueryvg** [comment]
Careful, you are building my hopes up.

**Comment by zadjii-msft** [comment]
@lqueryvg I'm sorry that you have this opinion that our team hasn't done anything for 15 years, though, that is mostly correct, considering the team was only founded about 4 years ago.

We've been really hard at work to add [a](https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/) [lot](https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/) [of](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/) [new](https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/) [features](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-windows-console-in-windows-10-fall-creators-update/) to the console, though, admittedly, many of them are "under the covers" improvements. 

Honestly, we have hundreds of items on our backlog of improvements we'd like to make to the console. We're not keeping it bad on purpose, we just don't have the developer bandwidth to get everything done immediately. We know that in general, unix terminals are more user friendly than conhost, but we're hoping one day that will no longer be the case, and even linux users will be like "damn, the windows console is actually *pretty good*". We have a long way to go, but we're happy to do the work.

As far as this particular issue goes, I'm going to close this thread, and follow up with the specific feature request in the other repo.

**Comment by lqueryvg** [comment]
@zadjii-msft & @fpqc , I didn't mean to imply that you'd done nothing. Re-reading my comment, I can see how someone on the team might read it that way. I apologise for that - I'm sure you all work very hard.
