### ISSUE TITLE
File system upgrade?

### ISSUE THREAD

**Issue by DDoSolitary** [Microsoft/WSL#3119]
I just noticed that after upgrading to build 17134 `bash.exe` says "Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution..." when launching a distribution from the previous Windows version. I'm wondering what it actually does. Thanks.

**Comment by onomatopellan** [comment]
It's on the release notes. It applies the case sensitivity flag on every folder.

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17093

**Comment by 0xbadfca11** [comment]
It's certain that WSL turning on per-directory case sensitive flags.
![image](https://user-images.githubusercontent.com/7390559/39132906-e777e406-474d-11e8-9e72-4000725c6b79.png)
(I don't know why eleven directories are flagged before launch ubuntu.)

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17107
> Display a message when upgrading the Linux file system directories when moving from a pre-17093 build. For more details on the 17093 file system changes, see the release notes for 17093.

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17093
> When starting WSL for the first time after upgrading to this build, it needs to perform some work upgrading the Linux file system directories. This may take up to several minutes, so WSL may appear to start slowly. This should only happen once for each distribution you have installed from the store.

**Comment by Biswa96** [comment]
Agree with @0xbadfca11, that also happend in my Ubuntu bionic at build 17093. The release page says "Improved case sensitivity support in DrvFs. DrvFs now supports per-directory case sensitivity."

There is another update in Windows 17650. LxssManager.dll shows three resources in RCDATA section. The third one is a `init` file compressed with CPIO and GZIP (though there is another simple `init` file as older builds). `init` becomes larger than older builds and it is now ~93KB.

**Comment by DDoSolitary** [comment]
@0xbadfca11 @onomatopellan @Biswa96 Just checked the flags and you're correct. Thank you very much! 👍

**Comment by Biswa96** [comment]
I try to find the string in those wsl* executables and Lx* DLLs. But I can't find that. Did you?
