### ISSUE TITLE
WSL processes show up with a capital starting letter in Windows task manager

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/WSL#3122]
Processes run under WSL show up with a capital starting letter in the "Processes" tab in the Windows task manager - so for example "Cmake" instead of "cmake", but it applies to all processes I've seen. See the screenshot.

* Your Windows build number: Microsoft Windows [Version 10.0.16299.402]

* What you're doing and what's happening: ![image](https://user-images.githubusercontent.com/4967343/39212085-8dae5582-4805-11e8-9045-dca761b36e66.png)

* What's wrong / what should be happening instead: Task manager should show the correct process name, which is lowercase (e.g. `cmake`)

**Comment by patrikhuber** [comment]
Okay, cool!
Is there any way to upgrade WSL, or is the only way to switch to Windows Insider builds (or wait until the next "consumer update" is released)?

**Comment by ax0** [comment]
Only the latter as far as I know.

**Comment by patrikhuber** [comment]
That would be too bad, thank you @ax0!

**Comment by patrikhuber** [comment]
I can confirm that this is fixed in `Version 10.0.17134.1` (1803) that officially came out today.
