### ISSUE TITLE
Adding WSL in Visual Studio fails with "Failed to archive sysroot [...]"

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/WSL#3124]
I'm following the instructions here: https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/ to the point.
When going to "Tools > Options > Cross Platform > Connection Manager", entering the details, and clicking "Connect", it results in the following error:
![image](https://user-images.githubusercontent.com/4967343/39217420-ddab9966-4817-11e8-9bd3-22a06eb752fb.png)

The log file contains the following:

> liblinux.ExceptionBase: Failed to archive sysroot, command used: 'zip -r /var/tmp/sysroot_bd10b29c-e9ef-409f-94da-ad87165daa75.zip '.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)

* Your Windows build number:  Microsoft Windows [Version 10.0.16299.402]

**Comment by therealkenc** [comment]
Variation #2505 ([message](https://github.com/Microsoft/WSL/issues/2505#issuecomment-330063913)). The Visual C++ for Linux team has a github [here]([url](https://github.com/Microsoft/VSLinux)).

**Comment by patrikhuber** [comment]
@therealkenc Shouldn't WSL's ssh show an error or at least a warning though if you start it on port 22, but Windows is already listening on port 22?

**Comment by therealkenc** [comment]
"WSL's `ssh`" is not well formed. The OpenBSD Foundation has a `ssh` called OpenSSH, and Canonical Ltd. (among others) distributes it. Not a WSL actionable. But to answer your question; no. OpenSSH by default does a `setsockopt(...SO_REUSEADDR...)`, so it will listen even if the port is occupied. This is the case on both WSL and Real Linux (natch). As an experiment, on Real Linux™ you can try for example:
```
$ nc -l 2222
```
... and then in another term:
```
$ /usr/sbin/sshd -D -p 2222
```
OpenSSH `sshd` will fire up without warning. And behave badly.

**Comment by patrikhuber** [comment]
> so it will listen even if the port is occupied

Wow!
Learned something the hard way then. That's quite surprising.
Thank you very much for the explanation :-)
