### ISSUE TITLE
pv: write failed: Input/output error

### ISSUE THREAD

**Issue by mobluse** [Microsoft/WSL#3125]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17128.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I get a bug when I run this in most updated Ubuntu 16.04 for WSL from Microsoft Store.

`clear; curl -s http://www.robvanderwoude.com/files/apple_ansi.txt | dos2unix | iconv -f CP437 -t UTF8 | pv -L 20 -q`

`pv: write failed: Input/output error`

My purpose is to simulate ANSI Art coming over a slow line. I think `pv` should be able to pass a file that can be seen in the console without it.

E.g. this works:
`clear; curl -s http://www.robvanderwoude.com/files/apple_ansi.txt | dos2unix | iconv -f CP437 -t UTF8`

* What's wrong / what should be happening instead:
`pv` should not give an error. This works in WSLtty and `xterm` in VcXsrv.

**Comment by therealkenc** [comment]
Sounds like #636
