### ISSUE TITLE
the kernal parameter vm.max_map_count in /etc/sysctl.conf is don't work!

### ISSUE THREAD

**Issue by vagile-cn** [Microsoft/WSL#3126]
when I set vm.max_map_count in /etc/sysctl.conf and reload the parameter with sysctl -p,
I'll get an error:
sysctl: cannot stat /proc/sys/vm/max_map_count: No such file or directory
and the parameter dosn't work.

**Comment by DarthSpock** [comment]
Ref #1579

**Comment by vagile-cn** [comment]
@DarthSpock thanks you for answer my question
but I mean I can't make WSL kernal parameter work

**Comment by DarthSpock** [comment]
I don't think you'll be able to do anything regarding `systemctl` until `systemd` is working as mentioned in the referenced issue.

**Comment by vagile-cn** [comment]
@DarthSpock all right
There are still a lot of imperfections in WSL = =!

**Comment by DarthSpock** [comment]
There is a [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16571479-support-for-running-systemd) and several related issues open for getting `systemd` working, it'll be a major unblocker of quite a few things including this. 

> There are still a lot of imperfections in WSL = =!

There are quite a few limitations but you'd be surprised at what is possible with WSL.

**Comment by fpqc** [comment]
um, sysctl is not the same as systemctl.  Systemctl is the command and control application for the Systemd daemon.  sysctl.conf is a configuration file that gets loaded on startup that sets certain kernel parameters.

**Comment by DarthSpock** [comment]
I was thinking that sysctl might rely on systemctl or at least systemd. If I'm mistaken, then I learned something new.

**Comment by fpqc** [comment]
Yes you are mistaken. Sysctl is also in freebsd (though freebsd doesn't have a virtual filesystem for its kernel params, so it uses a special sysctl syscall).

**Comment by vagile-cn** [comment]
@fpqc 
thank u for understanding what I mean.
I just try echo 65530>>/proc/sys/vm/max_map_count
but I get an error as same as use "sysctl -p" to reload kernel parameter

-bash: /proc/sys/vm/max_map_count: Operation not permitted

**Comment by vagile-cn** [comment]
@fpqc 
I am thinking about a question.
Is this parameter necessary?
I think the limit of max virtual memory may be in Windows.
is this the reason why can't use the parameter in WSL(Ubuntu).

**Comment by fpqc** [comment]
@vagile-cn That particular parameter of the linux memory manager is not available right now in the WSL driver surface. If you need it for something specific, that will help the developers prioritize it.  If you don't have any particular reason to use it, then don't.

**Comment by vagile-cn** [comment]
@fpqc I just run elasticsearch in WSL = =!

**Comment by fpqc** [comment]
Could you make that memory problem its own issue? That sounds like a bug while this is a feature request

**Comment by vagile-cn** [comment]
@fpqc sure~ I'd like create a new issue when I have time.

**Comment by therealkenc** [comment]
> WSL causes the paged pool of the memory to bloat insanely 

Norton?

**Comment by Dakkaron** [comment]
@therealkenc Nope, I don't run any antivirus except Windows Defender.

**Comment by Dakkaron** [comment]
@rofol: This is the basic problem this issue is about: it cannot be created or set, no matter what user is used (yes, root cannot do it either).

**Comment by shoffmeister** [comment]
WSL does not use a Linux kernel, is not a Linux kernel. Trying to apply Linux kernel parameters to WSL therefore is almost never going to work out as you intend.

The advice from above

> Could you make that memory problem its own issue? That sounds like a bug while this is a feature request

is the only thing that will help you. By creating such a report, you enable the WSL developers to investigate the memory ballooning behaviour and introduce changes into WSL (fix/config etc) to address that behaviour.

It is almost certain, that those Linux kernel /sys settings you are looking for will never pop up on WSL. WSL is intended to run GNU/Linux user-mode applications natively (much in the spirit of the user-mode Linux of many years ago). WSL is not a virtual machine host which emulates hardware, on top of which the Linux kernel runs, on top of which the GNU/Linux user-mode applications run.

**Comment by rofrol** [comment]
@Dakkaron I'm not telling you some basic instruction, but what I actually did and it worked in the sense that:

```bash
$ cat /proc/sys/vm/max_map_count
65530
```

but I couldn't preserve after reboot.

**Comment by shoffmeister** [comment]
Did setting the max_map_count parameter have any effect on the virtual memory manager that is employed by WSL?

**Comment by rofrol** [comment]
@Dakkaron sorry, you are right. I can't set it:

```bash
# echo 65530 >> /proc/sys/vm/max_map_count
-su: /proc/sys/vm/max_map_count: Operation not permitted
```

**Comment by shoffmeister** [comment]
@rofrol, @Dakkaron - there is no such parameter, because there is no Linux kernel. There is a (Windows-layered) "kernel" which implements quite a few syscalls that the Linux kernel exposes. But, still, _there is no Linux kernel_.  Because there is no Linux kernel, the "tweak this Linux kernel setting" instructions you will find all over the Internet will almost never apply.

The only means to make progress for this issue here is that an interested party opens up a separate ticket, describing the memory ballooning behaviour in detail, and the best / fastest way to reproduce it. WSL developers can then review whether some action can be taken.

**Comment by therealkenc** [comment]
> there is no such parameter, because there is no Linux kernel ... the "tweak this Linux kernel setting" instructions you will find all over the Internet will almost never apply

That isn't strictly speaking true. Certain kernel parameters might be emulated. A few already are. Whether `map_map_count` will be one that is emulated I can't tell you, but the _semantics_ of the tunable parameter is independent of the _implementation_ of the tunable. But to your more salient point...

> an interested party opens up a separate ticket, describing the memory ballooning behaviour in detail

Right. The OP skidded off the track from the gate for lack of use case or context (which I gather is ElasticSearch). ElasticSearch I in turn gather has special memory management requirements. If an interested party exists, please reboot this one following CONTRIBUTING.md.

**Comment by shoffmeister** [comment]
@therealkenc . please note the very, very careful, very considerate, and very deliberate use of the word "almost" :)

From my point of view, educating users that WSL is *not* the Linux kernel, but the Windows kernel (whatever that translates to these days in the architectural world) might help in directing these outlier cases into the right direction.

From the more recent issues that I have seen opened on WSL, it would seem as if users think that WSL _is_ the Linux kernel, with all userland (runlevels, init system, and whatever-not) on top of it.

It is *not*, at this time, and (economically speaking) will never be 100%.

That is neither bad in itself, nor good in itself itself. It just means that WSL != any-one-whatever-Linux-*kernel*-version. And people don't see that, don't get that. And up goes the cost of support and down goes the level of user satisfaction. This, I think, is a pity.

(Disclaimer: I went the "let's get those Windows things running on Linux" way about two decades ago. Ah, and "on FreeBSD, NetBSD, Solaris" ....)

**Comment by therealkenc** [comment]
Ran course. Someone motivated could open a well-formed issue following CONTRIBUTING.md along the lines of #1809. "much /proc/sys/vm/* missing" or somesuch. If there is a memory ballooning issue with ElasticSearch (or anything else), ditto.

**Comment by Dakkaron** [comment]
Would it be possible to create that file as read-only with a fitting value in it? I keep getting errors with programs that expect that value to exist, e.g. Elastic Search. I don't care too much about what that value is, but scripts keep crashing because that file does not exist. Maybe just make that file writable but ignored or something.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/93958662-cf250980-fd0b-11ea-8c27-d542455c5c67.png)
