### ISSUE TITLE
Home directory is not working (chmod mainly)

### ISSUE THREAD

**Issue by Aebian** [Microsoft/WSL#3127]
Hi WSL Team,

I have a strange issue that I wasn't able to fix by searching on google.

I have my home folder /home/aebian with a bunch of files in it.
However when doing a chmod on files I get denied. 

The folder is owned by myself and was copied from a Unbuntu system to /mnt/p/_temp/@BKP/aebian

Then I installed the Debian WSL and did a cp -R .* /home/aebian 

The files are getting used since zsh can read the .zshrc file which also includes oh-my-zsh:
![image](https://user-images.githubusercontent.com/7494018/39273347-e66636b8-48b4-11e8-8251-94bc152a65ab.png)
However I'm unable to perform chmod's using my normal aebian account. I need to use sudo or root instead...

Do you have any idea?

OS: Windows 10 Pro x64
Microsoft Windows [Version 10.0.16299.371]
Locale: en_CA
Time Zone: Atlantic TIme (Canada)
→ uname -a
Linux itsAebian 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

==

What I tried:

- Change permissions and owner via chmod
- Go as root via sudo -i and perform same steps.
- re-copy of the files from /mnt/p/_temp/@BKP/aebian

**Comment by Aebian** [comment]
Funny, I told that above:

→ chmod -R 600 .ssh
chmod: cannot access '.ssh/authorized_keys': Permission denied
chmod: cannot access '.ssh/config': Permission denied
chmod: cannot access '.ssh/freenode.pem': Permission denied
chmod: cannot access '.ssh/id_rsa': Permission denied
chmod: cannot access '.ssh/known_hosts': Permission denied
chmod: cannot access '.ssh/known_hosts.old': Permission denied

**Comment by heldchen** [comment]
use `sudo chmod -R 600 .ssh` as the .ssh folder does not seem to belong to your current user. check with `ls -al`. chmod only changes permissions, not the owner. use `sudo chown blah:blah -R .ssh` to change the owner and group.

**Comment by Aebian** [comment]
I know how linux works and also via sudo and even as root changed the owner to aebian many times via ``chmod -R aebian:aebian /home/aebian/``
The complete folder is owned by me. atleast my shell is telling that. The issue here is that the actual owner seems to be someone else but my user aebian is still displayed when using ``ls -la`` and I'm not quire sure if there is another way to force owner of a complete folder.

**Comment by heldchen** [comment]
the screenshot does not show `.ssh`, which is the subfolder you seem to have trouble with... depending how you chown'ed the folders this might be due to the dotfile-handling. `chown *` does normally not include dotted files/folders

**Comment by Aebian** [comment]
![image](https://i.imgur.com/AbUjtHZ.png])

However I just found out that everytime I restart the PC I need to reapply the permissions again using sudo or root.

Any ideas?

**Comment by Aebian** [comment]
Issue seems to be fixed itself randomly after the restart ....

**Comment by tylergoodman** [comment]
any ideas what fixed it? Tried restarting, getting the same error
