### ISSUE TITLE
busybox ash echo weirdness

### ISSUE THREAD

**Issue by agowa338** [Microsoft/WSL#3129]
# Your Windows build number
Microsoft Windows [Version 10.0.17650.1001]

# What you're doing and what's happening
Within Alpine Linux as root (busybox ash):

```
wget https://raw.githubusercontent.com/jirutka/alpine-make-rootfs/v0.1.0/alpine-make-rootfs
echo '714a764b96442f551084fc50941fd1352e15ca6d  alpine-make-rootfs' | sha1sum -c
```

# What's wrong / what should be happening instead
2nd command fails with `can't set tty process group (Operation not permitted)`

Used wsl userland: [Alpine](https://github.com/agowa338/WSL-DistroLauncher-Alpine/tree/3250a42d6bb1b18baed6c232cde87b41d4183a12)
Used shell: ash
Symlinks in the system:
/bin/echo => /bin/busybox
/bin/ash    => /bin/busybox

but it is not a problem of busybox, as doing all of the following works:

```
ash -c "echo '714a764b96442f551084fc50941fd1352e15ca6d  alpine-make-rootfs'" | sha1sum -c
/bin/echo '714a764b96442f551084fc50941fd1352e15ca6d  alpine-make-rootfs' | sha1sum -c
busybox echo '714a764b96442f551084fc50941fd1352e15ca6d  alpine-make-rootfs' | sha1sum -c
```
also using zsh or bash instead of ash

# Strace of the failing command
[gist](https://pastebin.com/uJMdNLHp)

**Comment by Biswa96** [comment]
@agowa338 Yes, that second command does not work. But if you change a little it then works. Try this:
```
wget https://raw.githubusercontent.com/jirutka/alpine-make-rootfs/v0.1.0/alpine-make-rootfs
echo '714a764b96442f551084fc50941fd1352e15ca6d  alpine-make-rootfs' > test.txt
sha1sum -c test.txt
```

**Comment by agowa338** [comment]
I tried to generate a new strace file, but as soon as I specify the "-f" option it works. So I'm unable to provide a `strace -f -o` output, but I can provide a `strace -o` output. But I doubt it will be much different than the one from above
[pipeError.log](https://github.com/Microsoft/WSL/files/1958308/pipeError.log)

**Comment by therealkenc** [comment]
> I just discovered it and would like to have it fixed. 

If you don't hear different, keep one eye on #2786 / #1353. It might be working under `strace` because the child stays alive just long enough.

**Comment by therealkenc** [comment]
I got something today that might be related. This was on 17661 and Ubuntu 16.04.
```
63    waitid(P_PID, 13, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13, si_uid=0, si_status=213, si_utime=0, si_stime=0}, WEXITED, NULL) = 0
63    waitid(P_ALL, 0, 0x7ffffc491380, WNOHANG|WEXITED|WNOWAIT, NULL) = -1 ECHILD (No child processes)
63    clock_gettime(CLOCK_MONOTONIC, {233, 656312000}) = 0
63    epoll_wait(4,  <unfinished ...>
62    +++ killed by SIGKILL +++
```
I don't have a repro anyone wants to hear. The catch is in my case, that `SIGKILL` causes a blue screen. I sent a minidump to secure@microsoft.com and poked @benhillis.

**Comment by therealkenc** [comment]
@agowa338 - please try build [17713](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17713) and see if it addresses your issue with `ash` on Alpine.

**Comment by knottio** [comment]
@therealkenc I had this same issue on Alpine prior to build 17713. Updating to 17713 fixed it.

**Comment by therealkenc** [comment]
Right thanks for the heads up. My [suspicion](https://github.com/Microsoft/WSL/issues/3129#issuecomment-385199804) was correct and this was [Rick Grimes problem](https://github.com/Microsoft/WSL/issues/2786#issuecomment-353813641). Duping for closure.
