### ISSUE TITLE
Whether the WSL is avaliable to run do-release-upgrade ?

### ISSUE THREAD

**Issue by dingyx99** [Microsoft/WSL#3131]
Here is a problem.
Ubuntu has been upgraded to 18.04 LTS which owns a lot of features and fixes.
After reading issues here, many people met problems when do-release-upgrade from trusty to xenial.
So if I upgrade xenial to bionic, will it work well? Or I'll met al lot of crashes?
(Or maybe I'll be the first one to try😂)
Windows Version: 10.0.17134.1 Insider Slow Ring

**Comment by DarthSpock** [comment]
You can run it just fine. Someone already posted in my https://github.com/Microsoft/WSL/issues/2874 that the person was able to successfully upgrade.
