### ISSUE TITLE
Clarify how detailed logs should be conveyed to the WSL team

### ISSUE THREAD

**Issue by chwarr** [Microsoft/WSL#3137]
Please consider clarifying within https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs how these details logs should be sent to the WSL team.

Other sections, like [the BSOD](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#bsods) and [additional information](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#7-additional-information) sections have explicit guidance for their particular contents. This is lacking for detailed logs. If one of these other sections applies, a back reference would be sufficient.

-------------------------

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

N/A

CONTRIBUTING.md as of commit 86682f73d38b20a778dc35d3a461405b46fd5399 in the one that I read.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Attempting to provide details logs to a repro [after they were requested](https://github.com/Microsoft/WSL/issues/3020#issuecomment-372843346).

* What's wrong / what should be happening instead:

I don't know how to get the logs to the WSL team. Other [issues](https://github.com/Microsoft/WSL/issues/3074#issuecomment-378299658) imply that I should not attach them to a GitHub comment. There is no guidance in the detailed logs section.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

N/A

**Comment by DarthSpock** [comment]
> This repo is for the reporting of issues found within and when using Windows Subsystem for Linux.

> Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.

This is at the very beginning. By default when requested to provide logs that can't otherwise be publicly posted, the email address specified above will be where you send the logs to. After you send that email with the logs, you go back to the issue you were experiencing and post a comment specifying you sent an email from "email address" so when they take a look at it, they can link it to the issue.
 
So what they could do is place a link to https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs in the statement above as the instructions themselves are adequate.

**Comment by DarthSpock** [comment]
In your particular case, seeing as you work there...you should probably be able to obtain a direct email so you can keep the communication internal without having to go through the external facing team (of which the WSL team is only a part of).

**Comment by therealkenc** [comment]
Stale for three months....

> I don't know how to get the logs to the WSL team. Other issues imply that I should not attach them to a GitHub comment. There is no guidance in the detailed logs section.

The WSL README.md states the following:

> If there are files required, email the files to InsiderSupport@microsoft.com with: Subject: Forward to WSL Team - RE: github issue <issue #> Body: "Please forward to WSL Team" and include your attachment.

If that verbiage needs to be clarified further the dev team has been amenable to accepting [PRs](https://github.com/Microsoft/WSL/pulls).

**Comment by chwarr** [comment]
Thanks. This fell off my radar. Based on a bug I filed, the process that the WSL appears to want it the e-mail approach. I've added a reference back to section 7 in section 8.

PR: https://github.com/Microsoft/WSL/pull/3442

**Comment by Biswa96** [comment]
Why the `lxss_adss` event tracing is remove from contributing file?

**Comment by benhillis** [comment]
Because it is not used.
