### ISSUE TITLE
wsl.conf does not exist

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3139]
After April update (1803-17134.1), in my WSL installation (Ubuntu) I don't find `wsl.conf`:

```
$ ls -lrt /etc/wsl*
ls: impossibile accedere a '/etc/wsl*': File o directory non esistente
```

Should I reinstall all WSL?

**Comment by Brian-Perkins** [comment]
You can create it if it doesn't exist. Link [here](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/) if you need it.
