### ISSUE TITLE
Win 10 1803: Enter not working consistently in WSL console

### ISSUE THREAD

**Issue by ericblade** [Microsoft/WSL#3140]
Just upgraded to 1803 yesterday.  I'm noticing that the "Enter" key isn't working in my Ubuntu terminal windows, probably close to about 30% of the time I try to use it.  It worked fine yesterday, before the upgrade.  It seems to work fine if I launch the WSL shell in ConEmu.  It also doesn't seem to affect cmd.exe launched from the start menu.  

Any ideas?

**Comment by Biswa96** [comment]
Smash it with a sledge hammer :)

**Comment by ericblade** [comment]
Of course, the first thing I tried before checking out all the other terminal options I had available, was to press it harder, but that didn't seem to really help much at all. :-)

**Comment by therealkenc** [comment]
Use ctrl-m. The enter key is for lightweights.

**Comment by ericblade** [comment]
Heh.  Nope, that didn't work either.

What *did* seem to fix it, is uninstalling "MSI Afterburner", which seems to be highly messed up in 1803.  Closing, since I found what seems to be a fix.

**Comment by Line117** [comment]
https://conemu.github.io/en/BashOnWindows.html#arrows-sol-2
