### ISSUE TITLE
Curl shipped with Windows does not support HTTP2

### ISSUE THREAD

**Issue by fcharlie** [Microsoft/WSL#3141]
**cmd /ver**
```
Microsoft Windows [版本 10.0.17134.5]
```

I found that curl shipped with Windows does not support HTTP2

**C:\Windows\System32\curl.exe**

![dcfb2wyuqaehuq9](https://user-images.githubusercontent.com/6904176/39497081-2a879c46-4dd4-11e8-951a-7c2eb03a8fa0.jpg)

**Other curl binary, Support HTTP2**
![dcfcxqzvqaamgya](https://user-images.githubusercontent.com/6904176/39497083-2da8fcd0-4dd4-11e8-80ad-70c0116add77.jpg)

about curl's blog: [https://daniel.haxx.se/blog/2018/01/13/microsoft-curls-too/](https://daniel.haxx.se/blog/2018/01/13/microsoft-curls-too/)

## How to support HTTP2

By default, CURL support HTTP2 require nghttp2, nghttp2 can build static with vcpkg. we build CURL with OpenSSL support HTTP2 success, but WinSSL maybe failed. (Thanks vcpkg, OpenSSl can build with static.)

curl port: [https://github.com/Microsoft/vcpkg/tree/master/ports/curl](https://github.com/Microsoft/vcpkg/tree/master/ports/curl)

see: [https://github.com/Microsoft/vcpkg/tree/master/ports/curl](https://github.com/Microsoft/vcpkg/tree/master/ports/curl)

**Comment by fcharlie** [comment]
@bitcrazed

**Comment by fpqc** [comment]
This is for [the console team](../../console)

**Comment by bitcrazed** [comment]
Thanks @fcharlie.

@fpqc: not entirely. Will discuss withe the teams.

**Comment by fcharlie** [comment]
@bitcrazed CURL support use WinSSL to support HTTP2 see: https://curl.haxx.se/mail/lib-2018-04/0077.html

**Comment by fcharlie** [comment]
@bitcrazed  I build curl with WinSSL to support HTTP2 success. https://github.com/curl/curl/issues/2591#issuecomment-390668035

**Comment by benhillis** [comment]
Curl.exe is not part of WSL, closing this out.

**Comment by fcharlie** [comment]
@benhillis See: https://github.com/Microsoft/WSL/issues/3141#issuecomment-385861583

**Comment by benhillis** [comment]
@fcharlie - Please clarify what I'm looking at.

**Comment by fcharlie** [comment]
@benhillis According to bitcrazed, although this issue does not belong to WSL, it can be discussed here.

**Comment by therealkenc** [comment]
> Curl.exe is not part of WSL, closing this out.

Almost did that myself from the getgo, but I didn't have a good idea of where the complaint department should be (ie: I couldn't offer a link). There is the [Microsoft/vcpkg](https://github.com/Microsoft/vcpkg) github but that didn't seem right. I doubt `C:\Windows\System32\curl.exe` is pulled from there in real life. The Windows [Feedback Hub](https://www.microsoft.com/en-ca/p/feedback-hub/9nblggh4r32n) I guess. Unless someone has a better suggestion.

**Comment by benhillis** [comment]
@therealkenc - Feedback hub is probably a good bet.

**Comment by DarthSpock** [comment]
Per https://github.com/Microsoft/console/issues/216, apparently the WSL team sorta owns the `curl` binary.

**Comment by jilvin** [comment]
It would have been nice to have support for HTTP/2 shipped in Windows 11.
