### ISSUE TITLE
Unable to setup Ubuntu on windows

### ISSUE THREAD

**Issue by radam0** [microsoft/WSL#3142]
I have enabled Windows Subsystem for Linux on windows power shell. But i am unable to download the Ubuntu app. kindly help me

![image](https://user-images.githubusercontent.com/30886007/39546071-237ef5d2-4e21-11e8-9356-e3f876dd1d78.png)

**Comment by Biswa96** [comment]
What error do you see? Provide a screenshot.

**Comment by DGideas** [comment]
I noticed that it displays:

> See "Available on" below for devices this product runs on. It won't on this one.

Just run ```winver``` and check your Windows' version? It seems your OS version too old?

**Comment by Pushkoff** [comment]
Windows 10 1803
`lxrun /install` 
causes blue screen

**Comment by benhillis** [comment]
@vnikhil5 - Are you running and x86 build of windows by chance?

@Pushkoff - That's not supposed to happen. If you have a MEMORY.DMP file could you forward it along to secure@microsoft.com and say it's for benhill?

**Comment by thinkingcap** [comment]
I had to uninstall Bitdefender on build 1803 to stop the BSOD when starting WSL.
