### ISSUE TITLE
WSL can not stop `cp /dev/urandom` command

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#3144]
Everybody knows that [`/dev/urandom`](http://man7.org/linux/man-pages/man4/random.4.html) generates pseudorandom numbers. When I try this command `cat /dev/urandom` in WSL it shows `cat: write error: Input/output error` (generally expected result). But when I run this command `cp /dev/urandom /mnt/c/XYZ` WSL can't stop that. This command can write approximately 1GB per 10 seconds.

I know that this is "by-design", "Linux issue" etc. Should WSL prevent that type of heavy-file-generation in small time?

**Comment by ChrisJefferson** [comment]
I'm not entirely clear what you want.

As you say, this is exactly how linux / unix has always worked, and copying lots of data through pipes very quickly is a thing people do all the time in unix. I would get very upset if windows decided I couldn't send a few GBs through a pipe into a file whenever I wanted.

**Comment by Biswa96** [comment]
But this command goes continuously untill disk is full if someone doesn't notice CPU and disk usage.

**Comment by ChrisJefferson** [comment]
Lots of commands can fill a disk if you ignore them, writing the logs of many programs to a disk can cause the same problem.

I understand your irritiation, but I can't imagine a way of fixing this without breaking many common unix programs. Windows could introduce a "your disk is nearly full" message (if it doesn't have one already), but that wouldn't be a WSL issue.

**Comment by therealkenc** [comment]
> Should WSL prevent that type of heavy-file-generation in small time?

This one is pretty much asked an answered: "No, WSL should not prevent that". Unless there is a diverge from Real Linux I'm missing. Stuff like `cat /dev/zero > somefile` is a Linux feature not a bug.
