### ISSUE TITLE
wslpath command does not return the windows path for home directory

### ISSUE THREAD

**Issue by mmktomato** [Microsoft/WSL#3146]
```
$ wslpath -w ~
wslpath: /path/to/home: Result not representable
```
Is this intended behavior? I expect following result:
```
$ wslpath -w ~
C:\Users\mkt\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\path\to\home
```

### env
```
>ver

Microsoft Windows [Version 10.0.17134.1]
```

**Comment by 0xbadfca11** [comment]
WSL team says don't modify Linux files from Windows applications.
So I think that wslpath does not provide path conversion except /mnt for Windows applications interoperability.
If provided, will helps modify Linux files from Windows applications.

**Comment by mmktomato** [comment]
Ah~~~ I forgot the prerequisite.
I want to run like:
```
$ AutoHotkey64.exe $(wslpath -w ~/dotfiles/ImDisable.ahk)
```
This is completely read only.
I hope wslpath resolves paths other than /mnt.

**Comment by benhillis** [comment]
This is by-design for now.  Since modifying files inside your Linux file system can cause issues, we do not want to make it easier for users to shoot themselves in the foot.

**Comment by mmktomato** [comment]
I see. I understand my demand is potentially dangerous.

**Comment by espoelstra** [comment]
You may be able to work around this using https://brianketelsen.com/going-overboard-with-wsl-metadata/ if you read the post and pay special attention to the "Update" section at the end.

**Comment by nic-hartley** [comment]
@benhillis That's what `--force` and a warning is for. `rm --no-preserve-root -rf /` doesn't say `Result not representable`. Sometimes you _want_ to do "stupid" things.

**Comment by pkruk2** [comment]
I wanted to save ssh key generated with putty into ~/.ssh. Is it safe or is it not safe as per "Since modifying files inside your Linux file system can cause issues, we do not want to make it easier for users to shoot themselves in the foot." ?

If it is safe, how can I know where is the ~/.ssh located? (from Windows perspective)

**Comment by pkruk2** [comment]
There's more details about this in https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/

I think MS said they are going to lift this limitation in future Windows update.

**Comment by ivictbor** [comment]
> WSL team says don't modify Linux files from Windows applications.
> So I think that wslpath does not provide path conversion except /mnt for Windows applications interoperability.
> If provided, will helps modify Linux files from Windows applications.

But still, this is not cool, I just want to open folder with virtualenv sources in windows, not to edit, but to open it in IDE

**Comment by ssbarnea** [comment]
Something clearly changed as on WSL2, `wslpath -w ~` does report what is expected to. 

In order to attempt to reproduce what happens with GHA runners which have only WSL1, I made the mistake for trying to convert my Ubuntu from 1 to 2.
```
wsl --set-version Ubuntu 1
Conversion in progress, this may take a few minutes...
# Two hours later and it will completely hogged.
```
