### ISSUE TITLE
Hitting CTRL+C doesn't stop docker-compose.exe containers (Docker for Windows / Ubuntu 16 WSL)

### ISSUE THREAD

**Issue by nickjj** [Microsoft/WSL#3147]
* Your Windows build number:  Version 10.0.17134.1 (Windows 10 Pro, Spring 2018 edition)

It's also worth mentioning this problem happened with earlier versions of WSL too. I'm also running Ubuntu 16 inside of WSL with the version of Bash that comes included.

* What you're doing and what's happening:

I have Docker for Windows installed which installs both the Docker daemon and Docker Compose. You can access `docker-compose.exe` directly from inside of WSL. For example you could start up a project by running `docker-compose.exe up`.

* What's wrong / what should be happening instead:

Everything loads in the foreground of the process like you would expect, but pressing `CTRL+C` does not terminate any containers. The `^` character gets added to the screen  and you drop back into your prompt.

But if you run a `docker ps` you'll notice everything is still running. This is not related to the bug where Docker Compose occasionally doesn't stop containers with an ABORT message. This happens every single time.

The expected outcome would be that all of the containers managed by Docker Compose for that project would stop and then you would regain control over your terminal.

* Workaround for now:

Of course you could type `docker-compose.exe stop` afterwards but that's not fun.

Alternatively you could also install Docker / Docker Compose inside of WSL and configure Docker to use your Docker for Windows host. This is what I do for now but it's not ideal since you need to keep both your WSL and Docker for Windows versions in sync for both Docker and Docker Compose.

**Comment by benhillis** [comment]
I suspect that this is fixed in 17618. #3160 and others.
