### ISSUE TITLE
request: create a new "distribution" with different root

### ISSUE THREAD

**Issue by bbulkow** [Microsoft/WSL#3151]
The WSL system seems to create a '/' and associated Linux directories at a certain position in the NTFS file system - when you install a "distribution".

What would be super-duper-great is to expand the system just a little, and allow me to create a .... "container" ? "shadow-distribution" ? from a particular distribution.

Thus I could have two "debian 9" based distributions. They show up in the distribution list, I guess, because I'll want to launch them at different times for different purposes. Let's say one has Python 3.6 installed, one has python 3.5 installed, because I have some different dev tools....

This seems, from the outside, like it should be easy. You already have the ability to manage parallel distributions, they already must have different "root mappings". Just allow me to create them simply.

You know, like containers and virtual machines. This is so terribly useful, because Linux has "DLL Hell" like no one's business and it's great to be able to uplevel a package or two ( or downlevel it ) and get some work done for a few days, and blow it away.

If you can manage this, I can really stop using Docker which doesn't have great integration with Windows.

Thanks!

**Comment by therealkenc** [comment]
#1856
