### ISSUE TITLE
ijar's problem

### ISSUE THREAD

**Issue by Uldiniad** [Microsoft/WSL#3157]
* Your Windows build number: Microsoft Windows [Version 10.0.17661.1001]

* Steps to reproduce:
1. git clone https://github.com/LineageOS/android_prebuilts_build-tools.git
2. cd android_prebuilts_build-tools/linux-x86/bin/
3. wget https://github.com/cs-au-dk/thor/raw/master/tools/jacocoant.jar
4. ./ijar jacocoant.jar

* What you're doing and what's happening: 
I'm attempting to run ijar on wsl and consistently get this output on .jar files
`ftruncate(fd_out, GetSize()): Invalid argument
Aborted (core dumped)`

* What's wrong / what should be happening instead:
should successfully complete as on native Ubuntu

* Strace of the failing command, if applicable: 
https://gist.github.com/Uldiniad/cbc1da569f93253e53c25dac9cb83d45

* Related workaround:
https://review.lineageos.org/#/c/LineageOS/android_build/+/208102/5/tools/ijar/zip.cc

**Comment by benhillis** [comment]
Some more repro steps would be useful.

**Comment by Uldiniad** [comment]
@benhillis I've added the repro steps, I apologize that I can't make it much simpler than this.

**Comment by Uldiniad** [comment]
I mean, for shorter repro it could be a matter of just cloning the repository containing the tool that fails. In this case ijar which is here: https://github.com/LineageOS/android_prebuilts_build-tools/tree/lineage-15.1/linux-x86/bin and run it against some test files

**Comment by onomatopellan** [comment]
Easiest repro
```
git clone https://github.com/LineageOS/android_prebuilts_build-tools.git

cd android_prebuilts_build-tools/linux-x86/bin/

wget https://github.com/cs-au-dk/thor/raw/master/tools/jacocoant.jar

./ijar jacocoant.jar
```

> ftruncate(fd_out, GetSize()): Invalid argument
> Aborted (core dumped)
>

**Comment by Uldiniad** [comment]
thanks @onomatopellan

**Comment by Uldiniad** [comment]
@benhillis just wanted to note I've simplified the strace and the steps to reproduce on the OP as much as I could. should be simple to figure what's going on

**Comment by therealkenc** [comment]
> should be simple

Indeed. #902
