### ISSUE TITLE
Error: /proc must be mounted

### ISSUE THREAD

**Issue by jerrysoft-x** [Microsoft/WSL#3159]
Hi,

I'm using WSL (Ubuntu) on WIn 10, I got the following, but it looks already mounted, I found an issue someone said this problem will be fixed, but it didn't help any...Please give some suggestions, thank you!

$ ps
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
$ sudo ps
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
$ mount
rootfs on / type rootfs (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=204320k,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)

**Comment by therealkenc** [comment]
More importantly repro steps leading to the fail. `ps` is not the repro for this.

**Comment by jansaasman** [comment]
Does the closed sign above indicate the issue is also solved?
