### ISSUE TITLE
.exe CLI programs called from WSL don't work with input/stdin from WSL

### ISSUE THREAD

**Issue by theoDiefenthal** [Microsoft/WSL#3160]
I'm not quite sure if this is a duplicate of https://github.com/Microsoft/WSL/issues/2406 or any other related stdin topics, but all the issues I found seem to be rather limited in affected scope (e.g. just affecting vagrant), whereas in my case, anything related to calling an .exe from WSL seems to not work as soon as stdin is involved. 

Here are two examples:
```bash
cd /c/Program\ Files/PostgreSQL/9.6/bin/
# Following works fine
psql.exe --help
# Following blocks indefinitely:
psql.exe --username=postgres -W
Passwort für Benutzer postgres:
```

I get a stdin, but I can't enter anything in there. Clicking ENTER does not hat any effect. Event CTRL+C doesn't kill the process. I have to close the opened WSL.exe terminal and reopen it in order to issue any more commands.

Same goes for a docker-compose I just wanted to run (Which is not a password stdin prompt, but just a standard stdin prompt):
```bash
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin"
git clone https://github.com/influxdata/TICK-docker.git
cd TICK-docker/1.3
# Following works and starts the database InfluxDB:
docker-compose.exe up -d
# Following will again get stall, as influxdb-cli is a CLI program which expects the user to produce some input followed by ENTER to issue commands. 
docker-compose.exe run influxdb-cli -precision rfc3339
```

The expected behavior: I can interoperate with .exe files the same way in WSL.exe as I can from PowerShell, i.e. I can write characters from my keyboard and press ENTER.
What's actually happening: I can not enter anything. I just have a blinking cursor any any key I press doesn't have any effect at all so that I have to close the window. 

As mentioned in the beginning, I don't know if this is related to the "stdin" to "filehandle" and vice versa thing or not, but this limits in my point of view the possibilites with using WSL against windows executables quite a lot, so that there is a huge need for a proper solution or at least a workaround. 

* Your Windows build number: Microsoft Windows [Version 10.0.16299.371]

**Comment by therealkenc** [comment]
> Microsoft Windows [Version 10.0.16299.371]

Likely #2370. Try Spring Creators and ping this issue if it remains unresolved.

**Comment by theoDiefenthal** [comment]
I just updated to the new windows version but still have pretty much the same issue:
ver prints Microsoft Windows [Version 10.0.17134.1]

Well, it's not entirely the same. 
Case 1: everything behaves the same way.
Case 2 (with docker-compose): I am now able to make keyboard inputs and see them in the console. Even ENTER works and starts a new line, but it is not caught. I am just typing and the CLI is not doing anything with my input.... So it is not catching up properly with my ENTER key?! 
![grafik](https://user-images.githubusercontent.com/4670569/39764117-340a7882-52df-11e8-95e2-a3d5cb15c6a5.png)
whereas in PowerShell I get:
![grafik](https://user-images.githubusercontent.com/4670569/39764205-640d525c-52df-11e8-8c6e-edbc99d4f471.png)

So it even prints out a bit more to stdout which is not shown in my WLX.exe / bash.exe (tried with both)

**Comment by therealkenc** [comment]
Alright. You'll need a repro for this to have a fighting chance tho.

**Comment by theoDiefenthal** [comment]
As I already wrote, execute in WSL.exe or bash.exe the following:
```
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin"
git clone https://github.com/influxdata/TICK-docker.git
cd TICK-docker/1.3
# Following works and starts the database InfluxDB:
docker-compose.exe up -d
# Following will again get stall, as influxdb-cli is a CLI program which expects the user to produce some input followed by ENTER to issue commands. 
docker-compose.exe run influxdb-cli -precision rfc3339
```
Assuming that git and Docker for Windows is installed. Once the `docker-compose.exe up -d` was settled, you can also open PowerShell and do `docker-compose.exe run influxdb-cli -precision rfc3339` to demonstrate that this is working.

**Comment by theoDiefenthal** [comment]
Does it mean that I'll have to wait half a year now for the next major windows 10 upgrade in order to test? Or is there another way to upgrade the version? Sadly, I can't agree to the insider preview program terms and conditions on my work machine..
