### ISSUE TITLE
Projects checked out using wsl svn unable to be built with visual studio 2013 since 1803 update.

### ISSUE THREAD

**Issue by archer0001** [Microsoft/WSL#3163]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Attempting to compile a project with any uppercase characters in the directory / file names checked out using svn fails with a file not found error.
The same project checked out with tortoise svn in a different directory succeeds.
This is new behavior since the 1803 update.

* What's wrong / what should be happening instead:
Successful compilation.

I suspect this has something to do with the case sensitivity added recently.  After running process monitor, I notice that the build that succeeds' path is:
`C:\projects\Hello_World_2\WSLTest`
wheras the build that fails' path
`C:\projects\personal\Hello_World_2\wsltest`
despite being the same capitalization showing up in the explorer window.

Additionally, if I copy the project that failed to a different location and attempt to build, it succeeds.  Finally, if I delete the source project, copy the new one back, it fails again, leading me to believe that something is persisting in the environment somehow.

I have attempted to set the DrvFsAllowForceCaseSensitivity registry key to revert back to the previous behavior, but problem appears to persist even after a reboot.

I have PML files captured from process monitor that I intend to send in, just not attached here due to privacy concerns.

Error:
![image](https://user-images.githubusercontent.com/8215860/39713729-d02c44ba-51f5-11e8-83c5-2e6263f130c3.png)

Filtered log of bad compilation:
![bad](https://user-images.githubusercontent.com/8215860/39713912-678d2d7e-51f6-11e8-9398-5a55da7eabc9.png)

Filtered log of good compilation:
![image](https://user-images.githubusercontent.com/8215860/39713952-8fa7f7f8-51f6-11e8-8da3-a85394978c0e.png)

**Comment by archer0001** [comment]
![image](https://user-images.githubusercontent.com/8215860/39713599-554f0412-51f5-11e8-8be6-4fb905af27ac.png)

**Comment by Biswa96** [comment]
Try this to enable case sensitivity https://github.com/Biswa96/WSL_Reverse/blob/master/setCaseSensitiveInfo.cpp

**Comment by Biswa96** [comment]
Try `fsutil` command to enable case sensitivity.

**Comment by archer0001** [comment]
I tried

**Comment by archer0001** [comment]
I suspect something gets tagged when a wsl process creates a file and it isn't limited to svn.  If I check out the file using a windows process and wsl's svn updates it, I don't get the same issue.

**Comment by archer0001** [comment]
Sadly, I've tested with both the metadata option turned on and off, it doesn't appear to affect how visual studio or cl.exe can see the files.

**Comment by DarthSpock** [comment]
Ok for giggles, since VS 2013 wasn't developed with WSL in mind, have you tried the latest version out for 2016? Not sure if you're able to test but if it compiles fine then at least know where the issue lies. If not, you still might be able to file an issue with the VS Code folks so if it's something with WSL, they can at least prove as much by showing where the problem lies to make it easier for the WSL team to fix.

**Comment by archer0001** [comment]
For giggles, built with the latest and greatest VS2017.  Same problem of being unable to locate the file to build.

I don't think it's something special about visual studio, just that it's possibly exposing something that wsl is changing in the filesystem that's affecting non wsl processes.

**Comment by tLambda** [comment]
I'm experiencing the same problem.   We check out our code on an Ubuntu box, and then rsync the source files over to a windows build machine using WSL/Ubuntu.

If files are rsynced over to a machine running 1803, msbuild reports a bunch of "No such file or directory"  errors which stops it from compiling.

If I copy the rsync'ed files to another directory using explorer, it will compile successfully.  If I move the files, they retain the same problem.

I can't see any difference in the file attributes and permissions exposed by windows.

**Comment by archer0001** [comment]
@tLambda Thank you for pointing me at 2937.  I hadn't tried editing wsl.conf.  I had just unmounted and remounted c: with the different case options to test what was going on.  I also had left the same code checked out there while attempting the different mount options.

I believe that 2937 and this ticket describe the same underlying issue.

**Comment by therealkenc** [comment]
Duping into #2937 as landing zone for Spring Update case sensitivity issues.
