### ISSUE TITLE
Apache fails to start on Ubuntu 1604 after Windows 10 Spring Creators Update 1803

### ISSUE THREAD

**Issue by grandgeorg** [Microsoft/WSL#3164]
Windows build number: Microsoft Windows [Version 10.0.17134.1]

After starting Ubuntu (via C:\Windows\System32\bash.exe) I try to start Apache via

```
sudo /etc/init.d/apache2 start
```
or (as now services may be supported)
```
sudo service apache2 start
```
In both cases I get the following error:

```
 * Starting Apache httpd web server apache2
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
```

Before the Windows 10 1803 Update everything worked fine.
I also tried to reinstall apache - no difference.

**Comment by grandgeorg** [comment]
I found the problem. With the update to 1803 the service W3SVC (WWW Publishing Service) got activated in Windows. That caused the error. After turning the service off everything works again.
See also https://github.com/Microsoft/WSL/issues/1921

**Comment by hevekerl** [comment]
Thank you very much. I've been tearing my hair out :-D
