### ISSUE TITLE
Error 0x80070005 when trying to launch ubuntu

### ISSUE THREAD

**Issue by belenko** [Microsoft/WSL#3166]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.17134.1]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
This is on a reasonably fresh Win 10 Enterprise install (i.e. not an upgrade from a previous build).

After installing WSL and Ubuntu via store, whenever I try to launch it (via "Launch" button in the Store app or via command line) I am getting following error:
```
C:\Users\xyz>ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
```
`lxrun /install` goes on to download distro but then bails out with same error:
```
C:\Users\xyz>lxrun /install
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

This will install Ubuntu on Windows, distributed by Canonical and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Microsoft Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070005
```

* What's wrong / what should be happening instead:

Expectation is that Linux session should start.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

ETL traces:
[lxss_traces.zip](https://github.com/Microsoft/WSL/files/1983312/lxss_traces.zip)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Duplicate of #3020.
