### ISSUE TITLE
Yet another Error: 0x80070005 on launching WSL (any distro)

### ISSUE THREAD

**Issue by krader-amdocs** [Microsoft/WSL#3167]
The beta version of WSL worked on this laptop but no version has worked since the Windows update following the official release of the Microsoft Store based version in 2017.

The first appearance of _Error: 0x80070005_ occurs in and infinite loop during installation of the Ubuntu (or any other) distro, after prompting for a default user name. 

Ctrl-c required to terminate installer.

The error recurs immediately on invoking ubuntu.exe thereafter.

Zip attachment contains logs created when attempting to launch Ubuntu with `start_lxcore_trace.cmd` enabled.

[lxcore_logs.zip](https://github.com/Microsoft/WSL/files/1984226/lxcore_logs.zip)

**Comment by Biswa96** [comment]
You didn't mention Windows build version. I see the logs. The problem may be in wsl.exe or bash.exe with COM initialization (CoInitializeEx). Did you try to start or restart the LxssManager service? 
Try this command as administrator: `sc start LxssManager`.

**Comment by Line117** [comment]
Sorry for such an answer. But try uninstall/install lxss from the beginning.
Copy the lxss folder to restore the settings.

**Comment by benhillis** [comment]
Dupe #3020
