### ISSUE TITLE
Bugcheck (BSOD) when using Apache Tomcat

### ISSUE THREAD

**Issue by wkbrd** [Microsoft/WSL#3168]
* Your Windows build number: Version 10.0.17134.

* What you're doing and what's happening:  

1. Install Java 8 JRE
2. Unpack apache-tomcat-7.0.86
3. Run bin/startup.sh
4. Wait a minute
5. Navigate to http://localhost:8080/ in Edge
6. Click on Server Status
7. System will bug check (BSOD) 

and then reboot.  (This does not happen on all systems tested)

* What's wrong / what should be happening instead:
System should not crash and instead Server Status should cause a pop-up with username and password to be presented.  This problem has also happened via using a "curl" command pointed at http://localhost:8080.

* Strace of the failing command, if applicable:  
N/A

An associated mini-dump file has been e-mailed to secure@microsoft.com as of 5:33 PM ET.

**Comment by wkbrd** [comment]
An associated mini-dump file has been e-mailed to secure@microsoft.com as of 5:33 PM ET.

**Comment by sunilmut** [comment]
@wkbrd - Thanks for the dump. It seems like WSL is not the culprit here. Fingers are pointing at the `lcencvm.sys` driver from `Sophos`, maybe `Utimaco`? Looks like a bug where the driver is freeing a memory that is already freed. `Arg2` (pool tag) might help the driver developer get closer.

You can check for a driver update for lcencvm. If that doesn't solve the problem, try contacting their customer support.

```
0: kd> !analyze -v

BAD_POOL_CALLER (c2)
The current thread is making a bad pool request.  Typically this is at a bad IRQL level or double freeing the same allocation, etc.
Arguments:
Arg1: 0000000000000007, Attempt to free pool which was already freed
Arg2: 0000000031726d58, Pool tag value from the pool header
Arg3: 0000000004360000, Contents of the first 4 bytes of the pool header
Arg4: ffffe5861c963010, Address of the block of pool being deallocated 

0: kd> k
Child-SP          RetAddr           Call Site
ffff8386`82ad7c38 fffff800`3cd9403c nt!KeBugCheckEx [minkernel\ntos\ke\amd64\procstat.asm @ 140]
ffff8386`82ad7c40 fffff800`69f2e320 nt!ExFreePoolWithTag+0xfdc [minkernel\ntos\ex\pool.c @ 5150]
ffff8386`82ad7d20 ffffe586`1cf81010 lcencvm+0x2e320
ffff8386`82ad7d28 00000000`00000000 0xffffe586`1cf81010
```

**Comment by wkbrd** [comment]
If you are still experiencing this problem, please try installing an updated Sophos SafeGuard Client, version 8.10 or newer.  The latest version appears to have fixed this issue.
