### ISSUE TITLE
WSL kernel as Linux container implementation

### ISSUE THREAD

**Issue by SkryptX** [Microsoft/WSL#3169]
I do see huge potential in a collaboration of the WSL with the Docker for Windows team. As it stands the Linux container support in Docker for Windows is pretty lackluster. If the WSL team collaborates with the Docker team and shares information about the implementation and WSL kernel, it would be possible to drop the need for Hyper-V and other virtualization technology. It would enable "native" Linux container support which would be a huge step and go a long way in a modern Windows OS.

I file this issue here since I found no other way of contacting the correct people. It seems the first step would have to be from the WSL team as WSL is not open source.

**Comment by SkryptX** [comment]
I've seen that and it seems that WSL is close to release fully featured version soon. The uservoice page doesn't have major issues on it anymore. But for Docker, it seems, that WSL is just an unnecessary layer. If Docker for Windows could utilize the kernel of WSL directly, it would probably benefit a lot in terms of performance and integration.

**Comment by therealkenc** [comment]
#2114 #1856 etc etc
