### ISSUE TITLE
How to resolve "systemctl" command problem?

### ISSUE THREAD

**Issue by redscience** [Microsoft/WSL#3170]
In Debian problem is:
root@win:~# systemctl
System has not been booted with systemd as init system (PID 1). Can't operate.

And in Ubuntu problem is:
root@win:~# systemctl
Failed to connect to bus: No such file or directory

**Comment by Seriell** [comment]
As far as I understand, WSL doesn't use systemd, so `systemctl` can't be used.

**Comment by therealkenc** [comment]
#1579 etc. Landing zone is #994

**Comment by unihon** [comment]
this problem let me head big all day
