### ISSUE TITLE
Failed to ssh localhost

### ISSUE THREAD

**Issue by xiligey** [Microsoft/WSL#3173]
![12](https://user-images.githubusercontent.com/17290149/39862116-64353c80-5475-11e8-858d-c12dc6a8d552.png)

I have tried some ways from  @issues2729, but still failed to ssh localhost.

```bash
xiligey@DESKTOP-9NNPCP8:~$ sudo /usr/sbin/sshd -d -p 2222
[sudo] password for xiligey:
debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: private host key #0: ssh-rsa SHA256:31rf3rSuM67fNm2WneaMzIyJq4JttT2mDk7B+UvCtmA
debug1: private host key #1: ssh-dss SHA256:PJGq7XlOESo1SRfi6adWXPlketkhvcsC1vR/epk141g
debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:3KSlicDZcCsHygwnsjDvkLcUPQQnrAF5S6nuFZgVshw
debug1: private host key #3: ssh-ed25519 SHA256:ZGScLJXFJImZdAnTQeRyhZDJ0JHy/DLLSNQzznxnwT8
Missing privilege separation directory: /var/run/sshd
```

I tried to shut down the windows internal ssh server in services.msc. But it can't help.

**Comment by xiligey** [comment]
I finally fixed it with two steps!
1. I add this into file  /etc/hosts.allow:
ssh:ALL:allow
sshd:ALL:allow

2. remove openssh-server, then install it again.
```bash
sudo apt-get remove openssh-client openssh-server
sudo apt-get install openssh-client openssh-server
```

**Comment by mysaggar** [comment]
I tried the same steps as specified.
I tried changing the /etc/hosts.allow file, /etc/ssh/sshd_config file for changing the port, but still, I am unable to ssh to localhost.
Below are the contents of my /etc/hosts.allow file:
![image](https://user-images.githubusercontent.com/22439570/65449443-9fbd9180-de58-11e9-959f-a5c94a43fd85.png)

Below are the contents of my /etc/ssh/sshd_config file

```
Port 2222
PermitRootLogin no
AllowUsers hduser
UsePrivilegeSeparation no
ChallengeResponseAuthentication no

UsePAM yes
X11Forwarding yes

PrintMotd no

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

Subsystem       sftp    /usr/lib/openssh/sftp-server
```
and here is the ss of my error
![image](https://user-images.githubusercontent.com/22439570/65449850-73eedb80-de59-11e9-991e-d80a49c74231.png)

**Comment by ICYPOLE** [comment]
k

**Comment by iptoux** [comment]
Just create Directory "/var/run/sshd" or "/run/sshd" on sshd server, then it's working.
