### ISSUE TITLE
Odd issues with SSH in xfce term - possibly I/O related?

### ISSUE THREAD

**Issue by kenshen112** [Microsoft/WSL#3182]
This occurs on any build of windows 10 / wsl with SSH capabilities, I understand that issues with xorg aren't necessarily on the front of your menu's so to speak but I thought this interestingly worth mentioning. 
To start off I am a CS student as such to program and submit assignments I have to access the schools linux servers via ssh. If I open a plain xorg free wsl session and SSH directly from the console what ever one I may be using everything's great and awesome. However if I'm using a terminal on a desktop rendered by an xserver through wsl like the xfce4 desktop using the xfce4 terminal, The entire SSH session slows significantly whilst XFCE and wsl seem to run at normal speed, everything from entering simple commands to editing in emacs is so significantly slowed by this use case that it's almost entirely unusable.

**Comment by therealkenc** [comment]
> If I open a plain xorg free wsl session and SSH directly from the console what ever one I may be using what ever one I may be using everything's great and awesome

`ENOTASENTENCE`

I'll interpret this to mean ssh runs fine for you with a WSL session started from inside cmd.exe.

> However if I'm using a terminal on a desktop rendered by an xserver through wsl like the xfce4 desktop using the xfce4 terminal, The entire SSH session slows significantly

The OpenSSH client (`ssh`) should perform the same in a xfce4 terminal running in Xming or VcXsrv as anywhere else. One doesn't really have to do with the other, and it is a common scenario. Hence the chirping crickets. About your best way forward would be to start eliminating variables on your specific setup, starting de-minimis and building up from there. You might for example try other latency sensitive tests like a [netcat](https://linux.die.net/man/1/nc) client server pair and see if you observe the same slowness. But as to why you are observing poor latency while others (including myself) are not, I can't give you much in the way of specifics based on the information provided. Bonne chance.
