### ISSUE TITLE
hiccup w/ tcp stream occuring only Windows 10 WSL

### ISSUE THREAD

**Issue by girng** [Microsoft/WSL#3186]
hello everyone at WSL. i created an issue in the crystal-lang repo: https://github.com/crystal-lang/crystal/issues/6090

and unfortunately, it looks like this could be related to WSL. in fact, i think it is 99% because it doesn't happen on debian 9 ( a cheap $1.99 vps), and also another contributor  said he can't replicate it either. and he's not on WSL

have there been any updates to WSL in the networking, local unix pipes, or tcp department by chance, since late 2017? if anyone has time, if you can, chime in on what could possibly be going on?  

i'm not sure how else to debug this or investigate it further, as it could be something happening internally in the kernel (of which is beyond my scope of knowledge).

thank you for reading

**Comment by onomatopellan** [comment]
Which Windows 10 build are you running (WIN+R-> winver)? I just tested in latest April 2018 update (build 17134.48) and I cant notice any hiccup. 

You can see all the changes in the [release notes.](https://docs.microsoft.com/en-us/windows/wsl/release-notes)

**Comment by onomatopellan** [comment]
With that server.cr and `server = TCPSocket.new("0.0.0.0", 9300)` on the socker.cr there are no hiccups nor zeros. Values are always 99, 100, 101, 102. This is after installing crystal_0.24.2-1_amd64.deb BTW.

**Comment by girng** [comment]
what the hell, so there is no hiccup for you on WSL. this makes no sense.  why is happening to me what have i done

**Comment by onomatopellan** [comment]
Dunno what's happening. You can try to post here an strace of server.cr and maybe @sunilmut can help you better.

**Comment by girng** [comment]
@onomatopellan awesome! i'm very new to linux, so took me a while to get strace working, so i can only TRACK when the messages are sent (otherwise, it would have been a 615KB file :P), sorry for the wait!

so, i did `sudo strace -o strace.txt -p 1920` after i started server.cr. ran socket.cr for 5 seconds and stopped. (saw the hiccup happen).

here is strace.txt:
https://paste.ee/p/MgPzb

**Comment by therealkenc** [comment]
> upload it here dragging and dropping the file in the reply box

Or linking a [gist](https://gist.github.com/) may increase the number of eyeballs clicking through. I am not convinced we're going to see syscall fails here, but it might shed some light.

Might want to back up a bit and experiment with `nc` just to eliminate external factors. In one term:
```
nc -l 9300 # or whatever port
```
In another:
```
nc localhost 9300
hello world
etc
etc
```
See if you are getting any 'hiccups'.

**Comment by girng** [comment]
@therealkenc tried the `nc`, no hiccups. thanks for suggestion =]
@onomatopellan ty for the commands

okay this is really weird @onomatopellan when i run the server with your strace command, the hiccups don't happen.

**Comment by onomatopellan** [comment]
It's not the first time that I read an strace makes a problem impossible to reproduce. It could be a race condition, so yes, you should upload the strace files to gist as @therealkenc stated.

It could be related to multithreading. Which CPU do you have? My test were on an old E2200 (2 cores).

**Comment by girng** [comment]
@onomatopellan hi again! cpu: i7 2600. straces:
[straces.zip](https://github.com/Microsoft/WSL/files/1999084/straces.zip)
Gists: [server.trace](https://gist.githubusercontent.com/girng/5457f4c4a25c220c690d1fb8db069f39/raw/9590e2df6dc2f170d0992b284610d94811ba8785/server.trace) and [socket.trace](https://gist.githubusercontent.com/girng/5457f4c4a25c220c690d1fb8db069f39/raw/9590e2df6dc2f170d0992b284610d94811ba8785/socket.trace)

**Comment by girng** [comment]
I am a victim of The Nagle Algorithm.

you have to set `server.tcp_nodelay = true` (Disables The Nagle Algorithm) on the server.cr, and socket.cr. The hiccups don't happen.

thank you to @onomatopellan and @therealkenc for helping me and giving me the motivation to trial and error. WSL is great, i will still use it!
