### ISSUE TITLE
WSL sudo apt-get update error

### ISSUE THREAD

**Issue by dblock247** [Microsoft/WSL#3188]
Info: Window Version 10.0.17134.48

I installed wsl and the first linux distro I tried was Debian. It installed correctly but when it prompted to enter the username I got the following repeating message

passwd: user 'username' does not exist.

So I uninstalled Debian and installed Unbuntu. This time I was able to enter a username and password. This issue comes when I try to run "sudo apt-get update" I get the following errors.

```
Reading package lists... Error!
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.T2LTnp - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.TTEUlL - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.n6Ilk7 - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.pMDcjt - IsAccessibleBySandboxUser (13: Permission denied)
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/binary-amd64/Packages  Could not open file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-amd64_Packages.xz - open (5: Input/output error) [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/Packages  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_binary-amd64_Packages.xz - open (5: Input/output error) [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages.xz - open (5: Input/output error) [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/binary-amd64/Packages  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages.xz - open (5: Input/output error) [IP: 91.189.88.152 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.b4ZVQL - RemoveCaches (13: Permission denied)
E: Problem renaming the file /var/cache/apt/pkgcache.bin.LaDPtw to /var/cache/apt/pkgcache.bin - rename (13: Permission denied)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
```
running "strace -o sudo apt-get update" results in:

```
Reading package lists... Done
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.LaDPtw - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.b4ZVQL - RemoveCaches (13: Permission denied)

```
Please let me know how to fix this issue.

**Comment by dblock247** [comment]
@therealkenc  so I have tried uninstall and reinstalling with no results. I even removed wsl rebooted and tried again. There is one strange things I notices. When I used the sudo command It prompts me for a password with a username that was created on the first Install attempt. The second time around I used a different user name so that old one shouldn't exist. 

I ran your suggested command and the results are below. 

`Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Ign:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Err:5 http://security.ubuntu.com/ubuntu xenial-security Release
  Could not open file /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_Release - open (5: Input/output error) [IP: 91.189.88.162 80]
Err:6 http://archive.ubuntu.com/ubuntu xenial-updates Release
  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_Release - open (5: Input/output error) [IP: 91.189.88.161 80]
Err:7 http://archive.ubuntu.com/ubuntu xenial-backports Release
  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-backports_Release - open (5: Input/output error) [IP: 91.189.88.152 80]
Ign:8 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:11 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en
Ign:8 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:11 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en
Ign:8 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:11 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en
Err:8 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
  Could not open file /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages.xz - open (5: Input/output error) [IP: 91.189.88.162 80]
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:11 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en
Reading package lists... Error!
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.cl2Mrt - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.6y6q2D - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.ujhXDO - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.ily6fZ - IsAccessibleBySandboxUser (13: Permission denied)
E: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Problem renaming the file /var/cache/apt/pkgcache.bin.QYVPAI to /var/cache/apt/pkgcache.bin - rename (13: Permission denied)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted`

**Comment by dblock247** [comment]
@therealkenc I ran the code and here are the resutls

sudo apt clean

```
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.F3Qoj4 - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.HF76cu - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin.qq01WR - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.KadxGE - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.ol8eiE - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin.zm6pSd - RemoveCaches (13: Permission denied)
anon@WORKSTATION:~$ sudo rm -fr /var/lib/apt/lists/partial/*
```

sudo rm -fr /var/lib/apt/lists/partial/* 
sudo apt update

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f86d2d80700 (most recent call first):
```

I have uploaded he apt.strace file [here](https://gist.github.com/dblock247/e8158971e697852f878da5407ef7201a)

**Comment by therealkenc** [comment]
Hmm. No surprise in the `strace` given the console messages:
```
unlink("/var/cache/apt/pkgcache.bin") = -1 EACCES (Permission denied)
```

Blow away the whole apt cache with `sudo rm -fr /var/cache/apt/*`. Curious if you get a `Permission Denied` on the `rm` even though `sudo`. If it succeeds try the `apt clean` and `apt update` again.

This is looking pretty hooped though. Someone on the team like Ben might need to jump in at this point and suggest the current preferred method to wipe out the whole installation conclusively and start over; given that a Store uninstall doesn't seem to get you there (grumble). Needless to say, an `apt update` right after install "works", or heads would explode. What is missing is the confluence of events got you in this state.

**Comment by dblock247** [comment]
@therealkenc apt-get update did not work right after install. I haven't really been able to do anything with it other then install wsl and then ubuntu (would rather use debian but i can't create a username and password when I install it). 

I tried your preview suggestion and got the following results:

```
anon@WORKSTATION:~$ sudo rm -rf /var/cache/apt/*
[sudo] password for dblock:
Sorry, try again.
[sudo] password for dblock:
rm: cannot remove '/var/cache/apt/archives/lock': Permission denied
rm: cannot remove '/var/cache/apt/archives/partial': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.F3Qoj4': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.HF76cu': Permission denied
rm: cannot remove '/var/cache/apt/pkgcache.bin.qq01WR': Permission denied
rm: cannot remove '/var/cache/apt/srcpkgcache.bin': Permission denied
rm: cannot remove '/var/cache/apt/srcpkgcache.bin.KadxGE': Permission denied
rm: cannot remove '/var/cache/apt/srcpkgcache.bin.ol8eiE': Permission denied
rm: cannot remove '/var/cache/apt/srcpkgcache.bin.zm6pSd': Permission denied
```

one thing I noticed is that although the username is anon when I use sudo it request a password for dblock. That username doesn't exists. It must be from one of my previous installs but still there. if I run 

`cut -d: -f1 /etc/passwd`

the username exists but I didn't create it on this install.

**Comment by dblock247** [comment]
@therealkenc I was having another issue with CLion and discovered the problem. I use Comodo Internet Security and it was silently blocking WSL from doing anything. I disabled it and everything started working. I just have to figure out how to allow WSL in Comodo. Sorry for the inconvenience and thanks for all of your help.

**Comment by therealkenc** [comment]
Alright we'll lay all the blame on Comodo and leave it at that I guess. You've got other strangeness happening here though that I can't reasonably attribute to "Internet Security" anything. Passwords are entirely isolated between WSL "distributions" so that remains unexplained. Anyway, your fails will show up in a search now, in the event someone hits something similar (due to Comodo or otherwise). It was worth the submission. No inconvenience.

**Comment by lx07** [comment]
Having the same issue on 3 different devices, Kaspersk Internet User here. Tried turning it off no difference. Even tried different networks same problem.

**Comment by lx07** [comment]
Having the same issue on 3 different devices, Kaspersk Internet Security 2018 User here. Tried turning KIS2018  on and off - no difference. Even tried different networks and ISPS and DNSSess same problem.

**Comment by scriptninja** [comment]
I know this is greatly delayed, but in case it's useful information to anyone else coming across a similar issue, I suspect the reason there is "strangeness happening" that one cannot "reasonably attribute to Internet Security" is because in addition to firewall and antivirus, Comodo Internet Security offers a feature it calls "auto-containment," which operates as a sort of sandbox with (I think) virtualized access to some resources, read-only access to some, and no access at all to some. What ends up happening is that commands run from a "contained" wsl can't modify certain files. For me, at least, explicitly excluding wsl from containment solved that part of the problem.
