### ISSUE TITLE
It is possible to running WSL in sandbox?

### ISSUE THREAD

**Issue by karatihh** [Microsoft/WSL#3189]
It is possible to running WSL in sandbox like sandboxie or shadow defender?
I've try running WSL in sandboxie but WSL foreclose.
I want to use benchmark tools (but based on linux) to know sandbox performance, so i want running that benchmark in sandbox.
Thanks before.

**Comment by therealkenc** [comment]
Apparently not.

**Comment by HsunGong** [comment]
Sounds bad.
