### ISSUE TITLE
rsync error with Windows 1803

### ISSUE THREAD

**Issue by Mornon** [microsoft/WSL#3192]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type ver at a Windows Command Prompt) Microsoft Windows [Version 10.0.16299.431]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

When I use rsync with a USB drive, I get errors:

rsync: chgrp "/mnt/f/Gamification/TechLand/TPS/Illuminotecnica/Immagini/03/A/Stanza.dwg" failed: Operation not permitted (1)
rsync: mkstemp "/mnt/f/Gamification/TechLand/TPS/Illuminotecnica/Immagini/03/A/.Stanza.dwg.vU7MSj" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

This started happening after upgrading from 1709 16299.431 to 1803 17134.48, and fixed itself after a rollback. This is the code, which worked in 1709:

    cd /mnt/d/Mauro/Documenti/Insegnamento/
    rsync -Rauv --del --chown Mauro --chmod=ugo=rwX \
      'Gamification' \
      /mnt/f/ \
      >/mnt/c/Users/Mauro/Desktop/lista.txt \
      2>/mnt/c/Users/Mauro/Desktop/errori.txt

It still works syncing from internal hard drive to internal hard drive, and from internal to external hard drive. I tried formatting the USB drive, reformatting it as NTFS, recreating permissions, formatting again as FAT32; I also tried to remove entirely the folders and run the script again, to no avail.

* What's wrong / what should be happening instead:

The folders should sync.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by DarthSpock** [comment]
I'm going to cite #2770 for this one.

**Comment by Mornon** [comment]
By the way, I also tried with

`--no-owner --no-group`

but got this error:

failed to set times on "/mnt/f/2017-2018": Operation not permitted (1)

(Not sure if the sync went through, will check as soon as possible.)

**Comment by DarthSpock** [comment]
Yes you should do that. Or you can just use wsl.conf to set the metadata option. In your case, you may also want to use fstab to mount your drives vice the auto drvfs. I would try either way and see if it helps. Also try running an elevated and non-elevated session to ensure Windows permissions aren't also a blocker. Oh and I should say that it will require you to upgrade to build 17134. The fix I'm describing doesn't exist in 16299.

**Comment by DarthSpock** [comment]
Also, there is possibly another related issue since I just realized you're on 16299: #1869

**Comment by Mornon** [comment]
Will try that as soon as I will reupgrade do 17134, thanks. Just not sure what do you mean by "to mount your drives vice the auto drvfs"?

**Comment by DarthSpock** [comment]
Yes but he mentioned he's new to Linux so just recommending he does some research so he can understand more about Linux.

**Comment by Mornon** [comment]
Now I'm on 1803 17134.1, and I still got the same errors, also using --no-owner and -o metadata.

rsync: mkstemp "/mnt/f/2017-2018/.5A.xlsx.hOeFu7" failed: Operation not permitted (1)

**Comment by Mornon** [comment]
I was able to solve using this option: https://github.com/Microsoft/WSL/issues/3187#issuecomment-388904048

**Comment by Mornon** [comment]
Any idea about how to add `uid=1000,gid=1000` as default using wsl.conf? I tried editing it and adding

`[automount]
options = "uid01000,gid=1000"`

but it doesn't work; using `mount -l` I can't see the external drive listed, so maybe it's that?

**Comment by KnuX** [comment]
Hi all,

Using the windows insider build 2004 (19033.1), I still have errors using rsync to an external USB drive used for backups.

> $ rsync -vrltxz --rsync-path="wsl rsync" --delete --no-p --progress /mnt/d/filename knux@10.42.56.21:/mnt/e/
> ...
> rsync: failed to set times on "/mnt/e/filename.0APmfD": Operation not permitted (1)

mount confirms that my device is mounted with uid=1000,gid=1000 as suggested in this issue:

> $ mount
> ...
> e: on /mnt/e type 9p (rw,relatime,dirsync,aname=drvfs;path=e:;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=3,wfd=3)

It occurs only with newer files uploaded by rsync. Each time I run rsync the same files will be uploaded this the timestamp isn't the same as the source file...

My E: drive is bitlocked, I manually mount it after having unlocked it.

**Comment by therealkenc** [comment]
> I was able to solve using this option: https://github.com/Microsoft/WSL/issues/3187#issuecomment-388904048

/dupe #3187 ➡️ #2770
