### ISSUE TITLE
mkfifo: cannot create fifo 'testfifo': Operation not permitted - dotnet 2.1.300 SDK CLI issues

### ISSUE THREAD

**Issue by jacobrillema** [Microsoft/WSL#3195]
```bash
ver
Microsoft Windows [Version 10.0.17134.48]

uname -a
Linux testmachine 4.4.0-17134-Microsoft # 48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

```bash
sudo apt-get install dotnet-sdk-2.1.300-preview1-008174
dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

If we run dotnet with sudo it writes to the local filesystem at /tmp and no issues.
```bash
sudo dotnet --version
2.1.300-rc1-008673
```

```bash
cd /mnt/c/Users/jrillema/AppData/Local/Temp

mkfifo testfifo
mkfifo: cannot create fifo 'testfifo': Operation not permitted

cd /tmp
mkfifo testfifo
ls -ltr testfifo
prw-rw-rw- 1 jrillema jrillema 0 May 15 00:33 testfifo
```

Problem creating a pipe on /mnt/c/users/jrillema/appdata/local/temp folder. 

Problem originally reported over [dotnet/core-setup](https://github.com/dotnet/core-setup/issues/4149)

```bash
4586 21457 unlink("/mnt/c/Users/jrillema/AppData/Local/Temp/clr-debug-pipe-21457-299289-in") = -1 ENOENT (No such file or directory)
4587 21457 mknod("/mnt/c/Users/jrillema/AppData/Local/Temp/clr-debug-pipe-21457-299289-in", S_IFIFO|0700) = -1 EPERM (Operation not permitted) 
4588 21457 futex(0x7f2340125680, FUTEX_WAKE_PRIVATE, 2147483647) = 0
4589 21457 write(2, "Failed to initialize CoreCLR, HR"..., 49) = 49
```

Workaround found [here](https://github.com/dotnet/coreclr/pull/15878)

export COMPlus_EnableDiagnostics=0

**Comment by jacobrillema** [comment]
@https://github.com/dotnet/core-setup/issues/4149

**Comment by danmosemsft** [comment]
@jacobrillema were you able to determine whether the symlink in your path is necessary to repro this?

**Comment by jacobrillema** [comment]
@danmosemsft symlink was not the issue. I tired flipping my local temp to a non-symlink and still received the same operation not permitted error. In my testing of mkfifo from the command prompt it received that error on any "non-native" WSL mount points. Anything native to WSL like /tmp or /home worked.

**Comment by danmosemsft** [comment]
Our code has not changed here to my knowledge so it seems this was a WSL regression.

**Comment by danmosemsft** [comment]
FYI @Anipik

**Comment by jacobrillema** [comment]
The only thing odd is in the same setup (WSL env and user id) the SDK 2.1.200 works fine. I did not strace that to see where it is trying to create the pipe. Let me try that to see if we can verify the location changed somehow.

**Comment by jacobrillema** [comment]
So 2.1.200 version writes to /tmp which does not have an issue and will work fine without sudo.

```bash
dotnet --version
2.1.200

3296 2203  unlink("/tmp/clr-debug-pipe-2203-4265323-in") = -1 ENOENT (No such file or directory)
3297 2203  mknod("/tmp/clr-debug-pipe-2203-4265323-in", S_IFIFO|0700) = 0
3298 2203  unlink("/tmp/clr-debug-pipe-2203-4265323-out") = -1 ENOENT (No such file or directory)
3299 2203  mknod("/tmp/clr-debug-pipe-2203-4265323-out", S_IFIFO|0700) = 0
```

**Comment by danmosemsft** [comment]
@mikem8361..did this change recently?

**Comment by jacobrillema** [comment]
Quick update. It appears .NET Core 2.1 is enforcing the use of $TMPDIR environment variable. In my environment this is what i had. 

```bash
dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80004005

echo $TMPDIR
/mnt/c/Users/jrillema/AppData/Local/Temp

export TMPDIR=/tmp
dotnet --version
2.1.300-rc1-008673
```
Changing it instead to use local /tmp works. Is the underlying issue then mkfifo not supported on any Window mount drives inside WSL?

**Comment by therealkenc** [comment]
> Is the underlying issue then mkfifo not supported on any Window mount drives inside WSL?

Appears not. On 17666:
```
$ mkdir -p ~/tmp/mnt
$ cd ~/tmp
$ sudo mount -t drvfs -o metadata,uid=1000,gid=1000 C: ./mnt
$ cd ./mnt/Users/ken/AppData/Local/Temp
$ mkfifo fefifofum
mkfifo: cannot create fifo 'fefifofum': Operation not permitted
```
That said, a DrvFS `$TMPDIR` _in WSL_ isn't especially how I'd roll.

**Comment by jacobrillema** [comment]
I was using it as a setup to help run a Beyond Compare diff session launched from inside WSL. But after the headaches here I will have to rethink a different approach. Thanks for the feedback.

**Comment by danmosemsft** [comment]
@therealkenc to make sure I understand, you're agreeing that mkfifo ought to work in this case in WSL? (Whether CoreCLR should fail to start if mkfifo fails is a separate issue)

**Comment by therealkenc** [comment]
> you're agreeing that mkfifo ought to work in this case in WSL

I don't really have standing to say. Sunil alluded [last May](https://github.com/Microsoft/WSL/issues/2137#issuecomment-304176416) it might be in the offing, but it doesn't seem to be supported ATM. Or I'm "doing it wrong". The metadata [blog post](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) doesn't mention (or even suggest) special files are supported so I'd call it by-design for the time being.

But to be clear, `%TMPDIR%` won't get inherited into WSL and `$TMPDIR` won't be set by Ubuntu 16.04's userspace by default. You'd have to make a conscious decision to set it in `.bashrc`, or include it in [`%WSLPATH%`](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/). If Linux .NET Core needs to assume a temp directory when `$TMPDIR` is not set, it should probably assume `/tmp`. [It wasn't clear in this thread where exactly `$TMPDIR` inside WSL is being set.]

> (Whether CoreCLR should fail to start if mkfifo fails is a separate issue)

Glad you said it first. Whether named pipes should be used in 2018 by anyone, ever, for anything, is definitely a separate issue. 😉

**Comment by jacobrillema** [comment]
@therealkenc @danmosemsft 

That metadata blog post did specify special files like pipes would be supported. So I went back through to see how I was mounting my /mnt/c drive and sure enough I did not opt in to the new metadata drvfs approach. I created a /etc/wsl.conf with the following:

```bash
[automount]
enabled = true
options = "metadata,uid=1000,gid=1000,umask=22,fmask=111"
mountFsTab = true
```
Note I have mountFsTab set so I can access my SD card. So after enabling this metadata and keeping my original TMPDIR set I was able to get pass the critical error from the .NET SDK. See my results below

```bash
dotnet --version
2.1.300-rc1-008673

mount -l | grep "C:"
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=111,metadata)

echo $TMPDIR
/mnt/c/Users/jrillema/AppData/Local/Temp

cd $TMPDIR
pwd
/mnt/c/Users/jrillema/AppData/Local/Temp

mkfifo testfifo
ls -tlr testfifo
prw-rw-rw- 1 jrillema jrillema 0 May 16 00:37 testfifo
```
So I was able to get this working with opting into the new drvfs metadata options. Here is the link and search for [special files](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) The whole reason I went down this path was to accomodate running a [Beyond Compare](https://www.sep.com/sep-blog/2017/06/07/20170607wsl-git-and-beyond-compare/) diff session from inside WSL. 

I appreciate everybody's help on this one. I will play around a bit more with testing this the next few days to make sure it is working. I would suspect we might be able to close this out here if it works. I am not sure how new WSL installations are handled with the new metadata by default but I am working with an older WSL installation.

**Comment by danmosemsft** [comment]
Great update thanks @jacobrillema. Feel free to close this as far as I am concerned.

**Comment by therealkenc** [comment]
> That metadata blog post did specify special files like pipes would be supported.

Okay so I can't skim blog posts like I used to. Close if everyone is satisfied. 

The unsettling thing is I just cut-and-pasted my [exact steps](https://github.com/Microsoft/WSL/issues/3195#issuecomment-389082502) from last night into my terminal just now and `mkfifo` works fine. I didn't imagine the "operation not permitted" because I pasted that in the opposite direction from the terminal into Github last night. Had it worked I probably wouldn't have projected fifos not being cited in the blog (which they clearly are). Collective shrug on why it failed last night.

**Comment by jacobrillema** [comment]
>Okay so I can't skim blog posts like I used to. Close if everyone is satisfied.

No worries and I am glad we figured this one out. Thanks again everybody for the help. I am closing this one out now. As I can confirm my original state is now working again with the .NET Core CLI/SDK and doing visual diffs with Beyond Compare from inside WSL.

At least this is documented if somehow else runs into this issue.
