### ISSUE TITLE
support drvfs metadataflag when rebooting

### ISSUE THREAD

**Issue by fenchu** [Microsoft/WSL#3197]
Hi
windows build:
4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64

my filesystem:
D: on /mnt/d type drvfs (rw,relatime,metadata)

After reboot we are back in old dark times:
D: on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000)

sudo umount /mnt/d
sudo mount -f drvfs D: /mnt/d -o metadata

Now it is fine:
D: on /mnt/d type drvfs (rw,relatime,metadata)

Without metadata umask is not working all files are 777, ssh refuses to
read *.priv certificates which have 777 permissons. Working with git is pain
since all files get 777 permissions etc......., testing an application that should have
its own user is hard, running services problematic.. etc

Thanks

**Comment by onomatopellan** [comment]
Do you know about wsl.conf?
https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/

**Comment by therealkenc** [comment]
Yep. But ref #3138 #3153 #352.
