### ISSUE TITLE
Extended Unicode filename translation fails in version 1803

### ISSUE THREAD

**Issue by raydavis** [Microsoft/WSL#3200]
**Windows build number**: Regression occurs after installing feature update version 1803.
All is well with version 1709 (and in 8 previous months of Windows 10 / WSL use).

**Background**: A fair number of the files I handle from the web include embedded non-standard Unicode characters as separators in filenames. Thanks to WSL, I switched back to Windows as my preferred working environment in summer 2017, and the default Ubuntu shell has been working well for me since then, including its filename encoding translation between Linux and Windows-style UTF-16.

**Issue**: After upgrading to this spring's feature version, that translation stopped working and so did all my WSL/Ubuntu file management routines, notably rsync scripts.

Here are the two characters which trigger the most errors in my local system. Use the default Windows Explorer font, Segoe UI, to view these characters as dots/bullets.

Character : 
Hex code: F025
Hex UTF-8 bytes : EF 80 A5 

Character :  
Hex code :  F027
Hex UTF-8 bytes : EF 80 A7 

BEFORE log
WSL default Ubuntu (release 16.04.3 LTS) bash shell with Windows 10 Pro version 1709:

```
test> ls -al
total 136
drwxrwxrwx 0 root root   512 May 15 05:53 .
drwxrwxrwx 0 root root   512 May 15 05:57 ..
-rwxrwxrwx 1 root root 14678 Jun  2  2015 filename_with_dot.jpgheight=142&width=200
-rwxrwxrwx 1 root root 50647 Nov 11  2016 Filename Without Dots.html
-rwxrwxrwx 1 root root 50647 Nov 11  2016 Filename With Unicode  Dots.html
test>
```

AFTER log
WSL default Ubuntu (release 16.04.3 LTS) bash shell after upgrading to feature update version 1803:

```
test> ls -al
ls: cannot access 'Filename With '\''Unicode '\'' Dots.html': No such file or directory
ls: cannot access 'filename_with_dot.jpg%height=142&width=200': No such file or directory
total 52
drwxrwxrwx 1 root root  4096 May 15 05:53 .
drwxrwxrwx 1 root root  4096 May 15 18:26 ..
-????????? ? ?    ?        ?            ? filename_with_dot.jpg%height=142&width=200
-rwxrwxrwx 1 root root 50647 Nov 11  2016 Filename Without Dots.html
-????????? ? ?    ?        ?            ? Filename With 'Unicode ' Dots.html
test>
```

**Comment by raydavis** [comment]
For the benefit of searchers who, like me, first encounter this regression while running `rsync`, the reported error will be "file has vanished" for each of the relevant filenames.

**Comment by benhillis** [comment]
@svengroot - might this be related to some of the filename escaping work?

**Comment by SvenGroot** [comment]
As @benhillis thought, it's a problem in our filename escaping code. We use the Unicode range 0xf000 to 0xf0ff to escape characters that are legal in Linux but not in NTFS. Unfortunately, it looks like our unescaping code, used by readdir, is a bit overzealous and unescapes every character in that range even if they don't correspond to an escaped character.

That means that readdir unescapes the file name, but the returned name won't get escaped when you use it, so it doesn't work.

I've got a fix in the works, and it'll be coming to an RS5 insider build as soon as possible. We'll also consider backporting the fix to RS4.

In the meantime, I'm afraid the only solution is to avoid characters in the range 0xf000 to 0xf0ff.

**Comment by SvenGroot** [comment]
This issue is fixed since build 17692. Let us know if you still have problems.

**Comment by jboucha** [comment]
I seem to be experiencing a similar issue with a different character on Windows 10 Education Version 21H1 (OS Build 19043.928) under Debian 10.9.

Character: �
Unicode: U+D835 | <Non Private Use High Surrogate>
UTF-8 Encoding: | 0xED 0xA0 0xB5

It appears my music library software appends this character to the end of filenames containing certain special characters when truncating them. I received the same "file has vanished" error from rsync as the original poster, as well as identical error messages from ls:
```
$ ls -l
ls: cannot access '35 ℑ 𝔉𝔞𝔩𝔩 ℑ𝔫𝔱𝔬 𝔖𝔩𝔢𝔢𝔭 𝔈�.mp3': No such file or directory
ls: cannot access '36 ℑ 𝔉𝔞𝔩𝔩 ℑ𝔫𝔱𝔬 𝔖𝔩𝔢𝔢𝔭 𝔈�.mp3': No such file or directory
total 0
-????????? ? ? ? ?            ? '35 ℑ 𝔉𝔞𝔩𝔩 ℑ𝔫𝔱𝔬 𝔖𝔩𝔢𝔢𝔭 𝔈�.mp3'
-????????? ? ? ? ?            ? '36 ℑ 𝔉𝔞𝔩𝔩 ℑ𝔫𝔱𝔬 𝔖𝔩𝔢𝔢𝔭 𝔈�.mp3'
$
```
