### ISSUE TITLE
start bash with error code : 0x8007041d

### ISSUE THREAD

**Issue by scmod** [Microsoft/WSL#3203]
Microsoft Windows [Version 10.0.16299.431]
win+r start bash,but it only shows 
error : 0x8007041d
press any key to continue...
I have tried lxrun /uninstall /full run with administrator, after confirm "press y to continue",
it only shows "error : 0x8007041d" again..
I have just installed gcc and g++ this morning,and I'm sorry that I can't find out more infomation

**Comment by guijianchou** [comment]
try ubuntu 18.04 https://t.co/D5XtUFDzIR

**Comment by scmod** [comment]
thanks a lot, let me see...
start downloading......sometimes show the code :0xC0020036, somtimes download fail, emmmmmmm...poor network

**Comment by scmod** [comment]
perhaps I have find out the reason,
I have changed my position setting yesterday,
locale -> manager -> change system locale setting of, ah, non-unicode program language?
from english to chinese back, then it's all right
![image](https://user-images.githubusercontent.com/9472690/40158669-5470feca-59d8-11e8-9869-cdce60d24dac.png)
