### ISSUE TITLE
Is ssh-agent working in WSL?

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3206]
To avoid that `scp` asks the password for each package to be transferred (see for example this discussion [1]), it seems that `ssh-agent` is needed.

I found [2] that one has to start it as

```
$ eval $(ssh-agent -s) > /dev/null
$ ssh-add
```

but `ssh-add` asks nothing and `scp` continues to ask the password, so the conclusion is that, maybe, `ssh-agent` in WSL is not working...

What is the status of 'ssh-agent` in WSL? Is it working? How?

Thanks.

---
[1] http://tug.org/pipermail/tex-live/2018-May/041732.html
[2] https://gist.github.com/copperlight/e9eaa40d6f3bb9e1e6e6b1dd8ba0a8d5

**Comment by morgan-greywolf** [comment]
It works for me. But I haven't used it in quite a while because I use Emacs
on Win32. I couldn't get Tramp working with OpenSSH, but it works fine with
pscp/plink. So I use pageant to load my keys and weasel-pageant in place of
ssh-agent.

**Comment by s-sajid-ali** [comment]
This was working fine but after the latest update, it isn't. I'm getting the following error when I run an alias that first does ```eval $(ssh-agent)``` followed by ```ssh-add ```: 
```
sajid@DESKTOP-NDBN82B:/mnt/c/Users/sajid/Documents/ssh-keys/xrmlite_account> xrmlite
Agent pid 476
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/mnt/c/Users/sajid/Documents/ssh-keys/xrmlite_account/xrmlite_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
sajid@xrmlite.phys.northwestern.edu's password:
```

I've tried using chmod to change the access but since WSL is running over the windows kernel, the solutions given for linux os don't work here. Alternatively if I disable inheritance for the private key file, WSL can no longer access the key. 


Is there any fix for this ?

**Comment by morgan-greywolf** [comment]
Ah. Try mounting /mnt/c with thebmetadata option.
