### ISSUE TITLE
How to start 'bash' for Ubuntu 16.04 and Ubuntu 18.04 respectively

### ISSUE THREAD

**Issue by anji993** [Microsoft/WSL#3208]
Microsoft Windows [Version 10.0.17134.48]

I install both Ubuntu 16.04 and Ubuntu 18.04 from the Microsoft Store.  They can start from icon in the menu. But type 'bash' in the Windows PowerShell can start the 16.04 version (first install one).

Is there another 'bash' point to 'bash' of '18.04' and i modified the setting in VS Code like this "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe" to start WSL in VS Code.

How to start bash for Ubuntu 16.04 and Ubuntu 18.04 respectively ans use Ubuntu 16.04 and Ubuntu 18.04 in the VS Code.

**Comment by benhillis** [comment]
Bash.exe launches /bin/bash in your default distribution. You can configure this via wslconfig.exe

**Comment by DarthSpock** [comment]
Alternatively, you could run wsl.exe instead of bash (which is the supported way) or call the executibles directly. So `ubuntu.exe` or `ubuntu1804.exe`.
