### ISSUE TITLE
can't install ubuntu 18.04

### ISSUE THREAD

**Issue by xtoolkit** [Microsoft/WSL#3209]
ver: Microsoft Windows [Version 10.0.17134.48]
hi
why i can't install ubuntu 18.04 from store?
no error
just loop refresh store page when click get app
plz help me, thank you

**Comment by onomatopellan** [comment]
It's a bug of April Update. You need to close your user session inside the Store App and login in again with the same user name.

**Comment by xtoolkit** [comment]
@onomatopellan
