### ISSUE TITLE
Unable to install Ubuntu (or other distributions) through Windows Store

### ISSUE THREAD

**Issue by evancohen** [Microsoft/WSL#3211]
* `Microsoft Windows [Version 10.0.17134.1]`

* What you're doing and what's happening: 
  * Ran `bash` in cmd and was prompted to install a distribution via https://aka.ms/wslstore
  * Followed link to install
  * Clicked 'Get' and page did a refresh but silently failed (download did not start, no error)

![wsl](https://user-images.githubusercontent.com/1198365/40204801-a46dcec0-59de-11e8-91bb-baf1cff41423.gif)

* What's wrong / what should be happening instead:
  * Download should have started, or error shown
  * I am able to download other apps from the Windows store

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
  * NA

I know this isn't a ton to go on, but I'm not sure what other information would be useful here, please advise.

**Comment by onomatopellan** [comment]
Duplicate of #3209

**Comment by evancohen** [comment]
Thanks @onomatopellan! Logging out of the Store and logging in again solved the issue.
