### ISSUE TITLE
Error: 0x800703fa Illegal operation attempted on a registry key that has been marked for deletion

### ISSUE THREAD

**Issue by xtoolkit** [Microsoft/WSL#3215]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

turn on laptop and open ubuntu and see error!!!

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800703fa
Error: 0x800703fa Illegal operation attempted on a registry key that has been marked for deletion.

Press any key to continue...
```
this problem fix by reboot and restart Lxss service! but why? why April update has some big bugs on windows and wsl!!!

**Comment by Biswa96** [comment]
Duplicate...

**Comment by xtoolkit** [comment]
@Biswa96 this error?
please link me. thank you

**Comment by Biswa96** [comment]
See this https://github.com/Microsoft/WSL/issues/2576

**Comment by ozen** [comment]
It is not a duplicate. It has the same error code but a different message. @kyranet solved this error by modifying registry. However there is no fix for #2576 so far.

**Comment by darkygeezard** [comment]
As mentioned in #2576 was solved by restarting `LxssManager` service in Windows Services. It's a dup.

**Comment by TheTerence** [comment]
My corrupted shell was on a non-admin account.  After reading these posts, I signed on as Administrator and started an Ubuntu shell.  First message referenced a file re-format, after which the shell instance funtioned normally.  
However, I still terminated Ubuntu from the Apps/Services, then signed back on to my non-Admin account and opened Ubuntu again.  All good.

**Comment by rechenberger** [comment]
I had the same issue after restarting Windows. Restarting Windows once again fixed it for me.

**Comment by ddproxy** [comment]
Confirmed restarting LxssManager resolved this issue for me. If finding the service is a pain, run the following in an command prompt as an administrator: `net stop "LxssManager" & sc start "LxssManager"`

**Comment by macxfadz** [comment]
@ddproxy  thanx bro,it worked.Thanks again for the solution.

**Comment by gitsoft** [comment]
same here - restarting LxssManager resolved this issue

**Comment by xtoolkit** [comment]
@gitsoft it's best solution?
each restart windows, restart Lxss service!
microsoft plz fix this problem with update.
i'm back to 1709

**Comment by xtoolkit** [comment]
@Biswa96 
this code is work, but when restart windows wsl error back!!

**Comment by mauriciolazo** [comment]
Restarting LxssManager worked.

**Comment by SagarBajpai** [comment]
Restarting the laptop helped me!

**Comment by anaganisk** [comment]
so am I supposed to restart the service every time I restart? Or is there a better solution?

**Comment by benhillis** [comment]
Disable fast boot.

**Comment by Biswa96** [comment]
Or make the Lxss Manager Service 'Automatic startup'. Run this command as administrator: 
```cmd
reg add "HKLM\SYSTEM\CurrentControlSet\Services\LxssManager" /T REG_DWORD /V "Start" /D 2 /F
```

**Comment by xtoolkit** [comment]
@Biswa96
your solution good in turn off and turn on windows.
but while restart windows, error back!

**Comment by anaganisk** [comment]
I just stopped the service, and changed the startup type to manual, the problem never came back after that.

**Comment by sureshgururajan** [comment]
as noted in one of the above replies, restarting LxssManager from Task Manager -> Services helped fix the issue

**Comment by etoricky** [comment]
Restarting LxssManager worked +1 on 2018 Aug

**Comment by anaganisk** [comment]
I noticed that it happens, when you exit the shell abruptly. Could not be the reason, but it happened to me multiple times.

**Comment by benhillis** [comment]
This thread is very long so I'll repeat myself:

Two ways to resolve this:
1. Disable fast boot
2. Manually stop /  start the lxssmanager service

sc stop lxssmanager
sc start lxssmanager

**Comment by nanonyme** [comment]
How about Microsoft devs just lock this thread until the fix is out?
