### ISSUE TITLE
Got "Socket type not supported!" Error, when start snort in WSL kali

### ISSUE THREAD

**Issue by Mithrilwoodrat** [Microsoft/WSL#3216]
* Windows build number : 10.0.16299.431
* WSL version: Kali Linux `Linux DESKTOP-SDPSKB6 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux`

* Trying to start snort in command line, Got `Socket type not supported!` error.
* Command Output
```
root:snort-2.9.11.1# snort -ilo
Running in packet dump mode

        --== Initializing Snort ==--
Initializing Output Plugins!
pcap DAQ configured to passive.
Acquiring network traffic from "lo".
ERROR: Can't start DAQ (-1) - socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported!
Fatal Error, Quitting..
```

* strace [snort.strace](https://gist.github.com/Mithrilwoodrat/07db9596d2d66ae9db691db85ae6a4b1)

according to `socket(AF_UNIX, SOCK_RAW, 0)      = -1 ESOCKTNOSUPPORT (Socket type not supported)` ,
it seemss this problem related to `AF_UNIX` support in WSL.

I found an Issue about this <https://github.com/Microsoft/WSL/issues/134>. And there is also a [blog](https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/) saying it's supported in Insider Build 17063.
Can I fixed this if I update my windows system to newer vesion?

**Comment by therealkenc** [comment]
`SOCK_RAW` is #717 #1383 and friends. #134 is `AF_UNIX` with `SOCK_DGRAM `and `SOCK_STREAM`.

**Comment by malrubiy** [comment]
MS PEOPLE PLZ SOLVE THE AF_UNIX PROPLAM ON WSL.

**Comment by moralrebuild** [comment]
hitting this issue with latest Windows 10 updates (2019 Feb), please fixed it instead of muting the complaining voice

**Comment by rwalk3r** [comment]
Still a problem on win 10 build 17763.316.. back to a VM.. nice try M$

**Comment by Qrbaker** [comment]
Yep, issue is still present and makes tcpdump et. al useless as of build 18363.535.

**Comment by moises-gonzalez** [comment]
Humm, I'm, seeing this Issue and I think would be better use Kali as Virtual environment in VMBOX.

**Comment by kashan91** [comment]
The issue still presents today.

**Comment by Djoraan** [comment]
Same issue with ubuntu
Win 10 v.1909 (Build 18363.778) WSL - Ubuntu 18.04.2 LTS:
netdiscover -r 192.168.0.0/24
Couldn't find default device: socket: Socket type not supported

**Comment by k1941996** [comment]
the same error arrives on Linux distros running on android: can you please look into the matter, or give me hint so i could solve it myself

**Comment by sundxu** [comment]
same issue

**Comment by robertegj** [comment]
same, go M$ go, someday you'll be a serious linux competitor!
/s

**Comment by koifans** [comment]
same issue here.
Windows version: 10.0.18363.836
WSL: Ubuntu 18.04.4 LTS

**Comment by nameisalreadytakenexception** [comment]
yeap, issue is still present, M$ let's fix it
Win 10 v.1909 (Build 19041.329) WSL - Ubuntu 20.04 LTS

**Comment by Eriobis** [comment]
Same issue here

**Comment by Ahnaf702** [comment]
#Help
Same issue with Kali-linux 
![image](https://user-images.githubusercontent.com/64384952/85922616-990bf100-b8a6-11ea-95ad-175c8a96ea61.png)
Please solve this issue as soon as possible

**Comment by yudengc** [comment]
Same issus here.
Windows10 version: 19041.329
WSL Ubuntu 20.04 LTS

**Comment by suchb** [comment]
got same issue，why closed？

**Comment by logi14** [comment]
Why this issue is closed still have same problem.

**Comment by vonmoraes** [comment]
Same here....

**Comment by therealkenc** [comment]
> Why this issue is closed still have same problem.

Because it is duplicative #717, #1930, others. But you know that because of the tag at the top of the page.

![image](https://user-images.githubusercontent.com/7049700/87964444-18887c80-ca6f-11ea-8886-f24d9254a3ed.png)

![image](https://user-images.githubusercontent.com/7049700/87965174-30accb80-ca70-11ea-838f-83a9eb39ee7b.png)

**Comment by CC-4477** [comment]
same issue occurs for me, while trying to use EtherApe, a packet sniffer:

`siyengar@DESKTOP-SDU1C6C:~/Downloads/etherape-0.9.18$ etherape

(etherape:12795): GVFS-RemoteVolumeMonitor-WARNING **: 01:14:23.023: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
EtherApe-INFO: 01:14:23.461: sctp protocol not supported
EtherApe-INFO: 01:14:23.462: ddp protocol not supported
EtherApe-INFO: 01:14:23.462: ddp protocol not supported
EtherApe-INFO: 01:14:23.462: ddp protocol not supported
EtherApe-INFO: 01:14:23.462: ddp protocol not supported
EtherApe-INFO: 01:14:23.474: get_interface result: 'socket: Socket type not supported'
EtherApe-INFO: 01:14:23.474: No suitables interfaces for capture have been found
(etherape:12795): Gtk-DEBUG: 01:14:23.528: Failed to create D-Bus proxy: Could not connect: No such file or directory
(etherape:12795): dconf-DEBUG: 01:14:23.550: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(etherape:12795): dconf-DEBUG: 01:14:23.550: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(etherape:12795): dconf-DEBUG: 01:14:23.551: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)`

**Comment by GoodspeedAmar** [comment]
Hello.. 
i know its old issue, but was anyone finally able to find a solution for this.
if anyone has solution for this please please let me know.

i have installed Bettercap on Kali  on WINDOWS 10 os..
Bettercap   version 2.28 is still giving issue...
--------------------------------------------------------------------
socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported
----------------------------------------------------------------------------------------

**Comment by diegofelipe01** [comment]
Hi,

Just got this issue on the latest version of Windows 10 with Kali Linux.

Will we have a fix for the issue? For what I can see it has been around for a long time and it is closed for some reason.

**Comment by GoodspeedAmar** [comment]
Any one please .. help  /  hint / Guide... hunting this issue  since 1 week now.. still no Clue..

**Comment by GoodspeedAmar** [comment]
Dear Microsoft/Wsl,
please give us some  solution for this issue.

it will Really Help a lot.

**Comment by ikbs** [comment]
this problem happened on kali and ubuntu which based on windows

**Comment by JoepTM** [comment]
> this problem happened on kali and ubuntu which based on windows

Ow :(

**Comment by FaresCharfi** [comment]
Same issue! 
WSL2
OS Build 18363.1316
Ubuntu 18.04 LTS
--
$ tcpdump -i eth0
tcpdump: socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported

**Comment by YowFung** [comment]
**same issue!**
> WSL Ubuntu 20.04 LTS (Linux xxxx 4.4.0-17763-Microsoft #1432-Microsoft Mon Aug 18 18:18:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux)
> Windows 10 1809 (17763.1697)
```txt
$ tcpdump -i eth1
tcpdump: socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported
```

**Comment by therealkenc** [comment]
For `ETHTOOL_GET_TS_INFO` you need WSL2.

**Comment by ttellerx** [comment]
STILL THERE:

Does Microsoft want WSL to be *really* like Linux or not ?
This breaks stuff I'm doing so its back to VMWare and a working UBUNTU VM.

root@Rubidium:/home/ttellerx# tcpdump
tcpdump: socket: Socket type not supported
root@Rubidium:/home/ttellerx#

**Comment by nobody48sheldor** [comment]
same issue even with wsl2

```
ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team

ERROR : 94, Socket type not supported
[/build/ettercap-TFupjX/ettercap-0.8.3/src/ec_capture.c:capture_getifs:114]

 socket: Socket type not supported
```

**Comment by m1mohamad** [comment]
"workaround ?> remove WSL > install Linux VM :D :D :D 👍 MS 👯 on Linux wanting to making Lindows .. tell me I'm crazy but I think they are planning something with all these issues .. some hybrid MS dominated Linux flavor of sorts ...."

**Comment by janellealag** [comment]
I have the same issue

**Comment by jeremybusk** [comment]
Still there on WSL 2 and 20.04

**Comment by andychen-1** [comment]
Same problem with WSL2 + Ubuntu 20.04.2

**Comment by goshante** [comment]
Same problem WSL2 + Ubuntu 18 on  Windows10 Pro 21H2
It seems like M$ don't give a sh*t, this bug is 4 years old, Microsoft what the hell?

**Comment by Jr24x** [comment]
Still an issue for me as well, why hasn't this problem been fixed? I cant find a solution anywhere.

**Comment by HarukaYang** [comment]
Still an issue today with WSL2 Ubuntu 18.

**Comment by szhydkov** [comment]
Same here: Windows 10, WSL2 Ubuntu 20.04

**Comment by foxhacker0000** [comment]
same

**Comment by mohamedelhoudaigui** [comment]
same thing jesus man
