### ISSUE TITLE
gui

### ISSUE THREAD

**Issue by Roguemaltron** [Microsoft/WSL#3217]
My issue is not really about commands and what not since my instillation went great but is it possible if you the microfsoft wsl devs could make a gui for the wsl to give users a very native feel of kali instead of just using the cli

**Comment by Biswa96** [comment]
See this article https://www.kali.org/news/kali-linux-in-the-windows-app-store/. You can find the GUI tutorial video at last in that article.

**Comment by therealkenc** [comment]
#637

**Comment by Roguemaltron** [comment]
exactly where on the page

**Comment by Roguemaltron** [comment]
it is ok i found out how
