### ISSUE TITLE
Please update GLX to version 1.3

### ISSUE THREAD

**Issue by r00ster91** [Microsoft/WSL#3218]
Please update GLX to version 1.3 or higher. When i'm using GLFW3 then i'm getting this error:
```Crystal
WARNING: [GLFW3 Error] Code: 65542 Decription: GLX: GLX version 1.3 is required
WARNING: GLFW Failed to initialize Window
Invalid memory access (signal 11) at address 0x0
[0x4499b6] *CallStack::print_backtrace:Int32 +118
[0x43e73b] __crystal_sigfault_handler +75
[0x7febcd931390] ???
[0x0] ???
```
My `glxinfo` output is https://hastebin.com/ucizegicot.css.
I'm using Xming to translate the picture from Bash to the Windows Windowing System.
Or can I maybe update GLX myself somehow?
* My Windows build number:  Microsoft Windows [Version 10.0.17133.1]

**Comment by therealkenc** [comment]
> `client glx vendor string: Mesa Project and SGI`
> `GLX version: 1.2`
> `OpenGL renderer string: llvmpipe (LLVM 6.0, 128 bits)`

That would be an ask for the mesa/llvmpipe peeps.
