### ISSUE TITLE
Ubuntu WSL via Microsoft Store appears to have trashed Windows boot

### ISSUE THREAD

**Issue by mostlytigerproof** [Microsoft/WSL#3220]
So I'm having a rather bad day:
1. Had LXSS installed since the beta in Windows 10 Anniversary Edition. (Ubuntu Trusty). It was working fine.
1. Needed a newer distro, went to the Microsoft Store to install Ubuntu Xenial. I didn't wipe my old LXSS stuff with lxrun. Wasn't logged into a MS Account.
1. Installed it and ran the new command line shortcut and it displayed "Please wait, installing" or something to that effect. Hung there for hours, no CPU, network or disk activity. Closed the window to try a reboot.
1.  Windows has been failing to boot since. It hangs on a black screen after the logo comes up, but before the logon prompt. There's a busy mouse cursor I can still move around. It's using both displays so the video driver has loaded. Unresponsive to keyboard input.
1. I've tried all the options on the recovery disk except for reinstalling Windows. The only System Restore point I have fails to restore the file:
E:\Users\craig\AppData\Local\lxss\rootfs\usr\lib\perl\5.18.2\sys\cdefs.ph
This restore point is from before the new Ubuntu.
1. chkdisk reports no errors on the drive. MBR is an ordinary windows one, and I ran the startup repair in any case. Hardware hasn't exhibited any other symptoms, has been well behaved running the recovery DVD. Haven't tested the memory yet.
1. This cdefs.ph doesn't already exist in the FS. The disk has plenty of space. 

My next step is to reinstall the OS, but I don't imagine that'll leave you with much to diagnose. I'd be grateful for any troubleshooting tips here (particularly how to get to the event log from a recovery DVD command prompt), but I'm gonna need to press the machine back into service before terribly long so I'd appreciate a prompt response.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

April 2018 Update as of 3 days ago. Ver reports 10.0.10586, but that'll just be the recovery DVD.

**Comment by DarthSpock** [comment]
You'll have to either restore prior to installing Ubuntu from the Store (recommended) or reinstall. You're unable to install both the Store version and the depreciated lxrun version. You must fully uninstall with `lxrun /uninstall /full`, reboot, and then install from the Store. I also recommend restarting the LXSS manager service before uninstall and after rebooting due to other issues in build 17134.

**Comment by mostlytigerproof** [comment]
Looks like WSL's involvement was only coincidence after all. Traipsed through the logs for ages but didn't learn anything. I finally got it to boot by yanking the ethernet cable. Dying NIC perhaps? Still really puzzled by this set of symptoms.

Thanks for the tip DarthSpock, I'll bear that in mind once I've got this stuff solved.
