### ISSUE TITLE
Overflow in monotonic clock.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/WSL#3221]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.17134.48

* What you're doing and what's happening:

While at PyCon 2018 I was working on [CPython](https://github.com/python/cpython) in WSL.  As I worked on it during talks, this involved:

1. putting my laptop to sleep (closing it)
2. going to the next talk
3. waking my laptop (opening it)
4. hacking on source
5. building ("make -j8")
6. running tests
7. go back to step 1

* What's wrong / what should be happening instead:

After doing this a dozen (or two) times, my builds started failing with an error about overflow in the monotonic clock.  I dug down into the CPython code that makes calls into the system libraries (and consequently syscalls).  Indeed, the clock was overflowing.  Once the failure started it failed the same way every time.  After rebooting everything started working again.  (I may have only restarted WSL, but I'm pretty sure I rebooted, so restarting WSL *might* have fixed it...)  I'm pretty sure I also did not try putting the laptop to sleep and then waking it up again, which I suppose could have gotten the clock back to a valid state.

My initial impression is that there is some race between the power management system and WSL.  It might also be some issue just with power management and that WSL is simply exposing it.  Presumably the way the clock is initialized upon waking has a small chance of causing the issue, which I hit after many times waking (with WSL active).

Unfortunately I do not have any other info than that.  Thanks for taking a look.

**Comment by benhillis** [comment]
I'm thinking this might be related to #3252.  When you get in this state does `ps aux` segfault?

**Comment by benhillis** [comment]
Virtually certain this is #3252.

**Comment by ericsnowcurrently** [comment]
As to #3252, I see that pretty frequently but not all the time.  I have rebooted quite a few times since May and the issue with `ps aux` continues to happen periodically (but my CPython builds are working fine).

FYI, I haven't see *this* issue (#3221) since that one time.  I've been building CPython relatively frequently in the meantime, but then again I haven't been putting my laptop to sleep like I was at PyCon.

Regardless, are you suggesting that my original issue is due to a highly intermittent bug that surfaces more frequently with `ps` and does not relate to power management?  I'm not refuting you, only clarifying. :)

**Comment by benhillis** [comment]
I think the only relation with power management is that when your machine is asleep, the counter we use will continue to increment (when you resume from sleep a bias is added) making it much easier for our boot time calculation to overflow.  I should clarify the time needed for this overflow is about 3 weeks, so not an unreasonable amount of time for a laptop that rarely reboots or shuts down but goes into sleep states.

If you have a machine that is currently experiencing this issue, could you run this command from cmd.exe?
`systeminfo | find /i "Boot Time"`

**Comment by ericsnowcurrently** [comment]
Got it.   Thanks for the explanation.  My laptop is not currently having the issue with `ps`, but I'll run that command the next time it happens.  Currently, from cmd.exe, it shows the following:

    System Boot Time:          2018-07-13, 09:00:12

**Comment by ericsnowcurrently** [comment]
FWIW, I do occasionally go stretches of several weeks between reboots.

**Comment by benhillis** [comment]
@ericsnowcurrently - Cool, let me know if you hit this again (and share the output of the command).  Going to go ahead and close this as a duplicate but feel free to reopen if you hit this again.

**Comment by ericsnowcurrently** [comment]
FYI, I've run into the problem again, but this time my laptop was running continuously (no sleep).  Here's the output from `systeminfo`:

```
System Boot Time:          2018-09-15, 17:38:59
```

FWIW, here's additional relevant info:

```
$ uptime
15:08:22 up -24855 days, -3:-14,  0 users,  load average: 0.52, 0.58, 0.59
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8304    88 ?        Ss   Oct08   0:00 /init ro
root        37  0.0  0.0  18788   456 ?        Ss   Oct08   0:00 /usr/sbin/sshd
# ...some output omitted...
esnow      105  0.0  0.0  15308  2112 pts/2    Ss   Oct09   0:00 -bash
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
root      1833  0.0  0.0   8304    68 tty1     Ssps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

Note that I'm running sshd in the background.  Currently I cannot connect using SSH (e.g. putty) though I can normally.  I'd be surprised if that wasn't correlated to the issue with the uptime/clock.

**Comment by ericsnowcurrently** [comment]
Yeah, 17134.  I see from #3434 that a fix is in after that.  FYI, I'm running an Insider Preview build, but have it set to "Just fixes, apps, and drivers".

**Comment by benhillis** [comment]
@ericsnowcurrently - With that "ring" of Insider Preview you're basically just testing Windows Update packages.  The fix for this issue will be in the next release of Windows, due next month.

**Comment by ericsnowcurrently** [comment]
cool, thanks
