### ISSUE TITLE
Ubuntu causes Bluescreens, and can't be removed for a clean re-install

### ISSUE THREAD

**Issue by ThePMO** [Microsoft/WSL#3223]
I'm using Ubuntu as a development environment for my C++ development.
Today, pretty much out of the blue, I started to get a bluescreen when I tried to compile my software (with gcc) every time with the error message "BAD POOL HEADER".
I tried it a few times until strangely enough the source file i was trying to compile seemed empty, although after inspecting it closer was filled with NUL.

Then I tried to update my ubuntu install using apt-get update -> also bluescreen

OK, so something seems to have broken my ubuntu installation, (although other, less critical programs that only communicate with a webserver and write stuff into a log file still worked), I guess I reinstall it freshly.

I uninstalled it through "Apps and Features" and then reinstalled it from the store.
Upon first start, where it sets up the system -> same Bluescreen again.

Now I can't even uninstall ubuntu anymore:
lxrun /uninstall doesn't work -> throws error 0x880070002
Uninstolling via  "Apps and Features" works maybe? it get's removed from the list but reappears after a reboot. 

I tried deactivating the "Windows Subsystem for Linux" and reactivating it, but it doesn't help with the problem.

My Windows Build is: 10.0.17134.48

**Comment by ThePMO** [comment]
False alarm.
Bluescreens on install as well as on other bash calls like apt-get are caused by Avira Antivir realtime scanner. Turning off the antivirus software solves this problem.

Still this should be looked into how and why this is happening, since it did work just a few days ago, apparently Avira changed something in a recent update!

**Comment by DarthSpock** [comment]
@ThePMO That being the case, Windows still shouldn't BSOD. I recommend sending a mini-dump to secure@microsoft.com so they can ensure BSOD doesn't occur as a result of Avira not playing nice.

**Comment by benhillis** [comment]
@DarthSpock - Avira's kernel mode driver is likely responsible for bugchecking the machine.  There's nothing Windows can do to prevent buggy drivers from causing bugchecks.

**Comment by DarthSpock** [comment]
I will redact my comment then
