### ISSUE TITLE
perf and kernel and package absent

### ISSUE THREAD

**Issue by mprevot** [Microsoft/WSL#3225]
I'm trying to make perf work in WSL ubuntu. It is said to be under linux-tools-4.4.0-17134-Microsoft but this doesn't exist. So I installed the linux-tools-generic-4.4.0. Then trying to run perf, I got:

> WARNING: perf not found for kernel 4.4.0-17134
> 
>   You may need to install the following packages for this specific kernel:
>     linux-tools-4.4.0-17134-Microsoft
>     linux-cloud-tools-4.4.0-17134-Microsoft
> 
>   You may also want to install one of the following packages to keep up to date:
>     linux-tools-Microsoft
>     linux-cloud-tools-Microsoft

Anyway, is there a way to run perf on WSL, the purpose is to get cpu cycles for a running program for benchmarking purposes ?

Where are those *Microsoft packages ?

regards

**Comment by Biswa96** [comment]
In WSL, the LxCore.sys driver emulates (like of) the Linux kernel. It also change the kernel details (i.e. struct utsname). Hence WSL shows that kernel version in `WARNING: perf not found for kernel 4.4.0-171314`.

**Comment by therealkenc** [comment]
#329 which was sent to UserVoice purgatory.

**Comment by optomux** [comment]
What's the status on this?

**Comment by mramsterdam85** [comment]
I got the same issue! What is the status?

**Comment by therealkenc** [comment]
The status of this issues is that it is closed as a duplicate of #329. A slightly more constructive status is `CONFIG_HAVE_PERF_EVENTS` is available in [WSL2](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/).

![image](https://user-images.githubusercontent.com/7049700/65281284-18ce8900-dae7-11e9-93ee-a812f98c02ee.png)

**Comment by BeverlyXu** [comment]
Would love to see this feature. And please correct the error message. It's misleading. 

> root@Beverly-Dev2:~# perf
WARNING: perf not found for kernel 4.4.0-18362

 >You may need to install the following packages for this specific kernel:
    linux-tools-4.4.0-18362-Microsoft
    linux-cloud-tools-4.4.0-18362-Microsoft

 > You may also want to install one of the following packages to keep up to date:
    linux-tools-Microsoft-lts-<series>
    linux-cloud-tools-Microsoft-lts-<series>

**Comment by mprevot** [comment]
I believe that with the WSLv2, which includes an actual linux kernel, it will work. Which makes this ticket candidate for closing.

**Comment by therealkenc** [comment]
This ticket isn't a 'candidate' for closing. It was closed as a dupe in May 2018.
