### ISSUE TITLE
How to run a command with grep, single quotes and double quotes with 'bash -ic'?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/WSL#3226]
Take the following Linux command as an example: `lsof | grep '$4=="cwd"'`. I need to execute this with `bash -ic`.

I tried `bash -ic "lsof | grep '$4=="cwd"'"` but I can't seem to properly escape the double quotes around `cwd` while having the command output the expected result.

How do I properly escape such a command?

**Comment by putty182** [comment]
GNU grep thinks you're wanting to match the characters `4=="cwd"` after the end of a line, which is an impossible scenario.

You're probably thinking of `awk`'

    lsof | awk '$4=="cwd"'

Using `bash -i -c` with `$` and `"` characters escaped

    bash -ic "lsof | awk '\$4==\"cwd\"'"

Have a look at [3.1.2 Quoting](https://www.gnu.org/software/bash/manual/html_node/Quoting.html) in the Bash Reference Manual for more info on how single quotes, double quotes and escaping work ~~against each other~~ together.

**Comment by rfgamaral** [comment]
@putty182 Yes, I meant `awk`, bad copy/paste, sorry.

However, that is not quite working as I expected because I'm actually invoking that command through [`exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) in a Node.js/Electron app. Sorry, forgot to mention that detail.

Here's what I have:

```js
exec(`bash -ic "lsof | awk '\$4==\"cwd\"'"`, (err, stdout) => {
  console.error('ERROR:', err);
  console.info('OUTPUT', stdout);
});
```

And this is what I get:

![image](https://user-images.githubusercontent.com/96476/40482810-e1c677d0-5f4d-11e8-95d9-d02af5396e94.png)

**Comment by therealkenc** [comment]
Right; not even a self contained nodejs test case given. Grumble. Against my better judgement at this point, you want:
```
const { exec } = require('child_process');

const cmd = 'lsof | awk \\$\\4==\\\"cwd\\\"';
exec(cmd, (err, stdout) => {
  console.error('ERROR:', err);
  console.info('OUTPUT', stdout);
});
```
