### ISSUE TITLE
sudo mount -t drvfs -o inode32 E: /mnt/e failed.

### ISSUE THREAD

**Issue by lygstate** [microsoft/WSL#3228]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [版本 10.0.17134.48]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I was trying to using a very old gcc that does not support for inode32 file system.
So I am trying to mount a filesystem that are inode32 but  failed.

**Comment by 0xbadfca11** [comment]
Workaround is use FAT instead of NTFS.
Pseudo file id of FAT never higher than 32-bit.

**Comment by therealkenc** [comment]
Yeah. But if it works on Real Linux™ on ntfs-3g and Samba this seems legit enough. Does it? I can test myself because, you know, no repro and the OP deleted the template.

**Comment by lygstate** [comment]
what about exfat， cause I need symbolic links

**Comment by lygstate** [comment]
exFat works, but another problem appear, exFAT doesn't support symblic link & hard link and other advanced functionals.
