### ISSUE TITLE
Processes wouldn't be killed after exiting terminal

### ISSUE THREAD

**Issue by emads3** [Microsoft/WSL#3229]
After updating to [10.0.17134.48] when I exit the terminal (all opened terminals) I still see the WSL processes run in the task manager like apache2 or mySQL (also I can still connect). And when I open the terminal again and check the `top` output out, I see the processes from last time are still up and running.
Before upgrading windows to that build, exiting the terminal was like a reboot for WSL. now I'm no longer able to reset it or even reboot it
Before updating windows to that build (which is sucks BTW) I was able to terminate all the WSL background processes just by terminating all opened sessions.

**Comment by onomatopellan** [comment]
That's by-design.

https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl/

Daemons will run until you close your Windows session unless you stop them manually. If you have to terminate them you can open Task Manager and kill the remaining `init` process after closing every WSL terminal.

**Comment by therealkenc** [comment]
Yep. But ref #200 and #2533 ([message](https://github.com/Microsoft/WSL/issues/2533#issuecomment-334501376)). I'd point you at the [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-backgroun?email_login_token=2c13a6339b97e8dd3243b3c2a687c5b7&tracking_code=27bad2863787ec423321e259ae75324e) but that's totally "IN PREVIEW" and presumably soon to be marked "COMPLETED". Or something. Grumble.
