### ISSUE TITLE
Unmet udev dependencies following do-release-upgrade

### ISSUE THREAD

**Issue by pkeir** [Microsoft/WSL#3234]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.16299.19]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
`sudo do-release-upgrade`

* What's wrong / what should be happening instead:
The upgrade to Ubuntu 18.04 (from 16.04 LTS) may not have completed; there were errors, which I unfortunately failed to note down. `lsb_release -a` reports Ubuntu 16.04.4 LTS. If I now try `sudo apt-get upgrade` (following `sudo apt-get update`) I get the following:

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 udev : Depends: libudev1 (= 229-4ubuntu21.2) but 234-2ubuntu12.3 is installed
E: Unmet dependencies. Try using -f.
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
The output of `sudo strace -o apt-get.strace sudo apt-get update` is [here](https://gist.github.com/pkeir/d62521660bf07a81f546599fa41e091d).

**Comment by DarthSpock** [comment]
You'll either need to download Ubuntu 18.04 directly from the Store or upgrade Windows to build 17134 in order to successfully upgrade with no errors.

**Comment by therealkenc** [comment]
#2960
