### ISSUE TITLE
No kernel headers in WSL

### ISSUE THREAD

**Issue by mprevot** [Microsoft/WSL#3235]
I was installing Intel parallel studio for Linux, and I couldn't have full installation because `linux-headers-4.4.0-17134-Microsoft` are missing, and there no such headers to my knowledge.
However it would be very useful for linux development (HPC, AI).

From Intel:

> VTune installs a kernel driver to collect events from the hardware. This driver requires kernel headers from the underlying OS. In your case, it's actually a Windows OS - so this kernel driver aspect will not work. You can still use the user-mode collections, like Basic Hotspots and Locks & Waits. During the installation you should have the option to customize the features and you can deselect the sampling driver.
> 
> If you want to use the kernel driver, you will need to install on a pure OS (Windows and Linux both work), or in a VM that supports virtualization of these events.

**Comment by Biswa96** [comment]
Seems to be same as your previous issue.

**Comment by therealkenc** [comment]
No repro and you deleted the template (natch).

> linux-headers-4.4.0-17134-Microsoft are missing

No the headers are there; the apt install scripts just makes assumptions about the `uname` output format. What is missing is a Linux kernel. Same as #2363.

**Comment by mprevot** [comment]
Microsoft Windows [Version 10.0.17134.48]

Linux rouge 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04)

Repro: install [Intel parallel studio XE](https://software.intel.com/en-us/parallel-studio-xe/choose-download) for linux (install.sh)

If I understand well, what is missing is more a Windows driver that will expose those functionalities to WSL, rather than an actual linux kernel.

[Long-term goal idea: DRM support #882 ](https://github.com/Microsoft/WSL/issues/882)
[lxss -- Fun with the Windows Subsystem for Linux (WSL/LXSS)](https://github.com/ionescu007/lxss)

**Comment by therealkenc** [comment]
A link is not a repro; and doing a CLI repro in this instance (starting with `apt` or `wget`) is problematic due to licensing. DRM is unrelated. You can't implement `/dev/sep*` with lxss. Closer to #1893.

**Comment by mprevot** [comment]
A link is indeed not a repro but allows you to do the repro: you can install with a trial version. Even though you can have a license for free since you're developing open source software. Anyway, all it says is that it needs kernel headers to build the driver to access to CPU counters.
Then, when I install linux-headers-generic, it won't work, that's it.

Thanks for the details.

**Comment by et304383** [comment]
Hold on, why is this issue closed?  We need linux-headers packages...

Why is the kernel on WSL Ubuntu 18.04 so old?

**Comment by therealkenc** [comment]
> Why is the kernel on WSL Ubuntu 18.04 so old?

It isn't old. There is no Linux kernel. This issues was closed because it is dupe #2363. Which is also closed for the aforementioned [reason](https://github.com/Microsoft/WSL/issues/2363#issuecomment-348745625).

**Comment by AnosKh** [comment]
For me worked fine after I did as below: sudo apt-get update sudo apt-get upgrade sudo apt-get install linux-generic sudo apt-get install linux-headers-$(uname -r)
Credit: H De Almeida (https://stackoverflow.com/users/4521952/h-de-almeida) 
Original Page: https://stackoverflow.com/questions/56586840/apt-get-install-linux-headers-generic-installed-in-directory-different-than

**Comment by crgarcia12** [comment]
Since WSL2 has a real kernel, can we get the headers?

**Comment by benhillis** [comment]
They are available on the WSL2-Linux-Kernel GitHub.

**Comment by tajetaje** [comment]
> They are available on the WSL2-Linux-Kernel GitHub.

a bit of necro here, but could you elaborate on that?

**Comment by therealkenc** [comment]
The WSL2 kernel source including headers is [here](https://github.com/microsoft/WSL2-Linux-Kernel). For most purposes they are the same headers as those on [kernel.org](https://www.kernel.org/). Tangentially, #5526 could use some more upvotes.
