### ISSUE TITLE
Error: 0x80070002

### ISSUE THREAD

**Issue by hron84** [microsoft/WSL#3236]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:  I trying install WSL from Control Panel / Programs and services, only enabling Linux Windows Subsystem.

* What's wrong / what should be happening instead: after clicking Next, the wizard immediately displays unsuccessful installation with this error code (0x80070002) and nothing else. Commands like `lxrun`, `wsl` not available. Registry keys not present, this machine never seen WSL before.

**Comment by av-tobii** [comment]
I have the exact same issue, same circumstances, same windows build. I have tried enabling from windows powershell as well (as admin) using the command

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

This is the error I get there:

Enable-WindowsOptionalFeature : The system cannot find the file specified.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by GJKrupa** [comment]
I'm getting exactly the same and have tried both methods as per the previous messages.  Windows 10 Pro 1803 (17134.81).  It's pretty much a clean installation.

**Comment by hron84** [comment]
Anyone watching these issues from the contributors? Okay, it's just a month old ticket but I'd like to see something that ensures me developers/contributors get knowledbe about it.

**Comment by trashcluster** [comment]
Up, same issue as above, totally clean install (Installed win10 before any major updates from a usb installer ISO (from 2015) and immediately upgraded to the latest win10 update 17134)

**Comment by thedonquixotic** [comment]
I'm also having the same issue. Is there going to be a solution for this or not? Microsoft devs? I need WSL to do my job.

**Comment by benhillis** [comment]
Sorry for the day in response.  To clarify, enabling the optional component is the step that's failing?  Are there any interesting events in the Windows event log around when this happens?

**Comment by trashcluster** [comment]
Just got an update and now i can install just fine, try to reboot to see if it works for you.

**Comment by hron84** [comment]
@benhillis Yeah, enabling the component fails, both in CLI and the Control Panel -> Programs & Features -> Windows components GUI fails. Settings would fail too but I did not tested.

**Comment by benhillis** [comment]
Thanks for providing the logs, I've forwarded this thread along to the team that owns Windows componentization, hopefully they will have a solution.

**Comment by benhillis** [comment]
@av-tobii - could you attach the full CBS.log?

**Comment by mehmetalianil** [comment]
I happened to bump into this yesterday. Did you check that your Windows copy is undergoing an update cycle, waiting to be restarted?

**Comment by hron84** [comment]
@mehmetalianil It's independent from those states. I tried it few different times, after a fresh restart, after a restart of a 'big' update (which ensures Windows should not be undergoing an update cycle), nothing changed that.

**Comment by ZoeOsorio** [comment]
@benhillis I'm seeing this error too - Windows build number 17134.191

**Comment by therealkenc** [comment]
This issue went stale on without a local repro. If the problem persists on Windows 20H2 aka 19042, please open a new issue following the issue template and include a backlink to the [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)  feedback item.
