### ISSUE TITLE
I cannot start my Kali Linux. When i launch my Kali Linux, it shows an error code: 0x80070040

### ISSUE THREAD

**Issue by NormanLCY** [microsoft/WSL#3238]
Here's the file that microsoft asked for, all the information that they needed is inside, pls email: looicyun@gmail.com after you guys know what's the problem...... Thanks for your help.

This file down here is all the information that you guys asked for and all the .etl file is inside:
[Starting bash gives an error code 0x80070040.zip](https://github.com/Microsoft/WSL/files/2033573/Starting.bash.gives.an.error.code.0x80070040.zip)

**Comment by sirredbeard** [comment]
How about just a screenshot of the error?

**Comment by Biswa96** [comment]
Log files are enough.

**Comment by sirredbeard** [comment]
@Biswa96 

Maybe for you to help the guy.

But I don't see you helping the guy.

I see you unconstructively calling me out for how I am trying to help.

But since you only need log files, I am sure you can help @NormanLCY from here.

Thanks.

**Comment by Biswa96** [comment]
@NormanLCY What's your Windows version?

**Comment by benhillis** [comment]
I haven't seen 0x80070040 errors for some time, if you still see this issue in 19042 please open a new issue.
