### ISSUE TITLE
wsl crashes windows!

### ISSUE THREAD

**Issue by Klystron** [Microsoft/WSL#3240]
Microsoft Windows [Version 10.0.17134.81]
What I did:  typed 'windows key wsl enter' OR clicked bash.exe in c:\Windows\System32
Result: windows crashes, blue screen, microsoft says it's not their problem, baloney.  Also cmd dir can't see bash.exe

c:\Windows\System32>dir bash.exe
 Volume in drive C has no label.
 Volume Serial Number is 025D-C2D0

 Directory of c:\Windows\System32

File Not Found

Blue screen says 'STOP CODE: BAD_POOL_HEADER

I turned off wsl check box in control panel - windows rebooted. Re-checked it, rebooted. Installed Ubuntu. Same problem.
 I can't run any linux programs 'cause it crashes before that.

**Comment by Klystron** [comment]
Problem fixed by disabling Avira antivirus 'real time protection'

**Comment by benhillis** [comment]
I suspect the issue is with their driver. I would suggest following with them to see if they are aware.

**Comment by sunilmut** [comment]
Problem is outside of WSL.

**Comment by robotbroken** [comment]
I contacted Avira about this and the suggested fix is to add the WSL files to the exception list in the real-time scanner options.

> Hello,
> 
> thank you for your inquiry.
> 
> We would recommand to set the files of the WSL to the exceptions in the Antivirus-configuration.
> 
> File exceptions can be defined for both the “System Scanner” and the “Real-Time Protection”. A special feature of the “Real-Time Protection” is that processes may be excluded from the scan as well.
>
> Exclude files or processes 
> 
> 1. Click the Avira icon in the taskbar to open Avira.
> 2. Search for Antivirus and click Open.
> 3. Click the settings symbol  in the lower left corner.
> 4. Click PC Protection → Exceptions.
> 
> Since the exceptions for the “System Scanner” and “Real-Time Protection” must be configured separately, please select the corresponding module in the left panel. Search and add files or processes you want to be skipped by the Real-Time Protection or System Scanner and Real-Time Protection.
> ![image](https://user-images.githubusercontent.com/16373241/41931318-52670618-79b0-11e8-9c5f-7c8c0f8bacf6.png)
> 
> 
> 5. Click OK to save the configuration.

I haven't had the time to research exactly what folders and/or processes need to be added to the exception list yet. So I haven't tested their fix yet. I will try to remember to update this post when I figure it out.
