### ISSUE TITLE
using the gui described in the page with xfec4

### ISSUE THREAD

**Issue by Roguemaltron** [Microsoft/WSL#3242]
um recently i opened an issue asking how to get the kali gui in wsl and i was answered in an email and i was told to return to the page and watch a video so everything run smoothly but when it cam to the point of opening a remote connection on the server listening to port 3990 it said device not existing or something along those lines then i realized that i missed that step that allows the remote server to listen to port 3990 , so will i need to uninstall and reinstall kali's wsl and repeat the process or there is a way to move back to that step using the terminal

**Comment by therealkenc** [comment]
You will probably get better service over there by not using pronouns ("that step").
