### ISSUE TITLE
How can i configure to debug python installed on WSL with VS Code

### ISSUE THREAD

**Issue by anji993** [Microsoft/WSL#3248]
Microsoft Windows [Version 10.0.17134.48]
Ubuntu 18.04

I am using VS Code as the editor for python running on Linux. I know how to use bash in the VS Code.

Is here some way like to configure a PATH so that i could debug python and use extensions with the python installed on WSL?

**Comment by sirredbeard** [comment]
This is very do-able.

This is not my workflow so I can't give you a how-to but I do know you can even use git on the WSL side.

I recommend checking out some guides for setting up programming environments here:

https://github.com/sirredbeard/Awesome-WSL#using-wsl

**Comment by therealkenc** [comment]
Yeah this would be better followed up in the link cited.
