### ISSUE TITLE
Ubuntu 18.04 not listed on WSL landing page on Microsoft Store

### ISSUE THREAD

**Issue by sirredbeard** [Microsoft/WSL#3249]
The "Run Linux on Windows" landing page on the Microsoft Store hasn't been updated with Ubuntu 18.04 or to give users a clear choice between 16.04 and 18.04.

It shows Ubuntu:

![capture](https://user-images.githubusercontent.com/33820650/40580800-ee3c6ae2-6114-11e8-99ae-461dee78af24.PNG)

And if you click through you get Ubuntu:

![capture2](https://user-images.githubusercontent.com/33820650/40580806-fcd0c440-6114-11e8-8790-622af352ac4b.PNG)

But it's Ubuntu 16.04, if you look at the notes and release date:

![capture3](https://user-images.githubusercontent.com/33820650/40580809-1052d33c-6115-11e8-9b30-8145856f0063.PNG)

Ideally you would see both Ubuntu 16.04 and 18.04 listed as such on the WSL landing page, so users can chose between the versions.

When you search for Ubuntu you see Ubuntu 16.04 listed twice as Ubuntu and again as Ubuntu 16.04, then Ubuntu 18.04.

![capture4](https://user-images.githubusercontent.com/33820650/40580822-4b75ebe8-6115-11e8-956e-7623bca4f992.PNG)

Not giving users the choice up front between 16.04 and 18.04 and having confusing duplicate 16.04 could be addressed by dropping the generic Ubuntu listing and adding both 16.04 and 18.04 to the WSL landing page.

I think this would help reduce confusion and empower users.

**Comment by benhillis** [comment]
Thanks for filing. We have a thread ongoing with the store team to get this page updated. I'll check and see what's taking so long...

**Comment by sirredbeard** [comment]
@benhillis Thank you!

**Comment by sirredbeard** [comment]
@feherneoh 

Yes, there is a generic "Ubuntu" that is 16.04, "Ubuntu 16.04", and "Ubuntu 18.04".

I think it could be simplified to have just "Ubuntu 16.04" and "Ubuntu 18.04" and list them both on the WSL landing page in the Store.

And yes, it is also possible to upgrade from 16.04 to 18.04.
