### ISSUE TITLE
Vim theme doesn't like the console black background

### ISSUE THREAD

**Issue by gosukiwi** [Microsoft/WSL#3250]
I'm use a 256 colors theme in Vim. It works on Linux and macOS but when I run it in Bash on Windows 

I'm using an Ubuntu distro I got in the Windows Store:

```bash
~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

When I open Vim, it looks like this:

![background](https://user-images.githubusercontent.com/161972/40581226-5c9cc090-6129-11e8-9d02-a551c43e65c6.png)

I can't find a way to remove that black background.

**Windows Build Number:** Microsoft Windows [Version 10.0.17134.48]

**Comment by sirredbeard** [comment]
Console development is coming along and it's possible [to do some color customizations](https://github.com/neilpa/cmd-colors-solarized) but they aren't easy to implement.

If you have specific theme requirements, I would probably recommend a [third-party terminal app](https://github.com/sirredbeard/Awesome-WSL#terminals) in the mean time that are just easier to set up.

**Comment by gosukiwi** [comment]
Awesome, thanks @sirredbeard ! [wsltty](https://github.com/goreliu/wsl-terminal) does the trick.
