### ISSUE TITLE
Can't start julia windows binary from within WSL

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/WSL#3258]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.81]

* What you're doing and what's happening:  I download the windows julia binary from [here](https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6.2-win64.exe) and install it normally. I then start wsl (Ubuntu 18.04). From within WSL I then try to start the julia windows, which errors:
````
davidanthoff@DANTHOFF-5820:/mnt/c/Users/david/source/julia-cb$ /mnt/c/Users/david/AppData/Local/julia-0.6/bin/julia.exe
ERROR: error initializing stdio in uv_pipe_open (2, 7)
^C
davidanthoff@DANTHOFF-5820:/mnt/c/Users/david/source/julia-cb$
````
When I start the same julia windows binary from say PowerShell, it starts successfully:
````
C:\Users\david> C:\Users\david\AppData\Local\julia-0.6\bin\julia.exe
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia>
````

* What's wrong / what should be happening instead: The problem is that I can't start the julia windows binary from within WSL, while I can start it from Windows. I would expect that it can just be started from within WSL and work normally.

* Strace of the failing command, if applicable:  [here](https://gist.github.com/davidanthoff/382e66585eea56edab0910d79d020106)

CCing @vtjnash, one of the core julia devs.

**Comment by therealkenc** [comment]
#2370. You are on 17134. Fixed in [17618](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17618-skip-ahead).

**Comment by davidanthoff** [comment]
Excellent!
