### ISSUE TITLE
errno 13

### ISSUE THREAD

**Issue by escape160** [Microsoft/WSL#3260]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

![capture](https://user-images.githubusercontent.com/39752389/40757689-bcc2d71c-6457-11e8-896d-4719984f2424.PNG)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I got an issue after install ubuntu. tying to run some simple script in the classroom, however it is denied every time...with this error message " python3: can't open file 'simple.py': [Errno 13] permission denied";

then trying to chmod 764 simple.py; it was denied again: "chmod: change permissions of 'simple.py': operation not permitted"

![capture png2](https://user-images.githubusercontent.com/39752389/40757874-97d02486-6458-11e8-9f84-e861fb4ce4a2.PNG)

I tried to change the folder's permission to full control, including all sub-folders.  nothing changes, I still got the same error message....denied

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

could someone please help me? very frustrating...thank you!

**Comment by DarthSpock** [comment]
You stripped contributing.md. Follow the template. Repro steps are needed if you want to get help.

**Comment by DarthSpock** [comment]
Alittle better. A couple more things to ask: 

Are you using the default python installed with Ubuntu (or an updated version) or Windows Python? 

Is your homework folder a Windows directory or did you create it in Ubuntu?

**Comment by escape160** [comment]
thank you.  

Yes, I did use the default python (python2) installed with Ubuntu, but updated to python3, since our class is using python3.  

I created the homework folder using Ubuntu

**Comment by sunilmut** [comment]
@escape160 - After `cd homework`, please share the output of these two commands from bash

```
~whoami
~ls -al
```

**Comment by escape160** [comment]
here it is...

![capture](https://user-images.githubusercontent.com/39752389/40808963-ee2f9886-64f6-11e8-9fb3-6c3e6ddd8489.PNG)

**Comment by therealkenc** [comment]
For help running Python3 on Ubuntu you'll get better service in ServerFault, the Ubuntu forums, or a Python forum.

**Comment by escape160** [comment]
thank you!
