### ISSUE TITLE
Can't use commands from Windows in WSL

### ISSUE THREAD

**Issue by nebrelbug** [Microsoft/WSL#3262]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:

I can't run commands that I can run in Windows.

*Example*: I installed Rust for Windows, and it works fine in my Git Bash shell. However, in my Debian Bash, none of the `rustc`, `rustup`, etc commands are available. (When I install Rust for WSL, as described on the Rust Homepage, it rewrites my Windows Rust directory and makes it so the files won't run). When I type in `echo $PATH` in my Bash, it displays this:
![echopathwslrust](https://user-images.githubusercontent.com/25597854/40719025-f8c07006-6409-11e8-9b03-707b7aef8379.png)
Which includes the `/.cargo/bin` link to Rust.

*Another example*: I have `npm` installed on my computer, and it works great on Git Bash, Command Prompt, etc. When I try and run `npm` on my WSL (even though $PATH has npm in it) it doesn't work. None of the modules I installed work either...

* What's wrong / what should be happening instead:
The commands should work

I set my home in WSL to be /mnt/c/Users/(my username), is that part of the problem perhaps? I'd really like to continue doing that...

**Comment by nebrelbug** [comment]
As a side comment, when I run `make cargo` (my cargo rule contains `xargo build --release --target x86_64-unknown-internebos-gnu`) it gives me this error:
```
make (e=2): The system cannot find the file specified.
make: *** [cargo] Error 2
```
According to my research (though I couldn't solve the problem) it means that the values of $PATH are different when I have the shell open and when Make opens the shell for me... maybe that's related? Thanks!

**Comment by benhillis** [comment]
How are you trying to launch Windows binaries?  Keep in mind due to the way Linux shells launch binaries you'll have to add the file extension eg: npm.exe

**Comment by nebrelbug** [comment]
Wow, I just realized that all the programs I'm trying to launch are Windows programs, and that's probably why they're not working. In that case, why does WSL use Windows' path?

**Comment by benhillis** [comment]
They do work, you just need to include the file extension (exe).

**Comment by Voskrese** [comment]
@nebrelbug 

AppendNtPath

```

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"AppendNtPath"=dword:00000000
```

**Comment by Biswa96** [comment]
@Voskrese That registry is value is for Legacy WSL installation from Lxrun.exe. The new registry value Flags works well. See [WSL_DISTRIBUTION_FLAGS enumeration](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826872(v=vs.85).aspx).

**Comment by benhillis** [comment]
Closing, if there are further questions / issues please reopen.
