### ISSUE TITLE
SEGV caught by ps

### ISSUE THREAD

**Issue by cdenneen** [Microsoft/WSL#3264]
> ps -ef |grep ssh
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
ps:root         4     3  0 Jun05 tty1     00:00:00 sudo /usr/sbin/sshd -D
display.c:66: root         5     4  0 Jun05 tty1     00:00:00 /usr/sbin/sshd -D
please report this bug

**Comment by therealkenc** [comment]
Issue template deleted, but presumably same as #3252 given the timing.
