### ISSUE TITLE
gnutls_handshake() failed: Error in the push function

### ISSUE THREAD

**Issue by modInfo** [Microsoft/WSL#3265]
```youtube-dl: ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> (caused by URLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))```

```
update-ca-certificates
ls /etc/ssl/certs | wc -l
445
```

`# openssl s_client -host ftp.halifax.rwth-aachen.de -port 443`
==> http://paste.itunix.eu/view/raw/f5bf9d07

`# openssl s_client -host ftp.halifax.rwth-aachen.de -port 443 -debug`
==> http://paste.itunix.eu/view/raw/38b0f2ef

`# openssl s_client -connect ftp.halifax.rwth-aachen.de:443 -state -nbio`
==> http://paste.itunix.eu/view/raw/0f1fdf4f

On Windows openssl show certificate correctly

No proxy, clean Internet access

Microsoft Windows [Version 10.0.17134.48]

**Comment by modInfo** [comment]
I switched Karspersky off and it works.

**Comment by N0xFF** [comment]
Needs to disable one function:

Settings -> Network -> Encrypted connections scanning -> **Do not scan encrypted connections**

![image](https://user-images.githubusercontent.com/20356954/45706172-c3932b00-bba5-11e8-8715-75650a11a7fa.png)

**Comment by SkqLiao** [comment]
> I switched Karspersky off and it works.

Thank!! I had reinstalled wsl for several times for this problem these days. After I turned off Karspersky and everything became normal.

**Comment by igor-ye** [comment]
> > I switched Karspersky off and it works.
> 
> Thank!! I had reinstalled wsl for several times for this problem these days. After I turned off Karspersky and everything became normal.

The problem and solution are the same as for https://github.com/Microsoft/WSL/issues/3353#issuecomment-455976221
