### ISSUE TITLE
Cuda can not be installed

### ISSUE THREAD

**Issue by dtracers** [microsoft/WSL#327]
As of right now cuda 7.5 can not be installed through the usual means because of the same issue affecting java.  (just thought I would create this and link it to the same issue before someone else does and)

(Also does anyone know if cuda will work at all when compiled manually?)
Same problem as issue #49 

This is through the debian local package method.

Additionally cuda will not work even when this bug is fixed because bash is now aware of the graphics card.

running this command is supposed to list the nvidia card if your computer has one installed

```
lspci | grep -i nvidia
```

its output is this:

```
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
```

This could also be related to the other issues people are having with /proc
(cant find an official issue number for /proc issues)

**Comment by russalex** [comment]
Cuda is not supported at this time.  We have requests to get [Cuda on our User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250010-ubuntu-shell-access-to-system-gpu-ability-to-run).  We're using the user voice to help inform our priority decisions.

**Comment by firewave** [comment]
I also ran into the lspci problem - should this be tracked as a separate issue or is fine having it here implicitly?

**Comment by russalex** [comment]
@firewave, just wondering, but did you hit lspci trying out Cuda or was it in another scenario?  Either way, it would be interesting to have a new User Voice just for lspci to see if it gets any traction.  We know this is a blocker for some people, but it's always good to get a feel for about how many.

**Comment by firewave** [comment]
@russalex I hit the issue using lspci explicitly. I use it to get information about the graphics cards of the system. It's part of a bigger script which fetches hardware information about the system.

**Comment by bootstrapbill123** [comment]
I can confirm with @firewave that this is something you do to check if there is a GPU installed so it could be a broader issue than just for CUDA support.

**Comment by firewave** [comment]
FYI lspci is also used by do-release-upgrade. The errors messages mentioned in the first post happen very early during "Reading cache...".

**Comment by craigloewen-msft** [comment]
Hi folks, we announced today that WSL will support GPU compute! I'll be posting more details about this change today. :)

**Comment by therealkenc** [comment]
The [OP](https://github.com/microsoft/WSL/issues/327#issue-153333839) `lspci | grep -i nvidia` repro is (academically) now LZ #5492

For CUDA and DirectML, /fixed [20150](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20150)

**Comment by Munyola** [comment]
#327 implications problems not yet working not unless render from neighborhood docs.Microsoft.com/windows/wsl

**Comment by Munyola** [comment]
#11045Terminal now supports actions that can run multiple other actions (we heard you like actions,even if azure failed but colour succeed.

**Comment by Munyola** [comment]
No automatic link on terminal run with your experience

**Comment by nonsec** [comment]
> lspci

> pcilib: Cannot open /proc/bus/pci
> lspci: Cannot find any working access method.

5 years later and this still isn't fixed? what's the point of using WSL if you don't even have a real working linux os? virtualbox can do it, why can't WSL? What else is broken?
