### ISSUE TITLE
iwconfig - no wireless extensions

### ISSUE THREAD

**Issue by rootkittt** [Microsoft/WSL#3270]
hey im using kali and windows 10 subsystem. but i have any problems to start the monitor-mode.

if i try "iwconfig" it says no wireless extensions...

`rootz@Rootkit-Surf:~$` iwconfig
`eth0`      no wireless `extensions.`

`lo`        no wireless `extensions.`

`wifi0`     no wireless `extensions.`

`wifi1`     no wireless `extensions.`

`wifi2`     no wireless `extensions.`

the output of `ifconfig` is...

`rootz@Rootkit-Surf:~$` `ifconfig`
`lo:` flags=73<UP,LOOPBACK,RUNNING>  mtu `1500`
       inet 127.0.0.1  netmask `255.0.0.0
       inet6 ::1  prefixlen 128  scopeid `0x0<global>
       loop  (Local `Loopback)
       RX packets 0  bytes 0 (0.0 `B)
       RX errors 0  dropped 0  overruns 0  frame `0
       TX` packets 0  bytes 0 (0.0 `B)
       TX errors 0  dropped 0 overruns 0  carrier 0  collisions `0

`wifi0:` flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu `1500`
        inet 192.168.178.23  netmask 255.255.255.0  broadcast 192.168.178.255
        inet6 2a02:810a:900:3080:2077:8457:db9:9ce6  prefixlen 64  scopeid 0x0<global>
        inet6 2a02:810a:900:3080:a49b:a075:ea28:4d99  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::2077:8457:db9:9ce6  prefixlen 64  scopeid 0x0<global>
        unspec C4-9D-ED-8B-48-37-00-00-00-00-00-00-00-00-00-00  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

`wifi2:` flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu `1500`
        inet 192.168.137.1  netmask 255.255.255.0  broadcast 192.168.137.255
        inet6 fe80::18d7:3266:7aa:a01  prefixlen 64  scopeid 0x0<global>
        unspec C6-9D-ED-8B-4C-36-00-00-00-00-00-00-00-00-00-00  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
what should i do to fix that problem?

**Comment by therealkenc** [comment]
No template but #1104

**Comment by Balachzehri** [comment]
how do it
