### ISSUE TITLE
restoring bash window shrinks the buffer

### ISSUE THREAD

**Issue by mikeymop** [Microsoft/WSL#3271]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
16299.309
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
 1. Execute `tmux`
 2. Minimize, then restore, the window
 3. tmux will now have space belowit
 4. if you disconnect and reconnect to tmux it will reconnect with the proper height
* What's wrong / what should be happening instead:
When you restore a bash prompt that has tmux running the windows console will append an extra line at the bottom of stdout adding a black bar at the bottom of the screen.

If you use a terminal on a unix like operating system this issue is not present. Tmux windows can be minimized and restored at will and will always look proper in a terminal. 

![image](https://user-images.githubusercontent.com/4002969/40862769-8df3862e-65bb-11e8-9ad6-a90d4688fec9.png)

![image](https://user-images.githubusercontent.com/4002969/40862830-b69a3226-65bb-11e8-9f9c-c3cadc43c16d.png)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Quote from your post:

> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the console issue tracker.

**Comment by mikeymop** [comment]
Sorry, I didn't think it was related to console as it doesn't happen on a normal powershell or cmd window.
