### ISSUE TITLE
Horizontal scrollbar obscures text

### ISSUE THREAD

**Issue by BobBall** [Microsoft/WSL#3278]
I routinely use tmux, which has a status bar along the bottom, although I suspect the same behaviour could be observed with other applications such as irssi.

When starting bash there is no horizontal scroll bar, but at some point during the day a horizontal bar appears, obscuring (partially or completely, depending on the absolute height of the console) the bottom line
This makes tmux very hard to use because you can't see which session you are using.

A resize does sometimes temporarily corrects the positioning, but switching to a new console inside tmux repaints the status bar under the scrollbar.

Note that the horizontal scrollbar is fully disabled (as is the vertical) - so there shouldn't be extra content.

![image](https://user-images.githubusercontent.com/1170329/40968842-66aa0a66-68ae-11e8-8b8e-79242a388e1b.png)

Seen on earlier builds, but still present on 1803.

**Comment by DarthSpock** [comment]
Wrong repo. https://github.com/Microsoft/Console is where you want to file though I think there are several reports of this already.

**Comment by BobBall** [comment]
Sorry, and thanks for the pointer!
