### ISSUE TITLE
Rsync stops without successful completion

### ISSUE THREAD

**Issue by arnieswap** [Microsoft/WSL#3280]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) [Microsoft Windows [Version 10.0.17682.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots) 
When I rsync files from local machine to a local UNIX machine, the rsync stops after a while. I have tried it with my Linux and macOS systems and there the file transfer works smoothly.

How: I go to start menu and search for 'bash' it opens ' bash shell. Then I run this command:

swapnil@DESKTOP-QROLF7F:~$ rsync -avzP --delete /mnt/f/Images/ ssh swapnil@192.168.1.185:/Volumes/prime2/Images/

It indexes the files and start transferring file, but then it stops after a while (could be 10 or 20 mins). Nothing happens, so I had to abort  and I get this error: Crsync error: unexplained error (code 130) at rsync.c(638) [sender=3.1.1]

* What's wrong / what should be happening instead:
It should successfully complete the file transfer.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Perennial #2138
