### ISSUE TITLE
I can not connect

### ISSUE THREAD

**Issue by NebitnoIme** [Microsoft/WSL#3287]
Hey, i'm install Pterodactyl panel for game panel and in linux ip 127.0.0.1 go to and access to site. i'm open windows 10 and type 127.0.0.1 and get This Webpage is not available? How to fix? I'm use Vitrual Box for Linux .. use same internet. I'm not talking nicely english :/ Sorry

**Comment by benhillis** [comment]
Are you using WSL or Virtual Box?

**Comment by NebitnoIme** [comment]
Vitrual Box

**Comment by Biswa96** [comment]
Are you using WSL in a VirtuaBox guest?

**Comment by NebitnoIme** [comment]
I do not know what it is "WSL" ..

**Comment by Biswa96** [comment]
OMG!!!!! 😵😱😨😰

**Comment by scshepard** [comment]
WSL is Windows Subsystems for Linux (default is Ubuntu, but others as well).
________________________________
