### ISSUE TITLE
ETA for Fedora on WSL?

### ISSUE THREAD

**Issue by samjones3** [Microsoft/WSL#3288]
Our team is standardized on centos. One or two of us can deal w ubuntu, but we can't get the team, which is %100 on win10 desktops, to use WSL until Fedora is avail from the MS Store.

**Comment by therealkenc** [comment]
#2584

**Comment by samjones3** [comment]
@therealkenc  thanks for the ref to #2584 , but that one is closed, and now this one is closed.  How do we open this as an issue that needs attention?  Thanks!

**Comment by samjones3** [comment]
@therealkenc  Thanks!  I do not use twitter or reddit.  I will give user voice a try.
