### ISSUE TITLE
can i add perf in this ubuntu

### ISSUE THREAD

**Issue by qweccc** [Microsoft/WSL#329]
can i add perf in this ubuntu

WARNING: perf not found for kernel 3.4.0+

  You may need to install the following packages for this specific kernel:
    linux-tools-3.4.0+

**Comment by russalex** [comment]
At this time we are focusing on providing the Bash on Ubuntu environment and some of the developer tools (i.e. node).  Tools like perf have taken a lower priority.  For future releases we'll be using our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page to help inform us on the priorities of the community.

**Comment by therealkenc** [comment]
#1577 is a dupe of this -- which seems like fair game.

**Comment by BeverlyXu** [comment]
Would love to see this feature.

**Comment by therealkenc** [comment]
Will be available in [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/) 20H1, or in [Insiders](https://insider.windows.com/en-us/) now.

**Comment by bushidocodes** [comment]
I'm on 20H1, and I'm unclear how to make this work. 

```
❯ perf
WARNING: perf not found for kernel 4.19.84-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-4.19.84-microsoft-standard
    linux-cloud-tools-4.19.84-microsoft-standard

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard
    linux-cloud-tools-standard
```

I saw you mention this command in another issue. Here is what I see

```
❯ cat /proc/config.gz | gunzip - | grep PERF_EVENTS
CONFIG_HAVE_PERF_EVENTS=y
CONFIG_PERF_EVENTS=y
# CONFIG_PERF_EVENTS_INTEL_UNCORE is not set
# CONFIG_PERF_EVENTS_INTEL_RAPL is not set
# CONFIG_PERF_EVENTS_INTEL_CSTATE is not set
# CONFIG_PERF_EVENTS_AMD_POWER is not set
CONFIG_HAVE_PERF_EVENTS_NMI=y
```

It seems like perhaps the kernel supports it, but I still am missing the associated aptitude packages.

**Comment by Biswa96** [comment]
You can build those Linux kernel tools from source code. Shallow clone the WSL2 Linux kernel repo, cd into tools folder, run `make perf`. The binary will be in that folder.

**Comment by crvdgc** [comment]
> You can build those Linux kernel tools from source code. Shallow clone the WSL2 Linux kernel repo, cd into tools folder, run `make perf`. The binary will be in that folder.

The built `perf` binary can't be executed due to the failure of `perf_event_open` system call, see #4595 . On my system, it gives

```
$ ./perf record --call-graph=dwarf /path/to/binary
perf_event_open(..., 0) failed unexpectedly with error 22 (Invalid argument)
Error:
The sys_perf_event_open() syscall returned with 22 (Invalid argument) for event (cycles:u).
/bin/dmesg | grep -i perf may provide additional information.
```

**Comment by Biswa96** [comment]
@crvdgc In the previous comment by @bushidocodes, he mentioned WSL2 which uses actual Linux kernel. Hence `perf` works.

**Comment by crvdgc** [comment]
> 
> 
> @crvdgc In the previous comment by @bushidocodes, he mentioned WSL2 which uses actual Linux kernel. Hence `perf` works.

Oh, you're right. I didn't realized you were replying to the WSL2 comment. Thanks.

**Comment by postwait** [comment]
I'm running insider release and my kernel (WSL2) is 4.4.0-19592-Microsoft and I'm having the same issue as @crvdgc in that `perf` will not run due to perf_event_open erroring:

```
perf_event_open({type=PERF_TYPE_SOFTWARE, size=0 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_CPU_CLOCK, ...}, -1, 0,
-1, PERF_FLAG_FD_CLOEXEC) = -1 EINVAL (Invalid argument)
perf_event_open({type=PERF_TYPE_SOFTWARE, size=0 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_CPU_CLOCK, ...}, -1, 0,
-1, 0) = -1 EINVAL (Invalid argument)
```

How do I get `4.19.84-microsoft` ?

**Comment by postwait** [comment]
I solved my own issue, I thought WSL2 was the default on insider.  I needed to upgrade my wsl

```
wsl --set-version Ubuntu-18.04 2
```

Then I built perf and it works... to save other people the effort and pain I pushed it to github... hopefully microsoft will build this and I can delete this work-around

https://github.com/postwait/wsl2-stuff/tree/master/linux-tools

**Comment by qweccc** [comment]
perf worked, running on WSL2 gentoo

**Comment by Trass3r** [comment]
> https://github.com/postwait/wsl2-stuff/tree/master/linux-tools

Thanks, I built a VSCode + Docker environment based on this: https://github.com/Trass3r/WSL2-Linux-Kernel-Docker-Build.
Works fine but still no HW perf counters: #4678
