### ISSUE TITLE
lxrun install hangs over ssh (plink)

### ISSUE THREAD

**Issue by BenHagaman** [Microsoft/WSL#3290]
Running this against a generalized image created in Azure from the windows 10 offer on May 17 (Microsoft Windows [Version 10.0.16299.431]) - publisherName = "MicrosoftVisualStudio", offer = "windows", sku = "Windows-10-N-x64", location = 'westus'

I have been able to successfully run "lxrun /install /y" locally, but when I try to do so through ssh(plink) it hangs while displaying download progress. This worked previously. Automated setup is required here as we are creating automated deployments in azure using a generalized image, which removes the linux install during generalization.

I am running the blow command using plink (most recent version - 0.70.0.0) The target windows 10 VM has OpenSSH-Win64 installed (version 0.0.14.0) running ssh agent as Local System and sshd as NT SERVICE/SSHD. 

"plink.exe -ssh <IP_ADDRESS> -l <USERNAME> -i "C:\...\SSH.ppk" "cmd.exe `"/c lxrun /install /y`" 2>&1"

Output:
D o w n l o a d i n g   f r o m   t h e   W i n d o w s   S t o r e . . .   0  0  0  0  0  0  0  0  0  0  0  0  0  0 %
...
...
9 6  9 6 9 6  9

Output always cuts and the process hangs completely at the exact same spot (halfway through printing what looks like 96% again or 97%). I have tried several variations of this using powershell, bat scripts, ps1 scripts, cmd.exe - all have the same result. I have also tried redirecting the output as well as not redirecting ("2>&1", "*>&1", "powershell.exe lxrun... | Out-Null", ...)

I tested the initially stated command against both this current image and a previously created image using a similar setup from an older date. The old image works without issue when running this command using plink.

"plink.exe -ssh <IP_ADDRESS> -l <USERNAME> -i "C:\...\SSH.ppk" "cmd.exe `"/c lxrun /install /y`" 2>&1"

New Version: Microsoft Windows [Version 10.0.16299.431]
Old Version: Microsoft Windows [Version 10.0.15063]

**Comment by Biswa96** [comment]
Did you try other SSH client instead of pklink? Also Microsoft deprecated lxrun.exe installation.

**Comment by BenHagaman** [comment]
Running over ssh when interactively connecting it has no issues - it completes the install without hanging. When I run something along the lines of 
ssh -i <KEY> <USER>@<IP> "lxrun /install /y"
in bash - It hangs in the exact same fashion

Bens-MacBook-Pro-3:.ssh bhagaman$ ssh -i <KEY> <USER>@<IP> "lxrun /install /y"
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

This will install Ubuntu on Windows, distributed by Canonical and licensed under its terms available here: 
https://aka.ms/uowterms

Downloading from the Windows Store... 96%

I am aware that lxrun was deprecated - but is there an equivalent replacement to run this in an automated fashion? We need to automate the install because we are setting this up in azure with a custom image, and generalization removes the linux installation (leaving only the WSL feature enabled)

**Comment by DarthSpock** [comment]
> but is there an equivalent replacement to run this in an automated fashion?

No but there is an issue open in the new [Windows-dev-box-setup-scripts](https://github.com/Microsoft/windows-dev-box-setup-scripts/issues) to for automating Store packages. For now though, the answer is no, you need to install everytime by installing from Store or building the distro yourself using https://github.com/Microsoft/WSL-DistroLauncher. The stand-alone appx files to install without Store capability is coming, it's just taking longer than expected for them to get published.

**Comment by therealkenc** [comment]
> "plink.exe -ssh <IP_ADDRESS> -l -i "C:...\SSH.ppk" "cmd.exe "/c lxrun /install /y" 2>&1"

Output:
D o w n l o a d i n g f r o m t h e W i n d o w s S t o r e . . . 0 0 0 0 0 0 0 0 0 0 0 0 0 0 %
...

Calling this dupe #1228 addressed in 17017 based on symptoms. Try 17134 aka 1803 aka RS4 aka April Update and see if the problem persists. If not please reboot the issue with detailed CLI repro steps on both the client and the server.
