### ISSUE TITLE
Tail -F && tail - f

### ISSUE THREAD

**Issue by nindogo** [Microsoft/WSL#3292]
I am running WSL - and I love it.

This may be a low level issue but ....

Running Debian on Windows 10.
```
C:\Users\hp>ver
Microsoft Windows [Version 10.0.17134.48]
```
I can not get `tail -f` or `tail -F` to follow the logs for qBittorrent. It shows the last 10 lines - but it does not follow the log as it is growing - or files as they change.

Tried it against aptitude's log and that works fine. Is it an issue of populating a log file in windows and "reading" it in WSL?

Thanks.
nindogo

**Comment by therealkenc** [comment]
> [Version 10.0.17134.48]

#925. Try April Update with Ubuntu 18.04 from the Store, or upgrade coreutils yourself per [this](https://github.com/Microsoft/WSL/issues/925#issuecomment-357301112).

**Comment by neoadventist** [comment]
I'm having the same exact issue here! upgrading with core-utils didn't work for me :(  @therealkenc

**Comment by simsicon** [comment]
> I'm having the same exact issue here! upgrading with core-utils didn't work for me :( @therealkenc

According to this [thread](https://www.reddit.com/r/bashonubuntuonwindows/comments/9004w1/tail_with_follow_not_working/), pass  the `---disable-inotify` will solve the problem, I am using 18.04 which should have contain the patch @therealkenc mentioned

**Comment by jhorriga** [comment]
Also having this problem. It's supposed to be fixed but clearly there is a regression. 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Windows 10, 1809 OS Build 17763.195
Microsoft Windows [Version 10.0.17763.195]

tail -f <file> does not follow when the file is written/updated from Windows
This is (I would think) a core scenario that should work.

**Comment by ericnewton76** [comment]
Same issue.  tail -f not picking up file writes via (assuming) windows calls.

**Comment by ilxj** [comment]
I Had meet the same issue

**Comment by arnisjuraga** [comment]
I am using Ubuntu 18.04 WSL 1
If file is located on Linux partition, `tail -f ` works fine. 

But if you are monitoring file located on NTFS, e.g.: 
```tail -f /mnt/c/path/to/file ---disable-inotify```
works.

**Comment by sdalmeida** [comment]
Seems like this is still a problem. 
Using `---disable-inotify` does the trick, but I would say that `tail -f` on wsl should just work out of the box without having to specify any extra flags.
I see that this issue was marked as a duplicate of #925, but that issue was also closed (and this issue is still present).

Should this be relooked into?

**Comment by therealkenc** [comment]
Over in the dupe target
