### ISSUE TITLE
Networking issue, cannot connect to remote servers

### ISSUE THREAD

**Issue by chawkinsuf** [microsoft/WSL#3295]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I cannot connect to remote servers.
```
$ sudo apt-get update
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Could not connect to archive.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (111: Connection refused) [IP: 2001:67c:1560:8001::11 80]
Err:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Unable to connect to archive.ubuntu.com:http: [IP: 2001:67c:1560:8001::11 80]
Err:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Unable to connect to archive.ubuntu.com:http: [IP: 2001:67c:1560:8001::11 80]
Err:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Could not connect to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (111: Connection refused) [IP: 2001:67c:1360:8001::21 80]
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not connect to archive.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (111: Connection refused) [IP: 2001:67c:1560:8001::11 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 2001:67c:1560:8001::11 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 2001:67c:1560:8001::11 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Could not connect to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (111: Connection refused) [IP: 2001:67c:1360:8001::21 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

$ ping google.com
PING google.com (172.217.2.206) 56(84) bytes of data.
^C
--- google.com ping statistics ---
20 packets transmitted, 0 received, 100% packet loss, time 19244ms
```
* What's wrong / what should be happening instead:
Networking is not working. The system will not connect to any ip addresses. I wanted to make sure ping was working for that server, so I ran one in the windows terminal too. I ran a second ping using in the ubuntu terminal and typed ping 172.217.2.206 into a windows terminal. Suddenly, the ping started working in the ubuntu terminal, but only for that one ip.
```
$ ping 172.217.2.206
PING 172.217.2.206 (172.217.2.206) 56(84) bytes of data.
64 bytes from 172.217.2.206: icmp_seq=11 ttl=54 time=48.7 ms
64 bytes from 172.217.2.206: icmp_seq=12 ttl=54 time=50.1 ms
64 bytes from 172.217.2.206: icmp_seq=13 ttl=54 time=54.4 ms
64 bytes from 172.217.2.206: icmp_seq=14 ttl=54 time=47.7 ms
64 bytes from 172.217.2.206: icmp_seq=15 ttl=54 time=43.0 ms
64 bytes from 172.217.2.206: icmp_seq=16 ttl=54 time=49.1 ms
^C
--- 172.217.2.206 ping statistics ---
16 packets transmitted, 6 received, 62% packet loss, time 15147ms
rtt min/avg/max/mdev = 43.060/48.891/54.411/3.357 ms
```

 It seems reproducible in that I can make any ip work in the ubuntu terminal by accessing it in the windows terminal. Only that single ip works however and it doesn't last long. If I stop accessing the ip for about 3 minutes, I can no longer access it anymore. If I keep pinging it though, it seems like it will keep working indefinitely.

I don't have an unusual networking setup. Just a standard connection to my router through wifi.

**Comment by Alternate-Egoist** [comment]
i don't know it is works or not but you could try :)
can you uncomment #precedence in /etc/gai.conf so all the connection prefer through ipv4

![test](https://user-images.githubusercontent.com/37222997/41349190-4cc9288e-6f39-11e8-8b93-b12f5fc60fdf.png)

**Comment by chawkinsuf** [comment]
No luck. I would assume pinging an ipv4 address would force ipv4 though anyway (regardless of the ipv6 addresses listed in the apt-get update).

My computer was updated last night to:
Microsoft Windows [Version 10.0.17134.112]

Same issue persists. I am happy to provide any information to help debugging, but I don't know what might be needed.

**Comment by zhfreal** [comment]
Same here. I am running bonic and have this same issue. The network is working well. I tried curl to get InRelease file and It did work. But apt did not work at all.

And, I find it work with http proxy.

**Comment by WorldofJARcraft** [comment]
Same Problem with Xenial. I can ping remote servers by ip and also domain name (like ping google.de) and ssh to remote server works as well. But everything related to http (like wget or apt) fails.

**Comment by eguisse** [comment]
fixed by disabling Self-Defense in Kaspersky

**Comment by ruiconti** [comment]
It might be a long shot but what worked for me was to run bash from Windows Powershell (also run as administrator)

**Comment by charlesastaylor** [comment]
> Same Problem with Xenial. I can ping remote servers by ip and also domain name (like ping google.de) and ssh to remote server works as well. But everything related to http (like wget or apt) fails.

Bit late to the party but I've just spent an age trying to fix same issue. Found solution [here](https://forum.kaspersky.com/index.php?/topic/395813-bash-windows-10-wsl-connection-issues/&do=findComment&comment=2805896).
