### ISSUE TITLE
Is it possible building linux from sratch through wsl

### ISSUE THREAD

**Issue by realternate** [Microsoft/WSL#3297]
Im just curious to see any guide how to make linux through wsl :)

**Comment by shoffmeister** [comment]
See the documentation here: https://docs.microsoft.com/en-us/windows/wsl/build-custom-distro

**Comment by benhillis** [comment]
@shoffmeister - I believe @realternate is asking about compiling Linux using WSL.  Yes that's possible, and you should be able to use any instructions you find online to accomplish this.

**Comment by therealkenc** [comment]
[Here](https://wiki.gentoo.org/wiki/Handbook:Main_Page), [here](https://wiki.archlinux.org/), [here](https://wiki.alpinelinux.org/wiki/Main_Page), and [here](http://www.linuxfromscratch.org/lfs/) are good places to start. There is no linux kernel in WSL (or rather, you already have the kernel part) so you skip those bits.
