### ISSUE TITLE
CPU steadily increasing and keeps being high

### ISSUE THREAD

**Issue by thebillkidy** [Microsoft/WSL#3299]
Hi All,

When using the WSL recently, I am starting to see high CPU usage (and a slow computer due to it) when using WSL in vscode, but also sometimes the Bash process itself.

I can easily replicate this in vscode, but it's harder to replicate the Bash file cpu process in the Task Manager.

**Windows Version:** 10.0.17686.1003

See more details here:

https://github.com/Microsoft/vscode/issues/51724

**Screenshots:**
![image](https://user-images.githubusercontent.com/591282/41403070-43aad9b0-6fc4-11e8-832e-a3055a38b5b5.png)

![image](https://user-images.githubusercontent.com/591282/41403079-46a6f55e-6fc4-11e8-97ca-d84b1bc317bb.png)

![image](https://user-images.githubusercontent.com/591282/41403265-ca280634-6fc4-11e8-9c55-9eb400904d54.png)

![image](https://user-images.githubusercontent.com/591282/41403380-04b5275a-6fc5-11e8-9a1e-fb042e856563.png)

![image](https://user-images.githubusercontent.com/591282/41403391-0bc3fb7a-6fc5-11e8-8bf5-ffb771e0cb2c.png)

![image](https://user-images.githubusercontent.com/591282/41403408-15b223c8-6fc5-11e8-805d-0b6e2ad7747a.png)

**A dump of this process:**
https://mega.nz/#!DzhRwRwb!0OI9hBcpZSUTm8PluNiixLYlhkUPXU-UnpFlOjQmRro

**Comment by therealkenc** [comment]
If it is "recent" this is probably #3191

**Comment by benhillis** [comment]
This should be fixed in Insider Build 17704.
