### ISSUE TITLE
symbolic link permission denied after auto mounting

### ISSUE THREAD

**Issue by a2975667** [Microsoft/WSL#3300]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.112]

* What you're doing and what's happening:  
I was trying to edit `wsl.conf` (an upgrade from 2018 spring) to auto mount my disks at startup (in order for me to run W10 docker from WSL from [this](https://goo.gl/4yGTDC) tutorial) which causes unexpected behaviors even as `ls`.

This is what i added in `wsl.conf`
```
[automount]
root = /
options = "metadata"
```
The results:
![image](https://user-images.githubusercontent.com/8285540/41426605-bdadb436-7036-11e8-9b27-e4c2487a1d7a.png)

* What's wrong / what should be happening instead:
No errors it should?

**Comment by shoffmeister** [comment]
Your user does not have the necessary privileges to access those objects - not even under Windows.

In Windows Explorer, simply double-click on "C:\Documents and Settings" and all the other items you report above. You will notice exactly the same behaviour.

So inside WSL you see exactly what you see on the outer Windows host.

**Comment by therealkenc** [comment]
#2779
