### ISSUE TITLE
Directory symbolic links inside the WSL root are not recognized by Windows programs

### ISSUE THREAD

**Issue by sysprogs** [Microsoft/WSL#3301]
We are using Windows 1803 (build 17134.112) and WSL with Ubuntu.
It appears that symlinks created from WSL outside the rootfs are properly recognized by Windows programs, e.g.:

(from bash)
```
cd /mnt/e/temp
mkdir dir1
ln -s dir1 dir2
```

(from cmd.exe)
```
cd /d e:\temp
dir
```

yields:
```
06/14/2018  10:36 AM    <DIR>          dir1
06/14/2018  10:36 AM    <SYMLINKD>     dir2 [dir1]
```

However, doing this inside the WSL's rootfs doesn't work:

(from bash)
```
cd ~
mkdir dir1
ln -s dir1 dir2
```

(from cmd.exe)
```
cd /d C:\Users\testuser\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\testuser
dir
```

yields:

```
06/14/2018  10:37 AM    <DIR>          dir1
06/14/2018  10:37 AM                 4 dir2
```

Here **dir2** is not shown as a directory symlink, but instead as a test file containing the symlink target ("dir1"). Opening "dir2" from Windows Explorer or any other Windows tools doesn't work either.

**Comment by therealkenc** [comment]
> other Windows tools doesn't work either.

Correct. [It doesn't](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/). 

#1524
