### ISSUE TITLE
Unable to update my 18.04 fresh install, without the store. 

### ISSUE THREAD

**Issue by lewisdonofrio** [Microsoft/WSL#3302]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

Microsoft Windows [Version 10.0.16299.492]

donofrio@WSAL0196:] sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y && sudo sync && sudo sync
[sudo] password for donofrio:
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [32.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [142 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [55.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [84.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [2684 B]
Fetched 559 kB in 6s (100 kB/s)
Reading package lists... Done
W: http: aptMethod::Configuration: could not load seccomp policy: Invalid argument
W: http: aptMethod::Configuration: could not load seccomp policy: Invalid argument
W: store: aptMethod::Configuration: could not load seccomp policy: Invalid argument
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  apport apt apt-utils bind9-host btrfs-progs cryptsetup-bin curl dirmngr dnsutils dpkg fonts-ubuntu-font-family-console gnupg gnupg-agent isc-dhcp-client libapparmor-perl
  libapt-pkg5.0 libbind9-160 libcurl3 libgnutls30 libidn2-0 libirs160 libisccc160 libisccfg160 liblwres160 liblxc1 libnss-systemd libpam-systemd libperl5.26 libpsl5 libsystemd0
  nplan perl perl-base python3-apport rsyslog strace systemd ubuntu-server
The following packages will be upgraded:
  apparmor at bash bash-completion bsdutils btrfs-tools byobu ca-certificates cloud-guest-utils cloud-init command-not-found command-not-found-data console-setup
  console-setup-linux cryptsetup debconf debconf-i18n dh-python distro-info-data dmeventd dmsetup dnsmasq-base e2fslibs e2fsprogs eatmydata ebtables ethtool fdisk file
  friendly-recovery gcc-7-base gcc-8-base geoip-database gettext-base gir1.2-glib-2.0 git git-man gnupg-l10n gpgv hdparm initramfs-tools initramfs-tools-bin initramfs-tools-core
  iproute2 isc-dhcp-common iso-codes keyboard-configuration language-selector-common libapparmor1 libapt-inst2.0 libatm1 libblkid1 libc-bin libc6 libcom-err2 libcomerr2
  libcurl3-gnutls libdb5.3 libdevmapper-event1.02.1 libdevmapper1.02.1 libdrm-common libdrm2 libeatmydata1 libelf1 libext2fs2 libfdisk1 libfreetype6 libgcc1 libgcrypt20 libgdbm5
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libgraphite2-3 libharfbuzz0b libicu60 libidn11 libkeyutils1 liblvm2app2.2 liblvm2cmd2.02 liblz4-1 libmagic-mgc libmagic1
  libmount1 libmpdec2 libncurses5 libncursesw5 libnghttp2-14 libnih1 libpam-modules libpam-modules-bin libpam-runtime libpam0g libplymouth4 libpolkit-agent-1-0
  libpolkit-backend-1-0 libpolkit-gobject-1-0 libpopt0 libprocps6 libpython3-stdlib libpython3.6 libpython3.6-minimal libpython3.6-stdlib libseccomp2 libselinux1
  libsemanage-common libsemanage1 libslang2 libsmartcols1 libss2 libssl1.0.0 libssl1.1 libstdc++6 libtinfo5 libudev1 libuuid1 libxcb1 locales lshw lvm2 lxcfs lxd lxd-client
  man-db mawk mdadm mlocate mount multiarch-support nano ncurses-base ncurses-bin ncurses-term netcat-openbsd open-iscsi open-vm-tools openssh-client openssh-server
  openssh-sftp-server openssl pastebinit patch perl-modules-5.26 plymouth plymouth-theme-ubuntu-text policykit-1 popularity-contest powermgmt-base procps publicsuffix
  python-apt-common python3 python3-apt python3-cffi-backend python3-commandnotfound python3-cryptography python3-debconf python3-distro-info python3-distupgrade
  python3-distutils python3-gdbm python3-lib2to3 python3-minimal python3-pkg-resources python3-problem-report python3-serial python3-software-properties python3-update-manager
  python3.6 python3.6-minimal rsync sensible-utils snapd software-properties-common sosreport squashfs-tools ssh-import-id systemd-sysv tcpdump tzdata ubuntu-advantage-tools
  ubuntu-keyring ubuntu-minimal ubuntu-release-upgrader-core ubuntu-standard ucf udev unattended-upgrades update-manager-core update-notifier-common util-linux uuid-runtime vim
  vim-common vim-runtime vim-tiny vlan wget xdg-user-dirs xfsprogs xxd
201 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
Need to get 1023 kB/90.0 MB of archives.
After this operation, 18.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 command-not-found-data amd64 18.04.5 [1009 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-commandnotfound all 18.04.5 [9020 B]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 command-not-found all 18.04.5 [5184 B]
Fetched 1023 kB in 1s (734 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 27026 files and directories currently installed.)
Preparing to unpack .../bash_4.4.18-2ubuntu1_amd64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:368: __spawnix: Assertion `ec >= 0' failed.
dpkg: error processing archive /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb (--unpack):
 new bash package pre-installation script subprocess was killed by signal (Aborted), core dumped
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
Errors were encountered while processing:
 /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb
W: http: aptMethod::Configuration: could not load seccomp policy: Invalid argument
E: Sub-process /usr/bin/dpkg returned an error code (1)

donofrio@WSAL0196:] sudo dpkg -i /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb
(Reading database ... 27026 files and directories currently installed.)
Preparing to unpack .../bash_4.4.18-2ubuntu1_amd64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:368: __spawnix: Assertion `ec >= 0' failed.
dpkg: error processing archive /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb (--install):
 new bash package pre-installation script subprocess was killed by signal (Aborted), core dumped
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
Errors were encountered while processing:
 /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb
donofrio@WSAL0196:~$ bash --version
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
donofrio@WSAL0196:~$

***STUCK with insecure 18.04 till this is worked around****

**Comment by shoffmeister** [comment]
Try this:
a) update to the most current version of Windows 10
b) have a look at https://github.com/meefik/linuxdeploy/issues/869#issuecomment-345659515
c) have a look at https://forums.kali.org/showthread.php?38997-Getting-quot-http-aptMethod-Configuration-could-not-load-seccomp-policy-quot-error
d) tell us which single command still produces the error - your upgrade seems to have been fine, mostly

What you are experiencing most like stems from the configuration of your Linux applications.

**Comment by lewisdonofrio** [comment]
It's the failed to update bash that is one of the "Linux applications" that most anyone uses daily with linux (I mean unless your ksh or another shell.)

It's exactly this issue:
Preparing to unpack .../bash_4.4.18-2ubuntu1_amd64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:368: __spawnix: Assertion `ec >= 0' failed.
dpkg: error processing archive /var/cache/apt/archives/bash_4.4.18-2ubuntu1_amd64.deb (--unpack):
new bash package pre-installation script subprocess was killed by signal (Aborted), core dumped

**Comment by therealkenc** [comment]
>  [Version 10.0.16299.492]

#2615

**Comment by Kihara-tony** [comment]
I GET THIS ERROR WHEN TRYING TO INSTALL PYTHON AND PIP
moringa@moringa-Lenovo-V110-15ISK:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  python3-debconf update-notifier-common
The following packages will be upgraded:
  python3-debconf update-notifier-common
2 to upgrade, 0 to newly install, 0 to remove and 81 not to upgrade.
58 not fully installed or removed.
Need to get 0 B/164 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 188077 files and directories currently installed.)
Preparing to unpack .../python3-debconf_1.5.66ubuntu1_all.deb ...
/var/lib/dpkg/info/python3-debconf.prerm: 6: /var/lib/dpkg/info/python3-debconf.prerm: py3clean: not found
dpkg: warning: old python3-debconf package pre-removal script subprocess returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/prerm: 6: /var/lib/dpkg/tmp.ci/prerm: py3clean: not found
dpkg: error processing archive /var/cache/apt/archives/python3-debconf_1.5.66ubuntu1_all.deb (--unpack):
 new python3-debconf package pre-removal script subprocess returned error exit status 127
/var/lib/dpkg/info/python3-debconf.postinst: 6: /var/lib/dpkg/info/python3-debconf.postinst: py3compile: not found
dpkg: error while cleaning up:
 installed python3-debconf package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/python3-debconf_1.5.66ubuntu1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
moringa@moringa-Lenovo-V110-15ISK:~$ sudo apt-get clean
moringa@moringa-Lenovo-V110-15ISK:~$ sudo apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 python3-debconf : Depends: debconf (= 1.5.66) but 1.5.66ubuntu1 is installed
 update-notifier : Depends: update-notifier-common (= 3.192.1.7) but 3.192.1.5 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
moringa@moringa-Lenovo-V110-15ISK:~$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  python3-debconf update-notifier-common
The following packages will be upgraded:
  python3-debconf update-notifier-common
2 to upgrade, 0 to newly install, 0 to remove and 81 not to upgrade.
58 not fully installed or removed.
Need to get 164 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ke.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-debconf all 1.5.66ubuntu1 [4,060 B]
Get:2 http://ke.archive.ubuntu.com/ubuntu bionic-updates/main amd64 update-notifier-common all 3.192.1.7 [160 kB]
Fetched 164 kB in 0s (422 kB/s)                 
debconf: Unable to initialise frontend: Dialog
debconf: (Dialogue frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
(Reading database ... 188077 files and directories currently installed.)
Preparing to unpack .../python3-debconf_1.5.66ubuntu1_all.deb ...
/var/lib/dpkg/info/python3-debconf.prerm: 6: /var/lib/dpkg/info/python3-debconf.prerm: py3clean: not found
dpkg: warning: old python3-debconf package pre-removal script subprocess returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/prerm: 6: /var/lib/dpkg/tmp.ci/prerm: py3clean: not found
dpkg: error processing archive /var/cache/apt/archives/python3-debconf_1.5.66ubuntu1_all.deb (--unpack):
 new python3-debconf package pre-removal script subprocess returned error exit status 127
/var/lib/dpkg/info/python3-debconf.postinst: 6: /var/lib/dpkg/info/python3-debconf.postinst: py3compile: not found
dpkg: error while cleaning up:
 installed python3-debconf package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/python3-debconf_1.5.66ubuntu1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
moringa@moringa-Lenovo-V110-15ISK:~$ sudo dpkg --configure -a
Setting up libglvnd0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libglvnd0:i386 (1.0.0-2ubuntu2.3) ...
Setting up libapt-inst2.0:amd64 (1.6.11) ...
Setting up libnss-systemd:amd64 (237-3ubuntu10.22) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Setting up libnss-myhostname:amd64 (237-3ubuntu10.22) ...
Setting up libdb5.3:amd64 (5.3.28-13.1ubuntu1.1) ...
Setting up libdb5.3:i386 (5.3.28-13.1ubuntu1.1) ...
Setting up apt-utils (1.6.11) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Setting up debconf (1.5.66ubuntu1) ...
debconf: Unable to initialise frontend: Dialog
debconf: (Dialogue frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
Setting up debconf-i18n (1.5.66ubuntu1) ...
Setting up systemd-sysv (237-3ubuntu10.22) ...
Setting up libelf1:amd64 (0.170-0.4ubuntu0.1) ...
Setting up libelf1:i386 (0.170-0.4ubuntu0.1) ...
Setting up mutter-common (3.28.4-0ubuntu18.04.1) ...
Setting up evolution-data-server-common (3.28.5-0ubuntu0.18.04.2) ...
Setting up libglib2.0-0:i386 (2.56.4-0ubuntu0.18.04.3) ...
Setting up libglib2.0-0:amd64 (2.56.4-0ubuntu0.18.04.3) ...
Setting up libgnome-bluetooth13:amd64 (3.28.0-2ubuntu0.2) ...
Setting up libgnutls30:amd64 (3.5.18-1ubuntu1.1) ...
Setting up libgnutls30:i386 (3.5.18-1ubuntu1.1) ...
Setting up gnome-shell-common (3.28.4-0ubuntu18.04.1) ...
Setting up libcamel-1.2-61:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libegl1:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libglib2.0-data (2.56.4-0ubuntu0.18.04.3) ...
dpkg: dependency problems prevent configuration of python3-debconf:
 python3-debconf depends on debconf (= 1.5.66); however:
  Version of debconf on system is 1.5.66ubuntu1.

dpkg: error processing package python3-debconf (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up udev (237-3ubuntu10.22) ...
update-initramfs: deferring update (trigger activated)
Setting up gnome-bluetooth (3.28.0-2ubuntu0.2) ...
dpkg: dependency problems prevent configuration of update-notifier:
 update-notifier depends on update-notifier-common (= 3.192.1.7); however:
  Version of update-notifier-common on system is 3.192.1.5.

dpkg: error processing package update-notifier (--configure):
 dependency problems - leaving unconfigured
Setting up libgles2:amd64 (1.0.0-2ubuntu2.3) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Setting up initramfs-tools-bin (0.130ubuntu3.8) ...
Setting up libglx0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libglx0:i386 (1.0.0-2ubuntu2.3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up libglib2.0-bin (2.56.4-0ubuntu0.18.04.3) ...
Setting up libdbus-1-3:amd64 (1.12.2-1ubuntu1.1) ...
Setting up libdbus-1-3:i386 (1.12.2-1ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Setting up libdw1:amd64 (0.170-0.4ubuntu0.1) ...
Setting up gir1.2-gnomebluetooth-1.0:amd64 (3.28.0-2ubuntu0.2) ...
Setting up initramfs-tools-core (0.130ubuntu3.8) ...
Setting up initramfs-tools (0.130ubuntu3.8) ...
update-initramfs: deferring update (trigger activated)
Setting up libgl1:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libgl1:i386 (1.0.0-2ubuntu2.3) ...
Setting up dbus (1.12.2-1ubuntu1.1) ...
A reboot is required to replace the running dbus-daemon.
Please reboot the system when convenient.
Setting up libpam-systemd:amd64 (237-3ubuntu10.22) ...
debconf: Unable to initialise frontend: Dialog
debconf: (Dialogue frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
Setting up dbus-x11 (1.12.2-1ubuntu1.1) ...
Setting up dbus-user-session (1.12.2-1ubuntu1.1) ...
Processing triggers for gconf2 (3.2.6-4ubuntu1) ...
Setting up libmutter-2-0:amd64 (3.28.4-0ubuntu18.04.1) ...
Setting up libedataserver-1.2-23:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libebackend-1.2-10:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libebook-contacts-1.2-2:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up gir1.2-mutter-2:amd64 (3.28.4-0ubuntu18.04.1) ...
Setting up libedata-book-1.2-25:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libedataserverui-1.2-2:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up mutter (3.28.4-0ubuntu18.04.1) ...
Setting up libecal-1.2-19:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libedata-cal-1.2-28:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up libebook-1.2-19:amd64 (3.28.5-0ubuntu0.18.04.2) ...
Setting up evolution-data-server (3.28.5-0ubuntu0.18.04.2) ...
Setting up gnome-shell (3.28.4-0ubuntu18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for initramfs-tools (0.130ubuntu3.8) ...
update-initramfs: Generating /boot/initrd.img-4.19.28-acs-patch
Errors were encountered while processing:
 python3-debconf
 update-notifier
moringa@moringa-Lenovo-V110-15ISK:~$
