### ISSUE TITLE
[Community/Meta] IRC, Telegram, Slack channel for WSL community?

### ISSUE THREAD

**Issue by sirredbeard** [Microsoft/WSL#3306]
Many open source projects have a live chatroom in addition to bug trackers, mailing lists, and wikis. They seem to be part of the community toolkit around open source projects. There seems to be some benefit to the live interaction in addition to more asynchronous communication.  It is also likely that some of WSL's potential target users are already using IRC and Telegram. 

I think designating a WSL live chatroom somewhere would be useful, for referencing on the README.md and pointing people to for additional assistance. I am posting this to generate discussion about this idea. Of course there is where to chose from: IRC, Slack, Telegram, Discord. There is already ##windows-wsl on Freenode and it is usually populated by ~30 folks.

**Comment by benhillis** [comment]
Closing out this discussion. If somebody would like to make a channel please submit a PR to the readme with the link.
