### ISSUE TITLE
Node.js freezes on stdin buffer larger than 163840 bytes

### ISSUE THREAD

**Issue by zanona** [Microsoft/WSL#3307]
Hey guys, I have been experiencing a very odd issue where node is simply freezing whenever calling `cmd.stdin.end()` with data larger than `163840 bytes`.
Perhaps this can be related to #1774, however I decided it's best to open a new issue, since it may as well be a different thing.

The code below works fine on OSX and Linux, but surprisingly fails on WSL runnnig Ubuntu.

```node
const spawn = require('child_process').spawn;
const cmd = spawn('wc', ['-c']);
const stdin = Buffer.alloc(163841); // works when using 163840
cmd.stdout.pipe(process.stdout);
cmd.stdin.write(stdin);
cmd.stdin.end();
````
I also noticed that when piping a large stdin directly with `process.stdin.pipe(cmd.stdin)` the problem didn't occurr at all, however, whenever manipulating stdin like the above, will cause this unexpected behaviour.

#### specs 
- Windows 10 - 1803 (build 17686.1003)
- Ubuntu 16.04 LTS (build 20180510.1)
- Same behaviour on Debian 9
- Node.js 10.4.1

**Comment by therealkenc** [comment]
You deleted the template. `strace -f -o yourthing.strace node yourthing.js`. Please link a [gist](https://gist.github.com/).

**Comment by therealkenc** [comment]
nvm. Spins on `epoll_wait()`. This is a right repro of #3191

**Comment by zanona** [comment]
Fixed on build 17704 as per https://github.com/Microsoft/WSL/issues/3191#issuecomment-400877977

Thanks, so much!
