### ISSUE TITLE
How to get my windows PATH variables accessible from the WSL bash?

### ISSUE THREAD

**Issue by firou1925** [Microsoft/WSL#3308]
When trying to run npm or node or any other windows PATH variables from bash I can't. Is there any solution for this?

**Comment by Voskrese** [comment]
root@net:/mnt/f# 
`which npm`
`/usr/bin/npm`

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{8fa2e5cc-b32b-4e49-8e17-333d5e353907}
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{ID_WSL}`
```

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{5176076a-d649-4763-a822-c3930825fc92}]
"Flags"=dword:00000007
```

**Comment by benhillis** [comment]
Please fill out the issue template. Not enough info to go on here. By default yout Windows path variable is automatically added to the end of your $PATH. You will need to fully qualify the binary name (add .exe)
