### ISSUE TITLE
Failed to start pteroq.service: Launch helper exited with unknown return code 1?

### ISSUE THREAD

**Issue by NebitnoIme** [Microsoft/WSL#3309]
Hey, i'm don't know good speak english.. Sry. I'm created game panel pterodactyl and  `sudo systemctl start pteroq` and get error "Failed to start pteroq.service: Launch helper exited with unknown return code 1
See system logs and 'systemctl status pteroq.service' for details." How to fix? I'm used Sub System Ubuntu 16.04 LTS to Windows 10 ..

**Comment by therealkenc** [comment]
`systemctl` isn't functional on WSL right now. See #994.
