### ISSUE TITLE
NPM install Webpack is running into a bunch of errors. 

### ISSUE THREAD

**Issue by thedonquixotic** [Microsoft/WSL#3310]
Microsoft Windows [Version 10.0.17134.112]

# What I'm doing and what's happening:

I'm a designer learning how to code. I type 

`npm install webpack webpack-dev-server --save-dev`

which follows the tutorial I'm following [[here]](https://css-tricks.com/introduction-webpack-entry-output-loaders-plugins/)

The thing looks like it's installing but then it ends in a bunch of errors and the node modules folder is empty. 

I've already tried sudo, and when I `which npm` I get the linux `usr/bin` etc location that I would expect. It's not running Node from my Windows Program Files folder. 

# EDIT  
It now kind of works? Idk what happened. I just kept telling it to install multiple times and eventually it did I guess? Anyway, my build isn't working.The debug file is what it's giving me below. I was going to give the previous debug file from when it was acting wonky. I think it's an issue to do with my package.json but I thought I might as well post it for someone to give feedback on while I continue to troubleshoot. 

````
 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 silly lifecycle @~prebuild: no script for prebuild, continuing
7 info lifecycle @~build: @
8 verbose lifecycle @~build: unsafe-perm in lifecycle true
9 verbose lifecycle @~build: PATH: /usr/share/npm/bin/node-gyp-bin:/mnt/c/Users/Owner/Work/Web/WebpackPractice/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle @~build: CWD: /mnt/c/Users/Owner/Work/Web/WebpackPractice
11 silly lifecycle @~build: Args: [ '-c', 'webpack' ]
12 silly lifecycle @~build: Returned: code: 2  signal: null
13 info lifecycle @~build: Failed to exec build script
14 verbose stack Error: @ build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @
16 verbose cwd /mnt/c/Users/Owner/Work/Web/WebpackPractice
17 error Linux 4.4.0-17134-Microsoft
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error @ build: `webpack`
22 error Exit status 2
23 error Failed at the @ build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Voskrese** [comment]
`23 error Tell the author that this fails on your system:`
for Windows ?

**Comment by thedonquixotic** [comment]
I'm on windows but using wsl and bash.

**Comment by Voskrese** [comment]
`'/usr/bin/node', '/usr/bin/npm'` - linux _pseudo_
`uname -a`  - linux _pseudo_

`cmd.exe`
`ver` - windows
c:\program ...\npm\npm.exe - windows

**Comment by chimalsky** [comment]
@thedonquixotic 

How did you use the information @Voskrese wrote to resolve your issue? -- if you were able to resolve...

**Comment by thedonquixotic** [comment]
@chimalsky  I actually dont' know why it started working. I just kept calling the command over and over again and eventually it worked.

**Comment by chimalsky** [comment]
Haha alright.

For me I had permissions problems because I installed either npm or node the 'incorrect' way.

I reinstalled everything using NVM instead of npm and it worked for me.

Now I'm able to use npm and webpack with joy on WSL

**Comment by EPOTH** [comment]
just try a "sudo npm install webpack webpack-dev-server --save-dev"

or change your wsl user permissions to reflect your needs .
