### ISSUE TITLE
Particular path doesn't mount in docker: /usr/local/bin/docker-compose

### ISSUE THREAD

**Issue by ODemidenko** [microsoft/WSL#3317]
windows 1803
I need to run docker-compose from within docker container. for this purpose I use following mounting:
```	
volumes:
	      - /var/run/docker.sock:/var/run/docker.sock
	      - /usr/bin/docker:/usr/bin/docker
	      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose`
```
docker.sock mounts perfectly.  I can create new docker containers from within a container.
But docker-compose isn't mounted (creates an empty folder in docker, instead of the mounted file).

What can be the reason for the `/usr/local/bin/docker-compose` not to get mounted?

The only specific wsl setting that can potentially affect this is:
`/etc/wsl.conf`
which is set like this:
```
[automount]
root = /
options = "metadata"
```

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
