### ISSUE TITLE
How can I start OpenSSH automatically after boot?

### ISSUE THREAD

**Issue by Luberen** [Microsoft/WSL#3318]
* Your Windows build number: 
17134.112

* What's wrong / what should be happening instead:
SSHD was automatically restarted when I login as my own username.
Currently I changed it to **root** and now SSHD doesn't restart automatically after reboot PC.
How can I enable auto-start SSHD after boot when login as root?
My Ubuntu version is 18.04.

**Comment by SRGOM** [comment]
https://www.reddit.com/r/bashonubuntuonwindows/comments/8jd7kk/a_relatively_simple_way_to_start_services_upon/

**Comment by Lappro** [comment]
I'm currently using this script, which is much simpler than that reddit post:
`#!/bin/bash

# Edit this for your relevant services.
services=(ssh mysql apache2)

for service in "${services[@]}"
do
        if (( $(ps -ef | grep -v grep | grep $service | wc -l) == 0 ))
        then
                # Uncomment to get messages.
#               echo "Starting service ${service}"
                (sudo service $service start > /dev/null &)
        fi

done
`
Save that in startservers.sh file and make it executable: `chmod +x startservers.sh`.

Then add it in your .bashrc, preferably for the user your bash has set for initial login:
`echo ./startservers.sh >> .bashrc`


It simply checks if the service is already started, if not it starts it. So there is no harm in having the script executed more than once.

**Comment by Luberen** [comment]
@Lappro Do I have to create new `startservers.sh` file?

**Comment by Lappro** [comment]
Yes it should be a new file. However you can name it whatever you want.

**Comment by therealkenc** [comment]
#511
