### ISSUE TITLE
terminal display issues on Insider build

### ISSUE THREAD

**Issue by nicferrier** [Microsoft/WSL#3322]
The terminal looks broken in the latest builds; I'm on Windows Insider and have build:

    17692.red_prerelease.180609.1317

ver output shows:

    Microsoft Windows [Version 10.0.17692.1000]

Steps to recreate:

* open a bash terminal, say, ubuntu 16 or 18
* view a file, eg:
    
      view .bashrc

* cursor down a page of lines, so the terminal has to scroll
* see the screen garble and all the lines get compressed to the bottom line

      TERM reports xterm-256color

View is just one way to validate, I haven't been able to narrow it down but many things that do sophisticated screen are failing.

* ls -l works
* htop works
* less -r works
* emacs -nw works
* view doesn't work
* vi doesn't work
* vi doesn't work in a remote ssh from the terminal

I'm not sure when this broke as I haven't used it that much in the past week.

Any help?

**Comment by therealkenc** [comment]
[Windows Console issue tracker](https://github.com/microsoft/console)
