### ISSUE TITLE
apt not funtioning

### ISSUE THREAD

**Issue by Poseidon-Inc** [Microsoft/WSL#3323]
when I run any apt command (eg. apt-get install wireshark) this is the output:
  
E: Syntax error /etc/apt/apt.conf.d/999seccomp:1: Malformed tag
help will be greatly appreciated

**Comment by Voskrese** [comment]
`rm /etc/apt/apt.conf.d/999seccomp`

there is no such file in the system by default, you added it yourself, and there are errors, why apt can not work

**Comment by Poseidon-Inc** [comment]
thank you for the response ,so how do I fix it

**Comment by Voskrese** [comment]
`sudo mv /etc/apt/apt.conf.d/999seccomp /tmp`

`sudo apt-get install wireshark`

**Comment by therealkenc** [comment]
Thanks Voskrese.

**Comment by Poseidon-Inc** [comment]
its working thank you
