### ISSUE TITLE
How to relocate“temp” folder?

### ISSUE THREAD

**Issue by Neutron3529** [Microsoft/WSL#3329]
for person using SSD and have a large memory (for example, I myself), it may be better to relocate "Temp" folder(`%AppData%\Local\lxss\Temp`) to another location (e.g., just put them into RAM-disk)
but either using mklink/j or mklink/d will got an error 0x80070057 or 0x80070780 or something like that.
what's more, use `ln -s` in wsl to relocate usr folder could also cause the same problem(0x80070780).
it there any method to relocate Temp folder?

**Comment by Biswa96** [comment]
Which temp folder are you talking about? Provide a full path for example.

**Comment by Neutron3529** [comment]
Sorry
`%AppData%\Local\lxss\Temp`

**Comment by therealkenc** [comment]
Duping into #449 for want of a better home. There is no supported method to relocate `%AppData%\Local\lxss\Temp` would be the short answer to the concrete question asked. The second post is too scattered to give any kind of definitive response. For further assistance, please see [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) and re-file with a set of CLI repro steps from clean install and someone can try to help.
