### ISSUE TITLE
BSOD KERNEL_SECURITY_CHECK_FAILURE when running ansible in Ubuntu 18.04

### ISSUE THREAD

**Issue by mhulscher** [Microsoft/WSL#3331]
* **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

I can provide an `strace` and minidump on request

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.17134.81]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Running `ansible` or `ansible-playbook` version `2.1.0.0` from a python2 virtualenv on ubuntu 18.04.
```
strace -o ansible-playbook.strace -f ansible-playbook -vvv --diff -i foo_inventory bar.yml
```

* What's wrong / what should be happening instead:

BSOD of type `KERNEL_SECURITY_CHECK_FAILURE`

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

I can mail this upon request.

**Comment by benhillis** [comment]
Yes, please forward the mini dump to secure@microsoft.com.

**Comment by mhulscher** [comment]
Sent minidump and strace. I referred to the issue number in the subject.

**Comment by benhillis** [comment]
Thanks, Mitch. I got your dump and will take a look when I get to my desk.

**Comment by benhillis** [comment]
The issue is understood, we are working on a fix now.

**Comment by mhulscher** [comment]
I see that a `fixinbound` label has been added, for which I am very grateful! However, can this be made more specific? I am curious when a patch is expected.

**Comment by MikeGitb** [comment]
Shouldn't BSOD errors and the like also be fixed in the current release version now that wsl is out of beta?

**Comment by onomatopellan** [comment]
@MikeGitb You are right, BSOD and regressions are special cases that could be backported to current release but it would take weeks from the moment the fix hits an insider build until people gets it on a cumulative update.
