### ISSUE TITLE
Permission denied for very specific .cmd files

### ISSUE THREAD

**Issue by Asaaj** [Microsoft/WSL#3332]
While I have not tried every file extension with this, I know it happens with `.cmd` or `.CMD` files. All of these following files, once created, will return `permission denied` errors when trying to read/write them (I used `cat` for testing):

- `9.asdf.asdf.cmd`
- `9.asd.cmd`
- `test.abcd.ef.cmd`
- `test.ab.ef.cmd`
- `.ab.ef.cmd`
- `abcd.ef.gh.cmd`

These have no issues:

- `abc.ef.cmd`
- `abcd.ef.cmd`

I'm having trouble nailing down the exact pattern that makes these files invalid, but they all have multiple periods and either (1) at least one group of 3 or more letters after the first period (other than the `.cmd`) or (2) 3 or more periods. Again, the exact pattern is hard to find. 

Can anyone else reproduce this issue? I'm running Windows 10.0.15063 with Ubuntu 16.04.4 LTS Xenial

**Comment by benhillis** [comment]
Can you please provide some repro steps, I'm not able to reproduce this:

```
ben@BENHILL-X1:/mnt/c/Users/benhill$ echo foo > 9.asdf.asdf.cmd
ben@BENHILL-X1:/mnt/c/Users/benhill$ cat 9.asdf.asdf.cmd
foo
```

**Comment by Asaaj** [comment]
Those are the steps on my machine, so I'm not sure what's different. This is my output:

```
jacob:~$ echo foo > 9.asdf.asdf.cmd
bash: 9.asdf.asdf.cmd: Permission denied
```

**Comment by 0xbadfca11** [comment]
A similar issue is #3079.
Check the security software you're using.

**Comment by Asaaj** [comment]
Good call, McAfee logged those accesses as "Suspicious Double File Extension Execution" threats. Wish work would let me uninstall it. Thanks for your help
