### ISSUE TITLE
Unable to enable WSL in Windows 10 Enterprise

### ISSUE THREAD

**Issue by hrsmanian** [microsoft/WSL#3333]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  Microsoft Windows [Version 10.0.16299.431

* What you're doing and what's happening: I am trying to enable the WSL but getting the error below. Not sure which parent feature is missing

PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -All
Enable-WindowsOptionalFeature : One or several parent features are disabled so current feature can not be enabled.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

even after rebooting, WSL is not enabled

* What's wrong / what should be happening instead: WSL should enabled. My update is up to date

**Comment by lewisdonofrio** [comment]
not sure I'm 10.0.16299.492 so I don't think that is it, my build steps that I use because my corp removes 'the store' from w10 - http://www.tinyurl.com/donofrioworkdesk this is my step 3 in the raw doc that I have "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux" from "Admin Powershell" (should have just asked - did you "Run As Administrator" when you started your powershell?)  Also I do not think you need "-All" that could be it?

**Comment by lewisdonofrio** [comment]
We're running 1709 so it's not LTSB, the folks here that make the image (I used to do that 2 decades ago with win95 anyways) they run a few remove commands before it's done building and the Store is removed along with OneDrive client.  So this is why I have needed this cloud install process no store for me.  I've yet to replicate a repo for local use (say if you didn't have the internet but needed to install ubuntu through wsl and patch it to the most recent (as local rsync copy would have.)

**Comment by fpqc** [comment]
Weird. If it's not LTSB it should work.
