### ISSUE TITLE
Running WSL distribution as a Windows service fails

### ISSUE THREAD

**Issue by Yukigaru** [Microsoft/WSL#3338]
* Windows build number: version 1803 (build 17134.112)

* What I'm doing and what's happening: 
I'm trying packing my linux server in to a distro and make it so it's automatically launches as a service in Windows. The service is installed and run, but WslRegisterDistribution fails when called from a service with "NT AUTHORITY\\System" account. In contrary, a regular app (not a service) registers the distribution and runs bash commands successfully.

Thanks!

**Comment by Biswa96** [comment]
May you share that Linux server link?

**Comment by Yukigaru** [comment]
Sorry, can't, it's under development and not open source

**Comment by benhillis** [comment]
Since distributions are per-user they must be registered from a user account, not the system account.

**Comment by Yukigaru** [comment]
Thank you! I'll close the issue then.
