### ISSUE TITLE
Error 0x80070003 when running bash

### ISSUE THREAD

**Issue by IamCarbonMan** [microsoft/WSL#3341]
* Your Windows build number:  10.0.16299.492

* What you're doing and what's happening:  Running `bash` or `C:\Windows\System32\bash.exe` results in "Error 0x80070003 Press any key to continue...". The Ubuntu 18.04 shortcut works.

* What's wrong / what should be happening instead: The Bash shell should open or at least give a more descriptive error.

**Comment by ioanmoldovan** [comment]
First of all, @IamCarbonMan you're out of date, get Redstone 4 build 17143!

**Comment by RobertdeLeeuw-IHomer** [comment]
Same issue: error 0x80070003  when starting bash.

- OS build: 17134.137



[lxcore.zip](https://github.com/Microsoft/WSL/files/2175927/lxcore.zip)

**Comment by benhillis** [comment]
I took a look at the trace and the service is failing to find a registered distribution.  Can one of you please share the output of `wslconfig.exe /list`

**Comment by therealkenc** [comment]
Closing as stale given `wslconfig.exe` is deprecated and no follow-ups were forthcoming. If the "failing to find a registered distribution" problem persists please open a new ticket and the error can be revisited.
