### ISSUE TITLE
wireless card not found on kali subsystem 

### ISSUE THREAD

**Issue by ismailelmoudni** [Microsoft/WSL#3343]
I've just intalled the KALI subsystem on WIN10 , but i can't access my wireless card on aircrack-ng , any solution please ? or I have to wait for a real update from MS ?

**Comment by shoffmeister** [comment]
aircrack-ng will want rather low-level access to your hardware (https://www.aircrack-ng.org/doku.php?id=compatibility_drivers)

WSL, by design, will not ever give you that.

Just use the native Windows version of aircrack-ng on Windows (https://www.aircrack-ng.org/downloads.html)

**Comment by therealkenc** [comment]
#2932 #1104 and friends.

> WSL, by design, will not ever give you that.

Nah I bet it could be made to [work](https://github.com/Microsoft/WSL/issues/1349#issuecomment-400936919). Just not worth the effort because [aircrack-ng](https://www.aircrack-ng.org/) for Windows.

**Comment by KYKKIS2** [comment]
Does it work now?

**Comment by patv81** [comment]
It's will never work, isn't it?
