### ISSUE TITLE
apt-get update takes forever

### ISSUE THREAD

**Issue by Naadwo** [microsoft/WSL#3345]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.112]
* What you're doing and what's happening: apt-get update
* What's wrong / what should be happening instead: First two updates are fetched quickly, operation hangs on 3rd one (on _Waiting for headers_). Finally after really long time source is ignored - but the same thing is with next ones.
* Full strace of the failing command: [gist](https://gist.github.com/Owdaan/f3063897265ee5b34641c71ed5798290)

The part while process is hanged is below (in the loop):
```
526   write(1, "0% [Waiting for headers] [Waitin"..., 46) = 46
526   select(12, [5 6 7 9 11], [], NULL, {0, 500000}) = 0 (Timeout)
526   gettimeofday({1530516107, 324585}, NULL) = 0
526   rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
526   rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
```

I've also tried to run it with option _-o Acquire::ForceIPv4=true_, but it doesn't help.
I know this is similar to #472, but I have a newver version than it is mentioned there. 
I've tried to do full reinstall (with lxrun), it didn't make any change. 
I will also add that this is on Windows Enterprise, however on older versions (10.0.15063, 10.0.16299.492), in the same domain, it works fine.

**Comment by Owdaan** [comment]
Suprisingly it helped when I've used Artifactory as cache in the middle - but it was still unstable. Finally after switching to SSL connection, apt is working stable.
