### ISSUE TITLE
Is it possible to install WSL using powershell?

### ISSUE THREAD

**Issue by thedonquixotic** [Microsoft/WSL#3346]
I'm doing a fresh install of my Windows 10 machine. 

I thought I would at least make this process less painful and write a bat file that I could automate things with. I know how to install most programs using the chocolatey package manager. I don't know however how to do something like install the Ubuntu 18 for Windows subsystem layer. Any suggestions? Is it even possible?

**Comment by Brian-Perkins** [comment]
There is a good landing page at http://aka.ms/devsetup for automated setups. See [Web Setup](https://github.com/Microsoft/windows-dev-box-setup-scripts/blob/master/dev_web.ps1) for an example involving WSL.

**Comment by thedonquixotic** [comment]
Excellent! Thank you @Brian-Perkins ! This is exactly what I needed 🤓

**Comment by thedonquixotic** [comment]
@Brian-Perkins Hey Brian, thanks for turning me towards this. It's been super awesome! BUT.... sadly as far as I can tell there is no official supported way to install WSL Ubuntu 18.04 using powershell/boxstarter. It seems that the only way of getting it is through the MS store and I can't figure out how to automate it. I mean... I don't need to automate it. I could just manually install it, but it would be cool to be able to do that.
