### ISSUE TITLE
Alt+Shift+Arrow Key doesn't work

### ISSUE THREAD

**Issue by Kimeiga** [Microsoft/WSL#3347]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.112]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Holding down Alt + Shift and pressing any arrow key doesn't send anything to the WSL command line. I was trying to select a word of text in the [Micro text editor](https://github.com/zyedidia/micro) with the AltShiftLeftArrow and AltShiftRightArrow keybindings, and nothing was happening.
  * I confirmed that I don't have Alt+Shift set to switch language keyboards in Windows.
  * I tried using Alt + Shift + Arrow Key in WSL (Bash), Cmder (running WSL Bash), Command Prompt (after entering bash via "bash" command"), and MobaXTerm (local shell).
  * I tried debugging this via Micro's own key debugger: ["raw"](https://github.com/zyedidia/micro/blob/master/runtime/help/commands.md), and I could see keys being sent when I pressed Alt + Shift + Letter Key, but when I pressed Alt + Shift + Arrow Key there was no output.
  * I also installed [xev](https://www.x.org/archive/X11R7.7/doc/man/man1/xev.1.xhtml) within WSL, via apt-get, and ran it with an X server in MobaXTerm. When I pressed Alt+Shift+Letter Key, it would register all keys individually (and when I kept holding Letter Key, it would repeat quickly, as is normal in Windows). However, when I pressed Alt+Shift+Arrow Key, again, no output.

* What's wrong / what should be happening instead:
Alt + Shift + Arrow Key should be sending some key codes to the terminal because some applications like Micro, depend on it (unless you change your keybindings to something different).

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
N/A

**Comment by Kimeiga** [comment]
Also thanks for all your hard work everyone <3 WSL allows me to use my gaming laptop for all kinds of development while still being able to do all kinds of graphically intensive operations (3D Suites, Games, Video Editing, etc).

It's a dream come true 🥇

**Comment by Kimeiga** [comment]
I actually tried to solve this by rebinding as so

Alt-Shift-Left Arrow => 
Alt-Shift-Left Arrow => 
Alt-Shift-Left Arrow =>

**Comment by Kimeiga** [comment]
I actually tried to solve this by rebinding as so

Alt-Shift-Left Arrow => Alt-Shift-H
Alt-Shift-Right Arrow => Alt-Shift-L
Alt-Shift-Up Arrow => Alt-Shift-K
Alt-Shift-Down Arrow => Alt-Shift-L

And these don't work either. When I press Alt-Shift-H, Alt-Shift-K, or Alt-Shift-J in bash, the default windows error sounds and nothing is printed. Alt-Shift-L : no error sound, nothing printed.

Within Micro, Alt-Shift-[H,K,J,L] print their respective capital letters and do nothing else. I've exhausted my knowledge of what could be going on, I'm just going to try Alt-[H,K,J,L] as my keybindings now.

Something tells me this could be a console issue, but I couldn't find any mention of this issue in WSL's Github Issues, nor Console's github issues.

SOS :)

**Comment by Kimeiga** [comment]
Here's some info on the Alt+Shift by the Micro creator

https://github.com/zyedidia/micro/issues/974#issuecomment-355390586

**Comment by Kimeiga** [comment]
I installed Micro under windows via chocolatey and tried Alt+Shift+Arrow Key detection in "raw" mode and didn't see any output. It could be an underlying Command Prompt bug. I'm just surprised there's no talk about it.

**Comment by shoffmeister** [comment]
Are you in the optimal issue tracker?

> Note that WSL distro's launch in the Windows Console (unless you have taken steps to launch a 3rd party console/terminal). Therefore, please file UI/UX related issues in the Windows Console issue tracker.

--> https://github.com/microsoft/console

**Comment by therealkenc** [comment]
Yes, better off to post this one in the console tracker. You might also try [wsltty](https://github.com/mintty/wsltty). Doing that helps isolate the terminal emulation divergence.

**Comment by Kimeiga** [comment]
If I experience the same problem in Cmder which is based on ConEmu, is it still a console issue? Thanks guys.

**Comment by therealkenc** [comment]
I just gave it a try under wsltty (as suggested,) and yeah it appears to work. So yeah, console. I also tried it on 17704 and it appears to work there too. So not only 'console', but looks like fixed-in-insider console.

**Comment by Kimeiga** [comment]
Thank you, thats fantastic! I actually just joined Microsoft Insider and updated my computer and tried to find some of the new features that came to bash last april (like copy and paste via keyboard). The new features were supposed to appear in the properties menu as options, but I couldn't find them. And Alt+Shift+Arrow Keys still don't work.

But I think that's my fault because `ver` still displays 
`Microsoft Windows [Version 10.0.17134.137]`
so I think there are more instructions I need to follow

Thanks for the research! I'll use wsltty!

**Comment by Kimeiga** [comment]
Oh my gosh. I just discovered it's just keyboard ghosting on my own computer. There's nothing wrong with console. Terribly sorry for the inconvenience!

**Comment by Kimeiga** [comment]
Doesn't appear to be keyboard ghosting. Also doesn't work in wsltty for me. I'll try console on 17704

**Comment by therealkenc** [comment]
Do try out 17704 if you can. But if you are _still_ having difficulties after installing [Insiders](https://insider.windows.com/en-us/), you will get better service over in the [console github](https://github.com/microsoft/console) because they will be more familiar with "problems with keyboard ghosting" (whatever they may be) as well as more familiar with what might or might not have been addressed between 17134 and 17704. I don't follow console very issues closely nor do I use ConEmu, MobaXterm, nor even the Micro text editor until you linked it. I can only confirm the Alt+Shift+Arrow Key sequences appear functional, for me, with my unadulterated 17704. Bonne chance.
