### ISSUE TITLE
Git ignores .gitattributes EOL settings

### ISSUE THREAD

**Issue by GPhilo** [Microsoft/WSL#3348]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.112]

[Related SO question with in-depth explanation and sample setup](https://stackoverflow.com/questions/51086499/wsl-git-eol-configuration-ignoring-gitattributes) (if necessary, I can copy the whole thing here as well)

* What you're doing and what's happening:  Attempting to configure EOL settings for `git` via `.gitattributes` fails. Git seems to ignore `.gitattributes` completely, relying instead exclusively on what is specified in the global configuration (e.g., changing `core.eol`).

* What's wrong / what should be happening instead: `git` correctly follows the EOL settings specified via attributes.

**Comment by therealkenc** [comment]
It isn't clear (to me) what might be going wrong with your setup. You might try pushing a github repo with two files, `wincrlfeol.txt` and `lxlfeol.txt`  along with your `.gitattributes`. Then provide a set of CLI steps to reproduce the problem, starting with:
```
$ git clone https://github.com/GPhilo/wsl_git_test.git
$ cd wsl_git_test
$ # ....steps
$ git add -A
```
"Steps" here might mean mucking with one of those files using [`printf(1)`](http://man7.org/linux/man-pages/man1/printf.1.html) with "`\r\n`" or `cat(1)`. Or use `dos2unix(1)` maybe. I'll take a look, but there is a high degree of probability your scenario is linux-behavior (with the usual caveat that anything is possible). WSL doesn't know you are running `git` and just follows the syscalls `git` is feeding the kernel.

**Comment by GPhilo** [comment]
Setting up the test environment I found the problem, had to do with formatting of the .gitattributes file.
Once fixed that, git works as expected
