### ISSUE TITLE
Blue screen while connected via SSH to a remote box and running Ansible

### ISSUE THREAD

**Issue by evaryont** [Microsoft/WSL#3350]
* Your Windows build number:  `Microsoft Windows [Version 10.0.17134.112]`, uname: `Linux XYZ123-DELL-M4800 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux`

* What you're doing and what's happening: Running Ansible and OpenSSH in Ubuntu 16.04.4, managing my company's systems.

* What's wrong / what should be happening instead: Not a BSOD. But it hasn't happened before, this is the first time it's ever happened to me. I don't do very odd things in the WSL environment -- I use it since I'm simply more comfortable in the Linux CLI with Zsh, Ruby/Python, and (neo)vim.

I'll be submitting the dump via email, per the instructions. *Edit*: Sent.

**Comment by shoffmeister** [comment]
Is that the same root cause / trigger as in #3331 ?

**Comment by therealkenc** [comment]
Yeah dupe for sure. Thanks for the ref.
