### ISSUE TITLE
Unable to Mount Remote Share via drvfs if FQDN is used

### ISSUE THREAD

**Issue by x86txt** [microsoft/WSL#3351]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17134.137

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

mount -t drvfs '\\\hyperv02.mylocal.lan\share' /media/hyperv02/ = doesn't work and returns the following error:

mount: wrong fs type, bad option, bad superblock on \\\hyperv02.mylocal.lan\share,
       missing codepage or helper program, or other error

However, if you shorten it to the host/netbios name, it works:

mount -t drvfs '\\\hyperv02\share' /media/hyperv02/

* What's wrong / what should be happening instead:
You cannot mount a drvfs remote share using a FQDN. You should be able to.

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
