### ISSUE TITLE
Ubuntu on WSL gets corrupted - WslRegisterDistribution failed with error: 0x800700b7

### ISSUE THREAD

**Issue by icex** [Microsoft/WSL#3352]
* Your Windows build number: Microsoft Windows [Version 10.0.17134.137]

* What you're doing and what's happening:  
Sometimes, after a reboot, when I open Ubuntu I receive the error below and the only solution so far is to reinstall it clean or never reboot(ever). Same issue happened on 18.04 and on 16.04 and I had to reinstall, loosing all my config.

* What's wrong / what should be happening instead:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800700b7
The distribution installation has become corrupted.
Please select Reset from App Settings or uninstall and reinstall the app.
Error: 0x800700b7 Cannot create a file when that file already exists.

Press any key to continue...
```

**Comment by icex** [comment]
PS: This happened on my PC and on my Laptop, both after a reboot.

**Comment by Voskrese** [comment]
https://github.com/Microsoft/WSL/issues/634#issuecomment-230862990

```
sc query LxssManager
sc stop LxssManager
sc start LxssManager
```

**Comment by icex** [comment]
Thanks. Restarting LxssManager solved it.

**Comment by nick-walt** [comment]
After running `wslconfig /unregister Ubuntu-18.04` I received the error that started this thread. Restarting LxssManager service did not resolve it. However, uninstalling the instance did resolve it.

**Comment by KenLast** [comment]
Thank you.  I ran into the same thing and restarting the service as you describe fixed it.

**Comment by saidfagan** [comment]
I get this error on both Ubuntu and OpenSuse. Restarting LxssManager solves it. But when I restart my Windows problem happens again. Any ideas?

**Comment by icex** [comment]
I had a scheduled task to start some services (using a Vbs script) and I think I had checked run as administrator. I guess that was my cause for this. I could be wrong, but check that if you’re running at startup.

**Comment by NicholasIoanJones** [comment]
Restarting LxssManager solved it for me too

**Comment by caal-15** [comment]
Restarting the Manager does resolve it, but it happens everytime I start the PC again :(

**Comment by kj-joseph** [comment]
@caal-15: I found this very helpful: https://github.com/Microsoft/WSL/issues/2576#issuecomment-456386629

**Comment by caal-15** [comment]
@kj-joseph Thank you!, that was actually really helpful :)

**Comment by Skippidar** [comment]
Same error, but https://github.com/Microsoft/WSL/issues/3352#issuecomment-402673907 doesnt help

**Comment by epogrebnyak** [comment]
For those looking how to restarting LxssManager, here is [an instruction](https://superuser.com/questions/1319478/rebooting-wsl-in-windows-1803).

**Comment by objt-ba** [comment]
In my case, stopping the LxssManager takes ages, and after stopping it, it won't start again.
After a full system reboot everything works again though.

Now, what I have found, is that if an application displays an exception while being connected through an in-line command. (i.e. `ubuntu1604 <command>`) this can sometimes hang the system. My guess is that this command never comes to an end, and as a result there is no way to use that instance anymore. ... until a full system reboot in my case.

**Comment by JaredOchoa** [comment]
I cant restart LxssManager, it's stop and when I try to run it, console print ERROR 1058

**Comment by vseal001** [comment]
I found a better way to deal it, first delete the files, then delete reg, then reinstall.
Finaly： its work

**Comment by CiaranWelsh** [comment]
> I found a better way to deal it, first delete the files, then delete reg, then reinstall.
> Finaly： its work

Could you be more specific so others can try and replicate your solution?

**Comment by ThrashAbaddon** [comment]
This can happen if Kasperski is installed.

**Comment by vjkaran** [comment]
> This can happen if Kasperski is installed.

Did stopping the Kasperski solve it for you @ThrashAbaddon  ?

**Comment by juanccamachob94** [comment]
I came here because of this error

`error 0x8007010b al iniciar wsl.exe -d Ubuntu-18.04`  (`C:/mnt/c/`)

It seems that they updated some features of the terminal and my home path `/mnt/c/Users/Developer/Documents/` no longer works, but making the following change works, and better, because I can access subdirectories that before the home path did not allow me.
![image](https://user-images.githubusercontent.com/42450812/120101963-774a6800-c10e-11eb-844b-585cf34ea3ae.png)
(this picture belongs to terminal configuration)


I leave it here in case it helps someone

**Comment by LiLejia** [comment]
Fore those of you still in trouble.
Download rootfs and import manually could at least work.
https://gist.github.com/djfdyuruiry/61e32fb69645bd2618182ee17373d068

**Comment by Usman-Click** [comment]
Well... i'm here in 2024

in my case it got solved after i reset the distribution

**these are the steps :**

- Open Settings:
Press Windows + I to open the Settings app.
Navigate to Apps:

- Go to Apps > Apps & features.
Find Your Linux Distribution:

- Scroll through the list of installed apps and find your Linux distribution (e.g., Ubuntu, Debian).
Reset the App:

- Click on the distribution and then click Advanced options.
Scroll down and click Reset.

re-open your distribution and ta-da i'll work In shaa Allah

**Comment by markbaydoun** [comment]
If anyone runs into this, the solution in https://github.com/microsoft/WSL/issues/3352#issuecomment-402673907 didn't work for me because `LxssManager` seemed to not be present in my PC and I wasn't able to install it.

I was able to fix it with the solution in this SU thread https://superuser.com/questions/1725594/windows-lxssmanager-is-missing-from-services-msc

What worked for me was: in Powershell, run `Restart-Service WSLService`
