### ISSUE TITLE
Cannot update apt-get -Failed to fetch Connection failed [IP: 91.189.88.149 80]

### ISSUE THREAD

**Issue by frankfuu** [Microsoft/WSL#3353]
I'm running Ubuntu on WSL and wish to update my apt-get via `sudo apt-get update` but came across this error.
```
Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/binary-amd64/Packages  Connection failed [IP: 91.189.88.149 80]
```

Running a `lsb_release -a` shows
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```
My Windows system
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
Hotfix(s):                     4 Hotfix(s) Installed.
                                       [01]: KB2693643
                                       [02]: KB4103729
                                       [03]: KB4287903
                                       [04]: KB4284835
```

Here is the complete log

```
frank@WIN-D7471GB:~$ sudo apt-get update
[sudo] password for frank:
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,201 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main Translation-en [568 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [8,344 B]
Get:8 http://archive.ubuntu.com/ubuntu xenial/restricted Translation-en [2,908 B]
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:10 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Get:11 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
32% [Waiting for headers]
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:10 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en
Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Get:10 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en [6,256 kB]
Err:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
  Connection failed [IP: 91.189.88.149 80]
Fetched 247 kB in 2min 44s (1,504 B/s)
Reading package lists... Done
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/binary-amd64/Packages  Connection failed [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I'm not sure if this is the best place to post my issue if not, please provide suggestions.

Thanks.

**Comment by shoffmeister** [comment]
How often did you try to make sure that this is not a transient problem in connecting to 91.189.88.149?

Are you located in an environment - anti-virus tool / proxy / enterprise network / political zone etc - which would tend to introduce interesting behaviour into an otherwise plain and simple TCP/IP connection to an IP address which according to geo-coding to be located in Scotland (at least for me and with all the caveats that apply to geo-coding)?

If you are located in such an environment - have you tried outside of that environment?

**Comment by frankfuu** [comment]
hi @shoffmeister ,

Strangely enough, I jumped onto a different machine on a different WAN network, with the same windows build and it worked fine. So it could be related to my company network.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
Hotfix(s):                    3 Hotfix(s) Installed.
                                  [01]: KB2693643
                                  [02]: KB4287903
                                  [03]: KB4284835
```

**Comment by howels** [comment]
Same problem here. I can put the URL in a browser on the Windows host and the connection works. I can update my Linux laptop and it works. I cannot run "apt update" or curl that URL from within WSL. Yay Windows!

**Comment by jarkelen** [comment]
Same here, using the IP address `91.189.88.41` in the browser works, but when doing a `sudo apt update` gives `Connection failed [IP: 91.189.88.41 80]`.

**Comment by Mizumaky** [comment]
Had a similiar problem of failing all/some connections which prevented me to apt-get install gcc.
Finally solved by looking at forums and trying everything i could:
- editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4."
- looking at the port behind ip adresses of failed connections and trying disabling network protection for the specified port in the antivirus settings (solved only for most connections, not all, even on that port)
- completely turning off Kaspersky Free anitivirus
- changing from connection through my dormitory's internet to a wifi connection i shared from my phone
- (trying apt-get update first)

I dunno if all or only some of this helped, but somehow i got apt-get install gcc to download the rest and work.

**Comment by Nerdsie** [comment]
> 
> 
> Had a similiar problem of failing all/some connections which prevented me to apt-get install gcc.
> Finally solved by looking at forums and trying everything i could:
> 
>     * editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4."
> 
>     * looking at the port behind ip adresses of failed connections and trying disabling network protection for the specified port in the antivirus settings (solved only for most connections, not all, even on that port)
> 
>     * completely turning off Kaspersky Free anitivirus
> 
>     * changing from connection through my dormitory's internet to a wifi connection i shared from my phone
> 
>     * (trying apt-get update first)
> 
> 
> I dunno if all or only some of this helped, but somehow i got apt-get install gcc to download the rest and work.

Completely closing Kaspersky fixed everything for me

**Comment by chrisls121** [comment]
Same here, "Pause Protection" does not work. Had to stop the Kaspersky service and it started working.

**Comment by sofsip** [comment]
I had the same issue with Zone Alarm Firewall - Snoozing doesn't work. it has to be completely stopped.

**Comment by igor-ye** [comment]
> Completely closing Kaspersky fixed everything for me

Also you can just temporarily switch off Kaspersky Free firewall for both 80 and 443 ports - in Настройки (Settings) -> Дополнительно (Additional?) -> Сеть (Network) -> Контролируемые порты (Protected network ports?) - custom network ports list in option Контролировать только выбранные (Protect only selected?). After successful apt-get update - switch them on again.

P.S. This also helped me with failing Ivy dependencies update in Scala sbt build.

**Comment by SonyStone** [comment]
> Had a similiar problem of failing all/some connections which prevented me to apt-get install gcc.
> Finally solved by looking at forums and trying everything i could:
> 
> * editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4."
> * looking at the port behind ip adresses of failed connections and trying disabling network protection for the specified port in the antivirus settings (solved only for most connections, not all, even on that port)
> * completely turning off Kaspersky Free anitivirus
> * changing from connection through my dormitory's internet to a wifi connection i shared from my phone
> * (trying apt-get update first)
> 
> I dunno if all or only some of this helped, but somehow i got apt-get install gcc to download the rest and work.

only `sudo apt-get update` was enough for me.

**Comment by jasonzhn** [comment]
change your network, and have a try.

**Comment by herlianzhang** [comment]
try to run that command "sudo apt-get update" in tty, press ctrl + alt + f3 or f4, then run the command

**Comment by z3nth10n** [comment]
Avast is making troubles... I disabled it and this worked perfectly

**Comment by Dwerg01** [comment]
> Had a similiar problem of failing all/some connections which prevented me to apt-get install gcc.
> Finally solved by looking at forums and trying everything i could:
> 
> * editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4."
> * looking at the port behind ip adresses of failed connections and trying disabling network protection for the specified port in the antivirus settings (solved only for most connections, not all, even on that port)
> * completely turning off Kaspersky Free anitivirus
> * changing from connection through my dormitory's internet to a wifi connection i shared from my phone
> * (trying apt-get update first)
> 
> I dunno if all or only some of this helped, but somehow i got apt-get install gcc to download the rest and work.

Champ! I only changed one thing to get it working. Added "nameserver 8.8.8.8" to /etc/resolve.conf

**Comment by vncastanheira** [comment]
> 
> 
> Had a similiar problem of failing all/some connections which prevented me to apt-get install gcc.
> Finally solved by looking at forums and trying everything i could:
> 
>     * editing /etc/resolv.conf and leaving only line "nameserver 8.8.4.4."
> 
>     * looking at the port behind ip adresses of failed connections and trying disabling network protection for the specified port in the antivirus settings (solved only for most connections, not all, even on that port)
> 
>     * completely turning off Kaspersky Free anitivirus
> 
>     * changing from connection through my dormitory's internet to a wifi connection i shared from my phone
> 
>     * (trying apt-get update first)
> 
> 
> I dunno if all or only some of this helped, but somehow i got apt-get install gcc to download the rest and work.

For some reason with WSL2 I have to keep redoing this because `resolve.conf` resets at the default value each time I open a new instance.

Using WSL2 on Windows 10 version 2004 with Ubuntu 20.04.

**Comment by holzkohlengrill** [comment]
`do-release-upgrade` solved the issue for me.

**Comment by khairaf** [comment]
> * changing from connection through my dormitory's internet to a wifi connection i shared from my phone

why only this way works for me?  everything else doesn't work

**Comment by verdian123** [comment]
same problem here, solved by using VPN

**Comment by PeterFlorian** [comment]
You have to configure the proxy.
Create a file named `/etc/apt/apt.conf` with this content (use your proxy settings!):
`Acquire::http::proxy "http://proxy:8080/";`
`Acquire::https::proxy "https://proxy:8080/";`

**Comment by makspundyk** [comment]
You should run the update command:
`sudo apt-get update`

I faced this issue at the very beginning, after system installation.
It helped.

**Comment by lucadonnoh** [comment]
`sudo apt-get update` solved my issue

**Comment by acchen73** [comment]
```
root@acchen:/etc# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 3s (123 kB/s)
Reading package lists... Done
```
Is apt-get update working? But I still got a Connection failed error when I install packages.

**Comment by xue-fc** [comment]
> You have to configure the proxy. Create a file named `/etc/apt/apt.conf` with this content (use your proxy settings!): `Acquire::http::proxy "http://proxy:8080/";` `Acquire::https::proxy "https://proxy:8080/";`

This method works! Thank you!

**Comment by Echo64** [comment]
> You have to configure the proxy. Create a file named `/etc/apt/apt.conf` with this content (use your proxy settings!): `Acquire::http::proxy "http://proxy:8080/";` `Acquire::https::proxy "https://proxy:8080/";`

Wow hours of troubleshooting and somehow I totally missed this, using the `export proxy_http` for a single use or adding it to the .bashrc file didn't work but this did! thanks!

**Comment by nilknow** [comment]
I changed the ubuntu repository, new repository works.

**Comment by LQTam** [comment]
> You have to configure the proxy. Create a file named `/etc/apt/apt.conf` with this content (use your proxy settings!): `Acquire::http::proxy "http://proxy:8080/";` `Acquire::https::proxy "https://proxy:8080/";`

thanks, This work for me.
For anyone using WSL on a machine that connects to the internet via a Proxy

**Comment by PriyankaAppMath** [comment]
I have facing same kind of problem in ubuntu 23.10

sudo apt-get update
Get:1 https://download.docker.com/linux/ubuntu mantic InRelease [48.8 kB]
Ign:2 http://archive.canonical.com/ubuntu mantic InRelease                     
Hit:3 http://archive.ubuntu.com/ubuntu mantic InRelease                        
Err:4 http://archive.canonical.com/ubuntu mantic Release
  404  Not Found [IP: **************]
Hit:5 http://archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu mantic-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Reading package lists... Done
E: The repository 'http://archive.canonical.com/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Tried with do-release-upgrade. But no help.
