### ISSUE TITLE
dist-upgrade isn't present in "Ubuntu 18.04" WSL

### ISSUE THREAD

**Issue by linuxct** [Microsoft/WSL#3354]
* Your Windows build number:  10.0.17134.112

* What you're doing and what's happening:  When I run dist-upgrade, reports command isn't found

* What's wrong / what should be happening instead: The command should run the binary in question and let me upgrade to the latest Ubuntu version, whether I've set up my WSL to receive beta versions from Ubuntu or not.

* Strace of the failing command, if applicable:  N/A

**Comment by shoffmeister** [comment]
Works for me, see below. Perhaps you could provide some more steps for reproduction?

```
myself@DESKTOP-205QDD6:~$ sudo apt dist-upgrade
[sudo] password for myself:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  ebtables
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/79.9 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

**Comment by linuxct** [comment]
You're right, I was missing `apt`.
