### ISSUE TITLE
Error 0x800703fa after locale change

### ISSUE THREAD

**Issue by kpengboy** [Microsoft/WSL#3357]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  10.0.17134.112

* What you're doing and what's happening: I installed the Debian WSL distribution with the Windows language set to Chinese (China). Upon switching the language back to English (US), running debian.exe attempts to reinstall the distribution and fails with HRESULT 0x800703fa.

   ```
   PS> debian
   Installing, this may take a few minutes...
   Installation Failed!
   Error: 0x800703fa
   Press any key to continue...
   ```

* What's wrong / what should be happening instead: debian.exe should launch the existing installation.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by kpengboy** [comment]
Hmm...it seems to work now after no change. I guess it takes a while for locale changes to propagate?

**Comment by benhillis** [comment]
This is a duplicate.
