### ISSUE TITLE
Cannot build vue app for production -- webpack gets into endless loop

### ISSUE THREAD

**Issue by qodfathr** [Microsoft/WSL#3360]
* Your Windows build number:  10.0.17692.1004

* What you're doing and what's happening:  Trying to build a node Vue app for production.

* What's wrong / what should be happening instead: It should build the app. Instead, build runs forever.

From a clean install of Ubuntu/WSL,

Install nvm, node v8, and @vue/cli

node -v : 8.11.3 (problem also happens with v9 and v10, btw)
npm -v: 5.6.0
vue -V : 3.0.0-rc.3

use `vue create` to create a sample app with defaults.

`npm run build` to build the project for production

Observe that the build never finished, and a node process is consuming 100% of a core.

What appears to be happening is, within the running of webpack as part of the compile, a call from **native back to node** for managing async callbacks/promises isn't doing anything. In particular, in `async_hooks.js`, the function `emitHookFactory` will be called over and over again with the same `asyncId`, but for that particular `asyncId` it does not do anything -- seemingly leaving it on the list of callbacks yet to be resolved. Rinse and repeat.

This behavior is not observed on CentOS (in a Hyper-V VM) with the exact same project and same versions of node/npm/vue.

**Comment by Alternate-Egoist** [comment]
Where do you installed node from ? apt sources ubuntu or apt from sources node packages

**Comment by qodfathr** [comment]
I installed `nvm` via
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
```
and then node via `nvm` with
```
nvm install node v8
```
I'm not sure where `nvm` gets `node` from, though.

**Comment by therealkenc** [comment]
> Your Windows build number: 10.0.17692.1004

#3191. Try [17677](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17704)

**Comment by Alternate-Egoist** [comment]
Try installed node from here, then reinstall vue https://nodejs.org/en/download/package-manager/

**Comment by qodfathr** [comment]
I agree this was likely just a dupe of #3191. I upgraded to 10.0.17711.1000 and the problem immediately went away without any additional remediation.

Closing as dupe.
