### ISSUE TITLE
In ubuntu on WSL, network interfaces not correctly configured for link-local ipv6 addresses

### ISSUE THREAD

**Issue by leifurhauks** [Microsoft/WSL#3361]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.371]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I'm on a DHCP network that doesn't assign me an IPv6 address. In ubuntu, I find that link-local IPv6 addresses are configured as global, as seen in the following output from `ip addr`:
```
3: eth4: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether 9c:eb:e8:49:b3:59
    inet 172.16.32.65/24 brd 172.16.32.255 scope global dynamic
       valid_lft 609476sec preferred_lft 609476sec
    inet6 fe80::8874:dc55:3b36:674f/64 scope global dynamic
       valid_lft forever preferred_lft forever
```

* What's wrong / what should be happening instead:
`fe80::8874:dc55:3b36:674f/64` is a [link-local](https://en.wikipedia.org/wiki/Link-local_address#IPv6) address and shouldn't be configured with scope global. I believe this is causing me various network issues (including occasional `IN6_IS_ADDR_V4MAPPED` errors).

I am aware that I can disable IPv6 in Windows as a workaround, but I believe the above behavior is a bug.

**Comment by Brian-Perkins** [comment]
This should be better in Insider Build [17723](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17723-fast).
