### ISSUE TITLE
Bash.exe fails to start

### ISSUE THREAD

**Issue by xkjyeah** [Microsoft/WSL#3363]
This has happened twice to me, once on my work laptop and once on my personal laptop

* Your Windows build number:  Microsoft Windows [Version 10.0.17134.112]

* What you're doing and what's happening:  Tried to start bash. The command hangs there with no output.
![image](https://user-images.githubusercontent.com/2659143/42417484-f82f09e0-82bd-11e8-9d27-1e07df80057f.png)

* What's wrong / what should be happening instead: Bash.exe should start.

* Strace of the failing command, if applicable:  (n.a. the entire subsystem fails to start)

(Question: where should I upload the .etl files?)

**Comment by xkjyeah** [comment]
Starting bash directly gives zero output at all (it has been this way for minutes)
![image](https://user-images.githubusercontent.com/2659143/42417500-57dc091a-82be-11e8-8d25-7524870e0997.png)

Uninstallation is also unresponsive:

![image](https://user-images.githubusercontent.com/2659143/42417503-6fe2404c-82be-11e8-8b5b-68f77201607a.png)

(at this point, it doesn't even respond to a Ctrl+C)

ETL files below:

[Downloads.zip](https://github.com/Microsoft/WSL/files/2173413/Downloads.zip)

**Comment by rms46** [comment]
metoo!
It does not hang, but it took 6 minutes until I have got a bash prompt.
Another 2 minutes until for the "ps ax" output.
`
rms46@YOGA920:~$ ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /init ro
   29 tty1     Ss     0:00 /init ro
   30 tty1     S      0:00 -bash
   40 tty1     R      0:00 ps ax

`

**Comment by rms46** [comment]
Somehow, it just went back to normal...
No clue why...  The only thing I did was closing Malwarebyte

**Comment by xkjyeah** [comment]
Nope, my problem is far worse. doesn't resolve itself even after a reboot, can't uninstall WSL either. My only AV is Windows defender

**Comment by benhillis** [comment]
@xkjyeah - Unfortunately I am not seeing any events in your trace apart from instance create / end events in the service.  It looks like you're using the old legacy distribution, could you try running Ubuntu from the store?

**Comment by xkjyeah** [comment]
Hmmm it seems to have resolved itself after a Windows update.
