### ISSUE TITLE
VS file access errors on files that were created using git from WSL

### ISSUE THREAD

**Issue by dauthleikr** [Microsoft/WSL#3364]
When cloning a repo using git from WSL, Visual Studio does not find project files (or at least says so):
![vs error](https://user-images.githubusercontent.com/5332935/42420302-f06cba8a-82c3-11e8-9736-94320f151c90.PNG)
Needless to say, the files are actually there and can be opened from within visual studio. Only the build fails. The errors are shown when building or opening the files in question.
When cloning using git (same version) from CMD, everything works.

Repo that can be used to reproduce this issue: [https://github.com/dauthleikr/NetLoader](https://github.com/dauthleikr/NetLoader)

**Use this exact command to reproduce:**
> git clone https://github.com/dauthleikr/NetLoader

If you tell git to clone into an already existing directory that was created by windows, the bug cannot be reproduced!

Visual studio version:
[visualstudio.txt](https://github.com/Microsoft/WSL/files/2173768/visualstudio.txt)

Windows build number: Microsoft Windows [Version 10.0.17134.137]
WSL uname -a:  Linux NEW 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shoffmeister** [comment]
You seem to be encountering https://blogs.msdn.microsoft.com/commandline/2018/06/14/improved-per-directory-case-sensitivity-support-in-wsl/ which has been discussed earlier, e.g. #3356.

Both the blog entry and the discussion on #3356 would seem to contain suggestions for remedy, and an outlook into the future.

**Comment by dauthleikr** [comment]
@shoffmeister That is very likely. I did not recognize this was a case issue.
I'll use the "fix" from [https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/#comment-62645](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/#comment-62645) and close this because it's duplicate. Thank you!
