### ISSUE TITLE
Django runserver woes

### ISSUE THREAD

**Issue by varunarora** [Microsoft/WSL#3366]
Hi there!

Thanks for making Ubuntu on Windows a reality. I have switched from Native Ubuntu to Native Windows since late 2017 and am generally happy. The past 2 months I've wanted to move to Mac OS because of small quirks with WSL, the most important of which is below:

**The bearable stuff**: I use my computer to develop on Django. When running Django's 1.8.11 hot-reload `runserver` for more than a couple of hours without actively coding, the memory seems to crash - causing graphics to crash and often the computer to restart. Allowing the computer to sleep as a default behavior causes something similar. So I HAVE TO shut the `runserver` in order to hope that my computer won't crash when I step out.

**The unbearable stuff**: The best thing in the world about Django is it listening to your filesystem saves and instantly reloading the server. This takes 5-20 seconds, when on most computers of similar specs on Ubuntu, this should take max 2-3 seconds. I also happen to use webpack which also listens on such disk changes, but it rebuilds within 1-2 seconds always.

Can't see anyone else complaining about this on Issues or forums - how should I begin to resolve this?

------------------------------------

Microsoft Windows [Version 10.0.17134.112]
Dell 13 7359
WSL: 5/24/2018 install date; can't figure out version easily, but this seems to be the latest

**Comment by varunarora** [comment]
And turns out Docker isn't an option because I am on Windows Home.

**Comment by therealkenc** [comment]
You've got multiple issues in one submissions. First sounds like an OOM problem with "Django" (Jamie Foxx does not do Franco Nero justice). For that, please open a new issue following [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md); mostly a set of CLI repro steps from clean install, probably with a git clone of a project that will OOM if left to it's own devices. An `strace` won't be much applicable here, just the repro.

There is also implied a problem when the computer goes to sleep (contrast OOM). #2176 #2519 and friends. But first you'll want to eliminate the OOM variable.

For the "unbearable stuff" the landing zone is #873 with a nod to #981 and #2626.

**Comment by varunarora** [comment]
@therealkenc Super valid, thank you for being so prompt.
