### ISSUE TITLE
VSCode is in a mess.

### ISSUE THREAD

**Issue by problem233** [Microsoft/WSL#3372]
* Your Windows build number:  `Microsoft Windows [Version 10.0.17711.1000]` (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I'm running `code` in an ArchLinux installed with [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline/).

![snipaste_2018-07-11_17-13-43](https://user-images.githubusercontent.com/13145126/42562242-cafa679a-852d-11e8-9ef2-a0a8b4bd0521.png)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable: When I strace it, it always runs normally except it's very slow.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Please see [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). You have not provided CLI repro steps in a supported WSL distribution. Probably [reddit](https://www.reddit.com/r/bashonubuntuonwindows/) would be the best place to discuss. Or possibly the LxRunOffline [tracker](https://github.com/DDoSolitary/LxRunOffline/issues).

**Comment by 12101111** [comment]
This is a issue about Vxsrv. You can try mobaXterm
![default](https://user-images.githubusercontent.com/8438475/42981327-2b86388c-8c0e-11e8-8aa4-ef67b74de492.png)
