### ISSUE TITLE
wslpath -u does not handle %USERPROFILE%

### ISSUE THREAD

**Issue by rigarash** [Microsoft/WSL#3375]
wslpath does not handle special folders like %USERPROFILE%.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.165]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
$ wslpath -u %USERPROFILE%
wslpath: %USERPROFILE%: Invalid argument

* What's wrong / what should be happening instead:
$ wslpath -u %USERPROFILE%
/mnt/c/Users/rigarash

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
not applicable

**Comment by therealkenc** [comment]
[this](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/)
```
C:\> set WSLENV=USERPROFILE
C:\> wsl.exe
C:\>wsl.exe ~
$ echo $USERPROFILE
C:\Users\ken
$ wslpath -u "$USERPROFILE"
/mnt/c/Users/ken
```

**Comment by Biswa96** [comment]
At the launch time wsl.exe and bash.exe finds `%PATH%` variable only. Then it passes only that `%PATH%` variable in the COM method with which Linux world comes to light. So if you want to add extra variable you have to use `WSLENV` which is appended to that PATH variable at runtime. Alternatively, add that `%USERPROFILE%` value in `%PATH%`. Like, `setx /m PATH C:\Users\rigarash`.

**Comment by Biswa96** [comment]
At the launch time wsl.exe and bash.exe finds `%PATH%` variable only. Then it passes only that `%PATH%` variable as a parameter in the LxssInstance COM method -- with which Linux world comes to light. So if you want to add extra variable you have to use `WSLENV` which is appended to that PATH variable at runtime. Alternatively, add that `%USERPROFILE%` value in `%PATH%`. Like, `setx /m PATH C:\Users\rigarash`.

**Comment by therealkenc** [comment]
> so commonly used that it would be nice to use such folders without special treatment.

It wold be "nice" if _all variables_ were passed by fiat, exactly like `execve()`, and `WSLENV` wasn't a thing. But I digress. Glad it worked out for you.

**Comment by Biswa96** [comment]
@therealkenc Do you know how to patch executables in Windows easily? I've a procedure with IDA. Patch the `%PATH%` string in bash.exe or wsl.exe and it will work.

**Comment by rigarash** [comment]
@therealkenc 
I understand that I can use WSLENV if I want to use environment variables on the Windows side.
However, as long as wslpath claims to translate paths between Windows side  and WSL side, I believe that it would be natural to assume that wslpath can translate special folders (%USERPROFILE%, %APPDATA%, etc.) without any other settings.
I only want to use %USERPROFILE% or other special folders as arguments to wslpath.

I want to use wslpath as follows:
```
$ cp $(wslpath -u "%USERPROFILE%test") .
```
