### ISSUE TITLE
Bash.exe doesn't work.

### ISSUE THREAD

**Issue by donnol** [Microsoft/WSL#3381]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.  Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [版本 10.0.17134.165]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I open bash.exe, but it doesn't work, like this.
![wsl_bash_error](https://user-images.githubusercontent.com/5707519/42735181-3662753e-8882-11e8-890c-fece909b9f2b.png)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by donnol** [comment]
On my other PC, its version is Microsoft Windows [版本 10.0.17134.165] too.But it can work after this
![bash-error](https://user-images.githubusercontent.com/5707519/42740498-d92b879e-88da-11e8-9492-00b1daa5b880.png)

**Comment by donnol** [comment]
After I install the ubuntu18.04 in Microsoft Store and restart the computer, it works again.

**Comment by benhillis** [comment]
If you're still hitting this issue could you please collect a trace:

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by benhillis** [comment]
@Malgalad - I received your traces, thanks for that.  Looking at what's happening it looks like zsh is spending a lot of time doing something, I'm not sure what.  Would it be possible for you to try switching your default shell to /bin/bash and seeing if that resolves the issue?

**Comment by Malgalad** [comment]
@benhillis sorry for late response - yes, switching back to `bash` did the trick.
