### ISSUE TITLE
Parallel make fails. make -j<any number above 1>

### ISSUE THREAD

**Issue by Nadav-Ruskin** [Microsoft/WSL#3384]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.165]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Trying to build a project using a parallel make (`make -j<any number above 1>`).

* What's wrong:
I get random errors. It happens to my colleague too.

* What should be happening instead:
I should compile just as well as it would using `make -j1`

* strace
https://gist.github.com/Nadav-Ruskin/7b348a55c0d5a003bec51541e2781dd5
https://gist.github.com/Nadav-Ruskin/3ef18e5f4152a62d08bb39fa653edc95

Related: #2606 #2448

**Comment by therealkenc** [comment]
You've got `clone()`s in there but the `strace` log doesn't appear to be threaded. Use `strace -f -o make.strace make -j2`. Also repro steps. Parallel `make` "works" in WSL as it goes: `make -j[n]` just spawns multiple processes, and folks use `make -j[n]` pretty regularly. The cause of the fail is going to depend on what you're `make`ing. A repro would also illuminate details such as whether you are in `/mnt/c` or `/home`, which sometimes matters for some scenarios.

**Comment by onomatopellan** [comment]
Ok, this is confusing. You are using dockross, right? Which uses "Docker for Windows" which uses Hyper-V which uses a real Lilnux Kernel.
The only thing from WSL you are using is the Docker client but everything that comes after "bash -c" like make, cmake...etc is executed inside the container which again it uses a real Linux kernel and has nothing to do with WSL.

You should try the Docker windows client (Docker command line) first and see if the same problem happens. In that case a better place to ask would be on [docker-ce/moby issues tracker](https://github.com/moby/moby/issues?q=is%3Aissue+windows+label%3Aplatform%2Fwindows+sort%3Aupdated-desc).

**Comment by Nadav-Ruskin** [comment]
I'm not sure what you mean by "repro". If some open source example had this problem someone would have said something by now (see #2606 and #2448).
I've encountered this bug only in complicated projects thus far, I'm not currently sure how to replicate it with a simple or opensource example.
Indeed it seems to happen only when I use docker, but I encounter it only on Windows machines. I'm not sure which is at fault. I suppose I'll open a bug on docker's issue tracker, thank you for the tip.

Attached is what is hopefully a proper trace. It is too large for gisthub.

[strace.tar.gz](https://github.com/Microsoft/WSL/files/2216887/strace.tar.gz)

**Comment by onomatopellan** [comment]
repro is the steps you need to do in order to replicate your problem. (three dots to hide propietary info)
For example this repro:
`sudo apt update && sudo apt upgrade -y`
`sudo apt install build-essential`
`git clone ...`
`make -j9 ...`
would be a WSL issue. 

But this one:
`sudo apt update && sudo apt upgrade -y`
`sudo apt install docker.io`
`docker run --rm ... bash -c "make -j9" `
would be a Docker for Windows issue.

Your last strace seems called inside a container but repro steps would clean any doubt.

**Comment by Nadav-Ruskin** [comment]
Like I said, exact reproduction would be problematic since I'm only encountering it while trying to compile proprietary sources. I am using a container, `linux-armv7` from dockcross in this example, however it happens inside every container I've tried.

**Comment by onomatopellan** [comment]
Then `make -j9` happens inside the container. WSL is not truly involved since running Docker Linux containers on Windows 10 is achieved technically by running a minimal Linux VM using Hyper-V.
The Docker installed in WSL is just the client application that tells the Docker for Windows engine to create the container and execute `make -j9` inside.

You should indicate that at the moby thread.

**Comment by Nadav-Ruskin** [comment]
Thanks for the info, I'm not proficient in the inner workings of WSL.

**Comment by therealkenc** [comment]
> Indeed it seems to happen only when I use docker, but I encounter it only on Windows machines
> I suppose I'll open a bug on docker's issue tracker, thank you for the tip.

If you do, use the _Windows_ docker client and take WSL out of the equation, or you'll almost certainly get punted back here. You said you only encounter "it" (where "it" is "I get random errors") on Windows machines. But if you are using Docker you aren't on a "Widows machine" anymore (that's kind of the point of using Docker). You're on a virtual Linux machine. You still haven't stated the mode of failure (`EINVAL` like #2448?) but at this point we're sort of past that. I looked at the `strace` log but it just indicates `Makefile:162: recipe for target [failed]` without much clue (that I could see) where it might have gone south. Without a set of repro steps to watch it fail, there isn't enough information to investigate further.
