### ISSUE TITLE
"bash.exe -c <cmd>" does not exit correctly when launched using CreateProcess() with pipe redirection

### ISSUE THREAD

**Issue by rdmello** [Microsoft/WSL#3389]
**Background information:**
* Windows build number: Microsoft Windows [Version 10.0.16299.492]

* What you're doing and what's happening:  When launching a `bash.exe` process using the Windows `CreateProcess` function, the exit code of the process is `259` (corresponding to `STILL_ACTIVE`) even though the output of the `bash.exe` command has already been read. 

For example, a process created to run `bash.exe -c "date"` only exits after an additional character is written to the `stdin` pipe of the process. I have attached a minimal C++ code in `Main.cpp` which reproduces this issue using the Windows APIs: [CreateProcess_WSL_repro.zip](https://github.com/Microsoft/WSL/files/2206442/CreateProcess_WSL_repro.zip)

This is surprising since most other non-interactive command-line utilities (like `net.exe`) on Windows will provide exit code `0` after output is generated.

* What's wrong / what should be happening instead: The `bash.exe -c "date"` process is currently providing exit code `259` when used with `CreateProcess` pipe redirection, but it should instead provide exit code `0` after executing the command.

* Strace of the failing command, if applicable:  not applicable; this issue seems to be occurring outside of the Linux userspace (in WSL/`CreateProcess` pipe interaction)

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs): This doesn't seem to be a WSL launch issue either, but I can try and get these logs if it would help.

**Comment by onomatopellan** [comment]
>Version 10.0.16299.492

If you read the [release notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17017) there have been related issues and most probably has been fixed already on April 2018 Update.

**Comment by rdmello** [comment]
@onomatopellan thanks for letting me know about the WSL release notes. I tried the same workflow on a version 10.0.17134.165 system and it worked correctly, so it does seem like this issue is fixed in newer builds.
