### ISSUE TITLE
Incompatibility of a bioinformatic tool on WSL

### ISSUE THREAD

**Issue by cakirb** [Microsoft/WSL#3391]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.165]
Ubuntu 16.04.4 LTS (WSL)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Me and my friend have a problem with featurecounts command (https://sourceforge.net/projects/subread/files/subread-1.6.2/) which is a bioinformatic tool. When I run that command in WSL, I got the error of "Segmentation fault (core dumped)". Initially we thought that the amount of RAM was not enough for this process. But Windows computers with different RAMs (8GB vs 64GB) had the same problem in WSL. And when this command is tried in an Ubuntu computer (native Ubuntu, not WSL), it worked seamlessly. So, it made us think that there should be some incompatibility in WSL for this command. (Until this command, all the other commands worked with no issue.)

In summary, we found out that this command works problematically in WSL, but seamlessly in Ubuntu.

For your own tests, the inputs used for this command is stated below:
Homo_sapiens.GRCh38.92.gtf: https://goo.gl/Pnp3RH
SRR1639080_sorted.bam: https://goo.gl/oWV6Sr

`featureCounts -T 3 -a "/mnt/c/Users/user/Desktop/STEMCELL/RNA_3/References/Homo_sapiens.GRCh38.92.gtf" -o "/mnt/c/Users/user/Desktop/STEMCELL/RNA_3/Output_Files/SRR1639080_readCounts.txt" "/mnt/c/Users/user/Desktop/STEMCELL/RNA_3/Output_Files/SRR1639080_sorted.bam"`

Output:
```

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
          v1.6.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S SRR1639080_sorted.bam                          ||
||                                                                            ||
||             Output file : SRR1639080_readCounts.txt                        ||
||                 Summary : SRR1639080_readCounts.txt.summary                ||
||              Annotation : Homo_sapiens.GRCh38.92.gtf (GTF)                 ||
||      Dir for temp files : /mnt/c/Users/user/Desktop/STEMCELL/RNA_3/Out ... ||
||                                                                            ||
||                 Threads : 3                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Homo_sapiens.GRCh38.92.gtf ...                        ||
||    Features : 1237303                                                      ||
||    Meta-features : 58395                                                   ||
||    Chromosomes/contigs : 47                                                ||
||                                                                            ||
Segmentation fault (core dumped)
```

* What's wrong / what should be happening instead:

The command gives an error (Segmentation error (core dumped)) that Ubuntu itself doesn't give. It should have worked just like Ubuntu. People who uses Linux for bioinformatics avoid WSL not to have any incompatibility issues. So, it is quite important to resolve incompatibility issues like this.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

[featurecounts.zip](https://github.com/Microsoft/WSL/files/2209696/featurecounts.zip)
(To get that, command above used with strace. `strace -o featurecounts.strace featurecounts......`)

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> 225   execve("/mnt/c/Users/user/Desktop/STEMCELL/RNAseqTools/subread-1.6.2/bin/featureCounts", ["featureCounts", "-T", "3", "-a", "/mnt/c/Users/user/Desktop/STEMCE"..., "-o", "/mnt/c/Users/user/Desktop/STEMCE"..., "/mnt/c/Users/user/Desktop/STEMCE"...], [/* 18 vars */]) = 0
[....]
225   lseek(3, 20480, SEEK_SET)         = 20480
225   close(3)                          = 0
225   munmap(0x7f94086a0000, 4096)      = 0
225   --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600000} ---
225   +++ killed by SIGSEGV (core dumped) +++

#1462 . Haven't got one of those in a while. Fix would be to recompile `subread-1.6.2/bin/featureCounts` with a recent glibc.

**Comment by cakirb** [comment]
It is good to have a workaround, but can you say anything when it will be fixed in WSL?

**Comment by yl2j** [comment]
Hello folks, our lab is getting into the single cell rnaseq analysis work. As we are new to this, would you care to comment on the usability of current WSL on windows for rnaseq analysis? How about the upcoming WSL2? @cakirb @therealkenc

**Comment by therealkenc** [comment]
> It is good to have a workaround, but can you say anything when it will be fixed in WSL? @therealkenc

Answer to that question was and remains in the dupe entry [here](https://github.com/microsoft/WSL/issues/1462#issuecomment-413491484).

Better answer these days is WSL2 will be out in a month or two.

[Fun nostalgia BTW. I did the original port of [AceDB](http://www.dbbm.fiocruz.br/genome/generalinfo/acedbfaq.html) to Linux (for C. elegans) in 1993. That's a less gray version of me in FAQ Q2.]
