### ISSUE TITLE
Dive is remounted without metadata after WSL window reopen

### ISSUE THREAD

**Issue by Paul-Pushkarov** [Microsoft/WSL#3393]
I am trying to remount my drive `C` with metadata (following steps in [Chmod/Chown WSL Improvements
](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) article) so I could change my files permissions.

```
sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata
```

I am able to remount the drive and then run `mount -l` to see that it is mounted with metadata:

```
C: on /mnt/c type drvfs (rw,relatime,metadata)
```

Although as I close the `WSL` console and restart it - I see that the drive is mounted without metadata again:

```
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
```

- Is it a but or expected behavior? 
- Is there a way to keep metadata?

* Windows build number: 10.0.17134.165

![metadata_1](https://user-images.githubusercontent.com/37558836/42960871-fcb5cab2-8b41-11e8-826e-6ad033762102.PNG)

![metadata_2](https://user-images.githubusercontent.com/37558836/42960872-fcd34894-8b41-11e8-8e7b-7e864bf61df4.PNG)

**Comment by benhillis** [comment]
Yes this is expected. You have two options to get the behavior you desire:

1. Change settings via [wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings)
2. Add your mount commands to [/etc/fstab](https://en.wikipedia.org/wiki/Fstab)

**Comment by Paul-Pushkarov** [comment]
@benhillis thank you for the quick response!
Though I can't find file `wsl.conf`, tried to search `sudo find / -name "wsl.conf"` got only bunch of `Permission denied` and no positive results. Will check how can I use `/etc/fstab`.

**Comment by benhillis** [comment]
@Paul-Pushkarov - You can just create a new /etc/wsl.conf file with the following contents:

```
[automount]
options="metadata"
```

**Comment by therealkenc** [comment]
> You can just create a new /etc/wsl.conf file with the following contents:

Reminds me... Generate a default `/etc/wsl.conf` via `init` if it isn't there at startup, right around the point you fiddle `resolv.conf`. Its nonexistence is nonobvious to a lot of folks (Paul wasn't the first to ask).

**Comment by benhillis** [comment]
@therealkenc - Not a bad idea...

**Comment by Biswa96** [comment]
@therealkenc `/init` is growing.... ~100KB

**Comment by therealkenc** [comment]
> `/init` is growing.... ~100KB

```
$ ls -l /lib/systemd/systemd
-rwxr-xr-x 1 root root 1595792 Apr 20 09:55 /lib/systemd/systemd
```
😑

**Comment by Paul-Pushkarov** [comment]
Thanks everyone!
I created `/etc/wsl.conf` as @benhillis suggested and it helped.

**Comment by Paul-Pushkarov** [comment]
One more question, is there any performance penalty for using `metadata`?

**Comment by benhillis** [comment]
@Paul-Pushkarov - It should be negligible.
