### ISSUE TITLE
How to disable case sensitivity on WSL 1803?

### ISSUE THREAD

**Issue by gordonwang0** [Microsoft/WSL#3394]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.17134.112]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I use `git clone` on Ubuntu WSL to clone a repo.  This repo has a Visual Studio 2017 solution file in it.  But the solution fails to build because of the new case-sensitive file system.

* What's wrong / what should be happening instead:
The compiler (MSVC) is unable to find files in the project because of case sensitivity.  (A zip downloaded from github on Windows works fine).  Also, running `fsutil` to disable case sensitivity on directories fixed the issue.

I have tried using the following `/etc/wsl.conf` file, but it doesn't seem to have any effect (I don't see `case=off` on `/mnt/c` when I run `mount` in Ubuntu).
```
[automount]
enabled = true
options = "case=off"
```

What am I doing wrong with `/etc/wsl.conf`?  Also -- would you consider defaulting case-sensitivity to OFF?  Upon updating Windows, I encountered several errors with files used on both Ubuntu and Windows.  It took several hours to trace it to the case sensitivity change, as the errors simply say "file not found".

**Comment by 0xbadfca11** [comment]
Did you shutdown all linux processes?
``wsl.conf`` only applies when ``init`` (PID equal to 1) is launched.
Just stop all WSL processes anyway or restart Windows.

**Comment by gordonwang0** [comment]
Restarting Windows fixed it.  Thanks.

**Comment by bonniesimon** [comment]
[automount]
enabled = true
options = "case=off"

Where should I type these commands exactly?
Asking since its 2 years since the original question.
