### ISSUE TITLE
EACCESS when renaming folder that is being watched from nodejs

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/WSL#3395]
Microsoft Windows [Version 10.0.17134.112]

I am trying to use `chokidar`, a popular nodejs file system watcher library.

Whenever I use chokidar to listen for file system changes, I can no longer rename folders that lie within the folder being watched.

* `npm install chokidar`
* `mkdir test`
* `echo hello > test/test.txt`
* create `repro.js`:
```js
var fs = require('fs');
var chokidar = require('chokidar');

// Watch current directory and ignore the node_modules folder
chokidar.watch('.', {ignored: /node_modules/}).on('all', (event, path) => {
  console.log(event, path);
});

// After sufficient time, attempt to rename the test folder
// Note: this is also reproducible using `mv` on the command line
setTimeout(function() {
    fs.rename('test', 'test2', function(err) {
        if (err) {
            console.log(err);
        } else {
            console.log('rename ok');
        }
    });
}, 1000);
```

WSL (Ubuntu 18.04):
![image](https://user-images.githubusercontent.com/5047891/43011345-6bd64da2-8c43-11e8-9c3c-c95fe418ea8f.png)

Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/5047891/43011514-002295d8-8c44-11e8-8ea4-2c90623b6a84.png)

I don't think it is terribly important (other colleagues are able to reproduce with other node versions), but I am using nodejs `v8.11.3`

**Comment by therealkenc** [comment]
> I don't think it is terribly important (other colleagues are able to reproduce with other node versions)

Nah it's a manifestation of about the most pervasive bug around here (if you don't count 0xhexdigits fail at startup).  Call this dupe #1956 but you can pick any dating back to #14.

**Comment by qwabra** [comment]
## this does not work fo me

[code.visualstudio.com/docs](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace)

```json
// settings.json
{
    "remote.WSL.fileWatcher.polling": true
}


## but this is helped

```json
// settings.json
{
    "files.watcherExclude": {
        "**/**/*": true
    }
}
```

**Comment by 95th** [comment]
@qwabra I tried your approach and even that doesn't work.

I tried:
```
    "remote.WSL.fileWatcher.polling": true,
```
then 
```
    "files.watcherExclude": {
        "**/**/*": true
    }
```
then both.

None of this works for me.

Can anyone please help?

**Comment by JordanSimba** [comment]
This is pretty annoying... for now I just close VS code since the file watcher has a lock on the files, do file work in terminal or file explorer and reopen when done with `code .` in ubuntu.
Otherwise, unless there is a reason to not upgrade to WSL 2 I would suggest anybody does so.

**Comment by DerekNonGeneric** [comment]
Why is the workaround from https://github.com/Microsoft/WSL/issues/3395#issuecomment-631630044 not explicitly stated in [the VS Code docs section about known WSL limitations](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace)? It should note that _all_ workspace files _must_ be excluded from being watched otherwise the problem _will_ persist&hellip;

**Comment by qwabra** [comment]
> ...  
> for now I just close VS code since the file watcher has a lock on the files, do file work in terminal or file explorer and reopen  
> ...

 you can just open `settings.json` and switch trigget `false`/`true` in `"**/*": false`
```jsonp
{
    "files.watcherExclude": {
        //
        // block Svelte update
        "**/*": false,
        // "**/*": true,
        //
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "**/.hg/store/**": true
    },
}
```

----

 it can be set locally (use warckspace settings) `.vscode/settings.json`  
[see docs](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)

**Comment by Spongman** [comment]
something is fundamentally broken here. while having my remote-wsl workspace open in vscode, i get the following in a command prompt:

```
C:\WINDOWS\system32>handle my-directory-name | wsl wc -l
177481
```

that means the windows kernel has every single one of the files in my workspace open.


i have the following in my `settings.json`:

```
	"remote.WSL.fileWatcher.polling": true
```

**Comment by GEeKkk** [comment]
> ## this does not work for me
> [code.visualstudio.com/docs](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace)
> 
> ```json
> // settings.json
> {
>     "remote.WSL.fileWatcher.polling": true
> }
> ```
> 
> ## but this is helped
> ```json
> // settings.json
> {
>     "files.watcherExclude": {
>         "**/**/*": true
>     }
> }
> ```

Thank you. This also solved my problem in installing go tools on WSL.

**Comment by SanjivG10** [comment]
// settings.json (located in %appdata%/code/user/settings.json)
{
    "files.watcherExclude": {
        "**/**/*": true
    }
}

After saving it, restart VsCode.

**Comment by asimarora** [comment]
Hello,
I know the issue is closed but summarizing the full steps. I got the what but was not able to get how  of it from this chat.
I am using WSL1 with Docker Desktop 

File -> Preferences -> Settings
Click on the Open Settings(JSON) button on top right corner and change this "remote.WSL.fileWatcher.polling": true.

Hope I am not repeating someone else answer.

**Comment by 554948671** [comment]
تعليقات
[](url)
