### ISSUE TITLE
Ubuntu/WSL interface problem with OS --

### ISSUE THREAD

**Issue by aabatpurdue** [Microsoft/WSL#3400]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.167]
ubuntu 18.04
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I use _procman_ from the sysinternalssuite a lot.  When I do a search (click on the binoculars) for "ubuntu", there seem to be way too many "ubuntu" file paths associated with the **system** (pid=4) process.  Immediately after bringing up a bash window, there are 840+ file paths displayed with the **system** process accounting for about 820 of them.   If I execute <ls /usr/share/man/man1>, there are 3300+ paths displayed.  And it keeps getting worse from there.  After awhile, _procman_ reaches a count of 10000 and does not display any more.

So, is this a feature or a bug (:@{)?
* What's wrong / what should be happening instead:
Should so many paths be accumulated by **system**?  I suspect that the more paths that are there the slower the OS will be.
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
No command to strace.
* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
No logs.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
"Made me look", but not seeing this here. `ls /usr/man/man1` causes ~300 system events, and then it goes quiet. I'm on Insider but doubtful that would make much of a difference relative to '134.

![image](https://user-images.githubusercontent.com/7049700/43053418-6523c9c2-8de1-11e8-95e6-5a871d109390.png)

**Comment by aabatpurdue** [comment]
@therealkenc -- Really off topic but where did you get your _procmon_?  I downloaded the sysinternalssuite bundle in June but my _procmon_ does not have your display and some extra options like the edit, event, filter, tools and options buttons.

**Comment by therealkenc** [comment]
That is version 3.50 from [here](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). Dunno what to tell you about the "extra" options tho. Thing hasn't changed in a decade (and it shows). Here is a August 2009 [article](https://4sysops.com/archives/free-process-monitor-view-file-system-registry-and-network-activity/) (googled at random) with the same [experience](https://4sysops.com/wp-content/uploads/2008/10/process-monitor.png).

**Comment by aabatpurdue** [comment]
I seem to have a brain leak about this topic (maybe it's just a general case of brain leak (:@{)).  Not _procman_, not _procmon_ but _**procexp,**_ duh.  You can observe the problem when you search for "ubuntu" using the File Handle / DLL search on _**procexp**_.

**Comment by therealkenc** [comment]
> You can observe the problem

I cannot. Here's mine, again on 17713, after a `ls /usr/share/man/man1` (and much else). Maybe a caching mechanism changed since 17134. Way to find out would be to try insiders and see.

![image](https://user-images.githubusercontent.com/7049700/43120190-312b6024-8ece-11e8-8ac4-4b499b959475.png)

**Comment by aabatpurdue** [comment]
This handle leak in `system (pid=4)` still occurs with the
 `    Feature update to Windows 10, version 1809`
 `    Microsoft Windows [Version 10.0.17763.55]`
installed.

@therealkenc  - did your processes have elevated privilege when you made your tests?  I made the mistake of attempting the tests as pud user me and got zilch results.  The test processes required the elevated priviledge to get them to work.

Found another way to demonstrate the problem.  When I bring up an admin Command Prompt window and execute `handle -p 4 | find /c "Ubuntu"`, the count agrees with the count that I observe from `procexp`s search mechanism at least up to a count of 10000.  Using this check I got a count of 12000+ once.  `handle` is a process in the `SysinternalsSuite` (needed to modify my PATH so I could execute it).  I see that `system` has 852 open "Ubuntu"  file handles if the only thing that I do is login to Ubuntu/WSL.

**Comment by therealkenc** [comment]
Fool me once, shame on you. Fool me twice, shame on me. That `/usr/share/man/man1` listing is elevated. I will keep a eye out for other reports of handle leaks tho (Admin or otherwise).

![image](https://user-images.githubusercontent.com/7049700/46713222-2a868b80-cc0a-11e8-8314-7dab5085d215.png)

**Comment by aabatpurdue** [comment]
@therealkenc - I think I saw a 0 for your `find` count in the background.  I'm getting a bit frustrated because we are not getting the same results.  Can you suggest any reason for my counts?

--  Thanks

**Comment by therealkenc** [comment]
What do you have for antivirus software if not MSFT Defender. That's grasping though. No straightforward guess or I'da told ya.

**Comment by aabatpurdue** [comment]
@therealkenc - Actually two different antivirus softwares.  When I first started this thread, I had McAfee Endpoint Security installed.  It and Feature Update 1809 had an argument so I uninstalled it so I could install Feature Update 1809, i.e., It's currently MS Defender.  The core system should be effectively unmodified although I've installed a number of items among them being Cygwin and MSYS2.

McAfee has a tendency to stick its nose in places where I'm not sure it should.  Until I figured out what it was doing and stopped it, it even blocked my access to WSL.   After I hang up here, I am going to run McAfee's "get rid of all McAfee  pieces and parts process"  and then check to see if that makes any difference.

FWIW - I am going to get a new laptop in the near future.  At that time, I will install Ubuntu and the SysinternalsSuite with a bare minimum of everything else and make the same tests.  Hopefully that will tell me something.

**Comment by therealkenc** [comment]
> I will install Ubuntu and the SysinternalsSuite with a bare minimum of everything else and make the same tests.

Or just [try it in a VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) is an effective way to get behavioral parity.

**Comment by aabatpurdue** [comment]
Finally got the new laptop.  It has **win10 pro**.  With just **Ubuntu** and **handle.exe** installed, I get the zero counts that you get.  Have barely started to get all of my junk installed but the count has remained zero so far.

NOTE that the other laptop has **win10 home**.  Are we looking at an edition problem?  Which edition do you use?

**Comment by therealkenc** [comment]
> Are we looking at an edition problem?

Doubtful. That doesn't help tell you want it _was_, though. Occam says it is some third party thing (maybe something you didn't even know you had). But who knows. Academic.

> Which edition do you use?

All of them 😉. 

Mostly Pro.
