### ISSUE TITLE
How to remove Ubuntu 16.04 after installing Ubuntu 18.04?

### ISSUE THREAD

**Issue by MartyIX** [Microsoft/WSL#3401]
Hi,

I have installed via Ubuntu 18.04 via Microsoft Store (I just clicked `Install`). How can I now remove Ubuntu 16.04 that still resides on my computer?

Thank you

Best regards,
Martin

Environment: Microsoft Windows [Version 10.0.17134.165]

**Comment by shoffmeister-swisscom** [comment]
Uninstall the "Ubuntu" application.

(There are three applications in the store "Ubuntu 18.04",  "Ubuntu 16.04", and "Ubuntu" - yes, uninstall "Ubuntu")

**Comment by DarthSpock** [comment]
Settings - System - Apps and Features. Search for "Ubuntu".  Click on Ubuntu 16.04, click on "Uninstall". Now go to your `rootfs` under C:\Users\username\appdata\...\Canonical.Limited... Right Click and Delete (or just `rm -rf` from Ubuntu 18.04 that directory.) Be sure to delete the 16.04 directory as 18.04 will also start with Canonical.Limited.. Now done.

**Comment by benhillis** [comment]
@darthspock Uninstalling the app also removes the root file system. No manual steps are required.

**Comment by DarthSpock** [comment]
I've seen it left before on my own machine when I switched to Debian (on 16299) and it was reported in #3390 (17134). So the uninstall doesn't always completely remove everything. Pretty sure I've seen leftover registry entries as well but I run a registry cleaner every week to clean up such issues.

**Comment by benhillis** [comment]
Question has been answered.

**Comment by ohadschn** [comment]
For me Ubuntu 16.04 did not appear in _Apps & Features_ (Windows 10 1909). However I was able to remove it using `wsl --unregister <DistributionName>` (in my case ` wsl --unregister "Legacy"`). You can use `wsl --list` to see all installed distributions. 

Docs: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#unregister-and-reinstall-a-distribution
