### ISSUE TITLE
clisp segfault

### ISSUE THREAD

**Issue by Hellrespawn** [microsoft/WSL#3403]
Windows 10 Pro, version 1803, build 17134.165

I'm trying to run clisp (`clisp_2.49.20170913-4build1_amd64`) on Ubuntu 18.04 but it's failing with the following message:
`Cannot map memory to address 0x8009635c2000`
`[/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 22 (Segmentation fault (core dumped)`

The address seems to be random every time.

Strace: [https://gist.github.com/Hellrespawn/3af705260bde2e2d760dde9860441d24](https://gist.github.com/Hellrespawn/3af705260bde2e2d760dde9860441d24)

As far as I can tell, this is not the same bug as #1128 or #1201 and googling the error message doesn't bring anything up. Any help would be appreciated.

**Comment by therealkenc** [comment]
Haven't dug deep (no repro, natch) but the [mincore(2)](http://man7.org/linux/man-pages/man2/mincore.2.html) fail in the `strace` log seems pretty clear on this one. Was mentioned in #645 ([in passing](https://github.com/Microsoft/WSL/issues/645#issuecomment-247841893)). 
```
912   mincore(0x80098109f000, 4096, 0x7fffe8847cb7) = -1 ENOSYS (Function not implemented)
```

**Comment by Hellrespawn** [comment]
It seems that clisp does work on Ubuntu 16.04. Manually installing `clisp_2.49-10build1_amd64.deb` and `libffcall1_1.10+cvs20100619-4_amd64.deb` from the 17.10 repositories in 18.04 works as a workaround, but it's not ideal.

**Comment by webanck** [comment]
Windows 10 Famille, version 1903, build 18362.418
WSL's Ubuntu 18.0.4.3

I get a clisp error, trying to compile a Latex document with pdflatex calling makeglossaries calling xindy using clisp.
```
xindy  -L french -C utf8 -I xindy -M "main" -t "main.xxx-glg" -o "main.xxx-gls" "main.xxx-glo"
Cannot map memory to address 0x80098aeb1000 .

***Call to xindy failed***

Check 'main.implicits-glg' for details
[/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 12
```

I get the same clsp error calling `xindy --version`:
```
xindy release: unknown
xindy script version: 1.18
Cannot map memory to address 0x80097240d000 .
[/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 12
```

**Comment by supernovae** [comment]
Ubuntu 18.0.4  Windows 10 1909

`bmiller@SP4:/mnt/c/Users/mtheo$ clisp -repl
Cannot map memory to address 0x80096ced6000 .
[/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 12 (Segmentation fault (core dumped`

**Comment by michaelkolber** [comment]
@therealkenc Any update on this issue? I'm getting the same error as @supernovae, same specs.

**Comment by therealkenc** [comment]
You should be good on WSL2.
