### ISSUE TITLE
/tmp not being cleared on boot

### ISSUE THREAD

**Issue by mwidmann** [Microsoft/WSL#3406]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.167]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Restarting the Windows System

* What's wrong / what should be happening instead:

In Debian-like Systems the `/tmp` folder starts fresh when the system is booted. After a fresh restart of Windows (and thus debian in wsl) the `/tmp` folder is still full of files.

**Comment by DarthSpock** [comment]
Dupe of #1278, which was deemed "fixed" because of #344 being resolved.

**Comment by mwidmann** [comment]
Thank you, I started the cron service with `sudo service cron start`. Will look if it works.
