### ISSUE TITLE
^M newlines break bash scripts, typically pipefail error

### ISSUE THREAD

**Issue by toniwillberg** [Microsoft/WSL#3407]
This scenario occurs when downloading ARM template.zip from Azure. It seems the .sh scripts in ARM templates have Windows CRLF line endings, ie. they appear as ^M. 

Example from deploy.sh as seen by "cat -net deploy.sh":

#!/bin/bash^M$
set -euo pipefail^M$

When trying to run this in WSL terminal:
 bash deploy.sh
 : invalid option namet: pipefail

After switching to LF linefeeds it works in WSL as expected.

This probably can not be fixed in WSL, but seems to be quite common error and it was quite hard to figure out what was the root cause. E.g. VSCode doesn't give user any warning about this when using integrated WSL terminal.

Probably something to add to documentation / FAQ.

**Comment by DarthSpock** [comment]
I think you'll have better luck filing this over at https://github.com/Microsoft/Console/ .

**Comment by benhillis** [comment]
@toniwillberg - Can you point me to the scripts so I can follow up with the team that owns them?  There's nothing that WSL can do to handle how Linux applications handle Windows-style line endings.

**Comment by toniwillberg** [comment]
@benhillis I'll send you email with details about the scripts.

Meanwhile feel free to close this issue.

**Comment by benhillis** [comment]
@toniwillberg - Sounds good, thanks!

**Comment by therealkenc** [comment]
> There's nothing that WSL can do to handle how Linux applications handle Windows-style line endings.

There isn't. But Cygwin's `set -o igncr` [patch](https://github.com/Alexpux/MSYS2-packages/blob/master/bash/0001-bash-4.4-cygwin.patch) could be upstreamed to Canonical's [launchpad](https://launchpad.net/ubuntu/+source/bash), as mentioned a [while back](https://github.com/Microsoft/WSL/issues/2365#issuecomment-317526788). You can't win [this war](https://github.com/Microsoft/WSL/issues/3408#event-1753123401) one script at a time.
