### ISSUE TITLE
React-native/NPM CLI issues 

### ISSUE THREAD

**Issue by TheSolly** [Microsoft/WSL#3408]
I am running latest windows with bash on Ubuntu running through cmder wslbridge (i tried running directly throuh bash but same errors). Moving to my react-native folder and trying to run some cli like `react-native run-android` , `gradlew clean` is always producing errors;

![capture](https://user-images.githubusercontent.com/31882844/43197732-5927ea22-900c-11e8-86d4-31d3b87f7b27.PNG)
![capture2](https://user-images.githubusercontent.com/31882844/43197741-5bf546c8-900c-11e8-9f88-181c3e3e2916.PNG)

while surprisingly some other commands like `npm start` work properly...
which npm print out; `/usr/local/bin/npm`
i have npm installed localy and inisde Ubuntu and `whereis npm` produce this:

![capture3](https://user-images.githubusercontent.com/31882844/43196861-b889f512-9009-11e8-9f4e-38afeaf384bf.PNG)

Any idea what i am doing wrong or how to fix this?!

**Comment by therealkenc** [comment]
You've got carriage returns in that script and your Windows/WSL node installations are tripping over one another. #1512

**Comment by TheSolly** [comment]
@DarthSpock i've created the `wsl.conf` and added `metadata`, but still the same problem...

@therealkenc  followed all the suggested solution in [#1512](https://github.com/Microsoft/WSL/issues/1512); but still nothing worked as well. Any suggested solution for fixing why Windows/WSL node are tripping one another?!

**Comment by DarthSpock** [comment]
@TheSolly my suggestion for that would work only if they weren't tripping each other and you were still having issues accessing both. You need to modify your path as mentioned a number of times. If none of the solutions currently posted work for you (after trying multiple times to eliminate the typo factor), then post there so it can gain the attention of the other node folks on the thread.
