### ISSUE TITLE
umask 222 created files/directories are not marked as Read-Only on Windows side

### ISSUE THREAD

**Issue by yarikoptic** [microsoft/WSL#3411]
build 17134, mount with `-o metadata`:

![gkrellshoot_07-25-18_132248](https://user-images.githubusercontent.com/39889/43216848-04b8dc06-900e-11e8-8eb5-ef4427d6f88d.png)
edit 1: actually for none of the directories read-only is set in above example!  got mixed up with **A**rchive, ~~~the purpose of which I am yet to comprehend ;-)~~~ (comprehended -- a somewhat useless, and thus even more surprised that it is set here also inconsistently)

even more fun (even though probably is not even intended to be supported) when mount is without `-o metadata` but with uid/gid -- then only `chmod a-w` results in changing the read-only but not for a directory:

![gkrellshoot_07-25-18_132741](https://user-images.githubusercontent.com/39889/43217096-b2963468-900e-11e8-9c8b-e4437be24916.png)

Underlying story: investigating correct operation of git-annex under WSL mounted `/mnt/c` where windows side does not get read-only flag set for annexed files for some reason. Attn @joeyh

**Comment by Voskrese** [comment]
It is amazing that in general you are running chmod on the NTFS FS partition, these utilities are originally designed to work with Linux file partitions ext* llvm*
Do you want to make a working Linux version of WSl?

\\translate

**Comment by benhillis** [comment]
@yarikoptic - Thanks for filing. Looks like we should be setting the readonly bit on files we create with no write access bits set on DrvFs.  We currently only set / clear the readonly bit on chmod.
