### ISSUE TITLE
Cannot allocate memory error when plenty of free memory

### ISSUE THREAD

**Issue by skuzzer** [Microsoft/WSL#3412]
* Your Windows build number:  Microsoft Windows [Version 10.0.17713.1000]

* What you're doing and what's happening:
```sh
skuzzer@skuzlaptop:~$ assume-role somerole aws s3 ls
MFA code: ......
error: cannot allocate memory
skuzzer@skuzlaptop:~$
```
* What's wrong / what should be happening instead:
The Go program assume-role (https://github.com/remind101/assume-role) should run and then run "aws s3 ls" which is using aws-cli (aws-cli/1.15.21 Python/2.7.12 Linux/4.4.0-17713-Microsoft botocore/1.10.21)
There is plenty of free memory:
```sh
skuzzer@skuzlaptop:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           8092        6279        1581          17         230        1674
Swap:         24576         612       23963
```
* Strace of the failing command, if applicable:  I'll email a zip of the strace output files

**Comment by therealkenc** [comment]
> if applicable: I'll email a zip of the strace output files

It's applicable, but link a [gist](https://gist.github.com/). A CLI repro from clean install is also applicable.

**Comment by skuzzer** [comment]
I've emailed the strace output because there are multiple (10) forks.
I don't have an environment where I can do this clean right now

**Comment by benhillis** [comment]
@skuzzer - Please link the strace on the issue. If you email it to secure@microsoft.com only the Microsoft employees can look at it.
