### ISSUE TITLE
WslLaunchInteractive  failed with error: 0x80070005 Error: 0x80070005 Access is denied.

### ISSUE THREAD

**Issue by tquiggle** [microsoft/WSL#3415]
Had Ubuntu 16.04-LTS running just fine for months (yea).  After taking an update and rebooting, I can no longer launch wsl.exe.  I've checked the permissions on C:\Windows\System32\wsl.exe and I do have read and execute access.

The service is enabled:

  C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- 
  Subsystem-Linux

  Path          : 
  Online        : True
  RestartNeeded : False

PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties : 
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.167]

Clicking on the Ubuntu icon on my desktop (which always worked before) brings up a window with the following text:

WslLaunchInteractive  failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...

* What's wrong / what should be happening instead:

wsl.exe won't launch / should launch

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Attached in a .zip file

[lxcore.zip](https://github.com/Microsoft/WSL/files/2233976/lxcore.zip)

**Comment by tquiggle** [comment]
Additionally info.

I don't have UMCI enabled:

C:\WINDOWS\system32> Get-CIPolicyInfo

   Options HVCIOptions Version PolicyGuid     
   ------- ----------- ------- ----------     
1073741824           0       0 {0, 0, 0, 0...}

When run from an elevated shell, wslconfig shows:

C:\WINDOWS\system32> .\wslconfig.exe /l
W i n d o w s   S u b s y s t e m   f o r   L i n u x   D i s t r i b u t i o n s : 

 U b u n t u   ( D e f a u l t ) 

and trying to run wsl.exe from either a normal or administrator shell hangs.

The suggestion to manually set the page file size to 800 didn't help, nor did Settings -> Applications -> Ubuntu -> Advanced Options -> Repair.

**Comment by benhillis** [comment]
@tquiggle - Thanks for sharing the logs. Unfortunately I'm not seeing anything in the logs you shared that would explain the access denied failure. This makes me think that the error is coming from somewhere outside of our components.  Do you see any interesting logs in the system event viewer around where the error takes place?

**Comment by tquiggle** [comment]
No, I don't see anything in the system logs.  Out of curiosity, how do you read the lxcore* files?

Just in case I botched the timing on the previous ones, I generated a new set where I'm 100% confident I launched Ubuntu twice from the desktop icon while loggging was enabled.  Both times it failed with 0x80070005 Access is denied.

I appreciate any help!

[lxcore-2.zip](https://github.com/Microsoft/WSL/files/2237269/lxcore-2.zip)

**Comment by benhillis** [comment]
@tquiggle - I use [WPA](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer) to view the logs.  Unfortunately your second set of logs also do not make too much sense.  I see an instance being created but I do not see any access denied errors.

**Comment by Biswa96** [comment]
How about including TraceView in WDK and Microsoft/Etw2Json repository?

**Comment by subhasiscgr** [comment]
Microsoft Windows [Version 10.0.18362.145]

Issue: Cannot start WSL.

Console output: 
C:\Users\Subhasis>bash
Access is denied.

WSL is installed and running:

PS C:\WINDOWS\system32>  Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux           

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

Ubuntu is installed and set as default:

C:\Users\Subhasis>wslconfig /l
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)

Additional details: I was never able to set even an username. This is how the initialisation went:

Installing, this may take a few minutes...
Access is denied.
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: subhasis
Access is denied.
Enter new UNIX username:


Logs in zip file:

[bash.zip](https://github.com/microsoft/WSL/files/3268362/bash.zip)
[ubuntuinstall.zip](https://github.com/microsoft/WSL/files/3268363/ubuntuinstall.zip)

**Comment by jvdvegt** [comment]
I'm having the exact same error with a new WSL install. I installed Ubuntu 18.04 manually (using a browser) as mentioned here: https://docs.microsoft.com/en-us/windows/wsl/install-manual

**Comment by AshwinJGitHub** [comment]
Same error here. Tried running this manually from the CanonicalGroupLimited error and got a more detailed error:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.
```

**Comment by HATIMEDIA** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

**Comment by jvdvegt** [comment]
This is when using ubuntu installed from the website:
[Logfile_ubuntu.zip](https://github.com/microsoft/WSL/files/3554154/Logfile_ubuntu.zip)
I didn't even have a Windows Store account, but I made one and reinstalled ubuntu through there, but it makes no difference.
This might be related to https://github.com/microsoft/WSL/issues/2577, though the workaround mentioned there (moving the ubuntu installation some place else) doesn't work for me.
I'm running McAfee anti virus, might that be related?

**Comment by lewisdonofrio** [comment]
So just wondering did you follow my steps at tinyurl.com/donofrioworkdesk?

**Comment by n3jain** [comment]
I am having the exact same error. I have had working WSL on my previous Dell xps 13 machine. I can't get it to run on the new surface machine. https://github.com/microsoft/WSL/issues/4514

**Comment by Biswa96** [comment]
Try to take ownership of the installation folder aka. BasePath before installing it. Command:

```cmd
takeown /f path\to\folder
icacls path\to\folder /grant Everyone:(OI)(CI)(F)
```

**Comment by n3jain** [comment]
`wsl.exe` is in `C:\Windows\system32`, I was able to run `takeown` however I am getting error on `icacls` `OI : The term 'OI' is not recognized as the name of a cmdlet`

**Comment by Biswa96** [comment]
Those commands are for Command Prompt. The path is where WSL distribution will be installed.

**Comment by lewisdonofrio** [comment]
Are you having issues starting wsl or rights got messed up my mistake (just trying to get a baring on what is wrong - have you tried my 'no microsoft store available' writeup tinyurl.com/donofrioworkdesk?

**Comment by Xelnes** [comment]
i have try every method but still the same eror  WslRegisterDistribution failed with error: 0x80070005
what should i do?

**Comment by lewisdonofrio** [comment]
> WslRegisterDistribution failed with error: 0x80070005

What about this (if you have WSL installed by "Store" uninstall it...then it should work 'they say?'
https://github.com/microsoft/WSL/issues/6744

**Comment by Xelnes** [comment]
> 'they say?'
> #6744
yes it works but now im thinking that whats the different beetwen uninstalling it with installing? there must be some +- feature right?

**Comment by Xelnes** [comment]
> > 'they say?'
> > #6744
> > yes it works but now im thinking that whats the different beetwen uninstalling it with installing? there must be some +- feature right?
bcs every time im installing the wsl then the ubuntu will get the WslLaunchInteractive failed with error: 0x80070005 Error: 0x80070005 Access is denied.

**Comment by Xelness** [comment]
> > WslRegisterDistribution failed with error: 0x80070005
> 
> What about this (if you have WSL installed by "Store" uninstall it...then it should work 'they say?' #6744

yes i can open it wihtout any eror but are there some different feature or anything?
