### ISSUE TITLE
Can't connect to Docker for Windows

### ISSUE THREAD

**Issue by aaronpowell** [Microsoft/WSL#3416]
* Your Windows build number: `Microsoft Windows [Version 10.0.17723.1000]`

* What you're doing and what's happening: Using the [unix pipes approach to access Docker for Windows](https://blogs.technet.microsoft.com/virtualization/2017/12/08/wsl-interoperability-with-docker/).

* What's wrong / what should be happening instead: I get the following error:

```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/images/json: EOF
```

Prior to installing build `17723` it was working just fine

* Strace of the failing command, if applicable:  `strace` output: https://gist.github.com/aaronpowell/c34b72f9b946ab0b3cf44d8e214adbce

* Other info:
  * Docker
    * Version: 18.06.0-ce-win69 (19070)
    * Engine: 18.06.0-ce
    * Notary: 0.6.1
    * Compose: 1.22.0
    * Credential Helper: 0.6.0
    * Machine: 015.0
    * Kubernetes: v1.10.3
  * wsl flavour: Ubuntu 18.04

**Comment by aaronpowell** [comment]
I've upgraded to Docker for Windows Edge and still the same problem (well, `v1.38` not `v1.37` in the url).

Also installed the original Ubuntu distro and same problem.

**Comment by onomatopellan** [comment]
Does the TCP without TLS method works? After #3276 fix maybe [npiperelay](https://github.com/jstarks/npiperelay) needs and update.

**Comment by aaronpowell** [comment]
@onomatopellan yes, disabling TLS and using TCP works.

**Comment by aaronpowell** [comment]
Updated to Windows build `17728` and am still having the described problem. I'd guess something's changed impacting how `npiperelay` works.

**Comment by Brian-Perkins** [comment]
This is #3424. You can modify the docker-relay script to call the windows executable directly instead of via the symlink as a workaround. There is a fix for this internally, but it has not yet reached an Insider Build.

**Comment by aaronpowell** [comment]
@Brian-Perkins Thanks, that has fixed it. I'll monitor until a build is flighted with the fix and revert the change to test again 🙂

**Comment by therealkenc** [comment]
#3424 flighted in 17738.
