### ISSUE TITLE
Console: cursor up does not show previous command when using /bin/sh

### ISSUE THREAD

**Issue by egamma** [Microsoft/WSL#3417]
1) open the WSL bash terminal
2) start /bin/sh
3) ls
4) echo bla
5) enter cursor up

I would have expected that this brings up the previously run `ls` command, but the cursors key is not interpreted.

![image](https://user-images.githubusercontent.com/172399/43306949-1d9d1136-917d-11e8-8819-7c81fad36a0a.png)

**Comment by therealkenc** [comment]
Must be the weekend. [this](https://unix.stackexchange.com/questions/21733/why-dont-my-arrow-keys-work-in-sh)

**Comment by egamma** [comment]
@therealkenc makes sense, thanks!
