### ISSUE TITLE
Discussion/Feature_Request: make the WSL Available by Default on Non-developer Windows Machines

### ISSUE THREAD

**Issue by martinvahi** [Microsoft/WSL#3420]
A quote from the [WSL FAQ page](https://docs.microsoft.com/en-us/windows/wsl/faq) _([archival copy](https://archive.is/krqU8))_:

> Who is this for?
> 
> This is primarily a tool for developers -- especially 
> web developers and those who work on or 
> with open source projects. This allows those 
> who want/need to use Bash, common Linux 
> tools (sed, awk, etc.) and many Linux-first 
> tools (Ruby, Python, etc.) to use their toolchain on Windows.
> ...

I understand that the main motive of the Micro$oft to 
develop the WSL is to increase the [Azure hosting service](https://azure.microsoft.com/) sales,
but for some reason the Micro$oft also pursues 
Windows App popularization goals. Given that a general
purpose operating system, including Windows, can run 
programs that are written in various different programming languages 
and given the popularity of an architecture, where "microservices" 
are used, it makes sense to facilitate the use of the 
"microservice architecture" at Windows Apps.

To allow Linux console applications to be part of such Windows Apps 
the end users must have the WSL 
**available and properly configured by default**. 
At some point a Linux specific "microservice" that
is part of a Windows App might be reused at an Azure web app.
That would mimic the NodeJS idea, where the same
code can be used at both ends: at the client side and at the server side.
_(The client side would be a Windows App and the server side would be an Azure hosted web app.)_

Why does the WSL project target only web developers, when
it could really contribute to the Windows App development and
offer a vast array of additional sub-components, the Linux
specific libraries, to the Windows App developer community?
For example, artificial intelligence libraries tend to be Linux specific,
but without the default availability of the WSL at 
non-developer Windows machines, the Windows Apps
that target non-developers can not easily benefit
from the vast array of the Linux specific AI libraries/tools.
If You have the WSL already working, why to hold it back?

Thank You for reading my post.

**Comment by therealkenc** [comment]
[CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l). #675

**Comment by benhillis** [comment]
I am not fond of that insulting nickname.
