### ISSUE TITLE
stdin can not be reused after EOF

### ISSUE THREAD

**Issue by dram** [microsoft/WSL#3421]
* Your Windows build number:

10.0.17134.165

* What you're doing and what's happening:

For following code:

```
#include <stdio.h>

int main () {
        int c;

        printf("Please enter Ctrl-D...\n");
        c = getchar();
        printf("read Ctrl-D %d\n", c);

        clearerr(stdin);

        c = getchar();
        printf("read another character %d\n", c);

        return 0;
}
```

Output in WSL:

```
% ./a.out
Please enter Ctrl-D...
read Ctrl-D -1
read another character -1
```
* What's wrong / what should be happening instead:

`stdin` should be reuseable after `clearerr(stdin)`, but in WSL, subsequent `getchar()` still return `-1`.

Following is expected result (which run under Linux):

```
% ./a.out
Please enter Ctrl-D...
read Ctrl-D -1
a
read another character 97
```

**Comment by therealkenc** [comment]
Yep. Ctrl-D doesn't _close_ stdin on Unix. In `icanon` mode, libc just makes a note of it (and `clearerr()` forgets taking note). Another bane for xplat programmers for the last 30 years, Ctrl-D on Unix and Ctrl-Z on Windows don't work the same. 

WSL 18204:
```
795   write(1, "Please enter Ctrl-D...\n", 23) = 23
795   fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
795   read(0, "", 1024)                 = 0
795   write(1, "read Ctrl-D -1\n", 15)  = 15
795   read(0, "", 1024)                 = 0
795   write(1, "read another character -1\n", 26) = 26
795   exit_group(0)                     = ?
795   +++ exited with 0 +++
```

Real Linux:
```
26720 write(1, "Please enter Ctrl-D...\n", 23) = 23
26720 fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
26720 read(0, "", 1024)                 = 0
26720 write(1, "read Ctrl-D -1\n", 15)  = 15
26720 read(0, "\n", 1024)               = 1
26720 write(1, "read another character 10\n", 26) = 26
26720 exit_group(0)                     = ?
26720 +++ exited with 0 +++
```

**Comment by Brian-Perkins** [comment]
There is a logic error when EOF is the only item left in the buffer -- the read won't advance past it. If there are any additional characters in the buffer after the EOF, it will behave as expected. Current workarounds would include switching to non-canonical/raw mode or injecting an extra character (TIOCSTI).

**Comment by Brian-Perkins** [comment]
Fixed in Windows Insider Build [18890](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18890)
