### ISSUE TITLE
Attempts to execute a symlink to Windows executable does nothing

### ISSUE THREAD

**Issue by luislavena** [Microsoft/WSL#3424]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`10.0.17723.1000` (Insiders Preview, Fast ring)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Within Ubuntu (16.04):

```console
luis@Nostromo:~/bin$ which docker-machine.exe
/mnt/c/ProgramData/chocolatey/bin/docker-machine.exe

luis@Nostromo:~/bin$ docker-machine.exe version
docker-machine.exe version 0.15.0, build b48dc28d

luis@Nostromo:~/bin$ /mnt/c/ProgramData/chocolatey/bin/docker-machine.exe version
docker-machine.exe version 0.15.0, build b48dc28d

luis@Nostromo:~/bin$ ln -s /mnt/c/ProgramData/chocolatey/bin/docker-machine.exe docker-machine
luis@Nostromo:~/bin$ which docker-machine
/home/luis/bin/docker-machine

luis@Nostromo:~/bin$ file docker-machine
docker-machine: symbolic link to /mnt/c/ProgramData/chocolatey/bin/docker-machine.exe

luis@Nostromo:~/bin$ ./docker-machine version
luis@Nostromo:~/bin$ echo $?
1
```

* What's wrong / what should be happening instead:

I expected, as previous versions, that symlink executable gets properly executed. It appears something broke with 17723 and these symlinks no longer work (it worked on previous version)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

```console
$ strace -ff docker-machine version
execve("/home/luis/bin/docker-machine", ["docker-machine", "version"], [/* 33 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x61c0b8)       = 0
set_tid_address(0x61c0f0)               = 9026
getpid()                                = 9026
brk(NULL)                               = 0xb1e000
brk(0xb1f000)                           = 0xb1f000
getcwd("/home/luis/bin", 4096)          = 15
uname({sysname="Linux", nodename="Nostromo", ...}) = 0
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7fffcb943e40) = 0
open("/home/luis/bin/docker-machine", O_RDONLY|O_NOFOLLOW|O_PATH) = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffcb943cc0) = -1 EINVAL (Invalid argument)
close(5)                                = 0
close(3)                                = 0
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

* Contents of `/etc/wsl.conf`:

```
[automount]
enabled = true
options = "metadata"
```

Thank you for making WSL!
❤️ ❤️ ❤️

**Comment by benhillis** [comment]
@luislavena - Looks like this was regressed when #2909 was "fixed".  Since this is a behavior change that is potentially breaking, I'll add a wsl.conf option to opt into the new behavior.

**Comment by benhillis** [comment]
@luislavena - This should be fixed in 17738, please let me know if you have any more issues.

**Comment by luislavena** [comment]
Hello @benhillis, I just upgraded to 17738 and can confirm this is working as expected:

```console
$ which docker-machine
/home/luis/bin/docker-machine

$ file `which docker-machine`
/home/luis/bin/docker-machine: symbolic link to /mnt/c/ProgramData/chocolatey/bin/docker-machine.exe

$ docker-machine version
docker-machine.exe version 0.15.0, build b48dc28d
```

Thank you!
❤️ ❤️ ❤️

**Comment by davidovich** [comment]
Hello, what is the conf entry that you are talking about? Is it the `[interop]` section? I have the same error when trying to symlink docker.exe to docker:

```
# docker -> /mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe
$ ./docker
./docker: Invalid argument
```

**Comment by bbulkow** [comment]
I have exactly this pathology a year later.
Windows 10.0.18362.53 ( slow ring )
Ubuntu 16.04 and 18.04 WSL
I have a soft link which I've defined to my windows editor ( sublime ) so I can just type "subl" in WSL and the file pops up. It's invaluable and has worked great until just the last few weeks.

bin$ which "/mnt/c/Program Files/Sublime Text 3/sublime_text.exe"                                                       /mnt/c/Program Files/Sublime Text 3/sublime_text.exe                                                                    bin$ file "/mnt/c/Program Files/Sublime Text 3/sublime_text.exe"                                                        /mnt/c/Program Files/Sublime Text 3/sublime_text.exe: PE32+ executable (GUI) x86-64, for MS Windows                     bin$ ls -l                                                                                                              total 0                                                                                                                 lrwxrwxrwx 1 root root 52 Apr 25 12:28 subl3 -> '/mnt/c/Program Files/Sublime Text 3/sublime_text.exe'                  bin$     

Executing subl3 doesn't pop up a window, but executing the command directly does.
