### ISSUE TITLE
Can't unzip Ubuntu.appx on Windows Server 2019

### ISSUE THREAD

**Issue by timothies** [Microsoft/WSL#3426]
Version 1803 (OS Build 17666.1000)

**PS C:\> Expand-Archive ~/Ubuntu.appx ~/Ubuntu**
Expand-Archive : .appx is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:1
+ Expand-Archive ~/Ubuntu.appx ~/Ubuntu
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.appx:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive

**Following the instructions in https://docs.microsoft.com/en-us/windows/wsl/install-on-server
to unzip the Ubuntu install on Windows Server 2019**

**Comment by Biswa96** [comment]
Use [7zip](https://www.7-zip.org/).

**Comment by therealkenc** [comment]
Or rename it to `.zip` extension (no really, they're the same thing).

**Comment by timothies** [comment]
Thanks for the suggestion therealkenc I didn't realise that.  

Now that this issue is closed the documentation @  **https://docs.microsoft.com/en-us/windows/wsl/install-on-server** will not get corrected.   What is the best way to request it gets updated?

**Comment by therealkenc** [comment]
> What is the best way to request it gets updated?

There is literally a "Content Feedback" button on the page you linked. See [MicrosoftDocs/WSL](https://github.com/MicrosoftDocs/WSL). Whether the documentation gets "updated" (or not) has nothing to do with whether this issue is open or closed.

**Comment by timothies** [comment]
Good to know, thanks mate

**Comment by benhillis** [comment]
I've updated the server install documentation.

**Comment by timothies** [comment]
Thanks Ben
