### ISSUE TITLE
[BUG] closing sockets in one thread doesn't cause blocking I/O in others to be cancelled

### ISSUE THREAD

**Issue by christianparpart** [Microsoft/WSL#3431]
Hi,

I can reproduce this behaviour with TCP as well as with AF_UNIX. The main thread creates the blocking-I/O server, and a background thread is invoking accept() on it. Now, when the main thread decides to close()/shutdown() the listening file descriptor, the background thread's accept() syscall is meant to be cancelled, returning -1 and having errno set to EINVAL, as the file descriptor became invalid. This works just fine on Linux/OSX but not on WSL.

**Expected Behavior:** Any blocking syscall on a closing file descriptor must be returning with -1 (and errno being set to EINVAL) instead of just continuing to block indefinitely.

NB: I noticed that a connect() to such a socket that got closed/shutdown can still accept (once).

* **Microsoft Windows** [Version 10.0.17134.165]

**Comment by therealkenc** [comment]
> Any blocking syscall on a closing file descriptor must be returning with -1 (and errno being set to EINVAL) instead of just continuing to block indefinitely.

In a word, no. [this](https://stackoverflow.com/questions/9365282/c-linux-accept-blocking-after-socket-closed)

```
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <iostream>

int main(int argc, const char *argv[])
{
    struct sockaddr_un unaddr = {};
    unaddr.sun_family = AF_UNIX;
    unlink("/tmp/tstsvr");
    strcpy(unaddr.sun_path, "/tmp/tstsvr");
    int sd = socket(AF_UNIX, SOCK_STREAM, 0);
    bind(sd, reinterpret_cast<struct sockaddr*>(&unaddr), SUN_LEN(&unaddr));
    listen(sd, 8);
    if (fork() == 0) {
        sleep(1);
        close(sd);
    } else {
        int ret = accept(sd, nullptr, nullptr);
        std::cout << "accept returned: " << ret << "\n";
    }
    return 0;
}
```

Real Linux:
```
unlink("/tmp/tstsvr")                   = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
bind(3, {sa_family=AF_UNIX, sun_path="/tmp/tstsvr"}, 13) = 0
listen(3, 8)                            = 0
clone(strace: Process 3052 attached
child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ffb2d894050) = 3052
[pid  3052] nanosleep({tv_sec=1, tv_nsec=0},  <unfinished ...>
[pid  3051] accept(3, NULL, NULL <unfinished ...>
[pid  3052] <... nanosleep resumed> 0x7ffd949d3850) = 0
[pid  3052] close(3)                    = 0
[pid  3052] exit_group(0)               = ?
[pid  3052] +++ exited with 0 +++
<... accept resumed> )                  = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3052, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3052, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
accept(3, NULL, NULL     <--- and here we wait
```
