### ISSUE TITLE
WSL not responding after some time when serving .

### ISSUE THREAD

**Issue by PadamSethia** [Microsoft/WSL#3432]
* Your Windows build number: Microsoft Windows [Version 10.0.17134.165]

* What you're doing and what's happening: When I run any flask app 
`python run.py` , the flask server starts running . And works fine , but after a few hours of constantly using WSL for local run of the flask app it stops responding , so if i go to `127.0.0.1:5000` on any windows browser , there's no response even in WSL . It seems it doesn't get any request from the browser.
To solve it I have to again and again restart WSL

* What's wrong / what should be happening instead: The flask server running in WSL should keep responding rather than dying / not responding.

Thanks!

**Comment by PadamSethia** [comment]
Does it require more info ? What does `need-repro` label mean @therealkenc

**Comment by WarTP** [comment]
That means: Need steps to reproduce.
Aka more info to reproduce this issue

**Comment by GriffithGNeumark** [comment]
I am having the same issue where I need to restart WSL fairly often as any server I run stops responding after a while. Sometimes it stops after changing git branches, other times it does it out of the blue. This doesn't really have reproducible steps, but I was hoping I could find some suggestions as to what might be causing this
