### ISSUE TITLE
mounted Parallels VM symlinks back to OSX such as \\.psf\home have an I/O error

### ISSUE THREAD

**Issue by sgtz** [Microsoft/WSL#3436]
**Please fill out the below information:**
* Your Windows build number:  Windows NT Version 6.2 Build 9200

* What you're doing and what's happening: trying to access a symlinked directory from bash/WSL that works from both cmd.exe and Hamilton C Shell.

from cmd.exe
  > cd /
  > mklink /D somedir \\.psf\home  
  > bash
  $ cd /mnt/c/somedir 
  -bash: cd: src: Input/output error  

weird advice such as creating a junction out of the /D directory also fail. Developers mode doesn't help either.

* What's wrong / what should be happening instead:

WSL is not recognising symlinks that point to Parallels shares (possibly parallels is using network share driver?)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

n/a

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

n/a

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Voskrese** [comment]
A long ago * nix OS started to understand the link windows?
Maybe I missed something over time.

**Comment by therealkenc** [comment]
#1954. Other one was EINVAL not EIO, but same diff, and same fundamental [response](https://github.com/Microsoft/WSL/issues/1954#issuecomment-311139334).
