### ISSUE TITLE
Distros fail to launch: File system error -2145103860

### ISSUE THREAD

**Issue by fappy012** [Microsoft/WSL#3437]
* Your Windows build number:  
Microsoft Windows [Version 10.0.16299.492]

* What you're doing and what's happening:  
After installing WSL, rebooting, downloading all three linux distros from the "Downloading distros"
section of https://docs.microsoft.com/en-us/windows/wsl/install-manual, each distro .appx fails to launch with File system error -2145103860. Should these be able to launch as a regular user, or do I need to have admin rights to launch?
check sums and sizes in bytes:
$ cksum *
3981138175 208978356 openSUSE-42_v1.appx
4197424015 208258653 SLES-12_v1.appx
3421032464 201749452 Ubuntu.1604.2017.711.0_v1.appx

* What's wrong / what should be happening instead:
I see the following error dialog instead of a bash shell (or whatever is supposed to appear when launch succeeds).
![image](https://user-images.githubusercontent.com/39504279/43662634-7430cb48-971b-11e8-99aa-c755d635d79a.png)

* Strace 
Sorry, not sure how to run strace on a windows machine and the linux part isn't launching.

* For WSL launch issues, detailed logs:
I think only an admin/elevated user can get these logs. I do not have admin rights.

**Comment by onomatopellan** [comment]
Try this:

1. Uninstall Ubuntu app (right click on tile -> Uninstall)
2. Rename Ubuntu.1604.2017.711.0_v1.appx to Ubuntu.1604.2017.711.0_v1.zip and extract all.
3. Run Ubuntu.exe inside the extracted folder.

Does it work now?

**Comment by fappy012** [comment]
Yes! Installing an app within ubuntu now. Thanks! Why did it work this way instead of the original?

**Comment by benhillis** [comment]
@fappy012 - you are likely hitting some issue related to the Microsoft Store. Extracting the appx and running the executable directly bypasses that issue.

**Comment by fappy012** [comment]
Oh, perhaps it is because my admins are blocking Microsoft Store. I thought by downloading it and doing a 'manual' install would avoid any attempt to reach the Store. But I guess those extra steps were necessary too.

**Comment by brucify** [comment]
> Try this:
> 
> 1. Uninstall Ubuntu app (right click on tile -> Uninstall)
> 2. Rename Ubuntu.1604.2017.711.0_v1.appx to Ubuntu.1604.2017.711.0_v1.zip and extract all in to a folder.
> 3. Run Ubuntu.exe inside the extracted folder.
> 
> Does it work now?

This works me. How do you uninstall with this method?

**Comment by tagMacher** [comment]
There is an additional requirement - the extracted folder needs to be on the same drive on which Windows OS is installed. The above does not work if the extracted folder is on a different drive.

**Comment by onomatopellan** [comment]
@brucify You can uninstall the distro with `wsl.exe --unregister <DistributionName>` altough beware because it deletes everything inside the linux distro.

@tagMacher I have distros installed on G: (being C: the system drive) without problem. That should be an only Microsoft Store limitation for now.

**Comment by assadniang** [comment]
@onomatopellan 
Thank you, it worked for me:
![Capture](https://user-images.githubusercontent.com/55926182/70468047-58789180-1a94-11ea-8b2b-92bb7e1157d7.PNG)

**Comment by tvaroglu** [comment]
@onomatopellan  thank you very much for this!  Also worked for me

**Comment by smjltd** [comment]
i am sure this question is little unrelated but when i install any app let's say windows terminal i get this below error file system error "12030"

![image](https://user-images.githubusercontent.com/8701960/83347225-39183e00-a32c-11ea-8252-9a133c758df5.png)

i am using https://store.rg-adguard.net/ to download apps, but i can see exe's when i extract them

**Comment by onomatopellan** [comment]
@smjltd Even If the setup file is a msix like in Windows Terminal I'm afraid you can't choose the folder where to install it.

**Comment by Biswa96** [comment]
> I am sure this question is little unrelated

This is fully unrelated. If you're downloading msix, you can use 7zip to extract it anywhere.

**Comment by smjltd** [comment]
wow that did work you have to basically extract twice, thanks mate 👍🏼

**Comment by IT1810** [comment]
> 
> 
> @smjltd If the setup file is a .msix like in Windows Terminal I'm afraid you can't choose the folder where to install it.
You can install Windows Terminal via Chocolatey
choco install microsoft-windows-terminal

[Chocolatey - Windows Terminal](https://chocolatey.org/packages/microsoft-windows-terminal)
[Github - Windows Terminal](https://github.com/microsoft/terminal)

**Comment by IT1810** [comment]
I tried to extract AppxBundle and run without internet x64.appx or x64.msix with 7zip and some UWP apps successfully installed it.
It worked with Files UWP - Beta, Ear Trumpet, Fluent Terminal, but didn't work for XAML Studio

**Comment by smjltd** [comment]
> I tried to extract AppxBundle and run without internet x64.appx or x64.msix with 7zip and some UWP apps successfully installed it.
> 
> It worked with Files UWP - Beta, Ear Trumpet, Fluent Terminal, but didn't work for XAML Studio

i tried x64.appx behind firewall one that has full access it always fails with 12030 error.

**Comment by valeriob** [comment]
> @brucify You can uninstall the distro with `wsl.exe --unregister <DistributionName>` but beware because it deletes everything inside the linux distro.
> 
> @tagMacher I have distros installed on G: (being C: the system drive) without problem. That should be an only Microsoft Store limitation for now.

Thanks a lot @onomatopellan 
i'm on Windows 10 Enterprise LTSC (1809) i was able to install wls just unzipping the appx package, but i'm unable to uninstall it, my wsl command has very few parameters :( i do not even have lxrun.

Thanks
