### ISSUE TITLE
No internet access after reboot

### ISSUE THREAD

**Issue by avxkim** [microsoft/WSL#3438]
OS Version: 10.0.16299 Build: 16299
Ubuntu 18.04 from microsoft store

After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:

```
ping: google.kz: Temporary failure in name resolution
```

Then i check:

```
cat /etc/resolv.conf
```

File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?

**Comment by Biswa96** [comment]
Try to add DNS server IP address with: `echo 8.8.8.8 > /etc/resolv.conf`.

**Comment by heihachi88** [comment]
`sudo echo 8.8.8.8 > /etc/resolv.conf`

Output:

`bash: /etc/resolv.conf: Permission denied`

Even with sudo i can't

**Comment by onomatopellan** [comment]
@heihachi88 What's the output of `ll /etc/resolv.conf` ?

**Comment by heihachi88** [comment]
both files empty... what the hell, yesterday it worked after reboot, approx after 1 hour. Nothing new i installed.

**Comment by onomatopellan** [comment]
Empty or file did not exist? I was interested in the file permissions. This is what it looks like:.
```console
onoma@DESKTOP-2HISNRP:~$ ll /etc/resolv.conf
lrwxrwxrwx 1 root root 29 May 11 21:15 /etc/resolv.conf -> ../run/resolvconf/resolv.conf
onoma@DESKTOP-2HISNRP:~$ ll /run/resolvconf/resolv.conf
-rw-r--r-- 1 root root 147 Aug  4 20:28 /run/resolvconf/resolv.conf
```
Seems file got corrupted or something. I would uninstall the Ubuntu18.04 app and reinstall it to see if it happens again.

**Comment by heihachi88** [comment]
Are you sure it's not 18.04 issue? Are you using 18.04 yourself?

**Comment by onomatopellan** [comment]
Yes, I'm using 18.04 but I'm using build 17134. Can't you upgrade your Windows 10?

**Comment by heihachi88** [comment]
How can i upgrade build? I must switch to beta or something? I just migrated from MacOS (used it last 6 years)

**Comment by onomatopellan** [comment]
If it's your computer this should work
https://support.microsoft.com/en-us/help/4027667/windows-update-windows-10

**Comment by heihachi88** [comment]
Updated to 1803, same picture. After sleep / reboot, no resolv.conf, i even reinstalled Ubuntu 18.04

**Comment by heihachi88** [comment]
Ended it this way:

```
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.4.4" >> /etc/resolv.conf'

exit
```

-c parameter was missing from @Biswa96 answer, now my DNS is working, but still, why DOES it happening?

**Comment by Voskrese** [comment]
You have problems with the network adapter, WSL is not at all .WSL uses WinSocket

**Comment by heihachi88** [comment]
@Voskrese if i had a problem with the network adapter, then in windows i would have the same problem, but on Windows i have no issues related to DNS.

**Comment by Biswa96** [comment]
@heihachi88 No, I missed the nameserver word. BTW, the resolve.conf file should be automatically created. And it's a symbolic link to `/run/resolvconf/resolv.conf`. Try to delete that `/etc/resolve.conf` and exit from wsl.exe. Then rerun wsl.exe and check if that file/symbolic link will automatically created or not.

**Comment by heihachi88** [comment]
@Biswa96 I can't delete not existing file, both files you mentioned didn't exist, before i manually injected them and `exit` shell, then relaunch again.

**Comment by Voskrese** [comment]
![2018-08-05_205123](https://user-images.githubusercontent.com/10104740/43686063-09eaf0be-98f2-11e8-9f33-3a89a40e3e07.png)

**Comment by heihachi88** [comment]
@Voskrese is reboot necessary? I'll try it next time it won't resolve.

**Comment by Voskrese** [comment]
@heihachi88 This is a recommendation, once reboot to have entered new settings, I think is not the same and the problem

**Comment by heihachi88** [comment]
@Voskrese tried your changes, even rebooted 🤣 , but still no /etc/resolv.conf just WTF is this.

**Comment by onomatopellan** [comment]
Try to recover resolv.conf again (uninstalling the app and reinstalling?) and just after waking up PC from sleep get some logs following this:
https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by heihachi88** [comment]
I've already reinstalled Ubuntu 18.04 twice, maybe it's hardware?

**Comment by onomatopellan** [comment]
Please post the logs. It could be your internet configuration or some permission problem.

**Comment by Voskrese** [comment]
@heihachi88 
I did not write that I will create a file resolv. conf, I said that you have problems with the drivers and the network in Windows
Essentially resolv. conf is Podnastrojkoj, as well as the host file

What service uses resolv. conf in WSL? No, only utilities working with the network, by custom

**Comment by Voskrese** [comment]
@heihachi88  Well, if you want to deal with the network in more detail, here everything is described
https://wiki.debian.org/NetworkConfiguration

> In the most complex situations, using resolvconf really is the way to go, though in more simple configurations it is probably overkill. 

`apt-get install resolvconf`

Check network card settings

`cat /etc/network/interfaces`

Add DNS to the Resolvconf utility

added

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

to

```
/etc/resolvconf/resolv.conf.d/base
/etc/resolvconf/resolv.conf.d/tail
```

`sudo resolvconf -u`

**Comment by Voskrese** [comment]
Alternatively, firewall may block outbound connection
cmd.exe

`netsh advfirewall set allprofiles state off`

bash.exe

`ping google.com`

ON firewall 

`netsh advfirewall set allprofiles state on`

**Comment by heihachi88** [comment]
Ubuntu's firewall you mean?

**Comment by Voskrese** [comment]
I traced the process that is responsible for going into the WSL network, apparently as a layer

https://github.com/henrypp/simplewall

под названием **PICO**

![2018-08-07_184148](https://user-images.githubusercontent.com/10104740/43771542-288d79b6-9a72-11e8-99f7-cc5984095d09.png)

**Comment by wonkyroger** [comment]
Open `C:\Users\%USERNAME%\AppData\Local\lxss\rootfs\etc\resolv.conf`
Add line `nameserver 8.8.8.8` and save.
Run wsl.exe and execute `sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'`
Restart wsl.exe
These steps are fixed my problem. I hope it helps you too.

**Comment by wonkyroger** [comment]
1. Run `wsl.exe`
2. Open `C:\Users\%USERNAME%\AppData\Local\lxss\rootfs\etc\resolv.conf`
3. Replace all with line `nameserver 8.8.8.8`
4. Save

After these steps my problem was fixed.
I hope it helps you too.

**Comment by pauloscardine** [comment]
Looks like there is some problem with WSL networking on build 18945. After booting, the WSL virtual interface got the following address:

```
$ ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.170.29  netmask 255.255.255.0  broadcast 192.168.170.255
        inet6 fe80::215:5dff:fe70:91d2  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:70:91:d2  txqueuelen 1000  (Ethernet)
        RX packets 1892  bytes 285656 (285.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21  bytes 1586 (1.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

On the windows side, the WSL interface was:

```
PS C:\Users\paulos> ipconfig
...
Ethernet adapter vEthernet (WSL):

  Connection-specific DNS Suffix  . :
  Link-local-IPv6 Address . . . . . : fe80::a07a:25bd:e562:a887%61
  IPv4 Address. . . . . . . . . . . : 192.168.160.1
  Subnet Mask . . . . . . . . . . . : 255.255.240.0
  Default Gateway . . . . . . . . . :
...
```

I think the problem is that the default gateway on the linux side should be `192.168.160.1` but since it is outside the `192.168.170.0/24` network the WSL instance ends up without a default gateway.

If I change the netmask to `255.255.240.0` and add the windows IP as default gateway on the linux side too problem is fixed:
```
$ sudo ifconfig eth0 192.168.170.29 netmask 255.255.240.0
$ sudo route add default gw 192.168.160.1
```

I guess that after the upgrade the netmask on the Windows side changed and the virtual DHCP server is providing the wrong one for the WSL host (may be it was hardcoded). Or vice-versa. Anyway the workaround is:

1) check the netmask on the windows side using ipconfig (look for the WSL interface)
2) change the netmask on the linux side
3) add a default route pointing to the IP of the windows network interface.

**Comment by benhillis** [comment]
Thanks @pauloscardine, I noticed the subnet mask was incorrect a bit ago as well. The fix had already been checked in and will be in an Insider build soon.

**Comment by andrewvc** [comment]
I wrote a [powershell script](https://gist.github.com/andrewvc/fe22397c554ac3e6255681bfc864e62e) that does what @pauloscardine described if you have a simple install as I do, with one WSL guess accessible via the `bash` command. You can just run it from the host to search for the right settings and apply them.

**Comment by CarlosLVar** [comment]
Just `sudo su`, enter your password and then do:
`echo "nameserver 8.8.8.8" > /etc/resolv.conf`

Where 8.8.8.8 is your preferred DNS. If you dislike google try 9.9.9.9 or 1.1.1.1 or some adblocking DNS or stuff.

You have to do it as root, not sudo.

**Comment by scardine** [comment]
> Just `sudo su`, enter your password and then do:
> `echo "nameserver 8.8.8.8" > /etc/resolv.conf`
> 

One way to achieve the same result using sudo is:

    echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf

This may solve some problem with the local DNS cache but unfortunately will not solve the "default gateway" problem: you can't reach 8.8.8.8 without a router.

**Comment by shanselman** [comment]
@mscraigloewen I'm hitting this to in a flight upgrade. https://github.com/microsoft/WSL/issues/3438#issuecomment-516847566 is the issue, I have the same netmask mismatch.

**Comment by jordansissel** [comment]
^^ Confirmed @andrewvc's [powershell script](https://gist.github.com/andrewvc/fe22397c554ac3e6255681bfc864e62e) fixes this for me.

Before:

```
% ping google.com
ping: google.com: Temporary failure in name resolution
```

After:

```
ping google.com
PING google.com (172.217.6.78) 56(84) bytes of data.
64 bytes from sfo07s17-in-f14.1e100.net (172.217.6.78): icmp_seq=1 ttl=53 time=15.0 ms
```

**Comment by chelnak** [comment]
For anyone that wants to fix this via @andrewvc 's method but doesn't have pwsh installed in WSL you can do it natively in bash like this:

```
GW=$(route -n | grep 'UG[ \t]' | awk '{print $2}')
sudo ifconfig eth0 netmask 255.255.240.0
sudo ip route add default via $GW
```

**Comment by hjpotter92** [comment]
What if the installed WSL does not have `ifconfig` installed? For eg. debian.

**Comment by chelnak** [comment]
Guess you have to do some magic with ‘/etc/network/interfaces.d‘. (I may be wrong.. I’m not a Debian user)

This bug doesn’t seem to exist for me anymore anyway. Maybe the latest build has fixed it?

**Comment by eljorgio** [comment]
> Just `sudo su`, enter your password and then do:
> `echo "nameserver 8.8.8.8" > /etc/resolv.conf`
> 
> Where 8.8.8.8 is your preferred DNS. If you dislike google try 9.9.9.9 or 1.1.1.1 or some adblocking DNS or stuff.
> 
> You have to do it as root, not sudo.

This worked for me. Thanks!

**Comment by dezza** [comment]
This happened suddenly, I just removed `/etc/resolv.conf` rebooted and let it regenerate the file, this makes sure you are not hardcoding your DNS server for easing further troubleshooting and keeping installation as close to defaults as possible. Most people want the DNS to follow in WSL if you decide to tether internet via phone, use VPN provider etc.

**Comment by mafshin** [comment]
@scardine hint helped me on **WSL2**

```
nano /etc/resolv.conf
```
Change nameserver to google DNS

`nameserver 8.8.8.8`

**Comment by jjcf89** [comment]
I think my problem exists due to a conflict between comcast DNS and my work's openVPN.

While on work's openVPN I can't contact comcast DNS.  Note openVPN is not set up to direct internet traffic over the link but it does print "Blocking outside dns using service succeeded".

While on VPN
```
$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
nameserver 75.75.75.75
nameserver 75.75.76.76
nameserver 2001:558:feed::1
search hsd1.ma.comcast.net.
$ nslookup google.com
../../../../lib/isc/unix/socket.c:2165: internal_send: 75.75.75.75#53: Invalid argument
../../../../lib/isc/unix/socket.c:2165: internal_send: 75.75.76.76#53: Invalid argument
../../../../lib/isc/unix/socket.c:2165: internal_send: 2001:558:feed::1#53: Invalid argument
```

Disconnected from VPN:
```
$ nslookup google.com 75.75.75.75
Server:         75.75.75.75
Address:        75.75.75.75#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.10.110
Name:   google.com
Address: 2607:f8b0:4006:806::200e
```

Note manually setting my Windows DNS to 8.8.8.8 doesn't work but using works DNS does.  Guess I'll talk to IT.
```
jcormier@LAPTOP-JCORMIER2012:~$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
nameserver 8.8.8.8
nameserver 2001:558:feed::1
nameserver 2001:558:feed::2
search hsd1.ma.comcast.net.
jcormier@LAPTOP-JCORMIER2012:~$ nslookup google.com
../../../../lib/isc/unix/socket.c:2165: internal_send: 8.8.8.8#53: Invalid argument
../../../../lib/isc/unix/socket.c:2165: internal_send: 2001:558:feed::1#53: Invalid argument
../../../../lib/isc/unix/socket.c:2165: internal_send: 2001:558:feed::2#53: Invalid argument
```

**Comment by aneudysamparo** [comment]
In my case, the problem was my work VPN. I was installing some ubuntu packages, and I activated my VPN, after successfully connected, my WSL shell began timeout. I saw @jjcf89 answer and I disconnect my VPN and it worked again. 
VPN: Check point Endpoint security

**Comment by jjcf89** [comment]
Note my fix was to remove "block-outside-dns" from my openvpn config file.  This lets the dns calls go through my local LAN.

**Comment by JoeyOverby** [comment]
I was having the same problem, and it was due to Express VPN. So I added an exception for ubuntu2004.exe and pwsh.exe (Power Shell) and now it works fine. 

To find the location of Ubuntu (or other version), open your task manager. Find your distribution, click the drop down, and then right click and select "Open file location". 

Not sure if I need both, but since I sometimes open wsl through power shell, I left both in my exceptions/split tunneling options.

**Comment by AhtiAhde** [comment]
For some of us this seems to be a Windows Defender / Security related issue.

What happens is, that if you upgrade your machine or for some other reason Windows Security reboots with warning, it will disconnect WSL2.

The symptom should be that when you `ping google.com`, it should fail (for me it just freezes and when I ctrl-C, I get that all packages have been lost).

Then you should fix the warnings (usually this means re-enabling "Reptutation-based protection" under the "App & browser control"), and do the following:

1) Disable firewall temporarily by running this in PowerShell: `netsh advfirewall set allprofiles state off`
2) Go to WSL2 and retry `ping google.com`, this should now work, if the problem was related to Windows Security and warnings (it can also relate to firewalls and VPN; you have to google for solving those)
3) Re-enable firewall by running this in PowerShell: `netsh advfirewall set allprofiles state on`
4) The reset the firewall and you should be fine: `netsh advfirewall reset`

This worked nicely for me.

**Comment by lukee1234** [comment]
If you modified, moved or compressed the temp folder, look at #5437 for the solution

**Comment by krehwell** [comment]
[source: stackoverflow](https://stackoverflow.com/questions/62314789/no-internet-connection-on-wsl-ubuntu-windows-subsystem-for-linux)
based on the above, it resolves my problem.
```
Open windows cmd in admin mode and type thses commands

1. netsh winsock reset
2. netsh int ip reset all
3. netsh winhttp reset proxy
4. ipconfig /flushdns
5. reboot
```

**Comment by MaxPowerWasTaken** [comment]
Someone recommended this to me for alleviating a (different but probably related) wsl2 internet connectivity issue:
https://github.com/sakai135/wsl-vpnkit

**Comment by gustavo-lara-molina** [comment]
I fix this with windows 11:
https://github.com/microsoft/WSL/issues/5336#issuecomment-874212438

**Comment by emma3kevin** [comment]
This is what helped to me ...  I am having WSL2 and using VPN (Cisco Anyconnect) to connect to my company network.

WSL2 VM is configured with INTERNAL type of connection of virtual switch be default, which can be the main reason for issues, so we could think about to change to EXTERNAL.

![image](https://user-images.githubusercontent.com/55488356/142191632-46a74a06-8fea-4d36-991b-a7c55198b012.png)


1) update the resolv.conf with 8.8.8.8 (ensure that it is not being overwritten after reboot, see elsewhere how to do it )

2) In powershell with admin privs:  Get-NetAdapter | Where-Object {$_.InterfaceDescription -Match "Cisco AnyConnect"} | Set-NetIPInterface -InterfaceMetric 4000

3) Optionally:  Get-NetIPInterface -InterfaceAlias "vEthernet (WSL)" | Set-NetIPInterface -InterfaceMetric 1

Not sure what this exactly does, and how to do it other way and permanently, but it works.

**Comment by ivanvallenas** [comment]
If you can ping web pages from the linux terminal you can try turning off all your firewalls or antivirus. It worked for me.

**Comment by YevheniiPokhvalii** [comment]
This bug happened to me after installing VirtualBox 6.1.34 - WSL network stopped working.
In order to be able to use VPN beside my home network (the trick with 8.8.8.8 did not work here), I added my router gateway IP as a nameserver to the WSL config:
```
> netsh interface ip show config "WiFi"

Configuration for interface "WiFi"
    DHCP enabled:                         Yes
    IP Address:                           192.168.0.106
    Subnet Prefix:                        192.168.0.0/24 (mask 255.255.255.0)
    Default Gateway:                      192.168.0.1
    Gateway Metric:                       0
    InterfaceMetric:                      50
    DNS servers configured through DHCP:  192.168.0.1
    Register with which suffix:           Primary only
    WINS servers configured through DHCP: None
```
Check if you can ping the router gateway in WSL:
```
$ ping -c1 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=1 ttl=63 time=2.49 ms

--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.487/2.487/2.487/0.000 ms
```
(optionally) Check the content of `/etc/resolv.conf`. You will see a description there:
```
$ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.24.208.1
```
Create `/etc/wsl.conf` in WSL:
```
$ cat /etc/wsl.conf
[network]
generateResolvConf = false
```
In Powershell:
```
wsl --shutdown
```
In WSL:
```
sudo bash -c 'echo "nameserver 192.168.0.1" > /etc/resolv.conf'
```
Works even after the system reboot, no `chattr` is required.

However, the reason why this issue happened is still unclear.

**Comment by VarunBanka** [comment]
> OS Version: 10.0.16299 Build: 16299 Ubuntu 18.04 from microsoft store
> 
> After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:
> 
> ```
> ping: google.kz: Temporary failure in name resolution
> ```
> 
> Then i check:
> 
> ```
> cat /etc/resolv.conf
> ```
> 
> File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?



i was also havibg same issue, here,s how i have fixed
open windows powershell as admin and type the following

netsh advfirewall set allprofiles state off

then press enter 
restart
hope it helps

**Comment by VarunBanka** [comment]
> OS Version: 10.0.16299 Build: 16299 Ubuntu 18.04 from microsoft store
> 
> After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:
> 
> ```
> ping: google.kz: Temporary failure in name resolution
> ```
> 
> Then i check:
> 
> ```
> cat /etc/resolv.conf
> ```
> 
> File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?


i was also having same issue, here's how i have fixed
open windows PowerShell as admin and type the following

netsh advfirewall set allprofiles state off

then press enter
restart
hope it helps

**Comment by VarunBanka** [comment]
> OS Version: 10.0.16299 Build: 16299 Ubuntu 18.04 from microsoft store
> 
> After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:
> 
> ```
> ping: google.kz: Temporary failure in name resolution
> ```
> 
> Then i check:
> 
> ```
> cat /etc/resolv.conf
> ```
> 
> File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?


i was also having same issue, here's how i have fixed
open windows PowerShell as admin and type the following

netsh advfirewall set allprofiles state off

then press enter
restart
hope it helps

**Comment by jjcf89** [comment]
> What are the security risks of doing that?

Looks like it's disabling your windows firewall. Wouldn't recommend

**Comment by VarunBanka** [comment]
> > > OS Version: 10.0.16299 Build: 16299 Ubuntu 18.04 from microsoft store
> > > After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:
> > > ```
> > > ping: google.kz: Temporary failure in name resolution
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then i check:
> > > ```
> > > cat /etc/resolv.conf
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?
> > 
> > 
> > i was also having same issue, here's how i have fixed open windows PowerShell as admin and type the following
> > netsh advfirewall set allprofiles state off
> > then press enter restart hope it helps
> 
> What are the security risks of doing that?

He shouldn't disable firewall. Instead he should use linux in vm

**Comment by VarunBanka** [comment]
> > > OS Version: 10.0.16299 Build: 16299 Ubuntu 18.04 from microsoft store
> > > After PC reboot i open Ubuntu from the start menu, and trying to `ping google.kz` (using bash), getting an error:
> > > ```
> > > ping: google.kz: Temporary failure in name resolution
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then i check:
> > > ```
> > > cat /etc/resolv.conf
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > File not found. Not using any VPN, just windows defender and malwarebytes (i've tried to turn it off, but no result). I guess WSL is having trouble launching some auto scripts to create resolv.conf?
> > 
> > 
> > i was also having same issue, here's how i have fixed open windows PowerShell as admin and type the following
> > netsh advfirewall set allprofiles state off
> > then press enter restart hope it helps
> 
> What are the security risks of doing that?

There are major security ricks of doing that so it's not recommended but what I would recommend is using using linux on vm. Fell free to contact me for any errors or anything.....

**Comment by bayangan** [comment]
I tried many things but it didn't solve my problems. 
Changing nameserver to 8.8.8.8 or 1.1.1.1 can't solve the problem. 
Also tried wsl --shutdown and enter again. 
Tried turn stopping and start the LsxxManager service.

$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=115 time=15.7 ms

$ ping google.com
ping: google.com: Temporary failure in name resolution

composer diagnose or sudo apt update
can't connect to repo

BUT, i have 2 distro installed. One for ubuntu 20.04 and the other one is for ubuntu 22.04. 
ubuntu 20 never has this problem, but for ubuntu 22, it will occasionally starting the problem of connectivity, especially i notice, it will have problem (not really sure, cross fingers) when restarting computer due to windows update

the thing is, distro 1 actually has this in /etc/resolv.conf
nameserver 172.31.16.1

so i change my config file to the same nameserver, and boom. problem solve
as
$ composer diagnose
Checking http connectivity to packagist: OK

while changing it back to
nameserver 8.8.8.8
$ composer diagnose

**Comment by bayangan** [comment]
I changed nameserver in /etc/resolv.conf using IP i found from [public dns](https://public-dns.info/), replacing the usual google dns 8.8.8.8 or 1.1.1.1

No need to restart wsl or computer.
To test the connection can simply run
$ composer diagnose
or
$ sudo apt update
or
ping reknown domain
$ ping google.com

Note: I notice this problem happens sometimes after restarting computer due to windows update (cross finger)

**Comment by VarunBanka** [comment]
> @bayangan
> 
> You may still have issues after that so use your Default Gateway (by default 192.168.0.1) in `/etc/resolv.conf` instead of Google public DNS or any other public DNS.

I've tried it but it needs to be changed after every restart, however I was able to fix it by:

opening the windows PowerShell as admin and typing the following

netsh advfirewall set allprofiles state off

then pressing enter
restarting 

But there are major security ricks of doing that so it's not recommended but what I would recommend is using using linux on vm instead.....

**Comment by CaretakerBlayze** [comment]
Nothing helped. I deleted wsl and now i can't even open google. I just don't have internet connection. Please help

**Comment by bernardosts** [comment]
Still with the same issue. Somehow network between the host and the VM is broken after some actions. With me happens always when I need to connect to any VPN. Just after vpn connection everything works fine. When I disconnect from the vpn wsl vm can't access the internet anymore. I have tried all those commands to restart the windows network stack, wsl vm reboot, restart the wsl system service. Nothing works at all, except a windows reboot. This is really unfortunate. I hope that you guys figure this out in the near future. I would hate to miss the integrated experience of using WSL (and turn to an VM) because of this...

**Comment by craigloewen-msft** [comment]
Hi folks, we have put out a new update that aims to address networking issues in WSL. In your `.wslconfig` file you can set `experimental.networkingMode=mirrored`, as well as some other key settings that should improve your network compatibility, and add support for IPv6! Please try them out and let us know what you think.

More info on this release and the changes can be [found here in the blog post](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/).

Please note: You need to be on a Windows Insiders version to use the new networking settings (Any channel of Windows Insiders will do, including release preview). If you see the "These are not supported" messages it means that your current Windows version doesn't have support, and you will need to upgrade. These features will eventually be coming to Windows 11 22H2.

Please see megathread for DNS issues in WSL: #8365

**Comment by OneBlue** [comment]
Hi ! Please try the [latest networking features](https://learn.microsoft.com/en-us/windows/wsl/networking#dns-tunneling) that we've added in WSL. Those should greatly improve compatibility with VPN's.

If the issue still remains, please reopen this issue.
