### ISSUE TITLE
middle mouse insert in WSL

### ISSUE THREAD

**Issue by edpell** [Microsoft/WSL#3439]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

As I am not a software developer I do not know the breakdown of where this function resides If console refers to windows 10 and wsl is a second class citizen then I think the the console is not at fault. I think it is in WSL.

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.165]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I highlight text with the mouse right button and drag, I then position mouse at desired location of paste, I then hit middle mouse button, sadly nothing is pasted even if the location is the command line. Either the highlight is not enough to save the desired text or the middle mouse is not enough to paste the text. Or no such functionality exists. 
* What's wrong / what should be happening instead:
In Ubuntu in WSL under Windows 10, if text is highlighted by a right mouse slide over it should be saved in a buffer that is available to the middle mouse such that a middle mouse click insert said text at the postion of the mouse at the time of middle mouse click. 

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
My issue is more GUI like I do not see how to do this Strace on a middle mouse click.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
If you can tell me how to collect detailed logs I will be happy to do this for you. Please send email to my work account eapell@us.ibm.com 

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for asistance.

**Comment by therealkenc** [comment]
[Windows Console issue tracker](https://github.com/microsoft/console)

**Comment by edpell** [comment]
I read your contributing instructions and find they my get me in trouble with IBM IT security. I will consult with my manager on how to proceed with logging detailed info on secure IBM machines.

**Comment by edpell** [comment]
Why is this closed? No reason is given. What does adding the console label mean? Yoou have communicated zero information to me so far.

**Comment by peterjc** [comment]
Probably https://github.com/microsoft/terminal/issues/6250

(Commenting since my internet search found this issue first)
