### ISSUE TITLE
Ping using specific interface (SO_BINDTODEVICE error)

### ISSUE THREAD

**Issue by Skywalker-11** [microsoft/WSL#3440]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.165]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. install WSL feature
2. install Debian GNU/Linux from MS store
3. open the app (opens bash command line)
4. `sudo su`  (optional, result same with and without)
5. `ping -I eth3 google.com` or `ping -I eth3 -4 google.com` or `ping -I eth3 -6 google.com`

* What's wrong / what should be happening instead:
It should execute a ping using a specific network device (here eth3 - hosts lan connection)
What actually happens for ipv4 destination (`-4` argument or ipv4-only host)
```
ping -I eth3 -4 google.com
ping: SO_BINDTODEVICE: Invalid argument
```
For ipv6 enabled destination
``` 
ping -6 -I eth3 google.com
setsockopt(SO_BINDTODEVICE): Protocol not available
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
Gist with straces: https://gist.github.com/Skywalker-11/4e9fa7550918fdeb11a0de451e2ce904

Ping without `-I` argument for using a specific interface is working correctly

**Comment by therealkenc** [comment]
Fair enough given #69 [(**MESSAGE**)](https://github.com/Microsoft/WSL/issues/69#issuecomment-345777465) but really this is spiritually dupe #1349. `nmap` does the same thing [here](https://github.com/nmap/nmap/blob/f973b4b9f4cec9055a4fedf2de047cd29d20b817/nbase/nbase_misc.c#L352).

```
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = -1 EFAULT (Bad address)
capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0, permitted=1<<CAP_NET_ADMIN|1<<CAP_NET_RAW, inheritable=0}) = 0
capset({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=1<<CAP_NET_RAW, permitted=1<<CAP_NET_ADMIN|1<<CAP_NET_RAW, inheritable=0}) = 0
setsockopt(4, SOL_SOCKET, SO_BINDTODEVICE, "eth3\0", 5) = -1 ENOPROTOOPT (Protocol not available)
```
