### ISSUE TITLE
After rebooted the win10, the wsl would reinstall auto. How to fix this bug?

### ISSUE THREAD

**Issue by hewind1992** [Microsoft/WSL#3441]
Updates:
My desktop is with windows 10 Pro, version 1803(the newest version up to date 8.8.2018.)

The wsl is the ubuntu 16.04.
-----
I successfully install the wsl and rebooted my windows 10.

When I clicked on the wsl, something showed as belowed:

 **

> Installing, this may take a few minutes...
>  Please create a default UNIX user account. The username does not need to match your Windows username.
> For more information visit: https://aka.ms/wslusers
> Enter new UNIX username:

**

It means I have to configure the wsl again.

This bug happens several times.

How can I fix it? Thx.

**Comment by Biswa96** [comment]
Please fill up the issue template. What is your Windows 10 build number? What distribution you have installed? etc. etc.

**Comment by shoffmeister** [comment]
Could this be related to #2576 ?
