### ISSUE TITLE
WSL does not get focus when launching from taskbar

### ISSUE THREAD

**Issue by mariusstrom** [Microsoft/WSL#3443]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17134

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
If an instance of WSL is running, to run another copy: right-click on the running instance in Taskbar, and select the instance name (i.e., Ubuntu).

* What's wrong / what should be happening instead:
In all other apps (including cmd.exe), the new instance immediately takes focus. With WSL, explorer.exe retains focus and requires either alt-tab to the WSL window or clicking in the WSL window.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
Don't imagine logs are needed as I've repro'd this easily on builds from 16299 all the way through 17134.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by cheshrkat** [comment]
Seeing the same issue on windows 10.0.16299.551

**Comment by DarthSpock** [comment]
> In all other apps (including cmd.exe), the new instance immediately takes focus.

So if CMD is able to focus but WSL is not, I would say check https://github.com/Microsoft/Console/issues/. I think this was addressed in Insiders but it wouldn't hurt to file it over there for verification.

**Comment by mariusstrom** [comment]
thanks @DarthSpock for the suggestion. I just created issue 233 in the Console project.

**Comment by wkbrd** [comment]
Please see the related issues Microsoft/WSL#2597 and Microsoft/WSL#3123, which were replaced by Microsoft/Console#179

**Comment by therealkenc** [comment]
The "console" tag is at best loose on this one. It isn't terminal emulation related (console proper) and it certainly isn't Linux kernel ABI related (WSL proper). The label just qualifies the redirect since Microsoft/console#179 is open.
