### ISSUE TITLE
WSL for Windows Home 10 64 Bit

### ISSUE THREAD

**Issue by KennySydney** [Microsoft/WSL#3444]
Hi Folks, 
Can anyone give me a definitive answer to whether WSL can be enabled for Windows 10 Home 64 bit  vers 1803 OS build 1713.191 please?
I have been struggling to enable this in many ways:
1. Running Powershell in admin mode and ….
2. By ticking the "enable WSL" checkbox in programs and features setting
No joy!. During restart, it gives the message "we couldn't complete the features, removing changes …"

I gave up trying to do that and installed Virtual box and downloaded ubuntu 18.04 LTS. However, when I try to install it by unzipping and running the exe file; I get the error msg " Installation Failed!
Error: 0x8007019e" 
I read here that this error is because WSL is not enabled!!! going around in circle, I am

Much appreciate your help please.

Thanks

This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Gabrielcarvfer** [comment]
Do you have BitDefender installed? Might be related to: https://github.com/Microsoft/WSL/issues/2982

**Comment by shoffmeister** [comment]
Microsoft Windows [Version 10.0.17134.165] - this is Windows 10 Home at the latest "production" patch level.

Works perfectly fine and as expected.

**Comment by thedarkfalcon** [comment]
"downloaded ubuntu 18.04 LTS" and "tried running the exe file" 🤔
What exactly did you download? If you are trying to setup Ubuntu on VirtualBox you should have downloaded an Ubuntu ISO (there should be NO ubuntu exe's). If you need helping setting up a virtual box instance of Ubuntu this is not the right place. Google is your friend.
Here are some links to get you started:
Ubuntu ISO with Desktop GUI:
http://releases.ubuntu.com/18.04/ubuntu-18.04.1-desktop-amd64.iso
Ubuntu ISO with no GUI, only console:
http://releases.ubuntu.com/18.04/ubuntu-18.04.1-live-server-amd64.iso

Instructions on how to setup Ubuntu on VirtualBox:
https://websiteforstudents.com/how-to-install-ubuntu-16-04-17-10-18-04-guest-machines-on-virtualbox/

**Comment by KennySydney** [comment]
Thanks thedarkfalcon. I had downloaded the iso file and now all good after a bit of a battle 👍 :)
