### ISSUE TITLE
sudo apt-get update fails

### ISSUE THREAD

**Issue by wittyameta** [Microsoft/WSL#3445]
* Windows build number:  Microsoft Windows [Version 10.0.17134.191]

* Command run:
sudo apt-get update

> Failed to exec method /usr/lib/apt/methods/http ( via /usr/lib/apt/methods/http)            
Failed to exec method /usr/lib/apt/methods/http ( via /usr/lib/apt/methods/http)            
Failed to exec method /usr/lib/apt/methods/http ( via /usr/lib/apt/methods/http)            
Failed to exec method /usr/lib/apt/methods/http ( via /usr/lib/apt/methods/http)            
Reading package lists... Done                                                               
E: Method http has died unexpectedly!                                                       
E: Sub-process http returned an error code (100)                                            
E: Method /usr/lib/apt/methods/http did not start correctly                                 
E: Method http has died unexpectedly!                                                       
E: Sub-process http returned an error code (100)                                            
E: Method /usr/lib/apt/methods/http did not start correctly                                 
E: Method http has died unexpectedly!                                                       
E: Sub-process http returned an error code (100)                                            
E: Method /usr/lib/apt/methods/http did not start correctly                                 
E: Method http has died unexpectedly!                                                       
E: Sub-process http returned an error code (100)                                            
E: Method /usr/lib/apt/methods/http did not start correctly                                 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease                  
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease          
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease        
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease        
E: Some index files failed to download. They have been ignored, or old ones used instead.

Ping works fine:
> PING archive.ubuntu.com (91.189.88.162) 56(84) bytes of data.
64 bytes from yukinko.canonical.com (91.189.88.162): icmp_seq=1 ttl=49 time=124 ms
64 bytes from yukinko.canonical.com (91.189.88.162): icmp_seq=2 ttl=49 time=124 ms
64 bytes from yukinko.canonical.com (91.189.88.162): icmp_seq=3 ttl=49 time=124 ms
64 bytes from yukinko.canonical.com (91.189.88.162): icmp_seq=4 ttl=49 time=124 ms

**Comment by wittyameta** [comment]
> sudo apt-get install apt-transport-https
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> apt-transport-https is already the newest version (1.6.2).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by therealkenc** [comment]
Alright.
```
sudo su
cd /tmp
wget http://archive.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.6.1_amd64.deb
dpk -i apt_1.6.1_amd64.deb
rm /etc/apt/source.list.d/*
mv /etc/apt/sources.list /etc/apt/source.list.bak
cat <<EOF > /etc/apt/sources.list
> deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
> deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
> EOF
apt clean
apt update
```

If that doesn't work and there are no other takers you might get better service in [ServerFault](https://serverfault.com/) or [AskUbuntu](https://askubuntu.com/). Bonne chance.

**Comment by wittyameta** [comment]
@therealkenc It worked. Thanks!

**Comment by Biswa96** [comment]
@therealkenc It's `dpkg`.
