### ISSUE TITLE
Can I call a Linux API from a Windows program?

### ISSUE THREAD

**Issue by thomassligon** [Microsoft/WSL#3448]
Can I install WSL (but not Linux), and call a Unix/Posix/Linux command (such as backtrace) from a C++ Windows program?
Motivation: I am using a high-performance package for numerically solving differential equations (AMICI https://github.com/ICB-DCM/AMICI). Currently, it is a wrapper for Sundials/CVODES in MATLAB, but will also support Python in a future release. The C++ code makes a call to stacktrace when it runs on Linux or OSX, but skips it when it runs on Windows. Calling stacktrace on Windows/WSL would be a valuable addition to the Windows version. Some other alternatives look less attractive, including
1) Running the Linux version on WSL on Windows would require users to run a completely different environment.
2) Using StackWalk on Windows instead of stacktrace would require significant addition to the logic and appears to be rather complex (http://www.rioki.org/2017/01/09/windows_stacktrace.html).  In contrast, using stacktrace on Windows would would make it easier for the developers to use other Posix APIs with ease and less maintenance overhead.
Here is the code in question:
```
void storeBacktrace(const int nMaxFrames) {
    std::ostringstream trace_buf;
    
    #ifdef PLATFORM_WINDOWS
    
    trace_buf << "stacktrace not available on windows platforms\n";
    
    #else
    
    void *callstack[nMaxFrames];
    char buf[1024];
    int nFrames = backtrace(callstack, nMaxFrames);
    char **symbols = backtrace_symbols(callstack, nFrames);
    
    for (int i = 2; i < nFrames; i++) { // start at 2 to omit AmiException and storeBacktrace call
        Dl_info info;
        if (dladdr(callstack[i], &info) && info.dli_sname) {
            char *demangled = NULL;
            int status = -1;
            if (info.dli_sname[0] == '_')
                demangled = abi::__cxa_demangle(info.dli_sname, NULL, 0, &status);
            snprintf(buf, sizeof(buf), "%-3d %*p %s + %zd\n",
                     i-2, int(2 + sizeof(void*) * 2), callstack[i],
                     status == 0 ? demangled :
                     info.dli_sname == 0 ? symbols[i] : info.dli_sname,
                     (char *)callstack[i] - (char *)info.dli_saddr);
            free(demangled);
        } else {
            snprintf(buf, sizeof(buf), "%-3d %*p %s\n",
                     i-2, int(2 + sizeof(void*) * 2), callstack[i], symbols[i]);
        }
        trace_buf << buf;
    }
    free(symbols);
    if (nFrames == nMaxFrames)
        trace_buf << "[truncated]\n";
    
    #endif
    
    snprintf(trace, sizeof(trace), "%s", trace_buf.str().c_str());
}
```

**Comment by DarthSpock** [comment]
> Some other alternatives look less attractive, including
 1  Running the Linux version on WSL on Windows would require users to run a completely different environment.

Are you aware that they can setup the same environment using https://github.com/Microsoft/WSL-distrolauncher to install whatever distro they utilize for Real Linux?

Another alternative could be to call the AF_Unix on Windows to interop with AF_Unix on WSL to call the APIs from an installed distro. 

The ask still an interesting idea but I see this being marked as "by-design" or "feature request, open a UserVoice".

**Comment by therealkenc** [comment]
>    #ifdef PLATFORM_WINDOWS    
>    trace_buf << "stacktrace not available on windows platforms\n";    
>    #else
> ....
> 

No `dladdr()` et al is pretty classic ABI specific stuff. You might try [MSYS2](https://www.msys2.org/) or [Cygwin](http://www.cygwin.com/). I didn't look to see if that's feasible but it might. Also upvote this [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13292958-rethink-your-strategy-on-how-the-linux-bash-integr) (you're on to something but we're probably about a decade from MSFT coming around, and it is a long discussion topic to explain).

> Using StackWalk on Windows instead of stacktrace would require significant addition to the logic and appears to be rather complex

Yep. But that's why they pay the big bucks.

**Comment by Biswa96** [comment]
It may possible to call Linux API via IOCTLs though LxCore driver (like `bsdtar` executed w/o `init`).

**Comment by therealkenc** [comment]
> Another alternative could be to call the AF_Unix on Windows to interop with AF_Unix on WSL to call the APIs from an installed distro.
> It may possible to call Linux API via IOCTLs though LxCore driver (like bsdtar executed w/o init).

No.

**Comment by thomassligon** [comment]
Thanks to everyone who responded. I looked at UserVoice and found a good explanation
[https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13379040-offer-linux-apis-for-windows-via-wsl-syscall-techn](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13379040-offer-linux-apis-for-windows-via-wsl-syscall-techn)

**Comment by therealkenc** [comment]
The "sorry no plans" response in that UserVoice is correct in stating it is "extremely difficult". But, it is extremely difficult for exactly those reasons that implementing WSL is extremely difficult in the first place (meaning it is a correct but unenlightening observation). I suspect if we see this (in some imaginary future) it will happen by stealth in the reverse direction: NT kernel ABI suport "in WSL". Then there might be an ah-ha moment where everyone realises there is no "in" one or the other. But like I was saying it is a long discussion topic that isn't really useful to have until the _Linux_ ABI is more complete.

**Comment by Leon9113** [comment]
thanks so much !
