### ISSUE TITLE
pthread_mutex_init returns EOPNOTSUPP(95)

### ISSUE THREAD

**Issue by sacredaioros** [Microsoft/WSL#3449]
This is my test code:
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>

int main(int args, char **argv)
{
    pthread_mutex_t mut;
    pthread_mutexattr_t attr;
    pthread_mutexattr_init(&attr);
    pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
    pthread_mutexattr_setprotocol(&attr, PTHREAD_PRIO_INHERIT);
    int eno = pthread_mutex_init(&mut, &attr);
    printf("pthread_mutex_init errno=%d\n", eno);
    pthread_mutexattr_destroy(&attr);
    pthread_mutex_destroy(&mut);
}
```
The outpt is ``pthread_mutex_init errno=95``
I googled for a whole day but get nothing. Thank you for your help.
My Windows version is ``10.0.17134.167``. 
My WSL version is ``Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #137-Microsoft Thu Jun 14 18:46:00 PST 2018``

**Comment by therealkenc** [comment]
> 10.0.17134.167

Returns 0 here. #1006. You want [17627](https://github.com/MicrosoftDocs/WSL/releases/tag/17627). Note the caveat in the release notes. I haven't seen recursive locks in the wild, so if you run into behavioural issues with the lock (contrast the return value success) do feel encouraged to spin up a new submission. If you do, citing your use case helps.
