### ISSUE TITLE
Link provided when no distro's installed does not work

### ISSUE THREAD

**Issue by ChrisMaddock** [Microsoft/WSL#3452]
* Your Windows build number: 10.0.17134.165

* What you're doing and what's happening:  
I've just enabled WSL, and tried to run it. I got the below message:

```
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
```

Entering the suggested link in the browser opens the Microsoft store, but on this page:
![image](https://user-images.githubusercontent.com/4837132/43905884-e2fa1606-9be9-11e8-9111-31bedd9f9f37.png)

**Comment by benhillis** [comment]
Looks like the store must have had some kind of outage, it's working for me now.  Please reopen if you are still seeing this.

**Comment by ChrisMaddock** [comment]
You're right...it's back. Sorry for being premature!
