### ISSUE TITLE
missing dll when trying to install debian

### ISSUE THREAD

**Issue by theorem4** [Microsoft/WSL#3456]
Windows Version 10.0.16299.551

I'm unable to install debian gnu\linux from the microsoft store. Installation fails immediately and debian.exe throws a system error: code execution cannot proceed because api-ms-win-core-console-l2-2-0.dll was not found.

**Comment by derousse** [comment]
I have a similar issue but I had debian working fine previously.  I'm not certain it's related, but I did some driver updates through the Lenovo Vantage utility earlier today and now I get this exact same error when trying to start a bash window.
![image](https://user-images.githubusercontent.com/730202/43977626-56121d62-9caa-11e8-94bd-7fde96d52586.png)

I tried uninstalling Debian, turning off Windows Subsystem for Linux and then turning it back on and reinstalling Debian.  I'm still getting the same error.

**Comment by derousse** [comment]
I just installed Ubuntu and it works fine.  Still no luck with Debian though...

**Comment by 0xbadfca11** [comment]
``debian.exe`` was updated few days ago. ``ubuntu.exe`` is not. Lenovo software does not matter.
https://www.virustotal.com/#/file/b11a6b5812df69e70dc04e7812a64a54d946e3680f4e051cd99566c93efd3eca/details
https://www.virustotal.com/#/file/a4309682690a8dc9b02b4df07654b7991c3d84e60a7ba6b01ae6d61f97dddcd6/details
The difference between them is the version of MSVC used.

**Comment by Biswa96** [comment]
Yes, there are some [new commits](https://salsa.debian.org/rhaist-guest/WSL/commits/master) in GitLab Debian-WSL project. @rhaist may help.
How about compiling the debian.exe with multi-threaded option (/MT) to remove VC runtime dependency? Though it will increase the file size.

**Comment by rhaist** [comment]
I did update the Debian store app to use some of the new upstream features and bug fixes.

Can you post your current WIn10 build version?
(https://support.microsoft.com/en-gb/help/13443/windows-which-operating-system)

As I also had to bump the WindowsTargetPlatformMinVersion you might have to update your base system:
https://salsa.debian.org/rhaist-guest/WSL/blob/v2/DistroLauncher-Appx/DistroLauncher-Appx.vcxproj#L10

**Comment by stabidlo** [comment]
i'm running 16299, same problem - checked again few minutes ago

**Comment by raghavk92** [comment]
i tried to open debian today and i got the same error(api-ms-win-core-console-l2-2-0.dll not found. Its asking me to reinstall but as i see above reinstall wont help and if i reinstall i will loose all the packages i have installed . So should i wait for the solution or should i do something. I didnt update anything .

Currently running windows 10 1709

**Comment by Jotune** [comment]
I've done a windows update yesterday and my Debian isn't working anymore. I have same issue than the one mentioned above.

It's a shame because the popup tells us to reinstall (lose all previous config) and it actually doesn't fix the issue....

Also running on W10 1709.

**Comment by rhaist** [comment]
I am sorry you all have problems with the latest release. I have no clue why this happens for some people atm., as I don't know much of the inner workings of this pretty new WIN10 feature.

I will try to reproduce the problem, but this might take some time.

**Comment by benhillis** [comment]
I'll look into this as well. Likely a compiler setting when the app was built.

**Comment by benhillis** [comment]
@rhaist - If you bumped the _WindowsTargetPlatformMinVersion_ in the visual studio solution, you will also need to change your _TargetPlatformMinVersion_ in your appx manifest.  Why Visual Studio lets you do this is a very good question, but I think that's the issue you are running into.

**Comment by ijustlovemath** [comment]
Glad I'm not the only one seeing this error. I'm up to date, running Win10 Pro, on a Lenovo T530

**Comment by LordWolfenstein** [comment]
It says I am missing "api-ms-win-core-console-l2-0-0.dll" when trying to start Debian. Uninstall and reinstall did not fix the problem.

**Comment by Aheleos** [comment]
I too am unfortunately having this problem. I have installed Ubuntu for now, but it has extra complications for what I'm doing that has some of my work impacted. My personal server is Debian as well so I am really looking forward to the fix. 

I am also happy to help in anyway (testing perhaps).

**Comment by Biswa96** [comment]
Just use wsl.exe or bash.exe. Debian.exe (and others) eventually executes wsl.exe with standard I/O handles via `WslLaunch()` and `WslLaunchInteractive()` functions.

**Comment by Aheleos** [comment]
Thank you for the tip. That definitely brings up a window. Unfortunately it's to my Ubuntu installation. I would rather not uninstall that and lose what I have if I don't have to.

**Comment by benhillis** [comment]
@Aheleos - You can use wslconfig.exe to change your default distribution.

**Comment by Aheleos** [comment]
I was really excited at the idea of that and looked up wslconfig to read through the options, but since I tried to uninstall and reinstall Debian before, it's now installed, but unregistered and not on the list. 

Thank you guys for the quick response and help with this.

**Comment by ijustlovemath** [comment]
To be fair, this is NOT a fix for the issue, merely a workaround for those who havent already uninstalled Debian/installed Ubuntu

**Comment by rhaist** [comment]
Thank you all for bearing with me.
I am just uploading an update to the Debian app recompiled for target version Build 16299 (Fall Creators Update, Version 1709).

I hope this will solve your problems.

**Comment by Aheleos** [comment]
Thank you. I really appreciate the effort.

**Comment by rhaist** [comment]
Store submission went through really fast this time.
You should receive the updated app now if you search for updates in the Windows Store App.

Please tell me if it works.

**Comment by waltersom** [comment]
I was having this problem, a few minutes ago my Debian app updated, and now
it works. Thanks for the quick fix!

**Comment by theorem4** [comment]
Confirmed working on build 16299. Thanks much!

**Comment by ijustlovemath** [comment]
Also works for me! Thanks @rhaist

**Comment by Aheleos** [comment]
Awesome. Thank you @rhaist, @Biswa96, @benhillis  and everyone else that contributed to the discussion.

**Comment by TWXjm** [comment]
Working for me too, thank you all.
The output of uname -a is quite different from the screenshot on the store though. It seems my kernel is much older. Any ideas on how to upgrade it? "apt-get dist-upgrade"  shows no upgrades available. Do I need to add another repository?

$ uname -a
Linux box1 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

Windows 10 Enterprise, version 1709, OS Build 16299.492

**Comment by benhillis** [comment]
@TWXjm - There is no Linux kernel in WSL, thus no way to upgrade it.  The driver that handles the syscall translation is tied to your Windows build number.

**Comment by DarthSpock** [comment]
@rhaist Is there a way for you to add some logic (or did you already) so that the newer Store infrastructure functionalities you adopted can be used if you're using a newer version of Windows that supports it?

**Comment by Biswa96** [comment]
@DarthSpock He followed BenHillis's suggestion. There are some specific rules that should be maintained in project files so that Visual Studio can build the correct AppxManifest file *. See [this commit](https://salsa.debian.org/rhaist-guest/WSL/commit/48efd0d70cc21982652a91bafd5b00fb44009f8e), only the Windows Version was changed in project files. 

<sub><sup>* It can also be written just by typing</sup></sub>

**Comment by DarthSpock** [comment]
Yes I see. Thanks for the info.
