### ISSUE TITLE
netstats does not work

### ISSUE THREAD

**Issue by gao4263** [Microsoft/WSL#3458]
i run  `sudo netstat -anp`, but get no information, just below content:

(No info could be read for "-p": geteuid()=1000 but you should be root.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path

**Comment by Voskrese** [comment]
`cat /etc/network/interfaces` ?

https://wiki.debian.org/NetworkConfiguration

**Comment by gao4263** [comment]
# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown


i  install ifupdown , work as before ,   can you run netstats correctly?

**Comment by therealkenc** [comment]
#2249 ([message](https://github.com/Microsoft/WSL/issues/2249#issuecomment-315213423)). On a quick look, the "`No info could be read for "-p"`" error is a side effect of there being no entries at all.
