### ISSUE TITLE
Question about port

### ISSUE THREAD

**Issue by SCREAM2017** [Microsoft/WSL#3460]
### A question : 

**How to open ports in WSL [ KALI LINUX ]**

**Comment by SCREAM2017** [comment]
--up

**Comment by therealkenc** [comment]
It does not look that there are any takers for your question. This github is for reporting bugs and in the WSL system call emulation. Please see [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) and fill out the issue [ISSUE_TEMPLATE.md](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) when submitting issues.

**Comment by SCREAM2017** [comment]
@therealkenc | My brother, I mean, how to open Port, to use the metasploit. , Because the way from one system to another is different, for this reason I'm wondering how Bourn is being opened in the WSL system
