### ISSUE TITLE
Question about Windows Defender Firewall Whitelist

### ISSUE THREAD

**Issue by SukkaW** [Microsoft/WSL#3462]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

17134

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I was debugging my node application on WSL (Ubuntu 18.04). I start a node http-server lisening at port 8080. I can access my application on my local browser using `localhost:8080` `127.0.0.1:8080` `192.168.123.1:8080` (which is my computer's network IP), but another device which is in the same private network can't access `192.168.123.1:8080`.

* What's wrong / what should be happening instead:

The device which is under the same network can't access the WSL port.

I think I should configure the WIndows Defender or something else about Firewall. but I can't find where & how should I configure it.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Biswa96** [comment]
Collect the Firewall log and find which binary wants to connect.

**Comment by SukkaW** [comment]
I ran `netstat -ano|findstr "8080"` in CMD and got the PID of the binary. And then I could use taskmanager to find where the binary file is (it is under rootfs). And what should I do next?

**Comment by Biswa96** [comment]
Find the absolute Windows path of that Lx binary (in `%LocalAppData%\Packages`). Add that path in in/outbound rule as usual.

**Comment by therealkenc** [comment]
> 17134

Support for WSL pico processes was added in [17627](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17627-skip-ahead)
