### ISSUE TITLE
WSL-GPO Interaction Question

### ISSUE THREAD

**Issue by iAppropriate** [Microsoft/WSL#3463]
Does WSL respect GPO/Local Security Policy configurations? What is the current interaction and if it is not fully supported what is the road-map on this?

**Comment by lewisdonofrio** [comment]
Looking at this question to see what the replies are, I would also like to know what domain GPO can be applied, also can sccm work within the WSL session to enforce updates and the like on the guest session?

**Comment by therealkenc** [comment]
> Does WSL respect GPO/Local Security Policy configurations?

That question is too vague to give a specific answer, but oversimplifying a bit, "yes" or "not applicable". You user account policy is what it is on the "Windows side". What WSL's Linux emulation can do with those rights is dictated by policy under which the WSL pico process is executing. Simple as that.

> also can sccm work within the WSL session to enforce updates and the like on the guest session

No.
