### ISSUE TITLE
Add ability to CTRL-C batch file started from bash.exe

### ISSUE THREAD

**Issue by bubbleguuum** [Microsoft/WSL#3464]
If you launch a .bat from bash.exe, you cannot cancel it with CTRL-C like it would if started in cmd.exe.
It would be nice to have.

**Comment by benhillis** [comment]
Please fill out the issue template.

**Comment by bubbleguuum** [comment]
Oh well, I thought this was pretty much self explanatory from my description...

**Comment by benhillis** [comment]
Your description is clear, what was not clear is your Windows build number.

**Comment by bubbleguuum** [comment]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.228]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

- start bash.exe
- if necessary, register batch file launch support by running
sudo update-binfmts --install WindowsBat /init --extension bat
- start any .bat that does not terminate immediately
- while the .bat runs, try to CTRL-C to stop it. This does not work 

* What's wrong / what should be happening instead:

It would be nice if CTRL-C interrupted the .bat execution, to be more in line 
with behavior of running bacth files in cmd.exe and running shell scripts in bash.exe.
The fact that they cannot be interrupted is more an annoyance that something wrong,
and it is really useful to be able to run batch files in bash.

**Comment by therealkenc** [comment]
Ah that's #1614
