### ISSUE TITLE
setting ptrace_scope to persistent value fails 

### ISSUE THREAD

**Issue by claudevms** [Microsoft/WSL#3466]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 Pro
Version 1803
OS Build   17134.1
Ubuntu 16.04.05 LTS

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I modified the 10-ptrace.conf file to set kernel.yama.ptrace_scope to 0

kernel.yama.ptrace_scope = 0

* What's wrong / what should be happening instead:

Rebooting Windows 10  does not update /proc/sys/kernel/yama/ptrace_scope to the new value.

**Comment by therealkenc** [comment]
#994 or #2530, depending on one's disposition. WSL does not run `systemd` at startup.

Ref #3053, which works recently.
