### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by SCREAM2017** [Microsoft/WSL#3467]
Hello, Today's question is ,,

**How to install _**tools**_  Python  with all its **

with the click of a button

Because the connection system comes and is devoid of tools!

I mean _**tools**_ python such as:

> **[ python-devel , python-dev , python-pip , python-nmap , python-xml ]** **And very many of them**

<< 

If you want to install every one

It took a lot of time

And some Python tools do not write what you need them and then the error appears!

Cause: Because one of these  _**tools**_  Python is not installed, for example:

`**[ python-devel, python-dev, python-pip, python-nmap, python-xml ]**  **And very many of them**`

**Comment by therealkenc** [comment]
[CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md)

**Comment by SCREAM2017** [comment]
@therealkenc My brother did not understand me. I want to install all the tools with the click of a button or by one command

**Comment by SCREAM2017** [comment]
@therealkenc ||  Tools for kali Linux

**Comment by Voskrese** [comment]
`apt-get install python* `

> But this is not done, the packages are installed to fit their needs
> you do not install all the editors of the office, all versions
