### ISSUE TITLE
What about simplify installation folder for WSL?

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3468]
I see that my WSL is installed in

`CanonicalGroupLimited.UbuntuonWindows_1604.2018.510.0_x64__79rhkp1fndgsc`

and

`AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc`

On May there was an update that changed the string `1604.2018.510.0_x64__79rhkp1fndgsc` and this constrained the users which had a personal link to start WSL to upgrade it too (for example I use MinTTY from MSYS2 and wslbridge to start WSL).

Why not just install in `WSL-Ubuntu` (or `WSL-Debian`, `WSL-Suse` etc.)? After all many apps do not change ther installation directory in their updates...

**Comment by therealkenc** [comment]
#2348

**Comment by Biswa96** [comment]
You mentioned two different installation of Ubuntu. This behaviour (folder redirection) was already defined in UWP technology. That folder name can be fetched with `Get-AppxPackage` in Powershell. 

LxssManager.dll itself redirects the installation path at first run only for Windows Store Apps.
