### ISSUE TITLE
Running make on Android (Oreo/Pie) tree hangs on first steps

### ISSUE THREAD

**Issue by Uldiniad** [Microsoft/WSL#3469]
* Your Windows build number:  Microsoft Windows [Version 10.0.18214.1000]

* What you're doing and what's happening:  running `make` at the root of the Android tree on Oreo (8.1.0) and Pie (9.0.0) hangs infinitely within a few steps.

* What's wrong / what should be happening instead: should not hang. it used to work on build <= 17713

* Output up to hanging point: https://gist.github.com/Uldiniad/b150b5c0588509a434a3fb951a0627e8

* Strace of the failing command, if applicable: https://gist.github.com/Uldiniad/aa9e3e2bd28da70530cc60bcf3d32c18

Please let me know if there is anything else I can provide that would be helpful

**Comment by therealkenc** [comment]
#2948 #3157

**Comment by Uldiniad** [comment]
@therealkenc this issue is not related (at least not directly) to the ones you mentioned. I don't think it should be closed

**Comment by Brian-Perkins** [comment]
The strace shows pid 8138 making progress -- hard to tell how quickly it is running, but it does appear to be doing something (enumerating and reading .go files).

**Comment by Uldiniad** [comment]
I left it running 11 hours and it stays at the same step. strace only shows the clock_gettime and sched_yield for millions of lines

**Comment by Brian-Perkins** [comment]
You should scan through the 11-hour strace log (or one that has at least run a little longer) and see what ultimately happens on the pid doing work -- in the strace you shared it did an [openat](https://gist.github.com/Uldiniad/8414e7ded3f7c76655ef143f8095b437#file-make-strace-L13248) but we don't actually see it complete. I suspect at some point it ends up blocking at a specific command.

**Comment by Uldiniad** [comment]
sounds good. I'll also try uploading the larger strace if I can

**Comment by Uldiniad** [comment]
I ran it for 7 minutes (these steps completed in a flash before, there should be no hanging). the strace is 1 GB. how should I proceed for uploading it? Pasting it to gist just seems to crash or I get 405

**Comment by sdv22** [comment]
Seems fixed on 17746.

**Comment by Uldiniad** [comment]
@sdv22 what commands were you executing exactly? I still have the issue on 18219

**Comment by sdv22** [comment]
@Uldiniad 
As usual: . build/envsetup.sh, lunch devicename, make -j16.

**Comment by Uldiniad** [comment]
I have also heard from another source that 17746 seems functional. 18219 still fails on my side. haven't processed the strace yet. will do so next week when I'm back on my rig

**Comment by Uldiniad** [comment]
@therealkenc I've uploaded the preprocessed strace. 12000 lines and 8.9MB now.

**Comment by Uldiniad** [comment]
seems to be fixed in 18234
