### ISSUE TITLE
emulate vsyscall for legacy programs

### ISSUE THREAD

**Issue by Oeffner** [Microsoft/WSL#3470]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.228]

*
Executing the command line program shelxe from bash should display a default help text to the user. Instead the shelxe program dies with a segfault

* Strace of the failing command, if applicable:  

``
oeffner@Dirac:~$ strace -f /mnt/b/OeffnerStuff/LinuxStuff/shelxe
execve("/mnt/b/OeffnerStuff/LinuxStuff/shelxe", ["/mnt/b/OeffnerStuff/LinuxStuff/s"...], [/* 18 vars */]) = 0
uname({sysname="Linux", nodename="Dirac", ...}) = 0
brk(NULL)                               = 0x53fa000
brk(0x53fb150)                          = 0x53fb150
arch_prctl(ARCH_SET_FS, 0x53fa850)      = 0
brk(0x541c150)                          = 0x541c150
brk(0x541d000)                          = 0x541d000
rt_sigaction(SIGFPE, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, NULL, 8) = 0
rt_sigaction(SIGILL, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, NULL, 8) = 0
rt_sigaction(SIGABRT, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, {SIG_DFL, [], SA_RESTORER, 0x7f67652254b0}, 8) = 0
rt_sigaction(SIGINT, {0x17ddb50, [], SA_RESTORER|SA_RESTART|SA_NODEFER|SA_SIGINFO, 0x186f4b0}, {SIG_DFL, [], SA_RESTORER, 0x7f67652254b0}, 8) = 0
futex(0x4a339a0, FUTEX_WAKE, 2147483647) = 0
getrusage(RUSAGE_SELF, {ru_utime={0, 0}, ru_stime={0, 0}, ...}) = 0
getrusage(RUSAGE_SELF, {ru_utime={0, 0}, ru_stime={0, 0}, ...}) = 0
getrusage(RUSAGE_SELF, {ru_utime={0, 0}, ru_stime={0, 0}, ...}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600000} ---
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600000} ---
exit_group(174)                         = ?
+++ exited with 174 +++
oeffner@Dirac:~$
``

This is the same problem reported on https://github.com/Microsoft/WSL/issues/1462 . Since no one has responded for quite awhile on this I'm raising it again as it is a showstopper for more software suites used by several thousand users who would otherwise be able to run these software suites on WSL instead of native Linux once the problem gets solved. 

My understanding is that vsyscall emulation is all that is need to allow backwards compatibility with legacy programs such as shelxe program. Can this be implemented in WSL or has it been decided not to do this?

**Comment by Oeffner** [comment]
Why was this issue closed without further explanation? I may not be totally up to date with all that is going on with WSL but a few lines of explanation would be helpful.

**Comment by therealkenc** [comment]
> a few lines of explanation would be helpful.

It was
closed because
this is
dupe #1462.
