### ISSUE TITLE
Can't open ubuntu bash cause missing `api-ms-win-core-console-l2-2-0.dll`

### ISSUE THREAD

**Issue by DIYer22** [Microsoft/WSL#3471]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Windows 10, 1709, 16299.64

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Error received is as follows:     
`ubuntu.exe`: The code execution cannot proceed because `api-ms-win-core-console-l2-2-0.dll` was not found. Reinstalling the program may fix this problem. I've tried reinstalling as suggested, but the problem persists.

* What's wrong / what should be happening instead:

Open a bash

**Comment by DarthSpock** [comment]
#3456

**Comment by benhillis** [comment]
This is using the Ubuntu app so it is not the same issue. I will follow up with the Ubuntu app owner.

**Comment by DIYer22** [comment]
open `Windows Update`, and Update to latest Windows.   
This way solved my problem.

**Comment by KANGOD** [comment]
I'm running Windows 10, 1709, 16299.579 and come across this issue too. @DIYer22 Did you mean Windows 10 1803 when you said "latest Windows"?

**Comment by benhillis** [comment]
I've followed up with the dev at Canonical and he is working on fixing this.

**Comment by gitfilla** [comment]
I'm getting the same issue. But I can't run Windows Update (system locked by IT). I'm uploading the etl files as mentioned here: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting





[wsl_broken.zip](https://github.com/Microsoft/WSL/files/2298218/wsl_broken.zip)

**Comment by benhillis** [comment]
Fix is in the store submission process now.

**Comment by vsoutherner** [comment]
Will the end user need to manually update? I'm still getting this issue.

**Comment by gerardojbaez** [comment]
Just installed the update, it is working great!

**Comment by benhillis** [comment]
Package has been updated.

**Comment by DannyBiker** [comment]
Thanks for the update, it fixed the issue.

**Comment by KANGOD** [comment]
I am using **Ubuntu** https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6 and failed to find an update, until I noticed that it's a different app **Ubuntu 18.04** https://www.microsoft.com/en-us/p/ubuntu-1804/9n9tngvndl3q . But I was already solve it by updating to 1803.

In the first launch of **Ubuntu** app after booting 1803, it prints out `Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...` and then works well. Maybe this upgrade process makes some initialize/reset/install operation, which fixes this issue.
