### ISSUE TITLE
Ubuntu won't start after I reboot the laptop... 

### ISSUE THREAD

**Issue by sowona** [Microsoft/WSL#3473]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.228]
* What you're doing and what's happening:  
I installed Ubuntu +WSL yesterday on my laptop and all worked very.
I even manage to configure docker and everything was working well.
I notice this morning that a Windows update happened overnight.
Ubuntu Bash ins't starting since then. 

C:\Users\sowona\WSL\Troubleshooting>bash ~
C:\Users\sowona\WSL\Troubleshooting>Ubuntu.exe
C:\Users\sowona\WSL\Troubleshooting>C:\Users\sowona\WSL\Troubleshooting>uname -a
MSYS_NT-10.0 SOWONAX230 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

* What's wrong / what should be happening instead:
Normally bash ~ should start ubuntu bash

* For WSL launch issues, please [collect detailed logs]
[Troubleshooting.zip](https://github.com/Microsoft/WSL/files/2294097/Troubleshooting.zip)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
@sowona - Thanks for sharing the logs.  It looks like the instance is being created successfully, but launching /bin/bash is failing with ENOENT.  Did you do anything that would explain why /bin/bash would not be present?

**Comment by sowona** [comment]
I decided to recreate the instance from scratch and it's all sorted.
Thanks.

**Comment by benhillis** [comment]
No problem. Let me know if you figure out how you got it to this state.
