### ISSUE TITLE
windowsBash tool

### ISSUE THREAD

**Issue by aleppos** [Microsoft/WSL#3474]
Hello,

Today I have create a simple shell file that allow us to execute all available commands in Bash from cmd or Powershell...

https://github.com/aleppos/windowsBash

The idea is simple, just create a shortcut for all commands inside windows 
```sh
windowsPath=/mnt/c/windowsBash/
mkdir -p "$windowsPath"
for entry in /usr/bin/* /bin/*
do
  if [ -f "$entry" ];then
    filename=$(basename "$entry")
    #echo "$entry"
    echo @echo off > "$windowsPath""$filename".bat
    echo bash -c \""$filename" %*\" >> "$windowsPath""$filename".bat
    if [[ ( $filename == "apt-get" ) || (  $filename == "apt" ) || ( $filename == "npm" ) ||  ( $filename == "yarn" ) ]];then
      echo bash -c \"windowsBash\" >> "$windowsPath""$filename".bat
    fi
  fi
done
```

# windowsBash

This tool will allow you to use Bash commands inside Windows.

How to install
==

Run the following command inside Windows Bash to generate shortcuts for commands
```sh
wget https://raw.githubusercontent.com/aleppos/windowsBash/master/windowsBash -P /usr/bin && chmod 0777 /usr/bin/windowsBash && windowsBash
```

Then just add the following directory to your path in Windows
* C:\windowsBash

When you want to update the commands list just run the Shell file again
```sh
windowsBash
```

**Comment by benhillis** [comment]
Looks interesting. I'd suggest using wsl.exe instead of bash.exe though.
