### ISSUE TITLE
failure to launch: The code execution cannot proceed because api-ms-win-core-console-l2-2-0.dll was not found

### ISSUE THREAD

**Issue by JeroenStravers1** [Microsoft/WSL#3476]
**Your Windows build number:**
Microsoft Windows [Version 10.0.16299.547]

**What you're doing and what's happening:**
I get the following error when trying to run WSL:
> ubuntu.exe: The code execution cannot proceed because api-ms-win-core-console-l2-2-0.dll was not found. Reinstalling the program may fix this problem. 

Unfortunately an uninstall through the settings app followed by a reinstall through the Microsoft Store app did not fix this problem. I've also tried updating my Windows as per issue 3471 but the error persists.
It was working fine yesterday before I went to bed, although I left the pc on.

**What should be happening instead:**
It should launch WSL and open a bash.

**Comment by mahmedmostafa** [comment]
I have exactly the same issue

**Comment by 01mk** [comment]
Hello there, I encountered the same issue this morning as well.
I have just updated everything I could including windows. Update of windows fixed this issue. Now I have Windows 10 Pro Version 1803 [Version 10.0.17134.228].

**Comment by KiranMohan** [comment]
I am facing the same issue.

**Comment by ztime** [comment]
I have the same issue, and as OP said, reinstalling did not help the issue.
Windows 10 Enterprise 
Version: 1709
OS Build: 16299.551

There are no updates available for Windows .

**Comment by ILiuz** [comment]
Same issue here.

Windows 10 Pro
Version: 1709
OS Build: 16299.611

I'm wondering if this [https://support.microsoft.com/en-us/help/4023057/update-to-windows-10-versions-1507-1511-1607-1703-and-1709-for-update](windows update) is what prompted the error, but I can not be certain. Anyone else have this in their (recent) update history?

**Comment by ztime** [comment]
My latest update is from 2018-07-26 so that update does not seem to be the issue for me

**Comment by 01mk** [comment]
My WSL Ubuntu 18.04 was updated this morning & my windows was updated about half a month ago. So I think windows update wasn't culprit. 
You should update Windows to Version 1803 (manually check for updates).
If you can't update due to your company policy, try to find previous version of WSL.

**Comment by alexelshamouty** [comment]
Updating manually to 1803 fixed the issue for me!

**Comment by dhrosz** [comment]
Ditto on WSL being broken. I'm also on company hardware, so updating isn't really a solution for me.

**Comment by benhillis** [comment]
Duplicate of 3471. Use WSL.exe or bash.exe  in the meantime until Canonical fixes their issue.

**Comment by benhillis** [comment]
I've received word from Canonical that a fixed version of the app is in store submission now.
