### ISSUE TITLE
Ubuntu 18.04 links missing

### ISSUE THREAD

**Issue by xbotuk** [Microsoft/WSL#3477]
Hi, I want to be able to install latest version of Ubuntu 18.04 in Windows 1703 manually, however the links still point to the older version here.

  https://docs.microsoft.com/en-us/windows/wsl/install-manual

Can you add the Ubuntu 18.04 WSL links please?

**Comment by benhillis** [comment]
https://docs.microsoft.com/en-us/windows/wsl/install-manual has been updated.

**Comment by Biswa96** [comment]
@benhillis Kail missing!

**Comment by Seriell** [comment]
@Biswa96 If I understand correctly, Kali isn't an official Distro supplied by Microsoft. It's a third-party one offered by Kali themselves.

**Comment by therealkenc** [comment]
> official Distro supplied by Microsoft

Nit: Ubuntu isn't supplied by MSFT either. The documentation page is well meaning (it really is), but makes about as much sense as describing how to install Candy Crush Saga manually in "several scenarios in which you may not be able (or want) to, install" CCS from the Store.

In any event, to the extent that page survives for the next several years, please use the docs feedback mechanism when Fedora or Ubuntu 20.04 hits the Store (with the faintest of hopes this post will get a search hit if/when they do).
