### ISSUE TITLE
PhpStorm Terminal

### ISSUE THREAD

**Issue by rroslan** [Microsoft/WSL#3479]
I install debian and ubuntu1804. However when setting as bash,, terminal opens the debian terminal. I have installed composer and deployer and set ssh keys in ubuntu1804. and need to use this terminal.

If I want to open terminal in ubuntu1804 terminal, I experimented by replacing the shell path in PhpStorm with just ubuntu1804 and it works. However it does not open in the intended directory.

It is just a small inconvenience to cd to the work directory.

**Comment by Seriell** [comment]
While I don't know how to completely solve this, I worked around it by creating a batch file (`ubuntu.bat`) containing the following:
```batch
@echo off
ubuntu1804.exe run %*
```

And then setting the IDE to use that as the terminal entrypoint:
![image](https://user-images.githubusercontent.com/14004943/44308826-8d029e80-a3b4-11e8-96f1-d2a35a98514d.png)

This worked as intended in WebStorm, all Intellij editors function mostly the same so it should work in PhpStorm too.
![image](https://user-images.githubusercontent.com/14004943/44308838-aa376d00-a3b4-11e8-983d-48c186f6b5af.png)

As a note, if you ever want to open a non-default distro from the commandline to your current directory, running `ubuntu1804 run` (Using Ubuntu as an example) seems to do that, while `ubuntu1804` on its own opens it in your WSL home directory.
