### ISSUE TITLE
Installing opencv on WSL ubuntu 18.04

### ISSUE THREAD

**Issue by Ebrahim1604** [Microsoft/WSL#3480]
I was looking to install OpenCV on WSL ubuntu 18.04. Following the guide for the latest version from here:
https://www.pyimagesearch.com/2018/08/15/how-to-install-opencv-4-on-ubuntu/

I had previously installed OpenCV on windows using anaconda. Now as I followed the steps in the above tutorial, I was able to successfully build it but when I used the command:
>>> $ make -j4

a particular error appeared. Since I needed more precision in the error, I used the command:

>>> $ make VERBOSE=1 

and this is what screen looked like:

![errorscreen](https://user-images.githubusercontent.com/42499258/44302377-08c50280-a345-11e8-91a5-fe812688e936.PNG)

So I am confused here about 2 issues: 
1) Why is ubuntu accessing the header files of hdf5.cpp from the previously installed Anaconda header files? Shouldn't these header files be present in the directory /home/ebrahim1604/opencv_contrib/modules/hdf/src/ itself? But, the directory only contained the hdf5.cpp and precomp.hpp file. Was there something to be done before the OpenCV installation which I missed?  
2) So regarding the actual error, is the declaration error due to the above mismatch of C/C++ header files or it is a completely different issue?

I'm aware that OpenCV 4 is not yet officially released but I faced similar problems while installing OpenCV 3.3. Also attaching these files just in case:

hdf5.cpp,line37:

![hdf5cpp](https://user-images.githubusercontent.com/42499258/44302633-dc13e980-a34a-11e8-9f9c-d0e94370bff3.PNG)

hdf5.h, line22:
![hdf5h](https://user-images.githubusercontent.com/42499258/44302683-b20ef700-a34b-11e8-844d-58ffd707534c.PNG)

HFpublic.h, line 169:
![h5pub](https://user-images.githubusercontent.com/42499258/44302705-33ff2000-a34c-11e8-83bb-73c18ba073fa.PNG)

types.h, line 109:
![typesh](https://user-images.githubusercontent.com/42499258/44302733-a07a1f00-a34c-11e8-9c6d-8d716c7d5b91.PNG)

I'm still learning Linux so any help will be appreciated.

**Comment by harsh1247** [comment]
This might not be a wsl issue. The issue is due to conflicting declaration. U might get help if u move this issue to anaconda

**Comment by harsh1247** [comment]
Also try checkin INCLUDE environment variable which has been shared from windows to wsl . try to change it manually. or read about interoperability: https://docs.microsoft.com/en-us/windows/wsl/interop#share-environment-variables-between-windows-and-wsl
