### ISSUE TITLE
/mnt/c is empty after windows restart

### ISSUE THREAD

**Issue by izzygold** [Microsoft/WSL#3483]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.228]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
trying to access /mnt/c
cd /mnt/c
ls -a
* What's wrong / what should be happening instead:
ls -a returns nothing
ls -a should show all dirs in c

workaround:
sudo mount -t drvfs C: /mnt/d
cd /mnt/c
ls -a

now I can see the contents of drive c under /mnt/c

This problem reproduces upon windows restart

**Comment by benhillis** [comment]
Did you have a /etc/wsl.conf or mess with some registry settings?

**Comment by izzygold** [comment]
This is my wsl.config file. 
(the numbers are a result of my vim)
no registers where never touched on this machine.

1 [automount]
  2 enabled = true
  3 root = /windir/
  4 options = "metadata,umask=22,fmask=11"
  5 mountFsTab = false
  6 
  7 #Let’s enable DNS  even though these are turned on by default, we’ll specify here just to be explicit.
  8 [network]
  9 generateHosts = true
 10 generateResolvConf = true

**Comment by blackflame007** [comment]
#1864 I had the same issue added my fix at the bottom here
