### ISSUE TITLE
failed : message: invalid argument.....

### ISSUE THREAD

**Issue by conradwt** [Microsoft/WSL#3485]
# failed : message: invalid argument.....

- Your Windows build number: (Type `ver` at a Windows Command Prompt)

```text
C:\Users\username>ver

Microsoft Windows [Version 10.0.17134.228]
```

- What you're doing and what's happening: (Copy&paste specific commands and their output, or include screen shots)

In Ubuntu terminal, when I type

```text
wslpath "c:\Users\username\Desktop" /mnt/c/Users/username/Desktop
```

I'm seeing the following message:

```text
failed : message: invalid argument.....
```

- What's wrong / what should be happening instead:

I'm guessing that it should properly map the drives. At this time, I cannot locate the detail documentation for `wslpath`.

**Comment by Voskrese** [comment]
invalid **argument**.....

`wslpath /?`

**Comment by therealkenc** [comment]
> wslpath "c:\Users\username\Desktop" /mnt/c/Users/username/Desktop

`wslpath` takes only one CLI parameter. The tool was described in this [blog post](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/), but there really isn't much to know other than the usage information you clipped and replaced with ellipsis.

The error provided is most unfortunate (it isn't an `EINVAL`). The customary error is "Usage: " (ref #2715). But what you gonna do.

**Comment by conradwt** [comment]
@therealkenc Thanks for the information and I appreciate it.  I'm going to close this issue for now.
