### ISSUE TITLE
Docker with traefik 1.6.5 on Ubuntu 18.04 / WSL

### ISSUE THREAD

**Issue by UXMichael** [microsoft/WSL#3490]
Docker is running fine in Ubuntu 18.04.
I export the docker host ( tcp://localhost:2375 ).

But traefik throws an error cannt connect to docker daemon. i tried tcp://localhost:2375, tcp://127.0.0.1:2375 as docker.endpoint for traefik.

Is this an Issue or a configuration problem ?

**Comment by agaillar** [comment]
Hi UXMichael, 

I've the same problem.
do you have found an issue ?
Thanks,

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
