### ISSUE TITLE
Installation failed Error: 0x80073cfd

### ISSUE THREAD

**Issue by xVL00PeR** [microsoft/WSL#3491]
- Edition: Windows 10 Pro
- Version: 1607
- OS Compilation: 14393.2189

While following this tutorial: https://docs.microsoft.com/en-us/windows/wsl/install-win10
I managed installing WSL, and downloaded ubuntu appx, but when installing the appx, I'm getting this error: 
> Error message in the installation of the application: A prerequisite for an installation could not be met. (0x80073cfd)

This is the prove that WSL is installed:
```
PS C:\Windows\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Subsistema de Windows para Linux (beta)
Description      : Proporciona servicios y entornos para ejecutar shells y herramientas nativos de Linux en modo de
                   usuario en Windows.
RestartRequired  : Required
State            : Enabled
CustomProperties :
```
How could I fix this?
Thank you in advance.

**Comment by 0xbadfca11** [comment]
The store version requires Build 16215 or later.
The appx file is not clear, but it is the same requirement because it is the same file.

**Comment by deeptechs** [comment]
I have the same problem, any suggestion?

**Comment by rsoeldner** [comment]
@deeptechs facing the same problem

**Comment by deeptechs** [comment]
I solved the problem via installing at cmd not downloading appx file in ui. Just type bash in cmd. It is offering to install wsl, then installing Ubuntu 16.04 successfully.

**Comment by rsoeldner** [comment]
@deeptechs could you elaborate this more; first-time windows user :)
I have downloaded the appx file but how to install it without UI ?

**Comment by deeptechs** [comment]
Just open a cmd window. Type "bash" and enter. It will ask you to install. Then finished.   You don't need to use appx file.

**Comment by cdimauro** [comment]
I've always the same problem on my corporate laptop with latest Windows 10, trying both double-clicking on the .appx or by command-line (PowerShell, with admin privileges). Here follows a dump of PS commands & logs:
```
PS C:\> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


Path          :
Online        : True
RestartNeeded : False



PS C:\> Add-AppxPackage C:\Users\q416045\Downloads\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc.Appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Deployment Add operation with target volume C: on Package CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc from:  (CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc.Appx)  failed
with error 0x80073CFD. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
NOTE: For additional information, look for [ActivityId] f2084bb0-93d4-0003-cf56-0ff2d493d501 in the Event Log or use the command line Get-AppxLog -ActivityID f2084bb0-93d4-0003-cf56-0ff2d493d501
At line:1 char:1
+ Add-AppxPackage C:\Users\q416045\Downloads\CanonicalGroupLimited.Ubun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\q41604...hkp1fndgsc.Appx:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\> Get-Appxlog | Out-GridView
PS C:\> cd .\Ubuntu18.04\
PS C:\Ubuntu18.04> .\ubuntu1804.exe
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Press any key to continue...
```

**Comment by rdp** [comment]
Possibly due to "being administrator"  or "weird corporate privileges"?

**Comment by cdimauro** [comment]
> Possibly due to "being administrator" or "weird corporate privileges"?

Yes, but other colleagues had no problem with the same laptop and setup.

P.S. Admin privileges are required.

**Comment by jkrosado** [comment]
the error's official description is "Package <insert name> is end of life and can no longer be installed."
this means the app isn't being maintained, or is an old version. you can't do anything about that when it shows up on the windows store.

**Comment by cdimauro** [comment]
Problem solved for me, with WSL2.

**Comment by IHZAQSTORM33** [comment]
Hey how do I fix this
Pls help me

**Comment by cdimauro** [comment]
> Hey how do I fix this
> Pls help me

Please install WSL2 from scratch, following the official documentation, and it should work-out.

**Comment by IHZAQSTORM33** [comment]
> > Hey how do I fix this
> > Pls help me
> 
> Please install WSL2 from scratch, following the official documentation, and it should work-out.

Haha yeah its fied
