### ISSUE TITLE
compat-wireless-2010-06-26-p

### ISSUE THREAD

**Issue by SCREAM2017** [Microsoft/WSL#3492]
scream@ADWAA:/mnt/c/Users/ad/desktop/t/compat-wireless-2010-06-26-p$ sudo make unload
/sbin/modprobe: invalid option -- 'l'
/sbin/modprobe: invalid option -- 'l'
Stoping bluetooth service..
./scripts/unload.sh: line 34: /etc/init.d/bluetooth: No such file or directory
./scripts/unload.sh: line 35: /etc/init.d/bluetooth: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
scream@ADWAA:/mnt/c/Users/ad/desktop/t/compat-wireless-2010-06-26-p$

**Comment by therealkenc** [comment]
#1893

From [ISSUE_TEMPLATE.md](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) (which you deleted)

> So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

Please take the time to use the search feature and fill out the template.

**Comment by odtmusisi19** [comment]
/sbin/modprobe: invalid option -- 'l'
/sbin/modprobe: invalid option -- 'l'
Stoping bluetooth service..
Stopping bluetooth: /usr/sbin/bluetoothd.
bluetooth is not running ... failed!

help me

**Comment by pratham704** [comment]
did u get the solution ?

**Comment by Fouad-Bechar** [comment]
- Invalid options in `modprobe` command:
 The `-l` option is not valid for `modprobe`. To load or unload a kernel module, you should use the following syntax:
"/sbin/modprobe <module_name>"
Replace `<module_name>` with the actual name of the module you want to load or unload.
-Missing files in `unload.sh` script:
The `unload.sh` script is trying to access files in `/etc/init.d/bluetooth`, but those files do not exist. You can update the script to handle this situation gracefully. Here's an example of an updated `unload.sh` script:
----------
bash
#!/bin/bash
# Stop Bluetooth service
service bluetooth stop
# Print a success message
echo "Bluetooth service stopped."
# Save this script as unload.sh and make it executable:
# chmod +x unload.sh
# Then run the script:
# ./unload.sh
--------
Make sure to save this script as `unload.sh` and give it execute permissions using `chmod +x unload.sh` or execute and read permissions. Follow this:.'chmod u+r+x unload.sh'.

**Comment by Fouad-Bechar** [comment]
- Invalid options in `modprobe` command:
 The `-l` option is not valid for `modprobe`. To load or unload a kernel module, you should use the following syntax:
"/sbin/modprobe <module_name>"
Replace `<module_name>` with the actual name of the module you want to load or unload.
- Missing files in `unload.sh` script:
The `unload.sh` script is trying to access files in `/etc/init.d/bluetooth`, but those files do not exist. You can update the script to handle this situation gracefully. Here's an example of an updated `unload.sh` script:
bash
'#!/bin/bash '
'# Stop Bluetooth service'
'service bluetooth stop'
'# Print a success message'
'echo "Bluetooth service stopped."'
'# Save this script as unload.sh and make it executable:'
'# chmod +x unload.sh'
'# Then run the script:'
'# ./unload.sh'
Make sure to save this script as `unload.sh` and give it execute permissions using `chmod +x unload.sh` or execute and read permissions using `chmod  u+r+x unload.sh`.
