### ISSUE TITLE
Fedora builds not working on WSL (dnf / yum failing)

### ISSUE THREAD

**Issue by fquinner** [Microsoft/WSL#3493]
**Please fill out the below information:**
* Microsoft Windows [Version 10.0.17134.228]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

After installing Fedora 28 using an image from WSL-Distribution-Switcher to generate a docker image using:

    python get-prebuilt.py fedora:28

And creating a wsl installation using:

    choco install lxrunoffline
    refreshenv
    LxRunOffline.exe install -n fedora28 -d "C:\Users\fquinn\AppData\Local\Packages\Fedora28_LxRunOfflineInstall" -f C:\Users\fquinn\SourceExternal\github\RoliSoft\WSL-Distribution-Switcher\rootfs_fedora_28.tar.gz -s

Attempting to run dnf / yum in these containers causes:

    # yum install vim
    error: db5 error(12) from dbenv->open: Cannot allocate memory
    error: db5 error(22) from dbenv->close: Invalid argument
    error: cannot open Packages index using db5 - Cannot allocate memory (12)
    error: cannot open Packages database in /var/lib/rpm
    Error: Error: rpmdb open failed

I tried clearing out the `__db` entries in the guest as well as matching the working ubuntu kernel settings but neither has worked. I also tried clearing down my PATH to ensure no interpreter conflicts and that made no difference.

* What's wrong / what should be happening instead:

I should be able to launch the package managers in the guest.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

```
# ./strace -o ./dnf.install.vim.strace -f dnf install vim
error: db5 error(12) from dbenv->open: Cannot allocate memory
error: db5 error(22) from dbenv->close: Invalid argument
error: cannot open Packages index using db5 - Cannot allocate memory (12)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
```

Generates output: https://gist.github.com/fquinner/85b5b5c589ef0b00543c3fe53cb6a2e0

**Comment by therealkenc** [comment]
> Fedora 28 using an image from WSL-Distribution-Switcher 

That's an excellent question to post [in that product's forum](https://github.com/DDoSolitary/LxRunOffline/issues) since they supplied your image.

> error: db5 error(22) from dbenv->close: Invalid argument

But saving you the trouble the `EINVAL` is #902 ([message](https://github.com/Microsoft/WSL/issues/902#issuecomment-370169292)) #658 #3451 by roundabout way of #2852 #2871.

**Comment by fquinner** [comment]
@therealkenc thanks, see: https://github.com/DDoSolitary/LxRunOffline/issues/46 it was already raised and they think it's wsl's problem and based on #902 it looks like it is.

With WSL-Distribution-Switcher its actually docker from what i understand that provides the binaries used. all that script does is fetch and assemble them, see: https://github.com/RoliSoft/WSL-Distribution-Switcher/blob/master/get-source.py
