### ISSUE TITLE
Windows editor like notepad fails to open desired file in WSL shell 

### ISSUE THREAD

**Issue by BruceChen2017** [Microsoft/WSL#3494]
In bash, I try to open an existing file which belongs to WSL by some editor installed in Windows, but it will try to create new file in `c:\windows\system32`

**Comment by 0xbadfca11** [comment]
> DO NOT create / modify Linux files from Windows apps, tools, scripts or consoles
> https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/
