### ISSUE TITLE
Ruby unicorn web server is completely broken on WSL

### ISSUE THREAD

**Issue by SamSaffron** [Microsoft/WSL#3496]
To repro: 

install ruby
```
gem install unicorn
```

create a `rackup.ru` file with the contents: 

```
class HelloWorld
  def call(env)
    [200, {"Content-Type" => "text/html"}, ["Hello World!"]]
  end
end

run HelloWorld.new
```
 
run `unicorn`

This is due to socket options, also reported here: https://github.com/Microsoft/WSL/issues/1982#issuecomment-412730481 and https://bogomips.org/unicorn-public/CAAtdryOtTO8HGTeKLy_JbeRhWLC7JZpCABVpbpEK+z67JHx=ew@mail.gmail.com/T/#u

**Comment by SamSaffron** [comment]
per @bitcrazed ping @tara-raj

**Comment by therealkenc** [comment]
> This is due to socket options, also reported here: #1982 (comment)

No `strace` or rest or ISSUE_TEMPLATE.md but I'll take your word for it.
