### ISSUE TITLE
"sudo modprobe msr" failed

### ISSUE THREAD

**Issue by ProjectYoung** [Microsoft/WSL#3497]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows 10.0.17134.228

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I tried to disable turbo-boost on WSL and I followed the instructions I found at: https://askubuntu.com/questions/619875/disabling-intel-turbo-boost-in-ubuntu

I successfully installed msr-tools (sudo apt install msr-tools), and try to run:
rdmsr -p0 0x1a0 -f 38:38
and get the following error:
rdmsr:open: No such file or directory

As the post suggets, I tried to load the “msr” module by the following command:
sudo modprobe msr
and get this following error:

modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module msr not found in directory /lib/modules/4.4.0-17134-Microsoft

I searched on the internet but got no luck. However, path dev/cpu/CPUNUM/msr appears many times, but this directory does not exist on my computer, so I guess it's not supported in WSL?

I also tried cpupower but when I ran:
cpupower frequency-info
I got a warning:
WARNING: cpupower not found for kernel 4.4.0-17134

I'm new to both Ubuntu and WSL, so I'm not sure if it's related to WSL. Sorry if it's irrelevant.

**Comment by therealkenc** [comment]
[`modprobe`](http://man7.org/linux/man-pages/man8/modprobe.8.html) doesn't work on WSL unfortunately, and by extension, in your case, neither does `cpupower`. That `/dev/cpu/#/msr` device is enabled by the module that you can't load. If you want to disable turbo-boost, you can do it from the Windows side to same effect. In principle you could open a [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l) to request the functionality be baked into WSL. Your question isn't irrelevant. It can be confusing what and is not supported. There is some discussion on `modprobe` in #1893.
