### ISSUE TITLE
Executing Windows programs sometimes does not work in new PID namespace

### ISSUE THREAD

**Issue by Marc-Aldorasi-Imprivata** [microsoft/WSL#3498]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17134.228

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
$ sudo unshare --pid --fork sh -c '/mnt/c/Windows/System32/notepad.exe && true'
/mnt/c/Windows/System32/notepad.exe: Invalid argument
```

* What's wrong / what should be happening instead:
Notepad should be running

* Strace of the failing command, if applicable:
https://gist.github.com/marc-groundctl/7f213a00909aa72a1ff42123efbf0505

This appears to be because getpid returns the PID in the new PID namespace, but the IOCTL `_IOC(0, 0, 0x97, 0x22)` wants a pid in the original namespace.  If I attach a debugger and manually change the pid passed to that IOCTL, notepad executes correctly.

**Comment by benhillis** [comment]
/init is kind of our grab-bag binary that handles lots of things (including the binfmt interpreter for launching Windows binaries).  When run as pid=1 it thinks it is running as the init daemon, so it tries to connect back the LxssManager service.

I suppose we should treat the binfmt interpreter the same way we do wslpath and make it a symlink to /init.

Is this blocking something in particular or just something you noticed while poking around?  Thanks!

**Comment by marc-groundctl** [comment]
I found it when setting up an [Arch chroot](https://git.archlinux.org/arch-install-scripts.git/tree/arch-chroot.in).  The script works fine without unsharing the pid namespace, so it's not blocking anything.

**Comment by therealkenc** [comment]
> should treat the binfmt interpreter the same way we do wslpath and make it a symlink to /init

[Or.... ](https://github.com/Microsoft/WSL/issues/834#issuecomment-239488886). 

Inevitably (when the sad day comes), Ken Thompson's ghost is going haunt all of you in your sleep. And who wants to risk that?
