### ISSUE TITLE
0x80070002 when launching distro

### ISSUE THREAD

**Issue by laur89** [microsoft/WSL#3499]
Started using WSL yesterday, everything was working as advertised. Then broke the linux installation (ie from linux side, nothing to do with WSL), deleted distro directory (C:\distros\debian in my case), and followed same steps to reinstall, only to find it no longer working.
Note Store is disabled by the administrator, installing manually only.

* Windows build number:  [Version **10.0.16299.492**]

* What you're doing and what's happening:
Executed following commands from PowerShell (just like first time when it worked):

    - Invoke-WebRequest -Uri https://aka.ms/wsl-debian-gnulinux -OutFile debian.appx -UseBasicParsing
    - Rename-Item .\debian.appx debian.zip
    - Expand-Archive .\debian.zip 'C:\distros\debian'
    - cd C:\distros\debian\
    -  .\debian.exe

* What's wrong / what should be happening instead:
Expected bash shell prompt, instead got greeted by **Error: 0x80070002**

Refer to attached logs: [detailed_logs.zip](https://github.com/Microsoft/WSL/files/2315312/detailed_logs.zip)

Tried also disabling and re-enabling WSL, but no joy.

    PS C:\distros\debian> PowerShell Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

    FeatureName      : Microsoft-Windows-Subsystem-Linux
    DisplayName      : Windows Subsystem for Linux  
    Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
    RestartRequired  : Required
    State            : Enabled
    CustomProperties :

**Comment by benhillis** [comment]
The problem is that WSL still thinks your original distribution is installed.  Run this command and re-run debian.exe:

`wslconfig.exe /unregister Debian`

**Comment by laur89** [comment]
That was it, cheers!

I feel like easily accessible documentation is lacking on uninstallation/distro removal.
To confirm, are these steps sufficient for complete removal:

    1) delete your distro directory
    2) run wslconfig.exe /unregister <distro>

Think the first time I also had an empty directory C:\Users\laur89\debian that I deleted, but can't see it being created anymore.

**Comment by benhillis** [comment]
Good call.  @tara-raj, could you please update the offline / server installs steps with a link to https://docs.microsoft.com/en-us/windows/wsl/wsl-config#unregister-and-reinstall-a-distribution?

**Comment by alexsilva** [comment]
I'm also having this problem.
The only way I found to do the installation was to manually download the '.Appx' app for Debian from the  site [wsl-install-manual](https://docs.microsoft.com/en-us/windows/wsl/install-manual) for example, by extracting the `install.tar.gz` file.

After that is to finish the manual installation with lxrunoffline

`LxRunOffline.exe install -n Debian -f install.tar.gz -d X:\\Debian -s`

Create a sudo user (not to always start with root)
https://linuxize.com/post/how-to-create-a-sudo-user-on-debian/

Configure the `DefaultUid` key for the new user (starts as the user - 1000 ?)
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`

When the application is downloaded from the store it will be recognized as installed.

**Comment by therealkenc** [comment]
This issue went stale without a local repro, and `wslconfig.exe` has been deprecated in favor of `wsl.exe`. If the problem persists on Windows 20H2 aka 19042 (or better), please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), catching the `0x80070002` from `wsl.exe`.

**Comment by PoleG97** [comment]
I have the same problem, the difference it's that in my case it occurs at time to install the distro.
I say this because the most of solutions to try doesn't works for me... any help?

`Installing, this may take a few minutes...                                                                              
WslRegisterDistribution failed with error: 0x80070002                                                                   
Error: 0x80070002 El sistema no puede encontrar el archivo especificado.
                                                                                                                                                                        
Press any key to continue...    `
