### ISSUE TITLE
Can't start new processes after some time running

### ISSUE THREAD

**Issue by soar** [Microsoft/WSL#3500]
## Your Windows build number

**Microsoft Windows [Version 10.0.17134.81]**

## What you're doing and what's happening

After system boot all works fine. But after some time running (I have running WSL processes all the time) - running processes looks like dead and I can't start new processes. So, symtoms are:

* System uptime: more than 10 days
* Opened `ssh` sessions are dead (`Ctrl+C`/`Ctrl+D` don't work)
* Can't stop running `docker-compose`
* I can start new `bash` and only some commans inside it
* `uptime` in `bash` shows me:
	```
	12:37:48 up -24855 days, -3:-14,  0 users,  load average: 0.52, 0.58, 0.59
	```
* `ps faux`:
	```
	USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
	root         1  0.0  0.0   8304    96 ?        Ss   Sep04   0:00 /init ro
	soar        58  0.0  0.0 161156   816 ?        Ss   Sep04   0:01 gpg-agent --daemon --verbose
	root       112  0.0  0.0  14300   284 ?        Ss   Sep04   0:00 socat UNIX-LISTEN:/tmp/keeag
	soar      2552  0.0  0.0  16464  3804 ?        Ss   Sep04   1:35 tmux
	soar      2553  0.0  0.0  16676  1900 pts/1    Ss   Sep04   0:00  \_ zsh
	soar      2623  0.0  0.0  15416  2272 pts/1    S    Sep04  30:37  |   \_ htop
	soar     11155  0.0  0.0  17736  3076 pts/2    Ss   Sep05   0:00  \_ zsh
	soar     11267  0.0  0.0  17736  3076 pts/3    Ss   Sep05   0:00  \_ zsh
	soar     13177  0.0  0.0  17740  3000 pts/13   Ss   Sep06   0:00  \_ zsh
	soar     13239  0.0  0.0  11940  1484 pts/13   S    Sep06   0:00      \_ docker-compose up
	soar     13240  0.0  0.0 340608 19516 pts/13   Sl   Sep06   0:16          \_ docker-compose up
	Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
	root     16033  0.0  0.0   8304    92 tty1     Ssps:display.c:66: please report this bug
	[1]    16085 segmentation fault (core dumped)  ps fuax
	```
    initial strace [here](https://gist.github.com/soar/e792610ab01d8d79fb3953825467497f#file-ps-faux-strace) - I've tried to kill process, where it crashes, and got anothre [strace](https://gist.github.com/soar/e792610ab01d8d79fb3953825467497f#file-ps-faux-after-killing-16033-strace)
* trying to run `gedit` (strace [here](https://gist.github.com/soar/e792610ab01d8d79fb3953825467497f#file-gedit-strace)):
	```
	** (gedit:16483): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.a11y.Bus received signal 6
	GLib:ERROR:/build/glib2.0-b4FPyK/glib2.0-2.48.2/./glib/gasyncqueue.c:431:g_async_queue_pop_intern_unlocked: assertion failed: (retval || !wait || end_time > 0)
	```
* `ping` - executes successfully, but `Ctrl+C` doesn't work in it
* `mc`, `top`, `htop` - start successfully
* `ssh` client starts, but stuck on getting authorization through `socat` socket. I've tried to kill all `socat` processes, recreate socket and restart all that stuff - nothing helps.

## What's wrong / what should be happening instead

All commands should be executed successfully.

## Strace of the failing command, if applicable

Here are straces for all command above: https://gist.github.com/soar/e792610ab01d8d79fb3953825467497f

**Comment by therealkenc** [comment]
> Microsoft Windows [Version 10.0.17134.81
> ...
>  12:37:48 up -24855 days

#3252 #3434. Should be okay in 17738.
