### ISSUE TITLE
Are there some well known issues about mix using git for Windows and git in WSL?

### ISSUE THREAD

**Issue by ZYinMD** [Microsoft/WSL#3502]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17134.228

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Using git in WSL, while also using git for Windows, while also using the git plugin in Sublime Text

* What's wrong / what should be happening instead:
I get weird permission issues here and there.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

Hi, I'm sorry my description of the issue is going to be vague, because it's really hard to describe, and I assume it has been asked before, and I just hope people can point me to the former discussion.

When I mix my use of git in WSL and git for Windows and git plugin for Sublime Text (by mix I mean one command here followed by one command there), I often get all kinds of strange permission errors: fail to read file, fail to push, fail to fetch, fail to stash, etc etc. I can probably just work around it by never using git in WSL, but I'm curious, what exactly shouldn't I do?

Thanks!!

**Comment by mkarpoff** [comment]
You will definitely want to turn on permission meta data for /mnt/c or else disable git checking if the permissions change.
