### ISSUE TITLE
Auto resize window as user change Ubuntu wsl's window size

### ISSUE THREAD

**Issue by tuyenpm9** [Microsoft/WSL#3506]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 1709 (OS Build 16299.547)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
I'm using Ubuntu wsl on windows10 and ssh to an Virutal Machine running on vmware workstation installed on windows10, I run tmux with multiple sessions.
This issue happened randomly, this is reproduce steps:
1. Open Ubuntu wsl, and pin to taskbar - trying to shortcut it and choose my favor font for this Ubuntu wsl instance - this step happens ONLY one time. (Ubuntu wsl's properties -> Font -> my favor font)
2. Ubuntu wsl in normal window size (NOT open in maximum) --> now try to maximum Ubuntu wsl, switch sessions somehow try to trigger this issue, also try to minimize Ubuntu wsl to taskbar and re-open it.
3. When you open in normal mode and do some actions in 2. you may catch the issue that appears as Ubuntu wsl has problem to redraw its size to size of maximum window and minimum one.

Issue:
![redraw_issue](https://i.imgur.com/KEJa1O0.png)

* What's wrong / what should be happening instead: This is expected window, auto resize window as user change Ubuntu wsl's window size.

Expected:
![expected_window](https://i.imgur.com/BPdA8QW.png)

This is a copy of https://github.com/Microsoft/console/issues/241

**Comment by zadjii-msft** [comment]
This is definitely a console issue, I'm going to keep the main discussion in that thread.
