### ISSUE TITLE
docker service cannot be started

### ISSUE THREAD

**Issue by davidlubomirov** [Microsoft/WSL#3508]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.611]

* What you're doing and what's happening:
>$ sudo systemctl start docker
Failed to connect to bus: No such file or directory

* What's wrong / what should be happening instead:
docker service should start

I'm using Ubuntu on Windows:

>$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by therealkenc** [comment]
Error is #1579.  Hangout for Docker is #2291.

**Comment by davidlubomirov** [comment]
None of these posts helped resolving the issue!

**Comment by therealkenc** [comment]
Correct. Once (if) `sudo systemctl start docker` is working, the status of those issues will change from the current state of open to closed.
