### ISSUE TITLE
modprobe: FATAL: Module nbd not found in directory /lib/modules/4.4.0-17134-Microsoft

### ISSUE THREAD

**Issue by rudoletz** [Microsoft/WSL#3510]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information: 

* Your Windows build number:  Microsoft Windows [Version 10.0.17134.112]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

$ sudo modprobe nbd max_part=8

* What's wrong / what should be happening instead:

Got the following error message

modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module nbd not found in directory /lib/modules/4.4.0-17134-Microsoft

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

$ sudo strace modprobe nbd max_part=8

execve("/sbin/modprobe", ["modprobe", "nbd", "max_part=8"], [/* 14 vars */]) = 0
brk(NULL)                               = 0x7fffefcad000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc8d8100000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=23160, ...}) = 0
mmap(NULL, 23160, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fc8d8104000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\4\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1689360, ...}) = 0
mmap(NULL, 3795296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc8d7a60000
mprotect(0x7fc8d7bf5000, 2097152, PROT_NONE) = 0
mmap(0x7fc8d7df5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x195000) = 0x7fc8d7df5000
mmap(0x7fc8d7dfb000, 14688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fc8d7dfb000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc8d80f0000
arch_prctl(ARCH_SET_FS, 0x7fc8d80f0700) = 0
mprotect(0x7fc8d7df5000, 16384, PROT_READ) = 0
mprotect(0x7fc8d8422000, 8192, PROT_READ) = 0
mprotect(0x7fc8d8023000, 4096, PROT_READ) = 0
munmap(0x7fc8d8104000, 23160)           = 0
brk(NULL)                               = 0x7fffefcad000
brk(0x7fffefcce000)                     = 0x7fffefcce000
uname({sysname="Linux", nodename="W10LT-PF0TRV5E", ...}) = 0
stat("/etc/modprobe.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/modprobe.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents(3, /* 3 entries */, 32768)     = 80
newfstatat(3, "mdadm.conf", {st_mode=S_IFREG|0644, st_size=379, ...}, 0) = 0
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
stat("/run/modprobe.d", 0x7ffff7423ce0) = -1 ENOENT (No such file or directory)
stat("/lib/modprobe.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/lib/modprobe.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents(3, /* 4 entries */, 32768)     = 120
newfstatat(3, "aliases.conf", {st_mode=S_IFREG|0644, st_size=655, ...}, 0) = 0
newfstatat(3, "fbdev-blacklist.conf", {st_mode=S_IFREG|0644, st_size=390, ...}, 0) = 0
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
open("/lib/modprobe.d/aliases.conf", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fstat(3, {st_mode=S_IFREG|0644, st_size=655, ...}) = 0
read(3, "# These are the standard aliases"..., 4096) = 655
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/lib/modprobe.d/fbdev-blacklist.conf", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fstat(3, {st_mode=S_IFREG|0644, st_size=390, ...}) = 0
read(3, "# This file blacklists most old-"..., 4096) = 390
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/modprobe.d/mdadm.conf", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_GETFL)                       = 0 (flags O_RDONLY)
fstat(3, {st_mode=S_IFREG|0644, st_size=379, ...}) = 0
read(3, "# mdadm module configuration fil"..., 4096) = 379
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/lib/modules/4.4.0-17134-Microsoft/modules.softdep", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/proc/cmdline", O_RDONLY|O_CLOEXEC) = 3
read(3, "BOOT_IMAGE=/kernel init=/init ro"..., 4095) = 33
read(3, "", 4062)                       = 0
close(3)                                = 0
open("/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "modprobe: ERROR: ../libkmod/libk"..., 143modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
) = 143
open("/lib/modules/4.4.0-17134-Microsoft/modules.alias.bin", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "modprobe: FATAL: Module nbd not "..., 86modprobe: FATAL: Module nbd not found in directory /lib/modules/4.4.0-17134-Microsoft
) = 86
exit_group(1)                           = ?
+++ exited with 1 +++

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
#1893
