### ISSUE TITLE
Another 1803 fiasco

### ISSUE THREAD

**Issue by n4af** [Microsoft/WSL#3511]
After months trying to get 1803 installed (literally), I finally bought a dell 790 with 1803 installed-mistake.
I have a lot of servers that I need to control via WSL.
The install from MS store stares at me on 'get'. The manual download brings down the .appx file (tried both Ubuntu and Debian). But clicking on the appx ? NADA.
(Yes, Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux was executed from admin power shell)

OK, then, how about download from powershell ? Nope. running Ubuntu -nil.
Of course, no Ubuntu or Debian in launch.

I was a heavy user of WSL pre-1803.

I am so frustrated !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rodrymbo** [comment]
It does sound frustrating...

Your description confused me... you're following the instructions [in the docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10), right?

I wonder what could be different between your experience and all the others who aren't having problems...

**Comment by n4af** [comment]
Tks ur response.
I found event log showed faults in AppInstaller. No google match.

BUT, also found a way to do the appx install via PowerShell cmd (sorry not
remember the specific cmd) that worked perfectly.

The trick was NOT to use AppInstaller. So I now have Ubuntu running a-ok.
------------
Faulting application name: AppInstaller.exe, version: 1.0.1804.2001, time
stamp: 0x5ac2c1fe
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17134.81, time
stamp: 0x4f4899f8
Exception code: 0xc000027b
Fault offset: 0x00000000006a4e02
Faulting process id: 0x1b0
Faulting application start time: 0x01d4411eb9bb6f45
Faulting application path: C:\Program
Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.20921.0_x64__8wekyb3d8bbwe\AppInstaller.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 92380a6e-d5df-4d6a-a32a-84e3192b894a
Faulting package full name:
Microsoft.DesktopAppInstaller_1.0.20921.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Tks, Howard
