### ISSUE TITLE
Ubuntu 18 - Error with file system commands: Function not implemented

### ISSUE THREAD

**Issue by vagnercsouza** [microsoft/WSL#3517]
* Your Windows build number:
**Microsoft Windows [Version 10.0.17134.165]**

* What you're doing and what's happening:
**When I try to create a directory inside the mounted windows volume (/c), it is created but this error is showed:** 
![image](https://user-images.githubusercontent.com/6453240/44931587-85d67b80-ad38-11e8-87b8-d4d71b98a008.png)
**The problem also happens with rm, but the dir is not removed:**
![image](https://user-images.githubusercontent.com/6453240/44931620-b0283900-ad38-11e8-8bc5-d317ab4f14a3.png)

* What's wrong / what should be happening instead:
**Even though the directory is created, this error stop the execution of some scripts (like yarn, composer, etc).**

* Strace of the failing command, if applicable:
[Strace on Gist](https://gist.github.com/vagnercsouza/206f4b8086e5387bf3dfb8df924fe419)

* Additional information:
The problem is happening on a notebook configured in an Active Directory domain with Group Policies that limits Windows Update and runs Kaspersky Endpoint Security.
The Windows Store don't work because of GPO (I've installed WSL before configure the computer on the AD, but the problem was happening even before configure it).
It only happens on the mounted windows volume, inside WSL it works fine.

**Comment by therealkenc** [comment]
```
fstat(3, {st_mode=S_IFREG|0644, st_size=199772, ...}) = 0
mmap(NULL, 199772, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb5a405b000
close(3)                                = 0
mkdir("bar2", 0777)                     = -1 ENOSYS (Function not implemented)
```

**Comment by vagnercsouza** [comment]
@therealkenc I don't know what those lines means, can you give more details? Thanks.

**Comment by therealkenc** [comment]
Just pulled out the relevant lines from your `strace` log out so it lights up in search and saves others from doing a redirect. Nothing for you to do here. To sum what it means in a detailed technical way.... 

"That's very weird".

**Comment by vagnercsouza** [comment]
Got it. I've put some more information on the issue about the computer where the problem is happening.

**Comment by benhillis** [comment]
@therealkenc - looking through our code it looks lik ENOSYS can be returned if some NT operations fail with STATUS_NOT_IMPLEMENTED, which doesn't seem right. Likely a filesystem filter driver is failing an operation.

**Comment by Zophren** [comment]
Hello,

The same here, since i have installed Kaspersky Endpoint security, it's impossible to do rm ...

```
login@DESKTOP-WS:/c/temp  $ rm license.txt
rm: impossible de supprimer 'license.txt': Fonction non implantée
```

**Comment by vnluc** [comment]
I am getting same issue on Windows 10 and dont know where to start diagnose it.

```
$ rm hello.txt
rm: cannot remove 'hello.txt': Function not implemented
```
So I try strace command and get this:

```
unlinkat(AT_FDCWD, "hello.txt", 0)      = -1 ENOSYS (Function not implemented)
openat(AT_FDCWD, "/usr/share/locale/C.UTF-8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C.utf8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/C.UTF-8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/C.utf8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/C/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "rm: ", 4rm: )                     = 4
write(2, "cannot remove 'hello.txt'", 25cannot remove 'hello.txt') = 25
```

I am not sure what is the cause??? Maybe   'unlinkat' is not implemented or some library missing??

`openat(AT_FDCWD, "/usr/share/locale/C.UTF-8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)`

Hope someone could help point out...
