### ISSUE TITLE
There seems to be some serious IO bottleneck happening with windows...

### ISSUE THREAD

**Issue by TheDeepNate** [Microsoft/WSL#3518]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Version	10.0.17746 Build 17746

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Run the commands to install composer and laravel (for this demo) or any other package

```
sudo apt-get update && sudo apt-get upgrade
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php-fpm php-mysql php7.2-cli php7.2-curl php7.2-mbstring php7.2-xml php7.2-zip php7.2-intl curl git unzip php-cli
sudo apt install composer 
composer global require "laravel/installer"
```

Add the composer path to your ~/.bashrc

Run ```laravel new blog```

* What's wrong / what should be happening instead:

WSL:

<img src="https://i.imgur.com/JlnvdZl.gif">

Hyper-v Ubuntu:

<img src="https://i.stack.imgur.com/RypRV.gif">

As you can see, the ubuntu version is at least 4/5 times faster, I have even disabled windows defender on my machine, which sped it up, but nowhere near the speed of what it should be (like the hyper-v ubuntu)

**Comment by therealkenc** [comment]
#873
