### ISSUE TITLE
Can't launch distros in SD cards

### ISSUE THREAD

**Issue by DDoSolitary** [Microsoft/WSL#3519]
One of my users of the LxRunOffline project reported that he got 0x80070057 error when launching distros that are installed to an SD card and I guess it also applies to distros installed by WslRegisterDistribution.

**Comment by DDoSolitary** [comment]
[logs.zip](https://github.com/Microsoft/WSL/files/2342919/logs.zip)

**Comment by benhillis** [comment]
SD cards do not support stable GUIDs, which we require for the root filesystem. Installing to an SD card is not currently a supported scenario.

**Comment by Biswa96** [comment]
Why does LxCore Driver need a "stable" GUID of that installation volume? `mountvol` command can show the GUID of that SD card. Will there be any difference between [external SD card reader](https://www.amazon.com/s/field-keywords=sd+card+reader) and in-built SD card slot?

**Comment by therealkenc** [comment]
> Why does LxCore Driver need a "stable" GUID

#449 ([message](https://github.com/Microsoft/WSL/issues/449#issuecomment-346117044)). Nipping to keep discussion in one place.

**Comment by Biswa96** [comment]
@therealkenc In my opinion, this issue isn't related with #449. Moving WSL installation is already supported but in a special way. Hold tight, programming idea ahead!

Look carefully how `wslconfig /upgrade` command works (cough). It completely MOVES the Linux folders from `rootfs` to `wslfs` directory. So what does it do? The strings, `rootfs` and `wslfs`, are stored as `struct _UNICODE_STRING` which are passed to `struct _OBJECT_ATTRIBUTES.ObjectName` member. Then these `ObjectAttributes` variables are passed to `NtCreateFile()` or `NtOpenFile()`.

Both of the cases the `OBJECT_ATTRIBUTES.RootHandle` (comes from `CreateFile()`) are same. So my assumption is that, if someone change the base path or RootHandle (where WSL installed) then WSL installation can easily be moved.

Hence #449 is a user mode issue and this is a kernel mode issue (where LxCore wants stable GUID).
