### ISSUE TITLE
I can't launch MySQL

### ISSUE THREAD

**Issue by DemoCrazer** [Microsoft/WSL#3520]
**Please fill out the below information:**
* Your Windows build number:  17134.228

* What you're doing and what's happening:
![pic1](https://user-images.githubusercontent.com/26616056/44952677-581c3e80-aec0-11e8-89f1-633e803c3781.PNG)
![pic2](https://user-images.githubusercontent.com/26616056/44952679-5e121f80-aec0-11e8-8280-d8054d2ec5ce.PNG)

* What's wrong / what should be happening instead:
`sudo service mysql --full-restart`
If I try to launch MySQL, it just fails. Also MySQL doesn't write any error log files so I can't figure out what is the problem. This issue doesn't occur in native linux, so I report it in here.
I'm using Ubuntu 18.04 WSL and following is the content of `my.cnf` file.
```
#
# The MySQL database server configuration file.
#
# You can copy this to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/sever-system-variables.html

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

[client]

[mysqld]
#
# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M
#
# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
# log_bin
#
# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M

# read_rnd_buffer_size = 2M
datadir = /var/lib/mysql
socket = /var/run/mysqld/mysqld.sock
user = mysql

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links = 0

# Recommended in standard MySQL setup
sql_mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
character-set-client-handshake = FALSE
init_connect = "SET collation_connection = utf8_general_ci"
init_connect = "SET NAMES utf8"
character-set-server = utf8
collation-server = utf8_general_ci
log_error = /var/log/mysql/error.log
general_log_file = /var/log/mysql/mysql.log
general_log = 1

[mysqldump]

[mysql]

[mysqld_safe]
log-error = /var/log/mysqld.log
pid-file = /var/run/mysqld/mysqld.pid
```

* What I've tried but failed:
`sudo apt -y purge mysql-server` / `sudo apt -y autoremove` / `sudo apt -y install mysql-server`
`sudo apt -y --reinstall install mysql-server`

**Comment by alekseymvt** [comment]
Check user:group for /var/lib/mysql

**Comment by JacobDB** [comment]
I'm having issues getting `mysql-server` to install on 18.04, not sure if this is related or not.

**Comment by therealkenc** [comment]
> If I try to launch MySQL, it just fails.

There isn't enough to go on here to give any kind of constructive feedback. Feel encouraged to re-file following CONTRIBUTING.md. You can also see if anyone finding success in #2113 can help, or even better a MySQL group or [superuser](https://superuser.com/) to track the diverge.

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/158497251-951efec8-c2cf-4cea-8922-bac8af322a5e.png)

I have the same question
