### ISSUE TITLE
Nmap shows unnecessary error in result

### ISSUE THREAD

**Issue by R1w** [Microsoft/WSL#3521]
nmap/bionic,now 7.60-1ubuntu5 amd64
Running this command "nmap -sV --script=banner A.A.A.A -A" and in result there are hundreds of unnecessary line of error as shows in result:

Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
NSOCK ERROR [0.8960s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
NSOCK ERROR [0.8970s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
NSOCK ERROR [0.8970s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
NSOCK ERROR [36.4930s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
NSOCK ERROR [36.5040s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
NSOCK ERROR [36.5070s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
NSOCK ERROR [36.5100s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
NSOCK ERROR [36.5130s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)

**Comment by therealkenc** [comment]
#3440 #1349
