### ISSUE TITLE
Unable to get Fastboot connection

### ISSUE THREAD

**Issue by zeburek** [Microsoft/WSL#3524]
* Your Windows build number:
10.0.17134.228 

* What you're doing and what's happening:
`sudo apt install android-sdk`
Connect Android device in Fastboot mode to PC
`fastboot devices` - nothing
`sudo fastboot devices` - nothing

* What's wrong / what should be happening instead:
There should be displayed a device ID and it's name. The same command is perfectly working on Windows shell if fastboot is installed.

**Comment by tinybarks** [comment]
As far as I know, WSL does not support accessing USB devices that are not storage (mountable in Windows, like USB drives). See #412.

**Comment by therealkenc** [comment]
Template deleted natch, but probably closer to #2195

**Comment by zeburek** [comment]
@therealkenc closer, but not the same - fastboot is not working through ADB server 
Seems that the problem is in no USB support
