### ISSUE TITLE
How can I install other distributions (SuSE, Kubuntu)?

### ISSUE THREAD

**Issue by creibens** [Microsoft/WSL#3527]
Is there a way to install other distributions than the ones listed? My favourite, Kubuntu, is not shown on the list, nor is SuSE.

**Comment by tara-raj** [comment]
The short answer is, yes. You can sideload a distro using the instructions in [this project](https://github.com/Microsoft/WSL-distroLauncher)

**Comment by Biswa96** [comment]
Or install KDE desktop environment in Ubuntu i.e. Ubuntu + KDE = Kubuntu

**Comment by therealkenc** [comment]
This is actually a weird one because of the distros asks. Kubuntu is Ubuntu (is Debian, _to a first order_, for the lion's share of packages applicable to WSL). OpenSUSE is in the store [here](https://www.microsoft.com/en-ca/p/opensuse-leap-42/9njvjts82tjx?activetab=pivot%3aoverviewtab).
