### ISSUE TITLE
Unable to update repo's

### ISSUE THREAD

**Issue by bkr32** [Microsoft/WSL#3528]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.254]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
apt update/upgrade & git pull

* What's wrong / what should be happening instead:
i am unable to update or install using apt on both my kali and ubuntu installations and get this error back

```
Err:4 http://security.ubuntu.com/ubuntu xenial-security Release
  Connection failed [IP: 91.189.91.23 80]

E: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

fatal: unable to access 'https://github.com///': gnutls_handshake() failed: Error in the push function.

W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  Connection failed [IP: 192.99.200.113 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by wh75er** [comment]
same issue, dont know how to solve it

**Comment by bkr32** [comment]
if your running kaspersky, that's the problem, i found literally no way of unblocking it when the issue popped up so removed it entirely

**Comment by therealkenc** [comment]
dupping #3647 for lack
