### ISSUE TITLE
Is this SSH workaround OK to use?

### ISSUE THREAD

**Issue by AndrewZamora** [Microsoft/WSL#3530]
## Build Number: 
`Microsoft Windows [Version 10.0.17134.228]`
## My Goal
I'm trying to use SSH keys in  `/mnt/c/Users/MY_USER_NAME/.ssh`  to authenticate with GitHub. 
I would also like to know if I should be using the same SSH in Windows and WSL or if I should be using two separate keys. 
## What I'm doing: 
I created a link to `~/.ssh` with this command `ln -s /mnt/c/Users/MY_USER_NAME/.ssh ~/.ssh`.
Then I tried to authenticate with GitHub with ` ssh -T git@github.com`. I got this response in the command line:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0555 for '/home/MY_USER_NAME/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/MY_USER_NAME/.ssh/id_rsa": bad permissions
Permission denied (publickey).
```
In response to this I removed `~/.ssh` with `rm -r .ssh` and then copied `/mnt/c/Users/MY_USER_NAME/.ssh` and pasted it in `~/` with ` cp -R /mnt/c/Users/MY_USER_NAME/.ssh` 
Then I changed permissions with 'sudo chmod 400 ~/.ssh/id_rsa' and I was able to authenticate:
```
You've successfully authenticated, but GitHub does not provide shell access.
``` 
## What's wrong 
I understand that this issue has been mentioned in #3181 but I'm still not sure if this is what I'm suppose to do or if this is a good workaround.

**Comment by ajostergaard** [comment]
You can either generate new keys for your new environment or, if you choose to, copy the keys as you did. It is up to you if you want to have separate keys or copy the key. If the two environments were actually separate devices I would recommend separate keys but as they are one there's really not much point as if one is compromised both are compromised.

If this answers your question please don't forget to close the issue.
