### ISSUE TITLE
Starting from powershell and escaping spaces

### ISSUE THREAD

**Issue by rogalmic** [Microsoft/WSL#3533]
To reproduce, run this in powershell 5.1.17134.228 (1.0 folder):
```
PS C:\Users\billc> bash -c 'echo "test    spaces"'
```
result (should be `test    spaces`):
```
test
```

Same thing works fine in cmd:
```
C:\Users\billc>bash -c 'echo "test    spaces"'
test    spaces
```

**Comment by therealkenc** [comment]
`bash.exe` is depreciated in the Win 10 build you are running, but setting that aside, `powershell.exe` and `cmd.exe` have different string quoting semantics. Newspeak is:
```
PS C:\Users\ken> wsl.exe bash -c "echo 'test      spaces'"
test      spaces
```
Or, in PS only (but not CMD which will eat the whitspace):
```
PS C:\Users\ken> wsl bash -c 'echo ''test     spaces'''
test      spaces
```
You'll get better service on this one in PS/CMD forums, but I'll let it percolate here for a short bit.

**Comment by rogalmic** [comment]
OK, thank you for this answer! Please close this issue when needed.
