### ISSUE TITLE
I downloaded the distro using PowerShell but how to install it?

### ISSUE THREAD

**Issue by swun90** [Microsoft/WSL#3538]
It's a loop.
To install the distro, as the web [MS wsl install](https://docs.microsoft.com/en-us/windows/wsl/install-win10)  says,  I need to use the powershell to download, as the web [install manual](https://docs.microsoft.com/en-us/windows/wsl/install-manual)  says.
So I downloaded the distro, but the 2nd web told me to follow instructions in the 1st web, which told me to go to the 2nd web.

IT IS A **LOOP**! How am I supposed to install the distro? The command window displays the error code 0x80070003, which cannot be fixed by the MS website suggestions.

P.S. I cannot install from the microsoft store. It says that `windows update` has been forbidden which is NOT. And the error code is 0x80070422, but the instructions to fix this error just didn't work.

**Comment by Statici** [comment]
So I came here with the same issue, then said screw it and just double-clicked on the downloaded item. It's installing right now.

**Comment by swun90** [comment]
> So I came here with the same issue, then said screw it and just double-clicked on the downloaded item. It's installing right now.

No. It's OK if you just want the ubuntu to run there.
But since I have a SSD and a HDD, and the installer is downloaded in the HDD but I want to run it in the SSD. I thought it was an installer, but it actually ran just in the HDD.
I deleted it cause it couldn't be uninstalled. Too bad I cannot do it now.

**Comment by sml156** [comment]
> 
> 
> > So I came here with the same issue, then said screw it and just double-clicked on the downloaded item. It's installing right now.
> 
> No. It's OK if you just want the ubuntu to run there.
> But since I have a SSD and a HDD, and the installer is downloaded in the HDD but I want to run it in the SSD. I thought it was an installer, but it actually ran just in the HDD.
> I deleted it cause it couldn't be uninstalled. Too bad I cannot do it now.

It will be installed in *./user ./something./ something *./appdata folder unless you know some kinda voodoo tricks, maybe even a couple of more something something apdata.

This is a beta test as far as I know for Microsoft, Although it does have a little polish on it  -- it is far from running Linux OS natively on your Win 10 box, Unless of course you do what most Win 10 people do and run Linux in a virtual machine.

**Comment by benhillis** [comment]
@tara-raj - Yeah looks like th manual instructions are missing the powershell add-appx package command.  Can you take a look?
