### ISSUE TITLE
WSL inherits Windows incompatible environment variables

### ISSUE THREAD

**Issue by Foadsf** [Microsoft/WSL#3540]
* **Windows build number:**  `Microsoft Windows [Version 10.0.15063]`

* **What you're doing and what's happening:**  was trying to compile OpenFOAM on WSL. first running `source ..../bashrc`

* **What's wrong:** receiving the error: 

> bash: eval: line 38: syntax error near unexpected token `('

plus the whole list of Windows environment variables printed multiple times.

* **What should be happening instead:**  This weird message should have been printed instead:

> ... incorrect platform, or not yet compiled?

* **Solution:** WSL shouldn't inherit the Windows environment variables directly but parse them first. a grep/awk/sed command could be constructed to find all the incompatible terms, including spaces and parenthesis for example, and put quotation marks around them. I have explained a workaround [here](https://www.reddit.com/r/techsupport/comments/9fr19i/in_windows_in_which_file_path_values_have_been/).

**Comment by Foadsf** [comment]
@benhillis I believe parentheses are. am I wrong?

**Comment by benhillis** [comment]
The paren is immediately preceded by a space. Neither are illegal characters in a path. Can you paste the lines from the script or makefile where it's failing?

**Comment by Foadsf** [comment]
Here the link to the bashrc : 
https://github.com/OpenFOAM/OpenFOAM-5.x/blob/master/etc/bashrc

**Comment by Foadsf** [comment]
to reproduce this error, download OpenFOAM source from [here](https://sourceforge.net/projects/openfoamplus/files/v1806/OpenFOAM-v1806.tgz) and follow the instructions [here](https://www.openfoam.com/download/install-source.php) to compile.

**Comment by therealkenc** [comment]
The build fails on Real Linux too. Do an `export PATH=$PATH:"foo bar/(baz)"` before sourcing `.../etc/bashrc` and you'll get the same error. The problem isn't spaces, it's the parentheses. The bug is in one of the `.../etc/config.sh/functions` shell scripts but that's as far as I tracked it. Your options are (a) set your `$PATH` to something short and sweet before sourcing `.../etc/bashrc` or (b) find and fix the bug in the script.

**Comment by Foadsf** [comment]
@therealkenc I don't think so. The build is ok. This is just a false warning. I have built this today 3 times. 2 times on WSL and once on Ubuntu. What were your steps leading to a failed build?

**Comment by therealkenc** [comment]
> The [emph mine] **build** is ok. 

Right; I was sloppy with the word "build" there. The script (which is part of the "build" instructions) fails in the same way on Real Linux. If it is a soft fail so much the better.
