### ISSUE TITLE
HAProxy can't start

### ISSUE THREAD

**Issue by josephapg** [Microsoft/WSL#3541]
Windows build number: 10.0.17134.285
Distro: Ubuntu 18.04.1 LTS

Installed HAProxy 1.8.13 from vbernat's ppa and here's what happened when I tried to start it:
```
[WARNING]: Failed to get the default value of TCP_MAXSEG
[WARNING]: Failed to get the default value of TCP_MAXSEG for IPv6
[ALERT]: Starting frontend http: cannot bind socket [0.0.0.0:80]
[ALERT]: Starting frontend https: cannot bind socket [0.0.0.0:443]
```

`netstat -anp` shows no processes listening on port 80 and 443.

**Comment by therealkenc** [comment]
You deleted the [template](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md). Note second sentence.

> cannot bind socket [0.0.0.0:443]

That port is open in in Windows and thus can't be bound. I assume port 80 is too, but there is no ([straightforward](https://github.com/Microsoft/WSL/issues/764#issuecomment-344812535)) way to not bind 443 in windows.

> [WARNING]: Failed to get the default value of TCP_MAXSEG

An `strace` would show the `setsockopt(2)` failing, but it it looks like a soft fail. Hasn't been reported before AFAIK. Suppose this issue can be the landing zone for that.

> netstat -anp shows no processes listening on port 80 and 443.

#2249. From the CMD prompt do `netstat.exe -an | find.exe "443"`

**Comment by josephapg** [comment]
Hi, @therealkenc!

Somehow it works after I did a reset from apps & features.

> The TCP_MAXSEG warning can probably be ignored.

Yes, you're correct. Now it works even with that warning.

Thanks for your help!
