### ISSUE TITLE
Provide method to obtain registered path in `Wslapi.h`

### ISSUE THREAD

**Issue by abelsromero** [Microsoft/WSL#3543]
Similarly to https://github.com/Microsoft/WSL/issues/3515 I'd like to know the path where a distribution is installed, but in my case using the C api
The API provides methods to register, unregister and check if a distro is registrered ([ref](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/wslapi/)) , but it does not provide any method to obtain the path with which it was registered.

I am checking a custom launcher and I found the following behavior:
- if the rootfs is manually moved after installation, calling `WslLaunchInteractive` prints `Error: 0x80070002` and waits until the user presses some key to continue executing and return control to the calling method.

So, I'd like to be able to obtain the path to validate if this exists before calling `WslLaunchInteractive`.
Alternatively, if WslLaunchInteractive did not print and wait, that would also be nice.

**Comment by Biswa96** [comment]
Possible ways:
1. From registry.
2. From COM interface in LxssSession.
3. From IApplicationData interface in WinRT.

But bad news all are undocumented and prone to changed.

**Comment by abelsromero** [comment]
thanks @Biswa96!

I just found out about the registry option and already exploring that 👍, this is more a request for the maintenance team. I think that for consistency the C API should provide that option.

**Comment by therealkenc** [comment]
This is dupe #3515 ([message](https://github.com/Microsoft/WSL/issues/3515#issuecomment-417411525)) and #449.

**Comment by abelsromero** [comment]
I honestly struggle to see how this is a duplicate.
* #3515 requests for documentation
* #449 is about moving an existing installation
* this is about adding a new method to the C library.

If this repo is not the right place to report feature requests for C lib please let me know where to go.
