### ISSUE TITLE
Missing /dev/full

### ISSUE THREAD

**Issue by alexlarsson** [microsoft/WSL#3547]
I'm trying to make flatpak/bubblewrap work with WSL, and one of the issues I found is that /dev/full is missing.

I have a workaround for this in the wip/WSL bubblewrap branch here: 
https://github.com/projectatomic/bubblewrap/commit/37cba1851b8420b1fc73e089643ad9c49a1d8f25
But it would be nice if it was just there.

**Comment by SRGOM** [comment]
Thank you, Alex for your work. It's nice to see you treat WSL as a first class "Linux" platform.

**Comment by tara-raj** [comment]
Thanks for submitting this issue. We're currently working on a large body of work for WSL that will provide a fix for this. Will update this here when that fix hits Insiders Builds
