### ISSUE TITLE
Can't install the git PPA in WSL?

### ISSUE THREAD

**Issue by Ncage1974** [Microsoft/WSL#3557]
Microsoft Windows [Version 10.0.17134.286]
Ubuntu 18.04 from the Windows Store

Trying to add the git PPA:

```
sudo add-apt-repository ppa:git-core/ppa
Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
ERROR: '~git-core' user or team does not exist.
```

I'm doing this behind a corporate proxy. I thought it might have been related to that. I tried to add the proxy to WSL (HTTP & HTTPS) & tested wget to make sure its working correctly and its working fine (i can actually see it hitting the proxy)

```
sudo wget http://site.com
sudo wget https://site.com

```

**Comment by SRGOM** [comment]
Are you sure about the ~ sign? Try wrapping the entire string inside single quotes. In any way this is 99.99% a user space issue.

**Comment by therealkenc** [comment]
> Are you sure about the ~ sign?

Nah that's "normal". The URL is `https://launchpad.net/~git-core/`. Right about it being 99.99% likely a userspace problem though. Something like [this](https://askubuntu.com/questions/724224/cant-add-ppa-on-ubuntu-15-10-user-or-team-does-not-exist) (which is no way authoritative just my first Google hit).

**Comment by SRGOM** [comment]
@therealkenc got it, thanks.

OP, 
Please ignore my suggestion of using single quotes, I assumed you were manually entering the tilde, I didn't read your command carefully.
