### ISSUE TITLE
Exclamation marks get expanded

### ISSUE THREAD

**Issue by sguillia** [Microsoft/WSL#3558]
* Windows build number:

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:

I want to type some specific text in the WSL console.
The text is `!git ls`.

Steps to reproduce:
- Open WSL
- Type `!git ls`
- As soon as you press the space bar, the exlamation mark gets expanded

Notes:
- The exclamation mark is a special symbol in most shells
- I assume you have at least one command starting with `git` in your history

As a workaround, I could type `git ls` then move the cursor left and put an exclamation mark. Or I could put quotes around what I want to type, then remove the quotes. But this would not work when pasting text.

* What's wrong / what should be happening instead:

This is a bug. I should be able to edit the line until the very moment when I press enter (or tab). Before that moment, everything is draft.

**Comment by therealkenc** [comment]
No special action happens at the space after the '`t`' in `!git` here. I suspect something was lost in translation.

**Comment by sguillia** [comment]
What do you mean by translation?

Do you have any line in history that begins with git?

How can I help you reproduce since the bug happens only on my side?

**Comment by therealkenc** [comment]
> How can I help you reproduce since the bug happens only on my side?

You could try the Spring 2018 (aka 1803 aka 17134) and Ubuntu 18.04 from the MSFT Store, which might perturb enough variables and make the problem go away. The upgrade itself won't change anything mind, but starting over might. The greater hope is that someone else will see it and try to guess the reproduction steps based on your OP. The space character has no special powers in GNU bash.

**Comment by therealkenc** [comment]
Wild ass guess attempt: You aren't running `bash`, you are running `zsh`and have magic-space expanded, like [this](https://superuser.com/questions/926266/how-to-prevent-zsh-from-expanding-history-when-space-bar-is-pressed).

**Comment by sguillia** [comment]
Well seen, this did the trick:

    set +o histexpand

I didn't know that this option existed and I never saw it enabled by default.

Sorry! Thanks for your help. This issue is solved.

**Comment by therealkenc** [comment]
> Sorry! Thanks for your help.

No worries. You can be forgiven for not knowing the option existed because neither did I (or my memory of the feature was lost in the great purge). Glad it worked out.
