### ISSUE TITLE
Unable to mount ext4 raw img on loop device

### ISSUE THREAD

**Issue by rupansh** [Microsoft/WSL#3559]
* Your Windows build number: 10.0.17134.285

* What you're doing and what's happening:  sudo mount -t ext4 -o loop sysp.img output

* What's wrong / what should be happening instead: mount: output: mount failed: Unknown error -1
however, In my linux machine, the same image mounts fine

I am specifically porting Android ROMs which usually requires modification in the system.img. I do dual boot with Ubuntu 16.04 but I find it annoying to switch as most of my important files are in Windows.

**Comment by therealkenc** [comment]
#1691
