### ISSUE TITLE
Initializing an open TCP connection (socket) hangs

### ISSUE THREAD

**Issue by girng** [Microsoft/WSL#3560]
Hello WSL community! I ran into an issue that caused great pain and distress towards me and other users.
We finally figured it out, and it's definitely an issue with WSL. 
https://github.com/crystal-lang/crystal/issues/6759#issuecomment-423558890

 I tried searching for other TCP socket connection issues here but with no luck.

For some reason, when you are connecting to a tcp socket, WSL is not reporting connection refused, or connection timeout.  **It does work on native ubuntu/debian**, just not on WSL

You can see this example in the original post.
How to replicate it on WSL using crystal lang:
```
require "socket"
puts "Waiting for the server to become connectable.."
check = TCPSocket.new("0.0.0.0", 9300)
```

It will hang there, indefinitely. What you are supposed to see:
![image](https://user-images.githubusercontent.com/36117592/45898538-1bd95100-bd8f-11e8-819c-59832e7b8bf1.png)

If you need me to test any other stuff lmk!

**Comment by therealkenc** [comment]
This one was lost in the noise for lack of repro but wasn't tagged as such. Please re-file following CONTRIBUTING.md and the issue template that was deleted.
