### ISSUE TITLE
Non-UTF-8 filenames silently use replacement character.

### ISSUE THREAD

**Issue by Random832** [microsoft/WSL#3564]
When attempting to write a filename containing invalid UTF-8 bytes, it silently interprets the bytes as the replacement character.

e.g. echo x > $'\x80.txt'

All such filenames are treated as identical, and a directory listing returns the filename as \xef\xbf\xbd.txt

Incidentally, filenames created in Windows with invalid surrogates are also returned in directory listings as the replacement character, and the file cannot be accessed from WSL. I don't know if this should be considered as a separate issue or not.

On a real Linux system, in at least one scenario where allowing the filename to be round-tripped is impractical (VFAT filesystem mounted with option iocharset=utf8 - I have not investigated NTFS or CIFS), attempting to create such a file results in an error status [EINVAL] from open(2).

**Comment by DHowett-MSFT** [comment]
@therealkenc 
![image](https://user-images.githubusercontent.com/14316954/46044540-e8b8f980-c0cf-11e8-975d-1209b7a5a6b1.png)

**Comment by therealkenc** [comment]
> @therealkenc
> [pretty screencap]

Well that's awkward. You didn't provide your version number, distro, or an `strace` log per the deleted issue template either. But alright. I think I know what is happening here. Dropping the need-repro tag on house rules.

> Incidentally, filenames created in Windows with invalid surrogates are also returned in directory listings as the replacement character...I don't know if this should be considered as a separate issue or not.

That's not a bad question. In the context I think that part is "correct", given what is being returned by `getdents()`. GNU `ls` and the Windows Console are just following orders. If you do the same `ls` with (say) `xterm` you'll get a similar funky character displayed.

**Comment by DHowett-MSFT** [comment]
@therealkenc Sorry :smile:
For my repro: 17763, 18243. Distribution-agnostic. The invalid character is making it out through the system call:

```
$ strace touch $'\x80'
openat(AT_FDCWD, "\200", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 3
                   ^^^
...
$ strace touch $'\x81'
openat(AT_FDCWD, "\201", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 3
                   ^^^
```

**Comment by DHowett-MSFT** [comment]
(and if you actually have a file called `\x80.txt`, lxss returns it from getdents as `\xC2\x80`)
