### ISSUE TITLE
etc/hosts not being used

### ISSUE THREAD

**Issue by TheDeepNate** [Microsoft/WSL#3565]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Version	10.0.17134 Build 17134

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am adding a host to the ```etc/hosts``` file

    127.0.0.1 demo.test

* What's wrong / what should be happening instead:

My machine isn't using the host file under /etc/hosts, it only works if I edit the actual windows hosts file

**Comment by therealkenc** [comment]
`demo.test` resolves here when added to my `/etc/hosts`. WSL (or more accurately glibc) is not aware of the existence of the Windows host file. I can't quite guess what might be happening for you here, but note that `/etc/hosts` gets blown away by WSL's `init` process on instantiation (per comment in the file).
