### ISSUE TITLE
why the $PS1 prompt can't show on uwp

### ISSUE THREAD

**Issue by unihon** [Microsoft/WSL#3566]
- system:
win10-1803
debian(wsl-uwp)
- problem:
why the $PS1 prompt can't show on uwp,but is work on other conslole like cmd\ps\xshell...
![image](https://user-images.githubusercontent.com/42078581/45923694-4eb24f00-bf1f-11e8-8e46-ed389e802eaa.png)

and I have reinstall the wsl (uwp) many times,but alway have this problem.
the ~/.bashrc is default
```bash
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m
\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt
```

**Comment by therealkenc** [comment]
From the template you deleted after clicking on "new issue":

> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

Can't repro here FWIW (I'll spare the screencap), but maybe someone has a quick guess.

**Comment by unihon** [comment]
> From the template you deleted after clicking on "new issue":
> 
> > If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).
> 
> Can't repro here FWIW (I'll spare the screencap), but maybe someone has a quick guess.

thanks
