### ISSUE TITLE
Error 0x80070002 initializing WLinux distro

### ISSUE THREAD

**Issue by vancura** [Microsoft/WSL#3567]
I am trying to install [WLinux distro](https://whitewaterfoundry.com/WLinux/), but so far it's failing for me due to old `0x80070002`. My console legacy mode is *off*.

* Your Windows build number: 10.0.18242.1000 (Insiders fast)

* What you're doing and what's happening: 
```
wlinux
Installing, this may take a few minutes...
[wlinux-etl.zip](https://github.com/Microsoft/WSL/files/2409079/wlinux-etl.zip)

WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.
```

* What's wrong / what should be happening instead:
Initialize [WLinux distro](https://whitewaterfoundry.com/WLinux/).

ETLs [here](http://vncr.in/0506d0ec3e3b).

Is there anything I can do to fix it? People recommend reinstallation of Windows, but that's an overkill for me now.

Thanks,
V.

**Comment by vancura** [comment]
For the record, I tried whatever I was able to touch, including https://github.com/Microsoft/WSL/issues/3499#issuecomment-415482073.

**Comment by sirredbeard** [comment]
@vancura:
What is the output of wslconfig /list?

**Comment by Biswa96** [comment]
Do any Ubuntu version from Windows Store runs well?

**Comment by vancura** [comment]
Yes, both Ubuntu and Kali run without problems. 

I posted it here as this is what WLinux authors replied to me on Twitter: 

> I have encountered this before too. Seems to be an upstream issue with WSL that isn't quite nailed down. Do you think you could save some logs and open an issue on the WSL GitHub? Seems to also affect Kali so we can all work on it together with Microsoft there.

(https://twitter.com/WLinuxApp/status/1043930559695728640)

I'll move to WLinux repo. Sorry!
