### ISSUE TITLE
Pinning a Task Bar icon to startWSL not always works as expected

### ISSUE THREAD

**Issue by angelog0** [Microsoft/WSL#3568]
I use MinTTY (from [MSYS2](https://sourceforge.net/projects/msys2/)) to start WSL (Ubuntu). To do this I have created a Desktop link with the target:

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\utente\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```

with icon

```
%SystemDrive%\Program_Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc/ubuntu.exe
```

and after clicking on it I have pinned the resulting icon to the Task Bar.

Now all this worked fine as expected but after a recent upgrade, when I launch WSL a new icon shows up in TB, and it is not that from `ubuntu.exe` but from `mintty.exe`.

Really it [seems](https://github.com/mintty/mintty/issues/801#issuecomment-423851347) that the pinning of apps to the TB not always works as expected.

Maybe you have to put a special attention to this issue because it disturbs the usage of `WSL`: sometimes users does not use the basic DOS box terminal for WSL but some other third-party software (CMder, MinTTY, ConEMU, Hyper etc.).

Did you think to give WSL an its own not-basic Terminal?

Thanks.

**Comment by therealkenc** [comment]
No takers on the question.
