### ISSUE TITLE
Default language not set / unable to configure default language

### ISSUE THREAD

**Issue by laurin1** [Microsoft/WSL#3569]
I don't think this is the same issue as https://github.com/Microsoft/WSL/issues/1544, but if it is, I apologize for duplication. I have had no issues with default language being set until on one machine where I've run "Reset this PC", now I get locale errors when connect via SSH and upon investigation, LANGUAGE and LC_ALL are not set on this machine (it is on the other machines where I use WSL).

keithdavis@KDAVIS:/usr/share/i18n/charmaps$ locale
LANG=C.UTF-8
LANGUAGE=
[Logs.zip](https://github.com/Microsoft/WSL/files/2412169/Logs.zip)

LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

Using App Settings for Ubuntu, I've tried reset and reinstall. I've tried all kinds of commands to set this manually, including those in https://github.com/Microsoft/WSL/issues/1544, but nothing works.

Microsoft Windows [Version 10.0.17134.286]

keithdavis@KDAVIS:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by therealkenc** [comment]
There were no takers on this one, probably because there isn't much to go on here. You didn't say what locale you want, but for say Canadian English it would be:
```
$ sudo locale-gen en_CA.UTF-8
$ sudo update-locale LANG=en_CA.UTF-8
```
If those don't take for you (for whatever reason) it won't be a WSL actionable. Both the Real Linux kernel and the WSL emulated kernel don't know what a libc locale is; they both just execute system calls. You could try serverfault or similar on your specific scenario, which might get better hits than here.

**Comment by laurin1** [comment]
> There were no takers on this one, probably because there isn't much to go on here. You didn't say what locale you want, but for say Canadian English it would be:
> 
> ```
> $ sudo locale-gen en_CA.UTF-8
> $ sudo update-locale LANG=en_CA.UTF-8
> ```
> If those don't take for you (for whatever reason) it won't be a WSL actionable. Both the Real Linux kernel and the WSL emulated kernel don't know what a libc locale is; they both just execute system calls. You could try serverfault or similar on your specific scenario, which might get better hits than here.

Yep, tried that, did not work.

**Comment by laurin1** [comment]
Ok, I have no idea why, but I tried it again, just to make sure I was not crazy and this time those 2 commands worked. 👍
