### ISSUE TITLE
bash shell CLI does not interact well with windows console programs

### ISSUE THREAD

**Issue by Masterxilo** [Microsoft/WSL#3570]
You can add the mounted system32 to the path in WSL and then you can start cmd.exe and powershell.exe. However, these programs cannot be used very well in that nested context. 

All editing functionality (ctrl+backspace, arrow up) is broken and the output is also not correct (self-overlapping very often).

**Comment by Masterxilo** [comment]
Furthermore, in this mode, because the PATH is inherited, powershell (and cmd?) will start unix programs.

For example, I have installed node in my windows and WSL environments.

Starting node in powershell or node in bash alone works.

But starting node in powershell nested in bash runs the linux version, which will then complain about some native modules failing obviously.

**Comment by therealkenc** [comment]
no takers on discussion
