### ISSUE TITLE
File creation within a Docker bind mount doesn't appear in WSL until lxss is restarted.

### ISSUE THREAD

**Issue by stshrive** [Microsoft/WSL#3571]
Microsoft Windows [Version 10.0.17134.285]

*Using docker bind mounts to modify files on host system*

Repro:
Set an environment variable in Windows that points to the Windows package for WSL:
DOCKER_MOUNT_LOCATION
![image](https://user-images.githubusercontent.com/6007067/46051454-73a8ec80-c0ee-11e8-9c80-d0b34ae0a8ce.png)

Make this variable available in WSL:
![image](https://user-images.githubusercontent.com/6007067/46051485-a521b800-c0ee-11e8-8c39-8370cdb72575.png)

[have docker for windows installed.](https://docs.docker.com/docker-for-windows/install/)
[Setup WSL to run docker on Windows](https://medium.com/software-development-stories/developing-a-dockerized-web-app-on-windows-subsystem-for-linux-wsl-61efec965080)

in WSL console, run:
```
docker pull ubuntu
docker run -it --mount type=bind,source="$DOCKER_MOUNT_LOCATION/home/<wsl_username>",target=/mnt/mounted ubuntu bash
```

inside container:
```
cd /mnt/mounted
touch any_new_file.anything
```

In a separate WSL Window:
```
cd ~/
ls -la
```

any_new_file.anything does not appear.

Try touching this file in the second WSL window.
```
touch any_new_file.anything
```
![image](https://user-images.githubusercontent.com/6007067/46051712-83750080-c0ef-11e8-9e6e-b4a0711a7981.png)

In CMD window
```
cd %DOCKER_MOUNT_LOCATION%\home\<wsl_username>
dir
```
![image](https://user-images.githubusercontent.com/6007067/46051768-c6cf6f00-c0ef-11e8-8c05-16c74ba19c4f.png)

Exit all WSL windows and open a new WSL console window:
![image](https://user-images.githubusercontent.com/6007067/46052090-b02a1780-c0f1-11e8-8434-72aada31ac21.png)

NOTE: The lack of permissions may be due to this same issue or may be strictly to Docker, however, this permissions issue appears regardless of setting the dockerfile user to the same UID and GID as the WSL user
i.e. uid=(1000) gid=(1000)

Ideally, when running a docker container with a bind mount to a host windows directory, changes that occur in the docker container appear in the WSL console. (They do appear in CMD console).

You should not get file Input/Output error when trying to access the files.

**Comment by DHowett-MSFT** [comment]
This is no different than using any other Windows application to modify files inside the WSL rootfs, which you're [not supposed to do](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/). Involving Docker doesn't change anything -- you're just adding more complicated steps to achieve the same goal. Ref #45, #87, #154, #552, #649.

**Comment by stshrive** [comment]
I would like to point out that the files I am referencing are mounted in the directory that the link you have provided points out. WSLENV translates this file path to a path on the `/c/<dir>` when executed (I have my default mount point setup to be `/c`, not `/mnt`. 

Another thing the link points out is not modifying files here: `%localappdata%\lxss`,  which I am not using, or accessing in any way. However, I think the main point is the OS metadata being different for Linux and Windows. Which, of course, makes sense.

Are you essentially telling me it is impossible to run docker from WSL (or that this is in fact a bug on docker)?

**Comment by DHowett-MSFT** [comment]
Sorry about that. The files in `AppData\Local\Packages\<package>\rootfs` where `<package>` is a WSL distribution are the modern equivalent of `%localappdata%\lxss` -- the packaged location is the new location for non-legacy distributions. They're subject to the same rules.

The problem here isn't using bind mounts, exactly. You're using a bind mount into a Windows volume, pointed at the WSL _private data directory_. Because you've set up docker using [this guide](https://medium.com/software-development-stories/developing-a-dockerized-web-app-on-windows-subsystem-for-linux-wsl-61efec965080), you're asking the linux docker client to tell the Windows docker daemon to run a linux utility (via LCOW) to manipulate the WSL files for you.
