### ISSUE TITLE
Cannot consistently launch WSL as another windows user

### ISSUE THREAD

**Issue by jhatlerlaird** [Microsoft/WSL#3573]
* Your Windows build number: Server Core 1709 (10.0.16299.665) and Server Core 1803 (10.0.17134.285)

* What you're doing and what's happening:

Using the runas command to run bash.exe, wsl.exe, or ubuntu.exe as the user who initialized the WSL installation only works the first time as expected. 

Following that, bash.exe or wsl.exe may only be run once per 5 minutes. Attempts to run them prior to that will result in the below error. 

![2018-09-26 14_51_12-window](https://user-images.githubusercontent.com/26472965/46118370-33bc3500-c1d4-11e8-82cf-49125a22f648.png)

Running ubuntu.exe within 5 minutes of a successful execution of the WSL on 1709 will open a new blank window which never returns a bash prompt as shown below.

![2018-09-26 14_53_34-window](https://user-images.githubusercontent.com/26472965/46118380-4171ba80-c1d4-11e8-9238-b2c36460bd73.png)

At the same time that the ubuntu process hangs, the svchost.exe process for lxssmanager will start using 100% of a single CPU core. This will continue and prevent any new executions of the WSL until the system is rebooted.

On 1803, running ubuntu.exe within 5 minutes of the first execution causes the below error instead of hanging and impacting lxssmanager. Additionally, on 1803 reboots are not required if the error is encountered.

![2018-09-26 22_48_29-1803](https://user-images.githubusercontent.com/26472965/46121017-e5ad2e80-c1df-11e8-8797-8f39d1520e78.png)

On both versions, if subsequent executions of ubuntu.exe are done at least 5 minutes apart following the first they will work without necessitating a reboot.

The only workaround we've found so far has been to log into the system via RDP as the user who initialized the WSL installation and then disconnect (not log off). So long as the session remains in either the disconnected or active state, then the WSL executions will work without issue and without requiring a 5 minute wait between attempts.

**Setup Instructions**
A fresh installation of Server Core is perfomed. It is then brought fully up to date and restarted as needed.

Then a new local admin account is created with the below powershell commands run as Administrator.

```powershell
New-LocalUser -Name OtherUser -AccountNeverExpires -PasswordNeverExpires -Password (Read-Host -AsSecureString)
Add-LocalGroupMember -Group Administrators -Member OtherUser
```

Then the OtherUser account is logged into and the below command is run to enable the WSL.

```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

The system is then rebooted and the OtherUser account is logged back into. 

The below powershell commands are then run to install Ubuntu 16.04. When prompted to create a user the usernamer OtherUser is specified.

```powershell
Start-BitsTransfer -Source https://aka.ms/wsl-ubuntu-1604 -Destination C:\Ubuntu.zip
Expand-Archive C:\Ubuntu.zip C:\WSL\Ubuntu
C:\WSL\Ubuntu\ubuntu.exe
```

Then the WSL shell is exited and the system is rebooted. 

**Steps to Reproduce Issue**

The system is logged into as Administrator.

The below command is run to launch the WSL as OtherUser.

```batch
runas /user:OtherUser wsl.exe
```

This will give a bash prompt. Close it and try the command again. You will receive the above mentioned error.

Wait at least 5 minutes and then try the command again. It will work. 

To reproduce the ubuntu.exe hang accompanied by the high load from lxssmanager, reboot the system. Then log in as Administrator.

Run the above runas command and then close the bash prompt. Then run the below command to run ubuntu.exe.

```batch
runas /user:OtherUser C:\WSL\Ubuntu\ubuntu.exe
```

You will see the empty window. Looking at Task Manager, you will see a svchost.exe process running at 100% usage of a single core. This should be the svchost.exe process for lxssmanager.

To test the workaround mentioned previously, reboot the system and log into it via RDP as OtherUser. Close the session but do not log off. Now attempt either of the previous runas commands and they should work as expected.

* What's wrong / what should be happening instead:

The WSL should allow any number of executions as the other user account. The 5 minute delay between attempts or having the other account logged in via RDP should not be required. This functionality is vital to allowing the WSL to be utilized by an application running as a different service account (such as IIS).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

The detailed logs for the below scenarios have been attached in the combined zip file below.

[detailed_logs.zip](https://github.com/Microsoft/WSL/files/2422308/detailed_logs.zip)

* 1709-5min_wait-lxcore*.etl
   * This test was run on Server Core 1709 as the Administrator user.
   * The below process was followed.
      * Logging was started.
      * The WSL was run with the command ```runas /user:OtherUser wsl.exe``` and then immediately closed.
      * Approximately 30 seconds later the command was attempted again and produced the above mentioned error.
      * Approximately 5 minutes later the command was attempted again and succeeded.
      * Logging was stopped after closing the bash shell.
* 1709-ubuntu_hang-lxcore*.etl
   * This test was run on Server Core 1709 as the Administrator user.
   * The below process was followed.
      * Logging was started.
      * The WSL was run with the command ```runas /user:OtherUser wsl.exe``` and then immediately closed.
      * Approximately 30 seconds later ubuntu.exe was run with the command ```runas /user:OtherUser C:\WSL\Ubuntu\ubuntu.exe``` to cause the hang.
      * Approximately 5 minutes later the ubuntu window was closed and an attempt to restart the lxssmanager service was made via Task Manager.
      * Approximately 1 minute later, logging was stopped.
* 1803-5min_wait-lxcore*.etl
   * This test was run on Server Core 1803 as the Administrator user.
   * The below process was followed.
      * Logging was started.
      * The WSL was run with the command ```runas /user:OtherUser wsl.exe``` and then immediately closed.
      * Approximately 30 seconds later the command was attempted again and produced the above mentioned error.
      * Approximately 5 minutes later the command was attempted again and succeeded.
      * Logging was stopped after closing the bash shell.
* 1803-ubuntu_error-lxcore*.etl
   * This test was run on Server Core 1803 as the Administrator user.
   * The below process was followed.
      * Logging was started.
      * The WSL was run with the command ```runas /user:OtherUser wsl.exe``` and then immediately closed.
      * Approximately 30 seconds later ubuntu.exe was run with the command ```runas /user:OtherUser C:\WSL\Ubuntu\ubuntu.exe``` to cause the error.
      * Approximately 5 minutes later the ubuntu.exe command was attempted again and succeeded.
      * Logging was stopped after closing the bash shell.

**Comment by 0xbadfca11** [comment]
It's considered to be the same problem as #2576.
That happens by sign-out (unloads user profile) and sign-in (re-loads user profile).
This happens by unloads user profile (after 1st runas) and re-loads user profile (by 2nd runas).
And, both will work again after 5 minutes.

**Comment by benhillis** [comment]
@0xbadfca11 - I agree, this is likely the same as #2576.  If this can be reproduced on a recent Insider build I will take a closer took.

**Comment by jhatlerlaird** [comment]
@benhillis - I can test on an insider build and let you know if it's reproducible. If it is, I'll attach the detailed logs from my testing.

**Comment by benhillis** [comment]
@jhatlerlaird - Perfect, thank you very much.

**Comment by jhatlerlaird** [comment]
@benhillis - It looks like the issue isn't present on the latest Windows Server insider preview (17744). We'll evaluate upgrading once Server 2019 is released. Until that point though we're, in need of a solution of some kind. Do you anticipate that the fix for this issue may be backported to 1803 or 1709? 

Our current workaround of leaving a RDP session in a disconnected state is non-ideal as it requires manual steps after each reboot to retrieve the account credentials and login. Can you think of any alternative workarounds which would not require manual steps or could be scripted in some way?

One potential we're investigating is launching SSH in the WSL as a Windows service and executing our commands over ssh to avoid running more than one wsl.exe command. If there are better alternatives which would allow us to use wsl.exe directly, those would be preferable.

**Comment by benhillis** [comment]
@jhatlerlaird - Yes, this fix is on the list of items to be backported.  I believe the ETA is sometime next month.

**Comment by jhatlerlaird** [comment]
@benhillis - Would that be backported to both 1709 and 1803 or only 1803?
