### ISSUE TITLE
Failure to mount WSL file system in Docker for Windows

### ISSUE THREAD

**Issue by kmillett** [microsoft/WSL#3575]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.286]

* What you're doing and what's happening:  Using docker run and mounting a volume to a path in the WSL file system fails.  The command I am running (from within a Makefile) is:  docker run --mount type=bind,source=$(shell pwd), destination=/mnt/infrastructure

* What's wrong / what should be happening instead:  [docker: Error response from daemon: invalid mount config for type "bind"; bind mount source path does not exist: /home/user/infrastructure]
The path "/home/user/infrastructure" does exist.  That is where I am running the command from.  I can get the docker run command to succeed if I copy the contents of /home/kmillett/infrastructure to a location on the Windows file system, /c/Users/kmillett/infrastructure.  I would rather not have to copy the files to a Windows path as this is a repo that I do not own and I need to be able to use from the WSL file system.

Docker version:
Client:
Version:           18.06.1-ce
API version:       1.38
Go version:        go1.10.3
Git commit:        e68fc7a
Built:             Tue Aug 21 17:24:51 2018
OS/Arch:           linux/amd64
Experimental:      false

Server:
Engine:
 Version:          18.06.1-ce
 API version:      1.38 (minimum version 1.12)
 Go version:       go1.10.3
 Git commit:       e68fc7a
 Built:            Tue Aug 21 17:29:02 2018
 OS/Arch:          linux/amd64
 Experimental:     true

Docker Community Edition
Version 18.06.1-ce-win73(19507)
Channel: stable
b0f14f1

**Comment by tara-raj** [comment]
Thanks for submitting this issue. Could you please clarify if you're running the Docker Community Edition for Windows as your client and your Docker server is on top of WSL?

**Comment by benhillis** [comment]
@kmillett - So you've installed docker in WSL?

**Comment by kmillett** [comment]
yes
