### ISSUE TITLE
How to change uid ?

### ISSUE THREAD

**Issue by ish-org** [Microsoft/WSL#3576]
I want to specify uid and gid for user foo because I don't use map for NFS.
I changed the uid/gid as follows, but this makes 0x80040305 error.
(1) add newgrp by vigr and vigr -s
(2) usermod -g newgrp foo
(3) edit gid in /etc/wsl.conf
This seems working good.
(4) change uid for foo by vipw
(5) chown -R foo ~foo
(5) edit uid in /etc/wsl.conf
(6) reboot windows10pro.
This makes 0x80040305 error.

**Comment by benhillis** [comment]
@ish-org - Which distribution are you using?

**Comment by ish-org** [comment]
I'm using WLinux version 1.1.15.0 purchased from the windows store.
$ cat /etc/os-release | grep -v _URL
PRETTY_NAME="WLinux"
NAME="WLinux"
ID=debian
$ cat /etc/issue| sed '/^$/D'
Debian GNU/Linux 9 \n \l
$ cat /etc/debian_version
9.5

**Comment by ish-org** [comment]
I found that this thread is for ubuntu, sorry.
Then I installed ubuntu 18.04.1 LTS, but  the same error has occurred.
$ cat /etc/os-release | grep -v _URL
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ cat /etc/issue| sed '/^$/D'
Ubuntu 18.04.1 LTS \n \l
$ cat /etc/debian_version
buster/sid

Is there any versions/distributions of specifying UID/GID for initial user creation ?

**Comment by ish-org** [comment]
I solved this problem.
Open cmd.exe with administrator privileges and edit computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{cefb...cb50}\DefaultUid to newuid with regedit.

**Comment by sirredbeard** [comment]
Good to know. Thank you, @ish-org.

**Comment by silent567** [comment]
> I solved this problem.
> Open cmd.exe with administrator privileges and edit computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss{cefb...cb50}\DefaultUid to newuid with regedit.

Hi, I am looking for methods to mount NFS in WSL. Until now, I only found this issue #2869 saying that there was no support for NFS. It seems that you have mounted NFS successfully. Could you please describe the procedures? Or has WSL alreadly supported NFS now?

I am using Ubuntu18.04 on win10 and keeping receiving error: mount.nfs: no such device. 

Thank you very much!

**Comment by MagicFrogSJTU** [comment]
I solve this problem in wsl2 using the following two steps:
1. replace uid with newuid in /etc/passwd in wsl
2. change computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss{cefb...cb50}\DefaultUid to newuid with regedit.
