### ISSUE TITLE
Netselect not working

### ISSUE THREAD

**Issue by tifeit** [Microsoft/WSL#3577]
#wget http://ftp.au.debian.org/debian/pool/main/n/netselect/netselect_0.3.ds1-26_amd64.deb
#sudo dpkg -i netselect_0.3.ds1-26_amd64.deb
#sudo netselect -s 20 -t 40 $(wget -qO - mirrors.ubuntu.com/mirrors.txt)

error:

netselect: socket: Permission denied

**Comment by therealkenc** [comment]
No `strace` or version number. Duping #717 #2742. Whatever the fail, if those flip and the problem persists, feel encouraged to re-submit following CONTIBUTING.md.

**Comment by anasfanani** [comment]
so what the solutiion

**Comment by sdc111** [comment]
# strace sudo netselect -s 20 -t 40 $(wget -qO - mirrors.ubuntu.com/mirrors.txt)

execve("/usr/bin/sudo", ["sudo", "netselect", "-s", "20", "-t", "40", "http://mirror.math.ucdavis.edu/u"..., "http://mirrors.xtom.com/ubuntu/", "http://mirrors.easynews.com/linu"..., "http://www.club.cc.cmu.edu/pub/u"..., "http://mirrors.bloomu.edu/ubuntu"..., "http://mirror.us.leaseweb.net/ub"..., "http://mirror.math.princeton.edu"..., "http://mirror.cs.jmu.edu/pub/ubu"..., "http://mirrors.mit.edu/ubuntu/", "http://mirrors.gigenet.com/ubunt"..., "http://mirror.pit.teraswitch.com"..., "http://mirrors.sonic.net/ubuntu/", "http://ubuntu.mirrors.tds.net/pu"..., "http://mirrors.ocf.berkeley.edu/"..., "http://mirror.clarkson.edu/ubunt"..., "http://mirror.cs.unm.edu/archive"..., "http://mirrors.maine.edu/ubuntu/", "http://repo.ialab.dsu.edu/ubuntu"..., "http://reflector.westga.edu/repo"..., "http://mirror.pnl.gov/ubuntu/", "http://mirrors.vcea.wsu.edu/ubun"..., "http://mirror.us-tx.kamatera.com"..., "http://mirror.vcu.edu/pub/gnu+li"..., "http://ubuntu.mirror.constant.co"..., "http://mirrors.arpnetworks.com/U"..., "http://mirrors.syringanetworks.n"..., ...], 0x7fffd5833128 /* 18 vars */) = -1 EPERM (Operation not permitted)
fstat(2, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
getpid()                                = 184
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by nicolasdanelon** [comment]
hey @therealkenc is this usefull? the bug is alive
```
➜  Nicolas sudo strace netselect -s 20 -t 40 $(wget -qO - mirrors.ubuntu.com/mirrors.txt)
execve("/usr/bin/netselect", ["netselect", "-s", "20", "-t", "40", "http://mirrors.eze.sysarmy.com/u"..., "http://ubuntu.unc.edu.ar/ubuntu/", "http://archive.ubuntu.com/ubuntu"...], 0x7fffcd9a0478 /* 13 vars */) = 0
brk(NULL)                               = 0x12fb000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fffc90844a0) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=27438, ...}) = 0
mmap(NULL, 27438, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2d70652000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360q\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0cBR\340\305\370\2609W\242\345)q\235A\1"..., 68, 880) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=2029224, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2d70650000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0cBR\340\305\370\2609W\242\345)q\235A\1"..., 68, 880) = 68
mmap(NULL, 2036952, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2d70420000
mprotect(0x7f2d70445000, 1847296, PROT_NONE) = 0
mmap(0x7f2d70445000, 1540096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25000) = 0x7f2d70445000
mmap(0x7f2d705bd000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19d000) = 0x7f2d705bd000
mmap(0x7f2d70608000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7f2d70608000
mmap(0x7f2d7060e000, 13528, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2d7060e000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f2d70651380) = 0
mprotect(0x7f2d70608000, 12288, PROT_READ) = 0
mprotect(0x7f2d7064d000, 4096, PROT_READ) = 0
munmap(0x7f2d70652000, 27438)           = 0
socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 3
socket(AF_INET, SOCK_RAW, IPPROTO_RAW)  = -1 EACCES (Permission denied)
getuid()                                = 0
setuid(0)                               = 0
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
brk(NULL)                               = 0x12fb000
brk(0x131c000)                          = 0x131c000
fstat(4, {st_mode=S_IFCHR|0660, st_rdev=makedev(0x4, 0x2), ...}) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(4, "netselect: socket: Permission de"..., 37netselect: socket: Permission denied
) = 37
close(4)                                = 0
exit_group(5)                           = ?
+++ exited with 5 +++
```

**Comment by therealkenc** [comment]
```
socket(AF_INET, SOCK_RAW, IPPROTO_RAW)  = -1 EACCES (Permission denied)
```

You aren't `sudo` here hence the `EACCES`. This is /dupe #717 aka #1349.

![image](https://user-images.githubusercontent.com/7049700/87026843-2e559200-c191-11ea-96a1-b2624e873b95.png)
