### ISSUE TITLE
Port/s stuck listening

### ISSUE THREAD

**Issue by Garfius** [Microsoft/WSL#3580]
Hello, i am developing web services 'rest' using Eclipse PyDev under WSL using flask libraries.

System is: Windows 10 pro, 6gb ram, mechanic Hdd, cable network
    WSL: Ubuntu 18.04, openjdk 10.0.2, eclipse oxygen 3.a

The problem is:
Most of the times when i am debugging, and i stop the process using the eclipse stop button, pyhton stops listening, but suddently the listening port is taken by the system (30-70% chance by each run).

This beheaviour means the port cannot be used again until i restart my computer. Which is really annoying.

Here follows display capture of the misbeheaviour shown by cports from nirsoft.net. In this case is shown the blocked ports by previous launches by the o.s.. And the one i am using , which 40% chance will be blocked by o.s. when i click stop on eclipse.
![image](https://user-images.githubusercontent.com/12560815/46278197-bdb62600-c565-11e8-99a2-b115d109909a.png)

Already tried restarting eclipse, and everything else, maybe if i can restart WSL kernel...?

It seems to happen only using Eclipse/Pydev, apache worked fine.

Thanks and keep up the gr34t work  !!

**Comment by benhillis** [comment]
@Garfius - Which version of Windows are you running?  If you're running a recent build, you'll be able to terminate a specific distribution via wslconfig.exe /terminate <distroname>

**Comment by Garfius** [comment]
> @Garfius - Which version of Windows are you running? If you're running a recent build, you'll be able to terminate a specific distribution via wslconfig.exe /terminate

Nice thing wslconfig.exe /terminate, but it doesn't work

Version from powershell:
```
[System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0

```
Version from Winver: 17134.285
