### ISSUE TITLE
Execution failed without /sbin folder

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#3584]
* Windows Build: Version 10.0.18247.1001 (also in 18234)

`mount.drvfs` was added in Windows 10 19H1 builds. It resides in `/sbin` and a symbolic link to `/init`. If the `/sbin` folder isn't present in the installed distribution then the `wsl.exe` or `bash.exe` shows error: 
* HRESULT == 0x80070040
* Win32 Error == ERROR_NETNAME_DELETED : The specified network name is no longer available.
* Event from LxssManager:
```
[Microsoft.Windows.Lxss.Manager] Error file:onecore\vm\wsl\lxss\lxcmdlineshared\lxssserverport.cpp linenumber:61 type:0 failurecount:6 threadid:3888 hr:0x80070040 message: code: function:
[Microsoft.Windows.Lxss.Manager] Error file:onecore\vm\wsl\lxss\service\lib\lxssusersession.cpp linenumber:423 type:1 failurecount:5 threadid:3888 hr:0x80070040 message:onecore\vm\wsl\lxss\lxcmdlineshared\lxssserverport.cpp(61)\lxssmanager.dll!00007FFC59EAD771: (caller: 00007FFC59E83DE6) Exception(6) tid(f30) 80070040 The specified network name is no longer available.
```
* Possible error in `LxssServerPort::WaitForConnection` after IOCTL.
* Solution: If I add the `/sbin` folder manually with Ctrl+Shift+N from Windows then it works.

**Comment by benhillis** [comment]
Good catch, I'll fix this up. Out of curiosity how did you hit this?

**Comment by Biswa96** [comment]
First I use my repo [WslInstall](https://github.com/Biswa96/WSLInstall) where I compiled a single busybox binary and a `/etc/passwd` file. I used it in every Windows insider build. After seeing the error, I also used @0xbadfca11's repo [miniwsl](https://github.com/0xbadfca11/miniwsl). Both shows same error which also confirm that the error was not from my WslInstall. Then I use my [real time trace event tool](https://github.com/Biswa96/TraceEvent) and x64dbg/windbg simultaneously to find the possible error. 

I've also a curious thing. In Windows build 18247 `/init` and `/bsdtar` placed outside of LxssManager.dll. Doesn't it become a possible attacking vectors from malware?

**Comment by benhillis** [comment]
@Biswa96 - Thanks, that's useful to know.  I'll make sure the sbin directory exists before creating the symlink.

Regarding an attack vector, a similar attack vector would be malware replacing cmd.exe, notepad.exe, or any other binary / dll in system32.

**Comment by Biswa96** [comment]
Replacing a System file may requires admin privilege but the `init` and `basdtar` is copied to user folder aka. LocalAppData\Packages. That'll be easy step. Also one can experiment with `init` file, can't he? Like replace the init with their own, maybe systemd with the proper IOCTLs.

**Comment by benhillis** [comment]
init is copied from system32 to the user folder each time a new instance is launched.  While the instance is running the file will not be able to be replaced because it is in used.  Similar story with bsdtar, except in a future change it will no longer be copied at all.

**Comment by Biswa96** [comment]
Any ETA for this fix and the 'future change'? Which Windows build will get this fix?

**Comment by benhillis** [comment]
@Biswa96 - Change was checked in yesterday, it needs to make its way to the prerelease branch. I don't control or have much influence over how fast that happens, but hopefully it won't be more than a couple of weeks.

**Comment by benhillis** [comment]
Fixed in 18267.

**Comment by Biswa96** [comment]
Confirmed! Fixed in insider build 18267.

`%windir%\System32\lxss\tools\ext4.vhdx.gz` Interesting 🧐
