### ISSUE TITLE
Could not let LXSSMANAGER autostart

### ISSUE THREAD

**Issue by meijieru** [Microsoft/WSL#3585]
* Your Windows build number: Microsoft Windows [Version 10.0.17134.286]

* What you're doing and what's happening:  I run `service.msc` as admin, but I still could not let LXSSMANAGER autostart. 
![image](https://user-images.githubusercontent.com/9511136/46378538-ea536600-c669-11e8-8244-48b258e7ef66.png)

* What's wrong / what should be happening instead: It should autostart

**Comment by Biswa96** [comment]
Add this registry:
```ini
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager]
"Start"=dword:2
```

**Comment by benhillis** [comment]
@meijieru - Why do you want the service to automatically start? It will be trigger-started when any clients attempt to connect to it.

**Comment by meijieru** [comment]
@benhillis Because when I run `wsl` it says no distribution installed.

**Comment by raji2004** [comment]
ubuntu is not working on my pc it is saying to restart wsl but i cant do that
