### ISSUE TITLE
Error 0x80070003 when I `bash`, but totally fine when I manually run Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by Aetheryx** [Microsoft/WSL#3586]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.286]

* What you're doing and what's happening:
When I run `bash` from a terminal (either normal `cmd` or a PowerShell), I am met with this error:
![image](https://user-images.githubusercontent.com/25572140/46385116-96bd3880-c6ba-11e8-86c0-9301404436f8.png)  

It should be noted that I can select the [Bash on Ubuntu on Windows](https://i.imgur.com/gjjm0yC.png) option from the Start Menu and then get into Bash totally fine:
![image](https://user-images.githubusercontent.com/25572140/46385150-cb30f480-c6ba-11e8-9137-ca97277858b1.png)  
I installed WSL through `lxrun /install /y` (after enabling Developer Mode and enabling the WSL feature).

* What's wrong / what should be happening instead:
I shouldn't be receiving this error when I start `bash`.

[logs.zip](https://github.com/Microsoft/WSL/files/2440242/logs.zip)

**Comment by benhillis** [comment]
You likely have multiple distributions installed, and one of them seems to be corrupt (0x80070003 is file not found).  Could you share the output of wslconfig.exe /list?

**Comment by Aetheryx** [comment]
You were right! Upon running `wslconfig.exe /list` it showed me that the default distribution was an old Arch install I fucked around with. I unregistered the entry and `bash` works fine :smile:
