### ISSUE TITLE
could not execute .exe file beyond windows root

### ISSUE THREAD

**Issue by LightMelodies** [Microsoft/WSL#3588]
* Your Windows build number: (Type ver at a Windows Command Prompt)
10.0.17763.1
* What you're doing and what's happening: (Copy&paste specific commands and their output, or include screen shots)
When I change current direcyory to a drive expect C: and try to run some exe file like this
`--- /mnt/r » notepad.exe`

* What's wrong / what should be happening instead:
As I expected, notepad.exe should be running, but it failed with this:
`/mnt/c/Windows/System32/notepad.exe: Invalid argument`
However, the same command works well when running in /mnt/c or in linux home dir

* Strace of the failing command, if applicable: (If some_command is failing, then run strace -o some_command.strace -f some_command some_args, and link the contents of some_command.strace in a gist here).

```
execve("/mnt/c/Windows/System32/notepad.exe", ["notepad.exe"], 0x7fffc8d3c578 /* 30 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x61c0b8) = 0
set_tid_address(0x61c0f0)         = 174
getpid()                          = 174
brk(NULL)                         = 0x1b4c000
brk(0x1b4d000)                    = 0x1b4d000
getcwd("/mnt/r", 4096)            = 7
uname({sysname="Linux", nodename="Canoe", ...}) = 0
open("/dev/lxssclient", O_RDWR)   = 3
ioctl(3, _IOC(0, 0, 0x2f, 0x22), 0x7fffc360b870) = 0
open("/mnt/c/Windows/System32/notepad.exe", O_RDONLY|O_NOFOLLOW|O_PATH) = 5
ioctl(3, _IOC(0, 0, 0x3f, 0x22), 0x7fffc360b6e0) = 0
close(5)                          = 0
open("/mnt/r", O_RDONLY|O_DIRECTORY) = 5
ioctl(3, _IOC(0, 0, 0x3f, 0x22), 0x7fffc360b6e0) = 0
close(5)                          = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGPGRP, [172])        = 0
getpgid(0)                        = 172
fstat(0, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=50, ws_col=211, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 -opost -isig -icanon -echo ...}) = 0
dup(0)                            = 5
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffc360b840) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffc360b840) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffc360b840) = 0
write(4, "\0\0\0\0\263\0\0\0'\0\0\0\0\0\0\0(\0\0\0\0\0\0\0)\0\0\0\0\0\0\0"..., 179) = 179
read(4, "\10\0\0\0000\0\0\0\26\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 48) = 48
writev(2, [{iov_base="/mnt/c/Windows/System32/notepad."..., iov_len=54}, {iov_base=NULL, iov_len=0}], 2) = 54
close(3)                          = 0
Subtitleclose(4)                          = 0
ioctl(5, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
close(5)                          = 0
exit_group(1)                     = ?
+++ exited with 1 +++
```

**Comment by Biswa96** [comment]
Can you provide the full command that to typed in bash? And what is the current working directory aka. `echo $PWD`.

**Comment by LightMelodies** [comment]
@Biswa96 
I am using zsh so `/mnt/r` is the cureent workding dir(in windows aka R:\) and `notepad.exe` is the full command.

**Comment by LightMelodies** [comment]
I find a similar issue, but it has been fixed. #3379

**Comment by therealkenc** [comment]
I almost duped you to #3397 out of the gate when you posted, but saw your build number (17763 > 17728). The fail is too coincidental though. If you get further up `/mnt/r` to say `/mnt/r/this/that/other` does it make a difference?

**Comment by LightMelodies** [comment]
I have find the reason that R:\ is a ramdisk. When I create a real drive(like D:\),  it works well.  But I can not figure out the difference between a ramdisk and a real hard disk partition since all others behave the same in windows.

**Comment by Biswa96** [comment]
The reason may be same as with SD card. LxCore driver needs static GUID.

**Comment by therealkenc** [comment]
> The reason may be same as with SD card. LxCore driver needs static GUID.

That might be the root cause; dunno. But @LightMelodies you can hold this open for a bit if you want, depending on how you created the ramdisk. Which (naturally) you did not include in your reproduction steps in the OP. 

While it could be a static GUID thing (shrug) #3519 isn't the fail mode here. This is a different scenario than #3519 where the filesystem is LxFS and the root directory of a distro. Maybe it is just a badly formed filter driver, which is spiritually dupe other issues. 

I won't look a closed tag in the mouth but this might be legit enough if all you are doing is a `mount -t drvfs R: /mnt/r`. You might well get an 'external' tag for the trouble if your ramdisk is an unsupported third-party driver (read: ImDisk), but at least what you are attempting will be on the books. And who knows maybe you'll get lucky and support can be added to DrvFS (it has been getting more tolerant of filesystem driver implementations over time). And, it might yet be something "silly" and easy to fix.
