### ISSUE TITLE
ssh and apt-get update connection seems not working after the 1809 update

### ISSUE THREAD

**Issue by RegexYman** [Microsoft/WSL#3590]
Windows 10 Build 1809

What you're doing and what's happening: 

ssh and apt-get update connection seems not working after the windows update

ssh command
![image](https://user-images.githubusercontent.com/36397069/46431260-edd81180-c77d-11e8-8948-8564a7a1cc92.png)

apt-get update
![image](https://user-images.githubusercontent.com/36397069/46431394-48716d80-c77e-11e8-9568-4458809051b8.png)

*What's wrong / what should be happening instead:
something woring in network connections / configurations

* Strace of the failing command, if applicable:  
ssh root@xx.xx.xx.xx
apt-get update

**Comment by RegexYman** [comment]
>           Allow Linux binaries in Windows Firewall.
Still happend when I switched off the firewall....

**Comment by Webysther** [comment]
same here

**Comment by Webysther** [comment]
Duplicated #3367

**Comment by DarthSpock** [comment]
You need to create entries for each archive server being pulled from in your firewall config. Same issue arose with Kali. Disabling firewall doesn't appear to do anything, only explicit rules work. Make sure to enable both port 80 and 443 for the IP entries.

**Comment by RegexYman** [comment]
Problem solved. I switched off the port 80 and port 443 monitoring in Kaspersky settings then it works. This issue never happend before the windows 10 build 1809 update even the port monitoring is on.....

**Comment by pffang** [comment]
same problem
