### ISSUE TITLE
EINVAL when connecting to outside TCP port after many connections

### ISSUE THREAD

**Issue by oxygen** [Microsoft/WSL#3591]
`Microsoft Windows [Version 10.0.17134.285]`

`Linux DESKTOP-EHS2807 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux`

I have a NodeJS application listening on TCP ports 80 and 443. 

Alongside it I have some native Linux application listening on many TCP and UDP ports 
and another NodeJS app that is just a TCP client to the other two mentioned apps.

The app needs to make thousands of TCP outgoing calls to some internet address over port 443 (for the record, using the node-fetch client library).
I even set it to have a 100ms cooldown between requests, and made all requests sequential.

At some point it permanently starts to fail all outgoing requests with 
```
  message: 'request to https://some/domain/ failed, reason: connect EINVAL 188.215.115.89:443 - Local (0.0.0.0:0)',
  type: 'system',
  errno: 'EINVAL',
  code: 'EINVAL'
```

Also it is no longer possible to connect to it from outside the server, so the listening port is also affected.
Importantly, incoming connections do not fail with connection refused, they fail with connection timeout.

The other two apps's existing connections are unaffected and can also receive requests.
However, if restarted, they too show the same behaviour.

Restarting the LxssManager service solves the issue.

**Comment by therealkenc** [comment]
Could be like #2913 #3311 et al. No repro.

**Comment by oxygen** [comment]
Yes, please close this, I'll move there.
