### ISSUE TITLE
WslRegisterDistribution fails if tarball contains security.selinux extended attributes

### ISSUE THREAD

**Issue by mattycourtney** [microsoft/WSL#3592]
**Windows Build:** 
Microsoft Windows [Version 10.0.17134.286]

**Steps to reproduce:**
Attempt to register a new WSL distribution, passing [WslRegisterDistribution()](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslregisterdistribution) the filename of a tarball that contains filenames prefixed with './'

**Expected outcome:**
New WSL distribution registered successfully

**Actual outcome:**
No error message is given, but the the call to WslRegisterDistribution() seems to hang indefinitely

**Comment by mattycourtney** [comment]
[livemedia-creator](http://weldr.io/lorax/livemedia-creator.html) is typically used by RPM-based distros to create images for docker containers, and produces tarballs with filenames prefixed by './'

This is a valid filename per POSIX standards, but WslRegisterDistribution() seems to struggle with it.

**Comment by Biswa96** [comment]
Can you provide the tarball link?

**Comment by mattycourtney** [comment]
**Working tarball:** https://drive.google.com/open?id=1DzO214kLD2BqjCgJCkBCHFS2x3haIHRw
**Non-working tarball:** https://drive.google.com/open?id=16LoblWT1qwubmZXT0o5BEURtydEmDbEh

These are based on the [Centos 7 Docker image](https://github.com/CentOS/sig-cloud-instance-images/blob/24c0d04946b72e37776309224712b5f05aa52639/docker/centos-7-docker.tar.xz), which was originally compressed with xz (I converted it to gzip)

**Comment by benhillis** [comment]
@mattycourtney - Thanks for filing this issue. The issue is actually that the non-working tarball contains security.selinux extended attributes (which WSL does not support).  I've identified what is causing the hang and will get that part fixed up.

**Comment by mattycourtney** [comment]
Good to know. Thanks @benhillis!

**Comment by therealkenc** [comment]
> security.selinux extended attributes (which WSL does not support)

That's what I figured ref (dupe?) #2677 but you beat me to it.

**Comment by benhillis** [comment]
Fixed in 18267.

**Comment by Biswa96** [comment]
I found some errors in build 18267 and CentOS 7 can't be installed. Here are some of my findings:

* Event Trace logs from `LxCore!VfsInodeExtendedAttributeAccessCheckSecurityNamespace()`:

```md
ExecutablePath:bsdtar Function:VfsInodeExtendedAttributeAccessCheckSecurityNamespace Line:1451 Message:Unsupported extended attribute: security.selinux
ExecutablePath:bsdtar Function:LxpSysDispatch Line:6133 Message:[0xffffffa1] Syscall 189 failed with unexpected error -95!
ExecutablePath:bsdtar Function:LxpSysDispatch Line:6133 Message:[0xffffffa1] Syscall 190 failed with unexpected error -95!
```
* WslRegisterDistribuion Hresult: `0x80004005`
* LxssUserSession::RegisterDistribution Error: `0x4005 Unspecified error`

What about the other "unsupported attributes" for example `security.capability`, `security.evm`, `security.ima`, `security.selinux `?
