### ISSUE TITLE
Windows Store Ubuntu vs Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by kaba2** [Microsoft/WSL#3594]
* Your Windows build number:  10.0.17134.285

* What you're doing and what's happening

I wanted to upgrade an existing installation of Bash on Ubuntu on Windows 16 to 18, so I went to the Windows Store and installed Ubuntu 18 from there. Installation succeeded, and Ubuntu 18 can now be invoked from the start menu. 

* What's wrong / what should be happening instead:

I now have two installations of Ubuntu. There is Bash on Ubuntu on Windows which runs Ubuntu 16, and there is the start menu one, which runs Ubuntu 18. I expected the Windows Store installation to upgrade the existing Ubuntu, not install a new side version. 

What is the proper way to update Ubuntu on Windows? If I remove Ubuntu 18 using Window's usual "Remove programs", does it also remove Bash on Ubuntu on Windows (Ubuntu 16)?

**Comment by nyanhacker** [comment]
There's seperate root of Ubuntu which from bash.exe / wsl install cmd and Windows Store. Well, if you're going uninstall 18.04 there's nothing to do with 16.04 or vice versa.

In Windows bash.exe / wsl install cmd. That's means you installing Beta Version that has still many bugging. Not like from the windows store that has latest repository update.

Well, i suggest you installed Ubuntu 18.04  from Windows Store and delete the beta.

For Alternative: you can upgrade Ubuntu 16.04 Beta Installation to 18.04 even to 18.10 (Cosmic) with `sudo do-release-upgrade` / `-d` options for upgrade Cosmic if available. But still, i don't reccomend upgrade wsl beta

**Comment by kaba2** [comment]
Thanks for the reply. I did as you said; deleted the beta and using Windows Store version now. Everything seems to work.
