### ISSUE TITLE
Directory created by bash on windows is inexplicably different than if created using Windows Explorer

### ISSUE THREAD

**Issue by mdmower** [Microsoft/WSL#3596]
* Your Windows build number:

Microsoft Windows [Version 10.0.17134.320]

* What you're doing and what's happening:

    `$ mkdir /mnt/c/Users/mdmower/source/repos/WebBash`

* What's wrong / what should be happening instead:

The folder created by bash on Windows (WSL with Ubuntu 18.04) is _somehow_ different than if I had created it in Windows Explorer. Internet Information Services 10 (IIS 10.0.17134.1) will not read `Web.config` if it resides in the folder created by bash.

If I create side-by-side directories -- `WebBash` created with mkdir in bash and `WebWin` created with Windows Explorer -- and then copy the same Web.config file into each directory. IIS will not read the file from the `WebBash` directory. The security settings (Properties > Security > Advanced) for the two directories are identical. PowerShell's `Get-ItemProperty` reports that both directories have the same mode `(d-----)`, no LinkType, and valid Target.

I am at a loss about _what_ is different about a directory created using `mkdir` with bash.

I have a [question open on ServerFault](https://serverfault.com/questions/933718/why-cant-iis-read-web-config-within-a-folder-created-by-bash-on-windows) that is more tailored to IIS -- with steps to reproduce.

**Comment by therealkenc** [comment]
> Microsoft Windows [Version 10.0.17134.320]

Probably #3356.
