### ISSUE TITLE
automount root does not work

### ISSUE THREAD

**Issue by mmicu** [Microsoft/WSL#3597]
**Windows build number**:  Microsoft Windows [Version 10.0.16299.611]

Hello. I've installed the Ubuntu 18.04 version by using [this guide](https://docs.microsoft.com/en-us/windows/wsl/install-on-server), even if I'm not using a Windows server, but the Windows store is blocked by the company's policies.

If I open a command promt and digit "wsl.exe" everything works fine. I'm able to install packages and so on. However, I modified the /etc/wsconf.conf in this way:

```
[automount]
enabled = true
root = /windir/
```

but when I restart `wsl` the `C:\` disk is always mounted in `/mnt/c`. I tried to restart the machine and execute `wsl` by using the PowerShell, but the result is the same.

**Comment by 0xbadfca11** [comment]
> Windows build number: Microsoft Windows [Version 10.0.``16299``.611]

> Available in Windows Insider Build ``17093 and later``
> https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings

Require update.

**Comment by thehashrocket** [comment]
> > Windows build number: Microsoft Windows [Version 10.0.`16299`.611]
> 
> > Available in Windows Insider Build `17093 and later`
> > https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings
> 
> Require update.

I'm on `Windows 10 Pro 10.0.17763 Build 17763` and I'm having the same results. When I go to `/mnt/c` or any of the other mounted drives their empty. It's like wsl is completely ignoring the conf file.

**Comment by benhillis** [comment]
@thehashrocket - What are the contents of your /etc/wsl.conf?
