### ISSUE TITLE
wslpath not working?

### ISSUE THREAD

**Issue by musm** [Microsoft/WSL#3599]
```
wslpath -w "/home"
wslpath: /home/: Invalid argument
```

**Comment by ckuai** [comment]
it doesn't work for unix path. the param has to be Windows path format. I do wish wslpath will just take both unix and windows path. when it is unix path, just return as is. currently I have to check path condition before calling wslpath.

**Comment by cuihaoleo** [comment]
wslpath will not reveal Windows path of files on the root filesystem. My wslpath give a more clear error message:
```
$ wslpath -w "/home"
wslpath: /home: Result not representable
$ wslpath -w "/mnt/c/Users"
C:\Users
```

**Comment by 0xbadfca11** [comment]
This is by design. https://github.com/Microsoft/WSL/issues/3146#issuecomment-388118689
