### ISSUE TITLE
Spelling mistake in usage information for wsl command

### ISSUE THREAD

**Issue by robertwray** [Microsoft/WSL#3601]
* Your Windows build number:  17763.1

* What you're doing and what's happening:  Running the command `wsl --help`

* What's wrong / what should be happening instead: The help text for the -d parameter has a spelling mistake in its description. *distribition* should be *distribution*

**Comment by benhillis** [comment]
Thanks. I noticed this as well earlier this week.

**Comment by robertwray** [comment]
Issue resolved, noticed in 18346
