### ISSUE TITLE
Support NFS server inside WSL for use with Vagrant VM file sync

### ISSUE THREAD

**Issue by codeguy** [Microsoft/WSL#3603]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I am running WSL with Ubuntu Bionic. I am running Vagrant in WSL based on these instructions: https://www.vagrantup.com/docs/other/wsl.html. My goal is to use NFS for file sync between my WSL host and the Vagrant VM. Currently this is not possible, and I have to rely on rsync or the default vboxfs. Both of these are veeeeery slow.

* What's wrong / what should be happening instead:

NFS server should be supported in WSL. I understand WSL is userland only and without a Linux kernel. I was hoping that the powers-that-be can work some magic and make this happen.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

n/a

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by MrObvious** [comment]
Not helpful as far as bug reporting fixes, but does Vagrant support SMB? Maybe you could share it that way.

**Comment by therealkenc** [comment]
Re-categorizing question. One can submit a (hypothetical) request for in-kernel `nfsd` to be built into the WSL driver to UserVoice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l), if that's the ask. It isn't clear at all wht the setup is here (vboxsf is mentioned tangentially), but either way academic. See also [this](https://github.com/Microsoft/WSL/issues/873#issuecomment-388629603) and [this](https://github.com/Microsoft/WSL/issues/873#issuecomment-388645854) for possible explorations (although it is not the answer to your veeeeerry slowness).

**Comment by er1z** [comment]
@MrObvious — SMB performance under Vagrant is pathetic.
