### ISSUE TITLE
Lose cursor

### ISSUE THREAD

**Issue by purocean** [Microsoft/WSL#3604]
* Your Windows build number:  10.0.18252.1000

* What you're doing and what's happening: 
Use vim or MySQL cli tool

* What's wrong / what should be happening instead:
Lose cursor
![2](https://user-images.githubusercontent.com/7115690/46641228-02177680-cba3-11e8-9849-8e4b5ddb0470.gif)

**Comment by therealkenc** [comment]
> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console).

**Comment by purocean** [comment]
@therealkenc Thanks. 

https://github.com/Microsoft/console/issues/269
