### ISSUE TITLE
`umount -f` incorrectly reports "not mounted"

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#3605]
Under `18252`, it appears that `umount -f` is broken in some regard. I'm pretty sure this is a regression as I seem to recall using this before (and my fish shell history confirms) but I don't recall having a problem.

```fish
~> sudo umount /mnt/c
mqudsi@ZBook:/mnt/c/Users/mqudsi$ sudo umount /mnt/c
umount: /mnt/c: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
~> sudo umount -f /mnt/c
umount: /mnt/c: not mounted
~> mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
```

log of `sudo strace -o umount.log umount -f /mnt/c` is attached.
[umount.log](https://github.com/Microsoft/WSL/files/2461962/umount.log)

**Comment by therealkenc** [comment]
Confirmed on '252 and yeah that's gotta be a regress. It's actually the [first thing](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) this MSFT blog post suggests to do.

**Comment by benhillis** [comment]
Took a look at our code, and it doesn't look like the MNT_FORCE flag has ever been supported.  Adding @SvenGroot to confirm.

Failing to umount /mnt/c while your current working directory lies within that mount is expected.

**Comment by therealkenc** [comment]
> The blog post does not specify adding the '-f' flag.

Good point I missed that (cut-and-paste blindness). 

And right, an `EBUSY` fail would be, like you say, linux-behavior if you live in the tree. The `EINVAL` on `MNT_FORCE` is pretty much beside the point. You'll get `EBUSY` force or no force. `MNT_FORCE` is overrated anyway, and not applicable here. The flag can just "do nothing" as intended behavior, just like ext234 ot tmpfs on Real Linux.

So a better repro, which treads into academic at this point (absent a use case, which has never come up):

```
$ mkdir foo
$ sudo mount -t tmpfs foo ./foo
$ sudo umount ./foo
umount: /home/ken/tmp/foo: not mounted.
```
That should unmount `./foo`, with the `MNT_FORCE` being unilaterally disregarded.

**Comment by benhillis** [comment]
@therealkenc - Yeah, we should probably just ignore the MNT_FORCE flag instead of rejecting callers that provide it.

**Comment by therealkenc** [comment]
> Yeah, we should probably just ignore the MNT_FORCE flag

Right, that's what Real Linux does. It isn't even a case of stubbing it out "for WSL" per se. Doing nothing is how it is supposed to behave on filesystems that don't support `MNT_FORCE` semantics. Which is pretty much the case for all "normal" filesystems. From man7:

```
MNT_FORCE (since Linux 2.1.116)
[blah blah...]
As at Linux 4.12, MNT_FORCE is supported only on the following
filesystems: 9p (since Linux 2.6.16), ceph (since Linux
2.6.34), cifs (since Linux 2.6.12), fuse (since Linux 2.6.16),
lustre (since Linux 3.11), and NFS (since Linux 2.1.116).
```

All of which is pretty damn unimportant; but there's no dupe to punt this issue to either and it is (academically) a legit enough diverge. And there is probably more ink spilled above than the number of line(s) of code that need to be commented out in the WSL driver.

**Comment by mqudsi** [comment]
It turns out I had some processes in the background that had dissociated from all terminals, and they were `cd`'d into `/mnt/c`.

While I have you both here, shouldn't `umount /mnt/c` (without sudo) be EPERM and not EINVAL?

**Comment by therealkenc** [comment]
The `EINVAL` is because of the `MNT_FORCE` (aka `-f`). Which isn't "supported" in WSL. Scary quotes because there isn't really anything to support.

**Comment by mqudsi** [comment]
No, without `-f`

**Comment by therealkenc** [comment]
I'm not seeing that here. I get `umount: /mnt/c: umount failed: Operation not permitted` _without_ the `-f` and without `sudo`. _With_ `-f` I get `umount: only root can use "--force" option`. It doesn't [make it](https://github.com/karelzak/util-linux/blob/d5fd9ac6b208c5acdb6c0023757a7e2827474482/sys-utils/umount.c#L131) to the `mount(2)`.

**Comment by mqudsi** [comment]
```fish
mqudsi@ZBook /m/c/U/m/Downloads> cmd.exe /c 'ver.bat'

Microsoft Windows [Version 10.0.18252.1000]
mqudsi@ZBook /m/c/U/m/Downloads> mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)
mqudsi@ZBook /m/c/U/m/Downloads> umount /mnt/c
umount: /mnt/c: umount failed: Invalid argument
```

**Comment by benhillis** [comment]
MNT_FORCE is now stubbed in 18277.

**Comment by mqudsi** [comment]
Thanks!
