### ISSUE TITLE
Cursor disappears in Vim in build 18252

### ISSUE THREAD

**Issue by nernst** [Microsoft/WSL#3606]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18252.1000

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Attempt to navigate a text file using vim. As soon as any of the primary navigation keys are pressed ('h', 'j', 'k', 'l'), the cursor disappears. It will reappear if you search for something or change modes (e.g. visual or insert), but it then disappears after any further keystrokes. The cursor will also reappear if the console is deactivated/activated (e.g. alt-tab away and back).

Cursor visible:
![image](https://user-images.githubusercontent.com/6090005/46702936-b5f02480-cbea-11e8-8e46-d25f4c005c77.png)

Cursor no long visible after hitting 'l':
![image](https://user-images.githubusercontent.com/6090005/46702975-d7511080-cbea-11e8-8d66-093040ac946e.png)

* What's wrong / what should be happening instead:
The cursor should remain visible.

I think this issue is specific to WSL as I cannot reproduce it in either a standard command prompt or powershell instance.

**Comment by benhillis** [comment]
I believe this is the same as  https://github.com/Microsoft/console/issues/269.
