### ISSUE TITLE
🤯 WSL symlink is different from Native Linux (VM/Container) symlink 

### ISSUE THREAD

**Issue by myuseringithub** [Microsoft/WSL#3611]
**Symlinks interoperability is a must ! Creating symbolic links files either on _WSL_ or from other _Linux distributions_ should be able to work between them** (not mentioning _Windows OS_, only _Linux distributions_, i.e. VM/Container with shared files with _WSL host machine_). 

It is really weird that for allowing _Windows Subsystem for Linux_ symlinks to work with _Windows OS_ symlinks, interoperability is dropped for _Native Linux Kernel_. A huge bottleneck for adopting WSL and subsequently Windows for development. 
Personally I'm on the verge of switching to a _Linux_ setup for development and dropping _Windows_ as development/user OS altogether, was using _Cygwin & Bash.exe_ till now. It seems that there will always be issues that requires days of searching for a solution, but this one was enough for me (wish I could find this mentioned in the docs before attempting to change my setup).

### Use case: 
Working with `node_modules/.bin/<symlinks>` that where installed with _WSL_ or using _native Linux_. In such case NPM/Yarn on Linux creates relative symlinks for the `.bin` scripts.

### Symlinks support between WSL, Native Linux, Windows OS:

**○ WSL created symlink:** 
![wsl](https://user-images.githubusercontent.com/7758497/46877532-c9e59180-ce49-11e8-9747-54e5bc038b3d.PNG)
- WSL - ✔️ Symlink
- Docker container - ❌permission denied (`No such file or directory`). 
- Ubuntu Hyper-V VM - ❌ shows as a text file.
- Windows - ✔️ Symlink

**○ Linux Container/VM created symlink:** 
![linuxmobyvm or container](https://user-images.githubusercontent.com/7758497/46877530-c9e59180-ce49-11e8-9c7d-6eaabf7a9e25.PNG)
- WSL - ❌ shows as a text file.
- Docker container - ✔️ Symlink
- Ubuntu Hyper-V VM - ✔️ Symlink
- Windows - ❌ shows as a text file.

**○ Windows created symlink:** _Regular soft symbolic link (not Junction)_
![windows](https://user-images.githubusercontent.com/7758497/46877531-c9e59180-ce49-11e8-84de-e66051cca111.PNG)
- WSL - ✔️ Symlink
- Docker container - ❌permission denied (`No such file or directory`). 
- Ubuntu Hyper-V VM - ❌ shows as text file.
- Windows - ✔️ Symlink

### Versions: 
- **Windows 10 Pro** 1803, OS build 17134.345, Developer mode turned on.
- **WSL** Debian GNU/Linux 9.5 (stretch)
- **Docker for Windows** 2.0.0.0-beta1-win75 (19925) edge 915f68b
- **MobyLinuxVM** kernel 4.9.125-linuxkit
- **Docker Engine**: 18.09.0-ce-beta1
- **Container** - any Linux container.
- **Hyper-V VM** Ubuntu 18.04.1

**Comment by therealkenc** [comment]
#1475

**Comment by myuseringithub** [comment]
@therealkenc Have you even looked at the issue ? It is not fixed.

**Comment by RDeluxe** [comment]
I think this issue should be still opened.

I'm encountering the exact same issue:

- `npm install` in WSL (creates symlinks in node_modules/.bin/)
- `docker-compose up` mounts my app in a volume in a alpine container
- inside the container, all the symlinks are broken

**Comment by devoto13** [comment]
@therealkenc I experience exactly the same issue as @RDeluxe using build 17134.376. https://github.com/Microsoft/WSL/issues/1475#issuecomment-409357010 mentions that fix is included in 17046, so I assume it should already have it. Or is it not the case?

If the fix is already included, please, consider re-opening this issue as at least part of it is still not working as desired.

Anyway here are steps to reproduce the issue without Node/Npm and Docker Compose:
1. Install Docker for Windows and configure Docker client inside WSL to connect to it ([guide](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)).
2. Open WSL bash and follow the steps:

```
WSL $ cat 1.sh
#!/bin/sh
echo 1
WSL $ chmod +x 1.sh
WSL $ ln -s ./1.sh 2.sh
WSL $ ls -la
total 0
drwxrwxrwx 1 kushtrim kushtrim 4096 Nov  6 12:58 .
drwxrwxrwx 1 kushtrim kushtrim 4096 Nov  6 11:57 ..
-rwxrwxrwx 1 kushtrim kushtrim   18 Nov  6 12:57 1.sh
lrwxrwxrwx 1 kushtrim kushtrim    6 Nov  6 12:58 2.sh -> ./1.sh
# Both work under WSL
WSL $ ./1.sh
1
WSL $ ./2.sh
1

WSL $ docker run -it --rm -v `pwd`:/opt/test alpine sh
/ # cd opt/test/
/opt/test # ls -la
total 5
drwxrwxrwx    2 root     root             0 Nov  6 11:58 .
drwxr-xr-x    3 root     root          4096 Nov  6 12:03 ..
-rwxr-xr-x    1 root     root            18 Nov  6 11:57 1.sh
ls: ./2.sh: cannot read link: No such file or directory
l---------    1 root     root             0 Nov  6 11:58 2.sh
# Symlink does not work when run inside Docker container being mounted as a volume
/opt/test # ./1.sh
1
/opt/test # ./2.sh
sh: ./2.sh: not found
```

**Comment by therealkenc** [comment]
@devoto13  - do you have [developer mode](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#YeBCd1HJ6c6rlqBv.97) enabled in your Windows 10.

**Comment by devoto13** [comment]
@therealkenc Yes, enabling developer mode fixes the symlink problem. Sorry for the false alarm.
