### ISSUE TITLE
WSL can not allocation when the memory less than 3.7G

### ISSUE THREAD

**Issue by ecJon** [Microsoft/WSL#3613]
my win10 version is 17134.WSL can not allocation when the free memory less than 3.7G.

**Comment by ecJon** [comment]
WSL will display Segmentation fault (core dumped) and exit program.I already try it in c program,python program and nodejs program.

**Comment by gvimos** [comment]
> mi versión de win10 es 17134.WSL no se puede asignar cuando la memoria libre tiene menos de 3.7G.
