### ISSUE TITLE
local & external networking issues after 1809 upgrade

### ISSUE THREAD

**Issue by pascoemitch** [Microsoft/WSL#3614]
Microsoft Windows [Version 10.0.17763.55]

After upgrading to Win 1809, connections to localhost & external endpoints both outgoing and incoming fail the majority of the time through WSL.

Connections timeout between running services (postgresql, redis) where on build 1803 they all worked fine.
Tested with Windows Firewall off and problem still exists. But having a VPN active on windows improves general network performance externally, but obviously does not solve local connections.

Tested on 2 machines, rolled one back to previous build and issues went away.

**Ping test**
Without VPN (WSL Bash):
![image](https://user-images.githubusercontent.com/7876802/46904841-f4d3f200-ceea-11e8-8f37-253c93929777.png)

With VPN active (WSL Bash):
![image](https://user-images.githubusercontent.com/7876802/46904831-d1a94280-ceea-11e8-896c-871a93a07e70.png)

**Speedtest**

Chrome no VPN:
![image](http://www.speedtest.net/result/7713990526.png)

Without VPN (WSL Bash):
![image](https://user-images.githubusercontent.com/7876802/46904892-d3273a80-ceeb-11e8-9089-cf77f5b59966.png)

With VPN active (WSL Bash):
![image](https://user-images.githubusercontent.com/7876802/46904860-3c5a7e00-ceeb-11e8-8e29-7371cf7a43a9.png)

**Comment by therealkenc** [comment]
List all your relevant third party system layer software installed on Windows (antivirus or network related) particularly if the software is common to the two machines tested. Third party VPN software in particular would make this a write-off, because there is no way of telling how their driver reacted to the upgrade. If on the other hand they're both unadulterated machines that would be an interesting catch, so good post. Thanks for trying speedtest to demonstrate the diverge. I'm not seeing any change in perf on my unadulterated machine here (VPN or not, I do both) so we're in need-repro territory.

**Comment by pascoemitch** [comment]
Thanks for the response, and you are on to something. 

It seems to be tied to Malwarebytes Real Time Web Protection. Disabling that and the network performance is still a bit slower than in the previous build, but it does function correctly.

It seems it may be tied to #3509.

Not sure on the change between 1803 & 1809 that causes this though as Malwarebytes web protection does not cause this issue on the previous build.

**Comment by therealkenc** [comment]
Alright so we'll chalk this up as 'external' unless we get some more hits to the contrary. You'll need to _uninstall_ Malwarebytes to do any kind of consistent test. _Disabling_ stuff like AV or VPN software rarely (if ever) actually unloads NT filter drivers (this goes for MSFT Defender too, sigh). Not sure what changed in 1809 that causes Malwarebytes grief either, but at least you have a good report on the books here in case someone else hits it. You could ask them, and also use the [Feedback Hub](https://support.microsoft.com/en-ca/help/27932/windows-10-send-us-feedback). Bonne chance.
