### ISSUE TITLE
wslpath resolves symbolic links for objects in them, without the ``-a`` flag

### ISSUE THREAD

**Issue by fakuivan** [microsoft/WSL#3615]
**Please fill out the below information:**
* Your Windows build number:  10.0.17763.55

* What you're doing and what's happening:  
     On PowerShell:
    ```powershell
    $test_on_d = "D:\Users\fakui\test"
    $test_on_c = "C:\Users\fakui\test"
    mkdir $test_on_d
    mkdir "$test_on_d\original"
    mkdir $test_on_c
    New-Item -Type Junction -Value "$test_on_d\original" "$test_on_c\junction"
    New-Item -Type SymbolicLink -Value "$test_on_d\original" "$test_on_c\symlink"
    ```
    On wsl
    ```sh
    cd "$(wslpath "C:\\Users\\fakui\\test")"
    ll "$(pwd)"/*
    wslpath "C:\\Users\\fakui\\test\\symlink\\dir" # Should be resolved to /mnt/c/Users/fakui/test/symlink/dir
    wslpath "C:\\Users\\fakui\\test\\junction\\dir" # Should be resolved to /mnt/c/Users/fakui/test/junction/dir
    wslpath "C:\\Users\\fakui\\test\\symlink" # This converts the path correctly
    wslpath "C:\\Users\\fakui\\test\\junction" # This one too
    wslpath # I didn't add the -a flag. I want it to translate paths, not to resolve symbolic links!
    ```

* What's wrong / what should be happening instead:
    The wslpath command is resolving symbolic links and junctions in the parent paths of the object without the user specifying the ``-a`` flag
     ![image](https://user-images.githubusercontent.com/15100012/46906238-ccda9380-ced6-11e8-8fb6-6b719fe62af4.png)

**Comment by benhillis** [comment]
Thanks for filing.  I'm curious if this is breaking anything in practice or just an annoyance you noticed.

**Comment by fakuivan** [comment]
Mostly an annoyance as there are symbolic links that lead to very long paths covering the whole bash prompt line. This doesn't happen when I open a powershell prompt so I expected that behaviour.

**Comment by ipcjs** [comment]
flutter requires the sdk and the project to be on the same disk, and I currently put them together via a symbolic link. It works fine in cmd, but in wsl, no.😰

https://github.com/flutter/flutter/issues/105395

**Comment by sim590** [comment]
As I'm working with [a mutagen setup to sync two directories of the same project to avoid slow performance][slowp], this issue is a annoying a lot to me. I use `wslpath` a lot to get the path to the corresponding file on the other directory and one of the paths I use under Windows is under a junction so I'm getting this all the time and it's breaking some of my tools since a of our team tool expects a certain path so I have to manually change it every time.

[slowp]: https://j0eii.cwhlabs.com/wsl2-extremely-slow-file-read-fix-mutagen/
