### ISSUE TITLE
Shouldn't this say "you *can't* use WSL commands here"?

### ISSUE THREAD

**Issue by mike-u** [Microsoft/WSL#3617]
* My Windows build number:  Microsoft Windows [Version 10.0.16299.665]  

* What I'm doing and what's happening: I'm trying to install themes for Hyper.JS, my preferred client for accessing WSL.
![Screenshot](https://user-images.githubusercontent.com/8935879/46974720-d1e44200-d092-11e8-8a17-13cc8e771d25.PNG)

* What's wrong / what should be happening instead: I get this error: `Warning! Due to WSL limitations, you can use CLI commands here. Please use Hyper CLI on cmd, PowerShell or GitBash/CygWin.rShell or GitBash/CygWin.`

This is confusing to me. Can or can't I use CLI commands here? I think it's trying to say that I *can't*, and I think this error message should be changed to: `Warning! Due to WSL limitations, you can't use CLI commands here. `

**Comment by benhillis** [comment]
This error message is owned by the Hyper.js folks, not us.
