### ISSUE TITLE
Git fails to create directories due to user folders containing spaces

### ISSUE THREAD

**Issue by marcus-sa** [Microsoft/WSL#3619]
> Symbolic linking doesn't work either, because starting up the WSL terminal, it'll automatically use the source user folder and not the symbolic.

**Reproducing**
Install a clean Windows OS.
Create a new account using your Microsoft account _(or type in a name that has spaces)_
Your user folder will now be named after your full name _(most likely containing spaces)_
Install WSL.

**Example**
Clone a Git repository and watch it fail due to Linux not supporting to make directories or read directories without escaping the spaced folder or file with single/double quotes.

**Comment by DHowett** [comment]
```
(Libra) /tmp/take0raMWC % mkdir "if this does not work it is almost certainly a bug in git"
(Libra) /tmp/take0raMWC % cd if\ this\ does\ not\ work\ it\ is\ almost\ certainly\ a\ bug\ in\ git
(Libra) /tmp/take0raMWC/if this does not work it is almost certainly a bug in git % git clone git@gitlab.howett.net:go/plist
Cloning into 'plist'...
remote: Enumerating objects: 953, done.
remote: Counting objects: 100% (953/953), done.
remote: Compressing objects: 100% (340/340), done.
remote: Total 953 (delta 631), reused 924 (delta 608)
Receiving objects: 100% (953/953), 242.35 KiB | 5.27 MiB/s, done.
Resolving deltas: 100% (631/631), done.
(Libra) /tmp/take0raMWC/if this does not work it is almost certainly a bug in git % ls plist/README.md
plist/README.md
```

If git doesn't support a particular directory name format, that's a git issue.
_What error are you getting, specifically?_

**Comment by therealkenc** [comment]
> Resolving deltas: 100% (631/631), done.

Yep.

> What error are you getting, specifically?

And a gist of the `strace` log. And Win10 build number. And distro. And git version. And the git repo being cloned (or a public facsimile thereof). And the full pathname into which the repo is being cloned. And if that path is on `/mnt/c` then the mount options being used.

> if this does not work it is almost certainly a bug in git

There's no bug in `git`.
