### ISSUE TITLE
Specific language(Korean) 'tput' results are being strangely output

### ISSUE THREAD

**Issue by uyu423** [Microsoft/WSL#362]
Language : Korean
### General Result (Ubuntu Bash)

![2016-05-14 09-03-46](https://cloud.githubusercontent.com/assets/8033320/15264856/50c70a38-19b3-11e6-8969-12c44bffe487.png)
### Strangely Result (Windows Bash)

![default](https://cloud.githubusercontent.com/assets/8033320/15264855/50bab76a-19b3-11e6-92ef-6b15572f6420.PNG)
#### 'The following strings are strange output for the result of the tput commands
- '컴퓨터정보공학부 학회 F.A.N'
- '학생용 실습 서버'
- '작업 환경'
- '기타 정보'
- '메모리, HDD 사용량이 90% 이상이면 FAN 임원진에게 알려주세요.'
#### But the English output is normal
- 'last modified : 160330-yowu'
#### importing used shell script

<pre>
#!/bin/bash
# Shell Script by Yowu (uyu423@gmail.com / Yu Yongwoo, CSIE '10
publicIP=`wget http://ipecho.net/plain -O - -q ; echo 2> /dev/null`
TotalPMem=`free -m | grep -v total | grep -v Swap | awk '{print $2}'`
UsingPMem=`free -m | grep -v total | grep -v Swap | awk '{print $3}'`
UsingPMemPer=`expr \( ${UsingPMem} \* 100 \/ ${TotalPMem} \)`
TotalVMem=`free -m | grep -v total | grep -v Mem | awk '{print $2}'`
UsingVMem=`free -m | grep -v total | grep -v Mem | awk '{print $3}'`
UsingVMemPer=`expr \( ${UsingVMem} \* 100 \/ ${TotalVMem} \)`
TotalHDD=`df -h | grep sda1 | awk '{print $2}'`
UsingHDD=`df -h | grep sda1 | awk '{print $3}'`
UsingHDDPer=`df -h | grep sda1 | awk '{print $5}'`

#color
NONE='\033[0m'
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
MAGENTA=`tput setaf 5`
CYAN=`tput setaf 6`

echo "=================================================================================="
echo "||                                        ||"
printf "||  가톨릭대학교 ${MAGENTA}컴퓨터정보공학부 학회 F.A.N${NONE} 의 ${GREEN}학생용 실습 서버${NONE}입니다.  ||\n"
echo "||                                        ||"
printf "||  = ${CYAN}작업 환경${NONE} =                             ||\n"
echo "||        배포판 정보    : Ubuntu 16.04 LTS (64 bit)         ||"
echo "||        커널 정보   : `uname -r`                ||"
echo "||        메모리 사용량 : ${UsingPMem}M / ${TotalPMem}M (${UsingPMemPer}%)              ||"
echo "||        SWAP 사용량  : ${UsingVMem}M / ${TotalVMem}M (${UsingVMemPer}%)              ||"
echo "||        HDD 사용량   : ${UsingHDD} / ${TotalHDD} (${UsingHDDPer})                ||"
echo "||                                        ||"
printf "||  = ${CYAN}기타 정보${NONE} =                             ||\n"
echo "||        마지막 재부팅     : `uptime -s`               ||"
echo "||        공인 IP   : ${publicIP}               ||"
echo "||        gcc 버전  : `gcc --version | grep gcc | awk '{ print $4 }'`                       ||"
echo "||        javac 버전    : 9-internal                    ||"
echo "||                                        ||"
printf "||  * 실습에 필요한 패키지가 설치되지 않은 경우 임원진에게 알려주세요.  ||\n"
printf "||  * ${YELLOW}메모리, HDD 사용량이 90%% 이상이면 FAN 임원진에게 알려주세요.${NONE}        ||\n"
echo "||    * 시스템 자동 업데이트 : 매주 토요일 새벽 3시              ||"
echo "||                                        ||"
printf "||                      ${BLUE}last modified : 160330-yowu${NONE}   ||\n"
echo "||                                        ||"
echo "=================================================================================="
</pre>

- And Do not have ever Korean support plan?

**Comment by youngminz** [comment]
Is there any update about this bug?

**Comment by uyu423** [comment]
No. Korean Language(Hangul) output still does not work properly.

**Comment by youngminz** [comment]
![image](https://cloud.githubusercontent.com/assets/5145369/25049134/2adad888-217b-11e7-916a-1918dcfa602d.png)
It seems like Hangul print problem is fixed now after upgrading to `Windows Version 10.0.15063` 👍

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is old and has likely been fixed since it was opened. If not, please post a new issue in the [Console GitHub Repo](https://github.com/Microsoft/console)
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
