### ISSUE TITLE
wsl.exe eval does not respect the user's default shell

### ISSUE THREAD

**Issue by kekstee** [Microsoft/WSL#3620]
wsl.exe does not respect the configured default shells on eval calls, while wsl.exe with no argument does.

* Version `Microsoft Windows [Version 10.0.16299.726]`

## Steps to reproduce
1. Set a different shell for the user 
    ```sh
    sudo apt-get install zsh
    chsh user -s $(which zsh)
    ```
2. Run `wsl` with no arguments and `echo $0` from the new prompt. It correctly returns `-zsh`
3. Run `wsl eval 'echo $0'`, it will show `/bin/bash`

I would expect both to be the same.

## Use case
I want to launch a terminal application from Windows via the eval call, but since the environment lacks the correct default shell information I have to work around it by launching alternative shells from `.bashrc` based on the `$TERM` variable.

P.S. I now realize this might be closely related to the login behaviour explained [in this comment](https://github.com/Microsoft/WSL/issues/352#issuecomment-264217088)

**Comment by therealkenc** [comment]
Can't reproduce this here on 18262. It is _possible_ something changed since 16299, but I'm too lazy to dupe search tonight. 
```
C:\>wsl eval 'echo $0'
/usr/bin/zsh
```

**Comment by Biswa96** [comment]
Try to change the default shell of that specific user in `/etc/passwd` file.

**Comment by kekstee** [comment]
It is set correctly in `/etc/passwd` and works with the default wsl initialization.

Nice to hear that this might already be fixed in future releases. If this doesn't get any further reports I should be able to test it with a newer version in maybe two weeks or thereabouts.

**Comment by benhillis** [comment]
@kekstee - This behavior was changed during the 1809 timeframe.  Previously wsl.exe would always use /bin/bash.
