### ISSUE TITLE
Missing privilege separation directory: /run/sshd

### ISSUE THREAD

**Issue by ddatsh** [Microsoft/WSL#3621]
/etc/ssh/sshd_config

UsePrivilegeSeparation no

```
bash.exe -c 'sudo /usr/sbin/sshd -D'
[sudo] password for xxx:
/etc/ssh/sshd_config line 37: Deprecated option UsePrivilegeSeparation
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
Missing privilege separation directory: /run/sshd
```

**Comment by therealkenc** [comment]
> Could not load host key: /etc/ssh/ssh_host_rsa_key

#3303 ([message](https://github.com/Microsoft/WSL/issues/3303#issuecomment-397507923)) and friends.

> Missing privilege separation directory: /run/sshd

Same as [ansible-container#141](https://github.com/ansible/ansible-container/issues/141). Goes spirituality to #2530 and #994 (depending on your disposition).

You can comment out the UsePrevilegeSeaparation line. It is depreciated as mentioned in the error.

```
# ssh-keygen -A
# mkdir -p /run/sshd
```
