### ISSUE TITLE
binary install of django; missing "manage.py" file

### ISSUE THREAD

**Issue by bad-banana** [Microsoft/WSL#3623]
Windows 10 1803
Ubuntu 18.04 wsl

1. used pip to install django (whatever version)
2. create project:
`django-admin.py startproject addressbook .`
3. it should produce the following file/s:
manage.py
./addressbook
    __init__.py
    settings.py
    urls.py
    wsgi.py
4. "manage.py" is missing

same steps done on ubuntun VM in Virtualbox or VMware doesn't have that missing file.

**Comment by therealkenc** [comment]
No takers on question posed. Suggest checking with the django community.
