### ISSUE TITLE
Bash, `cd` command - Cannot enter folder with (escaped!) space in name

### ISSUE THREAD

**Issue by PsychoXIVI** [Microsoft/WSL#3625]
Opened `bash` for Windows. Entered folder with folder with escaped space in name.

![image](https://user-images.githubusercontent.com/23557839/47272510-1c7c2780-d587-11e8-8d18-390bc760a16a.png)

Cannot enter the folder. 

Meanwhile on Ubuntu works.

![image](https://user-images.githubusercontent.com/23557839/47272494-e9399880-d586-11e8-9e28-3f0c4e573088.png)

Windows build number: `Microsoft Windows [Version 10.0.16299.431]`

**Comment by MetGang** [comment]
¯\_(ツ)_/¯

**Comment by therealkenc** [comment]
Well as an initial matter those screencaps don't looks the same, so you've got variables to eliminate. Your CWD is a different path, and one has case sensitivity as a possible gotcha. And `cd` is a shell builtin, and your shell setup looks suspiciously different in the before and after pics.

Can't repro here with '`/tmp/issueWithBashChangeDirectory/directory with space`' on 18262 with unadulterated `bash`. Hesitant to blame your Windows version though. Do:
```
$ mkdir '/tmp/a b c'
$ strace -f -o cd.strace bash -c "cd '/tmp a b c'"
```
Link a gist of `cd.strace`, or just post the lines around the `chdir(2)` near the bottom. Maybe it'll just be a `ENOENT` but it's a start.

**Comment by DHowett** [comment]
That looks like a pretty highly-customized bash profile. Can you run `type cd` and see if it's been (poorly) redefined to be _a function that doesn't support spaces_?

If you get anything but "cd is a shell builtin", this is by no means a WSL problem.

**Comment by therealkenc** [comment]
> That looks like a pretty highly-customized bash profile. 

Maybe that's the variable, but `cd` is an odd builtin to mess with; seems doubtful. Either way, bailing on absent template.
