### ISSUE TITLE
"wsl.exe" and "bash.exe" have the same file system but different $PATH

### ISSUE THREAD

**Issue by mohsenkhanpour** [Microsoft/WSL#3627]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
 Microsoft Windows [Version 10.0.17134.345]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I am switching from Git-Bash to WSL Bash on my development environment (VS Code), according to these issues ([1](https://github.com/Microsoft/vscode/issues/51455), [2](https://github.com/Microsoft/vscode/issues/49713)), it is suggested to use WSL.exe instead of Bash.exe. However when I use WSL.exe the previously installed packages are not loaded into the WSL's $PATH.

Here you can see the screenshots once using "wsl.exe" and once using "bash.exe" as you can see Ruby is available in bash.exe's $PATH but not available in wsl.exe's $PATH.

WSL:
![screenshot_1](https://user-images.githubusercontent.com/28626829/47322357-7acb0800-d664-11e8-8a4d-62107f1205b3.jpg)

Bash:
![screenshot_2](https://user-images.githubusercontent.com/28626829/47322358-7acb0800-d664-11e8-8003-3393a772d9f6.jpg)

* What's wrong / what should be happening instead:

The interesting point is I once tried to install Ruby again on WSL, after I did it didn't install much of dependencies saying they were available (so "wsl" and "bash" are using the same file system) and I could run Ruby. However after running `wsl` again they were gone (removed from the $PATH).

Now I don't have any problems with using `bash` with VS Code, but as it is suggested both by VS Code and WSL maintainers to use `wsl` instead of `bash`, I want to do it the standard way.

Now regarding this problem I have some questions:
1. Why does my $PATH reset every time I run a new instance of WSL?
2. What is the risk of using `bash` instead of `wsl` as suggested by the community?
3. How can I get my $PATH on `wsl` to be the same as `bash`?

**Comment by bardware** [comment]
Are you sure `wsl` and `bash` are the same? How does the result of `wslconfig /l` look?

**Comment by therealkenc** [comment]
I think this is related to the fact that you changed your default shell. But that's a guess. `bash.exe` is deprecated and no longer being maintained so no actionable.

**Comment by jeansordes** [comment]
So what's the solution ? Switching to another distro if ours doesn't work ? (I've downloaded "Ubuntu" instead of "Ubuntu 18 LTS")

Is this a bug or is it intended ?

**Comment by therealkenc** [comment]
> Is **this** a bug or is it intended ?

The answer to that question was:

> I suspect if you are on 1809 and use `wsl.exe` you'll get reasonable(ish) behavior. Ref #3620.

You are on RS4 aka 1803 aka 17134.

['Suspect' caveat because neither the present issue nor #3855 contains any details necessary to reproduce 'this' using software distributed by MSFT or Canonical, whatever 'this' may be.]

**Comment by jeansordes** [comment]
Alright, in my case (#3855), it was `nvm` that was not working properly, so I simply found a way of not using `nvm` and use `npm` directly
