### ISSUE TITLE
Unable to call fakeroot-tcp after 1809

### ISSUE THREAD

**Issue by M1K8** [microsoft/WSL#3629]
Windows Version: Microsoft Windows [Version 10.0.17763.55]

Since updating to 1809, I have been unable to run fakeroot-tcp, meaning I have been unable to successfully run anything that requires a fakeroot environment, such as building the "yay" package manager. It appears to have something to do with the Windows firewall, as a prompt to allow "faked" appeared when I first ran fakeroot. Allowing it through both public and private firewalls does not help the issue.

I have attached strace logs for both Ubuntu and Arch below.
[fctpUbuntu.log](https://github.com/Microsoft/WSL/files/2506070/fctpUbuntu.log)
[fctpArch.log](https://github.com/Microsoft/WSL/files/2506071/fctpArch.log)

Repro (Ubuntu):
1. Install fakeroot
2. Run sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp 
3. Run fakeroot. Observe error.

Repro (Arch):
1. Install prebuilt fakeroot-tcp
2. Attempt to build the yay package manager
3. Observe error when fakeroot is ran.

**Comment by therealkenc** [comment]
The `strace` doesn't appear to be threaded (`-f`). It will probably just show connection refused but it's a start.

**Comment by kayhayen** [comment]
I can call it with current 1910 just fine, however I get a firewall prompt for each run of a pbuilder, each in a different build directory. how to setup the rule to allow it? Seems to work even if I ignore the firewall prompt, but they are annoying.
