### ISSUE TITLE
Spaces break line in $ENV_VARIABLE

### ISSUE THREAD

**Issue by SoleSensei** [Microsoft/WSL#3632]
Hey, there.
I stucked with same problem as [here](https://github.com/Microsoft/WSL/issues/1766#issue-213017084)
__Example:__
```bash
SoleSensei@SoleSurface:~$ $BROWSER
-bash: /mnt/c/Program: No such file or directory
SoleSensei@SoleSurface:~$ export BROWSER='"/mnt/c/Program\ Files/Firefox/firefox.exe"'
SoleSensei@SoleSurface:~$ $BROWSER
-bash: "/mnt/c/Program\: No such file or directory
SoleSensei@SoleSurface:~$ export BROWSER="/mnt/c/Program\ Files/Firefox/firefox.exe"
SoleSensei@SoleSurface:~$ $BROWSER
-bash: /mnt/c/Program\: No such file or directory
SoleSensei@SoleSurface:~$ export BROWSER=/mnt/c/Program\ Files/Firefox/firefox.exe
SoleSensei@SoleSurface:~$ $BROWSER
-bash: /mnt/c/Program: No such file or directory
SoleSensei@SoleSurface:~$ export BROWSER='/mnt/c/Program Files/Firefox/firefox.exe'
SoleSensei@SoleSurface:~$ $BROWSER
-bash: /mnt/c/Program: No such file or directory
SoleSensei@SoleSurface:~$ xdg-open https://github.com
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: /mnt/c/Program: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: /mnt/c/Program: not found
xdg-open: no method available for opening 'https://github.com'
```
Path just breaks on first space. Any ideas?

_Originally posted by @SoleSensei in https://github.com/Microsoft/WSL/issues/1766#issuecomment-432814055

**Comment by benhillis** [comment]
You'll need to quote your environment variable usage:
"$BROWSER"

https://superuser.com/questions/616351/spaces-in-linux-environmental-variables

**Comment by SoleSensei** [comment]
@benhillis, okay, but what about xdg-open and other applications using unquoted variable environments?

**Comment by benhillis** [comment]
@SoleSensei - Their scripts should be updated because they are incorrect.  Spaces are not common in Linux paths, but they are not illegal either.

**Comment by SoleSensei** [comment]
okay, thanks, so i'm closing issue. And trying not to use Windows paths with spaces in WLS.

**Comment by imadelq** [comment]
I have used :
export BROWSER='eval "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"'

It worked for me.
