### ISSUE TITLE
RFE: support windows path in WSL like cygwin

### ISSUE THREAD

**Issue by fenchu** [Microsoft/WSL#3633]
Hi

In cygwin I can write:
`cd /cygdrive/d/python` or `cd d:\\python`

Could you support the same in WSL:
```
cd /mnt/d/python
cd d:\\python
bash: cd: d:\python: Fila eller mappa finnes ikke
```

```
$ uname -a
Linux MB-PC 4.4.0-18262-Microsoft #1000-Microsoft Fri Oct 12 14:14:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks

**Comment by DarthSpock** [comment]
Navigation is pure linux style: `cd /mnt/c/*some random path*`. Any drive that uses a few (but not all) windows file systems such as NTFS and FAT32 are supported through DrvFS (what is what provides the interop).

**Comment by Biswa96** [comment]
@fenchu Well you can do something like this: `cd $(wslpath D:\\MyFolder)`.

**Comment by benhillis** [comment]
@Biswa96's solution is going to be your best bet.
