### ISSUE TITLE
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)

### ISSUE THREAD

**Issue by zhangshengsheng** [Microsoft/WSL#3634]
root@SKY-20181022EYQ:/home/ubuntu# uname -a
Linux SKY-20181022EYQ 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
root@SKY-20181022EYQ:/home/ubuntu# iptables -L
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by zhangshengsheng** [comment]
root@SKY-20181022EYQ:/home/ubuntu# iptables -t nat -L
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by therealkenc** [comment]
Was #767. UserVoice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/32025199-support-iptables). Tempting to close this on procedural grounds for lack of [ISSUE_TEMPLATE.md](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) but I guess this is as good a landing zone as any per precedent. Ref #2291 ([message](https://github.com/Microsoft/WSL/issues/2291#issuecomment-411765522)).
