### ISSUE TITLE
Unable to get DBus System bus connection: Failed to connect to socket: System_bus_socket missing

### ISSUE THREAD

**Issue by BlackCentipede** [Microsoft/WSL#3635]
My Windows Build Version: Microsoft Windows [Version 10.0.17134.320]
My Linux Version: Ubuntu 18.04.1 LTS (Bionic Beaver)
My Kernel Version: 4.4.0-17134-Microsoft

I wanted to be able to connect to Xen Server or other virtualization servers via Libvirt and Libvirt requires having a daemon running in order to use Libvirt API. The problem with that is the D-Bus socket is being missing on WSL.

![result](https://user-images.githubusercontent.com/9369939/47545649-9d4e6280-d8aa-11e8-885b-c46f2a87b9a1.png)

To reproduce the steps:

`sudo apt-get update`

`sudo apt-get install libvirt-daemon`

`sudo libvirtd`

There seems to be a lack of support for D-bus for WSL, this is preventing me from porting my workspace on Linux to Windows. My intention isn't to run any sort of virtualization on this library, but to use it to connect to existing virtualization server external to my machine and to migrate any settings/configurations on my machine for virtualization over to those servers.

**Comment by therealkenc** [comment]
#1579 ([message](https://github.com/Microsoft/WSL/issues/1579#issuecomment-271555310))

> The problem with that is the D-Bus socket is being missing on WSL.

That socket isn't part of WSL (or Linux™). It's part of freedesktop.org.
