### ISSUE TITLE
git stash or other command in WSL change/remove file permissions

### ISSUE THREAD

**Issue by kivi** [Microsoft/WSL#3636]
* Your Windows build number: 17134.345 pro
* What you're doing and what's happening: on WSL running Ubuntu: **git stash** in my home directory /mnt/c/Users/me/project
* What's wrong / what should be happening instead: the file permission are changed. Wheater in WSL nor in Explorer I am able to write the file anymore. I need to restart in recovery mode, and delete the files from command line, to continue.

**Comment by therealkenc** [comment]
#81

**Comment by kivi** [comment]
@mkarpoff  I don't have a wsl.conf, I think since I never created one so there must be some defaults.
 
@therealkenc I am not agreeing with you, it is not the same as discussed in #81 - chmod generally in my wsl. Somehow some files I am accessing within WSL are locked and this happens up to now only on files in directories I am using GIT. I also edit the files outside of WSL with vsCode or File Explorer. I think it happens when I use git (installed on WSL/Ubung) command it removes some important parts of permissions or ACL and I am not able do any write operations on that file(s) anymore inside and outside WSL.
I have also tried to repair the files in PowerShell but no success. The only method I know is to restart the computer, start in recovery mode. Use the advanced tools and access C: on a Cmd Line without booting Windows.

**Comment by mkarpoff** [comment]
@kivi I actually think therealkenc is correct this is a chmod on mounted drive issue. WSL by default mounts the drive so that all files have permission 777. It only actually applies the change to permission on write to the file. This is why when you use git it makes the change only when you try to apply the changes. Create a wsl.conf file and set it up so that saves metadata of files and doesn't change them unless you explicitly change it. As an example here is my config

```
[automount]
#This Mounts the drives (pretty sure this is default)
enable=true
#metadata: save file metadata (otherwise it makes it 777)
#masks (Sets them to Ubuntu defaults) make them whatever you want
options=metadata,uid=1000,gid=1000,umask=0027,fmask=0137,dmask=0027

[interop]
# enable launch of Windows binaries; default is true
enabled=false
# append Windows path to $PATH variable; default is true
appendWindowsPath=false
```
