### ISSUE TITLE
Set path environment variable in WSL-Ubuntu

### ISSUE THREAD

**Issue by leyei** [Microsoft/WSL#3639]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.345]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Need to add the folders to PATH environment variable in WSL-Ubuntu and when I echo $PATH, I get path variables from Windows machine.  How can I add path to WSL (Ubuntu) and it is recognised in WSL- Ubuntu too?

**Comment by therealkenc** [comment]
> How can I add path to WSL (Ubuntu) and it is recognised in WSL- Ubuntu too?

I cannot parse that sentence.
