### ISSUE TITLE
application in windows do not have access to root folder in bash

### ISSUE THREAD

**Issue by Himanshuvashist** [Microsoft/WSL#3640]
* _**Windows build number**_:  (Version 10.0.17134.376)

* _**What you're doing and what's happening**_:  I am opening files in **```~```** through application(sublime text editor or visual studio code which is on my window machine  but, it seems that application do not have access above **"c"** **"d"** **"e"** drives(windows files only have access to **```/mnt```** *(see pitchure 2)*), i wanted to open **```.gitconfig```**, **```.bash_profile```** and **```.bashrc```** file which are saved in **```/home/user/```** or **```~```**,but it was not able to open it because the applications were taking wrong reference location. see in pitchure below. 
![1](https://user-images.githubusercontent.com/35025815/47622741-9a63a400-db2e-11e8-8c5a-44a28b11f162.png)

* _**What's wrong / what should be happening instead**_: Problem is windows (application in windows) have access to these only (see below )
![2](https://user-images.githubusercontent.com/35025815/47622796-4ad1a800-db2f-11e8-96ed-57759d448a56.png)
I want that windows applications can also access these directories, so i can use windows applications to access files in these directories and do my job(pitchure shown below)
![3](https://user-images.githubusercontent.com/35025815/47622820-a2701380-db2f-11e8-8d20-7e249e529fad.png)

**Comment by therealkenc** [comment]
#1524. User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341279-a-file-created-in-c-users-user-appdata-local-lx).
