### ISSUE TITLE
WSL apt-get upgrade error fail to set securebits to 024/0x14 windows ver. 10.0.17134..345

### ISSUE THREAD

**Issue by dklmandl** [microsoft/WSL#3641]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.
Every time I run the apt-get upgrade or apt-get install libdvd.pkg in WSL, I get these dkpg error messages and failures

![capture2upgrade](https://user-images.githubusercontent.com/44600472/47703083-6c956280-dbf5-11e8-8add-3c3c52d25bd8.PNG)

Is there a fix for this issue?

I ran sudo apt-get update, and upgrade , also and all the reinstall and reconfigure commands in WSL nothing has work

your help would be greatly appreciated.

Thank you

**Comment by vanjavk** [comment]
same here
![image](https://user-images.githubusercontent.com/1491765/54389846-61713980-46a1-11e9-94ee-a623ef8231b7.png)

**Comment by genlintan** [comment]
I have the same problem:
Setting up libdvd-pkg (1.4.2-1-1) ...
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.2.orig.tar.bz2: OK
libdvd-pkg: Unpacking and configuring...
libdvd-pkg: Building the package... (it may take a while)
libdvd-pkg: Build log will be saved to /usr/src/libdvd-pkg/libdvdcss2_1.4.2-1~local_amd64.build
failed to set securebits to 024/0x14
dpkg: error processing package libdvd-pkg (--configure):
 installed libdvd-pkg package post-installation script subprocess returned error exit status 1
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.2.orig.tar.bz2: OK
libdvd-pkg: Unpacking and configuring...
libdvd-pkg: Building the package... (it may take a while)
libdvd-pkg: Build log will be saved to /usr/src/libdvd-pkg/libdvdcss2_1.4.2-1~local_amd64.build
failed to set securebits to 024/0x14
E: Sub-process /usr/bin/dpkg returned an error code (2)
by Genlin Tan

**Comment by therealkenc** [comment]
It seems this one was overlooked and eventually buried because there were no reproduction steps provided. It just didn't get tagged.

**Comment by therealkenc** [comment]
New LZ can be #4278.
