### ISSUE TITLE
drvfs: file type 'socket' is not shared between wsl and windows

### ISSUE THREAD

**Issue by Gerrit-K** [Microsoft/WSL#3643]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.345]

* What you're doing and what's happening:
  * **Background**: I was trying to use my ssh agent which runs on Windows from within WSL using a Unix socket (similar to [this solution](https://github.com/mendhak/keepass-and-keeagent-setup) but with WSL instead of git bash), but I couldn't get it to work. After hours of frustrating google searches, I think I can narrow it down to a broken SSH_AUTH_SOCK.
  * **actual bug**: I thought that Windows and WSL now support sockets as described [here](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/). But the socket type doesn't seem to be propagated correctly between the systems (if created on a shared path). If I create a socket in WSL, it is recognized as a socket in WSL but as a regular file in git bash on Windows and vice versa. The following commands should demonstrate this:  
    * In WSL:
        ```
        $ mount -l
        rootfs on / type lxfs (rw,noatime)
        sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
        proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
        none on /dev type tmpfs (rw,noatime,mode=755)
        devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
        none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
        none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
        none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
        none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
        binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
        E: on /mnt/e type drvfs (rw,noatime,uid=1000,gid=1000)
        F: on /mnt/f type drvfs (rw,noatime,uid=1000,gid=1000)
        C: on /mnt/c type drvfs (rw,relatime,uid=1000,gid=1000,umask=22,fmask=11,metadata)

        $ # create a dummy unix socket
        $ python3 -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/mnt/c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-wsl')"

        $ stat /mnt/c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-wsl
        File: /mnt/c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-wsl
        Size: 0               Blocks: 0          IO Block: 512    socket
        Device: ch/12d  Inode: 7318349394503710  Links: 1
        Access: (0777/srwxrwxrwx)  Uid: ( 1000/  gerrit)   Gid: ( 1000/  gerrit)
        Access: 2018-10-30 23:47:27.008807800 +0100
        Modify: 2018-10-30 23:47:27.008807800 +0100
        Change: 2018-10-30 23:47:27.008807800 +0100
        Birth: -

        $ # inspect the socket that was created by keepass/keeagent:
        $ stat /mnt/c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-win
        File: /mnt/c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-win
        Size: 53              Blocks: 0          IO Block: 512    regular file
        Device: ch/12d  Inode: 18014398509501744  Links: 1
        Access: (0744/-rwxr--r--)  Uid: ( 1000/  gerrit)   Gid: ( 1000/  gerrit)
        Access: 2018-10-30 23:41:22.669863500 +0100
        Modify: 2018-10-30 23:11:05.770805700 +0100
        Change: 2018-10-30 23:11:05.770805700 +0100
        Birth: -
        ```
    * Now the same last two commands in git bash on Windows:
        ```
        $ stat /c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-wsl
        File: /c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-wsl
        Size: 0               Blocks: 0          IO Block: 65536  regular empty file
        Device: 94f3aee8h/2498997992d   Inode: 7318349394503710  Links: 1
        Access: (0644/-rw-r--r--)  Uid: (197609/  Gerrit)   Gid: (197121/ UNKNOWN)
        Access: 2018-10-30 23:47:27.008807800 +0100
        Modify: 2018-10-30 23:47:27.008807800 +0100
        Change: 2018-10-30 23:47:27.008807800 +0100
        Birth: 2018-10-30 23:47:27.008807800 +0100

        $ stat /c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-win
        File: /c/Users/Gerrit/AppData/Local/Temp/.ssh-sock-win
        Size: 0               Blocks: 1          IO Block: 65536  socket
        Device: 1e0078h/1966200d        Inode: 18014398509501744  Links: 1
        Access: (0700/srwx------)  Uid: (197609/  Gerrit)   Gid: (197121/ UNKNOWN)
        Access: 2018-10-30 23:41:22.669863500 +0100
        Modify: 2018-10-30 23:11:05.770805700 +0100
        Change: 2018-10-30 23:11:05.770805700 +0100
        Birth: 2018-10-30 22:51:33.685576000 +0100
        ```

* What's wrong / what should be happening instead:
  * The sockets are only recognized as sockets on the systems they were created on. On the other system, they are recognized as regular files (Is this one of the limitations mentioned [here](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/)? If so, please apologize, I'm not really that familiar with the matter).
  * I would love to see the sockets working between Windows and WSL. If that's (currently) not possible, I would also appreciate alternative solutions to my initial problem (i.e. communicating with the SSH_AUTH_SOCK that was created by keepass/keeagent from within WSL)

**Comment by therealkenc** [comment]
> I think I can narrow it down to a broken SSH_AUTH_SOCK.

Yeah I _believe_ that translates (roughly) into an  [`SO_PASSCRED`](http://man7.org/linux/man-pages/man7/unix.7.html) + `SCM_RIGHTS`, mentioned as unsupported in the [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/). I couldn't find a clever reference in the OpenSSH source to cite.

> Now the same last two commands in git bash on Windows
> The sockets are only recognized as sockets on the systems they were created on.

The rub here is one of the systems "they were created on" is [MSYS2](http://www.msys2.org/) which isn't a MSFT product. This can seem nonobv because "Git for Windows" is a psudo-MSFT product maintained by MSFT [people](https://github.com/git-for-windows), and [`ssh-agent(1)`](http://man7.org/linux/man-pages/man1/ssh-agent.1.html) and [`git(1)`](http://man7.org/linux/man-pages/man1/git.1.html) and (per your repro) the [`stat(1)`](http://man7.org/linux/man-pages/man1/stat.1.html) _look_ real similar in WSL and win32. But that win32 `stat(2)` (and the underlying libc it calls) hasn't the faintest what WSL has done with that Windows file object. The two systems have different worldviews wrt `AF_LOCAL` sockets.

> I would love to see the sockets working between Windows and WSL. 

Me too. It should be possible to get the "modern" (scare quote) Windows `AF_UNIX` named sockets working all the way up through the MSYS2 libc to (say) `stat(1)` (or `python(1)` or `ssh-agent(1)`). I tried a non-exhaustive search to see if anything like that was in the works, but didn't find much. That does not mean it doesn't exist; I don't hang out in the MSYS2/MinGW/Cygwin communities except in passing.

But _even_ if you had `AF_UNIX` support in MSYS2, I think you are going to brick-wall fast on `SCM_RIGHTS`. The error you are seeing (which you don't state) related to `SSH_AUTH_SOCK` _isn't_ going to be because of `SCM_RIGHTS` _limitations_. The socket use hasn't made it that far. Adding `SCM_RIGHTS` support worms real fast too, because while you are nominally "local" (in the filesystem sense) you aren't in the same process space.

> If that's (currently) not possible, I would also appreciate alternative solutions to my initial problem (i.e. communicating with the SSH_AUTH_SOCK that was created by keepass/keeagent from within WSL)

Nothing straightforward for you off the cuff, and I am past my TL;DR quota already. It is an honest enough ask.

**Comment by Gerrit-K** [comment]
Thank you *very* much for the detailed and fast response! Although not the answer I was hoping for, this probably saved me another couple of hours of unsuccessful research. Now I'll rather start to look for alternatives, e.g. directly launching and adding the key to `ssh-agent` within WSL. 

Regarding the issue: I'll close it since you answered my question and (as far as I understand) this won't be possible anytime soon. but feel free to reopen it if you want to keep it on the list.

Oh and for the sake of completeness, here's the command and output in question:

```
$ ssh -AvvvT git@github.com
OpenSSH_7.4p1 Debian-10+deb9u4, OpenSSL 1.0.2l  25 May 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "github.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to github.com [192.30.253.113] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/gerrit/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
debug1: Remote protocol version 2.0, remote software version babeld-ec6cfddd
debug1: no match: babeld-ec6cfddd
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to github.com:22 as 'git'
debug3: hostkeys_foreach: reading file "/home/gerrit/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/gerrit/.ssh/known_hosts:3
debug3: load_hostkeys: loaded 1 keys from github.com
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256
debug2: host key algorithms: ssh-dss,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib,zlib@openssh.com
debug2: compression stoc: none,zlib,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug3: hostkeys_foreach: reading file "/home/gerrit/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/gerrit/.ssh/known_hosts:3
debug3: load_hostkeys: loaded 1 keys from github.com
debug3: hostkeys_foreach: reading file "/home/gerrit/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/gerrit/.ssh/known_hosts:4
debug3: load_hostkeys: loaded 1 keys from 192.30.253.113
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /home/gerrit/.ssh/known_hosts:3
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: Permission denied
debug2: key: /home/gerrit/.ssh/id_rsa ((nil))
debug2: key: /home/gerrit/.ssh/id_dsa ((nil))
debug2: key: /home/gerrit/.ssh/id_ecdsa ((nil))
debug2: key: /home/gerrit/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/gerrit/.ssh/id_rsa
debug3: no such identity: /home/gerrit/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/gerrit/.ssh/id_dsa
debug3: no such identity: /home/gerrit/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/gerrit/.ssh/id_ecdsa
debug3: no such identity: /home/gerrit/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/gerrit/.ssh/id_ed25519
debug3: no such identity: /home/gerrit/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
```

The hint that got me looking at the socket was `debug1: pubkey_prepare: ssh_get_authentication_socket: Permission denied`.

Again, thanks for your help!

**Comment by therealkenc** [comment]
> I'll close it since you answered my question and (as far as I understand) this won't be possible anytime soon.

Well "anything is possible" :). It isn't a WSL actionable so closing is appropriate thanks (`ssh-agent` on WSL works alright ref #3183). But that begs the pretty bloody valid question: "Okay whose actionable is it then?", and that doesn't have an entirely straightforward answer. _In principle_ you could try your luck over in the Git for Windows [tracker](https://github.com/git-for-windows/git/issues), but they probably won't be thrilled to hear from you since it isn't really a `git` issue either. That said, if there ever was a use case for the newfangled Windows AF_LOCAL functionality, yours is pretty much it, so you might find a sympathetic audience over there. I should also caveat that I haven't deep dived this at all, and for all I know lack of `SCM_RIGHTS` isn't a hard blocker or could be fudged or isn't even a problem (I'd feel more confident if I found a good reference in the OpenSSH source but I didn't in a quick). Anyway good post, and as mentioned, entirely reasonable ask. Bonne chance.
