### ISSUE TITLE
No libGL libraries when running Gazebo from ROS

### ISSUE THREAD

**Issue by buddha314** [Microsoft/WSL#3644]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```ver

Microsoft Windows [Version 10.0.17134.345]
````

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
 gazebo
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

* What's wrong / what should be happening instead:

[Gazebo](http://gazebosim.org/) should launch

**Comment by buddha314** [comment]
This question on [askubuntu](https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t) seems to provide a clue as to what's going on.

**Comment by buddha314** [comment]
I'm hoping posterity gets some use of this.  My next issue was the black screen issue addressed in this ticket:  https://github.com/Microsoft/WSL/issues/3368  

I fiddled around a bit, then tried

```
export GAZEBO_IP=127.0.0.1
```

and was able to see the scene.

**Comment by therealkenc** [comment]
You can follow along in #3368. `memfd()` is likely soft and is #3542. Your Alsa errors are #237 but better #486. So dupes all around.

> This is a lot of hoops to jump through.

No more than getting Gazebo up on a headless Linux box with `CONFIG_DRM=n`. No WSL actionable here.

**Comment by buddha314** [comment]
I disagree with closing it, this seems like a fundamental disconnect between WSL and the display, something that can be reasonably addressed.

**Comment by therealkenc** [comment]
There is no fundamental disconnect between WSL and the display because WSL [has no display](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799) per the [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq).
