### ISSUE TITLE
ssh connection with sshpass in background

### ISSUE THREAD

**Issue by streameast** [Microsoft/WSL#3648]
Hello,
I have a problem with the sshpass command. When I execute a ssh connection in background, at the end of the command, it closes the connection.

```
sshpass -p <password> ssh -Nf <user>@<host> ...
```

When I execute it without sshpass, it does work.

**Comment by therealkenc** [comment]
I was unable to reproduce this here on 18267. I do not have access to `eramos@other-host`, but:

![image](https://user-images.githubusercontent.com/7049700/48031655-c91ee300-e109-11e8-8182-8875470ac5ae.png)

**Comment by k-y** [comment]
Unable to repro on 18262
