### ISSUE TITLE
Opposing end of half-shutdown socketpair incorrectly indicates EOF

### ISSUE THREAD

**Issue by dw** [microsoft/WSL#3649]
Build Number: Microsoft Windows [Version 10.0.17134.376]

What you're doing and what's happening: 

1. Call `socketpair(AF_UNIX, ..)`
2. Set both sides `O_NONBLOCK`
3. Call `shutdown(a, SHUT_WR)`
4. Call `read(b, .., 1)`

`read()` fails with `EAGAIN`, as if the socket hasn't been partially shut down. Linux/OS X  both calls succeed and indicate 0 bytes read, which is commonly interpreted to indicate disconnection.

As shown in the script below, WSL is generating conflicting indicators: the socket is marked as readable by `select()`, but on attempting to read it, `EAGAIN` is generated.

Strace:

````
socketpair(AF_UNIX, SOCK_STREAM, 0, [3, 4]) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
sendto(3, "x", 1, 0, NULL, 0)           = 1
select(5, [4], [], [], {tv_sec=0, tv_usec=0}) = 1 (in [4], left {tv_sec=0, tv_usec=0})
read(4, "x", 1)                         = 1
shutdown(3, SHUT_WR)                    = 0
select(5, [4], [], [], {tv_sec=0, tv_usec=0}) = 1 (in [4], left {tv_sec=0, tv_usec=0})
read(4, 0x7fe8bb36dc0c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
````

Reproduction script (run with CWD = Git checkout of https://github.com/dw/mitogen/ or just replace the set_nonblock call):

````python
import socket
import os
import select

import mitogen.core

s1,s2 = socket.socketpair()
mitogen.core.set_nonblock(s1.fileno())
mitogen.core.set_nonblock(s2.fileno())

def is_ready(f):
    r,_,_ = select.select([f], [], [], 0)
    return len(r) > 0

s1.send('x')
assert is_ready(s2)
assert 'x' == os.read(s2.fileno(), 1)

s1.shutdown(socket.SHUT_WR)
assert is_ready(s2)
assert '' == os.read(s2.fileno(), 1)
````

Bugs:

* https://github.com/dw/mitogen/issues/323
* https://github.com/dw/mitogen/issues/333

**Comment by therealkenc** [comment]
Haven't done a side-by-side, but this sure smells like #3100. You are on 17134 and it wasn't fixed until 17666. Give RS5 aka 1809 aka 17763 a try and see if that helps.

**Comment by dw** [comment]
Looks very similar! Is there a way to get RS5 without enabling insider on my main laptop?

**Comment by therealkenc** [comment]
1809 is the ["October 2018 Update"](https://support.microsoft.com/en-ca/help/4028685/windows-10-get-the-update). You shouldn't need to be on Insiders. I don't really follow the status of the update rollout (and I don't work at MSFT) but you should get it automatically, eventually, if you haven't already.

**Comment by poizan42** [comment]
@therealkenc The rollout of 1809 is currently halted are the file deletion bugs and other critical issues I think.
