### ISSUE TITLE
Cannot kill process group with negative PID

### ISSUE THREAD

**Issue by marcanpilami** [Microsoft/WSL#3650]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [version 10.0.17763.55]

* What you're doing and what's happening:  
```
> /bin/sh -c sleep 3600
> ps -edf | grep sleep
xxx   2604     1  0 12:24 tty1     00:00:00 /bin/sh -c sleep 3600
xxx   2605  2604  0 12:24 tty1     00:00:00 sleep 3600

> kill -TERM -2604
kill: (-2604) - No such process
```

* What's wrong / what should be happening instead: negative PID should be understood as process group and both /bin/sh and sleep (2604 and 2605) should be killed. (from `man kill`: Negative PID values may be used to choose whole process groups)

This seems linked to the fact that WSL does not name it pgroups after the ID of the process group leader as seems mandated by Posix (Wikipedia - I have not read the spec), as :

```
ps -o pid,ppid,pgid,gid,sess,cmd -U xxx
  PID  PPID  PGID   GID  SESS CMD
    4     3     4  1000     3 -bash
  557   556   557  1000   556 -bash
 2604     1  2499  1000     3 /bin/sh -c sleep 3600
 2605  2604  2499  1000     3 sleep 3600
```
PGID is 2499, not 2604 as expected. There is no process with ID 2499.

**Comment by marcanpilami** [comment]
Amusingly enough, /bin/kill displays no error message, but does not kill anything, and return code is 1. So no dice. But clearly it's different indeed.

**Comment by therealkenc** [comment]
> PGID is 2499, not 2604 as expected. There is no process with ID 2499.

Need a repro to get WSL into a state starting from instantiation where PGID ends up being a nonexistent PID. Believe you got into the state; just can't reproduce how you got there. A vanilla `/bin/sh -c "sleep 3600"`  (avec quotes) gets a sane PGID here. I suspect there is an explanation: if process groups didn't work as expected then I'm thinking the whole shell edifice would collapse. But who knows,.. anything possible caveat applies.

![image](https://user-images.githubusercontent.com/7049700/48671822-92ba6e00-eae2-11e8-8129-ad96dd00a75d.png)
