### ISSUE TITLE
WSL Ubunbtu 18.04 error. No compatible interface...

### ISSUE THREAD

**Issue by kherio** [Microsoft/WSL#3651]
I'm on Win10 Pro Insider Preview.
Build 18272.rs_prerelease.181026-1425

Activated the WSL and trying to install Ubuntu 18.04 LTS...
When opening the bash, I get:

_Installing, this may take a few minutes...
Interfaz no compatible
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:_

It doesn't matter whatever I type, I always get : "Non compatible interface"

What can I do to solve it? I've already tried to uninstall/install it :)

**Comment by aleppos** [comment]
I am getting the same issue.

**Comment by inezwibs** [comment]
same issue , updating with 18277 now
