### ISSUE TITLE
nvm and nodejs cant Unable to pass argument in WSL 

### ISSUE THREAD

**Issue by Relsoul** [Microsoft/WSL#3653]
- Your Windows build number: win10.1803 17134.376
- WSL version: Ubuntu 18.04.1 LTS
- NODE version: 8.11.1, use NVM install
- ENV string: PATH=/home/soul/.local/share/umake/bin:/home/soul/.nvm/versions/node/v8.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- node path: /home/soul/.nvm/versions/node/v8.11.1/bin
- What you're doing and what's happening:

i have a node cli a.js
// a.js
```
#!/usr/bin/env node --max-old-space-size=100
(function () { // wrapper in case we're in module_context mode
 console.log(' running ')
})()
```
//package.json
```
{
  "name": "test",
    "bin": {
    "testrun": "./a.js"
  },
}
```
and npm link in ~/.nvm/versions/node/v8.11.1/bin
It looks pretty good to this?
then run
```
$ sudo testrun
$ testrun
```
and... no print,no running.
so. i remove --max-old-space-size=100
```
#!/usr/bin/env node 
(function () { // wrapper in case we're in module_context mode
 console.log(' running ')
})()
```
or

```
#!/home/soul/.nvm/versions/node/v8.11.1/bin/node --max-old-space-size=100
(function () { // wrapper in case we're in module_context mode
 console.log(' running ')
})()
```
it is work.
Can't pass extra parameters when I use /usr/bin/env?

**Comment by therealkenc** [comment]
> Can't pass extra parameters when I use /usr/bin/env?

You have not provided a repro I can work with here (`testrun` is just going to return not found). I did try this on Real Linux:
```
$ cd ~
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
$ source ./bashrc
$ nvm install 8.11.1
$ mkdir foo && cd foo
$ npm i node-bin-example
$ cd node_modules/node-bin-example
$ sed -i "1s/.*/#\!\/usr\/bin\/env node  --max-old-space-size=100/" ./bin/node-bin-example
$ ./bin/node-bin-example
```
This gives no output and spins horribly with the `--max-old-space-size=100` modification to the shebang line. Works fine with the original. Couldn't tell you the faintest idea why. But probably linux-behavior unless someone has alternative thoughts.

**Comment by Relsoul** [comment]
[download_code](http://cdn.emufan.com/img/testrun.zip)
it is my code
1. unzip this
2. npm link
3. open bash 
4. run testrun
5. run testrun_ab
6. run testrun_remove

![](http://cdn.emufan.com/img/testrun.png)
![](http://cdn.emufan.com/img/testrun-2.png)

run testrun, no response. Can only be forced to end.

**Comment by therealkenc** [comment]
> run testrun, no response. 

Same result (no response) on Real Linux.

![image](https://user-images.githubusercontent.com/7049700/47993909-af4bb480-e0a5-11e8-8ca1-141f94627841.png)
