### ISSUE TITLE
Invoking commands from windows prompt with "bash -c" fails (1st command fails)

### ISSUE THREAD

**Issue by PHubaut** [Microsoft/WSL#3658]
* **Windows build number**:  Microsoft Windows [version 10.0.17763.107]
* **What I am doing and what's happening**:  
I want to execute some Linux commands from a CMD Windows prompt using "bash -c".
The command run does not work -or- I should say the first command always fails to work correctly as if I prefix the command with ":;" (actually "do nothing then do my command"), it works
See code below (blank lines removed)
```
Microsoft Windows [version 10.0.17763.107]
(c) 2018 Microsoft Corporation. Tous droits réservés.
C:\Users\Pierre>bash -c ps -ef
  PID TTY          TIME CMD
    4 tty1     00:00:00 ps
C:\Users\Pierre>bash -c :;ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 05:46 ?        00:00:00 /init ro
root         3     1  0 05:46 tty1     00:00:00 /init ro
Pierre       4     3  0 05:46 tty1     00:00:00 /bin/bash -c /bin/bash -c :;ps -ef
Pierre       6     4  0 05:46 tty1     00:00:00 ps -ef
C:\Users\Pierre>
```

* **What's wrong / what should be happening instead**:
"ps -ef" is "_failing_" if I invoke the command from Windows CMD prompt as "bash -c ps -ef" (failing = output is not expected one).
When command is invoked as "bash -c **:;**ps -ef" (i.e. running a dummy command 1st) it works fine.
It looks like the WSL/Linux environment is not immediately ready to run the command and, adding this "do nothing" command will give WSL extra time to be ready.
Note that I tried executing a script and the issue is similar, the first instruction in the script fails. 

* **Strace of the failing command, if applicable**:  n/a
* **For WSL launch issues, please [collect detailed logs]**: n/a

**Comment by jowadmax** [comment]
I may be wrong here, but adding double quotes to the CMD command makes it work.
`ps -ef` -> `bash -c "ps -ef"`

Now if you need quotes in the bash command, you'll have to escape them using `\`.
`ls "My Documents"` -> `bash -c "ls \"My Documents\""`

**Comment by therealkenc** [comment]
Try `wsl.exe ps -ef`

**Comment by tara-raj** [comment]
Hey WSL PM here! As mentioned by @therealkenc, we recommend using wsl.exe instead of "bash -c" now. We're no longer adding functionality to the bash.exe executable. The wsl.exe executable is the one we've been improving and the one we'll continue adding to in the future.

**Comment by Biswa96** [comment]
> We're no longer adding functionality to the bash.exe executable

wsl.exe == bash.exe + `--distribution`, `--exec` and `--user` option.

**Comment by therealkenc** [comment]
> We're no longer adding functionality to the bash.exe executable.

Alright fiat by-design it is. I can't repro with `wsl.exe` on 1809, quotes or no quotes. I am having trouble pinning this on `bash.exe` proper, because `bash.exe` has no idea what `ps` is or should be outputting to `stdout`. 

But either way, to the extent `ps` is missing `init PID 1`, I can't conjure a concrete fail scenario. "I am trying to do [thing] but [thing] is failing because `bash.exe ps -ef` is missing `init`". Nah. This could be issue re-worked into a new submission if there is some kind of race causing actual fails (and there might be) if PID 1 isn't making it into `/proc` on time. But for this submission as framed, we're simultaneously in can't repro territory with `wsl.exe` and academic territory with `bash.exe`.

**Comment by PHubaut** [comment]
Good - thanks you all for your reply and indeed /
1) bash syntax is `bash -c "...command…"` which was my first error, it was explicit in bash documentation
2) Well noted, use wsl.exe rather than bash (and it works fine as well using `wsl -- ps -ef`
Sorry for the trouble.
