### ISSUE TITLE
node_modules / vendor performance

### ISSUE THREAD

**Issue by vielhuber** [Microsoft/WSL#3659]
Hello!

I am very happy with Windows WSL running my lamp stack (apache, mysql, php, node).

The only pain currently is performance on npm install / composer install / npm run serve.

At the moment my only option is to run those commands outside of WSL, which is not the preferrable way because of several issues (different environment).

I have two possible solutions:

- Exclude these folders from mount / folder sync. Is this somehow possible that WSL just excludes those folders from syncing between my Windows machine and the linux mount? Can I unmount a subfolder ("node_modules" and/or "vendor")?

- Make a symlink from /mnt/c/htdocs/project/node_modules to ~/project/node_modules to outsource these modules and prevent a drop in i/o performance.

Unfortunately the second option does not work properly; E.g. when I run npm install, I get a "Cannot find module 'mkdirp'."

I'm happy for any advice.

**Comment by arcanis** [comment]
If you use Yarn, use [the Plug'n'Play feature](https://gist.github.com/arcanis/02b49752c385908479734d8027d7a6c7) (>= 1.12). It will make node_modules disappear, which will improve a lot the install time 🙂

**Comment by vielhuber** [comment]
Wow, awesome concept. Would be awesome, if npm also adopts to that.
