### ISSUE TITLE
Installation of all distros failed (Interface not supported)

### ISSUE THREAD

**Issue by saigkill** [Microsoft/WSL#3661]
I tried to install openSUSE and WLinux through the Windows Store. The Installation itself was successful. After launching it takes some minutes to install.  I can see now the message "Schnittstelle nicht unterstützt" (english: Interface not supported). After that it asks me for a username. But after typing a username and tapping enter the same message comes again. So i can't do the Setup.

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18272.1000]
It's a Insider Preview.

* What you're doing and what's happening:  
Installing, this may take a few minutes...
Schnittstelle nicht unterstützt
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: sascha
Schnittstelle nicht unterstützt
Enter new UNIX username:

* What's wrong / what should be happening instead:
I can't finish the Setup process.

**Comment by benhillis** [comment]
#3645

**Comment by FreddyCamposeco** [comment]
lxrun don't exist !!!
