### ISSUE TITLE
how to install python3-pip in WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by solvingj** [Microsoft/WSL#3663]
This is a simple question, after installing Ubuntu 18.04, I cannot install PIP.  Is it available?  If not, will it be available in the future?

Also, when I type `python`, the cursor goes down 1 line and hangs indefinitely.  `python3` runs python3 as expected, but it seems `python` is a black-hole of a command.

**Comment by Biswa96** [comment]
Fill up all the fields in the issue template which you've deleted.
