### ISSUE TITLE
build nodejs 11 failed

### ISSUE THREAD

**Issue by gengjiawen** [Microsoft/WSL#3666]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
windows 10 1809

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
build nodejs source code after cloning using
```
git clone https://github.com/gengjiawen/node.git 
cd node
 ./configure --debug && make -j4
```
![image](https://user-images.githubusercontent.com/3759816/48558829-32ca9880-e925-11e8-8344-866380e1ba12.png)

* What's wrong / what should be happening instead:
build failded

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by bzoz** [comment]
You are probably missing building tools, see: https://github.com/nodejs/node/blob/master/BUILDING.md#prerequisites

**Comment by gengjiawen** [comment]
nope, I installed gcc.

**Comment by bzoz** [comment]
There is more to build tools than gcc. Try running `sudo apt-get install git python g++ make` and try again

**Comment by therealkenc** [comment]
> sudo apt-get install git python g++

And `sudo apt install build-essential` as a starting point.

Can't repro here (it builds). You'll get better service on general questions regarding building nodejs and the dependencies required in forums dedicated to that scenario. No WSL actionable.

**Comment by gengjiawen** [comment]
I have all that installed and still failed. Btw, I am using ubuntu 18.04.

**Comment by therealkenc** [comment]
Notice you are on `/mnt/d`. That _should_ work if you hit the crease just right, but is asking for trouble on a number of fronts that may be nonobvious. Try `/home/you/build/node`.

**Comment by gengjiawen** [comment]
Still no luck, which wsl you are using ?

**Comment by bzoz** [comment]
@gengjiawen can you try checking out a clean copy of Node sources from WSL? If you have a repo checked out by Windows git, CRLF line endings can cause issues for configuration tools.

**Comment by gengjiawen** [comment]
@bzoz Thanks, I will give it a try. wonder if I can test WSL using Azcure Devops cc @therealkenc .
