### ISSUE TITLE
Boot init before bash start

### ISSUE THREAD

**Issue by bluefoxicy** [Microsoft/WSL#3667]
Hello!

I see several issues like #994 and #834, about what will get `systemd` running or how to start services at Windows boot.  We can generalize systemd to `init`, and generalize service start as starting of services at Linux boot.

The simple way to address the second type, then, is to:

1. Start `/sbin/init` (or other configured init) when starting a WSL application (e.g. `bash`) in an environment which is not booted;
1. Create a terminal under a booted WSL environment when launching an application needing a terminal;
1. Properly handle shutdown (e.g. `shutdown -h`) and exit of pid 1 by terminating everything and shutting down the WSL environment.

To start services on boot, the WSL environment would just be configured to boot at Windows boot.  Each WSL environment could be a service of its own which starts when attempting to launch an application from that environment, or starts at boot.

That won't get `systemd` running, of course; nor will it make `dbus` work, or get `wayland-rdp` working (so you can RDP into the local Ubuntu GDM and log into Gnome Shell), or whatnot.  It's simply the logical direction.

**Comment by therealkenc** [comment]
Dupe #834.

**Comment by bluefoxicy** [comment]
834 seems to be asking about running services, rather than bringing up the full init system to be bootable and rebootable.
