### ISSUE TITLE
`Error: /proc must be mounted` when executing `vmstat`

### ISSUE THREAD

**Issue by Mirr0ch1** [Microsoft/WSL#3673]
**Please fill out the below information:**
- Your Windows build number:  
17134

- What you're doing and what's happening:  
    - trying to run `vmstat`, results are like:

>```
>mirro@LAPTOP-MiP:/$ vmstat
>procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
> r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
>Error: /proc must be mounted
>  To mount /proc at boot you need an /etc/fstab line like:
>      proc   /proc   proc    defaults
>  In the meantime, run "mount proc /proc -t proc"
>```

- yet `/proc` has already listed as `mounted`

>```
>mirro@LAPTOP-MiP:/$ mount
>rootfs on / type lxfs (rw,noatime)
>sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
>proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
>none on /dev type tmpfs (rw,noatime,mode=755)
>devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
>none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
>none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
>none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
>none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
>binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
>C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
>```

**I'm aware of this issue has been marked as solved under #105. Apparently there's still some bug need to be fixed. Please look into this problem, huge thanks.**

**Comment by therealkenc** [comment]
The error spewed by `vmstat(1)` is misleading; it is just confused by the lack of `/proc/vmstat` and assumes `/proc` must not be mounted at all. Dupe #1071. Russel's [request](https://github.com/Microsoft/WSL/issues/1071#issuecomment-246398465) for a blocking scenario posted _over there_ (sic) always helps.

**Comment by jansaasman** [comment]
So I"m on the very latest versions and I still see the problem with vmstat -SM 1

**Comment by MikeWilcoxMicrosoft** [comment]
We are seeing the same problem. 

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic 

$ mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
$
$ vmstat 2
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

**Comment by dasamitkumar** [comment]
Same problem here as well.

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

$mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
proc on /proc type proc (rw,relatime)
proc on /proc type proc (rw,relatime)

$vmstat 2
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
$

**Comment by amjadparacha** [comment]
Still facing this problem

- Windows build number:
   17134

- What I'm doing and what's happening:
   trying to run vmstat, results are like:

`root@***:/mnt/c/Windows/System32# vmstat -s
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"`

- yet /proc has already listed as mounted

`root@****:~# mount
rootfs on / type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
D: on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000,case=off)`
