### ISSUE TITLE
git difftool doesn't copy/link the files to the /tmp locations

### ISSUE THREAD

**Issue by zlatko-michailov** [Microsoft/WSL#3674]
This must be a bug in WSL, because a machine with the same Linux (openSUSE) distro works fine.

_* Your Windows build number:  (Type `ver` at a Windows Command Prompt)_
Microsoft Windows [Version 10.0.17763.134]

_* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)_

I noticed that when I try to use VSCode a git diff tool, it shows empty panes. So I started digging. I wrote the following shell script, and set it up as a git diff tool:

``` sh
#!/bin/sh
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo $1
echo $2
echo -------------------------------------------------------
ls -al $1
cat $1
echo -------------------------------------------------------
ls -al $2
cat $2
```

This is the output from `git difftool -y HEAD~1..HEAD`, i.e. when each changed file is sent individually:
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
/tmp/utICHb_log.h
/tmp/urTOKf_log.h
-------------------------------------------------------
ls: cannot access '/tmp/utICHb_log.h'$'\r': No such file or directory
cat: '/tmp/utICHb_log.h'$'\r': No such file or directory
-------------------------------------------------------
ls: cannot access '/tmp/urTOKf_log.h'$'\r': No such file or directory
cat: '/tmp/urTOKf_log.h'$'\r': No such file or directory
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
/tmp/96sISa_main.cpp
/tmp/LMwWLc_main.cpp
-------------------------------------------------------
ls: cannot access '/tmp/96sISa_main.cpp'$'\r': No such file or directory
cat: '/tmp/96sISa_main.cpp'$'\r': No such file or directory
-------------------------------------------------------
ls: cannot access '/tmp/LMwWLc_main.cpp'$'\r': No such file or directory
cat: '/tmp/LMwWLc_main.cpp'$'\r': No such file or directory
```

And this is the output from `git difftool -y --dir-diff HEAD~1..HEAD`, i.e. when all changed files are put in a left/right subfolder:
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
/tmp/git-difftool.ubZX1V/left/
/tmp/git-difftool.ubZX1V/right/
-------------------------------------------------------
ls: cannot access '/tmp/git-difftool.ubZX1V/left/'$'\r': No such file or directory
cat: '/tmp/git-difftool.ubZX1V/left/'$'\r': No such file or directory
-------------------------------------------------------
ls: cannot access '/tmp/git-difftool.ubZX1V/right/'$'\r': No such file or directory
cat: '/tmp/git-difftool.ubZX1V/right/'$'\r': No such file or directory
```

_* What's wrong / what should be happening instead:_
In both cases, git generates /tmp paths, but there are no files behind them. Again, on a normal Linux machine, the files are there (in both cases.)

_* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)._

**Comment by therealkenc** [comment]
> ls: cannot access '/tmp/utICHb_log.h'$'\r': No such file or directory

Almost certainly variation #2365. You've got carriage returns in your shell script; which won't be reflected in the cut-and-paste into your OP. They're being appended to `$1` and `$2`.

**Comment by zlatko-michailov** [comment]
I also manually examined the /tmp folder, and there is nothing relevant there. So before the configured difftool is invoked, the system has failed to create the temp files.

**Comment by zlatko-michailov** [comment]
I see (from the strace) that the files get deleted, which explains why I don't see anything relevan under /tmp.

But where are carriage returns coming from? Here's the line from my git config file:
```
[difftool "t1"]
	cmd = /bin/sh t1.sh \"$LOCAL\" \"$REMOTE\" 
```

I don't think the test script has anything to do with it, because VSCode shows blank panes too.

**Comment by therealkenc** [comment]
> But where are carriage returns coming from? 

Your editor.

If you like, post CLI repro steps along the lines of the following that fails on WSL but not your Real Linux machine.

```
$ sudo apt install git
$ git clone sometoyrepo
$ cd sometoyrepo
$ # stuff, probably a wget of your script from a gist... 
$ # ....and steps to set up git's diff.tool configuration variable in your git config
$ # (or pass --tool= to git difftool below)
$ # more stuff
$ # etc
$ git difftool -y --dir-diff ....
```

Fair warning, my best guess here is you'll wild goose chase. But anything possible caveat always applies. I'm happy to take a look.

**Comment by zlatko-michailov** [comment]
Thank you, @therealkenc! After `dos2unix t1.sh`, the test diftool started working.  I will dig into VSCode a bit more. Anyway, I don't think this a WSL issue anymore.
