### ISSUE TITLE
Ubuntu slow to start and missing DNS configs

### ISSUE THREAD

**Issue by ThreePinkApples** [microsoft/WSL#3678]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.407]

* What you're doing and what's happening:  After recent run of Windows update (followed by reboot), starting Ubuntu (18.04) takes a long time, and when started, all DNS queries fail. After some digging I found that ```/run/resolvconf/resolv.conf``` is missing, adding my own custom ```/etc/resolv.conf``` with nameservers solves the issue until next reboot. (The symlink ```/etc/resolv.conf``` pointing at ```/run/resolvconf/resolv.conf``` is recreated on every boot)
I tried to reproduce the issue by forcing Ubuntu to reboot with ```sudo touch /var/run/reboot-required```, but then Ubuntu failed to start at all. Had to reboot whole PC. Logs are included later.

* What's wrong / what should be happening instead: DNS settings from Windows should be present in Ubuntu

Logs from first reproduction, where I used ```sudo touch /var/run/reboot-required``` and starting failed.
[lxcore detailed logs failed.zip](https://github.com/Microsoft/WSL/files/2604051/lxcore.detailed.logs.failed.zip)

Logs from second reproduction, where I rebooted the PC first
[lxcore detailed logs slow but successful.zip](https://github.com/Microsoft/WSL/files/2604048/lxcore.detailed.logs.slow.but.successful.zip)

**Comment by goduck777** [comment]
Actually the file /run/resolvconf/resolv.conf is not needed anymore.
