### ISSUE TITLE
Language pt_BR

### ISSUE THREAD

**Issue by LucasSchiavo** [Microsoft/WSL#3681]
Hi everyone,

I'm using WSL with Ubuntu, how can I change the Ubuntu language ? I tried to create some folders, but the folders are in Portuguese, and the terminal can't read that language. Is it right ?

So, I repeat the question, how can I change the language of Ubuntu ?

I need change to pt_BR.

Thnak you.

**Comment by therealkenc** [comment]
> how can I change the language of Ubuntu ?

No takers on the question from the community, and there is no WSL actionable. There is a starting point [here](https://help.ubuntu.com/community/Locale). You may try a Ubuntu Forum or ServerFault.

**Comment by therealkenc** [comment]
freebie because I was putting #3018 to bed:
```
$ sudo locale-gen pt_BR.UTF-8
$ sudo update-locale LANG=pt_BR.UTF-8
$ bash  # more practically, close and re-open the terminal
$ locale | grep LANG=
LANG=pt_BR.UTF-8
```
