### ISSUE TITLE
 WARNING: UNPROTECTED PRIVATE KEY FILE!

### ISSUE THREAD

**Issue by DariusLLL** [Microsoft/WSL#3686]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.407]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
dariusl@DARIUS-NAMAI:~/.ssh$ ssh -i dariusl_id_rsa-cert.pub dariusl@g-lb04.arwico.info
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for 'dariusl_id_rsa-cert.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "dariusl_id_rsa-cert.pub": bad permissions
dariusl@g-lb04.arwico.info's password:

* What's wrong / what should be happening instead:
dariusl_id_rsa-cert.pub is a certificate file which is signed on the server
I other words: in WSL ubuntu 18-04 ssh -i expects only private key file.
The same case is working perfectly from Hyper-V Ubuntu VM but not from WSL

If I chmod to 600 - I get wrong key file format. Of course, because dariusl_id_rsa-cert.pub is certificate file.
Thanks
DL

**Comment by SRGOM** [comment]
Seems like the usual file system related "inconsistency" issue...

**Comment by therealkenc** [comment]
There is no repro here and no WSL actionable, and it looks like not enough for a guess from the community except what the last sentence in the OP already states. There are no known issues related to unspecified filesystem scare quote inconsistencies (of the usual or unusual variety) that would explain the behavior described.
