### ISSUE TITLE
Buildroot not working

### ISSUE THREAD

**Issue by cooked** [Microsoft/WSL#3688]
Microsoft Windows [Version 10.0.17134.407]

Trying to run [Buildroot ](https://buildroot.org) in WSL:

git clone git://git.busybox.net/buildroot
cd buildroot
make pc_x86_64_efi_defconfig
make

The build fails with the error message below

![image](https://user-images.githubusercontent.com/1381353/49163132-a78dd180-f32c-11e8-8189-84b22e32bd21.png)

https://gist.github.com/cooked/4769c9149e7499ff246d89f30bb5150c

**Comment by therealkenc** [comment]
Carriage returns in the script. #2365 #3674 #3407 et al.

**Comment by Biswa96** [comment]
Workaround:
1. Clone the repository in WSL user home folder (or paths where user has read/write permissions). e.g. `/home/user_name` aka. `~`, `/home/user_name/myfolder` etc.
2. Allow git in firewall. The build procedure depends on [pkgconf](https://github.com/pkgconf/pkgconf).

**Comment by Biswa96** [comment]
Simple workaround:
1. Clone the repository in WSL user home folder (or paths where user has read/write permissions). e.g. `/home/user_name` aka. `~`, `/home/user_name/myfolder` etc. Don't clone in any windows drive e.g. `/mnt/c`, `/mnt/d` etc.
2. Allow `/usr/bin/git` and `/usr/bin/wget` in windows firewall. The build procedure depends on [pkgconf](https://github.com/pkgconf/pkgconf).

**Comment by therealkenc** [comment]
You can build it in `/mnt/c`. DrvFS doesn't (and can't) treat file contents any different than LxFS. You will probably want `-o metadata,case=dir` given the nature of the build. And you'll want your symlink ducks in line by enabling Developer Mode in Windows. But neither of those things are related to the fail in the screencap, which is Windows-convention `CRLF` in some script being interpreted by `bash`. Something Win32 related (an editor, Windows git maybe) has mucked up the contents. I'm building it in `/mnt/c` using the repro given as I am typing this. [Not that I have the patience to watch it finish.]
