### ISSUE TITLE
Cannot install mysql-client

### ISSUE THREAD

**Issue by Frank-Shaw-FS** [Microsoft/WSL#3690]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
1803(OS Build 17134.407), the wsl is using 16.04
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
use apt-get install mysql-client

* What's wrong / what should be happening instead:
![image](https://user-images.githubusercontent.com/5810166/49194871-c0939280-f3bf-11e8-9e85-950225872f43.png)

It seems the apt always like to use the security.ubuntu.com to fetch the package. I have two more 16.04 vms in my pc, they will try to get the package from us.archive.ubunt.com that is quick and flawless

**Comment by therealkenc** [comment]
`sudo apt update && sudo apt upgrade` possibly.

**Comment by therealkenc** [comment]
> I guess it is caused by using qemu to support 32-bit application.

I couldn't tell you without guessing. The reproduction steps you submitted do not involve `qemu`. But... yes.
