### ISSUE TITLE
Ubuntu installation lost after Windows updated, home folder and all files lost.

### ISSUE THREAD

**Issue by nurmuhammadsirat** [Microsoft/WSL#3692]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.407]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Windows Update ran and updated to the version above. Previous version unknown.

After the update completes and reboots, Ubuntu was no longer installed. Running `bash` at the command prompt tells me to go to the Windows store and install Ubuntu. Link provided wasn't working. Manually went to the Windows Store and searched for Ubuntu. I have it installed quite some time ago, but now, all the Ubuntu apps show `Free` instead of `Installed`. Installed `Ubuntu 18.04 LTS` app from the store. Went through the motions after installing to create a new UNIX user and password.

All files in the home folder (`/home/<user>`) were lost. The biggest pain is that my ssh config and private keys were also gone.

* What's wrong / what should be happening instead:

Ubuntu installation was preserved and no files were lost.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

Not applicable.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Not sure how to get logs for a lost installation.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by nurmuhammadsirat** [comment]
$ wslconfig.exe /list

Windows Subsystem for Linux Distributions:
Legacy (Default)
Ubuntu-18.04

**Comment by nurmuhammadsirat** [comment]
@benhillis All my files auto-magically came back!

**Comment by benhillis** [comment]
Thanks, you're liking hitting #3215.
