### ISSUE TITLE
WSL Distro deleted after reopeing bash.exe

### ISSUE THREAD

**Issue by alexmandt** [Microsoft/WSL#3694]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.407]

* What you're doing and what's happening:  bash.exe

* What's wrong / what should be happening instead:
When I opened bash.exe to use WSL to ssh into a remote machine, I got greeted with the message "No distro is installed. Please go to this url to get a distro."

I expected that a bash instance of my Ubuntu 18.04 Distro that I installed via the Microsoft Store would open.

However, after a few minutes, when I tried to reopen bash.exe, my distro was back.

**Comment by 0xbadfca11** [comment]
#2576
