### ISSUE TITLE
Home directory is expanded incorrectly in different programs

### ISSUE THREAD

**Issue by FallenGameR** [Microsoft/WSL#3700]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.134]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Trying to edit a config file in the home directory. But it turns out that VS code opens a different file.
Here is how I invoke the command in the console:
alexko@alexko-ds /m/e/C/a/p/d/A/N/SymmetricKeys> cat ~/.tmux.conf
alexko@alexko-ds /m/e/C/a/p/d/A/N/SymmetricKeys> code ~/.tmux.conf

And here are the paths that are actually being touched:
![image](https://user-images.githubusercontent.com/711295/49547427-7e72c100-f897-11e8-813b-b63bbf045168.png)

* What's wrong / what should be happening instead:

Both paths should resolve in the same place, not edit two different unrelated files.
Right now I don't know how to use VS code to edit config files...

**Comment by therealkenc** [comment]
I assume you're talking about Windows `code.exe` via [interop](https://docs.microsoft.com/en-us/windows/wsl/interop). Windows (win32) programs cannot access stuff in LxFS. #1524. If you want to edit with `code.exe` you need to be in `/mnt/c/Users/you/somewhere`.
