### ISSUE TITLE
Post fall update I can no longer launch jupyter notebooks from windows terminal with bash

### ISSUE THREAD

**Issue by dsaffo** [Microsoft/WSL#3701]
When I launch jupyter notebooks from the windows terminal after the bash command I get this error

Server error: Traceback (most recent call last): File "/home/default/miniconda3/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute result = yield result File "/home/default/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run value = future.result() File "/home/default/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) File "/home/default/miniconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/home/default/miniconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) File "/home/default/miniconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model if self.should_list(name) and not is_file_hidden(os_path, stat_res=st): File "/home/default/miniconda3/lib/python3.7/site-packages/notebook/utils.py", line 145, in is_file_hidden_posix stat_res = os.stat(abs_path) PermissionError: [Errno 13] Permission denied: '/mnt/c/Users/David Saffo/Application Data'

launching from the Ubuntu terminal works fine but I need to be able to work from my windows folders. This was not an issue I had until recently. 

Any way to fix this? It looks like windows is denying WSL permission from its folders.

**Comment by therealkenc** [comment]
Closing on [TEMPLATE.md](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md). Ref #3608 (two of these now). Error is on `'/mnt/c/Users/David Saffo/Application Data'` which might mean `C:\` wasn't mounted with metadata (which is the default). Or might not. Folks having problems with jupyter are encouraged to open a new issue with a CLI repro.
