### ISSUE TITLE
install arguments for initial setup

### ISSUE THREAD

**Issue by noahjcorwin** [Microsoft/WSL#3702]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  17763.107

* What you're doing and what's happening:  server setup for WSL

* What's wrong / what should be happening instead: no agruments for automated install, requires user interaction for setting "new unix username"

* Strace of the failing command, if applicable:  NA

* For WSL launch issues, please [collect detailed logs]: NA

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by 0xbadfca11** [comment]
<distribution>.exe install --root

**Comment by noahjcorwin** [comment]
```
C:\WSL\Ubuntu1604>ubuntu.exe install --root
Installing, this may take a few minutes...
Installation Failed!
Error: 0x8007007e
Press any key to continue...
```

**Comment by benhillis** [comment]
Looks like you don't have the optional component installed.

**Comment by noahjcorwin** [comment]
it looks like the 'install --root' args aren't working for the current 1604 package, I get the following error '"invalid command line arg 'install'".  I did get it to work with the 1804 package.

**Comment by noahjcorwin** [comment]
This does the trick.
```
ubuntu1804.exe install --root
ubuntu1804.exe run adduser user --gecos "First,Last,RoomNumber,WorkPhone,HomePhone" --disabled-password' 
ubuntu1804.exe run echo 'user:P@ssw0rd' | sudo chpasswd
ubuntu1804.exe run usermod -aG sudo user
ubuntu1804.exe config --default-user user
```
