### ISSUE TITLE
Add support for custom serial port baud rate

### ISSUE THREAD

**Issue by rustyx** [Microsoft/WSL#3705]
For ESP8266 programming it is important to be able to set non-standard baud rates, specifically 74880.

The newly [added `ttyS*` devices](https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/) do not seem to support **`TCGETS2`/`TCSETS2`** IOCTLs, which are needed to set a custom baud rate.

Similarly **`TIOCGSERIAL`/`TIOCSSERIAL`** ioctl's also don't work.

**Steps to reproduce:**

1. Get a USB-to-serial adapter like ch340, ft232, cp2102 or pl2303.
2. Compile the following C application (`gcc -o baud baud.c`)

```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <asm/termios.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>

char *device = "/dev/ttyUSB0";
int speed = 74880;

int main ( int argc, char **argv )
{
    struct termios2 tio = {0};
    int fd;

    if ( argc > 1 )
	device = argv[1];

    if ( argc > 2 )
	speed = atoi(argv[2]);

    printf("Setting baud rate of %s to %u\n", device, speed);

    fd = open ( device, O_RDWR );
    if ( fd < 0 ) {
        perror("open");
	return 1;
    }

    if (ioctl(fd, TCGETS2, &tio))
        perror("ioctl(TCGETS2)");

    tio.c_cflag &= ~CBAUD;
    tio.c_cflag |= BOTHER;
    tio.c_ispeed = speed;
    tio.c_ospeed = speed;
    if (ioctl(fd, TCSETS2, &tio))
        perror("ioctl(TCSETS2)");

    return 0;
}
```

3. Run as: `./baud /dev/ttyS5` (adjust to match the COM port)

**Expected output:** success.

**Actual output:**

```
$ ./baud /dev/ttyS5
Setting baud rate of /dev/ttyS5 to 74880
ioctl(TCGETS2): Inappropriate ioctl for device
ioctl(TCSETS2): Inappropriate ioctl for device
```

**Comment by therealkenc** [comment]
#2595
