### ISSUE TITLE
ESP32 serial device incorrectly forwarded

### ISSUE THREAD

**Issue by dnicoara** [Microsoft/WSL#3706]
* Your Windows build number: 10.0.17134.407

* What's wrong / what should be happening instead:

This issue is specific for a ESP32-DEVKITC-32D device.

After installing the driver it shows up as a serial device and I can properly connect via putty. When attempting to connect to the device via WSL it didn't seem that the serial device was forwarded correctly.

Looking at the registry keys in Computer\HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM I see it as key: "\Device\Silabser0" value: "COM3". After a bit of digging around it turns out that the key is incorrect. Looking at the device's properties, its "Physical Device Object name" is "\Device\USBPDO-8". Sure enough, adding a new registry entry with the correct key value fixed the issue.

I'm not sure where the previous name comes from (perhaps stale value from prior to driver installation)? Though unplugging and re-plugging the device didn't solve the issue, nor did rebooting my PC.

**Comment by Beeline-MQTT** [comment]
You legend...

This looks like a driver issue that needs fixing.

I have been tearing my hair out the last few days because of this.

I still can't get my serial port working in WSL. But this is clearly an issue.

**Comment by Beeline-MQTT** [comment]
I fixed my issue by removing the "Windows 10 Universal" driver and be using the "Windows 7/8/8.1" driver.
My registry still shows \Device\Silabser0 = COM4. And its working OK.
