### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by biligeny** [Microsoft/WSL#3707]
When installed tomcat and run command "systemctl daemon-reload", I got "System has not been booted with systemd as init system (PID 1). Can't operate", is this kind of beyond WSL supported function, or have some sort of work around etc?

**Comment by therealkenc** [comment]
#994

**Comment by Nitin123-4** [comment]
I am also facing the same problem...
sudo systemctl start docker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by ifaniqbal** [comment]
I got this error after doing these:
- run fresh debian distro
- install docker

**Comment by felipementel** [comment]
I had this problem running WSL 2

the solution was the command

     $ sudo dockerd

Open other terminal and try it

     $ docker ps -a

if after that you still have a problem with permission, run the command:

     $ sudo usermod -aG docker your-user

**Comment by ifaniqbal** [comment]
My bad. I was not following the official guide to integrate WSL with Docker. I run into that problem because I install docker from inside WSL with `sudo apt install docker`.

So, follow the guide to integrate WSL with Docker Desktop.

**Comment by felipementel** [comment]
https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

> My bad. I was not following the official guide to integrate WSL with Docker. I run into that problem because I install docker from inside WSL with `sudo apt install docker`.
> 
> So, follow the guide to integrate WSL with Docker Desktop.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by jose-juarez-renteria** [comment]
@ifaniqbal what guide did you followed?

**Comment by ifaniqbal** [comment]
Hi, you can follow these guidelines:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
https://docs.docker.com/docker-for-windows/wsl/
