### ISSUE TITLE
Win32 interoperability with Alpine #NotWorking

### ISSUE THREAD

**Issue by am11** [Microsoft/WSL#3710]
```cmd
C:\>ver

Microsoft Windows [Version 10.0.18290.1000]
```

In [Alpine WSL](https://www.microsoft.com/en-us/p/alpine-wsl/9p804crf0395), testing interoperability with win32 applications results in Almquist shell throwing "not found" error, e.g.:

```ash
~# echo test | clip.exe
-ash: clip.exe: not found
```

Following the [docs](https://docs.microsoft.com/en-us/windows/wsl/interop#disable-interop), I can see that WSLInterop is enabled:

```ash
~# cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags:
offset 0
magic 4d5a
```

Are there any prerequisites to be installed in "bare minimum" operating systems, such as Alpine, to make the win32 applications interoperability work under WSL?

```ash
apk add ??
```

or something that is required to be implemented in [WSL-DistroLauncher-Alpine](https://github.com/agowa338/WSL-DistroLauncher-Alpine )?

**Comment by benhillis** [comment]
Seems like Alpine is overriding the $PATH variable. Look in /etc/profile, likely it's being set there.

**Comment by am11** [comment]
Brilliant, thanks for the tip!

Making the following change in `/etc/profile` fixed the issue:

```diff
export CHARSET=UTF-8
- export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
