### ISSUE TITLE
console broken after update 18298.1000

### ISSUE THREAD

**Issue by nicferrier** [Microsoft/WSL#3711]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18298.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* start WSL,
* vi ~/.bashrc
* quite vi
* console no longer prints anything

or if you have it installed:

* emacs -nw
* screen looks wierd
* quit emacs
* console has got a red background

it appears that most curses apps are the same, htop, etc...

curiously top resets it.

* What's wrong / what should be happening instead:

The console should continue to work after vi and other curses apps.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Biswa96** [comment]
There is no error shown with your given steps. Did you change any color in console settings?

**Comment by therealkenc** [comment]
> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Comment by rhacer63** [comment]
I was going to open a new report, but this sounds very similar to what I'm seeing on 18298. While Vim and psql all work, "less" no longer works. I get a blank screen with a cursor blinking in the middle of it.

I thought for sure it was curses related but with Vim and psqql and pico all working, I'm not entirely convinced of that.

**Comment by mjoppich** [comment]
Should it have been fixed in 18305? Then it would be another bug, because less does not work in 18305, showing invisible characters...
