### ISSUE TITLE
Simple Java operations hanging

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/WSL#3712]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17134.407

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I'm trying to use javac to compile an incredible simple, pretty much "Hello World", java program. In WSL, running `javac path/to/file.java` will hang, never returning. In PowerShell, it compiles perfectly fine.

Note that this is random. In 3 tests I did of trying to javac the same file, it worked 1 out of 3 times.

I also tested `java path.to.file` and it randomly hung as well.

* What's wrong / what should be happening instead:
It hangs and never returns. It should compile the Java program.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

First time using strace - it attached to the process, but nothing else was shown.

`javac --showversion` returns  1.8.0_191.

**Comment by therealkenc** [comment]
> Note that this is random. In 3 tests I did of trying to javac the same file, it worked 1 out of 3 times.

Works here. Compiles all day. 

> (Copy&paste specific commands and their output, or include screen shots)

No repro steps provided, naturally.

```
$ cat /proc/version
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #345-Microsoft Wed Sep 19 17:47:00 PST 2018
$ lsb_release -d
Description:    Ubuntu 18.04.1 LTS
$ sudo apt update && sudo apt upgrade -y
$ sudo apt install openjdk-8-jdk-headless
$ cd ~ && mkdir javahello && cd javahello
$ wget -O HelloWorld.java https://goo.gl/54MVVG
$ javac -version
javac 1.8.0_191
$ javac HelloWorld.java
$ java HelloWorld
Hello, World
```

**Comment by cfjedimaster** [comment]
"No repro steps provided, naturally." I'm assuming the naturally bit was said with a nice smile. ;)

I did provide repro steps - specifically the `javac` and `java` commands. This is *not* specific to one Java file. For me I'm seeing it with multiple, short, HelloWorld style examples. If there is more info I can provide, please let me know.

**Comment by bitcrazed** [comment]
Hey Reymond: 

We ask for detailed repro steps becuase we have to diagnose so many highly variant scenarios, tools, and environments. Full repro steps REALLY help us reproduce YOUR specific issues using specific versions/builds of specific tools.

I also created a simple [Java Hello World repo](https://github.com/bitcrazed/hellojava) and tested locally on my machine running Windows 10 18303, in an Ubuntu 18.04 WSL instance, following these steps:

```
$ sudo apt update && sudo apt upgrade -y
$ sudo apt install openjdk-8-jdk-headless
$ cd ~/dev/
$ git clone git@github.com:bitcrazed/hellojava.git
$ cd hellojava/
$ javac -version
javac 1.8.0_191
$ javac hello.java
$ java hello
Hello World!
$ seq 10 | xargs -Iz java hello
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
```
I've not managed to hang Java running this HelloWorld sample.

You mention that you tried running `strace`. When I do I see this:

```
$ strace java hello
execve("/usr/bin/java", ["java", "hello"], 0x7ffffcaeabd8 /* 18 vars */) = 0
brk(NULL)                               = 0x7fffc4e9b000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
readlink("/proc/self/exe", "/usr/lib/jvm/java-8-openjdk-amd6"..., 4096) = 46
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/../lib/amd64/jli/tls/x86_64/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

# … LOTS OF OUTPUT ...

futex(0x7f5b9d9b09d0, FUTEX_WAIT, 7598, NULLHello World!
) = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
If you don't see anything at all when running strace, its likely there's something VERY wrong with your distro/setup.

**Comment by cfjedimaster** [comment]
One thing I see is that I'm on Ubuntu 16.04.5 LTS. Let me try upgrading and see if the issue goes away.

**Comment by cfjedimaster** [comment]
Hot diggity - I have to run and this isn't a great test, but updating seems to have corrected it. I did about 15 quick tests and `javac` ran perfectly each time.
