### ISSUE TITLE
Error running Bash or Ubuntu installer

### ISSUE THREAD

**Issue by kuzi-moto** [Microsoft/WSL#3714]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.194]
* What you're doing and what's happening: 
1. Manually download Ubuntu from this page: https://docs.microsoft.com/en-us/windows/wsl/install-manual.
2. Rename the .aspx file to ubuntu.zip
3. Extract zip
4. Run ubuntu1804.exe from elevated command promt
5. Returns error: `The specified network name is no longer available.`

* What's wrong / what should be happening instead:
It should begin installing Ubuntu 18.04.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
Not relevant?

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
Not relevant?

**Comment by kuzi-moto** [comment]
> 
> 
> Could you please follow the "collect detailed logs" instructions above and share those etl files?

I get the following error:
`logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749843B3F5C9} -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets
logman.exe : A value that is not valid (.\lxcore_kernel.etl) was specified for the outputFormat parameter. Valid
values are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter`

**Comment by benhillis** [comment]
@kuzi-moto - Try running the command in cmd.exe, not powershell.

**Comment by kuzi-moto** [comment]
> 
> 
> @kuzi-moto - Try running the command in cmd.exe, not powershell.

Ah, I believe I did see that, I just ignored it ;) here are the files: [logs.zip](https://github.com/Microsoft/WSL/files/2681981/logs.zip)

**Comment by benhillis** [comment]
Thanks for the logs! I took a look at this and somehow it looks like your filesystem's /bin folder is missing.  I would suggest unregistering your distribution using wslconfig.exe, and attempting to run the installer again.

**Comment by kuzi-moto** [comment]
@benhillis No problem! And thanks for the suggestion on using wslconfig. Looks like unregistering did the trick! Don't know how I missed that in my searching, but at least things are working now.

Thanks again!

**Comment by EricSP2** [comment]
> Thanks for the logs! I took a look at this and somehow it looks like your filesystem's /bin folder is missing. I would suggest unregistering your distribution using wslconfig.exe, and attempting to run the installer again.

AWESOME!!!!!

**Comment by Akito13** [comment]
> I would suggest unregistering your distribution using wslconfig.exe, and attempting to run the installer again.

## For people running into this on Google
Unregister your distribution like this:
1. Open Powershell or CMD.
2. Run.
```
wslconfig.exe /u Debian
```
You can replace _Debian_ with the distribution you were using.

**Comment by aarumug** [comment]
wslconfig /l /all -- will list all the distributions that's available to WSL (which also means its installed)
wslconfig /u <distro-name> -- unregisters the distro
And then running the installation fixed the problem for me.

**Comment by MajorBarnulf** [comment]
> > I would suggest unregistering your distribution using wslconfig.exe, and attempting to run the installer again.
> 
> ## For people running into this on Google
> Unregister your distribution like this:
> 
> 1. Open Powershell or CMD.
> 2. Run.
> 
> ```
> wslconfig.exe /u Debian
> ```
> 
> You can replace _Debian_ with the distribution you were using.

I am using an arch based distro in wsl ( https://github.com/yuk7/ArchWSL ) 
`wslconfig /u Arch` worked just fine

**Comment by manuelinfosec** [comment]
None of these worked for me. Unregistered, did a lot. I'm exhausted.

**Comment by firefumavn** [comment]
> `wslconfig /l /all` -- will list all the distributions that's available to WSL (which also means its installed)
> `wslconfig /u <distro-name>` -- unregisters the distro
> For e.g. `wslconfig /u Ubuntu-18.04` (in my case)
> 
> And then running the installation fixed the problem for me.

Great
Thank you
