### ISSUE TITLE
Mount permissions prevent interop

### ISSUE THREAD

**Issue by mkarpoff** [Microsoft/WSL#3715]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

17763

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I'm trying to run some windows commands in ubuntu (clip.exe specifically but all win commands do the same thing). I ran into permission errors. Interop is enable but the problem is that I mount C:> with the `options=metadata,umask=22,fmask=111`.

* What's wrong / what should be happening instead:

The problem is that mount options set the default file permissions to be non executable for windows programs but if you try to manually give the file bash executable permissions it doesn't allow that either.
Ex.
`sudo chmod +x /mnt/c/Windows/System32/clip.exe`
throws
`chmod: changing permissions of '/mnt/c/Windows/System32/clip.exe': Permission denied`

Here is how my `/etc/wsl.conf` is setup
```
[automount]
#This Mounts the drives (pretty sure this is default)
enable=true
#metadata: save file metadata (otherwise it makes it 777)
#masks (Sets them to Ubuntu defaults) make them whatever you want
options=metadata,uid=1000,gid=1000,umask=22,fmask=111
[interop]
# enable launch of Windows binaries; default is true
enabled=true
# append Windows path to $PATH variable; default is true
appendWindowsPath=true
```

**Comment by therealkenc** [comment]
You (your Windows user) don't have permission to modify files, including the metadata, in `C:\Windows\System32`. By extension neither does your WSL user, which is not granted special powers to do so. You'll note the perms are `r-x` (lacking `w`). That much is by design.

> Copy&paste specific commands and their output, or include screen shots)

They would have looked like:

```
$ cat /proc/version
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #471-Microsoft Fri Dec 07 20:04:00 PST 2018
$ lsb_release -d
Description:    Ubuntu 18.04.1 LTS
$ cd ~ && mkdir -p ~/tmp/mnt && cd tmp
$ sudo mount -o metadata,uid=1000,gid=1000,umask=22,fmask=111 -t drvfs C: ./mnt 
$ mount | grep tmp/mnt
C: on /home/ken/tmp/mnt type drvfs (rw,relatime,uid=1000,gid=1000,case=off)
$ ls -l ./mnt/Windows/System32/clip.exe
-r-xr-xr-x 2 ken ken 30720 Dec  5 23:38 
$ ./mnt/Windows/System32/clip.exe /?
-bash: ./mnt/Windows/System32/clip.exe: Permission denied
```

**Comment by therealkenc** [comment]
Sorry that was my bad. I did more than one run and pasted from the wrong place (I need to stop doing these in a rush). Yes those are the correct perms with `umask=111`. Fixed up the above post with a screencap instead. Yes, you will not get `x`. Because you've masked it. You don't have `w` because you don't have permissions. That leaves you with `r`.

**Comment by mkarpoff** [comment]
Is there some way to mount parts of the drive with separate permissions?

**Comment by therealkenc** [comment]
Yes. Mount `C:` on two mountpoints with different permissions and use a [bind mount](https://unix.stackexchange.com/questions/198590/what-is-a-bind-mount) for the part you want. You can set these up in your [`fstab(5)`](http://man7.org/linux/man-pages/man5/fstab.5.html) (see also `mountFsTab=true` per this [blog post](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/)). Not that I think you need to or should do this, but you asked. Bonne chance.
