### ISSUE TITLE
Clipboard with single character returns garbage via win32 interoperability

### ISSUE THREAD

**Issue by am11** [microsoft/WSL#3716]
This issue is also reproducible with MinGW64 and I am not sure what is the common denominator between WSL and MinGW. Please let me know if it belongs to a different repository / issue tracker.

```cmd
:: get the OS version
C:\>ver

Microsoft Windows [Version 10.0.18298.1000]

:: enter some WSL distro
C:\>alpine
```
```sh
# get the OS version
~:❄️ $ cat /etc/os-release | grep VERSION
VERSION_ID=3.8.0

# test copy and paste using win32 interoperability
~:❄️ $ echo HelloWorld! | clip.exe; powershell.exe -noprofile -command Get-Clipboard
HelloWorld!

# test the same thing with single character to get weird character
~:❄️ $ echo 1 | clip.exe; powershell.exe -noprofile -command Get-Clipboard
਱

# same problem with an alphabet
~:❄️ $ echo a | clip.exe; powershell.exe -noprofile -command Get-Clipboard
੡

# with two or more characters, it works fine
~:❄️ $ echo A1 | clip.exe; powershell.exe -noprofile -command Get-Clipboard
A1
```

`Get-Clipboard` cmdlet or pasting with keyboard/mouse in any editor gives the same `੡` character.

**Comment by therealkenc** [comment]
Nice. Was able to reproduce here. No doubt this is an edge case in the two byte encoding on Windows and one byte WSL/Linux. Legit, thanks.

**Comment by therealkenc** [comment]
Try this. It's fun.

![image](https://user-images.githubusercontent.com/7049700/50048897-e8574b80-008b-11e9-9c84-798739de3178.png)

**Comment by therealkenc** [comment]
Forward dupe up to #4852 where there is some more investigation. The OP scenario is pretty clearly the same.

> I am not sure what is the common denominator between WSL and MinGW

I am mildly sure. The common denominator between WSL and MinGW is `clip.exe`.

I can't reproduce the "`echo a`" game above on 19951. That could be #4637; we'll probably never know. Whatever that was, it is **not** related to the OP.

**Comment by sellithy** [comment]
Was this issue closed because it was fixed? If so, then it should be reopened because the same thing still happens.
