### ISSUE TITLE
Permission denied when moving file which is owned with 777

### ISSUE THREAD

**Issue by AlseinX** [Microsoft/WSL#3717]
I am running debian (the latest version from the microsoft store) on Windows 10 1803 x64
the folder is checked out by git in a repository (the repository is cloned in a folder in the home path `~/`)
when I was trying to rename the folder, `Permission denied`
I can open, edit or delete the files inside the folder but I cannot mv the folder
I have runned the commands to ensure I get the full permission
```
sudo chown -R my-name the-whole-repository
sudo chmod -R 777 the-whole-repository
```
I still have this problem. (WHY???)
but if I change the permission to 644, mv command works. (WHY???)

And, when I was running VS code inside WSL (forwarding X11 to the local hosted VcXsrv),
VS code cannot even list the files inside the folder when the permission is 644 as the owner (WHY???)
but when I changed it to 777, VS code can list, open, and edit the files normally, but cannot move (again WHY???)

**Comment by therealkenc** [comment]
No repro given. Duping #1529 summarily for lack.
