### ISSUE TITLE
Renaming user profile folder breaks WSL

### ISSUE THREAD

**Issue by huxoll** [Microsoft/WSL#3720]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17763.194

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I renamed my user folder as per https://support.microsoft.com/en-gb/help/2454362/renaming-a-user-account-does-not-automatically-change-the-profile-path
...after install Ubuntu/WSL
Subsequently, launching Ubuntu fails with an error about creating a file that already exists.
 
* What's wrong / what should be happening instead:
Startup should reference the user profile setting rather than apparently a fixed path.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
@huxoll - Thanks for filing. This is definitely an oversight since the path to the distribution's root filesystem will not be updated when the profile name is changed.  I will take a look at fixing this.

**Comment by benhillis** [comment]
@huxoll - Just to make sure I'm following this correct, you did not run into issues until modifying the ProfileImagePath registry key?  The link you pasted does not mention Windows 10, so I'm thinking it is not supported.

From playing around with this a bit myself, all sorts of things fall over when this value is modified (including not being able to install store apps any longer and getting error messages when I log in).  As such, I don't think there's much that can be done about this.

**Comment by weyfonk** [comment]
I know this issue is closed, but in case this helps someone: I recently renamed my user profile folder using a similar method and broke WSL, with `bash` run from a Windows command-line environment telling me that no distribution was registered. This happened with Debian, but the same most likely applies to Ubuntu as well.

I fixed it as follows:
    

1. Installed [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline);
2. Ran `lxrunoffline.exe -rg -n 'Debian' -d '$my_windows_user_dir\AppData\Local\Packages\$the_debian_project_dir\LocalState'` to register my distro again;  at this point, I could only log into it as `root`;
3. Ran `debian.exe config --default-user $my_existing_debian_user` and was able to log in as a regular user as was the case before renaming my windows user directory.

**Comment by bryeduria** [comment]
> 
> 
> I know this issue is closed, but in case this helps someone: I recently renamed my user profile folder using a similar method and broke WSL, with `bash` run from a Windows command-line environment telling me that no distribution was registered. This happened with Debian, but the same most likely applies to Ubuntu as well.
> 
> I fixed it as follows:
> 
>     1. Installed [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline);
> 
>     2. Ran `lxrunoffline.exe -rg -n 'Debian' -d '$my_windows_user_dir\AppData\Local\Packages\$the_debian_project_dir\LocalState'` to register my distro again;  at this point, I could only log into it as `root`;
> 
>     3. Ran `debian.exe config --default-user $my_existing_debian_user` and was able to log in as a regular user as was the case before renaming my windows user directory.

I was able to make my Ubuntu run by removing the dash on the rg (i.e. -rg to rg), and by doing the rest of your instructions. Thank you!

**Comment by riolly** [comment]
> I know this issue is closed, but in case this helps someone: I recently renamed my user profile folder using a similar method and broke WSL, with `bash` run from a Windows command-line environment telling me that no distribution was registered. This happened with Debian, but the same most likely applies to Ubuntu as well.
> 
> I fixed it as follows:
> 
> 1. Installed [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline);
> 2. Ran `lxrunoffline.exe -rg -n 'Debian' -d '$my_windows_user_dir\AppData\Local\Packages\$the_debian_project_dir\LocalState'` to register my distro again;  at this point, I could only log into it as `root`;
> 3. Ran `debian.exe config --default-user $my_existing_debian_user` and was able to log in as a regular user as was the case before renaming my windows user directory.

It also work for me by removing "-" on rg
Look like this
`lxrunoffline rg -n 'Debian' -d C:\Users\riolly\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState`

**Comment by PeterQiu0516** [comment]
Also works for me

```
lxrunoffline rg -n 'Debian' -d C:\Users\<username>\AppData\Local\Packages\<the_debian_project_dir>\LocalState
```

**Comment by kuangfu2016** [comment]
When I tried to run
```
lxrunoffline.exe -rg -n 'Debian' -d '$my_windows_user_dir\AppData\Local\Packages\$the_debian_project_dir\LocalState'
```

I got an error as
```
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".
```

After creating a `DistributionName REG_SZ Alpine` (`Alpine` is an arbitrary value), above command succeded.

**Comment by imansyaefulloh** [comment]
If anyone still have this problem, i fixed it using this method

just open registry editor, and then go to this 

`HKY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Lxss`

find 'BasePath', and update old user name using new one

**Comment by Dengda98** [comment]
> If anyone still have this problem, i fixed it using this method
> 
> just open registry editor, and then go to this
> 
> `HKY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Lxss`
> 
> and check every folder inside it, and then find 'BasePath', and update old user name using new one

Works for me! Easy method, Thanks!
