### ISSUE TITLE
first launch dialog should ask if I keep the same user as the windows user

### ISSUE THREAD

**Issue by mailinglists35** [Microsoft/WSL#3721]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.441]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
open microsoft store
search ubuntu
install ubuntu
launch
i am prompted for name of new user
![image](https://user-images.githubusercontent.com/2054302/50292404-b07c4980-0479-11e9-85d3-43e242e2640e.png)

* What's wrong / what should be happening instead:
to be prompted instead if I want to use my logged-on windows username or type in a new user name

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
That prompt is from the Store app (Ubuntu/Canonical) and not controlled by WSL. You could modify mechanism [here](https://github.com/Microsoft/WSL-DistroLauncher/blob/540a593313f8abbc8ce3afe8ca98434e8a771798/DistroLauncher/DistroLauncher.cpp#L44) if you want to [roll your own](https://blogs.msdn.microsoft.com/commandline/2018/03/26/wsl-distro-launcher/).
