### ISSUE TITLE
WSL shell freezes upon automount while off from local network

### ISSUE THREAD

**Issue by lsoustelle** [microsoft/WSL#3728]
* Your Windows build number:  `version 10.0.17134.472`

* What you're doing:  running WSL shell (here Debian 9) on my laptop, with automatic remote drive mounting (/etc/fstab), while being off from my local network.
```
myself@name:~$ cat /etc/fstab
LABEL=cloudimg-rootfs   /        ext4   defaults        0 0

\\localnetwork\remote_drive /mnt/remote_drive drvfs
```
Basically, while connected to the local network (\\\\localnetwork), everything works perfectly as expected (remote drives are being mounted automatically as I run the WSL shell).
On the other hand, being off from it results in an empty shell (no login) upon running the shell ; a `^C` shuts down the window.
Alternatively, I discovered that rebooting the LxssManager Windows service allows to bypass the issue ; altough temporarily, which is somewhat annoying.

Does anyone have any idea to address this specific issue ?

**Comment by therealkenc** [comment]
Tagging this "file system" for the fact that WSL probably (possibly?) ought not freeze in the scenario, and certainly ought not require restarting `LxssManager`. I haven't actually reproduced here. But in general, sticking filesystems that might not be there in `/etc/fstab` is bad news on Real Linux™ too. This sort of thing is usually handled by more sophisticated mechanisms like `systemd-automount` (or similar), and WSL does not have a good `systemd` story right now (ref #994).

Work-around on WSL2 would be to test for the mount in your `.bashrc`, and if it isn't there, do a `sudo mount.cifs ...` on your share.

**Comment by lsoustelle** [comment]
thanks for the reply !
