### ISSUE TITLE
`kali config --default-user root`  wont work as expected  

### ISSUE THREAD

**Issue by MisakaMikoto19090** [Microsoft/WSL#3729]
**Please fill out the below information:**
* Your Windows build number: 
    Microsoft Windows [Version 10.0.17763.195]

* What you're doing and what's happening: 
     `kali config --default-user root`

* What's wrong / what should be happening instead:
    * wrong: when you login kali by typing `kali.exe` it is the user i created when first launched:`wsluser@COMPUTER`
    * should happen: when you login it shoud be like `root@COMPUTER` 

* Strace of the failing command, if applicable: 
    the command throw no error
    this command works fine with ubuntu : `ubuntu config --default-user root`,when you login ,it is root as expected

**Comment by therealkenc** [comment]
Can't reproduce here.

![image](https://user-images.githubusercontent.com/7049700/50404212-26becb80-075a-11e9-9686-097f2faf1f00.png)

**Comment by MisakaMikoto19090** [comment]
thank you for your time .
after several times of reboot and uninstall and install kali . it worked .
