### ISSUE TITLE
Can't run Qt based apps on wsl 

### ISSUE THREAD

**Issue by elswerky** [Microsoft/WSL#3730]
whenever i install a qt based app and try to run it on arch on wsl or any other terminal emulator with the use of x410 server  i get this error 

**error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory**

mostly all apps based on qt gives me this error 

any idea how to fix it 
i have qt-base pkg installed on arch on wsl ,,and on ubuntu on wsl

**Comment by therealkenc** [comment]
Please ask this in the group responsible for your arch rig. Ref #2820 ([message](https://github.com/Microsoft/WSL/issues/2820#issuecomment-378324824)).
