### ISSUE TITLE
slash and backslash character corruption

### ISSUE THREAD

**Issue by yuis-ice** [Microsoft/WSL#3731]
The character slash and backslash is be clipped to clipboard with the state of having character corruption. 

e.g. 

```
echo "\\" | clip.exe # is clip "ਯ"
echo "/" | clip.exe # is clip "ੜ"
```

gif: [https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_391e1a04-4a8f-4734-b2a8-8cda16709d5d.gif](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_391e1a04-4a8f-4734-b2a8-8cda16709d5d.gif)

I've tried to solve this issue with

- without .bashrc file with `env -i bash --norc --noprofile`
- to try on another computer 
- raw bash prompto (I'm usually using Conemu as bash runner)

**Comment by therealkenc** [comment]
Almost certainly variation #3716
