### ISSUE TITLE
Windows 10 1809 Buffer issues with VSCode (windows ver)

### ISSUE THREAD

**Issue by weikinhuang** [microsoft/WSL#3734]
After upgrading to W10 1809, I'm having issues running VSCode (the windows version) from the WSL terminal via `code` commands.

I reported the issue here: https://github.com/Microsoft/vscode/issues/63539 & https://github.com/Microsoft/console/issues/333

However after some additional testing, I've discovered it might be a issue with WSL instead of vscode.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
Microsoft Windows [Version 10.0.18305.1003]
```

**Copying from the other issue**

Seems there might be some weird issue with the shell or something with the stdout buffer in the current version of wsl or ELECTRON_RUN_AS_NODE.

Note: I run this under a fresh install of Windows 10 1809 in a VM and a fresh install of WSL Ubuntu, and the VSCode x64 User Installer.

I ran `vscode --version` in the `Ubuntu` app shell and got this output with weird spacing:

```bash
$ code --version
1.30.1
      dea8705087adb1b5e5ae1d9123278e178656186a
                                              x64
```

Then I tried again with a cat to buffer the output, and it printed out fine:

```bash
$ code --version | cat
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
```

In the case where I opened the issue, I was running the shell via SSH and using a local ssh terminal emulator (`SecureCrt`):

```bash
$ code --version
--- NO OUTPUT ---
```

However if I use `cat` as I did above, it works just fine:

```bash
code --version | cat -           
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
```

This also solves the issue where I don't regain control of the terminal when I run `code .`, if I pipe it through `code . | cat -`, it works perfectly like it used to.

**Comment by sarunint** [comment]
Also Microsoft/vscode#62698.

**Comment by sarunint** [comment]
@weikinhuang can you confirm that in v1803 it is working?

**Comment by BookOfGreg** [comment]
Commenting to say thank you to @weikinhuang
I followed the long chain of open issues to get here. You've been really tenacious in following this issue right to the source!

**Comment by robhawkes** [comment]
Also seeing this since the 1809 update — happy to provide any information / diagnostics as required.

**Comment by BookOfGreg** [comment]
@benhillis Can you please mark this as a bug.

**Comment by ccpacillos** [comment]
I have a very similar issue. I have been following this thread and checking it every single day.
From what I have observed, if you have VSCode app already running, calling `code .` from wsl will return immediately.

**Comment by robhawkes** [comment]
Still seeing this in 1809. Has any progress been made? I've been holding onto 1803 for as long as I could but I was forcefully upgraded to 1809 yesterday so need to find a solution to this.

**Comment by BookOfGreg** [comment]
@robhawkes I'm assuming since the announcement of WSL2, this project is probably abandoned and everything in it will be closed.
