### ISSUE TITLE
Add proper argument parsing to wsl.exe and document CWD passing

### ISSUE THREAD

**Issue by Eugeny** [microsoft/WSL#3735]
Re https://github.com/Microsoft/WSL/issues/1346#issuecomment-449562215

1) Implement argument parsing that doesn't depend on magic parameter ordering

2) Document the way to pass CWD to the WSL shell.

**Comment by benhillis** [comment]
--cd <Directory>
        Sets the specified directory as the current working directory.
        If ~ is used the Linux user's home path will be used. If the path begins
        with a / character, it will be interpreted as an absolute Linux path.
        Otherwise, the value must be an absolute Windows path.
