### ISSUE TITLE
Arabic Support  In Gui apps and bash

### ISSUE THREAD

**Issue by elswerky** [Microsoft/WSL#3739]
why there is no arabic support for writing in wsl ??
i installed xfce4 desktop on wsl ,,but i can't write arabic on any gui app

for example gedit or any other app or firefox on wsl ,,,,it only display arabic writing but i can't write in arabic 

even in xfce desktop on wsl ,,i choose to write in both arabic and english but stilll only english and no arabic writing support!
this is screenshot shows that from inside xfce4 on wsl ,,i choose arabic language but still can't access it ,,also in bash terminal arabic letters appear as boxes (no support at all )
![font](https://user-images.githubusercontent.com/26687459/50542015-bb8e5280-0bba-11e9-81ce-00b214631a56.PNG)

**Comment by therealkenc** [comment]
See note [here](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799). It  is impossible to tell with the info given, but if that is a native X server like xdrp you are probably looking at variation #2730. If it is a Windows X (such as VcXsrv) server you'd need to ask the purveyor of that product. Either way no repro.

**Comment by elswerky** [comment]
here are screenshots from cmd ,, powershell and ubuntu 18.04 on windows 10 l
the arabic letters not understood !
and by the way i can't write arabic in gui apps on wsl   ,, the x11 server is x410 from ms store ,, i don't think it is a problem from x11 server (may be) 
![cmd](https://user-images.githubusercontent.com/26687459/50542342-298b4780-0bc4-11e9-8756-14f680097de1.PNG)
![powershell](https://user-images.githubusercontent.com/26687459/50542343-2a23de00-0bc4-11e9-8b72-b53d0f789743.PNG)
![ubuntu](https://user-images.githubusercontent.com/26687459/50542344-2a23de00-0bc4-11e9-990e-7d975740d95d.PNG)

**Comment by therealkenc** [comment]
Your OP was about an X server. Console questions should be directed [here](https://github.com/microsoft/console) (which is also stated in the [template](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md)).
