### ISSUE TITLE
semctl(1, 2, IPC_STAT, segment_address) returns -1 (Permission Denied)

### ISSUE THREAD

**Issue by shabiel** [microsoft/WSL#3743]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!  Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.17763.195]
* What you're doing and what's happening: 
This happens on a database program [YottaDB](https://yottadb.com/) that is used in banking and healthcare. Here are all the steps to reproduce:
1. Install Ubuntu 18.04 from the Windows Store.
2. Install YottaDB on Ubuntu

```
sudo apt install binutils
mkdir /tmp/tmp ; wget -P /tmp/tmp https://gitlab.com/YottaDB/DB/YDB/raw/master/sr_unix/ydbinstall.sh
cd /tmp/tmp ; chmod +x ydbinstall.sh
sudo ./ydbinstall.sh --utf8 default --verbose
```

You will get this at the end of all the output:
```
YottaDB version r1.22 installed successfully at /usr/local/lib/yottadb/r122
YottaDB pkg-config file installed successfully at /usr/share/pkgconfig/yottadb.pc
```

Note: when running some of the commands, you will get this error due to the absence of /dev/log. This is unrelated to the issue at hand.

```
YDB-MUMPS[936]: %YDB-E-SYSCALL, Error received from system call fopen() -- called from module /Distrib/YottaDB/R122/sr_unix/err_init.c at line 101, %SYSTEM-E-ENO2, No such file or directory -- generated from 0x00007FFC791A4124.
```

Now set-up to create a sample database:

```
$ export gtm_dist=/usr/local/lib/yottadb/r122
$ export gtmroutines=/usr/local/lib/yottadb/r122/libyottadbutil.so
$ export gtmgbldir="$PWD/mygbl.gld"
$ $gtm_dist/mumps -r ^GDE <<< "exit"
%GDE-I-GDUSEDEFS, Using defaults for Global Directory
        /tmp/testdb/mygbl.gld

GDE>
%GDE-I-VERIFY, Verification OK

%GDE-I-GDCREATE, Creating Global Directory file
        /tmp/testdb/mygbl.gld

$ $gtm_dist/mupip create
%YDB-I-DBFILECREATED, Database file /tmp/testdb/mumps.dat created

$ $gtm_dist/mumps -r ^%GD <<< '*'

Global Directory

Global ^

start+1^%GSEL,%YDB-E-DBFILERR, Error with database file /tmp/testdb/mumps.dat,%YDB-I-TEXT, Error with database control semctl IPC_STAT1,%SYSTEM-E-ENO13, Permission denied
```

* What's wrong / what should be happening instead: No error.

* Strace of the failing command, if applicable:  [gist](https://gist.github.com/shabiel/ccff1ec5a0468791c812535314f969aa).

**Comment by 1ftskank** [comment]
We've also run into this issue with `semctl`. Would be great to get this fixed! Could we have an update on this issue please?
