### ISSUE TITLE
wsl.exe leaks memory when running windows processes

### ISSUE THREAD

**Issue by marc-groundctl** [Microsoft/WSL#3746]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.195]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

When I run `while true; do /mnt/c/Windows/System32/cmd.exe /c '' ; done` wsl.exe's memory usage continuously increases.

* What's wrong / what should be happening instead:

wsl.exe should not be allocating all of my memory.

This happens when running any Windows program, not just cmd.

**Comment by benhillis** [comment]
Thanks for filing, I have identified the memory leaks and will be submitting a fix.

**Comment by benhillis** [comment]
Fixed in 18323.
