### ISSUE TITLE
Bash and cmd virtualenv overlap

### ISSUE THREAD

**Issue by klondikemarlen** [Microsoft/WSL#3748]
Problem: I am currently developing using both bash (Ubuntu, WSL) and Windows 10. I need to be able to install my project in both a Windows and Ubuntu environment. This lead me to creating a Python virtual environment in to test my python app in both Windows and Ubuntu. The setup is like this:

myapp/windowsvenv
myapp/linuxvenv
myapp/frontend
myapp/etc.

As soon as I create a virtualenv in Bash the one from Windows no longer works. I am currently using Python3.6 and pip 18.1. There seems to be some kind of cache or configuration overlap?

**Comment by iivmok** [comment]
@klondikemarlen what does "stop working" mean?

**Comment by klondikemarlen** [comment]
Complete failure. Seems to be looking for files that don't exists, in all the wrong places.
