### ISSUE TITLE
redraw of scrolling text inside GNU screen w/ caption is horribly slow

### ISSUE THREAD

**Issue by aleks-mariusz** [Microsoft/WSL#3750]
**Please fill out the below information:**
Version 1809 (OS Build 17763.195)

* Summary
I updated to win10 ver 1809 today (previously ran 1803), and one of the first things i noticed is that when within using GNU screen the redraw is noticeably _slower_, when using _caption_ value in .screenrc.

* Environment
Here's the contents of an example $HOME/.screenrc:

```
caption always '%{= kw}[ %{y}%H%{-} ][ %= %-Lw%{+b M}%n%f* %t%{-}%+LW %= ][ %{r}%l%{-} ][ %{c}%c%{-} ]'
```

This is a pretty basic setting for screen to draw a floating "status bar" on the bottom showing what screen is selected, and is discussed on https://lizdenys.com/journal/articles/understanding-gnu-screens-captions.html

After i updated to 1809, i noticed that when launching GNU screen from within WSL (triggered via bash.exe), and doing something that requires the screen to re-draw scrolling text, the refresh rate is pretty slow (e.g. doing something like ```ls -l /usr/bin``` takes several seconds instead of being near instance when not using that setting in screen.

I've also tried resetting my environment entirely (wiping out all bash shell settings files e.g. $HOME/.bashrc and $HOME/.bash_profile).  I narrowed it down to that captions always line being the culprit.  I was first noticed how painful running ps auxwww was on a remote linux system :-(

* What you're doing and what's happening:  
generating output that exceeds the size of the window, resulting in scrolling behaviour.  the redraw of the text from scrolling, results in a rate that makes me think i'm back on my first 486 computer

```
$ echo "caption always '%{= kw}[ %{y}%H%{-} ][ %= %-Lw%{+b M}%n%f* %t%{-}%+LW %= ][ %{r}%l%{-} ][ %{c}%c%{-} ]'" > .screenrc
$ screen
[... inside new screen ...]
$ ls -l /usr/bin
```

* What's wrong / what should be happening instead:
time to perform a simple "dir" (via ```ls -l /usr/bin```) takes ~20 seconds inside GNU screen 

this same listing takes only a second and a half when not using GNU screen at all (or not using that captions always line in $HOME/.screenrc) .  

whether or not using a screen multiplexer like GNU screen should not affect the refresh time, at least it didn't before i upgraded to win10 ver 1809 today.

* Strace of the failing command, if applicable:  
 not applicable, running the ls comand using time reports nearly identical values: 

outside of screen:
```
real    0m1.240s
user    0m0.016s
sys     0m0.063s
```

inside screen: 
```
real    0m0.069s
user    0m0.000s
sys     0m0.063s
```

Which makes it seem that the comand isn't what's running any slower (in fact it reports it ran faster?) but the drawing the scrolling text is what's in-fact impacted.

**Comment by DarthSpock** [comment]
Wrong GitHub, you want to file with Console: https://github.com/Microsoft/Console/issues/

**Comment by therealkenc** [comment]
#2772
