### ISSUE TITLE
radare2 Not Working Correctly on Kali

### ISSUE THREAD

**Issue by ReaHe** [microsoft/WSL#3753]
* Your Windows build number: 
Microsoft Windows [Version 10.0.17134.472]

* What you're doing and what's happening:  

I am using radare2 to open a process in debug mode. This use to work in the past, however it stopped working recently and now just freezes my entire terminal. Ctrl-C will not interrupt the window either. radare2 runs perfect in static mode, this seems to also only affect the Kali Distro and not the Ubuntu Distro. I am able to reproduce this issue on my laptop as well using Kali via WSL.
Command:
radare2 -d /bin/ls

* What's wrong / what should be happening instead:
radare2 a reverse engineering program that should open the process as a separate process and be able to watch/manipulate it as if I was using gdb to debug a process.

I also attempted to strace, however straceing radare2 had different results then not straceing it. straceing would cause a graceful close unlike without it.

Thank you in advance for any solutions or help you provide/fix.

**Comment by Anutrix** [comment]
Same issue here. I am waiting for it to be updated to latest release version(3.2.0 right now) in debian repo. Did you try latest version from their github release page?. I don't have full Kali OS installed so I can't check.

**Comment by ReaHe** [comment]
I tested it with the Github and apt-get, and both have the exact same issues. I do not have a real Kali VM or computer with Kali installed. However if this was a Kali issue, I'm certain it would be known on the radare2 github. No one has stated this as a problem the last time I checked. I believe this a Kali-Windows thing. Considering uname -a passes "windows" as part of it. I would imagine this Kali was their implementation, and is a bug in their kernel.

**Comment by Anutrix** [comment]
This Radare2 issue is the same I think [link](https://github.com/radare/radare2/issues/12658).

**Comment by ReaHe** [comment]
Yep seems like the same issue, however my Ubuntu runs it fine. Its the Kali, that totally freezes the terminal.

**Comment by Vyber90** [comment]
I am experiencing this problem in WSL Kali, Linux 4.4.0-1904 for Windows x64_86 with everything up to date (not with github versions, but with apt-get ones), and I see the issue is still opened.
Is this problem still going out there, or is there any solution yet?
