### ISSUE TITLE
First Interop process launched per session cannot be killed from WSL, while following processes in the same session can

### ISSUE THREAD

**Issue by CherryDT** [microsoft/WSL#3760]
Windows 10.0.17763.107

I am observing a weird issue related to killing Windows processes (started from WSL) from within WSL. This is related to #1614 but it's a more specific problem so I thought it warrants its own issue.

### What's working

In general, when I start a Windows process from WSL, I get an `/init /mnt/c/path/to/process.exe` process inside WSL with the Windows image name as process title. If I send SIGTERM, SIGINT or SIGKILL to that process from within WSL, it kills the corresponding Windows process too, just as I'd expect. This even works by pressing Ctrl+C in the console in order to kill a Windows GUI process.

### What's NOT working

**However:** The _very first_ such process spawned in a _session_ (see my definition below) behaves in an unexpected manner - killing it will terminate only the WSL-side `init` process but leave the actual Windows process alive. All the following processes will be killable just fine.

### Clarifications

* Sessions: In this context, a session is defined by the `/init` process which is the parent of the shell's process tree. Starting `bash.exe` from Explorer will start a new session. Starting `bash` from within bash will keep the current session. Starting `bash.exe` (note the `.exe`) from within `bash` (either directly or through other Interop processes like `cmd.exe`) _will_ start a new session.
* It can be tested by launching e.g. `notepad.exe &` and then attempting to use `kill <PID>` (same with `kill -9 <PID>`) from either the same or any other bash shell. The _killer_ is not important, only the _launcher_ is.
* When testing this with a console program like `ping.exe` and using Ctrl+C it may seem to work even with the first process per session. However, this is only the case because most Windows console processes like `ping.exe` do handle Ctrl+C themselves, so they terminate on their own. Make sure to test with `kill`.
* It does not make any difference if the "bugged" Windows process is closed from Windows or left open.

### Example

Demonstrated below:

* Bash session started
* notepad.exe launched (first process) and killed from WSL
* notepad.exe is still around in Windows!
* (killing notepad.exe from Windows)
* notepad.exe launched (second process) and killed from WSL
* notepad.exe was killed correctly!
* notepad.exe launched (third process) and killed from WSL
* notepad.exe was killed correctly!
* Bash session exited, new bash session started
* Steps above repeated to show that it happens once for each session

```
Microsoft Windows [Version 10.0.17763.107]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

Z:\>bash
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22874
david@CHE-X1:/mnt/c/Users/david $ kill 22874
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
notepad.exe                  16932 Console                    1        14 320 K
david@CHE-X1:/mnt/c/Users/david $ taskkill.exe /f /pid 16932
ERFOLGREICH: Der Prozess mit PID 16932 wurde beendet.
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22890
david@CHE-X1:/mnt/c/Users/david $ kill 22890
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22902
david@CHE-X1:/mnt/c/Users/david $ kill 22902
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
david@CHE-X1:/mnt/c/Users/david $ exit
logout

Z:\>bash
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22938
david@CHE-X1:/mnt/c/Users/david $ kill 22938
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
notepad.exe                   2236 Console                    1        14 328 K
david@CHE-X1:/mnt/c/Users/david $ taskkill.exe /f /pid 2236
ERFOLGREICH: Der Prozess mit PID 2236 wurde beendet.
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22954
david@CHE-X1:/mnt/c/Users/david $ kill 22954
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
david@CHE-X1:/mnt/c/Users/david $ notepad.exe &
[1] 22966
david@CHE-X1:/mnt/c/Users/david $ kill 22966
[1]+  Terminated              notepad.exe
david@CHE-X1:/mnt/c/Users/david $ tasklist.exe | grep notepad.exe
david@CHE-X1:/mnt/c/Users/david $
```

**Comment by niander** [comment]
Any update on this? I am also experiencing the same!

**Comment by davidbailey00** [comment]
Copying @CherryDT's workaround from #1614 for those who haven't seen that issue:

> A workaround can be running a Windows process which does nothing from your .bashrc. Just add a line rundll32.exe (which will do nothing if launched without arguments) to the bottom of ~/.bashrc. This way, the first process you manually run in a bash session will always actually be the second process, hence it won't misbehave.

**Comment by davidbailey00** [comment]
It seems that at least for me, the ability to kill Window processes with CTRL+C sometimes stops working entirely - not sure why this is, but it seems to work again after restarting the WSL service (run `Restart-Service LxssManager` from an elevated PowerShell).
