### ISSUE TITLE
No SIGINT propagated to linux processes if WSL started with redirected streams

### ISSUE THREAD

**Issue by segrey** [microsoft/WSL#3766]
* Microsoft Windows [Version 10.0.17763.253]

Processes running inside a WSL started with redirected streams don't receive SIGINT signals when the WSL is stopped via Ctrl+C/sending SIGINT.

Prerequisites: install [Node.js](https://nodejs.org/) on both Windows machine and WSL (e.g. Ubuntu).
1. Create a new folder on Windows machine and place there `app.js` and `run-wsl.js` files:
```javascript
// app.js
process.on('SIGINT', () => {
  console.log('Got SIGINT');
  process.exit(123);
});

process.on('SIGHUP', () => {
  console.log('Child process in WSL: got SIGHUP');
  process.exit(124);
});

setInterval(() => {}, 1000);

console.log('Child process in WSL: started with pid ' + process.pid  + ' on ' + require('os').platform());
```

```javascript
// run-wsl.js
const WSL_EXE = 'ubuntu.exe';
const child_process = require('child_process');
const wslProcess = child_process.spawn(WSL_EXE, [
  'run', 'node', 'app.js'
], {stdio: 'inherit'});

console.log(WSL_EXE + ' process started: pid ' + wslProcess.pid + ' on ' + require('os').platform());

if (wslProcess.stdout) {
  wslProcess.stdout.on('data', (data) => {
    process.stdout.write(data);
  });
}

if (wslProcess.stderr) {
  wslProcess.stderr.on('data', (data) => {
    process.stderr.write(data);
  });
}

wslProcess.on('close', (code) => {
  const info = code === 0xC000013A ? ' as a result of Ctrl+C' : '';
  console.log(`${WSL_EXE} process exited with code ${code + info}`);
});


process.on('SIGINT', () => {
  console.log('run-wsl.js: got SIGINT, resending it to the ' + WSL_EXE + ' process');
  wslProcess.kill('SIGINT');
});
```

2. Run `node run-wsl.js` command on Windows machine in Command Prompt / PowerShell. The command will output the following text and will be running:
```
> node run-wsl.js
ubuntu.exe process started: pid 12600 on win32
Child process in WSL: started with pid 3 on linux
```

3. Press Ctrl+C, the process will output the following text and exit:
```
run-wsl.js: got SIGINT, resending it to the ubuntu.exe process
Child process in WSL: got SIGHUP
ubuntu.exe process exited with code 3221225786 as a result of Ctrl+C
```

* What's wrong / what should be happening instead:
The ubuntu.exe process was terminated as a result of Ctrl+C / SIGINT (confirmed by its exit code), but `app.js` running inside WSL didn't receive `SIGINT`. It received just `SIGHUP`.
It makes it impossible to terminate processes running inside WSL gracefully.

Please note the issue is reproduced when the ubuntu.exe process is started with redirected streams (see `{stdio: 'pipe'}`). It works correctly when started with inherited streams. Just replace `pipe` with `inherit` and it will work:
```
> node run-wsl.js
ubuntu.exe process started: pid 10880 on win32
Child process in WSL: started with pid 3 on linux
^CGot SIGINT
ubuntu.exe process exited with code 123
```

This issue was inspired by how tools, like IDEs, runs applications in WSL. In this case, IDEs start a WSL process (e.g. ubuntu.exe) with redirected streams and unable to terminated started linux processes gracefully. Moreover, if `SIGHUP` signal is handled in a special way, the underlying linux process might be never terminated (https://youtrack.jetbrains.com/issue/WEB-36644).

**Comment by CherryDT** [comment]
This may even have been the root cause of https://github.com/Microsoft/vscode/issues/44408

**Comment by GregUtas** [comment]
I have a C++ console application compiled under WSL-GCC-Debug in VS2002 (WSL2). One of its tests is to kill a runaway thread if it receives `SIGINT` via **ctrl-C**. This works on Windows, compiled with either MSVC or clang. A `SIGINT` hits a breakpoint in the signal handler. But entering **ctrl-C** in the Linux Console Window does nothing.
