### ISSUE TITLE
Unable to rename a directory if a binary is working inside it

### ISSUE THREAD

**Issue by MAnyKey** [Microsoft/WSL#3767]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.472]

* What you're doing and what's happening:  

I run the following Go program (which essentially calls `renameat` on the directory which contains the binary):

```
package main

import (
        "path/filepath"
        "log"
        "os"
)

func main() {
        s, err := os.Executable()
        if err != nil {
                log.Fatal(err)
        }
        s, err = filepath.Abs(s)
        if err != nil {
                log.Fatal(err)
        }
        d := filepath.Dir(s)
        root := filepath.Dir(d)
        err = os.Rename(d, filepath.Join(root, "tst2"))
        if err != nil {
                log.Fatal(err)
        }
}
```

```
manykey@MSEDGEWIN10:~/tst$ go build -o tst1/main tst1/main.go
manykey@MSEDGEWIN10:~/tst$ tree tst1
tst1
├── main
└── main.go

0 directories, 2 files
manykey@MSEDGEWIN10:~/tst$ ./tst1/main
2019/01/11 04:28:53 rename /home/manykey/tst/tst1 /home/manykey/tst/tst2: permission denied
```

* What's wrong / what should be happening instead: `renameat` fails with **EACCES**, but it should succeed.

* Strace of the failing command: https://gist.github.com/MAnyKey/e923c740029e8eea4f5a03e1d2375ad1

NOTE: unlinking the running binary file (or moving it outside the containing directory) helps working around this issue.

**Comment by therealkenc** [comment]
Another variation #1529. That directory is pinned like the Iron Sheikh and Hulk Hogan (too old?) by the running executable. 

> unlinking the running binary file (or moving it outside the containing directory) helps working around this issue.

That works because unlinking isn't actually `unlink(2)` semantics in WSL. That's really a `mv(1)` of the exe into a hidden Windows folder, which takes it out of the tree, which is then no longer pinned to the mat.

What you gonna do.
