### ISSUE TITLE
binfmt_misc bug

### ISSUE THREAD

**Issue by yoava333** [microsoft/WSL#3768]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.253]

* What you're doing and what's happening:  

When registering a format with an offset, binfmt fails to execute all ELF files even though the pattern doesn't match the ELF file.
```
perl -e 'print ":fmt_name:M:1:\x02::./interpreter:"' | sudo tee /proc/sys/fs/binfmt_misc/register
$ ls
-bash: /bin/ls: No such file or directory
$ bash
bash: /bin/bash: No such file or directory
```
Trying to install the same interpreter with magic on 0 offset the problem doesn't happen.

* What's wrong / what should be happening instead:
binfmt_misc should only try to execute the interpreter on files that which the 2nd bytes is equal to 0x02, which are not elf files: 
```
00000000  7f 45 4c 46 02 01 01 00  00 00 00 00 00 00 00 00  |.ELF............|
```

**Comment by therealkenc** [comment]
Was able to repro here. Thanks.
