### ISSUE TITLE
Can not 'mv' files to a target containing ':' on drvfs

### ISSUE THREAD

**Issue by nomike** [Microsoft/WSL#3773]
Problem:
When using the 'mv' command on a drvfs mount, specifying a target which contains a ':' will lead to a 'No such file or directory' error.

Steps to reproduce:
'''
micpos@VIE-MICPOS-MOB:/tmp% cd test 
micpos@VIE-MICPOS-MOB:/tmp/test% touch foo
micpos@VIE-MICPOS-MOB:/tmp/test% touch test:1 
micpos@VIE-MICPOS-MOB:/tmp/test% ls
foo  test:1
micpos@VIE-MICPOS-MOB:/tmp/test% mv test:1 bar 
micpos@VIE-MICPOS-MOB:/tmp/test% mv foo test:2
micpos@VIE-MICPOS-MOB:/tmp/test% cd /mnt/c/tmp/delete/test
micpos@VIE-MICPOS-MOB:/mnt/c/tmp/delete/test% touch foo   
micpos@VIE-MICPOS-MOB:/mnt/c/tmp/delete/test% touch test:1
micpos@VIE-MICPOS-MOB:/mnt/c/tmp/delete/test% ls           
foo  test:1
micpos@VIE-MICPOS-MOB:/mnt/c/tmp/delete/test% mv test:1 bar
micpos@VIE-MICPOS-MOB:/mnt/c/tmp/delete/test% mv foo test:2
mv: cannot move 'foo' to 'test:2': No such file or directory
'''

Expected behavior:
Either it should not be possible at all to have files with a ':' in the filename (so the 'touch' at the beginning should already fail) or the file should be renamed without an error message.
If it fails a proper error message should be displayed as I consider 'No such file or directory' to be very misleading.

Actual behavior:
'mv' fails with a big error message.

Reproducibility:
Always

Version information:
Windows 10 Version 1803 (OS Build 1734.472)

**Comment by 0xbadfca11** [comment]
That has been fixed in Version 1809. #3316
