### ISSUE TITLE
Cannot install WSL from PowerShell

### ISSUE THREAD

**Issue by kennethjf** [microsoft/WSL#3777]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.523]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Running as administrator

PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

* What's wrong / what should be happening instead:

I'm not able to install WSL as per instructions

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

log creation also failing:

PS C:\WINDOWS\system32> logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749843B3F5C9} -mode 0x00000008
 -ft 10:00 -o .\lxcore_kernel.etl -ets
>>
logman.exe : A value that is not valid (.\lxcore_kernel.etl) was specified for the outputFormat parameter. Valid
values are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter

PS C:\WINDOWS\system32> logman.exe create trace lxcore_user -p {D90B9468-67F0-5B3B-42CC-82AC81FFD960} -ft 1:00 -rt -o .\
lxcore_user.etl -ets
logman.exe : A value that is not valid (.\lxcore_user.etl) was specified for the outputFormat parameter. Valid values
are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_user -p {D90B9468-67F0-5B3B-42CC-82AC8 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter

PS C:\WINDOWS\system32> logman.exe create trace lxcore_service -p {B99CDB5A-039C-5046-E672-1A0DE0A40211} -ft 1:00 -rt -o
 .\lxcore_service.etl -ets
logman.exe : A value that is not valid (.\lxcore_service.etl) was specified for the outputFormat parameter. Valid
values are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_service -p {B99CDB5A-039C-5046-E672-1A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by mscraigloewen** [comment]
@alexpanter @kennethjf 
Are you able to install WSL using the GUI approach? 
Search for 'Turn windows features on or off' (It is available inside of Control Panel) and try to enable the optional component that way, does it still fail?

**Comment by kennethjf** [comment]
No, it returns an error that the resource cannot be located.

**Comment by alexpanter** [comment]
Yes the GUI approach also failed for me, which is why I was resorting to do things the old-fashioned way.

**Comment by mscraigloewen** [comment]
@kennethjf and @alexpanter could you please send me an email at: **crloewen@microsoft.com** with the logs from: `C:\Windows\Logs\CBS\CBS.log` and we can take a further look into what might be causing this!

In the meantime try running these commands in an Powershell window with Administrator privileges to try and fix it:
`sfc /scannow`
`dism /online /cleanup-image /restorehealth`

**Comment by abbyokleung** [comment]
@mscraigloewen is there any update on this issue? I'm having the same problem

**Comment by mscraigloewen** [comment]
@abbyokleung these kind of issues stem from an incorrect installation state which could be caused from a variety of issues. The best advice is to run these commands in a Powershell window with Administrator privileges:
`sfc /scannow`
`dism /online /cleanup-image /restorehealth`

And if that doesn't resolve the issue then you will need to look into resetting your installation of Windows. We're looking into ways to fix this! I'll post here if we get any major updates.

**Comment by Asinin3** [comment]
Same issue, above suggestions didn't help.
![powershell](https://user-images.githubusercontent.com/15137035/57099204-07185f00-6d5b-11e9-8800-c4ca12b95ded.jpg)
I'm also on Windows 10 LTSC, so the "turn windows features on or off" option won't work for me.

**Comment by Biswa96** [comment]
The one and only option that works, reinstall Windows 10 from scratch.

**Comment by abbyokleung** [comment]
I did an in place upgrade and it works now
https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/how-to-perform-an-in-place-upgrade-with-windows-10/7f0b236e-3c6c-4913-9691-c4baa2a6190a

**Comment by gitcnd** [comment]
Is this going to get fixed?  Can you give us a less-destructive way to sort this out other than a "reinstall" ?

**Comment by mscraigloewen** [comment]
Hi @gitcnd these kind of issues are difficult to diagnose and resolve as usually they're caused by your install or optional components being in a strange or unexpected state. In general the easiest way to resolve this is to reinstall, or repair your Windows image. We're also diving deeper with internal teams at Microsoft to help see if we can get some more targeted solutions.

**Comment by connorlyoung** [comment]
this is so rediculous.

**Comment by rd-pub-ac** [comment]
....still no fix?

**Comment by gitcnd** [comment]
the fix is to use a different version of windows.

**Comment by sourojitg** [comment]
If people are still looking for a fix, I have one. It's really dumb, but it worked for me. When opening PowerShell, make sure to run it as Administrator. I searched up PowerShell on Cortana and instead of clicking to open, I right clicked to "Run as Administrator". This is important because you can only run the WSL command in the Windows/windows32 folder (or windows64, depends)

**Comment by bpulliam** [comment]
I'm going to close this one, as the recommended approach is to use the 'wsl --install' command.  If you see an issue with --install, please file a new issue and we can fix/track that separately.

Thanks!

**Comment by Jeongki** [comment]
It's already been answered on StackOverflow, so ... hope this answer would be helpful for the person who watched this site first.

Powershell recognize the following as a script.
{012616AB-FF6D-4503-A6F0-EFFD0523ACE6}

Change it like following.
`{012616AB-FF6D-4503-A6F0-EFFD0523ACE6`}

` seems similar to \ in Linux. So, when it is changed that way, it works.
