### ISSUE TITLE
chroot: failed to run command ‘dpkg-deb’: Exec format error

### ISSUE THREAD

**Issue by liudonghua123** [Microsoft/WSL#3779]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.253]

* What you're doing and what's happening: 
I want to compile and run 32bit assemble program in my ubuntu 18.04 WSL.
So I tried to create a 32bit chroot environment, but When I execute this command `sudo debootstrap --variant=buildd --no-resolve-deps --arch=i386 bionic /var/lib/schroot/chroots/bionic-i386 http://mirrors.tuna.tsinghua.edu.cn/ubuntu/`, I got `chroot: failed to run command ‘dpkg-deb’: Exec format error` error.
The last few console logs were
```
......
I: Extracting sensible-utils...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting util-linux...
I: Extracting zlib1g...
W: Failure trying to run: chroot /var/lib/schroot/chroots/bionic-i386 dpkg-deb -f /var/cache/apt/archives/dpkg_1.19.0.5ubuntu2_i386.deb Version
W: See /var/lib/schroot/chroots/bionic-i386/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot /var/lib/schroot/chroots/bionic-i386 mount -t proc proc /proc
W: See /var/lib/schroot/chroots/bionic-i386/debootstrap/debootstrap.log for details
liudonghua@DESKTOP-KA8TQF4:/etc/apt$ chroot /var/lib/schroot/chroots/bionic-i386 dpkg-deb -f /var/cache/apt/archives/dpkg_1.19.0.5ubuntu2_i386.deb
chroot: cannot change root directory to '/var/lib/schroot/chroots/bionic-i386': Operation not permitted
liudonghua@DESKTOP-KA8TQF4:/etc/apt$ sudo !!
sudo chroot /var/lib/schroot/chroots/bionic-i386 dpkg-deb -f /var/cache/apt/archives/dpkg_1.19.0.5ubuntu2_i386.deb
chroot: failed to run command ‘dpkg-deb’: Exec format error
liudonghua@DESKTOP-KA8TQF4:/etc/apt$
```

I tried the same command on a ubuntu 18.04, it did not have such problem.

**Comment by liudonghua123** [comment]
I also tried another way to create a chroot via `mk-sbuild --arch=i386 bionic --debootstrap-mirror=https://mirrors.tuna.tsinghua.edu.cn/ubuntu`, it gave me the same error message. If I ignore the message and tried to activate the chroot via `schroot -c bionic-i386`, it shown me the error message `E: Failed to set personality ‘linux32’: Invalid argument`, my configuration file was the following 
```
liudonghua@DESKTOP-KA8TQF4:/etc/apt$ cat /etc/schroot/chroot.d/bionic-i386.conf
[bionic-i386]
description=Ubuntu 18.04 bionic-i386
directory=/var/lib/schroot/chroots/bionic-i386
root-users=liudonghua
users=liudonghua
type=directory
personality=linux32
liudonghua@DESKTOP-KA8TQF4:/etc/apt$
```

I am sure the `linux32` of `personality` is correct according to the man pages of `schroot`.

**Comment by therealkenc** [comment]
#2468 #390
