### ISSUE TITLE
Installation fails for all-numeric usernames

### ISSUE THREAD

**Issue by sraase** [Microsoft/WSL#3780]
**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.16299.847]

* What you're doing and what's happening:
Trying to install Ubuntu 16.04 with an all-numeric username, to match the username used elsewhere in the network. See below:

PS C:\Users\12345678\Ubuntu> .\ubuntu.exe
Installing, this may take a few minutes...
Installation successful!
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: 12345678
useradd: group '12345678' does not exist
adduser: `/usr/sbin/useradd -d /home/12345678 -g 12345678 -s /bin/bash -u 1000 12345678' returned error code 6. Exiting.
usermod: user '12345678' does not exist
passwd: user '12345678' does not exist
passwd: user '12345678' does not exist
passwd: user '12345678' does not exist
passwd: user '12345678' does not exist
[... until CTRL+C ...]
PS C:\Users\12345678\Ubuntu>

* What's wrong / what should be happening instead:

Installation should succeed with an all-numeric username.

**Comment by therealkenc** [comment]
> adduser: `/usr/sbin/useradd -d /home/12345678 -g 12345678 -s /bin/bash -u 1000 12345678'

This is sort of variation #3273. That line above fails on Real Ubuntu also, like [this](https://askubuntu.com/questions/920629/cannot-add-a-user-account-with-numerical-username-useradd-group-11-does-not). The solution would be to get Canonical to update their launcher to do a `groupadd` as part of the process. Or maybe you could talk Hayden into doing it [here](https://github.com/WhitewaterFoundry/WLinux/blob/master/DistroLauncher/DistributionInfo.cpp#L12). Work around, same as #3273, would be to bootstrap with a fake name and then add the user/group after the fact. Yes I know, lame, don't shoot the messenger.
