### ISSUE TITLE
Avoid Insider Build 18317

### ISSUE THREAD

**Issue by Brian-Perkins** [Microsoft/WSL#3781]
There is a WSL bug in the [18317](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18317) release. This will cause bugchecks, hangs and other unpleasant side-effects when WSL is used.

**Comment by benhillis** [comment]
To avoid this build you can use the "Pause Updates" feature via Settings -> Update & Security -> Windows Insider Program -> Stop Insider Preview Builds.

**Comment by riverar** [comment]
Any details on this bug? I haven't hit any problems yet.

**Comment by Biswa96** [comment]
Console team has fixed [many issues](https://blogs.windows.com/windowsexperience/2019/01/16/announcing-windows-10-insider-preview-build-18317/) and improved performance. How one can avoid this build? I didn't find any issue with WSL (since 2 hours).

**Comment by 0xbadfca11** [comment]
> [UPDATE 1/17] WSL should work correctly on this build – our apologies for the mix up.
> https://blogs.windows.com/windowsexperience/2019/01/16/announcing-windows-10-insider-preview-build-18317/

🤔

**Comment by Biswa96** [comment]
There should be a proper detailed changelog for this 18317 build in WSL release notes.

**Comment by am11** [comment]
Is win32 interoperability working for anyone? After updating to latest insider `10.0.18317.1000`, win32 commands appear to be no-op / no output.

```sh
~ powershell.exe -noprofile "echo Welcome!"
~ powershell.exe -noprofile "throw 'We got a problem ..'"
```

etc. used to show the output in WSL before the update.
