### ISSUE TITLE
Provide  public API to ELF binaries.

### ISSUE THREAD

**Issue by throwable-one** [Microsoft/WSL#379]
For now it is only possible to launch them using `bash.exe` that does not even supports redirection!
Please provide one of the following:
- cmdlet
- ole automation object (you already have com for `LxssUserSession`, but it does not support ole automation nor it is documented
- C API (there are some function for "pico processes" but they are undocumented!)
- .NET class

Anything giving user ability to work with WLS programmatically, not with `bash.exe`

**Comment by throwable-one** [comment]
Please document ``ILxssSession`` at least...

**Comment by russalex** [comment]
Thanks for the feedback and interest.

We are looking at how we want to expose interoperability between WSL and Windows.  We know that there is some interest (Such as #2 and on the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250514-allow-native-win32-applications-to-launch-wls-exec)).  For feature requests like this I would suggest going to the User Voice page and up voting.
