### ISSUE TITLE
Performance limitations

### ISSUE THREAD

**Issue by nonyy** [Microsoft/WSL#3791]
Version 10.0.17134.523

So my question is about WSL performance limitations. Obviously it was never intended for production, so...

here's what I am trying to accomplish:
1) tool: nodejs
2) goal: simultaneous calls to an API using all possible threads
3) about 22k requests to be made so performance is important
4) using cluster module to use all cores

and what happens:
1) node reports 8 cpus on windows node using `os.cpus().length`
2) node reports 1 cpu on wsl node using `os.cpus().length`

So are those cores supported? Or not? What's the implementation state? Thanks.

**Comment by nonyy** [comment]
@therealkenc so here's a repro:
1) Download image samples with the following options from http://unsample.net/
  - count 30
  - width 3000
  - height 3000
2) Unpack to a folder
3) Cd into it
4) Use GNU parallel - `time find -maxdepth 1 -type f -maxdepth 1 -name '*.jpg' | parallel --bar --eta convert -resize 50% {} {.}.new && find -name '*.new' -delete`
5) See output. It says CPU cores 1.
6) But strangely enough specifying jobs manually speeds things up even though it says jobs 0  `time find -maxdepth 1 -type f -maxdepth 1 -name '*.jpg' | parallel -j0 --bar --eta convert -resize 50% {} {.}.new && find -name '*.new' -delete`

**Comment by therealkenc** [comment]
That is not a repro.

> Use GNU parallel 

Calling this #3736 since whatever the steps it is you are doing, I imagine `/proc/[pid]/status` - `Cpus_allowed` is probably the root problem.
