### ISSUE TITLE
Can't Install Anything in the Terminal - WSL

### ISSUE THREAD

**Issue by DanielGelfand** [Microsoft/WSL#3793]
Microsoft Windows [Version 10.0.17134.523]

apt install is not working. For example, if I run sudo apt install python3-pip, all I get is errors. 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip-whl_8.1.1-2ubuntu0.4_all.deb  Connection failed [IP: 91.189.88.149 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.5/python3.5-dev_3.5.2-2ubuntu0~16.04.1_amd64.deb  Connection failed [IP: 91.189.88.161 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python3-defaults/python3-dev_3.5.1-3_amd64.deb  Connection failed [IP: 91.189.88.149 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python3-pip_8.1.1-2ubuntu0.4_all.deb  Connection failed [IP: 91.189.88.161 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python-setuptools/python3-setuptools_20.7.0-1_all.deb  Connection failed [IP: 91.189.88.149 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/w/wheel/python3-wheel_0.29.0-1_all.deb  Connection failed [IP: 91.189.88.161 80]

I have tried disabling Kaspersky, disabling IPv6, and reinstalling the WSL.

**Comment by therealkenc** [comment]
> I have tried disabling Kaspersky

No way to reproduce this so no concrete suggestions for you. But it is worth reiterating that disabling (contrast uninstalling) antivirus and/or any other third-party software that might be mucking at the networking layer is not necessarily sufficient in general. [This fact is complicated by the observation that disabling Kaspersky _does_ unblock some Kaspersky folks, in some scenarios, sometimes.]
