### ISSUE TITLE
st-link support ( usb problem ) 

### ISSUE THREAD

**Issue by AleksandrVin** [Microsoft/WSL#3803]
There is no way to use usb st-link debugger with wsl. Any other stuff like flashers isn't working with wsl.  This is a linux st-link software. https://github.com/texane/stlink. 
lsusb command gives , 0 usb devises. 
st-info command gives , no st-link devises

On windows st-link works well.

**Comment by therealkenc** [comment]
[this](https://github.com/texane/stlink/blob/6db0fc243ffb90aed314ef1d59811486e9214883/include/stlink/usb.h#L12). #2185 #2195 landing zone is #412

**Comment by neilbalch** [comment]
@therealkenc Sorry, what do you mean? I have the exact same question as OP.

**Comment by therealkenc** [comment]
> Many of your links are dead

The relevant duplicate, /dupe #2195, is alive.

STLink [depends](https://github.com/stlink-org/stlink/blob/ffe6240012d7cb83749bf00baf0e300cf7cab2ea/src/stlink-lib/libusb_settings.h#L4) on libusb.

> or otherwise too deep in the weeds

Indeed. Me I'd stop at the green "Open" icon at the top. There is no support for libusb on WSL as of this writing.

**Comment by neilbalch** [comment]
@therealkenc Ah okay and `libusb` is the interface required to support forwarding Windows USB devices to the linux environment? Gotcha.
