### ISSUE TITLE
Can not find ubuntu14.04 in Microsoft Store

### ISSUE THREAD

**Issue by wlmnzf** [Microsoft/WSL#3804]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
#### Microsoft Windows [Version 10.0.17763.253]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
#### I am just searching the Ubuntu 14.04 in Microsoft Store,But I can not find

* What's wrong / what should be happening instead:

**Comment by therealkenc** [comment]
Dupe #2321. The old 14.04 shipped with the now deprecated `bash.exe` not from the Store.
