### ISSUE TITLE
Computer loses internet connection after reinstalling WSL

### ISSUE THREAD

**Issue by GoncaloRod** [Microsoft/WSL#3808]
I've used Windows subsystem for Linux since it was released, but some months ago I installed it by disabling it on windows features and now I want to install it back but when I enable the feature my computer loses internet connection. Anyone has any idea of what is causing this problem?

**Comment by mscraigloewen** [comment]
That's an interesting problem! I haven't heard of it before.

Have you tried the regular troubleshooting activities? Here are some suggestions:
- Restarting your computer (And disabling it and reenabling it and restarting)
- Disabling and enabling your network adapter in device manager (and making sure the driver is up to date)
- Run hardware scanning commands (the second one uses internet): 
   ```
   sfc /scannow
   dism /online /cleanup-image /restorehealth
   ```

If none of those work please email me at: `crloewen@microsoft.com` and include these logs: `C:\Windows\Logs\CBS\CBS.log` and we can try and take a look! :)

**Comment by GoncaloRod** [comment]
I got it working! Apparently the network card was enabled, but all her features were disabled (like IPV4 and other things). Thank you for the tips!

**Comment by srockalex** [comment]
wow I just had this happen to me updating to build 19608 on w10 fast ring, over a year later, same issue. my intuition was to turn all the protocols back on, but hyper-v was in the mix too, so I assumed user error. Crazy how  many people in 15 months hit this snag read this work around and just kept going lol. Sounds like typical linux users to me. :) anyone heard if they plan on fixing this?
