### ISSUE TITLE
Don't segfault when there's an invalid Windows path

### ISSUE THREAD

**Issue by Coalpha** [microsoft/WSL#3810]
![image](https://user-images.githubusercontent.com/22552895/51888720-18ad2d80-234c-11e9-9357-bf8470f543ec.png)

I understand that the `/p` flag should not be used with something that doesn't begin with `/mnt/c/`

It'd be great if instead of a segfault, there was some information printed to stderr. Other than that, WSLENV seems to work really well :)

**Comment by benhillis** [comment]
I believe I fixed this recently, but will double-check today.

**Comment by benhillis** [comment]
Yep I'm unable to reproduce this on my end.  No issue template provided so I'm not sure what version you're running.

**Comment by Coalpha** [comment]
My bad. I should have read that issue template better
```
C:\>ver

Microsoft Windows [Version 10.0.17763.107]
```
[strace of the command](https://gist.github.com/Coalpha/3c441ebee50051f7a99d727569a5ff6f)

**Comment by worksWithTools** [comment]
Recently I've been trying to use WSL to run make files which pass environment variables with "." as the current directory. This results in apparently nothing happening. 

However, when trying to repro the behaviour manually I can get a segfault quite reliably as follows:

$ export MYPATH=.
$ export WSLENV=$WSLENV:MYPATH/p
$ cmd.exe
**Segmentation fault**

Here is the version info:
Microsoft Windows [Version 10.0.19041.84]
(It's the release preview)

The WSL I'm working in produces the same results whether its v1 or v2. 
Has there been a regression of this issue?
(I get the same result if I export MYPATH=foo -- where foo does not exist)
