### ISSUE TITLE
WSL launch error 0x000004C8 (ERROR_USER_MAPPED_FILE)

### ISSUE THREAD

**Issue by dmex** [microsoft/WSL#3811]
Starting wsl.exe or calling the WslLaunch API returns error 0x000004C8 (and sometimes error 0xffffffff).

![image](https://user-images.githubusercontent.com/1306177/51938981-b9fcb800-240e-11e9-8f5d-0630ac7a2e65.png)

* Your Windows build number:
10.0.17763.292

* What's wrong / what should be happening instead:

Anti-virus/Anti-cheat/Task managers/System tools regularly open file section handles to running processes such as the /init binary and this prevents WSL from starting if it exited too quickly just prior to starting WSL. This also causes the WslLaunch API to randomly stop working when it's called multiple times within a short timeframe and when the user hasn't started bash prior to the application calling WslLaunch. 

Here's simplified example of what happens in this scenario:
1) Application calls WslLaunch
2) The user hasn't previously started WSL and so LxssManager starts the /init process and executes command from step 1
3) Antivirus opens file section handle to /init
4) Lxss finishes executing command and terminates distribution (including /init).
5) Application calls WslLaunch a second time; Error 0x000004C8 

I've found a few applications running into this problem. You can easily reproduce the issue using notepad from the command prompt:

1) Execute "notepad > %path_to_init_binary%"
2) Execute wsl.exe or call WslLaunch.

![image](https://user-images.githubusercontent.com/1306177/51938285-00511780-240d-11e9-80ef-9102e6687893.png)

**Comment by Biswa96** [comment]
Interesting! Reproducible in Insider build 18323. The error in `LxssManager!Filesystem::UpdateInit` file. It copies `init` binary with `CopyFileW(..., ..., FALSE)`. If that fails then whole WSL execution fails. 

Is Antivirus opening file section handle same as the notepad command? Notepad R/W the `init` binary.

**Comment by benhillis** [comment]
This is likely the fault of the anti-virus software for not specifying appropriate sharing bits when opening the files to scan: https://docs.microsoft.com/en-us/windows/desktop/FileIO/creating-and-opening-files.
