### ISSUE TITLE
Reading in arguments causes segfault (C).

### ISSUE THREAD

**Issue by jedthe3rd** [Microsoft/WSL#3812]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.292]
* Your WSL version: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

* What you're doing and what's happening: 
I am running this code C code: 
mydash.c -
```
int main(int argc, char **argv)
{
    printf("%%");
    char *prompt = getenv("DASH_PROMPT");
    char *line;
    char **cArgs;
    int numArgs = 0;
    char *delimiter = " ";
    char *version = NULL;

    printf("%d", argc);
    if(argc >= 2){
        printf("test");
		 if(strcmp(argv[1],"-v") == 0){
				version = (char *) malloc(sizeof(char)*1024);
				sprintf(version, "Version 1: Revision");
				printf("%s   ", version);
				exit(0);
		}
    }
    
    exit(0);
}
```
This is the problem code (there is more to my full program but this is where things are going wrong.
When I enter the command:
`./mydash -v`
It will segfault.
When I enter the command:
`./mydash` 
It will run fine.

* What's wrong / what should be happening instead:
When I run the above code on a real linux install:
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core)
Release:        7.5.1804
Codename:       Core

It doesn't segfault when running:
`./mydash -v`

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

Not sure if applicable, will edit if someone says I should add it.

**Comment by therealkenc** [comment]
> Oh, tried to remove everything that wasn't part of the problem. Updated post with that removed.

Okay but now you've gone and "fixed" the problem. That doesn't segfault as of this writing (just tried).

Probably about enough for one night, eh? There are more appropriate groups on the Interwebs for this sort of thing. There's no WSL actionable here. But bonne chance.
