### ISSUE TITLE
WslRegisterDistribution failed with 0x80070422

### ISSUE THREAD

**Issue by dvescovi1** [Microsoft/WSL#3815]
Windows 10 Enterprise version 1803

I am on a corp network which has several group polices enforced. I was blocked from accessing the full MS-Store but was able to download via the following instructions:
https://docs.microsoft.com/en-us/windows/wsl/install-manual

I enabled wsl, rebooted and launched the CanonicalGroupLimitedUbuntu18.04onWindowsxxxx.Appx

it appeared to install but then got:
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070422
Error: 0x80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

Press any key to continue...

Any idea what could be causing this? Could it be due to some corp. group policy?

I do have local admin rights on my PC.

**Comment by Biswa96** [comment]
Did you enable WSL feature? Try this command `sc start LxssManager`, anything shows?

**Comment by dvescovi1** [comment]
C:\WINDOWS\system32>sc start LxssManager
[SC] StartService FAILED 1058:

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.


C:\WINDOWS\system32>

**Comment by dvescovi1** [comment]
I think you found the issue.
If I look under "Services" I see the LxssManager service is "disabled". 
If I try to set it to manual I get an "Access Denied".
My guess corp. disabled this as part of a group policy.

**Comment by Biswa96** [comment]
If you've registry access you can enable that service with registry.

**Comment by benhillis** [comment]
Yeah 0x80070422 is E_SERVICE_DISABLED. Not sure how it got into that state, but that's not a supported configuration.

**Comment by arclicious** [comment]
I'm on my Windows 10 Home installation and with no group policies edited or anything like that and I get the same "Access denied" error when I try to enable it.

**Comment by leonardovilarinho** [comment]
Same problem

**Comment by Salman-EF** [comment]
I had the same issue.
I just disabled & enabled "Windows Subsystem for Linux". reboot windows after each step as requested and everything worked as usual.

**Comment by josemalcher** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Exactly!
Remember to use CMD as Administrator

**Comment by leephung** [comment]
"sc config LxssManager start=auto" is my hero.  Much thanks for the tip!

**Comment by yeeking** [comment]
> I had the same issue.
> I just disabled & enabled "Windows Subsystem for Linux". reboot windows after each step as requested and everything worked as usual.

On Windows 10 Home, no sc.exe so cannot run the magic command, so the above worked for me.
* I typed windows features into the start search, selected turn windows features on or off
* I disabled WSL, rebooted.
* Went back in there again, enabled WSL, rebooted.
* Then I was able to re-enable the LxssManager service in the services list, though only in manual, still not allowed to set it to automatic for some reason. 

Noting that I am running Kaspersky cloud, since I had another non-circumventable permission denied problem with windows defender. Having not used Windows for serious work since Windows 2000, this kind of mad stuff where I as administrator and sole user of my computer can't turn things on that I want to turn on is totally infuriating and bonkers. I'm gonna dig out my windows 98SE disk. That was the last good one :) Oh hang on, not CD drive.

**Comment by ezero0** [comment]
Karsperski Free Antivirus block the service.  

"sc config LxssManager start=auto" Works

**Comment by DNCTrung** [comment]
> Karsperski Free Antivirus block the service.
> 
> "sc config LxssManager start=auto" Works

Thank @ezero0 , I choose to remove KFA.

**Comment by Groberts93** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Thank you so much.

**Comment by Kirandp6** [comment]
> sc config LxssManager start=auto

I was running with Powershell ... with cmd it worked !

**Comment by victordev13** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Thanks, it worked for me, then just ignore kaspersky in the popup

**Comment by iBOY2020** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Hey So I am learning hacking but  I created a discord server so that others can learn too.
If you have discord please join my server you seem to have knowledge in these stuff 
Link: https://discord.gg/MJmeaG92fS

**Comment by gbyteinfo** [comment]
sc config LxssManager start=auto tnaks, é só executar como adm o cmd e executar esse comando. Em seguida basta inicializar o Ubunto WSL

**Comment by tangosoftsrl** [comment]
> > El mismo problema. 
> > Logré arreglarlo entrando en modo seguro y usando:
> > Presione win + r; 
> > Escribe "cmd" 
> > Da el comando:`sc config LxssManager start=auto`
> > Parece que Kaspersky había bloqueado el servicio, por lo que es bueno volver a instalarlo si tienes uno, y cuando te pregunte sobre la ejecución de comandos de Linux lo dejas desbloqueado.
> 
> ¡Exactamente!
> Recuerde usar CMD como administrador

gracias, me funcionó a la perfección, el problema lo genera Karspersky free.

**Comment by marcelo-antiqueira-silva** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Welll! Great works for me! 

Remember execute cmd with Administrator Level! GREAT JOB!

**Comment by mufidu** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

finally it works. thanks.

**Comment by fbenrejdal** [comment]
Thanks for the tip
from CMD as administrator the command sc config LxssManager start=auto works !

**Comment by hevener10** [comment]
> Same problem.
> I managed to fix it by going into safe mode and using:
> 
> Press win + r;
> Write "cmd"
> Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

finally it works. thanks.

**Comment by giftmafomo** [comment]
> Same problem. I managed to fix it by going into safe mode and using:
> 
> Press win + r; Write "cmd" Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Was indeed blocked by Kaspersky after uninstalling, then running CMD the code was  a sucess since was denied before. Ubuntu is now running, Thanks alot!

**Comment by iipran** [comment]
> Same problem. I managed to fix it by going into safe mode and using:
> 
> Press win + r; Write "cmd" Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

thank youuuuu

**Comment by MaxGuH** [comment]
So, after using command 'sc config LxssManager start=auto' you should got the message similar to the one on the picture above - go to the Kaspersky app itself and choose "Ignore". And you set.
![Screenshot 2022-09-07 202121](https://user-images.githubusercontent.com/107904669/189019716-3e3d869d-c69b-4a05-b906-ade8e25792ce.jpg)

**Comment by PedroHenrique-Maia** [comment]
"sc config LxssManager start=auto" Funciona

**Comment by Gui-mp8** [comment]
> Same problem. I managed to fix it by going into safe mode and using:
> 
> Press win + r; Write "cmd" Give the command: `sc config LxssManager start=auto`
> 
> It seems that Kaspersky had blocked the service, so it is good to reinstall it if you have one, and when it asks about executing Linux commands you leave it unlocked.

Yes man, the problem was Kapersky rs

**Comment by MisaelAlves** [comment]
Exatamente aconteceu comigo. 

> Mesmo problema. Consegui corrigi-lo entrando no modo de segurança e usando:
> 
> Pressione win + r; Escreva "cmd" Dê o comando:`sc config LxssManager start=auto`
> 
> Parece que o Kaspersky bloqueou o serviço, então é bom reinstalá-lo se você tiver um, e quando perguntar sobre a execução de comandos do Linux, deixe-o desbloqueado.

Perfect, Done!

**Comment by rebroad** [comment]
I have this error also, but setting LxssManager to run at startup does NOT fix the issue. Can this issue therefore be re-opened given that the solution mentioned doesn't always work?

**Comment by DoctorSec22** [comment]
I fixed it without reinstalling Kaspersky. 
**Go to security -> manage resources -> search for wslhost.exe -> disable control**. After that I restarted my PC and it works fine.

**Comment by lorenzo-elias** [comment]
This solved my problem:
My pc decided to cancel the WSL Service, after putting it on again and restarting the LxssManager, everything worked. 
![afbeelding](https://github.com/microsoft/WSL/assets/94633339/e0751714-dc75-46c0-a9e0-0fc6673dcd0d)

**Comment by tongshu1943** [comment]
> This solved my problem: My pc decided to cancel the WSL Service, after putting it on again and restarting the LxssManager, everything worked. ![afbeelding](https://private-user-images.githubusercontent.com/94633339/315226455-e0751714-dc75-46c0-a9e0-0fc6673dcd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDM5NDUsIm5iZiI6MTcxMTU0MzY0NSwicGF0aCI6Ii85NDYzMzMzOS8zMTUyMjY0NTUtZTA3NTE3MTQtZGM3NS00NmMwLWE5ZTAtMGZjNjY3M2RjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEyNDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWM1NmE5MTdhMzc3ZGE4NGIzODEyYTk1ZTZmZTNhYTAzODQ2YWEyMTI0MjI0N2M5YTViZWFmYTgzN2ViM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1T2T83WGv0PPI35cACUvVWyufCzaiY4ZyV-6eJmzZo)

This worked! Thank you. Great help.

**Comment by sontoriyama** [comment]
thanks for
sc config LxssManager start=auto
i go to restart ;)

**Comment by n1xsi** [comment]
> This solved my problem: My pc decided to cancel the WSL Service, after putting it on again and restarting the LxssManager, everything worked. ![afbeelding](https://github.com/microsoft/WSL/assets/94633339/e0751714-dc75-46c0-a9e0-0fc6673dcd0d)

only this helped me
thanks so much 🙏
