### ISSUE TITLE
rlwrap crashed (caught SIGSEGV)

### ISSUE THREAD

**Issue by tomasorti** [Microsoft/WSL#3824]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.936]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1. Install rlwrap & python: `sudo apt install rlwrap python`
2. Put this content in a file:  
```
while True:
    inp = raw_input("> ")
    print "You entered", inp
```
3. Run: `rlwrap python read.py`, input some text and hit ENTER twice. You will get:
```
rlwrap: Oops, crashed (caught SIGSEGV) - this should not have happened!
If you need a core dump, re-configure with --enable-debug and rebuild
Resetting terminal and cleaning up...
```
* What's wrong / what should be happening instead:
It **should not crash** and give `readline` abilities.

Check: https://github.com/hanslub42/rlwrap/issues/95

**Comment by therealkenc** [comment]
Can't reproduce here with Python `2.7.16~rc1-1ubuntu0.1` on `18323`. You could try a newer WSL (16299 is quite old) but smarter money is something wrong with your userspace or other borkage. If you couldn't read a line of input in Python, even in 2017 FCU, you'd know.

**Comment by therealkenc** [comment]
Can't reproduce here with `python2.7 2.7.15~rc1-1ubuntu0.1` and `rlwrap 0.43-1` on 18323. You could try a new version of WSL (16299 is quite old) but more likely the problem is with your userspace or some other borkage.

**Comment by tomasorti** [comment]
I am not able to test in newer WSL version, since this is my company's laptop.  
They control the updates and unfortunately there is no update available now.

I have returned to the original `.profile` & `.bashrc` and still having this issue.  
Not sure what can I have wrong in my userspace to make this crash...  
Can you point what can I do to test it as clean as possible (avoid my userspace to intermingle)?

**Comment by therealkenc** [comment]
>  can you point what can I do to test it as clean as possible

You could download and compile the [rlwrap source](https://github.com/hanslub42/rlwrap) and try to figure out where it goes south with `gdb`. Wouldn't be a small undertaking.

Maybe try installing [Debian](https://www.microsoft.com/en-us/p/debian-gnu-linux/9msvkqc78pk6?rtc=1&activetab=pivot:overviewtab) try the test again immediately after installing the debian `rlwrap`. Not because there's anything magical about the Debian package versus Ubuntu, but you'll know your starting from an unadulterated userspace.

Possible you're hitting [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799943) or something like it.

**Comment by tomasorti** [comment]
Well, I tried a simpler approach.  
I created a new user on WSL with `adduser`.
Then tried the python example and it works.  

So it seems I have something corrupted in my userspace...  
Let's see how I fix that.
Thank you!

**Comment by tomasorti** [comment]
Finally found the mystery, an `.inputrc` file...
https://github.com/hanslub42/rlwrap/issues/95#issuecomment-460421296
