### ISSUE TITLE
Can not SFTP multiple files to Debian WSL.

### ISSUE THREAD

**Issue by gscorrea** [microsoft/WSL#3825]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.523]

When I try to SFTP multiple files to Debian WSL, I can only get the first file uploaded successfully, second file created, then the session stops. The second file data is not written and I have to cancel the sftp session.
I can only SFTP one fil at a time.
the SFTP works fine on any other Linux server I use.

* What's wrong / what should be happening instead:
I should be able to SFTP several files at once.

From /var/lo/auth.log we can see that SFTP uploads <file1> successfully , then creates <file2>, but never gets to write <file2>

Feb  4 21:19:05 DESKTOP-UGTU1VQ sshd[3391]: Accepted password for <user> from 127.0.0.1 port 51340 ssh2
Feb  4 21:19:05 DESKTOP-UGTU1VQ sshd[3391]: pam_unix(sshd:session): session opened for user <user> by (uid=0)
Feb  4 21:19:05 DESKTOP-UGTU1VQ sshd[3391]: pam_systemd(sshd:session): Failed to connect to system bus: No such file or directory
Feb  4 21:19:05 DESKTOP-UGTU1VQ sftp-server[3398]: session opened for local user <user> from [127.0.0.1]
Feb  4 21:19:05 DESKTOP-UGTU1VQ sftp-server[3398]: received client version 6
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 1: open flags 26
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: open "/home/<user>/<file1>" flags WRITE,CREATE,TRUNCATE mode 0666
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug1: request 1: sent handle handle 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug1: request 2: write "/home/<user>/<file1>" (handle 0) off 0 len 1464
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 2: sent status 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: sent status Success
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug1: request 3: fsetstat handle 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: set "/home/<user>/<file1>" modtime 20190204-15:30:33
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 3: sent status 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: sent status Success
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 4: close handle 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: close "/home/<user>/<file1>" bytes read 0 written 1464
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 4: sent status 0
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: sent status Success
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug3: request 5: open flags 26
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: open "/home/<user>/<file2>" flags WRITE,CREATE,TRUNCATE mode 0666
Feb  4 21:19:06 DESKTOP-UGTU1VQ sftp-server[3398]: debug1: request 5: sent handle handle 0

Feb  4 21:23:57 DESKTOP-UGTU1VQ sftp-server[3398]: debug1: read eof
Feb  4 21:23:57 DESKTOP-UGTU1VQ sftp-server[3398]: forced close "/home/<user>/<file2>" bytes read 0 written 0
Feb  4 21:23:57 DESKTOP-UGTU1VQ sftp-server[3398]: session closed for local user <user> from [127.0.0.1]
Feb  4 21:23:57 DESKTOP-UGTU1VQ sshd[3391]: pam_unix(sshd:session): session closed for user <user>

**Comment by mscraigloewen** [comment]
Hi @gscorrea I tried to replicate this by using sftp on both a Linux machine and in WSL. I found that using the `mput` command to upload multiple files didn't work as intended in either, so it may not be a problem with WSL. Is this the command that you're using?

Could you please send over the list of commands you're trying so we can try and reproduce it more accurately? 

Thank you!

**Comment by gscorrea** [comment]
I used MOBAXterm SFTP functionality that works perfectly with my other non WSL Linux machines. (same MobaXterm application). Once it freezes on second file upload, I cancel it and start another upload from the second file (now first file) and it uploads it successfully and then freezes on the new second file.

**Comment by mscraigloewen** [comment]
@gscorrea I'm not quite sure what issue you're running into. I wasn't able to find the SFTP functionality on MOBAXterm. Are you connecting to an external server? Or are you hosting the server using MobaXterm?

**Comment by gscorrea** [comment]
I am running WSL Debian and using MobaXterm to ssh to the WSL.
When you SSH connect via MOBA, an SFTP tab opens on the left side of the MOBA app, this is the one I am using.

Sent from Mail for Windows 10

**Comment by mscraigloewen** [comment]
I see!
Just to check my understanding:
You're SSHing into a WSL instance running Debian (which is running a SSH server), and that WSL instance is not on the current computer that you're using.

Is that correct?
I'll try and replicate the problem.

**Comment by mscraigloewen** [comment]
Are you running the SSH server and SSHing into the same machine? MobaXterm can connect to the WSL instance without SSH. That can be accomplished just by opening up a new session and selecting WSL.

As well, in general, an SSH server on WSL can be complicated to setup and manage. I would recommend connecting to WSL as a regular session inside of MobaXterm (which only works provided that the WSL instance you're trying to connect to is on the machine you're using). 

And as far as SFTP, I would recommend using the `scp` command, which I haven't had any problems with.

**Comment by gscorrea** [comment]
Hi Craig,

Yes, Moba and WSL on same windows machine.
My SSH connection is working perfectly.
SFTP for multiple files does not work, for single file it works fine.
So I imagine that the configuration for SSH is fine.
Only Moba 11 supports native WSL, I have Moba 10.9 pro and not planning to buy new licenses now.



Sent from Mail for Windows 10

**Comment by mscraigloewen** [comment]
Hey @bitcrazed could you take a look at this issue as well? :)
