### ISSUE TITLE
Android Source Code Build Issues in WSL

### ISSUE THREAD

**Issue by NandhanThiravia** [microsoft/WSL#3826]
* Windows build number:  Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:
I am trying to sync the Android P Source Code and trying to build

* What's wrong / what should be happening instead:
After syncing the code, I tried to run the "lunch" command but the lunch command failed with certain number of files mentioned as missing but I can find them using "ls" command. Actually it fails either in "lunch" or in "make", it is kind of very un-certain.

- When it fails using "lunch" command, find the logs
_nandhan@IND54Q3JR2:/mnt/c/Project/Android_Platform/SourceCode/platform_P_asample$ lunch vw_regio-userdebug
11:16:02 Could not create module-finder: finder encountered 3 errors: [/mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/2.0: lstat /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/2.0: no such file or directory /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/1.2.3: lstat /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/1.2.3: no such file or directory /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/2.0-rc1: lstat /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/external/mockftpserver/tags/2.0-rc1: no such file or directory]_

- When it fails using "make" command, find the logs
nandhan@IND54Q3JR2:/mnt/c/Project/Android_Platform/SourceCode/platform_P_asample$ make -j8
11:42:37 Could not create module-finder: finder encountered 1 errors: [/mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/frameworks/ex/common/tests/src/com/android/common: lstat /mnt/c/Project/Android_Platform/SourceCode/platform_P_asample/frameworks/ex/common/tests/src/com/android/common: no such file or directory]

**It is so uncertain that, upon trying multiple times the Lunch command succeeded, once I tried to build the source code using Make, the command failed, but after some more attempts Make command also started working. 
Currently Make command is in progress so not sure if it would succeed ultimately.**

**Comment by Uldiniad** [comment]
> Upon several trials the build somehow continued but again stopped. Reliability is a major concern.
> Just wanted to know if WSL can be used to build AOSP Source code ?

https://forum.xda-developers.com/android/software-hacking/guide-how-to-build-lineageos-15-1-t3750175/
not without patches

**Comment by sanchosachu** [comment]
Any idea how to solve this error in linux?.... Am getting the same type error in linux at the end of the build

**Comment by soroshsabz** [comment]
I have same issue on

```
adevtool generate-all -d shiba
```

my errors is

```
15:29:41 Could not create module-finder: finder encountered 2 errors: [/mnt/s/graphenos-16/vendor/adevtool/dl/unpacked/shiba-BP2A.250805.005-tmp/product: lstat /mnt/s/graphenos-16/vendor/adevtool/dl/unpacked/shiba-BP2A.250805.005-tmp/product: no such file or directory /mnt/s/graphenos-16/vendor/adevtool/dl/unpacked/shiba-BP3A.250905.014-tmp/product: lstat /mnt/s/graphenos-16/vendor/adevtool/dl/unpacked/shiba-BP3A.250905.014-tmp/product: no such file or directory]
Error: command failed
    at promiseSpawn (/mnt/s/graphenos-16/vendor/adevtool/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
    at /mnt/s/graphenos-16/vendor/adevtool/src/config/paths.ts:91:23
```
