### ISSUE TITLE
WslRegisterDistribution failed with error: 0x800700b7

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/WSL#3828]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.17763.253]
```
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```
C:\wsl\ubuntu> .\ubuntu1804.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800700b7
The distribution installation has become corrupted.
Please select Reset from App Settings or uninstall and reinstall the app.
Error: 0x800700b7 Cannot create a file when that file already exists.
```
* What's wrong / what should be happening instead:
I expect the distro to install and open a bash terminal

* For WSL launch issues, please [collect detailed logs]
[logs.zip](https://github.com/Microsoft/WSL/files/2840456/logs.zip)

----
* Additional Information
  The distro seems to work fine for the first user who logs into the server. The next user trying to use WSL gets this error message.

**Comment by mscraigloewen** [comment]
Hi @dhirschfeld ! 

If you uninstall the app and then try to reinstall it do you get the same error? 
As well, I see you're installing it using the command line approach, have you tried using the Windows Store to install it (if you're able?) 

As far as troubleshooting goes, if uninstalling it and reinstalling it doesn't work I would recommend running this command in an Administrative Powershell window:
`dism /online /cleanup-image /restorehealth`
And then check to see if you have any antivirus that might try and stop the install

And then try and install again.

Let me know if any of those work for you!

**Comment by dhirschfeld** [comment]
> *have you tried using the Windows Store to install*

My usecase is deploying on servers, some being headless so I don't think I can use the App Store. In any case I'm petty sure the App Store is disabled by policy in our organisation so it would be great if the portable version Just Worked.

I tried it twice, both times it works for the first user and then the 2nd user gets the `file when that file already exists` `0x800700b7` error..

From the suggestion in #3305 I already tried:
```
sfc /scannow
dism /online /cleanup-image /restorehealth
```
and 
```
Restart-Service LxssManager
```
with no luck.

**Comment by dhirschfeld** [comment]
I'd like WSL to be available to anyone who uses the server... in the same way that anyone can login and use powershell.

Are you saying there's no way to support that usecase?

When each new user logs in for the first time do they then have to install WSL for themselves before they can use it? ...and then repeat that for every single server in our organisation?

**Comment by benhillis** [comment]
Correct, distributions are per-user.  I agree this isn't ideal for your scenario.

**Comment by dhirschfeld** [comment]
Thanks for the info @benhillis, that is a bit disappointing though :( Given that constraint I'm not sure we can really use it on our servers :/

Is it likely/possible that constraint will be removed in future?

I'd also suggest that that constraint be documented in the server installation guide:
https://docs.microsoft.com/en-us/windows/wsl/install-on-server

If the distribution *is* necessarily per-user then it seems a bit of an anti-pattern to install it into `C:\Distros\Ubuntu` as documented there, rather than into the users home directory?

**Comment by benhillis** [comment]
@dhirschfeld - The way the distributions are registered (especially on server) is something that could potentially change in the future, but nothing planned in the short term.  From a Windows perspective each WSL distribution is owned by the user that registered the distribution.

**Comment by dhirschfeld** [comment]
I'll close this as resolved then.

...though I hope a multi-user install is considered in future.

**Comment by debinz** [comment]
@dhirschfeld @benhillis I encounter the same error because I have changed my windows user-name, can I get the ubuntu back without reinstalling it?

**Comment by EvModder** [comment]
Same; unable to access after username change, I would really like it if I could save my Ubuntu setup :(

**Comment by hans-bit** [comment]
> Same; unable to access after username change, I would really like it if I could save my Ubuntu setup :(
I have the same problem as you. It seems like I can only reload

**Comment by hans-bit** [comment]
> Same; unable to access after username change, I would really like it if I could save my Ubuntu setup :(

I have the same problem as you. It seems like I can only reload

**Comment by hans-bit** [comment]
> Same; unable to access after username change, I would really like it if I could save my Ubuntu setup :(

I have the same problem as you in Aug 1 2021. It seems like I can only reset...

**Comment by hans-bit** [comment]
> Same; unable to access after username change, I would really like it if I could save my Ubuntu setup :(

I have the same problem as you. It seems like I can only reinstall.
