### ISSUE TITLE
Cant create user in new WSL installation

### ISSUE THREAD

**Issue by nickvanwegen** [Microsoft/WSL#3830]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
![image](https://user-images.githubusercontent.com/47427309/52428799-02992d00-2b03-11e9-8dc9-6658283da071.png)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I have installed WSL on a fresh installation of windows. I can download ubuntu from the windows store just fine. after opening the app it will prompt the install message and after it will ask me to create a user for the new installation.
* What's wrong / what should be happening instead:
The following error occurs when trying to make a new user. 
groupadd: /etc/group.5: lock file already used
groupadd: cannot lock /etc/group; try again later.
adduser: `/usr/sbin/groupadd -g 1000 nick' returned error code 10. Exiting.
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Could you please assist in this matter since i highly prefer working with WSL over installing a VM on my machine.
See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by mscraigloewen** [comment]
Hello @nickvanwegen !
We'll start taking a look into what might cause this issue.

In the meantime, have you been able to uninstall the Ubuntu app, redownload it and try to reinstall it? Do you get the same error?

**Comment by nickvanwegen** [comment]
Hi @mscraigloewen 
So I have been trying to solve it for a while but now suddenly it works. 
The last thing I did where the following steps. 
1. uninstall ubuntu(and all other distro's)
2. remove WSL from windows via control panel.
3. Reboot the system. 
4. Enable WSL again
5. Reboot the system
6. install unbuntu via the windows store
7. Reboot the system
8. Run ubuntu as admin to trigger the install. 

at first when I entered the username it gave me a diffrent message "Acces denied" (which is wierd since I won the folder with will control). Anway I gave up and closed my laptop :)....After a while I wanted to try again and then it worked. 

What caused the issue I have no idea..

**Comment by mscraigloewen** [comment]
Okay great! Well the infamous turn it of and turn it back on again system seems to have helped :) 

I'll close out the issue since it has been resolved, and we'll check internally on what could have caused it. 

Thanks for letting us know!
