### ISSUE TITLE
/proc/filesystems doesn't reflect WSL

### ISSUE THREAD

**Issue by mqudsi** [microsoft/WSL#3831]
This is perhaps not of very high priority at all, but `/proc/filesystems` should reflect the capabilities of the kernel with regards to what filesystem types may be mounted (e.g. as an argument to `mount -t`).

On my WSL install (as of 17763), `/proc/filesystems` looks like it's been copied wholesale from a Real Linux™ install, in that it both contains values that WSL does not support (pretty much everything in there) and does not contain values that it *does* support (e.g. `drvfs`).

**Comment by mscraigloewen** [comment]
Hello @mqudsi,

You're right there are some fileysstems in `/proc/filesystems` that really shouldn't be there.
We've noted the feedback internally and will take a look into resolving this in future updates.

Thanks for making us aware! 😊
