### ISSUE TITLE
zsh: permission denied: help

### ISSUE THREAD

**Issue by zenis0102** [Microsoft/WSL#3833]
I have installed **Ubuntu-18.04** as for _WSL_ on a x64 based Windows 10 and typing all following commands in bash gives me **`zsh: permission denied: help`**
1.  `help`
     `zsh: permission denied: help`
2. `help export`
     `zsh: permission denied: help`
3. `help sed`
     `zsh: permission denied: help`

I'm new to Linux system and just trying to get some help info about `export` command as I found out that it is a `builtins` command so there is no man page for it in my system.

I'll appreciate any help.

**Comment by mscraigloewen** [comment]
Hi @zenis0102 , 

If you want some help info for different commands I would recommend typing in the commands like this:
`sed --help`
`export --help`

And if you'd like to view some more detailed pages you can always view the manual pages of some applications with 
`man sed`

Does that help answer your question?

**Comment by therealkenc** [comment]
>> trying to get some help info about `export` command

> I would recommend typing in the commands like this commands like
> `export --help`

`export` is a shell builtin (ie, there is no `/usr/bin/export`). Thus there is no man page, and no `export --help` on `zsh`. The relevant page of the `zsh` manual is [here](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html). 

The `permission denied` error made me curious though. An `EACCES` doesn't make sense. The expected error is: `zsh: command not found: help`, because unlike `bash`, `zsh` doesn't have a `help` builtin. Turns out:
```
532   execve("/mnt/c/WINDOWS/system32/config/systemprofile/.dnx/bin/help", ["help"], 0x7fffdecc3c40 /* 21 vars */) = -1 EACCES (Permission denied)
532   access("/mnt/c/WINDOWS/system32/config/systemprofile/.dnx/bin", X_OK) = -1 EACCES (Permission denied)
```
Which has the fun repro:
```
$ ls -l /mnt/c/WINDOWS/system32/config/systemprofile/.dnx/bin/help
ls: cannot access '/mnt/c/WINDOWS/system32/config/systemprofile/.dnx/bin/help': Permission denied
```
Which is probably dupe #2779, though that's as far as the motivational curiosity took me.

**Comment by zenis0102** [comment]
thank you both **@mscraigloewen** and **@therealkenc** for any recommendation.

First of all, I'm sorry that I made a small but misleading mistake here:

> typing all following commands in _**bash**_

actually I have edited `.bashrc` file to start **zsh** for WSL shell and I typed all those commands in **zsh** shell and NOT the **bash** although I thought it was obvious from the shell-outputs in my post.

---

as to

> I would recommend typing in the commands like this
> 
> `export --help`

which **@therealkenc** clarified it too there is no `export --help` command in `zsh`. Following outputs may explain it more clearly.

here is the result in `zsh` :

```bash
$ export --help
export: bad option: -e
```

and I don't know where the `option: -e` has come from!
and in `fish` :

```bash
$ export --help
/usr/share/fish/functions/export.fish (line 9): $- is not a valid variable in fish.
                set -gx $v $$v
                            ^
in function 'export'
        called on standard input
        with parameter list '--help'
```

and finally for the good old `bash` :

```bash
$ export --help
export: export [-fn] [name[=value] ...] or export -p
    Set export attribute for shell variables.

    Marks each NAME for automatic export to the environment of subsequently
    executed commands.  If VALUE is supplied, assign VALUE before exporting.

    Options:
      -f        refer to shell functions
      -n        remove the export property from each NAME
      -p        display a list of all exported variables and functions

    An argument of `--' disables further option processing.

    Exit Status:
    Returns success unless an invalid option is given or NAME is invalid.
```

and this latter one was the very info I was expecting for `export --help` for which I had to reset `.bashrc` not to load `zsh` shell but the `bash` itself. Now I understand that neither `zsh` nor `fish` shell have the `export --help` command and I can ONLY use this inside the `bash` shell_.

thanks again for the good replies.

**Comment by therealkenc** [comment]
> Now I understand that neither `zsh` nor `fish` shell has the `export` command and I can ONLY use it inside the `bash` shell because `export` is a **builtin** command of the `bash`

Export is a builtin in `zsh` just like `bash`. Per the [link](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) I sent previously. It is the builtin documented after `exit` and before `false`.

```
$ export --help
export: bad option: -e
```

You passed argument `--h` to `zsh`'s `export` builtin which takes no `e` option.

Contrast "`export PATH=$PATH:/home/ken/mybinaries`" which will behave as expected in `zsh`/`fish`/`dash`, same as `bash`.

[But not [`csh`](https://en.wikipedia.org/wiki/C_shell) or `tcsh` which uses the builtin `setenv` because Bill Joy.]

**Comment by zenis0102** [comment]
> Export is a builtin in `zsh` just like `bash`. Per the [link](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) I sent previously. It is the builtin documented after `exit` and before `false`.

I just overlooked that part of `zsh` documentation, sorry about that and a big thank you **@therealkenc** for correcting my mistake and providing really helpful and extensive info. I will edit my previous comment to add the correct information.

**Comment by cerealXDD** [comment]
This is not working. ```help history``` does not work.

**Comment by jdknox** [comment]
To answer your question more directly, `zsh` apparently uses `run-help` instead of `help`.  So you can possibly:
`alias help=run-help`, which works for me in WSL2.  Although somewhat lacking compared to bash's `help export`...

More info here: https://superuser.com/a/1563859/741067
