### ISSUE TITLE
Unable to access http server from networked computers

### ISSUE THREAD

**Issue by alshdavid** [Microsoft/WSL#3834]
from administrator CMD

```
bash
sudo npx http-server
```

From the host machine (Windows) I am able to visit the page fine via both localhost and my machine's IP.
If I try to access the http server from another computer on the same network, I am unable to find it.

To ensure that it wasn't my network configuration, when I run `npx http-server` from Windows CMD, it's accessible without issue.

I have updated my firewall settings to allow all inbound and outbound connections for the program `%SystemRoot%\System32\bash.exe` to `Allow`

**Comment by 0xbadfca11** [comment]
Network I/O does not through via bash.exe. Allowing rules must be given to Linux programs. Or port based rules.
> netsh.exe advfirewall firewall add rule name=wsl_python dir=in action=allow program="C:\users\<username>\appdata\local\packages\canonicalgrouplimited.ubuntuonwindows_79rhkp1fndgsc\localstate\rootfs\usr\bin\python2.7" enable=yes
> https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17627-skip-ahead

**Comment by DemoorBug** [comment]
> 网络I / O不通过bash.exe。必须为Linux程序提供规则。或基于端口的规则。
> 
> > netsh.exe advfirewall防火墙添加规则名称= wsl_python dir = in action = allow program =“C：\ users <username> \ appdata \ local \ packages \ canonicalgrouplimited.ubuntuonwindows_79rhkp1fndgsc \ localstate \ rootfs \ usr \ bin \ python2.7”enable =是
> > https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17627-skip-ahead

According to your answer did not solve, I closed the windows firewall, the problem was solved, but this is not a way

**Comment by DemoorBug** [comment]
> Network I/O does not through via bash.exe. Allowing rules must be given to Linux programs. Or port based rules.
> 
> > netsh.exe advfirewall firewall add rule name=wsl_python dir=in action=allow program="C:\users<username>\appdata\local\packages\canonicalgrouplimited.ubuntuonwindows_79rhkp1fndgsc\localstate\rootfs\usr\bin\python2.7" enable=yes
> > https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17627-skip-ahead

According to your answer did not solve, I closed the windows firewall, the problem was solved, but this is not a way

**Comment by DemoorBug** [comment]
If the problem is solved, please let me know, thank you.

**Comment by therealkenc** [comment]
> According to your answer did not solve, I closed the windows firewall, the problem was solved, but this is not a way

Unfortunately not WSL actionable and there don't seem to be takers on the firewall question. Might get a community driven answer where Windows firewall folks hangout (serverfault maybe). Bonne chance.
