### ISSUE TITLE
Drawbridge PAL on WSL

### ISSUE THREAD

**Issue by woachk** [microsoft/WSL#3835]
* Windows build number: 17763.292 (lxcore.sys: 17763.253)

* What you're doing and what's happening:  Trying to run SQL Server on Linux. (and other apps over there too :-) )

* What's wrong / what should be happening instead: The Drawbridge PAL requires AIO to be usable.

https://pastebin.ubuntu.com/p/YnpJxpptGt/ is an attached debug log that showcases the issue.

Drawbridge PAL version: Commit 6c2a6b3
Drawbridge LibOS version: 14388.2/10.0.15063.907.

**Comment by woachk** [comment]
@mscraigloewen

**Comment by mscraigloewen** [comment]
Hi @woachk ! 

I'm taking a look into this issue. I've also seen the context from Twitter! Thanks for reaching out, I'll give you any updates as they become available.
