### ISSUE TITLE
CONTRIBUTING.md content in not in sync with MS WSL Troubleshooting doc

### ISSUE THREAD

**Issue by LeslieGerman** [Microsoft/WSL#3842]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
N/A

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

See next point.

* What's wrong / what should be happening instead:

The "8) Detailed Logs" section on page https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs  is not in sync with https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code

`CONTRIBUTING.md` mentions only 3 log files:
```
lxcore_kernel.etl
lxcore_service.etl
lxcore_user.etl
```
However the script on the Troubleshooting page creates 4 log files:
```
lxcore_kernel.etl
lxcore_service.etl
lxcore_user.etl
lxcore_adss.etl
```
All 4 are expected to be mentioned on the `CONTRIBUTING.md` page.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
N/A

**Comment by benhillis** [comment]
OMG thank you! I've been wondering where the instructions that created the old lxcore_adss.etl file were.  I will get this updated.

**Comment by benhillis** [comment]
Fixed, thanks again.
