### ISSUE TITLE
Kali Linux Config --default-user root Doesn't Work

### ISSUE THREAD

**Issue by haselton** [Microsoft/WSL#3843]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.523]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1. Open an elevated command prompt
2. Type `kali --default-user root`
3. Type `kali` to start instance

* What's wrong / what should be happening instead:
Instance should start with `root` as the default user but the instance starts with the original default user.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
NA

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
See attached
[wsllaunchlogs.zip](https://github.com/Microsoft/WSL/files/2856444/wsllaunchlogs.zip)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Thanks for filing.  We (Microsoft) do not own kali's app, so it would probably be best to follow up with them: https://www.kali.org/tutorials/kali-on-the-windows-subsystem-for-linux/

**Comment by haselton** [comment]
FYI, I went back through various blog posts and found this:  
[Kali Linux for WSL](https://blogs.msdn.microsoft.com/commandline/2018/03/05/kali-linux-for-wsl/)

From the above:

> Hope you enjoy using Kali Linux on WSL!
> Let us know how you use Kali Linux with WSL by submitting issues on our [GitHub repo](https://github.com/Microsoft/WSL) and Tweeting us at #WSL - @kalilinux, @muts, @tara_msft, and @virtualscooley.

The GitHub link above is to this repo.

**Comment by benhillis** [comment]
@haselton - I would suggest tweeting that Kali folks, unfortunately this is not actionable by us.

**Comment by haselton** [comment]
Done.
FYI, I figured out the problem; after running `kali config --default-user username` you have to restart the `LxssManager `service to commit the change.  I'll submit an update request for the docs.
