### ISSUE TITLE
Nvidia-Smi

### ISSUE THREAD

**Issue by Hamahmi** [Microsoft/WSL#3847]
#### Ubuntu app WSL: 
From the *Graphics settings* I added Ubuntu to use the High performance GPU NVIDIA GeForce 930MX
and still when using nvidia-smi I get : 
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. 
```

I installed and reinstalled nvidia drivers for different versions and still have the same problem.

**Comment by mscraigloewen** [comment]
Hello @Hamahmi ! 

Unfortunately as of right now WSL isn't able to access the GPU. So I don't believe you will be able to use NVIDIA-SMI. 

This is our [Number 1 request on Uservoice!](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support) So we are certainly taking this issue seriously and are looking into ways to resolve it.

**Comment by Hamahmi** [comment]
Thanks, and great work you guys :D

**Comment by therealkenc** [comment]
#829

**Comment by mscraigloewen** [comment]
@Hamahmi we're very glad that you're enjoying WSL! 😊

**Comment by elnazsn1988** [comment]
Has this been resolved? Trying to use pytorch - with GPU access on WSL, no luck so far...

**Comment by Hamahmi** [comment]
@elnazsn1988  no, not yet.

**Comment by franva** [comment]
how about now?

I updated my Windows 10 to May 2020 version, installed WSL 2.

I saw on Microsoft Build conference, the WSL 2 supports GPU which enables us to do DS works.

**Comment by y0d4a** [comment]
and what is status now?
i have same issue, cannot set cuda to work on wsl..

**Comment by onomatopellan** [comment]
The status now is that NVIDIA drivers are in preview and they have some limitations with CUDA.
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations

If Nvidi-Smi uses NVML API then it won't work yet.

**Comment by sebastianfast** [comment]
This guide describes the use of nvidia-docker2 instead of Windows Docker Desktop with WSL 2 support.

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by ishankumarkaler** [comment]
```
cp /usr/lib/wsl/lib/nvidia-smi /usr/bin/nvidia-smi
chmod ogu+x /usr/bin/nvidia-smi
```
Source: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations

**Comment by benhillis** [comment]
Fixed in 21354.

**Comment by franva** [comment]
> 
> 
> Fixed in 21354.

Could you please provide a link?

Cannot see anything, so may I assume that WSL2 now fully supports CUDA and everything is working?

**Comment by benhillis** [comment]
@franva - I meant specifically the chmod workaround that @ishankumarkaler pointed out - no longer needed with 21354.
