### ISSUE TITLE
tmpfs implementation

### ISSUE THREAD

**Issue by nonyy** [Microsoft/WSL#3848]
Is it ready to use? Or is it just a block on disk?

**Comment by therealkenc** [comment]
The latter. `tmpfs` is persistent on WSL.

**Comment by nonyy** [comment]
@therealkenc any recommended workaround? I found a few opensource solutions that mount a disk.

Also ETA on implementing this?

**Comment by therealkenc** [comment]
> any recommended workaround?

No. The performance bottleneck is not your ssd.

> Also ETA on implementing this?

I gather it is on their [backlog](https://www.reddit.com/r/bashonubuntuonwindows/comments/69zez8/does_tmpfs_really_work/).

**Comment by koyae** [comment]
Any update here? A [comment over on Stackoverflow](https://stackoverflow.com/questions/64401190/can-i-use-docker-tmpfs-in-wsl2-for-running-docker-containers-on-ram#comment130738069_64838516) indicates tmpfs may have been implemented for real in WSL2 as of 2022, but this I'm looking for an official source to confirm that.
