### ISSUE TITLE
ESC doesn't respond in gvim under WSL

### ISSUE THREAD

**Issue by eyeloveu** [Microsoft/WSL#3849]
I installed WSL today with the Ubuntu 18.04 version. After that, I was trying to run GUI applications via X-Server, and it worked. But when I run gvim, ESC doesn't respond and stuck in insert mode. I have searched a lot and tried a lot, but nothing worked. What's wrong with it?

**Comment by lewisdonofrio** [comment]
does it work when you install full xfce4 gui like - http://www.tinyurl.com/donofrioworkdesk I tried and am wondering what virtual package did you install?

**SNIPPED**
donofrio@localhost:~$ sudo apt-get install gvim -y
[sudo] password for donofrio: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gvim is a virtual package provided by:
  vim-gtk 2:8.0.1453-1ubuntu1
  vim-athena 2:8.0.1453-1ubuntu1
  vim-gtk3 2:8.0.1453-1ubuntu1
You should explicitly select one to install.

E: Package 'gvim' has no installation candidate
donofrio@localhost:~$

**Comment by eyeloveu** [comment]
@lewisdonofrio I didn't install the full desktop. I will try this later.

**Comment by eyeloveu** [comment]
@lewisdonofrio After full xfce4 installed, gvim (vim-gtk3) worked for me! Thanks!

**Comment by therealkenc** [comment]
Close on not-actionable works for sure, but just so it is on the search engine books: running `xfec4` (or any other X window manager) has zero/nada/bupkis to do with whether `ESC` (insert mode) in works in vim-gtk3. Great that the OP got this working. It just has nothing to do with `xfce4` (or `compiz`, or `fvwm`, or `twm`). `vim.gtk3 -g` works fine with the WM built into VcXsrv, and every other window manager, or the entire gtk3 ecosystem would implode. One has nothing to do with the other.
