### ISSUE TITLE
Remote Post Build Event only runs once

### ISSUE THREAD

**Issue by JrIndie** [Microsoft/WSL#3850]
Not sure if this is intentional, but my normal cmake visual studio projects will always run my post build events(even if there is nothing new to compile).

**Comment by JrIndie** [comment]
Hello.

Step 1:
Right Click Project -> Properties -> Build Events -> Remote Post-Build Event -> Command Line: echo hi1;echo hi2

Step 2:
Right Click Project -> Build

Output:
hi1
hi2

Step 3:
Right Click Project -> Build

Output:
Nothing

**Comment by JrIndie** [comment]
Any updates on when this could get fixed?  Or if it is working for you, then I will give more information on my windows/versions.

**Comment by JrIndie** [comment]
Attached are my test projects for you to test with.

**Note**: Inside TestLinuxApp you will have to change:
C/C++: Additional Include Directories
Linker: Additional Library Directories

To fit your needs.
[TestProjects.zip](https://github.com/Microsoft/WSL/files/2873175/TestProjects.zip)

**Comment by therealkenc** [comment]
No CLI repro, strace, or anything to identify a WSL diverge vs. Real Linux on this one. WSL has no idea whether your project is using static or dynamic libraries. There is a VSLinux github over [here](https://github.com/Microsoft/VSLinux/issues). They might, or might not, be able to help. Smart play would be to reproduce your issue in a Linux VM before posting tho.
