### ISSUE TITLE
CPU usage is reported incorrectly

### ISSUE THREAD

**Issue by mqudsi** [microsoft/WSL#3851]
_Environment is Windows 10 17763.316 x64_

I'm running into a situation with running some high CPU processes under WSL results in the Task Manager under the "Performance" tab the net utilization of the CPU showing correctly, but the individual processes in the "Details" view do not reflect the correct values.

However, the odd thing is that WSL itself is correctly aware of how much CPU its processes are consuming..

Here's a screenshot showing what I see:

![image](https://user-images.githubusercontent.com/606923/52835574-9db67780-30ac-11e9-9d76-9bcb9b6f7c94.png)

![image](https://user-images.githubusercontent.com/606923/52835602-b7f05580-30ac-11e9-8eb7-261993a9e022.png)

which are both correct, as compared to

![image](https://user-images.githubusercontent.com/606923/52835613-c3dc1780-30ac-11e9-8365-7114fb8bd320.png)

which is wrong. (The values don't change, they're each at 3% each.)

**Comment by therealkenc** [comment]
#2814

**Comment by mqudsi** [comment]
@therealkenc if you don't mind, it's not the same at all.

That one is about the load average (cpu usage over past n seconds) as viewed from within WSL being incorrect. Here I'm saying WSL is correct but the WIN32 subsystem has the wrong info being proxied to it by the lxss interface.

**Comment by therealkenc** [comment]
Alright. I was not able to repro however doing a quick `make -j8` in a project that was handy (CPU details were as expected in task manager).

**Comment by mqudsi** [comment]
Thanks. Yeah, it normally works fine for me as well. I'm waiting for this job to finish and then I'll experiment with it a bit.

**Comment by dmex** [comment]
@mqudsi 

> which is wrong. (The values don't change, they're each at 3% each.)

The values shown by Task Manager are correct because it calculcates process utilization (usage / total cores) while htop is calculcating process utilization (usage / single core).

If you add up the individual usage of the ffmpg processes showing 3% it will total about 50% usage and will be the same total usage shown for the CPU on performance tab.
