### ISSUE TITLE
WSL Containerisation

### ISSUE THREAD

**Issue by xOrMalware** [Microsoft/WSL#3852]
The question that springs to mind, is what is the security between the subsystem and host windows system? Is WSL being considered as VM, and thus, their should not be any leaks of data between host and subsystem - and their is no concept of breakout or "break in" for that matter.

Maybe I am thinking too deeply and comparing the system to a VM, but in my eyes, there needs to be sometype of subsystem security to prevent leaks of data. Hypothetical example, you have RDP enabled on the host windows. You are hacked, by a questionable sort. If the person is not able to log in to the Linux subsystem are there protections/mitigations in place to prevent memory reads, disk reads etc.
The only reason I ask, is that I am going to look at a breakout scenario for a VM - and my mind wondered on to what WSL has to offer in this area.

**Comment by benhillis** [comment]
From Window's perspective, WSL processes are just another process (a bit of a simplification).  WSL processes run using the Windows user's permissions, so they are only able to do things that the user has permission to do (delete files etc).

Can you clarify what you mean by a breakout scenario?  Interoperability with Windows, is a core feature of WSL, and is explicitly supported.

**Comment by therealkenc** [comment]
> Is WSL being considered as VM

No. But it is a lot like a container.

> Can you clarify what you mean by a breakout scenario?

This is going to go sideways fast... but the model would be something like having [FreeBSD jails](https://en.wikipedia.org/wiki/FreeBSD_jail) _in Windows_. Back in the day before LXC and Docker, folks used `chroot(1)` to isolate their userspace OS environments (what we call distributions). They were simpler times when no one cared whether chroot A could scribble all over chroot B, or scribble on the path above (what we call Windows). Then, later, it became fashionable to disallow information from leaking between chroots at a finer grain.

These olden tymes (circa pre dot-bomb 1990s) is not unlike the present WSL situation, assuming a rainbow and unicorn world where LxFs and DrvFs were unified and could be used interchangeably. Right now we just say: "You're not allowed in `C:\Local\Packages\CanonicalGroupLimited...`! Don't do that haven't you read the blog post?"

Which is less than ideal if you consider your WSL Ubuntu distro chroot 'A' and your WSL OpenSUSE distro chroot 'B', with your Windows User (`ken`) the superuser that controls the two containers.

> Interoperability with Windows, is a core feature of WSL, and is explicitly supported.

Sure. But you don't have any fine grained control over that interoperability.

For example, right now we have:
```
# ls /mnt/c/Users/there/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs
ls: cannot open directory 'rootfs': Permission denied
```

Which is a good enough hack for now, as it goes. Lunch room conversation might be: what would formalizing that 'Permission denied' look like?

**Comment by ziggythehamster** [comment]
WSL is literally running Linux processes on Windows. There's no virtualization. Also, Linux processes show up in task manager. Because they're just processes as far as Windows is concerned.

Lots of things come back as permission denied because they're unsupported in some way or are inaccessible by your user in Windows. If you want to lock something down, do it in Windows and it will apply to WSL.
