### ISSUE TITLE
wsl "echo $PATH" != run wsl and then "echo $PATH"

### ISSUE THREAD

**Issue by jeansordes** [Microsoft/WSL#3855]
* Your Windows build number:  `Microsoft Windows [version 10.0.17134.590]`

* What you're doing and what's happening:  `wsl echo $PATH` is different than when I run `wsl`, then do `echo $PATH` in it (In the first case, I get only the Windows PATH parsed in a Linux format `/mnt/c/...`, in the second case I get the Linux PATH followed by the Windows PATH parsed like described right before)

* What's wrong / what should be happening instead: It should be the same output (I think, but maybe it's a feature, I couln't find informations about it on internet)

**Comment by therealkenc** [comment]
Ref #3627

**Comment by jeansordes** [comment]
This #3627 issue was closed without any solutions, else than "weird, it does work on my machine now"

Sorry to say that even if I moved to the "Insider" update, I still have the same problem

**Comment by jeansordes** [comment]
Found the solution and explained what I found in the #3627 issue

**Comment by therealkenc** [comment]
> I'm not "fluent" enough with bash syntax to understand exactly what NVM did to the path with this last 2 lines

Good information thank-you. If nothing else you found the variable (for your case anyway) and your update will serve as a useful search target.https://github.com/Microsoft/WSL/issues/1896#issuecomment-32710132

I suspect (but can't prove) you have actually hit on the short answer to several other issues floating open and unloved like #1896 (and others). It would take a deeper dive to figure out _exactly_ what is going on here. Those two lines aren't mucking `$PATH` alone but based on your description it appears the script(s) those lines call probably do.

**Comment by FilBot3** [comment]
Those script modify the $PATH so that they insert "shims" into your PATH. They then handle the determining of which node/npm command to use. 

Should be similar to: https://github.com/rbenv/rbenv#how-it-works
