### ISSUE TITLE
Cannot open any wsl paths in neither explorer.exe nor PowerShell

### ISSUE THREAD

**Issue by SeanIanHale** [Microsoft/WSL#3857]
**Windows build number:**
10.0.18334.1 

**What I'm doing at what's happening:**
Upgraded to version 1903 through the Windows Insider Program. Both Debian and Ubuntu were installed prior to the upgrade.
Start Ubuntu or Debian using any one of the commands below:
```
ubuntu
wsl.exe --distribution Ubuntu
debian
wsl.exe --distribution Debian
```

A terminal opens with the respective distribution. I leave these terminals running. To confirm the distros are running I run the following command from within cmd.exe:
```
C:\Users\sean>wsl --list --running
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Debian
```

In either of the Linux terminals I run the command below:
```
explorer.exe .
```
The command immediately returns but nothing else happens. I have also tried specifying other paths in the linux filesystems and get the same result. However, if I run:
```
cd /mnt/c
explorer.exe .
```
...an instance of File Explorer opens to c:\

In PowerShell, I run either of the following commands and get the results shown:
```
PS C:\Users\sean> cd \\wsl$\Ubuntu
cd : Cannot find path '\\wsl$\Ubuntu' because it does not exist.
At line:1 char:1
+ cd \\wsl$\Ubuntu
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\wsl$\Ubuntu:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\sean> cd \\wsl$\Debian
cd : Cannot find path '\\wsl$\Debian' because it does not exist.
At line:1 char:1
+ cd \\wsl$\Debian
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\wsl$\Debian:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

**What's wrong / what should be happening instead:**
When running `explorer .` when in a WSL folder, an instance of File Explorer should appear and be browsing the distribution's filesystem as per this blog article:
https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/
Also per the above blog, calling `cd \\wsl$\<Distro>`, I should get a directory listing.

I also installed SLES-12 after the upgrade to version 1903 and I got the same results as on Ubuntu and Debian.

**Comment by Biswa96** [comment]
That article is for Windows 10 insider build 18836 and above. You've to enable "skip ahead" feature in Settings.

**Comment by SeanIanHale** [comment]
> That feature is for Windows 10 insider build 18836 and above. You've to enable "skip ahead" feature in Settings.

Ok. I had never enabled skip ahead before and it seems I may not have the option at this point. I tried following the instructions in this article but it doesn't seem to have had any affect (including after a restart). Is there some way to get access to skip ahead at this point?

**Comment by 0xbadfca11** [comment]
You'd better wait for the feature to come to the 19H1(1903) branch.

> Please note as of right now these features are available in the insider build 18836, which is a 20H1 branch. They will become available in a 19H1 branch build very soon! Since the features are already available to some users we decided to post the blog content early. :)
> https://twitter.com/craigaloewen/status/1096522531714940928

**Comment by SeanIanHale** [comment]
Ok, thanks for the clarification. I'm now following @craigaloewen on Twitter too. Closing the issue.
