### ISSUE TITLE
Mariadb fails to create database tables with "Input/output error"

### ISSUE THREAD

**Issue by karolyi** [Microsoft/WSL#3860]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.316]

* What you're doing and what's happening: 
I'm trying to install mariadb and/or create a DB table, that fails.

* What's wrong / what should be happening instead:
Upon reinstalling mariadb and running `mysql_install_db`, I get the following error messages:
```
Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
2019-02-18 14:22:16 0 [ERROR] mysqld: Can't sync file '/var/lib/mysql/' to disk (Errcode: 5 "Input/output error")
2019-02-18 14:22:16 0 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 5 "Input/output error")
2019-02-18 14:22:16 0 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
2019-02-18 14:22:16 0 [ERROR] Plugin 'Aria' init function returned error.
2019-02-18 14:22:16 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2019-02-18 14:22:16 6 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
ERROR: 27  Can't sync file './mysql/' to disk (Errcode: 5 "Input/output error")
2019-02-18 14:22:16 0 [ERROR] Aborting


Installation of system tables failed!  Examine the logs in
/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /usr/sbin/mysqld --skip-grant-tables --general-log &

and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /var/lib/mysql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at http://mariadb.org/jira
```

I get the same 'sync' errors when I try to create a table in a freshly created database.

* Strace of the failing command, if applicable:  https://gist.github.com/karolyi/a1ad406cdbae82da6ba403ee892cc6f3

**Comment by therealkenc** [comment]
```
1775  openat(AT_FDCWD, "/var/lib/mysql/aria_log_control", O_RDWR|O_CREAT|O_CLOEXEC, 0660) = 3
1775  openat(AT_FDCWD, "/var/lib/mysql/", O_RDONLY|O_CLOEXEC) = 4
1775  fdatasync(4)                      = -1 EIO (Input/output error)
```
Appreciate the strace log. Possibly (probably?) same as #2652. But in your case the `fdatasync()` is in happening in `/var/lib`, which eliminates a lot of `/mnt/c` related variables. Best to provide baby CLI repro steps for this one to have a fighting chance (note the other one celebrated a birthday).

**Comment by karolyi** [comment]
@therealkenc I meanwhile reseted the ubuntu image and it started working again.

What I did yesterday (since it was broken), is that I played around with bind mounts and getting C: mounted from the fstab, since I got my homedir moved out of the base image (just in case an image upgrade would wipe out my homedir and lots of work in it).

I put the fstab back on the reseted image as well, it still works. I have no idea what on earth caused the error before I reseted the ubuntu image.

Here's my current fstab:
```
LABEL=cloudimg-rootfs   /        ext4   defaults        0 0
C:      /mnt/c  drvfs   metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11 0       0
/mnt/c/Users/Laszlo\040Karolyi/WSL/home/karolyi/ /home/karolyi none bind,rw,uid=1000,gid=1000,umask=22,fmask=11 0   0
```

Again, I have no idea what went south, but after the image reset it seems to work. Maybe metadata changes?

I know this might not provide any help, but I had to get my dev env working, I got work to do.

**Comment by therealkenc** [comment]
Alright, appreciate the follow up muchly. We'll call it need-repro for now and can re-open if someone hits this in a search and figures out some concrete steps to manifest the problem. You're probably onto something here. `fdatasync()` works, as far as it goes. If you did another `strace` you'd see it returning '`0`' now. But there's unfortunately no actionable for now, and anyway #2652 can serve as the holding pattern.

**Comment by karolyi** [comment]
Thanks. Whenever I manage to 'screw up' my WSL Ubuntu again in a reproducible way, I'll let you know through here.

**Comment by starfishpatkhoo** [comment]
I've managed to reproduce this issue with fairly common regularity as well as the fix.

* Windows 10 1709 with the latest updates (as of 2019-05-07)
* Windows Subsystem for Linux with Ubuntu 18.04.2 with the latest updates (as of 2019-05-07)
* LXRunOffline 3.3.3 - https://github.com/DDoSolitary/LxRunOffline

To reproduce this problem:

1. Install Ubuntu 18.04.2 on WSL (default is C:\Ubuntu)
2. Use LxRunOffline and export the WSL instance to image
   LxRunOffline.exe ec -n <instance> -f <instance>.config.xml
   LxRunOffline.exe e -n <instance> -f <instance>.tar.gz
3. Use LXRunOffline to delete the existing WSL instance
   LxRunOffline.exe ui -n <instance>
4. Use LXRunOffline to import WSL image exported in step 2 - can use previous/same or different path
   LxRunOffline.exe i -n <instance> -f <instance>.tar.gz -d <new-path> -c <instance>.config.xml
5. Launch WSL Console and sudo to root
6. apt-get install mariadb-server mariadb-client
7. Install errors
   [ERROR] [MY-012585] [InnoDB] Linux Native AIO interface is not supported on this platform. Please check your OS documentation and install appropriate binary of InnoDB.
   ERROR: 27  Can't sync file './mysql/' to disk (Errcode: 5 "Input/output error")
8. Exit WSL Console
9. Use LXRunOffline to delete the WSL instance
   LxRunOffline.exe ui -n <instance>
10. Use LXRunOffline to import WSL image exported in step 2 - can use previous/same or different path - but this time, force FS version 1
   LxRunOffline.exe i -n <instance> -f <instance>.tar.gz -d <new-path> -c <instance>.config.xml -v 1
11. Launch WSL Console and sudo to root
12. apt-get install mariadb-server mariadb-client
13. Install succeeds, no errors

I think the difference here is that LXRunOffline by default uses file system version 2, but the default install for WSL Ubuntu 18.04 is file system version 1. But basically, to reproduce this problem, just import an image with file system version 2. You can also try to setup mariadb first between step 1 and 2, export the image, then re-import as FS v2 and while the server will run and you can create new databases, you will have problems creating new tables. To make it work properly, be sure to force import as FS v1.

Also, I'm not sure if issue https://github.com/Microsoft/WSL/issues/3631 is related...

**Comment by florent-izypay** [comment]
I can confirm @starfishpatkhoo test case.
Switching back to FS v1 does fix the issue on a Debian Stretch instance (W10 1809 Pro x64).
