### ISSUE TITLE
\\wsl$ not reachable. Name for the Networkservice is invalid

### ISSUE THREAD

**Issue by zackmuc** [microsoft/WSL#3861]
Windows 10 18836.rs_prerelease.190208-1649 (German)

* If i do the following things i get an error nor not the expired result:
  Open installed Ubuntu subsystem and typing "Explorer.exe ." I land in my documents folder
  Opening "\\wsl$" in explorer shows an error that the Network service is invalid

* What's wrong / what should be happening instead: 
![errorwsl](https://user-images.githubusercontent.com/4520343/52955296-93d29400-338c-11e9-97ea-b6b9d8d5bc80.PNG)
I cannot reach the Windows LInux subsystem folders/files

**Comment by benhillis** [comment]
The instance must currently be running in order to see the files. We are working on changing this behavior.

**Comment by zackmuc** [comment]
But it is running, cause i did "explorer.exe ." in bash
![fehler2](https://user-images.githubusercontent.com/4520343/52965376-f041ad80-33a4-11e9-8d9e-b6b8c32e0925.PNG)

**Comment by benhillis** [comment]
Interesting, @SvenGroot will likely want to take a look.

**Comment by zackmuc** [comment]
Sure

**Comment by Biswa96** [comment]
Google translate shows [this](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=Der%20angegebene%20Name%20f%C3%BCr%20einen%20Netzwerkdienstanbieter%20ist%20unzul%C3%A4ssig).

**Comment by benhillis** [comment]
@zackmuc - Are you able to see the contents if you use a full path?  For example:

cmd.exe /c dir \\wsl$\Ubuntu-18.04\

Replace Ubuntu-18.04 with whatever your distro is called

**Comment by zackmuc** [comment]
Does not work .. says .. path not found

**Comment by gojimmypi** [comment]
@benhillis did you really intend only one leading `\` in your suggestion, above?

In any case, none work for me:

![image](https://user-images.githubusercontent.com/13059545/53103760-03f32e00-34e3-11e9-970a-272b4a156fd6.png)

![image](https://user-images.githubusercontent.com/13059545/53103866-34d36300-34e3-11e9-91fc-f4de4a50b7b5.png)

![image](https://user-images.githubusercontent.com/13059545/53103978-63e9d480-34e3-11e9-8628-390b0d1f95d5.png)

**Comment by zackmuc** [comment]
When i click on settings of the Linux folder in Explorer it shows me a link which does not exist in system32 ....
![misingfolder](https://user-images.githubusercontent.com/4520343/53106218-df26a700-3532-11e9-8789-0ced1349b2a9.PNG)

**Comment by Disidente** [comment]
I had the same problem after upgrading to Insider Preview (20/Feb/2019) with Ubuntu 18.04. The solution was to uninstall Ubuntu 18.04 via uninstall (Start->Menu-->Ubuntu 18.04->Uninstall) and re-install Ubuntu (without version) from Microsoft Store.

I think, that is a generalized problem due to permissions in Windows NT, when the distribution files are installed for the first time in NTFS Linux.

**Comment by Biswa96** [comment]
Did Anyone try build 18342?

**Comment by dcronin05** [comment]
> Did Anyone try build 18342?

I am on 18343 and it's still a problem for me. I have not tried the uninstalling solution as I'd rather not spend the time. Easier to just SSH in to the distro if I really need to access something.

**Comment by gbaligh** [comment]
Same problem

> 
> 
> Did Anyone try build 18342?

I'm using the build 18342 too, upgraded from 18334.
And I have the same issue.

**Comment by slewsys** [comment]
Just one more data point:  [Disidente's suggestion
](https://github.com/Microsoft/WSL/issues/3861#issuecomment-466474294) worked for me.

Started with a vanilla Windows Pro 1809 (OS Build 17763.348).  Installing unversioned Ubuntu from Windows Store did not work.  But after upgrading to 1903 (OS Build 18353.1), it did.  Just for fun, I uninstalled Ubuntu and reinstalled Ubuntu 18.04 without incident.

IPv4 and DNS are statically assigned, IPv6 disabled.  One problem does persist: Docker Desktop needs to be restarted after sign in to be reachable.  In Event Viewer, there is DistributedCOM Event ID 10016, but no idea if that's related.  Network interface wsl$ now seems stable.  Thank you!

![wslpath in explorer](https://user-images.githubusercontent.com/418762/54065885-bc0b2100-41db-11e9-8c32-622f056b5ea1.jpg)

**Comment by t3kk** [comment]
I had this problem as well.  I resolved it by removing the wsl feature from windows, restarting, and adding it again.

**Comment by zackmuc** [comment]
> I had this problem as well. I resolved it by removing the wsl feature from windows, restarting, and adding it again.

Thx that worked for me too. I only don't have the linux link in the explorer with the pinguine ..

**Comment by zackmuc** [comment]
> @zackmuc - Are you able to see the contents if you use a full path? For example:
> 
> cmd.exe /c dir \wsl$\Ubuntu-18.04\
> 
> Replace Ubuntu-18.04 with whatever your distro is called

must be **cmd.exe /c dir \\wsl$\Ubuntu**

**Comment by LuKePicci** [comment]
I'm on 18356.16, distro is "Ubuntu", dir `\\wsl$\Ubuntu` works, but `explorer.exe .` opens my documents library, In short, I an actually access WSL files from Windows, but not from Explorer

**Comment by gojimmypi** [comment]
@LuKePicci you actually could, but **should NOT access WSL files from Windows** (Explorer or any other app). See:

https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/

fwiw my WSL files are found in:

``
C:\Users\gojimmypi\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\gojimmypi\
``

**Comment by woachk** [comment]
@LuKePicci You can mount \\wsl$\ubuntu as a network drive, to make it work in cmd too.

**Comment by hd321kbps** [comment]
Also, \\ wsl $ \ Ubuntu and explorer.exe does not work. Even there is no icon in the explorer. I tried to reset did not help

cmd.exe /c dir \\wsl$\Ubuntu It worked

Maybe it's in (The volume in the device \\wsl$\Ubuntu does not have a label)

**Comment by SvenDowideit** [comment]
both 18917.rs_prerelease.190607-1942 (at work) and 18922... something (at home) have this problem
* `cmd.exe /c dir \wsl$\Ubuntu` works
* `explorer.exe .` does not
* `explorer.exe \\wsl$\Ubuntu` does not

the most painful place this exhibits itself, is that using saveas in vscode shows me my windows user's Documents dir

**Comment by SvenDowideit** [comment]
I modified the registry keys mentioned in https://github.com/microsoft/WSL/issues/4027#issuecomment-496628274 and suddenly (presumably for the reasons listed) explorer based access works for me :)

**Comment by boan-jfm** [comment]
> I modified the registry keys mentioned in [#4027 (comment)](https://github.com/microsoft/WSL/issues/4027#issuecomment-496628274) and suddenly (presumably for the reasons listed) explorer based access works for me :)

I had the same issue, thanks :-)

**Comment by DanielSchmied** [comment]
I tried like everything mentioned here and other Blogs / Tips / Websites nothing helped.
For me it suddenly worked as following:
I opened \\wsl$\ in the Explorer (and could not access via Doubleclick)
But then i found in the context Menu (right click) on my Folder Ubuntu-20.04 ("Netzlaufwerk verbinden..." in German, maybe "Connect Network Drive" in English)
I just said "Fertigstellen" (Maybe "Save Settings" in english) and didnt change a thing in the masks (leaving all at the default settings)
And there it was the new Folder in my "Dieser Computer" (This Computer) and it opened up already.

Guys and Gals, i really tried like 10 hours straight to get it to open......
Maybe im helping just one of you.... it would be worth this Comment

Good Luck to all of you

**Comment by DominiqueGarmier** [comment]
I believe I had the same Issue, not sure if it's the same cause, but at least the same symptoms. I supposedly fixed it by disabling and reenabling WSL in windows features (you need to restart twice). Just incase I first exported the WSL image, which wasn't required. Once reenabled the WSL instance was just like I left it with `\\wsl$\istance_name` being accessible again from explorer.

**Comment by LedzZm** [comment]
As @DanielSchmied mentioned. 
I typed \\wsl$ in the windows search and found the menu shortcut.

Single click on it got me inside the network.
Right click -> open file location does not work.
For me, typing \\wsl$ or clicking the "Network" link in the file explorer, both work, but for a colleague with the same setup only the menu shortcut works. (After using the menu shortcut once, my colleague is also able to access it directly via typing \\wsl$ but the Network link still does not work for them).

This seems to be a very bizarre behavior.

**Comment by eizedev** [comment]
> As mentioned in [#4027 (comment)](https://github.com/microsoft/WSL/issues/4027#issuecomment-496628274)

For anyone that comes to this issue using google etc. (like me).  
You could also run this two lines in an powershell window (Start as Admin) to add the missing entry in the registry keys.

```powershell
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order' -Name 'ProviderOrder' -Value 'P9NP,RDPNP,LanmanWorkstation,webclient'
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\NetworkProvider\HWOrder' -Name 'ProviderOrder' -Value 'P9NP,RDPNP,LanmanWorkstation,webclient'
```

After that i could access `\\wsl$\Ubuntu` or just `\\wsl$\`. Maybe a restart may required for you.

**Comment by legistek** [comment]
I'm still having this problem, on Windows Server 2019. @eizedev's fix didn't seem to do anything. 
I'm on an on-prem domain. I wonder if that has anything to do with it?

**Comment by rhacker** [comment]
if anyone has this problem in windows' latest build, `\\wsl$\` has been changed to `\\wsl.localhost\`
