### ISSUE TITLE
USB joystick for Windows Subsystem for Linux? 

### ISSUE THREAD

**Issue by mshong0320** [Microsoft/WSL#3862]
I am using WSL to use ROS for a graduate course, and I need to access a joystick usb driver through WSL. I want to figure out how I can do that. When I plug in the joystick to my computer it doesn't show on /dev/. The joystick uses Windows' xusb22.sys driver, and it's showing that it's connected to Port_#0001.Hub_#0001. How can I access this joystick usb data through WSL?

**Comment by therealkenc** [comment]
> How can I access this joystick usb data through WSL?

Unfortunately for your use-case, WSL doesn't have `/dev/js?` or block/character device support in general (with the exception of `/dev/tttyS?` and some special devices like `/dev/null`). We also don't have `/dev/usb/*` (`libusb`) support yet ref landing zone #412 and this [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/31920928-add-libusb-support-to-wsl). You could (in principle) open a new User Voice for `/dev/js?`, but if it were me I'd upvote `libusb`. Doing that won't get you joystick support before your course completes, but it does help express community interest in improved device support for WSL.
