### ISSUE TITLE
Does 9P file server largely solve slow Windows Network Share access sluggishness?

### ISSUE THREAD

**Issue by rswgnu** [Microsoft/WSL#3864]
Does adding the 9P file server for cross-file access between Linux and Windows, as mentioned in your recent blog posting, largely help resolve the widely reported I/O sluggishness when accessing Windows Network Shares from wsl?  Just listing network shares can take over 100x as long from the LInux side as it does from File Explorer.  This is the main reason we might have to abandon WSL when everything else seems to work pretty well..

Would running Linux under a VM using Samba for Windows file access resolve this issue?

Thanks.

**Comment by lewisdonofrio** [comment]
I do not know why this was added, I've been using WSL for two years and have C: and two network drives mapped using devfs and it's working great, please do not add anything into WSL for newbee's that would slow down IO acess

**Comment by rswgnu** [comment]
> On Feb 19, 2019, at 2:58 PM, Lewis L. Donofrio <notifications@github.com> wrote:
> 
> I do not know why this was added, I've been using WSL for two years and have C: and two network drives mapped using devfs and it's working great, please do not add anything into WSL for newbee's that would slow down IO acess
> 

Umfortunately, you seem to be in the minority with dozens if not hundreds of separate messages detailing extremely slow I/O under WSL, Microsoft acknowledging it, saying it is a hard problem, working on it for years but not yet announcing an solid fix.

Any word from the Microsoft staff working on this.  I would like to continue using WSL with Debian but it is presently excruciatingly slow with remote shares on an i7 laptop from 2018 with 24GB RAM and a fast SSD under Windows 10, something like Oct 2018 release.

**Comment by therealkenc** [comment]
Ran course. I couldn't follow the question enough to add anything constructive.
