### ISSUE TITLE
2 instances of WSL in same machine

### ISSUE THREAD

**Issue by GoncaloRod** [Microsoft/WSL#3866]
I've used Windows subsystem for Linux since it was released and when the new version came out (Windows Store Version) I installed it and now I have 2 different instances of Ubuntu in my computer and now when I want to open the terminal using `bash.exe` it uses the old one instead of the new one. Anyone know how can I at least change it to the new version?

**Comment by benhillis** [comment]
Wslconfig.exe is used to manage your distributions.

**Comment by benhillis** [comment]
Wslconfig.exe is used to manage your distributions.
