### ISSUE TITLE
WSL commands/processes logging to event viewer

### ISSUE THREAD

**Issue by c3101** [Microsoft/WSL#3868]
More of a question than an issue, but can't find any reference....

Is is possible for the WSL to log all user executed processes to the windows logging subsystem, either for shipping to a SIEM, ATA, ATP or similar?

**Comment by lewisdonofrio** [comment]
you'll need to do the syslog to (im_msvistalog) eventlog from https://www.loggly.com/ultimate-guide/centralizing-windows-logs/ or use splunk or some type of central logging system. keep in context I'm just guessing here....

**Comment by mscraigloewen** [comment]
Hi @c3101 ,

I _believe_ you can do this with command line auditing. 

Here is a blog post on [how to set up command line auditing for the Windows Console](https://blogs.msdn.microsoft.com/commandline/2017/07/28/how-to-determine-what-just-ran-on-windows-console/), and you can use the info there to help log process creation and filter down to see what was running in WSL. :)

**Comment by Biswa96** [comment]
Isn't the easiest way to parse the event logs from LxCore. Details here: https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by therealkenc** [comment]
Looks like this got all the answers forthcoming.
