### ISSUE TITLE
A pure linux environment, exclude the environment variable of windows

### ISSUE THREAD

**Issue by CyangYu** [Microsoft/WSL#3874]
How to exclude the environment variable of windows, it sometimes casue some problem.

**Comment by Biswa96** [comment]
Link: https://stackoverflow.com/a/51345880/8928481

**Comment by therealkenc** [comment]
Similar [this](https://www.reddit.com/r/bashonubuntuonwindows/comments/63ytth/can_i_get_wsl_to_ignore_windowss_path_variable/). As of 1809 I gather there is also `appendWindowsPath=false` in `wsl.conf`.
