### ISSUE TITLE
Unable to SSH from PowerShell to WSL Bash.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/WSL#3877]
**Please fill out the below information:**

* Your Windows build number:  10.0.17763.316

* What you're doing and what's happening:  
  * use ssh-keygen in PowerShell to create a key.
  * In bash.exe, paste the pub key into ~/.ssh/authorized_keys
  * In bash.exe configure /etc/ssh/sshd_config to accept connections on port 2200
  * in bash.exe, start the ssh server: `sudo service ssh start`
  * in PowerShell, run `ssh <username>@localhost -p 2200`, accept the host, then you'll see an error:
    ```
    PS C:\WINDOWS\system32> ssh trusktr@localhost -p 2200
    trusktr@localhost: Permission denied (publickey).
    ```

* What's wrong / what should be happening instead:

It should allow me to connect to WSL through SSH, but it isn't obvious why it doesn't work. My understanding is that running the Ubuntu ssh server on a different port than 22 should get out of the way of Windows device discovery. No luck though.

Is there a guide on how to connect to WSL over ssh from PowerShell?

**Comment by trusktr** [comment]
At bottom of the default /etc/ssh/sshd_config I added

```
AllowUsers <username> # replaced with actual username!
ListenAddress 0.0.0.0
Port 2200
AuthorizedKeysFile %h/.ssh/authorized_keys
```

And I still get `Permission denied (publickey).` even from inside bash.exe when trying `ssh 0.0.0.0 -p 2200`

**Comment by NoSubstitute** [comment]
What does your _netstat -l_ show?
I don't get sshd listed there, or anything else for that matter, so it's hard to verify that the port is actually open.

**Comment by NoSubstitute** [comment]
Also, I don't seem to have any syslogs, so I can't check there why it doesn't connect. Do note I am so far trying to connect with l/p and not pubkey.

**Comment by Po-wei** [comment]
WSL's currently doest not support netstat.
Check your private key for Powershell is properly placed in C:User/<user>/.ssh/
I just tried it and I can log in WSL by poweshell.

**Comment by Po-wei** [comment]
I just tried it and I can log in WSL by poweshell.

1. WSL's currently doest not support netstat.
2. Check your **private key** for Powershell is properly placed in **C:\Users\<user>\.ssh\private_key**
   ( I generate the key from WSL and paste it to that directory)
P.S. I used default port 22.

**Comment by therealkenc** [comment]
> Is there a guide on how to connect to WSL over ssh from PowerShell?

Nothing specific, because there isn''t anything especially unique about the scenario. You've covered the caveat of using another port like `2200`, which isn't really a WSL thing either but it is a common gotcha.

There doesn't seem to be any more takers for a troubleshooting walkthrough. WAG you are missing `PasswordAuthentication yes` in `/etc/ssh/sshd_config`. Smarter play is to just get your pubkey setup working from powershell to someplace known, and then use that same key in WSL `~/.ssh/authorized_keys`.

**Comment by ivanferrier** [comment]
If someone else ends up here looking for solutions, here is a tutorial for SSH on WSL 
https://www.illuminiastudios.com/dev-diaries/ssh-on-windows-subsystem-for-linux/
