### ISSUE TITLE
Symlink created with cygwin on a Windows mount is not identified as a symlink from WSL

### ISSUE THREAD

**Issue by rdcoe** [Microsoft/WSL#3878]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

Microsoft Windows [Version 10.0.18343.1]

I'm attempting to create a transparent link to the kubernetes config from both Cygwin and WSL.  In my Windows user directory, I have a directory called .kube/.  I created a symlink to that using Cygwin to the config located in my Windows User home:
**Cygwin**
```Robin@BEASTIE $ ln -s $USERPROFILE/.kube .kube
lrwxrwxrwx  1 Robin None   29 Feb 26 22:52 .kube -> /cygdrive/c/Users/Robin/.kube/
```

I then tried the same thing from Ubuntu Bash, using a local symlink that resolves my Cygwin $home to my WSL $home.  I do this so I can share settings between WSL and cygwin:
**Bash**
```rcoe@BEASTIE:~/cyghome$ ln -s /c/cygwin64/home/Robin cyghome
lrwxrwxrwx 1 rcoe rcoe   22 Feb 10 22:06 cyghome -> /c/cygwin64/home/Robin/
rcoe@BEASTIE:~$ ln -s cyghome/.kube .kube
lrwxrwxrwx 1 rcoe rcoe   13 Feb 26 23:06 .kube -> cyghome/.kube
```

* What's wrong / what should be happening instead:
The symlinked .kube directory in Bash looks like a regular file, instead of a symlink:
```lrwxrwxrwx 1 rcoe rcoe   13 Feb 26 23:06 .kube -> cyghome/.kube
rcoe@BEASTIE:~$ cat .kube
!<symlink>C : \ U s e r s \ R o b i n / . k u b e
```
From Cygwin, the symlink cannot be cat'd:
```Robin@BEASTIE /home/Robin
$ cat .kube
cat: .kube: Is a directory
```
but it can be listed:
```Robin@BEASTIE /home/Robin
$ ll .kube
lrwxrwxrwx 1 Robin None 29 Feb 26 22:52 .kube -> /cygdrive/c/Users/Robin/.kube/
$ ll .kube/
total 8.0K
-rwx------+ 1 Robin None 4.1K Feb 26 09:00 config*
```
whereas from WSL bash, listing fails:
```rcoe@BEASTIE:~$ ll .kube
lrwxrwxrwx 1 rcoe rcoe 13 Feb 26 23:06 .kube -> cyghome/.kube
rcoe@BEASTIE:~$ ll .kube/
ls: cannot access '.kube/': Not a directory
```

Again, to show the cyghome symlink works from WSL to my Cygwin home:
**WSL**
```
rcoe@BEASTIE:~$ la cyghome/
total 40K
drwxrwxrwx 1 rcoe rcoe 4.0K Feb 26 23:02 ./
drwxrwxrwx 1 rcoe rcoe 4.0K Jan 18 04:18 ../
-rwxrwxrwx 1 rcoe rcoe 1.3K Feb 11 20:32 .bash_aliases*
-rw-rw-rw- 1 rcoe rcoe 6.8K Feb 26 22:52 .bash_history
-rwxrwxrwx 1 rcoe rcoe 1.5K Feb 10 20:35 .bash_profile*
-rwxrwxrwx 1 rcoe rcoe 6.0K Feb 10 20:32 .bashrc*
-rwxrwxrwx 1 rcoe rcoe  494 Feb  9 14:39 .gitconfig*
-rwxrwxrwx 1 rcoe rcoe 1.9K Feb 10 20:47 .inputrc*
-rw-rw-rw- 1 rcoe rcoe   54 Feb 26 22:52 .kube
...
```
Note that the .kube listing is not seen by WSL to be a symlink

**Cygwin**
The same listing from Cygwin
```
Robin@BEASTIE /home/Robin
$ la
total 72K
drwxr-xr-x+ 1 Robin        None             0 Feb 26 23:02 ./
drwxrwxrwt+ 1 Robin        None             0 Jan 18 04:18 ../
-rwxrwx---+ 1 Robin        None          1.3K Feb 11 20:32 .bash_aliases*
-rw-------  1 Robin        None          6.8K Feb 26 22:52 .bash_history
-rwxrwx---+ 1 Robin        None          1.5K Feb 10 20:35 .bash_profile*
-rwxr-xr-x  1 Robin        None          6.0K Feb 10 20:32 .bashrc*
-rwxr-xr-x  1 Robin        None           494 Feb  9 14:39 .gitconfig*
-rwxr-xr-x  1 Robin        None          1.9K Feb 10 20:47 .inputrc*
lrwxrwxrwx  1 Robin        None            29 Feb 26 22:52 .kube -> /cygdrive/c/Users/Robin/.kube/
...
```

What I expect to happen is that WSL would follow the Cygwin symlink to my $USERPROFILE/.kube/ directory when I reference the .kube symlink in WSL Bash.

**Comment by PastorGL** [comment]
@rdcoe seemingly your Cygwin env uses 'magic cookie' symlinks that aren't real symlinks, so WSL doesn't know how to handle them because those are just plain files with SYSTEM attribute set. You should enable native symlinks as documented here — http://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks

**Comment by rdcoe** [comment]
Perfect, thanks.  I love learning something new.
