### ISSUE TITLE
`mv` cannot move directory even in Linux file system

### ISSUE THREAD

**Issue by TerrorJack** [microsoft/WSL#3879]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18346.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```
terrorjack@LAPTOP-A0NTIMCN:~$ mkdir foo
terrorjack@LAPTOP-A0NTIMCN:~$ mv foo bar
mv: cannot move 'foo' to a subdirectory of itself, 'bar'
```

* What's wrong / what should be happening instead:

```
terrorjack@b0ad2443b572:~$ mkdir foo
terrorjack@b0ad2443b572:~$ mv foo bar
terrorjack@b0ad2443b572:~$ ls
bar
```

* Strace of the failing command, if applicable:

https://gist.github.com/TerrorJack/6e0489408d9451d09720cf67676e9e24

**Comment by therealkenc** [comment]
```
7669  renameat2(AT_FDCWD, "foo", AT_FDCWD, "bar", RENAME_NOREPLACE) = -1 ENOSYS (Function not implemented)
```

What's your output from `lsb_release -a`, `ldd --version`, and `mv --version`.

**Comment by TerrorJack** [comment]
@therealkenc 
```
terrorjack@LAPTOP-A0NTIMCN:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux buster/sid
Release:        unstable
Codename:       sid
terrorjack@LAPTOP-A0NTIMCN:~$ ldd --version
ldd (Debian GLIBC 2.28-7) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
terrorjack@LAPTOP-A0NTIMCN:~$ mv --version
mv (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Parker, David MacKenzie, and Jim Meyering.
```

**Comment by sassjajc** [comment]
I'm also using Debian buster/sid and I had a similar problem which manifested as:
```
Updating certificates in /etc/ssl/certs...
mv: cannot move '/tmp/ca-certificates.crt.tmp.pGZ0hg' to a subdirectory of itself, 'ca-certificates.crt'
```
I tracked it down to mv from coreutils 8.30-2. They added the renameat glibc function and "prefer renameat2 from glibc over syscall if available." It's likely peripherally related to #37.

Replacing it with mv from coreutils 8.30-1 fixes the problem.
