### ISSUE TITLE
Futex problem when building duckling with haskell

### ISSUE THREAD

**Issue by peidaqi** [Microsoft/WSL#3881]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17763.316
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
1. Clone duckling repo from https://github.com/facebook/duckling
2. Install haskell environment in bash with:
sudo apt install haskell-stack
3. Build duckling with:
stack build

* What's wrong / what should be happening instead:
The build process failed with:
The futex facility returned an unexpecteHUnit-1.5.0.0: configure

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Those repro steps do not work, and the `strace` is entirely applicable (this is a build so the trace would be of the specific failing command in the build). In any case after getting GHC into order I wasn't able to reproduce the `futex facility` fail (made me look). Builds cleanly here. This was on Bionic and 18841. The Win10 version difference might matter -- but best guess, I'm doubting it. Doesn't hurt to try.

![image](https://user-images.githubusercontent.com/7049700/53528244-f23ef700-3a9d-11e9-82ab-31671808cb63.png)

**Comment by peidaqi** [comment]
Hmmm..... my uname -a shows 17763. Which Ubuntu did you install from the Windows Store? I'm using the one without version number, which is supposed to be the latest.

**Comment by benhillis** [comment]
The "kernel" version is tied to your Windows release, not the Ubuntu app.

**Comment by peidaqi** [comment]
Yes I just realized that too. So @therealkenc do you work for Microsoft and have a lately Windows build not yet released for consumer update?

**Comment by benhillis** [comment]
@therealkenc does not work at Microsoft, but he runs various Windows Insider builds.

**Comment by peidaqi** [comment]
Ok in that case, I think the problem is probably fixed in new release of LXSS. I'll just have to wait for the right Windows Update then. Thanks.

**Comment by therealkenc** [comment]
> I think the problem is probably fixed in new release of LXSS

Appears so. Confirmed your problem on 1809 (I needed a new image for unrelated reasons). `futex(2)` is interrupted on signal `SIGVTALRM`, the `restart_syscall(2)` fails with `ETIMEDOUT`, and that's ballgame. Can't dupe ya for lack of an immediately plausible target. Thanks for reporting. `stack init` fails let alone building duckling, so anyone using [The Haskell Tool Stack](https://docs.haskellstack.org/en/stable/README/) will hit this.

**Comment by peidaqi** [comment]
No problem. Thanks for confirming this.

**Comment by Brian-Perkins** [comment]
#3618 fixed in  build [18277](https://github.com/MicrosoftDocs/WSL/releases/tag/18277)
