### ISSUE TITLE
NPEnumResource does not call CoInitialize before creating COM instance

### ISSUE THREAD

**Issue by Biswa96** [Microsoft/WSL#3884]
* Windows build number: Tested in 18841. But all insider build with 9P server may be affected.
* What I did: Just calling `NpOpenEnum()` and `NPEnumResource()` to get all connected distros with 9P server. See [this commit](https://github.com/Biswa96/pnconnect/commit/6316ee75b6b09666d249f7cfdd60751b0a2630c5) where I add `CoInitializeEx()`. If I remove those `NpEnumResource()` shows `CO_E_NOTINITIALIZED` error.
* What's wrong / what should be happening instead: `p9np!ConnectToLxssManagerService` should have `CoInitialize()` function call.

**Comment by Biswa96** [comment]
It has been a week. Any update?

**Comment by benhillis** [comment]
@Biswa96 - It is unclear what you are doing.  Are you invoking methods of dll yourself or are you seeing this error somewhere else?  It is typically the responsibility of the calling application to decide the appropriate COM initialization settings for the thread, not a DLL that happens to use COM under the covers.

**Comment by Biswa96** [comment]
I'm calling [`NPEnumResource()`](https://docs.microsoft.com/en-us/windows/desktop/api/npapi/nf-npapi-npenumresource) from p9np.dll. If it is responsibility for the calling application then docs doesn't mention it.

**Comment by Biswa96** [comment]
>  It is typically the responsibility of the calling application

Accepting this as answer.
