### ISSUE TITLE
Can't start wsl.exe, can't end wslbridge, need to restart PC...

### ISSUE THREAD

**Issue by nephewtom** [microsoft/WSL#3888]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
# ver
Microsoft Windows [Version 10.0.16299.967]
```
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

In fact, I can not say what I was exactly doing as I was doing many things...
Writing a bash script with Emacs, editing logs in vi, tailing log files...
And suddenly every single WSL terminal and Emacs got hung...

So I just killed every `bash` and `bash.exe` processes and processes trees.
But now I can not even start a single `wsl.exe`.

I also noticed that `wslbridged-backend` process is there.
But I can not kill it...

So, the only way to make WSL work is to **restart my computer**...
Not an optimal solution.

* What's wrong / what should be happening instead:

I should be able to start a `wsl.exe` process.
In any case, restarting my PC should not be the solution to fix this.

How can I troubleshoot this if it happens again?

Executed in CMD as Admin:

```
etomort@ES-00002604 C:\Users\etomort
# tasklist.exe | grep bash
bash                         73084 Console                    1      3,236 K
bash                         88520 Console                    1      3,144 K
bash                        281068 Console                    1        364 K
bash                        281624 Console                    1        976 K
bash                        281632 Console                    1        728 K
bash                        281644 Console                    1        648 K

etomort@ES-00002604 C:\Users\etomort
# tasklist.exe | grep wsl
wslbridge-backend            73032 Console                    1        468 K

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 73084
ERROR: The process with PID 73084 could not be terminated.
Reason: Access is denied.

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 88520
ERROR: The process with PID 88520 could not be terminated.
Reason: Access is denied.

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 281068
ERROR: The process with PID 281068 could not be terminated.
Reason: Access is denied.

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 281624
ERROR: The process with PID 281624 could not be terminated.
Reason: Access is denied.

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 281632
ERROR: The process with PID 281632 could not be terminated.
Reason: Access is denied.

etomort@ES-00002604 C:\Users\etomort
# taskkill.exe /f /pid 281644
ERROR: The process with PID 281644 could not be terminated.
Reason: Access is denied.
```

I can even see the processes are still running with ProcessHacker/ProcessExplorer:

![image](https://user-images.githubusercontent.com/2485147/53748806-5bf84000-3ea6-11e9-949d-f5d913dc5644.png)

or TaskManager, but I can NOT terminate them or end each task:

![image](https://user-images.githubusercontent.com/2485147/53748984-b72a3280-3ea6-11e9-891a-3a5de8c97bcc.png)

**Comment by benhillis** [comment]
If it happens again, collecting the traces mentioned in the issue contribution instructions would be helpful.

**Comment by tomasorti** [comment]
> If it happens again, collecting the traces mentioned in the issue contribution instructions would be helpful.

How can I do that if it happens again?

**Comment by tomasorti** [comment]
> > If it happens again, collecting the traces mentioned in the issue contribution instructions would be helpful.
> 
> How can I do that if it happens again?

Ok, I guess you mean this:
https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md

And the part referring to `logman.exe`, because I was unable to run `strace`.

**Comment by benhillis** [comment]
@tomasorti - Correct.

**Comment by tomasorti** [comment]
Ok, it seems I have identified how WSL gets hung.

I tried to remove a file from Emacs dired, I got WSL completely hung.
Before that, I tried to `rm -f` a file on bash and it worked.

I have been using Emacs dired for a while without any problem, so I don't think dired is the reason.
However, I recently started using [OneDrive](https://en.wikipedia.org/wiki/OneDrive) solution provided by my company.
And the files I tried to remove are stored there, which I access them through a symlink.

The files I tried to remove from Emacs are located at `alm9572` directory:

```
etomort@ES-00002604 C:\Users\etomort
$ dir smip\validator\defects\
 Volume in drive C is OSDisk
 Volume Serial Number is 9CE8-C5B2

 Directory of C:\Users\etomort\smip\validator\defects

04-Mar-19  15:02    <DIR>          .
04-Mar-19  15:02    <DIR>          ..
09-Feb-19  17:29    <DIR>          alm7282-connections-pradhec
04-Mar-19  15:02    <SYMLINKD>     alm9572 [C:\Users\etomort\OneDrive - Ericsson AB\alm9572\]
20-Dec-18  19:56    <DIR>          alm9982
11-Dec-18  16:14             4,186 inc000002510121.org
02-Jan-19  11:45    <DIR>          INC000002523937
05-Jan-19  10:38             1,784 INC000002541677.org
24-Jan-19  11:19    <DIR>          INC000002568794
10-Dec-18  18:34            11,995 PBI000008981890.org
10-Dec-18  17:27            11,988 PBI000008981890.xlsx
12-Jan-19  18:12    <DIR>          PBI000008982993
               4 File(s)         29,953 bytes
               8 Dir(s)  248,734,773,248 bytes free
```
which is a SYMLINKD I created with [MKLINK](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink).

My guess is that something goes wrong when Emacs dired is deleting those files and WSL hungs.
The good point is that I have a way to reproduce it.

I attach a zip file with `logman.exe` logs as shown in contribution instructions.
[lxcore.zip](https://github.com/Microsoft/WSL/files/2927733/lxcore.zip)

Let me know if I can provide more troubleshooting or more related information.
