### ISSUE TITLE
File opened by VSCode through `wsl$` doesn't truncate correctly

### ISSUE THREAD

**Issue by studoot** [microsoft/WSL#3891]
* Your Windows build number:  Microsoft Windows [Version 10.0.18342.8]

* What you're doing and what's happening:

I create a file called `test` in my Linux home directory using `touch test` and open it in a Windows buiild of VSCode (Version: 1.31.1, Commit: 1b8e8302e405050205e69b59abb3559592bb9e60) using the (otherwise excellent) 9p server access - the file path from Windows is `\\wsl$\Ubuntu-18.04\home\u404261\test`. VSCode was using just line-feeds as line separators, was using UTF-8 encoding and detected the file as 'Plain Text', all as expected.

I added some text (the characters `@@@@@@@@@@##########`) to the file in VSCode, saved it and ran `cat test` and `wc -c test` from the WSL command-line. The file displayed as expected:

```
u404261@cabbage:~$ cat test
@@@@@#####
u404261@cabbage:~$ wc -c test
11 test
```

I added some more text (on a new line, the word `Hello`) to the file in VSCode, saved it and ran teh same two commands from the WSL command-line. The file displayed as expected:

```
u404261@cabbage:~$ cat test
@@@@@#####
Hello
u404261@cabbage:~$ wc -c test
17 test
```

I then deleted the word `Hello` from the file in VSCode, saved it and ran the two commands again from the WSL command-line. The `cat` command still displayed the word `Hello`:

```
u404261@cabbage:~$ cat test
@@@@@#####
Hello
u404261@cabbage:~$ wc -c test
17 test
```

* What's wrong / what should be happening instead: The final `cat test` should not have displayed the word `Hello` and the final `wc -c test` should have displayed the value `11`.

I tried the same sequence of actions in the following scenarios:

1. With VSCode, but on a different network filesystem (a Synology NAS, both through a UNC path and when mounted with a Windows drive letter)

2. With Notepad, through the `\wsl$\....` path.

In these scenarios, the sequence of actions performed as I expected.

The question is - is it VSCode or WSL doing the wrong thing? I kind of think it's WSL, because a) VSCode does the right thing with other drives (networked or local), and b) the wsl$ access functionality is new.

I couldn't work out what process I ought to try to use `strace` with (is it the `/init` with PID 1? If so, I couldn't `strace` that).

**Comment by therealkenc** [comment]
Was able to reproduce with 18845 and Code 1.29.1. Delete the 'Hello' line, Close code, and re-open Code (all in Windows natch) and the line will still be there. A little playing around adding and deleting characters from a single line appears to indicate the file never shrinks just grows. Which isn't a problem if you are always coding I guess 😉. 

I suppose the way to go at it is use Process Monitor (or similar) and filter on the file, see what's being called on the Windows side (I haven't). Good effort on the `strace` log but this is going to be a black box for us mostly.

**Comment by studoot** [comment]
I've done the Process Monitor thing ([here's the zipped PML file](https://github.com/Microsoft/WSL/files/2937008/VSCode-WSL.zip)), monitoring any path containing "wsl$" when writing a file that should have reduced the size from 14 bytes to 7 (this time I used 'Line 1' as the first line ,'Line 2' as the second, saved the file, then deleted the second line).

VSCode seems to be attempting to truncate the file (there's a line with the 'Operation' field set to `SetEndOfFileInformationFile` and in the 'Detail' field, it shows `EndOfFile: 0`), followed soon after by writing 7 bytes of data to the file.

**Comment by benhillis** [comment]
@SvenGroot is taking a look at this.

**Comment by duncan** [comment]
This appears to be fixed now.

**Comment by studoot** [comment]
Yep - seems to be fixed on build 18894 (Insiders, Fast Ring) here.
