### ISSUE TITLE
Error: 0x80070002 Press any key to continue...

### ISSUE THREAD

**Issue by bitttttten** [microsoft/WSL#3893]
Today it started after I used my terminal inside VSCode and ran `yarn install`.

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/me/.cache/yarn/v4/npm-domhandler-2.1.0-d2646f5e57f6c3bab11cf6cb05d3c0acf7412594/node_modules/domhandler/test/tests.js'".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/path/to/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

And then after opening bash on ubuntu on windows I get the title:

`Error: 0x80070002 Press any key to continue...`

If I attemp to run `lxrun /uninstall /full /y followed by lxrun /y` in cmd, I get:

```
C:\Users\me>lxrun /uninstall /full /y followed by lxrun /y
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Sets the default subsystem user. If the user account does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password
```

```
C:\Users\me>wslconfig /list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```

I can fix it by uninstalling and reinstalling, but this is now the 3rd time it's happened. I don't want to have to reinstall, as then I have to setup all my SSH keys, git config, all over again 😅 

Are there any clues as to why it's failing? I have been trying to look through log files but I am out of my depth. It feels like there is an underlying issue, rather than a fluke coincidence. It must be something I am doing.

**Comment by mscraigloewen** [comment]
Hi @bitttttten !

What version of Windows are you running? (When you open CMD and type in `ver` what does it say?)

For uninstalling and reinstalling a distribution you can use: `wslconfig /u <DistroName>` since lxrun is an older command.

If you're able to get the issue to happen again, could you try and take some detailed logs for us? Instructions can be found [here.](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)

All you'll need to do is enable the logging service, run: `wsl` from Powershell or CMD, hit the error, and then disable the logging service and you can send the logs over to us.

**Comment by bitttttten** [comment]
Hey @mscraigloewen . Thanks for the reply! `Microsoft Windows [Version 10.0.17134.590]` is the version. I have not been at this machine the last few days, but I will follow up if with logs it happens again.

Although I just tried to enable logs and I am getting:

```
C:\Users\bitttttten>logman.exe create trace lxcore_kernel -p "{0CD1C309-0878-4515-83DB-749843B3F5C9}" -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets

Error:
Type mismatch.
Try running this command as an administrator.
```

And my googlefu is apparently not so strong tonight. I tried this is the ubuntu terminal and CMD. Are you familiar with this error? Hopefully I don't get my original issue before fixing these logs haha.

**Comment by mscraigloewen** [comment]
Judging from the error output from the logging command, I just want to double check that you're running CMD (or Powershell) as an adminstrator and then trying to execute the command? I believe that might address the error!

**Comment by therealkenc** [comment]
This issue went stale on without a local repro, and the `lxrun.exe` app has been deprecated in favor of `wsl.exe`. If the problem persists on Windows 20H2 aka 19042, please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), catching the `0x80070002` from `wsl.exe` if it persists.
