### ISSUE TITLE
Can only run bash in WSL as the user who installed it

### ISSUE THREAD

**Issue by nmnuckols** [Microsoft/WSL#3897]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.107]  (Windows Server 2019 v. 1809)

* What you're doing and what's happening:  

I followed the steps found on this page (https://docs.microsoft.com/en-us/windows/wsl/install-on-server) to install WSL.  I don't have access to the Windows Store, so I manually downloaded Ubuntu using this link: https://aka.ms/wsl-ubuntu-1804.  I extracted and installed the Linux distro following the steps in the first article.  These steps were all performed while remoting into the server using a domain admin account.  PowerShell was used to execute all commands and was started using "Run as Administrator".  Installation of the Ubuntu distro was successful and I could run bash.exe using that same admin account without any problems.

* What's wrong / what should be happening instead:

Any other account (admin and non-admin alike) cannot run bash.exe at the command line.  When another account tries, the following message is displayed: "Windows Susystem for Linux has no installed distributions.  Distributions can be installed by visiting the Microsoft Store: https://aka.ms/wslstore".

When I use my admin account to run the "wslconfig /list /all" command, I can see that Ubuntu-18.04 (Default) is listed.  If I run the "wslconfig /s Ubuntu-18.04" command, the issue is not resolved for other users.  If I use any other account to run the "wslconfig /list /all" command, I see the "Windows Susystem for Linux has no installed distributions.  Distributions can be installed by visiting the Microsoft Store: https://aka.ms/wslstore" message.

**Comment by benhillis** [comment]
This is by design.  Due to the permission model of WSL, distributions are per-user.

**Comment by nmnuckols** [comment]
Okay, that's good to know.  Does that mean that a non-admin user can install a distro and run it?  My end goal is to run WSL as a non-admin user.  So it was originally installed as an admin user and then we ran into these issues trying to run bash commands as a less privileged user.

**Comment by benhillis** [comment]
@nmnuckols - Correct. Enabling the optional component will require admin, but a non-admin user can install and use distributions.
