### ISSUE TITLE
ROS Gazebo TurtleBot3 incomplete launch

### ISSUE THREAD

**Issue by rlkamalapurkar** [microsoft/WSL#3900]
**Please fill out the below information:**
* Your Windows build number:  10.0.17763.316
* Linux Flavor: Ubuntu

* What you're doing and what's happening:
1. Installed ros-melodic-desktop-full
2. Installed ros-melodic-turtlebot3, ros-melodic-turtlebot3-simulations, and ros-melodic-turtlebot3-msgs
3. Installed vcXsrv and configured it to not use native opengl, ran `export DISPLAY=localhost:0`
5. Ran `roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch`

* What's wrong / what should be happening instead:
As expected, Gazebo is launched and I can see the TurtleBot model in Gazebo. However, the launch in incomplete. It does not load the `DiffDrive` plugin. The console output is:

```
... logging to /home/rushik/.ros/log/bf20974c-4075-11e9-8c79-00e04c20247f/roslaunch-MAE-RK-GAB329-A-8152.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://MAE-RK-GAB329-A:12149/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [8165]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bf20974c-4075-11e9-8c79-00e04c20247f
process[rosout-1]: started with pid [8176]
started core service [/rosout]
process[gazebo-2]: started with pid [8179]
process[gazebo_gui-3]: started with pid [8186]
process[spawn_urdf-4]: started with pid [8191]
[ INFO] [1551921009.340254200]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1551921009.341176600]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1551921009.377451600]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1551921009.378416900]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
shared memfd open() failed: Function not implemented
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[ INFO] [1551921010.023359300, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1551921010.039723300, 0.030000000]: Physics dynamic reconfigure ready.
[ INFO] [1551921010.591972500, 0.158000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1551921010.592237400, 0.159000000]: Starting Laser Plugin (ns = /)
[ INFO] [1551921010.593722400, 0.159000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[spawn_urdf-4] process has finished cleanly
log file: /home/rushik/.ros/log/bf20974c-4075-11e9-8c79-00e04c20247f/spawn_urdf-4*.log
```

When I run the same exact command on native Ubuntu 18.04 connected to vcXsrv as the remote X server via ssh (using PuTTY), everything works as expected and the console output is:
```
... logging to /home/rushik/.ros/log/14e6ccc8-4076-11e9-904b-d89ef33f674f/roslaunch-MAE-RK-AT324-5-3607.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://MAE-RK-AT324-5:43473/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [3620]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 14e6ccc8-4076-11e9-904b-d89ef33f674f
process[rosout-1]: started with pid [3631]
started core service [/rosout]
process[gazebo-2]: started with pid [3634]
process[gazebo_gui-3]: started with pid [3637]
process[spawn_urdf-4]: started with pid [3648]
[ INFO] [1551921152.499570834]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1551921152.501769731]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1551921152.525723001]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1551921152.527843043]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1551921153.549435196, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1551921153.865368258, 0.196000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1551921153.866988924, 0.196000000]: Starting Laser Plugin (ns = /)
[ INFO] [1551921153.872055781, 0.196000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1551921153.876021825, 0.196000000]: Physics dynamic reconfigure ready.
[ INFO] [1551921153.973998653, 0.196000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1551921153.974116808, 0.196000000]: DiffDrive(ns = //): <rosDebugLevel> = na
[ INFO] [1551921153.975142929, 0.196000000]: DiffDrive(ns = //): <tf_prefix> =
[ INFO] [1551921153.976264592, 0.196000000]: DiffDrive(ns = //): Advertise joint_states
[ INFO] [1551921153.977083348, 0.196000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel
[ INFO] [1551921153.980242914, 0.196000000]: DiffDrive(ns = //): Subscribe to cmd_vel
[ INFO] [1551921153.981079927, 0.196000000]: DiffDrive(ns = //): Advertise odom on odom
[spawn_urdf-4] process has finished cleanly
log file: /home/rushik/.ros/log/14e6ccc8-4076-11e9-904b-d89ef33f674f/spawn_urdf-4*.log
```

Notice the  DiffDrive plugin being launched here, absent in the WSL launch.

Logs are too large to attach here, see https://1drv.ms/f/s!Am-zUqfMZr3wiNYVSEwCknR6vjGw3w

**Comment by therealkenc** [comment]
Looks like dupe #3542 ie #1209.

**Comment by rlkamalapurkar** [comment]
Perhaps, what is weird is that if I try a few times with options like
gui:=False or gui:=FALSE, or just stop and restart the simulation a free
times, the DiffDrive plugin is loaded in WSL and the Gazebo simulation
works fine.

I did not add that to the original report because it is not entirely
reproducible. Sometimes I have to run the roslaunch command with different
gui options upto 10 times to finally get all the plugins to load. Once they
load, despite all the ALSA errors, everything works as expected.

**Comment by sagniknitr** [comment]
@rlkamalapurkar does the latest WSL versions solve your issue?

**Comment by rlkamalapurkar** [comment]
@sagniknitr I can confirm that this issue is solved in WSL 2. Thank you so much! I still see all the ALSA Lib errors, but everything I tested works like it should.

`SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [2100]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to cb7aeebc-b70b-11ea-b839-00155d553ca3
process[rosout-1]: started with pid [2111]
started core service [/rosout]
process[gazebo-2]: started with pid [2117]
process[gazebo_gui-3]: started with pid [2122]
process[spawn_urdf-4]: started with pid [2128]
[ INFO] [1593107188.417787900]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1593107188.418933400]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1593107188.446276300]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1593107188.447721800]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[ INFO] [1593107188.890941300]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1593107188.915227100]: Physics dynamic reconfigure ready.
[ INFO] [1593107189.296321500, 0.216000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1593107189.296397400, 0.216000000]: Starting Laser Plugin (ns = /)
[ INFO] [1593107189.297168700, 0.216000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1593107189.342269800, 0.216000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1593107189.342355300, 0.216000000]: DiffDrive(ns = //): <rosDebugLevel> = na
[ INFO] [1593107189.342794300, 0.216000000]: DiffDrive(ns = //): <tf_prefix> =
[ INFO] [1593107189.343379800, 0.216000000]: DiffDrive(ns = //): Advertise joint_states
[ INFO] [1593107189.343862900, 0.216000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel
[ INFO] [1593107189.345515000, 0.216000000]: DiffDrive(ns = //): Subscribe to cmd_vel
[ INFO] [1593107189.345874400, 0.216000000]: DiffDrive(ns = //): Advertise odom on odom
[spawn_urdf-4] process has finished cleanly
log file: /home/rushik/.ros/log/cb7aeebc-b70b-11ea-b839-00155d553ca3/spawn_urdf-4*.log
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
^X^C[gazebo_gui-3] killing on exit
[gazebo-2] killing on exit
^C^C[gazebo_gui-3] escalating to SIGTERM
[gazebo-2] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
rushik@MAE-RK-GAB329-A:~$ nano ~/.ignition/fuel/config.yaml
rushik@MAE-RK-GAB329-A:~$ nano ~/.ignition/fuel/config.yaml
rushik@MAE-RK-GAB329-A:~$ roslaunch turtlebot3_gazebo turtlebot3_house.launch
... logging to /home/rushik/.ros/log/1064d2ae-b70c-11ea-b7fa-00155d553ca3/roslaunch-MAE-RK-GAB329-A-2509.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://MAE-RK-GAB329-A:41821/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [2522]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1064d2ae-b70c-11ea-b7fa-00155d553ca3
process[rosout-1]: started with pid [2533]
started core service [/rosout]
process[gazebo-2]: started with pid [2539]
process[gazebo_gui-3]: started with pid [2544]
process[spawn_urdf-4]: started with pid [2550]
[ INFO] [1593107303.955650300]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1593107303.956992600]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1593107304.083214400]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1593107304.084419600]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
**ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default**
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[ INFO] [1593107304.408342000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1593107304.426215200]: Physics dynamic reconfigure ready.
[ INFO] [1593107304.825221800, 0.228000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1593107304.825317100, 0.228000000]: Starting Laser Plugin (ns = /)
[ INFO] [1593107304.826122500, 0.228000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1593107304.887755800, 0.228000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1593107304.887848300, 0.228000000]: DiffDrive(ns = //): <rosDebugLevel> = na
[ INFO] [1593107304.888264100, 0.228000000]: DiffDrive(ns = //): <tf_prefix> =
[ INFO] [1593107304.888831100, 0.228000000]: DiffDrive(ns = //): Advertise joint_states
[ INFO] [1593107304.889253000, 0.228000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel
[ INFO] [1593107304.890998200, 0.228000000]: DiffDrive(ns = //): Subscribe to cmd_vel
[ INFO] [1593107304.891362700, 0.228000000]: DiffDrive(ns = //): Advertise odom on odom
[spawn_urdf-4] process has finished cleanly`
