### ISSUE TITLE
Running Ubuntu 18.04 LTS fails with Error: 0x80070003

### ISSUE THREAD

**Issue by GregoryScottBell** [Microsoft/WSL#3901]
**Please fill out the below information:**
* Your Windows build number: 
Microsoft Windows [Version 10.0.17134.590]

* What you're doing and what's happening:  
I have Ubuntu 18.04 LTS installed in the Windows Store. When I try to launch it from the windows store, I just get a console window that says:
```
Error: 0x80070003
Press any key to continue...
```

* What's wrong / what should be happening instead:
I should get a working bash shell.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
[EtlTraces.zip](https://github.com/Microsoft/WSL/files/2939065/EtlTraces.zip)

**Comment by mscraigloewen** [comment]
Hi @GregoryScottBell ,

It seems your issue is a duplicate of #2576 

From the duplicate thread, the recommended solution is to reboot and try again. Could you please try that and let me know if the issue still persists? Thanks!

**Comment by GregoryScottBell** [comment]
This issue has persisted across reboots, reinstalls, and disabling then re-enabling the WSL optional component.

**Comment by GregoryScottBell** [comment]
Is there any additional information I can provide to help diagnose this issue?

**Comment by mscraigloewen** [comment]
I'd recommend opening a Powershell or CMD window with administrator privileges and running this command:
`DISM /Online /Cleanup-Image /CheckHealth`

And then try reinstalling the distro and see if that helps. 

If the error still persists then logs may be helpful to us. Please take a look at section 8 [on this page](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) to see how to provide us with detailed logs.

**Comment by GregoryScottBell** [comment]
That worked! Thanks a bunch.

**Comment by mscraigloewen** [comment]
Glad to heart it! :)
