### ISSUE TITLE
Linux folder is missing

### ISSUE THREAD

**Issue by Erableto** [Microsoft/WSL#3902]
* Your Windows build number:  10.0.18845.1001

* What you're doing and what's happening:  In Build 18836, a Linux folder was added to the Windows Explorer Navigation Pane. However, in the following builds, I lost it.

* What's wrong / what should be happening instead: The Linux folder is missing for me.

**Comment by Biswa96** [comment]
Ya, it's seem to be a known issue. The 19H1 tree also doesn't contain that network folder. I've a workaround. If you have that old 18836 build somewhere (e.g. VM) grab the `Distros.lnk` file.

**Comment by benhillis** [comment]
This feature is still in development, it will come back better than before in a future build.

**Comment by nandorc** [comment]
when? 2025? now we are un build 19044.1387 but I have no WSL folder on navigation pane 🤔
