### ISSUE TITLE
WSL should print an error if distro is missing /etc/passwd and bash

### ISSUE THREAD

**Issue by marler8997** [microsoft/WSL#3903]
This came up when I was trying to get my custom linux distro to run in WSL (https://github.com/Microsoft/WSL-DistroLauncher/issues/57).  I didn't have an `/etc/passwd` file nor bash installed to `/bin/bash`.  However, when I launched wsl with `wsl -d mydistro` it just failed with no error message.  Also when I tried to run `WslLaunchInteractive` it would just return success with an exit code of `-1`.  After adding the `/etc/passwd` file with these contents `root:x:0:0:root:/:/bin/msh` it started working.  Seems like WSL should have given a message saying something like:
```
Error: failed to find '/bin/bash' and no '/etc/passwd' file was found to override the default shell path.
```

Rootfs can be downloaded here: https://github.com/marler8997/maros/releases/tag/ForTest

```
Microsoft Windows [Version 10.0.17763.292]
```

**Comment by benhillis** [comment]
@marler8997 - Yep this is the right place.  When filing issues please make sure to include the requested information in the issue template, especially the version number.  Regarding a missing /etc/passwd file, in later builds, WSL will fall back to root if this file is not present (just verified this on 17763).

**Comment by marler8997** [comment]
Solution seems reasonable.  Thanks for the info.

**Comment by marler8997** [comment]
Wait a second.  I'm on build 17763.292.  I think I have to add one more condition to the error case.  My distro doesn't have bash.  So it looks like if you don't have an `/etc/passwd` file and no bash, then WSL will fail with no error message.

**Comment by marler8997** [comment]
Here's my rootfs that should reproduce this behavior: https://github.com/marler8997/maros/releases/tag/ForTest

**Comment by therealkenc** [comment]
The lack of usable error feedback from `wsl.exe` is most unfortunate to be sure, but if you don't have `/etc/passwd` nor `/bin/sh` that's treading into "by-design fail because prerequisites missing" territory. You probably want `wsl.exe --exec`. The ask for better error feedback is legit enough I guess tho; can't really argue with that.

**Comment by marler8997** [comment]
@therealkenc 

Not to invalidate this issue, but do you have a link that describe the requirements for a distro?  I could not find anything that said `/bin/sh` and/or `/bin/passwd` were required or how WSL uses them.  Having a document that explains how WSL interacts with the rootfs of the distro would be very helpful.  Some type of reference document that says things like:
## Files that matter to WSL
| filename | description |
|-----------|-------------|
| `/etc/passwd` | WSL reads user information from this file such as uid, home directory, default shell, etc.  Refer to https://linux.die.net/man/5/passwd for more details. |
| `/bin/sh` | The default shell that WSL will launch with if the user does not have an entry in `/etc/passwd`. |
| ... | ... |

But again, I also think that when WSL has some sort of failure that would cause it not to be able to launch a shell (i.e. when there's not entry in `/etc/passwd` and the default shell `/bin/sh` doesn't exist) that it should still print an error message.

**Comment by therealkenc** [comment]
> Not to invalidate this issue, but do you have a link that describe the requirements for a distro?

No not me.

> would be very helpful

Less helpful than you'd think, I expect, if one was was actually handed a list of things necessary to bring up a shell. It isn't WSL domain specific knowledge, and strictly speaking, depends on the nature of your shell  (which might depend on all sorts of things, or next to nothing). Ben has removed the requirement for `/etc/passwd`. If WSL `/init` has its own dependencies or makes other unnecessary assumptions hopefully those are picked off as they are pointed out (this has been happening over time).

> it should still print an error message.

Well, yeah.

**Comment by marler8997** [comment]
Yes I was saying that only the WSL specific requirements should be documented. If you take my rootfs and put it on a partition, it will boot up and the init program will launch the shell correctly. The /etc/passwd file is not required. However, it appears that WSL is a bit unique here, it doesn't take the normal Linux boot path of calling '/init'. Instead, it appears to take the UID it is launching the shell for, and tries to find the the shell from the /etc/passwd file. This is WSL specific behavior. Furthermore, now that it will fallback to using /bin/sh if no entry can be found for the requested UID in /etc/passwd is also specific to WSL.

Note that I'm not saying this behavior is wrong, in fact it makes a lot of sense and matches the semantics of /etc/passwd. However, this process that WSL uses to launch a shell should be documented. If I go to any other distro I can see which init program they are using and look at source code or docs to see how they "initialize" shell processes. With WSL I can't do that.

**Comment by benhillis** [comment]
@marler8997 - You should think of WSL's init daemon as a combination between the inti daemon and /bin/login, which does parse the /etc/passwd file.  The /bin/sh requirement is also a hard requirement for Linux c libraries, which will not be functional without the /bin/sh binary (required by calls to the shell command, among others).

**Comment by marler8997** [comment]
> You should think of WSL's init daemon as a combination between the inti daemon and /bin/login, which does parse the /etc/passwd file.

Thanks for the info that's very helpful.  Do you have a link to the specific `/bin/login` project you're referring to?  That sounds like a great thing to document :)

> The /bin/sh requirement is also a hard requirement for Linux c libraries, which will not be functional without the /bin/sh binary (required by calls to the shell function, among others).

My distro doesn't use any C libraries...so...I didn't realize it was missing :)  I just use the system calls.

**Comment by benhillis** [comment]
http://man7.org/linux/man-pages/man1/login.1.html

**Comment by therealkenc** [comment]
> The /bin/sh requirement is also a hard requirement for Linux c libraries

Call this a nit, but it is meant to be a constructive one (contrast pedantic). It is a _soft_ requirement of posix libc. [`system(3)`](http://man7.org/linux/man-pages/man3/system.3.html) (or equivalent) can fail by design. If `system(3)` fails, it is up to the caller what to do about that fail. Which might mean `write(2)`ing an error out `/dev/tty` (and calling `mknod(2)` if  `/dev/tty` is missing). Or writing the error out a socket or some other communication mechanism to a logger on the windows side. Or whatever `/init` fancies, up to including setting the user's printer on fire as an indication of the failure. None of which necessitates `/bin/sh` as a _hard_ requirement.

**Comment by benhillis** [comment]
@therealkenc - Thanks for the clarification, I oversimplified a bit.

**Comment by marler8997** [comment]
> also misspoke saying "shell" instead of "system".

I knew what you meant :)
