### ISSUE TITLE
systemctl failed to connect to bus: no such file or directory

### ISSUE THREAD

**Issue by fceledon** [Microsoft/WSL#3905]
Windows 10. Debian Stretch on WSL, After today's upgrade to Build 18351.18h1 release 190301-1611. 

So, I can't run MySQL :(

**Comment by fceledon** [comment]
use system instead on systemctl

**Comment by puppylpg** [comment]
Thanks bro, it helps me a lot

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/68259220-3b573a00-0074-11ea-9fee-468e4706debe.png)


> Thanks bro, it helps me a lot

How so ,any idea?it didn't come out of any reply and service still cannot be access
