### ISSUE TITLE
Windows 10 Build 18351.18h1 release 190301-1611. Ubuntu uninstall.

### ISSUE THREAD

**Issue by fceledon** [Microsoft/WSL#3906]
WSL: 
Previously installed, Ubuntu is not showing on the uninstall list, however, still available on Start Menu. 
Right click on 'Bash on Ubuntu on Windows' shows uninstall option, but it's not available on the uninstall list.

**Comment by benhillis** [comment]
Thanks for reporting. The "bash on Ubuntu on Windows" designates the legacy WSL mechanism. If you run wslconfig /list is "Legacy" in the list?

You can safely remove this icon from your start menu if you are no longer using the legacy distro.
