### ISSUE TITLE
file URI's incompatible between wsl and windows.

### ISSUE THREAD

**Issue by ertwro** [Microsoft/WSL#3907]
I'm trying to open local html files as an output from a remote linux emacs session but the output lacks a colon in the drive letter and due to the file uri scheme it doesn't open.
```
(emacs)
xdg-open file:///c/Users/ertwr/.docsets/Bash.docset/Contents/Resources/Documents/bash/Aliases.html
(Browser)
file:///c/Users/ertwr/.docsets/Bash.docset/Contents/Resources/Documents/bash/Aliases.html
``` 
I have ```/c/Users/ertwr/AppData/Local/Vivaldi/Applications/vivaldi.exe``` boht in xdg-open and $BROWSER. 

I've tried wslpath but it gives gets rid of the initial slashes from file ``` file:/c:/Users/ert/...```
cmd.exe /c start doesn't work. I've tried using sed or awk scripts on the linux side, but is super inconsistent sometimes adding or removing slashes and whitespaces. Not to mention the firefox version inside wsl doesn't support GPU. So I'm stuck.

**Comment by Biswa96** [comment]
Try to add `/mnt/c`.

**Comment by ertwro** [comment]
@Biswa96 Try to add it where? I'm trying to use the default windows web-browser. This means it requires access to the windows URI file system. Not just that ```/mnt/c``` is the default and if you input in the firefox or chrome broser version of windows ```file:///mnt/c/``` it opens nothing.  so I've changed it because it doesn't work. The reason I have ```/c/Users/ertwr/...``` is because That's where the C unit is mounted in my WSL, due to me modifying ```/etc/wsl.conf``` specifically to do so becuase it actually reduces the number of problems when dealing with ```wslpath```.

**Comment by fpopineau** [comment]
Hi,
Not sure it will solve you problem, but I open most files from WSL/emacs using this quick hack:
```
  (defun w32-shell-execute (operation document &optional parameters show-flag)
    (if (and operation (not (string= "open" operation)))
        (error "Don't know how to open %s" document)
      (call-process "/mnt/c/Windows/System32/cmd.exe" nil nil t "/c" "start" "\"\""
                    (concat ""
                            (replace-regexp-in-string "^/mnt/c/" "c:/"
                                                      (replace-regexp-in-string "^\\(/mnt/c\\)?/home/Fabrice/" "c:/home/" document))
                            ""))))
  )
```
My c:/Users/Fabrice/Documents directory is linked to c:/Home in Win32.
I vastly prefer to use only one Chrome browser and I use the Win32 one.
Regards;

**Comment by ertwro** [comment]
@fpopineau Many thanks. Unfortunately no. I had already tried a similar approach with cmd.exe /c start and replacing the regexp but it was inconsistent maybe because it's a remote session. Your hack is almost identical to mine. Thanks.

**Comment by therealkenc** [comment]
Ran course. Ref #3832 for sport. There is probably a solution to "I've tried using sed or awk scripts on the linux side, but is super inconsistent sometimes adding or removing slashes and whitespaces" but you'll probably find a better audience on serverfault or similar.

**Comment by ertwro** [comment]
Half a year later this still doesn't work. Linux and Windows URI's are incompatible. Not even the new Edge browser tries to translate. I'm done with this.

**Comment by ertwro** [comment]
For anyone interested. I found a solution for the browser.
Use a portable version of your browser and place it in a path included in your environmental variable. Either inside your shell .rc through ```export BINARY='/your/path/'``` or directly in windows.
In my case, I use [scoop](https://scoop.sh/) as a package manager which accomplishes both.
Next use the following script:
# Don't forget to adapt the regular expresion to your mount point in ```wsl.conf``` In my case is ```root = / ```
```bash
#!/usr/sbin/env bash
IFS=$'\n'

if [[ "$@" =~ \/([a-zA-Z]+)\/ ]]; then 
	"${HOME}/scoop/shims/chrome.exe" "${@/$BASH_REMATCH/${BASH_REMATCH[1]}\:\/}"
fi
```
Add it to your path and export it as your browser.
