### ISSUE TITLE
/proc/<pid>/stat presents niceness incorrectly

### ISSUE THREAD

**Issue by marc-groundctl** [microsoft/WSL#3911]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.17763.316

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```sh
$ { nice -n 0 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
0
$ { nice -n 1 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
4294967295
$ { nice -n -1 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
1
```

* What's wrong / what should be happening instead:

```sh
$ { nice -n 0 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
0
$ { nice -n 1 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
1
$ { nice -n -1 sleep 2 & sleep 1 && awk '{print $19 }' < /proc/$!/stat ; }
-1
```

There are 2 issues here.  The first is that the process niceness changes in the wrong direction (`nice -n -1` changes the niceness to 1 instead of -1).  The second is that the niceness is unsigned instead of signed (4294967295 instead of -1).

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/111536482-86cd2e00-8727-11eb-9f0f-ec7f75a85f5b.png)
