### ISSUE TITLE
Initial x87 control word is different from native linux

### ISSUE THREAD

**Issue by luoqi-git** [Microsoft/WSL#3912]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.523]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
The default/initial x87 control word is different from that of a native linux system, specifically the precision control field. This affects for example all `long double` variants of math library functions which use x87 FPU and not SSE.
```
% cat t.c
#include <stdio.h>
#include <xmmintrin.h>

static unsigned short _mm_getfcw()
{
	unsigned short word;
	asm volatile("fstcw %0" : "=m" (*(&word)));
	return word;
}

int main()
{
	printf("%x %x\n", _mm_getfcw(), _mm_getcsr());
}
% cc -o t t.c
centos% ./t
37f 1f80
wsl% ./t
27f 1f80
```

* What's wrong / what should be happening instead:
The initial x87 control word is expected to be 0x37f.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
N/A

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
#830
