### ISSUE TITLE
becomes no-login shell after su

### ISSUE THREAD

**Issue by LeoJhonSong** [Microsoft/WSL#3913]
I modified my `/etc/profile`, `/etc/bash.bashrc`, `~/.profile` and `~/.bashrc` to show  which of them have been loaded. But then I find something intersting:

```bash
/etc/bash.bashrc
/etc/profile
~/.bashrc
~/.profile
leo-dell-ubuntu@Leo-Dell:~$ su
Password:
/etc/bash.bashrc
~/.bashrc
root@Leo-Dell:/home/leo-dell-ubuntu#
```

The first four lines shows these four files are loaded when access WSL by the start menu tile,which means it is a **login shell**. As I know, it should also be a **login shell** after we run `su`.  
However from the above experiment we can see that it becomes a **no-login shell** then, since neither `/etc/profile` nor `~/.profile` is loaded.

I suppose this is kind of issue 🤷‍♂️

**Comment by therealkenc** [comment]
I don't get `.profile` executed on `su` in a quick test on Real Linux (just tried). Which is expected, given what `su` (and everything under it) does isn't in WSL's control. WSL just performs whatever syscalls it is told to perform.

Gonna get tagged linux-behavior absent a `strace` log demonstrating a diverge per the template that was deleted.

![image](https://user-images.githubusercontent.com/7049700/54305610-e9adec80-4584-11e9-9249-f19e6473302f.png)

**Comment by therealkenc** [comment]
Can't reproduce `.profile` being executed on `su` here, on Real Linux or WSL.

![image](https://user-images.githubusercontent.com/7049700/54306772-5f1abc80-4587-11e9-9297-06b05650f34d.png)

![image](https://user-images.githubusercontent.com/7049700/54307120-19122880-4588-11e9-8f18-38e673a7eaac.png)

**Comment by LeoJhonSong** [comment]
Sorry this is my fault, I soon figured out that su access **non-login** shell by default.
