### ISSUE TITLE
Starting WSL from a scheduled task does not persist unless run as admin

### ISSUE THREAD

**Issue by nmnuckols** [Microsoft/WSL#3918]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.107] (Windows Server 2019 v. 1809)

* What you're doing and what's happening:  

I'm using WSL to run Redis inside an Ubuntu distro on Windows Server 2019.  I'm not able to use a real Linux box or even Docker, so WSL seemed like my only other option if I want to use Redis for small light-load applications.  Another requirement that I had was to run WSL as a Managed Service Account (MSA).  These are the steps I took:
1.  Since the distro must run in the context of the user who installed it, I was able to log into the server using my domain admin account, start PowerShell running as the MSA account and install the distro.  
2. Installed Redis on the distro.
3. I can use PowerShell (as MSA) to kick off the WSL process and start the Redis service, then sign off the server and everything works great.
4. Next step was to set up a scheduled task to kick off the WSL process and start the Redis server by setting the Program/Script to "C:\Windows\System32\bash.exe" and the Arguments to -c "sudo ~/.local/bin/start_redis.sh", where start_redis.sh is a script on the distro that calls "service redis-server restart".
5. The scheduled task had to run as the MSA account, so I used PowerShell to assign that account to the scheduled task.  

* What's wrong / what should be happening instead:

The scheduled task will only work if the MSA account is in the Administrators group.  If it is, then I can restart the server and the task will successfully kick off WSL and run that script.  Redis is started and life is good.  
If the MSA account is NOT in the Administrators group, I can open the Task Scheduler and manually "run" the scheduled task.  This works fine, but restarting the server does not start WSL properly using that task.  
To debug the issue, I piped the output of the scheduled task to a log file.  A successful run would show the following: 
Stopping redis-server: redis-server
Starting redis-server: redis-server
This is what you'd expect to see as the std out from bash.exe when you make a call to "service redis-server restart", which means that the task was able to start WSL and run the bash command under the MSA account.  This is the output I see when I run it manually or when the task is run at server startup.  
I believe that running the bash.exe command at startup under the MSA account creates a separate instance (or temporary instance) of WSL.  If I log into the server and run bash as the MSA, then redis isn't running even though the startup task was successful.  
The result is different if MSA is in the Administrators group.  In that case, it executes the bash command on start up and if I log into the server and run bash myself, my services are already running.

This is a problem because my IT group won't allow me to put the MSA account in the Administrators group.  It was only allowed to be there for testing to determine that was the issue.

**Comment by JacekHoleczek** [comment]
I am facing the same problem. Have found a solution?
