### ISSUE TITLE
Invalid error code EAGAIN returned on USB Serial Port disconnection

### ISSUE THREAD

**Issue by rustyx** [microsoft/WSL#3919]
This issue is related to the WSL USB [serial port support](https://www.scivision.co/usb-tty-windows-subsystem-for-linux/).

On USB device disconnection, `read` and `select` syscalls set errno to EAGAIN.

But in Linux EAGAIN is the same code as EWOULDBLOCK:

```
#define EAGAIN          11      /* Try again */
#define EWOULDBLOCK     EAGAIN  /* Operation would block */
```

And is generally not useful for permanent errors.

Indeed pySerial just [retries the read](https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L531) indefinitely.

The following simple Python program therefore goes into an infinite loop:

```
import serial
port = '/dev/ttyS5' # ttyS5 = COM5
ser = serial.Serial(port, 115200)
while ser.is_open:
    print(ser.readline())
```

(The same happens in most other serial programs, for example idf_monitor).

Please change the error handling to return a more meaningful error for this situation, for example `EIO` or `ENODEV`.

**Comment by therealkenc** [comment]
`strace(1)` log on Real Linux vs. WSL (per the template you deleted) would help clarify the ask here. It doesn't need to be long (with a bunch of retries) just the diverge between the two. If there is no diverge that's tag just by-design.

**Comment by rustyx** [comment]
Here are the relevant traces:

Ubuntu x64 (kernel 4.15.0 x86_64):
```
open("/dev/ttyUSB0", O_RDWR|O_NOCTTY|O_NONBLOCK) = 3
ioctl(3, TCGETS, {B9600 opost isig icanon echo ...}) = 0
ioctl(3, TCGETS, {B9600 opost isig icanon echo ...}) = 0
ioctl(3, TCGETS, {B9600 opost isig icanon echo ...}) = 0
ioctl(3, SNDCTL_TMR_START or TCSETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TIOCMBIS, [TIOCM_DTR])         = 0
ioctl(3, TIOCMBIS, [TIOCM_RTS])         = 0
ioctl(3, TCFLSH, TCIFLUSH)              = 0
select(4, [3], [], [], NULL)            = 1 (in [3])
read(3, "", 1)                          = 0
write(2, "SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
) = 123
close(3)                                = 0
```

WSL (kernel 4.4.0 x86_64):
```
open("/dev/ttyS5", O_RDWR|O_NOCTTY|O_NONBLOCK) = 3
ioctl(3, TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(3, SNDCTL_TMR_START or TCSETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B115200 -opost -isig -icanon -echo ...}) = 0
ioctl(3, TIOCMBIS, [TIOCM_DTR])         = 0
ioctl(3, TIOCMBIS, [TIOCM_RTS])         = 0
ioctl(3, TCFLSH, TCIFLUSH)              = 0
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL)          = 1 (in [3])
read(3, 0x7f6bc451061c, 1)              = -1 EAGAIN (Resource temporarily unavailable)
<...infinite loop...>
```
So it seems Linux simply returns EOF. Would that be possible to implement? If not, EIO will also work I guess.

**Comment by therealkenc** [comment]
Most excellent, thank-you. That looks like a pretty clear diverge from here. Your OP was muddled by the ask for "`EIO` or `ENODEV`" (which is what threw me). You don't want that. Your Real Linux kernel `strace(1)` log demonstrates the expected behavior; which is to succeed but return no data.

**Comment by therealkenc** [comment]
One last; because there is some nuance here not being stated explicitly. When you say "On USB device disconnection" I assume you mean you've yanked the dongle. Short story short here: don't do that (no, really). WSL has no udev. On Real Linux I assume that `/dev/ttyUSB0` is no longer in your `/dev`, after the dongle is yanked, correct? [I don't have one to actually try myself.] On Real Linux you've got an open handle to that device (which is in principle fine) and that `read()` should return `0` not `EAGAIN`. I hope that can be addressed. 

But... because WSL is in effect a old-school-pre-udev-circa-2002 Linux kernel, your scenario treads into user error territory. It is like you yanked your RS232 PCI board in 2002 and are wondering why all hell broke loose.
