### ISSUE TITLE
Java 8 Maven Build Locks Up WSL

### ISSUE THREAD

**Issue by shawnweeks** [microsoft/WSL#3922]
During one of the unit tests for the Apache Knox Project WSL locks up and becomes unkillable. Once this happens you cannot restart the LxssManager and new Ubuntu 16.04 instances never start.

To reproduce
apt install maven openjdk-8-jre openjdk-8-jdk git
git clone https://github.com/apache/knox.git
cd knox
maven clean install

It's stops responding on the step Running org.apache.knox.gateway.websockets.WebsocketMultipleConnectionTest

OS Windows 10 Pro 1809 Build 17763.379

Attaching LogMan Logs

**Comment by shawnweeks** [comment]
If I run strace around the maven build it doesn't lockup WSL. Attaching STrace for specific module that locks up normally.
[strace.log](https://github.com/Microsoft/WSL/files/2984143/strace.log)

**Comment by mtnygard** [comment]
I observe similar behavior (WSL locks up, unkillable, LxssManager cannot be stopped.)

I am not using Maven, but I am running OpenJDK 11. This just started in the last two days, since build 18356 went to the Slow ring. I've also tried moving up to build 18361 and experienced the same thing.

**Comment by shawnweeks** [comment]
I suspect it's related to forking and network threads as this fails on a test where it tries to spin up a jetty webserver and make connections until it fails. Not sure what kind of tracing I can do to help the team track it down though.

**Comment by brokebroke** [comment]
Also being affected by this. Java 8. Restarting windows is only recovery option.

**Comment by brhahlen** [comment]
Experiencing a similar using while running a totally different product.
Not sure why it happens, but restarting Windows is indeed the only option

**Comment by brhahlen** [comment]
WSL has become unusable for me because of this...
I run java programs a lot, and I have had to reboot my machine four times already this morning...

**Comment by mtnygard** [comment]
Shortly after my previous comment build 18356.1 went to the fast ring. I'm on that build now and have _not_ experienced this problem in several days.

**Comment by brhahlen** [comment]
I'm not on Insider builds though... I'm on 1809, build 17763.379

**Comment by brhahlen** [comment]
I seem to have the same problem on 1903, build 18362.86

**Comment by Brian-Perkins** [comment]
Fixed in Windows Insider Build [18890](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18890)

**Comment by shawnweeks** [comment]
Unfortunately my organization doesn't allow insider builds and this is starting to show up on all of my Java Projects. Apache NiFi won't build either. I'm going to have to try and get something setup with Docker or in a VM now.

**Comment by brhahlen** [comment]
Any chance the fix will be "backported" to 1903?
It is getting really annoying to use WSL and having it crash all the time.

**Comment by kwahsog** [comment]
Would love to have this backported, currently having a very similar issue with our project. 

Windows 1809, 17763.557

**Comment by RMMSecurity** [comment]
Also running into this problem!

Windows 1803

**Comment by mliradelc** [comment]
Hi, I'm a developer of the [Opencast Project](github.com/opencast) and I tried WSL because it could give me a lot of flexibility, but I'm facing the same issue. When I execute maven, Java crashes WSL, in specific when executing automated network tests.

Please can you solve this? Otherwise, I will have to install a good'ol Virtual machine to work.
