### ISSUE TITLE
Fail to enable WSL on Windows 10 Home

### ISSUE THREAD

**Issue by justinfrankel** [Microsoft/WSL#3925]
This is a Lenovo X1 Carbon (5th gen) running Windows 10.0.17134.

I've recently run "DISM /Online /Cleanup-Image /RestoreHealth" from a administrator powershell, which had no effect.

Method 1: Control Panel / Programs and Features / Turn Windows features on or off: check Windows Subsystem for Linux, hit OK. Result: "Windows couldn't complete the requested changes / The referenced assembly could not be found. / Error code: 0x80073701". The "Tell me how to solve this problem" link links to https://support.microsoft.com/en-us/help/2734782/net-framework-3-5-installation-error-0x800f0906-0x800f081f-0x800f0907 which does not seem to help.

Method 2: Administrator powershell, running "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux" . This gives an error "Enable-WindowsOptionalFeature : The referenced assembly could not be found."

I'd be happy to provide any more details or screen capture as needed, thanks!

**Comment by mscraigloewen** [comment]
Hi @justinfrankel ,

So it seems to be an issue with your optional component store, which can be difficult to fix. 

Could you try running: `sfc /scannow` , and also try going to your settings and checking if you have any updates to install? If neither of those work, I'd also suggest the age old repair tool of turning it off and on again (if you haven't done so already) 😊

And if those don't work let me know and we can figure out next steps.

Thanks for your patience!

**Comment by justinfrankel** [comment]
Thanks, I did the following:

1) run: sfc /scannow, which seemed to do stuff and mentioned that errors were corrected.
2) Tried to enable WSL, which failed
3) Power off and on
4) Tried again to enable WSL, same error
5) Windows update, which now showed a new update (version 1809 amd64 2019-03) (was not listed earlier today, woohoo) 
6) Installed update
7) Reboot
8) That seemed to the trick!

**Comment by mscraigloewen** [comment]
Glad to hear your problem is fixed!
If you run into any more issues please reach out and we'll help you out. :)
