### ISSUE TITLE
docker service is running but containers can't be started

### ISSUE THREAD

**Issue by gnastnosaj** [Microsoft/WSL#3927]
Microsoft Windows [Version 10.0.17763.379]
```
jasontsang@JASONTSANG-SURFACEPRO2:~$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:2557e3c07ed1e38f26e389462d03ed943586f744621577a99efb77324b0fe535
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"EOF\"": unknown.
ERRO[0012] error waiting for container: context canceled
jasontsang@JASONTSANG-SURFACEPRO2:~$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
jasontsang@JASONTSANG-SURFACEPRO2:~$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
```

**Comment by mscraigloewen** [comment]
Hi @gnastnosaj , it looks like you're trying to run the docker service inside of WSL. Is that correct?

If that's the case, then unfortunately docker isn't supported currently in WSL (but we are working on it!)
My recommendation is to install Docker for Windows and connect to that using WSL. [This article](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) goes over how to set that up!

**Comment by nikaslg** [comment]
@gnastnosaj They didn't yet found a way to run a docker the smart way in WSL, so you can just bind windows docker to bash and just use it from there, also there will be bugs, but it's better than using shell or gui tools.

**Comment by Biswa96** [comment]
@nikaslg Docker uses many low level Linux kernel features (like cgroups, namespace) which can be hard to implement in Windows kernel mode. So, the docker daemon shows may error. But from 20H1 builds, I can bind/connect docker daemon i.e. `/usr/bin/dockerd` in WSL with `unix://`, `fd://` and `tcp://0.0.0.0:2375` sockets. Also `docker pull` works.

**Comment by gnastnosaj** [comment]
thanks for all your help, I will continue to pay attention to this issue.

**Comment by little-motor** [comment]
thanks，this is the question I'm looking for

**Comment by drshiki** [comment]
docker is supported in WSL2， upgrade WSL1 to WSL2，https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/
