### ISSUE TITLE
Accessing Linux Files from Windows 

### ISSUE THREAD

**Issue by brubakerjeff** [Microsoft/WSL#3929]
Hi,

According to this article
https://www.omgubuntu.co.uk/2019/02/access-linux-files-from-windows-explorer-wsl

With build 1903 of Windows I will be able to access Linux Subsystem files from Windows through explorer (can that be confirmed?).

Running "explorer ." from a shell as mentioned does not work for me (I'm at build 17134, how can I upgrade? Or just wait?)

If that is indeed the case could that feature be mentioned here?

https://docs.microsoft.com/en-us/windows/wsl/faq

Thanks,
Jeff

**Comment by WSLUser** [comment]
New features are only available in newer builds. If you want to try out using the Plan9 Server then you'll need to be on Insiders. Otherwise wait for the next release of Windows and upgrade to that for the feature.

**Comment by mscraigloewen** [comment]
Hi @brubakerjeff , 

Yes it's confirmed that you can access Linux files through Windows File Explorer. [Here's](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/) a link to the blog post that the team wrote about the new features!

If you want to try out the new features, you'll need to be running build 18836 or later. To echo what @WSLUser said, to do that you'll need to be part of the Windows Insider program. You can learn more about doing that [here](https://insider.windows.com/en-us/). It's a great way of getting access to new features, and giving valuable feedback on them! 

Let me know if you have any more questions :)

**Comment by Po-wei** [comment]
@brubakerjeff  You are currently at 1803, the new feature will be shipped at 1903.
Therefore, you are 2 large windows update behind.
