### ISSUE TITLE
tmux closes upon closing the last terminal

### ISSUE THREAD

**Issue by kundeng** [Microsoft/WSL#3930]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.1029]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
tmux closes when last terminal closes

This seems to be a regression from a bug filed previous 
https://github.com/Microsoft/WSL/issues/1007

* What's wrong / what should be happening instead:
tmux closes when last terminal closes

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> Microsoft Windows [Version 10.0.16299.1029]

#709 and company, [17046](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046) or better. Not a regression, 16299 is behind the fix.

**Comment by aont** [comment]
@kundeng Hello. I'm not a WSL developer, but the workaround I have developed works good: [aont/tmux-wsl-workaround](https://github.com/aont/tmux-wsl-workaround/)
