### ISSUE TITLE
Got a bug with kali wsl terminal

### ISSUE THREAD

**Issue by r1riyad** [Microsoft/WSL#3931]
Whenever I type clear in the terminal the user@pc:~$ went under the terminal(cmd) title and I have to scroll up for see the text. even Script like Fsociety has the same issue with this! it can't show the full text or intro in terminal I have to scroll after every single command!please fix this I checked other wsl like ubuntu . Those doesn't have this issue so far. 

My build version is 1809
![Capture 1](https://user-images.githubusercontent.com/33262712/54810524-87ee3080-4cb0-11e9-96eb-7a3dfc2ede90.PNG)
![Capture2](https://user-images.githubusercontent.com/33262712/54810534-8ae92100-4cb0-11e9-94d9-d6be9385119d.PNG)

**Comment by WSLUser** [comment]
https://github.com/Microsoft/Console/issues

**Comment by mscraigloewen** [comment]
Hi @r1riyad , 

Could you clarify on your issue a little more? Are you talking about the idea that when you type `clear` in Kali Linux, you can't scroll up to see the previous commands, whereas in Ubuntu or Debian after you type in `clear` you can scroll up and see previous commands?

**Comment by sirredbeard** [comment]
To workaround: alias `clear` to `clear -x` in your respective shell config file, e.g.:

```
$ echo "alias clear='clear -x'" >> ~/.bash_aliases && source ~/.bash_aliases
```

**Comment by r1riyad** [comment]
> 
> 
> To workaround: alias `clear` to `clear -x` in your respective shell config file, e.g.:
> 
> ```
> $ echo "alias clear='clear -x'" >> ~/.bash_aliases && source ~/.bash_aliases
> ```

Fixed the general user issue. But the problem still exist on root mode after "sudo su" command.

**Comment by r1riyad** [comment]
> 
> 
> Hi @r1riyad ,
> 
> Could you clarify on your issue a little more? Are you talking about the idea that when you type `clear` in Kali Linux, you can't scroll up to see the previous commands, whereas in Ubuntu or Debian after you type in `clear` you can scroll up and see previous commands?

I m not talking a about the previous command . as u can see in my snaps that whenever i type clear the whole screen goes blank and and i have to click the scroll up arrow to see the user@pc line.

**Comment by r1riyad** [comment]
Ok Fixed the root issue also by adding below lines in **.bashrc** after @sirredbeard 's workaround.Those lines are..... 
```
if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi
```
Thanks everone!!!

**Comment by zMAX17** [comment]
Hai, for me it's Working in the Terminal. But when i open some program like Python that have command like os.system("clear") it's not working, i have to scroll up every single command. What's the Problem?
