### ISSUE TITLE
WSL apt full-upgrade reverts directory mask (Ubuntu 1804.2018.817.0)

### ISSUE THREAD

**Issue by jardinimf** [Microsoft/WSL#3933]
In a fresh install of Ubuntu 18.04, the command `mkdir` creates a directory with expected mask 755. After updating with apt (update and full-upgrade) the behavior reverts to 777.

Versions:
Microsoft Windows 10 Enterprise 1809 (build 17763.379)
WSL Ubuntu 18.04 (build 1804.2018.817.0)

**Comment by therealkenc** [comment]
Closing with ref #352 for lack.
