### ISSUE TITLE
CROSSMETA integration with WSL to add Linux file systems support and beyond

### ISSUE THREAD

**Issue by crossmeta** [Microsoft/WSL#3934]
Hi,

Glad to see WSL recognizing beyond NTFS drives and able to interface with other native IFS file system drivers such as [Crossmeta](https://github.com/crossmeta/cxfuse)
With Crossmeta interface WSL instantly adds support for all popular file systems XFS, EXT2/3/4 , ReiserFS, HPFS and FUSE.

After adding support for FileInformationClass 68,70,71 WSL is able to do read/write to crossmeta namespace. But still there are some minor quirks related to permissions and ownership which has to be strengthened.

Is there any information for IFS developers to interface with WSL properly.

Also Crossmeta is much more powerful than VolFS as it brings the entire BSD VFS and all VFS syscalls are supported.  When compared to Lxcore it has bare minmum syscall  notably fork/wait just to get busybox ash shell working.  

You can check out [Crossmeta Sys](https://github.com/crossmeta/sys) for its unique features

Thanks

Sam

**Comment by therealkenc** [comment]
> Is there any information for IFS developers to interface with WSL properly.

You'll want to be a lot more specific, or this question post submission, more likely than not, ends up answer "no, not really" after the customary wait period.

**Comment by crossmeta** [comment]
I was looking for some write-up on how WSL interacts with IFS file systems drivers, especially for the  FileInformationClass structure 
1. Is the EffectiveAccess  access mask just for the owner of file. 
2. Is FILE_STAT_LX_INFORMATION  is the only needed information for chmod, symbolic links to work
3. Is there any debug trace within drvfs when it deals with the IFS drivers. strace

Thanks

**Comment by Biswa96** [comment]
`FILE_STAT_LX_INFORMATION` can not be written with `NtSetInformationFile()` https://github.com/Microsoft/WSL/issues/3865

**Comment by benhillis** [comment]
DrvFs sits on top of the NTFS stack so conceptually it is no different than any other Windows binary.

**Comment by crossmeta** [comment]
One would wish DrvFs behaves like any other program apparently it is not as pointed out in #3865
There would be other vagaries  too as WSL as I am unable to launch exe programs from crossmeta V: drive.  I am not sure why would it think that is symbolic link as the stat output shows regular file only.

But I could run from WSL as follows ```cmd.exe /c v:\\bin\\dmesg.exe```

```console
user@WinDev1903Eval:/mnt/v/bin$ strace ./dmesg.exe  
execve("./dmesg.exe", ["./dmesg.exe"], 0x7ffff3186a00 /* 18 vars */) = 0 
arch_prctl(ARCH_SET_FS, 0x61c0b8)       = 0
set_tid_address(0x61c0f0)               = 17
getpid()                                = 17
getcwd("/mnt/v/bin", 4096)              = 11
uname({sysname="Linux", nodename="WinDev1903Eval", ...}) = 0 
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0, 0x2f, 0x22), 0x7ffffe8fbb80) = 0
open("./dmesg.exe", O_RDONLY|O_NOFOLLOW|O_PATH) = 5
brk(NULL)                               = 0xab0000
brk(0xab1000)                           = 0xab1000
ioctl(3, _IOC(0, 0, 0x3f, 0x22), 0x7ffffe8fb9f0) = -1 EINVAL (Invalid argument) 
close(5)                                = 0
readlink("./dmesg.exe", 0xab0020, 255)  = -1 EINVAL (Invalid argument)
close(3)                                = 0
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
user@WinDev1903Eval:/mnt/v/bin$ stat  ./dmesg.exe  
  File: ./dmesg.exe 
  Size: 4608            Blocks: 10         IO Block: 512    regular file        
Device: dh/13d  Inode: 12551       Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)        
Access: 2019-03-25 00:40:52.894490500 -0700
Modify: 2019-03-23 17:03:27.212588500 -0700
Change: 2019-03-23 17:03:49.212588500 -0700
 Birth: -
user@WinDev1903Eval:/mnt/v/bin$
```
