### ISSUE TITLE
Broken multiprocessing with forkserver in Python 3.7 on WSL

### ISSUE THREAD

**Issue by tsangwpx** [microsoft/WSL#3935]
**Please fill out the below information:**
* Your Windows build number: 
Microsoft Windows [Version 10.0.18356.16]
Debian GNU/Linux from MS Store
`3.7.2-3` from Debian buster

* What you're doing and what's happening: 
`$ python3.7 main.py` failed. `main.py` is given by
```
import multiprocessing as mp
import multiprocessing.pool

def tasks():
    print(mp.current_process())

def main():
    mp.set_start_method('forkserver')

    with mp.pool.Pool(1) as pool:
        results = [pool.apply_async(tasks) for i in range(3)]

        for ret in results:
            ret.get()


if __name__ == '__main__':
    main()
```

* What's wrong / what should be happening instead:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3.7/multiprocessing/forkserver.py", line 186, in main
>     with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
>   File "/usr/lib/python3.7/socket.py", line 156, in __init__
>     _socket.socket.__init__(self, family, type, proto, fileno)
> OSError: [Errno 22] Invalid argument: 'protocol'

The correct output should look

> <ForkServerProcess(ForkServerPoolWorker-1, started daemon)>
> <ForkServerProcess(ForkServerPoolWorker-1, started daemon)>
> <ForkServerProcess(ForkServerPoolWorker-1, started daemon)>

* Strace of the failing command, if applicable:
> [pid   360] getsockopt(8, SOL_SOCKET, SO_TYPE, [1], [4]) = 0
> [pid   360] getsockopt(8, SOL_SOCKET, SO_PROTOCOL, 0x7fffdc818384, 0x7fffdc818380) = -1 EINVAL (Invalid argument)

Seem that SO_PROTOCOL is not supported.

https://github.com/python/cpython/blob/b6e43af669f61a37a29d8ff0785455108e6bc29d/Modules/socketmodule.c#L4885-L4890

* Workaround
Use `spawn` instead of `forkserver`

**Comment by Biswa96** [comment]
Any event tracing, etl files?

**Comment by therealkenc** [comment]
Nah that `strace` snippet speaks for itself. But the smart play would be to link the whole gist of the `strace(1)` log though. Chances also improve with CLI repro steps. Isn't a dupe that I can see (which in itself is suspicious). Maybe WSL doesn't like what it sees in `*optlen`.

**Comment by miguelbalmeida** [comment]
Also having this same issue.

Your Windows build number:
Edition: Windows 10 Home
Version: 1809
OS build: 17763.678
Installed Ubuntu from the App Store
Python 3.7.4

What you're doing and what's happening:
`$ python main.py` with `main.py` as given above by @tsangwpx. Output is
```
$ python main.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/forkserver.py", line 186, in main
    with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument: 'protocol'
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 10, in main
    with mp.pool.Pool(1) as pool:
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/popen_forkserver.py", line 55, in _launch
    self.pid = forkserver.read_signed(self.sentinel)
  File "/home/miguel/anaconda3/envs/myenv/lib/python3.7/multiprocessing/forkserver.py", line 312, in read_signed
    raise EOFError('unexpected EOF')
EOFError: unexpected EOF
```

Sadly, in my case the workaround is not feasible as this is a client's project with multiple other developers who all use (non-WSL) Unix-based systems. I cannot just go and change all instances of `forkserver` to `spawn` across all the libraries we're using.

**Comment by CJ-Wright** [comment]
This seems to be the same error as https://github.com/Microsoft/WSL/issues/3764 (I've also experienced this error with Dask)

**Comment by therealkenc** [comment]
Can't speak to #3764 (there was zero repro over there), but by total chance #4604 was posted recently with a strace log. Duping forward; same thing.

**Comment by andriworld** [comment]
This is fixed in WSL 2. 

To check whether your distribution is on version 2:  `wsl -l --all -v`
To upgrade to version 2: `wsl --set-version <your_distro> 2`

**Comment by taviso** [comment]
A quick alternative workaround for WSL1, save this as `wslcompat.c`:

```c
#define _GNU_SOURCE
#include <sys/socket.h>
#include <dlfcn.h>
#include <errno.h>
#include <string.h>

static int (*getsockoptptr)(int sockfd, int level, int optname, void *optval, socklen_t *optlen);

static void __attribute__((constructor)) init(void)
{
    getsockoptptr = dlsym(RTLD_NEXT, "getsockopt");
}

int getsockopt(int sockfd,
               int level,
               int optname,
               void *optval,
               socklen_t *optlen)
{
    struct sockaddr sa = {0};
    socklen_t len = sizeof(sa);

    // Pass through the request.
    int result = getsockoptptr(sockfd, level, optname, optval, optlen);

    // If it worked, we're good.
    if (result != -1 || errno != EINVAL)
        return result;

    // We only handle sockets.
    if (level != SOL_SOCKET || !optlen || !optval)
        return result;

    // Test if this is an AF_UNIX socket.
    if (getsockname(sockfd, &sa, &len) != 0)
        return result;

    if (sa.sa_family != AF_UNIX)
        return result;

    // Okay, see if this is one we can easily emulate.
    if (optname == SO_DOMAIN && *optlen >= sizeof(sa.sa_family)) {
        memcpy(optval, &sa.sa_family, sizeof sa.sa_family);
        return 0;
    }

    // This one is always 0 for AF_UNIX
    if (optname == SO_PROTOCOL && *optlen >= sizeof(int)) {
        memset(optval, 0, sizeof(int));
        return 0;
    }

    return result;
}
```

Compile it:

```
$ sudo gcc -shared -fPIC wslcompat.c -o /usr/local/lib/libwslcompat.so -ldl
```

Verify that solves your problem:

```
$ LD_PRELOAD=/usr/local/lib/libwslcompat.so python yourscript.py
```

If it did... **optionally** make it permanent:

```
$ sudo patchelf --add-needed /usr/local/lib/libwslcompat.so /usr/bin/python
```

I'll try to maintain these in https://github.com/taviso/wslcompat
