### ISSUE TITLE
wls.exe --import of Fedora 29 suceeds, but leaves dnf and rpm broken

### ISSUE THREAD

**Issue by EricPell** [Microsoft/WSL#3936]
Microsoft Windows [Version 10.0.18362.1]                                                                                                                                        

Steps to Reproduce: 

Fedora 29 Docker base container at https://koji.fedoraproject.org/koji/taskinfo?taskID=33660404

Extract Userspace tar from file

`wsl.exe --import Fedora Fedora C:\Users\Me\Downloads\c6fca5740f468ee746eb1490ca7490e9d7bc873a45c3882a01a89ce6b8e26e98\layer.tar`

Start Fedora :
`wsl.exe -d Fedora`

What is wrong: 
I can not update or repair the rpm repository:
`dnf update` produces
error: db5 error(12) from dbenv->open: Cannot allocate memory
error: db5 error(22) from dbenv->close: Invalid argument
error: cannot open Packages index using db5 - Cannot allocate memory (12)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed

`rpm --rebuilddb` fails with output
error: failed to replace old database with newdatabase!
error: replace files in /var/lib/rpm with files form /var/lib/rpmrebuilddb.27 to recover

Expected behavior: That will fix the data base
Resulting behavior: It has no effect. Trying to rebuild the database again increments the recovery rebuild number but has no effect on the erorr.

**Comment by therealkenc** [comment]
#3742

**Comment by EricPell** [comment]
> #3742

Just be clear I was asked by Ben Hillis to make this a new issue
