### ISSUE TITLE
Wrong Keyboard input when using ssh into Azure VM

### ISSUE THREAD

**Issue by timlod** [Microsoft/WSL#3938]
Microsoft Windows [Version 10.0.17134.648]

When using ssh from WSL to remote into an Azure DSVM (Ubuntu 16.04), certain key combinations do not work.
Specifically, CTRL-Backspace (or ALT-Backspace) do not work as intended.
CTRL-Backspace gives CTRL-H instead.
ALT-Backspace gives CTRL-ALT-H instead.
This was discovered in GNU emacs.

ssh user@hostname
$ emacs

Then try to use backward-kill-word using C-Backspace or M-Backspace; it generates C(-M)-h instead.

* What's wrong / what should be happening instead:
The correct combinations should be input.

**Comment by timlod** [comment]
Update:
Issue doesn't require ssh, emacs from WSL terminal experiences the same problem.
Not sure now if it's an emacs from Windows Console problem, as in general I can delete a word in WSL bash using ALT-Backspace.

**Comment by WSLUser** [comment]
Any Console-related issues should be filed at https://github.com/Microsoft/Console/issues. WSL uses `conhost` (well technically ConPTY now but that's Insider builds) just like CMD or PS.

**Comment by therealkenc** [comment]
Yeah, punting only because you'll get a much better response over there. WSL proper doesn't know you have a CTRL key. As a work around you can try an alternative terminal emulator like [`wsltty`](https://github.com/mintty/wsltty) or [`ttyd`](https://github.com/tsl0922/ttyd).
