### ISSUE TITLE
Unexpected behavior in mmap causing issues with rpm

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/WSL#3939]
* Summary:

This is the result of several weeks of collaboration between the Pengwin team, WSL community members, outside experts we retained, and partners at Oracle on an bug affecting Red Hat Package Manager (rpm) on WSL, in CentOS, RHEL, Fedora (partial), Oracle Linux, and Scientific Linux. Those efforts are extensively documented [here](https://github.com/WhitewaterFoundry/Pengwin-Enterprise/issues/20). After working through several theories and workarounds we believe we have narrowed down the issue to unusual mmap handling on WSL affecting the implementation of Berkeley DB inside rpm. The unusual mmap behavior seems to sync up with our workarounds and mitigations, so we have medium to high confidence this is the issue. There have been a handful of occasionally vague mmap issues reported before here, see #902 and #658, that are not quite on point, closest being #2852. Because this issue affects a broad array of distros on WSL we appreciate Microsoft's attention to this issue.

* Your Windows build number:  17134 and 17763.

* What you're doing and what's happening: 

1. Install an rpm-based distro on WSL, e.g. WLinux Enterprise with Scientific Linux.
2. Set root password and create new default user.
3. `su -` into root.
4. Example 1:
```
[root@t470s ~]# rpm -q rpm
rpm-4.11.3-35.el7.x86_64
[root@t470s ~]# rpm --rebuilddb
[root@t470s ~]# rpm -q rpm
Segmentation fault (core dumped)
```
5. Example 2:
```
[hayden@t470s ~]$ sudo rm -rf /var/lib/rpm/__db*
[hayden@t470s ~]$ db_verify /var/lib/rpm/Packages
BDB5105 Verification of /var/lib/rpm/Packages succeeded.
[hayden@t470s ~]$ sudo rpm --rebuilddb
[hayden@t470s ~]$ sudo yum update
Loaded plugins: ovl
Segmentation fault (core dumped)
```

* What should be happening:

Would expect `rpm --rebuilddb` would rebuild a working rpmdb. 

* What's wrong:

Running rpm --rebuilddb breaks rpmdb.

"When the underlying file is extended, the extended part of the mapping is actually mapped back to the beginning of the file. This is why BDB would crash when it extended the size of the file that backed the in-memory cache (one of the __db.### files), and why setting the cache size to a small value works as a work around" - Dr. Lauren Foutz, Oracle

C code which replicates the issue: 
[mmap_extend.c.txt](https://github.com/Microsoft/WSL/files/3008860/mmap_extend.c.txt)

* Strace of the failing command, if applicable: 

See strace, procmon, and etl files [here](https://github.com/WhitewaterFoundry/Pengwin-Enterprise/issues/20).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See strace, procmon, and etl files [here](https://github.com/WhitewaterFoundry/Pengwin-Enterprise/issues/20).

* Notes:

This issue does not affect OpenSUSE's implementation of rpm because of a [unique rpm implementation](https://github.com/WhitewaterFoundry/Pengwin-Enterprise/issues/20#issuecomment-468068581) in that distro.

**Comment by therealkenc** [comment]
Likely going to be the underlying cause behind #3742 as well, with a different but related repro. It is also probably causing Ben's observation in #3451 ([message](https://github.com/Microsoft/WSL/issues/3451#issuecomment-411925273)).

**Comment by therealkenc** [comment]
Wonderbar. But I've got to ask or it is going to nag at me. The following from Hayden's test case:
```
    addr1 = mmap(NULL, total_size, PROT_READ | PROT_WRITE, MAP_SHARED, fid, 0);
    /* Extend the file, write the last byte */
    printf("Extend the file to 1MB\n");
    lseek(fid, total_size - 1, SEEK_SET);
    write(fid, buf, sizeof(buf[0]));
```
... is semantically the same as...

```
    addr1 = mmap(NULL, total_size, PROT_READ | PROT_WRITE, MAP_SHARED, fid, 0);
    /* Extend the file */
    ftruncate(fid, total_size);
```

...which is #902. Which was allegedly impossible [because](https://github.com/Microsoft/WSL/issues/3451#issuecomment-415083094):

> I've looked into this and #902 and they share the commonality that both rely on functionality that the Windows kernel does not support which makes the scope of this fix a bit larger.

I'll take the win. But either (a) #902 just got fixed too or (b) I'm missing something stupid.

**Comment by Brian-Perkins** [comment]
When a file is mapped, we create a [section](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwcreatesection
) with that file as the backing store. In NT, when you have a file-backed section you can't make the file smaller -- the section is essentially locking those file "pages". That is causing the #902 problem and is the rationale behind the cited comment. In the current scenario, where mmap is bigger than the file size, that is supported, and the only interesting bit is when the actual view of the extended part of the file is [mapped](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwmapviewofsection). Currently this is done on-demand via guard pages, after verifying that the file is appropriately sized.

**Comment by therealkenc** [comment]
>  In the current scenario, where mmap is bigger than the file size, that is supported

Thanks much. Makes sense. 

In the #902 test case, maybe instead of actually truncating, make a note locally in the WSL VFS that new file size is 16 bytes (not 8192 byes), make a note the current high water mark is 8192, and don't call down to NT at all. In other words, lie to userspace that you've shrunk the file. A `read()` beyond the noted size 16 can return 0 bytes as expected. If a subsequent `write()`/`ftruncate()` enlarges the file beyond 8192 bytes, extend like you are doing here. Fix up the noted file size on `munmap()`/`close()` if the file really did shrink in the end.

If that means the mapped pointer still has valid pages containing `????....` characters from offset 16 through 8191 even after the `ftruncate(fd, 16)`, everyone can live with that. It beats an `ftruncate() EINVAL` any day of the week, and no working program will poke those addresses after the truncate anyway. [n.b. I assume if this was straightforward or actually work you'd have done it already, but I'll throw it at the wall anyway.]

**Comment by Brian-Perkins** [comment]
Fixed in Windows Insider Build [18890](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18890)

**Comment by ytrezq** [comment]
Unfortunately no.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/57339315-f1ea5a00-70e5-11e9-93e5-c242ede01a85.png)

**Comment by rfikki** [comment]
$ cd /home/rfikki/downloads
$ wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/rfikki/.wget-hsts'. HSTS will be disabled.
--2019-05-15 07:40:39-- https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 2607:f8b0:4009:805::200e, 172.217.0.14
Connecting to dl.google.com (dl.google.com)|2607:f8b0:4009:805::200e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 127938445 (122M) [application/octet-stream]
Saving to: ‘go1.12.5.linux-amd64.tar.gz’

go1.12.5.linux-amd64.tar.gz 100%[=================================================>] 122.01M 32.2MB/s in 4.1s

2019-05-15 07:40:43 (30.1 MB/s) - ‘go1.12.5.linux-amd64.tar.gz’ saved [127938445/127938445]

$ ls
go1.12.5.linux-amd64.tar.gz
$ tar xf go1.12.5.linux-amd64.tar.gz
$ sudo mv go /usr/local
[sudo] password for rfikki:
$ export GOROOT=/usr/local/go
$ mkdir -p $HOME/goprojects
$ export GOPATH=$HOME/goprojects
$ export PATH=/usr/local/go/bin:$PATH
$ cd $GOPATH
$ go get github.com/boltdb/bolt
$ cat /proc/version
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #706-Microsoft Mon Apr 01 18:13:00 PST 2019
$ ./main
-bash: ./main: No such file or directory
$ go build main.go
stat main.go: no such file or directory
$ cd $GOPATH
$ cat /proc/version
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #706-Microsoft Mon Apr 01 18:13:00 PST 2019
$ joe maain.go
^K I A maain.go (Modified)(go) Row 38 Col 1

func main() {
os.Remove("test.db")
db, err := bolt.Open("test.db", 0600, nil)
if err != nil {
log.Fatal(err)
}
defer db.Close()

    db.Update(func(tx *bolt.Tx) error {
            _, err := tx.CreateBucket([]byte("MyBucket"))
            if err != nil {
                    return fmt.Errorf("create bucket: %s", err)
            }
            return err
    })

    db.View(func(tx *bolt.Tx) error {
            b := tx.Bucket([]byte("MyBucket"))

            c := b.Cursor()

            c.Seek([]byte("test"))

            return nil
    })
    os.Remove("test.db")
}

File maain.go saved
$ cp maain.go main.go
$ ls
maain.go main.go pkg src
$ go build main.go
$ ./main
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/boltdb/bolt.(*Cursor).search(0xc00009ae20, 0xc00009aea8, 0x8, 0x8, 0x4)
/home/rfikki/goprojects/src/github.com/boltdb/bolt/cursor.go:256 +0x354
github.com/boltdb/bolt.(*Cursor).seek(0xc00009ae20, 0xc00009aea8, 0x8, 0x8, 0x4cb6a0, 0x7f2f206d0001, 0xc000018170, 0xc00009ae38, 0x43c892, 0xc00000e040, ...)
/home/rfikki/goprojects/src/github.com/boltdb/bolt/cursor.go:159 +0x7e
github.com/boltdb/bolt.(*Bucket).Bucket(0xc0000a00f8, 0xc00009aea8, 0x8, 0x8, 0xc00000e040)
/home/rfikki/goprojects/src/github.com/boltdb/bolt/bucket.go:112 +0xd5
github.com/boltdb/bolt.(*Tx).Bucket(...)
/home/rfikki/goprojects/src/github.com/boltdb/bolt/tx.go:101
main.main.func2(0xc0000a00e0, 0x4ecc50, 0xc0000a00e0)
/home/rfikki/goprojects/main.go:28 +0x72
github.com/boltdb/bolt.(*DB).View(0xc00000a1e0, 0x4ecc80, 0x0, 0x0)
/home/rfikki/goprojects/src/github.com/boltdb/bolt/db.go:629 +0x90
main.main()
/home/rfikki/goprojects/main.go:27 +0x10f

**Comment by galapogos01** [comment]
@therealkenc what is the chance of this fix being added to a 18362 servicing build? Or do we need to wait until next year / WSL2 to get a fix in a Production release?

**Comment by GigabyteProductions** [comment]
We'd like to see this fixed in WSL1 because we use VMware and VirtualBox on our workstations.

**Comment by therealkenc** [comment]
> @therealkenc what is the chance of this fix being added to a 18362 servicing build?

I don't have control over that sort of thing, but historically speaking, chances low to nonexistent. It should appear in the Fall 2019 release tho. You won't have to wait until 20H1 or WSL2.

**Comment by ytrezq** [comment]
@therealkenc : no it’s not fixed in latest insider builds… ʀᴘᴍ on Fedora still crash the same way…

**Comment by birbird** [comment]
I need this fix, how can I upgrade to 18890?

**Comment by therealkenc** [comment]
> It should appear in the Fall 2019 release tho.

^--- pretty sure it it didn't make 19H2 aka 2909 (18363 < 18890) but 2004 should be good.

**Comment by pdinc-oss** [comment]
> > It should appear in the Fall 2019 release tho.
> 
> ^--- pretty sure it it didn't make 19H2 aka 1909 (18363 < 18890) but 2004 should be good.

Not seeing it in Server 2019 yet, is it being applied there?
