### ISSUE TITLE
How to reduce the  reponse time of WSL after a period of idle time

### ISSUE THREAD

**Issue by shendaowu** [Microsoft/WSL#3941]
I use WSL, Windows 10 and mediawiki 1.32.0. My wiki is only used by me. Sometimes I would not ues my wiki several hours or use other software several hours, And after that it takes it 10 to 30 seconds to load the page. And after that visit of my wiki, the load time of other page is less than 1 second. Are there any simple method like changing some configuration files to improve it? Or Are there any method to make the priority of performance of WSL more high?

I have askd a similar question here: https://www.mediawiki.org/wiki/Topic:Ui3j7w0os4c73tx5 .

**Comment by therealkenc** [comment]
No takers; not WSL actionable. Answer you got over at mediawiki seems plausible. You might also try serverfault.com. Standard operating procedure (for the last 40+ years) is: buy more RAM.
