### ISSUE TITLE
Cannot create symlink with existing directory as second argument to `ln`

### ISSUE THREAD

**Issue by Oberon00** [microsoft/WSL#3943]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.379]

* What you're doing and what's happening:
```sh
$ # somewhere under /mnt/c (DriveFs)
$ mkdir foo
$ ln -s somefile foo ### ISSUE IS HERE ###
ln: failed to create symbolic link 'foo': Invalid argument
$ ln --version
ln (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Parker and David MacKenzie.
$ /my/old/ln -s somefile foo # OK
$  /my/old/ln --version
ln (GNU coreutils) 8.26
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Parker and David MacKenzie.
```
* What's wrong / what should be happening instead: `ln` should create a symlink to somefile in foo. Instead if fails with `Invalid argument`.

* Strace of the failing command, if applicable:  https://gist.github.com/Oberon00/a3c59298e5b8f88bd3b136c121eb0785

Notice that the new ln first does `symlinkat("somefile", AT_FDCWD, "foo") = -1 EINVAL (Invalid argument)` and then immediately goes on to error handling. Probably it doesn't like EINVAL.

The old ln first does a `stat("foo", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0` and then proceeds with `symlink("somefile", "foo/somefile") = 0`, so it never sees the EINVAL.

**Comment by therealkenc** [comment]
Can't repro here. Possibly #1475 #2898 #3611.

**Comment by Oberon00** [comment]
The coreutils I'm using is from Arch Linux https://www.archlinux.org/packages/core/x86_64/coreutils/ (via https://github.com/yuk7/ArchWSL). If you have a new enough glibc, you should be able to download the package from the archlinux.org link and just use the ln binary.

**Comment by therealkenc** [comment]
> The coreutils I'm using is from Arch Linux

[....redacted...] Of course it is.

That `EINVAL` in your `strace(1)` is incorrect on its face so made me look. On Arch in a VM, the `ln(1) 8.31` sequence is:
```
symlinkat("somefile", AT_FDCWD, "foo")  = -1 EEXIST (File exists)
openat(AT_FDCWD, "foo", O_RDONLY|O_PATH|O_DIRECTORY) = 3
symlinkat("somefile", 3, "somefile")    = 0
```

Small test case below. `glibc` doesn't matter because those are just unadulterated syscalls.
```
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

int main(int argc, const char *argv[])
{
    mkdir("foo", 0644);
    symlinkat("somefile", AT_FDCWD, "foo");
    return 0;
}

```
On Real Linux, and with WSL 18860 using LxFS, that yields an `EEXIST` alright. No surprise there.
```
mkdir("foo", 0644)                      = 0
symlinkat("somefile", AT_FDCWD, "foo")  = -1 EEXIST (File exists)
```

On WSL with DrvFS , the test case yields `EISDIR` for me.
```
mkdir("foo", 0644)                      = 0
symlinkat("somefile", AT_FDCWD, "foo")  = -1 EISDIR (Is a directory)
```
Which is wrong, pedantically. I never did get an `EINVAL`, so a reasonable assumption is something moved between your 17763 and my 18860 (I don't have a '783 handy to check). Either way that unexpected `EISDIR`/`EINVAL` looks like it is tripping `ln(1) 8.3`, contrast the `EEXIST` which `ln` sees coming.

**Comment by Oberon00** [comment]
Interestingly, this is the latest commit to GNU coreutils ln, at the time of this writing: coreutils/coreutils@3e0dff3925b5e521cae468087950e85b60002d1c
So it seems Solaris also returns EINVAL here.

**Comment by therealkenc** [comment]
Great find, thanks. Looks from the code like `EISDIR` on 18860 (assuming I've got that right) will still trip however. Patch or no patch that's a time bomb.

At base, construct is fragile. `ln(1)` is throwing bad inputs at the function and then trying to read tea leaves. Some FUSE filesystem on Real Linux™ might return who knows what. [Often programmers will point at the [man page](http://man7.org/linux/man-pages/man2/symlink.2.html) or [posix](http://pubs.opengroup.org/onlinepubs/9699919799/functions/symlink.html), but that doesn't help your customer or your employer if your program doesn't work on a filesystem enough people like.]

Anyway, academic. That DrvFS returns something different than LxFS isn't coherent. Hopefully it can be fixed up to return `EEXIST` like `ext4` on Real Linux.

**Comment by xzn** [comment]
This sort of "breaks" autoconf.

AS_INIT Generate code to detect whether `ln -s` is working [like this](https://github.com/autotools-mirror/autoconf/blob/6d38e9fa2b39b3c3a8e4d6d7da38c59909d3f39d/lib/m4sugar/m4sh.m4#L1291) and falls back to `cp -pR` when detection fails. Currently using a directory name as the second argument without trailing slash always results in "Is a directory" error.

**Comment by therealkenc** [comment]
>always results

On 21387 the `EISDIR` bug still exists on WSL1 with `drvfs` with [my repro](https://github.com/microsoft/WSL/issues/3943#issuecomment-478206390). I was not able to reproduce the `EISDIR` on WSL2 `9p` (or `ext4` by def), or on WSL1 `wslfs`.

![image](https://user-images.githubusercontent.com/7049700/120044011-d9e21d80-bfc1-11eb-8c67-6b60188973c1.png)

**Comment by xzn** [comment]
Thank you for the clarification. It's interesting that there's no error on `wslfs` since it's supposedly just `drvfs` under the hood.

**Comment by raymod2** [comment]
What is the resolution for this?  I upgraded my WSL1 distribution from Ubuntu 20.04 to Ubuntu 22.04 and now I am seeing build failures due to the following autoconf failure:

checking whether ln -s works... no, using cp -pR

I see that /usr/bin/ln has changed from coreutils 8.30 (Ubuntu 20.04) to coreutils 8.32 (Ubuntu 22.04) and that triggered this bug.  If this is fixed when using wslfs how do I switch to that?

**Comment by svi-os** [comment]
We're having the same issue as [raymod2](https://github.com/raymod2), if anyone has a pointer to a workaround that would be much appreciated.

**Comment by raymod2** [comment]
This was reported over 5 years ago and still hasn't been fixed!  And now MSFT is closing this ticket for lack of "activity"?
