### ISSUE TITLE
Windows file changes not recignized by bash processes

### ISSUE THREAD

**Issue by neilbalch** [Microsoft/WSL#3950]
* Your Windows build number:  1809/17763.379

* What you're doing and what's happening:  Start a hot-reloading process in WSL bash _(e.g. "serve" feature of  Vue CLI)_ on a project hosted in the `/home/[USERNAME]` path, then edit a project file with VS Code running from Windows. The WSL process doesn't recognize that any file was changed, but performing a subsequent "save" with `vim` on the bash terminal does the job. Vim recognizes that the file's contents have changed.

* What's wrong / what should be happening instead: Saving from Windows should result in the hot-reload kicking in and rebuilding the project.

* Strace of the failing command, if applicable:  N/A

I'm not exactly sure how this is the case or what precisely is happening. This is surprising to me, as I believe I remember using this capability in the past with no issues.

**Comment by therealkenc** [comment]
If you do submit a repro I'd go with something more lightweight than Vue CLI. Notepad + something with minimal steps (though vue-cli would do absent alternatives). Maybe [`inotifywait(1)`](http://man7.org/linux/man-pages/man1/inotifywait.1.html). You're probably right about an `strace(1)` log not going to help much here, since I _assume_ the log will just show the command you ran (whatever it was) will just be blocking on the inotify handle. But that's am assumption because no repro and no strace provided.

**Comment by neilbalch** [comment]
I'm not exactly sure what you want me to reproduce with, @therealkenc. I don't know of many more simple apps that make use of file-change listeners.

**Comment by therealkenc** [comment]
You can provide any [specific CLI reproduction steps](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) you like so long as they are provided. I was suggesting `inotifywait(1)` with `notepad.exe`, but whatever your pleasure.

**Comment by neilbalch** [comment]
Alright then! By using `inotifywait -m item.txt` _(pwd being `/home/neil`)_, I get the following when editing from `vim` on bash:

```
Setting up watches.
Watches established.
item.txt OPEN
item.txt CLOSE_NOWRITE,CLOSE
item.txt OPEN
item.txt CLOSE_NOWRITE,CLOSE
item.txt OPEN
item.txt ACCESS
item.txt CLOSE_NOWRITE,CLOSE
item.txt OPEN
item.txt CLOSE_NOWRITE,CLOSE
item.txt OPEN
item.txt CLOSE_NOWRITE,CLOSE
item.txt MOVE_SELF
item.txt ATTRIB
item.txt DELETE_SELF
```

and by using VS Code on Windows:

```
Setting up watches.
Watches established.
```

no events, no open events nor write events were captured. Does this help describe the situation more?

**Comment by therealkenc** [comment]
> Does this help describe the situation more?

Not really, because you can't access `/home/neil` from Windows VS Code.

Here is an example set of CLI repro steps.

```
$ sudo apt install inotify-tools
$ cd $(wslpath C:\\) && cd $(wslpath $(cmd.exe /c "echo %USERPROFILE%") | tr -d '\r')
$ mkdir -p ./inotify-test && cd inotify-test
$ echo "editing this in vscode" > ./item.txt
$ cmd.exe /c code.cmd --version | head -n 1
1.32.3
$ # edit and save the file after Code launches and inotifywait is live
$ cmd.exe /c code.cmd -n $(wslpath ./item.txt)   $ inotifywait -m ./item.txt    
Setting up watches.
Watches established.
./item.txt MODIFY
./item.txt ATTRIB
./item.txt MODIFY
./item.txt ATTRIB
```

Seems to take.

**Comment by therealkenc** [comment]
> Does this help describe the situation more?

Not really, because you can't access `/home/neil` from Windows VS Code.

Here is an example set of CLI repro steps.

```
$ sudo apt install inotify-tools
$ cd $(wslpath C:\\) && cd $(wslpath $(cmd.exe /c "echo %USERPROFILE%") | tr -d '\r')
$ mkdir -p ./inotify-test && cd inotify-test
$ echo "editing this in vscode" > ./item.txt
$ cmd.exe /c code.cmd --version | head -n 1
1.32.3
$ # edit and save the file after Code launches and inotifywait is live
$ cmd.exe /c code.cmd -n ./item.txt
$ inotifywait -m ./item.txt    
Setting up watches.
Watches established.
./item.txt MODIFY
./item.txt ATTRIB
./item.txt MODIFY
./item.txt ATTRIB
```

Seems to take.

**Comment by neilbalch** [comment]
Wait, what? Since when can I not access `/home/neil`? I opened the file alright; no problems there. It even saved the file! What do you mean by:

>  you can't access /home/neil from Windows VS Code.

**Comment by SvenGroot** [comment]
Accessing Linux files from Windows directly is not supported, since Windows editors will not correctly deal with metadata and we also apply caching which will become inconsistent if you edit files from Windows.

In 1903, you'll be able to access these files using \\\\wsl$\\<distro_name>, which is supported and your scenario should work then (though file change notifications in the other direction—Windows getting notified of a file modified in Linux—do not currently work).

**Comment by therealkenc** [comment]
^--- I don't _think_ he's end-running for what it is worth (I was giving the benefit of the doubt that would have been mentioned). But yeah.... There just isn't anything to add to this one.
