### ISSUE TITLE
How to restore original packages for Ubuntu 18.04

### ISSUE THREAD

**Issue by charlotte44yu** [Microsoft/WSL#3952]
Microsoft Windows [Version 10.0.17134.648]
Ubuntu 18.04 bionic from Win store

After installation, I did the "update & upgrade" for packages. But when I tried to install AFNI and SUMA, it turned out that a lot of needed shared libaries were gone. It is hard to install all the lost libaries one by one.
How can I restore the packages to the original ones (while keeping AFNI and SUMA)?

**Comment by therealkenc** [comment]
Ubuntu forums are [here](https://ubuntuforums.org/). They will probably want to know what a AFNI and a SUMA are when you post.
