### ISSUE TITLE
Odd make failure ` can't find lib.dll`

### ISSUE THREAD

**Issue by musm** [Microsoft/WSL#3953]
I'm trying to cross compile  `XC_HOST=x86_64-w64-mingw32`  from a WSL distribution. Running make leads to a mysterious error `Makefile:242: *** can't find lib.dll.  Stop.` 

I don't have any issues running a cross compile form, say, Cygwin.

**Comment by therealkenc** [comment]
This is a error from userspace and not WSL actionable. You'll get better answers (and if you are lucky maybe even a correct one) in a forum dedicated to cross compiling on Linux.
