### ISSUE TITLE
wslpath output not correct  for ramdisk drive

### ISSUE THREAD

**Issue by wangdingwei** [microsoft/WSL#3955]
**Please fill out the below information:**
* Microsoft Windows [版本 10.0.17763.379]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

wslpath output not correct 
```
$ wslpath -w -a test
\Device\ImDisk0\test
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          476G   47G  429G  10% /
none            476G   47G  429G  10% /dev
none            476G   47G  429G  10% /run
none            476G   47G  429G  10% /run/lock
none            476G   47G  429G  10% /run/shm
none            476G   47G  429G  10% /run/user
C:              476G   47G  429G  10% /c
O:              954G  4.7G  950G   1% /o
X:              128M   45M   84M  35% /x
```

the correct result should be: X:\test

X: drive is a ramdisk created by  ImDisk

**Comment by LightMelodies** [comment]
I have had similar trouble. #3588 , Some operation failed when dealing with ramdisk, The reason may be that ImDisk emulates disk volumes rather than complete disks,  as mentioned by the author in [Imdisk](http://www.ltr-data.se/opencode.html/#ImDisk). Full disk emulation like Arsenal Image Mounter should work. The strategy I finally choose is to use a vhdx and the Unified Write Filter (UWF) to emulate ramdisk.

**Comment by therealkenc** [comment]
Yeah, it is going to be the "same". From #3588:

> Maybe it is just a badly formed filter driver, which is spiritually dupe other issues.

I'll hold this open, but the hard fact is WSL doesn't support all third-party IFS, and [quoth](https://github.com/Microsoft/WSL/issues/1954#issuecomment-311139334) "it's unlikely [the devs] will get to all of them". The constructive path forward is to contact the purveyors of Imdisk and let them know about the problem, and they can in turn contact MSFT directly with questions if they have any. Which they probably won't need to do, once they take a look at the fail.

**Comment by 0xbadfca11** [comment]
Maybe fixed at build 18252?
![image](https://user-images.githubusercontent.com/7390559/55665233-b3f3df00-5876-11e9-8c9c-b918af19ed29.png)
> - Allow path translation on volumes without a volume GUID.
> https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18252-skip-ahead

**Comment by therealkenc** [comment]
> Maybe fixed at build 18252?

Chalking external for lack. There isn't any identifiable reason 17763 -> 18252 would address the OP. But if it was an unidentified WSL change, guess it would be fixedin1909.

**Comment by mehrdadn** [comment]
### For those still facing this issue in 1909:

Make your drive Fixed and not Removable.

WSL doesn't seem to like removable drives.
