### ISSUE TITLE
Can't change MTU

### ISSUE THREAD

**Issue by JiaChen-Zeng** [microsoft/WSL#3957]
* Your Windows build number:  `Microsoft Windows [Version 10.0.17763.379]`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```
shinoka:/mnt/c/Users/mid1886$ ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.191.16.107  netmask 255.255.255.0  broadcast 10.191.16.255
        inet6 fe80::151c:9ca1:45ee:a0e5  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 54:bf:64:8a:ec:4c  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

shinoka:/mnt/c/Users/mid1886$ sudo ifconfig eth0 mtu 1000
[sudo] password for shinoka:
shinoka:/mnt/c/Users/mid1886$ ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.191.16.107  netmask 255.255.255.0  broadcast 10.191.16.255
        inet6 fe80::151c:9ca1:45ee:a0e5  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 54:bf:64:8a:ec:4c  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

* What's wrong / what should be happening instead:

MTU should be set to 1000, but it doesn't changed.

* Strace of the failing command, if applicable: https://ideone.com/6L6rlc (Sorry I can't use gist)

**Comment by therealkenc** [comment]
Looks stubbed.
```
ioctl(3, SIOCSIFMTU, {ifr_name="eth0", ifr_mtu=1000}) = 0
```

Use [`netsh.exe`](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-contexts) and [interop](https://docs.microsoft.com/en-us/windows/wsl/interop) as a work-around.

Legit enough ask, although it is real close in spirit to #1930. WSL has limited support for low-level networking, and enumerating all the things [`ifconfig(8)`](http://man7.org/linux/man-pages/man8/ifconfig.8.html) and [`ip(1)`](http://man7.org/linux/man-pages/man8/ip.8.html) _can't_ do one submission at a time would get repetitious fast (ref #1809).

If you can describe your use case rough detail it will probably help prioritize. Me I'd take the work-around.

**Comment by Sh1noka** [comment]
Thank you for your reply.

I have a problem that if I `cat` a large file over ssh, ssh will freeze. Also commands like `vi` works abnormally. It is exactly like [this question](https://serverfault.com/questions/137951/ssh-traffic-over-openvpn-connection-freezes-when-i-cat-a-file). It seems that changing MTU will fix this problem.

I also tried change MTU using `netsh` on the Windows side. 

```cmd
netsh interface ipv4 set subinterface "イーサネット" mtu=1000 store=persistent
```

This can normally change the network interface on the Windows side. However, when I run `ifconfig`, it still shows the MTU unchanged.

**Comment by therealkenc** [comment]
> It is exactly like this [question](https://serverfault.com/questions/137951/ssh-traffic-over-openvpn-connection-freezes-when-i-cat-a-file). 

Good cite; appreciate you sharing, thanks.

> netsh didn't affect WSL's network settings.

Tried your `netsh` repro. Yeah, laugh. If you look at the MTU ifconfig`(8) on WSL reports for interface `lo` (loopback) it says `1500` too. It isn't. A loopback MTU would be higher (Windows claims 4294967295). 

Pretty sure your MTU changed fine, and that `1500` is just hard-coded in WSL. Which is to say, writing the MTU is stubbed, and reading the MTU is stubbed too, seems. Don't sweat that though. It Windows says it is 1000, it is 1000. There is no "WSL's network settings". WSL doesn't have a ipv4 stack; it is all Windows.

**Comment by Droggelbecher** [comment]
For me this seems to be an actual problem:
If I set the MTU on windows side to 1000 and ping (with fragmentation allowed) from within WSL with packet sizes between 1000 and 1500, packets silently get lost (whereas native windows ping fragemnts them correctly).

I have the feeling this might be the cause for some very annoying networking problems i'm having from within WSL (eg can't push to github for weeks!).

Am I understanding correctly that the cause is that the client side applications see the wrong MTU and don't fragment correctly on their end?
Is there any workaround?
I.e. any way to make the WSL see a different value for MTU than the hardcoded 1500?

**Comment by Sh1noka** [comment]
I tried to set MTU to a very low value like 700. However, ssh still freezes. If MTU is actually changed, then I don't know what to do to fix my problem...

**Comment by therealkenc** [comment]
> If MTU is actually changed, then I don't know what to do to fix my problem...

That part I can't help you with much. That serverfault link is great on its own merits, but there is no real way to tell if (a) MTU is really the problem even if the symptom is the same and (b) even if it is, whether changing the MTU is some kind of universal solution to "the problem" isn't certain. I am not even sure _what_, _precisely_ (in specific detail), what is causing the ssh connection over a OpenVPN tunnel to hang in the first instance. [I do `ssh` on WSL over (Windows) OpenVPN all the time without workarounds; but then me telling you that doesn't help _you_ any, does it.]

We can chase the rabbit for a bit if you want, but given I won't be able to reproduce the problem on my side we're pretty limited for options here. First, when it hangs, try resizing the window -- which is #2138. Yes, nutty, and yes, long shot. But I've seen it unstick stuck connections first-hand so it is worth a try.

Next, see if you can reproduce your scenario _as closely as humanly possible_ with a win32 `ssh`. You can try [MSFT's new(ish) OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview). You can also try [Cygwin's](https://www.cygwin.com/). The Linux version and the win32 ports are all largely (read: entirely) the same source under the hood. If the exact same scenario _doesn't hang_, then at you you have a kludgy work-around, and we learn something. If the win32 `ssh` _also hangs_, then at least we learn it isn't a WSL thing.

**Comment by turtlemonvh** [comment]
This may deserve a new issue, but it's related and the ticket is still open.

I ran into an issue where the MTU of the vEthernet interface for WSL didn't update when I joined a VPN. This led me to look for  way to persist MTU settings across restarts](https://askubuntu.com/questions/1127497/how-can-i-change-mtu-size-permanently/1283819#1283819), which worked when using @M-Azuma's command ([above](https://github.com/microsoft/WSL/issues/3957#issuecomment-479343268)).

Should I expect interface MTU to change automatically? (i.e. is this a bug?)

If not, is the a recommended way for me to detect the changed MTU settings in the guest when the network changes and adjust setting accordingly?

**Comment by therealkenc** [comment]
> This may deserve a new issue, but it's related and the ticket is still open.

This one can serve as the landing zone, to the extent the OP ask (which is changing the MTU) is still open on WSL2. In a more perfect world one could imagine the vEthernet MTU changes flowing in both directions, at least in principle. What this issue needs most is a big like count (more than a new issue).

**Comment by JamesKehr** [comment]
From a technical TCP/IP standpoint this sort of behavior is expected unless something in between tells a side that the MTU is wrong. The ICMP "needs fragmentation" message can trigger corrective behavior *if* the message is enabled and not dropped. Which in most cases it is not sent or is dropped because security people don't like ICMP.

The best option, in my opinion, is to enable MSS clamping if the VPN product supports the option. MSS clamping was made for exactly this situation and most major VPN products should have support.

When MSS clamping is enabled the VPN server enforces a maximum MTU size by altering the MSS option in the TCP header during the handshake. This option should fix the issue without requiring intervention on any OS.

Options like using the netsh command or running a script/command that changes the MTU or enables tcp_mtu_probing on the WSL2 distro can be used when MSS clamping is not available.
