### ISSUE TITLE
Windows 10 subsystem Ubuntu 16.04 and Ubuntu 18.04 installation docker can't run! Report an error

### ISSUE THREAD

**Issue by thousmile** [Microsoft/WSL#3958]
Windows 10 subsystem Ubuntu 16.04 and Ubuntu 18.04 installation docker can't run! Report an error
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by therealkenc** [comment]
#2291 #2527
