### ISSUE TITLE
OpenSUSE 15 and SLES 15 won't open due to missing api-ms-win-core-console-l2-2-0.dll

### ISSUE THREAD

**Issue by Dxvid** [microsoft/WSL#3959]
Windows build number:
Microsoft Windows [Version 10.0.16299.1004]

What you're doing, what's happening, and what's wrong:
I installed SLES 15 and OpenSUSE 15 from the Microsoft store. 
I get a message that api-ms-win-core-console-l2-2-0.dll is missing and it's impossible to open OpenSUSE 15 or SUSE Linux Enterprise Server 15.

Comments:
Let me know if you want logs. I'm not giving logs as this is a duplicate of what happened to Ubuntu a few months back, so the cause of the problem should be known.

Ubuntu and SLES 12 work fine on my machine.
I haven't tested all Linux distros from the store yet.

**Comment by Biswa96** [comment]
Update Windows 10 version. Use `wsl.exe` or `bash.exe` (deprecated) to run that distribution. `wslconfig.exe /l` can show the distribution name.

**Comment by Dxvid** [comment]
Thanks Biswa96 for trying to help me, but I'm on a corporate computer and can't upgrade windows or do any custom solutions not permitted by the IT department.

SLES 15 or OpenSUSE 15 don't show in the list when doing `wslconfig.exe /l` only the ones working show up there.

Anyway I don't want help, I just wanted to help by reporting a bug so the people maintaining the SLES/OpenSUSE 15 for WSL can fix the bug.

Using  SLES 12 or OpenSUSE 42 is good enough for me. I can also use Hyper-V for setting up real virtual machines with version 15 if I need it later.

**Comment by benhillis** [comment]
I'm following up with our Suse partners to see if they can resolve this.

**Comment by neodino** [comment]
Any news!

**Comment by benhillis** [comment]
This was resolved some time ago.
