### ISSUE TITLE
`root` user's home directory not accessed with neither `~` nor `$HOME`

### ISSUE THREAD

**Issue by tukusejssirs** [Microsoft/WSL#3961]
When I run WSL (auto-logged in as regular user) and run `sudo -s` to log in as `root` user, the following commands enter the `/home/$USER` (where `$USER` is the aforementioned regular user):

```bash
cd ~
cd $HOME
```

When I check these variables content using `echo`, it outputs regular user's home directory:

```bash
echo ~
/home/$USER
echo $HOME
/home/$USER
```

Home directory for the `root` user should be (by default) in `/root`.

Note that I wanted to change the `root` user's home directory in the `/etc/passwd` file (as it is written [here](https://superuser.com/a/1134645/412152)), however, it already is set correctly there:

```bash
head -1 /etc/passwd
root:x:0:0:root:/root:/bin/bash
```

Microsoft Windows [Version 10.0.17763.379]

**Comment by benhillis** [comment]
I get the same behavior on native Ubuntu.

**Comment by therealkenc** [comment]
> run sudo -s to log in as root user

`sudo -s` does not "log [you] in" as root user.

> When I check these variables content using echo, it outputs regular user's home directory:

This is linux-behavior. `sudo -s` is the equivalent to `sudo -s /bin/bash`, which spawns the a new `bash` process with a different UID/GID, and that new process inherits the same environment as the process that called it. 

You probably want `su(8)`.
