### ISSUE TITLE
looks like WSL does not support named pipes yet? dbus suffers and other apps do unless i force other forms of IPC!

### ISSUE THREAD

**Issue by petersvp** [Microsoft/WSL#3962]
**Please fill out the below information:**
* Microsoft Windows [Version 10.0.17134.648]

* What you're doing and what's happening:  
Trying to create named pipes with mkfifo seems to be not implemented:

* What's wrong / what should be happening instead:
tipyng   mkfifo test in bash gives error: Operation not permitted

* Strace of the failing command
 strace -o test.strace -f mkfifo test
https://gist.github.com/petersvp/c8ecd306956db3b54c449c7806acf643

**Comment by therealkenc** [comment]
WSL supports named pipes. If I had to guess (and I do, for lack of repro) you have done that `mkfifo` command with a relative path of `./test` on DrvFs mounted without [metadata enabled](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/) (which is the default).
```
$ cd ~ && sudo umount /mnt/c
$ sudo mount -t drvfs C:\\ /mnt/c -o metadata
$ cd $(wslpath C:\\) && cd $(wslpath $(cmd.exe /c "echo %USERPROFILE%") | tr -d '\r')
$ mkdir ./pipetest && cd ./pipetest
$ strace -o test.strace -f mkfifo ./test
```
