### ISSUE TITLE
Odd care behavior same as issue #1436

### ISSUE THREAD

**Issue by avielc** [Microsoft/WSL#3965]
I'm still suffering from that case, 
the only workaround i managed to help me was `export TERM=eterm-color` 
i'm on 1809 and still suffers from that. `xterm-256color` doesn't seem to cut to it
Here is an example of how it looks like on my windows 10 1809 17763.253
connecting to centos 7.6.1810
![xterm issue](https://user-images.githubusercontent.com/13572969/55680973-9f245380-5929-11e9-991e-aa99f3d5b980.gif) 

I do have to point out this didn't happen on Debian system i sshed into. 
So something to do with centos<->wsl

I tried to update the terminfo according to the wget command, but it didn't help
the only solution was changing TERM variable

Would love to hear anyone's thoughts or help about it. 
Thanks

_Originally posted by @avielc in https://github.com/Microsoft/WSL/issues/1436#issuecomment-480570997_

**Comment by Biswa96** [comment]
Does this happen in Command Prompt? You are using Cmder.

**Comment by therealkenc** [comment]
[this](https://github.com/Microsoft/WSL/issues/1436#issuecomment-391168513)

**Comment by avielc** [comment]
@Biswa96  yes, it happens if i open bash as well, or command prompt.
@therealkenc - why did you close it mate? 
I tried adding my post on there, but the issue won't open. 
It is an issue after all.

**Comment by therealkenc** [comment]
> why did you close it mate?

In the [link](https://github.com/Microsoft/WSL/issues/1436#issuecomment-391168513) provided, to the issue you cited.

> If you have further asks/issues, please file new issues on our [Console GitHub Repo.](https://github.com/microsoft/console/issues)

This was also noted in the issue [template](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md), which you deleted.

> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).
