### ISSUE TITLE
Bash on Windows screen flashes on briefly then disappears

### ISSUE THREAD

**Issue by makdaddy8888** [microsoft/WSL#3969]
I have installed Bash on Windows using the Turn Windows features on or off.
I selected Windows Subsystem for Linux
restarted
I am using windows 10 pro 1809 v17763.437
help

@makdaddy

**Comment by benhillis** [comment]
Could you please collect [log files](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)?
