### ISSUE TITLE
Substitution of exe commands in tmux session not working as expected

### ISSUE THREAD

**Issue by shamakhov** [microsoft/WSL#3970]
Windows build number:  Microsoft Windows [Version 10.0.17763.437]
I have two distributions:
```cmd
>wslconfig /l
Windows Subsystem for Linux Distributions:
Legacy (Default)
Ubuntu
```
Using Legacy distribution (which I installed about year and half ago, DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS") I get:
```bash
$ tmux
$ echo $(cmd.exe /c echo Hello)
Hello
$
```

Using Ubuntu distribution installed from Microsoft Store (DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS") I get:
```bash
$ tmux
$ echo $(cmd.exe /c echo Hello)

$
```
Not sure if a problem is in WSL, because without starting tmux session everything works fine.

**Comment by WSLUser** [comment]
There are sporadic issues between using Legacy edition and Store version. Legacy is not intended to be used. Uninstall it, reboot, and try again. If there's still an issue, provide an update though this may end up going to the Console issue page.

**Comment by shamakhov** [comment]
Looks like it was some kind of problem with Ubuntu 18.04 installation. Reinstalled it and now substitution works fine. Thanks!
