### ISSUE TITLE
Running LXD in WSL?

### ISSUE THREAD

**Issue by rayj00** [microsoft/WSL#3971]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

**Microsoft Windows [Version 10.0.17763.437]**

ray@LAPTOP-JNA8O7S4:/mnt/c/Users/rayj0$ **lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
ray@LAPTOP-JNA8O7S4:/mnt/c/Users/rayj0$

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

ray@LAPTOP-JNA8O7S4:/mnt/c/Users/rayj0$ **sudo service lxd start**
[sudo] password for ray:
Starting Container hypervisor based on LXC: lxd.
Error: LXD still not running after 600s timeout (Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: no such file or directory)
ray@LAPTOP-JNA8O7S4:/mnt/c/Users/rayj0$

* What's wrong / what should be happening instead:
  LXD should be running.  It does not start up?

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
The WSL bionic dode not have the logman command
Would running Ubuntu 16.04 be the better choice?

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
This can be a landing zone I guess, but the ask is spiritually dupe a combination of Venn diagram of #2374 #2291 #994, and the ever popular #412. No `strace(1)` log provided natch. If you had, you would hit the first of a few blockers. As a starting point you can upvote UserVoice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl), [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl), [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/18019348-lxc-cgroups-support), [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16571479-support-for-running-systemd) plus some lesser others not worth citing.

**Comment by rayj00** [comment]
I would really like to run LXD on WSL. Please don't suggest HyperV or vBox. I am working on an application that uses LXD on my VPS under Ubuntu 16.04 and I can at least run LXD and create containers. On WSL, I can't do squat as LXD will not start because of that systemd issue! Please fix!
