### ISSUE TITLE
Can't play Minecraft on WSL through VNC

### ISSUE THREAD

**Issue by joehays** [Microsoft/WSL#3973]
I'm trying to play the game of Minecraft on my Chromebook through a VNC connection to WSL running on my Windows 10 machine. Basically, I have two licenses of Minecraft and two computers but one is a Chromebook (which can't install Minecraft). So, for my son and I to play together I wanted to try and have one of us play through a VNC connection to WSL. Performance once be the best but it will hopefully be playable... 

**System:**
- Microsoft Windows [Version 10.0.17134.706]
- WSL == Ubuntu 18.04.2 LTS installed on WSL.
- I have tightvncserver installed and configured in Ubuntu.
- VNC client (on Windows 10 desktop) == UltraVNC and TightVNC (both have the same problem)

From my Windows 10 desktop and from the Chromebook I can successfully connect to the running VNC server on WLS. I've tested with both XFCE and Gnome desktops and they both connect just fine. I can successfully launch the Minecraft launcher (version 1.13). However, when I press PLAY a new window comes up saying the game has crashed. 

All combinations of XFCE/Gnome desktops and UltraVNC/TightVNC have the same crash behavior.

I don't know if this is a Minecraft or a WSL issue. I suspect WSL so I'm starting here.

Thanks for the help in advance.

Here are the terminal stderr output and Minecraft crash-reports:
[terminal.txt](https://github.com/Microsoft/WSL/files/3076794/terminal.txt)
[crash-2019-04-13_21.03.30-client.txt](https://github.com/Microsoft/WSL/files/3076795/crash-2019-04-13_21.03.30-client.txt)

**Comment by therealkenc** [comment]
ref #637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799)).
