### ISSUE TITLE
Impossible to set default user of distribution installed via wsl --import on 1903

### ISSUE THREAD

**Issue by BtbN** [microsoft/WSL#3974]
Windows Version 10.0.18362.30 (1903)

The only way that's left to set the default user of a distribution is via its command line utility (ubuntu.exe for example).
However, for Distributions installed via "wsl --import", no such command exists.

Since lxrun does not exist anymore, there appears to be no way to change the default user.

I tried manually setting it via WslConfigureDistribution from wslapi.dll, but all I'm getting back is an Access Denied error code.

Edit:
I found the relevant registry key at
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{MY-UUID}`
Where I could set DefaultUid to the desired value.
Still, there should be a command for this in wsl.exe or at least somewhere at all.

**Comment by therealkenc** [comment]
> I found the relevant registry key at
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{MY-UUID}

`...\Lxss\{DISTRO-UUID}\DefaultUid`, yes.

> Still, there should be a command for this in wsl.exe or at least somewhere at all.

Probably. To the extent these registry entries continue to exist under the present WSL model, anyway. Or, to the extent `--export` isn't bundling up (and `--import` isn't restoring) everything `PackageFamilyName` related including the [launcher](https://github.com/Microsoft/WSL-DistroLauncher).

So I guess a concrete ask would be for something like:
```
wsl.exe --setdefaultuid DistributionName uid
```
Fair enough. Someone motivated could probably do a short powershell script to that effect.

[As an aside, `wsl.exe` doesn't know where mnemonic usernames live, since (1) there is no basis on which to assume `/usr/bin/id` [exists](https://github.com/Microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistributionInfo.cpp#L44), (2) a distribution might be inclined to store their usernames in `/config/credentials.json` instead of `/etc/passwd` or maybe in the cloud, and (3) a distribution might not have mnemonic usernames at all.]

**Comment by hermanocabral** [comment]
I had the same issue after importing Ubuntu 18.04 and until the import/export is fixed (IMHO the problem lies there) you can use the LxRunOffline tool to set the default user:

`LxRunOffline.exe set-uid -n Name_of_Distro -v user_UID`

**Comment by KaOzPoNs** [comment]
Hi there! I think that I found the solution for this...

As BtbN said, the relevant registry key must be changed...
If you don't want to install LxRunOffline or some other tool...  I can do the job with this command in the PowerShell:
 
Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName | Where-Object -Property DistributionName -eq <UbuntuCustom> | Set-ItemProperty -Name DefaultUid -Value 1000

Where <UbuntuCustom> is the name of the distribution (while using wsl --Import ).
and the "- Value 1000" is the Uid of the user that you want to change.

Note: To find the Uid just write "cat /etc/passwd | grep <UserName>" 

For example: cat /etc/passwd | grep Bob
Result: Bob:x:1000:1000 Bob

That 1000 is the Uid

I hope this help to someone.

**Comment by merkuriy** [comment]
Thanks to @KaOzPoNs for the proposed manual method! Next, my additions.

Get UID value by specific distro and user.
```bash
wsl -d <DistroName> -u <UserName> -e id -u
```
---

My PowerSheell function `WSL-SetDefaultUser <DistroName> <UserName>`:
```bash
Function WSL-SetDefaultUser ($distro, $user) { Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName | Where-Object -Property DistributionName -eq $distro | Set-ItemProperty -Name DefaultUid -Value ([int] ((wsl -d $distro -u merkuriy -e id -u) | Out-String)); };
```

Example using:
```bash
WSL-SetDefaultUser ubuntu-19-04-server merkuriy;
```

Remove function:
```
Remove-Item Function:WSL-SetDefaultUser;
```

---

Single line with call and remove function.
```bash
Function WSL-SetDefaultUser ($distro, $user) { Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName | Where-Object -Property DistributionName -eq $distro | Set-ItemProperty -Name DefaultUid -Value ([int] ((wsl -d $distro -u merkuriy -e id -u) | Out-String)); }; WSL-SetDefaultUser <DistroName> <UserName>; Remove-Item Function:WSL-SetDefaultUser;
```
Replace <DistroName> and <UserName> inserts at the end of the command.

**Comment by anaisbetts** [comment]
imho this should be moved into `wsl.exe`, it's the only configuration option where you still have to use DistroLauncher (or manually hack the registry)

**Comment by thisguychris** [comment]
As of [build no. 1890](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980) 

You can set the default user via editing `/etc/wsl.conf`.

```ini
[user]
default=username
```

No need for registry hacks or DistroLauncher anymore.

I believe @BtbN / @therealkenc we can close this now. 🙏🏻

**Comment by BtbN** [comment]
Looks great to me!

**Comment by therealkenc** [comment]
Call it fixedinsiders; it was a legit feature request just never got categorized as such.

**Comment by shinji257** [comment]
This is an old thread but I'm surprised that for changing the default user no one ever thought about `ubuntu config --default-user username`.  This still works even with WSL 2.

**Comment by BtbN** [comment]
Very first sentence of the report:

> The only way that's left to set the default user of a distribution is via its command line utility (ubuntu.exe for example).
> However, for Distributions installed via "wsl --import", no such command exists.

**Comment by ArthurYdalgo** [comment]
> Thanks to @KaOzPoNs for the proposed manual method! Next, my additions.
> 
> Get UID value by specific distro and user.
> 
> ```shell
> wsl -d <DistroName> -u <UserName> -e id -u
> ```
> 
> ### Command WSL-SetDefaultUser
> My PowerSheell function for set default user by distro name and user name. It works both for official distributions (from the MS Store), and for any custom distros.
> 
> ```shell
> Function WSL-SetDefaultUser ($distro, $user) { Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName | Where-Object -Property DistributionName -eq $distro | Set-ItemProperty -Name DefaultUid -Value ((wsl -d $distro -u $user -e id -u) | Out-String); };
> ```
> 
> Using:
> 
> ```shell
> WSL-SetDefaultUser <DistroName> <UserName>
> ```
> 
> Example using:
> 
> ```
> WSL-SetDefaultUser ubuntu-19-04-server merkuriy
> ```
> 
> Remove function:
> 
> ```
> Remove-Item Function:WSL-SetDefaultUser
> ```
> 
> ### Single-line command with call and remove function
> ```shell
> Function WSL-SetDefaultUser ($distro="<DistroName>", $user="<UserName>") { Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName | Where-Object -Property DistributionName -eq $distro | Set-ItemProperty -Name DefaultUid -Value ((wsl -d $distro -u $user -e id -u) | Out-String); }; WSL-SetDefaultUser; Remove-Item Function:WSL-SetDefaultUser;
> ```
> 
> Replace `<DistroName>` and `<UserName>` inserts at the begin of the command.

You just saved my day, sir

**Comment by alan23273850** [comment]
> As of [build no. 18980](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980)
> 
> You can set the default user via editing `/etc/wsl.conf`.
> 
> ```ini
> [user]
> default=username
> ```
> 
> No need for registry hacks or DistroLauncher anymore.
> 
> I believe @BtbN / @therealkenc we can close this now. 🙏🏻

This solution also works for me! Thank @thisguychris very much!

**Comment by data-pata** [comment]
[https://github.com/microsoft/WSL/issues/3974#issuecomment-636375135](Merkuriy and KaOzPoNz solution) worked but not: 

> > As of [build no. 18980](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980)
> > You can set the default user via editing `/etc/wsl.conf`.
> > ```ini
> > [user]
> > default=username
> > ```
> > 
> > 
> > No need for registry hacks or DistroLauncher anymore.
> > I believe @BtbN / @therealkenc we can close this now. 🙏🏻
> 
> This solution also works for me! Thank @thisguychris very much!

**Comment by kre75rub** [comment]
> 
> 
> > As of [build no. 18980](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980)
> > You can set the default user via editing `/etc/wsl.conf`.
> > ```ini
> > [user]
> > default=username
> > ```
> > 
> > 
> > No need for registry hacks or DistroLauncher anymore.
> > I believe @BtbN / @therealkenc we can close this now. 🙏🏻
> 
> This solution also works for me! Thank @thisguychris very much!

Might be obvious but, to save some people a bit of headache, I want to point out, that it is important to --terminate the running distro, in order to have this work.

**Comment by richardso21** [comment]
> > As of [build no. 18980](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980)
> > You can set the default user via editing `/etc/wsl.conf`.
> > ```ini
> > [user]
> > default=username
> > ```
> > 
> > 
> > No need for registry hacks or DistroLauncher anymore.
> > I believe @BtbN / @therealkenc we can close this now. 🙏🏻
> 
> Might be obvious but, to save some people a bit of headache, I want to point out, that it is important to --terminate the running distro, in order to have this work.

Can confirm that running `wsl.exe --terminate <distro name>` resolved it for me. Or, you can wait out a few minutes.

**Comment by codeacade** [comment]
> This is an old thread but I'm surprised that for changing the default user no one ever thought about `ubuntu config --default-user username`. This still works even with WSL 2.

Actually for latest ubuntu versions this is `ubuntu[version] config --default-user user_name`
For example `ubuntu2004 config --default-user user_name`

(this command should be run from Windows level - CMD or PowerShell window)

**Comment by CompSciMaj13** [comment]
I ran into quite a few issues when converting from WSL 1 to WSL 2 that relates to this ticket. I detailed my environment and the journey I took to work around them in the following comment.

https://github.com/microsoft/WSL/issues/4102#issuecomment-673145649

**Comment by calbraz** [comment]
> ubuntu2004 config --default-user user_name

@codeacade, it seems the cleanest fix. I have tried @thisguychris solution, which has worked, once you terminate wsl. This was also described in FAQ session that automates this operation: [https://github.com/pxlrbt/move-wsl](url)

BTW, @codeacade, if ran from Ubuntu shell, `ubuntu config` command is not a recognized command. Wonder why..

**Comment by benhillis** [comment]
@calbraz - it's not.

/etc/wsl.conf
```
[user]
default=username
```
