### ISSUE TITLE
bluez emulator not suppoted in WSL [AF_ALG], EAFNOSUPPORT (Address family not supported by protocol)

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/WSL#3975]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt): `Microsoft Windows [Version 10.0.18875.1000]`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

`EAFNOSUPPORT` error when trying to create [`AF_ALG`] socket:

Setting up repo:
```sh
$ sudo apt update 
$ sudo apt install -y git autotools-dev automake m4 libtool libglib2.0-dev libdbus-1-dev libdw-dev libudev-dev libjson-c-dev libreadline-dev
```
``` sh
$ git clone git://git.kernel.org/pub/scm/libs/ell/ell.git && cd ell && git checkout -b 0.17 0.17 \
&& ./bootstrap-configure --prefix=/usr \
&& make && sudo make install && cd ..
```
``` sh
$ git clone git://git.kernel.org/pub/scm/bluetooth/bluez.git \
&& cd bluez && git checkout -b 5.50 5.50 \
&& ./bootstrap-configure --prefix=/usr \
    --disable-cups --disable-a2dp --disable-avrcp \
    --disable-network --disable-hid --disable-hog \
    --disable-android --disable-midi --disable-obex \
    --enable-testing --enable-experimental --enable-debug \
&& sed -i 's/-Werror//g' acinclude.m4 \
&& make
```
``` sh
$ cd emulator
$ sudo touch /dev/vhci
$ sudo strace -o btvirt.strace -f ./btvirt -l 2
Bluetooth emulator ver 5.50
Failed to open Virtual HCI device

```

* What's wrong / what should be happening instead:
1. Error:
```log
socket(AF_ALG, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = -1 EAFNOSUPPORT (Address family not supported by protocol)

```
2. Expected is: above command should be successful.

* Strace of the failing command: [btvirt.strace](https://gist.github.com/n3rd4i/fe6749c28db3260c437147c4ffb74737)

**Comment by n3rd4i** [comment]
probably will not be implemented in wsl1, maybe wsl2 has this working

**Comment by ivan2angelov** [comment]
I have WSL2 with [bluez from master ](https://github.com/bluez/bluez) #2e4627c3c92ed823cb976b0a48d5463c2b187fec and I have exactly same problem - I cannot get BlueZ working in WSL2. Why 2 years and nobody made an effort to fix it?

` sudo strace -o btvrit.strace -f ./btvirt -l 2
Bluetooth emulator ver 5.63
Failed to open Virtual HCI device
==284==LeakSanitizer has encountered a fatal error.
==284==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==284==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)`

**Comment by vChavezB** [comment]
I think you need to compile the WSL2 kernel with CONFIG_BT_HCIVHCI

https://github.com/dorssel/usbipd-win/wiki/WSL-support#building-your-own-usbip-enabled-wsl-2-kernel

**Comment by wxj7king** [comment]
For people who are still concerned about this issue, opening these kernel configs would solve this problem:

```
CONFIG_CRYPTO_USER_API=y
CONFIG_CRYPTO_USER_API_HASH=y
CONFIG_CRYPTO_USER_API_SKCIPHER=y
CONFIG_CRYPTO_USER_API_RNG=y
CONFIG_CRYPTO_USER_API_AEAD=y
CONFIG_CRYPTO_USER_API_ENABLE_OBSOLETE=y
CONFIG_CRYPTO_STATS=y
```
