### ISSUE TITLE
Enabling WSL causes Ethernet connection to be disabled

### ISSUE THREAD

**Issue by Firebeam** [microsoft/WSL#3981]
* Your Windows build number: [10.0.17763.437]

* What you're doing and what's happening:  I've enabled WSL with both the Powershell as admin method and the Windows features method. After restarting, my Ethernet connection icon shows a red X as if I had disconnected a cable. Trying to repair the connection does nothing (it reports that there's probably a driver issue). The only option is to roll back WSL and restart.

* What's wrong / what should be happening instead: WSL enabling should not mess Ethernet connections.

**Comment by firdacz** [comment]
Just happened to me, had to re-enable IPv4 and most stuff in properties of the adapter which got disabled by enabling WSL and restarting.
