### ISSUE TITLE
Qutebrowser "shared memfd open() failed: Function not implemented"

### ISSUE THREAD

**Issue by FaithLV** [Microsoft/WSL#3982]
* Your Windows build number:  _Microsoft Windows [Version 10.0.17134.706]_

* What you're doing and what's happening: _Launching qutebrowser after having run_ [`sudo strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5`](https://superuser.com/questions/1347723/arch-on-wsl-libqt5core-so-5-not-found-despite-being-installed)

* What's wrong / what should be happening instead: Qutebrowser should launch, instead it crashes

* Strace of the failing command: https://gist.github.com/FaithLV/bd278ef498d0f2b6b3b680801d5ef8df

Crash output: https://gist.github.com/FaithLV/8befcb1ca30b5332e72bb9d9c75341f8

For context, running Arch WSL with _Kernel: 4.4.0-17134-Microsoft_

**Comment by therealkenc** [comment]
The error cited is #3542. Duping you over there, but I doubt that's the actual fatal. 

```
571   memfd_create("pulseaudio", MFD_ALLOW_SEALING <unfinished ...>
591   <... mprotect resumed>)           = 0
571   <... memfd_create resumed>)       = -1 ENOSYS (Function not implemented)
591   mprotect(0x7f21241b0000, 12288, PROT_READ|PROT_WRITE <unfinished ...>
571   write(2, "shared memfd open() failed: Func"..., 53 <unfinished ...>
```
