### ISSUE TITLE
Enter tmux would reset console font .

### ISSUE THREAD

**Issue by eromoe** [Microsoft/WSL#3988]
* Your Windows build number: windows 10 1809

1. I set a powerline font `dejavu` in ubuntu 18.04 shell 
2. quit ubuntu bash and re-enter 
3. the font setting is keeped 
4. vim powerline theme worked very well
    ![image](https://user-images.githubusercontent.com/3938751/56483200-f108d400-64fa-11e9-8aa4-7a34c36c4522.png)
5. enter tmux, its powerline theme was broken , font setting became `新宋体`
6. in tmux, enter vim , powerline theme became broken too .
    ![image](https://user-images.githubusercontent.com/3938751/56483194-e4847b80-64fa-11e9-88ab-75da9667f3b6.png)
7. quit tmux, the font setting return to `dejavu`

This is a weird behavior. 
Enter tmux would reset console font to default .

**Comment by therealkenc** [comment]
ref tangential #2050

**Comment by bookyue** [comment]
1. Open regedit.
2. Find this. `HKEY_CURRENT_USER\Console\C:_Program Files_WindowsApps_CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc_ubuntu1804.exe` (you will not as the same as mine)
3. then, add CodePage（Type: DWORD, Value: 0x01b5).
It wokrs for me!

**Comment by rathboma** [comment]
I don't have a Ubuntu entry under HKEY_CURRENT_USER\Console, I'm using WSL2, is that different?

**Comment by marukaz** [comment]
I had the same issue in WSL2 and I found `HKEY_CURRENT_USER\Console` but adding the CodePage didn't work for me...

**Comment by matthewstrasiotto** [comment]
The following works, at least in the instance of sshing into WSL: 

https://github.com/wernight/powerline-web-fonts/issues/8#issuecomment-353081869

> In my case, it's because tmux wasnt using utf-8.
> 
> try
> 
> ```shell
> export LANG=en_US.UTF-8
> export LC_CTYPE=en_US.UTF-8
> ```
> 
> then start tmux,
> 
> or
> 
> ```shell
> tmux -u
> ```

**Comment by memo-off** [comment]
`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"FaceName"="Consolas"
"CodePage"=dword:0000fde9
`

**Comment by ddaversa** [comment]
All of the above did not work for me. To fix it, I simply went to

HKEY_CURRENT_USER\Console\C:_Program Files_**_ubuntu.exe

and added
FaceName (String) "Lucida Console"

Works for me now.

**Comment by praton1729** [comment]
In Linux just launching `tmux -u` worked for me.
