### ISSUE TITLE
tcpdump not work

### ISSUE THREAD

**Issue by dingrui37** [Microsoft/WSL#3989]
eric@SKY-20190404IXR:/mnt/c/Users/user$ sudo tcpdump -i eth0
tcpdump: socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Socket type not supported
eric@SKY-20190404IXR:/mnt/c/Users/user$

**Comment by dingrui37** [comment]
eric@SKY-20190404IXR:/mnt/c/Users/user$ ethtool eth0
Settings for eth0:
Cannot get device settings: Invalid argument
Cannot get wake-on-lan settings: Invalid argument
Cannot get message level: Invalid argument
Cannot get link status: Invalid argument
No data available

**Comment by dingrui37** [comment]
eric@SKY-20190404IXR:/mnt/d$ sar
Cannot open /var/log/sysstat/sa22: No such file or directory
Please check if data collecting is enabled
eric@SKY-20190404IXR:/mnt/d$ iostat
Cannot find disk data
eric@SKY-20190404IXR:/mnt/d$

**Comment by therealkenc** [comment]
#1515
