### ISSUE TITLE
Postgresql issues in start

### ISSUE THREAD

**Issue by MajidDehnamaki** [Microsoft/WSL#3991]
OS: Windows Server 2019
WSL Linux Distro: Ubuntu 

installed postgresql and tried to start with this command

`sudo service postgresql start`

and then see this error :

`could not flush dirty data: Function not implemented`

after google it set `fsync=off` in `postgresql.conf` and start again and see this error:

`replication checkpoint has wrong magic 0 instead of 307747550`
what should I do؟

**Comment by ajaykagrawal** [comment]
I was able to get Postgresql working on WSL by adding the following to postgresql.conf 

data_sync_retry = true

See https://www.postgresql.org/message-id/flat/CA%2BmCpegfOUph2U4ZADtQT16dfbkjjYNJL1bSTWErsazaFjQW9A%40mail.gmail.com

**Comment by MajidDehnamaki** [comment]
@ajaykagrawal no, it's not work

**Comment by ajaykagrawal** [comment]
This is interesting. It works for me. I am running PostgreSql 11.2 and I am on Windows version 1809. Note I only have data_sync_retry = true and do *not* have fsync = off

**Comment by MajidDehnamaki** [comment]
@ajaykagrawal that's work for windows but not in windows server

**Comment by MajidDehnamaki** [comment]
no one can help?

**Comment by karansinghgit** [comment]
@ajaykagrawal thanks a lot. that worked for me.

**Comment by therealkenc** [comment]
#3863 #645
