### ISSUE TITLE
wslpath.exe missing from Win10 1809 (and 1903)

### ISSUE THREAD

**Issue by biao-w** [Microsoft/WSL#3993]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.30]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

C:\Windows>wslpath
'wslpath' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows>dir wslpath.exe /s
 Volume in drive C has no label.
 Volume Serial Number is C2A4-2230
File Not Found

* What's wrong / what should be happening instead:
I expect wslpath.exe should exist on Windows (in additional to /usr/bin/wslpath)

**Comment by benhillis** [comment]
There is no wslpath.exe, you can invoke it from Windows by using:

`wsl.exe wslpath`

**Comment by eggbean** [comment]
> There is no wslpath.exe, you can invoke it from Windows by using:
> 
> `wsl.exe wslpath`

When you do that, which wsl distro is used? Always the default one?
