### ISSUE TITLE
Non specified error 0x80004005 

### ISSUE THREAD

**Issue by andypillip** [microsoft/WSL#4003]
Windows build number: 10.0.17134.706

I did the following
* Activate WSL Feature
* Restart
* Verify that WSL Feature is active
* Download Ubuntu 18.04 for WSL (aka.ms/…)
* Unzip contents to C:\Ubuntu
* cd Ubuntu
* ubuntu1804.exe

My group policies disabled Windows Store, that's why I download Linux manually.

Output:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Erreur non spÚcifiÚe

Press any key to continue...
```
[lxcore etl (zip)](https://github.com/Microsoft/WSL/files/3122573/lxcore.zip)

**Comment by tremblaysimon** [comment]
I get the same error and it seems to be related to antivirus software that is scanning the files while it's decompressing.

Ref.: https://appuals.com/solved-how-to-fix-error-0x80004005/

**Comment by hron84** [comment]
Is there any way to work it around if disabling AV is not a possibility?

**Comment by Boobies** [comment]
I'm getting this error outside of WSL, when I try to make a copy of my home directory using the Windows Explorer, for backup purposes.
