### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070005

### ISSUE THREAD

**Issue by amenlao** [microsoft/WSL#4004]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 ?????

**Comment by billziss-gh** [comment]
The 0x80070000 prefix means that this is a Windows error [see [HRESULT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0642cb2f-2075-4469-918c-4441e69c548a)]. Error 5 is `ERROR_ACCESS_DENIED`.

**Comment by ivy0709** [comment]
I have the same problem and solved by run cmd as administrator 
Win+X --> Windows PowerShell(A)

**Comment by stdedos** [comment]
_Others, also see https://github.com/microsoft/WSL/issues/3020#issuecomment-604589190_

**Comment by sailfish009** [comment]
can confirm, works ok with extracted ubuntu2004.exe and install.tar.gz, ubuntu2004.exe in root powershell

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by chengsu** [comment]
I turn "Developer Mode" on, and it solves the problem. May this can help.

**Comment by stdedos** [comment]
We are sorry MS, but we have other things to do than rollback our solutions, if after much pain we managed to get them working.

One of the issues is that paths must not contain spaces.

**Comment by dougwithseismic** [comment]
Fix ahead, praise the sun! https://github.com/microsoft/WSL/issues/3020#issuecomment-531579997
