### ISSUE TITLE
NTFS mounted files are intermittently inaccessible.

### ISSUE THREAD

**Issue by robiwano** [Microsoft/WSL#4009]
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.345]

* What you're doing and what's happening: Building Linux binaries from my C/C++ source code residing on a Windows mount (NTFS) using CMake/Ninja. Intermittently, files on /mnt/c/... are reported as not found during compiling ("No such file or directory"). Just reissuing the build command fixes this. This happens several times during a build (for different files). After reissuing the build command X times, the build completes successfully.

* What's wrong / what should be happening instead: All files on /mnt/c/... should be found instantly, and build should be completed without having to reissue the build command several times.

**Comment by Biswa96** [comment]
I would suggest to upgrade Windows 10 latest version and [mount the NTFS partitions](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/) with proper metadata enabled.

**Comment by therealkenc** [comment]
^--- Any idea the dupe#? I think you might have commented or even posted in the thread, but I can't find it in the 30 seconds I dedicated to the search.

Closing tag question for lack.
