### ISSUE TITLE
"ls -l" is not counting the number of sub-directories for a directory that has sub-directories

### ISSUE THREAD

**Issue by rowem** [Microsoft/WSL#4010]
* Windows build number:  
    Microsoft Windows [Version 10.0.17134.706]
    Running Ubuntu (Canonical group) Release Date: 10/7/2017

* What you're doing and what's happening:  
   
Using the "ls -l" command........

<my_pc_Name>:~ $ ls -l
total 0
-rw-rw-rw- 2 mhr mhr  95 Apr 12 17:31 1.txt
-rw-rw-rw- 2 mhr mhr  95 Apr 12 17:31 1_dup.txt
-rw-rw-rw- 1 mhr mhr   0 Apr 14 16:59 2.txt
-rw-rw-rw- 1 mhr mhr  82 Apr 14 15:37 myfile
drwxrwxrwx 1 mhr mhr 512 Apr 29 23:15 uts1

* What's wrong / what should be happening instead:

The last line should read "drw........5....." as this directory has 3 sub-directories (plus "." and ".." gives 5).
This is how "ls -l" works on other Linux machines I have access to.
It appears to always show "1".

**Comment by 0xbadfca11** [comment]
However btrfs always return 1, ext4 return 1 when number of sub dirs > 64998, in real Linux.
(There is also a limitation due to the NTFS disk format, but) that rule is no longer observed.
If that causes problems on WSL, the same problem should also occur on Linux.

**Comment by billziss-gh** [comment]
It is legal for file systems to report `st_nlink==1` for directories. See [reference](http://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html):

> the value of the member st_nlink shall be set to the number of links to the file.

The `find` utility now has a workaround for this ([man find](https://linux.die.net/man/1/find) `-noleaf` option).

**Comment by therealkenc** [comment]
#2443, #2229
