### ISSUE TITLE
Another color issue...

### ISSUE THREAD

**Issue by QAnders** [Microsoft/WSL#4011]
Not sure when this started as I haven't used WSL for development in a while but I had previously set up colors mimicking Ubuntu some time ago using the color palette in the Properties settings.
Previously the text in the JSON output was yellow but now they are the same color as the background:
![image](https://user-images.githubusercontent.com/12028885/56967616-d8836400-6b61-11e9-9642-3ed26eba8bf0.png)

This is how JSON looks now, the actual JSON text is (copy/pasted from the console):
```
QIPJS: { document_id: '207867',
  receiver_data:
   { externalId: '1003',
```

Which color is used for the string in the JSON output above?

**Comment by therealkenc** [comment]
Closing on not WSL actionable.
