### ISSUE TITLE
No /proc/<pid>/pagemap

### ISSUE THREAD

**Issue by jonathanasdf** [microsoft/WSL#4018]
Is there a way to get this information?

**Comment by therealkenc** [comment]
You aren't going to get [libTAS](https://github.com/clementgallet/libTAS/issues/223) up on WSL for a number of reasons, [`/proc/<pid>/pagemap`](https://www.kernel.org/doc/Documentation/vm/pagemap.txt) being one of them but not alone. [Tool Assisted Speedrun](https://en.wikipedia.org/wiki/Tool-assisted_speedrun). Huh. I guess that's a thing.

Oddly (?) this is the first ask for `pagemap` I can see. [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l) I guess. Including details of your development workflow helps.
