### ISSUE TITLE
Error: 0x80070002 after delete of Ubuntu folder

### ISSUE THREAD

**Issue by alexrjs** [microsoft/WSL#4023]
**Please fill out the below information:**
Microsoft Windows [Version 10.0.16299.15] with WSL enabled

**What you're doing and what's happening:**  
- Downloaded and Installed CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc.zip to Ubuntu folder on April, 1st, cause Windows Store is disabled in our organisation.
From: (German) https://docs.microsoft.com/de-de/windows/wsl/install-on-server
- First time usage allowed creation of a user
- Used ubuntu1804.exe till today (May, 8) with this user
- Deleted Folder Ubuntu by accident
- Unzipped it again to Ubuntu folder, after that 0x800070002 appears when ubuntu1804.exe is called.
- If you use a different user (eg. a seperate Local Admin User) the same ubuntu1804.exe works fine, so I assume the registry is somehow broken for the current user, so ubunutu1804.exe registry is in an undefined state for the current user.

**What's wrong / what should be happening instead:**
- A detailed message what the problem is
- There should be a option to reset the registry when this error occurs
- Or there should be a description to clean the registry to get to a state so you can create new user

**Strace of the failing command, if applicable:**  
N/A

**For WSL launch issues, please [collect detailed logs]**
See Attachement
[ubuntu1804-0x80070002.zip](https://github.com/microsoft/WSL/files/3157115/ubuntu1804-0x80070002.zip)

**Comment by sirredbeard** [comment]
Have you thought of using a [Chocolatey package](https://chocolatey.org/packages/wsl-ubuntu-1804) to manage your deployment of WSL?

**Comment by alexrjs** [comment]
@sirredbeard - I wasn't aware that this was possible... But thanks, I give it a try.... I'm not sure if it helps with the registry problem...

**Comment by alexrjs** [comment]
@sirredbeard So I tried Chocolatery package... Same effect... Still a broken registry... Still a different user works fine... Still think a reset tool for a broken registry would be nice... But guess the WSL team has bigger fish to fry... :-/

**Comment by benhillis** [comment]
Could you try wslconfig.exe /list /all followed by wslconfig.exe /unregister <distro>

**Comment by alexrjs** [comment]
@benhillis Many thanks for your help... I did the following to solve my problem:

1. wslconfig.exe /list /all
Windows-Subsystem für Linux-Distributionen:
Ubuntu-18.04 (Standard)
2. wslconfig.exe /unregister Ubuntu-18.04
Registrierung wird aufgehoben…

This solved the 0x80070002 error problem and I could install the Ubuntu 18.04 Subsystem with my local user, again. 👍
