### ISSUE TITLE
Metadata option is not set when doing mount

### ISSUE THREAD

**Issue by riponbanik** [microsoft/WSL#4025]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 1709

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
With reference to https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/, running command 

sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata

* What's wrong / what should be happening instead:
mount -l showing, missing metadata 
.....
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
C: on /c type drvfs (rw,noatime)
**C: on /mnt/c type drvfs (rw,relatime)**

* Additional Information - without setting the following option, result is the same
cat /etc/wsl.conf

[automount]
enabled = true
options = metadata,uid=1000,gid=1000,umask=022

**Comment by cinemast** [comment]
I am having the same problem.

**Comment by Heady20006** [comment]
i can mount C: with metadata but if i try to mount my second disk (D:) with metadata nothing changed on D:

**Comment by patrickporto** [comment]
My folder home is /mnt/c and I am trying to use automount with options metadata but don't working

**Comment by patrickporto** [comment]
I have got a fix!

1. Go to Settings
1. Update & Security > Windows Security > Virus & threat protection
1. Virus & threat protection > Virus & threat protection settings > Manage settings > Exclusions > Add or remote exclusions > Add an exclusion
1. Select the folder `C:\Users\<your-user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_<hash>\LocalState\rootfs`.
1. Done
