### ISSUE TITLE
Will WSL 2 use Systemd

### ISSUE THREAD

**Issue by mikeroyal** [microsoft/WSL#4028]
Now that WSL 2 will be using a real Linux kernel(version 4.19) does that mean you will be using Systemd or will you have another method ?

**Comment by therealkenc** [comment]
The Build 2019 WSL2 [presentation](https://www.youtube.com/watch?v=lwhMThePdIo) indicates that WSL `/init` will live on. It is integral to the 9P service, among other things. Making WSL2 look exactly like WSL1 (except for the whole "all the syscalls work" thing) is stated as an explicit goal, as is fast startup. The `systemd` pow-wow is over at #994.

**Comment by Biswa96** [comment]
Though the idea isn't bad. Who knows whatever comes next ;)
