### ISSUE TITLE
File edited on windows disappears on linux?

### ISSUE THREAD

**Issue by seemsindie** [Microsoft/WSL#403]
Hello guys, as the title says, i have node project opened in VSCode running on windows. When i save edited file that file disappears from linux filesystem. It's just gone...

Any idea why is this happening and how to fix it?

**Comment by aseering** [comment]
Hey @seemsindie -- welcome to BashOnWindows!

Is the file in the Windows filesystem, or in the hidden directory containing the data for the Linux filesystem?  If the latter, the WSL developers have indicated that this behavior is known and Works-As-Intended:  The Linux filesystem storage is more complicated than it looks (it looks like just a bunch of files but it seems that there's more going on behind the scenes) and it's not intended for direct use by Windows apps that aren't Linux-aware.  (Which is to say, "all Windows apps other than 'bash.exe'.")

Can you put your code in a Windows directory and symlink to it within WSL?

**Comment by seemsindie** [comment]
Hello @aseering 

The project folder is in appdata folder, in lxss/home/ivan/...
And i have that folder in vscode...

So what are you saying is to relocate the folder in win filesystem and to link the folder in lxss/home/ivan?

**Comment by aseering** [comment]
Yes, try relocating the folder to the Windows filesystem, and use a Linux command such as "ln -s /mnt/c/path/to/your/folder" to make it more convenient to access from within WSL.

You can also "cd" into "/mnt/c/..." from within WSL.  Linux can work with the Windows filesystem, but Windows cannot work with the Linux filesystem.

**Comment by seemsindie** [comment]
@aseering I did all of that, but now i have different issue, i can't install node modules...
I am getting this error:

```
Traceback (most recent call last):
  File "/usr/share/node-gyp/gyp/gyp", line 9, in <module>
    load_entry_point('gyp==0.1', 'console_scripts', 'gyp')()npm
  File "/usr/lib/python2.7/dist-packages/gyp/__init__.py", line 547, in script_main
 http     return main(sys.argv[1:])
GET  File "/usr/lib/python2.7/dist-packages/gyp/__init__.py", line 540, in main
 https://registry.npmjs.org/diff/1.4.0
    return gyp_main(args)
  File "/usr/lib/python2.7/dist-packages/gyp/__init__.py", line 525, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/lib/python2.7/dist-packages/gyp/generator/make.py", line 2042, in GenerateOutput
npm http GET https://registry.npmjs.org/mkdirp/0.5.1
    ensure_directory_exists(makefile_path)
  File "/usr/lib/python2.7/dist-packages/gyp/generator/make.py", line 110, in ensure_directory_exists
    os.makedirs(dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)npm
OSError : [Errno 17] File exists: 'build/.'
```

**Comment by aseering** [comment]
@seemsindie what directory or directories are you symlinking in from Windows?

**Comment by seemsindie** [comment]
@aseering The project folder including node_modules. I guess this is happening because of windows max path size or something like that, so what i did in the end(i don't like the solution) i have a symlink just for node_modules on linux for project that is located in windows. So when i do npm i all packages are stored on linux but linked on the windows...huh :)

**Comment by russalex** [comment]
@seemsindie What build are you running?  There is a known issue on installing node modules on /mnt/x drives before build 14342 (tracked on #3).  There is one more npm bug tracked on #313.  Once you have those you should be able to use /mnt/x for your node modules.

As for the files disappearing when edited, @aseering is absolutely correct (thanks!).  If you're curious into what's going on here, @dethoma has a good blog post [here](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/) which starts to explain things.  We have more detailed blog posts on the way with one being all about the filesystem.

**Comment by dreyks** [comment]
@russalex it says "Interoperability between Windows applications and files in VolFs is not supported." but if I edit a file on linux FS from notepad/akelpad etc., it all goes well. Things go south only if I try editing it with some IDE (like Rubymine). Is there any difference? Is such interoperability planned in future? 
If I store a file in windows FS it has 777 from the linux side, which messes with git, because it thinks that file was changed. What is the workaround here?

**Comment by russalex** [comment]
@dreyks Unfortunately there is a difference on how applications interact with extended attributes.  We're finding that some apps actually strip the extended attributes off (say by deleting and re-creating the file when you hit save).  Comparability becomes very difficult in these cases.

As for storing files on DrvFs (/mnt/<x>), we do our best to map and show the Windows privileges correctly.  There is a blog post going into details about the filesystem that's in the works and should be done soon (blogs are [here](https://blogs.msdn.microsoft.com/wsl/)).

We are looking at interoperability, what it means and how things can be improved, but to do it right will take a little bit of time.

**Comment by SungamR** [comment]
While not addressing the issue but rather walking around it I use Xming, Linux tools when working in the VoIF.  Surprisingly much work. Unfortunately not VSCode (Electron issue), but Sublime is ok.

**Comment by SRGOM** [comment]
Also, a file in Linux home directory- created on Linux but deleted on Windows becomes unusable in both places 

Create a file on the WSL side `touch x`. You see it fine on the Windows Side. Now delete from Windows side `del x`.  `ls x` on Windows side shows that the file is still there. `vim x` on the Windows side will not allow you to save it. `vim x` on the WSL side will not allow you to save it. Basically you can no longer do anything to the file from either side, the only option is to remove it using Win+X -> a -> rm.

**Comment by therealkenc** [comment]
From the OP:

> The project folder is in appdata folder, in lxss/home/ivan/...

There is a summary blog post [here](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/). Ref #1740 #1524. User Voice on making things better [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341279-a-file-created-in-c-users-user-appdata-local-lx). There is some mitigation on "files disappearing" per #873 ([message](https://github.com/Microsoft/WSL/issues/873#issuecomment-347334200)).

**Comment by PiotrFusik** [comment]
How come files disappearing when saved could be intended behavior? "It's complicated" is an excuse, not a reason. Symlinking is a workaround and not a solution. Please fix it!
