### ISSUE TITLE
Swift REPL does not start

### ISSUE THREAD

**Issue by thorsteneb** [microsoft/WSL#4030]
* Your Windows build number:  18894 20H1 Insider build - same behavior on 1809 release
WSL 1, Ubuntu 18.04
Swift 5.01 installed from https://swift.org/download/
Please note this NOT a duplicate of #286 , the execstack issue has since been solved upstream in Swift 

* What you're doing and what's happening:  
Execute 'swift'
Terminal does not show further output, Ctrl-C does not end swift REPL. strace shows "process launch failed: 'A' packet returned an error: 8"

```
tbehrens@WSL-INSIDERTEST:~$ swift -version
Swift version 5.0.1 (swift-5.0.1-RELEASE)
Target: x86_64-unknown-linux-gnu
tbehrens@WSL-INSIDERTEST:~$ swift


^C


^C
```

* What's wrong / what should be happening instead:
swift REPL should start, output along the lines of:

```
Welcome to Apple Swift version 5.01. Type :help for assistance.
  1>
```

* Strace of the failing command, if applicable:

[swift-strace.txt](https://github.com/microsoft/WSL/files/3166651/swift-strace.txt)

From roughly line 4340 in strace, a number of EBADF, then on line 6383, a failed ptrace with EPERM followed by an fseek with ESPIPE.

Same behavior with "sudo /path/to/swift/usr/bin/swift"

**Comment by the-provost** [comment]
I encountered the same issue. Any fixes or workarounds?

**Comment by yorickdowne** [comment]
Workaround: Use WSL 2.

**Comment by bmaciag** [comment]
Same issue here.

**Comment by yostane** [comment]
Same issue

**Comment by yostane** [comment]
> Workaround: Use WSL 2.

I confirm. Debugging and REPL do not function on WSL1

**Comment by yostane** [comment]
Maybe we can close this issue ? @thorsteneb

**Comment by thorsteneb** [comment]
Certainly. I think closing it says something about ongoing WSL 1 development - and, I am perfectly fine by that.
Go ahead and close!

**Comment by yostane** [comment]
> Certainly. I think closing it says something about ongoing WSL 1 development - and, I am perfectly fine by that.
> Go ahead and close!

Sorry, I am not a contributor so I can't tickets. Maybe someone from WSL team can close it ?
