### ISSUE TITLE
tcpdump/wireshark support on upcoming WSL 2

### ISSUE THREAD

**Issue by WashingtonARamos** [microsoft/WSL#4032]
With the annoucement of the upcoming WSL2 I remembered that tcpdump doesn't work with current WSL1 and it's been quite some time since developers first asked for it. Will WSL2 support it and other network-related tools?

**Comment by benhillis** [comment]
Yes, networking related tools will work much better on WSL2.

**Comment by romulobrandino** [comment]
Do you how to install wireshark on WSL2, is it compatible with wirehshar on win10 64bits?
