### ISSUE TITLE
Can't start up bash on Windows 10 version 1809 Build 17763.475

### ISSUE THREAD

**Issue by DragonOsman** [microsoft/WSL#4033]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Output of running 'ver` at a Command Prompt is `Microsoft Windows [Version 10.0.17763.475]`.  

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
This is what I did and the output:
```
C:\emsdk>bash
Server execution failed
```
Note: this also happened while I was in the C:\ drive (elevated and non-elevated Command Prompt, as well as Developer Command Prompt for VS 2019 or otherwise).  

* What's wrong / what should be happening instead: As you can see above, I can't run `bash` at all, and the error I get is "Server execution failed".  I don't understand what's happening or why.  But I do know that I should be getting the WSL started.  

Any help is appreciated.

**Comment by DragonOsman** [comment]
Making this post to add: This happened after I ran the commands `sudo apt-get update` and `sudo apt-get upgrade -y` the last time I successfully ran `bash`.  I exited from it right after the update and upgrade processes were completed; the next time I tried to start up the WSL, I got the error message `Server execution failed`.

**Comment by DragonOsman** [comment]
Disabling and reenabling the feature in the optionalfeatures.exe window solved it, but I'm not sure if it could happen again so I'd like to know why the "Server execution failed" error happens.  As well as ways to fix it.

**Comment by jsteenri** [comment]
Is the [mentioned solution](https://github.com/microsoft/WSL/issues/4033#issuecomment-491614975) data-safe?   I'm thinking it's a complete wipe of the WSL subsystem and thus not a good idea if WSL contained data you didn't have elsewhere...

**Comment by naikrovek** [comment]
> Is the [mentioned solution](https://github.com/microsoft/WSL/issues/4033#issuecomment-491614975) data-safe? I'm thinking it's a complete wipe of the WSL subsystem and thus not a good idea if WSL contained data you didn't have elsewhere...

I just had to do this and it appears my data is all still intact.  Not sure if this is a guaranteed thing, or if it's just a fluke.

**Comment by wagnerteixeira** [comment]
I some problem here, i'm was disabled and reenabled in optionalfeatures, work some days and broken again

**Comment by MrTommyt** [comment]
> I some problem here, i'm was disabled and reenabled in optionalfeatures, work some days and broken again

@wagnerteixeira I had the same problem, did you manage to find a solution? This is driving me crazy.
