### ISSUE TITLE
prctl(PR_SET_SECCOMP, SECCOMP_MODE_STRICT) does not work in WSL

### ISSUE THREAD

**Issue by jozefizso** [microsoft/WSL#4035]
Windows 10 Pro x64 1903 (10.0.18362.53)
WSL Ubuntu 18.04

I'm trying to use [lepton](https://github.com/dropbox/lepton) in WSL.

The application is using two calls, which are not implemented in WSL, so the application is failing. Both calls return EINVAL (Invalid argument).

```
prctl(PR_SET_SECCOMP, SECCOMP_MODE_STRICT)
prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, &prog)
```

The call is used here: https://github.com/dropbox/lepton/blob/master/src/io/Seccomp.cc#L122

```c
#include <stdio.h>
#include <sys/prctl.h>
#include <linux/seccomp.h>
#include <linux/filter.h>

int main(int argc, char **argv) {
    int errno = 0;
    if ( errno = prctl(PR_SET_SECCOMP, SECCOMP_MODE_STRICT) ) {
        printf("ERROR: PR_SET_SECCOMP SECCOMP_MODE_STRICT not working. Error: %i\n", errno);
        return 1;
    }

    return 0;
}
```

```c
#include <stdio.h>
#include <sys/prctl.h>
#include <linux/seccomp.h>
#include <linux/filter.h>

int main(int argc, char **argv) {
    int errno = 0;
    struct sock_fprog prog;
    if ( errno = prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, &prog) ) {
        printf("ERROR: PR_SET_SECCOMP SECCOMP_MODE_FILTER not working. Error: %i\n", errno);
        return 1;
    }

    return 0;
}
```

When I run these programs under WSL, they does not work.
Logs: https://gist.github.com/jozefizso/c29dc4a37fe1d1a24f63178a0e396795

**Comment by therealkenc** [comment]
Try [`-unjailed`](https://github.com/dropbox/lepton/blob/44c28a83b2d09c36478c1a5a9e7e28d71a1f0d38/src/lepton/jpgcoder.cc#L1053).
