### ISSUE TITLE
Wrong display of prompt in last byte

### ISSUE THREAD

**Issue by Whale-fall** [microsoft/WSL#4037]
The last byte's color of the prompt should consist, however，it displays like that 
![{F2@QZ Y`S76ZY9{6%XG619](https://user-images.githubusercontent.com/22662209/57601739-e9839a80-758f-11e9-9484-a0ec5f34b6a7.png)(on Terminus)
![JAUWN~ZT_7FPJC~73GOIDSO](https://user-images.githubusercontent.com/22662209/57601745-edafb800-758f-11e9-8776-8f01d57ac296.png)(on windows terminal).

it occurred when I update the win10 to the last version（till "019-05-13“）
zsh--version  ：zsh 5.4.2 (x86_64-ubuntu-Linux-gnu)
zsh -- theme: spaceship.
when I change the theme to other zsh-theme like "cypher", it displays fine. Wired

**Comment by Biswa96** [comment]
What is on CMD, without any other terminal emulators?

**Comment by Whale-fall** [comment]
![BIFMU Y6M9W}HIG51Z~YU$1](https://user-images.githubusercontent.com/22662209/57602432-a3c7d180-7591-11e9-976b-f1317c416a8c.png)
I am sorry but it seems same,by the way when I use tab trying to autocomplie the conmand the help information will not dissapper imdiately like that
![L_R_ 9L3R`5JME3IB%S9}PB](https://user-images.githubusercontent.com/22662209/57602699-7596c180-7592-11e9-9f58-0271956d7a6d.png)

**Comment by Whale-fall** [comment]
> ![BIFMU Y6M9W}HIG51Z~YU$1](https://user-images.githubusercontent.com/22662209/57602432-a3c7d180-7591-11e9-976b-f1317c416a8c.png)
> I am sorry but it seems same,by the way when I use tab trying to autocomplie the conmand the help information will not dissapper imdiately like that
> ![L_R_ 9L3R`5JME3IB%S9}PB](https://user-images.githubusercontent.com/22662209/57602699-7596c180-7592-11e9-9f58-0271956d7a6d.png)
