### ISSUE TITLE
Creating a socket on drvfs will create a regular file

### ISSUE THREAD

**Issue by 0xbadfca11** [microsoft/WSL#4038]
* Your Windows build number:
Microsoft Windows [Version 10.0.18362.116]

* What you're doing and what's happening:
```bash
$ mount | grep C:
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
$ mkdir -p /mnt/c/test
$ python3 -c "import socket; socket.socket(socket.AF_UNIX).bind('/mnt/c/test/socket');"
$ ls -l /mnt/c/test/socket
-rwxrwxrwx 1 root root 0 May 13 00:00 /mnt/c/test/socket
```
```bash
$ mount | grep C:
C:\ on /mnt/c type drvfs (rw,noatime,metadata,uid=1000,gid=1000,case=off)
$ mkdir -p /mnt/c/test
$ python3 -c "import socket; socket.socket(socket.AF_UNIX).bind('/mnt/c/test/socket');"
$ ls -l /mnt/c/test/socket
---------- 1 root root 0 May 13 00:00 /mnt/c/test/socket
```
This regular file still functions as a socket.
* What's wrong / what should be happening instead:
Should fail or create as correctly state.

**Comment by 0xbadfca11** [comment]
I found sockets made with Windows API were regular files, not reparse point.

**Comment by Biswa96** [comment]
Windows sockets are file? Which API?

**Comment by 0xbadfca11** [comment]
Code is here.
https://github.com/MicrosoftDocs/WSL/blob/live/wsl-samples/afunix-wsl-interop/windows_server/af_unix_win_server.cpp

**Comment by lpereira** [comment]
Similar issue found with .NET core, when the temporary directory is set to a drvfs mount.  More information here: https://github.com/dotnet/core-setup/issues/4149

**Comment by karolyi** [comment]
Can confirm. I bind-mounted my home dir to a directory on /mnt/C. The created socket files in the bind mount are also not socket files but regular files with empty umask.
