### ISSUE TITLE
When can CentOS 7 be supported

### ISSUE THREAD

**Issue by thousmile** [microsoft/WSL#4043]
I hope I can support centos 7 earlier.！

The ubuntu system is not very easy to use, and I try to install docker always has some inexplicable problems. For example: the installation can not be started, or the image file cannot be pulled after startup.

I think the experience is terrible.

**Comment by Biswa96** [comment]
It is possible to run basic programs in CentOS (may be). [My repo][1] has some steps. For docker, wait for 1-2 months until "WSL2" will be released. 

[1]: https://github.com/Biswa96/WSLInstall.git

**Comment by therealkenc** [comment]
You can contact the CentOS peeps and see if they are interested in making their distibution available in the store. The "when" is up to them. More information [here](https://github.com/microsoft/WSL-DistroLauncher).

**Comment by eromoe** [comment]
@thousmile wsl doesn't support docker , you need wait wsl2
