### ISSUE TITLE
The command “openSUSE-42 config –default-user root” does not work.

### ISSUE THREAD

**Issue by BFASKarlR** [microsoft/WSL#4044]
The command “openSUSE-42 config –default-user root” does not work.

—
> openSUSE-42 config –default-user root
Default UNIX user set to: root

Yet the user is still the original user when I start openSuse.

Also, I told WSL to use the same password for root as the user.
I cannot sudo. I cannot su. Basically, my installation is useless.
Any ideas?

**Comment by therealkenc** [comment]
I could not reproduce this here (default is set as root). The `openSUSE-42.exe` application is shipped by and controlled SUSE not WSL. You _could_ try setting it manually in the registry per #3974 ([message](https://github.com/microsoft/WSL/issues/3974#issuecomment-483061865)).

On [18305](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18305) or better you can do (from `cmd.exe`):
```
wsl.exe --user root --distribution openSUSE-42
```

> I cannot sudo. I cannot su.

That's a different question. `sudo` and `su` _work_, naturally, or heads would explode. You don't specify your mode of failure. Assuming `sudo` is saying your password is incorrect, it probably is. Get yourself `root` via the aforementioned and use `passwd` to reset your password. Or start over is always an option.
