### ISSUE TITLE
`wsl --list` is not a command

### ISSUE THREAD

**Issue by shogerr** [microsoft/WSL#4045]
As the topic states: `wsl --list` is not a command.

Use `wslconfig /l` instead.

```
PS C:\> wsl --list
Invalid command line option: --list
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
```

**Comment by mscraigloewen** [comment]
Hi @shogerr ! 

What version of Windows are you running? To find this, if you open up cmd.exe and type in `ver` what's the output?

**Comment by therealkenc** [comment]
Since the output was pasted in the OP, whatever winver, it is demonstrably a pre-[18305](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18305) `wsl.exe`. So, same by-design closure regardless of the specifics (let's say it is 17763 for sport).

[As an aside, both `wsl.exe` and `/init` lack a `--version` CLI param. Not exactly a showstopping gap in functionality, but it's a longstanding convention.]

**Comment by Biswa96** [comment]
Speaking of CLI params, do we need wslconfig.exe now? Because wslconfig.exe params are same as wsl.exe.

**Comment by benhillis** [comment]
Nope it will be depreciated eventually.

**Comment by SharakPL** [comment]
Could someone explain why was this closed and labeled _bydesign_. Is it Microsoft's intention to use command `wsl -l` or `wsl --list` all over the docs and then block it completely? Does this have something to do with switching default console terminal from bash to zsh? Should I import all rules from `.bashrc` to `.zshrc` for this to work properly?

**Comment by Nakilon** [comment]
> Is it Microsoft's intention to use command `wsl -l` or `wsl --list` all over the docs and then block it completely in final product?

Yes, this is absolutely lame. The commands are in the "How to install WSL" https://docs.microsoft.com/en-us/windows/wsl/install and they just don't work. Such a Windows experience.

**Comment by Nakilon** [comment]
It needs a reboot. Why isn't it written in docs?

**Comment by realyukii** [comment]
@Nakilon I tried to reboot but it still not work, it didn't print any error though, just print the help message instead of list something
