### ISSUE TITLE
Console opens only after restart, then stops

### ISSUE THREAD

**Issue by Protazy21** [microsoft/WSL#4047]
*  Microsoft Windows [Version 10.0.17763.503]

* opening console works only after reboot, you can open OpenSuse or Ubuntu console or type bash in cmd and all works fine, after some use if you close all windows with console you can't open again, say you open OpenSuse42.3 the window will show up but there is no prompt, if you type bash in cmd, the command will start execution and hang, no prompt will show up.
Seems to be distro unrelated as both ubuntu and opensuse are affected.

* What's wrong / what should be happening instead:
Prompt never shows up, should show up after opening a console window or execution command in cmd/powershell

![opensuse-bash](https://user-images.githubusercontent.com/4419551/57956890-6ac19100-78f2-11e9-8f4e-a08348227d10.png)
![cmd-bash](https://user-images.githubusercontent.com/4419551/57956900-7319cc00-78f2-11e9-879d-29ce1fe83810.png)

[logs.zip](https://github.com/microsoft/WSL/files/3193141/logs.zip)

**Comment by hnlpower** [comment]
same problem

**Comment by joeycasabar** [comment]
Similar issue on Windows 10 Pro, build 18362.175. WSL functions after reboot until first time closing, then hangs on subsequent openings.

**Comment by dfeinzeig** [comment]
same problem. any updates? this is ridiculous. i use this to make a living.

**Comment by benhillis** [comment]
What state is the LxssManager service in while this is happening?

**Comment by dfeinzeig** [comment]
LxssManager is running. It fails to stop/restart.

**Comment by benhillis** [comment]
If you "sc stop lxssmanager" from admin, does the service stop or does it get stuck in the "stopping" state?

**Comment by dfeinzeig** [comment]
```
C:\Windows\system32>sc stop lxssmanager
[SC] ControlService FAILED 1061:

The service cannot accept control messages at this time.
```

**Comment by benhillis** [comment]
Thanks. This is an issue that I've been debugging for a while. In the meantime, to get back to a working state if you kill the svchost.exe that is running the LxssManager service.  You can get this pid via the services tab of task manager.  You can avoid this issue by leaving a window open, or launching something in the background like a detached tmux session.

**Comment by dfeinzeig** [comment]
I get access denied message when trying to kill that svchost process

**Comment by benhillis** [comment]
From task manager?

**Comment by dfeinzeig** [comment]
yes, end task from task manager and also from taskkill on cmd as admin

**Comment by benhillis** [comment]
Interesting... I can do that on my machine with no issues.  My other workarounds will still work for you though as I diagnose this issue.

**Comment by dfeinzeig** [comment]
ok, i will reboot i guess and then just keep a shell open. let me know if there is anything else you'd like me to try before rebooting and losing this broken state?

**Comment by benhillis** [comment]
If possible, a dump of the service might be useful, but if you cant kill it it's unlikely you'll be able to collect a memory dump.

**Comment by dfeinzeig** [comment]
nope, no luck also get access denied. next time it happens i can try again.

**Comment by dfeinzeig** [comment]
after restart i can start bash. but then if i close it, and try to open again it hangs again. once again can't kill the svchost process or take a dump of it, getting access denied.

**Comment by benhillis** [comment]
@dfeinzeig - Could you collect a trace?  Starting from a fresh reboot?

**Comment by dfeinzeig** [comment]
sure, how do i do that?

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by dfeinzeig** [comment]
so reboot, start the 3 traces, launch bash, close it, try to relaunch, stop 3 traces?

**Comment by benhillis** [comment]
Correct, thanks!

**Comment by dfeinzeig** [comment]
k, np, brb

**Comment by dfeinzeig** [comment]
ugh, now bash starts again after closing (not something i thought i'd complain about!) i collected traces, but guessing they aren't particularly helpful?

**Comment by benhillis** [comment]
Yeah I'd need a trace of the repro.  In the past is it possible you waited about 5 minutes before attempting to re-launch?

**Comment by dfeinzeig** [comment]
when i tried a few minutes ago i successfully launched it, tried `uptime`, closed it, and then immediately tried to relaunch but it failed

**Comment by jgoeglein** [comment]
Found this thread while having the same issue. Ran 3 log traces as described. Adding additional logs in case they help.

Surface Pro 6. Version 10.0.18362 Build 18362

I first ran Ubuntu directly. After that, I attempted to run bash from Powershell with the same result (screenshots below). I waited roughly a minute for each attempt.

![image](https://user-images.githubusercontent.com/6181164/61190581-d195c900-a65b-11e9-9be5-004c728c4a68.png)

![image](https://user-images.githubusercontent.com/6181164/61190586-e1ada880-a65b-11e9-8fd8-d9dbbaf13ab5.png)

[lxcoreLogs.zip](https://github.com/microsoft/WSL/files/3390508/lxcoreLogs.zip)

**Comment by craigloewen-msft** [comment]
Pinging this thread with updates from @DHowett-MSFT

This appears to be related to a console bug. Please check the properties for the console hosting your distro to make sure the options on the “Terminal” page aren’t turned on, or aren’t set to make the colors all black.

This is being tracked here: https://github.com/microsoft/terminal/issues/2319

**Comment by jgoeglein** [comment]
An update to try for anyone else coming along - I removed BitDefender antivirus and haven't had this issue since.

**Comment by arsdever** [comment]
Any progress made on this scope? Still happens on my machine

**Comment by MerzDaniel** [comment]
Also (or again) hangs with the most recent windows update KB4023057 . I have no HyperV installed. Clean restart fixed it

**Comment by stemabo** [comment]
+1
terminal appears to be fine first, but starting nano or vim results in a blanc black screen

**Comment by lafloresb** [comment]
The best solution that always worked for me was to:
1) Disable WSL windows feature
2) Restart OS
3) Enable WSL windows feature
4) Restart OS
5) It is going to work again without deleting any of your WSL environments

**Comment by Sieboldianus** [comment]
WSL1 Ubuntu 18.04 LTS stopped working today after I installed Debian in another WSL1 distro.

Nothing helps so far:
- Disabling/Enabling WSL Feature
- Stopping `lxssmanager` and starting again
- Renaming `.bashrc` in the Ubuntu WSL distro using powershell bash

I have the feeling this distro is lost. It is only 1 month away from EOL for Ubuntu 18.04 LTS, so I may as well leave the ship to a new distro.

**Comment by sanba-anass** [comment]
> The best solution that always worked for me was to:
> 
> 1. Disable WSL windows feature
> 2. Restart OS
> 3. Enable WSL windows feature
> 4. Restart OS
> 5. It is going to work again without deleting any of your WSL environments

u saved my day !!!!!!!!!
