### ISSUE TITLE
ubuntu tmux shift+insert doesn't paste from clipboard

### ISSUE THREAD

**Issue by cmskzhan** [microsoft/WSL#4049]
* Windows build number:  (Type `ver` at a Windows Command Prompt): 
Microsoft Windows [Version 10.0.17134.765]

* What you're doing and what's happening: 
Unable to paste to tmux when running under wsl ubuntu, not even shift+insert

* What's wrong / what should be happening instead:
shift+insert works on cmd, but doesn't work on default ubuntu bash or tmux. 
shift-insert only output 2~

This might not relevant to tmux, just wsh ubuntu in general. 
Tried Enable/Dsiable Quick Edit Mode and Insert Mode. No joy

Currently the only way to paste it mouse right click (that won't work in tmux though)

**Comment by therealkenc** [comment]
[console issue tracker](https://github.com/microsoft/console/issues).
