### ISSUE TITLE
Terminal ought to work with more fonts

### ISSUE THREAD

**Issue by HenkPoley** [Microsoft/WSL#405]
Currently the selection of fonts is very limited. For example the FiraCode programming ligatures font cannot be chosen: https://github.com/tonsky/FiraCode/

I understand that it's a bit outside of the scope, but since you are driving the terminal emulator code forward at the moment.

**Comment by mkarpoff** [comment]
There are pretty easy ways to add more fonts the same way you would for the normal console since bash works inside it. You do need to do some use regedit to do it though so it would be nice to have a better interface. I've attached a link on how to do it in the mean time.[Think Geek Change console fonts](http://www.howtogeek.com/howto/windows-vista/stupid-geek-tricks-enable-more-fonts-for-the-windows-command-prompt/)

**Comment by zadjii-msft** [comment]
So, I'm not sure if it's in the insiders build yet or not, but we have added the ability to pick your font from more than just the 3 legacy console fonts, without any need for dirty registry hacks like the one @mkarpoff linked. We're doing our best to try and support as many monospaced fonts as possible, but ligatures are definitely not going to be able to make it for the anniversary update.

I'll add it to the backlog though :)

**Comment by zerocool4u2** [comment]
multiple fonts are working right now, i believe that firacode is not monospace, all the chars are monospace size, but the glyphs aren't so the font itself doesn't belong to the family, i have lots of fonts on my console right now, fira mono is one of them, i'm guessing is pretty much the same, @zadjii-msft it would be nice to have the option of use any kind of font for those cases or maybe font fallback support for adding multiple glyphs fonts(devicons, powershell, font awesome, etc), right now the only solution is patch fonts and is a really pain in the @ss, with scripts(size problems) or by editing one character at the time, regards

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing. If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
