### ISSUE TITLE
Atom call from WSL resulting in a frozen shell if Atom is not yet running

### ISSUE THREAD

**Issue by Tekaoh** [microsoft/WSL#4051]
* Your Windows build number:  Microsoft Windows [Version 10.0.17763.475]

* What you're doing and what's happening:  I'm trying to invoke `atom .` to launch a Windows Atom installation from a Bash shell. If Atom is already running on Windows, the command succeeds, a new Atom window opens with the expected directory loaded, and I am presented with my next Bash prompt. Perfect! But: If Atom is NOT ALREADY running on Windows, Atom opens in the expected directory but the Bash shell hangs and I am never presented with another prompt. I cannot CTRL+C or anything and I have to close the shell and open a new one.

* What's wrong / what should be happening instead: I should always be presented with another Bash prompt after invoking `atom .`

* Strace of the failing command, if applicable:  [gist](https://gist.github.com/Tekaoh/bb2cf0f150d18363aa9904715d73cdae)

* For WSL launch issues, please collect detailed logs.
[logs.zip](https://github.com/microsoft/WSL/files/3194518/logs.zip)

**Comment by Tekaoh** [comment]
Atom community [seems to be aware.](https://github.com/atom/atom/pull/19316#issuecomment-491649528)

**Comment by solvaholic** [comment]
This issue is also discussed in https://github.com/atom/atom/issues/18126#issuecomment-459242044 and https://github.com/microsoft/WSL/issues/3769.

**Comment by felipecassiors** [comment]
To work around it, I'm using:

```bash
powershell.exe 'Start "C:\Program Files\Docker\Docker\Docker Desktop.exe"'
```
