### ISSUE TITLE
.exe's run through ubuntu symbolic links no longer work

### ISSUE THREAD

**Issue by jlennox** [microsoft/WSL#4052]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
*Does not* work in: Microsoft Windows [Version 10.0.18362.113]
*Does* work in: Microsoft Windows [Version 10.0.17134.765]

I setup a new system which has a newer version of Windows than my older system. I do not know if this is the change that causes this issue.

* What's wrong / what should be happening instead:

This is the expected result:
```
joe@DESKTOP-PHPIUJ2 in ~ λ /mnt/c/Users/Joe/Dropbox/Portables/PortableGit/bin/git.exe status
fatal: not a git repository (or any of the parent directories): .git
```

When I make a symbolic link of the exe, then run that link, nothing happens instead now, which was not the case in 10.0.17134.765.
```
joe@DESKTOP-PHPIUJ2 in ~ λ sudo ln -s "/mnt/c/Users/Joe/Dropbox/Portables/PortableGit/bin/git.exe" /usr/local/bin/git
joe@DESKTOP-PHPIUJ2 in ~ λ readlink /usr/local/bin/git
/mnt/c/Users/Joe/Dropbox/Portables/PortableGit/bin/git.exe
joe@DESKTOP-PHPIUJ2 in ~ λ stat /usr/local/bin/git
  File: /usr/local/bin/git -> /mnt/c/Users/Joe/Dropbox/Portables/PortableGit/bin/git.exe
  Size: 58              Blocks: 0          IO Block: 4096   symbolic link
Device: 2h/2d   Inode: 6473924464618020  Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-05-18 15:54:54.391862600 -0700
Modify: 2019-05-18 15:54:54.391862600 -0700
Change: 2019-05-18 15:54:54.391862600 -0700
 Birth: -
joe@DESKTOP-PHPIUJ2 in ~ λ /usr/local/bin/git status
joe@DESKTOP-PHPIUJ2 in ~ λ
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
System where this *does not* work: https://gist.github.com/jlennox/ba2b22a489b202d681f811a067bf9ec0
System where this *does* work: https://gist.github.com/jlennox/81f2e34011862f7f6d9c5456e953cec6

Note: I am not using aliases because software that expects git does not work with them. Notably, my zsh extensions.

**Comment by therealkenc** [comment]
#3999
