### ISSUE TITLE
Overwrite corrupts file when user-mapped by Windows

### ISSUE THREAD

**Issue by thcoffee-msft** [microsoft/WSL#4056]
* Your Windows build number:  10.0.17763.437

* What you're doing and what's happening: 

I was creating and updating PDF files in the Windows file space using WSL tools, and used Microsoft Edge to preview a file "a.pdf" (the default PDF preview behavior on Windows 10). Subsequent updates from tools on WSL silently resulted in corrupt PDF files. The problem can be demonstrated as follows:

1. Open file "a.pdf" with Microsoft Edge.
2. Copy a file "b.pdf" that is smaller than "a.pdf" in WSL console: `cp b.pdf a.pdf`.
3. Console warns "Truncating output file: Invalid argument, /mnt/c/Users/thcoffee/OneDrive - Microsoft/test/b.pdf."
4. Reload file "a.pdf" with Microsoft Edge: corrupt file will very likely fail to read properly, as bytes in original "a.pdf" beyond end of "b.pdf" will be retained.

Note that the warning above is shown when using `cp` on the console, but does not appear when using background processes that overwrite the PDF file.

For comparison, in the Windows command line, executing `copy b.pdf a.pdf` and assenting to overwrite gives the output: "The requested operation cannot be performed on a file with a user-mapped section open. 0 file(s) copied." In this case, the file remains uncorrupted.

* What's wrong / what should be happening instead:

It seems to me that WSL should fail commands that attempt to overwrite files that are being held by Windows applications in ways that will lead to file corruption.

(In this particular case, it also seems that the Microsoft Edge PDF previewer should not hold PDF files in this way (as Firefox does not), but this is independent of WSL.)

* Strace of the failing command, if applicable: 

The key command in the above demonstration is `cp`. When I attempted to run `strace -o cp.strace -f cp b.pdf a.pdf`, I received the error: "cp: cannot stat 'b.pdf': No such file or directory". Using absolute path names gave the same result.

**Comment by therealkenc** [comment]
> /mnt/c/Users/thcoffee/**OneDrive** - Microsoft/test/b.pdf.

Probably dupe or issue#something. Try the same scenario on a NTFS directory and see if it still repros. It might, but that's a good first thing to try.

**Comment by thcoffee-msft** [comment]
The behavior is identical on an NTFS directory.

**Comment by therealkenc** [comment]
Alright thanks; in that case there is something fishy going on. That `strace` fail is pretty questionable too, given the _identical_ `cp` (scare quote) "succeeds" under _identical_ conditions when not being traced. Appreciate the submission.
