### ISSUE TITLE
WslRegisterDistribution places rootfs in path of calling executable; works in terms of executable location

### ISSUE THREAD

**Issue by GigabyteProductions** [microsoft/WSL#4057]
On Windows 10 Enterprise 10.0.17763.0.

As there is no utility distributed with Windows to simply register a given rootfs.tar.gz under a given distribution name (without a distro's launcher file), I am writing a small C program to compile with MinGW or Visual Studio Build Tools to call [WslRegisterDistribution](https://docs.microsoft.com/en-us/windows/desktop/api/wslapi/nf-wslapi-wslregisterdistribution) for this purpose.

Given the following `wslutil.c` C code ...:
```
#define UNICODE 1
#define _UNICODE 1

#include <stdio.h>
#include <tchar.h>
#include <windows.h>
#include <assert.h>

typedef HRESULT(STDAPICALLTYPE* WSL_REGISTER_DISTRIBUTION)(PCWSTR, PCWSTR);
WSL_REGISTER_DISTRIBUTION WslRegisterDistribution;

int wmain(int argc, wchar_t const *argv[])
{
	HMODULE wslapi = LoadLibraryEx(L"wslapi.dll", NULL, LOAD_LIBRARY_SEARCH_SYSTEM32);

	if (wslapi == NULL)
	{
		fprintf(stderr, "could not load wslapi.dll");
		return 1;
	}

	WslRegisterDistribution = (WSL_REGISTER_DISTRIBUTION)GetProcAddress(wslapi, "WslRegisterDistribution");

	if (argc != 3)
	{
		fprintf(stderr, "syntax error");
		return 1;
	}

	HRESULT hr  = WslRegisterDistribution(argv[1], argv[2]);

	if (FAILED(hr))
	{
		fprintf(stderr, "error: 0x%08x", hr);
		return 1;
	}

	return 0;
}
```

or the following version when utilizing a [wslapi.def](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/bfd2db7ac52c48fb48a679f41b6e0ea6e815f047/tree/mingw-w64-crt/lib-common/wslapi.def?format=raw) for implicit linking:
```
#define UNICODE 1
#define _UNICODE 1

#include <stdio.h>
#include <tchar.h>
#include <windows.h>
#include <assert.h>
#include <wslapi.h>

int wmain(int argc, wchar_t const *argv[])
{
	if (argc != 3)
	{
		fprintf(stderr, "syntax error");
		return 1;
	}

	HRESULT hr  = WslRegisterDistribution(argv[1], argv[2]);

	if (FAILED(hr))
	{
		fprintf(stderr, "error: 0x%08x", hr);
		return 1;
	}

	return 0;
}
```

... I ran into multiple issues regarding executable and tarGzFilename location.

For example, if tarGzFilename is not absolute, it is resolved relative to the executable location instead of the working directory, so the following generates `0x80070003`:
```
C:\Users\user>dir wslutil\
 Volume in drive C has no label.
 Volume Serial Number is 20E4-586A

 Directory of C:\Users\user\wslutil

05/20/2019  04:30 PM    <DIR>          .
05/20/2019  04:30 PM    <DIR>          ..
05/20/2019  03:48 PM            95,054 wslutil.exe
               1 File(s)         95,054 bytes
               2 Dir(s)  41,854,816,256 bytes free

C:\Users\user>dir wsl\busybox\
 Volume in drive C has no label.
 Volume Serial Number is 20E4-586A

 Directory of C:\Users\user\wsl\busybox

05/20/2019  04:26 PM    <DIR>          .
05/20/2019  04:26 PM    <DIR>          ..
05/20/2019  03:16 PM        16,809,765 busybox.rootfs.tar.gz
               1 File(s)     16,809,765 bytes
               2 Dir(s)  41,854,816,256 bytes free

C:\Users\user>wslutil\wslutil.exe busybox wsl\busybox\busybox.rootfs.tar.gz
error: 0x80070003
```
while the following works, instead:
```
wslutil\wslutil.exe busybox ..\wsl\busybox\busybox.rootfs.tar.gz
```

And where I would expect `rootfs\` to either end up at `C:\Users\user\rootfs\` or `C:\Users\user\wsl\busybox\rootfs\`, it instead ends up at `C:\Users\user\wslutil\rootfs\`

This hurts my ideal use case:
```
C:\Users\user>cd %userprofile%\wsl\distro1
C:\Users\user\wsl\distro1>\\smb.internal.gigabyteproductions.net\srv\wslutil.exe distro1 \\smb.internal.gigabyteproductions.net\srv\distro1.rootfs.tar.gz
C:\Users\user\wsl\distro1>cd %userprofile%\wsl\distro2
C:\Users\user\wsl\distro2>\\smb.internal.gigabyteproductions.net\srv\wslutil.exe distro2 \\smb.internal.gigabyteproductions.net\srv\distro2.rootfs.tar.gz
...
```

Instead, I need to copy my executable to the location I'd like my `rootfs/` to be located...

I think the API should be updated/added to either use the working directory, or accept the target directory as a parameter.

**Comment by Biswa96** [comment]
In newer Windows 10 releases, there is a `wsl.exe --import` option to register/extract/install a tar.gz file in any location. Otherwise there are many undocumented ways to do it. 

BTW, the link you've provided is from mingw-w64 repository which is different from mingw project.

**Comment by GigabyteProductions** [comment]
Now seeing `wsl --import` on Windows 10 Enterprise 10.0.18362.30.

**Comment by benhillis** [comment]
Thanks for filing, this is by design.
