### ISSUE TITLE
Errno 13 Permission Denied running bitbake for Yocto

### ISSUE THREAD

**Issue by kdubious** [microsoft/WSL#4066]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.503]

* What you're doing and what's happening:
bitbake -k console-tdx-image

Fails with an error

* What's wrong / what should be happening instead:
ERROR: update-rc.d-0.7-r5 do_package: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_task_postfunc(d)
     0003:
File: '/home/kdubious/oe-core/build/../layers/openembedded-core/meta/classes/sstate.bbclass', lineno: 700, function: sstate_task_postfunc
     0696:
     0697:    omask = os.umask(0o002)
     0698:    if omask != 0o002:
     0699:       bb.note("Using umask 0o002 (not %0o) for sstate packaging" % omask)
 *** 0700:    sstate_package(shared_state, d)
     0701:    os.umask(omask)
     0702:
     0703:    sstateinst = d.getVar("SSTATE_INSTDIR")
     0704:    d.setVar('SSTATE_FIXMEDIR', shared_state['fixmedir'])
File: '/home/kdubious/oe-core/build/../layers/openembedded-core/meta/classes/sstate.bbclass', lineno: 620, function: sstate_package
     0616:    for plain in ss['plaindirs']:
     0617:        pdir = plain.replace(workdir, sstatebuild)
     0618:        bb.utils.mkdirhier(plain)
     0619:        bb.utils.mkdirhier(pdir)
 *** 0620:        os.rename(plain, pdir)
     0621:
     0622:    d.setVar('SSTATE_BUILDDIR', sstatebuild)
     0623:    d.setVar('SSTATE_PKG', sstatepkg)
     0624:    d.setVar('SSTATE_INSTDIR', sstatebuild)
Exception: PermissionError: [Errno 13] Permission denied: '/home/kdubious/oe-core/build/tmp-glibc/work/all-angstrom-linux/update-rc.d/0.7-r5/package' -> '/home/kdubious/oe-core/build/tmp-glibc/work/all-angstrom-linux/update-rc.d/0.7-r5/sstate-build-package//package'

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

NOTE: Tasks Summary: Attempted 3530 tasks of which 3509 didn't need to be rerun and 10 failed.

**Comment by scpark97** [comment]
did you solve it?.

**Comment by hedwinkoning** [comment]
Facing the same problem, any update on what is going wrong?
