### ISSUE TITLE
Recent Microsoft Store downloads of Ubuntu 16.04 LTS report as version 18.04

### ISSUE THREAD

**Issue by almondtoast** [microsoft/WSL#4068]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.437]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

After downloading and installing Ubuntu 16.04 LTS, running the command "lsb_release -a" returns the output:

almondtoast@computer:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

* What's wrong / what should be happening instead:
Expected output should be similar to:

almondtoast@computer:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by therealkenc** [comment]
Indeed, it does (made me look). This isn't WSL actionable; WSL does not control the contents of the store apps (absent some really weird confluence of events). But this can be held open for a bit in case there is any update/resolution to report. On a lark you could ask in the [Ubuntu Forums](https://ubuntuforums.org/).

**Comment by miguelprada** [comment]
FYI, just posted a [question on Ask Ubuntu](https://askubuntu.com/questions/1146822/ubuntu-16-04-installation-in-wsl-reports-itself-as-bionic).

**Comment by mscraigloewen** [comment]
Thanks for filing this issue! I've contacted the Canonical team and they are putting in a fix. 😊

**Comment by rbalint** [comment]
Hi, The 16.04 app is reverted to the previous version until the fixed one passes Store certification.

**Comment by miguelprada** [comment]
Reinstalling already gave me a working 16.04 distribution, thanks @mscraigloewen, @rbalint!

**Comment by mscraigloewen** [comment]
Glad to hear it @miguelprada ! I'll mark this issue as closed since your original problem was resolved.
