### ISSUE TITLE
Remove vertical scrollbar from full screen mode

### ISSUE THREAD

**Issue by 0xMF** [Microsoft/WSL#407]
I could not find a way to turn off vertical scrollbar in full screen mode. How can I remove the vertical  scrollbar as that needless visual artefact interferes with my thinking process, so the first thing I always do (for any new terminal) is find a way to turn it off but for some reason I did not find a way to do that on WSL Bash.

**Comment by rcarmo** [comment]
Oh yest, please. I would love this to happen - right now mintty provides a better user experience where it regards window customization, and this is a key aspect of it. I'd only add that I'd like to remove the scrollbar completely, and not only in full screen mode.

**Comment by fpqc** [comment]
@rcarmo If you use ConEMU or console2 to launch bash.exe, this is an available setting.

**Comment by rcarmo** [comment]
Hmmm. Good point. I was hoping to use mintty instead (no point in installing more stuff), but it doesn’t seem to work in my install. Will upgrade and fiddle with it a bit.

**Comment by 0xMF** [comment]
@fpqc I tried ConEMU and while the no-vertical scrollbar works. There were other problems: up/down in bash history did not work making this a problem with ConEmu.

@rcarmo Yes I want WSL bash to have similar features (at minimum) mintty has. Without scrollbar, I can use tmux and I'd be just fine. Believe or not, this is becoming a show stopper for me using WSL bash as I cannot seem to get over the (to me) ugly scrollbar because it occupies screen real estate that is a premium for me.

**Comment by fpqc** [comment]
@rcarmo right now that won't work because bash.exe is a Windows Console application (speaks through conhost) while MinTTY is actually its own separate GUI that talks directly to programs that speak "xterm".  If SSH-server was working in WSL, you probably could use MinTTY through SSH, but it doesn't work that way for the moment.  My understanding is that the team is working on getting PTYs supported as we speak.

@0xMF you should start ConEMU's bash with the option -cur_console:p (or let conemu generate the bash.exe profile automatically).

**Comment by timriker** [comment]
Are there keyboard shortcuts to scroll? I tried shift-pgup/shift-pgdn, and a bunch of others with no luck. If they allow turning off the scrollbar, I hope they add keyboard shortcuts to page through the history first. :)

**Comment by rcarmo** [comment]
Hmmm. I always use a trackpad (which usually minimizes the need to move my fingers to move the mouse cursor), but I’d file that as a separate issue if it’s not working with the scrollbars enabled ;)

**Comment by shanselman** [comment]
This is still annoying, today in April of 2017 @bitcrazed @miniksa

**Comment by rcarmo** [comment]
Ditto. I'm still using mintty because of this.

**Comment by miniksa** [comment]
Thanks for your input. It is still on the backlog. We have limited resources on our team, and unfortunately this hasn't ranked high enough to be booked yet. Sorry about that. We hope to get to it in the future!

**Comment by timriker** [comment]
Are the sources available someplace in case a third party wants to create a patch that adds this?

**Comment by miniksa** [comment]
Not at this time. Sorry.

**Comment by timriker** [comment]
Thanks for the open response, @miniksa! I hope this make it through the backlog sometime soon. The recent improvements are appreciated.

**Comment by miniksa** [comment]
Me too! I wish I had 100 hands and the ability to open source any code I want so you all could help. But alas! Thanks for your enthusiasm about Bash on Windows! It means a lot to me and the entire team that you appreciate and enjoy our work!

**Comment by 0xMF** [comment]
I solved my problem by simply making the default settings for the initial window's Screen Buffer Size and Window Size to be the same value. I had to make this change once in the Default Settings then close and open the console window again.

Now whenever I open my initial window there is no scrollbar and I simply use Ctrl+Enter to go to full screen without the scrollbar. It's when I go back, with another Ctrl+Enter, to windowed-mode again after being in full screen that the scrollbar reappears but, really, why would you want to leave full screen? Heh! Sorry, I thought everybody did this and I was the only one that didn't. 😊

**Comment by wklm** [comment]
+1

**Comment by mkarpoff** [comment]
It would be tolerable if the scroll bar didn't cover console text in full screen mode. Yes it is highly annoying in window mode but in full screen if the scroll bar is there it hides 2 columns of text which actively hinders the usability of full screen.

**Comment by bitcrazed** [comment]
We hear ya and are looking forward to being able to turn our focus to improving more of the user-visible features of Console in the future, now that much of the core re-architecture work is nearing completion. 

Bear with us knowing that we're keen to fix these issues, but are a very small team with finite resources, and a mountain of debt to climb ;)

**Comment by int3l** [comment]
btw, it seems that this request feature is available in the **Window** options of mintty.
You can select the **None** option in the **Scrollbar** section.

Unfortunately this option is global, but as I can see, you can use custom .minttyrc config files for different instances of mintty.
So from my perspective, this issue is solved.

![Example setup image on Windows 7](https://i.imgur.com/h7NeWuy.png)

**Comment by rcarmo** [comment]
I don’t think this should be closed. @int3l found a workaround by using `mintty` (which I also use) but I think this feature should be added to the standard Windows console.

**Comment by int3l** [comment]
This is correct, it's a workaround. But I don't know how long it will take for the team to add such feature.
Thats's the reason why I posted it here :)

**Comment by timriker** [comment]
@0xMF please reopen this. Closing it because another product implements the suggested feature does not seem a wise move. Perhaps you have some other reason for closing this?

**Comment by 0xMF** [comment]
Reopening issue at @timriker request. I closed the issue because I solved my problem a long time (see my own workaround in thread) back but I can see how the absence of the option to disable the scrollbar (initially/always) from fullscreen might confuse/irritate/bother others.

**Comment by bitcrazed** [comment]
We're aware of this ask and are exploring options at this time. Bear with us.

**Comment by Macmee** [comment]
+1 I find the scroll bars in windows 10 to just be ugly in general. Would love to have a system wide feature to disable them completely like in MacOS.

**Comment by bitcrazed** [comment]
@Macmee - Please submit a suggestion to "Add option to remove scrollbars completely" via Feedback Hub where it'll be received by the shell team and considered for future releases.

For Console itself, we hear ya and will be considering this ask for future releases anyhow.

**Comment by tuyenpm9** [comment]
This workaround solution also completely break copy and paste using right-mouse.

**Comment by Jon-Galloway** [comment]
Not sure if this is still a thing for you guys but it was for me.  I found however that opening a command window in W10, right-clicking title-bar and choose Properties.  Then click Layout and set Height of Screen Buffer Size to that on Options tab (likely 50).  Hit F11 to maximize and execute:

wsl

Enjoy!  hth.

**Comment by rcarmo** [comment]
I’m still using wsltty because it lets me remove the scroll bar without side effects...

**Comment by yvd** [comment]
> I solved my problem by simply making the default settings for the initial window's Screen Buffer Size and Window Size to be the same value. I had to make this change once in the Default Settings then close and open the console window again.
> 
> Now whenever I open my initial window there is no scrollbar and I simply use Ctrl+Enter to go to full screen without the scrollbar. It's when I go back, with another Ctrl+Enter, to windowed-mode again after being in full screen that the scrollbar reappears but, really, why would you want to leave full screen? Heh! Sorry, I thought everybody did this and I was the only one that didn't. 😊

Detached from tmux and set the height in **Screen Buffer** to 1 as suggested [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/9l42u9/is_there_a_way_to_hide_the_scrollbar_in_ubuntu_wsl/egdrb48?utm_source=share&utm_medium=web2x). Went fullscreen now and reattached to tmux. Solved the issue, might have to repeat it if you reboot though.

**Comment by swdevbali** [comment]
> I solved my problem by simply making the default settings for the initial window's Screen Buffer Size and Window Size to be the same value. I had to make this change once in the Default Settings then close and open the console window again.

It's crazy how this simple trick solved this issue!
Don't forget to reopen the terminal for this.

Now WSL is a way to go in Windows 10 *nix development!

**Comment by PankajKushwaha** [comment]
Does anybody found any neat solution for this ? I tried workaround by 0xMF by changing "window's Screen Buffer Size and Window Size" , but doesn't seems working for me. Enabling WSL is not an option for me. Any suggestion?

**Comment by Jon-Galloway** [comment]
@PankajKushwaha I open a cmd prompt, hit F-11, and then enter command wsl. ¯\_(ツ)_/¯

**Comment by PankajKushwaha** [comment]
@Jon-Galloway Thanks for your reply , I meant It is my office laptop , enabling wsl is not allow by policy, I tried F-11 also Alt-Enter, but scrool bar is still there .  mobaxterm seems perfect for all the task but just this one small issue , it so annoying to see scroll bar in full screen mode.

**Comment by PankajKushwaha** [comment]
Finally found solution :)
Go to Settings>Terminal>Terminal Features>Display Scrollbar , turn off option , restart .
Its pure blessing to see complete full screen :) , Thanks everyone.

**Comment by davehouser1** [comment]
Is there anyway to make this feature a per-session feature? I don't want all my sessions to loose the scrollbar just a few of them that I full screen? I tried checking the sessions settings but I don't see the "display scrollbar" check box there. I assume this settings is global and its either on or off, true?
