### ISSUE TITLE
How to detect if running under WSL?

### ISSUE THREAD

**Issue by AgnerF** [microsoft/WSL#4071]
How do you detect if running under WSL?

C compilers in Mingw and Cygwin have preprocessing defines that allow you to identify the system. Is there a __WSL__ preprocessing define or some other method for identifying the system? If not, please make a preprocessing define that gives a WSL version number.

You may claim that this is a genuine Linux (Ubuntu or whatever), but it is not. The floating point control word is set to reduced precision, and this causes a lot of problems. (Why has issue #830 never been fixed?). Also, of course, there is no GUI in WSL.

**Comment by floodkoff** [comment]
I think your question should be addressed to the gcc or clang compiler team not WSL

**Comment by benhillis** [comment]
The Windows version is present in our kernel command line (/proc/version, or uname -a).

**Comment by xtremeperf** [comment]
if [[ $(grep Microsoft /proc/version) ]]; then
    echo "Bash is running on WSL"
fi

**Comment by AgnerF** [comment]
Thanks for the comments. I would like to detect WSL from a preprocessing directive when compiling a program. Something like #ifdef __WSL__. There are special versions of gcc for Mingw and Cygwin, but as I understand it, there is no special version of gcc for WSL. Is there any way that a __WSL__ define can be added automatically when the compiler is running under WSL?

**Comment by floodkoff** [comment]
@AgnerF it is a kind of define that you can do yourself. You don't need compiler support for that. Just generate config.h file using the build system of your choice. Here is how to do it in meson for example:
meson.build file
```
# meson.build
grep = find_program('grep')
runcmd = run_command(grep, '-q', 'Microsoft', '/proc/version')

confdata = configuration_data()
if runcmd.returncode() != 0
    confdata.set('WTL', 0)
else
    confdata.set('WTL', 1)
endif

configure_file(
    input : 'config.h.in',
    output : 'config.h',
    configuration : confdata)
```
config.h.in file
```
#mesondefine WTL
```
Meson will generate `config.h` with the following contents:
```
#define WTL 1
```
`WTL` define will be 1 under WTL and 0 under any other linux.

**Comment by therealkenc** [comment]
#423

**Comment by b-hayes** [comment]
Is there a way to determine the WSL1 vs WS2. I normally use the `uname -a` and check for Linux and Microsoft but both will say that.

**Comment by mirabilos** [comment]
@AgnerF the idea here is that **unmodified** Linux binaries run on WSL (and that binaries compiled on WSL are unmodified Linux binaries), so you’ll have to do a run-time check, not a compile-time check.

**Comment by flickerfly** [comment]
A little correction/update for what @xtremeperf said, you need to grep case insensitive. On my (maybe newer?) WSL, it is not a capital M, just "microsoft" so use this for greater confidence.

```
if [[ $(grep -i Microsoft /proc/version) ]]; then
    echo "Bash is running on WSL"
fi
```

**Comment by b-hayes** [comment]
@flickerfly its actually WSLv2 using lowecase from my experience. If Ya'll are interested here's what I use to detect all operating environments that I use.

```
#!/usr/bin/env bash

unameOut=$(uname -a)
case "${unameOut}" in
    *Microsoft*)     OS="WSL";; #wls must be first since it will have Linux in the name too
    *microsoft*)     OS="WSL2";; 
    Linux*)     OS="Linux";;
    Darwin*)    OS="Mac";;
    CYGWIN*)    OS="Cygwin";;
    MINGW*)     OS="Windows";; 
    *Msys)     OS="Windows";;
    *)          OS="UNKNOWN:${unameOut}"
esac

if [[ ${OS} == "Mac" ]] && sysctl -n machdep.cpu.brand_string | grep -q 'Apple M1'; then
    #Check if its an M1. This check should work even if the current processes is running under x86 emulation.
    OS="MacM1"
fi

echo ${OS};

```

**Comment by mirabilos** [comment]
Josiah Ritchie dixit:

>A little correction/update for what @xtremeperf said, you need to grep
>case insensitive. On my (maybe newer?) WSL, it is not a capital M, just
>"microsoft" so use this for greater confidence.
>
>```
>if [[ $(grep -i Microsoft /proc/version) ]]; then
>    echo "Bash is running on WSL"
>fi
>```

Define “maybe newer?”, because I have this:

	/* check uname first (this is improbable to fail) */
	if ((uerr = uname(&u)) == 0) {
		if (strstr(u.release, "Microsoft") != NULL) {
			/* pretty certainly WSL 1 */
			errno = e;
			return (1);
		}
		if (strstr(u.release, "microsoft") != NULL) {
			/* probably WSL 2 */
			errno = e;
			return (2);
		}
	}

This distinction is important (in this library, anyway).
I have access to a system with both WSL 1 and 2, but that
system is not going to be updated to Win11, so I might
miss out on latest changes. (For networking, WSL 1 is
better anyway.)

bye,
//mirabilos
-- 
Infrastrukturexperte • tarent solutions GmbH
Am Dickobskreuz 10, D-53121 Bonn • http://www.tarent.de/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 5168 • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by mirabilos** [comment]
b-hayes dixit:

>The difference changes between WSLv1 and WSLv2

Could you please explain that? What exactly changes?

Used to be (?) that
• "Microsoft" is WSL 1 with a very high probability
• "microsoft" is WSL 2 with good probability
• if uname contains neither, check environment variables
  – WSL_INTEROP is relatively certainly WSL 2
  – WSL_DISTRO_NAME is WSL; if uname check succeeded, WSL 1 was
    already caught above, so it’s WSL 2; if uname failed guess
    WSL 1 instead since WSL 2 would (also) have WSL_INTEROP set

Is this no longer correct?

bye,
//mirabilos
-- 
Infrastrukturexperte • tarent solutions GmbH
Am Dickobskreuz 10, D-53121 Bonn • http://www.tarent.de/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 5168 • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by b-hayes** [comment]
That's correct. The difference in case changes from WSL to WSLv2. As per my script above, WSLv2 uses lowercase.

**Comment by mirabilos** [comment]
b-hayes dixit:

>That's correct.

Huh, why did you write “The difference changes” then?

>The difference in case changes from WSL to WSLv2. As
>per my script above, WSLv2 uses lowercase.

Do you maybe mean the difference *is* in the changed case?

**Comment by b-hayes** [comment]
Yeah, that's what I meant sorry for the confusion.

**Comment by cuynu** [comment]
is there anyway to detect if running under WSL but for java jar runtime?

**Comment by b-hayes** [comment]
@cuynu you could run a shell command in Java and use the same approach as my script does: https://github.com/microsoft/WSL/issues/4071#issuecomment-1223393940

**Comment by durantschoon** [comment]
> if [[ $(grep Microsoft /proc/version) ]]; then echo "Bash is running on WSL" fi

this needs to be `grep -i Microsoft /proc/version` for case insensitive search now.

**Comment by RokeJulianLockhart** [comment]
I think this should be transferred to a https://github.com/microsoft/WSL/discussions/new?category=q-a.
