### ISSUE TITLE
apt-get update & apt-get upgrade somehow killed Windows subsystem for Linux

### ISSUE THREAD

**Issue by rfausey** [microsoft/WSL#4072]
I am running Ubuntu 16.04 LTS on Win 10. When I run apt-get update & apt-get upgrade, and then close the shell, I cannot restart the shell; all I get is a blank window with a blinking cursor. Something with the upgrade is killing Ubuntu.

**Comment by rfausey** [comment]
I am running Ubuntu 16.04 LTS on Win 10. When I run apt-get update & apt-get upgrade, and then close the shell, I cannot restart the shell; all I get is a blank window with a blinking cursor. Something with the upgrade is killing Ubuntu.

**Comment by mscraigloewen** [comment]
Hi @rfausey !

What version of Windows are you running? Are you running `apt-get update` and `apt-get upgrade` and then immediately closing the Window or are you letting them run and leaving the Window open? Does this issue happen with any other distributions?

**Comment by rfausey** [comment]
I am running version 1809 build 1776.529.  I ran a windows update so this is current for me as of right now.

> Are you running `apt-get update` and `apt-get upgrade` and then immediately closing the Window or > are you letting them run and leaving the Window open? 

Both commands complete, so I'm not exactly sure what you mean.

As a test I installed Debian from the MS Store.  I then ran 'apt-get update' the 'apt-get upgrade'.  The upgrade broke Debian & Ubuntu both.  I did not run an upgrade on Ubuntu just Debain.

I can not just remove the WSL package and re-install it.  I need to remove the package and remove the files in %USERPROFILE%\AppData\Local\Packages\

**Comment by mscraigloewen** [comment]
If you'd like to remove your WSL package and reinstall it (Please note: this will delete all the files that you have in your WSL distro!) you can use the command: 

`wsl --unregister <DistroName>`

And then you can reinstall the distro by opening up the app (like the Ubuntu app or Debian app etc.)

Could you try reinstalling and see if that fixes it? If not we can dive further into what may be causing this.

**Comment by mscraigloewen** [comment]
This also could be a related issue to #2352 and #4047

**Comment by rfausey** [comment]
Yes my issue is similar to [#2352](https://github.com/microsoft/WSL/issues/2352)

I don't have wsl installed, in the powershell I got a command not found.  
So I disabled 'Windows Subsystem for Linux' rebooted, 
then enabled 'Windows Subsystem for Linux'.  

I was able to run `apt-get update` and upgrade packages.
After some testing I have discovered `apt-get update` alone will kill bash. 
bash can not executed from an Linux shell or the PowerShell. 
Rebooting does fix this.

Installed wsl with apt-get.  I am getting a syntax error with the --unregister
option or no output.

**Comment by rfausey** [comment]
Hope this helps.

[lxcore.zip](https://github.com/microsoft/WSL/files/3232784/lxcore.zip)

**Comment by 1nj3cti0n** [comment]
Did you fix this? I have the exact same problem as #2352. Blank screen

**Comment by rfausey** [comment]
> 
> Did you fix this? I have the exact same problem as #2352. Blank screen

Not fixed but a workaround.  I disabled & enabled `Windows Subsystem for Linux` the reinstalled Ubuntu.

I couldn't get `wsl --unregister <DistroName>` to work.  The Linux binaries are located in `%USERPROFILE%\AppData\Local\Packages\' you could try deleting it and reinstalling.

Now when I run `apt-get update` & `apt-get upgrade` if I get a blank terminal rebooting fixes it.

**Comment by 1nj3cti0n** [comment]
> 
> 
> > Did you fix this? I have the exact same problem as #2352. Blank screen
> 
> Not fixed but a workaround. I disabled & enabled `Windows Subsystem for Linux` the reinstalled Ubuntu.
> 
> I couldn't get `wsl --unregister <DistroName>` to work. The Linux binaries are located in `%USERPROFILE%\AppData\Local\Packages' you could try deleting it and reinstalling.
> 
> Now when I run `apt-get update` & `apt-get upgrade` if I get a blank terminal rebooting fixes it.

Didn't work for me sadly

**Comment by mwbaxter11** [comment]
Hello there. WSL is great but I'm having a frequent reproducible problem where it gets into a bad state after an earlier usage. When it's bad, there is only a flashing cursor after typing 'bash' and WSL does not start similar to #2352. The bad state seems to happen after running a script which uses rsync to copy data from a remote server. The only cure appears to be to restart the PC. I'm running Ubuntu 16.04 and recently upgraded to Windows 1903 (build 18362.175) to try to fix the problem. That made the problem less prevalent, but it still happens frequently. Happy to give more info or diagnostics. Very grateful for any advice, comment or workarounds.

**Comment by offero** [comment]
I am getting a powershell error every time wsl tries to run a powershell command now after an apt-get upgrade/update. For example, I have neovim set up to run 
`powershell.exe -Command Get-Clipboard<CR>` as a leader command to paste from the system clipboard and I am seeing this error:

![image](https://user-images.githubusercontent.com/4681330/60035082-04aaf500-967a-11e9-9e4d-a1835bd9e58a.png)

**Comment by offero** [comment]
Okay a system reboot seems to have cleared up my problems. Sorry for the noise.

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
