### ISSUE TITLE
zsh: how to exit terminal other than exit to bash?

### ISSUE THREAD

**Issue by swun90** [microsoft/WSL#4074]
I added ` if [ -t 1 ]; then exec zsh fi` in `$HONE/.bashrc` and it worked well in startup, i.e. start zsh automatically.
But question is, every time I `exit` in zsh, it exits to bash. not exiting the terminal. So I have to exit twice.
I think I've read the solution somewhere, I searched for quite a lot time, but I couldn't find it now.
I use ConEmu, perhaps related to the software's feature?

**Comment by Biswa96** [comment]
Make zsh default shell.

**Comment by benhillis** [comment]
Instead of running zsh from your bashrc, change your default shell via chsh:
https://linux.die.net/man/1/chsh

**Comment by swun90** [comment]
Funny thing is, it now exits the terminal other than to bash, before I use `chsh` command. Perhaps a windows reboot?

Also I thought the WSL was different from Linux/GNU? I run `chsh -s zsh`, but `echo $SHELL` gave me `/bin/bash`.

**Comment by benhillis** [comment]
Can you describe what you are doing?

**Comment by swun90** [comment]
I restarted the windows, and started the WSL. It went into zsh automatically, and `exit` command just exited the terminal.
Not sure whether the command `chsh -s zsh` was needed or not. Coz I typed it before restart.
