### ISSUE TITLE
Line wrap / overwriting previous lines

### ISSUE THREAD

**Issue by c-en** [microsoft/WSL#4075]
Microsoft Windows [Version 10.0.17134.765]

Ubuntu 18.04 LTS, from the Windows Store

When I type a long command into the terminal, it doesn't wrap to the next line as it should, it wraps to the beginning of the same line and starts overwriting. *functionally* it seems to be fine, the command still seems to be fully there, I just can't see what I've been typing. Also, if I type a long command / go to long command in history, and press the up key to cycle away from the long command to a previous command, then an entire line vanishes - the 0th line (bottom, where I've been typing) replaces the 1st line (one right above with the last command entered or the output of the last command, that shouldn't be edit-able), and the 1st line disappears.

**Comment by mscraigloewen** [comment]
Hi @c-en , this appears to be an issue related to Windows Console/Terminal since it's related to the rendering and visuals, etc.

I'd recommend that you open an issue on the [Windows Terminal](https://github.com/microsoft/console/issues) page describing your problem and they'd be able to help you!
