### ISSUE TITLE
Error: 0x80070005 -- tried all past solutions

### ISSUE THREAD

**Issue by gobbedy** [microsoft/WSL#4077]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.1087]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
bash.exe

* What's wrong / what should be happening instead:
Error: 0x80070005
Press any key to continue...

* Things I've tried from previous issue suggestions
I tried this command
powershell get-cipolicyinfo

And got:
Options HVCIOptions Version PolicyGuid
------- ----------- ------- ----------
      0           0       0 {0, 0, 0, 0...}

So no x10, which others have reported as causing the issue.

I checked the contents of C:\Windows\System32\CodeIntegrity:
driver.stl
bootcat.cache

So no "SIPolicy.p7b" which others have reported as causing the issue.

I also tried running wsl.exe but got the same error. Only difference is that it prints "Error: 0x80070005" then hangs (No "Press any key to continue...")

Finally, I tried running as administrator. Same error.

**Comment by mscraigloewen** [comment]
Hi @gobbedy , from your Windows Version it looks like you're on a much older version of Windows (on the Fall Creator's Update), are you able to update to a more current version? I think this is the best way to resolve your issue.

**Comment by gobbedy** [comment]
Hi @mscraigloewen, thank for answering quickly.

I will ask our IT on Monday, but given that I work in a government lab and that there is red tape surrounding most requests, I can say with almost total certainty that I will be unable to upgrade my version of Windows within a reasonable timeframe.

Can you tell me the minimum version of Windows I should request to avoid most WSL issues?

**Comment by gobbedy** [comment]
Hi @mscraigloewen, I asked our local IT team, and they say it would be low priority for them to address.

They said I should submit a request to our central IT to ask for the "latest" Windows version. I've submitted a ticket, but it can take weeks to get a reply, and I suspect the reply will be that for now Fall Creators is the only supported version of Windows (my computer is brand new, so I suspect they loaded it with the latest version that central IT supports).

Would it be possible to investigate this issue without requiring a Windows upgrade on my end?

While I do have an older version (Redstone 3), it is the latest build (16299), and since it is the Enterprise edition, it is after all still supported until April 2020. :)

**Comment by mscraigloewen** [comment]
Looking into this, there are some similar issues (like #3020 ) and they have a mix of either being based on installation, or being fixed in later version of Windows (like issue 3020 is). 

In terms of things you can try right now, you can verify the health of your components by opening a Powershell window with admin privileges and running this command: 

`dism /online /cleanup-image /restorehealth`

**Comment by gobbedy** [comment]
Hi @mscraigloewen,

Thanks for your even quicker reply than last time.

I ran the ```dism /online /cleanup-image /restorehealth```

The command hangs, after giving the following output:
```
PS C:\Users\Perraultag> dism /online /cleanup-image /restorehealth

Deployment Image Servicing and Management tool
Version: 10.0.16299.15

Image Version: 10.0.16299.1087


```

Should I get the lxcore logs for this new issue?

To clarify the question of how old my Windows Versions is, I'm on build 16299.1087 -- which became available April 9, 2019 according to the microsoft page: https://docs.microsoft.com/en-us/windows/release-information/.

Are fixes to WSL not propagated to all supported versions?

PS. I had read all #3020 and already tried all the solutions that are in my control, including disabling/enabling Hyper-V.

**Comment by mscraigloewen** [comment]
Yes I think the logs would be helpful!

You can find the instructions on how to do so [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). You can then email them to me at: crloewen@microsoft.com .

**Comment by gobbedy** [comment]
Hi @mscraigloewen, actually I was just too impatient and killed the ```dism``` command too soon.

I've updated my previous reply with the output of the command.

I also tried rerunning ```bash``` but I get the same error as before, ie:
```
Error: 0x80070005
Press any key to continue...
```

Should I try rebooting?

**Comment by mscraigloewen** [comment]
Yes please, and if you still have the issue, run the logs and then send them over and we can take a look.

**Comment by gobbedy** [comment]
The issue is still present after reboot. I e-mailed you the logs :)

**Comment by WSLUser** [comment]
> Are fixes to WSL not propagated to all supported versions?

That is correct. Unless BSOD or security related, backports rarely occur. FCU may tout "official support" but I just mentioned the official support. Major factor that's always been mentioned are changes to the NT kernel which can't be propagated to earlier versions of Windows.

**Comment by stdying** [comment]
run Power Shell as administrator
