### ISSUE TITLE
qemu-ppc-static segmentation fault

### ISSUE THREAD

**Issue by spinosae** [microsoft/WSL#4085]
* Your Windows build number: 

Microsoft Windows [Version 10.0.18362.145]

* What you're doing and what's happening:

I was trying to run a cross compiled hello-world program (statically linked) in WSL via qemu-ppc-static. It failed with segmentation fault. To reproduce, extract hello-ppc from [hello_world.zip](https://github.com/microsoft/WSL/files/3260272/hello_world.zip).
```
sudo apt install qemu-user-static
qemu-ppc-static -cpu e500 hello-ppc
```
* What's wrong / what should be happening instead:

It should print "Hello World!" on screen. In fact, if I compile the program for arm and run it with qemu-arm-static, it worked. So the problem is unique to qemu-ppc-static.

* Strace of the failing command, if applicable:  

Strace was attached in  [hello_world.zip](https://github.com/microsoft/WSL/files/3260272/hello_world.zip).

**Comment by therealkenc** [comment]
Thanks for the submission. Confirmed. My strace looks like:
```
[pid  5128] mprotect(0x625e2000, 4096, PROT_NONE) = 0
[pid  5128] uname({sysname="Linux", nodename="DESKTOP-4UTIQSF", ...}) = 0
[pid  5128] brk(0x63ed3000)             = 0x63ed3000
[pid  5128] mmap(0x7fb747b93000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb747b93000
[pid  5128] mmap(0x7fb747b94000, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb747b94000
[pid  5128] mprotect(0x7fb747b8c000, 4096, PROT_READ|PROT_EXEC) = 0
[pid  5128] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7fb747b8c918} ---
[pid  5128] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid  5128] rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], NULL, 8) = 0
[pid  5128] prlimit64(0, RLIMIT_CORE, NULL, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
[pid  5128] prlimit64(0, RLIMIT_CORE, NULL, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
[pid  5128] prlimit64(0, RLIMIT_CORE, {rlim_cur=0, rlim_max=RLIM64_INFINITY}, NULL) = 0
[pid  5128] futex(0x625fdc40, FUTEX_WAKE_PRIVATE, 2147483647) = 0
[pid  5128] write(2, "qemu: uncaught target signal 11 "..., 67qemu: uncaught target signal 11 (Segmentation fault) - core dumped
) = 67
[pid  5128] rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x60190d50}, NULL, 8) = 0
[pid  5128] getpid()                    = 5128
[pid  5128] kill(5128, SIGSEGV)         = 0
[pid  5128] rt_sigsuspend(~[SEGV RTMIN RT_1], 8) = ? ERESTARTNOHAND (To be restarted if no handler)
[pid  5128] --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=5128, si_uid=1000} ---
```

Your `hello` binary takes on Real Linux, so there is some diverge here. It would take compiling `qemu` with debug symbols and firing it up under `gdb` to see where it goes south. You are on bleeding edge WSL already so you'll probably find joy in a few weeks with WSL2.

**Comment by DanPinGF** [comment]
@therealkenc - Seems like this issue hasn't had any activity for merely two years. It should be tagged with 'needs-author-feedback' and let it sit there, having the issue to be closed. Not too sure if the author has found a fix... :\

**Comment by the-moog** [comment]
> This seems to be an old issue. Please try to use WSL2.
I am.  And I am using ARM not PPC, but I get the same error.  I fixed it by changing the memory back-end to disk, pre-allocated.  For some reason the VM memory can't be allocated in RAM.
