### ISSUE TITLE
Mouse scrolling stopped working

### ISSUE THREAD

**Issue by sierratango88** [microsoft/WSL#4086]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.145]

* What you're doing and what's happening:  
1. Open a WSL Ubuntu terminal from the Ubuntu shortcut
    OR
    Open command prompt and run `ubuntu`
2. Use any command to increase screen buffer size (e.g., `ls -l /`) so that content is out of view
3. Attempt to scroll up using mouse wheel

* What's wrong / what should be happening instead:
The content in the window does not scroll when the window is focussed / active. However, if the window loses focus / becomes inactive then scrolling will work. What should happen is that the content should scroll when the window is active. 

The problem seems to have appeared after the recent Windows 10 1903 update. I have tried reinstalling WSL Ubuntu to no avail. I have also confirmed the issue on another Windows 10 1903 machine. However, the issue is not present when running `ubuntu` in a PowerShell window.

**Comment by therealkenc** [comment]
Look like could be [msft/terminal#137](https://github.com/microsoft/terminal/issues/137). Mouse wheel scrolling works in general or heads would explode (works here), but seems others have experienced something similar. The Console aka Terminal tracker would be the place to follow-up.
