### ISSUE TITLE
1903 regression: chromedriver can not start through a symlink

### ISSUE THREAD

**Issue by PetterS** [microsoft/WSL#4088]
See https://superuser.com/questions/1446085/chromedriver-fails-inside-wsl-after-updating-windows-to-1903/1446091#1446091

I had `chromedriver.exe` in a Windows folder with a symlink to it in WSL. Before 1903, I could type `chromedriver --version` and it would print the version information as expected.

After upgrading to WSL, `chromedriver --version` returned 1 with no output.

The workaround is to start chromedriver directly without going through a symlink,

**Comment by Biswa96** [comment]
Duplicate #3999.

**Comment by PetterS** [comment]
> Duplicate #3999.

Thanks! Let's close this.
