### ISSUE TITLE
Buggy Characters in shell

### ISSUE THREAD

**Issue by MattixNow** [microsoft/WSL#4089]
Microsoft Windows [version 10.0.17763.503]

When i use zsh or fish buggy characters appear, any solution ?
![image](https://user-images.githubusercontent.com/32040951/59121300-05444b80-8958-11e9-9bf7-06ace1a0815d.png)
![image](https://user-images.githubusercontent.com/32040951/59121352-2a38be80-8958-11e9-9ee6-bab1d61d976d.png)

**Comment by mscraigloewen** [comment]
Hi @MattixNow those are due to the fact that you don't have a Powerline font. 

Here are some instructions on how to [install and use powerline fonts for WSL](http://iamnotmyself.com/2017/04/15/setting-up-powerline-shell-on-windows-subsystem-for-linux/). (Thank you Bobby Johnson for writing them!)
