### ISSUE TITLE
Absolute paths are translated incorrect from WSL to Win

### ISSUE THREAD

**Issue by carlolars** [microsoft/WSL#4091]
**Please fill out the below information:**
* Your Windows build number:  10.0.17134.765
* wsl.conf:  
```
[automount]
enabled = true
root = /
options = "metadata,umask=022,fmask=111,case=off"
```

* What you're doing and what's happening:
`$ notepad.exe /c/Users/carl-oskar/workspace/example/readme.txt`

* What's wrong / what should be happening instead:
Instead of notepad opening the file it shows an error message box stating that the path could not be found.  
If using *notepad++.exe* instead it shows an error message box that says
*"C:\c\Users\carl-oskar\workspace\example\readme.txt" cannot be opened:
Folder "C:\c\Users\carl-oskar\workspace\example" doesn't exist.*

I tried with changing the mount root back to */mnt/* but it still failed but now with *C:\mnt\c\...*.

If using a relative path to open the file in notepad then the file opens as expected.

**Comment by benhillis** [comment]
We don't automatically translate any command line arguments, but you can use wslpath to do this for you.

`notepad.exe  $(wslpath -w /c/Users/carl-oskar/workspace/example/readme.txt)`

**Comment by carlolars** [comment]
Ah I see.  
I noticed that the 'C:' is prefixed on the windows side, doing Win-R with  
`notepad++.exe /c/Users/carl-oskar/workspace/example/readme.txt`  
yielded the same problem with the path being *"C:\c\Users\..."*

Unfortunately I was actually trying to do something like  
`GIT_SEQUENCE_EDITOR="/c/Program\\ Files/Notepad++/notepad++.exe" git rebase -i HEAD~3`  
but for another editor.

The "problem" line in the _git-rebase--interactive_ script is  
`eval "$GIT_SEQUENCE_EDITOR" '"$@"'`  
Changing the line to  
`eval "$GIT_SEQUENCE_EDITOR" '"$(wslpath -w $@)"'`  
makes the file open as expected.

But I suspect that it is probably easier to get the author of the editor to adjust for wsl support than to get the git authors to adjust for this.

Thanks
