### ISSUE TITLE
Unable to run Pengwin distro, error 0x80070002

### ISSUE THREAD

**Issue by jkunkee** [microsoft/WSL#4093]
After a long period of being in the Insider Program, I settled on the 1903 release and later decided to try Pengwin (a WSL distro) on my device. It fails.

More specifically, repro steps:
1. Install Pengwin from the Store
2. Navigate to and select Pengwin in the Start Menu
3. Observe error

```
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.
```

4. Similarly run Ubuntu 18.04.
5. Observe that WSL starts correctly.

Other diagnostic info:

* `>ver`
  `Microsoft Windows [Version 10.0.18362.145]`
* Detailed logs:
[wsl-pengwin-issue.zip](https://github.com/microsoft/WSL/files/3268058/wsl-pengwin-issue.zip)

I have already tried:
* uninstalling and reinstalling both distros
* disabling/enabling WSL in the Enable Features dialog

Related tweet:
https://twitter.com/jkunkee/status/1133086982832238593?s=20

**Comment by benhillis** [comment]
Thanks Jon, I will take look at the traces on Monday.

**Comment by benhillis** [comment]
I took a look at the trace and don't see any evidence that WslRegisterDistribution is making it to the service.  This leads me to believe that the tar file that is being specified by the Pengwin app is not present.  @sirredbeard, can you double check that the name of the tar.gz file in your appx matches what is being used in the WslRegisterDistribution call?

**Comment by sirredbeard** [comment]
Odd.

@benhillis I double-checked. Everything is in the right place. Have not made any changes there that would cause an issue. No other reports of this either.

**Comment by jkunkee** [comment]
If it helps, this is on an ARM64 HP Envy x2. The version reported in Settings for Pengwin is 1.2.4.0. I'm happy to pull logs or put things under a debugger.

**Comment by hMounir** [comment]
I converted mine when I run the command as administrator

**Comment by jimp02** [comment]
The new version of Pengwin uses port 2222 instead of 22.
Check the following and change if wrong.
Options > Cross Platform > Connection Manager, local host port should be 2222.
The OS column in the connection manager should show "Debian (x64)".

If this works you won't be able to run Ubuntu.
Set up a new connection with a different name and port 22.
The OS column in the connection manager should show "Ubuntu".

**Comment by jkunkee** [comment]
Some time later on updated 1903 it just started working...

**Comment by jimp02** [comment]
Don't know if it makes a difference but...
I had to reinstall Pengwin a couple of days ago.
It installs with port 22.
This is changed to 2222 by a program in pengwin-setup.
Some users will have port 22, and some will have 2222.
