### ISSUE TITLE
Running "wsl.exe --upgrade" from inside WSL itself renders distribution inaccessible

### ISSUE THREAD

**Issue by iconmaster5326** [microsoft/WSL#4094]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.145]

* What you're doing and what's happening: Running the following commands:

```
wsl.exe # to enter WSL bash
wsl.exe --upgrade Legacy  # upgrading my WSL... While in WSL. Oops!
```

* What's wrong / what should be happening instead: The terminal window immediately closed. Now, whenever I try to start WSL, I get the following message: `An install, uninstall, or upgrade is in progress for this distribution.`. No upgrades are actually in progress, or at least that is what Task Manager reports.

* Strace of the failing command, if applicable:  Not applicable.

* Detailed logs: [LOGS.zip](https://github.com/microsoft/WSL/files/3268444/LOGS.zip)

* Addendum: Yes, I understand this is an extremely bad idea, what I did just did. I can safely say that mistakes were made. But I'm hoping my distribution can be recovered.

**Comment by benhillis** [comment]
Thanks for reporting, we have recently removed the upgrade functionality from wsl.exe and wslconfig.exe.  The new WslFs file system will be the default for new installations.

**Comment by Biswa96** [comment]
But the old "Legacy" Ubuntu installation (i.e. LxFs) appears in LxssManager.

**Comment by Biswa96** [comment]
But the old "Legacy" Ubuntu installation (i.e. LxFs) appears in LxssManager. Will it be deprecated or removed in future?

**Comment by benhillis** [comment]
@Biswa96 - No we will not be removing it.

**Comment by joewood** [comment]
Is there any way to recover the distribution?

**Comment by vadimbo** [comment]
I just run in exactly the same problem. How to recover the distribution, please help. If I run wslconfig.exe /upgrade then it just displays "Upgrading..." and it seems like nothing else happens.
```
    PS C:\WINDOWS\system32> wslconfig.exe /upgrade "Ubuntu-16.04"
    Upgrading...
```

**Comment by h4de5** [comment]
+1
can somebody PLEASE say that it can be recovered?
