### ISSUE TITLE
Upgrade to WslFs does not complete after many hours.

### ISSUE THREAD

**Issue by abalter** [microsoft/WSL#4095]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
**Microsoft Windows [Version 10.0.18362.145]**

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

`wsl --upgrade Ubuntu`

```
C:\Users\ariel>wsl --list --running
There are no running distributions.

C:\Users\ariel>wsl --list --all
Windows Subsystem for Linux Distributions:
Ubuntu (Default)

C:\Users\ariel>wsl
An install, uninstall, or upgrade is in progress for this distribution.
```

* What's wrong / what should be happening instead:

Process does not complete after many hours.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by mscraigloewen** [comment]
Could you collect some detailed logs for us when you run `wsl` or `wsl --upgrade Ubuntu`? 

Details on how to do so are [here](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). 

Thanks!

**Comment by benhillis** [comment]
We have recently removed the wslconfig /upgrade functionality because it can cause these types of issues.

**Comment by abalter** [comment]
Sorry I didn't respond to this. As it happened, I applied the May update over the weekend. On Monday, my laptop started acting a little funny, so I did the first logical thing which was to restart. When it booted back up it had unlinked my account from my profile. All of my files were there, but my account could no longer point to them. I tried to fix this in the registry. Upon restarting again, all of my data was wiped.

So I immediately shut down, swapped out my drive, and rebuilt my system (fortunately, virtually everything I needed was in cloud storage or version control).

The good news is that I'm no longer having a problem upgrading my WSL installation! Lemonade!!!

However, I was wondering if there is a simple way to tell if my WSL is the new filesystem or the old right now. I know I was at 1903 (October update) when I installed WSL, but not sure if the May updated had been applied yet.

That should probably be a new issue...

**Comment by benhillis** [comment]
@abalter  - We are no longer supporting inplace upgrades from LxFs to WslFs.  However in 1903 WslFs is the default for new installations.

**Comment by abalter** [comment]
But suppose I had the v1903 but not yet the May update. Is my WSL still the WslFs version? Can I check somehow?

**Comment by benhillis** [comment]
You will be able to see by running "mount"

```
ben@BENHILL-STUDIO:/mnt/c/Users/benhill$ mount
rootfs on / type lxfs (rw,noatime)
```

**Comment by abalter** [comment]
```
(base) balter@spectre:/mnt/c/Users/ariel$ mount
rootfs on / type wslfs (rw,noatime)
```

Yay!

Thanks @benhillis!!!
`

**Comment by SharakPL** [comment]
> 
> 
> We have recently removed the wslconfig /upgrade functionality because it can cause these types of issues.

It doesn't look "removed", because I've just run `wsl --upgrade ubuntu` and I can't access WSL in result. Whole upgrade process failed stating some Vuejs related npm package's folder is not empty. Now every time I hit `wsl` I get:
````
An install, uninstall, or upgrade is in progress for this distribution.
````
How can I fix it?
