### ISSUE TITLE
import/export issue

### ISSUE THREAD

**Issue by delcata** [microsoft/WSL#4096]
Hello,
I'm trying to export my distro from my desktop to use on my laptop, so I use wsl --export command but after doing that, when I try to import it on my laptop, I don't find any distro exe like (debian.exe, ubuntu.exe,pengwin.exe) and if I try to use my distro with bash.exe or cmd I can't change the default user from root and every time my bash start with system32 path , please how can i resolve that or using the importing/exporting feature properly?

**Comment by therealkenc** [comment]
#3974
