### ISSUE TITLE
Error 0x8007007b installing Debian package 1.1.3.0

### ISSUE THREAD

**Issue by b-spencer** [microsoft/WSL#4098]
**Please fill out the below information:**
* Your Windows build number:  Version 10.0.17763.503

* What you're doing and what's happening:  Installing the Debian 1.1.3.0 package with WSL enabled
0. Downloaded the installation package from https://aka.ms/wsl-debian-gnulinux as per https://docs.microsoft.com/en-us/windows/wsl/install-manual
1. In powershell, `start .\DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx` 
2. Get pretty window with "Launch" button and click that.
3. Get a command window with this in it:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007007b
Error: 0x8007007b The filename, directory name, or volume label syntax is incorrect.

Press any key to continue...
```

* What's wrong / what should be happening instead: It should install.

* For WSL launch issues, here are the detailed logs: [logs.zip](https://github.com/microsoft/WSL/files/3279289/logs.zip)

WSL is enabled:
```
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux
```

**Comment by b-spencer** [comment]
I used the Windows Store to install it (after uninstalling whatever I had with powershell) and that just worked.

**Comment by Royal-Oak** [comment]
I have encountered the same problem when I installed it in D: drive by using Windows Store.By looking at [Microsoft's installation instructions,](https://docs.microsoft.com/en-us/windows/wsl/install-win10) I found that WSL and Linux must be installed on the same drive. After changing the installation location to C, the initialization is successful. Hope useful to you.
