### ISSUE TITLE
/bin/sh missing

### ISSUE THREAD

**Issue by Lagicrus** [microsoft/WSL#4100]
* Your Windows build number:  10.0.17763.504

* What you're doing and what's happening:  Opening WSL by typing "ubuntu" into windows search to open it

* What's wrong / what should be happening instead: I get printed at the top my terminal `-bash: /usr/bin/lesspipe: /bin/sh: bad interpreter: No such file or directory`
Typing in bash into terminal gives me: `bash: /usr/bin/lesspipe: /bin/sh: bad interpreter: No such file or directory`
Running `sudo apt update` gives me errors, 
* `Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_InRelease`
* `GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_InRelease`

* Strace of the failing command, if applicable:  Running `strace -o bash.strace -f bash` gives 
`bash: /usr/bin/lesspipe: /bin/sh: bad interpreter: No such file or directory`

**Comment by Lagicrus** [comment]
I have reinstalled WSL multiple times now after a few errors and this is how I fixed it last time. It was working fine a few hours ago but then I restarted and it broke

**Comment by Lagicrus** [comment]
Unsure what I can do to repro it. Currently, all I do is open up the Ubuntu app and I get `-bash: /usr/bin/lesspipe: /bin/sh: bad interpreter: No such file or directory` Printed at the top of my terminal.

**Comment by gb-git** [comment]
I am looking to solve the same issue.

**Comment by gb-git** [comment]
I solved my problem on Windows 10 Pro Bash for Windows. I selected Ubuntu 18.04 LTS.

Symptom: get the error message  "bash: /usr/bin/lesspipe: /bin/sh: bad interpreter: No such file or directory" when opening an Ubuntu shell. This did not happen immediately when I installed it, but appeared after I rebooted my Windows (version 10.0.18363).

I tracked the problem down to /bin/dash which does not exist. I fixed the problem with:
# use bash as a temporary dash
cd /bin
sudo cp bash dash
sudo apt-get install --reinstall dash
