### ISSUE TITLE
error to occur at powershell for Enable-WindowsOptionalFeature command

### ISSUE THREAD

**Issue by dryworld** [microsoft/WSL#4108]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

my ver result at cmd
Microsoft Windows [Version 10.0.17134.829]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

the command for wsl2 result at powershell

PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Enable-WindowsOptionalFeature : Feature name VirtualMachinePlatform is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand* 

Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

**Comment by OmriSama** [comment]
Don't you have to be on the latest Windows version for this to work?

**Comment by dryworld** [comment]
my systeminfo result next follow, is this latest?

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

**Comment by dryworld** [comment]
latest windows version is 1903 so I will upgrade now and then try again.

**Comment by dryworld** [comment]
It works!

very nice performance, thanks Microsoft :)

**Comment by navigaid** [comment]
On a side note, if you are not using the latest windows insider build, you can still try out wsl2 in a hyper-v virtual machine.

1. download windows insider build 18917 from [here](https://uupdump.ml/selectlang.php?id=34ab8c79-fa34-490a-88b0-e6bd148d03b5) 
2. create a hyper-v virtual machine with the downloaded image
3. [enable nested virtualization](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq?WT.mc_id=thomasmaurer-blog-thmaure#can-i-run-wsl-2-in-a-virtual-machine) for that virtual machine on your host
4. [install wsl2](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) in the virtual machine

**Comment by machinshin** [comment]
is there any performance difference between the 2 methods? 

I ask because my employer has a custom update schedule (not sure what it is) but we're a bit behind version-wise.

**Comment by baselbj** [comment]
WSL 2 needs Windows 10 Insider Preview Build 18917 or higher so  you should update to latest windows release please check this link to update:
https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-update
