### ISSUE TITLE
WSL2: Can't exec files on non-NTFS drives.

### ISSUE THREAD

**Issue by 0xbadfca11** [microsoft/WSL#4109]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:
E: is NTFS, mounted on /mnt/e.
F: is FAT32, mounted on /mnt/f.
```bash
# cp /usr/bin/id /mnt/e/
# cp /usr/bin/id /mnt/f/
# /mnt/e/id
uid=0(root) gid=0(root) groups=0(root)
# /mnt/f/id
-bash: /mnt/f/id: Invalid argument
```
* What's wrong / what should be happening instead:
Same output result.

**Comment by benhillis** [comment]
@SvenGroot could you please take a look at this one?

**Comment by lazerl0rd** [comment]
@0xbadfca11 AFAIK you can’t exec on a FAT32 system due to fs limitations. This is common with Android OTG too. See here https://askubuntu.com/questions/23128/how-do-i-execute-a-file-from-a-fat-usb-drive.

**Comment by SvenGroot** [comment]
Thanks for reporting this. This is a bug in WSL 2 and I'm working on a fix.
