### ISSUE TITLE
Debian wsl bash crashes at Installation via debian.exe

### ISSUE THREAD

**Issue by ashiwalv** [microsoft/WSL#4110]
**Issue**
* I was trying to Install WSL for Debian on Window 10 and encountering the problem of crashing whenever I start debian.exe file.

**Things I have tried so far**
* Windows build number:  Version 10.0.17763.503

* Enable Developer Mode but it encounters with **Error no 0x800f0954 as "**D**eveloper mode is turned on. However, remote development and Windows Device Portal couldn't be found in Window Update, so they're not available. Error Code 0x800f0954** ", my window store is blocked from IT department so I guess this error is because of that, but I not sure if it has any effect on Installation of **Debian WSL**. 

A screenshot is attached here!
![1](https://user-images.githubusercontent.com/3264554/59415811-7eaec480-8dc4-11e9-93d1-3a3e761e7b73.png)
* I also activated "Windows Subsystem for Linux" at "Turn Window features on and off" and rebooted the PC so WSL is activated but if I try to check it via PowerShell, it through this error(Attached Screenshot).
![2](https://user-images.githubusercontent.com/3264554/59416013-dd743e00-8dc4-11e9-9d01-579d41b38fd8.png)

* I followed the process as per "https://docs.microsoft.com/en-us/windows/wsl/install-on-server" until unzip and then after double clicking on debian.exe, the bash get crash.

* I tried the same procedure with OpenSUSE and Ubuntu and it worked with them but it does not work with Debian.

* I saw some forum entries and found to uninstall by lxrun command in power shell or cmd prompt but my system can not recognize lxrun cmd too!

Any command or experience with debian will be helpful.

Thanks!

Best Regards,
Virendra

**Comment by benhillis** [comment]
Your Windows build does not need Developer Mode to run Windows Subsystem for Linux.  If you do not see wsl.exe or bash.exe in \Windows\System32, the "Windows Subsystem for Linux" optional component is not installed.  Could you verify it is enabled and there were not errors enabling it?

**Comment by ashiwalv** [comment]
wsl.exe is there at \Windows\System32 and there were no errors while enabling WSL!
