### ISSUE TITLE
'  Unknown error executing apt-key'

### ISSUE THREAD

**Issue by geev-gv** [microsoft/WSL#4113]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.17134.829]

* What you're doing and what's happening: root@DESKTOP-HSG3SE7:~# clear
root@DESKTOP-HSG3SE7:~# apt update
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://ftp.debian.org/debian stretch-backports InRelease [91.8 kB]
Get:3 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:4 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2,434 B]
Err:3 http://security.debian.org/debian-security stretch/updates InRelease
  Unknown error executing apt-key
Err:4 http://deb.debian.org/debian stretch-updates InRelease
  Unknown error executing apt-key
Err:2 http://ftp.debian.org/debian stretch-backports InRelease
  Unknown error executing apt-key
Ign:6 http://deb.debian.org/debian stretch Release.gpg
Reading package lists... Done
W: GPG error: http://security.debian.org/debian-security stretch/updates InRelease: Unknown error executing apt-key
E: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian stretch-updates InRelease: Unknown error executing apt-key
E: The repository 'http://deb.debian.org/debian stretch-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ftp.debian.org/debian stretch-backports InRelease: Unknown error executing apt-key
E: The repository 'http://ftp.debian.org/debian stretch-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian stretch Release: Unknown error executing apt-key
E: The repository 'http://deb.debian.org/debian stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@DESKTOP-HSG3SE7:~#

 

* What's wrong / what should be happening instead: WsL on WoA 10 (on a Raspberry Pi 3B ,SBC) worked before including the installation of LAMP.
The same error happens on Ubuntu 18.04 too..

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> Your Windows build number: Microsoft Windows [Version 10.0.17134.829]

#3286
