### ISSUE TITLE
Release file for repository is not valid yet

### ISSUE THREAD

**Issue by salaxander** [microsoft/WSL#4114]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  Attempting to run a `sudo apt update` within a WSL 2 installation. Seeing thing following error

[sudo] password for xander:                                                                                             Hit:1 https://packages.microsoft.com/repos/azure-cli bionic InRelease                                                   Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                 Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                             Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                       Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                               Reading package lists... Done                                                                                           E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 10h 29min 48s). Updates for this repository will not be applied.                                                    E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 11h 0min 22s). Updates for this repository will not be applied. 

Based on my own searching, I suspect the WSL clock may be falling out of sync with my windows machine? Though trying to cat `/etc/localtime` causes WSL to hang

* What's wrong / what should be happening instead: apt should run an update with no error output

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
What do the following commands return?

date
cmd.exe /c time /t
readlink /etc/localtime

What is your Windows timezone?  Any interesting errors in sudo dmesg?

**Comment by salaxander** [comment]
Thanks for the reply!
```
~ date 
Wed Jun 12 19:29:19 PDT 2019 
```
```
~ cmd.exe /c time /t                                                                                                 '\\wsl$\Ubuntu\home\xander'                                                                                             
CMD.EXE was started with the above path as the current directory.                                                       UNC paths are not supported.  Defaulting to Windows directory.                                                          09:14 AM
```
```
~ readlink /etc/localtime                                                                                            /usr/share/zoneinfo/America/Los_Angeles
```
The only thing that catches my eye in `sudo dmesg` is
```
[    0.606657] hv_utils: cannot register PTP clock: 0
```

**Comment by benhillis** [comment]
Thanks, does Ameria/Los_Angeles match your Windows time zone (Pacific)?

**Comment by salaxander** [comment]
It does indeed! For what it's worth, I was also selfhosting a build with WSL 2 about a month ago (I work at Microsoft 😄), and I encountered the same issue, sorry for not reporting it to the team sooner!

**Comment by trondhindenes** [comment]
Can repro. My windows computer is in CET, but WSL2 gives a completely different utc time altho `/etc/localtime` seems to be correctly set to `Europe/Berlin`

**Comment by benhillis** [comment]
This seems to have to do with clock drift.  If you shut down wsl and restart, is the problem solved?

wsl.exe --shutdown

**Comment by salaxander** [comment]
That does seem to resolve the issue for now. Running `date` shows the correct time. I'm still seeing `[    0.531827] hv_utils: cannot register PTP clock: 0` when running a `sudo dmesg` though (not sure if that's consequential or not). I'll report back if things fall out of sync again.

**Comment by therealkenc** [comment]
Laptop? Did it sleep? Maybe related [this](https://superuser.com/questions/1312335/why-doesnt-my-debian-hyper-v-guest-update-time-after-host-sleeping). WAG.

**Comment by mithunshanbhag** [comment]
Running into this same issue when running `sudo apt update && sudo apt upgrade` (Ubuntu 18.04 with WSL2).

Definitely some clock drift issue as the date command is returning the wrong time. 

Shutting down WSL2 (`wsl --shutdown`) and rerunning the `apt update` command seems to fix it for now.

**Comment by salaxander** [comment]
Yeah this does seem to be a re-occurring thing for me, running a shutdown is a quick fix though. Feel free to let me know if there's any more data that I can provide!

**Comment by akalipetis** [comment]
You could also try `sudo hwclock -s`, which does not need a restart of the underlying VM.

**Comment by leon-strong** [comment]
apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update  

will work around it temporarily.

**Comment by xitos2019** [comment]
i am getting below error i dont kow how to fix this i am running on WSL1. any suggestion would be appreciable 

Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:2 http://security-cdn.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Reading package lists...
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 2d 7h 51min 12s). Updates for this repository will not be applied.
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 1d 12h 25min 46s). Updates for this repository will not be applied.
ERROR: Service 'php-fpm-7.2' failed to build: The command '/bin/sh -c apt-get update         && apt-get install -y apt-transport-https ca-certificates         && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by giggio** [comment]
I used to have this problem with Docker for Windows. Whenever the machine hibernated, when it came back I had to go to Hyper-v Manager and disable and reenable Time sync, than it would be back to regular time.
I'm pretty sure this is the same problem, it is happening to me in exactly the same pattern: whenever the computer hibernates. I'm on WSL 2.
I can confirm that `sudo hwclock -s` fixes it, but this should come in the box.
This did not happen before when this wsl instance was on WSL 1.

**Comment by gsusI** [comment]
Still happening:

- Microsoft Windows [Version 10.0.19041.208]
- Happens when running `sudo apt-get update` on WSL2 Ubuntu 18.04

Using `sudo hwclock --hctosys` to fix it. However, uncomfortable.

Output:

```bash

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://packages.cloud.google.com/apt gcsfuse-bionic InRelease
Hit:5 http://packages.cloud.google.com/apt cloud-sdk InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists... Done
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 7h 34min 8s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 7h 35min 30s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 7h 33min 8s). Updates for this repository will not be applied.

```

**Comment by pofl** [comment]
This bug has given me HUGE frustration.

I'm coming off of two days of hunting a bug. I was trying to interact with Google BigQuery from code running inside a docker container. And I couldn't for the life of me find out why the fuck I can't authenticate. For the longest time I thought the problem was introduced during the latest library update. 

But how the fuck am I supposed to think of the possibility that the problem is in fact that during authentication you need a correct clock otherwise the during the request of a token you get an error response because a fucked up timer fucks up the expiry mechanism. TWO DAYS OF MY WORKING LIFE GONE! Oh the hours I have spent trying to debug the library. WTF.

How is this stupid bug not fixed a whole year later? I'm sorry for the language, but this has just been so frustrating.

**Comment by prairiewolf-by** [comment]
Guys, please, help!
HOW TO FIX THIS ***********N BUG???
None of recipes above work! :(
Cannot proceed with my task as I am permanently stopped by this.

Moreover, I am thinking of returning to WSL1 if that will be possible.

OS: Windows 2004 (build 19041.329) Pro.

**Comment by daleffe** [comment]
> Guys, please, help!
> HOW TO FIX THIS ***********N BUG???
> None of recipes above work! :(
> Cannot proceed with my task as I am permanently stopped by this.
> 
> Moreover, I am thinking of returning to WSL1 if that will be possible.
> 
> OS: Windows 2004 (build 19041.329) Pro.

I used the workaround suggested by @leon-strong:

`apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update`

**Comment by prairiewolf-by** [comment]
> 
> 
> > Guys, please, help!
> > HOW TO FIX THIS ***********N BUG???
> > None of recipes above work! :(
> > Cannot proceed with my task as I am permanently stopped by this.
> > Moreover, I am thinking of returning to WSL1 if that will be possible.
> > OS: Windows 2004 (build 19041.329) Pro.
> 
> I used the workaround suggested by @leon-strong:
> 
> `apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update`

That did not help, however, I was by some strange reason able to run a single-layer 'apt-get' command within my dockerfile - so that was pretty enough for me.
I have been using all suggestions in a single line for it to work:
`apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false -o Acquire::Max-FutureTime=86400 update`

Anyway, thanks for trying to help!

**Comment by pcolmer** [comment]
A couple of points to add to this:

1. This clearly doesn't just affect `apt-get`. For example, I use AWS on my Ubuntu system and, if the clock is wrong, then the authentication phase succeeds but the use of the obtained authorisation tokens then fails.

2. This might not just affect systems that have gone to sleep or hibernated. I shut down my Windows 10 system at the end of every day and, since finding this issue, I've been very careful to check the date on the Ubuntu WSL system when I start it, and it is always wrong. I don't know if that is because shutdown on Windows 10 might not be a "full" shutdown though? I seem to remember reading something about Windows not doing full shutdowns by default to make it faster, so maybe my system is hibernating after all?

**Comment by leon-strong** [comment]
https://github.com/stuartleeks/wsl-clock is quite a clever work around.

**Comment by bartr** [comment]
None of the above worked for me, but putting this in my WSL .bashrc is working so far (you have to apt install ntpdate). I run it in the background because it takes 7-10 seconds to run. hth

sudo ntpdate ntp.ubuntu.com &

**Comment by leiless** [comment]
> None of the above worked for me, but putting this in my WSL .bashrc is working so far (you have to apt install ntpdate). I run it in the background because it takes 7-10 seconds to run. hth
> 
> sudo ntpdate ntp.ubuntu.com &

Which we should first install `ntpdate`: `sudo apt install ntpdate`

**Comment by ManuInNZ** [comment]
Confirmed that on Win 10 WSL 2 I had to use the following after hibernation:
```
 wsl -d docker-desktop hwclock -s
```

Cheers
Manu

**Comment by benmccann** [comment]
I think this is a duplicate of https://github.com/microsoft/WSL/issues/5324

**Comment by ManouchehrRasoulli** [comment]
> > Guys, please, help!
> > HOW TO FIX THIS ***********N BUG???
> > None of recipes above work! :(
> > Cannot proceed with my task as I am permanently stopped by this.
> > Moreover, I am thinking of returning to WSL1 if that will be possible.
> > OS: Windows 2004 (build 19041.329) Pro.
> 
> I used the workaround suggested by @leon-strong:
> 
> `apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update`

thanks for answer this one worked for me

**Comment by shinebayar-g** [comment]
Another quick fix: 

```
sudo apt-get install ntpdate
sudo ntpdate pool.ntp.org
```

**Comment by mcandre** [comment]
Why does WSL ntpd fail upon resuming from hibernation?

**Comment by bc3tech** [comment]
> Another quick fix:
> 
> ```
> sudo apt-get install ntpdate
> sudo ntpdate pool.ntp.org
> ```
> 
> Working on WSL2, Ubuntu 20.04 LTS.

Even better, added to `~/.bashrc` :)

**Comment by brandonh-msft** [comment]
> Another quick fix:
> 
> ```
> sudo apt-get install ntpdate
> sudo ntpdate pool.ntp.org
> ```
> 
> Working on WSL2, Ubuntu 20.04 LTS.

Even better, added to `~/.bashrc` :)

This lost me hours of work last night as I tried to troubleshoot [a mysterious auth error from Terraform](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9882) as it was trying to deploy an Azure Storage Account. Shows up in the form of a "bad authentication header" error message.

**Comment by SebTardif** [comment]
> > Another quick fix:
> > ```
> > sudo apt-get install ntpdate
> > sudo ntpdate pool.ntp.org
> > ```
> > Working on WSL2, Ubuntu 20.04 LTS.
> 
> Even better, added to `~/.bashrc` :)

It's not good enough for me. I need to have a cron job that execute it each 5 minutes. Basic things are so complicated when Windows is close by.

**Comment by devedse** [comment]
Hi all, I created a script that creates a scheduled task to automatically update the time of WSL when you either restore from sleep or you restore a "Saved" Hyper-V VM.

```
wsl -d Ubuntu -u root apt-get update && apt-get install ntpdate
schtasks /Create /TN wsl-clock /TR "wsl -d Ubuntu -u root ntpdate pool.ntp.org" /SC ONEVENT /EC System /MO "*[System[Provider[@Name='Microsoft-Windows-Kernel-Power'] and (EventID=107 or EventID=507) or Provider[@Name='Microsoft-Windows-Kernel-General'] and (EventID=1)]]" /F
```

Change `Ubuntu` (in both places in the script) to the name of your WSL Instance (See `wsl --list`), then execute the script in `cmd`.

Thanks to all the other comments/suggestions that helped me create this script 😄 .

**Comment by SehiiRohoza** [comment]
I have the same issue on Windows 11 22H2, WSL2, Ubuntu 22.04 while updating packages:

```
$sudo apt update && sudo apt upgrade -y                                                                                                                                                                    
[sudo] password for serhii_rohoza:
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Hit:4 https://baltocdn.com/helm/stable/debian all InRelease
Get:5 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security InRelease [7,535 B]
Hit:6 https://apt.releases.hashicorp.com jammy InRelease
Hit:7 https://packages.cloud.google.com/apt cloud-sdk InRelease
Get:8 https://esm.ubuntu.com/apps/ubuntu jammy-apps-updates InRelease [7,459 B]
Get:9 https://esm.ubuntu.com/infra/ubuntu jammy-infra-security InRelease [7,453 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:11 https://esm.ubuntu.com/infra/ubuntu jammy-infra-updates InRelease [7,452 B]
Reading package lists... Done
E: Release file for http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease is not valid yet (invalid for another 1d 16h 4min 18s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease is not valid yet (invalid for another 1d 16h 4min 40s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease is not valid yet (invalid for another 1d 16h 5min 15s). Updates for this repository will not be applied.
```

It could be fixed with `sudo hwclock --hctosys`, but it's quite annoying.

**Comment by matthewnourse** [comment]
This problem was killing me so a chucked a tantrum and wrote a little daemon for it:
https://github.com/matthewnourse/polite-hwclock-hctosys

I hope you find it useful.

**Comment by ManuInNZ** [comment]
I guess my question will be then, do we need this daemon or similar in all
will distro?

e.g. lately I had recovery issues after hibernation with docker desktop
(docker and docker-data) and rancher desktop (similar 2 distro).

cheers
Manu

**Comment by craigloewen-msft** [comment]
/dupe #10006

We're migrating all clock skew issues to a megathread so we can keep the top comment up to date with any updates and work arounds. Thank you for filing this!

**Comment by roskee** [comment]
This might occur when there is another OS dual booted on the computer. For example, there will be a 3-hour clock offset between Ubuntu and Windows dual boot setup. I used the configuration changes recommended by @leon-strong.

**Comment by mcandre** [comment]
I'm not dual booting.

Why do WSL and native Windows have split clocks?
