### ISSUE TITLE
I cannot make WSL2 apply multiprocessing

### ISSUE THREAD

**Issue by kimrj** [microsoft/WSL#4118]
Trying to make WSL2 work like the results documented here:

http://www.simxon.com/articles/20190521-while-we-wait-for-wsl2.html

, I have installed openmpi and other software packages to WSL2 Ubuntu like I did before with WSL1. The 12-processor task runs and appears to give the same intermediate results as before. However, I see do indications that multiprocessing actually takes place. In particular, runtimes seem to be unacceptably long.

What am I doing wrong? Which switch should I have set?

**Comment by therealkenc** [comment]
Forward duping to #4135 as the landing zone, since it is the same blog and the other one has the need-author-feedback tag.
