### ISSUE TITLE
Converting to WSL 2 is not working

### ISSUE THREAD

**Issue by hMounir** [microsoft/WSL#4119]
Hi, first of all, thanks for developing WSL, I have been a long user, now that WSL 2 is out, I got it on my machine, now when I try to convert my current distro (Pengwin WSL linux), it fails to convert, 
Can you please help ? 

Here's the Distro Link: 

> https://github.com/WhitewaterFoundry/Pengwin

The command I used to convert it to WSL 2: 
`wsl --set-version WLinux 2`

```
PS C:\Users\hisha> wsl --set-version WLinux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Unspecified error
PS C:\Users\hisha>
```

> Microsoft Windows [Version 10.0.18917.1000]

**Comment by mscraigloewen** [comment]
Hi there! Could you provide us with some detailed logs?
Instructions can be found [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md).

**Comment by hMounir** [comment]
Never mind, it worked, I ran the command again in admin mode and the conversion completed, thanks
