### ISSUE TITLE
Can't convert Ubuntu to WSL 2

### ISSUE THREAD

**Issue by x-cubed** [microsoft/WSL#4121]
* Your Windows build number:
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening: 
Trying to convert an existing Ubuntu installation to the new WSL 2 format with
> C:\\>wsl --set-version Ubuntu 2
> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2`
> Unspecified error

* What's wrong / what should be happening instead:
Conversion should succeed.

* Detailed logs: [lxcore_etl.zip](https://github.com/microsoft/WSL/files/3288072/lxcore_etl.zip)

**Comment by x-cubed** [comment]
Logs above are from my second attempt, it actually succeeded when I tried a third time.
The only thing different between my second and third attempts was that I had launched bash in between and ran apt-get update && apt-get upgrade.

**Comment by dontmint** [comment]
I happened the same for me, failed twice and succeed at the third time.

**Comment by Biswa96** [comment]
Duplicate #4102.

**Comment by mkezmkez** [comment]
Same thing happened to me, opened ubuntu, closed, restarted windows 3 times, and it finally worked.
