### ISSUE TITLE
snapd needs squashfs support in kernel

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4123]
WSL 2, build 18917.

While WSL2 doesn't have the issues with snapd described in #2374 , we now have another blocker. snap install now fails after downloading the snap, as it is unable to mount it, since the WSL 2 kernel doesn't contain squashfs support. (Per /proc/filesystems and the obvious test:

![image](https://user-images.githubusercontent.com/371623/59469037-542b2e80-8df9-11e9-83ea-220880feb379.png)

 .)

Any chance we can get that included?

**Comment by therealkenc** [comment]
> we now have another blocker.

Still have [one of](https://github.com/microsoft/WSL/issues/2374#issuecomment-406895982) the blockers.

> Any chance we can get that included?

In the meantime, pending an answer to that, bet you could, with a little hackery, probably get over the hump with [this](https://github.com/vasi/squashfuse).

**Comment by benhillis** [comment]
We've added squashfs support to the kernel, it will be available in an Insider build soon.

**Comment by therealkenc** [comment]
Ugh. Was heartbroken trying the more obvious work-around than the first idea....

![image](https://user-images.githubusercontent.com/7049700/59482979-083fb000-8e20-11e9-9000-284c8e21e072.png)

**Comment by therealkenc** [comment]
Second try is the trick....

![image](https://user-images.githubusercontent.com/7049700/59510994-fc78db80-8e69-11e9-91c1-e36208581352.png)

**Comment by bbhopesh** [comment]
@therealkenc I am still facing #2374 in WSL2. Is it just me or is it a known issue for wsl2 too? @cerebrate says he doesn't get it in WSL2.

**Comment by cerebrate** [comment]
@bbhopesh To clarify that, I don’t get in WSL 2 _because I can run systemd in WSL 2_. (Using my https://github.com/arkane-systems/genie code.) Without that or some equivalent method to get systemd up and running for snapd, I’d still get it, and snapd won’t run without both that and a recompiled kernel.

**Comment by therealkenc** [comment]
Yes, as of this writing `snapd` won't run "out of the box" on WSL2. [`CONFIG_SQUASHFS`](https://github.com/torvalds/linux/blob/master/fs/squashfs/Kconfig) should roll out RSN though. There is usually a couple week delay from tag fixinbound to the change actually making its way into a Windows Update rollout.

**Comment by cerebrate** [comment]
Since this is in the kernel now, closing.

**Comment by Biswa96** [comment]
Here is a naughty procedure to use snapd with systemd. See this link https://forum.snapcraft.io/t/snapd-on-wsl2-insiders-only-for-now/13033

**Comment by cerebrate** [comment]
So much reinventing of the wheel. 🤷‍♂

**Comment by therealkenc** [comment]
My [one-liner](https://github.com/microsoft/WSL/issues/994#issuecomment-502055417) seems to have a legs. Yeah.

**Comment by cerebrate** [comment]
In so many very similar wrapped variants, heh. This is about the fifth one I've seen, counting mine, and I haven't been looking.
