### ISSUE TITLE
Can't open GUI apps After WSL 2 Conversion

### ISSUE THREAD

**Issue by hMounir** [microsoft/WSL#4124]
Hello, did anyone face the issue regarding Linux GUI apps after the conversion, it was working before, now it's not. I'm using X410 as X-Server. When I try to launch a gui app, it says the connection is refused.

```
hisham@Hisham-PC:~$ xfce4-terminal
Unable to init server: Could not connect: Connection refused

(xfce4-terminal:433): Gtk-WARNING **: 16:34:13.842: cannot open display: windowsIP:0.0
```

**Comment by sirredbeard** [comment]
This is a duplicate of #4106.

**Comment by cerebrate** [comment]
Did you tick the "Allow Public Access" option in the X410 menu? Remember, since WSL 2 uses a separate IP address and you have to use the Windows IP rather than localhost, it's not considered the local machine any more.

**Comment by hMounir** [comment]
> Did you tick the "Allow Public Access" option in the X410 menu? Remember, since WSL 2 uses a separate IP address and you have to use the Windows IP rather than localhost, it's not considered the local machine any more.

It worked, thanks

**Comment by ekartsonakis** [comment]
I also added an exception in the windows firewall for the xserver (vcxsrv in my case)

**Comment by gaussian37** [comment]
I also tried it in wsl 2. But I got messeage "can't open display" too.
And I changed wsl version from 2 to 1 and I solved the problem. I can use GUI and display.
I think that wsl 2 is not yet perfect and it should be improved someday.

please use wsl 1 for display !
