### ISSUE TITLE
WSL2: After having started new WSL instance many times, it doesn't start any more.

### ISSUE THREAD

**Issue by 0xbadfca11** [microsoft/WSL#4126]
* Your Windows build number:
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:
Every time start a new WSL instance, ``ext4.vhdx`` is given a new ACL.
When after it starts approximately 2000 times, WSL will not start.

Batch file for reproduction
```cmd
:start
wsl -e /bin/true
wsl --shutdown
goto start
```
![The inherited access control list (ACL) or access control entry (ACE) could not be built.](https://user-images.githubusercontent.com/7390559/59484961-e6d9d500-8eae-11e9-9343-b42e898d2791.png)
``The inherited access control list (ACL) or access control entry (ACE) could not be built.``
* What's wrong / what should be happening instead:
Starts fine anytime.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
[lxcore.zip](https://github.com/microsoft/WSL/files/3289137/lxcore.zip)

**Comment by benhillis** [comment]
Excellent bug! I will take a look.

**Comment by benhillis** [comment]
If you get into this state, you can remove the GUID ACLs from the file via Properties -> Security -> Edit and removing the GUID entries from the "Group or user name"list.

**Comment by ggodool** [comment]
I just experienced this bug too. And I also had to delete GUID ACLS from my _ext4.vhdx_ too. 
Could you fix this bug?

**Comment by darkzbaron** [comment]
Have the same issue, the fix works but it's annoying.
