### ISSUE TITLE
(WSL 2) VSCode does not automatically start in Remote WSL mode when opened from Bash command line

### ISSUE THREAD

**Issue by fancyplants** [microsoft/WSL#4127]
* Your Windows build number: Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:
When evoking `code <dir>` in WSL 2, VSCode opens and doesn't connect to the Remote WSL server automatically. The program runs within the current terminal context and VSCode closes when the command line version is interrupted.

Powershell:
```powershell
wsl --set-version Ubuntu 2
```
WSL bash:
```bash
~/code/js$ code .

[main 2019-06-14T05:34:33.398Z] update#setState idle
[main 2019-06-14T05:35:03.409Z] update#setState checking for updates
[main 2019-06-14T05:35:03.451Z] update#setState idle


```
* What's wrong / what should be happening instead:
The behavior of WSL 1 (which works with this normally):

WSL Bash:
```bash
~/code/js$ code .
~/code/js$
```
`code <dir>` command is evoked, pauses for a moment, and then returns to command line, while VSCode opens and automatically boots up the Remote WSL server within that folder.

(The rest of the parts were not applicable)
If more information is needed, just ask! Thank you WSL team for the work you do. This is my only issue with WSL 2 so far!

**Comment by therealkenc** [comment]
I'm (unfortunately?) not able to reproduce this. Windows VS Code 1.35.1 fires up okay from inside WSL2 with the directory given.

I'd hate to suggest doing a `--set-version Ubuntu 1` just to see whether it still works (not go back permanently) but I can't think of something else to try. Maybe there is another variable here, but I'm not guessing one atm.

**Comment by Bruce-YC** [comment]
I have the same issues. "Remote-WSL: New Window" would be successful but it can not really start in the terminal. I think this problem might be caused by the same problem with localhost.

**Comment by fancyplants** [comment]
> I'm (unfortunately?) not able to reproduce this. Windows VS Code 1.35.1 fires up okay from inside WSL2 with the directory given.
> 
> I'd hate to suggest doing a `--set-version Ubuntu 1` just to see whether it still works (not go back permanently) but I can't think of something else to try. Maybe there is another variable here, but I'm not guessing one atm.

Actually, this seems to fix things. VSCode opens with Remote WSL booting up normally when the version of my Ubuntu install is WSL 1 instead of WSL 2.

**Comment by mscraigloewen** [comment]
@fancyplants VSCode remote needs to be used on your default distro in WSL 2. Do you have multiple distros installed?

**Comment by fancyplants** [comment]
@mscraigloewen I only have Ubuntu installed, and I've ensured that it's been set to the (Default) distro for WSL.

**Comment by therealkenc** [comment]
I'm straw grasping (_totally_), but I only just notice you the OP says `--set-version Ubuntu 2` not `--set-version Ubuntu-18.04`. Maybe try installing `Ubuntu-18.04` from the Store, set it as the default like Craig says, and see if that changes anything. If nothing else you'll be disturbing variables. My run was on "Ubuntu-18.04" not "Ubuntu" and that's a repro diverge. [Actually full disclosure my Ubuntu-18.04 was dist-upgraded, but that's not the variable tweak I'm after here. Point is to try the "other" one from the Store.]

**Comment by fancyplants** [comment]
@therealkenc So I installed `Ubuntu-18.04` and converted to WSL 2. Unfortunately, same thing happens where it prints those same messages as in the original issue and VSCode does not connect to WSL automatically. As is the same with `Ubuntu` when using the `code .` command, this works if you open a new window using the VSCode command `Remote-WSL: New Window`.

**Comment by therealkenc** [comment]
> it prints those same messages as in the original issue

I get the goofy messages too (I should have mentioned that) but it launches as expected. I think those messages are (scare quote) "by-design" VS Code, at least for the release in question. Do appreciate you taking the trouble to spin up 18.04 even if doing so didn't yield anything new.

**Comment by mscraigloewen** [comment]
This might be a VSCode Remote issue that's related to WSL. So it could be a good idea to also file an issue on their Github page and link to this one.

Have you tried the nuclear option of uninstalling and reinstalling VSCode?

**Comment by therealkenc** [comment]
> Have you tried the nuclear option of uninstalling and reinstalling VSCode?

That's not the _**nuclear**_ option. ;)

**Comment by fancyplants** [comment]
@mscraigloewen I will file an issue soon with VSCode Remote team as well. As for now, the combos I've tried (at least I think I remember):
* Reinstalling VSCode
* Reinstalling Ubuntu WSL 2
* Uninstalling both, followed by installing Ubuntu WSL 2 and then VSCode

And so far the only fix has been reverting to WSL 1.

**Comment by fancyplants** [comment]
Update: someone posted about this in an issue on the Remote Development extension for VSCode, so I think we're all good! (https://github.com/microsoft/vscode-remote-release/issues/714) Keep up the good work on WSL 2 guys

**Comment by therealkenc** [comment]
^--- Call it a gift horse _if_ the msft/vscode-remote-release#714 issue solves your problem. It goes without saying you can try again once a fix related to the `/proc/version` diverge rolls. But off the cuff, it isn't immediately obvious that it will. If the `/proc` diverge were the cause it would manifest for everyone equally, including Craig&I. Either way we can keep this issue in a holding pattern until you find joy. Appreciate the update.

**Comment by benc-uk** [comment]
With your default distro set to WSL2, VS Code will open in there and work but not using `code .` you have to use **"Remote-WSL: New Window"** from the command pallet. Once you do this, VS Code will open a new instance running remotely inside WSL2

**Comment by therealkenc** [comment]
@fancyplants 

Try:
```
$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ cd ~ && mkdir vscodetest && cd vscodetest && touch ./hello.txt
$ "/mnt/c/Users/there/AppData/Local/Programs/Microsoft VS Code/bin/code" -n .
```

**Comment by hatroman** [comment]
Hello, I have the same issue on WSL2.
I tried commands suggested by @therealkenc but the problem is not solved.
Please, help to fix it.

**Comment by craigloewen-msft** [comment]
@hatroman your error is likely related to https://github.com/microsoft/WSL/issues/4362 and https://github.com/microsoft/WSL/issues/4337 . A fix is inbound that will address these.

**Comment by kohbo** [comment]
This issue is still happening for me

VSCode Version 1.38.1
Remote Development .17.0
Remote-WSL 0.39.5

**Comment by gusbemacbe** [comment]
Hello @craigloewen-msft 

Is it possible to set Remote WSL as default run option when I open VSCode?

Referring to https://www.reddit.com/r/vscode/comments/eak5t3/can_i_make_remote_wsl_as_default_run_option/.

**Comment by craigloewen-msft** [comment]
That's a good question! Does the workflow of opening a bash shell and then running `code .` from there work for you? That's how I always run something if I want it to start up in Remote mode automatically.

**Comment by gusbemacbe** [comment]
@craigloewen-msft 

> Does the workflow of opening a bash shell and then running code . from there work for you?

Yes, it is possible. Here are the steps:

1. Set in the file `settings.json`:

```json
{
    "terminal.integrated.shell.linux": "/usr/bin/zsh",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe"
}
```

2. Open the `Remote WSL: New Window`
3. Save the workspace as.

Ready.

The problem is that, even if I set `"window.restoreWindows": "one"` and `"window.restoreWindows": "all", it opens automatically the Remote WSL, but if you open any file or any folder, it will open the Remote WSL, but not with any clicked file or folder.

> Also for further discussion, please consider opening up a new issue on this board or on the VSCode Remote repo and we can discuss that request there, as this ask is not explicitly related to this specific issue, so it'll help us keep better track. :)

Yes, I'll do. @Tyriar is unaware of this type because it sounds something new.

**Comment by theAkito** [comment]
> Is it possible to set Remote WSL as default run option when I open VSCode?

This worked for me on WSL 1 in another Windows 10. I never enabled it, it just worked automatically. Now, I use a newer Windows 10 with WSL 2 and I can't figure out how to set this to default. The whole point of VS Code is using it with WSL, so I really don't know how this is not one of the most obvious options.

**Comment by vielhuber** [comment]
- When I open vscode with `code .` from wsl, it opens the "system wide installation", not the "user based installation", which I need

- When I open vscode normally or directly inside a folder in Windows Explorer, I always have to do: "Remote-WSL: Reopen folder in WSL", which is annoying. 

Any tips for that?

**Comment by vielhuber** [comment]
I've managed to open now projects with `code .`, after I uninstalled the system wide VSCode installation from the programs panel.

**Comment by divyanshtiwari** [comment]
Hi! this is still valid for me, I am using windows 11 version 21H2 , WSL profile : ubuntu 22.04 
I am able to open vs code via `code .` but the prompt hangs, until I close the VScode instance.

**Comment by vielhuber** [comment]
Check your RAM. For me from time to time it runs full.
In .wslconfig memory=8GB / swap=16GB solves this (partly).
