### ISSUE TITLE
[WSL2]Error! Your kernel headers for kernel 4.19.43-microsoft-standard cannot be found.

### ISSUE THREAD

**Issue by 0312birdzhang** [microsoft/WSL#4128]
* Your Windows build number:  

  10.0.18917.1000

* What you're doing and what's happening:  

  Installing anbox-modules on Ubuntu 18.04(wsl2)

* What's wrong / what should be happening instead:

```
bird@20100104-0187:~/anbox-modules$ sudo dkms install anbox-ashmem/1
Creating symlink /var/lib/dkms/anbox-ashmem/1/source ->
                 /usr/src/anbox-ashmem-1
DKMS: add completed.
Error! Your kernel headers for kernel 4.19.43-microsoft-standard cannot be found.
Please install the linux-headers-4.19.43-microsoft-standard package,
or use the --kernelsourcedir option to tell DKMS where it's located

bird@20100104-0187:~/anbox-modules$ sudo apt install linux-headers-generic
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-generic is already the newest version (4.15.0.51.53).
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.
```

**Comment by lazerl0rd** [comment]
@0312birdzhang does the package `linux-headers-4.19.43-microsoft-standard` exist for you (I can’t test WSL2 but you should use the headers for your specific kernel here, not the generic one)?

If it’s not existing try use `--kernelsourcedir /usr/src/<kernel src folder if that exists too>`.

**Comment by 0312birdzhang** [comment]
@lazerl0rd not exist
```
bird@20100104-0187:~/anbox-modules$ sudo apt-get install linux-headers-4.19.43-microsoft-standar
[sudo] password for bird:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-4.19.43-microsoft-standar
E: Couldn't find any package by glob 'linux-headers-4.19.43-microsoft-standar'
E: Couldn't find any package by regex 'linux-headers-4.19.43-microsoft-standar'
```

**Comment by lazerl0rd** [comment]
@0312birdzhang you missed out the d.

**Comment by 0312birdzhang** [comment]
@lazerl0rd Updated, i'm sure it not exist. 
`sudo apt search linux-headers` show noting about `4.19`

**Comment by lazerl0rd** [comment]
> @lazerl0rd Updated, i'm sure it not exist.
> `sudo apt search linux-headers` show noting about `4.19`

Tried my second method above? Hopefully the source is bundled.

**Comment by 0312birdzhang** [comment]
@lazerl0rd It works with `dkms install `, but failed on the next step. 
```
bird@20100104-0187:~/anbox-modules$ sudo dkms install anbox-ashmem/1 --kernelsourcedir /usr/src/linux-4.19.43

ashmem_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.43-microsoft-standard/updates/dkms/

depmod...

DKMS: install completed.
bird@20100104-0187:~/anbox-modules$ sudo dkms install anbox-binder/1 --kernelsourcedir /usr/src/linux-4.19.43

binder_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.43-microsoft-standard/updates/dkms/

depmod...

DKMS: install completed.
bird@20100104-0187:~/anbox-modules$ cd /lib/modules/4.19.43-microsoft-standard/updates/
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates$ ls
dkms
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates$ cd dkms/
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ ls
ashmem_linux.ko  binder_linux.ko
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ ll
total 180
drwxr-xr-x 2 root root   4096 Jun 14 15:06 ./
drwxr-xr-x 3 root root   4096 Jun 14 15:06 ../
-rw-r--r-- 1 root root  15208 Jun 14 15:06 ashmem_linux.ko
-rw-r--r-- 1 root root 158800 Jun 14 15:06 binder_linux.ko
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ sudo modprobe ashmem_linux
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.19.43-microsoft-standard/modules.builtin.bin'
modprobe: ERROR: could not insert 'ashmem_linux': Exec format error
bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ sudo insmod ashmem_linux.ko
insmod: ERROR: could not insert module ashmem_linux.ko: Invalid module format
```

**Comment by 0312birdzhang** [comment]
Finally, i made modules install work.

Step1: build 4.19.43 kernel with `zcat /proc/config.gz` config (https://www.cyberciti.biz/tips/compiling-linux-kernel-26.html)

`sudo update-initramfs -c -k `
need install `grub2-common` to `update-grub`

Then stop Ubuntu with `wsl -t Ubuntu` or you can use `wsl --shutdown` stop all
Start `wsl --distribution Ubuntu`

Step2: Use `make`  `ashmem` and `binder` on each folder

Step3: Install them
```
sudo cp ~/anbox-modules/{binder,ashmem}/*.ko /lib/modules/4.19.43-microsoft-standard/updates/dkms/ 
sudo modprobe ashmem_linux
sudo modprobe binder_linux
```
It should be working now
```
bird@20100104-0187:~/anbox-modules$ lsmod | grep -e ashmem_linux -e binder_linux
binder_linux          102400  -2
ashmem_linux           16384  -2
```

And as snap not supported on wsl2 (still no systemd), we need waiting for MS do some work.

**Comment by lazerl0rd** [comment]
@benhillis sorry to bother you but where can we find the WSL2 kernel source?

**Comment by 0312birdzhang** [comment]
> 
> 
> @benhillis sorry to bother you but where can we find the WSL2 kernel source?

I use the origin kernel source forn git.kernel.org, with `zcat /proc/config.gz` config

**Comment by 0312birdzhang** [comment]
@benhillis 
```
bird@20100104-0187:~$ lsmod
Module                  Size  Used by
squashfs               36864  -2
binder_linux          102400  -2
ashmem_linux           16384  -2
bird@20100104-0187:~$ sudo /usr/lib/snapd/snapd
AppArmor status: apparmor not enabled
2019/06/14 17:42:11.621471 daemon.go:379: started snapd/2.38+18.04 (series 16; classic; devmode) ubuntu/18.04 (amd64) linux/4.19.43-microsoft-standar.
2019/06/14 17:42:11.717598 main.go:123: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount: /tmp/sanity-mountpoint-789039418: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
2019/06/14 17:42:16.728076 daemon.go:611: gracefully waiting for running hooks
2019/06/14 17:42:16.728110 daemon.go:613: done waiting for running hooks
daemon stop requested to wait for socket activation
```

**Comment by 0xbadfca11** [comment]
WSL2 kernel source is here.
> https://docs.microsoft.com/en-us/windows/wsl/wsl2-about
> https://thirdpartysource.microsoft.com/download/Windows%20Subsystem%20for%20Linux%20v2/May%202019/WSLv2-Linux-Kernel-master.zip

**Comment by 0312birdzhang** [comment]
@0xbadfca11 Thank you.

**Comment by ningacoding** [comment]
> @lazerl0rd It works with `dkms install `, but failed on the next step.
> 
> ```
> bird@20100104-0187:~/anbox-modules$ sudo dkms install anbox-ashmem/1 --kernelsourcedir /usr/src/linux-4.19.43
> 
> ashmem_linux:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/4.19.43-microsoft-standard/updates/dkms/
> 
> depmod...
> 
> DKMS: install completed.
> bird@20100104-0187:~/anbox-modules$ sudo dkms install anbox-binder/1 --kernelsourcedir /usr/src/linux-4.19.43
> 
> binder_linux:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/4.19.43-microsoft-standard/updates/dkms/
> 
> depmod...
> 
> DKMS: install completed.
> bird@20100104-0187:~/anbox-modules$ cd /lib/modules/4.19.43-microsoft-standard/updates/
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates$ ls
> dkms
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates$ cd dkms/
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ ls
> ashmem_linux.ko  binder_linux.ko
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ ll
> total 180
> drwxr-xr-x 2 root root   4096 Jun 14 15:06 ./
> drwxr-xr-x 3 root root   4096 Jun 14 15:06 ../
> -rw-r--r-- 1 root root  15208 Jun 14 15:06 ashmem_linux.ko
> -rw-r--r-- 1 root root 158800 Jun 14 15:06 binder_linux.ko
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ sudo modprobe ashmem_linux
> modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.19.43-microsoft-standard/modules.builtin.bin'
> modprobe: ERROR: could not insert 'ashmem_linux': Exec format error
> bird@20100104-0187:/lib/modules/4.19.43-microsoft-standard/updates/dkms$ sudo insmod ashmem_linux.ko
> insmod: ERROR: could not insert module ashmem_linux.ko: Invalid module format
> ```

Some of those steps helped me alot, togheter with this tutorial:

https://www.reddit.com/r/bashonubuntuonwindows/comments/eofn5s/run_anbox_on_wsl_2/

To make it work with WSL2 Ubuntu18.04
