### ISSUE TITLE
color against my eye!!!!!!

### ISSUE THREAD

**Issue by charlesld** [microsoft/WSL#4130]
* Your Windows build number:

> Microsoft Windows [版本 10.0.18362.116]

* bash version

```shell
C:\WINDOWS\system32>bash
charles@DESKTOP-3DSSNKC:/mnt/c/WINDOWS/system32$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
charles@DESKTOP-3DSSNKC:/mnt/c/WINDOWS/system32$
```

* What you're doing and what's happening:

> just use wsl shell in **jetbrain** IDE(`Idea` `pycharm` `goland`..) 

* What's wrong / what should be happening instead:

after upgrade win10 to current version. then  
**strange color config** when typed `bash` in the console.
![image](https://user-images.githubusercontent.com/23304239/59496729-a7b67e80-8ec4-11e9-8826-d6b912b052cf.png)

**can you see what I typed in the bash console?????????**
but is works well in `win+r -> cmd -> bash` or`win+r -> bash` 
what I can do , or where I can restore the config?   
ide just conf like this ,and no more conf can be set.
![image](https://user-images.githubusercontent.com/23304239/59497717-8bb3dc80-8ec6-11e9-9327-ded513cc85f1.png)

**Comment by charlesld** [comment]
![image](https://user-images.githubusercontent.com/23304239/59498507-29f47200-8ec8-11e9-8cd8-a6833b64ca69.png)

**Comment by therealkenc** [comment]
> If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).
