### ISSUE TITLE
Kernel Headers on WSL2

### ISSUE THREAD

**Issue by abnerfreitas** [microsoft/WSL#4132]
So, now we have a real kernel backing WSL2. Is it possible to release Kernel Headers so we cant test CUDA and Nvidia drivers?

**Comment by therealkenc** [comment]
Kernel headers are released [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include?h=v4.19). They will not help you to test CUDA and Nvidia drivers on this kernel. The user voice for CUDA is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support).
