### ISSUE TITLE
WSL2 locks when operating on an NTFS file system

### ISSUE THREAD

**Issue by kimrj** [microsoft/WSL#4134]
I have "stress-tested" WSL2 as described here: http://www.simxon.com/articles/20190614-wsl2-and-still-waiting.html

If the home directory of my calculation resides on the root file system, everything works - but as slowly as with WSL1. If the home directory resides on an NTFS file system, everything stops with no error messages appearing. The job just goes down to 0 % CPU.

**Comment by benhillis** [comment]
Thanks for filing, this is likely an issue with our 9P server. @SvenGroot can you take a look?

**Comment by SvenGroot** [comment]
Do you have a concise repro of the problem that I can attempt? I read through your articles but it's unclear exactly what commands I should run to get into the state you're in.

**Comment by kimrj** [comment]
Hi Sven,

 

Sounds like a reasonable demand 😉. Do you have a way to receive data amounts of, say, 5 GB?

 

Regards, Kim

 

Fra: Sven Groot <notifications@github.com> 
Sendt: 14. juni 2019 18:44
Til: microsoft/WSL <WSL@noreply.github.com>
Cc: kimrj <kim@ravn-jensen.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/WSL] WSL2 locks when operating on an NTFS file system (#4134)

 

Do you have a concise repro of the problem that I can attempt? I read through your articles but it's unclear exactly what commands I should run to get into the state you're in.
