### ISSUE TITLE
No multiprocessing floating point improvement between WSL1 and WSL2

### ISSUE THREAD

**Issue by kimrj** [microsoft/WSL#4135]
See here: http://www.simxon.com/articles/20190614-wsl2-and-still-waiting.html

**Comment by benhillis** [comment]
Can you please provide a summary of the issues you are hitting?

**Comment by kimrj** [comment]
Hi Ben,

 

I would call this a summary:  <http://www.simxon.com/articles/20190614-wsl2-and-still-waiting.html> http://www.simxon.com/articles/20190614-wsl2-and-still-waiting.html

 

If this format does not suit you, how would you like me to present my information, then?

 

Regards, Kim

 

Fra: Ben Hillis <notifications@github.com> 
Sendt: 14. juni 2019 16:54
Til: microsoft/WSL <WSL@noreply.github.com>
Cc: kimrj <kim@ravn-jensen.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/WSL] No multiprocessing floating point improvement between WSL1 and WSL2 (#4135)

 

Can you please provide a summary of the issues you are hitting?

**Comment by benhillis** [comment]
Filling out the issue template is a good start.  I'd rather our GitHub be links to external blogs.

**Comment by therealkenc** [comment]
> I'd prefer GitHub issues to not be links to external blogs.

Or just a repro. The blog worms to some previous article, which worms on something about (something called) OpenFOAM, which links to a "build guide". All very interesting stuff I'm sure (really).

> If this format does not suit you, how would you like me to present my information, then?

CLI repro steps from a clean install of some WSL distro from the Store. A script or github repository that can be cloned is nice, but a list copy-pasteable command line steps will often do. 

Once you have those lined up, try running those same steps in a bog-standard Hyper-V instance and see if the results are different than WSL 2. Certainly if there is a diverge from Hyper-V it should be looked at. If performance is the same, there are whole communities for discussion about running numerical apps in vitrual machines. That might be OpenFOAM on Hyper-V. Or lots of other scenarios; I dunno AV1 trans-coding on Windows QEMU maybe. Lots of improvements being made to VM solutions all the time. Sounds like you are pretty wired into that community so you'll probably see them as they happen.

**Comment by kimrj** [comment]
Hi Ken (did I get that right?),

 

I appreciate that you have cleaned up any mess that I have left due to my ignorance concerning Microsoft procedures 😊.

 

I do understand this statement of yours: “CLI repro steps from a clean install of some WSL distro from the Store. A script or github repository that can be cloned is nice, but a list copy-pasteable command line steps will often do.” I’ll start working along those lines. In that context, how can I hand over, say, 5 GB, to you?

 

The bottom paragraph in your email below, however, I do not understand as it refers to concepts which I have never heard of. Will you please clarify?

 

Regards, Kim Ravn-Jensen

 

Fra: therealkenc <notifications@github.com> 
Sendt: 14. juni 2019 23:11
Til: microsoft/WSL <WSL@noreply.github.com>
Cc: kimrj <kim@ravn-jensen.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/WSL] No multiprocessing floating point improvement between WSL1 and WSL2 (#4135)

 

I'd prefer GitHub issues to not be links to external blogs.

Or just a repro. The blog worms to some previous article, which worms on something about (something called) OpenFOAM, which links to a "build guide". All very interesting stuff I'm sure (really).

If this format does not suit you, how would you like me to present my information, then?

CLI repro steps from a clean install of some WSL distro from the Store. A script or github repository that can be cloned is nice, but a list copy-pasteable command line steps will often do.

Once you have those lined up, try running those same steps in a bog-standard Hyper-V instance and see if the results are different than WSL 2. Certainly if there is a diverge from Hyper-V it should be looked at. If performance is the same, there are whole communities for discussion about running numerical apps in vitrual machines. That might be OpenFOAM on Hyper-V. Or lots of other scenarios; I dunno AV1 trans-coding on Windows QEMU maybe. Lots of improvements being made to VM solutions all the time. Sounds like you are pretty wired into that community so you'll probably see them as they happen.

**Comment by therealkenc** [comment]
>  due to my ignorance concerning Microsoft procedures 

No worries. Those are in the [template](https://github.com/microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) that you deleted.

> In that context, how can I hand over, say, 5 GB, to you?

Any way you like so long as it is accessible on the Interwebs. Although the odds of someone downloading 5GB, absent a lot of evidence that whatever it is you are reporting (which remains unclear), is required to demonstrate a diverge against bog-standard Hyper-V behavior is probably pretty small. You want a [targeted repro](https://github.com/microsoft/WSL/issues/2913#issuecomment-423742801).

There is information on Hyper-V [here](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine). Information on QEMU is [here](https://www.qemu.org/). Information on transcoding is [here](https://en.wikipedia.org/wiki/Transcoding). You asked.

But if I've skimmed your blog post, you've already run on Windows Docker and it is all the same tech as WSL2. I am doubting you'll learn anything new. If it were me I'd subscribe to #4137 because Occam's Razor. But tests that demonstrate novel errant behavior are always welcome and encouraged here. Bonne chance.

**Comment by kimrj** [comment]
Now I have tried bare-metal Hyper-V: http://www.simxon.com/articles/20190618-wsl2-and-still-waiting-ii.html

**Comment by therealkenc** [comment]
> Microsoft has claimed that they would soon be able to run Linux binaries as efficiently as a native GNU/Linux installation

That line lacks citation. [I the WSL2 [announcement](https://devblogs.microsoft.com/commandline/announcing-wsl-2/) does not.]

There is no WSL2 actionable here. Thanks for sharing. If you do come up with a tight repro explaining the ~50% fall-off versus metal (I suspect a short 50-liner ought do it) do feel encouraged to submit an issue following the [template](https://github.com/microsoft/WSL/blob/master/ISSUE_TEMPLATE.md). In the mean time subscribe #4135.
