### ISSUE TITLE
ERR_CONNECTION_REFUSED when trying to connect to http://<ipofwsl2>:<port> on WSL2 (first preview)

### ISSUE THREAD

**Issue by psijkof** [microsoft/WSL#4136]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
18917.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

install dotnet core sdk on ubuntu
dotnet new webapp
dotnet run 
try to connect from windows browser: ip-address of wsl2 session (ip addr | grep eth0)
ERR_CONNECTION_REFUSED

* What's wrong / what should be happening instead:
well, it would be great to connect to the wsl2 app

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by mscraigloewen** [comment]
I was able to repro your issue.
My guess is that dotnet is only listening for requests coming from the internal loopback address (i.e: 127.0.0.1) so when you're trying to access it form an external IP address (from the Host machine) it's throwing you some errors. I'll try and verify this and get back to you!

**Comment by mscraigloewen** [comment]
Confirmed that this is a dotnet issue, you can get your website working by making it accept any IP address and not just `localhost`. You can do this by going into: `./Properties/launchSettings.json` and editing any mention of `localhost` to `:`. Here is my launchSettings.json that I got it working with:

```
{
  "iisSettings": {
    "windowsAuthentication": false, 
    "anonymousAuthentication": true, 
    "iisExpress": {
      "applicationUrl": "http://::65093",
      "sslPort": 44352
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "webapp": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://::5001;http://::5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by koryphaee** [comment]
This did not work for me. I had to replace `localhost` with `0.0.0.0`.

**Comment by pana216** [comment]
> Confirmed that this is a dotnet issue, you can get your website working by making it accept any IP address and not just `localhost`. You can do this by going into: `./Properties/launchSettings.json` and editing any mention of `localhost` to `:`. Here is my launchSettings.json that I got it working with:
> 
> ```
> {
>   "iisSettings": {
>     "windowsAuthentication": false, 
>     "anonymousAuthentication": true, 
>     "iisExpress": {
>       "applicationUrl": "http://::65093",
>       "sslPort": 44352
>     }
>   },
>   "profiles": {
>     "IIS Express": {
>       "commandName": "IISExpress",
>       "launchBrowser": true,
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     },
>     "webapp": {
>       "commandName": "Project",
>       "launchBrowser": true,
>       "applicationUrl": "https://::5001;http://::5000",
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     }
>   }
> }
> ```

When I do this I get an "Invalid URI: The hostname could not be parsed" Error.
