### ISSUE TITLE
WSL filesystems general purpose availability

### ISSUE THREAD

**Issue by tinchou** [Microsoft/WSL#414]
Hi,

This thread is to discuss the possibility of opening up the WSL filesystems for other purposes.

I'm really excited about this project and all the innovation around it, as I usually work both with Windows and Linux. Docker is also part of my workflow, and right now I'm testing the Docker for Windows beta (hopefully you are too!).

I'm not a docker dev, but as I was poking around and having some issues with symlinking support in Windows, I was at the same time having issues with symlinking with Bash on Windows (e.g. see [here](https://forums.docker.com/t/symlinks-on-shared-volumes-not-supported/9288)). I'm also seeing that your filesystems are evolving and have great support now, and I thought this could be a great opportunity for colaboration!

Currently, Docker for Windows uses an SMB share, which lacks the necessary support for things as basic as installing and running some node modules (I found [this post](http://docker-saigon.github.io/post/Docker-Beta/) explains all the gory details very well).

I don't know if this is even feasible for docker to integrate, but I thought it would be great to start the conversation here.

So, what do you think??

**Comment by russalex** [comment]
Excellent thought.  We are just starting to have some of these conversations internally.  We are still in the discussion / exploring phase here but we know that there is a need here.

We can share more information once we have something, but that may take a little time.

**Comment by atrauzzi** [comment]
https://twitter.com/richturn_ms/status/730530167156658177

This short discussion had me under the understanding that the WSL team hasn't quite cracked the symlink thing yet either.

But I totally agree, this is a chance for collaboration.

**Comment by Moonlighter** [comment]
Hi,

Yesterday i try to install angularjs-cli on SharFolder between a host (Windows10) and à VM on VMware 12(Workstation, with Ubuntu 14.04 LTS)

[In my Ubuntu.vmx]

sharedFolder0.present = "TRUE"
sharedFolder0.enabled = "TRUE"
sharedFolder0.readAccess = "TRUE"
sharedFolder0.writeAccess = "TRUE"
sharedFolder0.hostPath = "C:\wamp\www"
sharedFolder0.guestName = "www"
sharedFolder0.expiration = "session"
sharedFolder0.followSymlinks = "TRUE"

I access to my ShareFolder on my VM here /mnt/hgfs/www/

So after i try to install i receive this issues:

EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
Error: EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
    at Error (native)

Somebody have an idea? Thank's!

**Comment by aseering** [comment]
Hi @Moonlighter -- it sounds like you're using native Ubuntu and VMware, not WSL?  (WSL is VMware's new tool for running Linux binaries natively on Windows, without a Linux VM running at all.)  You would probably have more luck on the VMware forum.

That said -- I think VMware HGFS volumes may not support symlinks?  So that might be the cause of your error.

**Comment by Moonlighter** [comment]
@aseering Thank's for your answer, i'll try it! :)

**Comment by marfillaster** [comment]
If only there's a way for windows to mount  virtual or physical ext-like partitions.

**Comment by therealkenc** [comment]
This discussion ran course in 2016. WSL supports a few MSFT branded filesystems (cifs, fat32, cdfs) as of the [Windows Filesystem Improvements](https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/) in 16176 and Fall Creators Update 16299. For other third party and MSFT filesystems there are various open issues such as #579 #2896 #2999 etc etc.
