### ISSUE TITLE
Certain `wsl.conf` file breaks WSL2

### ISSUE THREAD

**Issue by TerrorJack** [microsoft/WSL#4140]
## Your Windows build number:

```
Microsoft Windows [Version 10.0.18917.1000]
```

## What you're doing and what's happening:

Set WSL 2 as default version, install Debian from the store, then add the following `/etc/wsl.conf`:

```
[interop]

enabled=false

appendWindowsPath=false
```

## What's wrong / what should be happening instead:

After `wsl.conf` is added, next time `wsl.exe` or `debian.exe` is invoked in powershell, bash prompt is not displayed, and nothing seems to happen (but `wsl -l` shows that `Debian` is running)

**Comment by benhillis** [comment]
Thanks for filing! I will fix this ASAP, I think this might be the cause of some other issues...

**Comment by TerrorJack** [comment]
Fix confirmed locally in 18945, and also listed in https://docs.microsoft.com/en-us/windows/wsl/release-notes#wsl. Closing and thanks for all the work!
