### ISSUE TITLE
Access is Denied message when converting Ubuntu 18.04 to use WSL2

### ISSUE THREAD

**Issue by ScottBarkman** [microsoft/WSL#4141]
I'm receiving an `Access is Denied` message trying to convert my Ubuntu 18.04 environment to use the new WSL2. I was able to successfully convert a brand new 16.04 instance, but can't seem to convert my main environment. 

```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Access is denied.
```

Let me know what logs would be required, since they aren't inside of ubuntu per say, just in Powershell where I'm attempting the conversion.

**Comment by mscraigloewen** [comment]
Could you collect the detailed logs for us and post them here? Instructions on how to do so can be found [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). Thank you!

**Comment by melaniejones731** [comment]
Hello, this is my response on Issue #6967:
Hi Stefan, thank you for your response. Interestingly, when I run this command from the Windows Terminal Power Shell instance, I see my Ubuntu instances and they claim to be version 2 WSL.

![terminalpic](https://user-images.githubusercontent.com/28410534/83337787-6658e380-a27b-11ea-8c5b-ec795ce428fd.png)

However, when I run the same commands from Windows PowerShell (as admin), I get an Access denied message similar to what is shown in Docker for Windows.

![powershellpic](https://user-images.githubusercontent.com/28410534/83337786-65c04d00-a27b-11ea-8616-b82652aa5add.png)

Do you think resolving this WSL issue will also resolve the problem where I am unable to switch back from windows containers to linux containers?

Also, my goal is to use WSL for development environment on a docker project which uses docker-compose. I am behind a corporate proxy which seems to have some impact.
