### ISSUE TITLE
All files and folders with 777 permissions after clone repo in wsl2

### ISSUE THREAD

**Issue by Soufraz** [microsoft/WSL#4142]
* Your Windows build number: 
Version	10.0.18917 Build 18917

* What you're doing and what's happening:  
After clone git repo all permissions are changed to 777.

* What's wrong / what should be happening instead:
The permissions in repo is completly different.

/etc/wsl.conf
```
[automount]                                                                                                                                                                                                     
enabled=true                                                                                                                                                                                                    
options=metadata,uid=1000,gid=1000,umask=022 
```

**Comment by therealkenc** [comment]
I think this is related to our old friend #352. I did a double take too when I saw it yesterday, and figured I'd wait for someone else to report. That's you I guess. I haven't looked exactly into why this is happening, and it doesn't make a lot of sense to me either. I have a dangerously unsupported guess though. That guess being, WSL1 semantics were subtly broken, and we should have seen this for three years. And now they aren't because the semantics are correct. [Noting that would be all wrong.]

Specifics matter here so first step is going to be a repro (because pronoun 'this'). Toy github repository with a few files and directories, where the `/usr/bin/git ls-files --stage` line in your steps is sane. Current working directory matters, so that too. I would start with working off `/home` rather than inviting `/mnt/c` to the party.

In the mean time, workaround do a `umask 0022` at the bash prompt before the `git clone`. Which Just Works™. But there is some 'splainin to do here, and I don't have clear sense yet as to why there is a **_change_** in behavior with wsl2, when we've had the #352 problem all along, and still do.

**Comment by Soufraz** [comment]
So it really works only inside the /home folder. Using /mnt/c ou d doesnt fix the permissions. 

I dont know if it is a knowning issue by wsl developers. If we think about it, make windows permissions as linux is left the windows permissions on the fly. Probably developers know that and will figure out a way to dont change their core (I really dont know the windows permissions system at the low level.. so it is a big guess).

By the way after make my main projects works in wsl2 with docker and permissions fixed now I realize that we have a problem with mapping wsl drive to host too. So what is happend, I need change my code right? Then I mapped the wsl drive to my machine and then open it in phpstorm or vscode. When both of ides finish to index files, after maybe 15 or 20 minutes the mapped network drive disappear and I need to do it again. Very boring and I cant use wsl2 to full develop in windows yet.

**Comment by therealkenc** [comment]
> So it really works only inside the /home folder

You've got 'it' pronoun without CLI repro steps to reproduce the it you to which you are referring. So I can't say for your scenario. But in the interest of forward motion, I did try:
```
$ cat /proc/version
Linux version 4.19.43-microsoft-standard (oe-user@oe-host) (gcc version 7.3.0 (GCC)) #1 SMP Mon May 20 19:35:22 UTC 2019
$ sudo bash -c "cat << EOF > /etc/wsl.conf
[automount]
enabled = true
options = metadata,uid=1000,gid=1000,umask=0022
EOF"
$ exit
C:\> wsl.exe --shutdown
C:\> wsl.exe
$ mount | grep 'C:\\'
C:\ on /mnt/c type 9p (rw,noatime,sync,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;uid=1000;gid=1000;umask=0022,access=client,trans=fd,rfd=8,wfd=8)
$ umask 0022
$ sudo apt install git
$ cd /mnt/c/Users/ken && mkdir 9ptest && cd 9ptest
$ git clone https://github.com/therealkenc/wsl-umask-toy.git
$ cd wsl-umask-toy
$ /usr/bin/git ls-files --stage
100644 b8f2223eaa5ddb41a71aabc076a122a581199733 0       README.md
100644 ce013625030ba8dba906f756967f9e9ca394464a 0       dir/hello.txt
$ ls -l wsl-umask-toy/dir/file.txt
-rw-r--r-- 1 ken ken 6 Jun 18 14:45 ./wsl-umask-toy/dir/hello.txt
```

The permissions are correct. Long story short dupe this issue appears dupe #352.

**Comment by Soufraz** [comment]
After follow your steps permissions works. Thank you.
Only thing here that didnt respond as in your example was:

```
#  mount | grep 'C:\\'
C:\ on /mnt/c type 9p (rw,noatime,sync,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;metadata;uid=1000;gid=1000;umask=0022,access=client,trans=fd,rfd=9,wfd=9)
```

But affter clone my project all permissions was preserved. Thank you.

**Comment by therealkenc** [comment]
> Only thing here that didnt respond as in your example was:

Academic. But now you said it... so gotta ask or it'll nag me. By "didn't respond" I assume the `grep` did not get a hit. Maybe do a naked `mount` without the filter and look for the `/mnt/c` among the other mounts. Might be subtly different for reasons yet unknown.

**Comment by Soufraz** [comment]
Now I just realized that git seems not to know how to handle the files on drive c:

```
# git status
on branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    .env.example


It took 2.25 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")
```

When I make the clone inside vm in / home / project i git status works normally.

**Comment by therealkenc** [comment]
> # git status

That is not a repro. The OP one was free.

> But I think that is another issue.

That would make three counting the OP.

**Comment by blkwtch** [comment]
`umask 0022` can also be added to your` .bashrc` to avoid having the issue again

**Comment by tassoman** [comment]
I have symlinked a folder inside my home dir `C:\Users\Me\mydir` using `ln -s /mnt/c/Users/Me/mydir` but ... nothing happens. 
I still have only that files and directories in 777 mode. The first directory missing the mod is `/mnt/c/Users/Me`

Reading this document, I created the `/etc/wsl.conf` file, I've checked **fstab** with no luck, I added `umask 0022` to `~/.bashrc` then I've executed it inside bash console. Doesn't seem to work.
Should I edit windows folder privileges in explorer.exe ?

**Comment by tassoman** [comment]
I solved by avoiding symlinking to /mnt/c/... 
Explorer.exe can access WSL filesystem by configured "network" `\\wsl$\Ubuntu\home\Me\mydir`
