### ISSUE TITLE
(WSL2) Cannot map network drive to Linux filesystem

### ISSUE THREAD

**Issue by BusterNeece** [microsoft/WSL#4143]
* Your Windows build number: Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening: Attempting to map a network drive using Windows Explorer that points to the Linux file system of an Ubuntu 18.04 distribution running inside WSL2.

* What's wrong / what should be happening instead: Despite Explorer being able to see the `\\wsl$` directory and navigate through it, when attempting to mount it as a network drive, either through the "Easy Access" menu from the directory itself or from "Map Network Drive" at "This PC", the same error appears: `Windows cannot access \\wsl$\Ubuntu-18.04\the\path\specified`, specifically error code `0x80070043`.

I'm aware of the existence of issues #3854 and #3996, which both seem to be referring to a similar issue, but it appears those issues apply to WSL1 and this is a new problem relating to WSL2. The previous issues were reported as fixed several builds prior to 18917 (which appears to be the current "Fast" ring build), but I'm still experiencing this issue as of the newest version with WSL2.

**Comment by patpilus** [comment]
@SlvrEagle23, I've got the same issue when trying to map my home directory on WSL2 ubuntu distribution. However, mounting the root path `\\wsl$\ubuntu` works flawlessly

**Comment by SlvrEagle23** [comment]
@patpilus Interesting, can confirm on my end as well that if you specifically mount `\\wsl$\Ubuntu-18.04`, nothing more, nothing less, it works, but that's the only path I can get to mount properly.

**Comment by onomatopellan** [comment]
You can also pin a wsl folder on Quick Access . I just tried and it even opens the folder without having WSL open.

**Comment by erikhakansson** [comment]
I can map drives, if I map to root `\\wsl$\Ubuntu` but frequently that mapped drive stops working and I get an "U:\ is unaccessible. The parameter is incorrect".

I get it everytime after hibernating and quite often without that.

**Comment by asolopovas** [comment]
+1

**Comment by Gaibhne** [comment]
+1

**Comment by lyhu** [comment]
+1

**Comment by MohitKumarAgniotri** [comment]
+1

**Comment by CComparon** [comment]
+1

**Comment by Darkvater** [comment]
+1; still an issue

**Comment by SalmanMarvasti** [comment]
still an issue

**Comment by tommyb82** [comment]
Just encountered this after a restart - Win 10 Pro 21H1 build 19043.1110.  Exact same error code as OP - `0x80070043`.  Can't remap drive but can access `\\WSL$\Ubuntu\` directly in windows explorer fine.

**Comment by psgrove** [comment]
I have the same issue no linux dive mapped in windows explorer side nav, I can map the network drive but can get to Ubuntu file system by using \\WSL$\Ubuntu in windows explorer address bar
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by jacarrico** [comment]
I am also having the same issue. Can't map the drive or open in explorer. 

Trying to map or open to `\\wsl$\Ubuntu-18.04`. Which is the distro I have 

Also in WSL can't open the folder in windows with `explorer.exe .` command

Win10 Version 20H2 (OS Build 19042.1165)

**Comment by brunopulis** [comment]
> I am also having the same issue. Can't map the drive or open in explorer.
> 
> Trying to map or open to `\\wsl$\Ubuntu-18.04`. Which is the distro I have
> 
> Also in WSL can't open the folder in windows with `explorer.exe .` command
> 
> Win10 Version 20H2 (OS Build 19042.1165)

Same here 😢

**Comment by OliverKohlDSc** [comment]
Hi guys,

the same issue can be found on a Windows 11 system (Windows 11 Pro Insider Preview, Build 22463.rs_prerelease.210917-1503).

![Issue](https://user-images.githubusercontent.com/8104064/135724617-f04664d6-8881-447e-a761-78424250990e.png)

Beside that I wanted to say thanks for WSL2. A great system!

👍😎

Thanks
Oliver

**Comment by vanarajan2496** [comment]
+1
