### ISSUE TITLE
WSL 2 conversion fails without any actionable details

### ISSUE THREAD

**Issue by flynnham** [microsoft/WSL#4145]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
PS C:\Users\Flynn Buckingham> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18917  0
```

* What you're doing and what's happening:

I'm attempting to migrate my WSL Ubuntu (1) over to (2), but the migration fails without any key indicators (besides a vague error message). While I'd love to have WSL 2 working, the lack of actionable output makes me a bit uneasy. (Also, I have restarted twice as of writing, after enabling the WSL 2 feature)

```
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux               

FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux




PS C:\WINDOWS\system32> wsl --list --verbose                                                                              
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2                                                                      Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
A device attached to the system is not functioning.
PS C:\WINDOWS\system32> wsl --list --verbose                                                                             
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
```

* What's wrong / what should be happening instead:

It should at least be giving me actionable error information; but ultimately should be working.

**Comment by chodges15** [comment]
I'm seeing this as well with both Debian and Ubuntu:

```
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform                       

Path          :
Online        : True
RestartNeeded : False



PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux Distributions:
Debian (Default)
Ubuntu
PS C:\WINDOWS\system32> wsl --set-version Debian 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Unspecified error
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Unspecified error
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME      STATE           VERSION
* Debian    Stopped         1
  Ubuntu    Stopped         1
PS C:\WINDOWS\system32>
```
At least I can still access WSL using V1 after the failed conversion. I was surprised by the ability to auto convert my V1 WSL to V2, this will be really nice when it works.

**Comment by kevin-coyle** [comment]
Hey @flynnham I had the same message as this and I resolved it by removing Acrylic DNS. Maybe see if you have that installed or something similar?

**Comment by flynnham** [comment]
@kevin-coyle That seems to have done the trick, though I am 1100% certain I wouldn't have figured this out intuitively.

**Comment by haydennyyy** [comment]
What's Acrylic DNS?

**Comment by benhillis** [comment]
Thank for filing, let's track install / conversion failures with #4112.  Agreed, the error messages could be better, and when the root causes are identified I'll add some better errors.

**Comment by flynnham** [comment]
@haydennyyy Acrylic DNS is like a supercharged override fot eh `hosts` file found in `system32`. I use it to enable me to develop websites on my Windows 10 machine using wildcard domains.

It looks like WSL currently has issues where programs that are altering the underlyuing windows networking tools, it causes it to fail. I'd try and seeing if you have any network altering programs running (like some antivirus programs, DNS resolvers, other network altering services) that are breaking it.

**Comment by haydennyyy** [comment]
Well, I've never installed that...

**Comment by mbonig** [comment]
Having the same problem. Worked for a few days after the initial install and then produced the same error message everyone else is getting. After the latest Windows update WSL2 started magically working again for a day or two then went back to throwing an error. Not sure where to find any useful logs, though.
