### ISSUE TITLE
WSL fails to launch after file downloads

### ISSUE THREAD

**Issue by mwbaxter11** [microsoft/WSL#4146]
I am running Windows 10.0.18362.175 using Ubuntu 16.04.06. Whenever I run commands which get data from remote servers (like rsync or apt-get upgrade), and then close the shell, I can't restart WSL because it fails to launch. 

Here are steps which reliably reproduce the problem for me:

- Open a cmd console as Admin
- Run bash script to do rsync copy from remote machine. The rsync command is of the form:
- `sudo -u <userid> rsync -av --delete -e "ssh -i <rsa_file>" --exclude-from=<exclude_file> <userid>@<remotehost>:/ --rsync-path=<remote_script_file> <local_dest_folder>`
- rsync finishes successfully, bash closes OK
- wait 0-60 seconds
- open another cmd window
- type bash
- WSL does not start - just shows a blank window with blinking cursor

The only fix is to restart the PC.

Please see attached log files which contain an example of this.
[logs.zip](https://github.com/microsoft/WSL/files/3293069/logs.zip)

It's all a little bit frustrating. What can I do to avoid this?

**Comment by mscraigloewen** [comment]
Seems related to #4047 . We're looking into a fix!

**Comment by mwbaxter11** [comment]
Thanks very much, that's good to hear. Is there any known workaround in the short term?
