### ISSUE TITLE
Not able to lauch gui apps on wsl2 

### ISSUE THREAD

**Issue by elswerky** [microsoft/WSL#4147]
I was able to run linux gui apps and xfce4 desktop on wsl (1)  using x11 app such as x410 
on a localhost 

but now on wsl2 i am not able to run gui apps or lauch xfce4 desktop on wsl2 

plz help me and tell me what to do to be able to run gui apps on x410 like it was working on  wsl (v1)

**Comment by Biswa96** [comment]
Duplicate #4106.
