### ISSUE TITLE
Unable to run exe from Gnome-Terminal

### ISSUE THREAD

**Issue by karuboniru** [microsoft/WSL#4148]
# Your Windows build number:  

18197.1000

# What you're doing and what's happening:  

## When In Gnome-terminal (tilix had the same problem)

[yan@BOOK-Karuboniru ~]$ ipconfig.exe
<3>init: (217) ERROR: UtilConnectToInteropServer:270: connect failed 2
[yan@BOOK-Karuboniru ~]$ 

## When In CMD.exe ----> run wsl.exe--->run something else

I can call exe programs normally
# What's wrong / what should be happening instead:

I didn't test if it behaves the same in WSL1. I am using WSL 2

Calling exe should work fine even in Linux Terminal apps 

[log.zip](https://github.com/microsoft/WSL/files/3293412/log.zip)

**Comment by karuboniru** [comment]
I think I have found the reason. Different session gives different WSL_INTEROP, and those in Gnone-Terminal or some other gui terminal apps doesn't work.

If I export WSL_INTEROP in wsl started from cmd to Gnome-Terminal, everything works fine. If I do the opposite way, both will stop calling exe programs

**Comment by karuboniru** [comment]
Actually if I start Gnome-terminal with 
`ubuntu1804.exe run "cd \"$(wslpath .)\"; source /home/yan/.profile; gnome-terminal"`
I will found the wsl instance would have wrong WSL_INTEROP
but if I run ubuntu1804.exe first, and then gnome-terminal. Everything will work.

**Comment by karuboniru** [comment]
Found a solution: 
add 
```
if [ ! -f "$WSL_INTEROP" ]; then
	export WSL_INTEROP=/run/WSL/`ls /run/WSL/|awk 'NR==1{print}'`
fi
```
to ~/bash_profile
and go to Edit -> Profile Preferences -> Title and Command tab check the "Run command as a login shell" option.
Gnome-terminal will work fine in this way.

**Comment by mscraigloewen** [comment]
Hi @karuboniru it seems like you have a solution to your issue! Thank you for your detective work, if everything is working please close out the issue. :)

**Comment by benhillis** [comment]
@karuboniru - I wouldn't suggest that solution.  I am working on a fix for this.

**Comment by karuboniru** [comment]
> @karuboniru - I wouldn't suggest that solution. I am working on a fix for this.

Yes. My code "stole" a WSL_INTEROP socket randomly from `/run/WSL/.` and the socket may close before you exit your Terminal. 

Maybe you can provide a persisting socket in next releases?

**Comment by elig0n** [comment]
I experience the same problem in TMUX but not outside it. I have several `_interop` files under /run/WSL/ some of them would make my terminal hang, few others (once that show up in wsl terminals without tmux) would proceed to execute windows .exe files normally.
