### ISSUE TITLE
(WSL2) VS code remote editing shows empty file when opening symlink

### ISSUE THREAD

**Issue by simmessa** [microsoft/WSL#4152]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

**Microsoft Windows [Version 10.0.18917.1000]**

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```
echo "text example" >> text
ln -s ./text ./textlink
code textlink 
```

* What's wrong / what should be happening instead:

The expected behaviour is to have code display on Windows the content of the file, but it shows an empty file instead, this is due to the symbolic link, which currently cannot be recognized by code remote editing (WSL2) capabilites

**Comment by therealkenc** [comment]
Was able to reproduce this with (what I am pretty sure are) all the correct ducks in line. Problem demonstrated more generally:

![image](https://user-images.githubusercontent.com/7049700/59726750-bca65100-91e7-11e9-9fd4-16dffb3170e8.png)

Work-arounds while improvements arrive same as #4188. Symlinks in the [SSH variety](#4188) of VS Code Remote with [Windows OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview) is okay, as is Samba.

![image](https://user-images.githubusercontent.com/7049700/59729748-ae126680-91f4-11e9-9287-9458a358e6c6.png)

**Comment by bpulliam** [comment]
If you still have issues like this, please open a new issue.  Much has changed in WSL since this time.

**Comment by therealkenc** [comment]
#5118 is a dupe that can can serve as the landing zone. There are 39 likes over there as of this writing. The problem remains in 21370 WSL1 and WSL2.
