### ISSUE TITLE
WSL2 Breaks, can't start.

### ISSUE THREAD

**Issue by vysecurity** [microsoft/WSL#4156]
I previously used VMWare, so I applied:

```
bcdedit /create {0cb3b571-2f2e-4343-a879-d86a476d7215} /d "DebugTool" /application osloader
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} path "\EFI\Microsoft\Boot\SecConfig.efi"
bcdedit /set {bootmgr} bootsequence {0cb3b571-2f2e-4343-a879-d86a476d7215}
bcdedit /set {0cb3b571-2f2e-4343-a879-d86a476d7215} loadoptions DISABLE-LSA-ISO,DISABLE-VBS
bcdedit /set hypervisorlaunchtype off

```

But now I changed it back with:

```
bcdedit /set hypervisorlaunchtype auto

```

And it still won't run WSL 2. I even turned on all the necessary Control Panel features.

![image](https://user-images.githubusercontent.com/3596242/59567384-ed7b6e80-909f-11e9-8adb-cc72258a5f28.png)

**Comment by vysecurity** [comment]
![image](https://user-images.githubusercontent.com/3596242/59567816-57e2dd80-90a5-11e9-9d8e-162ca251d9f8.png)

**Comment by vysecurity** [comment]
Even Sandbox works now. But WSL2 doesn't.

**Comment by vysecurity** [comment]
I don't even know how to debug it.

**Comment by vysecurity** [comment]
v
![image](https://user-images.githubusercontent.com/3596242/59568312-86fc4d80-90ab-11e9-8cf2-218f27f47d0b.png)

**Comment by vysecurity** [comment]
Note: Not a Kali Issue, it happens with Ubuntu too.

**Comment by vysecurity** [comment]
Just in case someone doesn't believe me: 
![image](https://user-images.githubusercontent.com/3596242/59568438-44d40b80-90ad-11e9-867a-3e5a794faf78.png)

**Comment by OmriSama** [comment]
What is your Event Viewer saying? Go to Event Viewer and look for any logs that look like they have to do with Hyper-V, Virtual Machine Platform, or WSL/lxcore.

**Comment by vysecurity** [comment]
Nevermind, I rolled back Windows, then reinstalled Update. Thanks :)
