### ISSUE TITLE
how to start wsl2 Distro

### ISSUE THREAD

**Issue by yangyuw** [microsoft/WSL#4160]
**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  wsl2 stopped when I reboot and I don't know how to start again. `--help` don't helped me .  `wsl` **closed immediately after I open it.** `wsl -l -v` show blow:
```
C:\Users\52945>wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
```

**Comment by andreluizgit** [comment]
bash

**Comment by m1styLife** [comment]
I guess you've encountered this issue(#4105).

**Comment by mscraigloewen** [comment]
@yu-yang2 could you send the command lines and error outputs that you're seeing when trying to start WSL?
What do you see when you run `wsl.exe` ?

**Comment by yu-yang2** [comment]
@mscraigloewen When I open wsl.exe, the command box pops up for a second and then closesd immediately, no error logs.

**Comment by SvenDowideit** [comment]
`wsl.exe`  need command line parameters
for example, i just ran `wsl.exe -d Debian` to run the debian distro

start a powershell cmd shell, and play with the wsl command there (wsl itself doesn't have a UI)

**Comment by yu-yang2** [comment]
@SvenDowideit when I run `wsl.exe -d  Ubuntu-18.04`, it shows error blow.
```
PS C:\WINDOWS\system32> wsl.exe -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
PS C:\WINDOWS\system32> wsl.exe -d Ubuntu-18.04
The referenced object type does not support the attempted operation
PS C:\WINDOWS\system32> wsl
The referenced object type does not support the attempted operation
PS C:\WINDOWS\system32> wsl.exe
The referenced object type does not support the attempted operation
```

**Comment by benhillis** [comment]
@yu-yang2 - that is a new error, could you please collect a trace?

**Comment by yu-yang2** [comment]
@benhillis cloud you please tell me how to collect wls.exe trace?

**Comment by benhillis** [comment]
Instructions are in our contribution instructions under "collect detailed logs".

**Comment by tyskink** [comment]
![image](https://user-images.githubusercontent.com/22754217/64437261-944c3580-d0f8-11e9-88c6-3a8ae8fd5443.png)
same problem after convert wsl1 to 2.

**Comment by redblue9771** [comment]
I just upgraded 18990.1 in order to use wsl2, and it stopped.

```PowerShell
PS C:\WINDOWS\system32> wsl -l -v
  NAME      STATE           VERSION
* Alpine    Stopped         2
PS C:\WINDOWS\system32>
```

**Comment by redblue9771** [comment]
#4105 According to this issue, I cleared the hosts file and used solved it.
