### ISSUE TITLE
WSL2: wsl.exe shell not picking up $PATH

### ISSUE THREAD

**Issue by KSiig** [microsoft/WSL#4167]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:
Trying to issue a command with `wsl.exe bash -c`. Whatever command I try to execute, it will show the following message: `/bin/ash: bash: not found`

* What's wrong / what should be happening instead:
For some reason, the shell is not picking up $PATH, when executed through `wsl.exe`(verified by simply running `wsl.exe echo $PATH`). This ultimately means I cannot use the Remote Development tool in VSCode, since it can't find `/bin/bash`. 

I've also tried using multiple shells directly in WSL 2, to print out $PATH, and it works every time.

**Comment by benhillis** [comment]
You are using alpine, which does not have bash installed by default.  If you launch alpine using wsl.exe, then apk install bash, it will work.

**Comment by benhillis** [comment]
@KSiig - Would you mind creating a VSCode issue that they are relying on /bin/bash?  They really should use /bin/sh instead.

**Comment by KSiig** [comment]
Huh, you are absolutely right. Installed it quickly to test something, and didn't realised it changed my default WSL from Ubuntu. I'll go right ahead and open that issue, but just to be sure: It should be an issue on the repo of the extension, right? Or is using /bin/bash a default of VSCode itself?

Oh and thanks for the quick answer!

**Comment by benhillis** [comment]
No problem, yes likely the extension is the right place for the issue, but they will know better than me.
