### ISSUE TITLE
"Unspecified error" when converting WSL1 to WSL2

### ISSUE THREAD

**Issue by patrick330602** [microsoft/WSL#4168]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  18917

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

![image](https://user-images.githubusercontent.com/15316889/59618275-77880d80-915a-11e9-9162-b0cbb4ec5bb4.png)

`wsl --set-version` reported **unspecified error** when converting a WSL distro from WSL1 to WSL2 when a WSL2 Distro is opening.

* What's wrong / what should be happening instead:

It should display an error that a distro is running.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Biswa96** [comment]
The error code seems to be similar with #4102.

**Comment by patrick330602** [comment]
Some additional information: After completing the conversion, Ubuntu went back to install state (which I have already complete installing) and giving error code 0x80080005
![image](https://user-images.githubusercontent.com/15316889/59620118-a4d6ba80-915e-11e9-9ab0-fa83ef34cdd4.png)

**Comment by benhillis** [comment]
Let's keep all the conversation in #4102.
