### ISSUE TITLE
WSL2: nodemon file watcher no longer working

### ISSUE THREAD

**Issue by adamlacombe** [microsoft/WSL#4169]
**Your Windows build number**: 10.0.18917.1000

**What you're doing and what's happening**:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

I'm running [nodemon@1.19.1](https://github.com/remy/nodemon)

My working directory is located in `/mnt/c/Users/Adam/Documents/...`

My `nodemon.json`:
```json
{
  "watch": [
    "**/*.ts"
  ],
  "ext": "ts",
  "ignore": [
    "./test/*.ts",
    "./node_modules/**/node_modules"
  ],
  "exec": "node -r ts-node/register Index.ts",
  "env": {
    "NODE_ENV": "development"
  }
}
```

I run: `nodemon --delay 1500ms --signal SIGTERM` and then modify a file that is being watched.

I'm modifying the file from outside WSL, but I have also tried from within WSL using `nano`.

**What's wrong / what should be happening instead**: After updating to WSL2 `nodemon` no longer triggers a restart of my application.

I'm able to run `nano ./modified_file.ts` and see the change. 

In another project built with [Stencil@1.0.4](https://github.com/ionic-team/stencil) I'm able to run `stencil build --dev --watch --serve` and file modifications trigger a reload.

**Comment by therealkenc** [comment]
Yep. The /Build 2019 [presentation](https://www.youtube.com/watch?v=lwhMThePdIo) the devs mention that they (quoth) "still need to plumb" [`inotify(7)`](http://man7.org/linux/man-pages/man7/inotify.7.html) on the 9p filesystem. The word "plumb" is carrying a lot of weight there. Ref #1956 ([message](https://github.com/microsoft/WSL/issues/1956#issuecomment-491266167)).

In the meantime, the WSL 2 launch [blog post](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) suggests:

> We understand that we have spent the past three years telling you to put your files into your C drive when using WSL 1, but this is not the case in WSL 2. To enjoy the faster file system access in WSL 2 these files must be inside of the Linux root file system.

Faster, yes. But for the purposes of your scenario (and a few other edge cases), also to have access to the complete set of ext4 filesystem features.

**Comment by adamlacombe** [comment]
That makes sense. Moving my project into the linux file system solves the issues with inotify. Thanks

**Comment by canselcik** [comment]
This is related to https://github.com/microsoft/WSL/issues/4064#issuecomment-501047822 just like https://github.com/microsoft/WSL/issues/4224.

**Comment by therealkenc** [comment]
#4064 as LZ

**Comment by LiamKarlMitchell** [comment]
@therealkenc @adamlacombe Could you please elaborate on how to solve this by putting the project into the linux file system so that inotify works?

Would like to be able to run docker containers from windows, map the files in as volumes and have changes auto-reload by using inotify/related tools e.g. nodemon/hotreload/Quasar is this possible?

**Comment by onomatopellan** [comment]
@LiamKarlMitchell the linux file system is the /home/* folder. It will work faster and better if you move/clone your code there. Also remember to install any tool you need in it's Linux version.

The [Docker for Windows Edge](https://docs.docker.com/docker-for-windows/edge-release-notes/) with WSL2 backend supports your scenario but you will also need to use VSCode + Remote Extensions in order to edit files with inotify support inside the Linux distro.
It was explained in https://www.docker.com/blog/developing-docker-windows-app-wsl2/

**Comment by rodrigogs** [comment]
Just run `wsl --set-version {my_linux} 1`

Yeah, go back to WSL 1, it just works.

**Comment by Yassine-49** [comment]
> Just run `wsl --set-version {my_linux} 1`
> 
> Yeah, go back to WSL 1, it just works.

but what if you are using WSL 2 for a reason

**Comment by Witti** [comment]
> > Just run `wsl --set-version {my_linux} 1`
> > Yeah, go back to WSL 1, it just works.
> 
> but what if you are using WSL 2 for a reason

You can migrate all your projects to the linux partition within WSL and then access the files via `\\wsl$`

**Comment by fonziemedia** [comment]
> That makes sense. Moving my project into the linux file system solves the issues with inotify. Thanks

@adamlacombe  do you mean you managed to get nodemon working on WSL 2 by moving the project into the linux file system?
Does this not give you problems when trying it edit files from a windows code editor? I can't seem edit any linux file systems files from Visual Studio Code per example..
Thanks

**Comment by LiamKarlMitchell** [comment]
Yeah it works fine in the WSL 2 file system faster as well :)

**Comment by fonziemedia** [comment]
Thanks @LiamKarlMitchell!
I just had to give permissions to my projects folder to enable editing from vs code and it's all working great :)

**Comment by mohemos** [comment]
@fonziemedia how did you give the permission? Do you still have your files on windows file system or you also moved it to linux file system?

**Comment by fonziemedia** [comment]
Hi @mohemos 
I moved the files to the Linux file system as advised on this thread and then did the following on WSL:
`sudo chown -R [username]:[group] [directory_name]`
example:
`sudo chown -R cartman:cartman projects`

Extra info:
I'm using Remote WSL on VS code.
To check the user VS code uses I opened a remote terminal inside VS code and typed:
`whoami`
To check your group:
`groups`
This is for Ubuntu But it may vary depending on the Linux dist you're using

Hope this helps

**Comment by LiamKarlMitchell** [comment]
Only issue so far with having the code in WSL is that git kraken is rather sluggish on large projects. You can run an XServer in it and launch GUI from WSL however.

**Comment by areizas** [comment]
I am using the WSL 2 and I solved the issue by adding the following env variable: **CHOKIDAR_USEPOLLING=true**

`
This is how looks like my nodemon command:
`
CHOKIDAR_USEPOLLING=true nodemon index.js
Now you can keep WSL2 instead of moving your environment to WSL1.

**Comment by nuran571** [comment]
reply+APDAAINMEX2KRF6VFGP63IN6FRNS7EVBNHHBWPN5PA@reply.github.com

**Comment by nuran571** [comment]
reply+APDAAINMEX2KRF6VFGP63IN6FRNS7EVBNHHBWPN5PA@reply.github.com

**Comment by slim-hmidi** [comment]
I face the same issue here. 
`wsl -l -v` :
```
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
```
Should I download any linux distribution like ubuntu to work with it on windows. When I update any file in the node server, it takes around 3 minutes for nodemon to take into consideration the changes and reload the server and it is long time. The previous version of docker took 30s to reload the server and I can access the app to see the changes.

**Comment by tripolskypetr** [comment]
Great! We made WSL2 but file system is working slower and file watching is broken :-)

**Comment by LiamKarlMitchell** [comment]
@slim-hmidi , yeah so I run Ubuntu on WSL2 and have source files for projects etc on the WSL2 file system, it is faster than running it on the Windows side, but that means you also need tools that can work with the wsl path (intelij ide's seems to work ok other than generated files from cli not updating in IDE fast but you can rightclick reload from disk)

It does mean I have two installations of gitkraken but im actually trying to use the git that is built-in to intelij/phpstorm more frequently atm which seems to work well.

When I ran from windows and volume mapped a directory of source code or other files I watched, to do hot-reload etc it did not work great from windows filesystem side.
