### ISSUE TITLE
Not able to browse files with explorer.exe if the directory was mounted with SSHFS

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [microsoft/WSL#4172]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Mounting a directory with sshfs in WSL2 and browsing it using explorer.exe.
```bash
sudo apt-get update
sudo apt-get install -y sshfs
mkdir directory_for_testing_fuse
sudo sshfs -o allow_other root@xxx.xxx.xx.xx:/ ./directory_for_testing_fuse
ls directory_for_testing_fuse
cd directory_for_testing_fuse
explorer.exe .
```
"This folder is empty"

* What's wrong / what should be happening instead:

I should see the files (root, home, etc, dev...) as they are listed in WSL

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

No command is failing. So no trace available.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

I wonder if this is a bug report or a feature request. Should we expect this scenario to work with WSL2 ?

**Comment by benhillis** [comment]
Thanks for filing this issue, this is due to how we isolated DrvFs mounts for admin / non admin access via mount namespaces.  I have some ideas how to solve this in a future update.

**Comment by gabrieldemarmiesse** [comment]
Thanks for the quick response. I'll wait then.

WSL 2 is awesome. You guys rock.

**Comment by benhillis** [comment]
![image](https://user-images.githubusercontent.com/17727402/60234710-2793ff80-985a-11e9-9f78-5f7cc4dcf8f6.png)

I have a change in CR right now that makes this work.  Stay tuned for an upcoming Insiders build.

**Comment by gabrieldemarmiesse** [comment]
Niiiiiice :)

**Comment by alexbogun** [comment]
Hi,

I am on 18945.1001 and am trying to get SSHFS  to work, but then I type 
sudo sshfs -o allow_other root@xxx.xxx.xx.xx:/ ./directory_for_testing_fuse

I get an error: fuse: device not found, try 'modprobe fuse' first

and on modprobe fuse I get:
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18945-Microsoft/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-18945-Microsoft

What can it be? Thanks in advance!

**Comment by onomatopellan** [comment]
@alexbogun You are using WSL1 becasue it shows the build number 18945. 
Fuse should work in WSL2 and if it doesn't at least it would say "modprobe: FATAL: Module fuse not found in directory /lib/modules/4.19.55-microsoft-standard"

**Comment by jmstrampe** [comment]
@onomatopellan if I'm getting the "modprobe: FATAL: Module fuse not found in directory /lib/modules/4.19.55-microsoft-standard" error in WSL2, is there a way to fix this?

**Comment by onomatopellan** [comment]
@jmstrampe I think WSL2 doesn't support kernel modules. Instead you will need to compile the linux kernel from [here](https://github.com/microsoft/WSL2-Linux-Kernel) with the options you need and then load it with [.wslconfig file](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18945).

**Comment by Biswa96** [comment]
>  I think WSL2 doesn't support kernel modules.

Did you try it? I have not any sshfs system. Throw me any alternative test procedure.

**Comment by onomatopellan** [comment]
@Biswa96 I mean modprobe won't work in WSL2 because modules can't be loaded. But I can be wrong too.

**Comment by adojaan** [comment]
In my wsl2 (w10 1903 18995.1) sshfs is able to mount remote resource and it works well, I can read and write files (in bash), browse folders (with mc) and so on. But when I try to launch explorer.exe . in my sshfs-mounted folder it displays error message 
kristjan@Latirostris:~/Xenops$ explorer.exe .
/mnt/c/WINDOWS/explorer.exe: Invalid argument
 (Xenops is my sshfs-mounted folder).
In other folders the explorer works. When I launch explorer.exe in another folder and then try to open Xenops it displays error
 \\wsl$\Ubuntu\home\kristjan\Xenops is not accessible. You might not have permission to use
this network resource. Contact the administrator of this server to find out if you have access
permissions. Attempt to access invalid address.
The rights, displayed in my wsl2 ubuntu are following:
kristjan@Latirostris:~$ getfacl Xenops
# file: Xenops
# owner: kristjan
# group: kristjan
user::rwx
group::r-x
other::r-x
In windows explorer, Properties -> Advanced displays following info for the sshfs-mounted folder.
Unable to display current owner.
Even Administrator's explorer cannot open this folder.

**Comment by EwolBash** [comment]
I'm glad to have fuse working in WSL 2. Huge thank you to everyone involved for making it a reality.

Just so people know I'm running.

` Microsoft Windows [Version 10.0.19030.1] `

I can open explorer fine so as far I'm concerned it's fixed (if it was broken)

I will post my mount command for people in case it helps.

`sshfs -o allow_other,reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,cache_timeout=3600 user@host.com:/home/user/ /mnt/sshfs/` 

Thank you @benhillis

**Comment by gabrieldemarmiesse** [comment]
I don't have a server to test the fix anymore so if you think the fix has landed @benhilis feel free to close this issue.

Thanks a lot.

**Comment by apetickler** [comment]
The command described by @EwolBash works for me, but when my computer sleeps and wakes back up again, SSHFS seems to be in a bad state. The mount can’t be read or unmounted and I have to kill the SSHFS process.

**Comment by EwolBash** [comment]
How are you trying to unmount it? I'm assuming `fusermount -zu /mnt/whatever`

**Comment by apetickler** [comment]
Ah! I was trying to `umount`. (I’m new to FUSE.) I guess, as far as I can tell so far, everything is working as expected! This is very exciting!
