### ISSUE TITLE
How to install WSL 2 kernel for boot?

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4173]
Having now tried downloading and building - successfully - the WSL 2 kernel source, the next thing on my list was to try switching to this locally-built kernel, but while we have build instructions in README-Microsoft.WSL2, there aren't install instructions.

And, hence my asking, the usual

```
sudo make install
sudo update-initramfs -c -k 4.19.43-microsoft-localhack
sudo update-grub
```

process doesn't seem to do the trick.

**Comment by mscraigloewen** [comment]
We're investigating ways to make it possible for users to configure which kernel WSL 2 is using. Please stay tuned! :)

**Comment by miketheitguy** [comment]
> We're investigating ways to make it possible for users to configure which kernel WSL 2 is using. Please stay tuned! :)

Hi Craig! Was wondering if there's a process for upgrading/updating the kernel?

**Comment by mscraigloewen** [comment]
The kernel that's provided in box will be updated via Windows Update. So once you update your Windows version you'll get the latest Linux kernel version.

**Comment by miketheitguy** [comment]
> The kernel that's provided in box will be updated via Windows Update. So once you update your Windows version you'll get the latest Linux kernel version.

I assume this means kernel security fixes and the like will track Patch Tuesday? Or will be released separately per Windows Store app updates?

**Comment by mscraigloewen** [comment]
That's correct they'll be shipped as a Windows security fix, and so they won't be shipped via the Microsoft Store.

**Comment by cerebrate** [comment]
This is now a supported feature, so closing.
