### ISSUE TITLE
Is it Possible to Run WSL2 and Oracle VirtualBox?

### ISSUE THREAD

**Issue by toml12953** [microsoft/WSL#4174]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Version 1903 OS Build 18917.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

In order to run Oracle VirtualBox, I have to turn off virtual services:
bcdedit /set {current} hypervisorlaunchtype off

* What's wrong / what should be happening instead:
Now when I try to start WSL2, the window flashes open and immediately closes.

If I try to run WSL from a CMD prompt I get
Please enable the Virtual Machine Platform Windows feature.

I have Windows Hypervisor Platform and Virtual Machine Platform checked in Windows Features.

Is there a way to run both WSL2 and VirtualBox? I had no trouble with WSL1.

**Comment by Biswa96** [comment]
Present: Impossible. Future: Maybe.

**Comment by therealkenc** [comment]
Ref VBox ticket [16801](https://www.virtualbox.org/ticket/16801) and this VBox forum [discussion](https://forums.virtualbox.org/viewtopic.php?f=6&t=90853&start=60).

Biswa96's answer is a good short answer. There is this [post](https://forums.virtualbox.org/viewtopic.php?f=6&t=90853&start=60#p445491) that says "this feature (Hyper-V support) is highly pre-alpha status so far" which at least implies existence "this feature". But that's not the same as "yes" either.

Folks who land here are going to be better off following those VBox threads. That is not meant as a punt. It really really isn't. It's a valid, honest question that clearly "relates" to WSL. But the only _authoritative_ answer will be seeing that cited VBox ticket flip status and some rejoicing in the forum thread.

[FWIW, recent QEMU appears to be okay side-by-side with WSL2 in my (very) limited testing. But that wasn't the question, was it.]

**Comment by CyrilTaylor** [comment]
FYI

[Virtualbox 6 doesn't run with Hyper-V enabled on Windows 10 1903](https://superuser.com/questions/1480214/virtualbox-6-doesnt-run-with-hyper-v-enabled-on-windows-10-1903)

- Step 1: enable `Windows Hypervisor Platform` in Windows Features
- Step 2: enable experimental feature for Virtualbox 6. Oracle VM VirtualBox can now be used on a Windows host where Hyper-V is running. [But this is an experimental feature for now](https://docs.oracle.com/cd/E97728_01/F12470/html/hyperv-integ.html).

```powershell
VBoxManage setextradata global "VBoxInternal/NEM/UseRing0Runloop" 0
```
