### ISSUE TITLE
WSL2 where is docker volume location?

### ISSUE THREAD

**Issue by dryworld** [microsoft/WSL#4176]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.175]
Docker version 18.09.6, build 481bc77

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I installed ubuntu-16.04 at WSL2, and also install docker.
I maked volume by docker command.

## docker volume ls
DRIVER              VOLUME NAME
local               doc_vol

* What's wrong / what should be happening instead:

I looking for the mounted location so I execute command next follow

## docker volume inspect doc_vol
[
    {
        "CreatedAt": "2019-06-18T02:11:35Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/doc_vol/_data",
        "Name": "doc_vol",
        "Options": {},
        "Scope": "local"
    }
]

and then checked the location, It's strange result.

## ls -l /var/lib/docker/volumes/doc_vol/_data
ls: cannot access '/var/lib/docker/volumes/doc_vol/_data': No such file or directory

I checked the '/var/lib/docker/volumes/' only one file exist.

## ls -l /var/lib/docker/volumes/
total 32
-rw------- 1 root root 32768 Jun 18 11:08 metadata.db

where is mounted doc_vol?

**Comment by mscraigloewen** [comment]
You need to be using `sudo ls` to access the volumes in that folder.

```
caloewen@LOE-WSL:/var/lib/docker$ sudo docker run -d --name=nginxtest --mount source=doc_vol,destination=/usr/share/nginx/html nginx:latest
ec7304a051d3f1564dfa91b4a81538caea236d4b30e0092da90d1737058b145d
caloewen@LOE-WSL:/var/lib/docker$ sudo ls ./volumes/doc_vol/_data
50x.html  index.html
caloewen@LOE-WSL:/var/lib/docker$  
```

**Comment by dryworld** [comment]
thanks @mscraigloewen I already root user.
this editor # change to big bold font. :(

anyway previous BIG font has # prompt
also I try as you said 'sudo ls ./volumes/doc_vol/_data' result is 
'ls: cannot access '/var/lib/docker/volumes/doc_vol/_data': No such file or directory'

**Comment by therealkenc** [comment]
There were no takers on the question and no repro to form a WSL actionable. Might get more eyeballs over at [Superuser](https://superuser.com/). If you post be sure to include more specifics; I (personally) couldn't follow the ask on this one.

**Comment by david-sackstein** [comment]
@craigloewen-msft Your answer is incorrect. sudo does not solve the problem because it is not caused by lack of permissions. That path does not exist.

**Comment by craigloewen-msft** [comment]
@david-sackstein you're totally correct!

From my answer, it seems that I wasn't able to repro the error, which means it could be something specific to your setup. I agree with @therealkenc , as of right now it's hard for us to try and repro this so superuser might be your best choice, or posting more repro steps here for us to try. 

Thanks!

**Comment by kerams** [comment]
With Docker Desktop 2.1.7.0 and WSL 2 (Ubuntu), I can see the volumes at /mnt/wsl/docker-desktop-data/data/docker/volumes. Access requires elevated permissions, so you could do `ubuntu.exe config --default-user root` before entering wsl.

**Comment by mahmoud-samy** [comment]
@kerams Thanks.

From linux:  `sudo ls /mnt/wsl/docker-desktop-data/data/docker/volumes`
From windows: `\\wsl$\docker-desktop-data\mnt\wsl\docker-desktop-data\data\docker\volumes`

**Comment by haimat** [comment]
@mahmoud-samy Thanks for this info.
But how can I find out where Docker Desktop saves this data on the Windows host?

**Comment by kerams** [comment]
@haimat, it might be in in a VHDX file in `C:\Users\_user_\AppData\Local\Docker\wsl\data`

**Comment by haimat** [comment]
@kerams Ohh yes, that's it, thanks a lot!
Now, do you also know whether I can `--export` & `--import` both WSL's to another location, or does that confuse Docker Desktop? I know this is not the Docker GitHub repo, but maybe you do know that :-)

**Comment by thejacket** [comment]
Thanks @mahmoud-samy

So what those paths really mean if they're not referring to host machine? 
![image](https://user-images.githubusercontent.com/23661765/78978919-0d8e8980-7b1b-11ea-82d5-17e51b88e724.png)

**Comment by alexandermalfait** [comment]
The key seems to be the "virtual" wsl distro named docker-desktop-data

See https://dev.to/kimcuonthenet/move-docker-desktop-data-distro-out-of-system-drive-4cg2 for solution

**Comment by mahmoud-samy** [comment]
@haimat  @thejacket Sorry for the late reply

AFAIK, when you use WSL integration, two distros will be created for you (docker-desktop & docker-desktop-data)
![image](https://user-images.githubusercontent.com/3718630/88474617-b6c18a00-cf28-11ea-8f27-f685d22788f8.png)

To reach their file system, you need to access it over network
```
\\wsl$\docker-desktop
\\wsl$\docker-desktop-desktop
```

**Comment by dmckee-ebsco** [comment]
This is... not simple. I don't know why it's this hard. I found what I was looking for after dropping into wsl session, and using the `find` command to locate a folder name that I knew...

```bash
find /mnt/host/wsl/docker-desktop-data/data/ -name 'jekyll'
```

**Comment by filippzaripov** [comment]
I found my volume here:
`\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes`

**Comment by ethzero** [comment]
> I found my volume here:
> `\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes`

This took far too much failed Docker documentation trawling and Googling to find this answer. Nice one!

**Comment by sandeeptembare** [comment]
> I found my volume here:
> `\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes`

Thanks, buddy, it helps a lot.

**Comment by gaia** [comment]
very helpful thread!

though i want to know where the docked containers reside from the windows perspective.

it seems to be inside the vhdx at `C:\Users\johndoe\AppData\Local\Packages\distro\LocalState` 

is this correct? if I backup this VHDX from windows I will have a backup of the docker containers?

**Comment by cdalexndr** [comment]
This should be clearly documented, as the advantage of WSL is that you can access volume files directly

**Comment by sebtiz13** [comment]
> I found my volume here:
> `\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes`

Thanks, This took far search to find this.
Just i want truncate log of containers but like said @gaia the mounted directory in WSL are not accessible
`/wsl/docker-desktop-data/version-pack-data` are empty

Somebody have an idea, how can access to this file from WSL2 ?

**Comment by spicylentils** [comment]
Counter intuitive why the path would include 'version-pack-data\community' !!! Why should this path have anything to do with the names associated with these directories???

**Comment by pauloricardomg** [comment]
`/mnt/wsl/docker-desktop-data/version-pack-data` is empty and `docker-desktop-data\version-pack-data\community\docker\volumes` does not exit, so I'm still not able to find where my images are located. WSL2 and docker desktop 2.4.2.0. Does anyone know where to find it?

**Comment by spicylentils** [comment]
Did you try prefixing your path with: 

\\wsl$\

?

**Comment by Kallestofeles** [comment]
> `/mnt/wsl/docker-desktop-data/version-pack-data` is empty and `docker-desktop-data\version-pack-data\community\docker\volumes` does not exist, so I'm still not able to find where my images are located. WSL2 and docker desktop 2.4.2.0. Does anyone know where to find it?

This is strange. I get the exact same behavior and am unable to see the directory when in WSL2 guest. But when accessing the same folder in windows explorer using `\\wsl$\` I see quite a few folders and the volumes are listed there nicely as well. Why is this a thing and we cannot see the folder in WSL guest?

**Comment by truboxl** [comment]
`\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes` is now empty with a `metadata.db` file

`\\wsl$\docker-desktop-data\version-pack-data\community\docker\overlay2` \ randomstring \ `diff` folder
is where you should look for

Not sure how that randomstring is calculated
It's not container ID or image ID
Just brute force your way using search or `find` or other tools

I am not even sure this directory is safe to write files to given the complex structure Docker has laid out...
It should be safe to read from though

I am on `Docker version 19.03.13, build 4484c46d9d` or `Docker Desktop 2.5.0.1`

**Comment by ekam230** [comment]
\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes

**Comment by johnnyoshika** [comment]
From powershell, I can get to my volumes like this:

```
cd \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
```

I can also type this in the Windows Explorer address to get to the same path:
```
\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
```

I can't seem to access that folder from WSL2 though. Anyone know the path? Is it possible?

The reason why I want to access that path from WSL is because I'd like to use bash commands to play with the volumes (e.g. back up, restore, etc).
