### ISSUE TITLE
WSL2: Service Fabric for Linux Installation Errors

### ISSUE THREAD

**Issue by MedAnd** [microsoft/WSL#4178]
* Your Windows build number:  

_Microsoft Windows [Version 10.0.18917.1000]_

* What you're doing and what's happening:  

_Following installation steps as per [Prepare your development environment on Linux](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux)_

* What's wrong / what should be happening instead:

Actual: 

_getfacl: Removing leading '/' from absolute path names
find: ‘/mnt/d/$RECYCLE.BIN/S-1-5-21-3037394892-517346355-113189614-1001’: Permission denied
find: ‘/mnt/d/$RECYCLE.BIN/S-1-5-21-3053762458-1566222040-1484859411-1604’: Permission denied
find: ‘/mnt/d/$RECYCLE.BIN/S-1-5-21-3053762458-1566222040-1484859411-1637’: Permission denied
find: ‘/mnt/d/$RECYCLE.BIN/S-1-5-21-3053762458-1566222040-1484859411-500’: Permission denied
find: ‘/mnt/d/Recovery’: Permission denied
find: ‘/mnt/d/System Volume Information’: Permission denied
find: ‘/mnt/c/$Recycle.Bin/S-1-5-18’: Permission denied
find: ‘/mnt/c/ProgramData/Docker/windowsfilter/1086c288b057704d5e3e7526ca950740c67d688d22aeeb3dd8a8b1ba2700f766/Files/Program Files/WindowsApps’: Permission denied
find: ‘/mnt/c/ProgramData/Docker/windowsfilter/1086c288b057704d5e3e7526ca950740c67d688d22aeeb3dd8a8b1ba2700f766/Files/ProgramData/Microsoft/Crypto/PCPKSP/WindowsAIK’: Permission denied
find: ‘/mnt/c/ProgramData/Docker/windowsfilter/1086c288b057704d5e3e7526ca950740c67d688d22aeeb3dd8a8b1ba2700f766/Files/ProgramData/Microsoft/Diagnosis’: Permission denied_

Failed to connect to bus: No such file or directory
/var/lib/dpkg/info/servicefabric.postinst: line 202: echo Error: Failed to restart atop.service: command not found
dpkg: error processing package servicefabric (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of servicefabricsdkcommon:
 servicefabricsdkcommon depends on servicefabric (>= 6.4.625.1); however:
  Package servicefabric is not configured yet.

dpkg: error processing package servicefabricsdkcommon (--configure):
 dependency problems - leaving unconfigured
Setting up libbabeltrace1:amd64 (1.3.2-1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
Setting up libbabeltrace-ctf1:amd64 (1.3.2-1) ...
Setting up babeltrace (1.3.2-1) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.21) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for dbus (1.10.6-1ubuntu3.3) ...
Errors were encountered while processing:
 servicefabric
 servicefabricsdkcommon
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error@67: Failed to install Service Fabric SDK

Expected:

Assume the windows file system should not be iterated?

**Comment by onomatopellan** [comment]
On real Linux there is no /mnt/* windows folders.
With `mount` you can see how many windows drives you have mounted. You can unmount them with `sudo umount /mnt/c`.

**Comment by MedAnd** [comment]
Before downloading and setting up the Ubunti 16.04 VM via the MS Marketplace I ran:

`wsl --set-default-version 2`

Some questions:

- Can I assume this means my Ubuntu VM is running on WSL2?
- Does WSL2 auto mount windows drives within the Ubuntu VM, is this documented etc?
- Is this an issue with how the Service Fabric installation scripts work or with WSL2?

**Comment by onomatopellan** [comment]
1.- On cmd run `wsl -l -v` to see the version of running WSL.
2.- Yes, but it can be changed with [wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings) 
3.- That's more a question for the Azure devs.

**Comment by MedAnd** [comment]
Right, so WSL2 uses the same wsl.conf as WS1 and windows drives are auto mounted... thinking this would be great info to add to [WSL 2 FAQ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)

**Comment by benhillis** [comment]
@MedAnd - Agreed, @mscraigloewen can you add this to the FAQ?

**Comment by benhillis** [comment]
@MedAnd - It's unclear to me why service fabric is falling over, is it because you are getting permission denied errors even though you are running as root?

**Comment by MedAnd** [comment]
@benhillis - I've updated the issue with more logs given the process has finally completed. I notice the following:

_Failed to connect to bus: No such file or directory
/var/lib/dpkg/info/servicefabric.postinst: line 202: echo Error: Failed to restart atop.service: command not found_

Wondering if I should also log this with the Service Fabric team?

**Comment by mscraigloewen** [comment]
@MedAnd @benhillis I've added the info about wsl.conf to the [WSL 2 FAQ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-use-wslconf-in-wsl-2) docs.

**Comment by therealkenc** [comment]
From the attached shell log:

> Failed to connect to bus: No such file or directory

That's because the bus is not there dupe #376

> /var/lib/dpkg/info/servicefabric.postinst: line 202: echo Error: Failed to restart atop.service: command not found

That line looks like [this](https://github.com/Microsoft/service-fabric/blob/master/src/prod/linuxsetup/crossplatsetup/runtime/postinst#L200), also #376,

> PS. Wondering if I should also log this with the Service Fabric team?

Ask them how to make it run on Alpine/Gentoo/Void Linux. It will make a better formed question, and you will get a short and less confused answer. LZ is #994.

**Comment by MedAnd** [comment]
@benhillis @mscraigloewen - may I recommend the FAQ is updated to clearly spell out that WSL2 does not run systemd (or anything that systemd usually starts, like dbus-daemon)

@therealkenc - would also be good to clarify if this will never be supported or it's on your roadmap.
