### ISSUE TITLE
WSL2: clock drift on suspend/resume

### ISSUE THREAD

**Issue by simonferquel** [microsoft/WSL#4179]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18917.1000]
* What you're doing and what's happening:  
Yesterday evening, I closed my laptop lid with an active WSL2 terminal. I don't know if it went to hybernation or just on suspend mode, but this morning, I got a very big clock drift between WSL and my host: 
from WSL:
```
simon@simonxps:~$ date
Mon Jun 17 19:06:58 CEST 2019
```
from Powershell:
```
C:\Users\simon> get-date

Tuesday, June 18, 2019 9:59:33 AM
```

It does not recover by itself

* What's wrong / what should be happening instead:

Clock drift can be very nasty for running distributed systems. It is also particularly annoying for things relying on file modification timestamp. WSL should keep clocks in sync.

**Comment by simonferquel** [comment]
After wsl --shutdown, clock drift expectedly disappears

**Comment by Biswa96** [comment]
Seems to be similar with #4149.

**Comment by therealkenc** [comment]
Landing zone #4114
