### ISSUE TITLE
wsl --list in powershell script, many unexpected space characters

### ISSUE THREAD

**Issue by silverqx** [microsoft/WSL#4180]
I need to `wsl -l` in my dotfiles, but it doesn't behave correctly, when I use this command with **pipe** or **redirection**, output looks like this:
```
W i n d o w s   S u b s y s t e m   f o r   L i n u x   D i s t r i b u t i o n s :


 U b u n t u   ( D e f a u l t )


 L e g a c y


 U b u n t u - t m p



```

I'm talking about these commands:
`wsl -l | echo`
`wsl -l | sls ubuntu`
`wsl -l > file.txt`

Does anybody have any idea how to workaround this problem?

**Comment by therealkenc** [comment]
> but it doesn't behave correctly

Are you sure? Does your script parse the output if the string "(`Default`)" or an `--import` distribution name that is Kanji or Chinese text? 

It's correct, just, well, unfortunate. You can probably get to where you want to be from Linux with:

```
$ wsl.exe -l | iconv -c -f utf16 -t utf8
```

From Powershell, I'm not qualified to repeat the Google hits.

**Comment by silverqx** [comment]
I can leave without this `wsl -l` check in my script for now, but would be much helpful to mark this as a bug for later investigation, if not we can close this issue.
@therealkenc thank you for advice.

**Comment by therealkenc** [comment]
It is not a bug. It is powershell's by-design [behavior](https://stackoverflow.com/questions/19388342/why-does-powershell-file-concatenation-convert-utf8-to-utf16). And unrelated to `wsl.exe`, which does not output ASCII because it's output is internationalized.

**Comment by riverar** [comment]
As mentioned in #4607, it is unexpected that WSL outputs multi-byte codepoints. I suspect this bug was closed too hastily. It's unclear if this even went through proper triage; it doesn't appear @therealkenc works at Microsoft...

**Comment by silverqx** [comment]
It doesn't work correctly in any console, powershell, cmd or conemu, the same problem.
