### ISSUE TITLE
[WSL 2] wsl --set-version Ubuntu 2 failed

### ISSUE THREAD

**Issue by otarim** [microsoft/WSL#4182]
![image](https://user-images.githubusercontent.com/2024477/59695910-98656700-921d-11e9-901b-93978d949382.png)
![image](https://user-images.githubusercontent.com/2024477/59695233-79b2a080-921c-11e9-821e-9fd46cb4471b.png)
![image](https://user-images.githubusercontent.com/2024477/59695743-4b819080-921d-11e9-8678-2d7c97477b15.png)

When execute `wsl --set-version Ubuntu 2` the console prompt `Please enable the Virtual Machine Platform Windows feature. `

I have enable the Virtual Machine Platform Windows feature using Enable-WindowsOptionalFeature command. And from Windows Features Pannel, the Virtual Machine Platform option is checked. I try to resolve it by Google but Seems no one had encountered this problem from result.

Thanks for your answer :-)

**Comment by benhillis** [comment]
Please ensure that virtualization is enabled in your BIOS.

**Comment by otarim** [comment]
@benhillis It works for me👍
