### ISSUE TITLE
Error on pipe reading when launch win32 console app with wsl ubuntu

### ISSUE THREAD

**Issue by gvollant** [microsoft/WSL#4184]
[input_bug5.txt](https://github.com/microsoft/WSL/files/3302267/input_bug5.txt)
[bug_wsl.zip](https://github.com/microsoft/WSL/files/3302272/bug_wsl.zip)

I've a specific text file (less than 256 KB, each line take less than 300 chars, only TAB, CR/LF and ascii char between 0x20-0x7f) named input_bug5.txt.

I build console win32 app below with VS2019 (latest sdk) which just copy the file.
and I run 
myapp.exe <  input_bug5.txt
`
with wsl the copied file had 2 lines merged!

#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

int main(int argc, char** argv)
{
    FILE* fin = stdin;
    FILE* fout = fopen("resbug3.txt", "wb");
    
#define SIZE_BUFFER (524288)
    int nblines = 0;
    int nbbytes=0;
    char* buffer = (char*)calloc(SIZE_BUFFER + 1, 1);
    while (!feof(fin)) {
        if (fgets(buffer, SIZE_BUFFER, fin) == NULL) break;
        fwrite(buffer, 1, strlen(buffer), fout);
        nblines++; nbbytes+=(int)strlen(buffer);
    }
    fclose(fout);
    free(buffer);
    fprintf(stderr, "line=%d, nb bytes=%d.\n", nblines,nbbytes);
    return 0;
}`

**Comment by htristra** [comment]
I have exactly the same problem

**Comment by gvollant** [comment]
bug still here with windows 10 20H2, both Ubuntu 20.04 and debian 10 WSL1

**Comment by gvollant** [comment]
bug still here in 2024 with windows 11 ans wsl debian 11
