### ISSUE TITLE
[Suggestion] KDE Plasma and other Linux Desktop Environments on Windows 10 via WSL

### ISSUE THREAD

**Issue by setsunati** [microsoft/WSL#4186]
I want to install KDE Plasma Desktop Environment via WSL so i can replace the entire Windows 10 User Interface with KDE Plasma.

It would be awesome if all Linux Desktop Environments work correctly with WSL.

**Comment by setsunati** [comment]
I want to replace the entire Windows desktop with a Linux desktop KDE Plasma.

**Comment by benhillis** [comment]
Thanks for the suggestion, we do not currently have any plans to do this.
