### ISSUE TITLE
wsl -h typo for setdefault option

### ISSUE THREAD

**Issue by inphobia** [microsoft/WSL#4187]
* Your Windows build number:
  * Microsoft Windows [Version 10.0.18362.175]

* What you're doing and what's happening:
  * start `cmd.exe` or whatever cli.
  * run `wsl -h`

* What's wrong / what should be happening instead:
  * typo for `-setdefault` option
    * ```
      -setdefault, -s <DistributionName>
        Sets the distribution as the default.
      ```
  * only has 1 dash
  * should have 2 dashes for long options: `--setdefault`
  * single dash version also not accepted when used:
    * ```
      wsl -setdefault Debian
      Invalid command line option: -setdefault
      ```
  * double dash version (`--setdefault`) works:
    * `wsl --setdefault openSUSE-Leap-15`
  * single char, single dash version (`-s`) works:
    * `wsl -s Debian`

* Strace of the failing command, if applicable:
  * it's just a typo, not an actual wsl regression.

* For WSL launch issues, please collect detailed logs
  * not a big deal, it's only a typo.

**Comment by benhillis** [comment]
Thanks, I've resolved this in recent insider builds.

**Comment by Biswa96** [comment]
One confusion. Build 18917, both `--set-default` and `--setdefault` works but help says only `--set-default` or `-s`.

**Comment by benhillis** [comment]
@Biswa96 - Yep, I left --setdefault but removed it from usage, so it wouldn't break anybody.

**Comment by inphobia** [comment]
> Thanks, I've resolved this in recent insider builds.

coolness, fast response :)

can be closed then i guess?

**Comment by benhillis** [comment]
Sure! Thanks for filing the issue.

**Comment by inphobia** [comment]
fixed in insider it seems, good enuf for me.
