### ISSUE TITLE
WSL 2 umask for /home folder accessed from Windows

### ISSUE THREAD

**Issue by leninalive** [microsoft/WSL#4188]
When creating folders or files on WSL2's Linux partition (/home etc.) from Windows Explorer folders are always created with 777 permissions, and files with 666 - looks like umask 0 in effect. I can't find way to change system-wide umask for folders accessed from Windows - are there one?

**Comment by therealkenc** [comment]
> are there one?

No I don't think so. Not yet anyway. A `wsl.conf` addition with `[9p]` section with a `umask` parameter is a reasonable ask. [If one assumes the WSL default user is the only WSL user per the current model.]

Possible work-around, while the MSFT's house brand 9p client and server death marches to feature parity with [Samba](https://www.samba.org/), is to run Samba (set the `create umask` in `smb.conf`). Samba works as advertised in WSL2 (ref #764). 

The other way to go is follow the guidance given in the WSL2 launch [blog post](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) and do all ext4 (aka `/home`) filesystem operations from inside WSL. This is how [VS Code Remote](https://code.visualstudio.com/blogs/2019/05/02/remote-development) works. However you'll have to use the "[Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)" variety (contrast ["Remote - WSL"](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) variety) so `sshd` inside WSL can set the `umask` correctly.

**Comment by benhillis** [comment]
@therealkenc - Agreed, some wsl.conf settings for the 9p server likely make sense.  @SvenGroot - is this something you'd be open to us adding?

**Comment by therealkenc** [comment]
Unilateral default of `0022` would make around  93.7% of users happy, overridable in `wsl.conf` so much the better. Ditto tangential #352.

**Comment by benhillis** [comment]
I've changed the default umask of the 9p server to 022, with an override available in /etc/wsl.conf:

```
[filesystem]
umask = 022
```

Fix will be in an upcoming Insider build.

**Comment by xbb** [comment]
> 
> I've changed the default umask of the 9p server to 022, with an override available in /etc/wsl.conf:
>

Doesn't seem to work with build 18362.295
Is the [filesystem] section available only in Insider builds?

**Comment by xeres** [comment]
Is Remote SSH the only workaround in WSL 1 + Remote WSL?
