### ISSUE TITLE
wsl2 cause vmmem process use 90% memory even after wsl2 ubuntu closed

### ISSUE THREAD

**Issue by qclzdh** [microsoft/WSL#4191]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
_18917_

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
_I build Android source code, in the whole building process, vmmem use 90% memory, and after building successfully, i closed wsl2 ubuntu, but vmmem process still use 90% memory._

* What's wrong / what should be happening instead:
_vmmem process use 90% memory_

**Comment by therealkenc** [comment]
#4166

`wsl.exe --shutdown`

**Comment by wmsj100** [comment]
wsl.exe --shutdown to shutdown wsl
wsl restart wsl 
than Vmmem use memory normal
