### ISSUE TITLE
calling explorer.exe stopped working

### ISSUE THREAD

**Issue by tlmii** [microsoft/WSL#4196]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18917.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.): 
In Ubuntu shell, just type explorer.exe and press enter. Same thing happens with "explorer.exe ."

* What's wrong / what should be happening instead:
I get the error "/mnt/c/WINDOWS/explorer.exe: Invalid argument" instead of the expected opening of Explorer in Windows. It also indents the prompt on the next line aligned to the end of the error message. This used to work the last couple of days.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
I don't think this is applicable.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
Not applicable

**Comment by tlmii** [comment]
Well, I figured out the cause, sort of.
I had another Explorer window open with a modal error message popped up saying that \\wsl$\[rest of path] was not available anymore. I guess that happened at some point when my laptop went to sleep? Not positive.
Regardless, I'm unblocked, but that's a not-so-helpful error message.

**Comment by therealkenc** [comment]
> but that's a not-so-helpful error message

What would you propose the [`execve()`](http://man7.org/linux/man-pages/man2/execve.2.html)? [This is a rhetorical not a real question.]

Happy to hear you are unblocked. 👍
