### ISSUE TITLE
Issues while configuring Visual Studio Code for WSL

### ISSUE THREAD

**Issue by tanay-jha** [microsoft/WSL#4198]
<b>Windows Build Number : Microsoft Windows [Version 10.0.18362.175]</b>

I'm trying to configure Visual Studio Code to use WSL, as per the steps detailed by Microsoft here at https://code.visualstudio.com/docs/remote/wsl , however every time, I input <code>code .</code>, the following issue occurs, 

<p>

```
tanayjha@LAPTOP-4NQ98UA8:~$ cd /mnt/d/Development/CProgramming/
tanayjha@LAPTOP-4NQ98UA8:/mnt/d/Development/CProgramming$ ls
'Hello, World'
tanayjha@LAPTOP-4NQ98UA8:/mnt/d/Development/CProgramming$ cd Hello\,\ World/
tanayjha@LAPTOP-4NQ98UA8:/mnt/d/Development/CProgramming/Hello, World$ code .
Updating VS Code Server to version c7d83e57cd18f18026a8162d042843bda1bcf21f
Removing previous installation...
Downloading:     Failed
Redirecting output to ‘wget-log’.
ERROR: Failed to download https://update.code.visualstudio.com/commit:c7d83e57cd18f18026a8162d042843bda1bcf21f/server-linux-x64/stable to /home/tanayjha/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f-1560983444.tar.gz
tanayjha@LAPTOP-4NQ98UA8:/mnt/d/Development/CProgramming/Hello, World$
```

</p>

Every time the setup gets stuck here, no matter if I use <code>Visual Studio Code or Visual Studio Code Insiders</code> with the  <code>Remote Development Extension</code>. I've tried using both wired and wireless internet connections, and yet it fails. Other commands such as <code>sudo apt-get update</code> work just fine.

Here's a screenshot just in case,
![Ubuntu Snip](https://user-images.githubusercontent.com/33920656/59806329-9ed50b00-9311-11e9-923c-24b2bb633313.jpg)

Here's the log from <code>wget-log</code> file,

```
 cat wget-log
--2019-06-20 04:00:45--  https://update.code.visualstudio.com/commit:c7d83e57cd18f18026a8162d042843bda1bcf21f/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
Unable to establish SSL connection.
```

**Comment by therealkenc** [comment]
What is the significance of the `cd Hello\,\ World/` in your repro (it can't have been for giggles). Does VS Code Remote WSL operate correctly from `/home/foo`?

**Comment by tanay-jha** [comment]
> What is the significance of the "`cd Hello\,\ World/`" in your repro (it can't have been for giggles). Does VS Code Remote WSL operate correctly from `/home/foo`?

@therealkenc 
I was just trying to navigate inside the folder, and then open VS Code. Basically was trying to build a Hello, World app using VSCode, and the terminal powers of WSL. 

No, WSL doesn't operate correctly even from ``home/foo`` . Ends up returning the same error

**Comment by therealkenc** [comment]
Okay, appreciate the follow-up. Since `wget` is apparently working for you in general, and the VS Code spawned `wget` is not, you _might_ get better guesses [over there](https://github.com/microsoft/vscode-remote-release). That said, it isn't going to be a VS Code Remote thing proper either, since they'll tell you they aren't doing anything "special" with `wget`. With luck we'll get some me2s and learn some more about what is causing the diverge on your rig.

**Comment by therealkenc** [comment]
Wait... I am thinking the [resolver](http://man7.org/linux/man-pages/man3/resolver.3.html), somehow. Your Internet connection is fine, but your DNS is not. Try sticking go-to `8.8.8.8` in `/etc/resolve.conf` on a lark. Noting that we're grasping here. Like:
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 8.8.8.8
```

**Comment by tanay-jha** [comment]
> Wait... I am thinking the [resolver](http://man7.org/linux/man-pages/man3/resolver.3.html), somehow. Your Internet connection is fine, but your DNS is not. Try sticking go-to `8.8.8.8` in `/etc/resolve.conf` on a lark. Noting that we're grasping here. Like:
> 
> ```
> # This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
> # [network]
> # generateResolvConf = false
> nameserver 8.8.8.8
> ```

I edited the resolve.conf file using vim, and set the nameserver value to ``8.8.8.8``, however the problem continues. The download fails by stating ``failed to establish a SSL connection``

**Comment by therealkenc** [comment]
> however the problem continues

Well it was worth a try..... Thanks.

**Comment by tanay-jha** [comment]
@therealkenc it seems the problem was due to my antivirus, Kaspersky's network settings, which have a fix as stated here https://superuser.com/questions/1401889/complete-ssl-ubuntu-failure-on-windows-subsystem
