### ISSUE TITLE
PPP not available

### ISSUE THREAD

**Issue by yisonPylkita** [microsoft/WSL#4201]
Windows version: Microsoft Windows [Version 10.0.18917.1000]

I was trying to connect to a VPN and my client (`openfortivpn`) requires `ppp`.
After running `pppd` I got this error

```bash
➜  pppd
Couldn't open the /dev/ppp device: No such device or address
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module ppp_generic not found in directory /lib/modules/4.19.43-microsoft-standard                                                                                                                                                                                        pppd: Please load the ppp_generic kernel module.
```

**Comment by onomatopellan** [comment]
Yes, another thing the WSL2 linux kernel lacks right now. If you feel adventurous, in #4203 you have an example of how to reconfigure, compile and replace the kernel yourself.

**Comment by benhillis** [comment]
Can you describe your scenario? Does connecting to the the VPN via Windows work?

**Comment by therealkenc** [comment]
Some wrongthinking VPNs use PPTP, sure, and there will always be Windows solutions for those. [There are Windows solutions for a lot of things...] But `/dev/ppp` and `pppd` has other use cases, like PPP over PTY. Problem with the long tail of the Linux kernel modules is there is a use case for all of them.

Not saying it should be enabled. Not saying it shouldn't. Saying it is a long long tail.

**Comment by yisonPylkita** [comment]
@benhillis I tried connect to a VPN in Windows a few time in them past, but every time I failed. (`fortinet client` doesn't seem to support stuff like `realm`). So I used a VM with a Linux and I could connect without problems.

Yet working on Windows and using Linux VM at the same time is rather troublesome so I tried to switch to Windows entirely and use WSL whenever I need a CLI. This support for `PPP` is the only thing that holds me back from doing so.

**Comment by uishon** [comment]
Same for me. Tried working with `openfortivpn` on wsl2 and got an error that pppd is not found. So, I went ahead, installed ppp (`apt-get install ppp`) and retried `openfortivpn`  but got a read/write error. Ran it again in verbose mode to find the root cause and got this:

      ...
      DEBUG:  pppd_write thread
      ERROR:  read: Input/output error
      INFO:   Cancelling threads...
      DEBUG:  Waiting for pppd to exit...
      DEBUG:  waitpid: pppd exit status code 4
      ...

whereas exit code 4 means (from the manpage)

      4      The  kernel  does  not  support  PPP,  for  example, the PPP kernel driver is not included or cannot be
              loaded. 

Any plans to include ppp in wsl2?

**Comment by benhillis** [comment]
Thanks for the information, I will get /dev/ppp added to the kernel config.

**Comment by uishon** [comment]
Great. Thanks!
Please update when done so I can retry.

Uri.

**Comment by dylman123** [comment]
Hi, any progress on this issue?

**Comment by therealkenc** [comment]
Yep, [here](https://github.com/microsoft/WSL2-Linux-Kernel/commit/c21a3bdbc0fbac1964df18b1ca07f67630782bb7#diff-b9b62ad49605a89f14bdab86df03f1c4L1521). `/dev/ppp` is live on 18950, at least.

Although, that `CONFIG_PPPOE is not set` looks problematic, for [some scenarios](https://www.roaringpenguin.com/products/pppoe), anyway. FWIW this is how Ubuntu's native kernel ships.
```
$ grep PPP config-5.0.0-20-generic 
CONFIG_PPP=y
CONFIG_PPP_BSDCOMP=m
CONFIG_PPP_DEFLATE=m
CONFIG_PPP_FILTER=y
CONFIG_PPP_MPPE=m
CONFIG_PPP_MULTILINK=y
CONFIG_PPPOATM=m
CONFIG_PPPOE=m
CONFIG_PPPOL2TP=m
CONFIG_PPP_ASYNC=m
CONFIG_PPP_SYNC_TTY=m
```

**Comment by uishon** [comment]
Just tried it out again - build 18956.
Seems like ppp is now supported by the kernel (thanks!) but still - `openfortivpn` is not working. Here is the `openfortivpn` log with the errors I'm getting now:

    INFO:   Connected to gateway.
    INFO:   Authenticated.
    INFO:   Remote gateway has allocated a VPN.
    ERROR:  read: Input/output error
    INFO:   Cancelling threads...
    ERROR:  pppd: Has detached, or otherwise the connection was successfully established and terminated at the peer's request.
    INFO:   Terminated pppd.
    INFO:   Closed connection to gateway.
    INFO:   Logged out.

When checking the `pppd` log, I see the following error:

    Couldn't set tty to PPP discipline: Invalid argument

Any idea?

**Comment by Biswa96** [comment]
Any strace output please?

**Comment by Biswa96** [comment]
I found that `CONFIG_PPP_SYNC_TTY` is not set in WSL/Linux kernel config.

**Comment by uishon** [comment]
Thanks. If it helps, here is the `strace` output - [strace.log](https://github.com/microsoft/WSL/files/3490447/strace.log).

**Comment by therealkenc** [comment]
> I found that CONFIG_PPP_SYNC_TTY is not set in WSL/Linux kernel config.

Correct, I [linked](https://github.com/microsoft/WSL2-Linux-Kernel/commit/c21a3bdbc0fbac1964df18b1ca07f67630782bb7#diff-b9b62ad49605a89f14bdab86df03f1c4L1521) that in my previous post. None of the suboptions are set, and needless to say, anything that depends on the suboption being available (here, arbitrarily, `openfortivpn` and `CONFIG_PPP_SYNC_TTY`) isn't going to work. 

All of them are available, either as a module or `=y` in native Ubuntu.

```
# CONFIG_PPP is not set
CONFIG_PPP=y
# CONFIG_PPP_BSDCOMP is not set
# CONFIG_PPP_DEFLATE is not set
# CONFIG_PPP_FILTER is not set
# CONFIG_PPP_MPPE is not set
# CONFIG_PPP_MULTILINK is not set
# CONFIG_PPPOE is not set
# CONFIG_PPP_ASYNC is not set
# CONFIG_PPP_SYNC_TTY is not set
```

**Comment by Biswa96** [comment]
FYI, those options are now enabled in WSL2-Linux-Kernel repository in linux-msft-wsl-4.19.y branch, see the commit on Aug 17, 2019.

**Comment by uishon** [comment]
Just checked it with insiders build 18995. `openfortivpn` works 👍. Thanks.

**Comment by therealkenc** [comment]
Great thanks for the confirm.

**Comment by francovp** [comment]
I'm in build 18999 and it doesn't work. I'm still receiving 
`pppd: The kernel does not support PPP`

**Comment by uishon** [comment]
Strange. It does work for me. The only difference I can think of is that
it's an upgraded build, not a fresh install and I've apt-get installed ppp
previously. Not sure why that would make a difference though.

**Comment by francovp** [comment]
Its working now, it was because I was using WSL1. I switch to WSL2 and now is working fine :)

**Comment by uishon** [comment]
:-)
