### ISSUE TITLE
systemd still not working on wsl2

### ISSUE THREAD

**Issue by elswerky** [microsoft/WSL#4202]
why still systemd services still not working on wsl2 ?? 

i am using arch on wsl2 
and ubuntu 18.04 on wsl2 

can you help plz to make systemd services works on wsl2 ?

**Comment by mscraigloewen** [comment]
A WSL user has posted how to set up systemd inside of WSL 2. You can view [their repo here](https://github.com/arkane-systems/genie).

**Comment by therealkenc** [comment]
#994

**Comment by datdinhquoc** [comment]
> A WSL user has posted how to set up systemd inside of WSL 2. You can view [their repo here](https://github.com/arkane-systems/genie).

sadly the guide is only for debian-based wsl :(

**Comment by nezorflame** [comment]
@datdinhquoc actually now it also supports Arch with AUR packages: https://github.com/arkane-systems/genie#arch

**Comment by germainlefebvre4** [comment]
> > A WSL user has posted how to set up systemd inside of WSL 2. You can view [their repo here](https://github.com/arkane-systems/genie).
> 
> sadly the guide is only for debian-based wsl :(

There's an Ubuntu section that is working for me on Ubuntu 18.04 and apparently in 19.10 but not in 20.04.

**Comment by markusmo** [comment]
> > > A WSL user has posted how to set up systemd inside of WSL 2. You can view [their repo here](https://github.com/arkane-systems/genie).
> > 
> > 
> > sadly the guide is only for debian-based wsl :(
> 
> There's an Ubuntu section that is working for me on Ubuntu 18.04 and apparently in 19.10 but not in 20.04.
> 
> Another trick is to fake the bash binary : https://github.com/shayne/wsl2-hacks

This repo broke my 20.04 installation of Ubuntu on WSL2

**Comment by lildonpancho** [comment]
This article shows how to get systemd up and running on WSL2 which inturn will allow you to access Snaps. I found it while I was trying to figure out how to get Microk8s to work on WSL2 as Hyper-V blocks me from being able to go my normal route which was using Multipass. I was THIS close to uninstalling WSL2. Problem solved and I am off to the races. Hope this helps.

https://wsl.dev/wsl2-microk8s/

**Comment by lopugit** [comment]
> This article shows how to get systemd up and running on WSL2 which in turn will allow you to access Snaps. I found it while I was trying to figure out how to get Microk8s to work on WSL2 as Hyper-V blocks me from being able to go my normal route which was using Multipass. I was THIS close to uninstalling WSL2. Problem solved and I am off to the races. Hope this helps.
> 
> https://wsl.dev/wsl2-microk8s/

I've gotten systemd working via this, although he puts NOPASSWD: ALL in his %sudo group /etc/sudoers file which I would never do so it just means you need to enter sudo password everytime you start a session, which is a bit annoying but safer than having NOPASSWD...?!?!? Is there a way to do it by having a separate user to launch systemd with nopasswd just for that extra user and then enter a normal session for your default user?
