### ISSUE TITLE
[WSL2] K3s and Kubernetes support

### ISSUE THREAD

**Issue by ibuildthecloud** [microsoft/WSL#4203]
k3s is simple, lightweight distribution of Kubernetes.  To run k3s on WSL2 the following kernel settings are missing.  These will be needed for most any Kubernetes setup, so this is not specific to k3s.

CONFIG_BRIDGE_NETFILTER=y
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
CONFIG_NETFILTER_XT_MATCH_MULTIPORT=y
CONFIG_NETFILTER_XT_MATCH_OWNER=y
CONFIG_NETFILTER_XT_MATCH_PHYSDEV=y
CONFIG_VXLAN=y
CONFIG_GENEVE=y

I was able to get k3s and rio (which uses istio, knative, prometheus, grafana, kiali, and lot of other things) with these steps. https://gist.github.com/ibuildthecloud/1b7d6940552ada6d37f54c71a89f7d00

While I only included the CONFIG_NETFILTER_XT_MATCH_* parameters Kubernetes specifically needs, it might be worth it to just include all the default xt_match options.  It is going to continually pop up that people want different iptables modules.

**Comment by benhillis** [comment]
Thanks for posting, I've kicked off a new kernel build with those features enabled.

**Comment by onomatopellan** [comment]
Do notice after replacing the original kernel wsl.exe won't convert installs between WSL1 and WSL2 anymore. It freezes and a reboot is needed in order to run WSL2 again.

Using the original kernel file conversions work again.

@benhillis Is this expected? Why is the kernel included in WSL2 50Mb in size? Is the kernel truly just a renamed bzImage file?

**Comment by Biswa96** [comment]
Did you compile it from WSL2 Linux kernel source code or from kernel.org?

**Comment by Biswa96** [comment]
Did you compile it from WSL2 Linux kernel source code or from kernel.org? @simonferquel did some testing with home-made ones.

**Comment by Biswa96** [comment]
Did you compile it from WSL2 Linux kernel source code or from kernel.org? @simonferquel did some testing with home-made ones.

> Why is the kernel included in WSL2 50Mb in size?

Probable answer:

```console
root@A:~# cd /mnt/c/Windows/System32/lxss/tools/
root@A:/mnt/c/Windows/System32/lxss/tools# file kernel
kernel: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=1cdcda82d3a405575308724a5e303c5738893915, not stripped
```

**Comment by onomatopellan** [comment]
@Biswa96 I downloaded it from the WSL2 docs [link](https://thirdpartysource.microsoft.com/download/Windows%20Subsystem%20for%20Linux%20v2/May%202019/WSLv2-Linux-Kernel-master.zip).

The WSL2 kernel is 50 Mb but real size in disk is 14Mb so maybe is uncompressed?

**Comment by Biswa96** [comment]
@onomatopellan Same issue. I compiled the Linux kernel, everything works but the WSL1 <--> WSL2 conversion does not. The cause may be static linking. README does not provide how to do it.

**Comment by Biswa96** [comment]
@onomatopellan Try with the [WSL2-Linux-Kernel](https://github.com/microsoft/WSL2-Linux-Kernel). It works.

**Comment by benhillis** [comment]
@biswa96 - does converting work as well?

**Comment by Biswa96** [comment]
Yes.

**Comment by onomatopellan** [comment]
Indeed replacing kernel with bzImage (7Mb) from git and now conversions and new installs work. :)

**Comment by benc-uk** [comment]
Is this coming to the default "stock" WSL2 kernel?
I'd love to run k3s but I **really** don't fancy building my own kernel :)

**Comment by Biswa96** [comment]
The configurations are added in the wsl2 Linux kernel repository. If you don't want to build the kernel wait for next 2 or 3 Windows 10 insider builds.

**Comment by benc-uk** [comment]
Thanks, I can wait for a build or three

**Comment by daniel-kun** [comment]
Any update on this?

**Comment by Biswa96** [comment]
It's in repository. You can check the kernel flags from `/proc/config.gz` file.

**Comment by markfarnan** [comment]
Just looked through /pro/config.gz on my install. 
Looks like all the requested kernel settings are enabled in  WSL 2 in Build 18995

**Comment by benc-uk** [comment]
Yes K3s seems to work in 18995 ! 😎
This is in WSL2, Kernel: 4.19.72-microsoft-standard
```
 $ sudo ./k3s kubectl get po --all-namespaces                                                                           
NAMESPACE     NAME                         READY   STATUS      RESTARTS   AGE
kube-system   coredns-66f496764-nksvz      1/1     Running     0          39s
kube-system   helm-install-traefik-kx7cx   0/1     Completed   0          39s
kube-system   svclb-traefik-tskxx          3/3     Running     0          16s
kube-system   traefik-d869575c8-xqccw      0/1     Running     0          16s
 $ sudo ./k3s kubectl get nodes                                                                                         
NAME        STATUS   ROLES    AGE   VERSION
becolemsb   Ready    master   59s   v1.15.4-k3s.1
```

**Comment by GaboFDC** [comment]
> Yes K3s seems to work in 18995 ! 😎

How did you manage to install it? Latest script looks for systems, so I cant install k3s in wsl

**Comment by onomatopellan** [comment]
@GaboFDC for systemd see https://github.com/arkane-systems/genie
