### ISSUE TITLE
WSL spawns wsl.exe continuously for no reason

### ISSUE THREAD

**Issue by TheGoddessInari** [microsoft/WSL#4211]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  10.0.18362.175

* What you're doing and what's happening:  I use the system normally (typically not interacting with WSL much if at all), and wsl.exe spawns copies of itself repeatedly with a command line like `dpkg-query -S /init`.

* What's wrong / what should be happening instead: WSL repeatedly spawns itself (as in, many copies of wsl.exe) that then exit, then respawn. This badly thrashes the HDD. / WSL should behave normally!

* Strace of the failing command, if applicable: 

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

Commands **are not** hanging, and respond normally, except for the bizarre WSL thrashing.
This is on a machine with Device Guard/Credential Guard running, but no HVCI.

It was working perfectly on 10.0.18362.145, so this is a brand new regression looks like.

There are **no** scheduled tasks relating to WSL that I can find, so it's unclear why it's trying to run `dpkg-query` to begin with.

This runs away forever until WSL is uninstalled. Stopping LxssManager is **not** enough as it simply resetarts and **cannot** be disabled. This **will** happen on a boot even when not trying to interact with WSL at all.

Since it badly thrashes the boot HDD (~1mb/s but 100% active usage), it does make the machine extremely difficult to use and unresponsive.

**Comment by benhillis** [comment]
Definitely going to need more information here.  Can you glean any information about why these processes are being created by looking at process monitor?

**Comment by TheGoddessInari** [comment]
They just spawn continuously out of the LxssManager service EXE independently of any other activity on the system, constantly die, and constantly respawn.

Eg, I've never seen PIDs above 500,000 until this started happening.

**Comment by benhillis** [comment]
@TheGoddessInari - The service doesn't launch wsl.exe.  In fact, the service is trigger-started by wsl.exe.  Something else on your machine is launching the processes.

**Comment by TheGoddessInari** [comment]
They all spawned under the service in the process tree, same as `init`, etc.

**Comment by Biswa96** [comment]
Open Task Manager or [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) or [Process Hacker](https://github.com/processhacker/processhacker) and provide a screenshot of the process tree.

**Comment by TheGoddessInari** [comment]
Before uninstalling, then reinstalling the WSL feature, it had `wsl.exe` in place of init/dpkg, as I said, with command lines passed to it like `dpkg-query -S /init`. And Administrator instead of local user for username. This screenshot's taken after ~30 seconds of it respawning indefinitely and I had to uninstall the feature again for it to start behaving again, as before.

Because it's treating it as lxss processes again instead of `wsl.exe`, it doesn't show any meaningful details anymore, but previously the command line passed to it was as mentioned, as recorded by Process Hacker.

That svchost.exe is LxssManager, `C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s LxssManager` running under `SYSTEM`, and all of the errant processes were spawning out of it previously as well. I didn't have to touch WSL for it to start happening. I'd be working and it'd start endlessly spawning `wsl.exe` processes, thrashing the HDD and making things hard to interact with. The behavior as it stands now is identical except for what the processes are called.

I didn't and don't have anything that I'm aware of (no autoruns, no services, no scheduled tasks) that would interact with WSL. Only a few manual command-line things which were disabled previously just in case something was trying to call them unexpectedly.

I should've taken screenshots before uninstalling the feature the first time, but I was just desperate to get on with work at that point as the resulting HDD thrashing was extremely severe and would continue 24/7 unabated. Just stock Windows Defender as AV, so the overhead was likely much more than a third party one. Stopping LxssManager using service manager, it'd restart itself after 1-2s, and gave `Access Denied` when trying to disable it. 

![wsl](https://user-images.githubusercontent.com/38739324/59976491-27ee7b00-957a-11e9-92d7-6f4ae7e8ffe0.png)

**Comment by TheGoddessInari** [comment]
Don't know why the previous comment I replied to asking for screenshot disappeared, but as mentioned, it happens spontaneously with Windows 10.0.18362.175, **did not** occur on 10.0.18362.145; Ubuntu 18.04. The base install from the store that you just run with `ubuntu.

Base and C++ development tools have been installed via apt, as has boost and emacs, but nothing stands out as unusual.

If anything's configured differently than default the clean default, it's only been from running `apt update && apt upgrade` to update packages.

No WSL command of any kind was needed for this to happen, just having WSL and Ubuntu installed, and presumably having logged in at least once at some point in the history of the Windows 10 installation.

It'll spontaneously start spawning endless processes in a loop at some period after every boot, and won't stop until the WSL feature is uninstalled. LxssManager restarts **itself** every time you stop it.

I don't have third party software installed to interact with WSL or LxssManager.

**Comment by benhillis** [comment]
@TheGoddessInari - You have the cause and effect backwards.  LxssManager doesn't launch wsl.exe, wsl.exe will trigger-start LxssManager. Something on your system unrelated to WSL is launching wsl.exe.  If you can reproduce this, you should be able to narrow down what is launching the processes by looking for wsl.exe in process hacker.

**Comment by Biswa96** [comment]
This may be related to https://github.com/processhacker/processhacker/issues/153. ProcessHacker itself creates WSL processes to detect packages version due to lack of WSL APIs. cc @dmex

**Comment by TheGoddessInari** [comment]
That seems a really likely case as again, I did repeatedly mention the command arguments to wsl.exe, which match what show up in that issue. Thanks for pointing that out, @Biswa96.
