### ISSUE TITLE
SSH port forwarding not 

### ISSUE THREAD

**Issue by ZaninAndrea** [microsoft/WSL#4217]
## Issue Description
* Your Windows build number: 10.0.18917.1000

* What you're doing and what's happening: 
I tunneled a port from a remote host using ssh

```
ssh -N -f -L localhost:28000:localhost:28000 remote-host # run in a zsh shell in WSL2
```

The port can be accessed inside WSL via

```
curl localhost:28000
```

but from windows 

```
curl http://172.18.78.172:28000 # port obtained with ifconfig in WSL
```

fails to connect to the remote server.

* What's wrong / what should be happening instead: I should be able to access the 28000 port via windows

## Additional tests
I also tried to run a simple express server inside WSL and connect to the server from windows, this works fine.

**Comment by therealkenc** [comment]
You've only bound to localhost, which probably isn't what you are looking for in your scenario. Nothing is listening on `172.18.78.*`. The syntax for [`ssh(1) -L`](http://man7.org/linux/man-pages/man1/ssh.1.html) is:
```
     -L [bind_address:]port:host:hostport
     -L [bind_address:]port:remote_socket
     -L local_socket:host:hostport
     -L local_socket:remote_socket
```
Ref #4199 _insofar_ that _if_ you didn't have `sshd` listening on a Windows `sshd` port 22 and **if** Windows and WSL shared `127.0.0.1`, your syntax would work (read: it would work in WSL1 under some circumstances). For general questions about `ssh`, ServerFault is a good go-to.
