### ISSUE TITLE
Windows 10 WSL2 install 

### ISSUE THREAD

**Issue by Kogam22** [microsoft/WSL#4222]
If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Please fill out the below information:**

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.829]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```powershell
PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform 
Enable-WindowsOptionalFeature : Feature name VirtualMachinePlatform is unknown. 
At line:1 char:1 
+ Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlat ... 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
     + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```
* What's wrong / what should be happening instead:
I'm trying to  enable/install wsl 2 but its giving me a weird error when i try to enable the VM feature.

**Comment by Ethergeist** [comment]
Need to apply windows update 1903 - Windows 10 didn't automatically install it, I had to go and manually start it.

**Comment by onomatopellan** [comment]
@Kogam22 You have build 17134 and you need at least Insider build 18917 for WSL2

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18917

@Ethergeist v1903 is build 18362 so no, WSL2 wont work there either.
