### ISSUE TITLE
Get Disconnected from internet since i upgrade to wsl2

### ISSUE THREAD

**Issue by sithlord2** [microsoft/WSL#4223]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sithlord2** [comment]
Msgraiglowen: the problem i described in the other post about ,getting Disconnected from internet completely ,happen since i upgrade to wsl2 from wsl1, i didnt have this problem when i found out that windows 10  came out with wsl1 i install debian and ubuntu ,telling you the true i'm not a developer yet,i was trying to learn some linux tools for development ,firts on cywing but i soon learned of wsl1 i  install them both distros to try both  cause i was told both for a beginner were good linux distros to learn development but as i say,i didnt have this problem of been disconnected from the hole internet ,thats why i wonder if since when i got upgrade to wsl2 ,i enable on virtual machine platform and when i stiil have wsl1 at that time, but even then i didnt have the problem ,i'm speaking about the problem of that this connection stats when i began use wsl2, i wonder why this happen ,now i know have nothing to do with my dns or my ip provider cause as i said i havent had this problem  before so i wonder is because the kernel  is still  new or still unstable or is because i have to export DISPLAY=the ip that hyper-v give to my wsl2 that and is an a public ip the you get on hyper-v some king of DDOSS dont know. an sorry if im bother but im confuse and concern, is all, oh i forgot when i get DC i dont get any message only that i m not connected,my pc is a all taouch machine and i can connect throw WI-FI on this machine i know is not the wi-fi as i said i havent had this problem bewfore upgrading to wsl2, dont get me wrong im not complainning about wsl2 just im confuse that this is happening when i haven had this problem before when i use wsl1,i used it without this disconnecttions.than you i hope you answerme.

**Comment by sithlord2** [comment]
OK my question is why I get disconnected since, I upgrade to wsl2,when before that I haven't had this problem but, more I when I open a session like xfce4 desktop or mate, it takes more time to disconnected my internet , I DON'T UNDERSTAND WHY MY WHOLE INTERNET GET DC ,SINCE I UPGRADE TO WSL2 BEFORE THIS NEVER HAPPEN NOT EVEN WITH WSL1 IF WAS ONLY WSL2 I WOULD UNDERSTAND IS SOMETHING WRONG WITH MY FIREWALL OR MY ANTI-VIRUS BUT SIN I UPGRADE FIRST TO 18917 AND THEN TO 18922 THIS IS HAPPENING ?

**Comment by sithlord2** [comment]
Sorry my English if you don't understand me at all I'm not native english, speaker my mother tongue is Spanish ,but even though I can defend my self with English ,even with my limitations sorry if I bother you to much guys

**Comment by mscraigloewen** [comment]
To check my understanding, you're not able to access the internet in WSL 2? 

I would double check your firewall and anti-virus settings. (See [this similar issue](https://github.com/microsoft/WSL/issues/4198#issuecomment-505122504) for reference. )

This doesn't seem to be a common problem, or something that I'm easily able to reproduce.

**Comment by phebert5009** [comment]
There is a possible relation to #4171 and #4183: inability to reach the the local windows machine (via `cat /etc/resolv.conf` then using any networking command such as ping to the IP address) will result in having no name servers (the only one listed in `resolv.conf` is unreachable). Connecting to the internet is still possible but only via IP addresses. if @sithlord2 was only trying to connect via domain names, it would seem like they have no connection.

An easy (but slow and annoying) work-around is to append some other name servers to the /etc/resolv.conf file whenever it is reset by auto-generation.

**Comment by hichem77** [comment]
Same problem here ..
Since I've upgraded to wsl2 I get disconnected from my internet every time I launch wsl.

**Comment by SylveonBottle** [comment]
Same problem. https://imgur.com/a/aAwDuvf

**Comment by Alexander-Huang** [comment]
> Same problem here ..
> Since I've upgraded to wsl2 I get disconnected from my internet every time I launch wsl.

a little different from you,I get disconnected when I try downloading or uploading anything in wsl2.
windows 10 2004(19041.508)

**Comment by SylveonBottle** [comment]
Happens to me when attempting to share USB mobile hotspot with ethernet connection to second computer

**Comment by Alexander-Huang** [comment]
> Happens to me when attempting to share USB mobile hotspot with ethernet connection to second computer

Yeah man you are completely right!As my mother won't buy a wireless network card,I use an idle Android phone instead.
If you get how to fix it from the software level,please let me know.Thank you!

**Comment by SylveonBottle** [comment]
> > Happens to me when attempting to share USB mobile hotspot with ethernet connection to second computer
> 
> Yeah man you are completely right!As my mother won't buy a wireless network card,I use an idle Android phone instead.
> If you get how to fix it from the software level,please let me know.Thank you!

After 30 hours of troubleshooting if I recall, I had never found a fix. 

I had to give up completely on any dreams or plans related to WSL2.

**Comment by TheTechOddBug** [comment]
This issue happens to me and other colleagues. We get without internet access if we start a WSL2 console. Our laptops have security tools like Pulse Secure and others and we think maybe there is something related with this.

**Comment by JadJabbour** [comment]
> Happens to me when attempting to share USB mobile hotspot with ethernet connection to second computer

the exact same is happening to me,
