### ISSUE TITLE
[WSL 2] File watchers like create-react-app, gulp or sass doesn't work

### ISSUE THREAD

**Issue by jrmiranda** [microsoft/WSL#4224]
But I can, for example, open a react app from browser normally. Am I missing something?

**Comment by therealkenc** [comment]
> Am I missing something?

No repro was offered offered which would allow a definitive answer; but guessing, no, you are probably not missing something ref #4169.

**Comment by canselcik** [comment]
Related to https://github.com/microsoft/WSL/issues/4064#issuecomment-501047822 for sure.

**Comment by therealkenc** [comment]
#4224

**Comment by djma777** [comment]
same problem here...

**Comment by isaumya** [comment]
I am also facing the exact same issue. So let's say I am using WSL 2 with Ubuntu 20.04 LTS with Sass installed over nodejs. So, when I am doing the following:

```
> cd /mnt/d/some-folder/
> sass assets/scss/example.scss:assets/css/example.css --watch --style compressed
```

It says that watching file, but making changes to the file doesn't invoke the SASS compilation. 

I had to go back to WSL 1 in order for it to work. Is this a WSL bug? Am I missing something here?

**Comment by daviidesnow** [comment]
@isaumya It is currently not working in WSL2. There is still an open issue #4739 .

**Comment by isaumya** [comment]
@daviidesnow Thanks a lot for letting me know. I've moved back my Linux install to WSL 1 as it seems WSL 2 is still not ready for our use-case. Maybe will be fixed in a couple of months or so or maybe never. Who knows? Thanks a lot for pointing to the correct issue.

**Comment by TasinAhmed** [comment]
@daviidesnow Thank you. I was disappointed about this. Guess I'll use WSL1 for now :/

**Comment by tytrdev** [comment]
I got around this by just keeping my project on the native filesystem. I use Windows Terminal and open two tabs. One is ZSH on Ubuntu and this is where I do my tmux/vim stuff. The other is a powershell tab where I add dependencies, run the project, use git commandline, etc.

It's definitely not perfect, but it allows me to feel mostly at home on windows for now.
