### ISSUE TITLE
Error 0x803b0005

### ISSUE THREAD

**Issue by ff0000-it** [microsoft/WSL#4227]
Hi all,

I just passed to WSL 2 and I'd like to install from scratch a distribution; specifically Debian, but the following happens with Alpine and Kali too.

Windows build number:  Microsoft Windows [Version 10.0.18922.1000]

After installed it I simply launched it from the Store and its setup (Debian) fails like this:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```

Or like this (randomly):

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x803b0005
Error: 0x803b0005 The network does not have a subnet for this endpoint.

Press any key to continue...
```
This is what it looks like on Alpine:

```
Temporary directory: C:\Users\ALESSA~1\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-minirootfs-3.9.0-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\ALESSA~1\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Status code : 32
Finding resource...
Connecting...
Sending request...
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: f82efed1a80c9af86c38bed10f3541c5588453b97684d767a5a3b0f3fa0e3f09

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
WslRegisterDistribution failed
Error: 0x80070005 Access is denied.

Press any key to continue...
```

Any hints about it?

Thanks,
Alessandro

**Comment by ff0000-it** [comment]
Just tried Ubuntu and it works... maybe the other WSL distro aren't update for the WSL 2?

**Comment by novotnej** [comment]
I have been using Ubuntu 20.04 in WSL2 for about a week, this happened today. I was running very low on disk space, also I manually rewrote /etc/resolv.conf - I suspect these could be the likely causes, but I have no idea how to fix them at this stage...


![image](https://user-images.githubusercontent.com/3701992/125344254-586b0280-e357-11eb-8077-837119501a66.png)
