### ISSUE TITLE
[WSL 2]Replace/update kernel?

### ISSUE THREAD

**Issue by pascua28** [microsoft/WSL#4228]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18922.1000]

* What you're doing and what's happening:  I've successfully compiled the kernel from here: https://thirdpartysource.microsoft.com/download/Windows%20Subsystem%20for%20Linux%20v2/May%202019/WSLv2-Linux-Kernel-master.zip using the default config from /proc/config.gz. I used `make -j4` and then `sudo make install`. I checked the corresponding files in /boot to ensure everything is updated.

* What's wrong / what should be happening instead: After issuing the above commands and shutting down the vm using `wsl --shutdown Debian`, `uname -a` still returns `Linux Sam 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 GNU/Linux` which means the kernel didn't get updated. I even did `make -j4 bindeb-pkg` to make debian packages, and after installing, still the same.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by kdrag0n** [comment]
The WSL 2 kernel is not actually inside any of the distro containers. Instead, it's located at `C:\Windows\System32\lxss\tools\kernel` in Windows and owned by TrustedInstaller, which means that you will need to take ownership of the file and grant yourself the permissions necessary to modify it first.

Since this process can be daunting, I wrote a comprehensive guide for replacing the kernel, as well as some helper scripts to do the work for you: https://github.com/kdrag0n/proton_wsl2/blob/v4.19-proton/README.md#installation

**Comment by pascua28** [comment]
> The WSL 2 kernel is not actually inside any of the distro containers. Instead, it's located at `C:\Windows\System32\lxss\tools\kernel` in Windows and owned by TrustedInstaller, which means that you will need to take ownership of the file and grant yourself the permissions necessary to modify it first.
> 
> Since this process can be daunting, I wrote a comprehensive guide for replacing the kernel, as well as some helper scripts to do the work for you: https://github.com/kdrag0n/proton_wsl2/blob/v4.19-proton/README.md#installation

Thanks for the guide. Okay, so I just realized that the kernel must be loaded first in order to mount the ext4 partition (which the /boot partition also resides). Many thanks
