### ISSUE TITLE
debian.exe The service has not been started.

### ISSUE THREAD

**Issue by dannyg64** [microsoft/WSL#4233]
Attempted to install Debian using WLS on Windows 10.  Had to use the manual procedure due to proxy settings.  Downloaded and executed the installation package for debian.  Continually get the "The service has not been started" error when trying to startup the distro.  Logs have been gathered and are attached.

**Comment by therealkenc** [comment]
> Had to use the manual procedure due

You are off-roading it here and there isn't _possibly_ a conclusive answer forthcoming based on the information provided. "The [hand wave] manual procedure" is going to be a list of very specific CLI steps you followed from a unknowable set of initial conditions save for clean install no one is likely to replicate (or that you even remember, specifically; I certainly wouldn't). 

Attach the logs or link a gist thereof when you can. With luck maybe get an answer. Do a blog post on your experience. But as a practical matter, there is nothing to work with here. But bonne chance. (really!)

**Comment by shrknt35** [comment]
Getting the same error for ubuntu.
![image](https://user-images.githubusercontent.com/849889/84910570-a837b580-b0d4-11ea-95b2-b56a34c3af2a.png)
