### ISSUE TITLE
Bash hangs immediately on launch

### ISSUE THREAD

**Issue by sagebrush1111** [microsoft/WSL#4235]
* Your Windows build number:  10.0.18362.175

* What you're doing and what's happening: Trying to launch bash but immediately hangs. The line <username@device>$ never shows up just a black screen.

* What's wrong / what should be happening instead: WSL 1 should launch and show <username@device>$. 

I have tried to fix it by restarting LxssManager but it never stops. Only solution is a full reboot.

Others seem to have related issues within the past week: #849

**Comment by mscraigloewen** [comment]
Marking this as a duplicate to issue #4047 , please follow that issue for further news! Thanks
