### ISSUE TITLE
Wslpath doesn't ignore flags in the beginning of a string

### ISSUE THREAD

**Issue by imswebra** [microsoft/WSL#4236]
**Your Windows build number:** 18362.175

**What you're doing and what's happening:**
```Python
# Current behavior
wslpath "-Wall -std=c++11 C:\foo\bar.cpp"
# wslpath: unrecognized option: W

# Desired behavior
wslpath "-Wall -std=c++11 C:\foo\bar.cpp"
# -Wall -std=c++11 /mnt/c/foo/bar.cpp
```

**What's wrong / what should be happening instead:**
Though I may be incorrect given the limited documentation on wslpath, I consider the persistence of suffix flags through wslpath to be an intended feature, given the utility this offers in terms of Linux/Windows interoperability. For example, currently, `wslpath "C:\foo\bar.cpp -Wall -std=c++11"` returns `/mnt/c/foo/bar.cpp -Wall -std=c++11`. This type of behavior is extremely useful for [wsl-proxy](https://github.com/watzon/wsl-proxy) like scripts and projects.

I would therefore consider the parsing of prefix flags within a string as shown above to be a potential bug, as the flags for wslpath itself should never be contained within a string (as far as I'm aware).

**Comment by benhillis** [comment]
You could easily work around this behavior by doing this:
```
-Wall -std=c++11 $(wslpath 'C:\foo\bar.cpp')
# -Wall -std=c++11 /mnt/c/foo/bar.cpp
```

**Comment by therealkenc** [comment]
```
$ touch ./-Wall
```

`wslpath` doesn't have the slightest idea those are flags.

**Comment by imswebra** [comment]
@benhillis I understand and agree, though in cases where you are looking to use a Windows linter with a WSL compiler/interpreter for example, you may not have control over what commands are being sent. 

Say my linter happens to place flags after the path, in this case I can just have a proxy batch file which first runs something like `wsl wslpath "%*"` to figure out the arguments to then pass along with `wsl g++`. I was hoping to have as elegant of a solution for the case in which the linter places the flags before the file path.

@therealkenc, if I'm understanding your comment correctly, the functioning example I provide in the original post is more me getting lucky than intended behavior, correct?

**Comment by benhillis** [comment]
@imswebra - Correct.  Wslpath just assumes the first argument after wslpath's own flags is the path to be translated.

**Comment by imswebra** [comment]
@benhillis So the "proper" approach then (utilizing wslpath as intended) would be a much fancier proxy file which a) discerns which argument is a path, b) extracts and converts the path using wslpath, c) reinserts the new, converted path back into the original argument list, d) passes that new argument list to the WSL compiler / interpreter?

Is there a better way to approach the path-style conversions when using the wsl interop?

**Comment by benhillis** [comment]
@imswebra - Ideally you could use relative paths instead of absolute and 95% of things will "just work".  Windows will happily accept / as a path separator.

**Comment by imswebra** [comment]
@benhillis Fair enough. Maybe the solution to a more closed system such as a linter is to modify the linter itself to work with relative paths instead of trying to convert absolute.

**Comment by therealkenc** [comment]
It's good advice. And use Windows `mklink` to `D:/ `E:/` `F:/path/to/stuff` with a pretty name if something absolutely positively has to live over there.
