### ISSUE TITLE
Path doesn't delete in wsl

### ISSUE THREAD

**Issue by eromoe** [microsoft/WSL#4237]
env : windows 1903
wsl : ubuntu 1804
## 1

`E:\pp\pyspark-jobs` is not exist in windows file explorer : 

![image](https://user-images.githubusercontent.com/3938751/60243335-9751cb00-98ea-11e9-9ad1-62c819fb3cf0.png)

![image](https://user-images.githubusercontent.com/3938751/60243383-b18ba900-98ea-11e9-9d36-68932597a9e4.png)

## 2 

`ls` doesn't show `pyspark-jobs` : 
```
➜  /e cd /e/pp
➜  pp ls -al|grep pyspark
drwxr-xr-x 1 root root      4096 Oct 24  2018 pyspark
drwxr-xr-x 1 root root      4096 Jun 13 11:12 pyspark-example-project
drwxr-xr-x 1 root root      4096 Jun 27 14:21 pyspark-jobs1
drwxr-xr-x 1 root root      4096 Jun 27 14:37 pyspark-jobs - 副本
```

## 3 

But can enter this folder , this folder can not be remove because `scripts` under it can be remove .

```
➜  pp cd /e/pp/pyspark-jobs
➜  pyspark-jobs ls -al
total 0
drwxr-xr-x 1 root root 4096 Jun 27 14:45 .
drwxr-xr-x 1 root root 4096 Jun 27 14:44 ..
drwxr-xr-x 0 root root 4096 Jun 25 18:24 scripts
➜  pyspark-jobs rm -rf scripts
rm: cannot remove 'scripts': Directory not empty
```

-------------

I think it maybe some fault with windows deletion .

Since yesterday I can't rename this folder, I have to unlock it and rename by https://lockhunter.com/.

I think this is how the problem come from.
But I have no idea how to solve it .

**Comment by therealkenc** [comment]
>  https://lockhunter.com/.

And now I'm in my sad place. "Our flasgship product USB Safely Remove won "100 Best Products of 2008" award from PCWorld magazine."

#1529

**Comment by eromoe** [comment]
I found the problem . 
I was used tmux , actually it is a splited pane at path `/e/pp/pyspark-jobs` . 
Because I ssh to a remote server , didn't aware this pane prevernt the deletion .
