### ISSUE TITLE
WSL2: OMS-Agent-for-Linux Installation Failure

### ISSUE THREAD

**Issue by MedAnd** [microsoft/WSL#4238]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

_Microsoft_ Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Followed installation steps as per [Configure Log Analytics agent for Linux computers in a hybrid environment](https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-linux-computer)

* What's wrong / what should be happening instead:

**Actual**

_Failed to connect to bus: No such file or directory
dpkg: error processing package scx (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 scx_

**Expected**

Script installs without error and the agent is running, ready to be configured for reporting metrics back to Azure Monitor.

**Full log**

[WSL2-OMS-Agent-for-Linux-Install-Logs.txt](https://github.com/microsoft/WSL/files/3333907/WSL2-OMS-Agent-for-Linux-Install-Logs.txt)

**Comment**

The above failure seems similar to the [WSL2: Service Fabric for Linux Installation Errors](https://github.com/microsoft/WSL/issues/4178).

**Comment by therealkenc** [comment]
> The above failure seems similar to the WSL2: Service Fabric for Linux Installation Errors.

In addition to #4178, fundamentally dupe #2941 #2209 #1579 #376 et al aka everyone's favorite landing zone #994.

An OMS-Agent-for-Linux (I gather that's a thing) could likely be made to run on a Linux without `systemd` --- and probably does --- but you will get better information on how to do that in a forum related to the product.

**Comment by MedAnd** [comment]
@benhillis @mscraigloewen - may I recommend the FAQ is updated to clearly spell out that WSL2 **does not run systemd (or anything that systemd usually starts, like dbus-daemon)**

@therealkenc - would also be good to clarify if this will never be supported or it's on your roadmap.

**Comment by mscraigloewen** [comment]
Adding the question 'Can I run systemd in WSL?' would be a great addition to the FAQ page on our docs. I'll put in a change for that!
