### ISSUE TITLE
WSL2 cannot allow server running inside to be accessible outside WSL

### ISSUE THREAD

**Issue by marioidival** [microsoft/WSL#4239]
**Please fill out the below information:**
Microsoft Windows [version10.0.18922.1000]

I cannot access serves inside of WSL anymore.

**Comment by mscraigloewen** [comment]
Please check out this section of the docs detailing [how to connect to a Linux server from Windows in WSL 2 (in initial builds)](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#accessing-linux-applications-from-windows). 

We're working on improving the networking story. I'll close this issue as without any more repro steps I believe that's your issue. If your issue still isn't solved please reopen this issue and provide some more detail in what you're trying to do and what's failing.

**Comment by marioidival** [comment]
```
(project) kakarotto@DESKTOP-K9R1Q1Q:~/workspace/project$ ip addr | grep eth0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.17.218.60/16 brd 172.17.255.255 scope global eth0
````

**Comment by marioidival** [comment]
```(project) kakarotto@DESKTOP-K9R1Q1Q:~/workspace/project/validation$ npm start

> ui-validation@0.0.0 start /home/kakarotto/workspace/project/validation
> ng serve --proxy-config=proxy.conf.js


** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building 4/4 modules 0 active[HPM] Proxy created: [ '/vwapi' ]  ->  http://127.0.0.1:5000
[HPM] Proxy rewrite rule created: "^/vwapi" ~> ""
                                                                                                 
Date: 2019-06-27T18:33:05.299Z
Hash: 5da6b81e9bec4e9bd30a
Time: 29383ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 98.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 309 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 179 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.3 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by marioidival** [comment]
On browser: http://172.17.218.60:4200 not working, @mscraigloewen

**Comment by mscraigloewen** [comment]
I would guess that you need to make sure your web app is accepting connections from all IP addresses (and not just localhost). 

Please see issue #4136 for an example of how to configure this.

**Comment by marioidival** [comment]
All people:

with angular, you need set host as `0.0.0.0` to work

ng serve --host=0.0.0.0

**Comment by yonasayfu** [comment]
for me it works using "ng serve --open --host 0.0.0.0" but there is a warning 

WARNING: This is a simple server for use in testing or debugging Angular applications locally. It hasn't been reviewed for security issues.
Binding this server to an open connection can result in compromising your application or computer. Using a different host than the one passed to the "--host" flag might result in websocket connection issues. You might need to use "--disableHostCheck" if that's the case.
