### ISSUE TITLE
ethtool on bash doesn't work - can't pull info from windows

### ISSUE THREAD

**Issue by Squish8294** [Microsoft/WSL#424]
It runs, it dumps output correctly, but can't pull the info for windows, so the output is as follows:

root@SQUISH-PC:/mnt/c/Users/Squish# sudo ethtool eth0
Settings for eth0:
Cannot get device settings: Invalid argument
Cannot get wake-on-lan settings: Invalid argument
Cannot get message level: Invalid argument
Cannot get link status: Invalid argument
No data available

Addendum: Output is the same running bash on elevated cmd prompt.

**Comment by sunilmut** [comment]
ethtool uses functionality such as socket IOCTL SIOCETHTOOL which is not yet implemented in WSL. We are using our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to prioritize what to implement next. You can help us prioritize by providing the feedback there as well. I see one item that is [related](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration), feel free to up vote it or open up a new one.

**Comment by dcuomo** [comment]
👍 is this uservoice request created already?  I'd like to upvote!  ethtool -T is important!

**Comment by Squish8294** [comment]
@dcuomo 

I submitted this issue on hardware that is no longer mine, and the problem I was having that ended up in me opening this request was a faulty cable.

I was attempting to force gigabit connectivity in an effort to verify whether my onboard NIC had developed a hardware fault. I wound up booting Ubuntu to debug this further.

**Comment by dcuomo** [comment]
Thanks @Squish8294 - So does ethtool work for you now?

I'm still getting "Cannot get device time stamping settings: Invalid argument" when i run sudo ethtool -T eth0

**Comment by 0ric1** [comment]
WSL Ubuntu 18.04, ethtool version 4.15 output of ethtool eth0:
`Cannot get device settings: Invalid argument
Cannot get wake-on-lan settings: Invalid argument
Cannot get message level: Invalid argument
Cannot get link status: Invalid argument`
