### ISSUE TITLE
wsl2 hibernation date error - Date mismatch in wsl1 and wsl2 after wake up from hibernation

### ISSUE THREAD

**Issue by alkthegit** [microsoft/WSL#4247]
Hi, I'm having an issue with the time mismatch on WSL2.

Windows version: 10.0.18922.1000

🖥 WLS distros. I have the following distros installed:
- Ubuntu 18.04 as Legacy wsl1
- Ubuntu 18.04 installed and converted to version 2

``` PowerShell
>wsl -l
Legacy (Default)
Ubuntu-18.04
```

⬇ I used to hibernate my Windows machine with the following command:

``` cmd
>shutdown /h
```

⬆ After my machine wakes up the outputs of the bash command `date` in WSL and WSL2 seem to differ by the duration of time the system was in the hibernation sleep.

🐧 With that being the case Linux tools such as apt-get stop working properly.

✔ How I solve this right now
The only way I've found to work around this is to shut down all WSL images:
``` PowerShell
>wsl --shutdown /h
```
and running a distro I need:
``` PowerShell
>wsl -d Ubuntu-18.04
```

After that the command 
``` bash
>date
```
run under wsl1 Legacy and wsl2 Ubuntu-18.04 shows exactly the same output.

**Comment by therealkenc** [comment]
#4114
