### ISSUE TITLE
All commands for a specific WSL2 Distro fail with a network error message

### ISSUE THREAD

**Issue by rkttu** [microsoft/WSL#4248]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

  * 10.0.18922.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

  * The Debian distribution with WSL 1 was upgraded to WSL 2 and used for a while. Then one day when I try to run the Debian distribution, I get the following error message and it does not work.

  * "The network does not have a subnet for this endpoint."

  * I tried to use other options such as `--export`, `--set-version` to solve the problem, but because the distribution itself needs to be executed, all the operations fail with the above message.

  * No special error codes appear and troubleshooting is difficult.

  * Note that this computer uses both OpenVPN and ExpressVPN.

  * This also seems to be related to https://github.com/microsoft/WSL/issues/4227 .

* What's wrong / what should be happening instead:

  * At the very least, I need a guide for me to figure out what the problem is and how to fix it.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

  * I can not get a strace trace because I can not get into that Linux distribution at all.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

  * I attached three files for this issue. [logs.zip](https://github.com/microsoft/WSL/files/3342576/logs.zip)

**Comment by rkttu** [comment]
Update: Again, I get the same error when importing a new distribution to WSL 2, not just for a particular distribution.

**Comment by VirtualSatai** [comment]
I had the same issue, and a simple reboot resolved it for me.

**Comment by mhegreberg** [comment]
@rkttu , what solved this issue for you?

**Comment by rkttu** [comment]
> @rkttu , what solved this issue for you?

I'm sorry that I cannot remember what was the situation. Because it's quite long time passed since I closed this issue.
