### ISSUE TITLE
npm/node does not work in the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by daveanonuevo** [microsoft/WSL#4249]
Can't run NPM or Node as expected

running "npm" give this error

```
: not foundram Files/nodejs/npm: 3: /mnt/c/Program Files/nodejs/npm:
: not foundram Files/nodejs/npm: 5: /mnt/c/Program Files/nodejs/npm:
/mnt/c/Program Files/nodejs/npm: 6: /mnt/c/Program Files/nodejs/npm: Syntax error: word unexpected (expecting "in")
```
running "node" gives this error

```
Command 'node' not found, but can be installed with:

sudo apt install nodejs

```

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.593]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I have a website made in ReactJS, I am trying to use npm start. However, this does not work. I am assuming it's because Linux does not know how to access "/mnt/c/Program Files/nodejs/npm" because it probably needs a "/mnt/c/Program\ Files/nodejs/npm" to escape the space

**Comment by therealkenc** [comment]
> because it probably needs a "/mnt/c/Program\ Files/nodejs/npm" to escape the space

It is a EOL thing. Dupe #1512 ([message](https://github.com/microsoft/WSL/issues/1512#issuecomment-373300810)) variation Variation #2365 ([message](https://github.com/Microsoft/WSL/issues/2365#issuecomment-317526788)) etc.

> Command 'node' not found, but can be installed with:
> sudo apt install nodejs

Yes that. `sudo apt install npm` too. Or maybe better, from the [makers](https://nodejs.org/en/download/package-manager/).

**Comment by firstoctet** [comment]
Ran into this wsl npm headache today.  If other solutions did not work this is what I did.
For this example, it is important to understand what the goal is for this case so you can use this example to show the error exists, do the fixes, and see if it fixed it for you as well.
```
$ cat broken.js
const puppeteer = require('puppeteer-core');

$ node broken.js
# Some errors related to "Cannot find module puppeteer-core"

$ npm i install  puppeteer-core
# Some errors, maybe something related to package.json 
# After a few hours, I begin to doubt my career choice.
```
1- UNINSTALL ubuntu wsl but don't forget to Run history first and back up your files.
2- Go to the microsoft store and search for Linux.  Choose the Microsoft provided Debian wsl.
3- sudo apt update
4- sudo apt upgrade
5- sudo apt install wget
6- wget https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.xz
7- Read this install guide
https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux
8 - sudo mkdir -p /usr/local/lib/nodejs
9- sudo tar -xJvf node-v12.16.3-linux-x64.tar.xz -C /usr/local/lib/nodej
10- Put this on the last line of your ~/.profile file
```
export PATH=/usr/local/lib/nodejs/node-v12.16.3-linux-x64/bin:$PATH
```
11- which node 
12- which npm
13- sudo apt install dos2linux
14- dos2linux broken.js
15- npm i puppeteer-core
16- node broken.js

Twitter is the best way to reach me.  I think those are all the steps, but ping me @mabrafoo if needed.

**Comment by mohammedSlimani** [comment]
I dont know why, but using yarn instead of npm seems to solve my problem

**Comment by vchacon** [comment]
firstoctet, this was the exact fix to my problem. NPM would not function I suspect the path "Program Files" to be at least part of the issue. Took that out of the equation by installing it manually.  Thanks saved my a ton of hours.  WSL 2 NPM not working

**Comment by fuhrmanator** [comment]
So, the best practice if I follow correctly is to install node/npm (and respective packages) separately in WSL? Because of the shared paths, WSL's npm finds my global packages installed from Windows 10... Is it too soon to call this a best practice?

**Comment by tastyneko** [comment]
I used this guide to install node

https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2

npm works on both windows and wsl 2.

**Comment by icculp** [comment]
I ended up adding appendwindowspath=false to /etc/wsl.conf
