### ISSUE TITLE
Why is WSL not accessible to locked users?

### ISSUE THREAD

**Issue by ckunte** [microsoft/WSL#4250]
Despite years of hoping that one day WSL would be accessible to locked, end-users, that day is yet to come. The company I work for outsources IT support + system administration to third party organisations, and it has been a losing battle with these outsourced system administrator(s) who have zero interest in user empowerment. Should I still nurse the idea that someday WSL, which works in user space, but requires admin intervention for installation, be part of Windows without the latter?

**Comment by mscraigloewen** [comment]
WSL follows a traditional app model. Like most applications yes you will need administrative rights to install it, and I do not see this changing anytime in the near future. I hope your IT support can be convinced to let you start using WSL in the future!
