### ISSUE TITLE
Update documentation for WSL_DISTRIBUTION_FLAGS for WSL2

### ISSUE THREAD

**Issue by DDoSolitary** [microsoft/WSL#4251]
When a distro gets upgraded to WSL2 using `wsl /set-version`, its `Flags` registry key is ORed with a new bit flag 0x08, which is not documented for now. It would be nice to have official explanation/documentation for this new flag.

**Comment by benhillis** [comment]
@DDoSolitary - We are not going to document internal registry state because it is subject to change.

**Comment by DDoSolitary** [comment]
@benhills The registry value isn't internal at all. It's directly exposed via the argument `wslDistributionFlags` of the function `WslGetDistributionConfiguration` which is part of the public API.

**Comment by benhillis** [comment]
No, it's not. Try setting the value via the api.

**Comment by benhillis** [comment]
Fair enough. We will update the document when the new flag ships outside of insider builds. FYI setting the flag via that API will not work.

**Comment by therealkenc** [comment]
> It would be nice to have official explanation/documentation for this new flag.

[Next one](https://github.com/microsoft/WSL/issues/3693) of these _please_ post over in [MicrosoftDocs/WSL](https://github.com/MicrosoftDocs/WSL/issues).

**Comment by Biswa96** [comment]
The lxss registry isn't changed in three years. Why it can't be documented? It may fix many things in simple ways. For example, to move a WSL2 distribution one can move the VHDX file and change the BasePath registry and done. No need to do import/export. Another example, one can parse the lxss registry key and implement their own `wsl -l -v` style output. Another example, users can change distribution name easily.

Do we have to wait 1 year to get the WSL2 flag?
