### ISSUE TITLE
WSL is not recognized as the name of a cmdlet, etc.

### ISSUE THREAD

**Issue by 8thHalfHour** [microsoft/WSL#4259]
* Your Windows build number:  Microsoft Windows [Version 10.0.18922.1000]

* What you're doing and what's happening:
I am trying to set wsl 2 as my default version. The command I attempt in Powershell:

`wsl --set-default-version 2`

PowerShell responds with:

`wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

* What's wrong / what should be happening instead:

The command should work; wsl.exe should be found and execute. 

I *can* get it to work if I do this:

`C:\windows\system32\wsl.exe --set-default-version 2`

Does this mean that WSL is not in my path?

* What I tried to do to fix it:

I removeed WSL from my system and after restarting, performed a full `DISM.exe /Online /Cleanup-image /Restorehealth` check and then an `sfc /scannow`; no issues were found. I re-enabled WSL, Hyper-V, and the Virtual Machine Platform. Everything is telling me this should be working. Except, it's not. I also cannot seem to find anyone else having this issue.

**Comment by therealkenc** [comment]
Can’t reproduce here, but you know that.

> Does this mean that WSL is not in my path?

What is your path? For example:

```
PS C:\> where.exe wsl
C:\Windows\System32\wsl.exe
PS C:\> $Env:Path
C:\Program Files (x86)\Google\Chrome\Application;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\there\AppData\Local\Microsoft\WindowsApps;C:\Program Files\qemu;
```

> Everything is telling me this should be working. Except, it's not. I also cannot seem to find anyone else having this issue.

No guesses, because you're right (it should be working). Try running something else in `System32` from Powershell just to eliminate the possibility it isn't `wsl` but something being more generally borked. Say at random:

```
PS C:\> where.exe calc
C:\Windows\System32\calc.exe
PS C:\> calc
```

**Comment by 8thHalfHour** [comment]
RESOLVED. Somehow when I removed PowerShell 6, the `%SystemRoot%\system32` and `C:\Windows\System32` entries were removed from the PATH. It came to me last night to look, and sure enough, those entries were gone. All is well now. Thanks for your help!

**Comment by vahidzolf** [comment]
this command was useful for me to enable Linux Subsystem: 
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

**Comment by velletti** [comment]
Solution for me: 
Use correct version of powershell (not the x86) :

x86 Version of powershell does not list wsl.exe using f.e. dir wsl*.*  or which wsl.exe

**Comment by voronoipotato** [comment]
This is a genuine problem for surface pro x where there is ONLY a x86 version.

**Comment by therealkenc** [comment]
You can get a win-arm64 copy [here](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3). [Why the 64-bit version doesn't ship by default (taking as given it doesn't) I couldn't tell ya, but that much is not WSL actionable.]

**Comment by one2code** [comment]
> Solution for me:
> Use correct version of powershell (not the x86) :
> 
> x86 Version of powershell does not list wsl.exe using f.e. dir wsl*.* or which wsl.exe

This was the solution for me. I wish the official documentation was clear about this. You saved me A LOT of headache, thanks man.
