### ISSUE TITLE
WSL2: can't access linux file system from windows

### ISSUE THREAD

**Issue by Martaver** [microsoft/WSL#4260]
**Please fill out the below information:**
* Your Windows build number:  10.0.18922.1000

* What you're doing and what's happening:
Using visual studio code's bash terminal for WSL, I `cd ~` and attempt to `explorer.exe .` as per documentation here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#place-your-linux-files-in-your-linux-root-file-system

* What's wrong / what should be happening instead:
Instead of opening `explorer.exe` at the corresponding folder in the linux file system, I get the error:
```
/c/WINDOWS/explorer.exe: Invalid argument
```

* Strace of the failing command, if applicable:  No other errors logged. If I'm given instructions I'm happy to run diagnostic commands and report back.

**Comment by Martaver** [comment]
Note: running `explorer.exe .` from a mounted windows drive, e.g. `/mnt/c` works fine.

This is a blocker, preventing me from opening a project located on the linux file system in VSCode.

**Comment by onomatopellan** [comment]
Things I'd try:
-Try using the real bash terminal or the new Windows terminal, not the one inside Vscode.
-Look at /etc/wsl.conf content. (that /c/WINDOWS/ is fishy)
-See `dmesg` output to see if it tells what's happening.

**Comment by Martaver** [comment]
I am mounting `/mnt/...` drive directly under `/` in my `wsl.conf`... 

I ruled that out, though, because `explorer.exe .` works fine from within the mounted drive at `/c/...`

Would you mind giving me some more information on how I can debug this using dmesg?

VSCode remoting to WSL works quite nicely, btw.

**Comment by mscraigloewen** [comment]
Another troubleshooting idea: If you go into File Explorer and type in: `\\wsl$\<yourDistroName\` into the address bar (replacing <yourDistroName> with the name of your distro which you can see from `wsl -l`), does that work or does that result in an error?

**Comment by Martaver** [comment]
Ah, so from File Explorer, browsing to `\\wsl$\Ubuntu-18.04\` gives me error:
```
\\wsl$\Ubuntu-18.04 is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions.

Attempt to access invalid address.
```

Can't quite tell if this is a permissions issue, or 'invalid address'... any ideas?

**Comment by mscraigloewen** [comment]
This seems to be an error with the Plan 9 server. @SvenGroot is the resident expert for this area!

**Comment by erikhakansson** [comment]
I suddenly have this issue too after upgrading to 18932. It worked previously but with issues (#4262)

**Comment by erikhakansson** [comment]
`sudo apt update && sudo apt upgrade` followed by `wsl --shutdown` and then starting wsl again resolved the issue for me.

But I don't know if it's permanently or not.

**Comment by Martaver** [comment]
@erikhakansson's steps didn't change the problem for me.

**Comment by onomatopellan** [comment]
#Martaver I think your issue it's very similar to [#4027](https://github.com/microsoft/WSL/issues/4027#issuecomment-494969089)?
Keep reading and try the registry workaraound that Sven suggested in that thread.

**Comment by stuffaboutpete** [comment]
I'm struggling with the same and the linked issue wasn't my problem - the registry values were already correct. `apt upgrade` also made no difference although running `wsl --shutdown` is helpful because it saves logging out or rebooting.

**Comment by peidaqi** [comment]
Same here.

\\wsl$ is very unstable and drops from time to time. This seems to have something to do with number of writes - I often have the problem after working with a project from VSCode (and save the files several times).

It can be decieving that sometimes \\wsl$\ can still be accessed, but this is from cache. If you try to actually open the files using notepad/vscode you will still have a filesystem error.

Restarting WSL with wsl --shutdown seems to fix it temporarily.

**Comment by enterit** [comment]
> Ah, so from File Explorer, browsing to `\\wsl$\Ubuntu-18.04\` gives me error:
> 
> ```
> \\wsl$\Ubuntu-18.04 is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions.
> 
> Attempt to access invalid address.
> ```
> 
> Can't quite tell if this is a permissions issue, or 'invalid address'... any ideas?

I am seeing exactly the same issue on my Windows 10 1903 18941.1001.
Updating Ubuntu or restarting WSL did not help.
@Martaver, have you by any chance figured out how to fix this?

**Comment by David-Defoort** [comment]
I've updated to 1903 18362.356 as of yesterday and I'm having this issue as well
* Explorer shows Ubuntu under \\wsl$
* when I double click I get:
![image](https://user-images.githubusercontent.com/5627161/64904747-8d13c180-d6ce-11e9-9ed6-79195b35b292.png)
* inside a cmd, `dir \\wsl$\Ubuntu` does not works ("The system cannot find the path specified.")
* (in bash) `explorer.exe .` inside a /mnt point works fine.  Explorer.exe comes up to the expected path location
* (in bash) `explorer.exe .` outside a /mnt point does nothing, it does not even bring explorer at all
* (in bash) `code` does not work outside /mnt points, which is what bothers me the most. It used to work and I became dependent of it...

I tried to:
- apt-get update/upgrade no effect
- uninstall/reinstall Ubuntu and Ubuntu-18.04, no effect
- disable WSL, reboot, re-enable, no effect
- verified the registry as [#4027](https://github.com/microsoft/WSL/issues/4027#issuecomment-494969089) said to no effect

I have another PC where that works as expected on 1903, `explorer.exe .` etc...

**Comment by abreingan** [comment]
Hi I seem to have exactly the same problem as David-Defoort, but with the Debian distro.
1903 18362.356 also.

**Comment by aleblanco** [comment]
> Another troubleshooting idea: If you go into File Explorer and type in: `\\wsl$\<yourDistroName\` into the address bar (replacing with the name of your distro which you can see from `wsl -l`), does that work or does that result in an error?

This solution worked perfectly for me. Thanks!

**Comment by abreingan** [comment]
I am now on 10.0.18362.388 and retried the disable wsl and that was successful (not sure if this is permanent or not).
I started cmd with admin authority and entered "wsl -t Debian"
After that File Explorer and enter  \\wsl$\Debian\ works.

**Comment by ferlauf** [comment]
When it happens, I usually do "Get-Service LxssManager | Restart-Service" from the PS (Run as administrator). 
I'm currently on 10.0.18999.1 and it seems WSL is a bit more stable now.

**Comment by benhillis** [comment]
There have been a handful of fixes around the \\wsl$\ paths so things should be much more robust now.  Please reopen a new issue if you continue to see issues after build 19002.

**Comment by fracasula** [comment]
It would be great if it'd be possible to map a network drive that points to a folder in the Linux subsystem:

![Annotation 2019-11-19 083927](https://user-images.githubusercontent.com/1288256/69126324-3a78cc00-0aa8-11ea-849b-093e0440b6ba.png)

Unfortunately that doesn't work and I don't see other options for editing those files with editors like JetBrains' (I'm talknig about running the editor from the host, not the VM of course).

Any ideas?

**Comment by raphaeldisanto** [comment]
fracasula, come at it from the other angle.

All of your windows files are accessible from within the linux distro under /mnt/<drive letter>, so just store the files there.  That way, both windows and linux has access to them.

**Comment by SvenGroot** [comment]
@fracasula Does simply mapping \\\\wsl$\\Ubuntu-18.04 not work for you? You should be able to do that and then access the folder as Z:\\root\\Code.

Is there any reason you have to map the specific folder to a drive?

**Comment by whaaaley** [comment]
I was still having this problem up until today. Previously, my lowercase file path worked, `\\wsl$\debian`, but reading https://github.com/microsoft/WSL/issues/4260#issuecomment-507841709 I tried uppercase, `\\wsl$\Debian`, and it worked, and it also made the lowercase paths start working again. So check your casing.

**Comment by fracasula** [comment]
> fracasula, come at it from the other angle.
> 
> All of your windows files are accessible from within the linux distro under /mnt/, so just store the files there. That way, both windows and linux has access to them.

I did not know that was possible, thanks 👍

**Comment by whaaaley** [comment]
FWIW. I was having issues with file watching when storing files Windows side, so depending on your needs, accessing files via `/mnt` may not be viable.

**Comment by phelps-matthew** [comment]
For some others that encounter the same error, my case was able to be resolved by ```Set-ExecutionPolicy Unrestricted``` in powershell. Previously I had changed it to remotesigned, and this was the source of not being able to access the /mnt directory.

**Comment by Msadr471** [comment]
Hi
in this picture, you can see  I don't have access my directory:
![image](https://user-images.githubusercontent.com/49529241/71692587-8ca74f80-2dbf-11ea-9288-2f4bc2888520.png)

What is this??
thinclient_driver?!
![image](https://user-images.githubusercontent.com/49529241/71692613-a6e12d80-2dbf-11ea-822f-6e960bac5a7e.png)

also, I don't have access to the root folder?! Why?
![image](https://user-images.githubusercontent.com/49529241/71692673-d728cc00-2dbf-11ea-94f0-f94052c08728.png)

how can I set root forever when I open it.
![image](https://user-images.githubusercontent.com/49529241/71692768-148d5980-2dc0-11ea-8591-c6b3b5ae0d63.png)

**Comment by whaaaley** [comment]
This is still an issue in March 2020. It happens 50% of the time.

**Comment by fjeddy** [comment]
Ditto, latest windows 10 stable build, keep losing the WSL connection every few hours. So far the only "fix" is to reboot the entire computer.

**Comment by abreingan** [comment]
I managed to temporarily fix this by starting a cmd with admin authority and entered "wsl -t Debian" (the name of my WSL instance) 
After that start File Explorer and enter \wsl$\Debian\ works.
You might also add you comment on to the open issue i started after this one was closed. It is 
WSL2: can't access linux file system from Windows Explorer #4812

**Comment by whaaaley** [comment]
I gave up trying to get this to work consistently, I bit the bullet and moved all my projects out of WSL and rewrote my file watching scripts to work with Window's janky file change events :) ~ I'm about to buy another SSD just to install Debian... It's starting to not be worth the headache... Honestly...

**Comment by mike240se** [comment]
i am in the same boat, I use PHPStorm to edit a symfony project and I was hosting the project in windows and accessing it in linux as microsoft suggested but that broke when i upgraded from symfony 3.4 to 4.4.  In Symfony 4.4 it was throwing hundreds of cache errors every page load (slowing things down badly) because it was trying to set linux utime on the cache files and i guess windows doesnt support the same time resolution in its file system or something like that.

**Comment by ElanHasson** [comment]
@fracasula 

> Any ideas?

Yeah, use subst:

From cmd.exe: 
`subst S: \\wsl$\Ubuntu\home\elan\source\repos`

Now to goto your s: drive

![image](https://user-images.githubusercontent.com/234704/80758490-b2412d00-8b03-11ea-9699-831d597934bb.png)

**Comment by abreingan** [comment]
the subst above does not work for me (if the problem is "active" at the time - it just reports path not found. 
Very annoying as I have not had any other major problems

**Comment by pfortin-expertime** [comment]
Thanks a lot @ElanHasson , now I can work with PhpStorm on my WSL2 distro without using FTP connection!

**Comment by Anasme** [comment]
> Thanks a lot @ElanHasson , now I can work with PhpStorm on my WSL2 distro without using FTP connection!

Hello ! I want to achieve the same goal as you, launching my project over wsl2 on phpstorm... 
I tried to subst like ElanHasson said my wsl2 home but cant explore it by explorer.. can you tell me how you did it please?

btw I access S: drive by cmd.

Im on windows 10 pro 19041

**Comment by Anasme** [comment]
> > Thanks a lot @ElanHasson , now I can work with PhpStorm on my WSL2 distro without using FTP connection!
> 
> Hello ! I want to achieve the same goal as you, launching my project over wsl2 on phpstorm...
> I tried to subst like ElanHasson said my wsl2 home but cant explore it by explorer.. can you tell me how you did it please?
> 
> btw I access S: drive by cmd.
> 
> Im on windows 10 pro 19041

Ok sorry for the post, found out I can map my \\wsl$\debian only, If i try to go deeper in folder directory its fail.

Thanks again!

**Comment by ElanHasson** [comment]
Good to hear :)

Elan Hasson
561-445-4667

**Comment by gottfired** [comment]
Same here, tried all the solutions, nothing works. \\wsl$\Ubuntu is unreachable. explorer.exe only works in windows mount points. WSL2 is basically unusable this way.

**Comment by edditor** [comment]
> Same here, tried all the solutions, nothing works. \wsl$\Ubuntu is unreachable. explorer.exe only works in windows mount points. WSL2 is basically unusable this way.

Same for me.

**Comment by onomatopellan** [comment]
@gottfired @edditor Open an elevated Powershell and post the output of these

reg query HKLM\SYSTEM\CurrentControlSet\Control\NetworkProvider /s

reg query HKLM\SYSTEM\CurrentControlSet\Services\p9np /s

reg query HKLM\SYSTEM\CurrentControlSet\Services\p9rdr /s

**Comment by gottfired** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\HwOrder
    ProviderOrder    REG_SZ    P9NP,RDPNP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    P9NP,RDPNP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\ProviderOrder
    LanmanWorkstation    REG_DWORD    0x7d0
    RDPNP    REG_DWORD    0x3e8
    webclient    REG_DWORD    0xbb8
    P9NP    REG_DWORD    0x1f4



HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9np
    Description    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-101
    DisplayName    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-100

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9np\NetworkProvider
    DeviceName    REG_SZ    \Device\P9Rdr
    DisplayName    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-100
    Name    REG_SZ    Plan 9 Network Provider
    ProviderPath    REG_EXPAND_SZ    %SystemRoot%\System32\p9np.dll
    TriggerStartCompleteNotification    REG_BINARY    7510BCA3541EC641
    TriggerStartNotification    REG_BINARY    7508BCA3541EC641
    TriggerStartPrefix    REG_SZ    wsl$


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9rdr
    DependOnService    REG_MULTI_SZ    RDBSS
    Description    REG_SZ    @%SystemRoot%\System32\drivers\p9rdr.sys,-101
    DisplayName    REG_SZ    @%SystemRoot%\System32\drivers\p9rdr.sys,-100
    ErrorControl    REG_DWORD    0x1
    ImagePath    REG_EXPAND_SZ    System32\drivers\p9rdr.sys
    Start    REG_DWORD    0x3
    Type    REG_DWORD    0x1

**Comment by onomatopellan** [comment]
@gottfired No issue here in build 19041 with the same reg entries. 
Can you post the output of `sudo dmesg` in pastebin or a gist?

**Comment by gottfired** [comment]
https://gist.github.com/gottfired/0d5ea06d1c4d083da67e50a4570357c7

**Comment by onomatopellan** [comment]
@gottfired Thanks. I can't see anything wrong there. How about the output of `sudo mount` ?

**Comment by gottfired** [comment]
`/dev/sdb on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
tmpfs on /mnt/wsl type tmpfs (rw,relatime)
tools on /init type 9p (ro,relatime,dirsync,aname=tools;fmask=022,loose,access=client,trans=fd,rfd=6,wfd=6)
none on /dev type devtmpfs (rw,nosuid,relatime,size=6518436k,nr_inodes=1629609,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620,ptmxmode=000)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
D:\ on /mnt/d type 9p (rw,noatime,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)`

**Comment by onomatopellan** [comment]
@gottfired This thread is closed. Better follow #5307. We are waiting for the team to answer there.

**Comment by arthurborgesdev** [comment]
I was having this issue today, but after updating the WSL kernel, it began working again! 

https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by thisismydesign** [comment]
For me the issue turned out to be that via Chocolatey WSL Ubuntu is installed to require admin rights (`choco install wsl2 wsl-ubuntu-1804`). This is also reflected in that the command line is only accessible when running as an admin. I tried running explorer as admin but that didn't help.

It was solved by:
- Navigate to (C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\unzipped) and change the folder permissions to full control for "users"

Afterward:
- I can open WSL terminal without admin privileges
- I can `cd ~ && explorer.exe .`
- I can navigate to `\\wsl$\Ubuntu-18.04` manually from explorer

**Comment by SvenGroot** [comment]
@thisismydesign This is a known issue that was recently fixed. When you install a WSL2 distro from an elevated process, the VHD is owned by the Administrators group rather than your account, so only elevated users can start the VM.

We have recently made a fix that makes sure the VHD is owned by your account even if created when elevated.

**Comment by thisismydesign** [comment]
@SvenGroot thanks a lot. Can you ping me when it's live? Or just let me know which version will contain the fix?

**Comment by hariharan382** [comment]
> Ah, so from File Explorer, browsing to `\\wsl$\Ubuntu-18.04\` gives me error:
> 
> ```
> \\wsl$\Ubuntu-18.04 is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions.
> 
> Attempt to access invalid address.
> ```
> 
> Can't quite tell if this is a permissions issue, or 'invalid address'... any ideas?

i am having the same issue have you solved this issue

**Comment by jepet** [comment]
I too have this problem. I can use an un-elevated powershell to access the mount-point (\\wsl$\Ubuntu-20.04), but explorer.exe doesn't recognize it, and neither does the powershell in elevated mode. Any hint as to how to fix this, or a timeframe for an available hotfix will be greatly appreciated.

**Comment by DanielGoldfarb** [comment]
@ElanHasson 
Regarding https://github.com/microsoft/WSL/issues/4260#issuecomment-622107929

This is what I get when I try it:

    C:\Users\dgold>subst S: \\wsl$\Ubuntu\home
    Path not found - \\wsl$\Ubuntu\home

This is what I see looking regular:

    C:\Users\dgold>dir AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\
     Volume in drive C has no label.
     Volume Serial Number is DA84-E891

     Directory of 
    C:\Users\dgold\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState

    08/12/2020  12:07 AM    <DIR>          .
    08/12/2020  12:07 AM    <DIR>          ..
    08/13/2020  09:56 PM     6,296,698,880 ext4.vhdx
                   1 File(s)  6,296,698,880 bytes
                   2 Dir(s)  358,663,135,232 bytes free

With WSL2 the entire file system is one file (virtual disk).  
Any ideas?  (Your post above seemed promising but didn't work for me;  Am I doing something wrong?)

 Thanks in advance.  --Daniel

**Comment by ElanHasson** [comment]
@DanielGoldfarb be sure `Ubuntu` is the name of your wal2 environment.

**Comment by DanielGoldfarb** [comment]
@ElanHasson 
Elan,  Thanks!   Worked like a charm.  (Although, to get it to work, I had to first delete that bad s: drive i had created yesterday).

    C:\Users\dgold>subst s: /d
    C:\Users\dgold>wsl --list
    Windows Subsystem for Linux Distributions:
    Ubuntu-20.04 (Default)
    C:\Users\dgold>subst s: \\wsl$\Ubuntu-20.04\home\

All the best!  --Daniel

**Comment by jpoles1** [comment]
This issue (or a related one) should really be reopened @benhillis. It's been nearly a year and this is still not working properly.

I've had to resort to creating a .bat file which makes it easier to create a "network" drive to my ubuntu files:

```
subst L: /d
subst L: \\wsl$\<DistroNameHere>\
explorer.exe L:
```

**Comment by manierim** [comment]
Is there any update?

Still experiencing this. Can map a network drive to \\wsl$\Ubuntu and access its contents.

But explorer or any other window executable (launched from Windows or from a WSL prompt) can access \\wsl$\Ubuntu.


Win 1903 build 18362.1139
Ubuntu App 2004.2020.812.0

Ubuntu 20.04.1 LTS (Focal Fossa)
Linux 4.19.128-microsoft-standard x86_64

**Comment by gottfired** [comment]
I know it's not much of a help. But my HD crashed a few weeks ago which forced me to reinstall Windows. Now everything is working fine.

**Comment by saltazaur** [comment]
I had tried solutions listed in this topic, but in my case it occured that I didn't have wsl.config in my Ubuntu, now after adding the file with default settings, I can access Ubuntu from Windows and all problems are solved (`code .` ...)
Info on wsl.conf: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf

**Comment by nikoscvas** [comment]
@saltazaur 's solution worked for me. I had the `wsl.conf` file but `root = /windir/` wasn't there. After I added it, and restarted for good measure, the problem went away.

**Comment by whaaaley** [comment]
It worked for me as well. I added this to my Debian install and I haven't had any issues since. Nice catch. Someone should probably make a new thread to report the missing conf files and reference this issue.

**Comment by CollapsedMetal** [comment]
@saltazaur solution worked for me as well! 

`/etc/wsl.conf` was not there! 
Iv'e copied the one mentioned on [https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf). 
Rebooted and done!

**Comment by Ryuhouji** [comment]
> > fracasula, come at it from the other angle.
> > All of your windows files are accessible from within the linux distro under /mnt/, so just store the files there. That way, both windows and linux has access to them.
> 
> I did not know that was possible, thanks 👍

If you're using wsl2 this will cause a MASSIVE performance penalty. Always edit from inside your distro. If you use your distro with Windows paths, this is going to be very slow. This is NOT a solution, it's not even a good workaround.

**Comment by Ryuhouji** [comment]
I have the same problem. After feature upgrade to 20h2, linux filesystem is inaccessible to windows. VS Code remote works perfectly fine inside the distro. I need to be able to browse my project files for editing things other than code.
I've tried:
Rebooting PC
Rebooting wsl (shutdown/starting it)
Trying to set a new title with -t
explorer.exe . inside a linux path does nothing. The terminal acts as if it is still doing something, nothing happens.
Trying `\\wsl\. . .` causes explorer to hang and do nothing.

**Comment by eusoubrasileiro** [comment]
what worked for me
```
subst s: \\wsl$\Ubuntu-20.04\home\
; run in a admin cmd or powershell
; this makes \\wsl$ work again from explorer
```
Based on above [here](https://github.com/microsoft/WSL/issues/4260#issuecomment-692312532) @jpoles1

**Comment by speller** [comment]
I just hit this issue. I can access Docker Desktop WSL folders but can't access my Ubuntu installation folders:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1829515/149871518-43f510e9-9fdb-403d-888d-8a2e9b1c896e.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1829515/149871552-99631be4-77d6-40d0-b01f-b854c25e9a52.png">

All file exploring tools from Windows hang infinitely connecting to the folder. The distro is accessible from the terminal and works well.

**Comment by NyaMisty** [comment]
Same as @speller , I'm on the fast ring of insider, with WSL kernel version 5.10.81.1

**Comment by feland207** [comment]
For me the solution was to run: `subst S: \\wsl$\Ubuntu-20.04\` from cmd.exe

I got an icon like this in Network locations:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/56425462/160110211-6642848f-3cb5-4027-a072-0f0e34e58510.png">

Properties:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/56425462/160110374-8f528cd2-e47e-4416-ac1c-2af5ed5628cf.png">


Despite the Disconnected Network Drive, when I File Explorer this Drive, I can see the Linux file system from Windows. Happy days:)

Thanks, @ElanHasson !

**Comment by Tewuzij** [comment]
> @fracasula Does simply mapping \\wsl$\Ubuntu-18.04 not work for you? You should be able to do that and then access the folder as Z:\root\Code.
> 
> Is there any reason you have to map the specific folder to a drive?

I think there is, for example to access network files in a specific location without traversing back and forth between directories. See [WSL2 network drive authentication issue](https://superuser.com/questions/1752699/windows-wsl2-network-drive-authentication-issue)

**Comment by Kimi450** [comment]
I was struggling with this issue for a while but today I stopped using the "default" install of Ubuntu that comes with WSL and installed a separate version (Ubuntu 20.04) and I havent encountered this issue on 20.04. Maybe thats the workaround? Install something separately from the store and that wont give you issues?
