### ISSUE TITLE
'ls' shows access denied

### ISSUE THREAD

**Issue by tpu01yzx** [microsoft/WSL#4263]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [版本 10.0.18362.175]

> $ uname -a
> Linux yzx-lab3 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I am running nodejs programs downloaded from https://github.com/sjfkai/grab12306 and https://github.com/rikkertkoppes/json2xls. I modified the js file in Windows with Editplus, and run the program in Ubuntu (WSL) after the codes have been modified. Also the files created in WSL are modified in Windows. There are many operatioins over the same files between WSL and Windows, such as create, modified, read, rename,delete. I cannot remember exact ly the operations sequence. All the operations are done in the directory ~/grab12306.

* What's wrong / what should be happening instead:
At some moment, when "ls -l data" gives many error message. but 'sudo ls -l data' gives the correct information. Here are the outputs. I try to restart WLS by  
`Get-Service LxssManager | Restart-Service`
It does not work.

> $ls data -l
> ls: cannot access 'data/ greater_train_stations.xlsx': Permission denied
> ls: cannot access 'data/greater_station_list.json': Permission denied
> ls: cannot access 'data/greater_station_list.json.bak': Permission denied
> ls: cannot access 'data/greater_station_list.xlsx': Permission denied
> ls: cannot access 'data/greater_train_schedule.xlsx': Permission denied
> ls: cannot access 'data/station_list.json': Permission denied
> ls: cannot access 'data/station_list.xlsx': Permission denied
> ls: cannot access 'data/train_list.json': Permission denied
> ls: cannot access 'data/train_list.xlsx': Permission denied
> ls: cannot access 'data/train_schedule.json': Permission denied
> ls: cannot access 'data/train_schedule.xlsx': Permission denied
> total 0
> -????????? ? ? ? ?            ? ' greater_train_stations.xlsx'
> -????????? ? ? ? ?            ?  greater_station_list.json
> -????????? ? ? ? ?            ?  greater_station_list.json.bak
> -????????? ? ? ? ?            ?  greater_station_list.xlsx
> -????????? ? ? ? ?            ?  greater_train_schedule.xlsx
> -????????? ? ? ? ?            ?  station_list.json
> -????????? ? ? ? ?            ?  station_list.xlsx
> -????????? ? ? ? ?            ?  train_list.json
> -????????? ? ? ? ?            ?  train_list.xlsx
> -????????? ? ? ? ?            ?  train_schedule.json
> -????????? ? ? ? ?            ?  train_schedule.xlsx
> $ ls -l | grep data
> drw-rw-rw- 1 share share     4096 Jul  1 19:42 data
> $ sudo ls data -l
> total 19596
> -rw-r--r-- 1 root  root    112911 Jul  1 19:42 ' greater_train_stations.xlsx'
> -rw-rw-rw- 1 share share     8003 Jun 30 15:09  greater_station_list.json
> -rw-rw-rw- 1 share share     8001 Jun 30 15:09  greater_station_list.json.bak
> -rw-rw-rw- 1 share share    12604 Jun 30 14:34  greater_station_list.xlsx
> -rw-r--r-- 1 root  root    258705 Jun 30 15:39  greater_train_schedule.xlsx
> -rw-rw-rw- 1 share share   498130 Jun 29 23:31  station_list.json
> -rw-rw-rw- 1 share share   137886 Jun 30 13:34  station_list.xlsx
> -rw-rw-rw- 1 share share  1528795 Jun 29 23:31  train_list.json
> -rw-rw-rw- 1 share share   293770 Jun 30 13:34  train_list.xlsx
> -rw-rw-rw- 1 share share 13819391 Jun 30 08:57  train_schedule.json
> -rw-rw-rw- 1 share share  3369094 Jun 30 13:34  train_schedule.xlsx

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
The strace file generated by `strace -o ls.strace -f ls data -l` is in [here](https://gist.github.com/tpu01yzx/d7f23e98a980005be73f129d0aea35d8).

**Comment by mscraigloewen** [comment]
It seems like the permissions on your files were changed. 
If you run the command `sudo chmod -R 777 data` it should fix it. Before you do, please read up on [Linux file permissions](https://www.linux.com/learn/understanding-linux-file-permissions) so you can understand what this command will be doing.

As well, were you using the `\\wsl$\<distroName>\` path to access your files?

**Comment by tpu01yzx** [comment]
Thanks. Your solution works. I thought it is a read permission to list the files in a directory. In fact is an execute permission. Maybe the permissions of direcotry "dat" was changed by accident. 

No. Some project in github.com was used to change the location of the rootfs into "E:\WSL". I just used the explore to manage the files. Anyway, using `\\wsl$\<distroName>\` sounds more reasonable.

**Comment by mscraigloewen** [comment]
Got it! It seems like your issue's resolved, please use the `\\wsl$\<distroName>\` path to access your Linux files in the future and you should be good to go.
