### ISSUE TITLE
wsl2 and vmware workstation

### ISSUE THREAD

**Issue by silverqx** [microsoft/WSL#4264]
hi, wsl2 is behind doors and want to ask, how it will be with vmware workstation, is true that wsl2 use hyper-v under the hood? I'm asking because I'm heavily using both of these technologies and also know that vmware workstation doesn't work if hyper-v is enabled.

thank you for reply

**Comment by onomatopellan** [comment]
https://twitter.com/benhillis/status/1146078266630950913

**Comment by silverqx** [comment]
Pleasant to hear something like this, now I'm hoping that it's true 😃, because I didn't find any related issue here.

**Comment by mscraigloewen** [comment]
[Here's our answer from our FAQ page](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox). In short this is something that we are looking into resolving!

**Comment by silverqx** [comment]
thx, think that answered my question.

**Comment by thz** [comment]
https://techcommunity.microsoft.com/t5/Virtualization/VMware-Workstation-and-Hyper-V-Working-Together/ba-p/825831

**Comment by mdowais** [comment]
A Stable Release

https://blogs.vmware.com/workstation/2020/05/vmware-workstation-now-supports-hyper-v-mode.html

**Comment by jayunit100** [comment]
ahhh so this is solved now?

**Comment by mdowais** [comment]
> ahhh so this is solved now?

Yupp!! Now go fish!!
