### ISSUE TITLE
WSL 2 cat /proc/cpuinfo shows only 0-7 on 12 logical unit cpu

### ISSUE THREAD

**Issue by raiscan** [microsoft/WSL#4266]
* Your Windows build number: 10.0.18922.1000

* What you're doing and what's happening:  when running "cat /proc/cpuinfo" in WSL2 or running "htop", I am seeing 8 logical cpus (0-7), whereas I have a 6-core 12 logical unit processor. WSL does not have this issue

* What's wrong / what should be happening instead: WSL2 virtual machines should have the same number of logical processors as the host machine. WSL is not affected.

**Comment by Librazy** [comment]
maybe #4137

**Comment by raiscan** [comment]
Seems likely based on the comment history. Apologies for the dupe!

**Comment by benhillis** [comment]
No problem, thanks for filing.
