### ISSUE TITLE
Ubuntu unresponsive when restarting. Similar to #4047, #2352

### ISSUE THREAD

**Issue by geschaftsreise** [microsoft/WSL#4267]
Microsoft Windows [Version 10.0.17763.557]

#restart windows
#begin Ubuntu App successfully, with the following commands entered into bash environment

ssh user@host
exit

#close ubuntu window
#attempt to start ubuntu window shows blank black screen with no command prompt
#attempt to restart lxssmanager results in service hanging at 'stopping'

#log files attached below

#note that some similar issues have implicated BitDefender. This issues replicates even with Bitdefender shut down.

[lxcore_logs.zip](https://github.com/microsoft/WSL/files/3357063/lxcore_logs.zip)

**Comment by benhillis** [comment]
Thanks for filing! I have been trying to reproduce an issue with the service stopping, it seems to have to do with COM rundown.  Unfortunately I'm not seeing the hang when issuing the above commands.  Is there any additional setup I need to do before running this?

**Comment by geschaftsreise** [comment]
No other manual steps.

Fresh restart, open ubuntu, ssh user@host, exit ssh, close window.
Try to restart ubuntu fails.

Any ssh command that I try kills it once I close the ubuntu window, otherwise it's stable for hours, and only becomes unresponsive once it's closed.

Thanks for working on this, I use it all day every day and it's been super helpful!

**Comment by bpulliam** [comment]
If you still this, please file a new issue since much has changed in WSL.
