### ISSUE TITLE
WSL2 Unable to start Ubuntu 18.04 distro after receiving read-only file system error

### ISSUE THREAD

**Issue by spoiledsport** [microsoft/WSL#4269]
* Your Windows build number:  Microsoft Windows [Version 10.0.18922.1000]

* I am using ubuntu 18.04 to do a Android X86 build. I setup the distro and proceeded to install all dependency packages. The I started the build. Things were going really well (for a change). It was really late and I disable power management so the build could be completed by the time I woke. I went to sleep. When I woke up, the following error was in the terminal window.

06:41:21 Trace write error: write out/build.trace.gz: read-only file system
06:41:21 Trace write error: write out/build.trace.gz: read-only file system
06:41:21 Trace write error: write out/build.trace.gz: read-only file system
06:41:21 Trace write error: write out/build.trace.gz: read-only file system -- this repeated forever
06:41:21 Error closing trace writer: write out/build.trace.gz: read-only file system

#### failed to build some targets (03:14:41 (hh:mm:ss)) ####

I then tried to re-start the build. 
$ m -j4 iso_img
rm: cannot remove '/home/<myusername>/android-x86/out/.soong_ui.trace': Read-only file system

I tried to see space used
$ df
-bash: /bin/df: Input/output error

Tried to see what was reported by strace
$ strace ls
-bash: /usr/bin/strace: Input/output error

I decided to logout and start the whole thing again
$ exit
logout
-bash: /home/<myusername>/.bash_logout: Input/output error

* That is when things really went south
Now I can't start the distro (surprise, surprise)
When I run ubuntu1804.exe, nothing happens

* For WSL launch issues, please [collect detailed logs)
[lxcore_user.zip](https://github.com/microsoft/WSL/files/3358443/lxcore_user.zip)

**Comment by benhillis** [comment]
@spoiledsport - Would it be possible to install a second WSL2 distribuiton, run "sudo dmesg -w", then launch your Ubuntu1804 distro and see if there are any errors printed to dmesg?

**Comment by 0xabu** [comment]
FWIW I saw the same symptoms (EROFS errors followed by everything going haywire) when running out of disk space on C:, where the WSL VHD lives. Stopping the WSL VM, freeing up some space, and then restarting allowed the VHD to keep growing and the system recovered.
