### ISSUE TITLE
alpine chroot install script fails with error 255

### ISSUE THREAD

**Issue by simplejackcoder** [microsoft/WSL#4271]
https://github.com/alpinelinux/alpine-chroot-install

I ran this script on my Windows Redstone 5 client machine and server machine.

Both of them fail in the post init script phase.

The host WSL distro was 18.04 Ubuntu LTS which has the latest qemu so it shouldn't be the whole instruction code 384 problem.

**Comment by therealkenc** [comment]
Tagged need-repro, but note actually demonstrating the diverge would not be for the faint of heart. Constructively, assuming that 255 error (whatever it is) is coming from QEMU, you would get better feedback in a QEMU forum, and then (very hypothetically) work your way back from there.
