### ISSUE TITLE
openSUSE Leap 15-1 fails to install in WSL1/WSL2

### ISSUE THREAD

**Issue by seritools** [microsoft/WSL#4272]
* Your Windows build number:  18932

* What you're doing and what's happening: 

WSL1:

- Trying to install openSUSE Leap 15-1 via Windows Store
- Clicking "Launch"
- "Installing, this may take a few minutes..."
- Asks for UNIX user name, enter it
- Get spammed with "The system cannot find the file specified"

WSL2:

- Installation fails with 0x80071772 (seems encryption related)

* What's wrong / what should be happening instead:

The app files seem to be created encrypted in the Program Files/WindowsApps folder:

![image](https://user-images.githubusercontent.com/5844066/60684635-318fb100-9e9f-11e9-93a0-248c1486a025.png)

After pressing "Launch", the folders in my LocalState folder are marked as encrypted as well:

![image](https://user-images.githubusercontent.com/5844066/60684814-20936f80-9ea0-11e9-985a-89a8b098f75e.png)

Compare that to Ubuntu, for example:

WindowsApps:

![image](https://user-images.githubusercontent.com/5844066/60684654-53893380-9e9f-11e9-896e-d9c93ed3930b.png)

LocalState after (successful) install:

![image](https://user-images.githubusercontent.com/5844066/60684880-6cdeaf80-9ea0-11e9-9816-8e4f67ecbe1a.png)

It seems this may be related to #4103, however the files don't seem to be compressed, but encrypted instead?

**Comment by NotTheDr01ds** [comment]
Same issue - Windows Build 18362 here with WSL1.  I have Ubuntu 16.4 and 18.4 installed, but that shouldn't matter, I wouldn't think.

**Comment by lemmy04** [comment]
still happening with wsl2 on build 18363.535. Any chance to get that fixed?

**Comment by benhillis** [comment]
@lemmy04 WSL2 was first available in 18917, you're still running WSL1.

**Comment by lemmy04** [comment]
> @lemmy04 WSL2 was first available in 18917, you're still running WSL1.

I'm on the latest windows 10 build 1909, which according to the microsoft docs should be running WSL2. At least I have a wsl command which i thought means it's wsl2 and not wsl1...

**Comment by therealkenc** [comment]
Confirmed here. This is on 19023, `--set-default-version` set to 2. Also tried 19555 before rolling back. I am not 100% convinced this is limited to OpenSUSE, but not willing to clobber my Ubuntu installs to find out.

![image](https://user-images.githubusercontent.com/7049700/73676780-d35fc200-4669-11ea-912e-7896e6a5bedd.png)

**Comment by nevgeniev** [comment]
still doesn't work with 2004 release

**Comment by bpulliam** [comment]
@crramirez has a good workaround until the solution is available: make sure your distros install on the system drive to ensure that they are not encrypted.  Closing this issue and marking as workaround-available and fixinbound.

**Comment by zhuziyi1989** [comment]
我的20.04版本也存在这个问题，于是我下载了18.04进行安装，最后18.04成功安装，这个时候我打开之前的20.04，居然没有提示找不到路径的错误了。

This problem also exists in my version 20.04, so I downloaded 18.04 for installation. Finally, 18.04 was successfully installed. At this time, I opened the previous version 20.04 without prompting the error that the path could not be found.
