### ISSUE TITLE
wsl --set-default-version 2 err:Invalid command line option

### ISSUE THREAD

**Issue by darkread** [microsoft/WSL#4280]
I run command in powershell as adminsitrator:
```powershell
>Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform 
Path          :
Online        : True
RestartNeeded : False

>wsl --set-default-version 2
命令行选项无效: --set-default-version
版权所有 (c) Microsoft Corporation。保留所有权利。
用法: wsl.exe [参数] [选项...] [CommandLine]
....
```
"命令行选项无效: --set-default-version" means: Invalid command line option -set-default-version.
Have I make a mistake?

**Comment by benhillis** [comment]
What Windows build?

**Comment by kesadae11** [comment]
I have this same problem. (Win10 1903)
Is there any solution? 

Thank you in advance!

**Comment by benhillis** [comment]
WSL2 is currently only available via the Windows Insider Program.

**Comment by Oneiroi** [comment]
@benhillis it would have been useful to link to some documentation on this issue, esp as this is one of the firstpage results when searching for this issue.

I've followed this documentation on getting WSL2 operational: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

My windows build is too: 1903, I have subscribed to Insider preview builds.

```
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform                       

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> wsl --set-version Distro 2
Invalid command line option: --set-version
```

I too face the issue of despite following documentation available completely, WSL install does not appear to be updated to version 2 or the command line arguments have been changed and not reflected in the output of `--help`

**Comment by Oneiroi** [comment]
*note* for future readers the linked installation guides notes: you'll need to be running Windows 10 build 18917 or higher to use WSL 2` thus your Insider Programme "Ring" needs to be changed from "Default" to "Fast" (Windows Insider Program Settings)

_however_ this comes with associated risks and you should consider these before doing so, WSL2 is not at the time of writing on earlier builds (afaict) and requires >= 18917

**Comment by mscraigloewen** [comment]
@Oneiroi on the [wsl 2 install documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) it states that you need to be running build 18917 or higher, and also gives the solution to the error: `Invalid command line option` that you will need to upgrade.

Does this address your feedback?

**Comment by DChistyakov** [comment]
> @Oneiroi on the [wsl 2 install documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) it states that you need to be running build 18917 or higher, and also gives the solution to the error: `Invalid command line option` that you will need to upgrade.
> 
> Does this address your feedback?

He use 1903 that is higher than 18917, as he wrote above. I have the same problem with build 1903, investigating.

**Comment by DChistyakov** [comment]
Well.. I solved. In my case windows installated 1903 update and windows update tool confirmed it, but! if i call system information than i see that my current build is 10.0.18362 Build 18362. I sovled it by downloading "Windows 10 Media Creation Tool" from https://www.comss.ru/download/page.php?id=3271
it updated my build to 1903 and all cmds now available.

Alternate options as i found is: 
https://www.groovypost.com/howto/manually-install-windows-10-1903-may-2019-update-now/

Good luck!

**Comment by benhillis** [comment]
1903 is not higher than 18917. 1903 is the release, 18362 is the version.

**Comment by DChistyakov** [comment]
> 1903 is not higher than 18917. 1903 is the release, 18362 is the version.
https://blogs.windows.com/windowsexperience/2019/06/12/announcing-windows-10-insider-preview-build-18917/

**Comment by Msadr471** [comment]
Hi...
If I install WSL1 on my windows and work with it, install some app ... , at least when I change wsl1 to wsl2 my distro work without a problem??

**Comment by kesadae11** [comment]
Hi @Msadr471 
In a theory yes, but in my opinion, better if you make a backup before upgrade, as always...
Docs.: https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by JonRobertson** [comment]
Someone should update Microsoft Store. It specifically states to go to 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

Microsoft Store should be "intelligent" enough not to tell me to go there if my current Windows build doesn't support it. I didn't even notice the text at the time that states I needed to have 18917. I incorrectly assumed that Microsoft Store would not have told me to install something that I didn't need to install.

**Comment by tatosjb** [comment]
The https://docs.microsoft.com/en-us/windows/wsl/wsl2-install is off, returning 404

**Comment by Shogobg** [comment]
> The https://docs.microsoft.com/en-us/windows/wsl/wsl2-install is off, returning 404

Works for me

**Comment by tatosjb** [comment]
@Shogobg now works for me as well, it'll probably was the 7 day time lapse between my and yours try

**Comment by 13ROY** [comment]
The same happened to me, did the update via the Windows Update yet the winver version was referencing the previous version. Downloaded and updated via the Windows Update site and this resolved my issues.

**Comment by cybergavin** [comment]
Had the same issue on Windows 10 (OS Build 18363.1016). Summarized steps to get WSL 2 working on this Windows 10 version at https://cybergav.in/2020/08/28/wsl2-on-windows-10/
