### ISSUE TITLE
why cannot remote access app installed in wsl like redis

### ISSUE THREAD

**Issue by JimmyGitHub16** [microsoft/WSL#4283]
when I installed redis in wsl with ubutu 18.0.4, why I cannot access the redis from another remote computer?
For example: if i installed redis in a linux pc with ip address 192.168.8.2, then, i can access remotely by using the 192.168.8.2:6379, but if it install in wsl, the connection failed? Why? if can
connect, how?

H
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by mscraigloewen** [comment]
This is most likely due to a firewwall restriction. 

Please make sure to go to `Windows Firewall with Advanced Security`->`New Rule`->`Port`->Specify which port you'd like opened so from your example `6379`->`Allow the connection`->Pick which level you'd like it applied to->Give the rule a name

And then after that it should be accessible.
