### ISSUE TITLE
CONFIG_SECURITY_YAMA not set

### ISSUE THREAD

**Issue by therealkenc** [microsoft/WSL#4286]
```
$ cat /proc/version
Linux version 4.19.43-microsoft-standard (oe-user@oe-host) (gcc version 7.3.0 (GCC)) #1 SMP Mon May 20 19:35:22 UTC 2019
$ cd /mnt/c && cmd.exe /c systeminfo | grep "^OS Version"
OS Version:                10.0.18932 N/A Build 18932
$ lsb_release -d
Description:    Ubuntu 18.04.2 LTS
$ sudo cat /proc/config.gz | gunzip - | grep YAMA
# CONFIG_SECURITY_YAMA is not set
$ cat /proc/sys/kernel/yama/ptrace_scope 
cat: /proc/sys/kernel/yama/ptrace_scope: No such file or directory
```

[Because:](https://github.com/microsoft/WSL/issues/4255#issuecomment-509397343)

![image](https://user-images.githubusercontent.com/7049700/60857386-331ee900-a1bf-11e9-8689-ef2cbf1eac4c.png)

**Comment by Biswa96** [comment]
I didn't see those errors in latest VScode and remote WSL extension.

**Comment by therealkenc** [comment]
> I didn't see those errors in latest VScode and remote WSL extension.

Appreciate you giving it a whirl. Haven't tried since I posted last month. But the repro remains:

![image](https://user-images.githubusercontent.com/7049700/62567073-4d3ffb80-b83f-11e9-84c7-e8bfdc629b14.png)

Which is a diverge from what the Ubuntu userspace being shipped in the MSFT Store expects. It expects `=y`. Or, see, Canonical wouldn't ship their kernel with `=y`.

**Comment by Biswa96** [comment]
I mean the errors in the second screenshot. VSCode remote WSL extension works as usual without any issue.

**Comment by therealkenc** [comment]
>  I mean the errors in the second screenshot.

Ahh. It's unlikely you reproduced that screencap. Because, it involves getting a `strace(1)` out of vscode's remote service. 

> VSCode remote WSL extension works as usual without any issue.

It doesn't work, if you hit #4255 aka  #4175 aka #3886. Which you (and me) don't.

**Comment by therealkenc** [comment]
Since I'm here and didn't mention it explicitly in the OP, this one is rare oddball regress from WSL1. Ref three-digit #121 ([message](https://github.com/microsoft/WSL/issues/121#issuecomment-373748896)).

**Comment by acepaceNS** [comment]
Still exists. Not sure how to workaround to debug processes

**Comment by MisterAero** [comment]
any solution?
