### ISSUE TITLE
cygstart equivalent

### ISSUE THREAD

**Issue by cup** [microsoft/WSL#4287]
With Cygwin, cygstart wraps the ShellExecuteW function

https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew

cmd.exe has similar option with `start` and PowerShell with `Start-Process`

it seems WSL has no such option

**Comment by therealkenc** [comment]
```
$ cat << EOF > wslstart
#!/usr/bin/env sh
cmd.exe /c start \$@
EOF
$ chmod 755 ./wslstart
$ ./wslstart https://github.com/microsoft/WSL/issues/4287
```

**Comment by cup** [comment]
@therealkenc no, thats not a good idea as it fails with space or ampersand:

~~~
http://example.com?aa bb&cc
~~~

**Comment by therealkenc** [comment]
Alright.
```
cat << EOF > wslstart
#/usr/bin/env sh
powershell.exe -command \& {Start-Process \'\`echo \$@\`\'}
EOF
$ chmod 755 ./wslstart
$ ./wslstart 'http://example.com?aa bb&cc'
```

Although that URI mostly has what is coming. Ref #3832 ([message](https://github.com/Microsoft/WSL/issues/3832)) with open LZ #2835.

**Comment by 0xbadfca11** [comment]
```sh
$ ./wslstart iexplore 'http://example.com?aa bb&cc'
```
Start-Process method can not use any arguments. And ``-ArgumentList`` doesn't match the shell's idiom.
After all it is better to use ``cmd.exe /c start``?
```sh
cmd.exe /c start '' "$@"
```

**Comment by therealkenc** [comment]
I was hoping you'd show.

> And -ArgumentList doesn't match the shell's idiom.

Maybe...
```
#/usr/bin/env sh
al=$(echo "${@:2}" | tr ' ' ,)
if [ $al ]
then
  powershell.exe -command \& {Start-Process \'$(echo $1)\' -ArgumentList $al}
else
  powershell.exe -command \& {Start-Process \'$(echo $1)\'}
fi
```

> After all it is better to use cmd.exe /c start?

Yeah. Probably after all....
```
#/usr/bin/env sh
cmd.exe /c start '' "${@//&/^&}"
```

**Comment by therealkenc** [comment]
PS: I [take back](https://github.com/Microsoft/WSL/issues/648#issuecomment-299703872) that there's no use case for Linux-native Chrome/Firefox on WSL. Its so all the `bash` and `python` scripts in the wild that call [`xdg-open(1)`](http://manpages.ubuntu.com/manpages/xenial/man1/xdg-open.1.html) work out of the box......

**Comment by cup** [comment]
Is this really what you all are suggesting? A hacky shell script? A standalone tool would be better, like cygstart. that way dont have to worry about any drama with `cmd.exe` or powershell issues.

i was hoping WSL offered something like `open` or `xdg-open`, but failing that i found this workaround:

~~~sh
rundll32 url,OpenURL "http://example.com?aa bb&cc"
~~~

**Comment by therealkenc** [comment]
> Is this really what you all are suggesting? A hacky shell script?

Your hacky script only launches URLs. 

```
#/usr/bin/env sh
rundll32.exe url,OpenURL "$@"
```

Which wasn't your OP ask. Your OP ask was for `ShellExecute()`. So, yes.

**Comment by cup** [comment]
@therealkenc did you actually test that? or are you just assuming after reading the function name?

Works for me with files and URLs

**Comment by therealkenc** [comment]
>  or are you just assuming after reading the function name?

No; I need not assume anything. Because I know what ShellExecuteW() does. And way rundll32 takes parameters.

**Comment by cup** [comment]
@therealkenc perhaps you should actually test it before talking further

it works with URLs and local files

**Comment by therealkenc** [comment]
> it works with URLs and local files

Yes. Yes it does. Never said it didn't work with both files and URLs. Never even implied otherwise. What I said was I know what `ShellExecuteW()` does. And that I know why `rundll32` takes parameters.

But happy you found an answer to your question either way.

**Comment by cup** [comment]
> Your hacky script only launches URLs.

**Comment by therealkenc** [comment]
> I am confused because previously you said this:

`C:\Windows\System32\url.dll` will eat path strings and does not insists on the `file:` prefix. But you already know that, as does everyone less confused. At any rate, happy to hear you found a solution to your use case. Even happier that 0xbadfca11 stepped up with a solution to pushing WSL interop args into `start`, since it has been a common question and now there is a good answer.

**Comment by cup** [comment]
> will eat path strings and does not insists on the `file:` prefix. But you already 
> know that, as does everyone less confused

i am flattered - but maybe i am not that smart

as i dont know what "eat path strings" mean

thank you sir

**Comment by therealkenc** [comment]
> as i dont know what "eat path strings" mean

Apologies for being terse. That on me. `url.dll` is not strict about URL syntax. It will parse (eat) the path component string of a `file:` scheme without the prefix. It's all good.

![image](https://user-images.githubusercontent.com/7049700/60896072-8b370900-a21a-11e9-91d5-9ad74e9c4900.png)

**Comment by cup** [comment]
restoring deleted message:

> Apologies for being terse. That on me. `url.dll` is not strict about URL
> syntax. It will parse (eat) the path component string of a `file:` scheme
> without the prefix. It's all good.
>
> https://user-images.githubusercontent.com/7049700/60896072-8b370900-a21a-11e9-91d5-9ad74e9c4900.png

i guess i am a dummy, as I am still not understanding

do you have some example path that gets mangled by `url.dll`? i know my
workaround is not ideal, but i havent seen any parsing issues myself yet like
i experienced with `cmd start`.
