### ISSUE TITLE
WSL2 fails to start docker container based on Centos 6

### ISSUE THREAD

**Issue by tst-rwildes** [microsoft/WSL#4290]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
C:\Users\rwildes>ver

Microsoft Windows [Version 10.0.18922.1000]
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
After installing docker into a WSL 2 instance running Ubuntu 18 containers running centos 6 fail to start with exit code of `139`.  To duplicate the issue after installing docker run: `docker run -it --rm centos:6 sh`
* What's wrong / what should be happening instead:
The docker container should start and enter into the containers shell.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/tst-rwildes/78efc9bb9b86edd8760fa5a4103b24dc

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by tst-rwildes** [comment]
Moved to Version 10.0.19013.1000 and still have the same issue...

**Comment by 5ym** [comment]
I can't even boot centos5 based image.

**Comment by squeaky-pl** [comment]
I believe this is a duplicate of: https://github.com/microsoft/WSL/issues/4694

**Comment by tst-rwildes** [comment]
The workaround in #4694 seems to fix my issue: https://github.com/microsoft/WSL/issues/4694#issuecomment-556095344

**Comment by 5ym** [comment]
me too
I think it ’s okay to remove this issue
