### ISSUE TITLE
WSL2 fails to start after upgrade to insider build 18932

### ISSUE THREAD

**Issue by mithunshanbhag** [microsoft/WSL#4292]
* **Your Windows build number:**  10.0.18932.1000

* **What you're doing and what's happening:**  
  - I already had WSL2 enabled and working on previous windows insider build.
  - Upgraded to latest insider window (18932) after it became available.
  - Now I can't launch any of my distros after the upgrade. WSL complains that `virtual machine platform` is not enabled even though it actually is. 
  - Re-enabling the `virtual machine platform` feature too didn't work. 
  - Please see attached screenshot below: 
![image](https://user-images.githubusercontent.com/2327905/60971212-448ffe80-a341-11e9-9280-79d07a5714fa.png)

* **What's wrong / what should be happening instead:** If I type in `wsl` or my distro names on the command line, then the distro should start.  However it doesn't.

* **ETL logs zipped and attached below**:
[wsl-etl-logs.zip](https://github.com/microsoft/WSL/files/3377592/wsl-etl-logs.zip)

Please let me know if any additional details are needed.

**Comment by mscraigloewen** [comment]
Can you please check in your machine's BIOS that you have virtualization enabled? It should be somewhere in your CPU settings.

**Comment by adamkenway007** [comment]
i have same problem,but my all virtualization setting already enabled

**Comment by alekseymvt** [comment]
Excuse me, I don't know, it is the same problem or not, but the VirtualBox no longer works. (WSL 1 works).
Your Windows build number: 18936.1000
![изображение](https://user-images.githubusercontent.com/22454101/61113093-09ebaa80-a496-11e9-9a74-78dfc30b5868.png)

**Comment by mscraigloewen** [comment]
You cannot run Virtual Box when Hyper-V architecture is present. You can learn more about this and WSL [on our FAQ page for WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox).

**Comment by mithunshanbhag** [comment]
> Can you please check in your machine's BIOS that you have virtualization enabled? It should be somewhere in your CPU settings.

So weirdly enough, this issue seems to have somehow resolved/fixed itself. 

I'm on windows10 on a macbook. I rebooted into macOS, then rebooted back into windowsOS. Somehow this has fixed the issue (your guess is as good as mine). 🤷‍♂ 

Am able to use WSL2 now without issues. 

Will close this github issue for now. Will reactivate if it repro'es again.
