### ISSUE TITLE
WSL - repeated compilation with gcc causes bluescreen 

### ISSUE THREAD

**Issue by adityaka** [microsoft/WSL#4294]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.829]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

for i in $(seq 1 50); do gcc -o <progname> file.c; done

* What's wrong / what should be happening instead:
repeated compilation with an IDE or vim plugins or even a simple bash scripts causes bluescreen.

* Stack Trace of the failing command, if applicable:  (If `some_command` is failing, then run `
Microsoft (R) Windows Debugger Version 10.0.18914.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\kapura1\Documents\src\JIRAs\dumps\tba1.DMP]
Kernel Bitmap Dump File: Full address space is available

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\Users\kapura1\Documents\src\JIRAs\dumps\symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*C:\Users\kapura1\Documents\src\JIRAs\dumps\symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
Windows 10 Kernel Version 17134 MP (8 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 17134.1.amd64fre.rs4_release.180410-1804
Machine Name:
Kernel base = 0xfffff801`a2017000 PsLoadedModuleList = 0xfffff801`a23c4150
Debug session time: Wed Jun 12 21:14:56.263 2019 (UTC + 5:30)
System Uptime: 1 days 19:28:50.192
Loading Kernel Symbols
...............................................................
................................................................
................................................................
..............................................................
Loading User Symbols
PEB address is NULL !
Loading unloaded module list
..................................................
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff801`a21c1ab0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffffe87`7feb4e70=0000000000000139
4: kd> kvn
 # Child-SP          RetAddr           : Args to Child                                                           : Call Site
00 fffffe87`7feb4e68 fffff801`a21d2669 : 00000000`00000139 00000000`00000003 fffffe87`7feb5190 fffffe87`7feb50e8 : nt!KeBugCheckEx
01 fffffe87`7feb4e70 fffff801`a21d2a10 : 00000000`00000000 ffff8002`949a4c20 ffff8002`b73dd6a0 00000000`00000000 : nt!KiBugCheckDispatch+0x69
02 fffffe87`7feb4fb0 fffff801`a21d101f : ffffdd81`1a11e560 ffff8002`9411f000 00000000`00000000 00000000`00000000 : nt!KiFastFailDispatch+0xd0
03 fffffe87`7feb5190 fffff801`a2303427 : ffffdd81`1a11e570 ffffdd81`1a11e3c0 ffffdd81`1a11d280 00000000`00000000 : nt!KiRaiseSecurityCheckFailure+0x2df (TrapFrame @ fffffe87`7feb5190)
04 fffffe87`7feb5320 fffff808`b249f602 : ffffb488`00000003 00000000`00001000 ffffb488`6156784c fffffe87`00000000 : nt!ExAllocatePoolWithTag+0x1697
05 fffffe87`7feb5410 fffff808`b249f335 : ffffb488`458fe420 ffffb488`4b1af0c8 00000000`00000000 fffffe87`7feb55d8 : LXCORE!LxpMiAllocateVad+0x46
06 fffffe87`7feb5440 fffff808`b24791a9 : fffffe87`7feb5860 00000000`00000000 00000000`00000004 00000000`00001000 : LXCORE!LxpMmSupportCloneComplete+0xa5
07 fffffe87`7feb54d0 fffff808`b249505c : ffff8002`b90ea400 ffffffff`8000ec40 00000000`00000000 00000000`00000000 : LXCORE!LxpProcessCreate+0x3cd
08 fffffe87`7feb5580 fffff808`b248ff2f : 00000000`00000000 00000000`00000000 00000000`00000000 fffffe87`7feb5688 : LXCORE!LxpThreadGroupFork+0xc0
09 fffffe87`7feb5650 fffff808`b248409b : 00007f0f`40cb09d0 ffffb488`64afa010 00007f0f`40cb09d0 00000000`00000000 : LXCORE!LxpThreadClone+0x27b
0a fffffe87`7feb5830 fffff808`b2483218 : 00000000`00000000 fffffe87`7feb5939 fffff808`b242b150 ffff8002`ab2c0700 : LXCORE!LxpSyscall_CLONE+0x6b
0b fffffe87`7feb58e0 fffff808`b249e691 : fffffe87`7feb5a00 fffffe87`7feb5a00 00000000`00000000 00000000`01200011 : LXCORE!LxpSysDispatch+0xf8
0c fffffe87`7feb59a0 fffff801`a279669f : 00007f10`24000020 00000000`00000060 00007f10`24010270 00000000`00000160 : LXCORE!PicoSystemCallDispatch+0x11
0d fffffe87`7feb59d0 fffff801`a21d1f38 : fffffe87`7feb5a00 00000000`00000014 00007f10`24000080 00000000`00000000 : nt!PsPicoSystemCallDispatch+0x1f
0e fffffe87`7feb5a00 00007f10`74694b1c : 00007f10`7499e968 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 : nt!KiSystemServiceUser+0x76 (TrapFrame @ fffffe87`7feb5a00)
0f 00007f0f`40cae340 00007f10`7499e968 : 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 : 0x00007f10`74694b1c
10 00007f0f`40cae348 00000000`00000000 : 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 00000000`00000000 : 0x00007f10`7499e968
4: kd> .trap fffffe87`7feb5190
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=ffffb4886d4a2930 rbx=0000000000000000 rcx=0000000000000003
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=fffff801a2303427 rsp=fffffe877feb5320 rbp=fffffe877feb53a9
 r8=0000000000000000  r9=0000000000000001 r10=0000000000000001
r11=0000000000000002 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na pe cy
nt!ExAllocatePoolWithTag+0x1697:
fffff801`a2303427 cd29            int     29h
4: kd> kvn
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr           : Args to Child                                                           : Call Site
00 fffffe87`7feb5320 fffff808`b249f602 : ffffb488`00000003 00000000`00001000 ffffb488`6156784c fffffe87`00000000 : nt!ExAllocatePoolWithTag+0x1697
01 fffffe87`7feb5410 fffff808`b249f335 : ffffb488`458fe420 ffffb488`4b1af0c8 00000000`00000000 fffffe87`7feb55d8 : LXCORE!LxpMiAllocateVad+0x46
02 fffffe87`7feb5440 fffff808`b24791a9 : fffffe87`7feb5860 00000000`00000000 00000000`00000004 00000000`00001000 : LXCORE!LxpMmSupportCloneComplete+0xa5
03 fffffe87`7feb54d0 fffff808`b249505c : ffff8002`b90ea400 ffffffff`8000ec40 00000000`00000000 00000000`00000000 : LXCORE!LxpProcessCreate+0x3cd
04 fffffe87`7feb5580 fffff808`b248ff2f : 00000000`00000000 00000000`00000000 00000000`00000000 fffffe87`7feb5688 : LXCORE!LxpThreadGroupFork+0xc0
05 fffffe87`7feb5650 fffff808`b248409b : 00007f0f`40cb09d0 ffffb488`64afa010 00007f0f`40cb09d0 00000000`00000000 : LXCORE!LxpThreadClone+0x27b
06 fffffe87`7feb5830 fffff808`b2483218 : 00000000`00000000 fffffe87`7feb5939 fffff808`b242b150 ffff8002`ab2c0700 : LXCORE!LxpSyscall_CLONE+0x6b
07 fffffe87`7feb58e0 fffff808`b249e691 : fffffe87`7feb5a00 fffffe87`7feb5a00 00000000`00000000 00000000`01200011 : LXCORE!LxpSysDispatch+0xf8
08 fffffe87`7feb59a0 fffff801`a279669f : 00007f10`24000020 00000000`00000060 00007f10`24010270 00000000`00000160 : LXCORE!PicoSystemCallDispatch+0x11
09 fffffe87`7feb59d0 fffff801`a21d1f38 : fffffe87`7feb5a00 00000000`00000014 00007f10`24000080 00000000`00000000 : nt!PsPicoSystemCallDispatch+0x1f
0a fffffe87`7feb5a00 00007f10`74694b1c : 00007f10`7499e968 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 : nt!KiSystemServiceUser+0x76 (TrapFrame @ fffffe87`7feb5a00)
0b 00007f0f`40cae340 00007f10`7499e968 : 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 : 0x00007f10`74694b1c
0c 00007f0f`40cae348 00000000`00000000 : 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 00000000`00000000 : 0x00007f10`7499e968
4: kd> !thread
THREAD ffff8002b73dd380  Cid 10a4.758c  Teb: 0000000000000000 Win32Thread: 0000000000000000 RUNNING on processor 4
Not impersonating
DeviceMap                 ffffb488469da310
Owning Process            ffff8002ab2c0200       Image:         java
Attached Process          N/A            Image:         N/A
Wait Start TickCount      10017932       Ticks: 0
Context Switch Count      317            IdealProcessor: 4             
UserTime                  00:00:00.000
KernelTime                00:00:01.515
Win32 Start Address 0x00007f10746d1881
Stack Init fffffe877feb5b90 Current fffffe877feb5010
Base fffffe877feb6000 Limit fffffe877feaf000 Call 0000000000000000
Priority 8 BasePriority 8 PriorityDecrement 0 IoPriority 2 PagePriority 5
Child-SP          RetAddr           : Args to Child                                                           : Call Site
fffffe87`7feb4e68 fffff801`a21d2669 : 00000000`00000139 00000000`00000003 fffffe87`7feb5190 fffffe87`7feb50e8 : nt!KeBugCheckEx
fffffe87`7feb4e70 fffff801`a21d2a10 : 00000000`00000000 ffff8002`949a4c20 ffff8002`b73dd6a0 00000000`00000000 : nt!KiBugCheckDispatch+0x69
fffffe87`7feb4fb0 fffff801`a21d101f : ffffdd81`1a11e560 ffff8002`9411f000 00000000`00000000 00000000`00000000 : nt!KiFastFailDispatch+0xd0
fffffe87`7feb5190 fffff801`a2303427 : ffffdd81`1a11e570 ffffdd81`1a11e3c0 ffffdd81`1a11d280 00000000`00000000 : nt!KiRaiseSecurityCheckFailure+0x2df (TrapFrame @ fffffe87`7feb5190)
fffffe87`7feb5320 fffff808`b249f602 : ffffb488`00000003 00000000`00001000 ffffb488`6156784c fffffe87`00000000 : nt!ExAllocatePoolWithTag+0x1697
fffffe87`7feb5410 fffff808`b249f335 : ffffb488`458fe420 ffffb488`4b1af0c8 00000000`00000000 fffffe87`7feb55d8 : LXCORE!LxpMiAllocateVad+0x46
fffffe87`7feb5440 fffff808`b24791a9 : fffffe87`7feb5860 00000000`00000000 00000000`00000004 00000000`00001000 : LXCORE!LxpMmSupportCloneComplete+0xa5
fffffe87`7feb54d0 fffff808`b249505c : ffff8002`b90ea400 ffffffff`8000ec40 00000000`00000000 00000000`00000000 : LXCORE!LxpProcessCreate+0x3cd
fffffe87`7feb5580 fffff808`b248ff2f : 00000000`00000000 00000000`00000000 00000000`00000000 fffffe87`7feb5688 : LXCORE!LxpThreadGroupFork+0xc0
fffffe87`7feb5650 fffff808`b248409b : 00007f0f`40cb09d0 ffffb488`64afa010 00007f0f`40cb09d0 00000000`00000000 : LXCORE!LxpThreadClone+0x27b
fffffe87`7feb5830 fffff808`b2483218 : 00000000`00000000 fffffe87`7feb5939 fffff808`b242b150 ffff8002`ab2c0700 : LXCORE!LxpSyscall_CLONE+0x6b
fffffe87`7feb58e0 fffff808`b249e691 : fffffe87`7feb5a00 fffffe87`7feb5a00 00000000`00000000 00000000`01200011 : LXCORE!LxpSysDispatch+0xf8
fffffe87`7feb59a0 fffff801`a279669f : 00007f10`24000020 00000000`00000060 00007f10`24010270 00000000`00000160 : LXCORE!PicoSystemCallDispatch+0x11
fffffe87`7feb59d0 fffff801`a21d1f38 : fffffe87`7feb5a00 00000000`00000014 00007f10`24000080 00000000`00000000 : nt!PsPicoSystemCallDispatch+0x1f
fffffe87`7feb5a00 00007f10`74694b1c : 00007f10`7499e968 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 : nt!KiSystemServiceUser+0x76 (TrapFrame @ fffffe87`7feb5a00)
00007f0f`40cae340 00007f10`7499e968 : 00000000`00000000 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 : 0x00007f10`74694b1c
00007f0f`40cae348 00000000`00000000 : 00000000`00000040 00007f0f`40cae5d0 00000000`00000004 00000000`00000000 : 0x00007f10`7499e968

**Comment by therealkenc** [comment]
>  [Version 10.0.17134.829]

Please try 1903 aka 18362
