### ISSUE TITLE
Calling `explorer.exe /directory` from within an Ubuntu instance opens the explorer but on an empty view and not on the specified directory

### ISSUE THREAD

**Issue by seb128** [microsoft/WSL#4297]
Using Windows Insider 10.0.18932.1000 with Ubuntu 18.04, doing this from the Ubuntu command line

$ explorer.exe /etc
opens a File Explorer view which states 'This folder is empty"

While doing
$ cd /etc; explorer.exe .

Correctly open a File Explorer listing the directory content

They should be equivalent commands

**Comment by seb128** [comment]
Using W10 r18932 

Typing 'wslusc' on a WSL2/Ubuntu 18.04 uptodate instance leads to have the Ubuntu instance font changing/being screwed untill the app is restarted

**Comment by 0xbadfca11** [comment]
They must not be equivalent commands.
WSL can run multiple distributions simultaneously.
How do called application distinguish these, and which location to open?
```
$ explorer.exe /etc    # From Ubuntu
$ explorer.exe /etc    # From SUSE
C:\> explorer.exe /etc # From Windows
```
Even if Explorer supports it, how about other applications?

And command line arguments should not be converted implicitly.
There is a big gap between what "a string that looks like a file system path" and "the file system path".
Conversion should be done explicitly.
```bash
$ explorer.exe "$(wslpath -w "/etc")"
```

- ``explorer.exe .``

There is no problem that the current working directory is implicitly converted. Unlike the command line arguments, CWD is definitely a file system path.

**Comment by seb128** [comment]
Thanks for the reply, 

> 
> How do called application distinguish these, and which location to open?
> 
> $ explorer.exe /etc    # From Ubuntu
> $ explorer.exe /etc    # From SUSE

Those commands are entered from within the distro environment, there is only one '/etc' in my Ubuntu and doing 'ls /etc' does know to list the Ubuntu /etc and not the SUSE one right? 

Why would an user think that 'ls' and 'explorer.exe' don't have the same understanding of the filesystem?

> C:\> explorer.exe /etc # From Windows

There is no /etc under Windows, those linux installations are under \\wls$ no?


The rest of your explanations sounds like describing implementation details to justify why it's not working. 

When I readi https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/ what I understood was 'now it's possible to call explorer.exe the same way you would call your filemanager on a traditionnal linux system', I didn't understand that '.' was special cased and the only option available.

I expect I'm not the only linux user who is going to be confused by that behaviour since on a standard linux system/distribution  '$ <filemanager> /path' would just open '/path' on pretty much any filemanager (commandline or graphical)

Also if the syntax is not handled it would be better to just return a message to the user than to open the filemanager and state that the directory is empty (which is misleading since it's not)

**Comment by seb128** [comment]
I wonder if the initial title was maybe confusing on what the problem is? I update it now, let me know if that makes a difference of your understanding of the problem described?

**Comment by imReker** [comment]
Is it hard to understand?
'/etc' is a string not a path passed to explorer.
If you have a 'e' folder in the root, so it's path is '/e', now, tell me what will happen if I exec 'explorer.exe /e'

**Comment by seb128** [comment]
Yes it is difficult to understand for as linux users sorry

1. You are providing an 'linux' environement, in that command line any command will understand /etc or /etc/wsl.conf as paths.
Like you can try to do
- $ ls /etc 
-> works
- $ vim /etc/wsl.conf
-> works
- install a linux filemanager (e.g mc)
$ mc /etc
-> works

Now in the same environment you make available an 'explorer.exe' which doesn't understand the same syntax as any of the other tools available ... so yes, it might makes sense from a windows engineer perspective that knows that the backend/tech behind are not the same, but sorry as an user it's over me why the explorer command can't understand a local path, I just lack the windows API/low system knowledge (and as an user I'm probably not the only one?)

2. on Ubuntu if you want to list a directory you use 'ls /directory', if you want to see it in a graphical filemanager you do
$ nautilus /directory
(nautilus is the name of the filemanager binary there)

I understood from the Microsoft blog post that explorer.exe was made available as an equivalent and would easily allow you do open directories the same way

3. currently the behaviour is buggy, if the parameter is wrong the result shouldn't be to open a explorer view which tells you the directory is empty because the information is wrong and misleading.

Things you could do
- warn on the command line that '/etc' isn't a valid path or argument
- warn in the UI that the directory you asked for is invalid
- provide an 'explorer_wrapper.exe' in the linux command line that does the path conversion to a valid windows one so users can have the same workflow they would have on a linux system

**Comment by imReker** [comment]
OMG, Windows and Linux DO NOT have same behaivor, they are different thing.
`-` or `--` is NOT standard param prefix on Windows, `/` is the right one.

`ls -l /etc` of course works on Linux because it parse params start with `-` or `--` and pase anything else as a path.
BUT `ls --etc` or `ls /?` on Linux will not work, right? And you know what? `dir /?` and `dir -etc` works well on Windows.

**Comment by seb128** [comment]
I though the point of WSL was to provide a linux command line though?

**Comment by benhillis** [comment]
At the end of the day there are two options:
1. Look at command line arguments and try to guess which are paths, and translate them potential making mistakes. 
2. Pass arguments as-is and require the user to explicitly translate cross-environment paths.

**Comment by seb128** [comment]
@benhillis one variant of 2. could be
include a 'explorer.sh' wrapper in the WSL environment which takes a linux path argument and does the unix_to_win path conversion and call explorer.exe on that win-compatible-path.

Could that wrapper come from the windows side, or is the content of the WSL environment only under the distribution control? (in which case it would be something to add e.g in the Ubuntu image, it would mean the command is 'less standard' though)

(I still think that calling explorer.exe with an argument it doesn't understand should warn the user that the argument wasn't understood instead of acting like it did but giving you an empty dir, but that's probably a different issue/one to report on explorer.exe itself?)

**Comment by imReker** [comment]
So it's still option 1.
You can write this 'explorer.sh' by yourself because it's quiet simple:
1. Convert Linux param prefix `-` or `--` to Windows style '/'
2. Translate Linux path

But this script can only apply to explorer because every param is specific to program, so MSFT will ever provide an official solution
