### ISSUE TITLE
Lost mount driver after 2019 07 update !

### ISSUE THREAD

**Issue by eromoe** [microsoft/WSL#4300]
I mount drivers from `/mnt`  to `/`  several months ago , it worked perfectly .
Today I found windows install 201907 , then this problem occur : 

```
➜  ~ ls -al /mnt/f
total 0
drwxrwxrwx 1 root root 4096 Oct 10  2018 .
drwxr-xr-x 1 root root 4096 Oct 10  2018 ..
➜  ~ ls -al /f
total 0
drwxrwxrwx 1 root root 4096 May 16 18:00 .
drwxr-xr-x 1 root root 4096 May 16 18:00 ..
➜  ~ cat /etc/wsl.conf
[automount]
enabled = true
root = /
options = "metadata,umask=22,fmask=11"
mountFsTab = false

[network]
generateHosts = true
generateResolvConf = true
```

`mount -l | grep drvfs`  show nothing 

How do I solve this ???

**Comment by benhillis** [comment]
Any errors in dmesg?

**Comment by eromoe** [comment]
No. only error message is soft link  not found .

**Comment by benhillis** [comment]
What is the output of the mount command?

**Comment by eromoe** [comment]
```
➜  ~ mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
```

**Comment by 0xbadfca11** [comment]
Where is mount?
``$ which -a mount``
As far as I know, recent WSL assumes that mount must exists as ``/bin/mount``.

**Comment by eromoe** [comment]
I can access my work pc now. But it must esixt in that path or I can't run `mount` command

**Comment by eromoe** [comment]
Just confirm it is in `/bin/mount` .

**Comment by eromoe** [comment]
I recall I update ssh.exe(C:\Windows\System32\OpenSSH\ssh.exe) to 8.0beta in order to fix problem when using vscode remote . Does wsl use ssh to share disk infomation ?

**Comment by onomatopellan** [comment]
The fact that your `/mnt/f` and `/f` folders are owned by root means those folders are not mounted. You can get rid of those folders with `sudo rmdir /mnt/f /f` 

Drvfs folders correctly mounted are owned by the user and they appear in blue.

Let's assume your wsl.conf file is damaged. Delete it, close the terminal, wait for 15 seconds and launch terminal again. Do the drives appear on /mnt/ now?

**Comment by eromoe** [comment]
rmdir would show error 
```
➜  ~ sudo rmdir /mnt/f /f
sudo: unable to resolve host Mithril: No such file or directory
```
However those folder did be deleted .
Delete `wsl.conf`  and wait  15 seconds ,  nothing appear in /mnt .

**Comment by eromoe** [comment]
I also found can not use docker in wsl :

```
➜  ~ docker start jupyter
error during connect: Post http://localhost:2375/v1.39/containers/jupyter/start: dial tcp: lookup localhost on 114.114.114.114:53: no such host
Error: failed to start containers: jupyter
```

I have below settings in `~/.profile`
```
export DOCKER_HOST=tcp://localhost:2375
```
Strange thing is it look up from remote DNS server I set some days ago .

**Comment by onomatopellan** [comment]
Can you install another linux distro and try if the problem persists there?

Also I'd look at the Windows hosts file. Something is definitely broken if you cant' even use sudo without errors.

**Comment by WSLUser** [comment]
Also use the Reset option in Settings - Apps and Features if you don't want to install another distro.

**Comment by eromoe** [comment]
Another distro debian is no problem. So this must be something happen damege ubuntu .
