### ISSUE TITLE
Add NOPASSWD to sudoers file by default

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/WSL#4302]
In Ubuntu on WSL, the sudo command requires typing the UNIX user password by default. This could be avoided with a very simple patch: changing the line `%sudo ALL=(ALL:ALL) ALL` to `%sudo ALL=(ALL:ALL) NOPASSWD: ALL` In the /etc/sudoers file.
Users would still need to type sudo for commands that require elevated privileges, but won’t be prompted for a password.

I’ve been doing this on every WSL installation I made, would just love it if it were a default.

**Comment by ItalyPaleAle** [comment]
Just to add on this: if this were implemented, you could also stop asking WSL users to create a UNIX password when they start the first time (which is too often forgotten!). At that point, you could use any random-generated password; if users ever needed to change that, they could just do "sudo passwd" to set a new password.

**Comment by xtremeperf** [comment]
That's something you'll need to request from the maintainer of each distro.  I highly doubt any of them would be interested in bypassing sudo passwords for all commands by default though.

You could use a shell script to automatically change this for your new installs. Have you considered removing the sudo package altogether? Some distros, minbase builds, as well as most Docker images, don't include the sudo package and run as the root user by default.

**Comment by ItalyPaleAle** [comment]
@xtremeperf  well, Microsoft works with the distro maintainers and I'm sure the team has a way to add patches after a distro is deployed.

Passwordless sudo is actually very common, e.g. when you create a VM on the cloud (including Azure) and set it up to authenticate via SSH keys only (so without setting a password for the user). It's considered [not less safe](https://security.stackexchange.com/questions/45712/how-secure-is-nopasswd-in-passwordless-sudo-mode) than requesting a password. Considering that WSL is mostly used for development anyways, it shouldn't be a significant risk.

Instead, running everything as root could have bigger security implications.

**Comment by xtremeperf** [comment]
@ItalyPaleAle Actually, Microsoft requires that all packages be digitally signed using code signing certificates with encryption to guarantee that the code has not been altered by any party after the software developer has signed it.

I understand what your point of view, and often use the same methods myself, however, please consider that your request is for EVERY installation of WSL be modified by Windows after installation to disable the software developer's password security feature for privilege elevation.

**Comment by ItalyPaleAle** [comment]
It's not a "modification", it wouldn't alter signed code. It's just a "startup script", similar (in a sense) to cloud-init...

**Comment by WSLUser** [comment]
As a security dev, my answer to this is do it yourself. Windows should allow the most security it can including what WSL does or doesn't do. I want to see all the security that Linux distros offer not be messed with by Windows except when necessary to ensure interop. Otherwise, leave it be. You always can change it yourself. Having a secure default is better than having a non-secure.

**Comment by mscraigloewen** [comment]
There's been some great discussion here. In general, the distro maintainers provide almost all of the userspace binaries in each Linux distro. There are some distros that do not use sudo or have a sudoers file (like Alpine for example), and so I think it would be more challenging for us to implement your request. I believe these kind of decisions are better left up to the distro maintainers themselves.

**Comment by ItalyPaleAle** [comment]
Thanks, Craig!
