### ISSUE TITLE
docker run remote error: tls: bad record MAC.

### ISSUE THREAD

**Issue by appenthused** [microsoft/WSL#4306]
* Your Windows build number:  Microsoft Windows [Version 10.0.18936.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:
root@LAPTOP-BPPURGE2:/mnt/c/Users/appenthused# docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: remote error: tls: bad record MAC.
See 'docker run --help'.

**Comment by experimenti** [comment]
@appenthused Plugging in my network cable resolved this. 

I hit this as well.  Ping and other network-related commands worked fine.  Tried a few fixes (below), but issue is resolved with plugging in network cable (so specific to the wifi/vethernet bridge, I guess).

I can now remove the cable and all is well with docker is WSL2, BUT upon reboot, I have the same issue and need to re-cable.


INFO:
Windows 18936.1000 
Killer E2500 Gigabit Ethernet

TRIED:
1) Uninstall all network components and reinstall
2) Alt method of starting docker sudo  /etc/init.d/docker start vs. sudo service docker start
3) Different versions of linux from the store
4) Uninstall docker desktop
5) Create a wsl.conf in /etc
6) Drop firewall

**Comment by vanstinator** [comment]
Try updating your wifi driver if you have an intel wifi card. https://stackoverflow.com/questions/56946336/ubuntu-wsl2-git-getting-the-remote-end-hung-up-unexpectedly-on-large-repos

**Comment by experimenti** [comment]
@vanstinator Resolved.  Thanks!   It was a Killer Networking driver.

**Comment by appenthused** [comment]
@experimenti @vanstinator thank you!

**Comment by chldong** [comment]
现在可以确定，OpenSSL的握手过程不是多线程安全的操作，在我写这篇文章前，网络上却始终没有一个人给出这个解答，真是悲剧，不过你很走运，如果你的软件，或者开源软件使用了OPEN SSL，使用多线程过程中出现随机的bad record mac, 或者干脆卡在tls握手阶段，恭喜你中招，解决办法只有一个，取消掉多线程握手加速，当然你想重写OpenSSL握手函数，我会非常佩服，成功了记得告诉我一声

**Comment by CS2Us** [comment]
I was checking this problem and i finally figure out: the reason is because the intel wifi card driver. when i update the driver to the latest version but it can't work, so i go to the internet wift card driver setting and **Roll Back Driver** to the previous driver. it finally work. So, if you update to the latest version and then it can't work, try roll back to the previous version.
