### ISSUE TITLE
[WSL 2] Cannot access \\wsl$ after waking computer from sleep

### ISSUE THREAD

**Issue by Coridyn** [microsoft/WSL#4311]
* Your Windows build number:  Microsoft Windows [Version 10.0.18936.1000]
(This was also happening for me on build 18917)

* What you're doing and what's happening: 

I put computer to sleep overnight.
After waking my computer I cannot access my Linux files via `\\wsl$\Ubuntu`.  
Explorer fails with the message: `\\wsl$\Ubuntu is not accessible.`

This happens often (but not every time) after waking computer from a long overnight sleep.

I ran `dmesg` and I got these errors in the log:

	[  175.397844] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)

	[  175.402700] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)

	[  175.409129] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)

	[  175.417134] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)

	[  175.422563] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)

	[26961.870773] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\\p9handler.cpp:853 (EmplaceFid)

	[26961.896837] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\\p9handler.cpp:853 (EmplaceFid)

	[26961.899632] init: (1) ERROR: LogException:30: FS: (null) Invalid argument @..\\p9handler.cpp:853 (EmplaceFid)

Is there any additional information I can provide to help?

-------------------------------------------------

(NOTE: This issue is superficially similar to #4027 and #4260 except accessing `\\wsl$\...` usually works. It just fails after some amount of time, usually after waking the computer from sleep.)

-------------------------------------------------

**(hopefully temporary) Workaround for people experiencing this issue:**

It's possible to temporarily restore file integration without having to restart your whole machine by restarting the WSL distribution (I'm only running one distribution so I don't know if you have to shutdown and restart all distributions to restart the 9P server).

(just make sure to close all applications that are accessing Linux files (e.g. vscode) before restarting the WSL distribution)

```
# close all apps accessing linux files (e.g. vscode)

# shutdown WSL distribution
$ wsl --shutdown Ubuntu

# confirm WSL distribution has shut down
$ wsl -l -v

# start the WSL distributuion again
$ wsl -d Ubuntu
```

**Comment by joemaller** [comment]
Maybe the same issue: I have a Windows Explorer window open showing files from my WSL Ubuntu file system. Computer goes to sleep. Wake the computer, I get this error modal from Windows Explorer (one for every window which was viewing WSL files):

> \\wsl$\Ubuntu is not accessible. YYou might not have permission... 
> Attempt to access invalid address. 

![wsl-sleep-error](https://user-images.githubusercontent.com/8320/65397245-8810db00-dd7c-11e9-9606-0dc13bd01c4a.png)

I dismiss the dialog, and everything works correctly after a moment.

**Comment by benhillis** [comment]
@SvenGroot has a fix for this in review.

**Comment by Bengrunt** [comment]
Hey there, experiencing the same issue.
Any idea when the fix will be out?

Thanks!

**Comment by abuteler** [comment]
Same here. Although it wasn't something that started happening on the get go.
I could suspend my laptop and resume working without problem two months ago.
I started having this issue mid December.
VSCode will tell me it's unable to connect to the WSL server, as if it didn't wake up.
Yet I am able to access the ubuntu filesystem via a quickaccess I created in Windows Explorer.

**Comment by Stanzilla** [comment]
Yeah same, that is happening for resume from standby and normal restarts when you use the "restore explorer windows" option

**Comment by whaaaley** [comment]
I have "Restore previous folder windows at login", disabled and this still happens. It's really frustrating.

**Comment by Stanzilla** [comment]
Yeah if you are fast enough to call wsl.exe directly which causes the VM to boot then restoring network drives and explorer folders etc does not fail. @benhillis @therealkenc can we please remove the fixed flag here? Or will this not get fixed for 2004?

**Comment by therealkenc** [comment]
^--- File under a new issue if there is a well formed repro for remaining or related issues. The OP stated:

```
ERROR: LogException:30: FS: (null) Invalid argument @..\..\inc\p9protohelpers.h:122 (Name)
```

Given the timing of the fixinbound tag (September) it is safe to assume (unless/until someone says otherwise) that _whatever_ fix was applied with respect to the above error, it will ship in 2004.

**Comment by Stanzilla** [comment]
There you go https://github.com/microsoft/WSL/issues/5021

**Comment by nidia95** [comment]
I had this problem, although my wsl hanges and haven't been able to shutdown it with `wsl --shutdown`.  after tow days I found out I can fix it by killing the wslservice.exe in a admin powershell: `taskkill /f /im wslservice.exe`.

as I found here: #8529

**Comment by fredhaegele** [comment]
Why is this closed? 

In this year of 2023, this is still an everyday problem only fixed by shutting down wsl and restarting it, or rebooting the computer.

**Comment by markrmiller** [comment]
Why is this closed?

In this year of 2025, this is still an everyday problem only fixed by shutting down wsl and restarting it, or rebooting the computer.

**Comment by lesmo** [comment]
Why is this closed?

In this year of 2026, this is still an everyday problem only fixed by shutting down wsl and restarting it, or rebooting the computer.

#14193, #14005, #8696
