### ISSUE TITLE
Unable to list wifi supported channels

### ISSUE THREAD

**Issue by WajahatAliAbid** [microsoft/WSL#4313]
Please fill out the below information:

* Your Windows build number: ver 18362.239

* What you're doing and what's happening:
I am trying to list the channels my WIFI supports using the commands `iwconfig` and `iwlist`. When I use `iwconfig`, it shows the interfaces with "No wireless extension" in the tab next to them.
When I use `iwlist <interface_name> freq` it says no frequency information

* What's wrong / what should be happening instead:
This command should provide me list of all network interfaces and then I should be able to use `iwlist <interface_name> freq` command to check the channels my wifi supports.

So what I need to do? i cannot find any instructions on google.

**Comment by therealkenc** [comment]
#1077

**Comment by Kamel20dz** [comment]
Any new
