### ISSUE TITLE
Unable to mount network share via SSH, cron, or fstab

### ISSUE THREAD

**Issue by sysrage** [microsoft/WSL#4314]
**Your Windows build number:**
10.0.17763.615

**What you're doing and what's happening:**

When attempting to mount a network share via SSH, the following error is observed:
```
ls@LNVUSTSLICSVR:~$ sudo mount -t drvfs '\\10.37.163.91\tset' ${HOME}/tset
[sudo] password for ls:
mount: /home/ls/tset: cannot mount \\10.37.163.91\tset read-only.
```

The same UNC path is mounted by the 'ls' Windows user as 'Z:'. However, attempting to mount 'Z:' via SSH also fails:
```
ls@LNVUSTSLICSVR:~$ sudo mount -t drvfs Z: ${HOME}/tset
mount: /home/ls/tset: special device Z: does not exist.
```

However, on the exact same system with no changes, the above commands work without issue when run from the 'Ubuntu' console (instead of SSH).

I have also enabled cron and included a script in crontab which attempts to run the above commands. This also fails to mount the network share.

Additionally, when mounting the network share through the Ubuntu console, that path is then not accessible to the root user in an SSH session:
```
ls@LNVUSTSLICSVR:~$ ls /home/ls/tset/
ls: cannot open directory '/home/ls/tset/': Permission denied
ls@LNVUSTSLICSVR:~$ sudo ls /home/ls/tset/
ls: cannot open directory '/home/ls/tset/': Permission denied
ls@LNVUSTSLICSVR:~$ ls -ld /home/ls/tset
drwxrwxrwx 1 root root 512 Jul 16 16:05 /home/ls/tset
```

**What's wrong / what should be happening instead:**

The network share should mount, whether the mount command is invoked via SSH, cron, or local console.

**Strace of the failing command, if applicable:**

[strace gist here](https://gist.github.com/sysrage/d51f174a0823ae0750c17f7718def441)

**Comment by therealkenc** [comment]
I wasn't able to reproduce this here with either WSL1 or WSL2 under 18941. Tried connecting from a remote machine and just doing localhost (with WSL1). I don't have any reason to suggest upgrading will fix this for you, mind. I don't think there have been been a changes in this area that would explain why it is working for me but not for you. I suspect (but can't prove) there is some other factor/variable here. But getting up to the May 2019 Update 18362 would be a first next step.

This run below was WSL1.

![image](https://user-images.githubusercontent.com/7049700/61602551-eee40d80-abee-11e9-8f2f-e31a2c278579.png)

**Comment by sysrage** [comment]
I am no longer seeing this behavior after upgrading to 18362. Thank you.
