### ISSUE TITLE
WSL filesystem triggers write locks when other Unix systems do not

### ISSUE THREAD

**Issue by fgarcia** [microsoft/WSL#4315]
There is one tiny difference in the way Wsl filesystem deals with files compared to Linux. 

As a node user, when I try to do an `npm upgrade` I tend to get "NPM Access Denied Errors (Error: EACCES)" and also I get some random denied access errors in VsCode moving folders (just with WSL containers)

I found many issues mentioning how to fix permission problems but that fixes nothing

After a while getting used to WSL I noticed that the root problem is that WSL tends to grant a write lock to some files which never happen to me before in Linux and Mac OS X

In my case this happens specially with VsCode or running file watchers in the terminal.

After noticing this I solved lots of frequent file access problems by just closing all extra terminals and VsCode. 

Was this limitation already mentioned somewhere? Will it be solved on WSL2? I think it is an essential tip for people doing Javascript/node development in WSL

**Comment by therealkenc** [comment]
This is #1529 #1956 and friends.

> Will it be solved on WSL2? 

For the use case of `npm upgrade` when run with Linux `npm` on the ext4 VHD (aka, `/home`), yes that should be better now.
