### ISSUE TITLE
Cannot connect to WSL due to ssh connection refused

### ISSUE THREAD

**Issue by blackredscarf** [microsoft/WSL#4316]
I cannot connect to WSL  by ssh on Windows due to connection refused.
```
>ssh zjw@localhost -p2222
ssh: connect to host localhost port 2222: Connection refused
```

But Actually, the ssh-server is running well on my WSL. And ssh on WSL can connect to WSL itself normally.
```
$ sudo service ssh status
 * sshd is running

$ ssh zjw@localhost -p2222
...
```

WSL's sshd_config is 

```shell
# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
# configured by CLion
ListenAddress 127.0.0.1
Port 2222
UsePrivilegeSeparation no
PasswordAuthentication yes
```

(Actually, this configuration is got from this [script](https://github.com/JetBrains/clion-wsl/blob/master/ubuntu_setup_env.sh))

What's wrong about this? Thanks.

**Comment by onomatopellan** [comment]
See https://github.com/Microsoft/WSL/issues/2729#issuecomment-350265972

**Comment by blackredscarf** [comment]
@onomatopellan The SSH Server Broker does not exist on my services.msc

**Comment by fazilboudjellal93** [comment]
try to exclude the bash from your antivirus i hope it will help

**Comment by blackredscarf** [comment]
@onomatopellan Unfortunately, that didn't work

**Comment by Zoom1111** [comment]
I have the same problem with you, but I have no solutionuu🥶

**Comment by GuoHao150** [comment]
> I have the same problem with you, but I have no solutionuu🥶

Check  `https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-clion.html#wsl-tooclhain`  `In the ListenAddress 127.0.0.1 line, replace 127.0.0.1 with 0.0.0.0` and `then Save the changes and run sudo service ssh restart` it works for me

**Comment by SeanChao** [comment]
I solved this problem by set port number to 22222. I guess this may be a **firewall** issue?
e.g: I tried to launch a nodejs app on port 2000 and access it in windows via localhost, I got "connection refused"
Is anyone knows the root cause and how to solve it?
@therealkenc (Right before the issue closed, a link is posted but it's not a solution, so could this issue be reopened?)

**Comment by spaulaus** [comment]
I started having this problem after the latest windows update. [These instructions](https://jeetblogs.org/post/sshing-into-a-windows-wsl-linux-subsystem/) worked for me. They're quite old, but seem to still be valid.

**Comment by SiqingYu** [comment]
Same issue. I tried all methods mentioned above, but none works.

**Comment by Pogsquog** [comment]
I had two issues:
* UsePrivilegeSeparation is deprecated, I had to delete it from the ssh config (/etc/ssh/sshd_config)
* port 2222 was getting "connection refused" when I ran sshd thus: "sudo /usr/sbin/sshd -Dddde". I changed to port 2828 and now it works fine.

**Comment by Nejat** [comment]
When I have connectivity issues either getting ```sudo apt update``` to run or ```ssh```-ing into ```wsl```, generally one of two possibilities fixes the problem:

- docker desktop needs to be updated
- or ```wsl``` needs to be recycled ```wsl --shutdown```, _docker needs to be shutdown before this step_

\* if ```wsl``` can not shutdown, most likely docker should be updated, _however I have not run into this in a long while, so maybe there was a bug fix some where along the line_

I hope this helps save some frustration

**Comment by AlexanderMishutkin** [comment]
No advice from this discussion helps:
`sudo /usr/sbin/sshd -Dddde` works properly and I can connect to my openssh server from WSL, but not from windows CMD. Got `connection refused` every time
1. I have tried to change port to 22222, 2223, 8002, but situation did not change
2. I tried to alter 127.0.0.1 with 0.0.0.0 - same
3. Tried to shutdown windows firewall - same
4. Tried to restart openssh and reboot wsl - same
5. Finally, I tried to `dpkg-reconfigure openssh-server` but got error `invoke-rc.d: could not determine current runlevel`

**Comment by hectorhalpizar** [comment]
This worked for me:

To enable, start your Ubuntu (or other Systemd) distribution under WSL (typically just wsl ~ will work).

`sudo -e /etc/wsl.conf`
Add the following:

```
[boot]
systemd=true
```
Exit Ubuntu and again:

`wsl --shutdown`
Then restart Ubuntu.

`sudo systemctl status`
... should show your Systemd services.

Source: [AskUbuntu](https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate/1379567#1379567)
