### ISSUE TITLE
Bug: bash process created by tmux never gone when the window is closed.

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/WSL#4317]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18362.239

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

In a Windows cmd, "bash" to start WSL.
"tmux" to start tmux.
create 3 pane (c-b %). Each pane has bash process.
Close the Window of Windows cmd.

* What's wrong / what should be happening instead:

Observed:
Bash processes created by tmux and tmux process itself stay in the system forever.

Expected:
Bash processes created by tmux and tmux process itself should be killed, since their grand parent process has been killed/closed.

**Comment by 9527KGG** [comment]
One more observation: 

The issue is : tmux process is not killed. If I kill tmux process manually, bash process would be killed too.

**Comment by 9527KGG** [comment]
seems a tmux issue???

**Comment by mscraigloewen** [comment]
This seems to be a 'bydesign' issue. We added [background task support](https://devblogs.microsoft.com/commandline/background-task-support-in-wsl/) in WSL, so when you close a Window with a long running process still running like tmux we keep that alive.
