### ISSUE TITLE
wslpath return absolute paths, UNC

### ISSUE THREAD

**Issue by ares09x** [microsoft/WSL#4318]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.18936.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Problem 1: When I run wslpath -m or -w on a Ubuntu path I do not get a full Windows path, but rather a shortened one. For example wslpath -m . in my home directory just returns wslpath: ., and wslpath -m / just returns /.

Problem 2: Running sudo apt update takes significantly longer in WSL 2 than in WSL 1, and sudo apt upgrade takes somewhat longer.

* What's wrong / what should be happening instead:

Problem 1: I expected to see the full Windows path returned. This may be a problem with WSL 2, because on a PC running WSL 1 the output of wslpath -m . is just /lxss/home/rhy, which is at least closer to what I expected. Can you provide an option that returns the full Windows path, including the drive indicator, like C:?

Problem 2: sudo apt update read package info very quickly in WSL 1, but seems to take 2-3 times as long after I converted to WSL 2. sudo apt upgrade initial processing seems about as quick, but setting up and processing triggers seems to take 2-3 times a long in WSL 2 as in WSL 1.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Thanks for filing. Yes it looks like some of the path translation logic needs to be updated with \\wsl$ info. Honestly I think the -a flag should just be the default...

**Comment by therealkenc** [comment]
> For example wslpath -m . in my home directory just returns wslpath: 

Agreed, `.` is near always the "wrong answer" for the purposes passing a CLI parameter to program running over on the Windows side. Feature request would be to make `-a` the default.

**Comment by ares09x** [comment]
too old now
