### ISSUE TITLE
[WSL2] Add NFS v4 support to kernel

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4319]
Current as of build 18936.

i.e., enable the CONFIG_NFS_V4 flag.

A request because even my cheap consumer NAS defaults to NFS 4 these days, and there's no point in inadvertently encouraging people to use downlevel versions.

**Comment by lazerl0rd** [comment]
You can build your own kernel for now, with that option. Be aware to replace the symlinked file not the symlink itself in `C:\Windows\System32\lxss\tools\kernel` tho. It is a non-compressed kernel stored there btw.

**Comment by cerebrate** [comment]
Oh, I can and I do. Works great for me -- but if my NAS defaults to NFS 4, my point is, there're going to be lots more out there that people really shouldn't have to enable downlevel NFS on or recompile their kernel to make work with WSL. IMO.

**Comment by lazerl0rd** [comment]
Yeah, ofc @cerebrate. I'm sure the WSL team will look into this - it just seems there's more pressing bugs to squash before the feature add-ing stage ATM. So it might take them a while.

**Comment by therealkenc** [comment]
> So it might take them a while.

I was looking at the remaining list of config options "`is not set`" a week or two ago and if you don't count all the ones already asked for, hopefully we're getting down to the short hairs.

Seems at base an intractable problem though. Tomorrow someone points out `CONFIG_EXT2_FS` isn't set or `CONFIG_XFS_FS` isn't set (identical `CONFIG_NFS_V4` is not set), and desperately tries to justify their use-case as worthy of inclusion. They're all worthy to someone.

The problem isn't lack of resources to flip the switch ("time"). It is staring down the elephant in the room: which is, do they all get turned on. [Those that can be turned on given the virtual hardware on offer, anyway.]

**Comment by lazerl0rd** [comment]
@therealkenc if building your own kernel were made to be easier, I'm sure a lot of these requests wouldn't be necessary. For example, I have heard from another dev saying that if they replaced the kernel symlink itself - they can't update Windows.

**Comment by onomatopellan** [comment]
@lazerl0rd I have updated Fast Ring twice having my own compiled kernel without problem. It just replaces whatever you have in the "tools" folder so I need to copy my kernel there again.

**Comment by therealkenc** [comment]
> if replacing the WSL2 kernel your own kernel were made to be easier,

I've fired a few neurons imagining an easiness scenario, and it devolves to everything being turned on instantly. Ben adds "`wsl.exe --install-new-vmlinuz <image>`" feature. Thirty minutes later someone opens a github repo with kernel images with everything turned on, merged up to 5.3 (or the kernel of the week). It becomes SOP for everyone to use that repo's kernel "because Microsoft's stock kernel is really old and is missing stuff". And then people start posting here when something doesn't work with those images, and those posts go instant chirping-cricket because the kernel isn't (scare quote) "supported". Which is okay; not against it playing out that way. Might be inevitable regardless. Easier. But not simple.

**Comment by lazerl0rd** [comment]
@therealkenc ah yes, that would end up being awful. I guess there's no "perfect solution" to the config issue, and it's up to the WSL team, in the end, to decide what to do.

**Comment by cerebrate** [comment]
@therealkenc That consideration's why I didn't trot out my whole shopping list. Now that kernel replacement is on the table, I can easily enough recompile it for my personal set of obscure options.

This, one, though, I figure is worth putting in the default kernel because where there are Linux clients (WSL included), there are going to be some Linux servers, hence NFS. And so this goes out to a bunch of my former colleagues in the sysadmin business who get the same twitch when they hear "NFS 2/3" as I do when I hear "SMB 1/2 support only".

**Comment by cerebrate** [comment]
Closing this, as it is included in the latest kernel.

**Comment by lazerl0rd** [comment]
@cerebrate on another note, it's been made much easier to use your own kernel now too :).
