### ISSUE TITLE
[WSL 2] move VHD File

### ISSUE THREAD

**Issue by leafbebop** [microsoft/WSL#4320]
Thanks for the good work of bringing WSL 2! I am wondering that if it is possible to move VHD File to another volume. Thanks in advance!

**Comment by Biswa96** [comment]
With registry, it's a matter of some seconds. But it's "undocumented".

**Comment by leafbebop** [comment]
@Biswa96 That's awesome news. However I am not familar with registry. Would you please point to me what path holds the key?

**Comment by mscraigloewen** [comment]
This is also possible using `wsl --export` and `wsl --import`. You can export your distribution with the export command and then import it to another drive using import.

```
C:\cDev> wsl --export Ubuntu ubuntu.tar
C:\cDev> wsl --unregister Ubuntu
C:\cDev> wsl --import Ubuntu E:\wslStore\Ubuntu\ ubuntu.tar 
```
Please note that this will start you off as a root user. Please see #3974 where we're tracking this!

**Comment by 0xabu** [comment]
If you want to move the VHD file (and not go back to WSL1, you should really use `--version 2`, i.e.:
```
wsl --export Ubuntu ubuntu.tar
wsl --unregister Ubuntu
wsl --import Ubuntu E:\wslStore\Ubuntu\ ubuntu.tar --version 2
```

**Comment by ketozhang** [comment]
Note the command cannot be installed on root of a drive (e.g., `D:\`). You'll get the error `Access is denied.`.

**Comment by alexandermalfait** [comment]
The key seems to be the "virtual distro" named `docker-desktop-data`:

See https://dev.to/kimcuonthenet/move-docker-desktop-data-distro-out-of-system-drive-4cg2

**Comment by KUGA2** [comment]
> 
> 
> If you want to move the VHD file (and not go back to WSL1, you should really use `--version 2`, i.e.:
> 
> ```
> wsl --export Ubuntu ubuntu.tar
> wsl --unregister Ubuntu
> wsl --import Ubuntu E:\wslStore\Ubuntu\ ubuntu.tar --version 2
> ```

I did this and it worked. Can i delete the tar file afterwards?
