### ISSUE TITLE
Installing NVIDIA Driver on WSL 2: unable to find kernel source tree for currently running kernel.

### ISSUE THREAD

**Issue by Juenjie** [microsoft/WSL#4326]
* When I try to install NVIDIA driver on WSL 2, the driver yields an error: cannot find the current kernel tree. 

* When I later use the command:
`sudo sh NVIDIA-Linux-x86_64-430.34.run --kernel-source-path=/mnt/c/Windows/System32/lxss/tools`
It says that  
         The kernel header file
         '/mnt/c/Windows/System32/lxss/tools/include/linux/kernel.h' does not
         exist.

* Where I can find the real tree, and install this driver successfully?

**Comment by karuboniru** [comment]
Actually you can't use your Nvidia devices in WSL2.
But if you are looking for kernel headers. you can find them from the source.

**Comment by therealkenc** [comment]
Real tree is [here](https://github.com/microsoft/WSL2-Linux-Kernel). Which are exactly the same as the header [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include?h=v4.19). That you are getting "`..../include/linux/kernel.h' does not exist`" is not the blocker for installing NVIDIA video drivers.

#829
