### ISSUE TITLE
[WSL2 - Ubuntu] System's root directory does not exist...

### ISSUE THREAD

**Issue by TheLeaker** [microsoft/WSL#4328]
- **Your Windows build number:**  Microsoft Windows [Version 10.0.18941.1001]

- **What you're doing and what's happening:** Nothing special... All I did was installing WSL2 and Ubuntu from Microsoft Store.

- **What's wrong / what should be happening instead:** As the title says, I can't find System's root directory for Ubuntu.

As per my research the root directory should be located at

`C:\Users\USER_NAME\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState`

But all I see is temp (File Folder) and ext4 (Hard Disk Image File).

![Cap 2019-07-22 12-34-30-550](https://user-images.githubusercontent.com/51280654/61604586-184b7a80-ac7d-11e9-8cb3-d4f1a6d044c7.png)

**Comment by Biswa96** [comment]
You can access root directory from 9P server i.e use `\\wsl$` network path.

**Comment by TheLeaker** [comment]
Hi @Biswa96,

Whoa... I don't get what 9P server and what that network path are D:.....

Sorry, I'm super new to not only WSL, but also Linux environment :/

**Comment by TheLeaker** [comment]
![Cap 2019-07-22 16-44-10-478](https://user-images.githubusercontent.com/51280654/61611971-98370c00-aca0-11e9-9f66-f4cb35657be8.png)

It definitely exists on WSL side of Ubuntu as shown above, but I can't locate it on Windows side :/

**Comment by Biswa96** [comment]
1. Run the distribution 2. Press Win+R 3. Type `\\wsl$` which opens File Explorer 4. Double click on the distribution folder.

**Comment by TheLeaker** [comment]
> 1. Run the distribution 2. Press Win+R 3. Type `\\wsl$` which opens File Explorer 4. Double click on the distribution folder.

Wow!!! I got it!

Thank you so much @Biswa96!

I can finally check those files XD

But, I still don't get why that file directory method is not working for me... I don't see anyone else having the same issue as I do :/

**Comment by Biswa96** [comment]
Because this is not an issue. This is by-design for WSL2. Users are not supposed to use that AppData\Local\Packages path. That `\\wsl$` path is also valid for older WSL1 versions. Read (this blog post](https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/) for more.

**Comment by Biswa96** [comment]
Because this is not an issue. This is by-design for WSL2. Users are not supposed to use that AppData\Local\Packages path. That `\\wsl$` path is also valid for older WSL1 versions. Read [this blog post](https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/) for more.

**Comment by TheLeaker** [comment]
> Because this is not an issue. This is by-design for WSL2. Users are not supposed to use that AppData\Local\Packages path. That `\\wsl$` path is also valid for older WSL1 versions. Read [this blog post](https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/) for more.

So, you are saying that accessing via that path is more like a cheaty way, not intended output of the design, right?

If it is, that makes much more sense.

Thank you so much for your clarification, @Biswa96 !!

**Comment by mscraigloewen** [comment]
Please do not access your Linux files using the Appdata folder! This is where your Linux files are (in general) stored on your disk, but accessing them with Windows tools directly from that location could cause issues. 

As @Biswa96 commented, please only use the `\\wsl$\` method (which we refer to as a 9P server) to access your Linux files from Windows.

**Comment by TheLeaker** [comment]
> Please do not access your Linux files using the Appdata folder! This is where your Linux files are (in general) stored on your disk, but accessing them with Windows tools directly from that location could cause issues.
> 
> As @Biswa96 commented, please only use the `\\wsl$\` method (which we refer to as a 9P server) to access your Linux files from Windows.

Roger that!

**Comment by legistek** [comment]
This is good stuff thank you. Although I had to use the pure BAT file option on Windows Server as Task Scheduler seemed to refuse to run a VBS no matter what I did.
