### ISSUE TITLE
SR-IOV and Discrete Device Assignment and WSL2 and Legacy hardware

### ISSUE THREAD

**Issue by walkerjian** [microsoft/WSL#4330]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.239]
* What you're doing and what's happening:  I have an oldish box (3930k, ga-x79-up4, 32GB quad channel). I recently had (I think) a fleeting run with tensorflow gpu accelerated in a docker container! I also had hyper-v server running in hyper-v too. And then the latest update to windows dropped and the  world changed for the worse, again. Nothing worked, a complete reinstall of docker (well I think it was) did no good and now linux containers for docker no longer work. There seems to be legacy crud in the filesystem and registry, and I do not have the hours to try and do your jobs (the collective MS 'your'). All I want to do is get stuff done without continually getting the rug pulled out from under my feet! To cap it off, during my toil, I ran up a powershell script (SurveyDDA.ps1) that was meant to tell me if my hardware could handle the brave new world of SR-IOV, Discrete Device Assignment and hyper-v. Now I don't know and the script told me that it has disabled something incomprehensible! For security! A SURVEY SCRIPT! Argh! I have uninstalled the hyper-v role, and several other windows features that I have no clue as to what they do... I have installed virtual-box 6, and docker-toolbox, which runs on a virtual-box vm. SO now I can have dockers running again without (most) incomprehensible fails. This not satisfying though. I had GPU pass-through, I had TensorFlow in containers, I had a process of booting into a hyper-v mode and booting into a virtual-box mode, and whilst not being convenient, it was a working solution. Now I don't - so here is the question: With the advent of WSL2, what will the ramifications be for SR-IOV, Discrete Device Assignment, legacy hardware and catastrophic (in the bad sense) forced updates. In other words; should I even bother even when forced too by your egregious updates...

* What's wrong / what should be happening instead: The crux of the question is that you (MS) keep on breaking in unfixable ways that are incomprehensible without devoting too much of my precious time to working out what went wrong. 

Is there a way I can safely and securely use WSL2? For anything? Is it worth me devoting any more time to it? to MS? You keep on ripping the rug out from under my feet, and no, I WILL NOT BE DRIVEN INTO THE CLOUD...

**Comment by therealkenc** [comment]
Ran course.

**Comment by walkerjian** [comment]
Ran course... ? great comment!
