### ISSUE TITLE
git diff doesn't work in a special case 

### ISSUE THREAD

**Issue by phihh** [microsoft/WSL#4335]
When I've installed git on windows and on wsl ubuntu, git diff doesn't show anything in ubuntu when it's in a directory outside of wsl system and in a directory of windows instead( e.g.: C\Users\me\Desktop\New_folder)

**Comment by JeromeDane** [comment]
Is this one related? https://github.com/microsoft/WSL/issues/4336

@phihh You might also want to add your system information as described in https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

**Comment by mscraigloewen** [comment]
Hi @phihh to echo what @JeromeDane said could you please give us more info. What version of Windows are you using? If you're running an insiders build are you using a WSL 1 or WSL 2 distro? Can you provide us steps to reproduce your issue?

Thanks!
