### ISSUE TITLE
Windows Git sees executable files in WSL 2 linux file system as non-executable

### ISSUE THREAD

**Issue by JeromeDane** [microsoft/WSL#4336]
## Description
In WSL 2, when a Git repository is hosted within the Linux file system and contains executable files, these files are seen by Windows Git as non-executable.

## Steps to reproduce
1. In bash run the following commands:
```bash
cd ~
mkdir wsl2-executable-files
cd wsl2-executable-files
git init
touch test-executable
chmod 755 test-executable
git add .
git commit -m "Create executable file"
```

2. Get the Windows path to this folder. This can be done by typing `explorer.exe .` in `bash` and getting the full path from the Windows Explorer window that opens. e.g: `\\wsl$\Ubuntu\home\<user>\wsl2-executable-files`
 
3. In Windows PowerShell run the following commands:
```powershell
cd \\wsl$\Ubuntu\home\<user>\wsl2-executable-files
git status
```

## Expected Result
The Windows version of Git should not detect any changes to the repository hosted in the Linux file system
```
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\<user>\wsl2-executable-files> git status
On branch master
nothing to commit, working tree clean
```

## Actual Result (problem)
The Windows version of Git shows that `test-executable` has been modified:
```
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\<user>\wsl2-executable-files> git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test-executable

PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\<user>\wsl2-executable-files> git diff
diff --git a/test-executable b/test-executable
old mode 100755
new mode 100644
```

This also manifests in editors like [Atom](https://atom.io/) that have built-in support for Git. If a Windows version of Atom is opened to read the repository hosted in the Linux file system, it will also detect a change:

![image](https://user-images.githubusercontent.com/451066/61894443-72974600-aede-11e9-97e6-ba49945de308.png)

### Windows Build Number
```
Microsoft Windows [Version 10.0.18941.1001]`
```

### WSL Instance Information
```powershell
C:\> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

### Ubuntu information
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

### Linux Git Version
```
$ git --version
git version 2.17.1
```

### Windows Git Version
```
PS C:\> git --version
git version 2.22.0.windows.1
```

**Comment by therealkenc** [comment]
This is by-design Windows `git.exe` which does not grok Linux metadata. You'd see the same behavior if you did the same thing on a Real Linux box and Windows given identical circumstances. There are [standard](https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows) work-arounds for the impedance mismatch. Hail Mary ref #3865 maybe one day in a galaxy far far way.

**Comment by iugo** [comment]
You can try `git config core.filemode false` then restart the Git GUI.
