### ISSUE TITLE
WSL2: localhost connection not working with PHP builtin server

### ISSUE THREAD

**Issue by gmsantos** [microsoft/WSL#4338]
* Your Windows build number:  Microsoft Windows [Version 10.0.18945.1001]  

* What you're doing and what's happening:  

I'm trying to access a [linux application via localhost from Windows](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/). 

To test this I installed php-cli on Ubuntu 18.04 and started the PHP builtin server on localhost:8000:

```
sudo apt install php-cli
php -S localhost:8000
```

* What's wrong / what should be happening instead:

When I tried to access localhost:8000 from Windows I got an ERR_CONNECTION_REFUSED error:

![image](https://user-images.githubusercontent.com/1991286/61983084-5aeeb900-afd5-11e9-80b5-e838e8922742.png)

Other application like apache2 works as expected.

![image](https://user-images.githubusercontent.com/1991286/61983174-c042aa00-afd5-11e9-8bdb-3f0794458545.png)

**Comment by mscraigloewen** [comment]
Can you check what IP address your php instance is bound to? I suspect that it's only accepting connections from localhost (127.0.0.1) and it needs to be able to accept incoming connections from all IP addresses (i.e: bind it to 0.0.0.0). 

So in python you would use `app.run(host='0.0.0.0')`

**Comment by gmsantos** [comment]
Binding to 0.0.0.0 works:

![image](https://user-images.githubusercontent.com/1991286/61989539-6eb31300-b007-11e9-86c8-6a79904f2b81.png)

thank you @mscraigloewen

**Comment by gmsantos** [comment]
It seems to be fixed after build 18970+

![image](https://user-images.githubusercontent.com/1991286/64454327-102a8b80-d0c1-11e9-9843-ce254ef23d02.png)

**Comment by thymbahutymba** [comment]
I'm trying to run this simple example without success. I'm running ubuntu and I've installed php 7.4, I tried both `php -S 0.0.0.0:8000` and `php -S localhost:8000`; In both cases the borwser is not able to connect, what I'm doing wrong?
