### ISSUE TITLE
vim auto indent not work

### ISSUE THREAD

**Issue by eromoe** [microsoft/WSL#4339]
Follow  https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode

```
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
    set pastetoggle=<Esc>[201~
    set paste
    return ""
endfunction
```

Doesn't work on wsl ubuntu 1804

**Comment by DHowett-MSFT** [comment]
The console does not support bracketed paste mode. microsoft/terminal#395.
