### ISSUE TITLE
wsl can`t open Vscode after install Windows 10 Insider Preview 18945.1001 (rs_prerelease)

### ISSUE THREAD

**Issue by cassss** [microsoft/WSL#4343]
Today I install Windows 10 Insider Preview 18945.1001 (rs_prerelease). After restart I found it`s would be blocked when I started VSCode in wsl,and i can open it in Windows

**Comment by SeanTAllen** [comment]
I have the same issue. There's an open issue here for it as well:

https://github.com/microsoft/vscode-remote-release/issues/914
