### ISSUE TITLE
Can't expand a command and execute any command related to writing to the filesystem 

### ISSUE THREAD

**Issue by jnzs1836** [microsoft/WSL#4344]
My windows build is Windows 10 Insider Preview 18945.1001 (rs_prerelease)

When I am trying expand a command by clicking 'Tab' but got 
```bash: cannot create temp file for here-document: Read-only file system```
which should be that after I click 'Tab'
```cd ./Downloads```

Then when I try to use any command related to writing to the filesystem, the system tells me:
```
-bash: /bin/cp: Input/output error
```
`strace` command also fails like the above

**Comment by mscraigloewen** [comment]
Are you using a WSL 1 or WSL 2 distro? Is the problem reproduceable on both?

Is this just in your Linux root file system or in your Windows file system (/mnt/c/) as well?

**Comment by jnzs1836** [comment]
I am using WSL2 and I only met the problem on WSL2. I think the problem happend in both Linux root file system and windows file system.
However, reboot makes the system work normally. I wonder is it a bug in WSL2?

**Comment by silviuk** [comment]
Similar behavior here, it appears sometimes there's not enough space or not right permissions (sometimes permissions are messed randomly). 
It seems the WSL 2 VM is somehow starving or not getting resources available quickly enough, e.g. when doing git clone and then compile of big projects like qemu build fails, sometimes works.
