### ISSUE TITLE
Debian WSL Install Lost After Installing Windows Update KB4505903

### ISSUE THREAD

**Issue by aGrimRepoMan** [microsoft/WSL#4345]
* Your Windows build number:   Version 10.0.18362.267

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
0. Starting condition: Debian WSL installed on Windows 10 and working well / stable for past month.
1. Installed Windows Update KB4505903 today.
2. Restarted PC
3. Launched WSL Debian shortly thereafter.

* What's wrong / what should be happening instead:
At step 3, instead of getting the expected Bash shell with previously configured user & user's filesystem available, a new install of Debian was triggered.  It appears that my previous install has been wiped out. 

The Windows directory C:\Users\<my_username>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_<Letters&NumbersHere>\LocalState\rootfs\  no longer contains my previous installation's files, only fresh install files.

I looked through the Windows logs, but did not note anything that looked relevant.  It may be coincidental that this happened after updating KB4505903?

[Also, I invested significant time customizing the previous install - are those files perhaps backed up somewhere else, if so where?   (I did search for them, but no joy so far).]

Thanks for considering this.

**Comment by aGrimRepoMan** [comment]
Update:  This happened again today, the scenario being very similar except that this time there was no KB<xxxxxxx> update.  So, the problem doesn't seem to be triggered by Windows OS updates.

**Comment by mscraigloewen** [comment]
Was there anything you can think of that could have triggered the distro being reset? When it's reset does it say `Installing Please Wait..` And then ask you to create a new user?

And also if you'd like to save a snapshot of your distro please use the `wsl export` function, and you can import that back. That way if this happens again you can at least have a saved version of the distro to restore back to.

**Comment by aGrimRepoMan** [comment]
Yes, when it resets I see the messge "Installing Please Wait..." and it asks me to create a new user.

I haven't been able to find a definitive trigger. After happening twice in three days, it hasn't happened since.   The only changes I can think of are:
1. I had a Windows task running at system start-up which starts sshd on WSL1 Debian - after finding/reading https://github.com/microsoft/WSL/issues/4063, I delayed that task for 2 minutes post system start-up. 
2. In general, now that I have my WSL Debian distribution set up the way I need it, I'm not restarting very often.

Since the issue seems similar to 4063, I'd suggest marking it as a duplicate of 4063.  Has your team had any feedback from the store team on the following likely pertinent comment: https://github.com/microsoft/WSL/issues/4063#issuecomment-494863775   ?

p.s. Thanks for the tip on "wsl export".

**Comment by mscraigloewen** [comment]
Agreed, I'll mark this as a duplicate for #4063 and we can continue the conversation there if this issue keeps surfacing. I'll follow up with the Store team to see if anything has changed on their end.
