### ISSUE TITLE
`ln -s` returns `Input/output error` in existing files

### ISSUE THREAD

**Issue by EvHaus** [Microsoft/WSL#435]
Using Build 14352, I'm still seeing some odd symlink issues. For older files which were created using the Windows file system, I will get this error when trying to symlink to them:

```
ln: failed to access ‘/mnt/r/Work/my_project/src/cordova.js’: Input/output error
```

However, creating a new file in that same directory (via `touch`) and then symlinking to that new file -- works just fine.

What is the reason that symlinks might fail for existing Windows files? And is there anything I can do to get Bash on Windows to play nice with them again? The permissions seem to be `root / root` on all directories so I'm not sure if it's a permission problem or what...

**Comment by russalex** [comment]
Haven't seen this one yet.  What are the permissions on the file you're trying to link to and does it happen on any file created by Windows?

Tried to repro with a local file with no success:

> russ@RUSSALEX-BOOK:/mnt/c/Users/russalex/Saved Games$ ll
> total 12
> drwxrwxrwx 2 root root   0 May 31 11:25 ./
> drwxrwxrwx 2 root root   0 May 31 13:31 ../
> -rwxrwxrwx 1 root root 282 May 31 11:25 desktop.ini*
> russ@RUSSALEX-BOOK:/mnt/c/Users/russalex/Saved Games$ ln -s desktop.ini foo
> russ@RUSSALEX-BOOK:/mnt/c/Users/russalex/Saved Games$ ll
> total 12
> drwxrwxrwx 2 root root   0 May 31 16:20 ./
> drwxrwxrwx 2 root root   0 May 31 13:31 ../
> -rwxrwxrwx 1 root root 282 May 31 11:25 desktop.ini*
> lrwxrwxrwx 1 root root  11 May 31 16:20 foo -> desktop.ini*

**Comment by EvNaverniouk** [comment]
I think I see the issue. Symlinks created via Windows are not compatible with symlinks created via Bash On Windows. Steps to reproduce issues:

**CASE 1**

- Using "Bash On Windows" create a symlink, ie: `touch test.txt && ln -s test.txt link.txt`
- Using Windows Explorer navigate to that directory and try to launch `link.txt`
- The following error appears:

![test](https://cloud.githubusercontent.com/assets/226640/15695733/344cd568-275f-11e6-96a4-bbc1c0add5cf.png)


**CASE 2**
- Using "cmd.exe" create a symlink, ie. `mklink link.txt test.txt`
- Using "Bash On Windows" navigate to that directory and try to launch `link.txt` (ie. `tail link.txt`)
- The following error appears:

```
tail: cannot open ‘link.txt’ for reading: Input/output error
```

**Comment by russalex** [comment]
Correct.  Symlinks created in Bash on Ubuntu on Windows are not windows symlinks.  This is by design for the Anniversary edition.

Please feel free to vote on our [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) to help us prioritize if this type of cross system behavior.  I believe the User Voice page for this specific issue is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13347663-symlinks-and-pathing).

**Comment by benhillis** [comment]
We have made some massive improvements to the ways symlinks interact between NT and Windows Subsystem for Linux.  Please give this a try on a recent Windows Insider build.
