### ISSUE TITLE
WSL1: VSCode

### ISSUE THREAD

**Issue by Smerdokryl** [microsoft/WSL#4350]
* Your Windows build number:  10.0.18362.239

* What you're doing and what's happening:  At some point after a Windows update, `code . ` would no longer be recognised as a command (though it still was in PATH), so I had to add the path to code.exe as an alias. Since then, VSCode cannot save any edited/new files in my git repo folder because of 'Insufficient permissions'. Retrying as admin does not help.

* What's wrong / what should be happening instead: Files should be saving properly, as they used to.

**Comment by gmsantos** [comment]
Did you tried [VS Code Remote extension](https://devblogs.microsoft.com/commandline/an-in-depth-tutorial-on-linux-development-on-windows-with-wsl-and-visual-studio-code/)?

**Comment by Smerdokryl** [comment]
> Did you tried [VS Code Remote extension](https://devblogs.microsoft.com/commandline/an-in-depth-tutorial-on-linux-development-on-windows-with-wsl-and-visual-studio-code/)?

I have it installed and enabled. Reinstalling does not help.

**Comment by Biswa96** [comment]
@Smerdokryl AFAIK, WSL2 is available in fast ring insider builds. Your build isn't in that.

**Comment by Smerdokryl** [comment]
> @Smerdokryl AFAIK, WSL2 is available in fast ring insider builds. Your build isn't in that.

Yes, you are right

**Comment by Biswa96** [comment]
Then check if files have correct permission and ownership. Try to use `/etc/fstab` or `/etc/wsl.conf` to modify permissions. Ready-made sample here https://github.com/WhitewaterFoundry/pengwin-base/blob/master/wsl.conf.

**Comment by Smerdokryl** [comment]
@Biswa96 There is no fstab in etc at all. My `wsl.conf` at the moment contains only `root = "/"`. Should I add `enabled = true`, or something else?

Also, I noticed that, having removed the alias, the code command still works on my original sudo user, but does not work on my second non-sudo user - how could I fix this?

**Comment by Smerdokryl** [comment]
So I changed the code alias to point to `/bin/code` rather than `Code.exe`, and now I'm getting the following errors when I run the command:

```
Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
