### ISSUE TITLE
Write Files to Windows Host is Too Slow

### ISSUE THREAD

**Issue by sunstarchan** [microsoft/WSL#4352]
I have an application which is running on WSL2 Ubuntu 18.04. The application will try to save some files to a dedicated folder, which I point to Windows host folder such as /mnt/c/Users/XXXX/projects/. I find it takes too much time to finish the writing process compared to WSL 1. I have no precise performance data. 

Is this a potential problem of different file system? 

* Microsoft Windows [version 10.0.18945.1001]
* Ubuntu 18.04

**Comment by Biswa96** [comment]
Duplicate of https://github.com/microsoft/WSL/issues/4197. Workaround, use `~/` instead of `/mnt`.

**Comment by sunstarchan** [comment]
@Biswa96

**Comment by thedipling** [comment]
I found also this
https://github.com/microsoft/WSL/issues/4197

and I do have the problem that all distros using winsows folders are slow as heck - I cannot tell you when this started with mine wsl2 installation
