### ISSUE TITLE
Almost always can't import a distro

### ISSUE THREAD

**Issue by SeanTAllen** [microsoft/WSL#4354]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18945.1001]   

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I exported a distro. When I run:

```
wsl --import Primary ..\wsl-vms\primary\ .\ubuntu.tar   
```

to import it, almost every time I get the following error:

```
The specified network name is no longer available.   
```

1 time out of about 20 so far, it managed to successfully import.

* What's wrong / what should be happening instead:

It should import as a new Distro named 'Primary'

* Additional note:

The distro in question is WSL2 distro.

**Comment by krvd** [comment]
@SeanTAllen Did you solve the problem?

**Comment by SeanTAllen** [comment]
@krvd problem still exists.

**Comment by Biswa96** [comment]
Can you install a distro as WSL1 then convert to WSL2? Did you try the command without specifying those dot (that is using absolute path)?

**Comment by therealkenc** [comment]
A me2. Haven't managed to converge on a concrete work-around. Post above might work, IDK. I think, but can't prove, if you have any other WSL2 distro live then the underlying VM won't timeout. I also kept `\\wsl$` open in Windows Explorer on a unsupported theory that might help (it probably doesn't). Once it takes, you move on pretending it never happened so...

![image](https://user-images.githubusercontent.com/7049700/64082230-ad03b800-ccc0-11e9-9bab-31e5ea581b82.png)

**Comment by Biswa96** [comment]
All good in 18970.

**Comment by therealkenc** [comment]
Not here unfort:

![image](https://user-images.githubusercontent.com/7049700/64082662-4930bd80-ccc7-11e9-81c9-aa58dcf7dc4c.png)

**Comment by therealkenc** [comment]
Above screencap was on 18970 fwiw. My bad for not stating that. I suspect if you've got an instance running (knowingly or not) the problem won't manifest so it is difficult to conclusively declare fixed until we have some positive affirmation something change in some version 18xxx.

**Comment by Biswa96** [comment]
There is no instance running.

**Comment by KadaGuetouache** [comment]
For me i'v had Ubuntu wsl2 had the same issue :
`The specified network name is no longer available. `

what worked for me is importing the distro and converting it to wsl2 at the same time even the original distro is wsl2
`wsl --import Ubuntu C:/wsl/ G:/ubuntu.tar --version 2` .

That do the trick for i hope anyone will find this helpful instead of importing it as wsl-1 then do the convert to wsl-2.
