### ISSUE TITLE
treceroute is not working with ICMP

### ISSUE THREAD

**Issue by jayph88** [microsoft/WSL#4355]
* Windows build number:  Version 10.0.17763.503

* What am i doing and what's happening: 
unable to traceroute through ICMP packets
# traceroute -I google.com

connect: Operation not supported

* What's wrong / what should be happening instead:
i am expecting actual hops taken to connect to google.com
instead i am getting error "connect: Operation not supported"

* Strace of the failing command: 
https://gist.github.com/jayph88/1a08b0c79e7668cd184e6dc3f0a450c8

**Comment by owennewo** [comment]
Probably not much help to you but it works in wsl2

Although my version of ubuntu doesn't recognise -l as a traceroute flag

**Comment by therealkenc** [comment]
#2249. Addressed in WSL2.
