### ISSUE TITLE
Os Build: 18945 Can't access local development via domain name in hosts file

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/WSL#4356]
I love that `localhost` has been implimented in 18945 but we also need maping to `127.0.0.1` for use with the hosts file as this still isn't working so I still need to get the ip address each time i boot or shutdown wsl.

**Comment by SonicGD** [comment]
Hello. We are facing similar problem with wsl2 ports mapped to [::1] and not to 127.0.0.1 cause some of our libraries can't work with ipv6.

**Comment by scrossan-crown** [comment]
Is there a way to represent this in the hosts file?

**Comment by Drakota** [comment]
@scrossan-crown You can do this in your hosts file
```
127.0.0.1 yourdomain.local.com
::1 yourdomain.local.com
```

**Comment by scrossan-crown** [comment]
@Drakota I have tried that but it didn't work for me

**Comment by Drakota** [comment]
@scrossan-crown 
At the moment there's alot of issue with localhost being inconsistent and not working sometimes so I think you're affected by this.

See
#4347 
#4340

**Comment by glenfordwilliams** [comment]
doesn't work for me

```
127.0.0.1 yourdomain.local.com
::1 yourdomain.local.com
```

**Comment by europaisch** [comment]
@Drakota's solution works in 19018

**Comment by ZdenekKrcal** [comment]
> @Drakota's solution works in 19018

Yes it is working but it so slow now. In WSL 1 websites under localhost was really fast but WSL is too slow in this topic.

**Comment by ZdenekKrcal** [comment]
It is necessary to move website to linux directory etc /home/username and then website is really fast now. But it would be nice to have same speed in /mnt/c

**Comment by Drakota** [comment]
@ZdenekKrcal For WSL 2, it is necessary to move it to a Linux partition. IIRC they are also working on improving this.
