### ISSUE TITLE
Guidance : Setting environment variable permanently

### ISSUE THREAD

**Issue by sherry-ummen** [microsoft/WSL#4359]
I am playing with WSL and the first thing I am stuck is setting environment variable. I have gone through a bunch of Stack overlow and github issues and they are not giving me a common understanding.

I have tried to edit the ~/.profile, but that does not work either.

Could some one please add a documentation about it on How to set the environment variable permanently.

**Comment by Biswa96** [comment]
You may try adding this `export PATH=/path/to/folder:$PATH`.

**Comment by sherry-ummen** [comment]
thanks. hmm I am trying to add a new environment variable. I have used export but I think its for the session only and if you close the terminal its lost. Correct me if I am wrong.

**Comment by Biswa96** [comment]
You can add those environment variables in `.bashrc` file (or other if required).

**Comment by sherry-ummen** [comment]
tried that already as well.

**Comment by owennewo** [comment]
Is your wsl distro ububtu?  If it is then .profile and .bashrc will both work (I've tried).

If it's not working then I reckon you should check the following
 - are you editing .bashrc and .profile in the correct directory?  It should be the logged in users home directory.  e.g. I'd use vi ~/.profile to edit
- have you closed and reopened the terminal.  The file only gets reloaded when the terminal starts (or if you 'source' the file).
- are you absolutely certain its not been set?  e.g. if you type 'env | grep PATH' it will show what its set to.  
- Finally - It's easy to get confused with paths when swapping betweeb win10 and linux e.g c:\windows is /mnt/c/windows in your wsl shell

**Comment by DHowett-MSFT** [comment]
Just FYI: this is something you can find [all](https://www.bing.com/search?q=bash+set+environment+variable+permanent) [over](https://www.google.com/search?q=linux+set+environment+variable+permanently) the [internet](https://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables).

**Comment by 0xbadfca11** [comment]
Do you have a ``.bash_profile``?
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

**Comment by sherry-ummen** [comment]
Aah sorry my bad. I have been using ZSH and yes ubuntu so all I had to to is to put it in .zshrc.

Btw I am not a linux guy but is this standard way of keeping global environment variables in linux world?

**Comment by owennewo** [comment]
I wish there was a standard!  

You've got your 'all user' files too e.g. /etc/profile  or /etc/environments but they don't all work in all distros and all shells.

**Comment by PhilParisot** [comment]
@sherry-ummen any idea on how to achieve this with regular Ubuntu Bash WSL? I'm having the same issue currently, added my variables to ~/.bash_profile, ~/.profile.

**Comment by sherry-ummen** [comment]
my issue was that I was using zsh and setting the env variable to .bash_profile that does not work, I had to add it to .zshrc . Also, I don't use windows any more so I cannot test what is the situation now. sorry :(

**Comment by ritchiecarroll** [comment]
@PhilParisot -- a million thanks - all the articles you find say to add the variables to `/etc/environment` or `~/.bashrc`, neither of which seem to work under WSL2. Adding to `~/.bash_profile` did the trick.

**Comment by ClintRajaniemi** [comment]
@PhilParisot - another thumbs up for this if anyone comes around. I was able to simply `cp .profile .bash_profile` and it solved the problem.

**Comment by kiratot** [comment]
What did the trick for me was setting the env variables in one line as follow in the `~/.bash_profile`:
`export API_KEY="something" && export ANOTHER_VAR="somethingelse" && export VAR="foo"`

**Comment by namaljayathunga** [comment]
sudo nano ~/.bashrc

add your command as alias

    alias laravel='~/.config/composer/vendor/laravel/installer/bin/laravel'

**Comment by xtcprzemek** [comment]
To create an environment variable which will be visible for all users on Ubuntu you can create a sh file in /etc/profile.d folder.
In example :
`sudo vi /etc/profile.d/my_vars.sh && sudo chmod o+r /etc/profile.d/my_vars.sh`
then include there your variables. For example:
`export ORACLE_HOME="/opt/oracle/instantclient_11_2"`

terminate and start wsl again. Variables should be accessible for all users.
