### ISSUE TITLE
WSL is unkillable without rebooting. Access denied as Administrator

### ISSUE THREAD

**Issue by hexosphere** [microsoft/WSL#4360]
I read the issue #1086, but now is closed and I didn't find any info for the current windows.

_Originally posted by @Herz3h in https://github.com/microsoft/WSL/issues/1086#issuecomment-456149491_

@Herz3h replied after the issue closure, and I have likelly the same.

Microsoft Windows [Version 10.0.17763.615]

C:\WINDOWS\system32>sc queryex LxssManager

SERVICE_NAME: LxssManager
        TYPE               : 30  WIN32
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x2
        WAIT_HINT          : 0xea60
        PID                : 14872
        FLAGS              :

C:\WINDOWS\system32>taskkill /f /PID 14872
ERROR: The process with PID 14872 could not be terminated.
Reason: Access is denied.

C:\WINDOWS\system32>

How does people to reboot their WSL/linux distro without rebooting the entire Windows or having to unprotect the service in the registry ?
I don't want to hack the LxssManager, just wanna shutdown it or restart it...

Thanks in advance

**Comment by owennewo** [comment]
I don't think you can reboot it, you can terminate it though
wslconfig /t Ubuntu-18.04
It'll start up again

**Comment by hexosphere** [comment]
> I don't think you can reboot it, you can terminate it though
> wslconfig /t Ubuntu-18.04
> It'll start up again

Is it not the same behaviour than closing all terminals/shells connected to the distro ?
I closed all the shells, but when I relaunch the distro, the uptime doesn't fall to zero, I guess then the distro didn't reboot for reloading system stuff for instance.

**Comment by ignorabilis** [comment]
@owennewo, I've tried a lot of things but nothing seems to be working. Here's a list of them: 
1. `wslconfig /t Ubuntu (Default)' just hangs
2. Trying to stop `LxssManager` from `Services` shows a loading window, but after some time this message appears:
```
Windows could not stop the LxssManager service on Local Computer.
Error 1053: The service did not respond to the start or control request in a timely fashion
```
Then in `Services` `LxssManager` hangs at `Stopping`.
3. Finding the pid and trying `taskkill /f /pid 11111` returns an error (yes, I'm admin):
```
ERROR: The process with PID 840 could not be terminated.
Reason: Access is denied.
```
4. Although the same, but for completeness - doing `Stop-Process 11111 -Force` yields ` Access is denied`
5. Using the built-in admin and trying `taskkill` or `Stop-Process` yields the same errors.

Microsoft Windows [Version 10.0.18362.207]

```
SERVICE_NAME: LxssManager
        TYPE               : 30  WIN32
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x2
        WAIT_HINT          : 0xea60
        PID                : 11111
        FLAGS              :
```

**Comment by therealkenc** [comment]
> C:\WINDOWS\system32>taskkill /f /PID 14872
> ERROR: The process with PID 14872 could not be terminated.
> Reason: Access is denied.

That's by-design per [message](https://github.com/microsoft/WSL/issues/1086#issuecomment-324571901). `wsl.exe -t <Distro>` is the newspeak for shutting down WSL. If that isn't working, please re-file under a different cover.
