### ISSUE TITLE
WSL2 - Unable to access localhost:3000 from Windows browser

### ISSUE THREAD

**Issue by krushi123** [microsoft/WSL#4365]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows build 18945.
* What's wrong / what should be happening instead:
I have installed WSL2 using the guide https://docs.microsoft.com/en-us/windows/wsl/wsl2-install 
After installing, I have installed ruby and rails in the Linux local file system.
The installation has visible speed change compared to wsl1 and went smoothly. 
Now, when I try rails s - It shows tcp:localhost:3000 has Puma server listening, but, when I type localhost:3000 in the Chrome browser in Windows, I get nothing. 
I tried rails -b 0.0.0.0 s also, to bind the server, still nothing happens.

**Comment by krushi123** [comment]
Unsure what happened. I got 18950 build today. Once I have upgraded and reinstalled WSL2, now, when I tried rails -b=0.0.0.0, it started working.
WSL2 has an order of speed difference when compared to WSL1. Thanks for all the effort.

**Comment by NEKN3X** [comment]
In my environment

wsl2 react server localhost;3000 is OK
I can open react page.

wsl2 rails server localhost:5000 is NG
I can't connect my rails API.

I am sorry I can't speak English well.

**Comment by craigloewen-msft** [comment]
@NEKN3X please open a new issue detailing what build of Windows you are using and what problem you're running into and we'll help you out there! :)
