### ISSUE TITLE
Whitespace after processors= global option causes option to be ignored

### ISSUE THREAD

**Issue by Bleeping** [microsoft/WSL#4367]
Your Windows build number: Microsoft Windows [Version 10.0.18945.1001]

What you're doing and what's happening: Testing the global options feature recently announced.

For the processors option, you cannot have whitespace after the value.

For example, this option will not work:

processors=2            # How many processors to assign to the WSL2 VM.

The memory option, though, has no issue when adding it like this:

memory=3GB              # How much memory to assign to the WSL2 VM.

Removing the whitespace after the processors value, works fine:

processors=2

What's wrong / what should be happening instead:

Amount of processors shown using top should reflect the global option value. Instead it shows that the VM is using all of the available processors on the host.

![image](https://user-images.githubusercontent.com/5934041/62307242-3f5e3500-b451-11e9-9a0b-14db14d3f7ea.png)

**Comment by benhillis** [comment]
Thanks, I'll sort this out.

**Comment by jrnewton** [comment]
Is this bug still open?
