### ISSUE TITLE
[18945/18950] WSL2 localhost sometimes stalls in Chrome (curl seems to work)

### ISSUE THREAD

**Issue by shayne** [microsoft/WSL#4368]
Microsoft Windows [Version 10.0.18950.1000]
(also happened on last 18945 build)

* Node app running, bound to 0.0.0.0:3000
* Launch Chrome and navigate to localhost:3000 and it works as intended
* Make code changes in text editor (VSCode FWIW)
* Hit refresh
    * Sometimes it works and the page reloads
    * More often, the browser stalls on "connecting to localhost". It doesn't seem to resolve itself, usually I close the tab and reopen it and it starts working. But sometimes it takes multiple attempts.

It's worth noting that while I'm struggling in the browser, if I `curl localhost:3000` from PowerShell, I've never had it hang there, it always seems to work.

* What's wrong / what should be happening instead:

Since I started using the new localhost feature of WSL2 I experience this hang-up in the browser where it's not reloading. I'd expect it to reload without any trouble.

**Comment by Drakota** [comment]
Duplicate of #4340 
Seems to be a keepAlive issue

**Comment by shayne** [comment]
I agree- thanks for linking, I failed to find it before creating this issue.

Closing, Dupe of #4340
