### ISSUE TITLE
brew doctor hopelessly slow

### ISSUE THREAD

**Issue by pcbeard** [microsoft/WSL#4370]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.267]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
In WSL (I use Debian/GNU Linux), install linuxbrew (https://docs.brew.sh/Homebrew-on-Linux). On my system, I have 77 programs installed (brew list | wc -l). Once it's installed, run the following command:

`time brew doctor`

On my system, here's the output:

     Your system is ready to brew.
     brew doctor  1.86s user 8.03s system 11% cpu 1:23.02 total

* What's wrong / what should be happening instead:

The performance of this command is incredibly bad. If I disable Windows Security Real-time protection, and run the command again, here's the output:

     Your system is ready to brew.
     brew doctor  1.81s user 5.25s system 99% cpu 7.087 total 

I've read about this numerous times; developers recommending disabling real-time protection to get back performance on their development machines. Would it be possible to disable this for the WSL system when it's working in its own file system? This performance difference is frankly striking (more than 10x faster in this case).

Another very noticeable performance difference is in `brew list` itself:

time brew list
brew list  0.28s user 1.30s system 77% cpu 2.031 total
brew list  0.39s user 1.17s system 98% cpu 1.584 total

The top line is with real-time protection enabled, bottom line with it off.

**Comment by pcbeard** [comment]
This is somewhat improved by excluding the folder

~/AppData/Local/Packages/TheDebianProject.DebianGNULinux_76v4gfsz19hv4/

in Windows Security -> Virus & threat protection -> Virus & threat protection settings -> Exclusions

But even with this setting, the execution time is:

brew doctor  2.84s user 13.36s system 66% cpu 24.545 total

**Comment by therealkenc** [comment]
#873 et al
