### ISSUE TITLE
Intending to upgrade a WSL1 instance to WSL2 by running wsl.exe from inside a WSL instance crashes the terminal.

### ISSUE THREAD

**Issue by sjetha-pason** [microsoft/WSL#4372]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 1903 (OS Build 18932.1000)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Running wsl --set-version Ubuntu-18.04 2 from inside the Ubuntu WSL instance

* What's wrong / what should be happening instead:
When running this same command from a PowerShell instance, the first error that was given was that the Virual Machine Platform feature needed to be installed. This should have been what was displayed in the Ubuntu terminal, rather than crashing the instance first. After that, either the terminal should be shut down, upgraded and then restarted, or the user should be instructed to run this command outside of a WSL instance.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by Biswa96** [comment]
You can't do that. To upgrade a WSL1 distribution, it must not have any running session.

**Comment by mscraigloewen** [comment]
Please run the command outside of the WSL distribution that you're trying to upgrade. This is something that is created by design. Thanks for filing the issue!
