### ISSUE TITLE
Shell difference between vscode remote-wsl and wsl.exe

### ISSUE THREAD

**Issue by Lips7** [microsoft/WSL#4374]
**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.18950.1000]

* What you're doing and what's happening:  Launch remote-wsl in VScode **1.37.0-insider**, `echo $SHELL`, and get `sh`. Then launch `wsl.exe` in powershell, get `/usr/bin/zsh`.
Then I get the problem, two shells don't share the same **PATH**. 

In VSCode terminal
`❯ echo $PATH   
/home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b/bin:~/anaconda3/bin:/home/lips/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program`

In wsl.exe
`❯ echo $PATH 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Microsoft VS Code Insiders/bin:/mnt/c/Users/97579/scoop/shims:/mnt/c/Users/97579/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/97579/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin:/mnt/c/Users/97579/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/97579/AppData/Local/hyper/app-3.0.2/resources/bin:/mnt/c/Users/97579/scoop/apps/hyper/3.0.2/resources/bin`

So the problem is , I can not exec the same command in both shell(cuz the **PATH**  aren't the same)
![image](https://user-images.githubusercontent.com/51849534/62419010-87779480-b6a9-11e9-8af3-dbb790091e29.png)

**Comment by Lips7** [comment]
BTW in **18950** I still can not connect to my Linux applications from Windows Browser via **localhost**, could anyone help me ?

**Comment by Biswa96** [comment]
It that distribution in WSL2? Can you add the output of `pstree -ap` in text (not image)  opening other wsl instance?

**Comment by Lips7** [comment]
Yes, it's WSL2.

`pstree -ap` here. 😓(terrible in text)
❯ pstree -ap
init,1
  ├─init,6
  │   └─init,7
  │       ├─zsh,8
  │       │   └─pstree,223 -ap
  │       └─zsh,47 -dfxc...
  │           └─gitstatusd-linu,48 --lock-fd=3 --parent-pid=8 --num-threads=8--max-num-stag
  │               ├─{gitstatusd-linu},50
  │               ├─{gitstatusd-linu},51
  │               ├─{gitstatusd-linu},52
  │               ├─{gitstatusd-linu},53
  │               ├─{gitstatusd-linu},54
  │               ├─{gitstatusd-linu},55
  │               ├─{gitstatusd-linu},56
  │               └─{gitstatusd-linu},57
  ├─init,58
  │   └─init,59
  │       ├─sh,60 -c...
  │       │   └─wslServer.sh,62 /mnt/c/Users/97579/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.39.1/scripts/wslServer.sh...        
  │       │       └─sh,66 /home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b/server.sh  --port=0 ...
  │       │           └─node,68/home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1ae
  │       │               ├─node,94/home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1ae
  │       │               │   ├─Microsoft.VSCod,182
  │       │               │   │   ├─{Microsoft.VSCod},183
  │       │               │   │   ├─{Microsoft.VSCod},184
  │       │               │   │   ├─{Microsoft.VSCod},185
  │       │               │   │   ├─{Microsoft.VSCod},186
  │       │               │   │   ├─{Microsoft.VSCod},187
  │       │               │   │   ├─{Microsoft.VSCod},188
  │       │               │   │   ├─{Microsoft.VSCod},189
  │       │               │   │   ├─{Microsoft.VSCod},190
  │       │               │   │   ├─{Microsoft.VSCod},191
  │       │               │   │   ├─{Microsoft.VSCod},192
  │       │               │   │   ├─{Microsoft.VSCod},193
  │       │               │   │   └─{Microsoft.VSCod},194
  │       │               │   ├─node,200/home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1ae
  │       │               │   │   ├─{node},201
  │       │               │   │   ├─{node},202
  │       │               │   │   ├─{node},203
  │       │               │   │   ├─{node},204
  │       │               │   │   ├─{node},205
  │       │               │   │   └─{node},206
  │       │               │   ├─zsh,118
  │       │               │   ├─{node},95
  │       │               │   ├─{node},96
  │       │               │   ├─{node},97
  │       │               │   ├─{node},98
  │       │               │   ├─{node},99
  │       │               │   ├─{node},100
  │       │               │   ├─{node},108
  │       │               │   ├─{node},109
  │       │               │   ├─{node},110
  │       │               │   ├─{node},111
  │       │               │   ├─{node},116
  │       │               │   ├─{node},117
  │       │               │   ├─{node},119
  │       │               │   ├─{node},141
  │       │               │   └─{node},181
  │       │               ├─node,101/home/lips/.vscode-server-insiders/bin/0bd57ac9efae79f9eb1ae
  │       │               │   ├─{node},102
  │       │               │   ├─{node},103
  │       │               │   ├─{node},104
  │       │               │   ├─{node},105
  │       │               │   ├─{node},106
  │       │               │   ├─{node},107
  │       │               │   ├─{node},112
  │       │               │   ├─{node},113
  │       │               │   ├─{node},114
  │       │               │   └─{node},115
  │       │               ├─{node},69
  │       │               ├─{node},70
  │       │               ├─{node},71
  │       │               ├─{node},72
  │       │               ├─{node},73
  │       │               ├─{node},74
  │       │               ├─{node},75
  │       │               ├─{node},76
  │       │               ├─{node},77
  │       │               ├─{node},78
  │       │               └─{node},81
  │       └─zsh,167 -dfxc...
  │           └─gitstatusd-linu,168 --lock-fd=3 --parent-pid=118 --num-threads=8--max-num-st
  │               ├─{gitstatusd-linu},170
  │               ├─{gitstatusd-linu},171
  │               ├─{gitstatusd-linu},172
  │               ├─{gitstatusd-linu},173
  │               ├─{gitstatusd-linu},174
  │               ├─{gitstatusd-linu},175
  │               ├─{gitstatusd-linu},176
  │               └─{gitstatusd-linu},177
  └─{init},5

**Comment by Lips7** [comment]
> It that distribution in WSL2? Can you add the output of `pstree -ap` in text (not image) opening other wsl instance?

Opening other wsl instance, just show the same as executing `wsl` in **powershell** , **cmd** or just the **Ubuntu**.

**Comment by Biswa96** [comment]
I can not reproduce the issue, maybe the `$PATH` is not too long as yours. There is an option to change default shell in VSCode terminal setting. Like this:

![Capture](https://user-images.githubusercontent.com/31443074/62422422-1b5c5700-b6d0-11e9-8449-01e33fdf203a.PNG)

Also you can add the following line in `settings.json` file

    "terminal.integrated.shell.linux": "/bin/bash"

**Comment by Lips7** [comment]
> I can not reproduce the issue, maybe the `$PATH` is not too long as yours. There is an option to change default shell in VSCode terminal setting. Like this:
> 
> ![Capture](https://user-images.githubusercontent.com/31443074/62422422-1b5c5700-b6d0-11e9-8449-01e33fdf203a.PNG)
> 
> Also you can add the following line in `settings.json` file
> 
> ```
> "terminal.integrated.shell.linux": "/bin/bash"
> ```

I realize what the problem is，I did‘t login in with superuser，and do everything in remote-wsl instead wsl.exe.
So I reinstall the whole WSL2 system. FML.

**Comment by Lips7** [comment]
It seems like some scripts rewrite the `PATH`, so I can not accesss windows program in remote-wsl. 
The major difference  is there is no `user PATH` in wsl.exe, such like `/home/lips/.local/bin`, but `windows' PATH` exit. And the remote-wsl contain `user PATH` but no windows'.

**Comment by mscraigloewen** [comment]
I chatted with the VSCode team about this issue and they've put in a pull request to resolve it. This should be available in a VSCode update soon™!

**Comment by Lips7** [comment]
Thanks!
