### ISSUE TITLE
WSL2 import sets wrong WSL-version

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#4380]
If you export a distro, that was converted to WSL2, and import it again (under a different name), the version is set to 1.

### Expected behaviour
Convert distribution to WSL2
Export
Import distribution ends up being WSL2

### Actual behaviour
Convert distribution to WSL2
Export
Import distribution ends up being WSL1

**Comment by Biswa96** [comment]
That's why `wsl.exe --import` has another option `--version`. See the `--help` output.

**Comment by Biswa96** [comment]
That's why `wsl.exe --import` has another option `--version`. See the `--help` output. If yoi don't want WSL1, just use `--set-default-version 2`.

**Comment by Biswa96** [comment]
That's why `wsl.exe --import` has another option `--version`. See the `--help` output. If you don't want WSL1, just use `--set-default-version 2`.

**Comment by ad-on-is** [comment]
Ah, I see. Is there a way to see what `default-version` is set right now, since I remember that I've already set it to `2` some time ago.

**Comment by Biswa96** [comment]
Here is the registry:

```ini
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"DefaultVersion"=dword:2
```
