### ISSUE TITLE
apt failed to update (but internet is working)

### ISSUE THREAD

**Issue by Junn-Sorran** [microsoft/WSL#4382]
**Please fill out the below information:**
* Windows build number:  Microsoft Windows [version 10.0.16299.1217]
* wsl version : Linux XXXX 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

* What you're doing and what's happening:  
I'm trying to run apt-get update on a fresh install of ubuntu wsl
    - I can ping google.com () any other websitess
    - I can curl "http://archive.ubuntu.com/ubuntu" (or any other repos ) 
    - I don't have any proxy, just direct internet connection
    - I didn't touch any apt config files

```
# apt-get update
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
0% [Working]^C
```

* What's wrong / what should be happening instead:
apt should be updating fine

I'm a bit lost, I saw many similar issues here, but everyone else had some kind one internet access issues with wsl, in my case the only issue is with apt since I tested that wsl can reach the repos in http.

**Comment by mscraigloewen** [comment]
This seems like it could be a firewall or anti-virus issue. Do you have any of those enabled? If you disable them and try `apt update` does it work?

**Comment by Junn-Sorran** [comment]
Hello,
I have a corporate computer with a mcafee antivirus, but I can't disable it. (I was connected to a different wifi for my test, so I had free internet access and no proxy)

That's weird because all my colleagues have the same computer model installed with the same os images et the same antivirus rules. And nobody else has theses problems

**Comment by mscraigloewen** [comment]
Perhaps this solution from issue may help connectivity for apt update:
https://github.com/microsoft/WSL/issues/3647#issuecomment-517047815

If you try that, does it fix your problem?

**Comment by Junn-Sorran** [comment]
No I tried that already but I think we have a ntlm proxy and that linux does not support the connection to it.
But anyway this problem happen when I'm not behind any proxy so it doesn't matter. But in the post you linked I don't see the link bettween McAfee Endpoint Security and the proxy you can't bypass an antivirus just by setting up a proxy right?

**Comment by mscraigloewen** [comment]
You're right that was my mistake, if you're accessing the internet without a proxy then that solution wouldn't help you. 

These network problems are difficult do diagnose, my best guess is that it has something to do with your antivirus since you're able to curl to the repos. Is this the case with other repos as well like Debian or OpenSUSE? And I realize you're on a corporate computer, but updating your Windows version to a more recent one will also help WSL's general performance.

**Comment by ParkerM** [comment]
@Junn-Sorran Re: apt.conf proxy settings

Have you also tried adding a line for `Acquire::https::Proxy`?  
My proxy-friendly apt.conf contains the following two lines:
```conf
Acquire::http::Proxy "http://myUserId:myPassword@my.proxy.example.com:1234";
Acquire::https::Proxy "http://myUserId:myPassword@my.proxy.example.com:1234";
```

**Comment by Junn-Sorran** [comment]
Yeah, I think I did tried it and it didn't work.

Anyway, I gave up on ubuntu and switched to debian wsl, I strangely had no issues with it.

**Comment by trinhpham** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/9128061/75992874-37a4c880-5f2b-11ea-9aaf-191d5bd3cbb4.png)

Windows version: 2004 build 19041.113
WSL 2: Linux HLVTRINH-MSI 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have no idea to find what is happening...

**Comment by Junn-Sorran** [comment]
Did you try to use the debian image instead? It was mutch better for me
