### ISSUE TITLE
resolv.conf is not persisted between sessions

### ISSUE THREAD

**Issue by nicoabie** [microsoft/WSL#4383]
* Your Windows build number: Microsoft Windows [Version 10.0.18950.1000]

* What you're doing and what's happening:
I modified /etc/wsl.conf setting generateResolvConf = false.
I added a nameserver to /etc/resolv.conf that works
(the name server generated automatically doesn't work)

* What's wrong / what should be happening instead:
The resolv.conf gets deleted after I shutdown wsl.
I believe that if I opted out of it being generated it should not be removed.

**Comment by Biswa96** [comment]
After effect of this https://github.com/microsoft/WSL/issues/4210.

**Comment by benhillis** [comment]
/etc/resolv.conf is typically a symlink to tmpfs.  You will have to also replace the symlink wih a regular file.

**Comment by therealkenc** [comment]
Same as #3928
