### ISSUE TITLE
WSL background transparancy doesn't stay when switched to different window

### ISSUE THREAD

**Issue by adampann** [microsoft/WSL#4386]
* Your Windows build number: Microsoft Windows [Version 10.0.18362.10005]

* What's wrong / what should be happening instead: When WSL is setup to have a transparent background it works when the window is in focus but clicking away from WSL converts it back to full opacity.
When in focus:
![image](https://user-images.githubusercontent.com/25598414/62677515-722d8f00-b963-11e9-9f4d-8f20e85860db.png)
When click away:
![image](https://user-images.githubusercontent.com/25598414/62677596-c6387380-b963-11e9-8232-4258797ad4f8.png)

**Comment by mscraigloewen** [comment]
This issue is more appropriate on the [Terminal issue page](https://github.com/microsoft/terminal/issues/1375) as we do not control the Terminal/Console here on the WSL team.
