### ISSUE TITLE
Getting Permission error num. 13 on Jupyter Notebook with Mnist database

### ISSUE THREAD

**Issue by LukyMentor** [microsoft/WSL#4390]
Hello,
I am trying to make my first neural network. I would like to use Jupyter's Notebook with MNIST dabase of letters. (I am running Jupyter ntb on **W10**)
When using this code:

```
pip install python-mnist --user

from mnist import MNIST 

with open('C:\\Users\\path\\to\\the\\samples') as file:
    mndata = MNIST(file)
    file.close()

images, labels = mndata.load_training()

```
I get this error:

```
PermissionError                           Traceback (most recent call last)
<ipython-input-3-3f4a73fe9c75> in <module>
      1 from mnist import MNIST
      2 
----> 3 with open('C:\\Users\\path\\to\\the\\samples') as file:
      4     mndata = MNIST(file)
      5     file.close()

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\path\\to\\the\\samples'
```

Thanks for the help!

**Comment by mscraigloewen** [comment]
This seems like a Linux permissions issue. If you run the command with `sudo` does it install correctly?

**Comment by LukyMentor** [comment]
> 
> 
> This seems like a Linux permissions issue. If you run the command with `sudo` does it install correctly?

I can't, because I am working on Windows 10

**Comment by mscraigloewen** [comment]
Ah I see that now in your output. Are you using the Windows Subsystem for Linux at all? From the info provided it looks like you're just using pure Windows tools.

If you're running this using the Windows 10 version of Python, and are not using the Windows Subsystem for Linux then there isn't anything we can help you with on this Github page.

**Comment by LukyMentor** [comment]
Oh, I see! I am sorry to be bothering you! This was my first time using GitHub

**Comment by mscraigloewen** [comment]
No problem! I'd recommend posting your issue to the [Jupyter Notebook github repo](https://github.com/jupyter/notebook) and I'm sure they'd be able to help you out. Good luck!
