### ISSUE TITLE
WSL2: Access Linux Web Server from Windows. Connection failed

### ISSUE THREAD

**Issue by supermuka** [microsoft/WSL#4392]
I can not access from the Windows browser the web server running on the Linux subsystem.

Based on 18945 or newer Windows Build according [this news](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/), I understand that `localhost` should be working. 

Is there a additional configuration that needs to be applied to network "talk" between Linux subsytem and Windows?

Following details:

**Steps:**

1. Windows Insider Release - last build  updated
> Microsoft Windows [versão 10.0.18956.1000]

2. "Windows Subsystem for Linux" feature activated 
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

3. "Debian GNU/Linux" instaled
`https://www.microsoft.com/store/apps/9MSVKQC78PK6`

4. "Virtual Machine Platform" feature activated.
`Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform`

5. Set WSL2
`wsl --set-version Debian 2`

6. List wsl version
`wsl --list --verbose`

>   NAME      STATE           VERSION
> * Debian    Running         2

7. Linux IP
`ip add | grep inet`

> inet 172.17.180.64/16 brd 172.17.255.255 scope global eth0
 
8. Web Server installed and running in Linux (*)
> [INFO] Serving `web` on http://127.0.0.1:8080

*This is a development web server used by Dartlang for web started with this command `webdev serve` on project directory.

**Wrong:**

_Browser on Windows:_

http://localhost:8080

> Unable to access this site. 
> The connection to localhost was refused.

_Telnet on Windows:_
`telnet 172.17.180.64 8080`
`telnet 127.0.0.1 8080` or
`telnet localhost 8080` or
> Could not open host connection, on port 8080: connection failed

**Comment by Drakota** [comment]
Looking at the webdev command wiki page, you could try to bind web server to `0.0.0.0`.
Something like` webdev serve --hostname 0.0.0.0:8080`

**Comment by supermuka** [comment]
Great, works! You need to force `0.0.0.0` instead of using default `127.0.0.1` to `localhost`. The command is `webdev serve --hostname 0.0.0.0` or informing the port `webdev serve --hostname 0.0.0.0 web:8080`
