### ISSUE TITLE
network comms  worked in WSL 1 broken in WSL 2

### ISSUE THREAD

**Issue by keithware** [microsoft/WSL#4395]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by keithware** [comment]
Microsoft Windows [Version 10.0.18956.1000]
Using Debian distro WSL 1
At work I was able to turn on a VPN client into a customers VPN network and ssh into 40 or so servers, perform all linux terminal functions perfectly, no issues.
I upgraded to WSL 2 and now I can connect to the same servers over the VPN but directory listings, unless there's only a handful of files, or dumping a file contents to stdout with cat for example and the bash terminal hangs. I have not been able to get past any of the hangs and end up having to just close the terminal window. This looks like a network frame size type of issue as far as the symptoms of it but I don't have any control over the customers VPN configurations to try a smaller frame size (along the lines of mssfix in openvpn - but this isn't openvpn) My only option was to roll back to WSL 1 under which all of the above works flawlessly.

**Comment by craigloewen-msft** [comment]
Could you collect some networking logs for us? It would help us diagnose what the issue is. 

You can find instructions on how to do that [here!}(https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs)

**Comment by keithware** [comment]
Craig,
Thanks for the response. I will do that.

Keith Stevens
keithware.com
kstevens-software.com

**Comment by keithware** [comment]
Craig,
On mine it doesn't when I click recreate my problem it doesn't have the
include data about checkbox or the start capture button.

Keith Stevens
keithware.com
kstevens-software.com

**Comment by keithware** [comment]
but I switched to version 2, fired up the vpn, ssh'd into one of the
servers and tried to cat /var/log/syslog. It spit out about 20 lines and
froze and is unresponsive all I can do is kill the powershell window.

Keith Stevens
keithware.com
kstevens-software.com

**Comment by craigloewen-msft** [comment]
I think getting network tracing logs is still our best bet on finding out what's going on.

Are you logged into Feedback hub when submitting feedback? And what version of Feedback hub do you have? (You can find the version by opening up feedback hub, going to the settings page and scrolling to the bottom, it's under the 'About' section).
