### ISSUE TITLE
file permissions changing with new sessions

### ISSUE THREAD

**Issue by cat768** [microsoft/WSL#4396]
Windows 10 version 10.0.18362.239

I'm trying to use ssh to connect to an amazon ec2 instance.
(The name is going to be ec2.pem)
I've followed the instructions given by amazon, and moved my file from /mnt/c//Users/Username/Downloads/ec2.pem to /home/Username/WSL-path/ec2.pem

After that I sudo chmod 400 ec2.pem
After this I'm able to SSH into the vm.

However, if I close my Windows Terminal (Preview) and try to ssh into the vm again, it displays a permission error, requiring me to chmod the pem file again.

Is there any way I can prevent using chmod each time? I'm really thankful windows has a built in SSH tool right now :)

**Comment by therealkenc** [comment]
There is no CLI repro here, and no takers to speculate.
