### ISSUE TITLE
Can't set directory case sensitivity from WSL with fsutil

### ISSUE THREAD

**Issue by LostSnail42** [microsoft/WSL#4398]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.885]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

(open powershell)
```
> bash
$ fsutil.exe file setCaseSensitiveInfo testDir enable
Error:  Access is denied.
$ sudo fsutil.exe file setCaseSensitiveInfo testDir enable
sudo: fsutil.exe: command not found
$ whereis fsutil.exe
fsutil: /mnt/c/Windows/System32/fsutil.exe
$ sudo whereis fsutil.exe
fsutil:
$
```
* What's wrong / what should be happening instead:

Specified directory should have case sensitivity enabled (or disabled with disable option).

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A?
* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
N/A

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

EDIT:
This command works (without sudo) if I use an Adminstrator PowerShell, surely I don't have to sit in an Admin PowerShell at all times in case I want to use this command?

**Comment by lengthmin** [comment]
Maybe it only works in Windows Path.
It is not feasible for you to use fsutil.exe with `WSL files path` directly.

**Comment by mscraigloewen** [comment]
I'm marking this as `external` and `bydesign`.

If you try to run that .exe in powershell or CMD without Admin privileges you'll get the same error, and running it in an Admin window will resolve the error as you mentioned. WSL is calling the .exe correctly and it is behaving as expected, so this does not seem to be a WSL specific issue. Thank you for filing!
