### ISSUE TITLE
inotifywait not work on certain files on WSL

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/WSL#4399]
I tested inotifywait with three of files: ~/.bashrc, ~/.env, /mnt/c/../tmp03.md. As result, when I saved tmp03.md, there's a stdout. when I saved .bashrc or .env file, there's no stdout. thus, I think this bug caused if the file is on WSL file system directory. (  C:\Users\foo\AppData\Local\lxss\home\bar\.bashrc )

```
testinoti(){
  
  while inotifywait -o ~/inotifywait.log --quiet --timefmt "%FT%T%Z" --format "%T  %f%w  %e" ~/.bashrc ~/.env /mnt/c/owncloud_scarlet/note/tmp03.md ;
  do
      echo y 
  done 

}

```

additionally, I tested with .bashrc as symbolic link. But there's same result as above.

```
testinoti(){
  
  while inotifywait -o ~/inotifywait.log --quiet --timefmt "%FT%T%Z" --format "%T  %f%w  %e" /mnt/c/_symlinks/.bashrc /mnt/c/_junction/.bashrc /mnt/c/owncloud_scarlet/note/tmp03.md ;
  do
      echo y 
  done 

}

```

build number:  Microsoft Windows [Version 10.0.17763.615]

**Comment by therealkenc** [comment]
Can't really follow "no stdout" here, which is why this went chirping crickets. File watchers (in WSL1) were implemented some time ago. Can't reproduce here, and there were no me2s.

![image](https://user-images.githubusercontent.com/7049700/67631308-b0936580-f851-11e9-8be1-7387fad5d190.png)
