### ISSUE TITLE
File edited on windows becomes executable file on linux?

### ISSUE THREAD

**Issue by RamThirupathy** [microsoft/WSL#4409]
Hello guys, i have a text file edited on windows editor. When i save edited file that file becomes executable file when looking at my linux bash.

Any idea why is this happening and how to fix it? Also I'm not able to find the ubuntu.exe file

ubuntu :  Ubuntu 18.04.2 LTS
Windows os version: 10.0.17763 Build 17763

**Comment by Biswa96** [comment]
[Do not change Linux files using Windows apps and tools][1].

[1]: https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/

**Comment by mscraigloewen** [comment]
@Biswa96 is correct, and to add on: If you'd like to use your Windows editors on your Linux files please update your Windows version to version 1903 (The May update) or later and you will be able to do so. In the meantime while you're on an older build please store any files you wish to interact with on the Windows side of things inside of your Windows file system `/mnt/c`. 

As far as finding the `ubuntu.exe` it is installed automatically to your Appdata folder and added to your path when you install the Ubuntu app. 

I'm going to close this issue as I believe it's resolved, if you run into any further issues please feel free to reopen it. Thank you!

**Comment by RamThirupathy** [comment]
Thanks @craigloewen-msft,

I was trying it only in /mnt/c folder

{code}
kalisamyA1@kalisamyA1:/mnt/c/testing/VCTRS-7156$ pwd
/mnt/c/testing/
{code}

Also I'm not able to find the ubuntu.exe in appData folder
{code}
kalisamyA1@kalisamyA1:/mnt/c/Users/kalisamya/appdata$ ls -a
.  ..  Local  LocalLow  Roaming
{code}

All was working in my previous windows 10 laptop which had,
{code}
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
{code}

**Comment by craigloewen-msft** [comment]
No problem I'll reopen the issue for you. So you have two issues rolled up into one here so I'll try and separate them.

## Setting file permissions

To change your default file permissions you need to change the [umask](https://www.mysoftkey.com/linux/what-is-umask-what-is-default-umask-and-how-to-set-new-umask-in-linux/) value of the mounted drive. You can do this using `wsl.conf`. [Here's](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/) the blog post describing it, and [here's](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings) our documentation on it. In your case, to make sure any files in your Windows drives won't be marked as executable do this: 

- Create and open `/etc/wsl.conf` in a text editor.
- Add the following: 

```
[automount]
enabled = true
options = "metadata,umask=011"
```

This will remove executable permissions from files in your C: drive

## Finding ubuntu.exe

`ubuntu.exe` is installed automatically when you start WSL, you don't need to go digging in your Appdata to go find it. 

If you open Powershell or CMD and run the command `ubuntu.exe` what happens? Your distro should just start.

**Comment by RamThirupathy** [comment]
@craigloewen-msft 
Tried updating the /etc/wsl.conf as you mentioned but still the same problem, im adding more details below

```
root@kalisamyA1:/mnt/c/Windows/System32# mount -l
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /mnt/c type drvfs (rw,noatime,uid=0,gid=0,metadata,case=off)
```

Regarding `ubuntu.exe`,
In command prompt:
```
C:\Users\kalisamya>ubuntu.exe
'ubuntu.exe' is not recognized as an internal or external command,
operable program or batch file.
```

In Power shell:
```
C:\Users\kalisamya> ubuntu.exe
ubuntu.exe : The term 'ubuntu.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ubuntu.exe
+ ~~~~~~~~~~
   + CategoryInfo          : ObjectNotFound: (ubuntu.exe:String) [], CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by craigloewen-msft** [comment]
Thank you for the extra details.
Seems like your wsl.conf settings aren't being set. Could you make sure that your wsl.conf file is the exact same as the one I posted above? If it's successful you should see this in C:\ when you run `mount -l`
`C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=11,metadata,case=off)  `

And to make sure, you installed using the Windows store is that correct? Could you try uninstalling (right click on the app in your start menu and click uninstall) and reinstalling it and see if that fixes it.

**Comment by rhaglennydd** [comment]
I'm having this problem. Contents of `wsl.conf`:

    [automount]
    options = metadata,case=dir,umask=22,fmask=11,uid=1000,gid=1000

(Partial) results of `mount -l`:

    C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=dir)

No issues with creating files from WSL:

    cd /mnt/c
    touch test.txt
    ls -l test.txt

(Partial) output of last command:

    -rw-r--r--

But when I create a file using a Windows application, it has these permissions:

    -rwxr--r--

I've tested this with multiple programs and in different directories.
