### ISSUE TITLE
VS Code WSL "Install from VSIX..." prepends "C:" to the path.

### ISSUE THREAD

**Issue by rdubner** [microsoft/WSL#4410]
Windows Build Number: Microsoft Windows [Version 10.0.18362.295]  
The wsl.exe file version is 10.0.18362.239
The Linux installation is Ubuntu 18.04 LTS

From a Windows command prompt I launch wsl.exe
From the resulting Linux prompt, I execute 'code -v'; the report that comes back is
``
bob@Bobtop:/mnt/c/Users/Bob$ code -v
1.37.0
036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
x64
``
I then launch 'code' from the Linux prompt.  
F1 or Ctrl+Shift+P gives me the Command Palette
I use that to get to "Extensions: Install from VSIX..."
I navigate to my VSIX file.
When I click it, an error message opens in the lower left corner of the window:

``
ENOENT: no such file or directory, open 'C:\home\bob\projects\test\test.vsix'
``
The problem, of course, is that "C:" that somehow found its way onto the front of the path I specified.

Since it's difficult to imagine this behavior is "as designed", it seems to me that you got yourselves a bug.

Best regards,

Bob Dubner

**Comment by craigloewen-msft** [comment]
Was able to reproduce this! I'll cross post it over to the VS Code repo since they'll be able to track it.
