### ISSUE TITLE
exe run hangs if run inside emacs

### ISSUE THREAD

**Issue by TrunovS** [microsoft/WSL#4412]
* Your Windows build number:  
Build 18362.19h1_release.190318_1202

* What you're doing and what's happening:  
Updated Windows to 1903 update.

Running MSBuild.exe /version (or solution file) in terminal is ok:
`Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.`

Running the same MSBuild.exe (or any other exe) inside emacs (25, 26.2) hangs and doesn't return anything:
![изображение](https://user-images.githubusercontent.com/13647806/63091801-3cdaff80-bf68-11e9-88a9-da8f1e2e3a49.png)
At the same time, executing all linux specific binaries works just fine.

* What's wrong / what should be happening instead:

Running the same MSBuild.exe (or any other exe) inside emacs shell, eshell or compilation buffer (25, 26.2) hangs and doesn't return anything.
The problem repeats itself in ConEmu, new Windows Terminal, and simple instances of wsl Debian, Ubuntu distros (default cmd line) on default emacs 25 installed from apt, and 26.2 src builded.

Before Windows 1903 update running exe inside emacs shell, eshell or compilation buffer was right.
MSBuild.exe or any other command line exe program must run inside emacs shell, eshell or compilation buffer correctly.

* Strace of the failing command, if applicable:  
[ms_build_err.txt](https://github.com/microsoft/WSL/files/3505370/ms_build_err.txt)
[ms_build_ok.txt](https://github.com/microsoft/WSL/files/3505371/ms_build_ok.txt)

**Comment by TrunovS** [comment]
Update: Christopher Crawford on [https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903] talks about the same problem, but in his case, its resolved by update KB4512508 which already installed for me. After deleting this update through settings menu on my computer and reinstalling it in automatic mode problem persist,

**Comment by TrunovS** [comment]
Update: Installed KB4517211 update. Problem persists.

**Comment by TrunovS** [comment]
Update: KB4517389 also doesn't fix the problem.

**Comment by dgud** [comment]
This breaks my workflow as well, any known workarounds? emacs settings or bash that can be done?

**Comment by ambarve** [comment]
I am looking at this bug. However, until it is fixed, the workaround seems to be using `term` instead of `shell` or `eshell`. I am able to run windows binaries via term from within emacs without any issues.

**Comment by dgud** [comment]
Thanks for the workaround.

FYI the same things happens when invoking "M-x compile" with default 'make' when 'make' does the call to the window executable.

**Comment by smithzvk** [comment]
I think I hit this bug when my corp upgraded Win10 last month.  Looked into it and it seems to only be triggered when Emacs attempts to start a Windows console executable as an asynchronous process.  If you interrupt the process from eshell, then the ~conhost~ instance that seems related to it suddenly maxes out a single core and you must kill in manually from task manager.  It seems to be tied to some issue with setting up the file streams in the sub-process, or at least that is my best guess.

I found a workaround that actually works with my work-flow.  I created a program (at end) which will create a child process, read all of its stdout and stderr output and send it back out on the parent's stdout and stderr.  Why this is necessary, not sure, but it seems to do the trick.

If you customize `shell-file-name` to point to this executable and `async-shell-commad` and `compile` will start working.  Eshell does its async stuff differently and ignores the value of `shell-file-name`, so you will need to patch it to make it work as expected.

````
--- esh-proc.el	2020-03-30 22:43:46.532596300 -0500
+++ esh-proc.el.new	2020-03-30 22:49:19.360686600 -0500
@@ -283,7 +283,8 @@
 	      (apply 'start-file-process
 		     (file-name-nondirectory command) nil
 		     ;; `start-process' can't deal with relative filenames.
-                     (append (list (expand-file-name command)) args))))
+                     (append (list shell-file-name "-c")
+                             (list (mapconcat 'identity (cons command args) " "))))))
       (eshell-record-process-object proc)
       (set-process-buffer proc (current-buffer))
       (if (eshell-interactive-output-p)
````

Source of wsl-proxy (this is mostly taken from [this howto](http://www.microhowto.info/howto/capture_the_output_of_a_child_process_in_c.html))  Probably has bugs, but it seems to work for me.

````
/* This program is to work around some bug in the way WSL console handling works
 * with async processes launched from Emacs.
 *
 * Currently, processes launched in an asynchronous way cause the sub process to
 * hang and, if killed, produces a run-away conhost process which must be killed
 * from the task manager.  This seems tied to the way input/output streams are
 * handled, so we do them manually in this program and it seems to work. */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <poll.h>

int main(int argc, char *argv[])
{
   int fd_out[2];
   int fd_err[2];
   if (pipe(fd_out) == -1)
   {
      perror("stdout pipe");
      exit(1);
   }
   if (pipe(fd_err) == -1)
   {
      perror("stderr pipe");
      exit(1);
   }

   pid_t pid = fork();
   if (pid == -1)
   {
      perror("fork");
      exit(1);
   }
   else if (pid == 0)
   {
      while ((dup2(fd_out[1], STDOUT_FILENO) == -1) && (errno == EINTR)) {}
      while ((dup2(fd_err[1], STDERR_FILENO) == -1) && (errno == EINTR)) {}

      close(fd_out[1]);
      close(fd_out[0]);
      close(fd_err[1]);
      close(fd_err[0]);

      argv[0] = "/bin/sh";
      execvp(argv[0], &argv[0]);
      perror(argv[0]);
      _exit(1);
   }
   close(fd_out[1]);
   close(fd_err[1]);

   uint8_t buffer[4096];
   int keep_going[] = {1, 1};
   while (keep_going[0] || keep_going[1])
   {
      struct pollfd fds[] = {
         {
            .fd = fd_out[0],
            .events = POLLIN,
            .revents = 0
         }, {
            .fd = fd_err[0],
            .events = POLLIN,
            .revents = 0
         }
      };

      if (poll(fds, 2, -1))
      {
         for (int i = 0; i < 2; i++)
         {
            if (fds[i].revents & POLLHUP)
            {
               keep_going[i] = 0;
            }
            if (!(fds[i].revents & POLLIN))
            {
               continue;
            }

            ssize_t count = read(fds[i].fd, buffer, sizeof(buffer));
            if (count == -1)
            {
               if (errno == EINTR)
               {
                  continue;
               }
               else
               {
                  char *stream_names[] = {"stdout", "stderr"};
                  perror(stream_names[i]);
                  exit(1);
               }
            }
            else if (count == 0)
            {
               break;
            }
            else
            {
               FILE *output_streams[] = {stdout, stderr};
               fwrite(buffer, 1, count, output_streams[i]);
            }
         }
      }
   }

   int child_status;
   if (wait(&child_status) == -1)
   {
      perror("wait");
   }

   if (WIFEXITED(child_status))
   {
      close(fd_out[0]);
      close(fd_err[0]);
      exit(WEXITSTATUS(child_status));
   }

   close(fd_out[0]);
   close(fd_err[0]);
   exit(0);
}
````

**Comment by nidrissi** [comment]
One trick that seems to work is to redirect all outputs to `/dev/null` (for example by appending `2>&1 > /dev/null` to the command). See [this "hack"](https://github.com/nidrissi/dotfiles/blob/313e353dccebed3c681573bcf2dc3ec12a13f69e/local/bin/wslopen#L5) that I use.

**Comment by Thiel** [comment]
@nidrissi Thanks a lot for the tips quite functional even though clearly a hack.

Allow me to add to your advice the following alternative that preserve output log: `2>&1 | tee` or simply `| tee` seems to work too.

Enjoy

**Comment by TobiasZawada** [comment]
Had the same problem with emacs 27.1 on WSL1 (downgraded from WSL2).

Setting `process-connection-type` to `nil` fixed the problem for me.
