### ISSUE TITLE
WSL console doesn't work

### ISSUE THREAD

**Issue by TPGPL** [microsoft/WSL#4413]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.295]

* What you're doing and what's happening:  After installing Ubuntu subsystem for the first time, everything was going good, while trying to create a new default UNIX user i was prompted to disable Legacy Console, i did so and restarted the Ubuntu console. When I launched Ubuntu once more the console was blank like this:

![image](https://user-images.githubusercontent.com/19843905/63119065-87c43980-bf9f-11e9-9a79-af6326bfed52.png)

Restarting, uninstalling the distro didnt help at all. Writing `bash` in cmd outputs this:

![image](https://user-images.githubusercontent.com/19843905/63119140-b0e4ca00-bf9f-11e9-8c4f-c734e12ed502.png)

it looks like WSL created a default user itself and i can't change that by reinstalling or resetting the distro.

![image](https://user-images.githubusercontent.com/19843905/63119308-26509a80-bfa0-11e9-86a6-86d6759e9a63.png)

the distro looks to be installed properly but the console doesnt work

* What's wrong / what should be happening instead: I should be able to create a new default UNIX user, use Ubuntu console and reinstall the distro properly

* Strace of the failing command, if applicable:  -

Steps to reproduce:
1. Enable WSL subsystem in Powershell
2. Install Ubuntu from Microsoft Store
3. Launch Ubuntu with Legacy Console enabled
4. Try to create a new user and encounter Legacy Console error
5. Disable the Legacy Console and turn off the Ubuntu console
6. Relaunch the Ubuntu console

**Comment by craigloewen-msft** [comment]
This seems related to #4047 
Does restarting have any effect?
If you run the command `wsl` in CMD or Powershell what happens?
If you run `wsl --unregister Ubuntu` and then try and launch the Ubuntu app what happens?

**Comment by TPGPL** [comment]
1. Restarting Ubuntu or PC had no effect
2. Typing `wsl` in cmd activates bash and it works completely fine
3. Unregistering Ubuntu did nothing

while bash in cmd works fine, opening Ubuntu distro results in something like this: 
![image](https://user-images.githubusercontent.com/19843905/63162781-bdab0180-c023-11e9-83c5-0497cf89f776.png)

looks like it works but i can't write anything for some reason

**Comment by craigloewen-msft** [comment]
Ah, so this issue is slightly different in the fact that `wsl` and `bash` work fine from CMD. We'll dig into this, thank you for filing!

**Comment by DHowett-MSFT** [comment]
Hey, I think somebody reported something like this on the Console repository. Can you check the properties for the console hosting Ubuntu to make sure the options on the “Terminal” page aren’t turned on, or aren’t set to make the colors all black?

**Comment by TPGPL** [comment]
@DHowett-MSFT oh god it works now, thanks for help

![image](https://user-images.githubusercontent.com/19843905/63228331-7b371f80-c1f1-11e9-9c2b-e6b79bf2bf16.png)

**Comment by DHowett-MSFT** [comment]
Sure thing! This is definitely a windows console bug; we're tracking it over at https://github.com/microsoft/terminal/issues/2319
