### ISSUE TITLE
click on ubuntu icon, the shell did not start, and no error messages shown

### ISSUE THREAD

**Issue by mingwugmail** [microsoft/WSL#4418]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.678]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

after reboot machine, click the Ubuntu icon on the taskbar, the shell window flash on the screen, but then just exit.

* What's wrong / what should be happening instead:

maybe because of some systemd config cmd I run in the previous bash session.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by mingwugmail** [comment]
[lxcore_startup_failure_logs.tar.gz](https://github.com/microsoft/WSL/files/3512521/lxcore_startup_failure_logs.tar.gz)

**Comment by Silic0nS0ldier** [comment]
This sounds like an issue I've been facing. When run from an existing console you can see that there is indeed an error message.

```
Error: 0xffffffff
```

Attempts to re-register (`wsl --unregister ubuntu-18.04 ; ubuntu1804.exe`) result in the following error.
```
Unregistering...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xffffffff
Error: 0xffffffff (null)
Press any key to continue...
```

As mentioned by the OP this issue manifests are restarting, before restarting I had noticed that VS Code was unable to connect to WSL (it was why I restarted).

This issue has happened a few times for me, so far I've yet to pinpoint a common denominator. If I find anything, I'll post it here.

**Comment by Silic0nS0ldier** [comment]
Possibly related, one of the issues I encounter before Ubuntu starts failing to start is that the host binding breaks (`/mnt/c`) and shows `ls: cannot access 'c': Input/output error` when attempting to use `ls` in `/mnt`.

This appears to be resolved by restarting wsl (`wsl --shutdown ; wsl`), however it will break shortly afterwards. The fix for this is to restart Windows, which brings us a step closer to recreating the reported issue.

**Comment by yooakim** [comment]
I have the same issues since the update yesterday

```
Microsoft Windows [Version 10.0.18963.1000]
~> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
~> wsl "Ubuntu-18.04"
Error: 0xffffffff
```

**Comment by mingwugmail** [comment]
`wsl --shutdown` from the command prompt?

```
C:\Users\xxx>wsl --shutdown
Invalid command line option: --shutdown
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
```

**Comment by mingwugmail** [comment]
I can do (notice the space before `shutdown`) from the command prompt

`wsl -- shutdown; wsl`

but after that when I click the Ubuntu icon on the taskbar, still the same problem.

**Comment by benhillis** [comment]
Duplicate #4364.
