### ISSUE TITLE
how to init the whole Linux system in general (or mysqld in particular)  from bash?

### ISSUE THREAD

**Issue by mingwugmail** [microsoft/WSL#4419]
I cannot start the installed Ubuntu from the icon on the taskbar, while I can start bash from a command prompt window. But I noticed the bash shell I got in this way does not have the full Ubuntu system properly init-ed, e.g. the MySQL server is not started.

My question is how can I properly init the whole system from the bash?

Or if it's not possible, how do I start mysqld from the bash?

**Comment by craigloewen-msft** [comment]
You can use this command to start the service:
`/etc/init.d/mysql start`

**Comment by mingwugmail** [comment]
```
$ /etc/init.d/mysql start
 * Starting MySQL database server mysqld                                                                                                                                                      install: cannot change owner and permissions of ‘/var/run/mysqld’: No such file or directory
```

From this bash how I do make the current login user as sudoers?

FYI, on the fully init-ed system (launched from Ubuntu icon on the taskbar), the current login user is sudoers, but it's not in this bash.

**Comment by craigloewen-msft** [comment]
What error do you run into when launching the Ubuntu icon from the taskbar?

And please use the `wsl` command in Powershell or CMD to start a bash session. 

As well it was my mistake, it should be: `sudo /etc/init.d/mysql start`. However this doesn't seem to be your issue as it can't find a file. I followed the install instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-16-04) and was able to get mysql working in WSL.

**Comment by mingwugmail** [comment]
My error to launch the Ubuntu icon from the taskbar:

https://github.com/microsoft/WSL/issues/4418

**Comment by mingwugmail** [comment]
I tried `wsl` from both the command prompt & Power shell, nothing happened.

which `bash` I can as least get a Linux shell.

MySql on my machine was properly installed, and was fully functional before my problem of #4418.

The file `/var/run/mysqld` I think is a run file, i.e. *it's created* after the mysqld start.

Basically the login user need to be sudoer.

**Comment by craigloewen-msft** [comment]
You can run `ubuntu.exe config --default-user <username>` to change your default user in Ubuntu.

This seems related to your other issue, I'll try and dig in on both to see if I can find any solution.

**Comment by mingwugmail** [comment]
···
> ubuntu.exe config --default-user root
Error: 0x80070057 The parameter is incorrect.
···

I also tried my own user name (which I can use when launching `bash`), same error message.
