### ISSUE TITLE
Windows Server 2019 - Ubuntu - WslRegisterDistribution failed with error: 0x80070001

### ISSUE THREAD

**Issue by larde** [microsoft/WSL#4420]
On Windows Server 2019 Standard (64bit OS) - Build 17763.615, when trying to install Ubuntu on WSL (by following https://docs.microsoft.com/en-us/windows/wsl/install-on-server), I have this error:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.
```

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763`
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```
PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Path          :
Online        : True
RestartNeeded : False

Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1604 -OutFile Ubuntu.appx -UseBasicParsing
Rename-Item Ubuntu.appx ./Ubuntu.zip
Expand-Archive Ubuntu.zip D:\Ubuntu
Remove-Item .\Ubuntu.zip
cd D:\Ubuntu

$userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
[System.Environment]::SetEnvironmentVariable("PATH", $userenv + ";D:\Ubuntu", "User")

.\ubuntu1604.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 Incorrect function.`
```

* Logs:
[logman.zip](https://github.com/microsoft/WSL/files/3514856/logman.zip)

**Comment by larde** [comment]
I have fixed my issue.

It seems that I can't use WSL on an NVMe disk.
On a classical disk, on the same server, it works.

**Comment by SequoiaDu** [comment]
> I have fixed my issue.
> 
> It seems that I can't use WSL on an NVMe disk.
> On a classical disk, on the same server, it works.

I have the same issue on Windows Server 2019. However, my OS runs on a SATA SSD rather than a nvme drive.

**Comment by MichaelMc64** [comment]
I get this error when installing WSL on a server which is a hosted VM. So the disk is neither an NVMe nor a Sata SSD. It's a file on a hypervisor somewhere in a cloud or something. 
And why should any of that make any difference at all? What kind of hocus pocus nonsense would the type of disk make which would prevent running a virtual OS inside another OS?
It's the 21st century. It's VM's all the way down.

**Comment by kogutenko** [comment]
Had same problem (HDD Windows installation – success, NVMe – failure), was solved like this:

1. Open `msconfig` (e.g. via `Win` + `R`)
2. Select "Services" tab
3. Mark "Hide all Microsoft services"
4. Click on the "Disable all" button
5. Apply changes and reboot the system
6. Install WSL in the standard way
7. Revert services changes and reboot again

<details>
<summary>Which services were disabled</summary>

- Intel(R) Content Protection HDCP Service
- Intel(R) Dynamic Tuning Technology User Interface Service
- Intel(R) Graphics Command Center Service
- Intel(R) Innovation Platform Framework Service
- Intel(R) Innovation Platform Framework User Interface Service
- Intel(R) Dynamic Application Loader Host Interface Service
- Intel(R) Management Engine WMI Provider Registration
- ImDisk RamDisk starter
- ImDisk VirtualDisk Driver Helper
- Mozilla Maintenance Service
- Realtek Audio Universal Service
</details>
