### ISSUE TITLE
/etc/fstab syntax for drvfs and CIFS paths

### ISSUE THREAD

**Issue by clintolsen** [microsoft/WSL#4423]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.17763.615

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

`sudo mount -t drvfs '\\HOST\vol' /mnt/vol`
 
I'm trying to replicate the syntax from the command-line in `/etc/fstab` and not all the googling in the world has seemed to find a solution.

* What's wrong / what should be happening instead:

I've tried pretty much every syntax I can think of, and the result is something along the lines of:

The last thing I tried was:

`//HOST/vol /mnt/vol drvfs default 0 0`

`mount: /mnt/vol: wrong fs type, bad option, bad superblock on //HOST/vol, missing codepage or helper program, or other error.`

It's not clear to me how to placate mount to get it to do what I want.

**Comment by clintolsen** [comment]
It does appear that if you remove `default` that there is a canned set of mount options already there for for `drvfs` and it will work.

It would be good to know what mount options are available. Are they documented anywhere?

**Comment by 0xbadfca11** [comment]
Is ``default`` a mistake for ``defaults``?

**Comment by clintolsen** [comment]
> Is `default` a mistake for `defaults`?

Yes, it was a typo!
