### ISSUE TITLE
Issues with kernel module development on WSL2

### ISSUE THREAD

**Issue by tcaputi** [microsoft/WSL#4425]
I filed this bug [here](https://github.com/microsoft/WSL2-Linux-Kernel/issues/35) last night, not realizing that it was probably not the right place to file the report. I will paste the relevant parts here. I apologize that it does not follow the template, but I will make sure all of the info you asked for is here.

## Description
Hello. I am a developer for the OpenZFS project (specifically ZFS on Linux). I was really excited when I heard that WSL2 was coming out. I personally prefer Windows' UI so, for the moment, I write my kernel module code in Windows, then run a VirtualBox VM with a shared folder (which is ludicrously slow) to compile and test my code. With WSL2, I hope to be able to continue writing my code on Windows and use the new file sharing mechanism to get much faster compile times.

When trying this out, I ran into a few issues (in the order in which I ran into them):
1. I did not find any documentation for how to get the kernel headers installed in the "Ubuntu" way after compiling this kernel. Luckily, I have a friend who is good at that sort of thing who built some debian packages for me, but I was wondering if there was a "correct" way to get the headers installed after building the source.
2. Kernel modules are loadable, but load with a reference count of -2 and are not unloadable. Normally, the kernel modules would have a reference count >= 0, depending on how they are being used. I didn't get a chance to look into this very thoroughly, but thought you guys might know why that might be. This is a bit of an inconvenience for me because iterating on a new version of a kernel module now requires me to restart WSL2 to load the new module.
3. This one is the most perplexing to me. For a little bit of background, zfs is a filesystem that uses pooled storage (called a zpool) consisting of any number of files or block devices. After I got the zfs kernel module installed, I attempted to create a zpool based on a file that I truncated named `/root/vdev`. The userspace code reported a failure due to an ENOENT error coming from the kernel. After a lot of debugging and tracing, it seems this error is being returned from the call to `filp_open()` that the kernel uses to open the file. I am able to `ls -la` and `cat` the file so it seems to be working ok except for this call. This is especially surprising to me because (as far as I can tell) `/root` is just a directory in the ext4 root filesystem.

## Steps to Reproduce 2 and 3
I started with a clean WSL2 Ubuntu 18.04 LTS VM from the Windows store. From here I had my friend build me a debian package for this kernel off of the current master branch of https://github.com/microsoft/WSL2-Linux-Kernel (tip at 709a095). To be honest, I'm not entirely sure what he did there, but the important thing is that I ended up with the vmlinuz compressed kernel, config, and System.map files installed in `/boot` and the kernel headers installed in `/usr/src`, which is where Ubuntu expects them. I then copied the vmlinuz file out to my Windows machine and setup my .wslconig to boot the new kernel. After that I built the zfs kernel modules and binaries:

### Setup
```
# install zfs dependencies
apt update && apt upgrade && \
apt install build-essential autoconf libtool gdb lcov \
git alien fakeroot wget curl bc fio acl \
sysstat mdadm lsscsi parted gdebi attr dbench watchdog ksh \
nfs-kernel-server samba rng-tools xz-utils dkms \
linux-headers-$(uname -r) \
zlib1g-dev uuid-dev libblkid-dev libselinux-dev \
xfslibs-dev libattr1-dev libacl1-dev libudev-dev libdevmapper-dev \
libssl-dev libffi-dev libaio-dev libelf-dev libmount-dev \
python-dev python-setuptools python-cffi \
python3 python3-dev python3-setuptools python3-cffi \
pax-utils shellcheck cppcheck mandoc \
python3

# clone and build zfs
git clone https://github.com/zfsonlinux/zfs.git
cd zfs
./autogen.sh
./configure.sh --prefix=/usr
make -j4

# install zfs and insert the kernel module
make install
modprobe zfs
```

### Observing Problem 2
Run `lsmod` and note the reference count of -2 on all the newly inserted kernel modules. Note that the modules cannot be removed.
```
root@Roy:~# lsmod
Module                  Size  Used by
zfs                  4804608  -2
zunicode              335872  -2
zlua                  172032  -2
zcommon                86016  -2
znvpair                73728  -2
zavl                   20480  -2
icp                   323584  -2
spl                   122880  -2
root@Roy:~# modprobe -r zfs
modprobe: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'zfs': Function not implemented
```

### Observing Problem 3
Truncate a file and attempt to create a zpool. The error message is a bit misleading because zfs does not expect this error when the userspace tools know the file actually exists.
```
root@Roy:~# truncate -s 5G /root/vdev
root@Roy:~# zpool create pool /root/vdev
cannot create 'pool': no such pool or dataset  
```
I was able to find out that the problem was coming from `filp_open` using gdb and the `kprobe` and `funcgraph` utilities from https://github.com/brendangregg/perf-tools. (I got a little farther than that actually. I know the error code comes from somewhere in `path_openat()`, but `filp_open()` is the interface the zfs kernel module actually calls.) If you wish to see this yourself, clone that repository, navigate to the `bin/` directory and run the following command while attempting to create the pool:
```
root@Roy:~# ./kprobe 'r:filp_open $retval' | grep vdev_open
       vdev_open-30386 [009] d... 50119.481084: filp_open: (vn_open+0x1ff/0x2e0 [spl] <- filp_open) arg1=0xfffffffffffffffe
```
Here is an strace of the `zpool create` command: [strace.txt](https://github.com/microsoft/WSL/files/3521344/strace.txt)

Let me know if I can provide any more information

**Comment by Biswa96** [comment]
I'm doing some tests. How can I know zfs module work correctly?

**Comment by tcaputi** [comment]
After the steps above you should be able to run `zpool create pool /root/vdev` with no error message. Afterwards `zpool status` should show a bunch of stats about the newly created pool.

**Comment by tcaputi** [comment]
I have figured out issue 2. `CONFIG_MODULE_UNLOAD` is not set by default, preventing modules from being unloaded. Is there a reason for this?

So now the last technical problem I have is issue 3

**Comment by tcaputi** [comment]
After some more debugging I was able to find a deeper cause (although still not the root cause) of the problem. It seems (at least for the `vdev_open` kernel thread that zfs creates) that the root filesystem is not the ext4 filesystem that is mounted at `/`.  Instead, the root filesystem appears to be of type `rootfs`, which is the temporary in-memory filesystem that is used to get the OS to boot. I found this using the `bpftrace` utility and the attached script for it. There is a lot of extra debugging there (partially because I'm not very good at using bpftrace), but I was able to determine that when `d_alloc_parallel()` is called, the `parent` dentry belongs to a superblock with filesystem type of `rootfs` instead of `ext4`. Here is the bpf script I used (github doesnt like it when I upload .bpf files, so I just renamed it to .txt): [filp_open.txt](https://github.com/microsoft/WSL/files/3522557/filp_open.txt)

Let me know if there is anything else I can help with.

**Comment by tcaputi** [comment]
Hmm, while investigating a little more I noticed that kernel threads are not exposed to the user through the proc filesystem (although I can see them with kernel tracing tools). Maybe WSL2 isn't ready for my use-case yet....

**Comment by cerebrate** [comment]
Presumably the kernel thread non-exposure is because all the WSL 2 distros share a common kernel but [some] different namespaces, leading to the kernel threads not existing in the distro's pid namespace.

I'd speculate that that's also why you're not seeing the _distro's_ root filesystem from your kernel thread, because each distro is mounting its own root filesystem inside its own file namespace, and the kernel thread doesn't know to look inside those; it's instead seeing whatever the WSL internals use to get the WSL light-vm up and running.

As for how to get around this... that I don't know.

(On a side note, for building the WSL kernel, I just use make xconfig/make/make modules_install/make install normally from the directory I cloned the kernel source repo into, which puts all the modules, /boot stuff, etc., in its proper place, then copy it out to use with wslconfig. Then I supply that source location to the --with-linux switch to configure to point it at that source directory when compiling other things. Quicker than packaging it when you find yourself tweaking the config a lot.)

**Comment by tcaputi** [comment]
Thats good to know. Thanks. For the moment I'm back to just using VirtualBox.

**Comment by tangruize** [comment]
I also encountered the confusing "cannot create 'pool': no such pool or dataset" msg when create zfs pool using LXD.
Currently, I use a workaround method, which firstly losetup the file, and then run zpool create for the loop file. It can succeed.
