### ISSUE TITLE
how to figure out which version my debian is?

### ISSUE THREAD

**Issue by XSun771** [microsoft/WSL#4427]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [版本 10.0.17763.678]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I would like to know the version of debian which I'm suing via WSL. So I input 'uname -a' in WSL shell, but it report like following:
Linux DESKTOP-L79Q7C3 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 GNU/Linux

* What's wrong / what should be happening instead:

I can't get any useful information about the version. is it debian 9? is it debian 10?

**Comment by Biswa96** [comment]
Command `cat /etc/os-release`.

**Comment by rdp** [comment]
Unrelated but would be nice if `wsl --list --online` listed which version of Debian it can install :)
