### ISSUE TITLE
Could not access elasticsearch an kibana from windows

### ISSUE THREAD

**Issue by niudai** [microsoft/WSL#4428]
* Your Windows build number: 18963.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```shell
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-amd64.deb
sudo dpkg -i elasticsearch-7.3.0-amd64.deb
sudo /etc/init.d/elasticsearch start
```

The command above download and starts the elasticsearch, which runs on port 9200, and everything goes well.

When I user curl to test elasticsearch to see if it works, the output is just fine:

```
curl localhost:9200
```

The output is :

```
{
  "name" : "YLMF-1702181159",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "156pQeVZR72gllFIXg2TLQ",
  "version" : {
    "number" : "7.3.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "de777fa",
    "build_date" : "2019-07-24T18:30:11.767338Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
which is fine, but when I open the broweser and enter `localhost:9200`, I could not connect to elasticsearch, saying that refusing to connect.

![image](https://user-images.githubusercontent.com/44165182/63431666-f0089480-c451-11e9-98da-64b977b280cb.png)

The kibana is just the same, it serves at port 5601, and when I curl it in WSL, everything goes well, but it seems that I could not access these services outside the WSL.

It's weird,  because when I run some front-end web app using node and npm, I could access these service in my browser.

My ipconfig page:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5601          0.0.0.0:*               LISTEN      761/node
tcp        0      0 127.0.0.1:9060          0.0.0.0:*               LISTEN      908/node
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      441/java
tcp6       0      0 ::1:9200                :::*                    LISTEN      441/java
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      441/java
tcp6       0      0 ::1:9300                :::*                    LISTEN      441/java
tcp6       0      0 :::3001                 :::*                    LISTEN      908/node
tcp6       0      0 :::9000                 :::*                    LISTEN      908/node
```
5601 is kibana, 9200 is elasticsearch, which I could not access outside of WSL, but 9000 port works perfectly when I try to access in browser by typing localhost:9000.

Am I doing sth wrong?

**Comment by craigloewen-msft** [comment]
The connection refused error message makes me suspect that this is due to which IP address your application is binding to. In python with Flask I would use `app.run(host='0.0.0.0')` instead of `app.run()` and I suspect you will need to make a similar change here. In node this is done with `app.listen(3000,"0.0.0.0")`

**Comment by niudai** [comment]
What does '0.0.0.0' mean? I know 127.0.0.1 denotes self-host, but I've got no idea what '0.0.0.0' is for.

**Comment by lahma** [comment]
@niudai all network interfaces, both public and private

**Comment by niudai** [comment]
Thank you.
