### ISSUE TITLE
WSL2: closing the console window with the "x" terminates subprocesses while typing "exit" in bash does not

### ISSUE THREAD

**Issue by bsmedberg-xometry** [microsoft/WSL#4429]
* Your Windows build number: 10.0.18963-1000
* What you're doing and what's happening:
** I have vcxsrv running with DISPLAY and XAUTHORITY configured correctly
** This works:
*** open ubuntu shell from a shortcut
*** type `emacs &` - emacs X window opens
*** type `exit`
*** emacs stays open
** this fails:
*** open ubuntu shell from a shortcut
*** type `emacs &` - emacs X window opens
*** press the "X" button on the shell window
*** emacs window closes

* What's wrong / what should be happening instead: I believe in both of these cases the emacs window/process should stay alive even as the shell goes away.

I've also tried using various incantation of nohup and piping the emacs stdin/stdout.

* Strace of the failing command, if applicable: I tried collecting an strace of the bash process tree and it didn't show anything interesting for the processes... but I'm not sure I did it correctly

**Comment by therealkenc** [comment]
/dupe #4649 ➡️ #4649, which is in a bit of an undead state until someone calls by-design.
