### ISSUE TITLE
Git commit -m closes the terminal

### ISSUE THREAD

**Issue by eullercdr** [microsoft/WSL#4430]
Dears, 

I have a problem in WSL, when i type `git commit -m` the terminal is closed!

Note: In the default terminal, this error does not happen. The error happens when I install zsh + plugin oh my zsh

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

My windows build is Windows 10 Pro, 1903.

I have been installed Ubuntu 18.04 LTS.

Can you help me please?

**Comment by kkkasio** [comment]
i have same problem,
it occurs whenever I type "git commit -"
I haven't found another command with the same error yet.

**Comment by onomatopellan** [comment]
Does it happen in the new Windows Terminal too?

Since it closes the terminal window the issue should be posted here too::
https://github.com/microsoft/terminal/issues

**Comment by eullercdr** [comment]
@onomatopellan done! https://github.com/microsoft/terminal/issues/2518 Thans a lot. Case you need more informations, please let me know!!!

**Comment by summarek** [comment]
@eullercdr Hey, how did You fix that? I have same problem.

**Comment by SuNNjek** [comment]
In case it helps, it have the same problem and have some logs:


[logs.zip](https://github.com/microsoft/WSL/files/3569339/logs.zip)

**Comment by ertwro** [comment]
If you are using compeltion or highlighting plugins you will experience several of those problems. This is a WSL exclusive problem when interacting with zsh due to filesystem files.
introduce this in your .zshrc
```
FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"
```
There are varieties of this solution depending on your plugins. e.g. prezto, omz.

**Comment by therealkenc** [comment]
Following microsoft/terminal#2518 lead and closing for lack of repro. It isn't even clear whether this is tag console. Even given repro steps and and strace(1) log per the template, the likelihood of someone diving a zsh plugin to find a WSL1 syscall diverge is.... small.
