### ISSUE TITLE
'wsl --set-version Debian 2" returns "RPC server unavailable"

### ISSUE THREAD

**Issue by longwuyuan** [microsoft/WSL#4433]
Microsoft Windows [Version 10.0.18965.1000]

 - I am setting a distro to wsl2
- The command "wsl --set-version Debian 2" return the message "RPC server unavailable"
- The RPC services and RPC mapper serivice are running

```
PS C:\WINDOWS\system32> wsl --set-version Debian 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The RPC server is unavailable.
PS C:\WINDOWS\system32>
```
I should be able to set a distro to wsl version 2

**Comment by longwuyuan** [comment]
reinstalled os

**Comment by soda0289** [comment]
I had same problem. Needed to enable "DNS Client" service or dns cache. My PC had this service disabled.

Followed instructions here: https://wintechlab.com/enable-disable-dns-client-service/

Had to update registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache` and update Start DWORD key and change its value from 2 (Automatic) to 4 (Disabled)
