### ISSUE TITLE
Apt-get update and apt-get upgrade fail

### ISSUE THREAD

**Issue by mavaleriano** [microsoft/WSL#4435]
* Your Windows build number:  18965.1000

Whever I use Ubuntu on WSL, apt-get update and apt-get upgrade work fine. And pinging works as well. As soon as I convert to WSL 2, I get these errors with sudo apt-get update:

$ sudo apt-get update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                   
Temporary failure resolving 'archive.ubuntu.com'                                                                      
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                         
Temporary failure resolving 'security.ubuntu.com'                                                                     
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                           
Temporary failure resolving 'archive.ubuntu.com'                                                                      
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                         
Temporary failure resolving 'archive.ubuntu.com'                                                                      Reading package lists... Done                                                                                           
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  
Temporary failure resolving 'archive.ubuntu.com'                                                                                                                    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  
Temporary failure resolving 'archive.ubuntu.com'                                                                                                            W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'                                                                                                          W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  
Temporary failure resolving 'security.ubuntu.com'                                                                                                         W: Some index files failed to download. They have been ignored, or old ones used instead.

Whenever I try pinging google I receive:
ping: google.com: Temporary failure in name resolution

I've tried switching networks, turning off Firewall, and reinstalled Ubuntu.
![Version2_errors](https://user-images.githubusercontent.com/27215977/63485278-a9766280-c470-11e9-863c-3419941a1452.PNG)

**Comment by craigloewen-msft** [comment]
This looks like a duplicate of https://github.com/microsoft/WSL/issues/4342 or https://github.com/microsoft/WSL/issues/3438 . Please try some of the workarounds [\[1\]](https://github.com/microsoft/WSL/issues/3438#issuecomment-518464665) \[[2\]](https://github.com/microsoft/WSL/issues/3438#issuecomment-519666790) posted in those threads, and if those fix your issue we can mark this as a duplicate and close it.

**Comment by mavaleriano** [comment]
The powershell script available there was able to fix my issue!

**Comment by ad-on-is** [comment]
I'm facing the same problem after I updated Windows Insider to 18965.1005.

**Comment by evilArsh** [comment]
i cannot ping baidu.com and google.com ,my version is 19008.1 insider and i am using v2ray ,"wsl2"

**Comment by carloscoelhow** [comment]
deleting  /etc/resolv.conf and reopen wsl terminal worked for me

**Comment by Sergej-Popov** [comment]
`/etc/resolv.conf` was getting re-created for me every time. this fixed it for me:

> Create a file: /etc/wsl.conf.
> Put the following lines in the file
> [network]
> generateResolvConf = false
> In a cmd window, run wsl --shutdown
> Restart WSL2
> Create a file: /etc/resolv.conf. If it exists, replace existing one with this new file.
> Put the following lines in the file
> nameserver 8.8.8.8
> Repeat step 3 and 4. You will see git working fine now.

[found here](https://github.com/microsoft/WSL/issues/4285#issuecomment-522201021)

**Comment by Cartman0** [comment]
i faced to this issue in Windows10 ver2004, wsl2, and Ubuntu20.04LTS.
this issue should reopen.

**Comment by Cartman0** [comment]
@Sergej-Popov
hi, have you installed docker desktop for windows?
`docker ps` is dead in my env. can it run in your env?

**Comment by pooryamoh** [comment]
I faced this issue too, on windows10 ver2004, wsl2, and Ubuntu18.04LTS

**Comment by roonie007** [comment]
I faced this issue too, on windows10 ver2004, wsl2, and Ubuntu18.04LTS

**Comment by wbranstetter** [comment]
I am also having this issue when i attempt to run Docker with MLflow. 

![image](https://user-images.githubusercontent.com/32022830/95595089-68913280-0a11-11eb-9fe0-4d5a8b5c6e99.png)

This seems to be some access issue from within my WSL2 shell.  I've tried the suggestions mentioned here, but no luck.  

Anyone have a resolution?

**Comment by jaredhagel** [comment]
Doesn't work for me either with Windows 10 Enterprise, Version 10.0.18362, WSL2, and Ubuntu18.04 LTS. None of the workarounds have worked for me yet.

**Comment by ad-on-is** [comment]
Guys, check your 3rd party firewall settings. BitDefender firewall broke my internet connection in WSL

**Comment by pieball** [comment]
Turning off my VPN got it working for me.

**Comment by ctsstc** [comment]
Started sounding like a VPN issue, glad I'm not the only one with the VPN issue. Oddly I have whitelisted apps for my VPN, but it must be the DNS resolver for the VPN screwing things up.

**Comment by theDreamer911** [comment]
if you still not found this solution, 
For me i was checking the /etc/resolv.conf 
and add the nameserver 8.8.8.8 inside it

I think this problem because we not add the global DNS, when we set our local DNS

**Comment by ed-graham** [comment]
Adding `nameserver 8.8.8.8` to `/etc/resolv.conf` worked for me, too.

**Comment by slim-hmidi** [comment]
I added the company dns ip but does not fix the issue

**Comment by kubaszostak** [comment]
Resolved this issue on windows10 ver2004, wsl2, and Ubuntu18.04LTS with @craigloewen-msft help and his [link](https://github.com/microsoft/WSL/issues/3438#issuecomment-410518014) to the fix:

```
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.4.4" >> /etc/resolv.conf'
```

**Comment by 735l4** [comment]
> Adding `nameserver 8.8.8.8` to `/etc/resolv.conf` worked for me, too.

Worked for me too. had trouble after i added fish ppa

**Comment by cristiansaavedra** [comment]
Changing the server to 8.8.8.8 worked for me too.

```
sudo nano /etc/resolv.conf

# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/resolv.conf
# [network]
# generateResolvConf = false
nameserver 8.8.8.8
```

**Comment by rogerioefonseca** [comment]
> Adding `nameserver 8.8.8.8` to `/etc/resolv.conf` worked for me, too.

This worked 100%, thanks!!!!

**Comment by selimunal** [comment]
In the command prompt:
 
1. wsl -l -v     

( NAME            STATE           VERSION
 * Ubuntu-22.04    Running         2)

2.   wsl --set-version Ubuntu-22.04 1

3. bash 
4. sudo apt-get update 

This worked for me.
