### ISSUE TITLE
Can't go back to wsl

### ISSUE THREAD

**Issue by Yolo-plop** [microsoft/WSL#4438]
Hello,
I need to go back to wsl1 because i'm encountering too much issues with 2, can't access vhost and can't access the content of my c drive anymore.

But when i try to enter wsl --set-version debian 1 in Powershell, i get the following error in french : "Impossible de créer un fichier déjà existant.", which translates roughly to "Cannot created an already existing file".

I tried to restart my session to make sure the issue was not from something running.

**Comment by SaintZ13** [comment]
I am having this issue as well, I cannot seem to find a solution anywhere.

**Comment by craigloewen-msft** [comment]
What build of Windows are you running?
Have you tried installing another Linux distro and do you get the same error with that distro?
