### ISSUE TITLE
[exact repro] Exiting browser-sync after a pageload prevents further Windows-WSL connections in WSL2

### ISSUE THREAD

**Issue by cchan** [microsoft/WSL#4443]
**Please fill out the below information:**
* Your Windows build number: 10.0.18965.1005

* What you're doing and what's happening:

**Exact repro steps, assuming you have a reasonably recent version of node installed in WSL (I have v10.16.3)**

1. Check that networking works.
```
/usr/bin/python -m SimpleHTTPServer 1234
```
Visiting `localhost:1234` should work in Windows.

2. Run
```
npx browser-sync start
```
Visiting `localhost:3000` should work in Windows. [You must visit the page for this breakage to work.]

3. Press ctrl-c to terminate browser-sync.

4. Run
```
/usr/bin/python -m SimpleHTTPServer 1234
```
(or use the server you started last time)
Visiting `localhost:1234` no longer works in Windows.

**Other things I tried:**
- Only browsersync does this - not python SimpleHTTPServer, nor nodejs static server. It might have something to do with its use of websockets.
- ifconfig and netstat don't show anything suspicious.
- Restarting the network interface on the linux side (ifconfig down/up eth0) does not fix the problem.
- Only `wsl --shutdown` fixes the problem.

This might be related to #2913 and #3951, but I haven't had a chance to evaluate it in detail yet. Those issues claim to have been fixed in 18890, but I'm on a later build already (18965).

**Comment by joemaller** [comment]
If you wait a few minutes, does the network start working again? 

I’ve been trying to isolate some intermittent connection issues with webpack devserver (also socket-based) running from a wsl docker container, this issue sounds similar.

**Comment by craigloewen-msft** [comment]
@cchan if the issue does pop up again please try and collect some logs using our [networking log instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs).
