### ISSUE TITLE
Special characters <E2> in SSH session

### ISSUE THREAD

**Issue by llamafilm** [microsoft/WSL#4446]
Although this is a text rendering issue, I'm posting it here because it only happens with the linux shell, not in PowerShell.

**Please fill out the below information:**
* Your Windows build number: 10.0.18362.295
* Using Ubuntu shell, ssh into CentOS 7 server, then run `sytemctl status`

* What's wrong / what should be happening instead:
It displays weird characters at the beginning of each line instead of tabs/spaces.  These special characters are highlighted in white for some reason.

```
[user@localhost ~]$ systemctl status
<E2><97><8F> localhost.localdomain
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2019-08-26 10:23:31 PDT; 27min ago
   CGroup: /
           <E2><94><9C><E2><94><80>1 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
           <E2><94><9C><E2><94><80>user.slice
           <E2><94><82> <E2><94><94><E2><94><80>user-1000.slice
           <E2><94><82>   <E2><94><94><E2><94><80>session-6.scope
           <E2><94><82>     <E2><94><9C><E2><94><80>18309 sshd: pixspan [priv]
           <E2><94><82>     <E2><94><9C><E2><94><80>18313 sshd: pixspan@pts/0
           <E2><94><82>     <E2><94><9C><E2><94><80>18314 -bash
           <E2><94><82>     <E2><94><9C><E2><94><80>18354 systemctl status
           <E2><94><82>     <E2><94><94><E2><94><80>18355 less
           <E2><94><94><E2><94><80>system.slice
             <E2><94><9C><E2><94><80>packagekit.service
             <E2><94><82> <E2><94><94><E2><94><80>17367 /usr/libexec/packagekitd
             <E2><94><9C><E2><94><80>crond.service
             <E2><94><82> <E2><94><94><E2><94><80>6191 /usr/sbin/crond -n
             <E2><94><9C><E2><94><80>gdm.service
             <E2><94><82> <E2><94><94><E2><94><80>6190 /usr/sbin/gdm
             <E2><94><9C><E2><94><80>atd.service
             <E2><94><82> <E2><94><94><E2><94><80>6189 /usr/sbin/atd -f
             <E2><94><9C><E2><94><80>dcismeng.service
             <E2><94><82> <E2><94><94><E2><94><80>6438 /opt/dell/srvadmin/iSM/sbin/dsm_ism_srvmgrd
```

![Screenshot (1)](https://user-images.githubusercontent.com/3991046/63711537-7aede400-c7f0-11e9-9b43-db8d5b59d295.png)

**Comment by onomatopellan** [comment]
Can you try it in the new Windows Terminal?

**Comment by therealkenc** [comment]
No takers on the question. Whatever the answer, it is going to be config related. There is no syscall behavioral diverge here that is actionable. On a lark I sshed into my Ubuntu box and the output is sane to a first order. Probably relates to impedence between your CentOS locale and your WSL locale, but that's a WAG (which doesn't mean much).

![image](https://user-images.githubusercontent.com/7049700/67631619-fce0a480-f855-11e9-8aeb-e928b4578425.png)
