### ISSUE TITLE
WSL2 opens and immediately closes

### ISSUE THREAD

**Issue by xhevahir** [microsoft/WSL#4448]
Windows Version 10.0.18965.1005

Opening WSL2 (Ubuntu) brings up a window, which closes a moment later. I suspect this has something to do with my having set the default Linux shell to xonsh; following that, I uninstalled the version of xonsh from the Ubuntu repos and installed the one in conda-forge.

I've attached the error files that were generated by my running bash from Windows Terminal.

[errors.zip](https://github.com/microsoft/WSL/files/3544070/errors.zip)

**Comment by fr34kyn01535** [comment]
Duplicate of #4364

**Comment by MichealJl** [comment]
I have the same problem. Have you solved it?

**Comment by xhevahir** [comment]
No, i didn't solve it. I decided i was better off rolling back to an earlier stabler version of windows and installing WSL 1 on it.
