### ISSUE TITLE
Can't install SSH

### ISSUE THREAD

**Issue by feinstein** [microsoft/WSL#4449]
I am using WSL Ubuntu 18.04.3 LTS, and just upgraded Windows 10 to the latest version.

I was having trouble connecting with SSH, getting `connection refused` so I found [this issue](https://github.com/microsoft/WSL/issues/3173)(which is not the same as my case) and tried to follow it, basically:

    sudo apt-get remove openssh-client openssh-server
    sudo apt-get install openssh-client openssh-server

remove works, but install gives me:

    sudo apt-get install openssh-client openssh-server
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following additional packages will be installed:
    openssh-sftp-server ssh-import-id
    Suggested packages:
    keychain libpam-ssh monkeysphere ssh-askpass molly-guard rssh
    E: Could not read response to hello message from hook [ ! -f /usr/bin/snap ] || /usr/bin/snap advise-snap --from-apt 2>/dev/null || true: Success
    E: Could not read response to hello message from hook [ ! -f /usr/bin/snap ] || /usr/bin/snap advise-snap --from-apt 2>/dev/null || true: Success

Now I can't even reinstall SSH. I know this looks like a question, but being unable to install SSH, that came with Ubuntu looks like a bug to me.

**Comment by loganbontrager** [comment]
Hi feinstein. How did you go about deleting the snap hook file? I am having the same issue.

**Comment by feinstein** [comment]
Well, at the end the problem I was having was at the console, but it worked fine with CLion. I can't say much more as I migrated away from WSL and am I am using native Linux anyway.

**Comment by XavierBoniface** [comment]
> Hi feinstein. How did you go about deleting the snap hook file? I am having the same issue.

sudo rm -rf /etc/apt/apt.conf.d/20snapd.conf

(Source: https://askubuntu.com/questions/1123159/broken-apt-on-wsl-18-04)

**Comment by Vivskecher** [comment]
run `sudo apt-get autoremove`
its work for me then you can re install SSH
