### ISSUE TITLE
Getting Windows 10 to realize the new location for the Linux distro

### ISSUE THREAD

**Issue by s-usr** [microsoft/WSL#4451]
After moving the Linux distro (see https://github.com/MicrosoftDocs/WSL/issues/412), I got "access denied" when importing. This is probably because I do not have WSL2. I cannot get WSL2 because I have build 10.0.18362. Gettign the latest build failed because of the limited space on C.

When importing did not work, I unzipped the Linux distro at L:

I do not want to reinstall the app because the installation will again go to C:\users\...\AppData\Packages\LocalState\...

How do I get Windows to realize that the Linux distro is at L: (through D:\Linux.vhdx) not at C:\users\... anymore? Can anybody share the Environment Variables after the distro has been moved? 

As noted earlier, if I run 'bash' from the Power Shell, I get the message
> bash
Windows Subsystem for Linux has no installed distributions. Distributions can be installed by visiting the Microsoft Store: https://aka.ms/wslstore

But I do not want to install again, because the installation will go to C. I already have the full distro at L.

Thanks.

**Comment by craigloewen-msft** [comment]
Can you share the steps that you're taking to import your WSL distro and the exact error message you're seeing?

Have you tried re-importing the distro using the tar file?

**Comment by s-usr** [comment]
Thanks much. I have joined the Insider program, but installation of the latest build failed twice by now. I will attempt again. Once the installation works, I will have access to WSL2, and I will post an update then.

**Comment by s-usr** [comment]
*** For the benefit of others who might come across this case ***

On the fourth trial, Windws 10 update-as part of the 'Insider Program'-worked and I got build 18975. I was now able to successfully update WSL to version 2.  WSL version 2 requires the 'VirtualMachine' feature. Coincidentally, I read that the VM feature might need to be enabled in the BIOS settings. I rebooted my 'Lenovo' laptop pressing F2 until I got the BIOS menu. Sure enough, under "Configuration" the "Intel Virtual Technology" was disabled. I enabled that, saved, and exited. As the laptop restarted, I went to C:\Users\<user>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState, highlighted and deleted the folders "rootfs" and "temp". 

Open PowerShell as an Administrator:
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Pushing the Debian icon in Windows Start Menu, I got a fresh install of Debian GNU/Linux.  This created "ext4.vhdx" and the folder "temp" under "C:\Users\<user>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\\LocalState".
> wsl --set-version Debian 2
> wsl --set-default-version 2
> wsl -l -v
Name: Debian | State: Running | Version: 2

If you get the error message "VHD must be uncompressed", uncompress the folder "C:\Users\<user>\AppData\Local\Packages" and its descendants. File Explorer | Point to the folder | Properties | Attributes / Advanced | Uncheck "Compress to save disk space".

If you get the "Permission Denied" error, get permissiosn through File Explorer | Properties | Security or:
C:\>icacls "C:\Users\<user>\AppData\Local\Packages" /grant "<user>:(OI)(CI)(F)"

Open CommandPrompt as an Administrator. This is because PowerShell does not understand 'mklink'.
> cd C:\Users\<user>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4
> ren "LocalState" "Linux.bak"
> robocopy "Linux.bak" "D:\Linux" /E /ZB /DCOPY:T /COPYALL /R:1 /W:1 /V  (should execute without errors)
> mklink /J "LocalState" "D:\Linux"  (you will see "Junction created for LocalState <<===>> D:\Linux")
> robocopy "D:\Linux" "LocalState" /E /COPY:SOU /xo /xn /xc /xx  (should execute without errors)
> bash
<user>@PLUTO:/mnt/c/$ exit
logout
C:\>

Test also through PowerShell and the Debian icon under Windows Start. Reboot. Test one more time through the CommandPrompt, PowerShell, and the Debian icon under Windows Start. Everything should be fine. You now have a functional Linux distribtion with "C:\Users\<user>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\\LocalState" pointing to "D:\Linux\". You can now delete "Linux.bak" under "C:\Users\<user>\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\". 

Hope this helps!

**Comment by s-usr** [comment]
> icacls "C:\Users<user>\AppData\Local\Packages" /grant "<user>:(OI)(CI)(F)"

In the version above, <user> did not come out. This is meant to be "grant <user> (OI)(CI)(F) inheritance and full access permissions". See https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls.

**Comment by ctivanovich** [comment]
I'm getting this same issue trying to import ubuntu-19.04 with the wsl command. No matter where in I try to install the distro to, I get access denied.

**Comment by AllanOricil** [comment]
These https://docs.microsoft.com/pt-br/windows/wsl/install-win10 instructions are not working for me.
After I restarted my laptop I only get 
![image](https://user-images.githubusercontent.com/55927613/83969171-4900c680-a8c6-11ea-8ac7-c2ff79c832ff.png)

And Im executing powershell as an Administrator.
