### ISSUE TITLE
Intermittently broken CTRL+SHIFT+V 

### ISSUE THREAD

**Issue by mforde84** [microsoft/WSL#4452]
I'm experiencing issues with copy / paste into WSL especially with multi-line content. I will copy something in a notepad and when I paste (control shift v) in a terminal either nothing happens or WSL pastes an incorrect clipboard. The only way I can "fix" the issue at the moment is to copy the text multiple time using the drop down menu, then paste into a new notepad session, then paste into WSL. Can you guys fix this behavior? Not sure why I would need more than a two step process to copy and paste into WSL, and I have no other choice but to use Windows.

**Comment by craigloewen-msft** [comment]
Copy and paste is handled by the terminal you're using. If you're using CTRL+SHIFT+V I'm going to assume you're using the Windows Console. The one that looks like this: 
![image](https://user-images.githubusercontent.com/42221804/63959734-b0d5d700-ca41-11e9-8bfb-04c0e82a427b.png)

If you are using the Windows Console then please open up an issue on the [Windows Terminal repo](https://github.com/microsoft/terminal/issues) as they'll be the best people to help you with your issue!

**Comment by pgoddijn** [comment]
@craigloewen-msft I think you're correct. I experience a similar issue where copying a multi-line selection is stored as a single line.
Tested this directly in PowerShell 5.1.18362.145, same behavior.

@mforde84 If you use Enter to copy the selected text, does it work as expected? Using Enter to copy a selection does work as expected.
