### ISSUE TITLE
bash doesn't open from cmd

### ISSUE THREAD

**Issue by caespinoza5** [microsoft/WSL#4458]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.295]

* What you're doing and what's happening: Running 'bash' from any folder that is not C:/System32. Console shows "‘bash’ is not recognized as an internal or external command,
operable program or batch file."

* What's wrong / what should be happening instead:
'bash' should open the bash console installed with WSL.

I'm not too sure what caused this issue, but before I was able to run "bash -c _command_ " and the command would run normally, from any folder. However, after reinstalling Windows Subsystem for Linux (That is, disabling WSL from Windows features and reenabling it) and reinstalling Ubuntu from Microsoft store and setting linux username and password, I'm only able to run bash from system32 folder and not anywhere else. Is there a possible fix to this? I already have "C:\Windows\System32\bash.exe" added to my system variables. The biggest problem is that this doesn't let me do any bash commands from cmd on any folder that is not system32 (for example, "bash -c ls").

**Comment by therealkenc** [comment]
You've likely clobbered your Windows `%PATH%` similar to #4259 but that is a WAG. There is not enough information in the submission to reproduce.

> I already have "C:\Windows\System32\bash.exe" added to my system variables.

You do not add `....\System32\bash.exe` to any system variable. You need directory `....\System32` directory in your path.

**Comment by caespinoza5** [comment]
¡Solved! It was indeed similar to #4259. By adding %SystemRoot%\system32 and C:\Windows\System32 to PATH On Environment Variable -> System Variables, it worked. Thank  you so much, I had been stuck with this problem for hours.
