### ISSUE TITLE
Child processes are not getting the signal to stop running (SIGINT)

### ISSUE THREAD

**Issue by Mikewl** [Microsoft/WSL#446]
Testing [Julia](https://github.com/JuliaLang/Julia) which finally compiled and found that if the tests were cancelled midway the workers were not killed but would continue to run in the background.

This behaviour was not present when testing inside an Ubuntu VM.

I think SIGINT is not being passed correctly in bash on windows to the child processes.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, can you please share out an strace of the failing scenario?  This may be due to a lack of PR_SET_PDEATHSIG, depending on how the application is configured.
