### ISSUE TITLE
sudo apt-get update, user is not in the sudoers file

### ISSUE THREAD

**Issue by NandaAndrade** [microsoft/WSL#4462]
nanda_andradebc@DESKTOP-6SL8QN6:~$ sudo apt update && sudo apt upgrade
[sudo] password for nanda_andradebc:
nanda_andradebc is not in the sudoers file.  This incident will be reported.

**Comment by therealkenc** [comment]
Absent [template](https://github.com/microsoft/WSL/blob/master/ISSUE_TEMPLATE.md)

Get logged in as root. On recent Windows, use `wsl.exe -u root`. On older releases, see [this](https://docs.microsoft.com/en-us/windows/wsl/user-support).

Then update your [`suders(5)`](https://www.sudo.ws/man/1.8.13/sudoers.man.html) file. On saner distros with a sudo group, this will usually suffice:
```
# usermod -a -G sudo 
```

On other distros you can add yourself to /etc/sudoers directly with [`visudo(1)`](https://www.sudo.ws/man/1.8.7/visudo.man.html)
```
#
# This file MUST be edited with the 'visudo' command as root.
#
... blah blah
nanda_andradebc ALL=(ALL) ALL
```
