### ISSUE TITLE
VIM over SSH starts in REPLACE

### ISSUE THREAD

**Issue by PathosV** [microsoft/WSL#4463]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.295]
* WSL : Ubuntu 18.04.3 LTS

* What you're doing and what's happening: 

I am connecting to a work cluster and editing files with vim. 
Using the openssh packaged with Ubuntu, vim will start in REPLACE mode when opening a file on the connected server. Editing files on local machine does not cause this problem.  
Using the openssh provided by Windows gives the same results. 
Using the openssh provided by Git-Bash fixes the issue, but is not an optimal solution for use with my .ssh/config due to the file path.

I've also connected to an AWS server and did not experience this issue with the built-in ssh, so it is not completely broken for me. My hunch is that it might have to do with the server requiring diffie-hellman-group1-sha1.

**More Info:**

Work Cluster:
SUSE Linux Enterprise Server 12 SP3

/usr/bin/ssh                       
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

/mnt/c/WINDOWS/System32/OpenSSH/ssh.exe
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

/mnt/c/Program\ Files/Git/usr/bin/ssh.exe
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
(works in both WSL and Windows Environments)
    
Issue is independent of Terminal's tested:

- MINGW64
- cmd
- Powershell
- Windows Terminal

Related (Reverse) Issue:
https://github.com/microsoft/terminal/issues/1637

**Comment by sirredbeard** [comment]
I am not sure how a change in the encryption method used in the SSH would affect the starting settings on vim.

Because you can reproduce with other platforms leads me to think this is a setting in vim on your server. Have you ruled that out?

**Comment by PathosV** [comment]
I had previously checked my personal vimrc settings and found nothing that fixed the issue. I only just found the -u option for vim to load only a specific file, so I checked each setting in /etc/vimrc and found a lead. 

The guilty setting:
```
set esckeys  " Required to be able to use keypad keys and map missed escape sequences
```
The "fix" : 
```
set noesckeys
```
Only works if placed after:
```
set nocompatible
```
This is still not a preferable "fix". Loading the server setting file on my local machine also does not cause an issue. No issue on my AWS server either. Seems like vim is receiving some escape codes over ssh that are again specific to my work cluster.

**Comment by PathosV** [comment]
To be clear, my last comment was not an indication that my problem is solved. While the problem does have something to do with the unique connection to my work cluster, it only occurs when using the Windows or WSL versions of openSSH.

**Comment by therealkenc** [comment]
Your OP question is not WSL actionable. Neither `vim` not `ssh` ship as part of WSL, and WSL is not related to your AWS server. There is no CLI reproduction identifying a WSL1 diverge in the Linux syscall surface. 

Questions are left open for a while to give the community a chance to weigh in with help on this WSL repo, based on community interest (me2s) and the likelihood it will lead to identifying a WSL diverge. You may find more more eyeballs at a [Ubuntu forum](https://ubuntuforums.org/) or at [Superuser](https://superuser.com/). If you manage to identify a WSL1 kernel diverge please feel encouraged to open a new issue following the issue template, which reads in part:

> Please use the following bug reporting template to help produce issues which are actionable and reproducible, including all command-line steps necessary to induce the failure condition. Please fill out all the fields! Issues with missing or incomplete issue templates will be closed.

**Comment by ioklo** [comment]
I fixed this problem by 'set TERM=xterm-color'(not 256color) before using ssh (Windows OpenSSH version).

**Comment by hgkamath** [comment]
Instead of using the default OS-bundled ssh-client
```
> C:\WINDOWS\System32\OpenSSH\ssh.exe -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5 
```
I updated an instance of a local windows openssh server, to a pre-release version 8.1. The ssh-server also comes with its own ssh-client.
```
> 'C:\Program Files\OpenSSH-Win64\ssh' -V
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
