### ISSUE TITLE
Win32 Interop fails when used inside namespace

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4464]
* Your Windows build number:  Microsoft Windows [Version 10.0.18970.1005]

* What you're doing and what's happening:

Inside any namespaces created with `unshare(1)`, Win32 interop fails with a segmentation fault. Well, sort of -- the problem occurs on any occasion that the -f/--fork flag is used with unshare, even if no namespaces have been specified to unshare with other options. For example:

```
avatar@athena-wsl:~$ sudo /usr/bin/unshare -f /bin/sh
# /mnt/c/Windows/notepad.exe
Segmentation fault
# exit
```

This also happens if it is used from any child process within the namespace:

```
avatar@athena-wsl:~$ sudo /usr/bin/unshare /bin/sh
# sh
# /mnt/c/Windows/notepad.exe
Segmentation fault
# exit
# exit
```

* What's wrong / what should be happening instead:

Notepad should be launched, as it is if `/mnt/c/Windows/notepad.exe` is executed outside unshare.

* Strace of the failing command, if applicable:  

I have included straces from both outside the `sudo unshare ...` and of the `notepad.exe` separately here:

https://gist.github.com/cerebrate/656892026946f52bcf7e4dae9303df12

**Comment by cerebrate** [comment]
Additional note: it _doesn't_ fail if you execute `unshare` without `sudo`, but that makes `unshare` a lot less useful...

**Comment by therealkenc** [comment]
Has nothing to do with the namespace. If you do a simple `sudo su` or `sudo login -f root` and then run `/mnt/c/WINDOWS/system32/notepad.exe` you'll get the same segfault.

**Comment by cerebrate** [comment]
Hm. Guess I came at simplifying it from the wrong direction, although I could swear that had worked before.

**Comment by therealkenc** [comment]
> although I could swear that had worked before

Me too, but then I can't swear to that either. 

You don't need to summarily close if you don't want. I'm not sure that interop as `UID 0` _shouldn't_ work by-design. Or at least until someone authoritative says otherwise. That segfault is unsightly regardless. Worst case, say "`error: sorry interop as UID 0 isn't supported have a nice day`".

**Comment by cerebrate** [comment]
I'll open a properly described issue for it next I have a minute.
