### ISSUE TITLE
stderr not correctly bound --> crashes wsl container

### ISSUE THREAD

**Issue by bvandenbon** [microsoft/WSL#4466]
I noticed when I perform a `ubuntu1604 ~/dosomething`, if that `dosomething` command returns a message on stdout it works fine. But if it also returns a message on **stderr**, then the entire ubuntu container crashes, and it cannot be recovered. The only thing I can do is reboot my operating system (i.e. windows). After rebooting my entire computer I can use the ubuntu instance again. Everything works fine, until it returns something on that stderr.

It's different if I first connect with `ubuntu1604` and then afterwards execute the `~/dosomething`. In that if there is a message on the stderr everything just continues to work as expected. 

So, I assume something is wrong with how the stderr of the inner ubuntu process is bound to the stderr of the outer windows process.

**Comment by craigloewen-msft** [comment]
I'm unable to reproduce your problem after running a program with stderr output in both WSL 1 and WSL 2 the way you described.

What version of Windows are you using?
Could you provide some reproducible steps that we could try?

Thank you!
