### ISSUE TITLE
Distro Delete Itself From WSL

### ISSUE THREAD

**Issue by Seljuke** [microsoft/WSL#4469]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.295]

* What you're doing and what's happening:  Installing any distro from Store, Using it. After couple of restarts to windows the distro delete itself from wsl.

* What's wrong / what should be happening instead: Distro shouldn't delete itself from wsl

I was using my wsl yesterday, when I open my pc and try to connect wsl I found out it delete itself again. This happened 3 times, last distro I was using is Pengwin but the same issue happened with Ubuntu-18.04 too.
![image](https://user-images.githubusercontent.com/16338294/64321598-86e45d80-cfc9-11e9-93d4-7f9388f2ebac.png)

When this happened I have to start distro unpacking and set up it again.

**Comment by therealkenc** [comment]
Sounds external. No guesses.

**Comment by Seljuke** [comment]
> Sounds external. No guesses.

What do you mean by external? like another application that can affect windows features?

**Comment by therealkenc** [comment]
Yes. External to WSL. Something other than enabling the WSL feature, installing a distro, and running it.

**Comment by Seljuke** [comment]
> Yes. External to WSL. Something other than enabling the WSL feature, installing a distro, and running it.

I don't have any third party app or add-on or configuration to affect WSL. Is there any where I can look for logs or something?

**Comment by therealkenc** [comment]
Okay this has the same symptoms as #2986. That one was deemed addressed in 1809 (aka 18362 ie your version), but the details over there on collecting logs is the same. Have a look at #2576 as well (it's long). The TL;DR is try restarting the `LxssManager` service and see if that helps.

Hopefully you'll get some me2s if there was a regress, or if there is something similar but new going on.

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by benhillis** [comment]
Another potential cause of this issue was fixed in 19002.

**Comment by Seljuke** [comment]
I just found the culprit, the windows task scheduler. I have a task scheduled to run when user loged in. The task wast just starting the ssh service inside wsl. It looks like this
![image](https://user-images.githubusercontent.com/16338294/68472249-1fe55e00-0231-11ea-9f0e-b30efae503a2.png)
.

Even after Windows 1909 update wsl distro was keep deleting itself. So after I learnt that wsl keep couple minutes the start after user loged in, I just give task scheduler 15 minutes delay and everything is fine now.
