### ISSUE TITLE
wsl terminal getting stuck if receive special char "▒"

### ISSUE THREAD

**Issue by EpiqSty** [microsoft/WSL#4470]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.950]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
WSL terminal getting stuck after receiving special char like "▒"  : 

1. start  Debian app ( installed from Windows Store)
2. connect to Juniper firewall:
```
$ ssh fw
--- JUNOS 15.1X49-D170.4 built 2017-11-04 19:54:00 UTC
```
3. connect to secondary node:
```
{primary:node0}
fw> request routing-engine login node 1
 
```

* What's wrong / what should be happening instead:
If I am using putty for the same operation I see such output:
```
{primary:node1}
fw> request routing-engine login node 0
▒
--- JUNOS 15.1X49-D170.4 built 2017-11-04 19:54:00 UTC
{secondary:node0}
```

* Strace of the failing command:
https://gist.github.com/EpiqSty/e5c7865c495ff6d81bf07f0c6776ce46

**Comment by therealkenc** [comment]
> [Version 10.0.17134.950]

There is not enough information here to repro. Try 1903 aka 19H1 aka 18362 aka May 2019 Update as a baseline. If it doesn't help please post specific CLI steps starting from clean install of your distro.

1903 | 19H1 | 18362 | May 2019 Update
-- | -- | -- | --




1903 | 19H1 | 18362 | May 2019 Update
-- | -- | -- | --

**Comment by EpiqSty** [comment]
@therealkenc - thanks i'll try May 2019 Update and let you know
