### ISSUE TITLE
Allow bridged networking for WSL 2

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4472]
* Your Windows build number: 18970

Please allow the WSL 2 networking infrastructure to be configured for bridged mode, as well as the current NAT system.

Here are my reasons:

1. Simplicity. In my little home-office network here, I've got VMs, containers, a cluster, and an Azure virtual network; as such, I use bridging a _lot_, because what there's only one of is _me_. The flatter the network structure, the less time I have to spend playing network admin.

While the workaround to publish WSL 2-hosted services to the wider network (per #4150) does work for most protocols, it's also more overhead to keep track of, as is managing source/destination IP addresses in configurations with ever-shifting IP ranges (per #4467).

And since I have a /16 to play with, burning another IP address on WSL 2 isn't going to hurt.

2. IPv6, which at the moment the WSL Hyper-V infrastructure doesn't support, and which I'm using as the primary protocol on my network for everything that supports it. The reason I ask for it by this method and not a request for specific IPv6 support is because bridging also supports whatever other non-IPv4 protocols turn up tomorrow.

3. Incidentally fixes the other #4467 problem; I too have had the problem of the WSL interface happening upon a choice of private IP range in use elsewhere on the network.

**Comment by therealkenc** [comment]
#4150 is the landing zone.

**Comment by colemar** [comment]
See my equivalent solution
https://github.com/microsoft/WSL/issues/11632
