### ISSUE TITLE
some sigcontext fields always 0 (with test-case)

### ISSUE THREAD

**Issue by stsp** [microsoft/WSL#4473]
Some sigcontext fields, namely trapno and cr2, are always 0.
There are programs that do not work because of that.
I wrote a small test-case to help you reproduce this.

Test-case in C, to be compiled:
[segv.c.txt](https://github.com/microsoft/WSL/files/3580489/segv.c.txt)

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.18362.329

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```
$ cc -Wall -o segv segv.c
$ ./segv
test failed: 3 0, trapno 0
```

* What's wrong / what should be happening instead:

test-case detects inconsistency and writes that.
Under linux, this test-case passes.
Of course the test-case was made just for the bug report.
I am trying to run the program that relies on the trapno and
cr2 fields of sigcontext.

**Comment by craigloewen-msft** [comment]
Yup this repros in WSL 1, and doesn't in WSL 2. I'll mark this as a bug. Thanks for filing!

**Comment by therealkenc** [comment]
Same as #2555 #3657 #4007. There is test case [here](https://github.com/microsoft/WSL/issues/3657#issuecomment-437684189).

**Comment by stsp** [comment]
I dont think its a duplicate: all the
bugs you mentioned, and the test-case
are about missing FPU state. My bug
is about the missing exception info.
Even if technically they are result of
the same bug, I don't believe the
necessary analyses were done to make
such conclusion.
So I would appreciate if my bug is
re-opened.

**Comment by therealkenc** [comment]
> and the test-case are about missing FPU state. 

The [test case](https://github.com/microsoft/WSL/issues/3657#issuecomment-437684189) looks up the fault address in func `segv()`.

> I don't believe the necessary analyses were done

Couldn't tell you since it was first reported in #1692 ([message](https://github.com/microsoft/WSL/issues/1692#issuecomment-300891904)), and was subsequently [folded](https://github.com/microsoft/WSL/issues/1692#issuecomment-376040523) into #2555 as the landing zone for "SIGSEGV has no valid machine specific signal context".

**Comment by stsp** [comment]
Yes, I agree your test-case also looks up the faulting addr.
But:
1. It is provided in a thread named "Floating-point exception trapping not working",
meaning that non-fpstate problems may be missed there.
2. There is already a patch pending for fpstate, but it won't fix
my problem. And I very much doubt mine will be re-tested and
re-opened after the patch is applied.
3. Yours doesn't test the fact that also "trapno" is missing, mine does.
4. I simply forgot to test for "err" (exception error code), which is also missing.
5. Faulting address is in fact not a problem, you can get it from
siginfo_t::si_addr. That way seems to even work under wsl.
But missing "trapno" and "err" are nowhere to get from.

So at least bugs should be amended to make sure the
full exception info will be provided in the future. As it stands
now, 99% is the chance that you'll get only fpstate (by applying
the pending patch) fixed, but miss the rest.

**Comment by stsp** [comment]
> was subsequently folded into #2555 as the landing zone for
> "SIGSEGV has no valid machine specific signal context".

But it is named "ucontext_t fpregs ABI incompatibility".
Please amend ticket names, update test-cases etc, if
you don't want to just re-open mine.

**Comment by therealkenc** [comment]
#2555 #3657 #4007 will be sufficient to track your submission as named, but thank you for the suggestions.

[n.b., you want WSL2, where the problem has been addressed. Your issue has celebrated its second birthday since it was first reported.]

**Comment by stsp** [comment]
All the tickets you point, only mention fpstate
in their names... When only fpstate will be fixed,
I'll get back to ya're ass. :)

Waiting half a year or more for WSL2 (afaik
its not yet officially released) and switch to a
full-blown virtual machine (which is what I think
wsl2 is) just because of 2 sigcontext fields,
looks like the unreasonable trade-off.
