### ISSUE TITLE
Poor Angular startup performance

### ISSUE THREAD

**Issue by ARambazamba** [microsoft/WSL#4476]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18970.1005]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Open WSL
Install Node:
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs
Install Angular CLI - Scaffold a new project - run it
npm i @angular/cli
ng new whatever
ng serve

takes an eternity to startup

* What's wrong / what should be happening instead:
should start within max 20 sec on an i9 with m2

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by archilkarchava** [comment]
Are you using linux filesystem or windows ntfs? Try cding into your home folder in wsl and go from there.

**Comment by ARambazamba** [comment]
> Are you using linux filesystem or windows ntfs? Try cding into your home folder in wsl and go from there.

I am using my ordenary projects drive -> ntfs .... did not know that there also is linux fs available

Can I also format a partition of a hd with linux fs? dont want to work in home folders - not in windows - not in linux :-)

**Comment by craigloewen-msft** [comment]
Yes there is a Linux file system available! Please put your projects into your Linux file system to have much faster file IO performance.

And we don't have support for accessing another partition of the hard drive yet (though we have captured feedback!)

Your startup performance should significantly improve when moving to your Linux file system, so I'll mark this as closed. If you run into anymore issues, or have more questions please feel free to comment or reopen. Thanks!
