### ISSUE TITLE
Filesystem Feature and Performance Issues

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/WSL#4478]
_Submitted as per a [twitter convo](https://twitter.com/Omega_/status/1170031381969330176) with @craigloewen-msft._

**Please fill out the below information:**
* Your Windows build number:  `Microsoft Windows [Version 10.0.18975.1000]`

* What you're doing and what's happening:  In my particular case, I'm running the phpstorm IDE pointed at my `wsl$\Ubuntu` share, mapped as `W:`.
Over the course of using my WSL2-backed share, I receive warnings and experience very obvious performance degradation of static code analysis in the IDE.  I also am always shown the following notification on first run:

![image](https://user-images.githubusercontent.com/115199/64475572-3e07e280-d14a-11e9-8b00-d54b98ed27b6.png)

* What's wrong / what should be happening instead: I think static code analysis features should not be impacted by the fact that I'm using a share that - while it uses network-based technologies - is effectively on the same physical machine as my IDE.

**Comment by therealkenc** [comment]
wsl2 perf on wslfs is #4197
inotify on 9p is #4224, #4064, tangential #1956 ([message](https://github.com/microsoft/WSL/issues/1956#issuecomment-491266167)), others. (Yes,  "they are under a network mount.")

If your heart is set on JetBrains, drawing outside the lines and using VcXsrv or xrdp is route though, just like is was with VS Code before WSL Remote was invented.

**Comment by atrauzzi** [comment]
Sorry, I'm not sure I followed that last paragraph?

**Comment by therealkenc** [comment]
I decorated the paragraph with links with more information. It is possible in extremis to use [native Linux JetBrains PhpStorm](https://www.jetbrains.com/phpstorm/download/#section=linux), just as you would in a VM like [Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/)/[VirtualBox](https://www.virtualbox.org/)/[QEMU](https://www.qemu.org/), or as you would remotely from a headless cloud server. It isn't a supported scenario; at least in the sense that those third-party X server products aren't WSL actionable. But that doesn't stop lots of folks.

The current recommended practice ref #4169 [message](https://github.com/microsoft/WSL/issues/4169#issuecomment-502771420)) per this [blog post](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) is to access files on the WSL (Linux) side. Recent versions [VS Code](https://code.visualstudio.com/) now does this by running a service on the WSL (Real Linux [too](https://code.visualstudio.com/docs/remote/ssh)). But that is small consolation if your development environment isn't Code, natch.

**Comment by atrauzzi** [comment]
So is the message here to not expect to use the WSL2 share because it will never offer native performance and features?
