### ISSUE TITLE
Installing WSL2 and moving Linux to another disk drive

### ISSUE THREAD

**Issue by s-usr** [microsoft/WSL#4482]
Sharing the experience. See https://github.com/microsoft/WSL/issues/4451.

**Comment by s-usr** [comment]
Others who managed to move the distro using other methods are welcome to share their experience here.

**Comment by Alcheri** [comment]
### Move Your Linux Disk Image

The Linux disk image is installed on your C: drive. Optionally, you can move it to another drive to free up space. The following instructions presume you’ll move it to D:\wsl.

In a Windows Powershell terminal (not the Ubuntu terminal), enter wsl --list to view your Linux distributions, then export one by name to a back-up .tar file, e.g. D:\backup\ubuntu.tar:

`mkdir D:\backup`\
 `wsl --export Ubuntu D:\backup\ubuntu.tar`

Unregister the same distribution to remove it from the `C: drive`:

`wsl --unregister Ubuntu`

Enter `wsl --list` to verify the distribution has been removed.

Import the backup into a new WSL2 distribution at another location, such as `D:\wsl`:

`mkdir D:\wsl` \
`wsl --import Ubuntu D:\wsl\ D:\backup\ubuntu.tar`

Verify it has been successfully created by entering `wsl --list` and launching the Ubuntu app from the Start menu.

Unfortunately, Ubuntu will now use root as the default user. To use your own account, enter the following command:

`ubuntu config --default-user <yourname>`

Where `<yourname>` is the username you defined during installation.

Presuming all has gone well, you can safely delete the backup file (`D:\backup\ubuntu.tar`).
