### ISSUE TITLE
Softlinking explorer.exe has weird behavior.

### ISSUE THREAD

**Issue by JackGengChen** [microsoft/WSL#4485]
* Your Windows build number:  Version 1903 (OS Build 18362.329)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
![image](https://user-images.githubusercontent.com/42476505/64624203-482f1880-d3b8-11e9-91e2-e0437f7f552b.png)

* What's wrong / what should be happening instead:
I expect command line `explorer .` to behave the same as `explorer.exe .` after softlinking \usr\bin\explorer to explorer.exe. However, two issues emerged.  
1. I have to use sudo to call explorer, otherwise, nothing would happen.
2. `sudo explorer .` leads to the System32 folder instead of home directory folder of WSL. 
![image](https://user-images.githubusercontent.com/42476505/64624792-2aae7e80-d3b9-11e9-81ea-0f55394d39ea.png)

**Comment by craigloewen-msft** [comment]
This is a duplicate to this issue: https://github.com/microsoft/WSL/issues/3999 which has already been fixed! :)

Thank you for filing.
