### ISSUE TITLE
how to create "bash" alias in windows command prompt? 

### ISSUE THREAD

**Issue by pearsonkyle** [microsoft/WSL#4488]
Hello, 
My "bash" command accidentally disappeared from my command prompt despite having WSL installed. Does anyone know how to remake the alias? My file system is shown below for proof

![](https://i.stack.imgur.com/QeqO5.png)

**Comment by benhillis** [comment]
Could you try turning the feature off, reboot, turn feature on, reboot? Should pull bash.exe from the base image.

**Comment by therealkenc** [comment]
I think something out there in the wild (unrelated to WSL) is blowing away folks' Windows `%PATH%`. #4458 #4259.

**Comment by pearsonkyle** [comment]
I found bash.exe in C:\Windows\System32, I can cd into that directory and run bash from there. I guess I have to remake the alias. Everything seems to be working okay...

**Comment by therealkenc** [comment]
> I can cd into that directory and run bash from there

You do not need to (should not have to) cd into `C:\Windows\System32`. You do not need to make or remake a console alias.
