### ISSUE TITLE
debian won't start after windows 10 reboot

### ISSUE THREAD

**Issue by wsvdyk** [microsoft/WSL#4490]
* Your Windows build number: Microsoft Windows [Version 10.0.17763.615]

* What's wrong / what should be happening instead: I installed debian did some programming for arduino uno (school requires us to use linux) and uploaded it. Then I shutdown my laptop and now when I start debian again nothing is showing. The "Debian GNU/linux" shell is opening but the only thin I see in blinking cursor.

Commands done (might not be the full list as I'm doing it from mind):
[account creation stuff]
usermod -G sudo [accountname]
sudo id -a [accountname]
[logout of debian]
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install avr-libc gcc-avr gdb-avr binutils-avr avrdude make arduino-mk
sudo apt-get install git
mkdir src && cd src && mkdir -p opdracht1/blink
nano blink.c
[created a simple blink program]
nano makefile
[created a simple makefile]
sudo chmod 666 /dev/ttyS5
make upload

**Comment by craigloewen-msft** [comment]
This seems like a duplicate of https://github.com/microsoft/WSL/issues/2352 or https://github.com/microsoft/WSL/issues/4055 so perhaps some of the comments there might help you.

Could you do a few things:
- Run your distro and then query the state of lxssmanager by running `sc query lxssmanager` in CMD?
- Check if your console is running in legacy mode by right clicking on the title of the Window -> Properties -> Options -> Use legacy console and then try turning that on and off.
- Gather logs for us by following [these instructions](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Thanks!

**Comment by wsvdyk** [comment]
oops, totally forgot about this.

The issue resolved itself after a quick reboot of the windows computer. After that, the issue never came back.

I was able to replicate the issue again on a different computer, the same solution.
