### ISSUE TITLE
Error: 0x80070070 Press any key to continue... when entering bash subsystem

### ISSUE THREAD

**Issue by janeen-b** [microsoft/WSL#4492]
When tryingt to enter the subsystem of windows (bash this statement displays) Error: 0x80070070
Press any key to continue...

**Comment by craigloewen-msft** [comment]
I'd recommend trying to update your Windows version if you're able, as that will include many install fixes. 

Please let me know if you're able to upgrade, or any of the solutions in the threads I linked to helped you out.

**Comment by janeen-b** [comment]
Hello @craigloewen-msft , Thank you so much for the recommendation it work perfectly find now. I upgraded my windows versions and also followed issuse #2980. But i dont know which one cause it to start workin again.

**Comment by craigloewen-msft** [comment]
Brilliant! I'll mark this issue as closed, glad that it was resolved for you.
