### ISSUE TITLE
Problem of ROS2.0 talker/listener example on WSL1.0

### ISSUE THREAD

**Issue by b0mbard** [microsoft/WSL#4494]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [10.0.18970.1005]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I installed ROS2 according to this document:
[https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/](url)
Then I tried to run the demo_nodes_cpp _talker_ example in one bash:
 `source /opt/ros/dashing/setup.bash`
 `ros2 run demo_nodes_cpp talker`
and in another ubuntu terminal run a _listener_:
`source /opt/ros/dashing/setup.bash`
`ros2 run demo_nodes_cpp listener`
After that, the _talker_ said that it’s publishing messages:
`[INFO] [talker]: Publishing: 'Hello World: 1'`
but the _listener_ cannot receive any msgs, `ros2 topic list` cannot see the `/chatter` topic.

* BTW:
I installed WSL 2.0, then run this example again, it worked!
The _listener_ can get the msg:
`[INFO] [listener]: I heard: [Hello World: 24]`

**Comment by Gyudong-Han** [comment]
I have the same problem.

**Comment by b0mbard** [comment]
> I have the same problem.

@Gyudong-Han 
WSL 2 can fix this problem, but only works in VM's private network, other computer(ex: turtlebot) cannot connect to WSL 2 hosted on windows.
Maybe network forwarding can do something, see #4150 ,but first we should caculate DDS-RTPS's UDP ports with DOMAIN_ID, I'm still working on it.

**Comment by Gyudong-Han** [comment]
> > I have the same problem.
> 
> @Gyudong-Han
> WSL 2 can fix this problem, but only works in VM's private network, other computer(ex: turtlebot) cannot connect to WSL 2 hosted on windows.
> Maybe network forwarding can do something, see #4150 ,but first we should caculate DDS-RTPS's UDP ports with DOMAIN_ID, I'm still working on it.

@b0mbard 
Oh... 
At first, I think the problem is related with Windows Defender... but it was not.
Thank you for your reply. I will try to solve this problem.

**Comment by xindax2000** [comment]
Did you manage to solve the problem? What did you set up? How do you forward the network?
