### ISSUE TITLE
[WSL2] Using head with some binaries hangs the terminal

### ISSUE THREAD

**Issue by onomatopellan** [microsoft/WSL#4495]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.18980.1
Ubuntu 18.04 WSL2 from the Store.

* What you're doing and what's happening:
``head $(which gzip)``

* What's wrong / what should be happening instead:
In WSL1 it shows some characters and ends with the message "head: error writing 'standard output': Input/output error"
In WSL2 the Ubuntu terminal/Windows Terminal hangs after showing some characters and not even CTRL+C works. Only option is closing the tab/window.
Head works correctly in VScode's terminal with Remote WSL plugin or using xterm with VcXsrv though.

**Comment by onomatopellan** [comment]
@benhillis Can you reproduce this bug? Since gzip can be updated in any moment a better repro step would be:
 
`for i in /bin/*; do head ${i}; done`

With this there is always a binary that hangs the terminal. And this is weird but this is the output in VScode. It shows the prompt name with weird characters.

![bug](https://user-images.githubusercontent.com/599142/64912595-eeb94780-d731-11e9-8c07-9c3a8d2821b4.png)

**Comment by benhillis** [comment]
@onomatopellan - Sorry didn't see this thread.  I am not seeing a hang, but I am seeing us exit out of the shell when I run some binaries.  I'll look into this today.

**Comment by benhillis** [comment]
Tracking this here: https://github.com/microsoft/terminal/issues/3320

**Comment by onomatopellan** [comment]
Great, thanks!

**Comment by onomatopellan** [comment]
I just tested latest Windows Terminal on build 19033 and indeed problem it's already fixed. Thanks again!
