### ISSUE TITLE
WSL uninstalls after Windows 10 update

### ISSUE THREAD

**Issue by vichardy1** [microsoft/WSL#4496]
Last night, Windows 10 did an update - Cumulative update for ver 1903, KB4514359 - and this morning when I logged in and brought up bash it had to reinstall a new user.  This has happened once before and I chalked it up to chance but now it appears that this type of update is deleting all the user info.  The bash window was there but when I brought it up, the message was 'installing, please wait... and then I had to re-create my user name and a password.  Unfortunately, I have to reinstall my aliases, reconfigure .bashrc and my .ssh keys.  Annoying.

Does anybody have insights as to why this is happening and if there's anything I can do to mitigate it other than save all my keys and .bashrc outside of the wsl directories?  This is a ubuntu installation.

The only other thing that occurs to me is that I did some updates via the cli but not the version number, which I believe is 18.04 LTS.

Thanks in advance...

**Comment by benhillis** [comment]
Build [19002](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19002) has a fix that could potentially explain this.  Thanks for reporting the issue.
