### ISSUE TITLE
WSL 2 can't run on Arm64 WOS

### ISSUE THREAD

**Issue by ericvh** [microsoft/WSL#4499]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

18980.vb_release.190907-1301

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Trying to upgrade Ubuntu to use wsl 2 or install a new distro using wsl 2

(I've wsl --set-default-version 2)

then I start Ubuntu (already installed) or try some other distro I haven't installed.

* What's wrong / what should be happening instead:

I'm getting 0x80370102: could not be started because a required feature is not installed.

Went through and confirmed VM enabled and WSL enabled (wsl1 worked fine) -- assuming this is a BIOS problem on WOS, but when poking around UEFI no way to enable the feature.  Also doesn't seem to be any way to try and upgrade my BIOS outside of normal windows update stream so seem to be at a dead end.

**Comment by benhillis** [comment]
Which device do you have?  Your suspicion seems correct, the processor / firmware may not support virtualization.

**Comment by ericvh** [comment]
Yoga 630 and HPE Envy x2 -- (Qualcomm 850 and 835).  if I can ask, which systems have processor/firmware compatibility with WSL 2?

**Comment by benhillis** [comment]
I don't have a list of which systems support virtualization.  I know the Surface Pro X does, and I believe the Samsung Galaxy Book 2 does as well.

**Comment by mlindgren** [comment]
Based on [this page](https://support.microsoft.com/en-us/topic/virtualization-based-security-in-windows-10-on-arm-818468f0-d67f-9bf9-4a5c-183fa55c0898) it seems to me that the Snapdragon 850 should support virtualization. However, I could not find a way to enable the setting in the BIOS on my Samsung Galaxy Book 2.
