### ISSUE TITLE
Cant't start Ubuntu WSL 1 from shortcut

### ISSUE THREAD

**Issue by kskalski** [microsoft/WSL#4501]
* Your Windows build number: Microsoft Windows [Version 10.0.18975.1000]

* What you're doing and what's happening: I click on Ubuntu shortcut icon of task bar or select ubuntu from start menu, the terminal shows up for a fraction of a second and disappears

* What's wrong / what should be happening instead: the command line terminal should start normally. I actually managed to start it by typing ``ubuntu.exe`` on the search panel and selecting it, so it might be that some option used by the shortcut is causing the crash

* Strace of the failing command, if applicable:  I'm not sure how to collect the error if there is any, since starting ubuntu.exe from cmd or as a command from search bar (as opposed to clicking on app strore installed "application") doesn't trigger the problem

* For WSL launch issues, please [collect detailed logs]
I'm attaching the logs from the attempt to start ubuntu through Ubuntu application icon

[lxcore_kernel.zip](https://github.com/microsoft/WSL/files/3609146/lxcore_kernel.zip)

**Comment by kskalski** [comment]
same problem in new update: Microsoft Windows [Version 10.0.18980.1]

**Comment by definelicht** [comment]
Same issue here. I can run `ubuntu.exe` from cmd, but not from the start menu.

**Comment by CyrusNajmabadi** [comment]
Same here.  I'm on:

![image](https://user-images.githubusercontent.com/4564579/65447959-939bea80-ddec-11e9-8f39-62999811b064.png)

I can run ubuntu from cmd.exe, but my shortcut icon on my taskbar (or from start menu) dn't work.

**Comment by definelicht** [comment]
Opening the WSL shortcut works, only the Ubuntu shortcut crashes.

**Comment by benhillis** [comment]
Thanks for posting, we are debugging this internally.

**Comment by benhillis** [comment]
Good news, we have identified an issue with app migration that is causing this bug.  The Appx team is working on a fix.

**Comment by MichaelTong** [comment]
@therealkenc can you clarify whether the "fixedininsiderbuilds" refers to a future insider build? Because I'm on 19013 and still getting the issue.

**Comment by therealkenc** [comment]
Could have been premature; dunno. [Actually I am hoping we drop the distinction.]

**Comment by kskalski** [comment]
Finally looks like it's fixed in Microsoft Windows [Version 10.0.19023.1]
