### ISSUE TITLE
WSL2 doesn't release free memory

### ISSUE THREAD

**Issue by hwo411** [microsoft/WSL#4503]
* Your Windows build number:
Microsoft Windows [Version 10.0.18970.1005]

* What you're doing and what's happening:
I was regularly using WSL 2 (Ubuntu 18.04.3) with tmux, docker and vim. I checked windows task manager and discovered that vmmem.exe uses almost 8GB of memory. In `top` output in WSL 2 there were only around 1.3GB. After closing all apps the memory wasn't released and vmem continued using 8GB. Only wsl --shutdown released the memory.

* What's wrong / what should be happening instead:
WSL2 should release the free memory to Windows and shouldn't consume that match.

I was uploading screenshots, but green screen appeared, though they were showing that it's almost 8GB consumed by vmmem in WIndows task manager and that there is almost no processes and almost all memory is free in WSL 2 according to top command.

**Comment by onomatopellan** [comment]
Yes, the fix is coming. See #4166

**Comment by hwo411** [comment]
@onomatopellan thanks, somehow I missed this.

**Comment by athoynilimanew** [comment]
I still having the same issue in 2023. What was the fix again?
