### ISSUE TITLE
Two drivers related to WSL causing Kernel Mode Heap Corruption BSOD?

### ISSUE THREAD

**Issue by DragonOsman** [microsoft/WSL#4504]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.18362.356.

For a while when I had version 1809 of Windows 10 Home, I was facing a BSOD issue with the stop code Kernel Mode Heap Corruption.  It still appeared some time after updating to version 1903.  I went to the Microsoft Support forums and asked there but it didn't help much, so I went to Ten Forums instead.  I used their log extraction program to get my logs and files that showed what the problem might be and was told that most of it seems to be related to two WSL drivers.  There was also something about WWAJSE and my Norton Security extension to MS Edge; I uninstalled the latter but still don't know what the former is exactly.  I did a repair upgrade of Windows 10 and chose to only keep my files while removing everything else.  It's fine so far.  I'm scared to install WSL again.  [Here](https://www.tenforums.com/bsod-crashes-debugging/140074-bsod-after-updating-windows-10-version-1903-a.html) is a link to the Ten Forums thread.

Note: This is not exactly a WSL issue post.  I just want to report the two drivers that may have been a possible cause.

**Comment by GregAndo** [comment]
Ditto, I can very reliably reproduce this by setting up a WSL v1 Ubuntu environment, and attempting to install go.  The commands I used were:

sudo apt-get update
sudo apt-get install golang

Blue screens with the kernel mode heap corruption error message without failure...
