### ISSUE TITLE
(Ubuntu 18.04.3) showkey eats keystrokes, doesn't work

### ISSUE THREAD

**Issue by GittyupMule** [microsoft/WSL#4506]
* Your Windows build number: `18362.356`

* What you're doing and what's happening:

Attempting to run `sudo showkey` with any argument except `-h` (help) results in the following error:
```
kb mode was UNICODE
[ if you are trying this under X, it might not work
since the X server is also reading /dev/console ]

showkey: ioctl KDSKBMODE: Invalid argument
```
The terminal then "eats" all keystrokes so that they are not visible (except for Ctrl+C, which prints "^C" to the terminal), although they are processed (like entering a password) 

* What's wrong / what should be happening instead:

Showkey should be reporting the scancodes of all keypresses until exited.

* Strace of the failing command, if applicable: (same as stdout output)

**Comment by therealkenc** [comment]
#1806
