### ISSUE TITLE
Can't access Windows socks5 tunnel from WSL2

### ISSUE THREAD

**Issue by oliviercwa** [microsoft/WSL#4507]
**Environment**

- Windows build number:  1903 (OS Build 18980.1)
- Distro: Ubuntu-18.04

**Repro steps:**
From Windows Powershell: Create a SOCKS 5 tunnel to an SSH Server:

> ssh -D 0.0.0.0:20000 USER@IP_ADDRESS

Validate that the proxy is working. For my specific environment, I have a web server that i can query using:

> curl --socks5 127.0.0.1:20000 http://10.0.2.5:8081

This returns a response (a Spring Boot configuration JSON payload)

Next go to WSL2 mode

> wsl

> curl --socks5 127.0.0.1:20000 http://10.0.2.5:8081

Result:
"curl: (7) Failed to connect to 127.0.0.1 port 20000: Connection refused"

> curl --socks5 localhost:20000 http://10.0.2.5:8081

Result:
"curl: (7) Failed to connect to localhost port 20000: Connection refused"

Expected:
- Curl request from WSL to work as well.

**Comment by therealkenc** [comment]
ref #4402

**Comment by oliviercwa** [comment]
Thank you very much for the quick answer. I have tried the first method from [here ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes): 

> cat /etc/resolv.conf 

and copying the IP address following the term nameserver but it did not work.

**However the second method did work**: Establish the tunnel from WSL

Thanks again

**Comment by lackovic** [comment]
I am running into the same issue, can't establish a connection in the `WSL->Windows` direction.

@oliviercwa can you elaborate more on how you managed to fix this problem?

**Comment by oliviercwa** [comment]
You need to create the tunnel **not** from a windows command prompt, but from a WSL command prompt. In windows, launch powershell, then type:
```
wsl
```
This will enter the wsl model

Then create your tunnel, for example:
```
ssh -D 0.0.0.0:20000 USER@IP_ADDRESS
```
Then curl will work properly

Note that I am running WSL2 from Windows 10 version 19035.1

**Comment by lackovic** [comment]
I have a service running in WSL (listening on `127.0.0.1:3000`) which needs to access a service running in Windows on `127.0.0.1:5432`.

My WSL `resolv.conf` file:

```shell
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.224.1
```

When I run `ssh -D 127.0.0.1:5432 marco@192.168.224.1` I get the following error:

```shell
ssh: connect to host 192.168.224.1 port 22: Connection timed out
```

Also using WSL2 from Windows 10 version 19035.1

**Comment by oliviercwa** [comment]
Are both these services running on the same machine? If so, you don't need a tunnel for this. You should be able to call the Windows service directly.

**Comment by lackovic** [comment]
Yes, they are both running on the same machine.

I am not able to access the service directly, the service in WSL returns the error:
```shell
PG::ConnectionBad - could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

Also, in WSL:

```shell
curl 127.0.0.1:5432
curl: (7) Failed to connect to 127.0.0.1 port 5432: Connection refused
```

while on Windows it works fine:

```shell
curl 127.0.0.1:5432
curl: (52) Empty reply from server
```

According to ref #4402, this is expected because tunneling 127.0.0.1 does not currently work in the `WSL->Windows` direction.

**Comment by lackovic** [comment]
I must point out also that everything works perfectly fine in WSL 1.
The issue occurs only with WSL 2.

**Comment by lackovic** [comment]
Today I have updated to Windows 10 version 19037.1 and tunneling `127.0.0.1` stopped working in the `WSL->Windows` direction with WSL 1 too: I get the same error I get on WSL 2 mentioned above.

**Comment by therealkenc** [comment]
> I must point out also that everything works perfectly fine in WSL 1.

Right #4402, aka  #4619 (with a side of #4199, #4210, #4711)

**Comment by danksuperuser** [comment]
I have a proxy client running on windows which provides a socks5 proxy. This client has been set to listening 127.0.0.1:9050 .I want to use it in WSL2 Kali Linux terminal.How can I ??

Exactly what I am trying to do is ,to rotate IP's in kali Linux terminal WSL2 via windows client proxy application. The proxy application itself changes/rotate proxy
frequently no need of other application in the WSL2.

So the only need is How can I connect it in WSL.

The proxy client supports socksv5 so I have to set the WSL to socksv5 proxy.

TIA!

@therealkenc

**Comment by sanjaychauhan7321** [comment]
@danksuperuser  did you get your query answered???

I am facing the same problem, want to access this socks5 client running on windows on my vs-code running on wsl
