### ISSUE TITLE
WSL (Ubuntu) install fails with Error: 0x80070005 Access is denied.

### ISSUE THREAD

**Issue by n3jain** [microsoft/WSL#4514]
* Your Windows build number: 18362.239

* What you're doing and what's happening:  Launch Ubuntu from Microsoft store. Even tried ubuntu 18.04

* What's wrong / what should be happening instead: Should have prompted for setting username and password, instead returned error `Access Denied`

I followed the instructions for collection of detailed logs but the filetype generated is `lxcore_*.etl` and I can't include it with this issue.

**Comment by craigloewen-msft** [comment]
Are you able to run `wsl.exe -l` in PowerShell or command prompt? 

And please try putting all of your logs into a zip file and uploading that.

**Comment by n3jain** [comment]
I ran the powershell as admin and I am getting following error

`Program 'wsl.exe' failed to run: Access is deniedAt line:1 char:1`
`+ .\wsl.exe`
`+ ~~~~~~~~~.`
`At line:1 char:1`
`+ .\wsl.exe`
`+ ~~~~~~~~~`
`   + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException`
`    + FullyQualifiedErrorId : NativeCommandFailed`

**Comment by craigloewen-msft** [comment]
It looks like your machine is unable to access the LxssManager service. This seems overall similar to the problem that [this user experienced](https://scriptech.io/windows-10-1903-wsl-access-is-denied-error-0x80070005/) (And thanks to them for creating a writeup on the problem!).

Is this a work computer with group policies on it? Or is this your own private computer?

**Comment by n3jain** [comment]
This is a work computer

**Comment by craigloewen-msft** [comment]
Seems likely that it could be related to what that user experienced and wrote about: Some form of security or group policy is not allowing you to access the LxssManager service. I'd investigate your group policies and security to see if you can resolve it there.

**Comment by safwaan-menk** [comment]
> It looks like your machine is unable to access the LxssManager service. This seems overall similar to the problem that [this user experienced](https://scriptech.io/windows-10-1903-wsl-access-is-denied-error-0x80070005/) (And thanks to them for creating a writeup on the problem!).
> 
> Is this a work computer with group policies on it? Or is this your own private computer?

Please fix or remove the link in this reply. If it was once a legitimate link, it no longer is.
