### ISSUE TITLE
WSL2: File operations on NTFS  folders extremely slow

### ISSUE THREAD

**Issue by mwidmann** [microsoft/WSL#4515]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18980.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

My original projects folder resides on c:\projects, mounted into debian (wsl1, unable to convert) as `~/projects`. It has a set of git projects in it. Performing a `git status` on one of those folders, e.g. one Project with less then 5000 files takes little time:

```
❯ time git status                                                                                                                                               On branch bugfix/mobile-menu
Your branch is up-to-date with 'origin/bugfix/mobile-menu'.
nothing to commit, working tree clean
git status  0.05s user 3.23s system 378% cpu 0.867 total
```

Ubuntu 18.04 (WSL2, converted) is painfully slow on this kind of operations on the same folder.

```
❯ time git status                                                                                                                                               On branch bugfix/mobile-menu
Your branch is up to date with 'origin/bugfix/mobile-menu'.


It took 3.31 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working tree clean
git status  5.66s user 22.04s system 41% cpu 1:06.64 total
```

Same occurs in node projects, where `npm run dev` takes over a minute in a relatively small nuxt project do just get started.

* What's wrong / what should be happening instead:

I expected not only the ext4 filesystem in WSL2 to be much faster than in previous versions, but also accessing mounted local files/directories to be at least as performing as in WSL1. Some projects need to stay on the /c/- mount as certain applications don't  want to open files from the \\wsl$\ share.

**Comment by craigloewen-msft** [comment]
Hi @mwidmann we are tracking this issue over in https://github.com/microsoft/WSL/issues/4197 so I'm going to mark this as a duplicate and close it out. 

And we are looking into ways to improve this experience! Please follow the other thread for any updates.
