### ISSUE TITLE
While connected to VPN the curl command hangs up

### ISSUE THREAD

**Issue by Darkside81** [microsoft/WSL#4517]
OK: From our office and from home remotely, we can use the VPN connection, curl succeeds. 
OK: While visiting our customer's office, without using the VPN connection, curl also succeeds. 
FAIL: While visiting our customer's office, when using the VPN connection, curl hangs as follows:
```
$ curl ifconfig.co; curl -vvv https://testlink.limelightbox.com 
198.199.107.195 
* Rebuilt URL to: https://testlink.limelightbox.com/ 
* Trying 52.39.78.238... 
* TCP_NODELAY set 
* Connected to testlink.limelightbox.com (52.39.78.238) port 443 (#0) 
* ALPN, offering h2 
* ALPN, offering http/1.1 
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH 
* successfully set certificate verify locations: 
* CAfile: /etc/ssl/cert.pem 
CApath: none 
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```
Above simply hangs.

Can someone assist with advice

**Comment by craigloewen-msft** [comment]
What build of Windows are you using? And are you using WSL 1 or WSL 2?

**Comment by therealkenc** [comment]
Also maybe try [Windows `curl.exe`](https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/) with the VPN up and see if that takes, just for the datapoint. Eliminates WSL if it doesn't work. Points finger at WSL if it does.

**Comment by Darkside81** [comment]
I'm using WSL 2

**Comment by craigloewen-msft** [comment]
@Darkside81 and @zot could you please take networking logs of the issue that you're seeing? Instructions on how to do so are [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs). Please comment back on this thread with a link to your feedback item and we can take a look at what might be causing it! Thanks!

**Comment by zot** [comment]
OK, here's the [link](https://aka.ms/AA681j4).

**Comment by zot** [comment]
I'm able to use services on our VPN by port-forwarding with SSH from within Windows-land. Maybe other people with this problem can use a similar technique. Here's my script (run it from git-bash/msys/cygwin):
```
#!/bin/sh
MAIL_HOST=YOUR-MAIL-HOST
SSH_USER=YOUR-USER-NAME
SSH_HOST=YOUR-VPN-SSH-HOST
ADDR=$(ipconfig|sed '/WSL/ {N;N;N;N;s/\n//g;s/^.*: \([^:]*\)$/\1/;p};d')
echo $ADDR
exec ssh -L $ADDR:11000:$MAIL_HOST:110 -L $ADDR:2500:$MAIL_HOST:25 $SSH_USER@$SSH_HOST
```
It just finds the ip addr of the WSL adapter, prints it out, and uses SSL to port-forward 11000->110 and 2500->25 on it.

Configure your Linux email client to use the printed IP address and port 11000 for pop, 2500 for outgoing.

Note that the WSL switch changes IP every time you boot: https://github.com/microsoft/WSL/issues/4150

I have a second workaround for this, I created a NAT switch Hyper-V Manager and I actually use that instead of the WSL adapter (my script uses Ethernet NAT instead of WSL). It has a static IP, so it doesn't change every time I boot.

**Comment by timesnewmen** [comment]
> I'm able to use services on our VPN by port-forwarding with SSH from within Windows-land. Maybe other people with this problem can use a similar technique. Here's my script (run it from git-bash/msys/cygwin):
> 
> ```
> #!/bin/sh
> MAIL_HOST=YOUR-MAIL-HOST
> SSH_USER=YOUR-USER-NAME
> SSH_HOST=YOUR-VPN-SSH-HOST
> ADDR=$(ipconfig|sed '/WSL/ {N;N;N;N;s/\n//g;s/^.*: \([^:]*\)$/\1/;p};d')
> echo $ADDR
> exec ssh -L $ADDR:11000:$MAIL_HOST:110 -L $ADDR:2500:$MAIL_HOST:25 $SSH_USER@$SSH_HOST
> ```
> 
> It just finds the ip addr of the WSL adapter, prints it out, and uses SSL to port-forward 11000->110 and 2500->25 on it.
> 
> Configure your Linux email client to use the printed IP address and port 11000 for pop, 2500 for outgoing.
> 
> Note that the WSL switch changes IP every time you boot: #4150
> 
> I have a second workaround for this, I created a NAT switch Hyper-V Manager and I actually use that instead of the WSL adapter (my script uses Ethernet NAT instead of WSL). It has a static IP, so it doesn't change every time I boot.

How can you set the WSL VM use the "NAT Switch" you have created?

**Comment by zot** [comment]
> > I'm able to use services on our VPN by port-forwarding with SSH from within Windows-land. Maybe other people with this problem can use a similar technique. Here's my script (run it from git-bash/msys/cygwin):
> > ```
> > #!/bin/sh
> > MAIL_HOST=YOUR-MAIL-HOST
> > SSH_USER=YOUR-USER-NAME
> > SSH_HOST=YOUR-VPN-SSH-HOST
> > ADDR=$(ipconfig|sed '/WSL/ {N;N;N;N;s/\n//g;s/^.*: \([^:]*\)$/\1/;p};d')
> > echo $ADDR
> > exec ssh -L $ADDR:11000:$MAIL_HOST:110 -L $ADDR:2500:$MAIL_HOST:25 $SSH_USER@$SSH_HOST
> > ```
> > 
> > 
> > It just finds the ip addr of the WSL adapter, prints it out, and uses SSL to port-forward 11000->110 and 2500->25 on it.
> > Configure your Linux email client to use the printed IP address and port 11000 for pop, 2500 for outgoing.
> > Note that the WSL switch changes IP every time you boot: #4150
> > I have a second workaround for this, I created a NAT switch Hyper-V Manager and I actually use that instead of the WSL adapter (my script uses Ethernet NAT instead of WSL). It has a static IP, so it doesn't change every time I boot.
> 
> How can you set the WSL VM use the "NAT Switch" you have created?

No, I'm using a vanilla WSL 2 Ubuntu setup except that I'm limiting the memory usage (currently to 8G).

**Comment by zot** [comment]
> How can you set the WSL VM use the "NAT Switch" you have created?

Maybe my last comment wasn't so helpful. I just used a virtual switch I already had lying around. It's not actually connected to WSL 2 or any other VM. To make one, open the Hyper-V Manager and click "Virtual Switch Manager...". Then create a new virtual switch like this, hooking it into your ethernet or wifi network, whichever one you use:

![image](https://user-images.githubusercontent.com/26665/66890612-5c85b700-efef-11e9-9688-b6f3776ccc78.png)

Once you've created it, use ipconfig to see the IP address Windows has assigned to it. Mine uses a dynamic IP but Windows has given it the same IP every time I've booted, so far. 

I tried using Default Switch, because I wanted it to work with both ethernet and wifi but that didn't work for me.  Once you've made the switch, make your SSH tunnel listen on its address, like in my script, above.

**Comment by giggio** [comment]
I'm having the exact same problem, I can't work when connected to my company network. The network does not seem to work in some scenarios.
DNS resolution works.
Curl does not work, either with http or https.

This is what I get on http:

````
❯ curl --verbose http://www.google.com
*   Trying 172.217.29.132:80...
* TCP_NODELAY set
* Connected to www.google.com (172.217.29.132) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.65.3
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
````

On https the log is the same as from this issue, but I'm on TLS 1.3:
````
❯ curl --verbose https://www.google.com
*   Trying 172.217.29.132:443...
* TCP_NODELAY set
* Connected to www.google.com (172.217.29.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
````

I'll report the logs as explained earlier, as well.

I'm on Windows Version 10.0.19041.207, WSL 2, Ubuntu 18.10 (but it also repros on Suse).

curl.exe works on Windows normally.

curl works when the vpn is not being used.

**Comment by kaskii** [comment]
I have same issue as @giggio except that my curl works for public addresses such as google.com. Any internal resource inside company private network I get the same behavior as @giggio. Windows side works fine. Check Point Mobile VPN client opened in Windows that to my knowledge should route ALL traffic via company network. 

I made the feedback as @craigloewen-msft instructed and it can be found [here](https://aka.ms/AA8a2uy). Hope it helps.

**Comment by FallenMax** [comment]
I'm having the same issue with WSL2+VPN:

- ping company website domain - ok
- curl/wget company website from wsl2 - **hangs**
- curl/wget external website from wsl2 - ok
- curl/wget company website from cmd.exe - ok

To get around this problem, I'm redirecting http(s)/ssh requests in wsl2 through a proxy set up in Windows-land, and curl/wget/git are working properly now. Hope it helps.

**Comment by giggio** [comment]
@FallenMax how did you do that? Please share, that would be very useful to me right now.

**Comment by FallenMax** [comment]
@giggio Here's my setup:

### 1. Setup a HTTP or SOCKS5 proxy in Windows-land

I'm using [cow](https://github.com/cyfdecyf/cow/blob/master/README-en.md), as I already have it installed (you can use whatever proxy software works). My cow config `rc.txt` is as below:
```
listen = http://0.0.0.0:7777
```

It does nothing other than proxying traffic from port 7777 to Windows network.

### 2. Setup curl/wget/git in WSL2 to use the Windows proxy above

- To delegate the traffic of curl/wget, I'm using [proxychains-ng](https://github.com/rofl0r/proxychains-ng), it's a little bit complex but I think just setting up `http_proxy` and `https_proxy` environment variable instead should be enough. e.g. `export http_proxy=http://${your windows local IP}:7777` 
- To delegate `ssh` protocol for git and ssh, add these config to `~/.ssh/config`:

```
Host git.yourcompany.com
User git
ProxyCommand nc -X connect -x 192.168.2.171:7777  %h %p
```

replace `git.yourcompany.com` with your company's Gitlab host, and replace `192.168.2.171` with your Windows machine's local IP (see ipconfig.exe) and it's done.

**Comment by giggio** [comment]
Thanks, @FallenMax, this works perfectly.
Cow is a cool project, it's a pity I can't understand most of it because of the Chinese. But it will solve other issues for me, so thanks for that too.

I hope someone from the WSL team is able to investigate this in the meantime.

**Comment by FallenMax** [comment]
@giggio Thank you, glad it helps! English version of Cow's [README.md](https://github.com/cyfdecyf/cow/blob/master/README-en.md) and [example config](https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc-en) are available if needed.

**Comment by neseih** [comment]
May this could be a fix for you:
Set MTU to the value of the VPN interface:
`sudo ifconfig eth0 mtu 1350`

**Comment by giggio** [comment]
@neseih this actually solves the problem. What exactly is going on? How do I found out the 1350 number, is it on Windows somewhere?

**Comment by neseih** [comment]
You could type in cmd.exe `netsh interface ipv4 show subinterfaces` and look at the leftmost column MTU.

It seems like I found out in packet dumps the ssl handshake is fragmented and gets dropped for some reason.

**Comment by giggio** [comment]
Cool. I'm trying now to set it permanently, but things seem a little different from a default Ubuntu installation. And as this needs to run as root, I can't add it to my init scripts.
I also found out that mtu 1400 also works for me. That is the value set in my VPN, my LAN works at 1500.

**Comment by giggio** [comment]
I went the other way around, and found out that my VPN accepts 1500. I set it on Windows to 1500, but Ubuntu keeps failing, unless I set it to 1400. I have no idea why.
This article explains how to set the MTU for a VPN on Windows, and how to test for the correct MTU: https://support.purevpn.com/how-to-change-mtu-value-on-windows-xp-vista-7-and-8

**Comment by zot** [comment]
> May this could be a fix for you:
> Set MTU to the value of the VPN interface:
> `sudo ifconfig eth0 mtu 1350`

Fantastic, works for me! Thanks!

**Comment by MoeRT09** [comment]
Hello,

just jumping into the discussion as I'm experiencing the same problem while connecting via SSH over a VPN connection.

Setting the MTU manually can't be the solution to this issue. In the screenshot below you can see a traffic capture on the WSL interface as well as the VPN interface. Up until packet 29 everything lines up on both interfaces. At packet 30, fragmentation happens. This is exactly the point where my SSH connection froze (just launching `htop`). As you can see, fragmented packets don't get forwarded to the WSL interface which causes this issue.

![Clipboard 1](https://user-images.githubusercontent.com/8270908/83035894-4b4b6100-a03a-11ea-8272-1b10a06f0fc1.png)

**Comment by zot** [comment]
I don't see an extra network interface, it looks to me like Shrew Soft installs a "Shrew Soft Lightweight Filter" into the current network adapter (properties show up in my network bridge). I don't know the command to list this so I'm using the network adapter GUI and it looks like this:

![image](https://user-images.githubusercontent.com/26665/83346532-ec316900-a325-11ea-82f8-d8d7c2582757.png)

**Comment by erikmack** [comment]
WSL2 hangs indefinitely when I try to manually set MTU to 1400 with 'sudo ip link set dev eth0 mtu 1400' and a full reboot is necessary.  This hang occurs whether or not I'm connected to our Pulse VPN.

+1 for this issue.  When connected to our Pulse VPN many network connections hang, certainly due to the still-1500 MTU in the WSL2 environment.

Oddly I can sometimes work around the issue by exec'ing into a Debian docker container from the Debian WSL2 environment and doing my network operation there.  I'm not sure why this works, since the interface in the container also maintains a 1500 MTU.

**Comment by erikmack** [comment]
Since getting the latest kernel I'm now able to set MTU successfully.

**Comment by giggio** [comment]
@erikmack what is your new kernel version? How did you get the new version?

**Comment by erikmack** [comment]
It's a manual .msi and download from [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel).  I'm currently on
```
erikm@erikm-pc2:~$ uname -a
Linux erikm-pc2 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux
```

**Comment by victorsferreira** [comment]
I still have this problem with Checkpoint VPN

**Comment by alex20465** [comment]
This has nothing to do with WSL I have exact the same issue with a native ubuntu installation:

CURL / SSH every IPv4 connection hangs:

```
*   Trying 142.250.185.228:443...
* TCP_NODELAY set
* Connected to www.google.com (142.250.185.228) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```

Other IPv6 supported connections are successfully communicating.

**Comment by Paladinhanxiao** [comment]
> Cool. I'm trying now to set it permanently, but things seem a little different from a default Ubuntu installation. And as this needs to run as root, I can't add it to my init scripts. I also found out that mtu 1400 also works for me. That is the value set in my VPN, my LAN works at 1500.

So how do you set it permanently?

**Comment by RioChndr** [comment]
> May this could be a fix for you:
> Set MTU to the value of the VPN interface:
> `sudo ifconfig eth0 mtu 1350`

This works for me too.

my kernel

```
uname -a
Linux RioChndr-Lenovo-Legion 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I make it permanent by add this line to `/etc/wsl.conf`
```
[boot]
command = sudo ifconfig eth0 mtu 1350
```

**Comment by XrestRus** [comment]
I'll leave it for the future.

The utilities from the terminal did not work for me, but the browser worked

For some reason, the problem was in the Outline client, I changed it to amnesia, and everything worked.
 
🤔
