### ISSUE TITLE
update-binfmts does not persist when WSL2 restarted

### ISSUE THREAD

**Issue by danwalmsley** [microsoft/WSL#4520]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18980.1

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
im installing qemu, inside ubuntu (WSL2 enabled)

then doing... sudo update-binfmts --enable qemu-aarch64

then  im using code that runs aarch64 binaries, all is well.

* What's wrong / what should be happening instead:

after restarting wsl2 then I have to run this command again, its not persisted. In other environments this would normally persist.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
No `systemd` so no [`systemd-binfmt.service`](https://www.freedesktop.org/software/systemd/man/systemd-binfmt.service.html). Landing zone is #994.

**Comment by danwalmsley** [comment]
@therealkenc thats fine, but there may be a workaround to my issue? Like a config file you can specify commands that get run as root, whenever the vm fires up? or before ubuntu console is opened?

**Comment by Biswa96** [comment]
One _bizarre_ idea would be: set root as default user > Add the binfmt command in root's `.bashrc` (or other) file > Then add `su` to change to normal user.

**Comment by therealkenc** [comment]
The go-to solution for all things missing from `/init` is to put the program in `/etc/sudoers` with `NOPASSWD` and launch it in `.bashrc`. There's a few other ways you can go.

Mine personally is using the shell history......

**Comment by danwalmsley** [comment]
@therealkenc sorry for delay in response, thank you very much exactly what I needed.
