### ISSUE TITLE
Use mainline Kernel with WSL2

### ISSUE THREAD

**Issue by microhobby** [microsoft/WSL#4521]
This is not really a issue. It is actually a request. I am trying to run a mainline kernel on WSL2 but without success. I can build the 4.19.y and run it. I would like to ask the team to provide perhaps a to do list of what still needs to be integrated into the mainline. So the community could help with development.

**Comment by therealkenc** [comment]
Here is the list of [differences](https://gist.github.com/therealkenc/4b5256af912329cd279cf6f5e6a4f6ac) that would need to be integrated (not including the kconfig). Bonne chance.

**Comment by Biswa96** [comment]
OMG! Did you diff the whole Linux kernel repository? How much time/CPU/heat did it take?

**Comment by therealkenc** [comment]
1.4 seconds.

![image](https://user-images.githubusercontent.com/7049700/65223991-20564980-da77-11e9-91cc-247f065f45e0.png)

**Comment by Biswa96** [comment]
Didn't you change the config?

**Comment by microhobby** [comment]
I push the merge on my GitHub, so if anyone is interested or finds out what is missing ...
https://github.com/microhobby/linus-tree/tree/wsl2

**Comment by therealkenc** [comment]
Excellent. Convo can continue over in your repo.

**Comment by microhobby** [comment]
This was fixed by Kernel Mainline, it is now possible to use a custom kernel with the source of Linus Torvalds: https://youtu.be/N6b7DZKbvEE
