### ISSUE TITLE
Install failed: system cannot find the file specified

### ISSUE THREAD

**Issue by AvailCat** [microsoft/WSL#4524]
* Your Windows build number:  10.0.18362.239

* What you're doing and what's happening:  
Install "OpenSUSE-Leap-15-1" from Microsoft Store and launch it, but install failed with success tips and error message.

* What's wrong / what should be happening instead:
There should no error message

* For WSL launch issues, please [collect detailed logs]
See attachment.
[lxcore.zip](https://github.com/microsoft/WSL/files/3630770/lxcore.zip)

Output:
>
>C:\Users\seeyo> openSUSE-Leap-15-1.exe
>Installing, this may take a few minutes...
>Installation successful!
>系统找不到指定的文件。**(Translate: System cannot find the file specified.)**
>系统找不到指定的文件。
>Please create a default UNIX user account. The username does not need to match your Windows username.
>For more information visit: https://aka.ms/wslusers
>Enter new UNIX username: someusername
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>系统找不到指定的文件。
>**And more same error message...**
>

**Comment by Meeeeow** [comment]
Solved by follow the first of https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting .

But why Debian and Ubuntu works with same setting?
