### ISSUE TITLE
poll system call return pipes with writable bytes < PIPE_BUF

### ISSUE THREAD

**Issue by dizzam** [microsoft/WSL#4525]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.356]

* What you're doing and what's happening:  poll system call return pipes with writable bytes < PIPE_BUF

The following code created a pipe and write to fill its capacity (typically 64k) until only one bytes is left. Then it tries to poll the write end to see if it is still writable. It returns "Yes" in WSL.

```c
#include <unistd.h>
#include <poll.h>
#include <stdio.h>

int main()
{
    int pipefd[2];
    pipe(pipefd);

    char buf[1024] = {0};
    for (int i = 0; i < 63; i++)
    {
        write(pipefd[1], buf, 1024);
    }
    write(pipefd[1], buf, 1023);  // Write to the pipe until only one byte left

    struct pollfd pfd = {pipefd[1], POLLOUT, 0};
    if (poll(&pfd, 1, 1000) == 0)
    {
        printf("No\n");
    }
    else
    {
        printf("Yes\n");
    }
}
```

* What's wrong / what should be happening instead:  According to POSIX.1, pipe I/O operations guarantee its atomicity when the number of bytes to write <= PIPE_BUF. Therefore, **in Linux kernel. the poll syscall would not return the pipe when its writable bytes < PIPE_BUF**. Although I cannot find this feature defined explicitly in POSIX.1, it was implemented by many UNIX and UNIX-like systems in practice. 

A lot of softwares depend on this feature. For example, the CPython subprocess module [says](https://github.com/python/cpython/blob/3171d67a6aaf7fe88685b3a80644f0284686ef63/Lib/subprocess.py#L215-L218 ):

```python
    # When select or poll has indicated that the file is writable,
    # we can write up to _PIPE_BUF bytes without risk of blocking.
    # POSIX defines PIPE_BUF as >= 512.
```

Therefore, if we want to pass data to the subprocess through stdin, the main process is likely to be permanently blocked and make a deadlock in WSL. But that is not the case in Linux.

**Comment by therealkenc** [comment]
Great report. This reproduces on WSL1 on 18980 Insider as well. I also checked, and despite the "Yes", it does indeed block on the next write. [This is obvious to you natch, but wanted to state that explicitly.]

This has not been reported before, which is unusual in the sense that if it were causing widespread fall-downs (in say CPython) it would have been. Speculating, I suspect much code in the wild ends up blocking on the write (instead of the poll). Then the other end eventually drains some bytes, the write unblocks, and the code limps along despite the incorrect behavior. But that only a guess. It is, obviously, a problem for your use case, or you wouldn't have brought it up today.

I'm trying to think of a source work-around to get you by, but can't off the top off my head (short of unrealistically extreme measures). The way you'd normally test would be to use poll or select of course (the whole point). 

Your test case will be okay in [WSL2](https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/) if you are able to entertain running Insiders.

**Comment by dizzam** [comment]
Well, I'm trying to figure it out. In my situation, a python program is trying to send a pdf file to a subprocess (ghostscript) for processing, and get its output for sending to an upstream server. And I indeed found that the python program and the subprocess simultaneously block on write. So I write a small program to show this procedure.

```c
#include <limits.h>
#include <unistd.h>
#include <poll.h>
#include <stdio.h>

int main()
{
    int w[2];
    int r[2];
    pipe(w);
    pipe(r);
    if (fork() == 0)
    {
        dup2(w[0], STDIN_FILENO);
        dup2(r[1], STDOUT_FILENO);
        while (1)
        {
            ssize_t num;
            char buf[2753];
            num = read(STDIN_FILENO, buf, 2753);
            /* Some time consuming procedure */
            // sleep(1);
            write(STDOUT_FILENO, buf, num);
        }
    }
    else
    {
        char buf[32768] = { 0 };
        struct pollfd pfd[] = {{w[1], POLLOUT, 0}, {r[0], POLLIN, 0}};
        while (poll(pfd, 2, 1000) >= 0)
        {
            if (pfd[0].revents == POLLOUT)
            {
                write(w[1], buf, PIPE_BUF);
                printf("Write %d Bytes\n", PIPE_BUF);
            }
            else if (pfd[1].revents == POLLIN)
            {
                ssize_t num = read(r[0], buf, 32768);
                printf("Read %ld Bytes\n", num);
            }
        }
    }
}
```

Here are the things that cause the problem.

1. The subprocess will read byte that cannot be factored by PIPE_BUF.
2. The main program will only process only one of the pipes in one loop (the if ... else if ... clause).

But those are exactly what ghostscript and python subprocess module will do. So for simplicity, I patched the subprocess module and changed the "else if" clause to another "if" clause, and that seems to solve my problem (just practically).

As for the WSL2, I have done some study on it. It's an amazing idea but I think I wouldn't switch to it until it has a more stable release. I'm not sure about your future plan about WSL1, but I still hope you can have a fix since it indeed has the potential to cause a deadlock.

**Comment by therealkenc** [comment]
```
while (poll(pfd, 2, 1000) >= 0)
```

Doesn't that crazy spin? [n.b. haven't actually tried.]  When I looked last month, `poll(2)` returned right away regardless. If testing `revents` works, that's a good enough work around, nice work (desperate measures for desperate times). But if I'm reading that right (I might not) you might want to stick a small sleep in there if `poll()` returned on a false positive.

> but I still hope you can have a fix since it indeed has the potential to cause a deadlock.

What remains weird about this one is there aren't more fail examples. I mean, it's a pretty bog-standard pattern. I don't have any special insight on what will and what won't be addressed in WSL1, but short of 50 thumbs-up votes (made-up number) on this issue, you can probably make an educated guess.
