### ISSUE TITLE
WSL 1 crashes each time internet connection is lost

### ISSUE THREAD

**Issue by kskalski** [microsoft/WSL#4526]
* Your Windows build number:  
  Microsoft Windows [Version 10.0.18980.1]

* What you're doing and what's happening:  
 open up Ubunut WSL 1 terminal
 disable Wifi (also happens when I close / hibernate my laptop for longer time)
 see terminal crash

* What's wrong / what should be happening instead:
  WSL should not crash. The crash also takes down background processes running there (I have ssh-agent activated)

* Strace of the failing command, if applicable:  
 the whole terminal and WSL instance crashes, so can't strace any specific program

* For WSL launch issues, please [collect detailed logs]
 [lxcore_service.zip](https://github.com/microsoft/WSL/files/3631842/lxcore_service.zip)

**Comment by kskalski** [comment]
Same with 
Microsoft Windows [Version 10.0.18985.1]

When I start ubuntu.exe from cmd it leaves a message upon crash, but it's not very descriptive:

nazgul@narsil:~$ The Windows Subsystem for Linux instance has terminated.

**Comment by kskalski** [comment]
Ah, I guess this might be related to https://github.com/microsoft/WSL/issues/4474 since when I try to start ubuntu.exe from cmd.exe *without* working internet connection, then I also see error about remove procedure call failed

**Comment by craigloewen-msft** [comment]
I'll mark this as duplicate to #4474 to help simplify things. If you're still running into this issue after a fix for #4474 is out please feel free to reopen this!
