### ISSUE TITLE
[WSL 2] LAN hosts can't reach ports listened on 0.0.0.0 in WSL 2 while Windows can

### ISSUE THREAD

**Issue by Menci** [microsoft/WSL#4527]
**Please fill out the below information:**
* Your Windows build number:  `Microsoft Windows [Version 10.0.18970.1005]`

* What you're doing and what's happening: Start OpenSSH in WSL 2 (while Windows's OpenSSH is stopped), execute `ssh 127.0.0.1` on Windows and `ssh [ip_of_windows]` in LAN.

* What's wrong / what should be happening instead: Windows can access OpenSSH in WSL 2 while LAN hosts can't.

The same issue doesn't exists on WSL 1. Windows Firewall is FULLY turned-off. The most strange thing is, since WSL 2's port could be forwarded to Windows's 127.0.0.1, why NOT listening on 0.0.0.0 on Windows?

**Comment by therealkenc** [comment]
Confirmed. I had done this at one point this summer (could swear, anyway), but I am not able to ping WSL's gateway address from the outside right now on 18980. For me that is gateway address is (for example) `172.30.48.1` (today). I don't _remember_ doing anything special at the time, but that doesn't mean I didn't. 

Unfortunately I haven't actually accessed WSL from the "outside" in months; nearly all my WSL access is local to the machine. Could use come guidance here before finding a `netsh` work-around that does more damage than good. Did this ever work?

**Comment by timesnewmen** [comment]
Check here.
[#4150](https://github.com/microsoft/WSL/issues/4150)

**Comment by Menci** [comment]
```

**Comment by Menci** [comment]
```

**Comment by Menci** [comment]
```
C:\Users\Menci>tasklist | findstr wslhost
wslhost.exe                  12868 Console                    1      7,164 K
wslhost.exe                   5816 Console                    1      7,676 K
wslhost.exe                   9684 Console                    1      5,972 K

C:\Users\Menci>netstat -aon | findstr 12868
  TCP    127.0.0.1:22           0.0.0.0:0              LISTENING       12868
  TCP    127.0.0.1:22           127.0.0.1:53093        ESTABLISHED     12868
  TCP    127.0.0.1:80           0.0.0.0:0              LISTENING       12868
  TCP    127.0.0.1:1180         0.0.0.0:0              LISTENING       12868
  TCP    127.0.0.1:1935         0.0.0.0:0              LISTENING       12868
  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING       12868
  TCP    [::1]:22               [::]:0                 LISTENING       12868
  TCP    [::1]:80               [::]:0                 LISTENING       12868
  TCP    [::1]:1180             [::]:0                 LISTENING       12868

C:\Users\Menci>
```

With `netstat` we can see `wslhost.exe`, the process to forward network connections between Windows and WSL 2, is listening only on `127.0.0.1`. So this may NOT be solved without a patch to `wslhost.exe` (or related libraries).

Inspired by @edwindijas's idea in @timesnewmen's link, a possible (and usable) workaround is a program which watches WSL's listening ports and changes `netsh` rules to forward them.

**Comment by therealkenc** [comment]
Thanks @timesnewmen. Let's use #4150 as the LZ.

**Comment by qingliangcn** [comment]
try this https://github.com/CzBiX/WSLHostPatcher
