### ISSUE TITLE
WSL mnt/drives are empty

### ISSUE THREAD

**Issue by webdevisme** [microsoft/WSL#4529]
Windows build number:  Version 10.0.18362.356

Hi.

`ls /mnt/d -al`

returns

`total 0
drwxrwxrwx 1 root root 4096 Oct 16  2018 .                                                                              drwxr-xr-x 1 root root 4096 Oct 16  2018 ..`

(D is NTFS and a fixed drive)

This only just started happening, the only thing I've done which springs to mind is trying to install ubuntu as dual boot (which failed).

Any ideas?

**Comment by benhillis** [comment]
What is the output of the "mount" command? Any errors in dmesg?

**Comment by webdevisme** [comment]
Hi Ben,

```
rootfs on / type lxfs (rw,noatime)                                                                                      none on /dev type tmpfs (rw,noatime,mode=755)                                                                           sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)                                                               proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)                                                                devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)                                                none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)                                                             none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)                                                           none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)                                                                   none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)                                                  binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)                                                  cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)                                                              cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
```

**Comment by benhillis** [comment]
Are there any errors in dmesg?

**Comment by webdevisme** [comment]
Hi Ben, sorry, I missed the dmesg part of your instructions:

`[    0.017817]  Microsoft 4.4.0-18362.1-Microsoft 4.4.35                                                                                                   [    0.493461] <3>init: (1) ERROR: UtilCreateProcessAndWait:360: /bin/mount failed with status 0                                                           [    0.493471] 2000                                                                                                                                        [    0.516849] <3>init: (1) ERROR: UtilCreateProcessAndWait:360: /bin/mount failed with status 0                                                           [    0.516859] 2000                                                                                                                                        [    0.531148] <3>init: (1) ERROR: UtilCreateProcessAndWait:360: /bin/mount failed with status 0                                                           [    0.531156] 2000                                                                                                                                        [    0.531440] <3>init: (1) ERROR: LogException:23: FS: Could not start file system server. Operation not permitted @.\plan9.cpp:33 (TranslatePath)                                                                                                                                                                   [    0.581722] <3>init: (5) ERROR: UtilTranslatePathList:2154: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Commo                                                                                                                                                                              [    0.581784] <3>init: (5) ERROR: UtilTranslatePathList:2154: Failed to translate C:\WINDOWS\system3                                                                                                                                                                                                                 [    0.581864] init: (5) ERROR: UtilTranslatePathList:2154: Failed to translate C:\WINDOWS   `

**Comment by benhillis** [comment]
Mounting your drives is failing, can you take a trace?

https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs
