### ISSUE TITLE
Couldn't import wsl2 distribution

### ISSUE THREAD

**Issue by sdv22** [microsoft/WSL#4530]
D:\wsl>wsl --import Ubuntu U:\wsl2\Ubuntu sdvhome_wsl2_2.tar --version 2
The specified network name is no longer available.

Process allocating all of the available memory and terminates with the error.

tar size is ~360 GB.

Windows version is 18985.

**Comment by WahrMethode** [comment]
Same problem here. Tar size is ~10GB. Windows Version is 18985.1.

**Comment by Biswa96** [comment]
If tar size is that much why don't use a dual booted Linux distribution?

**Comment by sdv22** [comment]
> 
> 
> If tar size is that much why don't use a dual booted Linux distribution?

Because Win is my primary platform. I'm using MS tools even for Linux/Android development.

**Comment by sdv22** [comment]
Workaround:
1. Import tar as WSL1
2. Comress some data to reduce the size to be less than 256GB
3. Convert distrubution to wsl2.

But anyway, it's a crutch.
My primary wsl distribution is ~700 GB. (several Android trees).

**Comment by SuperLamic** [comment]
@sdv22 how can you compile android with https://github.com/microsoft/WSL/issues/4166 ? I had my RAM (16 GB) full after like 10 minutes even with repo sync.

**Comment by sdv22** [comment]
1. Use nocache
2. Limit amount of memory available for vm with .wslconfig

**Comment by RevCBH** [comment]
This also fails for me with a ~22 GB tar backup.
