### ISSUE TITLE
Soft links on Linux ext2/3/4 partition not recognized by WSL

### ISSUE THREAD

**Issue by xuancong84** [microsoft/WSL#4531]
Currently, WSL does not recognize existing ext2/3/4 partitions on any device. It will be cool to have this feature incorporated into WSL kernel so that on a dual boot system, Windows can access Linux partitions directly via WSL.

Therefore, currently, I have to use ext2fsd (https://github.com/matt-wu/Ext3Fsd/) for Windows to see ext2/3/4 partitions. However, there is a problem. For Windows file explorer (i.e., explorer.exe), the soft-linked files are displayed properly and can be accessed.
![image](https://user-images.githubusercontent.com/10172392/65372233-def4b280-dc9f-11e9-81b8-a542e9f3c6a2.png)
However, for Windows subsystem for Linux (WSL), all soft-linked files cannot be accessed nor read at all.
![image](https://user-images.githubusercontent.com/10172392/65372308-d2bd2500-dca0-11e9-9796-4b6d8c3ce9bd.png)
As a consequence, I have to reinstall all packages in anaconda again, wasting much more disk space.

In fact, I found that it is possible to run Linux binary executable on native ext2/3/4 Linux system partition using the /lib64/ld-linux-x86-64.so.2 trick. However, the soft-link issue causes most of the .so library files fail to load.
![image](https://user-images.githubusercontent.com/10172392/65372449-157ffc80-dca3-11e9-9134-17f73b3eab1e.png)

By implementing this feature, most of the programs can be run in both WSL and native Linux.

**Comment by therealkenc** [comment]
Core ask for block device support is dupe #689.

Ext3Fsd LZ is #579. It should be possible in principle _for Ext3Fsd_ (sic) to provide the correct information to make symbolic links work in WSL. It would take some debugging in Ext3Fsd to look at the queries being made on the Windows side of 9p, what is being returned, and how it differs from NTFS behavior.
