### ISSUE TITLE
Ctrl + F not working

### ISSUE THREAD

**Issue by SiqingYu** [microsoft/WSL#4532]
**Please fill out the below information:**
* Your Windows build number:  10.0.18362.356

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I can open the find box by right-clicking the title bar and select from the menu. But I can't open it with Ctrl + F shortcut.
![image](https://user-images.githubusercontent.com/22290018/65384136-21c29300-dd51-11e9-8fbf-2aa42ebdb579.png)
![image](https://user-images.githubusercontent.com/22290018/65384179-8978de00-dd51-11e9-93e9-4c4d382714f5.png)

My `/etc/inputrc` is the default.
```
# /etc/inputrc - global inputrc for libreadline
# See readline(3readline) and `info rluserman' for more information.

# Be 8 bit clean.
set input-meta on
set output-meta on

# To allow the use of 8bit-characters like the german umlauts, uncomment
# the line below. However this makes the meta key not work as a meta key,
# which is annoying to those which don't need to type in 8-bit characters.

# set convert-meta off

# try to enable the application keypad when it is called.  Some systems
# need this to enable the arrow keys.
# set enable-keypad on

# see /usr/share/doc/bash/inputrc.arrows for other codes of arrow keys

# do not bell on tab-completion
# set bell-style none
# set bell-style visible

# some defaults / modifications for the emacs mode
$if mode=emacs

# allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line

# allow the use of the Delete/Insert keys
"\e[3~": delete-char
"\e[2~": quoted-insert

# mappings for "page up" and "page down" to step to the beginning/end
# of the history
# "\e[5~": beginning-of-history
# "\e[6~": end-of-history

# alternate mappings for "page up" and "page down" to search the history
# "\e[5~": history-search-backward
# "\e[6~": history-search-forward

# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word

$if term=rxvt
"\e[7~": beginning-of-line
"\e[8~": end-of-line
"\eOc": forward-word
"\eOd": backward-word
$endif

# for non RH/Debian xterm, can't hurt for RH/Debian xterm
# "\eOH": beginning-of-line
# "\eOF": end-of-line

# for freebsd console
# "\e[H": beginning-of-line
# "\e[F": end-of-line

$endif
```

**Comment by therealkenc** [comment]
[console](https://github.com/microsoft/terminal)

**Comment by craigloewen-msft** [comment]
Adding some more context:

Some Terminal applications run in 'processed' mode. Like CMD or PowerShell. This is where the Windows Console intercepts key commands (Like CTRL+F or CTRL+V for paste, etc.) and does actions with them. 

However, WSL runs in 'raw' mode, where the console does not intercept any commands, and passes them all to the shell. So in this case it's not intercepting your CTRL+F keystroke, and is instead passing that straight to the application you're running for it to be interpreted there. 

Echoing @therealkenc this is a console based issue, I'd urge you to try the new Windows Terminal as that's where much of the console's team's efforts is going into to improving the Windows command line experience.
