### ISSUE TITLE
latest fast track, wsl 2 ubuntu app crashing. Working in powershell

### ISSUE THREAD

**Issue by adam-hanna** [microsoft/WSL#4533]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```bash
# cmd
C:\WINDOWS\system32>ver

Microsoft Windows [Version 10.0.18985.1]

# powershell
PS C:\WINDOWS\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18985  0
```

In the lower right corner of the screen, it reads `Windows 10 Pro; build 18985.vb_release.190913-1426`

I just recently installed windows updates last night and this began happening this morning.

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Opening wsl2 from powershell is working. I.e. all of the following commands, when run from powershell, running as admin, are working: wsl, ubuntu, bash.

However, running the Ubuntu app is crashing. Please see the attached image.
![ubuntu-crash](https://user-images.githubusercontent.com/5436950/65395936-e5456600-dd55-11e9-9656-42a67c06482e.gif)

* What's wrong / what should be happening instead:

I expect ubuntu app to work.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

How to run command? I can't find the exe?

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Attached.

[lxcore_kernel.zip](https://github.com/microsoft/WSL/files/3640280/lxcore_kernel.zip)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by adam-hanna** [comment]
Scratch that, I found it in `C:\Users\ahann\AppData\Local\Microsoft\WindowsApps\ubuntu.exe`

Running directly from there is working.

**Comment by L1ghtman2k** [comment]
This is still a problem in the sense that a regular Ubuntu terminal crashes, so this issue should probably be re-opened

**Comment by adam-hanna** [comment]
Ok, I'm now having worse issues. WSL hangs no matter how I open it. I was using it this morning to work on a few software projects. I shut the computer down (it didn't update to my knowledge). I turned the computer back on tonight and it's not working.

When running wsl, ubuntu or bash it just hangs (from powershell). There's no output and I can't even ctrl+c to stop.

Attached are the logs.

**Comment by adam-hanna** [comment]
aaaannnnndddddddd...... three restarts later and its working. Not one, not two, three was the magic number. :)

[somewhat] [relevant xkcd](https://xkcd.com/1495/)
