### ISSUE TITLE
can't access localhost:8000 webpack server presented from WSL Ubuntu

### ISSUE THREAD

**Issue by psaleh** [microsoft/WSL#4535]
* Your Windows build number:  Microsoft Windows [Version 10.0.18956.1000]

* What you're doing and what's happening:  I'm running gatsbyJS within Ubuntu WSL. However, I can't view the webpage that I'm working on via localhost:8000 as would be expected.

* What's wrong / what should be happening instead: I should be able to see the website, but all I'm getting on the browser is "This site can't be reached, localhost refused to connect"

![image](https://user-images.githubusercontent.com/6106543/65403990-35c9cb80-de09-11e9-8a5f-268add54db04.png)

![image](https://user-images.githubusercontent.com/6106543/65403996-40846080-de09-11e9-8a04-a04c7a86d7cd.png)

**Comment by archilkarchava** [comment]
Gatsby binds to localhost by default, you have to bind it to 0.0.0.0.
Change `gatsby develop` to `gatsby develop -h 0.0.0.0` in your package.json

**Comment by craigloewen-msft** [comment]
@archilkarchava is correct. This behavior has been fixed in build 18970, so if you upgrade to that build or higher you'll be able to connect without having to change which IP address you bind to. I'll close this issue out as resolved, if you are still experiencing issues after upgrading to 18970 or higher please reopen! Thanks.

**Comment by archilkarchava** [comment]
@craigloewen-msft This behavior hasn't been fixed. I still have to do `gatsby develop -h 0.0.0.0` to access my website in windows on `build 18980.1`

**Comment by craigloewen-msft** [comment]
@archilkarchava , this should be fixed. Could you open up a new issue describing your problem? If you can link to the project you're using so we can try and run it locally that would help us a lot! Thanks :)
