### ISSUE TITLE
WSL 2: wsl --shutdown accepts extra cmdline arguments

### ISSUE THREAD

**Issue by swarren** [microsoft/WSL#4539]
`wsl --shutdown` is the entire legal command according to `wsl --help`. However, if I actually type `wsl --shutdown Ubuntu` (i.e. when I get confused about which of `--shutdown` and `--terminate` is which), no error is issued. There should be an error, because `Ubuntu` is not an expected parameter to `--shutdown`.

Put another way. Actual behaviour:

```
c:\> wsl --shutdown foo
c:\> 
```

Expected behaviour:

```
c:\> wsl --shutdown foo
Error: Unknown argument "foo"
c:\> 
```

(No doubt this is happening because other cmdline options in wsl allow launching an arbitrary command within the WSL VM. However, --shutdown doesn't allow this, so shouldn't accept the meaningless/unused command argument.)

Windows build number: 10.0.18985.1

**Comment by therealkenc** [comment]
> so shouldn't accept the meaningless/unused command argument

That's pretty normal

```
$ gcc --version foo
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

No error on superfluous `foo` argument.

**Comment by swarren** [comment]
I think the fact gcc has the same issue doesn't mean it isn't a bug. Admittedly, `--version` and `--help` often do have this quirk, but it's rare for other options in my experience.

**Comment by Biswa96** [comment]
`shutdown` option does not accept any argument. It kills all running Lx session. Try that option with running WSL1 and WSL2 distribution simultaneously.
