### ISSUE TITLE
Access windows git project with wsl git is too slow

### ISSUE THREAD

**Issue by hwdef** [microsoft/WSL#4540]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.18970.1005

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Access windows git project with wsl git 

* What's wrong / what should be happening instead:

![图片](https://user-images.githubusercontent.com/13084946/65490314-83186c80-dedf-11e9-95e6-5265f2cd9728.png)

When I access Kubernetes project , I wait 5 Minutes.Because my zsh theme will loading git info when I access a git project.
When I use `git status` ,it is also very slow.

**Comment by Biswa96** [comment]
Duplicate of this issue https://github.com/microsoft/WSL/issues/4197. Please subscribe to that issue for future updates and info.

**Comment by hwdef** [comment]
@Biswa96 
If i use wsl1,it is also very slow.

**Comment by Biswa96** [comment]
The tech behind accessing Windows partitions in WSL is same in WSL1 or in WSL2.

**Comment by hwdef** [comment]
@Biswa96 
All right,I hope it can be fixed.
Thank you!
