### ISSUE TITLE
Exec format error with .o files

### ISSUE THREAD

**Issue by reeved** [microsoft/WSL#4541]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.356]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I'm using WSL to compile and run some C++ files. I've got a makefile and I'm using ./FileName.o to run them

* What's wrong / what should be happening instead:

The file should run but I'm getting the following error message:

> bash: ./main.o: cannot execute binary file: Exec format error

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

```
222   execve("./main.o", ["./main.o"], 0x7fffd53c5118 /* 25 vars */) = -1 ENOEXEC (Exec format error)

222   write(2, "strace: exec: Exec format error\n", 32) = 32

222   getpid()                          = 222

222   exit_group(1)                     = ?

222   +++ exited with 1 +++
```

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by DHowett-MSFT** [comment]
You're not supposed to run `.o` files. They're intermediate objects that need to be linked into a final binary.
