### ISSUE TITLE
When will WSL 2 get officially released?

### ISSUE THREAD

**Issue by LubomirGeorgiev** [microsoft/WSL#4542]
When will WSL 2 get officially released?

**Comment by craigloewen-msft** [comment]
WSL 2 will be released in the first half of 2020! You'll see more details posted on the [command line blog](https://aka.ms/cliblog) or on [Twitter by WSL team members](https://twitter.com/craigaloewen/lists/wsl-team-members).

**Comment by detro** [comment]
Any update about this?
Really feels long overdue folks!
We are so ready for this!

**Comment by luizmiguelsl** [comment]
Can't wait for the official release :-)

**Comment by AlexanderWanitschke** [comment]
Any update on a tentative release date? First half of 2020 is here. :)

**Comment by jeffleo** [comment]
According to this [Microsoft dev blog ](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/) from March 13th 2020, "WSL2 will soon be officially available as part of Windows 10, version 2004". Based on the Windows 10 major update release cycle and other blogs, Version 2004 was estimated to arrive sometime in May 2020.

**Comment by michaelkarlcoleman** [comment]
I was hoping that this would be out in the release pushed to me today, but sadly not.  :-(

**Comment by geerlingguy** [comment]
For anyone like me who is confused as to why their Windows Update is _still_ not showing the update as available, you can go to the [Windows Update Assistant](https://www.microsoft.com/software-download/windows10) page and download the tool, or in my case there was a button that I could click for an exe file that kicked off the 2004 update automatically.

**Comment by LubomirGeorgiev** [comment]
> For anyone like me who is confused as to why their Windows Update is _still_ not showing the update as available, you can go to the [Windows Update Assistant](https://www.microsoft.com/software-download/windows10) page and download the tool, or in my case there was a button that I could click for an exe file that kicked off the 2004 update automatically.

Where can I find this button for the exe file?

**Comment by jayliu50** [comment]
@geerlingguy holy smokes, thank you so much!
@LubomirGeorgiev The link for the button is https://go.microsoft.com/fwlink/?LinkID=799445
