### ISSUE TITLE
Can not install any distribution by wsl2

### ISSUE THREAD

**Issue by hipudding** [microsoft/WSL#4543]
![20190925-090820(eSpace)](https://user-images.githubusercontent.com/3837401/65561159-0aafbb00-df74-11e9-8fbd-760820dc0df7.png)
I update to BUILD 18970 a few days before. I choose to keep my programs and data.
Then I follow the offcial guide to turn on WSL2, when installing any distribution(ubuntu 18.04,16.04 and centos), when start Ubuntu(Centos) a few mins later, it shows this problem.
I cannot get any infomation about this problem. Please help me. THX

**Comment by benhillis** [comment]
Interesting, is the Virtual Machine Platform feature available?  Are there any interesting events in any of the Hyper-V eventvwr log?
