### ISSUE TITLE
WSL2: dmidecode missing /dev/mem -> /sys/firmware/dmi/tables/smbios_entry_point No such file or directory

### ISSUE THREAD

**Issue by MrRedHead** [microsoft/WSL#4545]
Your Windows build number:  Microsoft Windows [Version 10.0.18362.356]
WSL: SUSE Linux Enterprise Server 12 SP2 

* What you're doing and what's happening:
Trying to register with SUSEConnect, with SUSE_registration_code replaced with actual registration code.

sudo SUSEConnect -r SUSE_registration_code
root's password:
command 'dmidecode -s system-uuid' failed
Error: SCC returned 'Unknown Registration Code.' (401)

When running dmidecode:
sudo dmidecode -s system-uuid
/dev/mem: No such file or directory

* What's wrong / what should be happening instead:
SUSEConnect uses dmidecode, which fails
dmidecode -s system-uuid should give some usefull data

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

sudo strace dmidecode -s system-uuid
execve("/usr/sbin/dmidecode", ["dmidecode", "-s", "system-uuid"], [/* 14 vars */]) = 0
brk(0)                                  = 0x1cb2000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2280d20000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=19301, ...}) = 0
mmap(NULL, 19301, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2280d23000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\10\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1925032, ...}) = 0
mmap(NULL, 3811776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2280650000
mprotect(0x7f22807e9000, 2097152, PROT_NONE) = 0
mmap(0x7f22809e9000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x199000) = 0x7f22809e9000
mmap(0x7f22809ef000, 14784, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f22809ef000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2280d10000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2280d00000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2280cf0000
arch_prctl(ARCH_SET_FS, 0x7f2280d00700) = 0
mprotect(0x7f22809e9000, 16384, PROT_READ) = 0
mprotect(0x612000, 4096, PROT_READ)     = 0
mprotect(0x7f2280c20000, 4096, PROT_READ) = 0
munmap(0x7f2280d23000, 19301)           = 0
open("/sys/firmware/dmi/tables/smbios_entry_point", O_RDONLY) = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x1cb2000
brk(0x1cd3000)                          = 0x1cd3000
open("/sys/firmware/efi/systab", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/proc/efi/systab", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("/dev/mem", O_RDONLY)              = -1 ENOENT (No such file or directory)
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fstat(3, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig icanon echo ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2280ce0000
write(3, "/dev/mem: No such file or direct"..., 36/dev/mem: No such file or directory
) = 36
close(3)                                = 0
munmap(0x7f2280ce0000, 4096)            = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by benhillis** [comment]
zcat /proc/config.gz | grep -i devmem
# CONFIG_DEVMEM is not set

Potentially something we should look at adding to the kernel config.

**Comment by MrRedHead** [comment]
Without the possibility to add a regcode it isn't possible to update or add repositories.
Is there another way to register? Or please fix the bug.

**Comment by MrRedHead** [comment]
Alternate way of register:

This is possible either with the YaST2 Registration Module or with the SUSEConnect tool.

* With YaST2
Do the following:
yast -> software
  -> Add-on Products
     -> Add
       -> Extensions and Modules from Registration Server... 

enter registration details

**Comment by iadgovuser29** [comment]
That would be very useful.

**Comment by benhillis** [comment]
I'm adding the config option, thanks for posting the issue.

**Comment by SteveIves** [comment]
> I'm adding the config option, thanks for posting the issue.

What hapenned? Sounded like this was going to get addressed, but it's still an issue in released WSL2?

**Comment by ssssshql** [comment]
![image](https://github.com/user-attachments/assets/de40ae49-efc8-4dfd-b6e1-7a2ffd8ec48f)
