### ISSUE TITLE
Linux VM crashes during rsync copy into VM

### ISSUE THREAD

**Issue by zot** [microsoft/WSL#4549]
**Please fill out the below information:**
* Your Windows build number: `Microsoft Windows [Version 10.0.18990.1]`

* What you're doing and what's happening: 

Copying a 40G directory with 15K files from another VM running in Hyper-V. The other VM doesn't crash. The WSL 2 Linux VM crashes every time I rsync this directory.

I did successfully rsync a 14G directory with 347K files and a 5G directory with 55K files.

Here's the command I used to copy the files: 
`rsync -czaP 10.0.1.5:/old/home/bill/Downloads/ downloads/`

* What's wrong / what should be happening instead:

Linux VM crashes

* Strace of the failing command, if applicable:

cmd: `rsync -czaP 10.0.1.5:/old/home/bill/Downloads/ downloads/`

strace -ff output: [rsync-strace.txt](https://github.com/microsoft/WSL/files/3664419/rsync-strace.txt)

**Comment by zot** [comment]
Hmm, looking at my resource graphs, it looks like I ran out of ram and it's running a lot longer without -c. I'm guessing running out of memory is the problem here.

**Comment by craigloewen-msft** [comment]
We're tracking the behaviour that the WSL 2 VM does not return memory, and have a fix for it in the works! Issue https://github.com/microsoft/WSL/issues/4166 is our landing zone for this. I'd recommend following that thread for updates. If that solves your issue let me know and I can mark this as duplicate and close out the issue. Thanks!

**Comment by zot** [comment]
Thanks! I made <HOME>/.wslconfig and it does limit the VM's ram consumption. That solves my issue!

**Comment by luciorq** [comment]
If you are limiting the amount of RAM in the VM maybe is a good thing to increase swap amount.
