### ISSUE TITLE
Can't able to install ubuntu 18.04  in Microsoft Windows [Version 10.0.18990.1] build

### ISSUE THREAD

**Issue by nandhanandy92** [microsoft/WSL#4551]
2. Microsoft Windows [Version 10.0.18990.1] 

3. just install install ubuntu from store and launch

4. RPC server not available

5.should install nessesary files and ask to set a unix user name and password.

7. Additional information
	i.currently docker is running in backgroud 
	ii.wsl default version is set to 2.

**Comment by craigloewen-msft** [comment]
Hi @nandhanandy92 can you take some networking logs for us (instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs)) and then link us to your feedback item so we can get a detailed look at what's going on? Thank you!

**Comment by nandhanandy92** [comment]
Hi @craigloewen-msft  Thank you for your time to reply to my issue my issue seems to be very similar to the issue no: #4474 . [https://github.com/microsoft/WSL/issues/4474](url)
and it seems fix is on bound with upcoming insider builds.
