### ISSUE TITLE
sed creates empty read-only files when trying to replace on external drives

### ISSUE THREAD

**Issue by bpsib** [microsoft/WSL#4553]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18362.356

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Insert an external drive such as a USB stick and mount it. E.g. `sudo mount -t drvfs F: /mnt/f`
```
cd /mnt/f
echo foo > test.txt
sed -i s/foo/bar/g test.txt
```

* What's wrong / what should be happening instead:
`sed: couldn't open temporary file ./sedvb7177: Permission denied`
Text should get replaced but doesn't because of the permission denied error. I then find it created an empty file "sedvb7177" and is marked as read-only. I have also tried running it from sudo but it makes no difference. This might be a regression as I think it worked with 1803/1809 if I recall correctly. The weird thing is works fine on the C: drive. It's just external drives (I tried it with both FAT32 and NTFS formatted ones).

P.S. Temp file name is different each time. The above file name is an example.

* Strace of the failing command, if applicable: 
[sed.strace](https://gist.github.com/bpsib/4d2bc3dc01acb99a467a6f10250dd990)

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
> If some_command is failing, then run strace -o some_command.strace -f some_command some_args, and link the contents of some_command.strace in a gist here

I think I have a wild ass guess but would need the trace to know.

**Comment by bpsib** [comment]
> 
> 
> > If some_command is failing, then run strace -o some_command.strace -f some_command some_args, and link the contents of some_command.strace in a gist here
> 
> I think I have a wild ass guess but would need the trace to know.

I have added [sed.strace](https://gist.github.com/bpsib/4d2bc3dc01acb99a467a6f10250dd990) to a gist.

**Comment by therealkenc** [comment]
```
1611  fstat(3, {st_mode=S_IFREG|0777, st_size=5, ...}) = 0
1611  umask(0700)                       = 000
1611  gettimeofday({tv_sec=1569795902, tv_usec=671563}, NULL) = 0
1611  getpid()                          = 1611
1611  openat(AT_FDCWD, "./sedqFyZ8l", O_RDWR|O_CREAT|O_EXCL, 0600) = -1 EACCES (Permission denied)
1611  umask(000)                        = 0700
```

Thanks! Nothing in there to support my early guess, unfortunately. That we have a trace is still useful.

One thing you might try is toy around with the `mount` options. That is the only variant between your external drive, and your automounted `C:\`. Or the only variant you have control over on the WSL side, anyway. For me, `C:\` looks like:
```
$ mount | grep 'C:\\'
C:\ on /mnt/c type drvfs (rw,noatime,uid=0,gid=0,case=off)
```

Try mounting your `F:\` with the same:
```
$ sudo mount -t drvfs -o "rw,noatime,uid=0,gid=0,case=off" F: /mnt/f
```

The other thing to do would be create a subdirectory on your stick, and then look at that directory with Windows Explorer File Properties for differences in _Windows_ permissions. Your observation "The weird thing is works fine on the C:" is a great data point, but "on the C: drive" is sensitive to folder permissions where you are performing the `sed`.

Needless to say the UX is sub-optimal whatever the cause. Just trying to ascertain what might be causing the `EACCES`.

**Comment by bpsib** [comment]
I have now got it working on my NTFS formated external drive. But still get permission denied on FAT32 and extFAT drives.

**Comment by therealkenc** [comment]
> I have now got it working on my NTFS formated external drive

How

> But still get permission denied on FAT32 and extFAT drives.

That would not surprise me too much, given that `openat()` is going out of it's way to try to set the file mode, and metadata is not supported on FAT32. It is hard to tell whether trying `sed(1)` on FAT32 is something no one ever tried, or whether `openat(....., 0600)` worked at some point in the past but no longer does. I take as a given here that bog standard scenarios like `cat hello > ./hello.txt` or `touch ./foo" works okay for you on a FAT32 mount. [n.b. I have no tried any of this; never mounted a FAT32 under WSL myself.]

**Comment by stefanloerwald** [comment]
I'm running into issues with `sed -i foo` too. The error message points towards the issue of "preserving permissions for <sedtmpfile>: Operation not permitted", but the end result is that the file `foo` is left as read-only.

Not sure what I can do to help solve this issue, so please let me know what further info you need.

Thanks
Stefan

**Comment by therealkenc** [comment]
> Not sure what I can do to help solve this issue, so please let me know what further info you need.

If your scenario is FAT32 also then mostly a like on the OP (which this issue currently is suffering).

**Comment by stefanloerwald** [comment]
I'm experiencing this on NTFS, so not FAT32.

**Comment by stefanloerwald** [comment]
So to reproduce:

On an NTFS drive perform the following operations using WSL (Ubuntu 18.04):

1. `echo "Hello" > tmp`
2. `cat tmp`
> Hello
3. `sed 's/ello/i/' tmp`
> Hi
4. `sed -i 's/ello/i/' tmp`
> `sed: preserving permissions for ‘./sedOcla1z’: Operation not permitted`
5. `cat tmp`
> Hi
6. `sed -i 's/i/ello/' tmp`
> sed: preserving permissions for ‘./sedTx3bu6’: Operation not permitted
> sed: cannot rename ./sedTx3bu6: Permission denied
7. `cat tmp`
> Hi

So the operation works, has some trouble with its temporary file, and leaves the file in a read-only state.

**Comment by therealkenc** [comment]
Probably just missing metadata your on the mounts. Turn on metadata in [/etc/wsl.conf](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/#configuration-options). Something like:
```
[automount]
options = "metadata"
```

You'll need a `wsl --shutdown` for it to take.

**Comment by stefanloerwald** [comment]
I only have one drive on that computer, so shouldn't that be covered by the default config?

**Comment by therealkenc** [comment]
No. And you have buried the OP, which was a FAT32 filesystem on a USB stick.
