### ISSUE TITLE
Let me keep my home directory (and others) in a VHDX so I can upgrade and switch Linux versions without fear

### ISSUE THREAD

**Issue by zot** [microsoft/WSL#4556]
This is a feature request. I [posted ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash?query=Let%20me%20keep%20my%20own%20files%20in%20a%20separate%20VHDX%20so%20I%20can%20upgrade%20and%20switch%20Linux%20versions%20without%20fear) on in the User Voice forum but that forum was apparently just closed.

I'd like to be able to attach VHDX files as drives to the WSL 2 VM so I can keep my own stuff separate from the stock image. That way I can upgrade and switch versions without having to transfer files between images, etc. Also, I'd like to be able to keep my docker repository in another VHDX for the same reason. I'm sure there are plenty of other reasons [people want to attach VHDXs to the WSL 2 VM](https://www.reddit.com/r/bashonubuntuonwindows/comments/cwrrog/how_to_attach_additional_vhdx_to_wsl2s_vm/).

**Comment by Biswa96** [comment]
Did you try to mount a Windows side folder as `/home` folder with proper flags or permissions?

**Comment by zot** [comment]
> Did you try to mount a Windows side folder as `/home` folder with proper flags or permissions?

@Biswa96, I'd like these to be Linux file systems for speed and behavior. At this point, my home directory is a sparse, loop-mounted file from inside the WSL Linux file system. Less than ideal but it's way faster to use than loop mounting a file from Windows through 9p and I can easily (slowly) back it up with tar -S.

**Comment by ajw107** [comment]
I just replied to a similar issue with a method on how to mount vhdx disk here:
[https://github.com/microsoft/WSL/issues/4574#issuecomment-538668112](https://github.com/microsoft/WSL/issues/4574#issuecomment-538668112)

**Comment by zot** [comment]
Thanks but I'm pretty sure your method mounts over 9p since it uses a file from /mnt/c, so I don't want to use it for the same reason I gave above.

**Comment by therealkenc** [comment]
Another use-case appears to be segregating files onto a different physical disk/partition (f.e. `D:`) without paying a 9p price to do it, ref #4574.

**Comment by starwing** [comment]
I just want to attach another vhdx file because a MySQL docker expect ext4 for data storage... Without this I can use docker desktop, and had to use docker in Hyper-V VM for now T_T

**Comment by Biswa96** [comment]
How about using a IMG file? I have created it with `qemu-img` -> `fdisk` -> `mkfs.ext4`.

**Comment by starwing** [comment]
@Biswa96 thanks for the hint! I'll try this later, but the issue is I cannot move data from existing data from current seprate vhdx for mysql container :(

**Comment by sarim** [comment]
Another hyper-v feature hidden in wsl2 :( 

A option to set additional drives via `/etc/wsl.conf`  would be super cool.
something like `d:/images/xxxx.vhdk` -> would appear in inside that distro as `/dev/sdc` . Just make a hyperv SCSI device with user's provided vhdk file...

**Comment by romabysen** [comment]
This would also be a good feature for when you have a small SSD as your Windows system disk. In this case you'd want to keep large source code repos and such on a different disk than the system SSD.

**Comment by sarim** [comment]
Not really the feature being asked for here, but If you use the `wsl --import` command to install distro you can select the directory. So the wsl distro is not in `c:`. I'm downloading image directly from ubuntu ( focal-server-cloudimg-amd64-wsl.rootfs.tar.gz ) and using wsl --import to install it in different drives.

**Comment by hzhangxyz** [comment]
I am not familiar with hyper v

Is there anyone explain how to "make a hyperv SCSI device with user's provided vhdk file"?

> A option to set additional drives via `/etc/wsl.conf` would be super cool.
> something like `d:/images/xxxx.vhdk` -> would appear in inside that distro as `/dev/sdc` . Just make a hyperv SCSI device with user's provided vhdk file...

**Comment by sarim** [comment]
> Is there anyone explain how to "make a hyperv SCSI device with user's provided vhdk file"?

You can't do it, it was a suggestion for wsl dev team. hyperv is the underlying virtualization technology used by wsl2.

**Comment by fekerr** [comment]
> This would also be a good feature for when you have a small SSD as your Windows system disk. In this case you'd want to keep large source code repos and such on a different disk than the vhd on the system SSD.

This is the case I have. I may just install a different ubuntu on my other (physical hard drive) drive. C: is SSD, E: is physical hard drive.

**Comment by fcying** [comment]
wsl2 can mount ext4 disk from `Windows 10 Build 20211`.
It would be great if vhd could also be mounted.

**Comment by therealkenc** [comment]
Let's call this fixed [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211), with further improvements to be filed under different covers (there are a few open already). Requests for documentation improvements (such as they might be expanded) in the [usual place](https://github.com/MicrosoftDocs/WSL).

/fixed 20211

**Comment by giggio** [comment]
@therealkenc Can the disk be mounted in more than one distro, read/write? If not, we can't share the home directory between distros.

**Comment by Spongman** [comment]
_Is_ this fixed in 20211, though? the original request asked for mounting .vhdx files as drives in wsl2. is this possible with `wsl --mount` ?

**Comment by onomatopellan** [comment]
@Spongman Yes, but you need to do it manually. See https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl

**Comment by Spongman** [comment]
@onomatopellan great, thanks! i'm surprised this wasn't mentioned in the original release-notes/article...
