### ISSUE TITLE
Interop fails to launch Windows exes when accessed via symlink

### ISSUE THREAD

**Issue by adamantoise** [microsoft/WSL#4558]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.356]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Attempting to launch Windows executables from WSL when accessed via certain symlinks fails with no useful error output:

```
$ sudo ln -s /mnt/c /c
$ ls -l /c
lrwxrwxrwx 1 root root 6 Jun 27 12:34 /c -> /mnt/c
$ /c/Windows/system32/notepad.exe
$ echo $?
1
```

* What's wrong / what should be happening instead:

The executable fails to launch and exits with status 1 when accessed via the symlink `/c`.  When accessed instead via the non-symlinked path `/mnt/c`, or without an an absolute path via `$PATH` (i.e. just the command line `notepad.exe`), it launches as expected.

* Strace of the failing command, if applicable:

```
execve("/c/Windows/system32/notepad.exe", ["/c/Windows/system32/notepad.exe"], 0x7fffe34871d8 /* 39 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x293820)       = 0
set_tid_address(0x293858)               = 15505
brk(NULL)                               = 0x2294000
brk(0x2295000)                          = 0x2295000
sched_getaffinity(0, 128, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) = 64
uname({sysname="Linux", nodename="DESKTOP-3PNEBRF", ...}) = 0
getpid()                                = 15505
getcwd("/mnt/c/Users/Adam Rosenfield/src/sdk", 4096) = 37
open("/dev/lxss", O_RDWR)               = 3
ioctl(3, _IOC(0, 0, 0x2f, 0x22), 0x7ffff61b4468) = 0
getcwd("/mnt/c/Users/Adam Rosenfield/src/sdk", 4096) = 37
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - lxfs ro"..., iov_len=1024}], 2) = 857
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
getcwd("/mnt/c/Users/Adam Rosenfield/src/sdk", 4096) = 37
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - lxfs ro"..., iov_len=1024}], 2) = 857
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
getcwd("/mnt/c/Users/Adam Rosenfield/src/sdk", 4096) = 37
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - lxfs ro"..., iov_len=1024}], 2) = 857
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, 0x7ffff61b41c8)        = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7ffff61b4418) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7ffff61b4418) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7ffff61b4418) = 0
write(4, "\0\0\0\0O\1\0\0006\5\0\0\0\0\0\0007\5\0\0\0\0\0\0008\5\0\0\0\0\0\0"..., 335) = 335
close(0)                                = 0
close(1)                                = 0
close(2)                                = 0
rt_sigprocmask(SIG_BLOCK, [INT WINCH], NULL, 8) = 0
signalfd4(-1, [INT WINCH], 8, 0)        = 0
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
read(4, "\10\0\0\0 \0\0\0\26\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
writev(2, [{iov_base="/c/Windows/system32/notepad.exe:"..., iov_len=50}, {iov_base=NULL, iov_len=0}], 2) = -1 EBADF (Bad file descriptor)
close(3)                                = 0
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Can provide if needed.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

---

This issue began appearing when I upgraded to 1903.  Prior to that, launching Windows executables via the `/c` symlink worked as expected.

According to Process Monitor traces, the difference between a working invocation (`/mnt/c/...`) and a non-working invocation (`/c/...`) begins when the working invocation calls `CreateFile` on the target executable (`C:\Windows\system32\notepad.exe`), whereas the non-working invocation first calls `CreateFile` on the path `C:\Users\Adam Rosenfield\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\fsserver`; that succeeds, then it calls `CloseFile` on that, and then it calls `CreateFile` on the target executable.

However, that `CreateFile` call is given `Desired Access: Read Data/List Directory, Execute/Traverse, Read Attributes, Synchronize` and `Options: Synchronous IO Non-Alert, Non-Directory File`, and it fails with the error `NOT A DIRECTORY`.  I.e., the system appears to be trying to open the executable file as a directory, which it isn't.

**Comment by benhillis** [comment]
Fixed in 18917.

**Comment by adamantoise** [comment]
Thank you!  I tried to search for duplicates of this issue, but I apparently didn't do a good enough job.  #3999 appears to be the master issue for this.

**Comment by benhillis** [comment]
@adamantoise - you are correct, thanks for posting!
