### ISSUE TITLE
apt install 404

### ISSUE THREAD

**Issue by slymon99** [microsoft/WSL#4560]
**SOLVED** https://github.com/microsoft/WSL/issues/4245

I'm getting the following errors when installing packages through apt
```
Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 binutils-common amd64 2.30-21ubuntu1~18.04.1
  404  Not Found [IP: 91.189.88.173 80]
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libbinutils amd64 2.30-21ubuntu1~18.04.1
  404  Not Found [IP: 91.189.88.173 80]
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 binutils-x86-64-linux-gnu amd64 2.30-21ubuntu1~18.04.1
  404  Not Found [IP: 91.189.88.173 80]
...
```

Though I can directly ping archive.ubuntu.com
```
ping archive.ubuntu.com
PING archive.ubuntu.com (91.189.88.174) 56(84) bytes of data.
64 bytes from secondary.danava.canonical.com (91.189.88.174): icmp_seq=1 ttl=53 time=74.5 ms
```

I get this on apt-get update
```
sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Reading package lists... Done
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 4d 3h 29min 57s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 4d 15h 34min 34s). Updates for this repository will not be applied.
```

Might it be something with apt using ipv6 and not having permission? I thought that was solved with the creators update.

I've looked at previous threads on similar issues (these are for apt-get update while mine is for actually installing packages with apt install)
https://github.com/Microsoft/WSL/issues/1720
https://github.com/Microsoft/WSL/issues/3353

There are a few different issues that I've ruled out
- Firewall / security (especially Kapersky and Symantec). I have tried disabling Windows firewall and don't have any other firewall / AV
- Not on an outdated version of Ubuntu
```sclark@DESKTOP-G9G19N3:~/eece$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
On Windows Build 1903

Let me know if there is any more information I should provide

**Comment by therealkenc** [comment]
> SOLVED #4245

The problem was related to an incorrect system date? I'll buy it (heck I'll buy anything). But it would be best to have clarification before closing as resolved.

**Comment by slymon99** [comment]
> > SOLVED #4245
> 
> The problem was related to an incorrect system date? I'll buy it (heck I'll buy anything). But it would be best to have clarification before closing as resolved.

Yea, if you look at the other thread the OP complains that it breaks` apt update`. The actual problem here is what is in the other thread is WSL's clock falling out of sync, I think this bug is specifically with laptops sleeping (which I could be a candidate for as I'm on a laptop)

Either way, fixing the time with `sudo hwclock -s` worked for me. Should be resolved.

**Comment by therealkenc** [comment]
I think [I see](https://github.com/microsoft/WSL/issues/4245#issuecomment-507517006) the post you are referring to. I has focused on the 404, which isn't easily explained by a broken clock. "`Updates for this repository will not be applied.`" makes perfect sense though. If `sudo hwclock -s` solves all your ills, including the 404, that's good enough for me here. Appreciate the follow up!

**Comment by benoitscherrer** [comment]
thanks, worked for me!

**Comment by fatihunlu0** [comment]
first yo should use "date" command after that use "sudo hwclock -s", finaly again use "date" command . it is now work for me.

**Comment by nisarg0** [comment]
Worked for me too thanks!
