### ISSUE TITLE
List of /mnt/c shows unknown/non-existent files and directories

### ISSUE THREAD

**Issue by dankox** [microsoft/WSL#4562]
ls /mnt/c provide weird output

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.295]

* What you're doing and what's happening:  
I'm trying to list /mnt/c `ls /mnt/c` and it shows me files which I've never seen before and can't read. If I check that directory in Explorer or in cmd/git-bash/powershell, those files are not there.

* What's wrong / what should be happening instead:
Listing of /mnt/c shouldn't show files which are invisible everywhere else. Maybe it's something wrong with my disk, but I just get new laptop with Windows 10 installation and install WSL (Ubuntu) on it.

Other thing to mention, that I see similar (or maybe the same) files in directories like my home directory, or documents, etc.      
But I don't see them in Windows directory or any other directory related to Windows or something else.

* Strace of the failing command, if applicable: 

https://gist.github.com/dankox/5041bbac98cd34200f3074f98cd911b3

Here is a screenshot how it looks on my system:
![WSL-vs-Windows-snip](https://user-images.githubusercontent.com/39275087/66059918-19323f80-e53d-11e9-926c-ebe45c5c92b1.jpg)

**Comment by therealkenc** [comment]
Almost certainly variation [this](https://social.technet.microsoft.com/Forums/Lync/en-US/096b353f-5f97-43a8-8cdd-32814f2fbcbb/weird-files-in-public-profile-beginning-with-zzzzz-or-?forum=win10itprogeneral). Not that I endorse (nor, equally, refute) any of the comments over in that thread. But something third-party (possibly of the unwanted variety) put those files there. How those files got there is not related to WSL. It could be the purveyors of your laptop put them there deliberately. It could be something else. [It's probably something else.]

Try a `dir /ah` with `cmd.exe` in `C:\`. If they show up, the NTFS hidden attribute is set on those files. Linux (and *nix) does not (conventionally) have a hidden attribute, and those files appear in Linux by-design [1]. Only files beginning with a dot ('`.`') are hidden, and only by convention, by the `ls` application. Those files would appear in Real Linux with [ntfs-3g](https://en.wikipedia.org/wiki/NTFS-3G) as well. 

If the files _don't_ show up with a `dir /ah`, then whatever put them there hid them but good using deeper voodoo. Either way, you could try copying those files with known extensions (png, pdf) somewhere on `/mnt/c` using `cp` in WSL, open them in Windows, and see if the contents sheds any light. With the serious warning: I can't tell you whether Bad Things™ will happen if you open them. Maybe start with looking at files with a `.txt` extension in WSL, which has a pretty low risk of harm. Bonne chance.

[1] It would be, getting into the weeds, possible in principle for Linux to behave differently. Say translating the NTFS hidden bit into a Linux extended attribute, and teaching GNU `ls` (list stuff) how to hide files with that attribute set, and show them with a `dir /ah` equivalent like `ls --show-hidden-win`. But for all practical purpose, if they exist in Windows (and they do) then they'll appear in WSL by-design.

**Comment by dankox** [comment]
@therealkenc Thanks for the response and for the links. It really looks like those "honey traps" done by our antivirus. I double check with other in our company and actually all of them have those files there visible thru WSL `ls` command. 

I totally understand, that removing the output from it just to match Windows visibility is not the correct approach. This way I can at least see what is Windows trying to hide from me :) 
It's not really bothering me, I was just surprised what is it and why I can see it only thru WSL.

I'm closing the issue, as it's not an issue in the end. Thanks

**Comment by brainz80** [comment]
@dankox Hi, I know this is a very old issue. I'm having the same issue with these weird files showing up in WSL `ls`. The antivirus you're using / were using was it by chanse Cortex XDR?

**Comment by dankox** [comment]
> @dankox Hi, I know this is a very old issue. I'm having the same issue with these weird files showing up in WSL `ls`. The antivirus you're using / were using was it by chanse Cortex XDR?

@brainz80 Hi, to be honest I'm not sure. It's been a while and I don't use Windows anymore. But it was a company antivirus, so I assume it was Symantec back then.

**Comment by Panagiss** [comment]
@brainz80 I have the same and I'm using Cortex XDR.

**Comment by WeSpeakEnglish** [comment]
Confirning, have Cortex XDR, same issue
