### ISSUE TITLE
Windows "Restore firewalls to default" breaks WSL networking

### ISSUE THREAD

**Issue by joemaller** [microsoft/WSL#4566]
I've been happily working in WSL 2 for a few months. Today, while trying to troubleshoot a networking issue, I reset my Windows firewall to defaults. Now WSL can't connect to anything. 

* _Your Windows build number:_
`Microsoft Windows [Version 10.0.18990.1]`

* _What you're doing and what's happening:_ 

1. Open the **Firewall & network protection** pane in **Windows Security**
2. Click **Restore firewalls to default**
3. WSL 2 network connections are now blocked, it can't connect to anything 

* _What's wrong / what should be happening instead:_

Network connectivity should work from inside WSL after resetting the Windows Firewall. 

Best case would be a WSL-aware Windows Firewall  which could correctly reset itself so WSL still worked. A second-best solution would be a command which re-applies WSL-compatible firewall settings. But I'd be fine with documentation somewhere.

**Comment by WSLUser** [comment]
Actually should be both. The command would be for a workaround.

**Comment by ctadlock** [comment]
To work around this, open a new PowerShell terminal as an administrator and run the command:

`New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow`

**Comment by silentkdev** [comment]
I ran into this issue and the above command did not restore the localhostforwarding functionality.  My distro is able to connect to the internet but Browsers in Windows are unable to connect to process running on ports from WSL via localhost.

**Comment by silentkdev** [comment]
> I ran into this issue and the above command did not restore the localhostforwarding functionality. My distro is able to connect to the internet but Browsers in Windows are unable to connect to process running on ports from WSL via localhost.

https://github.com/microsoft/WSL/issues/5575#issuecomment-922637756

So turns out the disabling the IP Service restored the localhost connection between WSL and WIndows.  I'm not sure if the IP Service was enabled after resetting the restoring firewall to default but this is what worked for me.
