### ISSUE TITLE
Bash command taking too long to finish

### ISSUE THREAD

**Issue by ye-lin-aung** [microsoft/WSL#4568]
* Your Windows build number:  Microsoft Windows [Version 10.0.18995.1] WSL 2 Ubuntu 18.04

* What you're doing and what's happening:  
I tried to execute commands in mounted C drive in wsl2. There is a project folder copied from my old linux laptop. I opened it with my emacs editor on windows. Save a new file. I go back to wsl and try to execute `ls`. The command executed immediately and show results but takes too long to take another input. It took too long to finally show up for another input

![Capture](https://user-images.githubusercontent.com/11737664/66187808-9f6c9400-e6ab-11e9-88d1-44a768c5f9b0.PNG)

* What's wrong / what should be happening instead: The command should be executed immediately and available for next input.

**Comment by craigloewen-msft** [comment]
@ye-lin-aung what shell are you using? Perhaps the shell is trying to run commands such as `git status` etc. to show you your git branch or other info and those processes are causing the delay for a new line of input. 

If you use the bash shell with default configurations do you still get this input delay?

**Comment by ye-lin-aung** [comment]
Ooh yea. Found the issue now. It was my zsh trying to show git status. Will close the issue now
