### ISSUE TITLE
base16-shell's profile_helper.sh hardlocks in WSL2 causing login hangs 

### ISSUE THREAD

**Issue by gordallott** [microsoft/WSL#4571]
As title describes, [base16-shell](https://github.com/chriskempson/base16-shell) is a utility generally run on login via a .bashrc/.zshrc - it sets colour themes for a terminal. 

Has worked perfectly everywhere I have run it, aside from wsl2 where it hard-locks. 

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18995.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

cloning [base16-shell](https://github.com/chriskempson/base16-shell) and running the profile_helper.sh that comes with it 
```bash
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
./.config/base16-shell/profile_helper.sh
```

* What's wrong / what should be happening instead:
script hardlocks instead of executing 

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

https://gist.github.com/gordallott/42a9b39febcfe203506acc3b6e98c349

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Was not able to reproduce this here on 18995, WSL2, with bash.
