### ISSUE TITLE
pyenv not installing any version successfully?

### ISSUE THREAD

**Issue by Pietro-G** [microsoft/WSL#4572]
* Your Windows build number: Microsoft Windows [Version 10.0.17763.737]

* What you're doing and what's happening:  I'm attempting to use `pyenv` with WSL
* What's wrong / what should be happening instead: I can install pyenv, however, when I use 'pyenv install {any version}' it won't ever succeed. The verbose log isn't much help, it passes some, it doesn't pass others, and logs about failing to install to target.
* What's wrong / what should be happening instead: Target python version should be installed instead, and the plug in should enable multiple versions of python to live inside the pyenv directory.

All other prompts fell under N/A

**Comment by Pietro-G** [comment]
My working solution is currently to just create a python virtual environment `venv` which seems to be giving no issues as of now.

**Comment by jChapman** [comment]
Have you read over this? https://github.com/pyenv/pyenv/wiki/common-build-problems

**Comment by Pietro-G** [comment]
Yes, the issue does not compare to any of those common-build-problems, however, it is no longer an issue for me, therefore I will simply close the issue, thanks!
