### ISSUE TITLE
WSL2 Unable to Install/Upgrade Distros 18995.1+

### ISSUE THREAD

**Issue by ev-dev** [microsoft/WSL#4573]
Build: 10.0.18995.1

I tried really hard not to open another issue here but I'm not having any success with WSL2 on latest build. The following issues may be related as to why:
- Attempts to convert working WSL v1 distros fail with prompt to enable Virtual Machine Platform feature (tested w/Ubuntu 18.04 LTS from Store)
![image](https://user-images.githubusercontent.com/26840537/66248434-f64a8b80-e6f4-11e9-905d-94f79e4a1c81.png)

- Attempts to install new distros after setting wsl default version to 2 fail with error 0x80370102
![image](https://user-images.githubusercontent.com/26840537/66248429-d4e99f80-e6f4-11e9-8129-0882f548d810.png)

- Conversion attempts also prompt a Defender notification (I have automatic sample submission turned off)
![image](https://user-images.githubusercontent.com/26840537/66248461-60633080-e6f5-11e9-9f9b-704f5ce1c754.png)

**Before Creating Issue**
- I triple checked my BIOS virtualization is enabled and verified via Task Manager & multiple motherboard/BIOS config apps (ASUS utilities)
- Tried enabling/disabling/re-enabling of the Subsystem for Linux & Virtual Machine Platform features via both PowerShell & Features GUI (with restarts between each individual feature)
- Tried fully disabling Defender/Firewall protection
- Because researching docs/community still left me unclear on Hyper-V as it relates to WSL2, I tried enabling/disabling Hyper-V & Windows Hypervisor Platform features via both PowerShell & Features GUI (restarts between tests)

**Comment by GManzato** [comment]
I'm having the same problem.

**Comment by ev-dev** [comment]
After a few subsequent insider builds my wsl2 distros automagically began to work. 
Since no other users have commented and there are far too many isssues for this repo, I'm closing it up.
