### ISSUE TITLE
ulimit -n dose not works

### ISSUE THREAD

**Issue by 19317362** [microsoft/WSL#4575]
$ uname -a Linux DESKTOP-RF30NLI 4.19.72-microsoft-standard #1 SMP Sun Sep 15 10:03:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic
$ ulimit
unlimited
$ ulimit -n
1024
$ ulimit -a core file size (blocks, -c) 0
data seg size (kbytes, -d) unlimited
scheduling priority (-e) 0
file size (blocks, -f) unlimited
pending signals (-i) 124007
max locked memory (kbytes, -l) 64
max memory size (kbytes, -m) unlimited
open files (-n) 1024
pipe size (512 bytes, -p) 8
POSIX message queues (bytes, -q) 819200
real-time priority (-r) 0
stack size (kbytes, -s) 8192
cpu time (seconds, -t) unlimited
max user processes (-u) 124007
virtual memory (kbytes, -v) unlimited
file locks (-x) unlimited
$ ulimit -n
1024
$ ulimit -n 1023
$ ulimit -n 1023
$ ulimit -n 8000
-bash: ulimit: open files: cannot modify limit: Operation not permitted
$ ulimit -n 1024 -bash: ulimit: open files: cannot modify limit: Operation not permitted
$

**Comment by therealkenc** [comment]
Linux behavior.

![image](https://user-images.githubusercontent.com/7049700/66262097-b7691400-e78e-11e9-8ae2-68898c69a3be.png)

**Comment by hundanLi** [comment]
So how to solve this problem？

**Comment by therealkenc** [comment]
If a process could increase its own limit, it wouldn't be much of a limit, would it.

You possibly want:
```
$ mylimit=8000
$ sudo prlimit --nofile=$mylimit --pid $$; ulimit -n $mylimit
```

n.b. Support for process limits on WSL1 is... limited.

**Comment by hundanLi** [comment]
Thanks a lot!

**Comment by crazyoptimist** [comment]
```bash
sudo prlimit --nofile=8000 --pid $$; ulimit -n 8000
```

That solved my problem, thanks.

Can you explain what it does?
