### ISSUE TITLE
New option automount/crossDistro in wsl.conf is not documented

### ISSUE THREAD

**Issue by zot** [microsoft/WSL#4577]
The `crossDistro` option in `wsl.conf` is undocumented in [the wsl.conf documentation](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md#configuration-options).

@therealkenc mentions in https://github.com/microsoft/WSL/issues/4574#issuecomment-538767587 that `automount/crossDistro` might have to do with mounting VHDX files, as I request in issue https://github.com/microsoft/WSL/issues/4556 but all I can find is a brief mention in the [release notes for build 18970](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18970).

**Comment by benhillis** [comment]
Typically we do not update docs until the build with the options is officially released (non Insider builds).

**Comment by xtremeperf** [comment]
crossDistro, when enabled, cross mounts the rootfs for currently running instances under /mnt/wsl

```
bash$ wsl.exe -l --running

Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
Arch
Debian

bash$ findmnt --submounts /mnt/wsl

TARGET                  SOURCE   FSTYPE OPTIONS
/mnt/wsl                tmpfs    tmpfs  rw,relatime
├─/mnt/wsl/Ubuntu-18.04 /dev/sdb ext4   rw,relatime,discard,errors=remount-ro,data=ordered
├─/mnt/wsl/Debian       /dev/sdc ext4   rw,relatime,discard,errors=remount-ro,data=ordered
└─/mnt/wsl/Arch         /dev/sdd ext4   rw,relatime,discard,errors=remount-ro,data=ordered

bash$
```

**Comment by zot** [comment]
Thanks!

**Comment by therealkenc** [comment]
Be interesting to try installing [Docker Desktop](https://docs.docker.com/docker-for-windows/install/) along side WSL and see what happens, if anything (n.b. I have not).

**Comment by zot** [comment]
I have been using it since I first switched from a VM to WSL 2 a couple weeks ago and it works great!

This is another reason I want external VHDXs, so I can keep my personal docker repository in one for easy backup and piece of mind...

**Comment by benhillis** [comment]
FYI - after some discussion with @simonferquel (the dev working on WSL2 Docker Desktop) we have changed the way this works a bit.  Now the /mnt/wsl path is a recursive shared tmpfs mount that does not have the distros root filesystems automatically mounted.  The upside of this is it allows users much greater flexibility of what to share with other distros (for example create a recursive bind mount of you're entire distro including submounts).

**Comment by tabarnakos** [comment]
> Typically we do not update docs until the build with the options is officially released (non Insider builds).

How can the insiders provide feedback then ? If the source code is not public, some draft documentation should accompany the Insider releases.

**Comment by zot** [comment]
> > Typically we do not update docs until the build with the options is officially released (non Insider builds).
> 
> How can the insiders provide feedback then ? If the source code is not public, some draft documentation should accompany the Insider releases.

Just provide feedback anyway, that's what I do :)

**Comment by therealkenc** [comment]
The `wsl.conf` `crossDistro=` option was abandoned in favor of more flexible (and generic) bind mounts of the user's choosing. A doc request or PR for bind mounts can be submitted in [MicrosoftDocs/WSL](https://github.com/MicrosoftDocs/WSL). Two-liner sketch is in #5177 ([message](https://github.com/microsoft/WSL/issues/5177#issuecomment-685169738)).
