### ISSUE TITLE
libQGLViewer Example failed on WSL

### ISSUE THREAD

**Issue by Beniko95J** [microsoft/WSL#4578]
**Please fill out the below information:**
* Your Windows build number:
Microsoft Windows [Version 10.0.18362.356]

* What you're doing and what's happening: 
I am using Ubuntu 18.04 on WSL and I want to run 
the libQGLViewer Example on it (https://svn.larosterna.com/oss/tags/cleanup-7nov2014/trunk/holodeck/libQGLViewer/doc/examples/simpleViewer.html). I got this error message:

```
Thread 1 "simple_viewer" received signal SIGSEGV, Segmentation fault.
0x00007ffffef13a7a in QGLWidget::qglClearColor(QColor const&) const () from /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
```

I have enabled my WSL to run some gui programs like **glxgears**, but I failed to run the libQGLViewer program. I have installed libqglviewer-dev-qt5 and qt5-qmake on the WSL, and my cmake file and cmake_modules are as follows so you may reproduce the problem

cmakelists.txt
```
cmake_minimum_required(VERSION 3.0)
PROJECT(simple_viewer)

SET(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake_modules)

FIND_PACKAGE(OpenGL REQUIRED)
INCLUDE_DIRECTORIES(${OPENGL_INCLUDE})

FIND_PACKAGE(QGLViewer REQUIRED)
INCLUDE_DIRECTORIES(${QGLVIEWER_INCLUDE_DIR})

FIND_PACKAGE(Qt5 COMPONENTS Xml OpenGL Gui Core REQUIRED)
INCLUDE_DIRECTORIES(${Qt5Xml_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${Qt5OpenGL_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${Qt5Gui_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${Qt5Core_INCLUDE_DIRS})

ADD_EXECUTABLE(${PROJECT_NAME} main.cpp simpleViewer.cpp)

TARGET_LINK_LIBRARIES(${PROJECT_NAME}
  ${QGLVIEWER_LIBRARY}
  Qt5::Xml
  Qt5::OpenGL
  Qt5::Gui
  Qt5::Core 
  ${OPENGL_gl_LIBRARY}
  ${OPENGL_glu_LIBRARY}
)
```

cmake_modules
```
find_package(Qt5 COMPONENTS Core Xml OpenGL Gui Widgets)
if(NOT Qt5_FOUND)
  message("Qt5 not found. Install it and set Qt5_DIR accordingly")
  if (WIN32)
    message("  In Windows, Qt5_DIR should be something like C:/Qt/5.4/msvc2013_64_opengl/lib/cmake/Qt5")
  endif()
endif()

find_path(QGLVIEWER_INCLUDE_DIR qglviewer.h
    /usr/include/QGLViewer
    /opt/local/include/QGLViewer
    /usr/local/include/QGLViewer
    /sw/include/QGLViewer
    ENV QGLVIEWERROOT
  )

find_library(QGLVIEWER_LIBRARY_RELEASE
  NAMES qglviewer-qt5 QGLViewer-qt5
  PATHS /usr/lib
        /usr/local/lib
        /opt/local/lib
        /sw/lib
        ENV QGLVIEWERROOT
        ENV LD_LIBRARY_PATH
        ENV LIBRARY_PATH
  PATH_SUFFIXES QGLViewer QGLViewer/release
)
find_library(QGLVIEWER_LIBRARY_DEBUG
  NAMES dqglviewer dQGLViewer dqglviewer-qt5 dQGLViewer-qt5 QGLViewerd2
  PATHS /usr/lib
        /usr/local/lib
        /opt/local/lib
        /sw/lib
        ENV QGLVIEWERROOT
        ENV LD_LIBRARY_PATH
        ENV LIBRARY_PATH
  PATH_SUFFIXES QGLViewer QGLViewer/debug
)

if(QGLVIEWER_LIBRARY_RELEASE)
  if(QGLVIEWER_LIBRARY_DEBUG)
    set(QGLVIEWER_LIBRARY optimized ${QGLVIEWER_LIBRARY_RELEASE} debug ${QGLVIEWER_LIBRARY_DEBUG})
  else()
    set(QGLVIEWER_LIBRARY ${QGLVIEWER_LIBRARY_RELEASE})
  endif()
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QGLVIEWER DEFAULT_MSG
  QGLVIEWER_INCLUDE_DIR QGLVIEWER_LIBRARY)
```

Thanks!

**Comment by therealkenc** [comment]
There is no repro nor strace log. But we're treading into academic territory. Give [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/) a whirl and, assuming the app (and Qt) works on Real Linux _in a remote X11 scenario with the same X11 server_ (it might, it might not) you'll be good.

**Comment by pangyuteng** [comment]
for what its worth, to those attempting to launch GUIs from WSL2, I was able to launch `glxgears` from a docker container that started within WSL2 with X11 forwarding via ssh.  The high level steps are a follows:

+ install openssh, wsl2, docker-desktop with chocolatey
+ enable openssh, X11 forwarding.
+ set environment variables in wsl2 terminal.
```
export LIBGL_ALWAYS_INDIRECT=1
export DISPLAY=$IP:0.0
```
+ launch docker container with environment variable `DISPLAY`, some claim they have to provide more display related `-v` and `-e`, you can easilty find those from stackoverflow, askubuntu.
+ within the container/Dockerfile, install dependencies and launch your gui.

More info can be found in below link. (Do note that I am still having issues with rendering QT+OpengGL windows, which I believe is more related to QT+VTK+OpenGL integration issues)

https://gist.github.com/pangyuteng/3fea371f9c783d81b75d0ef12099dbef

**Comment by therealkenc** [comment]
> export LIBGL_ALWAYS_INDIRECT=1

That is and remains [dubious guidance](https://github.com/microsoft/WSL/discussions/6154#discussioncomment-113280).

> you can easily find those from stackoverflow, askubuntu

Yes, you can, which is most unfortunate, but what you gonna do.
