### ISSUE TITLE
Not startinng in current directory for drives mounted by subst

### ISSUE THREAD

**Issue by nory190** [microsoft/WSL#4580]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.388]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

When current directory is in the drive mounted by subst, wsl starts at `~`, instead of current directory.

```
D:\> subst f: d:\$drives\F
D:\> f:
F:\> wsl
user@pc:~$ pwd
/home/user
```

This is same as #2043#issuecomment-402105837. But #3246, in which #2043 is merged, seems to be a topic only for virtual disks and optical disks.  
In this case, `/mnt/f` is not appeared. It is mentioned in #789.

dmesg saids:
```
[    0.003052]  Microsoft 4.4.0-18362.1-Microsoft 4.4.35
[    0.086162] init: (8) ERROR: CreateProcessParseCommon:869: Failed to translate F:\
```

I created `/mnt/f` and mounted `/mnt/d/$drive/f` like subst, or created symbolic link `/mnt/f -> /mnt/d/$drive/f`, but both were ineffective.

The same applies when the drive mounted by registry 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices'. I use this method.

* What's wrong / what should be happening instead:

I think wsl should start with current directory even on subst drives.  
It is desirable that subst drive be automounted, but it can also be manually mount or a symbolic link.

In Windows 10 1803 (April 2018 Update), it had worked with symbolic link.

**Comment by btreut** [comment]
I have a similar problem see issue https://github.com/microsoft/WSL/issues/6798. It has been rejected due to an outdated but supported Windows version. Interestingly my network share is mounted read only.
