### ISSUE TITLE
Cannot start WSL on the machine that have already installed VMWare or VirtualBox

### ISSUE THREAD

**Issue by andres-iniesta** [microsoft/WSL#4584]
I have installed VMWare Player version 15 into my computer

* Your Windows build number:  Microsoft Windows [Version 10.0.18990.1]

* What you're doing and what's happening:  I have installed Ubuntu from Microsoft Store

Then try to open Ubuntu from Start menu:

* What's wrong / what should be happening instead:
I got the error message like this:

> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80370102
> Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
> 
> Press any key to continue...
>

**Comment by throwable-one** [comment]
From what I know, you can only have one hypervisor: either VMWare or Hyper-V. Latter is used by WSL2.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox

**Comment by 0xbadfca11** [comment]
Looks like the ``VirtualMachinePlatform`` feature is not installed.
Because the Windows hypervisor used by WSL2 is started by the boot loader at boot time, no other type-2 hypervisor can win this.
Make sure you have the ``VirtualMachinePlatform`` enabled.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by Biswa96** [comment]
Though I have not test it, there is some way to run VirtualBox (hv-2) and HyperV (hv-1). See [this SuperUser answer][1] and the [actual VirtualBox forum post][2].


[1]: https://superuser.com/a/1489744/726810
[2]: https://forums.virtualbox.org/viewtopic.php?f=6&t=90853&sid=f20b0f7f51e462005f9b3be80a567617&start=120#p453078

**Comment by craigloewen-msft** [comment]
The information above is correct, please make sure to enable the `VirtualMachinePlatform` optional component, and it should resolve this issue for you. I'll close this out as that will very likely fix your problem. If you are still running into issues please feel free to reopen, or keep commenting if you have more questions.

**Comment by pranithan-kang** [comment]
To anyone who try to re-install your Linux Subsystem after uninstall it. If you see 0x80370102 error despite your `Virtual Machine Platform` in Windows Feature is turn on (checked), please, do the following steps:
  - Turn the `Virtual Machine Platform` __OFF__
  - Restart your machine
  - Turn the `Virtual Machine Platform` __ON__
  - Restart your machine
  - Reinstall your WSL via Microsoft Store

**Comment by jithubhaijabs** [comment]
**Update:** Anyone facing similar issue when running VMware workstation and wants to install WSL. VMWare and VirtualBox has released versions that support Hyper-V and WSL2.

- If you have 3rd party hypervisors installed (Such as VMware or VirtualBox) then please ensure you have these on the latest versions which can support HyperV (VMware 15.5.5+ and VirtualBox 6+).
- Ensure virtualization technology (VTx) is enabled at the BIOS level.
- Goto Windows Programs and Features > Turn Windows Features on or off > Ensure Virtual Machine Platform is enabled. If not enable it.
- Run wsl --install -d <distro_name>. It should start installation and launch it.
