### ISSUE TITLE
warning: Insecure world writable dir /mnt/c in PATH, mode 040777

### ISSUE THREAD

**Issue by shafali03** [microsoft/WSL#4586]
I have installed ruby and WSL Ubuntu. Whenever I run ruby inside my code vs editor or console, I receive this warning message.

/usr/lib/ruby/vendor_ruby/rbnacl/libsodium/version.rb:5: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
How do you fix this problem?

**Comment by Biswa96** [comment]
Add the proper mounting permission with `/etc/wsl.conf` file. See this blog post https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/.

**Comment by shafali03** [comment]
I have seen this blog when I type /etc/wsl.conf and enter the password I see a blank page at the bottom of the page I have "/etc/wsl.conf" [New File]

**Comment by Biswa96** [comment]
> when I type /etc/wsl.conf and enter the password I see a blank page

Sorry, I can not understand that statement. `/etc/wsl.conf` is a file that you have to create and add the proper mounting options with any text editor in that WSL installed Linux distribution e.g. vi, vim, nano, emacs etc. Though the permission of `/mnt/c` is shown as `0777` you can not add or write any file or folder. For that the `wsl.exe` need to be run as administrator.

**Comment by shafali03** [comment]
How can I get the --INSERT-- page

**Comment by shafali03** [comment]
Sorry for the late response. First I need to go into etc and create a file call wsl.conf inside the wsl.conf 

generateHosts = false  
[amount]
options = "metadata"
Is the above process correct

**Comment by therealkenc** [comment]
This is by-design Ruby. #1426
