### ISSUE TITLE
Segmentation fault when calling rpm -qp

### ISSUE THREAD

**Issue by aghsmith** [microsoft/WSL#4587]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.805]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I'm running rpm with the -qp options on an oracle rpm.

`sudo -s
su -
wget https://download.oracle.com/otn_software/linux/instantclient/193000/oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64.rpm
rpm -qp /root/oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64.rpm`

I'm getting a segfault:
`rpm -qp oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64.rpm
Segmentation fault (core dumped)`

with a return value of 139

The following files are also created:
`ll .rpmdb/
total 804
drwxr-xr-x 1 root root   4096 Oct 10 17:44 ./
drwx------ 1 root root   4096 Oct 10 17:43 ../
-rw-r--r-- 1 root root      0 Oct 10 17:43 .dbenv.lock
-rw-r--r-- 1 root root   8192 Oct 10 17:43 Basenames
-rw-r--r-- 1 root root   8192 Oct 10 17:44 Conflictname
-rw-r--r-- 1 root root   8192 Oct 10 17:44 Dirnames
-rw-r--r-- 1 root root   8192 Oct 10 17:43 Group
-rw-r--r-- 1 root root   8192 Oct 10 17:44 Installtid
-rw-r--r-- 1 root root   8192 Oct 10 17:43 Name
-rw-r--r-- 1 root root   8192 Oct 10 17:44 Obsoletename
-rw-r--r-- 1 root root  12288 Oct 10 17:43 Packages
-rw-r--r-- 1 root root   8192 Oct 10 17:43 Providename
-rw-r--r-- 1 root root   8192 Oct 10 17:43 Requirename
-rw-r--r-- 1 root root   8192 Oct 10 17:44 Triggername
-rw-r--r-- 1 root root 393215 Oct 10 17:43 __db.001
-rw-r--r-- 1 root root  90111 Oct 10 17:43 __db.002
-rw-r--r-- 1 root root 110591 Oct 10 17:44 __db.003`

which are a subset of the ones created if the same is performed on another machine: Virtual box instance of Ubuntu 18.04.3 LTS.

WSL version:
`wslsys --version
wslu v2.0.0; wslsys v28`

Guest OS:
`cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

RPM version:
`rpm --version
RPM version 4.14.1`

* What's wrong / what should be happening instead:
There should be no segfault, the name of the rpm should be echoed and a superset of the .rpmdb files shoudl be present. The return value should be 0.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

[rpm_qp.strace.txt](https://github.com/microsoft/WSL/files/3713688/rpm_qp.strace.txt)

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
There wasn't a WSL launch issue.

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sirredbeard** [comment]
#3939?

**Comment by therealkenc** [comment]
> 10.0.17763.805

> #3939?

Yeah.
