### ISSUE TITLE
WSL2 doesn't support masked watchpoints

### ISSUE THREAD

**Issue by Swiftloke** [microsoft/WSL#4589]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18990.1]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem
WSL doesn't seem to support masked watchpoints, even though the x86-64 architecture supports them.
Open up gdb (I'm personally using pwndbg) and write a command such as the following:
```watch *0x6c0000 mask 0xff0000```
This command fails with:
```This target does not support masked watchpoints.```
* What's wrong / what should be happening instead:
The watchpoint should be successfully set.
This may have something to do with #2609, which has conflicting claims that hardware watchpoints aren't supported in WSL at all.

**Comment by therealkenc** [comment]
Same behavior Real Linux, on a stock Ubuntu kernel, anyway.

![image](https://user-images.githubusercontent.com/7049700/66673238-0393d880-ec15-11e9-9666-0b5938945242.png)

> This may have something to do with #2609,

Unrelated. That is WSL1.

**Comment by Swiftloke** [comment]
@therealkenc Can confirm. Just tried it out on an old machine. Sorry for wasting your time. It seems x64 doesn't support masked watchpoints after all.

**Comment by therealkenc** [comment]
> It seems x64 doesn't support masked watchpoints after all.

No x64 does, AFAIK, anyway. TBH I didn't dive why your particular repro results in the error. Just know it does. [Also if we're being completely honest, I'm more of a [caveman](https://medium.com/@firhathidayat/the-caveman-debugging-ab8f7151415f) guy if I need a watch.]

> can be tagged as "fixed in WSL2"?

You'd think so. Not sure how that works, precisely. There are lots of open issues that could be marked fixed-in-wsl2.
