### ISSUE TITLE
Any chance for IPv6 networking?

### ISSUE THREAD

**Issue by spajak** [microsoft/WSL#4590]
Microsoft Windows [Version 10.0.18999.1]

```
$ ping6 www.google.com
    ping6: connect: Network is unreachable
```

Upps..

```
$ ip addr show | grep inet6
    inet6 ::1/128 scope host
    inet6 fe80::215:5dff:fe40:655a/64 scope link
```

I have a server that's IPv6 only and I cannot access it from WSL 2

**Comment by miyurusankalpa** [comment]
I use WSL 1 all the time with IPv6. If WSL2 does not support it, I wont be upgrading.

**Comment by spajak** [comment]
I've started with WSL 2 without using WSL 1 much. So maybe I'm missing something important about network configuration? But everything else is working fine.
```
$ uname -a
Linux SPHOME 4.19.72-microsoft-standard #1 SMP Sun Sep 15 10:03:24 UTC 2019 x86_64 GNU/Linux
```

**Comment by craigloewen-msft** [comment]
IPV6 only sites and addresses are not yet supported by the Host Networking service which powers networking in WSL 2. This is a feature request we've relayed to the team, and we are tracking it on this thread: https://github.com/microsoft/WSL/issues/4518. I'll mark this thread as a duplicate and close it out, please feel free to watch and/or comment on the linked thread for further discussion. Thanks! :)
