### ISSUE TITLE
how to register already exist WSL distribute when I changed windows account

### ISSUE THREAD

**Issue by qclzdh** [microsoft/WSL#4591]
I already setup wsl distribution in my WIN10 account as following:
![1](https://user-images.githubusercontent.com/16543023/66694525-f9420f00-ece6-11e9-9cdb-7153004f164c.png)

But, when i changed my WIN10 account to another one, i can't find my distribution, is there some easy way to register this:
![2](https://user-images.githubusercontent.com/16543023/66694542-1d9deb80-ece7-11e9-9802-efcc5bc1acc8.png)

My distribution already install many things, it takes about 800G, I don't want to re-install it, or export/import, it is too long to do this, since it's so big.

**Comment by qclzdh** [comment]
BTW, my distribution installed in D:\wsl\Ubuntu\

**Comment by Biswa96** [comment]
Let assume two users, 1st user has installed a distro but 2nd does not.

* 😇 Good advice:

  - Use `wsl --export` in 1st user to make a tar file.
  - Move that file to 2nd user realm.
  - Use `wsl --import` to install it in 2nd user.

* 😈 Evil advice:

  - Copy the VHDX file from 1st user. See [this Superuser answer][1] for how to find.
  - Export the registry `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss` from 1st user in a REG file.
  - Copy or move those two files to 2nd user realm.
  - Double click to import the registry.
  - Copy the path where you put the VHDX file in 2nd user realm and paste it in the `BasePath` in  Lxss registry key. Make sure to match the distribution name.

[1]: https://superuser.com/q/1067373/726810

**Comment by benhillis** [comment]
@Biswa96 - I wish you'd stop suggesting people mess around with the registry...

**Comment by Konstantin-Glukhov** [comment]
You can even go further, just create a new entry under Lsxx and register whatever you want :) Just make sure to generate a unique key for the distribution.
E.g.:

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{5526db11-a739-4a33-9031-9793a481c2ed}]
"State"=dword:00000001
"DistributionName"="Ubuntu-18.04"
"Version"=dword:00000002
"BasePath"="\\\\?\\E:\\Linux\\Ubuntu\\18.04"
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000

**Comment by sisrfeng** [comment]
> @Biswa96 - I wish you'd stop suggesting people mess around with the registry...

Hi, is there any command that can solve this issue without touching the registry?

**Comment by sisrfeng** [comment]
> make sure to generate a unique key for the distribution.

in powershell:
```{b0ce2bd6-34f1-445a-b990-949154fe8576}```

ref:
1. https://www.tenforums.com/tutorials/130522-generate-globally-unique-identifier-guid-windows.html
2. 2
![Uploading image.png…]()

**Comment by eugenesvk** [comment]
FYI to correct a few typos in the version listed above the full .reg file you can paste it into, update and open to add
 
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{5526db11-a739-4a33-9031-9793a481c2ed}]
"State"=dword:00000001
"DistributionName"="Ubuntu"
"Version"=dword:00000002
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000
"BasePath"="\\\\?\\E:\\Linux\\Ubuntu"
```
