### ISSUE TITLE
Distro Installation Fails in WSL

### ISSUE THREAD

**Issue by nidens** [microsoft/WSL#4593]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18999.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
1. Opening Ubuntu.exe
2. Given this error
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070032
Error: 0x80070032 The request is not supported.

Press any key to continue...
```
3. Installation has failed on both Ubuntu and Kali Linux. 

* What's wrong / what should be happening instead:
I am currently unable to install any linux distributions to WSL. The expected outcome should be the distribution should install properly. I have reinstalled WSL multiple times and also updated to the latest windows insider build but the problem persists. Additionally since this is a launch issue, i've attached the logs generated from logman. 

[lxcore_kernel.log](https://github.com/microsoft/WSL/files/3720708/lxcore_kernel.log)
[lxcore_service.log](https://github.com/microsoft/WSL/files/3720709/lxcore_service.log)
[lxcore_user.log](https://github.com/microsoft/WSL/files/3720710/lxcore_user.log)

**Comment by nidens** [comment]
I ended up just reinstalling Windows 10, upgrading to the insider build and reinstalling WSL + Ubuntu and have no issues.

**Comment by MattGal** [comment]
I'm hitting this problem but am less interested in fully reinstalling windows than nidens.

**Comment by hrai** [comment]
i have the same issue on v10.0.19613.1005

**Comment by MattGal** [comment]
> I have the same issue on v10.0.19613.1005

I actually unblocked myself using Process Monitor.  At least for my case it was a file permission issue for where the app was uninstalled.  I had to take ownership of the folder it was installed in to fully delete it, then reinstall worked. YMMV.

**Comment by poon64** [comment]
> * Your Windows build number:  (Type `ver` at a Windows Command Prompt)
>   Microsoft Windows [Version 10.0.18999.1]
> * What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
> 
> 1. Opening Ubuntu.exe
> 2. Given this error
> 
> ```
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80070032
> Error: 0x80070032 The request is not supported.
> 
> Press any key to continue...
> ```
> 
> 1. Installation has failed on both Ubuntu and Kali Linux.
> 
> * What's wrong / what should be happening instead:
>   I am currently unable to install any linux distributions to WSL. The expected outcome should be the distribution should install properly. I have reinstalled WSL multiple times and also updated to the latest windows insider build but the problem persists. Additionally since this is a launch issue, i've attached the logs generated from logman.
> 
> [lxcore_kernel.log](https://github.com/microsoft/WSL/files/3720708/lxcore_kernel.log)
> [lxcore_service.log](https://github.com/microsoft/WSL/files/3720709/lxcore_service.log)
> [lxcore_user.log](https://github.com/microsoft/WSL/files/3720710/lxcore_user.log)

I have the same problem and have done the same steps as you have, but the results are always the same. I have updated windows insider to latest version. I haven't found any solution for this problem yet, and I don't want to reinstall windows, I'd rather go Linux native in that case.

**Comment by dragonofmercy** [comment]
I solved this by ensuring that Virtual Machine Platform was installed/ticked in Turn Windows features on or off.

**Comment by jimdibb** [comment]
Yup, turn on the feature.   This caught me out when I upgraded from a build with WSL1 to the build with WSL2.  You won't have the Virtual machine platform on, but V1 installs will still work, but the upgrade of the install to version 2 or a new install will fail.

**Comment by neitrinoweb** [comment]
I have the same issue under WSL2, WSL1 works.

**Comment by antoniovizuete** [comment]
I faced the same problem

**Comment by NickBanspach** [comment]
I was struggling with this issue for the past 2 weeks and managed to solve it. 
I am on a PC managed by Microsoft Intune, Storage driver installation is not allowed. So it turned out I was missing the device driver for the Virtual Hard Disks, wsl2 wants to create. Device Manager was looking like this:
![DeviceManager](https://github.com/microsoft/WSL/assets/85608978/ead5758f-4509-4233-b7e8-5b07be64e538)
Once I figured that out, I could ask my friendly sysadmin to allow this driver to be installed and wsl2 was running fine.
So if you have this issue, please check that you have the `Microsoft VHD Loopback Controller` in the `Storage controllers` section of Device Manager.

**Comment by NgoDuc2505** [comment]
> I solved this by ensuring that Virtual Machine Platform was installed/ticked in Turn Windows features on or off.

It worked for me. Thank you.
