### ISSUE TITLE
How to open Windows process from within WSL with passing valid path? 

### ISSUE THREAD

**Issue by a-r-m-i-n** [microsoft/WSL#4594]
Hi. Basically I would like to achieve this command working from within WSL:

```
$ code . 
```
Which should open a VS Code window with the current working directory. 

Actually it does open the VS Code Window, but because the dir path in arguments is in unix style, VS Code can not handle it. 

I've seen there is a wsl Plugin for vs code existing, connecting to a remote session (in wsl). But this is not what I'm looking for. I also want to open other apps, this way. 

The only issue is to pass the correct path in Windows style. I've thought about an alias in bash which could achieve this (convert the path before calling windows program). Do you have an example for me? I'm not that familiar with bash script. 

Thanks in advance 
Armin

**Comment by a-r-m-i-n** [comment]
I should mention that I've changed the root mounts. My absolute paths in wsl start like this: /c/and/so/on

So I could convert it 1:1 without need to strip the /mnt dir.

**Comment by timesnewmen** [comment]
I am using vscode insider version, with WSL1, i don't have this issue. VS code open the current folder(not in remote session) for me.

**Comment by xtremeperf** [comment]
`wslpath -w .`
