### ISSUE TITLE
Unable to launch WSL2 

### ISSUE THREAD

**Issue by amalshaji** [microsoft/WSL#4598]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18999.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

  When I try to launch wsl, this is the output even though virtualization and WSL are enabled

`Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install`

[screenshot](https://drive.google.com/open?id=1oHeh8flvQ4lXcLbpufrKf0PCPsoZcMMi)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment]
Is virtualization enabled in your computers bios?

**Comment by amalshaji** [comment]
Yes. I'm able to run virtualbox. I do development on WSL2, It was working
fine until 3 days ago, suddenly it stopped working. So I had to switch back
to VirtualBox.

**Comment by benhillis** [comment]
@amalshaji - Are there any interesting messages in any of the Hyper-V related eventvwr logs?

**Comment by amalshaji** [comment]
Yes. Hyper-V-Hypervisor displays 3 warning messages around the date this
happened
************************************************************************************************************************************************************************************************************************************************************
Log Name:      Microsoft-Windows-Hyper-V-Hypervisor-Operational
Source:        Microsoft-Windows-Hyper-V-Hypervisor
Date:          09-10-2019 07:07:17 PM
Event ID:      12550
Task Category: None
Level:         Warning
Keywords:      (70368744177664)
User:          SYSTEM
Computer:      BEAST
Description:
Hyper-V detected access to a restricted MSR (Msr: 0x65C, IsWrite: 0x0,
MsrValue: 0xDD0000, AccessStatus: 0x0, Pc: 0xFFFFF807452C0200, ImageBase:
0xFFFFF807452B0000, ImageChecksum: 0x68C4F, ImageTimestamp: 0x59FB8DEC,
ImageName: esif_lf.sys).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Hyper-V-Hypervisor"
Guid="{52fc89f8-995e-434c-a91e-199986449890}" />
    <EventID>12550</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x2000400000000000</Keywords>
    <TimeCreated SystemTime="2019-10-09T13:37:17.270419200Z" />
    <EventRecordID>2</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="484" />
    <Channel>Microsoft-Windows-Hyper-V-Hypervisor-Operational</Channel>
    <Computer>BEAST</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Msr">0x65c</Data>
    <Data Name="IsWrite">0</Data>
    <Data Name="MsrValue">0xdd0000</Data>
    <Data Name="AccessStatus">0</Data>
    <Data Name="Pc">0xfffff807452c0200</Data>
    <Data Name="ImageBase">0xfffff807452b0000</Data>
    <Data Name="ImageChecksum">0x68c4f</Data>
    <Data Name="ImageTimestamp">0x59fb8dec</Data>
    <Data Name="ImageName">esif_lf.sys</Data>
  </EventData>
</Event>
************************************************************************************************************************************************************************************************************************************************************
Log Name:      Microsoft-Windows-Hyper-V-Hypervisor-Operational
Source:        Microsoft-Windows-Hyper-V-Hypervisor
Date:          10-10-2019 09:46:28 AM
Event ID:      12550
Task Category: None
Level:         Warning
Keywords:      (70368744177664)
User:          SYSTEM
Computer:      BEAST
Description:
Hyper-V detected access to a restricted MSR (Msr: 0x65C, IsWrite: 0x0,
MsrValue: 0xDD0000, AccessStatus: 0x0, Pc: 0xFFFFF8026CB60200, ImageBase:
0xFFFFF8026CB50000, ImageChecksum: 0x68C4F, ImageTimestamp: 0x59FB8DEC,
ImageName: esif_lf.sys).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Hyper-V-Hypervisor"
Guid="{52fc89f8-995e-434c-a91e-199986449890}" />
    <EventID>12550</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x2000400000000000</Keywords>
    <TimeCreated SystemTime="2019-10-10T04:16:28.253723500Z" />
    <EventRecordID>5</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="428" />
    <Channel>Microsoft-Windows-Hyper-V-Hypervisor-Operational</Channel>
    <Computer>BEAST</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Msr">0x65c</Data>
    <Data Name="IsWrite">0</Data>
    <Data Name="MsrValue">0xdd0000</Data>
    <Data Name="AccessStatus">0</Data>
    <Data Name="Pc">0xfffff8026cb60200</Data>
    <Data Name="ImageBase">0xfffff8026cb50000</Data>
    <Data Name="ImageChecksum">0x68c4f</Data>
    <Data Name="ImageTimestamp">0x59fb8dec</Data>
    <Data Name="ImageName">esif_lf.sys</Data>
  </EventData>
</Event>
************************************************************************************************************************************************************************************************************************************************************
Log Name:      Microsoft-Windows-Hyper-V-Hypervisor-Operational
Source:        Microsoft-Windows-Hyper-V-Hypervisor
Date:          10-10-2019 01:14:55 PM
Event ID:      12550
Task Category: None
Level:         Warning
Keywords:      (70368744177664)
User:          SYSTEM
Computer:      BEAST
Description:
Hyper-V detected access to a restricted MSR (Msr: 0x65C, IsWrite: 0x0,
MsrValue: 0xDD0000, AccessStatus: 0x0, Pc: 0xFFFFF8066B930200, ImageBase:
0xFFFFF8066B920000, ImageChecksum: 0x68C4F, ImageTimestamp: 0x59FB8DEC,
ImageName: esif_lf.sys).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Hyper-V-Hypervisor"
Guid="{52fc89f8-995e-434c-a91e-199986449890}" />
    <EventID>12550</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x2000400000000000</Keywords>
    <TimeCreated SystemTime="2019-10-10T07:44:55.233908400Z" />
    <EventRecordID>8</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="9220" />
    <Channel>Microsoft-Windows-Hyper-V-Hypervisor-Operational</Channel>
    <Computer>BEAST</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Msr">0x65c</Data>
    <Data Name="IsWrite">0</Data>
    <Data Name="MsrValue">0xdd0000</Data>
    <Data Name="AccessStatus">0</Data>
    <Data Name="Pc">0xfffff8066b930200</Data>
    <Data Name="ImageBase">0xfffff8066b920000</Data>
    <Data Name="ImageChecksum">0x68c4f</Data>
    <Data Name="ImageTimestamp">0x59fb8dec</Data>
    <Data Name="ImageName">esif_lf.sys</Data>
  </EventData>
</Event>
************************************************************************************************************************************************************************************************************************************************************
I hope this helps

**Comment by amalshaji** [comment]
Currently I'm on Windows Insider Version 18999 and I'm downloading 19002.
Let me see if the update fixes the issue.

**Comment by amalshaji** [comment]
Updated to 19002. WSL2 working fine now. Please fix the issue on 18999.

**Comment by benhillis** [comment]
@amalshaji - We do not backport fixes to previous Windows Insider builds.

**Comment by nk521** [comment]
@benhillis  I'm on 19041 and still facing this issue 🤔

**Comment by Biswa96** [comment]
@nk521 If possible do a clean install of Windows, **not** from the backup or snapshot.
