### ISSUE TITLE
WSL2 On Windows 10 Home

### ISSUE THREAD

**Issue by brady-miller** [microsoft/WSL#4600]
I currently use wsl2 on my desktop with Windows 10 Pro, which works perfectly. However, when I am setting up wsl2 on my laptop (Win10 Home) I realized that wsl2 is using hyper-v, essentially making virtualbox impossible (unable to get it working with vbox 6). It's also impossible to use hyper-v for regular virtual machines, or docker for containers (requires win10 pro, or virtualbox which doesn't work). Esentially, wsl2 breaks every hypervisor, so you have no way of using any sort of virtual machines or containers besides the wsl2 machines unless you upgrade to pro. Are there any workarounds to this, or am I stuck just using my desktop for virtual machines/containers and any sort of pentesting (or I have to upgrade to win10 pro)? Doesn't seem right to prevent all virtualization just for an actual linux kernel.

**Comment by therealkenc** [comment]
VittualBox information can be found [here](https://forums.virtualbox.org/). Other questions about third-party VM solutions (every hypervisor) elsewhere on the web.

**Comment by brady-miller** [comment]
I know the virtualbox forums are there, and I have looked through them extensively because the docs are extremely sparse. Very few people were able to get it working with hyper-v, and no one really knows the requirements. Some people had success with 32 bit machines and 1 cpu, no hardware acceleration, but then it would freeze on boot. For me it just changed error messages, still crashing immediately. It's been an issue for 9+ months, but those are community forms with no developers.

I really want virtualbox to work as that is my preferred hypervisor, but unless someone knows of something I missed, not sure what more I can do. I have tried everything suggested in the forms, and anywhere I can find. Other vm solutions are the same, type 2 hypervisor does not work with type 1.

**Comment by Biswa96** [comment]
> I have looked through them extensively 

Did you see this? https://forums.virtualbox.org/viewtopic.php?f=6&t=90853&sid=f20b0f7f51e462005f9b3be80a567617&start=120#p453078

Try this command:

    VBoxManage setextradata global "VBoxInternal/NEM/UseRing0Runloop" 0

It works but very slow with type 2 hypervisor because type 1 is already in the chair.

**Comment by brady-miller** [comment]
Thank you! I'll try that now, I must have missed it.

I now remember I accidently got it working right when vbox 6 came out, because I was messing with hyper-v and saw the turtle icon, but never knew about hyper-v/virtualbox conflicts. Seems odd that I would have to do that (Supposedly no configuration) but ill see how it works.

Will post results soon.

**Comment by craigloewen-msft** [comment]
Virtual Box also added the ability to use Hyper-V as a fallback as of [Virtual Box 6.0.0](https://www.virtualbox.org/wiki/Changelog-6.0).

![image](https://user-images.githubusercontent.com/42221804/66953832-0e36df00-f014-11e9-8168-df3a4110c369.png)

So there is an immediate work around, and hopefully this performance can be increased in the future! :)

**Comment by brady-miller** [comment]
That is what I was referring to, the hyper-v fallback.

Suprisingly, I actually got it to book up and work. However, it seems the gpu capabilities are incredibly slow, as it takes 10 minutes for linux to reach the home screen. Trying out different acceleration seems to help some, but still unmanageable. Going to try this on my desktop and see if an ssd and much better hardware will help anything.

**Comment by brady-miller** [comment]
On my desktop it's much faster, and pretty usable. Somewhat slow bootup time, but I was still using an hdd (7200rpm vs 5400rpm). However, it only worked when the graphics controller was set to VBoxSVGA, and acceleration was enabled when possible. Continuing to optimize and figure out why its slow on laptop (wasn't slow prior to hyper-v)

**Comment by brady-miller** [comment]
At this point I have basically found that linux works well in this environment, not so much windows. I can get linux to boot up and work normally with minimal gui lag (besides startup), but I have been unable to get windows to boot whatsoever. I guess at this point I can use kali and metasploitable on my laptop, but for windows pentesting ill have to switch to use my desktop.

On the bright side, I think docker should be able to work now, thought I am not sure how this will work with wsl2, if at all (docker toolbox). 

If you guys have any ideas on how to fix windows with virtualbox/hyper-v, it would me much appreciated. :)
