### ISSUE TITLE
WSL2 Docker Service makes it unable to ping host machine

### ISSUE THREAD

**Issue by jaretscrews** [microsoft/WSL#4602]
Windows Version 10.0.18932.1000
Running sudo service docker start cause ping 172.17.212.79 (ip of host machine) to have 100% packet loss. I am still able to ping www.google.com.

**Comment by craigloewen-msft** [comment]
Hi @jaretscrews I'm not able to repro this issue on the latest build.

![image](https://user-images.githubusercontent.com/42221804/66954219-cebcc280-f014-11e9-9c10-676d67ab957c.png)

I'd recommend upgrading your Windows version and trying this again, please let me know if that resolves your problem!

**Comment by jaretscrews** [comment]
Hey, @craigloewen-msft I updated to 10.0.18999.1 and the issue persists. For some reason the ping is trying to go through my docker virtual network.
![Capture](https://user-images.githubusercontent.com/19211675/67012687-d4bbad80-f0bf-11e9-91c3-c1665fe09cdd.PNG)

**Comment by jaretscrews** [comment]
I had to remove WSL2 to go back to a VM as I had spent too much time on this issue.
