### ISSUE TITLE
Building Perl with Perlbrew fails? (Different issue in WSL2)

### ISSUE THREAD

**Issue by jacoby** [microsoft/WSL#4603]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.10022]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

\curl -L https://install.perlbrew.pl | bash
perlbrew install perl-5.30.0

* What's wrong / what should be happening instead:

It should build Perl 5.30 in ~/perl5/perlbrew/perls/perl-5.30.0/

It instead fails, leaving a log file in ~/perl5/perlbrew/build.perl-5.30.0.log

Link provided. https://gist.github.com/jacoby/e3823bc62804f49891d21c3c2d9045e8

Failed tests are at the end, starting with io/sem.t Non-zero exit status: 22

Looking for io/sem.t in the build log gets you this at line 4730

semctl not implemented at io/sem.t line 50.
semctl not implemented at io/sem.t line 27.
END failed--call queue aborted.

Looks like it needs and you don't provide the semctl system call.

http://man7.org/linux/man-pages/man2/semctl.2.html

I tried to add --force to the build and that failed, so looks like Perl can't be built without semctl.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by sirredbeard** [comment]
I was able to reproduce this on Ubuntu 18.04 and Debian buster.

**Comment by therealkenc** [comment]
> Looks like it needs and you don't provide the semctl system call.

No it's there all right; #3743 gets an (almost certainly) incorrect `EPERM` contrast `ENOSYS`. There's a hint above with "`Non-zero exit status 22` aka `EINVAL`". The `semctl` syscall doesn't like one of the params, and Perl likely interprets that as good as not implemented. An `strace(1)` log per skipped bullet point would show for certain, but academic. You'll find joy on WSL2.

**Comment by jacoby** [comment]
I thought I was, but it turns out I wasn't. Must be my other machine.

Will retry there. 

Thanks.

**Comment by jacoby** [comment]
I tried again.

PS C:\Users\jacob> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu          Stopped         2
  Ubuntu-18.04    Running         2

https://gist.github.com/jacoby/1939304409856bb2a14e51b2c3de7085

Specifically:

```text
Test Summary Report
-------------------
../cpan/IO-Socket-IP/t/31nonblocking-connect-internet.t          (Wstat: 29440 Tests: 8 Failed: 0)
  Non-zero exit status: 115
  Parse errors: No plan found in TAP output
Files=2648, Tests=1217571, 1052 wallclock secs (150.26 usr 22.76 sys + 620.36 cusr 80.75 csys = 874.13 CPU)
Result: FAIL
makefile:837: recipe for target 'test_harness' failed
make: *** [test_harness] Error 1
##### Brew Failed #####
```
But going to line 6159:

```text
../cpan/IO-Socket-IP/t/30nonblocking-connect.t ..................... ok
select() timed out at t/31nonblocking-connect-internet.t line 87.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 115 just after 8.
../cpan/IO-Socket-IP/t/31nonblocking-connect-internet.t ............ 
Dubious, test returned 115 (wstat 29440, 0x7300)
All 8 subtests passed 
```

That _might_ simply be bad tests written into IO::Socket::IP that interact poorly with WSL, so that going with --no-test gives me Perl, but I have built 5.30 on normal Ubuntu (16.04, sure) and if there was a problem, that _should_ have shown up somewhere else. A Perl that works but doesn't have TCP/IP, and thus no SMTP, no HTTP, etc, is not a Perl that works for me.

"All 8 subtests passed" yet still failing is not good.

**Comment by jacoby** [comment]
It's line 87 of this test:

https://metacpan.org/source/PEVANS/IO-Socket-IP-0.39/t/31nonblocking-connect-internet.t

And that's in this loop:

```perl
while( !$socket->connect and ( $! == EINPROGRESS || $! == EWOULDBLOCK ) ) {
      my $wvec = '';
      vec( $wvec, fileno $socket, 1 ) = 1;
      my $evec = '';
      vec( $evec, fileno $socket, 1 ) = 1;
 
      my $ret = select( undef, $wvec, $evec, 60 );
      defined $ret or die "Cannot select() - $!";
      $ret or die "select() timed out";
   }
 ```

So that should limit the range of weird interconnections involved.

**Comment by jacoby** [comment]
FWIW, I installed the Debian distro and tried again, and got the same 31nonblocking-connect-internet.t fail.

I tried installing the Alpine distro, but (problems unrelated to this issue).

I looked at Fedora, but that'd cost $6, and I'm not spending money to debug this issue.

I saw Kali, but it's another Debian-based distro, so that wouldn't help anything.

So hope that helps.
