### ISSUE TITLE
Python 3 crashes when trying to create a socket object via fileno parameter.

### ISSUE THREAD

**Issue by tonycosentini** [microsoft/WSL#4604]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.418] running WSL 1 with Ubuntu 18.04

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Creating a Python 3 socket via the fileno param does not work (I confirmed that this does work on an Ubuntu VM). Here's a sample script to reproduce the issue:

```
import os
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
print(f'Creating with fd: {sock.fileno()}')
sock_from_fd = socket.socket(family=-1, type=-1, proto=-1, fileno=sock.fileno())
```

To run this simply install Python 3 (I'm on 3.7.4) and then just run the sample script.

Some potentially useful context: I'm running into this crash when using [Gunicorn](https://github.com/benoitc/gunicorn).

* What's wrong / what should be happening instead: 

When running this, we end up with the following error:
```
Traceback (most recent call last):
  File "repro_socket.py", line 6, in <module>
    sock_from_fd = socket.socket(family=-1, type=-1, proto=-1, fileno=sock.fileno())
  File "/home/tonyc/.pyenv/versions/3.7.4/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 92] Protocol not available: 'protocol'
```

Ideally, this should not crash.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

https://gist.github.com/tonycosentini/bd3ab63595472be6cd67f5d01865a3d8

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
```
4313  socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 3
4313  write(1, "Creating with fd: 3\n", 20) = 20
4313  getsockname(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, [128->16]) = 0
4313  getsockopt(3, SOL_SOCKET, SO_TYPE, [1], [4]) = 0
4313  getsockopt(3, SOL_SOCKET, SO_PROTOCOL, 0x7fffd2fac240, [4]) = -1 ENOPROTOOPT (Protocol not available)
4313  write(2, "Traceback (most recent call last"..., 35) = 35
```

I think that's [here](https://github.com/python/cpython/blob/d565fb9828ee9c494bb7a80057a08e4738273e30/Modules/socketmodule.c#L5206).

Curiously no hits on `getsockopt ... SO_PROTCOL` variations, so this isn't likely a dupe. Which means nothing else of note takes a hard error on lack thereof.

Reasonable fix would be for that `else` to set `proto=0`, which is good enough for the `#ifdef SO_PROTOCOL` guard. 

One thing to try would be passing a sane family/type/proto to your test case and see if that goes down a different `cpython` path. I haven't tried, but I suspect it might. If the `-1/-1/-1` idiom were common there would have been more screeching. I can't believe no one has ever got a socket from a `fd` in the past and tripped this (but I've been surprised before).

Other options include WSL2, and prayer.

**Comment by therealkenc** [comment]
> One thing to try would be passing a sane family/type/proto to your test case

Moment of curiosity weakness while I'm failing miserably on something unrelated...

![image](https://user-images.githubusercontent.com/7049700/67131785-d9b15780-f1ba-11e9-8b27-89fa72f56dc3.png)

So there is your work-around. Still be worth a poke of the Python crowd, if you feel motivated. That fail path is gratuitous.

**Comment by mszhanyi** [comment]
I came across the same issue in WSL2 with the same script(main.py) #3935
