### ISSUE TITLE
PHP 7.3 Doesn't Connect to Host MySQL

### ISSUE THREAD

**Issue by MickSawy3r** [microsoft/WSL#4608]
**Please fill out the below information:**
* Your Windows build number:  18990.1

* What you're doing and what's happening:  
I'm Trying to Connect to MySQL, RabbitMQ, Jenkins and ElasticSearch Engine installed on Windows From WSL2 Kali Linux PHP7.3-FPM.

* What's wrong / what should be happening instead: Whats is Wrong is that?
when i try to connect to MySQL via IP From kali -- a simple mysqli_connect -- it just stands forever, doesn;t connect via localhost nor the host ip and doesn't connect no matter what, even though it connected in wsl1.
Note when i used nmap the connection was a success, MySQL in Particular seems to have a problem?!!

**Comment by AHPanna** [comment]
Hello @MickSawy3r,
did you try to edit the my.cnf file.
there is a config for mysql that others from outside of your network vm can connect, this is not the solution idk, but why not try :
i am using ubuntu 18 : mysql config
`sudo vim /etc/mysql/mysql.conf.d/mysqld.cnf`

and add the bind-address to 0.0.0.0 or your host machine who want to connect to this mysql :
![image](https://user-images.githubusercontent.com/4123487/67755231-0fb2cf00-fa38-11e9-87d9-c48f198dc355.png)
maybe this should help you.
