### ISSUE TITLE
Unable to install/enable Virtual Machine Platform

### ISSUE THREAD

**Issue by smare** [microsoft/WSL#4614]
I'm on build 19008.  Whenever I try to install/enable Virtual Machine Platform I get a green screen (attached).  I did not install either Windows Subsystem For Linux or Virtual Machine Platform prior to this attempt, on any previous versions of Windows - this is the first time.

I am able to successfully enable Windows Subsystem for Linux and install a distro.  It is only Virtual Machine Platform that causes the green screen.  I've updated all my drivers and there are no "!" alerts in Device Manager.  I've unplugged all peripherals.  Nothing seems to work.
![green-screen](https://user-images.githubusercontent.com/1779111/67414024-4304e200-f590-11e9-8969-c00b20342283.jpg)

**Comment by benhillis** [comment]
tmcomm.sys is not owned by Microsoft, it is the Trend Micro Internet Security driver by Trend Micro.

**Comment by smare** [comment]
You're right, my bad - I didn't see the "What failed" line.  I've disabled that, and now I get a green screen that does not have the line "What Failed", but the same Stop Code: PAGE_FAULT_IN_NONPAGED_AREA.  Like I mentioned, I've updated all my drivers and I have no alerts in device manager, so I'm stumped as to what else could cause this on my end.
![green-screen-1](https://user-images.githubusercontent.com/1779111/67418039-10f77e00-f598-11e9-84df-7c3e7cd8b3ee.jpg)

**Comment by therealkenc** [comment]
> I've disabled Trend Micro

Disabling generally has little effect on kernel drivers.

> would it make a difference if I tried booting into Safe Mode and installing it from there?

Dunno if WSL runs in safe mode. Even if it did, if WSL ran successfully, you'd learn: "there is some third-party thing installed in the kernel that is faulting". Which you already know.

**Comment by smare** [comment]
Thanks so much for the feedback, I sincerely appreciate it.  I'll get rid of Trend Micro and give it a shot!

**Comment by smare** [comment]
A quick follow-up: uninstalling Trend Micro fixed the issue.  I haven't tried reinstalling Trend Micro yet.
