### ISSUE TITLE
WSL2 on Surface Laptop 3 AMD

### ISSUE THREAD

**Issue by khuongduybui** [microsoft/WSL#4615]
As directed on https://docs.microsoft.com/en-us/windows/wsl/wsl2-install, I installed WSL 1 and 2 with the following command as Administrator:
```
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

I then installed Ubuntu from Microsoft Store and ran it successfully.
When I try to convert it to v2 with `wsl --set-version Ubuntu 2`, I got the following error:

```
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
```

**Comment by drescherjm** [comment]
Did you do as it says? Or can't you get into the bios?

**Comment by khuongduybui** [comment]
The UEFI for Surface Laptop does not have any option to toggle virtualization support

**Comment by khuongduybui** [comment]
I figured out what the problem is. VirtualMMachinePlatform was not installed correctly. I removed it and reinstalled and solved the problem.

As for the UEFI not having an option to toggle virtualization support, I was able to just open Task Manager / Performance tab and _see_ (not change) that Virtualization is enabled for my CPU.
Rhanks @drescherjm for your assistance.
