### ISSUE TITLE
Can't start the bash right after install. Cannot create the first username

### ISSUE THREAD

**Issue by suoko** [microsoft/WSL#4616]
Installing, this may take a few minutes...
Access is denied.
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: tt
Access is denied.
Enter new UNIX username: sadf
Access is denied.
Enter new UNIX username:

check the logs:
[Dell.zip](https://github.com/microsoft/WSL/files/3767486/Dell.zip)

**Comment by benhillis** [comment]
@suoko - Looks like calling into the driver is failing with access denied.  One thing that can cause this is various code integrity policies. Do you know if your configuration has any of those enabled?

**Comment by suoko** [comment]
> @suoko - Looks like calling into the driver is failing with access denied. One thing that can cause this is various code integrity policies. Do you know if your configuration has any of those enabled?

I don't think that's the root cause, since other users in the company, who are joined to the same domain and with less priviledged accounts, happily use wsl2

**Comment by okainov** [comment]
Any update on this one, I have the same issue (corporate environment)

**Comment by Droid-** [comment]
Friendly ping on this one. I'm seeing it too and I'm not on a corporate machine.

**Comment by lggomez** [comment]
I'm also having this problem con windows 10 enterprise (build 17763)

**Comment by okainov** [comment]
@therealkenc  any reason why is this closed?

**Comment by therealkenc** [comment]
Died on needs-attention tag but you're right if there was something in the logs I'll re-tag it for now.

**Comment by sryze** [comment]
Same issue with Ubuntu 20.04 on WSL 1
