### ISSUE TITLE
vmwp process is running after uninstalling a distribution

### ISSUE THREAD

**Issue by Biswa96** [microsoft/WSL#4617]
* Windows Version: 10.0.19008.1

* Procedure: 

  - Shutdown WSL2 VM: `wsl --shutdown`
  - Install any distribution: `wsl --import test .\ test.tar.gz --version 2`
  - Run the distribution: `wsl -d test`
  - Exit from it with Ctrl+D.
  - Uninstall the distribution: `wsl --unregister test`
  - See Task Manager, `vmwp.exe` process is running also with `vmmem` minimal process.

* Question: Shouldn't the `vmwp.exe` process be terminated after uninstalling the _previously running_ distribution?

**Comment by benhillis** [comment]
By design. We keep the VM running for about 1 minute after your last distro exits in case you do another operation.
