### ISSUE TITLE
Cannot install any distributions, WslRegisterDistribution failed with error: 0x80070002

### ISSUE THREAD

**Issue by owenworley** [microsoft/WSL#4618]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
C:\Users\owen>ver
Microsoft Windows [Version 10.0.18362.10024]
```

* What you're doing and what's happening:
```
C:\Users\owen>wslconfig /list /all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

C:\Users\owen>ubuntu1804
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```

* What's wrong / what should be happening instead:
```
I cannot install any distributions of Linux on Windows. 
I should be able to install Ubuntu or any other distributiuon.

I have tried the following suggestions already but they have not helped:

- Uninstall WSL feature, reboot, reinstall WSL feature, reboot
- Uninstall and reinstall (between reboots) all distributions of linux from the 
Windows Store, they all show the same error 0x80070002
- I have made sure windows content is set to install to C:\
- I have tried running "sfc /scannow" and rebooting
- I have tried running "DISM /Online /Cleanup-Image /Scanhealth" and 
nothing bad was reported
```

* Strace of the failing command, if applicable:
```
I cannot strace as I am not using WSL yet.
```
* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
```
I have attached `lxcore_kernel.etl` `lxcore_service.etl` `lxcore_user.etl` here:
```
[lxcore_logs.zip](https://github.com/microsoft/WSL/files/3770580/lxcore_logs.zip)

**Comment by benhillis** [comment]
Thanks for the trace.  We are attempting to open the "nul" device and that is failing with ERROR_FILE_NOT_FOUND.  Do you have any third party AV or software that could explain this?

**Comment by owenworley** [comment]
I use BitDefender and Malware Bytes. I have tried compeltely disabling these but it doesn't make a difference.

**Comment by owenworley** [comment]
` We are attempting to open the "nul" device`

Genius!

I found the solution. A while back, I was having issues with my non-paged memry pool growing massively over time (usingup to my entire 32gb of ram). At the time, I was suggested to try a nuber of things, including setting the following reg key:
Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Null\Start to 4
And disabling the null service (sc config Null to disable and not start)

I just changed that reg key backl to 4, and ran from an elevated prompt:
`sc config Null start= system`
`sc start Null`

And now I just successfully installed Ubuntu and it works fine.

When I read you saying about 'nul' i immediately tried running `echo hello> nul` and saw the same message `The system cannot find the file specified.`

After reenabling the null service, i can run `echo hello > nul` with no errors.

Excellent! Than you so much for pointing me on the right track.

It might be useful though, for wsl to state the file that it cannot open in these cases, because if I had seen a message earlier like `Failed to open 'nul'. The system cannot find the specified file` I would have been able to self diagnose this months ago.

**Comment by spaceraccoon** [comment]
Hi @benhillis, could I know how you analyzed the log files to figure out the missing file? I'm trying to figure out a similar error for me. #5107

**Comment by HItzz07** [comment]
Used this "wsl --set-default-version 1" , 
It worked for me.

**Comment by pereirajo** [comment]
After a few years, I had the same problem, that was just the problem...
