### ISSUE TITLE
Documentation: make explicit how distros run as containers under a single kernel

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4622]
**Is your feature request related to a problem? Please describe.**

I've either had or seen a few awkward-to-track-down issues arising from this: one being that kernel threads aren't shown by `ps(1)` or otherwise inspectable from a WSL distro (see #4425 for an example); kernel threads not sharing an identical understanding of the filesystem with a given distro (also #4425); `auditd(8)` not functioning under WSL since a contained process cannot adjust the kernel audit enable flag; et. sim.

**Describe the solution you'd like**

All of these are in themselves relatively minor (or at least niche) issues when they cannot be worked around, but it would be useful to have this part of the architecture explicitly described in the documentation to avoid the debugging and hunting through the issue tracker to figure out what's going on.

**Describe alternatives you've considered**

Well, y'all could entirely redesign WSL 2 to work on a one-kernel-per-distro model, but that seems a mite excessive for this. 😄

**Comment by Biswa96** [comment]
Same question: How docker can run multiple container with one host kernel?

**Comment by therealkenc** [comment]
There is no repro on "cannot adjust the kernel audit enable flag; et. sim" provided. For documentation improvements: [here](https://github.com/MicrosoftDocs/WSL).

**Comment by cerebrate** [comment]
@therealkenc 

```
❯ sudo auditctl -e 1
Error sending enable request (Operation not permitted)
[1]    21673 exit 255   sudo auditctl -e 1

❯ sudo auditctl -s
Error sending status request (Operation not permitted)
[1]    21741 exit 255   sudo auditctl -s
```

But seriously, do we really need repro cases for one-of-various examples of already documented limitations? People can easily look up whatever limitations, etc., are related to being in the WSL container _if they know that they're in one_ , which for this issue is the thing and the whole of the thing.

**Comment by therealkenc** [comment]
Can't repro here with the steps provided. I get:
```
$ sudo auditctl -e 1
ken@DESKTOP-BNN97ME:/mnt/c/Users/there$ sudo auditctl -e 1
Error - audit support not in kernel
Cannot open netlink audit socket
```
Naturally because:
```
ken@DESKTOP-BNN97ME:/mnt/c/Users/there$ cat /proc/config.gz | gunzip | grep CONFIG_AUDIT
# CONFIG_AUDIT is not set
```
Which does not require WSL documentation, because the behavior is not WSL specific and is documented widely. Any kernel with `CONFIG_AUDIT=n ` will return that error.

> But seriously, do we really need repro cases

Yes seriously, if one is submitting a bug report (or more recently) a feature request. Otherwise there would be absolutely no way to turn the request into an actionable, and eventually the issue gets closed or at best goes chirping crickets if no one gets around to closing it.

Would `CONFIG_AUDIT=y` be a reasonable feature request? Dunno. Depends on the use case demonstrated in the CLI repro, and the number of thumbs up on the OP, mostly. As of this writing such a request would not be a dupe AFAICT.

**Comment by cerebrate** [comment]
Which would be fine if this feature request was actually _related_ to CONFIG_AUDIT/auditd (or the kernel threads, or any of the other behaviors ) in any way other than them being an example. Talking about or reproing any of those particular cases is a distraction from the substance of the issue, namely that this particular detail of the WSL architecture makes it behave in ways (1) different from a "generic" Linux installation when you use certain programs and enable certain kernel features, and these ways are unexpected if you don't know what's going on under the hood. And hence it would be useful to have that in the docs.

I have no idea how one would even write a repro case for that - "Install a WSL distro. Attempt to run everything. Note that some things with documented or undocumented, explicit or implicit, expectations of running outside any user namespaces behave in unexpected ways." - nor, for that matter, can I see the problem in turning "Please document this particular item." into an actionable.

1. Ways which are spread out across a whole variety of kernel features and user programs and as such properly documented there, rather than trying to cram details into the WSL docs beyond "your distro is in a container and behaves as such".
