### ISSUE TITLE
[User Question | Feature Request] Rename "wsl$\old" to "wsl$\new" in the terminal

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/WSL#4624]
I refer to https://github.com/microsoft/WSL/issues/4241. 

**Is your feature request related to a problem? Please describe.**
I made a mistake, naming the distro imported from `wsl` in the terminal. I did not find the option of renaming the imported distro attached to network `wsl$`.

**Describe the solution you'd like**
To be able to rename the imported distro with a new name, using the command `wsl`:

```
wsl -d Gefuntoo --rename Funtoo
```

**Comment by craigloewen-msft** [comment]
Thank you for the request!

In 1903 we added the ability to export a distro and import a distro.

Would exporting you distro and then importing it back under a different name work as a solution for you?

**Comment by gusbemacbe** [comment]
@craigloewen-msft 

> In 1903 we added the ability to export a distro and import a distro.
> Would exporting you distro and then importing it back under a different name work as a solution for you?

Exporting, unregistering the imported distro and importing take a lot of time. Renaming the imported distro is quick.

**Comment by CryptoSiD** [comment]
Closing this without implementation is frustrating — this is a 7-year-old request for what amounts to a single registry key update under HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\<guid>\DistributionName.

The syntax should be straightforward: wsl -d Gefuntoo --rename Funtoo

Instant, zero-cost, no data movement. The current workaround requires exporting and reimporting the entire distro, copying potentially hundreds of GBs of vhdx data just to change a name in a registry entry.

This was closed the same day it was opened with barely any community engagement. Closing the issue doesn't make the need go away.
