### ISSUE TITLE
[wsl2]no modules or vmlinuz available for the reported kernel version

### ISSUE THREAD

**Issue by catalin-h** [microsoft/WSL#4625]
After upgrading my Ubuntu to WSL2 (insider preview + fast ring) I've noticed that there are no kernel modules for the reported kernel version. However, the old modules and vmlinuz image are still present. I was expected to find the kernel modules for the current running kernel version.

Details:
- Windows version / build number :  10.0.19008.1000
- Linux: Ubuntu
```
C:\>wsl -l -v
  NAME      STATE           VERSION
 * Ubuntu    Running         2
```
- reported kernel version
```
~$ uname -r
4.19.75-microsoft-standard
```
- actual found modules and vmlinuz 
```
~$ ls -alh /boot
total 49M
drwxr-xr-x  3 root root 4.0K Apr 21  2019 .
drwxr-xr-x 24 root root 4.0K Oct 28 21:19 ..
-rw-r--r--  1 root root 187K Mar 26  2019 config-4.4.0-145-generic
drwxr-xr-x  2 root root 4.0K Apr 21  2019 grub
-rw-r--r--  1 root root  38M Apr 21  2019 initrd.img-4.4.0-145-generic
-rw-------  1 root root 3.8M Mar 26  2019 System.map-4.4.0-145-generic
-rw-------  1 root root 6.9M Mar 27  2019 vmlinuz-4.4.0-145-generic
```
```
~$ ls /lib/modules/
4.4.0-145-generic
```
- expected: kernel modules & vmlinuz image for the current reported kernel version: 4.19.75

**Comment by 0xbadfca11** [comment]
Those ``*-4.4.0-145-*`` are what you installed.
Ubuntu's rootfs tar ball contains empty ``/boot`` and empty ``/lib/modules``.

Kernel is here.
``C:\Windows\System32\lxss\tools\kernel``

Modules does not exist.
```bash
$ zgrep '=m' /proc/config.gz
$ 
```

If want to use a custom kernel or kernel modules you can compile from this source tree.
https://github.com/microsoft/WSL2-Linux-Kernel
https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18945

**Comment by therealkenc** [comment]
That's correct. You aren't running Ubuntu's `4.4.0-145-generic` kernel on WSL.
