### ISSUE TITLE
WSL symbolic linked folders are owned by root

### ISSUE THREAD

**Issue by pmonty** [microsoft/WSL#4627]
* **Windows Version:**
Microsoft Windows [Version 10.0.18362.449]

* **What you're doing and what's happening:** 
```js
ln -s /mnt/c/Projects
ls -al ~/Projects/test
```

* **What's wrong / what should be happening instead:**
Everything is owned by `root:root` and doing `sudo chown -R pmonty:pmonty .` does nothing.

I installed WSL and set it up maybe a week ago and done everything exactly the same way (order and everything). But after a fresh install of WSL now I find that this issue has appeared. Don't recall if it wasn't `root:root` previously but don't see why it should be.

Main reason i discovered this is because i created the symlink then went into a project to run `npm install formik` and it was complaining about permissions. Also some issues with installing globally too.

_**EDIT/UPDATE:**_

If i `ls -al /mnt/c/Test` then that is owned by pmonty:pmonty but not the link for some reason. Really strange

**Comment by pmonty** [comment]
Not sure what the fix was. I did add some config to a /etc/wsl.conf that didn't exist. Maybe restarted terminal a few times. But whatever it is working now after some re cloning and remaking of links. I have another system I plan to enable WSL on so might see if anything happens on that.

**Comment by gusbemacbe** [comment]
@pmonty 

Can I know what you added in the file `/etc/wsl.conf`?

**Comment by yithian** [comment]
I ran into this rebuilding my wsl environment and found this issue trying to fix it. In case it helps anyone else, here's what I did:

### set up /etc/wsl.conf
open up `/etc/wsl.conf/` in an editor with this contents:
> [automount]
> enabled = true
> options = "metadata,umask=22,fmask=11"

### restart wsl
in _powershell_ run `wsl --shutdown`

when you start wsl back up, the permissions should be right

**Comment by BPowell76** [comment]
This doesn't do anything in WSL 2. I even changed the permissions on `/etc/fstab` to use my uid/gid.
