### ISSUE TITLE
WSL 2 not running after restoring after entering sleep (error code: 0xffffffff)

### ISSUE THREAD

**Issue by rkttu** [microsoft/WSL#4628]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number: 10.0.19013.1

* What you're doing and what's happening: 
1. Launch WSL 2 first
2. Launch Docker Desktop 2.0 as a Windows Container mode
3. Enter sleep mode
4. Leave sleep mode
5. WSL 2 fails with 0xffffffff error code

* What's wrong / what should be happening instead:
I think that WSL 2 should run well regardless of conditions.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

[lxcore.zip](https://github.com/microsoft/WSL/files/3788831/lxcore.zip)

**Comment by benhillis** [comment]
@rkttu - Thanks for posting, if you are still able to hit this, would you possibly be able to collect a trace using [Feedback Hub](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs)?

**Comment by rkttu** [comment]
@benhillis Thanks for the suggestion. As the build of Windows 10 continues to upgrade, I think the problem might go away one day.

But the problem I'm having isn't a networking issue. I would be grateful if you could let me know the criteria to share what I'm posting on Github issues with what I'm posting on the Feedback Hub.

**Comment by benhillis** [comment]
When I looked at your trace the error is coming from the creation of our virtual network so the network traces will likely have more info.

**Comment by rkttu** [comment]
Then I will send the log to the feedback hub and close this issue. Thank you for the suggestion.
