### ISSUE TITLE
(Maybe) Wrong default permission for "/dev/net/tun"

### ISSUE THREAD

**Issue by karuboniru** [microsoft/WSL#4629]
* Your Windows build number:  10.0.19013.1

* What you're doing and what's happening:  
`slirp4netns` needs to use `/dev/net/tun` to set up network for a `libpod` container. But default permission for `/dev/net/tun` is 
```
[yan@BOOK-KARUBONIRU ~]$ ll /dev/net/tun
crw------- 1 root root 10, 200 10月 30 20:35 /dev/net/tun
```
Because of that, I need to run `sudo chmod 666 /dev/net/tun` to make everything work as it like in Linux Host.

* What's wrong / what should be happening instead:
When doing the same in a `Fedora 31` machine 
```
[root@yan ~]# ll /dev/net/tun
crw-rw-rw-. 1 root root 10, 200 10月 28 15:02 /dev/net/tun
```
According to [Kernel Documentation For tuntap](https://www.kernel.org/doc/Documentation/networking/tuntap.txt): 

>  There's no harm in allowing the device to be accessible by non-root users, since CAP_NET_ADMIN is required for creating network devices or for connecting to network devices which aren't owned by the user in question.

So, please set default permission for `/dev/net/tun` to `666` instead of `600`.

**Comment by benhillis** [comment]
Fixed in [19028](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19028).

**Comment by karuboniru** [comment]
Thanks, everything works good now!
