### ISSUE TITLE
Problem with chrome/chromedrive when using Python Selenium under Windows WSL

### ISSUE THREAD

**Issue by k-ji** [microsoft/WSL#4631]
i followed [this thread](https://github.com/microsoft/WSL/issues/648), but couldn't get it working..

Error:

selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=78.0.3904.70)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-18362-Microsoft x86_64)UDEV STUB: Using libudev-stub 0.9.0

Plus, start getting this after every apt command:
UDEV STUB: Using libudev-stub 0.9.0

**Comment by therealkenc** [comment]
#646 has been obsolete for quite some time now; you don't want udev-stub. For questions, you'll generally get more eyeballs in a question/discussion forum like reddit or serverfault.
