### ISSUE TITLE
cmd.exe on tmux on WSL freezed

### ISSUE THREAD

**Issue by aont** [microsoft/WSL#4635]
## Issue Reproduction
cmd.exe on tmux on WSL gets freezed.

I open a tmux session, where cmd.exe is running.
```sh
>wsl
$ tmux
$ cmd.exe
>
Ctrl+B D to detach
$ exit
```
Next, I reopen tmux.
```sh
>wsl
$ tmux a
>
```
I see the previous cmd.exe terminal.
But, any input to cmd.exe is ignored ( though input to tmux is valid for example Ctrl+B & to kill ) .
If this is a bug of tmux, then please let me know. I will post this issue on tmux repos.

Windows: Windows 10 Home 1903 18362.418
Linux: https://lxrunoffline.apphb.com/download/Ubuntu/bionic
tmux: 2.6-3ubuntu0.2

**Comment by aont** [comment]
Following is the strace output of cmd.exe. 

Before exiting WSL
```
execve("/mnt/c/Windows/system32/cmd.exe", ["cmd.exe"], 0x7fffd991ba88 /* 18 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x293820)       = 0
set_tid_address(0x293858)               = 78
brk(NULL)                               = 0x1cb6000
brk(0x1cb7000)                          = 0x1cb7000
sched_getaffinity(0, 128, [0, 1, 2, 3]) = 64
uname({sysname="Linux", nodename="DESKTOP-IIUBDHU", ...}) = 0
getpid()                                = 78
getcwd("/mnt/c/Users/aont/strace", 4096) = 26
open("/dev/lxss", O_RDWR)               = 3
ioctl(3, _IOC(0, 0, 0x2f, 0x22), 0x7fffddd2ac28) = 0
getcwd("/mnt/c/Users/aont/strace", 4096) = 26
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - wslfs r"..., iov_len=1024}], 2) = 867
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
getcwd("/mnt/c/Users/aont/strace", 4096) = 26
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - wslfs r"..., iov_len=1024}], 2) = 867
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGPGRP, [76])               = 0
getpgid(0)                              = 76
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=43, ws_col=168, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 -opost -isig -icanon -echo ...}) = 0
dup(0)                                  = 5
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffddd2abd8) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffddd2abd8) = 0
ioctl(4, _IOC(0, 0, 0xb7, 0x22), 0x7fffddd2abd8) = 0
write(4, "\0\0\0\0\260\0\0\0005\1\0\0\0\0\0\0006\1\0\0\0\0\0\0007\1\0\0\0\0\0\0"..., 176) = 176
close(0)                                = 0
close(1)                                = 0
close(2)                                = 0
rt_sigprocmask(SIG_BLOCK, [INT WINCH], NULL, 8) = 0
signalfd4(-1, [INT WINCH], 8, 0)        = 0
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
read(4, "\10\0\0\0 \0\0\0\0\0\0\0\0\0\0\0008\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
ioctl(4, _IOC(0, 0, 0xa3, 0x22), 0x7fffddd2abf8) = 0
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLHUP}])
```

After exiting WSL
```
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLHUP}])
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLHUP}])
poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLHUP}])
... infinite
```

**Comment by benhillis** [comment]
@aont - I cannot reproduce this on 19013.

**Comment by aont** [comment]
@benhillis - I see. Since I don't use preview release, I cannot confirm. But somehow this is fixed on the next release. Thank you!

**Comment by aont** [comment]
I can reproduce this even on Windows 11 Pro 25H2 (26200.8875) WSL1.
When I use this workaround [aont/tmux-wsl-workaround](https://github.com/aont/tmux-wsl-workaround/) , this issue is avoided.

**Comment by aont** [comment]
## Investigation Results by ChatGPT 5.6 Pro

**The cause is not tmux. Rather, it is that the lifetime of WSL1's Windows executable interoperability mechanism—the interop server provided by `wsl.exe` / `wslhost.exe`—is tied to the Windows-side console that initially created the tmux server.**

When the original terminal is closed, the Linux-side tmux server and PTY remain alive. However, the Windows-side interop host or interop endpoint used by that tmux server is terminated or invalidated, causing only programs such as `cmd.exe` to stop responding.

## `cmd.exe` on WSL Is Not an Ordinary PTY Process

Linux programs generally follow a path like this:

```text
tmux server
  └─ Linux PTY
      └─ bash / vim / other Linux processes
```

By contrast, `cmd.exe` is launched through a path like this:

```text
tmux server
  └─ Linux PTY
      └─ /init (binfmt interpreter)
          └─ WSL interop server
              └─ Windows-side wsl.exe / wslhost.exe
                  └─ CreateProcess(cmd.exe)
```

Current WSL technical documentation explains that when launching a Windows executable, Linux-side `/init` connects to the server at `/run/WSL/*_interop` specified by `$WSL_INTEROP`. This server communicates with `wsl.exe` or `wslhost.exe`, creates the Windows process, and relays standard input/output. In WSL1, `LxInitMessageCreateProcess` is used. ([WSL][1])

Furthermore, the published source code shows that the interop worker obtains Linux-side stdin/stdout/stderr as Windows handles and, after launching the Windows process, maintains a control channel for handling signals, exit status, terminal resize events, and so on. In other words, `cmd.exe` does not operate solely through tmux's PTY; the Windows-side interop worker must remain alive. ([GitHub][2])

## What Happens During a Normal Launch

Under normal circumstances, the state is conceptually as follows:

```text
Windows Terminal A / Console A
├─ wsl.exe A
├─ wslhost.exe A
│   └─ interop endpoint A
└─ Linux shell
    └─ tmux server
        └─ pane
            └─ /init → interop endpoint A → cmd.exe
```

The tmux server inherits interop endpoint A from the initial shell.

If another terminal is then opened and attached, the state becomes:

```text
Windows Terminal B
└─ wsl.exe B
    └─ tmux client
        ── tmux socket ──> existing tmux server
                              └─ still using interop endpoint A
```

Attaching replaces only the **tmux client and display terminal**.

It does not replace:

* the tmux server process
* processes in existing panes
* `$WSL_INTEROP` inherited by the panes
* the Windows-side worker managing an already-running `cmd.exe`
* Windows-side standard I/O and control channels

Therefore, even if the new `wsl.exe B` has a valid interop server, existing panes and already-running `cmd.exe` processes are not automatically migrated to it.

## The Immediate Failure Point Is the Lifetime of the Windows-Side Console

The current `wslhost.exe` source contains logic that almost directly explains this phenomenon.

Before starting interop processing, the current `wslhost.exe` creates a dedicated Windows console. Comments in the source explain, in substance, that:

* interop requires a console
* `wslhost.exe` must not be attached to the same console as `wsl.exe`
* if they share the same console, closing that console also terminates `wslhost.exe`
* as a result, interop can no longer be provided to daemonized Linux processes

Furthermore, `wslhost.exe` waits for its parent `wsl.exe` to terminate before starting the interop worker loop.

This describes exactly the following failure mode:

```text
the tmux server remains alive
but the interop host dies together with the original console
as a result, only Windows executables break
```

In the 2019 WSL1 environment, the mitigation used today—ensuring that `wslhost.exe` has a reliably independent console—was likely not yet sufficient, or did not properly isolate it under certain launch configurations.

## Why `cmd.exe` Appears to "Freeze" Instead of Exiting

An already-running `cmd.exe` has a worker thread and control pipe allocated within the interop host. If the original console is closed and that host terminates, one of the following may occur:

1. The Windows-side `cmd.exe` terminates, but the Linux-side `/init` shim never receives the exit notification and continues waiting.
2. Only the standard-input relay is lost, leaving `cmd.exe` or the shim waiting indefinitely for input.
3. The Windows-side process has terminated, but tmux continues displaying the last prompt it rendered.

In the current code, if the interop control pipe is disconnected, non-GUI Windows processes are terminated. In older WSL1 versions, the exit status may not have been fully propagated or the Linux-side shim may not have been released correctly, resulting in a state where "the prompt remains visible, but input is ignored." ([GitHub][2])

Indeed, in the original report, only input to `cmd.exe` is ignored while tmux key operations continue to work. This indicates that the Linux-side PTY and tmux server are functioning normally and only the Windows interop side has failed. ([GitHub][3])

## The Behavior Follows the Terminal That Created the tmux Server

Another WSL1 report describes the following controlled experiment:

* If the tmux server is created from a local WSL shell, Windows executables work even when attaching through mosh.
* If the local shell that originally created that tmux server is closed, Windows executables also hang on the mosh side.
* Conversely, if the tmux server is created from the mosh side, Windows executables do not work even when attaching from the local side.

In other words, the behavior follows not "where you are currently attaching from," but the **WSL client / interop context in which the tmux server was created**. This strongly indicates that the cause is not the tmux client or terminal emulator, but rather the interop context inherited when the server was created. ([GitHub][4])

## Why the Workaround Fixes It

When creating a new tmux server, the workaround essentially performs the following:

```text
current WSL
└─ cmd.exe /c start "" /min
    └─ new wsl.exe B
        └─ tmux new-session -d
            └─ tmux server
```

The original terminal then attaches using the session ID received through a FIFO:

```text
original terminal
└─ tmux attach-session -t <session-id>
```

The implementation and README explicitly describe this structure: a new server is created through "another, minimized Windows-side `wsl.exe` launch," after which the original terminal attaches to it. ([GitHub][5])

`cmd.exe`'s `start` command starts a separate Command Prompt window to run the specified program. `/min` minimizes that new window. Because `/b` is not used, it is not launched within the original console. ([Microsoft Learn][6])

Thus, after applying the workaround, the conceptual state is:

```text
Console A: terminal operated by the user
└─ tmux client

Console B: independent console created by start /min
└─ wsl.exe B / wslhost.exe B
    └─ interop endpoint B
        └─ tmux server
            └─ cmd.exe
```

If the user closes Console A, Console B and its `wslhost.exe B` remain unaffected. As a result, the tmux server's interop endpoint and the I/O path for Windows executables launched through it remain intact.

### The Essential Part

The role of each element of the workaround is as follows:

| Element               | Role                                                                       |
| --------------------- | -------------------------------------------------------------------------- |
| `cmd.exe /c start`    | Creates a launch independent of the original Windows console               |
| `/min`                | Minimizes the dedicated console so it remains unobtrusive                  |
| second `wsl.exe`      | Creates a dedicated interop context for the tmux server                    |
| `tmux new-session -d` | Creates the server within that dedicated context                           |
| FIFO                  | Merely returns the session ID and exit status to the original WSL instance |
| `attach-session`      | Connects the original terminal purely as a tmux client                     |

Therefore, neither the FIFO nor the session ID is what fixes the problem. **The actual fix is creating the tmux server in a separate Windows console / WSL launch from the original interactive console.**

## Updating `$WSL_INTEROP` Alone Does Not Fully Fix the Problem

If the new `$WSL_INTEROP` is set on the tmux server after attaching, it may in some cases improve only the ability to "launch Windows executables in newly created panes from this point onward."

However, it cannot repair:

* an already-running `cmd.exe`
* an `/init` process that has already established an interop connection
* a worker thread that has disappeared
* standard I/O handles that have already been disconnected
* the environment of existing pane processes
* Windows processes belonging to the original host

Therefore, updating the environment variable is not equivalent to the workaround. The workaround creates the tmux server under a long-lived interop host from the outset.

## How to Verify It

On builds where `$WSL_INTEROP` is visible, you can compare tmux launched normally with tmux launched through the workaround:

```sh
printf 'current shell: %s\n' "$WSL_INTEROP"
tmux show-environment -g WSL_INTEROP
```

To inspect the shell PID of a pane and verify the value it actually inherited:

```sh
pane_pid=$(tmux display-message -p '#{pane_pid}')
tr '\0' '\n' < "/proc/$pane_pid/environ" | grep '^WSL_INTEROP='
```

After closing the original terminal, inspect the stored socket:

```sh
interop_path=$(
    tr '\0' '\n' < "/proc/$pane_pid/environ" |
    sed -n 's/^WSL_INTEROP=//p'
)

printf '%s\n' "$interop_path"
ls -l "$interop_path"
```

If the socket disappears or becomes unreachable on the normal path but remains available when using the workaround, this directly confirms that the issue concerns the lifetime of the interop endpoint.

On the Windows side, observing the following processes with Process Explorer or a similar tool can make the behavior even clearer:

```text
wsl.exe
wslhost.exe
conhost.exe
cmd.exe
```

On the normal path, closing the original terminal should cause the corresponding `wslhost.exe` or console association to disappear. With the workaround, the host associated with the separate minimized console should remain alive.

## Confidence

Microsoft Issue #4635 does not contain a published detailed RCA, and `Lxcore.sys`, the WSL1 kernel-side implementation used in Windows 10 1903, remains closed source. Therefore, public information alone is insufficient to determine whether the specific object ultimately destroyed is the `ServerPortHandle`, console handle, job, accepted message port, or something else. ([Microsoft Learn][7])

However, the following conclusions can be drawn with high confidence:

1. The failure is in the WSL interop layer, not tmux's PTY.
2. The interop context originates from the initial WSL launch that created the tmux server.
3. Closing the original Windows console causes that interop host or connection to be lost.
4. Reattaching does not migrate the interop context.
5. The workaround creates a dedicated minimized console and a separate `wsl.exe` launch, thereby isolating the tmux server's interop host from the interactive terminal.
6. The current WSL source even contains a mitigation comment matching this phenomenon: if `wslhost` is attached to the same console as `wsl.exe`, terminating the console prevents it from continuing to provide interop to daemonized processes.

In short, this workaround is effective **not because it "starts tmux in another process," but because it gives the WSL interop host on which tmux depends a Windows console lifetime separate from the terminal that the user closes.**

[1]: [https://wsl.dev/technical-documentation/interop/]\(https://wsl.dev/technical-documentation/interop/\) "Interop - WSL"
[2]: [https://raw.githubusercontent.com/microsoft/WSL/master/src/windows/common/interop.cpp]\(https://raw.githubusercontent.com/microsoft/WSL/master/src/windows/common/interop.cpp\) "[https://raw.githubusercontent.com/microsoft/WSL/master/src/windows/common/interop.cpp](https://raw.githubusercontent.com/microsoft/WSL/master/src/windows/common/interop.cpp)"
[3]: [https://github.com/microsoft/WSL/issues/4635]\(https://github.com/microsoft/WSL/issues/4635\) "[https://github.com/microsoft/WSL/issues/4635](https://github.com/microsoft/WSL/issues/4635)"
[4]: [https://github.com/microsoft/WSL/issues/5146]\(https://github.com/microsoft/WSL/issues/5146\) "[https://github.com/microsoft/WSL/issues/5146](https://github.com/microsoft/WSL/issues/5146)"
[5]: [https://github.com/aont/tmux-wsl-workaround]\(https://github.com/aont/tmux-wsl-workaround\) "[https://github.com/aont/tmux-wsl-workaround](https://github.com/aont/tmux-wsl-workaround)"
[6]: [https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start]\(https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start\) "start | Microsoft Learn"
[7]: [https://learn.microsoft.com/en-us/windows/wsl/opensource]\(https://learn.microsoft.com/en-us/windows/wsl/opensource\) "[https://learn.microsoft.com/en-us/windows/wsl/opensource](https://learn.microsoft.com/en-us/windows/wsl/opensource)"

**Comment by aont** [comment]
Similar (same?) report: #4858 #11258 #5057 #4858 #1944 #3930

**Comment by aont** [comment]
For those attempting to reproduce this:
Please follow the Issue Reproduction steps **exactly**.
- Open a WSL shell with `wsl -d {distro}`
- Open tmux with `tmux new-session`
- Start cmd.exe with `/mnt/c/windows/system32/cmd.exe`
- While leaving cmd.exe running, detach tmux with Ctrl+B D without exiting cmd.exe.
- Exit WSL with `exit`
- **Close the PowerShell or cmd.exe window that was used to start WSL**.
- **Open a different PowerShell or cmd.exe window**.
- Open a WSL shell with `wsl -d {distro}`
- Attach to the session with `tmux attach`
- You will see the cmd.exe screen. Try typing something.

**Comment by aont** [comment]
I had AI consider a proposed fix and implement it. I don’t have time to test or debug it myself, so if anyone’s interested, feel free to give it a try: [aont/WSL](https://github.com/aont/WSL/tree/service-owned-interop-broker)
