### ISSUE TITLE
cmd.exe /c "echo hello" yields no visible output on tty

### ISSUE THREAD

**Issue by therealkenc** [microsoft/WSL#4637]
> * What you're doing and what's happening

Output from `cmd.exe` (and probably else) doesn't make it to the tty. Repro:
```
$ cd /mnt/c
$ cmd.exe /c "echo hello"
$ # nothing
```

Piping though `cat(1)` (or anything else) seems to right the problem consistently.

![image](https://user-images.githubusercontent.com/7049700/68065152-03ea3580-fce2-11e9-8d0d-43ccea0a9e6d.png)

> * What's wrong / what should be happening instead:

Output on the tty.

> * Strace of the failing command, if applicable

Here is the [gist](https://gist.github.com/therealkenc/be6f072908bb58b31475560332f07d29) of:
```
$ strace -f -o cmdexe.strace cmd.exe /c "echo hello"
```

Oddly there was life on one run:

![image](https://user-images.githubusercontent.com/7049700/68065213-37798f80-fce3-11e9-92ee-9d330f0d501d.png)

There is a better than zero chance this is a console or conpty thing. If so feel free to punt me over there.

**Comment by craigloewen-msft** [comment]
Seems like this is related to the Windows console. I just tried this in both Windows Terminal and the Windows Console and it works in Terminal. 

![image](https://user-images.githubusercontent.com/42221804/68962500-9af6c900-0789-11ea-9ac6-b69ea1e50a7d.png)

@therealkenc could you open an issue on the Microsoft/Terminal repo for this?

**Comment by benhillis** [comment]
There should be a fix for this coming soon from the console folks.

**Comment by Biswa96** [comment]
Any related issue from MS terminal repo?

**Comment by therealkenc** [comment]
Thanks. Will close tag console.
