### ISSUE TITLE
"Could not read response to hello message..." while installing python3

### ISSUE THREAD

**Issue by goryntsev** [microsoft/WSL#4640]
Trying to install python3 on WSL [Windows Version 10.0.17763.805] with
`sudo apt-get install python3`

and get this error:
**E: Could not read response to hello message from hook [ ! -f /usr/bin/snap ] || /usr/bin/snap advise-snap --from-apt 2>/dev/null || true: Success**

Apparently it is the package specific issue as other packages are installed smoothly.

**Comment by therealkenc** [comment]
/dupe #2374 ([message](https://github.com/microsoft/WSL/issues/2374#issuecomment-389462712)) #2972 ([message](https://github.com/microsoft/WSL/issues/2972#issuecomment-547225657)) et al.

**Comment by phoyer** [comment]
Look for the hook script causing the trouble:
cd /etc/apt/apt.conf.d/
grep -r snap

Delete the script. In may case it was:
sudo rm 20snapd.conf

**Comment by eddyp** [comment]
A better option, without killing snapd integration entirely is to rename the file so is disabled as an apt hook:

`sudo mv /etc/apt/apt.conf.d/20snapd.conf{,.disabled}`

**Comment by FER00Z** [comment]
It worked for me
sudo rm -rf /etc/apt/apt.conf.d/20snapd.conf

**Comment by MadDogofShimano** [comment]
> 
> 
> Look for the hook script causing the trouble:
> cd /etc/apt/apt.conf.d/
> grep -r snap
> 
> Delete the script. In may case it was:
> sudo rm 20snapd.conf

This works! Thanks a ton.

**Comment by vikrant577** [comment]
> Look for the hook script causing the trouble:
> cd /etc/apt/apt.conf.d/
> grep -r snap
> 
> Delete the script. In may case it was:
> sudo rm 20snapd.conf

Thanks man!!! savior!!! it worked for me..

**Comment by TheWaveLab** [comment]
run sudo rm -rf /ect/apt/apt.conf.d/20snapd.conf

**Comment by jlord31** [comment]
> run sudo rm -rf /ect/apt/apt.conf.d/20snapd.conf

This works for me.....Saved me hours of debugging
Thanks a lot

But out of curiosity what exactly is the apt.conf.d script?

**Comment by KerwinKoo** [comment]
> Look for the hook script causing the trouble: cd /etc/apt/apt.conf.d/ grep -r snap
> 
> Delete the script. In may case it was: sudo rm 20snapd.conf

thanks very mach

**Comment by AnthonyLapadula** [comment]
FWIW, I had two files causing this problem in /etc/apt/apt.conf.d: 20apt-esm-hook.conf and 20snapd.conf

**Comment by misterBart** [comment]
> FWIW, I had two files causing this problem in /etc/apt/apt.conf.d: 20apt-esm-hook.conf and 20snapd.conf

Same here

**Comment by addliam** [comment]
> A better option, without killing snapd integration entirely is to rename the file so is disabled as an apt hook:
> 
> `sudo mv /etc/apt/apt.conf.d/20snapd.conf{,.disabled}`


Safer and clean. Thanks very much

**Comment by iadelofficial** [comment]
> > FWIW, I had two files causing this problem in /etc/apt/apt.conf.d: 20apt-esm-hook.conf and 20snapd.conf
> 
> Same here
remove both
