### ISSUE TITLE
Solus distro imported from WSL always receives the same error "FATAL: kernel too old"

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/WSL#4642]
* **Windows build number:**  Microsoft Windows [Version 10.0.18362.449]

* **What you're doing and what's happening:** 

![image](https://user-images.githubusercontent.com/2257024/68097323-3b4d1380-fe95-11e9-8b79-5c882f327810.png)

* **What's wrong / what should be happening instead:**

Solus should have the same native glibc and same native Windows' Linux kernel that other unofficial distributions have, and which worked successfully. 

* **Detail**

* 1st case:
   - I downloaded and extracted an ISO of the latest Solus distribution version, and mounted an rootfs image, compressing as .tar or tar.gz;
   - I imported a Solus distribution from WSL or from https://github.com/yuk7/wsldl, received that error. I thought that, because it was an ISO.

* 2nd case:
  - I created a virtual machine of Solus, upgraded the glibc and Linux kernel;
  - I converted .vdi to .img;
  - I mounted the .img and compressed the root tree as `.tar.gz`
  - I imported a Solus distribution from WSL or from https://github.com/yuk7/wsldl, received that error. I thought that, because glibc and kernel were missed, and I had an idea.

* 3rd case;
   - Docker's Solus image does not have that error, so I created a container of Solus, and exported as `rootfs.tar.gz`
   - I imported a Solus distribution from WSL or from https://github.com/yuk7/wsldl, received that error. 

**Reference;** https://github.com/yuk7/wsldl/issues/46

**Comment by therealkenc** [comment]
> 10.0.18362.449
> ISO of the latest Solus distribution

Somewhere between by-design tag and external tag. You will probably make better progress in the cited thread. You _might_ find more joy on WSL2, which reports a slightly higher kernel version number (4.19.x vs 4.4.x). Then again you might not, depends on whatever it is that you are running considers too old. Work-around (not really the word) would be to find `FATAL`, comment it out.

Fun party trick, you can spoof your `/proc/version` with a bind mount.
```
$ echo "Linux version 6.13.7-microsoft-standard+ (ken@DESKTOP-BNN97ME) (gcc version 11.2.0 (Ubuntu 8.3.0-6ubuntu1)) #1 SMP Sun Oct 27 14:46:29 PDT 2019" > ./version
$ sudo mount --bind ./version /proc/version
```

Bonne chance.

**Comment by gusbemacbe** [comment]
Salut @therealkenc !

> ```
> $ echo "Linux version 6.13.7-microsoft-standard+ (ken@DESKTOP-BNN97ME) (gcc version 11.2.0 (Ubuntu 8.3.0-6ubuntu1)) #1 SMP Sun Oct 27 14:46:29 PDT 2019" > ./version
> $ sudo mount --bind ./version /proc/version
> ```

Inside Solus or sent from Ubuntu to Solus? Outside Solus, using Windows PowerSHell on Windows Terminal?

If inside Solus, I will not be to send, because if I send `echo`, it will return the fatal error.

**Comment by gusbemacbe** [comment]
@therealkenc 

The first command worked, but the last command not:

![image](https://user-images.githubusercontent.com/2257024/68114370-9f42fc80-fed4-11e9-96b4-4c5a162957fb.png)

**Comment by therealkenc** [comment]
>Inside Solus or sent from Ubuntu to Solus?

Wouldn't have the slightest idea (never used Solus). Which is why the question would be better directed to the purveyors of the product.

**Comment by gusbemacbe** [comment]
Hello @therealkenc !

One of Solus team developers said they are not familiar with building WSL environments. 

But @yuk7 said his explanation was not clear, so the fault was his, indicated the Linux kernel version. I checked Solus' Linux kernel version. I saw it is Linux 4.9.184 and not Linux.4.4.0. 

I will see if I can install Linux 4.4.0 kernel, set it as default and remove Linux 4.9.0.

**Comment by gusbemacbe** [comment]
@therealkenc 

I have a question. Does WSL support Linux kernel 5.3.x?

**Comment by gusbemacbe** [comment]
@therealkenc 

I have checked, WSL does not support 5.3.x. I have to compile 4.4.x or 4.19.x

**Comment by Biswa96** [comment]
I have compiled latest 5.4-rc6 in Ubuntu Eoan and it works in WSL. Steps:

1. Get the latest tarball from kernel.org.
2. Extract in a folder.
3. Copy the kernel config from WSL Linux kernel repository.
4. You may have to add the changes in kernel source code but I didn't, lazy :)
5. Compile it with that config file. Accept default options for all other settings.

The WSL2 VM boots up. But I don't know if Linux kernel 5 works for all cases without any bugs. Where did you get the Solus rootfs tarball?

**Comment by gusbemacbe** [comment]
@Biswa96 

**1st alternative**:

1. Create a virtual machine and install Solus Budgie in VirtualBox. Switch to VBoxSVGA.
2. In Solus, make an upgrade and reboot.
3. Plug your 8GB or 16GB USB drive stick.
4. Open the terminal:

```
cd /
sudo tar -czvpf /run/media/yourusername/Your_USB_srick/rootfs.tar.gz --one-file-system /
```

5. Create a folder called `Solus`, download @yuk7's [Launcher.exe](https://github.com/yuk7/wsldl/releases/tag/19110100). Move `Launcher.exe` and `rootfs.tar.gz` to the folder `Solus`. Rename Launcher.exe to `Solus.exe`. Run the `Solus.exe

**2nd alternative (quicker):**

1. Use Docker.
2. Open the terminal and run:

```
$ docker pull feddamisch/solus:system.devel
$ docker run --rm -it feddamisch/solus:system.devel
bash# exit
# Take the container-id
$ docker ps -a
$ docker restart <container-id>
$ docker container export -o rootfs.tar.gz <container-id>
3.  Create a folder called `Solus`, download @yuk7's [Launcher.exe](https://github.com/yuk7/wsldl/releases/tag/19110100). Move `Launcher.exe` and `rootfs.tar.gz` to the folder `Solus`. Rename Launcher.exe to `Solus.exe`. Run the `Solus.exe
```

**Comment by gusbemacbe** [comment]
@Biswa96 

> Copy the kernel config from WSL Linux kernel repository.

Where exactly?

**Comment by DataDrake** [comment]
We don't have any of the Hyper-V stuff enabled in the kernel. So regardless, WSL2 won't work unless you turn it on.

**Comment by gusbemacbe** [comment]
Do you mean to turn the Hyper-V on inside the kernel, @DataDrake ?

**Comment by DataDrake** [comment]
Yes.

**Comment by gusbemacbe** [comment]
Ok, I do not know how, although you do not have this stuff, but let us @Biswa96 know, answer and figure.

**Comment by JoshStrobl** [comment]
Solus developer here (as is @DataDrake), it is completely unreasonable to expect @Biswa96 to walk you through kernel module enabling for an unsupported kernel (we have too new of a kernel) for an unsupported configuration. WSL supports 4.19, which we stopped supporting in December of 2018 (almost a year ago), and 4.4.x is purely an LTS kernel used for older hardware with no plans on enabling kernel modules for unsupported configurations.

Our recommendation is you use a supported operating system in WSL such as Ubuntu.

**Comment by gusbemacbe** [comment]
@JoshStrobl, why does Solus come with 4.9, which is older than 4.19?

**Comment by JoshStrobl** [comment]
> @JoshStrobl, why does Solus come with 4.9, which is older than 4.19?

Our ISOs do not come with 4.9, they ship with 4.20 per our [Solus 4 release notes](https://getsol.us/2019/03/17/solus-4-released/). We **offer** 4.9 in the repository for reasons I mentioned in my comment.

**Comment by gusbemacbe** [comment]
OK, I read and saw. As I want to provide the packages for Solus users, I will reconsider using natively Solus on another HD or running the virtual machine, although the virtual machine performance is not good. 

I have to buy more than ten HDDs, each for each of unsupported distribution. 

I give up on attempting to build on a WSL. 

@Biswa96, forget it. I am sorry if my comment upset you!

**Comment by Biswa96** [comment]
@gusbemacbe I am not upset. Busy with some human things 😴

First question: How to replace Linux kernel 4.x with 5.x? I have tested this in Ubuntu Eoan. Here are the steps:

* Download Linux kernel tarball: https://git.kernel.org/torvalds/t/linux-5.4-rc6.tar.gz
* Install required packages: `apt install build-essential flex bison libssl-dev libelf-dev`
* Untar it: `tar -xf linux-5.4-rc6.tar.gz`
* Download the WSL/Linux kernel config file: https://raw.githubusercontent.com/microsoft/WSL2-Linux-Kernel/master/Microsoft/config-wsl
* There are some changes in WSL Linux kernel. Here is a [diff output](https://gist.github.com/therealkenc/4b5256af912329cd279cf6f5e6a4f6ac), all credit goes to @therealkenc.
* Compile kernel: `make KCONFIG_CONFIG=config-wsl`
* Press enter until it is satisfied.

There are 50-50 chance that the new kernel boots in WSL2 VM. Hence this may not be the correct way to use Solus in WSL. 

The docker container may work. I will update this post if it works. @JoshStrobl Is there any rootfs tarball of Solus distribution, like Ubuntu has [cloud images](https://cloud-images.ubuntu.com/releases/).

**Comment by JoshStrobl** [comment]
Solus is not based on Ubuntu, so the steps you provided for compilation of the kernel, while appreciated, will not work. We have our own build tooling and chroot-based environment for the compilation of the Linux kernel, of which @gusbemacbe is already familiar with (in a separate discussion post he made on our forums).

The Docker image is not one which is provided by us, nor do we provide any form of cloud images. Solus simply is not aimed at WSL or supporting it, sorry. It simply is the case that @gusbemacbe is better off using another Linux-based operating system for this specific usecase.

**Comment by Biswa96** [comment]
The [unofficial Solus docker image][1] works. 

* Pull the image: `docker pull feddamisch/solus:system`
* Save the image: `docker save feddamisch/solus:system --output /mnt/c/MyFiles/solus.tar`
* Extract the layer.tar file from the first layer of the exported solus.tar file.
* Import it: `wsl.exe --import test layer.tar --version 2`

No kernel error as there is no Linux kernel in a Docker image. Finding a official way to do it 🤔 

[1]: https://hub.docker.com/r/feddamisch/solus

**Comment by gusbemacbe** [comment]
@JoshStrobl, @DataDrake and @Biswa96 

If you want to ask me why I wanted to do that.

I know that, when you read the whole explanation, you will not agree with what I did, you may find me crazy, unreasonable, unsustainable and unsuitable. 

I own 7 drives, 3 HDDs and 4 SSDs. I have still to buy else. I use Arch Linux as mainly and daily, although I have Solus, Ubuntu and Void Linux natively. 

My goal is that, on the same OS, to run many server OSes with different package managers for providing my packagers for users who will install my packages natively from the official OS repositories, like https://dev.getsol.us/, so they do not need to go to my repository every time. 

* Alphine (`apk`)
* Arch Linux (`pacman -S` or `trizen -S`) 
* Fedora (`dnf install` or `rpm i`)
* FreeBSD (freshports)
* Gentoo (`emerge -a`)
* NetBSD (pkgsrc)
* openSUSE (`zypper`)
* ROSA Linux/Mageia (`urpmi`)
* Slackware
* Solus (`eopkg It`) 
* Ubuntu (`apt install`)
* Void Linux (`xbps-install`)

The WSL allows me to symlink or mount the some same folders (`Applications/Source`, `GitHub`, `GitLab`), some same configs (`~/.local/share/fonts|icons`, `.zplug`, `.zsh`) to all the OSes once and for all, and it also allows me to run the same apps (@probonopd's AppImages' extracted source), so it saves a lot of space and keeps me efficient, productive, quick and sufficient. It consumes less memory than VirtualBox.

As for VirtualBox... My super-computer is unbelievably very powerful and quick, the performance is marvellous. But as I have only 16GB RAM memory and 8 CPU cores of AMD Ryzen 7 2700X, I have to give 4 CPU cores and 8GB to a virtual machine, to keep both the guest and the host quicker. The performance gets slowed down when I mount the folders and config folders from the host to the guest, because I wanted to keep the space less busy. Mounting the zplug and zsh folders also slow the terminal's performance down. Other VirtualBox's disadvantage is that, I have to install natively few apps for each virtual machine, what will fatten the space, so I have to mount @probonopd's AppImages' folder. Or I have to buy 64GB RAM memory and a processor which comes with 16 cores, what will help to improve the performance of mounted folders and of the terminal's mounted zsh and zplug. 

Docker is another good option, but Docker is very restricted than WSL. Docker does not allow me to access the full OS directories from the normal file manager on Linux or Windows nor to copy the files without root. The WSL allows me to access the full OS directories from the Windows Explorer or the Total Commander without required root.

**Comment by Biswa96** [comment]
chroot??

**Comment by Biswa96** [comment]
If I were in your place I wouldn't choose WSL at all. After all a developer or matainer of a project can't satisfy thousands of GNU/Linux distributions. Also distributions have different repository to download packages in their own format.

**Comment by DataDrake** [comment]
I can't speak for the other distributions, but we use our custom `solbuild` utility to build our packages in an isolated chroot. It's then up to the maintainer of the package to test and verify things. Then we expect that if they encounter issues that they bring it to the attention of the upstream developers (e.g. @gusbemacbe) and work with them to get it working on our side. We have no expectation of the upstream developers to install Solus in any form to test and fix things unless they want to.

But I agree, if you are going to do this for a lot of distros, you are creating a lot of unnecessary work for yourself. Our maintainers should be shouldering the burden, not the upstream developers. Especially considering that most of what @gusbemacbe is developing are icon themes and GTK themes, there are more efficient ways of testing that. You really only need to test those against specific desktop environments, most of which can be installed on a single distribution like Debian/Ubuntu or Arch.

**Comment by gusbemacbe** [comment]
> If I were in your place I wouldn't choose WSL at all. After all a developer or matainer of a project can't satisfy thousands of GNU/Linux distributions. Also distributions have different repository to download packages in their own format.

And the VirtualBox? And each native OS one each drive?

**Comment by gusbemacbe** [comment]
> I can't speak for the other distributions, but we use our custom solbuild utility to build our packages in an isolated chroot.

Is there how to check if `solbuild ` install directly to the Solus OS' directory on any non-Solus OS? I need to know if my package is installed and located in the correct folder.

**Comment by DataDrake** [comment]
@gusbemacbe We generate a `pspec_x86_64.xml` after the package is built and you can look at that. Alternatively inside of the `eopkg` itself is a file called `files.xml` that has a complete listing with sizes, hashes, modes, and ownership.

**Comment by therealkenc** [comment]
> Download Linux kernel tarball: https://git.kernel.org/torvalds/t/linux-5.4-rc6.tar.gz
> [...]
> - Compile kernel: make KCONFIG_CONFIG=config-wsl
> - Press enter until it is satisfied.
> There are 50-50 chance that the new kernel boots in WSL2 VM. 

Smaller than that.

**Comment by sileshn** [comment]
It does boot. Solus on wsl2 running 5.6 kernel

[![solus-wsl2.png](https://i.postimg.cc/Qt7ZGqyZ/solus-wsl2.png)](https://postimg.cc/wy9GDDzw)

**Comment by gusbemacbe** [comment]
@sileshn 

If you do not hesitate, please make a repository named "SolusWSL"and explain how you got it, like you did with FedoraWSL.

**Comment by sileshn** [comment]
@gusbemacbe I cannot do that for obvious reasons. Contact me on sileshn@gmail.com.

**Comment by rescenic** [comment]
@sileshn I am really interested too. I've contacted you via email.
