### ISSUE TITLE
Windows SDK missing WSLAPI import libs

### ISSUE THREAD

**Issue by riverar** [microsoft/WSL#4643]
Windows 10 10.0.18363.418

Consuming [WSL* APIs](https://docs.microsoft.com/en-us/windows/win32/api/wslapi/) is cumbersome due to the lack of import libs (e.g. wslapi.lib) in the Windows SDK (checked 14393 - 18985).

**Comment by Biswa96** [comment]
Workaround: `LoadLibray("wslapi.dll") or `gendef wslapi.dll`.

**Comment by Biswa96** [comment]
Workaround: `LoadLibray("wslapi.dll")` or `gendef wslapi.dll`.

**Comment by riverar** [comment]
Yup I generated my own with dumpbin/lib. But not all developers will know how to do this.

**Comment by Biswa96** [comment]
> But not all developers will know how to do this.

If anyone need it, readymade files and instructions are available here https://github.com/Biswa96/WSLInstall/tree/master/lib.
