### ISSUE TITLE
Arrows , PgUP , PgDown are not passed to wsl in pipes from cmd, powershell to wsl

### ISSUE THREAD

**Issue by nkrepo** [microsoft/WSL#4646]
* Your Windows build number: 
Microsoft Windows [Version 10.0.18362.418]

* What you're doing and what's happening:  
Arrows , PgUP , PgDown are not passed to the wsl application when that application is called inside a pipe from cmd terminal or powershell terminal to wsl.

In Powershell terminal:
Get-ChildItem C:\Windows\System32\ | wsl less

In Cmd terminal:
dir C:\Windows\System32\ | wsl less

* What's wrong / what should be happening instead:
Arrows , PgUp, PgDown should work in less.

**Comment by therealkenc** [comment]
This is for all intents by-design for the foreseeable future. Try for example in Real Linux:
```
$ ls /usr/bin | ssh localhost less
```
...which is analogous to your command.

[The foreseeable future caveat is academic in the sense "anything theoretically possible" but in reality "that's how remote pipes work".]

**Comment by nkrepo** [comment]
I understand @therealkenc , the pipe  between Windows and Linux subsystems even in WSL 1 is considered as a remote pipe. 
In contrast with ssh, that it cannot allocate pty when input is pipped from stdin, the current allocated pty is used from the Linux subsystem when pipe interop is used or I am wrong ?

The limitation should be noted in [https://docs.microsoft.com/en-us/windows/wsl/interop](https://docs.microsoft.com/en-us/windows/wsl/interop).

**Comment by therealkenc** [comment]
> In contrast with ssh, that it cannot allocate pty when input is pipped from stdin, the current allocated pty is used from the Linux subsystem when pipe interop is used or I am wrong ?

I can't parse that.

> The limitation should be noted in https://docs.microsoft.com/en-us/windows/wsl/interop.

Doc PRs can be directed [here](https://github.com/MicrosoftDocs/WSL).

**Comment by nkrepo** [comment]
Sorry I was not clear.
Lets take for example a Powershell terminal (conpty) and the example command:

`Get-ChildItem C:\Windows\System32\ | wsl less` 

Can the terminal allocated for Powershell be accessed from the WSL applications inside the pipe?
Or they are run non interactively like the ssh analogous example?

**Comment by therealkenc** [comment]
> Or they are run non interactively like the ssh analogous example?

$ ls /usr/bin | ssh localhost less
...which is analogous to your command.
