### ISSUE TITLE
ulimit -Hs cannot be changed? Work arounds?

### ISSUE THREAD

**Issue by AhmedSalih3d** [microsoft/WSL#4647]
Hello

Is it really still not possible to increase the stack size in Ubuntu using WSL? I found this post from about 3 years ago:

https://github.com/microsoft/WSL/issues/633

When ever I try to change the limit I get the error:

> -bash: ulimit: stack size: cannot modify limit: Operation not permitted

The command I run is:

> ulimit -Hs unlimited

Do I really have to forget about using WSL, if I am trying to read a lot of data in a C pointer and transfer to Python? Or is there any work around.

Kind regards

**Comment by cqwang2018** [comment]
Hi, do you have a solution about the issue? I met the same situation recently. Run "ulimit -Hs unlimited"  and got this error "-bash: ulimit: stack size: cannot modify limit: Operation not permitted"
