### ISSUE TITLE
WSL & Ubuntu, how to move the init file

### ISSUE THREAD

**Issue by ImadYIdrissi** [microsoft/WSL#4648]
I deployed a dev environment on wsl and I'm so excited about it. My only problem is the existence of an init file in the root path of the system.

![root subdirectories](https://user-images.githubusercontent.com/19647868/68211481-f4b40200-ffd7-11e9-96fa-76d45b42cd2a.png)

For one of my clients, I need to have an /init directory, this is a constraint that **cannot be changed.**

Needless to say, this renders my exciting and newly found wsl dev environment unusable for this project.

Is there a way to change the path of the wsl init file?

**Comment by therealkenc** [comment]
> Is there a way to change the path of the wsl init file?

Not without drawing outside the lines, no. Much the same as you can draw outside the lines and with your client's immutable `/init` directory constraint. You could for example enter a mount namespace.
