### ISSUE TITLE
AOSP build needs case-insensitive.

### ISSUE THREAD

**Issue by dayfan0810** [microsoft/WSL#4651]
Win Version : Windows 10 Pro 1903
Win Version Code : 18362.449

WSL:Ubuntu 18.04.3 LTS

when I use "brunch sailfish" for Pixel image build, it comes out as below:

day@desktop-day:/mnt/e/project/cm16$ brunch sailfish
including vendor/lineage/vendorsetup.sh
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20191106-UNOFFICIAL-sailfish
TARGET_PRODUCT=lineage_sailfish
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-18362-Microsoft-x86_64-Ubuntu-18.04.3-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190705.003
OUT_DIR=/mnt/e/project/cm16/out
============================================
12:09:54 ************************************************************
12:09:54 You are building on a case-insensitive filesystem.
12:09:54 Please move your source tree to a case-sensitive filesystem.
12:09:54 ************************************************************
12:09:54 Case-insensitive filesystems not supported

**Comment by Biswa96** [comment]
Please fill up all the files in issue template. What your Windows 10 version? GNU/Linux distribution name and version? Where is the repository saved?

**Comment by dayfan0810** [comment]
> Please fill up all the files in issue template. What your Windows 10 version? GNU/Linux distribution name and version? Where is the repository saved?

Win Version : Windows 10 Pro 1903
Win Version Code : 18362.449

WSL:Ubuntu 18.04.3 LTS

**Comment by karuboniru** [comment]
Check `case=?` in your mount information

**Comment by dayfan0810** [comment]
> Check `case=?` in your mount information.
> If not `case=force` , that should be the problem.

day@desktop-day:/mnt/e/project/cm16$ mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
D:\ on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
E:\ on /mnt/e type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
F:\ on /mnt/f type drvfs (rw,noatime,uid=1000,gid=1000,case=off)

**Comment by dayfan0810** [comment]
I use https://github.com/microsoft/WSL/issues/101#issuecomment-370293978  solve the case-insensitive problem.
