### ISSUE TITLE
Cannot acces WSL from windows service

### ISSUE THREAD

**Issue by kristjanvalur** [microsoft/WSL#4652]
I want to use WSL to run scripts from my automated build system which is running as a service.  This is the latest version of TeamCity.
The service is logged on as a system user with admin rights.  for the same user, I have logged on on the desktop, and installed Ubuntu-18.
From a command line on the desktop, I can run wsl.exe and bash.exe. further, I can see wsl.exe:
 ```
dir c:\windows\system32\wsl.exe
 Volume in drive C has no label.
 Volume Serial Number is A813-6BF8

 Directory of c:\windows\System32

09/17/2019  09:09 PM           142,848 wsl.exe
               1 File(s)        142,848 bytes
               0 Dir(s)  171,728,314,368 bytes free
```
However, from the service, my command scripts fail, claiming that
```
'wsl' is not recognized as an internal or external command,
operable program or batch file.
``` 
Further, doing the same exact dir command from here gives me:
 ```
dir c:\windows\system32\wsl.exe
 Volume in drive C has no label.
 Volume Serial Number is A813-6BF8

 Directory of c:\Windows\System32
 
File Not Found
```

What magic is windows using to hide the files like this?  What is the correct way to do this?

**Comment by therealkenc** [comment]
This is not a WSL actionable nor was a repro provided, but it can be tag question for a short bit in the event there are takers.

**Comment by kristjanvalur** [comment]
Well, creating windows services isn't exactly trivial, so the repro case is, I suppose, to set up a teamcity build agent as described and have it try to execute wsl commands.
But also understanding how it is possible that the executables are not even visible from the service context would be useful.

**Comment by therealkenc** [comment]
> But also understanding how it is possible that the executables are not even visible from the service context would be useful.

Sounds like that would be useful. But the likelihood of finding an answer to that question in a WSL bug tracker, contrast a question/discussion forum (possibly a forum related to teamcity, whatever a teamcity may be, or elsewhere) is.... probably small.

**Comment by 0xbadfca11** [comment]
File system redirection with WOW64, almost certainly.
https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector

**Comment by therealkenc** [comment]
If so then #223 might hint work-around.

**Comment by kristjanvalur** [comment]
Thanks, the 64/32 bit thing was the clue.  And the redirector is indeed the culprit for why the files weren't visible.
Turns out TeamCity uses 32 bit java to run:  https://teamcity-support.jetbrains.com/hc/en-us/community/posts/360000181539-Upgrade-a-build-agent-to-use-64-bit-java
So, a 32 bit command processor cannot start wsl.  Thanks for looking into this.

**Comment by CheckingCode** [comment]
C:\Windows\Sysnative\wsl.exe
run WSL on ASP.net server side 
Computer Windows 
IIS server 
ASP.net or Core web project
From web page ASP run on server side: call WSL/SWL2  run linux programm , return result to the web page
Problem after transfer project from IIS express to IIS 
WSL.exe have not user iis app pool
