### ISSUE TITLE
[19018+] cross-distro mounts do not appear

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4654]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.19018.1]

* What you're doing and what's happening:

1. Install two WSL distributions (for example, Debian and Alpine)
2. Ensure that both distributions contain an `/etc/wsl.conf` file, which in turn contains the following text:

```
[automount]
crossDistro = true
```

3. Open a shell in both distros simultaneously.
4. In both distros, `ls /mnt/wsl`
5. Observe that this directory is empty in both distros.

* What's wrong / what should be happening instead:

In step 5, the filesystem of each distribution should be mounted beneath `/mnt/wsl`.

Note that if the latest Docker with WSL 2 support is installed and the WSL engine is running, the `docker-desktop`, `docker-desktop-bind-mounts`, and `docker-desktop-data` mounts are visible beneath `/mnt/wsl` and in `mount(8)` output, but the distro mounts are not.

**Comment by benhillis** [comment]
@cerebrate - the behavior of this feature was changed, distro root filesystems are no longer automatically mounted.  However, this shared space is much more flexible (MS_SHARED) so mounts made into this space will be visible in all other mount namespaces.

**Comment by cerebrate** [comment]
Nifty!

**Comment by QAston** [comment]
How do I mount another distro with this change then?@benhillis

**Comment by cerebrate** [comment]
@QAston Like this:

```
#! /bin/bash

# If mount point directory does not exist, create it.
if [ ! -d "/mnt/wsl/$WSL_DISTRO_NAME" ]; then
    mkdir "/mnt/wsl/$WSL_DISTRO_NAME"
fi

# If mount point directory is not mounted upon, bind mount fs.
if ! mountpoint -q -- "/mnt/wsl/$WSL_DISTRO_NAME"; then
    mount --bind --make-private / "/mnt/wsl/$WSL_DISTRO_NAME"
fi
```

run on the distro whose filesystem you wish to share. It will then be visible to all distros.

**Comment by DesignByOnyx** [comment]
@cerebrate - I think your suggestion is the only solution on the internet which actually works. Thank you so much! The last issue I'm having is running this on startup with elevated privileges (only root can use `--bind` option).  I opened a question about it here: https://unix.stackexchange.com/questions/659655/how-to-bind-mount-a-directory-on-startup-without-sudo. 

Thanks again for your help. This saved me.

**Comment by cerebrate** [comment]
@DesignByOnyx I would have expected your `/etc/sudoers` change would have made it work, myself. I use

```
avatar ALL=(ALL) NOPASSWD: ALL
```

in mine to save on typing, and can bind mount just fine with `sudo mount --bind`.

That said, since I run systemd under WSL with genie, I use [this unit](https://randombytes.substack.com/p/wsl-share-fs-01) ([source here](https://github.com/arkane-systems/wsl-share-fs)) to handle sharing the distro fs automatically when I start it up.
