### ISSUE TITLE
Change WSL installation drive

### ISSUE THREAD

**Issue by JinZhuXing** [microsoft/WSL#4655]
How can I change WSL installation directory to other driver not system driver.
I have no enough space on system drive.
So I want to change installation directory of WSL (Ubuntu 18.04) to other driver.
Please help me.
Thank you.

**Comment by karuboniru** [comment]
`wsl --export` and then `wsl --import`

**Comment by therealkenc** [comment]
This is /dupe #1270 which was sent to (now defunct) UserVoice and duped #449 which floats open feature tag as the LZ.
