### ISSUE TITLE
[WSL2] ServerName not working in apache2

### ISSUE THREAD

**Issue by europaisch** [microsoft/WSL#4656]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.19018.1
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1. in PowerShell: wsl --set-default-version 2
2. in hosts file, add example.test next to localhost
3. install Ubuntu from Windows store
4. sudo apt update && sudo apt upgrade && sudo apt install apache2
5. sudo nano /etc/apache2/sites-available/000-default.conf
6. add ServerName example.test to VirtualHost, save file
7. sudo service apache2 restart
8. try to open example.test in your browser of choice

* What's wrong / what should be happening instead:
I get the **ERR_CONNECTION_REFUSED** error. If I open localhost, though, I do see the website I intended to open when I opened example.test
I'd also like to note that in WSL1 this worked correctly.
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
not applicable
* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by Biswa96** [comment]
Is the Apache service running after step 7 and before step 8?

**Comment by europaisch** [comment]
Yes.
I just tried to do what was recommended in #4356, and sadly it did not work either.

**Comment by europaisch** [comment]
Actually no, what is in #4356 does work. It's just that if you add localhost next to 127.0.0.1 in hosts, it overrides WSL and leads to the error.
