### ISSUE TITLE
Docker pull error with Surface Dock "bad record MAC"

### ISSUE THREAD

**Issue by ryankmcintyre** [microsoft/WSL#4658]
* Your Windows build number: 
19018.1

* What you're doing and what's happening:  
WSL2 Ubuntu on a Surface Book connected to a Surface Dock with hardwired network connection through the dock (Surface Ethernet Adapter). When I run `docker pull ubuntu`, the result is `local error: tls: bad record MAC` and image isn't downloaded.

Unplugging network cable from the Surface Dock and using wireless, docker pull works fine. Using a different network adapter through USB and going through that wired connection, docker pull works fine. Error only results when using the network connection in the Surface Dock.

Similar to [this](https://github.com/microsoft/WSL/issues/4306) and [this](https://github.com/microsoft/WSL/issues/4253) issue, but now with a wired connection instead of wireless. I checked if there is a firmware update for the Dock and it's already on the latest (1.42.139) according to [this doc](https://docs.microsoft.com/en-us/surface/surface-dock-firmware-update).

Comparing network connection properties between the two ethernet connections, I don't see a difference.

* What's wrong / what should be happening instead:
Image should be downloaded without MAC error

* Strace of the failing command, if applicable:  
Results from `strace -o dockerpull.strace -f docker pull ubuntu` when connected through Surface Dock: https://gist.github.com/ryankmcintyre/bd5d9ce2d323b42a6cd5f68588e8f8eb

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
N/A

**Comment by ryankmcintyre** [comment]
@therealkenc What else can I provide beyond the initial description to help with repro?

**Comment by therealkenc** [comment]
A set of CLI steps that identifies the source of the "`local error: tls: bad record MAC`" error. It wouldn't be a trivial undertaking. Think [`openssl(1)`](https://wiki.openssl.org/index.php/Command_Line_Utilities) experiments with `-debug` traces and possiblly [wireshark](https://www.wireshark.org/). None of which is expected; just probably what it would take to track down.

The strace log you linked is always super appreciated. Will drop the need-repro tag (plenty else open with less). Maybe someone with a Surface Dock who can reproduce the problem locally with dive it.

**Comment by ryankmcintyre** [comment]
If anyone picks this up, I'd be happy to open up a remote session for some debugging/tracing with them. Or run some additional tools locally. I realize this is an edge case and not many folks have the same hardware setup I do.

**Comment by james-d-elliott** [comment]
Other reports suggest it was a driver/NIC issue. https://github.com/microsoft/WSL/issues/4306

**Comment by therealkenc** [comment]
> Other reports suggest it was a driver/NIC issue. #4306

Thanks! Given the symptoms that seems very plausible. Calling this a dupe for lack. [The alternative being this one remaining open and chirping crickets indefinitely.]

**Comment by ryankmcintyre** [comment]
@therealkenc If you check the original issue text you'll see I referred to 4306 and already eliminated that as the cause due to drivers being up to date. This issue isn't a dup of 4306. Up to you to keep it open with the hopes someone picks it up or close it since it doesn't seem anyone else is interested in fixing it.

**Comment by therealkenc** [comment]
It isn't that no one wants to fix it. There's no repro; or, at least, no flood of Surface Book users (of which, let's assume there are a few at MSFT) rushing to thumbs up the OP. The error strongly suggests (but does not prove) an unidentified external factor vs. something plausibly actionable within WSL.

> This issue isn't a dup of 4306

That's fair. Your poison on open/closed status.

**Comment by james-d-elliott** [comment]
Also my intent was to help solve it, someone else had this issue and I discovered both of these issues via searching, so rather than ignoring the possible relation I wanted to mention it. I just didn't see the previous links due to how they were linked, small oversight on my part.

**Comment by stmax82** [comment]
I don't think this is a Surface Dock problem.. I'm struggling with this error since months and have to retry docker pulls and apt-get installs several times until everything goes through. Only on this one PC.. it's got some ASRock Z170 Extreme4 board and a "AVM FRITZ!WLAN Stick AC 860" Wifi adapter.

I don't think it's a driver / NIC problem - I can curl debian isos day and night without a single error. But I cannot manage to docker pull an image of 300MB without getting tls errors :/

**Comment by stmax82** [comment]
> I'm not sure if it's a driver / NIC problem - I can curl debian isos day and night without a single error on **Windows/PowerShell** and in **WSL2/Ubuntu/bash** - but I get "bad record mac" errors when I try to curl the same debian iso in a docker container or when I try to docker pull something.

Well let me update my opinion.. I now think it is a driver / NIC problem - I replaced my "Fritz!WLAN Stick AC860" with a new "TP-Link Archer T3U AC1300" wifi usb dongle and the TLS errors are gone. Nice.

I'm not sure how a faulty driver can cause that error though.. if there's data corruption somewhere in the network stack, shouldn't TCP handle that and request retransmission of faulty packets? Also not sure why errors only occurred within docker contains but never outside (see examples above).. oh well.. at least it works now.

**Comment by philicevic** [comment]
Also got the "Fritz!WLAN Stick AC860" - and got the same problems as @stmax82. But for me docker pulls do not work at all. I don't really know a lot about network stuff, but i would rather not replace the stick. Maybe anyone has an idea to overcome this?

**Comment by RedaDZ** [comment]
had the same problem, switched from 2.4Ghz to 5.0Ghz and it works. don't know if is due to that

**Comment by ramboll-max** [comment]
> had the same problem, switched from 2.4Ghz to 5.0Ghz and it works. don't know if is due to that

also worked for me!

**Comment by SysCoder** [comment]
I was connected to a hard wired connection. After I went to WIFI, it worked.

I am using podman and Mac OS 13.2

WAT!?!?! weird issue.
