### ISSUE TITLE
wifite (no wifi extentions)

### ISSUE THREAD

**Issue by kayden-coderr** [microsoft/WSL#4659]
Ive looked this up everywhere but can't find anything that will work with kali

Ive tried nawin.cf
and index of/download/compat-wireless-2.6/

but neither have worked index had 404 not found
and nawin.cf would not open at all

**Comment by MDALAMRAN** [comment]
Hello sir, 
When i type iwconfig in termina it shows(no wireless extension) i tried so many ways to solve this problem but it won't. Please help me
