### ISSUE TITLE
Microsoft-Windows-Subsystem-Linux is unknown 

### ISSUE THREAD

**Issue by Ayalghamdi** [microsoft/WSL#4661]
Hi All , 
  Anyone can help me to solve this issue .

>Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

---Name                           Value
----                           -----
PSVersion                      5.0.10586.122
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.122
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Ayalghamdi** [comment]
The feature is not appearing by using the GUI approach to install WSL.
\ Turn Windows Features On or Off - the Windows Subsystem for Linux option is not found .

**Comment by Ayalghamdi** [comment]
OS Build 10586
Version 1511 
Windows 10 pro

**Comment by karuboniru** [comment]
UPGRADE YOUR WINDOWS

**Comment by knut-erik** [comment]
You need to upgrade your os @Ayalghamdi  to at least 18917 or higher.
Here is a link to installing WSL2 => https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by therealkenc** [comment]
> 10.0.10586.122

Yeah call that answered. Thx all.

**Comment by Ayalghamdi** [comment]
Thank you all . The issue it's resolved after upgraded my windows to latest version .

**Comment by geocine** [comment]
```
Deployment Image Servicing and Management tool
Version: 10.0.19041.572

Image Version: 10.0.19042.631


Error: 0x800f080c

Feature name Microsoft-Windows-Subsystem-Linux is unknown.
A Windows feature name was not recognized.
Use the /Get-Features option to find the name of the feature in the image and try the command again.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
```
Anyone have solutions?

**Comment by olsonperrensen** [comment]
PowerShell 7.4.2
PS C:\Users\BEDRIJF> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.22621.1

Image Version: 10.0.22631.2428


Error: 0x800f080c

Feature name Microsoft-Windows-Subsystem-Linux is unknown.
A Windows feature name was not recognized.
Use the /Get-Features option to find the name of the feature in the image and try the command again.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log

build 22631.2428 same issue.
