### ISSUE TITLE
Ubuntu wsl not starting after upgrade

### ISSUE THREAD

**Issue by gerhardamegg** [microsoft/WSL#4662]
I'm running on `Microsoft Windows [Version 10.0.18362.449]`.
My Ubuntu subsystem ran flawless until today: I noticed you can upgrade your distro to the WslFs file system via `wsl --upgrade Ubuntu` ([doc](https://docs.microsoft.com/en-us/windows/wsl/reference#wslconfigexe)) on Powershell as Admin. I tried that out of curiosity. I got the output `Upgrade läuft ...` (German for `executing update`). About half an hour later, I interrupted the execution with `CTRL+C` (execution stopped immediately). The time to update/upgrade my system with `sudo apt update`/`sudo apt upgrade` is normally around a few minutes, so I got suspicious something might went wrong. But wsl is not starting anymore: when running `wsl` or `ubuntu`, I get the message `Für diese Distribution läuft ein Installations-, Deinstallations- oder Upgrade-Vorgang.` (German for `Currently this distribution is running an installation, uninstallation or upgrade)` and returns. If you type `wsl --upgrade Ubuntu` again, it starts over. Killing the task with powershell `Stop-Process -processname "wsl"` shows no change, neither does a restart of my PC. I tried to create a late backup with `wsl --export Ubuntu ubuntubackup.tar`, but (after creating an empty file) it just prints out the "Currently running an update....". `wsl --list --running` shows no running distros.

**Comment by sirredbeard** [comment]
File conversion can take time. WSL installs can quickly grow to many gigs. A good way to see if it is stalled is to check Task Manager for activity. Interrupting it can cause issues. In your cause I would try to restore by removing the WSL feature and re-adding it.

**Comment by benhillis** [comment]
wsl.exe --upgrade is deprecated (functionality no longer present on newer builds).

**Comment by sirredbeard** [comment]
Good to know. Thanks, @benhillis.

**Comment by gerhardamegg** [comment]
Sooo.... @benhillis  is there any way to get my bash running again? Or do I have to reinstall the whole thing? Although, why is the doc not saying a word about that? Or at least prints it in the terminal? Did that depreciated command seriously just brake my wsl?

**Comment by pathaine** [comment]
Wondering the same thing. My WSL stopped working last night's Windows update.

**Comment by sirredbeard** [comment]
@gerhardamegg @pathaine See #4673

**Comment by gerhardamegg** [comment]
I´m not using wsl2 or a VM. I removed the wsl in the "optional features", restarted, activated it again, no change.

**Comment by gerhardamegg** [comment]
Removed Ubuntu and installed it again. Lost all data, but now it's working.
