### ISSUE TITLE
Cannot install Ubuntu 1804; WslRegisterDistribution failed with error: 0x80070003

### ISSUE THREAD

**Issue by Devilmoon** [microsoft/WSL#4663]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.829]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Downloaded Ubuntu 1804 via Powershell 
`Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx -UseBasicParsing`
Installed it
`Add-AppxPackage .\Ubuntu.appx`
Now where I try launching Ubuntu 18.04 to initialize it I get this output
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 The system cannot find the path specified.
```

* What's wrong / what should be happening instead:

Ubuntu should be installed

**Comment by sirredbeard** [comment]
Are you by chance trying to install the .appx from a drive other than C:\?

**Comment by Biswa96** [comment]
If possible upgrade Windows version.

**Comment by Devilmoon** [comment]
@sirredbeard Yes, I was trying to install it on D:
But I also found out that WSL doesn't have access to the GPU so I had to switch to a dual-boot installation :)

**Comment by sirredbeard** [comment]
@Devilmoon I am glad we worked it out but sorry it couldn't meet your needs. You should also know you can run Ubuntu on Hyper-V with PCI pass-through to your GPU and then ssh in from WSL.

@therealkenc This can be closed.

**Comment by tunsco2010** [comment]
I got the same error on Windows 11 preview. Kindly help as I need it to work with Docker. I have tried installing it from both the store and command line still same error.

**Comment by tunsco2010** [comment]
I got the same error on Windows 11 preview. Kindly help as I need it to work with Docker. I have tried installing it from both the store and command line still same error.
