### ISSUE TITLE
Unable to get upgraded to WSL2

### ISSUE THREAD

**Issue by robertstrom** [microsoft/WSL#4664]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18363.449]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Trying to upgrade to WSL2. I have upgraded to Win10 1909 and enabled virtualization

Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform

rebooted, and launched an Administrative PowerShell shell and typed wsl -v -l and all I get is the help text for the wsl command

I have done a full uninstall of Ubuntu 18.04, the Virtualization feature, and the Linux subsystem and then reinstalled them multiple times - all with the same results.

I did have WSL and Ubuntu installed prior to upgrading to Win10 1909.

* What's wrong / what should be happening instead:

Based on what I have read I should get a print out to the console that shows me that I am on WSL v2

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by Biswa96** [comment]
WSL2 is in fast insider builds.

**Comment by robertstrom** [comment]
SO all the articles that I have read for months have stated that WSL2 would be part of WIn10 1909. That appears to absolutely not be the case. What happened? How much longer do we have to wait. Supremely disappointed!

**Comment by Sword-Smith** [comment]
I really like WSL2 but it would be nice if it was available on the regular Windows build, not just on the Insider build.
