### ISSUE TITLE
Very slow IO with WSL2 even on SSD. Example: updatedb

### ISSUE THREAD

**Issue by Borkason** [microsoft/WSL#4668]
* Your Windows build number: Microsoft Windows [Version 10.0.19018.1]
* What you're doing and what's happening:

WSL 2 installed on a SSD. Running `updatedb`. 
It takes 6 minutes the first time and 2 minutes the second run. On an SSD this should take a couple of seconds at most, at least for the second run.

```
root@BORKASON:~# time updatedb

real    5m50.360s
user    0m7.647s
sys     0m50.115s
root@BORKASON:~# time updatedb

real    1m55.429s
user    0m2.723s
sys     0m16.396s

```

* What's wrong / what should be happening instead:
On an SSD this should take a couple of seconds at most.

**Comment by onomatopellan** [comment]
Try adding `/mnt` to the PRUNEPATHS variable in `/etc/updatedb.conf`

Accessing /mnt files in WSL2 is slow right now #4197

**Comment by therealkenc** [comment]
>Try adding /mnt to the PRUNEPATHS variable in /etc/updatedb.conf

That's the catch. I didn't consider `updatedb(8)` would traipse all over `/mnt` (an strace log would have made that obj). Thanks!

**Comment by LakshmiBhaskarPVL** [comment]
![Image](https://github.com/user-attachments/assets/96186a03-03ad-49d3-b24b-bd26366f19ea)
 that happened much faster after trying to keep this running for almost 7 days
