### ISSUE TITLE
WSL2 problem when $HOME is mounted from outside VolFs

### ISSUE THREAD

**Issue by fpopineau** [microsoft/WSL#4670]
This is WSL2 with Ubuntu 18.04 on Microsoft Windows [version 10.0.19013.1122].
Running :
```
Fabrice@Marvin:/source$ dconf list /
**
dconf:ERROR:dconf-shm.c:92:dconf_shm_open: assertion failed: (memory != MAP_FAILED)
Aborted
```
This is because my $HOME is linked from some place outside VolFs (/home/Fabrice -> /mnt/c/Home)
If I set $HOME inside VolFs, then `dconf` is working ok.
No need to say that it prevents many Gtk app from running.

Regards,

**Comment by therealkenc** [comment]
`strace(1)` log. Possibly be Linux behavior; but to confirm that would take making your home a symlink to a SMB share on Real Linux. Even if that worked (it might, it might not) It isn't an advised scenario on native Linux or WL. Work-around: don't make your home folder a Windows share.

**Comment by fpopineau** [comment]
Well, WSL2 seems unable to memory map this configuration file.
I moved ~/.cache directory to VolFs and symlinked it to ~/.cache.
That fixed this problem.

Sincerely:
- not being able to put ~/ and other work files outside of VolFs defeats
the purpose of WSL in many scenarios,
- if you add on top of it the performance issue
https://github.com/microsoft/WSL/issues/4197 it makes the thing unusable.
Pity because it was a nice idea.

Regards,


Le mer. 13 nov. 2019 à 05:53, therealkenc <notifications@github.com> a
écrit :

**Comment by therealkenc** [comment]
Fail appears to be [here](https://gitlab.gnome.org/GNOME/dconf/blob/7419a726a2dbaca7781cec4eeb65bd1334a523d7/shm/dconf-shm.c#L93) (for the sake of bookmarking).
