### ISSUE TITLE
Wsl 2 docker localhost bindings

### ISSUE THREAD

**Issue by vladymyrs** [microsoft/WSL#4671]
* Windows build number: Microsoft Windows [Version 10.0.19018.1]

* I have docker installed in WSL Ubuntu-18.04 and Mysql container in it.
Mysql docker ports look like this `0.0.0.0:3306->3306/tcp, 33060/tcp`
Netstat inside WSL looks like:
`tcp6       0      0 :::3306                 :::*                    LISTEN      23443/docker-proxy`
Netstat on Windows host looks like:
`  TCP    [::1]:3306             [::]:0                 LISTENING       12532`

* What's wrong / what should be happening instead:
Connecting to mysql using `localhost:3306` on Windows Machine works as expected, but doesn't work using `127.0.0.1:3306`
Having similar issues with a couple of other containers as well. 
Is there any way of fixing this issue?

**Comment by eungook** [comment]
I had a same problem too.
see the netstat on windows host
> TCP [::1]:3306 [::]:0 LISTENING 12532

I think you should use `::1`
not `127.0.0.1` 😀

**Comment by xuyiyang** [comment]
I had the same problem. I run nginx and redis by docker on wsl2.
I can use 127.0.0.1:80 to access to nginx .
but I can not use 127.0.0.1@6379 to access to redis by redis client,
only can use ::1@6379 to access.

**Comment by netcore-jroger** [comment]
> I had a same problem too.
> see the netstat on windows host
> 
> > TCP [::1]:3306 [::]:0 LISTENING 12532
> 
> I think you should use `::1`
> not `127.0.0.1` 😀

you can use `localhost` instead `::1`. I use `localhost` work fine.
