### ISSUE TITLE
[WSL1] valgrind return" error calling PR_SET_PTRACER, vgdb might block" windows 1909

### ISSUE THREAD

**Issue by Po-wei** [microsoft/WSL#4672]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18363.476]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
run valgrind

* What's wrong / what should be happening instead:

always return error calling PR_SET_PTRACER, vgdb might block

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/Po-wei/7b2228c689fa33c847bf95874964b2f2

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
> > Copy&paste the full set of specific command-line steps necessary to reproduce the behavior
> run valgrind

That wasn't your repro. Do appreciate the `strace(1)` logs tho.

```
execve("/usr/bin/valgrind", ["valgrind", "./ixtest_01"], 0x7fffc2e543f0 /* 21 vars */) = 0
[...]
34    mmap(0x1002bb1000, 27597024, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1002bb1000
34    mmap(0x1004603000, 4769856, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004603000
34    mmap(0x1004a90000, 1362816, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004a90000
34    mmap(0x1004bdd000, 131042, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004bdd000
34    mmap(0x1004bfd000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004bfd000
34    write(1027, "\nvalgrind: the 'impossible' happ"..., 71) = 71
34    gettid()                          = 34
34    write(1027, "\nhost stacktrace:\n", 18) = 18
```

There's a few google [hits](https://www.google.com/search?rlz=1C1CHBF_enCA874CA874&sxsrf=ACYBGNRdkZRaJ5FyU4XnIaTR1JS_9tsnbw%3A1573675909567&ei=hWPMXfOXItH1-gTO3LvICg&q=%22valgrind%3A+the+%27impossible%27+happened%22&oq=%22valgrind%3A+the+%27impossible%27+happened%22&gs_l=psy-ab.3..35i39j0l2j0i30j0i8i30j0i333.43292.43927..44144...0.2..0.83.158.2......0....1..gws-wiz.......0i71j0i22i30.P7PcUaKqwxo&ved=0ahUKEwiz7tLM_-flAhXRup4KHU7uDqkQ4dUDCAs&uact=5). Dunno if they apply (probably not). `valgrind` has/had been reported to work at some point ref #120. Guidance would be to try [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/).

**Comment by therealkenc** [comment]
> > Copy&paste the full set of specific command-line steps necessary to reproduce the behavior
> run valgrind

That wasn't your repro. Do appreciate the `strace(1)` logs tho.

```
execve("/usr/bin/valgrind", ["valgrind", "./ixtest_01"], 0x7fffc2e543f0 /* 21 vars */) = 0
[...]
34    mmap(0x1002bb1000, 27597024, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1002bb1000
34    mmap(0x1004603000, 4769856, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004603000
34    mmap(0x1004a90000, 1362816, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004a90000
34    mmap(0x1004bdd000, 131042, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004bdd000
34    mmap(0x1004bfd000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x1004bfd000
34    write(1027, "\nvalgrind: the 'impossible' happ"..., 71) = 71
34    gettid()                          = 34
34    write(1027, "\nhost stacktrace:\n", 18) = 18
```

There's a few google [hits](https://www.google.com/search?rlz=1C1CHBF_enCA874CA874&sxsrf=ACYBGNRdkZRaJ5FyU4XnIaTR1JS_9tsnbw%3A1573675909567&ei=hWPMXfOXItH1-gTO3LvICg&q=%22valgrind%3A+the+%27impossible%27+happened%22&oq=%22valgrind%3A+the+%27impossible%27+happened%22&gs_l=psy-ab.3..35i39j0l2j0i30j0i8i30j0i333.43292.43927..44144...0.2..0.83.158.2......0....1..gws-wiz.......0i71j0i22i30.P7PcUaKqwxo&ved=0ahUKEwiz7tLM_-flAhXRup4KHU7uDqkQ4dUDCAs&uact=5). Dunno if they apply (probably not). `valgrind` has/had been reported to work at some point ref #120. Guidance would be to try [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/).

**Comment by Po-wei** [comment]
prior to 1909, I can run valgrind with very very same program in WSL1.

**Comment by Po-wei** [comment]
./a.out is a simple C++ hello_world just return 0;
![image](https://user-images.githubusercontent.com/17596021/68811399-6a961a00-0625-11ea-94c1-ec01812403fd.png)

**Comment by Po-wei** [comment]
manual compile the latest version of [valgrind](http://valgrind.org/downloads/) fix the problems
