### ISSUE TITLE
WSL takes too long to start after a Windows Update

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#4673]
~~Just installed Windows 19023, and WSL seems broken.~~
I noticed this issue happening since 19023. After updating Windows, WSL takes too long, aproximately 30 minutes, to actually start.

## What's not working

- Network drive mount of `\\wsl$`
- `wsl` command in CMD
- `bash` command in CMD
- Windows Terminal, which has `bash` as default profile
- Docker in WSL2 profile, i.e Docker not starting and Docker Settings -> Resources -> WSL integration, All distros are unselected (which were previously selected when everything is running fine)

## Expected behaviour
WSL should work instantly after updating Windows. So, when entering `wsl` in CMD. Network drive mounts to `\\wsl$` should be mounted and working. `bash` should start the default distro when entering in CMD. Docker should start and all the distros under Resources -> WSL integration should be selected.

## Actual behaviour
- Running `wsl` in CMD does nothing, no errors, nothing.
- Running `bash` command in CMD just hangs, no erros, nothing.
- When opening network mount of `\\wsl$` this error message shows up
![image](https://user-images.githubusercontent.com/9553253/68783072-b69f8980-063a-11ea-8604-118d75cbe7b4.png)
- After some minutes (30 or so) everything starts to work as expected.

## Things tried so far without success
- Restart/Shutdown
- `Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")`

## Infos
![image](https://user-images.githubusercontent.com/9553253/68782631-02056800-063a-11ea-89bd-3de1b6ac52ba.png)
![image](https://user-images.githubusercontent.com/9553253/68782683-134e7480-063a-11ea-940f-41f22c1dbc1c.png)

## Update
After a while, everything started to work again as expected. Now, even after a restart, everything works instantly.

## Fixed
I realized that my PC was slow overall, when waking from hybernate or restarting. After fiddling around, I found out that the firewall of Kaspersky Internet Security 2019 was causing the lags, and the slow startup of WSL and all the realted service (network mount, docker, etc..)

**Comment by Biswa96** [comment]
I am using WSL2 with build 19023 right now without any issue. Does WSL1 work? One random thought, can you check if vmcompute, LxssManager, dhcp, dnscache, p9rdr services are running?

**Comment by ad-on-is** [comment]
> I am using WSL2 with build 19023 right now without any issue. Does WSL1 work? One random thought, can you check if vmcompute, LxssManager, dhcp, dnscache, p9rdr services are running?

Just looked into task manager:

- vmcompute running
- LxssManager running
- LxssManger_User stopped
- Dhcp running
- Dnscache running
- Can't find p9rdr or any p9* services

**Comment by ad-on-is** [comment]
Strange, now everything works :-)

**Comment by therealkenc** [comment]
We can let the float need-repro for a bit and see if some me2s come in. Can't reproduce here either.

**Comment by hugomartins11** [comment]
I'm having exactly the same issue. Can't even install new distros from the Microsoft Store, since they won't install, after being downloaded.
I'm on Windows 10 Home, build 19018, with wsl 2 installed.

**Comment by ad-on-is** [comment]
> I'm having exactly the same issue. Can't even install new distros from the Microsoft Store, since they won't install, after being downloaded.
> I'm on Windows 10 Home, build 19018, with wsl 2 installed.

Do you have Docker Desktop 2.1.5.0 running? I remember, the only thing I did was quitting, but I'm not sure if that was really the fault.

**Comment by thisguychris** [comment]
Hi, 👋🏻, I just updated to 19023, seems to be working fine here

**Comment by sirredbeard** [comment]
There were some other reports of this in #4662.

**Comment by therealkenc** [comment]
#4662 is 18362 with a side of `wsl.exe --upgrade` (which probably hooped everything); that one probably can't be redeemed at this point. This one might (or might not) be something "new", if we can figure out the variable. I run docker desktop so that's _probably_ not it.

**Comment by pathaine** [comment]
> 
> 
> There were some other reports of this in #4662.

Thanks @sirredbeard!
Switching to WSL 2 worked, but only after following [these](https://answers.microsoft.com/en-us/windows/forum/all/error-server-execution-failed-when-trying-to-run/1e834b62-8106-4fc3-8bbf-9ab1b1218388) instructions.

**Comment by Ghostaunt** [comment]
Same for me but I resolved the issue with : 

CMD + R : optionalfeatures.exe
Disable Linux windows sub system
Reboot

CMD + R optionalfeatures.exe
Enable back Linux sub system
it works now

**Comment by hugomartins11** [comment]
> > I'm having exactly the same issue. Can't even install new distros from the Microsoft Store, since they won't install, after being downloaded.
> > I'm on Windows 10 Home, build 19018, with wsl 2 installed.
> 
> Do you have Docker Desktop 2.1.5.0 running? I remember, the only thing I did was quitting Docker, but I'm not sure if that was really the fault.

I'm not. I'm on windows 10 home, for laziness reasons really, so I can't even run docker

**Comment by sdv22** [comment]
Just got the same problem. wsl2 machine refused to start. The problem was that there was not enough disk space on the drive pointed as linux swap in .wslconfig.
wsl2 machine gaved "bus error" before. Not any sign of the real problem anywhere.

**Comment by europaisch** [comment]
Just finished upgrading to 19023, and literally the first thing I did was launch Windows Terminal to see what's up.
WSL2 machine started normally, the apache2 and mysql setup I had before works just as it was supposed to. 
Docker Desktop not installed either.

**Comment by thisguychris** [comment]
I'm in 19025, wsl2 working well here.

**Comment by phisad** [comment]
> Same for me after this update but I resolved the issue with :
> 
> CMD + R : optionalfeatures.exe
> Disable Linux windows sub system
> Reboot
> 
> CMD + R optionalfeatures.exe
> Enable back Linux sub system
> it works now

This worked for me for Windows Version 21H1 (OS Build 19043.867). The Ubuntu WSL wasnt starting anymore, the Ubuntu terminal wasnt listed in the Windows Terminal and the `wsl --list` command was "frozen". Now its looking fine again.
