### ISSUE TITLE
dpkg command gives BSOD

### ISSUE THREAD

**Issue by a-bj-q** [microsoft/WSL#4674]
I got twho blue screen of deaths in a row when issuing dpkg, so it seems broken.

run the following commands:

c:\>ubuntu config --default-user root

c:\>bash
root@gb: apt-get check
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
--- NOTE there might be something corrupt here...
root@gb: dpkg --configure -a

**Comment by a-bj-q** [comment]
uname -a
Linux gb 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sirredbeard** [comment]
I am unable to reproduce, see below.

Which build of Windows are you on? `C:\ ver`

Which build of Ubuntu are you running? `$ cat /etc/os-release`

I think dpkg failing is odd too. That leads me to think something unusual is happening. Are you running third-party security software or behind a VPN/proxy?

```
hayden@T470s ~ $ cmd.exe
'\\wsl$\Ubuntu\home\hayden'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Microsoft Windows [Version 10.0.18363.449]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Windows>ubuntu config --default-user root

C:\Windows>bash
root@T470s:/mnt/c/Windows# apt-get check
Reading package lists... Done
Building dependency tree
Reading state information... Done
root@T470s:/mnt/c/Windows# dpkg --configure -a
root@T470s:/mnt/c/Windows#
```

**Comment by therealkenc** [comment]
> 17134

Upgrade. Re-file if you are still seeing problems on 1903 aka 19H1 aka 18362, or 1903 aka ... if you can get it. You could send the minidump to secure@microsoft.com.

**Comment by sirredbeard** [comment]
Oh. Duh. I forget to check the kernel string.

**Comment by a-bj-q** [comment]
Don't worry about the c:/ path I just removed my home directory name for security reasons. 

So the standard response - upgrade. Well, here goes:

root@gb-cmlb-lt-aqua:/mnt/c/u-blox/scripts# apt update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [795 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [282 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [21.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [6128 B]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1024 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [315 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [8520 B]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [4044 B]
Get:13 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4024 B]
Get:14 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1856 B]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [572 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [189 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [13.2 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [4292 B]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [619 kB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [206 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [5904 B]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2568 B]
Fetched 4326 kB in 17s (251 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
77 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@gb-cmlb-lt-aqua:/mnt/c/u-blox/scripts# apt upgrade
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
root@gb-cmlb-lt-aqua:/mnt/c/u-blox/scripts#

Oh - does this start to look familiar (see above)?

I am saving this now because I can predict what will happen next, I will report back in a few minutes after the inevitable.

**Comment by a-bj-q** [comment]
Some extra details - the BSOD is a "BAD_POOL_CALLER".

It also happens after manually cleaning up /var/lib/dpkg/lock* and /var/lib/dpkg/updates/* and then running "apt update".

Microsoft Windows [Version 10.0.17134.706]

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by sirredbeard** [comment]
> Are you running third-party security software or behind a VPN/proxy?

**Comment by therealkenc** [comment]
Could be same #4537. `dpkg` invariably ends up trying to rename pinned folders, which is why #640 was open for so long. [#640 was closed tag external, but really isn't because the underlying cause remained.] In any event, both the `dpkg` case here and the `npm` case in #4537 has had issues related to the same cause in the past.

This one remains adrift so long as the repro is 17134. It _could_ be third party related per Hayden's WAG. It is going to be _some_ as yet unidentified variable, or there would be more screaming. [Past tense would have been more screaming circa 17134's release Spring 2018.]

**Comment by sirredbeard** [comment]
> Could be same #4537. `dpkg` invariably ends up trying to rename pinned folders, which is why #640 was open for so long.

Ah, gotcha.

> This one remains adrift so long as the repro is 17134. It _could_ be third party related per Hayden's WAG.

Not a complete WAG, this error shows up when using some Sophos endpoint tools.
