### ISSUE TITLE
Support hardware performance counters - WSL2

### ISSUE THREAD

**Issue by 6a4h8** [microsoft/WSL#4678]
How to enable them - currently they are disabled by default:

`[    0.184805] Performance Events: unsupported p6 CPU model 142 no PMU driver, software events only.`

I tried this [guide](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware). However when I type `Get-VM` the list is empty.

**Comment by therealkenc** [comment]
Wait your ask is different. References above still worthy, but de-duped.

**Comment by Dr-Emann** [comment]
I think this is a blocker for running [rr](https://rr-project.org/) in wsl2.

**Comment by zexuan** [comment]
Any plan to support hardware performance counters?

**Comment by bsld** [comment]
@zexuan You can enable those thinkering with vmwp binary. It is self explanatory once you open it with let's say IDA (you need to patch only the initial calls in the function setting the flags).  However you can't rr windows binaries so it's kind of pointless to me.

**Comment by fberlakovich** [comment]
@bsld Could you maybe expand how you did this? Hardware performance counters would be tremendously helpful for my work as I need reverse debugging and gdb `record` lacks a few features Mozilla `rr` has. 

Is this feature on the WSL2 roadmap at some point?

**Comment by kruxmeier** [comment]
The ProcessorSettings are read from some `VmRepository/configuration/settings/processors`.
If someone finds that repo you could alter the settings `enable_perfmon_pmu`, `enable_perfmon_lbr`, `enable_perfmon_pebs`, `enable_perfmon_ipt`.

**Comment by Trass3r** [comment]
> I tried this [guide](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware). However when I type `Get-VM` the list is empty.

FWIW `hcsdiag list` lists the container at least.
But `Get-VM -Id` does not accept that uuid.
Oh and: https://github.com/MicrosoftDocs/windowsserverdocs/pull/4984

**Comment by Trass3r** [comment]
> Hardware performance counters would be tremendously helpful for my work as I need reverse debugging and gdb `record` lacks a few features Mozilla `rr` has.
rr is also way faster.

[AutoFDO](https://github.com/google/autofdo) is also prevented by the lack of hw perf counters.
And general system profiling with perf and maybe LTTng.

**Comment by Radrik5** [comment]
> Or you [patch vmwp.exe](https://gist.github.com/kruxmeier/eb4becb7ba5c16192274f6fce3a47309).

The patch doesn't work in Windows 10 Build 19042. Patched WSL cannot start and prints "Incorrect function."

**Comment by Trass3r** [comment]
Well since they change the file with every update patching it is not really an option anyway.

**Comment by GitMensch** [comment]
... and patching that way seems to be host-processor specific, too ...

**Comment by Nufflee** [comment]
Any updates on this?

**Comment by benhillis** [comment]
This change is makings its way to the Store version of WSL soon.

**Comment by GitMensch** [comment]
😕 Which change? Do you patch vmvp.exe in the distributed WSL? Which "store version" (only distributions are part of the store, not WSL itself, which is a Windows feature and therefore updated with Windows update)?  ❓

**Comment by Trass3r** [comment]
No they finally fixed it but it's gonna be Win11-only it seems.
https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/

**Comment by GitMensch** [comment]
> No they finally fixed it

Yay!

> but it's gonna be Win11-only it seems.

Oh no, the store is blocked (and there's no Win11 for a multitude of persons) - @benhillis Can you please ensure that this is getting to the WSL _feature_, too (or at least, if this is _really_ necessary push that over to W10, too).

**Comment by GitMensch** [comment]
That shows no hardware counters support yet, @eiennohito does the perf output show any different?

You may need to `apt install linux-perf` (sometimes named linux-tools or just perf, depending on your GNU/Linux distribution the installation may be done with `yum install` or `pacman -S` or ...

I assume
> This change is makings its way to the Store version of WSL soon.

likely means that "it" (whatever it actually is, that wasn't named so far) isn't available _currently_ but _soon_ (for W11/Store) and _possibly_ available with a (feature) update to W10 someday.

**Comment by Trass3r** [comment]
Any updates?

**Comment by Trass3r** [comment]
https://github.com/microsoft/WSL/releases

**Comment by GitMensch** [comment]
Thanks @Trass3r for the update notice, so...

What is the output of the following, now?

```sh
perf stat -e br_inst_retired.conditional true
dmesg | grep PMU
```

**Comment by oscarbg** [comment]
dmesg | grep PMU
[    0.405297] [Firmware Bug]: the BIOS has corrupted hw-PMU resources (MSR 189 is 100430000)
[    0.410568] Intel PMU driver.

./perf stat -e br_inst_retired.conditional true

 Performance counter stats for 'true':

             23313      br_inst_retired.conditional:u

       0.001944800 seconds time elapsed

       0.001218000 seconds user
       0.000000000 seconds sys

**Comment by GitMensch** [comment]
> [    0.405297] [Firmware Bug]: the BIOS has corrupted hw-PMU resources (MSR 189 is 100430000)
[    0.410568] Intel PMU driver.

@oscarbg Do you mind creating a bug report for that? I _guess_ that _something_ will not work correctly if dmesg says it is buggy.

**Comment by hbirler** [comment]
```
> dmesg | grep PMU
[    0.220027] Performance Events:  AnyThread deprecated, Icelake events, 32-deep LBR, full-width counters, Intel PMU driver.
```

I seem to not have the `br_inst_retired.conditional` event:

```
> perf list | grep br_inst_retired
  br_inst_retired.all_branches
  br_inst_retired.cond
  br_inst_retired.cond_ntaken
  br_inst_retired.cond_taken
  br_inst_retired.far_branch
  br_inst_retired.indirect
  br_inst_retired.near_call
  br_inst_retired.near_return
  br_inst_retired.near_taken
```

**Comment by GitMensch** [comment]
@hbirler and you are on https://github.com/microsoft/WSL/releases/tag/0.50.2?

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/0.50.2.

**Comment by benhillis** [comment]
@oscarbg - would you please create a new issue for the corrupt bios issue?

**Comment by Trass3r** [comment]
Does anyone know if this also affects `/sys/kernel/tracing/` functionality?

**Comment by fifididi** [comment]
Please please please bring this to win 10 asap :(

**Comment by StephanDollberg** [comment]
Anybody got IPT working with this?

**Comment by Trass3r** [comment]
fwiw `/sys/devices/intel_pt` does not exist.

**Comment by GitMensch** [comment]
We know that this won't land in Windows 10 - but is there any option to install the new WSL2 release in a Windows 11 "normal" version (no insider)?
Opening the msixbundle fails with an error message that this package cannot be installed with app-installer...

**Comment by mati865** [comment]
@GitMensch you have to install it using shell with admin rights. I'm away from home and don't have the command on my phone.

**Comment by GitMensch** [comment]
I've missed something - people that check for `br_inst_retired` on WSL2 and not founding it likely don't use an Intel processor (which provides this event). For AMD it is likely better to test for `perf stat -e ex_ret_cond true` instead ... (which is available)

**Comment by lemire** [comment]
My tiger-lake processor does not appear to be supported. Is that expected?

<img width="737" alt="image" src="https://user-images.githubusercontent.com/391987/167939725-a47901fe-0749-4fb3-bdef-a4381477e6c8.png">

I have an up-to-date WSL, and up-to-date Ubuntu and an up-to-date Windows.

**Comment by yingdam** [comment]
> My tiger-lake processor does not appear to be supported. Is that expected?
> 
> <img alt="image" width="737" src="https://user-images.githubusercontent.com/391987/167939725-a47901fe-0749-4fb3-bdef-a4381477e6c8.png">
> 
> I have an up-to-date WSL, and up-to-date Ubuntu and an up-to-date Windows.

My processor is also tiger-lake, and got the same output with no PMU driver.

**Comment by Trass3r** [comment]
@benhillis probably needs to be updated for newer processors?

**Comment by GitMensch** [comment]
Not sure, but I _guess_ that's kernel related. Would be nice to get a 5.15 kernel, soon (release-ring has 5.10.102 as noted in the images above, not sure if insiders have a newer version).

**Comment by Trass3r** [comment]
Ah yeah worth a try: https://github.com/nathanchance/WSL2-Linux-Kernel

**Comment by lemire** [comment]
Upgrading the kernel to @nathanchance's version does not help me.

<img width="712" alt="Capture d’écran 2022-05-26 101423" src="https://user-images.githubusercontent.com/391987/170505781-9eaa42a4-e422-41d2-8701-0de98df7f913.png">

**Comment by jrmuizel** [comment]
`unsupported p6` comes from https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/arch/x86/events/intel/p6.c#L272 and this code path is likely being triggered because `!cpu_has(&boot_cpu_data, X86_FEATURE_ARCH_PERFMON)` from https://github.com/torvalds/linux/blob/a6b450573b912316ad36262bfc70e7c3870c56d1/arch/x86/events/intel/core.c#L5618


`X86_FEATURE_ARCH_PERFMON` is set when:
```
	if (c->cpuid_level > 9) {
		unsigned eax = cpuid_eax(10);
		/* Check for version and the number of counters */
		if ((eax & 0xff) && (((eax>>8) & 0xff) > 1))
			set_cpu_cap(c, X86_FEATURE_ARCH_PERFMON);
	}
```

So the `cpuid` values in the guest might explain what's going on.

**Comment by lemire** [comment]
Possibly related https://github.com/microsoft/WSL/issues/8155

**Comment by Evian-Zhang** [comment]
I am using Intel i9-12900K CPU with latest Windows 11, latest WSL2 (using `wsl --update`) and latest Ubuntu 22.04, but I still can't using Intel PT:

```console
dmesg | grep PMU
[    0.040335] Performance Events: unsupported p6 CPU model 151 no PMU driver, software events only.
```

Linux kernel version:

```console
uname -a
Linux evian-workstation 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Evian-Zhang** [comment]
I am using Intel i9-12900K CPU with latest Windows 11, latest WSL2 (using `wsl --update`) and latest Ubuntu 22.04, but I still can't using Intel PT:

```console
dmesg | grep PMU
[    0.040335] Performance Events: unsupported p6 CPU model 151 no PMU driver, software events only.
```

Linux kernel version:

```console
uname -a
Linux evian-workstation 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Trass3r** [comment]
> We are evaluating bringing the store version of WSL back to older versions of Windows 10, but cannot yet comment on timelines.

@benhillis is there any hope the decoupled WSL will still land on Win10?

**Comment by Trass3r** [comment]
It just landed in KB5020030!

**Comment by GitMensch** [comment]
There's no info in https://support.microsoft.com/en-us/topic/november-15-2022-kb5020030-os-builds-19042-2311-19043-2311-19044-2311-and-19045-2311-preview-237a9048-f853-4e29-a3a2-62efdbea95e2 related to WSL...

**Comment by Trass3r** [comment]
I know. But after it you get the 1.0 store version via `wsl --update`.

**Comment by clemenswasser** [comment]
@Trass3r do you know if there is a KB5020030 equivalent for Win 11 22H2? (Even with WSL v1.0, perf counters are still not working for me, Alderlake with latest Win 11 updates)

**Comment by Trass3r** [comment]
There's no need on Win11, that KB is more of backport of the changes that allow the separation of WSL from the base system.
You're probably looking for https://github.com/microsoft/WSL/issues/8155.

**Comment by apjanke** [comment]
Hi, folks. Thanks for working on this!

Could someone summarize where the state of hw perf counters on Windows 10 ended up? I read through this ticket and the related linked pages, but I'm not sure I fully followed it.

My read here was that [this "it just landed...!" comment](https://github.com/microsoft/WSL/issues/4678#issuecomment-1318579235)

**Comment by Trass3r** [comment]
https://superuser.com/a/1754527

`wsl --update --web-download`

**Comment by vimkim** [comment]
Any tigerlake updates?

pwsh:
```pwsh
> wsl --update --pre-release --web-download
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

wsl ubuntu

```bash
$ uname -a
Linux WIN-ER7KSLJRTMP 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ dmesg | grep -i 'perf' | clip
[    0.078762] Performance Events: unsupported p6 CPU model 170 no PMU driver, software events only.
[    0.327316]     Performance counters on
```

I wish I could run rr debugger on my laptop.

**Comment by lux-QAQ** [comment]
@kruxmeier 
> The ProcessorSettings are read from some `VmRepository/configuration/settings/processors`.ProcessorSettings 是从某些 `VmRepository/configuration/settings/processors` . If someone finds that repo you could alter the settings `enable_perfmon_pmu`, `enable_perfmon_lbr`, `enable_perfmon_pebs`, `enable_perfmon_ipt`.如果有人找到那个仓库，可以修改设置 `enable_perfmon_pmu` 、 `enable_perfmon_lbr` 、 `enable_perfmon_pebs` 、 `enable_perfmon_ipt` 。
> 
> Or you [patch vmwp.exe](https://gist.github.com/kruxmeier/eb4becb7ba5c16192274f6fce3a47309).  或者你修补 vmwp.exe。

I tried to force IsEnabling PerfmonPmu to return True.
But this seems to cause problems when WSL starts up.
Is this because the driver does not support it or do I need to modify other areas?

![Image](https://github.com/user-attachments/assets/a3b7f13b-f5c9-4bbe-ab78-476c312f041c)

![Image](https://github.com/user-attachments/assets/3e8df310-dba7-48ca-8ea0-19992851a3ae)

**Comment by Trass3r** [comment]
WSL is open source now.
And just force-enabling does not work: https://github.com/microsoft/WSL/issues/8155#issuecomment-2916572800
