### ISSUE TITLE
Unable to install Ubuntu Distro WslRegisterDistribution failed with error: 0x8007071a

### ISSUE THREAD

**Issue by kdcllc** [microsoft/WSL#4681]
Windows build number:  Microsoft Windows [Version 10.0.19023.1]

After upgrading to the latest Windows Insider Preview, I am not able to install `Ubuntu` distro.

I had previous version of `wsl` enabled so I ran: `Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` and then `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

When `Ubuntu` is insalled from Windows store and first time open I get the following:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007071a
Error: 0x8007071a The remote procedure call was cancelled.

Press any key to continue...
```
In addition if I try to run `wsl -l` I get the following as well:

```
wsl -l
The remote procedure call was cancelled.
```

The expected behavior is to have `Ubuntu` installed.

**Comment by europaisch** [comment]
Same build here, but wsl -l works.

Also just to make sure, you did restart after disabling and enabling the feature, right? You also need to have Virtual Machine Platform enabled, so try having that on and off at the same time perhaps?

**Comment by kdcllc** [comment]
@europaisch, I did all of the steps and still have the same issue...

**Comment by europaisch** [comment]
Is your default wsl version set to 2?

**Comment by kdcllc** [comment]
Yes I set it to `wsl --set-default-version 2`

**Comment by kdcllc** [comment]
I traced the issue to `LxssManager` not being to run
https://github.com/microsoft/WSL/issues/4474#issuecomment-558882794.

**Comment by therealkenc** [comment]
Assume (?) this was unblocked (worked around) at some point. If not please submit detailed logs and we can revisit/reopen.
