### ISSUE TITLE
wslpath does not translate some characters correctly

### ISSUE THREAD

**Issue by ko1nksm** [microsoft/WSL#4682]
**Windows build number:**

  * Version 10.0.18363.476
  * Version 10.0.19013.1 (WSL1 / WSL2)

**What you're doing and what's happening:**

It translate correctly on lxfs. This is the desired result.

```console
/tmp$ wslpath -u "$(wslpath -w ':*?')"
/tmp/:*?
```

It does not translate on drvfs and 9p.

```console
/mnt/c/temp$ wslpath -u "$(wslpath -w ':*?')"
/mnt/c/temp/
```

```console
/mnt/c/temp$ wslpath -u "$(wslpath -w ':*?')" | hexdump -C
00000000  2f 6d 6e 74 2f 63 2f 74  65 6d 70 2f ef 80 ba ef  |/mnt/c/temp/....|
00000010  80 aa ef 80 bf 0a                                 |......|
00000016
```

It seem not to be translated characters correctly that cannot be used on Windows.

**What's wrong / what should be happening instead:**

It should be  translate on drvfs and 9p same as on lxfs.

**Comment by therealkenc** [comment]
> that cannot be used on Windows.

They can; it would just be foolish to do so. By design ref #1514.

![image](https://user-images.githubusercontent.com/7049700/72689207-dbddc780-3ac3-11ea-82f1-c81b870a5d64.png)
