### ISSUE TITLE
Terminator doesn't working in WSL2

### ISSUE THREAD

**Issue by mituso89** [microsoft/WSL#4684]
Yesterday My terminator still working however it doesn't working now.

export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0 in .zshrc
 Vcxsrv is runing and i was turn on Disable access control
When i run DISPLAY.0 terminator &
I received an error

[1] 676
zsh: command not found: DISPLAY.0
[1]  + 676 exit 127   DISPLAY.0 terminator
 
I tried reinstall terminator and Install new wsl2 with terminator however it still not working.

Pls help me. Thank you so muck

**Comment by Biswa96** [comment]
Display is an environment variable now, use `$DISPLAY`.

**Comment by mituso89** [comment]
> Display is an environment variable now, use `$DISPLAY`.
Thank you. I tried but Don't working for me

**Comment by bvierra** [comment]
`DISPLAY.0 terminator &`

would have never worked, if you are already exporting DISPLAY (as it shows you are) you should just run

`terminator`

I can confirm this is working just fine for me

**Comment by mituso89** [comment]
Thank bvierra. It's working for me.

**Comment by therealkenc** [comment]
> exporting DISPLAY (as it shows you are) you should just run `terminator`.

Or equivalent `$ DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0 terminator` if you _aren't_ exporting `$DISPLAY`.

**Comment by JulianNicholls** [comment]
The key to the problem is that WSL2 is a VM with a different IP address from the main Windows system. When VxCsrv starts, it starts on the Windows IP address. 

Unfortunately, the contents of `/etc/resolv.conf` reflect the WSL2 VM IP address, so that doesn't help.
The bottom line is that you need to explicitly specify the Windows IP address, e.g.

`DISPLAY=192.168.1.229:0 terminator &`

**Comment by ramrasi** [comment]
> 
> 
> The key to the problem is that WSL2 is a VM with a different IP address from the main Windows system. When VxCsrv starts, it starts on the Windows IP address.
> 
> Unfortunately, the contents of `/etc/resolv.conf` reflect the WSL2 VM IP address, so that doesn't help.
> The bottom line is that you need to explicitly specify the Windows IP address, e.g.
> 
> `DISPLAY=192.168.1.229:0 terminator &`

Yes. It works. Thanks

**Comment by bvierra** [comment]
> The key to the problem is that WSL2 is a VM with a different IP address from the main Windows system. When VxCsrv starts, it starts on the Windows IP address.

You can add the following to your .bashrc and it works fine as the nameserver in the resolv.conf is your windows machine which you will be start VxCsrv on

    hostip=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')            
    export DISPLAY=$hostip:0
