### ISSUE TITLE
Is telemetry coming to WSL2?

### ISSUE THREAD

**Issue by Biswa96** [microsoft/WSL#4686]
* Windows version: 10.0.19023.1
* Detection:

  - Download [Strings from Sysinternals][1]. Run these two commands (output are also added):

This find `tel` string from the `init` binary in System32.

```cmd
$> strings.exe C:\Windows\System32\lxss\tools\init | find /i "tel"
telagent
StartTelemetryLogger
Could not start telemetry agent.
.\\telemetry.cpp
<3>init: (%d) ERROR: %s:%u: TELEMETRY: %s %s
ConfigUpdateLanguage
```
  - Extract `init` from `initrd.img` file: `cpio -i -F initrd.img`

  - Run Strings also with this extracted `init` file:

```cmd
$> strings.exe initrd | find /i "tel"
/telagent
StartTelemetryAgent
```

* Questions: Is telemetry coming to WSL2? Will there be any article or blog post about what it is collecting? Is there any toggle switch to turn it off from users' side?

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/strings

**Comment by fpqc** [comment]
@Biswa96 afaik WSL has always had telemetry.  This is in order to detect failing syscalls and such.

**Comment by WSLUser** [comment]
If they want to follow GDPR (and now CCPA) (which MS is required to do), then an option to disallow the telemetry should be implemented.

**Comment by fpqc** [comment]
@WSLUser WSL is a kernel module of the windows operating system.  Its telemetry is tied into the telemetry of OS itself.  It's not a WSL thing.  If MS is confident that its telemetry meets GDPR and CCPA standards for the whole OS, then a fortiori it also meets them for a small part of the OS.

**Comment by benhillis** [comment]
FYI Windows (and WSL by extension) is fully GDPR compliant, and you can view any of the diagnostic data being generated by your machine by going to the "View your diagnostic data" section of the settings app.

**Comment by Biswa96** [comment]
Didn't get the answers of my questions.

1. Does WSL2 `init` collects any data?
2. If yes, then what data?
3. If yes, then is there any way to stop it?
Any documentations may be helpful, like [microsoft/terminal: organization](https://github.com/microsoft/terminal/blob/master/doc/ORGANIZATION.md).

**Comment by fpqc** [comment]
@Biswa96 They didn't add in more telementry to WSL-init.  The telemetry that they're generating is coming through the driver.  You can try to decompile the WSL-init, and iirc some people have already done so.  Its code flow is well-understood.  All it does is set up the special WSL pipes and does some interop handling.
