### ISSUE TITLE
do not treat Windows subfolders in $PATH like executables

### ISSUE THREAD

**Issue by Konfekt** [microsoft/WSL#4688]
On Windows 10, 1903,  WSL openSUSE 15.1, every subfolder contained in one of the Windows folders appended to `$PATH` is handled just like an executable: For example, if in `/mnt/c/Program Files (x86)/Lua/5.1/clibs` in `$PATH` there is a folder `md5` (but no executable with such a name), then calling `md5` on the command-line returns `permission denied`. Instead, subfolders should not be handled like executables, that is, expected is `no such command`.

**Comment by therealkenc** [comment]
Can't repro here. [`md5` makes for a bad test case because I get a suggestion to install Linux `md5` because it's not found.]

![image](https://user-images.githubusercontent.com/7049700/69109727-7884da00-0a2d-11ea-8908-156b0bc7168c.png)

The permission denied suggests #4104 but can't tell without a repro.

**Comment by Konfekt** [comment]
The exact version according to `ver.exe` is `Microsoft Windows [Versione 10.0.18362.476]`. It is an issue of `zsh` that  occurs as well under Linux, but does not occur under `bash`. It is therefore independent of `WSL`.

![immagine](https://user-images.githubusercontent.com/7195553/69145397-d79a2b80-0acd-11ea-97f2-f09095da9dc7.png)

**Comment by Konfekt** [comment]
Apparently the same issue of ZSH is related at 

https://stackoverflow.com/questions/23297832/weird-rails-error-permission-denied-bin-rails-for-old-rails-apps

and

https://stackoverflow.com/questions/51073014/zsh-permission-denied-gam

however, without any indication how to disable directories in $PATH becoming global executables.

**Comment by therealkenc** [comment]
Right, more in /dupe #3833 #3886 et al.
