### ISSUE TITLE
ADB in WSL2

### ISSUE THREAD

**Issue by yanotoma** [microsoft/WSL#4692]
ADB (Android Debug Bridge) used to work on WSL1 but no longer in WSL2
The catch was to use the same version in both windows and linux

**WSL1**
![image](https://user-images.githubusercontent.com/2429644/69091232-dd353a00-0a17-11ea-8123-595ad9f52478.png)

**WSL2**
![image](https://user-images.githubusercontent.com/2429644/69092413-52097380-0a1a-11ea-9a3c-9dff22d2144a.png)

**OS**
![image](https://user-images.githubusercontent.com/2429644/69091472-5af94580-0a18-11ea-8bad-8ab3d6f16bb5.png)

**Comment by therealkenc** [comment]
TCP bridge. Likely dupe #4619 but having pulled the trigger too fast once already will let it float.

**Comment by andreialecu** [comment]
See https://github.com/microsoft/WSL/issues/4619#issuecomment-596990676 for a workaround.

**Comment by gusflopes** [comment]
Workaround didn't work for me...

**Comment by anaganisk** [comment]
@gusflopes For me it was windows firewall issue, check  your firewall settings, after correcting that it worked.

**Comment by steelbrain** [comment]
Fwiw, what worked for me is to start the ADB server in WSL and make the Host Windows connect to it. Set `ADB_SERVER_SOCKET=tcp:localhost:5037` in your windows environment variables.

Also make sure that your host and WSL adb are the same version or else they'll keep killing each other's servers

**Comment by Newbie012** [comment]
I was able to connect over wifi without the need of installing on both sides. See - https://developer.android.com/studio/command-line/adb/?gclid=CjwKCAjw2dD7BRASEiwAWCtCbxKzwu63T-HpLaIp8ASO1aNA6aRl7_8Wvc2LqCvf3BI3umOlQQaOtBoCQrEQAvD_BwE&gclsrc=aw.ds#wireless

**Comment by therealkenc** [comment]
This one ("used to work on WSL1 but no longer in WSL2") is #4619. It's analogous X11 Server on Windows, Database server on Windows, etc etc. Rather than dupe, porting over to the discussion forum for tips/tricks ADB over TCP with WSL2. Thanks for the input everyone.
