### ISSUE TITLE
WSL2 on ARM64 runs very slow when CPU otherwise idle

### ISSUE THREAD

**Issue by brion** [microsoft/WSL#4696]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.19025.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

In a WSL2 Ubuntu virtual machine (current LTS) on ARM64 Surface Pro X running Insiders build 19025, am running a multithreaded CPU-intensive program. (In this case a Rust program, though something simpler may be fine.) The program's reported runtimes are much slower than expected when the machine is left sitting, but speeds up to expected speeds when exercising CPU on the Windows side, such as by tapping the 'windows' key to cycle the Start Menu.

Task Manager shows very low CPU usage as well as a very low CPU clock speed (<0.5 GHz) during the slow periods, even though 'top' or 'htop' in Linux shows heavy usage.

I suspect that the CPU is being throttled based on what it thinks is low usage on the Windows side, slowing down the Linux processes, but could be wrong about the details...

Steps to reproduce:

* Surface Pro X, updated to Insiders current build
* install Ubuntu from microsoft store
* `wsl --set-version Ubuntu 2`
* install Rust:
    * `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
* `git clone https://github.com/brion/mtpng.git`
* `cd mtpng`
* `./test-sample.sh dual4k.png --repeat=1000`

This will take a few moments to compile then start spitting out compression times per iteration, like this:

```
Using 8 threads
dual4k.png -> ../out/dual4k.png
Done in 954 ms
Done in 983 ms
Done in 848 ms
Done in 422 ms
Done in 201 ms
Done in 156 ms
Done in 172 ms
Done in 362 ms
Done in 714 ms
```

![2019-11-18 (15)](https://user-images.githubusercontent.com/103075/69123571-90248880-0a56-11ea-826d-e81bdd1ad369.png)

* What's wrong / what should be happening instead:

When the machine is otherwise idle, times are often 800-1000ms but should be consistently in the 160-200ms range as with WSL1. These numbers can be reached when triggering some minor CPU usage on the Windows side such as hitting the 'windows' key to cycle the Start Menu, or running a sustained 1-thread CPU program on the Windows side.

**Comment by zlim** [comment]
I'm observing similar symptoms with a different workload (make -j 8 shows ~100% cpu utilization in Linux, but very low utilization in Windows). Any suggestions from WSL team on how to debug this?

**Comment by nathansoz** [comment]
@benhillis @craigloewen-msft I'm also hitting this when compiling dotnet core applications in WSL2. If you need more information or want to look at my device I can reach out internally.

**Comment by benhillis** [comment]
@nathansoz - Yes please start a thread with Craig and I and we can loop in the appropriate people.

**Comment by imbushuo** [comment]
I observed the identical problem with WSL2 and Hyper-V VM - it seems that the power management driver (specifically Qualcomm PEP / qcpep8180.sys) do DVFS (dynamic voltage and freq scaling) based on the management OS partition's workload.

Putting some workload on the host OS (e.g. running 7-zip) slightly improves WSL2 performance (but this is an ugly workaround).

**Comment by Sonicadvance1** [comment]
This is very much a real issue.
PEP can only see the load outside the VM so the CPUs never clock up.
This is a pain and as an end-user I don't see any real way to work around it.
This needs to be fixed on the Microsoft and Qualcomm side of things, Microsoft is shipping the Pro X as a high end product even!

**Comment by dgurney** [comment]
Any status updates on this? I hate asking questions like this but it's been a while, and this still happens on build 20175.

**Comment by davide-rota** [comment]
Still the same. WSL2 on SPX is really great but this CPU problem defeats the purpose...
![image](https://user-images.githubusercontent.com/11763/92416119-3d8a9900-f15c-11ea-9dec-67fc5b916ae4.png)

**Comment by Gerdya** [comment]
Can we get a fix for this please? It is been a year and I believe all devices are affected by this bug. 

Are you really believing it is a permanent solution that we keep running a non blocking host process for the sole purpose of keeping the frequencies up? Among other things, this a very bad workaround, because we loose performance and the battery is drained for no reasons.

**Comment by brion** [comment]
@benhillis did you loop in the right people on this? Is there anything we can do as users to provide data or feedback which will help prioritize development? Thanks.

**Comment by dgurney** [comment]
[I submitted feedback in case it helps to get the priority up.](https://aka.ms/AAa4uqw)

**Comment by brion** [comment]
@nathansoz @benhillis @craigloewen-msft hi do you folks still work at Microsoft? If so, I'd really appreciate a status update about this bug. Has it been determined to be not worth fixing? Or is it being worked on but something's holding it up in the kernel or other parts of Windows? Is there no way you can say anything without violating NDA?

Proof of life would be great. ;) <3

**Comment by nathansoz** [comment]
@brion So I'll let @benhillis or @craigloewen-msft decide how much they can share, but I do continue to push on this issue internally as an interested party.

**Comment by benhillis** [comment]
Hopefully we will have some news to share soon, progress is being made.

**Comment by brion** [comment]
Thanks for the update! Just knowing whether something is happening is a big help.

**Comment by Gerdya** [comment]
Thanks for the update! I am looking forward.

**Comment by nathansoz** [comment]
I believe that insider build 20262 or higher should have _some_ improvements (I could be misreading the commit history and it might be in the build that comes out immediately after 20262). There are still known issues that are being worked on and I'll keep pushing internally to get those resolved.

**Comment by brion** [comment]
@nathansoz thanks, I'll check it out once the build finishes downloading and installing later!

**Comment by nathansoz** [comment]
To be clear, the performance I'm seeing still has some dependency on the outside host, but performance seems better (before I was averaging ~900ms on your benchmark at idle and now it averages ~400ms at idle).

![image](https://user-images.githubusercontent.com/6821708/99579473-1558bb00-2993-11eb-9343-b5e2a0f01023.png)

**Comment by benhillis** [comment]
I have some good news to report, this issue should be fixed in [21292](https://blogs.windows.com/windows-insider/2021/01/13/announcing-windows-10-insider-preview-build-21292/).  I'd encourage users to give this a try and let us know if you continue to have lower than expected performance on ARM64.

**Comment by dgurney** [comment]
![kuva](https://user-images.githubusercontent.com/12816807/104650698-43baf400-56bf-11eb-93b4-c2cee131f860.png)
Excellent, thank you!

**Comment by benhillis** [comment]
@dgurney - that was quick!  Things working better for you now?

**Comment by dgurney** [comment]
> 
> 
> @dgurney - that was quick! Things working better for you now?

@benhillis yes, clocks are staying exactly where they should under non-synthetic load as well :)

**Comment by Sonicadvance1** [comment]
Confirmed myself here that this is working on my ProX as well.

**Comment by brion** [comment]
Confirmed fixed on my Surface Pro X with this week's update installed. Well done! It's performing quite well now, clocks up the cores the same whether it's WSL1 or WSL2 though WSL1 gets a slight advantage in my CPU-bounded benchmark as expected.

This is great news, I'm very happy. :) Closing.

**Comment by zlim** [comment]
Awesome! Thanks @benhillis for tracking this down 💪

![image](https://user-images.githubusercontent.com/748121/104687933-f76ab680-56b4-11eb-8e5d-d9b2d216260d.png)
