### ISSUE TITLE
VAAPI: /dev/dri not found

### ISSUE THREAD

**Issue by suvl** [microsoft/WSL#4700]
Trying to use `ffmpeg` with video acceleration throught VAAPI, I simply tried to `ls /dev/dri` but there's no folder in there. Is VAAPI supported? Will it be supported anytime soon?

**Comment by Biswa96** [comment]
Any commandline example.

**Comment by suvl** [comment]
@Biswa96 from [the docs](https://trac.ffmpeg.org/wiki/Hardware/VAAPI), we can try something like:
`ffmpeg -vaapi_device /dev/dri/renderD128 -i input.mp4 -vf 'format=nv12,hwupload' -c:v h264_vaapi output.mp4`
for hardware-accelerated encoding of h264 using the [VA-API](https://wiki.archlinux.org/index.php/Hardware_video_acceleration).

**Comment by therealkenc** [comment]
/dupe #829. There is no `/dev/dri` in WSL2 (or 1). In the future event that #829 flips status but libVA hw acceleration doesn't work, one could hypothetically file a bug/feature submission on lack thereof.

**Comment by outhud** [comment]
This was not a duplicate. The other issue is about NVIDIA's hardware acceleration. 
This issue was about using Intel's VA-API (which uses /dev/dri/renderD128 for example). This does not get created under WSL2 Ubuntu, and cannot be used.
