### ISSUE TITLE
Upgraded from 1803 to 1909, LxssManager refuses to start

### ISSUE THREAD

**Issue by dcleaver-rbr** [microsoft/WSL#4702]
* Your Windows build number:
18363.476 (1909)

* What you're doing and what's happening:
    Upgraded from Windows 17134 (1803) to 18363 (1909).

    Previously had WSL installed and working. After upgrade, the Lxssmanager service refuses to start:
![image](https://user-images.githubusercontent.com/42941881/69353899-27682680-0c77-11ea-80aa-c3e830d79617.png)

    Disabled the WSL feature and re-enabled it again - no change.

    Uninstalled Ubuntu, disabled WSL, re-enabled, re-installed Ubuntu - no change.

* What's wrong / what should be happening instead:
    Lxssmanager service should start.
    Ubuntu bash should not error with:
    ```
    Installing, this may take a few minutes...
    WslRegisterDistribution failed with error: 0x80080005
    Error: 0x80080005 Server execution failed
    ```
[lxcore.zip](https://github.com/microsoft/WSL/files/3875582/lxcore.zip)

**Comment by haydennyyy** [comment]
It's a dumb question, but have you tried `sc start LxssManager` as admin?

**Comment by benhillis** [comment]
Something strange seems to have happened during upgrade, could you try removing the Windows Subsystem for Linux Optional Feature, rebooting, and re-enabling it?

**Comment by dcleaver-rbr** [comment]
@benhillis yep, I've done that multiple times.

@haydennyyy yep, tried that.

**Comment by ad-on-is** [comment]
Might this be related to an issue I posted a while back?
https://github.com/microsoft/WSL/issues/4673

**Comment by ygj6** [comment]
the same issue

**Comment by tigerlei010** [comment]
The same issue on my windows 10 10.0.18362.592. run `sc start LxssManager ` as admin, it failed.

**Comment by kosztkas** [comment]
I have the same issue, just upgraded from 1809 to 1909 (10.0.18363.778).
Previously everything was working fine.

**Comment by heartbeast** [comment]
The same issue on my win10 10.0.18363.720. 
run sc start LxssManager as admin didn't output anythin, but the service is still STOPPED.

**Comment by leephung** [comment]
anything update on this issue please?

**Comment by justor95** [comment]
> It's a dumb question, but have you tried `sc start LxssManager` as admin?

It's a dumb answer.

**Comment by strank** [comment]
Similar issue, but upgraded from 1909 to 2004. Also no distro installed before the upgrade, only the wsl component.

Now I see the same symptom: LxssManager cannot start. Error 1: Incorrect Function.

**Comment by dcleaver-rbr** [comment]
Seems to be working for me now (still on 1909). I _think_ it's down to Sophos Safeguard (corporate machine). I upgraded to Sophos Safeguard 8.30 and WSL now seems to be working fine.

Happy for this to be closed in my case, but see that others are experiencing the same issue.

**Comment by michelepagot** [comment]
from a generic Google search maybe it is what cited in Sophos release letter as
`DPSGN-15431	Windows subsystem for linux no longer working (lxssmanager does not start) on Windows 10 version 1903 (19H1)`

**Comment by Planzo** [comment]
> Seems to be working for me now (still on 1909). I _think_ it's down to Sophos Safeguard (corporate machine). I upgraded to Sophos Safeguard 8.30 and WSL now seems to be working fine.
> 
> Happy for this to be closed in my case, but see that others are experiencing the same issue.

Thanks for this hint! I wasn't able to update Sophos Safeguard from 8.20 to 8.30 due to corporate limitations, but I could turn Bitlocker off, uninstalled Sophos Safeguard, rebooted and everything worked fine again! After this I reinstalled Sophos Safeguard again, re-encrypted the hardware again and it still worked.
BTW: I've upgraded 1809 to 20H2.
