### ISSUE TITLE
Cannot access file:/// uri from WSL2

### ISSUE THREAD

**Issue by edyu** [microsoft/WSL#4704]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19025.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
when running commands in the shell that uses Start command. 
for example, I was running `fish_config` or `help` in the fish shell. Both of which use the Start command. 
For `fish_config` it calls
`Start file:///home/ed/.cache/fish/web_config-9S5EM8.html`
and for `help` it calls `Start file:///usr/share/doc/fish/index.html`

* What's wrong / what should be happening instead:
The Linux path are not recognized in WSL. To make it easier to run commands in WSL2, I'd think all the Linux path should be recognized while in WSL2.
Here are the commands and the errors:
<pre>
~ fish_config                                                       
Web config started at 'file:///home/ed/.cache/fish/web_config-9S5EM8.html'. Hit enter to stop.
Start : This command cannot be run due to the error: The system
cannot find the file specified.
At line:1 char:1
+ Start "file:///home/ed/.cache/fish/web_config-9S5EM8.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process]     , InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.P     owerShell.Commands.StartProcessCommand

Shutting down.
 ~ help                                                   
Start : This command cannot be run due to the error: The system
cannot find the file specified.
At line:1 char:1
+ Start "file:///usr/share/doc/fish/index.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process]     , InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.P     owerShell.Commands.StartProcessCommand
</pre>

**Comment by karuboniru** [comment]
So...you are calling `PowerShell` to open `/mnt/c/xxx` by this?
```
$ powershell.exe start /mnt/c/xxx
```
**That will never work**, you need to use
```
$ powershell.exe start `wslpath -w '/mnt/c/xxx'`
```
Remember that you don't have `/mnt` for Windows programs.

**Comment by edyu** [comment]
I wasn't. This is mainly for fish shell. I'll inform them of this as well.
