### ISSUE TITLE
Cannot install WSL

### ISSUE THREAD

**Issue by brumeistern** [microsoft/WSL#4705]
I am trying to enable WSL. I am running a "lite" version of Windows 10.
Windows Linux Subsystem does not show in "Turn Windows features on or off"
Is there a way to install from an installation file, like it can be done for .NET Framework ?
When I try to enable, I get the following:
PS C:\Users\Administrator> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux         Enable-WindowsOptionalFeature : The specified package is not valid Windows package.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by benhillis** [comment]
@brumeistern - By "lite" do you mean Windows 10 S?

**Comment by brumeistern** [comment]
No, I mean one of those "lite" version people build in order to use much less resources. My WinSXS folder is almost empty, meaning the resources were removed from the ISO. There is a file: microsoft-windows-netfx3-ondemand-package.cab used to install .NET Framework 3.5. I need something similar for WSL. Do you know anything like that ?

**Comment by craigloewen-msft** [comment]
Hi @brumeistern, these 'lite' versions are not made by Microsoft and so we do not support them. 

Additionally, currently you are only able to install WSL as a Windows optional component, we do not have any installer to enable it. 

If you'd like to use WSL please switch to a supported version of Windows and then you'll be able to use the commands you had above. Thank you!
