### ISSUE TITLE
[WSL 2] Tight loop of wsl --shutdown / start put the utility VM in a blocked state

### ISSUE THREAD

**Issue by simonferquel** [microsoft/WSL#4707]
* Your Windows build number:  Microsoft Windows [Version 10.0.19025.1]

* What you're doing and what's happening:  

We have a test case in Docker Desktop test suite that shutdown wsl while Docker is running, and restart it a few times in a row.

The test fails randomly, and when it does, WSL becomes totally unusable (either the docker-desktop nor ubuntu work anymore) (running wsl --shutdown puts everything back to work).
Even `wsl -d Ubuntu dmesg` does not work at this point.

* What's wrong / what should be happening instead: wsl should always restart correctly

* Strace of the failing command, if applicable:  n/a

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs):
[wsl-logs.zip](https://github.com/microsoft/WSL/files/3880992/wsl-logs.zip)

**Comment by benhillis** [comment]
Can you share some command line repro steps please?

**Comment by simonferquel** [comment]
I'll try to find a simple one but unfortunately my current repro case involves docker desktop. And our e2e test suite.

**Comment by simonferquel** [comment]
One thing that we do between runs is changing ~/.wslconfig (the test where it sometimes happens try to run Kubernetes with various cpu/ram config)

**Comment by simonferquel** [comment]
Ok, I did not find an exact repro for that, but here is some context + a partial problem repro:
Docker desktop run some processes within wsl and try to automatically restart them when they terminate. Examples of those processes are:
- docker-desktop-data keep alive (ensure the distro is alive so that it /mnt/wsl mounts stay alive)
- vpnkit-bridge the named pipe to unix socket proxy/reverse proxy that we run to enable interaction from win32 processes to linux services (and vice-versa)
- Linux workspaces proxies - handle exposition of the docker socket + handle bind mounts.

So my guess is that somewhere within WSL system, there might be some race condition when the utility VM is restarted.

I made a test case for reproducing this kind of scenario (
[concurrency-test.zip](https://github.com/microsoft/WSL/files/3885600/concurrency-test.zip)), and while it does not reproduce a full utility VM deadlock as Docker desktop does, it does reveal a race somewhere (which might lead to something more serious with what we do in Docker Desktop - mounting things, creating namespaces, etc.).

This repro is made of 3 powershell scripts that must be run concurrently:

restart-loop.ps1 restarts wsl every 2 s.
```
Function WSL_Shutdown() {
    & wsl --shutdown
    return $LASTEXITCODE -eq 0
}

Function WSL_Hello(){
    & wsl echo "hello world"
    return $LASTEXITCODE -eq 0
}

While(WSL_Shutdown -and WSL_Hello) {
    Start-Sleep -s  2
    Write-Host "restarting"
}
```


dmesg-loop.ps1 print kernel messages in a loop (-w is for following)
```
While($True) {
    & wsl -u root dmesg -w
    Write-Host "Exited with code $LASTEXITCODE"
}
```

cat-loop.ps1 blocks on /dev/stdin in a loop
```
While($True) {
    & wsl cat /dev/stdin
    Write-Host "Exited with code $LASTEXITCODE"
}
```

When you run those 3 scripts concurrently you quite often see (and the more you run concurrent scripts, the more you see them):
```
Cannot create a file when that file already exists.
Exited with code -1
``` 
(I also checked with adding -e on wsl scripts to avoid running the script within the default distro shell, it has the same effect).

**Comment by simonferquel** [comment]
I made a small hack in a docker desktop branch to avoid having concurrent wsl commands on wsl --shutdown, I then run our flakky test in a loop. Seems to workaround the issue.

Fixing the root cause seem desirable though, but at least we are able to workaround this :)

**Comment by benhillis** [comment]
Thanks for the info.  Looks like this is related to \\\\wsl$\\.  I'll take a look with @SvenGroot.

**Comment by benhillis** [comment]
A few releases ago we fixed an issue that could cause this deadlock, closing as fixed in Insider Builds. If you can still hit this in the recent Insider Dev builds, please open a new issue.
