### ISSUE TITLE
the "chmod" command doesn't work well

### ISSUE THREAD

**Issue by pan102887** [microsoft/WSL#4710]
### Windows version
   Microsoft Windows [version 10.0.18362.476]
### WSL version
  Distributor ID: Ubuntu  
  Description:    Ubuntu 18.04.3 LTS  
  Release:        18.04  
  Codename:       bionic    

----

- I try to Modify file permissions through command "chmod',but failed;  
   and this is what I've done
   
   <img width="524" alt="批注 2019-11-25 193103" src="https://user-images.githubusercontent.com/27915798/69537029-2c501180-0fba-11ea-9507-42de03ca1e4b.png">    
    
- and the following is what command I try  
    ls -l  
    chmod 755 test  
    ls -l  
    chmod u=wrx,u=wr,o=w
    ls -l  
   Then I find the permissions of test-file has no change at all
* What's wrong / what should be happening instead:
  I don't know if this is "by design",But this actually happened.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

    [log.zip](https://github.com/microsoft/WSL/files/3886478/test.zip)

**Comment by Biswa96** [comment]
You have to enable metadata option for drvfs mount. Create a `/etc/wsl.conf` file. Add these two lines:

```ini
[automount]
options = "metadata"
```
See [this blog post][1] for further information.

[1]: https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/

**Comment by pan102887** [comment]
Ok,Thanks

**Comment by pan102887** [comment]
But unfortunately,It still doesn't work
