### ISSUE TITLE
Special DNS name

### ISSUE THREAD

**Issue by boan-jfm** [microsoft/WSL#4711]
Could we have something similar in WSL2? Maybe `host.wsl.internal`, this may be used for the `xdebug.remote_host` within PHP development as well: https://www.jetbrains.com/help/phpstorm/configuring-xdebug.html#configuring-xdebug-docker

> The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Windows.

https://docs.docker.com/docker-for-windows/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host

**Comment by therealkenc** [comment]
Brought up in #4199 and #4210, but neither are really on topic for the specific ask. This one can be the LZ for a local DNS name ask, independent of the localhost ask and the static ip ask.

**Comment by xtremeperf** [comment]
Install libnss-myhostname package.  It's a plugin for the Name Service Switch.  It will always assign a hostname of '_gateway' that resolves to the current default routing gateway address.

**Comment by gwharton** [comment]
https://github.com/microsoft/WSL/issues/4210#issuecomment-622933974

**Comment by dataman713** [comment]
[]()
