### ISSUE TITLE
Commands are significantly slower when run using "wsl.exe" than SSH'ing in

### ISSUE THREAD

**Issue by prashantv** [microsoft/WSL#4712]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.19025.1051]
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

My WSL instance felt quite slow when run using cmd + wsl, but significantly faster with cmd + ssh.

Repro:
 * Run `cmd`
 * Run `wsl` inside cmd
 * Run the following:
```
$ time (for i in `seq 1 100`; do uname -a; done)
[...]
( for i in `seq 1 100`; do; uname -a > /dev/null; done; )  0.06s user 0.89s system 18% cpu 5.207 total
```

Compare to:
 * Run `cmd`
 * `ssh` into the same WSL instance
 * Run same command as above.
```
( for i in `seq 1 100`; do; uname -a > /dev/null; done; )  0.03s user 0.02s system 61% cpu 0.083 total
```

Running in the wsl.exe session takes >5 **seconds**. Running over my SSH connection takes < 0.1s. There's a 50x difference in performance. Redirecting output to `/dev/null` results in similar numbers, so it doesn't seem to be related to the output.

* What's wrong / what should be happening instead:
I'm expecting that running using the wsl session is faster or at least as-fast as using SSH, but SSH seems to have a significant performance advantage.

**Comment by therealkenc** [comment]
Can't actually follow the steps here because no CLI for "ssh into the same WSL instance" (from where?). But I can't repro the first 5s observation, so details of the second part academic. Let's run with the assumption your run was on WSL2.

![image](https://user-images.githubusercontent.com/7049700/69680922-4b55ae80-1061-11ea-8002-a7c40db1da75.png)

[...]

![image](https://user-images.githubusercontent.com/7049700/69680944-57417080-1061-11ea-8ac0-3c44010a6f83.png)

**Comment by prashantv** [comment]
Yes, this was WSL2. 

> no CLI for "ssh into the same WSL instance"

This requires the Ubuntu instance to have SSH server set up ([example setup instructions](https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-18-04/)).

Once set up, `ssh [linux user]@localhost`.

My OS was upgraded to `[Version 10.0.19025.1052]` yesterday, and I'm no longer able to reproduce it, so something odd is going on.

I'll close the issue and reopen if I see it again.
