### ISSUE TITLE
[Feature Request] Save status of WSL2 before restart windows

### ISSUE THREAD

**Issue by hzhangxyz** [microsoft/WSL#4713]
Since wsl2 uses hyper v, is saving status of wsl2 possible? Then I can continue to run program in wsl without stop even if I restart windows.

Since windows insider update is very often and I have to restart windows about twice a week, I hope I can restart windows without restarting programs in wsl.

**Comment by Biswa96** [comment]
It may be possible. There is an exported function `HcsPauseComputeSystem()` in computecore.dll which can pause/hibernate the utility VM that WSL2 uses.

**Comment by therealkenc** [comment]
Pause != saving state.

Short answer, no; you want Hyper-V. Long answer you might be able to off road it with [`Save-VM`](https://docs.microsoft.com/en-us/powershell/module/hyper-v/save-vm?view=win10-ps) somehow, but there are probably nontrivial barriers to getting that working, because WSL != Hyper-V.

**Comment by urkh** [comment]
Any news about this feature? or is it something that can already be done? I googled this but found nothing.

**Comment by hzhangxyz** [comment]
@urkh I think ms want you to treat this vm called wsl2 as subsystem, not vm. So, do not expect this feature.

**Comment by ethanthoma** [comment]
Same, this would be an awesome feature

**Comment by gdnathan** [comment]
Using windows terminal, I often have to run multiple nodes on multiple instances of the terminal with different env variable for work, it easily takes me 30 minutes to set up everything, knowing I will have to do it again the next day.
Saving the state of WSL could be lifechanging for this kind of situation

**Comment by TodoshiTakato** [comment]
> Using windows terminal, I often have to run multiple nodes on multiple instances of the terminal with different env variable for work, it easily takes me 30 minutes to set up everything, knowing I will have to do it again the next day. Saving the state of WSL could be lifechanging for this kind of situation

I totally agree with you!
Still neeed feature request! Please!

**Comment by maxres-es** [comment]
Very much needed. This drives me insane have to restart all my sessions, remember the name of my git worktree etc etc. I have to reboot all the time.
