### ISSUE TITLE
Windows Trojan in R packages

### ISSUE THREAD

**Issue by NobodyXu** [microsoft/WSL#4716]
My computer got infected by virus when installing R packages from R mirror **2 times** under WSL 1.0.

One using http, giving the wsl program admin privilege on windows, one using https and with no admin. In both cases, I run R without root permission and install packages inside home.

The packages I installed are tidyverse, data.table, stringr, stringi and devtools. Detailed of the instructions I used for the second installation can be seen in [here](https://github.com/NobodyXu/stacks/tree/master/R_toolchains). The first installation only differs in that it does not configure R to use https in `~/.Rprofile`.

### The first installation
During the first installation, it looked fine at first until kaspersky warned me that `/usr/bin/R/exec/R` was a windows32 Trojan which it **did not warn** after I installed `R` using `apt` (the installation of packages took more than 5 mins and kaspersky should have finished scanning R). Since I installed R from official source in linux not windows, I was very confident at what I was doing and did not click ‘disinfect now and restart’ and just ignore it.

After that, the packages installation quits with some strange errors which I did not record (sorry about that).

Then when I tried to find out what happened, all command in linux failed with `no permission`. After a while, my chrome cannot access network and a windows core is damaged. I cannot even open settings or WSL. Windows shell crashed with the same error as chrome.

Attempted to disinfect my computer manually, I deleted `/usr/bin/R/exec/R` from windows explorer.

After I restarted the computer, my login is also partly corrupted with message:

> C:\Windows\system32\wbem\wbemprox.dll is either not 
> designed to run on Windows or it contains an error. Try 
> installing the program again using the original installation 
> media or contact your system administrator or the software 
> vendor for support. Error status 0xc0000022.

It was a late night so I turned off the computer. When I restarted, probably due to my “manual disinfection” and the power of kaspersky, my computer restored with the consequence that WSL is not working properly.

### The second installation
I reset WSL in windows app and tried to reinstall R in WSL. This time I run bash from cmd.exe to prevent giving wsl any privilege to mess up with my system (an advice from one friend) and configure R to use https in `~/.Rprofile`.

I also modified windows security level to prompt for every request for admin privileges so that no privilege is given accidentally.

This time the same problem appeared again, except that when kaspersky prompted me that it has detected a virus, I immediately clicked “disinfect” and the system restarted. Just before the restart, I recalled that the same windows dll is missing.

After the restart, the system is working just fine and kaspersky detected no virus and my WSL misbehaved again.

As I have personally experienced this twice, I highly doubt this is a coincidence or just simple wifi hiject to because I was in two different location: one in my home, one in my university.

### System info:

```
Device specifications:
Device name HP_OMEN
Processor      Intel(R) Core(TM) i7-8750H CPU@ 2.20GHz 2.21 GHz

Windows specifications
Edition    Windows 10 Education
Version   1903
OS build 18362.476

WSL:
4.4.0-18362-Microsoft
Debian buster 10.2

R:
3.5.2-1
```

**Comment by sirredbeard** [comment]
This is not the appropriate or responsible venue to report security issues.

The front page of the project page states up top: "Do not open Github issues for....security issues. Please direct all ...security issues to secure@microsoft.com." You should report suspected WSL vulnerabilities there. 

You should report a security issue with R to the R Project via [R-Help](https://www.r-project.org/mail.html) but be sure to consult the [Posting Guide](https://www.r-project.org/posting-guide.html) first. If you believe a specific R dependency has been compromised, you should private contact the maintainer of that dependency. If you know which R Project mirror you connected to, you should privately contact the admin of that mirror as well.

I downloaded the binaries for [Debian buster](http://cloud.r-project.org/bin/linux/debian/buster-cran35/) unpacked them and ran them through VirusTotal with no positive hits.

It is very possible that the detection of the R executable by Kaspersky was a false positive. If you search this issues section you will see Kaspersky can cause a number of odd behaviors with WSL.

It is possible that one of the R project mirrors was compromised and is dishing out bad binaries, though that is unlikely as R project signs their repo files. It is also possible that your system was already injected with a trojan which infected WSL executable files on access. It is likely that editing WSL filesystem manually in Explorer also caused some of the erratic behavior.

Anti-virus software uses wbemprox.dll to load third-party .dlls and it's possible wbemprox.dll was corrupted by Kaspersky crashing your system. I would break out [DISM /Online /Cleanup-Image /RestoreHealth](https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image) after uninstalling Kaspersky.

The fact is we don't really know and reporting security issues like this is dangerous. Please report them privately to the appropriate parties and give them adequate time to investigate before disclosing them publicly.
