### ISSUE TITLE
Using \\wsl$ causes "init" CPU load

### ISSUE THREAD

**Issue by firewave** [microsoft/WSL#4719]
* Your Windows build number:  Windows 10 Version 1909 (OS Build 18363.476)

* What you're doing and what's happening: 
Accessing WSL via `\\wsl$` causes the `init` process to consume CPU visibly in Task Manager/top. In case of very frequent accesses (i.e. CLion) this will cause the process to consume a lot of CPU. The access are also quite slow it seems.

* What's wrong / what should be happening instead:
I would not expect it to consume so much CPU.

There's also an open issue with CLion I created - https://youtrack.jetbrains.com/issue/CPP-17597

The issue occurs on two completely different machines and was already present in 1903. I am using WSL 1 with Kali.

**Comment by Biswa96** [comment]
Can you provide any Windows Event logs or strace logs in WSL? The instructions are provided [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md).

**Comment by benhillis** [comment]
\\\\wsl$\\ works by running a file server in the init process.

**Comment by firewave** [comment]
I see. But it seems that it is rather CPU heavy and slow - at least in the way CLion uses it. I will try to get some more information and data on this soon.

**Comment by peci1** [comment]
I see the pretty same slowness if I instruct my IDE to communicate with WSL over ssh. And it's again the init process taking up all CPU time.

**Comment by therealkenc** [comment]
"slow" over in #4197.
