### ISSUE TITLE
WSL 2004 19033.1 Docker Networking / localhost Access

### ISSUE THREAD

**Issue by nsteblay** [microsoft/WSL#4720]
* Your Windows20 build number:  2004 19033.1

* What you're doing and what's happening: 
 
Joined Insider Program Fast Ring and Upgraded Windows
Installed Latest Docker Desktop 2.1.6.1 (40900)
Installed Ubuntu 18.04 from Microsoft Store
Enabled WSL 2 from Docker Desktop
From Terminal Executed Command: sudo docker run mmumshad/simple-webapp (simple FLASK web app)
Output: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
I also turned off the Windows firewalls

When I try and access the application from Chrome running in Windows at http://localhost:5000 it fails with message "localhost refused to connect"

I've tried using the container's IP address also with same failure.

* What's wrong / what should be happening instead: My understanding is with latest release localhost access should work.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by nsteblay** [comment]
[lxcore_service.zip](https://github.com/microsoft/WSL/files/3902935/lxcore_service.zip)

**Comment by timesnewmen** [comment]
Did you forgot to add  -p 5000:5000 when you run the container?

**Comment by nsteblay** [comment]
Yes.  Thank you.

**Comment by nsteblay** [comment]
Dumb mistake.  Thanks for the help!
