### ISSUE TITLE
Docker-hosted PHP CLI scripts stopped working in most recent insider builds

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/WSL#4721]
* Your Windows build number:  `Microsoft Windows [Version 10.0.19033.1]`

* What you're doing and what's happening:  The best explanation I can offer is that I am running docker containers with the latest Docker for Windows edge release.  After installing the most recent Windows 10 updates yesterday, PHP scripts within the containers eventually stop working and just hang on subsequent calls.

* What's wrong / what should be happening instead: The scripts should always run.

This is a pretty tall stack to have to offer any concrete insights on.  All I can say is that without updating any other application (not even docker desktop), my PHP CLI scripts that used to work all the time in previous builds now don't.  The first one or two will work, but after some seemingly random period of time, I have to reboot my whole machine before they'll go back to working again.

This doesn't impact scripts answering network requests.  Just ones that I run when exec'd into a container and calling via CLI.

The projects I'm running are private and not exclusively my property, so I would prefer to not post anything here, but if anyone on the MS team would like to do a screen share session with me, let me know and I'm happy to let you poke around.

**Comment by Biswa96** [comment]
Can you create any hello world like mininal project which can exactly reproduce your issue?

**Comment by Biswa96** [comment]
Can you create any hello world like minimal project which can exactly reproduce your issue?

**Comment by atrauzzi** [comment]
No, as I have absolutely no clue what's causing it.
