### ISSUE TITLE
Failed to initialize a WSL Distro

### ISSUE THREAD

**Issue by saintube** [microsoft/WSL#4724]
* Your Windows build number:  10.0.19033.1  

* What you're doing and what's happening:  
I've enabled **Windows Subsystem for Linux** and **Virtual Machine Platform** features. But when I followed [*Manually download Windows Subsystem for Linux distro packages*](https://docs.microsoft.com/en-us/windows/wsl/install-manual) to manually setup a Distro (Ubuntu 18.04) with `Add-AppPackage` command, I found the initialization of WSL Distros are always failed. More specifically, I've enabled the WSL features and used `wsl` command in PowerShell normally, but couldn't successfully install or initialize a Distro like [Ubuntu16.04](https://aka.ms/wsl-ubuntu-1604).

* What's wrong / what should be happening instead:  
When I used `Add-AppPackage` command in PowerShell to install a WSL Distro, I got no errors. However, if I used App Installer to install `.appx` file, I would get a popup which said:  
```
C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu16.04onWind...\ubuntu16.04.exe  
Bad parameter
```
Unfortunately, I cannot initialize the Distro in either way. When I clicked the `Ubuntu 16.04` icon on the Start Screen, I would get a progressbar below that and then nothing happened. And the `wsl -l -v` command also doesn't print any available Distros.

**Comment by Biswa96** [comment]
No need to use `Add-AppPackage`. Extract the Appx file in any folder. Double click on the exe file in it.

**Comment by saintube** [comment]
@Biswa96 
Thx. But I've also tried double click which uses App Installer to extract it, and then got the `Bad Parameter` errors.

**Comment by craigloewen-msft** [comment]
@saintube do you have access to the Microsoft Store? Are you able to try installing from there?

**Comment by saintube** [comment]
@craigloewen-msft 
I had some problem with my network at that time and couldn't access Microsoft Store. However, I've successfully install a Distro after deleting the Windows.old directory and restarting that PC. Anyway, I have no idea how this problem just got fixed.

**Comment by craigloewen-msft** [comment]
Interesting! Well I'm glad that it did get resolved, we'll look out to see if this issue pops up again. In the meantime I'll close this issue out, please feel free to reopen it if you see the same error again. :) Thanks for filing!
