### ISSUE TITLE
Cannot start Ubuntu on build 19033.1

### ISSUE THREAD

**Issue by kpeters-cbsi** [microsoft/WSL#4725]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  19033.1

* What you're doing and what's happening: When I type "bash" at the Windows command prompt, I get "The Windows Subsystem for Linux instance has terminated"

* What's wrong / what should be happening instead: bash / Ubuntu should start.

* Strace of the failing command, if applicable: N/A

* Logs: [bash logs.zip](https://github.com/microsoft/WSL/files/3911919/bash.logs.zip)

**Comment by benhillis** [comment]
@kpeters-cbsi - It looks like you are hitting a timeout waiting for the VM to start.  Is this a very slow machine by chance?  Does this hit 100% of the time or only sometimes?

**Comment by kpeters-cbsi** [comment]
No, it's a fairly recent machine. Core i7, 16GB RAM. Hits 100% of the time.

**Comment by benhillis** [comment]
@kpeters-cbsi - if you install a new distro (like debian) does this still reproduce?

**Comment by kpeters-cbsi** [comment]
No; I copied off my VHDX file and tried to "reset" the Ubuntu app; that
uninstalled it. When I reinstalled Ubuntu and converted the new
installation to WSL2, it started without any problems.

**Comment by benhillis** [comment]
Interesting... I wonder if there was something about your old VHDX that was causing mounting the VHD to take a long time.

**Comment by kpeters-cbsi** [comment]
The only weirdness I can think of is that I had an SSHFS mount in fstab that I haven't since restored.

**Comment by benhillis** [comment]
Ah interesting... that could definitely cause issues if your ssh server isn't responding.

**Comment by dongqi-suzhou** [comment]
@benhillis I had meet the same issue
windows build number: 19035.1000
the ubuntu(wsl2) can not start, the windows crashed when I press the icon.

**Comment by awson** [comment]
Windows build number: 19035.1000
Wsl 2 is slow as hell at startup (but still starts). 

(Yesterday I've been stuck in https://github.com/microsoft/WSL/issues/4731, today I've upgraded to 19035.1, the network issue has been gone, but it's now horrible slow at startup)

**Comment by gloveboxes** [comment]
yeah, same issue. Take about 40 seconds to start a bash shell (Ubuntu 18.04). It started happening with slow ring build 19035. Noticed if you press ctrl+c it kills whatever is hanging and takes you to the command prompt.  Running on the latest Surface Laptop 3, 16GB, i7

**Comment by Biswa96** [comment]
I'm using WSL with 19035, no issue.

**Comment by archilkarchava** [comment]
> The only weirdness I can think of is that I had an SSHFS mount in fstab that I haven't since restored.

probably related https://github.com/microsoft/WSL/issues/4738

**Comment by gloveboxes** [comment]
I uninstalled and reinstalled Ubuntu 18.04 and it now starts as expected. Not necessarily the most convenient workaround - but for now it has worked...

**Comment by gloveboxes** [comment]
I uninstalled Ubuntu 18.04 and reinstalled. I worked as expect until I did an apt update/upgrade of the distro and now it's back to the slow start again...

**Comment by pds2208** [comment]
Same issue and it was on a new build and straight after an apt update/upgrade. Before the apt it was fine.

**Comment by ricardosantos9521** [comment]
This was happening to me too in Ubuntu, but i remembered the last package that was updated (wslu). I uninstalled it and it works great again (sudo apt autoremove --purge wslu).

**Comment by pds2208** [comment]
> This was happening to me too in Ubuntu, but i remembered the last package that was updated (wslu). I uninstalled it and it works great again (sudo apt autoremove --purge wslu).

Thanks! This fixed it.
