### ISSUE TITLE
Can scroll up to view previous ouput after printf "\033c"

### ISSUE THREAD

**Issue by liamness** [microsoft/WSL#4727]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
19033.1

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
  - I open a new terminal window running Ubuntu 18.04, using zsh as the shell
  - I run `repeat 100 echo wat` (not something you would actually want to do, but sufficient to demonstrate the issue)
  - I then run `printf "\033c"`

* What's wrong / what should be happening instead:
The terminal seems to have been reset, with a clear screen, but you can scroll upwards to view previous commands. This can make working in the terminal a bit cumbersome when you are running a command with a long output (e.g. a suite of tests) as it then becomes difficult to scroll back through the output without accidentally scrolling into the output of previous commands. Seems to be a regression of a bug that was previously fixed, #1441.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N / A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
N / A

**Comment by craigloewen-msft** [comment]
I was able to repro this as well. I also tried this on an Ubuntu VM and found that zsh behaves as expected there, where `printf "\033c"` clears without letting you scroll up.

I believe this is a Windows console related bug, as they control presenting the text. 

Sorry to ping you off to another repo but could you please post this issue to the [Windows Terminal Github repo](https://github.com/microsoft/terminal) and then post a link here? They will be able to help you out! :)

**Comment by liamness** [comment]
🤦‍♂ I think I had somehow convinced myself that's the repo I was opening this issue on...

Thanks for going to the effort to reproduce. I'll close this now.
