### ISSUE TITLE
wsl arguments and options ??  

### ISSUE THREAD

**Issue by stevebovy** [microsoft/WSL#4732]
wsl arguments and options ??

Are vague and confusing, especially without useful and adequate examples 

So here are some questions:

--exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.
What does that mean,  how can you execute with out using the default shell ???

And how do you execute using "other dist"  
Majority of commands require shell env set-up  ??  How can you invoke a command without the shell ???

What are the valid and useful ways that you can combine arguments and  options 

The current docs are terrible

**Comment by stevebovy** [comment]
[command line] usage ????

From what I can ascertain by experimental research it seems like

The <command line>  [arguments]   and   the  

[options]   are     EXCLUSIVE   

Therefore  it should look like this 

[ Arguments ]  OR   [Options]

Because  any attempt to combine   Arguments   with   { -d or -u } options does not work       

Also the doc should say default non-login shell ,  because  it is definitely not running the bash login profile scripts   

AND  the  [--]  option ??? 

Passing the remaining command line as is    ( to who ??? is it being passed )  ????

-e with -d  and -u  works

but  --  cannot be used with  -d and -u   

but what about adding   a  -l   option  (use the login shell) 

and the -e  should say  

Execute the specified command without using the  Linux shell.

Because  -e with -d  means execute non-default with no shell


Here is what i think it should say

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments to run Linux binaries:

    If no command line is provided, wsl.exe launches the default non-login shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux non-logon shell.

    --
        Pass the remaining command line as is to default non-login shell
        NOTE THIS argument does not support additional options

**Comment by therealkenc** [comment]
> The current docs are terrible

[here](https://github.com/MicrosoftDocs/WSL/issues)
