### ISSUE TITLE
WSL eats up lines from powershell

### ISSUE THREAD

**Issue by lubyrex** [microsoft/WSL#4733]
I encountered this problem when I was using tmux in wsl, and I wanted to open powershell.exe. But then I realized that older lines produced by powershell.exe disappears, and it's impossible to read the history. (Also there are some minor color issues)
Opening powershell.exe in wsl:
<img width="1088" alt="first_image" src="https://user-images.githubusercontent.com/16534505/70207820-c9533d00-1766-11ea-9437-c6bc7440d5df.png">
Everything above and including Copyright disappears:
<img width="1085" alt="second_image" src="https://user-images.githubusercontent.com/16534505/70207824-cb1d0080-1766-11ea-9754-033f23d89e11.png">
Is there any way I can get around this? Thanks

**Comment by DHowett-MSFT** [comment]
This is a bug in PowerShell that has already been fixed. There is an update to the `PSReadline` module that you may install to fix it.
