### ISSUE TITLE
WSL 2 session takes 40 seconds just to get to prompt

### ISSUE THREAD

**Issue by mchassy** [microsoft/WSL#4737]
* Windows build number:  `Version 2004 (OS Build 19035.1)` with `Ubuntu 18.04 WSL`

* What I'm doing and what's happening: open WSL 2 session using MobaXterm (same result when using bash.exe)

* What's wrong / what should be happening instead: Using WSL 1, the session took a second or two to open. Now with WSL2, it take 40 seconds. I am attaching a screen recording  which is about as exciting as watching paint dry.

[MobaXterm 2019-12-06 13-57-23.mp4.zip](https://github.com/microsoft/WSL/files/3932527/MobaXterm.2019-12-06.13-57-23.mp4.zip)

**Comment by effolkronium** [comment]
u Better to use a VM with linux instead wsl2. It's the same thing

**Comment by stefankummer** [comment]
Same issue here using Windows Terminal version 0.7.3291.0
Windows build 19035.1, Ubuntu 18.04 on WSL2

[videorec_tmp.zip](https://github.com/microsoft/WSL/files/3933324/videorec_tmp.zip)

**Comment by craigloewen-msft** [comment]
@mchassy and @stefankummer thank you both for the videos! To help troubleshoot this, could you both please look at doing these steps:
* After you start WSL can you run the `dmesg` command, put the output into a [Github gist](https://gist.github.com/) and paste a link to it here?
* If you install a new distribution like Debian as a WSL 2 distro, does the problem persist there as well?

**Comment by mchassy** [comment]
Hi Craig ... done for the week (I'm in the UK), but I will do that on Monday.
I can check for another distro as well.

**Comment by noelbundick** [comment]
I'm hitting similar issues, originally thought it may have been related to https://github.com/microsoft/WSL/issues/4498

My symptoms are similar - 30s+ to get a new prompt. I've reset my Ubuntu 18.04 environment several times to troubleshoot. In my case, I've also observed some interesting behavior based on how I launch into wsl, starting from a new Windows PowerShell instance:

* `wsl.exe` or `ubuntu1804`: 39s to prompt, I land in `/home/noel`
* `wsl.exe` followed immediately by `Ctrl+C`: instant prompt, none of my `.bashrc` has run, and I'm in `/mnt/c/Users/noel`
* `wsl -d Ubuntu-18.04 /bin/bash`: 2s to prompt, `.bashrc` has run, I land in `/mnt/c/Users/noel`

The last case seems to rule out it being "my fault" for having an excessively slow bash profile, and is an acceptable workaround for the time being

dmesg logs in case it helps: https://gist.github.com/noelbundick/36d20fdf21b01838ce5a97df10c39dc9

**Comment by stefankummer** [comment]
> @mchassy and @stefankummer thank you both for the videos! To help troubleshoot this, could you both please look at doing these steps:
> 
> * After you start WSL can you run the `dmesg` command, put the output into a [Github gist](https://gist.github.com/) and paste a link to it here?
> * If you install a new distribution like Debian as a WSL 2 distro, does the problem persist there as well?

Hi Craig,

dmesg here : https://gist.github.com/stefankummer/0b8645e2fc3ae6d36271a27d32622cf6

I installed a new distro (Debian) and the problem does not arise. 
Debian starts normally, but still not Ubuntu.

Regards

**Comment by geerteltink** [comment]
If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.

**Comment by M-Kub** [comment]
> 
> 
> If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.

I can confirm this, after commenting out the checks for pulseaudio and x11, the startuptime is back to normal.

**Comment by nhuse9** [comment]
> If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.

I can also confirm. Noticed I was having long hanging times after running my update script. 
Ran `sudo vim \etc\profile.d\wsl-integration.sh`
Edited it to look as so: https://i.imgur.com/hNGrCnF.png
Now it is working as it did before updating.

**Comment by junxy** [comment]
@noelbundick Yes. Refer to your approach. The startup time is back to normal.

1. 

I inserted [`return`](https://gist.github.com/junxy/c1fc03f1d16953f861936059e3d546ec#file-tryfix_etc_profile-d_wsl-integration-sh-L1) on the first line. And tracked the execution time consumption.

```log
λ wsl
wsl:1 ->
11:25:29

wsl:2 ->
11:25:29

wsl:3 detect WSL host: 192.168.208.1 ->
11:25:29

wsl:4 set display -> (33s)
11:26:02

wsl:5 set audio done -> (5s)
11:26:07
```

2. 

**The reason may be related to the network. Commands executed cannot return results in a timely manner.**

Further testing (Runs on WSL):

```bash
# WSL_HOST=192.168.208.1
awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null

# set DISPLAY if there is an X11 server running  (Key commend) 
$ time env DISPLAY=192.168.208.1:0 xvinfo

# set up audio if pulse server is reachable only via tcp  (Key commend) 
$ time env PULSE_SERVER=tcp:192.168.208.1 pactl info
```

Result: 

(using $WSL_HOST and my Lan IP)

```bash
# WSL_HOST=192.168.208.1

# set DISPLAY if there is an X11 server running  (Key commend) 
$ time env DISPLAY=192.168.208.1:0 xvinfo
xvinfo:  Unable to open display 192.168.208.1:0

real    0m32.391s
user    0m0.001s
sys     0m0.000s

$ time env DISPLAY=<lan ip>:0 xvinfo
xvinfo:  Unable to open display <lan ip>:0

real    0m3.147s
user    0m0.002s
sys     0m0.000s

# set up audio if pulse server is reachable only via tcp  (Key commend) 
$ time env PULSE_SERVER=tcp:192.168.208.1 pactl info
Connection failure: Connection refused

real    0m5.010s
user    0m0.000s
sys     0m0.003s
$ time env PULSE_SERVER=tcp:<lan ip> pactl info
Connection failure: Connection refused

real    0m3.138s
user    0m0.003s
sys     0m0.000s
```

And

(using 127.0.0.1)

```bash
$ time env DISPLAY=127.0.0.1:0 xvinfo
xvinfo:  Unable to open display 127.0.0.1:0

real    0m0.003s
user    0m0.002s
sys     0m0.000s

$ time env PULSE_SERVER=tcp:127.0.0.1 pactl info
Connection failure: Connection refused

real    0m0.004s
user    0m0.003s
sys     0m0.000s
```

**Comment by Sword-Destiny** [comment]
It's because of the network check, I think.
This is the dmesg output:

[    0.570791] Adding 2097152k swap on /swap/file.  Priority:-2 extents:1 across:2097152k
[    0.601659] FS-Cache: Duplicate cookie detected
[    0.601661] FS-Cache: O-cookie c=00000000fa5cc921 [p=00000000261177d3 fl=222 nc=0 na=1]
[    0.601661] FS-Cache: O-cookie d=000000005e9b151a n=00000000e917c7fe
[    0.601662] FS-Cache: O-key=[10] '34323934393337333338'
[    0.601664] FS-Cache: N-cookie c=000000001f062dbd [p=00000000261177d3 fl=2 nc=0 na=1]
[    0.601665] FS-Cache: N-cookie d=000000005e9b151a n=000000008ae87d6d
[    0.601665] FS-Cache: N-key=[10] '34323934393337333338'
[    0.606069] FS-Cache: Duplicate cookie detected
[    0.606072] FS-Cache: O-cookie c=0000000068d70691 [p=00000000261177d3 fl=222 nc=0 na=1]
[    0.606072] FS-Cache: O-cookie d=000000005e9b151a n=0000000082f3bb09
[    0.606072] FS-Cache: O-key=[10] '34323934393337333339'
[    0.606075] FS-Cache: N-cookie c=0000000046c85068 [p=00000000261177d3 fl=2 nc=0 na=1]
[    0.606076] FS-Cache: N-cookie d=000000005e9b151a n=00000000cba492b9
[    0.606076] FS-Cache: N-key=[10] '34323934393337333339'
[    0.608752] FS-Cache: Duplicate cookie detected
[    0.608754] FS-Cache: O-cookie c=0000000068d70691 [p=00000000261177d3 fl=222 nc=0 na=1]
[    0.608755] FS-Cache: O-cookie d=000000005e9b151a n=0000000082f3bb09
[    0.608755] FS-Cache: O-key=[10] '34323934393337333339'
[    0.608758] FS-Cache: N-cookie c=0000000046c85068 [p=00000000261177d3 fl=2 nc=0 na=1]
[    0.608759] FS-Cache: N-cookie d=000000005e9b151a n=00000000f8d9280e
[    0.608759] FS-Cache: N-key=[10] '34323934393337333339'
[    1.291850] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   49.108158] hv_balloon: Max. dynamic memory size: 6430 MB
[   61.514076] WSL2: Performing memory compaction.
[  107.009342] init: (118) ERROR: LogUsage:253: Could not find owner of socket 2 2222 15432
[  122.519965] WSL2: Performing memory compaction.
[ 3423.555836] WSL2: Performing memory compaction.
[11584.876330] WSL2: Performing memory compaction.
[16446.158393] WSL2: Performing memory compaction.

**Comment by rsletta** [comment]
> > If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.
> 
> I can also confirm. Noticed I was having long hanging times after running my update script.
> My steps:
> Ran `sudo vim /etc/profile.d/wsl-integration.sh`
> Edited it to look as so: https://i.imgur.com/hNGrCnF.png
> Now it is working as it did before updating.

I had the same issues, and disabling the firewall removed the issue. Editing /etc/profile.d/wsl-integration.sh, like the image, solved the issues without disabling the firewall.

**Comment by Sword-Destiny** [comment]
> > > If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.
> > 
> > 
> > I can also confirm. Noticed I was having long hanging times after running my update script.
> > My steps:
> > Ran `sudo vim /etc/profile.d/wsl-integration.sh`
> > Edited it to look as so: https://i.imgur.com/hNGrCnF.png
> > Now it is working as it did before updating.
> 
> I had the same issues, and disabling the firewall removed the issue. Editing /etc/profile.d/wsl-integration.sh, like the image, solved the issues without disabling the firewall.

I can not access the URL “https://i.imgur.com/hNGrCnF.png”.  Could you please copy the content of your "/etc/profile.d/wsl-integration.sh" after modified?

**Comment by rsletta** [comment]
`if type pactl > /dev/null 2>&1 || type xvinfo > /dev/null 2>&1; then
  1     # detect WSL host
  2     if type systemd-detect-virt > /dev/null 2>&1 && test "$(systemd-detect-virt -c)" != wsl -a -e /etc/resolv.c    onf; then
  3         WSL_HOST=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null)
  4     fi
  5     WSL_HOST=${WSL_HOST:-localhost}
  6
  7     # set DISPLAY if there is an X11 server running
  8     #if type xvinfo > /dev/null 2>&1 && env DISPLAY=${WSL_HOST}:0 xvinfo > /dev/null 2>&1; then
  9     #    export DISPLAY=${WSL_HOST}:0
 10     #    export LIBGL_ALWAYS_INDIRECT=1
 11     #fi
 12
 13     # set up audio if pulse server is reachable only via tcp
 14     #if type pactl > /dev/null 2>&1 \
 15     #       && (! pactl info > /dev/null 2>&1 || pactl info 2> /dev/null | grep -q 'Default Sink: auto_null' )     \
 16     #       && env PULSE_SERVER=tcp:${WSL_HOST} pactl info > /dev/null 2>&1; then
 17     #    export PULSE_SERVER=tcp:${WSL_HOST}
 18     #fi
 19
 20     unset WSL_HOST
 21 fi`

**Comment by rsletta** [comment]
@Sword-Destiny: See Gist at https://gist.github.com/rsletta/0b634d717dd812bfb841383ca91e4974

**Comment by mchassy** [comment]
@rsletta: I followed your advice and commented out the same sections as you did. I even commented out setting `WSL_HOST=localhost` because it just gets unset after the comments which have just been commented out. My session seems to work just fine without them.
Could somebody explain what this script is actually trying to do, including the parts which remains active?

**Comment by rsletta** [comment]
@craigloewen-msft: Might someone from the team have time to shed some light onto this?

**Comment by M-Kub** [comment]
The "wsl-integration.sh" file was added to WSL2 with the last update to "wslu" to detect if an X11Server or Pulseaudio is running.  [Here](https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1853343) is the bugreport about WSL2 "not" checking for it. Now the question is whats causing the delay for the prompt to appear when the system is running this checks.

**Comment by mchassy** [comment]
Thanks @M-Kub. So  ...
- Audio .... I don't care. I'm not using audio on my WSL.
- X11 - I am using that, so what does that mean if I don't verify in that script?
- There is also a first block that seems to be checking context of the WSL session (container, VM, etc)
based on testing that, it sets WSL_HOST to a given IP, only to set it localhost immediately afterwards? Why bother?

**Comment by mchassy** [comment]
Actually, I just saw that the session tool I'm using (Xmobaterm) give you the IP of the Xserver.
Given that my WSL install is stable, I simple set WSL_HOST to that IP without any tests or conditions.
Session opens instantaneously. 

This kind of script should not be running every time you run a session, rather it could be run at setup with the possibility to run it again as necessary.

**Comment by benhillis** [comment]
https://twitter.com/rsletta/status/1203957912072273921?s=21

**Comment by mchassy** [comment]
Ok ... I am closing the issue.
I am simply putting this into wsl_setup.sh
```
WSL_HOST=${WSL_HOST:-XX.XX.XXX.XX}
export DISPLAY=${WSL_HOST}:0
export LIBGL_ALWAYS_INDIRECT=1

```
Not the most elegant solution, but I shouldn't have to modify it until we get to WSL 3 ;-)

**Comment by rbalint** [comment]
This will be fixed soon in the wslu package: https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1855520

**Comment by rbalint** [comment]
The change causing the long delay on WSL2 has been reverted in Ubuntu thus it can be fixed now with `apt update ; apt upgrade`.
There is also an improved fix adding all detection with caching the results in the -proposed pocket. 
The https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1855520 bug includes information on how to get that fix. Feedback is appreciated.

**Comment by wil93** [comment]
Upgrading the `wslu` package fixed it!

The solution as of today is to simply run:

    sudo apt update
    sudo apt dist-upgrade

😄

**Comment by azeveco** [comment]
I'm still getting super slow times. I did the apt update and apt upgrade, rebooted, but nothing seems to work.

**Comment by ketozhang** [comment]
While this is tangentially related, the issue for me was ohmyzsh. Make sure to test your slow times using bash.

I found there was no need to comment out the Xserver and audio portion on `/etc/profile.d/wsl-integration.sh`. However, I did run `sudo apt update && sudo apt upgrade`.

**Comment by fahds** [comment]
Hello guys I found a possible reason for the problem, in my case I have installed NVM (Node Version Manager) in WSL and when I comment the following lines in .zshrc

```
# export NVM_DIR = "$ HOME / .nvm"
# [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
# [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
```

wsl starts instantly

To continue using NVM I found a possible solution here:
https://www.growingwiththeweb.com/2018/01/slow-nvm-init.html

**Comment by rsletta** [comment]
> Hello guys I found a possible reason for the problem, in my case I have installed NVM (Node Version Manager) in WSL and when I comment the following lines in .zshrc
> 
> ```
> # export NVM_DIR = "$ HOME / .nvm"
> # [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
> # [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
> ```
> 
> wsl starts instantly
> 
> To continue using NVM I found a possible solution here:
> https://www.growingwiththeweb.com/2018/01/slow-nvm-init.html

I experienced slow startups again. Commented out my NVM path like you, and got instant startup. Seems like that's the culprit in my setup too.

**Comment by cbartondock** [comment]
For me the key was allow all of my x11 server (vcxsrv) apps through the defender firewall. Massive speedup.

**Comment by eknee** [comment]
NVM was the culprit for me.  Commenting out the lines you mentioned @rsletta solved my issue

```
# export NVM_DIR = "$ HOME / .nvm"
# [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
# [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
wsl starts instantly
```

**Comment by 2015xli** [comment]
The problem for me is the network connection due to "pactl info".  I found that by opening another Ubuntu shell and "ps -axf". This problem never existed before I did a "apt dist-upgrade".

I avoid the problem by simply "cat /dev/null > /usr/share/wslu/wsl-integration.sh" to set it empty, since I don't see how it can be useful to me. And I set the DISPLAY and PULSE_SERVER in my profile file:

```
export HOST=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
export DISPLAY=$HOST:0
export PULSE_SERVER=tcp:$HOST
```

My X apps and music apps run fine.

**Comment by krehwell** [comment]
commenting the NVM in .bashrc starts my wsl instantly as the @fahds has mentioned

**Comment by shugaoye** [comment]
I found that it will be very slow after I run a X server. If I run it as `mc -X`, it can start immediately.

**Comment by geohadab** [comment]
> Hello guys I found a possible reason for the problem, in my case I have installed NVM (Node Version Manager) in WSL and when I comment the following lines in .zshrc
> 
> ```
> # export NVM_DIR = "$ HOME / .nvm"
> # [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
> # [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
> ```
> 
> wsl starts instantly
> 
> To continue using NVM I found a possible solution here:
> https://www.growingwiththeweb.com/2018/01/slow-nvm-init.html

I can confirm that this solved the slowness I just commented the NVM

**Comment by ronilaukkarinen** [comment]
Thank you @fabioods! Only commenting out nvm from my .bashrc helped.

**Comment by NoSubstitute** [comment]
> I found that it will be very slow after I run a X server. If I run it as `mc -X`, it can start immediately.

I too have had to start running mc that way.
The slowness of mc was driving me crazy!
It took several minutes to start, and then again if I use _mcedit_ it took just as long to start it.

I didn't have to change the firewall (I tested opening firewall for ping, but it didn't help, so deactivated again).

**Comment by arafatx** [comment]
WSL 2 is a nightmare, I wasted 2 hours and I thought that my bash script has trouble with linode API call. It took 1 minute to call one API and WSL 2 did not display any of my beautiful spinning progress bar!. I tested the online API and did not see problem with it. Then I tried the script on ubuntu virtualbox, the script run very fast, with the fast spinning progress bar. Maybe WSL 2 is not suitable for bash script more than 15k lines which I tested this. Problem solved using multipass for ubuntu.

**Comment by arafatx** [comment]
WSL 2 is a nightmare, I wasted 2 hours and I thought that my bash script had trouble with linode API call which took more than a minute to call one API. In addition of that, WSL 2 did not display any of my beautiful spinning progress bar in terminal!. I tested the linode online API and I can confirm there was no issue with the API call. Then I tried the script on ubuntu virtualbox, the script ran very fast, with my beutiful spinning progress bar (that did not even show up in WSL2). Maybe WSL 2 is not suitable for bash script more than 15k lines which I tested this. Problem solved using multipass for ubuntu. I had to apologize to the linode team for getting mad with them because I thought there was a problem with their API.

**Comment by arafatx** [comment]
WSL 2 is a nightmare, I wasted many hours debugging and I thought that my bash script had trouble with linode API call which took more than a minute to call one API. In addition of that, WSL 2 did not display any of my beautiful spinning progress bar in terminal!. I tested the linode online API and I can confirm there was no issue with the API call. Then I tried the script on ubuntu virtualbox, the script ran very fast, with my beutiful spinning progress bar (that did not even show up in WSL2). Maybe WSL 2 is not suitable for bash script more than 15k lines which I tested this. Problem solved using multipass for ubuntu. I had to apologize to the linode team for getting mad with them because I thought there was a problem with their API.

**Comment by elliottcarlson** [comment]
After trying all of the suggestions in this thread (that comes up as the first result for most of my Google queries regarding WSL2 slowness), I finally found the culprit on my system to be Neofetch; starting any user shell would take upwards of a minute.

Commenting out the following lines in `~/.config/neofetch/config.conf` solved the problem for me:

```
#    info "Resolution" resolution
#    info "DE" de
#    info "WM" wm
#    info "WM Theme" wm_theme
#    info "Theme" theme
#    info "Icons" icons
```

**Comment by xinxilas** [comment]
i dont have NVM
i dont have neofetch
I tried "cat /dev/null > /usr/share/wslu/wsl-integration.sh

Still having slowness at startup

And my windows explorer starts slows too because it tries to resolve shell $wsl/ directories

**Comment by NikolaDucak** [comment]
In my case, I had [MegaCMD](https://github.com/meganz/MEGAcmd) installed which added a custom bash completion script: `/etc/bash-completion.d/megacmd_completion.sh`. The culprit was [this line](https://github.com/meganz/MEGAcmd/blob/master/src/client/megacmd_completion.sh#L79) in the said script, more precisely, the `compgen -ca | grep mega-` command. Removing the file or that for loop fixes the problem.

**Comment by geekshen8521** [comment]
In my case, as soon as I remove the `wslu` from ubuntu wsl, the terminal launch in 2 seconds.

**Comment by kierenfunk** [comment]
> In my case, I had [MegaCMD](https://github.com/meganz/MEGAcmd) installed which added a custom bash completion script: `/etc/bash-completion.d/megacmd_completion.sh`. The culprit was [this line](https://github.com/meganz/MEGAcmd/blob/master/src/client/megacmd_completion.sh#L79) in the said script, more precisely, the `compgen -ca | grep mega-` command. Removing the file or that for loop fixes the problem.

changing `compgen -ca | grep mega-` to `compgen -ca mega-` also works

**Comment by fathomserver** [comment]
For me it was commenting this line:

```
# Load Angular CLI autocompletion.
#source <(ng completion script)
```

Inside:
`vim ~/.zshrc`

In case this doesn't work out for you, go in that file and start commenting things you installed to find the culprit.

**Comment by indrajeetgour** [comment]
> For me it was commenting this line:
> 
> ```
> # Load Angular CLI autocompletion.
> #source <(ng completion script)
> ```
> 
> Inside: `vim ~/.zshrc`
> 
> In case this doesn't work out for you, go in that file and start commenting things you installed to find the culprit.

Worked for me too...

**Comment by dhruvinsh** [comment]
For me, Microsoft Terminal take a while to open but once it open, next few time opening a split window or new tab of WSL works fine.

After a while if I try to open split it takes while as if the observer in the beginning. 

But while using a Wezterm I do not observe such issue, first launch of wsl after fresh reboot is quick, and delayed new tab or split windows are faster as well.

**Comment by asolopovas** [comment]
It still slow on startup, each time when I spend some time in Windows and than start working on linux of forget how much more it faster than Windows. Because they have to spinup virtual machine unless its started at boot time I don't see anyway they can increase the boot time. They tried something really difficult to translate kernell calls from linux with WSL 1 but it feels like its abandonded, maybe now wth the power of AI they will revisit WSL 1 project?

**Comment by neilborromeo** [comment]
> > Hello guys I found a possible reason for the problem, in my case I have installed NVM (Node Version Manager) in WSL and when I comment the following lines in .zshrc
> > ```
> > # export NVM_DIR = "$ HOME / .nvm"
> > # [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
> > # [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wsl starts instantly
> > To continue using NVM I found a possible solution here:
> > https://www.growingwiththeweb.com/2018/01/slow-nvm-init.html
> 
> I experienced slow startups again. Commented out my NVM path like you, and got instant startup. Seems like that's the culprit in my setup too.

forgot about it when I don't use nvm in new WSL distro and copied everything in my home folder from previous distro install. So it must be within these files during startup that cause the issue.

**Comment by Luuk34** [comment]
Can anyone point to a **good** solution for this?

**Comment by lindhe** [comment]
> looks like ldconfig is the issue,

@dhruvinsh Interesting! Did you find any fix? Can you please expand upon how you identified ldconfig as the culprit? I'm also having the issue with WSL2 being slow to spawn new terminal instances (often).

**Comment by dhruvinsh** [comment]
> > looks like ldconfig is the issue,
> 
> @dhruvinsh Interesting! Did you find any fix? Can you please expand upon how you identified ldconfig as the culprit? I'm also having the issue with WSL2 being slow to spawn new terminal instances (often).
> 

I simply gave up.

I switched to wezterm and it works fine. Launch time is sub second (every time). 

I do from time to time use he windows terminal and I do have the same lag, sometimes it takes 10 seconds to spawn a window/pane for wsl.

There is something different between how wezterm spawn the wsl vs Microsoft terminal.

**Comment by AhmedMustafa2201** [comment]
> If I do a fresh install ubuntu starts normally. After `sudo apt update && sudo apt upgrade` the slow startup starts. I have tracked it down to `/etc/profile.d/wsl-integration.sh`. Disabling the X11 server check reduces the delay to a second or two. Disabling the audio check as well gives an instant startup as expected.

@geerteltink great job. I've tried to do the same, but there's nothing on my `/etc/profile.d/wsl-integration.sh` file through my ubuntu wsl2. do you know the root cause for this issue?

**Comment by thecatontheflat** [comment]
> Hello guys I found a possible reason for the problem, in my case I have installed NVM (Node Version Manager) in WSL and when I comment the following lines in .zshrc
> 
> ```
> # export NVM_DIR = "$ HOME / .nvm"
> # [-s "$ NVM_DIR / nvm.sh"] && \. "$ NVM_DIR / nvm.sh" # This loads nvm
> # [-s "$ NVM_DIR / bash_completion"] && \. "$ NVM_DIR / bash_completion" # This loads nvm bash_completion
> ```
> 
> wsl starts instantly
> 
> To continue using NVM I found a possible solution here: https://www.growingwiththeweb.com/2018/01/slow-nvm-init.html

This was the culprit for me too!

I believe that it started after installing one of the minor Windows updates. Interestingly, another symptom which may or may not be related is an overall slow DNS resolution when I open a URL in a browser for the first time.

**Comment by lindhe** [comment]
I too had issues caused by NVM. I'm not very knowledgeable at all about NVM – is this a bug in NVM or why does it cause such a bad effect? Or is it a WSL bug that makes NVM freak out?

**Comment by Luuk34** [comment]
A nice reference to get a working solution might be nice ....
I am trying to follow anything on this problem, for over a month now, and still not **real** solution ....

**Comment by cm-uni** [comment]
> For me it was commenting this line:
> 
> ```
> # Load Angular CLI autocompletion.
> #source <(ng completion script)
> ```
> 
> Inside: `vim ~/.zshrc`
> 
> In case this doesn't work out for you, go in that file and start commenting things you installed to find the culprit.

This worked for me! Thank you!

**Comment by mdrzn** [comment]
> In my case, I had [MegaCMD](https://github.com/meganz/MEGAcmd) installed which added a custom bash completion script: `/etc/bash-completion.d/megacmd_completion.sh`. The culprit was [this line](https://github.com/meganz/MEGAcmd/blob/master/src/client/megacmd_completion.sh#L79) in the said script, more precisely, the `compgen -ca | grep mega-` command. Removing the file or that for loop fixes the problem.

This solved it for me, went from over 10s to load to 0s. This thread is so important.
