### ISSUE TITLE
WSL 2 distro won't start if resource specified in /etc/fstab is not available

### ISSUE THREAD

**Issue by archilkarchava** [microsoft/WSL#4738]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
  Microsoft Windows [Version 10.0.19035.1]
* What you're doing and what's happening:
  add `\\192.168.1.1\Seagate1TB /media/keenetic cifs 
  rw,uid=0,credentials=/home/archil/.smb,iocharset=utf8 0 0 in /etc/fstab`
  Starting wsl distro.
* What's wrong / what should be happening instead:
  When I'm on a different network the distribution won't start.
  One workaround I found is adding `noauto` parameter.

**Comment by russelltg** [comment]
Adding `nofail` doesn't seem to help either, which is how you would address this on Linux
