### ISSUE TITLE
Cannot run Linux apps from Windows command line

### ISSUE THREAD

**Issue by akainth015** [microsoft/WSL#4740]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18363.476]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
From within Ubuntu; the following output is correct.
```bash
akainth@gram:/mnt/c/Users/akain$ rustc
Usage: rustc [OPTIONS] INPUT

[rest of output omitted for brevity]

akainth@gram:/mnt/c/Users/akain$ wslpath -w $(which rustc)
\\wsl$\Ubuntu\home\akainth\.cargo\bin\rustc
```
This is what is happening from the Windows command line (incorrect)
```cmd
Microsoft Windows [Version 10.0.18363.476]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\akain>wsl rustc
/bin/bash: rustc: command not found

C:\Users\akain>wsl -u akainth rustc
/bin/bash: rustc: command not found

C:\Users\akain>wsl wslpath -w $(which rustc)
wslpath: Invalid argument
Usage:
    -a    force result to absolute path format
    -u    translate from a Windows path to a WSL path (default)
    -w    translate from a WSL path to a Windows path
    -m    translate from a WSL path to a Windows path, with '/' instead of '\'

EX: wslpath 'c:\users'
```
* What's wrong / what should be happening instead:
`wsl` should emit the output of `rustc` and `wslpath`.
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
There is no repro here, but WAG you've set your `$PATH` to `rustc` in your `.bashrc`. Your `.bashrc`, meanwhile, isn't run with the command `wsl.exe rustc`. You almost certainly want:

```
C:\> wsl.exe -ic /bin/bash rustc
```

Or for illustration:
```
C:\> wsl.exe /bin/bash -ic 'echo $PATH'

```
vs...
```
C:\> wsl.exe /bin/echo $PATH
```
Effectively dupe #2816.

**Comment by akainth015** [comment]
Ah, you were pretty much correct, it was `export PATH="$HOME/.cargo/bin:$PATH"` in my `~/.profile`. Is it documented anywhere, or is it just something you have to remember?

**Comment by akainth015** [comment]
Just saving this here because using `bash -ic` alone did not fix it, probably because `rustup` adds the toolchain to PATH in `.profile`.
```
wsl bash -ic "source ~/.profile && rustc"
```
The following is also valid and functional
```
bash -c "source ~/.profile && rustc"
```

To load both `~/.bashrc` an `~/.profile`, you would have to do the following.
```
wsl bash -ic "source ~/.profile && nvm"
```
It is worth noting that this takes a non-negligible time to run (~2 seconds on my LG gram)

**Comment by therealkenc** [comment]
> Is it documented anywhere, or is it just something you have to remember?

Wouldn't know. Technically it is bog standard Linux-behavior. Spawing `rustc` (or anything else) doesn't imply `.bashrc` or `.profile` being run for no reason. That said, the behavior isn't eactly obvious either. You get `login(1)` behavior from `ssh you@localhost rustc`, which is arguably analgous.

They take PRs for doc improvements [here](https://github.com/MicrosoftDocs/WSL).

> It is worth noting that this takes a non-negligible time to run (~5 seconds on my LG gram)

Better than it [used to be](https://github.com/microsoft/WSL/issues/776#issuecomment-298078915). Better still in WSL2.
