### ISSUE TITLE
zsh crashes on typing `git commit -` segmentation fault

### ISSUE THREAD

**Issue by KsRyY** [microsoft/WSL#4742]
**Please fill out the below information:**
* Your Windows build number:  2004 (build 19035.1000)
* WSL Linux: Ubuntu 19.04 (Manually updated form Ubuntu 18.04 LTS)

* What you're doing and what's happening:  
``` bash
git commit 
```
and when I continue to type `-`, zsh crashes and leaves `zsh: segmentation fault (core dumped)`
When I came back, there is no history record of this.

* What should be happening instead:
No crashing

* Strace of the failing command, if applicable:  
***Not applicable***

**Comment by KsRyY** [comment]
This problem is plaguing me...
Could anyone suggest what happened?

**Comment by craigloewen-msft** [comment]
Is this something that you can repeat? Does it happen every time you run git commit? Are you using WSL 1 or WSL 2? 

This seems related to this WSL bug: https://github.com/microsoft/WSL/issues/4430 which leads to this terminal bug: https://github.com/microsoft/terminal/issues/2518 which was marked stale. Could you follow up on the Terminal thread and see if you can give them a repro?

**Comment by KsRyY** [comment]
@craigloewen-msft I noticed that they mentioned zdharma/fast-syntax-highlighting in these issues as a reason. I thought that's that case. Thank you.

**Comment by KsRyY** [comment]
I installed that plugin.
