### ISSUE TITLE
Make it possible to install without requiring a restart

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/WSL#4743]
**Is your feature request related to a problem? Please describe.**
I'm attempting to enable WSL on a remote machine which I have a shell access to but cannot restart. I know `Enable-WindowsOptionalFeature` has a `-NoRestart` switch, but when using it when installing WSL, the `wsl` command is then not available in PATH.

**Describe the solution you'd like**
```
Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName Microsoft-Windows-Subsystem-Linux
```

**Describe alternatives you've considered**
There is no alternative for restartless installation in my case. I cannot restart the target machine.

**Comment by Biswa96** [comment]
You have to restart that machine. `-NoRestart` option means that command does not show any prompt to restart.

**Comment by TomasHubelbauer** [comment]
My request is for not having to restart the machine to install and use WSL.

**Comment by Biswa96** [comment]
It is not possible. WSL is not a separate user mode program. It is a feature of Windows, it install kernel mode drivers, signed services, apiset dlls, hypervisor features etc.

**Comment by TomasHubelbauer** [comment]
That's unforrtunate. Do you know if WSL2 when GA will be the same in this regard?

**Comment by Biswa96** [comment]
What is GA?

**Comment by TomasHubelbauer** [comment]
Generally available, when WSL2 is out of Insiders, can I expect that will be enable-able without a restart? I don't think so, because installing WSL2 is still the same as installing WSL2, the different is that one can choose the generation for each VM, right? But the Windows feature is enabled the same way on Windows versions which support WSL2.

**Comment by craigloewen-msft** [comment]
To use WSL2, you will need to enable the `Virtual Machine Platform` optional component. If you're installing it for the first time it will require a restart. 

For more info on the WSL2 install process check out our docs [Install WSL2](https://aka.ms/wsl2-install)!

**Comment by TomasHubelbauer** [comment]
Okay, looks like I need to have the agent imaged ti include these Windows components beforehand and they are not possible to enable on the fly in an ephemeral VM.
