### ISSUE TITLE
WSL2 sleeps at startup

### ISSUE THREAD

**Issue by armacoty** [microsoft/WSL#4744]
* Windows build number: `Microsoft Windows [Version 10.0.19035.1000] `
* What I'm doing and what's happening: I start WSL 2 session through the Start menu or bash.exe in the console (or windows terminal)
![lolwat](https://user-images.githubusercontent.com/16017717/70371858-57efc780-18e9-11ea-84f7-087d9a425595.png)
* What's wrong / what should be happening instead: WSL2 sleeps at startup

---

What I found:
It responds to ^C --> problem in the `/etc/profile` or `.profile` or `.bashrc`

![image](https://user-images.githubusercontent.com/16017717/70371971-946ff300-18ea-11ea-95ec-cc7035693539.png)

---

I check files  `/etc/profile`, `.profile`, `.bash_rc` using the exception method:
- `.profile` - OK
- `.bashrc` - OK
- `/etc/profile` - the problem is most likely here

![image](https://user-images.githubusercontent.com/16017717/70372093-c33a9900-18eb-11ea-8b37-62ac5c728f1f.png)

---

`bash -x /etc/profile`:

![image](https://user-images.githubusercontent.com/16017717/70372143-465bef00-18ec-11ea-91b2-84cac01942fd.png)

`/etc/profile.d/wsl-integration.sh` - the problem is here

 `bash -x /etc/profile.d/wsl-integration.sh`:

![image](https://user-images.githubusercontent.com/16017717/70372165-a0f54b00-18ec-11ea-94d1-b38d4fa5fe9c.png)

---

problem on line 9 `/etc/profile.d/wsl-integration.sh`, WSL 2 sleeps if X11 is not started.

---

😄  after starting XMing, WSL sleeps 3 seconds 

![image](https://user-images.githubusercontent.com/16017717/70372229-69d36980-18ed-11ea-9368-943f80b7f3ce.png)

**Comment by benhillis** [comment]
I'm almost positive this is a duplicate of #4737
