### ISSUE TITLE
Wrong ubuntu (16 instead of 18)

### ISSUE THREAD

**Issue by vielhuber** [microsoft/WSL#4751]
Hello!

I installed ubuntu from the windows store. The package is called "Ubuntu" and should be, as stated, the latest 18.04.

When I open the wsl terminal and enter lsb_release -a, I get:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

I think this also happened suddenly, because I was sure to have 18.04.

Any ideas?

**Comment by Biswa96** [comment]
Ya, it's confusing. Here are the three Ubuntu in MS Store:

* Ubuntu: https://www.microsoft.com/store/productId/9NBLGGH4MSV6
* Ubuntu 16.04: https://www.microsoft.com/store/productId/9PJN388HP8C9
* Ubuntu 18.04: https://www.microsoft.com/store/productId/9N9TNGVNDL3Q

**Comment by vielhuber** [comment]
Yup; I've installed "Ubuntu". But this should be Ubuntu 18.04, or am I wrong?
I'm on Windows 10 Pro 1909.

**Comment by therealkenc** [comment]
Ubuntu's forums [here](https://ubuntuforums.org/).

**Comment by benhillis** [comment]
@therealkenc is right, we do not have control over what version Canonical ships in their packages.

**Comment by vielhuber** [comment]
I've opened a ticket here but got the expected answer, that they are not responsible: https://ubuntuforums.org/showthread.php?t=2433394&p=13917973#post13917973

**Comment by therealkenc** [comment]
Unfortunately the "they" you got is singularly incorrect [glaring hint being the opening "I have not used this software".] Ubuntu is not (quoth) "a modified version of Ubuntu/Linux created by microsoft". Which you (and they) can see clearly in the [Store](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q?activetab=pivot:overviewtab). Ubuntu is distributed by Canonical Group Limited.

![image](https://user-images.githubusercontent.com/7049700/71563390-7c9c1280-2a43-11ea-98a2-98ffb57c8faf.png)

Cutting to the chase in the interest of closure, of the three Biswa96 linked a few weeks ago, you want last one. Uninstalling all of your existing distros before installing 18.04 will probably simplify your experience; although you can run multiple distros at the same time, and select the default with `wsl.exe --set-default, -s <Distro>`.

**Comment by vielhuber** [comment]
Thanks, I will do this.
