### ISSUE TITLE
WSL-2 (build 19037) Can't to internet

### ISSUE THREAD

**Issue by CalBR** [microsoft/WSL#4753]
I was using build 19033 without problems. Updated to 19037 and installed WSL-2 and my internet stopped working. To be able to use the internet I had to set the nameserver to 8.8.8.8 in the /etc/resolv.conf which solves the connection failure but keeps me from using the X410. Any suggestions?

**Comment by therealkenc** [comment]
There isn't enough to go on regarding your DNS lookup (with resolv.conf work-around) to suggest anything concrete. On the X410 part, likely #4106 landing zone #4619.
