### ISSUE TITLE
Pasting clipboard into linux programs started from WSL does not work

### ISSUE THREAD

**Issue by jshnaidman** [microsoft/WSL#4755]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.535]

I'm running Ubuntu 18.04 LTS on WSL

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

sudo apt-get install terminator
DISPLAY=:0 terminator

copy something from windows environment onto the clipboard
try to use ctrl+shift+v to paste the contents into terminator
Nothing happens

* What's wrong / what should be happening instead:

The contents of the clipboard should be pasted into terminator

**Comment by DHowett-MSFT** [comment]
You are out of the realm of the Windows clipboard and you’ll have to take this issue up with your X11 server provider. The X server handles the clipboard for X11 applications.

**Comment by craigloewen-msft** [comment]
@DHowett-MSFT is correct, unfortunately copy and paste functionality isn't controlled by us (the WSL team) in this case, and you'll need to file this issue with the X11 server provider! Sorry to redirect you, and thanks for filing!
