### ISSUE TITLE
Windows Defender detects Ubuntu 16 nslookup as Trojan

### ISSUE THREAD

**Issue by jarmo** [microsoft/WSL#4757]
* Your Windows build number:
Microsoft Windows [Version 10.0.18363.535]

* What's wrong / what should be happening instead:
Defender detects `rootfs\usr\bin\nslookup` inside of WSL Ubuntu 16 as `Trojan:AndroidOS/BoxerSms` or `Trojan:AndroidOS/AndroRat`. I don't think that should happen?

**Comment by jarmo** [comment]
Here's a report for nslookup https://www.virustotal.com/gui/file/d91421c9ba7d507cda9efe8464b0dd3bfe9a31fea22e3006380a9451e35c9975/detection

**Comment by sirredbeard** [comment]
Can you please report back:

- [Your Windows Defender version](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version)
- The version of dnsutils you have installed. `$ dpkg -s dnsutils | grep '^Version:'`

I am on 1.307.504 and dnsutils 9.10.3.dfsg.P4-8ubuntu1.15 and I am unable to reproduce.

You can [submit these false positives](https://www.microsoft.com/en-us/wdsi/filesubmission) to Windows Security Intelligence. 

I went ahead and filed a report on this. Submission numbers 59102dd8-a63d-466d-92da-441b57021db2 and  fca6a9a7-01e9-4226-b7e4-c8330325b0e3.

**Comment by jarmo** [comment]
* Windows Defender (Security Intelligence) version: 1.307.557.0
* dnsutils version 1:9.10.3.dfsg.P4-8ubuntu1.14

Thanks, also submitted (hopefully) false positives to Windows Security Intelligene. Will keep this updated if I hear anything back from there.

**Comment by jarmo** [comment]
I see that nslookup was detected as a malware `Trojan:AndroidOS/BoxerSms` at the Windows Security Intelligence submission too. However, nsupdate is clean there.

**Comment by jarmo** [comment]
This is the response I got back from submissions:
```
We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.
```

However, I failed to follow these instructions:
```
c:\Program Files\Windows Defender>MpCmdRun.exe -removedefinitions -dynamicsignatures

Service Version: 4.18.1911.3
Engine Version: 1.1.16600.7
AntiSpyware Signature Version: 1.307.577.0
AntiVirus Signature Version: 1.307.577.0

Starting Dynamic Signature removal.Failed! Error 0x80070005

Service Version: 4.18.1911.3
Engine Version: 1.1.16600.7
AntiSpyware Signature Version: 1.307.577.0
AntiVirus Signature Version: 1.307.577.0
CmdTool: Failed with hr = 0x80070005. Check C:\Users\jarm0\AppData\Local\Temp\MpCmdRun.log for more information
```

In log file this is shown:
```
-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎E ‎dets ‎16 ‎2019 20:55:12

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpRemoveDefinitions(0)
ERROR: MpRollbackSignature failed with hr=80070005
MpCmdRun: End Time: ‎E ‎dets ‎16 ‎2019 20:55:12
-------------------------------------------------------------------------------------
```

Any ideas how to continue?

**Comment by sirredbeard** [comment]
I would try manually installing the new definitions.

**Comment by jarmo** [comment]
Closing this since threats got neutralized.
