### ISSUE TITLE
Upgrade to 19.10 hangs

### ISSUE THREAD

**Issue by alippai** [microsoft/WSL#4763]
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.1]

* What you're doing and what's happening: 

1. Installed Ubuntu from the store
2. Upgraded the Ubuntu to 19.04 (this works)
3. Run the upgrade again <-- it stuck at Setting up lvm2 (2.03.02-2ubuntu6) ...

* What's wrong / what should be happening instead:
I should be able to upgrade to 19.10.

I've tried to shutdown and do `apt upgrade`, also `apt purge lvm2` and `rm -rf /etc/lvm`, it didn't help.

**Comment by Biswa96** [comment]
If upgrade does not work you can install Ubuntu 19.10 directly.

1. Go to https://cloud-images.ubuntu.com/releases/eoan/release/
2. Download  `ubuntu-19.10-server-cloudimg-amd64-wsl.rootfs.tar.gz` file.
3. Import the tarball where you want to install the new distribution, use `wsl.exe --import` command. `wsl.exe --help` can shows the details.
4. Copy home directory from old distribution using `cp` command, **not** any Windows command or Ctrl+C and Ctrl+P.
5. Use `apt list --installed` to get the installed packages in old distribution and install those in new one.

**Comment by alippai** [comment]
I hit "Repair" in Settings (Add / remove programs, Ubuntu) and it fixed the issue. I'm not sure how or what it did, but after this I was able to install & update packages.

**Comment by lengthmin** [comment]
it seem hangs in memtest86+ on grub...
and click the setting's Repair button didn't help...

**Comment by lengthmin** [comment]
after diabled lvm2 scan, dpkg works.

see:
https://bbs.archlinux.org/viewtopic.php?id=242689
and here are details:
edit `/etc/lvm/lvm.conf `
set this options to `0`:
```
    # Disable scanning udev for md/multipath components.
    # This is required with recent versions of lvm2, even if you use another solution for
    # your LV device nodes; without it lvm commands will stall for minutes waiting for udev.
    multipath_component_detection = 0
    md_component_detection = 0

    # Set to 0 to disable udev synchronisation (if compiled into the binaries).
    udev_sync = 0
    # Set to 0 to disable the udev rules installed by LVM2
    udev_rules = 0
```

**Comment by therealkenc** [comment]
This one is pretty much tag external. WSL has no GRUB (let alone LVM), and the [grub package](https://packages.ubuntu.com/bionic/grub-common) (analogous Docker) was somehow installed. Whatever user experience improvements would be upstream those packages. One can reasonably assume Ubuntu 20.04 LTS will appear in the store at some point.
