### ISSUE TITLE
Ubuntu 16.04 nslookup getting Trojan:AndroidOS/BoxerSms alert

### ISSUE THREAD

**Issue by javadan** [microsoft/WSL#4764]
Not sure this is the place to write about this, but this is where the Microsoft pages take me.

After installing Ubuntu 16.04 from the App Store, nslookup gets a Severe threat from the nslookup command. 

Is that a false positive?  Not sure Android or Sms's have anything to do with installing Ubuntu on WSL.

**Comment by sirredbeard** [comment]
Duplicate of #4757
