### ISSUE TITLE
how to add second network interface  for wsl2

### ISSUE THREAD

**Issue by gao4263** [microsoft/WSL#4765]
i want to install oracle database 19c into wsl2  ,   it need a  ip (not support 127.0.0.1)  ,but wsl2 ip  is change when win10 rebooted .

i add a  eth1 file  , and exec " ifup eth1 start"
 report: /etc/sysconfig/network-scripts/ifup-eth] Device eth1 does not seem to be prepresent, delaying initialization

**Comment by luxzg** [comment]
One of many issues with DefaultSwitch and not having other options. Just like #4210 / 
 #4601 / #4467 / #4150 / #4799 ; to name a few.

I'm taking my time today to mark all these issues.

**Comment by tbarbette** [comment]
To answer to the title of this issue, this tool can be used to add multiple switches : https://github.com/dantmnf/WSLAttachSwitch
