### ISSUE TITLE
WSL 2 can't be installed

### ISSUE THREAD

**Issue by sdutwangkaisdut** [microsoft/WSL#4766]
Everything seem OK while I was going through each step, but wsl 2 just can't be set in the end. I'm with bulild 19041.1. What's wrong here?

PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2

PS C:\WINDOWS\system32> wsl -l -v
  NAME      STATE           VERSION
 Ubuntu    Stopped         1

**Comment by craigloewen-msft** [comment]
Please make sure you have the 'Virtual Machine Platform' optional component installed. You can do so by running this command from an admin level Powershell and then restarting after:

`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

And if that doesn't resolve your issue, make sure you have Virtualization enabled in your BIOS. You can see if Virtualization is enabled on your computer by looking at Task Manager -> Performance -> CPU

![image](https://user-images.githubusercontent.com/42221804/70930633-7db45500-1fea-11ea-9287-c8e0bedfbe46.png)

**Comment by sdutwangkaisdut** [comment]
Hi Craig,

       Thank you for the reply. I didn't enable Virtualization in BIOS previously, which caused the issue. Now I have successfully enabled WSL 2.

Thank you,
Kai

**Comment by hectorviov** [comment]
I did all that was suggested, and I can see "Virtualization: Enabled" but still getting the error.

`Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install`

What else can I try?

**Comment by ssgromov** [comment]
Same here. Win 10 Ent build 19035.

**Comment by AurinoJunior** [comment]
Thank you Craig, helped me a lot. 😄 👍 🚀

**Comment by AurinoJunior** [comment]
> Please make sure you have the 'Virtual Machine Platform' optional component installed. You can do so by running this command from an admin level Powershell and then restarting after:
> 
> `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
> 
> And if that doesn't resolve your issue, make sure you have Virtualization enabled in your BIOS. You can see if Virtualization is enabled on your computer by looking at Task Manager -> Performance -> CPU
> 
> ![image](https://user-images.githubusercontent.com/42221804/70930633-7db45500-1fea-11ea-9287-c8e0bedfbe46.png)

Thank you Craig, helped me a lot. 😄 👍 🚀

**Comment by justinmchase** [comment]
I have virtualization enabled:
![image](https://user-images.githubusercontent.com/10974/85228806-62683f00-b3ab-11ea-9a46-56dc00a737ec.png)

I have the right version installed:
![image](https://user-images.githubusercontent.com/10974/85228820-7744d280-b3ab-11ea-93da-20686c6b410f.png)

I have run the command to enable virtual machine platform:
![image](https://user-images.githubusercontent.com/10974/85228847-9c394580-b3ab-11ea-8bbd-40b78319df63.png)

Yet I'm still getting the error:
> Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
> For information please visit https://aka.ms/wsl2-install

What am I missing?

**Comment by justinmchase** [comment]
Ok I figured it out, the command in the documentation has this flag ` /norestart` so the machine doesn't restart but you do actually need to restart to complete the update.

**Comment by juanpablomorenomartin** [comment]
@justinmchase, I have exactly the same problem, I do not understand how you solved it.

**Comment by rahulkathar** [comment]
I have tried below there a command for WSL2 but still, it gives me an error. Please suggest a proper solution below error.

dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform -NoRestart

restart system

PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2

**Comment by 5E7EN** [comment]
As @vservin points out in #5749, you may have to use the `--set-version` flag and specify the instance name followed by the desired WSL version.

Example:
```
> wsl -l -v
NAME                   STATE           VERSION
Ubuntu-20.04           Stopped         1
```
```
> wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
```

**Comment by jrarturo** [comment]
> Everything seem OK while I was going through each step, but wsl 2 just can't be set in the end. I'm with bulild 19041.1. What's wrong here?
> 
> PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
> For information please visit https://aka.ms/wsl2-install
> 
> PS C:\WINDOWS\system32> wsl --set-default-version 2
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> 
> PS C:\WINDOWS\system32> wsl -l -v
> NAME STATE VERSION
> Ubuntu Stopped 1


I have the same problem, here's my solution:

**check if you have one or more versions:**  On command prompt `wls -l -v`
**Now convert all versions to wsl 2:** On command prompt `wsl --set-version <NAME> 2`

That works for me. 

![image](https://user-images.githubusercontent.com/62453825/101054403-dc097900-3556-11eb-86b9-631f185fbb8a.png)




See ya.

**Comment by Adamkaram** [comment]
i do every thing but it's Not working 
Notcie i have ubunt on my windows

**Comment by vindevoy** [comment]
I had WSL2 working until a couple of days ago.

- Bios is ok, I can check with the screenshot also here in a previous comment: virtialization is enabled
- The VirtualMachinePlatform is enabled and I rebooted
- Hyper-V is nowhere enabled in the "turn windows features on or off" thing

I was running Debian and even VMware workstation.  Then I installed VMware Horizon client and now my WSL gives this error as described above, whereas both things mentioned are set correctly and it was working before.

I really start to dislike this WSL stuff.

**Comment by justinmchase** [comment]
We're going to need more info than just "its not working", what errors are you seeing? What commands are you running, what do you see when you run `wsl -l -v`, what version of windows do you have, etc.

**Comment by vindevoy** [comment]
> We're going to need more info than just "its not working", what errors are you seeing? What commands are you running, what do you see when you run `wsl -l -v`, what version of windows do you have, etc.

https://user-images.githubusercontent.com/10974/85228847-9c394580-b3ab-11ea-8bbd-40b78319df63.png

**Comment by vindevoy** [comment]
> > We're going to need more info than just "its not working", what errors are you seeing? What commands are you running, what do you see when you run `wsl -l -v`, what version of windows do you have, etc.
> 
> Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
> 
> https://user-images.githubusercontent.com/10974/85228847-9c394580-b3ab-11ea-8bbd-40b78319df63.png

But I solved it.  In the end it was very simple.

I removed all the components through the Control Panel, even the downloaded Debian distribution. 
I removed all features linked to this.
Rebooted 
Re-installed it all again.

It only took me half a day.

**Comment by letmeseesome** [comment]
![image](https://user-images.githubusercontent.com/25289798/148453673-914c849c-5ac3-4b00-b752-c4d5caa81888.png)

**Comment by vservin** [comment]
@letmeseesome You need to enable virtualization in BIOS or UEFI, depends on your motherboard manufacturer and processor, in case of an intel-based machine it should look something like this:
![image](https://user-images.githubusercontent.com/43255681/148479865-b3f28988-f13b-47ed-a05a-e3f2400f3acb.png)
On a ryzen based machine it should look something like this called "SVM Mode"
![image](https://user-images.githubusercontent.com/43255681/148479978-79fd4dde-8271-49a8-8010-7bb96bebe5aa.png)

Let me know if that helped!

**Comment by letmeseesome** [comment]
> 

![image](https://user-images.githubusercontent.com/25289798/148635761-b4e1b643-3632-4e6a-b201-3995c4230bbb.png)

**Comment by letmeseesome** [comment]
> @letmeseesome You need to enable virtualization in BIOS or UEFI, depends on your motherboard manufacturer and processor, in case of an intel-based machine it should look something like this: ![image](https://user-images.githubusercontent.com/43255681/148479865-b3f28988-f13b-47ed-a05a-e3f2400f3acb.png) On a ryzen based machine it should look something like this called "SVM Mode" ![image](https://user-images.githubusercontent.com/43255681/148479978-79fd4dde-8271-49a8-8010-7bb96bebe5aa.png)
> 
> Let me know if that helped!

![image](https://user-images.githubusercontent.com/25289798/148635832-1f13d9d9-d148-4c45-86ca-725d13385ca4.png)

**Comment by jinhale** [comment]
Just for reference. I noticed this problem after a restart and having done no configuration to it or docker. I have three versions of Linux installed on November 25th 2022, which worked literally yesterday but not now even after running the command to enable virtualization, restarting, and noting virtualization is enabled as per the Task Manager. Yesterday I silently uninstalled a version of HAXM and installed a different version of it via Android Studio which has not adversely affected Android virtual device emulation. I have installed the WSL update November. 

After uninstalling every Linux version and installing Ubuntu via `wsl --install -d Ubuntu-20.04` I now have a new error: `WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.`

**Comment by jinhale** [comment]
I have since found what I think to be a the [likely solution ](https://askubuntu.com/a/1276072/1656311)for most people who have already followed the instructions. Sometimes Windows will, for no apparent reason fail to property check for the necessary features and thus falsely report that this feature is disabled. The hack is to cycle the feature, Virtual Machine Platform. I have Hyper-V disabled and three versions of Linux running after disabled the feature, restarting, enabling the feature, and finally restarting.

**Comment by Elijoodaki123** [comment]
My friends, I did all the necessary things, but I still have problems with installing WSL2. If anyone knows, I would be grateful

PS C:\WINDOWS\system32> wsl --set-version Ubuntu-20.04 2
F o r   i n f o r m a t i o n   o n   k e y   d i f f e r e n c e s   w i t h   W S L   2   p l e a s e   v i s i t   h t t p s : / / a k a . m s / w s l 2 
 
 F a i l e d   t o   c o n f i g u r e   n e t w o r k   ( n e t w o r k i n g M o d e   N a t ) .   T o   d i s a b l e   n e t w o r k i n g ,   s e t   ` w s l 2 . n e t w
 o r k i n g M o d e = N o n e `   i n   C : \ U s e r s \ E l i \ . w s l c o n f i g 
 
 E r r o r   c o d e :   W s l / S e r v i c e / C r e a t e V m / C o n f i g u r e N e t w o r k i n g / H N S / E R R O R _ F I L E _ N O T _ F O U N D 
![Capture](https://github.com/user-attachments/assets/ff92c253-e8e7-4c9a-a8d8-883247a95a73)

**Comment by kshatra1783** [comment]
I had followed each comment and did all necessary setps, but still cannot uprade to wsl2

C:\Windows\system32>wsl --set-version Ubuntu-22.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

**Comment by luiisp** [comment]
> I had followed each comment and did all necessary setps, but still cannot uprade to wsl2
> 
> C:\Windows\system32>wsl --set-version Ubuntu-22.04 2 Conversion in progress, this may take a few minutes... For information on key differences with WSL 2 please visit https://aka.ms/wsl2 Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS. For information please visit https://aka.ms/wsl2-install

**I had the same problem but I solved it by running:**
 ```bcdedit /set hypervisorlaunchtype auto```

basically it ensures that Hyper-V runs along with the boot, try running the command restart your computer
