### ISSUE TITLE
Another Error: 0x80070002 issue

### ISSUE THREAD

**Issue by fariello** [microsoft/WSL#4772]
I had had WSL installed since the first beta, and I have been updating (inside with apt update, outside with Windows Updates) ever since. About a week ago, on one of my systems, it "broke" [Note 2]. I therefore decided to "upgrade" to the current as of Dec 2019 MS Store Ubuntu version.

I removed the Windows Subsystem for Linux by simply uninstalling form the programs and features since it was an option (right-clicking on the start menu icon for Bash). Windows reported uninstalling successfully, but I could still launch it, and it "worked", aparently no less broken than before. Arguably, I should have delved deeper at that point,  but I went ahead and installed the MS Store Ubuntu and then tried running LxRun.exe. I ran

`./LxRun.exe /uninstall /full /y`

In an administrative powershell:

```
C:\WINDOWS\system32> .\LxRun.exe /uninstall /full /y
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Uninstalling...
Error: 0x80070002
```

Trying to reinstall results in the same thing.

```
C:\WINDOWS\system32> .\LxRun.exe /install /y
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

This will install Ubuntu on Windows, distributed by Canonical and licensed under its terms available here:
https://aka.ms/uowterms

Error: 0x80070002
```

The output was identical before and after uninstalling the new MS Store Ubuntu which uses different paths and registry keys (as far as I can tell).

When turning WSL off in the system features (`Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` or via GUI, did both), the error switched to `Error: 0x80040154`, so I re-enabled.

At no time that I can tell did anything in the %AppData%\Local\lxss\` directory change and `C:\WINDOWS\system32\LxRun.exe` was never removed.

Even after uninstalling all MS Store apps, registry keys such as 

-`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss`
-`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Svchost\LxssManagerUser`
-`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\PackageDetect\Microsoft-Windows-Lxss-Optional-Package~*`
-`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\PackageDetect\Microsoft-Windows-Lxss-Optional-onecore-Package~*`
-`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\PackageDetect\Microsoft-Windows-Lxss-Package~*`
-`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\PackageDetect\Microsoft-Windows-Lxss-onecore-*`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\ManufacturingMode\Default\Services\lxss`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\LxssManagerUser`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\LxssManager`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\lxss`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\ManufacturingMode\Default\Services\lxss`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManagerUser_*`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManagerUser`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager`
-`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss`
-`Computer\HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Lxss`

And many others persisted. Some disappeared (I could not find references to the `%AppData%\Local\lxss\root` or `%AppData%\Local\lxss\mysuername` directories, for example, which I thought had been there. There used to be a program called "Ubuntu Clean" that helped clean up WSL, but I can't find it.

I tried some other solutions (see Note 1) to no avail, and ultimately simply removed the `%AppData%\Local\lxss\` directories manually, removed other stragglers that I could find in a similar way, but left the Registry alone. I've kept `C:\WINDOWS\system32\LxRun.exe` in place, not sure why, and I did not touch other things in the `C:\WINDOWS` folder because it's not a great idea, but I'm still left with a partial WSL legacy system sprinkled around my system until I do a clean Windows install, and that's not a great place to be.

Side note: After BOTH the Control Panel uninstall of the legacy WSL AND the first `./LxRun.exe /uninstall /full /y` which did do something (I did not save the output between system reboots, unfortunately), the legacy WSl bash environme environment still worked just as well as before trying to uninstall.

Note 1: Tried solutions in
- https://github.com/Microsoft/WSL/issues/2590
- https://github.com/Microsoft/WSL/issues/2967

Note 2: Although I cannot be certain this was the cause, things stopped working around the time that Jonathan F (https://launchpad.net/~jonathonf) made his PPAs private. I could not even run apt properly because python2.7, pysqlite, and pycompile were on the fritz, so I could not remove, update, reinstall, etc

Edit: Formatting

**Comment by therealkenc** [comment]
This issue went stale without a local repro, and the `lxrun.exe` app has been deprecated in favor of `wsl.exe`. If the problem persists on Windows 20H2 aka 19042 (or better), please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), catching the `0x80070002` from `wsl.exe` if it persists.
