### ISSUE TITLE
[WSL2] drvfs drives do not mount automatically

### ISSUE THREAD

**Issue by theRemix** [microsoft/WSL#4774]
### Your Windows build number

**Microsoft Windows [Version 10.0.19041.1]**

### What you're doing and what's happening: 
- Launch Ubuntu 18.04 LTS
- wsl automount and fstab are not automounting
- enter `mount | grep drvfs` into bash
- no output, c drive is not mounted

### What's wrong / what should be happening instead:

`mount | grep drvfs` should return 

```
C: on /mnt/c type 9p (rw,relatime,dirsync,aname=drvfs;path=C:;symlinkroot=/,mmap,access=client,msize=65536,trans=fd,rfd=3,wfd=3)
C: on /c type 9p (rw,relatime,dirsync,aname=drvfs;path=C:;symlinkroot=/,mmap,access=client,msize=65536,trans=fd,rfd=3,wfd=3)
```

### /etc/fstab

`sudo mount -a` will mount all drives, though this doesn't happen automatically at bootup

```
LABEL=cloudimg-rootfs   /        ext4   defaults        0 0

C: /mnt/c drvfs defaults 0 0

# don't use symlink because docker won't work
/mnt/c /c none bind,umask=0222

```

### /etc/wsl.conf

```
[automount]
root = /
options = "metadata"
```

**Comment by LouisDega** [comment]
This configuration in the file /etc/wsl.conf helped me.
`[automount]
root = /
enabled = true
options = "uid=1000,gid=1000,umask=022,fmask=11,metadata"`
