### ISSUE TITLE
localhost doesn't work anymore after latest Insider program update

### ISSUE THREAD

**Issue by Geddard** [microsoft/WSL#4777]
* Your Windows build number:  Microsoft Windows [Version 10.0.19536.1000]

* What you're doing and what's happening:  Before i was able to access my wsl nodejs servers in windows using `localhost:port`, but since the last update i have to use the server ip, and i think this is screwing with some apps, like puppeteer running chromium

* What's wrong / what should be happening instead: i want localhost working again, so i can rule it out from what's breaking other parts of my apps

**Comment by onomatopellan** [comment]
Known regression https://github.com/microsoft/WSL/issues/4769#issuecomment-567162940

**Comment by Geddard** [comment]
> Known regression [#4769 (comment)](https://github.com/microsoft/WSL/issues/4769#issuecomment-567162940)

OK, thx, I couldn't find this info before :)
I can't roll back to a previous version for some reason.
Anyway, it's Friday so I hope next week this fix will be already available since I can't figure out how to do the "go back to previous version" hehe.

Regards
