### ISSUE TITLE
Virtual Machine Platform installation failure

### ISSUE THREAD

**Issue by jokem59** [microsoft/WSL#4780]
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.1]

* What you're doing and what's happening:  Whether I run `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart` or go through the "Turn Windows features on or off" GUI, after enabling VirtualMachinePlatform, I restart my machine per the instructions.  WSL is already installed/enabled.

* What's wrong / what should be happening instead: WIndows 10 fails to boot and enter computer goes into diagnostics/recovery mode.  If I boot into Safe Mode, I get a message before the Windows login screen that an update failed to install (presumably Virtual Machine Platform).

* Strace of the failing command, if applicable:  No immediately available error messages.

**Comment by therealkenc** [comment]
/dupe #4784 (+4 upward direction only because there's more traffic over there)
