### ISSUE TITLE
bash not picking up ~/.pam_environment

### ISSUE THREAD

**Issue by clearnote01** [microsoft/WSL#4782]
Steps to reproduce -> 

1. `echo "FOO=foo" >> ~/.pam_environment`
2. `sudo login`
3. `echo $FOO # returns blank; expected output:  foo`

Use of `~/.pam_environment` file?
- 

> Suitable files for environment variable settings that should affect just a particular user (rather than the system as a whole) are ~/.pam_environment and ~/.profile. After having edited one of those files, you should re-login in order to initialize the variables.

- https://help.ubuntu.com/community/EnvironmentVariables

Windows build number:  `Microsoft Windows [Version 10.0.19041.1]`

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/72309456-e61b4400-3633-11ea-9541-671d50a51a7d.png)

**Comment by alexander-novo** [comment]
Can some light be shed on why this issue is marked as bydesign and closed? How are environment variables meant to be set on WSL?
