### ISSUE TITLE
WSL connect failed

### ISSUE THREAD

**Issue by lujfsd** [microsoft/WSL#4786]
[reference](https://github.com/microsoft/vscode/issues/87752#issue-542755244)

**Comment by therealkenc** [comment]
> Most likely duplicate of microsoft/vscode-remote-release#2082 and root cause microsoft/WSL#4769

Will buy that explanation for lack.

**Comment by lujfsd** [comment]
yes ,this issues will be closed and look at [#4769](https://github.com/microsoft/WSL/issues/4769#issue-539022713)
