### ISSUE TITLE
ASCII control characters/sequences in WSL Ubuntu

### ISSUE THREAD

**Issue by fatherofinvention** [microsoft/WSL#4788]
Hello - 

The attached screenshot shows how the [Shift In control character](https://en.wikipedia.org/wiki/Shift_Out_and_Shift_In_characters) is rendering in WSL Ubuntu, specifically inside of [Vit ](https://github.com/scottkosty/vit) which is written in Python running in the new [Windows Terminal](https://github.com/microsoft/terminal). The font in use is [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono).

`SI (0x0F, ^O) activates the G0 character set;`
[Source](http://man7.org/linux/man-pages/man4/console_codes.4.html)

I am not sure if this is a WSL issue, Windows Terminal issue, a code page issue, a font issue, or a Python issue. I am hoping someone more knowledgeable can comment on whether this is a fundamental limitation of WSL's support of control characters or if this can be resolved by changing a setting. I have tried numerous monospace fonts without any luck.

![SI-control-characters](https://user-images.githubusercontent.com/24985048/71548000-7bdc8100-295c-11ea-8ab8-cbd48f394436.jpg)

Thank you.

**Comment by therealkenc** [comment]
You'll get better eyeballs on this one over in the terminal github. Probably get more takers with (a) some CLI steps to follow (b) your version information. It isn't clear "The font in use is Ubuntu Mono". Windows terminal uses Windows fonts. [It is hypothetically possible to install Ubuntu Mono on Windows, but that's almost certainly not your scenario.]
