### ISSUE TITLE
[WSL] Launcher. Icon from taskbar has reversed colors.

### ISSUE THREAD

**Issue by MicroBates** [microsoft/WSL#4789]
**1) Issue Title**
Bash On Ubuntu's icon from taskbar has reversed colors.

**2) Windows version / build number**
```
C:\Users\Windows>ver
Microsoft Windows [version 10.0.18362.535]
```
**3) Steps required to reproduce**
* Windows 10 Home edition 1903
* In Settings>Personalization>Taskbar
* "Use little button in taskbar" property is disenabled (/!\ otherwise the good icon is displayed)
* Install "Ubuntu" app from Windows Store (not the "Ubuntu 18.04" app)

**4) Copy of the terminal output**
N/A

**5) Expected Behavior**
To be displayed the 24 size icon with  the **orangish and round background** in the taskbar, that might be called `Square44x44Logo.altform-unplated_targetsize-24.png`

**7) Additional information**
In 
`C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc\Assets`
icon files are listed, it seems to lack a `Square44x44Logo.altform-unplated_targetsize-24.png`, whereas there are two files that match this size:
* `Square44x44Logo.targetsize-24.png`
* `Square44x44Logo.targetsize-24_altform-unplated.png`

But those have reversed colored, and thus doesn't meet the specification from Ubuntu logo guidelines.
I couldn't find or create the matching file as I can't produce a Package.appxmanifest.

Thx for reading those lines, and happy new year!

**Comment by DHowett-MSFT** [comment]
Canonical produced the Ubuntu package with the offending icon. :smile:

**Comment by MicroBates** [comment]
> Canonical produced the Ubuntu package with the offending icon. 😄

😂👍 I don't know where that comme from I went full "legal" with this "thus doesn't meet the specification from blabla"
Anyway, I opened a thread at askubuntu for those interested [https://askubuntu.com/questions/1199408/bash-on-ubuntu-on-windows-launcher-icon-from-taskbar-has-reversed-colors](https://askubuntu.com/questions/1199408/bash-on-ubuntu-on-windows-launcher-icon-from-taskbar-has-reversed-colors)

@DHowett-MSFT thank you for the quick reply.
