### ISSUE TITLE
lseek system call does not support SEEK_DATA or SEEK_HOLE

### ISSUE THREAD

**Issue by rk9109** [microsoft/WSL#4796]
**Build Number:** Microsoft Windows [Version 10.0.18362.535]

**Issue:** The code snippet below creates a sparse file containing holes. The calls to `lseek` using `SEEK_DATA` and `SEEK_HOLE` fail with error `EINVAL (Invalid argument)`, although these additional values should be supported since Linux version 3.1.

Is this a limitation associated with current WSL support for sparse files? Seems to be related to issues #1321 and #1886. It appears that this would cause problems for software that use `SEEK_DATA` and `SEEK_HOLE` for processing sparse files. As described in the man page for `lseek`:
>In the simplest implementation, a filesystem can support the operations by making SEEK_HOLE always return the offset of the end of the file, and making SEEK_DATA always return offset (i.e., even if the location referred to by offset is a hole, it can be considered to consist of data that is a sequence of zeros).

Code (`test_hole.c`):
```C
#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>

#define HOLE_SIZE 100
#define PATTERN "teststring"
#define PATTERN_SIZE 10

int main(int argc, char** argv) {
    int fd;
    off_t offset = 0;

    // open file (rw-------)
    fd = open(argv[1], O_WRONLY | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
    if (fd == -1) {
        perror("open");
        exit(EXIT_FAILURE);
    }

    // write PATTERN to open file; seek past EOF and rewrite PATTERN
    // should create a file hole with size HOLE_SIZE
    write(fd, PATTERN, PATTERN_SIZE);
    offset += PATTERN_SIZE + HOLE_SIZE;
    lseek(fd, offset, SEEK_SET);
    write(fd, PATTERN, PATTERN_SIZE);

    // errno: EINVAL (Invalid argument)
    // should return 0 (the file contains real data at offset 0)
    if (lseek(fd, 0, SEEK_DATA) == -1) {
        perror("SEEK_DATA");
    }

    // errno: EINVAL (Invalid argument)
    // should return 10 (next hole at offset 10)
    if (lseek(fd, 0, SEEK_HOLE) == -1) {
        perror("SEEK_HOLE");
    }

    close(fd);

    exit(EXIT_SUCCESS);
}
```
Running `./test_hole test` returns:
```
$ ./test_hole test
SEEK_DATA: Invalid argument
SEEK_HOLE: Invalid argument
```

The actual contents of the file are as expected:
```
$ cat test
teststring                                                                                                    teststring
```

The relevant strace:
```
openat(AT_FDCWD, "test", O_WRONLY|O_CREAT|O_EXCL, 0600) = 3
write(3, "teststring", 10)              = 10
lseek(3, 110, SEEK_SET)                 = 110
write(3, "teststring", 10)              = 10
lseek(3, 0, SEEK_DATA)                  = -1 EINVAL (Invalid argument)
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
brk(NULL)                               = 0x7fffd107d000
brk(0x7fffd109e000)                     = 0x7fffd109e000
fstat(4, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(4, "SEEK_DATA: Invalid argument\n", 28SEEK_DATA: Invalid argument
) = 28
close(4)                                = 0
lseek(3, 0, SEEK_HOLE)                  = -1 EINVAL (Invalid argument)
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
fstat(4, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(4, "SEEK_HOLE: Invalid argument\n", 28SEEK_HOLE: Invalid argument
) = 28
close(4)                                = 0
close(3)                                = 0
exit_group(0)                           = ?
```

**Comment by therealkenc** [comment]
Thanks for the excellent report. 

> Is this a limitation associated with current WSL support for sparse files?

Without having actually run your code, almost certainly. 

De facto landing zone #1732. Pragmatic solution[ WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/). On WSL2 your test case will work on `/home/you/test`, which is just a normal ext4 filesystem. It would be mildly interesting to try `/mnt/c/Users/you/test` (the 9p fs) too and see if it works.
