### ISSUE TITLE
Graphics driver problem after installing WSL

### ISSUE THREAD

**Issue by ThaiLe011094** [microsoft/WSL#4797]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

A brief description
I activated WSL. It messed up my graphics driver.
I have a Dell Inspiron 7447 with Intel HD4600 and nVidia GTX 850M.

Expected results
No driver problem.

Actual results (with terminal output if applicable)
Intel driver appeared to work incorrectly, even showed laggy when the startmenu appeared. There is no intel function on right-clicking at the desktop.

Your Windows build number
Microsoft Windows 10 Education 64 bit [Version 10.0.18363.535]

Steps / All commands required to reproduce the error from a brand new installation
Normal steps to activate WSL. Same kind of hardware I used : Intel core i5 4200H, Intel HD4600.
The HD4600 driver version I used is the latest one : 20.19.15.4531.

Strace of the failing command
Required packages and commands to install
See our contributing instructions for assistance.

**Comment by WSLUser** [comment]
Please fill out the template instead of removing it. It's there to help resolve your issue.

**Comment by ThaiLe011094** [comment]
> Please fill out the template instead of removing it. It's there to help resolve your issue.

i'm sorry, i edited the comment. please take a look

**Comment by WSLUser** [comment]
Great. I think you should collect detailed logs: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md 

> Intel driver 

Don't you mean the NVIDIA driver? Please also keep in mind older Dell systems (or other vendors for that matter) won't work well or in some cases at all with Windows 10. It may be time to upgrade your setup something more recent (and supported, which I know your NVIDIA GPU is not).

**Comment by ThaiLe011094** [comment]
> Great. I think you should collect detailed logs: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md
> 
> > Intel driver
> 
> Don't you mean the NVIDIA driver? Please also keep in mind older Dell systems (or other vendors for that matter) won't work well or in some cases at all with Windows 10. It may be time to upgrade your setup something more recent (and supported, which I know your NVIDIA GPU is not).

Hi, it's Intel driver, i got that number from Device Manager -> Display Adapters -> Intel (R) HD Graphics 4600 in Driver tab. Luckily, I fixed the issues.

Solutions: Using Dell 7447 Intel HD Graphics older driver (code: K3R4X) to fix. All Intel Graphics function works correctly now.

Thank you for your help.
