### ISSUE TITLE
False positive from MS-AV for `userdel`

### ISSUE THREAD

**Issue by angelog0** [microsoft/WSL#4798]
Here Win10 64 PRO 1909 10.0.18363.535. WSL is 

```
wsl --list --all
Distribuzioni del Sottosistema Windows per Linux:
Ubuntu (valore predefinito)
```

full updated.

The AV shiped with Win10 says:

`C:\Users\angelo\Ubuntu\rootfs\usr\sbin\userdel` is `Trojan:Win32/Softcnapp`.

Maybe we have to warn MS people... because Virustotal repotrs only MS-AV says this. See

![MS-AV-falsepos](https://user-images.githubusercontent.com/35931460/71740595-ec076d00-2e5c-11ea-8520-6932c17fdb47.png)

How can I clean this in MS-AV?

**Comment by therealkenc** [comment]
That's the second one of these recently (other being #4794). Not sure where the Windows AV peeps hang out to provide a link.

**Comment by sirredbeard** [comment]
When I can reproduce these I have been uploading them to https://www.microsoft.com/en-us/wdsi/filesubmission with pretty good success getting them cleared up.

**Comment by angelog0** [comment]
I submitted the question to the link suggested by @sirredbeard, and now it is fixed. Thanks.
