### ISSUE TITLE
WSL not properly resolving `sh.rustup.rs` or `static.rust-lang.org`

### ISSUE THREAD

**Issue by apokaliptis** [microsoft/WSL#4801]
### Your Windows build number: ###
Microsoft Windows [Version 10.0.18362.535]

### What you're doing and what's happening: ###

I'm trying to install Rust and rustup with this command:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
I get the following response:
```
info: downloading installer
curl: (6) Could not resolve host: static.rust-lang.org
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.P0N5YPdQT2/rustup-init
```

But sometimes I just get:
```
curl: (6) Could not resolve host: sh.rustup.rs
```

### What's wrong / what should be happening instead: ###

It seems that WSL is trying to use IPv6 to look up the address, but I don't have IPv6 with my ISP provider and I have it disabled in Windows.

### Strace of the failing command, if applicable: ###

I don't know if it's applicable or not, but I did [a strace][1] like this:
```
strace -o curl-rustup.strace -f curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
but that probably just gives an strace of everything before the `|`, right? So I did [a second strace][2] like this to trace the second half:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | strace -o curl-rustup.strace -f sh
```
Gists: [first half of strace][1] | [second half of strace][2]

[1]: https://gist.github.com/apokaliptis/6edc9288ae24c226244ba42de29114e4
[2]: https://gist.github.com/apokaliptis/b760e4645de97af4b799263945a2e4b8

**Comment by apokaliptis** [comment]
Also, WSL is able to resolve the address if I use the `-4` flag with curl or wget to have explicitly use IPv4 but the install script will still fail because the script doesn't explicitly use IPv4 to download the rest of the install files.

**Comment by qiluge** [comment]
ALSO.
I cannot `rustup update` or re-install rust because this problem.

**Comment by Anaga** [comment]
I had a same issue, but for me - adding a `-4`  and `-v` for verbose output, help:

```
build31@Ordi-PC:~/projects$ curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -v -4 | sh
*   Trying 18.165.122.110:443...
* TCP_NODELAY set
* Connected to sh.rustup.rs (18.165.122.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
```

**Comment by apokaliptis** [comment]
It's been a long time since I made this, but I decided to try this again in WSL2 just for kicks, and it downloaded fine.

**Comment by hanoj-budime** [comment]
on windows, using wsl.

worked for me

```cmd
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
```

**Comment by lmBored** [comment]
Im also having this problem on Alpine Linux 3.14
