### ISSUE TITLE
"explorer.exe: command not found" when user changed

### ISSUE THREAD

**Issue by iGom** [microsoft/WSL#4804]
* Windows  10.0.19536.1000

* What you're doing and what's happening: 

Login as normal user.

Change user to `root`

Then try `explorer.exe .`

* What's wrong / what should be happening instead:

expected opening of Explorer in Windows but `explorer.exe: command not found`

![image](https://user-images.githubusercontent.com/4786772/72012503-0a51dc00-3254-11ea-8929-86d0b98e0ba2.png)

**Comment by Biswa96** [comment]
Run `echo $PATH`. It should contain `/mnt/c/Windows/system32`. Did you add any config in `/etc/wsl.conf`?

**Comment by iGom** [comment]
No, I didn't add anything

root@DESKTOP-R7DVN7B:/home/roro# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by iGom** [comment]
It contains `/mnt/c/Windows/system32` but not under root

**Comment by vkecla** [comment]
That's by design Linux. If you `sudo su` you get root's path, not you roro path.

**Comment by moisesf10** [comment]
**> Isso é por design Linux. Se você `sudo su`obtiver o caminho do root, não o caminho do roro.**

I've been racking my brain for a day and nothing solved. Thanks for the answer

**Comment by sscanfer** [comment]
I ran into the same problem. when I first startup Ubuntu-18.04 in WSL and echo `PATH`, System32 was included, these commands  such as `explorer.exe .` can ran normally. But if I switch user to root, that problem just came up, echo `PATH` shows no System32

**Comment by dsampras** [comment]
As a temporary workaround, by changing the default user for wsl solves the issue. 
open PowerShell in Admin mode
`ubuntu2004.exe config --default-user <username>`

**Comment by Banerjee1996** [comment]
> As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`

No , it did not work for me

**Comment by santitomatis** [comment]
> > As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`
> 
> No , it did not work for me
> 
> (/mnt/c/Windows/explorer.exe .) use this instead of just (explorer.exe .)

This worked for me, thank you!

**Comment by bernardoadribeiro** [comment]
> As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`

It doesn't worked for me, but I tried to set the user in the command line that launch the distro:
   > Using the Windows Terminal
1. Go to config of Ubuntu terminal
2. In the section "Command line" set the command: `wsl ~ -d Ubuntu-20.04 -u <username>` or `ubuntu2004.exe -u <username>.
   > It will start the Ubuntu terminal as the specified user.
   **Note:** If you are using another version of Ubuntu, just replace the version in the command.
3. Save and start the Ubuntu terminal in another tab a see if the `explorer.exe .`  works

**Comment by jhwblender** [comment]
> > As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`
> 
> No , it did not work for me
> 
> (/mnt/c/Windows/explorer.exe .) use this instead of just (explorer.exe .)
Because this worked for me, I just added "alias explorer.exe='/mnt/c/Windows/explorer.exe'" to ~./bashrc
The normal "explorer.exe ."command worked from there.

**Comment by jhwblender** [comment]
> > As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`
> 
> No , it did not work for me
> 
> (/mnt/c/Windows/explorer.exe .) use this instead of just (explorer.exe .)

Because this worked for me, I just added "alias explorer.exe='/mnt/c/Windows/explorer.exe'" to ~./bashrc
The normal "explorer.exe ."command worked from there.

**Comment by selfdrivinglover** [comment]
> > As a temporary workaround, by changing the default user for wsl allows you to see the user files in windows. open PowerShell in Admin mode `ubuntu2004.exe config --default-user <username>`
> 
> No , it did not work for me
> 
> (/mnt/c/Windows/explorer.exe .) use this instead of just (explorer.exe .)

thanks to your method,I can use explorer.exe again.but I still want to know the reason behind it.

**Comment by morbloe** [comment]
explorer.exe . should show the current path in wsl - correct? For me it doesn't work.  Explorer starts in my documents instead.
So how do I open the explorer inside the WSL-Path? \\wsl$ does also not working. 
(10 Pro 21H2 19044.2311)

**Comment by Momo140868** [comment]
> explorer.exe . should show the current path in wsl - correct? For me it doesn't work. Explorer starts in my documents instead. So how do I open the explorer inside the WSL-Path? \wsl$ does also not working. (10 Pro 21H2 19044.2311)

alias explorer.exe='/mnt/c/Windows/explorer.exe
echo 'PATH=$PATH:/mnt/c/windows' >> ~/.bashrc

These two commands worked for me, thank you so much!
