### ISSUE TITLE
Getting syntax error when sourcing antigen (ZSHRC) on WSL Ubuntu

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/WSL#4806]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18363.535]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Using the latest version of Ubuntu downloaded from the Microsoft Store in WSL
Also using the shell `C:\\Windows\\System32\\wsl.exe`

* What's wrong / what should be happening instead:
Getting syntax error near unexpected token `fi'
Full command log is 
```
user@DESKTOP-DL1NO2L:~$ source ~/.zshrc 
-bash: /usr/libexec/java_home: No such file or directory
zmodload: command not found
autoload: command not found
-bash: /home/user/.zsh/bundle/bin/antigen.zsh: line 30: syntax error near unexpected token `fi'
-bash: /home/user/.zsh/bundle/bin/antigen.zsh: line 30: `      fi'
antigen: command not found
antigen: command not found
antigen: command not found
antigen: command not found
```
What should be happening is the command `source ~/.zshrc` should run succesfully and update the CLI bar and theme with the reloaded plugins

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
#2365 #3407 #2107 et al
