### ISSUE TITLE
Allow Running of Vagrant within WSL Entirely

### ISSUE THREAD

**Issue by davidshq** [microsoft/WSL#4807]
**Is your feature request related to a problem? Please describe.**
Right now in order to run Vagrant in WSL one needs to install Vagrant/VirtualBox on the Windows side as well. Seems like with WSL2 it might be possible to run Vagrant entirely within WSL? Not sure how performant it would be...but if it wasn't miserable, would be a nice simplification.

**Describe the solution you'd like**
Ability to run Vagrant within WSL without needing to rely on Vagrant/VirtualBox installed on Windows.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by therealkenc** [comment]
Neither Vagrant nor VirtualBox are MSFT products. There is no discernable WSL actionable here.
