### ISSUE TITLE
[WSL2] Can't connect to a web server running in linux  via Host IP

### ISSUE THREAD

**Issue by InfiniteLee** [microsoft/WSL#4808]
* Your Windows build number:  10.0.19041.1

* What you're doing and what's happening: 
In linux, start a webserver in some directory `python -m simpleHTTPServer`
In Windows, observe that navigating to `127.0.0.1:8000` or `localhost:8000` in your browser displays a generated directory listing (or an index.html file if you have one).

* What's wrong / what should be happening instead:
Also in Windows, observe that navigating to `<windows local ip address>:8000` (e.g. `192.168.1.XXX:8000`) results in a "This site can’t be reached" or "Unable to connect" page from the browser.

I need to use this local IP address so that I can connect to this web server from _other_ devices, e.g. phones & tablets. This used to work before I upgraded to WSL 2. I suspect this is related to the Hyper-V Virtual Ethernet Adapter that is now being used, but workaround attempts (found from similar issues that have been reported) including disabling Windows Firewall do not seem resolve the problem.

I have also tested this with a web server using `webpack-dev-server` explicitly configured with host `0.0.0.0` with the same results.

**Comment by InfiniteLee** [comment]
Nevermind, found the workaround here: https://github.com/microsoft/WSL/issues/4150

**Comment by ricjuanflores** [comment]
@InfiniteLee How did you do it?
