### ISSUE TITLE
Semaphores removing issue with PHP and apache user

### ISSUE THREAD

**Issue by BladeMF** [microsoft/WSL#4809]
There is an issue with containers that I have a suspicion has something to do with WSL as it doesn't happen on normal Ubuntu machine - when running as apache (www-data), when PHP removes a semaphore, a warning is produced. The other calls seem to work fine, including releasing.

_* Your Windows build number:  (Type `ver` at a Windows Command Prompt)_
Microsoft Windows [Version 10.0.18363.535]

_* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)_
```
$ su www-data
$ php -a
Interactive mode enabled

php > $s = sem_get(1234);
php > sem_acquire($s);
php > sem_remove($s);
PHP Warning:  sem_remove(): SysV semaphore 139832897032264 does not (any longer) exist in php shell code on line 1
```

_* What's wrong / what should be happening instead:_
No warning should be produced.

_* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)._
N/A

_* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)._
No launch issues.

_* Other_
```
$ php -v
PHP 7.2.25-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:42:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.25-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
```
$ apachectl -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2019-08-21T20:43:21
```

**Comment by therealkenc** [comment]
```
6921  semctl(0, 0, IPC_STAT, 0x7fffd39b4660) = -1 EACCES (Permission denied)
6921  write(2, "PHP Warning:  sem_remove(): SysV"..., 115) = 115
```

/dupe #3743
