### ISSUE TITLE
WSL2 Networking Breaks

### ISSUE THREAD

**Issue by hbjydev** [microsoft/WSL#4810]
Apologies for the vague title, I'm not sure how to go about naming this.

I'm on build 19041.1 and I'm running into numerous WSL2 network issues.

At first, it was that I couldn't access any ports on the WSL2 instance via IPv4, but I could over IPv6. Apparently this is some sort of only-one-port-at-a-time bug? Not sure where I saw it, but still. In any case, a simple `wsl --shutdown` command in PowerShell *seemed* to fix it.

Then, the issue arose that I couldn't ping outwards. At all. I tried `ping google.com`, `ping 1.1.1.1`...
`ping google.com` returned `ping: google.com: Temporary failure in name resolution`.

`ping 1.1.1.1` returned this:
```
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
From 172.29.190.109 icmp_seq=1 Destination Host Unreachable
From 172.29.190.109 icmp_seq=2 Destination Host Unreachable
From 172.29.190.109 icmp_seq=3 Destination Host Unreachable
From 172.29.190.109 icmp_seq=4 Destination Host Unreachable
From 172.29.190.109 icmp_seq=5 Destination Host Unreachable
^C
--- 1.1.1.1 ping statistics ---
6 packets transmitted, 0 received, +5 errors, 100% packet loss, time 5101ms
pipe 3
```

And I'm tearing my hair out at this point. Is this a known issue? If not, how fast can I get this fixed?

**Comment by EternalDeiwos** [comment]
Also had this and `wsl --shutdown` also fixed it for me but couldn't access anything hosted within WSL from the windows side.

**Comment by sitepodmatt** [comment]
The localhost port integration gets fixed and regresses in a stable pattern every couple of weeks (and has done for several months).  A bit like Intel's old tick tock cycle, benhillis claims on another related issue that they currently have a fix in the oven for latest round of localhost one-port-at-a-time regressions, but it hasn't been mentioned if it will be targetting the Slow or Fast ring, I suspect the latter.

**Comment by mrtumnus** [comment]
> Also had this and `wsl --shutdown` also fixed it for me but couldn't access anything hosted within WSL from the windows side.

--shutdown does not show as an option for my wsl.exe program.

I fixed the issue by deleting /etc/resolv.conf (it was empty!), closing my bash session, and re-opening it.  resolv.conf was re-generated and contained the appropriate information.

**Comment by itshaydendev** [comment]
@mrtumnus `wsl --shutdown` is the one, for sure.

**Comment by itshaydendev** [comment]
https://i.imgur.com/l5j7JZL.png

**Comment by mrtumnus** [comment]
@itshaydendev Hmm, I'm not getting the same result.  This is on Windows 10 1909.

![image](https://user-images.githubusercontent.com/1738198/78258603-7b0e3a80-74c9-11ea-8a5d-20d593b8c660.png)

**Comment by mrtumnus** [comment]
@itshaydendev Hmm, I'm not getting the same result.  This is on Windows 10 1909.

![image](https://user-images.githubusercontent.com/1738198/78258694-98430900-74c9-11ea-837e-743073512bbb.png)

**Comment by dgellow** [comment]
I'm on OS build 20211.1000, I'm also facing network issues from WSL2.

When trying to ping an IP from remote or local network, or even the IP of the Windows host, it fails with "Destination Host Unreachable".

**Comment by dgellow** [comment]
Hmm, one thing I notice is that the WSL Ethernet adapter on Windows isn't connected.

![image](https://user-images.githubusercontent.com/2451004/93254345-7fd55b00-f798-11ea-9890-a917ebb20378.png)

**Comment by hookenz** [comment]
It's flakey for me under wsl2 also.   I usually have to reboot my pc once a day to fix it.  Windows cannot reach my docker and linux apps running under WSL2 linux.
