### ISSUE TITLE
Unable to locate package...

### ISSUE THREAD

**Issue by Coder123heap** [microsoft/WSL#4811]
i ran this in ubuntu 
sudo apt install build-essential libboost-all-dev libssl-dev libcrypto++-dev libcurl4-openssl-dev
and it spit out
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libboost-all-dev
E: Unable to locate package libcrypto++-dev
E: Couldn't find any package by regex 'libcrypto++-dev'
what should i do

**Comment by sitepodmatt** [comment]
This isn't a WSL bug. Run update first 

```
sudo apt update
```

**Comment by wangqinghe95** [comment]
you also can run command of  apt-get upgrade

**Comment by MoSala7** [comment]
i tried to run 
apt-get update
then
apt-get upgrade
then
sudo apt-get install pyrit
and the same error
"E: Unable to locate package pyrit"

**Comment by therealkenc** [comment]
You didn't state your Ubuntu version, but `pyrit` [was dropped](https://packages.ubuntu.com/search?keywords=pyrit&searchon=names) from focal (20.04).

**Comment by Jota-C4rlos** [comment]
> This isn't a WSL bug. Run update first
> 
> ```
> sudo apt update
> ```

after " sudo apt-get upgrade"
