### ISSUE TITLE
WSL2: can't access linux file system from Windows Explorer 

### ISSUE THREAD

**Issue by abreingan** [microsoft/WSL#4812]
* Your Windows build number:  Version 10.0.18362.535

* What you're doing and what's happening:  
Attempt to access WSL distro from Windows Explorer by entering \\wsl$\Debian in the address bar or otherwise fails with:- 
"\\wsl$\Debian is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions.
Attempt to access invalid address."

* What's wrong / what should be happening instead: Root of Distro should be displayed 

However it can be fixed by running a commend prompt with admin privileges and entering the command wsl -t Debian 
After that the root is accessible through Window explorer. 
However it quickly reverts and the next time i try it will fail again
please note i am also running virtual machines via Hyper-V - could this have an effect?

**Comment by gottfired** [comment]
By the way, for me wsl -t Ubuntu does not fix it.

**Comment by abreingan** [comment]
Works consistently for me - all then seems to be OK for a few hours or a day, and something unknown then makes it go wrong again. The fix needs to be run with admin privileges or it doesn't work.

**Comment by rescenic** [comment]
Just set up openssh server in your default distro. 
https://github.com/rescenic/autossh
It will maintain connectivity from Linux to Windows (Explorer).

**Comment by michael-imbeault** [comment]
Same here with Ubuntu, fix doesn't work
