### ISSUE TITLE
Can not start the SSHD on openSUSE 15.1 WSL

### ISSUE THREAD

**Issue by m1xed0s** [microsoft/WSL#4815]
Fairly new to the WSL.

Windows 10 Pro 1909 build 18363.535.

Installed opensuse leap 15.1 from windows store today and trying to start SSH server on the opensuse WSL so I do not have to use CMD as the console...But run into errors below:
`user@LAPTOP:~$` sudo systemctl start sshd
[sudo] password for root:
Failed to connect to bus: No such file or directory
user@LAPTOP:~$ sudo /etc/init.d/dbus start
sudo: /etc/init.d/dbus: command not found
user@LAPTOP:~$ 
user@LAPTOP:~$ 
user@LAPTOP:~$ sudo mkdir -p /run/dbus
user@LAPTOP:~$ sudo dbus-daemon --system
user@LAPTOP:~$ 
user@LAPTOP:~$ 
user@LAPTOP:~$ sudo systemctl start sshd
Failed to start sshd.service: Launch helper exited with unknown return code 1
See system logs and 'systemctl status sshd.service' for details.
user@LAPTOP:~$ sudo systemctl status sshd.service
Failed to get properties: Launch helper exited with unknown return code 1
user@LAPTOP:~$ `

Tried to search for /var/log/messages but no such file...

**Comment by therealkenc** [comment]
/dupe #1579 et al LZ #994. You want `sudo service ssh start`.

**Comment by rescenic** [comment]
Use sudo /usr/sbin/sshd

**Comment by anlexN** [comment]
i also have this issue, so how to solve? i can not understand your dup issue.

**Comment by ErSoul** [comment]
I don't get it. How is this solved? Which is the duplicated thread (open)?

I'm on openSUSE 15.2

**Comment by rescenic** [comment]
Unless you are using Windows Insider Dev Channel Build 21286 or newer (you can specify command launch at boot: https://docs.microsoft.com/en-us/windows/wsl/release-notes); 
Here is a little guide for sshd to run after signing in to Windows:
https://github.com/rescenic/autossh
