### ISSUE TITLE
hardlink handling broken

### ISSUE THREAD

**Issue by lnussel** [microsoft/WSL#4816]
* Windows build number: 10.0.19041.21

* What you're doing and what's happening: 
```
#!/bin/bash
rm -rf /var/tmp/d{1,2,3}
mkdir /var/tmp/d{1,2,3}
echo "create file in d1"
echo hello > /var/tmp/d1/somefile
ls /var/tmp/d{1,2,3}
echo "link file from d1 to d2"
ln /var/tmp/d1/somefile /var/tmp/d2/somefile
ls /var/tmp/d{1,2,3}
echo "remove d1"
rm -r /var/tmp/d1
ls /var/tmp/d{1,2,3}
echo "link from d2 to d3"
ln /var/tmp/d2/somefile /var/tmp/d3/somefile
ls /var/tmp/d{2,3}
```

The last `ln` call results in an "permission denied" error even though the code is correct and will work on a real Linux.
Looks like the removal of the original directory (d1) triggers this behavior.

The package manager (zypp) in openSUSE relies on the hardlink semantic to work.

**Comment by therealkenc** [comment]
/dupe #1529. You're particular scenario (on `/var/tmp`) is addressed in [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/). _Expected_ output from this script below.

![image](https://user-images.githubusercontent.com/7049700/72558850-63270300-3858-11ea-9362-e2d155603a1a.png)
