### ISSUE TITLE
Can't enable WSL2

### ISSUE THREAD

**Issue by creativiii** [microsoft/WSL#4817]
* Your Windows build number: Microsoft Windows [Version 10.0.19041.1]

* What you're doing and what's happening:  
## Enable WSL
```
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Image Version: 10.0.19041.1

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
```

## Enable Virtual Machine
```
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Image Version: 10.0.19041.1

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
```

## Set default version
```
PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```

## Check WSL version
```
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu          Stopped         1
  Ubuntu-16.04    Stopped         1
```

* What's wrong / what should be happening instead: "VERSION" should be set to "2"

WSL 1 is working just fine, I just can't seem to enable WSL2. Any idea what's happening? Is it because I'm trying to enable WSL2 on pre-existing installations of Ubuntu? Should I be starting fresh?

**Comment by therealkenc** [comment]
You set the _default_ version. That doesn't affect your existing distro installs, which are version 1. You want `wsl.exe --set-version Ubuntu-16.04 2`. Or, perhaps better if you're just getting started with your disros anyway, delete them. When you install the next time it will be version 2. Because... now you've set the default to 2.

**Comment by creativiii** [comment]
I tried setting the specific distro, it also didn't work.

**Comment by SNvMK** [comment]
I have that problem too. Let's reopen this issue

**Comment by therealkenc** [comment]
Discussion topic at #6505
