### ISSUE TITLE
Can't use X-Server in WSL 2 (continued)

### ISSUE THREAD

**Issue by numeric-lee** [microsoft/WSL#4820]
Ben,
I was able to use graphic applications in WSL using XMING and  Export DISPLAY=:0.0

However, once I upgraded to  WSL2 (needed for docker)  the graphic export stopped working.

Things tried: 
* downloading VcXsrv  
* changing to export DISPLAY=172.28.80.1:0    (my host#)
* switching to another graphics application
* running vcxsrv -ac from bash (command not recognized)
* running vcxsrv -ac from powershell (command not recognized)
* turning firewall off

My Windows 10 build: 19041.1

Here is a typical error message 

> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-lw'    qt.qpa.screen: QXcbConnection: 
> Could not connect to display :0.0                           
> Could not connect to any X display.   

if my display path is anything other than 0.0 I also get

> Authorization required, but no authorization protocol specified

In https://github.com/microsoft/WSL/issues/4106  you advise to run "vcxsrv -ac" from the bash command line and at least one user accepted that as a solution. I downloaded vcxsrv.exe from sourceforge as an .exe outside of bash, and I see no way to execute it from bash

Many thanks

**Comment by therealkenc** [comment]
> Could not connect to display :0.0

Your display is not on `:0.0`. 

/dupe #637 ([message](https://github.com/Microsoft/WSL/issues/637#issuecomment-392989799)), #4106 ([message](https://github.com/microsoft/WSL/issues/4106#issuecomment-501885675)), #4210 ([message](https://github.com/microsoft/WSL/issues/4210#issuecomment-528079189)), LZ #4619.

**Comment by winest** [comment]
[Script to solve this problem](https://github.com/microsoft/WSL/issues/4793#issuecomment-588321333)

**Comment by snowman** [comment]
https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999

**Comment by snowman** [comment]
see [Unable to accessing Windows applications from WSL](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999)
