### ISSUE TITLE
wsl2 export requires available RAM larger than filesystem to finish

### ISSUE THREAD

**Issue by lzchgy** [microsoft/WSL#4822]
* Your Windows build number:  [Version 10.0.19041.21]

* What you're doing and what's happening:  I issued `wsl --export distro c:\wsl\distro.tar.gz` in powershell and got an `Insufficient system resources exist to complete the requested service` error. 

* What's wrong / what should be happening instead: The wsl2 filesystem I was trying to export is larger than the physical RAM my PC had. It couldn't finish exporting. It should be able to export without requiring available RAM as large as the whole root filesystem.

**Comment by therealkenc** [comment]
Ref #4530 on the chance there's something to the "large tar" thesis.

**Comment by jefferai** [comment]
Just hit this -- why is it tar'ing into memory instead of directly to the output file? As it stands I appear to have no way to export my wsl distro.

**Comment by craigloewen-msft** [comment]
I'd recommend trying the newest Insiders Fast version (Build 19564) which should fix this issue for you!
