### ISSUE TITLE
[WSL2] Folder created with dots in Ubuntu creates an unhealthy Windows folder

### ISSUE THREAD

**Issue by cboudereau** [microsoft/WSL#4823]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.19030.1]
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

in Ubuntu distro, wsl 2
```
cd /mnt/c/
mkdir hello...
```

* What's wrong / what should be happening instead:
The folder is ok in Ubuntu side but in windows, when deleting or using the folder an error message is displayed with the message : 
"Could no find this item. This is no longer located in C:\"

I also tested with those commands without the same error
```
mkdir "hello..."
mkdir "hello\..."
mkdir hello\...
```
The same commands without dots works well.

The workaround is to use `rd /s /q` on the folder hello.... to remove it.

Instead, expected a healthy folder.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
https://superuser.com/questions/494959/how-to-delete-a-file-ending-in-a-dot-in-windows-7

**Comment by cboudereau** [comment]
I know this problem but I was really surprised to see that the mounting point could break on windows.

Honestly, it reduces the usage of docker with linux container and I am sure that you will have to manage this kind of problems later.

Thank you for your quick feedback and and have a good weekend
