### ISSUE TITLE
RSync over SSH hangs until I resize the window

### ISSUE THREAD

**Issue by BarbeRouss** [microsoft/WSL#4824]
* Your Windows build number:  Microsoft Windows [version 10.0.18363.592]

* What you're doing and what's happening: I'm using rsync over SSH to create a backup of folder containing some picture and videos.

```
#!/bin/bash

echo "Sending files to NAS"
sshpass -p "[MYPASSWORD]" rsync --itemize-changes -a -c --compress --human-readable --delete --progress -e '*.db' '/mnt/c/Users/Julien/OneDrive/Images/Photos/Perso/' '[USERNAME]@[IP_ADDRESS]:/volume1/Photo/Perso'
```

* What's wrong / what should be happening instead: After a few files (Or one big file if I'm synchronizing another directory), the rsync hang like this:
![image](https://user-images.githubusercontent.com/24474067/72687746-3ba69380-3b01-11ea-9be1-773e38ac06f7.png)
Weird thing is that if I resize the window, then the process got unstuck for that file. Then got stuck again at the next file. Again, if I resize the window, I can sync the next file.

I created a Ubuntu VM in Hyper-V, mounted the directory to backup, and run the same command (Just with a different directory), and the command is working fine.
I also tested with a different backup location, and the issue is the same.
That's why I'm confident the issue is coming from WSL.

Obviously, I expect the entire folder to be synchronized without manual intervention on the window.

* Strace of the failing command, if applicable:  Strace available here: https://gist.github.com/BarbeRouss/69b1e09f05f866a3c002808fee2cd027

NOTE: When running the command from strace, the script instantly crash, outputing this in the terminal: 
```
julien@Julien-PC:/mnt/c/Users/Julien/OneDrive/Documents/Autre/RSync/Shell$ strace -o command.strace -f ./Sync\ -\ NAS\ -\ Photo\ Perso.sh
Sending files to NAS
rsync: Failed to exec *.db: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at io.c(235) [sender=3.1.2]````

**Comment by therealkenc** [comment]
/dupe #2138. Manifests in some other scenarios too.

**Comment by nathanpust** [comment]
I encountered this issue today after upgrading a system to Windows 11. What I didn't realize was that the previously installed WSL installation was WSL1 which has the bug mentioned above. After converting to WSL2, the issue went away. Apparently, this was a bug in WSL1 that was never resolved.

If you encounter this, first check whether you are using WSL1. If so, convert to WSL2 if that is an acceptable option for you.
