### ISSUE TITLE
/proc/meminfo format is incorrect

### ISSUE THREAD

**Issue by kabachook** [microsoft/WSL#4829]
* Windows build number: `Microsoft Windows [Version 10.0.18362.592]`

* What you're doing and what's happening:  

Reading from `/proc/meminfo` sometimes giving values in incorrect format, which breaks some programs. 

For example, python's psutil throwing error because of incorrect line format: `ValueError: invalid literal for int() with base 10: b'kB'`

* What's wrong / what should be happening instead:

Expected behavior: 
```bash
$ cat /proc/meminfo | grep SwapFree
SwapFree:              0 kB
```

Real behavior:
```bash
$ cat /proc/meminfo | grep SwapFree
SwapFree:18014396678257232 kB
```

There is no `\t` after semicolon. It occurs every 4th time I run the command

Also, related to this [comment](https://github.com/microsoft/WSL/issues/296#issuecomment-574932937)

**Comment by therealkenc** [comment]
Another data point: are you by chance on the hairy edge of running out of memory (as reported by Resource Monitor or similar).

**Comment by kabachook** [comment]
@therealkenc Yep, that's right. It's just `0`. But I have swap disabled.

It goes something like this:

```bash
$ cat /proc/meminfo | grep SwapFree                                                     
SwapFree:              0 kB
$ cat /proc/meminfo | grep SwapFree
SwapFree:              0 kB
$ cat /proc/meminfo | grep SwapFree
SwapFree:18014381513828768 kB
$ cat /proc/meminfo | grep SwapFree
SwapFree:              0 kB
$ cat /proc/meminfo | grep SwapFree
SwapFree:              0 kB
$ cat /proc/meminfo | grep SwapFree
SwapFree:              0 kB
```

About free memory: nope, I have at least 2 Gb free.

**Comment by kabachook** [comment]
Wow, htop output
![image](https://user-images.githubusercontent.com/9118683/72722955-a81ca380-3b90-11ea-8c47-70cac609ae3e.png)

**Comment by therealkenc** [comment]
> But I have swap disabled in Windows.

Thanks for the follow up. WAG give yourself some trivial amount swap, reboot, and see if that helps.

**Comment by kabachook** [comment]
Thanks, that worked! Apparently, there may be bug, when swap is not enabled 😄

**Comment by therealkenc** [comment]
> there may be bug, when swap is not enabled

Almost certainly.

> It goes something like this:

Because curious now and because it might help: Does it fail every four reads like clockwork, or "somelike like every four reads (on average)"?

**Comment by kabachook** [comment]
Sorry for not explaining, the latter. Every four on average.
