### ISSUE TITLE
Road Map for WSL2?

### ISSUE THREAD

**Issue by argoneus** [microsoft/WSL#4831]
Is there a road map for WSL2?  When is it anticipated to hit GA?

**Comment by therealkenc** [comment]
20H1, H1 being historically April or May.

**Comment by nick4fake** [comment]
@therealkenc I think original question still makes sense: is there any kind of roadmap?

**Comment by Biswa96** [comment]
If there is any it will be internal to Microsoft.

**Comment by therealkenc** [comment]
WSL2 was released in 20H1 (aka 19041) Spring of 2020 and subsequently [backported](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/) to 1903 and 1909.
