### ISSUE TITLE
Ugly icon in full hd display

### ISSUE THREAD

**Issue by francescoboc** [microsoft/WSL#4832]
So, I just bought a new laptop, with a full hd display, and now the WSL icon looks different than in my old (not full hd) laptop.

* Your Windows build number:  10.0.18363.592

* What you're doing and what's happening:  
Pinning Ubuntu to taskbar (with the option "Use small taskbar buttons" on) results in a tiny, white, ugly icon:
![image](https://user-images.githubusercontent.com/33369475/72751606-5855d080-3bc0-11ea-8888-f364b225a11a.png)

* What's wrong / what should be happening instead: 
I would expect just a smaller version of this icon:
![image](https://user-images.githubusercontent.com/33369475/72751687-8e935000-3bc0-11ea-9201-d0f8674c8609.png)

I know it's not the end of the world, but it's just kind of annoying! And thanks for the incredible work you are doing on WSL!

**Comment by sirredbeard** [comment]
This is a known issue we are tracking over at Ubuntu. https://bugs.launchpad.net/ubuntuwsl/+bug/1857851
