### ISSUE TITLE
mkdir: cannot create directory ‘a’: Permission denied 

### ISSUE THREAD

**Issue by xzn** [microsoft/WSL#4836]
Cannot create directory with `mkdir` even though `touch`, `rm`, `rmdir`, `mv` all works fine.

Microsoft Windows [Version 10.0.19546.1000]

Arch Linux distro created with
`wsl --export Arch D:\arch.tar`
`wsl --import Arch2 D:\WSL\Arch2 D:\arch.tar --version 2`

`cd /mnt/d/`
`mkdir a`
gives
`mkdir: cannot create directory ‘a’: Permission denied `

Works fine at home directory though
`cd /mnt/c/Users/user`
`mkdir a`
no problem here...

Where should I start to look for a solution for this?

**Comment by sirredbeard** [comment]
Can you reproduce this when using C:\ instead?

**Comment by xzn** [comment]
Same at `/mnt/c`

**Comment by sirredbeard** [comment]
Where did you get your Arch image?

I have tried the one at https://github.com/yuk7/ArchWSL/releases and except for some issues with permissions on the package GPG signatures it worked well for me.

**Comment by xzn** [comment]
I installed it using a guide from here https://github.com/DDoSolitary/LxRunOffline/wiki

WSL works fine, exporting it to WSL2 and I have trouble with `mkdir`.

Will try your link for now.

**Comment by sirredbeard** [comment]
Give the other Arch image a try, I know it's a good image.

What are the permissions in the folder what you are trying to create a folder?

Have you tried chown?

**Comment by xzn** [comment]
chown, chmod all works alongside touch, rm, rmdir, mv, etc. I just noticed mkdir wouldn't work when git clone gives me permission denied.

Thanks for helping btw! Will try a clean image instead of exporting from one I currently have.

**Comment by anas-mohammed** [comment]
I have the same issue, I am trying to create a directory so that I can mount the drive

**Comment by WMLHUST** [comment]
**I delete a git dict in windows explorer**, then mkdir failed in WSL terminal.

**Comment by kudaba** [comment]
I just upgraded to ubuntu version 2 and I'm getting the same issue. I can't mkdir on my drives in /mnt/c and /mnt/d, but it works fine in my home folder and other areas. All other operations work fine. Even running with sudo doesn't help. My app that I'm working on also can't create folders.

**Comment by kudaba** [comment]
In my case it was a mount issue, or at least changing the mount options fixed it. Running the following command from https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/ worked for me:

``sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata``

It's unclear but the command seems to be permanent. I'm not sure what happened during the upgrade from WSL 1 to 2 that affected this.

**Comment by stu85010** [comment]
Hello there,

In my case, this issue was solved by: giving the **Full control** permission to your Windows account for this directory with **Security** tab
![image](https://user-images.githubusercontent.com/5828325/96130098-0c0aa780-0f2a-11eb-8368-ab8de5815d35.png)

Said, I'd created a directory at `/c/src` and trying to develop there, but the "User" group doesn't have *Full control* permission at that path, so the folder creation is failed in WSL in my case.

Then I was added the **Full control** permission to my Windows account at that folder, and the `mkdir` worked perfectly in that directory.

**Comment by kudaba** [comment]
Turns out my mount solution didn't last through a reboot, but the Full Control to users fixed it, thanks @stu85010.

**Comment by alvinseville7cf** [comment]
I have the same issue except that sudo helps me to create some folder in /mnt/c. I use Ubuntu 20.04.2 LTS. Is this normal?

**Comment by kingmathers92** [comment]
You have launch Git Bash as an administrator. Simple as that, it helped me.

**Comment by shatanikmahanty** [comment]
try command `sudo chown -R "yourusername" .`
replace "yourusername" with the name of the user

**Comment by hariadiarief** [comment]
> try command `sudo chown -R "yourusername" .` replace "yourusername" with the name of the user

you save my live bro 😊😊😊

**Comment by QuyetVV2** [comment]
> try command `sudo chown -R "yourusername" .` replace "yourusername" with the name of the user

you saved my day 😊 thanks!

**Comment by SunSummoner** [comment]
> In my case it was a mount issue, or at least changing the mount options fixed it. Running the following command from https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/ worked for me:
> 
> `sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata`
> 
> It's unclear but the command seems to be permanent. I'm not sure what happened during the upgrade from WSL 1 to 2 that affected this.

![image](https://user-images.githubusercontent.com/95202116/227716251-06f24f44-3b12-4937-82d5-99027574c4ed.png)
This is the error I am getting while trying to run a few jupyter notebooks. Will this command help with this issue?

**Comment by harshalgunjal69** [comment]
> try command `sudo chown -R "yourusername" .` replace "yourusername" with the name of the user

Thanks for this brooo

**Comment by cookernetes** [comment]
> try command `sudo chown -R "yourusername" .` replace "yourusername" with the name of the user

Worked amazingly for me!

**Comment by cookernetes** [comment]
> > In my case it was a mount issue, or at least changing the mount options fixed it. Running the following command from https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/ worked for me:
> > `sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata`
> > It's unclear but the command seems to be permanent. I'm not sure what happened during the upgrade from WSL 1 to 2 that affected this.
> 
> ![image](https://user-images.githubusercontent.com/95202116/227716251-06f24f44-3b12-4937-82d5-99027574c4ed.png) This is the error I am getting while trying to run a few jupyter notebooks. Will this command help with this issue?

That looks less like a linux/system issue, and more like a Python issue for me...?
