### ISSUE TITLE
Unable to find EULA (End User License Agreement) for WSL

### ISSUE THREAD

**Issue by NitinShuklaML** [microsoft/WSL#4837]
Hi,

I am developing a docker based bash utility for a major corporation i am currently working in. My employer has a fetish for using Windows ecosystem for developing solutions and has placed stringent restrictions on anything that is not Microsoft. Thus i resorted to using WSL. However to get **WSL** approved i need to show them a **EULA** which would absolve them of any future liabilities. 

Since i cannot find **EULA** for **WSL**. Can you guys point me in a direction that would help with this issue? A formal endorsement of anybody from Microsoft that **MS Store** bought **Ubuntu 18.04 LTS** would not require a special **EULA** for WSL usage but **EULA** for **Ubuntu 18.04 LTS** would be fine?

Regards,
Nitin

**Comment by daniel-fudge** [comment]
I'm in the exact same situation and it's a none starter for me, and many others, if the EULA isn't well defined.

**Comment by craigloewen-msft** [comment]
For legal advice regarding licenses of any kind please refer to your company's legal council. 
 
WSL is part of Windows and covered by the Microsoft Windows EULA (just like any other Windows component). Products from the Microsoft store (like WSL distros) are governed by the licenses of those respective products.
