### ISSUE TITLE
Switching to WSL 2 fails with The request is not supported.

### ISSUE THREAD

**Issue by K2AAE** [microsoft/WSL#4840]
C:>ver  Microsoft Windows [Version 10.0.19546.1000]

I had installed WSL 1 with Ubuntu-18.04 then I joined insiders and it finished installing this morning. I surfed around for a while to find how to get WSL 2 running and found a command line from PS:

PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart 

It finished and I restarted.
From an Admin command prompt I tried:
wsl --set-version Ubuntu-18.04 2 
and got the 'Request is not supported' message.

I tried: 
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux            

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1

PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The request is not supported.

**Comment by K2AAE** [comment]
I removed all WSL installations of linux, rebooted and tried to install Ubuntu-18.04 and all I get is:
Installing, this may take a few minutes...
WslRegisterDistribution failed with Error: 0x80070032
Error: 0x80070032 The request is not supported.

Thank you Microsoft

**Comment by K2AAE** [comment]
Its been a long day, discovered the online ENGLISH WSL documentation, it mentioned virtual machine, I turned it on and installed another Ubuntu-18.04 and this one worked. It was version 2 but when I compiled the code that took three minutes to compile and link with WSL 1 with WSL 2 it now took 30~45. 
RIP WSL 2.

**Comment by lukepuplett** [comment]
I ran into this error after installing Windows 10 v2004 build 19041.21 in order to get WSL2. I then tried to update the version of my original Ubuntu WSL1 distro which failed with the error below.

I unregistered Ubuntu and reinstalled Ubuntu 18.04 LTS from the Windows Store. This took a little while to install but seemed to work. Then, trying to change it to WSL2 it failed again.

```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The request is not supported.
```

**Comment by lukepuplett** [comment]
I solved this by ensuring that **Virtual Machine Platform** was installed/ticked in Turn Windows features on or off.

**Comment by brucedkyle** [comment]
Hopefully this is a related issues. In my case, I am trying to install Ubuntu-20.04 and set the version in WSL 2 to that version.

```
PS C:\Users\bruce> wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu-16.04           Stopped         1
  Ubuntu-18.04           Stopped         1
  Ubuntu-20.04           Stopped         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
PS C:\Users\bruce> wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.
PS C:\Users\bruce> wsl
bruce@LAPTOP-2F5D148E:/c/Users/bruce$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

But Ubuntu tells me I am running the previous version.
Rebooting the Virtual Machine Platform did not fix this issue.
Perhaps I am missing something?

**Comment by vivi168** [comment]
> I solved this by ensuring that Virtual Machine Platform was installed/ticked in Turn Windows features on or off.

I also had to enable *Hyper-V* and *Hypervisor Plateform* in *Turn windows feature on/off*, after rebooting it finally worked.

**Comment by rennu** [comment]
@brucedkyle Your default distributions seems to be 16.04 (asterisk on the left side). Try running wsl with `-d Ubuntu-20.04` argument.

**Comment by vwal** [comment]
Sadly, it seems when the Virtual Machine Platform is enabled, VMware Workstation guests no longer start. Apparently WSL2 and VMWare Workstation cannot coexist on the same host.

**Comment by brandinarsenault** [comment]
I can confirm that if you remove VMWare Workstation the issue with converting the version in WSL goes away.

**Comment by zacwang89** [comment]
Hi @brucedkyle, how did you resolve your problem?

**Comment by sinapis** [comment]
I installed Nox Player and LdPlayer. I guess one (or both) disabled windows features that prevented WSL from working.
In order to bring WSL back online, I had to enable these two:
![image](https://user-images.githubusercontent.com/15230040/109664329-b13eb900-7b75-11eb-9efe-2b4f6a7a5282.png)

And then I had to restart the machine.

**Comment by Adarsh1999** [comment]
> I installed Nox Player and LdPlayer. I guess one (or both) disabled windows features that prevented WSL from working.
> In order to bring WSL back online, I had to enable these two:
> ![image](https://user-images.githubusercontent.com/15230040/109664329-b13eb900-7b75-11eb-9efe-2b4f6a7a5282.png)
> 
> And then I had to restart the machine.

Thanks man actually I had also installed nox and this problem came and I was worried so thanks a lot it helped me a lot

**Comment by carsonpowers** [comment]
> PS C:\Users\bruce> wsl --set-version Ubuntu-20.04 2
> The distribution is already the requested version.
> Perhaps I am missing something?

wsl --setdefault Ubuntu-20.04 2 instead

**Comment by jonathanbrunath-tc** [comment]
> 
> 
> > I solved this by ensuring that Virtual Machine Platform was installed/ticked in Turn Windows features on or off.
> 
> I also had to enable _Hyper-V_ and _Hypervisor Plateform_ in _Turn windows feature on/off_, after rebooting it finally worked.

This solution finally seems to have fixed my issue after ages trying to figure out what was wrong. My issue was with WSL2, Ubuntu 20.04.1 LTS, and Cisco Anyconnect

**Comment by jerviscui** [comment]
Have same question!

**Resolved:**

> > I solved this by ensuring that Virtual Machine Platform was installed/ticked in Turn Windows features on or off.
> 
> I also had to enable _Hyper-V_ and _Hypervisor Plateform_ in _Turn windows feature on/off_, after rebooting it finally worked.

**Comment by jerviscui** [comment]
Can you use `wsl` startup it?
My question is can't startup wsl.

Your problem is upgrade wsl to wsl2.
Must install VirtualMachinePlatform, and restart system:

```
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

Perhaps you can search 0x80041002.

**Comment by ELCBOLPL** [comment]
> 

I have the same issue

**Comment by Chris-Loughnane** [comment]
> > PS C:\Users\bruce> wsl --set-version Ubuntu-20.04 2
> > The distribution is already the requested version.
> > Perhaps I am missing something?
> 
> try `wsl --setdefault Ubuntu-20.04 2` instead

@carsonpowers Thanks mate, nothing else on this thread worked until I found your post.

**Comment by ericknkunda** [comment]
I faced the same issue too and I was about to give up. But as mentioned above, there some windows features that must be enabled for anyone wishing to upgrade to wsl 2. Here are these features
Note that you must be running at least windows 10.
1: Open settings->App->Optional features-> more windows features
2: On the opened window 
=>tick/check containers(if you may need to use docker in Linux containers mode)
=>tick/check Hper_V
=> tick /check virtual machine platform
=> tick/check Windows Hypervisor platform
=>tick/check Windows Subsystems for Linux (WSL)
After making sure that all the above are checked, hit enter and wait a little bit. Now the problem is solved. Go on and enjoy using Linux on your windows device
