### ISSUE TITLE
Neofetch crashing

### ISSUE THREAD

**Issue by cat768** [microsoft/WSL#4843]
Windows version number: 10.0.18363.5982
WSL: Ubuntu 18.04

I'm trying to run Neofetch to display my linux distro in ascii art. 
I install neofetch using sudo apt install neofetch, and then type sudo neofetch. It should have shown the linux distro as such:
![image](https://user-images.githubusercontent.com/15359961/72972964-42186200-3dc4-11ea-93c6-e3767c20c9b5.png)

However, sometimes it fails to display the logo, and always crashes in less than a second

**Comment by Joe-Pena** [comment]
Did you happen to install zsh by any chance? or are you still using bash?

I had the same issue, and just had to edit some configurations for neofetch for it to work. However, it didn't solve the underlying issue, I'll look at my config and circle back.

**Comment by cat768** [comment]
I was originally using bash, but I've installed zsh but the same issue happens.  Is there some way for me to upload my config?

**Comment by onomatopellan** [comment]
There is a known bug that crashes the terminal when using neofetch. For more info you can follow this thread until they fix it:
https://github.com/microsoft/terminal/issues/4254

**Comment by therealkenc** [comment]
Thanks @onomatopellan. Didn't see that answer coming. [I wasn't able to repro here; neogetch works inexplicably.]
