### ISSUE TITLE
DNS not working in WSL2, resolv.conf gets overwritten with symlink to ../run/resolvconf/resolv.conf

### ISSUE THREAD

**Issue by xzn** [microsoft/WSL#4844]
DNS not working at all in WSL2 after upgrading,

After setting
```
[network]
generateResolvConf = false
```
in `wsl.conf`

`resolv.conf` keeps getting overwritten with symlink to `../run/resolvconf/resolv.conf`

**Comment by xzn** [comment]
Seems like a configuration issue on my end.

Now it's just #4285.

**Comment by foobarbecue** [comment]
I'm having this same issue...

**Comment by jgangso** [comment]
I faced the same issue that resolv.conf kept getting generated despite `generateResolvConf = false:`

I learned from https://github.com/microsoft/WSL/issues/5420#issuecomment-646479747 the proper way to get rid of the generated symlinked file.
Basically what I was missing was the last command `sudo chattr +i /etc/resolv.conf`

My one-liner after which the resolv.conf started working as expected: (also after WSL2 shutdown)
`sudo rm /etc/resolv.conf && sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' && sudo chattr +i /etc/resolv.conf`

**Comment by piyush1104** [comment]
> I faced the same issue that resolv.conf kept getting generated despite `generateResolvConf = false:`
> 
> I learned from [#5420 (comment)](https://github.com/microsoft/WSL/issues/5420#issuecomment-646479747) the proper way to get rid of the generated symlinked file.
> Basically what I was missing was the last command `sudo chattr +i /etc/resolv.conf`
> 
> My one-liner after which the resolv.conf started working as expected: (also after WSL2 shutdown)
> `sudo rm /etc/resolv.conf && sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' && sudo chattr +i /etc/resolv.conf`

Thanks this worked for me.
