### ISSUE TITLE
ping not falling back to ipv4 when ipv6 is not enabled  on the windows network adapter

### ISSUE THREAD

**Issue by elonderin** [microsoft/WSL#4848]
* Your Windows build number:   Microsoft Windows [Version 10.0.18363.592]

### What you're doing and what's happening:  

i was testing if my internet was up again after a router restart, from WSL as i happened to be open:
````
tom@crack:~$ ping google.de
PING google.de(fra16s45-in-x03.1e100.net (2a00:1450:4001:800::2003)) 56 data bytes
^C
--- google.de ping statistics ---
87 packets transmitted, 0 received, 100% packet loss, time 1000ms
````

After waiting for a long time to be up, i got suspicious and and tested it (in git bash) on windows:
````
$ ping google.de

Pinging google.de [172.217.23.99] with 32 bytes of data:
Reply from 172.217.23.99: bytes=32 time=32ms TTL=56
````

* then i noticed that in WSL it was an ipv6 address so i remembered that i had turned off ipv6 on my machine for reasons which are off topic
* after turning it back on it worked:

````
PING google.de(fra16s45-in-x03.1e100.net (2a00:1450:4001:800::2003)) 56 data bytes
64 bytes from fra16s45-in-x03.1e100.net (2a00:1450:4001:800::2003): icmp_seq=1 ttl=56 time=28.8 ms
64 bytes from fra16s45-in-x03.1e100.net (2a00:1450:4001:800::2003): icmp_seq=2 ttl=56 time=28.3 ms
64 bytes from fra16s45-in-x03.1e100.net (2a00:1450:4001:800::2003): icmp_seq=3 ttl=56 time=28.8 ms
````

### What's wrong / what should be happening instead:

I would have expected that the WSL picks up the adapter change just as it works on windows where `ping` falls back to ip4.

But maybe that expectation is too much: after all, WSL is like living in a VM and i guess (to be tested) that when i use a normal VM that uses the host's adapter it's the same picture.

My guess is that other network utils are affected by this as well and it begs the question how to deal with such issues (windows hardware configs vs. perceived in WSL ) as well on how to give proper feedback to users.

**Comment by therealkenc** [comment]
> I would have expected that the WSL picks up the adapter change

WSL has no `systemd-networkd` and no `systemd-resolvd` equivalent. [This is root cause "my VPN doesn't work" for analogous reasons.]

If you disable your ipv6 again in Windows, do a `wsl.exe --shutdown`, re-enter WSL, and then `ping google.de`, I presume it pings ipv4 (f.e. `172.217.23.99`). Is that about right? After the restart with ipv6 disabled, the hostname `google.de` should resolve to a ipv4 address in WSL (contrast ipv6 f.e. `2a00:1450:4001:800::2003`).

**Comment by elonderin** [comment]
I dont have a `wsl.exe --shutdown` option, but i have a `--terminate` ...

BTW: i'm not running WSL2 if that was what u were thinking?

Nevertheless, I dont think that it would make a difference, b/c the adapter had been ip4 only for quite some time (months) and ofc. i had rebooted it since many a times.

**Comment by therealkenc** [comment]
> BTW: i'm not running WSL2 if that was what u were thinking?

I can't remember when `--shutdown` was introduced. It isn't unique to WSL 2, but it was introduced after `18363` if you don't have it. Safest equivalent would be a Windows reboot.

> Nevertheless, I dont think that it would make a difference, b/c the adapter had been ip4-only for quite some time

Understood. But then are we working on the premise that `$ ping google.de` hasn't worked "for months"? If so, that's okay. Fair game submission: "ping not falling back to ipv4 when ipv6 is not enabled on the windows network adapter" (full stop). It was the "I would have expected that the WSL picks up the adapter **change**" (also in the OP, with emphasis on "change") that was being explained, not the fail.

There's a simple work-around (don't turn off ipv6) and I'm sure you (and most everyone) can live with that. Appreciate the submission; valuable feedback. Legit even if there is a work-around.
