### ISSUE TITLE
$PATH in WSL

### ISSUE THREAD

**Issue by ff00** [microsoft/WSL#4850]
$PATH imported from host Windows to WSL's Ubuntu including spaces (C:/Program Files/" which makes a problem. any command fails

$  export $PATH=.
bash: export: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program': not a valid identifier
bash: export: `Files/WindowsApps/CanonicalGroupLimited.Ubuntu16.04onWindows_1604.2019.523.0_x64__79rhkp1fndgsc:/mnt/d/Python27/:/mnt/d/Python27/Scripts:/mnt/c/Perl64/site/bin:/mnt/c/Perl64/bin:/mnt/c/Program': not a valid identifier

IMHO every record in PATH should be enclosed in "..."

**Comment by therealkenc** [comment]
> `$ export $PATH=.`

You just expanded `$PATH` with an equal sign and a dot, and tried to export that. If there were no spaces you'd be assigning an invalid identifier starting with a `/`.

You want probably want:

```
$ export PATH=.
```

> IMHO every record in PATH should be enclosed in "..."

`$PATH` expansion doesn't work like that.....
