### ISSUE TITLE
Disabling WSL feature does not remove wsl.exe

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [microsoft/WSL#4854]
**Please fill out the below information:**
* Your Windows build number:  10.0.18362.592

* What you're doing and what's happening:  When I disable the WSL feature from Control Panel and reboot, the file at ``C:\WINDOWS\system32\wsl.exe`` does not get removed.

* What's wrong / what should be happening instead: The file should be removed.

**Comment by ShadowEO** [comment]
If I'm not mistaken, the file is there now even if WSL is NOT enabled, and is left as a form of feature discovery.

Really though, it's a small UX application, not a huge deal if they leave it while the feature is disabled as long as it simply states that it needs the feature enabled to do any work.
