### ISSUE TITLE
Problem scripting gdb under wsl2

### ISSUE THREAD

**Issue by Kalamatee** [microsoft/WSL#4856]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

19551

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

We use the following gdbinit script to debug our code  https://github.com/aros-development-team/AROS/blob/master/_gdbinit

It has some logic to handle symbols the binary hasn't provided, but these cause gdb to fail under wsl.

* What's wrong / what should be happening instead:

performing the following segment,

```
# Define $symbol = (type)addr if it exists,  undefined if not
define symbol_check
  log_to_file symbol.tmp on
  p $arg0
  end_log

  shell sed -i -e '/^[^\$]/d' -e 's/^\$[0-9]* =/set $'$arg0' =/' symbol.tmp
  source symbol.tmp
end

```
gdb under wsl silently falls back to the gdb prompt at the "p $arg0" line, for symbols that dont exist, causing the rest of the script to fail to run correctly, and leaving logging directed to the file confusing people using it.

under linux/bsd/macos etc this does not happen, allowing us to use the information to determine if we need to spoof the symbol and do the necessary steps.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by Kalamatee** [comment]
Create a .gdbinit file with the following in -:

```
define log_to_file
  set logging file $arg0
  set logging redirect on
  set logging overwrite $arg1
  set logging on
end

define end_log
  set logging off
end

# Define $symbol = (type)addr if it exists,  undefined if not
define symbol_check
  log_to_file symbol.tmp on
  p $arg0
  end_log

  shell sed -i -e '/^[^\$]/d' -e 's/^\$[0-9]* =/set $'$arg0' =/' symbol.tmp
  source symbol.tmp
end
```

Then, launch GDB and call symbol_check for some non-existant symbol, e.g. -:
`symbol_check SysBase`

Finally, now try to print the value of the symbol -:
`p SysBase`

Expected result: 
Normal output (in this case 'No symbol table is loaded. Use the "file" command.' should be shown)

Actual Result:
Nothing is output because logging is still enabled, due to the "p $arg0" in symbol_check silently failing.

**Comment by therealkenc** [comment]
There no output on Real Linux.

![image](https://user-images.githubusercontent.com/7049700/73625213-b8089e80-45f8-11ea-906b-9e923c9e445e.png)
