### ISSUE TITLE
mmap with MAP_LOCKED fails with EOPNOTSUP.

### ISSUE THREAD

**Issue by max0x7ba** [microsoft/WSL#4857]
My application does the following call:

    mmap(NULL, 33554432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_LOCKED, -1, 0);

It works in bare-metal Ubuntu 18.04.3 LTS as expected, but fails with `EOPNOTSUPP` in Microsoft Windows [Version 10.0.18363.592] with Ubuntu 18.04.2 LTS.

**Comment by therealkenc** [comment]
Strange it has never come up before; no dupe I can find. WSL does have `mlock()` although I couldn't tell you if it is a stub. Better in WSL2. Work-around in WSL1 is to drop the flag (there will near always be a config flag for well-worn packages), or shim `mmap()` with `LD_PRELOAD`.

**Comment by Biswa96** [comment]
It looks like the LxCore driver (WSL1) does not support `MAP_LOCKED` flag (0x2000). There is a way to get the debug output with `kd`, [here][1] is guide. The output is like this:

```
(a.out) Don't know how to handle flags 0x2000
MMAP - {0000000000000000}, 0x1, 3, 0x2022, -1, 0 = -95
(a.out) [0xffffffa1] Syscall 9 failed with unexpected error -95!
```

In LxCore it is handled like this, LxpSyscall_MMAP --> LxpMmMmap --> LxpMiMmapValidateParameters.


[1]: https://github.com/Biswa96/WslReverse

**Comment by max0x7ba** [comment]
> Strange it has never come up before; no dupe I can find. WSL does have [`mlock()`](http://man7.org/linux/man-pages/man2/mlock.2.html) although I couldn't tell you if it is a stub. Better in WSL2. Work-around in WSL1 is to drop the flag (there will near always be a config flag for well-worn packages), or shim `mmap()` with `LD_PRELOAD`.

I wonder when WSL2 is going to be released to all Windows 10 users. Closing the bug because it is fixed in an unavailable version is a bit of sad corporate joke.
