### ISSUE TITLE
Windows binary in detached tmux freezes on last terminal close

### ISSUE THREAD

**Issue by jarussell** [microsoft/WSL#4858]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows Version 10.0.18363.592

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Opening a urxvt terminal called from bash. Within this terminal I am opening tmux. Inside of tmux I open pianobar.exe (https://github.com/thedmd/pianobar-windows). I then detach tmux and close all terminals so I can listen to music without distractions but still reattach later to skip songs, etc. 

* What's wrong / what should be happening instead:

There is no problem until I close the shell that tmux was launched from (the only shell I had open). The windows binary, pianobar.exe, crashes and becomes unresponsive. linux programs in the same tmux session still appear to work.

This is a possible duplicate of  #4635, but does not happen immediately on detaching tmux but only on closing the last terminal.

**Comment by aont** [comment]
@jarussell Hello. FYI: I'm not a WSL developer, but the workaround I have developed works good: [aont/tmux-wsl-workaround](https://github.com/aont/tmux-wsl-workaround/)
