### ISSUE TITLE
can not find serial port

### ISSUE THREAD

**Issue by zcqh007** [microsoft/WSL#4861]
hi:
 i use wsl ubuntu 18.04LTS, but can not open any serial port .use dmesg  the result like  this
[    0.121676]  Microsoft 4.4.0-18362.476-Microsoft 4.4.35
[    2.258282] <3>init: (1) ERROR: UtilCreateProcessAndWait:360: /bin/mount failed with status 0
[    2.258288] 2000
[    2.318393] <3>init: (1) ERROR: UtilCreateProcessAndWait:360: /bin/mount failed with status 0
[    2.318399] 2000
please tell me how i can do.
e ,my english is so poor ,sorry.

**Comment by sirredbeard** [comment]
Serial ports are accessible on WSL as followed: COMx as /dev/ttySx For example, COM5 will be /dev/ttyS5.

To read and write, you may need to set permissions:

`chmod 666 /dev/ttyS5`

**Comment by waterfox207** [comment]
Hi if I type 'chmod 666 /dev/ttyS9' for my  FTDI chip wich is shown as COM9 into the device manager I get: Operation not permitted
How do I get it work? 
How can I list the usb ports? lsusb shows nothing.

**Comment by diegovisentin** [comment]
Does it also work on WSL2?
(from docs it seems that WLS1 supports serial ports but not WLS2)
