### ISSUE TITLE
add support for io uring

### ISSUE THREAD

**Issue by cppdev-123** [microsoft/WSL#4863]

**Comment by therealkenc** [comment]
Over [here](https://github.com/microsoft/WSL2-Linux-Kernel) in principle. Effectively dupe [microsoft/WSL2-Linux-Kernel#28](https://github.com/microsoft/WSL2-Linux-Kernel/issues/28).

**Comment by eligbr** [comment]
Hi, was this fixed? I could not manage to run io_uring after upgrading wsl kernel

**Comment by thomasjungblut** [comment]
I can also not see it being available yet in the latest: 
> Linux xxx 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

any idea when we can see support for io_uring? Would be much more convenient to develop.

**Comment by omertoast** [comment]
It seems like it still isn't available. Do you have an ETA for io_uring support?

**Comment by benhillis** [comment]
io_uring support is being added in an upcoming Linux kernel update.

**Comment by lefth** [comment]
Isn't this done already? I'm using io_uring in a project, and it's listed in a changelog here:
https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes

**Comment by Thendytx** [comment]
> Isn't this done already? I'm using io_uring in a project, and it's listed in a changelog here: https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes

hi, tks for providing the release note, but how do you use io_uring in wsl2? I just updated my wsl kernel to 5.10.102.2, but when I try to check in man it just said no manual entry for io_uring.
also when I use the command "locate liburing", my wsl2(ubuntu) has no result.

**Comment by Thendytx** [comment]
> Isn't this done already? I'm using io_uring in a project, and it's listed in a changelog here: https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes

hi @lefth , tks for providing the release note, but how do you use io_uring in wsl2? I just updated my wsl kernel to 5.10.102.2, but when I try to check in man it just said no manual entry for io_uring.
also when I use the command "locate liburing", my wsl2(ubuntu) has no result.

**Comment by lefth** [comment]
@Thendytx sorry I didn't use liburing. I used a Rust library that provided the APIs. I also compiled my own kernel, but I assume that probably wasn't necessary.
