### ISSUE TITLE
Partition in WSL separate from Windows (NTFS) ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/WSL#4864]
I've read up on how Windows and Linux communicate, but what I want to know; is it possible, to re-partition a drive separate from that in Windows.  Therefore not effecting basically anything on Windows, which would cause programs and Windows from booting, only when going into WSL would the partitions and drives be unique from Windows ?

**Comment by therealkenc** [comment]
Can't parse this, but best guess you are trying for either #579 or #689, or possibly #4556 (#4574). Or in the alternative, question➡️answer "no".

**Comment by SheepDomination** [comment]
What I want to do, is mount a loop back device ?
