### ISSUE TITLE
Cannot install WSL using PowerShell Add-AppxPackage

### ISSUE THREAD

**Issue by long-nguyenxuan** [microsoft/WSL#4865]
### Windows build number:  
Microsoft Windows [Version 10.0.18363.592]

### What you're doing and what's happening: 
- I'm trying to install Ubuntu 1804 on my WSL using `Add-AppxPackage` command on an Administrative Powershell follow [this guide](https://docs.microsoft.com/en-us/windows/wsl/install-manual)

### What's wrong / what should be happening instead:
*What's wrong:*

No distro got installed 
No shortcut showed up in startmenu
Cannot access to Microsoft Store (err msg: internal problem, maybe my company network)

*Should be happening:*

Ubuntu should be installed on my system. 
![20200202_214621_Window](https://user-images.githubusercontent.com/46129500/73610048-1425ef80-4606-11ea-9a58-3bb07f60a7e8.png)

**Comment by DHowett-MSFT** [comment]
From the documentation you linked:

> Once your distro is installed please refer to the [Initialization Steps](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro) page to initialize your new distro.

That link explains what you need to do next.

**Comment by long-nguyenxuan** [comment]
> From the documentation you linked:
> 
> > Once your distro is installed please refer to the [Initialization Steps](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro) page to initialize your new distro.
> 
> That link explains what you need to do next.

Thanks, sorry I did not note that there is no shortcut in the Start Menu nor the Microsoft Store at all.
I've renamed appx file to zip, unzip and double click on ubuntu1804.exe, now my wsl works.

But I think it could be better if inatall-process could open the first-time-launch-console automatically.
