### ISSUE TITLE
VS Code couldn't link with wsl2 and cannot open wsl2 through powershell or cmd

### ISSUE THREAD

**Issue by NaiveTomcat** [microsoft/WSL#4866]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [版本 10.0.19555.1001]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

In powershell
```
PS C:\Users\12045> wsl.exe -d Ubuntu
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

In VS Code

![image](https://user-images.githubusercontent.com/50436951/73611389-5fe39380-461c-11ea-8a50-16759bfc1ace.png)

* What's wrong / what should be happening instead:

I am using wsl2, and wsl2 is working properly and can be access through Windows Terminal. 
But when I attemp to launch wsl by typing `wsl.exe` in cmd or powershell prompt, connection 
failed.

Problem also occers when I try to run VS Code Terminal with wsl.

In addition, Windows Terminal and PuTTY ssh connected seccessfully.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by DHowett-MSFT** [comment]
This looks like a duplicate of #4860.

**Comment by therealkenc** [comment]
Maybe; but the error message ("`Unable to detect if server is already installed....`") is [different](https://github.com/microsoft/WSL/issues/4860#issuecomment-580895174). Also the diverge is it working in Windows Terminal but not Powershell or Windows Console (aka CMD). There's no indication in #4860 that using Windows Terminal is a work-around. [If it is, that would be a good data point.]

@NaiveTomcat: please confirm whether VS Code was working for you before your Windows Update to 19555. If it was working, roll back and see if that helps. If it doesn't, then we can dig a little more. A betting person would still pin this on #4860 -- for now.

**Comment by Ma3yTa** [comment]
I have the same issue. Windows Version 2004 (OS Build 19555.1001)
```powershell
>> wsl code .
Updating VS Code Server to version 26076a4de974ead31f97692a0d32f90d735645c0
Removing previous installation...
Installing VS Code Server for x64 (26076a4de974ead31f97692a0d32f90d735645c0)
...............
Failed
Connecting to update.code.visualstudio.com (104.42.78.153:443)
Connecting to az764295.vo.msecnd.net (117.18.232.200:443)
26076a4de974ead31f97 100% |************************************************************************| 28.1M  0:00:00 ETA
ERROR: Failed to download https://update.code.visualstudio.com/commit:26076a4de974ead31f97692a0d32f90d735645c0/server-linux-x64/stable to /root/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0-1580698853.tar.gz
```

**Comment by therealkenc** [comment]
^--- that is not on planet [same](https://www.merriam-webster.com/dictionary/same).

**Comment by NaiveTomcat** [comment]
> Maybe; but the error message ("`Unable to detect if server is already installed....`") is [different](https://github.com/microsoft/WSL/issues/4860#issuecomment-580895174). Also the diverge is it working in Windows Terminal but not Powershell or Windows Console (aka CMD). There's no indication in #4860 that using Windows Terminal is a work-around. [If it is, that would be a good data point.]
> 
> @NaiveTomcat: please confirm whether VS Code was working for you before your Windows Update to 19555. If it was working, roll back and see if that helps. If it doesn't, then we can dig a little more. A betting person would still pin this on #4860 -- for now.

@therealkenc On 19551.1005, Code can successfully connect to WSL and launch wsl through Windows Console and Powershell and Start Menu succeeded. All that happened after I updated it to 19555.1001. I have deleted the previous Windows install file so I couldn't roll back to 19551.1001. 

And for your information, my computer experienced update failure since 18990.1, and not untill 19551.1005 the update succeeded

**Comment by therealkenc** [comment]
Alright. That leaves a couple of options. (1) Sit on it until the #4860 fix rolls out. (2) Attempt work-arounds. The canonically [accepted](https://github.com/microsoft/WSL/issues/4860#issuecomment-580938962) work-around (other than rolling back) being launder your path to something crazy short. For example:

![image](https://user-images.githubusercontent.com/7049700/73626026-2bf87600-45fc-11ea-9ac0-a1dcf3fa208f.png)

However there are good indications that [doesn't work](https://github.com/microsoft/WSL/issues/4860#issuecomment-580967091) for your particular fail.

The other work-around is to use [Remote - SSH](https://github.com/microsoft/WSL/issues/4860#issuecomment-580895174).

Given you were okay on 19551 but not 19555, this near certain has to be a dupe root case (working premise anyway). But we can hold this submission standalone until your and @JMBBunch's scenario has a confirmed work-around short of rollback.

**Comment by NaiveTomcat** [comment]
I may have found a way to overcome this bug

Type `wsl --shutdown` in the Powershell and `wsl` again in the powershell to restart wsl and then, it started working dramatically. 

This way only applies to Powershell, VS Code and Command Prompt still can't launch wsl.

**Comment by NaiveTomcat** [comment]
> I may have found a way to overcome this bug
> 
> Type `wsl --shutdown` in the Powershell and `wsl` again in the powershell to restart wsl and then, it started working dramatically.
> 
> This way only applies to Powershell, VS Code and Command Prompt still can't launch wsl.

But I experienced another bothering thing that in the task manager, Internet connection for wsl does not appear after those. 

Bug need explain.

**Comment by JMBBunch** [comment]
> 
> 
> I may have found a way to overcome this bug
> 
> Type `wsl --shutdown` in the Powershell and `wsl` again in the powershell to restart wsl and then, it started working dramatically.
> 
> This way only applies to Powershell, VS Code and Command Prompt still can't launch wsl.

This did not help. Exact same messages.

**Comment by therealkenc** [comment]
> To be clear, my WSL now starts fine after shortening the path

Great. Thanks for the confirmation (the OP had not).

**Comment by NaiveTomcat** [comment]
发自我的华为手机It only works in Powershell and I have not tested it multiple times, so it might not work.Gimme more information about it and let me have another try.-------- 原始邮件 --------发件人： JMBBunch <notifications@github.com>日期： 2020年2月4日周二 凌晨2:59收件人： microsoft/WSL <WSL@noreply.github.com>抄送： NaiveTomcat <1204521668@qq.com>, Mention <mention@noreply.github.com>主    题： Re: [microsoft/WSL] VS Code couldn't link with wsl2 and cannot open wsl2 through powershell or cmd (#4866)
I may have found a way to overcome this bug
Type wsl --shutdown in the Powershell and wsl again in the powershell to restart wsl and then, it started working dramatically.
This way only applies to Powershell, VS Code and Command Prompt still can't launch wsl.

This did not help. Exact same messages.

**Comment by DHowett-MSFT** [comment]
Can you try.. (from PowerShell)

```
$Env:PATH=""
& C:\windows\system32\wsl.exe
```

?

Thanks.

FWIW: The translation of the error message "由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。" is ... "The connection attempt failed because the connecting party did not respond correctly after a period of time or the connected host did not respond." This seems like literally the same error message as #4866.

**Comment by NaiveTomcat** [comment]
@JMBBunch Actually, this way can only launch WSL from Powershell.

Any attempt for launching WSL from CMD and vscode fails.

**Comment by NaiveTomcat** [comment]
> Can you try.. (from PowerShell)
> 
> ```
> $Env:PATH=""
> & C:\windows\system32\wsl.exe
> ```
> 
> ?
> 
> Thanks.
> 
> FWIW: The translation of the error message "由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。" is ... "The connection attempt failed because the connecting party did not respond correctly after a period of time or the connected host did not respond." This seems like literally the same error message as #4866.

@DHowett-MSFT Making PATH environmental variable crazily short did help. It was the I found out restart WSL in Powershell did help, even with a more-than-one-thousand-chracter long PATH variable.

**Comment by NaiveTomcat** [comment]
And I did try it and it works. But I don't want to make some of my PATH-Variable-sensitive applications got messed so I restored my PATH environmental variable

**Comment by NaiveTomcat** [comment]
And because I am in PRC so my online time is base on GMT+8 time zone. I may be late to reply

**Comment by therealkenc** [comment]
> This seems like literally the same error message as #4866.

It is the same as (a dupe of) #4860. The only thing keeping this submission (#4866) alive is all the thumbs up on @JMBBunch's [post](https://github.com/microsoft/WSL/issues/4860#issuecomment-580967091) indicating shortening the `%PATH%` _didn't_ help.

Given that @NaiveTomcat has confirmed the `%PATH%` work-around though, there isn't an actionable left here.

**Comment by JMBBunch** [comment]
In Powershell 6:  
`$Env:PATH="C:\Users\<user>\AppData\Local\Microsoft\WindowsApps;C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\bin;"
C:\windows\system32\wsl.exe`

At that point I get the expected WSL prompt, sitting at /mnt/c/WINDOWS/system32.
At that prompt I run:  code .

Voila! VS Code opens a terminal sitting at /mnt/c/WINDOWS/system32. From there, I can get access to the WSL homedir ~.  Yay!

**Comment by therealkenc** [comment]
Alright. I hate denouncing closes, but there is nothing novel left here. Alternative work-around remains Remote - SSH.
