### ISSUE TITLE
Windows filesystem cannot resolve symlinks in WSL

### ISSUE THREAD

**Issue by BatmanAoD** [microsoft/WSL#4867]
I have found that Windows programs (such as native Windows gVim and `cmd.exe`) cannot resolve WSL filepaths involving symlinks.

The simplest example is using `cmd.exe` and the `type` built-in.

In a WSL shell:

```
$> echo "file contents" > /tmp/foo
$> ln -s /tmp/foo /tmp/bar
$> cat /tmp/foo
file contents
$> cat /tmp/bar
file contents
$> wslpath -wa /tmp/bar
\\wsl$\Ubuntu\tmp\bar
```

In `cmd.exe`:

```
C:\>type "\\wsl$\ubuntu\tmp\foo"
file contents

C:\>type "\\wsl$\ubuntu\tmp\bar"
The name of the file cannot be resolved by the system.
```

#### Version info

From a WSL shell:

```
$> cat /proc/version
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #476-Microsoft Fri Nov 01 16:53:00 PST 2019
$> cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.592]
```

**Comment by BatmanAoD** [comment]
I've marked this as a "bug", but arguably it's a missing feature of `wslpath`. It seems reasonable that the `-a` flag should dereference symlinks

**Comment by BatmanAoD** [comment]
For now, creating a workaround in the WSL shell is pretty easy, using GNU `readlink -f` to dereference symlinks *before* passing file paths to `wslpath`.

**Comment by therealkenc** [comment]
No version given. Ref #4866.

![image](https://user-images.githubusercontent.com/7049700/73624731-ce155f80-45f6-11ea-80e6-0b08b837cee1.png)

**Comment by BatmanAoD** [comment]
Sorry, I knew I forgot something! I've updated the top-level comment.

**Comment by therealkenc** [comment]
Alright, chasing issue links it seems the behavior didn't change until 18917 ref #3999 ([message](https://github.com/microsoft/WSL/issues/3999#issuecomment-576770161). /dupe #4078, I'll fix up the fixed-in tag over there. Thanks for the submission and the version clarification.
