### ISSUE TITLE
SIGTERM signal is not handled correctly by strace (build 14361)

### ISSUE THREAD

**Issue by xilun** [Microsoft/WSL#487]
SIGTERM is not handled by strace correctly: strace manages to dump it and does not exits, however the target process does not terminate and the old behavior of strace was actually better in this case because at this point:
- strace does not work anymore, strace can however be killed, but;
- the target process can not be straced again:
  
  strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
  strace: attach: ptrace(PTRACE_ATTACH, ...): Operation not permitted
  Could not attach to process.  If your uid matches the uid of the target
  process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
  again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
- the target process can not be killed (neither with the kill command, nor with a windows task manager, and not even with a kill -9 ! This is annoying, the reliability of kill -9 should be absolute...

However, I've noted that strace now (in 14361) seems to work correctly for signals not trying to terminate the process. Congrats for that, it will be easier to debug stuff :)

**Comment by misenesi** [comment]
Hi @xilun,

I have done the signal propagation when stracing fix (and we have done some additional work there as well). On my latest internal build I tried following:

1) strace -o /dev/null yes > /dev/null&
2) ps to find yes process pid
3) kill -15 [pid of yes process]

It seems to be working just fine.

Can you provide repro steps?

**Comment by misenesi** [comment]
I wrote a simple program that would ignore SIGTERM. Tried stracing it via attaching to already running process as well as stracing the process from start, and then sending SIGTERM to it. Everything seems to be working as expected.

@xilun I will close it for now as fixed, please don't hesitate to reactivate if you still find it not working for you. Thank you for reporting the issue :)

**Comment by xilun** [comment]
Just for info: I'm trying to get a minimal repro, will reopen if I manage to do it.

**Comment by xilun** [comment]
Hi,
Here is the minimal reduction I could come up with:

    // 1st shell:       gcc -O2 -Wall -Wextra -std=c11 -o wrun wrun.c  && strace -tt ./wrun
    // another shell:   killall wrun

    #define _XOPEN_SOURCE 700
    #define _BSD_SOURCE

    #include <sys/select.h>
    #include <signal.h>
    #include <string.h>

    int main(void)
    {
        sigset_t signal_set;
        sigemptyset(&signal_set);

        int nfds = 1;
        while (1) {
            fd_set rfds;
            FD_ZERO(&rfds);
            FD_SET(0, &rfds);

            pselect(nfds, &rfds, NULL, NULL, NULL, &signal_set);
        }

        return 0;
    }

**Comment by misenesi** [comment]
Hi @xilun,

just tried your repro and it still seems to work just fine in the latest build (not sure when these bits make it out to the public).

Milan

**Comment by misenesi** [comment]
However your repro did uncover one scenario that we weren't handling properly (restoring the temporary mask set by pselect when the process is ptraced and the signal is injected), so I have just prepared a fix for that.

Thank you @xilun for reporting the issue and taking time to create a repro, really appreciate it!

**Comment by misenesi** [comment]
I have installed your build and I was able to repro the issue. Checked in the fix. It might take a while before it bubbles all the way to the public release.

**Comment by misenesi** [comment]
The fix is being evaluated.

**Comment by xilun** [comment]
For info: I retested the repro on 14376, and it seems to still be buggy.

**Comment by misenesi** [comment]
The fix didn't make it to the build you retested it on unfortunatelly. In will be in one of the future builds, but I am unable to specify in which one exactly at this point.

**Comment by xilun** [comment]
ok, thanks for the info!

**Comment by xilun** [comment]
Again just for info and reference; it seems to be working a little better on 14388 (every process eventually dies) but strace still shows that this is not perfect.

Here is the end of the trace under WSL, just after the killall:

    23:32:43.215507 munmap(0x7f9d4a106000, 40054) = 0
    23:32:43.216835 pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = -1 EINTR (Interrupted system call)
    23:32:49.128153 --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=154, si_uid=1000} ---
    23:32:49.129795 pselect6(1, [?], NULL, NULL, NULL, 0x7ffffad9dd80

Here is a proper trace, under Linux:

    23:35:16.910652 munmap(0x7f8ac55e2000, 100585) = 0
    23:35:16.910964 pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = ? ERESTARTNOHAND (To be restarted if no handler)
    23:35:19.269235 --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=14551, si_uid=1000} ---
    23:35:19.269385 +++ killed by SIGTERM +++

**Comment by misenesi** [comment]
Hi @xilun,

thank you for your persistence! The change didn't make it to this flight, that is only addressing most critical bugs. I can only promise it should be in one of the following flights, but might not be the very next one either.

Thanks,
Milan
