### ISSUE TITLE
"wsl -l -v" lists only 1 WSL but I have installed multiple

### ISSUE THREAD

**Issue by francesco1119** [microsoft/WSL#4875]
* Your Windows build number:  **Microsoft Windows [Version 10.0.19035.1]**

* What you're doing and what's happening:  **When I type` wsl -l -v` only 1 version of WSL is shown but I have installed 3 of them**

* What's wrong / what should be happening instead: **I should see 3 versions: Ubuntu, Kali, Debian**
![possible](https://user-images.githubusercontent.com/3397477/73881352-724e0f00-4860-11ea-99c3-8d7015cecc36.png)

**Comment by craigloewen-msft** [comment]
If you open up the Kali or Debian distro app, what happens? 

My guess is that they'll give you an 'Installing please wait...' message. 

Once the distros are downloaded, they are registered to WSL during the first run, so after they're initialized you'll be able to see them in `wsl -l -v`.

**Comment by nunix** [comment]
I was about to write the same answer😅
I also faced it with freshly new store distros. The first launch will actually register the distro and launch it.
then even if you close the terminal without creating a user, you will see the distro as it ran the registration

at least that’s what I experienced

The Corsair

**Comment by francesco1119** [comment]
Dammit, you were definitely right. 
I read your post yesterday night and I fired up both Debian and Kali. I have an Intel NUC8i7HVK and after 24h and a reboot they are both still installing. 

I will update you tomorrow if the issue persists

![Run](https://user-images.githubusercontent.com/3397477/73976904-90337680-4929-11ea-9a13-8559a39fa926.png)

**Comment by francesco1119** [comment]
Yep, it took an eternity but in the end it was fixed
