### ISSUE TITLE
wsl ubuntu does not start anymore

### ISSUE THREAD

**Issue by tiefseeruebe** [microsoft/WSL#4876]
After removing manually a ubuntu folder in my home directory by mistake, Ubuntu does not start any more. The error message:

wslbridge error: failed to start backend process
note: bash.exe output: Der angegebene Netzwerkname ist nicht mehr verfügbar.
The German part is "The specified network name is not available any more."

I disabled and reenabled WSL for Windows in the Windows feature list. I reinstalled Ubuntu for WSL. But the error message persists.

Windows Version: Microsoft Windows [Version 10.0.17763.973]
Ubuntu Version: 1804.2018.817.0

The detailed logs enabled by logman.exe did not contain any information. The three files were empty after trying to start Ubuntu. 

The Feedback Hub recommended for network issues does not start at my system. It's probably disabled by my company. 

How could I start my Ubuntu again? 

Thank you very much for any hint.
Regards

**Comment by therealkenc** [comment]
> wslbridge error: failed to start backend process

wslbridge is [here](https://github.com/rprichard/wslbridge).

**Comment by tiefseeruebe** [comment]
thank you
