### ISSUE TITLE
WSL 2 distro not launch timing out

### ISSUE THREAD

**Issue by Gurran** [microsoft/WSL#4878]
#### Windows build number:
`Microsoft Windows [Version 10.0.19555.1001]`

* What you're doing and what's happening:  

When launching a wsl 2 distro it fails. This worked previously, stopped working about a week ago. WSL version 1 is fine. I can launch the distro through VSCode WSL Remote and through WSLTTY but __not__ through cmd or powershell. Neither powershell 5.1 or powershell 7.0.0-rc.2 works.

![image](https://user-images.githubusercontent.com/42462633/74011127-53966800-4987-11ea-8566-29b850b34949.png)

* What's wrong / what should be happening instead:

WSL 2 distros should launch.

**Comment by Gurran** [comment]
![image](https://user-images.githubusercontent.com/42462633/74012101-bee13980-4989-11ea-8b1a-1ab1e97d77aa.png)

**Comment by Biswa96** [comment]
The error message seems to be similar with this issue https://github.com/microsoft/WSL/issues/4860. That issue has a workaround by editing `%PATH%` environment variable. Could you check if that workaround solve your issue?

**Comment by Gurran** [comment]
I tried clearning the path. That just makes the `wsl` command not being found. 

But I've discovered that if I run `.\wsl` directly in `C:\WINDOWS\system32` is works fine.

So it seems to be something with the path. But clearning does nothing.

@Biswa96

**Comment by Gurran** [comment]
Oh! My fault. The fix did work.

![image](https://user-images.githubusercontent.com/42462633/74018370-19809280-4996-11ea-9fa7-d4cc763168bc.png)

**Comment by Gurran** [comment]
What worked for me.
1. Clearing path in powershell 
`$env:PATH=""`
2. Launching wsl distro from the wsl exe directly. 
`cd C:\Windows\System32\`
`.\wsl`

Reference to original discussion:
https://github.com/microsoft/WSL/issues/4860
