### ISSUE TITLE
WSL2 fails to launch again -- in build 19559

### ISSUE THREAD

**Issue by NaiveTomcat** [microsoft/WSL#4879]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.19559.1000

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Every attempt to launch wsl fails.

Using Terminal to launch returns `[Process exited with code 1]`. In 19555.1001, this way can work.
See #4866 .

* What's wrong / what should be happening instead:

wsl should have started but not.

My very own workaroud in #4866 did not help.

This time in cmd or Powershell no error message, just can't luanch.

Making `PATH` variable crazily short helps.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by Biswa96** [comment]
The same issue https://github.com/microsoft/WSL/issues/4860 is tagged with 'fixinbound'. There is no insider build released with the fix yet. Wait for 1 or 2 weeks for next insider build which may contain the fix.

**Comment by NaiveTomcat** [comment]
> The same issue #4860 is tagged with 'fixinbound'. There is no insider build released with the fix yet. Wait for 1 or 2 weeks for next insider build which may contain the fix.

The issue has different appearance of #4860 and #4866

**Comment by Biswa96** [comment]
But you've stated "Making PATH variable crazily short helps".
