### ISSUE TITLE
Jupyter Notebook causes an PowerShell-style error

### ISSUE THREAD

**Issue by altwarg** [microsoft/WSL#4881]
* Windows build number:  10.0.18363.628

* What you're doing and what's happening:
```sh
$ sudo apt install python3-pip
$ sudo pip3 install notebook
$ jupyter notebook
```

* What's wrong / what should be happening instead:
There're must not be any PowerShell-style error messages:
![image](https://user-images.githubusercontent.com/34391398/74139481-7f725180-4c04-11ea-8077-43c42253b212.png)

**Comment by therealkenc** [comment]
Jupiter is launching powershell.exe and failing to accomplish whatever it is it was trying to accomplish (WSL, launching a browser). Or [looks so](https://github.com/jupyter/notebook/blob/d145301b5583366fc0c5e938ded80f07a0bc1bbf/notebook/terminal/__init__.py#L18).

**Comment by altwarg** [comment]
> Jupiter is launching powershell.exe and failing to accomplish whatever it is it was trying to accomplish (WAG, launching a browser)

But os.name on WSL should not be 'NT'. Or..?

**Comment by therealkenc** [comment]
You're right. That cited line can't be it (it was the first/only hit on the Jupyter [source](https://github.com/jupyter/notebook/search?q=powershell.exe&unscoped_q=powershell.exe)). _Something_ in your userspace is spawning a `powershell.exe`. Could not tell you what. Can tell you nothing WSL related spawns a powershell.

**Comment by altwarg** [comment]
I figured it out. It seems that without an option `--no-browser` jupyter tries to open a browser inside WSL
