### ISSUE TITLE
WSL error 0x800700b7

### ISSUE THREAD

**Issue by Abdelazizdz** [microsoft/WSL#4886]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including all command-line steps necessary to induce the failure condition. Please fill out all the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the console issue tracker.

Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Ideally, please configure your machine to capture minidumps, repro the issue, and send the minidump from "C:\Windows\minidump".\

See our contributing instructions for assistance.

Please fill out the below information:

    Your Windows build number: (Type ver at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.973]

    What you're doing and what's happening: (Copy&paste the full set of specific command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

D:\Ubuntu_18.04>ubuntu1804.exe

    What's wrong / what should be happening instead:

What's wrong is that the following error message occurs:

**"Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800700b7
The distribution installation has become corrupted.
Please select Reset from App Settings or uninstall and reinstall the app.
Error: 0x800700b7 Cannot create a file when that file already exists."**

What should happen is the installation of ubuntu

What I've done : 

1)
sc query LxssManager
sc stop LxssManager
sc start LxssManager
==> same issue
2)
remove WSL > restart server > add WSL feature
==> same issue

Thanks for your help

**Comment by therealkenc** [comment]
Forward /dupe to #5724.
