### ISSUE TITLE
ssh connection to host resource temporarily unavailable

### ISSUE THREAD

**Issue by aclifton314** [microsoft/WSL#4888]
**Windows Version:** Microsoft Windows [10.0.17763.973]
**Linux Version:** Ubuntu 18.04 LTS

Hi Everyone,

I am trying to `ssh` from a laptop into a desktop using WSL. Both machines run the above Windows version and both run Ubuntu 18.04 LTS. I can `ssh localhost` into both machines with no issues. When I try to `ssh` into the desktop from the laptop, I get:

`
ssh: connect to host port 22: Resource temporarily unavailable
`

I have tried a few things from the issues open and closed here, but they haven't worked. Below is the verbose output from the laptop:
```
$ ssh -vvv desktop.address.com
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /home/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "desktop.address.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to desktop.address.com [***.***.**.**] port 22.
debug1: connect to address ***.***.**.** port 22: Resource temporarily unavailable
ssh: connect to host desktop.address.com port 22: Resource temporarily unavailable
```

Thanks in advance for your help!

**Comment by nunix** [comment]
hi, please note that if you have the developer mode active, the port 22 is already in use.

What you can do as a test, is to modify the /etc/ssh/sshd_config > Port 2222
Then restart the sshd service `sudo service sshd restart`

Finally, try to login with `ssh -p2222 desktop.address.com`

hope it helps
The Corsair

**Comment by aclifton314** [comment]
@nunix, just to clarify, I am modifying `/etc/ssh/sshd_config` on the desktop right?

**Comment by nunix** [comment]
@aclifton314 indeed, if I understood correctly, it is the endpoint you want to connect to, therefore the sshd daemon is running on your desktop.

**Comment by aclifton314** [comment]
@nunix Thanks for your response.
I edited the `/etc/ssh/sshd_config` file on the desktop, uncommented `Port`, set it to 2222, saved, and restarted the sshd service. `sudo service sshd restart` threw `sshd: Unrecognized service`, but `sudo service ssh restart` worked.

Here is the output from ssh-ing from the laptop:
```
$ ssh -vvv -p2222 desktop.address.com
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /home/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "desktop.address.com" port 2222
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to desktop.address.com [ip_address] port 2222.
debug1: connect to address ip_address port 2222: Resource temporarily unavailable
ssh: connect to host desktop.address.com port 2222: Resource temporarily unavailable
```

**Comment by nunix** [comment]
hmm ok, from the desktop directly, can you do a ssh -p2222 localhost
and ensure the sshd process is running fine: `ps -ef | grep ssh` (I didn't add the **d** on purpose)

**Comment by aclifton314** [comment]
Sure thing!
```
$ ps -ef | grep ssh
root      1109     1  0 13:55 ?        00:00:00 /usr/sbin/sshd
user  1117  1023  0 14:13 tty1     00:00:00 grep --color=auto ssh
```

And here is `ssh -p2222 localhost`
```
$ ssh -p2222 localhost
user@localhost's password:
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.4.0-17763-Microsoft x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Feb 12 14:14:29 STD 2020

  System load:    0.52      Memory usage: 37%   Processes:       10
  Usage of /home: unknown   Swap usage:   0%    Users logged in: 0

  => There were exceptions while processing one or more plugins. See
     /var/log/landscape/sysinfo.log for more information.


0 packages can be updated.
0 updates are security updates.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


Last login: Wed Feb 12 11:57:52 2020 from 127.0.0.1
```

**Comment by nunix** [comment]
ok good news it works with `localhost`, so the server is definitively running and accepting the connections.

now, try the local ssh -p2222 but with the "public ip" instead of localhost. it should work also.
if it's the case, then my guess is that the Windows firewall might need to have a new inbound and outbound rule for the port 2222

oh, and from powershell try `netstat -an | select-string 2222`, this will ensure that the port 2222 has correctly been also open on the Windows side

**Comment by aclifton314** [comment]
```
$ ssh -p2222 public_ip
user@public_ip's password:
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.4.0-17763-Microsoft x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Feb 12 14:33:18 STD 2020

  System load:    0.52      Memory usage: 38%   Processes:       10
  Usage of /home: unknown   Swap usage:   0%    Users logged in: 0

  => There were exceptions while processing one or more plugins. See
     /var/log/landscape/sysinfo.log for more information.


0 packages can be updated.
0 updates are security updates.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


Last login: Wed Feb 12 14:33:00 2020 from public_ip
```

and from Powershell:
```
PS H:\> netstat -an | select-string 2222

  TCP    0.0.0.0:2222           0.0.0.0:0              LISTENING
  TCP    public_ip:2222     public_ip:50262    ESTABLISHED
  TCP    public_ip:50262    public_ip:2222     ESTABLISHED
  TCP    [::]:2222              [::]:0                 LISTENING



PS H:\> 
```

**Comment by nunix** [comment]
ok, so finally I would say to add a rule in the Windows firewall for the port 2222 and try again from your other computer. add the rule to all profiles: Domain,Public,Private

ps: not recommended to keep it, but you can try deactivating the firewalls via powershell `Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False`
and don't forget to re-enable it `Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True`

**Comment by aclifton314** [comment]
I set an inbound rule for port 2222 that allows all connections and set it for all profiles as you said above. It is also set for the TCP protocol and I restarted the desktop machine.

I ran `ssh -p 2222 desktop.address.com` from my laptop and still get the `Resource temporarily unavailable` error. 

One thing I noticed was when I open the Windows Defender Firewall and click "Allow an app or feature through Windows Defender Firewall", the rule I set is selected only for Domain and Private. But when I go to the advanced settings and look for the inbound rule, there are 2 of them. 

One of them has a green check mark next to it and is set for Domain and Private under profile and the other has no green check mark and is set Public under profile.

**Comment by aclifton314** [comment]
Any further thoughts on this?

**Comment by waqasafzal** [comment]
@aclifton314 hi, did you find the solution for this ? Thanks.

**Comment by guo-fan-sun** [comment]
I think this is serve has not open ssh port

**Comment by HeshamZwayyed22** [comment]
I faced the same problem suddenly after ssh was working fine, then I found that windows made an update which affected my Hyper-V virtual switch configuration .. somehow after some trails I was able to fix it mainly by disabling and removing one of the Hyper-V virtual switches added after the windows update
