### ISSUE TITLE
Build 14361:  Memory leak / issue in phantomjs

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/WSL#489]
One of my untiTests seemed to get stuck in phantomJS.  Task manager showed a consistent increase in memory usage:  
![image](https://cloud.githubusercontent.com/assets/966863/15910356/610d175c-2dc2-11e6-923f-9b9e7a736e6b.png)

I left it continue until it nearly hit 100% and killed it via ctrl+c in the bash shell:  
![image](https://cloud.githubusercontent.com/assets/966863/15910386/7d643764-2dc2-11e6-9b0e-55854e64ee59.png)

Steps to reproduce:

```
(install nodejs 6.2.1)
mkdir ./someDir
cd ./someDir
git clone https://github.com/hpcc-systems/Visualization.git
cd Visualization
git checkout candidate-1.10.x
npm install -g gulp
npm install -g bower
npm install -g jshint
npm install
bower install
sudo apt-get install phantomjs
npm test
```

Restarting that step reproduced the issue - but at a different test:

```
gulp unitTestBuildNonAMD
```

![image](https://cloud.githubusercontent.com/assets/966863/15910511/140e375a-2dc3-11e6-9b44-e6f80699ab12.png)

**Comment by sunilmut** [comment]
@GordonSmith - Thanks for reporting this and the detailed analysis. I tried to repro this on 14361, but the "npm test" command is failing with the error below. Any idea why?
![image](https://cloud.githubusercontent.com/assets/16765049/15978935/00495278-2f16-11e6-8558-39cf60a71a31.png)

**Comment by GordonSmith** [comment]
Looks like your ```npm install``` failed?

**Comment by sunilmut** [comment]
Yes, thanks. Had to install it with the -g option and it seems to work now. Onto the repro now.

**Comment by benhillis** [comment]
@sunilmut Any update on this investigation?
