### ISSUE TITLE
Wrong last modified date of a folder

### ISSUE THREAD

**Issue by jamesbomb** [microsoft/WSL#4890]
Microsoft Windows [Versione 10.0.18363.657]
Decompressing a folder I noticed there was something wrong with the last modified date.
```
$ mkdir test && tar -C test -xvf filename.tar.gz
[...]
./folder/style.css
./folder/_folder/
./folder/_notes/file.xml

$ ls -la --time-style=long-iso | grep test
drwxrwxrwx 1 user user        512 2017-10-04 14:05 test
```
![image](https://user-images.githubusercontent.com/3781735/74430770-d9218880-4e5d-11ea-86f8-265eb0e90d86.png)

Compressed folder does not cointain a file or folder that matches the last modified date 2017-10-04 14:05:

Using this function i check last modified dates:
`function find_old () { find "${1:-.}" -type f,d -printf '%TY-%Tm-%Td %TH:%TM %P\n' 2>/dev/null | sort | less }`

here you can see no date is matching 2017-10-04 14:05:
`find_last old 1000`
`2015-09-11 12:53 folder_2015_en/js`
`2017-03-07 15:49 folder_2015_en`
`2017-03-13 15:36 folder2/js/plugins`
`2017-03-13 15:36 folder2/js/plugins/_notes`
`2017-03-14 15:42 folder2/Fonts`
`2017-03-16 17:54 folder2/js`
`2017-03-28 18:13 folder_2015`
`2017-04-05 10:22 folder2/img`
`2017-05-30 12:47 folder_2017/css`
`2017-05-30 12:47 folder_2017/Fonts/_notes`
`2017-05-30 12:47 folder_2017/img`
`2017-05-30 12:47 folder_2017/js`
`2017-05-31 12:30 folder_2017/Fonts`
`2017-06-20 16:48 folder_2017_en/css`
`2017-06-20 16:48 folder_2017_en/css/_notes`
`2017-06-20 16:48 folder_2017_en/Fonts`
`2017-06-20 16:48 folder_2017_en/Fonts/_notes`
`2017-06-20 16:48 folder_2017_en/img`
`2017-06-20 16:48 folder_2017_en/img/_notes`
`2017-06-20 16:48 folder_2017_en/js`
`2017-06-20 16:48 folder_2017_en/js/_notes`
`2017-06-20 16:48 folder_2017_en/_notes`
`2017-06-20 17:02 folder_2017_en`
`2018-10-28 16:54 folder2/css`

**Comment by DHowett-MSFT** [comment]
Just to help paint a complete picture, can you share the output of `tar tvvf filename.tar.gz`? Tape archives occasionally contain an entry for `.`, which would of course apply to the directory into which you extracted it.

(Right now, we’re looking at the residual data without consulting the original source :))

**Comment by jamesbomb** [comment]
I've noticed it's exactly as you say.
`drwxrwxrwx root/root         0 2017-10-04 14:05 ./`
`-rwxrwxrwx root/root        28 2020-02-13 10:39 ./index.php`
`drwxrwxrwx root/root         0 2020-02-13 10:53 ./folder/`
`-rwxrwxrwx root/root      1823 2020-02-13 10:39 ./folder/404.php`
`-rwxrwxrwx root/root      4681 2020-02-13 10:39 ./folder/accordi.php`
`[...]`
I didn't know about it.
What is it due from?

**Comment by DHowett-MSFT** [comment]
That entry comes from the folder the archive was created from. Check it out!

```
$ mkdir hello
$ echo hi > hello/file         # Make a dummy file
$ touch -d "1989-08-28" hello  # Set the modification time on hello to 1989
$ ls -ld hello                 # verify the date
drwxr-xr-x 2 root root 4096 Aug 28  1989 hello
```

Then compress it

```
$ tar -c -v -f test_archive.tar -C hello .
./
./file
```

Then verify the contents

```
$ tar -t -v -v -f test_archive.tar
drwxr-xr-x root/root         0 1989-08-28 00:00 ./
-rw-r--r-- root/root         3 2020-02-18 16:51 ./file
```

Even though the file was created today, 2020-02-18, the folder it was in was last modified in 1989 (because we used `touch` to make that true). `tar` recorded that date. :smile:

**Comment by jamesbomb** [comment]
Now it's clear, you taught me a new thing! Thank you!
