### ISSUE TITLE
ruby started breaking suddenly with error ruby: invalid option -:  (-h will show valid options) (RuntimeError) for all versions of ruby

### ISSUE THREAD

**Issue by bhaskar-vineti** [microsoft/WSL#4891]
I am using Windows (WSL) as a primary machine for Ruby on Rails development so I use it daily for all my projects. It was working fine couple of days ago and suddenly ruby started breaking with below error. I could not able to find any other error logs other than what is below.

```bash
bhasky93@DESKTOP-IH9EFN5:~$ ruby
Traceback (most recent call last):
ruby: invalid option -:  (-h will show valid options) (RuntimeError)
```
### Tried below options to resolve the issue with unsuccessful outcome
- Tried running `ruby` command with for other ruby versions
- Uninstalled all of the exiting rubies and installed only ruby-2.5.1
- Uninstalled all the updates until last two days as it was working two days before 

Even after all of the above tries to resolve the issue I am getting the same error

### Option that I have not tried yet
- Resetting whole Ubuntu 18.04 LTS WSL as it contains my work so kept that option for last.

### Below is my windows build info
Edition: Windows 10 Pro
Version: 1909
Installed on: 07-06-2019
OS build: 18363.592

Please help!

**Comment by therealkenc** [comment]
Cannot repro on WSL1.

![image](https://user-images.githubusercontent.com/7049700/74468074-0f0b4080-4e4f-11ea-9b74-171bf2c5ca5f.png)

You will almost certainly get better eyeballs in a place where Ruby people hangout.

**Comment by sirredbeard** [comment]
I wonder if bash completion might be broken, ruby was aliased to something with incomplete --flags, or some other custom configuration gone wrong.

**Comment by therealkenc** [comment]
Yes, the `ruby: invalid option -` error is some ruby configuration gone wrong. "Uninstalling all of the exiting rubies" (which is not a well defined statement) will get you there. How to do that is not a WSL question. But short story, if you purge _all_ the ruby parts living in `/usr` tree, and _everything_ living in your `$HOME` directory related to ruby, and start over, you'll be okay. There is no need to reinstall your distro, but you can always resort to that. Bonne chance.

**Comment by bhaskar-vineti** [comment]
@therealkenc Thank you for looking into this. As you said, It looks like the issue with `ruby-2.7.0` as discussed in [asdf-vm/asdf-ruby/issues/154](https://github.com/asdf-vm/asdf-ruby/issues/154). It was happening because of the `RUBYOPT` set in `.bashrc` as mentioned in my comment [asdf-vm/asdf-ruby/issues/154#issuecomment-586684659](https://github.com/asdf-vm/asdf-ruby/issues/154#issuecomment-586684659). Thank you again for looking into this.

**Comment by i01107** [comment]
I don't know if this could give you any help. But, you can try to do what I did based on my finding.

Go to the root directory of your app. Run the `pwd` command and see if there's any space in the path. And based on your problem, it probably have a space prior to `:` char.

I renamed my folder name which containing the space, into something space-less, and everything works fine

I hope it can help
