### ISSUE TITLE
Windows subsystem for linux shell timeout

### ISSUE THREAD

**Issue by gxh1991** [microsoft/WSL#4893]
I am running a program which takes longer than the default shell timeout. I would like to change the value of the timeout setting. However, I don't see it anywhere in the shell setting.

**Comment by sirredbeard** [comment]
I would recommend `$ timeout 20s /usr/bin/command`

Run

`$ man timeout `

for more info on the timeout command.

**Comment by gxh1991** [comment]
Thank you! I will try it out

**Comment by sirredbeard** [comment]
If you're running a very complicated command, I would put it in a script of it's own:

`$ nano script.sh`

```
#!/bin/bash
exec /usr/bin/command --flag1 settingB --flag2 settingA
```
^C
Y

`$ chmod +x script.sh`

`$ timeout 30s ./script.sh`
