### ISSUE TITLE
ssh: Could not resolve hostname cs2.utdallas.edu: Name or service not known

### ISSUE THREAD

**Issue by XianWang1989** [microsoft/WSL#4894]
I want to connect to the local server through ssh from linux subsystem.

I use vpn on windows side. 

then I open ubuntu and do the ssh to my account, it said 'ssh: Could not resolve hostname cs2.utdallas.edu: Name or service not known' .

when I turn off the vpn and do the ssh again, it is OK.

Besides, when vpn is open, I can also connect to the server on windows side through putty.

I want to know what is wrong and how I can fix it.

Thank you very much.

**Comment by sirredbeard** [comment]
What kind of VPN is it?

Can you ping or traceroute to cs2.utdallas.edu with your VPN enabled?

Does your VPN block ssh traffic?

**Comment by XianWang1989** [comment]
I think I have found the alternative solution, I can ssh through IP address of the server, and I tried to modify resolv.conf nameserver priority, does not work either. Anyway, I can use it, that is OK.
