### ISSUE TITLE
WSL - non-http connection problem (111: Connection refused)

### ISSUE THREAD

**Issue by marceljay** [microsoft/WSL#4895]
WSL version:
 `Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1130-Microsoft Thu Nov 07 15:21:00 PST 2019`

`Microsoft Windows [Version 10.0.17134.1130]`

I cannot download from repositories with our firewall/proxy restrictions. 
```
After this operation, 381 kB of additional disk space will be used.
Err:1 https://archive.ubuntu.com/ubuntu bionic/main amd64 make amd64 4.1-9.1ubuntu1
  Could not connect to archive.ubuntu.com:443 (91.189.88.162). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:443 (91.189.88.31).
```
I suppose the cause is that the repository is only to be accessed via http. 
`https://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-9.1ubuntu1_amd64.deb` is not reachable.

What I can do:
`ping archive.ubuntu.com`
` curl https://google.com` but not
`curl http://google.com`

And also I can only do that after setting our proxy server via `export HTTP_PROXY=...`

The question would be then, how to access ressources via HTTP?

**Comment by sirredbeard** [comment]
If http is blocked, there are [several official mirrors](https://launchpad.net/ubuntu/+archivemirrors) that support https:

https://ftp.halifax.rwth-aachen.de/ubuntu/
https://ftp.lysator.liu.se/ubuntu/
https://mirrors.cs.wmich.edu/ubuntu/

Just search and replace the ubuntu.com links with one of the above. I tested the .de mirror above with https and it worked for me.

**Comment by marceljay** [comment]
Thanks for your help, but seeemingly, the problem lies somewhere else:

`
0% [Connecting to ftp.halifax.rwth-aachen.de (137.226.34.46)]
Err:1 https://ftp.halifax.rwth-aachen.de/ubuntu bionic InRelease
  Could not connect to ftp.halifax.rwth-aachen.de:443 (137.226.34.46). - connect (111: Connection refused)`
