### ISSUE TITLE
wsl2: fail to launch custom linux kernel on ARM64 devices through replacing file under lxss/tools/kernel

### ISSUE THREAD

**Issue by Frankdwu** [microsoft/WSL#4896]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [ 10.0.19546.1000]

Hardware: ARM64 devices 

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I installed wsl2 with ubuntu 18.04.  And I want to make a custom kernel with in-tree module ashmem and binder.  When I made the kernel and replace the default kernel in "C:\Windows\System32\lxss\tools\kernel" with my custom kernel and launch ubuntu distribution, it failed with error message The operation timed out because a response was not received from the virtual machine or container.
Following is the detail steps:
1. git clone https://github.com/microsoft/WSL2-Linux-Kernel.git
2. export KCONFIG_CONFIG=Microsoft/config-wsl
make menuconfig
make KCONFIG_CONFIG=Microsoft/config-wsl
update the config file to enable ashmem and binder according to following files
https://github.com/torvalds/linux/blob/master/drivers/staging/android/Kconfig
https://github.com/torvalds/linux/blob/master/drivers/staging/android/Kconfig
3.  wsl --shutdown
4. copy the arch/arm64/boot/Image file (i.e. custom kernel) to overwrite C:\Windows\System32\lxss\tools\kernel
5. launch ubuntu distribution but get error The operation timed out because a response was not received from the virtual machine or container.

* What's wrong / what should be happening instead:
The ubuntu distribution with the custom kernel should boot up successfully however it failed with error message  "The operation timed out because a response was not received from the virtual machine or container."
I checked the etl file, there is following info:
lxcore_service.etl error is "onecore\vm\wsl\lxss\lxcmdlineshared\hvsocket.cpp" and error code is "0x80370109"
lxcore_user.etl exception is "onecore\vm\wsl\lxss\wsl\main.cpp" and "0x80370109".

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
Not applicable

* For WSL launch issues, please [collect detailed logs]
Here is the etl files.
[lxcore_kernel_service_user.zip](https://github.com/microsoft/WSL/files/4204836/lxcore_kernel_service_user.zip)

**Comment by Biswa96** [comment]
Ooo... Now I see. Try the `Microsoft/config-wsl-arm64` one.

**Comment by Biswa96** [comment]
Try the `Microsoft/config-wsl-arm64` one.

**Comment by therealkenc** [comment]
/dupe #4802 ([message](https://github.com/microsoft/WSL/issues/4802#issuecomment-571694751)) to keep custom kernel ARM64 in one place.

**Comment by Frankdwu** [comment]
> Try the `Microsoft/config-wsl-arm64` one.

It works for me, thanks for your great support
