### ISSUE TITLE
[WSL2] localhost/hostname stopped working after Cumulative Update reboot, but linux IP still works

### ISSUE THREAD

**Issue by InfiniteLee** [microsoft/WSL#4897]
Build: 19041.21
Linux: Ubuntu 18.04.3 LTS

My windows auto-updated with KB4539080 last night and after it rebooted, I can no longer access webservers running in WSL2. Tested via webpack-dev-server, `SimpleHTTPServer`, and `nc`, in all cases I can no longer connect via any browser (chrome, firefox or edge) to http://localhost:[port] or http://[hostname]:[port], or via telnet (from windows). Telnet from within linux works correctly. 

I _am_ able to connect via the WSL IP, however (as obtained via `ip addr`). 

I am not sure if this update is specifically the problem as I have even uninstalled it but I am still running into the same issue.

**Comment by therealkenc** [comment]
/dupe #4885 as landing zone variation localhost not working
