### ISSUE TITLE
WSL2-Ubuntu [process exited with code 1] under updating 19564.1005

### ISSUE THREAD

**Issue by Coldrain1232008** [microsoft/WSL#4899]
As the title. I updated the insider version to 19564.1005. WSL2-Ubuntu cannot start. I got `[process exited with code 1]` error with Terminal-run.

![QQ截图20200215123656](https://user-images.githubusercontent.com/58802401/74581889-deaed800-4fef-11ea-9da4-af11872473e2.png)

**Comment by ShadowEO** [comment]
It seems very random as to whether it starts the instance, or fails to connect/start it still. I'm still alternating between both "The Windows Subsystem for Linux Instance has terminated." and the original connection error when attempting to launch a new session after running `wsl --shutdown`

**Comment by Yanbo** [comment]
I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

**Comment by Coldrain1232008** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

Woo! Thank you for the advice! It works!

**Comment by moye2014** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

thanks, the same as your

**Comment by panda361** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

It works! Thanks!

**Comment by chengpengzhao** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

Worked perfectly！ 👍

**Comment by chengpengzhao** [comment]
> > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> 
> Worked perfectly！ 👍

However, everytime when I reboot my computer, this problem appears again. 😢

**Comment by yanke1311** [comment]
> > > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> > 
> > 
> > Worked perfectly！ 👍
> 
> However, everytime when I reboot my computer, this problem appears again. 😢

if you have any solution? i meet the same situation as you. everytime i reboot, it will not work

**Comment by jernejg** [comment]
> > > > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> > > 
> > > 
> > > Worked perfectly！ 👍
> > 
> > 
> > However, everytime when I reboot my computer, this problem appears again. 😢
> 
> if you have any solution? i meet the same situation as you. everytime i reboot, it will not work

Mine too. I installed an then uninstalled zsh. And am stuck with [process exited with code 1] message now. Wsl shutdown and winsock reset do not work :/

**Comment by vonnyfly** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

It works, amazing!

**Comment by edmael** [comment]
> 
> 
> > > > > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> > > > 
> > > > 
> > > > Worked perfectly！ 👍
> > > 
> > > 
> > > However, everytime when I reboot my computer, this problem appears again. 😢
> > 
> > 
> > if you have any solution? i meet the same situation as you. everytime i reboot, it will not work
> 
> Mine too. I installed an then uninstalled zsh. And am stuck with [process exited with code 1] message now. Wsl shutdown and winsock reset do not work :/

Same here, my brain farted and I removed zsh without thinking too much.
Now either I manage to enter as root in that WSL Distro or I think I've got to rebuild it completely.

**Comment by aadibajpai** [comment]
Same issue, except `netsh winsock reset` and reboot didn't help. Just installed fish today and it was working fine until I did `exit` and it got stuck on `[process exited with code 1]` even though previous `exit`s had worked fine. Now WSL is completely unusable :(

**Comment by slo-ge** [comment]
I have the same problem. After exit wsl2 Ubuntu-20.04 the error occurred. Running `netsh winsock reset` did not do anything (with or without restarting). A fresh installation of Ubuntu-20.04 seemed to work first, but after exiting and reopening the same error occurred. But even if the error occurs the drive `\\wsl$\Ubuntu-20.04\`  is available, so something must be run in the background. Windows Build: `19041.330`, version `2004`.

**Comment by rahulrai-in** [comment]
Hi, I was getting the same error but in VSCode integrated terminal. This is how I solved it.
Check the default WSL distribution with `wsl -l --all`. I had `docker-desktop` set as the default distribution. Change the distribution to Ubuntu with `wsl --setdefault Ubuntu`. HTH.

**Comment by Semnodime** [comment]
### The Error Cause
**The error is the result of lauching `docker-desktop`** when it is set as your default WSL distribution.

### Solution 1
As @rahulrai-in pointed out, dou can simply set a default distro.

### Solution 2
Also, if you have multiple profiles in your windows terminal, you have to **provide a start-up command** for each terminal profile.

### Example
This settings.json _is not complete_ but should provide necessary information to update your win-term-settings.
`%localappdata%\Packages\Microsoft.Windos.Terminal._………………\LocalState\settings.json` ->
```
{
    "profiles":
    {
        "list":[
            {
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "commandline": "wsl -d Ubuntu-20.04"
            }
        ]
    }
}
```

**Comment by thisisbenmanley** [comment]
Still getting [process exited with code 1].
Guest: Ubuntu 18.04
Host: Windows version 2004, build 19041.329
WSL1 was working great forever, converted to WSL2 and got numerous errors but eventually only this one. `netsh winsock reset` and any amount of restarting never worked for me. Tried converting back to WSL1, still the same error. Going to do a full reinstall of Ubuntu starting in WSL2 because other threads have mentioned that working.

**Comment by rahulrai-in** [comment]
> Still getting [process exited with code 1].
> Guest: Ubuntu 18.04
> Host: Windows version 2004, build 19041.329
> WSL1 was working great forever, converted to WSL2 and got numerous errors but eventually only this one. `netsh winsock reset` and any amount of restarting never worked for me. Tried converting back to WSL1, still the same error. Going to do a full reinstall of Ubuntu starting in WSL2 because other threads have mentioned that working.

Did you try the options mentioned in the previous reply? https://github.com/microsoft/WSL/issues/4899#issuecomment-652064108

**Comment by thisisbenmanley** [comment]
> @thisisbenmanley Did you try the options mentioned in the previous reply? [#4899 (comment)](https://github.com/microsoft/WSL/issues/4899#issuecomment-652064108)

Yeah. Mine wasn't a docker problem at all, but yes I already had a default distro that was working previously, and adding a start-up command didn't work either.

**Comment by rahulrai-in** [comment]
> > @thisisbenmanley Did you try the options mentioned in the previous reply? [#4899 (comment)](https://github.com/microsoft/WSL/issues/4899#issuecomment-652064108)
> 
> Yeah. Mine wasn't a docker problem at all, but yes I already had a default distro that was working previously, and adding a start-up command didn't work either.

@thisisbenmanley from what you mentioned, it seems like your WSL2 is borked. I hope reinstalling WSL2 solves your problem.

**Comment by thisisbenmanley** [comment]
Confirming as others have confirmed in other threads - with WSL default version set to 2, running a new Ubuntu install worked.

**Comment by banyh** [comment]
In my case, this issue was caused by too long PATH.
Just remove most of the paths in Advanced System Settings of Windows and reboot again.
Then the WSL2 is working now.

### Environment

* Windows 10 version 2004, build 20161.1000
* WSL2 kernel: 4.19.121-microsoft-standard
* Ubuntu 20.04

**Comment by benhillis** [comment]
@banyh - could you please take a trace with the king path?

**Comment by dtriana** [comment]
> 
> Same here, my brain farted and I removed zsh without thinking too much.
> Now either I manage to enter as root in that WSL Distro or I think I've got to rebuild it completely.
> 
> EDIT: nvm, I managed to solve the issue by using `wsl --user root` and fixing zsh from there.

Can you elaborate or share a link on "fixing zsh from there"?, The reason I'm stuck here is because of uninstalling zsh ... Thanks

**Comment by benhillis** [comment]
@dtriana - either apt install zsh or modify your users shell with chsh.

**Comment by dtriana** [comment]
> @dtriana - either apt install zsh or modify your users shell with chsh.

Thanks @benhillis. For other non linux users like me, uninstalling zsh with apt-get doesn't reset the shell to bash, but since we already lost access to either shell, it is necessary to first get a new shell with that wsl --user root, and then run chsh -s /bin/bash [theUsernameOfYourUser] , then its all good again.

**Comment by 18874762262** [comment]
For me, it is caused by my `virtual memory` limitation. I have the error [process exited with code 1] when I'm loading or processing something, as I set the virtual memory size to default, my default ubuntu 18.04 seems to be fine.

**Comment by Dicondur** [comment]
> Hi, I was getting the same error but in VSCode integrated terminal. This is how I solved it.
> Check the default WSL distribution with `wsl -l --all`. I had `docker-desktop` set as the default distribution. Change the distribution to Ubuntu with `wsl --setdefault Ubuntu`. HTH.

Had the same issue with VS Code, the above solution worked, Thanks!

**Comment by Keydex** [comment]
Hello everyone! I had this issue running chsh to change my default shell and provided a shell that didn't exist, e.g. `/usr/bin/bash` when it should've been `/bin/bash` Any attempts to modify chsh would ask for a password and I could not access the WSL terminal in vscode or any other method.

To resolve this, you need to execute commands directly from the CMD.
For example this command
`wsl.exe -e chsh -s /bin/bash`
This `executes` the linux command `chsh` and changes the `shell` to `/bin/bash`

Now if it asks you for a password and says `PAM: Authentication failure` this is because the root user doesn't have a valid profile under passwd config to execute this command. We can temporarily disable this by accessing your WSL folder directory, mine is under `\\wsl$\Ubuntu-18.04\etc\pam.d` which you can type into explorer if your ubuntu instance is running. Edit the chsh file to change `auth       required   pam_shells.so` to `auth       sufficient pam_shells.so` and save the file.

You should now be able to run the wsl.exe command in CMD without a password prompt. I recommend you revert the chsh file back to required after making your change.

**Comment by menih** [comment]
I have the same issue. WSL v1 worked very well for me. Now I am completely unproductive. I tried the "netsh winsock reset " workaround suggested in this thread but it did not work for me. Can someone please send the steps to fix or revert back to WSL v1? I am desperate ...

**Comment by cartman8936** [comment]
@dtriana Thanks for sharing, Your solution  solved my problem

**Comment by menih** [comment]
I gave up on v2. I've converted my distos back to v1, and I am back in business.

**Comment by SSylvain1989** [comment]
Hello , same problem, i have try all solutions you have mentionne but sill stuck with process exited with code1

**Comment by menih** [comment]
This is severe enough, hitting so many users, I don't understand why dev / microsoft is not looking into it with high urgency.

**Comment by SSylvain1989** [comment]
All fine with a fresh install of ubuntu from microsoft store

**Comment by menih** [comment]
It seems like some customizations may possibly breaks wsl. It is important than that it will be properly documented.

In my case however, I did have a fresh install of Ubuntu-20.04 , after upgrading to wsl v2. But that does not work as it hits this issue. I have not customized anything special other than terminal colors, prompt and path. If this breaks wsl, something is really broken.

**Comment by codemee** [comment]
In my case, it's the fish shell was removed in unknown reason after I installed Docker Desktop. Just open a PowerShell and run
```
wsl -e /bin/bash
```
you can go into bash shell, then reinstall the missing fish

```
sudo apt install fish
```

that solved the problem.

**Comment by muktiwbw** [comment]
> > > > > > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> > > > > 
> > > > > 
> > > > > Worked perfectly！ 👍
> > > > 
> > > > 
> > > > However, everytime when I reboot my computer, this problem appears again. 😢
> > > 
> > > 
> > > if you have any solution? i meet the same situation as you. everytime i reboot, it will not work
> > 
> > 
> > Mine too. I installed an then uninstalled zsh. And am stuck with [process exited with code 1] message now. Wsl shutdown and winsock reset do not work :/
> 
> Same here, my brain farted and I removed zsh without thinking too much.
> Now either I manage to enter as root in that WSL Distro or I think I've got to rebuild it completely.
> 
> EDIT: nvm, I managed to solve the issue by using `wsl --user root` and fixing zsh from there.

Thank you! It worked for me

**Comment by mahdi-akbary** [comment]
I removed zsh from wsl distro then I got the error **[process exited with code 1]** , I managed to solve this by logging in to wsl using ` wsl --user root -d [distro name]` then running command `chsh --shell /bin/bash [username]` fixed the issue.

**Comment by michelle-lira** [comment]
In my case, this error happened in zsh uninstallation. 
I was able to solve it this way:
1 - uninstalling Ubuntu
2 - repeating wsl2 installation commands 
3 - and reinstalling Ubuntu. 

The "netsh Winsock reset" did not work on my machine.

**Comment by sachinlionel** [comment]
This helped to login to wsl  `wsl.exe -e chsh -s /usr/bin/bash`
Later found the /bin/ folder is empty. 
Any help in fixing bin folder is appreciated.

**Comment by stevenbrix** [comment]
@sachinlionel I just ran into the same issue

Does anyone know if a fresh install of Ubuntu wipes out the filesystem? I have some changes that I don't want to lose

**Comment by codemee** [comment]
Maybe you can try to manually install a fresh copy in any folder by
commands.

https://docs.microsoft.com/en-us/windows/wsl/install-on-server

Steve Kirbach ***@***.***> 於 2021年5月14日 週五 23:08 寫道：

**Comment by sachinlionel** [comment]
> @sachinlionel I just ran into the same issue
> 
> Does anyone know if a fresh install of Ubuntu wipes out the filesystem? I have some changes that I don't want to lose

I did a trick in my case it was ubuntu 20.04 and `/bin` folder was empty...
I first switch the bash by `wsl.exe -e chsh -s /usr/bin/bash`
Then installed ubuntu 18.04.
Then copied the bin folder from ubuntu 18.04 to ubuntu 20.04.
I know this is not the solution, but this is doing okay for my daily development.

**Comment by stevenbrix** [comment]
interesting, i tried something similar. `/bin/` in my Ubuntu distros seems to just be a link to `/usr/bin/` - so this doesn't work for me

**Comment by aarav2you** [comment]
I am getting same issue, my \\wsl$ directory is gone

**Comment by shettykaran21** [comment]
Having the same issue. Does reinstalling WSL2 delete all the files in my Ubuntu filesystem? I guess reinstalling WSL2 is the optimal solution for this but I don't want to lose all the projects I made which I stored in my Ubuntu system. I cannot even access the files of Ubuntu with \\wsl\$

**Comment by boYu07** [comment]
https://github.com/microsoft/terminal/issues/4573

**Comment by aniket-kale** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

It works! Thanks!

**Comment by CarloSOOHYooo** [comment]
open PowerShell then type **wsl -e bash** to use the bash shell, then replace the default shell using bash by typing **chsh -s /bin/bash**

**Comment by CarloSOOHYooo** [comment]
> As the title. I updated the insider version to 19564.1005. WSL2-Ubuntu cannot start. I got `[process exited with code 1]` error with Terminal-run.
> 
> ![QQ截图20200215123656](https://user-images.githubusercontent.com/58802401/74581889-deaed800-4fef-11ea-9da4-af11872473e2.png)

open powershell then type **wsl -e bash** to use the bash shell, then replace the default shell using bash by typing **chsh -s /bin/bash**

**Comment by dboyd42** [comment]
> 
> 
> > As the title. I updated the insider version to 19564.1005. WSL2-Ubuntu cannot start. I got `[process exited with code 1]` error with Terminal-run.
> > ![QQ截图20200215123656](https://user-images.githubusercontent.com/58802401/74581889-deaed800-4fef-11ea-9da4-af11872473e2.png)
> 
> **Open PowerShell** then **type** `wsl -e bash` to use the bash shell, then replace the default shell using bash by **typing** `chsh -s /bin/bash`

I wished I read this earlier.  I ultimately did the same thing, but logged in as **root** from **PowerShell** `wsl -d <distro> --user root`.  From there, switched user and ran the command to run the default shell: `su <normalUser> -s /usr/bin/bash`.  Then reinstalled **zsh** and changed the shell back to **zsh**: `sudo apt install zsh -y && chsh -s /usr/bin/zsh`.  The reason why I posted this is in case anyone else may need a reason to access the shell from within WSL as *root* and change the necessary configs.

**Comment by Udit8158** [comment]
> > I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.
> 
> Woo! Thank you for the advice! It works!

where I run this commend It not works

**Comment by elib0** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

Work fine !

**Comment by VladPetriv** [comment]
> In my case, it's the fish shell was removed in unknown reason after I installed Docker Desktop. Just open a PowerShell and run
> 
> ```
> wsl -e /bin/bash
> ```
> 
> you can go into bash shell, then reinstall the missing fish
> 
> ```
> sudo apt install fish
> ```
> 
> that solved the problem.

Thank a lot

**Comment by thecoffeedev** [comment]
> Hi, I was getting the same error but in VSCode integrated terminal. This is how I solved it. Check the default WSL distribution with `wsl -l --all`. I had `docker-desktop` set as the default distribution. Change the distribution to Ubuntu with `wsl --setdefault Ubuntu`. HTH.

This helped my issue. Thanks a lot! 😊

**Comment by paulathomas** [comment]
For me snapd had to be removed before do-release-upgrade

**Comment by eliecer507** [comment]
I had the same problem. I uninstalled `zsh ` from my terminal, but I had it as my default shell, so I got that error, and I couldn't do anything until I run the command `wsl --distribuiton Ubuntu-20.04 --user root` and reinstall `zsh` from my `CMD`. I worked from then on.

**Comment by Fogggy** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

Thanks a lot! It works! But after this command, you should restart pc.

**Comment by OMIDBIDBID** [comment]
> wsl --user root

this command worked for me.thanks

**Comment by kokabi1365** [comment]
If you came to the conclusion that you need to renistall the ubuntu, instead, **Reset** the app in the *Add or removes program.*

![Screenshot 2022-07-04 213222](https://user-images.githubusercontent.com/44271870/177196337-3fdc51d6-5faa-4ba6-a671-52d4f659864b.png)
![Screenshot 2022-07-04 213248](https://user-images.githubusercontent.com/44271870/177196349-57fa5141-1de0-460c-b063-457cccaa5061.png)

**Comment by iambenzaid** [comment]
open your terminal as administrator and type:  wsl -u root

and then execute this command: chsh -s /bin/bash **_your-username_**

restart terminal.

**Comment by Guiquan-27** [comment]
> open your terminal as administrator and type: wsl -u root
> 
> and then execute this command: chsh -s /bin/bash **_your-ubuntu-username_**
> 
> restart terminal.

It works! Thanks!

**Comment by hongy19** [comment]
i get this error not when starting WSL with windows terminal. WSL could start correctly but I get this error after windows recovery from sleep with this error"process exited with code 1 (0x00000001)"

does anything know how to solve it

**Comment by ledadu** [comment]
> 
Thanx 

Adding   "commandline": "wsl -d Ubuntu-20.04"   fix that :
 After add a new tab in windows terminal, the previous WSL was aborted.

**Comment by joxford531** [comment]
Incredible, had this issue this morning presumably after some update. Only way to fix was to uninstall Ubuntu through "Add or remove programs" and then unregister the distro in Powershell by running `wsl --unregister <distro>`

Not looking forward to having to reinstall all my command line tools and download all my repos.

**Comment by israelsgalaxy** [comment]
> I also have this issue, but by trying "netsh winsock reset" under admin, it solved the problem.

Thanks

**Comment by MSumonD** [comment]
I had the same issue on my Windows 11; none of the solutions mentioned above worked. I had to enable memory virtualization in the BIOS settings.
