### ISSUE TITLE
cannot complete installing any linux distribution, installation progran repeats "Enter new UNIX username:".

### ISSUE THREAD

**Issue by guyeu** [microsoft/WSL#4900]
**Microsoft Windows [版本 10.0.19559.1000]**

every time I install any linux distibution, I cannot finish enter username, see the picture. I didn't do any thing strange. btw, wsl2.

![image](https://user-images.githubusercontent.com/13718160/74587686-e5117400-5030-11ea-8654-8e81f13ee173.png)

**Comment by Biswa96** [comment]
There is a newer Windows 10 insider build 19564.1000. Please update the insider build and try again.

**Comment by sirredbeard** [comment]
Also, where are you installing them? I have seen people getting permissions errors after installing other than C:\ drive and if you can't create a new user it might be a permissions issue.

**Comment by onomatopellan** [comment]
It seems there is some problem with input on chinese Windows console.
User needs to be added manually like in https://github.com/microsoft/WSL/issues/5245#issuecomment-632067047

**Comment by therealkenc** [comment]
Duping for forward to #5245 which has the work-around. Thanks onomatopellan.
