### ISSUE TITLE
WSL 2 - Custom Kernel - Process exited with code 4294967295

### ISSUE THREAD

**Issue by microhobby** [microsoft/WSL#4904]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows Insider 19013
Microsoft Windows [versão 10.0.19013.1000]

I trying to run a custom vmlinux with WSL2
After more less a minute the return : "process exited with code 4294967295"

Is there any way to get kernel logs with earlycon or earlyprint on WSL2? I fear that without these logs I will not be able to solve a bug during the boot process of my Kernel

I try to get some info with the saved **lxcore_kernel.etl** but nothing on events logs
thanks in advance!

**Comment by Vincent-Ye** [comment]
I fixed same problem by "netsh winsock reset"

**Comment by Gonzoe79** [comment]
had the same issue, had docker installed with wsl2 feature enabled

> 
> 
> I fixed same problem by "netsh winsock reset"

uninstalling docker and running "netsh winsock reset" solved it for me

**Comment by ZetaoYang** [comment]
@microhobby 
Run `netsh winsock reset` as Administrator, then reboot your computer. 
The result like below:
```
❯ netsh winsock reset

Sucessfully reset the Winsock Catalog.
You must restart the computer in order to complete the reset.
```

**Comment by microhobby** [comment]
This was fixed by Kernel Mainline, it is now possible to use a custom kernel with the source of Linus Torvalds: https://youtu.be/N6b7DZKbvEE

**Comment by windowsair** [comment]
Great! Nonetheless, there are still some troubles to migrate to the new kernel version. I don't know if Microsoft has a new solution. . .

**Comment by forecho** [comment]
If you are having this problem caused by updating the system, you can try to restore the previous version of Windows 10 in the settings. This method works for me.

![image](https://user-images.githubusercontent.com/1725326/84615521-d3b37800-aefb-11ea-95ab-6f41da4aeec9.png)

**Comment by godie007** [comment]
the solution is to update the kernel https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by forecho** [comment]
@godie007 Thx, It work 🙇‍

**Comment by jpsneto** [comment]
> the solution is to update the kernel https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel


Even though I already had the newest version installed, it solved the problem

**Comment by wtadeubarros** [comment]
I had my  docker disabled on startup. Opening it up before starting the wsl2 solved the problem to me.

**Comment by spersico** [comment]
If someone comes 'till here and nothing worked like I did, know that I had the same error, and I then noticed that I had mistakenly deleted my custom kernel file (like an idiot), and WSL couldn't find it. So **changing back the wslconfig file to not use a custom kernel** might be the solution.

**Comment by MethodJules** [comment]
@spersico Can you explain that a little bit more? Where can I find the wslconfig file? Under C:\User\{User}\.wslconfig? And how can I determine not to use a custom kernel? Thanks in advanded.

**Comment by spersico** [comment]
@MethodJules in my case it's on `C:\Users\<MY_USER>\.wslconfig`
By default it uses the normal, non-custom kernel, I just removed the line which pointed to my kernel file, in my case, that was
`kernel=C:\\Users\\SP\\bzImage`
