### ISSUE TITLE
Can't access host server on epiphany-browser

### ISSUE THREAD

**Issue by saschanaz** [microsoft/WSL#4907]
* Your Windows build number: 19564

* What you're doing and what's happening: 

Prerequisite:

1. Install vcxsrv on Windows and run it.
2. Run `export DISPLAY=$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):0.0` on WSL2 Ubuntu to connect automatically.
3. Get `epiphany-browser` via `apt install`.

Steps:

1. On host Windows, run a simple local HTTP server e.g. using `node-static` on port 8080.
2. On WSL2, run `epiphany-browser` and access `(your host ip):8080`.

* What's wrong / what should be happening instead: It should access the local server, but instead it gets network timeout.

**Comment by therealkenc** [comment]
Works here. 

![image](https://user-images.githubusercontent.com/7049700/74878615-809a3180-531c-11ea-873d-df2965f67cd0.png)

**Comment by saschanaz** [comment]
Ah, seems it's just `node-static` by default not exposing to the local network. `static -a 0.0.0.0` works. Thanks!
