### ISSUE TITLE
Importing the distribution failed.

### ISSUE THREAD

**Issue by ChihweiLHBird** [microsoft/WSL#4909]
`Microsoft Windows [Version 10.0.19041.84]
`
Input at powershell:
`PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2`

Output:
`Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Importing the distribution failed.
./var/lib/gems/2.5.0/doc/test-unit-3.3.5/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.5/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.5/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.5/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/test-unit-3.3.5/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/strscan-1.0.3/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/stringio-0.1.0/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/stringio-0.1.0/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/stringio-0.1.0/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/stringio-0.1.0/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/stringio-0.1.0/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rdoc-6.2.1/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/rdoc-6.2.1/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rdoc-6.2.1/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rdoc-6.2.1/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rdoc-6.2.1/rdoc/fonts/Lato-RegularItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-RegularItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rake-13.0.1/rdoc/js/jquery.js: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/js/jquery.js' does not exist.
./var/lib/gems/2.5.0/doc/rake-13.0.1/rdoc/fonts/Lato-Light.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Light.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rake-13.0.1/rdoc/fonts/Lato-LightItalic.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-LightItalic.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rake-13.0.1/rdoc/fonts/Lato-Regular.ttf: Hard-link target './var/lib/gems/2.5.0/doc/webrick-1.6.0/rdoc/fonts/Lato-Regular.ttf' does not exist.
./var/lib/gems/2.5.0/doc/rake-13.0.1/rdoc/fonts/Lato-RegularItalic.ttf`

Wondering how to get the log.

**Comment by therealkenc** [comment]
Going to be same /dupe #4457.
