### ISSUE TITLE
Different behavior in syscall of execve

### ISSUE THREAD

**Issue by mikecovlee** [microsoft/WSL#4912]
* Your Windows build number:  10.0.18362.657

* What you're doing and what's happening:  refer to https://github.com/libmozart/system/issues/6

* What's wrong / what should be happening instead: refer to https://github.com/libmozart/system/issues/6

* Strace of the failing command, if applicable:  https://gist.github.com/mikecovlee/778edfe2c10889a257e6c82625134c3c

**Comment by mikecovlee** [comment]
@imkiva

**Comment by therealkenc** [comment]
The strace log is appreciated, but appears to be not threaded. Try:
```
$ strace -f -o yourprogram.strace yourprogram args...
```

> refer to
> refer to

The likelihood of someone from the community entertaining going through an external thread that does not have CLI repro steps is.... small. A repro would look like:

```
$ # a CLI step
$ # another CLI step
$ # ... as many CLI steps as necessary
$ strace -f -o yourprogram.strace yourprogram args...
```

That said, I did follow the links take a look at the `strace(1)` log. 

```
...
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7faba4d00a10) = 2521
close(10)                               = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=2521, si_uid=1000, si_status=SIGSEGV, si_utime=0, si_stime=0} ---
...
clock_gettime(CLOCK_REALTIME, {tv_sec=1582272082, tv_nsec=942656200}) = 0
write(4, "runtime.info();runtime.delay(500"..., 49) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=2520, si_uid=1000} ---
+++ killed by SIGPIPE +++
```

One of the clients is dying on a segfault. Which is a bad start. Then the parent dies on a `SIGPIPE`, which is understandable. Why the segfault I cannot tell you with the information provided. But this is more likely than not a userspace problem.

**Comment by mikecovlee** [comment]
Thanks for your responding. We have solved our problem now.
