### ISSUE TITLE
Ubuntu installation fails with error code 0x800700B7

### ISSUE THREAD

**Issue by Gskartwii** [microsoft/WSL#4913]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.657]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I'm trying to install Ubuntu from Windows Store. It is downloaded successfully. However, the installation fails, and when I click on "See details", I am faced with the following message (error code 0x800700B7):
![image](https://user-images.githubusercontent.com/6651822/75032264-d56eb100-54b0-11ea-9098-579a39cf5227.png)
The installation fails, and I'm unable to launch WSL:
![image](https://user-images.githubusercontent.com/6651822/75032335-03ec8c00-54b1-11ea-81fe-4ac34f7c136b.png)

* What's wrong / what should be happening instead:
I expected the installation to complete without displaying any error messages.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
I attempted to do this, but each of the commands fails with the error "Type mismatch.":

![image](https://user-images.githubusercontent.com/6651822/75032400-2e3e4980-54b1-11ea-9157-944679dd08c6.png)

**Comment by ad-on-is** [comment]
What happens if you run `wsl` only?
What's the output of `wsl -list`?
If previous command shows a list, does `wsl -d <distro>` work?

**Comment by Gskartwii** [comment]
```
C:\Users\aleks>wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

C:\Users\aleks>wsl --list
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

FWIW, prior to this I attempted a remove a legacy installation of WSL using `LxRun /uninstall`, which resulted in an error code (which I sadly don't remember anymore).

**Comment by ad-on-is** [comment]
I don't know what your command did there. Another way would be downloading the gz file of ubuntu and import it with `wsl --import`

Here's the official WSL version of Ubuntu 19.10
https://cloud-images.ubuntu.com/eoan/current/eoan-server-cloudimg-amd64-wsl.rootfs.tar.gz

**Comment by Gskartwii** [comment]
That method of installation seems to have worked. Thanks a lot!

Should I leave this issue open? Installation from Windows Store still doesn't work, which doesn't seem right to me.

**Comment by feoh** [comment]
Please do leave it open. I hit the same error and was similarly stumped.

**Comment by therealkenc** [comment]
Forward /dupe #5724 as new LZ

**Comment by therealkenc** [comment]
#5724 is outright corrupt; different scenario. Reversing the dupe, apologies, nvm.
