### ISSUE TITLE
WSL unable to terminate process because of node

### ISSUE THREAD

**Issue by RootAndroid58** [microsoft/WSL#4914]
I installed node.js in wsl and while running the code for 2 -4  hrs the wsl freezes and nothing works the processhacker cannot stop the node process tried everything the Lxssmanager is just stuck unable to create a dump file too access denied for both lxssmansager and node  

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) Microsoft Windows [Version 10.0.18363.657]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.) can help me with that this occurs to me daily so needed help in creating dump file

* What's wrong / what should be happening instead: simply run the node.js (discord.js bot ) it just gets stuck while restarting the bot or while running the bot

**Comment by ad-on-is** [comment]
Without knowing what discord.js actually does, I'd suggest trying some other nodejs server, something simpler and see what happens. Whether you can terminate or let it run for a longer period of time.

Also, are you on WSL 1 or WSL 2?
