### ISSUE TITLE
"swapoff -a" returns error code 255 on Ubuntu 16.04 and WSL 2.

### ISSUE THREAD

**Issue by zxli** [microsoft/WSL#4918]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.19035.1

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
sudo swapoff -a

* What's wrong / what should be happening instead:
The command "sudo swapoff -a" returns error code 255. I'm trying to configure Kubernetes with kubeadm. My understanding is kubeadm requires "swapoff -a" to work.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/75101040-7c278000-558b-11ea-9215-905fde9b8463.png)

**Comment by zxli** [comment]
I installed Windows 10 Preview 19035 on a VM by ISO. Enabled nested virtualization for the VM. Installed Ubuntu 16.04 LTS from Microsoft Store app on the VM. Enabled WSL 2 on the VM. Then it seems to be a straight repro. Here is the screenshot. I'm very new to Linux. Correct me if I did anything wrong.
![image](https://user-images.githubusercontent.com/8853749/75641420-0a83ad80-5bed-11ea-84f5-09ab44f668a2.png)

**Comment by therealkenc** [comment]
Thanks. See it now. Your missing `strace(1)`:

```
swapoff("/swap/file")                   = -1 ENOENT (No such file or directory)
getuid()                                = 0
geteuid()                               = 0
getgid()                                = 0
getegid()                               = 0
prctl(PR_GET_DUMPABLE)                  = 1 (SUID_DUMP_USER)
stat("/etc/fstab", {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
openat(AT_FDCWD, "/etc/fstab", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
read(3, "LABEL=cloudimg-rootfs\t/\t ext4\tde"..., 4096) = 43
read(3, "", 4096)                       = 0
close(3)                                = 0
close(1)                                = 0
close(2)                                = 0
exit_group(-1)                          = ?
```

![image](https://user-images.githubusercontent.com/7049700/75642785-97306a80-5bf1-11ea-86e8-5f120bbe2ffb.png)

This is probably de-facto by-design. The VM is shared among all the running WSL2 distros, and by extension, so is the swap file. Looks like you can [turn it off](https://docs.microsoft.com/en-us/windows/wsl/release-notes) via `%UserProfile%\.wslconfig` `swap=0`.

**Comment by hobin2017** [comment]
> Thanks. See it now. Your missing `strace(1)`:
> 
> ```
> prctl(PR_GET_DUMPABLE)                  = 1 (SUID_DUMP_USER)
> openat(AT_FDCWD, "/proc/swaps", O_RDONLY|O_CLOEXEC) = 3
> fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
> read(3, "Filename\t\t\t\tType\t\tSize\tUsed\tPrio"..., 1024) = 97
> read(3, "", 1024)                       = 0
> close(3)
> swapoff("/swap/file")                   = -1 ENOENT (No such file or directory)
> [...]
> prctl(PR_GET_DUMPABLE)                  = 1 (SUID_DUMP_USER)
> stat("/etc/fstab", {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
> openat(AT_FDCWD, "/etc/fstab", O_RDONLY|O_CLOEXEC) = 3
> fstat(3, {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
> read(3, "LABEL=cloudimg-rootfs\t/\t ext4\tde"..., 4096) = 43
> [...]
> exit_group(-1)                          = ?
> ```
> 
> ![image](https://user-images.githubusercontent.com/7049700/75642785-97306a80-5bf1-11ea-86e8-5f120bbe2ffb.png)
> 
> This is probably de-facto by-design. The VM is shared among all the running WSL2 distros, and by extension, so is the swap file. Looks like you can [turn it off](https://docs.microsoft.com/en-us/windows/wsl/release-notes) via `%UserProfile%\.wslconfig` `swap=0`.

There is the [reference](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) for configuring swap in win10-wsl.
