### ISSUE TITLE
interop hangs inside sshd session initiated by Win32-OpenSSH client

### ISSUE THREAD

**Issue by therealkenc** [microsoft/WSL#4922]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

19569 WSL2

* What you're doing and what's happening

Start `sshd` in Ubuntu 18.04
```
$ sudo apt install openssh-server
$ sudo service ssh start
```

From a Windows CMD prompt, `ssh` into WSL and run a win32 command via WSL interop:

![image](https://user-images.githubusercontent.com/7049700/75111666-5fbe2e80-55f1-11ea-914e-93cd3019b01e.png)

* What's wrong / what should be happening instead:

The `cmd.exe /c echo` hangs and does not respond to Ctrl-C on the pty. `wsl.exe --shutdown` or `SIGINT`/`SIGTERM` on the PID recovers.

* Strace of the failing command

Here is the [gist](https://gist.github.com/therealkenc/c8003ab03388714d9c7b18d34a17c146).

[edit: more plausible strace interpretation]
The command loops on a `poll()` of (looks like) parent `fd 0,7,8,9` and `AF_VSOCK fd 4`, maybe (?) doing some sort of keepalive exchange.

```
193   execve("/mnt/c/Windows/System32/cmd.exe", ["/mnt/c/Windows/System32/cmd.exe", "/c", "echo", "test"], 0x7ffe028f2430 /* 19 vars */) = 0
...
193   socket(AF_VSOCK, SOCK_STREAM|SOCK_CLOEXEC, 0) = 4
193   bind(4, {sa_family=AF_VSOCK, sa_data="\0\0\377\377\377\377\377\377\377\377\0\0\0\0"}, 16) = 0
...
193   poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1) = 1 ([{fd=0, revents=POLLIN}])
193   poll([{fd=0, events=POLLIN}], 1, -1) = 1 ([{fd=0, revents=POLLIN}])
193   read(0, "\3", 4096)               = 1
193   write(6, "\3", 1)                 = 1
193   poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1
```

I suspect but can't prove the problem is related to [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases) aka [OpenSSH in Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview) and ConPTY. The problem does not manifest with a `ssh localhost` inside WSL, or`ssh` from an external Linux box (say from a VM). This is blocking a generic resolution of question #4911.

**Comment by DHowett-MSFT** [comment]
This is probably resolved with the 8.x builds of the Win32-OpenSSH client. On startup, in “inherit cursor” mode, ConPTY blocks until it receives a cursor location. Old versions of W32-OpenSSH implemented their own VT input stack that couldn’t send the cursor position escapes.

**Comment by DHowett-MSFT** [comment]
This does mean that any SSH client running in a terminal that doesn’t support the DEC cursor position report request will experience a similar failure.

**Comment by therealkenc** [comment]
Yep. Thanks for the quick answer Dustin.

![image](https://user-images.githubusercontent.com/7049700/75133769-d52d0c00-5690-11ea-8473-99388498e31e.png)
