### ISSUE TITLE
sudo echo "test" takes 25 Seconds on WSL 2

### ISSUE THREAD

**Issue by AGollapalli** [microsoft/WSL#4923]
* Windows build number:  Version 10.0.19041.84

* WSL Version: 2

* WSL Distribution: Ubuntu

* What I'm doing and what's happening:  `sudo echo "test"` takes 25 seconds. Should be near instant.
![image](https://user-images.githubusercontent.com/19639507/75119332-92931180-5647-11ea-9bf0-69458eb5dc22.png)

I suspect this might be related to https://github.com/microsoft/WSL/issues/2477

**Comment by sirredbeard** [comment]
Unable to reproduce here:

![image](https://user-images.githubusercontent.com/33820650/75119697-3df59380-5653-11ea-9d92-3adec127a5e8.png)

What distro and version are you on? `$ cat /etc/os-release'

**Comment by AGollapalli** [comment]
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Focal Fossa (development branch)"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by AGollapalli** [comment]
When you do detailed logging are you supposed to do the listed commands in the same directory as the command you're logging? I made these in an administrative powershell window, while I reran the `time sudo echo "test"` command in my WSL window.

**Comment by AGollapalli** [comment]
I tried to do the detailed logging as recommended in CONTRIBUTING.md, Hope these help:

[Logs.zip](https://github.com/microsoft/WSL/files/4242424/Logs.zip)

**Comment by therealkenc** [comment]
Try this see if it helps:
```
$ export PATH=/usr/bin:/bin:/usr/sbin:/sbin
$ sudo bash -c "/bin/echo test"
```

If that is faster then the problem is probably going to be something undisclosed in your `.bashrc`. If as a side effect of the command being run there is a lot of 9p activity (ie: on `/mnt/c`) then performance goes to pot.

> I tried to do the detailed logging as recommended in CONTRIBUTING.md

Per the template, the lxcore logs are useful for tracking down launch issues, which this is not. You might be able to glean where the command is spending its time with an `strace(1)`.

```
$ sudo strace -f -tt -o echo.strace time sudo echo test
```

**Comment by therealkenc** [comment]
Its not focal at least. Something local.

![image](https://user-images.githubusercontent.com/7049700/75124132-0d692600-5662-11ea-8ebb-bc03fa148cc8.png)

**Comment by AGollapalli** [comment]
Apologies, It was something in my bash file. Something about dbus and setting the display variable. Evidently I thought you had to do that and you don't.

![image](https://user-images.githubusercontent.com/19639507/75130458-09ee9280-5694-11ea-82e5-049e1e3b32ee.png)

Closing the issue.
