### ISSUE TITLE
xclip fails with Error: Can't open display: (null)

### ISSUE THREAD

**Issue by sinapis** [microsoft/WSL#4933]
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.84]

* What you're doing and what's happening:  
```
sudo apt install xclip
echo 111 > xclip
```

* What's wrong
nothing was copied. instead the following error message appeared:

`Error: Can't open display: (null)`
* What should be happening instead: 111 copied to clipboard and shared in windows as well.

* Strace of the failing command, if applicable:  https://gist.github.com/sinapis/c63332ce3c8e801d3fb14d65646007ef

I'm trying to make xclip work so I can use 3rd parties programs like [micro](https://github.com/zyedidia/micro#linux-clipboard-support) which rely on xclip to copy the clipboard.

**Comment by therealkenc** [comment]
Your `$DISPLAY` is not set. 
```
$ export DISPLAY=<x11-server-ip>:0
```
Similar #2975 see #646 ([message](https://github.com/microsoft/WSL/issues/637#issuecomment-392989799)) et al. You'll need an X Server of choice (such as [VcXsrv](https://sourceforge.net/projects/vcxsrv/)) listening on `<x11-server-ip>`. Watch out gotcha #4106 aka #4619 on WSL2.

**Comment by dwmkerr** [comment]
Unfortunately I couldn't get this to work either. My approach was to fall back on this:

```sh
alias pbcopy="clip.exe"
alias pbpaste="powershell.exe -command 'Get-Clipboard' | sed -e 's/\r\n$//g'"
```

More details at https://github.com/Microsoft/WSL/issues/1069#issuecomment-664468853

**Comment by gastonfun** [comment]
Hi, its my first post and cuestion and problem, pls Help me! 
I´m Gaston, from Buenos Aires Argentina. 
Ok the problem is whit adding ssh key to git agent. y cant copy i tried all ....
Like sinapis ...I'm trying to make xclip work so I can use 3rd parties programs like micro which rely on xclip to copy the clipboard.
But no way! cant copy my key. here is a capture from Ubuntu server 20 HA! I´ve installed MAAS over ubuntu its allfine Help Help Help! y nooooob in this im learning plis helpis :D
![VirtualBox_UbuntuServer_25_09_2020_19_49_11 ssh key](https://user-images.githubusercontent.com/32093380/94322497-270c7c00-ff69-11ea-9da4-39b475842b59.png)

**Comment by gastonfun** [comment]
> Hi, its my first post and cuestion and problem, pls Help me!
> I´m Gaston, from Buenos Aires Argentina.
> Ok the problem is whit adding ssh key to git agent. y cant copy i tried all ....
> Like sinapis ...I'm trying to make xclip work so I can use 3rd parties programs like micro which rely on xclip to copy the clipboard.
> But no way! cant copy my key. here is a capture from Ubuntu server 20 HA! I´ve installed MAAS over ubuntu its allfine Help Help Help! y nooooob in this im learning plis helpis :D
> ![VirtualBox_UbuntuServer_25_09_2020_19_49_11 ssh key](https://user-images.githubusercontent.com/32093380/94322497-270c7c00-ff69-11ea-9da4-39b475842b59.png)

y Tried this: https://www.digitalocean.com/community/questions/copy-ssh-key-to-clipboard
i´ve folowed this directions: https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by sinapis** [comment]
for now i'm using this as workaround:
https://github.com/microsoft/WSL/issues/4852#issuecomment-606497383

**Comment by evandrouzeda** [comment]
I use 
`xclip -d :0 -i test.txt -selection clip`
and work for me

**Comment by koushik355** [comment]
Not related to Xclip but you want to copy anything on WSL. Use `clip.exe`
Something like this

`cat testing.txt | clip.exe`

The content of `testing.txt` will be copied in the clipboard in this case.

**Comment by 8brandon** [comment]
> Not related to Xclip but you want to copy anything on WSL. Use `clip.exe`
> Something like this
> 
> `cat testing.txt | clip.exe`
> 
> The content of `testing.txt` will be copied in the clipboard in this case.

best comment!

**Comment by koushik355** [comment]
On another note, you can pretty much access many windows services from WSL itself. 
Like 
`explorer.exe .` would open the file explorer from your current dir that you're on WSL. 
You will have to find the `.exe` that you run from the `Run` and you can execute it in WSL.

**Comment by sinapis** [comment]
xclip on wsl2 requires xserver and I had corruption with clip.exe. That's why I use utf8clip. See https://github.com/microsoft/WSL/issues/4852#issuecomment-606497383
