### ISSUE TITLE
Unable to access windows localhost from WSL2

### ISSUE THREAD

**Issue by Ju-ch** [microsoft/WSL#4935]
As I said in the title, when I tried to use the windows localhost data in wsl2, I could neither obtain it through **127.0.0.1**, nor access it according to the **nameserver** in `cat /etc/resolv.conf`.

![image.png](https://i.loli.net/2020/02/27/bFtyBuv24ozlLfq.png)

My windows system version : 19041.84
WSL2 : Ubuntu

**Comment by therealkenc** [comment]
> nor access it according to the nameserver in cat /etc/resolv.conf

You have a 'nor' in there that doesn't match the title.

Two things. Make sure the Windows server is listening on the right addresses; listening on `0.0.0.0` being the easy win (ref #4907). The IP address you want to use for the client is the one marked "`(Preferred)`" in win32 `ipconfig /all`. It isn't clear the `resolve.conf` guidance being given works in all setups.

**Comment by Ju-ch** [comment]
> Two things. Make sure the Windows server is listening on the right addresses; listening on `0.0.0.0` being the easy win (ref #4907). The IP address you want to use for the client is the one marked "`(Preferred)`" in win32 `ipconfig /all`. It isn't clear the `resolve.conf` guidance being given works in all setups.

Thx, your answer helped me, and it also resolved my doubts.

Thanks again

**Comment by iongion** [comment]
I still have it in **Insider build** `19645`

- above is a msys shell in windows native
- under is wsl2 shell

![image](https://user-images.githubusercontent.com/867609/84981814-ace08600-b135-11ea-96f6-d4a66783bf8c.png)

- Windows firewall is down
- Postgress is set to allow connections from everywhere `host    all             all             0.0.0.0/0               md5`

**Comment by iongion** [comment]
To answer to my own post - it does not work like this, wsl2 needs the ip of the adapter not localhost :(

... see here https://superuser.com/questions/1536619/connect-to-mysql-from-wsl2
