### ISSUE TITLE
Linux subsystem randomly freezes after a few minutes 

### ISSUE THREAD

**Issue by jackyjkchan** [microsoft/WSL#4936]
I am using Microsoft Windows [Version 10.0.18363.657]
I launch the subsystem using the Ubuntu app from start menu, app version is 1804.2019.521.0

This issue has occurred from doing just about doing anything, to list a few, running "exit" in the ubuntu shell, exiting from vi, attempting to run vi. Installing python packages with pip, typing into shell... 
It sometimes even freezes right when i start the ubuntu shell. 

I would expect the shell to not randomly freeze.

I'll attach logs after i restart my computer. When this happens my entire computer becomes very slow and the CPU usage shoots to 100%. 

I've attached the error logs, i added a .log to the name so github would let me attach them. 
I also added a screen shot showing what processes seem out of place when this bug happens. 
After the freeze happened I tried to terminate WSL through cmd prompt. 
The "The Windows Subsystem for Linux instance has terminated" message appears after i run esl --terminate Ubuntu on command prompt. 

![WSL_Issue_Hanging](https://user-images.githubusercontent.com/16214863/75501829-0d895e80-599f-11ea-8731-2555da573636.PNG)

[lxcore_kernel.etl.log](https://github.com/microsoft/WSL/files/4264851/lxcore_kernel.etl.log)
[lxcore_service.etl.log](https://github.com/microsoft/WSL/files/4264852/lxcore_service.etl.log)
[lxcore_user.etl.log](https://github.com/microsoft/WSL/files/4264853/lxcore_user.etl.log)

**Comment by JudeLiu** [comment]
I'm experiencing exactly the same as you did, dude. I'm almost about to totally uninstall my WSL. It just drives me crazy with the never-stopping fan.

**Comment by afichou** [comment]
Same here, for a couple of computers since wednesday.

**Comment by jackyjkchan** [comment]
Oh to add to @JudeLiu's comment , I've also tried uninstalling and reinstalling WSL. My Ubuntu WSL install is fresh as of yesterday. So freshly reinstalling WSL doesn't help. 

By reinstalling i did the following:
wsl --unregister Ubuntu **on cmd prompt
disable windows linux subsystem option in control panel "Add and remove windows features"
restart computer
re enable
restart computer
install Ubuntu app from windows store.

**Comment by hevanlee** [comment]
This exact same issue happened to me as well. About 6 or so init processes stay in the background after I close terminal, each taking approx 15% CPU usage. I've tried disabling and re-enabling wsl, reinstalling several times, using Debian GNU instead, and deleting and replacing the lxss folder in system32 with one from another computer but nothing seems to work.

**Comment by vcristal** [comment]
I’m having the same exact issue.

**Comment by pmkays** [comment]
Also having the same issue and have tried reinstalling WSL Ubuntu multiple times. I've also got multiple init and bash files running that are taking up huge chunks of CPU; restarting the computer every time it freezes seems to be a temporary fix but it's a huge pain.

**Comment by vcristal** [comment]
You can not eve use task manager to close those processes and as previously said you have to restart the computer to get rid of them.

**Comment by LuthfiArfi** [comment]
I am having the same issue. My issue happened after i upgraded my wsl. now every time my wsl freeze i need to full reboot my laptop to make sure that init and bash in task manager is gone. hope they can get rid of this bug

**Comment by aussourd** [comment]
Hi guys,
I got exactly the same issue. 
It started right after I loaded the latest Windows update (Version 1909, OS Build 18363.693).
First, I supposed, I broke something under WSL or a bad mix with the new Windows version.
Thanks to this post, I can say it's not the case.
I hope MS will find a way to correct this issue because, as you all, I need to go ahead in my work.
Good weekend however ...

**Comment by pmkays** [comment]
What WSL and version are you all using?

**Comment by jackyjkchan** [comment]
I am using the Ubuntu app from the Microsoft app store. 1804.2019.521.0. I don't think this is the issue however as my desktop is also using this version and has not seen any issues. 
My laptop Windows OS is on build is 18363.693 (where i am observing seeing WSL issues).
Desktop build is 18363.657 where i have no issues.

**Comment by pmkays** [comment]
@jackyjkchan Over night I upgraded my Windows OS to Version 1909 18363.657 but I'm still having the same issue. My Ubuntu app from the app store is also 1804.2019.521.0

**Comment by jackyjkchan** [comment]
@pmkays well then, let us both pray to the engineers at Redmond and hope they notice us.

**Comment by JudeLiu** [comment]
@jackyjkchan my laptop OS version is 1909 build 18363.693 but still have this problem, and use Ubuntu 18.04 LTS app downloaded from win store.

I tried to reinstall WSL. I uninstalled it from setting, download ubuntu app from store again.
But when I install it, four _init_ processes are spawned again, just like before.

SAD

**Comment by aussourd** [comment]
Hi,
I run WSL 1, so I think it's time to make the leap toward WSL V2.
Hope it will be easy to preserve my environment.
Bye

**Comment by LuthfiArfi** [comment]
> Hi,
> I run WSL 1, so I think it's time to make the leap toward WSL V2.
> Hope it will be easy to preserve my environment.
> Bye

is it already on stable version?

**Comment by WillemLT** [comment]
I've exactly the same.
Running Windows 10 Pro Version, OS Build 18363.693

It's appearing after few minutes of use, sometimes during boot already. It feels a bit unpredictable when it use.
It can happen with different commands (nano, whois, ping).
When it freeze I have the same CPU behaviour as jackyjkchan. Some process become in a suspended state and only with a restart I can get my PC stable again.

I mainly use the Ubuntu app as well, but even using the wsl command via powershell let them crash. As well as the Debian repro.

![2020-03-01 16_43_47-Task Manager](https://user-images.githubusercontent.com/61658716/75628714-f5eae980-5bdb-11ea-9cd9-49f4c64804e9.png)

With the suspended processes.
![2020-03-01 16_45_03-Task Manager](https://user-images.githubusercontent.com/61658716/75628717-07cc8c80-5bdc-11ea-965c-ca8baa7df9b7.png)

**Comment by Pugabyte** [comment]
Using Intellij to run a bash script with WSL, after launching the WSL is frozen, my CPU is at 100% and the processes are unkillable. 

https://i.gyazo.com/11989e804e5e77802255e0f0161b25cb.gif
https://imgur.com/a/imCb9JW

**Comment by youcanyoudown** [comment]
I have exactly the same issue after updating the system.. I tried many ways but failed. Hope some heroes save us!

**Comment by fred-the-coder** [comment]
Same issue here....
Running a Windows update to try to solve the issue after the latest update. 
February update, not mandatory, has been detected, thus updating.
Crossing finger for the issue to be solved.
I'll keep you post if issue is solved after Windows Update...

**Comment by WillemLT** [comment]
I moved via Windows Insiders Program to (slow release track) build 19041.113
This is the version which supports as well WSL 2.
However for WSL 1 it seems to have a positive effect as well. 
Seems like it solves the issue on my side.

**Comment by vpeng2016** [comment]
Having the exact same issue- bash freezes after a few minutes of work with multiple instances of init and bash which consume a ton of CPU. Unfortunately Windows Update (windows-10-update-kb4535996) does not seem to fix the problem

**Comment by youcanyoudown** [comment]
> I moved via Windows Insiders Program to (slow release track) build 19041.113
> This is the version which supports as well WSL 2.
> However for WSL 1 it seems to have a positive effect as well.
> Seems like it solves the issue on my side.

I used this method and indeed the Windows Insiders Program 19041.113 fixed my issue.

**Comment by JudeLiu** [comment]
This problem forced to me to join windows insider preview and it's fixed.
Maybe this is what exactly MS wants us to do

**Comment by GiancarloZ** [comment]
HI, did this resolve it for everything? I'm having same exact issue. Even tried using Debian instead of Ubuntu and got same problem. What exactly is the Windows Insider Program?

**Comment by GiancarloZ** [comment]
> I moved via Windows Insiders Program to (slow release track) build 19041.113
> This is the version which supports as well WSL 2.
> However for WSL 1 it seems to have a positive effect as well.
> Seems like it solves the issue on my side.

What do you mean by "moved via Windows Insiders Program to (slow release track) build 19041.113". I joined insider program and updated to what showed up.

**Comment by GiancarloZ** [comment]
Works for me as well! Just join Windows Insiders Program and update.

**Comment by Lei-Guo** [comment]
Same problem. I spent the entire weekend trying to figure out what was going on. Windows Insiders Program may not be worth it for some computers as it sometimes causes system crash, driver issues and so on. Let's just hope MS will fix the problem in the next update.

**Comment by kavi9030** [comment]
I have the same issue. Is there any other solution rather than joining Windows Insiders Program and update?

**Comment by PdoubleU** [comment]
The same problem appears on my PC. It has begun a few days ago after one full day of working with WSL and code editor. Now I enrolled in Windows Insiders - I am updating my windows 10. I'll let You know if it works in my case.

**Comment by AleG94** [comment]
Same issue here, works for a few minutes then stuck with 100% cpu. Only full restart helps.

**Comment by PdoubleU** [comment]
After update to 19041.113 os version (windows insider program, slow option) the problem disappeared (few hours without mentioned previously issue) - WSL works so far.

**Comment by nicopatronelli** [comment]
I had the same problem (several init process running, CPU at 100%) but after update Windows 10 to 1909 (latest update) through Windows update page the problem was solved. 

Note: Reinstalling WSL or Ubuntu through Microsoft Store don't solve the problem.

**Comment by giannisdravilas** [comment]
I face exactly the same problem with both 18363.657 and 18363.693 versions of Windows 10-1909 on my laptop. I have tried using all the different versions of Ubuntu WSL available on the Microsoft Store, uninstalling and reinstalling each one of them multiple times, updating my OS version, as well as creating a new Windows User profile. The Ubuntu WSL terminal keeps completely freezing randomly, sometimes when it starts and some other times during using it. Every time this happens the terminal becomes completely unusable and several init and bash processes appear using 100% of the CPU, causing the whole system to lag. They can not be terminated through Task Manager and the only - temporal - solution seems to be restarting the whole computer.

**Comment by SvenGroot** [comment]
Can one of the people who are having this issue please trigger a full crash dump using the instructions [here](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting?redirectedfrom=MSDN#bash-is-hung). When you send the dump to secure@microsoft.com, please indicate the dump is for Sven Groot.

**Comment by giannisdravilas** [comment]
The issue seems to have been resolved, at least for me, by following the answer in the question I asked here: https://askubuntu.com/questions/1215167/windows-10-ubuntu-wsl-freezes-randomly.

**Comment by SvenGroot** [comment]
The Virtual Machine Platform feature should not affect WSL1 at all. Especially on 1903/1909 WSL should have no ties to that feature at all.

I would still prefer it if someone who's seeing this problem could trigger a crash dump as described above before trying to apply any workaround, so we can get an idea what the cause of this issue is.

**Comment by fred-the-coder** [comment]
Hello Sven,
Thank you for taking care of this issue...
Instructions to provide a dump are quite....complicated...especially the first step : "Change the memory dump type to "complete memory dump". While changing the dump type, take a note of your current type."
How to do that?

I applied  giannisdravilas workaround which seems to have a positive effect so far. Admit that for a non Windows OS person WSL and Virtual Machine are not that far...

Also, even if it has no direct link to this issue, I have in mind WSL (1) is in "beta mode"?...meaning it is a (nice) feature provided by MS but you decline any issue causes by this feature...am i right?

If time permits, and you answer my first point (!), I will remove the workaround and try to provide a dump, but no guaranty, even if I would loved helping you...

**Comment by SvenGroot** [comment]
@fred-the-coder The link to how to enable the keyboard shortcut also has more detailed instructions on how to change the dump type. You can also find alternate instructions [here](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump).

**Comment by Juanfdez11** [comment]
giannisdravilas approach has also worked for me. I have been able to normally operate the terminal for several hours. Although I will still keep an eye on this issue, it has been temporarily solved for me. Thanks!!

**Comment by Lei-Guo** [comment]
Yes, turning on the virtual machine platform solves the problem. Strange.

**Comment by lukasrusty** [comment]
Turning on the Virtual Machine Platform **solved** the problem.

**Comment by SvenGroot** [comment]
Just a reminder: we would still like a crash dump if someone can provide one.

**Comment by jackyjkchan** [comment]
![CrashOnCtrlScroll gif](https://user-images.githubusercontent.com/16214863/76246753-b55f2180-6214-11ea-89a1-d3ca6c1fe683.gif)
@SvenGroot 
I tried following the instructions to produce a MEMORY.DMP but could not do so. 
I have attached a gif of my attempt. I'm using a virtual keyboard to access Scroll Lock.

**Comment by SvenGroot** [comment]
@jackyjkchan I'm not sure if you can use the keyboard method with the virtual keyboard. Maybe try using the NotMyFault tool mentioned [here](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump) instead?

**Comment by jackyjkchan** [comment]
@SvenGroot I got the MEMORY.DMP file but its 14GB. I'm not sure how to get it to you.

**Comment by gcmurillo19** [comment]
@giannisdravilas recomendation solve the problem for me. Thanks!

**Comment by hsellik** [comment]
@SvenGroot , just sent a dump (15.8GB) to secure@microsoft.com.

OS Build 18363.720 with Ubuntu 18.04 WSL1.

I found [NVidia instructions for dump generation](https://nvidia.custhelp.com/app/answers/detail/a_id/4755/~/manually-forcing-a-system-crash-using-a-keyboard) to be quite clear and useful.

Hope it helps.

**Comment by Tsylvester8** [comment]
I had the same problem. @giannisdravilas recommendation seems to solve the problem for me as well.

**Comment by SaElAh** [comment]
Exact same problem there too... Has anyone found a temporary solution ? I freeze after only a few minutes of usage :/.

**Comment by Tsylvester8** [comment]
Yes. I had the same problem too. @giannisdravilas solution fixed it for me.

**Comment by fts-01** [comment]
I have the same problem but unfortunately @giannisdravilas solution does not fix it for me. Any other ideas how to fix ?

**Comment by AhrazA** [comment]
Having a similar issue in vim and neovim. The Virtual Machine Platform fix by @giannisdravilas did not work for me.

**Comment by sfdb** [comment]
Same problem here - the proposed fix did not work.

**Comment by lukastillmann** [comment]
I have the same or a similar problem. WSL hangs/freezes randomly, sometimes after a few minutes, sometimes after a couple of hours. Killing the process doesn't work, I always need to restart my pc.

Windows 10 Version 10.0.18363 Build 18363
Distribution: Ubuntu (Windows Store)

I have had this issue before last year and tried to describe it here:
https://superuser.com/questions/1430009/windows-wsl-ubuntu-hangs-freezes-randomly-when-listening-to-ports

At some pointit simply didn't happen any more until about last week.

I have noticed it only happening when I am running some kind of javascript dev server. But I usually do, so I cannot say for sure, that it wouldn't happen otherwise. 

I did install a windows update last week `kb4552931`, which coincided with the error occuring again

The virtual machine fix by @giannisdravilas did also not work for me.

**Comment by edmond1948** [comment]
> I have the same or a similar problem. WSL hangs/freezes randomly, sometimes after a few minutes, sometimes after a couple of hours. Killing the process doesn't work, I always need to restart my pc.
> 
> Windows 10 Version 10.0.18363 Build 18363
> Distribution: Ubuntu (Windows Store)
> 
> I have had this issue before last year and tried to describe it here:
> https://superuser.com/questions/1430009/windows-wsl-ubuntu-hangs-freezes-randomly-when-listening-to-ports
> 
> At some pointit simply didn't happen any more until about last week.
> 
> I have noticed it only happening when I am running some kind of javascript dev server. But I usually do, so I cannot say for sure, that it wouldn't happen otherwise.
> 
> I did install a windows update last week `kb4552931`, which coincided with the error occuring again
> 
> The virtual machine fix by @giannisdravilas did also not work for me.


uninstall kb4552931, it's worked to me. 
3q

**Comment by alexravenna** [comment]
I am experiencing this problem too, which is qute unfortunate, as I was looking forward to using WSL as my development system on my new work laptop.

My Windows updates are administered by my company's IT, so I don't have any influence on them, meaning:
- I can't update Windows to the latest version (I currently have 10.0.18363), so I can't use WSL2
- I can't roll back updates (I uninstalled kb4552931 as suggested by @edmond1948, then my system reinstalled it immediately).

I'm a web frontend developer and was using VS Code with WSL1 Ubuntu 18.04 as a remote development environment and the new Windows Terminal as my command line tool.

The Virtual Machine Platform "workaround" from @giannisdravilas seemed to work for me for a about a day, until a tried a `rm -rf node_modules` in my project and the problem reared its ugly head again 😢. The effects of this problem when it occurs are severe and make WSL1 usage infeasible:
- VS Code loses its connection to WSL
- Windows Terminal and WSL itself won't start anymore
- Other apps start behaving strangely or not responding
- All percentages in the task manager freeze and don't update
- Sometimes I can't even open the start menu anymore
- System can only be shut down by holding down the power key (Start Menu -> Power -> Shut down does nothing)

Looks like I'll have to go back to Git Bash and installing everything under Windows until this is fixed or I can upgrade to WSL2 😞.

**Comment by AhrazA** [comment]
@alexravenna I am experiencing this issue on WSL2 too sadly.

**Comment by onomatopellan** [comment]
@AhrazA This is a WSL1 issue. For WSL2 freezes the issue could be #4966.

**Comment by rodrigogs** [comment]
Randomly freezes when running npm scripts

**Comment by airtonix** [comment]
> @SvenGroot , just sent a dump (15.8GB) to [secure@microsoft.com](mailto:secure@microsoft.com).
> 
> OS Build 18363.720 with Ubuntu 18.04 WSL1.
> 
> I found [NVidia instructions for dump generation](https://nvidia.custhelp.com/app/answers/detail/a_id/4755/~/manually-forcing-a-system-crash-using-a-keyboard) to be quite clear and useful.
> 
> Hope it helps.

you sent a 15gb email?

**Comment by fgarcia** [comment]
I've been having randomly this problem too, but recently it got worst. It is hard to track because the terminal freezes and I try to find the buggy process from htop/top where it is easy to get the full path of the program. The ones usually blocking WSL terminal and background ports is vscode-server, specially the typescript server.

That being said, even when it is not really WSL fault, I wonder if I should expect WSL to not go down so easily from a rogue  process. Like in being able to prioritize the load so the terminal and open ports are not highjacked by a high cpu/mem process

**Comment by Sp4Rx** [comment]
Randomly freezes when running Docker inside wsl2

**Comment by ulftietze** [comment]
> Randomly freezes when running Docker inside wsl2

Oh this seems to be a quite good hint to check on. A lot of times when i am connected to a remote ssh server, the connection wsl terminal freezes. Not the windows or the process itself but the ssh connection seems to be frozen. I can open a new tab or a new pane with "alt"+"shift"+"+".
Maybe this can really be an issue with docker, because i first detect that behavior during the time i started to run some docker container. Or it's because i run CLion, IntelliJ or PHPStorm inside the WSL.

**Comment by Sp4Rx** [comment]
@ulftietze yeah it seems like when the docker takes too much memory it freezes.

And another problem with `wsl` I'm facing is, the max storage is defined as 250 GB regardless of available space on the hard drive. So if I build too many images windows drive get's full. There there is no way we could start wsl unless we free up some space.

**Comment by ulftietze** [comment]
@Sp4Rx Maybe, maybe not, i dont know. I have 32 GB of RAM and there is about 12GB left, so this shouldn't cause the problem.
Also it's the ssh connection which freezes, not a connection to a docker or anything equal, and thats the strange behaviour.

**Comment by FibHeap** [comment]
Same here. WSL1 hangs at least once a day. It happens during a lot of hard disk activity, I think. As mentioned above, deleting a big `node_modules` nearly triggers it with 100% certainty. Also, working on a big project in VS code can trigger it after some time without deleting anything.

I also have WSL1 and WSL2 running on the same machine and use Docker Desktop with WSL2 backend. However, it does not happen necessarily if I run docker commands.

**Comment by Sp4Rx** [comment]
I update docker and windows both when ever a update is available. Currently I don't see any random freez when I run docker in wsl2. 

Don't know what fixes it the windows update or rhe docker update

**Comment by meta-meta** [comment]
This is an issue for me on Docker Desktop on WSL2. Running jest tests inside my docker container takes over my CPU.

**Comment by mrjrieke** [comment]
I've noticed that this has gotten a lot better over time with various driver and windows updates, but occasionally, when coming back from sleep (or just screen lock), my linux based X apps will be sluggish and/or frozen.  The only workaround I've found so far is:
wsl --shutdown

But that means a whole lot of setup getting the apps running again.

**Comment by kierke-gaard** [comment]
same here. it freezes regularly. Especially after my computer hass been in sleep mode. What helps is shutting it down by force.
![grafik](https://user-images.githubusercontent.com/43842233/206440701-63ec4c28-6788-4e19-bc5d-731777dcd790.png)

**Comment by mrdragonblack** [comment]
hello my name dragonhacker1337 im not using wsl  im using vm in win 11 but i have glitch in kali linux os  this is the screenshot  
       
![IMG20230110134842](https://user-images.githubusercontent.com/118146225/211472227-557b8055-6a10-4d43-ac57-9bd83331713b.jpg)

![IMG20230110134837](https://user-images.githubusercontent.com/118146225/211472077-55af27db-155d-49c5-8aff-999aa6a96f35.jpg)


sorry if anyone dont know about vm i'cant find vm forum 
thank you if you want help me
