### ISSUE TITLE
chroot: cannot change root directory to 'myDir': Operation not permitted

### ISSUE THREAD

**Issue by stefancristianco** [microsoft/WSL#4938]
Hello,

I have encountered the error in subject while trying to use chroot from my home directory in WSL.

I am doing the following actions:
:~ $ mkdir myDir
:~ $ chroot myDir
chroot: cannot change root directory to 'myDir': Operation not permitted

If I try the same with "sudo" I get:
chroot: failed to run command ‘/bin/bash’: No such file or directory

Some data about my installation if it helps:
:~ $ uname -a
Linux myHostName 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

Am I doing something wrong, or is chroot still not supported?

Thanks and regards,
Cristian

**Comment by therealkenc** [comment]
> chroot: cannot change root directory to 'myDir': Operation not permitted

Linux behavior. You don't have permission to `chroot`.

> chroot: failed to run command ‘/bin/bash’: No such file or directory

Also Linux behavior. Your chroot directory has no `/bin/bash` or fallback `/bin/sh`. That is, `$PWD/myDir/bin/bash` does not exist. Or `$PWD/bin/bash` exists but cannot be executed.

> Am I doing something wrong

Yes.

>  or is chroot still not supported?

The `chroot(2)` syscall has been supported in WSL1 since 14936 circa Sept 2016.

**Comment by DungMinhDao** [comment]
@stefancristianco I'm facing the same issue. How did you solve the problem? I'm having WSL2/Ubuntu terminal installed somewhere in drive C: and want to migrate files to a folder in drive D:, but chroot gave me the same behavior. Do I need to copy any folder like /bin/bash (or other folders) to the folder in drive D:?
