### ISSUE TITLE
WSL failed to start after update Windows

### ISSUE THREAD

**Issue by merkuriy** [microsoft/WSL#4939]
* Windows build number: 
Microsoft Windows [Version 10.0.19041.113]

* What you're doing and what's happening:
Run:
`PS C:\> wsl -d ubuntu-19-04-server`
Freezes in an attempt to launch and nothing happens.

* What's wrong / what should be happening instead:
Distro should launched and worked.

* Detailed logs
[lxcore__.etl.zip](https://github.com/microsoft/WSL/files/4272324/lxcore__.etl.zip)

**Comment by merkuriy** [comment]
Tried to enable and disable optional components Windows for WSL:

* Disable
```powershell
dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart
dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart
```

* Restart machine

* Enable
```powershell
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

* Restart machine

* List WSL Distros:
```powershell
PS C:\>  wsl -l --all
```
Распределения подсистемы Windows для Linux:
ubuntu-19-04-server (по умолчанию)

* Run Distro:
```powershell
PS C:\> wsl -d ubuntu-19-04-server
```
Similar. Freezes in an attempt to launch and nothing happens.

**Comment by pedrodaniel10** [comment]
Hello, I have the exact same problem with the same Windows version (Version 10.0.19041.113)
I'd like to add that after some time (about 15 to 25 minutes) it shows the message:

> The operation could not be started because a required feature is not installed.
[process exited with code 4294967295]

This happened after an update 10 2004 (20H1) KB4540409  (Comulative update for Windows 10 Version 2004 for x64 based systems)

**Comment by merkuriy** [comment]
Thanks, @pedrodaniel10 ! The [solution you found helped](#issuecomment-593152539) me too.

**Comment by simeruk** [comment]
Same issue here with **19569.rs_prerelease.200214-1419**.

Issue manifesting itself as:

> The operation could not be started because a required feature is not installed.

Workaround link provided by @pedrodaniel10 did work and removed the issue in my case.

**Comment by davidwudv** [comment]
> Hello, I have the exact same problem with the same Windows version (Version 10.0.19041.113)
> I'd like to add that after some time (about 15 to 25 minutes) it shows the message:
> 
> > The operation could not be started because a required feature is not installed.
> > [process exited with code 4294967295]
> 
> This happened after an update 10 2004 (20H1) KB4540409 (Comulative update for Windows 10 Version 2004 for x64 based systems)
> 
> EDIT: I guess it was some configurations of Hyper-V that changed with the update. Following this post https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html fixed my problem.

Thank you! I fixed my problem.

**Comment by ThomasMConnors** [comment]
This did not work for me but it's a bit different,

WSL starts fine and MS Store Unbuntu 18.04.4 LTS runs fine. Yet Ubuntu 20.04 returns:

The system cannot find the file specified.
[process exited with code 4294967295]

**Comment by onomatopellan** [comment]
@ThomasMConnors what does `wsl.exe -l -v` shows?

**Comment by ThomasMConnors** [comment]
It shows

C:\temp>wsl.exe -l --all
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Ubuntu-20.04

(There was no -v option for wsl)

**Comment by onomatopellan** [comment]
@ThomasMConnors Thanks. Then it seems you are still in WSL1 and this thread's issue is more about WSL2 and hyper-v.
In WSL1 that message could mean the Ubuntu 20.04 app is not installed in C:
See https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting

**Comment by VishnuSuresh2000** [comment]
After windows 10 2004 update wsl is not working the commands also not working

**Comment by leizhilong** [comment]
> After windows 10 2004 update wsl is not working the commands also not working

Same here, no matter which distro I chose to start on Windows 10 2004,  I got a `[process exited with code 4294967295]'

```
PS C:\Users\username> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         2
  Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         2
``` 
Tried steps in [https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html](https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html), but nothing happened.

**Comment by onomatopellan** [comment]
@leizhilong Try this https://github.com/microsoft/WSL/issues/4929#issuecomment-636419019

**Comment by leizhilong** [comment]
> @leizhilong Try this [#4929 (comment)](https://github.com/microsoft/WSL/issues/4929#issuecomment-636419019)

Thanks @onomatopellan for the clue. 
I tried the method metioned in the comment. Unluckily,  my attempt to remove the Hyper-V virtual eth adapter end up with the same `4294967295` error code.  I guess errors with `0xffffffff ` and `4294967295`  might be due to differenet causes.

When I use `wsl -d Ubuntu` to run WSL after deleting virtual adapter and reboot,   the Hyper-V virtual eth adapter would appear again but WSL still dosen't work.

Thanks anyway.

**Comment by leizhilong** [comment]
`netsh winsock reset` saved my day.

see: 
https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141

**Comment by VishnuSuresh2000** [comment]
> > After windows 10 2004 update wsl is not working the commands also not working
> 
> Same here, no matter which distro I chose to start on Windows 10 2004, I got a
> `[process exited with code 4294967295]`
> 
> ```
> PS C:\Users\username> wsl -l -v
>   NAME            STATE           VERSION
> * Ubuntu-20.04    Stopped         2
>   Ubuntu          Stopped         2
>   Ubuntu-18.04    Stopped         2
> ```
> 
> Tried steps in https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html, but nothing happened.

This problem was solved by reinstalling windows features 

Hyper-V,
Windows subsystem from Linux,
Virtual machine platform

**Comment by jkugiya** [comment]
I was able to resolve the issue with the following steps.

1. Make the above [security settings changes](https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html).
2. Update [WSL2 kernel](https://docs.microsoft.com/windows/wsl/wsl2-kernel)

**Comment by DanOlivier** [comment]
I don't know if it was disabling and re-enabling the features (`Microsoft-Windows-Subsystem-Linux`, and `VirtualMachinePlatform`, then rebooting), or running `netsh winsock reset` and rebooting, which saved me.

**Comment by forecho** [comment]
https://github.com/microsoft/WSL/issues/4904#issuecomment-643883570

**Comment by johnymachine** [comment]
> `netsh winsock reset` saved my day.
> 
> see:
> [#5092 (comment)](https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141)

Yes it works!

**Comment by jlfsdtc** [comment]
> > > After windows 10 2004 update wsl is not working the commands also not working
> > 
> > 
> > Same here, no matter which distro I chose to start on Windows 10 2004, I got a
> > `[process exited with code 4294967295]`
> > ```
> > PS C:\Users\username> wsl -l -v
> >   NAME            STATE           VERSION
> > * Ubuntu-20.04    Stopped         2
> >   Ubuntu          Stopped         2
> >   Ubuntu-18.04    Stopped         2
> > ```
> > 
> > 
> > Tried steps in https://www.surfacetablethelp.com/2018/10/fix-hyper-v-not-working-after-windows-10-v1809-upgraded.html, but nothing happened.
> 
> This problem was solved by reinstalling windows features
> 
> Hyper-V,
> Windows subsystem from Linux,
> Virtual machine platform

Yes,Maybe Hyper-V has error

**Comment by frankaddelia** [comment]
I've spent multiple hours on this problem on a few different occasions and I don't remember the same solution working twice. This usually seems to happen after a Windows Insider update (verified the build version was higher than the minimum), but I had it happen for no reason that I could determine yesterday. After spending almost four hours trying to fix this problem for the third time, the thing that just worked for me was running through the installation steps without uninstalling first WSL or Ubuntu: https://docs.microsoft.com/en-us/windows/wsl/install-win10. This could have worked because it *might* have applied an update that I wasn't getting, but I have no idea which step fixed if it that's not what happened =\ This is not a technically good answer, but I hope it helps someone else who's reached the end of their patience and felt like they've tried everything too.

**Comment by chuan-325** [comment]
> Tried to enable and disable optional components Windows for WSL:
> 
> * Disable
> 
> ```powershell
> dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart
> dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart
> ```
> 
> * Restart machine
> * Enable
> 
> ```powershell
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> ```
> 
> * Restart machine
> * List WSL Distros:
> 
> ```powershell
> PS C:\>  wsl -l --all
> ```
> 
> Распределения подсистемы Windows для Linux:
> ubuntu-19-04-server (по умолчанию)
> 
> * Run Distro:
> 
> ```powershell
> PS C:\> wsl -d ubuntu-19-04-server
> ```
> 
> Similar. Freezes in an attempt to launch and nothing happens.


I faced the same problem on my machine's Ubuntu-20.04 distro (WSL2) after compacting its `ext4.vhdx` file. 

I've tried `netsh winsock reset` but failed. Yet your solution works for me. Thank you very much.
