### ISSUE TITLE
Ubuntu no longer installs on WSL 2

### ISSUE THREAD

**Issue by tdecaluwe** [microsoft/WSL#4944]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.19013.1122]`

* What you're doing and what's happening:
After installing Ubuntu app through the Microsoft Store, installation of the distro fails with the following output:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 De bewerking kon niet worden gestart omdat een vereist onderdeel niet ge´nstalleerd is.

Press any key to continue...
```
Installation was done as a way to fix a previously working broken Ubuntu installation in the first place. After removal of the distro and installing it again, the above is the result. However I can't find any relevant recent updates that might cause the problem.

* What's wrong / what should be happening instead:
Ubuntu should install successfully as a WSL 2 distro

**Comment by onomatopellan** [comment]
Take a look at #4626

**Comment by tdecaluwe** [comment]
Thanks @onomatopellan, seems to be the same underlying problem. I'm going to close this issue for now.
