### ISSUE TITLE
full ubuntu theming

### ISSUE THREAD

**Issue by BannerBomb** [microsoft/WSL#4948]
**Is your feature request related to a problem? Please describe.**
I can't get used to how the shell window will never feel like a ubuntu shell. It just feels like I am using the windows command prompt with additional ubuntu support. No matter what workaround I use to try to make it mostly similar it's not the same as using gnome shell in terms of looks and functionality.

**Describe the solution you'd like**
I would like to see there be an option to set the shell to look exactly like the Ubuntu gnome terminal shell because for people like me, I hate using and looking at a windows command line. I've always been around the ubuntu gnome shell and I just can't get used to the command line theme that it has by default. Even using alternative methods by installing the ubuntu fonts and changing the colors from the preferences, it just isn't the same. Especially when it comes to something light right clicking in the shell, I would like to be able to have it open a menu instead of pasting what ever is in the clipboard.

**Describe alternatives you've considered**

**Additional context**

**Comment by therealkenc** [comment]
> ubuntu shell

Let's start of being clear here. Ubuntu doesn't have a shell. GNU `bash` is a shell, among many shell alternatives such as `zsh`. Likewise `gnome-terminal` isn't a shell. The `gnome-terminal` is a (wait for it) terminal, among many terminal alternatives such as `enlightenment`.

You are being pretty specific here; you want `gnome-terminal`. Which is a reasonable ask, but not a WSL ask. Supporting GUI apps naively (which would include but is not specific to `gnome-terminal`) is duplicative #829, #938, others.

You might want to check out the new [terminal](https://github.com/microsoft/terminal). It is converging on modern terminal looks and functionality expectations.

Alternative is to use a third-party X11 Server like VcXsrv, others.
