### ISSUE TITLE
WSL2 iper slow executing nginx+php7.2-fpm+mysql

### ISSUE THREAD

**Issue by ganedda-softfobia** [microsoft/WSL#4950]
* Your Windows build number: Version 10.0.19041.84

* What you're doing and what's happening:  
I use WSL2 for developing on an installation of Magento 2, with nginx, php7.2, mysql. In the last few days the system is unstable: while I can perform any task on command line, and access WSL2 through VS Code, use the Magento through the web browser is frustratingly slow and CPU/RAM consuming, and I did not made any substantial changes. Windows has made some automatic updates but I don't know how have affected WSL2. I uninstalled the latest update but the problem is still here.

* What's wrong / what should be happening instead: Magento should work fast as some days ago

I know this is generic and on specific application, but it has become pretty strange to me that without any particular reason this has become slow as WSL1 (ah I also checked, the version of WSL is still 2 on this distro).
Any suggestion on what can I do? Thanks

**Comment by ad-on-is** [comment]
You need to have all your PHP project files in your WSL users `/home/xxx` folder and not in `/mnt/x`.

You will be amazed how fast it runs from there.

**Comment by ganedda-softfobia** [comment]
hi, thanks for your reply. My php projects are under /var/www so not shared with windows. Moving from WSL to WSL2 I noticed how fast the whole system has become, but it's the last few days that everything got really slow. I'm guessing a windows update broke the magic but I don't know how

**Comment by alexsandro-xpt** [comment]
@ad-on-is are you told the shared/mounted with WSL2 is slow?

**Comment by ad-on-is** [comment]
@alexsandro-xpt  Not only have I been told, I experienced it myself.
When I was about to set up my dev environment, I tried several approaches.

I ended up moving all my WSL-compatible projects away from the shared/mounted folders to WSLs home directory.

A TYPO3 backend loads within 600-800ms, while within shared folder it took several seconds.

I'm also using Docker for Windows, but inside WSL, for my LAMP-stack, if this helps.

**Comment by ad-on-is** [comment]
Also, I'm on the latest Windows Insider and don't experience any slowdowns.

**Comment by dyanakiev** [comment]
Sorry for reopening this, i wonder if i use rsync to sync the shared folder and the local one in real time will help, lets ignore that you will have the folders duplicated, but might be faster?

**Comment by pnt9948** [comment]
> You need to have all your PHP project files in your WSL users `/home/xxx` folder and not in `/mnt/x`.
> 
> You will be amazed how fast it runs from there.

Hello,

Can anyone help me with mounting directories ? I mean is it just the move command or anything else which needs to be done ?

Thank You
