### ISSUE TITLE
Windows doesn't see enabled WSL

### ISSUE THREAD

**Issue by gerrustalker** [microsoft/WSL#4952]
- **Version**: `Microsoft Windows 10.0.18363.628`
- Typed `kali` in cmd, returned `"The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again."`

- Screenshot:
![Скриншот 05-03-2020 200008](https://user-images.githubusercontent.com/45996315/76005362-f6f18300-5f1b-11ea-96ee-838319e1c3d0.png)

_Disable and enable doesn't change anything._

**Comment by ad-on-is** [comment]
Could you take a look under "Enable or Disable Windows Features", if WSL is enabled there?

https://code.visualstudio.com/remote-tutorials/wsl/enable-wsl

**Comment by gerrustalker** [comment]
> Could you take a look under "Enable or Disable Windows Features", if WSL is enabled there?
> 
> https://code.visualstudio.com/remote-tutorials/wsl/enable-wsl

![image](https://user-images.githubusercontent.com/45996315/76678042-a21dce80-65e5-11ea-8ead-00a7f11097ab.png)
