### ISSUE TITLE
No way to override uid mount setting?

### ISSUE THREAD

**Issue by rhaglennydd** [microsoft/WSL#4954]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18363.693

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
`sudo mount -t drvfs C: /mnt/c -o metadata,uid=1000`
`cd /mnt/c`
`sudo touch test.txt`
`stat -c '%u' test.txt`
Output:
`1000`

* What's wrong / what should be happening instead:
Output should be:
`0` (root)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

I admit I'm not sure whether this is a bug or if this is how it's supposed to be, but it just seems wrong that not even the root can override the mount settings for uid. This creates problems for processes in WSL not owned by user 1000 that access the Windows file system, e.g., a web server process running as another user with a virtual host located on the C: drive can't create files that are owned by itself, they're always owned by user 1000. If this is how mounting with a specified uid is supposed to work, then why do it in the first place? Might as well go back to how it was before the feature was added. Unless, of course, there's some setting or option I'm just not aware of that can allow exceptions?

**Comment by therealkenc** [comment]
Can't repro here.

![image](https://user-images.githubusercontent.com/7049700/76043286-e9340180-5f0b-11ea-9da9-313e6eb03b96.png)

[Full disclosure this was on more recent 19569 and WSL1, but that won't matter.]

**Comment by therealkenc** [comment]
I think I know what might (?) be happening here. I get nonobvious behavior if I don't `umuont(1)` `/mnt/c` first. I think that might be variation my dead crickets #3963. Here is a more complete sequence showing both `root` and `ken` in the same directory.

![image](https://user-images.githubusercontent.com/7049700/76044098-28635200-5f0e-11ea-904c-d5cebbab3510.png)

**Comment by rhaglennydd** [comment]
I forgot I already had automount settings in wsl.conf. I unmounted C: and rebooted my computer, but that didn't fix things. The settings in wsl.conf included `case=dir`. On a hunch, I unmounted C: again and remounted it without the `case` option. That fixed things. I edited wsl.conf so it's `case=off`. Do you know why having `case=dir` would cause this?

**Comment by therealkenc** [comment]
You don't have metadata in the options. The default is no metadata.

**Comment by rhaglennydd** [comment]
D'oh! Updated wsl.conf, will unmount and reboot later, let you know how it goes.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/76122423-dde3e300-5faa-11ea-8cf1-16dc7872fa42.png)

[n.b. You're on your own with `case=dir`.]

**Comment by rhaglennydd** [comment]
Can confirm that it's fixed now. Thanks!
