### ISSUE TITLE
Different behavior CMD > dist [command] than dist > [command] (Variables not available?)

### ISSUE THREAD

**Issue by StickyAI** [microsoft/WSL#4955]
**Version:**
10.0.18363.657
WSL 1
* What you're doing and what's happening:  

```
CMD:\ > debian 
:~$ xclock 
```
Xclock displays as expected.

```
:~$ exit
CMD> debian run xclock OR wsl xclock
Error: Can't open display:
```
It doesn't work :(

I've tried with WSLENV thinking maybe that's what it's for, and setting default WSL user.  No dice.

**Comment by StickyAI** [comment]
On using another terminal (the new one) it actually prints the display rather than the nothingness, 

```
CMD:\ >debian run echo $DISPLAY
 /127.0.0.1:0.0
```
That erroneous whack must be the culprit. It's definitely not mine. 


Also, when selecting any linux terminal from the new windows terminal, it also won't work with xapps.

**Comment by therealkenc** [comment]
There are no repro steps here; you aren't stating where you set `$DISPLAY` in that run immediately above.

> I've tried with WSLENV thinking maybe that's what it's for, and setting default WSL user.

It isn't.

You probably want `export DISPLAY=127.0.0.1:0` inside your `.bashrc`, and then:
```
C:\>wsl.exe /bin/bash -ic 'echo $DISPLAY'
```
![image](https://user-images.githubusercontent.com/7049700/76061333-21e9d000-5f38-11ea-8b97-f3774be14ed2.png)

Another way to roll is `wsl.exe /bin/bash --login -c 'echo $DISPLAY'`.

More [here](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html).

Repeat #4740 #2816 #2075 others.
