### ISSUE TITLE
WSL 1.0 Sometimes doesn't start

### ISSUE THREAD

**Issue by Salmondx** [microsoft/WSL#4961]
Sometimes WSL 1.0 doesn't start after turning on Windows. If I use Ubuntu app in Windows it just hangs with black screen, same for Visual Studio Code for WSL projects.

The only way to fix it is by stopping LxssManager service (and it hangs on stopping state again), restart Windows and enabling this service again.

Microsoft Windows [Version 10.0.18363.657]

**Comment by Xbeninni** [comment]
Some thing happened here, Microsoft Windows 10 Pro, OS Build 18363.592
The CLI interface just hang there

**Comment by amejiarosario** [comment]
I had the same issue and it was because there was some pending update: https://github.com/microsoft/WSL/issues/4962
