### ISSUE TITLE
WSL2 wont load when there is a windows updata pending

### ISSUE THREAD

**Issue by FloweyTheFlower420** [microsoft/WSL#4962]
WSL2 won't boot when there is a windows update pending. The update installed but needs a restart of windows. During that time, WSL2 won't boot and gets stuck on a blank screen.

**Comment by simeruk** [comment]
Got **Microsoft Windows [Version 10.0.19569.1000]** with pending **Windows 10 Insider Preview 19577.1000 (rs_prerelease)** using **WSL2** and no issues with bringing up my Ubuntu so far:

```C:\Users\Simon>wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2```

Is it possible its related to a partivular version of Linux that is being used?

**Comment by therealkenc** [comment]
Yeah. There are two plausible possibilities on this one. (1) There was some _specific_ update, which is not cited in the OP, that happened to cause a problem. (2) Something unrelated entirely, and an update just _happened_ to be pending, and the restart (not the update) resolved.

The latter is more likely. AFAIK a _pending_ update doesn't have any effect on a running system. Closing on need-repro for the fact there is nothing actionable even if it were the pending update.

![image](https://user-images.githubusercontent.com/7049700/76598037-24f83980-64bf-11ea-81c1-a7be3997c121.png)
