### ISSUE TITLE
App execution aliases in %LOCALAPPDATA%\Microsoft\WindowsApps don't launch through interop

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/WSL#4969]
This is particularly problematic with Windows Terminal's `wt.exe` alias -- launching it yields no response and no new terminal. This happens on Vibranium w/ WSL1 _or_ WSL2.

This applies even to console app execution aliases like `python.exe` and `DesktopAppConverter.exe`.

**Comment by benhillis** [comment]
/fixed [20190](https://blogs.windows.com/windowsexperience/2020/08/12/announcing-windows-10-insider-preview-build-20190/).

**Comment by korpa** [comment]
@benhillis When will this be fixed in Win10 2004?

**Comment by zachsiegel-capsida** [comment]
This does not seem to be fixed in Windows 10 21H2, 19044 (I have 19044.1526). Am I missing something?
