### ISSUE TITLE
clock_gettime(CLOCK_TAI) returns EINVAL

### ISSUE THREAD

**Issue by wangqr** [microsoft/WSL#4973]
**Is your feature request related to a problem? Please describe.**
Currently `clock_gettime(CLOCK_TAI)` on WSL1 returns `EINVAL`. According to [kernel document](https://github.com/torvalds/linux/blob/1b51f69461e6a3485bab5a7601e16b79d7eeac59/Documentation/core-api/timekeeping.rst), `clock_gettime(CLOCK_TAI)` returns the time in relative to the UNIX epoch starting in 1970 using the International Atomic Time (TAI) reference instead of UTC to avoid jumping on leap second updates.

**Describe the solution you'd like**
`clock_gettime(CLOCK_TAI)` should return without error, and set the correct TAI time in the given `struct timespec`. At now in 2020-03, the result of `clock_gettime(CLOCK_TAI)` should be equal to `clock_gettime(CLOCK_REALTIME)` plus 37 seconds. For details see [Wikipedia: Leap second](https://en.wikipedia.org/wiki/Leap_second).
This TAI offset is also able to adjust with [`adjtimex(ADJ_TAI)`](http://man7.org/linux/man-pages/man2/adjtimex.2.html) on linux. But changing it within WSL is not needed in my use case.

**Additional context**
The code I used to test this:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <errno.h>

int main()
{
   struct timespec ts_realtime;
   struct timespec ts_tai;

   if(clock_gettime(CLOCK_REALTIME, &ts_realtime))
       printf("clock_gettime(CLOCK_REALTIME) failed. errno=%d\n", errno);
   else
       printf("CLOCK_REALTIME: %lld.%.9ld\n", (long long)ts_realtime.tv_sec, ts_realtime.tv_nsec);
   if(clock_gettime(CLOCK_TAI, &ts_tai))
       printf("clock_gettime(CLOCK_TAI) failed. errno=%d\n", errno);
   else
       printf("CLOCK_TAI: %lld.%.9ld\n", (long long)ts_tai.tv_sec, ts_tai.tv_nsec);
}
```

And the output of the above code on WSL1 on Windows 10.0.18363.720:
```
CLOCK_REALTIME: 1584258060.292597100
clock_gettime(CLOCK_TAI) failed. errno=22
```

**Comment by sirredbeard** [comment]
I will let the WSL team weigh in but I just want to set your expectations that not all of the less popular time syscalls have been implemented in WSL1 and aren't likely to. They tend to be prioritized based on demand. An upstream change in glibc triggered #4898. If you could provide a use case for why you need CLOCK_TAI in WSL1 it may help the WSL team prioritize it accordingly.

**Comment by wangqr** [comment]
#4898 is indeed much more important than this. This issue is just a feature request and no need to prioritize it at the moment.

`CLOCK_TAI` is likely to be a monotonic clock that can work between reboots. It eliminates the hassle to handle the leap second issue with `CLOCK_REALTIME`. I'm not aware any software being broken without `CLOCK_TAI`, and my own usage does handle the case where `CLOCK_TAI` fail (for compatibility with linux<3.10).
