### ISSUE TITLE
Windows f: drive to fedoraremix files gone after kernel update

### ISSUE THREAD

**Issue by lincolnthomas** [microsoft/WSL#4977]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.19041.153]`

* What you're doing and what's happening:

Opening "Windows Terminal (preview)" where my default profile is a fedoraremix distro (https://www.whitewaterfoundry.com/fedora-remix-for-wsl) opened a shell which gave me the message about updating my kernel. 

I did "wsl --shutdown", then followed the steps in 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Now, starting my fedoraremix works, but the F: drive that used to exist in Windows is gone. It normally showed me the root filesystem of my fedoraremix distro. I use developer tools running on Windows that access my Fedora files, so without that Windows drive it's a blocker for me.

From my profiles.json:
```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "initialCols": 120,
    "initialRows": 50,

    "defaultProfile": "{d3f31bee-5823-5ed8-8e04-f31ed54f2cd9}",

    "profiles":
    [
        {
            // Fedora Remix WSL2
            "guid": "{d3f31bee-5823-5ed8-8e04-f31ed54f2cd9}",
            "hidden": false,
            "name": "fedoraremix",
            "source": "Windows.Terminal.Wsl",
            "fontSize": 10,
            "padding": "3",
            // Subdirs using /, \, or \\ doesn't work
            "startingDirectory": "F:"
        },
```

I can go the other direction just fine: I can see Windows files from Fedora via the `/mnt/c` mount.

If I try to install the kernel update again, I get the error:
`This update only applies to machines with the Windows Subsystem for Linux`

Otherwise everything about the fedoraremix distro is working fine.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
See attached.
[WSL logs.zip](https://github.com/microsoft/WSL/files/4340703/WSL.logs.zip)

**Comment by sirredbeard** [comment]
Did you have \\wsl$\fedoraremix manually mounted as F:\ in Windows before?

**Comment by lincolnthomas** [comment]
No, I did nothing manually. That line in profiles.json took care of it, I believe:
`            "startingDirectory": "F:"`
Yes, I can do it manually:
```
C:\Users\Lincoln>net use f: \\wsl$\fedoraremix
The command completed successfully.
```
I suppose I could add that command into my startup Windows batch script.

So why is it not happening automatically anymore?

**Comment by DHowett-MSFT** [comment]
Nothing in Terminal (which is what handles your profiles.json) would have taken care of drive mapping for you. :smile:

**Comment by lincolnthomas** [comment]
Ok, so that line only defines where the CWD should be, assuming the drive is already mapped. 

Starting a Terminal launches the distro if it's not already running, and something in the launch process did the drive mapping automatically before the kernel upgrade, and now doesn't. So what happened?

**Comment by DHowett-MSFT** [comment]
I don’t think WSL, or any operating system component underpinning WSL, will automatically map a network drive to the distribution folder; that could wreak havoc on peoples’ workflows by mapping and unmapping drives named after distributions and introduce silent failure cases like “what if my distribution name starts with a C? Will it just not map over C:\?”.

**Comment by sirredbeard** [comment]
It might be a question for the [fedoraremixonwsl team](https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL)? Maybe they are doing something with that now?

**Comment by crramirez** [comment]
Hello,

No, it should work in fedoraremix, we are not doing anything special. 
@lincolnthomas  Any way to fix your Windows Terminal issue to use this profile definition:

`"commandline": "fedoraremix.exe"`

and remove the `startingDirectory` line.  This will launch Windows Terminal in your home directory.

Regards,
Carlos

**Comment by lincolnthomas** [comment]
I don't know what changed, but now it's magically working again. I no longer have to do the `net use` command (above). Maybe a later automatic Windows Update on the fast track insider builds fixed it. I'm now running Version 10.0.19041.172

**Comment by jodett** [comment]
i had the same problem with the installer, error message "This update only applies to machines with the Windows Subsystem for Linux" .
i was able to fix it, by right-clicking the installer and choosing repair

**Comment by vineethsoma** [comment]
> i had the same problem with the installer, error message "This update only applies to machines with the Windows Subsystem for Linux" .
> i was able to fix it, by right-clicking the installer and choosing repair

Yeah, I had the same issue. In my case it worked once is did right-click and Uninstall. And then proceeded with installation again.
