### ISSUE TITLE
WSL2 green screen crash

### ISSUE THREAD

**Issue by 24githubs** [microsoft/WSL#4978]
recently, 
My computer freezes and turns green screen twice two time a week,
I found this problem starting from when i switch to use Insider version.

![20200315_105220](https://user-images.githubusercontent.com/60570585/76818192-87429880-6837-11ea-81fa-5eaf1d1738b8.jpg)

error message 
windows insider build ran into a problem and need to restart .blah blah
stop code DPC WATCHDOG VIOLATION

Insider
OS Build 19582,1000
Ubuntu 18.04
Win10Pro Ram18G
Docker  Desktop WSL 2  version 2.1.7.0

**Comment by sirredbeard** [comment]
From from the [README](https://github.com/microsoft/WSL/blob/master/README.md):

```
Do not open Github issues for Windows crashes (BSODs) or security issues. Please direct all Windows crashes and security issues to secure@microsoft.com. Issues with security vulnerabilities may be edited to hide the vulnerability details.
```
