### ISSUE TITLE
Cannot start WSL as administrator

### ISSUE THREAD

**Issue by svpudik** [microsoft/WSL#4979]
**Please fill out the below information:**
* Your Windows build number: OS version: 10.0.18362 N/A Build 18362

* What you're doing and what's happening: trying start `Windows.Terminal.Wsl` as administrator

* What's wrong / what should be happening instead: ![image](https://user-images.githubusercontent.com/32640971/76831018-c74d4f80-6826-11ea-84bc-528c882f375d.png)

I was forwarded to this repo from here https://github.com/microsoft/terminal/issues/4863

**Comment by sirredbeard** [comment]
Try `wsl --distribution Ubuntu --user root`

**Comment by svpudik** [comment]
thanks, but i am not interested for sudo session but possibility run wsl when i run windows terminal as admin in one window.

**Comment by sirredbeard** [comment]
`wsl --distribution Ubuntu --user root` is not a sudo session, it is booting your image as root.

If you are using the new Windows Terminal you can edit your settings to call your preferred WSL image with the command above to automatically drop in as root, or other user.

Create a new menu entry and add it to the command line:

```
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Ubuntu root",
                "commandline": "wsl.exe --distribution Ubuntu --user root",
                "hidden": false
            },

```

**Comment by svpudik** [comment]
![image](https://user-images.githubusercontent.com/32640971/77044097-1fb75500-69bf-11ea-8516-6112c806a49c.png)

**Comment by sirredbeard** [comment]
Strange. 

![image](https://user-images.githubusercontent.com/33820650/77122197-6767cc00-6a13-11ea-92ab-44e1befd87d0.png)

**Comment by svpudik** [comment]
Try start you CMD, powershell, as Administrator
![image](https://user-images.githubusercontent.com/32640971/77138185-5352b780-6a71-11ea-959a-7c884abd21ce.png)

![image](https://user-images.githubusercontent.com/32640971/77138161-24d4dc80-6a71-11ea-8488-0306795a43e5.png)

**Comment by sirredbeard** [comment]
Oh you are trying to run WSL as a Windows administrator. I see now.

**Comment by svpudik** [comment]
Yes, reason for that is I want use windows terminal application, but for my use case I need have started powershell as admin and in that case I cannot start WSL in new tab.

**Comment by kaushikdr** [comment]
@svpudik How did you solve it?
