### ISSUE TITLE
Linux Distro (Ubuntu) Installation stuck

### ISSUE THREAD

**Issue by butchiki** [microsoft/WSL#4984]
I tried to install Ubuntu distro in my laptop but when the installation shows up, using cmd and Ubuntu app itself, the installation is stuck in "Installing, this may take a few minutes...". I tried to leave it overnight, press any key, reset/repair the application in Setting, reinstall and also uninstall->remove Canonical... folder->reinstall but is always stuck in that part. It successfully installed once (used it for the first time after installation) but after restarting the application the prompt won't show up, so I tried to reinstall it again and then came the same problem again.
Windows 10 Pro x64 version 18363.720

**Comment by sirredbeard** [comment]
Do you have enough free space to unpack the image?

**Comment by butchiki** [comment]
If you're talking about drive C, yes i do have 191 gb free space out of 377 gb

**Comment by sirredbeard** [comment]
Are you using a roaming Windows profile, like on an enterprise network?

**Comment by butchiki** [comment]
Mine it says Local.

**Comment by sirredbeard** [comment]
> the prompt won't show up

What happens when you try to launch it from the command prompt? Can you please post a screenshot?
