### ISSUE TITLE
After installing native Ubuntu in win 10,input username failed-0x80080005

### ISSUE THREAD

**Issue by Gabriella-L** [microsoft/WSL#4987]
![c503f2bd876c5efb052ce136c164e13](https://user-images.githubusercontent.com/53573211/76920704-18347500-6907-11ea-8a01-72290f37937b.png)

**Comment by sirredbeard** [comment]
root already exists and can't be created.

admin is a group and a user with that name can't be created.

Linux usernames cannot begin with a number.

Capital letters in Linux usernames is possible but is likely to result in breakage, so it is disabled by policy. It can be forced once you create a standard admin user but I do not recommend it.

**Comment by sirredbeard** [comment]
The reason Linux has such restrictive username policies is to maintain backward compatibility with UNIX.

Here is a presentation on how the conventions got to be the way they are: https://paulgorman.org/technical/presentations/linux_username_conventions.pdf

I would recommend the following for reading on how users and groups work in Linux: https://wiki.archlinux.org/index.php/users_and_groups
