### ISSUE TITLE
Cannot launch bash (nor wsl) from PowerShell

### ISSUE THREAD

**Issue by NicolasCast** [microsoft/WSL#4988]
Hi,

Ubuntu's bash (installed as Windows Sub System) cannot be started from PowerShell.
The error ois
    CommandNotFoundException

The (only ?) problem is that the bash command is not in PowerShell'path.
Indeed, Ubuntu's bash runs OK when started in its own console from the Windows's start menu.

I guess it is a rather simple problem... !

Additionnal remarks :
Ubuntu 18 was installed from the Windows Store, in WindowsSubSystem. 
The installation process runned smooth.

(I ll add other infos, like WIndows version, later ; but I do not have the computer right now)

Thanks much !

**Comment by sirredbeard** [comment]
Did you try `bash.exe` or `wsl --distribution...`? 

Which build of Windows and PowerShell are you on?

![image](https://user-images.githubusercontent.com/33820650/76972205-a65b2c00-6904-11ea-9c29-2792b708ebe8.png)

**Comment by DHowett-MSFT** [comment]
You are using x86 PowerShell on ARM64 or AMD64.

**Comment by NicolasCast** [comment]
Thanks for your answers.

In Powershell, and also in Windows' cmd.exe :
    bash
    wsl
    bash.exe
    and wsl.exe
are not recognized  : CommandNotFoundException



 $PsVersionTable provides : 

Name Value

PSVersion 5.1.17763.1007
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17763.1007
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

@DHowett-MSFT
I dunno on which CPU the problem occurs : it is on one of my students, at his home. I ask hil.

**Comment by NicolasCast** [comment]
Thanks for your answers.

@sirredbeard
I confirm that in powershell none of the following commands start (CommandNotFoundException) : 
-  bash
-  wsl
-  bash.exe
-  and wsl.exe

Conversely: 
- ubuntu's wsl console launches and runs OK OK (when lanched from windows'menu)
- in the good-old cmd.exe, the **wsl** command launches and runs OK (starts a bash shell)

Windows' release is : 
- Windows 10 édition familiale (FR)
- Release 1809
- 05/11/2019
- OS version 17763.1098

PowerShell's version is ($PsVersionTable) : 
- PSVersion 5.1.17763.1007
- PSEdition Desktop
- PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
- BuildVersion 10.0.17763.1007
- CLRVersion 4.0.30319.42000
- WSManStackVersion 3.0
- PSRemotingProtocolVersion 2.3
- SerializationVersion 1.1.0.1

_=> it seems that PS build version differs from Windows' ?)_

@DHowett-MSFT : CPU is  intel Core i7 - 8750H (not ARM nor AMD).

_non related comment:  I am sorry that I used quite some time to come back to you. Indeed, the issue occurs on one of my students' computer, which I can't access directely. 
Just to let you know : we are starting advising WSL for all of our many students in programming, in the context of today's "stay at home" situation. So, BTW, thanks to all contributors for the very promising Windows feature !_

**Comment by DHowett-MSFT** [comment]
Thanks! Can you get the output of...

```
$env:PROCESS_ARCHITECTURE
```

?

**Comment by NicolasCast** [comment]
Hi again,

`Last news : in powershell : `
`bash.exe`
and 
`wsl.exe`
run OK.

Conversely, `the same commands but w/o .exe fail.`

Now, to answer your questions :
**In powershell :**
`$env:PROCESS_ARCHITECTURE`
prints nothing.

`$Env:Path `
contains :
`C:\WINDOWS\system32;`
(which is where bash lies on another (bug-free) machine.)

Finally, in cmd.exe
`where.exe bash`
prints :
`C:\Windows\System32\bash.exe`


I still dunno why we have this behaviour, but well, at least the student can work !
As far as I am concerned, and though I would be happy to know the trick, the issue could be closed.
Thanks much.
