### ISSUE TITLE
WSL not starting

### ISSUE THREAD

**Issue by marcostorto** [microsoft/WSL#4993]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Versione 10.0.18363.720]

* What you're doing and what's happening:  from powershell (admin mode)
PS C:\> wsl -l
Distribuzioni del Sottosistema Windows per Linux:
Ubuntu-18.04 (valore predefinito)
PS C:\> wsl
(after about 1 minute)
Operazione di I/O terminata a causa dell'uscita dal thread oppure della richiesta di un'applicazione.

* What's wrong / what should be happening instead: wsl should start

logs: [logs.zip](https://github.com/microsoft/WSL/files/4354337/logs.zip)

**Comment by benhillis** [comment]
If you're still experiencing this in 19042 please open a new issue.
