### ISSUE TITLE
SSH Connection Issues when on VPN

### ISSUE THREAD

**Issue by fritz-gerneth** [microsoft/WSL#4994]
**Your Windows build number:**  Version 10.0.19041.153

**What you're doing and what's happening:**  
While connected to the company VPN some SSH connections fail / get stuck. This is most notably happening with GIT (push) & SSH Tunnels to Kubernetes clusters. After disconnecting, the commands work as expected.

Executing the same command on the Windows Command Line works when connected to the VPN. I could observe this with different servers (e.g. GitHub + self-hosted Git Server). Also this does not affect all repositories on that server at once - for some repositories this still does work while for others it won't. If it doesn't work it will continue to not work for a week or so, at some point it will work again and others will fail. Other git commands, like `git fetch` , `git pull` still do work, only pushes do not work. 

**What's wrong / what should be happening instead:** SSH Should not hang.

**Strace of the failing command, if applicable:** 
Last few hundred lines of the strace, and git SSH command output in verbose mode: [Gist](https://gist.github.com/fritz-gerneth/eb2fa40f1d447f46101469540d34cc4d)

**VPN Connection Type:** L2TP/IPSec

**Comment by fritz-gerneth** [comment]
Upon further investigation this was due to the VPN connection using a MTU of 1400. 

tracepath suggests to use an MTU of 1400:

```
 1?: [LOCALHOST]                      pmtu 1500                                                                                                                                                                                               1:  lp-gerneth-fritz                                      0.249ms                                                                                                                                                                            1:  lp-gerneth-fritz                                      0.281ms                                                                                                                                                                            2:  lp-gerneth-fritz                                      0.306ms pmtu 1400                                                                                                                                                                  2:  no reply                                                                                                                                                                                                                                 3:  no reply                                                                                                                                                                                                                                 4:  no reply                                                                  
```

However the detected MTU seems to get ignored. Manually setting the MTU to 1400 fixes this issue. 

Wondering why this seems to get ignored though. Might be related to [this](https://mellowd.co.uk/ccie/debianubuntu-pmtud-urpf/), did not test this further though.

**Comment by therealkenc** [comment]
Merging this into /dupe #4698 which arrived to the same MTU conclusion.
