### ISSUE TITLE
Ubuntu 18.04 freeze after each reboot 

### ISSUE THREAD

**Issue by Adam123-png** [microsoft/WSL#4996]
Hello all,

I´m running Windows 10 64 bit (Intel r Core tm i5-5300 cpu) and using Ubuntu 18.04. 

I was using Ubuntu 18.04 for several last months without any problem but since last week Ubuntu freezes after approximately 5 minutes using. The only possibility is to reboot (shutdown) the whole system and Ubuntu then is working (just for other 5 minutes). If I mean freeze, any code in Ubuntu abruptly stops running and can´t do anything - I can type whatever I want but there is no response. It´s no problem to quit Ubuntu. Other Windows programs run without any problem. There hasn´t been any update that would cause this issue.

When typing "uname -a" ( all information regarding the kernel version): Linux DESKTOP-BKA8EK5 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux. So the exact Kernel Version should be 4.4.0-18362.

I´m quite new to WSL Ubuntu. Please, could you help me? Where is the problem?

Thanks a lot
Regards
Adam

**Comment by fts-01** [comment]
I have the same issue. 
After a few minutes each input causes a freeze

**Comment by Adam123-png** [comment]
Do you have any solution how address this issue? Eventually, have you tried any?
Has there been any system update that would eventually cause freezing?

**Comment by fts-01** [comment]
The bug first occurred with this kernel Update: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
I have no idea how to fix.

**Comment by Adam123-png** [comment]
Yes, the same problem in my case. I did updated the Kernel according to the link but the problem still persists. I will let u know if I find out how to correct it.

Please, does anyone know how to correct the freezing in WSF Ubuntu 18.04 that appeared after the release of WSL 2 Linux kernel in the middle of February?

**Comment by fts-01** [comment]
What is the reason for the closure of the issue?
Have you found a solution?
The problem still exists on my system.
