### ISSUE TITLE
Breaks when set default shell to pwsh

### ISSUE THREAD

**Issue by lucasteles** [microsoft/WSL#5000]
I'm trying to use PowerShell 7 as default shell in Ubuntu (18.04/16.04)

###  Steps to reproduce

-  Install plain new Ubuntu on WSL 
-  Install pwsh (using this [guide](https://docs.microsoft.com/pt-br/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7))
-  Set pwsh to default shell `chsh -s /usr/bin/pwsh username`
-  Restart WSL

###  Expected behavior
-  Start new WSL with pwsh as default shell

###  Actual behavior
-   WSL dont start, it give's an error message : 
```
: 6: export: Files/PowerShell/7:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program: bad variable name
 ```

**Comment by douglaswth** [comment]
It looks like this might be caused by `/etc/profile.d/apps-bin-path.sh` which contains the line:

```sh
    export PATH=$PATH:${snap_bin_path}
```

You can either fix it by quoting it or by just removing `snapd` as it doesn't work under WSL 1 anyway:

```sh
sudo apt purge snapd
```

**Comment by sjetha** [comment]
I'd just like to add that this happens when the default shell is set to /bin/sh, which is the default when running things like TMUX. Even switching to a different shell will not correct the issue.

**Comment by benhillis** [comment]
@douglaswth is correct. This is not a wsl-specific issue.
