### ISSUE TITLE
0x80080005 while installing Kali 

### ISSUE THREAD

**Issue by JuhJuhButts** [microsoft/WSL#5003]
I attempted to install the kali wsl on my windows insider computer, and got this error. If you need more info to help me just let me know.

**Comment by therealkenc** [comment]
Please fill out the [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md). If you are getting the error from `wsl.exe -d kali-linux` then please collect [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by JuhJuhButts** [comment]
Issue has been resolved with a full windows reset, sorry for not closing issue sooner

**Comment by bgigous** [comment]
> full windows reset

By that, I was afraid you meant a complete refresh/reinstall of Windows. However upon a restart, the issue was resolved for me.
