### ISSUE TITLE
kinect wsl

### ISSUE THREAD

**Issue by ikramooe** [microsoft/WSL#5004]
is there a way i can use kinect on wsl  with ros
couldn't find any documentation

**Comment by therealkenc** [comment]
The [libfreenect](https://github.com/OpenKinect/libfreenect) project seems active, making a bold assumption that's the go-to for kinect on Linux. Pretty safe assumption that is going to need libusb as a minimal prerequisite. Landing zone for that is #2195. Sort answer to query as of this writing: "no".
