### ISSUE TITLE
Problems with WiFi interface when type airmon-ng in Kali linux

### ISSUE THREAD

**Issue by hanonronan** [microsoft/WSL#5005]
All Kali Linux user can't run pentesting in the Windows subsystem for Linux or WSL please enable this feature for the future update

**Comment by devasish11** [comment]
any update on this? in wsl2 ifconfig only shows eth0 and loopback interfaces, neither usb nor internal wifi is detected, both are verified and compatible, i.e. wdn 3200, alfa etc. iwconfig shows no connections at all, airmon-ng shows no device! 

As per the hubbubs I thought wsl2 would be taking care of this shit, but all in vein, trying to run mdk3 airmon-ng etc. using usb wifi card, but all in vein! using 2004 build 19041 rev 172 win10 x64 enterprise, have 16gb ram, ssd, quad core and all other things to sail smoothly.

**Comment by jwothke** [comment]
Solution here is just endless loop.  If people dont have a solution, just say so or leave it alone.  THX
