### ISSUE TITLE
Issue with AMD Ryzen 7 2700X

### ISSUE THREAD

**Issue by graveto** [microsoft/WSL#5006]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
19541.rs_prerelease.200102-1216
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
SVM is enabled in BIOS.
Run PowerShell as administrator.
In PowerShell run:
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
Restart computer per instructions at:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
* What's wrong / what should be happening instead:
Windows does not boot. The system goes into perpetual repair cycle. This can be stopped by disabling SVM in BIOS which prevents me from setting WSL version to 2 with the following message:
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by onomatopellan** [comment]
It seems it's a common problem with SVM and Hyper-V. You probably will need to wait for a BIOS/chipset update.

Some people made it work disabling IOMMU on BIOS:
https://community.amd.com/thread/250096

**Comment by therealkenc** [comment]
Thanks for the link. Any word (for sake of the knowledge base) whether the problem applies to all Ryzen (5, 7, 9) or is the problem is limited to "older" chipe/chipsets with older BIOS (for some value of older)? Details over at that link are kind of thin.

**Comment by onomatopellan** [comment]
All the [similar](https://www.reddit.com/r/AMDHelp/comments/byaa8l/bootlopp_when_hyperv_and_amd_ryzensvm_enabled/) [cases](https://www.reddit.com/r/ryzen/comments/awnyi5/helpd_enabling_bios_features_for_hyperv_vms_locks/) I saw on reddit are Ryzen but then in #4771 there are plenty of people using WSL2 on Ryzen CPUs without any problem.
