### ISSUE TITLE
If the wsl can support windows form directory?

### ISSUE THREAD

**Issue by sffred** [microsoft/WSL#5008]
When using wsl, since it is a commend console, I'd like to just drag some files into the console and it will turn into its path, so that some simple commands can be easily excuted just like it in cmd does. But I am frustrated that in wsl the file will still turn into windows form directory like "C:\Program Files" rather than /mnt/c/'Program Files'. If wsl can support windows form directory, it will be more convenient to use.

**Comment by therealkenc** [comment]
You could ask over in [microsoft/terminal](https://github.com/microsoft/terminal) but it might be (?) a complicated ask (not sure). Speculation being: a terminal emulator doesn't know what is happening inside it. You could be calling wsl.exe from cmd.exe. Or you might not. You could even be calling `cmd.exe` or `powershell.exe` from inside WSL. There is no obvious way (to me) that the terminal can know the context.

**Comment by sffred** [comment]
Y

> You could ask over in [microsoft/terminal](https://github.com/microsoft/terminal) but it might be (?) a complicated ask (not sure). Speculation being: a terminal emulator doesn't know what is happening inside it. You could be calling wsl.exe from cmd.exe. Or you might not. You could even be calling `cmd.exe` or `powershell.exe` from inside WSL. There is no obvious way (to me) that the terminal can know the context.

Yes, I know that the problem relates to both microsoft/terminal and microsoft/wsl, but as you have said, a terminal emulator can't know what is happening in it. So a more complicated way to solve the problem is not let the windows terminal to carry out the task but let the bash shell in wsl to do this, and this is an issue for microsoft/wsl, although it seems to have a lot to do with microsoft/terminal, its user experience, etc.

**Comment by therealkenc** [comment]
> bash shell in wsl

The bash shell is unaware of a drag-and-drop, which is a niceity of the terminal emulator. Bash reads characters off a tty. Bash doesn't (and can't) even know if your terminal emulator is running on another machine on another continent via `ssh`.

**Comment by sffred** [comment]
> > bash shell in wsl
> 
> The bash shell is unaware of a drag-and-drop, which is a niceity of the terminal emulator. Bash reads characters off a tty. Bash doesn't (and can't) even know if your terminal emulator is running on another machine on another continent via `ssh`.

You didn't understand. Only the wsl has the needs to recognize "X:\*" as "/mnt/x/*", and if the special shell in wsl is capable of this task, we do not need to change the behavior of drag-and-drop or ssh terminal on another machine. It is a recognize task in wsl itself. When using a ssh client on windows to connect to another linux machine, we do not need to use windows form directory because there's no windows directory on that remote machine at all. The only application scenarios is when using wsl and the windows disk is mounted under the subsystem.

**Comment by therealkenc** [comment]
> You didn't understand. 

No; I understood how you wish it would behave clearly, and explained why such behavior not likely. [While deferring to the console peeps for the hard no.]

> Only the wsl has the needs to recognize "X:*" as "/mnt/x/*"

"The WSL" is a kernel emulator, or more properly, a reimplementation of the Linux kerrnel (in WSL2 it is real Linux kernel in a VM). A Linux kernel does not know what a drag-and-drop means. It performs `read(2)` and `write(2)` operations on a tty.

> and if the special shell in wsl 

There is no special shell in WSL. The shell in WSL is unadulterated GNU `bash`, or another Linux shell of your choosing, like `zsh` or `fish`. Even if you were to write a shell on your own, from scratch, it would not know that a drag and drop operation in the terminal happened either. It is a bunch of characters coming down the tty from the remote side, which your shell is reading. As if you typed them yourself on the keyboard in the terminal yourself.

> and can be solved perfectly by adding this function to the bash shell in wsl

It cannot<sup>1</sup>. Though you may [fork](https://savannah.gnu.org/git/?group=bash) GNU `bash` (or another shell) and attempt to implement the feature as an exercise.


[<sup>1</sup>You could probably prove me wrong with a heuristic that recognized really fast tty input that plausibly pattern-matched a Windows path. If someone told me it couldn't be done and bet enough, that's what I'd do.]

**Comment by sffred** [comment]
All right, but if I could fork bash, make it check all the X:/ in its input and change it to /mnt/x/ before going on, then it would be solved without dealing with the drag-and-drop behavior. May be its not the task for wsl, or maybe a special plugin is what I need.

**Comment by therealkenc** [comment]
It wasn't a serious proposal. The answer was "it cannot". You'd only do it on a dare. The hack would break pasting a windows path into a text editor (say nano), a perfectly reasonable thing to do. You'd have better luck getting the terminal emulator to understand context. Maybe with a magic VT sequence "set path drop translation behavior". [Also not an especially serious proposal. But that is how the title bar text in the terminal gets set, for example.]
