### ISSUE TITLE
two wsl2 instance how to connect

### ISSUE THREAD

**Issue by gao4263** [microsoft/WSL#5011]
I have two wsl2 instance on the same win10  computer:
1.  one is debian  10,  install a mysql server,  
2.  the other is centos 7,    install a mysql client

I want to use the  mysql client on centos to  connect the  mysql server on debian .    It doesn't work , how solve this problem

**Comment by WSLUser** [comment]
They should both have separate IP addresses. Treat it like you would two actual independent servers on a network. Point the client towards the server IP and vice versa. If that is failing, then an `strace` would help. Also be sure to check your FW to be sure the connections aren't getting blocked.

**Comment by therealkenc** [comment]
> They should both have separate IP addresses.

No.

![image](https://user-images.githubusercontent.com/7049700/77598581-6fb28200-6ebf-11ea-9831-d8d1cf406a3c.png)

> It doesn't work , how solve this problem

That is too open ended to get much in the way of help from the community. If your mysql service is listening on 0.0.0.0 on the debian 10 side, and you connect to the `hostname -I` from the centos 7 client side, you should be good.
