### ISSUE TITLE
Distribution cannot be executed after termination

### ISSUE THREAD

**Issue by were** [microsoft/WSL#5013]
I have a Ubuntu distribution converted from WSL1.
Every time after shutting it down, I cannot use `wsl -e` to boot it again.
It gives me:
```
The remote procedure call failed and did not execute.
```

**Comment by therealkenc** [comment]
I have hit the same error on 19592. Reboot resolved. Something might have regressed in recent Insider; not sure. Variation #4998.

**Comment by were** [comment]
> I have hit the same error on 19592. Reboot resolved. Something might have regressed in recent Insider; not sure. Variation #4998.

Yeah, I used this. It is a good workaround. I hope it can be fundamentally fixed in later versions.

**Comment by were** [comment]
Btw, this persists on 200321-1719.
