### ISSUE TITLE
If WSL becomes full, it wont open again

### ISSUE THREAD

**Issue by nntantidakis** [microsoft/WSL#5015]
I filled up all 250gb of usable space in WSL2 Ubuntu 18.04, and i tried expanding the vhd file to 500GB. After that, when i open WSL, window closes almost immediately without any output to the console. While running wsl --list --running shows that no distro is running.

I tried also running the distro through LxRunoffline and the output i got is this : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Please give us a way of expanding the VHDX file with safe methods.

**Comment by Biswa96** [comment]
It's already answered. Please see the procedure here https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes

**Comment by nntantidakis** [comment]
Thank you. By googling my issue about resizing, i wasn't able to find this procedure, so i used the method that Hyper-V uses to resize vhdx files. But i still cannot understand why just resizing the disk with this tool, rendered the distro broken, and thats why i posted it as an issue.

**Comment by nntantidakis** [comment]
It seems it wasnt the resizing the problem. When WSL becomes full and you dont monitor it, and you close it, it wont re-open.

**Comment by adrastogi** [comment]
The issue here seems to be resolved, so I'm marking this as closed. Thanks!
