### ISSUE TITLE
zsh service using 35% cpu constantly after exiting ssh session.

### ISSUE THREAD

**Issue by AndeYashwanth** [microsoft/WSL#5016]
* Your Windows build number:  Microsoft Windows [Version 10.0.18363.720]

* What you're doing and what's happening: 
I have powerlevel 10k installed on Ubuntu wsl.
Steps to reproduce:
-> open ubuntu wsl.
-> ssh into a server using ``` ssh user@abcd.com ```.
(Task manager shows ssh and zsh processes(using <1% cpu))
-> close the tab.
immediately task manager starts showing zsh process with 37% cpu usage.
If I do this multiple times, multiple processes of zsh are spawned and use all my CPU.

* What's wrong / what should be happening instead:
zsh should be stopped when wsl window is closed. If stopping processes is not possible, it should not use 37% cpu.

**Comment by therealkenc** [comment]
This is almost certainly variation #3914 ([message](https://github.com/microsoft/WSL/issues/3914#issuecomment-475451084)).

**Comment by therealkenc** [comment]
Call it /dupe #3914 for lack
