### ISSUE TITLE
Can't connect to local server started in WSL2 from Windows

### ISSUE THREAD

**Issue by wanderingminstrel** [microsoft/WSL#5018]
* Your Windows build number:  Version 10.0.19041.172

* What you're doing and what's happening: 
I'm unable to connect to a rails server started in my WSL2 instance of Ubuntu.  The server starts as expected and is able to receive requests from ubuntu:

![image](https://user-images.githubusercontent.com/30158500/77744891-3dfe0000-7012-11ea-988c-d86ee1ae3ad5.png)

![image](https://user-images.githubusercontent.com/30158500/77744946-579f4780-7012-11ea-8cae-18dfc8a75a0f.png)

However when trying to access via windows, I get a ERR_CON_REFUSED error:

![image](https://user-images.githubusercontent.com/30158500/77745010-743b7f80-7012-11ea-8cb4-17dccfc037f8.png)

Issue doesn't seem to apply to port 80, for example, running "sudo nc -l 80" and then making a request from windows browser results in ubuntu receiving the request:

![image](https://user-images.githubusercontent.com/30158500/77745153-b4026700-7012-11ea-9ad4-af62df082df1.png)

This issue also occurs when starting mailcatcher on port 1080, I'm unable to access mailcatcher from a windows browser event though it is accessible from within ubuntu: 

Mailcatcher in Links:
![image](https://user-images.githubusercontent.com/30158500/77745308-f0ce5e00-7012-11ea-854d-bc27d6a7b05f.png)

Trying to connect in Chrome on Windows:
![image](https://user-images.githubusercontent.com/30158500/77745389-13607700-7013-11ea-81d3-ba5fd95fc731.png)

This was working up until yesterday evening, however has now stopped working.  I also updated my windows install to KB4552455 earlier in the day yesterday, but am unsure whether this is related or not.

**Comment by crramirez** [comment]
Hello,

This is configured to only Listen in the local interface: tcp://127.0.0.1:3000. Configure it to listen in all interfaces, something like tcp://0.0.0.0:3000

Regards,
Carlos

**Comment by wanderingminstrel** [comment]
Hi @crramirez .

Thanks for you reply, I tried this, but unfortunatey I'm getting the same result:

![image](https://user-images.githubusercontent.com/30158500/77757934-07cc7a80-702a-11ea-9253-72881d5b47d4.png)

**Comment by crramirez** [comment]
Ok I am out of ideas

**Comment by therealkenc** [comment]
Other half is the IP address on the client. Once you are listening on `0.0.0.0` (which looks good in the screencap), use the IP address returned by `hostname -I` on the WSL side on the client. Likely same as #4851, which is open and actionable (contrast question, answered).

**Comment by wanderingminstrel** [comment]
I somehow managed to get it working again.  Steps I carried out that resolved the issue:

1) run the following command in Powershell
`Get-Service LxssManager | Restart-Service`
2) Enabled the following Under "Turn Windows features on and off"
- Hyper-V
- Windows Hypervisor Platform
3) Restart

No idea what of the above caused the issue to go away, but it seems to be working now.

**Comment by Sun-FreePort** [comment]
> I somehow managed to get it working again. Steps I carried out that resolved the issue:
> 
> 1. run the following command in Powershell
>    `Get-Service LxssManager | Restart-Service`
> 2. Enabled the following Under "Turn Windows features on and off"
> 
> * Hyper-V
> * Windows Hypervisor Platform
> 
> 1. Restart
> 
> No idea what of the above caused the issue to go away, but it seems to be working now.

I only run `Get-Service LxssManager | Restart-Service`, the error is resolve!

Thank you!

**Comment by czepesch** [comment]
> > I somehow managed to get it working again. Steps I carried out that resolved the issue:
> > 
> > 1. run the following command in Powershell
> >    `Get-Service LxssManager | Restart-Service`
> > 2. Enabled the following Under "Turn Windows features on and off"
> > 
> > 
> > * Hyper-V
> > * Windows Hypervisor Platform
> > 
> > 
> > 1. Restart
> > 
> > No idea what of the above caused the issue to go away, but it seems to be working now.
> 
> I only run `Get-Service LxssManager | Restart-Service`, the error is resolve!
> 
> Thank you!

Windows updated yesterday, had similar issue.
In my case it was:
```
Enabled the following Under "Turn Windows features on and off"
Hyper-V
Windows Hypervisor Platform
```
