### ISSUE TITLE
rename() syscall returns EPERM when target is non-writable but owned file on drvfs

### ISSUE THREAD

**Issue by sonologic** [microsoft/WSL#5019]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.18363.657]`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Make sure you have C:\ mounted as /mnt/c, and create a directory C:\Test that is accesible to your WSL user:

```
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
```

Then:
```
cd /mnt/c/Test
:> foo
:> bar
chmod ugo-w {foo,bar}
cat << EOF > rename.c
#include <stdio.h>
#include <errno.h>

void main(int argc, char* argv[])
{
    int ec = rename("foo", "bar");

    if(ec)
    {
        perror("Failed");
    }
    else
    {
        printf("Success\n");
    }
}
EOF
gcc -o rename rename.c
./rename
```

On WSL, when doing this on a drvfs filesystem, it prints:

```
Failed: Permission denied
```

* What's wrong / what should be happening instead:

On real linux, this prints:

```
Success
```

On a lxfs filesystem in WSL it also prints ```Success```.

Note that on older WSL builds, this also prints ```Success``` on drvfs. We can run this successfully on 10.0.17763.1039, it will print ```Success``` as it should. The bug was introduced after that build.

* Strace of the failing command, if applicable: 

https://gist.github.com/sonologic/037bbc6718e500f361a82e1686d8e02a

* Notes

This issue surfaced when running perforce's 'p4 sync' command in a perforce workspace on a drvfs filesystem.

**Comment by snoopotic** [comment]
Hi, I can approve this.
This seems to be an DRVFS Issue that is not yet fully POSIX compliant.
Somehow readonly-Files cannot be replaced in drvfs-mounts. Although you can manually remove them and place files...

Expected Behaviour:
```
## rootfs mount in wsl:
> cd /home/snoopotic/test
> touch from.file to.file
> chmod 444 *file
> l
total 0
drwxr-xr-x 1 snoopotic snoopotic 4096 Apr  5 09:38 .
drwxr-xr-x 1 snoopotic snoopotic 4096 Apr  5 08:00 ..
-r--r--r-- 1 snoopotic snoopotic    0 Apr  5 09:38 from.file
-r--r--r-- 1 snoopotic snoopotic    0 Apr  5 09:38 to.file
> mv -v from.file to.file
mv: replace 'to.file', overriding mode 0444 (r--r--r--)? y
renamed 'from.file' -> 'to.file'
```

Actual Behaviour:
```
## drvfs mount (C:\ on /c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=111,metadata,case=off))
> cd /c/Users/snoopotic/test
> touch from.file to.file
> chmod 444 *file
> l
total 0
drwxr-xr-x 1 snoopotic snoopotic 4096 Apr  5 09:33 .
drwxr-xr-x 1 snoopotic snoopotic 4096 Apr  5 09:34 ..
-r--r--r-- 1 snoopotic snoopotic    0 Apr  5 09:33 from.file
-r--r--r-- 1 snoopotic snoopotic    0 Apr  5 09:33 to.file
> mv -v from.file to.file
mv: replace 'to.file', overriding mode 0444 (r--r--r--)? y
mv: cannot move 'from.file' to 'to.file': Permission denied
```

This issue relates to many diferent tools that use "mv" or renaming things to already existing files in readonly. I changed my wsl's homedir to "$WINHOME" for soe reasons and thus sometimes run inissues because f that. 
Maybe I am missing some mount optins but I think something is mis-implemented yet - would like to see it fixed ;)

**Comment by therealkenc** [comment]
Confirmed on WSL2 19592. 

![image](https://user-images.githubusercontent.com/7049700/78537230-fdd21680-77a3-11ea-9ddd-daf730dba248.png)

The `strace(1)` has the expected:
```
rename("from.file", "to.file")          = -1 EACCES (Permission denied)
```

> Maybe I am missing some mount optins but I think something is mis-implemented yet

It is. What's surprising it is hasn't come up before (it isn't a dupe). Is there a killer app that is surfacing the pattern? [Sometimes it helps prioritization if there is one.]

**Comment by sonologic** [comment]
> It is. What's surprising it is hasn't come up before (it isn't a dupe). Is there a killer app that is surfacing the pattern? [Sometimes it helps prioritization if there is one.]

Not surprising at all because it's a new bug that has been recently introduced (please see my original bug report, at the end it says 'Note that on older WSL builds, this also prints Success on drvfs. We can run this successfully on 10.0.17763.1039, it will print Success as it should. The bug was introduced after that build.'.

For us the killer app is that we're currently unable to use perforce under WSL without nasty work-arounds, prompting a plan to migrate entirely away from windows to proper linux.

**Comment by therealkenc** [comment]
>  we're currently unable to use perforce

Heh, that was going to my wild ass guess. Thanks!

**Comment by sonologic** [comment]
Is anyone from microsoft actually looking at these issues, or is this issue tracker just for show?

**Comment by SvenGroot** [comment]
Yes, by default Windows will not let you rename over a read-only file. We do have a way to work around this for NTFS volumes at least, so this hopefully shouldn't be too hard to fix.

**Comment by haxpor** [comment]
Please allow me to kindly ask for estimated timeframe for this issue to be fixed?

**Just to add more info**. I had problem with perforce especially with `p4 sync`, and `p4 unshelve`. Although currently I have work-around script on top to allow those twos to work properly but for more complicated workflow, this will make it very difficult to tackle e.g. [backing out submitted changelist](https://community.perforce.com/s/article/3474?r=6&ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1). WSL is great, and I don't want to go back to base executing `p4` command on command prompt, or Power Shell.

**Comment by therealkenc** [comment]
Appears to be addressed circa [20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175). If people still experience what appears to be same-ish behavior in builds >20175 please file until a new cover.

/fixed 20175
