### ISSUE TITLE
[WLS2] Network share not accessible after boot/resume from standby

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/WSL#5021]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.172]

* What you're doing and what's happening:  
- Map WSL as a network drive via 9P. 
- Open Explorer Windows to that network drive, browse some folders
- Restart your PC / put it to sleep and wake again
* What's wrong / what should be happening instead:

Windows should restore those explorer folders on login, instead if errors with "could not reconnect all network drives and closes your explorer windows.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by Stanzilla** [comment]
Here's the error that comes up 
![image](https://user-images.githubusercontent.com/75278/79336610-5764de80-7f24-11ea-888d-08220b628fa2.png)

**Comment by Stanzilla** [comment]
This is still an issue with build 19041.264

**Comment by aadibajpai** [comment]
Bump, I get this issue on restart as well.

**Comment by donhector** [comment]
In my case, when I'm working in the wsl2 (ubuntu 20.04.2 from the MS Store) and then my machine goes to sleep (ie: during coffee break), when the machine wakes up,  my wls2 distro is no longer listed as "running" and I have to manually start it again so the tools that were connected to the wsl2 pre-sleep (ie: VsCode for example) can reconnect to the wsl2 after the wake up. Quite annoying.

My build is 19042.804

**Comment by ThadHouse** [comment]
Bump. Any update on this issue? Nothing seems to help.

**Comment by Stanzilla** [comment]
Sadly not, they've also been super silent about it when asked on Twitter. I assume it's just a Windows issue and not actually WSL but it's really really really annoying. 

cc @craigloewen-msft

**Comment by Stanzilla** [comment]
@craigloewen-msft any chance this could get fixed in Windows 11? Windows 10 would be nice but I understand most dev has been moved to 11 already?

**Comment by craigloewen-msft** [comment]
The main challenge that we've had here is reproing it. I've been using this setup on my machine and tried to repro it over the past few days but haven't had any success. I'm on Windows 10 build 22000. Any other tips on reproing this problem?

**Comment by Stanzilla** [comment]
Sadly not really. That's all there is to it for me, seems to be a recurring issue on Windows though, not even WSL specific:

- https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/mapped-network-drive-fail-reconnect
- https://www.youtube.com/watch?v=q8KVJdgewNk

I have not tried this one yet: https://www.partitionwizard.com/partitionmagic/could-not-reconnect-all-network-drives.html#:~:text=Disconnect%20network%20drive.-,Solution%202.%20Force%20Windows%20%E2%80%9CAlways%20wait%20for%20the%20network%20at%20computer%20startup%20and%20logon%E2%80%9D,-When%20you%20start

**Comment by jamieburchell** [comment]
Sometimes when I launch WSL, I get error messages about the file system being read-only. I see those because my .bashrc sets various things up which complain. Not sure if it's related. Again the "fix" is to shutdown WSL and start it again.

**Comment by Dylan-Brotherston** [comment]
I am also experiencing this issue. Build 19044.1266
I have found that it doesn't happen immediately after a reboot.
Either it takes some amount of time after a reboot or some number of resumes before this issues takes effect.

**Comment by Stanzilla** [comment]
Damn, issue is now back, even with that GP enabled, on Windows 11 22000.282.

**Comment by jamieburchell** [comment]
If I attempt to delete a folder stored in WSL of many files from Windows, nine times out of ten Windows Explorer will hang and the entire OS grinds to a halt. I need to logout or reboot, and nearly every time WSL then fails to start until I issue a wsl --shutdown first. The platform just seems really unstable.

**Comment by kamcknig** [comment]
This happens to me as well. To get it to work I can simply open a terminal and start wsl back up and immediately everything works.

Windows 11 Home build 22000
