### ISSUE TITLE
WSL CAN'T START

### ISSUE THREAD

**Issue by wpp2014** [microsoft/WSL#5022]
WSL can't start on my windows.
![QQ截图20200328113955](https://user-images.githubusercontent.com/7447933/77814114-2a719880-70e9-11ea-9007-9051797750bf.png)
![QQ截图20200328114013](https://user-images.githubusercontent.com/7447933/77814116-2cd3f280-70e9-11ea-96c9-5452f5d919d8.png)
![QQ截图20200328114148](https://user-images.githubusercontent.com/7447933/77814117-2e9db600-70e9-11ea-9dc4-0cce54bc3f06.png)

**Comment by craigloewen-msft** [comment]
Do you just see a blank screen with a blinking cursor? 

This could be related to these two issues: https://github.com/microsoft/WSL/issues/4055 and https://github.com/microsoft/WSL/issues/4047

I'd recommend reading those threads to see the comments there and see if that can resolve your issue!

**Comment by wpp2014** [comment]
> Do you just see a blank screen with a blinking cursor?
> 
> This could be related to these two issues: #4055 and #4047
> 
> I'd recommend reading those threads to see the comments there and see if that can resolve your issue! I'll also mark this as a duplicate since I believe we're tracking it elsewhere.

**Comment by wpp2014** [comment]
> Do you just see a blank screen with a blinking cursor?
> 
> This could be related to these two issues: #4055 and #4047
> 
> I'd recommend reading those threads to see the comments there and see if that can resolve your issue! I'll also mark this as a duplicate since I believe we're tracking it elsewhere.

Ok, thanks for your suggestions
