### ISSUE TITLE
Space in username breaks wsl integration cache

### ISSUE THREAD

**Issue by wesgarland** [microsoft/WSL#5024]
* Your Windows build number: Microsoft Windows [Version 10.0.18362.720]

My WSL is the Ubuntu flavour of 
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #476-Microsoft Fri Nov 01 16:53:00 PST 2019

* What you're doing and what's happening:  launching bash from a user whose name includes a space breaks /etc/profile.d/wsl-integration.sh 

* What's wrong / what should be happening instead:

> PS C:\Users\Jack Troughton\git\dcp-jason> bash
> -bash: [: /mnt/c/Users/Jack: binary operator expected
> mkdir: cannot create directory ë/mnt/c/Users/Jackí: Permission denied
> -bash: $WSL_INTEGRATION_CACHE: ambiguous redirect
> 
> 

The reason it breaks is due to incorrect quoting around $HOME and things derived from it.  It looks like you have parallel issues as well which could break pulse audio on a machine with a space in its hostname (is that legal in windows-land?)

I have attached a zip file containing a fix, both the complete script and a unified context diff.  I hereby place these files in the public domain, free for use by anybody for anything.

[wsl-integration-fix.zip](https://github.com/microsoft/WSL/files/4397119/wsl-integration-fix.zip)

**Comment by DHowett-MSFT** [comment]
This should be reported to Ubuntu, as they own the integration script.

**Comment by therealkenc** [comment]
Right this is [wslu](https://launchpad.net/ubuntu/+source/wslu/2.3.2-0ubuntu4) if I follow correctly.

**Comment by wesgarland** [comment]
Thanks - did not know that, appreciate the comment. Will follow up with Canonical.
