### ISSUE TITLE
No NUMA support available on this system.

### ISSUE THREAD

**Issue by vrastil** [microsoft/WSL#5025]
* Windows build number:  10.0.19592.1001

* Systeminfo:  [system.info.txt](https://github.com/microsoft/WSL/files/4397203/system.info.txt)

* Windows Features:  ![windows_features](https://user-images.githubusercontent.com/10885653/77824058-f9509280-70ff-11ea-9dfd-d48a1044ec75.png)

* Linux distro: Ubuntu-18.04 (WSL version 2)

* running comand under Ubuntu `numactl --show` results in:
````
physcpubind: 0 1 2 3
No NUMA support available on this system.
````

* Strace: [numactl.strace.txt](https://github.com/microsoft/WSL/files/4397202/numactl.strace.txt)

---

How can I enable Non-uniform memory access in WSL2?
I checked in BIOS that the virtualization is enabled and I have no problem running this command on linux host

**Comment by onomatopellan** [comment]
You will need to use a [custom kernel](https://microhobby.com.br/blog/2019/09/21/compiling-your-own-linux-kernel-for-windows-wsl2/) with "NUMA Memory Allocation and Scheduler Support" enabled.

With an intel i5 9400F CPU:
```
~$ numactl --hardware
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5
node 0 size: 12747 MB
node 0 free: 12615 MB
node distances:
node   0
  0:  10
~$ numactl --show
policy: default
preferred node: current
physcpubind: 0 1 2 3 4 5
cpubind: 0
nodebind: 0
membind: 0
```

**Comment by therealkenc** [comment]
Forward /dupe #5423 as landing zone (10 likes over there as of this writing).
