### ISSUE TITLE
Wsl2 sometime corrupt .zsh_history and git

### ISSUE THREAD

**Issue by lrnzfrr** [microsoft/WSL#5026]
Wsl2 often corrupt .zsh_history  file. 
Other times corrupt git rep ( i use git in wsl, not win version ).

wsl distro: Ubuntu 18.04
wsl version: 2
windows ver: 10.0.19041.172

**Comment by shrestaz** [comment]
Same here. Its not really reproducible as it happens randomly.
The obvious fix for me is to edit the `.histfile` and remove the culprit entry.

My choice of distro is [Arch Linux](https://github.com/yuk7/ArchWSL), which is not officially supported but that shouldn't be an issue.

WSL distro: Arch
WSL version: 2
Shell: zsh 5.8
Windows Version: 10.0.19592.1001

![image](https://user-images.githubusercontent.com/9460504/77914807-bbd23d80-7296-11ea-92f9-5a37e9271979.png)

**Comment by onomatopellan** [comment]
I also had file corruption problems with Windows 10 but not only on WSL.

In my case it was the Fast Startup feature. I was dual booting with another Windows 10 Insider build and it was a mess every time I tried to boot the other Windows.
Since I disabled that feature I had no problems with file corruption.

**Comment by GSPATalinjug** [comment]
Same here. Corrupt .zsh_history and .git

WSL DIstro: Ubuntu 20.04
WSL Version: 2
Windows Version: 10.0.19041

**Comment by luigimannoni** [comment]
Same here, corruption appears randomly after reboots or sleep wake-ups.

WSL DIstro: Ubuntu 20.04
WSL Version: 2
Windows Version: 10.0.19041.330 Insider's preview (Slow Ring)

I have a dual boot setup so fast startup is already disabled on my system.

**Comment by antonmaju** [comment]
i just got this corrupt git repo issue, happened twice in a span of a week.
i dual boot win 10 and manjaro,
wsl2 distro is ubuntu 20.04, and files are in wsl file system

**Comment by markprzepiora** [comment]
This happens to me about once per month in WSL2. Corrupts `~/.zsh_history` (adds some garbage characters to the file) as well as corrupting files in my the `.git` directory of the project I'm working on.

Fast Startup feature is disabled.

**Comment by elibarzilay** [comment]
I have the "blessing" of getting this history file corruption on each and every reboot, possibly because I run a wsl job on startup and a window is kept open.  Based on @anaisbetts's comment re the VM power being turned off impolitely, I tried to add a task when windows shuts down [based on this page](https://superuser.com/a/844579/64068), with the action being `wsl.exe --shutdown`, and trying a few reboots I didn't get the corruption.

Not enough data to make this more than a personal anecdote, but maybe others will try it too...

**Comment by squeaky-pl** [comment]
I sometimes get this on reboots. when i open `.zsh_history`  i visually search for garbage and delete the particular line which tends to be located near the end.

This can also happen when force restarting WSL2, in case networking stops working with:

```
Restart-Service -Force -Name hns
Restart-Service LxssManager
```

**Comment by marceloavf** [comment]
@elibarzilay I did create this script to run `wsl.exe --shutdown` too and seems the problems have ceased.

For anyone who wants to try it too to stop corrupting history and git:

1. Create a Basic Task in Task Scheduler
2. Name it `WSL Shutdown`
3. Set the options when a specific event is triggered:
```
Type : On Event (Basic)
Log : System
Source : User32
EventID : 1074
```
4. Set action as initiate a program/script
5. Set `wsl.exe --shutdown` and confirm

I'm using 
_WSL DIstro:_ Ubuntu 20.04
_WSL Version:_ 2
_Windows Version:_ Windows 10 20H2

**Comment by elibarzilay** [comment]
One warning though: at least in one case I had lost a file that was open in a windows app (via `wsl$`) which tried to save it after shutdown started, and it ended up with a corrupt (all NULs) file.

**Comment by luigimannoni** [comment]
I've added a task in the scheduler like @marceloavf suggested, however I just got another repository corrupted on the last shutdown.

Manually shutting down with `wsl.exe --shutdown` before shutting down seems to be still the more reliable method

**Comment by Empereol** [comment]
I'm also encountering this issue. Both `.zsh_history` and project git files are being corrupted. It appears to happen somewhat randomly to me...

- WSL Distro: `Ubuntu 20.04`
- WSL Version: `2`
- Windows OS Build: `19042.630`
- Fastboot is disabled.
- Primarily using the [Windows Terminal app](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and sometimes using the integrated terminal in VSCode.

**Comment by ridays2001** [comment]
![image](https://user-images.githubusercontent.com/46166258/99387595-45a04b00-28fa-11eb-89a6-145002c859ec.png)
WSL corrupts my git repo every week.
- Distro: `Ubuntu 20.04`
- WSL2
- Windows 20H2 (Build -`10.0.19042.630`)
- Using Windows Terminal by Microsoft.

**Comment by MartinMuzatko** [comment]
Same here. Need to start testing the shutdown method.
What are your methods to revert .git? right now I just clone the repo again and move all my changes there, so I don't lose my changes at least.

**Comment by ridays2001** [comment]
I use this:
```
rm -rf .git &&                    # delete old corrupted repo
git init &&                       # initialise new repo
git remote add origin "${url}" && # link to old repo
git fetch &&                      # get old history
git reset origin/master --mixed   # force update to old history
```

**Comment by edrevo** [comment]
@therealkenc, not sure if you are the best person to ping, but I've seen you add the "bug" tag to other issues in this repo. It would nice if this issue could be triaged and acknowledged as a bug, since it seems to affect a bunch of people (25 likes in this issue, plues other open related issues like https://github.com/microsoft/WSL2-Linux-Kernel/issues/168 or https://github.com/microsoft/WSL/issues/5895). Right now I have the feeling nobody is looking at this, and I can confirm not only that it happens quite often, but also that it is a very annoying bug from a user perspective. From what I gather in the different issues, it seems to be related to how the WSL subsystem gets shut down.

Is there anything I can do to get this issue triaged?

**Comment by TheFirstMe** [comment]
This happened to me today. My local git repo got corrupted. Thankfully I had no pending commits.

**Comment by TheFirstMe** [comment]
> I use this:
> 
> ```
> rm -rf .git &&                    # delete old corrupted repo
> git init &&                       # initialise new repo
> git remote add origin "${url}" && # link to old repo
> git fetch &&                      # get old history
> git reset origin/master --mixed   # force update to old history
> ```

I have two active branches: master and dev. What would the approach be then?

**Comment by bleepster** [comment]
This happened to me today on a Windows 10 Pro, version 20H2, build 19042.685. I have a different laptop with Windows 10 Home Single Language, version 2004, build 19041.685 and this issue does not occur.

**Comment by luastoned** [comment]
> 
> 
> > I use this:
> > ```
> > rm -rf .git &&                    # delete old corrupted repo
> > git init &&                       # initialise new repo
> > git remote add origin "${url}" && # link to old repo
> > git fetch &&                      # get old history
> > git reset origin/master --mixed   # force update to old history
> > ```
> 
> I have two active branches: master and dev. What would the approach be then?

I have found

`find .git/objects/ -size 0 -exec rm -f {} \;`

to be effective

**Comment by edrevo** [comment]
Seems like MSFT is finally looking into this issue! ♥ https://github.com/microsoft/WSL2-Linux-Kernel/issues/168#issuecomment-754106399

**Comment by craigloewen-msft** [comment]
We've identified a fix for this! I'll be closing this issue as a duplicate and tracking it over at https://github.com/microsoft/WSL/issues/5895. 

/dupe#5895

**Comment by mcandre** [comment]
@msftbot Which specific issue would that be? There are many.

**Comment by craigloewen-msft** [comment]
This is being tracked over at issue #5895 !

**Comment by lPaths** [comment]
I found a work around here. First navigate to repo dir then run this one below

```bash
find .git/objects/ -type f -empty | xargs rm; git fetch -p; git fsck --full
```

**Comment by jjaaccoobb** [comment]
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎6/‎21/‎2021
OS build	19043.1151
Experience	Windows Feature Experience Pack 120.2212.3530.0
```

```
Device name	WIN10-PVE
Processor	Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz   3.50 GHz
Installed RAM	32.0 GB
```

```
PS C:\Windows\system32> wsl -l -v
 NAME      STATE           VERSION
 *Debian    Running         1 
```

```
zsh 5.7.1 (x86_64-debian-linux-gnu)
```

I never use Command Prompt, PowerShell, or any Windows programs to modify text files or run commands in Zsh. Repositories checked out in the WSL location `~` consistently have their `.git/` directories corrupted, and very frequently `.zsh_history` is unreadable.

Bump for visibility

https://github.com/microsoft/WSL/issues/5895#issuecomment-893212275

**Comment by millette** [comment]
@jjaaccoobb See <https://github.com/microsoft/WSL/issues/5895#issuecomment-893307917> (@sarim replied in the other thread)

**Comment by craigloewen-msft** [comment]
This thread is closed, please comment on #5895 which is where we're tracking this!

@jjaaccoobb are there any repro steps that you have here for us to try this? We don't see this on the latest Insider builds and aren't able to repro the problem. If you are able to upgrade to the latest Insiders build, could you let us know if that fixes your problem?

**Comment by quentinjeanningros** [comment]
BTW the issue still exist

**Comment by asadullahnaeem-techtics** [comment]
I have faced this issue for 2 times in a week. No solution seems to work

**Comment by 66RED99** [comment]
i just face this issue

**Comment by acadjsr** [comment]
This happened to me too.
Win 11 for ARM on Snapdragon X Plus laptop.
Only one GIT repo was corrupted. (I have several repos in several directories. Only one was affected.)
MySQL database on the same WSL2 works.

**Comment by vadimmugalimov** [comment]
Same thing here
WSL is corrupting my .zsh_history file every time

**Comment by arthiccc** [comment]
its april 2026, still happened just today
The standard fix for a corrupt .zsh_history file in WSL2 involves backing up the corrupted file, extracting readable text using the strings utility, and reloading the cleaned history into the current session.  This error typically occurs due to improper shutdowns, system crashes, or concurrent terminal sessions writing to the file simultaneously, which is a known issue in WSL2 environments
To resolve the error, execute the following commands in your terminal:
```bash
cd ~
```
```bash
mv .zsh_history .zsh_history_bad
strings .zsh_history_bad > .zsh_history
```
```bash
fc -R .zsh_history
```
```bash
rm -f .zsh_history_bad   
```
