### ISSUE TITLE
Cannot access ssh server running in WSL 2

### ISSUE THREAD

**Issue by bferg88** [microsoft/WSL#5027]
**Please fill out the below information:**
* Your Windows build number:  2004 (OS Build 19041.172)

* I'm trying to access an ssh server running on port 2222 inside Ubuntu WSL 2.
ssh localhost -p2222 # this works 
ssh 127.0.0.1 -p2222 # this works
ssh [LAN IP address for my PC] -p2222 # this DOES NOT WORK
ssh [WAN IP address] # this also does not work, obviously. Note that port 22 ->2222 (in my router to the static LAN IP of my machine)
I have opened this port in my Windows Firewall and this worked on WSL 1 -- I just upgraded to WSL 2.

* What's wrong / what should be happening instead:
According to docs
https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes
you should be able to access servers running in WSL 2 via localhost, which suggests I should be able to ssh to my LAN IP on port 2222.

**Comment by bferg88** [comment]
Oh, also, I checked and the output of `ip addr | grep eth0` provides an address that does not match my PC's LAN IP -- but I don't know if it's supposed to.

**Comment by bferg88** [comment]
I checked and I can access the server as "localhost" if I use putty on my windows machine. So, I guess the problem is that traffic isn't being forwarded if you access your machine on the LAN. Is there a workaround for this or plans to make this seamless?

**Comment by ad-on-is** [comment]
That's a known issue, due to missing network bridge in WSL2. WSL2 has its own dynamic IP adress, which always changes after restarting WSL. You'd have to set a port forward on Windows to that IP and the 2222 port, and update this each time you restart WSL.

**Comment by therealkenc** [comment]
That's correct. /dupe #4150
