### ISSUE TITLE
Doesn't Recognize wsl --set-version Ubuntu 2 & wsl -l - v even after setup

### ISSUE THREAD

**Issue by fernandonjardim** [microsoft/WSL#5028]
Hello there, 

I have the latest windows build (1909), I've turned on Virtualization and the Linux System (via pannel, bios and code)

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

So I managed to Install Ubuntu, but when I try to update to WSL I get:
- Manually ([though here](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel)): I get a message "The update only applies to machine with Windows subsystem for Linux"
- Through Powershell: It doesn't recognize wsl --set-version Ubuntu & wsl -l - v even after setup .

How should I move forward? I already tried to remove all the installation and begin from 0 but still getting these errors!

**Comment by onomatopellan** [comment]
For WSL2 you need at least Windows 10 version 2004 (not released yet).

**Comment by fernandonjardim** [comment]
Hello there I am on windows insider programs, everyone on my team managed to install wls2 following the same steps, my machine was the only one that bugged  /:

**Comment by fernandonjardim** [comment]
https://www.thomasmaurer.ch/2019/06/install-wsl-2-on-windows-10/

Build 18917 or superior, my one is 1909

**Comment by fernandonjardim** [comment]
https://www.thomasmaurer.ch/2019/06/install-wsl-2-on-windows-10/

Build 18917 or superior, my one is 1909

**Comment by onomatopellan** [comment]
type winver on cmd to know the exact build number. What it shows?

**Comment by fernandonjardim** [comment]
That's it bud!
I thought I had hight build but I still on 18.363, going though updates the whole day to try to get to the highest one, thanks very much!!
