### ISSUE TITLE
When I delete a hard link of a readonly file, the readonly property of the original file is taken away

### ISSUE THREAD

**Issue by riowing** [microsoft/WSL#5031]
We have file Ads.brs, which is readonly, and then create a hard link copy hardLink.brs (with cp -l Ads.brs hardLink.brs), then remove hardLink.brs (rm -f hardLink.brs).
Expected result: Ads.brs stays as is, with readonly property as seen by both explorer and WSL.
**Actual result**: a.brs loses it's readonly property as seen by both explorer and WSL.

This doesn't always happen. I have two Ads.brs, one leads to the bug(case 1), one works fine (case 2). However I cannot find what's different between the two files with ls -l and stat.

Here is the comparison of properties ofAds.brs:
**Case1 repro**:
```
    ls -l Ads.brs
    rio@RioLe:~/proj$ ls -l ~Ads.brs
        -r--r--r-- 1 rio rio 835 Mar 17 13:12 Ads.brs
    rio@RioLe:~/proj$ stat Ads.brs
        File: Ads.brs
        Size: 835             Blocks: 8          IO Block: 4096   regular file
        Device: 10h/16d Inode: 8162774324935142  Links: 1
        Access: (0444/-r--r--r--)  Uid: ( 1000/     rio)   Gid: ( 1000/     rio)
        Access: 2020-03-30 15:18:53.937295400 -0700
        Modify: 2020-03-17 13:12:51.455972400 -0700
        Change: 2020-03-17 13:12:51.457012800 -0700
        Birth: -`
```
**Case 2, non-repro**:
```
    rio@RioLe:~/proj$ ls -l Ads.brs
        -r--r--r-- 1 rio rio 835 Mar 17 13:12 Ads.brs
    rio@RioLe:Ads.brs
        File: Ads.brs
        Size: 835             Blocks: 8          IO Block: 4096   regular file
        Device: 10h/16d Inode: 8162774324935142  Links: 1
        Access: (0444/-r--r--r--)  Uid: ( 1000/     rio)   Gid: ( 1000/     rio)
        Access: 2020-03-30 15:20:07.488791000 -0700
        Modify: 2020-03-17 13:12:51.455972400 -0700
        Change: 2020-03-26 18:25:42.637689100 -0700
        Birth: -`
```
WSL version: OS Build 18362.720, Windows 10 Home

**Comment by therealkenc** [comment]
This needs repro steps, using `touch(1)`, ln(1)`, `rm(1)`, `cp(1)` or whatever it takes. We can take as a given you're seeing _something_, but those two `ls(1)` cases in isolation aren't enough to tell what we're even looking at. A screencap with the actual end-to-end sequence might shed light.

**Comment by 0xbadfca11** [comment]
It's difficult to do, and that behaves same as explorer.

> Note that the attributes on the file are reflected in every hard link to that file, and changes to that file's attributes propagate to all the hard links.
> For example if you reset the READONLY attribute on a hard link to delete that particular hard link, and there are multiple hard links to the actual file, then you will need to reset the READONLY bit on the file from one of the remaining hard links to bring the file and all remaining hard links back to the READONLY state.
> https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

**Comment by riowing** [comment]
I updated the description so it's easier to read.
The bottom line:
    The two files, both called Roku_Ads.brs, must be different, since only one caused this problem, even though $ls and stat cannot tell the difference. 
    The repro step is quite straightforward: Roku_Ads.brs is readonly, create a hard link and remove that link, now Roku_Ads.brs is no longer readonly.
    Uploading Roku_Ads.brs doesn't help solving this bug, since it's the meta data, instead of the content of this file, that makes the difference.

@0xbadfca11   I don't reset READONLY in order to delete a file (rm -f), and never did; rm -f is enough. I never touched the READONLY and READONLY is gone, which is this bug.

**Comment by therealkenc** [comment]
This needs repro steps, using touch(1), ln(1), rm(1), cp(1) or whatever it takes. A screencap with the actual end-to-end sequence might shed light.

**Comment by riowing** [comment]
Repro steps cannot be provided because the file used to repro this issue is created by Perforce. Files created by me manually cannot repro this issue. Closing it for now

**Comment by therealkenc** [comment]
Thanks for the follow-up. Assuming "Perforce" is running on Windows (not familiar) you _might_ be able to come up with a repro using win32 [`attrib`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib) and [`mklink`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink). It would take some experimentation. If you find something that looks amiss don't hesitate to re-open. There might well be something wrong here. Or it might be correct but super nonobvious behavior.

**Comment by riowing** [comment]
Thank you therealkenc, I will update when I get new findings.

**Comment by therealkenc** [comment]
Someone had you back. Your problem is _almost_ certainly #5019. Subscribe over there.

**Comment by alecazam** [comment]
Microsoft's own rmdir/del on a hardlink change the read-only state of the files deleted.   I think this has to be done to delete the file.  But what ends up happening is the src shares the same state, and has read-only disabled on it.   This tampers with Perforce's ability to sync over read-only files, since it thinks the src file now has changed content that it isn't aware of.

This is also hard to fix.   Relative symbolic links like "mklink workingDir/link pathToLink/dst" isn't the same as "ln -s workingDir/dst workingDir/link".  And preserving and restoring read-only state around these calls, or even finding the src the hard link points to is complex to say the least.
