### ISSUE TITLE
vscode liveserver addon break my WLS

### ISSUE THREAD

**Issue by barrrettt** [microsoft/WSL#5033]
vscode + ritwickdey.liveserver addon
when run server and delete site files then WSL dont respont.

After this happens, I can't open a bash terminal. 
Even when I reboot windows, I can't access the bash terminal.

My solution is uninstall and install WSL again.

This has happened to me twice. in the same circumstances. 😢

**Comment by barrrettt** [comment]
Restart system solve but not logging out win sesion.

**Comment by sirredbeard** [comment]
Can you please provide a list of steps to reproduce?

When you say you can't access the bash terminal after reboot, what happens if you run wsl.exe from the Command Prompt?

**Comment by barrrettt** [comment]
i cant reproduce now 😞, I can't stop working XDD
but steps to reproduce:
1.run vscode + ritwickdey.liveserver addon
2. launch the liveserver on a website.
3. delete files from the website

at this point: the liveserver is not responding, the vscode bash terminal is not responding. the microsoft store app Ubuntu terminal is not responding.
(cmd wsl.exe I haven't tried it)

close win sesion and enter again: app Ubuntu terminal and vscode Remote -WSL addon is not responding.

restar win-> ok

maybe it's an unfinished thread-process?

I hope it helps. (or it's nothing)
