### ISSUE TITLE
wsl_update_x64.msi unable to run because "This update only applies to machines with the Windows Subsystem for Linux"

### ISSUE THREAD

**Issue by resigned** [microsoft/WSL#5035]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.172]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I am trying to run the kernal updater tool and I'm receiving an error that "This update only applies to machines with the Windows subsystem for Linux

* What's wrong / what should be happening instead:

I am unable to update the kernel and use WSL 2

**Comment by resigned** [comment]
I didn't mention this but I definitely have WSL 1 installed, I updated Windows with the intention of installing WSL 2. WSL 1 still runs fine.

**Comment by resigned** [comment]
Thanks.

**Comment by DeathNet123** [comment]
the same thing is happening to me I have WSL 1 already installed but WSL Update is not working

**Comment by simonpfeifhofer** [comment]
Same behaviour: WSL1 installed, unable to update. Error: "This update only applies to machines with the Windows Subsystem for Linux".

**Comment by gbr5** [comment]
Same here, did someone succeed fixing this problem?

- Updated Windows, for 2004 version and Build 19041
- Ran the command "dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart" then restart the pc
- then installed the kernel update (https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)

just as is instructed by MS https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

**Comment by ultrawebmarketing** [comment]
https://github.com/MicrosoftDocs/WSL/issues/616#issuecomment-609574285

I have just got it working by running wsl_update_x64 from powershell with admin rights as opposed to double clicking.

**Comment by streaky** [comment]
Yep this the installer doesn't request admin..

**Comment by ofaaoficial** [comment]
> [MicrosoftDocs / WSL # 616 (comentario)](https://github.com/MicrosoftDocs/WSL/issues/616#issuecomment-609574285)
> 
> Acabo de hacerlo funcionar ejecutando wsl_update_x64 desde powershell con derechos de administrador en lugar de hacer doble clic.

Its works!

**Comment by danielmrussell** [comment]
Same here. Work from a console with admin rights. (Right click menu annoying has Install, etc, but not "Run as Administrator," and the program does not correctly upgrade its rights during running. Additionally the error is a misdiagnosis.

**Comment by cristianaxion** [comment]
no funciona

**Comment by sonook** [comment]
I found the working solution, please try and let me know the result.
https://youtu.be/4czn-4uu65c

**Comment by ultrawebmarketing** [comment]
@sonook comment is blatant spam

**Comment by Opus4210** [comment]
I don't know what @ultrawebmarketing is talking about. @sonook solved my problem.

**Comment by darer** [comment]
@sonook 's solution worked for me. Thansk!

**Comment by t-vert** [comment]
I got the issue today with 10.0.19042.685 (20H2) and the workaround proposed by sonook also worked for me. By the way a typo can be noticed in the error message : "This update only applies to machines with the Windows subsytem for Linux", with a missing "s" in subsystem.

**Comment by vincentkenny** [comment]
@sonook 's solution works for me. Thanks!!

**Comment by MattConrad** [comment]
@sonook 's solution worked for me also. Thanks.

**Comment by pe-pan** [comment]
@sonook's solution worked for me.

**Comment by m-dz** [comment]
+1 for @sonook 's solution, this error is hideous!

**Comment by luke-sackash** [comment]
I was able to resolve the issue by running PowerShell as an admin and invoking the installer from there.  This fix probably applies to a anyone who is not prompted for elevated permissions when starting the installer from within explorer.

**Comment by muhnick** [comment]
Check your BIOS to ensure virtualization support is turned on...

**Comment by mimranfaruqi** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

It worked for me

**Comment by kozak127** [comment]
@sonook 
It worked for me. Microsoft Windows [Version 10.0.19041.928]

**Comment by hasan-retrace** [comment]
Just restarting worked for me.

**Comment by supersciencegrl** [comment]
Only @sonook's solution worked for me! @ultrawebmarketing is blatant spam (username checks out)

**Comment by mortroguez** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

Worked for me

**Comment by meadlai** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

awesome, it did fix this issue.

**Comment by weilonggggg** [comment]
worked for me!

**Comment by viajandee** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

This worked for me, cheers

**Comment by YuRuiii** [comment]
I just solved the problem by enabling "BIOS Back Flash". For those who have never installed WSL before this might work.

**Comment by yadangdaxia** [comment]
The solution from @sonook worked for me!

**Comment by Rafat97** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

It works for me. 
Windows 10 pro  
Version 21H1 (OS build 19043.928)

**Comment by soraia653** [comment]
> 

This did not work for me.

**Comment by ndh80** [comment]
The good old "Have you tried turning it off an on again?"...

**Comment by orhirshfeld-elbit** [comment]
> I found the working solution, please try and let me know the result.
> 
> Procedure to fix the issue :-
> 
> 1. Open "turn windows features on or off"
> 2. Uncheck both "Virtual Machine Platform" and
>    "Windows subsystem for Linux"
> 3. Press OK
> 4. Reboot your system
> 5. Open "turn windows features on or off" again
> 6. Now check both "Virtual Machine Platform"     and "Windows subsystem for Linux"
> 7. Press OK
> 8. Reboot your system again
> 9. Now run the wsl_update_x64.msi again, it should install successfully now
> 10. Go to powershell and run wsl command
> 
> ### **Demo Video for graphical representation**
> https://youtu.be/4czn-4uu65c

actually, it didn't work for me, i got same issue using Win11 version 24H2 (OS Build 26100.4061)

also everytime i try to run wsl it poping out message that i have to update but i vannot acomplish it :(


```terminal
wsl
Windows Subsystem for Linux must be updated to the latest version to proceed. You can update by running 'wsl.exe --update'.
For more information please visit https://aka.ms/wslinstall

Press any key to install Windows Subsystem for Linux.
Press CTRL-C or close this window to cancel.
This prompt will time out in 60 seconds.
The requested operation requires elevation.
Downloading: Windows Subsystem for Linux 2.5.7
The server name or address could not be resolved
```

I tried also other solution like one offically from Microsoft with "dism.exe" commands for offline install and got same results

https://learn.microsoft.com/en-us/windows/wsl/install#update-to-wsl-2

**Comment by sadiqsalau** [comment]
1. First thing to do is to update WSL (System Wide) - https://github.com/microsoft/WSL/releases/latest
