### ISSUE TITLE
Configure mouse-button usage

### ISSUE THREAD

**Issue by lzsiga** [microsoft/WSL#5036]
Hi, is there a way to configure mouse-button usage? I'd prefer to use the Unix tradition: left/right: selection, middle: paste.

**Comment by therealkenc** [comment]
This would be a feature request or question over at [microsoft/terminal](https://github.com/microsoft/terminal).

**Comment by lzsiga** [comment]
Well, I don't have `wt.exe` only `wsl.exe`. Anyways, thank you for your answer.

**Comment by lzsiga** [comment]
Feedback: I realized that this be easily solved (along with the unconfigurable fixed UTF8 character set): I can run `sshd` in `WSL`, then I can use PuTTY to connect 127.0.0.1:22
