### ISSUE TITLE
[WSL2] [Windows interop] Piping to fzf in WSL make fzf un-interactable

### ISSUE THREAD

**Issue by kiennq** [microsoft/WSL#5037]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.172]

* What you're doing and what's happening:
1. Install fzf with
``` sh
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all
```
2. From powershell command prompt, type `echo 'aaaaa' | wsl /absolute/path/to/fzf` (should be absolute path of `~/.fzf/bin/fzf`)
3.  `fzf` interactive interface is showing up, however not interactable (cannot type anything)
![image](https://user-images.githubusercontent.com/2631472/78233709-1aa2eb80-7511-11ea-8180-5fde75b653ff.png)

* What's wrong / what should be happening instead:
Should be able to type and select candidate.
Note that this works in WSL1.

* Strace of the failing command, if applicable:  
How can I take strace in this piping case?

**Comment by therealkenc** [comment]
Likely variation #4754
