### ISSUE TITLE
The mechanism of memory recycling?

### ISSUE THREAD

**Issue by were** [microsoft/WSL#5038]
I am not sure it should be in either Bug or Feature Request.

I notice that every time after I run some memory-intensive workloads, like compiling a large project or run a program frequently new/delete memory for a long time, the `Vmmem` process will consume so much memory without shrinking.

I am curious about the mechanism of memory recycling.

**Comment by onomatopellan** [comment]
That's cached memory, it was explained here: https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/

Discussion and people's workarounds in #4166.

**Comment by craigloewen-msft** [comment]
Thanks @onomatopellan you wrote exactly what I was going to post! :)

The blog post should go over all the details. I'll close this for bookkeeping since we've answered the original question, but please feel free to reopen it if you have more questions. Thanks!
