### ISSUE TITLE
openssl password visible

### ISSUE THREAD

**Issue by latepaul** [microsoft/WSL#5042]
* Your Windows build number:  Version 10.0.18362.720

* What you're doing and what's happening: 

paul@pmxps:~/tmp> openssl aes-256-cbc -a -salt -in myfile.txt -out myfile.txt.enc
enter aes-256-cbc encryption password:secret123

Verifying - enter aes-256-cbc encryption password:secret123

paul@pmxps:~/tmp> openssl aes-256-cbc -d -a -in myfile.txt.enc -out myfile.txt.new
enter aes-256-cbc decryption password:secret123

* What's wrong / what should be happening instead:

password should not be echoed to screen

* Strace of the failing command, if applicable: [openssl.trace](https://gist.github.com/latepaul/4b74ae027c75c4abeb9bc7b7abd5b93b)

**Comment by latepaul** [comment]
The above was with openSuse 15.1 which has openssl 1.1.0i 
I just tried compiling openssl 1.1.1f from source and tested that, and it does not exhibit this issue. 

I guess the bug is in openssl - although I have to believe that it doesn't reproduce on native Linux.

**Comment by therealkenc** [comment]
Can't repro here, same as #2298. This run is on WSL1 19592, but that isn't going to make a difference.

![image](https://user-images.githubusercontent.com/7049700/78462916-c2442900-768b-11ea-9ccd-fa32477681f7.png)

> although I have to believe that it doesn't reproduce on native Linux.

Impossible to verify that hypothesis absent a repro.

**Comment by therealkenc** [comment]
Appears to be SUSE specific

![image](https://user-images.githubusercontent.com/7049700/78463258-8dd26c00-768f-11ea-9720-3c17cd2eb60a.png)

Given your recompile addressed, it is probably an explainable userspace thing (termcap/termio) but I can't prove that.

**Comment by therealkenc** [comment]
Sucker for the unexplained on weekends...

On Ubuntu `OpenSSL 1.1.1  11 Sep 2018`:
```
39    openat(AT_FDCWD, "myfile.txt", O_RDONLY) = 3
39    openat(AT_FDCWD, "/dev/tty", O_RDONLY) = 4
39    openat(AT_FDCWD, "/dev/tty", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
39    ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
39    fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
39    ioctl(5, TCGETS, {B38400 opost isig icanon echo ...}) = 0
39    write(5, "enter aes-256-cbc encryption pas"..., 38) = 38
[...rt_sigaction blah blah]
39    ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
39    ioctl(4, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon -echo ...}) = 0
39    ioctl(4, TCGETS, {B38400 opost isig icanon -echo ...}) = 0
39    fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
39    ioctl(4, TCGETS, {B38400 opost isig icanon -echo ...}) = 0
39    read(4, "password\n", 4096)       = 9
```

SUSE, my run `OpenSSL 1.1.0i-fips  14 Aug 2018`:
```
99    openat(AT_FDCWD, "myfile.txt", O_RDONLY) = 3
99    openat(AT_FDCWD, "/dev/tty", O_RDONLY) = 4
99    openat(AT_FDCWD, "/dev/tty", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
99    ioctl(4, TCGETA, 0x7fb1d598c820)  = -1 ENOTTY (Inappropriate ioctl for device)
99    fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
99    ioctl(5, TCGETS, {B38400 opost isig icanon echo ...}) = 0
99    write(5, "enter aes-256-cbc encryption pas"..., 38) = 38
[...rt_sigaction blah blah]
99    fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
99    ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
99    read(4, "password\n", 4096)       = 9
99    write(5, "\n", 1)                 = 1
```

The latter is sending some `ioctl` even `strace(1)` doesn't grok. Someone super motivated would need to look at where that `0x7fb1d598c820` is coming from by building `openssl 1.1.0i` from source.

Your `strace(1)` log (always appreciated) for completeness. Oddly (and unexplained), your run is missing a `write(2)` of the string "enter aes-256-cbc encryption password" entirely.
```
openat(AT_FDCWD, "myfile.txt.enc", O_RDONLY) = 3
fstat(0, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 3), ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
read(0, "secret123\n", 4096)            = 10
openat(AT_FDCWD, "myfile.txt.new", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
fstat(3, {st_mode=S_IFREG|0666, st_size=45, ...}) = 0
read(3, "U2FsdGVkX1+bChwZlGbokrhjBr6/ngLy"..., 4096) = 45
read(3, "", 4096)                       = 0
fstat(4, {st_mode=S_IFREG|0666, st_size=0, ...}) = 0
write(4, "Hello World\n", 12)           = 12
```

**Comment by DHowett-MSFT** [comment]
The `ioctl` right before the `read` that returns password differs: `-echo` (turn echo off) on the first, `echo` (keep echo on) on the second.
