### ISSUE TITLE
Windows Subsystem for Linux Update Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by friday963** [microsoft/WSL#5043]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.172]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Image Version: 10.0.19041.172

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Image Version: 10.0.19041.172

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

Download (wsl_update_x64) > run > "This update only applied to machines with the Windows Subsystem for Linux" > Ok > WSL Update Setup wizard ended prematurely > Finish > program exits.

* What's wrong / what should be happening instead:
I would have expected the WSL kernel to be updated after the install.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by onomatopellan** [comment]
See #5014

**Comment by friday963** [comment]
@onomatopellan  Thanks for the asisstance!

**Comment by kingdavid72** [comment]
I had the same problem of setup wizard ended prematurely. I tried to install it again but failed. I could not find the program uninstall in system setting >> add or remove programs. the solution is to find **wsl_update_x64.msi** file then right-click then it will show uninstall option. uninstall and reinstall solved the problem.

**Comment by hariharan382** [comment]
not solved anything for me by doing above methods,tried reinstalling

**Comment by sarsophx** [comment]
rebooting the os and starting again the install solved for me the issue.

**Comment by izzybabcock** [comment]
> I had the same problem of setup wizard ended prematurely. I tried to install it again but failed. I could not find the program uninstall in system setting >> add or remove programs. the solution is to find **wsl_update_x64.msi** file then right-click then it will show uninstall option. uninstall and reinstall solved the problem.

Thanks! This solved the issue for me as well!!

**Comment by Bielmartin** [comment]
I had the problem in the step of wsl82 they were installed for my development environment and after my test environment realized that it could be a problem and it was connected directly to my windows update that was with error 00042. Below is my step by step:

1- press the "**Windows**" key + **R**;

2- Type "**services.msc**" and press "**OK**";

3- Look for the "**Windows Update**" service and double-click on it;

4- In "**Initialization Type**" select the "**Automatic**" option and press "**OK**";

5- Look for the "**Windows Modules Installer**" service and double-click on it;

6- In "**Initialization Type**" select the "**Automatic**" option and press "**OK**";

7- Restart the computer and try to open Windows Update.

**Comment by LAIFUA** [comment]
> I had the same problem of setup wizard ended prematurely. I tried to install it again but failed. I could not find the program uninstall in system setting >> add or remove programs. the solution is to find **wsl_update_x64.msi** file then right-click then it will show uninstall option. uninstall and reinstall solved the problem.

In my env,  use your way to uninstall **wsl_update_x64.msi** , then reboot os and reinstall  ,that has worked

**Comment by Biswa96** [comment]
It is not required to install wsl_update_x64.msi. The latest Linux kernel comes with WSL from Windows Store.
