### ISSUE TITLE
Enable Changing Where Subsystem Files are Stored

### ISSUE THREAD

**Issue by Vandivier** [microsoft/WSL#5044]
**Is your feature request related to a problem? Please describe.**
My C drive is near capacity.

When using WSL + Ubuntu, I ran `Add-AppxPackage` from my storage drive (D:).

I also previously configured my Windows 10 Storage settings to "Change Where New Content is Saved" including "New Apps will Save to" my storage drive, but I notice the files are put on C: anyway. I would argue this is a bug, but [Stack Exchange states](https://askubuntu.com/questions/759880/where-is-the-ubuntu-file-system-root-directory-in-windows-subsystem-for-linux-an) it's simply not supported.

**Describe the solution you'd like**
1. If I run Add-AppxPackage on a remote drive, the subsystem files are stored on that drive.
2. From inside subsystem, if I install a package it can be saved to a folder I chose, potentially on another drive.

The two above can be implemented separately. For implementation on WSL side, I think it's easier to continue WSL installation on my main drive, but when I `sudo apt-get install unzip`, for example, that stuff can be put on my storage drive.

**Comment by therealkenc** [comment]
/dupe #449. YRMV on the discussion over there; it is just the landing zone for the topic.

There is `wsl.exe --import` and `--export` on recent releases, although that isn't quite the same ask.
