### ISSUE TITLE
Trying to get back my wsl 2 data

### ISSUE THREAD

**Issue by shane99a** [microsoft/WSL#5045]
For whatever reason, my bash decided to deadlock, and restarting didn't help. I tried to repair Ubuntu 18.04 but that seemed to have removed my ubuntu all together. When I open ubunutu it started installing again. I don't know what happened, but all the data that I had in wsl 2 ubuntu is now gone. I need to get it back otherwise I have to setup my home folder all over again with my projects, packages, aliases, etc. Is there any way I can find those files again, or get my wsl2 setup back to normal. This deadlock thing that bash on windows suffers from needs to be figured out, it's such a frustrating error and it just happens randomly.

I had to setup ubunutu with wsl2 all over again. Does wsl 2 not persist the data between reinstalls? Doesn't make sense why its not.

I have been to this location, but I don't see where I can find the old data, if its not already deleted:

`\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc`

### If my data is lost, how do I ensure in the future a simple deadlock doesn't cause me to lose my entire day figuring it out and setting up everything ALL OVER AGAIN?

**Comment by onomatopellan** [comment]
What Windows build are you running?

>I tried to repair Ubuntu 18.04

What did you exactly do a this step?

In WSL2 the data should be in a `ext4.vhdx` file in `\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState`

**Comment by shane99a** [comment]
@onomatopellan 

I went to _Add or Remove programs_, Search Ubuntu, and went to Advanced Options, clicked Reset. Restarted my computer and from that point bash would use old wsl. When trying to get back to wsl2, I opened Ubunutu from windows start menu, and it was telling me it is installing. At that point, it was becoming clear that my old ubuntu is gone.

I found the ext4 image file but I don't think its the one that I had before, I think when ubuntu installed again, it overwrote it. How can I tell though?

**Comment by onomatopellan** [comment]
Yes, it's probably overwritten. You can tell from the file size, specially if you installed lots of things in the old Ubuntu.

A very similar problem was fixed in build 19002. See #4974.
If you are in later insider builds then it's a new issue.

**Comment by shane99a** [comment]
The size I saw was 2 gb. 
I have updated windows recently. My os version is: `Build 19587.re_prerelease.200313-1639`. 

Right now I'm setting up everything all over again. I think there needs to be a backup option for image data somehow. Under no circumstance should it assume that its good to overwrite it, unless it saves the old one somewhere else.
