### ISSUE TITLE
Cant run LXRUN (KB4541335)

### ISSUE THREAD

**Issue by EzioAuditore1337** [microsoft/WSL#5047]
![image](https://user-images.githubusercontent.com/46085531/78560912-06c4f580-7841-11ea-88c7-130fd70948f4.png)

anyone, please help me, i cant install any linux distros :(

i already trying all the tutorial that i got on google, but no one can solve my problem.

**Comment by onomatopellan** [comment]
Lxrun disappeared from Windows 10 long ago. You now need to use wsl.exe.
Run `wsl.exe --help` for more info.
