### ISSUE TITLE
WSL scheduler assigns compute-heavy threads/tasks to LITTLE cores on big.LITTLE arm64 CPUs

### ISSUE THREAD

**Issue by blu** [microsoft/WSL#5049]
* Windows build 19592.1001
* ASUS NovaGo Windows-on-Arm notebook

* Running a native app under WSL (ubuntu/kali/etc) gets assigned to LITTLE cores on big.LITTLE CPUs, even when the app has compute-heavy thread(s), and there are vacant big cores.

 Steps to reproduce under Ubuntu:
 1. Open Ubuntu terminal
 2. Execute
 ```
$ sudo apt-get install stress
$ stress -c 1
 ```
 3. Observe the cpu load in Windows Task Manager.

* Running a compute-heavy WSL task/thread should get scheduled on the available big cores.

**Comment by blu** [comment]
Update: scheduling of compute-intensive tasks to big cores *does* happen when the unit is plugged in the mains. So the behavior descried in the OP is for battery-operated WSL only.

**Comment by sirredbeard** [comment]
I think that might be a feature.

**Comment by blu** [comment]
But that is not the case with native Windows apps -- those get scheduled to bit cores regardless of power-supply conditions.

**Comment by vilmibm** [comment]
👋 I _think_ this is manifesting for me in a worse way than degraded performance.

I'm on a Surface Pro X with WSL2 enabled on Windows build 19042.1052 . When not plugged into mains certain processes run in WSL2 (usually the Go compiler; but it's also affected `apt-get`) will hang forever. They immediately un-hang when I plug in power. It's not reliable (in that not every run of `go` when not plugged in hangs) but is guaranteed to happen multiple times a day (I had been terminating and restarting WSL throughout the day before finding this issue and trying plugging in).

This is a pretty big bummer; is anyone aware of any workarounds or fixes I could try?
