### ISSUE TITLE
No longer able to install new distro or convert existing installation to WSL2

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [microsoft/WSL#5050]
* Windows build number:  10.0.19041.153 (Insider Slow Ring)

* Somewhat I could no longer convert existing Ubuntu to WSL2 or install new distro.
```
❯ wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Error: 0x80041001
❯ debian
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```

* Have tried reinstalling WSL and Virtual Machine Platform. ```sfc /scannow``` and ```dism /online /cleanup-image /restorehealth``` gives 0 error(s) and 0 warning(s).

* Logs attached below.
[Converting Ubuntu to WSL2.zip](https://github.com/microsoft/WSL/files/4441580/Converting.Ubuntu.to.WSL2.zip)
[Launching Debian.zip](https://github.com/microsoft/WSL/files/4441581/Launching.Debian.zip)

**Comment by DHowett-MSFT** [comment]
Have you installed the WSL2 kernel package? There was a change recently that was documented [on the WSL blog](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/).

**Comment by Aster-the-Med-Stu** [comment]
Of course I have tried. But even if there is something wrong with WSL2 kernel at least it shouldn't prevent me from installing a new distro, isn't it? I have checked that the default WSL version is WSL1.

**Comment by Aster-the-Med-Stu** [comment]
It works after installing March Insider(Slow Ring) upgrade... Though still have no idea where is wrong...

**Comment by Jacquers** [comment]
I also got this error, it was because the distro wasn't running. I opened up a terminal which started it, then ran the command again successfully.
