### ISSUE TITLE
How to download 32bit package

### ISSUE THREAD

**Issue by rliu88** [microsoft/WSL#5052]
Hi,

I tried to download 32bit packages (not to install them) using this command in wsl:
$apt-get download <pkg_name>:i386

However wsl always complains that it cannot locate the package although the same package can be downloaded perfectly fine on a "real" ubuntu system.  I compared /etc/apt/sources.list on both systems and they are the same.  Is it possible to get this work on wsl?  I realized that wsl doesn't support running 32bit applications.  I don't need to run it, just need to download the package.

Thanks!

RL

**Comment by therealkenc** [comment]
You probably need `dpkg --add-architecture i386` or related. You'll probably find better specifics in a Debian or Ubuntu forum.

**Comment by rliu88** [comment]
dpkg --add-architecture i386 solved the problem.  Thank you.
