### ISSUE TITLE
Does WSL2 support GUI or graphical programs yet?

### ISSUE THREAD

**Issue by Bigbossbro08** [microsoft/WSL#5053]
Last time like 6-7 months ago when I was using WSL I wasn't able to run GUI apps. I googled about it and heard this support isn't available yet and heard WSL2 will come and add support for it. Now that WSL2 out then GUI is supported or what?

**Comment by matthew-nm** [comment]
Not out of the box, but you can run an X server on Windows and set the $DISPLAY variable in WSL to allow gui apps to display. I set this up yesterday and it works great. Google has plenty of links to articles about how to get this done.

**Comment by craigloewen-msft** [comment]
@matthew-nm is correct, we don't support it out of the box but you can use an x-server to facilitate GUI apps in WSL! Please check out the linked thread for some more info.

/dupe #938

**Comment by kingyue737** [comment]
> @matthew-nm is correct, we don't support it out of the box but you can use an x-server to facilitate GUI apps in WSL! Please check out the linked thread for some more info.
> 
> /dupe #938

I run a compiled app from WSL connecting to X server on Windows and it works just fine. However, is it possible to debug a GUI app in Visual Studio's WSL configuration?
