### ISSUE TITLE
Enable Virtualization within WSL2, ie. Android Emulator

### ISSUE THREAD

**Issue by matthew-nm** [microsoft/WSL#5055]
I enjoy using WSL2 for software development on Win10 and would like to extend this to as many development scenarios as possible.

The current scenario that I am having trouble realizing involves running android emulators via Android Studio within WSL2. I have been able to successfully install Android Studio within WSL2 Ubuntu, and I have an X11 server set up to allow gui apps to function. The only missing piece is the ability to create and run emulated android devices. Attempting to do so via Android Studio's AVD Manager results in the following message, "Your CPU does not support required features (VT-x or SVM)".

My understanding of virtualization is limited, but as I understand it, the virtualization support of my CPU is not accessible within WSL2. Perhaps this is related to https://github.com/microsoft/WSL/issues/4193

My actual use-case is for Flutter development, which I believe is going to become a large area of interest among mobile developers. I would love to see this feature available on WSL2, and I bet I'm not the only one! ;)

**Comment by RobinOpletal** [comment]
Hi, that sounds like the same exact issue as the issue you've mentioned ( #4193 ).

I would suggest to follow that thread going forward for fixes. For now I would suggest either running Android Studio natively or using the fix mentioned in the thread (running your own hyper-v VM)

**Comment by Zaraki596** [comment]
@matthew-nm It would be great if you share some link or tools on how to setup android studio on wsl2? and if windows have android studio installed Do I need to remove it?

**Comment by matthew-nm** [comment]
@Zaraki596 I used the process describe [here](https://itnext.io/flutter-with-wsl-2-69ba8fc7682f) to install Flutter on WSL2. You can just follow the section regarding Android Studio if you do not want all of Flutter.

**Comment by FPardo1023** [comment]
@matthew-nm does it offer hot-reload?
