### ISSUE TITLE
Cannot activate WSL2

### ISSUE THREAD

**Issue by zallarak** [microsoft/WSL#5056]
I connected my outlook account, gave up privacy (said that windows can have full access for debug logs and metrics) and keep getting this. Please help.

![image](https://user-images.githubusercontent.com/806155/78673866-9b5a4280-7897-11ea-9e08-cfdcee802e90.png)

**Comment by craigloewen-msft** [comment]
This problem seems related to getting onboarded onto the Windows Insiders program. I've pinged Jen Gentleman about it on Twitter [here](https://twitter.com/craigaloewen/status/1247625352052006918) to see if she's able to help.

**Comment by alchudry** [comment]
You should make sure you are in/upgrade to the latest version of Windows. Restart. And try again. I ever face this problem before.
