### ISSUE TITLE
All .exe apps hang in WSL2 within Tmux but succeed outside Tmux

### ISSUE THREAD

**Issue by matthew-nm** [microsoft/WSL#5057]
Windows build number:  Version 10.0.19041.172

I am able to run Windows binaries (such as cmd.exe) from WSL2 Ubuntu if I simply open the WSL2 terminal and execute the command from my shell of choice (zsh).

However, if I am inside of a tmux session, the command hangs, returns no output, and I can't kill the command with Ctrl+c. I have to kill the tmux pane and the process ends up stuck in my processes list with the tag [defunct].

Why would being inside tmux prevent a Windows command from executing?

I have included the strace from inside tmux: 
[strace.txt](https://github.com/microsoft/WSL/files/4445349/strace.txt)
and the strace from outside:
[strace_outside.txt](https://github.com/microsoft/WSL/files/4445389/strace_outside.txt)

Thanks for any insight. I am happy to include more information if asked.

**Comment by therealkenc** [comment]
Could not repro here.

![image](https://user-images.githubusercontent.com/7049700/78704726-269bfe00-78c1-11ea-9a3c-27f2dc878b4c.png)

**Comment by matthew-nm** [comment]
I was using the WSLtty terminal but have done the same test via Powershell. It still fails within tmux, but a little more gracefully.

[test_powershell.txt](https://github.com/microsoft/WSL/files/4446571/test_powershell.txt)
[test_powershell_tmux.txt](https://github.com/microsoft/WSL/files/4446572/test_powershell_tmux.txt)

**Comment by matthew-nm** [comment]
Problem solved. Bought a Mac.

**Comment by aont** [comment]
@matthew-nm Hello. I'm not a WSL developer, but the workaround I have developed works good: [aont/tmux-wsl-workaround](https://github.com/aont/tmux-wsl-workaround/)
