### ISSUE TITLE
[Question] Systemd compatible init

### ISSUE THREAD

**Issue by SRGOM** [microsoft/WSL#5060]
Hello- seeing as a lot of services are mostly written with Systemd in mind, are you actually, presently, considering adding a service running capability to your own init system in a systemd compatible way?

**Comment by craigloewen-msft** [comment]
We are investigating adding systemd support to WSL. We don't currently have any updates on this work, but we have been looking into it!

**Comment by SRGOM** [comment]
Please feel free to close, or perhpas leave open if you foresee more such questions. Thank you, I hope WSL2 works out well.
