### ISSUE TITLE
Show folder in File Explorer in the new Linux folder instead of Network folder

### ISSUE THREAD

**Issue by StefanScherer** [microsoft/WSL#5062]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19603.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Open a Ubuntu 18.04 terminal
Go into a folder
Try to open a File Explorer from that folder:
```
$ pwd
/home/stefan
$ wslview .
$ powershell.exe start .
```

* What's wrong / what should be happening instead:

Both `wslview .` and `powershell.exe start .` should take advantage of the new Linux folders in File Explorer and open the folder in the Linux folder tree (yellow arrow).
That would feel much more natural and better integrated.
Instead it opens the folder under the Network icon (red arrow).

![wslview-explorer-network](https://user-images.githubusercontent.com/207759/78833979-1c2b5280-79ee-11ea-8cfd-de86675da095.jpg)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by craigloewen-msft** [comment]
Thank you for the repro! We'll look into adding in this behaviour.
