### ISSUE TITLE
Linux Folder showing my Mac network location when WSL is not using 

### ISSUE THREAD

**Issue by patrick330602** [microsoft/WSL#5064]
**Please fill out the below information:**
* Your Windows build number:  19603

* What you're doing and what's happening:  

Using a Windows 10 Insider virtual machine on Mac via Parallels Desktop with Mac side folders mounted as a network location. Right now, if I don't use any WSL distro, it will show my Mac network location instead of the WSL file location. When any WSL distro is active, it will be back to normal.

![Screenshot 2020-04-09 at 10 54 04 PM](https://user-images.githubusercontent.com/15316889/78909646-6d067e00-7ab6-11ea-9ae6-f033a9bc2015.png)
* What's wrong / what should be happening instead:

It should just display WSL folders.

**Comment by mez-01** [comment]
[](https://www.dropbox.com/sh/lcpluebq83neoh5/AACeNu20V13fxyMnuFpIZcUma?dl=0)

**Comment by licanhua** [comment]
@patrick330602 did you still see this issue?

**Comment by patrick330602** [comment]
Yep, I am still seeing this bug @licanhua

**Comment by licanhua** [comment]
@patrick330602 Thanks to confirm that. But I can't find repro on our side, and I think it's minor impact to user, so I will not fix it.
