### ISSUE TITLE
此安装需要的CAB文件"Ixss_kernel.cab”已受损，不能使用。可能表明网络错误、读CD-ROM错误或此程序包有错。

### ISSUE THREAD

**Issue by B8kingS0ga** [microsoft/WSL#5067]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [版本 10.0.19041.172] 

* What you're doing and what's happening:   
1. 更新版本后 输入 wsl, 提示我
`WSL 2 需要更新其内核组件。有关信息，请访问 https://aka.ms/wsl2kernel`
2. [进入网址](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) 下载
3. 点击打开 并点击下一步后
出现错误"此安装需要的CAB文件"Ixss_kernel.cab”已受损，不能使用。可能表明网络错误、读CD-ROM错误或此程序包有错。"
* What's wrong / what should be happening instead:
"此安装需要的CAB文件"Ixss_kernel.cab”已受损，不能使用。可能表明网络错误、读CD-ROM错误或此程序包有错。"

应该安装成功

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
Could not repro here:

![image](https://user-images.githubusercontent.com/7049700/79025586-1d1dca80-7b3b-11ea-9deb-8793a2729675.png)

**Comment by B8kingS0ga** [comment]
@therealkenc  yes, the error pops up right after the first "next"

**Comment by therealkenc** [comment]
That screencap is **after** the next (see 'cause "finish" button). If there was an error on "next" for a critical mass of users the dupes would be rolling in. [Still early, they might.]
