### ISSUE TITLE
Performance accessing WSL2 instance via localhost is dismal

### ISSUE THREAD

**Issue by pds2208** [microsoft/WSL#5069]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.19041.173

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Doing a large number of network request to a WSL 2 instance using 'localhost' is around > 10 times slower than access the instance via its IP address. For example, a large number of inserts into a database running either directly in WSL or via Docker. See https://www.reddit.com/r/bashonubuntuonwindows/comments/fxe3wu/postgres_in_wsl2_performance/

* What's wrong / what should be happening instead:

There should be no performance difference between localhost and the WSL2 instance IP address

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
/dupe #4946 (with side order of #4901)

**Comment by pds2208** [comment]
Okay. I guess down you can now narrow it down to something to do with using localhost rather than the IP address. Hope it helps and hope it gets fixed soon.

**Comment by eldiablolives** [comment]
@pds2208 you are right, when accessing localhost be it through alias or IP address, it is dead slow, accessing through network is fast, so if you do ifconfig in WSL, find out your IP address then access through that IP address then it's all good. Problem with that 1) I've got to serve apps on 0.0.0.0 2) I have to look it up on DHCP change.
