### ISSUE TITLE
\\wsl$ not accessible from File Explorer

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#5071]
There's now a dedicated "Linux" Root-Folder in File Explorer in Windows 19603. When I click on that, I get the followin gerror message.
![image](https://user-images.githubusercontent.com/9553253/78992962-d8932e80-7b3c-11ea-8a21-dab25dbe1582.png)

The WSL distro is up and running.

![image](https://user-images.githubusercontent.com/9553253/78993075-30319a00-7b3d-11ea-904e-c2df0d344794.png)

Windows 10 Insider 19603

**Comment by sirredbeard** [comment]
Try \\wsl$\Ubuntu

**Comment by sirredbeard** [comment]
Does Ubuntu appear in the Linux drop-down?

Did you install Ubuntu on WSL from the Store and manually upgrade to 19.10 or some other method?

**Comment by ad-on-is** [comment]
I can't expand the dropdown. I imported it from a prebuilt official Ubuntu tarball

**Comment by sirredbeard** [comment]
I installed a clean 19603 and sideloaded a clean Eoan and was unable to reproduce. 

![Annotation 2020-04-10 133617](https://user-images.githubusercontent.com/33820650/79010609-51d85480-7b30-11ea-9c60-ee446ec7c520.png)

I would try removing the WSL and Virtual Machine Platform in Programs and Features, rebooting, reinstalling, rebooting, and then try again.

**Comment by ad-on-is** [comment]
> I would try removing the WSL and Virtual Machine Platform in Programs and Features, rebooting, reinstalling, rebooting, and then try again.

Sorry, but absolutely no option for me, since it's my daily working setup and all my project files reside within WSL.

Strange thing is, I have \\wsl$ mounted as a network drive, which works fine. So there must be something wrong elsewhere.

**Comment by sirredbeard** [comment]
That means the 'file server' is working.

Can you install a stock Ubuntu 18.04 image from the Store and see if you have an issue there?

If you can reproduce with known good Ubuntu image then I think you should try following:

So usually you can reinstall feature and then re-run Ubuntu and everything should still be where it is, you are not removing the distro itself.

But when you manually import an image versus installing with the launcher in the Microsoft Store some of the distro registration on the WSL API is not done for you and it might not automatically re-appear.

In your case I would make a backup of your current working environment first using wsl.exe --export, then do an import as another distro, like ubuntu-backup, to make sure it imports correctly, re-install the features as described above, and then import your known good backup.

I also strongly urge you to automate regular backups of your WSL environment if you are running it on Insiders Fast.

**Comment by ad-on-is** [comment]
> That means the 'file server' is working, that's a good sign.
> 
> Can you install a stock Ubuntu 18.04 image from the Store and see if you have an issue there?
> 
> If you can reproduce with known good Ubuntu image then I think you should try following:
> 
> So usually you can reinstall feature and then re-run Ubuntu and everything should still be where it is, you are not removing the distro itself.
> 
> But when you manually import an image versus installing with the launcher in the Microsoft Store some of the distro registration on the WSL API is not done for you and it might not automatically re-appear.
> 
> In your case I would make a backup of your current working environment first using wsl.exe --export, then do an import as another distro, like ubuntu-backup, to make sure it imports correctly, re-install the features as described above, and then import your known good backup.
> 
> If it is image-specific then we might need to look at the problem in your image.
> 
> I also strongly urge you to automate regular backups of your WSL environment if you are running it on Insiders Fast.

Unfortunatelly, nothing helped.

So, I installed Ubuntu 18.04 from the store, opened File Explorer, clicked on the Linux icon, and the same error appears. 

I went ahead, exported/imported my WSL distro, still error. Then I disabled Virtual Machine Platform and WSL, rebooted, enabled it back again, rebooted. I opend File Explorer, and again the same error.

Is there anything else I could try? Also, what's the benefit of the new WSL integration in File Explorer compared to mounting \\wsl$ as a network drive?

Regarding backups, my WSL resides on a different partition, and I'm doing daily backups with Easeus Backup, so I think I've sufficiently backed everything up, at least, that's what all of us think about their backup-setups :-D.

**Comment by sirredbeard** [comment]
> Is there anything else I could try?

I will give it some thought.

> my WSL resides on a different partition

If I had to bet that is probably it.

**Comment by ad-on-is** [comment]
> > Is there anything else I could try?
> 
> I will give it some thought.
> 
> > my WSL resides on a different partition
> 
> If I had to bet that is probably it.

But I had Ubuntu 18.04 from the store which was not on a different partition. Or is it maybe the fact that some distros are not in the default WSL location. If that is really the case, than it's an issue.

**Comment by ad-on-is** [comment]
Ok, so I found the problem. First I have manually to access `\\wsl$` from the address bar to be able to open it in File Explorer.

1. Restart PC
2. File Explorer, click on Linux icon, the error appears.
3. Type manually `\\wsl$` in the address bar, Distros show up, as expected
4. Click on Linux icon again, distros show up

**Comment by norti** [comment]
Apparently the 'Linux' quick shortcut in File Explorer is not functioning. Any chance to fix this? I have the exact same problem.

**Comment by PavelSosin-320** [comment]
The same with all distros: they are not accessible under Linux subfolder in FileExplorer but accessible via \\wsl$ in my Windows 10 2004 build 161. 
In Windows 10 2004 Home OEM edition Linux subfolder doesn't exist in  File Explorer at all.
But 
# Enable extra metadata options by default
[automount]
enabled = true
root = /windir/
is ignored in both cases , in all distros - there is no /windir/. Everything is mounted at /mnt/host

**Comment by kieranomahoney** [comment]
Bit late to the party - had the same issue but was able to mount by mapping network drive and use folder \\wsl$\Ubuntu

**Comment by gmankab** [comment]
same problem

**Comment by gbiagini** [comment]
Exact same issue. I've tried all recommended steps. Persistent since I set up my current device in August.

Does not happen with other devices I use, such as a Windows 11 on ARM laptop.

**Comment by gbiagini** [comment]
(Hopefully) relevant update:

Running `dmesg |grep 9p` on my Windows 11 machine (with has the issue) results in the following: 
![image](https://user-images.githubusercontent.com/48301124/146435233-8e65efc3-a685-4d9d-8f45-87c702f1f613.png)

While, on my Windows 11 on ARM machine (with no such issue)
![image](https://user-images.githubusercontent.com/48301124/146435837-abd74bb9-c46e-406c-88bb-36c081d0b1a3.png)

No issue with registry keys as suggested in (https://github.com/microsoft/WSL/issues/4027#issuecomment-496628274): P9NP is present, and in the front of the list in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order and HwOrder.

Other similar issues suggest a 9P Filesystem error for similar issues accessing the Linux filesystem. Is this potentially another such case?

**Comment by gmankab** [comment]
still actual
