### ISSUE TITLE
Is there a way to start the WSL in another terminal i.e. the Windows terminal so there can be multiple tabs?

### ISSUE THREAD

**Issue by xtianus79** [microsoft/WSL#5077]
That's it just wanted to know if this was possible and if so is there a place for documentation?

**Comment by beltaurus** [comment]
I am not sure if this is what you're after, but doesn't the "[screen](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/)" application do this (You will have to install it `sudo aptinstall screen`)?

1. In the CMD shell, start your WSL shell (`wsl `or [ubuntu1804 ](url)or ...).
2. In your WSL shell, start the screen application (`screen`).
3. If you want multiple tabs, just create them when needed...

There are instructions on how to [visualize the tabs of screen](http://bigdatums.net/2017/03/25/how-to-display-window-tabs-in-linux-screen/), but I haven't tried those myself:

For the functionality you're after, I start an X server on my windows platform.
Then I launch 'konsole', it is a terminal that has built-in tabs...
![image](https://user-images.githubusercontent.com/54114043/79082796-2c894900-7cde-11ea-8b86-cd2a74797c9e.png)

And of course, there are plenty of Windows applications that offer a tabbed view of different CMD windows, and you can invoke `wsl` in each of them at your hearts' content?

**Comment by xtianus79** [comment]
@beltaurus i'm sorry how do you access the screen application?

**Comment by craigloewen-msft** [comment]
@xtianus79  the Windows Terminal supports WSL out of the box! If you go install it you'll see all of your WSL distros should be enumerated automatically for you.

**Comment by beltaurus** [comment]
> @beltaurus i'm sorry how do you access the screen application?

1. It probably needs to be installed first
```
screen --version
# If this gives an error message, then install it:
sudo apt install screen
```
2.  Before using it for the first time, you need to have an administration directory:
```
mkdir -m 700 ~/.screen 
# You can make this directory anywhere you want, this location is just a suggestion
```
3. Then you invoke it by just typing the command
```
screen
```
4. Use the [Ctrl]+[a],[key] to execute a screen administration command:
You can look at the man page for a complete list, but the interesting [key] commands are:
```
'a': Create a new window (tab)
'"': List all windows (tabs), allow to select
'n': Go to the Next window (tab)
'p': Go to the Previous window (tab)  
[Ctrl]+[\]:  Exit screen session
```

The main feature that 'screen' users are after is the fact that you can detach from your working session (all is cached in the administration directory), and reattach later on.
There are many more features such as window naming, splitting,...

Another tool that has similar properties, but also visualizes the tabs without any magic is tmux... People find it a bit more intuitive than screen, here is a quick snapshot:
![image](https://user-images.githubusercontent.com/54114043/79162935-f2c64a00-7d92-11ea-9977-c87119b5f102.png)


But if you're going for intuitive, I personally just go through the trouble of starting an X Server, and launching Konsole.

**Comment by beltaurus** [comment]
> @xtianus79 the Windows Terminal supports WSL out of the box! If you go install it you'll see all of your WSL distros should be enumerated automatically for you.

Maybe I'm misunderstanding the question: If you just want to have a bunch of WSL terminals, all in their own window, then all you need to do is double-click the shortcut for each window you want...
 Or you can just launch a bunch of CMD terminals, and launc `wsl` in each and every one of those.

If your question is to how to create multiple terminals WITHIN one window, then my answer (screen, tmux,...) would apply. But if it comes down to having multiple windows, I still prefer launching konsole, or even a desktop...

**Comment by DHowett-MSFT** [comment]
Or just click the `v` part of the `+ v` menu in Windows Terminal and choose your favorite 40 distributions. Each one opens in its own tab.

**Comment by beltaurus** [comment]
> in Windows Terminal

Ah, it looks like you decoded the question more accurately than I did...
I hadn't used Windows Terminal, so I didn't recognize it as the object of the quesiton... Sorry for all the confusion.

**Comment by mchubby** [comment]
You can use cmder, follow the instructions at:

https://gist.github.com/nickautomatic/02ccb76292f7f8d9767e

The command for the task would be
`%windir%\sysnative\wsl.exe` for the default distribution
`%windir%\sysnative\wsl.exe -d Legacy` for the one installed by lxrun.exe

Run wsl -l for the list of available shells.

**Comment by xtianus79** [comment]
@craigloewen-msft thank you. and all of this information is correct. perfect!
