### ISSUE TITLE
WSL2 NodeJS local HTTP server  (+Webpack) is very slow

### ISSUE THREAD

**Issue by Newbie012** [microsoft/WSL#5078]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.19603.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1. wsl --unregister Ubuntu
2. wsl --set-default-version 2
3. Reinstall Ubuntu
4. Make sure it's version 2 by running `wsl -l -v`:
```
  NAME      STATE           VERSION
* Ubuntu    Running         2
```
5. run `npx create-next-app wsl-app`
6. run `npm run dev` (should create an instance of webpack)

* What's wrong / what should be happening instead:

It takes a long time to serve the app to localhost, and after it detects a change, it takes up to a minute to refresh. Usually, it's slow whenever you run `createServer`. On WSL1 it worked as expected.

**Comment by Newbie012** [comment]
@therealkenc How would you want it to be reproduced? I've written the steps I did in order to show the bug. I'm not sure if it will happen to everyone tho. If you need any logs, let me know

**Comment by therealkenc** [comment]
This one was marked need-repro because it doesn't make it over the cli step bar. I assume `npm i -g npx` or something like that followed by whatever a "run `createServer`" means. 

> How would you want it to be reproduced?

Bisecting from clean Windows install probably. Likely destined for #4901, but here didn't make it that far. Noting that #2477 has gone since 2017 without a repro.

**Comment by oldium** [comment]
May be the same as https://github.com/microsoft/WSL/issues/5079? Where are you executing the commands, what is you current folder? Is it on the Windows filesystem or within your WSL2 distro?

**Comment by Newbie012** [comment]
@therealkenc `npx` is a built in command of NodeJS. It just executes mpm packages binaries. I know it's very specific to NodeJS and may sound unfamiliar for you if you haven't used NodeJS at all, but I can't afford to install a clean windows just to reproduce it. If you look over Reddit, you'll see that I'm not the only one who's experiencing NodeJS server issues.

@oldium thanks for the reply. It's not the same, since composer is from PHP's ecosystem. Plus, I didn't have issues downloading packages. The issue I'm experiencing is that it takes a long time for NodeJS to create a server, and it takes much longer time to detect changes in order to restart reload the files (Webpack related).

If you want me to create a git repository for you with the NextJS files, I can do so.

**Comment by oldium** [comment]
@Newbie012 Where are you executing the commands, what is you current folder? Is it on the Windows filesystem or within your WSL2 distro?

**Comment by Newbie012** [comment]
@oldium via Windows Terminal (Ubuntu).

In `eliya@DESKTOP-LDD0TT1:/mnt/c/Users/Eliya/projects/example-nextjs$`

As you can see, withing my  WSL2 distro.

**Comment by oldium** [comment]
@Newbie012 /mnt/c is your Windows drive, so WSL2 accesses files from Windows via a proxy, not directly. Copy all project files from /mnt/c/.../example-nextjs to /home/eliya, so that it is stored in WSL2 virtual machine.

**Comment by Newbie012** [comment]
You're a magician, @oldium!

Why wouldn't \\wsl$/home be the default destination folder in the first place?

**Comment by therealkenc** [comment]
> /mnt/c/Users/Eliya

/dupe #4197

**Comment by AnimeshRy** [comment]
> You're a magician, @oldium!
> 
> Why wouldn't \wsl$/home be the default destination folder in the first place?

You can change the defaults in the terminal's settings.json file.
