### ISSUE TITLE
wsl can't  launch docker 

### ISSUE THREAD

**Issue by wenchaomartin** [microsoft/WSL#5081]
hi : I am newer the wsl  and install docker in the wsl  occur some problem
* os ver : microsoft win10.0.18362.720

* i install ubuntu bash (Linux DESKTOP-T90CO9O 4.4.0-18362-Microsoft [#]476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux)
i follow this guide [docker doc]( https://docs.docker.com/engine/install/ubuntu/) to intall docker in ubuntu 
docker service not running 

* problem:

sudo dockerd 

warining:

* Your kernel does not support cgroup memory limit
* Unable to find cpu cgroup in mounts
* Unable to find blkio cgroup in mounts
* Unable to find blkio cgroup in mounts
* Running iptables --wait -t nat -L -n failed with message: `iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)

error:
*  Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by therealkenc** [comment]
#767. De-facto hangout for Docker on WSL1 is #2291.
