### ISSUE TITLE
I/O error when launching WSL 

### ISSUE THREAD

**Issue by void32** [microsoft/WSL#5085]
Microsoft Windows [Version 10.0.19541.1000]

Launching Ubuntu on windows
![image](https://user-images.githubusercontent.com/6043260/79231659-b2d09700-7e66-11ea-9127-2e8663872272.png)

The terminal window hangs several minutes and reports the error:
```
The I/O operation has been aborted because of either a thread exit or an application request.
Press any key to continue...
```

Workaround: close the window wait several minutes and try again. The problem occasionally:
![image](https://user-images.githubusercontent.com/6043260/79232162-73567a80-7e67-11ea-9635-d993c73eaf41.png)

**Comment by mstva** [comment]
same issue here, did you find a fix? @void32

**Comment by simis2626** [comment]
@void32 
have a look at this thread, solved my issue with the workaround there.

TL;DR; looks like often a too long PATH env var is causing the issue (there's a fix inbound)
https://github.com/microsoft/WSL/issues/5633

**Comment by void32** [comment]
Yep `cmd /c "set path=C:\WINDOWS\System32;C:\WINDOWS; && wsl"` worked for me.

![image](https://user-images.githubusercontent.com/6043260/89869740-1371a580-dbb5-11ea-9086-dba6aff090b8.png)
