### ISSUE TITLE
BOINC causes network to stop working (WSL1)

### ISSUE THREAD

**Issue by mobluse** [microsoft/WSL#5086]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.720]

I use Ubuntu in WSL (WSL1) from Microsoft Store, and Ubuntu is most updated and the Store apps are also most updated.

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

```
sudo apt install boinc-client boinctui
sudo service boinc-client start
boinctui
```
I then configure it to use Rosetta@home and Einstein@home.

After a while (typically within an hour) the networks stops working -- i.e. web pages can't be reloaded in Chrome or other browsers and also the work units in BOINC can't be uploaded. In the web page there is a link to start Windows network diagnostics, but that finds no error. `ping github.com` still works. I use WiFi. Changing to another router doesn't help. The only thing AFAIK that fixes the error is to reboot. BOINC works without network problems using Ubuntu 18.04 LTS natively on an x86 (32-bit) computer.

* What's wrong / what should be happening instead:

The network stops working -- at least higher levels. (I have not tested with cable network.)
The network should continue to work. E.g. the similar program Folding@home doesn't crash the network, but that is a native Windows program. `ping github.com` still works, but https://github.com/ doesn't work when this error has started.

**Comment by therealkenc** [comment]
Smells like #3951 #2913.
