### ISSUE TITLE
WSL2 "network path was not found" 

### ISSUE THREAD

**Issue by nerumo** [microsoft/WSL#5088]
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.173]

* What you're doing and what's happening:  Using visual studio code's bash terminal for WSL, I cd /tmp/ and attempt to explorer.exe . as per documentation here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#place-your-linux-files-in-your-linux-root-file-system

* What's wrong / what should be happening instead: Explorer opens in my Windows Document directory. If I try to access the linux distro by UNC path \\wsl$\Ubuntu-18.04\ I get:
```
System error 53 has occurred.

The network path was not found.
```
I reinstalled "Windows Subsystem for Linux" feature, I installed a new distro (all in wsl v2), but nothing helped. I have to mention that I have several VPN solutions (forti, cisco, openvpn) installed which might cause a side effect. Is there a specific windows file share service (netbios or whatever) that I have to turn on?

**Comment by lilred** [comment]
Should be `\\wsl$\Ubuntu\`
