### ISSUE TITLE
WSL stopped launching

### ISSUE THREAD

**Issue by Geo1088** [microsoft/WSL#5089]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`10.0.19041.173`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Accessing a WSL terminal just doesn't work. I'm trying to use it by using the `wsl` command via PowerShell and CMD; neither work. The error returned is "The process cannot access the file because it is being used by another process." Here's an elevated PowerShell session showing me collecting logs while trying to open WSL:

<details>
<summary>PowerShell Session</summary>

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> cd C:\Users\George\TempLogStuff\
PS C:\Users\George\TempLogStuff> logman.exe create trace lxcore_kernel -p "{0CD1C309-0878-4515-83DB-749843B3F5C9}" -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets
The command completed successfully.
PS C:\Users\George\TempLogStuff> logman.exe create trace lxcore_user -p "{D90B9468-67F0-5B3B-42CC-82AC81FFD960}" -ft 1:00 -rt -o .\lxcore_user.etl -ets
The command completed successfully.
PS C:\Users\George\TempLogStuff> logman.exe create trace lxcore_service -p "{B99CDB5A-039C-5046-E672-1A0DE0A40211}" -ft 1:00 -rt -o .\lxcore_service.etl -ets
The command completed successfully.
PS C:\Users\George\TempLogStuff> wsl
The process cannot access the file because it is being used by another process.
PS C:\Users\George\TempLogStuff> logman.exe stop lxcore_kernel -ets
The command completed successfully.
PS C:\Users\George\TempLogStuff> logman.exe stop lxcore_user -ets
The command completed successfully.
PS C:\Users\George\TempLogStuff> logman.exe stop lxcore_service -ets
The command completed successfully.
```

</details>

And here's the actual log files: [`lxcode_kernel.etl`](https://files.catbox.moe/rvt7jz.etl), [`lxcore_service.etl`](https://files.catbox.moe/ionvsf.etl), [`lxcore_user.etl`](https://files.catbox.moe/esfduu.etl).

* What's wrong / what should be happening instead:

WSL should show me my Linux prompt and let me do things.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

Here they are again: [`lxcode_kernel.etl`](https://files.catbox.moe/rvt7jz.etl), [`lxcore_service.etl`](https://files.catbox.moe/ionvsf.etl), [`lxcore_user.etl`](https://files.catbox.moe/esfduu.etl).

**Comment by Neeldip** [comment]
Having the same issue. WSL does not launch anymore.
Using `10.0.19041.173. `

Launching with cmd and powershell gives:

> Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
> For information please visit https://aka.ms/wsl2-install

Cant understand what broke it.

**Comment by Geo1088** [comment]
I'd prefer to avoid resetting if possible; I have unpublished changes to a Git repo in this distro that I'm not looking forward to recreating if they're lost.

**Comment by Geo1088** [comment]
Wow, I feel dumb. I'd accidentally mounted the WSL virtual disk image by double-clicking it in explorer, and it remained mounted to my machine even though it reported an error that made having it mounted useless. Unmounting the vdisk from Disk Management resolved the issue for me.

@Neeldip it seems unlikely your situation was caused by the same thing; I'd recommend you make a new issue and include your own logs.
