### ISSUE TITLE
Command "ip neighbor show" not behaving properly

### ISSUE THREAD

**Issue by TheMagicNacho** [microsoft/WSL#5091]
**Widows Version**  
Microsoft Windows [Version 10.0.17134.1365]
**Linux Kernel**
OpenSUES Leap 15.1
**Steps to reproduce**
In terminal: `$ip n show`
Output
`Cannot send dump request:  Operation not supported`
note: `$sudo ip n show` yields the same response.
**Expected Outcome**
That command should output similar information as "arp -a" in windows. 
**Strace Output**
[https://gist.github.com/TheMagicNacho/52ed53f1fa2b6a369b8a17da41269a4d](https://gist.github.com/TheMagicNacho/52ed53f1fa2b6a369b8a17da41269a4d)

**Comment by therealkenc** [comment]
```
[...]
74    socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 3
74    setsockopt(3, SOL_SOCKET, SO_SNDBUF, [32768], 4) = 0
74    setsockopt(3, SOL_SOCKET, SO_RCVBUF, [1048576], 4) = 0
74    setsockopt(3, SOL_NETLINK, NETLINK_EXT_ACK, [1], 4) = -1 EINVAL (Invalid argument)
[...]
74    sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=28, type=0x1e /* NLMSG_??? */, flags=NLM_F_REQUEST|0x300, seq=1586977711, pid=0}, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}, iov_len=28}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = -1 EOPNOTSUPP (Operation not supported)
```

Technically satisfies "pick up the torch" from #3656. Spiritually dupe #69.
