### ISSUE TITLE
WSL2 ERROR: The virtual machine or container with the specified identifier is not running.

### ISSUE THREAD

**Issue by jiangslee** [microsoft/WSL#5095]
**Please fill out the below information:**
* Your Windows build number:  

**Microsoft Windows [Version 10.0.19041.173]**

* What you're doing and what's happening:  
![image](https://user-images.githubusercontent.com/27892476/79414944-95263d80-7fde-11ea-8737-d6f6d308c2b2.png)
----------------

> PS C:\WINDOWS\system32> wsl -l -v
>   NAME            STATE           VERSION
> \* Ubuntu-18.04    Stopped         2
> PS C:\WINDOWS\system32> ubuntu1804.exe
> The virtual machine or container with the specified identifier is not running.
> Press any key to continue...

----------------
* What's wrong / what should be happening instead:
![image](https://user-images.githubusercontent.com/27892476/79415548-41b4ef00-7fe0-11ea-8357-dd51e5b9426b.png)

![image](https://user-images.githubusercontent.com/27892476/79415607-627d4480-7fe0-11ea-89e9-a7f969506784.png)

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by jiangslee** [comment]
![image](https://user-images.githubusercontent.com/27892476/80075140-cec9ec00-857c-11ea-8b1c-e2cf8d909647.png)
upgrade "Microsoft Windows [Version 10.0.19041.207]" to fiexd this issue!

**Comment by likylim** [comment]
I have exact same issue on my machine. I'm not sure but I also use XEON E3-1231v3.
And I use 10.0.19041.208
Is there any issue on Xeon processor? or should I do some set on bios setup to use wsl?

**Comment by jiangslee** [comment]
![image](https://user-images.githubusercontent.com/27892476/80442742-31860380-8940-11ea-9f95-7ecc58fffe75.png)

After upgrading my windows to 10.0.19041.208, wsl2 cannot start again

**Comment by likylim** [comment]
Hello, is there any progress on this?
I made another machine (i7-4770) as same as e3-1231v3 machine, and it works. 
so i think it's related with xeon processor.

**Comment by whpac** [comment]
I have the same issue on my i3-4005U, windows version [Version 10.0.19041.264]. Yesterday it worked well, but today it doesn't work

**Comment by ridays2001** [comment]
Hello. I had the same issue. In my case, it happened when I enabled the virtualization. It seems that the system needs some time to start the virtual container for the first time. After waiting for 10 -15 mins, the virtual container started automatically and my WSL was installed successfully. [Ubuntu 20.04 in my case].

**Comment by buka4rill** [comment]
I solved this by uninstalling ubuntu and reinstalling it

**Comment by redwine-1** [comment]
Hello, starting virtual machine or container from start menu solved my problem. First start your vm from start menu then you use cmd or powershell to access your vm. If you are using windows terminal you can click on your vm from  powershell's drop down menu.

**Comment by kitavidavis** [comment]
I had the same issue just after updating the linux kernel. I did wait for like 3 minutes and the problem was gone.

**Comment by Shire-hmd** [comment]
I had the same issue and just restarted vm after waiting a couple minutes and it worked.

**Comment by nextstep10** [comment]
I just had the same issue in wsl. can you help me? what will I do?

**Comment by maxthestranger** [comment]
> I just had the same issue in wsl. can you help me? what will I do?

You need to enable virtualization in your bios and then wait for a few minutes
