### ISSUE TITLE
[WSL2] Error during migration: The interface is unknown

### ISSUE THREAD

**Issue by raffaeler** [microsoft/WSL#5096]
OS: Windows 10 fast ring (in a VM) 10.0.19592.1001 (version 2004)
Nested virtualization enabled.

Sequence of commands. The last one finished immediately and failed with `The interface is unknown`:
```
C:\Users\raf>wsl --set-default Ubuntu-18.04 2

C:\Users\raf>wsl --set-default-version 2

C:\Users\raf>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The interface is unknown.
```` 
Event viewer: there is one entry for this error:
```
Fault bucket 1157523123894259464, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: vmwp.exe
P2: 10.0.19592.1001
P3: 6b61f99b
P4: KERNELBASE.dll
P5: 10.0.19592.1001
P6: 60fcd3a8
P7: c0000194
P8: 000000000010cd7c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A7B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1C7F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CA0.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20200407 1 Event Collector_0_inject.etl
\\?\C:\Windows\Temp\WER1F7F.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\Windows\Temp\WER1F9F.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1F9B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1FBC.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_vmwp.exe_831ddeb2b5a269cc54ec21cf4d7a7cd656693_8a785f3d_d968ee25-38bd-4645-9f07-bdf11ce1d361

Analysis symbol (wer file attached): 
Rechecking for solution: 0
Report Id: efd45841-8c5d-46cb-8b7f-f6ebb1223f85
Report Status: 268435456
Hashed bucket: 7007e53d236ba2cbd0105925fb048f08
Cab Guid: 0
```
[Report.zip](https://github.com/microsoft/WSL/files/4486788/Report.zip)

I have no way to repro this issue as repeating the migration succeeded.

*As as side note, I noticed Windows Defender consuming high levels of CPU during the conversion that succeeded. This should not occur given the conversion is driven by a system component.*

**Comment by lohriialo** [comment]
Ran into this error myself, I had a perfectly running wsl 2 Ubuntu-18.0.4 for few weeks now and then all of a sudden this morning the error is `"The interface is unknown"`
Ran command `"wsl --set-default Ubuntu-18.04 2"` and it's working again

**Comment by bpulliam** [comment]
Without a repro or logs, I don't see any further action we can take here.

**Comment by raffaeler** [comment]
Oh well, after one year, I don't even remember the build I was testing :-D
