### ISSUE TITLE
Unable to create symbolic links on mounted network drive

### ISSUE THREAD

**Issue by mikkelee** [microsoft/WSL#5097]
* Your Windows build number: Microsoft Windows [Version 10.0.18363.720]

* Running Debian 10 (buster)

* What you're doing and what's happening:

```console
mikkelee@HOST:/mnt/drive$ virtualenv virt
PermissionError: [Errno 1] Operation not permitted: '/usr/bin/python3' -> '/mnt/drive/virt/bin/python'
mikkelee@HOST:/mnt/drive$ touch test
mikkelee@HOST:/mnt/drive$ ln -s test test2
ln: failed to create symbolic link 'test2': Operation not permitted
```

Drive is currently mounted like so:

```console
mikkelee@HOST:/mnt/drive$ cat /etc/fstab
X:      /mnt/drive  drvfs   defaults        0       0
mikkelee@HOST:/mnt/drive$ mount -l
[snip]
X: on /mnt/drive type drvfs (rw,relatime,case=off)
```

The X drive is a ReFS network drive. I have also tried using `\\server\drive` in `fstab` to no avail.

* What's wrong / what should be happening instead:

I should be able to create symlinks & virtual envs.

**Comment by mikkelee** [comment]
No suggestions? I have googled a lot but found no solution or explanation for why it doesn't work for me.

**Comment by ReneKat** [comment]
Hi, I"m having a similar issue and this page may help you:
https://askubuntu.com/questions/1115564/wsl-ubuntu-distro-how-to-solve-operation-not-permitted-on-cloning-repository
Look at the second answer from Wojtek Grojec

**Comment by mikkelee** [comment]
Thanks, I will try this when I get back to the office in a few weeks.

**Comment by mikkelee** [comment]
I have now tried this, unfortunately it didn't work... Same errors.

**Comment by scruel** [comment]
Any update?
