### ISSUE TITLE
Still can't get WSL2 to work.

### ISSUE THREAD

**Issue by pnunn** [microsoft/WSL#5101]
* Your Windows build number:  10.0.19041.207

* What you're doing and what's happening:  Trying to start debian as a wsl2 instance

* What's wrong / what should be happening instead: This time atleast I get a half useful error messsage, it tells me I need to update the kernel (which I've done already in the past mind you) to make it work.

I followed (again) the instructions to install wsl2, however, when it comes time to install the kernel msi I get this...
![image](https://user-images.githubusercontent.com/1034315/79671473-c59fee80-820d-11ea-88b4-5bbc3b27b293.png)

WSL1 still works thank goodness... How is wsl2  even remotely ready for prime time?

**Comment by pnunn** [comment]
OK, found the messages other people have been reporting... uninstalled and re-installed the kernel.. so atleast we get one step further now.. but sadly, nothing has improved past that.

I'm still getting

![image](https://user-images.githubusercontent.com/1034315/79671660-78248100-820f-11ea-9d26-54fa392d5c8d.png)

I should mention this is post the latest updates being installed yesterday.

**Comment by onomatopellan** [comment]
Something is interfering the console output. Read this http://www.os2museum.com/wp/anomaly-meaningless-rex-prefix-used/

BTW what's that thing in your titlebars?

**Comment by pnunn** [comment]
Hi @onomatopellan, thanks for the input, but its seems the Regex may not be more than a message issue.. the bigger issue is that wsl2 just crashes (still).

I'm not sure what 'thing'your refering too, but if its the left hand symbol on the right that comes from DisplayFusion.

**Comment by onomatopellan** [comment]
If you call ``wsl.exe -d debian` from cmd does it show the same?

"The attempted operation is not supported for the type of object referenced." could be same as #4177

**Comment by pnunn** [comment]
Yep.. same error. I'll have a look at 4177.
]

**Comment by pnunn** [comment]
OK, still issues... any sort of network tools (ping, traceroute etc) give socket: Operation not permitted

**Comment by onomatopellan** [comment]
That's another issue. You should search for that error or create a new issue thread with the steps you did to get there.
