### ISSUE TITLE
Installation of any linux iso's

### ISSUE THREAD

**Issue by perincolony1** [microsoft/WSL#5105]
**Is your feature request related to a problem? Please describe.**
I don't see anywhere how to install a Linux version that's not in the windows app list

**Describe the solution you'd like**
I like an option for selecting the windows app download or an iso you have downloaded

**Describe alternatives you've considered**
Example deepen-20

**Additional context**
Also include example of how to setup an x-server for your Linux distros

**Comment by beltaurus** [comment]
As an X-server, I really prefer [VcXsrv](https://sourceforge.net/projects/vcxsrv/): they took the original Xorg source code, and got it to compile with Microsoft Visual Studio, so the X support is rather authentic.

It is extremely flexible on how it supports  X windows within your Desktop Window Manager (rootless, within a window, multiwindow,...).

I prefer to have my WSL/Linux applications pop up in their own window, amidst my Windows applications. You can use the VcXsrv XLaunch application to start the X server, but I just launch it from within a script in WSL (remember you can launch any Windows application from within WSL);
the command line options are documented in the [VcXsrv help](https://gist.github.com/ctaggart/68ead4d0d942b240061086f4ba587f5f):
```
/mnt/c/Program\ Files/VcXsrv/vcxsrv.exe\
  :0\
  -multiwindow
```

I have only been working on WSL (not WSL 2), so I don't use Unix sockets, but TCP/IP connections.

That means that I need to export my DISPLAY as follows:
```export DISPLAY=localhost:0
```

And after launching the server, and setting the DISPLAY environment variable, you are in business:

```
xeyes
````
![image](https://user-images.githubusercontent.com/54114043/79674551-090c4580-8199-11ea-8607-dec677bc6570.png)


I also have a more advanced script, that starts the XFCE4 desktop on my second monitor (but this requires a bit of familiarity with X):

```
exec xinit /etc/xdg/xfce4/xinitrc -- \
/mnt/c/Program\ Files/VcXsrv/vcxsrv.exe\
  :$0\
  -nodecoration\
  -screen 0 @2\
  -reset\
  -unixkill
```
![image](https://user-images.githubusercontent.com/54114043/79676446-322dd580-819b-11ea-8589-30812cfb5211.png)

**Comment by perincolony1** [comment]
I try it

If you can help mr get deepin 20 installed also i be golden

Pb

**Comment by beltaurus** [comment]
> If you can help mr get deepin 20 installed also i be golden

I'm sorry, I know that some of people have been experimenting with this, but I have always stuck to distro's distributed by Microsoft...
