### ISSUE TITLE
How to auto start service

### ISSUE THREAD

**Issue by rornor** [Microsoft/WSL#511]
Hi,

it seems that Ubuntu used upstart and now uses systemd for service management.

I installed mpd and want this service to auto-start. Installation seem to created valid auto start service script as `/lib/systemd/system/mpd.service` but service does not start unless I manually start with `sudo service mpd start`.

So I wanted to ask how to auto start service generally in WSL?

**Comment by sunilmut** [comment]
Background tasks are currently not supported on WSL. One way to accomplish this right now would be to use the "bash.exe -c <cmd>" to start whatever you want. If you want that to auto start post Windows boot, you can hook that command to the Windows startup.

**Comment by benhillis** [comment]
Thanks @sunilmut.  I'd also like to add that any daemons that you run will be terminated when the last bash.exe goes away so you'll have to leave one bash.exe running.

**Comment by ymeiner** [comment]
Correct me if i'm wrong just running -c with a command will not be enough, you need to exec bash at the end to get the window to stay open.

You can either do this:
`bash.exe -c 'bash /path/to/file.sh;  bash'`
Or add $SHELL at the end of the script.

**Comment by ZuSe** [comment]
Is there any more elegant way in the meantime that is more similar to systemd/upstart?

**Comment by skywind3000** [comment]
It is 2017 now, the background service is the last thing stopping me to swith from cygwin to wsl.

Has it been planned in the feature release ?

Any roadmaps ??

**Comment by dioptre** [comment]
This question is not answered here. Any progress on this?

**Comment by sunilmut** [comment]
@dioptre - Background tasks, daemons are now supported starting Insider build 17046. See the [blog](https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl) for more details. But, auto start of services is still not available. More detailed discussion on that at #834, #612

**Comment by DarthSpock** [comment]
@SvenGroot Since this is a separate but related ask to [2636](https://github.com/Microsoft/WSL/issues/2636) and you indicated support there, will there be support for this as well or what's the progress for this one?

**Comment by troytse** [comment]
Hi guys, I made a script to support starting the WSL services on Windows start.
[WSL-Autostart](https://github.com/troytse/wsl-autostart)

**Comment by mathieucaroff** [comment]
@benhillis's remark is no longer true.
I can successfully exit wsl while I run shellinabox in a tmux server in wsl, without my shellinabox session being interrupted.

**Comment by benhillis** [comment]
Yeah that was 2+ years ago. We have added support for background tasks in the meantime.

**Comment by mnpenner** [comment]
@benhillis We can start the cron service manually, and it will run as long as the terminal is open, but when we reboot Windows it doesn't start automatically, nor after opening a Bash window.

**Comment by Justsoos** [comment]
Now my solution is adding such like command to **~/.bashrc**, 
**service start tor**
Works well.

**Comment by mathieucaroff** [comment]
@ymeiner
> Correct me if i'm wrong just running -c with a command will not be enough, you need to exec bash at the end to get the window to stay open.
> 
> You can either do this:
> `bash.exe -c 'bash /path/to/file.sh; bash'`
> or add $SHELL at the end of the script.

Here's a minor improvement: in `bash.exe -c 'bash /path/to/file.sh; bash'`, the last `bash` will start bash as a child of the current bash process. Using `exec` will replace the current process:
```bash
bash.exe -c 'bash /path/to/file.sh; exec bash -i'
```

The final `-i` may be ommited in most situations.
Use `pstree` to show the current process with its ancestories.

**Comment by lenowng** [comment]
> Now my solution is adding such like command to **~/.bashrc**,
> `service start tor`
> Works well.

In this case, for every instance you have extra line of command that potentially cause a delay (might not quite noticeable but definitely not elegant) for example when opening a new tab.

**Comment by javierguzman** [comment]
Any better way to do this in 2021? Thank you in advance and regards
