### ISSUE TITLE
gcc error?

### ISSUE THREAD

**Issue by haha010508** [microsoft/WSL#5111]
ar -cr kaldi-base.a kaldi-math.o kaldi-error.o io-funcs.o kaldi-utils.o timer.o
ar: unable to rename 'kaldi-base.a'; reason: Permission denied

i make c/c++ code with ubuntu18.04 and win10, but i got this error, who know how to handle this? and make the openblas have the same problem.

**Comment by rmsilva1973** [comment]
@therealkenc I guess he was trying to build Kaldi (https://github.com/kaldi-asr/kaldi). Well, I did the following steps on my ubuntu on WSL in an attempt to reproduce:

**git clone https://github.com/kaldi-asr/kaldi
cd kaldi/tools
make
./extras/install_mkl.sh
cd ../src
make depend -j 4
make -j 4**

and it built without any problem. The archive file _kaldi-base.a_ included:

![image](https://user-images.githubusercontent.com/28487379/80356543-f86e6600-884f-11ea-8688-1c8c5fc2e23d.png)

So, unless @haha010508 provides any further info to reproduce, I suggest closing the issue.
