### ISSUE TITLE
Network interface selection

### ISSUE THREAD

**Issue by PoleG97** [microsoft/WSL#5119]
Hello, I don't know if is implemented or not, but could be great has a little control about that interface as you can do in a Virtual Machine. In addition the possibility of can change the network interface, between ethernet, or USB 
Thanks

**Comment by andrp92** [comment]
Also consider taking a look at this https://github.com/microsoft/WSL/issues/4150

**Comment by luxzg** [comment]
Allowing to chose an interface for WSL2 instance would be a step in right direction.

To expand on it, if possible, allowing for multiple interfaces on same WSL2 instance, or for having multiple instances (eg different distros), each hooked to different network interface.

Multiple interfaces would allow communication to different (separate) networks, etc
