### ISSUE TITLE
WSL2 with wsl.conf "uid=1000,gid=1000" duplicates uid and gid in actual mount

### ISSUE THREAD

**Issue by diablodale** [microsoft/WSL#5122]
WSL2 with a wsl.conf file having automount options for `uid` and `gid` duplicates them in actual mount

### Setup

* Windows 10 2004 build 19041.207
* fresh install of distro Debian from Windows Store
* fresh change of that Debian distro to WSL2
* updated WSL2 kernel as needed to switch distro to WSL2

### Repro

1. Run Debian
2. create a `/etc/wsl.conf` with the following content
   ```
   [automount]
   options = "metadata,uid=1000,gid=1000,fmask=0027,dmask=0027"
   ```
3. Terminate the Debian distro
4. Run Debian
5. at the prompt run `mount`

### Result

The mount info for the C drive will have duplicated uid and gid in it 👯‍♀️
```
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;uid=1000;gid=1000;fmask=0027;dmask=0027;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```

### Expected

The uid and gid to be listed only once, and it to be the uid and gid specified in `wsl.conf`

### Notes

I have not yet noticed harm if the gid and uid are the same as the duplicates.
I do not know when they are different that harm occurs. Or other combinations.

In general, the official doc for WSL2 points to the official doc for WSL Distro management https://docs.microsoft.com/en-us/windows/wsl/wsl-config which writes 

> By default, WSL sets the uid and gid to the value of the default user (in Ubuntu distro, the default user is created with uid=1000,gid=1000). If the user specifies a gid or uid option explicitly via this key, the associated value will be overwritten. Otherwise, the default value will always be appended.

Therefore, I believe whatever code is putting the duplicate, should be overwritten by the gid,uid specified in `wsl.conf`

**Comment by diablodale** [comment]
Continues to be a bug in WSL2
Microsoft Windows [Version 10.0.19042.541]
kernel 4.19.128

**Comment by benhillis** [comment]
This is a display issue only, the last uid/gid in the string are the values provided by /etc/wsl.conf and will take priority.
