### ISSUE TITLE
Unable to Turn on Subsystem Feature

### ISSUE THREAD

**Issue by TomGarvey456** [microsoft/WSL#5123]
When I attempt to enable the Subsystem feature in PowerShell with the following

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

I get the following message. 

Enable-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

I am unsure how to proceed. When I attempt to install Ubuntu, I am unable to do so.

**Comment by onomatopellan** [comment]
https://superuser.com/questions/1168451/how-can-i-provide-elevation-to-an-operation

**Comment by prabhb1** [comment]
> https://superuser.com/questions/1168451/how-can-i-provide-elevation-to-an-operation

Hi onomatopellan,

I tried the above command in PowerShell with Run as Administrator option and had a different error:

Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand



I'm unable to install ubuntu.

**Comment by onomatopellan** [comment]
@prabhb1 Which Windows build? You should also see Windows Subsystem for Linux in the Windows  features dialog.
![enable-windows-subsystem-linux-windows-10](https://user-images.githubusercontent.com/599142/80588935-8ba6c780-8a19-11ea-9998-addb6ff0c7bf.jpg)

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows. Also your Windows build.
