### ISSUE TITLE
unable to run ng serve --open

### ISSUE THREAD

**Issue by DrewStax1982** [microsoft/WSL#5128]
im unable to run the examples tht iam given, Im new to programming and really could use a hand im new to node-modules, Im afraid i might have erased a file and now im not getting the right output...

**Comment by sirredbeard** [comment]
You may wish to consult more general programming, Angular, and Linux command line resources to become more comfortable in file handling and setting up your development environment.

Here are some you can begin with: https://github.com/sirredbeard/Awesome-WSL#using-wsl

You could also look for YouTube videos, tutorials, and other guides to get you started.
