### ISSUE TITLE
WSL 2 and Ubuntu 20.04

### ISSUE THREAD

**Issue by thedozo** [microsoft/WSL#5129]
I'm running Windows 10 version 2004 (build 19041.207) from Insider release preview. I have configured WSL 2 properly in my system and also installed Kernel component update. Last night Ubuntu 20.04 LTS has been released. But I'm facing an error while trying to run this under WSL 2.
Error screenshot is here - https://i.ibb.co/LQ9XbxC/sc1.png
I don't have any proxy/VPN tool installed.

**Comment by Biswa96** [comment]
How did you install it?

**Comment by thedozo** [comment]
> How did you install it?

https://www.youtube.com/watch?v=MiAocGRMJwY

**Comment by thedozo** [comment]
Solved. NoLSP command works.
