### ISSUE TITLE
WSL2 Allows to create files and folders with Windows Reserved Name

### ISSUE THREAD

**Issue by COLAMAroro** [microsoft/WSL#5130]
Using WSL 2, it is possible to create files and folders that can't exist in a Windows operating system
[MSDN - Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN)

### Windows Version
`Microsoft Windows [Version 10.0.19041.207]`

### Commands:
```sh
mkdir /mnt/c/aux
echo "nul" > /mnt/c/aux/nul
echo "con" > /mnt/c/aux/con.exe
```

### Excepted behavior:
Probably a Permission denied error

### Actual behavior:
Working without any issue.
`explorer.exe .` can not open a directory with a reserved name, neither can `code .`
However, `code .` using the `WSL - Remote` option can open a folder containing impossible files (and open impossible files without issues)

**Comment by sirredbeard** [comment]
WSL users are just extreme like that. 😉
![EWFD4WjU4AAV4pM](https://user-images.githubusercontent.com/33820650/80249856-91c72d80-8640-11ea-8a74-f59de7ea3b5f.png)

**Comment by benhillis** [comment]
This is by design. You can also do this by calling the NtCreateFile API (not the Win32 createfile) api.  WSL just makes it easier.

**Comment by COLAMAroro** [comment]
It make sense :)

Thanks for the answer !
