### ISSUE TITLE
WSL1 places VPN-provided DNS servers last in /etc/resolv.conf

### ISSUE THREAD

**Issue by dchsueh** [microsoft/WSL#5132]
**Please fill out the below information:**
* Your Windows build number:

10.0.18362.535
running ubuntu-18.04

* What you're doing and what's happening: 

On connecting to a VPN, one VPN nameserver is being added to the end of /etc/resolv.conf

* What's wrong / what should be happening instead:

The VPN's nameserver should be added at the top of /etc/resolv.conf

**Comment by ggiesen** [comment]
This is particularly pertinent with Palo Alto GlobalProtect VPN, as the Windows client by default blocks queries to DNS servers not pushed out by the VPN, completely breaking name resolution.
