### ISSUE TITLE
Docs request: how to import all Root CAs from Windows store into WSL?

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/WSL#5134]
**Is your feature request related to a problem? Please describe.**

I'm writing this because I think that WSL is the most amazing thing that's come along for a long time.  It has my ❤️ 

However, there's a problem that hinders adoption.  It's hindering me and, having worked in a variety of environments I'm pretty confident this is a very common issue.  The situation is well described here: https://security.stackexchange.com/questions/177759/what-is-the-best-practice-when-corporate-network-is-overwriting-ssl-certificates

That's right!  It's the "what do we do when the corporate network overwrites SSL certificates with their own self issued one" problem.  

To quote @rfgamaral:

> I have this self-signed corporate root CA installed on my Windows machine for all internal company services which is not being automatically propagated to WSL.

Related to: https://github.com/Microsoft/WSL/issues/3161

Also see: https://askubuntu.com/questions/1095266/apt-get-update-failed-because-certificate-verification-failed-because-handshake

This leads to command line experiences in WSL like this:

```
~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:5 https://dl.yarnpkg.com/debian stable InRelease
Err:6 https://dl.yarnpkg.com/debian stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.18.126.100 443]
Reading package lists... Done
E: The repository 'https://dl.yarnpkg.com/debian stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Describe the solution you'd like**

This is a very common problem and I'm not aware of any good guidance / documentation on how to set up WSL to use the corporate root CA so that SSL operations do not error out when you are using WSL.  

I'd love it if there were docs which guide you through how to resolve this issue.  Useful points I can think of:

- how you can acquire the corporate CA you'll need inside WSL
- how you can make WSL make nice with the corporate CA

I haven't quite cracked this yet myself and I'm very far from being an expert on certs.  I'm sure some of the things I'm asking for don't quite make sense; forgive me.

What I want is to be able to use WSL on my corporate laptop without crying.  Help me!

**Describe alternatives you've considered**

Not using WSL.  And that makes me sad.

**Additional context**

N/A

**Comment by sirredbeard** [comment]
This is an interesting and compelling feature request that would be helpful in enterprise environments.

**Comment by brianstebar2** [comment]
May I suggest the documentation also include details about how to _keep_ Windows' CAs synced after initial import?  If other folks' corporate environments are anything like mine, their companies have a habit of adding, expiring, or otherwise tweaking their CA certs occasionally. It'd be nice if these were _automatically synced_ between Windows and the WSL OS.

**Comment by mrslezak** [comment]
What I don't understand is why they didn't make an interface to have WSL2 automatically use the Windows Certificates on the same machine.  Yes, I know they are in different formats typically on Windows and Linux certificate stores, but CAs generated by Group Policy on Enterprise machines in corporations make this a real headache.  Especially when you can't export the private keys to import into WSL2; it becomes useless. 

I understand that they probably didn't make it that far in developing WSL2, and switched over to Windows 11 development.  But this was an excellent product that could be used by corporations all over the place with just a few patches.  My IT department has been trying to get the keys exported from the Windows Certificate Store to no avail to import into WSL2...

**Comment by progressEdd** [comment]
>  * how you can acquire the corporate CA you'll need inside WSL
>  * how you can make WSL make nice with the corporate CA

I'd also include a section for Zscaler, but I think the same steps apply.

------ 
# How I solved Zscaler ssl issues
Here's the steps I took [I wrote this also on stackoverflow](https://stackoverflow.com/a/71164917/16150356)
## background
I had this same issue, but ran into a similar with my work laptop except where Zscaler blocked my curl, git, and anaconda traffic. The temporary fix was to disable ssl verification, but this introduces a number of security vulnerabilities such as man-in-the-middle attacks.

## Solution
The long term solution is to get the Zscaler certificate and add it to your shell file. Run the following commands in WSL after getting the certificate and navigating to the directory.
```
echo "export SSL_CERT_FILE=<Path to Certificate>/ZscalerRootCA.pem" >> $HOME/.bashrc
```
which I got from
https://help.zscaler.com/zia/adding-custom-certificate-application-specific-trusted-store#curl-SSL_CERT_FILE
They have more commands for other applications

If you use any other shells, make sure to change `.bashrc` to the directory of the configuration of that file. In my case I use fish, so I replaced `$HOME/.bashrc` with `$HOME/.config/fish/config.fish`

```
echo "export SSL_CERT_FILE=<Path to Certificate>/ZscalerRootCA.pem" >> $HOME/.config/fish/config.fish
```

After adding the certificate, make sure to reload the shell. In my case, I ran using instructions from [jeffmcneil](https://jeffmcneill.com/path-bash-shell-fish-shell/)

```
source ~/.config/fish/config.fish
```
for bash, you would want to run
```
source ~/.bashrc
```
or
```
. ~/.bashrc
```

from
https://stackoverflow.com/a/2518150/16150356

**Comment by DarkChocolate** [comment]
@progressEdd - Your solution didn't work for me. 
I was able to locate the ZScalar .cer in my C drive, I put the .cer and .pem (converted .cer to .pem) paths in the .bashrc file but unfortunately, none of them worked 😞 
Does anyone know how to resolve this issue? It's very frustrating...

**Comment by DarkChocolate** [comment]
![image](https://github.com/microsoft/WSL/assets/6497560/aa8a099c-5449-4414-9532-bdf235023f45)

**Comment by 1data0** [comment]
You could try something like the following for an Ubuntu VM on WSL2

```powershell
# Get Zscaler root CA
#
# Get certificate thumbprint
$cert = @(Get-ChildItem -path Cert:\* -Recurse | where {$_.Subject –like '*Zscaler Root CA*'})[0] | Select -ExpandProperty Thumbprint
#
# Export certificate in DER format
Get-ChildItem -Path Cert:\LocalMachine\Root\ | where{$_.Thumbprint -eq $cert} | Export-Certificate -Type cer -FilePath $env:USERPROFILE\zscaler.cer
##

# Import Zcaler Root CA
wsl --user root -e bash -c "cd /mnt/c/Users/$Env:UserName/; cp zscaler.cer /root/;cd;ls"
wsl --user root -e bash -c "cd; openssl x509 -inform der -in zscaler.cer -out zscaler.crt;ls"
wsl --user root -e bash -c "cd /etc/ssl/certs/;cp /root/zscaler.crt .;chmod 644 zscaler.cert;ls -l"
wsl --user root -e bash -c "update-ca-certificates -v -f;"

```

**Comment by dominik-ba** [comment]
was this ever really fixed or is everyone doing a workaround on their own system?

**Comment by vsamarcus** [comment]
That's worked for me! Thanks @1data0.

Problem:

<img width="978" height="441" alt="Image" src="https://github.com/user-attachments/assets/78cf0ea1-5456-495f-a4ff-9fa4c0b742ee" />

Resolved:

<img width="946" height="816" alt="Image" src="https://github.com/user-attachments/assets/1092e5ff-a2b3-4b97-869c-a9050630f615" />

Thanks!

**Comment by mdziezyc** [comment]
> wsl --user root -e bash -c "cd /etc/ssl/certs/;cp /root/zscaler.crt .;chmod 644 zscaler.cert;ls -l"

`.cert` -> `.crt` - typo :)
