### ISSUE TITLE
FAH on WSL

### ISSUE THREAD

**Issue by ajmch** [microsoft/WSL#5137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajmch** [comment]
Not sure whether this is a bug report or a lacking feature. 

I'm trying to run foldingathome (FAH https://foldingathome.org/ - a distributed computing system used to simulate the folding of proteins, now essentially used in the struggle against the coronavirus) on Ubuntu via WSL. 

It's a test, in order to see whether it would be better to run FAH via WSL, as it is faster (more efficient) on Linux than on Windows. There is a thread about it on the FAH forum (last post: https://foldingforum.org/viewtopic.php?p=330089#p330089). 

I am running Win 10 Pro 2004, with WSL. I installed Ubuntu 18.04, then everything that is needed to run FAH (AMD and Nvidia drivers, OpenCL, FAHClient and FAHControl). I also installed Xming in order to run FAHControl in graphical mode, which allows to monitor the client software and configure the whole thing. 

So far it worked quite well. It is actually folding (ie running), and FAHControl can be generated via Xming (screenshot on the forum page above). But I can only use the CPU. When I want to add a GPU slot, Ubuntu throws an error: 
`ERROR: On client "local" 127.0.0.1:36330: No available GPUs`

Now, is it a mere configuration problem, or is WSL2 not able yet to use GPUs? And if it is the latter, when can we hope to have that feature implemented?

Thank you!

**Comment by Biswa96** [comment]
Will FAH in WSL really do any better job than running it in actual Linux distribution? WSL1 is like a kernel mode compatibility layer and WSL2 is a lightweight virtual machine. So, FAH wastes a portion of the CPU juice just for "translation".

**Comment by ajmch** [comment]
I think it won't, of course, but it might be better than using the Windows client. And if so, the Windows client could be adapted to use WSL/Linux.

**Comment by ajmch** [comment]
I found my answer here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2-are-there-plans-to-increase-hardware-support
And as it seems to have been a much discussed topic already, I close this issue.
