### ISSUE TITLE
wsl 2 the virtual machine or container with the specified identifier is not running

### ISSUE THREAD

**Issue by fcabrera86** [microsoft/WSL#5140]
Please , i can´t install wsl2.
Virtualization is enabled in BIOS and in windows features but when i try wsl --set-version Ubuntu 2 show me this message:
"the virtual machine or container with the specified identifier is not running"

i dont find any solution

**Comment by bplasmeijer** [comment]
@fcabrera86 please look at the installed distributions, ```wsl -l -all```.
