### ISSUE TITLE
apt-get update not working

### ISSUE THREAD

**Issue by guidovbrakel** [microsoft/WSL#5142]
Ubuntu 18.04 WSL

Please help fix this
```
sudo apt-get update
[sudo] password for guido:
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable)
Err:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable)
Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by PrakharUniyal** [comment]
Hi @guidovbrakel , this seems like a network issue to me. Can you check and tell whether the internet is working? Try running this command and share your output:
```
get --spider google.com
```

**Comment by aaemon** [comment]
same issue, wsl2 internet not working, but wsl1 is working fine.

**Comment by aaemon** [comment]
> Hi @guidovbrakel , this seems like a network issue to me. Can you check and tell whether the internet is working? Try running this command and share your output:
> 
> ```
> get --spider google.com
> ```

wsl2 internet not working, but wsl1 working fine. I tried reinstalling windows, same issue.

**Comment by guidovbrakel** [comment]
Hi,

I removed the Client Hyper-V role and then it started working again. Seems to be conflicting with each other on th network part

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dhikrahashim** [comment]
Is this issue fixed? Same error for me also. but ping to google.com is working for me.

Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Connection failed [IP: 2001:67c:1562::15 80]
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Connection failed [IP: 2001:67c:1562::18 80]
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Connection failed [IP: 2001:67c:1562::15 80]
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Connection failed [IP: 91.189.88.142 80]
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Connection failed [IP: 2001:67c:1562::18 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Connection failed [IP: 2001:67c:1562::15 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Connection failed [IP: 91.189.88.142 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Connection failed [IP: 2001:67c:1562::15 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

==================================
 ping google.com
PING google.com(maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e)) 56 data bytes
64 bytes from maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e): icmp_seq=1 ttl=54 time=93.8 ms
64 bytes from maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e): icmp_seq=2 ttl=54 time=129 ms

**Comment by guidovbrakel** [comment]
> Is this issue fixed? Same error for me also. but ping to google.com is working for me.
> 
> Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
> Connection failed [IP: 2001:67c:1562::15 80]
> Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
> Connection failed [IP: 2001:67c:1562::18 80]
> Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
> Connection failed [IP: 2001:67c:1562::15 80]
> Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
> Connection failed [IP: 91.189.88.142 80]
> Reading package lists... Done
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease Connection failed [IP: 2001:67c:1562::18 80]
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease Connection failed [IP: 2001:67c:1562::15 80]
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease Connection failed [IP: 91.189.88.142 80]
> W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease Connection failed [IP: 2001:67c:1562::15 80]
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> ==================================
> ping google.com
> PING google.com(maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e)) 56 data bytes
> 64 bytes from maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e): icmp_seq=1 ttl=54 time=93.8 ms
> 64 bytes from maa05s03-in-x0e.1e100.net (2404:6800:4007:80d::200e): icmp_seq=2 ttl=54 time=129 ms

Yes for me it's fixed.

**Comment by jameshfisher** [comment]
I have the exact same issue - how did you fix it @guidovbrakel?

**Comment by DipanjaliNaik** [comment]
@jameshfisher 
Did the issue get fix for you. Even I am facing same problem.

**Comment by mrcat323** [comment]
@jameshfisher @aaemon @dhikrahashim @PrakharUniyal guys I have fix here. Just while running `apt-get update` or something just add `-o Acquire::ForceIPv4=true` something like:
```apt-get  update -o Acquire::ForceIPv4=true```
but to solve this problem permanently create a file with `99force-ipv4` in `/etc/apt/apt.conf.d/` directory and add following stuff:
```Acquire::ForceIPv4 "true"; ```

**Comment by khairaf** [comment]
run this command doesn't work for me
> `apt-get update -o Acquire::ForceIPv4=true`

**Comment by courteous** [comment]
In my case it was the problem related to the configuration of the  /etc/apt/sources.list. All the packages was configured for https and when i visited http://91.189.91.39/ over Firefox i realized that this site does not support https at all. then i changed to some other mirror  any that support https i.e. from the list below and it all worked.  https://launchpad.net/ubuntu/+archivemirrors

**Comment by eldano1995** [comment]
Checkout my comment: maybe it helps: https://github.com/microsoft/WSL/issues/5061#issuecomment-756457106

**Comment by lbiru** [comment]
> 
> 
> In my case it was the problem related to the configuration of the /etc/apt/sources.list. All the packages was configured for https and when i visited http://91.189.91.39/ over Firefox i realized that this site does not support https at all. then i changed to some other mirror any that support https i.e. from the list below and it all worked. https://launchpad.net/ubuntu/+archivemirrors

Thank you.
This solution work for me.

**Comment by Rajkgokeda** [comment]
In my case it was the problem related to the configuration of the /etc/apt/sources.list. All the packages was configured for https and when i visited http://91.189.91.39/ over Firefox i realized that this site does not support https at all. then i changed to some other mirror any that support https i.e. from the list below and it all worked. https://launchpad.net/ubuntu/+archivemirrors

After applying various solutions available in google for the whole day, this is the one worked for me. Thank you so much.

**Comment by sadeghams** [comment]
i had same issue and resolve with disabling my anti virous application( symantec endpoint )

**Comment by ElAmen** [comment]
> i had same issue and resolve with disabling my anti virous application( symantec endpoint )

This worked for me. Thanks

**Comment by krogge-obando** [comment]
> i had same issue and resolve with disabling my anti virous application( symantec endpoint )

This worked for me thanks for sharing!

**Comment by fahadmeraj** [comment]
disabling the symantec end protection anti virus resolved the issue for me. I had the same issue that internet was on and DNS was configured but still I was unable to connect to the repos of Ubuntu

**Comment by serup** [comment]
disabling the antivirus is definitely not recommended - find another way

**Comment by IAmTahazzot** [comment]
> In my case it was the problem related to the configuration of the /etc/apt/sources.list. All the packages was configured for https and when i visited http://91.189.91.39/ over Firefox i realized that this site does not support https at all. then i changed to some other mirror any that support https i.e. from the list below and it all worked. https://launchpad.net/ubuntu/+archivemirrors
> 
> After applying various solutions available in google for the whole day, this is the one worked for me. Thank you so much.

Can you please help me to get through all of this steps :( I am so new here. I need wsl2 badly, I am stuck with this problem for about more than 6 month. Please.

**Comment by hirwa-nshuti** [comment]
I had the same issue and was resolved by editing 

> /etc/apt/sources.list

I replaced all 

http://**xx**.archive.ubuntu.com/ubuntu... with  http://archive.ubuntu.com/ubuntu ...

and it worked out.

You can try it

**Comment by fahadmeraj** [comment]
Thank you

**Comment by IAmTahazzot** [comment]
> Thank you
> 

Has it worked?

**Comment by Aprime98** [comment]
It worked ... 
Navigate to sudo visudo /etc/apt/sources.list  to change where apt gets the packages and save after changing.

**Comment by bkoprivica** [comment]
> get --spider google.com



> I had the same issue and was resolved by editing
> 
> > /etc/apt/sources.list
> 
> I replaced all
> 
> > http://**xx**.archive.ubuntu.com/ubuntu... with  http://archive.ubuntu.com/ubuntu ...
> 
> and it worked out.
> 
> You can try it

I do not have xx.archive but archive... It did not resolve the issue.

**Comment by bkoprivica** [comment]
> -o Acquire::ForceIPv4=true

it doesn't work

**Comment by bkoprivica** [comment]
> Client Hyper-V role

My Hyper-V feature is not selected, but the issue persist.

**Comment by Cheran-VG** [comment]
> i had same issue and resolve with disabling my anti virous application( symantec endpoint )

Thanks, disabling Symantec worked for me.

**Comment by fahadmeraj** [comment]
I cannot remember as a lot of time has passed. I think I reinstalled the OS
to resolve the issue. I found that the VM on my local machine was being
problematic.

**Comment by Bang1338** [comment]
# Solution
- Disable your god damn antivirus firewall

Wise word to ESET: why

**Comment by manwarhussain** [comment]
Err:7 https://download.mono-project.com/repo/ubuntu vs-bionic InRelease
  Could not connect to 121.0.0.0:443 (121.0.0.0). - connect (110: Connection timed out)

**Comment by Bang1338** [comment]
> Err:7 https://download.mono-project.com/repo/ubuntu vs-bionic InRelease Could not connect to 121.0.0.0:443 (121.0.0.0). - connect (110: Connection timed out)

try using vpn

**Comment by aquibmir** [comment]
Allowing OG traffic to archives in my AV software solved the problem.
