### ISSUE TITLE
WSL 2: Cannot launch detached/immune to hangups (nohup ... &) processes from wsl-command

### ISSUE THREAD

**Issue by PHubaut** [microsoft/WSL#5143]
**Issue information:**

* Windows build number:  (`ver` at a Windows Command Prompt)

```none
Microsoft Windows [version 10.0.19041.208]
```

* What I am doing and what's happening:

I am trying to use `wsl` command on Windows side to launch a script/process in the Linux subsystem, detaching it (&), making it immune to hangups (nohup) so that it remains running when `wsl` command completes.

To illustrate and reproduce the issue, here is the `test.sh` script I am using, stored in my `$HOME` directory, where the `sleep 99999` command (that does nothing else than waiting for 99999") is a placeholder for some actual daemon-like script I want to launch. `test.sh` is

```bash
#!/bin/bash
echo "Before \"nohup sleep 99999 &\" ..."
nohup sleep 99999 </dev/null >/dev/null 2>&1 &
echo "... after \"nohup sleep 99999 &\"."
```

This script can be invoked from a Linux `bash` session: (1)

```bash
~/test.sh
```

or from Windows side, using the `wsl`command: (2)

```cmd
wsl -- ~/test.sh
```

In both cases, a detached process should be started, executing the sleep command and therefore waiting for 99999" and this process should not be killed when either the `bash` session is closed or
on Windows side, when the `wsl` command returns. Opening anew a `bash` session and executing `ps -ef` command (or from Windows `wsl -- ps -ef`) should show a process executing "sleep 99999".

Unfortunately, it works in case (1) but not (2) preventing, therefore, to launch a daemon-like program from Windows using `wsl` command.

Note: it happened to fail on an early version of WSL 1 as well but was corrected (shutting down the subsystem despite processes were supposed to be still running, therefore, keeping subsystem alive) - WSL 2 - not working.

* What's wrong / what should be happening instead:

**Wrong behavior (when `wsl`command is called from Windows side)**

Showing no `sleep 99999` process is running,

```cmd
C:\>wsl -- ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  2 17:51 ?        00:00:00 /init
root         6     1  0 17:51 ?        00:00:00 /init
root         7     6  0 17:51 ?        00:00:00 /init
Pierre       8     7  1 17:51 pts/0    00:00:00 ps -ef
```

Starting the script (we can see from output it is executed)

```cmd
C:\>wsl -- ~/test.sh
Before "nohup sleep 99999 &" ...
... after "nohup sleep 99999 &".
```

Showing the running processes after script execution

```cmd
C:\>wsl -- ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:51 ?        00:00:00 /init
root        13     1  0 17:51 ?        00:00:00 /init
root        14    13  0 17:51 ?        00:00:00 /init
Pierre      15    14  0 17:51 pts/0    00:00:00 ps -ef
```

As we can see there is no `sleep 99999` process running (killed somehow) although it should be present.

**Correct Behavior (can only be shown when invoked from `bash` session due to issue)**

Invoking `ps -ef`to show no `sleep 99999`process, executing script `~/test.sh` then `ps -ef`again to
see the `sleep 99999`process. This is expected bahavior.

```bash
Pierre@PierreTAB1:~$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:53 ?        00:00:00 /init
root        23     1  0 17:53 ?        00:00:00 /init
root        24    23  0 17:53 ?        00:00:00 /init
Pierre      25    24  0 17:53 pts/0    00:00:00 -bash
Pierre      38    25  0 17:53 pts/0    00:00:00 ps -ef
Pierre@PierreTAB1:~$ ~/test.sh
Before "nohup sleep 99999 &" ...
... after "nohup sleep 99999 &".
Pierre@PierreTAB1:~$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:53 ?        00:00:00 /init
root        23     1  0 17:53 ?        00:00:00 /init
root        24    23  0 17:53 ?        00:00:00 /init
Pierre      25    24  0 17:53 pts/0    00:00:00 -bash
Pierre      40    24  0 17:53 pts/0    00:00:00 sleep 99999
Pierre      41    25  0 17:53 pts/0    00:00:00 ps -ef
Pierre@PierreTAB1:~$
```

Closing the `bash` session and opening another one a few minutes later will still show the `sleep 99999`process indicating the Linux subsystem was not shutdown

```bash
Pierre@PierreTAB1:~$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:53 ?        00:00:00 /init
root        24     1  0 17:53 ?        00:00:00 /init
Pierre      40    24  0 17:53 ?        00:00:00 sleep 99999
root        45     1  0 17:56 ?        00:00:00 /init
root        46    45  0 17:56 ?        00:00:00 /init
Pierre      47    46  1 17:56 pts/0    00:00:00 -bash
Pierre      60    47  0 17:56 pts/0    00:00:00 ps -ef
Pierre@PierreTAB1:~$
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

n/a

* For WSL launch issues, please [detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

n/a

**Comment by PHubaut** [comment]
`[version 10.0.19041.264]` - it looks like there is a regression in WSL2 (vs WSL1) -
_Following a recent reaction by @chris2crawford in https://github.com/microsoft/WSL/issues/3670#issuecomment-632457575 to an old solved issue_
The issue is back in WSL2 and (the long description above) can be summarized as: `wsl.exe bash -c "nohup sleep 99999 &"` will not leave a running `sleep 99999` process (check with `wsl.exe  ps -ef`) when it should. To the contrary, `wsl.exe bash -c "nohup sleep 99999 & sleep 1"` will do (`sleep 0` was not always working for me, I suspect `sleep 1` may also fail on some machine - looks like some race and may depend on processor speed, CPU load...). Comment in the old issue record was marked by @therealkenc as **fixedin1903**, for this new issue relating to WSL2, it is not fixed in `10.0.19041.264` (which is `2004`).

**Comment by chris2crawford** [comment]
I was reporting behavior of WSL1 + VcXsrv, not the insider build.
--Chris

Christopher Crawford,  Director of Graduate Studies

Department of Physics and Astronomy, University of Kentucky

859-257-2504 (o)  859-421-9612 (c)  schedule: www.pa.uky.edu/~crawford

**Comment by therealkenc** [comment]
> looks like some race

This is variation #4649. That issue is sort of in an undead state until someone authoritative declares it by-design. Note the issue title over there is incorrect: nothing is being killed. The shell exited and so did the child of its own volition. Generally speaking, folks are imagining shell job control behaving differently that it does.

This said, without dedicating enough neurons to thinking about it, I'd imagine this _might_ ought work but it doesn't:

![image](https://user-images.githubusercontent.com/7049700/82839813-70e33980-9e85-11ea-9252-0149cdf65564.png)

Won't dupe on the basis disowning off a `wsl.exe bash -c` is "different".

**Comment by therealkenc** [comment]
This will get you there; although I hesitate to recommend anyone reach for the big [`daemonize(1)`](http://manpages.ubuntu.com/manpages/bionic/man1/daemonize.1.html) hammer without at least keeping tabs on this issue and #4649 for some conclusive behavioral explanation, by-design or otherwise. [Lest it get pasted all over the Interwebs bad serverfault-advice style.]

```
C:> wsl.exe bash -c "daemonize /bin/sleep 9999; wait $!"
```

In English: Ignore terminal signals, disavow `stdin`/`stdout`/`stderr`, and wait for the `fork()` to happen before abandoning your child.

![image](https://user-images.githubusercontent.com/7049700/82841988-dc7cd500-9e8c-11ea-8460-26366f93c16d.png)

**Comment by chris2crawford** [comment]
OK maybe that's why I needed the sleep 0  at the end of:
wsl.exe bash -c "DISPLAY=:0 nohup xclock & sleep 0"

**Comment by therealkenc** [comment]
That `sleep 0` is going to race for sure; Dustin [isn't wrong](https://github.com/microsoft/WSL/issues/4649#issuecomment-552147258). Undefined behavior on Real Linux™ too. My only head-scratch is why a `disown` won't take in your scenario. [I have a WAG but would do more damage than good speculating.]

**Comment by therealkenc** [comment]
I see it now (late). Cookbook answer for your real ask (`xeyes`), you want:

```
C:\>wsl.exe nohup sh -c "DISPLAY=:0 xeyes &" < nul > nul 2>&1
```

![image](https://user-images.githubusercontent.com/7049700/82866771-6608c300-9ede-11ea-880b-558062619a7b.png)

In the alternative:

```
C:\>wsl.exe daemonize /bin/sh -c "DISPLAY=:0 exec xeyes"
```

![image](https://user-images.githubusercontent.com/7049700/82867310-779e9a80-9edf-11ea-83a6-e66995c85900.png)

**Comment by chris2crawford** [comment]
disown worked sometimes (together with nohup), but not reliably as the Target in an icon on the taskbar to start X11/emacs.

**Comment by therealkenc** [comment]
The two alternatives will work reliably, although from a shortcut you'll have to forgo the redirects (`> nul`) and settle for `nohup.out`.

![image](https://user-images.githubusercontent.com/7049700/82871052-c94a2380-9ee5-11ea-9e6d-2282e33b3b03.png)

Or use the alternative which avoids the redirects.

**Comment by PHubaut** [comment]
> I was reporting behavior of WSL1 + VcXsrv, not the insider build. --Chris

Indeed. I was actually referencing your `wsl.exe bash -c "DISPLAY=:0 nohup clock & sleep 0"` example which, I realize, was actually the same problem I was facing... in WSL2.

**Comment by PHubaut** [comment]
by the way, as this post is referring to WSL2, the `DISPLAY=:0` part in the commands may need to be changed to `DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0` or similar
See #4150

**Comment by Jason5Lee** [comment]
I got this problem. Is there any solution for starting a background process from the Windows side?
