### ISSUE TITLE
can't make haxm because I need the lib modules for 4.4.0-19041-Microsoft

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#5145]
Hello.

I would like to make an experiment. I would try to install and use haxm to accelerate qemu,instead of kvm. I prefer to use the WSL 1 instead of 2,because I can't keep the hypervisor down,since haxm does not need it. So,I've configured WSL with ubuntu 16.04 and I tried to install haxm. This is what happened :

root@DESKTOP-N9UN2H3:~/Desktop/haxm/platforms/linux# make

make -C /lib/modules/4.4.0-19041-Microsoft/build M=$PWD modules

make[1]: *** /lib/modules/4.4.0-19041-Microsoft/build: No such file or directory. Stop.

Makefile:29: recipe for target 'modules' failed

make: *** [modules] Error 2

I need the source code,the headers and the modules of the kernel "4.4.0-19041-Microsoft". I see that the linux kernel for wsl 2 is here :

https://github.com/microsoft/WSL2-Linux-Kernel

but I haven't found the kernel for WSL 1 in any place.

**Comment by DHowett-MSFT** [comment]
WSL1 does not have a Linux kernel. Applications are running directly on the NT kernel. You cannot install kernel modules.
