### ISSUE TITLE
using std::async on a WSL2 Ubuntu distro

### ISSUE THREAD

**Issue by shalevm** [microsoft/WSL#5149]
Hi,

I've recently started using WSL2 with Ubuntu 18.04.

i wanted to see how it handles using threads, so i wrote a small example program that uses `std::async`.

specifically the line
`auto ftr = std::async(std::launch::async, X(), 42);`

​where X() is a simple fanctor.
when i try to compile i get the following compilation error:

`/usr/include/c++/7/thread:122: undefined reference to pthread_create`

i also tried several other ways of using `std::async`, all resulted in the same compilation error.

​I have g++ version 7.5 installed on the Ubuntu distro. The program runs fine on a stand-alone Ubuntu machine (and directly on windows for that matter).
so I'm assuming the problem is with WSL2, and a google search did not help. 
any ideas?

Thanks,
Shalev.

**Comment by LightMelodies** [comment]
Just add **-lpthread** to gcc command line.

**Comment by shalevm** [comment]
> 
> 
> Just add **-lpthread** to gcc command line.

nope - already tried that. like i said, this runs fine on a standalone Ubuntu machine, without any additional flags.

**Comment by LightMelodies** [comment]
> > Just add **-lpthread** to gcc command line.
> 
> nope - already tried that. like i said, this runs fine on a standalone Ubuntu machine, without any additional flags.

So what's your complie cmd? **g++ -lpthread xxx.cpp** will fail with gcc 7.5, while **g++ xxx.cpp -lpthread** works fine.

**Comment by shalevm** [comment]
Totally. My bad :)
Thanks!
although i still don't understand how it worked on a standalone Ubuntu
machine without the flag...

**Comment by benhillis** [comment]
Perhaps a different compiler version?
