### ISSUE TITLE
Poor network upload / download speeds after update

### ISSUE THREAD

**Issue by martincox** [microsoft/WSL#5150]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.19041.208]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Extremely slow network speed:

`$>speedtest-cli
Retrieving speedtest.net configuration...
Testing from Three (94.197.82.124)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Structured Communications (London) [2.56 km]: 54.77 ms
Testing download speed................................................................................
Download: 2.82 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.66 Mbit/s`

* What's wrong / what should be happening instead:

Should look more like:

`$> speedtest-cli
Retrieving speedtest.net configuration...
Testing from Three (94.197.82.124)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Mauritius Telecom Ltd (London) [2.56 km]: 43.587 ms
Testing download speed................................................................................
Download: 47.14 Mbit/s
Testing upload speed......................................................................................................
Upload: 23.33 Mbit/s`

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

After rolling back to 10.0.19041.207, the problem for download is resolved but not upload in Ubuntu 18.04. Although, it might be the case that I have never noticed poor upload speeds (may not be a new issue). Interestingly, 20.04 performs as expected for both upload _and_ download.

**Comment by therealninot** [comment]
See if with the following command you get better results:

curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -

I think is an issue with speedtest

**Comment by martincox** [comment]
@therealninot I tried that first and went with speedtest-cli as a second opinion, both results were the same, unfortunately.
