### ISSUE TITLE
WSL randomly breaks the internet

### ISSUE THREAD

**Issue by barnu5** [microsoft/WSL#5153]
Turning on, my Windows 10 laptop works OK.

Several minutes to hours after opening WSL, websites stop loading on the Windows machine.

Antivirus checks are OK.

Using another wifi network does not work

incognito/other browsers makes no difference

Tried netsh winsock reset

Restart fixes the issue

Pinging google.com works OK

See ask ubuntu question which has a workaround

**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.18363.815]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.

[See workaround solution posted on ask ubuntu](https://askubuntu.com/questions/1203412/wsl-causing-my-internet-to-not-work)

**Comment by barnu5** [comment]
![Annotation 2020-05-01 082824](https://user-images.githubusercontent.com/3778403/80765189-c0d02880-8b85-11ea-8ca2-119b1133707e.jpg)

Already this morning. It's only 8:27am

**Comment by barnu5** [comment]
Adding to this, I am running an expo project within WSL. Also, the fingerprint sensor doesn't work when the internet doesn't work, but starts working again after that command is run.

**Comment by barnu5** [comment]
Alright, it looks like this is definitely down to something in the expo app. Still not sure how an issue like this could happen but it's almost certainly not WSL's fault. Still, perhaps something can be done in WSL. Not sure. Leaving this here!

**Comment by Kailonlee** [comment]
I got same problem! Have you solved it?

**Comment by onomatopellan** [comment]
If `www.google.com` doesn't work but `216.58.192.164` does then you will confirm it's a DNS problem.

**Comment by barnu5** [comment]
The issue is with WSL1. Read this: https://github.com/expo/expo/issues/8189

**Comment by klaimane** [comment]
same issue, WSL1, Ubuntu 18.04 Image,
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763
Any solution @Microsoft?

**Comment by mksiq** [comment]
I had the same issue with Windows 10 Home Version 20H2 19042.421 and it was also happening in the previous version.
By some reason I disable Ethernet 3 (Tap-Windows adapter V9), enabling it back fixed my problem. Keep in mind this is Surcace Pro 6 without a Dock. So it means it is virtual connection, most likely necessary for WSL.
