### ISSUE TITLE
Exec format error on WSL with Microsoft Windows [Version 10.0.19041.208] and Ubuntu20.04 LTS

### ISSUE THREAD

**Issue by uraxurax** [microsoft/WSL#5154]
* Windows version / build number
Microsoft Windows [Version 10.0.19041.208]

* Steps required to reproduce
I cannot execute my binary on WSL as follows. [foo.zip](https://github.com/microsoft/WSL/files/4557448/foo.zip)
$sudo apt-get install build-essential
$ cc -c foo.c
$ cc -static -Wl,--omagic -o foo foo.o
$ ./foo
-bash: ./foo: cannot execute binary file: Exec format error

* Copy of the terminal output
I cannot execute my binary on WSL as follows.
$ ./foo
-bash: ./foo: cannot execute binary file: Exec format error
However, I can execute it on WSL2.
$ ./foo
$echo $?
42

* Strace of the failing command
$strace -ff ./foo
execve("./foo", ["./foo"], 0x7fffe5dd4078 /* 21 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++

**Comment by sirredbeard** [comment]
What happens without `-Wl,--omagic`?

I wonder if that is breaking the ELF binary parser in WSL1.
