### ISSUE TITLE
PHP thinks files on a mapped WSL drive in windows are not readable, but they are.

### ISSUE THREAD

**Issue by gwharton** [microsoft/WSL#5155]
**Please fill out the below information:**
* Your Windows build number: 

Microsoft Windows [Version 10.0.19041.208]

* What you're doing and what's happening: 

Launched Ubuntu 20.04 as WSL Version 2
Launched explorer.exe from ubuntu
Mapped network drive to Z:
From windows ran the following PHP test script located at "Z:\home\ubuntu\dev\test.php"

```
<?php
$filename = "Z:\\home\\ubuntu\\dev\\test.php";
echo "Testing " . $filename . "\n";
echo is_readable($filename) ? "Readable\n" : "Not Readable\n";
echo is_file($filename) ? "Is File\n" : "Is not a file\n";
```
```
Z:\home\ubuntu\dev>php test.php
Testing Z:\home\ubuntu\dev\test.php
Not Readable
Is File
```
* What's wrong / what should be happening instead: 

PHP thinks the file is not readable for some reason. This works fine on fixed disks. It only seems to fail on mapped WSL disks.

No idea whether this is PHP's problem or WSL's

**Comment by sirredbeard** [comment]
Can you open test.php with another application on Windows, like notepad.exe?

**Comment by gwharton** [comment]
Yes. A search of php bugs showed similar behaviour back with is_readable not working on network drives but that got fixed. Something to do with ACLs. Seems that a mapped wsl drive behaves differently to a normal network drive.

**Comment by gwharton** [comment]
I changed to using samba in wsl2 and mapping network drive to windows and php works as intended. It is only when accessing via wsl$ that php fails.
