### ISSUE TITLE
WSL2: installation got Error: 0x800706ba

### ISSUE THREAD

**Issue by Falseclock** [microsoft/WSL#5164]
```
PS C:\WINDOWS\system32> systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
```

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706ba
Error: 0x800706ba The RPC server is unavailable.

Press any key to continue...
```

![image](https://user-images.githubusercontent.com/3299139/80806463-92ca0300-8bdc-11ea-9fe5-aebc8f00611c.png)

**Comment by Falseclock** [comment]
[lxcore_logs.zip](https://github.com/microsoft/WSL/files/4564146/lxcore_logs.zip)

**Comment by Falseclock** [comment]
FIXED: DNS Client service must be turned on

**Comment by realray808** [comment]
> [lxcore_logs.zip](https://github.com/microsoft/WSL/files/4564146/lxcore_logs.zip)

Hi, i wanna try this method but i do not know how to use this.  Can u tell me how to solve this problem?

**Comment by Evlpsrfc** [comment]
> > [lxcore_logs.zip](https://github.com/microsoft/WSL/files/4564146/lxcore_logs.zip)
> 
> Hi, i wanna try this method but i do not know how to use this. Can u tell me how to solve this problem?

As he told, turning on DNS Client service can fix this problem. The three .etl files were uploaded just for providing debug info.

**Comment by venkat125** [comment]
This works for me. U saved my frustrating week on installing wsl2 on windows 10. Thanks a lot buddy. KUDOS! @Falseclock

**Comment by gmnowels** [comment]
> FIXED: DNS Client service must be turned on

Yep; AND, I was using VPN service (PIA). Needed that off as often do with app installs from MS Store.

**Comment by mxns-nicolas** [comment]
Thanks @gmnowels for the tip, make sure to turn off your vpn client app when starting your wsl distro.

**Comment by Msouza91** [comment]
Do I have to have DNS Client UP all the time? I use a hosts file to mitigate telemetry and the DNS Client breaks my internet when I load the hosts file...

**Comment by Falseclock** [comment]
@Msouza91 nope, only when installing or converting WSL

**Comment by Msouza91** [comment]
I have tested and unfortunately after installing the distro of my choice I disabled dns cache, when I tried to start my distro, post reboot, in wsl it went back to the RPC server error again.

**Comment by Dannymx** [comment]
I had this happen to me today, I turned off my VPN (PIA) and the problem went away.

**Comment by usmanublox** [comment]
I am not running the VPN on my machine but facing this issue.

PS C:\Windows\system32> systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042


PS C:\Windows\system32> netsh interface show interface

Admin State    State          Type             Interface Name
-------------------------------------------------------------------------
Disabled       Disconnected   Dedicated        Ethernet 2
Enabled        Disconnected   Dedicated        Ethernet
Enabled        Connected      Dedicated        Wi-Fi

PS C:\Windows\system32>

**Comment by usmanublox** [comment]
Hi I am facing this issue on my brand new machine with following info.

```
PS C:\Windows\system32> systeminfo | Select-String "^OS Name","^OS Version"

OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.19042 N/A Build 19042
```

- Don't have VPN running
- Virtualization is enabled in BIOS
- Windows Subsystem for Linux is enabled in features.
- Hyper-V is disabled in features
- Remote Procedure Cal (RPC) is up and running
![image](https://user-images.githubusercontent.com/64967703/143776606-16d616ff-20e1-46ea-8c2d-45a4f021938e.png)
- DNS client is up and running
![image](https://user-images.githubusercontent.com/64967703/143776620-d6ace0ea-8d4f-4c82-b4c7-53c9c52601d9.png)
- DCOM Server Procedure Launcher is up and running
![image](https://user-images.githubusercontent.com/64967703/143776691-cba48152-507b-411b-9ebe-b7ccd85eb639.png)

**Comment by Misunderstood-Wookiee** [comment]
> Hi I am facing this issue on my brand new machine with following info.
> 
> ```
> PS C:\Windows\system32> systeminfo | Select-String "^OS Name","^OS Version"
> 
> OS Name: Microsoft Windows 10 Pro
> OS Version: 10.0.19042 N/A Build 19042
> ```
> 
> * Don't have VPN running
> * Virtualization is enabled in BIOS
> * Windows Subsystem for Linux is enabled in features.
> * Hyper-V is disabled in features
> * Remote Procedure Cal (RPC) is up and running
>   ![image](https://user-images.githubusercontent.com/64967703/143776606-16d616ff-20e1-46ea-8c2d-45a4f021938e.png)
> * DNS client is up and running
>   ![image](https://user-images.githubusercontent.com/64967703/143776620-d6ace0ea-8d4f-4c82-b4c7-53c9c52601d9.png)
> * DCOM Server Procedure Launcher is up and running
>   ![image](https://user-images.githubusercontent.com/64967703/143776691-cba48152-507b-411b-9ebe-b7ccd85eb639.png)

Same here

**Comment by realray808** [comment]
您的邮件已经收到 谢谢

**Comment by Frotty** [comment]
> FIXED: DNS Client service must be turned on

This was indeed the issue, but I was only able to start it by setting the Start registry to value `2` in registry editor and restarting windows. The menu is all greyed out.

**Comment by realray808** [comment]
您的邮件已经收到 谢谢

**Comment by malohr** [comment]
For me the DNS Client was running and all other RPC related services were configured correctly. Also firewall settings did not help. 

But what really did the trick was the following:

1. First check on your network adapter properties if File and printer sharing is enabled and ipv6
2. Check if you have selected the correct time zone in the date & time settings
3. Then run cmd as admin
4. ipconfig /flushdns
5. ipconfig /release
6. ipconfig /renew
7. netsh winsock reset
8. Restart your computer
9. ipconfig /registerdns
10. Retry your ubuntu installation and enjoy WSL 2!

**Comment by realray808** [comment]
您的邮件已经收到 谢谢
