### ISSUE TITLE
Run Ubuntu WSL2 display  'Press any key to continue...'

### ISSUE THREAD

**Issue by soyum2222** [microsoft/WSL#5166]
CPU virtualization is enable.

HYPER-V is open

 I have been using WSL2 for a while ,this problem suddenly appeared  , but i change WSL2 to WSL1 ,WSL1 can run normally.

I tried reinstalling,but it was useless

![image](https://user-images.githubusercontent.com/35021738/80856214-6fee2c00-8c7a-11ea-8b45-b684c6abe6b0.png)

![image](https://user-images.githubusercontent.com/35021738/80856238-ad52b980-8c7a-11ea-944b-5cf204323f0b.png)

![image](https://user-images.githubusercontent.com/35021738/80856268-002c7100-8c7b-11ea-83f5-2f2a2875953e.png)

**Comment by wm775825** [comment]
i meet the same problem today. 
And i try to run 

> wslconfig /u <distribuntion name>

to unregister it, and then reinstall it. However, i meet this disgusting problem...
![1](https://user-images.githubusercontent.com/29559912/80908397-2244f280-8d52-11ea-9e65-1bd541a76bb0.png)

I have to input "Ctrl-C" to kill it. Finally i restart wsl, it remains "Press any key to continue"...



but luckily, wsl1 is okay.

**Comment by benhillis** [comment]
Please fill out the issue template, this is missing a lot of information we would need to debug (version numbers, etc).

**Comment by cdgeass** [comment]
you can try to run `netsh winsock reset` and restart, i resolve it by this

**Comment by soyum2222** [comment]
I  do nothing,  just after few day，WSL2 Back to normal , i dont know why , but I think this issue can be close

**Comment by wm775825** [comment]
> you can try to run `netsh winsock reset` and restart, i resolve it by this

Thanks, it work for me!

**Comment by wm775825** [comment]
https://github.com/microsoft/WSL/issues/5166#issuecomment-626131883

Thanks! It works for me.

**Comment by soyum2222** [comment]
> Please fill out the issue template, this is missing a lot of information we would need to debug (version numbers, etc).

My current Windows version 10.0.19619.1000

**Comment by mamhadu** [comment]
> you can try to run `netsh winsock reset` and restart, i resolve it by this

Until some other software changes it again. I'll give my use case.

Machine with forefront and WSL2:

- WSL2 works as expected but forefront doesn't. Its says that're a problem with the instalation and you need to reinstall it.

- Repair Forefront using the installer. Forefront starts working as expected but WLS stops working with error ( The attempted operation is not supported for the type of object referenced.
Press any key to continue...)

- Execute in a privilege CMS the command `netsh winsock reset` WSL2 starts working again and forefront stops working and is showing the error again.

This is a issue  that happen when, not only forefront, a piece of software changes sometime at the winsock level.

**Comment by cdgeass** [comment]
> > you can try to run `netsh winsock reset` and restart, i resolve it by this
> 
> Until some other software changes it again. I'll give my use case.
> 
> Machine with forefront and WSL2:
> 
> * WSL2 works as expected but forefront doesn't. Its says that is a problem with the installation and you need to reinstall it.
> * Repair Forefront using the installer. Forefront starts working as expected but WLS stops working with error ( The attempted operation is not supported for the type of object referenced.
>   Press any key to continue...)
> * Execute in a privilege CMS the command `netsh winsock reset` WSL2 starts working again and forefront stops working and is showing the error again.
> 
> This is a issue that happen when, not only forefront, a piece of software changes sometime at the winsock level.

https://github.com/microsoft/WSL/issues/4177#issuecomment-597736482

you can try this, it was offered by Proxifier. it works for me

**Comment by maicWorkGithub** [comment]
2020-06-15，Monday，seems Windows auto restart and update in weekend, os info:
![image](https://user-images.githubusercontent.com/15863224/84610179-4ddc0080-aeec-11ea-85a2-30b419ea560d.png)

below is wsl terminal and terminal app show
![image](https://user-images.githubusercontent.com/15863224/84610215-68ae7500-aeec-11ea-9a68-28350ac965ab.png)
![image](https://user-images.githubusercontent.com/15863224/84610196-5c2a1c80-aeec-11ea-95e6-444f34018504.png)

`netsh winsock reset` not works for me

**Comment by sniper-fly** [comment]
This page might be your help
https://docs.microsoft.com/ja-jp/windows/wsl/wsl2-kernel

I resolved this problem by updating the wsl2 linux kernel

**Comment by maicWorkGithub** [comment]
@sniper-fly you mean reinstall?

**Comment by soyum2222** [comment]
I think this issue related to windows version , I'm use  insider windows version , After this issue ,i  keep update windows , has several versions will reproduce this problem ,and im every time reproduce is after updated .

**Comment by edwardyehuang** [comment]
Same. Just updated to the 20150. Works fine in 2004

**Comment by yan97ao** [comment]
I solved this problem by this https://qiita.com/jun_summer/items/7950f93d65a0757ea7df
This works for me, but I cannot guarantee, and it probably dangerous

1. Switch to windows inside Dev channel
2. Update to Windows 10 Insider Preview 20152.1000 (rs_prerelease)
3. Reboot
4. Run `wsl.exe --update` but get some error
5. Followed by its instruction  and goto https://aka.ms/wsl2kernel
6. Download wsl_update_x64.msi and run it
7. rerun `wsl.exe --update`

**Comment by bpulliam** [comment]
It appears this has been resolved with a kernel update.  If you see this again, please file a new issue so that we can gather logs and diagnose  that (potentially new) problem.
