### ISSUE TITLE
Enviroment variable path failled

### ISSUE THREAD

**Issue by longlong-zhang** [microsoft/WSL#5167]
Hello all,

I have install a software in the directory:```/mnt/c/oommf```,also when i chnage the pwd directory to it the software can work well.

then i add this path to the global enviroment variable path by modefy the ```~/.profile```.

![微信截图_20200503170807](https://user-images.githubusercontent.com/50805242/80910273-b453f780-8d60-11ea-9a51-12fea8c69816.png)

Besides , i have ```soure ~/.profile```

But when i try to run the software in my /home it can not find this software.

Hoping for any suggesstions help me solve this problem.

**Comment by ywsswy** [comment]
source
