### ISSUE TITLE
Connecting iPhone with WSL 2 (Ubuntu)

### ISSUE THREAD

**Issue by thedozo** [microsoft/WSL#5169]
Hello,

Following this method: https://github.com/jovton/USB-Storage-on-WSL2  I have enabled USB storage support in WSL 2 which is running on Ubuntu 20.04.
Also I have found that there is way to connect Android devices too: https://github.com/microsoft/WSL/issues/4692

But I'm using an iPhone and looking for a proper way to connect it with WSL. it can't get connected with WSL like traditional storage devices (i.e. Pendrive). 
is there any way to connect my iPhone with WSL 2?

**Comment by onomatopellan** [comment]
This is how you would do it in real Ubuntu
https://www.maketecheasier.com/easily-mount-your-iphone-as-an-external-drive-in-ubuntu/

Maybe you can do something similar like adb. It seems installing iTunes in Windows makes your device available through TCP localhost:27015 so you could try using 
`export USBMUXD_SOCKET_ADDRESS=0.0.0.0:27015` before calling `idevicepair pair` in WSL2.

**Comment by thedozo** [comment]
@onomatopellan so you are saying i don’t need iSCSI method to connect iPhone with WSL?  Just connecting the phone with Windows and giving following command will work?
export USBMUXD_SOCKET_ADDRESS=0.0.0.0:27015

**Comment by onomatopellan** [comment]
I didn't try it because I don't have an iPhone. You should try first in a real Ubuntu or in a Virtual Machine and if you succeed the try in WSL2.

**Comment by thedozo** [comment]
> That's what Libsusmuxd developer [thinks](https://github.com/libimobiledevice/usbmuxd/issues/126#issuecomment-555780290).
> I didn't try it because I don't have an iPhone. You should try first in a real Ubuntu or in a Virtual Machine and if you succeed then try in WSL2.

Real Ubuntu will get iPhone as usual, but connecting it with WSL is the hardest part. It seems usbmuxd didn’t help that guy in given link.

**Comment by onomatopellan** [comment]
Because that was WSL1. Maybe it works in WSL2.
What I'm sure is if you succeed it will be with a TCP method like adb/xserver/Pulseaudio.

This explains the iTunes thing:
https://www.secureauth.com/sites/default/files/project/attachment/2018-10/iPhone-TCP-connection-through-USB.pdf

**Comment by thedozo** [comment]
@onomatopellan 
The method of https://www.maketecheasier.com/easily-mount-your-iphone-as-an-external-drive-in-ubuntu/ is working in Real ubuntu machine, but not in WSL 2.
I have iTuens installed and I tried with usbmuxd command. But device is not being detected.
![Capture](https://user-images.githubusercontent.com/55230761/80917122-c6dd2980-8d7e-11ea-838e-d6c2467d882c.PNG)
I also tested with 0.0.0.0 and 127.0.0.1 IP. But same result. Although the command of usbmuxd didn't produce any error. What to do now?

**Comment by onomatopellan** [comment]
In Resource Monitor -> Network tab- > Listening ports can you see if there is an exe listening on port 27015?

**Comment by thedozo** [comment]
@onomatopellan 
yes, a process is running on port 27015
![Capture](https://user-images.githubusercontent.com/55230761/80920705-67d5df80-8d93-11ea-93a8-e565f36ac23f.PNG)

Also tried with PC's IP (192.168.1.104) but result is same. No iphone is detected.

**Comment by onomatopellan** [comment]
AppleMobiceDeviceService is actually using USBMUXD so you already have it in the Windows side waiting for connections.
Now the problem is connecting from WSL2. Try `idevicepair --debug pair` to see if it shows more info.

**Comment by thedozo** [comment]
> AppleMobiceDeviceService is actually using USBMUXD so you already have it in the Windows side waiting for connections.
> Now the problem is connecting from WSL2. Try `idevicepair --debug pair` to see if it shows more info.
> 
> BTW, its your iPhone jailbroken?

@aseering 
yes, iPhone is jailbroken. is it an issue?

--debug command not showing anything new. Just the same output like before that device not found.

**Comment by onomatopellan** [comment]
@thedozo No problem. If it's jailbroken you can always try things like ssh to access to the iPhone if it's connected to your network.
https://www.reddit.com/r/jailbreak/comments/au20zn/tiptutorial_ssh_into_your_ios_device_on_windows/

**Comment by thedozo** [comment]
@onomatopellan 
Yes, i can ssh Into it but it’s not serving my purpose. I need to connect it somehow with WSL to run some CLI tools to work with the device.

**Comment by onomatopellan** [comment]
I see. And normally those tools what are using to connect to the device? libusb?

**Comment by thedozo** [comment]
> I see. And normally those tools what are using to connect to the device? libusb?

Yes, usb. iPhone need to be connected with USB port to those tools detect it correctly.

**Comment by onomatopellan** [comment]
No, I mean the library used to access those usb ports. Libusb is most common library in Linux but I don't know on Mac world.

**Comment by thedozo** [comment]
> No, I mean the library used to access those usb ports. Libusb is most common library in Linux but I don't know on Mac world.

Yes, libusb. Now I actually need to ‘fool’ the WSL system to believe that iPhone is connected with it via USB post.

**Comment by onomatopellan** [comment]
Did you see the `sudo dmesg` output? Any error usb related?

**Comment by thedozo** [comment]
> Did you see the `sudo dmesg` output? Any error usb related?

@onomatopellan 
no, nothing related to usb in dmesg output :(

**Comment by thedozo** [comment]
SO no solution for me yet?
:sigh:

**Comment by Biswa96** [comment]
> SO no solution for me yet?

Yes, there is and will be always a solution -- install a GNU/Linux distribution and dual-boot it. 🤓

**Comment by onomatopellan** [comment]
@thedozo Any example/source code of linux tools you want to use with the iPhone?

**Comment by thedozo** [comment]
> @thedozo Any example/source code of linux tools you want to use with the iPhone?

@onomatopellan 
Yes, here is one- https://checkra.in/releases/

**Comment by thedozo** [comment]
> > SO no solution for me yet?
> 
> Yes, there is and will be always a solution -- install a GNU/Linux distribution and dual-boot it. 🤓

Ha Ha funny...but no way, thanks

**Comment by onomatopellan** [comment]
>checkra1n is released in binary form only at this stage. We plan to open-source later in 2020.

Thanks. And any tool with source available?

**Comment by thedozo** [comment]
> > checkra1n is released in binary form only at this stage. We plan to open-source later in 2020.
> 
> Thanks. And any tool with source available?

Here’s another- https://sourceforge.net/p/iphoneanalyzer/code/HEAD/tree/

**Comment by onomatopellan** [comment]
Not really source code since uses jar files. Tell me if you find another tool with open sources preferably hosted on github.

**Comment by onomatopellan** [comment]
For checkra1n, as last resort, how about trying running this ISO in a Hyper-v machine? https://github.com/foxlet/bootra1n

About USBIP, this is what I was looking for: https://github.com/axi0mX/ipwndfu
This one uses a [Python library](https://github.com/pyusb/pyusb/blob/master/docs/tutorial.rst) that calls libusb library and thus it should work with a working USBIP. If I have time I'd try to see if USB are really available via USBIP in WSL2.

**Comment by thedozo** [comment]
> For checkra1n, as last resort, how about trying running this ISO in a Hyper-v/VMWare virtual machine? https://github.com/foxlet/bootra1n
> 
> About USBIP, this is what I was looking for: https://github.com/axi0mX/ipwndfu
> This one uses a [Python library](https://github.com/pyusb/pyusb/blob/master/docs/tutorial.rst) that calls libusb library and thus it should work with a working USBIP. If I have time I'd try to see if USB are really available via USBIP using this library in WSL2.

Ok. pls let me know of you find anything. I already tested USB/IP though. It can attach iPhone but can't be detected by tools: https://github.com/cezanne/usbip-win/issues/149 and https://github.com/cezanne/usbip-win/issues/150

**Comment by onomatopellan** [comment]
Ok, this is what I found. Whatever the method you use to access the USB ports (USBIP, iSCSI, VirtualHere) if your device appears in `lsusb` half the job is done. The other half is the kernel and the distro packages. Recompiling the kernel was not enough until I installed mtp-tools and gmtp. You also will need an Xserver like Vcxsvr and install the gtk2.0 package. I finally managed to connect my Galaxy Tab A through ADB and MTP connections but sure it's slow.

![USBIP](https://user-images.githubusercontent.com/599142/81200637-8b33a100-8fc4-11ea-95c1-0b96c1eca069.png)

So if the iPhone appears in lsusb and you still can't access the device then something is missing, could be the USB cable,  the usb port connection (USB2.0, 3.0 , 3.1, type-c) incompatible for USBIP or the kernel needs to be recompiled with some weird parameter. The best would be connect the iPhone on a real Linux do `sudo lsmod` and notate the modules needed to use the device.

**Comment by thedozo** [comment]
> Ok, this is what I found. Whatever the method you use to access the USB ports (USBIP, iSCSI, VirtualHere) if your device appears in `lsusb` half the job is done. The other half is the kernel and the distro packages. Recompiling the kernel was not enough until I installed mtp-tools and gmtp. You also will need an Xserver like Vcxsvr and install the gtk2.0 package. I finally managed to connect my Galaxy Tab A through ADB and MTP connections but sure it's slow.
> 
> ![USBIP](https://user-images.githubusercontent.com/599142/81200637-8b33a100-8fc4-11ea-95c1-0b96c1eca069.png)
> 
> So if the iPhone appears in lsusb and you still can't access the device then something is missing, could be the USB cable, the usb port connection (USB2.0, 3.0 , 3.1, type-c) maybe incompatible for USBIP or the kernel needs to be recompiled with some weird option. The best would be connect the iPhone on a real Linux do `sudo lsmod` and notate the modules needed to use the device.

Ok i will check it from Real Linux machine. Btw can you pls tell me about virtual here? Seems you are using it, easier than iSCI or USB/IP method?

**Comment by onomatopellan** [comment]
I found it very easy to use. It's free if you connect 1 device and you use the gui linux version as client.

For the server, just download and run it:
https://www.virtualhere.com/sites/default/files/usbserver/vhusbdwin64.exe

For the client (you need an XServer and gtk2):
```
wget https://www.virtualhere.com/sites/default/files/usbclient/vhuit64
chmod 777 vhuit64
sudo ./vhuit64
```
After that you can right click -> "Specify the hub" and add YOUR_PC_IP:7575
right click on a device -> Use this device
And that's it. You should see the device with `lsusb`.

BTW which model of iPhone and which Real Linux Distro are you running?

**Comment by thedozo** [comment]
> I found it very easy to use. It's free if you connect 1 device and you use the gui linux version as client.
> 
> For the server, just download and run it:
> https://www.virtualhere.com/sites/default/files/usbserver/vhusbdwin64.exe
> 
> For the client (you need an XServer and gtk2):
> 
> ```
> wget https://www.virtualhere.com/sites/default/files/usbclient/vhuit64
> chmod 777 vhuit64
> sudo ./vhuit64
> ```
> 
> After that you can right click -> "Specify the hub" and add YOUR_PC_IP:7575
> right click on a device -> Use this device
> And that's it. You should see the device with `lsusb`.
> 
> BTW which model of iPhone and which Real Linux Distro are you running?

Ok. thanks.
I’m using iPhone 7 plus and Debian as Real Linux.

**Comment by onomatopellan** [comment]
Also please post here the /proc/config.gz file from Real Linux. That file contains the config of the Debian kernel.

**Comment by thedozo** [comment]
@onomatopellan 
Here's the lsmod output after connecting the iphone with Real Linux machine: 
[lsmod.txt](https://github.com/microsoft/WSL/files/4590974/lsmod.txt)

**Comment by thedozo** [comment]
@onomatopellan 
Here's an issue. I have installed virtualhere as you described and everything goes fine. I can attach normal USB devices (pendrive, memory card etc.) with this tool fine. but I can't attach my iPhone with WSL in this method.
![Untitled](https://user-images.githubusercontent.com/55230761/81268213-7bba6380-9069-11ea-9f26-efd96aacf804.png)
what to do now pls?

**Comment by onomatopellan** [comment]
For the config file you can create a text file with `zcat /proc/config.gz > file.txt`

Before continue with VirtualHere you need to update the kernel. Looking at your lsmod.txt the module lacking is ipheth. Without that most tools won't work. Try this kernel
[bzImage.txt](https://github.com/microsoft/WSL/files/4592710/bzImage.txt)
Use wsl.exe --shutdown and update the .wslconfig file to load the kernel. It should include everything needed so you don't have to load more usb modules via script.

After that use the method you can until you see the device listed in `lsusb`. Now tools like ´idevicepair´ or ´ifuse´ shoud work.

**Comment by thedozo** [comment]
@onomatopellan 
BIG THANKS MAN!
After booting from your given kernel, Now I can connect my iPhone and also run CLI tool as well.

1) iPhone is connected and lsusb
![Capture](https://user-images.githubusercontent.com/55230761/81296342-8d186580-9093-11ea-9218-0663318e63f0.PNG)

2) CLI Tool is running and phone is detected
![checkra1n](https://user-images.githubusercontent.com/55230761/81296390-a15c6280-9093-11ea-82f4-dc43f7580096.PNG)

VirtualHere is a life saver for me.

**Comment by thedozo** [comment]
@onomatopellan 
btw what is special about this kernel? does it have all USB modules installed? Can you pls share the config file for this kernel?
So that I can compile later if i ever need to install newer kernel version.

**Comment by onomatopellan** [comment]
Nothing extraordinary. Just configure with `make nmenuconfig` and enable things with "*" instead of "M" so everything will be in the kernel.
[config-wsl.txt](https://github.com/microsoft/WSL/files/4593030/config-wsl.txt)

**Comment by onomatopellan** [comment]
@thedozo Just for security, you should hide you ECID in that last screenshot

**Comment by thedozo** [comment]
> @thedozo Just for security, you should hide you ECID in that last screenshot

Ohhh....ok

**Comment by thedozo** [comment]
@Marietto2008
Hello, finally i have succeed in achieving my goal with VirtualHere, it seesms easier than USB/IP. You can give it a try for your Kinect device if you want to.

**Comment by TheProgramableTurtle** [comment]
Hi, I'm still having this problem, I'm using Virtual Here to connect my iPhone 5S to Ubuntu running the kernel @onomatopellan provided and it shows in `lsusb` but not when running `idevicepair pair`, or any other CLI tool. When running [checkra1n](https://checkra.in/) the device is not detected, but running in CLI mode with `sudo checkra1n -c` with the device already manually placed in DFU mode the tool is able to detect the device, albeit failing to execute successfully but that is to be expected. I understand why checkra1n will not work, but how can I get it to detect the device when not in DFU mode?
