### ISSUE TITLE
wslconfig file is being ignored

### ISSUE THREAD

**Issue by rmsilva1973** [microsoft/WSL#5170]
* Your Windows build number:  **Microsoft Windows [versão 10.0.18363.778]**
* What you're doing and what's happening:  **Compiled the latest wsl2-kernel, copied it to my windows %USERPROFILE% folder and created a .wslconfig file pointing to the freshly compiled image. When opening a new Ubuntu terminal (assuring I killed the previous one with _wsl -t Ubuntu-18.04_ the command _uname -r_ is showing the original version: _4.4.0-18362-Microsoft_**
* What's wrong / what should be happening instead:
**_uname -r_ should show my compiled version (4.19.84-microsoft-standard+) as stated by the _file_ command ran on bzImage:**

![image](https://user-images.githubusercontent.com/28487379/80927441-3d285e80-8d74-11ea-968d-001bf05fc9d9.png)

**I'm attaching launch logs as well as my wslconfig file**

[wsl_lx_logs.zip](https://github.com/microsoft/WSL/files/4572065/wsl_lx_logs.zip)

[wslconfig.txt](https://github.com/microsoft/WSL/files/4572075/wslconfig.txt)

**Comment by onomatopellan** [comment]
>10.0.18363.778
There is no WSL2 in build 18363. You need at least build 19041 (Windows 10 2004) to use the `.wslconfig` file.
