### ISSUE TITLE
WSL Ubuntu 18.04 display freezes when cat file with some binary

### ISSUE THREAD

**Issue by harshana-pickme** [microsoft/WSL#5172]
[freeze.gz](https://github.com/microsoft/WSL/files/4573231/freeze.gz)
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18363.778]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

copy the attached file freeze.gz to another linux machine (mine was a remote ubuntu server). 
unzip the file. 
it is text file with some binary characters. you can run cat freeze | xxd to see what is inside
now ssh to the remote machine from the WSL ubuntu 18.04 terminal
run: cat freeze
This will freeze the terminal.
But if you type exit, you will exit the ssh session and things will start to work normally. 

[freeze.gz](https://github.com/microsoft/WSL/files/4573233/freeze.gz)

**Comment by ywsswy** [comment]
i usually run ssh service in WSL, and use XShell to connect to WSL.

It fails in WSL but not in XShell.

**Comment by onomatopellan** [comment]
Did you try that in the new Windows Terminal?
In any case the upcoming Windows 10 version 2004 (build 19041) has a fix that perfectly fits your problem. #4495

**Comment by ywsswy** [comment]
> Did you try that in the new Windows Terminal?
> In any case the upcoming Windows 10 version 2004 (build 19041) has a fix that perfectly fits your problem. #4495

bro, help me 
https://github.com/microsoft/WSL/issues/5168

**Comment by DHowett-MSFT** [comment]
But also, why would you cat binary files to your terminal?

**Comment by harshana-pickme** [comment]
> But also, why would you cat binary files to your terminal?

Not intentionally doing it. When you cat a text file, it has few random non printable text, terminal hangs. It's really bad experience. All the other terminal programs handle it perfectly.

**Comment by zhouzhendiao** [comment]
I also encountered a similar problem, when `cat file` with Chinese characters
