### ISSUE TITLE
Custom kernel name throwing remote-wsl connection error in VScode

### ISSUE THREAD

**Issue by thedozo** [microsoft/WSL#5173]
Hello,
I'm booting WSL 2 with custom kernel (4.19.104) which has custom name by editing config-wsl while compiling. Custom kernel name is- 4.19.104-microsoft-myname
this is fine, but I'm having connection problem while i'm trying to connect with WSL from vscode (remote-wsl).
`ERRORCONNECR 127.0.0.1:port connection refused`

Also the command `code . ` no longer works in WSL which supposed to open current folder in vscode.

but everything works if I use default kernel name format. How to fix this issue?

**Comment by onomatopellan** [comment]
You need to edit code.sh manually. See:
https://github.com/microsoft/vscode-remote-release/issues/2809

**Comment by thedozo** [comment]
> You need to edit code.sh manually. See:
> [microsoft/vscode-remote-release#2809](https://github.com/microsoft/vscode-remote-release/issues/2809)
> 
> For now the best is creating a new tag in git and compiling the kernel with the original `4.19.104-microsoft-standard` name.

Problem still not solved.
I issue following command by watching your code:
`uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft|([0-9]+).([0-9]+).([0-9]+)-microsoft-standard\dozo?|.*/\1\2\3\4/'
`
but it doesn't solve the issue. How to edit code.sh file? pls elaborate.
My kernel name is: **4.19.104-microsoft-dozo**

**Comment by onomatopellan** [comment]
You need to change code.sh every time you update VSCode so the best way for your would be run
`sed -i 's/standard/dozo/g' "$(which code)"`

**Comment by thedozo** [comment]
> `uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft|([0-9]+).([0-9]+).([0-9]+)-microsoft-dozo|.*/\1\2\3\4/'`
> 
> You need to change code.sh every time you update VSCode so the best way for your case would be running this each time:
> `sed -i 's/standard/dozo/g' "$(which code)"`

ohh...hope they will fix this problem soon. WSL 2 has option to try custom kernel now.
