### ISSUE TITLE
multiple init process starts in WSL 2

### ISSUE THREAD

**Issue by souradeep100** [microsoft/WSL#5176]
ps -ef showing multiple  "/init" process running in WSL 2 ubuntu 18.
If we install docker-ce in Ubuntu (wsl2) and start the docker service then I can see one more extra
init also started.

```
souradeep@LAPTOP-L9AIV34E:~$ ps -eauxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    900   576 ?        Sl   21:33   0:00 /init
root         8  0.0  0.0    892    80 ?        S    21:33   0:00 /init
root      2469  0.5  0.7 1570100 99152 ?       Sl   21:53   0:13  \_ /usr/bin/dockerd -p /var/run/docker.pid
root      2482  1.1  0.4 1498812 55688 ?       Ssl  21:53   0:30      \_ containerd --config /var/run/docker/containerd/containerd.toml --log-level info
root      2798  0.0  0.0    900    88 ?        Ss   22:38   0:00 /init
root      2799  0.0  0.0    900    88 ?        S    22:38   0:00  \_ /init
sourade+  2800  1.1  0.0  22976  4852 pts/1    Ss   22:38   0:00      \_ -bash HOSTTYPE=x86_64 LANG=C.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
sourade+  2827  0.0  0.0  40092  3680 pts/1    R+   22:38   0:00          \_ ps -eauxf LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd
```

**Comment by souradeep100** [comment]
souradeep@LAPTOP-L9AIV34E:~$ uname -a
Linux LAPTOP-L9AIV34E 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Biswa96** [comment]
How did you start the service?

**Comment by souradeep100** [comment]
> How did you start the service?

sudo service docker start
as systemctl does not work in wsl2.

**Comment by souradeep100** [comment]
I know wsl2 MS kernel uses a custom made /init binary, instead of systemd. But still why so many /init.

**Comment by DHowett-MSFT** [comment]
`init` on WSL is used for multiple things. The one that spawns as PID 1 operates as init, and the others serve as the p9 volume server and the interop host and stuff like that. It’s in the same binary, but it has different responsibilities.

This is very similar to `telinit`, which is usually just a hardlink to the `init` binary.

**Comment by benhillis** [comment]
@DHowett-MSFT is correct, we create multiple forks of the init binary to do different things.  This is by design.

**Comment by souradeep100** [comment]
thanks :)

**Comment by daiwei233** [comment]
I found that there are 2 init processes and the cpu usage is always 100%, I don't know why.
Ubuntu version: Ubuntu 20.04.3 LTS
![image](https://user-images.githubusercontent.com/27661838/154252398-1f408396-12fe-4b5d-b243-424ac858dc0c.png)

Can somebody help me ?
