### ISSUE TITLE
can't shutdown anymore WSL2 with windows 10 vers. 19624

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#5180]
On Windows 10 vers. 19624 I can't shutdown wsl anymore because this error 👍
 
λ wsl shutdown
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to talk to init daemon.

**Comment by onomatopellan** [comment]
You need to do `wsl.exe --shutdown` otherwise you are calling the shutdown binary inside your default distro.
