### ISSUE TITLE
WSL GUI SUPPORT

### ISSUE THREAD

**Issue by IAmCodingCoding** [microsoft/WSL#5185]
Can I use WSL to build a application with gui window, as I kown ,for now ,wsl can not support gui application,I want to know  when this feature can be released?

**Comment by blackliner** [comment]
Hi, you need a Xserver, i like X410:
https://x410.dev/cookbook/wsl/setting-up-wsl-for-linux-gui-apps/
https://x410.dev/cookbook/wsl/using-x410-with-wsl2/
