### ISSUE TITLE
WSL1 magically disappears randomly

### ISSUE THREAD

**Issue by GitGangGuy** [microsoft/WSL#5187]
[lxcore_logs.zip](https://github.com/microsoft/WSL/files/4599038/lxcore_logs.zip)
**Please fill out the below information:**
* Your Windows build number:  `Microsoft Windows Version 10.0.18363.778`

* What you're doing and what's happening:
  * Starts computer
  * Opens Windows Terminal
  * Default profile (GUID pointing to `Windows.Terminal.WSL` running Debian) couldn't be loaded
[lxcore_logs.zip](https://github.com/microsoft/WSL/files/4599028/lxcore_logs.zip)
[lxcore_logs.zip](https://github.com/microsoft/WSL/files/4599031/lxcore_logs.zip)

  * Opens Debian app from the Microsoft Store separately
  * Doesn't respond/window stays black
  * Opens CMD with administrator priviledges
  * `wsl` and `wsl --list` don't respond either
  * Disables WSL and VirtualMachinePlatform via dism
  * Restarts PC
  * Re-Enables WSL and VirtualMachinePlatform via dism
  * Restarts PC
  * (Sometimes this works, this time it didn't)
  * \>:(
* What's wrong / what should be happening instead:
WSL apparently disables itself. I'm not really sure what debug information I could provide here, since it's not responding anymore. Last time this happened, disabling and re-enabling WSL/VirtualMachinePlatform worked. I don't understand why WSL is behaving this way. I'm also not able to launch a WSL instance of `vscode `etc.
* LOGS
As requested, I'm attaching the logman log files. However, I have already extracted their contents via tracerpt and censored data I regard as personal.

**Comment by GitGangGuy** [comment]
One restart later everything is working again. What is wrong with WSL?

**Comment by rescenic** [comment]
Try using CCleaner, delete temporary files & old prefetch data, then restart.

**Comment by GitGangGuy** [comment]
Switched to GNU/Linux after finding myself primarily using WSL and other open source software. Closing. Still thumbs up to Microsoft for embracing what they once hated!

**Comment by evanottinger** [comment]
This happened to me today with WSL2.
