### ISSUE TITLE
ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status after upgrading to build 19624

### ISSUE THREAD

**Issue by ryudice** [microsoft/WSL#5192]
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.19624.1000]

* What you're doing and what's happening:  It happens immediate after opening Ubuntu application

* What's wrong / what should be happening instead:
I get message 'An error occurred mounting one of your file systems. Please run 'dmesg' for more details.'. It looks like the windows file system is not mounted, causing other issues.

This is the output of dmesg:

`[    0.266418] rtc_cmos 00:00: setting system clock to 2020-05-09 16:14:59 UTC (1589040899)
[    0.266428] Unstable clock detected, switching default tracing clock to "global"
               If you want to keep using the local clock, then add:
                 "trace_clock=local"
               on the kernel command line
[    0.267596] Freeing unused kernel image memory: 1504K
[    0.307863] Write protecting the kernel read-only data: 20480k
[    0.308455] Freeing unused kernel image memory: 1988K
[    0.308698] Freeing unused kernel image memory: 1260K
[    0.308861] Run /init as init process
[    0.486389] scsi 0:0:0:0: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    0.486766] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    0.487331] sd 0:0:0:0: [sda] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    0.487332] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    0.487400] sd 0:0:0:0: [sda] Write Protect is off
[    0.487401] sd 0:0:0:0: [sda] Mode Sense: 0f 00 00 00
[    0.487528] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    0.487612] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    0.490279] sd 0:0:0:0: [sda] Attached SCSI disk
[    0.508602] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    0.508845] sd 0:0:0:1: Attached scsi generic sg1 type 0
[    0.509252] sd 0:0:0:1: [sdb] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    0.509253] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[    0.509307] sd 0:0:0:1: [sdb] Write Protect is off
[    0.509308] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 00 00
[    0.509457] sd 0:0:0:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    0.518335] hv_pci 6d32dfb4-5a19-4085-b301-36817e518994: PCI VMBus probing: Using version 0x10002
[    0.518609] sd 0:0:0:1: [sdb] Attached SCSI disk
[    0.519055] hv_pci 6d32dfb4-5a19-4085-b301-36817e518994: PCI host bridge to bus b301:00
[    0.519056] pci_bus b301:00: root bus resource [mem 0xc00000000-0xc00002fff window]
[    0.519528] pci b301:00:00.0: [1af4:1049] type 00 class 0x010000
[    0.520685] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    0.520893] pci b301:00:00.0: reg 0x10: [mem 0xc00000000-0xc00000fff 64bit]
[    0.521449] pci b301:00:00.0: reg 0x18: [mem 0xc00001000-0xc00001fff 64bit]
[    0.521982] pci b301:00:00.0: reg 0x20: [mem 0xc00002000-0xc00002fff 64bit]
[    0.525320] pci b301:00:00.0: BAR 0: assigned [mem 0xc00000000-0xc00000fff 64bit]
[    0.525700] pci b301:00:00.0: BAR 2: assigned [mem 0xc00001000-0xc00001fff 64bit]
[    0.526068] pci b301:00:00.0: BAR 4: assigned [mem 0xc00002000-0xc00002fff 64bit]
[    0.533082] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    0.575248] 9pnet_virtio: no channels available for device drvfs
[    0.575377] init: (1) ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status 0x
[    0.575378] 2000
[    0.575381] init: (1) WARNING: Retrying mount
[    0.590629] Adding 4194304k swap on /swap/file.  Priority:-2 extents:2 across:4202496k
[    0.676269] 9pnet_virtio: no channels available for device drvfs
[    0.676373] init: (1) ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status 0x
[    0.676374] 2000
[    0.676377] init: (1) WARNING: Retrying mount
[    0.777262] 9pnet_virtio: no channels available for device drvfs
[    0.777361] init: (1) ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status 0x
[    0.777363] 2000
[    0.777365] init: (1) WARNING: Retrying mount
[    0.878194] 9pnet_virtio: no channels available for device drvfs
[    0.878327] init: (1) ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status 0x
[    0.979276] 9pnet_virtio: no channels available for device drvfs
[    0.982273] 9pnet_virtio: no channels available for device drvfs
[    1.083625] 9pnet_virtio: no channels available for device drvfs
[    1.184912] 9pnet_virtio: no channels available for device drvfs
[    1.257769] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    1.286279] 9pnet_virtio: no channels available for device drvfs
[    1.387502] 9pnet_virtio: no channels available for device drvfs
[    1.388986] 9pnet_virtio: no channels available for device drvfs
[    1.490256] 9pnet_virtio: no channels available for device drvfs
[    1.591641] 9pnet_virtio: no channels available for device drvfs
[    1.695844] 9pnet_virtio: no channels available for device drvfs
[    1.797426] 9pnet_virtio: no channels available for device drvfs
[    1.798238] 9pnet_virtio: no channels available for device drvfs
[    1.902583] 9pnet_virtio: no channels available for device drvfs
[    2.004429] 9pnet_virtio: no channels available for device drvfs
[    2.105687] 9pnet_virtio: no channels available for device drvfs
[    2.208513] 9pnet_virtio: no channels available for device drvfs
[   49.146112] hv_balloon: Max. dynamic memory size: 13056 MB
[   61.488137] WSL2: Performing memory compaction.
[  122.496430] WSL2: Performing memory compaction.
[  183.504213] WSL2: Performing memory compaction.
[  244.512348] WSL2: Performing memory compaction.
[  305.520143] WSL2: Performing memory compaction.
[  366.529437] WSL2: Performing memory compaction.
[  427.541173] WSL2: Performing memory compaction.
[  430.476273] init: (5041) ERROR: CreateProcessParseCommon:871: Failed to translate C:\Program Files\Microsoft VS Code

[  431.643418] init: (5044) ERROR: CreateProcessParseCommon:871: Failed to translate C:\Program Files\Microsoft VS Code

[  431.714430] init: (5047) ERROR: CreateProcessParseCommon:871: Failed to translate c:\Users\ryudice\.vscode\extensions\ms-vscode-remote.remote-wsl-0.42.4

[  431.714484] init: (5047) ERROR: UtilTranslatePathList:2721: Failed to translate c:\Users\ryudice\.vscode\extensions\ms-vscode-remote.remote-wsl-0.42.4

[  431.714527] init: (5047) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin

[ 1440.855953] init: (5054) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin

[ 1440.856001] init: (5054) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (x86)\Common Files\Oracle\Java\javapath

[ 1440.856047] init: (5054) ERROR: UtilTranslatePathList:2721: Failed to translate C:\WINDOWS\system32

[ 1440.856088] init: (5054) ERROR: UtilTranslatePathList:2721: Failed to translate C:\WINDOWS

[ 1440.856127] init: (5054) ERROR: UtilTranslatePathList:2721: Failed to translate C:\WINDOWS\System32\Wbem

[ 1448.575631] WSL2: Performing memory compaction.`

**Comment by rescenic** [comment]
Yeah, why WSL 2 broken in Windows 10 Insider build 10.0.19624.1000. The previous insider build didn't make this error. Ubuntu 20.04 & Alpine WSL got this failed to mount bug.

**Comment by timbophillips** [comment]
I have same issue

**Comment by Dijir** [comment]
Same issue here

**Comment by xiaomudk** [comment]
After wsl start, manually mount can be used temporarily
`mount -t drvfs C: /mnt/c -o metadata`

**Comment by ryudice** [comment]
Alot of things remain broken even after execucting the command. for example vscode doesnt work with the remote WSL addon because the windows executable is not added to the path due to the windows file system not being mounted.

**Comment by xiaomudk** [comment]
> Alot of things remain broken even after execucting the command. for example vscode doesnt work with the remote WSL addon because the windows vscode executable is not added to the path due to the windows file system not being mounted.

I use wsl2 to write python, vscode works fine on my computer, and the remote plugin can also be used normally.

**Comment by ryudice** [comment]
Well, in my case trying to open anything in vscode WSL fails because you have to keep running the mount command on every window the you open.

![image](https://user-images.githubusercontent.com/125211/81945657-9cc80a80-95bb-11ea-91b6-d550ee442401.png)

**Comment by maxshamko** [comment]
Have the same issue after update to 19624.1000. Not try to run vs code with wsl remote yet, but docker in wsl not starting

**Comment by PJCAfonso** [comment]
Have the same issue after last update on 19628.1, neither docker and code can't access to wsl mounts.

**Comment by LiuChangFreeman** [comment]
same issue

**Comment by peterpakos** [comment]
Same issue here, disappointed :/

**Comment by onomatopellan** [comment]
Fix is coming to insiders. https://github.com/microsoft/WSL/issues/4101#issuecomment-628741132

**Comment by chbdetta** [comment]
Same issue happens after the 200508-1414 insider update.

**Comment by metawrap-dev** [comment]
+1 Please fix. It has broken everything I am working on.

**Comment by therealkenc** [comment]
/dupe #4101. Thanks for linking these onomatopellan; appreciated..

**Comment by inthevortex** [comment]
> 
> 
> After wsl start, manually mount can be used temporarily
> `mount -t drvfs C: /mnt/c -o metadata`

Has the fix come yet for automating this?

**Comment by maxshamko** [comment]
After update to 20150 build, problem is gone. Disk mount, vscode with wsl remote starts and docker linux containers starts

**Comment by amirse** [comment]
I'm on 20175 and im getting this error.
just installed ubuntu 20.04, and immediately this happened.

**Comment by bbulkow** [comment]
20175 here, I get the error message, but my drives appear all properly mounted. Looking around to try to find _which_ mount failed. Hoping that since it's a "timeout" message there's been some error handling and the mount succeeded in spite of the error?

**Comment by fippy** [comment]
20190 and getting this error message

**Comment by acepace** [comment]
Build 20221 and getting this bug. One of the drives is indeed not mounted despite the folder name existing.

**Comment by MantasMikal** [comment]
Running `wsl --update` fixed the issue for me

**Comment by maple3142** [comment]
I have similar problem on build 20241 with WSL 1. (WSL 2 don't have this problem)

dmesg output:

```
[    0.015393]  Microsoft 4.4.0-20241.1000-Microsoft 4.4.35
[    0.221148] <3>init: (1) ERROR: UtilCreateProcessAndWait:647: /bin/mount failed with status
[    0.221154] 2000
```

**Comment by AlisterH** [comment]
> I have similar problem on build 20241 with WSL 1. (WSL 2 don't have this problem)
> 
> dmesg output:
> 
> ```
> [    0.015393]  Microsoft 4.4.0-20241.1000-Microsoft 4.4.35
> [    0.221148] <3>init: (1) ERROR: UtilCreateProcessAndWait:647: /bin/mount failed with status
> [    0.221154] 2000
> ```

For the record, I still see this with WSL1, but when I do it seems it just means I need to do a `wsl --shutdown`
