### ISSUE TITLE
Cannot create any user during installation of any distro

### ISSUE THREAD

**Issue by Baroneimen** [microsoft/WSL#5199]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Versione 10.0.18362.778]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
after the installation process when the distro asks for the username i get this error:
![immagine](https://user-images.githubusercontent.com/65166991/81556542-cd752d80-938a-11ea-8ac6-61ca00cf1f67.png)

Unfortunately every other post I've found with this error happened when the user had access to other commands, all I can do here is insert a username

* What's wrong / what should be happening instead:

allow me to create the user

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by rescenic** [comment]
Use CCleaner, check those options: delete temporary data, delete old prefetch data, restart windows. Install again from Microsoft Store.

**Comment by Baroneimen** [comment]
> 
> 
> Use CCleaner, check those options: delete temporary data, delete old prefetch data, restart windows. Install the distro again (Uninstall & Install) from Microsoft Store.

That didn't fix the problem

**Comment by therealkenc** [comment]
This submission could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.
