### ISSUE TITLE
Please identify the terminal emulator with TERM, do not pretend to be xterm.

### ISSUE THREAD

**Issue by floam** [Microsoft/WSL#52]
Presently bash.exe/cmd.exe is not detectable by the usual method - `$TERM` - it misidentifies itself as `xterm`. Please, it behaves very differently from `xterm`, it emulates just an incredibly small amount of what sets xterm apart, has little in common with xterm (compare behavior in `vttest`). It should export something different to the environment for sanity to avoid the certain mess this can spell in the future. 

~~`TERM=linux` is easier to justify.~~ It should set `TERM=interix`, `interix-nti`, or some new suffix for now.

**Comment by kilobyte** [comment]
Fixing this is not that easy: the new setting would need to be added into the terminfo database.  It can be easily done on the local Linux subsystem -- but what if you ssh to a remote host?  Even if the new terminal's definition was added to the likes of Debian or Fedora unstable today, it'd take a long time to get to stable releases.  And that's assuming distro maintainers doing their job -- Solaris *still* doesn't understand TERM="linux" despite that being only 25 years old.

So there are two ways:
* pragmatic: pick something defined in ncurses-term or ncurses-base
* idealistic: use a new name and request its inclusion in terminfo databases

I guess it'd be best to go with a hybrid: masquerade as something for now but submit a new definition so in a year or two you'll be able to switch (no one cares about Solaris anymore...).

And identifying yourself as "xterm" is about the worst choice: xterm is an extremely feature-rich/bloated terminal, current Windows Console is not even adequate for the moment (which is a separate issue).  Let's pick a simpler definition for now...

**Comment by jokeyrhyme** [comment]
Maybe some of this will be addressed when/if they bring some of the Windows 10 improvements to the CMD.exe console across to WSL + Ubuntu?

- https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/

**Comment by floam** [comment]
I also see there is `TERM=interix` and `interix-nti`! How about that! And it's just about everywhere! It's the champion at curses's box characters with raster fonts. It's otherwise a bit evident that it probably worked better on the old cons. 

![TERM=interix-nti screenshot](https://files.gitter.im/fish-shell/fish-shell/h45D/Screenshot-2016-04-11-at-6.54.03-AM.png)

It seems to me that could be what this identifies as - and work on modernizing the termcaps.

**Comment by orangeful** [comment]
As far as I've tried I prefer pcansi over interix.  Anyway, not xterm.

**Comment by bitcrazed** [comment]
Thanks for the feedback and suggestions - we'll take this into consideration for our future planning.

**Comment by chrisbra** [comment]
any update here?

**Comment by Qix-** [comment]
To be honest it should just define its own Termcap definition file. They're well defined, and they're there for this exact purpose. Plus, Microsoft would be able to define whatever escapes would suit their existing code bases, and terminfo-aware applications wouldn't have to change a thing.

Side note: If your application isn't terminfo aware, it should be. Assuming the xterm escapes will get you by is a hack and an unsafe assumption.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. Console is now MUCH more XTERM compatible
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
