### ISSUE TITLE
wsl.exe, bash.exe automation broken

### ISSUE THREAD

**Issue by sashafirsov** [microsoft/WSL#5201]
* Windows build number:  Microsoft Windows [Version 10.0.19041.208]
* What you're doing and what's happening: 
Trying to run Linux command from C executable via WSL.exe or BASH.exe.
```cplusplus
int main(int argc, char* argv[], char* envp[])
{    
    return system("C:\\Windows\\System32\\wsl.exe pwd");
    //return system("C:\\Windows\\System32\\cmd.exe /C C:\\Windows\\System32\\bash.exe pwd");
}
```
In any combination (directly or via cmd) the result is same:
> 'C:\Windows\System32\wsl.exe' is not recognized as an internal or external command,
operable program or batch file.

Attempts with executing wsl.exe or bash.exe via `ShellExecuteEx` or `CreateProcess` resulting in similar error.

* What's wrong / what should be happening instead:

output should be same as when running `wsl pwd`. In my case 
> /mnt/c/Users/suns/source/repos/wsl-call/Release

Any another executable like `ipconfig.exe` producing proper output.

PS. The initial idea was to enable linux commands by creation of executable "proxies" which will invoke wsl command. I.e.` git.exe` would call `wsl.exe git` with bypassed cli parameters. The list of executables would be taken out of linux path and saved in folder available over windows path.

**Comment by DHowett-MSFT** [comment]
You are compiling for `x86` or `Win32`, which means you are getting “system folder redirection.”

You’ll want to compile for `x64` or disable system folder redirection using the Wow64DisableWow64FsRedirection API.

**Comment by DHowett-MSFT** [comment]
(Because of system folder redirection, 32-bit processes automatically (and silently) convert all references to system32 to “syswow64”.)

**Comment by DHowett-MSFT** [comment]
@sashafirsov so, did that help?

**Comment by sashafirsov** [comment]
@DHowett-MSFT , thanks for the tip, it works. 
I would keep the `Wow64DisableWow64FsRedirection` call in source but would stick to x64 build. Will share git repo once have something useful.

**Comment by sashafirsov** [comment]
Here you go: WSL available from windows cli: https://github.com/sashafirsov/wsl-call

![image](https://user-images.githubusercontent.com/3978089/82110305-21b54000-96f2-11ea-8654-e01a1b61c879.png)
