### ISSUE TITLE
[WSL1] Zsh  command  fork  with wrong Nice value (4294967291)

### ISSUE THREAD

**Issue by Po-wei** [microsoft/WSL#5202]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18363.815]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
1. using zsh
2. (fork a command):  sleep 80 &
3. htop show wrong NICE value.

* What's wrong / what should be happening instead:
![image](https://user-images.githubusercontent.com/17596021/81610194-f814b580-938d-11ea-9425-080348cb586b.png)
There Nice is setted to 4294967291.
According to wiki, Nice should be -20 to +19 where -20 is highest, 0 default and +19 is lowest.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/Po-wei/b963bb7fc21a5faa69cc7508b4e1b42f

Bash works as expected

**Comment by therealkenc** [comment]
Fun catch. Was able to reproduce here, WSL1 19628:

![image](https://user-images.githubusercontent.com/7049700/82294240-adcd9e80-9962-11ea-8681-60ca40bcd5a6.png)

That first `4294967291` is in the `/proc/.../stat` string is the value you are seeing in `htop`. Mildly interesting there's no dupe I can recall: enough people use `zsh` and enough people use `htop`. 

Gold star to the person who figures out what `zsh` does differently than `bash` that gums up the works in WSL. Experimentally, if you suspend the `sleep` ctrl-z, and then `bg` (more or less the same thing) then the value is populated correctly. So it is probably job control related, as opposed to actually having to do with niceness. Or something.
