### ISSUE TITLE
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: /c/Program\: not found

### ISSUE THREAD

**Issue by alexiswl** [microsoft/WSL#5206]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.19041.208]
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

xdg-open fails because the `browser` variable is incorrectly quoted.

* What's wrong / what should be happening instead:

BROWSER variable has spaces in them and this is not correctly handled by the `xdg-open` binary.
i.e
```
export BROWSER='/c/Program Files/Mozilla Firefox/firefox.exe'
```

With the following changes I have been able to resolve the issue.  

```
 899             BROWSER=x-www-browser:firefox:iceweasel:seamonkey:mozilla:epiphany:konqueror:chromium:chromium-browser:google-chrome:$BROWSER
```
to
```
 899             BROWSER=x-www-browser:firefox:iceweasel:seamonkey:mozilla:epiphany:konqueror:chromium:chromium-browser:google-chrome:"$BROWSER"
```

```
 850         else
 851             $browser "$url"
 852         fi
```

to

```
 850         else
 851             "$browser" "$url"
 852         fi
```

**Comment by DHowett-MSFT** [comment]
This sounds like a worthwhile bug to file on the upstream project that owns `xdg-open`, because there’s nothing that WSL can do to fix its mishandling of paths with spaces in.

**Comment by benhillis** [comment]
@DHowett-MSFT is correct, this is not a WSL bug.
