### ISSUE TITLE
Bad variable name in WSL

### ISSUE THREAD

**Issue by mituso89** [microsoft/WSL#5208]
![image](https://user-images.githubusercontent.com/29556841/81827483-fc45fc00-9562-11ea-8219-3d1f3a406f87.png)

I'm using wsl2 with build 19624. I cab't commit code by git. it is work for me in case of ignore eslint to recheck before commit code

Please help me any solution

**Comment by Biswa96** [comment]
Create a `/etc/wsl.conf` file, add these lines:

```ini
[interop]
appendWindowsPath=false
```

Lear more from here https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/

**Comment by mituso89** [comment]
Thanks Biswa96. But it's not work for me

**Comment by Biswa96** [comment]
Try to stop the WSL2 VM with `wsl.exe --shutdown` then restart the WSL2 distribution.

**Comment by mituso89** [comment]
Sorry it's done after I restart my laptop and shutdown wsl. Thank u so much

**Comment by mituso89** [comment]
Hi Biswa96
In case of add 
```
[interop]
appendWindowsPath=false 
```
into /etc/wsl.conf. I get an issued. I can't run visual studio code insider wsl2. If I ignore wsl.conf it's is work

**Comment by benhillis** [comment]
This is something in Linux usermode not correctly handling paths with spaces.  If you want to run vscode with this setting disabled you can create an alias in your .bashrc with the full path.
