### ISSUE TITLE
Failed to make pptp config-requests 

### ISSUE THREAD

**Issue by LiuChangFreeman** [microsoft/WSL#5213]
* I'm using WSL2 ver 19619.1000

* I tried to connect a vpn server using `pptpsetup`, but the result is **LCP: timeout sending Config-Requests**. This happens only in WSL. I tried this on VMs and they all worked well.
```
pptpsetup --create  pptp  --server anyserver  --username myaccount  --password mypassword --start
Using interface ppp0
Connect: ppp0 <--> /dev/pts/2
LCP: timeout sending Config-Requests
Connection terminated.
Modem hangup
```

* I searched on some websites and they told me this should be caused by lack of some kernel modules.

* I used tcp-dump and tracked the information below:
![TIM截图20200515210819](https://user-images.githubusercontent.com/20047907/82054225-2b8a7380-96f1-11ea-82e2-06251de4d00f.png)

**Comment by therealkenc** [comment]
> I searched on some websites and they told me this should be caused by lack of some kernel modules.

That's a good guess. I don't have a PPP "anyserver" handy to test, but the PPP kconfigs were enabled circa the WSL Linux 4.19.52 release.

![image](https://user-images.githubusercontent.com/7049700/117382734-06f45200-ae94-11eb-869b-24c91eff1617.png)

If you are still on Insiders, please try your scenario with a recent kernel. If the problem persists, maybe it is something other than a missing kconfig.
