### ISSUE TITLE
WSL 2 not working with Acrylic DNS

### ISSUE THREAD

**Issue by lucaros97** [microsoft/WSL#5214]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

* Your Windows build number:  19041.264

* What you're doing and what's happening:  After installing Acrylic DNS service the wsl would not work anymore.
This is what you after start Acrylic DNS and opening WSL terminal (You need to restart the system)
![image](https://user-images.githubusercontent.com/8333004/82067907-9a57d480-96d1-11ea-8109-007eb51b9eda.png)

* What's wrong / what should be happening instead:
WSL and terminal shoul works normally

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs]:
[lxcore.zip](https://github.com/microsoft/WSL/files/4635343/lxcore.zip)

**Comment by kdbcinco** [comment]
This seems to be an issue with Acryclic DNS binding to port 53 according to some other issues here. First encountered this after switch Docker Desktop's backend to WSL 2. Disabled Acryclic DNS and was able to start Docker Desktop with WSL 2 properly.

**Comment by jamieburchell** [comment]
https://github.com/microsoft/WSL/issues/4364#issuecomment-866700145

**Comment by r0bbie** [comment]
I experienced this very recently (and so was watching this issue hoping for a fix..). So it seems to remain an issue.

**Comment by jamieburchell** [comment]
> I experienced this very recently (and so was watching this issue hoping for a fix..). So it seems to remain an issue.

Did you try [the workaround](https://github.com/microsoft/WSL/issues/4364#issuecomment-866700145)

**Comment by princeo** [comment]
This stopped docker desktop from starting. I simply stopped the Acrylic DNs Proxy. Restarted wsl and docker started working, once they were up and running, I restarted  acrylic DNS and it worked fine.
