### ISSUE TITLE
Can't find camera device 

### ISSUE THREAD

**Issue by Mugen-adm** [microsoft/WSL#5219]
Unable to access the device camera via the wsl, is it not possible or am I doing some mistakes ??
I am using OpenCV - cv2 for videocapture using `cv2.VideoCapture(-1)`
The error I get is `[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (874) open VIDEOIO(V4L2): can't find camera device`

**Comment by therealkenc** [comment]
No [`/dev/video`](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_v4l.cpp#L868) in WSL (1 or 2). Doesn't seem to be a good existing landing zone for the ask (couldn't find one anyway). Ref #2195 which is not quite related, but is lower hanging fruit as exposing devices in WSL2 goes.

**Comment by Mugen-adm** [comment]
Sorry for the format, didn't checked it before posting.
Anyway thanks for the answer.
