### ISSUE TITLE
rsync daemon unable to bind in WSL2

### ISSUE THREAD

**Issue by srana2000** [microsoft/WSL#5222]
I upgraded my Windows 10 Pro to latest 2004 (Microsoft Windows [Version 10.0.19041.264]).
I then upgraded my WSL 1 Ubuntu 18.04 to WSL 2. 

Now when I start `rsync` it exits with following log

```
2020/05/17 16:01:38 [11] rsyncd version 3.1.2 starting, listening on port 8730
2020/05/17 16:01:48 [26] rsyncd version 3.1.2 starting, listening on port 8730
2020/05/17 16:01:48 [26] bind() failed: Address already in use (address-family 2)
2020/05/17 16:01:48 [26] unable to bind any inbound sockets on port 8730
2020/05/17 16:01:48 [26] rsync error: error in socket IO (code 10) at socket.c(555) [Receiver=3.1.2]

```
Checking I found that wslhost.exe is binding to the port. 
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-Process -Id (Get-NetTCPConnection -LocalPort 8730).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
     95       6      948       3060       0.02   1104   2 wslhost

```

It was working perfectly since past two years and after upgrading to WSL2 this problem started coming. If I reboot the machine wslhost is not using that port. I tried with different port and it is same. How can I fix it.

**Comment by onomatopellan** [comment]
Did you try `rsync --address 0.0.0.0`?

**Comment by srana2000** [comment]
> Did you try `rsync --address 0.0.0.0`?
When rsync is started as Service I never specified IP address. It uses the machine IP.

**Comment by onomatopellan** [comment]
I think as a service it loads config from `/etc/default/rsync`

You can try editing the file modifying the line:
`RSYNC_OPTS='--address=0.0.0.0'`

**Comment by johtop** [comment]
> > Did you try `rsync --address 0.0.0.0`?
> > When rsync is started as Service I never specified IP address. It uses the machine IP.

srana2000, did you solve the problem?
