### ISSUE TITLE
ArchWSL emacs gui

### ISSUE THREAD

**Issue by WingDust** [microsoft/WSL#5225]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) Microsoft Windows [版本 10.0.19041.264] 

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.) i want to use emacs gui version in ArchWSL , I check the # 4106
so i write `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0` in .bashrc
and VcXrsv 
![image](https://user-images.githubusercontent.com/45911286/82168958-9656cd00-98f2-11ea-8d57-ac7c9ca11198.png)

i run `emacs` the **emacs** gui window in a flash and get this 
```
(emacs:1192): Gtk-WARNING **: 10:32:01.105: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/24x24/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/24x24/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Fatal error 6: Aborted
Backtrace:
emacs[0x50fbcf]
emacs[0x4f5175]
emacs[0x50dfcf]
emacs[0x50e20e]
emacs[0x50e2f9]
/usr/lib/libpthread.so.0(+0x14960)[0x7f27d30f0960]
/usr/lib/libc.so.6(gsignal+0x145)[0x7f27d2e382e5]
/usr/lib/libc.so.6(abort+0x127)[0x7f27d2e21853]
/usr/lib/libglib-2.0.so.0(+0x1c062)[0x7f27d42d7062]
/usr/lib/libglib-2.0.so.0(g_assertion_message_error+0xb8)[0x7f27d4304178]
/usr/lib/libgtk-3.so.0(+0x2c6169)[0x7f27d4b6b169]
/usr/lib/libgtk-3.so.0(+0x2c65c2)[0x7f27d4b6b5c2]
/usr/lib/libgtk-3.so.0(+0x2c66d9)[0x7f27d4b6b6d9]
/usr/lib/libgtk-3.so.0(+0x2c6990)[0x7f27d4b6b990]
/usr/lib/libgtk-3.so.0(+0x2af341)[0x7f27d4b54341]
/usr/lib/libgtk-3.so.0(+0x34b773)[0x7f27d4bf0773]
/usr/lib/libgtk-3.so.0(+0x3514b1)[0x7f27d4bf64b1]
/usr/lib/libgtk-3.so.0(+0x2aace3)[0x7f27d4b4fce3]
/usr/lib/libgtk-3.so.0(+0x1ef183)[0x7f27d4a94183]
/usr/lib/libgtk-3.so.0(+0x1ee16e)[0x7f27d4a9316e]
/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa5)[0x7f27d4a93275]
/usr/lib/libgtk-3.so.0(+0x3a4adc)[0x7f27d4c49adc]
/usr/lib/libgtk-3.so.0(+0x34b773)[0x7f27d4bf0773]
/usr/lib/libgtk-3.so.0(+0x3514b1)[0x7f27d4bf64b1]
/usr/lib/libgtk-3.so.0(+0x39e6a3)[0x7f27d4c436a3]
/usr/lib/libgtk-3.so.0(+0x1ef183)[0x7f27d4a94183]
/usr/lib/libgtk-3.so.0(+0x1ee16e)[0x7f27d4a9316e]
/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa5)[0x7f27d4a93275]
/usr/lib/libgtk-3.so.0(+0x34b773)[0x7f27d4bf0773]
/usr/lib/libgtk-3.so.0(+0x3514b1)[0x7f27d4bf64b1]
/usr/lib/libgtk-3.so.0(+0x3952f3)[0x7f27d4c3a2f3]
/usr/lib/libgtk-3.so.0(+0x1ef183)[0x7f27d4a94183]
/usr/lib/libgtk-3.so.0(+0x1ee16e)[0x7f27d4a9316e]
/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa5)[0x7f27d4a93275]
/usr/lib/libgtk-3.so.0(+0x1ef183)[0x7f27d4a94183]
/usr/lib/libgtk-3.so.0(+0x1ee16e)[0x7f27d4a9316e]
/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height+0x81)[0x7f27d4a934b1]
/usr/lib/libgtk-3.so.0(+0x1eec3e)[0x7f27d4a93c3e]
/usr/lib/libgtk-3.so.0(+0x1ee16e)[0x7f27d4a9316e]
/usr/lib/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xa5)[0x7f27d4a93275]
/usr/lib/libgtk-3.so.0(+0x8716c)[0x7f27d492c16c]
...
Aborted
```
And I already try ` sudo pacman -S pixbuf2` it still this way

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by WingDust** [comment]
microsoft/WSL#4106

**Comment by therealkenc** [comment]
> #4106

_Probably_ not in this case; `emacs-gtk` wouldn't have made it to the first warning, nvm the hard error. That native "Native gl" checkbox in VcXsrv is backwards; that might be a place to start (but probably isn't it).

Works here on Focal. You'll get better eyeballs forums related to the products involved (mostly Arch forum I suppose). That error "Unrecognized image file format" is not WSL actionable. Probably something (image related) not installed/configured in your userspace but won't speculate wut.

![image](https://user-images.githubusercontent.com/7049700/82272117-8d83ec80-992e-11ea-94df-385d92186880.png)

**Comment by WingDust** [comment]
I don't why but i reboot 
`emacs ` and `startxfce4` can show graphic interface
