### ISSUE TITLE
When multiple windows accounts use Linux on WSL, do they share the same ISO image?

### ISSUE THREAD

**Issue by plastikfan** [microsoft/WSL#5226]
This question is related to this issue [Please add multi-user support for wsl](https://github.com/microsoft/WSL/issues/5151), but on further consideration, it looks look they are similar but not addressing the same problem, so I thought it would be best to raise a separate issue.

Please could somebody answer me this question, as confusion about the distro still reigns. I need to make this very clear. There are 2 elements to this, particularly with the respect to separate disk space usage. The 2 parts I mean are the linux iso location and the linux install location. I am still not clear on this, so I need this to be clarified.

When the first windows account downloads the linux distro as part of their installation, where does this iso image get stored? Is it in a user specific (eg ~/Some-Location/) location or a system wide location (eg C:\Program Files\WindowsApps)?

Clearly the installation extracts files from the iso location to the install location where-ever that is, to be invoked for the runtime. I think that other people having been requesting sharing a single installation with multiple windows accounts, and this is fine. This is not so important to me, but I think I have not made it clear enough (when commenting on the issue referenced above) the difference between the 2 (iso location and install location).

The answer to this next point depends on the answer to where the iso image is stored. If the iso image is stored in user specific location, then I guess, this is the end of my query, because the second windows account will not have access to the first windows account application installs. However, if the iso is stored in a system location, then ....

When the second windows account goes to install Linux, (let's assume they both want to use Ubuntu), is it able to use the previously downloaded iso image, or will another iso image be downloaded just for them; so in this case, the system is storing 2 identical images? So what happens here?

I don't need to use WSL in a multi person environment (notice I didn't say multi-user), so I don't have the requirement that a particular Linux install needs to be shared at any one instance in time. I already assumed that separate windows accounts would have their own installation. I just want to know about the original iso image location. I hope this is much clearer now and I look forward to the hearing right answer :) (I really do hope the iso image isn't duplicated).

I should also add, if the iso images are duplicated, then the feature request would be to enable sharing of these images amongst multiple WSL windows accounts, to save disk space and install time (why waster time redownloading an image the system already has).

**Comment by therealkenc** [comment]
> When the first windows account downloads the linux distro as part of their installation, where does this iso image get stored?

Same place as all Store apps (say Candy Crush Saga). [It isn't an iso image, its a tarball embedded in an appx details [here](https://github.com/microsoft/WSL-DistroLauncher), but beside point.]

> Is it in a user specific (eg ~/Some-Location/) location or a system wide location (eg C:\Program Files\WindowsApps)?

The former. [As an initial matter you don't have permissions to scribble `C:\Program Files`, nor were you prompted for escalation rights to a that directory.]

> When the second windows account goes to install Linux, (let's assume they both want to use Ubuntu), is it able to use the previously downloaded iso image

It will use [Windows Update Delivery Optimization](https://support.microsoft.com/en-ca/help/4468254/windows-update-delivery-optimization-faq) if it can (AFAIK).

> the feature request would be to enable sharing of these images amongst multiple WSL windows accounts

There are no WSL Windows accounts, just Windows accounts. [Across all your devices, not just the one you are sitting at.]

Your disk space optimization suggestion would (hypothetically but not seriously) be a [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) ask, see [feedback hub](https://support.microsoft.com/en-ca/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). The Store app distribution mechanism is not unique to WSL and is not WSL actionable.

> why waster time redownloading an image the system already has

Mostly stems from the fact it isn't "the system's" image. It's yours, until you decide to delete it.
