### ISSUE TITLE
Can not start bash.exe - network name not available

### ISSUE THREAD

**Issue by legout** [microsoft/WSL#5227]
Hello,

I have installed WSL following this introduction: 
https://docs.microsoft.com/de-de/windows/wsl/install-win10

However, when I try to run `bash.exe` or `wsl.exe` in powershell, it gives me the following error (It is in german):

> Der angegebene Netzwerkname ist nicht mehr verfügbar.

This means something like "The provided network name is not available anymore."

I have already disabled and reanabled WSL with:
`dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux`
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux`

Thanks and regards,
legout

**Comment by rescenic** [comment]
Have you installed Linux WSL via Microsoft Store? Install Ubuntu, for example.
