### ISSUE TITLE
gem install fails with invalid argument sendto(2)

### ISSUE THREAD

**Issue by shadycuz** [microsoft/WSL#5230]
* Your Windows build number: 10.0.18363.836

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

On Ubuntu 18.04.4 LTS after installing ruby with apt-get. 

```
gem install bundle
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - sendto(2) for "1.1.1.1" port 53

```

I'm not really sure if this is a problem with WSL or gem but I thought I might post in both places.

**Comment by therealkenc** [comment]
Can't repro here on WSL1. No strace was provided.

![image](https://user-images.githubusercontent.com/7049700/82366746-8bba3780-99c7-11ea-8c04-ae5e0c20220b.png)

**Comment by shadycuz** [comment]
@therealkenc I'll provide a trace and version output similar to yours tomorrow. Thanks.

**Comment by drewkett** [comment]
Just ran into the same bug

Here's an strace

[strace.log](https://github.com/microsoft/WSL/files/4664824/strace.log)

**Comment by therealkenc** [comment]
Thanks. Doing an `strace -f` per the template gets the thread detail, but it does have the `EINVAL`. Here's the sequence for posterity:
```
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 7
fcntl(7, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
fstat(7, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
getrandom("\x70", 1, GRND_NONBLOCK)     = 1
getrandom("\x1a\x10\x84\x10", 4, GRND_NONBLOCK) = 4
getsockname(7, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
bind(7, {sa_family=AF_INET, sin_port=htons(5146), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
getrandom("\xe9\x13\x3f\xc8", 4, GRND_NONBLOCK) = 4
clock_gettime(CLOCK_MONOTONIC, {tv_sec=247151, tv_nsec=32641400}) = 0
getsockname(7, {sa_family=AF_INET, sin_port=htons(5146), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
sendto(7, "\23\351\1\0\0\1\0\0\0\0\0\0\t_rubygems\4_tcp\10ruby"..., 45, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.86.1")}, 16) = -1 EINVAL (Invalid argument)
close(7)                                = 0
writev(2, [{iov_base="ERROR:  While executing gem ... "..., iov_len=107}, {iov_base="\n", iov_len=1}], 2ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - sendto(2) for "192.168.86.1" port 53
) = 108
```

**Comment by shadycuz** [comment]
I forgot, but can provide if still needed.

**Comment by therealkenc** [comment]
Attaching a threaded `strace` (better still a gist) is probably worthwhile for completeness. But ultimately this one suffers from me not being able to reproduce locally (that's not on you) and an absence of me2s from the gallery shedding further light.

I did notice one thing on the necro I didn't notice the first go-around: your `1.1.1.1` DNS. That puts this issue in #4285 territory. If nothing else, it is a glaring variable versus my trivially working run. Try walking back all things (especially third-party things) that motivated you arriving at `1.1.1.1` as the destination of choice, and then work forward from there. Occam says that's it.

**Comment by shadycuz** [comment]
@therealkenc @drewkett 

I was connected to a work VPN and didn't realize it. It still shouldn't have caused an issue, because the vpn is only redirecting traffic from a private ip range but it does affect things apparently. 

When I'm not connected I get a file permission error because I'm not sudo. So it looks like all is good. 

Thanks

**Comment by mcleary** [comment]
Exactly the same problem for me. Disconnected from the vpn and it works
