### ISSUE TITLE
Cannot use WSL.exe to invoke Linux commands in PowerShell

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/WSL#5232]
@rickstrahl reported this issue in a Twitter conversation with @sundhaug92 and myself, ending here: https://twitter.com/richturn_ms/status/1262885317826113536 

Running Win10 x64 with Ubuntu (WSL2) distro with fortune-mod, cowsay, and lolcat installed.

In PowerShell Core x64, invoke simple Linux command, like fortune:
```bash
wsl fortune
You will be attacked by a beast who has the body of a wolf, the tail of
a lion, and the face of Donald Duck.
```
__Yay!__

Now let's make a cow say it and make it colorful
```bash 
wsl fortune | cowsay | lolcat
lolcat: The term 'lolcat' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
__SAYWHATNOW?__

Lolcat is definitely installed:

```bash
wsl echo hello | lolcat
lolcat: The term 'lolcat' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

No! I **KNOW** lolcat is intalled ...
```bash
wsl lolcat
Hello
Hello
^C
```

Perhaps PowerShell is parsing the command-line. Let's quote it so it's just a string.

```bash
wsl "fortune | cowsay | lolcat"
/bin/bash: fortune | cowsay | lolcat: command not found
```
__SRSLY?__

Worked example:
![image](https://user-images.githubusercontent.com/961950/82388015-545e8180-99ed-11ea-8ec9-4595aa47c85a.png)

So, how DOES one invoke wsl.exe passing an arbitrary command-line script?

**Comment by sundhaug92** [comment]
Just figured it out!
`wsl echo hello` works, so one potential next step is to escape |.
According to [this](https://www.robvanderwoude.com/escapechars.php), ^ escapes | : `wsl fortune ^| cowsay ^| lolcat`

**Comment by bitcrazed** [comment]
Thanks for the suggestion @sundhaug92, alas, no cigar

![image](https://user-images.githubusercontent.com/961950/82389729-bcaf6200-99f1-11ea-9a6a-9ff9167df65b.png)

**Comment by sundhaug92** [comment]
@bitcrazed I've updated the comment, I forgot we were talking pscore rather than cmd.exe

**Comment by sundhaug92** [comment]
Because wsl.exe treats each argv as a separate argument (or command), you can't use "". Because you can't use "" you have to find another way to tell the host-shell (cmd, ps, ...) if any to ignore things like `|`.

When using C#, you can then get away with something like
```csharp
var pi = new ProcessStartInfo();
pi.FileName = @"C:\Windows\sys" + (IntPtr.Size == 4 ? "native" : "tem32") + @"\wsl.exe"; // Solution for starting 64-bit WSL from a 32-bit process
pi.Arguments = "fortune | cowsay | lolcat";
var p = Process.Start(pi);
p.WaitForExit();
```

**Comment by DHowett** [comment]
Piping is a shell feature. You need to pipe in the syntax of the shell you’re invoking, and invoke the shell explicitly to do that. 

```
wsl "sh -c 'fortune | nyancat | dogmoof'"
```

**Comment by therealkenc** [comment]
This is #3284.

With `powershell.exe`: 

![image](https://user-images.githubusercontent.com/7049700/82398047-bd9ebe80-9a06-11ea-8728-34f6570cae6c.png)

But on planet sanity, Duntin's answer is better (same as [message](https://github.com/microsoft/WSL/issues/3284#issuecomment-532811786)). 

Those '`|`' characters aren't arguments to a command, they are shell script operators... operators which have arbitrary meaning (if not in practice then in principle). A powershell '`|`' is unrelated to a Bourne shell '`|`', notwithstanding the coincidental character choice. Maybe the _script_ you are trying to run uses other shell syntax like '`&&`' or '`;`', which might (or might not) be related to a how a powershell interpreter sees the world. Maybe your Linux interpreter of choice is `elisp` or `tcl` or `perl` or `python` (or `pwsh`!) instead of a Borne shell like `bash`. However you roll, call your script against the interpreter. Or if you do the thing a lot, write a `colorfulcowfortune.sh` and put a shebang at the top.

**Comment by RickStrahl** [comment]
Followed this, but my original question was trying to run multiple commands which works with `bash -c`  but does not work with `wsl '<cmd>;<cmd'`:

![image](https://user-images.githubusercontent.com/1374013/82410613-f5f4cb80-9a0b-11ea-9a37-4d25d0f595ed.png)

Notice the error is 'No such file or directory' - it looks like `wsl`  is looking specifically for an executable not a command line perhaps?

No look at the craziness of stuff that works and what doesn't:

![image](https://user-images.githubusercontent.com/1374013/82411027-ac58b080-9a0c-11ea-9930-da43fba0e4ab.png)

This works, which is sort of the same thing I'm doing - change path, then open:
```ps
wsl  cd /mnt/c/projects/Test/jekyll/help; code .
```

But... although it opens, when it does the path change is lost. It opens in my host folder (ie. ~).

The other commands likely are not working for the same reason - the commands appear to not execute in the same shell context.

**Comment by sundhaug92** [comment]
@RickStrahl Try the variant from @DHowett : `wsl "sh -c 'cd /mnt/c/projects/Test/jekyll/help; bundle exec jekyll serve;'"`. Also: That extranous plain `cd` changes directory to ~.

**Comment by therealkenc** [comment]
>  with bash -c but does not work with wsl `'<cmd>;<cmd>'`

Running `wsl.exe "<cmd>;<cmd>"` is the same as (inside Ubuntu) `/bin/bash -c "'<cmd>;<cmd>'"`. Which is something doable albeit unusual.

![image](https://user-images.githubusercontent.com/7049700/82416103-5d237780-9a2e-11ea-8aab-4ff168287d7e.png)

&nbsp;
> wsl  cd /mnt/c/projects/Test/jekyll/help; code .

Here `/bin/bash` was told to change directory and exit. The the semicolon ('`;`') was interpreted by `powershell`, which then fired up `code` in your current directory ('`.`'). Code is in your Windows `$env:path` and powershell had no trouble finding it.

> wsl  "cd /mnt/c/projects/Test/jekyll/help; code ."

In this one `/bin/bash` is trying to run a program called "`cd /mnt/c/projects/Test/jekyll/help; code .`" which doesn't exist.

> wsl  cd /mnt/c/projects/Test/jekyll/help; cd; bundle exec jekyll serve;

In this one powershell couldn't find `bundle` in your `$env:path` (unlike `code` previously, where it did).

Your scenario would be something like:
```
wsl.exe sh -c "cd /mnt/c/projects/Test/jekyll/help; bundle exec jekyll serve"
```

**Comment by brianhatchet** [comment]
Thanks @therealkenc. Perfect answer. I completely forgot about invoking sh. Duh.
