### ISSUE TITLE
[WSL2] Issues with running LXD (system containers)

### ISSUE THREAD

**Issue by stilren** [microsoft/WSL#5234]
This is basically a follow up from: https://github.com/microsoft/WSL/issues/4158

Using WSL2 and ubuntu 16.04

After doing sudo lxd init and accepting all defaults I run in to the issue
```
$ sudo service lxd start
Starting Container hypervisor based on LXC: ip6tables: No chain/target/match by that name.
Failed to setup lxd-bridge.
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
ip6tables: Bad rule (does a matching rule exist in that chain?).
ip6tables: Bad rule (does a matching rule exist in that chain?).
ip6tables: Bad rule (does a matching rule exist in that chain?).
ip6tables: Bad rule (does a matching rule exist in that chain?).
ip6tables: Bad rule (does a matching rule exist in that chain?).
ip6tables: No chain/target/match by that name.
```

Even if I uninstall by `sudo apt remove --purge lxd`, then install LXD again with `sudo apt install lxd` I will run in to this issue. Running init results in the following error:

```
$ sudo lxd init
error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
```

Notes:
This guy (https://wsl.dev/wsl2-lxd-funtoo/) seems to have the lxd network interface already, dont know what is up with that?
I plan to follow @simos post after this is cleared https://blog.simos.info/how-to-run-lxd-containers-in-wsl2/

**Comment by stilren** [comment]
My guess is that some lxd config is not removed when uninstalling

**Comment by sirredbeard** [comment]
Can you reproduce this on Ubuntu 18.04 or 20.04? LXD in 16.04 is ancient. 

Here is a video of Nuno's LXD workflow, BTW: https://www.youtube.com/watch?v=DULAocJuo_g

**Comment by stilren** [comment]
@sirredbeard I have it working on Ubuntu 18.04!

**Comment by therealkenc** [comment]
Closing remarks (mostly to self) there's probably "something" to the OP. I mean, Xenial is "ancient", but it also isn't like `lxd` _didn't_ work back in the day. That said, the probability of anyone drilling down hovers around zero in this issue context. I've seen some (utterly unproven) evidence something strange is going on with ipv6 that has the potential to trip upstream (userspace) assumptions when manipulating `iptables`, but finger pointing (scare quote) "WSL" versus chalking tag linux-behavior is not trivial ref #767.
