### ISSUE TITLE
Suggest for french customers

### ISSUE THREAD

**Issue by pedefe** [microsoft/WSL#5235]
Hello,

In the page "https://docs.microsoft.com/fr-fr/windows/wsl/" (main page given by Google) where you explain what is WSL, there is no arguments (in french language) to explain the interest to run such a linux distribution on a Windows PC. If I need to develop Linux  application, I perfer to use a standard and official distribution instead a Linux sub Windows. Or you can explain It is with same performance and compatibility. Give exemples about the interest of such  'cohabitation'.
Best regards.

**Comment by rescenic** [comment]
Well, maybe it goes down to your own preferences. I am very grateful that Windows make WSL. I can develop and utilize Linux apps without cygwin and msys2.

![wsl](https://i.ibb.co/NWxXswt/20-05-2020-551-18-00-49.png)
How cool is that? When I need GUI, I can just set up X11 display server via SSH.

Of course, I can use VMware or VirtualBox. But it comes down to your own preferences.
