### ISSUE TITLE
SetCaseSensitiveInfo cannot be set for RAM disks.

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/WSL#5236]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt): `Microsoft Windows [Version 10.0.19041.264]`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.):
1. Open ADMINISTRATOR terminal, e.g. `cmd.exe`
   1. optional dependency: [Install chocolatey](https://chocolatey.org/docs/installation#installing-chocolatey)
2. Install imdisk, e.g.: `choco install imdisk`
3. Generate RAM disk, from ADMINISTRATOR terminal: `imdisk -a -m K: -s 5GB -p "/fs:ntfs /q /y"`
4. Change folder to CaseSensitive: `fsutil.exe file SetCaseSensitiveInfo K:\experiments enable`
5. Output:
```
Error:  The directory is not a subdirectory of the root directory.
A local NTFS volume is required for this operation.
```

* What's wrong / what should be happening instead:
  * Command executes and returnes success because the volume is NTFS.

**Comment by 0xbadfca11** [comment]
Imdisks show unstable behavior even when not related to WSL, eg CHKDSK.
![image](https://user-images.githubusercontent.com/7390559/82454876-442dcb80-9aed-11ea-860c-2c7aa3a7f6a4.png)
Other virtual disk software, such as OSFMount, doesn't have this problem, so I think Imdisk is wrong.

**Comment by n3rd4i** [comment]
I've recreated the RAMDISK with OSFMount, it seems that chkdsk behaves the same:

1. Command: `OSFMount.com -a -t vm -m T: -o format:ntfs -s 5G`
2. Spoiler: 
```
The specified object was not found.
```

3. Full output:
```
C:\>chkdsk T:
The type of the file system is NTFS.
The specified object was not found.


WARNING!  /F parameter not specified.
Running CHKDSK in read-only mode.

Stage 1: Examining basic file system structure ...
  256 file records processed.
File verification completed.
 Phase duration (File record verification): 3.19 milliseconds.
  0 large file records processed.
```

OSFMount (ver. 3.0.1006)
```
C:\>osfmount --version
PassMark OSFMount Command Line Interface.
Version V3.0 (Build 1006) - (Compiled May  6 2020)
```

**Comment by therealkenc** [comment]
> fsutil.exe file SetCaseSensitiveInfo K:\experiments enable

Various third-party filesystem drivers might or might not support the functionality for that to work. Mostly not.
