### ISSUE TITLE
Windows Firewall block WSL2 accessing to Windows service 

### ISSUE THREAD

**Issue by eromoe** [microsoft/WSL#5237]
Test code:
```
winip=$(ip route | grep default | awk '{print $3}')
ping $winip
```
result:
![image](https://user-images.githubusercontent.com/3938751/82461188-b651e080-9aec-11ea-82e2-79fc61bee691.png)

Actually I want to use a proxy service host on windows .  I saw many people success with above command, why I faied ? Or wsl2 go into new problem ?

**Comment by therealkenc** [comment]
There isn't enough to go on here to guess why you can't ping your default route on (if I am interpreting correctly) WSL1.

**Comment by eromoe** [comment]
I can provide what you need if you tell me how to do , I have no clue to investigate it  .

**Comment by eromoe** [comment]
I found it due to windows firewall.  Add exclude rule of wsl.exe in firewall didn't work,  I saw several cases include me had to shutdown firewall to make wsl able to access windows service . 

Since this is common usage of wsl2, people shouldn't need shutdown firewall . It is system/wsl resposibility to make wsl2 bypass firewall at default .
