### ISSUE TITLE
getcpu systemcall not implemented correctly

### ISSUE THREAD

**Issue by Chronial** [microsoft/WSL#5239]
Windows build number:  10.0.18363.778

The [`getcpu`](http://man7.org/linux/man-pages/man2/getcpu.2.html) systemcall always reports that the process is running on core 0.

*Minimal Example:*
```c++
#include <iostream>
#include <sys/syscall.h>
#include <thread>

int main(){
    for(int i=0; i < 100; i++){
        std::thread([]{
            std::cout << sched_getcpu();
        }).detach();
    }
    return 0;
}
```

Running `g++ main.cpp -lpthread && ./a.out` always prints a row of `0`. On a Linux it prints numbers between 0 and the number of cores of the cpu.

This is probably the cause of #3294

**Comment by therealkenc** [comment]
That's a great analysis and repro. Yes almost certainly cause of #3294. Better on WSL2.

![image](https://user-images.githubusercontent.com/7049700/82486795-4151bd00-9a92-11ea-8fcd-195a328d8b60.png)

**Comment by Chronial** [comment]
Are WSL bugs not beeing fixed any more? Is there an official announcement about this?
