### ISSUE TITLE
Unix socket binding - Errno::EADDRINUSE

### ISSUE THREAD

**Issue by kingp0dd** [microsoft/WSL#5243]
Originally found in Puma:
https://github.com/puma/puma/issues/1521

Offending code in Ruby:
https://bugs.ruby-lang.org/issues/16277

```
require 'socket'

path = File.expand_path('listen.sock')
backlog = 5

s = UNIXServer.new(path)
if backlog
  s.listen backlog
else
  s.listen
end

File.delete(path) if File.exists?(path)
```

Listening twice does not throw `Errno::EADDRINUSE` in Linux but it does in WSL.

**Comment by therealkenc** [comment]
Spiritually #2915 (TCP over there).
