### ISSUE TITLE
After installing Ubuntu18.04, you are prompted for a username, which is invalid

### ISSUE THREAD

**Issue by CasterWx** [microsoft/WSL#5245]
Microsoft Windows [Version10.0.19628.1]

WSL 2

After installing Ubuntu18.04, you are prompted for a username, which is invalid。

```
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: antzuhl
Enter new UNIX username: abcsdasd
Enter new UNIX username: wangssds
Enter new UNIX username: fdfdas
```

**Comment by onomatopellan** [comment]
Make sure you have this option in Settings -> Storage pointing to the C: system drive. You may need to uninstall the distro and install again.

![Annotation 2020-05-21 132709](https://user-images.githubusercontent.com/599142/82554851-fb1a5d80-9b66-11ea-8e2d-eefc6ff3b985.png)

**Comment by CasterWx** [comment]
There are these options.

It was unloaded and reloaded many times， There is no problem with the WSL. However, after converting to WSL2, problems arise.

```
wsl --set-version Ubuntu-18.04 2
```

**Comment by onomatopellan** [comment]
Is that Windows Chinese version? You have same problem as #4900 

Try this from cmd:
`wsl.exe -d Ubuntu-18.04 -u root`

and from bash:
`adduser antzuhl`

**Comment by CasterWx** [comment]
It worked, thanks！！

**Comment by therealkenc** [comment]
People seeing this might file an issue with the disto maintainer similar #3273 ([message](https://github.com/microsoft/WSL/issues/3273#issuecomment-403962073)).

**Comment by naren3k** [comment]
hi, I can not follow, how was this fixed ? I am getting same issues with all distros WSL2 on Azure VM. Content is saved to C:  where I have full access to.    
`wsl.exe -d Ubuntu-18.04 -u root `
even this didn't work. Whats the work around ? , thanks

**Comment by onomatopellan** [comment]
@naren3k What's the Windows version in the Azure VM? What's your output for `wsl.exe -l -v` and `wsl.exe --status` ?

**Comment by 40rn05lyv** [comment]
I had the same problem on my laptop. Looks like it was blocked by McAfee, configured with company-wide antivirus policy.
There's a message about that in McAfee Event Log:
![image](https://user-images.githubusercontent.com/1200215/172845179-a5448807-474b-487b-ba50-d242a8b43505.png)
So, need to contact guys who are in charge of that.

**Comment by addliam** [comment]
> Is that Windows Chinese version? You have same problem as #4900
> 
> Try this from cmd: `wsl.exe -d Ubuntu-18.04 -u root`
> 
> and from bash: `adduser antzuhl` `usermod -aG adm,cdrom,sudo,dip,plugdev antzuhl`

This worked for me, but for some reason with Ubuntu-20.04.6 i wasn't able to do that. Even `wsl --list` did not show anything. Im on win10 and Ubuntu-18.04 fits good.
