### ISSUE TITLE
wslpath doesn't work for \\wsl$\ folders

### ISSUE THREAD

**Issue by isiah-lloyd** [microsoft/WSL#5250]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) 
Microsoft Windows [Version 10.0.19041.264]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```
isiah@LAPTOP-DC4OKU1J:~$ wslpath \\wsl$\ubuntu\home\isiah\website
wslpath: \wsl$ubuntuhomeisiahwebsite
```
* What's wrong / what should be happening instead:
I would expect that it would get translated to /home/isiah/website

**Comment by onomatopellan** [comment]
Works with `/` instead of `\`. Also remember using single quotes.
```
$ wslpath '//wsl$/Ubuntu2004/home'
/home
```

**Comment by isiah-lloyd** [comment]
> Works with `/` instead of `\`. Also remember to use single quotes.
> 
> ```
> $ wslpath '//wsl$/Ubuntu2004/home'
> /home
> ```

I'm trying to create a "Open in WSL VS Code" option when I right click a folder.  This is the command I have setup in my registry:
"wsl.exe code `wslpath '%V'" 

It works when I do it from a folder not in the wsl file system, like Documents. Not sure if I'll be able to get the slashes to go the other way.

**Comment by onomatopellan** [comment]
Try with `wslpath '\\wsl$\Ubuntu2004\home' | tr '\\' /`

**Comment by therealkenc** [comment]
Or escape the backslashes. The ones in the OP were eaten by `bash` before they ever got to `wslpath`.

![image](https://user-images.githubusercontent.com/7049700/82700415-ff0bb580-9c22-11ea-9077-d092960bb607.png)
