### ISSUE TITLE
no installed distributions

### ISSUE THREAD

**Issue by Dreamer451** [microsoft/WSL#5252]
* Your Windows build number:  2004 (19041.26.4)

* What you're doing and what's happening: 
<ol>
<li>installed WSL using directions at https://docs.microsoft.com/en-us/windows/wsl/install-win10</li>
<li>restarted the computer</li>
<li>installed Kali Linux from the Windows Store</li>
<li>restarted the computer</li>
<li>ran <code>bash.exe</code> at a Powershell command line (running as administrator).</li>
</ol>

* got the message:
<quote>Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore</quote>

[log files.zip](https://github.com/microsoft/WSL/files/4670238/log.files.zip)

**Comment by rescenic** [comment]
bash.exe ? how about just type: wsl.exe

**Comment by Dreamer451** [comment]
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

**Comment by dglinder** [comment]
I'm getting the same error message.  I have installed a few Linux images (Ubuntu 20.04 LTS, Debian, etc) but all get this error when starting:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

I'm running Windows 10 2004 (OS Build 19041.264), and Hyper-V is installed, and virtualization is enabled in the BIOS (VMWare Workstation works with Hyper-V now after the latest OS update).

**Comment by rescenic** [comment]
> I'm getting the same error message. I have installed a few Linux images (Ubuntu 20.04 LTS, Debian, etc) but all get this error when starting:
> 
> ```
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80370102
> Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
> ```
> 
> Running "wsl -l -v" from an administrator or "normal" power-shell command line reports the same:
> 
> ```
> PS C:\> wsl -l -v
> Windows Subsystem for Linux has no installed distributions.
> Distributions can be installed by visiting the Microsoft Store:
> https://aka.ms/wslstore
> PS C:\>
> ```
> 
> The Add/Remove menu AND the Windows Store both a number of Ubuntu and other WSL apps installed.
> 
> This machine is running Windows 10 2004 (OS Build 19041.264), and Hyper-V is installed, and virtualization is enabled in the BIOS (VMWare Workstation works with Hyper-V now after the latest OS update).

Have you enabled Virtual Machine Platform in Windows feature?

**Comment by dglinder** [comment]
Yes, I've enabled "Virtual Machine Platform", Windows Subsystem for Linux", and everything under the "Hyper-V" section.

![image](https://user-images.githubusercontent.com/1124371/83582942-91a43280-a508-11ea-9142-c51d04b7b2d8.png)

**Comment by rescenic** [comment]
@dglinder Try Network Reset in Windows Setting, and restart your computer.

**Comment by What-is-water93** [comment]
Same issue (wsl command outputs no installed distributions, even though I installed a couple ones, and can even start and use them).
I tried network reset & restart and still didnt detect the distribution, before and after I reinstalled Ubuntu.

**Comment by dglinder** [comment]
@rescenic I did the Network Reset then rebooted - same issue.

**Comment by FireMasterK** [comment]
I'm facing the same issue, WSL 1 works fine but WSL 2 doesn't work for some reason.
![image](https://user-images.githubusercontent.com/20838718/83791559-8fcca180-a6b7-11ea-8ae0-2caaabd473ea.png)
![image](https://user-images.githubusercontent.com/20838718/83791694-b5f24180-a6b7-11ea-82b4-4c0f47a19d7a.png)
![image](https://user-images.githubusercontent.com/20838718/83791820-dd490e80-a6b7-11ea-8047-84773e7bff88.png)

**Comment by What-is-water93** [comment]
I found out what my issue is: Opening the powershell as admin and using the WSL command. If you open it as regular user, it works like it should - most likely because my admin account didnt have any WSL distributions.

**Comment by Dreamer451** [comment]
It works now that I have reinstalled Kali--at least as a regular user. As and admin I get the message: 
<quote>Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore</quote>

**Comment by adspon** [comment]
> ny WSL distri

This solved my problem! :) tnx man

**Comment by V4A001** [comment]
Same issue here. Weird and user unfriendly.

**Comment by BnH2081** [comment]
> @rescenic I did the Network Reset then rebooted - same issue.

hi, can i ask you help me if you fixed this priiblem?

**Comment by edisonvillela** [comment]
Great, thanks!

**Comment by mbartelsm** [comment]
For people who still have this problem regardless of the proposed solution.

After installing Ubuntu (or whatever distro you get from the Ms Store), you need to run the app first at least once before you can invoke it from the command line.

**Comment by craiglandis** [comment]
> For people who still have this problem regardless of the proposed solution.
> 
> After installing Ubuntu (or whatever distro you get from the Ms Store), you need to run the app first at least once before you can invoke it from the command line.
> 
> So,
> 
> 1. Install steps detailed in the ms website
> 2. Search and run "Ubuntu" from your start menu
> 3. Follow the instructions
> 4. Now `wsl` can find the distro

This solved it for me also, but how can that step be scripted?

**Comment by majaa** [comment]
> I found out what my issue is: Opening the powershell as admin and using the WSL command. If you open it as regular user, it works like it should - most likely because my admin account didnt have any WSL distributions.

Totally makes sense! :) Thanks man for saving some time here!
