### ISSUE TITLE
Active directory and/or Group policy not compatible with WSL 1/2 in 2004 release

### ISSUE THREAD

**Issue by BeErikk** [microsoft/WSL#5259]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.264]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

PS C:\WINDOWS\system32> wsl --set-default-version 2
WSL 2 måste uppdateras enligt kernelkomponenten. Mer information finns på https://aka.ms/wsl2kernel
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME            STATE           VERSION
  Ubuntu-18.04    Running         1
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Det går inte att hitta sökvägen. '(unable to find path)'
* What's wrong / what should be happening instead:
The Ubuntu-18.04 instance is a WSL 1 installation from Windows 1909 and installed via the server method outside of the system disk on its own disk. It has been working perfectly for a year as far as I can tell and it is working now in Windows 2004. Is the upgrade procedure using a hardcoded path? Is there a way to specify an alternative path?
* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by onomatopellan** [comment]
See #5075

**Comment by BeErikk** [comment]
> See #5075

Thanks, if  I understand it right you're suggesting I should uninstall hyper-v and then reinstall it? Well, it sounds a bit dangerous but I'll try it. I just upgraded to 2004 and I used hyper-v in 1909 and it worked without issue and it's working now as well.

**Comment by BeErikk** [comment]
Just FYI
`PS L:\ubuntu> wsl.exe --export Ubuntu-18.04 ./Ubuntu-18.04.tar
Det går inte att hitta filen.`

**Comment by onomatopellan** [comment]
Can you install a new distro from the Store? Just for testing.

**Comment by BeErikk** [comment]
Still haven't tried the hyper-v thing but a good idea to try another distro. I'll do it now.

**Comment by BeErikk** [comment]
Crap 
```
C:\Windows\System32>ubuntu2004.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 Det gÕr inte att hitta filen.

Press any key to continue...
```

**Comment by onomatopellan** [comment]
That look bad. Plenty of threads with that error with most weird solutions like in #4618.
It's a different error because you can't even export. Do you use any AV or Firewall different from Windows Security?

**Comment by BeErikk** [comment]
Yes, I have a working Symantec which I managed to bring över from 1909. I hate to touch it. I usually do a clean Windows install just to avoid these things, but I didn't want the work this time. I'm reinstalling hyper-v now and I'll try again.

**Comment by BeErikk** [comment]
Nopp, reinstall hyper-v didn't change anything other than clean up my virtual networks.

**Comment by onomatopellan** [comment]
Some people fixed that bug with:

open Turn Features On or Off
untick Windows Subsystem For Linux
reboot
tick Windows Subsystem For Linux
reboot

**Comment by BeErikk** [comment]
OK, tried that but it didn't work, gives `WslRegisterDistribution failed with error: 0x80070002`. 

My old 1909 WSL 1 instance Ubuntu 18.04 survived though and is still working.

**Comment by Bengrunt** [comment]
Hi there, 

I've got the exact same problem. Any luck solving this?

Sticking to WSL 1 for now but I'd really like to get my distros on WSL 2 since it's supposed to perform better.

Thanks.

**Comment by BeErikk** [comment]
> Hi there,
> 
> I've got the exact same problem. Any luck solving this?
> 
> Sticking to WSL 1 for now but I'd really like to get my distros on WSL 2 since it's supposed to perform better.
> 
> Thanks.

No, I eventually gave up on my upgraded Windows and did a clean install. In the clean Windows (2004 en_US) I directly **tested to install WSL 2 which succeeded without issues**. This was done using a dummy install-account. I then joined my **AD network** and logged in as myself and tried to install a new WSL 2 instance which resulted in:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 Det gÕr inte att hitta filen.
```
Logging in on my previous dummy install-account and WSL 2 has stopped to work with a similar message. So what does this mean? I think one or more of the following causes:

> WSL 2 is not fully compatible with Active Directory services
> WSL 2 is depended on telemetry disabled by AD policy rules

Swedish MUI was installed by the dummy install-account and worked with WSL 2, no antivirus solution was installed, no hardware driver changes, system SSD formatted, no desktop applications or store apps installs other than Chrome Edge and Google Chrome.

**Comment by BeErikk** [comment]
Confirmed after a second clean install of Windows 2004. I had a hope that the WSL 2 upgrade package was prerelease and introduced telemetry dependencies. Unfortunately this isn't the case. Even if I avoid installing the WSL 2 upgrade, I cannot create new WSL 1 or WSL 2 instances as an AD user. However, now I can continue to use WSL 1 with my local dummy install-account even after joining the computer to AD.

**Comment by BeErikk** [comment]
For completeness and how I got a semifunctional Ubuntu 20.04 WSL 1 environment with the server method:

1. reverted back to Windows 1903
2. downloaded [http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz](url)
3. run `wsl.exe --import Ubuntu-20.04 ubuntu-20.04-server-cloudimg-amd64-wsl.rootfs.tar.gz E:\Linux\Ubuntu-20.04`
4. wsl.exe adduser
5. installed Ubuntu-20.04 from store and run it once
6. upgrade Windows to 2004

Still cannot install any distros in Windows 2004 and now I hit the `clock_nanosleep` issue.

**Comment by BeErikk** [comment]
Made a network trace as requested at [https://github.com/microsoft/WSL/issues/5107](url)
new logfiles for trying to install Ubuntu 18.04 in the network trace:
[failed.install.Ubuntu.18.04.zip](https://github.com/microsoft/WSL/files/4747386/failed.install.Ubuntu.18.04.zip)
