### ISSUE TITLE
File system performance is wildly different between mount points

### ISSUE THREAD

**Issue by devnoot** [microsoft/WSL#5262]
**Windows & WSL versions**
```
Microsoft Windows [Version 10.0.19041.264]
```

```
C:\Users\noot>wsl --list
Windows Subsystem for Linux Distributions:
Debian (Default)
```

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I am noticing that file system performance is wildly different between directories. Is this normal?

```
$ sudo dd if=/dev/zero of=/c/Users/noot/tmp/tmp bs=1M count=5000
5000+0 records in
5000+0 records out
5242880000 bytes (5.2 GB, 4.9 GiB) copied, 17.918 s, 293 MB/s
```

```
$ sudo dd if=/dev/zero of=/mnt/tmp/test bs=1M count=5000
5000+0 records in
5000+0 records out
5242880000 bytes (5.2 GB, 4.9 GiB) copied, 2.8185 s, 1.9 GB/s
```

I would expect performance to be closer. This is causing a lot of general slowness with WSL2.

**Comment by DHowett** [comment]
This sounds like https://github.com/microsoft/WSL/issues/4197, which is the master issue tracking performance differences in the Windows filesystem integration for WSL2.

Of note particular note, however: you have specified what sort of filesystem `/mnt/tmp` is. It does make it difficult to have an equitable comparison :)

**Comment by devnoot** [comment]
Ah, I didn't even realize c was symlinked in /mnt

This is almost certainly #4197 , I can contribute there
