### ISSUE TITLE
syslog-ng is hanging with Ubuntu 20.04 WSL1

### ISSUE THREAD

**Issue by perceival** [microsoft/WSL#5264]
* Your Windows build number:  10.0.19041.264

* What you're doing and what's happening:  
sudo apt install syslog-ng
sudo syslog-ng
or
sudo service start syslog-ng

lxcore_kernel.etl: 
https://mega.nz/file/4gkl1JSC#vCFE2IX8AkVfXxChsmeNqnp9UGo8PImIo3ZpPZiD_20

* What's wrong / what should be happening instead:
With the same configuration Ubuntu 18.04 is succesfully starting syslog-ng however in case of 20.04 syslog never starts picking up log entries also bash is not returning to the prompt

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by onomatopellan** [comment]
Ubuntu 20.04 + build 19041 WSL1 = problems with libc
workaround in https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931

**Comment by therealkenc** [comment]
We can call this /dupe #4898 although there's no `strace(1)` log here. Seems like there ought be some kind of `EINVAL` indication contrast a hang. But doesn't repro on WSL1 19631 (which has the #4898 fix) so fair enough.

![image](https://user-images.githubusercontent.com/7049700/82762148-45dce500-9db4-11ea-8869-835e91ea2abf.png)
