### ISSUE TITLE
Ubuntu re-installs after removing then install openssh-server

### ISSUE THREAD

**Issue by maxima2k** [microsoft/WSL#5266]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number: Microsoft Windows [Version 10.0.18363.836]

* What you're doing and what's happening:  
1) Open ubuntu app
2) After initial ubuntu installation completes, remove then install openssh-server
3) reboot the Windows 10 Machine.
4) Open ubuntu app

Ubuntu runs through an initial install process.

* What's wrong / what should be happening instead:
Ubuntu should not be re-installing again after rebooting.  My complete ubuntu environment gets wiped out and I have to re-install everything all over again.  Because invariably Windows 10 has to be re-booted.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
This submission cannot be reproduced locally. It is not possible to determine why the Ubuntu installer ran again after you rebooted, but whatever it was, it was unrelated to anything that happened inside Ubuntu at step 2. This submission was left open for a bit on the chance some "I had to install Ubuntu twice" me2s might be forthcoming, but that never materialized.

**Comment by maxima2k** [comment]
Sorry I thought I had followed up with diagnosis and remediation.  I have determined it was a PC BIOS issue that was resolved by updating the BIOS from the PC Manufacturer.
