### ISSUE TITLE
WSL causing my internet to not work

### ISSUE THREAD

**Issue by animeshxd** [microsoft/WSL#5267]
![Annotation 2020-05-25 184133](https://user-images.githubusercontent.com/47624427/82815913-ca645c00-9eb7-11ea-890f-20a969a61a05.png)
![Annotation 2020-05-25 184240](https://user-images.githubusercontent.com/47624427/82815917-cc2e1f80-9eb7-11ea-8c5d-d9f7b3899c91.png)
![Annotation 2020-05-25 184317](https://user-images.githubusercontent.com/47624427/82815920-cd5f4c80-9eb7-11ea-8455-4063f3f895d1.png)

**Comment by rescenic** [comment]
run cmd as admin: `netsh winsock reset`
restart computer
or
Network reset in Windows Setting, then restart.
