### ISSUE TITLE
What is `wsl$`? Where are the syntax rules to parse it correctly?

### ISSUE THREAD

**Issue by EricGT** [microsoft/WSL#5268]
This is simply a few related questions, but was only given the choice of bug or feature request.

---

1. What is `wsl$` when used to access a distro in WSL2 from Windows 10, e.g. via explorer.exe with `\\wsl$\Ubuntu-18.04\`

In checking [Naming conventions in Active Directory for computers, domains, sites, and OUs](https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and) one might think it is a `NetBIOS computer name` but after reading [Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#namespaces) one might think it is something else.

2. Knowing what it is, what are the syntax rules to parse it correctly?

3. Are there any shell commands to help sort out the differences? I did use [WinObj](https://docs.microsoft.com/en-us/sysinternals/downloads/winobj) but that didn't identify `wsl$`.

**Comment by therealkenc** [comment]
> was only given the choice of bug or feature request

That's because this is a WSL bug tracker.

> one might think it is something else

It's a [UNC path](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/62e862f4-2a51-452e-8eeb-dc4ff5ee33cc?redirectedfrom=MSDN). [One that happens to have a `$` in the hostname component.]
