### ISSUE TITLE
WSLENV will not translate ProgramFiles(x86) variable from Windows to Linux

### ISSUE THREAD

**Issue by tis-rpage** [microsoft/WSL#5269]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.836]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Testing WSLENV with various settings only translate the variable PROGRAMFILES, and the other two variables, all caps and camelcase, don’t convert.
`WSLENV=PROGRAMFILES/p:PROGRAMFILES(X86)/p:ProgramFiles(x86)/p`
`WSLENV=PROGRAMFILES(X86)/p:ProgramFiles(x86)/p:PROGRAMFILES/p`

* What's wrong / what should be happening instead:
The environment variable `ProgramFiles(x86)` should be set in the environ of the linux processes.

I’m wondering if this is technically possible with the current WSLENV implementation, as the characters ‘(‘ and ‘)’ are valid portable characters per the opengroup standard, and that most shells restrict names to being alphanumerics and the underscore character. Running the following proves that environ can contain an environment variable with parentheses, and bash will permit it:
`env -i ‘ProgramFiles(x86)=value’ bash`

**Comment by pagerc** [comment]
I believe this is a configuration issue with my wsltty invocation conflicting with WSLENV. As such, I think this should be closed unless others have similar issues.

This is my wsltty Target:
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ env TERM=mintty /bin/bash -l`

That said, it would be useful to have a WSLENV extension for rewriting variable names, e.g. WSLENV=PROGRAMFILES/p:ProgramFiles>PROGRAMFILES/p:PROGRAMFILES(X86)>PROGRAMFILESX86/p:ProgramFiles(x86)>PROGRAMFILESX86/p

**Comment by tis-rpage** [comment]
I believe this is a configuration issue with my wsltty invocation conflicting with WSLENV. As such, I think this should be closed unless others have similar issues.

This is my wsltty Target:
%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~ env TERM=mintty /bin/bash -l

That said, it would be useful to have a WSLENV extension for rewriting variable names, e.g. WSLENV=PROGRAMFILES/p:ProgramFiles>PROGRAMFILES/p:PROGRAMFILES(X86)>PROGRAMFILESX86/p:ProgramFiles(x86)>PROGRAMFILESX86/p
