### ISSUE TITLE
command piping through new bash

### ISSUE THREAD

**Issue by g1lf0yle** [microsoft/WSL#5270]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

* Microsoft Windows [Version 10.0.18362.535]

* What you're doing and what's happening:  bash | whoami

* What's wrong / what should be happening instead: After piping the whoami commands aren't working anymore. whoami, ls -la, uname -r, ... and with the command pwd bash throws you back to the cmd
* These commands should normally execute as usual, but they doesnt
![bug bash](https://user-images.githubusercontent.com/65606973/82863482-94a88d00-9f22-11ea-8400-3dc2ccfec631.png)

**Comment by rescenic** [comment]
`wsl whoami`
It will be processed in default distro. 
Except you set the additional parameter:
`wsl -d CentOS whoami`

if you run bash | whoami, windows will use the first bash in your system path folder location.

**Comment by g1lf0yle** [comment]
Thanks!

**Comment by rescenic** [comment]
Or you can use ` before using pipe.
![pipe](https://i.ibb.co/mBSwTSJ/26-05-2020-624-14-18-20.png)

**Comment by therealkenc** [comment]
Or:
```
PS C:\> wsl.exe -d distro sh -c "fortune | cowsay | lolcat"
```
