### ISSUE TITLE
Background GUI process can not receive mouse event

### ISSUE THREAD

**Issue by luochen1990** [microsoft/WSL#5273]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

> Microsoft Windows [版本 10.0.19631.1]

And I'm using WSL2 Ubuntu 20.04, with VcXsrv 1.20.8.1 (7 Apr 2020)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1. run `xeyes` or some other GUI application.
2. move mouse, and confirm that the xeyes works well (the eyes follows our mouse)
3. press `ctrl+z` to switch it to background
4. move mouse, and confirm that the xeyes not works  (the eyes doesn't follow our mouse)

* What's wrong / what should be happening instead:

The xeyes works (the eyes follows our mouse) when the process is running in background.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

https://gist.github.com/luochen1990/cb704cf46b524c33ca4c66d3b49e5ec5

**Comment by DHowett** [comment]
<kbd>Ctrl+Z</kbd> _suspends_ a process. You need to run `bg` to resume it in the background. I did not see this in your reproduction steps.
