### ISSUE TITLE
Can't run Firefox in WSL 2

### ISSUE THREAD

**Issue by toml12953** [microsoft/WSL#5276]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed.

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".\\

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19631.1]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
At a bash prompt I type firefox
* What's wrong / what should be happening instead:
Nothing happens. The system doesn't come back to the prompt and firefox doesn't start. 
I have 

export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0

in /etc/bash.bashrc and was able to run gedit before I installed firefox. After I installed firefox, the same problem now occurs with any graphical program: no return to prompt and no execution of program.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/83095332-f0c0fd80-a057-11ea-9dac-f65a06913d70.png)

**Comment by inidona** [comment]
maybe you have to allow the xserver networking port 6000 in your windows firewall. this was my issue with an company laptop.
