### ISSUE TITLE
Can't update wsl2 Error : 0x80041002

### ISSUE THREAD

**Issue by Dodotry** [microsoft/WSL#5278]
按照升级指引操作，转换的时候报0x80041002错误，无法转换。

OS Version:10.0.19041 N/A Build 19041 / 19041.264
subsystem：Ubuntu-20.04

Dodotry C:\..\system32 ❯❯❯ wsl --set-version Ubuntu-20.04 2
正在进行转换，这可能需要几分钟时间...
有关与 WSL 2 的主要区别的信息，请访问 https://aka.ms/wsl2
错误: 0x80041002

**Comment by animeshxd** [comment]
you can only Set your distribution version to WSL 1 or WSL 2 
`wsl --set-version <distribution name> <versionNumber>` 
 like `wsl --set-version Ubuntu 2`  
version 1 and 2 is only available.
[visit here for more details](https://docs.microsoft.com/en-in/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2)
![Annotation 2020-05-29 132139](https://user-images.githubusercontent.com/47624427/83235368-61c6f900-a1af-11ea-9193-81001a6d16f7.png)
![Annotation 2020-05-29 131814](https://user-images.githubusercontent.com/47624427/83235147-0f85d800-a1af-11ea-957d-b7de9b258fa7.png)

![Annotation 2020-05-29 132846](https://user-images.githubusercontent.com/47624427/83235997-6c35c280-a1b0-11ea-949b-5a875b3d37a3.png)
![Annotation 2020-05-29 132947](https://user-images.githubusercontent.com/47624427/83236063-88396400-a1b0-11ea-9d60-0bdbde83e9ed.png)


you can't update the version of your ubuntu using wsl command.
update it from Microsoft Store.

**Comment by Dodotry** [comment]
> you can only Set your distribution version to WSL 1 or WSL 2
> `wsl --set-version <distribution name> <versionNumber>`
> like `wsl --set-version Ubuntu 2`
> version 1 and 2 is only available.
> [visit here for more details](https://docs.microsoft.com/en-in/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2)
> ![Annotation 2020-05-29 132139](https://user-images.githubusercontent.com/47624427/83235368-61c6f900-a1af-11ea-9193-81001a6d16f7.png)
> ![Annotation 2020-05-29 131814](https://user-images.githubusercontent.com/47624427/83235147-0f85d800-a1af-11ea-957d-b7de9b258fa7.png)
> 
> ![Annotation 2020-05-29 132846](https://user-images.githubusercontent.com/47624427/83235997-6c35c280-a1b0-11ea-949b-5a875b3d37a3.png)
> ![Annotation 2020-05-29 132947](https://user-images.githubusercontent.com/47624427/83236063-88396400-a1b0-11ea-9d60-0bdbde83e9ed.png)
> 
> you can't update the version of your ubuntu using wsl command.
> update it from Microsoft Store.


I tried again, but the conversion still failed.
![image](https://user-images.githubusercontent.com/48266156/83236916-e3765100-a1c6-11ea-90d2-323a833dd6f6.png)

**Comment by animeshxd** [comment]
https://docs.microsoft.com/en-in/windows/wsl/install-win10
See this

**Comment by BlueNoob** [comment]
> https://docs.microsoft.com/en-in/windows/wsl/install-win10
> See this

No use.

**Comment by BlueNoob** [comment]
> https://docs.microsoft.com/en-in/windows/wsl/install-win10
> See this

wsl --list --online

**Comment by BlueNoob** [comment]
> > https://docs.microsoft.com/en-in/windows/wsl/install-win10
> > See this
> 
> No use.

And also according to this web page: https://docs.microsoft.com/en-in/windows/wsl/install-win10 ,
there is no this command: wsl --list --online

**Comment by ltq525** [comment]
the same to you！ help me！！！
