### ISSUE TITLE
WSL 2 - WslRegisterDistribution failed with error 0x80070040

### ISSUE THREAD

**Issue by kgrishchenyuk** [microsoft/WSL#5280]
WSL 1 installation is OK, WSL 2 - see above. This was after 20H1 update today.

**Comment by devsuitup** [comment]
Same here, on a fresh installation on WSL2 on windows version 2004 build 9041.264
It's crashing Docker when it tries to install the distro, and with debian and ubuntu

**Comment by devsuitup** [comment]
I actually had a different error code, I'm sorry for the noise. Posted another issue for the error code I've got, even though the behavior looks the same.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.
