### ISSUE TITLE
Run a Windows Executable which is in the WSL environment

### ISSUE THREAD

**Issue by Neur1n** [microsoft/WSL#5281]
I've noticed that a Windows executable can be invoked inside WSL, e.g. `/mnt/c/.../foo.exe`, according to this [documentation](https://docs.microsoft.com/en-us/windows/wsl/interop). However, if a Windows executable which is in the WSL environment, it seems not be able to be invoked (e.g. running `~/Documents/foo.exe` from bash).

Am I right about this behavior? Is it a limitation? Thanks.

**Comment by Jochnickel** [comment]
i was able to start a win .exe from ~/

**Comment by Neur1n** [comment]
Is that .exe file inside a subfolder of ~/?

**Comment by onomatopellan** [comment]
make sure it has the execution flag.
`chmod 777 file.exe`

**Comment by Neur1n** [comment]
@onomatopellan You are right.

Thank you guys.
