### ISSUE TITLE
WSL window does not remember last size/position

### ISSUE THREAD

**Issue by vanzod** [microsoft/WSL#5287]
Version 10.0.18363 Build 18363

When opening a new WSL window, the position and size does not reflect the position/size of the last closed window. The window is outside the screen, requiring a move/resize operation every time.

The position/size of a new WSL window should be the same as the latest closed window, consistently with the standard Win 10 behavior.

**Comment by therealkenc** [comment]
From the template that was deleted:

>If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).
