### ISSUE TITLE
WSL2 causing my internet to not work and internet is too slow 

### ISSUE THREAD

**Issue by animeshxd** [microsoft/WSL#5290]
Microsoft Windows [Version 10.0.19041.264]
Note: wsl 1 is working fine
![82815913-ca645c00-9eb7-11ea-890f-20a969a61a05](https://user-images.githubusercontent.com/47624427/83236332-fd0c9e00-a1b0-11ea-896c-1ed6f3283447.png)
![82815917-cc2e1f80-9eb7-11ea-8c5d-d9f7b3899c91](https://user-images.githubusercontent.com/47624427/83236338-00078e80-a1b1-11ea-9cc4-b51337b1ffef.png)
![82815920-cd5f4c80-9eb7-11ea-8455-4063f3f895d1](https://user-images.githubusercontent.com/47624427/83236343-01d15200-a1b1-11ea-8ec0-957f7614f219.png)
![Annotation 2020-05-29 133353](https://user-images.githubusercontent.com/47624427/83236385-11509b00-a1b1-11ea-83df-bba9b19961c2.png)
![Annotation 2020-05-29 133539](https://user-images.githubusercontent.com/47624427/83236569-583e9080-a1b1-11ea-8363-163b49ba01af.png)
![Annotation 2020-05-29 133641](https://user-images.githubusercontent.com/47624427/83236643-76a48c00-a1b1-11ea-9a37-653ac39ed200.png)

**Comment by onomatopellan** [comment]
Just for discard any configuration problem, does `sudo apt update` work with the ethernet cable connected?

**Comment by animeshxd** [comment]
Too slow

**Comment by onomatopellan** [comment]
Create some networking logs and paste the feedback url here so the team can see what's happening.

https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs

**Comment by ApplicationDeveloper** [comment]
Mine too. Noticed after installation of Ubuntu alongside Debian.
Noticed it when I used ssh, it would stutter/lag when typing. I tried using another pc but it was fine there.

**Comment by kenning** [comment]
this happens to me at times, as well as a friend of mine. pretty mysterious.
