### ISSUE TITLE
WSL kernel component update not working

### ISSUE THREAD

**Issue by ramanbanka** [microsoft/WSL#5292]
Windows build: 2004 (19041.264)

1. Enabled the optional feature:
    `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
2. Enabled the "Virtual Machine Platform" optional feature:
    `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
3. Restarted the machine
4. Intalled the latest[ WSL2 Linux kernel update package for x64](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) 
5. I can see "Windows Subsystem for Linux Update" under programs and features.
6. Again restarted the machine

Still, I see this message:
    `PS C:\WINDOWS\system32> wsl --set-default-version 2`
    `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`

**Comment by onomatopellan** [comment]
Can you see the `kernel` file in C:\Windows\System32\lxss\tools?

**Comment by ramanbanka** [comment]
> Can you see the `kernel` file in C:\Windows\System32\lxss\tools?

No

**Comment by Biswa96** [comment]
Try the `msiexec` workaround from here https://github.com/MicrosoftDocs/WSL/issues/591#issuecomment-599330026.

**Comment by ramanbanka** [comment]
Thanks tried, your this comment works: https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281

**Comment by ajensenwaud** [comment]
You can also use 7zip to extract the MSI file and then manually copy across the FID_LXSS_KERNEL file.
