### ISSUE TITLE
WSL2: The network was not found

### ISSUE THREAD

**Issue by bartek048** [microsoft/WSL#5294]
After multiple experiments with WSL2 VPN network issues (Cisco AnyConnect), I lost "vEthernet (WSL)" adapter in Hyper-V. It happened after reboot. I'm not sure why, because didn't change Hyper-V settings.

When I try to open wsl2, I see:
```
WslRegisterDistribution failed with error: 0xffffffff
Error: 0xffffffff (null)
```

Mentioned missing  "vEthernet (WSL)" is the problem, so I added it manually as "internal" network. Now I see:
```
WslRegisterDistribution failed with error: 0x803b0001
Error: 0x803b0001 The network was not found.
```

I tried reenabling WSL/Hyper-V or freshing distro installation, but didn't help. 

Uncle Google is out of ideas, so I'm creating this issue.

**Comment by naidu72** [comment]
Try to reinstall windows subsystem for Linux. It worked for me

**Comment by bartek048** [comment]
> Try to reinstall windows subsystem for Linux. It worked for me

By (un)checking it in Features list? Already tried that.

**Comment by bartek048** [comment]
I had to temporarily disable dnscrypt-proxy service to unblock port 53
