### ISSUE TITLE
Compiling arm gcc crashes on wsl 2 because virtual memory exhausted

### ISSUE THREAD

**Issue by gabrieldds** [microsoft/WSL#5295]
Microsoft Windows [version 10.0.19041.264]

I have tried compile arm gcc for a personal project on wsl 2, but compilation crashes because this:
```
cc1plus: out of memory allocating 65536 bytes after a total of 3624960 bytes

cc1plus: out of memory allocating 259737 bytes after a total of 2277376 bytes
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
cc1plus: internal compiler error: Aborted
make[2]: *** [Makefile:2361: s-attrtab] Error 1
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
```
I already have compiled same project on ubuntu and arch linux, but this is happening and i didn't find any issues of how solve this. It seems that wsl doesn't free memory allocated by program. Any help with this?

**Comment by onomatopellan** [comment]
when that happens do `free -h` and post the output.

**Comment by therealkenc** [comment]
If your building with `make -j` dial it back to -j1 (or no `-j`) to start, and creep up from there. Compiling gcc doesn't actually take that much memory except for the link phase. Hovering around ~600-750MiB for me with one concurrent job.

![image](https://user-images.githubusercontent.com/7049700/83311820-3fd87100-a1c5-11ea-9ac0-735fbc8f6841.png)

**Comment by gabrieldds** [comment]
Well, i put 12 gb on swap and now i think it's working, but now this is result of ```free -h```:
```
total        used        free      shared  buff/cache   available
Mem:          3.8Gi       3.0Gi       542Mi       0.0Ki       351Mi       681Mi
Swap:          12Gi       4.9Gi       7.1Gi
```

Yes, i'm compilling with ```make -j4```, i will try just ```make```. Thanks.

**Comment by therealkenc** [comment]
Yeah 4GiB is cutting it pretty close for a -j4. Old trick: let it build with (say) -j4. Watch it run out of memory. Get over the hump with -j1 (usually a link phase). Then ctrl-c, and start it back up with -j4. Repeat. I've done that with chromium builds, which can take over 32GiB to link.

But in your case with 4gb, probably just -j2, cross fingers, and be patient. The different is not worth the dance. Don't let it swap if you can. Your patience will probably run out.
