### ISSUE TITLE
Cannot Use Windows EXE From Within WSL 2

### ISSUE THREAD

**Issue by gaia** [microsoft/WSL#5296]
![image](https://user-images.githubusercontent.com/87547/83307062-a30fd680-a1b8-11ea-9913-88f8f1a3ee84.png)

* What's wrong / what should be happening instead:
explorer.exe should be in path and launch

```
$ echo $PATH
/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by onomatopellan** [comment]
>/snap/bin

are you using systemd? what method are you using?

**Comment by therealkenc** [comment]
> `$ echo $PATH`

There are no win32 paths in your `$PATH` so interop isn't going to find `explorer.exe`.

**Comment by onomatopellan** [comment]
Something is replacing the path. Try this and post the output:
```bash
cd ~
grep -i -e 'PATH' .*
```

**Comment by gaia** [comment]
![image](https://user-images.githubusercontent.com/87547/83312405-07399700-a1c7-11ea-8621-7109697666fd.png)

**Comment by onomatopellan** [comment]
I don't see anything weird there. Is that the root user?

**Comment by therealkenc** [comment]
Resetting the baseline, there is no `appendWindowsPath=false` in [wsl.conf](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/), right? Also do you happen to be using `WSLENV`?

You can push through this doing a `export PATH=$PATH:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32` in `.profile`.

But it would be nice to know what happened here for the collective knowledge-base. No guesses from me. The `grep` was a good stab, thanks onomatopellan. Maybe `grep -ril` 😏. Actually it would be somewhat weird for something to cleanly sever the Windows paths (and only the Windows paths). Anything possible I guess.

**Comment by gaia** [comment]
> I don't see anything weird there. Is that the root user?

nope. but the root user has the same issue, no win32 in PATH, no explorer.

> Resetting the baseline, there is no `appendWindowsPath=false` in [wsl.conf](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/), right? Also do you happen to be using `WSLENV`?

no `/etc/wsl.conf` . no windows env variable called WSLENV, if that's what you meant?

> You can push through this doing a `export PATH=$PATH:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32` in `.profile`.

this does it.

> Maybe `grep -ril` 😏.

too many results with `-ril`

happy to get to the bottom of this.

**Comment by therealkenc** [comment]
> no windows env variable called WSLENV, if that's what you meant?

Yes. If you don't use `WSLENV` forget I asked.

> too many results with -ril

Yeah, wasn't being real serious about that. 

What is needed is to figure out what steps happened leading up to you not seeing your Windows paths automatically marshalled into WSL (or being blown away after getting there). I don't have any easy guesses to offer unfortunately.

**Comment by wizardnet972** [comment]
same for me with **node.exe.** 
node - command not found.

although node is installed in my windows10 computer. 
I think something is not right with the path variable.

How to set the $PATH to know the paths in windows?

**Comment by WSLUser** [comment]
So I had the paths stripped even with the append option enabled using a custom imported distro automatically set up for WSL2 (though I saw this before on WSL1 before upgrade using Pengwin, FedoraRemix, Ubuntu, etc. from Store). I had also turned `case=on `and as well as having fstab turned on in `/etc/wsl.conf`. After manually setting the custom distro to version 2 again (even though in `wsl --list --verbose`, it shows version 2 and also switching `case=off `and turning fstab off) then doing a `wsl --shutdown`, interop worked again (you can immediately notice it because it automatically goes to the windows home instead of linux home when interop is working properly.)

**Comment by andradei** [comment]
For it was my `.zshenv` file that was setting `PATH` like this:

`export PATH="some/paths/here"`

instead of

`export PATH="some/paths/here:$PATH"` (Notice the appended `:$PATH` at the end)

I didn't know $PATH already had content when WLS2 first started, and that it had precisely the Windows `PATH`s. So my script was overriding that instead of appending to it.

Hopefully this will help others.

**Comment by licanhua** [comment]
For Debian, /etc/profile contributed to this problem.

Here is the path definition in /etc/profile
```
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
```

Please append ":$PATH" and then `wsl --shutdown` to restart Debian.
```
if [ "`id -u`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:$PATH"
fi
```

**Comment by therealkenc** [comment]
Was all ready to forward-dupe this one #5779, but it isn't. [On Ubuntu](https://launchpad.net/ubuntu/+source/base-files) (per [OP](https://github.com/microsoft/WSL/issues/5296#issue-627550600)) `/etc/profile` doesn't unilaterally initialize the `$PATH` and I guess never has.

![image](https://user-images.githubusercontent.com/7049700/90558975-c449e880-e151-11ea-89c7-869ac8ca4ff7.png)

**Comment by 12gabriel3** [comment]
I ran into the same issue after upgrading to windows 2004 and WSL2. System32 was in the PATH but I couldn't execute the commands. Running WSL as an administrator solved the issue.

**Comment by ilaipi** [comment]
> e PATH but I couldn't execute the

@12gabriel3 thanks, it's very useful for me. Do u know how to always run WSL as an administrator ?

**Comment by mcandre** [comment]
I had a workaround for WSL1, but the dang /proc/version output changed case and broke my grep expression. Added `-i` to account for WSL2.

**Comment by aragon000** [comment]
> Resetting the baseline, there is no `appendWindowsPath=false` in [wsl.conf](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/), right? Also do you happen to be using `WSLENV`?
> 
> You can push through this doing a `export PATH=$PATH:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32` in `.profile`.
> 
> But it would be nice to know what happened here for the collective knowledge-base. No guesses from me. The `grep` was a good stab, thanks onomatopellan. Maybe `grep -ril` 😏. Actually it would be somewhat weird for something to cleanly sever the Windows paths (and only the Windows paths). Anything possible I guess.

It work

**Comment by JimmyBringus** [comment]
> Resetting the baseline, there is no `appendWindowsPath=false` in [wsl.conf](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/), right? Also do you happen to be using `WSLENV`?
> 
> You can push through this doing a `export PATH=$PATH:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32` in `.profile`.
> 
> But it would be nice to know what happened here for the collective knowledge-base. No guesses from me. The `grep` was a good stab, thanks onomatopellan. Maybe `grep -ril` 😏. Actually it would be somewhat weird for something to cleanly sever the Windows paths (and only the Windows paths). Anything possible I guess.

Where is ".profile"?

**Comment by HeyITGuyFixIt** [comment]
> Where is ".profile"?

@JimmyBringus in your home folder. So `~/.profile`.
