### ISSUE TITLE
rsync'ing files from WSL 2's file system to a mounted external USB drive is unbearably slow

### ISSUE THREAD

**Issue by nickjj** [microsoft/WSL#5299]
**Please fill out the below information:**
* Your Windows build number:  `Microsoft Windows [Version 10.0.19041.264]`

* What you're doing and what's happening: Running the `rsync` command to sync files and directories from WSL 2's file system to an external USB drive is painfully slow

#### What's wrong / what should be happening instead:

With WSL 1, once I sync'd 400GB of files initially it would only take about 30 seconds to sync ~10 changed files from a mounted internal drive to an external drive. This is my backup process.

With WSL 2, if I do the same thing, it takes literally 20 minutes to sync ~10 changed files.

I'm not sure if it's slow because the permissions are different and those need to be sent over the wire as changes or if it's the new network based mounts with WSL 2.

Here's the output of what happens within WSL 2 after syncing a few file changes:

```
sent 76,436,320 bytes  received 30,590 bytes  72,929.81 bytes/sec
total size is 460,726,438,034  speedup is 6,025.17
```

In this case I was syncing an mp3 and a few text files, so it does seem like rsync in itself is mostly working because the mp3 is 69mb in size. I wonder what is happening behind the scenes tho. Is it transferring meta data changes on all of the files due to the permissions changing since WSL 2 has proper Linux permissions but a mounted external drive does not?

This is an issue for me because now with WSL 2, it's expected we put our source code in WSL 2, which means I can't run my backup script from WSL 1 since I'm backing up a combination of things in my WSL 2 file system and mounted drives.

**Comment by nickjj** [comment]
@therealkenc Were you able to 100% classify this as a poor file system performance related bug or is it  something to do with the permissions being different when syncing a WSL 2 file with proper Linux permissions to a Windows mounted drive which is causing rsync to do a ton of extra work?

**Comment by therealkenc** [comment]
`rsync` has to `getdents(2)` all the directories and `stat(2)` all files, whether they are touched or not. That is slow; slow enough to dominate the wallclock in some cases. It is not somuch "extra" work. It is expected work that takes a terrifically long time.
