### ISSUE TITLE
cant change directory

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [microsoft/WSL#5300]
### Environment

```none
Fresh windows install & updated to 1909
Windows build number: Microsoft Windows [Version 10.0.18363.836]
WSL 1
```

### Steps to reproduce

- open terminal and run `wsl`
- when we're in the bash shell we run `cd any/existing/folder` or `cd $HOME`

### Actual behavior

- nothing happen, it doesn't go the specified folder and i have to cancel the task using `ctrl+c` to be able to run other task

### Expected behavior

expected that when we run `cd any/existing/folder` it go to the specified folder

**Comment by onomatopellan** [comment]
Install another distro from the Store like Ubuntu and try again. Does it work now?

**Comment by mIcHyAmRaNe** [comment]
i finally decided to reset my windows which resolved my issue, 
but i think that the problem comes from: a disabled `ShellExperienceHost` or `searchUI`
