### ISSUE TITLE
Mount network drives in wsl

### ISSUE THREAD

**Issue by ekrogh** [microsoft/WSL#5302]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.264]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Mounting network shares in wsl(2)
E.g. Mapped windows network drives (e.g. Z:) or network locations (e.g. //TIMECAPSEKS/TimeCapsule)

I do that either from bash like
```
	sudo mkdir -p /mnt/TimeCapsule ;
	sudo mount -t drvfs '\\timeCapsEks\TimeCapsule' /mnt/TimeCapsule ;
```
or in /etc/fstab
```
\\timeCapsEks\TimeCapsule	/mnt/TimeCapsule	drvfs	"metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11"	0 0
z:	/mnt/z		drvfs	"metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11"	0 0
```
* What's wrong / what should be happening instead:

Except windows internal drives, c: and d: the mounted drives are not accessible. When I try to list the content I get something like
```
ls -al TimeCapsule/
ls: reading directory 'TimeCapsule/': Invalid argument
total 0
```
or
``` 
ls -al z
ls: reading directory 'z': Invalid argument
total 0
```
The problem is there both in wsl 1 and wsl 2.

In the previous version of windows I didn't have the problem.

Am I doing something wrong ?

--
Eigil

**Comment by therealkenc** [comment]
Can't repro here. 

![image](https://user-images.githubusercontent.com/7049700/83347946-730e2380-a2dd-11ea-8678-1693910c2c84.png)


What is the nature of the server on the other side (TIMECAPSEKS)?

**Comment by ekrogh** [comment]
I have two network drives that behaves the same way.

* Apple Time Capsule
* Buffalo Linkstation 200D

Linux version
eks@stendell:~$ cat /proc/version
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020

**Comment by gitbls** [comment]
Aren't you missing a backslash? Seems like the command should be: sudo mount -t drvfs '\\192.168.64.1\TimeCapsule' /mnt/TimeCapsule -o "metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11";

With 2 slashes?

**Comment by ekrogh** [comment]
Unfortunately not. I think this editor eats the backslash.

If I write it in another way, I get the same result:

eks@stendell:/mnt$ sudo mount -t drvfs //192.168.64.1/TimeCapsule /mnt/TimeCapsule -o "metadata,rw,noatime,uid=1000,gid=1000,umask=22,fmask=11";
mount: /mnt/TimeCapsule: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
<3>init: (64) ERROR: UtilCreateProcessAndWait:489: /bin/mount failed with status 0x2000
<3>init: (64) ERROR: MountPlan9:478: mount cache=mmap,rw,noatime,trans=fd,rfdno=3,wfdno=3,msize=65536,aname=drvfs;path=UNC\192.168.64.1/TimeCapsule;metadata;uid=1000;gid=1000;umask=22;fmask=11;symlinkroot=/mnt/ failed 2
No such file or directory


-- Eigil

**Comment by therealkenc** [comment]
It's not your syntax. If you are seeing `Invalid argument` on a `ls` after a successful mount, that usually indicates a problem/limitation (from WSL's narrow standpoint) with the filesystem driver on the Windows side.

> In the previous version of windows I didn't have the problem.

It is possible there was a regress. If there was we can expect some me2s to roll in. What was the previous working Win10 build? 

One data point that is useful: Did you have to install any third-party software in Windows in order to access the Time Capsule? [Or put another way: is it possible to access the Time Capsule without installing third-party software.]

On WSL2, one option may be to use a Linux [cifs mount](http://manpages.ubuntu.com/manpages/xenial/man8/mount.cifs.8.html).

**Comment by ekrogh** [comment]
Now I "Recovered" to the previous Windows version, 1909, from version 2004, and mounting of my network drives works again!

**Comment by ekrogh** [comment]
The OS build of the windows with the problem is

OS build  19041.264

**Comment by ekrogh** [comment]
Now Windows 10 2004 installed via Settings -> Update & Security and I still get the problem.

I have attached extra information in "Windows_10_2004_WSL_Network_Problems.zip"

[Windows_10_2004_WSL_Network_Problems.zip](https://github.com/microsoft/WSL/files/4789268/Windows_10_2004_WSL_Network_Problems.zip)

**Comment by ekrogh** [comment]
Found out that mounting works when using this form
sudo mount -o vers=1.0 -o username=<user> -o password=<passwd> //<server>/<share> /mnt/share

**Comment by therealkenc** [comment]
What does `mount | grep /mnt/share` look like after that command.

**Comment by ekrogh** [comment]
> What does mount | grep /mnt/share look like after that command.

`mount | grep /mnt/share
//buffalo/share on /mnt/share type cifs (rw,relatime,vers=1.0,cache=strict,username=userid,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.xxx.xxx,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=61440,wsize=65536,echo_interval=60,actimeo=1)
`

It was adding `vers=1.0` that did the trick. For Apple Time Capsule you also have to add `sec=ntlm`.

I have attached my fstab and a script (eksmount) that mounts all drives
[eksmount.zip](https://github.com/microsoft/WSL/files/4797533/eksmount.zip)
[fstab.zip](https://github.com/microsoft/WSL/files/4797534/fstab.zip)

Now my problem is that the shares are Not mounted automatically though fstab is configured (and `sudo mount -a` works fine) and `mountFsTab = true` in /etc/wsl.conf
[wsl.zip](https://github.com/microsoft/WSL/files/4797576/wsl.zip)

Can I do something to solve that new problem ?

-- Eigil

**Comment by startergo** [comment]
So after upgrading to 20150 I lost all my shares:
```
 9pnet: Could not find request transport: virtio
[    2.329472] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/a (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=A:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.329474] ) failed: 22
[    2.339407] 9pnet: Could not find request transport: virtio
[    2.343754] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/b (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=B:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.343757] ) failed: 22
[    2.357270] 9pnet: Could not find request transport: virtio
[    2.360232] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.360234] ) failed: 22
[    2.370613] 9pnet: Could not find request transport: virtio
[    2.373791] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/f (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=F:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.373793] ) failed: 22
[    2.383461] 9pnet: Could not find request transport: virtio
[    2.386423] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/g (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=G:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.386425] ) failed: 22
[    2.396367] 9pnet: Could not find request transport: virtio
[    2.399508] 9pnet: Could not find request transport: virtio
[    2.402571] 9pnet: Could not find request transport: virtio
[    2.407044] 9pnet: Could not find request transport: virtio
[    2.411443] 9pnet: Could not find request transport: virtio
[    2.415845] 9pnet: Could not find request transport: virtio
[    2.421394] 9pnet: Could not find request transport: virtio
[    2.425590] 9pnet: Could not find request transport: virtio
[    2.430046] 9pnet: Could not find request transport: virtio
```
I got 2 new devices:
```
sudo lspci -nn -vvvv -tt 
-+-[ba98:00]---00.0  Microsoft Corporation Device [1414:008e]
 +-[ab56:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 \-[0000:00]-
sudo lspci -nn -vvvv 
ab56:00:00.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio filesystem [1af4:1049] (rev 01)
	Subsystem: Red Hat, Inc. Virtio filesystem [1af4:0040]
	Physical Slot: 4158428068
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 64
	Region 0: Memory at c00000000 (64-bit, non-prefetchable) [size=4K]
	Region 2: Memory at c00001000 (64-bit, non-prefetchable) [size=4K]
	Region 4: Memory at c00002000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: [40] MSI-X: Enable- Count=65 Masked-
		Vector table: BAR=2 offset=00000000
		PBA: BAR=2 offset=00000400
	Capabilities: [4c] Vendor Specific Information: VirtIO: CommonCfg
		BAR=0 offset=00000000 size=00000038
	Capabilities: [5c] Vendor Specific Information: VirtIO: Notify
		BAR=0 offset=00000038 size=00000004 multiplier=00000000
	Capabilities: [70] Vendor Specific Information: VirtIO: ISR
		BAR=0 offset=0000003c size=00000001
	Capabilities: [80] Vendor Specific Information: VirtIO: <unknown>
		BAR=0 offset=00000000 size=00000000
	Capabilities: [94] Vendor Specific Information: VirtIO: DeviceCfg
		BAR=4 offset=00000000 size=00000007
	Kernel driver in use: virtio-pci
lspci: Unable to load libkmod resources: error -12

ba98:00:00.0 3D controller [0302]: Microsoft Corporation Device [1414:008e]
	Physical Slot: 2656115938
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Capabilities: [40] Null
```
How can I recover my shares?
Should I recompile the kernel without virtio passthrough?

**Comment by therealkenc** [comment]
> //buffalo/share on /mnt/share type cifs ... etc etc etc

Thanks for the `mount` output. Mounting type `cifs` vs `drvfs` is how I roll on WSL2. Using drvfs on WSL2 for a cifs filesystem is unnecessarily circuitous (and for you does not work, besides). Contrast WSL1 where there was no other option.

Your `mount -t drvfs` repro is still fair game technically, since a drivefs mount to your TimeCapsule worked on WSL1 with previous builds (19H2, say). That would be a regress. But given the work-around is better than the hypothetical fix, it is not hard to do the math here.

> [    2.329472] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/a (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=A:\;uid=1000;gid=1000;symlinkroot=/mnt/

That is not related to your OP and near certainly #5456.

> Should I recompile the kernel without virtio passthrough?

Free country, but mostly 'no'.

**Comment by startergo** [comment]
> > //buffalo/share on /mnt/share type cifs ... etc etc etc
> 
> Thanks for the `mount` output. Mounting type `cifs` vs `drvfs` is how I roll on WSL2. Using drvfs on WSL2 for a cifs filesystem is unnecessarily circuitous (and for you does not work, besides). Contrast WSL1 where there was no other option.
> 
> Your `mount -t drvfs` repro is still fair game technically, since a drvfs mount to your TimeCapsule worked on WSL1 with previous builds (19H2, say). That would be a regress. But given the work-around is better than the hypothetical fix, it is not hard to do the math here.
> 
> > [    2.329472] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/a (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=A:;uid=1000;gid=1000;symlinkroot=/mnt/
> 
> That is not related to your OP and near certainly #5456.
> 
> > Should I recompile the kernel without virtio passthrough?
> 
> Free country, but mostly 'no'.

It all operated properly with the former Windows version in WSL2 environment. I never said I used it in WSL1. Besides I never had to manually configure the shares. They were automatically configured with the installation of the WSL2 and the Ubuntu/Debian bistros. I am not sure what has changed here apart from the virtio PCI card being passed through. 
So steps to reproduce the error:
Upgrade Windows to the latest 20150 release. 
After the update has finished attempted to start the working WSL2 (error message kernel needs an update)
Inspected the folder c:\windows\system32\lxss\tools and found that the kernel was missing (after the Windows update)
Copy c:\temp\kernel (backup of 4.19.121-microsoft-standard) to c:\windows\system32\lxss\tools
Upon startup of the WSL2 the network shares are broken.
Not sure how to fix this permanently.

**Comment by onomatopellan** [comment]
@startergo Delete that kernel in c:\windows\system32\lxss\tools. In build 20150 you only need to check for Windows Updates to get the latest kernel. Make sure you have "Receive updates for other Microsoft products when you update Windows" enabled in the advanced options.

**Comment by startergo** [comment]
> 
> 
> @startergo Delete that kernel you copied in c:\windows\system32\lxss\tools. In build 20150 you only need to check for Windows Updates to get the latest kernel. Make sure you have "Receive updates for other Microsoft products when you update Windows" enabled in the advanced options.

That fixed it. Thanks.
```
sudo lspci -ttt -nnnn -vvvv
-+-[b98a:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[b56c:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[b4c8:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[b3a0:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[ae0f:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[ad77:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[a88f:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[a1ec:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9f57:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9dad:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9b29:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[99e2:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9988:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9938:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[970f:00]---00.0  Microsoft Corporation Device [1414:008e]
 +-[96c0:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[96ba:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[96a2:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9652:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[9557:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[92f4:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[91ce:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[8f7d:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[8e70:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[8ca1:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[8a7c:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[85dc:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[828d:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[8205:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 +-[808c:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 \-[0000:00]-

```

**Comment by myusrn** [comment]
[ using `ver` -> windows 2004 (os build 19041.329) and `wsl --list --verbose` -> ubuntu version 2 installation ]

I was having issues with cifs mount calls in my wsl2 setup that were not repro'ng on my vm based ubuntu install running on the same host. I saw in this thread folks using `-t drvfs` instead of the `sudo apt install samba` enabled `-t cifs` setting i thought was required.

q1 - Is `-t drvfs` a wsl2 specific oob mount type that we should be using in lieu of the `-t cifs` one that works on vm ubuntu install?

```
sudo mkdir /mnt/myrmthost/myrmtshr
sudo mount -t drvfs //myrmthost/myrmtshr /mnt/myrmthost/myrmtshr -o username=<usrn>
*** works ***
```

```
sudo apt install samba  # to enable -t cifs support
sudo mkdir /mnt/myrmthost/myrmtshr 
sudo mount -t cifs //myrmthost/myrmtshr /mnt/myrmthost/myrmtshr -o username=<usrn>
*** fails ***
mount: /mnt/myrmthost/myrmtshr: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

q2 - I tried enabling sshd in wsl2 so from local and remote host i could push files into my wsl2 instance using `scp` but that isn't working using the same steps i took to enable it in vm based ubuntu install on same host.  is that a known issue or is there existing issue i'm missing that talks about how to make that work?

**Comment by 123dev** [comment]
OK `sudo mount -t drvfs` works in Ubuntu 20.04 in windows WSL2
However launching a docker container from the following image `mcr.microsoft.com/powershell:latest` and then trying to mount `mount -t cifs` does not
We can't use vers=1.0 as smb 1.0 has been turned off on the DFS for security reasons.

PS: same docker container running under physical ubuntu 20.04 box has no issues mounting with the same command.

Any suggestions? have been trying so many tricks with no success.
Step 4 from here http://mattslay.com/connecting-ubuntu-to-windows-shares-and-dfs-trees/ was critical in getting it working under Physical Ubuntu 20.04.
Thanks

**Comment by Clonkex** [comment]
I also have this issue since updating Windows a week ago.

```
sudo mount -t drvfs '\\192.168.11.6\docs' /mnt/u
cd /mnt/u
ls
ls: reading directory '.': Invalid argument
```

:( Very frustrating. I rely on WSL for work and I don't know of any workaround.

**Comment by myusrn** [comment]
@Clonkex not sure what is going on with your above command. I just tested the following and they both work on my windows 10 enterprise 2004 / build 19041.508 wsl2 setup.

```
sudo mount -t drvfs '\\192.168.0.76\temp' /mnt/myrmthost/myrmtshr -o username=obrien
ls /mnt/myrmthost/myrmtshr; umount /mnt/myrmthost/myrmtshr
sudo mount -t drvfs //192.168.0.76/temp /mnt/myrmthost/temp -o username=myusrn
ls /mnt/myrmthost/myrmtshr; umount /mnt/myrmthost/myrmtshr
```

**Comment by calcium** [comment]
> I also have this issue since updating Windows a week ago.
> 
> ```
> $ sudo mount -t drvfs '\\192.168.11.6\docs' /mnt/u
> $ cd /mnt/u
> $ ls
> ls: reading directory '.': Invalid argument
> ```
> 
> :( Very frustrating. I rely on WSL for work and I don't know of any workaround.

I too had this problem.
Did you try what was suggested above?
ie something like
sudo mount -o vers=1.0 -o username=yourusername -o password=yourpassword  //192.168.20.1/shared_disk  /mnt/share/

cos when I tried this, it worked for me.

This is win 10 version 2004 build 19041.508

**Comment by Clonkex** [comment]
@calcium When I tried doing that it just said something like "unknown file system cifs". I'm not on 2004 though, just whatever the latest update that Windows gave me is.

**Comment by calcium** [comment]
BTW, I am on wsl 2, in case that changes anything.

PS > wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

I am running the latest. As in updated it this morning.
I needed to manually check the update. It didnt auto update for me.
Would updating to the latest be problematic for you?

**Comment by onomatopellan** [comment]
@Clonkex post the output of these
`uname -a`
`cat /etc/os-release`

**Comment by Clonkex** [comment]
@onomatopellan 
```
$ uname -a
Linux 146-dh 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by onomatopellan** [comment]
@Clonkex For the "unknown file system cifs" problem try to install cifs with `sudo apt install cifs-utils` first.

**Comment by Marietto2008** [comment]
Hello to everyone.

I'm running Windows 10 vers. Build 21354.co_release.210402-1630 and WSL with this kernel version :

```
root@DESKTOP-N9UN2H3:/mnt/h# uname -a

Linux DESKTOP-N9UN2H3 5.8.0-rc3-microsoft-standard #1 SMP Mon Jun 29 17:48:47 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

As soon as I run WSL I see these error messages :

```
Error during the mounting of one of the file system. For informations,run "dmesg".

swapon: swapfile has holes

ERROR: CreateSwap:875: swapon failed 22

FS-Cache: Duplicate cookie detected

FS-Cache: O-cookie c=000000006320c1f7 [p=00000000dbf76e64 fl=222 nc=0 na=1]

FS-Cache: O-cookie d=00000000c0578065 n=0000000025442b40

FS-Cache: O-key=[10] '34323934393337393337'

FS-Cache: N-cookie c=000000004bc50700 [p=00000000dbf76e64 fl=2 nc=0 na=1]

FS-Cache: N-cookie d=00000000c0578065 n=0000000036816ff5

S-Cache: N-key=[10] '34323934393337393337'

9pnet_virtio: no channels available for device drvfsa

init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/t (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=T:\;uid=1000;gid=1000;symlinkroot=/mnt/

```
so,when I try to access into the drive h (that's formatted with the ext4 fs),I get this error message :

```
root@DESKTOP-N9UN2H3:/mnt/h# ls

ls: reading directory '.': Function not implemented
```

**Comment by onomatopellan** [comment]
@Marietto2008 First of all I would update that kernel with `wsl.exe --update`.

**Comment by Marietto2008** [comment]
how can I disable the custom kernel ?

**Comment by Marietto2008** [comment]
ok...

zio@DESKTOP-N9UN2H3:/mnt/c/Program Files/cmder$ uname -a
Linux DESKTOP-N9UN2H3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Marietto2008** [comment]
I'm running the WSL2 environment on top of Windows 10 Build 21364co_release. Windows 10 is not the only OS that I use every day. In different disks formatted with ext4 I have installed Ubuntu and derivates. What I would like to know is if I can access those disks from within WSL2. Actually I can do it from Windows 10 using the Paragon ext4 file system. But it seems that it is not recognized by WSL2. Infact,when I try to cd into those drives,WSL2 gives the following error :
 
ls: reading directory '.': Function not implemented

**Comment by onomatopellan** [comment]
If it's a different disk you can try using `wsl.exe --mount` as stated in [the docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk).

**Comment by Marietto2008** [comment]
can u give a look at the images below ?

![2021-04-23_18-05-42](https://user-images.githubusercontent.com/755339/115927047-221e9500-a484-11eb-8583-c76022ca5ba5.png)

![2021-04-23_18-07-47](https://user-images.githubusercontent.com/755339/115927050-234fc200-a484-11eb-876f-39f4382c17f0.png)

**Comment by Marietto2008** [comment]
this is my .wslconfig file :

[wsl2]
#kernel=C:\\Users\\marietto2020\\bzImage121-new
nestedVirtualization=true
debugConsole=true
pageReporting=true
kernelCommandLine=intel_iommu=on iommu=pt kvm.ignore_msrs=1 kvm-intel.nested=1 kvm-intel.ept=1 kvm-intel.emulate_invalid_guest_state=0 kvm-intel.enable_shadow_vmcs=1 kvm-intel.enable_apicv=1

**Comment by aagha** [comment]
This solution by @calcium worked for me:

https://github.com/microsoft/WSL/issues/5302#issuecomment-691054678

Per @onomatopellan make sure you install cifs-utils:

https://github.com/microsoft/WSL/issues/5302#issuecomment-691480475

What I'm trying to do now is get this to work for me by putting this command in /etc/fstab, and a reboot isn't doing an auto-mount.

**Comment by seflerZ** [comment]
Anybody knows how to access the "\\tsclient" when staring WSL in a remote desktop session?

**Comment by YuanfengZhang** [comment]
> 

Thanks. That's right. I checked my NAS SMB folder in Windows folder and found that I need to input my Synology since several months.
