### ISSUE TITLE
WSL2 bridge network

### ISSUE THREAD

**Issue by ShePastAway0** [microsoft/WSL#5303]
I'm using WSL2 for developing a network app (client side on Windows and server side on Linux). It seems that by default WSL2 using NAT for networking, so it's not possible to connect both platforms correctly so them can be accessible for each other via various protocols such as TCP, UDP, ICMP, etc.

After quick search I've found a #4150 workaround but this is not valid in my situation because I need full availability (not only TCP). My question is there even a bridge mode in WSL2 (since its a wrapper around Hyper-V) and how to enable it? If not - is there any plans of adding this feature to WSL2? Like a easy to use setting for enabling different network modes without manual firewall forwarding, nesth, etc.?

I and many of my colleagues was expecting that with WSL2 introduction it will be possible to perform such tasks as mine "out of the box" without needing third-party software like Virtualbox but for now I'm stuck and unfortunately have to use VBox for that.

**Comment by ShePastAway0** [comment]
duplicate of what? why closed?

**Comment by therealkenc** [comment]
It is /dupe #4150 which you cited (and its friends #4825 #4928 with a side of #4210).
