### ISSUE TITLE
Process exited with code 9

### ISSUE THREAD

**Issue by Jacky2** [microsoft/WSL#5305]
**Please fill out the below information:**
* Your Windows build number:  

windows10 2004

* What you're doing and what's happening:

`pacman -S libffi`
Why can't I open Arch wsl2 after installing libffi software, System failure caused by libffi software

* What's wrong / what should be happening instead:

Arch WSL2 System failure
[ Process exited with code 9 ]

**Comment by rescenic** [comment]
Which WSL launcher did you use?

**Comment by Jacky2** [comment]
@rescenic The launcher I use is archlinux wsl2. It has been solved. First update the system `pacman -Syu` and then install the software. But there is a problem to ask. If there is a problem with the wsl2 system, must be reinstalling the system to fix it? Is entry rescue mode available?

**Comment by rescenic** [comment]
@Jacky2 Well, I just converted it back to WSL1 if that happens. For example, once, my Alpine WSL didn't work in WSL2, 'dmesg' always appears in the startup. So I converted it back to WSL1.
https://github.com/yuk7/ArchWSL - I use this.
https://github.com/yuk7/ArchWSL2
![arch](https://i.ibb.co/MZbBS75/03-06-2020-690-06-31-28.png)

**Comment by Jacky2** [comment]
@rescenic Thank you!  I use this launcher  too!  But Arch WSL2 cannot run in wsl version1, so i convert Arch wsl version1 it cannot work. Are all launchers WSL version 2 unable to run on WSL version 1?

**Comment by rescenic** [comment]
@Jacky2 yuk7 created special launcher for WSL2: https://github.com/yuk7/ArchWSL2, don't convert it to WSL 1. But when you use https://github.com/yuk7/ArchWSL it can be set to WSL1. I use WSL1 btw for my Arch WSL.

**Comment by Jacky2** [comment]
@rescenic Thanks. I will try it
