### ISSUE TITLE
Slow upgrade to WSL2

### ISSUE THREAD

**Issue by shadycuz** [microsoft/WSL#5310]
I'm over 1 hour into updating a very old WSL1 to WSL2. 

![image](https://user-images.githubusercontent.com/17090999/83410050-453af300-a433-11ea-8af2-9e92990a10c4.png)

Every now and again I see a burst of speed from bsdtar (12-80MB's) but mostly its like 0.5MB's and seems like its getting scanned by Windows Defender.

![image](https://user-images.githubusercontent.com/17090999/83410158-761b2800-a433-11ea-840f-8b99a2029ced.png)

![image](https://user-images.githubusercontent.com/17090999/83410239-a5319980-a433-11ea-82d4-bd28284a9235.png)

**Comment by shadycuz** [comment]
They have taken the RAM and the swap space  We have closed all chrome tabs, but cannot hold it for long. The ground shakes... Drums. Drums in the deep. We cannot get out. A BSOD moves in the dark... We cannot get out... WSL2 is coming...

**Comment by shadycuz** [comment]
Turning real time threat detection off fixed it I think.

Soon as I disabled it...

![IMG_20200601_190316](https://user-images.githubusercontent.com/17090999/83414367-fe50fb80-a43a-11ea-9629-807ec27a4350.jpg)

**Comment by shadycuz** [comment]
That was close...
![image](https://user-images.githubusercontent.com/17090999/83414553-5be54800-a43b-11ea-9bbe-c7da2eb1af2d.png)

**Comment by therealkenc** [comment]
Upgrades are slow owes partly due to #4197. That the operation eats memory is near certainly /dupe #4669, which landed in 19955, implying it didn't make 2004 aka 20H1 aka 19041. [No version given in the OP.]
