### ISSUE TITLE
WSL 0x800701bc requires update for kernel, but already installed

### ISSUE THREAD

**Issue by Jebediah** [microsoft/WSL#5311]
Windows version:
10.0.19631.1

Even after installing the kernel from https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel, this error persists. In "Apps & features" there is
"WindowsSubsystem for Linux Update" version 4.19.104.

I've tried all permutations of uninstalling the update & the Ubuntu distributions, but could not resolve it.

Even though Ubuntu 20.04 is shown as installed in Apps & features. Running wsl --list in powershell says that there aren't any distributions installed.

**Comment by onomatopellan** [comment]
You can try the manual method https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281

**Comment by Jebediah** [comment]
worked thanks @onomatopellan
