### ISSUE TITLE
How to access \\wsl$ from any app?

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#5314]
Is it possible to access \\wsl$ from the command line (Windows side) and or any native app?

**Comment by therealkenc** [comment]
> Is it possible to access `\\wsl$` from the command line 

From PowerShell, [yes](https://serverfault.com/questions/549040/access-network-share-without-mapping-drive-letter-powershell). From `CMD`, not that I know of, excepting [mapping](https://support.microsoft.com/en-ca/help/4026635/windows-map-a-network-drive) the UNC path to a drive letter.

> and or any native app

Apps that understand UNC paths, yes. That that do not, no, excepting mapping the UNC path to a drive letter.

**Comment by warpdesign** [comment]
Thanks for the answer.

After some digging it seems it's actually possible to access WSL from `cmd.exe`. For example, this will work:
> dir \\wsl$\Ubuntu-20.04

**Comment by therealkenc** [comment]
> dir \\wsl$\Ubuntu-20.04

That's right, thank-you. There might be some limitations in CMD, notably a UNC path can't be your current working directory.

![image](https://user-images.githubusercontent.com/7049700/83510902-a0480680-a482-11ea-8a2b-49b24b2d3489.png)

> Accessing the \\wsl$ root to get the list of WSL distributions won't work though

Enumerating the distros via `\\wsl$` is a pretty reasonable ask (I think?) if you or someone who lands here wants to open that as a feature request under another cover.

**Comment by warpdesign** [comment]
@therealkenc good idea! I'll open a feature request for that: I'll need it for https://github.com/warpdesign/react-explorer/issues/149
