### ISSUE TITLE
WSL2/Ubuntu and Windows's hosts file.

### ISSUE THREAD

**Issue by benlumia007** [microsoft/WSL#5315]
I don't know if this is the right place to ask and I don't know if anyone has ever asked before and since there are 1,025 issues, I'm not gonna waste time to look through. 

I just started using WSL2 right before the May 2020 update and I've been doing development under WSL2 ( Ubuntu 18.04 ). The main issue is the hosts file for the Windows side.  Is there a feature coming out where when you update the /etc/hosts file, it also updates the hosts file in parallel. I have to either update the hosts in windows manually or find a module for nodejs and modify it to point the hosts file in windows.

That's my issue right now.

**Comment by LeslieK** [comment]
I enabled wsl2 on may 24, also using ubuntu 18.04. Yesterday i looked at /etc/hosts on linux. I noticed stuff in there from the /etc/hosts file on windows (so the linux file included stuff i added to the windows file to do spoof testing of some apps). I removed those unneeded from windows file. The file on linux picked up my deletions.

**Comment by AdsonCicilioti** [comment]
@benlumia007 I agree. The inverse way make more senso for me too.
I dont understand why @therealkenc close this . But Okey!

**Comment by asdine** [comment]
I have the same problem, can we reopen this issue @therealkenc ?

**Comment by therealkenc** [comment]
This issue isn't on planet template.

**Comment by treysis** [comment]
Where's the template of `/etc/hosts` to which the lines of Windows' hosts file are added?
