### ISSUE TITLE
Cannot access http server located in Windows from WSL2

### ISSUE THREAD

**Issue by alshdavid** [microsoft/WSL#5316]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.264]

* WSL Details:
WSL2
Ubuntu 20.04

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I am unable to access a web server located in Windows from inside WSL2. 

Below I will create an http server, run it inside a Windows Command Prompt then attempt to curl it from WSL2.

I'm not familiar with an easy way to spin up an http server from Windows so I will use Go to write a tiny http server. I'm sure there is a better way, so feel free to use whatever you'd like to.

Video:
![output](https://user-images.githubusercontent.com/12656294/83488214-cf489180-a4ef-11ea-9b47-041cdb1501e3.gif)

Open a powershell window
```
mkdir server
cd server
touch main.go
```
Paste the following code into `main.go`
```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(w, "hello world\n")
	})
	http.ListenAndServe(":8090", nil)
}
```

Then in the powershell window run:
```
go run main.go
```

Accept the firewall prompt
Verify your server is working by opening Edge browser and navigating to `http://localhost:8090`

You can also verify it works by using `curl` form another Windows Command Prompt

Now open a new terminal window with WSL2 and Ubuntu 20.04

```
curl http://localhost:8090
```

We would expect to see `Hello World` but instead we see:
```
curl: (7) Failed to connect to localhost port 8090: Connection refused
```

** Use cases **

Puppeteer cannot be accessed from WSL
https://github.com/puppeteer/puppeteer/issues/5957

**Comment by alshdavid** [comment]
For visibility, users can acess the IP of the wsl host using the following line to their bash profile 
```
tail -1 /etc/resolv.conf | cut -d' ' -f2
```

The http server must also be given access to public networks

![image](https://user-images.githubusercontent.com/12656294/83490208-f5bbfc00-a4f2-11ea-9397-0d96dbdf742e.png)

Then running the following commands inside WSL2 will allow access to the http server.
```
export WSL_HOST=$(tail -1 /etc/resolv.conf | cut -d' ' -f2)
curl http://$WSL_HOST:8090
```
This does not solve the issue of puppeteer because Chrome would need be granted similar firewall permissions

**Comment by bobvandevijver** [comment]
This direction (wsl -> windows) looks unsupported yet: I have the same issue.

**Comment by bobvandevijver** [comment]
@craigloewen-msft I found that page, but interestingly, `/etc/resolv.conf` does not contain the IP of the host machine, but a private network IP (172.21.xx.1) which doesn't respond to anything.

Using the actual IP of the machine does work, but that is something that changes all the time for me...  Without a way of retrieving it from the WSL2 machine, I cannot use it consistently. For now, I downgraded to WSL1.

**Comment by therealkenc** [comment]
That go program only listens on ipv6. Edge meanwhile treats `localhost` as ipv4 `127.0.0.1`.

![image](https://user-images.githubusercontent.com/7049700/83958809-076f0d80-a82b-11ea-822f-25fc2f5df761.png)

Pretty much dupe #4851

**Comment by kilork** [comment]
I was able to get response from Windows server after I did this:

```
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow
```

**Comment by alshdavid** [comment]
> Since you're using WSL 2, you'll need to access your Windows networking applications using the IP of your host machine. We're investigating adding 'localhost' support to this in the future!
> 
> Instructions on how to do that [are here](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-windows-networking-apps-from-linux-host-ip). Let me know if that works for you!

While this does generally work as a workaround, there are certain application which validate that the client is running on localhost - such as when trying to debug Chrome through a tool like "puppeteer"

**Comment by therealkenc** [comment]
From [puppeteer/puppeteer/#2242](https://github.com/puppeteer/puppeteer/issues/2242) it [looks](https://github.com/puppeteer/puppeteer/issues/2242#issuecomment-544219536) like (?) it will accept `*.localhost` names which you can set up with [avahi-daemon(8)](http://manpages.ubuntu.com/manpages/bionic/man8/avahi-daemon.8.html) or an alias in `/etc/hosts`. Other option is to run chromium and puppeteer in WSL with an X Server.

Localhost in the windows direction is /dupe #4619.

**Comment by alshdavid** [comment]
> avahi-daemon(8)

Sadly this will not work because Chrome does the validation. The proxy needs to live on the Windows side as the "remote client" is the address of the WSL guest.

I don't mind working around this, but I'd need to write a readme for my team to follow and I can't guarantee everyone can

**Comment by therealkenc** [comment]
> Sadly this will not work

Will not or [did not](https://github.com/microsoft/WSL/issues/5368#issuecomment-645316048).

**Comment by doctorchuks** [comment]
This Microsoft page helped solve this on my end

https://docs.microsoft.com/en-us/windows/wsl/networking

Check in the "Accessing Windows networking apps from Linux (host IP)" section

**Comment by godotc** [comment]
try:
```go
http.ListenAndServe("127.0.0.1:8090", nil)
```

**Comment by MiCurry** [comment]
> try:
> 
> ```go
> http.ListenAndServe("127.0.0.1:8090", nil)
> ```

This worked for me! Thanks.

**Comment by brunolm** [comment]
I ran the firewall commands, but I don't know if they did anything. What definitely worked for me was to grab the IP address from here:

```
tail -1 /etc/resolv.conf | cut -d' ' -f2
```

Is this in some documentation somewhere? I got lucky to find it in this thread...
