### ISSUE TITLE
WSL2 localhost forwarding randomly stop working

### ISSUE THREAD

**Issue by svakirtzis** [microsoft/WSL#5317]
* Your Windows build number:  Version 2004 (OS Build 19041.264)

* What you're doing and what's happening: 
Running Ubuntu 20.04 with WSL 2 enabled.
```
C:\Users>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```
Inside WSL2 terminal i run a quick HTTP server with node doing the following:
```
$  npx http-server .
npx: installed 23 in 1.847s
Starting up http-server, serving .
Available on:
  http://127.0.0.1:8080
  http://172.20.178.242:8080
Hit CTRL-C to stop the server
```
In Chrome or Firefox within Windows i am  trying to access http://localhost:8080 which results in connection refused. Doing a curl  on the same resource from within WSL2 works fine.

* What's wrong / what should be happening instead:
I believe it should be working since WSL2 supports forwarding.
After going in Windows task manager and restarting the `LxssManager` service everything worked again.

Unfortunately i cannot provide a certain pattern to reproduce this, since it seems to be happening randomly or at least on currently unknown circumstance to me. 
(this has happened 4 times in 2 days)
 Let me know if I can provide more info. Thanks!

**Comment by onomatopellan** [comment]
See #5298. 

Turning off Fast Startup seems best solution for now. 
https://www.tenforums.com/tutorials/4189-turn-off-fast-startup-windows-10-a.html

**Comment by svakirtzis** [comment]
@onomatopellan Thank for the help.

I also confirm that the issue is happening when i initially start my computer from a shut down state.

**Comment by onomatopellan** [comment]
Thanks for the confirmation. I think @benhillis @craigloewen-msft  need to know this. This explains why so many people still had random problems with localhost forwarding in build 19041.

**Comment by craigloewen-msft** [comment]
Thank you for the tag @onomatopellan ! I'll use #5298 as the landing zone for this issue.
