### ISSUE TITLE
wsl.exe command not recognized

### ISSUE THREAD

**Issue by Caleb9** [microsoft/WSL#5319]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.19041.264]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Trying to install WSL following the guide [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Command is not available.

![image](https://user-images.githubusercontent.com/7767011/83546622-3c185780-a501-11ea-88e6-6f457c6195ae.png)

* What's wrong / what should be happening instead:

`wsl.exe` should be available.

**Comment by DHowett** [comment]
You’re using 32-bit powershell. You’ll want to use 64-bit powershell, or specify the fully qualified _redirected path_ to wsl.exe, `c:\windows\sysnative\wsl.exe`.

**Comment by Caleb9** [comment]
@DHowett That's it, thank you :).
