### ISSUE TITLE
fio: pid=711, err=38/file:engines/libaio.c:406, func=io_queue_init, error=Function not implemented

### ISSUE THREAD

**Issue by Jacky2** [microsoft/WSL#5321]
* Your Windows build number (run `ver` at a Windows Command Prompt), your distribution 

Windows10 2004
WSL version1
WSL Launcher debian10 install from microsoft application store.
fio version fio-3.15 

* What you're doing and what's happening. Copy&paste the _full_ set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screenshots if that helps demonstrate the problem:

```shell
./fio -direct=1 -iodepth=128 -rw=randread -ioengine=libaio -bs=4k -size=1G -numjobs=1 -runtime=1000
-group_reporting -filename=iotest -name=Rand_Read_Testing
Rand_Read_Testing: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-3.15
Starting 1 process
fio: pid=726, err=38/file:engines/libaio.c:406, func=io_queue_init, error=Function not implemented


Run status group 0 (all jobs):
```

* What's wrong / what should be happening instead:

I cant use fio software ,

fio: pid=711, err=38/file:engines/libaio.c:406, func=io_queue_init, error=Function not implemented

but fio can use in Windows10 1909.

**Comment by therealkenc** [comment]
No strace provided.
```
633   io_setup(128, 0x7fffeb098f50)     = -1 ENOSYS (Function not implemented)
633   write(1, "fio: pid=633, err=38/file:engine"..., 99) = 99
633   munmap(0x7f5c02160000, 536576)    = 0
```

You want WSL2.

**Comment by Jacky2** [comment]
I try wsl2 also this problem

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/83597393-0896f680-a51c-11ea-88f1-865dafff31f6.png)

To a first order, there is no such thing as `ENOSYS` in WSL2. [Edge case kconfig type things notwithstanding, but a `io_setup` is not one of them.]

**Comment by Jacky2** [comment]
OK，I try run fio in WSL2  is work . Think you. 

However, the iops of the fio test of WSL1 version of Windows 10 1909 is relatively high.

But I found that after updating Windows 2004, WSL1 was running slowly, especially when git status checking was enabled with oh-m-zsh.

This is my test in WSL2

![image](https://user-images.githubusercontent.com/23411395/83598619-c4980600-a59c-11ea-9dd0-63890bb34e97.png)
