### ISSUE TITLE
How to do data rescue from WSL2 VHDX image on another computer?

### ISSUE THREAD

**Issue by entn-at** [microsoft/WSL#5322]
Hi,
my laptop died and I am trying to retrieve files from its SSD via an external enclosure. The files are inside WSL2's VHDX image (running Ubuntu 18.04). How can I access them from another (Win10) machine without the ability to boot into the Win10 installation that hosted it?
Thanks
EDIT: Since I cannot boot into the system, I am unable to use `wsl --export` etc. or use 9P file sharing.

**Comment by 0xbadfca11** [comment]
Use ``qemu-img`` to convert from ext4.vhdx to raw disk image, then mount it.
Wish you could mount ext4.vhdx directly, but ``qemu-nbd`` and ``libguestfs-tools`` won't work.

**Comment by therealkenc** [comment]
That's a good answer. More on qemu-img [here](http://manpages.ubuntu.com/manpages/bionic/man1/qemu-img.1.html) and guestfish [here](http://manpages.ubuntu.com/manpages/cosmic/man1/guestfs-recipes.1.html).

Another reasonable approach would be to attach the vhd to your VM of choice ref #4574 ([message](https://github.com/microsoft/WSL/issues/4574#issuecomment-539171205))

> Wish you could mount ext4.vhdx directly

Goes to #4556.

**Comment by entn-at** [comment]
Thanks @0xbadfca11 it worked perfectly!

**Comment by Biswa96** [comment]
Another approach, copy the vhdx file to new system, register a dummy WSL2 distribution (like 0xbadfca11 has miniwsl), replace the newly created ext4.vhdx with your old one. Just take 10 seconds + copy paste time. Your WSL2 system will be intact.

**Comment by thoni56** [comment]
For those coming here wanting to rescue their complete WSL2 distribution from an unbootable but readable disk (like me) I can just add that simply replacing the `ext4.vhdx` in a fresh installation with the one from the old computer worked perfectly.

**Comment by guiguiboy** [comment]
I recently had a similar problem : had to reinstall the whole computer but kept the original ext4.vhdx.
You can simply use 7zip to open the vhdx file, pickup the files you want and put them in your new setup.

**Comment by Biswa96** [comment]
> You can simply use 7zip to open the vhdx file, pickup the files you want and put them in your new setup.

The down side is that the file attributes (permission, owner etc.) will be reset.

**Comment by cylzxje** [comment]
My `ext4.vhdx` is corrupted and unreadable so create a dummy WSL2 distro doesn't work
