### ISSUE TITLE
Ubuntu20.04 Installing WslRegisterDistribution failed with error: 0xc03a001a

### ISSUE THREAD

**Issue by aiyodiulehuner** [microsoft/WSL#5325]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xc03a001a
Error: 0xc03a001a ???????????????????????????????????????????????????

**Comment by rs-droid** [comment]
So, I did some digging and in the end, this is what did the trick for me.

NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.

Hope this helps, bonne chance!

**Comment by jaywhen** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

Thanks！I had the same error with Ubuntu 18.04 ,that worked for me!

**Comment by ycg000344** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

Thanks.

**Comment by WHU-Aaron** [comment]
Thanks！I had the same error with Ubuntu 18.04 ,that worked for me!

**Comment by WHU-Aaron** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

Thanks！I had the same error with Ubuntu 18.04 ,that worked for me!

**Comment by mp54214** [comment]
This solve also my similar issue I was facing in installing ubuntu.

**Comment by slimbis** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

Nice! Thank you!

**Comment by hu-qi** [comment]
> 所以，我做了一些挖掘，最后，这就是我的窍门。
> 
> NTFS具有压缩目录以节省空间的功能。如果您的某些或全部图标都带有2个相反的蓝色箭头标记，则表明该功能确实处于启用状态。现在，由于这个原因，托管商店下载的目录（在本例中为Ubuntu）可能也有相同的问题。
> 转到C：\ Users \用户名\ AppData \ Local \ Packages文件夹。如果不明显，则可能是隐藏的。进入目录后，使用“ ubuntu”字符串/关键字搜索子目录。找到后，右键单击目录>高级>取消选中压缩>应用。现在ubuntu目录应该删除了箭头，这意味着您应该有更大的机会实际运行发行版安装。
> 
> 希望这会有所帮助，机会很大！

![image](https://user-images.githubusercontent.com/17986122/96959764-5ea02100-1533-11eb-8b83-261d486723e6.png)

Thanks!It work!

![image](https://user-images.githubusercontent.com/17986122/96959855-88f1de80-1533-11eb-824e-77b73ff970a1.png)

**Comment by rs-droid** [comment]
Thanks guys, glad I could help!

**Comment by GENG824** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

thanks！

**Comment by Muskya** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

It did the trick. Thank you a lot 👍

**Comment by IsakGideon** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

Thanks a lot!!! It helps me out!

**Comment by javidigani** [comment]
Worked for me too! Once in the right folder, I had to select "Apply changes to this folder, subfolders and files" to get the install working. 

Also notable, if your run into this error and the install doesn't complete, the temporary installation folder you need to modify may look like: `CanonicalGroupLimited.UbuntuonWindows_*` with a 16 character string after it. I'm tired so it took me longer than I'd like to admit to notice that..

**Comment by Olimber** [comment]
> So, I did some digging and in the end, this is what did the trick for me.
> 
> NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue. Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> 
> Hope this helps, bonne chance!

I can't find the Ubuntu in the subfolders HELP!

**Comment by Bisyri07** [comment]
> > So, I did some digging and in the end, this is what did the trick for me.
> > NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> > Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> > Hope this helps, bonne chance!
> 
> Thanks！I had the same error with Ubuntu 18.04 ,that worked for me! Similar :
> 
> * [#4103](https://github.com/microsoft/WSL/issues/4103#issuecomment-501885534)
> * [#4299](https://github.com/microsoft/WSL/issues/4299)

so how to make it appear? I did not see C:\Users\user name\AppData\Local\Packages

**Comment by Bisyri07** [comment]
> > So, I did some digging and in the end, this is what did the trick for me.
> > NTFS has this feature that compresses directories to save space. If some or all of your icons are marked by 2 opposing blue arrows, that's your sign that said feature is indeed on. Now, because of this, the directory that hosts your Store downloads (in this case Ubuntu) might also have the same issue.
> > Go to C:\Users\user name\AppData\Local\Packages folder. If not apparent, it's probably hidden. Once inside directory, search subdirectory with 'ubuntu' string/keyword. Once located, right click the directory > Advanced > uncheck the compression > Apply. Now the ubuntu directory should have the arrows removed, which means you should have a better chance at actually running the distro install.
> > Hope this helps, bonne chance!
> 
> Thanks！I had the same error with Ubuntu 18.04 ,that worked for me! Similar :
> 
> * [#4103](https://github.com/microsoft/WSL/issues/4103#issuecomment-501885534)
> * [#4299](https://github.com/microsoft/WSL/issues/4299)

Thanks
