### ISSUE TITLE
Can't run `flutter doctor` from wsl bash vscode integrated terminal - line ending problems.

### ISSUE THREAD

**Issue by JoeCodeswell** [microsoft/WSL#5327]
Please use the following bug reporting template to help produce issues which are actionable and reproducible, including **all** command-line steps necessary to induce the failure condition. See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for more information. If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [terminal tracker](https://github.com/microsoft/terminal/issues). For documentation improvements, please post to the [documentation tracker](https://github.com/MicrosoftDocs/WSL/issues).

**Important: Do not open GitHub issues for Windows crashes (BSODs) or security issues.**  Please direct all Windows crashes and security issues to secure@microsoft.com.  Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".
<br/><br/>

Please fill out **all** the fields! Issues with missing or incomplete issue templates will be closed. 

* Your Windows build number (run `ver` at a Windows Command Prompt), your distribution (f.e. on Debian/Ubuntu run `lsb_release -r`), and whether the issue manifests on WSL 2 and/or WSL 1 (`cat /proc/version`): 
  - `ver`: `Microsoft Windows [Version 10.0.18363.836]`
  - `lsb_release -r`: `Release:        16.04`
  - `cat /proc/version`:  `Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020`

* What you're doing and what's happening. Copy&paste the _full_ set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screenshots if that helps demonstrate the problem:
Problem with `flutter doctor` command in vscode WSL integrated terminal:
```bash
WSL .../login_webapp/ $ flutter doctor
/mnt/c/flutter_beta/flutter/bin/flutter: line 5: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 6: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 14: $'\r': command not found
: invalid optioneta/flutter/bin/flutter: line 15: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/mnt/c/flutter_beta/flutter/bin/flutter: line 16: $'\r': command not found
': not a valid identifierer/bin/flutter: line 17: unset: `CDPATH
/mnt/c/flutter_beta/flutter/bin/flutter: line 18: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 19: syntax error near unexpected token `$'{\r''
'mnt/c/flutter_beta/flutter/bin/flutter: line 19: `function follow_links() {
WSL .../login_webapp/ $ 
```

* What's wrong / what should be happening instead:
This should behave like Git-Bash
```bash
GB .../~/ $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.45.1)
[√] VS Code, 32-bit edition
[√] Connected device (2 available)

! Doctor found issues in 2 categories.
GB .../~/ $

```

* An [`strace(1)`](https://www.man7.org/linux/man-pages/man1/strace.1.html) log of the failing command (if `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/)). For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs):

```bash
WSL .../login_webapp/ $ strace -o flutter.strace -f flutter doctor 
/mnt/c/flutter_beta/flutter/bin/flutter: line 5: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 6: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 14: $'\r': command not found
: invalid optioneta/flutter/bin/flutter: line 15: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/mnt/c/flutter_beta/flutter/bin/flutter: line 16: $'\r': command not found
': not a valid identifierer/bin/flutter: line 17: unset: `CDPATH
/mnt/c/flutter_beta/flutter/bin/flutter: line 18: $'\r': command not found
/mnt/c/flutter_beta/flutter/bin/flutter: line 19: syntax error near unexpected token `$'{\r''
'mnt/c/flutter_beta/flutter/bin/flutter: line 19: `function follow_links() {
WSL .../login_webapp/ $ 
```
I have attached `flutter.strace.txt
[flutter.strace.txt](https://github.com/microsoft/WSL/files/4724768/flutter.strace.txt)
` below.
Thanks for the help.
Love and peace,
Joe Dorocak aka JoeCodeswell

**Comment by DHowett** [comment]
I believe checking out any repository from Windows leaves the line endings in Windows format.

This isn’t really something WSL should try to fix, because it would put us back in the dark ages where you had to tell your FTP server to do a transfer in ASCII (mangle my files) it Binary (please don’t mangle my files) mode...

**Comment by therealkenc** [comment]
> because it would put us back in the dark ages where you had to tell your FTP server to do a transfer in ASCII (mangle my files) or Binary (please don’t mangle my files) mode...

True. But it is easy to forget that the [Dark Ages](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) lasted for [1000 years](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings). 😉

This is /dupe #2365 and friends. There is no WSL actionable; the problem (such that it is) is in userspace. Still no one motivated enough to do a `bash` PPA with [`set -o igncr`](https://stackoverflow.com/questions/42072239/how-to-set-up-cygwin-to-use-dos-file-endings). Not even sure doing one would cause more harm than good (although it would be interesting to watch the show).
