### ISSUE TITLE
 Cannot upgrade to WSL 2 even enable all the options

### ISSUE THREAD

**Issue by birdmanmandbir** [microsoft/WSL#5328]
* Windows version: 10.0.19041.264, windows 10 home edition
* What you're doing and what's happening:
  - enable virtual machine platform
  - enable linux subsystem
  - install ubuntu 18.04 from windows store (work well on wsl 1)
  - enable virtualization in BIOS
![image](https://user-images.githubusercontent.com/48193000/83664046-0d32dc00-a5fc-11ea-877d-34ce1bb130e6.png)
![image](https://user-images.githubusercontent.com/48193000/83664052-0efc9f80-a5fc-11ea-88f4-7db8eb8e0dac.png)

* What's wrong / what should be happening instead:
When I execute `wsl --set-version Ubuntu-18.04 2`, it said 
"please enable virtual machine platform and enable virtualization in BIOS", but I already open these options
![image](https://user-images.githubusercontent.com/48193000/83664231-4c612d00-a5fc-11ea-8404-3127f9639fd2.png)

So confused..

**Comment by truboxl** [comment]
Output of `systeminfo`?

**Comment by radiogron** [comment]
Fantastic. Hours spending an answer on question «Why it worked before windows reinstall and broken after» found in... wtf...

Btw thanku you, your solution worked to me.
