### ISSUE TITLE
invoke-rc.d: could not determine current runlevel with Openssh

### ISSUE THREAD

**Issue by Hamsas** [microsoft/WSL#5330]
Hello, my windows 10 version is  10.0.18363.836. 
I've started with WSL1 and already have some files in the system.
Thus, I don't wish to move to WSL2 even though I think that my version is low so I cannot upgrade.

However, I hope to have GUI with the WSL ubuntu 18.04.
Thus, with my limited cap, I've done some search online and it seems that it is possible to open a port via Openssh and get an access to the GUI VcXsrv in the windows system from the native X xfce in the Ubuntu. Yet, to do so I had to do the following command,

xxx@yyy:~$ sudo dpkg-reconfigure openssh-server
[sudo] password for xxx:
invoke-rc.d: could not determine current runlevel

Why am I getting this error message? What is the reason?
Also, would there be any way that I can access VcXsrv from Ubuntu in WSL1?

Thank you so much!
Any unsolicited ideas are welcome. 

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

#  Expected behavior

# Actual behavior

**Comment by therealkenc** [comment]
> Why am I getting this error message? What is the reason?

/dupe #573

> Also, would there be any way that I can access VcXsrv from Ubuntu in WSL1?

2. If I list multiple bugs/concerns in this one issue, the core team may close my issue without further explanation or engagement.

**Comment by rescenic** [comment]
https://github.com/rescenic/autossh 
https://dev.to/darksmile92/linux-on-windows-wsl-with-desktop-environment-via-rdp-522g

Those are the guides that will lead you to have running xrdp in your ubuntu wsl.

**Comment by Hamsas** [comment]
Wow! it works. Thank you so much for your help, Rescenic. Even without autossh, just with the remote desktop connection, even though I had to pay for it to upgrade into pro..., anyhow, rdc made all possible. Thank you again!

**Comment by rescenic** [comment]
Welcome. When connecting to SSH Server (sshd), you can enable X11 Forwarding in SSH Client, like Putty and VcXsrv Display Server.

**Comment by Hamsas** [comment]
Thank you for your suggestions. I hope to do so... Yet, I am new to all these so.. is there any website or a thread that explains more step by step how to configure that? Thank you!

**Comment by rescenic** [comment]
There are lots of tutorials in youtube. Just search for the relevant keywords.

**Comment by Hamsas** [comment]
Ok. I will look for them. Have a great day!
