### ISSUE TITLE
Enumerating the distributions when accessing \\wsl$

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#5333]
**Is your feature request related to a problem? Please describe.**
There no easy way to list the WSL distributions other than by calling `wsl -l -q`.

**Describe the solution you'd like**
As described in this [issue](https://github.com/microsoft/WSL/issues/5314#issuecomment-637452652) it would be great if accessing `\\wsl$` would return the list of WSL distributions.

**Comment by therealkenc** [comment]
> it would be great if accessing \\wsl$

Dang, the ask isn't as well formed as it seemed the other night. You hand-waved "accessing" above, when what you meant is directory enumeration ("dir"). And `\\wsl$` is, most unfortunately, not a directory. Analogy, my Media PC (ASUS-NETTOP) has two shares "Downloads" and "Users". But `\\ASUS-NETTOP` is not a path. It's a share component.

![image](https://user-images.githubusercontent.com/7049700/83746501-0617c800-a614-11ea-92a3-8022dc39f854.png)

Someone super motivated could hypothetically create a cmdlet based on [this](https://github.com/therealkenc/EnumWSL), along the lines of (but not the same as) [Get-SmbShare](https://docs.microsoft.com/en-us/powershell/module/smbshare/get-smbshare). But we way off the reservation now. This is my bad for suggesting `dir \\wsl$` made sense (it was late then too😳). Probability of this seeing light as a WSL ask: miniscule.
