### ISSUE TITLE
Incorrect wsl disk space

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/WSL#5335]
```
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

```
❯ lsb_release -r
Release:        20.04
```

```
❯ cat /proc/version
Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019
```

# Steps to reproduce
`df -h -> enter`

#  Expected behavior
Free space on wsl corresponds to reality

# Actual behavior

Free / occupied space does not correspond to reality
![image](https://user-images.githubusercontent.com/35394377/83756183-5aa05f00-a677-11ea-96f1-22f3f9d7d631.png)

**Comment by benhillis** [comment]
/dev/sdb is not your C drive, it's a VHD that contains your root filesystem.

**Comment by Mystic8b** [comment]
Yes, but there should be as much space on it as there is on the current drive, isn’t it?

**Comment by therealkenc** [comment]
No, because it isn't your drive. There is 250MiB on "it" (by default). Where the "it" here isn't a real drive. It is a virtual block device. The size of the _virtual device_ is 250MiB whether the _backing storage_ for the device lives on a 128 gigabyte ssd or a 128 terrabyte raid array. The size isn't real because the device isn't real.

**Comment by Mystic8b** [comment]
Where is 250mb here? There 251GB

**Comment by benhillis** [comment]
@Mystic8b - I don't see MB anywhere in the screenshot you posted, I might be looking at it wrong but I see.

/dev/sdb size=251G used=2.8G
C:\ size=209G Used=98G

**Comment by Mystic8b** [comment]
> /dev/sdb size=251G used=2.8G
> C:\ size=209G Used=98G

Exactly. Where does 251gb come from?
About megabytes, I never said a word

**Comment by therealkenc** [comment]
Type-o obv. 250 GiB (shows as 251GiB). That number is arbitrary ref #4373.

**Comment by Mystic8b** [comment]
Okay, therealkenc edited his post, first he wrote 250mib
So you want to say that a 250GB virtual disk with a real free space of 98GB is normal?

**Comment by therealkenc** [comment]
Very normal. You can have a dozen 250 GiB virtual disks (total of 3TiB of space that doesn't really exist) one 128 GiB SSD.

**Comment by benhillis** [comment]
> About megabytes, I never said a word

You can't lie on the internet:
![image](https://user-images.githubusercontent.com/17727402/83795876-f9679400-a654-11ea-8bf7-8257c7897690.png)

**Comment by benhillis** [comment]
@therealkenc is right, the disk is dynamic and that is the maximum size.

**Comment by Mystic8b** [comment]
![image](https://user-images.githubusercontent.com/35394377/83796043-09a95e80-a6a9-11ea-833e-927b3694b2a4.png)
kapish?

**Comment by therealkenc** [comment]
Thought of a clearer way to put this. Your ext4 filesystem is ~250GiB. It doesn't [resize](http://manpages.ubuntu.com/manpages/xenial/man8/resize2fs.8.html) every time you consume a few more bytes in Windows.

**Comment by Mystic8b** [comment]
damn, okay, it seems there is an opportunity to reduce the size of this disk, even so.
ty

**Comment by Mystic8b** [comment]
And deleted the trash message from benhillis, ahaha, nice

**Comment by benhillis** [comment]
This isn't constructive.
