### ISSUE TITLE
wsl2 cannot create temp file for here-document: Read-only file system

### ISSUE THREAD

**Issue by eromoe** [microsoft/WSL#5337]
# Environment

wsl2, win10 2004

# Steps to reproduce

I don't know . 

1. I was using vscode 
2.  runing `pipenv install ` 
3. vscode got error, then I found pipenv stuck
4. quit terminal and reopen it  ， go to same place ,  `pipenv install  again`
5. Is seems create virtual env successfully , but got error on later step :
![image](https://user-images.githubusercontent.com/3938751/83774559-6b24f980-a6b8-11ea-8d77-5f54ab262db4.png)

6. then I found

```
$ vim ~/.zshrc                
zsh: Input/output error: vim  
```
7. start a new shell , got 
```
0/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 210: cannot create temp file for here-document: Read-only file system /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 210: cannot create temp file for here-document: Read-only file system  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 210: cannot create temp file for here-document: Read-only file system  zsh: locking failed for /home/xxxxxx/.zsh_history: read-only file system: reading anyway                                                   
```

PS: I am using windows terminal

**Comment by eromoe** [comment]
Looks like windows driver run out of space . 
But after I clean up 10G for this driver , still go same error .

**Comment by benhillis** [comment]
@eromoe - How much free space is on your D: drive?

**Comment by eromoe** [comment]
about 24M at that time ?  can't remember clearly
