### ISSUE TITLE
Failed to load WSL2 subsystem with error 0x80041002

### ISSUE THREAD

**Issue by ifrond** [microsoft/WSL#5340]
-  Microsoft Windows [Version 10.0.19041.264]
- What you're doing and what's happening:
   * Tried to install WSL2 with Ubuntu 20.04 LTS. After several usages and reboots can't load it. 
   * Tried to reinstall Windows and again after few reboots can't start subsystem anymore. 
   * At subsystem was installed docker, docker-compose, composer and git. Nothing specific
- What's wrong / what should be happening instead:
   * Fails at start subsystem with error 0x80041002
![image](https://user-images.githubusercontent.com/398143/83807096-cce26500-a6b2-11ea-85f8-5dff7bdeb2be.png)
I can see installed wsl but can't start it anymore
![image](https://user-images.githubusercontent.com/398143/83807456-6873d580-a6b3-11ea-8dea-f593863e15a0.png)

**Comment by ifrond** [comment]
Tried to install fresh debian subsystem. Fails with same error code but with more descriptions
WslRegisterDistribution failed with error: 0x80041002
![image](https://user-images.githubusercontent.com/398143/83808381-f8fee580-a6b4-11ea-89ce-e19ea583d39b.png)

**Comment by onomatopellan** [comment]
Also see #4618

**Comment by TobbyReign** [comment]
Comodo Firewall block them. Even if disabled.

1. On Comodo Firewall main screen, click on "**Unblock Applications**"
2. Select all the app related to the PowerShell and Microsoft.
3. Click on **"Unblock"** at the top and select "**Unblock for all security components**"
4. Retry the installation/update for Linux

**Comment by b-hayes** [comment]
I have this problem appear today. Haven't been able to do any work all day because my entire dev env is inside that wsl distro.

I even tried removing all distros and installing a fresh copy of Ubuntu and I get the same error when trying to setup the first time.
```WslRegisterDistribution failed with error: 0x80041002```

At this point im tempted to reins-all windows lol.

**Comment by ScullKeith** [comment]
> Comodo Firewall block them. Even if disabled.
> 
> 1. On Comodo Firewall main screen, click on "**Unblock Applications**"
> 2. Select all the app related to the PowerShell and Microsoft.
> 3. Click on **"Unblock"** at the top and select "**Unblock for all security components**"
> 4. Retry the installation/update for Linux

I don't know what Comodo is. That's not something I'm using or is installed on my machine yet I face error of the OP.
