### ISSUE TITLE
WSL 2 - wsl command randomly exits immediately with exit code 1

### ISSUE THREAD

**Issue by mogzol** [microsoft/WSL#5342]
# Environment

```none
Windows build number: 10.0.19635.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Run the `wsl` or `bash` command, and it will randomly exit immediately with error code 1. To reproduce, run this in Powershell:

```
$LastExitCode=0; while ($LastExitCode -eq 0) { wsl echo hello }
```

For me, that will usually exit within a few minutes, though it seems that the longer my computer has been on and using WSL, the sooner it happens. After using my computer and WSL for a while (~eight hours), that command will usually end after just a few seconds. If I `--terminate` wsl and then run that command again, it takes much longer to happen, sometimes up to half an hour or so, but does eventually start happening again.

#  Expected behavior

`wsl` command always runs, or at least gives some output as to the error.

# Actual behavior

Running a `wsl` or `bash` command will randomly exit immediately with exit code 1 and no other output.

I realize that this is a huge pain to figure out the root cause of or reproduce, if you need more details please ask, I can try to provide them for you.

**Comment by therealkenc** [comment]
> Running a wsl or bash command will randomly exit immediately

I can't repro the "exit immediately" part here on 19640. [Implies nothing about whether it would run for 8 hours naturally.]

**Comment by mogzol** [comment]
Here's a short clip demonstrating the behavior after a full day of me using WSL. Note that I'm not hitting CTRL+C or anything to stop it, it just randomly does this.

![wsl-exit-issue](https://user-images.githubusercontent.com/11789801/84452948-12031b80-ac0c-11ea-8837-ac72b975eea2.gif)

Like I said, restarting WSL does make the issue happen less frequently, but having to restart WSL every few hours isn't the greatest solution.

**Comment by GregDThomas** [comment]
FWIW, I'm seeing this behaviour with Ubuntu 18.04.5 LTS with WSL 2 on 19042.804 - this is new, following an upgrade to Windows 20H2 + WSL2 from WSL1

**Comment by Jason5Lee** [comment]
I just got this error. `wsl echo 1` just exit without anything.

**Comment by Kallys** [comment]
I'm experiencing the same issue.  
Debian 11.1 "5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 GNU/Linux" on Windows 11.

**Comment by bojiang** [comment]
Experiencing the same issue.
Both Ubuntu 20.04 LTS and desktop docker exit immediately.
winver: 19044.1466

**Comment by ayalon** [comment]
I have the same issue.

**Comment by ayalon** [comment]
I think I found the reason for this behavior. It's related to the INTEROP sockets that are created.
If you are using a tool like IntelliJ / Jetbrains IDE or if you are using Fork with WSLGit, every command (mostly git calls) create a new socket. At some point there are too many sockets and the calls no longer work.

You can easily reproduce it.

Run
`$LastExitCode=0; while ($LastExitCode -eq 0) { wsl echo hello }`

Then go into a WSL shell and run;
`ls /run/WSL/`

For every `wsl echo hello` a new socket has been created.

As a workaround, I added this to my `~/.bashrc`. If the command is run in an interactive mode, `.bashrc` is executed and the stale sockets are closed.
```
export WSL_INTEROP=
for socket in /run/WSL/*; do
   if ss -elx | grep -q "$socket"; then
      export WSL_INTEROP=$socket
   else
      rm $socket 
   fi
done

if [[ -z $WSL_INTEROP ]]; then
   echo -e "\033[31mNo working WSL_INTEROP socket found !\033[0m" 
fi
```

Credits for the cleanup script script from here: https://github.com/microsoft/WSL/issues/5065#issuecomment-919595625
