### ISSUE TITLE
wsl.exe executes command and returns to Windows

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#5347]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.264]
Your Distribution version: Ubuntu-20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

Every time I run `wsl.exe <cmd>` it executes the specified command and then returns to Windows prompt. Is there a way to execute some command without returning to Windows?

Only typing `wsl.exe` will show Linux prompt without extiing to Windows prompt.

**Comment by therealkenc** [comment]
```
wsl.exe bash -c "echo hello; exec /bin/bash"
```
