### ISSUE TITLE
WslRegisterDistribution failed with error: 0xc03a001a

### ISSUE THREAD

**Issue by sun-jiao** [microsoft/WSL#5355]
I got an error display error -- this is not a wordplay, I cannot get any information except '?????' from the error information.

![image](https://user-images.githubusercontent.com/14086980/83944169-0c848a80-a834-11ea-9a2d-e7cf0f471438.png)

System version: 2004 (19041.264)
WSL version: 2

**Comment by rescenic** [comment]
Try this:
1. Uninstall Distro WSL

2. cmd as admin:
```
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns
```

3. Windows Search > Network Reset

4. CCleaner (or any software) > Remove all temporary data

5. Restart Windows

6. Install Distro WSL again

**Comment by therealkenc** [comment]
Detailed logs, instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
