### ISSUE TITLE
Trying to access USB for arduino on COM3

### ISSUE THREAD

**Issue by fregas** [microsoft/WSL#5359]
I have an elegoo arduino uno r3 hooked up to windows 10.  from windows I can use the arduino IDE to upload to com3 no problem.  

![image](https://user-images.githubusercontent.com/362617/83956585-54e87c00-a825-11ea-9bf7-0cb6477419f8.png)

However, in WSL 2.0, using ubuntu 20.04, I can't seem to upload to that port.  Supposedly, COM3 becomes ttys3 on linux.  I have tried the following:

```
sudo chmod 666 /dev/ttyS3
arduino-cli upload -p /dev/ttyS3 --fqbn arduino:avr:uno .

avrdude: ser_open(): can't set attributes for device "/dev/ttyS3": Inappropriate ioctl for device
Error during Upload: uploading error: exit status 1
```

I've tried the cu command:

```
sudo cu -l /dev/ttyS3 --debug all
cu: fconn_open: Opening port /dev/ttyS3 (default speed)
cu: fconn_set: Changing setting to 0, 0, 2
Connected.
cu: Got hangup signal
cu: Exit status 0
cu: fconn_close: Closing connection

Disconnected.
```

I've tried setting the baud rate:

```
stty -F /dev/ttyS3 sane 9600
stty: /dev/ttyS3: Input/output error

```

any ideas what i'm doing wrong here?

**Comment by fregas** [comment]
Thanks all.

**Comment by josegpulido** [comment]
> 
> 
> Thanks all.
Did you find a solution?

**Comment by josegpulido** [comment]
> 
> 
> Thanks all.

Did you find a solution?
