### ISSUE TITLE
VMMEN eat all my ram and slow my processing

### ISSUE THREAD

**Issue by darkRaspberry** [microsoft/WSL#5360]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19635.1]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce
Open any distro start doing anything in distro

#  Expected behavior
Things should work smooth. Normal ram usses. 

# Actual behavior
VMMEN(an app in taskmanger and also in process) eat all my ram. Some time even 1 whole GB. This restrict me using other app, slow down whole UI of windows. I have to stop that process in taskmanger so that i can work normally. And this is very frustating

**Comment by squareloop1** [comment]
Possible duplicate: https://github.com/microsoft/WSL/issues/4166

**Comment by darkRaspberry** [comment]
@squareloop1 Its same.
