### ISSUE TITLE
WSL2 vEthernet is Missing WFP Conditions for FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4/V6

### ISSUE THREAD

**Issue by zx2c4** [microsoft/WSL#5364]
# Environment

```none
Windows build number: 10.0.19041.264
Your Distribution version: applies to all
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 - 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Description

I maintain a piece of software ([WireGuard for Windows](https://git.zx2c4.com/wireguard-windows/about/)) that, under certain conditions, installs ingress blocking rules of the variety `FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4/V6` + `FWP_ACTION_BLOCK`. There are certain exceptions to this rule, such as the UDP port that the VPN uses, localhost, dhcp, and a few other odds and ends. Standard situation, nothing too fancy.

Now, WSL2 appears to work by running a DNS forwarder on the default IP of `172.25.64.1`, which is written into `/etc/resolv.conf`, with requests forwarded over the vEthernet interface from the guest VM to the host. This seems like a reasonable setup, but there's one problem: that block rule.

Comments in various threads like https://github.com/microsoft/WSL/issues/4698#issuecomment-571589914 indicate that users are having issues. And indeed I can confirm that with the standard block rule above, the Linux VM cannot send any packets to the Windows host at `172.25.64.1`, which is to be expected.

However, it would seem the logical next step would to exempt ingress from WSL2 from hitting that block rule, only it doesn't appear that there are any conditions that are valid under `FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4/V6` for matching on those packets.

I've tried using `FWPM_LAYER_INGRESS_VSWITCH_TRANSPORT_V4/V6` + `FWPM_CONDITION_VSWITCH_NETWORK_TYPE==FWP_VSWITCH_NETWORK_TYPE_INTERNAL|PRIVATE`, but the vswitch layer does not appear to be triggered or interacting powerfully enough with the existing block rule on `FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4/V6`.

So, in order for VPN app writers to interact nicely with WSL2, we might need an additional condition flag, like `FWP_CONDITION_FLAG_IS_LOOPBACK`, that can be matched with the normal `FWPM_CONDITION_FLAGS` inside of `FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4/V6`.

cc @rozmansi @mvd-ows

**Comment by rjadidi920** [comment]
Any update?

**Comment by rjadidi920** [comment]
yes I am experiencing the same issue still.. not fixed even in 2024 good job Microsoft.
