### ISSUE TITLE
WSL2 won't load when loading with kernel with CONFIG_DM_ZERO & CONFIG_DM_SNAPSHOT

### ISSUE THREAD

**Issue by gaetanww** [microsoft/WSL#5366]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19631.1]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

I ran WSL2 with a custom built kernel, according to [these instructions](https://gist.github.com/offlinehacker/b1d96515f87a47bd0b0bea574eab5583).

I also added the following kernel options: 
```none
CONFIG_DM_ZERO=y
CONFIG_DM_SNAPSHOT=y
```
#  Expected behavior

I expected WSL to start.

# Actual behavior

WSL won't and I get the following errors in the Debug Console:

```none
[    1.818509] Run /init as init process
<3>ERROR: ConnectHvSocket:670: connect failed 19
[    1.824506] kvm: exiting hardware virtualization
[    1.829331] ACPI: Preparing to enter system sleep state S5
[    1.834333] reboot: Power down
[    1.846798] acpi_power_off called
```

**Comment by onomatopellan** [comment]
Can you upload the kernel you are using? Just rename the vmlinux file to vmlinux.txt and drag it to the message box here.

**Comment by benhillis** [comment]
ENODEV from the connect is strange, but I suspect somehow one or all of the CONFIG_VSOCKET config options got disabled.

**Comment by onomatopellan** [comment]
The problem is that the Kconfig from the repos is outdated and won't work with later insider builds. 

You can try this 4.19.121 kernel with CONFIG_DM_ZERO & CONFIG_DM_SNAPSHOT enabled:
[bzImage.txt](https://github.com/microsoft/WSL/files/4754357/bzImage.txt)

You can get the KConfig from the running kernel with `zcat /proc/config.gz > wsl-config` to see what config options were missing.

**Comment by gaetanww** [comment]
It is now working, thanks!

**Comment by zoe9216** [comment]
> Can you post the kernel you are using? Get the `bzImage` file from `WSL2-Linux-Kernel/arch/x86/boot`, rename it to `bzImage.txt` and drag it to the message box here.

I cant find bzImage file in the path you mentioned. Any idea how to get it?

**Comment by onomatopellan** [comment]
@zoe9216 You need to [compile the kernel](https://gist.github.com/cerebrate/d40c89d3fa89594e1b1538b2ce9d2720) and it will appear on that folder.

**Comment by zoe9216** [comment]
> @zoe9216 You need to [compile the kernel](https://gist.github.com/cerebrate/d40c89d3fa89594e1b1538b2ce9d2720) and it will appear on that folder.

I did. But from root rather than /mnt/c. Got the file `bzImage`.
