### ISSUE TITLE
How to install kali linux tools on D:/ Drive? i.e apt-get  install

### ISSUE THREAD

**Issue by Halamadrid777** [microsoft/WSL#5377]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

#  Expected behavior

# Actual behavior

**Comment by craigloewen-msft** [comment]
I second @WSLUser 's comments. I'll close this issue out as the bug template isn't completed, and we need that information in general to help resolve user issues.

**Comment by CreateSean** [comment]
Why isn't this in the documention? Also why isn't drive location an option to choose when installing WSL? This is a major oversight IMO. My C: Drive is small but I have a 4TB d drive that I do all work on and shouldn't have to come looking for bug reports to find a way to do this.
