### ISSUE TITLE
wslconfig file doesn't work

### ISSUE THREAD

**Issue by PeterRK** [microsoft/WSL#5383]
I want to limit the memory in wsl2 by creating wslconfig file. But it doesn't work.
<img width="252" alt="捕获" src="https://user-images.githubusercontent.com/4464013/84406463-25c67600-ac3c-11ea-8c32-5ce8a5ffcda1.PNG">
<img width="570" alt="Ubuntu" src="https://user-images.githubusercontent.com/4464013/84406511-370f8280-ac3c-11ea-90e1-192f7097dd3c.PNG">

[lxcore-logs.zip](https://github.com/microsoft/WSL/files/4765834/lxcore-logs.zip)
<img width="327" alt="版本" src="https://user-images.githubusercontent.com/4464013/84406499-337bfb80-ac3c-11ea-8dba-79edcd6e7d31.PNG">

**Comment by craigloewen-msft** [comment]
Hi @PeterRK could you please resubmit using the prescribed bug template? That helps us make sure we have all the info available to help resolve your issue. Thank you!

**Comment by PeterRK** [comment]
I fixed it by removing the BOM header.
