### ISSUE TITLE
wslconfig file doesn't work

### ISSUE THREAD

**Issue by PeterRK** [microsoft/WSL#5389]
I want to limit the memory in wsl2 by creating wslconfig file. But it doesn't work.

# Environment
Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Ubuntu 20.04
Linux version 4.19.104-microsoft-standard

# Steps to reproduce
Follow [the document](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
<img width="252" alt="捕获" src="https://user-images.githubusercontent.com/4464013/84406463-25c67600-ac3c-11ea-8c32-5ce8a5ffcda1.PNG">
<img width="570" alt="Ubuntu" src="https://user-images.githubusercontent.com/4464013/84406511-370f8280-ac3c-11ea-90e1-192f7097dd3c.PNG">

#  Expected behavior
Memory in WSL2 can be limited.

# Actual behavior
WSL2 may consume memory more than expected.

**Comment by PeterRK** [comment]
I need helps to debug whether the wslconfig is loaded.

**Comment by therealkenc** [comment]
Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.

![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)

**Comment by PeterRK** [comment]
> Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.
> 
> ![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)

**Comment by PeterRK** [comment]
> > Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.
> > ![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)

I fixed it by removing the BOM header.
Thank you!

**Comment by PeterRK** [comment]
> Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.
> 
> ![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)

**Comment by PeterRK** [comment]
I fixed it by removing the BOM header.
Thank you!

**Comment by PeterRK** [comment]
> Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.
> 
> ![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)

**Comment by PeterRK** [comment]
I fixed it by removing the BOM header.
Thank you!

**Comment by PeterRK** [comment]
> Can't repro here. There is [some lore](https://github.com/microsoft/WSL/issues/4193#issuecomment-632732442) that the file is sensitive to whitespace (crlf) but I couldn't make it break changing that personally either.
> 
> ![image](https://user-images.githubusercontent.com/7049700/84466019-41765000-ac2d-11ea-954b-f754c0b810db.png)
I fixed it by removing the BOM header.
Thank you!

**Comment by PeterRK** [comment]
I fixed it by removing the BOM header.
Thank you!

**Comment by victorfeagins** [comment]
The problem I had is when I created the .wslconfig file in notepad it saved it as a text file with the extension .txt so I had to remove .txt to make it take effect

**Comment by neojob** [comment]
To solve the problem, you need to check if the file is named ".wslconfig.txt" and remove the ".txt" extension if it exists. Renaming the file to ".wslconfig" will resolve the issue.

**Comment by Josuecriollo** [comment]
I created the notepad file without the extension (.txt) and I still get the  default values. when I check the .wslconfig properties, it says the type is a "Text Document" is this file supposed to be saved with a different extension?

**Comment by alv-tor** [comment]
> I created the notepad file without the extension (.txt) and I still get the default values. when I check the .wslconfig properties, it says the type is a "Text Document" is this file supposed to be saved with a different extension?

Had the same issue. Yes, it seems to have something to do with it. Creating the file from Terminal (cd to C:/User/USERNAME directory and nano .wslconfig) created the file with the right file type. After it WSL applied the established configuration.

**Comment by Josuecriollo** [comment]
@alv-tor dumb question but what do you mean by nano .wslconfig? Also, i tried to save it as "all files" instead of text file and that did not help either

**Comment by alv-tor** [comment]
> @alv-tor dumb question but what do you mean by nano .wslconfig? Also, i tried to save it as "all files" instead of text file and that did not help either

I mean that creating directly a new file “.wsconfig” worked for me. I did it directly in Terminal by running the command “nano .wsconfig”. Hope it helps.

**Comment by Afrin127329** [comment]
The easiest way is, 

1. open Users/<Your Folder> inside vscode

**Comment by Abdiaziz76** [comment]
> The easiest way is,
> 
> 1. Open Users/ inside Vscode
> 2. Open the config file
> 3. Remove the .txt extension by renaming manually or press F2 for renaming
> 4. Open terminal
> 5. Run `wsl --shutdown`
> 6. Run `wsl free -m` for checking the memory allocation is okay or not
> 
> Thanks

Best Answer!!💯

**Comment by andreluiz901** [comment]
Since I found this searching by google, just want to say that, on Windows u need to create a file with LF and not CRLF chars. Every txt file i created was using CRLF, and i never changed my wsl2 memory allocation. So, i need to create a file on the wsl environment, and copy this .wslconfig to my C:user 

and finally thjis worked for me.

**Comment by skbtwiz** [comment]
Just want to add my two cents here, I have a simple and easy way to fix this issue for .wslconfig and .wslgconfig files.

Simply install dos2unix package using winget by typing 

```powershell
winget install dos2unix
``` 
This will also install a bunch of aliases under the same tool like unix2dos, mac2unix, and unix2mac. These commands essentially convert file formats from one OS to another.

Then after you make or modify your .wslconfig or .wslgconfig files in notepad or nano (PowerShell version), just run 
```powershell
dos2unix .wslconfig
``` 
or 
```powershell
dos2unix .wslgconfig
```
AND THAT'S IT! 

Your config files will now be read by WSL just fine, no issue. No need to bother with creating/modifying the files inside the WSL environment and having to copy them over.
