### ISSUE TITLE
WSL Kernel update installer doesn't recognize WSL installation

### ISSUE THREAD

**Issue by selfagency** [microsoft/WSL#5390]
# Environment

```none
Windows build number:  Win32NT 10.0.19645.0 Microsoft Windows NT 10.0.19645.0
Your Distribution version: Ubuntu 1804.2020.423.0
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

All I do is open Ubuntu to install (after uninstalling it to troubleshoot) and I get the message that I need to update the WSL kernel. However, when I run the installer, it says that the installer is only for systems running WSL and then sends me to quit. WSL is activated in the "Turn Windows features on or off" dialog and worked prior to today.

![Annotation 2020-06-11 205758](https://user-images.githubusercontent.com/2541728/84453859-f0635d80-ac26-11ea-8932-fdabc15858f7.png)

![Annotation 2020-06-11 205758 2](https://user-images.githubusercontent.com/2541728/84453902-0a9d3b80-ac27-11ea-97c4-82dc46063c52.png)

#  Expected behavior

For the kernel update installer to work.

# Actual behavior

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
```

![Annotation 2020-06-11 205758 4](https://user-images.githubusercontent.com/2541728/84453878-fb1df280-ac26-11ea-936e-00c1806da34b.png)

Run the installer at the above URL:
```
This update only applies to machines with the Windows Subsystem for Linux.
```

![Annotation 2020-06-11 205758 3](https://user-images.githubusercontent.com/2541728/84453889-0113d380-ac27-11ea-904f-e5a172c9ac7c.png)

**Comment by psgrove** [comment]
I had this had to right click on installer and unistall first and then install, this is becuase I had previously done an update then moved to an insider edition release

**Comment by jaysonsantos** [comment]
@psgrove that also worked for me, the error message on the installer stopped showing.

**Comment by selfagency** [comment]
Thanks @psgrove, that did the trick!
