### ISSUE TITLE
Windows 10 Update KB4557957 breaks WSL2

### ISSUE THREAD

**Issue by christianhuening** [microsoft/WSL#5392]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Install KB4557957
2. Reboot
3. WSL2 does not start anymore and produces no error. The command just hangs.
4. Uninstall KB4557957 again
5. Reboot
6. WSL2 starts as usual

#  Expected behavior

After having installed Windows 10 Patch KB4557957, WSL2 starts as usual.
# Actual behavior

After having installed KB4557957, WSL2 does not start at all anymore.

**Comment by straight-shoota** [comment]
I have a similar issue (probably the same cause), also after installing KB4557957.
The problem for me seems to be that mounting the drives from windows doesn't work. So WSL actually runs and I can enter it, but it can't access the windows drives:
```console
C:\Users\Johannes>bash
johannes@local:~ ls /mnt/c
johannes@local:~
```
What other information would be helpful?

**Comment by craigloewen-msft** [comment]
Hi there! Could you please upload logs for when you're hitting this error? Instructions are [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). Thank you!

**Comment by straight-shoota** [comment]
Okay, here are the logs: [logs.zip](https://github.com/microsoft/WSL/files/4789286/logs.zip)

It did start wsl, exec `ls /mnt/c` (empty dir) and then tred to run mintty using `%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~  -` which fails with the following error (I assume it's caused by the failed drive mount):
```
/bin/wslbridge2: Exit 1.
note: backend error output: wslpath: C:\Users\Johannes\AppData\Local\wsltty\bin\wslbridge2-backend
/bin/sh: 1: exec: : Permission denied
```

Btw. rolling back KB4557957 did not help in my case. So maybe it's even a different issue than the OP...

**Comment by straight-shoota** [comment]
Not sure if its relevant but while WSL2 basically works for me (I can do most of my typical things, just some integrations like VS Code and mintty are broken), it seems `fstab` and `mount` are missing:
```console
$ mount
Command 'mount' not found, but can be installed with:

sudo apt install mount
$ fstab
fstab: command not found
```

**Comment by christianhuening** [comment]
So i updated again to the KB patch and the issue is gone. No idea why, but now everything is working. for me mount also works from within my ubuntu WSL2 "machine"
