### ISSUE TITLE
WslRegisterDistribution failed with error: 0x800701bc

### ISSUE THREAD

**Issue by Silver-Fang** [microsoft/WSL#5393]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19645.0 Microsoft Windows NT 10.0.19645.0
CentOS8.1
WSL2
```

# Steps to reproduce
Install CentOS 8.1 in Microsoft Store. Then launch it. 

#  Expected behavior

First-launch install succeeds.

# Actual behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel

Press any key to continue...

**Comment by lengthmin** [comment]
go to https://aka.ms/wsl2kernel.
then download and install the Linux kernel update package:
![image](https://user-images.githubusercontent.com/13938334/84507666-c4fa7480-acf3-11ea-8377-571c4e7dcd50.png)

**Comment by craigloewen-msft** [comment]
Hi @Silver-Fang , did you follow the instructions that @lengthmin put? Were you able to install that kernel version and get it working?

**Comment by zhanghuizong** [comment]
I have the same problem

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel

Press any key to continue...
```

It also tries to upgrade the kernel, which is still invalid


![image](https://user-images.githubusercontent.com/4384876/84847870-a514d900-b084-11ea-84bb-f2bbc0f3a938.png)

![image](https://user-images.githubusercontent.com/4384876/84847927-beb62080-b084-11ea-9efa-665db144cdec.png)

![image](https://user-images.githubusercontent.com/4384876/84847886-ae9e4100-b084-11ea-8111-8fa4384c2137.png)

**Comment by zhanghuizong** [comment]
> I have the same problem
> 
> ```
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x800701bc
> Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel
> 
> Press any key to continue...
> ```
> 
> It also tries to upgrade the kernel, which is still invalid
> 
> ![image](https://user-images.githubusercontent.com/4384876/84847870-a514d900-b084-11ea-84bb-f2bbc0f3a938.png)
> 
> ![image](https://user-images.githubusercontent.com/4384876/84847927-beb62080-b084-11ea-9efa-665db144cdec.png)
> 
> ![image](https://user-images.githubusercontent.com/4384876/84847886-ae9e4100-b084-11ea-8111-8fa4384c2137.png)

**Supplementary notes:**

Secondary problem due to win10 update, uninstall wsl_update_x64.msi, it's normal when reinstalling.

**Comment by divinerapier** [comment]
Updating the Linux kernel is helpful to me. 👍

**Comment by duocang** [comment]
SOLVED!

[Please download the latest WSL2 Linux kernel update package for x64 machines.](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

**Comment by WindSnowLi** [comment]
> 去[https://aka.ms/wsl2kernel。](https://aka.ms/wsl2kernel)
> 然后下载并安装 Linux 内核更新包：
> ![image](https://user-images.githubusercontent.com/13938334/84507666-c4fa7480-acf3-11ea-8377-571c4e7dcd50.png)

This is a successful solution.Thank you

**Comment by heitordeve** [comment]
> RESOLVIDO!
> 
> [Baixe o pacote de atualização do kernel WSL2 Linux mais recente para máquinas x64.](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

This solution worked : )

**Comment by iEclisse** [comment]
In Windows 11 you should
```
wsl --update
wsl --shutdown
```

run WSL dist

**Comment by rediffusion** [comment]
I do all steps as shown [here](https://docs.microsoft.com/ru-ru/windows/wsl/install-win10) and it's helpful❗

**Comment by Gaudriol** [comment]
I followed all the steps [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I installed the WSL2 Linux kernel update package. But I still can't install any linux distribution through the Microsoft Store.

I still have the error : `WslRegisterDistribution failed with error: 0x800701bc`

**Comment by paul2048** [comment]
Enabling Virtual Machine Platform fixed the error for me.
![image](https://user-images.githubusercontent.com/23298862/138331445-ba0cb9f9-a2c7-47d9-a375-60b16fb0098a.png)

**Comment by LonelyGuy12** [comment]
You can just try using `wsl --update` with admin privileges in Command Prompt. And then `wsl --shutdown`. This solved the issue for me

**Comment by parthdedaniya** [comment]
> 

this also worked for me

**Comment by a1g0r1thm** [comment]
No one advice worked for me ((( But I finded my own way. You need to activate Hyper-V in Windows components and run in Power Shell next command:

**Comment by Gabriel-Negreiro-ey** [comment]
> RESOLVIDO!
> 
> [Baixe o mais recente pacote de atualização do kernel WSL2 Linux para máquinas x64.](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

thx bro

**Comment by anjaysahoo** [comment]
https://www.thewindowsclub.com/error-0x80370102-the-virtual-machine-could-not-be-started

This helped me solving above issue

**Comment by Hercute** [comment]
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

Installing this update Worked for me ! thank you !

**Comment by JaggarYussef** [comment]
> 

Of all instructions, this has solved my problem! I had this issue on a Dell laptop (just putting it out there)
Thanks

**Comment by JaggarYussef** [comment]
> No one advice worked for me ((( But I finded my own way. Go to BIOS and turnOn Virtualization Technology. Then you need to activate Hyper-V and Virtual Machines in Windows components(features) and run in Power Shell next command: _wsl --set-default-version 1_. How I understand it, last needs because my processor not have SomeLowLevelCommands ((( After last command install will be done! And after good install you can change back for WSL2: wsl --set-default-vers 2. And it works perfect for me. But I am not understand fully how ))) Oh, my god, half of my sunday ((( We live in notSimpleTime ))))) GoodLuck, guys!

Of all instructions, this has solved my problem! I had this issue on a Dell laptop (just putting it out there)
Thanks

**Comment by Sdator** [comment]
I'll add another easy-to-forget solution that may be caused by the fact that you don't have virtualization enabled in the bios

**Comment by bhaktar** [comment]
Try wsl -l -v
wsl -t Ubuntu
Get-Service LxssManager | Restart-Service

Restarting the LxssManager service fixed the problem for me

**Comment by aneshwar** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

**Comment by dorp007** [comment]
Thanks dude!

**Comment by Kyogre** [comment]
got errors 0x80370102 and 0x800701bc too in my VMware Windows 10 virtual machine.
The solution was: shutdown VM -> enable "Virtualize Intel VT-x/EPT or AMD-V/RVI" in VMs settings -> start VM -> enable all Hyper-V checkboxes in "Windows Features" window -> run `wsl --install -d <distro>` again.

**Comment by PraveenShaun** [comment]
> wsl --update
> wsl --shutdown
Run these 2 line of codes one by one at Windows terminal to fix the issue

**Comment by mayuehit** [comment]
> > wsl --update
> > wsl --shutdown
> > Run these 2 line of codes one by one at Windows terminal to fix the issue

This works for me

**Comment by AhanafRASHID** [comment]
> go to https://aka.ms/wsl2kernel. then download and install the Linux kernel update package: ![image](https://user-images.githubusercontent.com/13938334/84507666-c4fa7480-acf3-11ea-8377-571c4e7dcd50.png)

Thanks Brother. It actually worked!

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by StrongBearCeo** [comment]
enabling Virtualization in Bios worked for me

**Comment by HanzalaOP** [comment]
[Baixe o pacote de atualização do kernel WSL2 Linux mais recente para máquinas x64.](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)
this solution worked for me in (KALI LINUX)

**Comment by Themorningcormorant** [comment]
wsl --update
wsl --shutdown

this worked for me on windows 10

**Comment by Themorningcormorant** [comment]
> If someone have trouble in Windows 11 you should:
> 
> ```
> wsl --update
> wsl --shutdown
> ```
> 
> run WSL dist

thanks, this worked for me on windows 10

**Comment by 9gold241** [comment]
To solve this problem, type this command:
wsl - set default version 1

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by ThomazPom** [comment]
> If someone have trouble in Windows 11 you should:
> 
> ```
> wsl --update
> wsl --shutdown
> ```
> 
> run WSL dist

This was the one ! Thank you !!!

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by Adtrex** [comment]
> No one advice worked for me ((( But I finded my own way. Go to BIOS and turnOn Virtualization Technology. Then you need to activate Hyper-V and Virtual Machines in Windows components(features) and run in Power Shell next command: _wsl --set-default-version 1_. How I understand it, last needs because my processor not have SomeLowLevelCommands ((( After last command install will be done! And after good install you can change back for WSL2: wsl --set-default-vers 2. And it works perfect for me. But I am not understand fully how ))) Oh, my god, half of my sunday ((( We live in notSimpleTime ))))) GoodLuck, guys!

This works for me

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by xlinbo** [comment]
> SOLVED!
> 
> [Please download the latest WSL2 Linux kernel update package for x64 machines.](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

Very helpful, thank you for your suggestion!

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by Aamir-Shahzadah** [comment]
Thank bro

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by Artxcod** [comment]
Updating Kernel helped for me, thanks guys.

**Comment by Furkan-C-Aydin** [comment]
> Enabling Virtual Machine Platform fixed the error for me. ![image](https://user-images.githubusercontent.com/23298862/138331445-ba0cb9f9-a2c7-47d9-a375-60b16fb0098a.png)




Thanks buddy

**Comment by Vrinik** [comment]
> go to https://aka.ms/wsl2kernel. then download and install the Linux kernel update package: ![image](https://user-images.githubusercontent.com/13938334/84507666-c4fa7480-acf3-11ea-8377-571c4e7dcd50.png)

thanks its helpful to me

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。

**Comment by macknight** [comment]
wsl --update

**Comment by crystoneme** [comment]
good works for me,thkxxx

**Comment by mayuehit** [comment]
您好，您的邮件已收到，我会尽快给您回复，谢谢。
