### ISSUE TITLE
Attach vhdx file to make docker desktop mysql container work

### ISSUE THREAD

**Issue by starwing** [microsoft/WSL#5394]
**Is your feature request related to a problem? Please describe.**
I'm using Hyper-V for host nextcloud, and it needs a mysql to host data.  Now I want use Docker Desktop with WSL2 backend directly, but I meed some trouble: the mysql container can not start, because it can out reallocate the bin-log file with error 95: it need a ext4 partition for work.

**Describe the solution you'd like**
I've made a vhdx file for nextcloud before, so it will work if WSL2 just support mount a vhdx file for data. But I cannot find a way to do this.

**Describe alternatives you've considered**
Maybe just mount ext4.vhdx in VM and copy data to WSL2 disk will work, but it fails even I terminated the wsl2.

I found other request for this feature: #4574 #4556 and reddit post [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/cwrrog/how_to_attach_additional_vhdx_to_wsl2s_vm/), but no luck for now :(

**Comment by therealkenc** [comment]
There is not enough specificity to turn this into any kind of actionable different than /dupe #4556. If #4556 flips and your scenario (whatever it may be) is not addressed then it can be revisited then. You'll get way better help/suggestions on how or why your scenario is failing and/or possible ways to get it to work in a forum related to those packages.
