### ISSUE TITLE
Random X session crashes after upgrading distro to version 2

### ISSUE THREAD

**Issue by janvgils** [microsoft/WSL#5396]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Your Distribution version: Release:        10
WSL 2, Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

This is the tricky part because it is happening randomly and no way to force the problem.
I'll describe the setup before and after the WSL 2 update:

WSL 1: X410 X server run and the distro (debian buster) is connecting (gnome-terminal) via the export DISPLAY=localhost:0.0 variable.
This has been working fine for months now without any problems.

WSL 2: Same setup and now randomly the session crashes, it no longer shown and usable on the desktop. Sometimes it is enough to restart the gnome-terminal and sometimes I need to restart the X server. To make sure it isn't a X server problem I also tried VcVsrv and the issue is the same.

I did the following to move the distro to version 2

wsl --set-version <distro name> 2 and afterwards changed to DISPLAY setting from localhost to the host IP and disabled X server access control.

Because the behaviour wasn't acceptable I converted the distro back to version 1 and now the X session is already up for more then 24 hours.

#  Expected behavior

Keep the X session running until me the user stops it.

# Actual behavior

The X session crashes randomly.

**Comment by janvgils** [comment]
Is the label an indicator that I should add some information?

**Comment by gitbls** [comment]
@therealkenc this sounds like a potential me2 for [xterm crashes](https://github.com/microsoft/WSL/issues/5339)

**Comment by therealkenc** [comment]
I hesitated to dupe right of the gate, but agree. Call it /dupe #5339 for lack.
