### ISSUE TITLE
WSL 2 -  linux icon is missing from explorer

### ISSUE THREAD

**Issue by dfsantamaria** [microsoft/WSL#5400]
Steps:
- Upgrading to Windows 10 May Update.
-Upgrading to WSL 2.
-Installing a fresh Ubuntu 20.4 LTS.
-Make sure that  `wsl --list -v` shows a WSL 2 Ubuntu distribution.

Result:
No linux icon is showing in explorer.

I have no idea how to solve.

**Comment by therealkenc** [comment]
Does `\\wsl$` from the explorer bar work? Assuming 'yes' but just want to confirm it is just the icon not the functionality that is missing.

No guess as to why you didn't get the icon. You can get pretty close to the same idea (but without the penguin) by dragging `\\wsl$` into Quick Access. It might come back if your remove the WSL optional feature and then re-add it, but don't do that unless you feel like starting over anyway and have nothing to lose. It might sort itself on a windows update (sometimes quirks do).

**Comment by 0xbadfca11** [comment]
The icon was [added to the active development branch](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/) ahead of May 2020 Update(19041), so it seems normal that there is no icon.

**Comment by dfsantamaria** [comment]
Considering that

> The icon was [added to the active development branch](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/) ahead of May 2020 Update(19041), so it seems normal that there is no icon.

and that  `\\wsl$` works correcly, I may consider this topic closed.

**Comment by okibcn** [comment]
Issue found with the current [Windows Subsystem for Linux Preview](https://www.microsoft.com/store/productId/9P9TQF7MRM4R)  from MS store. Installed it after installing [Ubuntu 20.04 LTS](https://www.microsoft.com/store/productId/9N6SVWS3RX71) also from Microsoft Store.

The Linux icon in Explorer is missing.

The workaround for that is to add a quick link to the distribution using the link \\wsl$\Ubuntu-20.04 or \\wsl.localhost\Ubuntu-20.04

Anyway, the icon should be there and it isn't. Is there any way to add it manually?

This is the relevant WSL info:
WSL version: 0.51.2.0
Kernel version: 5.10.81.1
WSLg version: 1.0.30
Windows version: 10.0.22000.469

It also happens in another W11 prerelease build 22543 from the dev insiders channel.

**Comment by Raghav-Bell** [comment]
I am facing same issue after updating Windows 11 with KB5011493 ,KB4023057 etc. 
when i run on Command Prompt :
`wsl -l -v`
it showed me ubuntu state - stopped and Version 2
But when i run on Command Prompt 
`wsl`
it started wsl instance.

MS Windows Version 21H2(OS Build 22000.556)

**Comment by intexcor** [comment]
та же проблема

**Comment by bilal-akbar-9** [comment]
Guide to get the icon in **windows 11**, but the process should be somewhat similar to windows 10 as well.
1. Click on the following icon and choose "Add a network location"
![image](https://github.com/microsoft/WSL/assets/94855224/45720733-1957-4c59-b7ac-a1b171dca146)
2. Choose a custom network location and add "\\wsl.localhost\<distroname>" e.g., "\\wsl.localhost\Debian".
![image](https://github.com/microsoft/WSL/assets/94855224/17ed000c-26fc-4d2a-85ff-e0a19d48c625)
And the network location will appear in the file explorer 
![image](https://github.com/microsoft/WSL/assets/94855224/52569e39-1324-47dc-8b82-69eee34a79f5)

**Comment by intexcor** [comment]
было исправлено в недавнем обновлении
