### ISSUE TITLE
Able to access server running in a different user logged in into the same system.

### ISSUE THREAD

**Issue by vijaybritto** [microsoft/WSL#5402]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: 1
```

# Steps to reproduce
1. Start a node.js server in port 3000 in a user's WSL.
2. log off and login into another user in the same system.
3. Access localhost:3000 in the current user's browser.

#  Expected behavior
Not be able to access other user's web servers running in wsl

# Actual behavior
Able to access localhost:3000 running in a different user in the same machine. Shouldnt it be blocked? Does it have something to do with WSL being a shared resource for all users?
I have installed Ubuntu separately for both users.

**Comment by therealkenc** [comment]
> Shouldnt it be blocked?

No that is by-design. And unrelated to WSL. You will get the same behavior if you were to start a service on port 3000 in Windows (with nodejs or otherwise).

> Does it have something to do with WSL being a shared resource for all users?

It has to do with localhost being a shared resource on your computer.
