### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102

### ISSUE THREAD

**Issue by songroom2016** [microsoft/WSL#5405]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 ???????????????????

Press any key to continue...

**Comment by songroom2016** [comment]
Ubuntu1804, debian etc, all same error

**Comment by Akhee123** [comment]
this issue is not new now but it seems to appear alot with the stable release of wsl2

**Comment by songroom2016** [comment]
it is ok aftering setting  BIOS visualiztion technology enabled.

**Comment by Zhangfushan19** [comment]
setting name misspelled and it should be Virtualization Technology

**Comment by mrlalley** [comment]
I would love to know if anyone resolved this?
