### ISSUE TITLE
Cannot create default UNIX user account on Kali linux WSL2, "There is no distribution with the supplied name."

### ISSUE THREAD

**Issue by iiiklox** [microsoft/WSL#5409]
# Environment

```none
Windows build number:  Microsoft Windows NT 10.0.19041.0
Your Distribution version: Debian Kali Linux v1.1.4.0
Whether the issue is on WSL 2 and/or WSL 1: I have wsl2 as default, ubuntu returns "Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020" but I can't access Kali's terminal ;-;
```

# Steps to reproduce

On a fresh install of windows 10 version 2004, following microsoft's wsl2 installation guide, I managed to set wsl2 as my default and tried installing Kali Linux from the Microsoft store, after going through the store's own hell of bugs I got Kali linux to download all good till now..

Once I launched Kali from the start menu live tile it started installing.
couple of minutes passed and I got promoted to create a UNIX user account, and here is where it happened.. no matter what I enter, I always get `There is no distribution with the supplied name.`

I tried installing Ubuntu, seemed to run fine it installed and I got to create a new user account there so the problem really is from Kali only, or unless it's Microsoft store issue which I believe it's unlikely to be the reason. 

#  Expected behavior

Create a new UNIX account and password, Tried a couple hundred username ngl, It also blocks installation so I couldn't even do anything terminal related for Kali Linux.

# Actual behavior

```none
Installing, this may take a few minutes...
There is no distribution with the supplied name.
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: klox
There is no distribution with the supplied name.
Enter new UNIX username: uh
There is no distribution with the supplied name.
Enter new UNIX username: please work?
There is no distribution with the supplied name.
Enter new UNIX username: somelongname
There is no distribution with the supplied name.
Enter new UNIX username: smolnme
There is no distribution with the supplied name.
Enter new UNIX username: yeah this isn't going to work lol
There is no distribution with the supplied name.
Enter new UNIX username:
```

# Also

Hey! you guys are truly amazing, being part of this tools development is like writing history, keep going and I wish you have a hella awesome day! <3

**Comment by therealkenc** [comment]
Can't reproduce here

![image](https://user-images.githubusercontent.com/7049700/84698544-cea6f680-af04-11ea-9fc9-7fe2d0d10bee.png)

**Comment by MK3247** [comment]
How did you guys solve it? I am having the same issue and I can see where you stated the solution.

**Comment by r-asou** [comment]
> How did you guys solve it? I am having the same issue and I can see where you stated the solution.

@WMKCharles `netsh winsock reset`

Then restart. Then type wsl. fin!
