### ISSUE TITLE
Can I use Windows Terminal to "Launch" WSL?

### ISSUE THREAD

**Issue by rgparis** [microsoft/WSL#5411]
Feature Request: Looking to confirm that while using Windows Terminal that I can (our team) launch the WSL Bash shell.

**Comment by DHowett** [comment]
Yep!

Terminal can launch any text-mode executable that is already supported by the system.

Are you having a specific issue?

**Comment by rgparis** [comment]
Just convincing mgmt that developers could benefit

**Comment by MrTomasz** [comment]
```
        {
            "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "hidden": false,
			"fontFace" : "Consolas",
			"fontSize" : 10,
			"cursorShape" : "filledBox",
            "name": "Ubuntu-18.04",
            "source": "Windows.Terminal.Wsl"
        },
```
