### ISSUE TITLE
VSFTPD 500 OOPS: priv_sock_get_cmd

### ISSUE THREAD

**Issue by shungabubus** [microsoft/WSL#5412]
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020

# Steps to reproduce
It used to work fine, but since I haven't touched for a while I made a mistake and updated the system: **apt update** and **apt upgrade**. 
Since I did that the command doesn't work:
**FTP localhost**

#  Expected behavior
Prompt for user name

# Actual behavior
C:\Users\myuser>ftp localhost
Connected to mymachine.
500 OOPS: priv_sock_get_cmd
Connection closed by remote host.

Hint:
Tried this solution but did not work. From the explanation I would guess the same is happening here.
https://www.suse.com/support/kb/doc/?id=000018939

**Comment by therealkenc** [comment]
Gleaning/guessing your scenario, you want these two lines at the end of /etc/vsftpd.conf
```
seccomp_sandbox=NO
isolate_network=NO
```

WSL1 does not have `CLONE_NEWNET` (one that `vsftpd` is happy with, anyway). For sandboxed scenarios, you'll get better mileage on WSL2.

**Comment by shungabubus** [comment]
Hello, brilliant, many thanks. :)

**Comment by maxprehl** [comment]
Thanks for the tip! Really wanted to wireshark some vsftpd traffic locally.  WSL2 was causing network-related issues (i think windows firewall was blocking the incoming traffic?).  WSL1 with this config worked for me!
