### ISSUE TITLE
WSL Conversion failing with wsl conversion fail 4294967295 

### ISSUE THREAD

**Issue by BinaryVixen899** [microsoft/WSL#5415]
# Environment

```
Microsoft Windows [Version 10.0.19041.329]
Release:        18.04
WSL 1 
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

```

# Steps to reproduce
Originally when launching this command I received the message about a kernel update being needed. I downloaded the provided binary, installed it, restarted, still had WSL2. Tried upgrading with the command, got this. 

lealac@Kira:~$ wsl.exe --set-version Ubuntu 2
The Windows Subsystem for Linux instance has terminated.

[process exited with code 4294967295]

I am doing this in Windows Terminal
Doing it outside of Windows Terminal just instantly closes whatever terminal is used

Logs: https://gist.github.com/BinaryVixen899/88f7502fb0adea90bba7a81eb0d7695e

#  Expected behavior

Expecting WSL to go from 1 to 2

# Actual behavior

Process terminates, no upgrade

**Comment by BinaryVixen899** [comment]
Logs https://gist.github.com/BinaryVixen899/88f7502fb0adea90bba7a81eb0d7695e

**Comment by Biswa96** [comment]
Did you run the wsl.exe command inside the running WSL distribution? First close the running wsl.exe window and run the command from another command prompt window. If that didn't work try with another distribution.

**Comment by therealkenc** [comment]
> Did you run the wsl.exe command inside the running WSL distribution?

Yep, that's it good catch Bis.

```
81    execve("/mnt/c/Windows/system32/wsl.exe", ["wsl.exe", "--set-version", "Ubuntu", "2"], 0x7fffde0228d0 /* 22 vars */) = 0
```

**Comment by BinaryVixen899** [comment]
Whoops that was it, thanks Biswa!
