### ISSUE TITLE
DNS lookups causes BSOD on 2019 server

### ISSUE THREAD

**Issue by SomKen** [microsoft/WSL#5417]
I recently upgraded my 2016 standard server to 2019 because of WSL. However, anytime I attempt to run apt, for example, the server would BSOD 100% of the time. I then tried using nslookup and found any dns query to the local DNS on my Active Directory server would cause the problem.

The problem seems to be with DNS running on the local server.

# Environment
Windows Server 2019 Standard - 1809 (17763.1)
Ubuntu 18.04
Active Directory domain controller 

# Steps to reproduce
1. Open a shell in Ubuntu 18.04 with WSL,
2. Open nslookup 
3. Type "server 127.0.0.1" to make sure nslookup uses the local DNS server to resolve
4. Type "github.com" and observe bluescreen.

#  Expected behavior
DNS resolution working correctly

# Actual behavior
BSOD observed anytime using local DNS server for DNS lookup

**Comment by SomKen** [comment]
Any updates?

https://www.youtube.com/watch?v=PxLxwQnl4k8

Video of it happening. Happens with any IP that resolves on the DC. Doesn't have this issue if it uses other DNS servers

**Comment by lyt0802** [comment]
Hi, I'm actually running into a very similar issue as well, and I have the same environment setup as what you listed above, how did you come to resolve this issue?

**Comment by SomKen** [comment]
> Hi, I'm actually running into a very similar issue as well, and I have the same environment setup as what you listed above, how did you come to resolve this issue?

I ended up finding out that Windows Server wasn't updating and I had to update it directly from the .msu's. Once I did that, I haven't ran into this problem again. 

Same server is currently running build 1809 (17763.3346)
