### ISSUE TITLE
Ability to use gdb to debug core dumps through visual studio WSL/WSL2 or SSH connection

### ISSUE THREAD

**Issue by code12smonkey** [microsoft/WSL#5419]
**Is your feature request related to a problem? Please describe.**
The feature request is to lower the "barrier to entry" for our developers to debug linux core dumps that come from our public test environment servers.

**Describe the solution you'd like**
It is great that we can use WSL or WSL 2.0 to run & debug a local linux compiled server on our windows desktops, but when debugging core dumps that have been generated due to a linux server crash, we still have to open a bash terminal and use gdb to debug the contents of the core dump.
We would like the ability to specify a core-dump file that would be parsed with the program executable for the gdb commandline (E.g. gdb "exe" "core-dump-file"), which would then allow the core-dump to be loaded into gdb, and then each thread examinable via the Visual Studio debugger rather than the WSL gdb debugger.

**Describe alternatives you've considered**
Alternatives so far have been other GUI based gdb wrapper applications (E.g. VisualGDB, gdbgui, etc.). Since these are priced per-seat they are not easily scaleable and add an extra level of abstraction to the debugging of core dump files that we would prefer to simplify.

**Additional context**
I would guess a project setting "Core Memory dump file" "string" entry field would make sense under the GDB Debugger / Remote GDB Debugger project flavour property pages

**Comment by lightmelodies** [comment]
https://code.visualstudio.com/docs/cpp/cpp-debug#_memory-dump-debugging

**Comment by code12smonkey** [comment]
We use Visual Studio Professional (not Visual Studio Code) and so our projects do not have a launcher.json file auto-generated for them. Am I missing something, or should we be moving to Visual Studio Code?

**Comment by therealkenc** [comment]
All the cool kids seem to be using VS Code these days with either [vscode-cpptools](https://github.com/microsoft/vscode-cpptools) or [vscode-lldb](https://github.com/vadimcn/vscode-lldb). Visual Studio has their [Visual C++ for Linux](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=vs-2019) workload. None of those products are owned by the WSL team.
