### ISSUE TITLE
How does one log printk messages to troubleshoot a failed boot

### ISSUE THREAD

**Issue by rcwoolley** [microsoft/WSL#5421]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Yocto Project / OpenEmbedded
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I was successful in booting a custom built WSL2-Linux-Kernel and I am trying to boot a custom Yocto kernel in WSL 2.

I enabled the kconfig options listed here: https://www.funtoo.org/HyperV_Kernel_Configuration

Unfortunately, when I try to restart wsl2 with the new kernel it just gives me:

C:\Users\Rob>wsl -d Ubuntu
Error: 0x80041001

I tried looking in Event Viewer but could not find any error messages.  I also tried collecting the detailed logs  (https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs ) and viewing the attached files in Windows Performance Analyzer.  I could see the error trace event but couldn't ascertain the cause of the failure.

[lxss.zip](https://github.com/microsoft/WSL/files/4786894/lxss.zip)

Is there some way to see the printk output from the Linux kernel?

Thanks for the help,
Rob

**Comment by benhillis** [comment]
This feature is available in Insider builds:

%userprofile%\.wslconfig

[wsl2]
debugConsole=true

**Comment by rcwoolley** [comment]
Thanks,  I was able to use debugConsole successfully on Windows 10 Pro Insider Preview 19619.
