### ISSUE TITLE
WSL2 Inotify not working

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/WSL#5424]
Issue:

It seems that the INotify for mounted folders does not work with WSL2.

As per:
- https://github.com/microsoft/WSL/issues/4169  (issue closed without being fixed)
- https://github.com/microsoft/vscode-remote-release/issues/2310 (open)

I personally discovered this by trying to use NodeJs tooling like ```create-react-app``` and ```parcel``` which watch for changes and rebuild.   when editing source found in mounted folders the watch logic never triggers.

# Environment
Win10 (b2004+) WSL2
Either WSL2 native, or via docker desktop

# Steps to reproduce
as per the above linked issues, running nodemon or other file watching does not work.
This seems to be a known issue (reading the #4169 thread) but has not been fixed.

I personally don't know enough linux to come up with a simple repro, but can follow the explanation above regarding ```create-react-app```

#  Expected behavior
file watchers work properly.

# Actual behavior
file watchers don't get notified.

**Comment by therealkenc** [comment]
/dupe #4739 or #4581 depending on the direction you fancy.

**Comment by robozb** [comment]
+1
