### ISSUE TITLE
Upgrade to WSL2 did not work properly

### ISSUE THREAD

**Issue by differentblue** [microsoft/WSL#5428]
# Environment (after upgrade)

- Microsoft Windows [Version 10.0.19041.329]
- Linux version **4.4.0-19041-Microsoft** (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
- lsb_release -r     **Release:        20.04**

# Steps to reproduce

I had been running the original WSL for Ubuntu.  Following Windows 10 upgrade to 20.04, I used the WSL2 upgrade instructions at https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

I downloaded a new Ubuntu 20.04 image from the Windows Store.

There were no errors, but my WSL has **not** been properly upgraded.  I still have the old Linux kernel (4.4.0 as shown above), and I can not run nmap as expected.

#  Expected behavior

- I expected to be upgraded to **Linux kernel 4.19.104-microsoft-standard** (this is the version shown in a clean install on another machine)
- I expected to be able to run nmap without error.  Instead I get the same errors as WSL1 gives

# Troubleshooting

- I have deleted all Linux images (from the Powershell command line) but this did not help
- I unselected WSL from the Turn Windows Feature On or Off dialog to uninstall WSL.   I did this, and then rebooted, and then reinstalled.  This did not seem to help.
- The openssh version string indicates that some Linux application files are neweven if the kernel has not been (ssh -V says  OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020)

**Comment by therealkenc** [comment]
Do a `wsl.exe --set-default-version 2` from a non-administrator command prompt. Delete the Ubuntu 20.04 you just installed from the store through the start menu (right-click, uninstall). Then install it again. That might get you there.

**Comment by differentblue** [comment]
Fantastic!  It worked.   I assume I had incorrectly done **wsl.exe --set-default-version 2** as administrator when I first tried.

Thank you very much!

**Comment by Leonard1904** [comment]
Hi, everyone.

I still stuck on 104. I did everything above but the linux kernel still 104. Anything else I can do. 
P/s: My computer is inside the university network, could it be the university limit the update?
