### ISSUE TITLE
Impossible to install or convert distribution with WSL2 

### ISSUE THREAD

**Issue by adpeyre** [microsoft/WSL#5429]
Hi,

I followed all steps to install and use wsl2 but it doesn't work.

When I want to upgrade to wsl2 my ubuntu distribution:
```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
La conversion est en cours. Cette opération peut prendre quelques minutes...
Pour plus d’informations sur les différences de clés avec WSL 2, visitez https://aka.ms/wsl2
L'opération n'a pas pu être démarrée car une fonctionnalité requise n'est pas installée.
````

When I want to install a new distribution with wsl2:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 L'opÚration n'a pas pu Ûtre dÚmarrÚe car une fonctionnalitÚ requise n'est pas installÚe.
```

My configuration is:
- Window 10 pro
- version 2004 (19041.330)

I've tested on my personal computer and it works very well.

**Comment by therealkenc** [comment]
Ref #4626 0x80370114. No endorsement the that reddit-fueled solution over there is sound; just trying to keep identical error codes together as they come up.

**Comment by adpeyre** [comment]
Thanks @therealkenc ! Ok for me.

**Comment by BUREAUCRATE** [comment]
Bonjour j'aurais besoin d'aide car je n'arrive pas à comprendre pourquoi quand je lance linux ou ubuntu sur mon ordi portable qui tourne sous windows 11 ce message d'erreur apparait :
L'opération n'a pas pu être démarrée car une fonctionnalité requise n'est pas installée.
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_SERVICE_NOT_AVAILABLE
