### ISSUE TITLE
WSL2 Cannot Launch(Error code 4294967295)

### ISSUE THREAD

**Issue by panda361** [microsoft/WSL#5431]
# Environment

```none
Windows build number: 10.0.20150.1000
Your Distribution version: Ubuntu installed in store
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

When I click the ubuntu icon or type wsl in terminal, it returns "WSL 2" and nothing happens.
When I open Ubuntu via Windows Terminal, it also returns "WSL 2" and tells me Error code 4294967295.
I have tried "netsh winsock reset" but it still.

#  Expected behavior

Launch normally and have fun;)

# Actual behavior

Exit automatically :(

**Comment by grtstar** [comment]
build 19645 also got the wrong

**Comment by therealkenc** [comment]
> When I click the ubuntu icon or type wsl in terminal, it returns "WSL 2" and nothing happens.

Close enough /dupe #5406 for lack.
