### ISSUE TITLE
Error: The current working directory doesn't exist, cannot proceed. After each machine shutdown/startup. 

### ISSUE THREAD

**Issue by consal** [microsoft/WSL#5432]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Ubuntu Release: 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Shutdown Windows (Fast boot enabled)
2. Start Windows
3. Open Visual Studio Code, get an error: `/mnt/c/Users/xxx/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.3/scripts/wslServer.sh: Input/output error`
4. Open console using for example Windows Terminal, see an error: `Error: The current working directory doesn't exist, cannot proceed.`

#  Expected behavior

All should start normally, restart shouldn't be necessary.

# Actual behavior

- In the console I get an error:
    `Error: The current working directory doesn't exist, cannot proceed.`
- in VS Code, I get an error:
    `/mnt/c/Users/xxx/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.3/scripts/wslServer.sh: Input/output error`

To workaround, I have to open PowerShell and do:
```
wsl --shutdown
wsl
```

Please have a look.

**Comment by harmjanwestra** [comment]
I have the same issue. I'm running the Debian flavor of WSL, and with the recently released Windows update 2004, I have converted it to a WSL2 instance. My hardware is based on an AMD Ryzen CPU. Everytime after I have shutdown my computer, start it up again, and open Windows Terminal to start the Debian WSL2 environment, I cannot access the /mnt/c/ and /mnt/d/ mount. This issue occurs independent of the software used: trying 'ls' in bash on these mounts is also producing Input/Output errors. wsl --shutdown in a CMD/Powershell window fixes this issue.

My bet is the mounts do not get properly remounted after a warm reboot (e.g. fastboot), or that the Debian WSL2 environment does not get the proper signals to remount these volumes. The mounts do still exist, they're just not readable/writeable.

**Comment by xzycn** [comment]
I think this is similar to [my issue](#5446) :(

**Comment by gdubya** [comment]
I experienced a similar issue today w/Ubuntu WSL2. WSL shutdown / restart has resolved the issue. I'll try to capture more debug info next time I see it.

**Comment by roaddog4** [comment]
I am having that same issue today. Stopped and started Windows Terminal and WSL.  Entering a cd command, this is the response "-bash: cd: /openedai-speech: No such file or directory" . Performing an ls -l shows the directory with this "drwxrwxrwx" however no command I send allows me to change to that directory. I cannot remove it since it is not there.
