### ISSUE TITLE
can't show the plot  drawed by python matplotlib or R ggplot2 using wsl

### ISSUE THREAD

**Issue by zihaoxingstudy1** [microsoft/WSL#5433]
can't show the plot  drawed by python matplotlib or R ggplot2 using wsl

**Comment by dhruvinsh** [comment]
Plot requires graphical interface. Do you have graphical interface (desktop environment) installed?

**Comment by zihaoxingstudy1** [comment]
i installed xshell soft and use ssh connect xshell , then i can show the plot on xshell.

**Comment by zihaoxingstudy1** [comment]
> Plot requires graphical interface. Do you have graphical interface (desktop environment) installed?

i installed xshell soft and use ssh connect xshell , then i can show the plot on xshell.
