### ISSUE TITLE
Docker Stuck on Install

### ISSUE THREAD

**Issue by pxlogan** [microsoft/WSL#5436]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

#  Expected behavior

# Actual behavior

**Comment by pxlogan** [comment]
Microsoft Windows [Version 10.0.19041.329]

Docker desktop App has got stuck on install.  How do I kill it?

PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\WINDOWS\system32> wsl -l -v
  NAME              STATE           VERSION
  docker-desktop    Installing      2

**Comment by licanhua** [comment]
There is process name like `docker-desktop.exe`, and you can kill it. That window may have this message: `Installing, this may take a few minutes...`

**Comment by pxlogan** [comment]
Solved
