### ISSUE TITLE
Output text of wsl.exe before enabling WSL2 are garbled when Windows display language is not English.

### ISSUE THREAD

**Issue by 0xbadfca11** [microsoft/WSL#5438]
# Environment

```none
Microsoft Windows [Version 10.0.20150.1000]
WSL2
```

# Steps to reproduce
Setting app -> Time & Language -> Language -> Set "Windows display language".
Launch wsl.exe.

Translated text is displayed correctly after enabling WSL and rebooting.

#  Expected behavior
![image](https://user-images.githubusercontent.com/7390559/85029220-05a43300-b1b7-11ea-80a6-4e5abe01d5d2.png)

# Actual behavior
```cmd
C:\Windows\system32>wsl --help

Copyright (c) Microsoft Corporation. All rights reserved.

????: wsl.exe [Argument]

??:

    --install
        Linux ? Windows ??????????????????????
        ??????????????????? ???????????????????

    --help
        ??????????????

C:\Windows\system32>wsl --install
Installing Virtual Machine Platform
Virtual Machine Platform is now installed.
Installing Windows Subsystem for Linux
Windows Subsystem for Linux is now installed.
???????????????????????????????????????????????

C:\Windows\system32>wsl --install
??????????????????????????

C:\Windows\system32>
```
![image](https://user-images.githubusercontent.com/7390559/85029192-fc1acb00-b1b6-11ea-9ded-c8e09cbdb152.png)

**Comment by therealkenc** [comment]
Maybe variation your #5388 (and one other I can't find atm). I was meaning to ask over in the other one: is it any better in windows [terminal](https://github.com/microsoft/terminal).

**Comment by 0xbadfca11** [comment]
There was no improvement using Windows Terminal.

**Comment by benhillis** [comment]
I'll sort this out, thanks for reporting.

**Comment by licanhua** [comment]
I hit this too, it's replated to codepage. You may run `chcp` in cmd.exe to see what's the active code page, and the codepage is not the localized one. 

There are two ways to fix it:
1. use Windows Terminal. Windows Terminal fixed this problem.
2. There is  'Change system locale' in Region setting, change it and make it matches with Windows display language


_The traditional windows console host is very susceptible to changes in codepage and font. It doesn’t do font fallback, so it will replace glyphs that do not exist in the current font with the [?] symbol._

**Comment by licanhua** [comment]
> Maybe variation your #5388 (and one other I can't find atm). I was meaning to ask over in the other one: is it any better in windows terminal.

They are different problems. 5388 is WSL code problem, and you can't workaround it without code change. And this issue is not a bug and you should be able to fix it by settings.

**Comment by 0xbadfca11** [comment]
1. Windows Terminal does not solves this problem.
![image](https://user-images.githubusercontent.com/7390559/85196911-6b5c0080-b318-11ea-9b66-1267212f47d1.png)

2. Of course, if I have a fresh install of Windows, Windows display language and system locale match.
![image](https://user-images.githubusercontent.com/7390559/85197045-6ea3bc00-b319-11ea-8dc8-099fb70dcec5.png)

**Comment by licanhua** [comment]
Thanks, I can repro your problem.
It only happens before enabling WSL. After you enabled WSL, it will display message correctly.

![image](https://user-images.githubusercontent.com/6290692/85502193-b174c680-b59b-11ea-986e-4f605834dba9.png)

**Comment by benhillis** [comment]
I’ll find some time to fix this today.

**Comment by 0xbadfca11** [comment]
Fixed.
https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175

**Comment by mdragosv** [comment]
Before wsl --install

![image](https://user-images.githubusercontent.com/29517827/204930225-02c0d8d3-5c72-424a-bbd0-3d8c51290762.png)


after wsl --install

![image](https://user-images.githubusercontent.com/29517827/204930299-22794923-9bf4-48e8-8063-a7d75a6a668b.png)


WSL store looks like french or something

![image](https://user-images.githubusercontent.com/29517827/204930462-55fcf1bc-f564-4bc1-9ad0-6c2a1f244d49.png)

why the hell do i get french language ???
