### ISSUE TITLE
'paste' command doesn't work in WSL/WSL2

### ISSUE THREAD

**Issue by octotus** [microsoft/WSL#5441]
# Environment

```none
Windows build number: [Version 10.0.19041.330]
Your Distribution version: [Ubuntu 20.04]
Whether the issue is on WSL 2 and/or WSL 1: [Linux version 4.4.0-19041-Microsoft]

```

# Steps to reproduce

Input: a text input_file file with some lines [I had input from 1 - 5 in five lines]

// Operation //

> paste input_file input_file > b_file

#  Expected behavior

<
In a Linux machine, the result looks like this:

![Screenshot (6)](https://user-images.githubusercontent.com/9291612/85077464-53597500-b190-11ea-9f4b-1e9fa3903c87.png) 

>
# Actual behavior

<
b_file looks like this [below].

![Screenshot (5)](https://user-images.githubusercontent.com/9291612/85077270-ddeda480-b18f-11ea-837a-3dd446364206.png)

>

**Comment by therealkenc** [comment]
There is no repro here, call it landing zone /dupe #4852

**Comment by octotus** [comment]
Thanks for the response -- here is something that may help.

I had imported my .bashrc script from a *nix machine, and one of the aliases was for color in ls. Once I disabled that, the problem was resolved.
