### ISSUE TITLE
[Translation] A misused word in Chinese l10n when a nonexistent WSL distribution is accessed

### ISSUE THREAD

**Issue by DHowett** [microsoft/WSL#5442]
From microsoft/terminal#6582 (filed by @DaZui)

---

# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software? N/A
```

# Steps to reproduce

First of all, you have to have a Chinese (Simplified) system. 

Try to trigger a WSL distribution that is not present:

1. Open Windows Terminal;
2. Remove a distribution;
3. Try to use tab to open bash of the distribution you just removed.

# Expected behavior

It should notice user that the distribution is missing. 

The notice should be "发行版" (Linux Distribution) but not "分布" (mathematical distribution).

# Actual behavior

![image](https://user-images.githubusercontent.com/5781966/85078581-56516700-b18a-11ea-8f6f-47f69acc70e8.png)

**Comment by therealkenc** [comment]
Ref #4111 ([message](https://github.com/microsoft/WSL/issues/4111#issuecomment-502198662))

**Comment by benhillis** [comment]
@craigloewen-msft - do you know where to send localization issues?

**Comment by TinaMcN** [comment]
I logged a bug for the Windows localization team to investigate

**Comment by TinaMcN** [comment]
The localization checked in the fixed translation and should be included in the next builds.  Please let us know if you don't see it fixed soon.

**Comment by therealkenc** [comment]
/fixed 20190 (or thereabouts, based on the date)

If there are remaining localization issues, please reboot under a new issue submission.
