### ISSUE TITLE
Change Ubuntu from WSL 1 to WSL 2

### ISSUE THREAD

**Issue by ricardo-a-calderon** [microsoft/WSL#5443]
I have a issue when I change WSL version. Ubutu machine is running without any problem. Windows 10 version is ok, virtualization parameters are ok. But I cann't change WSL version. Any idea?
```
PS C:\WINDOWS\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    **Running**         1
PS C:\WINDOWS\system32> **wsl --set-version Ubuntu-20.04 2**
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
**Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.**
For information please visit https://aka.ms/wsl2-install
PS C:\WINDOWS\system32>
```
![Virtualization Enabled](https://user-images.githubusercontent.com/61300820/85082163-14c9b780-b19c-11ea-995f-9d8b7ac08b3b.jpg)
![Windows Version](https://user-images.githubusercontent.com/61300820/85082184-21e6a680-b19c-11ea-9b8a-6e4bc7bf21bf.jpg)
![Windows Features](https://user-images.githubusercontent.com/61300820/85082193-2b700e80-b19c-11ea-9946-8d0cfd7d2dd2.jpg)

**Comment by therealkenc** [comment]
Effectively same /dupe #5363
