### ISSUE TITLE
AMD vs Intel for WSL2

### ISSUE THREAD

**Issue by benlumia007** [microsoft/WSL#5444]
i was meant to ask. How compatible is WSL2 on AMD processors?  I've been using virtualization with Intel and I was wondering about using WSL2 with AMD.

**Comment by therealkenc** [comment]
This is a good question for reddit, twitter. Ref #4193 which has some discussion.

**Comment by benlumia007** [comment]
that's talking about nested VM and KVM. not what I wanted.  All I want to know if u enable WSL and Virtual Machine Platform. Does it work out of the box for AMD
