### ISSUE TITLE
WSL2 seeing only 1 of 2 ~identical gpus in system

### ISSUE THREAD

**Issue by cobb-research** [microsoft/WSL#5445]
## Environment

Windows build number:  10.0.20150.1000

WSL Distribution version: Ubuntu 20.04

WSL 2:  Linux version 4.19.121-microsoft-WSL2-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Thu May 14 20:25:24 UTC 2020

## Steps to reproduce

Run deviceQuery under WSL.... => output shows:
----------------------------------------------------------------------------------------------
deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1070"
... 
lots of stuff omitted
...
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 10.1,
NumDevs = 1, Device0 = GeForce GTX 1070
Result = PASS

---------------------------------------------------------------------------------------------
The problem is that there are TWO gpus in the system...
---------------------------------------------------------------------------------------------

.\extras\demo_suite\deviceQuery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "GeForce GTX 1070"
...
lots of stuff omitted
...
Device 1: "GeForce GTX 1070"
...
lots of stuff omitted
...
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 10.2, NumDevs = 2, Device0 = GeForce GTX 1070, Device1 = GeForce GTX 1070
Result = PASS
--------------------------------------------------------------------------------------------------------

As you can see WSL is only seeing 1 of the two GTX 1070 gpus.  I am not asserting that this
is a bug -- for all i know this is the intended or expected behavior.  But I haven't seen it mentioned in the list of issues so I thought I'd mention it.

#  Expected behavior

would expect deviceQuery in BOTH places to report 2 gpus present.

# Actual behavior

deviceQuery in WSL is only seeing 1 of the 2 gpus

I did run some standard multi-gpu code that i have just in case deviceQuery itself was being flakey -- that's not the issue.  WSL2 really only is using 1 gpu (as you would expect from what deviceQuery is reporting).

**Comment by WSLUser** [comment]
Do you have SLI configured? This may be something WSL2 needs to detect (along with CrossFireX when OpenCL gains more support)

**Comment by onomatopellan** [comment]
Nvidia drivers are in preview so I recommend to post your issue on their forums.
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-on-windows-subsystem-for-linux/

**Comment by cobb-research** [comment]
> Do you have SLI configured? This may be something WSL2 needs to detect (along with CrossFireX when OpenCL gains more support). If you use the same distro in full Hyper-V, does it see both GPUs?

In fact I *do* have SLI configured.  It never crossed my mind that this might be relevant or I would have mentioned it.  I'll try disabling it and retesting.

**Comment by cobb-research** [comment]
> Nvidia drivers are in preview so I recommend to post your issue on their forums.
> https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-on-windows-subsystem-for-linux/

Very true.  I will post there also.  Thanks.

**Comment by cobb-research** [comment]
> Do you have SLI configured? This may be something WSL2 needs to detect (along with CrossFireX when OpenCL gains more support). If you use the same distro in full Hyper-V, does it see both GPUs?

Turning off SLI solved the problem.  WSL2 now sees both GPUs!   Many thanks.

**Comment by cobb-research** [comment]
There appears to be an issue with WSL2 and multiple GPUs if SLI is enabled.  Disabling SLI allows WSL2 to see multiple GPUs.  Closing as "A workaround exists"
