### ISSUE TITLE
WSL should release the memory after the resource is no longer needed

### ISSUE THREAD

**Issue by nodew** [microsoft/WSL#5450]
It seems that WSL won't release the mem after the computed finished, so the mem will grow bigger and bigger, but never get released then eat all mem.
![image](https://user-images.githubusercontent.com/9988582/85206425-aed46000-b354-11ea-8dac-d82cfab1f802.png)

**Comment by y122972** [comment]
```bash
sudo su
sync; echo 3 > /proc/sys/vm/drop_caches
```
This can release buff/cache.

By the way, Ludashi app can release the Ram totally.
