### ISSUE TITLE
Cannot Install Any Ubuntu Distribuition

### ISSUE THREAD

**Issue by vlOd2** [microsoft/WSL#5453]
# Environment

Windows build number: 10.0.19041.264
Your Distribution version: 18.04 (But This Applies to every distribuition)
Whether the issue is on WSL 2 and/or WSL 1: Wsl 1.0

# Steps to reproduce

Its an Wsl/Ubuntu Launch Issue

#  Expected behavior
I would expect Ubuntu To let me Use it like so i can setup the account and other stuff

# Actual behavior
Ubuntu just crashes/gives an error after 2 or 3 minutes on launch:

Error:
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

**Comment by therealkenc** [comment]
Ref #4003
