### ISSUE TITLE
Installed package not found as command

### ISSUE THREAD

**Issue by jmap82** [microsoft/WSL#5454]
I use Handbrake to transcode my video files. On a native ubuntu install, the CLI worked well in a script I created. In Window, the CLI worked ok, but I couldn't use my bash script. Now, I'm trying to use WSL to run my bash script in Windows, but the HandBrake CLI isn't working. The package is installed, but the command can not be used. 
![HandBrakeCLI_NotFound](https://user-images.githubusercontent.com/20469947/85210696-080da680-b2f7-11ea-822f-d682cab525fd.PNG)

Help, suggestions, and/or demystification welcome. 

Solved: The correct command is <code>HandBrakeCLI</code>. Thanks Biswa96.

**Comment by Biswa96** [comment]
According to [Ubuntu packages][1], the command should be `HandBrakeCLI`.

[1]: https://packages.ubuntu.com/focal/amd64/handbrake-cli/filelist

**Comment by jmap82** [comment]
Ha! Just came back to delete my post. I went back and looked at my script and realized the same thing... Oops. Thanks.
