### ISSUE TITLE
TensorFlow build with DirectML aborts

### ISSUE THREAD

**Issue by devksingh4** [microsoft/WSL#5455]
I followed the instructions here: https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-tensorflow-wsl

I get: 

2020-06-20 16:32:45.432744: F tensorflow/core/common_runtime/dml/dml_adapter_impl.cc:123] Check failed: (((HRESULT)((DXCoreCreateAdapterFactory(__uuidof(**(&adapter_factory)), IID_PPV_ARGS_Helper(&adapter_factory))))) >= 0) == true (0 vs. 1)

I have: 
AMD Ryzen 5 1600AF
AMD RX580 8GB 
Windows build 20150
Radeon Driver version 27.20.2001.5002

**Comment by therealkenc** [comment]
> AMD Ryzen 5 1600AF

[this](https://forums.developer.nvidia.com/t/known-limitations-with-cuda-on-wsl-2/128506)

**Comment by devksingh4** [comment]
I have an AMD graphics card.On Jun 20, 2020 6:45 PM, therealkenc <notifications@github.com> wrote:

AMD Ryzen 5 1600AF

this

**Comment by onomatopellan** [comment]
Please post the output of
`uname -a`
`ll /dev/dxg`
`ll /usr/lib/wsl/lib`

**Comment by Charingchen** [comment]
I have the same problem.  I noticed in the instruction, "For this preview, you need a kernel version of 4.19.121 or higher." But I don't know how to update my from 4.19.104 to a 121 build
`uname -a` output
`Linux [computername] 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`ls -la /dev/dxg` output:
`ls: cannot access '/dev/dxg': No such file or directory`

`ls -ls /usr/lib/wsl/lib` output
```
total 26884
dr-xr-xr-x 1 root root     4096 Aug 10 13:43 .
drwxr-xr-x 4 root root     4096 Aug 10 22:38 ..
-r--r--r-- 2 root root   832936 Aug  1 09:43 libd3d12.so
-r--r--r-- 2 root root  5038600 Aug  1 09:43 libd3d12core.so
-r--r--r-- 2 root root 20765928 Aug  1 09:43 libdirectml.so
-r--r--r-- 2 root root   878768 Aug  1 09:43 libdxcore.so
```

**Comment by devksingh4** [comment]
Solves for me as well. Closing issue.
