### ISSUE TITLE
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#5456]
NOTE: This does **not** appear to be a dupe of #4101 at first sight, given the different errors appearing in dmesg output, hence why I am reporting it as a separate issue.

# Environment

```none
Windows build number: 20150
Your Distribution version: Debian bullseye
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Error occurs when a WSL session is started (i.e. wsl.exe is executed) even if WSL is already running in the background, with the message `An error occurred mounting one of your file systems. Please run 'dmesg' for more details.` being displayed.

On examining the output of dmesg, the following errors are seen:

```
...
[   33.894977] 9pnet: Could not find request transport: virtio
[   33.895098] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;umask=022;fmask=022;symlinkroot=/mnt/
[   33.895103] ) failed: 22
...
```

and the automatic drvfs mount of /mnt/c is missing. The same errors are repeated if an immediate attempt to mount the drive manually is made, but if one is made after several minutes, it succeeds without logging additional errors. 

#  Expected behavior

/mnt/c is automatically mounted without error.

**Comment by therealkenc** [comment]
Confirm are you on kernel 4.19.121.

**Comment by cerebrate** [comment]
Ah. No, 4.19.84. I'll update that now.

**Comment by benhillis** [comment]
I suspect you are using a private kernel? That is going to open you up to issues like this in the future. If there are config options you'd like to see in the supported kernel just let us know.

**Comment by cerebrate** [comment]
@benhillis I try to be proactive in making sure that my kernel is up to date with microsoft/WSL2-Linux-Kernel (and check that first when I have an issue) for situations just like this one. It just never occurred to me that I should be checking against branches other than master, too. My bad.

Anyway, this issue goes away once I merge in the changes from linux-msft-wsl-4.19.y to take me to 4.19.121, so I'll go ahead and close this now.

**Comment by parthagarwal** [comment]
Quick question: how exactly did you merge in the changes?

**Comment by cerebrate** [comment]
I keep a fork of the WLS2-Linux-Kernel repo to hold my own .config file and a couple of kernel patches I needed to apply, so I just did a pull request from microsoft/WSL2-Linux-Kernel:linux-msft-wsl-4.19.y against that, and did the usual git merge stuff.

**Comment by parthagarwal** [comment]
I see, is it it possible to get the latest release without pulling the source code? Should wsl_update_x64.msi also be able to update to 121, or does the latest kernel have to be built locally? After running the msi I'm still at version 84.

**Comment by cerebrate** [comment]
@benhillis On the config options I'd like to see in the supported kernel - well, I have a fair few of those, even once I eliminate the ones which are too idiosyncratic. Should I post them here as feature-requests-by-topic-group (which might be about a dozen, all told), or is there a different preferable way I should let you know?

**Comment by startergo** [comment]
It all operated properly with the former Windows version in WSL2 environment. 
Steps to reproduce the error:
Upgraded Windows to the latest 20150 release.
After the upgrade has finished attempted to start the working WSL2 (error message kernel needs an update)
Inspected the folder c:\windows\system32\lxss\tools and found that the kernel was missing (after the Windows upgrade)
Copied c:\temp\kernel (backup of 4.19.121-microsoft-standard) to c:\windows\system32\lxss\tools
Upon startup of the WSL2 the network shares were broken.
Not sure how to fix this permanently.
```
 9pnet: Could not find request transport: virtio
[    2.329472] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/a (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=A:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.329474] ) failed: 22
[    2.339407] 9pnet: Could not find request transport: virtio
[    2.343754] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/b (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=B:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.343757] ) failed: 22
[    2.357270] 9pnet: Could not find request transport: virtio
[    2.360232] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.360234] ) failed: 22
[    2.370613] 9pnet: Could not find request transport: virtio
[    2.373791] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/f (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=F:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.373793] ) failed: 22
[    2.383461] 9pnet: Could not find request transport: virtio
[    2.386423] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/g (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=G:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.386425] ) failed: 22
[    2.396367] 9pnet: Could not find request transport: virtio
[    2.399508] 9pnet: Could not find request transport: virtio
[    2.402571] 9pnet: Could not find request transport: virtio
[    2.407044] 9pnet: Could not find request transport: virtio
[    2.411443] 9pnet: Could not find request transport: virtio
[    2.415845] 9pnet: Could not find request transport: virtio
[    2.421394] 9pnet: Could not find request transport: virtio
[    2.425590] 9pnet: Could not find request transport: virtio
[    2.430046] 9pnet: Could not find request transport: virtio
```
```
sudo lspci -nn -vvvv -tt 
-+-[ba98:00]---00.0  Microsoft Corporation Device [1414:008e]
 +-[ab56:00]---00.0  Red Hat, Inc. Virtio filesystem [1af4:1049]
 \-[0000:00]-
```

**Comment by marc5000** [comment]
I ran into this issue when running the latest Insider release of Windows. My Windows drives weren't mounting in Ubuntu. 

I'm going to leave my experience with the issue for anyone who isn't able to mount using: 

`mount -t drvfs 'C:' /mnt/c`

If you have a custom kernel, you **need** to ensure that you enable: 

`CONFIG_NET_9P_VIRTIO=y`

If this isn't enabled, your mounts will not work (as per the opening issue).

The easiest way to recompile your kernel is to adjust the .config file; and find: 

_#CONFIG_NET_9P_VIRTIO=y_ and un-comment it. 

Once you have, make the new kernel (this should be quick if you compiled one before):

`make -j 8`

Load any kernel modules: 

`sudo make modules_install`

You'll need to copy the kernel to your C:\Users\<username> folder _via Winsows_

Access all your WSL files in Windows via: \\wsl$ -- then navigate to your kernel build folder:

_eg. /home/user/WSL-XXXXXX/arch/x86/boot/_

Copy the: bzImage to your Desktop, rename it, and then move your new kernel to your user folder.

Define the new kernel image in your C:\Users\<username>\.wslconfig

Shutdown wsl via Powershell:

`wsl --shutdown`

Finally, start wsl:

`wsl`

**Comment by Nxongo** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/68202255/102825024-a681de00-43e6-11eb-8454-d4cf2c9c8d83.png)
This is what had been happening when it try to launch my Kali Linux

**Comment by parsalotfy** [comment]
I have not installed any distro

```
PS C:\WINDOWS\system32> wsl --list --all --verbose
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
```

and this is wsl --status result :

```
PS C:\WINDOWS\system32> wsl --status
Default Distribution: docker-desktop-data
Default Version: 2

Windows Subsystem for Linux was last updated on 5/18/2021
WSL automatic updates are on.

Kernel version: 5.10.16

```


when I run `wsl` command I get the same error.
Is that because I have not installed any distro?
What the result of wsl command should be if we didn't install any distro?

**Comment by xuelongqy** [comment]
[download-the-linux-kernel-update-package](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)

**Comment by alex-pex** [comment]
You can update the kernel by typing `wsl --update` as an admin (in windows command line).
It fixed my problem

**Comment by Burnuts** [comment]
@Pechayland got this issue also and he is using kernel version 5.10.43 under WSL 2.
https://bugs.launchpad.net/ubuntuwsl/+bug/1939235

**Comment by bioinfonerd** [comment]
Same issue as well 
![image](https://user-images.githubusercontent.com/10776996/130074894-51abfc22-1584-4191-bd1f-dbf52708c7c1.png)

**Comment by grmlin** [comment]
> Same issue as well
> ![image](https://user-images.githubusercontent.com/10776996/130074894-51abfc22-1584-4191-bd1f-dbf52708c7c1.png)

Same problem here out of nowhere. Shut down the system yesterday (didn't install any updates) and today I was greeted with the error above. Running the latest Windows 11 Beta release Version 10.0.22000 Build 22000

**Comment by samurusov** [comment]
![same](https://user-images.githubusercontent.com/14890643/131266384-e3b0a374-9ece-4dc3-b6c3-995882d09f16.png)
Same problem here

**Comment by NeilCross** [comment]
I has this issue arise similarly to how @grmlin reports. WSL and docker desktop working fine then; 

After theupdate (on the 28 afaik), Hyper-v seemed to be not installed from a Windows Feature perspective. I renabled it via the "Turn Windows Features on or off" ui.

Following this i got;
```
$ wsl --list
Windows Subsystem for Linux Distributions:
docker-desktop  (Default)
docker-desktop-data
```

So I added a new distro via the store and set it as the default, and it started fine.

I didn't *need* anything on the old wsl install, so my impact was minimal.  I didn't look for a way to restore the old instace however. but this got me back up and running.

**Comment by grmlin** [comment]
Update: problem went away after installing the latest update Version 10.0.22000 Build 22000 of the Windows 11 Beta!

**Comment by zapisanchez** [comment]
Same problem here:

w11 22000.318

WSL kernel: 5.10.60.1

.wslconfig:
[wsl2]
kernel=C:\WINDOWS\System32\lxss\tools\kernel

Problem continues happening...

**Comment by gitxmax** [comment]
Hello,
Windows 11 here, with everything updated to the latest, including  wsl.exe --update
I get the mounting error as well
Also tried creating the .wslconfig file with the kernel path:
[wsl2]
kernel=C:\WINDOWS\System32\lxss\tools\kernel

Nothing helped.

`[    2.427992] init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/d (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=D:\;uid=0;gid=0;symlinkroot=/mnt/
[    2.427997] ) failed: 22
[    2.443178] FS-Cache: Duplicate cookie detected
[    2.443183] FS-Cache: O-cookie c=00000000628246f3 [p=00000000bdbcf6ac fl=222 nc=0 na=1]
[    2.443185] FS-Cache: O-cookie d=000000005a5c8b89 n=0000000072aa8c0b
[    2.443186] FS-Cache: O-key=[10] '34323934393337353335'
[    2.443194] FS-Cache: N-cookie c=000000001a5082bf [p=00000000bdbcf6ac fl=2 nc=0 na=1]
[    2.443195] FS-Cache: N-cookie d=000000005a5c8b89 n=000000009de194c2
[    2.443196] FS-Cache: N-key=[10] '34323934393337353335'
[    2.647880] hv_pci 1e51d629-aeef-40fe-b17b-7589b35a81bb: PCI VMBus probing: Using version 0x10003
[    2.649786] hv_pci 1e51d629-aeef-40fe-b17b-7589b35a81bb: PCI host bridge to bus aeef:00
[    2.649791] pci_bus aeef:00: root bus resource [mem 0x9ffe0c000-0x9ffe0efff window]
[    2.652087] pci aeef:00:00.0: [1af4:1049] type 00 class 0x010000
[    2.653937] pci aeef:00:00.0: reg 0x10: [mem 0x9ffe0c000-0x9ffe0cfff 64bit]
[    2.654910] pci aeef:00:00.0: reg 0x18: [mem 0x9ffe0d000-0x9ffe0dfff 64bit]
[    2.655950] pci aeef:00:00.0: reg 0x20: [mem 0x9ffe0e000-0x9ffe0efff 64bit]
[    2.664026] pci aeef:00:00.0: BAR 0: assigned [mem 0x9ffe0c000-0x9ffe0cfff 64bit]
[    2.664947] pci aeef:00:00.0: BAR 2: assigned [mem 0x9ffe0d000-0x9ffe0dfff 64bit]
[    2.665635] pci aeef:00:00.0: BAR 4: assigned [mem 0x9ffe0e000-0x9ffe0efff 64bit]
[    2.691485] init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/d (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=D:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    2.691489] ) failed: 22
[   49.151548] hv_balloon: Max. dynamic memory size: 2048 MB`

**Comment by yszzu1** [comment]
after uninstall docker-desktop,   wsl is working.

**Comment by BrianM0330** [comment]
Was having the same issue, tried messing with wsl.conf and updating kernel but no luck on kernel `5.10.60.1` and windows `21H2 22000.348`

Uninstalled Docker desktop on Windows, restarted WSL and it worked! Reinstalling Docker didn't seem to break it again, not sure why that happened in the first place.

**Comment by gitxmax** [comment]
Can't confirmed if the Docker Desktop is causing the issue, I don't have it installed, yet having the mounting issue.

**Comment by joworeiter** [comment]
For me the default distro changed to docker-desktop-data without noticing. 

so check with `wsl --status` if you have the correct default-distro. 
if not change it with `wsl -s ${distroname}`
Works again

**Comment by mrlux** [comment]
I can confirm this fixed it for me:
```
$ wsl --list
Windows Subsystem for Linux Distributions:
docker-desktop  
docker-desktop-data (Default)```

$ wsl -s docker-desktop

$ wsl --list
Windows Subsystem for Linux Distributions:
docker-desktop (Default)
docker-desktop-data

**Comment by gitxmax** [comment]
`Microsoft Windows [Version 10.0.22000.348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Solo>wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 11/18/2021
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.60.1

C:\Users\Solo>wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)`

Only Ubuntu ...

**Comment by mkhuramj** [comment]
After facing this issue and wasting hours to fix but no luck. I then asked myself why do I  need to use WSL1/2????
I am a fullstack web developer and have recently shifted from Ubuntu 21 to Windows 11 after almost using Ubuntu 9 years.
My use case is to develop REST APIs and C/S-SPAs and I like to have Debian/ubuntu as my working platform. So, after exploring Windows WSL, I started to use it not knowing that I can use VS-Code's Remote Container extension instead of WSL extension which is far more better in many cases like to provide interpreter path, running tests from vscode extension etc. 

So in my use case it was totally unnecessary to use WSL2 and I had stopped using it because of this instability.
Can someone please give me a good reason to keep using WSL1/2 and why not only Docker+Vs-Code+Remote Container???

**Comment by LoicLemerlus** [comment]
If I'm not mistaken the VS code remote container is using docker which is using WSL2 under the hood. So all the issues/bugs with WSL are still valid with this method.
You might be better using the VScode remote SSH with a ubuntu server.

**Comment by hungnhat130420** [comment]
> I fixed it with "wsl -s ubuntu" (docker was default)

thank you so much

**Comment by egiglio** [comment]
> 

This fixed it for me. Thank you!

**Comment by bathindahelper** [comment]
I found the solution [here](https://bathindahelper.com/t/ubuntu-linux-error-on-windows-11-or-win10/3613).

**Comment by LorenzoMorelli** [comment]
> I has this issue arise similarly to how @grmlin reports. WSL and docker desktop working fine then;
> 
> After theupdate (on the 28 afaik), Hyper-v seemed to be not installed from a Windows Feature perspective. I renabled it via the "Turn Windows Features on or off" ui.
> 
> Following this i got;
> 
> ```
> $ wsl --list
> Windows Subsystem for Linux Distributions:
> docker-desktop  (Default)
> docker-desktop-data
> ```
> 
> So I added a new distro via the store and set it as the default, and it started fine.
> 
> I didn't _need_ anything on the old wsl install, so my impact was minimal. I didn't look for a way to restore the old instace however. but this got me back up and running.

I resolved simply changing the default wsl from docker to ubuntu

**Comment by curtisrecords** [comment]
hi I'm Chinese and my English is not very good. Hope to understand... 😥 (Mashine Translated)

I tried uninstalling Docker tried turning off Hyper-V
When I finally checked dmesg, I realized that it seems to be caused by the fact that Windows does not support the data format of some partitions (with Hackintosh/Linux installed), I tried to set it (drive letters such as C:\, D:\) as hidden (*), it's back to normal; it's weird that there won't be a dmesg reminder before.

我尝试卸载了Docker 尝试关闭了Hyper-V
最终我查看dmesg的时候，我意识到似乎是因为Windows不支持一些分区的数据格式导致的(装了Hackintosh/Linux)，我尝试把它(盘符 例如C:\,D:\)设置成隐藏(*)，就恢复正常了；很奇怪，这在之前是不会有dmesg提醒的。

**Comment by x011** [comment]
In my case, it was a bitlocker drive not unlocked. After unlocking it using my password and shutdown wsl ( `wsl --shutdown`), the error disappeared.

**Comment by stevem26** [comment]
> In my case, it was a bitlocker drive not unlocked. After unlocking it using my password and shutdown wsl ( `wsl --shutdown`), the error disappeared.

This was me too.  It turned out that just because I had a locked drive attached, this error was generated.  However, it doesn't actually cause any problems using WSL and could be safely ignored (unless of course I actually need to mount that locked drive, which I do not!!).

**Comment by rohit1kumar** [comment]
> > I has this issue arise similarly to how @grmlin reports. WSL and docker desktop working fine then;
> > After theupdate (on the 28 afaik), Hyper-v seemed to be not installed from a Windows Feature perspective. I renabled it via the "Turn Windows Features on or off" ui.
> > Following this i got;
> > ```
> > $ wsl --list
> > Windows Subsystem for Linux Distributions:
> > docker-desktop  (Default)
> > docker-desktop-data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I added a new distro via the store and set it as the default, and it started fine.
> > I didn't _need_ anything on the old wsl install, so my impact was minimal. I didn't look for a way to restore the old instace however. but this got me back up and running.
> 
> I resolved simply changing the default wsl from docker to ubuntu

Adding to this ans: wsl --setdefault <DistributionName>

**Comment by debmaj2** [comment]
`wsl --update` fixed the issue. It seems to be the path issue which is resolved on updating the wsl version. This is especially applicable for the users who are having only one distro and still facing issues.
