### ISSUE TITLE
The I/O operation has been aborted because of either a thread exit or an application request. 

### ISSUE THREAD

**Issue by shahjahan0275** [microsoft/WSL#5457]
when I try to run Ubuntu 18.04. it shows this following error message
"The I/O operation has been aborted because of either a thread exit or an application request. "

Then it doesn't accept my new unix username.

**Comment by therealkenc** [comment]
Please open a new one with the template filled including [detail logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). Ref #5209 #3134
