### ISSUE TITLE
wsl --export failed

### ISSUE THREAD

**Issue by cool-delete** [microsoft/WSL#5460]
# Environment

```none
Windows build number:Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Distribution version: [Ubuntu Release:        20.04]
wsl2

```

# Steps to reproduce
after run `LxRunOffline move -n Ubuntu-20.04 -d F:\wsl\docker`
i type `wsl --export Ubuntu20.04 F:\wsl` 
return access Deni
#  Expected behavior
removed to other computer

**Comment by licanhua** [comment]
I guess F:\wsl is a directory, but --export requires file name, so the correct command should be like this:

`wsl --export Ubuntu-20.04 F:\wsl\abc.tar`

Another possible reason is that you don't have permission to create F:\wsl file

**Comment by cool-delete** [comment]
> I guess F:\wsl is a directory, but --export requires file name, so the correct command should be like this:
> 
> `wsl --export Ubuntu-20.04 F:\wsl\abc.tar`
> 
> Another possible reason is that you don't have permission to create F:\wsl file

yes! I forgot the suffix,Thanks for the trick!
