### ISSUE TITLE
WSL 2 no longer uses bridged network interface

### ISSUE THREAD

**Issue by happyharrysco1** [microsoft/WSL#5461]
I Have just updated from WSL1 to WSL2 and in WSL1 the Linux install used a bridged network interface with the host device, and in this manner i could for instance rdp from a remote machine to hostip:3389 and open an xrdp desktop session on the linux install, in WSL2 this functionality has changed and as such i can only access the WSL instance over the network from the local device using localhost:3389 to open the same session, is there any way to replicate this behaviour in WSL2?

**Comment by cerebrate** [comment]
See #4150 for discussion of this issue and currently available workarounds.

**Comment by happyharrysco1** [comment]
Hi There, 

#4150 does not provide a solution for domain joined machines due to privilege/account issues, a normal domain user cannot run the script due to low privileges, and while a domain admin can indeed run the script there are no wsl2 instances to run against because they all belong to the normal domain user account and not the domain admin account, please add a proper fix to the code!
