### ISSUE TITLE
PyTorch Can't transfer net to CUDA Device

### ISSUE THREAD

**Issue by Erik-Sovereign** [microsoft/WSL#5462]
Environment

```
Windows build number: Version 2004 (Build 20150.1000)
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
Linux Kernel: 4.19.121-microsoft-standard
Python: 3.5.4
PyTorch: 1.2
Geforce Driver: 455.41
```

# Steps to reproduce

I want to switch from my Ubuntu 18.04 Dual Boot to WSL 2 Ubuntu 20.04.
I tested my PyTorch CNN Training Script in WSL. 
It recognized my Nvidia GPU. 
(torch.cuda.is_available() gave true and 
torch.cuda.get_device_name(device) gave "GeForce RTX 2070 SUPER")

PyTorch downloaded ResNet but when I wanted to move the net to the GPU with net.to(device) like you see in the code below the following error occured and the script crashed (You see the error/crash log down below):
```
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
net = Networks.PhaseLSTMResNet(num_classes, lstm_size)
net.to(device)

#For Github: Just the Net Classes, it downloads the net with  self.resnet = #torchvision.models.resnet50(pretrained=True)
class FeatureResNet(nn.Module):
    def __init__(self, num_features = 2048):
        super(FeatureResNet, self).__init__()
        #self.resnet = torchvision.models.resnet18(pretrained=True)
        self.resnet = torchvision.models.resnet50(pretrained=True)
        self.sig = nn.Sigmoid()
        self.feature = nn.Linear(2048, num_features)

    def forward(self, x):
        x = self.resnet.conv1(x)
        x = self.resnet.bn1(x)
        x = self.resnet.relu(x)
        x = self.resnet.maxpool(x)

        x = self.resnet.layer1(x)
        x = self.resnet.layer2(x)
        x = self.resnet.layer3(x)
        x = self.resnet.layer4(x)

        x = self.resnet.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.feature(x)

        return self.sig(x)

    def load(self, model_file):
        self.load_state_dict(torch.load(model_file))

    def save(self, model_file):
        torch.save(self.state_dict(), model_file)

class PhaseLSTMResNet(nn.Module):
    def __init__(self, num_classes, lstm_size, pretrain = None):
        super(PhaseLSTMResNet, self).__init__()
        self.featureNet = FeatureResNet()

        if pretrain is not None:
            self.featureNet.load(pretrain)

        self.lstm_size = lstm_size
        self.lstm = nn.LSTM(2048, self.lstm_size, batch_first=True)
        self.classifier = nn.Linear(lstm_size, num_classes)

    def init_hidden(self, batch_size, device=None):
        return (torch.zeros(1, 1, self.lstm_size, device=device),
                torch.zeros(1, 1, self.lstm_size, device=device))

    def forward(self, x, hidden_state):
        x = self.featureNet.forward(x)
        x = x.view(1, x.size(0), -1)
        x, hidden_state = self.lstm(x, hidden_state)
        x = x.view(x.size(1), -1)
        x = self.classifier(x)

        return x, hidden_state

    def load(self, model_file):
        self.load_state_dict(torch.load(model_file))

    def save(self, model_file):
        torch.save(self.state_dict(), model_file)
```
  
Crash log when doing net.to(device)
```
Traceback (most recent call last):
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/local/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erik/XXX/surgical_phase_recognition/Train_SurgicalPhaseRecognition.py", line 77, in <module>
    net.to(device)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
```

#  Expected behavior

PyTorch should transfer the net to the GPU and procede like it does in my Ubuntu Dual Boot. There the entire training script works.

# Actual behavior

It crashes

**Comment by onomatopellan** [comment]
First of all make sure you have latest NVIDIA drivers 455.41 in Windows.
https://developer.nvidia.com/cuda/wsl/download

Does the CUDA sample `nbody -gpu -benchmark` work?

**Comment by Erik-Sovereign** [comment]
I have this NVIDIA Driver.

I don't know what nbody is
Do you mean this https://github.com/zchee/cuda-sample/tree/master/5_Simulations/nbody?

When yes how do I execute it :)?

**Comment by onomatopellan** [comment]
you need to install the CUDA toolkit. Follow these steps:
https://forums.developer.nvidia.com/t/failure-to-install-cuda-on-wsl-2-ubuntu/128592/8

Just entering in the sample directory you want and do `make` to generate the executable.

**Comment by therealkenc** [comment]
What is the output of:
```
$ powershell.exe Get-ComputerInfo | grep CsProcessors
```

**Comment by Erik-Sovereign** [comment]
@onomatopellan 
I installed the CUDA Toolkit.
cuda-10.0/samples/1_Utilities/deviceQuery was succesful

sudo make for nbody failed with
`unsupported GNU version! gcc versions later than 7 are not supported!`
I can imagine the problem is that I use Ubuntu 20.04 but the choices for the CUDA 10 Toolkit are Ubuntu 16.04 or 18.04.

@therealkenc 
The output is
`AMD Ryzen 5 3600 6-Core Processor`

Appreciate the help :)

**Comment by therealkenc** [comment]
> AMD Ryzen 5 3600 6-Core Processor

Almost certainly [this](https://forums.developer.nvidia.com/t/known-limitations-with-cuda-on-wsl-2/128506).

**Comment by Erik-Sovereign** [comment]
@therealkenc 
Then I guess I will wait if a bug fix for that fixes my problem.
Thanks

**Comment by onomatopellan** [comment]
@Erik-Sovereign That's a problem in CUDA 10. If you follow the steps correctly you can get latest CUDA 11. I'm running it just fine in Ubuntu 19.10 with gcc 9.

Reading the Nvidia forums some Ryzen scenarios are fixed with drivers 455.41 and deviceQuery is not proof enough of a working CUDA. I'm waiting for Nvidia devs response to why my GT710 can't run nbody but can run deviceQuery.

**Comment by Erik-Sovereign** [comment]
@onomatopellan 
I will try it with CUDA 11.
Do you think my PyTorch Script will work with CUDA 11 too?

On a side note: Why do you think the CUDA 11 Toolkit will fix my problem? I thought it would be enough to download and install the Geforce Driver to my Windows System?

**Comment by therealkenc** [comment]
> GT710 can't run nbody but can run deviceQuery without problem.

Because the [deviceQuery](https://github.com/NVIDIA/cuda-samples/blob/master/Samples/deviceQuery/deviceQuery.cpp) sample does not have to exercise even a `cudaMalloc()`.

> can't run nbody

This is _probably_ not the demo I'd start with because [you know](https://github.com/ndd314/cuda_examples/blob/master/5_Simulations/nbody/nbody.cpp#L21). [I can't confirm or deny that _won't_ work with a software renderer, mind.]

> Ryzen scenarios are already fixed with drivers 455.41

It can't add yet with my Ryzen and RTX with the 455.41 drivers. But then I wouldn't expect it to quite yet, given the aforementioned known limitation.

```
#include <stdio.h>

__global__ void add(int *a, int *b, int *c) 
{
    *c = *a + *b;
}

int main(void) 
{
    int a, b, c;
    int *d_a, *d_b, *d_c;

    cudaMalloc((void **)&d_a, sizeof(int));
    cudaMalloc((void **)&d_b, sizeof(int));
    cudaMalloc((void **)&d_c, sizeof(int));

    a = 2;
    b = 2;
    c = 0;

    cudaMemcpy(d_a, &a, sizeof(int), cudaMemcpyHostToDevice);
    cudaMemcpy(d_b, &b, sizeof(int), cudaMemcpyHostToDevice);

    add<<<1,1>>>(d_a, d_b, d_c);

    cudaMemcpy(&c, d_c, sizeof(int), cudaMemcpyDeviceToHost);

    cudaFree(d_a);
    cudaFree(d_b);
    cudaFree(d_c);

    printf("result: %d\n", c);

    return 0;
}
```

![image](https://user-images.githubusercontent.com/7049700/85339810-be10f600-b499-11ea-863d-7da4363e2ef2.png)

**Comment by onomatopellan** [comment]
@therealkenc I used nbody because is the first thing nvidia tests in their tutorial via [nvidia-docker](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#running-containers). I guess the benchmark argument doesn't use x11/GL.

Thanks for the code, I'll try it but I think CUDA+WSL2 just doesn't work yet in kepler gpus.

**Comment by Erik-Sovereign** [comment]
@onomatopellan I see, thanks.
I will just report it to the NVIDIA Forum.

**Comment by Erik-Sovereign** [comment]
NVIDIA wrote in the forum the 455.41 driver fixed the AMD Ryzen issue.
My problem persists.

**Comment by Erik-Sovereign** [comment]
Created more reproducible example at https://github.com/microsoft/WSL/issues/5477
