### ISSUE TITLE
/lib/modules is empty

### ISSUE THREAD

**Issue by crgarcia12** [microsoft/WSL#5464]
# Environment

Windows build number:  10.0.19041.0
Your Distribution version: Ubuntu Release 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020

# Steps to reproduce

Trying to create a kernel module. I normally build it like this:

`make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules`

but WSL does not contains header and `sudo apt search linux-headers-4.19.104-microsoft-standard  `does not bring anything

# Actual behavior

folder /lib/modules is empty, and I cannot find the modules i should include in there

**Comment by therealkenc** [comment]
The linux kernel is [over here](https://github.com/microsoft/WSL2-Linux-Kernel). That kernel does not ship with your distribution.
