### ISSUE TITLE
can not chroot to centos6 rootfs

### ISSUE THREAD

**Issue by zltl** [microsoft/WSL#5465]
# Environment

My Windows build number:
```none
PS C:\Users\liaot> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```
My Distribution version:
Ubuntu Release:        20.04

```
cat /proc/version:
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce

1. Download a centos6 rootfs from https://github.com/CentOS/sig-cloud-instance-images/tree/CentOS-6.10/docker

2. Extract it on wsl:
```
mkdir -p /fakeroot/c6
cp /path/to/centos-6-docker.tar.xz /fakeroot/c6
cd /fakeroot/c6
tar -xpf centos-6-docker.tar.xz  --numeric-owner
chroot /fakeroot/c6
```

#  Expected behavior

chroot to /fakeroot/c6

# Actual behavior

```
Segmentation fault (core dumped)
```

**Comment by zltl** [comment]
Then I try centos7 rootfs and gentoo stage3, chroot work well both.

chroot to Centos6 rootfs work on real linux.

**Comment by therealkenc** [comment]
```
138   rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
138   --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600400} ---
```

> chroot to Centos6 rootfs work on real linux.

That depends on the disposition of the Real Linux in question about vsyscalls.

/dupe #4694 ([message](https://github.com/microsoft/WSL/issues/4694#issuecomment-556095344)) aka #1462
