### ISSUE TITLE
mkdir command returning "bad address" on ubuntu distro wsl2

### ISSUE THREAD

**Issue by dev-uditraj** [microsoft/WSL#5469]
I am on windows 10 2004 with wsl2 running Ubuntu with wsl 2.

NAME STATE VERSION
Ubuntu Running 2

My c drive is mounted as below:
`uditr@u-PC:/mnt$ ls -la`
`total 8`
`drwxr-xr-x  4 root  root  4096 Jun 22 04:45 .`
`drwxr-xr-x 19 root  root  4096 Jun 23 16:21 ..`
`drwxrwxrwx  1 uditr uditr 4096 Jun 23 12:05 c`
`drwxrwxrwt  2 root  root    40 Jun 23 16:21 wsl`

when I try to create a folder using mkdir command, it returns the following:

`uditr@u-PC:/mnt/c/Users/uditr$ cd desktop`
`uditr@u-PC:/mnt/c/Users/uditr/desktop$ mkdir myfolder`
`mkdir: cannot create directory ‘myfolder’: Bad address`

when the distro was in `wsl version 1`, `mkdir` command worked just fine, the problem is with `wsl2`.

After this error, c drive unmounts and no file level command works
ls also returns the following:

`uditr@u-PC:/mnt/c/Users/uditr/desktop$ ls`
`ls: cannot open directory '.': Input/output error`

After this, when I check back the mnt folder I get the following result.
`uditr@u-PC:/mnt$ ls -la`
`ls: cannot access 'c': Input/output error`
`total 8`
`drwxr-xr-x 4 root root 4096 Jun 22 04:45 .`
`drwxr-xr-x 19 root root 4096 Jun 23 16:13 ..`
`d????????? ? ? ? ? ? c`
`drwxrwxrwt 2 root root 40 Jun 23 16:11 wsl`

**Comment by sirredbeard** [comment]
Can you please attach an strace output of the command failing?

Because you can't cp it to /mnt/c right now, try:

```
sudo apt install -y strace 
strace -o output.txt mkdir /mnt/c/Users/uditr/test
cat output.txt | clip.exe
```
Then open notepad/other editor, paste in log, save and attach.

**Comment by alexpenedo** [comment]
Same issue here. I can reproduce it trying to create a folder inside the mounted drive C: from wsl.
Ouput is attached here: [output.txt](https://github.com/microsoft/WSL/files/5504499/output.txt)

**Comment by therealkenc** [comment]
> uditr@u-PC:/mnt/c/Users/uditr/desktop

Before getting into the EIO state, what is the output of:

```
$ ls /mnt/c/Users/uditr/[dD]esktop
$ cmd.exe /c 'dir C:\Users\uditr' | grep -i desktop 
```

For me looks like:

![image](https://user-images.githubusercontent.com/7049700/117380568-d2ca6280-ae8e-11eb-9e11-6dadf4bef8d1.png)

...which is expected behavior. No 'desktop' subfolder, absent some deliberate steps to create one.

The reason I ask is "Users\you\desktop" is a _really_ unusual folder name to create under your Windows home. The `Desktop` path you see in Windows Explorer is not actually a directory.

**Comment by volk-christian** [comment]
As I run into the same issue, I want to repoen this ticket again.

I studied the information given by @sirredbeard and @therealkenc and can provide following additional information:
My test happens within a directory on windows drive C: which is called workspace.

Using windows CMD, I am able to list the directory content:

```
C:\workspace>dir
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: CAD6-A6CA

 Verzeichnis von C:\workspace

01.06.2021  08:03    <DIR>          .
01.06.2021  08:03    <DIR>          ..
01.06.2021  08:03    <DIR>          BCOM
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 389.844.418.560 Bytes frei
```

Now I try to list the same content in WSL2 (OK) and create a new subdirectory (notOK).
After the mkdir failure, even listing the content is not possible anymore:

```
cv@ubuntu -> ~ $ cd /mnt/c/workspace
cv@ubuntu -> /mnt/c/workspace $ ls -l
total 0
drwxrwxrwx 1 cv cv 512 Jun  1 08:03 BCOM

cv@ubuntu -> /mnt/c/workspace $ strace -o ~/output.txt mkdir test
mkdir: cannot create directory ‘test’: Bad address

cv@ubuntu -> /mnt/c/workspace $ strace -o ~/output2.txt ls -l
ls: cannot open directory '.': Input/output error
```

Please find attached the strace output of the commands:
[output.txt](https://github.com/microsoft/WSL/files/6583801/output.txt)
[output2.txt](https://github.com/microsoft/WSL/files/6583803/output2.txt)

After this failure, all windows executables additionally seem not to be available anymore:
```
cv@ubuntu -> ~ $ cat output.txt | clip.exe
zsh: Input/output error: clip.exe
```

Additional system information:

```
C:\workspace>ver
Microsoft Windows [Version 10.0.19042.985]

C:\workspace>wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
  Debian          Stopped         2
```

**Comment by mknj** [comment]
I can reproduce this issue, what info do you need to debug the issue?

**Comment by MooiestCow** [comment]
I ran into this issue when running "Ubuntu 20.04 LTS" from the Windows Store, the issue fixed for me when I reinstalled with just the "Ubuntu" installation. Not sure about the technical details though.

**Comment by volk-christian** [comment]
I still do have this issue regardless of using ubuntu or ubuntu20.04.
Still waiting for any hint how to fix this!
