### ISSUE TITLE
[wsl1] WSLHost eventually incorrectly tracks uptime

### ISSUE THREAD

**Issue by klikevil** [microsoft/WSL#5470]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17134.0 Microsoft Windows NT 10.0.17134.0

kali-rolling
Linux D5DZ5WT2 4.4.0-17134-Microsoft #1488-Microsoft Mon May 05 16:17:00 PST 2020 x86_64 GNU/Linux
$ lsb_release -r
Release:	2020.2

# Steps to reproduce

Difficult to determine...  leaving the shell open for a long period of time creating ssh connections every day eventually ssh just stops spawning a pty and when this occurs you also can't run commands over an ssh connection.

(e.g. ssh host uname -a)

What I have noticed when this occurs:

period@D5DZ5WT2 ~ $ cat /proc/uptime
4294083938.4294967263 3174791.47

<pre>root@D5DZ5WT2:~# uptime
 12:34:16 up -24855 days, -3:-14,  0 users,  load average: 0.52, 0.58, 0.59
root@D5DZ5WT2:~#</pre>

running sysinfo in command prompt gave this:
System Boot Time:          6/12/2020, 5:18:29 AM

So it may occur after 11 or more days of uptime but I can't be certain of this, the only solution I have found when this occurs is to use process explorer and restart wslhost, exit my shell and spawn a new one.

#  Expected behavior

ssh to always work and uptime to be tracked correctly

# Actual behavior

/proc/uptime jumps to an absurdly high number and ssh breaks (it still is able to initiate the connection but a pty is never allocated and no commands can be sent to the remote host)

**Comment by therealkenc** [comment]
> 17134

/dupe #3514
