### ISSUE TITLE
WSL 2 only uses 1 CPU socket on multiple socket systems

### ISSUE THREAD

**Issue by theblinkingman** [microsoft/WSL#5472]
When running an Ubuntu 18.04 image under WSL 2, only one CPU socket is detected.  
On the Ubuntu system lscpu reports
```
CPU(s): 40
Thread(s) per core: 2
Core(s) per socket: 20
Sockets(s): 1
Model Name: Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz
```
nproc also returns 40

On the Windows system running Version 2004 Microsoft Windows [Version 10.0.19041.329]
systeminfo
```
Processor(s): 2 Processors(s) Installed
[01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~1995 Mhz
[02]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~1995 Mhz
```
And 80 local cores are reported.  

When compiling code, only 40 of the 80 cores are utilized.  

Expected behavior is that all 80 cores are available inside WSL and that CPU intensive tasks (like compiling code) utilize all available resources.  

Maybe related to #5423 but this issue is specifically for multiple socket systems.

**Comment by sr229** [comment]
I think this has to deal with Hyper-V scheduling the VM to just one socket and not two.

**Comment by sr229** [comment]
I think GH-5423 is related to this.

**Comment by muratyurdakul75** [comment]
Hi

Unfortunately, there is no development on this issue. There are constant requests on this issue, but they are marked as "duplicate requests" and directed to old notifications. Is there any development?

Actually, there are multiple expectations regarding this NUMA issue;
1> More than one NUMA needs to be supported.
2> It needs to be able to work with more than 64 processors.
3> We need to be able to decide which NUMA it will work on. (There may be those who want it to work on only one NUMA)

It would be really great if such a development could be made.

Thank you in advance for your efforts.
