### ISSUE TITLE
Creating a user with an emoji username causes partial failure

### ISSUE THREAD

**Issue by AskAlice** [microsoft/WSL#5473]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

![image](https://user-images.githubusercontent.com/1855905/85474668-3fd45280-b572-11ea-8ed5-256017be3bb6.png)

![image](https://user-images.githubusercontent.com/1855905/85474640-377c1780-b572-11ea-865d-6e4fb0839309.png)

#  Expected behavior
it should either not allow you to create such a user since the directory fails to create, or it should allow you to create the directory.

# Actual behavior
the directory creation fails, causing a cascade of other issues

**Comment by therealkenc** [comment]
> /etc/profile.d/wsl-integration.sh
> it should

Home for that project ('it') is [here](https://github.com/wslutilities/wslu) and [here](https://launchpad.net/wslu). In any event, it looks like you are missing a [`-m`](https://www.man7.org/linux/man-pages/man8/useradd.8.html) on your useradd. Nothing to do with emojis. I'm guessing `wslu` takes as given a user will have a home directory.

![image](https://user-images.githubusercontent.com/7049700/85484385-9abe7780-b57b-11ea-8b2f-3b42fba0faee.png)
