### ISSUE TITLE
Initializing WSL 2 with more than 250GB of swap space fails

### ISSUE THREAD

**Issue by PershingSquare** [microsoft/WSL#5476]
# Environment

Windows build number: 10.0.20150.0

Your Distribution version: (Debian) Linux version 4.19.121-microsoft-WSL2-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Thu May 14 20:25:24 UTC 2020
Whether the issue is on WSL 2 and/or WSL 1: WSL 2

# Steps to reproduce
1. Create a `.wslconfig` file with the following items.

Note that drive E is an empty drive with around 512GB of free space.

```
[wsl2]

memory=8GB
swap=256GB
swapFile=E:\\swap.vhdx
```

2. In PowerShell run, `wsl --shutdown Debian`

3. Open up wsl and type in `free -m`

#  Expected behavior

`free -m` should report something similar to this.

```
              total        used        free      shared  buff/cache   available
Mem:           7972         256        7655           0          59        7556
Swap:        256000           0      256000
```

# Actual behavior

However actually it reports this.

```
              total        used        free      shared  buff/cache   available
Mem:           7972         256        7655           0          59        7556
Swap:          0            0          0
```

**Comment by benhillis** [comment]
You are correct, the current limit is a hair under 256GB.  Is this causing issues for you or just something you noticed while playing around?

I suspect you see an error something like this in your dmesg?
`[    1.942164] ERROR: CreateSwap:770: fallocate failed 28`

**Comment by zzjin** [comment]
Any update here? When using wsl2 +gpu for ml matrix calc, I bought 128GB(64x4) memory but need 256GB+ more memory.
On hard linux machine I can set swap with 512GB(one entire ssd), but cannot set on wsl2?

**Comment by woreom** [comment]
Hi, I'm encounter the same problem

**Comment by chag** [comment]
you may be able to create multiple swap files for the same effect

**Comment by ACastanza** [comment]
@therealkenc the inability to assign large amount of virtual memory to WSL2 continues to be an issue on current builds (including Windows 11). I've been able to fully reproduce the behavior described by the original author. Can we get this issue reopened?

**Comment by brianmingus2** [comment]
Don't specify the swap file.

```mingus@DESKTOP-P1AOA9A:/mnt/c/Users/BrianMingus$ cat .wslconfig
[wsl2]

memory=16GB
swap=100GB
```

**Comment by ACastanza** [comment]
> Don't specify the swap file.
> 
> ```
> [wsl2]
> 
> memory=16GB
> swap=100GB
> ```

100GB is not a large enough swap file to trigger this bug. The threshold is somewhere between 128GB (could not reproduce) and 256GB (could reproduce).

**Comment by brianmingus2** [comment]
On my Windows 11 system specifying the swap file causes it to not work at all.

**Comment by ACastanza** [comment]
That is very strange. I'm also running Windows 11 and have it working with a specified swapfile.
My working .wslconfig file:
```

[wsl2]
memory=96GB
swap=128GB
swapFile=%USERPROFILE%\AppData\Local\Temp\swap.vhdx


```
(placed in my %UserProfile%)

**Comment by woreom** [comment]
> That is very strange. I'm also running Windows 11 and have it working with a specified swapfile.
> My working .wslconfig file:
> 
> ```
> 
> [wsl2]
> memory=96GB
> swap=128GB
> swapFile=%USERPROFILE%\AppData\Local\Temp\swap.vhdx
> ```
> 
> (placed in my %UserProfile%)

deleting the swap.vhdx and restarting wsl will usually fix this

**Comment by ribsthakkar** [comment]
The pattern I noticed is that it only works when I set the swap limit to 128GB or less. I am running 10.0.19042.
Is it possible to indicate multiple swap files? Trying to list several comma separated files did not work for me.

**Comment by jokumo** [comment]
As a reference for others: The maximum size in `.wslconfig` on my machine is 250GB. This results in a total swap of:
262144000 Bytes, or
256000 MB, (2^8*1000) or
250 GB
![image](https://user-images.githubusercontent.com/16837904/167244701-52a7a0aa-388c-4fa4-91e8-1cc1758aee9e.png)

**Comment by xnohat** [comment]
Workaround for adding more Swap file

.wslconfig
```
[wsl2]
kernelCommandLine = vsyscall=emulate
processors=2
memory=2GB
swap=250GB
swapFile=c:\\wslswapfile.vhdx
```

WSL2 will auto create swapfile.vhdx with maximum 250GB in size (preset but not allocated dynamic vhdx disk)
For create more swap than 250GB limit use trick below
Install WSL2 Preview from Microsoft Store first: https://www.microsoft.com/store/productId/9P9TQF7MRM4R
1. .wslconfig with swap=250GB and correct swapFile path, save
2. Powershell: wsl --shutdown
3. delete .vhdx file in path
4. PS: start wsl by typing wsl.exe again & exit
5. "Duplicate" (copy-paste) new created wslswapfile.vhdx to wslswapfile2.vhdx
6. PS: wsl --shutdown again
7. start wsl by enter your distro bash shell (ex: Ubuntu)
8. bash: wsl.exe --mount --vhd c:\\wslswapfile.vhdx --name newswap  (command from here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)
9. bash: swapon /mnt/wsl/newswap
10. bash: free -mh to check new swap applied
11. repeat procedure above many times until meet your SWAP size need. Current linux kernel support up to 35 Swap Files
Notes: all swap files mounted will lose after restart WSL, so we need run command mount and swapon  every WSL start or create a startup script for that

**Comment by ibecodinghard** [comment]
Why is this closed? Issue still exists.

**Comment by ericblade** [comment]
.... swap file fails for me with 32gb.  Is the limitation not a constant at 250GB, or is there some variable involved?

**Comment by ericblade** [comment]
I've been unable to get swap mounted in my system for a *while*, noticed that the swap file existed, but wasn't getting loaded into any wsl instances.  Deleted the existing swapfile, did a wsl --shutdown and opened my distro again, and lo and behold, 32gb swap mounted!
