### ISSUE TITLE
OCI runtime create failed: container_linux.go:349

### ISSUE THREAD

**Issue by richardlgit** [microsoft/WSL#5480]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT            10.0.19041.0  Microsoft Windows NT 10.0.19041.0

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
/mnt/c/WINDOWS/system32$ lsb_release -r
Release:        20.04

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
/mnt/c/WINDOWS/system32$ cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

/mnt/c/WINDOWS/system32$ uname -a
Linux Auto-Edge-Windows10-02 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

PS C:\WINDOWS\system32> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         1
  docker-desktop         Running         2
  docker-desktop-data    Running         2

```
# Steps to reproduce
I have a docker image (niagara.img) and docker compose file (niagara.yml). This is for the Niagara server from Tridium 
I create a docker volume 
C:\Users\QE-User\Downloads\Niagara> docker volume create --name=niagara
I load the images using following command
C:\Users\QE-User\Downloads\Niagara> docker load -i niagara.img
Image is successfully loaded
I then run docker-compose and I get the error after running the below command
C:\Users\QE-User\Downloads\Niagara> docker-compose -f niagara.yml up -d

#  Expected behavior

I expect the docker services to start and the niagara sever to be up and running. This is working fine on AWS instance of Ubuntu

# Actual behavior

PS C:\Users\QE-User\Downloads\Niagara> docker-compose -f niagara.yml up -d
Starting niagara ... error

ERROR: for niagara  Cannot start service niagara: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/90d356f172209ed1507d72e09a12e78c9cbba8a41f548a73e05566cd929ca601/merged\\\" at \\\"/var/lib/docker/overlay2/90d356f172209ed1507d72e09a12e78c9cbba8a41f548a73e05566cd929ca601/merged/usr/share/zoneinfo/UTC\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for niagara  Cannot start service niagara: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/90d356f172209ed1507d72e09a12e78c9cbba8a41f548a73e05566cd929ca601/merged\\\" at \\\"/var/lib/docker/overlay2/90d356f172209ed1507d72e09a12e78c9cbba8a41f548a73e05566cd929ca601/merged/usr/share/zoneinfo/UTC\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

I have followed instructions from another forum to upgrade from wsl to wsl2 - https://github.com/microsoft/WSL/issues/5100

**Comment by onomatopellan** [comment]
```
PS C:\WINDOWS\system32> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         1
```
Your Ubuntu distro is still running in version 1. You will need to upgrade it to version 2 first.
To do that disable Real Time Protection in Windows Security and run this from cmd/PowerShell:
`wsl.exe --set-version Ubuntu 2`

After that with `wsl.exe -l -v` you can see if it's version 2. If so you can install the latest kernel  https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by therealkenc** [comment]
There might be something to this given the special handling of `/etc/localtime` by WSL. An actual CLI repro (which would be long and detailed) might give this submission a chance. You _possibly_ (?) will get better eyeballs in a Windows Docker forum, but the teams do work together so this issue can at least float for a bit. Ono is basically correct though. There is a pretty much baked in assumption (for better or worse) that if you are running Windows Docker with the WSL backend, you're also all-in on WSL2 not WSL1. But there might be something actionable here.

**Comment by richardlgit** [comment]
Thank you both. After upgrading to ubuntu to version 2 it still throws the same error. 

````
 PS C:\WINDOWS\system32> wsl.exe -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
````
But if I remove /et/localtime from the .yml file it works with no issues. This is not the case on another Windows machine with almost same specs running  same version of Windows. What is so special about this machine - I am not able to understand.

**Comment by therealkenc** [comment]
> What is so special about this machine - I am not able to understand.

Probably not going to get many guesses here. You were running `docker.exe` _from Windows_, so upgrading your Ubuntu to WSL2 was a red herring. Uneducated guess the issue might be somehow tangentially related to docker/for-win#4812.
