### ISSUE TITLE
PCI Devices not showing up in WSL

### ISSUE THREAD

**Issue by d-colwell** [microsoft/WSL#5485]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20150.1000]
Your Distribution version: Release:        18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
Kernel: 4.19.121-microsoft-standard
```

# Steps to reproduce
Have a machine with 2 GPUs on it, install the latest nvidia drivers
![image](https://user-images.githubusercontent.com/19940171/85659979-6cb27200-b6f8-11ea-9859-a9854ee7d5a7.png)
Run sudo lspci

#  Expected behavior

Expect 2 NVidia devices to show up, instead two Microsoft 3D drivers showed up
![image](https://user-images.githubusercontent.com/19940171/85660531-142fa480-b6f9-11ea-8300-991e95efc8f6.png)

tried the same with `lshw -C DISPLAY`
![image](https://user-images.githubusercontent.com/19940171/85660651-39241780-b6f9-11ea-817d-270c3b359555.png)

# Caveat
You can still use the GPUs using pytorch, and Pytorch is able to locate them and give them the correct names. 
![image](https://user-images.githubusercontent.com/19940171/85660878-7c7e8600-b6f9-11ea-85d3-06d73dea1c62.png)

**Comment by therealkenc** [comment]
That's pretty much by design. You don't have a TITAN RTX on the PCI bus in WSL anymore than you have a SCSI Controller on your PCI bus. It isn't PCI-passthough, nor can it be because you Windows wants to use those devices too. [Which as an aside is pretty amazing.]
