### ISSUE TITLE
Cannot connect to MongoDB server installed on Windows from WSL2

### ISSUE THREAD

**Issue by zashishz** [microsoft/WSL#5486]
# Environment

```none
Windows build number:  Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Release: 18.04
Whether the issue is on WSL 2 and/or WSL 1:  Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

I cannot connect to MongoDB server running on Windows 10 from WSL2.
- it was working in WSL1 via `mongodb://user:pass@localhost:27017/dbname`
- I have tried steps mentioned in [official guide](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications)
- I have also tried Network reset

On ubuntu WSL2
- `cat /etc/resolv.conf` returns `nameserver 192.168.176.1`
- ping 192.168.176.1 **works**
- ping www.google.com **works**

But i am **not able to connect** to mongodb on windows via same ip i.e **192.168.176.1**.
```javascript
mongoose
  .connect(`mongodb://user:pass@192.168.176.1:27017/dbname`,
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }
  )
  .then((msg) => {
    console.log("Successfully Connected via mongoose!");
  })
  .catch((err) => console.log("Error", err));
```

- Also tried bind mongodb server application to 0.0.0.0 **doesn't work**
![wsl](https://user-images.githubusercontent.com/11209820/85666988-bab87d00-b6da-11ea-9640-75ba6c0ded2d.png)

#  Expected behavior

I should be able to connect to MongoDB server running on Windows 10 via the WSL ip returned while running `cat /etc/resolv.conf`

# Actual behavior
Unable to connect **connection timed out Error**

**Comment by therealkenc** [comment]
What is the output of:

```
$ netstat.exe -na | grep 27017
```

**Comment by zashishz** [comment]
```none
$ashish:~ netstat.exe -na | grep 27017
  TCP    127.0.0.1:27017        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:27017        127.0.0.1:65277        ESTABLISHED
  TCP    127.0.0.1:27017        127.0.0.1:65278        ESTABLISHED
  TCP    127.0.0.1:27017        127.0.0.1:65280        ESTABLISHED
  TCP    127.0.0.1:27017        127.0.0.1:65281        ESTABLISHED
  TCP    127.0.0.1:65277        127.0.0.1:27017        ESTABLISHED
  TCP    127.0.0.1:65278        127.0.0.1:27017        ESTABLISHED
  TCP    127.0.0.1:65280        127.0.0.1:27017        ESTABLISHED
  TCP    127.0.0.1:65281        127.0.0.1:27017        ESTABLISHED
```

**Comment by onomatopellan** [comment]
In WSL1:
* mongodb server running in Windows in port 27017
* from WSL1 use `mongodb://user:pass@localhost:27017/dbname`

In WSL2:
* mongodb server running in Windows in port 27017
* from WSL2 use `mongodb://user:pass@IP_HOST:27017/dbname`

Don't modify anything from the windows side (the 0.0.0.0 bind is only for servers running inside WSL2)
IP_HOST is the IP of your PC you can get with ipconfig.exe.
If the Firewall ask for permission say yes to private and public.

**Comment by zashishz** [comment]
> In WSL1:
> * mongodb server running in Windows in port 27017
> * from WSL1 use `mongodb://user:pass@localhost:27017/dbname`
> 
> In WSL2:
> * mongodb server running in Windows in port 27017
> * from WSL2 use `mongodb://user:pass@IP_HOST:27017/dbname`
> 
> Don't modify anything from the windows side (I think the 0.0.0.0 bind is only for servers running inside WSL2)
> IP_HOST is the IP of your PC you can get with ipconfig.exe.
> If the Firewall asks for permission say yes to private and public.

Yes, i have already reverted 0.0.0.0 bind ip changed and tried but nothing works.

**Comment by onomatopellan** [comment]
At this point it can be Firewall related. Stop the server and, if you are not using a 3rd party firewall, then open "Windows Defender Firewall with advanced security". In Inbound Rules delete everything you find about mongod.exe.
Run the server again but this time check **Private** and **Public** before accepting.

**Comment by onomatopellan** [comment]
Ok, I have been testing with mongodb portable and you need indeed to run the mongod server on windows with the argument `--ip_bind_all` or `ip_bind 0.0.0.0`.
After that `mongo --host IP_HOST` connects to the server from WSL2 without issue.

**Comment by zashishz** [comment]
Thanks @onomatopellan ,
Starting mongoDB server as:
`mongod.exe --bind_ip 0.0.0.0`
Worked for me :)

**Comment by adspacheco** [comment]
Same problem here.

**Windows**
`mongod --bind_ip 0.0.0.0`

```
2020-06-26T16:20:33.577-0300 I  NETWORK  [listener] Listening on 0.0.0.0
2020-06-26T16:20:33.577-0300 I  NETWORK  [listener] waiting for connections on port 27017
```

_WiFi Adapter_
```
IPv4. . . . . . . .  . . . . . . . : 192.168.0.15
DHCP . . . . . . . . . . . . . . . : 192.168.0.1
```

_Ethernet vEthernet (WSL):_
`IPv4. . . . . . . .  . . . . . . . : 172.21.96.1`

Firewall off.

**WSL2**

```
~ » netstat.exe -na | grep 27017                                                                              
TCP    0.0.0.0:27017          0.0.0.0:0              LISTENING
TCP    127.0.0.1:27017        0.0.0.0:0              LISTENING
```

Tried to connect all ips:

```
2020-06-26T16:25:46.378-0300 E  QUERY    [js] Error: couldn't connect to server 0.0.0.0:27017, address resolved to 0.0.0.0 :

2020-06-26T16:26:12.961-0300 E  QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :

2020-06-26T16:28:07.007-0300 E  QUERY    [js] Error: couldn't connect to server 192.168.0.15:27017, connection attempt failed: SocketException: Error connecting to 192.168.0.15:27017 :: caused by :: Connection timed out :

2020-06-26T16:28:22.285-0300 E  QUERY    [js] Error: couldn't connect to server 192.168.0.1:27017, connection attempt failed: SocketException: Error connecting to 192.168.0.1:27017 :: caused by :: Connection refused :

2020-06-26T16:31:34.393-0300 E  QUERY    [js] Error: couldn't connect to server 172.21.96.1:27017, connection attempt failed: SocketException: Error connecting to 172.21.96.1:27017 :: caused by :: Connection timed out :
```

**Comment by tmushayahama** [comment]
In addition to the above solution of bind_ip 0.0.0.0, I was able to connect by allowing my path to mongod.exe to the inbound rules on (Windows firewall Firewall -> Advanced Settings). I don't know how safe it is but it is working for now.

![image](https://user-images.githubusercontent.com/2273929/93999753-0ebf1600-fd4b-11ea-9eb3-94a68e45d143.png)

**Comment by MKrupauskas** [comment]
I had to change the binding ip in `C:\Program Files\MongoDB\Server\4.2\bin\mongod.cfg` to 0.0.0.0
```
# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0
```

Then I got the IP for my PC by running the command `ipconfig` in `cmd` and copied the IPv4 Address. 

I could then finally connect to my Windows MongoDB server from Linux wsl2

**Comment by Justinqb** [comment]
> In addition to the above solution of bind_ip 0.0.0.0, I was able to connect by allowing my path to mongod.exe to the inbound rules on (Windows firewall Firewall -> Advanced Settings). I don't know how safe it is but it is working for now.
> 
> ![image](https://user-images.githubusercontent.com/2273929/93999753-0ebf1600-fd4b-11ea-9eb3-94a68e45d143.png)

This worked for me

**Comment by aim97** [comment]
In my app I use the mongodb URL as
`mongodb://192.168.1.9:27017/MyApp`
Using fixed IP `192.168.1.9`, but whenever I disconnect from my router for any reason, the connection would fail, do I really need a a router for something that is only done on my machine? is there no other way such that the connection is made internally?.

**Comment by sylvix** [comment]
Yet another solution, more in one place:
1. While installing MongoDB on Windows, make sure you enable Windows service, otherwise you'll have to run it manually.
2. After installation edit `mongod.cfg` and set `bindIp` to `0.0.0.0` (see previous post by @MKrupauskas, thank you, BTW)
3. Go to Firewall and Network protection in Windows settings (Start -> type "Firewall" -> Enter)
4. Click "Allow an app through firewall" link in bottom part of the window
5. Click "Change settings", then button "Allow another app" will be enabled. Click it. Browse for "mongod.exe" executable (in `%Program Files%\MongoDB\Server\X.Y\bin`. Then click "Network types" and select both types. Then click "Add". 
6. It will add a set of rules to Defender Firewall that didn't work for some reason when added manually.
7. In WSL find host IP. On my machine `cat /etc/resolv.conf` works, after "nameserver" part. Or google for "wsl find host ip" there are plenty of solutions there.
8. `mongo %INSERT_HOST_IP_HERE%`

**Comment by sarunmrzn** [comment]
> Yet another solution, more in one place:
> 
> 1. While installing MongoDB on Windows, make sure you enable Windows service, otherwise you'll have to run it manually.
> 2. After installation edit `mongod.cfg` and set `bindIp` to `0.0.0.0` (see previous post by @MKrupauskas, thank you, BTW)
> 3. Go to Firewall and Network protection in Windows settings (Start -> type "Firewall" -> Enter)
> 4. Click "Allow an app through firewall" link in bottom part of the window
> 5. Click "Change settings", then button "Allow another app" will be enabled. Click it. Browse for "mongod.exe" executable (in `%Program Files%\MongoDB\Server\X.Y\bin`. Then click "Network types" and select both types. Then click "Add".
> 6. It will add a set of rules to Defender Firewall that didn't work for some reason when added manually.
> 7. In WSL find host IP. On my machine `cat /etc/resolv.conf` works, after "nameserver" part. Or google for "wsl find host ip" there are plenty of solutions there.
> 8. `mongo %INSERT_HOST_IP_HERE%`

Thanks this works great! but why is the address on `resolv.conf` different from the address thats shown in `ip addr`? for me just the nameserver from `resolve.conf` works

**Comment by silvesfj** [comment]
All this ands it still does not work

**Comment by AshakaE** [comment]
found a working solution, you basically replace the localhost with your windows ip address `localhost:27017` will be `YourWindowsIpAddress:27017` [reference](https://blog.codonomics.com/2020/08/connect-to-mongodb-on-windows-host-from.html)

**Comment by GeoffDavis2** [comment]
I tried SOOOO many things and nothing seemed to work, til I finally tried the steps outlined by by sylvix and sarunmrzn!!!

Something about using the Windows settings firewall (instead of just using Windows Defender Firewall) worked!!!

The instructions for that part was a little confusing so let me clarify it a little.

To get to the RIGHT firewall config...
- Right Click the Windows Start icon (at the bottom left)
- Click on "Settings"
- In the search box, type then click "Firewall & network protection"
- Then click on the "Allow an app through firewall"
- From there you can follow the steps outlined by sylvix and sarunmrzn

Don't forget the bind to 0.0.0.0 setting in mongod.cfg file.
Probably should turn off the mongodb service (if running before doing any of this).
Then turn the MongoDB service and test.
BTW, a quick and easy test would be to use telnet on the wsl/Ubuntu command line
`telnet <host ip from> 27017`
You can get the host ip, that wsl/Ubuntu uses for localhost by using the `cat /etc/resolv.conf` that is mentioned in this thread.
If the telnet command just sits there waiting, then not good.
If you see a connection, then you are good.

**Comment by i-rebel-aj** [comment]
Followed all the steps however MongoDB fails to establish a connection with WSL2
![image](https://user-images.githubusercontent.com/43892979/154819223-3d17427b-930b-49d7-8fc1-77a6fdb9cb41.png)

`telnet <IP> 27017` just waits

**Comment by AshakaE** [comment]
`172.28.48.1` is your wsl2 IP, what you need to use is your WiFi IP on your windows machine, the last value sometimes fluctuates from `100 - 101 or 1` ... I believe it starts with `192`

**Comment by ambroiseRabier** [comment]
Using my local IP address instead of localhost solved the issue for me, no need for `--bind_ip_all`. [Check this Stackoverflow response to get the IP address !](https://stackoverflow.com/a/70824215/7696155)

**Comment by Karl-Heinrich** [comment]
For anybody having the same problem, I want to add to the solution discussed here.

I was able to successfully connect to my database after allowing `MongoDB Database Server` to communicate through Windows Defender Firewall and setting `bindIp: 0.0.0.0` in `C:\Program Files\MongoDB\Server\5.0\bin\mongod.cfg`. For the connection, I use the either the LAN or WLAN IPv4 Address I receive when typing `ipconfig` in the windows command prompt. As described by @sylvix.

However, in my case, it would only allow a connection through WIFI (WLAN), not Ethernet (LAN). This was because in `Network & Internet settings`, I found out that only my WIFI network profile was set to `private`. My LAN connection was set to `public`. If you want to connect over LAN and WLAN, both have to be set as private networks.

This also means that when traveling, e.g. using some coffee shops or the airports WIFI (which should be set to public), your MongoDB connection will fail again. But since this is rarely the case, I think while travelling its ok to start the node server from windows where everything works as expected.

**Comment by snehel4510** [comment]
Even after going through the entire thread and completing every process that was mentioned above, i'm still hanging on with this error.
![image](https://user-images.githubusercontent.com/79275152/181934339-02d6d0c8-4a99-4540-811a-61c509dd409b.png)
I was hoping if someone could help and make me understand what's going wrong.

**Comment by cfigueiroa** [comment]
`mongosh $(grep nameserver /etc/resolv.conf | awk '{print $2}')`

**Comment by cfigueiroa** [comment]
> For anybody having the same problem, I want to add to the solution discussed here.
> 
> I was able to successfully connect to my database after allowing `MongoDB Database Server` to communicate through Windows Defender Firewall and setting `bindIp: 0.0.0.0` in `C:\Program Files\MongoDB\Server\5.0\bin\mongod.cfg`. For the connection, I use the either the LAN or WLAN IPv4 Address I receive when typing `ipconfig` in the windows command prompt. As described by @sylvix.
> 
> However, in my case, it would only allow a connection through WIFI (WLAN), not Ethernet (LAN). This was because in `Network & Internet settings`, I found out that only my WIFI network profile was set to `private`. My LAN connection was set to `public`. If you want to connect over LAN and WLAN, both have to be set as private networks.
> 
> This also means that when traveling, e.g. using some coffee shops or the airports WIFI (which should be set to public), your MongoDB connection will fail again. But since this is rarely the case, I think while travelling its ok to start the node server from windows where everything works as expected.

this worked for me. also, you can do the command below if u don't wanna check your ip with cat:

`mongosh $(grep nameserver /etc/resolv.conf | awk '{print $2}')`



> Yet another solution, more in one place:
> 
> 1. While installing MongoDB on Windows, make sure you enable Windows service, otherwise you'll have to run it manually.
> 2. After installation edit `mongod.cfg` and set `bindIp` to `0.0.0.0` (see previous post by @MKrupauskas, thank you, BTW)
> 3. Go to Firewall and Network protection in Windows settings (Start -> type "Firewall" -> Enter)
> 4. Click "Allow an app through firewall" link in bottom part of the window
> 5. Click "Change settings", then button "Allow another app" will be enabled. Click it. Browse for "mongod.exe" executable (in `%Program Files%\MongoDB\Server\X.Y\bin`. Then click "Network types" and select both types. Then click "Add".
> 6. It will add a set of rules to Defender Firewall that didn't work for some reason when added manually.
> 7. In WSL find host IP. On my machine `cat /etc/resolv.conf` works, after "nameserver" part. Or google for "wsl find host ip" there are plenty of solutions there.
> 8. `mongo %INSERT_HOST_IP_HERE%`

Thanks, that worked here as well. Here's a one liner for step 7 and 8:

`mongosh $(grep nameserver /etc/resolv.conf | awk '{print $2}')`

Keep in mind that this assumes that the IP address is the second field on the line that starts with nameserver (it is on my wsl2 Ubuntu)

**Comment by cfigueiroa** [comment]
> Yet another solution, more in one place:
> 
> 1. While installing MongoDB on Windows, make sure you enable Windows service, otherwise you'll have to run it manually.
> 2. After installation edit `mongod.cfg` and set `bindIp` to `0.0.0.0` (see previous post by @MKrupauskas, thank you, BTW)
> 3. Go to Firewall and Network protection in Windows settings (Start -> type "Firewall" -> Enter)
> 4. Click "Allow an app through firewall" link in bottom part of the window
> 5. Click "Change settings", then button "Allow another app" will be enabled. Click it. Browse for "mongod.exe" executable (in `%Program Files%\MongoDB\Server\X.Y\bin`. Then click "Network types" and select both types. Then click "Add".
> 6. It will add a set of rules to Defender Firewall that didn't work for some reason when added manually.
> 7. In WSL find host IP. On my machine `cat /etc/resolv.conf` works, after "nameserver" part. Or google for "wsl find host ip" there are plenty of solutions there.
> 8. `mongo %INSERT_HOST_IP_HERE%`

Those steps worked here, thanks a lot.

For steps 7 and 8 im using `mongosh $(grep nameserver /etc/resolv.conf | awk '{print $2}')` instead.

**Comment by vathanac** [comment]
> 8\. mongo %INSERT_HOST_IP_HERE%

What you mean by this. 
Should I run it in terminal? ` mongo %INSERT_HOST_IP_HERE%`
But it return `mongo: The term 'mongo' is not recognized as a name of a cmdlet, function, script file, or executable program.`

Run mongosh on wsl
`mongosh.exe 172.28.112.1
Current Mongosh Log ID: 63f0c5d935196bb906f09cc1
Connecting to:          mongodb://172.28.112.1:27017/?directConnection=true&appName=mongosh+1.7.1
MongoNetworkError: connect ECONNREFUSED 172.28.112.1:27017`

**Comment by geekyayush** [comment]
> Yet another solution, more in one place

You saved my life. Thank you <3

**Comment by longqua69** [comment]
> Yet another solution, more in one place:
> 
> 1. While installing MongoDB on Windows, make sure you enable Windows service, otherwise you'll have to run it manually.
> 2. After installation edit `mongod.cfg` and set `bindIp` to `0.0.0.0` (see previous post by @MKrupauskas, thank you, BTW)
> 3. Go to Firewall and Network protection in Windows settings (Start -> type "Firewall" -> Enter)
> 4. Click "Allow an app through firewall" link in bottom part of the window
> 5. Click "Change settings", then button "Allow another app" will be enabled. Click it. Browse for "mongod.exe" executable (in `%Program Files%\MongoDB\Server\X.Y\bin`. Then click "Network types" and select both types. Then click "Add".
> 6. It will add a set of rules to Defender Firewall that didn't work for some reason when added manually.
> 7. In WSL find host IP. On my machine `cat /etc/resolv.conf` works, after "nameserver" part. Or google for "wsl find host ip" there are plenty of solutions there.
> 8. `mongo %INSERT_HOST_IP_HERE%`

Thanks, I followed every step of this thread exactly but still got the issue when running step 8:
```bash
$ cat /etc/resolv.conf 
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.22.64.1
$ mongo 172.22.64.1
MongoDB shell version v5.0.22
connecting to: mongodb://172.22.64.1:27017/test?compressors=disabled&gssapiServiceName=mongodb
Error: network error while attempting to run command 'isMaster' on host '172.22.64.1:27017'  :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1
```

**Comment by whaaaley** [comment]
If you can't get it to work go into services (start menu), find "MongoDB Server (MongoDB), stop the service, and start it again.

**Comment by cmschlenke** [comment]
I read everything above and I STILL couldn't connect to MongoDB on Windows from WSL2. The thing that finally got it to work for me was actually editing the MongoDB config file as described above INSTEAD OF PASSING --bing_ip_all AS A FLAG. I thought that passing --bind_ip_all would be equivalent to setting the bind IP to 0.0.0.0 in the config file.... turns out I was wrong.

**Comment by rayan1242** [comment]
@cmschlenke can u explain how to add a --bing_ip_all as a flag

**Comment by rayan1242** [comment]
https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-windows-networking-apps-from-linux-host-ip

This did not work for me

**Comment by cmschlenke** [comment]
@rayan1242 I'm saying DO NOT pass --bind_ip_all as a flag. Go edit the MongoDB config file instead.

**Comment by huboh** [comment]
This is most likely windows blocking the connection.

first of all, check to see if you can ping your host (windows) from your wsl distro, obtain the host ip with 
```bash
```

**Comment by huboh** [comment]
Had the same issue, turned out it was window firewall blocking the connection. Here's how i solved it.

1. first thing, check if you can ping your host machine (windows) from WSL:
2. add a firewall exception:
3. configure mongoDB to accept external connections:
4. restart MongoDB:
5. connect to mongoDB from WSL:

**Comment by huboh** [comment]
> [@rayan1242](https://github.com/rayan1242) I'm saying DO NOT pass --bind_ip_all as a flag. Go edit the MongoDB config file instead.

Check your windows firewall, It was the cause for me. I wrote about it here https://stackoverflow.com/a/79080712/16362460

**Comment by danqdinh** [comment]
Sum up, I got to use all these together:
* Set in mongod.cfg `bindIp: 0.0.0.0` (then restart MongoDB service with `services.msc`)
* Disable Windows firewall for MongoDB port `27017`
* MongoDB URL will work in WSL with only IP from `ipconfig` / `ifconfig`, not loopback 'localhost' nor '127.0.01'
