### ISSUE TITLE
musl support of libdxcore.so and libd3d12.so

### ISSUE THREAD

**Issue by 12101111** [microsoft/WSL#5487]
**Is your feature request related to a problem? Please describe.**
libdxcore.so and libd3d12.so only support glibc base linux distro

**Describe the solution you'd like**
Provied variant of libdxcore.so and libd3d12.so that link against musl

**Describe alternatives you've considered**
Maybe open source dx12 on linux?

**Comment by therealkenc** [comment]
It might be able to get it to work with [gcompat](https://github.com/AdelieLinux/gcompat) and a lot of effort.

**Comment by benhillis** [comment]
@12101111 - Those binaries should work with either glibc or musl.  You should be able to get it working by including those paths via [ldconfig](https://wiki.musl-libc.org/faq.html#Q:-Where-is-%3Ccode%3Eldconfig%3C/code%3E?).

**Comment by therealkenc** [comment]
There is are some `GLIBC_` symbols in `libcuda.so`.

![image](https://user-images.githubusercontent.com/7049700/86324294-36db2500-bbf3-11ea-8160-7adb43827a16.png)
