### ISSUE TITLE
wsl2 IP

### ISSUE THREAD

**Issue by root2018zh** [microsoft/WSL#5490]
**Is your feature request related to a problem? Please describe.**
Wsl2 can't get the default IP, I feel very disappointed. The network function of wsl2 is not as good as that of wsl1. The more products are made, the more backward they are

**Describe the solution you'd like**
I hope to give wsl2 the same IP address or the same segment address as windows

**Comment by sr229** [comment]
localhost forwarding has been included in WSL2 since 20H1, its enabled by default.
