### ISSUE TITLE
WSL2 AMD Radeon GPU support

### ISSUE THREAD

**Issue by Kayzh3r** [microsoft/WSL#5495]
Hi all,
First of all, thanks for WSL it's amazing having Linux on Windows. It is possible to install the ROCm framework on WSL2? I can't find any GPU through the command line.

It should be amazing running Neural Network acceleration with the ROCm framework in WSL. Thanks so much

**Comment by onomatopellan** [comment]
Not yet. OpenCL and OpenGL support is coming. they will work in WSL2 on top of d3d12.
https://devblogs.microsoft.com/directx/in-the-works-opencl-and-opengl-mapping-layers-to-directx/

For now just CUDA for NVIDIA and DirectML for AMD/Intel.

**Comment by Kayzh3r** [comment]
Thanks so much for your answer.

**Comment by cycleuser** [comment]
still no news?

**Comment by f1am3d** [comment]
bump

**Comment by farhansarker0412** [comment]
bump

**Comment by asleepace** [comment]
bump

**Comment by danieljemoore** [comment]
bump

**Comment by ftwftw0** [comment]
bump

**Comment by onomatopellan** [comment]
AMD official support is here. Only for Radeon 7000 series.

https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/howto_wsl.html
