### ISSUE TITLE
Can't no longer access to websites

### ISSUE THREAD

**Issue by exetak** [microsoft/WSL#5497]
I'm trying this new feature on windows to test some application, i got an ubuntu 20.04 distro where i installed LAMP services. I know now that the system change ip address when reboot Windows, alredy was working vtiger for testing but now no i can;t no longer access, i tried a lot of things what i found on internet, but can get the website get up again everyting seems to be working,

When run curl -v shows me the ip address that the system got when everything was working

 curl -v http://172.25.79.147
*   Trying 172.25.79.147:80...
* TCP_NODELAY set
* Connected to 172.25.79.147 (172.25.79.147) port 80 (#0)
> GET / HTTP/1.1
> Host: 172.25.79.147
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 26 Jun 2020 20:28:09 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Set-Cookie: PHPSESSID=3ffe4a485ef65a590f696; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Location: http://172.21.42.117/
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host 172.25.79.147 left intact

 netstat -a | grep http | grep LISTEN
tcp6       0      0 [::]:http               [::]:*                  LISTEN

lsof -i:80
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
apache2 1034     root    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1037 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1038 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1039 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1040 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1041 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)
apache2 1045 www-data    4u  IPv6   2991      0t0  TCP *:http (LISTEN)

**Comment by sr229** [comment]
Localhost redirection is avaialble in WSL2, try using `localhost` to see if it works.

**Comment by exetak** [comment]
nope, is not working at all

**Comment by sr229** [comment]
What precisely isn't working, is it the network ingress or the network egress? Egress is fine, but Ingress should be no problem because with localhost forwarding, you don't need to worry about the IP address.

**Comment by exetak** [comment]
My bad, I want to access from the same machine in edge on windows, not in the same Ubuntu desktop

**Comment by exetak** [comment]
My bad, yes on the Ubuntu system can reach it without a doubt, what I'm trying is from windows
