### ISSUE TITLE
Only one distro/OS can access CUDA at a time

### ISSUE THREAD

**Issue by Kyle2142** [microsoft/WSL#5498]
# Environment
```none
Windows build number: 10.0.20152.0
Your Distribution version: Debian 9.12 and Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: 2
```
# Steps to reproduce

1. Install two WSL2 distros
2. Follow setup for Nvidia CUDA usage
3. Open a shell for each
4. Try use Nvidia CUDA in both

Alternatively, try use CUDA on windows after starting a distro

#  Expected behavior

Expected CUDA to work in both, or documentation about this limitation

# Actual behavior
CUDA fails on anything but the first one to try use it

# Comments
I first encountered this due to having Debian but then Nvidia requires Ubuntu for CUDA in WSL.
Not sure how this person knew, but [this comment](https://github.com/microsoft/WSL/issues/829#issuecomment-647676567) says only the first distro will have access.
Today I found this also applies to windows, as my Killing Floor 2 game which uses CUDA for Nvidia Flex crashed as soon as it tried to use CUDA (debian was running in the background). `wsl --shutdown` made me able to continue playing without further hassle.
Snippet from KF2 logs, showing this.
```none
[0522.19] DevFlex: Flex: CUDA error: 77. at ../../../flex.cu:5375
[0530.54] Log: === Critical error: ===
Fatal error!
Address = 0xd057d1d8 (filename not found) [in D:\Steam\steamapps\common\killingfloor2\Binaries\Win64\flexExtRelease_x64.dll]
Address = 0xd057e6e0 (filename not found) [in D:\Steam\steamapps\common\killingfloor2\Binaries\Win64\flexExtRelease_x64.dll]
Address = 0xd057bb13 (filename not found) [in D:\Steam\steamapps\common\killingfloor2\Binaries\Win64\flexExtRelease_x64.dll]
...
```
As I do not know whether this is a problem in WSL or on Nvidia's side, I've created posts on both.

**Comment by onomatopellan** [comment]
This happens because of #5506. Fix is coming.
