### ISSUE TITLE
file disappear

### ISSUE THREAD

**Issue by luyahan** [microsoft/WSL#5501]
When i clone riscv-gcc and close the terminal, open the wsl2 again, the riscv-gcc is disappear.  What Happend?

Microsoft Windows [版本 10.0.19041.329]
Linux DESKTOP-GI20VUB 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by therealkenc** [comment]
There is not enough here to form an actionable.
