### ISSUE TITLE
Resolving error in Ubuntu 18.04 using WSL2

### ISSUE THREAD

**Issue by Daneduke7** [microsoft/WSL#5502]
I've come across an error that does not let me connect to my network, this occurred after running a debloat script for Windows 10. After running the command ip addr show, I get the following.

$ ip addr show
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether aa:64:32:cb:b0:cf brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0e:15:f8:72:8b:95 brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:15:5d:18:07:23 brd ff:ff:ff:ff:ff:ff
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

And after trying to update Ubuntu I receive this error

Sudo apt-get update 
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old old ones used instead.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

#  Expected behavior

# Actual behavior

**Comment by therealkenc** [comment]
> 4: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
link/ether 00:15:5d:18:07:23 brd ff:ff:ff:ff:ff:ff

No IP address assigned to the interface, landing zones #5336 #4731 et al absent novel data points.

**Comment by Daneduke7** [comment]
It appears you have made a mistake I've looked at the links you have
provided, but the issues are not the same.

**Comment by Yash-Garg** [comment]
I am facing this same issue, i have tried changing nameservers, disabling windows defender firewalls but it just doesn't work!

**Comment by therealkenc** [comment]
> running a debloat script

That is not a repro. But making reasonable assumptions about what "a debloat script" of unknown origin or operation might be inclined to do, evens it is variation #5437

**Comment by Kenney-G** [comment]
+1 this is really annoying.

**Comment by Daneduke7** [comment]
I have since reinstalled the windows 10  using a usb drive and the issue went away. My guess is some of the ssh apps where uninstalled by the de bloat script and that was causing connectivity issues with Ubuntu.

**Comment by Aman-rishu** [comment]
> I am facing this same issue, i have tried changing nameservers, disabling windows defender firewalls but it just doesn't work!

I too facing the same problem 
Please help!

**Comment by Aman-rishu** [comment]
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 4a:21:10:dd:60:4c brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 52:5d:5e:d0:45:0f brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:15:5d:0a:de:53 brd ff:ff:ff:ff:ff:ff
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
