### ISSUE TITLE
Incorrect return code from "rename()" syscall on a non-existing file

### ISSUE THREAD

**Issue by skywind3000** [microsoft/WSL#5505]
# Environment

```none
Windows Version: Microsoft Windows [Version 10.0.19041.329]
Distribution: ubuntu 20.04  (same issue in debian 10)
WSL: WSL 1
Version: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
Uname: Linux weilin0 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

# Steps to reproduce

- Create a new file named `test_rename.c` with the content:

```c
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

int main(void)
{
    printf("rename: %d\n", rename("not_exist_file", "not_exist_file"));
    printf("errno: %d\n", errno);
    return 0;
}
```

- Compile & run:

```c
gcc test_rename.c -o test_rename
./test_rename
```

output:

```
rename: 0
errno: 0
```

#  Expected behavior

In a real linux, for example:

```
Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)
```

The program should output:

```
rename: -1
errno: 2
```

Because `rename()` on a non-existing file should return -1 and set `errno` to `ENOENT`.

# Actual behavior

WSL's `rename()` always returns `0` if source file name equals to the dest file name no matter the file exists or not. This happens in the recently updates on windows 2004, the previous WSL in windows 1909 behaves correctly.

# Summary

`rename()` should always return -1 and set `ENOENT` to `errno` if the file doesn't exist. This incorrect return code will break applications which rely on the rename return code:

I am the maintainer of a command productivity tool [z.lua](https://github.com/skywind3000/z.lua), an issue related to WSL 1 has been reported recently: https://github.com/skywind3000/z.lua/issues/104

Lua is lack of system APIs to detect file existence, a portable way for this is using `rename`:

```lua
function exists(name)
    if type(name)~="string" then return false end
    return os.rename(name,name) and true or false
end
```

This is a widely used method to detect file existence in lua, it is also mentioned in [stackoverflow](https://stackoverflow.com/a/21637809). 

While the latest WSL1's `rename()` system call always returns zero and break this function, which breaks z.lua in WSL1.

**Comment by therealkenc** [comment]
Confirmed on WSL1. That has to be a regress.

![image](https://user-images.githubusercontent.com/7049700/86048468-6d534d00-ba05-11ea-9216-9d4a919caf0c.png)

**Comment by skywind3000** [comment]
FYI, WSL1 on Windows 1909 works as expected:

![图片](https://user-images.githubusercontent.com/3035071/86082131-989f7000-bac9-11ea-93cd-57135ffe2ab3.png)

and

![图片](https://user-images.githubusercontent.com/3035071/86082210-c7b5e180-bac9-11ea-9db3-8942d97288a9.png)

**Comment by skywind3000** [comment]
Any plan for this ? When can we get this fixed ?

**Comment by skywind3000** [comment]
@therealkenc , has it been fixed ? or still pending ?? 
is it assigned to some engineer or still nobody is accountable for this ?

Any update after three months ??

**Comment by skywind3000** [comment]
Any update ??

**Comment by skywind3000** [comment]
Any update ?? After 7 month.

**Comment by namniav** [comment]
Seems fixed (since unknown version) ? Testing on 21H2:
```
rename -1
errno 2
```

```
ver:      Microsoft Windows [Version 10.0.19044.1415]
uname:    Linux Namniav-PC 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
neofetch: Ubuntu 20.04.3 LTS on Windows 10 x86_64
```

**Comment by skywind3000** [comment]
@namniav , very strange, I have exactly the same windows version of yours, but it still happen:

![图片](https://user-images.githubusercontent.com/3035071/147696406-484790f8-6b15-4cf0-b594-b72efdb9925d.png)

**Comment by namniav** [comment]
@skywind3000, oh, there must be something really weird...
![image](https://user-images.githubusercontent.com/68486394/147700053-cdaee85e-36fc-45d7-87b9-fd07e60b2c68.png)

**Comment by liam-keepmove** [comment]
I can't use z.lua1.8.16
The bug is still there.
![image](https://user-images.githubusercontent.com/57088624/204126662-8d732e29-8d15-4776-9c03-c3a7a8edaf43.png)

**Comment by skywind3000** [comment]
@liam-keepmove there is a work-around, install `lua-filesystem` package, z.lua will try it if exists.
