### ISSUE TITLE
win10 20152 home chinese editon can't use wsl2 any more.

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/WSL#5509]
# Environment

```none
Windows build number: [ windows chinese home editon 20152.1000]
Your Distribution version: [ubuntu 20.04]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

I Just update to lastet windows fast build insider. then I can't use wsl -d ubuntu20.04 start my dirstibution. 
When I install wsl_x64_update.msi. the dialog below showed. But I already turn on  wsl and virtual platform feature in Control Panel.

![image](https://user-images.githubusercontent.com/3423893/86084501-a6f08a80-bacf-11ea-8d23-2013be30b9b6.png)

#  Expected behavior
start my ubuntu.

# Actual behavior
can't start ubuntu20.04

**Comment by therealkenc** [comment]
Under Windows Update -> Advanced Options, turn on "Receive updates for other Microsoft products". Check for updates. Then from the commandline, do a `wsl.exe --update`.

**Comment by ferstar** [comment]
You need to uninstall the `wsl_update_x64` first and then re-install it, and your wsl2 will be back again.

**Comment by jiayuehua** [comment]
it work! Great thank to you, my dear friend.

**Comment by ferstar** [comment]
@jiayuehua So, it's time to close this issue.

**Comment by jiayuehua** [comment]
this is not a problem
