### ISSUE TITLE
Could not launch ubuntu distro. Now I cannot install any distro. error: 0x80070002

### ISSUE THREAD

**Issue by MWolfR** [microsoft/WSL#5510]
# Environment

```
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19018.0 Microsoft Windows NT 10.0.19018.0

Your Distribution version: 
Cannot run the specified commands because of the issue. But it was Ubuntu 18.04
```

# Steps to reproduce

Trying to start the distro led only to an error mesage:
>ubuntu
The system cannot find the file specified.

In trying to debug, I first tried to uninstall and reinstall the distro. So I uninstalled it by right clicking the tile and selecting "uninstall". Next I verified that it is uninstalled:

> wslconfig.exe /l
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store

However, when trying to install a distro I run into one of two errors. For the one just named "Ubuntu" in the Windows store I get an error popup:
![image](https://user-images.githubusercontent.com/47882990/86121186-de623580-bad5-11ea-8c39-f3edc0389c9a.png)
Transcription:
"Something unexpected happened! Reporting this problem will help us understand it better. You can wait a bit and try again or restart your device. That may help.
Code: 0x80073D05"

For the one named "Ubuntu 18.04" in the Windows store it apparently installs correctly, but when trying to launch fails with the following message:

"Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue..."

Logs, gathered as specified under https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md can be found in the following file:
[logs.zip](https://github.com/microsoft/WSL/files/4851458/logs.zip)

#  Expected behavior

Start the distro

# Actual behavior

Encountering "Error: 0x80070002", the distro fails to launch.

**Comment by therealkenc** [comment]
Thank-you for submitting logs. Ref #5107 #4959.

**Comment by pavel-a** [comment]
Please see #5107

**Comment by MWolfR** [comment]
Thank you for your replies.

If I understand this correctly, issue #5107 links the problem to VPN installations under windows and indeed I have two VPNs installed. So this can indeed be what's causing my issue. 

As recommended there, I disabled and re-enabled the WSL feature in windows and this seems to have fixed the problem. For now.
Still would be nice to know what I can do to avoid running into this in the future...
