### ISSUE TITLE
Error 0x80080005

### ISSUE THREAD

**Issue by pbzitech** [microsoft/WSL#5512]
Windows build number: Microsoft Windows [Version 10.0.17763.1282]
Your Distribution version: 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL1

# Steps to reproduce

On my computer, Microsoft store is not available. This means that I have to download Ubuntu packages manually which I've done through (https://docs.microsoft.com/en-us/windows/wsl/install-manual). The first time I installed it, I was able to open Ubuntu and create a user as expected. 

The second time I opened the program, it came up with the following message: 
" Installing, this may take a few minutes...
After waiting some minutes, it says: 
wslRegisterDistribution failed with error: 0x80080005
Error 0x80080005 server execution failed. 

Press any key to continue
"
After countless of reinstallations, when I install Ubuntu and load the application it says the same:  
"Installing, this may take a few minutes...
After waiting some minutes, it says: 
wslRegisterDistribution failed with error: 0x80080005
Error 0x80080005 server execution failed. 

Press any key to continue
"
And when pressing a key, it shuts down. I have tried to install it as an administrator which also makes no difference. 
What is really weird is that it worked the very first time but does not work anymore, even after reinstallation. 

I really hope that someone can help me as I have to use the program soon. 

BR
Jesper

**Comment by therealkenc** [comment]
> 17763

First step would be update Windows to 1909 (19H2) or if possible 2004 (20H1). If the problem persists, please collect [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) on a run of `wsl.exe -d Ubuntu-18.04`.

**Comment by sroopsai** [comment]
Hi, 
I got a similar error after removing Ubuntu 20.04 LTS and installing Ubuntu 18.04 LTS and starting the server.

**Comment by prepstarr** [comment]
Same issue
