### ISSUE TITLE
cant compile /usr/local/m68k-elf/bin/gcc: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Jockey4her** [microsoft/WSL#5513]
# Environment

```
OS Build 19041.329
Ubuntu 20.04
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
```

# Steps to reproduce

make

#  Expected behavior

bmt@ubuntu:~/Linux/work/test$ make
tbsound -l snd.spec sounds.bin -m gamesounds.h
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ globals.c -o globals.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ main.c -o main.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ game.c -o game.o
game.c:126: warning: `void DoSelectGame()' defined but not used
game.c:179: warning: `void DoBatteriesInstalled()' defined but not used
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ sounds.c -o sounds.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ input.c -o input.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ nrrc.c -o nrrc.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ pwm.c -o pwm.o
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ timer.c -o timer.o
/usr/local/m68k-elf/bin/ld -lapp globals.o main.o game.o sounds.o input.o nrrc.o pwm.o timer.o -L/usr/local/lib/gcc-lib/m68k-elf/3.3.2/m68000 -L../../device/source/libapp -lgcc -Map app.map -T linkfile
mmcimage ../../device/source/os/os.s19 app.s19 sounds.bin >image.bin

# Actual behavior
make
/usr/local/m68k-elf/bin/gcc -I../../device/source/include -m68000 -Wunused -Wall -Wa,-m68000 -O2 -c -fno-builtin -fno-exceptions -fomit-frame-pointer -fmessage-length=0 -x c++ globals.c -o globals.o
/usr/local/m68k-elf/bin/gcc: 1: Syntax error: "(" unexpected
make: *** [Makefile:22: globals.o] Error 2
<!-- /usr/local/m68k-elf/bin/gcc: 1: Syntax error: "(" unexpected->

**Comment by Jockey4her** [comment]
I have been running a gcc compiler for an old tool chain, m68k-elf on an Ubuntu VM for years. With wsl2, I thought I would try to go native.  I installed binutils, make, and copied all the installation directories over from a working image.
When I run make, it throws a syntax error. Its a working project so it's not that. It's something else. I'm not into linux so I cant help but to say I will try to follow steps if you can go kinda slow.

**Comment by therealkenc** [comment]
`make` is not a repro. You could in the hypothetical entertain posting repro steps leading to your error, but the probability of arriving at a syscall diverge is here.... low.

**Comment by Jockey4her** [comment]
I dont follow.  sycall diverge?

**Comment by therealkenc** [comment]
> sycall diverge?

A problem with WSL1's implementation of the Linux kernel. As opposed to a problem in userspace.

**Comment by therealkenc** [comment]
I might be able to guess without a repro. Post the result of:

```
$ file /usr/local/m68k-elf/bin/gcc
```

**Comment by Jockey4her** [comment]
file /usr/local/m68k-elf/bin/gcc
/usr/local/m68k-elf/bin/gcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.2.5, not stripped

I installed the toolchain with guidance from a guy who knows it real well.  I installed binutils, then make, then copied the tree of files into place that he had prepared off his own machine.  I have it in a .tgz file, but it's like 9mb. not sure if a link to that would be useful.  Then try to make a known good project.

**Comment by therealkenc** [comment]
> /usr/local/m68k-elf/bin/gcc: ELF 32-bit LSB executable

That was the guess. This is actually a diverge of sorts; 32-bit binaries are not supported on WSL1. Happily you are on 19041 aka 2004 aka 20H1: you want [WSL2](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/). 

/dupe #2468 dating back to #228.

**Comment by Jockey4her** [comment]
ah.. i had no idea I was on 1.. Strange, I thought it just came with 2004.. they should mark it or something.

**Comment by therealkenc** [comment]
> they should mark it or something

`wsl.exe -l -v`
