### ISSUE TITLE
When browsing a WSL folder in Explorer, there's no way to name a file/folder with some characters

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#5515]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.329]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
- navigate to a WSL folder in Explorer
- long-click on a file/folder to rename it
- type one of the Windows forbidden characters that are valid on Linux, like `"`

#  Expected behavior
No error message should be displayed and the `"` character should appear in the textfield.

# Actual behavior
An error is displayed:

![image](https://user-images.githubusercontent.com/199648/86215691-30aa6180-bb7d-11ea-9539-36e152de62d2.png)

**Comment by warpdesign** [comment]
@therealkenc Is it really a duplicate? This one is about rename checks that are performed by Explorer, #5516 is about the display of special characters in Explorer.

**Comment by ExE-Boss** [comment]
You can manually input code points in the `U+F000` – `U+F0FF` range by using <kbd>⁠alt⁠</kbd>⁠<kbd>⁠+⁠</kbd>, e.g.: for `"` (`U+0022`), you’d type: <kbd>⁠alt⁠</kbd>⁠<kbd>⁠+⁠</kbd>⁠<kbd>⁠F⁠</kbd>⁠<kbd>⁠0⁠</kbd>⁠<kbd>⁠2⁠</kbd>⁠<kbd>⁠2⁠</kbd>, which inserts the Private Use `U+F022` code point.
