### ISSUE TITLE
When browsing a WSL directory, some characters are not properly displayed

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#5516]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.329]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
- in WSL use a `"` in a file name, for example `tutu"`
- browse the folder containing this file in Explorer

#  Expected behavior
Explorer should show the correct `tutu"` filename

# Actual behavior
The `"` is replaced with `` in Explorer while calling `ls` in a terminal shows the correct filename:

![image](https://user-images.githubusercontent.com/199648/86216562-85021100-bb7e-11ea-8d14-800151740fb2.png)

**Comment by therealkenc** [comment]
Quotes `"` is a [reserved character](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN) in Windows filesystems. Ref #1514. This is pretty much by-design.
