### ISSUE TITLE
[WSL2] Issue with update to Windows 20152?

### ISSUE THREAD

**Issue by jkw** [microsoft/WSL#5517]
# Environment

```none
Microsoft Windows [Version 10.0.20152.1000]
```

# Steps to reproduce

1. Install WSL1 on Windows 10 Pro x64 pre 20152 update.
2. Upgrade to WSL2 and set WSL2 as default
3. Update kernel as requested
4. Run WSL Distribution of choice without issues.
5. Update to Windows Insider Preview 20152.
6. Get kernel issue, follow instructions at aka.ms/wsl2kernel
7. Get the following error message:
![image](https://user-images.githubusercontent.com/388872/86219698-d6ac9a80-bb82-11ea-97a6-9153fa255fb0.png)

#  Expected behavior
WSL2 should work as kernel already have been upgraded.

# Actual behavior
WSL2 says to update kernel, but installation says WSL isn't enabled (See screenshot above).

**Comment by therealkenc** [comment]
variation #5509

`wsl.exe --update` is the new "Windows Subsystem for Linux Update Setup" installer msi. Announcement [here](https://devblogs.microsoft.com/commandline/gpu-compute-wsl-install-and-wsl-update-arrive-in-the-windows-insiders-fast-ring-for-the-windows-subsystem-for-linux/).

**Comment by jkw** [comment]
> variation #5509
> 
> `wsl.exe --update` is the new "Windows Subsystem for Linux Update Setup" installer msi. Announcement [here](https://devblogs.microsoft.com/commandline/gpu-compute-wsl-install-and-wsl-update-arrive-in-the-windows-insiders-fast-ring-for-the-windows-subsystem-for-linux/).

Tried searching for changes both here and on the web, I have to up my search-skills for sure. :|

Fix as described in https://github.com/microsoft/WSL/issues/5509#issuecomment-651650720 helped for me.

Thanks for your time. Closing issue.
