### ISSUE TITLE
Wayland server in Windows for graphical applications from WSL

### ISSUE THREAD

**Issue by felipealmeida** [microsoft/WSL#5518]
Right now it is necessary to use a X11 server to run Graphical applications. However, a X server is too big and requires a window manager to run (intrinsic to server or not). Wayland is already implemented by most graphical applications through toolkit libraries (GTK, Qt, EFL, etc) and can be enabled by environment variables.

The biggest challange, as I can see, is being able to use a socket file from a Win32 application to work as a communication of shared memory from WSL applications. This makes Wayland protocol impossible to implement.

I have a rudimentary Wayland server based on Vulkan API which I wanted to port to Windows, however, this is not possible AFAIU yet because of the above problem. My wayland server could be completely implemented on Win32 API (with Vulkan API) without any requirement of WSL, making it possible to create normal windows for WSL applications. However, the impossibility of passing memory shared segments makes this impossible to refresh buffers.

**Comment by benhillis** [comment]
We are currently working on a wayland-based GUI apps feature.  Stay tuned later in the year for more information.

**Comment by felipealmeida** [comment]
> 
> 
> We are currently working on a wayland-based GUI apps feature. Stay tuned later in the year for more information.

This is cool and all. But I wanted to port my own wayland compositor. AFAICS this is not possible for the reasons I mentioned in the issue. Am I missing something?

Regards,
