### ISSUE TITLE
Cannot use administrator mode after restarting the pc following the instructions.

### ISSUE THREAD

**Issue by Nagimagi** [microsoft/WSL#5520]
Having opened powershell with administrator mode, I tried typing "Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform",then the pc restarted,
as I tried open powershell with adminitstrator mode again. I noticed the default path was not C:\Windows\System32, but C:\Users\myname. 
I am trying to update WSL to WSL 2, now without the adminstrator mode, I could not follow the steps on the instruction.
How did that happened? And how to solve it?

P.S. I noticed this kind of situation of which I could not use bash to enter to root with the opening with administrator option for months. And I found a solution just to use the root as a user with typing "wsl -u root ". But right now it seems it is only plausible to use administrator mode to update WSL. I am very confused.

**Comment by therealkenc** [comment]
>  I could not follow the steps on the instruction

From a non-administrator cmd prompt, `wsl --set-version 2`. Updating from WSL1 to WSL2 does not depend on your path.

>  I could not use bash to enter to root

The `bash.exe` program is depreciated. Use `wsl.exe -d <Distro> -u root`.

![image](https://user-images.githubusercontent.com/7049700/86335024-cd631280-bc02-11ea-9660-123f9087cac8.png)

**Comment by Nagimagi** [comment]
> > I could not follow the steps on the instruction
> 
> From a non-administrator cmd prompt, `wsl --set-version 2`. Updating from WSL1 to WSL2 does not depend on your path.
> 
>But I tried 'wsl --set-version2'and'wsl --list --verbose'，it only seems that wsl on my powershell could only recognised few options like '-d -e -u'
![image](https://user-images.githubusercontent.com/33744937/86342110-bc111900-bc89-11ea-908b-e183766e86a9.png)

**Comment by therealkenc** [comment]
What is the output of:

```
PS C:\> cmd.exe /c ver
```

Also is that an administrative shell? I can't translate, but the format suggests that it is. Do not open PS as administer.

**Comment by Nagimagi** [comment]
> What is the output of:
> 
> ```
> PS C:\> cmd.exe /c ver
> ```

> Also is that an administrative shell? I can't translate, but the format suggests that it is. Do not open PS as administer.

Yes. Tried open with cmd, but still the options are not available
The version is as below.

![image](https://user-images.githubusercontent.com/33744937/86346009-e2858300-bc8e-11ea-9e49-bb18d4a71cbc.png)

**Comment by therealkenc** [comment]
WSL2 became available in Windows 10 2004 aka 20H1 aka build 19042. You are on build 17763 from circa Spring 2018.

**Comment by Nagimagi** [comment]
> WSL2 became available in Windows 10 2004 aka 20H1 aka build 19042. You are on build 17763 from circa Spring 2018.

Seems it is not really comprehensive on the Chinese documentation. Quite confusing and somewhat misleading. I shouldn't have followed it.
