### ISSUE TITLE
There is no distribution with the supplied name. "Ubuntu"

### ISSUE THREAD

**Issue by kobelobster** [microsoft/WSL#5521]
I saw this issue https://github.com/MicrosoftDocs/WSL/issues/487 but it didn't help

Hi,

so I installed WSL and WSL 2 and Ubuntu as a distro but to use Docker, I need Ubuntu to be wsl 2 which it currently isn't as you can see here

```
PS C:\Users\kobelobster> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         1
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

So now, I want to use `wsl --set-version (Ubuntu) 2` to set it to two, however, what happens is the following

```
PS C:\Users\Theo> wsl --set-version (Ubuntu) 2
❯ exit // Somehow this logs me into wsl, so I have to exit
There is no distribution with the supplied name
```

But, when I also use 

```
PS C:\Users\kobelobster> wsl --list --all
Windows-Subsystem for Linux distributions:
Ubuntu (Standard)
docker-desktop-data
docker-desktop
```

Why can't I set wsl2 for Ubuntu?

I also tried

* `wsl --set-version (Ubuntu) 2`
* `wsl --set-version (Ubuntu (Standard)) 2`
* `wsl --set-version (Ubuntu-20.04) 2`
* `wsl --set-version (Ubuntu-18.04) 2`

I also 

* Enabled Hyper-V
* Ran these commands in an elevated shell

Nothing worked. I set my default to wsl2 from now on, but I don't want to reinstall the Linux distro , because I have already lots of stuff configured that I don't want to completely reconfigure now.

**Comment by therealkenc** [comment]
```
PS C:> wsl --set-version Ubuntu 2
```

**Comment by kobelobster** [comment]
Oh, so it's without the brackets? I don't know where I got them from, somewhere it said (distribution name) and I didnt' see the brackets as placeholders as well.

This worked. Thanks

**Comment by gaurav93handa** [comment]
> ```
> PS C:> wsl --set-version Ubuntu 2
> ```

It works!!!
