### ISSUE TITLE
Is the lxss folder safe to remove?

### ISSUE THREAD

**Issue by albertotb** [microsoft/WSL#5522]
I have installed WSL2 with Ubuntu 20.04 distro. Checking my HD usage I found that I have a 14 Gb file in 

`C:\Users\alberto\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx`

however, I also have a 14Gb folder

`C:\Users\alberto\AppData\Local\lxss`

Are both neccessary or are they spurious files from an old WSL installation? I'm running low on space and I'm getting error code 0x80073d0b when trying to move Ubuntu to another HD.

**Comment by therealkenc** [comment]
Rename the folder to `lxss-bak`. If your workflow isn't disturbed after the rename, then yes probably safe enough (for some value of enough). Backing up before deleting it would be even safer.

**Comment by albertotb** [comment]
Thanks, I can definately try that! Just of curiosity it would be great to know if this has somthing to do with migrating from WSL1 to WSL2

**Comment by benhillis** [comment]
`C:\Users\alberto\AppData\Local\lxss` the path old “Legacy” distro. If you are no longer using it you can delete it.

**Comment by albertotb** [comment]
Perfect, thank you! I think this can be closed now
