### ISSUE TITLE
/etc/resolv.conf always automatically made, and ignores /etc/wsl.conf

### ISSUE THREAD

**Issue by michael-angelozzi** [microsoft/WSL#5527]
In `/etc/resolv.conf` it says:
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:     
# [network]
# generateResolvConf = false
```

# Environment

```none
Microsoft Windows [Version 10.0.19041.329]
Ubuntu lsb_release -r
WSL 2
```

# Steps to reproduce

1. `/etc/wsl.conf` didnt exist for me, so create it and add the following text to it:
  ```
[network] 
generateResolvConf = false 
  ```
2. Save and close.
3. Close Terminal, and re-open it.
4. Open `/etc/wsl.conf` and edit the auto generated nameserver which fails to resolve, change it to something like `8.8.8.8`.
5. Save and close
6. Wait a short while, and soon `/etc/wsl.conf` has reverted soon back to something like `172.30.16.1` which cant resolve github.com or PPA's etc.

#  Expected behavior

Not to change the nameserver as per the instructions.

# Actual behavior

Windows is changing the nameserver to something that doesnt work. The fix to the fix is not working.

**Comment by benhillis** [comment]
I suspect your /etc/reslv.conf is a symlink into /run, which is tmpfs and re-created at boot.

**Comment by therealkenc** [comment]
Ref #4285 (the de-facto hangout).

**Comment by michael-angelozzi** [comment]
> I suspect your /etc/reslv.conf is a symlink into /run, which is tmpfs and re-created at boot.

Thanks for the reply, you are correct @benhillis 
`lrwxrwxrwx 1 root root 29 Jun 10 13:28 /etc/resolv.conf -> ../run/resolvconf/resolv.conf`

I deleted the symlink, made a new `/etc/resolv.conf` file:
`-rw-r--r-- 1 root root 197 Jul  3 14:06 /etc/resolv.conf`
Restarted, and it was also automatically changed back to a none working nameserver.

**Comment by michael-angelozzi** [comment]
The Fix: reading this [post](https://github.com/microsoft/WSL/issues/4285#issuecomment-532962762), I see a simple `wsl --shutdown` was not enough, so I just restarted the whole pc to be sure it was restarted, and since then `resolv.conf` is no longer overwritten.
