### ISSUE TITLE
cannot update to latest kernel (from 4.19.104 to 4.19.121)

### ISSUE THREAD

**Issue by thisguychris** [microsoft/WSL#5529]
# Environment

```none
Microsoft Windows [Version 10.0.20161.1000]
Ubuntu 20.04
the issue is on WSL2 / currently on dev channel
```

# Steps to reproduce

- wsl.exe --update

#  Expected behavior

- should update to 4.19.121

# Actual behavior

- shows 
Checking for updates...
No updates are available.
Kernel version: 4.19.104

**Comment by onomatopellan** [comment]
Delete that `kernel` file you have in c:\windows\system32\lxss\tools. In build 20150+ you only need to check for Windows Updates to get the latest kernel. Make sure you have "Receive updates for other Microsoft products when you update Windows" enabled in the advanced options.

**Comment by thisguychris** [comment]
@onomatopellan 
I've deleted it, now I can't start my Ubuntu 20.04 installation. Checking Windows Update doesn't show anything.
![image](https://user-images.githubusercontent.com/532797/86486951-64f56c00-bd8f-11ea-8f5f-4f75af29870f.png)

**Comment by onomatopellan** [comment]
Open an elevated cmd and run `wsl.exe --update`

**Comment by thisguychris** [comment]
@onomatopellan 
yes, I have it enabled here:
![image](https://user-images.githubusercontent.com/532797/86489015-8ce7ce00-bd95-11ea-86a4-b77121d7de70.png)

I was able to debug by following your comment on this issue:
https://github.com/microsoft/WSL/issues/5014#issuecomment-609088197

1. I had to uninstall the Linux kernel by running this [program](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) as you have suggested.

2. I then installed the msi again from https://aka.ms/wsl2kernel

After that I finally was able to update via Windows Update:
![image](https://user-images.githubusercontent.com/532797/86489136-f071fb80-bd95-11ea-9b32-7a0f82e5b67e.png)

Hopefully, someone finds this post useful in the future, thanks @onomatopellan!

**Comment by datavistics** [comment]
I have receive updates enabled and Im fully updated.
I uninstalled WSL and resinstalled from the MS again.

Still at 4.19.104 -_- any advice?

**Comment by mhzed** [comment]
Same here, wsl just won't update.

**Comment by mhzed** [comment]
Found the fix.  Make sure you join the insider program first, then you will get the update.

**Comment by datavistics** [comment]
@mhzed can you send a link. Im not familiar with it.

**Comment by Biswa96** [comment]
No need to join Insider Program if you don't want it. Windows Insider builds may crash sometimes as they are not stable. One could download a Windows Update file from Microsoft Update Catalog. Follow these steps:

1. Go to this website https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
2. Click on the Linux kernel version you want. 
3. There will be a popup window. Select the package as per your CPU architecture (mostly x64 one).
4. It will be downloaded as CAB file. Open it. Extract the MSI file. Install the MSI file.

Voilà 🎊

**Comment by mhzed** [comment]
After 10 days, I can attest that windows insider program does crash very often.  Follow Biswa96's solution instead.

**Comment by cpoptic** [comment]
Tried uninstalling the `Windows Subsystem for Linux Update` but an error is thrown:

> The feature you are trying to use is on a network resource that is unavailable.
>
>Click OK to try again, or enter an alternate path to a folder containing the installation package `wsl_update_x64.msi` in the box below.

There is a dropdown text field to specify `Use source:`,

Yet regardless where I specify the source, I get an error box:

> The file `C:\downloads\wsl_update_x64.msi` is not a valid installation package for the product Windows Subsystem for Linux Update.  Try to find the installation package `wsl_update_x64.msi` in a folder from which you can install Windows Subsystem for LInux Update.

Pretty frustrating.  I've tried manually installing WSL2, reinstalling it, which it does reinstall successfully.
But each time I go to `System Updates`, the WSL update downloads (up to 100% download), but then throws the same old error 

`There were some problems installing updates, but we'll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0x80070643)`

I have sunk *hours* and *hours* trying to figure this out, but have been unsuccessful.

**Comment by onomatopellan** [comment]
@cpoptic Did you try [this](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed)?

**Comment by lwu-ox** [comment]
I encounter the same problem cannot uninstall 4.19.104, as described in #6613. It seems we need the original 4.19.104 install program msi (during the uninstall processes), but it can't be download from microsoft website anymore...
