### ISSUE TITLE
glxgears exits with GLXBadContext but sudo glxgears works fine.

### ISSUE THREAD

**Issue by chrisgmorton** [microsoft/WSL#5535]
# Environment

```none
Version 10.0.19041.329
Ubuntu 18.04 LTS
WSL2
```

# Steps to reproduce

Ubuntu side, packages installed that may be relevant here are:
```
mesa-common-dev
libgl1-mesa-dev
libglu1-mesa-dev
libxt-dev
mesa-utils
```

On the Windows side, I'm running a Cygwin Xserver using:

```C:\cygwin64\bin\run.exe -p /usr/bin Xwin -listen tcp -nowgl -ac -multiwindow -clipboard -silent-dup-error```

From Ubuntu terminal shell prompt:

```glxgears```

produces

```
X Error of failed request: GLXBadContext
  Major opcode of failed request: 149 (GLX)
  Minor opcode of failed request: 6 (X_GLXIsDirect)
  Serial number of failed request: 25
  Current serial number in output stream: 24
```

```sudo glxgears```

produces turning gears X window as expected after entering password. Note also that

```xeyes```

produces cursor following eyes X window as expected.

**Comment by chrisgmorton** [comment]
I did a clean install of Ubuntu 16.04, installed mesa-utils. Same issue. Can only run glxgears with sudo. Installed X11-apps to run xeyes. This runs fine without root privileges. This looks like a simple permissions issue on a driver or /etc config file. Would be good if worked out of the box as it is impacting my ability to use VTK.

**Comment by chrisgmorton** [comment]
This problem does not exist on Ubuntu 20.04. I also notice that I had to explicitly set DISPLAY from /etc/resolve.conf nameserver IP address in this case. So my guess is that some of the preconfig done on the windows side when a linux session is started is causing the need for root access to successfully run glxgears in 18.04 and 16.04. This looks like a WSL2 bug to me.

**Comment by chrisgmorton** [comment]
TBH this is not inspiring confidence. My Intel Math Kernel Library linkage has broken. I'll submit something separately on this. I'm running Python 3.8 but using Multiprocessing, Numpy, SciPy and Intel's MKL 2020. Worked beautifully in WSL 1 on Ubuntu 16.04. I am building a separate lib for Python for matrix multiplication that I previously imported with TBB linkage, Now hangs. There's probably a thread issue, kernel related. Not sure this is going to be viable at this point but will try to help, if possible. May just have to revert back to EDA practices of standardizing on Linux. Like the whole concept though.

**Comment by chrisgmorton** [comment]
Behavior is different the first time you open up an Ubuntu 18.04 after a reboot. The first time you run glxgears is fails with can't open display (even through DISPLAY is set correctly). Run again, and you get the gears window with turning gears, all fine. Open up a second Ubuntu 18.04 session and run glxgears and you ge the GLXBadContex error message. Not sure why this is labeled as question. Anyhow, I'm going to see if I can install the insider preview latest release as I want to check out the GPU capability. See if this release also has GLX issues.

**Comment by chrisgmorton** [comment]
Okay, this is an obvious issue and I see some others have run into this. /etc/profile.d/wsl-integration.sh links to /usr/share/wslu/wsl-integration.sh and sets LIBGL_ALWAYS_INDIRECT=1 which breaks everyone's mesa glx rendering by CPU on the linux side. I assume this will actually start to work in future with the development of GPU acceleration capability. For those who don't know, setting this variable to 0 will fix the GLXBadContext issue (provided the Windows side X server is started with the -nowgl option). The symbolic link is not present on the Ubuntu-20.04 installation and this is why glxgears works out-of-the-box, assuming you are correctly setting DISPLAY. Ubuntu's doc is also wrong, indicating that LIBGL_ALWAYS_INDIRECT=1 is required.

**Comment by therealkenc** [comment]
All of the components mentioned here, your X server, the X client libraries, glxgears, mesa, your entire Ubuntu install part of WSL. You'll get more takers in forums related to those products. The `GLXBadContext` error message is from userspace. At base: if your client X libraries says it is a bad context, that's because it got a bad context. WSL doesn't control the traffic between your X clients (GL or otherwise) and your X server.

**Comment by dgellow** [comment]
@chrisgmorton Thanks for all the details, that was really useful.
