### ISSUE TITLE
WSL2/HyperV does not support support installing on disks larger than 2TB

### ISSUE THREAD

**Issue by Kwizatz** [microsoft/WSL#5536]
# Environment

Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

# Steps to reproduce

C:\Windows\System32>wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The sector size of the physical disk on which the virtual disk resides is not supported.

C:\Windows\System32>wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation timed out because a response was not received from the virtual machine or container.

#  Expected behavior

WSL 2 should upgrade properly despite having a large hard drive.

# Actual behavior

Hyper-v related error pops up:
The sector size of the physical disk on which the virtual disk resides is not supported.

C:\Windows\System32>Fsutil fsinfo ntfsinfo c:
NTFS Volume Serial Number :        0x962cadfa2cadd611
NTFS Version      :                3.1
LFS Version       :                2.0
Total Sectors     :                3,905,070,138  (3.6 TB)
Total Clusters    :                  976,267,534  (3.6 TB)
Free Clusters     :                  880,894,610  (3.3 TB)
Total Reserved Clusters :              1,621,859  (6.2 GB)
Reserved For Storage Reserve :         1,610,081  (6.1 GB)
Bytes Per Sector  :                1024
Bytes Per Physical Sector :        4096
Bytes Per Cluster :                4096
Bytes Per FileRecord Segment    :  1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            1.25 GB
Mft Start Lcn  :                   0x00000000000c0000
Mft2 Start Lcn :                   0x0000000000000002
Mft Zone Start :                   0x0000000001604080
Mft Zone End   :                   0x000000000160fe00
MFT Zone Size  :                   189.50 MB
Max Device Trim Extent Count :     0
Max Device Trim Byte Count :       0
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      7906103A-A402-11EA-AAA0-8110D4D00ADB

**Comment by onomatopellan** [comment]
>Bytes Per Sector : 1024
Bytes Per Physical Sector : 4096

I don't think the disk size is the problem but the sector size is.  See https://support.microsoft.com/es-es/help/2515143/using-hyper-v-with-large-sector-drives-in-windows-server-2008-and-wind

If you can format a partition in that disk with 512bytes per sector you shouldn't have problem installing vhdx files there.

**Comment by 0xbadfca11** [comment]
> Bytes Per Sector : 1024

Not because of the disk size.
The sector size is wrong.
All Microsoft VHD implementation only supports 512 bytes or 4096 bytes.
The two are industry standards.
It is known that some onboard RAID implementations (eg AMD RAIDXpert) do this weird thing.

In any case, your environment is in a state where not only WSL2 but also everything else is not supported.
It is recommended that you stop using a weird RAID.
> https://support.microsoft.com/en-gb/help/2510009

Common Names | Reported Logical Sector Size | Reported Physical Sector Size | Windows Version with Support
-- | -- | -- | --
Other | Not 4 KB or 512 bytes | Not 4 KB or 512 bytes | Not Supported

**Comment by Kwizatz** [comment]
I was afraid that would be the case 😕. I could not find anyone else with this specific issue on the web, at least it will be documented now.

Thanks!
