### ISSUE TITLE
Can not start wsl2 Ubuntu18.04

### ISSUE THREAD

**Issue by nilaoda** [microsoft/WSL#5538]
# Environment

```none
Windows build number: 10.0.20161.0
Your Distribution version: 
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

In cmd, `bash` or `wsl` can not open Ubuntu18.04.

```
C:\Users\me>wsl
WSL 2
C:\Users\me>bash
WSL 2
C:\Users\me>
```

It was working normally a month ago, I don’t know what happened.

**Comment by benhillis** [comment]
I suspect you messed up your .bashrc file. You should be able to recover by using wsl.exe /bin/sh.

**Comment by 0xbadfca11** [comment]
May be #5388(#5438).
[The Linux kernel is no longer shipped with Windows.](https://blogs.windows.com/windowsexperience/2020/06/10/announcing-windows-10-insider-preview-build-19645/)
Even if it was installed before, it will be deleted.
You have to install kernel separate.

**Comment by benhillis** [comment]
@0xbadfca11 - I think you are right. We have an issue with printing that error text on some locales (fix inbound).

**Comment by nilaoda** [comment]
> May be #5388.
> [The Linux kernel is no longer shipped with Windows.](https://blogs.windows.com/windowsexperience/2020/06/10/announcing-windows-10-insider-preview-build-19645/)
> Even if it was installed before, it will be deleted.
> You have to install kernel separate.

How can I install the kernel? Download from Store? I already installed Ubuntu 18.04

![image](https://user-images.githubusercontent.com/20772925/86528735-7a78ac00-bedd-11ea-8cec-7073d98bdfb6.png)

**Comment by nilaoda** [comment]
> I suspect you messed up your .bashrc file. You should be able to recover by using wsl.exe /bin/sh.

Thank you, but it is not work.
```
C:\WINDOWS\system32>wsl.exe /bin/sh
WSL 2
C:\WINDOWS\system32>
```

**Comment by licanhua** [comment]
As @0xbadfca11 said, there is bug in display(#5388). You may change `Windows display language` to English, then you are able to see the details of the error message.
I expected the error is `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`, if yes, just follow the link and install the kernel manually.

**Comment by craigloewen-msft** [comment]
Please try the fix above from @licanhua and let us know if that resolves your issue!

**Comment by nilaoda** [comment]
i'll try tomorrow, thank you all!

**Comment by paulomanrique** [comment]
After last insider upgrade, we can't update the kernel.

![image](https://user-images.githubusercontent.com/4464977/86905411-66ed6100-c0e8-11ea-8dfc-56f18f628b58.png)

**Comment by JunlinHe** [comment]
I reinstall wsl and update the [kernel](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel), maybe it's not a good idea

**Comment by xiaomudk** [comment]
> I reinstall wsl and update the [kernel](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel), maybe it's not a good idea

I installed the upgrade package, wsl can run normally, thank you！

**Comment by nilaoda** [comment]
> I reinstall wsl and update the [kernel](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel), maybe it's not a good idea

Than you! I install the kernel then wsl2 works!
