### ISSUE TITLE
I cannot access wsl files from Windows

### ISSUE THREAD

**Issue by ScottEBean** [microsoft/WSL#5539]
I know this is a duplicate issue. I've tried many of the suggested fixes in https://github.com/microsoft/WSL/issues/4260 with no success.
# Environment

```none
Windows build number: *Win32NT  10.0.19041.0 Microsoft Windows NT 10.0.19041.0*
Your Distribution version: Release: Ubuntu *Release:  20.04*
Whether the issue is on WSL 2 and/or WSL 1:  WSL2 *Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020*
```

# Steps to reproduce
I've tried 3 ways to access wsl2 Ubuntu  files in windows.

*Add Network Location* with *\\wsl$\Ubuntu-20.04* as the address.

*\\wsl$\Ubuntu-20.04* in file explorer address bar

*explorer.exe .* in wsl.

#  Expected behavior
I'm expecting to be able to access wsl from windows. 
With *Add Network Location* I was expecting it to mount a network location to the *\\wsl$\Ubuntu-20.04* directory
Navigating to *\\wsl$\Ubuntu-20.04* should open that directory in file explorer.

With *explorer.exe .* in wsl I'm expecting a file explorer window to open to the current directory.

Add network location should mount a new folder in windows to that directory.

# Actual behavior

Using the file explorer address bar says there is a network error.
![File explorer address bar](https://user-images.githubusercontent.com/11564914/86504689-e1c91b80-bd78-11ea-8206-93c2af1aaec0.png)

Using *Add Network Location* gives the following error
![Add Network Location](https://user-images.githubusercontent.com/11564914/86504680-c65e1080-bd78-11ea-9e48-a889098370ab.png)

*explorer.exe .* just opens up explorer to my documents folder.
![explorer.exe .](https://user-images.githubusercontent.com/11564914/86504694-07eebb80-bd79-11ea-9fac-c78bad2c719b.png)

Please note this is while WSL is running
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2

**Comment by licanhua** [comment]
I would suggest you try this:
1. save your work, and `wsl --shutdown` in a console with admin
2. re-launch Ubuntu
3. `powershell.exe start .` in Linux instead of `explorer.exe`
4. or Win+R, then run `\\wsl$`

**Comment by ScottEBean** [comment]
I've tried these and did not have any success. Option 4 gave the the same error as the second screen shot above and option 3 gave me the following error: 

start : This command cannot be run due to the error: The network path was not found.
At line:1 char:1
+ start .
+ ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by licanhua** [comment]
I guess 9p has some problem. Can you try ` dmesg |grep 9p` in linux?
Here is my output:
```
[    0.363323] 9p: Installing v9fs 9p2000 file system support
[    0.363336] FS-Cache: Netfs '9p' registered for caching
[    0.398989] 9pnet: Installing 9P2000 support
```

**Comment by licanhua** [comment]
possible the same with #5307

**Comment by ScottEBean** [comment]
@licanhua https://github.com/microsoft/WSL/issues/5307 was indeed the problem. I wasn't very deep into my own setup so ended up uninstalling WSL completely and reinstalling. Problem fixed. Thanks for your help.
