### ISSUE TITLE
Everything Halfway Works

### ISSUE THREAD

**Issue by cardfaux** [microsoft/WSL#5541]
# Environment
WSL2 Ubuntu20.04
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
Try to Run Webpack or almost anything else that has to recompile code to reload

#  Expected behavior
I expect webpack to reload by itself with webpack dev server

# Actual behavior
It dosen't I have to rerun the npm script

I can get it to work if I run everything in Docker but outside of Docker I can't.  I would be ok just running everything in Docker but I also make shopify themes and apps and I can't run that inside of docker Because I have to run the code and push it to their servers during development.

**Comment by therealkenc** [comment]
No CLI repro was provided but the implication is /dupe #4739
