### ISSUE TITLE
WSL2-Uknown Virtual Disk in device manager

### ISSUE THREAD

**Issue by 2ral** [microsoft/WSL#5543]
Hi everyone Recently I have discovered an unknown Microsoft Virtual Disk in my device manager. My question is: does it correspond to WSL2 that I am running on my machine or I doubt it may be related to Windows Sandbox I used to have enabled some time ago but later disabled or any other service? Does WSL2  service create a separate virtual disk in the device manager?
It consumes 8gb of my SSD disk space and I want to get rid of it in case WSL2 does not need this disk to run on my machine. Thanks for replies

**Comment by DHowett** [comment]
Is it called “PortableBaseLayer”? If so, that is Windows Sandbox.

**Comment by 2ral** [comment]
Nope, It is called Microsoft Virtual Disk. I had setuped Windows Sandbox a year ago and switched it off couple months before. Logically if it was related to Sandbox it should have been disappeared after sandbox deactivation in windows features. Or maybe microsoft had screwed up and disk remain persistent? The thing I want to clarify for myself is requirment of WSL2 to create a Virtual Disk Device. As far as I know WSL2 migrates it's filesystem to .vhdx file. Or maybe this Microsoft Virtual Disk is a required component for Hyper-V?

**Comment by onomatopellan** [comment]
I'm running an Hyper-V VM and also WSL2 distro right now and no unknown vdisk appears in Device Manager.

**Comment by therealkenc** [comment]
> Does WSL2 service create a separate virtual disk in the device manager?

No, none here either.
