### ISSUE TITLE
Piping a Windows command to less does not work

### ISSUE THREAD

**Issue by bobf32** [microsoft/WSL#5545]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Release:        10
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

1. Open a command prompt or powershell terminal session

2. Type dir | wsl less

#  Expected behavior

In a fairly full folder, executing the statement above should display the first page of the output produced by the dir command, then pause while waiting for any input required by the less pager. I would expect then to be able to invoke the usual less commands e.g. SPACE to navigate to the next page of results, b to go back a page, h to invoke the less help, etc.

# Actual behavior

As expected, the first page of dir output is produced. A colon is displayed at the bottom of the screen, presumably to indicate there is more output available. However, no amount of pressing SPACE, b, h or any other key I normally use whilst paging with less, works. The only thing I seem to be able to do it hit Ctrl-C to quit the command.

**Comment by sirredbeard** [comment]
I can reproduce. 

![image](https://user-images.githubusercontent.com/33820650/86613620-deec4780-bf7f-11ea-9759-31b9c92c9726.png)
