### ISSUE TITLE
Intermittent input/output errors when accessing Windows filesystem resources from Linux

### ISSUE THREAD

**Issue by phillip-elm** [microsoft/WSL#5552]
# Overview

I am opening this issue as I have been experiencing intermittent `input/output error`s when accessing files on Windows from Linux. I originally opened an issue in the Docker for Windows repo (https://github.com/docker/for-win/issues/7552), but they indicated that this is likely to be a WSL-specific feature.

This seems related to https://github.com/microsoft/WSL/issues/4377, except that I cannot fix the issue by running `wsl --shutdown` and restarting it.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Docker Desktop Latest Stable and Edge (2.3.0 and 2.3.2.1)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Run a web server (WordPress, for example) or similar and access the files from it.
2. Reload the page at any frequency, cache disabled. It can happen on an idle server or a busy one.
3. Check the logs, also watch for missing resources (stylesheets and/or images not loading, etc)

#  Expected behavior

The page loads 100% with no IO errors.

# Actual behavior

WordPress PHP FPM:
```
NOTICE: PHP message: PHP Warning:  require(/var/www/html/wp-content/themes/twentytwenty/template-parts/footer-menus-widgets.php): failed to open stream: Input/output error in /var/www/html/wp-includes/template.php on line 725
```

In a separate in-house Golang application:
```
[ERR] Failed to stat /redacted/path/to/file: input/output error
```

**Comment by therealkenc** [comment]
Thanks for the submission. The remaining input/output errors which still exist [post 18895](https://github.com/microsoft/WSL/issues/4377#issuecomment-538038437) needed a landing zone. Ref #5449 which might or might not be related.

Need CLI repro steps, the less moving parts the better. A threaded [`strace(1)`](https://man7.org/linux/man-pages/man1/strace.1.html) log that catches the `EIO` even better.

**Comment by jwtowner** [comment]
Hey, I may have the same problem when building projects with MSVS 2019 using the Clang for Windows Subsystem for Linux platform toolset, with the project's source files being stored on the Windows filesystem. The problem manifests the moment I increase the number of parallel build processes to a suitably high number, such as the say the same number of hardware threads available on the build machine's CPU. The build will fail when accessing random files under high load and I/O contention, with an unexpected exception being thrown from MSBuild's liblinux.Local.dll when performing an IO operation from within WSL that is accessing files on the Windows filesystem (via /mnt/c/...).

To demonstrate and reproduce the problem consistently, I've made available a fork of the [Doom 3 for WebAssembly port](https://github.com/jwtowner/d3wasm) with working MSVS 2019 solution and project files. On my build machine consisting of a Ryzen 3900X (12c/24t), 32GB RAM, Samsung 960 Pro 2TB NVMe PCIe M.2 SSD, the problem will always occur around 8-10 seconds after starting a rebuild of the solution.

Only the first three steps from the following build instructions are needed to reproduce the problem: https://github.com/jwtowner/d3wasm/blob/master/BUILD.md

**Comment by phillip-elm** [comment]
@jwtowner it does sound like you and I are experiencing a similar issue. In my case:

- My setup is similar to yours: Ryzen 3900X, 64 GB RAM, 2 x 1TB Samsung 970 Plus drives. The drives are 6-7 months old, no errors reported from them.
- I'm running an in-house Golang reverse proxy that, for testing purposes, is serving a WordPress site.
- For context, Golang spins up one OS thread per hardware thread where all goroutines run.
- For each requested resource, the default `net/http` library creates a goroutine to handle the request.
- This "mini-burst" of concurrent filesystem syscalls caused by each page load seems to result in`EIO`  errors when the document root is on the Windows filesystem, accessed from WSL 2.
- The higher the number of concurrent requests, the higher the rate of `EIO` errors - that said, one request with the cache disabled is enough to see one or two `EIO` responses per page.

I'm not familiar with your setup (Visual Studio + WASM + WSL2) - do you know how one could run `strace` on the failing build process?

**Comment by phillip-elm** [comment]
@therealkenc Unfortunately, my time is limited today, [but I was able to throw `strace` in front of the reverse proxy I'm using](https://gist.github.com/phillip-elm/56d9de7f3586bdc31a9beb6217812e65).

Gleaning over all the strace logs, all of the `EIO` errors look like this:

```
newfstatat(AT_FDCWD, "${path}/wp-content/themes/twentytwenty/style.css", 0xc00046e108, 0) = -1 EIO (Input/output error) <0.001725>
newfstatat(AT_FDCWD, "${path}/wp-content/themes/twentytwenty/assets/js/index.js", 0xc000305b08, 0) = -1 EIO (Input/output error)
openat(AT_FDCWD, "${path}/wp-content/themes/twentytwenty/assets/js/index.js", O_RDONLY|O_CLOEXEC) = -1 EIO (Input/output error) <0.001732>
```

All `EIO` errors I'm seeing result from the `newfsstatat` and `openat` syscalls. These errors only occur when accessing multiple files concurrently, as one would when requesting a full web page in a browser. When accessing one file directly, it almost never fails.

Assuming @jwtowner and I are experiencing issues caused by the same bug, the common theme seems to be our system thread count plus a high number of concurrent filesystem stat/open requests where the files live on the Windows host.

**Comment by dpraul** [comment]
I experience this pretty much every time I restart my computer. I notice it when I open VS Code, and vscode-remote gives me a "WSL closed unexpectedly" -- which is currently an open issue here: https://github.com/microsoft/vscode-remote-release/issues/2818.

It seems to be the same WSL2 issue you're facing though. Anytime I try to access a `/mnt/` I get `Input/output error`. Running `sudo umount /mnt/c` gives `umount: /mnt/c: target is busy`.

I have also experienced vscode-remote crashing and ports no-longer mapping between wsl and windows, and this tends to happen when webpack does several consecutive rebuilds (if I'm actively editing multiple files). Same issues as above manifest. This appears to follow the theme of issues due to high number of concurrent filesystem requests between WSL2 and the Windows host.

**Comment by phillip-elm** [comment]
Hi @benhillis and @SvenGroot, is there any word on this issue?

**Comment by rkingsbury** [comment]
I'll add that I've been seeing this issue on a very similar system to those described by @jwtowner and @phillip-elm. I wonder if there's something specific to this hardware configuration? I have a Ryzen 3900X, 32 GB RAM, and a Samsung 970 Evo SSD. Windows 10 20H2 update (build 19042.541), WSL2, Ubuntu 20.04.

For me I get the input/output error every time I sleep the compute for more than ~1 hr. So for example, I can

    Open a WSL2 terminal
    Navigate to my windows filesystem under /mnt/c
    do any command like ls or less <some_text_file>
    Suspend computer for at least 1 hr
    Resume computer
    Issue ls again

And I will have ` Input/output error`.

Note that there is definitely a time element involved here. If I suspend and immediately resume there is no problem. It's only when I leave the PC suspended for some length of time that this occurs.

**Comment by peterdn** [comment]
I'm seeing exactly the same @rkingsbury. WSL2 working fine during normal use, but input/output errors after waking from hibernate. `wsl --shutdown` also restores it to working order.

System details:
* Windows 10 Pro 2004 19041.508
* WSL2 Ubuntu 20.04.1 LTS
* Intel Core i7-6700HQ
* 16GB RAM
* OS installed on a Crucial MX500 1TB SSD
* Data drive: Seagate BarraCuda 2 TB HDD

**Comment by rkingsbury** [comment]
Interesting @peterdn . I should mention that I'm also interacting primarily with an HDD data drive (while the OS is installed on the SSD). I think I've seen the issue when performing file I/O on either disk though.

**Comment by rkingsbury** [comment]
Update: it appears this is not actually related to suspend/resume for me. Rather, it's related to time. This morning I left a process running in my WSL2 environment for ~1-2 hours while I did other tasks (so the computer never went to sleep), and eventually the process failed with an input/output error. This was a program that was continuously appending data to a text-based output file located in the data partition of the HDD (`/mnt/d/....`)

I had to `wsl --shutdown` to get everything working again.

**Comment by matg19** [comment]
I am having the same issue when trying to install several python packages on a Windows drive (HDD with data only) using conda/snakemake to create an environment, the installation runs for a while but it ends up giving the `Input/output error`, I guess it's too many requests happening at the same time as others mentioned but I wonder if it should work regardless

The error does not occur if I install the packages in smaller batches

`wsl --shutdown` gets WSL back to working normally but doesn't fix the issue

**Comment by wclr** [comment]
I wonder if it is going to be fixed, I've described the case when working with remote containers https://github.com/microsoft/vscode-remote-release/issues/6007
