### ISSUE TITLE
Error! Your kernel headers for kernel 4.4.0-19041-Microsoft cannot be found

### ISSUE THREAD

**Issue by ardeal** [microsoft/WSL#5554]
Hi,

I have run the following commands to install GPU driver and CUDA:  
```C
sudo apt install nvidia-driver-440  
sudo apt install nvidia-utils-440
```

Those upper commands have been executed successfully on wsl2.
If I then execute nvidia-smi, I got the following error message:
```C
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
I then run the following commands:
```C
sudo dkms install -m nvidia -v 440.100
```

I got the following error messages:
```C
Error! Your kernel headers for kernel 4.4.0-19041-Microsoft cannot be found.
Please install the linux-headers-4.4.0-19041-Microsoft package,
or use the --kernelsourcedir option to tell DKMS where it's located
```

Thanks,
Ardeal

**Comment by DHowett** [comment]
That kernel version indicates that you are using WSL1.

**Comment by ardeal** [comment]
@DHowett ,
Thanks!
how to check I am using wsl1 or wsl2?

**Comment by licanhua** [comment]
`wsl -l -v` on windows and check the version column. 2 is WSL 2

```
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         2
```

**Comment by ardeal** [comment]
@DHowett ,

Thanks!

I checked the version as follows:
```C
wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
```

I did install the update of WSL2 according to the page:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

and set WSL 2 as default version:
 wsl --set-default-version 2


why is the version still 1 but not 2?

how could I change the version from 1 to 2?

Thanks,

**Comment by licanhua** [comment]
`wsl --set-version <distribution name> <versionNumber>` is the command to convert it wsl 2. So in your case, it's 
```
wsl --set-version  Ubuntu-20.04 2
```

You installed distro before --set-default-version, that's why it's 1

**Comment by ardeal** [comment]
@licanhua ,


Thanks!

I am also considering the issue you mentioned:
You installed distro before --set-default-version, that's why it's 1

now, I have already done that. If I run the command:
wsl --set-version  Ubuntu-20.04 2
The ubuntu I have already installed will be migrate to wsl 2, right?

now, I have run the command wsl --set-default-version 2. 
 should I uninstall the old distro and reinstall ubuntu when the default version is 2?

Thanks,

**Comment by licanhua** [comment]
NO, you don't need to uninstall it.
`wsl --set-version Ubuntu-20.04 2` convert the distro to WSL 2, this the command helps user to migrate distro from 1 to 2.

**Comment by ardeal** [comment]
Thanks,

```C
wsl --set-version  Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.
```

now I run command:
```C
dkms install -m nvidia -v 440.100
Error! Your kernel headers for kernel 4.19.104-microsoft-standard cannot be found.
Please install the linux-headers-4.19.104-microsoft-standard package,
or use the --kernelsourcedir option to tell DKMS where it's located
```



I am still experiencing the issue.

**Comment by therealkenc** [comment]
> 4.4.0-19041

You are on 19041 (whether WSL1 or WSL2) and that version does not support NVIDIA CUDA. The Insiders prerelease of GPGPU support in WSL2 became available in [20150](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20150). Announcement with more links on that [here](https://blogs.windows.com/windowsdeveloper/2020/06/17/gpu-accelerated-ml-training-inside-the-windows-subsystem-for-linux/). Even more [here](https://developer.nvidia.com/cuda/wsl) and [here](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl). Academically the headers error is #2363 et al. TL;DR the kernel support is already baked into the WSL2 Linux kernel 4.19.121 kernel so there is no module to install.

**Comment by ardeal** [comment]
@therealkenc ,

Thanks!

should I uninstall the current versio(19041)n and re-install the version(20150)?
how to uninstall it? Is there any link about the method?

Thanks,

**Comment by therealkenc** [comment]
Landing page for Windows insiders is [here](https://docs.microsoft.com/en-us/windows-insider/at-home/get-started). Instructions [here](https://docs.microsoft.com/en-us/windows-insider/at-home/get-started). The insider blog is [here](https://blogs.windows.com/windowsexperience/tag/windows-insider-program/). There is nothing to uninstall; it is a Windows update. Make sure to set "Windows Update" -> "Advanced Options" -> "Receive updates for other Microsoft Products" to ON which is a common gotcha.

**Comment by ardeal** [comment]
@therealkenc ,

Thanks!
According to you instructions, I am going to install the insider preview version of the latest Window 10.
Does this mean that the latest public release of Windows 10 does not support GPU /CUDA, only the 20150 preview version support GPU/CUDA?

Thanks,



Thanks,

**Comment by therealkenc** [comment]
> only the 20150 preview version support GPU/CUDA?

[Yes](https://github.com/microsoft/WSL/issues/5554#issuecomment-654603464). 20150 or better. CUDA is available only in the [Dev Channel](https://blogs.windows.com/windowsexperience/2020/06/15/introducing-windows-insider-channels/) (formerly Fast Ring) as of this writing.
