### ISSUE TITLE
When copy and pasting a file to Ubuntu file system root directory in Windows Subsystem for Linux using File Explorer, Not able to see the same on the Ubuntu terminal.

### ISSUE THREAD

**Issue by sgrkr** [microsoft/WSL#5555]
I copied and pasted a file inside Ubuntu file system root directory in Windows Subsystem for Linux "C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home
<username>" using File Explorer. I'm able to see the file on the File Explorer but not able to see using the Ubuntu terminal. If I am creating a file using the Ubuntu terminal, the same I can see on the File Explorer. This is really weird, not sure whether it is a bug or something else.

**Comment by therealkenc** [comment]
Accessing that directory is not supported ref #1740 and [FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-use-a-windows-file-with-a-linux-app).
