### ISSUE TITLE
Ошибка: 0xffffffff

### ISSUE THREAD

**Issue by aptem334** [microsoft/WSL#5556]
[logs.zip](https://github.com/microsoft/WSL/files/4883646/logs.zip)

![image](https://user-images.githubusercontent.com/23107015/86749376-e0804300-c045-11ea-914e-6532135cb324.png)

**Comment by aptem334** [comment]
DID NOT UNDERSTAND ANYTHING IN ENGLISH

**Comment by therealkenc** [comment]
Thank-you for the logs. Probably #5092 #4929.

What is your Windows version? `cmd.exe /c ver`

**Comment by aptem334** [comment]
> Thank-you for the logs. Probably #5092 #4929.
> 
> What is your Windows version? `cmd.exe /c ver`

Microsoft Windows [Version 10.0.19041.330]
