### ISSUE TITLE
`~/.bashrc` not sourced when opening a terminal

### ISSUE THREAD

**Issue by michael-angelozzi** [microsoft/WSL#5557]
# Environment

```none
Microsoft Windows [Version 10.0.19041.329]
WSL2, Ubuntu, lsb_release -r:
Release:        20.04
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

1. Put something in `~/.bashrc`, save and close.
2. In windows click start -> `Ubuntu 20.04 icon`
3. Test if `~/.bashrc` was sourced.

e.g.:
```
michael@DESKTOP-9BB5J32:~$ dottest
Command 'dottest' not found, did you mean:
command 'doctest' from deb doctest (0.16.0.1-1build5)
Try: sudo apt install <deb name>
michael@DESKTOP-9BB5J32:~$ source ~/.bashrc
michael@DESKTOP-9BB5J32:~$ dottest
bashrc_ext was sourced
michael@DESKTOP-9BB5J32:~$ lsb_release -r
Release:        20.04
michael@DESKTOP-9BB5J32:~$ echo $SHELL
/bin/bash 
```

#  Expected behavior
`~/.bashrc` was sourced.

# Actual behavior
`~/.bashrc` was **not** sourced.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/86768719-d5f08a00-c002-11ea-91ca-46f0ef0733ec.png)

**Comment by 0xbadfca11** [comment]
You probably have a .bash_profile and no sourced .bashrc in .bash_profile.
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

**Comment by therealkenc** [comment]
Or just a missing `.profile` altogether.

**Comment by michael-angelozzi** [comment]
I don't have a `.bash_profile`, nor a `.profile`.

I found what should be in `.profile` on [askubuntu](https://askubuntu.com/a/161274/433891):
```bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```
...and now it works. From the answer it seems like `.profile` should be added by default to Ubuntu, is it not missing from the WSL release? Is that not the problem which needs to be addressed?

**Comment by michael-angelozzi** [comment]
Additionally how does one change the ubuntu start menu icon to run with `--login`, when one right clicks on it there is no `properties ` option to set the target?

**Comment by therealkenc** [comment]
> From the answer it seems like .profile should be added by default to Ubuntu

It is added by default, as is `.bashrc`. [Imagine if it didn't.] You can re-install of 20.04 from the [Store](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab) if all else fails.

**Comment by michael-angelozzi** [comment]
> > From the answer it seems like .profile should be added by default to Ubuntu
> 
> It is added by default, as is `.bashrc`. [Imagine if it didn't.] You can re-install of 20.04 from the [Store](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab) if all else fails.

Thats what I am working on, a fresh install from 20.04. After I do some testing with this install I will wipe it and start again and double check I didn't do something silly that resulted in no .bashrc and no .profile. 

By the way do you know one can change the ubuntu start menu icon to run with --login? When one right clicks on the icon there is no properties , which allows one to modify the target.
