### ISSUE TITLE
Git on WSL not syncing correctly with repos cloned with Git on Windows

### ISSUE THREAD

**Issue by arafat-ar13** [microsoft/WSL#5558]
I have Git installed on my Windows 10 machine as well as in the Ubuntu 20.04 WSL installation. When setting up, I cloned all my repos using PowerShell Core to my PC using Git Windows. And, as expected, if I made any changes then Git on Windows tracks these and I can view the correct status in PS Core. But I faced something weird when accessing the same repositories using the Ubuntu 20.04 version of Git. When I navigated to the repository using Ubuntu Bash, I saw that everything in that repository was ***not*** staged for commit. I had just cloned them all and there were no edits at all. The Bash shell showed that **all the files of that repo was not staged in red color**. I am attaching a couple of screenshots to show my issue. 
![Annotation 2020-07-07 215722](https://user-images.githubusercontent.com/52791259/86808704-e9e8ca00-c09c-11ea-8f02-5ee54c9d282e.png)
![image](https://user-images.githubusercontent.com/52791259/86808805-0553d500-c09d-11ea-9d6d-73b440fa90e4.png)
I create two empty repositories on my Desktop called "test-app" and both Bash and PS Core show that the master branch is clean. Now I will add some files using PS Core and then staging and committing them using **Git on Windows**. 

![image](https://user-images.githubusercontent.com/52791259/86809276-86ab6780-c09d-11ea-9786-a0a6f938cc06.png)
After committing, I see that the master branch is clean again and all changes were saved. Now look at what happens when I view using repository using Bash.
![image](https://user-images.githubusercontent.com/52791259/86809708-f9b4de00-c09d-11ea-9450-a5f71aff9799.png)
It shows that the "info.txt" file was modified and needs to be staged, but I did that already using PS Core so why am I still seeing that my master branch is not clean? To further explain, my first commit is surprisingly available in the `git log` command in the Bash shell.
![image](https://user-images.githubusercontent.com/52791259/86810103-64feb000-c09e-11ea-9357-3ecaaa7b173b.png)

So the Git installed in WSL does know that the commit was made, but still shows that changes are not staged. What could be the reason that this is occurring? Interestingly, if I made edits and commit them using Bash, git on Windows actually knows about this commit and PS Core shows that my branch is clean. So, this is a one-way issue.

Please also know that my Git in WSL is configured with the same Git account details and GitHub credentials as the Windows variant. Any help or insight on this matter is really wanted and appreciated. Thanks.

**Comment by craigloewen-msft** [comment]
Hi @arafat-ar13 , can you please resubmit this issue with the Bug template? This will help make sure we have the necessary info that we need to help resolve your problem. Thank you!

**Comment by arafat-ar13** [comment]
Hey there, @craigloewen-msft, thanks for letting me know. I'll do that soon. Can you please confirm if I can use the same title while resubmitting?

**Comment by craigloewen-msft** [comment]
Yup that's not a problem to use the same title.
