### ISSUE TITLE
Question: Launch powershell from emacs WSL

### ISSUE THREAD

**Issue by JuanPabloMF** [microsoft/WSL#5560]
Hi,

My IDE/text editor is emacs. I installed wsl2 and followed this repo (https://github.com/hubisan/emacs-wsl) to set up emacs on wsl.

I am working on an automation pipeline, so the code must be executed from powershell (access to windows programs, pyautogui etc.). I still do my editing from emacs, so my files are in wsl filesystem. 

Can I use powershell directly from emacs? Emacswiki link seem obsolete (powershell.el is from 2010) and couldn't find any trivial way to launch my automation load directly from emacs/

**Comment by craigloewen-msft** [comment]
Hi @JuanPabloMF can you please resubmit your issue without deleting the bug template? This will help make sure we have all the necessary info that we need to help resolve your issue. Thank you!
