### ISSUE TITLE
Error: 0x80041001  Unable to install linux distributions.

### ISSUE THREAD

**Issue by Random06457** [microsoft/WSL#5561]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
```

# Steps to reproduce

Get a linux distribution from the Windows Store and run it. (See more in `Additional Context` below).

#  Expected behavior
The distribution should install without any problem.

# Actual behavior
The installation fails with the following error:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```
Detailed Logs: [lxcore logs.zip](https://github.com/microsoft/WSL/files/4887005/lxcore.logs.zip)

Note: At some point I got the following two errors bellow (I didn't do anything specific beside uninstalling/reinstalling multiple times the same linux distribution with some variants like repairing or resetting the app from `Apps & features`). However I didn't do any log collections and now I only get the error above.
```
WslRegisterDistribution failed with error: 0x80041001
Error: 0x80041001 (null)
```
```
WslRegisterDistribution failed with error: 0x80370110
Error: 0x80370110 The virtual machine or container with the specified identifier is not running.
```

# Additional context
WSL used to work fine on my machine (I was using WSL2 with Ubuntu) until I had a power outage ( I think?) which made my computer reboot on Windows 7 (I have two HDDs: my main HDD which is on Windows 10 and is supposed to have the highest boot priority and an old HDD which is on Windows 7). However when booting, Windows 7 did some kind of file system scan and apparently did some modifications to my files (it kept printing `Deleting extended attribute set due to presence of reparse point in the file ...`). After this event WSL stopped working on my Windows 10 system: 
![unknown](https://user-images.githubusercontent.com/28494085/86841572-68953580-c0a4-11ea-977a-dc1a11b9f0e7.png)

So I decided to uninstall my Ubuntu distribution (I ran `wslconfig /u Ubuntu`, uninstalled Ubuntu from `Apps & features` and turned off `Windows Subsystem for Linux` in `Turn Windows features on or off`) and tried to reinstall it from scratch. And I am now getting the issue described above.

**Comment by therealkenc** [comment]
Thank-you for the logs.

> it kept printing `Deleting extended attribute set due to presence of reparse point in the file ...`

That's "not good". You've done the right thing, which is to reinstall best you can. I don't have any specific suggestions on how re-install _harder_. Maybe disable then re-enable Virtual Machine Platform. You might get lucky and a Windows Update will magically address like #5050, as it "re-installs all the things".

**Comment by Random06457** [comment]
You were right! After installing the latest Windows Update (including `KB4565627` and `KB4565503`), WSL fixed itself and is now working perfectly with both WSL1 and WSL2. I wonder if there is another way to re-install WSL completely without having to wait for a Windows Update.

**Comment by therealkenc** [comment]
> if there is another way to re-install WSL completely

There isn't specifically, because there are a lot of moving parts. But then that isn't a state of affairs unique to WSL. Standard operating procedure is to make sure you have a system restore point handy that you can recover to when necessary.

**Comment by danvln** [comment]
It would be great to let us know what you mean by "re-installs all the things". I have the same issue and could not fix it, even after the updates specified. The only option for me was to go back to wsl 1.

**Comment by vanhoanHoang** [comment]
@Random06457 Could you fix this issue. I'm having the same problem. Thank.

**Comment by Random06457** [comment]
> @Random06457 Could you fix this issue. I'm having the same problem. Thank.

Sorry for the late reply.
I'm not sure I understand what you're asking. In my case the issue fixed itself with a windows update.
