### ISSUE TITLE
How can the kernel been updated to the 5.5.6 version?

### ISSUE THREAD

**Issue by vicentegarciadiez** [microsoft/WSL#5562]

**Comment by therealkenc** [comment]
WSL is moving to 5.4 "soon". It is somewhat safe to assume a new series after that would come when the [upstream](https://www.kernel.org/) official Linux kernel entered "longterm" maintenance. More on the general topic over [here](#95).

**Comment by vicentegarciadiez** [comment]
But, taking into account this branch [https://github.com/microsoft/WSL2-Linux-Kernel/tree/v5.5.6](https://github.com/microsoft/WSL2-Linux-Kernel/tree/v5.5.6)

How can I compile this kernel and start to using it in WSL2?
