### ISSUE TITLE
Git on WSL not syncing correctly with repos cloned with Git on Windows

### ISSUE THREAD

**Issue by arafat-ar13** [microsoft/WSL#5563]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
```

# Steps to reproduce

I have Git installed on my Windows 10 machine as well as in the Ubuntu 20.04 WSL installation. When setting up, I cloned all my repos using PowerShell Core to my PC using Git Windows. And, as expected, if I made any changes then Git on Windows tracks these and I can view the correct status in PS Core. But I faced something weird when accessing the same repositories using the Ubuntu 20.04 version of Git. When I navigated to the repository using Ubuntu Bash, I saw that everything in that repository was not staged for commit. I had just cloned them all and there were no edits at all. The Bash shell showed that all the files of that repo was not staged in red color. I am attaching a couple of screenshots to show my issue.

Now, let's create a new repo and demonstrate my problem.
![image](https://user-images.githubusercontent.com/52791259/86901137-008b3180-c12e-11ea-9020-62a1b2311754.png)
![image](https://user-images.githubusercontent.com/52791259/86901143-03862200-c12e-11ea-935f-bc6ceacba432.png)
I create two empty repositories on my Desktop called "test-app" and both Bash and PS Core show that the master branch is clean. Now I will add some files using PS Core and then staging and committing them using Git on Windows.

![image](https://user-images.githubusercontent.com/52791259/86901508-88713b80-c12e-11ea-9f32-2efd422ccc0a.png)
After committing, I see that the master branch is clean again and all changes were saved. Now look at what happens when I view the repository using Bash.
![image](https://user-images.githubusercontent.com/52791259/86901529-90c97680-c12e-11ea-8096-85b0ca168b3a.png)
It shows that the "info.txt" file was modified and needs to be staged, but I did that already using PS Core so why am I still seeing that my master branch is not clean? To further explain, my first commit is surprisingly available in the git log command in the Bash shell.
![image](https://user-images.githubusercontent.com/52791259/86901543-958e2a80-c12e-11ea-93f0-7f54c5d0ae94.png)

So the Git installed in WSL does know that the commit was made, but still shows that changes are not staged. What could be the reason that this is occurring? Interestingly, if I made edits and commit them using Bash, git on Windows actually knows about this commit and PS Core shows that my branch is clean. So, this is a one-way issue. Please also know that my Git in WSL is configured with the same Git account details and GitHub credentials as the Windows variant.

#  Expected behavior

Git in WSL should know that the edited files were staged and commit and the master is clean although I made changes using Git on Windows. It should be synced with the correct state of the repository whether the changes were committed using WSL Git or Git from PS Core on Windows. 

# Actual behavior

It shows **already committed** changes as unstaged and in red color **although** the commit is readily visible in the `git log`.

**Comment by 0xbadfca11** [comment]
Because you didn't match ``core.autocrlf`` on both sides.
https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-line-endings
![image](https://user-images.githubusercontent.com/7390559/86921858-c427f780-c166-11ea-938d-8ec97ff26b2c.png)
https://github.com/microsoft/WSL/issues?q=is%3Aissue+core.autocrlf

**Comment by arafat-ar13** [comment]
@0xbadfca11 Okay thank you so much for the suggestion. I will make sure to use same line endings on both sides. Thanks. 😄
