### ISSUE TITLE
WSL 2 on Windows 10 Home

### ISSUE THREAD

**Issue by TheProgramableTurtle** [microsoft/WSL#5564]
If WSL 2 requires Hyper-V to be enabled, but Hyper-V is not available on Windows 10 Home, how can Windows 10 Home support WSL 2?

**Comment by 0xbadfca11** [comment]
WSL 2 requires [Windows hypervisor](https://docs.microsoft.com/en-us/previous-versions/technet-magazine/cc895595(v=msdn.10)), part of Hyper-V, available on Windows 10 Home. Not requires whole of Hyper-V.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#does-wsl-2-use-hyper-v-will-it-be-available-on-windows-10-home

**Comment by TheProgramableTurtle** [comment]
So there is no advantage to using Windows 10 Pro for WSL 2?

**Comment by 0xbadfca11** [comment]
I don't think there is any advantage.

**Comment by therealkenc** [comment]
Docker is [available](https://www.docker.com/blog/docker-desktop-for-windows-home-is-here/) on Windows Home now too.

**Comment by TheProgramableTurtle** [comment]
Ok, that makes more sense, thanks!
