### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by ReneKat** [microsoft/WSL#5565]
# Environment

```
$ lsb_release -r
Release:        20.04
$ cat /proc/version
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce

```
$ megahit --12 /mnt/d/HBOI/FCCHH/01_Preprocessing/bbtools/per_site/FP_site.fq.gz --presets meta-large -m 0.9 -t 12 -o /mnt/d/HBOI/FCCHH/02_Assembly/megahit/FP
2020-07-08 13:55:53 - MEGAHIT v1.2.9
2020-07-08 13:55:53 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/home/renekat/anaconda3/envs/assembly/bin/megahit", line 1038, in <module>
    main()
  File "/home/renekat/anaconda3/envs/assembly/bin/megahit", line 988, in main
    build_library()
  File "/home/renekat/anaconda3/envs/assembly/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/home/renekat/anaconda3/envs/assembly/bin/megahit", line 719, in build_library
    create_fifo('pe12', i, inpipe_cmd(opt.pe12[i]))
  File "/home/renekat/anaconda3/envs/assembly/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
PermissionError: [Errno 1] Operation not permitted
```
Gist: "https://gist.github.com/ReneKat/e947b917189da640b739747cd806b96c.js"

#  Expected behavior

megahit is an assembly tool. It creates and output file and populates it with data.

# Actual behavior

Soon after starting the tools exits with a PermissionError:[Errno 1] Operation not permitted
I am working in a conda environment. I am updated conda and updated megahit. 

Any direction would be appreciated, as I'm new to WSL. Thank you!

**Comment by therealkenc** [comment]
[gist](https://gist.github.com/ReneKat/e947b917189da640b739747cd806b96c#file-megahit-strace)

```
25255 mknod("/mnt/d/HBOI/FCCHH/02_Assembly/megahit/FP/tmp/inpipe.pe12.0", S_IFIFO|0666) = -1 EPERM (Operation not permitted)
```

You can try turning on metadata in [/etc/wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-options). Something like:
```
[automount]
options = "metadata"
```

Better still, keep your working files in `/home/renekat/HBOI` instead of `/mnt/d/HBOI`.

**Comment by ReneKat** [comment]
Hello @therealkenc ,
Thank you very much for your reply! When I changed my pwd to be /home/renekat/HBOI this resolved my issue. 
I suppose best practice would be to just backup to the external hard drive daily. 
Thanks again,
Rene
