### ISSUE TITLE
git in WSL 2 does not pick up changes made in Visual Studio 

### ISSUE THREAD

**Issue by ruijxu** [microsoft/WSL#5566]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.900]
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft
```

# Steps to reproduce

Using Zsh as default shell in Ubuntu 18.04, but I can reproduce it in Bash as well.

Open a Ubuntu 18.04 app, navigate to the git repo on local filesystem.
Open the Visual Studio solution in Visual Studio 2017.
Make changes to tracked .cs file, Save in Visual Studio 2017.
go back to Ubuntu 18.04 app, do a `gst` or `git status`, there is no dirty files.
(close, and open a new Ubuntu 18.04 app, navigate to the repo again, do a `git status` will show the changes)

#  Expected behavior
`git status` on Ubuntu 18.04 app shows the changes made in Visual Studio 2017.

# Actual behavior
`git status` on Ubuntu 18.04 app does not show the changes, but a `git status` after close and reopening the Ubuntu 18.04 app does.

**Comment by ruijxu** [comment]
my teammate have suggested that Visual Studio 2017 maybe doing something with the git locks, so this may not be a WSL issue.

**Comment by therealkenc** [comment]
You might be able to get some feedback/suggestions in a Visual Studio forum.
