### ISSUE TITLE
When reverting back to WSL 1 from WSL 2, directory structure still exists

### ISSUE THREAD

**Issue by daveomcd** [microsoft/WSL#5571]
I recently tried upgrading to WSL2, but ran into various network issues and VPN related issues.  I'm now reverting back to WSL1.
When I completed that step I noticed that my home directory is still, "\\wsl$\Ubuntu\home\daveomcd".

Is this the expected behavior?  And is it fine to still use this location while working with WSL1?  I was believed that WSL2 constructed a virtualized environment for it's use, in my ignorant mind I wouldn't have expected this file location to still exist or even be used after I reverted by to WSL1.

**Comment by benhillis** [comment]
Yes that is expected. We run the same 9p server for wsl1 as well.
