### ISSUE TITLE
Scapy is not able to sniff packets at my network interface.

### ISSUE THREAD

**Issue by Alinaahmad** [microsoft/WSL#5572]
I'm using Scapy, on WSL. I checked for my network interface which is "wifi0". Using scapy I am trying to implement a packet sniffer.

import scapy.all as scapy
from scapy.layers import http
def sniff(interface):
8.    scapy.sniff(iface=interface, store=False, prn=process_sniffed_packet)

def process_sniffed_packet(packet):
    if packet.haslayer(http.HTTPRequest):
        
        #Extracting useful URLs
        url = packet[http.HTTPRequest].Host + packet[http.HTTPRequest].Path
        print("[+] HTTP Request >>" + URL)
.
.
.
.
.
.
.
    
27. sniff("wifi0")

Executing this throws an error, as under.

Traceback (most recent call last):
  File "Packet_Sniffer.py", line 27, in <module>
    sniff("wifi0")
  File "Packet_Sniffer.py", line 8, in sniff
    scapy.sniff(iface=interface, store=False, prn=process_sniffed_packet)
  File "/usr/local/lib/python3.8/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scapy/sendrecv.py", line 841, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

**Comment by therealkenc** [comment]
> self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type)) # noqa: E501
> OSError: [Errno 97] Address family not supported by protocol

/dupe #717 #1349 et al.

**Comment by omarakl** [comment]
If you are using kali Linux and installing it on a virtual machine then you need to buy a wifi adapter. Or you should install the kali linux on your real machine. Also remove the iface argument from sniff function. 

That worked for me 

Good luck :)
