### ISSUE TITLE
WSL report 444 permission for file while Cygwin report 400

### ISSUE THREAD

**Issue by BeErikk** [microsoft/WSL#5573]
# Environment
Microsoft Windows [Version 10.0.19041.329] (release, no insider)
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```
Release:        20.04
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

# Steps to reproduce
WSL1 /home/.ssh is a WSL symbolic link to Windows directory %HOMEDRIVE%%HOMEPATH%/.ssh (all NTFS)
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0444 for '/home/<user>/.ssh/id_rsa' are too open.
$ cd ~/.ssh
$ icacls.exe id_rsa '/reset'
$ icacls.exe id_rsa '/inheritance:r /grant:r "<user>:(R)"'
$ stat -c "%a %n" ~/.ssh/id_rsa
444 /home/<user>/.ssh/id_rsa
```
Without the symbolic link
```
$ stat -c "%a %n" /mnt/d/Users/<user>/.ssh/id_rsa
444 /mnt/d/Users/<user>/.ssh/id_rsa

```
In cygwin:
```
$ stat -c "%a %n" /cygdrive/d/Users/<user>/.ssh/id_rsa
400 /cygdrive/d/Users/<user>/.ssh/id_rsa
```
Thus it is impossible to do a `git push` from WSL although it's fine in Git for Windows and Cygwin. Note the `HOME/.ssh` is intended to be shared by several environments.

#  Expected behavior
```
$ stat -c "%a %n" ~/.ssh/id_rsa
400 /home/<user>/.ssh/id_rsa
```

# Actual behavior

```
$ stat -c "%a %n" ~/.ssh/id_rsa
444 /home/<user>/.ssh/id_rsa
```
--------------------------------------------------------------------------
Or is there another way to obtain 400 file permissions in WSL?

**Comment by therealkenc** [comment]
Cygwin and WSL's file permissions are unrelated.

You can try turning on metadata in [/etc/wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-options) and set permissions with `chmod` of `/mnt/c/User/you/.ssh/id_rsa`. Something like:
```
[automount]
options = "metadata"
```
You'll need a `wsl --shutdown` for it to take.

Better still, don't share your `.ssh` directory like that.

**Comment by BeErikk** [comment]
OK, thanks, it works!

```
$ cat > wsl.conf
[automount]
options = "metadata"
$ sudo cp wsl.conf /etc/wsl.conf
cmd>wsl.exe --shutdown
cmd>icacls.exe id_rsa /reset
$ chmod 400 ~/.ssh/id_rsa
$ stat -c "%a %n" ~/.ssh/id_rsa
400 /home/me/.ssh/id_rsa
```
Test:
```
$ git push
Enter passphrase for key '/home/me/.ssh/id_rsa':
```
Works!

As I could understand, this doesn't change the actual file permissions in Windows? Are these permissions only visible for WSL? How can I delete the metadata?

cheers Erik

**Comment by therealkenc** [comment]
> doesn't change the actual file permissions in Windows

Windows doesn't have file permissions. WSL is unrelated to Cygwin.
