### ISSUE TITLE
Can't convert existing wsl 1 linux image to wsl 2. Also can't install ubuntu as wsl 2 from scratch.  Windows 10 Home.

### ISSUE THREAD

**Issue by jcimoch** [microsoft/WSL#5574]
# Environment

```none
Windows 10 Home

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Microsoft Windows [Version 10.0.19041.329]
```

# Steps to reproduce

```
PS C:\Users\jaros> wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
There are no more endpoints available from the endpoint mapper.
PS C:\Users\jaros>

```

#Attached logs

I was following the instruction, please let me know if those logs are helpful in any way
[logs.zip](https://github.com/microsoft/WSL/files/4905633/logs.zip)

#  Expected behavior

```should convert linux distribution to wsl 2```

# Actual behavior

There are no more endpoints available from the endpoint mapper. ---> conversion failed
```
> wsl --list --verbose

  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1
  Ubuntu-18.04    Stopped         1

 ```

related issues: 
#4403 
#5152

I tried reinstalling/restaring windows features related to WSL without any change in behaviour. 
I also tried uninstalling all distributions and installing from scratch with default wsl set to version 2. But in that scenario I falled into #5331 issue. 

Any help will be really welcome, I'm blocked from using docker and I just have bought home license :(

**Comment by therealkenc** [comment]
The suggestion over in #4403 was to collect [network logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs).
