### ISSUE TITLE
Single WSL2 localhost port can't be accessed from Windows side

### ISSUE THREAD

**Issue by peterjuras** [microsoft/WSL#5575]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019
```

# Steps to reproduce

1. Create and start a new `create-react-app` app:
```
npx create-react-app my-app
cd my-app
npm start
```
2. Try to access it from the browser using the localhost address: `localhost:3000`
-> The browser can't connect
3. Re-start the app by specifying a different port `PORT=3001 npm start`
-> The browser can connect

# Further details

I expect that this is due to specific configuration on my machine, but I don't know what is wrong. I disabled Windows Firewall and it still doesn't work. Fast Startup is turned off. Accessing the react app through the ip address + port works as expected. Restarting Windows and WSL 2 (multiple times) did not help.

I assume that this issue is similar to issues #5497 and #5298, but I can access servers that are running on different ports (e.g. 5000, 8080, 3001, etc.).

Any workaround would be appreciated. If possible I would like to not need to get into the insider program again, I am hoping I can stay on the stable 2004 version.

**Comment by onomatopellan** [comment]
Open PowerShell and post the output of:
`netsh int ipv4 show excludedportrange protocol=tcp`
`netsh int ipv4 show dynamicport tcp`

**Comment by peterjuras** [comment]
```
C:\Users\pjura> netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
     50000       50059     *
     55651       55750
     55751       55850
     55991       56090
     56091       56190

* - Administered port exclusions.
```
```
C:\Users\pjura> netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384
```

**Comment by onomatopellan** [comment]
thanks, tcp dinamic assignation is not the problem then.

Try `HOST=0.0.0.0 npm start` and see if localhost:3000 works

**Comment by peterjuras** [comment]
No, sadly `HOST=0.0.0.0 npm start` does not work.

**Comment by onomatopellan** [comment]
In Resource Monitor -> Network tab- > Listening ports can you see if there is an exe listening on port 3000?

**Comment by peterjuras** [comment]
Thanks for helping!
Yes it listing a process, although I have neither anything open with port 3000 or 3100. I also can't find any firewall rule which restricts port 3000 🤔 

This is a screenshot of the resource monitor view: https://imgur.com/8qTO4Q6
![Annotation 2020-07-12 092742](https://user-images.githubusercontent.com/3640638/87241297-00d34780-c422-11ea-8d21-1479a8f14191.png)

**Comment by onomatopellan** [comment]
Some service is using both ports. To know the service on the same Resource Monitor go to CPU tab -> Services, order by PID and look for PID 4248.

**Comment by therealkenc** [comment]
What Ono said. Or from powershell, using TCP port `5040` as example, which is the Connected Device Platform Service

```
PS C:\> (Get-WmiObject -Class Win32_Service | where ProcessId -eq (Get-Process -Id (Get-NetTCPConnection -LocalPort 5040).OwningProcess).Id).Name
```

![image](https://user-images.githubusercontent.com/7049700/87249885-9b2d8e00-c416-11ea-874e-6b890977d6be.png)

**Comment by peterjuras** [comment]
Thanks a lot for the help. 👍 🙏 

It appears that the _IP Helper_ service was the culprit and after disabling it the port worked again. I assume this did not have anything to do with WSL 2 then, therefore I'm closing the issue.

**Comment by lgyaxx** [comment]
> What Ono said. Or from powershell, using TCP port `5040` as example, which is the Connected Device Platform Service
> 
> ```
> PS C:\> (Get-WmiObject -Class Win32_Service | where ProcessId -eq (Get-Process -Id (Get-NetTCPConnection -LocalPort 5040).OwningProcess).Id).Name
> ```
> 
> ![image](https://user-images.githubusercontent.com/7049700/87249885-9b2d8e00-c416-11ea-874e-6b890977d6be.png)

Thanks a million for this!

**Comment by adolgoff** [comment]
Just in case it happened to someone else and there were no such ports open during in-windows inspection, but inside WSL port was listened: it helped me simply to restart WSL by `wsl --shutdown {name}` and starting it then again.

**Comment by damienallen** [comment]
> Just in case it happened to someone else and there were no such ports open during in-windows inspection, but inside WSL port was listened: it helped me simply to restart WSL by `wsl --shutdown {name}` and starting it then again.

Restarting WSL was also the solution that I needed! The PS command is still very useful for troubleshooting this though!

**Comment by larizzatg** [comment]
> wsl --shutdown

This solved my issue, thank you

**Comment by micskeil** [comment]
> _IP Helper_ service 
Turning off IP helper was the solution for me!

**Comment by joshjm** [comment]
Ive tried a bunch of other things, but I had to disable IP Helper service to be able to access my stack on `localhost:4200` on windows 11, wsl2. weird that this seems to be the issue, i dont think I had this problem with win 10 or running natively on ubuntu. 

I wonder if there is some conflict here with the service that needs a more serious look at.

**Comment by tekkies** [comment]
This worked for me
https://superuser.com/a/1671709/28261

**Comment by RunhangShu** [comment]
In my case, my port is not allowed. After I add a new rule allowing the port in window firewall, it works. https://pureinfotech.com/open-port-firewall-windows-10/

**Comment by savely-krasovsky** [comment]
I think this problem is still there. Yes, `wsl.exe --shutdown` helps, but I have to do it almost daily, since our corporate VPN uses `localhost:RANDOM_HIGH_PORT` to receive authorization code from OAuth2 callback. And it just cannot do it, since port is used by something (wsl? IP Helper?)

**Comment by danon** [comment]
It's possible that random dynamic ports for IANA are blocking docker containers.

To verify, whether you have the problem, run
```
netsh int ipv4 show dynamicport tcp
```

If the `Start Port` is around 1000-2000, that's likely that IANA ports are blocking your wsl ports.

Set that, and then reboot:
```
netsh int ipv4 set dynamic tcp start=49152 num=16384
netsh int ipv6 set dynamic tcp start=49152 num=16384
```
