### ISSUE TITLE
file listing in WSL via Terminal varies depending on invocation of WSL

### ISSUE THREAD

**Issue by mayureshkathe** [microsoft/WSL#5576]
# Environment

Windows build number: Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Under Debian, but it does not have "lsb_release" and I don't know which package it is part of.
Whether the issue is on WSL 2 and/or WSL 1: WSL 2. Output of "cat /proc/version" below;
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020

# Steps to reproduce

Run the WSL invocation from PowerShell command prompt (such as "debian") and run "ls" and the Windows file-system isn't shown, but invoke WSL via the sub-menu on Windows Terminal Preview (such as pull-down menu item "debian") and run "ls" in the reulting WSL environment and the Windows file-system is shown.

#  Expected behavior

Either ways, either show the Windows file-system, or don't show the Windows file-system when WSL is invoked in any manner.
Didn't know if this was a bug with Terminal or WSL, so going to file it with both projects.

# Actual behavior

Everything is mentioned above.

**Comment by therealkenc** [comment]
The launch directory of the debian start menu item is controlled by the distribution maintainers. You can customize Terminal's behavior with its `settings.json`. You probably want `"commandlin:" wsl.exe -d <distro> ~`
