### ISSUE TITLE
USB support in WSL2

### ISSUE THREAD

**Issue by darkRaspberry** [microsoft/WSL#5577]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i connect a USB and i want to use USB and its is not supported

**Describe the solution you'd like**
When i plug any USB it should work as normal. Like i can access any file stored in it.

**Describe alternatives you've considered**
NOPE

**Additional context**
Need support in USB on Insiders preview latest on 11/07/2020
Version	10.0.20161 Build 20161

**Comment by robokamran** [comment]
Microsoft says specifically in here that there is [NO USB SUPPORT FOR WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2-are-there-plans-to-increase-hardware-support)
So you could stop trying and use real Linux instead :))
there are some hack such as USB-over-IP but may not work on some devices.
I also am desperately looking for a way to use joystick in my ROS Gazebo but there is no way :'(

**Comment by darkRaspberry** [comment]
either they close this issue or but this in back log
lets see
