### ISSUE TITLE
distribution registry reports wsl version 2 while it is wsl version 1

### ISSUE THREAD

**Issue by patrick330602** [microsoft/WSL#5578]
# Environment

```none
Windows build number: 20161
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: N/A
```

# Steps to reproduce

checking the distribution key under the `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`.

#  Expected behavior

It should reflect the correct `Version` key for wsl version used under each distribution key.

# Actual behavior

All `Version` value under distribution key reports a value of 2 even the distribution is on wsl1, as shown below:

![image](https://user-images.githubusercontent.com/15316889/87228932-f8a1ea80-c3d6-11ea-80a5-171f03bc8013.png)

**Comment by DHowett** [comment]
The registry is not a supported WSL API.
`Version` indicates whether `wslfs` or `lxfs` was used for the root filesystem, and has nothing to do with the WSL version.

The most effective way currently available to determine whether a distribution is using WSL2 is by interrogating `wsl.exe -l -v`.

The registry keys are an unsupported implementation detail.

**Comment by Biswa96** [comment]
@patrick330602 See 'Flags' dword registry. WSL1 == (0 + 1 +2 + 4) and WSL2 == (0 + 1 + 2 + 4 + 8).

**Comment by Biswa96** [comment]
@patrick330602 See 'Flags' dword registry. WSL1 == (0 + 1 + 2 + 4) and WSL2 == (0 + 1 + 2 + 4 + 8).

**Comment by patrick330602** [comment]
Thanks for the information!
