### ISSUE TITLE
Connecting to a web server running in wsl from native windows application is very slow.

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [microsoft/WSL#5579]
I recently started using WSL. I created a Laravel web application. When I issue command:
`php artisan serve`

I get a server address of 127.0.0.1:8000.

when I connect to it from my Native windows Edge Browser or Chrome Browser, It takes over a minute to load. Then navigating between pages also takes many minutes. That hampers down my speed considerably.

**Comment by therealkenc** [comment]
Please re-submit your issue following the [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md) in particular all relevant commandline steps leading up to `php artisan serve`. An `strace -f -t` log may help identify where your server is spending its time.
