### ISSUE TITLE
Getting Error while updating apps into Ubuntu. I am using WSL. 

### ISSUE THREAD

**Issue by vivekshinde93** [microsoft/WSL#5581]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

#  Expected behavior

# Actual behavior

I am trying to update my apps in Ubuntu terminal using sudo apt-get update but its giving me an error as "double free detected in tcache2" . What are the possible solution to solve this issue and update my apps. I have tried using apt upgrade --fix--missing. What more should I try ?
![image](https://user-images.githubusercontent.com/66086980/87282967-70c0fb00-c512-11ea-83d3-28c78bea2084.png)
![image](https://user-images.githubusercontent.com/66086980/87283077-8e8e6000-c512-11ea-961f-023e58ffbf30.png)

**Comment by rohandreamerz** [comment]
> # Environment
> ```
> Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
> Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
> Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
> ```
> 
> # Steps to reproduce
> # Expected behavior
> # Actual behavior
> I am trying to update my apps in Ubuntu terminal using sudo apt-get update but its giving me an error as "double free detected in tcache2" . What are the possible solution to solve this issue and update my apps. I have tried using apt upgrade --fix--missing. What more should I try ?
> [![image](https://user-images.githubusercontent.com/66086980/87282967-70c0fb00-c512-11ea-83d3-28c78bea2084.png)](https://user-images.githubusercontent.com/66086980/87282967-70c0fb00-c512-11ea-83d3-28c78bea2084.png)
> [![image](https://user-images.githubusercontent.com/66086980/87283077-8e8e6000-c512-11ea-961f-023e58ffbf30.png)](https://user-images.githubusercontent.com/66086980/87283077-8e8e6000-c512-11ea-961f-023e58ffbf30.png)

hmm...
