### ISSUE TITLE
The Ethernet stops working when WSL is disabled and enabled again.  

### ISSUE THREAD

**Issue by AAlMutairi** [microsoft/WSL#5586]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
WSL 2
```

# Steps to reproduce

I tried to disable both WSL and hyper-V and enable them again through "Turn Windows Features on or off" in the hope that it might fix the issue reported here: https://github.com/microsoft/WSL/issues/5423

However, after re-enabling them. The Ethernet stopped working. Right now, if I disable both, the Ethernet works fine but when I enable them it stops again.

**Comment by therealkenc** [comment]
This is a generic "hooped Windows beyond redemption with unknown and probably unknowable actions". There are multiple instances of people disabling and re-enabling Virtual Machine Platform (indeed, it is a common scenario) without blowing away their Windows networking. There is no reasonable way to reproduce your specific circumstances locally, nor pend this submission on like/me2 confirmation from others that would be meaningful. Practical remedy is going to be recover from a restore point or your external Windows backup. We can float this open for a bit in case there are suggestions from the community on recovering your network short of that, but there is no present way to turn this into an actionable.
