### ISSUE TITLE
Ctags doesn't work in Vim

### ISSUE THREAD

**Issue by coldspark29** [microsoft/WSL#5588]
Windows Version: 10.0.18362.900

**Steps to reproduce**
1. Install WSL2
2. Install ctags and vim
3. Tag a source directory with ```ctags -R .```
4. Open vim and try to jump to function definitions with Ctrl+]
5. Vim reports no tags stack was found

**Expected behavior'**
Vim should jump to the function definition

**Comment by therealkenc** [comment]
Cannot repro here.

![vim-ctags](https://user-images.githubusercontent.com/7049700/87476508-5a32a680-c5db-11ea-9f61-273a2ba4511e.gif)
