### ISSUE TITLE
Not utilizing all cores with multithreaded workload

### ISSUE THREAD

**Issue by CocoaMix86** [microsoft/WSL#5589]
# Environment

```none
Windows build number: 10.0.18363.0
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft
```

# Steps to reproduce

1. Setup a neural network using Torch
https://github.com/billzorn/mtg-rnn
2. Attempt to train the network
`th train.lua -data_dir data/mtgencode-std/ -rnn_size 256 -num_layers 3`
3. view the CPU usage in task manager

#  Expected behavior

This should use all cores of the CPU at 100%.

# Actual behavior

It uses a single core, ~10% CPU (for me) and training is extremely slow.

# Additional Notes

I'm using a Ryzen 5 1600x (6 cores). On the same computer, if I boot into Ubuntu instead of Windows and run the same program, it does use all cores.

**Comment by therealkenc** [comment]
> Windows build number: 10.0.18363.0

You could post an actual repro and threaded `strace(1)` log of the `th train.lua` but in this instance it would be mostly academic to find a diverge from linux-behavior. You want 19042 WSL2.
