### ISSUE TITLE
MSBuild project yields "Cannot create remote project directory: ... 'projects/ConsoleApplication1'. Please check directory permissions"

### ISSUE THREAD

**Issue by oregonduckman** [microsoft/WSL#5595]
I am trying to build a simple WSL 2 targeted console app that will not build because of the following error message:

MSBuild project yields "Cannot create remote project directory: ... 'projects/ConsoleApplication1'. Please check directory permissions"

Please note that build a CMake app does not cause the error and successfully executes on WSL 2.

Please advise.

**Comment by therealkenc** [comment]
Please see the submission template and re-file with commandline steps and an strace log of the failing command.

**Comment by therealkenc** [comment]
#5602 can be the landing zone since it appears to be the same error.
