### ISSUE TITLE
WSL is not recognized as the name of a cmdlet, etc

### ISSUE THREAD

**Issue by matze19999** [microsoft/WSL#5596]
Windows 10 20170 ARM64
Device: Microsoft Surface Pro X
WSL Version: 2

I'm trying to run wsl from powershell, but can't get it working. It always says that the file wasn't found. It works perfectly with cmd. System32 folder is in path and wsl.exe exists.

Even if I point directly to the file, it is totally ignored.

![image](https://user-images.githubusercontent.com/13684520/87671394-9861ce80-c771-11ea-810a-6cd7f12a43d5.png)

Get-Childitem also ignores wsl.exe:

![Anmerkung 2020-07-16 143441](https://user-images.githubusercontent.com/13684520/87671360-87b15880-c771-11ea-9199-3ea416ad9a14.png)

This is insane....

**Comment by matze19999** [comment]
![image](https://user-images.githubusercontent.com/13684520/87671493-b9c2ba80-c771-11ea-9bf7-897873485dfe.png)

It's visible and executable in explorer and cmd, but completely ignored by powershell

**Comment by Okesik** [comment]
".\wsl.exe" might not be valid PS syntax, it should start just by typing "wsl" as this is linked command.

**Comment by matze19999** [comment]
> ".\wsl.exe" might not be valid PS syntax, it should start just by typing "wsl" as this is linked command.

Just typing "wsl" also says that the command wasn't found

**Comment by therealkenc** [comment]
Usually means a 32-bit powershell.

/dupe #4660, #4259, others
