### ISSUE TITLE
fusermount: mounting over filesystem type 0x01021997 is forbidden

### ISSUE THREAD

**Issue by DevPlus31** [microsoft/WSL#5597]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: 
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
It should be WSL2 
```

# Steps to reproduce

I am trying to compile an OS called https://gitlab.redox-os.org/redox-os/redox/ the compilation is successful but it fails at some last steps 

#  Expected behavior
It should compile and fusermount should work fine.

# Actual behavior

![image](https://user-images.githubusercontent.com/16153522/87673763-f17b3380-c76c-11ea-9558-f30218b039f9.png)

I have some errors 
fusermount: mounting over filesystem type 0x01021997 is forbidden
redoxfs: failed to mount build/filesystem.bin.partial to build/filesystem/: Operation not permitted (os error 1)
redoxfs: not able to mount path build/filesystem.bin.partial
make: *** [mk/filesystem.mk:10: build/filesystem.bin] Error 1

**Comment by therealkenc** [comment]
Try building in /home. `0x01021997` is [`S_MAGIC_V9FS`](https://github.com/coreutils/coreutils/blob/6a3d2883fed853ee01079477020091068074e12d/src/stat.c#L528).

If that doesn't work, this submission would need to be narrowed into some failing command sequence. Something somthing something followed by an strace on the failing fusermount in this case. A link to some external project you is not an actionable repro. We got lucky here because the error in the screencap was instructive.

**Comment by DevPlus31** [comment]
Thanks it works compiled successfully.
One last question off-topic is nested virtualization supported I mean QEMU ?

**Comment by therealkenc** [comment]
There's some chat over in #4193. YRMV.

**Comment by markuszeller** [comment]
Mounting into a directory in `/home` works fine and no need to use `sudo`. To make it available for the Windows host using `\\wsl$\Ubuntu\home\username\mounted_directory` you can pass the option `-o allow_other` to the sshfs command. Also make sure to enable `user_allow_other` in `/etc/fuse.conf`.

**Comment by man8k** [comment]
A simple sshfs mount in WSL2 (Windows Built 19042) keeps producing the same error whenever the mountpoint is outside the WSL2 Ubuntu home directory. As long as the mountpoint is inside the home directory, everything works fine (along @therealkenc's  recommendation above).

For transferring larger amounts of data to a remote VM, this narrow functionality within WSL2 appears infeasible.

Therefore, I'd like to ask:
- is there a way to choose the mountpoint outside home in this Windows Built (19042) ?
  (when using SFTP in WSL2, all other directories outside home are accessible as well and isn't SFTP the grounds for sshfs?) 
- if not, would there be a minimum Windows Built that has possibly solved the issue ?
  (https://docs.microsoft.com/en-us/windows/wsl/release-notes do not seem to be explicit in this regard)

**Comment by agotad** [comment]
Hello there, so what's the solution to this problem? Or is it impossible to use sshfs in wsl in windows?

**Comment by cjarv** [comment]
this issue still persists and should not be closed

**Comment by madscientist42** [comment]
The issue is likely due to how Microsoft did things within WSL2.  It doesn't allow a handful of things (Like named pipes, as another example...) out of the directory structure exposed via WSL's integration.  It looks like a proper POSIX filesystem...acts...MOSTLY...like one- but it's very much a twisted implementation if it can't do these things- and you're not fixing it either.

**Comment by madscientist42** [comment]
And, no, you can't use the posixovl FUSE filesystem as a solution- it's why I came looking for answers...  I tried it.  And then I did some digging.

Those that find this need to understand that while it's pretty impressive, WSL2 has...issues...typical of each and every Microsoft "solution".

If I wasn't being **_forced_** to use their junk by a client...I wouldn't.  (And YES, Microsoft, I did say that in your project...you **_CAN_** try harder and do better.  It's a swing and a miss in many ways that may well force me to use VirtualBox for what I need to do for the client.  Thanks for NOTHING...again.)
