### ISSUE TITLE
Cannot run Eclipse IDE 2020 after installing WSL 2

### ISSUE THREAD

**Issue by drejmar** [microsoft/WSL#5599]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Ubuntu 20.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
WSL 2
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Restart Windows (in my case they were restarted by Windows Update).
Open Eclipse IDE 2020.

#  Expected behavior
Eclipse IDE opens normally

# Actual behavior
Eclipse IDE is stuck in the middle of startup

I found the problem in Task Manager. Starting Eclipse process also starts WSL 2 processes under Eclipse, then it gets stuck.

Workaround 1:
Call this in PowerShell:
wsl --shutdown
Eclipse startup will continue

Workaround 2:
Open Ubuntu 20.04 LTS before starting Eclipse.
This way WSL 2 processes will run under Ubuntu 20.04 LTS instead of Eclipse

**Comment by therealkenc** [comment]
Why eclipse gets stuck is not WSL actionable.

**Comment by drejmar** [comment]
@therealkenc
I was surprised to learn that it is not caused by WSL. Your answer is correct.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=565285
