### ISSUE TITLE
bash will not install

### ISSUE THREAD

**Issue by GamerProYT54** [microsoft/WSL#5601]
When i start bash for the first time, nothing happens, and nothing installs.

**Comment by therealkenc** [comment]
Please resubmit following the [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md) in particular [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
