### ISSUE TITLE
<unistd.h> sleep() does not sleep

### ISSUE THREAD

**Issue by hunter-negron** [microsoft/WSL#5603]
I'm not sure if this has been mentioned yet, but I can't find anything online about it.

The sleep function, instead of sleeping for the appropriate amount of time, returns immediately. I even tested for a negative return value and checked the errno, but that yielded nothing.

Here is the code that recreates the problem:
    `#include <stdio.h>`
    `#include <unistd.h>`
   ` int main() {`
        `printf("sleep for 10 seconds\n");`
        `sleep(10);`
        `return 0;`
    `}`

And compiled as
`gcc -o sleeptest sleeptest.c`

My Windows build number is  10.0.18363.900

**Comment by therealkenc** [comment]
Preemptively call this /dupe #4898 for lack of [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md) and `strace(1)` log.
