### ISSUE TITLE
Can't communicate with the Internet when using a cellular network(WWAN).

### ISSUE THREAD

**Issue by mayuki** [microsoft/WSL#5613]
# Environment

```none
Windows build number: 10.0.20170.1000
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

- Disconnect from Wi-Fi
- Connect to cellular network (WWAN)
- Launch WSL 2
- Communicate something over the Internet (curl, wget, npm, ...)

#  Expected behavior

The Linux processes should be able to communicate with the Internet without problems.

# Actual behavior

Can't communicate to the internet from WSL2 when using a cellular network (WWAN).

I'm having the problem with the Surface Pro X's LTE communication (Wi-Fi is already disconnected).

For example, the curl command gives me the following error.

 ````
$ ping www.example.com
PING www.example.com (93.184.216.34) 56(84) bytes of data.
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=1 ttl=54 time=278 ms
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=2 ttl=54 time=135 ms
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=3 ttl=54 time=134 ms
^C
--- www.example.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2389ms
rtt min/avg/max/mdev = 133.909/182.238/277.921/67.658 ms

$ curl www.example.com
curl: (7) Failed to connect to www.example.com port 80: Connection timed out
````

However, DNS resolution and pinging responds normally, perhaps because it goes through the host.

**Comment by StaticDefault** [comment]
Me too.. how to solve this problem?

**Comment by yaticl** [comment]
I have the same issue for WSL 2. It is very strange that if I used VPN than it will connect to internet normally even using cellular connection. There is no such problem when using WSL 1.

**Comment by jarvinlpt** [comment]
same issue here. can't use internet on wsl2 while i'm on my mobile data. are there any workaround on this?

**Comment by spindla** [comment]
Have anyone a solution?

**Comment by Macmee** [comment]
me too

**Comment by LucasWilliams** [comment]
I'm having this problem as of Feb. 28, 2021, more than half of a year after this problem was identified. Has there been any progress on resolving this?

**Comment by stupidawesome** [comment]
I also have a Surface Pro X, LTE works if WIFI is connected to anything while selecting "Use mobile instead of wifi: always" in the windows settings. Surely there's a better way.

**Comment by jasonrandrews** [comment]
Would love to figure this out. I can't access internet using WSL2 on Samsung Galaxy Book S with LTE.

**Comment by denysvitali** [comment]
In my case, when using WSL2 + Cellular (Snapdragon X24 LTE), ICMP works fine (gets responses back), DNS resolution works as well, but TCP / UDP packets do not get any reply.

**Comment by tumugin** [comment]
I'm having the same issue on my Surface Pro X(Insider 21364.1011).
On my ThinkPad with cellular modem(Intel CPU with Fibocom modem), it seems to be working so it might be ARM64 Windows issue or Snapdragon's modem driver issue.

**Comment by denysvitali** [comment]
I managed to solve my problem.

## Set a static IP to your vEthernet (WSL) adapter

<p align="center">
<img src="https://user-images.githubusercontent.com/4939519/118259406-66b0b580-b4b1-11eb-9202-350b9abb2e64.png" width="300"/>
</p>

```
Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-AE-82-30
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 172.23.224.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   IPv4 Address. . . . . . . . . . . : 192.168.137.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled
```


## Share your Cellular connection

Right click on the Cellular adapter, select "Properties", select the "Sharing" tab and tick "Allow other network users to connect through this computer's internet connection", then select the vEthernet adapter.

<p align="center">
<img src="https://user-images.githubusercontent.com/4939519/118259820-e5a5ee00-b4b1-11eb-8be5-293313003b37.png" width="300"/>
</p>


## Set a static IP to the VM

```
$ sudo ip addr add 172.23.239.4/20 dev eth0
$ sudo ip route add default via 172.23.224.1
$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=51 time=65.2 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=51 time=63.7 ms
^C
--- 1.1.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 63.748/64.490/65.233/0.742 ms
$ curl -I https://microsoft.com
HTTP/2 301
date: Fri, 14 May 2021 10:45:34 GMT
location: https://www.microsoft.com/
server: Kestrel
```

Enjoy!

**Comment by denysvitali** [comment]
Unfortunately the above mentioned solution doesn't work anymore on Windows 11 because the Hyper-V interface doesn't show up anymore in `Control Panel\Network and Internet\Network Connections`.

The weird part is the following:

### List of Network Adapters
```
PS C:\WINDOWS\system32> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (WSL)           Hyper-V Virtual Ethernet Adapter #2          49 Up           00-15-5D-51-8E-5E        10 Gbps
Bluetooth Network Conn... Bluetooth Device (Personal Area Netw...      20 Disconnected F0-1D-BC-A5-4A-1A         3 Mbps
Wi-Fi                     Qualcomm(R) Wi-Fi B/G/N/AC (2x2) Svc         12 Disconnected F0-1D-BC-A5-4A-19          0 bps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             39 Up           00-15-5D-01-6F-00        10 Gbps
Cellular                  Snapdragon (TM) X24 LTE Modem                 5 Up           00-A0-C6-00-00-00        50 Mbps
```

### Enum every connection with `HNetCfg.HNetShare`

```
PS C:\WINDOWS\system32> regsvr32.exe /s hnetcfg.dll
PS C:\WINDOWS\system32> $netShare = New-Object -ComObject HNetCfg.HNetShare
PS C:\WINDOWS\system32> $netShare.EnumEveryConnection | ForEach-Object { $netShare.NetConnectionProps($_) }


Guid            : {D6AEDC93-A58C-4CAF-A9E1-F8DF6D33935C}
Name            : Bluetooth Network Connection
DeviceName      : Bluetooth Device (Personal Area Network)
Status          : 7
MediaType       : 3
Characteristics : 262153

Guid            : {7E6F048D-BF66-4FC6-B910-18F9B188D90B}
Name            : Wi-Fi
DeviceName      : Qualcomm(R) Wi-Fi B/G/N/AC (2x2) Svc
Status          : 7
MediaType       : 3
Characteristics : 12297

Guid            : {1B64A8CD-C0C6-4D58-8353-32904C7483CF}
Name            : Cellular
DeviceName      : Snapdragon (TM) X24 LTE Modem
Status          : 2
MediaType       : 3
Characteristics : 4361
```

I still don't get why my WSL adapter is not being displayed here...

**Comment by kipters** [comment]
Same issue here (Surface Pro X SQ2 + Win11 20000.65)

**Comment by denysvitali** [comment]
Forgot to mention in my previous post that I eventually fixed my issue with a little bit of Powershell magic. I'll post later my steps.

**Comment by denysvitali** [comment]
I'm not 100% sure this is the solution, but after something like these commands, my "vEthernet (WSL)" started to appear in my "Network Connections" and I was able to share my "Cellular" connection w/ the "vEthernet (WSL)":

```powershell
Set-VMSwitch WSL -AllowManagementOS $False
Set-VMSwitch WSL -AllowManagementOS $True
```

YMMV: I'm not 100% sure this is what solved my issue, but I eventually got my interface in the "Network Connections" list and I was able ([with this procedure](https://github.com/microsoft/WSL/issues/5613#issuecomment-841167264)) to use my Cellular interface with Windows 11 and WSL 2 too.

**Comment by sparkleholic** [comment]
I'm facing a same problem.
Is there any other solutions for this?

**Comment by Macmee** [comment]
> I'm facing a same problem on cellular. (No problems on wireless connection.)
> Is there any other solutions for this?

I tried the above solution and couldn’t get it to work, but the one thing that does work for me is connecting to a VPN. On my Surface Pro X I use viscosity for a vpn client because it’s a native ARM application. Certain phone carriers like sprint block VPNs for their tablet plans, but I’ve discovered Verizon’s prepaid plans do not.

**Comment by imprisoner** [comment]
VPN did the trick for me too

**Comment by kvnp** [comment]
Add the following to your `.wslconfig' file if you are running Windows 11 Insider
```
[experimental]
networkingMode=mirrored
```
This will expose all network adapters to WSL

**Comment by muness** [comment]
Thanks, that worked for me. More details at [Advanced settings configuration in WSL
](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings).

**Comment by danielprettcampagna-ipiranga** [comment]
> Add the following to your `.wslconfig` file if you are running Windows 11 Insider
> 
> ```
> [experimental]
> networkingMode=mirrored
> ```
> 
> This will expose all network adapters to WSL.
> 
> https://learn.microsoft.com/en-us/windows/wsl/wsl-config

That worked for me!!
