### ISSUE TITLE
Files are not always written to mounted storages

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/WSL#5614]
# Environment

```none
Windows build number: 19041
Your Distribution version: Ubuntu 18.04
WSL version: 1
```

# Steps to reproduce

Write a file to an external storage device.

#  Expected behavior

Files written to external storage devices should not be put in the internal storage.

# Actual behavior

When a removable storage device is auto-mounted by WSL in `/mnt` (e.g. `/mnt/d`), writing to this drive may not actually write to it but to a temporary directory instead. When the device is removed and connected to another computer, changes are gone.

By going to WSL's folder (e.g. `%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs`) we can see the writed files (e.g. `%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\mnt\d\folder\some-written-file`).

This does not happen all the time, but randomly. Also it never happens with `/mnt/c`.

The only solution I've found until now is to force re-mounting the device through a `remount` function:

```bash
remount () {
        sudo umount /mnt/${1:l} 2> /dev/null
        sudo mkdir /mnt/${1:l} 2> /dev/null
        sudo mount -t drvfs "${1:u}:" /mnt/${1:l}
}

remount d # or whatever drive we want
```

I'll try to see if this happens on WSL 2, but this will be harder to debug as the files are stored inside a virtual storage file.

**Comment by DHowett** [comment]
If you can find the written files _inside the WSL root directory_, the drive was never mounted. WSL will not mount removable storage attached during a running session; you must do that yourself.

**Comment by ClementNerma** [comment]
The problem is that the drives _are_ mounted as I can read any file that is on these drives. I have an external hard drive of 5 TB and I can read any file from it without any problem, including ones taht are far larger than my internal drive ; but sometimes when I write to it the files go to WSL's `/mnt/d` directory instead of going to the external drive itselF.

**Comment by ClementNerma** [comment]
The problem is that the drives are mounted as I can read any file that is on these drives. I have an external hard drive of 5 TB and I can read any file from it without any problem, including ones taht are far larger than my internal drive ; but sometimes when I write to it the files go to WSL's /mnt/d directory instead of going to the external drive itself.
