### ISSUE TITLE
wsl 2 high input latency

### ISSUE THREAD

**Issue by rekaerst** [microsoft/WSL#5616]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: Release: Ubuntu  20.04
The issue is on WSL 2
```

# Steps to reproduce
Open terminal  and start typing

# Actual behavior
1.The input latency is notability higher than WSL version 1 and native Windows shells.
2.When typing long commands the input latency increases.
tested in various shells (bash, zsh, fish, csh) and terminal emulators

**Comment by onomatopellan** [comment]
Did you try Windows Terminal? It should have better input latency than the default terminal.
Also any shell that tries to access /mnt/ folders will be slow in WSL2.
Try creating an `/etc/wsl.conf` file with this content
```
[interop]
appendWindowsPath=false
```
and run `wsl.exe --shutdown`. Next time you open a terminal you should notice the difference.

**Comment by rekaerst** [comment]
Yes, but Windows Terminal does not help. I think it's not related to terminal emulator. Tried wsl.conf and it doesn't work.

**Comment by onomatopellan** [comment]
Can you install a WSL1 distro (or install a new WSL2 distro and convert it to WSL1)? If you still see the high input latency when opening a WSL1 terminal then the reason of the latency is more than just running WSL1 or WSL2.

**Comment by rekaerst** [comment]
I installed both WSL1 and WSL2 version of Ubuntu and input latency in WSL1 is normal. I've tried a variety of distros on different computers and got same high latency problem in WSL2

**Comment by rekaerst** [comment]
And the strange thing is that there's no latency in ssh session to WSL2. So i think this may be a problem related to how does WSL2 communicate with console host

**Comment by onomatopellan** [comment]
I suspect in some scenarios enabling WSL2 can add some input latency due to [Windows booting under Hyper-V](https://www.pugetsystems.com/labs/hpc/Does-Enabling-WSL2-Affect-Performance-of-Windows-10-Applications-1832/).
Any info on your configuration?  What keyboard are you using?

**Comment by therealkenc** [comment]
> add some input latency due to Windows booting under Hyper-V.

Not enough to notice or the shrieking would be deafening. No guesses on the externality though.

**Comment by rekaerst** [comment]
I'm using my laptop's built-in keyboard and I didn't configure much things. It's default settings from WSL2.
ssh from the same PC

**Comment by onomatopellan** [comment]
Are you using cmd.exe for the SSH session? Then this issue should also be posted in https://github.com/microsoft/terminal/issues

**Comment by rekaerst** [comment]
![out5](https://user-images.githubusercontent.com/52642831/91038615-a68eee80-e63d-11ea-831e-eaeaed118bc8.gif)
I think this should be a problem related to how does Window communicate with WSL2 tty

**Comment by therealkenc** [comment]
> I think this should be a problem related to how does Window communicate with WSL2 hypervisor's tty

To [repeat](https://github.com/microsoft/WSL/issues/5616#issuecomment-661247537): If that were the simple explanation, with probably tens of thousands of WSL2 users out there or more*, your issue would be the most popular on this github. There was never any question that you are experiencing unusual latency. Can't speculate on your externality, but you've got them in spades with that screencap.

Do `wsl.exe --set-default-version 2`, install a new Ubuntu-18.04 from the [Store](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q?activetab=pivot:overviewtab) (version chosen just so it doesn't collide with your 20.04), start it with `wsl.exe -d Ubuntu-18.04`, and don't install anything. If your latency persists that would be a useful datapoint.

(*made up number)

**Comment by rekaerst** [comment]
sorry for bothering, after an update of wslhost and conhost the input latency highly reduced. closing
