### ISSUE TITLE
There is a problem with Docker installing Redis remote connection in WSL2

### ISSUE THREAD

**Issue by Koorye** [microsoft/WSL#5618]
I tried the following command on aliyun server and WSL2:
    docker run --name redis -dit -p 6379:6379 redis

Then I tried to connect to Redis using Jedis, the Aliyun server received pong normally, but WSL2 reported an error that 'redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host 127.0.0.1:6379'.

However, in addition to Redis connection failure, MySQL, MongoDB, etc. can connect normally. So I don't think it's Docker or Redis itself.

**Comment by onomatopellan** [comment]
Try with 
`docker run --name redis -dit -p 0.0.0.0:6379:6379 redis`

**Comment by JULYRAINING** [comment]
> Try with
> `docker run --name redis -dit -p 0.0.0.0:6379:6379 redis`

same error

**Comment by Altair2169** [comment]
> Try with `docker run --name redis -dit -p 0.0.0.0:6379:6379 redis`

can you explain how this worked?

**Comment by onomatopellan** [comment]
@Altair2169 It's explained here: https://docs.microsoft.com/en-us/windows/wsl/networking#connecting-via-remote-ip-addresses

**Comment by deadcoder0904** [comment]
@onomatopellan even `0.0.0.0` isn't working. i have to use my ip. [this is exactly the problem i'm facing](https://stackoverflow.com/q/69447386/6141587) & [this is my solution to it](https://stackoverflow.com/a/78100745/6141587) although i would like `localhost` or `0.0.0.0` to work for consistency.
