### ISSUE TITLE
htop reports incorrect values on WSL 2

### ISSUE THREAD

**Issue by peanutfun** [microsoft/WSL#5620]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: Debian       Release:        stable-updates
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

1. Have Debian distro and WSL 1. `htop` works correctly.
1. [Update to WSL 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2).
2. Update `Debian` distribution to WSL 2:

    ```bash
    wsl --set-version Debian 2
    ```
3. Open Debian distro.
4. Run `htop`.
5. Compare `htop` output with Task Manager:

![Annotation 2020-07-20 180056](https://user-images.githubusercontent.com/34276446/87959439-2eb82c00-cab3-11ea-934d-fd48056afff2.png)

![Annotation 2020-07-20 180057](https://user-images.githubusercontent.com/34276446/87959565-64f5ab80-cab3-11ea-85c2-392bea73201e.png)

![Annotation 2020-07-20 180058](https://user-images.githubusercontent.com/34276446/87959458-3677d080-cab3-11ea-956e-a88a14e2103c.png)

#  Expected behavior

`htop` displays numbers similar to the ones reported by Task Manager.

# Actual behavior

* `htop` only displays RAM and CPU usage of Linux subsystem (?), rendering it useless.
* `htop` shows wrong amount of total system RAM (12.4 GB vs actual 16 GB).

**Comment by therealkenc** [comment]
WSL2 limits the amount of RAM it consumes and reports that value by design. Cannot repro the CPU usage part. If you've got really low CPU usage (0.2%) on `vmmem` that wouldn't be _too_ surprising since the virtual CPU resources consumed inside the VM isn't necessarily the same as the hypervisor itself is consuming in Windows. There are two problems reported here; if the CPU is _really_ off under load that could be filed under a different (new) cover.

![image](https://user-images.githubusercontent.com/7049700/87968544-71f3aa00-ca75-11ea-9133-19bc7c0398f9.png)

**Comment by muhammadabdulrahim** [comment]
I don't know why this is marked as complete. I am encountering the same issue. I want a configuration for `htop` that matches what's happening on Windows and not just within the VM. Behavior was what I expected in WSL 1, but it changed in WSL 2.

**Comment by MakaEdgar** [comment]
Agree with the previous comment, I still have the same issue on WSL2.

**Comment by ismailhaddouche** [comment]
What windows show is the default memory reserved for Wsl and is by default 2Gb you can change it on Wsl settings.
No relation between what is running inside the virtual machine that count only the running processes and the host that count the hole processe of virtualitation (hyperV, reserved memory...)
Remember WSL is a virtual machine not a container. A great virtual machine, but still a virtual machine.
