### ISSUE TITLE
[WSL2] Requests to PHP Docker containers are incredibly slow

### ISSUE THREAD

**Issue by DarkGhostHunter** [microsoft/WSL#5622]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 20.04 || Alpine 3.11.3 WSL 
Whether the issue is on WSL 2 and/or WSL 1: 
  WSL2
  Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

1. Create a new project using Laravel. You will need PHP but after that you can do this:

    composer global require laravel/installer
    laravel new blog

2. Run the built-in PHP Server:

   docker run -t -p 8080:8080 -v C:\User\MyUser\Projects\blog\:/opt/project php:cli-alpine -S 0.0.0.0:8080 -t /opt/project/public /opt/project/server.php

3. Open a browser and go to `http://localhost:8080`.
4. Watch it go so slow.

* strace on Alpine WSL2: https://gist.github.com/DarkGhostHunter/0ee2dddb44cbac4e47884ec10a1e806a
* strace on Ubuntu WSL2: https://gist.github.com/DarkGhostHunter/e64262aa32a7b277ee497dd7bfa9975c

> strace was made on the container, not the WLS itself.

I'm currently testing other machines for similar performance degradation compared to, welp, just use PHP binaries.

#  Expected behavior

GO FAST.

# Actual behavior

GO SLOW. Similar requests using Windows binaries take like 70% less time and these offer a free late with your purchase.

**Comment by DarkGhostHunter** [comment]
Successfully reproduced on second machine. It's slow.

My suspicion points me that mounting the files from Windows into WSL into Docker is what makes it slow.

**Comment by therealkenc** [comment]
> C:\User\MyUser\Projects\blog

/dupe #4197
