### ISSUE TITLE
FUSE for WSL2 not working

### ISSUE THREAD

**Issue by isVoid** [microsoft/WSL#5629]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Ubuntu Release:        18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

```
sudo modprobe fuse
```

#  Expected behavior

Fuse successfully loaded.

# Actual behavior

```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.104-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.19.104-microsoft-standard
```

**Comment by 0xbadfca11** [comment]
All of enabled kernel features are compiled as built-in.
No needs modprobe all time.

**Comment by isVoid** [comment]
> All of enabled kernel features are compiled as built-in.
> No needs modprobe all time.

That's correct. FUSE is working without the need of modprobe.
