### ISSUE TITLE
cmd cannot remove the directory that WSL made

### ISSUE THREAD

**Issue by MarchSakura** [microsoft/WSL#5632]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Ubuntu Release:        18.04

Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

In mounted file path of windows (*such as /mnt/c/Users/test/Documents/testDir*) , run ```mkdir ...``` in WSL, and the a new directory named ```...``` was created.

Using right click + delete can delete ```...``` or ```testDir``` failed to delete both the directories.

Using ``` rd /s ...``` in cmd, terminal showed *The process cannot access the file because it is being used by another process*.

Then I killed wslhost.exe process, run ``` rd /s ...``` in cmd again, terminal showed *Cannot Remove folder because the directory is not empty.*

#  Expected behavior

Delete directory ```...``` in windows or cannot create the directory of illegal name in mounted window drives by WSL.

# Actual behavior

Cannot delete the directory ```...``` and the directory which contains ```...``` in windows.

**Comment by therealkenc** [comment]
> Cannot Remove folder because the directory is not empty.

This is by-design Windows. Those `...` dots in your repro are being interpreted by `cmd.exe` as `..\.` (pretty sure). If you want to delete that file from the windows side, you want `rd \\?\C:\Users\there\tmp\...`. Which isn't in any way recomended, but that's how you'd remove it if one insisted. Goes without saying the sane way to delete the quirky directory you created on the WSL side would be from the WSL side. You'll need to make sure there aren't any open handles to the directory (note the `cd /` below) but that's Windows behavior also, or #1529 ([message](https://github.com/microsoft/WSL/issues/1529#issuecomment-505518153)) depending on one's disposition.

![image](https://user-images.githubusercontent.com/7049700/88189962-8909d780-cbee-11ea-9fcc-aeb6e7e4c459.png)

**Comment by MarchSakura** [comment]
@therealkenc 
For the *The process cannot access the file because it is being used by another process*, I exit from wsl in the directory where creating the directory which is the parent directory of ```...```. According to the [#1529](https://github.com/microsoft/WSL/issues/1529), the file descriptors are cached. But I reboot my computer, the delete operation still results in *The process cannot access the file because it is being used by another process*. 
It is by-design that stores the all *state* of WSL when the WINS computer shutdowns?

**Comment by therealkenc** [comment]
Disregard #1529, I only brought it up out of an abundance of caution. Forget I mentioned it. You are not getting `The process cannot access the file because it is being used by another process` because of #1529. The problem is your `rd file` syntax in Windows.

**Comment by MarchSakura** [comment]
@therealkenc 
Thanks! Using ```\\?\```prefix to prevent windows converting the path name to an NT-style name works.
