### ISSUE TITLE
can't connect to kali servers after updating wsl to v2

### ISSUE THREAD

**Issue by Fighteros** [microsoft/WSL#5634]
Microsoft Windows [Version 10.0.19041.388]

i installed kali linux on WSL version 1 it was working and every thing was so good
i then updated my WSL to version 2
and used this command to change the kali to be working on WSL 2 
wsl --set-version kali-linux 2 
and then it went successfully i tried to do sudo apt-get update 
and oops timeout 
i check internet nothing is working though my windows is connected correctly i hope u help me please

**Comment by therealkenc** [comment]
Call this /dupe #4183 which is close enough for a still-open landing zone. Tangentially similar #4223 #4171, others.

**Comment by Fighteros** [comment]
i tried all the solutions mentioned and nothing fixed my problem 
i can ping any ip any website 
![image](https://user-images.githubusercontent.com/59248007/88916160-df69bc80-d265-11ea-9ed0-3ef8076253b1.png)

**Comment by Fighteros** [comment]
![image](https://user-images.githubusercontent.com/59248007/88916283-19d35980-d266-11ea-8a61-73541a0d8d02.png)
![image](https://user-images.githubusercontent.com/59248007/88916307-25268500-d266-11ea-997b-cb2e2d20033b.png)
![image](https://user-images.githubusercontent.com/59248007/88916352-353e6480-d266-11ea-9368-f2435e99a002.png)

**Comment by Fighteros** [comment]
i tried all the solutions and nothing fixed my problem 
i can do ping for any ip and any website 
and nslookup also 
but can't do apt uipdate 
or curl or wget 
![image](https://user-images.githubusercontent.com/59248007/88918867-82243a00-d26a-11ea-9f10-38d47d1027b8.png)

**Comment by Fighteros** [comment]
this took me days searching trying installing and reinstalling i could finally fix this by using these commands in power shell 
`wsl --shutdown
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns`
and rebobted then went to avast firewall allow all inboud and outbound connection and it worked for me

**Comment by starling-21** [comment]
> this took me days searching trying installing and reinstalling i could finally fix this by using these commands in power shell
> `wsl --shutdown netsh winsock reset netsh int ip reset all netsh winhttp reset proxy ipconfig /flushdns`
> and rebobted then went to avast firewall allow all inboud and outbound connection and it worked for me

Thank. It worked for me too.
I had similar issue when tried to run `docker pull <some image>`, `docker login` or `docker-compose up`. I've been got timeout everytime I run any of those command. Nslookup, ping and curl were working with no issues.

**Comment by psytran** [comment]
┌──(pnvs㉿LAPTOP-0TJ1JHA7)-[~]
└─$ sudo apt update
[sudo] password for pnvs:
Ign:1 http://http.kali.org/kali kali-last-snapshot InRelease
Ign:1 http://http.kali.org/kali kali-last-snapshot InRelease
Ign:1 http://http.kali.org/kali kali-last-snapshot InRelease
Err:1 http://http.kali.org/kali kali-last-snapshot InRelease
  Temporary failure resolving 'http.kali.org'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://http.kali.org/kali/dists/kali-last-snapshot/InRelease  Temporary failure resolving 'http.kali.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
