### ISSUE TITLE
Vulkan in WSL2

### ISSUE THREAD

**Issue by mortim1** [microsoft/WSL#5636]
Is it possible to launch vulkan-based program in WSL2 with X Server ?

**Comment by therealkenc** [comment]
This is a good question for reddit or twitter. Somewhat similar [this](https://www.reddit.com/r/vulkan/comments/f8ch5v/how_i_can_run_vulkan_using_software_rendering_on/). Shorter answer: no. One day maybe tho.

**Comment by mortim1** [comment]
Okay thanks.

**Comment by GeorgeS2019** [comment]
[WSL2 and Vulkan using llvmpipe](https://github.com/microsoft/WSL/issues/7790#issuecomment-1086890736)
