### ISSUE TITLE
Update WSL1 to WSL 2 problem

### ISSUE THREAD

**Issue by ulziibat-n** [microsoft/WSL#5637]
Hi All!
Today i updated Windows 10, then try to update WSL
but can't get success. I've attached screenshot. 
What i should do? Please help me.

![image](https://user-images.githubusercontent.com/42606441/88211832-d63a8780-cc88-11ea-8e55-96d5f23a6321.png)

Error message is ```For information on key differences with WSL 2 please visit https://aka.ms/wsl2```

**Comment by therealkenc** [comment]
The `wsl --set-default-version` command does not upgrade anything, it just sets the default for new installs and subsequent `wsl --imports`. Also looks like you are calling `wsl.exe` from inside WSL, which is not what you want. Call `wsl.exe` from a command prompt (cmd.exe) or powershell. Docs [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2). TL;DR:

```
C:\> wsl.exe --set-version <distro> 2
```
... where `<distro>` is your distribution name returned by `wsl.exe -l`. Often `Ubuntu-18.04` if that's what you installed from the store.
```
