### ISSUE TITLE
The I/O operation has been aborted because of either a thread exit or an application request

### ISSUE THREAD

**Issue by yrest** [microsoft/WSL#5640]
# Environment

Windows build number: 10.0.20175.0
Your Distribution version: Ubuntu
Whether the issue is on WSL 2 and/or WSL 1: global

https://aka.ms/AA920gy

**Comment by derdimi** [comment]
Hi! I have the same problem on my corporate notebook after it was updated to 20H2 (build 19042.1165). Setting to empty PATH in cmd works okay as a workaround. How do I know which version has a proper fix included? The only reference I've found was in [Windows 10 Insider Preview Build 20190](https://blogs.windows.com/windows-insider/2020/08/12/announcing-windows-10-insider-preview-build-20190), referenced in #5633
