### ISSUE TITLE
service not started message box

### ISSUE THREAD

**Issue by btreut** [microsoft/WSL#5641]
# Environment
Microsoft Windows [Version 10.0.17763.1282]
due to restrictions in our environment, after having tried to install WSL and a distribution, I tried now to follow the commandline instructions given here: [Manual Installation](https://docs.microsoft.com/de-de/windows/wsl/install-manual#installing-your-distro )
# Steps to reproduce
1. Enabled the WSL feature in PowerShell and rebooted previously (as a user with administrative rights but not the full Administrator). I have now redone this step and it looks like this:

> PS C:\windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> 
> Path          :
> Online        : True
> RestartNeeded : False
> 
> 
> 

since it says: `RestartNeeded : False` I did not reboot again.

2. Downloaded DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx, unpacked it and run debian.exe from the
unpacked directory (still with the user with administrative rights), it worked and I was able to create a new user and now I am able to call debian.exe by specifying the full path of the debian.exe file or by calling wsl from anywhere as this user, but I cannot start it as normal user.
I had previously tried to install it via add-appxpackage and I have a menu entry "Debian", but when I try to start that I get a message box saying that some service is not started:
![Error](https://user-images.githubusercontent.com/8996291/88275223-4f63ca00-ccdd-11ea-95bf-2dd729a6b618.jpg)

#  Expected behavior
I would like to be able to start the debian prompt as normal user from anywhere in the filesystem.

# Actual behavior
I can start the debian prompt only as administrative user by calling wsl.exe

When I try to start wsl as normal user, I still get 
>H:\>wsl
>Für das Windows-Subsystem für Linux wurden keine Distributionen installiert.
> Distributionen zur Installation finden Sie im Microsoft Store:
> https://aka.ms/wslstore

**Comment by therealkenc** [comment]
> since it says: RestartNeeded : False I did not reboot again.

You needed to restart at that point. Relatively safe to assume you've restarted since though, since you did manage to install the distro.

>  from the unpacked directory (still with the user with administrative rights)

Install your distro as a normal user. [Similar to but different than #5428, others.]

> Microsoft Windows [Version 10.0.17763.1282]

Also advisable to sync up to 19041.

**Comment by btreut** [comment]
> Install your distro as a normal user. [Similar to but different than #5428, others.]
> 
 I managed to install & initialize Debian as normal user, but I cannot see/access network drives in linux and I still get that awfull message box (see above) when trying to start Debian from the start menu. When starting Linux from the Shift-Right klick menu in Windows Eplorer on a network drive, I end up in my home directory.

**Comment by btreut** [comment]
I have no idea what information I should prevode for a repro, please advise.

**Comment by therealkenc** [comment]
There isn't an expectation you'll be able to provide additional information. It is more likely it will remain unknown the steps taken to get your system in the current state. Hence the tag. Your constructive path forward would be to sync up to 19041, which will reinstall enough moving parts that there is at least some chance enough of your machine will be reconstituted into operable condition.

**Comment by btreut** [comment]
> sync up to 19041,

hmm, I don't have any chance to influence the sync up, this will be provided by our global administrators. The last update was yesterday, but it was only up to `Microsoft Windows [Version 10.0.17763.1339]`. 
Just to summarize my restrictions: I do not have access to MS-App store. I have to download manually and on the command line. Our environment forces a huge amount of group policies upon us and has an active applocker.

**Comment by therealkenc** [comment]
It is possible WSL is being thwarted by some admin policy. They way to test that hypothesis would be to try WSL on another machine in your organization with the same admin policies. Be careful to do the `Enable-WindowsOptionalFeature` as Administrator, rebooting, and the rest as a normal user. If it fails similarly on the other locked down machine, there isn't much you can do except ask your IT-Service Dpt. If it does work, it is an exercise in finding out what is special about your machine.

You can try, on a lark, as Administrator:
```
C:\> sc stop LxssManager
[it might not be started]
C:\> sc start LxssManager
```

Doing a "restart LxssManager" has cured some ills in the past. After the `start`, pause for half a minute before starting WSL in another console as a normal user. The chances of this working are "low" but it is worth the shot.

**Comment by btreut** [comment]
> try WSL on another machine in your organization with the same admin policies

there is one other (physical) machine with which I could try it, but that has to wait until I am back from home-office at my "normal" workplace.

When I try to call `sc stop LxssManager` from a cmd running with local admin rights I see  shortly a  black windowpopping up, but I don't have any chance to read any message. Trying it from Power Shell (with admin rights) passes silently without any feedback. The same happens for `sc start`. But the error message persists.
