### ISSUE TITLE
WSL Kernel update requires a CD-ROM?

### ISSUE THREAD

**Issue by AnselmJeong** [microsoft/WSL#5642]
**Sorry for raising an issue in unstructured format.....**

I'm on Windows Insider Program with Dev Channel

Weeks ago I started receiving weird update error. This relates to kernel update for windows subsystem for Linux to version 4.19.121.1 (my current version is 4.19.121)

![image](https://user-images.githubusercontent.com/1776524/88285022-63351d80-cd29-11ea-9a3e-e4a13206a29b.png)

I've tried multiple times, but did not succeed with the same error message.

I've tried to manually update wsl2 kernel by issuing `wsl --update` in a command line.

It then tries to download updates ...

![image](https://user-images.githubusercontent.com/1776524/88286009-0c304800-cd2b-11ea-8eda-cd5affe2ba37.png)

and finally display the following message box.

![image](https://user-images.githubusercontent.com/1776524/88285300-cfb01c80-cd29-11ea-9815-cd3c96cdb334.png)

I've entered `wsl_update_x64.msi` in the Use source input box. Then this message pop up.

![image](https://user-images.githubusercontent.com/1776524/88285397-f5d5bc80-cd29-11ea-9134-58fe716f535c.png)

I have no idea how to interpret the above instruction....

I've tried googling extensively, but could not find any mention about this phenomenon.

Thanks.....

**Comment by therealkenc** [comment]
> Sorry for raising an issue in unstructured format.....

Thanks for the detail screencaps they are helpful. What is your Windows build? Output of `ver` at the `cmd.exe` prompt.

No idea how you got in this state (and we'll both probably never know). That message box is pretty novel... hasn't come up before in this github AFAIK. You didn't get any google hits because you're the first.

Taking that prompt at its word, try putting the `wsl_update_x64.msi` in `C:\Users\you\somewhere` and the browse there for the "Use source". I don't actually think that will work but it is worth the try.

**Comment by licanhua** [comment]
@bpulliam It's possible a bug when doing minor update from 4.19.121 to 4.19.121.1

As I know, 4.19.121.1 is nearly the same as 4.19.121, and it's used to fix a vs code bug. User is safe to stay with 4.19.121 and wait for the next update.

**Comment by AnselmJeong** [comment]
Thanks for the reply... But recommendation of @therealkenc did not work.  I'll just wait for another round of update.

**Comment by therealkenc** [comment]
@AnselmJeong We're still lacking your Windows build. Output of `ver` at the `cmd.exe` prompt.

**Comment by AnselmJeong** [comment]
Sorry for being late

the output of `ver` is

Microsoft Windows [Version 10.0.20175.1000]

**Comment by AnselmJeong** [comment]
Microsoft recently rolled out kernel update version 4.19.128.

However, the `wsl --update` still refuses to proceed with exactly the same error as the above report. 
It still searches for the mysterious CD-ROM. (**Windows Subsystem for Linux Update disk**)

I have even turned off WSL and started from scratch with `wsl --install`. 
This procedure installed kernel version 4.19.121 and the update was unsuccessful.

Do I have to format the hard disk and try to reinstall Windows 10 ??

Any idea???

**Comment by AnselmJeong** [comment]
Windows version is 10.0.20197.1000

**Comment by therealkenc** [comment]
Was afraid of that. Thanks for the update. Please collect [wsl logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and backlink the feedback item. If you can capture that "Fatal error during installation" when running `wsl.exe --update` maybe it will show something in the traces. Your submission has an unfortunate absence of me2s, which makes this a difficult one.

**Comment by licanhua** [comment]
@AnselmJeong What's your display language and system locale? Are you using English version of OS?
Since you are working on insider, you can uninstall the kernel from 'Add or remove programs', then run `wsl --install` with admin, that should download and install kernel for you.

**Comment by mattmazer0397** [comment]
I'm on a newer windows build and I'm still having this issue. I use Pengwin, if it makes a difference

**Comment by yyuueexxiinngg** [comment]
Running into the same issue, Windows Update in the settings failed, same as this Issue here: https://github.com/microsoft/WSL2-Linux-Kernel/issues/127

Was trying to follow the uninstall instructions people posted in there and run into the this Issue.

Windows version `10.0.20201.1000`, Current WSL kernel version: `4.19.121.1`

Tried right click and select uninstall on the `wsl_update_x64.msi`, but it shows `This action is only valid for products that are currently installed`

Tried to disable the WSL feature, but the `Windows Subsystem for Linux Update` still remains in `Programs and Features`

**Comment by rybak** [comment]
Same issue for me. `ver` output:
```
Microsoft Windows [Version 10.0.19041.508]
```

**Comment by axd465** [comment]
I am having this exact same issue. Seems to be connected to Windows Insider Builds. My Windows version output is ```Microsoft Windows [Version 10.0.20215.1000]```. My WSL kernel version is  ```4.19.128-microsoft-standard``` (output of ```uname -r``` in the wsl shell), but I am still being notified that I need to update. I am getting the same errors described by @AnselmJeong. My system locale and language are all standard for the US I imagine. I cannot reinstall or uninstall either, as the same popup described by @AnselmJeong appears then. When you browse to find the downloaded MSI, you get this error

![wsl_msi_update_err](https://user-images.githubusercontent.com/25011252/93505592-131da600-f8e9-11ea-87e6-c38bcbd8fe43.PNG)

The Windows Update troubleshooter does nothing and I have attempted the steps described to fix the associated error code (as seen in the attached image) to no avail. 

![win_update_err](https://user-images.githubusercontent.com/25011252/93505307-af937880-f8e8-11ea-845b-6d3fde6797d5.PNG)

**Comment by Biswa96** [comment]
You could download the Linux kernel update package from Microsoft Update Catalog. See this search link here https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

**Comment by axd465** [comment]
> You could download the Linux kernel update package from Microsoft Update Catalog. See this search link here https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

After using the installer from this link, the same error popup occurs (see below). 

![msi_installer_error](https://user-images.githubusercontent.com/25011252/93513116-5b41c600-f8f3-11ea-9c20-5606c4b72c12.PNG)

**Comment by Biswa96** [comment]
Then you could do it in **dangerous** way. Follow these steps:

1. Go to this website https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
2. Click on the Linux kernel version you want. 
3. There will be a popup window. Select the package as per your CPU architecture (mostly x64 one).
4. It will be downloaded as CAB file. Open it. Extract the MSI file. Install the MSI file.
5. If the MSI file can not be installed extract the kernel from the MSI file using this command: `msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\destination"`. More info from this party https://github.com/microsoft/WSL/issues/5014.

**Comment by bpulliam** [comment]
If you currently have 4.19.128 as your kernel (as shown in uname -a), you are up-to-date as that is the latest kernel we have released.  There was an issue that Microsoft Update was trying to install an older version on top of a newer one, but that issue was recently fixed on the back end to stop offering the older version.

**Comment by bpulliam** [comment]
If you have an older version and are unable to update to 4.19.128, you can uninstall the currently installed version using msiexec, and then install the latest package.
•	Use the command ‘msiexec /x {Product Code}’
•	The product codes for previously released versions are
4.19.84                    28062DDD-5FAE-4A5A-8D36-86ECB8E48096
4.19.104                  9F858BB9-156F-4C4C-9295-0A06CA83D17C
4.19.121                  3AB71F5D-0FB9-4C33-9CFC-29DB37B1F222
4.19.121.1              93E5F4A6-8337-49F7-9BBC-94A82A5C2F80

For example, to uninstall 4.19.121, the command is ‘msiexec /x {3AB71F5D-0FB9-4C33-9CFC-29DB37B1F222}

**Comment by axd465** [comment]
> Then you could do it in **dangerous** way. Follow these steps:
> 
> 1. Go to this website https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> 2. Click on the Linux kernel version you want.
> 3. There will be a popup window. Select the package as per your CPU architecture (mostly x64 one).
> 4. It will be downloaded as CAB file. Open it. Extract the MSI file. Install the MSI file.
> 5. If the MSI file can not be installed extract the kernel from the MSI file using this command: `msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\destination"`. More info from this party #5014.

The reason why my kernel is now "technically" up-to-date at 4.19.128 is because I followed Step 5 of the above procedure. However, it seems that the Windows update installer and wsl --update do not recognize that the kernel is up-to-date. Should I use @bpulliam 's suggestion to uninstall to a later version (like 4.19.121) and then try wsl --update again? Is there something I should edit in the registries?

Either way, thanks for the quick replies 😄

**Comment by bpulliam** [comment]
You should go through the steps to uninstall and update.  Since the kernel is a Linux file, it doesn't have a Windows version number and we have to use the version of the MSI to determine which version you have installed.  It is best if your MSI and your kernel are in-sync to ensure that the update process works as expected.

**Comment by Dave-Lowndes** [comment]
I was in the same situation, and being unable to locate a copy of the original msi for the version I had installed, I eventually downloaded the [MS install/uninstall troubleshooter](https://support.microsoft.com/en-gb/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) - which allowed me to remove the version I was stuck with (despite not having the msi).
Once that was gone I've been able to update to the latest OK.

**Comment by Swift-Lee** [comment]
> I was in the same situation, and being unable to locate a copy of the original msi for the version I had installed, I eventually downloaded the [MS install/uninstall troubleshooter](https://support.microsoft.com/en-gb/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) - which allowed me to remove the version I was stuck with (despite not having the msi).
> Once that was gone I've been able to update to the latest OK.

Thanks, this really worked 👍

**Comment by cpoptic** [comment]
> If you have an older version and are unable to update to 4.19.128, you can uninstall the currently installed version using msiexec, and then install the latest package.
> • Use the command ‘msiexec /x {Product Code}’
> • The product codes for previously released versions are
> 4.19.84 28062DDD-5FAE-4A5A-8D36-86ECB8E48096
> 4.19.104 9F858BB9-156F-4C4C-9295-0A06CA83D17C
> 4.19.121 3AB71F5D-0FB9-4C33-9CFC-29DB37B1F222
> 4.19.121.1 93E5F4A6-8337-49F7-9BBC-94A82A5C2F80
> 
> For example, to uninstall 4.19.121, the command is ‘msiexec /x {3AB71F5D-0FB9-4C33-9CFC-29DB37B1F222}

I had an older wsl version 4.19.121 kernel lingering stubbornly and this fixed it.  Thank you so much!
Specifically I ran `msiexec /x 3AB71F5D-0FB9-4C33-9CFC-29DB37B1F222`

After that, 

`wsl --update`

> Checking for updates...
> Downloading updates...
> Installing updates...
> This change will take effect on the next full restart of WSL. To force a restart, please run 'wsl --shutdown'.
> Kernel version: 5.4.72
> 

and then checking the status of WSL:

`wsl --status`

> Default Distribution: Ubuntu-20.04
> Default Version: 2
> 
> Windows Subsystem for Linux was last updated on 4/30/2021
> WSL automatic updates are on.
> 
> Kernel version: 5.4.72

**Comment by kevincrans** [comment]
I have this error with a WSLg update

**Comment by isaac32767** [comment]
I also have this error updating to WSLg. And WSL2 is complaining about network mount problems when it starts, tho specifics are unclear.

I wonder if this has anything to do with changing \\network\wsl$ to \\network\wsl.local? Seems like an unnecessary tweek. 

Anyway, reverting to Windows 10 no. Hope this gets fixed before W11 update becomes unavoidable.

[    5.537230] 9pnet: Insufficient options for proto=fd
[    5.539012] init: (1) ERROR: UtilCreateProcessAndWait:673: /bin/mount failed with status 0x
[    5.539019] 2000
[    5.539041] init: (1) ERROR: ConfigMountFsTab:2529: Processing fstab with mount -a failed.
[    5.554379] hv_pci cfa05e34-be0e-4a36-9120-5f6cf4b0baa2: PCI VMBus probing: Using version 0x10003
[    5.724838] hv_pci cfa05e34-be0e-4a36-9120-5f6cf4b0baa2: PCI host bridge to bus be0e:00
[    5.724844] pci_bus be0e:00: root bus resource [mem 0xbffe08000-0xbffe0afff window]
[    5.727525] pci be0e:00:00.0: [1af4:1049] type 00 class 0x010000
[    5.729980] pci be0e:00:00.0: reg 0x10: [mem 0xbffe08000-0xbffe08fff 64bit]
[    5.731888] pci be0e:00:00.0: reg 0x18: [mem 0xbffe09000-0xbffe09fff 64bit]
[    5.733642] pci be0e:00:00.0: reg 0x20: [mem 0xbffe0a000-0xbffe0afff 64bit]
[    5.743471] pci be0e:00:00.0: BAR 0: assigned [mem 0xbffe08000-0xbffe08fff 64bit]
[    5.744661] pci be0e:00:00.0: BAR 2: assigned [mem 0xbffe09000-0xbffe09fff 64bit]
[    5.745842] pci be0e:00:00.0: BAR 4: assigned [mem 0xbffe0a000-0xbffe0afff 64bit]

**Comment by hansmuff** [comment]
@ramadhanafif That worked perfectly on Win10 for me as well. Thank you very much!

**Comment by kvnloughead** [comment]
I encountered this same issue and apparently stumbled on a solution. One difference though -- I've been running Ubuntu 18.04 with WSL for a year or so. But trying to update with the msi package I got the same odd issues. I also noticed another odd thing. Running `uname -r` gave me 4.40.x, which I believe means wsl2. But my version always showed as 1 when running `wsl --list --verbose` in PowerShell. 

Anyway, at one point during my struggles I wound up stopping my Ubuntu instance somehow, not sure how. But when I ran the installer _again_ it worked. But `uname -r` still read 4.40.x and my wsl version read 1. However, installing 20.04 seems to have miraculously solved everything. So maybe I should have started with that.

Not sure if this will be helpful to anyway, but I figured I'd share my experience!

**Comment by carlitorendon** [comment]
> I was in the same situation, and being unable to locate a copy of the original msi for the version I had installed, I eventually downloaded the [MS install/uninstall troubleshooter](https://support.microsoft.com/en-gb/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) - which allowed me to remove the version I was stuck with (despite not having the msi). Once that was gone I've been able to update to the latest OK.

Thank you @Dave-Lowndes it worked nicely
