### ISSUE TITLE
Redirecting command output to file results in different row counts each time

### ISSUE THREAD

**Issue by bobf32** [microsoft/WSL#5643]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: (Debian) Release:        10
Whether the issue is on WSL 2 and/or WSL 1:Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Run the following command multiple times:

/mnt/c/Program\ Files\ \(x86\)/Calibre2/calibredb.exe --with-library http://localhost:8080/#Calibre_Library list -s "vl:Unread" -f "id" --sort-by id --ascending > /mnt/c/temp/a.out ; wc -l /mnt/c/temp/a.out
-->

#  Expected behavior

The command should write the output of the calibredb command to the file a.out each time and result in a.out containing 3806 lines on each invocation.

# Actual behavior

The number of lines written to a.out varies on each invocation of the command as can be seen in screenshot 1.

# Other information

If I pipe the output to the wc command instead of writing to a file the output is 3806 every time, as expected. See screenshot 2.

/mnt/c/Program\ Files\ \(x86\)/Calibre2/calibredb.exe --with-library http://localhost:8080/#Calibre_Library list -s "vl:Unread" -f "id" --sort-by id --ascending | wc -l

![Screenhot 1](https://user-images.githubusercontent.com/6544564/88303862-6c10f980-ccff-11ea-9362-dc446772346e.png)
![Screenhot 2](https://user-images.githubusercontent.com/6544564/88303863-6ca99000-ccff-11ea-893a-4ebcbf16ba27.png)

**Comment by bobf32** [comment]
Update: I have rolled back my WSL instance from WSL2 to WSL1 and can confirm that this problem *only* manifests in the WSL2 instance.

**Comment by therealkenc** [comment]
Ref #4082 which has an evens chance of being the same. The one line submitted above is not a repro.

**Comment by bobf32** [comment]
So I had one day when this worked, but now the original construct is back to producing random truncated output:

/mnt/c/path/to/windows.exe > /mnt/c/temp.a.out

whereas the truncation does not seem to occur with:

/mnt/c/path/to/windows.exe > ~/a.out
