### ISSUE TITLE
set version Ubuntu-20.04 No distribution with supplied name

### ISSUE THREAD

**Issue by donnrri** [microsoft/WSL#5645]
Hi

Environment:   
Windows - 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Ubuntu - Ubuntu 20.04 LTS

I have installed WSL2

 In powershell (running as admin)  I set the default version of wsl 
wsl --set-default-version 2

I then set wls -l -v
This tells me the Ubuntu version I have uses WSL 1

I then try wsl --set-version- Ubuntu-20.04 2

I get the error  
'There is no distribution with the supplied name'

In my Ubuntu I use lsb_release -a to get the version it displays

Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

So I thought my version was Ubuntu-20.04

Here is a screen shot of what happens 

![screen](https://user-images.githubusercontent.com/1951795/88329643-2e719800-cd22-11ea-8f54-792a8b82a8ec.png)

I looked at the Ubuntu version in the Settings -> Apps -> Apps and Features

This had the version as  2004.2020.424.0  

However running wsl --set-version Ubuntu-2004.2020.424.0  2 resulted in the same error

**Comment by therealkenc** [comment]
> In powershell (running as admin) I set the default version of wsl

#5428 as an initial matter. Do not run `wsl.exe` as Administrator.

The syntax above is incorrect. Docs are [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2). For your scenario, with distribution `Ubuntu`:

```
PS C:\> wsl.exe --set-version Ubuntu 2
```

**Comment by donnrri** [comment]
For anyone having this issue .
1. After setting wsl --set-default-version 2
2. Uninstall your Unbuntu
3. Install from the store again

**Comment by donnrri** [comment]
Thanks for your your response

**Comment by therealkenc** [comment]
> So I don't see how my use of the command is incorrect.

Your first try was `wsl --set-distribution ubuntu 20.04 2` was incorrect because it has three parameters not two.

Your second try was `wsl --set-distribution Ubuntu-20.04` was incorrect because your distribution NAME is `Ubuntu`.

![image](https://user-images.githubusercontent.com/7049700/88397565-f8133780-cd78-11ea-9979-c0f2da66ab9f.png)

**Comment by dinaayoub** [comment]
Using "wsl --set-distribution ubuntu 2" worked for me. thanks @therealkenc.

**Comment by rcrapo** [comment]
I've tried the command "wsl --set-distribution ubuntu 2" as administrator  (I've also tried it with "wsl.exe" and it didn't work) and it still gives me the response "There is no distribution with the supplied name."

I've followed the instructions listed here: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Does anyone have any ideas?

**Comment by therealkenc** [comment]
> I've tried the command "wsl --set-distribution ubuntu 2"

It is `--set-version` not `--set-distribution`.

**Comment by adsk2050** [comment]
--set-version is also not working. I have tried:
-  wsl.exe --set-version ubuntu 20.04 2
-  wsl.exe --set-version Ubuntu 20.04 2
-  wsl.exe --set-version ubuntu 2
-  wsl.exe --set-version Ubuntu 2
-  wsl.exe --set-version 'Ubuntu 20.04' 2
-  wsl.exe --set-version 'Ubuntu 20.04 LTS' 2
