### ISSUE TITLE
Error: 0x80070006 in Ubuntu LTS

### ISSUE THREAD

**Issue by memeee728** [microsoft/WSL#5646]
I recently installed Ubuntu LTS for my Windows 10 laptop. Whenever I try to open it, it says **Error: 0x80070006**, within the Ubuntu window. If I press any key, the Ubuntu window automatically closes. I have no idea why that's happening. I used to have Ubuntu LTS before, but never got that error. This is the first time it's happening. Can someone please help me with that?

**Comment by therealkenc** [comment]
Please resubmit following the [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md) and include [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) of the `wsl.exe` launch leading to the error.
