### ISSUE TITLE
"The device is not connected." when open ubuntu/debian and other wsl linux

### ISSUE THREAD

**Issue by ZhongqiXiao** [microsoft/WSL#5647]
## Env
Version : Windows 10 build 18362.836

## Behavior
I have installed ubuntu 20.04, ubuntu 18.04, ubuntu16.04, debian gnu/linux, and when i execute these wsl linux , those program always shows
```
The device is not connected.
```

I checked Windows feature , "windows subsystem for linux " has been turn on,  I have no idea what's wrong

Your help is greatly appreciated

**Comment by therealkenc** [comment]
Please post screencap to help clarify what you mean. Type `Ubuntu-18.04` and a `cmd.exe` prompt and then screencap what happens. There isn't much to go on here.

**Comment by tecis** [comment]
I am having the same issue with a Debian distro installed in WSL.

Here is a screen shot of the console trying to ping one of Google's IP Addresses and trying to tun `sudo apt-get update` .

![Debian WSL not working](https://user-images.githubusercontent.com/67809811/88438927-c5e4f280-cdd7-11ea-8994-4a3a7161cebb.jpg)

**Comment by therealkenc** [comment]
There is no "The device is not connected" text _anywhere_ in that screencap.

Closing because the submission is effectively unrecoverable. @ZhongqiXiao if you are still experiencing difficulties please resubmit with your repro steps.
