### ISSUE TITLE
clip.exe hangs when redirecting output into it. 

### ISSUE THREAD

**Issue by EricWardner** [microsoft/WSL#5648]
# Environment

```none
Windows build number: 10.0.20175.1000
Your Distribution version: Ubuntu 18.04
WSL 2: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

```bash
echo "AAAA" | clip.exe
```

#  Expected behavior

AAAA get copied to my windows clipboard

# Actual behavior

The command hangs and nothing is copied

**Comment by therealkenc** [comment]
Ref #4475 (with a side of #4852). Am able to reproduce here. Consensus work-around is use a better `clip` application.

![image](https://user-images.githubusercontent.com/7049700/88411329-952b9b80-cd8c-11ea-9f71-1662bb5cdafc.png)

**Comment by EricWardner** [comment]
I also do not use it often. Can't remember if it was working before the most recent update.

**Comment by Biswa96** [comment]
dmesg? ETW? Any logs.

**Comment by therealkenc** [comment]
> dmesg? ETW? Any logs.

Nah. Turns out it isn't limited to `clip.exe`. Also hangs on:
```
$ ls | findstr.exe foo
```

Which [used to](https://github.com/microsoft/WSL/issues/4607) work (at least to the extent the scenario didn't hang).

**Comment by EricWardner** [comment]
Workaround I'm using is just to output to a file first and then read it in to clip.exe

```bash
echo "AAAA" > file.tmp
clip.exe < file.tmp
```

**Comment by raisin-loaf** [comment]
This is also the case with [win32yank](https://github.com/equalsraf/win32yank) which is [automatically detected by Neovim](https://github.com/neovim/neovim/blob/99aec382596bffaa91d0a944dc9474e42331ad93/runtime/doc/provider.txt#L205) meaning it's not currently possible to yank to the system clipboard from Neovim in WSL 2.

`echo 'please please me?' | win32yank.exe -i` hangs as per previous comments. It's not a problem on another computer that's still on build 20170.

Happy to gather additional info if someone can point me in the right direction. 🙂

**Comment by therealkenc** [comment]
> It's not a problem on another computer that's still on build 20170.

Those are the words I was looking for. Thanks.

**Comment by blumu** [comment]
This bug also breaks the [git credentials manager trick](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git) to authenticate in git under WSL via the Windows credential manager (`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"`)

**Comment by SR-Lut3t1um** [comment]
This Bug also breaks Docker :/

**Comment by zyazhb** [comment]
Is this still not fix in build 2018?

**Comment by shadowmaster63** [comment]
Not work in Microsoft Windows [Version 10.0.20180.1000]

**Comment by zyazhb** [comment]
> Not work in Microsoft Windows [Version 10.0.20180.1000]
> But Docker 2.3.0.4 install success.

tnx for information i have tried to install docker in build 2018 but failed.

**Comment by shadowmaster63** [comment]
> tnx for information i have tried to install docker in build 2018 but failed.

$ lsb_release -r
Release:        16.04
$ cat /proc/version
Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Fri Jun 19 21:06:10 UTC 2020

>wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2

**Comment by Mortinke** [comment]
I also get the same error with Build 20180 :(

**Comment by zyazhb** [comment]
@shadowmaster63 
```
$lsb_release -r                                                                 
Release:        18.04

$cat /proc/version
Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Fri Jun 19 21:06:10 UTC 2020

> wsl --list -v
  NAME            STATE           VERSION
* kali-linux      Stopped         2
  Ubuntu-18.04    Running         2
  Debian          Stopped         2
```
I have updated to build 2019 but when i install docker still:
```
 在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   在 System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   在 CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
```

**Comment by DarkTraveler** [comment]
I apologize everyone for my english! 

After 10 unsuccessful attempts, I thought to do reinstall windows.
But at the very last moment I changed my mind ...

1) We completely remove the Docker script via PoweShell
https://stackoverflow.com/questions/42161471/how-to-uninstall-docker-machine-under-windows-10/51167323#51167323

2) Run the latest Docker installation, I took 2.3.4.0
3) When installing, DO NOT select support for WSL2

4) Docker is installed ... and a notification appears at startup, about the start of the WSL2 subsystem, I don't understand how, but the launch still occurs

5) Docker itself did not completely start for me

6) You need to get to the settings and run hard reset

7) He is started, but unfortunately past manipulations cleared it :/ Nevertheless, I have already launched my working project
P/s I was able to run only through powershall: / through WSL hangs on deployment

8) Also check that the marks about integration with wsl 2 distributions have not gone off (Resources / Wsl integration)

9) maybe he's pretending ... that he works through wsl2 :)

**Comment by metcalfc** [comment]
Folks here for Docker issues. This WSL2 bug does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can  disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```

Docker on the Windows side (powershell, cmd, etc) will behave normally.

**Comment by bsosnowski** [comment]
> Windows 20175 and 20180 have this issue

I have the same issue with 19041.423. I think it started with one of the updates.

**Comment by therealkenc** [comment]
> I have the same issue with 19041.423.

The cause of this issue is known and applies only to Insider builds. **If** you are experiencing a problem on `19041.*` that appears to have similar symptoms, please open a new tracker. Be sure to follow the template and be _excruciatingly specific_ about the reproduction steps, in order to get a me2 from someone on 19041.

**Comment by nlundquist** [comment]
Still there in 20185 :(

**Comment by nguyennb9** [comment]
win32yank.exe was working perfectly in Neovim before I join the insider program. So that this bug happens with the new build only. I guess I have to use vscode while waiting for this bug fixed :(
```
Edition	Windows 10 Pro Insider Preview
Version	2004
Installed on	‎8/‎6/‎2020
OS build	20185.1000
Experience	Windows Feature Experience Pack 120.19801.0.0
```

**Comment by benhillis** [comment]
/fixed [20190](https://blogs.windows.com/windowsexperience/2020/08/12/announcing-windows-10-insider-preview-build-20190/).

**Comment by sajithneyo** [comment]
I updated the windows yesterday. It's KB4566782 (OS Build 19041.450). Suddenly WSL 2 started crashing. Any fixes?

**Comment by benhillis** [comment]
@sajithneyo - define "crashing".  This is an unrelated issue.

**Comment by sajithneyo** [comment]
@benhillis my bad. opened #5760

**Comment by Siths** [comment]
Anyways to get Docker Desktop installed?
Docker Desktop 2.3.0.4 
Installation failed
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()

**Comment by 1two3code** [comment]
Since it has not been mentioned here yet:

This issue can also occur with `<3>init: (2167) ERROR: UtilConnectUnix:467: connect failed 111` rather than just hanging the session.
In my case it was related to the $WSL_INTEROP pointing to the wrong parent.
This can be fixed by putting the following function in your .bashrc, as explained by @lvlts [here](https://github.com/microsoft/WSL/issues/5065#issuecomment-682198412)
```
fix_wsl2_interop() {
    for i in $(pstree -np -s $$ | grep -o -E '[0-9]+'); do
        if [[ -e "/run/WSL/${i}_interop" ]]; then
            export WSL_INTEROP=/run/WSL/${i}_interop
        fi
    done
}
fix_wsl2_interop
```

I hope this might help someone 🙏

**Comment by Yalian** [comment]
This bug seems that still persists as I'm experimenting the hangs with docker in build `22621`

**Comment by ImBIOS** [comment]
This bug seems that still persists as I'm experimenting the hangs with docker in build `137060`
