### ISSUE TITLE
c# .net program is opening port on host instead of wsl2 ubuntu 20.04

### ISSUE THREAD

**Issue by speed2048** [microsoft/WSL#5653]
# Environment

Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

# Steps to reproduce

The following code tests to see if a port is opened by an application. This code is running on Ubuntu 20.04 with dotnet 3.1.6.
```
using System;
using System.Net;
using System.Net.Sockets;

namespace testportopenwsl2
{
    
    class Program
    {
        public static bool isPortActive(string hostname = "localhost", int portno = 31416)
        {
            IPAddress[] addresses = Dns.GetHostAddresses(hostname);
            IPAddress ipa = null;

            foreach (IPAddress address in addresses)
            {
                if (address.AddressFamily == AddressFamily.InterNetwork)
                {
                    ipa = address;
                    break;
                }
            }

            try
            {
                Socket sock = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                sock.Connect(ipa, portno);
                if (sock.Connected == true)
                {
                    sock.Close();
                    return true;
                }


            }
            catch (System.Net.Sockets.SocketException ex)
            {
                if (ex.SocketErrorCode == SocketError.ConnectionRefused)
                {
                    return false;
                }
            }
            return false;
        }
        static void Main(string[] args)
        {
            if ( isPortActive())
            {
                Console.WriteLine("Port is active.");
            }
            else
            {
                Console.WriteLine("Port is not active.");
            }
        }
    }
}
```

#  Expected behavior

The code should be trying to open a port on the Ubuntu virtual Machine.

# Actual behavior

It trys to open the port on the host machine. 

Example... I have Boinc Manager ( https://boinc.berkeley.edu/ ) running on windows 10  and it has port 31416 open for connection. When I run the program on Ubuntu  it  will print Port is active, when I stop the Boinc Manager and rerun the program it will print Port is not active. So that tells me its looking at the Windows 10 instead of the ubuntu wsl2 vm.  

I wondering if this is by design or is there something I need to do to ensure it opens the port on Ubuntu....

Regards.

**Comment by therealkenc** [comment]
> Linux version 4.4.0-19041-Microsoft

That's WSL1

**Comment by speed2048** [comment]
That was it however when I enabled the VirtualMachinePlatform my VMWorkstation 15. 5.6 had failed to start my VM and had to mess with the virtualization settings but now docker with wsl2 on that vm no longer works.... Geez.....
