### ISSUE TITLE
Vmmem.exe takes way too much RAM (Memory Leak)

### ISSUE THREAD

**Issue by h0gan1ee** [microsoft/WSL#5654]
# Environment

```none
Windows build number: Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Your Distribution version: Pengwin 11
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

**Just use it normally.**

#  Expected behavior

**It should not take this much memory.**

# Actual behavior

**Vmmem.exe takes way too much memory (>=10,234 MB) than it actually need.
It seems to be a memory leak problem.**

**Other Information:**

**Linux Kernel: 4.19.104-microsoft-standard**

![批注 2020-07-26 175531](https://user-images.githubusercontent.com/39949564/88476494-6ddef500-cf6b-11ea-9446-9ee23160db99.jpg)
![批注 2020-07-26 175340](https://user-images.githubusercontent.com/39949564/88476496-733c3f80-cf6b-11ea-9220-a35064c650f7.jpg)

**And after I run `wsl --shutdown`:**

![批注 2020-07-26 175817](https://user-images.githubusercontent.com/39949564/88476547-ba2a3500-cf6b-11ea-8bbc-36a136320f6c.jpg)

By the way, "内存" means RAM.

**Comment by onomatopellan** [comment]
That's cached memory. The original thread is #4166
You can use:
`sync; echo 3 | sudo tee /proc/sys/vm/drop_caches`

**Comment by h0gan1ee** [comment]
> That's cached memory. The original thread is #4166
> You can use:
> `sync; echo 3 | sudo tee /proc/sys/vm/drop_caches`

If that is cached memory, it should be released when I have no spare memory to use, but it didn't and my computer became slow.

**Comment by onomatopellan** [comment]
Yes, the team is working on it. For now you can use [.wslconfig](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file to set the RAM you want WSL2 to use.

**Comment by h0gan1ee** [comment]
> Yes, the team is working on it. For now you can use [.wslconfig](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file to set the RAM you want WSL2 to use.

I see. Thanks for your help!

**Comment by olegKusov** [comment]
> Yes, the team is working on it. For now you can use [.wslconfig](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file to set the RAM you want WSL2 to use.

wslconfig 1GB ram limit breaks my nodejs build and CPU starts working hard.

**Comment by onomatopellan** [comment]
@olegKusov How much RAM do you have on your PC?
