### ISSUE TITLE
Brown color not changing

### ISSUE THREAD

**Issue by linuxcyberlabs** [microsoft/WSL#5655]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.421]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
```

# Steps to reproduce

use this colour scheme:
{
            "name": "linux",
            "foreground": "#C7F0FF",
            "background": "#0C0C0C",
            "cursorColor": "#FFFFFF",
            "black": "#0C0C0C",
            "red": "#E74856",
            "green": "#AFE4AC",
            "yellow": "#fffc5b",        //this seems to have no effect what so ever
            "blue": "#B170FF",
            "purple": "#E087FD",
            "cyan": "#3A96DD",
            "white": "#CCCCCC",
            "brightBlack": "#767676",
            "brightRed": "#FF707D",
            "brightGreen": "#16C60C",
            "brightYellow": "#F9F1A5",
            "brightBlue": "#3B78FF",
            "brightPurple": "#B4009E",
            "brightCyan": "#61D6D6",
            "brightWhite": "#F2F2F2"
        }

#  Expected behavior

for the line numbers to actually be yellow! "#fffc5b"
![image](https://user-images.githubusercontent.com/66681254/88477329-d2468800-cf5c-11ea-8798-068e6fbc8868.png)

# Actual behavior

the brown is still brown and not yellow!?

**Comment by therealkenc** [comment]
> Reporting issues in Windows Console or WSL text rendering/user experience
> Note that WSL distro's launch in the Windows Console (unless you have taken steps to launch a 3rd party console/terminal). ?> Therefore, *please file UI/UX related issues in the [Windows Console issue tracker](https://github.com/microsoft/console)*.
