### ISSUE TITLE
Rviz bug, failing to launch 

### ISSUE THREAD

**Issue by Daneduke7** [microsoft/WSL#5656]
I was running RVIZ fine about a 3 days ago, but then all of a sudden it stopped working. I've ried uninstalling the package and reinstalling it, both from source and the Debian repository. When I attempted to launch rviz, I get this error.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-daneduke777'
[ INFO] [1595816224.380083400]: rviz version 1.13.13
[ INFO] [1595816224.380154200]: compiled against Qt version 5.9.5
[ INFO] [1595816224.380192700]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1595816224.386157000]: Forcing OpenGl version 0.
Segmentation fault

Does anyone know what may be causing it, or what I can do to fix it?

Ogre.log file 
rosrun rviz rviz -l
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-daneduke777'
[ INFO] [1595816329.584187200]: rviz version 1.13.13
[ INFO] [1595816329.584263300]: compiled against Qt version 5.9.5
[ INFO] [1595816329.584272700]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1595816329.597628900]: Forcing OpenGl version 0.
[ INFO] [1595816329.682554700]: Creating resource group General
[ INFO] [1595816329.682701300]: Creating resource group Internal
[ INFO] [1595816329.682778200]: Creating resource group Autodetect
[ INFO] [1595816329.682932500]: SceneManagerFactory for type 'DefaultSceneManager' registered.
[ INFO] [1595816329.683216700]: Registering ResourceManager for type Material
[ INFO] [1595816329.683356100]: Registering ResourceManager for type Mesh
[ INFO] [1595816329.683451500]: Registering ResourceManager for type Skeleton
[ INFO] [1595816329.683572200]: MovableObjectFactory for type 'ParticleSystem' registered.
[ INFO] [1595816329.683708500]: ArchiveFactory for archive type FileSystem registered.
[ INFO] [1595816329.683790200]: ArchiveFactory for archive type Zip registered.
[ INFO] [1595816329.683852800]: ArchiveFactory for archive type EmbeddedZip registered.
[ INFO] [1595816329.683974400]: DDS codec registering
[ INFO] [1595816329.684043500]: FreeImage version: 3.17.0
[ INFO] [1595816329.684103900]: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
[ INFO] [1595816329.684311900]: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,cut,xbm,xpm,gif,hdr,g3,sgi,rgb,rgba,bw,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti,x3f,webp,jxr,wdp,hdp
[ INFO] [1595816329.684419800]: PVRTC codec registering
[ INFO] [1595816329.684472600]: ETC codec registering
[ INFO] [1595816329.684540800]: Registering ResourceManager for type HighLevelGpuProgram
[ INFO] [1595816329.684630500]: Registering ResourceManager for type Compositor
[ INFO] [1595816329.684929200]: MovableObjectFactory for type 'Entity' registered.
[ INFO] [1595816329.685030000]: MovableObjectFactory for type 'Light' registered.
[ INFO] [1595816329.685114800]: MovableObjectFactory for type 'BillboardSet' registered.
[ INFO] [1595816329.685185400]: MovableObjectFactory for type 'ManualObject' registered.
[ INFO] [1595816329.685277600]: MovableObjectFactory for type 'BillboardChain' registered.
[ INFO] [1595816329.685381900]: MovableObjectFactory for type 'RibbonTrail' registered.
[ INFO] [1595816329.685570200]: *-*-* OGRE Initialising
[ INFO] [1595816329.685668400]: *-*-* Version 1.9.0 (Ghadamon)
[ INFO] [1595816329.685760900]: OverlayElementFactory for type Panel registered.
[ INFO] [1595816329.685854200]: OverlayElementFactory for type BorderPanel registered.
[ INFO] [1595816329.685944300]: OverlayElementFactory for type TextArea registered.
[ INFO] [1595816329.686049200]: Registering ResourceManager for type Font
[ INFO] [1595816329.686162200]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL
[ INFO] [1595816329.689596900]: Installing plugin: GL RenderSystem
[ INFO] [1595816329.689763400]: OpenGL Rendering Subsystem created.
[ INFO] [1595816329.702219600]: Plugin successfully installed
[ INFO] [1595816329.702382400]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/Plugin_OctreeSceneManager
[ INFO] [1595816329.704281500]: Installing plugin: Octree Scene Manager
[ INFO] [1595816329.704456900]: Plugin successfully installed
[ INFO] [1595816329.704505400]: Loading library /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/Plugin_ParticleFX
[ INFO] [1595816329.706212200]: Installing plugin: ParticleFX
[ INFO] [1595816329.706366400]: Particle Emitter Type 'Point' registered
[ INFO] [1595816329.706410600]: Particle Emitter Type 'Box' registered
[ INFO] [1595816329.706496100]: Particle Emitter Type 'Ellipsoid' registered
[ INFO] [1595816329.706571600]: Particle Emitter Type 'Cylinder' registered
[ INFO] [1595816329.706652000]: Particle Emitter Type 'Ring' registered
[ INFO] [1595816329.706735500]: Particle Emitter Type 'HollowEllipsoid' registered
[ INFO] [1595816329.706815900]: Particle Affector Type 'LinearForce' registered
[ INFO] [1595816329.706899000]: Particle Affector Type 'ColourFader' registered
[ INFO] [1595816329.706976000]: Particle Affector Type 'ColourFader2' registered
[ INFO] [1595816329.707060500]: Particle Affector Type 'ColourImage' registered
[ INFO] [1595816329.707150500]: Particle Affector Type 'ColourInterpolator' registered
[ INFO] [1595816329.707213600]: Particle Affector Type 'Scaler' registered
[ INFO] [1595816329.707289400]: Particle Affector Type 'Rotator' registered
[ INFO] [1595816329.707344200]: Particle Affector Type 'DirectionRandomiser' registered
[ INFO] [1595816329.707426700]: Particle Affector Type 'DeflectorPlane' registered
[ INFO] [1595816329.707507500]: Plugin successfully installed
[ INFO] [1595816329.707621900]: CPU Identifier & Features
[ INFO] [1595816329.707691700]: -------------------------
[ INFO] [1595816329.707768500]:  *   CPU ID: AuthenticAMD: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
[ INFO] [1595816329.707851400]:  *      SSE: yes
[ INFO] [1595816329.707934000]:  *     SSE2: yes
[ INFO] [1595816329.708017200]:  *     SSE3: yes
[ INFO] [1595816329.708088700]:  *      MMX: yes
[ INFO] [1595816329.708170000]:  *   MMXEXT: yes
[ INFO] [1595816329.708244800]:  *    3DNOW: no
[ INFO] [1595816329.708320300]:  * 3DNOWEXT: no
[ INFO] [1595816329.708396600]:  *     CMOV: yes
[ INFO] [1595816329.708475500]:  *      TSC: yes
[ INFO] [1595816329.708554700]:  *      FPU: yes
[ INFO] [1595816329.708630600]:  *      PRO: yes
[ INFO] [1595816329.708679900]:  *       HT: no
[ INFO] [1595816329.708764400]: -------------------------
[ INFO] [1595816329.708842300]: ******************************
*** Starting GLX Subsystem ***
******************************
[ INFO] [1595816329.708943600]: Registering ResourceManager for type Texture
[ INFO] [1595816329.709088900]: GLRenderSystem::_createRenderWindow "OgreWindow(0)", 1x1 windowed  miscParams: FSAA=4 contentScalingFactor=1.000000 externalGLControl= externalWindowHandle=9437185 parentWindowHandle=9437185
[ INFO] [1595816329.713678700]: GLXWindow::create used FBConfigID = 90
[ INFO] [1595816329.714027200]: GL_VERSION = 1.4 (2.1 Mesa 20.1.0-devel (git-83f5a17a34))
[ INFO] [1595816329.714364200]: GL_VENDOR = Mesa Project

**Comment by Daneduke7** [comment]
Hello, I'm curious as to why the issue was closed?

**Comment by therealkenc** [comment]
Deleted [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md). 

> 1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.

In this instance _with_ version deets and a repro, the likelihood at arriving at an WSL actionable is "small". Your scenario was working at one point. "All of a sudden" is not actionable information. You will get better eyeballs debugging the problem in a forum related to the products involved (rviz, your X11 server, your distro underneath, etc) than a question tag in a WSL bug tracker, ref #637 ([message](https://github.com/microsoft/WSL/issues/637#issuecomment-392989799)). Loophole being I'll cut and paste most anything that looks as if the steps might plausibly work. [It's actually a low bar.]
