### ISSUE TITLE
WSL2 cannot make directory in drvfs when case=dir is in mount option

### ISSUE THREAD

**Issue by excelle08** [microsoft/WSL#5657]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

```bash
# When case=dir is in the mount option
$ cd /mnt/d
$ mkdir test
mkdir: cannot create directory ‘test’: Permission denied
$ sudo mkdir test
mkdir: cannot create directory ‘test’: Permission denied
```

#  Expected behavior

`mkdir` should create the desired directory

# Actual behavior

`mkdir` fails with "Permission denied" error even if using `sudo`. It only succeeds if the `case=dir` option is removed when mounting.

**Comment by therealkenc** [comment]
Was able to reproduce here. `C:` is okay. Both `C:` and `D:` are NTFS.

![image](https://user-images.githubusercontent.com/7049700/88505284-efdf1600-cf8b-11ea-88a0-4ca08eb29f16.png)

> Whether the issue is on WSL 2 and/or WSL 1: WSL 2

On WSL2, for case sensitivity in particular, you want `/home`. The `case=` feature never quite took.

**Comment by excelle08** [comment]
> On WSL2, for case sensitivity in particular, you want /home

@therealkenc That doesn't solve the problem - the capacity of `/home` is constrained by drive C:, and you can't access the content in `/home` in Windows.

I found a better workaround by recursively enabling case sensitivity for a directory in Powershell (Run as admin):
```powershell
cd D:\myprog
(Get-ChildItem -Recurse -Directory).FullName | ForEach-Object {fsutil.exe file setCaseSensitiveInfo $_ enable}
```

**Comment by therealkenc** [comment]
> is constrained by drive C

Import your distro onto `D:`.

> you can't access the content in /home in Windows

That is incorrect.

> I found a better workaround

You haven't used it yet. But the work-around is very appreciated; nicely done. 👍

**Comment by ouija** [comment]
Is there no solution to this?  

I needed a larger disk for building some source code in linux, but am getting a "Please move your source tree to a case-sensitive filesystem" error when building, and trying to enable case sensitivity via case=dir in the [automount] options of /etc/wsl.conf causes this 'permission denied' error on my secondary drive (but of course, it is working from the /mnt/c/Users/<user> folder).

I really hope this gets resolved, it would be nice to take advance of case senstivity on seperate drives instead of just the user's home folder 👎

**Comment by excelle08** [comment]
> Is there no solution to this?
> 
> I needed a larger disk for building some source code in linux, but am getting a "Please move your source tree to a case-sensitive filesystem" error when building, and trying to enable case sensitivity via case=dir in the [automount] options of /etc/wsl.conf causes this 'permission denied' error on my secondary drive (but of course, it is working from the /mnt/c/Users/ folder).
> 
> I really hope this gets resolved, it would be nice to take advance of case senstivity on seperate drives instead of just the user's home folder 👎

The best way is to create a new directory, set it to case sensitive using the Powershell command, and clone your source code there.

**Comment by ouija** [comment]
But my understanding was that the `setCaseSensitiveInfo` Powershell command is _not_ recursive, so all directories created during checkout would be created without this case-sensitive attribute being set -- although I haven't verified this.  (I am attempting to build from my main C drive parition now but had to free up a lot of space to do so)

**Comment by excelle08** [comment]
> But my understanding was that the `setCaseSensitiveInfo` Powershell command is _not_ recursive, so all directories created during checkout would be created without this case-sensitive attribute being set -- although I haven't verified this. (I am attempting to build from my main C drive parition now but had to free up a lot of space to do so)

@ouija If the parent directory is set to be case sensitive, aren't the files and directories created under it also case sensitive?

**Comment by ouija** [comment]
No, according to the documentation: 

> Note that the per-directory case sensitivity flag is not inherited; directories created in a case sensitive directory are not automatically case sensitive themselves. You must explicitly mark each directory as case sensitive. Changing the flag requires “write attributes” permission to the directory.

**Comment by up4k** [comment]
@ouija according to [the devs blog post](https://devblogs.microsoft.com/commandline/improved-per-directory-case-sensitivity-support-in-wsl/#case-sensitivity-inheritance), case sensitivity inherits in child directories.
Checked on WSL2 with default settings (9p mounted Windows drive D:, no explicit options in wsl.conf). Can not use setfattr and getfattr from Linux, but after setting attribute with fsutil.exe outside of WSL (from admin command prompt) one can create and work with case sensitive file names in subdirectories.

**Comment by eusoubrasileiro** [comment]
same issue here. ##The solution is as you described @up4k !!!
