### ISSUE TITLE
can't connect mysql running on wsl2

### ISSUE THREAD

**Issue by gao4263** [microsoft/WSL#5658]
I have to wsl2 instance , one is ubuntu ,the other is centos7,  I have install mysql on two wsl2 instance,  then  I  run python  on windows  as below,

this code can connect mysql on ubuntu , but can't connect mysql on centos ,   if I change host to  eth0 ip of centos , It work

```
import mysql.connector


mydb = mysql.connector.connect(
  host="localost",
  port=3306,
  user="root",
  password="xxx",
  database="xxxx"
)
```

**Comment by therealkenc** [comment]
Deleted template. If it is working in ubuntu not centos the problem is almost certainly in userspace not WSL. WAG you are using the same port for both instances of mysql.
