### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070057

### ISSUE THREAD

**Issue by MattWThomas** [microsoft/WSL#5660]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: NA (latest Ubuntu Debian and Kali)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2? (can't run WSL bash)
```

# Steps to reproduce

Open any distro on a completely clean install of Windows and WSL. Ubuntu, Debian, and Kali tested so far.

#  Expected behavior

Distro installs correctly.

# Actual behavior

Launching "Debian" or "Ubuntu" or "Kali Linux" from the MS store results in the following error.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...
```

**Comment by MattWThomas** [comment]
#7 is the same error message. I have made sure that legacy mode is disabled as advised in the original issue.

**Comment by therealkenc** [comment]
> #7 is the same error message. 

Closer #4800 #5293

[Detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by MattWThomas** [comment]
It looks very much like #5293. I was actually able to fix this by removing HyperV. It's odd. However, it probably has something to do with the virtual networking device from HyperV (#5293 is supposedly a networking issue). Or maybe it's just a coincidence.
