### ISSUE TITLE
WSL 2: Enabling 'Virtual Machine Platform' feature causes AMD Radeon driver to fail to load

### ISSUE THREAD

**Issue by pd5rm** [microsoft/WSL#5662]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: Ubuntu (but doesn't matter, since it's Windows/AMD issue).
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

Additional graphics related details (this is relevant, see below):
```
AMD Driver): 20.7.2 (7/11/2020 release date)
My BIOS 'UMA Frame buffer' is set to auto (other options available are 256MB and 512MB).
Note my graphics chipset is onboard/integrated and not a dedicated card.
```

System
```
HP EliteDesk 705 G5
```

# Steps to reproduce

1. Install the 'Virtual Machine Platform' features, following steps [here ](https://docs.microsoft.com/en-us/windows/wsl/install-win10)to install WSL 2.
2. Reboot machine.
3. Observe that resolutions seems odd (lower)
4. Open Device manage, and notice that AMD Driver fails with: `Windows has stopped this device because it has reported problems. (Code 43)`
5. Open WSL 2 based distro (Ubuntu), and verify that it works.
6. Disable 'Virtual Machine Platform'
7. Reboot.
8. Observe that resolution is restored to normal, and AMD driver loads successfully.
9. WSL 2 image no longer work. WSL 1 based image works fine.

#  Expected behavior

I would like to run WSL 2 based Linux and be able to run my native graphic card driver. ;-)

# Actual behavior

Some conflict occurs between the Virtual Machine Platform feature and AMD drivers. 

I'd like to know whether this is a Window or AMD issue, so I can followup for support accordingly.
Any other logs/debugging I can gather or provide?

**Comment by sr229** [comment]
Running Acer Nitro 5 AN515-43 here. I can't replicate this issue probably because the driver/GPU supports virtual GPUs via DirectX

**Comment by pawantimilsina** [comment]
I have the exact same issue as documented. My CPU is ryzen 5 pro 2400ge with Vega 11 integrated graphics.

**Comment by enalbert** [comment]
Same issue found on HP Elitebook 745 G6 with AMD Ryzen 5 PRO 3500U + Radeon Vega Mobile

**Comment by shpReacts** [comment]
I'm experiencing the same issue on HP Elitebook 775 g5 (AMD ryzen 7 pro 2700u + radeon vega mobile)

**Comment by tamuratak** [comment]
Enabling SVM and disabling IOMMU in BIOS settings has solved the issue. Ryzen 5 2400G.

**Comment by tamuratak** [comment]
Enabling SVM and disabling IOMMU in BIOS settings has solved the issue. AMD Ryzen 5 2400G

https://www.reddit.com/r/AMDHelp/comments/byaa8l/bootlopp_when_hyperv_and_amd_ryzensvm_enabled/

**Comment by chemoms** [comment]
Same issue found on HP Elitebook 755 G5 (Ryzen 7).

Disabling SVM has solved the issue but VirtualBox is KO.
No IOMMU option in BIOS settings in my laptop.

So sad.... :(

**Comment by pd5rm** [comment]
SVM is enabled (at least on my desktop HP 705). There's no ability to disable IOMMU from my BIOS. This seems like a HP BIOS specific issue. I suspect I can could disable onboard video and install a video card to make this problem go away, however laptop users don't have that option obviously.

@tamuratak Can you tell me what make/model of your system is?

Just for fun I 'disabled' SVM as well (thinking perhaps the option was working in opposite way). I noticed that the Window features seems to detect this when displaying the HyperV options (they're greyed out).
![SVM-Disabled](https://user-images.githubusercontent.com/1731288/93689647-5b71cb00-fa85-11ea-9241-996a4842a6cf.png)
![SVM-Enabled](https://user-images.githubusercontent.com/1731288/93689648-5c0a6180-fa85-11ea-903c-9053f0f53228.png)

**Comment by remisharrock** [comment]
Have an issue with Ryzen 5 mobile 2500u with vega 8 graphics. When I install either Hyper V or Virtual Machine Platform,  I cannot even launch visual studio code or windows terminal because they use gpu acceleration :) 
So it looks like the driver is failing.
When I uninstall Cirtual Machine Platform, it works again, but no WSL ...

**Comment by shpark0603** [comment]
I had the same issue with my HP EliteBook 755 G5 with AMD Ryzen 7 PRO 2700U w/ Radeon Vega Mobile Gfx on Windows version 2004.
The issue has fixed somehow by updating Windows to version 20H2.

**Comment by remisharrock** [comment]
> I had the same issue with my HP EliteBook 755 G5 with AMD Ryzen 7 PRO 2700U w/ Radeon Vega Mobile Gfx on Windows version 2004.
> The issue has fixed somehow by updating Windows to version 20H2.
> I suggest you give it a try 🤞

Well, on windows 20H2 that I just tried, still have the same issue with windows terminal and visual studio code ... so until it is fixed I don't use WSL but virtualbox instead...

**Comment by tamuratak** [comment]
You can try `code --disable-gpu`. See https://code.visualstudio.com/docs/supporting/FAQ#_vs-code-is-blank

**Comment by remisharrock** [comment]
> You can try `code --disable-gpu`. See https://code.visualstudio.com/docs/supporting/FAQ#_vs-code-is-blank

yes it works. But still I have GPU acceleration off everywhere, for example in chrome/edge :

when I go to edge://gpu/   here is the result:

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Disabled
Hardware Protected Video Decode: Disabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Disabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable

I sent a bug report to AMD, maybe that will help ... I don't know if it is windows or AMD driver related.

**Comment by uastack** [comment]
For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".

I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change.

**Comment by pankaj-nikam** [comment]
@uastack , I tried to do the legacy boot thing, it did not work, it still resulted in BSOD.

**Comment by uastack** [comment]
@pankaj-nikam To be clear you do not want legacy boot. You want "Legacy Support **Disable** and Secure Boot Disable" or "Legacy Support **Disable** and Secure Boot Enable". 

A BSOD is different then the issue initially reported in this thread. The issue initially reported and the one I was able to reproduce is that when Virtual Machine Platform is enabled AMD Radeon Graphics fails to load showing, _Windows has stopped this device because it has reported problems. (Code 43)_
For a BSOD make sure BIOS and drivers are up to date.  
Which platform are you using?

**Comment by pankaj-nikam** [comment]
Hi @uastack, I tried either way, it does not work. When I enable "Virtualization Platform", it results into BSOD with HP Laptop (Ryzen 4600H) and 24 GB RAM. The drivers and BIOS are up to date as per HP site. If I install non OEM drivers, it results into slow booting.

**Comment by uastack** [comment]
@pankaj-nikam sorry to hear this did not work. Is this an Omen 15z? When you say you have an HP system with a 4600H that leads me to thinking you also have an Nvidia discrete card.  My 2 cents on a few things to try:
Use DDU to fully remove both the AMD and Nvidia graphics drivers. 
With no graphics drivers installed enable Virtual Machine Platform, do you still get a BSOD? If you do  get a BSOD then there is something beyond the graphics drivers causing the issue most likely. 
If you do not get a BSOD with no graphics driver installed then try disabling Virtual Machine Platform. After Virtual Machine Platform is disabled Install the AMD graphics driver. Once the AMD graphics driver is fully installed and you have rebooted, enable Virtual Machine Platform. If you get a BSOD then I would try removing the AMD driver and try the latest from AMD https://www.amd.com/en/support/apu/amd-ryzen-processors/amd-ryzen-5-mobile-processors-radeon-graphics/amd-ryzen-5-4600h.
If you do not get a BSOD with just the AMD graphics driver then I would move on to testing Nvidia drivers.

**Comment by pankaj-nikam** [comment]
Hi @uastack, so far, I have tried the following:
A. Uninstalled both AMD and Nvidia drivers using DDU in safe mode (Didnt knew what ddu is till now, thanks for that)
B. Enabled virtualization platform it works without any drivers.
I will update this post after installing AMD drivers.

**Comment by uastack** [comment]
@pankaj-nikam glad to hear it worked and you are up and running!

**Comment by pankaj-nikam** [comment]
@uastack Thank you so much for your input, I forgot to mention my model number in previous post, it is HP Pavilion - 15-ec1051ax.

**Comment by pankaj-nikam** [comment]
@uastack now I have a strange issue, when I shut down the machine, it automatically restarts 😃

**Comment by pankaj-nikam** [comment]
@uastack , I had to do a recovery install and work the way through. It does crash again with OS updated to 20H2. If I clean the drivers and install it per your suggestion, it does not shutdown.
It is confirmed to be a driver issue. Let us hope that this gets resolved soon.
Thanks.

**Comment by uastack** [comment]
@pankaj-nikam sorry that is a bummer. Looking on HP's page neither the AMD or Nvidia drivers that they have listed are officially for 20H2. If it was me I would experiment with some of the newer drivers from AMD and Nvidia's site. While it is best practice to stick with OEM drivers, sometimes you have to experiment :) 

Would also recommend logging a case with HP support to make sure they are aware of the issue.

**Comment by pankaj-nikam** [comment]
@uastack, yes its a bummer! I tried to experiment with the latest AMD drivers from AMD site, however the machine takes too long to start - the official drivers on HP site - boot time 3 seconds - Drivers on AMD site - 1 minute or more. Also, after installing the drivers on the AMD site, it does not cause BSOD with virtualization platform; hence I confirmed that it is a driver issue.
I had logged a case with HP people, they have escalated the issue, however there is no word from them since long time. I think they must be investigating how to overcome this issue.

**Comment by remisharrock** [comment]
I also created an issue on amd community 4 weeks ago, but it looks like my post had "46" views, no answer, no kudo ... and I also filled an issue with the "amd bug report tool" ... maybe you should do the same so that AMD is aware something is wrong with their drivers

**Comment by uastack** [comment]
Hi @pankaj-nikam sorry for the late reply. systems with switch-able graphics brings a lot of complexity to the situation. When you try the latest graphics are you updating both the AMD and Nvidia drivers? I know it is not a fun process but I would again recommend removing both drivers installing the latest AMD driver then installing the latest Nvidia and see if you have the same slow boots. I would also recommend disabling Fast Startup as I have seen that cause issues with systems now shutting down or extending boot times even though it is meant to speed up boot times. 

@remisharrock what notebook do you have? Have you verified the system does not have legacy or CSM enabled in the BIOS. As stated above my HP EliteBook system only experiences the issue is legacy/CSM is enabled in the BIOS.

**Comment by pankaj-nikam** [comment]
Hi @uastack , I can understand. Its holiday season (almost) 😃 
Sure, I will give it a shot and update here.

**Comment by pankaj-nikam** [comment]
Hi @uastack , thanks for the insight. I used AMD Clean-up utility to clear the existing drivers.
Next, I uninstalled Nvidia drivers.
Then I installed both official latest drivers (AMD: 20.12.1 and Nvidia:460.79).
Tried enabling all options (Virtualization, Containers, Hyper V and WSL2) and it works! However, it did not shutdown!
I disabled fast boot and it works like a charm 👍🙌

**Comment by uastack** [comment]
@pankaj-nikam bummer, was hopeful and then you lost hibernate :( Hopefully HP will respond to your case soon.

**Comment by pankaj-nikam** [comment]
Hi @uastack , yes, let us hope for the best :)
The issue is more of driver. If they update it, it should ideally resolve what I am going through. AMD and HP people need to sit together and fix this, that is how it should ideally be done. Let us hope any one of the team reads this thread and does whatever is necessary 😄 
Thank you for your valuable input though. At least I was able to get the HyperV and WSL2 running because of you. Even though fast startup and hibernate is compromised, I still can manage with it (though not for too long 😄)

**Comment by nithinmohantk** [comment]
No luck for me though with Windows Insider preview 21277. I resetted drivers using DDU, but no luck.

**Comment by remisharrock** [comment]
@uastack I have the "Mini PC T-Bao TBOOK MN25 AMD Ryzen 5 2500U 16GB DDR4 512 Go NVME SSD Radeon Vega 8 Graphics"  https://www.banggood.com/en/T-Bao-TBOOK-MN25-Mini-PC-AMD-Ryzen-5-2500U-16GB-DDR4-512GB-NVME-SSD-Radeon-Vega-8-Graphics-2_0GHz-to-3_6GHz-DP-HD-4K-Dual-WiFi-p-1671849.html 
Let me try to find "legacy or CSM enabled in the BIOS" :)

**Comment by remisharrock** [comment]
@uastack 
> Let me try to find "legacy or CSM enabled in the BIOS" :)

Yes I do have a csm support module configuration page. ![IMG_20201215_014449.jpg](https://user-images.githubusercontent.com/8048877/102153367-556a6b00-3e77-11eb-97a6-2dbc176fa454.jpg)
Should I turn it off completely or change some parameters here ?

**Comment by uastack** [comment]
@remisharrock when you disabled CSM support, under Option ROM execution did the Video option change to UEFI? Hopefully it would, but strange things sometimes happen.

**Comment by remisharrock** [comment]
> @remisharrock when you disabled CSM support, under Option ROM execution did the Video option change to UEFI? Hopefully it would, but strange things sometimes happen. 
> 
> 
> 

Yes, in fact I couldn't disable CSM before putting video to UEFI, then rebooting then going back and change CSM to disable!

**Comment by pankaj-nikam** [comment]
@nithinmohantk , I am on stable build. The Windows version is important, I guess.

My windows details are:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11-‎12-‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

Try it with this version. Also, what is your configuration?

**Comment by nithinmohantk** [comment]
@pankaj-nikam 

I realized it is the wifi driver that is causing the problem,  I disabled it after multiple tries. Everything works fine again. 
My Specs - HP Pavillion Gaming 15-ec1001na - ryzen 5 4600h , 32x2 GSkill 3200SO-DIMM

So I will have to rely on Wired or USB Wifi to continue using it. Sadly there is no new drivers from HP for the Realtek card.

**Comment by pankaj-nikam** [comment]
@nithinmohantk , it's the drivers which are the culprit. I am not sure why half-baked drivers are pushed to consumers without extensive testing. 4600H is supposed to be high end processor and the Gaming series laptops are ought to be stable. I am not sure why don't they go correct in the first place. Even the WHQL drivers were causing BSOD - how did they pass the certification?
It's sad to know that you must rely on wired Wi-Fi. Let us hope that this gets fixed soon by the team.

**Comment by nithinmohantk** [comment]
@pankaj-nikam I had enough with restore, reinstall etc. I finally replaced the wifi card with an AX200 one found on amazon. 
It worked perfectly on my 15-ec1001na, and I also cleared Secureboot. So no UEFI issues, I am back on track without a USB Wifi stick. 

I saw most of the laptop with realtek rtl8822ce card, has issues with WSL2 and Hyper-V. Hope HP or Reatek or Windows would have to release a proper driver. 
For me, I am happy with AX200 one. 

Thanks for all the suggestions.

**Comment by pankaj-nikam** [comment]
@nithinmohantk , I have Intel AX200 series Wi-Fi card (it was default card), which is why it is stable on my machine.
It is good to hear that your machine is stable now 😃 
Let us hope these two companies sit together and fix these issues so that people don't have to hack in such ways 😄

**Comment by thomas-gg** [comment]
Not sure if I this helps, but I also was having the exact issue (with the AMDRyzenMasterDrive.sys) and I managed to get around the restart loop by following this [about page](https://docs.microsoft.com/en-us/windows/wsl/about "About Windows Subsysyem Linux") and therefore this [video](https://youtu.be/MrZolfGm8Zk?t=504 "WSL2: Code faster on the Windows Subsystem for Linux").
1. latest version of Windows
2. start menu --> turn windows features on or off --> enable Virtual Machine Platform and Windows Subsystem for Linux (restart computer)     DO THIS INSTEAD OF THE COMMAND WHICH CAUSES REBOOT LOOP. (for some reason this avoids the loop even though I will admit I thought this would do the same thing as that command)
3. Open Powershell and type "wsl --set-default-version 2"
4. Open Powershell and type wsl -l -v to confirm you had the ubuntu with wsl version 1 (if you had ubuntu previously installed) and uninstall ubuntu
5. You should be able to install the version of Ubuntu you want from the Microsoft Store and then restart the powershell terminal and type the same command "wsl -l -v". This will confirm that it is now Ubuntu version 2.

**Comment by nithinmohantk** [comment]
Thanks, Thomas. 
Unfortunately, we are aware of how to setup WSL2 configurations. The problem we are facing is the driver incompatibility with Windows. Especially with 4600h or 4800h series ryzen processors. It is evident in most of the laptops with WSL2 or Virtualization enabled, doing a quick google search could help you with it. Lots of random BSODs.

A similar case I have on my Desktop PC: 
- I have been using WSL2 on my windows PC for nearly 1-2 years, and have had many situations where I have to disable WSL2 to make Windows update work. Fairly saying WSL2 is not stable in  AMD Radeon driver. 
- My desktop is X570 + 3700X and on my recent 20279 insider build. Now my windows updates are blocked BSOD during update install, due to WSL2 again. I have to disable WSL2 completely to make the windows update work again.

**Comment by pankaj-nikam** [comment]
This is something that HP needs to fix:

https://www.reddit.com/r/XMG_gg/comments/kb1p9i/solution_for_hyperv_and_wsl2_issues_on_various/gfeqtpo?utm_source=share&utm_medium=web2x&context=3

XMG released a fix for crashing WSL2.

**Comment by saitejach1998** [comment]
I'm facing a related problem with my Ethernet controller [link](https://github.com/microsoft/WSL/issues/5911) probably because its connected to the same PCIe lane as the Wifi cards in this issue. We all seem to have the same generation of AMD processors. I have spoken to HP India extensively about this issue. The team that receives these complaints/bug reports is just a plain old tech support team and has no extensive knowledge about advanced issues or connection to the people who are responsible for updates and bug fixes. Therefore, There is no way of making the update team aware of such a situation. Maybe folks from other countries can try talking to their HP support and get this issue escalated. 
Since XMG has patched this issue, I'm assuming it's a problem with the OEM software. If not, Is there a channel through which we can contact Microsoft for a fix?

**Comment by pd5rm** [comment]
> For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".

Thanks @uastack. Changing to UEFI boot-style (and rewriting partition structure from MBR to GPT, and replacing the boot loader with a EFI based one) fixed the issue.

This is clearly a BIOS firmware bug on HP's side with 'legacy' style boots. HP has shown **zero** interest in resolving this via my repeated attempts at reaching them via support.

P.S Going to UEFI style boot also resolved some flakiness with AMDGPU driver loading in Linux as well. Yay!

**Comment by thewavelength** [comment]
@pd5rm on the HP Omen 15 Laptop Series, one cannot even enable Secure Boot (thus no need to check to disable it) and UEFI mode seems to be the default :-( Thanks for the hint anyway!

**Comment by pd5rm** [comment]
@thewavelength Yeah,I suspect it was resolved due to switching to UEFI and not the 'secure' boot aspect of UEFI.

**Comment by nithinmohantk** [comment]
For those who are using HP Gaming 15 - ec10xxna series, please check the new bios  F20. It could resolve some of the issues. 

15-ec1001na - https://support.hp.com/ie-en/drivers/selfservice/hp-pavilion-gaming-15-ec1000-laptop-pc-series/32612064/model/34953846?sku=133W8EA
15-ec1051ax - https://support.hp.com/us-en/drivers/selfservice/hp-pavilion-gaming-15-ec1000-laptop-pc-series/32612064/model/3803134

**Comment by pankaj-nikam** [comment]
@nithinmohantk I believe the issue is resolved after the BIOS update. It seems to be working now without any crash. Even the fast startup is working.

**Comment by kanei** [comment]
I was just able to resolve this by disabling the `Enhanced windows biometrics security` option in BIOS.

Lenovo Thinkpad T14s with AMD Ryzen

**Comment by e-mayo** [comment]
Hi @pankaj-nikam and @uastack. Thanks for the discussion. I got the Sam problem and solve it using the indications below. @uastack just for curiosity. How did you figure out it? What roles play security boot? Anyway thanks to you both and everyone on this issue 
> @pankaj-nikam To be clear you do not want legacy boot. You want "Legacy Support **Disable** and Secure Boot Disable" or "Legacy Support **Disable** and Secure Boot Enable".
> 
> A BSOD is different then the issue initially reported in this thread. The issue initially reported and the one I was able to reproduce is that when Virtual Machine Platform is enabled AMD Radeon Graphics fails to load showing, _Windows has stopped this device because it has reported problems. (Code 43)_
> For a BSOD make sure BIOS and drivers are up to date.
> Which platform are you using?

**Comment by pankaj-nikam** [comment]
@e-mayo , what is your laptops model number? Did you check the BIOS update?

**Comment by e-mayo** [comment]
@pankaj-nikam I'm using a Dell Inspiron 13 7375. I solved it  with Legacy Support Disable and Secure Boot Enable. I was wondering How did you find the solution to the his issue? What roles play security boot?

**Comment by uastack** [comment]
@e-mayo Windows 10 and it's security features like Secure Boot were built around UEFI and require a system to be in full UEFI mode. Knowing this I played around with some BIOS settings to see what may work and found that system I was able to to reproduce the issue on where set to CSM (Legacy enabled). If using Windows 10 on a modern system I would recommend having Legacy mode/CSM disable and Secure Boot enabled as that is what Microsoft is focusing on for Windows 10.

**Comment by e-mayo** [comment]
Hi @uastack. Thanks for your response

**Comment by junaideqbal** [comment]
My system is facing the same issue. when enabling "virtual machine platform feature" AMD drivers stopped working.

**System Information**
**Processor:** AMD Ryzen 7 PRO 2700U w/ Radeon Vega Mobile Gfx, 2200 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by igilham** [comment]
I also have a BSOD loop on a brand new HP OMEN Laptop - 15-en0008na Ryzen 4800H system with an Nvidia GPU when I try to enable Windows Virtualization Platform.

Testing the issue has been complicated by This April's Windows update, which also causes an unrecoverable BSOD loop on this machine, and the bug in Windows Recovery Environment whereby it rejects the admin user's password when you try to roll back the broken update or use System Restore.

I will have a dig in the BIOS and see what settings there are to fiddle with.

**Comment by undermark5** [comment]
HP finally released an updated BIOS for my machine (OMEN 15-en000 with 4600H) that at least combined with the latest public Windows version (20H2) seems to make everything work just fine, WiFi, Ethernet controller, and WSL2/Hyper-V

**Comment by thomas-gg** [comment]
@undermark5 please lmk if it also causess the stalls mentioned earlier. I had updated early with the insider program and everything seemed fine until once daily my computer would hang with no error messages.

**Comment by igilham** [comment]
My HP OMEN Laptop - 15-en0008na Ryzen 4800H system has received a new BIOS update today and now seems to be working correctly.

Since installing the new BIOS, I've also found that Windows Update is no longer pushing my device into a BSOD loop with KB5001330. This may not be related.

**Comment by 158Alfetta** [comment]
> For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".
> 
> I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change.

My Elitebook 735 G5 works fine by following your response, thank you a lot!

**Comment by leonardomontes** [comment]
> > For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".
> > I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change.
> 
> My Elitebook 735 G5 works fine by following your response. When turning on Hyper-V, the graphic driver still installed. Thank you a lot!

HP EliteDesk 705 35W G4 Desktop Mini PC - issue solved! thanks a lot!

**Comment by Hau-Hau** [comment]
> 
> 
> > > For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".
> > > I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change.
> > 
> > 
> > My Elitebook 735 G5 works fine by following your response. When turning on Hyper-V, the graphic driver still installed. Thank you a lot!
> 
> HP EliteDesk 705 35W G4 Desktop Mini PC - issue solved! thanks a lot!

HP ProBook 455 G7 - works partially. Drivers works fine, but now I got random computer restarts, even without bsod. (Kernel-Power, The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly).

**Comment by silviucotilici** [comment]
> > > > For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".
> > > > I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change.
> > > 
> > > 
> > > My Elitebook 735 G5 works fine by following your response. When turning on Hyper-V, the graphic driver still installed. Thank you a lot!
> > 
> > 
> > HP EliteDesk 705 35W G4 Desktop Mini PC - issue solved! thanks a lot!
> 
> HP ProBook 455 G7, AMD Ryzen 7 4700U - works partially. Drivers works fine, but now I got random computer restarts, even without bsod. (Kernel-Power, The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly).
> 
> Edit: Problem has been "solved" by using Hibernate option instead of Sleep.

Thanks a lot, guys! You saved me a ton of time!
It also worked for me on a ProBook 455 G7, AMD Ryzen 7 4700U. Not sure if this helped but I also updated Win 10 to the latest version (21H1) and the BIOS to the S79.

**Comment by pd5rm** [comment]
We can close this ticket. @ustack identified the root cause here:https://github.com/microsoft/WSL/issues/5662#issuecomment-732400600

**Comment by IkemNwodo** [comment]
> For those of you with HP systems having this issue, do you have the systems set to "Legacy Support Enable and Secure Boot Disable" (BIOS F10 > Advanced > Secure Boot Configuration). If so try changing to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable".
> 
> I can only reproduce the issue on an HP EliteBook 745 G5 and 745 G6 when set to Legacy Support Enable and Secure Boot Disable. When set to "Legacy Support Disable and Secure Boot Enable" or "Legacy Support Disable and Secure Boot Disable" I do not see the issue. As long as your Windows install is using UEFI you should be able to switch without having to reinstall Windows. If you do have bit locker enabled make sure to suspend or disable before making the change. 

God bless you abundantly 🙏
After over a month I finally found a solution!
Thank you so much
