### ISSUE TITLE
[WSL2 / Windows Insider 20175] Closing stdin not correctly propagated when running win32 process from WSL

### ISSUE THREAD

**Issue by simonferquel** [microsoft/WSL#5664]
# Environment

```none
Windows build number:  10.0.20175.0
Your Distribution version: Ubuntu
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

From a wsl terminal, just type `echo test | cmd.exe /s /c more`. 

#  Expected behavior

On 19041, this prints `test` and gives back control

# Actual behavior

On 20175, this prints `test` then hangs, seemingly waiting for stdin to be closed.

The issue was first reported on Docker Desktop issue tracker, where I drilled down the issue to this stdin close propagation bug: https://github.com/docker/for-win/issues/7808#issuecomment-664406938.

**Comment by SR-Lut3t1um** [comment]
This bug should receive a high priority as this bug prevents Docker from updating thus there are a lot of users who can't work right now.

**Comment by therealkenc** [comment]
> 10.0.20175.0

/dupe #5648
