### ISSUE TITLE
WSL2 Install Stopped working and now errors out with 0x800706d9 : WslRegisterDistributionFailed

### ISSUE THREAD

**Issue by dhruvv** [microsoft/WSL#5666]
# Environment

```none
Windows build number: Windows 10 Home x64, Build 2004
Your Distribution version: Ubuntu 20.04 
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 
```

# Steps to reproduce

Install WSL components from Programs and Features on Windows 10
Install the WSL 2 Upgrade from Microsoft and the Kernel Upgrade.
Install any WSL2 distribution from the Microsoft Store.
Attempt to open it (using in Powershell - `wsl` command or opening Ubuntu from the Start Menu

#  Expected behavior

The WSL Distro installs and prompts for a username/password and has network access. Becomes usable within less than 10 minutes. 

# Actual behavior

I get the message `Installing, this may take a few minutes`
Then `WslRegisterDistribution failed with error code 0x800706d9 : There are no endpoints available from the endpoint mapper`

Have tried the workarounds mentioned in #5331 but no dice, the same error occurs. Have tried rebooting and reinstalling WSL2 components. Same configuration works on my other Windows 10 machine and WSL 2 ubuntu works with no issues.

**Comment by xiaods** [comment]
this is a pain for me too. anyone can give some tips.

**Comment by wwboyer** [comment]
I also have the same issue. I tried the fixes mentioned in #5331 but I continue getting the error whenever I try to convert an existing environment to WSL 2 or install a new WSL 2 environment. My current WSL 1 environment works as expected, however.

**Comment by xiaods** [comment]
@wwboyer WSL2 seems is beta toys. not a production feature.

**Comment by xiaods** [comment]
Windows build number: Windows 10 Professional x64, Build 2004  internal version: 19041.388
Your Distribution version: Ubuntu 20.04 
Error:
I get the message Installing, this may take a few minutes
Then WslRegisterDistribution failed with error code 0x800706d9 : There are no endpoints available from the endpoint mapper

**Comment by therealkenc** [comment]
Likely same #4403. Please [collect wsl logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and link the feedback item.

**Comment by jeffreyulatan** [comment]
Hey there, I'm bumping this up as I was able to reproduce the exact problem on my end. 

Error:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 There are no more endpoints available from the endpoint mapper.

Press any key to continue...
```

_Microsoft Windows 10 Enterprise
10.0.19041 Build 19041_

**Steps I've done to replicate the error:** 

1. Virtual Machine Platform Enabled via Control Panel
2. Windows Subsystem for Linux Enabled via Control Panel
3. Installed WSL2 MSI Update from https://aka.ms/wsl2kernel
4. Set WSL to WSL2 via Powershell **wsl --set-default-version 2**
5. V-TD Enabled via Bios
6. Distro Ubuntu 20.04 LTS via Microsoft Store

Solutions I've tried

via Powershell 
**Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux.**
**dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart**
**dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart**
**wsl --set-default-version 2**

If anyone has any suggestions feel free to reply!

**Comment by xiaods** [comment]
@jeffreyulatan replicate the error steps is correct,  I have same errors.

**Comment by jeffreyulatan** [comment]
For those still having a problem I fixed the problem by manually updating via DISM the newest source utilizing Microsoft USB creation tool. 

**DISM /Online /Cleanup-Image /RestoreHealth Source:WIM:X:/sources/install.wim**

**Comment by xiaods** [comment]
> For those still having a problem I fixed the problem by manually updating via DISM the newest source utilizing Microsoft USB creation tool.
> 
> **DISM /Online /Cleanup-Image /RestoreHealth Source:WIM:X:/sources/install.wim**

I use powershell admin shell to run this command, it failed:

```console
DISM /Online /Cleanup-Image /RestoreHealth Source:WIM:X:/sources/install.wim
```

**Comment by jeffreyulatan** [comment]
> > For those still having a problem I fixed the problem by manually updating via DISM the newest source utilizing Microsoft USB creation tool.
> > 
> > **DISM /Online /Cleanup-Image /RestoreHealth Source:WIM:X:/sources/install.wim**
> 
> I use powershell admin shell to run this command, it failed:
> 
> ```console
> DISM /Online /Cleanup-Image /RestoreHealth Source:WIM:X:/sources/install.wim
> ```

You have to replace X: with your mounted DISM image path. Alternatively just download the official Microsoft USB creation media tool and click Update this Computer, it does the same thing.

**Comment by AEteve** [comment]
Issue still appears when trying to install Ubuntu 24.04 on wsl 2 on windows 11

**Comment by titus-k-m365group** [comment]
> Issue still appears when trying to install Ubuntu 24.04 on wsl 2 on windows 11

How did you have this solved?

**Comment by AEteve** [comment]
Issue got resolve after a microsoft update, I was able to install it

**Comment by titus-k-m365group** [comment]
Okay great, I also had to update windows and ensured Windows Hypervisor platform and Virtual machine platform were on in Windows Features on and Off

> Issue got resolve after a Microsoft update, I was able to install it

**Comment by udoletsplay** [comment]
Herunterladen: Klicke auf diesen direkten Link von Microsoft, um das korrekte Update-Paket (wsl_update_x64.msi) zu laden: [WSL2 Linux-Kernel-Updatepaket für x64-Computer](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi&authuser=1)
