### ISSUE TITLE
Interoperability for WSL symlinks accessed via \\wsl$

### ISSUE THREAD

**Issue by segrey** [microsoft/WSL#5670]
**Is your feature request related to a problem? Please describe.**

Linux symlinks cannot be resolved in a Windows applications accessing files on Linux partition via `\\wsl$\`.
There are many benefits from this feature. One of those is that it would help to develop project located in WSL:
For example, monorepo projects using Yarn workspaces or Lerna use symlinks to setup dependent workspace packages. Inability to resolve WSL symlinks from `\\wsl$\` makes it hard to open such projects in WebStorm / IntelliJ IDEA.

**Describe the solution you'd like**

WSL symlinks created in mounted Windows directories (e.g. under `/mnt/c`) can be resolved/accessed by a Windows application as expected. Would be great if it would work the same for WSL symlinks created in Linux partitions, so it'd be possible to access symlinks via `\\wsl$\`.

**Describe alternatives you've considered**

As a workaround, it's possible to setup a Samba share for directories from Linux partitions, and WSL symlinks are resolved in this case correctly. This might help in some cases, and it might not help in others (for example, it doesn't help to develop a project located in WSL with WebStorm / IntelliJ IDEA).

**Additional context**

This might be a duplicate of https://github.com/microsoft/WSL/issues/5118, but it describes a quite specific case, so I decided to file a more general issue for this feature just in case. Feel free to close this one if needed.

**Comment by therealkenc** [comment]
> This might be a duplicate of #5118, but it describes a quite specific case,

Mentioning something specific is usually a good thing in that the uses-cases help drive motivation. But yes, yours is the same ask /dupe #5118. [The two issues wouldn't get closed independently in the event \\wsl$ symlinks got implemented.]

> As a workaround, it's possible to setup a Samba share

That's a good approach. Another bit hammer approach is to run Linux WebStorm/IntelliJ under X11 until #938 ships.

**Comment by segrey** [comment]
@therealkenc Thanks for the update! Are there any plans to add this feature?
Unfortunately, using Samba share is impossible for IntelliJ, because in this case local (Windows) paths cannot be simply mapped to remote (WSL) paths and vice versa.

Yes, IntelliJ under X11 works, but UI is blurry. It looks better on Windows.
