### ISSUE TITLE
send a UDP packet to 255.255.255.255 on host os failed when wsl installed

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/WSL#5671]
# Environment
Windows build number:Microsoft Windows NT 10.0.19041.0
Your Distribution version: none
the issue is on WSL 2 and WSL 1

# Steps to reproduce

1. install windows 10 2004
2. send a UDP packet to 255.255.255.255 on the host os by any software you want
3. install Windows Subsystem for Linux
4. send a UDP packet to 255.255.255.255 on the host os  by any software you want

#  Expected behavior
two UDP packets can be captured on Wireshark 

# Actual behavior
The step 1 UDP packet can be captured on Wireshark 
The step 2 UDP packet can't be captured on Wireshark

**Comment by therealkenc** [comment]
> Your Distribution version: none
> the issue is on WSL 2 and WSL 1
> any software you want

In a less friendly place that would be two strikes on #5667. [And there's only two.] Let's pretend you answered: Ubuntu 20.04, WSL2, and `socat`.

![image](https://user-images.githubusercontent.com/7049700/88752134-fe553b00-d10d-11ea-8ec7-407bed766da3.png)


That wireshark part of the screencap above is supposed to represent an absence of traffic going out the physical NIC, watching from the Windows side. Normal (non-broadcast) UDP traffic goes out, natch. As a practical matter, anything that wants to broadcast is going to suffer #4825 as well, independent of broadcast. Blocks implementation of DHCP (and else) for anyone venturing to try. The submission is not novel, but I can't find a good dupe target.

**Comment by xspeed1989** [comment]
@therealkenc 
```bash
PS C:\Windows\system32> route PRINT -4
===========================================================================
Interface List
  8...00 ff 4f 2e cb 33 ......TAP-Windows Adapter V9
 25...00 15 5d c9 65 78 ......Hyper-V Virtual Ethernet Adapter
  6...00 e0 6e 68 00 fa ......Realtek PCIe GbE Family Controller
  1...........................Software Loopback Interface 1
 36...00 15 5d 8b db 2a ......Hyper-V Virtual Ethernet Adapter #2
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    172.16.60.254     172.16.60.81    291
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      172.16.60.0    255.255.252.0         On-link      172.16.60.81    291
     172.16.60.81  255.255.255.255         On-link      172.16.60.81    291
    172.16.63.255  255.255.255.255         On-link      172.16.60.81    291
     172.20.240.0    255.255.240.0         On-link      172.20.240.1    271
     172.20.240.1  255.255.255.255         On-link      172.20.240.1    271
   172.20.255.255  255.255.255.255         On-link      172.20.240.1    271
      172.21.64.0    255.255.240.0         On-link       172.21.64.1   5256
      172.21.64.1  255.255.255.255         On-link       172.21.64.1   5256
    172.21.79.255  255.255.255.255         On-link       172.21.64.1   5256
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link      172.16.60.81    291
        224.0.0.0        240.0.0.0         On-link      172.20.240.1    271
        224.0.0.0        240.0.0.0         On-link       172.21.64.1   5256
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link      172.16.60.81    291
  **255.255.255.255  255.255.255.255         On-link      172.20.240.1    271**
  255.255.255.255  255.255.255.255         On-link       172.21.64.1   5256
===========================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
          0.0.0.0          0.0.0.0    172.16.60.254  Default
===========================================================================
```
Look at the bold part, the metric is lower than _172.16.60.81    291_
if change 291 to lower than 271 or change 271 to greater than 291 
the issue is not existed

**Comment by craigloewen-msft** [comment]
@xspeed1989 could you take a trace for us using feedback hub for this issue? [Instructions here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) on how to do so. And then could you link us to the feedback hub item? 

Thanks!

**Comment by xspeed1989** [comment]
> @xspeed1989 could you take a trace for us using feedback hub for this issue? [Instructions here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) on how to do so. And then could you link us to the feedback hub item?
> 
> Thanks!

OK I will do it

**Comment by BrianGithubber** [comment]
We suspect that winnat may be at fault.  Is it possible to attempt this simple repro to confirm/deny that hypothesis?

Just setup the repro.  Then do:
net stop winnat

Then:
sc query winnat

to make sure it is stopped.

Then see if the repro still happens.   Note that you'll have to reboot your machine afterwards to get it back into the normal state.

**Comment by therealkenc** [comment]
Started or stopped `winnat` appears to have no effect here on WSL2. A dive of WSL1 seems okay started or stopped. This is on 20185.

WSL2:

![image](https://user-images.githubusercontent.com/7049700/89490803-8e286400-d762-11ea-89a7-a7a0f29d82fb.png)

WSL1 (`winnat` still stopped below, but get same result started):

![image](https://user-images.githubusercontent.com/7049700/89490870-b617c780-d762-11ea-93f6-72ca2c641cc6.png)

With reflection I'm not fully convinced _my repro_ is the same as the what the OP is intending to describe. His "on host os" (read: On Windows) can be taken at its word. If your 'suspect' is Windows Hypervisor Platform related (contrast WSL) I can do my repro under a different cover and go away.

**Comment by therealkenc** [comment]
@xspeed1989  please try `net stop winnat` and see if that helps your scenario.

**Comment by BWhitten** [comment]
I have the same issue so perhaps can provide the information needed.

Following the repro above with `net stop winnat` doesn't resolve sending the broadcasts from within WLS2
![image](https://user-images.githubusercontent.com/962974/102769691-e9a66780-437a-11eb-807f-daded5ea7868.png)

My problem case being slightly different, with WSL2 installed, sending a broadcast from the host and receiving direct replies on the host.
The problem appears to be in the sending of a broadcast as I am able to receive broadcasts on the box with WSL2 installed.

The following is a working UDP broadcast from a machine without WSL2 (or virtualbox) installed .
![image](https://user-images.githubusercontent.com/962974/102771449-d34ddb00-437d-11eb-8a72-1d93b63e998e.png)
