### ISSUE TITLE
wsl command and "linux shell here" option in shift-rightclick menu crash immediately after open

### ISSUE THREAD

**Issue by TangdizhiH** [microsoft/WSL#5672]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: wsl2
```

# Steps to reproduce
There are two independent action I mentioned while I think they may corelate with each other.

First, use win+s to search "wsl" and enter, there would be a window seems to be the terminal and crashed immediately

Second, find a folder and "shift+right_click" and click "linux shell here"(I'm not certain about the exact name since its in another language), and the termian appears and crased immediately

#  Expected behavior and actual behavior

I don't exactly know what wsl.exe command would produce, but I happened to download the fluent terminal, which access wsl through wsl.exe command, and I cannot use it because it reports "session was closed" every time I try to open a  wsl terminal, so I got the impression that my wsl.exe is broken

For the second one, the terminal was expected, but it crashed :(

**Comment by benhillis** [comment]
What happens when you run wsl from the command prompt?
