### ISSUE TITLE
Docker over WSL2 without any distros installed

### ISSUE THREAD

**Issue by turowicz** [microsoft/WSL#5675]
I'm running my linux docker containers using the WSL2 edition of Docker Desktop. I don't have any WSL2 distros installed at all, hence my questions:

- how is this thing even working?
- how can I apply the WSL2 disk performance workaround mentioned in https://github.com/microsoft/WSL/issues/4668#issuecomment-553173079?

**Comment by turowicz** [comment]
![image](https://user-images.githubusercontent.com/1055391/88805319-47a99700-d1af-11ea-9440-ca0347f11f5f.png)

Proof

**Comment by turowicz** [comment]
I will experiment by putting my workspace folder in \\wsl\docker-desktop-data

**Comment by simonferquel** [comment]
Docker Desktop creates its own distros to work within WSL2. However, storing your files directly within those distros is not supported.

The best way to make things work, is to install a distro from the store (Ubuntu being the most popular), make sure it is running on WSL 2 (using `wsl.exe --set-version`) and use docker from your Ubuntu's shell.

**Comment by turowicz** [comment]
@simonferquel that way I can't use Visual Studio Code with the Remote - Containers extension to develop on linux while using windows. I need docker containers in order to switch between frameworks etc.

**Comment by ad-on-is** [comment]
> @simonferquel that way I can't use Visual Studio Code with the Remote - Containers extension to develop on linux while using windows. I need docker containers in order to switch between frameworks etc.

Actually you can do that!

I'm "orchestrating" all my Docker-containers within WSL2 (Ubuntu 20.04). That's where my `docker-compose.yml`  is located, which mounts Linux-folders like `~/some/path` into the containers, and also where I execute commands like `docker run -v ~/path/:/some/path`, etc..

If I want to work inside one of the containers from VSCode (Windows), they're all listed there.

![image](https://user-images.githubusercontent.com/9553253/88900747-21880380-d250-11ea-91b9-bb03dee9c958.png)

**Comment by simonferquel** [comment]
You can also run vs code in "Remote - WSL" mode, and have it work just like if you were running vs code locally (including working with development containers).

**Comment by turowicz** [comment]
@ad-on-is I will trying attaching, thanks it seems like a viable solution.

@simonferquel - WSL mode doesn't leverage .devcontainer dockerfiles.

**Comment by turowicz** [comment]
@ad-on-is it works. Do you have a workaround for having settings and extensions installed in the container automatically similar to `devcontainer.json`?

**Comment by ad-on-is** [comment]
@turowicz Unfortunately, I can't help you out with that, since I don't work with remote containers extension in VSCode, I only use the remote WSL extension.

**Comment by turowicz** [comment]
`Open Repository in a Container` seems to do the job perfectly well!

It only required starting an ssh-agent on Windows and adding the default credential to it.

**Comment by rahiparsi-stemcell** [comment]
@simonferquel Is this behaviour (that Docker Desktop creates its own distros ...) documented somewhere and may I have the links?
> Docker Desktop creates its own distros to work within WSL2. However, storing your files directly within those distros is not supported.
> 
> The best way to make things work, is to install a distro from the store (Ubuntu being the most popular), make sure it is running on WSL 2 (using `wsl.exe --set-version`) and use docker from your Ubuntu's shell.
