### ISSUE TITLE
No ethernet media detected by windows after enabling Virtual Machine Platform

### ISSUE THREAD

**Issue by TheRealDarkCoder** [microsoft/WSL#5676]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I tried enabling Windows Subsystem for Linux and Virtual Machine Platform from "Programs and Features". After the system rebooted, Windows would show I'm not connected to the internet/ethernet cable is unplugged.
![Screenshot_2](https://user-images.githubusercontent.com/18534358/88830931-74ca6980-d1f0-11ea-99cf-887ac6bb8bd6.png)
![Screenshot_3](https://user-images.githubusercontent.com/18534358/88830951-7a27b400-d1f0-11ea-93c1-dd6df158e942.png)
At first I thought it was a hardware issue and I tried changing my ethernet cable (which connects to a wireless router) which didn't work. So I disabled WSL and VMP and it was normal again.
After further poking around, I found out WSL1 works just fine, i was able to enable just WSL and run Ubuntu. However, the problem returns as soon as I enable VMP.

#  Expected behavior

Windows should detect the connected ethernet cable. 
![image](https://user-images.githubusercontent.com/18534358/88831327-fde1a080-d1f0-11ea-8454-40437859f88d.png)
(Above screenshot is from WSL enabled but VMP disabled)
# Actual behavior

Windows doesn't detect any ethernet media.
![image](https://user-images.githubusercontent.com/18534358/88831342-05a14500-d1f1-11ea-9ef9-0092842f8fd8.png)
(Above screenshot is from both WSL and VMP enabled)

**Comment by licanhua** [comment]
Look like a dup of #5586. 
@therealkenc , What kind of log do we want to collect? reboot happens when enabling VMP and I don't think feedback hub will work.

**Comment by therealkenc** [comment]
> Look like a dup of #5586.

Possibly. Probably even. But over there, the user had a working VMP/WSL at some point, and then did unknown (and unknowable) steps. Was WSL2 working for you at some point similarly, or was this your first go at enabling VMP (at WSL) in Programs and Features?

>  I don't think feedback hub will work.

Yes that classic catch-22 predates feedback hub (in the general sense).

You could scour the Windows log in hopes something jumps out. You can also try cross-posting in the [windows hyper-v Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-server-hyper-v.html). If you do, enabling VMP but not enabling (and not mentioning) WSL is probably a good strategy (it's what I'd do). **If** your network is live with VMP enabled and WSL disabled, that gets more interesting.

**Comment by TheRealDarkCoder** [comment]
No it never worked for me, this is the first time enabling WSL/VMP.

If this is kept open, I'll look into the logs and try the combinations of VMP enabled and WSL disabled and other future suggestions and post updates here.

**Comment by therealkenc** [comment]
Updating your Killer E2200 [drivers](https://support.killernetworking.com/software/) is maybe worth a shot (at random).

**Comment by TheRealDarkCoder** [comment]
I have already tried that. It's already at the latest version, I've tried uninstalling and reinstalling it again while VMP was on and then again when it was off, no changes.

**Comment by TheRealDarkCoder** [comment]
Okay here are some updates regarding the issue.

1) I updated the driver from Killer website (After removing the old driver using their uninstaller too), but unfortunately, the issue persisted. 


2) While rebooting and testing and looking for more artifacts, today I stumbled across this.
![Screenshot_5](https://user-images.githubusercontent.com/18534358/88919720-739b4a00-d28d-11ea-962a-c02ddee64239.png)

`ipconfig` apparently now shows a vEthernet adapter for HyperV. This was absent before as you can see from the first comment's screenshot.
![Screenshot_7](https://user-images.githubusercontent.com/18534358/88919739-7e55df00-d28d-11ea-82a0-95a5bc783067.png)



At first I thought it was because I enabled "Hyper-V manager" from programs and features.
![Screenshot_8](https://user-images.githubusercontent.com/18534358/88919792-8e6dbe80-d28d-11ea-9b7d-8c759861babe.png)
(`ipconfig /all`)

But it stayed there even when I disabled it. So I assume it's from the driver update but I'm not exactly sure what caused this.
However, the actual ethernet is still disconnected.

![Screenshot_6](https://user-images.githubusercontent.com/18534358/88920170-31263d00-d28e-11ea-8123-09f1a1ab03b9.png)


3) After seeing that and also enabling Hyper-V manager, i decided to look into the Hyper-V Manager Panel. There I found this configuration.
![Screenshot_4](https://user-images.githubusercontent.com/18534358/88919968-d55bb400-d28d-11ea-90a0-779846d63f8f.png)


Being new to Hyper-V I don't know how to make sense of this, but posting it here in case something seems off here.


4) Finally, I've ventured into the event logs. I don't know what I'm looking for but I didn't find any Errors or Critical other than some Windows SPP stating some kind of license activation failure due to no internet connection. And yes, I found some "information" logs related to Hyper-V stating that Hyper-V started successfully.

**Comment by TheRealDarkCoder** [comment]
Another quick update:

While looking into Windows Network Settings and properties, I found this:

![hw props](https://user-images.githubusercontent.com/18534358/89062858-ff45d100-d388-11ea-87f5-fd641a466cee.png)

This is when VMP's enabled, as you can see, it says my adapter is disconnected. But the IpV4 address seems set and weird.
Because here's a screenshot from when VMP's disabled and ethernet's working:

![hw props working](https://user-images.githubusercontent.com/18534358/89062907-18e71880-d389-11ea-9c1a-8f59bad5b356.png)


As you can see, my router assigned IP is always 192.168.0.* range, could this be triggering some sort of DHCP Ip assignment issue and the router is ignoring my connection and so Windows says I'm disconnected?

**Comment by TheRealDarkCoder** [comment]
Asking from some clarification here, So today I decided to launch up the distro and look at it's network configuration and compare it with the host OS one.

And then I found out this:

![same ip both](https://user-images.githubusercontent.com/18534358/89106535-75f7d280-d44c-11ea-81c8-ad2ac4b49921.png)


I'm a networking noob so I'm assuming I'm wrong. 
But both the linux and the Host OS seems to see the same adapters, and they have the same configuration. Is this expected behavior? Because I thought there was some kind of network switch virtualized between the host OS and the hyper-v linux, are they supposed to share the same adapter and configuration? And even if so, where is this 169.254.111.26/16 subnet coming from?

Note: The screenshot is taken with both VMP and WSL enabled. For further comparison, here's a ifconfig vs ipconfig when VMP is disabled but WSL is enabled.

`$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.108  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::f076:8f50:a3d1:6f1a  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 44:8a:5b:82:31:e2  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=65<UP,RUNNING>  mtu 1472
        unspec [NONE SET]  netmask 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
        inet6 2001:0:284a:364:34b8:3a3f:989f:9725  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::34b8:3a3f:989f:9725  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 00:00:00:00:00:00  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0xfe<compat,link,site,host>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

==========================


Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-G5P156K
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Killer E2200 Gigabit Ethernet Controller
   Physical Address. . . . . . . . . : 44-8A-5B-82-31-E2
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::f076:8f50:a3d1:6f1a%3(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.0.108(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Saturday, August 1, 2020 10:46:57 PM
   Lease Expires . . . . . . . . . . : Wednesday, September 8, 2156 5:21:48 AM
   Default Gateway . . . . . . . . . : 192.168.0.1
   DHCP Server . . . . . . . . . . . : 192.168.0.1
   DHCPv6 IAID . . . . . . . . . . . : 105155163
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-86-EC-A8-44-8A-5B-82-31-E2
   DNS Servers . . . . . . . . . . . : 192.168.0.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:0:284a:364:34b8:3a3f:989f:9725(Preferred)
   Link-local IPv6 Address . . . . . : fe80::34b8:3a3f:989f:9725%10(Preferred)
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 167772160
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-86-EC-A8-44-8A-5B-82-31-E2
   NetBIOS over Tcpip. . . . . . . . : Disabled`

And guess what, it's the same behavior except some more information I don't understand. And hence why I assume I'm wrong.

Additional information:
1) Distributions I used for testing: Ubuntu-20.04 from Windows Store and Arch-WSL from https://github.com/yuk7/ArchWSL 
 same behavior in both.
2) I noticed my ethernet adapter also assigned IpV6 address even though my NAT/Router doesn't support/provide Ipv6. So I disabled IPv6 from Adapter properties but it didn't improve the situation other than removing the IPV6 address from the configuration.
3) I did set wsl default version to 2 before jumping into the distros.

**Comment by therealkenc** [comment]
> Is this expected behavior?

On WSL1, yes. On WSL2, no.

> And even if so, where is this 169.254.111.26/16 subnet coming from?

That's your [link-local address](https://en.wikipedia.org/wiki/Link-local_address). TL;DR (quoth) "In IPv4, link-local addresses are normally only used when no external, stateful mechanism of address configuration exists, such as the Dynamic Host Configuration Protocol (DHCP), or when another primary configuration method has failed."

Which is you.

> I did set wsl default version to 2 before jumping into the distros.

Setting the default WSL version to 2 does not change the currently installed WSL version to 2. That result from `ifconfig` above was performed on WSL1. Which is a good thing, because you don't want WSL2 given that enabling Virtual Machine Platform takes down your Windows networking.

**Comment by Techno-Disaster** [comment]
@TheRealDarkCoder were you able to fix this?

**Comment by TheRealDarkCoder** [comment]
> @TheRealDarkCoder were you able to fix this?

No. But I will try downgrading to 1903 or reset 2004 windows to see if that does anything since I moved to a new PC.

**Comment by StephanWard** [comment]
I had similar issue. I did two steps. Upon restart enter bios by F2. Under virtualization I/O; I disable it. I saved. Upon restart, still had no internet. While PC was running, I unplugged network adapter and plugged it back in. Internet now works, but receive a new error for my AVD

 " "unexpected '-prop' value ('monodroid.avdname=pixel_2_pie_9_0_-_api_28'), only 'qemu.' properties are supported
WARNING: unexpected '-prop' value ('emu.uuid=bc18601a-3027-4e3f-8c3f-0bdfe71e870f'), only 'qemu.' "

**Comment by SilentTaker** [comment]
I'm going to edit this when I get back to my computer, there are a few (and I mean 3-4 things) that are much simpler and worked for me. Enabling WSL2 completely shut off my Ethernet connection as well. I did find a solution in about 15 minutes. My own tinkering as no one seems to have a solution. There is no real need for cli use except to confirm or deny internet access. 

When I get back to my computer I'll upload screenshots to my feature settings which let Ethernet configure for both WSL2 and Windows allowing me to install Ubuntu 22.04 LTS.
