### ISSUE TITLE
Serial Port Strange Data , Data Fixes aftter Run in Windows

### ISSUE THREAD

**Issue by Erdemhan** [microsoft/WSL#5677]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL1
```

Hi i am trying to read serial port data which is providing by canbus. 

I get strange datas like these:
![Screenshot_1](https://user-images.githubusercontent.com/43721630/88832895-24e0a800-d1da-11ea-819d-ecc7b1d582cb.png)

The code that i read data:
```
import serial

serialPort = serial.Serial('/dev/ttyS3')

serialString = ""                           # Used to hold data coming over UART


while(1):

    # Wait until there is data waiting in the serial buffer
    if(serialPort.in_waiting > 0):

        # Read data out of the buffer until a carraige return / new line is found
        serialString = serialPort.readline()

        # Print the contents of the serial data
        print(serialString).decode('Ascii')
```

But when i run windows version of same code in windows i get true datas in windows and after run 1 times in windows i get true datas in linux WSL. When i un-plug and plug usb  linux data breaks again.

Code running in windows:
![Screenshot_2](https://user-images.githubusercontent.com/43721630/88833615-31b1cb80-d1db-11ea-89c8-a6c72b8f8259.png)
The code on windows:

```
import serial

serialPort = serial.Serial(port = "COM3")

serialString = ""                           # Used to hold data coming over UART


while(1):

    # Wait until there is data waiting in the serial buffer
    if(serialPort.in_waiting > 0):

        # Read data out of the buffer until a carraige return / new line is found
        serialString = serialPort.readline()

        # Print the contents of the serial data
        print(serialString)

        # Tell the device connected over the serial port that we recevied the data!
        # The b at the beginning is used to indicate bytes!
        serialPort.write(b"Thank you for sending data \r\n")

```

Code running in linux wsl after run 1 times in windows:

![Screenshot_3](https://user-images.githubusercontent.com/43721630/88833781-7b021b00-d1db-11ea-9033-3e4590139819.png)

**Comment by therealkenc** [comment]
This _might_ be recoverable. You've got data coming down the wire into WSL1 (which is much better than not). Try setting your `/dev/ttyS3` parameters explicitly with [`stty(1)`](https://man7.org/linux/man-pages/man1/stty.1.html) before running your python script. Also a useful thing to try is run `stty -a` before and after your "run 1 times in windows" to see what (if anything) changed.

**Comment by Erdemhan** [comment]
> 
> 
> This _might_ be recoverable. You've got data coming down the wire into WSL1 (which is much better than not). Try setting your `/dev/ttyS3` parameters explicitly with [`stty(1)`](https://man7.org/linux/man-pages/man1/stty.1.html) before running your python script. Also a useful thing to try is run `stty -a` before and after your "run 1 times in windows" to see what (if anything) changed.

Thanks it was about stopbits when i set stopbits=2 (-cstopb from stty) it solved.
