### ISSUE TITLE
"?" is showed when display language is not English and there is error during distro installation

### ISSUE THREAD

**Issue by licanhua** [microsoft/WSL#5679]
The output is extracted from #5331. most likely it's related to utf8 and utf16. I guess stderr is set to uft8 

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 ??????????????????
Press any key to continue...
```

**Comment by therealkenc** [comment]
>  related to utf8 and utf16

Might be. Whatever the cause, the lack of internationalization of the error text (contrast the "There are no endpoints available from the endpoint mapper" WslRegisterDistribution fail proper) is a legit enough ask. What is your Windows build (`C:\> ver`) for the save from a [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md) close. And your Windows language settings as the missing repro step.

**Comment by 0xbadfca11** [comment]
It is not within WSL that is displaying that error message.
https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/messages.mc#L3
https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/WslApiLoader.cpp#L48
https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/Helpers.cpp#L52
I'm sure it's
https://github.com/microsoft/WSL-DistroLauncher/issues/44

**Comment by therealkenc** [comment]
0xbadfca11's interpretation seems plausible enough. Track over in microsoft/WSL-DistroLauncher#44.
