### ISSUE TITLE
Failed to install cuda toolkit in WSL following advice from nvidia

### ISSUE THREAD

**Issue by oriko-mikuni** [microsoft/WSL#5682]
# Environment

```none
Windows build number: 20175
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 [Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP]
```

# Steps to reproduce

admi@DESKTOP-HTO6PH5:/mnt/c/Users/PC-ZHB$ sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
```none
Executing: /tmp/apt-key-gpghome.GrDft59DIf/gpg.1.sh --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
gpg: requesting key from 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub'
gpg: key F60F4B3D7FA2AF80: public key "cudatools <cudatools@nvidia.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
admi@DESKTOP-HTO6PH5:/mnt/c/Users/PC-ZHB$ sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
admi@DESKTOP-HTO6PH5:/mnt/c/Users/PC-ZHB$ sudo apt-get update
```none
Hit:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease
Hit:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease
Hit:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports InRelease
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease
Hit:5 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease
Hit:6 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-proposed InRelease
Ign:7 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Get:8 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Release [697 B]
Get:9 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Release.gpg [836 B]
Ign:10 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Packages
Ign:10 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Packages
Ign:10 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Packages
Err:10 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Packages
  404  Not Found [IP: 36.153.62.132 443]
Fetched 1533 B in 13s (118 B/s)
Reading package lists... Done
E: Failed to fetch https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64/by-hash/SHA256/4e75b4a2fd84a45853a14ea35e158e3e8528519b1644ee779b5137ee9ef16220  404  Not Found [IP: 36.153.62.132 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

#  Expected behavior

following the instruction from https://docs.nvidia.com/cuda/wsl-user-guide/index.html to install cuda 10.0, and with windows 10 insider build 20175, nvidia driver for wsl2 installed, wsl2 with core 4.19.121, it should be working.

# Actual behavior

it failed to work due to 404 not found issue.

**Comment by oriko-mikuni** [comment]
cuda is used on pytorch, which is for my machine learning program.

**Comment by therealkenc** [comment]
The 404 is because the file `...by-hash/SHA256/4e75b4a2fd84a45853....` is not there.

Cannot reproduce here.

![image](https://user-images.githubusercontent.com/7049700/88901549-c7fae700-d205-11ea-8ef3-ee03c13b7b93.png)

**Comment by oriko-mikuni** [comment]
by using runfile, instead of deb in that instruction, it no longer 404ed... and i am running my machine learning program now.

**Comment by oriko-mikuni** [comment]
still don't know why the deb way recommended by that instruction didn't work, but it doesn't matter for me now. thanks! @therealkenc

**Comment by callmeYe** [comment]
> by using runfile, instead of deb in that instruction, it no longer 404ed... and i am running my machine learning program now.

where is the runfile？

**Comment by zzjin** [comment]
When following the cuda+wsl instruction, you should replace `nvida.com` to redirect location: `nvida.cn` as shown.
Which means:
```
apt-key adv --fetch-keys http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sh -c 'echo "deb http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
```
or the gpg key file will be wrong. After change worked for me.

**Comment by necloux** [comment]
> When following the cuda+wsl instruction, you should replace `nvida.com` to redirect location: `nvida.cn` as shown.
> Which means:
> 
> ```
> apt-key adv --fetch-keys http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
> sh -c 'echo "deb http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
> ```
> 
> or the gpg key file will be wrong. After change worked for me.
> 
> For others who already have run add ` nvida.com` gpg key, run: `sudo apt-key adv --refresh-keys` before `apt get`.

I got the same issue and tied with this instruction, problem solved! Thanks!

**Comment by NEK-ROO** [comment]
> When following the cuda+wsl instruction, you should replace `nvida.com` to redirect location: `nvida.cn` as shown.
> Which means:
> 
> ```
> apt-key adv --fetch-keys http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
> sh -c 'echo "deb http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
> ```
> 
> or the gpg key file will be wrong. After change worked for me.
> 
> For others who already have run add ` nvida.com` gpg key, run: `sudo apt-key adv --refresh-keys` before `apt get`.

life savior!
