### ISSUE TITLE
Unable to set default version to 2

### ISSUE THREAD

**Issue by lpabon** [microsoft/WSL#5687]
# Environment

```none
Windows build number: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: none
Whether the issue is on WSL 2 and/or WSL 1: NA
```

# Steps to reproduce

I have a Razer 15 RZ09-03286 and I have reproduced this issue multiple times:

1. Full PC Reset
1. Update to the latest Windows 10 1909
1. Download update to Windows 10 2004: https://www.microsoft.com/en-us/software-download/windows10
1. Apply the upgrade (wait many hours to upgrade)
1. Follow the two first steps on https://docs.microsoft.com/en-us/windows/wsl/install-win10#install-the-windows-subsystem-for-linux 
1. Reboot
1. Run the command: `wsl --set-default-version 2`

I get:

```
PS C:\WINDOWS\system32> wsl --set-default-version 2
Error: 0x1bc
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```

FYI, I do have it working on my Gigabyte Aero 14.

**Comment by OdelinT** [comment]
Can you send the link of the other thread? This one was referenced first on google, I guess I won't be the last to want the lastest informations

**Comment by fenilmpatel** [comment]
same on my machine msi windows
 Edition	Windows 10 Home Single Language
Version	20H2
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0
