### ISSUE TITLE
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

### ISSUE THREAD

**Issue by Makgerland** [microsoft/WSL#5689]
But in my desktop have to installed already. How can fix this?
<img width="733" alt="Capture1" src="https://user-images.githubusercontent.com/40732947/88999286-4d71ba80-d31e-11ea-867f-e7d8cff65af8.PNG">
<img width="865" alt="Capture2" src="https://user-images.githubusercontent.com/40732947/88999292-4f3b7e00-d31e-11ea-97b8-a78f1b8ead02.PNG">
<img width="347" alt="Capture3" src="https://user-images.githubusercontent.com/40732947/88999299-51054180-d31e-11ea-8661-c896ef312f9c.PNG">

**Comment by licanhua** [comment]
I guess you may not enable VT in bios, your hardware doesn't support hyperv or you didn't enable nested virtualization(for VM).

[Offical document to enable virtual machine platform](
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#please-enable-the-virtual-machine-platform-windows-feature-and-ensure-virtualization-is-enabled-in-the-bios)

https://github.com/microsoft/WSL/issues/5014#issuecomment-646857507

**Comment by therealkenc** [comment]
Or #4120

**Comment by BnH2081** [comment]
> But in my desktop have to installed already. How can fix this?
> <img alt="Capture1" width="733" src="https://user-images.githubusercontent.com/40732947/88999286-4d71ba80-d31e-11ea-867f-e7d8cff65af8.PNG">
> <img alt="Capture2" width="865" src="https://user-images.githubusercontent.com/40732947/88999292-4f3b7e00-d31e-11ea-97b8-a78f1b8ead02.PNG">
> <img alt="Capture3" width="347" src="https://user-images.githubusercontent.com/40732947/88999299-51054180-d31e-11ea-8661-c896ef312f9c.PNG">

hi bro. did you find your probleme answer?
if yes please tell me, i have this priblem too

**Comment by codeict** [comment]
> I guess you may not enable VT in bios, your hardware doesn't support hyperv or you didn't enable nested virtualization(for VM).
> 
> [Offical document to enable virtual machine platform](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#please-enable-the-virtual-machine-platform-windows-feature-and-ensure-virtualization-is-enabled-in-the-bios)
> 
> [#5014 (comment)](https://github.com/microsoft/WSL/issues/5014#issuecomment-646857507)

@BnH2081 This worked for me. 
Just search for "How to enable VM in >Your Manufacturer< BIOS"

**Comment by RoZZaH** [comment]
If on Apple - option boot into mac and set Bootcamp as restart in System Preferences
(If you have Paragon (NTFS) Bootcamp won't be listed there but you can select bootcamp as the restart drive (context/right) on it from paragon menu/icon in menubar)

**Comment by horizonvert1027** [comment]
Why can't I activate Vitrualization?
