### ISSUE TITLE
Memcached high CPU load without usage

### ISSUE THREAD

**Issue by markuszeller** [microsoft/WSL#5691]
Installed memcached via  `sudo apt install libmemcached-dev` .

Launching it with `sudo service memcached start` instantly consumes high CPU load without anything else beeing done. Using it in PHP for example works fine, but the CPU load keeps high until service is stopped.

![memcached](https://user-images.githubusercontent.com/71471/89025517-4a2efc80-d327-11ea-9e6c-7a8f36b7087f.gif)

Microsoft Windows [Version 10.0.19041.388]
Ubuntu 20.4 from Store

C:\WINDOWS\system32>wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         1

Looking with htop in WSL itself, the CPU usage of the memcached is 0. RAM about 400 MB.

**Comment by onomatopellan** [comment]
>19041
>Ubuntu 20.4 WSL1

It's not recommended to use Ubuntu 20.04 WSL1 in build 19041 or you will hit #4898.
You need to convert Ubuntu distro to WSL2, use one of the available workarounds or wait for the fix to come via Windows Update..

**Comment by onomatopellan** [comment]
That's because libc6 and thus sleep are broken in WSL1 19041.
Try this workaround:
https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931

**Comment by therealkenc** [comment]
Confirmed just to be sure that was it

![image](https://user-images.githubusercontent.com/7049700/89065730-14871500-d321-11ea-91d0-a09170f3c27d.png)

/dupe #4898
