### ISSUE TITLE
Add support for directly launching alternative shells (other than bash) from powershell/cmd

### ISSUE THREAD

**Issue by noahgaertner** [microsoft/WSL#5692]
**Is your feature request related to a problem? Please describe.**
When you type bash into powershell or cmd, bash is launched in the default linux distro, but that behavior is not replicated with alternative installed shells, like zsh or fish.
**Describe the solution you'd like**
for installed shells in the default WSL distro, have wsl {shell} aliased to {shell} in command prompt and powershell
**Describe alternatives you've considered**
whatever the default implementation is for bash, or just typing in wsl {shell} every time.

**Comment by therealkenc** [comment]
>  type  bash into powershell

[`chsh(1)`](https://man7.org/linux/man-pages/man1/chsh.1.html). Use `wsl.exe` (`bash.exe ` is long deprecated).
