### ISSUE TITLE
FS-Cache: Duplicate cookie detected

### ISSUE THREAD

**Issue by rekaerst** [microsoft/WSL#5694]
# Environment

```none
Windows build number: Windows 10 OS Build 19041.388
Your Distribution version: Ubuntu 20.04
WSL 2
```

# Steps to reproduce
wsl.exe --shutdown
then boot wsl2

#  Expected behavior

Normally WSL2 should take no longer than 1 second to boot on my PC  and the output of dmesg shows no error

# Actual behavior
It takes 2 to 3 seconds 
output of dmesg
```
[    0.323739] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    0.323857] sd 0:0:0:0: [sda] Write Protect is off
[    0.323859] sd 0:0:0:0: [sda] Mode Sense: 0f 00 00 00
[    0.324077] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    0.694938] sd 0:0:0:0: [sda] Attached SCSI disk
[    1.097580] EXT4-fs (sda): recovery complete
[    1.136813] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    1.244528] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x2b291906204, max_idle_ns: 440795269018 ns
[    1.244534] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    1.244983] clocksource: Switched to clocksource tsc
[    2.107235] FS-Cache: Duplicate cookie detected
[    2.107237] FS-Cache: O-cookie c=0000000081e1b60e [p=000000002863f95a fl=222 nc=0 na=1]
[    2.107238] FS-Cache: O-cookie d=000000005580763a n=00000000ae3de5fa
[    2.107238] FS-Cache: O-key=[10] '34323934393337353032'
[    2.107240] FS-Cache: N-cookie c=00000000495c429f [p=000000002863f95a fl=2 nc=0 na=1]
[    2.107240] FS-Cache: N-cookie d=000000005580763a n=00000000e8a88081
[    2.107241] FS-Cache: N-key=[10] '34323934393337353032'
```

**Comment by therealkenc** [comment]
I get that too and it appears to be harmless. But fair game, harmless or not. You've got an 'and' in the submission that is technically a thread killer. Whether addressing the underlying cause of the `Duplicate cookie` message will improve boot time by 0.86s is at best hard to say.

**Comment by sirredbeard** [comment]
This is a known issue, it is harmless.

https://bugzilla.kernel.org/show_bug.cgi?id=200145
https://lkml.org/lkml/2019/3/5/665
Arch: https://bugs.archlinux.org/task/59058
Red Hat KB 4644911

**Comment by therealkenc** [comment]
Academically interesting, the patches on lkml look like they touch nfs and afs, but not 9p. Closing this linux-behavior. Thanks for the investigation Hayden.

**Comment by benhillis** [comment]
The warning comes from the vhd, not 9p.

**Comment by cyraid** [comment]
I'm getting a huge number of these. Using vscode in remote mode, even every time I go to a different tab, it spams more messages. Any way to filter this out?

**Comment by everything411** [comment]
the fscache driver is rewritten in latest mainline kernel 5.17-rc1, so I compiled and tested this kernel on my wsl2. there is no `FS-Cache: Duplicate cookie detected` error anymore

`Linux DESKTOP-5TB9DFG 5.17.0-rc1 #4 SMP PREEMPT Tue Jan 25 10:48:35 CST 2022 x86_64 GNU/Linux`

**Comment by lo-w** [comment]
update:
we compile the Linux kernel 5.17.0, this "Duplicate cookie detected" issue got resolved.
https://docs.microsoft.com/en-us/windows/wsl/wsl-config
https://github.com/torvalds/linux
https://github.com/microsoft/WSL2-Linux-Kernel
BR//

**Comment by everything411** [comment]
@fredizzimo There are third-party LTS or stable kernels with microsoft patches for WSL2, for example, https://github.com/Sarisan/WSL2-Linux-Kernel and https://github.com/Locietta/xanmod-kernel-WSL2. Currently linux kernel version 6.1 and 6.5.
