### ISSUE TITLE
Can't reclaim memory in custom-built kernel

### ISSUE THREAD

**Issue by rekaerst** [microsoft/WSL#5695]
# Environment

```none
Windows build number: Windows 10 OS Build 19041.388
Your Distribution version: Ubuntu 20.04 with kernel 5.7.11
The issue is on WSL 2
```
I built a Linux 5.7.11 kernel for WSL2 because I need better support for recent hardware ( newest ryzen processors).
I built my custom kernel with this Microsoft's configuration and the new option in kernel 5.7.11 was set to default.
Everything works fine in my build except memory reclamation.

# Steps to reproduce

Grow the memory need of WSL2 workflow and drop all the cache after the workflow is done.

#  Expected behavior

According to Microsoft, starting with Windows OS Build 19013, that memory which is no longer needed by the W would be able to get released back to the host and this feature is powered by a kernel patch.  [[source from devblog]](https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/)
# Actual behavior
But for some reason, this feature doesn't work in my custom-built kernel. Even though WSL2 still claims that it was performing memory compaction in the background.  

#  PS
Can this problem be solved by applying the patches to the kernel source tree?

**Comment by therealkenc** [comment]
This is a good question for reddit, or some people hang out in [microsoft/WSL2-Linux-Kernel](https://github.com/microsoft/WSL2-Linux-Kernel).
