### ISSUE TITLE
slow WSL2 prompt when PATH or LD_LIBRARY_PATH contain /mnt/c paths

### ISSUE THREAD

**Issue by yellowtailfan** [microsoft/WSL#5696]
As noted by several users here:

https://www.reddit.com/r/bashonubuntuonwindows/comments/haucd6/wsl2_slow_commandsdelay_after_upgrade/fzyzdje?utm_source=share&utm_medium=web2x

the WSL2 prompt can be very slow when there are paths containing `/mnt/c` in PATH or LD_LIBRARY_PATH. When I removed `/mnt/c` from those environment variables, the time to return to the prompt after typing simple commands like `git status` went down from 2 seconds to almost instant.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (Linux version 4.19.104-microsoft-standard)
```

# Steps to reproduce

Run WSL2 bash prompt using Windows Terminal. My normal PATH and LD_LIBRARY_PATH had about 10 paths starting with `/mnt/c`. Running `git status` in a folder on the Linux file system took about 2 seconds.

#  Expected behavior

`git status` should return almost instantly.

# Actual behavior

`git status` should returns after about 2 seconds.

**Comment by yellowtailfan** [comment]
Here is the work around I'm using to avoid the slow WSL2 prompt. I added the following lines to my `~/.bashrc`:
```
# Strip /mnt/c paths from paths, which otherwise cause 2 second delays on every command on WSL2.
export PATH="$(echo "$PATH" | python -c "import sys; path = sys.stdin.read().split(':'); path = [pp for pp in path if '/mnt/c' not in pp]; print(':'.join(path))")"
export LD_LIBRARY_PATH="$(echo "$LD_LIBRARY_PATH" | python -c "import sys; path = sys.stdin.read().split(':'); path = [pp for pp in path if '/mnt/c' not in pp]; print(':'.join(path))")"

# Add aliases for useful Windows commands to make up for them now being missing from the path.
alias exp='/mnt/c/WINDOWS/explorer.exe'
alias code='/mnt/c/Users/<Windows-User-Name>/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code'

```

**Comment by DHowett** [comment]
You can also just use the `appendWindowsPath` option in [wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf) to prevent the addition of Windows paths to `PATH` instead of spawning two instances of Python to do some string filtering :smile:

**Comment by therealkenc** [comment]
> and LD_LIBRARY_PATH had about 10 paths

Putting a `/mnt/c` component in `$LD_LIBRARY_PATH` is cray. WSL proper will not muck your `$LD_LIBRARY_PATH`. As far as I know anyway. Can't reproduce here. 

![image](https://user-images.githubusercontent.com/7049700/89107222-46ad7b00-d3e4-11ea-9041-9f968317975d.png)

Standard operating procedure on that would be, don't put `/mnt/c` things in `$LD_LIBRARY_PATH`. [Unless you are `/usr/lib/wsl/lib`. Which ought be a squashfs imo. But I digress.]

As for `$PATH`, it is not obvious why `git status` would be walking the components absent some unspoken externality. Cannot reproduce that here, on a pretty big git repository:

![image](https://user-images.githubusercontent.com/7049700/89107265-9be98c80-d3e4-11ea-9757-82900a683985.png)

While you _can_, as a big hammer, run with `appendWindowsPath=false`, it should not be necessary absent a good reason.

For use cases where there _is_ a good reason (for some value of good) to access `/mnt/c`, and it is slow, that much is 295 likes and counting /dupe #4197 which remains a high priority to improve.

**Comment by yellowtailfan** [comment]
Thanks for your rapid and informative responses! Now that you point it out, I agree that `/mnt/c` paths in LD_LIBRARY_PATH makes no sense. This was being caused by our internal build environment script. I've fixed that to remove `/mnt/c` paths from LD_LIBRARY_PATH, while leaving the `/mnt/c` paths in PATH. My WSL2 prompt remains happily much faster than before.

I did some testing with a clean and unclean LD_LIBRARY_PATH. A `time git status` command was 0.6 seconds with an unclean LD_LIBRARY_PATH, and 0.03 seconds with a clean LD_LIBRARY_PATH.

**Comment by chiqui3d** [comment]
I am using Docker with WSL2 + Oh My ZSH, and it is super slow, in the terminal I only use the G disk, the other disks that I have I don't have to have it mounted, I mean if this slows down my terminal.

A git status or any command like ls under my directory takes like 20 seconds delay. I mean I do "ls" it shows me the directories and then it takes about 20 seconds delay to get the cursor back to the terminal.

Do you know any solution?

**Comment by woodmanzee** [comment]
@chiqui3d I'm having the same ~20 second delay you mentioned in this issue and I can't find anybody else talking about it. Did you find a solution?
