### ISSUE TITLE
Accidentally wiped default wslpath script

### ISSUE THREAD

**Issue by nahuelarjonadev** [microsoft/WSL#5697]
As the title, prior to realizing there was a default wslpath tool that came with the wsl installation, I followed the guide from [laurent22/wslpath](https://github.com/laurent22/wslpath) and now I can't recover the old one nor find it on the internet. Can anyone share it with me? I thought wsl was open source but it turns out it is not so I can't go search the source code my self and recover the script

**Comment by therealkenc** [comment]
`wslpath` can't be killed with conventional weapons. 

![image](https://user-images.githubusercontent.com/7049700/89115917-d8e46c00-d442-11ea-8e82-41b582ddf292.png)
