### ISSUE TITLE
WSL Instal error 0x80080005

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/WSL#5700]
Environment

```none
Windows build number: 10.0.20180.0
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 probably, it's just the default, which is applied with an installation from the Microsoft Store.
```

# Steps to reproduce
1. Go to the Microsoft Store
1. Download Ubuntu
1. See error

#  Expected behavior
A clean and successful installation of WSL.

# Actual behavior
`
Installing, this may take a few minutes...  
WslRegisterDistribution failed with error: 0x80080005  
Error: 0x80080005 Server execution failed`

![image](https://user-images.githubusercontent.com/29888641/89132032-7d34e400-d511-11ea-9939-fc7f4c078b63.png)

**Comment by therealkenc** [comment]
Possibly #5512 #5003. If not, please send [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) via feedback hub.

**Comment by filiptronicek** [comment]
It is indeed a duplicate. Thanks!

**Comment by naveednilawfar** [comment]
I too got this error when installing ubuntu

**Comment by ERB3K** [comment]
Run Prompt as Admin
`sc config LxssManager start=auto`
reboot
