### ISSUE TITLE
Windows SSH Server conflict with tmpfs in WSL2

### ISSUE THREAD

**Issue by hzhangxyz** [microsoft/WSL#5704]
It is about #5703, I have already reproduce it, but I don't know why it was closed by @therealkenc

# Environment

windows 10 build 19041.388
WSL2
yuk7/ArchWSL(maybe useful, not test in other repo)

# Steps to reproduce

- use `/etc/fstab` to mount `tmpfs` to `/tmp`
- run tmux
- use another machine to ssh into this windows and run `wsl` to get into this wsl2
- try run `tmux attach` and fail

#  Expected behavior

get tmux session attached

# Actual behavior

show no session

# what else

my wsl2 user is the same, no problem here, both process started from ssh and the process starting tmux first are root user process

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/89207300-5e653a80-d56f-11ea-9f4f-652329967b54.png)

Try reddit, serverfault, arch forum, etc.

The Windows SSH server does not conflict with tmpfs. [The premise doesn't even make sense.]
