### ISSUE TITLE
ssh no longer works after post windows update restart

### ISSUE THREAD

**Issue by torstees** [microsoft/WSL#5708]
# Environment
10.0.19041.0
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
Launch WSL 1 (Ubuntu-20.04), run sudo service ssh start    

attempt to log into system either from localhost or from a machine on the network. This worked fine before the reboot required by the most recent .NET install. Though, windows update did also install a few other things like security updates. 

I tried turning all 3 parts of windows firewall off, but the behavior didn't change. 

$ sudo service ssh start
 * Starting OpenBSD Secure Shell server sshd                                                                            /etc/ssh/sshd_config line 16: Deprecated option UsePrivilegeSeparation
/etc/ssh/sshd_config line 19: Deprecated option KeyRegenerationInterval
/etc/ssh/sshd_config line 20: Deprecated option ServerKeyBits
/etc/ssh/sshd_config line 31: Deprecated option RSAAuthentication
/etc/ssh/sshd_config line 38: Deprecated option RhostsRSAAuthentication
                                                                                                                 [ OK ]
(base) est@~ $ ssh localhost -vvvvv
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "localhost" port 22
debug2: ssh_connect_direct
debug1: Connecting to localhost [127.0.0.1] port 22.
debug1: Connection established.
debug1: identity file /home/est/.ssh/id_rsa type 0
debug1: identity file /home/est/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
kex_exchange_identification: Connection closed by remote host
(base) est@~ $ sudo service ssh status

[lxcore-logs.zip](https://github.com/microsoft/WSL/files/5016734/lxcore-logs.zip)

#  Expected behavior
I should be able to ssh into this machine

# Actual behavior
SSH doesn't work

**Comment by therealkenc** [comment]
> 10.0.19041.0
> Launch WSL 1 (Ubuntu-20.04)

Can't reproduce here on 20180, WSL1, Ubuntu-20.04.

![image](https://user-images.githubusercontent.com/7049700/89224050-b1011f80-d58c-11ea-8a08-79768f1816ff.png)

Might be #4898, but I didn't dive enough to confirm (mostly because it worked).

It _probably_ isn't the Windows Update. Or at least, not without some additional unknown external factor contributing to the fail. If it is the Windows Update, there will be a flood of me2s soon enough (but that seems less likely until they arrive).

A couple of things to try:

- Set `PasswordAuthentication yes` in `/etc/ssh/sshd_config` to see if you can connect without the key exchange.
- Install 18.04 and see if it is okay there.

**Comment by torstees** [comment]
So, password authentication was already enabled and 18.04 behaved the same after I installed it. However, uninstalling two Windows Updates from Jun 21 (computer hadn't been restarted until this morning) and manually shutting down WSL did work. So, things are good now.

**Comment by therealkenc** [comment]
> uninstalling two Windows Updates from Jun 21

What were the updates you uninstalled.

**Comment by torstees** [comment]
Sadly, I didn't write down the numbers, but they were the only two windows updates that were installed on Jun 21 (probably when my the window I had instructed windows not to install updates had ended) so whatever would have become available once it was allowed to look for updates. I tried to find references to 'uninstall' in Application events, but nothing shows up. Do you have a way to find out without turning windows update back on? They were not marked as security updates nor were they .net updates, but regular windows updates.

**Comment by therealkenc** [comment]
Alright, thanks. Glad you are unblocked.
