### ISSUE TITLE
Factory Reset

### ISSUE THREAD

**Issue by chrisbohn1984** [microsoft/WSL#5712]
I had to do a factory reset on my Samsung laptop running windows 10 Home. Since then, I haven't been able to install anything including Ubuntu, Debian, etc. I've never had any problems arise like this after a reset. Has anyone else had this issue? How did you fix?

**Comment by therealkenc** [comment]
/template

Apart from the Windows version info, include at least _some_ mode of failure. If you get as far as installing Ubuntu-18.04 from the Store, then maybe a screencap of what happens when you run `Ubuntu-18.04.exe` from the `cmd` prompt.
