### ISSUE TITLE
tcpdump dump support

### ISSUE THREAD

**Issue by webstean** [microsoft/WSL#5714]
**Is your feature request related to a problem? Please describe.**
View network traffic being generated by linux  running under Windows

**Describe the solution you'd like**
Support the use of tcpdump to view network traffic being generated by WSL hosted linux systems

**Describe alternatives you've considered**
Avoid the need to setup VM - just for network development / troubleshotting

**Additional context**

**Comment by therealkenc** [comment]
WSL2 supports `tcpdump`, available in Windows 2004.
