### ISSUE TITLE
Docker on Windows 10 with WSL2 and Sysprep?

### ISSUE THREAD

**Issue by tndata** [microsoft/WSL#5716]
As a teacher I rely on pre-made Windows-10 images to create my student class-room images from. 

In the past I have used Hyper-V and Docker for desktop and sysprepped those machines and that have worked (but "slow)".

Now WSL2 is out and I was hoping to have a a better and more performant Docker experience for my students with no additional work after an image has been created.

Are there any guides for doing this? I tried but Docker hangs forever  with these entries in the log

[10:58:38.964][LoggingMessageHandler][Info   ] [8dd43976] <LifecycleClient start> GET http://localhost/ping
[10:58:39.958][LifecycleClient   ][Warning] HttpOS Client: connection timed out.

One issue I had is that Ubuntu that I download from the Windows store is per-user and that blocks any sysprep.

Is having Ubuntu installed a prerequisite to run Docker containers on Windows 10 using WSL2?

**Comment by therealkenc** [comment]
> Docker on Windows

Over [here](https://github.com/docker). There is a similar-looking but lifecycle-locked issue docker/for-win#4393 that might or might not be applicable. If not they might be able to help you out.

> One issue I had is that Ubuntu that I download from the Windows store is per-user and that blocks any sysprep.

That's open #5151 plus older variant #1636.

> Is having Ubuntu installed a prerequisite to run Docker containers on Windows 10 using WSL2?

Nah. Docker with the WSL2 backend will run without any WSL distros installed. AFAIK anyway.
