### ISSUE TITLE
Inability to access server running on WSL in Windows

### ISSUE THREAD

**Issue by ethanhowell** [microsoft/WSL#5717]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

In WSL:
```sh
python3 -m http.server
curl http://0.0.0.0:8000
```
Prints out `<html>`...</html>`.

In Windows open a browser and go to http://0.0.0.0:8000. 

#  Expected behavior
The browser in Windows would connect to the server.

# Actual behavior

You'll get something like `ERR_ADDRESS_INVALID` in the browser.

**Comment by licanhua** [comment]
try http://localhost:8000/ or http://127.0.0.1:8000/.
 "0.0.0.0" means accept any IPv4 address on which the server binds, but for the client, you can't use it.

**Comment by ethanhowell** [comment]
> try http://localhost:8000/ or http://127.0.0.1:8000/.
> "0.0.0.0" means accept any IPv4 address on which the server binds, but for the client, you can't use it.

Unfortunately neither works in Windows with the browser but they can both be `curl`ed in WSL.

**Comment by ethanhowell** [comment]
Also FWIW it was working before yesterday and then there was a software update and it no longer works.

**Comment by licanhua** [comment]
how about ifconfig to get the IP(eg: 172.21.97.149) from linux, then ping it from Windows, and use http://172.21.97.149:8000

**Comment by ethanhowell** [comment]
> how about ifconfig to get the IP(eg: 172.21.97.149) from linux, then ping it from Windows, and use http://172.21.97.149:8000

Yes that works!

**Comment by therealkenc** [comment]
The OP is linux-behavior. Li's suggestion is /dupe #4851 #5298, others.
