### ISSUE TITLE
WSL doesnt start after Windows Update

### ISSUE THREAD

**Issue by Ramil2911** [microsoft/WSL#5722]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.20175.0 Microsoft Windows NT 10.0.20175.0
Your Distribution version: None
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Setup WSL2 in Windows 10 19041
2. Install Windows 10 20175

#  Expected behavior

Works as usual, opens bash in cmd.

# Actual behavior

"WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel"

After reinstalling of WSL:
Unknown Error - wsl in cmd
Error 0x80004005 - Ubuntu 20.04 installer;

Reinstall using wsl_update_x64 and putting its files into System32/lxss:
Unknown error in the cmd (command "wsl") and Ubuntu Installer;

**Comment by therealkenc** [comment]
Please collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) and post to the feedback hub.

**Comment by Ramil2911** [comment]
https://aka.ms/AA96uyx
