### ISSUE TITLE
The distribution installation has become corrupted with error: 0x800700b7

### ISSUE THREAD

**Issue by abdallaegt** [microsoft/WSL#5724]
#5711 Environment

I don't want to reset or reinstall because the distribution contains data that I don't want to delete

```none
Windows build number: [Version 10.0.18363.959]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc 
version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce

- Run ubuntu

![Annotation 2020-08-05 232528](https://user-images.githubusercontent.com/67766127/89465815-0434c700-d773-11ea-977c-cfa17dda0de7.png)

**Comment by therealkenc** [comment]
That "`The distribution installation has become corrupted`" on face value sort of speaks for itself. Those are not steps to reproduce (but we both know that). 

You could [off the record](https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/) poke around....
```
 C:\Users\you\AppData\Local\Packages\CanonicalGroupLimited...somehexdigits\LocalState\rootfs` 
```
... and hope to grab what you can. Better, restore from backup.

**Comment by abdallaegt** [comment]
Where can I find the contents
`/home/myuser/`

**Comment by therealkenc** [comment]
It will look something like this. [Ignore the openSUSE specifics below, that just happens to be a WSL1 distro I have handy.]

![image](https://user-images.githubusercontent.com/7049700/89485617-09cfe400-d756-11ea-8490-29f5dcea69f6.png)

If you _do have_ a `rootfs`, but _nothing_ under it (or _something_ under it but no `....\rootfs\home`) that's not a good sign. And a good explanation for the error message. Also on a lark check `...\AppData\Local\lxss` like #5522. Long-short, if there isn't a `rootfs\home` _somewhere_ on your system, tautology it isn't there.

**Comment by abdallaegt** [comment]
It looks like I'm going to lose some data, but
We are now learning not to make mistakes again
_`The reason for possible damage is when I was modifying system files using windows programs`_
Thank you @therealkenc  and thank you for your help
