### ISSUE TITLE
command as alias doesn't work but does when run as a one liner

### ISSUE THREAD

**Issue by mikerod-sd** [microsoft/WSL#5725]
# Environment

Microsoft Windows [Version 10.0.19041.388]

wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-18.04           Running         1
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```

# Steps to reproduce

1. From my bash terminal I run the following command
`echo | openssl s_client -connect google.com:443 2>/dev/null | openssl x509 -noout -date`

with the following response:
notBefore=Jul  7 08:04:38 2020 GMT
notAfter=Sep 29 08:04:38 2020 GMT

2. I create and alias in my ~/.bash_aliases file with the following:
`alias checkexpire='echo | openssl s_client -servername $1 -connect $1:443 2>/dev/null | openssl x509 -dates'`

3. I source the file (and even closed wsl and reopened to be sure)

4. I then run the following command:
`checkexpire google.com`

and get the following error:
$ checkexpire google.com
x509: Unknown parameter google.com
x509: Use -help for summary

<!-- 
I am unable to run strace for the alias
-->

#  Expected behavior

I should be able to run the following command:
`checkexpire google.com`

and get the following response:
notBefore=Jul  7 08:04:38 2020 GMT
notAfter=Sep 29 08:04:38 2020 GMT

# Actual behavior

When I run `checkexpire google.com` I get the below error:
x509: Unknown parameter google.com
x509: Use -help for summary

**Comment by therealkenc** [comment]
> `alias checkexpire='echo | openssl s_client -servername $1 -connect $1:443 2>/dev/null | openssl x509 -dates'`
> I should be able to run the following command:
> `checkexpire google.com`

That's a pretty declaratory statement don't you think. I'm just 'sayin.

Morbidly curious enough late-nite to try to figure how your `alias` might actually expand.

![image](https://user-images.githubusercontent.com/7049700/89495232-b3ba6b00-d76c-11ea-852f-949784980a35.png)

Yours is the result you got:

![image](https://user-images.githubusercontent.com/7049700/89495323-e5333680-d76c-11ea-813f-6ea73bbd9057.png)

You want a shell function.

![image](https://user-images.githubusercontent.com/7049700/89496549-68558c00-d76f-11ea-9a93-807e3d20c4d4.png)
