### ISSUE TITLE
Vmmem uses 50% of CPU and Very High power despite .wslconfig limits

### ISSUE THREAD

**Issue by emin-ec** [microsoft/WSL#5736]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: On an Ubuntu 18 system in wsl2, lsb_release -r returns: Release:        18.04 
Whether the issue is on WSL 2 and/or WSL 1: cat /proc/version returns Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Use the following in `c:\Users\<username>\.wslconfig`:
```none
[wsl2]
memory=16GB
swap=0  
```

  1. Quit windows docker if you are using it so that doesn't confuse the issue.
  2. Run some python programs or do other useful work in wsl2.
  3. Run task manager to see that Vmmem is crushing the CPU (see screenshot below):
      - ![image](https://user-images.githubusercontent.com/47005807/89724262-b2887880-d9ce-11ea-8eac-71b48ab3d103.png)
  4. Run `top` in ubuntu to verify that ubuntu is not using any swap
      - ![image](https://user-images.githubusercontent.com/47005807/89724276-d9df4580-d9ce-11ea-90ec-4c5e3e3b9825.png)

#  Expected behavior

The `Vmmem` process should not be using 50% CPU with `Very high` power usage when:
   - nothing is running under Hyper-V
   - docker is not running
   - My `.wslconfig` set swap to 0 and this is confirmed by top.

I don't mind the memory usage but the CPU usage, power drain, and running the fan at full power are really annoying.

# Actual behavior

The `Vmmem` process is using a lot of CPU, power, and fan. I don't mind the RAM usage discussed in https://github.com/microsoft/WSL/issues/4166 and seem to have mitigated that with the `.wslconfig` but `Vmmem` seems seriously broken. A work around would be welcome.

**Comment by therealkenc** [comment]
You've got a load average of ~4 (read, overloaded 300% of the time, ie pegged) inside the VM, so that looks "about right". That vmmem isn't also pegged at 100% (vs only 50%) might be #5423.

**Comment by emin-ec** [comment]
> You've got a load average of ~4 (read, overloaded ~300% of the time, ie pegged) inside the VM, so that looks "about right". That vmmem isn't also pegged at 100% (vs only 50%) might be #5423.

Thank you for that information. I confirm that if I kill processes to reduce load then vmmem CPU usage goes down to a reasonable level. 

I guess I was confused by the name `vmmem` and thought it had to do with virtual memory (i.e., swap). Based on further search (e.g., https://devblogs.microsoft.com/oldnewthing/20180717-00/?p=99265) it seems like `vmmem` also represents CPU usage of virtual machines completely independent of whether they are using virtual memory or not.

If you could confirm the above understanding or give a description or pointer to what `vmmem` does, that might be useful for others who are similar confused.

In any case, I will close this issue. Thanks again.

**Comment by therealkenc** [comment]
> If you could confirm the above understanding or give a description or pointer to what vmmem does

You found it. [Confirming Raymond Chen's vmmem explanation would be a little like confirming Micheal Jordan thoughts on basketball.]

**Comment by ddobric** [comment]
Sorry for coming back on this.
I noticed continuous high consumption of the same process on the Surface Book 2, Win 10.

I have definitely no running VMs and the docker is stopped.
Why does this process penetrate the CPU? Moreover, the device is getting so hot and hibernating all the time.

![image](https://user-images.githubusercontent.com/1756871/97759678-ce00ac80-1b01-11eb-80c8-820023e24c1c.png)

![image](https://user-images.githubusercontent.com/1756871/97759847-23d55480-1b02-11eb-83b5-a2a24b4533f5.png)

Thanks

**Comment by dennismartini** [comment]
Same problem here
![image](https://user-images.githubusercontent.com/14280787/99880685-c65d9080-2bf3-11eb-8409-0d1b3f73d28b.png)

**Comment by guitarrapc** [comment]
Same to me.
![image](https://user-images.githubusercontent.com/3856350/101727007-03cc8400-3af7-11eb-81f8-e8795b9f7cfc.png)

**Comment by jgwinner** [comment]
This just happened to me recently. Exiting out of Docker fixed it. I had nothing running under docker, so I think there's some kind of weird bug here.

**Comment by throcha3** [comment]
It happens here too. My docker is closed and yet vmmem is using 50% of cpu

**Comment by ladislavlencucha** [comment]
I have the same issue. Docker not started, Ubuntu on WSL2 shows 0 cpu usage in "top" command. Yet, the vmmem utlizes 50% of CPU

**Comment by armsp** [comment]
same issue as above...docker not running, yet Vmmem uses 70% CPU

**Comment by Herts** [comment]
Docker with no containers consumes 99% of CPU

**Comment by aimalamiri** [comment]
Hi @armsp, I have the same issue, did you find a solution?

**Comment by throcha3** [comment]
@aimalamiri Usually I just reboot my computer then it go back to normal.

**Comment by RomanOrlovDev** [comment]
Same problem here

**Comment by kwende** [comment]
Same problem. Docker isn't running, no virtuals running. High utilization.

**Comment by MrSnoozles** [comment]
Same here. Running `wsl --shutdown` brings CPU back to normal (but took me around a minute to complete)

**Comment by hassanmehdi98** [comment]
Same problem here, no containers are active.
![image](https://user-images.githubusercontent.com/59412352/194083476-9036287c-0702-45a8-811b-b71f8d956568.png)

**Comment by rltas** [comment]
> Same here. Running `wsl --shutdown` brings CPU back to normal (but took me around a minute to complete)

Same here. Did `wsl --install` on a pretty fresh Win 11, then installed [Ubuntu 22.04 LTS](https://apps.microsoft.com/store/detail/ubuntu-22041-lts/9PN20MSR04DW) and Docker Desktop, ran `docker run hello-world` to see if everything works and things went downhill from there.

**Comment by nddipiazza** [comment]
Why is this issue closed? WSL is unusable for any real development task due to this weird behavior.

**Comment by treharne** [comment]
[This comment](https://github.com/microsoft/WSL/issues/6982#issuecomment-1275976254) in Issue #6982 100% confirms my suspicion that it is related to a recent Windows Update.

@alonbl (in that comment) was able to stop this issue from occurring by reverting Windows Update KB5017328, then turning off automatic updates.

Not ideal, but it might allow you to get some work done until Microsoft resolves the issue.

**Comment by JarrodSears** [comment]
I'm experiencing the same thing. Stopped WSL, stopped docker desktop. No VMs or containers running. Vmmem pegged between 97 and 100% on all 20 cores and using over 2 GB RAM

**Comment by andrusenko-ag** [comment]
Facing the same issue CPU 100%, 150 MB RAM. It appears 1-2 times daily. Looks like some mining plugin inside the Docker=))

**Comment by vladi14** [comment]
any news about this bug ?
it happens to me when i hibernate the machine and log on on the day after , only restart solves this issue.

**Comment by alonbl** [comment]
> any news about this bug ? it happens to me when i hibernate the machine and log on on the day after , only restart solves this issue.

Have you tried WSL `0.70.4.0`?

**Comment by MrSnoozles** [comment]
Still happening with version 1.0.0
I can so far confirm, that it only happens after coming back from hibernation.

**Comment by winrid** [comment]
Also ran into this today. Not running any VMs or containers. vmmem using 100% of 16 available threads and 2.8gb of ram...

**Comment by hailiang-wang** [comment]
vmmem seems to have a BIG bug.
I have to shutdown vmmem with `wsl --shutdown` almost everyday.

**Comment by lex0r** [comment]
This is exactly what I'm doing @hailiang-wang . I think this BIG bug somehow has low priority or there are just not enough good engineers at MS, which is really hard to admit.

**Comment by MrSnoozles** [comment]
@therealkenc Any chance to reopen the issue? Hibernation on Windows is rendered useless because WSL will take almost 100% CPU when coming back.
`wsl --shutdown` is not working anymore either (it used to shutdown after around a minute, now it just never finishes).

**Comment by hailiang-wang** [comment]
I fixed this problem by upgrading to windows 11, it works very well.

**Comment by vladi14** [comment]
I use win 11, problem is there

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by julian-sawicki-skrepr** [comment]
Same prooblem here: 

![afbeelding](https://user-images.githubusercontent.com/89254231/215076381-c27e127f-8f17-4391-a01d-bb1cd57bf13d.png)

**Comment by lex0r** [comment]
> I fixed this problem by upgrading to windows 11, it works very well.

Are you sure you are not getting random and not-as-noticeable-as-before CPU spikes for vmmem? I noticed that sometimes it just doesn't look as bad as other people reported it, it's quite random. Also, restarting via wsl --shutdown works but may freeze every now and then leading to a hard restart.

**Comment by winrid** [comment]
> I fixed this problem by upgrading to windows 11, it works very well.

I fixed this problem by upgrading to Linux on my dev machine, works very well. :p

**Comment by vladi14** [comment]
win 11 is core of the probelm not the solution.
Never had such a problem on win 10.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JDuchniewicz** [comment]
Unfortunately I have to use Windows at work and WSL is what made it bearable - running `wsl --shutdown` helped - it no longer has 100% CPU utilization but it is not the solution to the problem, rather a mitigation.

**Comment by abelbraaksma** [comment]
I have this happen both on a Windows 11 laptop and a Windows 10 workstation. The issue isn't related to either of these systems, it is related to both.

Perhaps we should just create a new bug report and point to this very long thread. There are some interesting hints in here, but nobody has yet come to a full solution. 

As with others, it didn't use to be this bad. Restarting `LxssManager` or running `wsl --shutdown` tended to work, but the first, while it ultimately finishes, doesn't remove the high CPU and the second just runs forever. Restarting from Docker Windows GUI doesn't help either.

PS: it should be said, if you restart _in time_ with `wsl --shutdown`, it works fine to bring the CPU usage down. That is before the `vmmem` takes 100% CPU of 1 or more cores (it is allowed to use 2 cores on my machine, of 24 cores, so it doesn't slow down everything else, but it still makes WSL and Docker unusable).

**Comment by lex0r** [comment]
> > I fixed this problem by upgrading to windows 11, it works very well.
> 
> I fixed this problem by upgrading to Linux on my dev machine, works very well. :p

Unfortunately this is the only available "solution". A 16 GB machine uses 80% of RAM on Windows 10 with Docker Desktop, and 30% of RAM on Ubuntu - it was a strong argument for me. And everything is just faster on a Linux.

**Comment by thangamani-arun** [comment]
read here if yours wsl hangs or cpu usage goes to 100% or both happens at the same time. 
https://github.com/microsoft/WSL/issues/6982#issuecomment-1500137635

**Comment by zizhaolaisuimuqu** [comment]
I don't even install Docker on my win11, but the same problem here. Also, `wsl --shutdown` doesn't seem work for me.

![Image](https://github.com/user-attachments/assets/9865381c-40c7-46a4-961f-6250bd8f4a7f)

**Comment by orionseye** [comment]
> I fixed this problem by upgrading to Linux on my dev machine, works very well. :p  

LOL.. of course it does. Show me ONE..just ONE thing which ever worked bug free on Windows.
Look at their support forums. Millions of entries from people trying to understand why common sense was deleted from Windows OS
