### ISSUE TITLE
Ctrl+` (backquote) does not working in vim

### ISSUE THREAD

**Issue by AirManH** [microsoft/WSL#5737]
First of all, sorry about my Enlish. I'm not an English native speaker.

# Environment

- Windows build number: 10.0.18363.0
- Your Distribution version: 18.04
- Whether the issue is on WSL 2 and/or WSL 1: WSL 1
  
  ```none
  $ cat /proc/version
  Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 
  16:04:00 PST 2020
  ```

# Steps to reproduce

1. double click to open `C:\Windows\System32\wsl.exe` (open a _cmd_ that runs wsl).
2. map <kbd>ctrl</kbd> + <kbd>`</kbd> to <kbd>space</kbd> in _vimrc_ :

   ``` none
   $ cat ~/.vimrc
   imap <C-`> <Space>
   ```

3. open _vim_, activate *insert mode*
4. press <kbd>ctrl</kbd> + <kbd>`</kbd>

# Expected behavior

A new _space_ appear in current buffer

# Actual behavior

No _space_ appear in current buffer

**Comment by therealkenc** [comment]
https://stackoverflow.com/questions/45907039/vim-mapping-ctrl-or-c-to-c-ww
