### ISSUE TITLE
Distro uninstalled after unplugging drive

### ISSUE THREAD

**Issue by Toomoch** [microsoft/WSL#5740]
# Environment

```none
Windows build number: 10.0.19041.388
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Install a WSL 2 distro, export it and import it on a drive that isn't C://. If you power off and disconnect that drive (sata cable for example), power on again and accidentally open the distro (I did and I shouldn't have), the next time you plug it in it will act as if you hadn't installed any distro.

#  Expected behavior
For it to recognise the distro without doing anything.

# Actual behavior
It is trying to install again if you open the distro.

**Comment by onomatopellan** [comment]
Open registry editor and go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`
You will see there an entry for each installed distro. Try again and see if the entire entry disappears when you run the inexistent distro or it just changes the BasePath key content.

**Comment by therealkenc** [comment]
Could not reproduce here. Just get the expected "system cannot find the path specified" if the external drive is unplugged. Comes back when the drive is plugged back in. 

![image](https://user-images.githubusercontent.com/7049700/90691497-41e02800-e228-11ea-8b21-6c7a7d62f539.png)

`dubuntu` was imported to now unplugged `D:` above.

If I'm reading the OP correctly, **any** already installed distro (nevermind the imported one) was failing to appear installed. That would be... very unusual. If every unrelated distribution was being affected by a drive being disconnected, there would be a shower of reports, but it hasn't come up before. There is no way to tell what sequence of events caused the OP behavior. Going to close on need-repro absent some me2s.
