### ISSUE TITLE
GDB's hardware watchpoints not working

### ISSUE THREAD

**Issue by Vyber90** [microsoft/WSL#5741]
# Environment

```none
Windows info: Win32NT ver. 10.0.19041.0
Distribution version: Kali 1.5.0.0 (WSL 2)
```

# Steps to reproduce
```none
$ gdb executable
(gdb) rwatch *0x7654
Hardware read watchpoint 1: *0x7654
(gdb) show can-use-hw-watchpoints
Debugger's willingness to use watchpoint hardware is 1.
(gdb) run
```

#  Expected behavior
Since the program reads the information at 0x7654 (it is a fictitional address, just for illustration), the execution should be paused by the watchpoint (GDB tells us hardware watchpoints are available).

# Actual behavior
The execution is not paused at all, and the program ends normally.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/89815657-004dcf80-dafa-11ea-9d60-1d6ceebe8121.png)

**Comment by Vyber90** [comment]
@therealkenc does it work with stripped and not-intended-for-debugging binaries?

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/89840637-9814e300-db25-11ea-9e29-30ea4ca7a5dc.png)
