### ISSUE TITLE
Determine path of cmd.exe programatically from WSL

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/WSL#5743]
**Is your feature request related to a problem? Please describe.**
Modules like https://www.npmjs.com/package/open are used to, for example, open a URL in a browser. This module has built-in detection for if it is running inside WSL. In which case it will utilize `cmd.exe` to invoke a browser on the Window side.

This mechanism only works when `cmd.exe` is available through the `$PATH` environment variable. This is the default behavior in WSL.

When [disabling the attachment of Windows elements to the `$PATH` environment variable](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop), this entire process no longer works. Disabling the `$PATH` attachment can be desireable in certain configurations, where you want to ensure that no Windows binaries creep into your environment unintenionally.

**Describe the solution you'd like**
My idea was some `/proc` endpoint that would return information about the Windows environment. An equivalent of `%SystemDrive%` and `%SystemRoot%` would probably be sufficient.

**Describe alternatives you've considered**
Reading the base mount point from `/etc/wsl.conf`, if it exists, then iterating over `/<mount_point>/[a-z]` and searching for a Windows installation.

This is not feasible. Multiple Windows installations could exist. I'm not sure if exotic configurations are possible where the Windows directory is not named `Windows`.

A search feels unclean. This information should be accessible through a clear API.

**Additional context**
https://github.com/sindresorhus/open/issues/186

**Comment by therealkenc** [comment]
This is variation discussion in rust-lang/rustup#2206 ([message](https://github.com/rust-lang/rustup/issues/2206#issuecomment-578584046))

> This is not feasible. Multiple Windows installations could exist

Under premise critical use case "multiple windows installations", ship a small static win32 binary which prints environment variables to `stdout`. Interop will execute it regardless of `wsl.conf [interop] appendWindowsPath=false`. Use `/bin/wslpath` for the path conversion, which takes into account oddball `[automount] root=foo`.

```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv)
{
	if (argc == 2) {
		char* v = NULL;
		size_t szv = 0;
		if (_dupenv_s(&v, &szv, argv[1]) == 0) {
			printf("%s\n", v);
			free(v);
		}
	}
	return 0;
}
```

![image](https://user-images.githubusercontent.com/7049700/89940861-0e215480-dbcf-11ea-870d-7d976b098d40.png)

Can leave it open 'feature' loophole. Smart money #938 ships first.

**Comment by oliversalzburg** [comment]
I really like that solution. Thanks a lot for the suggestion. This will work great for some things I had in mind for myself.

However, I'm unlikely to be able to introduce a native binary into the mentioned package to solve the problem as it exists there.

So maybe the "real" solution is to wait for alternative GUI approaches in the future that solve the entire problem better.

**Comment by oliversalzburg** [comment]
It seems like there is a tool I wasn't aware of: [`wslvar`](https://github.com/wslutilities/wslu)
```shell
wslpath $(wslvar systemroot)\\cmd.exe
```
This appears to do what I want.
