### ISSUE TITLE
Add an option a for repeating background

### ISSUE THREAD

**Issue by KarelHrkal** [microsoft/WSL#5745]
**Is your feature request related to a problem? Please describe.**
Currently the background image has to stretch to fill the entire window, which can deform it and leave it blurry.

**Describe the solution you'd like**
I would be happy with a simple true/false option `repeatBackground` that, when set to true, would override the `backgroundImageStretchMode` and `backgroundImageAlignment` options and would instead tile the background image while keeping its original size.

**Describe alternatives you've considered**
Another option option would be to pre-tile the image into another, very large image, and display it cropped to achieve a similar effect. But then the image cannot be easily changed. Plus you have to know before-hand what the maximum size of your terminal is going to be.

**Additional context**
This would work well with repeating patterns like this one: 
![image](https://user-images.githubusercontent.com/60599527/90017495-ea800c00-dcab-11ea-94f9-168f9f8bb5fc.png)

**Comment by therealkenc** [comment]
[microsoft/terminal](https://github.com/microsoft/terminal/issues)
