### ISSUE TITLE
Gatsby Hot Module Reloading not working on WSL

### ISSUE THREAD

**Issue by techno021** [microsoft/WSL#5746]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce
- Install Gatsby cli
```bash
npm i -g --unsafe-perm gatsby-cli
```
- Create a new project and cd into it
```bash
gatsby new my-gatsby-project
cd my-gatsby-project
```
- Open up your text editor, I'm using Visual Studio Code
```bash
code .
```
- Start the dev server
```bash
gatsby deploy
```
- Change something, preferably it should be a visible change on the browser

# Copy of the Output
- I've made a change in Line 11 of ```./src/pages/index.js```
![image](https://user-images.githubusercontent.com/29125087/90027468-33e55100-dcd6-11ea-99c9-39954f3bd077.png)

- The change is not recognised in terminal output
![image](https://user-images.githubusercontent.com/29125087/90027611-5b3c1e00-dcd6-11ea-9738-47f874da1d30.png)

- The change is also not reflected in the Browser
![image](https://user-images.githubusercontent.com/29125087/90027718-77d85600-dcd6-11ea-8960-f75e3d884426.png)

#  Expected behavior
The change should automatically be visible in the browser without any refreshes

# Actual behavior
You have to restart the dev server (not intended at all) to see the change

# Extras
- You can view Gatsby output [on localhost on port 8000](http://localhost:8000)
- To share, I've already tried changing into the linux directory, it clears after every restart (I think)

**Comment by therealkenc** [comment]
> code .

Working on the assumption your current working directory is on 9p (/mnt/c) /dupe #4739

**Comment by techno021** [comment]
> Working on the assumption your current working directory is on 9p (/mnt/c)

Yes, that would be correct
