### ISSUE TITLE
Failed install driver ATOL with dpkg

### ISSUE THREAD

**Issue by pavel6520** [microsoft/WSL#5748]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

I am installing ATOL driver, package libfptr10_10.7.0.0_amd64.deb (in directory installer \ deb)
http://fs.atol.ru/_layouts/15/atol.templates/Handlers/FileHandler.ashx?guid=63193199-65ea-4176-9e68-c013efe3bd45&webUrl=
I need it to test my software in Linux before release. Install via dpkg, but I get an error:

```
sudo dpkg -i libfptr10_10.7.0.0_amd64.deb
[sudo] password for pavel:
(Reading database ... 38478 files and directories currently installed.)
Preparing to unpack libfptr10_10.7.0.0_amd64.deb ...
Unpacking libfptr10 (10.7.0.0) over (10.7.0.0) ...
Setting up libfptr10 (10.7.0.0) ...
Failed to send reload request: No such file or directory
```

Using virtualbox and ubuntu 20.04 I installed the driver successfully.
Please tell me how to solve this problem, because using WSL is much more convenient when it comes to development.
I hope for you!
[strace.txt](https://github.com/microsoft/WSL/files/5066095/strace.txt)

**Comment by therealkenc** [comment]
Thank-you for including an `strace(1)` log; it is always appreciated. Your log isn't threaded (`strace -f`). 

[Unknown half-gig .zip file from dot-ru domain. What could go wrong....] The fail on a threaded `strace` is:

```
433   newfstatat(AT_FDCWD, "/proc/1/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
433   newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
433   socket(AF_UNIX, SOCK_SEQPACKET|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
433   setsockopt(3, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
433   connect(3, {sa_family=AF_UNIX, sun_path="/run/udev/control"}, 20) = -1 ENOENT (No such file or directory)
433   writev(2, [{iov_base="Failed to send reload request: N"..., iov_len=56}, {iov_base="\n", iov_len=1}], 2) = 57
433   close(3)                          = 0
433   exit_group(1)      
```

That missing file `/run/udev/control` is part of [`systemd-udevd`](https://man7.org/linux/man-pages/man8/systemd-udevd.8.html).

WSL doesn't support `systemd` out of the box right now, which is #994. You could try getting `systemd` and `systemd-udevd` up using means you can find on the interwebs. I am not exactly sure what the package [does exactly](https://translate.google.com/translate?hl=en&sl=ru&u=https://interface31.ru/tech_it/2019/01/podklyuchaem-kkt-atol-k-1spredpriyatie-83-v-debian-ubuntu.html&prev=search&pto=aue), but best guess you are going to run up against #2195 if the thing needs USB.

Call this /dupe #994 + #2195

**Comment by pavel6520** [comment]
> I am not exactly sure what the package [does exactly](https://translate.google.com/translate?hl=en&sl=ru&u=https://interface31.ru/tech_it/2019/01/podklyuchaem-kkt-atol-k-1spredpriyatie-83-v-debian-ubuntu.html&prev=search&pto=aue), but best guess you are going to run up against #2195 if the thing needs USB.

Thanks for the answer.
This package installs a driver that allows you to interact with ATOL cash registers using various programming languages ​​(by using a programming language packages to interact with the driver) and various communication channels such as USB, Bluetooth, Internet, WiFi (in my case, this is the Internet).

**Comment by therealkenc** [comment]
You _might_ be able to get it to work via Internet Protocol with some effort. You will probably hit #4150, because I'm guessing the cash registers call Linux not the other way around. A forum where `libfptr10` people hang out would be the place to ask.
