### ISSUE TITLE
changing file ownership on /mnt/c/Users/FOO/.ssh

### ISSUE THREAD

**Issue by Boran** [microsoft/WSL#5750]
# Environment

```
ver
Microsoft Windows [Version 10.0.18363.959]

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Debian 10

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce

Install ssh
  sudo apt-get install ssh
  sudo service ssh start

add keys to .ssh/authorized_keys

SSH to wsl from WIndows, the SSH connection works, but not the PK auth:
/var/log$ cat auth.log
Aug 13 07:57:15 NB50436 sshd[205]: Authentication refused: bad ownership or modes for directory /mnt/c/Users/foo/.ssh

chmod 700 /mnt/c/Users/foo/.ssh
ls -ald /mnt/c/Users/foo/.ssh
drwxrwxrwx 1 foo4096 Aug 13 07:42 /mnt/c/Users/foo/.ssh

#  Expected behavior
I should be able to change file permissions

# Actual behavior
FIle permission always world writable

**Comment by therealkenc** [comment]
Variation #5573 ([message](https://github.com/microsoft/WSL/issues/5573#issuecomment-656943394)). Turn on metadata in [/etc/wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-options). Something like:
```
[automount]
options = "metadata"
```
You'll need a `wsl --shutdown` for it to take.

**Comment by Boran** [comment]
Work, thanks.

Note on my WSL; "wsl.exe --terminate Debian" as opposed to "wsl --shutdown" was needed.
