### ISSUE TITLE
WSL Problem, cannot install the package

### ISSUE THREAD

**Issue by Itssuso17** [microsoft/WSL#5752]
Hello guys. I tried to install Kali Linux on my laptop (thanks to Microsoft Store), I thought "it will be easier". But isn't
I have had many problems, but finally I have the system installed. The problem is that I have version 1 and I need version 2. When i connect to remote system, I log in with my account on Kali Linux, but the screen keeps on black. I think that it is because off the WSL version. I went to the microsoft page and download the lastest version (https://aka.ms/wsl2kernel). But when I start it, it doesn't work.

HERE THE ERROR ========> The installer encountered an unexpected error while installing this package. This may indicate a problem with this package. The error code is 2502.

I didn't mention that I checked the box on Windows Features =====> WSL

**Comment by licanhua** [comment]
How do you install the .msi? double click it or use MsiExec.exe?
to install the msi, admin permission is required.
If you double-clicked it, a [UAC](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works#the-uac-user-experience) window would  perform a task that requires a user's administrative access token. If you didn't see the window, that means UAC prompt is disabled, and you can try msiexec.
If you are using msiexe, please open a window with admin permission, then run msiexec.exe to install the MSI.

**Comment by Itssuso17** [comment]
I will try, but a window appear and requires a user's administrative access token.
Thanks for your answer, I will write what happened

**Comment by Itssuso17** [comment]
UHH! It worked! Thanks man, I appreciate it 👍 :D
