### ISSUE TITLE
//wsl$/Ubuntu file or resource was not found

### ISSUE THREAD

**Issue by blacklightpy** [microsoft/WSL#5753]
# Environment

```none
Windows build number: 20185
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

Start a WSL instance
Close the terminal and do something else for a while
a ) Try to access a WSL file from the explorer sidebar or //wsl$/Ubuntu
OR
b) Start a new WSL instance in Windows terminal

#  Expected behavior

a) Since WSL was booted up once and I hadn't typed `wsl --shutdown`, the instance should be online and I should be able to access my files
OR
b) WSL should start a terminal instance without starting the distro again because it was started once and not shut down.

# Actual behavior

a) Trying to access //wsl/Ubuntu (Linux section in Explorer sidebar) or //wsl$/Ubuntu tells me file or resource was not found
OR
b) WSL starts the distro again, starting at /mnt/c/Users/Blacklight instead of ~ respecting startingDirectory attribute I set in terminal (I have made an issue about it at microsoft/terminal#7272).

This is the exact opposite of microsoft/WSL2-Linux-Kernel/#111, which suggests to add this feature as an option in WSL but this is what I have as default in my system and I don't have an option to turn it off :(

**Comment by sr229** [comment]
IIRC this is intended behavior as to prevent unnecessary usage for portable devices.

**Comment by blacklightpy** [comment]
Oh, that makes sense because my device is a laptop. In that case is there any way to turn it off?

**Comment by therealkenc** [comment]
>  //wsl$/Ubuntu tells me file or resource was not found

WSL does shut itself down by-design to conserve resources, but that doesn't (ie: shouldn't) prevent WSL from being fired back up on-demand when you access `\\wsl$\Ubuntu`. Your described behavior described does not reproduce here. There is some variable causing your "file or resource was not found" error, but no off-cuff guesses what.

Please collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs) and post to feeback hub.

**Comment by blacklightpy** [comment]
Here's the link of the Feedback Hub report: https://aka.ms/AA9at0w

While I was collecting the reports, I noticed that the delay for the //wsl$/Ubuntu path being inactive after closing WSL varies each time. In this instance it wasn't working immediately after I closed the tab, but I tried it once afterwards and it was active for a while more.
