### ISSUE TITLE
WSL2 hangs on launch

### ISSUE THREAD

**Issue by airtonix** [microsoft/WSL#5756]
# Environment

```none
# Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

~ $ [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.20185.0 Microsoft Windows NT 10.0.20185.0


# Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]

can't launch wsl

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]

can't launch wsl

```

# Steps to reproduce

#  Expected behavior

launch wsl2 without drama or ceremony. make it just work.

# Actual behavior

doesn't work. hangs. wastes my time.

```
~ $ wsl -l
Windows Subsystem for Linux Distributions:
Alpine (Default)
Ubuntu-20.04
Debian

Suggestion [4,General]: The most similar commands are: h, H:, %, ?, cp, cd, md, ll, fl, ft.
~ $ alpine
The I/O operation has been aborted because of either a thread exit or an application request.
```
![image](https://user-images.githubusercontent.com/61225/90198142-e40aa500-de0f-11ea-8c4c-9d8d8b182699.png)

**Comment by therealkenc** [comment]
What does `wsl -l -v` return.

**Comment by airtonix** [comment]
```
~ $ wsl -l -v
  NAME            STATE           VERSION
* Alpine          Stopped         1
  Ubuntu-20.04    Stopped         1
  Debian          Stopped         1
```

**Comment by airtonix** [comment]
i think this has to do with my `$env:Path` is too long. if i reduce it to the wsl.exe path then i can launch. i can't test it now because i forget where the wsl.exe is in order to accurately reduce the `$env:Path` to just where wsl.exe is

**Comment by therealkenc** [comment]
/dupe #5633. You'll be good [next roll](https://github.com/microsoft/WSL/issues/5633#issuecomment-673047918).
