### ISSUE TITLE
"Unspecified error" when launching WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by steveny9911** [microsoft/WSL#5758]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Your Distribution version: 20.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

Seems like Microsoft Store updated Ubuntu 20.04 LTS to version `2004.2020.812.0` for me today.

I'm also using WSL1 Ubuntu 18.04 on the side as well (no issue with 18.04 on WSL1):
```
❯ wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         1
  Ubuntu-20.04    Stopped         2
```

# Steps to reproduce

Launching WSL 2 Ubuntu 20.04 from anywhere - start menu, `ubuntu2004`, cmd, powershell, etc.

#  Expected behavior

Launching `ubuntu2004` should run WSL 2 with Ubuntu 20.04

# Actual behavior

Getting error:
```
Unspecified error
Press any key to continue...
```

**Comment by licanhua** [comment]
Can you check the logs in Windows `Event Viewer`? There should be some error details in the event view

**Comment by steveny9911** [comment]
I'm not sure exactly how to check the logs you're asking, but I took some screenshot of `Hyper-V-Worker` that appeared in the Error event type section.
![Snipaste_2020-08-13_21-57-42](https://user-images.githubusercontent.com/8460976/90215473-901ca380-ddb0-11ea-93cc-11356feb153f.png)
![Snipaste_2020-08-13_21-58-40](https://user-images.githubusercontent.com/8460976/90215475-914dd080-ddb0-11ea-8f36-e93a7d613e54.png)
![Snipaste_2020-08-13_22-01-26](https://user-images.githubusercontent.com/8460976/90215477-91e66700-ddb0-11ea-957b-424d4ea1be7a.png)

**Comment by licanhua** [comment]
From the picture you post, it seems hyper-v may have problem. You'll probably get better feedback in the [microsoft community](https://answers.microsoft.com/en-us/)

I saw some one resolved `The processor topology specified for the virtual machine cannot be supported by this host` by
[enable-processor-compatibility-mode](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn859550(v=ws.11)#to-enable-processor-compatibility-mode-for-a-virtual-machine). I don't know if it fits to you or not.
