### ISSUE TITLE
std::random_device always returns 0xFFFFFFFF.

### ISSUE THREAD

**Issue by llamerada-jp** [microsoft/WSL#5767]
`std::random_device` is a module in the standard library for getting random numbers in C++.
http://www.cplusplus.com/reference/random/random_device/
But in the WSL2 environment, the function always returns 0xFFFFFFFF.

The return value of `std::random_device` is implementation-dependent.
But it's a popular way to use `std::random_device` as the random seed for other algorithms, I think so.
It makes a negative impact on some programs. For example, the simulations continue to produce the same results.

# Environment

## Windows build number:
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

## Distribution version:
```
Release:        20.04
```

## WSL 2:
```
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

## C++ compiler
```console
$ c++ --version
c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## libstdc++
```console
$ dpkg -l | grep libstdc
ii  libstdc++-9-dev:amd64                9.3.0-10ubuntu2                    amd64        GNU Standard C++ Library v3 (development files)
ii  libstdc++6:amd64                     10-20200411-0ubuntu1               amd64        GNU Standard C++ Library v3
```

# Steps to reproduce

- Save a sample program as `main.cpp`.

```C++
#include <random>
#include <cstdlib>

static std::random_device seed_gen;

int main()
{
  printf("%f %x\n", seed_gen.entropy(), seed_gen());
  return 0;
}
```

- Build the program.
```console
$ c++ -O0 -g main.cpp
```

- Run the executable file.
```console
./a.out
```

#  Expected behavior

I can get each random result when I run sample program on the native machine environment.

```
$ ./a.out 
0.000000 521424d2
$ ./a.out 
0.000000 68900f4d
$ ./a.out 
0.000000 b42ba24c
$ ./a.out 
0.000000 14ac82f3
...
```

# Actual behavior

I run it many times, I can get the same result on WSL2.

```
$ ./a.out
0.000000 ffffffff
...
```

**Comment by 0xbadfca11** [comment]
libstdc++'s std::random_device uses RDRAND instruction (when available).
This looks like encountering the RDRAND bug on AMD Ryzen 3000 series processors.

**Comment by therealkenc** [comment]
Thank-you llamerada-jp for the concise submission, and thank you 0xbadfca11 for the excellent answer. I cannot reproduce here on a Ryzen 3950X, but regardless there is no way to call this anything but tag external. If you look at the `strace(1)` log it doesn't even make any syscalls to blame.

![image](https://user-images.githubusercontent.com/7049700/90342680-0d1d6800-dfbf-11ea-87f6-9607dcd4af82.png)

**Comment by llamerada-jp** [comment]
Hi 0xbadfca11, therealkenc
Thank you for your hint.
I used Ryzen 3700X. And I had didn't update bios/firmware from buying the mainboard.
I could avoid this bug by updating bios/firmware.
Thank you.
