### ISSUE TITLE
After enabling WSL2 - Your PC ran into problem

### ISSUE THREAD

**Issue by badri21P** [microsoft/WSL#5770]
I enabled WSL2 on my new laptop with this [reference](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and after restarting my Laptop for update i doesn't started. Looping in "Your Laptop ran into problem contact....". I Ran a startup Diagnostics and the my Laptop booted again. What Happened there is something i don't know.

My Laptop Specs: 
Laptop Name: HP Omen 15
Model Number: 15-en0002AX
Processor: AMD Ryzen 5 4600h
RAM: 8gb 3200mhz
Graphics: 1660ti
Build Version: 2004, 19041.450

I know this is not detailed one to help, Just reporting to the community there is a issue exists.

**Comment by chnyuwen** [comment]
I got the same problem in Omen.
Please start in safe mode, this will also undo the changes.Then uninstall the RyzenmasterSDK application in the settings.

**Comment by chnyuwen** [comment]
Be careful, enabling WSL then causes BSOD when AID64 starts.

**Comment by takizo** [comment]
Can you try uninstall Virtual Machine Platform the BSOD would go away? Possible it's related to #5760

**Comment by badri21P** [comment]
> 
> 
> I got the same problem.
> Please start in safe mode, this will also undo the changes.Then uninstall the RyzenmasterSDK application in the settings.Finally, re-enable WSL。
> 
> Be careful, enabling WSL then causes BSOD when AIDA64 starts.
> My Laptop Specs:
> Laptop Name: HP Omen 15
> Processor: AMD Ryzen 7 4800h
> Build Version: 2004, 19041.450

I didn't do any of that..when boot loped i just ran startup diagnostics..after that windows turned on with WSL enabled. I Just don't know what happened in between that.

**Comment by 19188** [comment]
Same problem.
Ryzen 4600h based laptop, after enabling Virtual Platform Supprot, I got BSOD.
Then I fresh installed Windows 2004(19041.450). But the problem is still there.
It seems that the only way is to enter safe mode and disable that feature by now.

**Comment by badri21P** [comment]
> 
> 
> Same problem.
> Ryzen 4600h based laptop, after enabling Virtual Platform Supprot, I got BSOD.
> Then I fresh installed Windows 2004(19041.450). But the problem is still there.
> It seems that the only way is to enter safe mode and disable that feature by now.

Just run startup Diagnostics it automatically fixes the problem, Atleast for me it happened.

**Comment by badri21P** [comment]
Now i can't do windows updates
1) Updating
2) Restarting...Your PC ran into problems
3) Startup repair
4) undoing update
5) booted back to same build
just updating
