### ISSUE TITLE
Enabling WSL then causes BSOD when AIDA64 starts.

### ISSUE THREAD

**Issue by chnyuwen** [microsoft/WSL#5773]
Enabling WSL then causes BSOD when AIDA64 starts.And installing the SteelSeries mouse driver also got the BSOD.

BSOD stop code: SYSTEM_SERVICE_EXCEPTION
Failed operation：kerneld.x64
kerneld.x64 is a file from AIDA64.

My Laptop Specs:
Laptop Name: HP Omen 15
Processor: AMD Ryzen 5 4800h
Build Version: 2004, 19041.450

**Comment by takizo** [comment]
> Enabling WSL then causes BSOD when AIDA64 starts.And installing the SteelSeries mouse driver also got the BSOD.
> 
> BSOD stop code: SYSTEM_SERVICE_EXCEPTION
> Failed operation：kerneld.x64
> kerneld.x64 is a file from AIDA64.
> 
> My Laptop Specs:
> Laptop Name: HP Omen 15
> Processor: AMD Ryzen 5 4800h
> Build Version: 2004, 19041.450

If you recently upgrade to KB4566782, it's related to this thread #5760

**Comment by therealkenc** [comment]
> it's related to this thread #5760

There is no data to support the supposition that the BSOD is in any way related to a `WslRegisterDistribution failed with error: 0x80041002` other than the fact you both did a windows update.

/dupe #5770
