### ISSUE TITLE
How to uninstall WSL2 from my windows I have Ubuntu 18.04 and 20.04 

### ISSUE THREAD

**Issue by codingonsteroid** [microsoft/WSL#5776]
Documentation is deprecated as it uses lxrun: https://docs.microsoft.com/en-us/windows/wsl/faq

```
(base) PS C:\WINDOWS\system32> lxrun /uninstall /full
lxrun : The term 'lxrun' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lxrun /uninstall /full
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (lxrun:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by therealkenc** [comment]
Suggestions for improvements and pull request for documentation can be submitted [here](https://github.com/MicrosoftDocs/WSL). Or using the feedback button on the page that you linked.

**Comment by codingonsteroid** [comment]
ok but is the answer @therealkenc ??

**Comment by therealkenc** [comment]
For distributions, "right-clicking on the app tile and clicking Uninstall", per the documentation you linked.

For WSL proper, the opposite of how you installed it. Uncheck "Windows Subsystem for Linux" and "Virtual Machine Platform" in "Control Panel ➡️ Programs ➡️ Programs and Features ➡️ Turn Windows features on or off". Or [with dism](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/enable-or-disable-windows-features-using-dism) in an elevated prompt.

**Comment by codingonsteroid** [comment]
Thankyou
