### ISSUE TITLE
WSL characters get corrupted after a while

### ISSUE THREAD

**Issue by martnd** [microsoft/WSL#5777]
After my Ubuntu 20.4 WSL terminal has been spewing a large amount of output - eg. when running a full integration test suite, the output becomes garbled, as though it is trying to use the wrong character standard.  

Like this:

s.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
[INFO] GCLOUD:  at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:28)
[INFO] GCLOUD:  at org.eclipse.jetty.servlet.ServletHandler$CachedCAhuagi n1.7d,o 2F0i2l0t e1r0(:S3e2r:v4l0 PeMt Hoarndg.qluearr.tjzava.:c1o5r9e6.)Q
uartzSchedu[[1e;r3 4<miInNiFtO[
mI]NF OG:C LQOuUaDr:t z  atS cohregd.uelecrl ivp.sUeN.KjNeOtWtNy..UNKsNeOrWvNl.eUtN.KSNeOrWvNl ectrHeaantdeld.
Aeug r1.7d,o H20a2n0d l1e0(:Se3r2v:l4e0t HPaMn dolregr.j.aqvau:a5r4t5z).
simpl.RAM[JÛâ±»Ó³ô´ïíòÉåÎ ÆéÏîÛôíéÝá ìÇéÃúÌåÏ
ÕÉÄÎºÆ Ï        ºá ôÒ ÁïÍòÊçï®âåÓãôïìòéåð éóîåéô®êéåôáôìùé®úóååäò®ö
åò®èáîäìÁåòõ®çÓ ãï±ðåä·Èá¬î ä²°ì²°å ò±®°èºá³î²äºì´å°¨Ó ãÐïÍð åïäÈòáçîä®ìåñòõ®áòêôúá®öéáíºð±ì´®³Ó©ô
íÏÝº  ÇÃÑÌõÏáÕòÄôºú  ôÛáóáôã èïåòäçõ®ìååãòì é§ðÄóååæ®áêõåìôôôùÑ®õóáåòãôõúòÓéãôèùå®äÓõåìãåõòò§é ôéùîÈáéîôäìéåáòì®éèúáåîää ìæåò¨ïÓíå ãäõåòæéáôõìùôÈ áòîåäóìïåõòò®ãêåá æéöìáåº µé¶î¶ ©Ñ
õáòôú ðáãëáçåº §ñõáòôú®ðÛÛï±ðåò»ô³é´åíóÉ§Î
ÆÏÝ ÇÃÌÏÕÁÄõºç          ±á·ô¬  ï²ò°ç²®° å±ã°ìºéð³óå²®ºê´å°ô ôÐùÍ® óïåòòçö®åñòõ®áèòáôîúä®ìéåíòð®ìÈ®áÓîôääÓãìèååäòõ×òìáåðòðÆåáòã®ôèïáòîùä ìéåî¨óÈôááîîäôìéåáòô×åò
áÉðÎÆÏº Ñõáòôú óãèåðäõìåò öåòóéïîº ÕÎËÎÏå×Î®òÕ®ÎêËáÎöÏá×ºÎ±®²Õ·Î©Ë
ÎÏ×Î
Áõç ±·¬ ²°²° Û±´É°Î ÆÐÏÍãíïÝí ®ÇçÃïÌïÏçÕìÄåº® á ðáðôå îïçòéçî®åå®ãáìðééð®óôåá®óêëåñôõôåùõ®åó®åäòåööå®òÌ®ïèãááîìäÔìáåóòë®ÑÓõãåïõðåå äóÈôááîòäôìßå
òÉ®ÎîÆåÏøºô ÈÌáïîãäáììå ¨ôÓáóë ñõåõå éîéôéãáìéúåïäð å÷äéÈôáèî âäáóìåå òõ®òêìá öèáôôðº¯¯ìïãáìèïóôº¸°º¸°
²³Áµõ©ç
 ±·¬ ²°²° ±°º³²º´° ÐÍ ïòç®ñõáòôú®ãïòå®ÑõáòôúÓãèåäõìåò óèõôäï÷î
ÉÎÆÏº Óãèåäõìåò ÄåæáõìôÑõáòôúÓãèåäõìåòß¤ßÎÏÎßÃÌÕÓÔÅÒÅÄ óèõôôéîç äï÷î®
Áõç ±·¬ ²°²° Û±Ûº±³»²³º´´í°É ÎÐÆÏÍïíòÝç ®ÇñÃõÌáÏòÕôÄúº® ã       ïáòôå ®ïÑòõçá®òåôãúìÓéãðèóåäõìåò óôáîäâù
ÉÎÆÏº Óãèåäõìåò ÄåæáõìôÑõáòôúÓãèåäõìåòß¤ßÎÏÎßÃÌÕÓÔÅÒÅÄ ðáõóåä®
å®êåôôù®óåòöåò®óåóóéïî®ÓåóóéïîÈáîäìåò®äïÈáîäìå¨ÓåóóéïîÈáîäìåò®êáöáº±¶±°©

Once it is in this state, even the characters I type are garbled.  I have to close the terminal and reopen to get it back to normal.

Any ideas?

**Comment by therealkenc** [comment]
/template

... and more of a serverfault or [stackexchange](https://unix.stackexchange.com/questions/109650/some-garbage-characters-in-linux-terminal) and Linux [blogs](https://www.cyberciti.biz/tips/bash-fix-the-display.html) kind of thing. Combination of `stty sane` and `tput reset` usually corrects.
