### ISSUE TITLE
WSL2 latest update - wsl.exe fails to terminate entries in the wsl -l -v  listing.

### ISSUE THREAD

**Issue by dsjm1** [microsoft/WSL#5778]
This came about after days of setting up Linux 18.045 and 20.04 on three work servers.

We installed off microsoft store on one server then did exports & imported onto 2 other servers.

The problems began with constant errors trying to install MySql 8. The installs were failing. But, despite that we persevered and got MySql running.  During this we did several import efforts.

Then when we tried to tidy up we had wsl -l -v entries that we had tried to terminate.
See the below attempt to terminate  -  we have tried looking for registry entries that we are sure are causing the problem (i.e. entries left in the registry after a partial removal).  WE even tried removing wsl2 using windows features list to remove wsl then reboot. But after re-enabling wsl and running wsl -l -v those rogue entries are still there ?

How can we clean this up ?

Thanks

![wsl2-terminmnates](https://user-images.githubusercontent.com/399801/90469261-b5683380-e15b-11ea-9268-15b93ac1a183.jpg)

**Comment by therealkenc** [comment]
The word "terminate" (in this context) means "stop". You probably want [`--unregister`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#unregister-and-reinstall-a-distribution).

**Comment by dsjm1** [comment]
Yes - that was it - working to hard n long and was using --shutdown then --terminate.

Thankyou that got rid of those 'rogue' entries

D
