### ISSUE TITLE
Upgrading from WSL1 to WSL2 breaks custom hostnames

### ISSUE THREAD

**Issue by sylfabre** [microsoft/WSL#5780]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Install Ubuntu 20.04 with WSL 1

2. Install Apache2 in WSL
```
sudo apt-get install apache2
```

3. Create an hello world file in Windows
```
#/mnt/c/www/index.html
Hello world!
```

4. Configure a virtual host
```
# /etc/apache2/sites-enabled/custom.conf

Listen 0.0.0.0:80

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /mnt/c/www

    <Directory "/mnt/c/www">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

5. Reload Apache2
```
sudo service apache2 restart
```

6. Install (Acrylic DNS)[https://mayakron.altervista.org/support/acrylic/Home.htm] to define wildcard subdomain as local hosts.
```
# Acrylic hosts file
127.0.0.1 *.test.tld
```

7. Configure Acrylic to bind port 55 instead of 53 to free the 53 for WSL2 (as reported here https://github.com/microsoft/WSL/issues/4432#issuecomment-528185325)
```
# Acrylic conf file
LocalIPv4BindingPort=55
LocalIPv6BindingPort=55
```

8. Restart Acrylic

9. Install [Yoga DNS](https://yogadns.com/) 

10. Define Acrylic as a DNS server for Yoga DNS
![image](https://user-images.githubusercontent.com/3177556/90484428-7378c680-e136-11ea-8979-68276119c0d4.png)

11. Define a Yoga DNS rules to route DNS queries to Acrylic for *.test.tld
![image](https://user-images.githubusercontent.com/3177556/90484619-b89cf880-e136-11ea-8ad3-2f40553a1a5d.png)

12. Check browsing to http://local.test.tld works in Chrome

13. Upgrade your WSL to version 2 in PowerShell as admin
```
wsl --set-version Ubuntu-20.04 2
```

14. Restart Apache in WSL 2
```
sudo service apache2 start
```

#  Expected behavior

Chrome still displays a page at http://local.test.tld

# Actual behavior

Chrome displays an error page at http://local.test.tld "ERR_CONNECTION_REFUSED"

# Additionnal information
* It works if you define the following (mind the localhost as the first hostname on 2nd line cf https://github.com/microsoft/WSL/issues/4353#issuecomment-567968418) but you cannot have wildcard
```
# c:\windows\system32\drivers\etc\hosts
127.0.0.1 local.test.tld
::1 localhost local.test.tld
```

* Accessing http://localhost/ works in Chrome in WSL2

* Using the WSL 2 with the IP found with `ip addr | grep eth0` does not work neither with:
- A ping from Windows
- In the Windows hosts file
- In Acrylic hosts file

**Comment by stevebovy** [comment]
WSL2  Wish-List Feature Fix ??  

PROBLEM DESCRIPTION: "DOUBLE TROUBLE"

NON UNIQUE WSL2 HOST NAME CREATES UNNECESSARY  "NAME RESOLUTION"  CONFUSION  WHICH CAN CURRENTLY ONLY BE WORKED

AROUND BY USING FULLY-QUALIFIED HOST NAME

Example of   problem   (Accessing  Windows Host X-Serv) 

The following will not work:   DISPLAY=HOSTNAME:0

THE WORK AROUND IS  DISPLAY=HOSTNAME.WINHOST-DOMAIN:0

Additional  wsl.conf   Network   Keywords  ??

Allow custom configuration of  HOSTNAME  file   so  that  WSL2 VM  machine network name is unique and different from windows

host machine name  (  I would prefer the default to be the linux distribution name )  this would of course impact the HOST file as well

**Comment by Biswa96** [comment]
I am not sure if this feature is documented or available in stable Windows OS versions. For my case, I have tried this in latest Windows Insider build and it works. Create a `/etc/wsl.conf` file in your preffered WSL-ed GNU/Linux distribution. Add the following two lines in that `/etc/wsl.conf` file.

```ini
[network]
hostname = HelloWorld
```

Change the host name as you want.

**Comment by therealkenc** [comment]
> [`network]`
> `hostname = HelloWorld`
> Change the host name as you want.

That doesn't expose the hostname to Windows. Whether that is by-design or WIP I can't say.

**Comment by Biswa96** [comment]
In `/etc/hosts` file, `127.0.1.1` is assigned to the host name. It can be used somehow.

**Comment by therealkenc** [comment]
The somehow is you can [`gethostbyname(3)`](https://man7.org/linux/man-pages/man3/gethostbyname.3.html) in WSL. Fornow.

**Comment by therealkenc** [comment]
> Chrome displays an error page at http://local.test.tld "ERR_CONNECTION_REFUSED"

Whatever circuitous path Yoga and Acrylic are taking, the result is an ipv4 address is being given to Chrome. There's no ipv4 listener on the WSL2 side.

![image](https://user-images.githubusercontent.com/7049700/92559485-88241800-f225-11ea-891e-a9bfdad15c8b.png)

/dupe #4851 #5298

Similar #5844 ([message](https://github.com/microsoft/WSL/issues/5844#issuecomment-686645177)), your options are: (a) get Chrome to point at ipv6 `::1` via your DNS scheme, or, (b) get apache2 to listen on ipv4.

Spiritually related #4592 ([message](https://github.com/microsoft/WSL/discussions/4592#discussioncomment-63110)), whether bouncing DNS queries off of two third-party Windows networking services is a good idea can be left to the beholder. For an alternate approach to accomplishing a similar end result, folks may want to consider [`avahi-daemon(8)`](http://manpages.ubuntu.com/manpages/bionic/man8/avahi-daemon.8.html).

**Comment by gmnowels** [comment]
> I am not sure if this feature is documented or available in stable Windows OS versions. For my case, I have tried this in latest Windows Insider build and it works. Create a `/etc/wsl.conf` file in your preffered WSL-ed GNU/Linux distribution. Add the following two lines in that `/etc/wsl.conf` file.
> 
> ```ini
> [network]
> hostname = HelloWorld
> ```
> 
> Change the host name as you want.

Need to restart to see the change. What this does is change the name /etc/hosts file; where as, changing in the host file does not persist. In this case the wsl.conf settings will not persist.
