### ISSUE TITLE
Latest Windows 10 update 19041.450 breaks WSL VPN access (Cisco Anyconnect)

### ISSUE THREAD

**Issue by tonyppe** [microsoft/WSL#5782]
System info: 
Windows 10 build 19041.450
WSL Ubuntu 18.04.4

Expectation (this was the case before Windows update yesterday 18/08/20)
1. use Windows 10 gui to connect to corp VPN via Cisco Anyconnect SSL VPN (Version 4.8)
2. Use WSL to establish an SSH connection to an instance in the corp network. Destination IP is an encrypted network on the remote side of the VPN tunnel
3. ssh successful 

Reality:
1. use Windows 10 gui to connect to corp VPN via Cisco Anyconnect SSL VPN (Version 4.8)
2. ssh failure to establish - destination is unreachable

Previously to the current update as mentioned and for the last few years this has been working fine. It no longer works today. Is this by design? Or has some setting or configuration change been applied with the update? I mean to ask, can I resolve this or do we need to wait for a fix from Microsoft? 

Thanks

**Comment by ec-max** [comment]
Are you sure this isn't just the 'WSL/HyperV picks a random private network range each boot' issue? 

https://github.com/microsoft/WSL/issues/5764

Open a command prompt and type `route print` to see if the network range used by your corp network conflicts with the network used by the WSL virtual switch.

**Comment by tonyppe** [comment]
i didnt close it as completed now, I closed it without a comment.
