### ISSUE TITLE
WSL 2 Internet connection doesn't work until I connect to VPN

### ISSUE THREAD

**Issue by N-Molham** [microsoft/WSL#5784]
# Environment

```none
Windows build number: `10.0.19041.0`
Your Distribution version: `Ubuntu 20.04`
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

To make internet connection working on WSL2 machine, I have to connect to VPN (Wire Guard) first, otherwise it doesn't work

This wasn't the case, it was working fine (with TunSafe VPN client) installed without any issue, I believe this issue surfaced after the latest windows update a couple of days ago. I am not sure what causing this problem, windows update is the only thing changes without me doing anything.

# Steps to reproduce
1. Connect to VPN, I use TunSafe
2. In WSL2 I have to edit `/etc/resolv.conf` and change the nameserver from `172.20.144.1` to something like `1.1.1.1` or `8.8.8.8`
3. If I changed the nameserver back or disconnect from the VPN, internet connection stops

**WSL logs**:  I tried to follow the steps but I didn't get the last option/tab which I can collect the logs

#  Expected behavior

I should have internet connection on my WSL2 machine

# Actual behavior

As described, I have to connect to VPN server and change nameserver to make it work

# More data

### Network adapters
![image](https://user-images.githubusercontent.com/3770036/90670279-3eae6180-e253-11ea-8083-ea91c1a9897a.png)

### Wi-Fi Adapter sharing settings, I already tried turning this on/off states
![image](https://user-images.githubusercontent.com/3770036/90670553-a82e7000-e253-11ea-995b-e88b901ff5f4.png)

### WSL Adapter
![image](https://user-images.githubusercontent.com/3770036/90670642-ca27f280-e253-11ea-928c-cc47518da28d.png)

### Default Switch adapter
![image](https://user-images.githubusercontent.com/3770036/90670701-db70ff00-e253-11ea-95f3-f93cb2c559a5.png)

Hope this helps to solve the problem that I am having as I need WSL for my web development work

**Comment by wushangwei** [comment]
I once had the opposite problem: WSL2 lost internet connection when connected to WIreGuard VPN.

I solved the problem by editing the "AllowedIPs“ field of WireGuard conf:
`[Interface]
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Address = 10.88.88.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
PresharedKey = zzzzzzzzzzzzzzzzzzzzzzzzzzzzz
AllowedIPs = ::/128, 0.0.0.0/1, 128.0.0.0/1
Endpoint = xxx.xxx.xxx.xxx:xxxxx`

Hope it will help you.

**Comment by N-Molham** [comment]
Thanks @wushangwei it worked

**Comment by rajnathsah** [comment]
Run below from powershell in admin mode for cisco any connect vpn.

Get-NetAdapter | Where-Object {$_.InterfaceDescription -Match "Cisco AnyConnect"} | Set-NetIPInterface -InterfaceMetric 4000
Get-NetIPInterface -InterfaceAlias "vEthernet (WSL)" | Set-NetIPInterface -InterfaceMetric 1

**Comment by jrgilman** [comment]
> I once had the opposite problem: WSL2 lost internet connection when connected to WIreGuard VPN.
> 
> I solved the problem by editing the "AllowedIPs“ field of WireGuard conf:
> `[Interface]
> PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Address = 10.88.88.2/24
> DNS = 1.1.1.1
> 
> [Peer]
> PublicKey = yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
> PresharedKey = zzzzzzzzzzzzzzzzzzzzzzzzzzzzz
> AllowedIPs = ::/128, 0.0.0.0/1, 128.0.0.0/1
> Endpoint = xxx.xxx.xxx.xxx:xxxxx`
> 
> Hope it will help you.

This worked for us just now! Awesome :) No idea why though, 0.0.0.0/0 should be identical to 0.0.0.0/1 and 128.0.0.0/1???

**Comment by juanmirocks** [comment]
If you are using WireGuard VPN, this might help: https://github.com/microsoft/WSL/issues/5784#issuecomment-679969533

**Comment by mys2kor** [comment]
> Run below from powershell in admin mode for cisco any connect vpn.
> 
> Get-NetAdapter | Where-Object {$_.InterfaceDescription -Match "Cisco AnyConnect"} | Set-NetIPInterface -InterfaceMetric 4000 Get-NetIPInterface -InterfaceAlias "vEthernet (WSL)" | Set-NetIPInterface -InterfaceMetric 1

Hi, I am having the same issue (WSL 2 Internet connection doesn't work until I connect to VPN) but I use `cisco any connect vpn`. I tried running the commands you mentioned but I get error. I am running Windows 11. Further details of my issue can be found here.
![image](https://github.com/microsoft/WSL/assets/109787441/44473b4f-2712-4b35-be79-df6e799d5835)
