### ISSUE TITLE
Error with redirects when using wsl.exe to exec command in distro

### ISSUE THREAD

**Issue by linuxrebel** [microsoft/WSL#5785]
Edition: Windows 10 Enterprise
Version 204
OS Build 1941.264

**Exists both on WSL 2 and WSL 1**

**Code:**
wsl.exe -d distro -u root -e echo "this is a test" >> /home/$user/somefile or
wsl.exe -d distro -u root -- echo "this is a test" >> /home/$user/somefile

**What is expected:**
   This should echo the string give into the file given.  

What does happen;  A variety of errors dependent upon nesting of " and '  Even if I can get the command to run without error.  The file is not created. For example this runs

   wsl.exe -d distro -u root  -- 'echo "this is a test" >> /home/$user/somefile' 

however despite running without error the command does not produce the desired result

**Most common error is:**
   The file C:\home\$user\somefile does not exist or you do not have permission

**Comment by therealkenc** [comment]
/dupe #5551 #5232 ([message](https://github.com/microsoft/WSL/issues/5232#issuecomment-631210016)) #5270 #3284
