### ISSUE TITLE
WSL Virtual Switch missing

### ISSUE THREAD

**Issue by atnoslen** [microsoft/WSL#5788]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Open Hyper-V Manager as Administrator
2. Click `Virtual Switch Manager...`
3. Only Default Switch is listed.

**WSL logs**: 

#  Expected behavior

The WSL2 switch that I can modify to bridged rather than NAT.

# Actual behavior

![image](https://user-images.githubusercontent.com/3331625/90836751-11ba8700-e305-11ea-97ac-3094c3ae1f49.png)

**Comment by hackermondev** [comment]
how to fix?
