### ISSUE TITLE
WSL distros suddenly duplicates itself - Multi user Environment

### ISSUE THREAD

**Issue by JacobsonLantern** [microsoft/WSL#5797]
# Environment

```none
Windows build number: 10.0.19042.0
Your Distribution version: Whole WSL infrastructure (not distro specific)
Whether the issue is on WSL 2 and/or WSL 1: Both
Last updates installed: KB4566782 on August 8th, 2020 and Feature update to Windows 10, version 20H2 on July 25th, 2020
Windows Insider Build channel: Beta
```

# Steps to reproduce
Upon opening Windows Terminal, 
![image](https://user-images.githubusercontent.com/58499468/90995243-87647280-e5e5-11ea-8ed1-90684752cc33.png)
Which translates to:
**Errors occurred while loading user settings**
Several profiles with the same GUID were found in your settings file - duplicates are ignored. Make sure that the GUID of each profile is unique.

using 'wsl -l -v' on powershell: (not as admin)
![image](https://user-images.githubusercontent.com/58499468/90995348-e1653800-e5e5-11ea-909f-d5d1f5613609.png)
It listed 10 distros, 5 are duplicates.

using 'wsl -l -v' on powershell: (as admin)
![image](https://user-images.githubusercontent.com/58499468/90995895-7f0d3700-e5e7-11ea-9b1b-b14b2265ea61.png)
5 distros are there, even tho no distros were installed before and i believe that WSL is still restricted to within each user space (not allowing cross-user access, like running WSL distro on 1 normal user account, while running docker on admin account). I don't even login to my Microsoft Store account on my admin account too.

Checking registry (HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss): (as normal user, not admin)
![image](https://user-images.githubusercontent.com/58499468/90995412-1a9da800-e5e6-11ea-980f-db8a1a79783d.png)
There are only 5 distros registered, nothing else.

My setup is as follows:
2 user accounts:
- 1 admin (local account, Microsoft store was not logged in)
- 1 normal user (using Microsoft account. Original distro (Ubuntu & Debian) was installed via store, exported to a .tar  and then installed/loaded via  'wsl --import' command (resulted in Ubuntu_Build, Ubuntu_Server, and KanboardServer).

Admin has no WSL installation; user has 5 distros. All WSL activities are performed under user, not admin.

**WSL logs**: 

#  Expected behavior
Only 5 WSL distros listed when performing 'wsl -l -v'

# Actual behavior
WSL listed duplicates of each distros, making it 10 distros, and confusing the Windows Terminal on the duplicated distros.

PS: Why I need 2 user account (admin and normal user)? Security. Also, I am trying to simulate some work environment, where access to admin account is strictly controlled or only allowed under a very strict exception (My last workplace needed me to register to 3 different managers (dept. head, country manager, and ASEAN/APAC manager) just to get permission to upgrade my account as admin), everything else (software install, updates, etc.) only performed via SCCM/Remote Deploy.

**Comment by WSLUser** [comment]
This belongs in the Windows Terminal repo. There must be an unforeseen issue in the way Windows Terminal detects installed distros that affects the multi-user environment.

**Comment by DHowett** [comment]
@wsluser This bug **absolutely** does not belong on the Windows Terminal repository.

As the user noted, `wsl -l` **literally prints the same distributions twice**. How did Terminal cause that?

**Comment by JacobsonLantern** [comment]
Any possible resolution to this? Or is it really unreproducible by anyone but me?

**Comment by JacobsonLantern** [comment]
OK, update:

Somehow, 12 days later (without modifying anything, I guarantee you I did not modify anything):
![image](https://user-images.githubusercontent.com/58499468/92297920-4ddd2100-ef6e-11ea-8f04-8e580329a4e7.png)
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss suddenly listed 10 distros, full of duplicates. Here are examples:

- Duplicated WSL, with 2 different version of WSL
![image](https://user-images.githubusercontent.com/58499468/92297943-867cfa80-ef6e-11ea-8285-21f5b32f66df.png)
![image](https://user-images.githubusercontent.com/58499468/92297957-af9d8b00-ef6e-11ea-9dcd-6131b6cb0abc.png)

- Duplicated WSL with broken path & incomplete 
![image](https://user-images.githubusercontent.com/58499468/92298005-f7241700-ef6e-11ea-8b66-60bcbf45e902.png)
![image](https://user-images.githubusercontent.com/58499468/92298014-03a86f80-ef6f-11ea-964e-605328757815.png)

- Duplicated WSL with misconfigured default UID
![image](https://user-images.githubusercontent.com/58499468/92298039-32bee100-ef6f-11ea-85b9-0043b0de2ebb.png)
![image](https://user-images.githubusercontent.com/58499468/92298044-3f433980-ef6f-11ea-878f-e9cfbbe34090.png)

REPEAT: I did not modify anything since I put up this report 12 days ago! WSL manager did all of this in background (most probably, otherwise what else can do this?)

The only suggestion I can put now to WSL team is to look closely again how WSL distros are registered and managed using WSL.exe. Transitioning to file-based DB for WSL system (using JSON file or any non-binary, human-readable file like text file) will solve this issue, PLUS enabling multi-user WSL experience without having to install 2 sets of WSL or creating this unwanted and unknown duplicates because of multi-user environment confusion. The weakness in registry-based DB is that it is too restrictive since each user has their own environment!
