### ISSUE TITLE
Cant change Files, Access Denied

### ISSUE THREAD

**Issue by daslicht** [microsoft/WSL#5799]
When I open and try to save a file located on my WSL2 installatiion var/www/html folder I get :  
![](https://i.imgur.com/eM3BLMC.png)

How to fix, please?

**Comment by dsjm1** [comment]
I just tried this too. I opened a cmd window, then tried a powershell widow, both as admin, ran the command 'explorer' assuming it would have admin rights and used it to access \\wsl$ but when I tried to change the name of a config file in /etc got stopped saying I needed admin priv.

But, I am sure a few weeks ago I did this (copied a mysql.cnf file over from a win folder) - I do know I copied quite a few files into my WSL2/home/myself folder without any issues.

Has something changed ?

**Comment by squeaky-pl** [comment]
Files outside `/home/user` in Linux are typically owned by root user account/or some other account. You can change the file owner with chown command from Linux (after elevating to root with sudo), chmod or add yourself to the same group depending on what are exact permissions/owner/group on the file in question.

**Comment by squeaky-pl** [comment]
@dsjm1 in your case the fastest course of action is opening Linux terminal and `sudo mv /etc/oldname /etc/newname`. Windows Administrator does not have WSL root permissions becouse you are crossing operating system boundaries.

**Comment by daslicht** [comment]
so  I need to change teh owner of the folder /var/www/html to my linux user name ?

i tried ```sudo chown -R myusernme /var/www/html``` but that doesnt change a thing 
with ls -al it still shows the owner root

**Comment by dsjm1** [comment]
squeaky-pl

Thanks - was thinking it would be something like that

Cheers Dsjm1

**Comment by inigopascall** [comment]
> 
> 
> @dsjm1 in your case the fastest course of action is opening Linux terminal and `sudo mv /etc/oldname /etc/newname`. **Windows Administrator does not have WSL root permissions because you are crossing operating system boundaries. Only files owned by normal user (everything in `/home/<user>`) are working out of the box**.

Interesting. This doesn't work for me; I've created a directory called `/home/inigo/projects` and can't edit anything in it, or under `/home/inigo`, at all. I can open files in Sublime Text or Notepad++ but attempting to actually save them gives me permission errors. I don't understand this..?
