### ISSUE TITLE
Error on startup: mount: /proc: proc already mounted on /proc.

### ISSUE THREAD

**Issue by dDanissimo** [microsoft/WSL#5800]
# Environment

```
Windows build number:
[Version 10.0.19041.450]

Your Distribution version:
Debian 11 (Debian-based Pengwin/WLinux)

Whether the issue is on WSL 2 and/or WSL 1:
WSL 2 (command output: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)))
```

# Steps to reproduce

1) Install fresh new Pengwin distribution from Microsoft Store
2) Launch it, do a pengwin-setup embedded command query to install essential utilities, if asks to upgrade system packages, do so, next, select the following: 
![image](https://user-images.githubusercontent.com/56019205/91019294-732a7080-e5f9-11ea-9867-be9d2d831636.png)

Then, In each of the categories:
![image](https://user-images.githubusercontent.com/56019205/91019342-84737d00-e5f9-11ea-9584-33ce26c8c3c4.png)

![image](https://user-images.githubusercontent.com/56019205/91019366-8c332180-e5f9-11ea-857f-633b7c61419c.png)

![image](https://user-images.githubusercontent.com/56019205/91019423-9f45f180-e5f9-11ea-8ee4-e7ae8508a526.png)

![image](https://user-images.githubusercontent.com/56019205/91019442-aa991d00-e5f9-11ea-9c04-1ab9f5f1d04a.png)

![image](https://user-images.githubusercontent.com/56019205/91019460-b1c02b00-e5f9-11ea-8053-26b1ca5ccc9a.png)
in sub-categories, select all of offered (e.g. shells - fish AND zsh AND csh AND bash BASH-RL, languages - configure ALL locales, leave en_us.UTF8 by default)

Everything seems to install properly, Pengwin will terminate itself after setup is done, relaunch.

**WSL logs**: 

#  Expected behavior

You should be meeted with nothing but an empty command-prompt, like this:
![image](https://user-images.githubusercontent.com/56019205/91019722-22674780-e5fa-11ea-8bb4-c08b3a434b35.png)
(no, i did not encounter this, i just scrolled down :D)
And you can continue to work with WSL afterwards.

# Actual behavior

Instead, on launch of your distro, this happens.
![image](https://user-images.githubusercontent.com/56019205/91020111-b76a4080-e5fa-11ea-8083-4e93ced83740.png)
However, /etc/fstab shows following:
![image](https://user-images.githubusercontent.com/56019205/91021476-84c14780-e5fc-11ea-87d8-1e0833e7f11b.png)
Nothing useful here, but /proc/mounts though shows that proc is mounted, and everything is ok:
`archangel@ikelos-a:~$ cat /proc/mounts                                                                                  /dev/sdb / ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0                                                  tmpfs /mnt/wsl tmpfs rw,relatime 0 0                                                                                    tools /init 9p ro,dirsync,relatime,aname=tools;fmask=022,loose,access=client,trans=fd,rfd=6,wfd=6 0 0                   none /dev devtmpfs rw,nosuid,relatime,size=3222184k,nr_inodes=805546,mode=755 0 0                                       sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0                                                                     proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0                                                                      devpts /dev/pts devpts rw,nosuid,noexec,noatime,gid=5,mode=620,ptmxmode=000 0 0                                         none /run tmpfs rw,nosuid,noexec,noatime,mode=755 0 0                                                                   none /run/lock tmpfs rw,nosuid,nodev,noexec,noatime 0 0                                                                 none /run/shm tmpfs rw,nosuid,nodev,noatime 0 0                                                                         none /run/user tmpfs rw,nosuid,nodev,noexec,noatime,mode=755 0 0                                                        binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0                                                        tmpfs /sys/fs/cgroup tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0                                                 cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0                                   cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0                                          cgroup /sys/fs/cgroup/cpu cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0                                                cgroup /sys/fs/cgroup/cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0                                        cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0                                            cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0                                          cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0                                        cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0                                        cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0                                        cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0                                  cgroup /sys/fs/cgroup/net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio 0 0                                      cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0                                        cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0                                              cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0                                              C:\134 /mnt/c 9p rw,dirsync,noatime,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;uid=1000;gid=1000;umask=0022;fmask=11;case=off;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8 0 0                                    D:\134 /mnt/d 9p rw,dirsync,noatime,aname=drvfs;path=D:\;uid=1000;gid=1000;metadata;uid=1000;gid=1000;umask=0022;fmask=11;case=off;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8 0 0
archangel@ikelos-a:~$`
We see that everything is ok with /proc, but i'm not sure what causes additional mount on startup
I am not that sort of an advanced user when it comes to thin lines of disk mounting and other stuff like what can cause mount on linux system boot, etc., so that is why I am texting here. I assume I should also forward the issue to Whitewater Foundry, the team behing Pengwin, but I also thought that would be necessary to post this initially on WSL repo, probably this is sort of a known issue.

**Comment by dDanissimo** [comment]
will attach my logs a little bit later, struggling with the feedback hub thing, i cannot switch my diagnostics data to full for some reason, troubleshooting that.

**Comment by dDanissimo** [comment]
i cant attach logs though, i cant change my diagnostic data to full for some reason, probably there's a trouble with registry that blocks me off, i dunno, currently in progress of solving this

**Comment by dDanissimo** [comment]
is there an alternative way to attach the logs? i suppose this issue is too complicated, i wish to keep on the context of the issue with the WSL

**Comment by therealkenc** [comment]
>  i'm not sure what causes additional mount on startup

You might be able to get an answer [here](https://github.com/WhitewaterFoundry/Pengwin/issues).

**Comment by wjm1191** [comment]
I have the same problem. It takes about 40 seconds to show the normal bash command line. But the Ubuntu 20.04 lts starts up immediately.
