### ISSUE TITLE
WSL2: An error occurred mounting one of your file systems

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#5804]
Windows 10 20197

When starting a WSL2 distro, I get the following message

`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.`

`dmesg` shows the following output

https://pastebin.com/4ZQHaNT1

And then, instead of pointing me to my `~` directory, I get pointed to

`/tmp/docker-desktop/shadowing-mounts/8075fc768312cf969c689ed2d4db67152ee3fd35e592ac485fe5efb168438811/tmp/docker-desktop/shadowing-mounts/1e7201140ddad79cb5f56b865f120c17779cd03beb2dc0656b7c4990034a06dd/tmp/docker-desktop/shadowing-mounts/18e2f3d30a33dd87be4a2e49c70726a143cf274b2ec124d7d6d12ac15a2c83e5/tmp/docker-desktop/shadowing-mounts/e4961029817803b361491465f1726af1c7b9618a586fa2c72d39b833a5f4cd2e/tmp/docker-desktop/shadowing-mounts/d4bb56114d3f0d766cac5a5af05200b79ceb2960c110ceef776a9098e203b31b/tmp/docker-desktop/shadowing-mounts/1ff255f984cfad458f609a5b6ffb494be3e378265a81dee199565f66b48cbd18/tmp/docker-desktop/shadowing-mounts/694d476a1103ec743794f4a691298e0b62d5ddde028e79264b152afab9f0f49a/tmp/docker-desktop/shadowing-mounts/f2f0554f0003229c1cc9b2b57d3f23ad2bf267ff08c92b80c4a05e40276e5410/tmp/docker-desktop/shadowing-mounts/a8be1b0843f151dfed67e4e616162638c94a60da850e76e4ccc9f76645f2c111/tmp/docker-desktop/shadowing-mounts/06b615746dc4b6b867d51db6485c56c402ba5733159f76cc06ccb8eb5ada2432/mnt/c/Users/add `

**Comment by therealkenc** [comment]
There appears to be lines cut off from your `dmesg` before timestamp `34.525372`.

**Comment by IanAWP** [comment]
also reported here
https://github.com/docker/for-win/issues/8186
