### ISSUE TITLE
Unable to start wsl, only cursor

### ISSUE THREAD

**Issue by AMIRIOX** [microsoft/WSL#5807]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1016]
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL1
```

# Steps to reproduce

* start `ubuntu1804.exe`. It only shows the cursor
* I waited for nearly half an hour, but it still doesn't work.
* I try to restart my Windows,  it still doesn't work.
* Then I try to start the `wsl.exe`, only shows the cursor, too.

#  Expected behavior

I just want to start wsl like yesterday.

# Actual behavior

![dcd8OO.png](https://s1.ax1x.com/2020/08/25/dcd8OO.png)

# Other

Since the last normal use until today, there is no suspicious action. I don't know if it is automatically updated. In fact, since the normal startup yesterday, my computer has been shut down.

**Comment by mrneo240** [comment]
Affected here as well, wsl.exe and all distro specific entry points hang. 
Restarting vmcompute or machine itself does not restore

**Comment by AMIRIOX** [comment]
@mrneo240 Uh, I don’t quite understand what you mean, what is "Affected here as well"? What happened? How should I deal with it?

**Comment by AMIRIOX** [comment]
@mrneo240 Uh, I don’t quite understand what you mean, what is "Affected here as well"? What happened? How should I deal with it?

**Comment by radovanobal** [comment]
also affects windows build 20197

**Comment by AMIRIOX** [comment]
> 
> 
> also affects windows build 20197, probably related to: #5768
> 
> for the reproduction step,
> 
> update windows to latest insider build from dev
> restart computer
> attempt to run wsl distro
> 
> as soon as any attempt at starting a distro is made lxmanager stops responding and hangs, being unable to start or stop it most of the times

My operating system is Windows build 1909, so I cannot use `--set-default-version 2` or `--update`, what can I do? If 2004 and above are necessary, thanks for reply!

**Comment by radovanobal** [comment]
> 
> 
> > also affects windows build 20197, probably related to: #5768
> > for the reproduction step,
> > update windows to latest insider build from dev
> > restart computer
> > attempt to run wsl distro
> > as soon as any attempt at starting a distro is made lxmanager stops responding and hangs, being unable to start or stop it most of the times
> 
> My operating system is Windows build 1909, so I cannot use `--set-default-version 2` or `--update`, what can I do? If 2004 and above are necessary, thanks for reply!

What I had to do is revert to a previous build, in my case that's build 20190

**Comment by AMIRIOX** [comment]
I did nothing, and after three days, it can start normally again
What a strange thing

**Comment by med100s** [comment]
I solved this by turning off and on option windows subsystem for linux  in windows features, restarted windows 2 times
