### ISSUE TITLE
Solution for Hi-DPI feature of jetbrains IDE make UI too big running VcXsrv

### ISSUE THREAD

**Issue by vasilvestre** [microsoft/WSL#5808]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.450]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Install VcXsrv on your windows host, install phpstorm and set this in ~/.bashrc 

```bash
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
export GDK_SCALE=2
```

Then launch phpstorm.

# Actual behavior

Here on my 1920*1080 3 screens (IRL), is the VcXsrv windows containing phpstorm. The font is quite normal considered how big the UI is.

![image](https://user-images.githubusercontent.com/17164385/91148126-83098980-e6b9-11ea-8fd7-28b514607722.png)

# How I fixed (workaround)

[this link](https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration) explains that the "auto-detect dpi" feature may break some display. I added `-Dsun.java2d.uiScale.enabled=false` to my JVM settings and it fix the problem. However, I have the same problem if I launch gitkraken.

# How I should have fixed (workaround)

```bash
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
export GDK_SCALE=1 #I don't know why but 2 was bad, seem like this env var isn't even needed
```

**Comment by devcircus** [comment]
As gui apps aren't officially supported yet, doubt they'll be willing to address it.

**Comment by Biswa96** [comment]
This answer may help https://superuser.com/a/1370548/726810

**Comment by therealkenc** [comment]
> As gui apps aren't officially supported yet, doubt they'll be willing to address it.

It isn't that X11/GTK apps aren't (super scary quote) "supported" per se, but that the submission is squarely tag linux-behavior (plus VcXsrv behavior). There is no (obligatory pronoun) _it_ bug to address _in WSL_. WSL will dutifully send the X11 protocol down tcpv4 port 6000 that the kernel is told to send.
