### ISSUE TITLE
MemoryError in Jupyter Notebook while performing label spreading (sklearn)

### ISSUE THREAD

**Issue by dleviminzi** [microsoft/WSL#5809]
# Environment

```none
Build 20197.rs_prerelease.200818-1420
```

# Steps to reproduce

 ```
from sklearn.semi_supervised import LabelSpreading
label_prop_model = LabelSpreading() 
```

 free -h returns the following
```
              total        used        free      shared  buff/cache   available
Mem:           7.8G        4.3G        2.3G         80K        1.1G        3.2G
Swap:          2.0G          0B        2.0G
```

#  Expected behavior

 I just want it to continue on with the operation.

# Actual behavior

I get a memory error (below). It seems this is because there is not enough memory being given the vm. From free -h it seems to be getting 16gb memory. Is there anyway to up this value? I have 32gb memory in my system.

MemoryError: Unable to allocate 9.40 GiB for an array with shape (50229, 50229) and data type float32

**Comment by therealkenc** [comment]
Yeah. Starting with [20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175) WSL2 started imposing a default memory upper bound of 8GB to help mitigate #4166. There is no repro here, but taking that error at face value, you'll have to manually modify your [`%USERPROFILE/.wslconfig`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) `memory=` parameter to something larger. For you, `memory=16GB` or something like that.

![image](https://user-images.githubusercontent.com/7049700/91238009-e06cfd00-e6f0-11ea-8d2e-ce3cabb2d6f0.png)

[As an aside, that the default upper bound was made 8GB instead of the (to me) obvious choice of 6.40GB was a missed humor opportunity. Just sayin'.]

**Comment by dleviminzi** [comment]
> Yeah. Starting with [20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175) WSL2 started imposing a default memory upper bound of 8GB to help mitigate #4166. There is no repro here, but taking that error at face value, you'll have to manually modify your [`%USERPROFILE/.wslconfig`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) `memory=` parameter to something larger. For you, `memory=16GB` or something like that.
> 
> ![image](https://user-images.githubusercontent.com/7049700/91238009-e06cfd00-e6f0-11ea-8d2e-ce3cabb2d6f0.png)
> 
> [As an aside, that the default upper bound was made 8GB instead of the (to me) obvious choice of 6.40GB was a missed humor opportunity. Just sayin'.]

Hello, sorry to bother! I increased the memory allocated to the vm several times yesterday with hopes that the Memory allocation error would go away. Unfortunately, no amount was enough. The same notebook runs without any trouble on my laptop (16gb, macOS). Not really sure what the problem could be here. Is there information I can provide that might provide more clarity?

**Comment by therealkenc** [comment]
A set of CLI repro steps, and a link to the [gist](https://gist.github.com/) of a threaded [strace(1)](https://man7.org/linux/man-pages/man1/strace.1.html) log might elucidate something.

**Comment by dleviminzi** [comment]
The error occurs within a Jupyter notebook so I'm not sure what kind of cli steps I can provide. I am using the [LabelSpreading ](https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/semi_supervised/_label_propagation.py#L410) module from sklearn on a ~50k square matrix. Here is a gist:

https://gist.github.com/dleviminzi/6855974110bc7a94ff3fa44f6f9bb162

**Comment by therealkenc** [comment]
The trace would have to be of something outputting `MemoryError: Unable to allocate`, and _commandline steps_ to evoke the fail. Those probably aren't going to be trivial for you to produce. Make sure `free` is showing plenty of memory available. The error is from userspace so there isn't going to be a WSL actionable. You will probably get better eyeballs where `LabelSpreading` people hang out.

**Comment by dleviminzi** [comment]
> The trace would have to be of something outputting `MemoryError: Unable to allocate`, and _commandline steps_ to evoke the fail. Those probably aren't going to be trivial for you to produce. Make sure `free` is showing plenty of memory available. The error is from userspace so there isn't going to be a WSL actionable. You will probably get better eyeballs where `LabelSpreading` people hang out.

Ok. I will close the issue. Thank you for the help!

**Comment by therealkenc** [comment]
Thanks back. In principle I think you can run `scikit-learn` in a minimal standalone commandline python app, and watch it fail. But Occum's Razor strongly suggests making the effort wouldn't tell more than the error message did at face value.
