### ISSUE TITLE
When pinging after activating a Wireguard VPN, WSL gets just one response, then nothing more. 

### ISSUE THREAD

**Issue by rdbisme** [microsoft/WSL#5810]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```

Distro: 
```
$> cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux]
```
WSL Version: **2** (`Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 202`)

# Steps to reproduce

**WSL logs**: 

1. Install [Wireguard Official Client](https://www.wireguard.com/install/)
2. Import a Tunnel configuarion file of the type
```
[Interface]
PrivateKey = </snip>
ListenPort = 51820
Address = 10.0.0.250/24

[Peer]
PublicKey = </snip>
AllowedIPs = 10.0.0.1/32, 192.168.1.0/24
Endpoint = </snip>:51820
PersistentKeepalive = 30

```
3. Activate the tunnel 
4. Ping `10.0.0.1` from within the WSL
```
$> ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=63 time=60.4 ms
```

#  Expected behavior
The WSL should be able to ping the VPN host at the IP 10.0.0.1

# Actual behavior
The ping receives just one single response, then nothing. 

## There's a workaround to make it work: 

Repeat step 1-3 of the procedure reported above.

4a. Ping `10.0.0.1` **from the host**
```
Pinging 10.0.0.1 with 32 bytes of data:
Reply from 10.0.0.1: bytes=32 time=58ms TTL=64
Reply from 10.0.0.1: bytes=32 time=60ms TTL=64
Reply from 10.0.0.1: bytes=32 time=58ms TTL=64
Reply from 10.0.0.1: bytes=32 time=59ms TTL=64
```

4b. Ping `10.0.0.1` from within the WSL
```
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=63 time=57.3 ms
64 bytes from 10.0.0.1: icmp_seq=2 ttl=63 time=59.9 ms
64 bytes from 10.0.0.1: icmp_seq=3 ttl=63 time=58.9 ms
64 bytes from 10.0.0.1: icmp_seq=4 ttl=63 time=59.7 ms
64 bytes from 10.0.0.1: icmp_seq=5 ttl=63 time=58.2 ms
64 bytes from 10.0.0.1: icmp_seq=6 ttl=63 time=60.6 ms
64 bytes from 10.0.0.1: icmp_seq=7 ttl=63 time=58.9 ms
64 bytes from 10.0.0.1: icmp_seq=8 ttl=63 time=60.3 ms
64 bytes from 10.0.0.1: icmp_seq=9 ttl=63 time=58.5 ms
```

**Comment by rubendibattista** [comment]
#5764 looks related

**Comment by therealkenc** [comment]
> 4a. Ping 10.0.0.1 from the host

There are steps missing here. If you install WireGuard on WSL, you won't be able to ping `10.0.0.1` with `ping.exe` on Windows. You'd get host unreachable. At least without adding a route on Windows. I suspect (but can't prove) that's the rub.
