### ISSUE TITLE
Need for Unique wsl2 host-names

### ISSUE THREAD

**Issue by stevebovy** [microsoft/WSL#5812]
WSL2  Wish-List Feature Fix ??  

PROBLEM DESCRIPTION: "DOUBLE TROUBLE"

NON UNIQUE WSL2 HOST NAME CREATES UNNECESSARY  "NAME RESOLUTION"  CONFUSION  WHICH CAN CURRENTLY ONLY BE WORKED AROUND BY USING "FULLY-QUALIFIED" WINDOWS-HOST-NAME

Example of problem   (Accessing  Windows Host X-Serv) 

The following will not work:   DISPLAY=HOSTNAME:0

THE WORK AROUND IS  DISPLAY=HOSTNAME.WINHOST-DOMAIN:0

Additional  wsl.conf   Network   Keywords  ??

Allow custom configuration of  HOSTNAME  file   so  that  WSL2 VM  machine network name is unique and different from windows host machine name ; this would of course impact the HOST file as well

NOTE; (  I would prefer the default to be the linux distribution name )

**Comment by Biswa96** [comment]
I am not sure if this feature is documented or available in stable Windows OS versions. For my case, I have tried this in latest Windows Insider build and it works. Create a `/etc/wsl.conf` file in your preffered WSL-ed GNU/Linux distribution. Add the following two lines in that `/etc/wsl.conf` file.

```ini`
[network]
hostname = HelloWorld
```

Change the host name as you want.

**Comment by Biswa96** [comment]
I am not sure if this feature is documented or available in stable Windows OS versions. For my case, I have tried this in latest Windows Insider build and it works. Create a `/etc/wsl.conf` file in your preffered WSL-ed GNU/Linux distribution. Add the following two lines in that `/etc/wsl.conf` file.

```ini
[network]
hostname = HelloWorld
```

Change the host name as you want.
