### ISSUE TITLE
Windows mounted network shares produce: Input/output error

### ISSUE THREAD

**Issue by rkitover** [microsoft/WSL#5817]
# Environment

```none
Windows build number: 10.0.20197.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Mount a network share to a filesystem location, for example mine is mounted to `C:\Users\rkitover\nas` for the network path `\nas\rkitover`.

In powershell `gi` this looks like:

```none
✔ C:\Users\rkitover
rkitover@epycwin > gi nas

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----           5/31/2020  9:18 PM                nas -> UNC\nas\rkitover
```

WSL 2 gives an `Input/output error` when accessing this folder in any way:

```none
rkitover@epycwin:/mnt/c/Users/rkitover$ ls -ld nas
ls: cannot read symbolic link 'nas': Input/output error
lrwxrwxrwx 1 rkitover rkitover 0 May 31 21:18 nas
rkitover@epycwin:/mnt/c/Users/rkitover$ cd nas
-bash: cd: nas: Input/output error
```

#  Expected behavior

It would be nice if this worked, of course I understand that may be very hard.

Since I want to use my Windows profile directory as my WSL home directory, I will use this `ls` function I made previously for the time being:

https://github.com/microsoft/WSL/issues/2779#issuecomment-490046753

**Comment by therealkenc** [comment]
Nice find, thank you. I don't think there is a dupe that is directly on-point. Was able to repro

![image](https://user-images.githubusercontent.com/7049700/91292754-d1676880-e74b-11ea-9b60-8bc5b9d61740.png)

> Since I want to use my Windows profile directory as my WSL home directory

"There's yer problem"
