### ISSUE TITLE
wsl writes messages to standard output

### ISSUE THREAD

**Issue by yecril71pl** [microsoft/WSL#5818]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: N/A
```

# Steps to reproduce

```CMD
WSL 2>WSL.LOG.TXT
START WSL.LOG.TXT
```

**WSL logs**: 
https://aka.ms/AA9fxyn

#  Expected behaviour

Windows Subsystem for Linux has no installed distributions.

Distributions can be installed by visiting the [Microsoft Store](https://aka.ms/wslstore).

# Actual behaviour

**Comment by therealkenc** [comment]
Closing not actionable.

![image](https://user-images.githubusercontent.com/7049700/91883097-c96e6380-ec38-11ea-80e1-9aa696fbc194.png)
