### ISSUE TITLE
WSL 2 is incompatible with the Angular CLI

### ISSUE THREAD

**Issue by mfish0005** [microsoft/WSL#5819]
# Environment

```none
Windows build number:  Win32NT  Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 18.04
WSL 2
```

## Description
I recently upgraded WSL from v1 to v2. I noticed some major breaking changes with the Angular CLI that only occur from my WSL 2 shell.  They don't occur from  WSL 1 or Powershell/Command Prompt.

1. Angular projects running from WSL 2 do not recompile when changes are made and the browser doesn't reload.  Even manually reloading the browser won't show your changes.
2. Serving Angular projects with `ng serve` or `npm start` takes minutes to load a project even if it's completely empty.  Running a medium to large project is practically impossible.  Worth noting that I have a higher end machine.

## Steps to reproduce

1. Make sure you have Nodejs installed.
2. Enter your WSL 2 shell
3. Install the Angular CLI `npm install -g @angular/cli`
4. Create a new Angular project: `ng new example-app`
5. Enter the project directory: `cd example-app`
6. Run `ng serve` or `npm start` to serve the application.  This might take a very long time on WSL 2
7. Go to http://localhost:4200
8. Change a file and save it.  
9. Notice the project doesn't recompile in your WSL 2 shell and the browser doesn't reload.  
10. Manually reload the browser and the changes still won't be there

#  Expected behavior

Running an Angular app from a WSL 2 shell should take a reasonable amount of time.   Once it's running and you save a file it should be possible to view your changes from a browser.  The browser should reload automatically when changes are made.

# Actual behavior

Running an Angular app from a WSL 2 shell takes an extremely long time(10+ minutes for larger projects).  Once it finishes compiling making changes to a file and saving it doesn't recompile the app or reload the browser.  Your changes aren't visible even if you manually reload the browser.

**Comment by therealkenc** [comment]
> Notice the project doesn't recompile in your WSL 2 shell and the browser doesn't reload.

/dupe #4739

**Comment by mfish0005** [comment]
For anyone that finds this issue here is a TL;DR:  This isn't how WSL 2 is designed to work. For better or worse, you're basically expected to put all your project's files inside of Linux itself now (E.G. in your /home aka ~/ directory). This is the only way to get usable performance, live reloading, and many other features that WSL 1 offered with the /mnt directory.

As of now your choices are basically just use VSCode and it's WSL extension for full stack development OR continue using WSL 1. I'm giving the former a try but if you want to use a different IDE just stick with WSL 1 instead.

**Comment by DragosN** [comment]
I'm a bit late to the party, but I've passed --poll=10000 flag to workaround this issue. 
`ng serve --poll=10000`

**Comment by doncadavona** [comment]
It's 2022 and Angular hot reload is working in WSL.

**Comment by JimmyBjorklund** [comment]
This issue is back, i have never had it before but now it's totally dead after recompiling. stop & start fixes the issue buts its annoying.
