### ISSUE TITLE
"The I/O operation has been aborted" will still happen in os version 20180

### ISSUE THREAD

**Issue by windowsair** [microsoft/WSL#5825]
# Environment

```none
Windows build number:10.0.20180.1000 
Your Distribution version: Ubuntu (can't run because failed to run the bash)
Whether the issue is on WSL 2 and/or WSL 1: WSL1
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

As the issue #5633  said, the problem will still occur in version 20180.

**Comment by onomatopellan** [comment]
You will need to upgrade to build 20190 to get the fix.

**Comment by windowsair** [comment]
> You will need to upgrade to build 20190 to get the fix.

Oh....I am barking at the wrong tree...:sweat_smile:Everything is ok under Build 20190
