### ISSUE TITLE
Android USB tethering + `sudo apt-get update` crashes the computer's network

### ISSUE THREAD

**Issue by Banou26** [microsoft/WSL#5827]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

Use the android tethering & portable hotspot via USB tethering.
run `sudo apt-get update` in the WSL2

#  Expected behavior

the WSL2 should run the `sudo apt-get update` command without any problems

# Actual behavior

When running `sudo apt-get update`, the command manage to execute for 1 second, and after that, the entire computer network crashes(WSL2's network + Windows's network are affected by the crash)

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by Vinche59** [comment]
Same problem ...
WSL Logs: https://aka.ms/AAae48d

**Comment by balciseri** [comment]
Same problem

**Comment by Banou26** [comment]
Problem look like it got fixed for me.

```
Microsoft Windows [Version 10.0.19041.867]
Release:        20.04
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

**Comment by morganarnel** [comment]
This issue is occurring once again, have submitted feedback using the steps suggested above.

**Comment by tsch0hnny** [comment]
This issue is occurring again on Windows 10 and Windows 11 in both the Ubuntu WSL and the Debian WSL while being tethered via USB.

I managed to temporarily fix the issue by switching to WiFi and running `sudo apt-get update` again
