### ISSUE TITLE
HKPS keyservers (gnupg) do not appear to work due to networking issue 

### ISSUE THREAD

**Issue by plttn** [microsoft/WSL#5829]
# Environment

```none
Windows build number: 19041
Your Distribution version: Pengwin Bullseye (also occurs on Ubuntu 20.04)
Whether the issue is on WSL 2 and/or WSL 1: WSL2 (Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020) (issue also occurs in WSL1)
```

# Steps to reproduce

Have at least one public key in GPG (v2.2.19) that would be available on sks keyserver pool for refreshing.
```
$ gpg --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net
```

Issue can also be replicated as a one-liner via:
```
$gpg --search-keys --keyserver hkps://hkps.pool.sks-keyservers.net Jack Platten
```

https://gist.github.com/plttn/112c43b48919d2c698a455ae0aaef9f8

**WSL logs**: https://aka.ms/AA9id37

#  Expected behavior

Expecting `gpg --refresh-keys` to result in a outcome of:
```
$ gpg --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net
gpg: refreshing 3 keys from hkps://hkps.pool.sks-keyservers.net
gpg: key 0xDEADBEEF: "John Doe" not changed
gpg: key 0xF00B1234: "Jane Doe" not changed
gpg: key 0xF00B4321: "John Smith" not changed
```

Expecting `gpg --search-keys Jack Platten` to result in an outcome of:
```
$ gpg --search-keys platten
gpg: data source: hkps://hkps.pool.sks-keyservers.net:443
(1)     Jack Platten <jack.k.platten@gmail.com>
          256 bit EDDSA key 0xEB771A347AD2D177, created: 2019-10-18, expires: 2022-04-21
(2)     Jack Platten <jack@plttn.me>
        Jack Platten <jack.k.platten@gmail.com>
        @plttn (Keybase Account) <plttn@keybase.io>
          2048 bit RSA key 0x7F2274DB202D35AC, created: 2018-07-06, expires: 2021-04-22
(3)     Marc Platten <marc@mplatten.de>
          4096 bit RSA key 0x7F58F2E8E8FF0751, created: 2018-02-16, expires: 2020-02-18 (expired)
(4)     Marc Platten <marc.platten@ekir.de>
          4096 bit RSA key 0x2CF9614F9E75C953, created: 2018-02-16, expires: 2020-02-18 (expired)
(5)     Jack Platten <japlatten@csumb.edu>
          4096 bit RSA key 0x28B2B4F6A60E247C, created: 2017-09-29, expires: 2022-09-28
(6)     Paul E. Platten <Pplatten8@gmail.com>
          4096 bit RSA key 0x4DBB1E1236F80247, created: 2017-03-25, expires: 2021-03-25
(7)     Pau E Platten <PPlatten8@gmail.com>
          4096 bit RSA key 0x6EF9DE94725F01E9, created: 2017-03-20, expires: 2021-03-20 (revoked)
(8)     Jack Platten <jack@plttn.me>
        Jack Platten <plttn@keybase.io>
        Jack Platten <jack.k.platten@gmail.com>
        Jack Platten (Keybase Account) <plttn@keybase.io>
          2048 bit RSA key 0xD3446965B4615930, created: 2016-06-07
Keys 1-8 of 30 for "platten".  Enter number(s), N)ext, or Q)uit >
```

# Actual behavior

```
$ gpg --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: General error
```

```
$ gpg --search-keys --keyserver hkps://hkps.pool.sks-keyservers.net Jack Platten
gpg: error searching keyserver: General error
gpg: keyserver search failed: General error
```

Wireshark doesn't show anything out of the ordinary. When running `gpg --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net` on WSL, there are occasional unknown record packets seen in `tls` filter, but those broken packets also appear when capturing a `--refresh-keys` run on Windows host. This issue occurs on both of my machines. I initially believed it to be a DNS issue, but it doesn't seem to be caused by that. Using `-vvvvv` to get it as verbose as possible, gpg sees absolutely no data, not even a malformed openPGP packet, it just immediately jumps to a fail state.

**Comment by Biswa96** [comment]
I am not sure if this is WSL issue or not. Try this `hkp://keys.gnupg.net:80` as keyserver.

**Comment by plttn** [comment]
Forgot to add, hkp does work successfully.

**Comment by therealkenc** [comment]
Cannot reproduce here on Ubuntu.

![image](https://user-images.githubusercontent.com/7049700/91664775-2e458480-eaa6-11ea-9a17-a665dcfee7bb.png)

**Comment by plttn** [comment]
Just to confirm, do you have any keys in that keyring? I don't believe --refresh-keys actually performs any actions unless there's something in the keyring.

**Comment by therealkenc** [comment]
No what I did was execute your reproduction steps. Which was one line.

**Comment by plttn** [comment]
Amended repro steps to clarify that there should be at least one key in the keyring.

**Comment by therealkenc** [comment]
"Have at least one public key in GPG (v2.2.19) that would be available on sks keyserver pool for refreshing" is not a repro step. The one liner offered exhibits the same behavior on Ubuntu running on bare metal.

![image](https://user-images.githubusercontent.com/7049700/91882659-287fa880-ec38-11ea-8fea-d847303a2ee8.png)

**Comment by david-caro** [comment]
Just for the record, as this might help someone, make sure that you have the sks servers CA properly added (https://sks-keyservers.net/verify_tls.php), you can see a more verbose log when talking directly to dirmngr with:
```
echo -e "KEYSERVER hkps://hkps.pool.sks-keyservers.net\nKS_SEARCH 2071B08A33BD3F06\n" | dirmngr
```

**Comment by EzeBirmanGlobant** [comment]
Here is the output of `echo -e "KEYSERVER hkps://hkps.pool.sks-keyservers.net\nKS_SEARCH 2071B08A33BD3F06\n" | dirmngr`

```dirmngr[2570.0]: permanently loaded certificates: 137
dirmngr[2570.0]:     runtime cached certificates: 0
dirmngr[2570.0]:            trusted certificates: 137 (136,0,0,1)
# Home: /home/eze/.gnupg
# Config: [none]
OK Dirmngr 2.2.25 at your service
OK
dirmngr[2570.0]: command 'KS_SEARCH' failed: Server indicated a failure <Unspecified source>
ERR 219 Server indicated a failure <Unspecified source>
```

I found this issue while trying to install https://github.com/asdf-vm/asdf-nodejs under WSL with `asdf install nodejs latest`
```
❯ cat /etc/os-release
NAME=Fedora
VERSION="33 (Container Image)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container

❯ uname -a
Linux XXXXX 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
