### ISSUE TITLE
When using git on wsl, An error occurs in which files are registered for uncommitted changes.

### ISSUE THREAD

**Issue by ywroh** [microsoft/WSL#5830]
# Environment
Microsoft Windows [Version 10.0.19041.450]
Release:        20.04
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019

# Steps to reproduce
I am working on a project using git in wsl, but if I cp a file from a Windows directory such as /mnt/c to the wsl directory, an error occurs in which the file is registered for uncommitted changes. 
An example command is shown below.

cd /mnt/c/users/{myid}/desktop/{myfilename}
cp {myfilename} ~/{mygitproject}

However, if you copy the compressed file from the Windows directory to the wsl directory and uncompress it, it is applied normally without being registered as uncommitted changes.

#  Expected behavior
I want both compressed files and general files to be properly applied to wsl.

# Actual behavior
If you try to commit the uncommitted changes, the following error occurs.

fatal: Unable to write new index file

Please review.

**Comment by therealkenc** [comment]
These are not repro steps.

**Comment by ywroh** [comment]
Yes thank you.
