### ISSUE TITLE
Strange port forwarding behavior

### ISSUE THREAD

**Issue by karuboniru** [microsoft/WSL#5834]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Your Distribution version: On a self-built WSL image, based on Fedora Rawhide
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce
 1. In Linux side, `echo linux side > test` in a certain folder
 2. In Windows side, `echo "Windows Side" > test` in another folder
 3. run `python -m http.server` or `python -m http.server --bind 127.0.0.1` in Linux Side
 4. run `python -m http.server` or `python -m http.server --bind 127.0.0.1` in Windows side (you need python on Windows)
 5. open another window in Windows Side, run `curl 127.0.0.1:8000/test` the output indicates the request went to which side
 6. kill those python webservers and restart them in different order, different command (overall 2x2x2=8 tries) and redo 5

#  Expected behavior

Emmmm. I don't mean the current behavior is wrong, but programs listening on Linux side can override Windows side in some cases, which used to confuse me a lot.

I noticed this because I run proxies on both WSL and Windows, listening on same port number, I sometimes find my chrome on Windows connects to proxy in WSL side. I have to kill the proxy instance or change port to fix this.

# Actual behavior

The behavior is strange
 - When you run `python -m http.server --bind 127.0.0.1` first, Linux side `python -m http.server` or `python -m http.server --bind 127.0.0.1` second, you will connect to Windows side
 - All other case, you get to Linux side

**Comment by therealkenc** [comment]
The behavior is strange because you've bound the same port to the same address.

/dupe #4619
