### ISSUE TITLE
Not really WSL's fault, but I'm not seeing the 1049 build of Windows 10 showing up - it's been 10 days

### ISSUE THREAD

**Issue by AltitudeApps** [microsoft/WSL#5837]
I'm not seeing the 1049 build of Windows 10 showing up - it's been 10 days since the blog post announcing the back port went up. 

I have done some searching and haven't seen this mentioned anywhere.  Do I have to join the release preview ring, (or whatever it is called these days) in order to get build .1049, and thus the ability to enjoy WSL 2 ?    I know .1049 will show up eventually, but I was surprised not to find any details on what the timing might be.   (Maybe my machine is just a little "stuck".)   (also: not really meant to be tagged 'feature', but I didn't want to spam this request for info alongside actual bug reports)

**Comment by licanhua** [comment]
Have you manually clicked "Check for Windows Updates" on Windows Update setting page? Otherwise it will take a long time to ship it into your machine.

**Comment by AltitudeApps** [comment]
Yes, quite persistently.   I should have mentioned that.   I tried several times.

**Comment by therealkenc** [comment]
Ref #5790

**Comment by AltitudeApps** [comment]
Got it, thank you very much!

I need either [KB4566116](https://support.microsoft.com/en-us/help/4566116/windows-10-update-kb4566116), or to wait for the September update to come through.

Perhaps the blog post [WSL 2 Support is coming to ... 1903 and 1909](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/) should be updated to reflect this.

from https://github.com/microsoft/WSL/issues/5790#issuecomment-678625150 :
> After some reading, my understanding is this: While the backport has been [announced](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/), the required update [KB4566116](https://support.microsoft.com/en-us/help/4566116/windows-10-update-kb4566116) was released as a preview. I assume it will become availabe as a regular update on September patch day.

Thanks again.

**Comment by c-johnson** [comment]
I'm also getting this same issue. Currently on backport 1016 (version 1903, build 18362, backport 1016).

**Comment by AltitudeApps** [comment]
@c-johnson You need either [KB4566116](https://support.microsoft.com/en-us/help/4566116/windows-10-update-kb4566116), or just wait for the September update to come through.

I'm simply waiting for the September update to arrive.
