### ISSUE TITLE
Running Win 10 Build 18363: WSL2 and NFS client mount attempt yields mount.nfs: No such device

### ISSUE THREAD

**Issue by cjbryant-github** [microsoft/WSL#5838]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

**Comment by cjbryant-github** [comment]
Hello,
   I am having trouble mounting to ANY Linux NFS server (elsewhere on my network) on WSL2 (Ubuntu 20.04) getting mount.nfs: No Such device.  I have reas this could be a problem with the installed NFS Kernel modules.  I have issued all the apt-get commands for mount, nfs client packages, nfs library and lock packages, etc.

If these NFS kernel modules are out of whack, how can this be repaired?  This is fresh Ubuntu install and fresh NFS install and I have rebooted the WIn 10 machine.

I am running Win 10 Build 18363.

Thank you for any assitance!

**Comment by therealkenc** [comment]
> I am running Win 10 Build 18363.
> I have reas this could be a problem with the installed NFS Kernel modules. 

There are no kernel modules (and no Linux kernel) in WSL1. Academically same #2869. NFS is [available](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/) in WSL2 as of 20H1 aka version 2004 aka build 19041.

**Comment by cjbryant-github** [comment]
Hello,
    Thank you for your reply!  I mistakenly thought downloading the latest Ubuntu 20.04 from the Win 10 App Store was WSL2. My machine does indicate Win 10 Build 1909.  I do have access to some 2004 Win 10 machines so I will re-try there.  Thank you very much!

~Charlie

**Comment by Ashark** [comment]
So, still no way to mount nfs with utf-8 file names when windows is itself in virtual machine.
wsl1 have not got kernel modules, and wsl2 requires the physical virtualization available.

**Comment by dragonly** [comment]
> > I am running Win 10 Build 18363.
> > I have reas this could be a problem with the installed NFS Kernel modules.
> 
> There are no kernel modules (and no Linux kernel) in WSL1. Academically same #2869. NFS is [available](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/) in WSL2 as of 20H1 aka version 2004 aka build 19041.

Thanks! Tested on Version 2004 Build 19041.610 and it works!
