### ISSUE TITLE
Deinstallation of nvidia-driver after each Windows update

### ISSUE THREAD

**Issue by Godofnothing** [microsoft/WSL#5848]
I have subscribed for the Windows Insider Developer Program. 
The current build of Windows is `20201.1000`.  
In order to use CUDA on WSL `455.41` version of driver is required with CUDA 11.1.

However after updating the operating system, this driver is mortaged , and the nvidia-smi shows 

` NVIDIA-SMI 451.67       Driver Version: 451.67       CUDA Version: 11.0`

And after that, the WSL doesn't see the GPU on the laptop. 
What should I do in order to prevent deinstallation of the latest driver?
Thanks in advance for the help!

**Comment by therealkenc** [comment]
Sounds like the drivers from your Linux distribution got installed.

**Comment by benhillis** [comment]
Should be fixed with [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211).
