### ISSUE TITLE
Help to commandline options have an error in them

### ISSUE THREAD

**Issue by Jikkelsen** [microsoft/WSL#5850]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1016]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce

1. Running "wsl -" in CMD, will result in the below output.

        Invalid command line option: -
        Copyright (c) Microsoft Corporation. All rights reserved.
    
        Usage: wsl.exe [Argument] [Options...] [CommandLine]
    
        Arguments to run Linux binaries:
    
        If no command line is provided, wsl.exe launches the default shell.
    
        --exec, -e <CommandLine>
            Execute the specified command without using the default Linux shell.
    
        --
            Pass the remaining command line as is.
    
        Options:
        --distribution, -d <DistributionName>
            Run the specified distribution.
    
        --user, -u <UserName>
            Run as the specified user.
    
        Arguments to manage Windows Subsystem for Linux:
    
        --export <DistributionName> <FileName>
            Exports the distribution to a tar file.
            The filename can be - for standard output.
    
        --import <DistributionName> <InstallLocation> <FileName>
            Imports the specified tar file as a new distribution.
            The filename can be - for standard input.
    
        --list, -l [Options]
            Lists distributions.
    
            Options:
                --all
                    List all distributions, including distributions that are currently
                    being installed or uninstalled.
    
                --running
                    List only distributions that are currently running.
    
        -setdefault, -s <DistributionName>
            Sets the distribution as the default.
    
        --terminate, -t <DistributionName>
            Terminates the distribution.
    
        --unregister <DistributionName>
            Unregisters the distribution.
    
        --upgrade <DistributionName>
            Upgrades the distribution to the WslFs file system format.
    
        --help
            Display usage information.
    

**WSL logs**: 

#  Expected behavior

**The option `-setdefault, -s <DistributionName>` has only a single dash, where its expected to have double dashes.**

# Actual behavior

It has only single dashes as in output

**Comment by therealkenc** [comment]
> [Version 10.0.18363.1016]

Fixed sometime since 18363.

**Comment by Jikkelsen** [comment]
Cheers, thanks :)
