### ISSUE TITLE
Can't connect to gRPC server running in WSL2 from Windows

### ISSUE THREAD

**Issue by benanderton** [microsoft/WSL#5853]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1049]
Your Distribution version: Ubuntu 20.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Firstly I'm not running a VPN, and have disabled Windows Firewall.

I'm developing some software comprising several gRPC services and some larger HTTP services (both written in Node.js). I can run HTTP services from within WSL2 and connect to them from Windows no problem. However, when trying to connect to a gRPC service from Windows I get a error stating that the gRPC client can't connect. The same client running from within WSL2 connects fine. 

To diagnose I've used Telnet from Windows, and from within WSL2. Please see below

**From within WSL2:**

```
 ~ telnet 127.0.0.1 8081                                                                                                                                                   Thu Sep  3 07:57:00 2020
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

**From Windows:**
```
C:\Users\Ben Anderton\Desktop\protobuffers>telnet 127.0.0.1 8081
Connecting To 127.0.0.1...Could not open connection to the host, on port 8081: Connect failed
```

**gRPC Client from Windows**
Just for good measure here's the error received by the gRPC client on Windows

```
C:\Users\Ben Anderton\Desktop\protobuffers>grpcc -i -p sage_accounts.proto -a 127.0.0.1:8081

Connecting to unknown.SageAccountsRequest on 127.0.0.1:8081. Available globals:

  client - the client connection to SageAccountsRequest
    createUpdateSupplier (SageAccountRequest, callback) returns Empty
    createUpdateCustomer (SageAccountRequest, callback) returns Empty
    createPurchaseInvoice (SageAccountRequest, callback) returns Empty
    createSalesInvoice (SageAccountRequest, callback) returns Empty
    createSalesReceipt (SageAccountRequest, callback) returns Empty

  printReply - function to easily print a unary call reply (alias: pr)
  streamReply - function to easily print stream call replies (alias: sr)
  createMetadata - convert JS objects into grpc metadata instances (alias: cm)
  printMetadata - function to easily print a unary call's metadata (alias: pm)

SageAccountsRequest@127.0.0.1:8081> (node:13740) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
SageAccountsRequest@127.0.0.1:8081> client.createUpdateCustomer({}, pr)
ClientUnaryCall {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  call: InterceptingCall {
    next_call: InterceptingCall { next_call: null, requester: [Object] },
    requester: undefined
  },
  [Symbol(kCapture)]: false
}
SageAccountsRequest@127.0.0.1:8081>
Error:  Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (C:\Users\Ben Anderton\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Users\Ben Anderton\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (C:\Users\Ben Anderton\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\Ben Anderton\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Users\Ben Anderton\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:847:24)
    at callbackTrampoline (internal/async_hooks.js:120:14) {
  code: 14,
  metadata: {},
  details: 'failed to connect to all addresses'
}

(To exit, press ^C again or ^D or type .exit)
```

**WSL logs**: 

#  Expected behavior

I should be able to connect to a gRPC service running in WSL2 from Windows

# Actual behavior

A gRPC client, and plain Telnet refuse to connect to a gRPC service from Windows. Connecting to HTTP works however, which leads me to believe there may be an issue with HTTP/2 and WSL2 (given that gRPC sit on top of HTTP/2).

**Comment by therealkenc** [comment]
/dupe #4851 on presumptive repro, for lack

![image](https://user-images.githubusercontent.com/7049700/92143564-4da42080-edca-11ea-9237-6bfe028928d0.png)

**Comment by NickLc** [comment]
I had this problem, when I tried to test the service that I developed in grpc with nodejs and molecular, Probe many things apparently there is a conflict with WSL.

**Solution**

Run grpc server directly on windows,

- install the dependencies you needed like node, npm, yarn, node-gyp, node-pre-gyp all of these globally with npm.
- I rebuilt my dependencies of nodemodules since these dependencies were for unix.
- change the execution part in the package.json from execute to set.

With all this I was finally able to perform my tests of the services.
I hope it helps you, it is the fastest solution you can find. 
**Result**
![imagen](https://user-images.githubusercontent.com/37456591/127708256-7c6a4d56-7359-4b05-87bf-6aa48f9dd019.png)
