### ISSUE TITLE
Some Fonts Missing from WSL Ubuntu Distro

### ISSUE THREAD

**Issue by DanielGoldfarb** [microsoft/WSL#5858]
# Environment

```Windows10 Version 1903 (OS Build 18362.1016)
PRETTY_NAME="Ubuntu 18.04.5 LTS"
dino@DINO:~$ cat /proc/version
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020
```

# Steps to reproduce
- Assuming WSL already enabled:
1. Go to microsoft store.  Install Ubuntu
2. After install is complete: `ls -l /usr/share/fonts/truetype/` 
3. See only `dejavu`

```
dino@DINO:~$ ls -l /usr/share/fonts/truetype/
total 0
drwxr-xr-x 1 root root 512 Aug 21 13:52 dejavu
```

**WSL logs**: 
- I will gladly do this if you tell me that it is necessary.  Imho it may not be necessary, since this **may be just a question of whether or not the list of fonts that come with the WSL Ubuntu distros has changed.**

#  Expected behavior

- After ` ls -l /usr/share/fonts/truetype/` ... **expect to see the full list of fonts that typically come with Ubuntu:**

```
abyssinica
dejavu
droid
fonts-beng-extra
fonts-deva-extra
fonts-gujr-extra
fonts-guru-extra
fonts-kalapi
fonts-orya-extra
fonts-telu-extra
fonts-yrsa-rasa
freefont
Gargi
Gubbi
hack
kacst
kacst-one
lao
liberation
liberation2
lohit-assamese
lohit-bengali
lohit-devanagari
lohit-gujarati
lohit-kannada
lohit-malayalam
lohit-oriya
lohit-punjabi
lohit-tamil
lohit-tamil-classical
lohit-telugu
malayalam
Nakula
Navilu
noto
openoffice
padauk
pagul
Sahadeva
samyak
samyak-fonts
Sarai
sinhala
tibetan-machine
tlwg
ttf-khmeros-core
ubuntu
```

# Actual behavior
- See only `dejavu`

```
dino@DINO:~$ ls -l /usr/share/fonts/truetype/
total 0
drwxr-xr-x 1 root root 512 Aug 21 13:52 dejavu
```

**Comment by therealkenc** [comment]
`sudo apt install fonts-beng-extra` et cetera. Or `sudo apt install ubuntu-desktop` if you want a big hammer.

What packages ship with a disto is up to the distribution maintainers. They wouldn't _typically_ ship a large font package in a headless [scenario](https://ubuntu.com/download/server).

**Comment by DanielGoldfarb** [comment]
@therealkenc 
Thanks for you help.  

Can find out from the distribution maintainers whether WSL Ubuntu18 distribution previously contained more fonts?  

Originally, I installed WSL Ubuntu(18) approximately a year ago.  I am 99.44% certain that I never installed any fonts myself.  
I have been developing a python package that relies on various fonts and it has been working fine.

Three weeks ago (for other reasons) I did a clean install of Windows10, followed by an install of WSL Ubuntu, and that's when _the regression tests for my package began failing specifically on the appearance of some fonts_.  (Yet the same regression tests continue to work fine on the other distros of Ubuntu that I use, and on a Red Hat linux distro).

Today I finally tracked the issue down to the fact that some of the fonts are missing from WSL Ubuntu; this after multiple deletions and re-installs of various versions of WSL Ubuntu (16,18,20) over the past few days.  

I would really like to know, for my own peace of mind,  whether or not the WSL Ubuntu distribution a year ago included these fonts, but now it does not.   

Thank you for your help.  Much appreciated.  
 --Daniel

**Comment by therealkenc** [comment]
> Can we find out from the distribution maintainers whether WSL Ubuntu18 distribution previously contained more fonts?

You could [ask](https://askubuntu.com/) the distribution maintainers whether WSL Ubuntu-18.04 previously contained moar fonts. Hypothetically.

**Comment by WSLUser** [comment]
In case it matters:  in the kernel config font options, not all font size options are selected though the `autoselect `option is enabled. As I'm not a font or kernel expert, I apologize if this has no relevance. Just wanted to ensure this isn't a factor (perhaps a distro provides fonts based on the config options).

**Comment by DanielGoldfarb** [comment]
@WSLUser ... Thanks.  I appreciate _any_ input, really.  

- **Ideally I would like to see a manifest of the distro.  And have access to the manifests historically**.  
That would help for any and all questions related to how a distro has changed over time (not just font issues).  
Not quite sure how to get that.

@therealkenc ... Thanks.  I _will_ ask. (Although I, sort of, [already did](https://askubuntu.com/questions/1272461/what-fonts-come-with-ubuntu) before posting here).  

I posted here because I was thinking that `github.com/microsoft/WSL/issues` _would be_ a likely place to find those who are actually involved in maintaining the distribution, but perhaps not.

**Comment by WSLUser** [comment]
Your best bet is @sirredbeard
