### ISSUE TITLE
rbenv/ruby/bundler error on bundle install

### ISSUE THREAD

**Issue by stevensona** [Microsoft/WSL#586]
Hi. Not sure if this is the correct place to post this, but I ran into this issue and thought others may benefit from hearing what I did to fix it. 

Fresh install of Bash on Windows 14371.rs1_release.160617-1723. Install rbenv latest, ruby 2.3.1, and bundler latest. Any attempt to run `bundle` fails with the following error: "ArgumentError: parent directory is world writable but not sticky". Following advice in this [comment](https://github.com/bundler/bundler/issues/4599#issuecomment-223969313), I was able to resolve the issue by running the command `find ~/.bundle/cache -type d -exec chmod 0755 {} +`

**Comment by lateau** [comment]
I think this caused by ```umask 0000``` on fresh WSL.
This is what I'm doing:
```sh
$ tail -n1 ~/.bashrc
umask 0022
```

**Comment by Tset-Noitamotua** [comment]
I reported a [similar issue on bundler`s issue tracker](https://github.com/bundler/bundler/issues/4887)  ... maybe it`s related.

**Comment by therealkenc** [comment]
Going to call @lateau's explanation authoritative.
