### ISSUE TITLE
No external network connection in any WSL2 distro, but available in Docker Desktop WSL2 backed dev container

### ISSUE THREAD

**Issue by KristoferHansson** [microsoft/WSL#5862]
# Environment
* Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
  * Version 1909 (OS Build 18363.1049)
* Ubuntu Release:        20.04
* Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
* Hyper-V feature turned off
 
```
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  Debian                 Running         2
  docker-desktop-data    Running         2
  Ubuntu-20.04           Running         2
```

# Steps to reproduce

# Notes

* I have tried installing different distros, with same result
* I have tried with Hyper-V feature enabled, with same result
* I have tried with 1903.1049 before upgrading to 1909.1049 and had the same issue in the distro
* I have no active VPN connection, but I have Check Point Endpoint Security installed
* I have tried the resolve.conf and netsh suggestions found in other issues with no effect

## Failing scenario in distro

* Clean install of WSL2 distro
* eth0 info
```
ip addr | grep eth0
5: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.176.231/28 brd 192.168.176.239 scope global eth0
```

* Trying to ping host (WSL adapter IP from running ipconfig on host) or trying to ping 8.8.8.8 gives 100% packet loss
```
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1074ms
```
```
$ ping 192.168.176.225
PING 192.168.176.225 (192.168.176.225) 56(84) bytes of data.
^C
--- 192.168.176.225 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1008ms
```

## Successful scenario in Docker Desktop WSL2 backed dev container from VSCode

* Docker Desktop Community
  * Version: 2.3.6.0 (47622)
  * Channel: edge
  * "Use the WSL 2 based engine" checked  

* VSCode 1.48.2
  * Start remote container configured repo: vscode-remote-try-python

* eth0 info
```
vscode@a5b5a09f91a2:/workspaces/vscode-remote-try-python$ ip addr | grep eth0
5: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
```
* Ping 8.8.8.8 successful
```
vscode@a5b5a09f91a2:/workspaces/vscode-remote-try-python$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=37 time=15.3 ms
```
* Ping Windows host WSL adapter interface IP successful
```
vscode@a5b5a09f91a2:/workspaces/vscode-remote-try-python$ ping 192.168.176.225
PING 192.168.176.225 (192.168.176.225) 56(84) bytes of data.
64 bytes from 192.168.176.225: icmp_seq=1 ttl=37 time=2.45 ms
```
* Ping host.docker.internal successful
```
vscode@a5b5a09f91a2:/workspaces/vscode-remote-try-python$ ping host.docker.internal
PING host.docker.internal (192.168.65.2) 56(84) bytes of data.
64 bytes from 192.168.65.2 (192.168.65.2): icmp_seq=1 ttl=37 time=2.63 ms
```

**WSL logs**: 
https://aka.ms/AA9kazx

#  Expected behavior

Successful ping response to both windows host and 8.8.8.8

# Actual behavior

100% packet loss when pinging both windows host and 8.8.8.8 from within distro

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by KristoferHansson** [comment]
@therealkenc : Added link to WSL logs sent via Feedback Hub.

**Comment by luochen1990** [comment]
I have the similar issue,  after waking up from sleep,  WSL2 occasionally lost network connection, It failed to ping 8.8.8.8 or connect to local X window server (VcXsrv),  but restarting the system can fix thing temporarily.

**Comment by KristoferHansson** [comment]
@luochen1990 : Hi, that seems like a (set) of issues already reported specifically regarding waking up from sleep. In this case it has never worked in a normal WSL2 distro, regardless of sleep or restart, also acted the same way in 1903.1049 and 1909.1049.

**Comment by KristoferHansson** [comment]
Installed a WSL1 backed distro(kali) in parallel and it has no network issues
```
wsl --list --verbose
  NAME                   STATE           VERSION
* Debian                 Running         2
  kali-linux             Running         1
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Ubuntu-20.04           Running         2
```

**Comment by Akkuma** [comment]
I have a fairly similar problem to you. I had everything working and suddenly found my distro completely screwed up, but restarting, setting nameserver, uninstalling/reinstalling, none of it seemed to matter. As soon as I used wsl --set-version <Distro> 1 and tested it worked perfectly fine. Resetting this to version 2, complete failure again.

**Comment by lasersio** [comment]
Pretty much same problem
```
$ ping google.com
PING google.com (216.58.207.206) 56(84) bytes of data.
^C
--- google.com ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2045ms

$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4140ms

$ traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.254.184  netmask 255.255.240.0  broadcast 172.18.255.255
        inet6 fe80::215:5dff:fe87:dc04  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:87:dc:04  txqueuelen 1000  (Ethernet)
        RX packets 651  bytes 163402 (163.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 152  bytes 11576 (11.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

$ ping 172.18.240.1
PING 172.18.240.1 (172.18.240.1) 56(84) bytes of data.
^C
--- 172.18.240.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2094ms

$ traceroute 172.18.240.1
traceroute to 172.18.240.1 (172.18.240.1), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  *^C
```

**Comment by lasersio** [comment]
Also some parts of host (windows) interface gets stuck.  

Periodically, I start to kill "Service Host: DNS Client" and "Service Host: Network List Services". And things start for a moment be better.

Feedback was simply hung loading until I done that. It looks like there router infinite loop and some packet flood happening behind the hood.

**Comment by laserus** [comment]
it is same as https://github.com/microsoft/WSL/issues/5821 I guess

**Comment by KristoferHansson** [comment]
I still had the issue after update to 1909 and later to 20H2. Indicating that there is some firewall rules active after all (probably part of  Check Point Endpoint Security), just by having it installed, without actually having an active VPN connection. (These times of remote work did how ever not encourage experimenting further with de-installing)

Using https://github.com/sakai135/wsl-vpnkit successfully as a work around (seeing that containers in docker desktop via WSL2 worked and that they had running vpnkit processes led me to it)

**Comment by marksteward** [comment]
I have this issue with no third-party firewall, and it's not #5821 because the WSL adapter shows up as active with an IP address. I'm not going to restart my computer every time it goes to sleep if that's the cause.
