### ISSUE TITLE
Error while enabling WindowsOptionalFeature Windows Subsystem for Linux

### ISSUE THREAD

**Issue by uttej4u4ever** [microsoft/WSL#5864]
I am facing an error while enabling the WindowsOptionalFeature Windows Subsystem for Linux by trying to run using Powershell as an administrator. Here is the error.

PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux            Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by uttej4u4ever** [comment]
> I am facing an error while enabling the WindowsOptionalFeature Windows Subsystem for Linux by trying to run using Powershell as an administrator. Here is the error.
> 
> PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux Enable-WindowsOptionalFeature : Feature name Microsoft-Windows-Subsystem-Linux is unknown.
> At line:1 char:1
> 
> * Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
>     + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
>   ```

**Comment by therealkenc** [comment]
/dupe #5123 (which didn't fill out the template either)
