### ISSUE TITLE
kernel version is different between wsl and ubuntu

### ISSUE THREAD

**Issue by tom5079** [microsoft/WSL#5868]
# Environment

```none
Windows build number: 20206.1000
Your Distribution version: Ubuntu 20.04.1 LTS
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

```
> wsl --update --status
...
Kernel version: 4.19.128

$ uname -r
4.19.104-microsoft-standard
```

#  Expected behavior

Same kernel version

# Actual behavior

Kernel version is different. why?

**Comment by 0xbadfca11** [comment]
wsl --update --status showing registry value in HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\KernelVersion. This value set by WSL2 kernel installer. Did not retrieve from actual kernel. uname -r does.
Possible causes are that the kernel was updated while WSL was running and still running, or you are using a custom kernel.
In the former case, wsl --shutdown should give you an updated kernel.

**Comment by tom5079** [comment]
Fixed by fresh-installing the windows.
