### ISSUE TITLE
How to close wsl2 and windows user sharing folder?

### ISSUE THREAD

**Issue by LittleBirdWiki** [microsoft/WSL#5870]
**Is your feature request related to a problem? Please describe.**
WSL2 default contains `/mnt/c/Users/UserName` windows sharing folder.  

**Describe the solution you'd like**
I'd like to close the link between two os system,because it's dangerous for `rm` command , it have risk to effect windows files.  
How can I do it? thanks a lot!

**Describe alternatives you've considered**

**Additional context**

**Comment by Biswa96** [comment]
By "close the link between two os system", if you mean to disable automatically mount Windows partitions, then add the following in `/etc/wsl.conf` file in that GNU/Linux distribution in WSL:

```ini
[automount]
enabled=false
```

For further information, see this blog post: [Automatically Configuring WSL][1]

[1]: https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/

**Comment by LittleBirdWiki** [comment]
> By "close the link between two os system", if you mean to disable automatically mount Windows partitions, then add the following in file in that GNU/Linux distribution in WSL:`/etc/wsl.conf`
> 
> ```ini
> [automount]
> enabled=false
> ```
> 
> For further information, see this blog post: [Automatically Configuring WSL](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/)

Thanks, it's work for me!
