### ISSUE TITLE
WSL 2 DNS Request Issue, although connection to the internet is available

### ISSUE THREAD

**Issue by NebulousNeo** [microsoft/WSL#5874]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: Release:        18.04
Linux version 4.19.104-microsoft-standard 
```

# Steps to reproduce
I'am getting the following error **Temporary failure in name resolution** when I ping a DNS like www.google.com (first recognized this failure after execute **sudo apt-get update**). If I ping the IP adress the request is successful. 

I tried to adjust the resolv.conf and wsl.conf file like described here [Fix DNS resolution in WSL2](https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6)

I have installed also OpenSuse Leap 15.1 and 15.2 same problem occurs.

Windows Features **Windows Subsystem for Linux** and **Windows Machine Platform** are enabled.

I tried to disable and reenable all Hyper-V Virtual Ethernet Adapter same problem occurs.

I first used WSL 1 and everything was fine, but I also needed docker in the WSL that's why I upgraded my Windows OS version and WSL 1 to WSL 2 after this upgrade I got this issue.

**WSL logs**: 
No logs available right now
#  Expected behavior
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=106 time=52.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=106 time=49.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=106 time=48.8 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=106 time=50.1 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=106 time=47.7 ms

# Actual behavior
ping google.com
ping: google.com: Temporary failure in name resolution

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by adescre** [comment]
I contributed a feedback for the same problem using the same feedback title.
Here is the feedback link: https://aka.ms/AA9lxsh

**Comment by NebulousNeo** [comment]
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

Thank you for you comment, here are my WSL logs : https://aka.ms/AA9l3wt

I have no additional networking software installed just the Windows Defender.
BR

**Comment by phihub** [comment]
I had the same problems. It seems to be a firewall issue. The Hyper-V network is considered a "Public Network" and the default setting is to reject all incoming traffic on public networks, so the DNS packages get rejected.

You can adjust this in the firewall settings -> Public Network -> There is a checkbox to reject all incoming traffic even if there are rules...

**Comment by NebulousNeo** [comment]
> I had the same problems. It seems to be a firewall issue. The Hyper-V network is considered a "Public Network" and the default setting is to reject all incoming traffic on public networks, so the DNS packages get rejected.
> 
> You can adjust this in the firewall settings -> Public Network -> There is a checkbox to reject all incoming traffic even if there are rules. You would have to uncheck that.
> 
> It is my desktop PC and it is just in a private network. If you are on a laptop and connect to public WiFis this setting could put you in danger.

Thank you very very very much🥇 now it is working also for me.

**Comment by enzy** [comment]
I don't want to turn off my firewall because of WSL 2 networking issue.
