### ISSUE TITLE
WSL doesn't recognize commands without it's file extension

### ISSUE THREAD

**Issue by jvzaniolo** [microsoft/WSL#5877]
# Summary

I was able to share Win Env Variables with WSL by usign WSLENV:
```js
~ echo $ANDROID_HOME // output: /mnt/c/Android/sdk
```
So I added some folders to PATH inside .zshrc
`export PATH=$PATH:$ANDROID_HOME/emulator`

# Environment

```none
Windows 10 Pro 20H2 19042.488
Ubuntu 20.04
WSL 2
```

# Steps to reproduce

Enable WSL 2 and install Ubuntu from Windows Store.
Share a Windows Environment Variable by creating a variable on windows like this:
</br>
 ```none
name: WSLENV
value: ANDROID_HOME/p
```
Add emulator's folder to .zshrc or .bashrc
`export PATH=$PATH:$ANDROID_HOME/emulator`

**WSL logs**: 
https://aka.ms/AA9kxem

#  Expected behavior
I would like to run
```js
~ emulator // expected output> emulator: ERROR: No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'
```

I can only get that response if I run `emulator` command with it's file extension:
```
~ emulator.exe
```

# Actual behavior
But instead I get:
```js
~ emulator // actual output> zsh: command not found: emulator
```

**Comment by benhillis** [comment]
This is by design.  You must specify the full executable name (including extension).  If you like you can create a .bashrc alias.
