### ISSUE TITLE
Connectivity problems with WSL2

### ISSUE THREAD

**Issue by ritmos** [microsoft/WSL#5881]
# Environment

```none
Windows build number: Version 10.0.19041.450
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
- Install and run mongo daemon in windows
- execute ubuntu2004 shell
- execute a nodejs script inside ubuntu shell that connects to local mongo server

#  Expected behavior

The nodejs script executed with ubuntu2004 shell connects to local mongo server (This works with WSL 1)

# Actual behavior

The script returns an error connect MongoNetworkError: failed to connect to server [localhost:27017]on first connect [MongoNetworkError: connect  ECONNREFUSED 127.0.0.1:27017]

**Comment by therealkenc** [comment]
> (This works with WSL 1)

/dupe #4619 for lack of repro.
