### ISSUE TITLE
sed -i makes files read-only on NTFS drives

### ISSUE THREAD

**Issue by stefanloerwald** [microsoft/WSL#5885]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

On an NTFS drive perform the following operations using WSL (Ubuntu 18.04):

1. `echo "Hello" > tmp`
2. `cat tmp`
> Hello
3. `sed 's/ello/i/' tmp`
> Hi
4. `sed -i 's/ello/i/' tmp`
> `sed: preserving permissions for ‘./sedOcla1z’: Operation not permitted`
5. `cat tmp`
> Hi
6. `sed -i 's/i/ello/' tmp`
> sed: preserving permissions for ‘./sedTx3bu6’: Operation not permitted
> sed: cannot rename ./sedTx3bu6: Permission denied
7. `cat tmp`
> Hi

So the operation works, has some trouble with its temporary file, and leaves the file in a read-only state.

This to me seems related to #4553, but this is on NTFS, not FAT32, using the main drive (C) of my Windows machine.

My expectation would be that the default drive that's mounted should not have any such issues. @therealkenc suggested [here](https://github.com/microsoft/WSL/issues/4553#issuecomment-689476365) that adding 

```
[automount]
options = "metadata"
```

to `/etc/wsl.conf` could fix it.

**Comment by therealkenc** [comment]
Thanks for rebooting into a separate issue. Cannot reproduce here:

![image](https://user-images.githubusercontent.com/7049700/92594253-5fb51180-f257-11ea-8287-293d70eac2fd.png)

**Comment by stefanloerwald** [comment]
Maybe it's an issue after the upgrade from WSL1 to WSL2 months ago? When I execute the commands you show, I get:

```
stefan@LAPTOP-4CK8UANC:/mnt/c/Users/Stefan Lörwald/DEV$ mount | grep /mnt/c
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
stefan@LAPTOP-4CK8UANC:/mnt/c/Users/Stefan Lörwald/DEV$ echo Hello > tmp
stefan@LAPTOP-4CK8UANC:/mnt/c/Users/Stefan Lörwald/DEV$ sed -i 's/ello/i/' tmp
sed: preserving permissions for ‘./sedrcR5Km’: Operation not permitted
stefan@LAPTOP-4CK8UANC:/mnt/c/Users/Stefan Lörwald/DEV$ ls -l tmp
-r-xr-xr-x 1 root root 3 Sep  9 13:52 tmp
```

**Comment by therealkenc** [comment]
> (....symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)

Don't know the cause, but those mount options are different enough. The `metadata` option didn't take (it's missing). That is _usually_ because missing `wsl.exe --shutdown` (or big hammer, a reboot). As interesting is the `trans=fd` vs. my `trans=virtio` difference.

You can try remounting it just as a sanity check:
```
$ cd /
$ sudo umount /mnt/c
$ sudo mount -t drvfs -o metadata C: /mnt/c
$ mount | grep /mnt/c
```

If you get it mounted with `metadata`, re-run the `sed` and see if it is any better.

Please also run `dmesg > dmesg.out` and post the contents in a [gist](https://gist.github.com/). It might show something.

Finally, is there anything you can think of that is running on top of your NTFS that might be unusual. Any third-party filter drivers that might intercept filesystem operations. Or anything special about the drive at all, like encryption.

**Comment by stefanloerwald** [comment]
The reboot-hammer solved it. The mount is now
```
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```

I remember that a some time ago I had set the default user of wsl to root and then back to my username. Maybe it's some effect that still lingered from back then?

**Comment by therealkenc** [comment]
I looked right through the `uid=0;gid=0` in your previous post.

The default user is stored in the registry if you set it with old-school `Ubuntu.exe config --default-user`. Newspeak is to set it with `/etc/wsl.conf`:
```
[user]
default=username
```

On best evidence, if rebooting solved, it isn't lingering anymore. Or you would still see `uid=0` in the mount options.
