### ISSUE TITLE
WSL --set-default-version not available on Windows 1909 (18363.959)

### ISSUE THREAD

**Issue by kevin2l** [microsoft/WSL#5887]
Per the article note:
If wsl --set-default-version results as an invalid command, enter wsl --help. If the --set-default-version is not listed, it means that your OS doesn't support it and you need to update to version 1903, Build 18362 or higher.

I am running a higher version, it is not listed and generates an error.

PS 7.0.2 & 5.1.18362.752 give same message.

**Comment by therealkenc** [comment]
Discussion #5790.  WSL2 is in minor 1836x.1049
