### ISSUE TITLE
SCP command gives broken pipe error in WSL2 

### ISSUE THREAD

**Issue by neoncrash** [microsoft/WSL#5889]
# Environment

```none
Windows build number: 10.0.18363.1049
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Attempting to send files to hpc system using scp command using wsl 2. 
What was typed:
 scp file.txt username@destination:/dir/to_be/sent/

What was returned:
packet_write_wait: Connection to XXX.XXX.XXX.XXX port 22: Broken pipe
lost connection

**WSL logs**: 

#  Expected behavior

Expected a file to transfer to another system using scp.

# Actual behavior

File does not get sent. It should be noted that when converting back to WSL 1, the scp command works as intended.

**Comment by tksmatsubara** [comment]
I encountered the same issue.

**Comment by damien-666** [comment]
This was stopping us moving to WSL2 as we are using Azure AlwaysOn VPN which failed every time we ran an ssh session and did an ls but worked when we used OpenVPN.  I struggled searching for the answer for weeks and finally raised with Mircosoft Azure support who advised to change the MTU to 1400 or 1300 using the command: 

“sudo ip link set dev eth0 mtu 1400”  

This worked for me - hope it helps.

**Comment by silvio2402** [comment]
Hi, I had the same issue because **the file already existed**.
This would be fine and it would overwrite it, but **the file was opened in another program** causing it to be locked.
I hope this helps future people having this problem.

**Comment by zzvara** [comment]
> sudo ip link set dev eth0 mtu 1400

What a life safer! For me, though, 1300 worked, 1400 did not. <3

**Comment by k1muza** [comment]
`sudo ip link set dev eth0 mtu 1400`

This worked for me

**Comment by siddharthagudgunti** [comment]
> `sudo ip link set dev eth0 mtu 1400`
> 
> This worked for me

This also helped me with scp/sftp command get stuck at 0% with stalled state.

**Comment by Nehyan9895** [comment]
> Hi, I had the same issue because **the file already existed**. This would be fine and it would overwrite it, but **the file was opened in another program** causing it to be locked. I hope this helps future people having this problem.

I also have the same issue. How did you overcome that

**Comment by silvio2402** [comment]
> I also have the same issue. How did you overcome that
Either delete the file so SCP can create it or kill the program in which the files is opened.
