### ISSUE TITLE
WSL 2 will not start after installing KB4571756

### ISSUE THREAD

**Issue by sean-physna** [microsoft/WSL#5890]
# Environment

```none
Windows build number: 10.0.19042.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I don't have a full picture if this is something specific to my machine, but here goes...

1. Install [KB4571756](https://support.microsoft.com/en-us/help/4571756/windows-10-update-kb4571756) via Windows updates
2. Reboot (per Windows Update instructions)
3. Attempt to start WSL
4. Receive the message "The remote procedure call failed." with no further information.

I uninstalled KB4571756 and I was able to start WSL as expected.  To verify reproduction, I re-installed the update, and the issue reproduced easily.

**WSL logs**: 
Feedback Hub Issue: https://aka.ms/AA9n435

It appears there's a failure in trying to talk to the LxssManager service.  When run with `strace` via Git Bash:
```
$ strace wsl -d Ubuntu
The remote procedure call failed.
--- Process 16028 created
--- Process 16028 loaded C:\Windows\System32\ntdll.dll at 00007ffc1b450000
--- Process 16028 loaded C:\Windows\System32\kernel32.dll at 00007ffc19e60000
--- Process 16028 loaded C:\Windows\System32\KernelBase.dll at 00007ffc18e00000
--- Process 16028 loaded C:\Windows\System32\ucrtbase.dll at 00007ffc19250000
--- Process 16028 thread 16068 created
--- Process 16028 loaded C:\Windows\System32\SHCore.dll at 00007ffc1b2c0000
--- Process 16028 loaded C:\Windows\System32\msvcrt.dll at 00007ffc1b370000
--- Process 16028 loaded C:\Windows\System32\combase.dll at 00007ffc19b00000
--- Process 16028 loaded C:\Windows\System32\rpcrt4.dll at 00007ffc1aaf0000
--- Process 16028 thread 16188 created
--- Process 16028 thread 12708 created
--- Process 16028 loaded C:\Windows\System32\ws2_32.dll at 00007ffc1acd0000
--- Process 16028 loaded C:\Windows\System32\kernel.appcore.dll at 00007ffc17440000
--- Process 16028 loaded C:\Windows\System32\bcryptprimitives.dll at 00007ffc19120000
--- Process 16028 loaded C:\Windows\System32\sechost.dll at 00007ffc1ada0000
--- Process 16028 loaded C:\Windows\System32\clbcatq.dll at 00007ffc1a8f0000
--- Process 16028 thread 1176 created
--- Process 16028 thread 9708 created
--- Process 16028 thread 11952 created
--- Process 16028 loaded C:\Windows\System32\lxss\LxssManagerProxyStub.dll at 00007ffbf5110000
--- Process 16028, exception e06d7363 at 00007ffc18e23e49
--- Process 16028 unloaded DLL at 00007ffbf5110000
--- Process 16028, exception e06d7363 at 00007ffc18e23e49
--- Process 16028 thread 9708 exited with status 0xffffffff
--- Process 16028 thread 11952 exited with status 0xffffffff
--- Process 16028 thread 16188 exited with status 0xffffffff
--- Process 16028 thread 12708 exited with status 0xffffffff
--- Process 16028 thread 1176 exited with status 0xffffffff
--- Process 16028 thread 16068 exited with status 0xffffffff
--- Process 16028 exited with status 0xffffffff
```

In the Application Event Log, this event is emitted while starting WSL:
```
Faulting application name: vmwp.exe, version: 10.0.19041.488, time stamp: 0xfc760123
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x5b4a3325
Exception code: 0xc0000409
Fault offset: 0x000000000010b3cc
Faulting process id: 0x242c
Faulting application start time: 0x01d686e6dac064f6
Faulting application path: C:\Windows\System32\vmwp.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c5dd148a-69bd-4ce1-8ef8-ff91167eb314
Faulting package full name: 
Faulting package-relative application ID: 
```

#  Expected behavior
WSL starts up, and my shell is launched.

# Actual behavior
Only shown a `The remote procedure call failed.` message, and WSL cannot continue.
![image](https://user-images.githubusercontent.com/63727586/92649491-1dbcb780-f2b9-11ea-9a34-c5e1be73b313.png)

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by geoffwellman** [comment]
Getting the same issue here after KB4571756 update.

**Comment by cpbotha** [comment]
Same issue on my setup, which obviously also breaks Docker Desktop with the WSL2 backend.

Uninstalling KB4571756.

I'm happy this has already been reported!

**Comment by corehello** [comment]
Same issue here.

**Comment by AboveBill** [comment]
Same issue here. And unistalling KB4571756 didn't correct the issue for me

**Comment by divanikus** [comment]
Same issue here. Both Debian and Docker aren't starting anymore.

**Comment by ManzDev** [comment]
Same issue here. Uninstall KB4571756 fix problem and works again.

**Comment by zjsyj** [comment]
Same issue here Uninstall KB571756 fix problme and works again
windows version: 10.0.19402.487

**Comment by sean-physna** [comment]
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

Ah, forgot the link.  It's here: https://aka.ms/AA9n435

**Comment by coldKingdom** [comment]
Same here, but in 20211: https://aka.ms/AA9n5a4

**Comment by Brian-Perkins** [comment]
@coldKingdom on that build you may be running into #5768.

**Comment by coldKingdom** [comment]
> 
> 
> @coldKingdom on that build you may be running into #5768.

Thanks! But not at the moment, but maybe in the future ;)

**Comment by cpbotha** [comment]
@alexpaluzzi's work-around in https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294 has been fixing the post-update WSL2 upgrade for more folks than just himself.

**Comment by stevefan1999-personal** [comment]
0xC0000409

STATUS_STACK_BUFFER_OVERRUN

The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

My speculation is that the Windows 10 stack protection is triggered

**Comment by SolomonCM** [comment]
I was receiving a "no more endpoints available from the endpoint mapper" error from wsl2 after KB4571756 was installed. But, I found a solution to getting WSL2 back up and running again. WITH the update still installed. maybe this fix will work for you as well. just run windows setup to perform a repair install (in-place upgrade) and make sure the dynamic updates option remains enabled. windows setup will install the update during setup, and WSL2 should work afterwards, assuming there are no other issues. just running windows setup and doing a repair install without installing any updates does not seem to be enough, as the issues will return once KB4571756 gets installed.

**Comment by cperrin88** [comment]
I have a smiliar Problem but I only get the message "Fehler: 0xffffffff"

https://aka.ms/AA9pfko

**Comment by Remty5** [comment]
I'm also getting `The remote procedure call failed.` here.
[Logs](https://aka.ms/AA9phbv)

**Comment by craigloewen-msft** [comment]
A fix for this has been put in with KB4577063, which released today to users on the Release Preview channel on 20H2. 

Can any folks from here please try installing this KB and verifying that it resolved this issue for them?

**Comment by PGScully** [comment]
Installed this morning, and WSL2 works again :-)

**Comment by frankdavidcorona** [comment]
Please update the system: https://blogs.windows.com/windows-insider/2020/09/22/announcing-windows-10-insider-preview-build-19042-541-20h2/

**Comment by Remty5** [comment]
I can confirm that build 20226 fixed this issue for me.

**Comment by andressltz** [comment]
To fix, install this update KB4577063 (Windows 10 Build 19041.546) launched 10/01/2020, this issue has fixed in this update.

**Comment by sean-physna** [comment]
Confirmed - after installing that update on the Release Preview Channel, I could once again spin up WSL.  Thanks for the hard work and fix!
