### ISSUE TITLE
wsl --set-default-version 2 not working on Microsoft Windows [versão 10.0.18363.1016]

### ISSUE THREAD

**Issue by rleoneti** [microsoft/WSL#5891]
I can't run "wsl --set-default-version 2"
And my windows is 10.0.18363.1016

```
C:\WINDOWS\system32>ver

Microsoft Windows [versão 10.0.18363.1016]

C:\WINDOWS\system32>exit
PS C:\WINDOWS\system32> wsl --set-default-version 2
Opção de linha de comando inválida: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```

![image](https://user-images.githubusercontent.com/6199846/92657720-acd2cb00-f2cb-11ea-9e66-6e37da71fcf9.png)

**Comment by licanhua** [comment]
Please check Windows update or install .1049 manually.
This backport has the minor build number: 1049. To summarize, if your minor build number is 1049 or higher on Windows builds 18362 or 18363, then you have the backport and the ability to run WSL 2 distros.

If hit issue #5837, please try KB4566116 manually

**Comment by craigloewen-msft** [comment]
We added instructions to our docs to help fix this issue! @licanhua is right you need to update to the latest version.

Check out [these instructions](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#im-on-windows-10-version-1903-and-i-still-do-not-see-options-for-wsl-2) and they should resolve your issue. If not, please feel free to reopen. :)
