### ISSUE TITLE
WSL2中的mongo容器无法访问

### ISSUE THREAD

**Issue by Wangdaen** [microsoft/WSL#5892]
在WSL2中安装docker（没有使用docker desktop，而是直接在子系统中安装docker）
1.启动mongo容器：docker run -itd --name mongo -p 27017:27017 --restart=always -v /data/mongo/data:/data/db mongo:3.2.21
mongo容器启动，在WSL2子系统中可以通过127.0.0.1:27017 进行连接，但是在win10系统中通过127.0.0.1:27017 连接会出现连接失败，无法连接到该网络。不知道怎么解决该问题。
2.通过docker run -itd --name mongo -p 27017:27017 --restart=always -v /mnt/d/mongo/data:/data/db mongo:3.2.21 来启动mongo容器会出现启动失败，该问题目前也不知道是由什么原因造成的，目前通过上#1的方式来进行启动.

**Comment by marshalby2** [comment]
我和你遇到一模一样的问题，在WSL2中的用docker安装了redis、mongodb、mysql，只有mysql可以在程序中访问，redis和mongodb都是连接失败
