### ISSUE TITLE
Terminal echo broke after `nslookup` executed in Ubuntu 20.04

### ISSUE THREAD

**Issue by imReker** [microsoft/WSL#5894]
# Environment

```none
Windows build number: 10.0.20175.1000
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce
1. Type `nslookup` and press return key.
2. Press Ctrl+C to exit `nslookup`.

#  Expected behavior
Type-in anything, it will show in the terminal window.

# Actual behavior

Type-in anything in terminal, nothing happens.

I also tried Ubuntu 18.04 and Debian from Store, and this bug only happens on Ubuntu 20.04.

**Comment by therealkenc** [comment]
> anything in terminal

Happens with 20.04 on Real Linux too. You want ctrl-d or `exit` from the `nslookup` interactive prompt (not ctrl-c, which does not reset the tty). 

You can get out of the bind by typing `stty sane` blindly. In the screencap below, I have typed `<ctrl-c>`, `<enter>` a few times, and then `stty sane`, and then `<enter>` again.

![image](https://user-images.githubusercontent.com/7049700/92884913-26031880-f3c7-11ea-9ca6-d7cde90f8c58.png)

External.

**Comment by missmah** [comment]
Thanks @therealkenc! `stty` is awesome, thank you for illuminating a new tool for me today!

**Comment by scbates930** [comment]
I'm seeing this on Ubuntu 24.04.2 LTS   (azureVM) and using terminal from windows11 PC

stty sane  is still a valid work around.

**Comment by shine-on-me** [comment]
Same with Ubuntu 24.04.3 LTS, blindly typing `stty sane` or `reset` both work to break out of the broken terminal state.
