### ISSUE TITLE
Create new virtual ext4 disk and attach to available WSL2

### ISSUE THREAD

**Issue by phongmis** [microsoft/WSL#5896]
Does WSL2 allow create new ext4 virtual disk and attach to available WSL2 instance ?
If WSL2 allow, how can I do that.

**Comment by guissalustiano** [comment]
just came out of the oven this functionality
https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2

**Comment by ad-on-is** [comment]
> just came out of the oven this functionality
> https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2

This blog post explains only how to mount a physical disk, but not how to mount an *.ext4 file.

**Comment by onomatopellan** [comment]
Not easy, but possible. I've been using this for weeks without problems:

https://gist.github.com/onomatopellan/90024008a0d8c8a2ed6fa57e8b64df54

**Comment by therealkenc** [comment]
> This blog post explains only how to mount a physical disk

Documentation requests and PRs can be sent [here](https://github.com/MicrosoftDocs/WSL).
