### ISSUE TITLE
Error: 0xffffffff On windows update

### ISSUE THREAD

**Issue by mellester** [microsoft/WSL#5899]
# Environment
[Version 10.0.19041.450]
WSL 2
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
After installing windows updates on reboot. I got a Error: 0xffffffff.
After a hour of searching for a solution I Stopped and restarted Hyper-V Virtual Machine Management service and dockerD service.
Then it started working again

**Comment by markexperience** [comment]
Was this Windows 10 Pro or Home?
