### ISSUE TITLE
Add emoji support to Windows Console

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/WSL#590]
Windows Console does not support emoji and other extended character-sets, as reported by the [emoj](https://github.com/sindresorhus/emoj) team: https://github.com/sindresorhus/emoj/issues/5#issuecomment-228693561

Consider adding emoji support to Windows Console in the future

**Comment by MadcowD** [comment]
Come on; at least give us GPU support first.

**Comment by be5invis** [comment]
@bitcrazed 
Are you going to rewrite the entire CONHOST and console C/C++ API?
Gee...

**Comment by bitcrazed** [comment]
@be5invis Rewrite? Only the parts that desperately need it. Otherwise, we're re-architecting and modularizing much of the Console internals which will result in us being able to iterate FAR faster, and more confidently & safely.

**Comment by SandHilt** [comment]
_Make console great again._

**Comment by fcharlie** [comment]
Is there any progress in supporting emoji ?

**Comment by be5invis** [comment]
@fcharlie This is very hard, the entire console buffer is a **fixed** data structure that each cell has only 16 bits.

**Comment by be5invis** [comment]
@fcharlie And it has C++ interfaces...
Means that we cannot change that.

**Comment by fcharlie** [comment]
@be5invis I use WriteConsoleW output emoji :heart: ，mybe use DirectWrite can output more Emoji

![wsudo](https://raw.githubusercontent.com/M2Team/Privexec/master/images/wsudo3.png)

**Comment by coreh** [comment]
Not entirely sure on the internals, but it should be possible to affect only the rendering, without changing the underlying memory structure. (Even if the character spacing becomes "off" with emoji taking up the space of two regular characters, that would be a fine compromise)

**Comment by bitcrazed** [comment]
> 'it should be possible to affect only the rendering, without changing the underlying memory structure'

Sure ... if you're starting from scratch, you might chose some flexible encoding like UTF-8 (though that has it's own perf costs to consider), but doesn't help you when the Console's internal buffers are currently UCS-2 based and can't fully deal with Unicode scenarios including zero-width joiners, and surrogate pairs.

And in amongst the work to handle Unicode encodings that we don't currently support (e.g. UTF-8), we have to modularize and wrap the internal buffers, expose an API that the rest of the Console is modified to call, rather than allowing external code to delve into the data structures and directly manipulate memory in a somewhat haphazard manner!

**Comment by HotelCalifornia** [comment]
I hate to be _that guy_, but have there been any updates to this?

**Comment by bitcrazed** [comment]
@HotelCalifornia - You are now, officially, THAT guy ;) :D 

While we've not moved forward on this feature of late, we HAVE completed a ton of stuff & this ask is edging up the backlog. 

A few more things to get to yet, but it's getting closer. 

Bear with us!

**Comment by stereokai** [comment]
@bitcrazed thanks for the honest update. Does that mean UTF-8 is also on the way?

**Comment by bitcrazed** [comment]
Absolutely. UTF-8 support is a pre-req' for us to eventually support emoji, and many other complex languages, symbols, etc.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. As noted above, we've a long list of work items that'll enable Console to store and render MUCH more of the UNICODE glyph space. It'll take us a while to get through them, but the work has begun
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by lc5415** [comment]
None of these options are working for me. When I try to run any variant of `wsl --set-version Ubuntu 1` I get:
```sh 
Error: Oxffffffff
```

**Comment by bitcrazed** [comment]
Sorry @lc5415 - this is the Terminal repo, and a closed issue discussing emoji support. 

If you're having WSL issues, could you please file an issue on the WSL repo: https://github.com/microsoft/wsl. Thanks.

**Comment by lc5415** [comment]
Excuse me @bitcrazed I got the issue number wrong!

**Comment by bitcrazed** [comment]
No problem ... I've done this countless times myself ;)
