### ISSUE TITLE
can not start ubuntu-18.04 using wsl after update to 20211

### ISSUE THREAD

**Issue by songjunjian** [microsoft/WSL#5902]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

update the windows  to Windows 10 Insider Preview 20211.1000 (rs_prerelease),
using  window terminal , start ubuntu 18.04, failed, exit code : 4294967295,

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by zhenjun115** [comment]
same. can not start wsl

**Comment by sd9cf** [comment]
same problem

**Comment by oska874** [comment]
same problem.

**Comment by davelowper** [comment]
same here (using debian 10)

**Comment by oska874** [comment]
Can not install new linux too.

When I try to install a new alpine,it shows:

```
Temporary directory: C:\Users\leile\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-minirootfs-3.11.4-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\leile\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: 47210239fcdd9a1dca72238f13912187cbcf0898fda2d12d4b583781279791e0

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
WslRegisterDistribution failed
Error: 0x80070005 ?????

Press any key to continue...
```

**Comment by haosmos** [comment]
same problem (ubuntu-20.04, windows build 20211 x64): 

After starting wsl, the following message is displayed in the console: 

`process exited with code 4294967295`

I tried the following solutions: 

1.
```
❯ netsh winsock reset

Sucessfully reset the Winsock Catalog.
You must restart the computer in order to complete the reset.
```

After restarting the computer the problem was not solved - after starting wsl the same error is shown: 

`process exited with code 4294967295`

2. 
```
DISM /online /disable-feature /featurename:VirtualMachinePlatform /norestart
DISM /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart
```

Reboot, and then:

```
DISM /online /enable-feature /featurename:VirtualMachinePlatform /norestart
DISM /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart
```

After starting wsl, the same error is shown: 

`process exited with code 4294967295`

3. 
Removed the Linux kernel (wsl_update_x64.msi) and reinstalled it. After starting wsl the same error is shown: 

`process exited with code 4294967295`


When rolling back to the previous version of the build (20206) — wsl works as expected.

**Comment by Fuzl** [comment]
Hi, same problem here.
Just to mention I don't have a checkpoint at build 20206 so I'm stuck and must leave the fast ring.

**Comment by banyh** [comment]
Same problem.
Revert to build 20206 and Ubuntu 20.04 works again.

**Comment by xiaoqidun** [comment]
<img width="734" alt="xiaoqidun_2020-09-12_01-04-40" src="https://user-images.githubusercontent.com/12410603/92953259-02f26a80-f494-11ea-9463-55f592298afc.png">
same problem

**Comment by barrettg** [comment]
I had a similar problem in 20206 and fixed it by creating a `.wslconfig` file in my Windows user home directory and adding the following contents:
```
[wsl2]
swap=0
```

**Comment by mkontani** [comment]
I got same problem, but after repating signout/signin a few times, WSL (and Docker desktop) came to work as expected... 🤔  

```
PS C:\Users\mkontani> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      20211  0

PS C:\Users\mkontani> wsl
/mnt/c/Users/mkontani

```

**Comment by CJYLab** [comment]
same +1

**Comment by zhenjun115** [comment]
> I had a similar problem in 20206 and fixed it by creating a `.wslconfig` file in my Windows user home directory and adding the following contents:
> 
> ```
> [wsl2]
> swap=0
> ```

not work

**Comment by walkthetalk** [comment]
same +1

**Comment by QtacierP** [comment]
Same +1.

**Comment by phoenixjyb** [comment]
same issue here

**Comment by Pagliacii** [comment]
Same problem.

Windows version: Microsoft Windows [Version 10.0.20211.1000]
Distribution version:
```shell
~
❯ wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  ArchLinux       Stopped         1
```

When I try to start via `wsl` or `wsl -d xxx`, it always claims `The remote procedure call failed.`. 

And I can see the error message like below in the event viewer:
```
Faulting application name: svchost.exe_LxssManager, version: 10.0.20211.1000, time stamp: 0xb0e7c44f
Faulting module name: ucrtbase.dll, version: 10.0.20211.1000, time stamp: 0xb4267ab9
Exception code: 0xc0000409
Fault offset: 0x000000000007c99e
Faulting process id: 0xd60
Faulting application start time: 0x01d688d74192e9d1
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 91956537-19c2-4d4b-bf01-476d58f2ad53
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Pagliacii** [comment]
BTW, I found that if I start the virtual machine in VirtualBox, it will cause a green screen of death. Hopefully, this can help for debugging.

**Comment by Mengkzhaoyun** [comment]
same +1

**Comment by Li-Shang** [comment]
same +1

**Comment by sashizaki** [comment]
same +1

**Comment by shakthifuture** [comment]
Same issue

**Comment by zyazhb** [comment]
Same issue

**Comment by shakthifuture** [comment]
I resolved the issue using https://askubuntu.com/questions/234856/unable-to-do-remote-desktop-using-xrdp

**Comment by xldsdr124** [comment]
> BTW, I found that if I start the virtual machine in VirtualBox, it will cause a green screen of death. Hopefully, this can help for debugging.

The same problem, some of my Android emulators cannot start

**Comment by zergvszerg** [comment]
@shakthifuture  Could you elaborate? Also, this thread is about wsl2 unable to launch, not about xrdp.

**Comment by gskm** [comment]
Same error, Ubuntu 18.04 (WSL1) after update Windows to build 20211 from 20206 won't start with error "remote procedure call failed", LxssManager service won't start with error 7034 (System Event).

**Comment by xyjnradio** [comment]
same +1

**Comment by phpdev-m** [comment]
same +1

**Comment by joesdu** [comment]
same +1

**Comment by ty-me** [comment]
same + 1

**Comment by benhillis** [comment]
If you are hitting this issue I suggest rolling back to the previous Insider build.

**Comment by benhillis** [comment]
Locking to cut down on +1 spam.

**Comment by therealkenc** [comment]
/fixed [20226](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20226)
