### ISSUE TITLE
Linux FS unavailable from Windows in 20211

### ISSUE THREAD

**Issue by metcalfc** [microsoft/WSL#5903]
# Environment
 Win32NT             10.0.20211.0 Microsoft Windows NT 10.0.20211.0
Ubuntu  18.04
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
WSL2

# Steps to reproduce

Update to 20211 and try to use the Linux filesystem. 

I noticed that something was up when I launched Windows Terminal and my starting directory was in my home on the Windows FS. I use `"startingDirectory": "//wsl$/Ubuntu/home/metcalfc"`

So I tried to get to the Linux FS from explorer and run. 

![linuxfs](https://user-images.githubusercontent.com/31925/92857021-f8a77200-f3a8-11ea-9e88-e3e0a1858531.png)

**WSL logs**: https://aka.ms/AA9n518

#  Expected behavior

Ability to browse the WSL2 Linux FS from Windows.

# Actual behavior

The Linux FS is not accessable from Windows. It seems to ok once inside a WSL2 terminal on the Linux side.

Enjoy the Tarkov screenshot... 🤣

**Comment by therealkenc** [comment]
Thanks for doing wsl logs in the OP, appreciated. Works here on 20211 (will spare the screencap).

**Comment by metcalfc** [comment]
Worked for me as well. Before the update.

**Comment by metcalfc** [comment]
I hadn't realized this also breaks all the WSL/Windows integration bits like launching `code` inside of WSL:

``` 
code . 
/mnt/c/Users/metca/AppData/Local/Programs/Microsoft VS Code/Code.exe: Invalid argument
```

**Comment by metcalfc** [comment]
Reboots on 20211 did not resolve. However, updating to 20215 so far seems to resolve.

**Comment by metcalfc** [comment]
Its back. Same issue on 20215. I rebooted to add a hard drive and the issue has returned. Same exact presentation. I'll try more reboot 🔨 but several in a row and no dice. If ya'll have more troubleshooting guidance then have you tried turning it off and on again, I'd appreciate it.

**Comment by metcalfc** [comment]
Update. Its clearly intermittent. This time a `wsl --shutdown` seems to do the trick to fix it. The last time though a reboot seemed to be needed. Reboot seems to be the trigger not a WSL restart.

**Comment by craigloewen-msft** [comment]
Hey @metcalfc thanks for providing logs. We're taking a look into these internally. I unfortunately wasn't able to repro this, as you noticed it does seem like an intermittent/transient issue, so please let us know if you find out any more info about reproducing this. 

Thanks!

**Comment by metcalfc** [comment]
Update 20231 - Still happens. `wsl --shutdown` now consistently fixes the situation.
