### ISSUE TITLE
WSL2 distro can't start: the remote procedure call failed (build 20211)

### ISSUE THREAD

**Issue by mcornella** [microsoft/WSL#5907]
First of all, I've seen other issues similar to this one but none mentioned the error I get.

# Environment

```none
Windows build number: 20211
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

- `wsl --status`:
```
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 04/09/2020
WSL automatic updates are on.
Kernel version: 4.19.128
```

- `wsl -l -v`:
```
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
  Alpine    Stopped         2
```

# Steps to reproduce

1. Open `cmd`
2. Run `wsl` or `wsl -d <Distribution>` (both `Ubuntu` and `Alpine` fail)

**WSL logs**: https://aka.ms/AA9l9ap

#  Expected behavior

The distribution should start.

# Actual behavior

The `wsl` command fails with the error `The remote procedure call failed.`. Windows Terminal additionally reports `process exited with code 4294967295` (0xffffffff, -1).

~~Also I don't know if it's connected, but pings wouldn't work from inside WSL2 before this started happening, though dns resolution worked correctly~~ [Fixed this part using the first part of this solution](https://github.com/microsoft/WSL/issues/5336#issuecomment-653881695).

# More information

Things I've checked from other issues:

1. [I don't have `KB4571756` installed](https://github.com/microsoft/WSL/issues/5092#issuecomment-689786812).
2. [Services `LxssManager` and `LxssManagerUser_871e1` were stopped](https://github.com/microsoft/WSL/issues/4364#issuecomment-668862353). After starting them and running `wsl`, the same error happens and they go back to being stopped.
3. [Stopping the Hyper-V service from Hyper-V Manager didn't fix it, and neither did restarting it](https://github.com/microsoft/WSL/issues/5092#issuecomment-634342554).
4. [Stopping the SharedAccess service only made it start again](https://github.com/microsoft/WSL/issues/5092#issuecomment-651232028).
5. [Disabling and enabling WSL didn't fix it either](https://github.com/microsoft/WSL/issues/5092#issuecomment-645567980).
6. [Running powershell as admin and starting `wsl` from there got me the same error](https://github.com/microsoft/WSL/issues/5092#issuecomment-668393945).

I haven't tried:

- [Rolling back to 20206](https://github.com/microsoft/WSL/issues/5092#issuecomment-691131488), but I don't want to if at all possible. Plus, if there's an issue with 20211, I want to have it so that a fix can be tested in my machine.

**Comment by licanhua** [comment]
Possible dup of #5902

**Comment by mcornella** [comment]
Yep, I just thought it would be worth documenting, plus many of the error messages in that issue are different. I think that issue is a megathread of many different problems that all have the similarity of closing with error code 4294967295 (0xffffffff, -1), so it might be a good idea to split it based on the real underlying problem. Feel free to close it as dup though!

**Comment by sashizaki** [comment]
same +1

**Comment by klimelau** [comment]
same +1

**Comment by genby** [comment]
+1

**Comment by mcornella** [comment]
Alright after a day without WSL I gave in and [rolled back to build 20206](https://github.com/microsoft/WSL/issues/5092#issuecomment-691131488) and the thing works again. There's something wrong with 20211.

**Comment by klimelau** [comment]
> Alright after a day without WSL I gave in and [rolled back to build 20206](https://github.com/microsoft/WSL/issues/5092#issuecomment-691131488) and the thing works again. There's something wrong with 20211.

Could you explain how I can do that? Need WSL urgently

**Comment by mcornella** [comment]
You should have the option **Go back to the previous version of Windows 10** available:
![image](https://user-images.githubusercontent.com/1441704/92998397-e567e400-f519-11ea-9e7c-706c1e0b82f3.png)

**Comment by jin8495** [comment]
same +1

**Comment by adrianvaneeden** [comment]
Microsoft has acknowledged that [this is an error](https://www.zdnet.com/article/windows-10-2004-patch-tuesday-problem-update-breaks-wsl2-say-users/) in KB4571756.  See [workaround on this thread](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294) in response by @alexpaluzzi.  If you aren't OCD like me and don't clean up your disk every five hours you shodul be able to find an older copy of the file.  Luckily I had one on another laptop,

**Comment by faymek** [comment]
> Microsoft has acknowledged that [this is an error](https://www.zdnet.com/article/windows-10-2004-patch-tuesday-problem-update-breaks-wsl2-say-users/) in KB4571756. See [workaround on this thread](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294) in response by @alexpaluzzi. If you aren't OCD like me and don't clean up your disk every five hours you shodul be able to find an older copy of the file. Luckily I had one on another laptop,

What if I have `C:\Windows\System32\VmSynthNic.dll` with 389KB and `C:\Windows.old\WINDOWS\System32\VmSynthNic.dll`  with 398KB. Not missing, but changed.

**Comment by comzyh** [comment]
> Microsoft has acknowledged that [this is an error](https://www.zdnet.com/article/windows-10-2004-patch-tuesday-problem-update-breaks-wsl2-say-users/) in KB4571756. See [workaround on this thread](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294) in response by @alexpaluzzi. If you aren't OCD like me and don't clean up your disk every five hours you shodul be able to find an older copy of the file. Luckily I had one on another laptop,

I think this is a solution to a different issue. In build 20211, I do have `C:\Windows\System32\VmSynthNic.dll` in place. And I tried to reregister this dll and reboot, the problem doesn't get resolved.

**Comment by Cherry-Ran** [comment]
the same to you!

**Comment by onomatopellan** [comment]
> Microsoft has acknowledged that [this is an error](https://www.zdnet.com/article/windows-10-2004-patch-tuesday-problem-update-breaks-wsl2-say-users/) in KB4571756. See [workaround on this thread](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294) in response by @alexpaluzzi. If you aren't OCD like me and don't clean up your disk every five hours you shodul be able to find an older copy of the file. Luckily I had one on another laptop,

No. That update KB4571756 is a problem for people in build 19041 or 19042. This thread is for users that are running latest Windows 10 Insider Dev build which is build 20211 and has nothing to do with KB4571756.

**Comment by xju2** [comment]
Same problem here. The `C:\Windows\System32\VmSynthNic.dll` is there in build 20211.rs_prerelease.200904-1619. The problem reported here is different.

**Comment by moonheart** [comment]
WSL1 encountered the same problem.

![image](https://user-images.githubusercontent.com/15916990/93034109-8d40f700-f66b-11ea-9abb-c1aa9f43de75.png)
![image](https://user-images.githubusercontent.com/15916990/93034118-95993200-f66b-11ea-9989-e002811773b2.png)

**Comment by bongjun-lee** [comment]
same +1

**Comment by bbongcol** [comment]
same +1

**Comment by zergvszerg** [comment]
same +1

**Comment by machalvan** [comment]
same +1

**Comment by laurentschoonbrodt** [comment]
same +1

**Comment by kozmats** [comment]
same +1

**Comment by kanghoon-won** [comment]
the same to you!

**Comment by koten03** [comment]
same +1

**Comment by mcornella** [comment]
You can +1 the [initial post](https://github.com/microsoft/WSL/issues/5907#issue-699626805), commenting +1 only introduces noise.

**Comment by efim-a-efim** [comment]
Same here, solved by following [this instructions](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294)

**Comment by haosmos** [comment]
> Same here, solved by following [this instructions](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294)

@efim-a-efim, tell me, please, do you have build 20211 (x64) and wsl 2? 

Did you save the vmsynthnic.dll file that was used in the build 20206 and then register it in the build 20211?

And everything works?

**Comment by keremnymn** [comment]
Same here, using Ubuntu 20.04 LTS.

**Comment by laoshancun** [comment]
![image](https://user-images.githubusercontent.com/4952748/93154794-1bce7a80-f737-11ea-93a6-c998637201cc.png)
Same issue.

**Comment by per-lind** [comment]
+1

**Comment by phpdev-m** [comment]
same +1

**Comment by peter-jerry-ye** [comment]
Even when running `wsl` or `wsl -l` or `wsl --shutdown` in powershell, it will hang

**Comment by s8186255** [comment]
same+1

**Comment by benhillis** [comment]
Fixed has been submitted and is on the way to Insider builds.

**Comment by suneetk92** [comment]
> 
> 
> Fixed has been submitted and is on the way to Insider builds.

Any workaround till the fix is available in Beta Channel?

**Comment by paracetamol32** [comment]
same problem with build 20215

**Comment by ThreshHNS** [comment]
> Fixed has been submitted and is on the way to Insider builds.

Can you tell me when the next build with this fix will be released? My previous build was accidentally deleted, can't rollback 😢

**Comment by onomatopellan** [comment]
@ThreshHNS Normally 3-4 weeks from the moment tag "fixinbound" is added.

**Comment by chdenat** [comment]
@ThreshHNS . yesterday, I've asked to @craigloewen-msft , the WSL master @MSFT. Fix will be available in a couple of week.

**Comment by ThreshHNS** [comment]
@onomatopellan , @chdenat , thanks for your reply. Are there any temporary solutions to solve this problem or how can I access the files in the distribution. I can't open Ubuntu folder via explorer because of this error.

**Comment by chdenat** [comment]
the only workaround is to rollback :(

**Comment by craigloewen-msft** [comment]
I can confirm that the fix will be available within the next couple of weeks. The fix is checked in and it needs to go through the regular process to head out to Windows Insiders. Thank you!

**Comment by xdrew** [comment]
I'm on 20221 now and the most recent "OK" build is 20206. Could anyone tell me how to rollback to that exact version without loosing my licence? Thanks!

**Comment by chdenat** [comment]
> I'm on 20221 now and the most recent "OK" build is 20206. Could anyone tell me how to rollback to that exact version without loosing my licence? Thanks!

Check this : https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_update-insiderplat_pc/insider-build-18947-information-and-how-to/3c371d12-e61b-4152-93e9-0975a2643208

**Comment by yihua1218** [comment]
Rolling back not works for me, can I reinstall the whole Windows 10 to fix it? Or back to use WSL version 1?

**Comment by phpdev-m** [comment]
![image](https://user-images.githubusercontent.com/3937451/94092785-3ba82180-fe4e-11ea-97c3-87d2d76d7810.png)
ver have fixed, thank MS

**Comment by xdrew** [comment]
> Check this : https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_update-insiderplat_pc/insider-build-18947-information-and-how-to/3c371d12-e61b-4152-93e9-0975a2643208

Thanks! Checked this.
But it only allows rolling back to the previous installed build. In my case 20215. After this, the Get started button is disabled. 

So the only way I see is a clean install, but I need my wsl files(

**Comment by hwl985** [comment]
Hope MS can fix it. I won't losing my files.

**Comment by albertlian** [comment]
+1

**Comment by xdrew** [comment]
Ok, I got my files back from wsl, but it's not the perfect solution.
Just took the ext4.vhdx file here c:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_<junk>\LocalState\
Stopped wsl on target pc.
And then moved the file to that pc with ok build, found similar folder there and replaced original vhdx with the desired one.
Wsl started normally. I have same ubuntu versions on both pc. Not sure if it is a required condition.

**Comment by DonGuych** [comment]
Not fixed in 20221 build

And also, WSL 2 **AND 1** are broken, not only WSL 2 ...

**Comment by ThreshHNS** [comment]
> Ok, I got my files back from wsl, but it's not the perfect solution.
> Just took the ext4.vhdx file here c:\Users<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_\LocalState
> Stopped wsl on target pc.
> And then moved the file to that pc with ok build, found similar folder there and replaced original vhdx with the desired one.
> Wsl started normally. I have same ubuntu versions on both pc. Not sure if it is a required condition.

Thank you! You saved my deadlines <3

**Comment by chdenat** [comment]
> Not fixed in 20221 build
> 
> And also, WSL 2 **AND 1** are broken, not only WSL 2 ...

Check the thread... It will ve fixed in a couple of weeks.  N
There is no WSL changes in the last release. 

2 options  : 
wait or try to rollback 
If you rollback, so do not forget to block updates temporarily amd wait for a new release with the fix.

**Comment by Dutch77** [comment]
> > Not fixed in 20221 build
> > And also, WSL 2 **AND 1** are broken, not only WSL 2 ...
> 
> Check the thread... It will ve fixed in a couple of weeks. N
> There is no WSL changes in the last release.
> 
> 2 options :
> wait or try to rollback
> If you rollback, so do not forget to block updates temporarily amd wait for a new release with the fix.

I really, really hope it will be sooner, because there is no way back to 20206 from 20221. 
Is there a way to install 20206 without loosing files?

**Comment by chdenat** [comment]
@Dutch77 , did not check it, but you can download previous build iso here : https://docs.microsoft.com/fr-fr/windows-insider/flight-hub/ (in kit column)

**Comment by Dutch77** [comment]
@chdenat It won't let you keep files. All you can do is a clean install. Already tried that :/

**Comment by chdenat** [comment]
> @chdenat It won't let you keep files. All you can do is a clean install. Already tried that :/

What kind of files ? AFAIK it's a windows iso and installing it does not affect your files nor WSK distro. 
But you can export, by security, your distros  to restore later if needed

**Comment by anarinsk** [comment]
This issue is fixed with build 20226 for WSL 2 + Ubuntu 20.04 distro. Thanks for the effort.

**Comment by FengYong07** [comment]
> This issue is fixed with build 20226 for WSL 2 + Ubuntu 20.04 distro. Thanks for the effort.

Does it work in build 20226 for WSL 2 + Ubuntu 18.04 distro? Everytime after  updating my windows 10 in Dev, I got new problems. That was nasty.

**Comment by BlackDragonBE** [comment]
If anyone stumbles upon this page years later and has the same issue, simply kill all processes that start with "wsl" and try again.

**Comment by mrtcmn** [comment]
> If anyone stumbles upon this page years later and has the same issue, simply kill all processes that start with "wsl" and try again.

It's worked. But why :)

**Comment by arfans22** [comment]
I'm facing the same issue on my windows 11, doing `wsl --update` works for me!👍🏾
