### ISSUE TITLE
WSL 2 networking doesn't work at all for me

### ISSUE THREAD

**Issue by naikrovek** [microsoft/WSL#5908]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Your Distribution version: Release:        20.04  (It's Ubuntu)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 - cat /proc/version gives this: MSYS_NT-10.0-19041 version 3.0.7-338.x86_64 (Alexx@WARLOCK) (gcc version 9.1.0 (GCC) ) 2019-07-11 10:58 UTC
```

# Steps to reproduce

Not sure how to reproduce this, specifically, but it has happened on two of my machines in which I installed Hyper-V before enabling WSL, and I can't reproduce this on a new machine where WSL was enabled first.

When using WSL 2, networking doesn't work in any way.  Some of this may be due to my employer's firewall configuration, I don't know.  DNS lookups don't work, pinging the host WSL interface doesn't work, nothing.  No networking works at all.

Setting the WSL instance to V1, uninstalling Hyper-V, rebooting, then setting the WSL instance to V2 made networking work, but only once, and only until I rebooted next, and I can't reproduce that success, now.  I'm not sure what was going on there.  I'm back to no network connectivity at all in WSL 2 instances, no matter what I try.

I collected logs per Craig Loewen's instructions on twitter and they're attached below.

**WSL logs**: 
[logs.zip](https://github.com/microsoft/WSL/files/5211183/logs.zip)

#  Expected behavior

Networking should work.  I should be able to ping stuff and do DNS lookups and `apt` should be able to do its thing.  

# Actual behavior

Networking doesn't seem to be working at all in WSL 2 instances.  

If there is further details I can collect, let me know, and I'll collect them.  Edit the bug subject/title as desired.

**Comment by mahdi7839** [comment]
hi, i have the same problem, but on my machine i will access the outside via Wifi and not Ethernet.
                                                -----> Wifi ---->      INETRNET   (ok)
WSL2  ---->  Pyhsical Laptop  |
                                                -----> Eth0  ----->  INTERNET   (X)
theoretically between Wsl2 and Internet ( on the windows ) musst runed a NAT or PAT function. 
can you please test it that have you outside access over Wifi or conversely?

**Comment by naikrovek** [comment]
#5831 appears to be related.  Same basic symptoms at least.

**Comment by naikrovek** [comment]
@mahdi7839 I switched to Wi-Fi and it doesn't work.  I notice now that I have two virtual Ethernet adapters with the same IP address, and three with the same network, and that may or may not be related.  It probably isn't good, whether it's the cause of this or not.

```
...

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::81dc:177c:46ef:2535%81
   IPv4 Address. . . . . . . . . . . : 172.24.240.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

...

Ethernet adapter vEthernet (Ethernet):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::79b5:4ea9:47f5:356f%54
   IPv4 Address. . . . . . . . . . . : 172.29.240.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (Ethernet 3):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::bcf7:1940:76e9:5582%59
   IPv4 Address. . . . . . . . . . . : 172.29.224.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```

All of these are of course managed by Windows and I didn't set them up.

does this give you any clues as to what's going on?

**Comment by naikrovek** [comment]
https://gist.github.com/danvy/9486bf730371436131cb888ff4c2ceb6 does not fix the issue for me.

Disabling the non-WSL ethernet adapters which share IPs or networks does not resolve the issue for me.

**Comment by naikrovek** [comment]
if the cause of this particular issue has been found, can anyone let me know if there is a workaround?  anything short of a complete OS reinstall is acceptable to me.

I really want to use WSL 2...

**Comment by lukee1234** [comment]
If you modified, moved or compressed the temp folder, look at #5437 for the solution

**Comment by naikrovek** [comment]
> If you modified, moved or compressed the temp folder, look at #5437 for the solution

Thank you.  That isn't the problem, in my case.  I tried the fix anyway, and still no network.

**Comment by naikrovek** [comment]
I am no longer convinced that this problem is related to anything I posted in the issue originally.

There is a far more pedestrian problem in my cases, that I failed to take into consideration.  Company mandated firewall on non-domain networks, and all WSL 2 networks are non-domain networks.

Closing.
