### ISSUE TITLE
Bug - Cant install and load bash

### ISSUE THREAD

**Issue by ddarvish** [Microsoft/WSL#591]
using windows 10 enterprise insider preview
build 14366.rs1_release/160610-1700

running bash from start shows windows quickly opening and closing. launching bash from CMD prompt results in error 
Cannot launch bash because the LX subsystem has an install, uninstall, or servicing operation pending.

restarting system and removing and adding said feature from windows features control panel doesn't fix issue.

**Comment by benhillis** [comment]
Could you share the contents of the [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss] registry key with me?

After doing that could you run the following from an admin command prompt?
- sc stop lxssmanager
- bash.exe

**Comment by indoorowls** [comment]
ddarvish:

Are you running with Legacy Console Enabled by any chance?

I just fought with an issue mimicking your symptoms (running bash shows window opening but immediately closing, as well as some initial install difficulty) that was caused as I switched over to legacy console mode periodically as required for an Atom plugin.

Open a Command Prompt session, right click the menu bar and select Properties, Options to check.

This fixed my issue of Bash refusing to open, and I suspect that this was also behind the initial difficulties I had installing Bash - the problem seemed to 'fix itself', so I had previously attributed it to an Insider Preview update; but now I suspect it was me adjusting the Command Prompt legacy settings.

**Comment by vanstinator** [comment]
I was facing a similar issue. I deleted the registry entry for lxsss. After that I stopped the service and ran bash again. I was able to install at this point. (I had at one time played with bash before removing the feature from Windows again. I'd guess this is where I got bit).

**Comment by ddarvish** [comment]
actually i went ahead and just ended task on lxsss and the install went
through. this was a fresh install on windows so im sure it was a bug.

anyway all is well and good. if anyone wants to possibly assist me in
trying to install get get working GmusicFS (
https://github.com/EnigmaCurry/GMusicFS) which is based on the fuse file
system i think that would be great =)


Davis Darvish

**Comment by tw0517tw** [comment]
@indoorowls Thanks! This helped me to install bash.

**Comment by Bluscream** [comment]
```
lxrun /uninstall /full /y
lxrun /install /y
```

**Comment by ChiefAlu** [comment]
thx Bluscream
this helped me a lot.

**Comment by Choreza** [comment]
ty Bluscream!

**Comment by Bluscream** [comment]
np guys, calm it were just two commands thanks :D

**Comment by praveengambhir16** [comment]
@benhillis I was using the Ubuntu bash successfully. Since the past 2 days, I am getting an error 0x8007001f. The Desktop shortcut terminates immediately. The error occurs when I try to execute bash in command line interface. The lxssmanager status is as follows

SERVICE_NAME: lxssmanager
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by RohitJain13** [comment]
Thanks Bluscream!

**Comment by sunilmut** [comment]
@praveengambhir16 - Sorry to hear about that. Can you gather traces using [these](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#starting-bash-gives-an-error-code) instructions. And, share the traces out so that we can see where things are going wrong?

**Comment by big-kahuna-burger** [comment]
> lxrun /uninstall /full /y
> lxrun /install /y

But between these two remove `lxss` folder

**Comment by yamimaio** [comment]
This was it Bluscream!!

**Comment by Bluscream** [comment]
Thank you all for thanking me <3 i feel honored :3

**Comment by jpls93** [comment]
Thanks @Bluscream !!

**Comment by Ethergeist** [comment]
Fixed with the solution @Bluscream mentioned. Tried to delete the registry entries and stop the service as mentioned by @benhillis and @vanstinator  (I had previously manually deleted the LXSS folder) and it didn't work. Previously I had tried lxrun /uninstall /full /y and it had not worked, so it may have been a combination of the two methods that fixed the problem.
