### ISSUE TITLE
$WSL_DISTRO_NAME does not exists after sudo -i

### ISSUE THREAD

**Issue by Herbert256** [microsoft/WSL#5914]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: 1 Debian GNU/Linux 10 (buster) / imported from https://salsa.debian.org/debian/WSL/-/raw/master/x64/install.tar.gz
Whether the issue is on WSL 2 and/or WSL 1: WSL 2, Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Description

When I enter the distro with user root the environment variabele $WSL_DISTRO_NAME does exists

When I enter the distro with the default user and then go to the root user with `sudo -i`  or `sudo su - root` the environment variabele $WSL_DISTRO_NAME does not exists

# Steps to reproduce

```none
wsl -d distro -u root
echo $WSL_DISTRO_NAME
*distro name here*
```

```none
wsl -d distro
sudo -i
echo $WSL_DISTRO_NAME
*no distro name here*
```

**Comment by 0xbadfca11** [comment]
This is the correct behavior of sudo.
See man of sudoer(5).

**Comment by Herbert256** [comment]
sudo -i is supose to work as a new login, imho that means the result should be the same as directly login with root with 'wsl -d distro -u root'

```
wsl -d distro -u root  # $WSL_DISTRO_NAME does exists
sudo -i                       # $WSL_DISTRO_NAME does not exists
```

**Comment by therealkenc** [comment]
How [`sudo(1)`](https://man7.org/linux/man-pages/man8/sudo.8.html) is "supposed to work" is not dictated by WSL, your h.o. notwithstanding.

You probably want `Defaults env_keep=WSL_DISTRO_NAME` in your [`sudoers(5)`](https://man7.org/linux/man-pages/man5/sudoers.5.html), as 0xbadfca11 was implying.

![image](https://user-images.githubusercontent.com/7049700/93253246-78d42b80-f74b-11ea-87c9-fbd22910ed61.png)
