### ISSUE TITLE
Windows 10升级到20211版本，然后打开Ubuntu提示“远程过程调用失败”！

### ISSUE THREAD

**Issue by Cherry-Ran** [microsoft/WSL#5915]
Windows 10升级到20211版本，然后打开Ubuntu提示“远程过程调用失败”！Uubuntu重装了几次还是这样子！

After windows 10 is upgraded to 20211.1000, Ubuntu opens and prompts "remote call failed". It has been reinstalled several times, and it still looks like this

**Comment by comzyh** [comment]
Duplicate #5902 #5907 #5913

**Comment by nightmare-Z** [comment]
me too

**Comment by hailang8635** [comment]
me too, WHY?

**Comment by hailang8635** [comment]
and I cannot connect Wifi

**Comment by hejiadong0608** [comment]
me too.

**Comment by funny123** [comment]
me too

**Comment by lpj0711** [comment]
yes，i'm the same problem

**Comment by wilhelmjung** [comment]
me too.

**Comment by zhangshengsheng** [comment]
回退20201 正常  
Go back 20201

**Comment by nakixii** [comment]
20215还没修复
not fixed yet on 20215

**Comment by Sol-666** [comment]
> 20215还没修复
> not fixed yet on 20215

所以20215上有办法吗
Anything can do on 20215?

**Comment by duocang** [comment]
> > 20215还没修复
> > not fixed yet on 20215
> 
> 所以20215上有办法吗
> Anything can do on 20215?

NO. There is no fix on 20215. I have updated and no working yet.

**Comment by jingyangcarl** [comment]
me too

**Comment by FengYong07** [comment]
版本回退20206后正常
get back to 20206

**Comment by Mickeyto** [comment]
版本	Windows 10 专业版 Insider Preview
版本号	2004
安装日期	‎2020/‎9/‎25
操作系统版本	20221.1000
体验	Windows Feature Experience Pack 120.22800.0.0
remote call failed
![image](https://user-images.githubusercontent.com/20398129/94265717-97b49800-ff6b-11ea-99a1-329b7bbe8e5d.png)

**Comment by chenjie04** [comment]
> 版本 Windows 10 专业版 Insider Preview
> 版本号 2004
> 安装日期 ‎2020/‎9/‎25
> 操作系统版本 20221.1000
> 体验 Windows Feature Experience Pack 120.22800.0.0
> remote call failed
> ![image](https://user-images.githubusercontent.com/20398129/94265717-97b49800-ff6b-11ea-99a1-329b7bbe8e5d.png)

me too

**Comment by lujfsd** [comment]
> 版本 Windows 10 专业版 Insider Preview
> 版本号 2004
> 安装日期 ‎2020/‎9/‎25
> 操作系统版本 20221.1000
> 体验 Windows Feature Experience Pack 120.22800.0.0
> remote call failed
> ![image](https://user-images.githubusercontent.com/20398129/94265717-97b49800-ff6b-11ea-99a1-329b7bbe8e5d.png)

me too
