### ISSUE TITLE
Scroll feature in Ubuntu 20.04 LTS terminal for windows

### ISSUE THREAD

**Issue by nj1902** [microsoft/WSL#5916]
**Is your feature request related to a problem? Please describe.**
Commands can be viewed till window screen ends, terminal has no scroll feature.
tput -x clear command working same as clear command. 

**Describe the solution you'd like**
Include scroll feature directly from Ubuntu code base and link related commands like tput as well.

**Describe alternatives you've considered**
Shift + Page UP/DOWN or Ctrl + Arrow Keys could be possible alternate.

**Additional context**
Like command prompt include function key 'F7' feature 'to list used commands' and switch between them as well.

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/93032192-14975780-f5e5-11ea-8643-613d85da3bdb.png)

![image](https://user-images.githubusercontent.com/189190/93032198-195c0b80-f5e5-11ea-9f95-802585b8b80b.png)

Make sure "Screen Buffer Size" height is large. This will fix scrolling and history.

**Comment by nj1902** [comment]
Thank you, @DHowett .
