### ISSUE TITLE
Commands not executing in Ubuntu-18.04 distribution even though distro is running and accessible 

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#5917]
Started seeing a problem where Ubuntu18.04 commands are not running (details below) but wsl command shows its running and I can access the files in the distro using explorer. Other distros are behaving normally

```
wsl --list --all --verbose
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  Alpine                 Stopped         2
  Ubuntu-18.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Debian                 Stopped         2
```
# Environment

Windows build number:  10.0.20211.0
Your Distribution version: Ubuntu-18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2

# Steps to reproduce

Running "wsl -d Ubuntu-18.04 pwd" exits without output, 

"wsl -d Ubuntu-18.04" also just returns.

Running the Ubuntu-18.04 distribution in a terminal just reports "[process exited with code 1]"

As noted above wsl shows the distribution as running 

windows explorer is able to access and operate on the files within the distribution

#  Expected behavior

Ubuntu should execute entered commands

# Actual behavior

Ubuntu is not coming up

**Comment by DHowett** [comment]
Does it work if you do `wsl -d Ubuntu-18.04 -e /bin/sh`?

If that works, can you run `wsl -d Ubuntu-18.04 -e /bin/bash -l -i -x`? That will run bash directly in a mode that prints out the commands that it's running as part of startup. You can likely pinpoint which of them is run directly before the shell exits.

**Comment by mwoodpatrick** [comment]
Many thanks for your response, much appreciated. Yes "wsl -d Ubuntu-18.04 -e /bin/sh" works, as curiously so does "wsl -d Ubuntu-18.04 -e /bin/bash"  but "wsl -d Ubuntu-18.04" just returns. In my first test case in the original message I had "wsl -d Ubuntu-18.04 pwd" I was missing the "-e". Does anyone know what command "wsl -d Ubuntu-18.04" actually runs on the target?

**Comment by DHowett** [comment]
It should be running your login shell; after you get it started can you run `getent passwd yourusername` and see what shell is configured for your user?

(If it is `/bin/bash`, you can start it as a login shell with `/bib/bash -li`)

**Comment by mwoodpatrick** [comment]
There was a problem in my entry in /etc/passwd after I changed my shell. 

This issue is now resolved

Many thanks for your help
