### ISSUE TITLE
Cannot Update from WSL 1 to WSL 2

### ISSUE THREAD

**Issue by dostarora97** [microsoft/WSL#5922]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Your Distribution version: Ubuntu 16.04
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce

**I need to update from WSL 1 to WSL 2.**   

I have read and followed these instructions : [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

These commands were run in Powershell(administrator) :  

1. `wsl -l -v`
![image](https://user-images.githubusercontent.com/31973060/93140045-69c78c00-f6ff-11ea-8c16-914c1798b70e.png)

2. `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
![image](https://user-images.githubusercontent.com/31973060/93140387-f96d3a80-f6ff-11ea-85c7-10ed91d31922.png)

3. System Restart...

4. `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
![image](https://user-images.githubusercontent.com/31973060/93140594-57018700-f700-11ea-8346-63ffd3c067ce.png)

Virtualization Enabled as seen in Task-Manager:
![image](https://user-images.githubusercontent.com/31973060/93142185-27a04980-f703-11ea-8e6b-f27e99fa076f.png)

5. System Restart...

6. `wsl --set-default-version 2`
![image](https://user-images.githubusercontent.com/31973060/93140694-83b59e80-f700-11ea-98c9-aa89181ec404.png)  
I guess this is not the **Expected output**, because [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-wsl-2-as-your-default-version) it says the output should be : `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`

7. `wsl -l -v`
![image](https://user-images.githubusercontent.com/31973060/93140866-cb3c2a80-f700-11ea-9e7b-cc808a7a2bfd.png)

**WSL logs**: https://aka.ms/AA9olbc

#  Expected behavior

The WSL should update from version 1 to version 2. That is after running command `wsl -l -v` in Powershell(administrator), it should say `2` under `VERSION`

# Actual behavior

Even after following the instructions to update WSL, it's version still remains `1`

**Comment by MathijsNL** [comment]
Did you enable this Windows update option? I believe you need it enabled.

![image](https://user-images.githubusercontent.com/1612886/93148501-392e2500-f6f4-11ea-908f-c1a40db95106.png)

**Comment by dostarora97** [comment]
I have that Windows option **Enabled**

```
> wsl cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```
![image](https://user-images.githubusercontent.com/31973060/93171137-25abaa00-f746-11ea-9437-7ae16434792c.png)

**Comment by power4** [comment]
I have the same problem.the same win version(Version 10.0.19041.508).i can't upgrade to wsl2 always

**Comment by therealkenc** [comment]
> 6. wsl --set-default-version 2

You want `wsl.exe --set-version Legacy 2`. The `--set-default-version` switch does just that; it changes the default. It doesn't change the version of the currently installed distro(s). The output in the OP is correct. Docs to set your distribution version [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2).

As an aside, "Legacy" is not all that common to have around anymore. The `--set-version 2` should take, but all things being equal, installing a new distro from the Store is probably not a bad idea in the circumstance.
