### ISSUE TITLE
Sourcing a bash script with dirname command in it crashes Windows Console

### ISSUE THREAD

**Issue by kenny1983** [microsoft/WSL#5924]
# Environment

Windows build number: 10.0.19041.508.
Your Distribution version: Debian 10.
Whether the issue is on WSL 2 and/or WSL 1: WSL 2.

# Steps to reproduce

1. Create the following script and save it as `script.sh`:
```
#! /bin/bash

set -e
dir=`dirname "$0"`
```
2. Run said script by `source`-ing it:
`source script.sh`

**WSL logs**: 
https://aka.ms/AA9o7ir

#  Expected behavior
Script runs as is normal in a proper GNU/Linux environment.

# Actual behavior
Windows Console window that was hosting the Debian session crashes!

Hi all!

Issue template pretty much says it all, except that `dirname <anything>` outside of a script works fine, and my real script also runs fine if I don't `source` it. The above example script is just the simplest, shortest thing I could come up with to demonstrate the problem. I have narrowed down my real script to just these few lines and the session still crashes.

I can't exactly provide an strace since `strace -o source.strace -f source script.sh` returns `strace: Can't stat 'source': No such file or directory`...if I've left out anything else vital, please let me know. MTIA! 😄

**Comment by DHowett** [comment]
Can you try...

`strace -o source.strace -f bash -c "source script.sh"`

It should let us see what bash is doing when it’s handling `source`.

**Comment by kenny1983** [comment]
@DHowett Here you go. Thanks again!

https://gist.github.com/kenny1983/f5e8e28c7d3bed157ec082324ff188f7

**Comment by therealkenc** [comment]
Bouncing the script off `bash -c` suppresses the behavior unfortunately. No guesses yet.

![image](https://user-images.githubusercontent.com/7049700/93229539-8ed1f400-f72b-11ea-8656-fbb749fbd720.png)

**Comment by therealkenc** [comment]
Looks like linux-behavior. I just can't justify the reason off the cuff. That `.178` is a Linux box on bare metal. 

![image](https://user-images.githubusercontent.com/7049700/93230302-61397a80-f72c-11ea-9896-84e6c65294c4.png)

**Comment by therealkenc** [comment]
It is nonobv behavior combination `source` plus [`set -e`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#The-Set-Builtin).

> Exit immediately if a pipeline (see Pipelines), which may consist of a single simple command (see Simple Commands), a list (see Lists), or a compound command (see Compound Commands) returns a non-zero status. 

The shell "exited immediately" on the error, and because `source`, the shell that exited is the only one you got.

**Comment by kenny1983** [comment]
Ahh fair enough @therealkenc. Thanks for sorting it out for me!
