### ISSUE TITLE
How to reset the date in WSL

### ISSUE THREAD

**Issue by AlphaKennyBudy** [microsoft/WSL#5925]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

When I was on a lesson I ran `sudo date --set="Sat Oct 14 13:23:53 EDT 1989"` to change the date. But I don't know how to reset my date to default (current), so I tried `timedatectl` but it showed me an error. It changed the date on both WSL that I have (Ubuntu and Kali Linux)

#  Expected behavior

`timedatectl set–ntp yes` should sync my date with NIST atomic clock

# Actual behavior
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
```

**Comment by onomatopellan** [comment]
does `sudo hwclock -s` work?

**Comment by AlphaKennyBudy** [comment]
> does `sudo hwclock -s` work?

thank you, it worked
