### ISSUE TITLE
系统找不到指定的文件。(The system can not find the file specified.)

### ISSUE THREAD

**Issue by ihbing** [microsoft/WSL#5930]
# Environment
window 10 2004 119041.450
![image](https://user-images.githubusercontent.com/27600008/93295143-f452dd00-f81e-11ea-8b38-e6d4906fe626.png)

# Steps to reproduce

![image](https://user-images.githubusercontent.com/27600008/93295209-14829c00-f81f-11ea-8289-2d4a79a35418.png)
```
Installing, this may take a few minutes...
系统找不到指定的文件。
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: ihbing
系统找不到指定的文件。
Enter new UNIX username:
```

**Comment by ihbing** [comment]
If you have downloaded the Appx file then extract it with any unzipping tool (for example 7zip) in a folder and run the ubuntu.exe in it.

**Comment by lanceyliao** [comment]
> 如果您已经下载了 Appx 文件，请使用任何解压工具（例如 7zip）将其解压到文件夹中，然后运行其中的 ubuntu.exe。
![image](https://github.com/microsoft/WSL/assets/45159389/e3ad07dd-41d0-49e2-9ea9-ef11eecda089)

遇到了相同问题。win10升级win11时要求我卸载了wsl，可能因为使用的第三方卸载软件，卸载了核心的系统组件。尝试过各种方式甚至修复系统（类似win10升级win11的方式，保留应用），未果。

看到这个帖子，在https://store.rg-adguard.net/ 下载了
CanonicalGroupLimited.Ubuntu_2204.3.49.0_neutral_~_79rhkp1fndgsc.AppxBundle
但这个appx文件没有解压选项并不是一个压缩文件？

请问是如何处理的？

**Comment by lanceyliao** [comment]
![image](https://github.com/microsoft/WSL/assets/45159389/96d8483f-afe2-4342-a947-a76b896e142f)
