### ISSUE TITLE
Strange characters appeared when entering Tmux

### ISSUE THREAD

**Issue by hexh250786313** [microsoft/WSL#5931]
# Environment

```none
Windows build number: Microsoft Windows [ver 10.0.19041.508]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
Tmux ver: tmux next-3.3
```

# Steps to reproduce

1. On WSL 2
2. Create a new session on tmux. I execute: `tmux new -s test`, then enter the session.
3. Or attach an old session: `tmux attach -t test`

#  Expected behavior

no strange characters

# Actual behavior

There are some strange characters appeared before the cursor. They are `0;10;1c`. Like this: 

![image](https://user-images.githubusercontent.com/26080416/93303612-5bc45900-f82e-11ea-9b3f-9bfbdb52d7d2.png)

But it didn't always happen. This is a chance event.

**Comment by hexh250786313** [comment]
And it happened in both my desktop and laptop.

**Comment by hexh250786313** [comment]
And it didn't happened in WSL 1. But my WSL 1 is Ubuntu 18.04. I'm not sure this is related to the Linux version or the WSL version.

**Comment by hexh250786313** [comment]
Ok, I finally resolved it. It happened when tmux run on Ubuntu 20.04. When your `.tmux.conf` has the line `set -sg escape-time 0`, it happens.

On Ubuntu 18.04, I add this line because there is a delay when I press `Esc` key. But the delay seems to be resolved on Ubuntu 20.04. And if I add the line `set -sg escape-time 0` on 20.04, The strange characters appear.

So I just need to delete the line `set -sg escape-time 0` on 20.04.

**Comment by kcking** [comment]
> 
> 
> Ok, I finally resolved it. It happened when tmux run on Ubuntu 20.04. When your `.tmux.conf` has the line `set -sg escape-time 0`, it happens.
> 
> On Ubuntu 18.04, I add this line because there is a delay when I press `Esc` key. But if I add the line `set -sg escape-time 0` on 20.04, The strange characters appear. I think it is because of the 0s. Finally I change it to 50ms (500ms default).
> 
> So I just need to change the line to `set -sg escape-time 50` on 20.04 and issue resolved.

Thank you for reporting your solution! This fixed my issue as well, I was also seeing `0;10;1c` on tmux start (using wezterm and tmux on wsl2 debian).

**Comment by kchen0x** [comment]
It helps!

**Comment by roachsinai** [comment]
Seems it works only for the first time start a Session, if you exit current session and run `tmux` again, prints chars again.

_Originally posted by @roachsinai in https://github.com/tmux-plugins/tmux-sensible/issues/61#issuecomment-880501724_

**Comment by trallnag** [comment]
For me only thing that fixed the characters appearing was placing `set -sg escape-time 50` right at the beginning of my `tmux.conf` before using `run-shell` to source a shell script that contains the bulk of my configuration.

https://github.com/tmux-plugins/tmux-sensible/issues/61#issuecomment-932816793

**Comment by zhuzhzh** [comment]
I didn't set `set -sg escape-time 50`, but I still have this issue with Windows Terminal Version: 1.11.3471.0.
I tried to remove .tmux.conf, and it still has this issue.

**Comment by quique0194** [comment]
It seems like "tmux-sensible" plugins sets escape-time=0

```
 grep escape-time -R .tmux/plugins
.tmux/plugins/tmux-sensible/README.md:set -s escape-time 0
.tmux/plugins/tmux-sensible/sensible.tmux:      if server_option_value_not_changed "escape-time" "500"; then
.tmux/plugins/tmux-sensible/sensible.tmux:              tmux set-option -s escape-time 0

```

**Comment by Blosberg** [comment]
Apparently the option in "sensible" is apparently to avoid [this issue](https://superuser.com/questions/252214/slight-delay-when-switching-modes-in-vim-using-tmux-or-screen/252717#252717
), and the `escape-time` parameter will 

> 'Set the time in milliseconds for which tmux waits after an escape is input to determine if it is part of a function or meta key sequences

Considering that, I think it would be advisable to set it as low as possible. I had the same problem as OP (with the exact same characters: `0;10;1c`) when there was nothing in my .tmux.conf about escape time (because the value was being set by  the "sensible" plugin to zero). When I explicitly set the value in .tmux.conf

`set -sg escape-time 50`

The weird character problem went away. Then when I set 

`set -sg escape-time 0`

The problem came back. So that's what's causing it, but I don't want to have a lag when leaving insert mode, so I set the following:

`set -sg escape-time 1` (which will allow 1 millisecond to escape insert mode  --imperceptible to any human user, but enough to avoid these characters)

**Comment by alinademi** [comment]
> Ok, I finally resolved it. It happened when tmux run on Ubuntu 20.04. When your `.tmux.conf` has the line `set -sg escape-time 0`, it happens.
> 
> On Ubuntu 18.04, I add this line because there is a delay when I press `Esc` key. But if I add the line `set -sg escape-time 0` on 20.04, The strange characters appear. I think it is because of the 0s. Finally I change it to 50ms (500ms default).
> 
> So I just need to change the line to `set -sg escape-time 50` on 20.04 and issue resolved.

Thanks! I confirm that this solved the issue! 🙏🏼

**Comment by pushpendra1x** [comment]
For me any value other than 0 is working in below command:

`set -sg escape-time 1
`
I put above in .tmux.conf

**Comment by smprather** [comment]
It's great that there's a work-around (and I will be using it), but did anyone try to root-cause and fix properly?

**Comment by smprather** [comment]
Note: I never had this problem with KiTTY. I am only seeing it now that I am trying to switch to Alacritty. Due to flakiness of the network I work on, I get a good number of disconnect/reconnects. Each reconnect to tmux generates this string. So I see it constantly. And it is not just "terminal noise". It is registering as real keystrokes to bash. This is what I see after a weekend of not working. (I hit `Enter` to verify that the chars were recognized by bash)
```
$ 0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c0;10;1c                                                                                                                                                      bash: 10: command not found
bash: 1c0: command not found
bash: 10: command not found
bash: 1c0: command not found
bash: 10: command not found
bash: 1c0: command not found
```

**Comment by Dan1jel** [comment]
Also started to see this issue... dont know why but when i start a `tmux new -s Big_letter_at_start` it usually showd thouse wierd symols, but when i had all lowered case i didnt see it.

when i removed the line `set -s escape-time 0` with # it all seams to work as intended...

**Comment by chrismferguson** [comment]
for anyone having it not work, place the set -s escape-time 1 line after the tmux sensible line.

**Comment by stewartli** [comment]
it happens to me after upgraded Ubuntu (V22). nothing above works for me.

**Comment by arecarn** [comment]
A related question similar to this was answered here: https://serverfault.com/a/1130091/481120. 

Here's the relevant part of the answer:

> It's the terminal's response to an ESC [ c "Request terminal attributes" that was issued by the remote program.
>
> (\033[c "Request terminal attributes" is one of several information requests that tmux outputs to the terminal, expecting to receive similar responses as input coming from the terminal (normally they would be invisibly consumed by tmux, just like special-key sequences are).

**Comment by baydakovss** [comment]
> set -s escape-time 1
In my case the issue disappeared when I put "tmux-sensible" and the workaround with "escape-time" just before initializing the plugins by plugin manager
```
set -g @plugin 'tmux-plugins/tmux-sensible'
# Workaround. Prevent appearing 0;10;1c when tmux start
set -sg escape-time 1
#
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by ariusxi** [comment]
> Ok, I finally resolved it. It happened when tmux run on Ubuntu 20.04. When your `.tmux.conf` has the line `set -sg escape-time 0`, it happens.
> 
> On Ubuntu 18.04, I add this line because there is a delay when I press `Esc` key. But if I add the line `set -sg escape-time 0` on 20.04, The strange characters appear. I think it is because of the 0s. Finally I change it to 50ms (500ms default).
> 
> So I just need to change the line to `set -sg escape-time 50` on 20.04 and issue resolved.

Thanks man, it works for me!

**Comment by khayo** [comment]
Probably this is some kind of absurdI know this is absurd and that this solution will give a loading error, but it was the only thing that made the strange characters not appear

`set -sg escape-time -1`

I'm using manjaro i3 with urxvt terminal

**Comment by baleti** [comment]
`set -sg escape-time 50` did nothing, issue still persists on every terminal except for wt.exe (windows terminal)

**Comment by Dan1jel** [comment]
> `set -sg escape-time 50` did nothing, issue still persists on every terminal except for wt.exe (windows terminal)

I have ```set -s escape-time 0``` in my .tux.conf file. Haven't got this issue for a long time now.

**Comment by giuliohome** [comment]
This is unresolved for win10: there the workaround is launching `cmd` instead of `wt`. 
Probably because the new conpty stack  implementation is bugged at that os level.
