### ISSUE TITLE
[BUG] Ctrl+r,  input some, Tab, get Suspended !

### ISSUE THREAD

**Issue by IanVzs** [microsoft/WSL#5934]
# Environment

```
Surface Book i7 16G 13.5inch, Windows 10 Pro 2004(OS BUILD: 19041.508)
```

# Steps to reproduce
1. Input `Ctrl+r`, show: (reverse-i-search)`':
2. input some thing, like `sou` show: (reverse-i-search)`sou': source ~/.profile
3. Input `Tab` to fill all orders. show :"~$ ource ~/.profile" or "~$ source ~/.profile" but then can not do anything.
4. Input `Ctrl+c`, if you got "$ ^Curce ~/.profile"  Congratulation! You reproduce this bug!

**WSL logs**: 
I do not know where it is.It may have nothing output.

#  Expected behavior

Fix that. I can fill all orders, and run this command.

# Actual behavior
???

**Comment by therealkenc** [comment]
Type `<enter> <enter> stty sane <enter>` blindly.

**Comment by therealkenc** [comment]
@IanVzs - Does `stty sane` restore your terminal after you've canceled the search?

Please post the contents of `strace -tt -f -o bash.strace /bin/bash`, either as a [gist](https://gist.github.com/) or attach a zip. At step 3, wait for round ten seconds before canceling with `ctrl-c` and then exiting. You should be able to exit the traced subshell by either typing `ctrl-d` or blindly typing `exit <enter>`. Cannot reproduce here, but it will look something like:

![image](https://user-images.githubusercontent.com/7049700/94966901-e786e800-04b2-11eb-8cd4-1619bdfa9bde.png)

**Comment by IanVzs** [comment]
[Uploading bash.strace.txt…]()

**Comment by andyneff** [comment]
I'm having the same issue. It can freeze for over **20** seconds. Happens on both WSL1 and WSL2, on Ubuntu, Fedora, and alpine alike.

The problem occurs if I'm using Windows Terminal, Mintty, command prompt terminal, powershell terminal, or wsl.exe (which I think is the same as command prompt)

Typing in `stty sane` before trying didn't seem to make much of a difference.

The interesting thing to note is the bell sound happens only AFTER the freeze finishes freezing.

The more and more I "test" this issue, the less it's happening. So now, for example there's either no freeze delay, or less than a second. But it was timed at over 20 seconds earlier. I've restarted my Windows Terminal several times, and it's inconsistent

Please reopen this issue

**Comment by margarineHound** [comment]
This issue is still happening for me 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000

NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"

**Comment by rdmtinez** [comment]
Its July 21, 2022, and this bug is still part of WSL, c'mon now

**Comment by gdi1942** [comment]
I am experiencing this issue on my Debian WSL, I think it should be reopened.
This issue is exactly as described in the title.
Windows: Microsoft Windows [Version 10.0.19044.2006]
WSL: Debian GNU/Linux 11 (bullseye)

**Comment by dvyas1** [comment]
Same issue here. Windows 11, WSL 2.

**Comment by cylzxje** [comment]
Bruh it's 2023 fix it please Microsuck

**Comment by mezdej** [comment]
WSL: Debian GNU/Linux 11
just go with ctrl + r, find something and press tab
I can no longer use terminal...

**Comment by AndersHogqvist** [comment]
Same issue here!

**Comment by huyxdong** [comment]
I have an exactly similar issue. 
OS: Windows 11 22H2 (OS Build 22621.1413)
WSL2: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

**Comment by monrage** [comment]
I had a similar problem.
found a third party solution https://github.com/junegunn/fzf
(not for advertising purposes)

**Comment by hawkwithwind** [comment]
I have same issue here with WSL 2, it was good on WSL 1, but I need docker desktop, so I have to change to WSL 2, and then the issue happens.
OS: 
Windows 11  22H2 (OS Build 22621.1555)
with Windows Feature Experience Pack 1000.22640.1000.0

WSL2: 
Ubuntu-20.04.6 LTS (2004.6.13.0)

please fix it.

**Comment by meitham** [comment]
I have experinced this issue too.  It is either a bug in WSL or the Windows Focus API.

Usually when you press "CTRL+r" while the focus is in a WSL terminal, you would expect the focus window to receive the CTRL+r keybind, but somehow in this case I found Symphony (An ATOM based messaging system) to have received the CTRL-r, despite it not having the focus, which prevents the reverse search history from working in WSL!

**Comment by AndersHogqvist** [comment]
I don't know if any dev reads this since the ticket has been closed, but it should be re-opened since the issue obviously isn't solved.

**Comment by asadis7171** [comment]
Yes this issue still persists please provide the solution

**Comment by rdmtinez** [comment]
Not too long ago I figured out what the actual problem is... What's hapenning is that upon Tab where we're expecting autocomplete, the CLI is actually cycling through $PATH (linux wsl: `echo $PATH`) in search of the script and not actually autocompleting. Generally this wouldn't be an issue in a linux system, but if you look closely at the $PATH in WSL it also includes /mnt/c/Windows ... causing a HUGE overheard in which to search. A solution is to remove the windows paths before they're loaded. Hope that helps.

**Comment by AndersHogqvist** [comment]
> Not too long ago I figured out what the actual problem is... What's hapenning is that upon Tab where we're expecting autocomplete, the CLI is actually cycling through $PATH (linux wsl: `echo $PATH`) in search of the script and not actually autocompleting. Generally this wouldn't be an issue in a linux system, but if you look closely at the $PATH in WSL it also includes /mnt/c/Windows ... causing a HUGE overheard in which to search. A solution is to remove the windows paths before they're loaded. Hope that helps.

Tried this but it didn't work for me. If I do a ctrl-r, then tab and then ctrl-c to abort the shell gets stuck and I have to close it.

**Comment by sarahandromeda** [comment]
I have also noticed this issue recently. 

1. `Ctrl-R` -> Being typing command to find
2. Without cycling through options hit `Tab` or an `Arrow Key` to fill in match
3. Cursor starts before text but can not move
4. Hitting `Ctrl-C` does nothing
5. Can not type `Exit`
6. Must close terminal to reset
    1. If I wait long enough, it seems like it eventually works (just found that out when testing for details)

Additional Info:
- Does not happen consistently
- Seems to be happening more frequently
- Seems to happen when using `Tab` or an `ArrowKey` to fill in the match

> Not too long ago I figured out what the actual problem is... What's hapenning is that upon Tab where we're expecting autocomplete, the CLI is actually cycling through $PATH (linux wsl: `echo $PATH`) in search of the script and not actually autocompleting. Generally this wouldn't be an issue in a linux system, but if you look closely at the $PATH in WSL it also includes /mnt/c/Windows ... causing a HUGE overheard in which to search. A solution is to remove the windows paths before they're loaded. Hope that helps.

For this solution, is removing the Windows `mnt` file from my `$PATH` safe? In order for that solution to work, I imagine I need to persist the change. Does WSL need to have the windows mount file in the path to do basic operations? I am always very weary of directly modifying the path and in a lot of cases there are other options that work instead of modifying the `$PATH`.

**Comment by BunNybuger** [comment]
Use `right arrow` instead of `tab`.

I had the same problem and figured out that if I do not use `tab`, it won't crash. So:

1- Press `Ctrl + R` and search.
2- Press `Ctrl + R` again if you need to find more results.
3- Then use `right arrow` to select the command you want.

**Comment by AndersHogqvist** [comment]
> Use `right arrow` instead of `tab`.
> 
> I had the same problem and figured out that if I do not use `tab`, it won't crash. So:
> 
> 1- Press `Ctrl + R` and search. 2- Press `Ctrl + R` again if you need to find more results. 3- Then use `right arrow` to select the command you want.

Thank you for sharing, works perfectly!

**Comment by Evgeny105** [comment]
> Use `right arrow` instead of `tab`.
> 
> I had the same problem and figured out that if I do not use `tab`, it won't crash. So:
> 
> 1- Press `Ctrl + R` and search. 2- Press `Ctrl + R` again if you need to find more results. 3- Then use `right arrow` to select the command you want.

Confirm the existence of the problem so far, and this is the only working solution.

**Comment by andrinr** [comment]
> Use `right arrow` instead of `tab`.
> 
> I had the same problem and figured out that if I do not use `tab`, it won't crash. So:
> 
> 1- Press `Ctrl + R` and search. 2- Press `Ctrl + R` again if you need to find more results. 3- Then use `right arrow` to select the command you want.

Thank you! Seems like this issue should be easy to fix then :)

**Comment by nevmerzhitsky** [comment]
I'm started to suffer from this issue yesterday, without any precursors.

In my case it's appears not on any search patter, but only "trunc" which produce line `truncate -s0 storage/logs/laravel.log` from my history.

```
wsl -v
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3194
```

**Comment by mateakos1** [comment]
Still happens in 2025 on Windows 11 running Ubuntu inside WSL.
Ctrl+R, type something, TAB, and the terminal freezes for about 20 seconds, then plays a sound effect and starts working again.

**Comment by murilogtoloni** [comment]
Still the same... so annoying!

**Comment by paskozdilar** [comment]
Affected by the same issue.

**Comment by gimme-control** [comment]
Same issue is there any temporary fix I accidentally keep hitting tab and its super annoying

**Comment by andyneff** [comment]
> Same issue is there any temporary fix I accidentally keep hitting tab and its super annoying

This seems to be a workaround for the issue:

```bash
export PATH=$(IFS=:; x=($PATH); for y in ${!x[@]}; do if [[ "${x[y]}" =~ /mnt/[c-z] ]]; then unset x[y]; fi; done; echo "${x[*]}")
```

But keep in mind, now nothing from the windows side is in your PATH anymore, include `wsl.exe`. This will probably not be a problem for most use cases.

**Comment by paskozdilar** [comment]
@andyneff 
Thank you!!!

Here's a slightly shorter version of that oneliner:

```bash
export PATH="$(echo "$PATH" | tr ':' '\n' | grep -v '^/mnt/[c-z]' | paste -sd: -)"
```

**Comment by andyneff** [comment]
I did a bit of digging, and I was able to determine that writing an initial word complete function can get around the issue. So I was thinking "I'd just write an initial word autocomplete function that works exactly same as the default, except not search the windows PATHs" and register it via `complete -I -F function_name`...

While I think this is a better solution, it is outside my skill set to get it to behave exactly like bash would (most difficult of all for this was tab complete on directory names which ends with a `/` and not added space ` `

**Comment by erlangen2001** [comment]
Issue still happening, please reopen it.

**Comment by AloysHF** [comment]
Issue still happening, 

```bat
PS C:\Users\jiang> wsl --version
WSL 版本: 2.6.3.0
内核版本: 6.6.87.2-1
WSLg 版本: 1.0.71
MSRDC 版本: 1.2.6353
Direct3D 版本: 1.611.1-81528511
DXCore 版本: 10.0.26100.1-240331-1435.ge-release
Windows: 10.0.26200.7623
```

**Comment by AndersHogqvist** [comment]
I tried to make the re-opening this one but it seems not to be a bug but related to the amount of entries in your $PATH (see comment on #14176).

**Comment by arlandfran** [comment]
> [@andyneff](https://github.com/andyneff) Thank you!!!
> 
> Here's a slightly shorter version of that oneliner:
> 
> export PATH="$(echo "$PATH" | tr ':' '\n' | grep -v '^/mnt/[c-z]' | paste -sd: -)"

Adding `appendWindowsPath = false` to your `/etc/wsl.conf` is another way of removing Windows from your $PATH - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings
