### ISSUE TITLE
Unable to enable WSL 2: 'WSL 2 requires an update to its kernel component' after kernel update MSI installed

### ISSUE THREAD

**Issue by moditpro365** [microsoft/WSL#5941]
# Environment
Win 10 - 10.0.19624.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
I've followed the instructions to enable WSL, VM components, reboot, run MSI. MSI installs without error, but installs quickly and without elevation prompts as mentioned in the article. Go to set WSL 2 as default and get 'WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel.'

Folowing: https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package

**WSL logs**: 

#  Expected behavior

# Actual behavior

`PS C:\> wsl --set-default-version 2
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
For information on key differences with WSL 2 please visit https://aka.ms/wsl2`

**Comment by licanhua** [comment]
most likely, the elevation prompts is blocked by [UAC](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-overview).

1. Download the kernel to a fold like c:\temp which doesn't include space
2. start cmd.exe with admin permission, and goto above folder.
3. msiexec /i "wsl_update_x64.msi

**Comment by moditpro365** [comment]
Thanks, @licanhua but I ended up wiping the OS. All is good now.
