### ISSUE TITLE
Filesystem watch functionality is broken after upgrade from WSL 1 to WSL 2

### ISSUE THREAD

**Issue by adam-arold** [microsoft/WSL#5948]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Run any Jekyll example project (like [this](https://github.com/jekyll/example)) with `bundler exec jekyll serve --watch` on WSL 1 then upgrade to WSL 2 and try it again. In the first instance file system watch will work and the contents of the site will update, when changes are made, with WSL 2 it won't.

The same happens if I use [nodemon](https://www.npmjs.com/package/nodemon) to do the same.

#  Expected behavior

I expect file system watch to work.

# Actual behavior

It doesn't work.

I don't know about the details regarding WSL, but this happens after upgrading from WSL 1 to WSL 2. It is reproducible.
#216 is related, but it is closed for some reason, although the bug persists.

**Comment by onomatopellan** [comment]
That's a known limitation of WSL2 when your code in is a /mnt/* folder. You need to move your project to the /home/user directory in order to have all the benefits of real Linux.

It's explained in the comparison page:
https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems

**Comment by adam-arold** [comment]
I'm sorry, @onomatopellan but what were you thinking? WSL 2 is practically useless for most use cases because of this issue. I had to downgrade to WSL 1 to get this functionality back. I can't move my project **into** WSL because then my IDE won't work. Who manages this project? Why did nobody think about this?

**Comment by onomatopellan** [comment]
@adam-arold I'm just a WSL user. It's normal WSL2 still doesn't support your scenario yet since it's a new technology and WSL1 is already 4 years old. Follow #4739 for more info.
