### ISSUE TITLE
windows10 安装 WSL 失败

### ISSUE THREAD

**Issue by ceerqingtingml** [microsoft/WSL#5952]
# Environment

```none
Windows build number: [run `[Microsoft Windows NT 10.0.18363.0] 
```

# Steps to reproduce

安装 Ubuntu 18.04 LTS  时，出现如下错误：
```bash
WslRegisterDistribution failed with error: 0x8007019e
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
```
原因是未启用“适用于 Linux 的 Windows 子系统”可选组件，目前有尝试两种解决方案，均无法成功。

1. 方案一：
按照官网的解决方案，输入如下指令启用“适用于 Linux 的 Windows 子系统”可选功能
以管理员身份打开 PowerShell 并运行：
```bash
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```
该指令未能执行成功，log 如下：
```bash
PS C:\WINDOWS\system32> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

部署映像服务和管理工具
版本: 10.0.18362.900

映像版本: 10.0.18363.1082


错误: 0x800f0819

功能名称 Microsoft-Windows-Subsystem-Linux 未知。
未识别出 Windows 功能名称。
请使用 /Get-Features 选项在映像中查找功能名称，然后重试该命令。

可以在 C:\WINDOWS\Logs\DISM\dism.log 上找到 DISM 日志文件
PS C:\WINDOWS\system32>
```
_dism.log 会上传至附件，麻烦分析一下是什么问题_
[dism.log](https://github.com/microsoft/WSL/files/5251169/dism.log)

2.方案二：
打开“控制面板” -> “程序和功能” -> “打开或关闭 Windows 功能”-> 选中“适用于 Linux 的 Windows 子系统”
选中后，会提示重启电脑，重启过程中，界面提示无法保存配置，恢复为之前的配置项，电脑重启成功之后，仍然提示此错误。

#  Expected behavior

成功安装 WSL

# Actual behavior

按照官方的解决方案执行后，仍提示 “0x8007019e”。

**Comment by licanhua** [comment]
Are you using the Windows 10 Home 64bit edition or Server Edition? Likely this feature is not supported in your machine.

Try if you can list Microsoft-Windows-Subsystem-Linux feature in powershell with admin permission, and here is the expected result.
```
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName *Linux*


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Disabled
```

From the log, it has problem find this feature package:
```
2020-09-20 12:55:20, Error                 DISM   DISM Package Manager: PID=13556 Feature name Microsoft-Windows-Subsystem-Linux is unknown. - CPackageManagerCLIHandler::Private_GetFeaturesFromCommandLine(hr:0x800f0819)
```

I don't know if 'Check Windows update' will fix the problem or not.

**Comment by ceerqingtingml** [comment]
@licanhua  Sorry for late reply.
Many thanks to your reply.

I am using Windows 10 Home 64bit edition.
![image](https://user-images.githubusercontent.com/19239201/95760483-ab872a80-0cdd-11eb-9b53-b01d379bfc4d.png)

And I cannnot get the expected result.
![image](https://user-images.githubusercontent.com/19239201/95760142-3ae00e00-0cdd-11eb-8ad3-2a1f072b3db0.png)

Are you sure that Windows 10 Home 64bit edition cannot support WSL feature?

**Comment by licanhua** [comment]
If it's English version, yes, it's supported because I used it at home.
But for Chinese and OEM version, I don't know
