### ISSUE TITLE
Unable to start Ubuntu 20 LTS: The specified module could not be found

### ISSUE THREAD

**Issue by barweiss** [microsoft/WSL#5954]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Your Distribution version: Ubuntu 20 LTS (I can't access WSL so I can't run the exact command, but it seems to happen in all distributions)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Run the `wsl` command

![image](https://user-images.githubusercontent.com/33583364/93710631-e7045e00-fb50-11ea-8f5c-d4c019a91e98.png)

When attempting to run using Windows Terminal there's an error code as well:

![image](https://user-images.githubusercontent.com/33583364/93710646-01d6d280-fb51-11ea-953d-b7bd1b95b3d1.png)

**WSL logs**: 

#  Expected behavior

WSL will start the Ubuntu 20 LTS distribution successfully.

# Actual behavior

An error prevents WSL from starting correctly.
I have Docker installed which also does not start up correctly.

**Comment by WSLUser** [comment]
Uninstall Docker and do a re-install of VMM feature. See if WSL2 works afterwards. Then re-install Docker, be sure to NOT choose the WSL2 backend. If this works, then try using the WSL2 backend. If this fails, file logs for both Docker and WSL. https://docs.microsoft.com/en-us/windows/wsl/troubleshooting

**Comment by barweiss** [comment]
Re-installing WSL 2 worked, thanks!

**Comment by lacriment** [comment]
In electronic devices restarting things usually solves the unexpected bugs.
This solved for me after trying many things:
Windows Features on & off -> Disable Windows Subsystem for Linux -> Reboot -> Re-Enable Windows Subsystem for Linux
