### ISSUE TITLE
Rules for hostname

### ISSUE THREAD

**Issue by nancym** [Microsoft/WSL#596]
My hostname is something like `LAPTOP-STUVWXYZ`. I'm pretty sure I need to change it because when I run `sudo apt-get update` or `sudo apt-get upgrade`, I get this message:

```
sudo: unable to resolve host LAPTOP-STUVWXYZ
```

Also, I installed the news (NNTP) reader `nn` and when I run it, I get this message:

```
hostname=LAPTOP-STUVWXYZ, You need a fully qualified domain name
```

I understand from issue #125 that I need to change the hostname from Windows, but before I do I'm wondering what, if any, rules there are for a hostname that will work for Windows, Bash, nn, Crashplan, and whatever tools I use now (and in the future :smile_cat:). While searching the net for answers to this question, I read that a nix hostname can't contain an underscore. I don't know if that's true, but Im guessing there are some restrictions like that.

I'd appreciate any hostname tips. Thanks!

**Comment by benhillis** [comment]
Could you try something for me?  Could you remove your /etc/hosts file and restart bash.exe and see if the error goes away?  This will regenerate the /etc/hosts file with an entry that contains your machine name.

`sudo rm /etc/hosts`

**Comment by nancym** [comment]
Wow, that worked to solve the `sudo apt-get update` and `sudo apt-get upgrade` "unable to resove host" messages! 👏 🎆 Thank you!!

(I'll try to solve the nn problem some other way. ~25 years ago I was an nn expert, but in those days I only ran it while ssh'd or telnetted into a remote nix server and never had to think about or configure the hostname. Tips are welcome about this nn issue.)

**Comment by NotMyself** [comment]
Just ran into this issue myself, but solved it a different way:

1. Make sure you know what your hostname is by running `cat /etc/hostname`.
2. Open the hosts file in VIM `sudo vim /etc/hosts`.
3. Navigate to an empty row with your arrow keys and hit the `i` key to enter insert mode.
4. Type the localhost address followed by a space and your hostname exactly as it appears in the hostname file.
5. Hit the `Esc` key to switch back to normal mode.
6. Type `:wq` followed by `enter`, to write your changes and quit VIM.
7. Close bash and reopen it just for good measure.

![selfie-0](http://i.imgur.com/m0VO4cA.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by tgillot** [comment]
Per https://github.com/Microsoft/BashOnWindows/issues/125 you need change change the hostname in Windows. I tried changing it in Ubuntu and it does not persist.

**Comment by therealkenc** [comment]
WSL's `/init` has populated `/etc/hosts` for a while now. Calling this fixed on that basis. Changing the hosts in WSL won't change it in Windows. That's by-design for the time being; you are spiritually in a container and might have multiple WSL instances each with their own hostname.
