### ISSUE TITLE
Connecting to local website from another computer on network

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [microsoft/WSL#5960]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.488]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020 
On Running wsl -l -v on powershell, it says version is 2
```
I want to access a website hosted on my wsl. I am using nginx server. For testing purpose I was trying to navigate to the default nginx landing page.

# Steps to reproduce
1. Enable the network as home network in my firewall settings.
2. Run ipconfig on command prompt.
3. Navigate to the ip address given under IPv4 address from another computer on network. 

**WSL logs**: 

#  Expected behavior

The Nginx landing page will load

# Actual behavior

ERR_CONNECTION_REFUSED error occurs.
I tried the same steps with docker and navigated to their ports and that's working.

**Comment by ad-on-is** [comment]
This is a known issue. If you want to achieve that, you'll have to install Docker Desktop, enable it for WSL2 and run your services (nginx, whatever) inside a Docker Container.
