### ISSUE TITLE
Why there is no centos

### ISSUE THREAD

**Issue by lbhnrg2021** [microsoft/WSL#5962]
Why is there no centos subsystem

**Comment by anwesh-b** [comment]
Download the zipped Centos file from [here](https://github.com/yuk7/CentWSL/releases)
Unzip the file and run CentOS.exe
This will complete the installation.
Again, run the CentOS.exe and you are ready to go

**Comment by anwesh-b** [comment]
Download the zipped Centos file from [here](https://github.com/yuk7/CentWSL/releases)
Unzip the file and run `CentOS.exe`
This will complete the installation.
Again, run the `CentOS.exe` and you are ready to go

**Comment by lbhnrg2021** [comment]
> Download the zipped Centos file from [here](https://github.com/yuk7/CentWSL/releases)
> Unzip the file and run `CentOS.exe`
> This will complete the installation.
> Again, run the `CentOS.exe` and you are ready to go

This is third-party and there is a problem,  docker cannot start
