### ISSUE TITLE
After changing window 10 username my linux distribution setup is lost 

### ISSUE THREAD

**Issue by hanzlahabib** [microsoft/WSL#5963]
I have installed Wsl2 and Linux distribution successfully
I was having issue with window username, I just changed my window username, after doing so when I started window terminal, my Linux distribution was not shown there
[![enter image description here][1]][1]

when I separately run ubuntu from start menu, instead of loading old setup it initialized new setup and asked for username and password to get ready

I lost my previous setup of all installed distributions (ubuntu, kali)

is there any configuration where I can tell wsl2 my updated user 'name' so that instead of initializing setup from start it load stuff from there

tried google and official documentation for wsl2 and Linux distributors, nothing helped. 
 
Thanks in Advance 

  [1]: https://i.stack.imgur.com/YUGzf.png

**Comment by DHowett** [comment]
Your Windows username is not ever expected to change, and a great many things can break when it does.

**Comment by WSLUser** [comment]
It probably would help if everything was tied to the SID instead of username unless that also changes (though I believe it shouldn't based on experience with AD).

**Comment by therealkenc** [comment]
@hanzlahabib 

What does `wsl.exe -l -v` return from the commandline after you've changed your username.

**Comment by warpdesign** [comment]
> Your Windows username is not ever expected to change, and a great many things can break when it does.

Why is it possible to modify it if:
- it's not supposed to happen
- bad things may happen if you do so

**Comment by DHowett** [comment]
Sorry, I conflated the user's name with the user's profile path. The first can change, but the second ends up hardcoded in a great number of places across the system (mostly in the registry.)
