### ISSUE TITLE
Disk space can' be free !

### ISSUE THREAD

**Issue by triump2020** [microsoft/WSL#5965]
Hi  !   
   After  i  deleted the big file in WSL2  ,  the free space of C-disk  in Win10  had no change !        
  
   My  C-disk in Win10  is  now in danger of data corruption ,  how  deal with it ? Thanks !
      

![image](https://user-images.githubusercontent.com/63033222/93882814-50cc6580-fd13-11ea-8a30-1cf6ad999751.png)

![image](https://user-images.githubusercontent.com/63033222/93882924-6fcaf780-fd13-11ea-84f1-4fac234ad6cd.png)

![image](https://user-images.githubusercontent.com/63033222/93882973-7eb1aa00-fd13-11ea-9ca8-35c99dafd9bb.png)

**Comment by onomatopellan** [comment]
That's because WSL2 uses a VHDX that needs to be shrunk manually.
See https://github.com/microsoft/WSL/issues/4699#issuecomment-635332770
