### ISSUE TITLE
Error: 0x80040202 on trying to convert a distro from wsl1 to wsl2..

### ISSUE THREAD

**Issue by CosmicSnow** [microsoft/WSL#5970]
# Environment

Windows Pro, version 2004, Build 19041.508

# Steps to reproduce

**WSL logs**: https://aka.ms/AA9q3d4

#  Expected behavior

The distro should convert from wsl v1 to v2.

# Actual behavior

It fails to convert to wsl v2, I can't open distro directly through terminal too, neither install it directly using `wsl --set-default-version 2`
It returns me Error: 0x80040202

I want to use it with docker..
I tried to find a solution everywhere, 
Maybe I'll have to install windows.. Again...

**Comment by licanhua** [comment]
The error is raised by Hyper-V `VmComEvents.h; 930`, and it requires Hyper-V to continue the investigation.

**Comment by CosmicSnow** [comment]
strange, I solved the problem disabling wsl and virtual machines on windows features.
Uninstalling all my distros, and wsl.

Then reinstalled everything, but rebooting after every install.
then set wsl default version as 2, and installed the ubuntu distro.
now it's working again, didn't have to enable Hyper-v
