### ISSUE TITLE
WSL2 no network over USB, works over wifi

### ISSUE THREAD

**Issue by inquirnigmind** [microsoft/WSL#5972]
# Environment

Windows 10 version 2004, build 1904.508
Ubuntu 18.04 on WSL 2

# Steps to reproduce

I am using a Verizon MiFi hotspot tethered via USB (Ethernet adapter Remote NDIS based Internet Sharing Device) and when using I cannot get networking to work in WSL2.  When pinging google, the IP address is resolved as 172.217.6.100 and there is 100% packet loss.  I also cannot ping 8.8.8.4 or the gateway of the mifi (192.168.1.1).  I can ping my host OS at 192.168.1.4.  When I un-tether the MiFi hotspot and connect to it using WiFi then networking in WSL2 works.

I uninstalled my third party firewall as well as disabled the Windows firewall and after a reboot the issue still persists.  Per other suggestions, I also uninstalled the Cisco Anyconnect VPN and another commercial VPN, reboot and still having the issue.

I am running VMWare 15 and there are two VMware Network Adapters under my Network Connections.

Under the Hyper-V Manager my Virtual Switch setting for WSL is "Internal network".  I tried to follow the suggestion from issue #4731 and set the connection to the above NDIS device but then my host OS networking stopped working and I had to remove/re-add the network adapter.

I also tried adding 8.8.8.4 to /etc/resolv.conf (instead of 172.17.144.1) but then when I ping google I get the error "Temporary failure in name resolution."

#  Expected behavior

Working network when using tethered network interface.

# Actual behavior

I cannot run apt-get update or ping from WSL2 while using a USB tethered network connection.  Either 100% packet loss or temporary failure in name resolution but networking works if I switch to WiFi.

**Comment by therealkenc** [comment]
This one is not materially different than /dupe #5313 insofar as actionable information. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item over in that issue.

**Comment by dmarquezbh** [comment]
In my case I switched from public to private network over USB Ethernet (from IPhone), and it worked. Hope it helps someone else.

**Comment by rf-correa** [comment]
I'm having this problem as of Jan/2022. Apparently is a problem wwith WSL2. WSL1 works fine.
