### ISSUE TITLE
kali.exe returns WslRegisterDistribution failed with error: 0x80070005

### ISSUE THREAD

**Issue by Fagbemi-Jeremiah** [microsoft/WSL#5973]
Sorry about the long explanation, i just want to know where i went wrong
i wanted to download kali on windows but microsoft store had some major bugs and after so many times of running different commands and doing others stuff i decide to go to [https://store.rg-adguard.net/](https://store.rg-adguard.net/) which allowed me to download kali without using Microsoft store after i downloaded it from the site i tried to run the .Appxbundle but the install button turned grey and didn't do anything, so i cancelled it a typed `Add-AppxPackage -Path "C:\Users\user\Downloads\KaliLinux.54290C8133FEE_1.5.0.0_neutral_~_ey8k8hqnwqnmg.AppxBundle"` in powershell(Adminstrator) and then it installed but now there is a new problem, if i open the app from start menu, it waits for some time the it brings a popup saying `The operation returned becuase the timeout period expired`, then if i open kali.exe from "C:\Program Files\WindowsApps\KaliLinux.54290C8133FEE_1.5.0.0_x64__ey8k8hqnwqnmg" it opens cmd and shows 
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
```
And after pressing any key it closes the window, an if i open cmd and type `kali` it returns `The system cannot execute the specified program.` , i have checked every where but nothing seems to be helping

**Comment by zyazhb** [comment]
same in 20221
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800700b7
The distribution installation has become corrupted.
Please select Reset from App Settings or uninstall and reinstall the app.
Error: 0x800700b7 ????????????????

Press any key to continue...
```

**Comment by onomatopellan** [comment]
I don't think that method is officially supported. Uninstall the App and try again with the [Windows Server way](https://docs.microsoft.com/en-us/windows/wsl/install-manual).

**Comment by Fagbemi-Jeremiah** [comment]
@onomatopellan i have done that and it didn't fix anything, i have also restarted Lxssmanager service, i don't think my method is wrong as it is directly equivalent to downloading from store

**Comment by therealkenc** [comment]
@zyazhb  your error code is not the same.

/dupe #4004
