### ISSUE TITLE
wsl2 error

### ISSUE THREAD

**Issue by sparrow84001** [microsoft/WSL#5975]
wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
**my system was enabled wsl and virtualization . Bios set up also enable but see that error. I cant figure out this problem pls help me  **  
[
![wsl2](https://user-images.githubusercontent.com/37022413/94060143-10e3ac00-fe01-11ea-8a75-ac7f6225e88e.PNG)
](![wsl1](https://user-images.githubusercontent.com/37022413/94060008-e42f9480-fe00-11ea-8f00-5839ad6162ff.PNG))

**Comment by benhillis** [comment]
Can you provide the output of msinfo32.exe?

**Comment by sparrow84001** [comment]
OS Name	Microsoft Windows 10 Pro for Workstations
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	SPARROW
System Manufacturer	HP
System Model	HP ZBook Studio x360 G5
System Type	x64-based PC
System SKU	5UL54PA#ACJ
Processor	Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz, 2904 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	HP Q71 Ver. 01.12.00, 29-07-2020
SMBIOS Version	3.1
Embedded Controller Version	22.72
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	844F
BaseBoard Version	KBC Version 16.48.00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.488"
User Name	SPARROW\Sparrow
Time Zone	India Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.8 GB
Available Physical Memory	8.83 GB
Total Virtual Memory	18.8 GB
Available Virtual Memory	10.4 GB
Page File Space	3.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Secure Memory Overwrite, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: Un-allowed DMA capable bus/device(s) detected
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by licanhua** [comment]
Have you reboot the machine after you enabled virtual machine platform?

Can you check the virtualization flag in `task manager`? `Enabled` is expected
![image](https://user-images.githubusercontent.com/6290692/94081880-82e1d400-fdb4-11ea-9940-c5292daa5828.png)

**Comment by sparrow84001** [comment]
![Capture](https://user-images.githubusercontent.com/37022413/94110638-977ba600-fe60-11ea-9c58-550a2dd3613f.PNG)
yes

**Comment by sparrow84001** [comment]
all things are good to go 
I am 1st disable virtualization restart and after some time  reenable and restart then all things okkk
