### ISSUE TITLE
Windows listen wsl2 port only ipv6，can not use ipv4 for access 

### ISSUE THREAD

**Issue by darth-j** [microsoft/WSL#5978]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

![image](https://user-images.githubusercontent.com/25424615/94101637-d4489c80-fe62-11ea-9715-8c9e6aa225c2.png)

I have apache2 server and iperf server in wsl2,but i can not use ipv4 address access . use netstat -ano,i find host windows listen wsl2's port is ipv6,not ipv4

**Comment by cljk** [comment]
Have the same issue. was wondering, why i CAN access my service on WSL2 via "localhost:8025" but NOT via "127.0.0.1:8025"

Solution is that "localhost" resolves to `::1` - and access to `[::1]:8025` works...

**Comment by Fagbemi-Jeremiah** [comment]
please check out [https://github.com/microsoft/WSL/issues/5973](https://github.com/microsoft/WSL/issues/5973)
