### ISSUE TITLE
Issues with SSH and git in WSL2

### ISSUE THREAD

**Issue by mikerod-sd** [microsoft/WSL#5979]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu Release:        18.04
WSL2
I have docker desktop version 2.3.0.4(46911) installed 
I also have Pulse Secure installed
The only AV I have installed is Windows Defender
```

# Steps to reproduce
I recently updated to WSL2 to be able to work with Docker linux containers natively.
Previously in WSL1 I was able to run the commands
`git pull ` and I would pull from our repository. 
Now I get the following:
```
git pull
ssh: connect to host github.xx.xxxxxxxx.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
SSH does not work either:
```
ssh mrod@internalhost.com
ssh: connect to host internalhost.com port 22: Connection timed out
```

Strace
https://gist.github.com/mikerod-sd/3785e97a645db0e65a887a4ca7b81814

I also noticed that DNS fails and I have to manually update my /etc/hosts file for resolution to work.

I have redacted internal hostnames.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by Fagbemi-Jeremiah** [comment]
please check out [https://github.com/microsoft/WSL/issues/5973](https://github.com/microsoft/WSL/issues/5973)

**Comment by mikerod-sd** [comment]
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

I can't get to the feedback forums via the mechanism listed as this is a work laptop. Is there a way an alternative way to get logs?

3rd party networking software:
Pulse secure VPN
F5 VPN

**Comment by therealkenc** [comment]
> Is there a way an alternative way to get logs?

Not that I'm aware. 

Thank-you for the VPN details, it is appreciated and helps by itself.

Subscribe /dupe #5068. Add a like over there.
