### ISSUE TITLE
WSL is closing instantly after opening it

### ISSUE THREAD

**Issue by andbaraks** [microsoft/WSL#5981]
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows Version 2004 (OS Build 19041.508)

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Ubuntu Release:        20.04

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
I can't open WSL but this is from Ubuntu:
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
I tried to install WSL 2 update but with or without that, the issue is still happening.

# Steps to reproduce
I used method 1 within the following document: https://itsfoss.com/install-bash-on-windows/
However, I don't think this is reproducible. I already used that procedure on my previous laptop and had no issue before. Also my colleagues used that procedure and everything is fine for them.

#  Expected behavior
Open WSL and work as expected, not to close exactly the moment after I open it.

# Actual behavior
Just the moment I open WSL, it is instantly closing. When I open Ubuntu, I have no issue.

Please let me know if other information is needed. Thank you for your help!

**Comment by Fagbemi-Jeremiah** [comment]
please check out [https://github.com/microsoft/WSL/issues/5973](https://github.com/microsoft/WSL/issues/5973)

**Comment by licanhua** [comment]
Please [collect logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and submit them by Feedback Hub.

**Comment by andbaraks** [comment]
@licanhua Done. Thank you for checking this!

**Comment by craigloewen-msft** [comment]
@andbaraks can you please provide a link to the logs that you submitted here? I took a look through Feedback Hub but wasn't able to find the logs you provided. Thanks!

**Comment by licanhua** [comment]
I think it's https://aka.ms/AA9twv0

**Comment by andbaraks** [comment]
Hello! Is there any update for this, please? Thank you!
