### ISSUE TITLE
WSL2 can't start: There are no more endpoints available from the endpoint mapper.  [process exited with code 4294967295]

### ISSUE THREAD

**Issue by 8549** [microsoft/WSL#5982]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20221.1000]
Your Distribution version: All distros are affected
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Attempt to launch distros either from Windows Terminal or from the Program Menu icons, or via command line.

**WSL logs**:  I can't provide logs because i can't use the "Recreate my problem" feature: clicking on "Start Recording" doesn't do anything.

#  Expected behavior

WSL can start my distros reliably

# Actual behavior

WSL doesn't start any distro, and after some minutes of the cursor blinking throws the error:
`There are no more endpoints available from the endpoint mapper.  [process exited with code 4294967295]`
`wsl` command in powershell/cmd doesn't respond, either.

WSL stopped working on 14/09/2020; i can't remember any updates breaking it. I just started windows and it was not working anymore. WSL worked this morning right after a cold boot after installing the latest windows build, i had to restart my PC and it went back to non working status. I can't find the KB4571756 update in my update history so i guess that's not my problem.

Occasionally, i am instead greeted with this error (my default profile is Ubuntu 20.04):
![image](https://user-images.githubusercontent.com/15671077/94135926-6ef5ab00-fe64-11ea-93e4-4ab8f2c3f064.png)

**Comment by 8549** [comment]
Found #5845 which is a duplicate. Uninstalling VirtualBox solved my issue. That's crazy though

**Comment by SkippityPaps** [comment]
Had this error happen before. Was able to resolve it. It's back for no reason as I was using ubuntu just fine 10 hours prior and now I'm getting this idiotic endpoint mapping error. 
Getting real irritated with tools breaking for no damn reason.
