### ISSUE TITLE
WSL2 is running but terminal hangs when connet WSL

### ISSUE THREAD

**Issue by FavonianKong** [microsoft/WSL#5983]
# Environment

```none
Windows build number: 19041.264 
Your Distribution version: Centos7
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Before run the `wsl`，the` wsl -l -v ` shows:
```
  NAME       STATE          VERSION
* CentOS7   Stopped         2
```
After run the `wsl` on PowerShell or use the terminal to launch the Centos7, It show nothing but just a cursor. Also, the `wsl -l -v` shows:
```
  NAME       STATE          VERSION
* CentOS7    Running         2
```
It seems that the Centos has been activated，but the terminal show nothing. No matter what I type, it's only printed on the screen and without any response.

![image](https://user-images.githubusercontent.com/40446561/94135961-c57bdd00-fe96-11ea-8955-af61ef631be7.png)

**WSL logs**:  I cant get any logs, if there is something I missed, plz tell me and I will upload it.

#  Expected behavior
Connet the Centos7 successfully and Linux commands can be used properly.

# Actual behavior
Nothing reponse :(!!

**Comment by onomatopellan** [comment]
Does Ubuntu WSL2 distro work? If it does you can do `sudo dmesg -w` there, let the window open and try running again Centos7. You should see some error appear in the dmesg window.

**Comment by Fagbemi-Jeremiah** [comment]
please check out [https://github.com/microsoft/WSL/issues/5973](https://github.com/microsoft/WSL/issues/5973)

**Comment by therealkenc** [comment]
> please check out #5973

Please stop. Not one of these issues cites a 0x80070005 error.

**Comment by FavonianKong** [comment]
> Does Ubuntu WSL2 distro work? If it does you can do `sudo dmesg -w` there, let the window open and try running again Centos7. You should see some error appear in the dmesg window.

Sadly not,  neither Centos nor Ubuntu can be launched successful，I guess the problem is caused by loading configuration files, eg: `~/.bashrc`.  Is there any way to view the configuration file of the WSL system from the Windows?

**Comment by onomatopellan** [comment]
@FavonianKong You can try launching with the root user with `wsl.exe -d CentOS7 -u root`

**Comment by FavonianKong** [comment]
> @FavonianKong You can try launching with the root user with `wsl.exe -d CentOS7 -u root`
> 
> If it's a configuration problem then you should be able to access files via windows explorer. Open Run (win+R) and type `\\wsl$\` to see the CentOS7 files.

Thanks for your advice，I failed to slove the problem in the end.  I find it so strange why the terminal never responds, even though the Centos7 is already running.

**Comment by onomatopellan** [comment]
@FavonianKong If it happens again please collect some WSL Logs following these steps: 
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs
