### ISSUE TITLE
Update commands not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Aman-rishu** [microsoft/WSL#5988]
![3C50A3705CBB4B4CBEF6A90F30CC8700](https://user-images.githubusercontent.com/67704051/94289824-efa4cc00-ff76-11ea-8603-b72d4d2bf772.png)

Please fix my issue!
sudo apt-get update
Throws error
    Temporary failure resolving 'security.ubuntu.com'

....

**Comment by Biswa96** [comment]
Please fill the issue template that you have just deleted.

**Comment by craigloewen-msft** [comment]
I'm closing this issue out since the issue template was deleted. We need the information there (like your build number, logs, etc.) to help diagnose your issue. Please resubmit an issue with the template filled out, and then we can take a look!

**Comment by odyright** [comment]
SAME Issue.... @Aman-rishu 've you got any solution?

**Comment by Aman-rishu** [comment]
Ya.
Still facing the same problem.

...
