### ISSUE TITLE
bash for WSL constantly running and using CPU even when WSL is not open

### ISSUE THREAD

**Issue by nickdrones** [microsoft/WSL#5989]
I do not have any WSL windows running on my laptop but in Task Manager, this program called "bash" (located in the WSL directory) is ALWAYS running and my battery life is 1 hour if I'm lucky.
![wsl](https://user-images.githubusercontent.com/16674954/94316305-b7d35f80-ff49-11ea-8cba-c691f1a0768c.PNG)
I right click and try to end the task but that does absolutely nothing and it also stays open if I try to kill it from the command line. Any suggestions?

**Comment by therealkenc** [comment]
Please post the output of `[Environment]::OSVersion` from a powershell prompt, or `ver` from a cmd prompt.

Does `bash` appear if you reboot? Assume not, but it is worth asking, and the reboot will get us grounded. After reboot, type `wsl.exe -l -v` and post that output. Finally, start your WSL instance with `wsl.exe` from PS or cmd prompt. You should not have a `bash` running.

**Comment by nickdrones** [comment]
Hmmm ok figured it out. I have the new WIndows terminal app. If I open the WSL shell through there, then it keeps running after I close it. If I run it from wsl.exe, then it closes when I close it. Strange, but it's ok now
