### ISSUE TITLE
Localhost can't connect to mysql

### ISSUE THREAD

**Issue by zhaozhiguang** [microsoft/WSL#5990]
# Environment
Windows build number:  Microsoft Windows [版本 10.0.19041.508] 
Your Distribution version: ubuntu Release:  20.04
the issue is on WSL2

# Steps to reproduce
wsl2 can not localhost connect mysql in docker ,but ip connect mysql in docker is ok
![image](https://user-images.githubusercontent.com/16306620/94327977-873f0480-ffe1-11ea-98b5-486a251273fe.png)
![image](https://user-images.githubusercontent.com/16306620/94327989-94f48a00-ffe1-11ea-9a3d-c9abe0548217.png)

#  Expected behavior
I want localhost to be able to connect to mysql

# Actual behavior
Localhost can't connect to mysql, but IP can

**Comment by therealkenc** [comment]
> Windows build number: Microsoft Windows [版本 10.0.19041.508]

On 19041 this is /dupe #5298. See also #4851.

![image](https://user-images.githubusercontent.com/7049700/94351415-1a416400-000d-11eb-997b-7dcdf0704d7a.png)

Configure mysql to bind on `0.0.0.0`.

![image](https://user-images.githubusercontent.com/7049700/94351771-149a4d00-0012-11eb-9c5f-f1015f731afa.png)
