### ISSUE TITLE
Please support drives mounted to a folder

### ISSUE THREAD

**Issue by alamp1360** [microsoft/WSL#5993]
Hi!

I have mounted my data disk as a folder to c:\data using the procedure described here:

https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive

When trying to access this folder from within WSL by changing directory to /mnt/host/c/data, i get an input/output error.

When i do an "ls" in /mnt/host/c, the data is shown as a symlink, i guess (it's light blue), but when i do a "ls -l", it says: cannot read link: I/O error.

It would be really helpful if you could support such type of "windows symlinks" in WSL, too...

Greetings
Andreas

**Comment by pcbeard** [comment]
I just noticed this too. The workaround is to also give the drive its own letter. Grudgingly I assigned Z to this folder mounted SSD. Please fix. Ideally, give us a way to mount drives wherever we want according to fstab.

**Comment by Leffe108** [comment]
I run into this too.

I have all my code projects sitting on a separate disk mounted into my user folder in Windows. Due to this bug, I cannot access it from wsl2 to for example use php-cli installed via apt in debian to execute a script than uses extra modules that is much easier to install in debian than on windows.

It is on a separate disk because my C:\ become full and had to by a separate disk and move some files to it and the easiest way to do than without breaking paths is to mount it into a folder.

**Comment by Biswa96** [comment]
If it is a separate disk it will appear mounted with that drive letter in /mnt, just like /mnt/c for C:\ drive.

**Comment by Leffe108** [comment]
> 
> 
> If it is a separate disk it will appear mounted with that drive letter in /mnt, just like /mnt/c for C:\ drive.

Unfortunately that is only the case for disks that are mounted as a drive letter.

![bild](https://user-images.githubusercontent.com/4630670/131241121-c40448f5-d640-46bf-be2c-9e7ec842b64a.png)

![bild](https://user-images.githubusercontent.com/4630670/131241083-fe655450-0dae-43c4-9bf3-838367c19eb7.png)

But my intel SSD disk mounted to C:\Users\Leif\Programmering folder is not listed in /mnt.` And accessing it via its path gives the input/output error as mentioned in OP

![bild](https://user-images.githubusercontent.com/4630670/131241170-e5ec4acb-0227-4dd8-becb-6520c72b440e.png)

I'm not quite sure where the disk management tool has gone in Windows 10, but here is a screenshot of the defrag tool that lists the folder mounted disk:
![bild](https://user-images.githubusercontent.com/4630670/131241247-0cf0cdd8-d377-4dea-844b-bf310006a88f.png)

**Comment by Biswa96** [comment]
It is possible to make a little program to do that. But I am not sure if it will actually work 🤓 The idea is like this - Mount the path with HcsModifyComputeSystem function from Windows side using plan9 server. Then mount it in WSL side with that as plan9 client.

**Comment by Leffe108** [comment]
I found a workaround:
* Right click on start menu
* Select disk management
* Right click on the disk and select to update mount point
* In this window it is possible to add a second mount point and make it a drive letter. So the drive retains it folder mount but additionally mount to a drive letter. Eg. P:\
* Reboot computer (so WSL auto-mount the new drive letter)
* In WSL now `ls /mnt/` will show the new drive letter.

Side note: If you use Windows in English the disk management tool can also be found in the search bar by searching for words like partion and possible also disk. But in Windows for Swedish that is simply not possible. You have to know to right click on start menu or know its name to use in the run dialog. :-/
