### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80040154

### ISSUE THREAD

**Issue by sc-idevops** [microsoft/WSL#5994]
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

# Steps to reproduce
1. Attempt to install Ubuntu from the store and run.
2. Unable to get any further because of the following errors:
WslRegisterDistribution failed with error: 0x80040154
Error: 0x80040154 Class not registered

Note: This subsystem was working fine before I upgraded to Windows 10 v2004

**WSL logs**: 
https://aka.ms/AA9rr3c
#  Expected behavior
Ubuntu should install itself and allow me to use WSL

# Actual behavior
I'm blocked by an error that seems to indicate that WSL isn't installed when it is.

**Comment by licanhua** [comment]
From the the trace, it has problem to initialize the mother board when creating virtual machine, and error is raised by Hyper-V. You'll probably get better feedback in the [microsoft community](https://answers.microsoft.com/en-us/)
Sometime disable/re-enable virtual machine platform may help to resolve this kind of problem.

**Comment by Biswa96** [comment]
Alternatively, use `wsl.exe --import` command to install/register a GNU/Linux distribution in WSL. If it works... remove Windows Store 🤣

**Comment by steveokard** [comment]
> From the the trace, it has problem to initialize the mother board when creating virtual machine, and error is raised by Hyper-V. You'll probably get better feedback in the [microsoft community](https://answers.microsoft.com/en-us/)
> Sometime disable/re-enable virtual machine platform may help to resolve this kind of problem.

I appreciate your insight, and it confirms my suspicions that there's something wrong with this motherboard I have. I've been trying to track down a problem with it not being able to run RAM at the correct XMP speeds. I guess this is just another malfunction to add to the list for my RMA.
