### ISSUE TITLE
[WSL2] WSL2 program can not make use of Intel Turbo boost

### ISSUE THREAD

**Issue by GitPaean** [microsoft/WSL#5995]
Hi, 

The Windows version I am using is Microsoft Windows [Version 10.0.19041.508],  and Ubunntu 20.04 LTS through WSL2. 

My CPU is Intel i7-8665U, which has 1.9GHz base frequency, Max Turbo Frequency 4.80 GHz and Configurable TDP-up Frequency 2.10 GHz. 

When I am working with Ubuntu through WSL2, no matter what types of program I am trying to run, the cpu frequency will stay at around 2.1GHz (or slightly above 2GHz).   While programs under Windows can easy make the CPU frequency to be above 4GHz.  Working at around 2.1GHz makes the laptop really not efficient in term of performance. 

Not sure it is a design feature for WSL2 or I can configure it to make it be able to boost CPU frequency to make it run faster?

BTW, when I try `cat /proc/cpuinfo` , it always show the frequency at 2.1GHz. I guess it is not a real-time frequency. 

Thank you.

**Comment by 12101111** [comment]
![image](https://user-images.githubusercontent.com/8438475/94412479-6a0a6180-01ac-11eb-9751-5e2a4567a63c.png)

WSL2 is based on Hyper-V, and Hyper-V don't report real frequency to guest OS. `/proc/cpuinfo` just print the information of virtual CPU created by Hyper-V, not the real one.

**Comment by GitPaean** [comment]
> WSL2 is based on Hyper-V, and Hyper-V don't report real frequency to guest OS. /proc/cpuinfo just print the information of virtual CPU created by Hyper-V, not the real one.

@12101111 , thanks for your update. It looks like your CPU can be boosted to a proper speed. 

When I run some computationally intense code, the cpu frequency from the task manager might jump to about 3.1 GHz for very short period, but after a few seconds, it will become the following, 
![2](https://user-images.githubusercontent.com/6847941/94609866-b08cb880-029f-11eb-9100-728365b32791.PNG)

Maybe it is because the CPU temperature is getting high and CPU goes back to the base frequency to cool down.  Maybe I should try to test the same machine under pure Linux environment to compare to make sure the issue is a valid issue.

**Comment by GitPaean** [comment]
More update, installing a Ubuntu besides the windows, set the frequency governor to be `performance`, the frequency looks more normal related to turbo boost, 

```
Every 2,0s: grep "cpu MHz" /proc/cpuinfo                                                                                                                                    paean: Wed Sep 30 14:09:00 2020

cpu MHz         : 4395.462
cpu MHz         : 4375.016
cpu MHz         : 4544.184
cpu MHz         : 4209.109
cpu MHz         : 4426.009
cpu MHz         : 4506.732
cpu MHz         : 4474.810
cpu MHz         : 4531.145

```

**Comment by Trass3r** [comment]
The question is how to set the frequency governor in WSL2?

**Comment by Trass3r** [comment]
> When I run some computationally intense code under Ubuntu through WSL2, the cpu frequency from the task manager might jump to about 3.1 GHz for very short period, but after a few seconds, it will become the following,

Same here but it settles at 2.56 GHz.

**Comment by Trass3r** [comment]
> WSL2 is based on Hyper-V, and Hyper-V don't report real frequency to guest OS. /proc/cpuinfo just print the information of virtual CPU created by Hyper-V, not the real one.

Makes sense. But doesn't allow the cpu freq governors to do their job.

```ini
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_ATTR_SET=y
CONFIG_CPU_FREQ_GOV_COMMON=y
CONFIG_CPU_FREQ_STAT=y
CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_USERSPACE=y
CONFIG_CPU_FREQ_GOV_ONDEMAND=y
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
CONFIG_X86_INTEL_PSTATE=y
```

**Comment by harshavmb** [comment]
Hello,

Any tweaks/configs found in the meantime? 

My WSL isn't using Turbo boost. Happy with 2.1GHz base frequency wherein the CPU manufacturer (Intel) says it can be overclocked up to 4.8GHz.
