### ISSUE TITLE
[WSL2] mount "The disk is in use or locked by another process" - workaround 

### ISSUE THREAD

**Issue by nikitalita** [microsoft/WSL#5997]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20221.1000]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```
# Issue

I am on a dual boot set-up with EFI enabled. I have two disks, one with my Ubuntu 20.04 install, another with my Windows install. I have my grub bootloader on the Ubuntu disk, set up to either boot me into Ubuntu or Windows.

On Windows, attempting to mount my boot disk onto my WSL 2 instance fails:

```
wsl --mount \\.\PHYSICALDRIVE2 --bare
The disk is in use or locked by another process
```

Reading [the article about mounting disks into WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) reveals why: 

```
At this time, only entire disks can be attached to WSL 2, meaning that it's not possible to attach only a partition. Concretely, this means that it's not possible to use wsl --mount to read a partition on the boot device, because that device can't be detached from Windows.
```

Because I was chainloading the Windows boot loader with grub, Windows considered my Ubuntu disk a boot disk, and locked the drive. 

#  Workaround

In your motherboard settings, change the system to boot from the windows bootloader instead of the linux bootloader. Then, it won't chainload from the linux drive, and Windows won't consider it a boot disk.

**Comment by noriakia** [comment]
I get the same message in my environment.

`PS C:\Users\xxxxxx> wsl --mount \\.\PHYSICALDRIVE0 --partition 2
プロセスはファイルにアクセスできません。別のプロセスが使用中です。`
It is displayed in a Japanese message, but has the same meaning as below.
The disk is in use or locked by another process

Windows build number: 
`Microsoft Windows [Version 10.0.20226.1000]`

**Comment by bubnikv** [comment]
I am sorry, but that the current limitation of not being able to mount a Linux partition from the Windows disk disables mounting of Linux partitions for the majority of us.

**Comment by nikitalita** [comment]
You can, but you can't mount the whole drive with the `--bare` option.

**Comment by bubnikv** [comment]
>> At this time, only entire disks can be attached to WSL 2, meaning that it's not possible to attach only a partition. Concretely, this means that it's not possible to use wsl --mount to read a partition on the boot device, because that device can't be detached from Windows.
>
>You can, but you can't mount the whole drive with the --bare option.

I don't understand the statement above then. The way I understand the limitation is that I cannot mount a linux partition to WSL2 if the linux partition resides on the same disk as my Windows partition with efi.

**Comment by nikitalita** [comment]
That's not what I had originally labeled the issue as, someone changed it.

**Comment by eromoe** [comment]
Same error

```
C:\Users\ufo>bash
另一个程序正在使用此文件，进程无法访问。
```

**Comment by noriakia** [comment]
> I get the same message in my environment.
> 
> ```
> PS C:\Users\xxxxxx> wsl --mount \\.\PHYSICALDRIVE0 --partition 2
> プロセスはファイルにアクセスできません。別のプロセスが使用中です。
> ```
> 
> It is displayed in a Japanese message, but has the same meaning as below.
> `The disk is in use or locked by another process`
> 
> Windows build number:
> `Microsoft Windows [Version 10.0.20226.1000]`

It hasn't been fixed even after 20231.

**Comment by smohring** [comment]
Windows/Ubuntu 20.10 in the same disk, getting the same error during mount:

`Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.`

**Comment by Cr1ft** [comment]
My external hard drive has three partitions: one ext4 and two NTFS.

I tried to mount the ext4 partition on the external hard disk, but it shows an error that another program is using this file and the process cannot access it.

![image](https://user-images.githubusercontent.com/43020689/95697307-e9019e80-0c70-11eb-93eb-2072105c7182.png)

**Comment by bubnikv** [comment]
It looks like the underlying HyperV virtualizer only supports attaching
whole disks. If the disk is used by the Windows system, you can neither
attach the whole disk, nor a single partition.

**Comment by Cr1ft** [comment]
Is there a way to disable the hard drive in Windows?Then mount the hard drive as a whole to WSL2.

**Comment by OneBlue** [comment]
Let me try to bring some clarity on this.

WSL --mount always detaches the disk from Windows, and then attaches it as a block device to WSL2.
That's the reason why wsl --mount fails if the disk is in use, because we can't detach it from Windows.

What actually happens when `wsl --mount X --partition Y` is:

* Disk X is unmounted & detached from Windows
* Disk X is attached to WSL2
* Partition Y is mounted in WSL2

So even if  `--partition` is passed to `wsl --mount`, the whole disk needs to be available so it can be attached to WSL2. 

In @nikitalita's scenario, I imagine that the EFI partition is on `PHYSICALDRIVE2`, and it's of course in use by Windows, so it's not possible to detach it if this disk was used as the boot disk. The suggested workaround of using a different boot disk makes perfect sense since it means that Windows won't use the EFI partition in `PHYSICALDRIVE2` and so the disk is not in use when `wsl --mount` runs.

I'll close this issue now. Let me know if you have any other questions !

**Comment by Amondale** [comment]
@OneBlue think you are on the right track. However, how to stop Windows from continuously attempting to mount an NTFS or FAT32 partition? Hopefully I won't have to resort to reg hacks with PHYSICALDISK settings, as I recently had to do with SDXC cards with ext4 partitions that keep coming up "format me so windows can use me" or some such nonsense.

**Comment by TheAlphaReturns** [comment]
Having this same problem, except my windows boot is on another drive.
i can also use `Get-Process * | Select-Object Path | findstr D:\` and confirm that there are no processes running on D:\ (aka \\.\physicaldrive0 partition 1)

how would you unmount this drive then?

**Comment by jivanf** [comment]
> Having this same problem, except my windows boot is on another drive. i can also use `Get-Process * | Select-Object Path | findstr D:\` and confirm that there are no processes running on D:\ (aka \.\physicaldrive0 partition 1)
> 
> how would you unmount this drive then?

What I did to fix this was go to Disk Management, right-click the disk and set it to offline to unmount it. Then I was able to mount it on WSL.

**Comment by YoungElPaso** [comment]
@jivanf Can confirm that also worked for me  - had to use diskpart in powershell however, but same thing - set offline, then mount.

**Comment by rraayyii** [comment]
The disks are now automatically mounted in the /mnt folder under wsl. 
![image](https://user-images.githubusercontent.com/63856439/197436503-25f6b6d7-94be-4c6d-a5ba-8d5456177711.png)

**Comment by xTye** [comment]
> @jivanf Can confirm that also worked for me - had to use diskpart in powershell however, but same thing - set offline, then mount.

https://answers.microsoft.com/en-us/windows/forum/all/online-offline-a-disk-in-disk-management-w10-home/c4c472a8-7fa1-41a5-a9ad-68434b64dc35

Here's the link on how to do it through powershell

**Comment by MordaNakmor** [comment]
EHM.. had the same problem and the solution is "quite simple".. before you even try to use power shell as admin to mount the disk, you "simply" have to put it offline in disk manager.. those Carrotsoft idiots either forgot to notify users about it or made it out of sheer evil joy for those who would try to do it by the book.. one stupid detail managed to put countless people to lay off of it..

**Comment by obfuscated-loop** [comment]
> EHM.. had the same problem and the solution is "quite simple".. before you even try to use power shell as admin to mount the disk, you "simply" have to put it offline in disk manager.. those Carrotsoft idiots either forgot to notify users about it or made it out of sheer evil joy for those who would try to do it by the book.. one stupid detail managed to put countless people to lay off of it..

Tried your solution, unfortunately even this didn't work and I got this MessageBox: `Disk attributes may not be changed on the current system disk or BIOS disk 0`.

It is not the current system disk, neither is it using slot 0! This is ridiculous

**Comment by moezakura** [comment]
> > EHM.. had the same problem and the solution is "quite simple".. before you even try to use power shell as admin to mount the disk, you "simply" have to put it offline in disk manager.. those Carrotsoft idiots either forgot to notify users about it or made it out of sheer evil joy for those who would try to do it by the book.. one stupid detail managed to put countless people to lay off of it..
> 
> Tried your solution, unfortunately even this didn't work and I got this MessageBox: `Disk attributes may not be changed on the current system disk or BIOS disk 0`.
> 
> It is not the current system disk, neither is it using slot 0! This is ridiculous

Isn't the boot loader in the disk you are trying to mount?
I moved my boot loader to another disk and that solved the problem.

**Comment by SpiderUnderUrBed** [comment]
I also have this issue, is windows working on a solution? with me its because my efi partition is on the disk im trying to mount, atleast i want a solution to that, or if its some random process using it, i would like to know how to debug it

**Comment by 901238746** [comment]
Due to how it unmounts the whole disk and not the partition while its mounting it to WSL it fails since critical windows system files are using the C drive.

Also trying to make it off line fails with "Disk attributes may not be changed on the boot disk."

**Comment by pkit** [comment]
This bullshit is why WSL2 is never used. Simple things don't work.
How would I know why windows decided to use an EFI partition on different drive when it was instructed to use a full bare disk instead at the installation time?
And now what? Reinstall windows?
