### ISSUE TITLE
wsl2 network didn't work if host ethernet working with vlan 

### ISSUE THREAD

**Issue by comicfans** [microsoft/WSL#6001]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.19041.508]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

if host network works, wsl2 network should work out of box

# Actual behavior

if my host network working at vlan mode (host ethernet has vlan id configured), host network everything works(no matter ping/tcp/udp),  but wsl2 can not reach any network except host peer (host <-> wsl2  can communicate with each other, but wsl2 can not reach upstream router, or anyother node out of host), 

then I reconfigure my host network to non-vlan mode (host ethernet has no vlan id), host network everything works, and wsl2 network also worked.

**Comment by acid2000** [comment]
Yes this! This has taken three hours of my life!

I’m assuming what is happening here is that WSL2 network adapter is being bonded to my untagged interface which has no gateway meaning my packets go nowhere.

Is this fixable by setting a vlan ID in the guest OS?

**Comment by ReyB59** [comment]
Hello, any update ?

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows if applicable.
