### ISSUE TITLE
Port Forwarding still not working correctly...

### ISSUE THREAD

**Issue by elucidsoft** [microsoft/WSL#6003]
https://github.com/microsoft/WSL/issues/4636 is not fixed, so this is an issue to re-open it.  It's easily reproducible, I just had it happen last night on the latest version of Windows Stable, all patches applied.  You should not be closing issues, that are not fixed!

Windows Version: 10.0.19041

Brand new install of Windows, less than 3 days old.

**Comment by Some1OnLine** [comment]
So I noticed that for some reason or another my WSL2/Debian distro is now failing to work with the typical port forwarding powershell script. It was working fine for the alst several months but for some reason has stopped. The power shell script creates the firewall rules but I am not able to see/access any of the forwarded ports from outside of the wsl host.

**Comment by craigloewen-msft** [comment]
I put a comment in #4636 to help address this! We close the issue because it is fixed in the latest builds, but your feedback is valid we need a better way to communicate that though that's it's only fixed in insiders, I'll start thinking on a good way to communicate this
