### ISSUE TITLE
USB Support??

### ISSUE THREAD

**Issue by AntonisGardi** [microsoft/WSL#6005]
Will ever wsl have usb support for flash drives or smartphones,iphones ??

**Comment by Some1OnLine** [comment]
do the drives auto mount the USB drives paths ie \\wsl$\<USB DRIVE Letter> when you start/boot the distro?

**Comment by craigloewen-msft** [comment]
We are aware of this feature request and are looking into solutions for it! We are tracking this request at this thread: https://github.com/microsoft/WSL/issues/2195
