### ISSUE TITLE
Chrome on WSL2 doesn't support webgl2

### ISSUE THREAD

**Issue by bluesfdw** [microsoft/WSL#6007]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
 Distribution version:  Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
1.  Install latest Google Chrome for linux (85.0.4183.121)
2. Navigate to url: https://get.webgl.org/webgl2/
3. it shows google chrome doesn't support webgl2

 a linux physical machine (Ubuntu 18.04) doesn't have this issue.

#  Expected behavior

Google Chrome should support WebGL2

# Actual behavior

Webgl2 is not available in wsl2 Google Chrome browser

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/94732885-bfb14c00-031b-11eb-967f-73433c84084f.png)
