### ISSUE TITLE
The remote procedure call failed fixed in the latest Windows Insider Update

### ISSUE THREAD

**Issue by theoware** [microsoft/WSL#6008]
We fixed an issue affecting Windows Subsystem for Linux 2 distros where users can receive the error: “The remote procedure call failed” on startup. See this GitHub issue for more details.
Source: https://www.tenforums.com/windows-10-news/165527-windows-10-insider-preview-build-20226-1000-rs_prerelease-sept-30-a.html

**Comment by HoFamilyMaker** [comment]
upgrade to build 20226 execute wsl --mount 'The remote procedure call failed'

![image](https://user-images.githubusercontent.com/46410370/94805610-3b47f180-041f-11eb-905a-4f4798715a45.png)
