### ISSUE TITLE
PHP local server connection failed on WSL2

### ISSUE THREAD

**Issue by kaalede** [microsoft/WSL#6010]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.508]
Your Distribution version: Ubuntu-20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard
```

# Steps to reproduce
```
php -S localhost:8000
```
![image](https://user-images.githubusercontent.com/51249939/94730673-dd0a0880-0363-11eb-843d-57a5ee9339ab.png)

#  Expected behavior

I expect to have a fully functionnal PHP local server.

# Actual behavior

The connexion between WSL2 and Firefox seems not to works. 

Have a nice evening.

**Comment by therealkenc** [comment]
Cannot reproduce on recent insiders. Try `php -S 0.0.0.0:8000`, see if that helps.

![image](https://user-images.githubusercontent.com/7049700/94734062-7feb6400-031d-11eb-85cb-ccb907a4d262.png)

**Comment by stloc** [comment]
same (recent) problem as @kaalede 
not possible to run localhost program 

Microsoft Windows [version 10.0.19041.508]
![image](https://user-images.githubusercontent.com/4832070/94899945-7b958700-0494-11eb-8b75-484be017c09c.png)

**Comment by stloc** [comment]
I have reboot my PC and now it's work... probbly program conflict

**Comment by kaalede** [comment]
I reinstall Ubuntu (just Ubuntu, not Ubuntu-20.04) and now it's work... Weird issue.
