### ISSUE TITLE
WSL2 cannot connect to the internet after upgrading from WSL1 (TRIED EVERYTHING!)

### ISSUE THREAD

**Issue by DramaDogg** [microsoft/WSL#6016]
Hi,

I'm currently running Windows 10 _(version 2004 build 19041.508)_. WSL2 just doesn't connect to the network. I have tried three different distributions (Debian, Ubuntu 20.04 LTS & openSUSE Leap 15.2) and neither of them could connect to the internet by running either sudo apt upgrade or sudo zypper up (in case of opensuse).

The following is shown when i run **`sudo apt update`** on **_debian_**: 

`Err:1 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://ftp.debian.org/debian buster-backports InRelease
  Temporary failure resolving 'ftp.debian.org'
Err:4 http://deb.debian.org/debian buster-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://ftp.debian.org/debian/dists/buster-backports/InRelease  Temporary failure resolving 'ftp.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.`

In response to this, I looked up for forums on such and did all the following (doing neither helped):

 --> Editing resolv.conf to point to a functioning nameserver for the duration of the session. (As mentioned in  https://github.com/microsoft/WSL/issues/5256#issuecomment-666545999)

Also, `sudo ping 8.8.8.8` returned the following error: `connect: Network is unreachable`

--> I had protonVPN installed in my pc, i went ahead and uninstalled it (including the network drivers it came with)

--> Uninstalled all Hyper-V components, uninstalled all TAP based networking by uninstalling VPN clients i have installed (as mentioned in https://github.com/microsoft/WSL/issues/5256#issuecomment-667751572)

--> Completely disabled Windows Firewall & Windows Defender Firewall

Doing all of them got me nowehere, whatsoever! WSL1 was doing great, but i need the features of WSL2 to let it interact with windows better than wsl1.
Looking through the issues in this github repo, a lot if has to do with WSL2's network connectivity. A kind request to the developers to fix the general network issues in WSL2 asap.

Any beginner-friendly help to this issue would be great! :)

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by allexlima** [comment]
same problem here =(
I'm trying this -> https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063

**Comment by DramaDogg** [comment]
> same problem here =(
> I'm trying this -> https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063
Let me know if it worked...I nearly never update to preview builds but i might this time if it has the issue fixed.

**Comment by DramaDogg** [comment]
> same problem here =(
> I'm trying this -> https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063

Let me know if it worked...I nearly never update to preview builds but i might this time if it has the issue fixed.

**Comment by agualdron** [comment]
You can also check if the **wsl** is connected to the local network, for example, ping to the IPV4 assigned to the windows host, and vice-versa.

You may already try this, but still, I'll leave what worked for me. 

I'm using Ubuntu 20.04, and `apt update` is working fine. 

Try to follow all the steps in order.

Edit the `/etc/resolv.conf` file with the following:
```bash
#/etc/resolv.conf
nameserver 8.8.8.8
```
To hold the file and avoid **wsl** to replace it every restart, edit the file `/etc/wsl.conf`:
```bash
#/etc/wsl.conf
[network]
generateResolvConf = false
```
Then in a windows command prompt execute this, before a new **wsl** session:
```
wsl --shutdown
```
Taken from [this comment](https://github.com/microsoft/WSL/issues/1908#issuecomment-698310174), and [this other comment](https://github.com/microsoft/WSL/issues/5256#issuecomment-666545999)

**Comment by allexlima** [comment]
> > same problem here =(
> > I'm trying this -> https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063
> 
> Let me know if it worked...I nearly never update to preview builds but i might this time if it has the issue fixed.

After upgrade my Windows version, it worked fine. I hope it can work for you as well =)

**Comment by DramaDogg** [comment]
> 
> 
> You can also check if the **wsl** is connected to the local network, for example, ping to the IPV4 assigned to the windows host, and vice-versa.
> 
> You may already try this, but still, I'll leave what worked for me.
> 
> I'm using Ubuntu 20.04, and `apt update` is working fine.
> 
> Try to follow all the steps in order.
> 
> Edit the `/etc/resolv.conf` file with the following:
> 
> ```shell
> #/etc/resolv.conf
> nameserver 8.8.8.8
> ```
> 
> To hold the file and avoid **wsl** to replace it every restart, edit the file `/etc/wsl.conf`:
> 
> ```shell
> #/etc/wsl.conf
> [network]
> generateResolvConf = false
> ```
> 
> Then in a windows command prompt execute this, before a new **wsl** session:
> 
> ```
> wsl --shutdown
> ```
> 
> Taken from [this comment](https://github.com/microsoft/WSL/issues/1908#issuecomment-698310174), and [this other comment](https://github.com/microsoft/WSL/issues/5256#issuecomment-666545999)

Tried this once again 
& no luck :(
![image](https://user-images.githubusercontent.com/63922865/95014234-30bf6f00-064e-11eb-9a39-1d606230bc24.png)

**Comment by DramaDogg** [comment]
> 
> 
> > > same problem here =(
> > > I'm trying this -> https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063
> > 
> > 
> > Let me know if it worked...I nearly never update to preview builds but i might this time if it has the issue fixed.
> 
> After upgrade my Windows version, it worked fine. I hope it can work for you as well =)

Strange..i did update to the preview build and no luck :(

**Comment by DramaDogg** [comment]
> 
> 
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

Here: https://aka.ms/AA9v0ml
I couldn't add any attachments since I've tinkered and debloated my PC, & disabled Diagnostics.
I don't have any third-party networking software installed.

**Comment by zhangshengsheng** [comment]
same problem

**Comment by zergvszerg** [comment]
same problem here.
I've tried to ping from wsl2 to windows host and from windows host to wsl2, and failed both times.

**Comment by piouson** [comment]
been pulling my hair out on this one..
- ping works from wsl, local `192.168.41.241` and remote `8.8.8.8, etc` nameservers
- dns works from wsl
- Windows `v1909` build `18363`
- Ubuntu 20.04.1 LTS
```sh
# ipconfig
Ethernet adapter vEthernet (WSL):
   IPv4 Address. . . . . . . . . . . : 192.168.41.241
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
```
```sh
# cat /etc/resolv.conf
nameserver 192.168.41.241
# ip route
default via 192.168.41.241 dev eth0
192.168.41.240/28 dev eth0 proto kernel scope link src 192.168.41.252
```
```sh
# sudo apt update
Err:1 https://packages.microsoft.com/repos/azure-cli focal InRelease
  Could not connect to packages.microsoft.com:443 (13.80.99.124), connection timed out
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable)
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable)
Err:5 http://security.ubuntu.com/ubuntu focal-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out
```

**Comment by Nevrmnd** [comment]
Had same issue and tried every solution I found, including the resolv.conf one, and nothing worked until I tried this:
https://github.com/microsoft/WSL/issues/4731#issuecomment-701134259

Now it works like a charm. Maybe there should be a way for Windows check for that folder during WSL 2 install if it is absolutely necessary for connectivity.

**Comment by DramaDogg** [comment]
> Had same issue and tried every solution I found, including the resolv.conf one, and nothing worked until I tried this:
> [#4731 (comment)](https://github.com/microsoft/WSL/issues/4731#issuecomment-701134259)
> 
> Now it works perfectly. Maybe there should be a way for Windows check for that folder during WSL 2 install if it is absolutely necessary for connectivity.

THIS WORKED!! FINALLY I'VE BEEN TRYING TO MAKE THIS WORK FOR ALMOST A MONTH!!
_BOY if there was a way i could give you a million dollars!!_

This worked for me:
- Uninstalled all distro(s)
- Created Temp folder in  C:\Users[username]\AppData\Local  _(I created the folder for all the users in my pc, just in case)_
- Reinstalled Ubuntu from Microsoft store
- Voila, `sudo apt update` worked right out of the box! Didn't have do any of the resolv.conf editing at all, the fresh install of ubuntu connected to the internet with no issues!

**Comment by Thribs** [comment]
> 
> 
> It's important to end current sessions with this commande
> 
> `wsl --shutdown`

This did the trick for me. Thank you

**Comment by Kratorator** [comment]
For me, it was the firewall, my bad. Long before I started using WSL, I thought I was being smart when I changed the public profile inbound connections rule from "Block (default)" to "Block all connections". After all, that computer never leaves my home and is always set to private profile. I changed the public profile rule back to the default, and "sudo apt update" etc. worked immediately.

 Why on earth are they using the public profile for WSL?

**Comment by Anamon** [comment]
> Then in a windows command prompt execute this, before a new **wsl** session:
> 
> ```
> wsl --shutdown
> ```

Your solution worked for me, but only if I **do not** shutdown WSL. If `generateResolvConf` is true, it will overwrite it with the wrong nameserver once WSL boots up again. If `generateResolvConf` is false, it will simply delete the `resolv.conf` file, regardless of its contents, so DNS resolution still doesn't work.

I think the correct way to keep WSL from breaking DNS resolution on every boot, is to make the fixed `resolv.conf` file read-only.
