### ISSUE TITLE
can't stop the process Vmmem

### ISSUE THREAD

**Issue by bady0059** [microsoft/WSL#6025]
I have wsl2 on my pc. Every time I open any Linux distribution I have a prosses called "vmmem" that takes 5 GB of my ram.
After I close my Linux that process keeps running. Before that I had wsl1 and it worked prefect. 

I tried to stop the process with task manager but it is not possible.
 please help.

**Comment by 0xbadfca11** [comment]
``wsl --shutdown`` terminate vm immediately.

vmIdleTimeout can adjust the time to terminate automatically, but it does not terminate immediately.
https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20190
