### ISSUE TITLE
C1 control characters allowed in Linux but not in Win32 are not escaped by drvfs

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/WSL#6027]
Using WSL1 on Windows 10 build 19042.546.

When modifying files names through Win32 API MoveFileExW, C0 control characters and \\/:*?"<>| are refused, and C1 control characters are refused on NTFS volumes (but for some reasons accepted on exFAT volumes, and probably FATx).

When modifying drvfs files through WSL, the C0 and \\:*?"<>| are +U+F000-escaped (not / as it is reserved in Linux) to allow characters supported in Linux but not on Win32.
However, WSL allows C1 control characters, the following can inject VT colors into a filename on an NTFS volume
`touch 'Test'$'\302\233''91mRed'`

![image](https://user-images.githubusercontent.com/25664275/95017501-ec39d080-0659-11eb-8865-3020846c04ba.png)

The folder as seen by PowerShell and CMD shows the processed VT sequence:
![image](https://user-images.githubusercontent.com/25664275/95017508-f2c84800-0659-11eb-8809-b380c0586bd6.png)
![image](https://user-images.githubusercontent.com/25664275/95017515-fcea4680-0659-11eb-8a92-443556f9fb46.png)

I think C1 control characters should also be +U+F000-escaped at the WSL layer to avoid injecting those on the Win32 side.

**Comment by 0xbadfca11** [comment]
```cmd
chcp 65001   # needed to clip.exe know that the input is UTF-8
wsl.exe echo -n 'Test'$'\302\233''91mRed' | clip.exe
md test
ren test <Ctrl+V here>
dir
```
It works.
WSL is used in the process, but it can be made without using WSL.

**Comment by PhMajerus** [comment]
@0xbadfca11 
Thanks for trying to replicate it. I tried again and indeed it works with MoveFileExW... not sure what I did wrong previously that returned an error.
