### ISSUE TITLE
clock_getres returns higher resolution than is actually available

### ISSUE THREAD

**Issue by mulderr** [microsoft/WSL#6029]
# Environment

```none
Windows build number: 10.0.19041.508
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

The `clock_getres(2)` function "finds the resolution (precision) of the specified clock". A minimal C program to get the precision of `CLOCK_REALTIME`:

```c
#include "stdio.h"
#include "stdlib.h"
#include "time.h"

int main()
{
  struct timespec ts;

  if (clock_getres(CLOCK_REALTIME, &ts) == -1) {
    perror("clock_getres");
    exit(EXIT_FAILURE);
  }

  printf("resolution: %lds %ldns\n", ts.tv_sec, ts_tv_nsec);

  return 0;
}
```

1. `sudo apt install gcc`
2. `cat > test.c` (paste the above program)
3. `gcc test.c`
4. `./a.out`

Running the program (4) produces:
```
resolution: 0s 1ns
```

**WSL logs**: 
![image](https://user-images.githubusercontent.com/5698461/95026717-9bdf6480-0693-11eb-8f9a-62db2ac58865.png)

When I click Share feedback it takes me back to the very beginning instead of giving a link. There is a link to the github issue in the description if that helps at all?

#  Expected behavior

Since `clock_gettime(CLOCK_REALTIME, ...)` on WSL2 only ever returns multiples of 100ns then it stands to reason that the resolution of `CLOCK_REALTIME` reported by `clock_getres` should be 100ns. The program should be printing:

```
resolution: 0s 100ns
```

# Actual behavior

`clock_getres(CLOCK_REALTIME, ...)` returns 1ns.

This seems incorrect and makes the user think they have 1ns resolution clock when in reality they do not.

**Comment by therealkenc** [comment]
Academically tag hypervisor-platform.

**Comment by Tritlo** [comment]
Having the same issue!
