### ISSUE TITLE
wsl --import <distro> <dir> <file> --version 2 fails: The parameter is incorrect

### ISSUE THREAD

**Issue by rjmholt** [microsoft/WSL#6031]
From https://github.com/docker/for-win/issues/8722. Rather than trying to use WSL dircectly, I hit this issue trying to start Docker.

# Environment

```none
> systeminfo | select -first 2 -skip 2
OS Name:                   Microsoft Windows 10 Enterprise Insider Preview
OS Version:                10.0.20230 N/A Build 20230

> wsl lsb_release -r
Release:        16.04

> wsl cat /proc/version
Linux version 4.4.0-20230-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1001-Microsoft Wed Oct 01 18:44:00 PST 2020
```

# Steps to reproduce

A simple reproduction of the issue is this:

```powershell
wsl --export Ubuntu backup.tar
mkdir backup-distro
wsl --import backup backup-distro backup.tar --version 2     # Issues the error 'The parameter is incorrect'
```

As I hit it, the issue causes Docker startup to fail, as described in https://github.com/docker/for-win/issues/8722.

Happy to provide more information as needed.

**WSL logs**: https://aka.ms/AA9ve8z

#  Expected behavior

(I'm not actually sure, but I assume it creates a new copy distro that Docker can use)

# Actual behavior

```
> wsl --import backup backup-distro backup.tar --version 2
The parameter is incorrect.
```

**Comment by licanhua** [comment]
@benhillis This error is raised from Hyper-V when creating network. From the logs, there is a HNS crash with 'One or more arguments are invalid'. Because the request parameter is removed from the logs and I can only see the response, so I don't know if wsl passed wrong parameter to Hyper-V or problem of hyper-v itself.

**Comment by therealkenc** [comment]
#4800 #5293

**Comment by benhillis** [comment]
@therealkenc - deleted your comment because this is a new issue, unrelated to the below.

**Comment by rhuijben** [comment]
I can also reproduce this behavior if I turn on 
![image](https://user-images.githubusercontent.com/2271549/121345982-d043a880-c925-11eb-9c65-a835213f6f14.png) in the current development preview of Windows. Once I turn it off things work as expected.

**Comment by rjmholt** [comment]
> I can also reproduce this behavior if I enable Windows Terminal as default terminal.

Ah interesting. I was almost certainly using Windows Terminal (though not as a configured default) for this
