### ISSUE TITLE
Can't connect to MySQL on Windows from WSL2

### ISSUE THREAD

**Issue by falke2** [microsoft/WSL#6034]
#5665 Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
Install MariaDB 10.4 server on Windows and try to connect to it from WSL

#  Expected behavior

connection

# Actual behavior
i'm running `mysql` on WSL and getting error `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
`ifconfig` gives me following:
```bash
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.229.92  netmask 255.255.240.0  broadcast 172.19.239.255
        inet6 fe80::215:5dff:fe43:8c13  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:43:8c:13  txqueuelen 1000  (Ethernet)
        RX packets 1138  bytes 369761 (369.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 174  bytes 17653 (17.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 34  bytes 2108 (2.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34  bytes 2108 (2.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
`/etc/resolv.conf` contents are `nameserver 172.19.224.1`
`mysql -h 172.19.224.1` gives me `ERROR 2003 (HY000): Can't connect to MySQL server on '172.19.224.1' (110)`

`ipconfig` on host windows gives me following:
```Настройка протокола IP для Windows


Адаптер Ethernet vEthernet (Default Switch):

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::100a:6830:2cec:21b9%25
   IPv4-адрес. . . . . . . . . . . . : 172.25.128.1
   Маска подсети . . . . . . . . . . : 255.255.240.0
   Основной шлюз. . . . . . . . . :

Адаптер Ethernet vEthernet (WSL):

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::7c88:c141:ea7f:9471%32
   IPv4-адрес. . . . . . . . . . . . : 172.19.224.1
   Маска подсети . . . . . . . . . . : 255.255.240.0
   Основной шлюз. . . . . . . . . :

Адаптер Ethernet Ethernet:

   DNS-суффикс подключения . . . . . :
   IPv6-адрес. . . . . . . . . . . . : 2002:5f4f:601c:1:f464:dfc1:ee37:3c9a
   Временный IPv6-адрес. . . . . . . : 2002:5f4f:601c:1:35eb:a2a3:5feb:5ccc
   Локальный IPv6-адрес канала . . . : fe80::f464:dfc1:ee37:3c9a%3
   IPv4-адрес. . . . . . . . . . . . : 192.168.0.2
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . : fe80::b295:75ff:fe00:acfb%3
                                       192.168.0.1

Адаптер Ethernet Сетевое подключение Bluetooth:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :
```

**Comment by therealkenc** [comment]
What is the output of `netstat.exe /an | grep 3306`?

Should look like:

![image](https://user-images.githubusercontent.com/7049700/95166206-4b830800-0762-11eb-931e-ed2974f3197c.png)

**Comment by falke2** [comment]
@therealkenc 
![image](https://user-images.githubusercontent.com/1539181/95175084-9ed97280-07c3-11eb-8ca9-4551c85c316d.png)

**Comment by falke2** [comment]
I was trying to connect to MariaDB server set up with OpenServer bundle.
I stopped MariaDB from OpenServer, reinstalled MariaDB from official site and it works for me with error:
![image](https://user-images.githubusercontent.com/1539181/95188313-e3b9d500-07d4-11eb-94cd-323ee4ffb3ac.png)
but looks like it's MariaDB misconfiguration. The problem was MariaDB not set up as a service as i think.

**Comment by falke2** [comment]
Allowed connections from subnet:
```mysql
GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.0.%' IDENTIFIED BY 'my-new-password' WITH GRANT OPTION;
```
and it's ok with connection:
![image](https://user-images.githubusercontent.com/1539181/95192369-c556d800-07da-11eb-8ee1-18d65c9bbb98.png)

192.168.0.2 is Windows local IP
