### ISSUE TITLE
Catastrophic error 0x800ffff

### ISSUE THREAD

**Issue by Gurkirat810** [microsoft/WSL#6036]
Whenever I try to enable windows subsystem Linux in windows features and click ok it shows catastrophic error 0x8000ffff. And not just with windows subsystem Linux I am unable to change any feature every time I get this error again and again. Please help.

Deployment Image Servicing and Management tool
Version: 10.0.20175.1000

Image Version: 10.0.20175.1000

Enabling feature(s)
[==========================100.0%==========================]

Error: 0x8000ffff

DISM failed. No operation was performed.
For more information, review the log file.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

**Comment by benhillis** [comment]
Can you please share that dism.log file mentioned above?

**Comment by Bobbbay** [comment]
+1 Still relevant. But, I don't get a nice error message:

```
PS > wsl
Catastrophic failure
PS >
```

**Comment by Bobbbay** [comment]
Just checked - I *do* have a dism.log file, though:

[dism.log](https://github.com/microsoft/WSL/files/6358175/dism.log)

**Comment by Bobbbay** [comment]
Potentially relevant: #5092. This is the error code I personally receive. Will test and confirm if [this](https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141) is a solution once I get to my laptop.

**Comment by Mulliken** [comment]
> Potentially relevant: #5092. This is the error code I personally receive. Will test and confirm if [this](https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141) is a solution once I get to my laptop.
> 
> UPDATE: Seems like that worked for me! I got some warnings, along the lines of "Something is wrong at /nix/store/...", but those are in my (NixOS WSL) Nix Store which I can reproduce. Cheers!

Hi Bobbbay. I got the same error (Catastrophic failure). What did you do to make WSL work? There are multiple solutions in issue #5092 and I would like to know which one works for you.

**Comment by Bobbbay** [comment]
> Hi Bobbbay. I got the same error (Catastrophic failure). What did you do to make WSL work? There are multiple solutions in issue #5092 and I would like to know which one works for you.

Hey, this was quite a while ago so I don't recall, but I assume it was the comment linked under the word "this" in my quote i.e. [this](https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141).

**Comment by jtcarden0001** [comment]
after trying every solution I could find, uninstalling docker desktop cleared the following error for me:

{
PS C:\Users\administrator> wsl
Catastrophic failure
Error code: Wsl/Service/CreateInstance/0x8000ffff
}

Issue is gone after docker desktop reinstall.

**Comment by BeamerSGB** [comment]
Just happened to me as well,  The machine is brand new.  I've had it for 3 days with an OEM windows Home install.
![image](https://user-images.githubusercontent.com/47667092/206488231-6e99e77c-6ece-4f6c-a683-e5250426e295.png)

**Comment by achaora** [comment]
I ran into similar issues and a manual setup resolved it: https://learn.microsoft.com/en-us/windows/wsl/install-manual

**Comment by V19Torrent** [comment]
> Potentially relevant: #5092. This is the error code I personally receive. Will test and confirm if [this](https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141) is a solution once I get to my laptop.
> 
> UPDATE: Seems like that worked for me! I got some warnings, along the lines of "Something is wrong at /nix/store/...", but those are in my (NixOS WSL) Nix Store which I can reproduce. Cheers!

That link worked for me as well!
