### ISSUE TITLE
WslRegisterDistribution failed with error: 0x800706d9

### ISSUE THREAD

**Issue by jeffreyulatan** [microsoft/WSL#6037]
Hey there, I'm bumping this up as I was able to reproduce the exact problem on my end.

Error:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706d9
Error: 0x800706d9 There are no more endpoints available from the endpoint mapper.

Press any key to continue...

Microsoft Windows 10 Enterprise
10.0.19041 Build 19041

Steps I've done to replicate the error:

    Virtual Machine Platform Enabled via Control Panel
    Windows Subsystem for Linux Enabled via Control Panel
    Installed WSL2 MSI Update from https://aka.ms/wsl2kernel
    Set WSL to WSL2 via Powershell wsl --set-default-version 2
    V-TD Enabled via Bios
    Distro Ubuntu 20.04 LTS via Microsoft Store

Solutions I've tried

via Powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux.
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
wsl --set-default-version 2

If anyone has any suggestions feel free to reply!

**Comment by licanhua** [comment]
Have you tried to start service ICS（Internet Connection Sharing)?
You may [collect wsl log](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by jeffreyulatan** [comment]
> 
> 
> Have you tried to start service ICS（Internet Connection Sharing)?
> You may [collect wsl log](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and I can take a initial investigation.

Yes I've tried starting ICS however it always fails to start. 

![ICS](https://user-images.githubusercontent.com/37856239/95274041-4a221000-0834-11eb-871a-818ac637d41a.PNG)

I've also tried
**netcfg –u vms_pp** 

```
Trying to uninstall vms_pp ...

... failed. Error code: 0x80071779.
```
**Get-HNSNetwork | Remove-HNSNetwork**

I've also used the Windows automatic troubleshooter
_https://docs.microsoft.com/en-us/troubleshoot/windows-client/virtualization/cannot-create-hyper-v-virtual-switch_

I also edited the bootup bcd to ensure the hypervisorplatform is started. 

I can't seem to get it working!

**Comment by AdrianMichigan** [comment]
> Hey there, I'm bumping this up as I was able to reproduce the exact problem on my end.
> 
> Error:
> 
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x800706d9
> Error: 0x800706d9 There are no more endpoints available from the endpoint mapper.
> 
> Press any key to continue...
> 
> Microsoft Windows 10 Enterprise
> 10.0.19041 Build 19041
> 
> Steps I've done to replicate the error:
> 
>     Virtual Machine Platform Enabled via Control Panel
>     Windows Subsystem for Linux Enabled via Control Panel
>     Installed WSL2 MSI Update from https://aka.ms/wsl2kernel
>     Set WSL to WSL2 via Powershell wsl --set-default-version 2
>     V-TD Enabled via Bios
>     Distro Ubuntu 20.04 LTS via Microsoft Store
> 
> Solutions I've tried
> 
> via Powershell
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux.
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> wsl --set-default-version 2
> 
> If anyone has any suggestions feel free to reply!

**Comment by AdrianMichigan** [comment]
6

**Comment by benyaminl** [comment]
@jeffreyulatan have you try to in-place upgrade? If not then try it first, it could probably fix many error like missing registry or missing wsl2 file that lead to this error.

**Comment by qnikil7** [comment]
Facing the same issue with wsl2 while installing Ubuntu 20.04.
Windows version 1909, OS build 18363.1916.

Able to install Ubuntu 20.04, when the version is changed to wsl1.

**Comment by OneTuskedMario** [comment]
Same issue here, I also seem not able to start the ICS server giving me the same error message "Access is denied"
