### ISSUE TITLE
Could not resolve proxy 

### ISSUE THREAD

**Issue by karasjoh000** [microsoft/WSL#6039]
# Environment

```shell
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

```shell
# myproxy.com:port is a filler but on wsl2 machine, it has a legit proxy that works on other Linux machines  
[Tue Oct 06 | 09:15 AM] (Projects) $ sudo curl -x "$http_proxy" www.google.com
curl: (5) Could not resolve proxy: myproxy.com
```

#  Expected behavior

Should work fine as previously with the wsl1 version

# Actual behavior
failing to resolve proxy

**Comment by karasjoh000** [comment]
Proxy works on version 1 `wsl --set-version Ubuntu 1` .

**Comment by Forbu** [comment]
thanks @karasjoh000 changing wsl version (2 => 1) works for me

**Comment by MasterSkepticista** [comment]
Waiting for WSL2 proxy fix. Is there yet?

**Comment by karasjoh000** [comment]
similar to #7224

**Comment by karasjoh000** [comment]
workaround https://gist.github.com/pyther/b7c03579a5ea55fe431561b502ec1ba8
