### ISSUE TITLE
WSL2 + DockerDesktop doesn't work - Remote procedure call failed.

### ISSUE THREAD

**Issue by ArthurDanjou** [microsoft/WSL#6041]
# Environment
Microsoft Windows [version 10.0.20215.1000]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: 2

# Steps to reproduce
Install WSL 2 with Ubuntu 20.04. 
Since the last update offered by Windows Insider, neither wsl 2 nor docker starts. Bash.exe doesn't work too.
Before the update, everything worked.

**WSL logs**: 
Docker crash while starting: https://hastebin.com/nayanoyebo.sql
Ubuntu crash while running & installing: https://hastebin.com/gutogihule.sql

#  Expected behavior
That WSL works as well as Docker or Bash.exe

# Actual behavior
I receive the following message : 'Remote procedure call failed.'

**Comment by licanhua** [comment]
This is known issue, please update windows to 20226.

**Comment by blackliner** [comment]
Use get.docker.com install script, I think it is the better alternative than docker desktop
