### ISSUE TITLE
C++ standard library headers could not be found

### ISSUE THREAD

**Issue by amyjbrown** [microsoft/WSL#6047]
# Environment
WSL Ubuntu on Windows 10
```none
Windows build number: Microsoft Windows [Version 10.0.18363.1082]
Your Distribution version:  Release 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020
```

# Steps to reproduce

I was attempting to compile a CPP object file from a text file that includes the standard library.
1. Install gpp via `sudo apt-get install gpp`
2. Create trivial test file, mine was
```cpp
// example.cpp
#include <cstdio>
int main(int argc, char* argv[]){
  printf("This is a %s!\n", "string");
  return 0;
}
```
2. Run `gpp example.cpp`
3. get following error message:
```shell
// Example c++ project

example.cpp:4: error: Requested include file not found
```

**WSL logs**: 
*I've attempted to share my WSL logs but it appears I can't do that unless my laptop is signed in with a Microsoft account. I'll see if I can't correct this tomorrow morning.*
#  Expected behavior

I was expecting to compile a trivial C program that prints "This is a string!" to check if the gpp compiler worked.
# Actual behavior
I got an error from the gpp compiler that the standard library header (in this case, `cstdio`) was not able to be found.
Additionally, Visual Studio Code Intellisense could not detect the code and gave me an error for it.

**Comment by onomatopellan** [comment]
Try `sudo apt install --reinstall build-essential`

**Comment by amyjbrown** [comment]
> Try `sudo apt install --reinstall build-essential`

Just tried this, successfully updated but the same error still occurs

**Comment by onomatopellan** [comment]
Any reason you need gpp? Just `gcc example.cpp` is enough for compiling you code.

**Comment by sr229** [comment]
gcc usually doesn't find the files so use `g++` instead.

**Comment by blackliner** [comment]
very propable that you want to use `g++` or at least `gcc` instead of the [PreProcessor ](https://logological.org/gpp?ref=darwinports.com)`gpp`

**Comment by amyjbrown** [comment]
Thanks everyone, now that I've done `--reinstall build-essentials` and am actually using the right program it works fine! 😅

**Comment by amyjbrown** [comment]
Compilation correctly works now -- it turns out I was using the wrong command line program.
