### ISSUE TITLE
An oddity with dual displays 

### ISSUE THREAD

**Issue by mattmazer0397** [microsoft/WSL#6050]
**Is your feature request related to a problem? Please describe.**
I use Pengwin WSL2 and the xfce desktop environment, through VcXsrv. If I initialize the xfce desktop, while using a dual display setup, park of the desktop wants to span across both screens, but not all. The desktop also falls beneath the taskbar, which can make accessing the toolbar in xfce a bit awkward. 
*DISCLAIMER* I'm not sure if this is an issue or feature request. I'm also not sure if this is a problem for WSL2 or the team behind xfce or even the xserver. At the least, I figure when Wayland/GUI is supported in WSL2 this issue will at least be on your radar.

**Describe the solution you'd like**
Maybe an option to pull up the desktop on one screen, or span the desktop appropriately across both screens.

**Describe alternatives you've considered**
I was thinking about looking at one or two other xservers and see how they handle it.

**Additional context**
![2020-10-07](https://user-images.githubusercontent.com/54451187/95358650-470c3b80-0897-11eb-8b79-bcc4b1408edc.png)

**Comment by benhillis** [comment]
This is more a xfce feature request.
