### ISSUE TITLE
WSL2 remote port forwarding for rmate fails

### ISSUE THREAD

**Issue by Memphizzz** [microsoft/WSL#6052]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2 - Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
```

# Steps to reproduce

I'm trying to use rmate which worked fine in WSL1 using the following command: `ssh user@host -R 52698:127.0.0.1:52698`.
Once this port forwarding is enabled I can usually run `rmate some/file.txt` and it would pop up on my VisualStudio Code instance running the "Remote VSCode" extension.

**WSL logs**: 

#  Expected behavior

I would expect the file to open in my VisualStudio Code instance.

# Actual behavior
I get: `connect_to 127.0.0.1 port 52698: failed.`

I know that WSL2 works differently in regards to networking (due to it using NAT) but does this mean that this kind of port forwarding is simply not supported anymore? Is there a workaround I can use?

**Comment by markko1-pro** [comment]
The difference is that 127.0.0.1 pointed to host in WSL1, but in WSL2 host is on another IP. You can find it out like that:
`grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'`
So you just have to point your program not to 127.0.0.1 as before, but to this new IP.
