### ISSUE TITLE
Windows does not recognize permissions to enable WSL?

### ISSUE THREAD

**Issue by lalbritton99** [microsoft/WSL#6053]
Attempting to enable WSL for a dev class at college. Forgive me if I don't have the best understanding of the IT involved in my issue. 

Attempting to enable on my personal computers admin account via start > search "Turn windows features on or off" resulted in a popup error window saying it could not access due to permissions for some reason. Attempting to enable using Powershell also was restricted due to "permissions". I followed the file path then and manually launched OptionalFeatures.exe, enabled WSL, and restarted the computer (no permissions issues doing this). WSL is definitely enabled now, but if I attempt to launch Ubuntu, as just downloaded, I get this error upon startup:

WslRegisterDistribution failed with error: 0x8007019e
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.

I'm at a loss for why my system doesn't seem to recognize my admin permissions or that WSL is now enabled. Any help troubleshooting from here is appreciated.

**Comment by saptarsi96** [comment]
@lalbritton99 In case it helps you, I had the same error despite having WSL checked.
Unchecking it, rebooting, checking it, rebooting again, and uninstalling Ubuntu and running Ubuntu install worked for me.

**Comment by lalbritton99** [comment]
@saptarsi96 I can't believe that after messing with computers for this long and preaching it endlessly, I still failed to "turn it off and on"... Resetting and rebooting took care of it. Appreciate the gentle reminder
