### ISSUE TITLE
WSL2: WslRegisterDistribution failed with error: 0x80070002

### ISSUE THREAD

**Issue by DiarmuidKelly** [microsoft/WSL#6062]
# Environment

Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Release:        9.5
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

# Steps to reproduce

PS C:\WINDOWS\system32> wsl.exe --set-version Debian 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The system cannot find the file specified.

#### OR

PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\WINDOWS\system32> cd C:\distros\Ubuntu\
PS C:\distros\Ubuntu> .\ubuntu2004.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...

---------------
#### Tried:
- $ sudo apt-get update
- $ sudo apt-get dist-upgrade
Inside distro, the conversion, does not work.
- unchecking windows features - does not work - restarting multiple times
- manually installing https://docs.microsoft.com/en-gb/windows/wsl/wsl2-kernel
- wsl.exe --update ( _--update_ not a parameter)
- dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

**WSL logs**: Submitted

#  Expected behavior

Expect WSL v1 to be converted to v2. Or, for _wsl --set-default-version 2_ to allow fresh installation under wsl2.

# Actual behavior

The system cannot find the file specified.

0x80070002 errors

Cannot run docker with WSL2 backend as a result.

**Comment by licanhua** [comment]
Please share the link of the log

**Comment by DiarmuidKelly** [comment]
https://aka.ms/AA9xqyz

**Comment by licanhua** [comment]
Error is coming from Hyper-V.
It has problem to create network. I don't know if you will hit error too if you create a network from hyper-v management.
I ever saw some user miss C:\Windows\System32\VmSynthNic.dll, can you check if this file exists?
Sometime it may fix hyper-v issue after you disable virtual machine platform feature, then enable it.

**Comment by licanhua** [comment]
You may also check if there is error in Event Viewer

**Comment by DiarmuidKelly** [comment]
Yes it could be a hyper-v issue. It's not possible to create a hyper-v virtual network

###### Event viewer indicates this started yesterday with 
ERROR: schannel: A fatal error occurred while creating a TLS client credential. The internal error state is 10013.
###### then a windows update:
Installation Started: Windows has started installing the following update: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.325.389.0)
Installation Successful: Windows successfully installed the following update: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.325.389.0)
###### then distributed COM
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
##### then Docker goes down
The Docker Desktop Service service terminated unexpectedly. It has done this 1 time(s).


---------------------
Current issues since then

Setting policy:
System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing
and
dism /online /cleanup-image /restorehealth
have no effect

**Comment by onomatopellan** [comment]
Could it be you are using some VPN? See https://github.com/microsoft/WSL/issues/5107#issuecomment-639222516

**Comment by DiarmuidKelly** [comment]
@onomatopellan thanks for your reply, I don't use a VPN. But the comment after this maybe provides some information [#5107 (comment)](https://github.com/microsoft/WSL/issues/5107#issuecomment-650879541). I recently uninstalled VMWare player. This could have brought down a network adapter that WSL was using. 

Should there be an entry for an ethernet adapter that Hyper-v is looking for?

**Comment by DiarmuidKelly** [comment]
Windows IP Configuration

   Host Name . . . . . . . . . . . . : DK-Laptop
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (3) I218-LM
   Physical Address. . . . . . . . . : -----------------------
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : -----------------------
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : -----------------------
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter WiFi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Dual Band Wireless-N 7265
   Physical Address. . . . . . . . . : -----------------------
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : -----------------------
   Temporary IPv6 Address. . . . . . : -----------------------
   Link-local IPv6 Address . . . . . : -----------------------
   IPv4 Address. . . . . . . . . . . : -----------------------
   Subnet Mask . . . . . . . . . . . : -----------------------
   Lease Obtained. . . . . . . . . . : Friday 9 October 2020 09:29:09
   Lease Expires . . . . . . . . . . : Friday 9 October 2020 12:29:09
   Default Gateway . . . . . . . . . : -----------------------
   DHCP Server . . . . . . . . . . . : -----------------------
   DHCPv6 IAID . . . . . . . . . . . : -----------------------
   DHCPv6 Client DUID. . . . . . . . : -----------------------
   DNS Servers . . . . . . . . . . . : -----------------------
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : -----------------------
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

**Comment by onomatopellan** [comment]
In my case it shows "Microsoft Hyper-V Network adapter". Try disabling "Virtual Machine Platform" windows feature, restart, and enable it again.

**Comment by DiarmuidKelly** [comment]
Could not figure this out, need to continue work. Reset Windows.

**Comment by olegueret** [comment]
> @onomatopellan thanks for your reply, I don't use a VPN. But the comment after this maybe provides some information [#5107 (comment)](https://github.com/microsoft/WSL/issues/5107#issuecomment-650879541). I recently uninstalled VMWare player. This could have brought down a network adapter that WSL was using.
> 
> Should there be an entry for an ethernet adapter that Hyper-v is looking for?

It was this for me: I also uninstalled VMware Player and this was the cause of this 0x80070002 error: i couldn't install WSL distros (Ubuntu 20.04) and it also failed when starting an Ubuntu 18.04 I had installed. 

Installing the latest version solved it for me (VMware-player-16.1.2-17966106.exe).

Before doing that, I noticed that the VMware Player uninstaller did remove their network adapters "VMware Network Adapter VMnet1" and "VMware Network Adapter VMnet8" and neither their services "VMware NAT Service" and "VMware DHCP Service". So I uninstalled the adapters manually from windows Device Manager but that didn't help (didnt' try to also remove leftover VMware services). Only reinstalling VMware Player worked.

**Comment by Postroggy** [comment]
> > @onomatopellan thanks for your reply, I don't use a VPN. But the comment after this maybe provides some information [#5107 (comment)](https://github.com/microsoft/WSL/issues/5107#issuecomment-650879541). I recently uninstalled VMWare player. This could have brought down a network adapter that WSL was using.
> > Should there be an entry for an ethernet adapter that Hyper-v is looking for?
> 
> It was this for me: I also uninstalled VMware Player and this was the cause of this 0x80070002 error: i couldn't install WSL distros (Ubuntu 20.04) and it also failed when starting an Ubuntu 18.04 I had installed.
> 
> Installing the latest version solved it for me (VMware-player-16.1.2-17966106.exe).
> 
> Before doing that, I noticed that the VMware Player uninstaller didn't remove their network adapters "VMware Network Adapter VMnet1" and "VMware Network Adapter VMnet8" and neither their services "VMware NAT Service" and "VMware DHCP Service". So I uninstalled the adapters manually from windows Device Manager but that didn't help (didnt' try to also remove leftover VMware services). Only reinstalling VMware Player worked.

thx,bro. reinstall the VMplayer solved my problem.

**Comment by Postroggy** [comment]
# a simple solution:
reinstall vmware again, then you will find everything just went back on track again.

**Comment by jerrychong25** [comment]
Can try to delete delete the .wslconfig under your `C:\Users\<your username>\`. This method works for my end.

Source: https://github.com/microsoft/WSL/issues/4959#issuecomment-1099128748

**Comment by hasantahsinakin** [comment]
> Can try to delete delete the .wslconfig under your `C:\Users\<your username>\`. This method works for my end.
> 
> Source: [#4959 (comment)](https://github.com/microsoft/WSL/issues/4959#issuecomment-1099128748)

Thank you. This solved my problem.

**Comment by tristiisch** [comment]
> Can try to delete delete the .wslconfig under your `C:\Users\<your username>\`. This method works for my end.
> 
> Source: [#4959 (comment)](https://github.com/microsoft/WSL/issues/4959#issuecomment-1099128748)
thx, there was a path to a file that I deleted...

**Comment by allape** [comment]
> # a simple solution:
> reinstall vmware again, then you will find everything just went back on track again.

Moving vmware workstation to another disk broke every "virtual" things. By changing config in RegEdit, and reinstalling vmware soleved this issue for me.
If reinstallation is stucked, search for the old partial path of vmware installation path in RegEdit, and replace it with the new location.

**Comment by shyed2001** [comment]
VMware is a dangerous software then. I had to do through regedit and finding all vmware words and had to change all the previous path set there. Why would vmware bind itself with so may other tis ?

**Comment by arthur1573** [comment]
i figued out: it is your network config limit of your company....

try to call/message your security work mate.....
