### ISSUE TITLE
mistake in german translation of wsl --mount command

### ISSUE THREAD

**Issue by schubc** [microsoft/WSL#6066]
# Environment

```none
Windows build number: 10.0.20231.0
Your Distribution version: any
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Use de-DE locale, mount a physical drive.

```PS C:\WINDOWS\system32> wsl --mount \\.\PHYSICALDRIVE1 -p 1```
```
Der Datenträger “\\.\PHYSICALDRIVE1” wurde unter dem Namen “PHYSICALDRIVE1p1” erfolgreich bereitgestellt. Der Bereitstellungspunkt kann unter dem Pfad gefunden werden, auf den die Einstellung "automount" (Standardwert: /mnt/wsl) verweist.
Führen Sie "wsl--unmount \\.\PHYSICALDRIVE1” aus, um die Bereitstellung aufzuheben und den Datenträger zu trennen.
```

**WSL logs**: 

#  Expected behavior
The last line should be 
```Führen Sie "wsl --unmount \\.\PHYSICALDRIVE1" aus, um die Bereitstellung aufzuheben und den Datenträger zu trennen.```

# Actual behavior

There are two problems in the output
- it should be ```wls --unmount```
- there are two kinds of quotation marks mixed, " and ”

**Comment by craigloewen-msft** [comment]
I've submitted this bug to the localization team so we can get a fix for this! Thank you for filing it.

**Comment by craigloewen-msft** [comment]
This has been marked as resolved internally, and should be fixed in a future build!

**Comment by schubc** [comment]
Hi,

this is still open in 10.0.21370

Actual behavior
-----------------

`PS C:\WINDOWS\system32> wsl --mount \\.\PHYSICALDRIVE1 -p 1
Der Datenträger „\\.\PHYSICALDRIVE1“ wurde unter dem Namen „PHYSICALDRIVE1p1“ erfolgreich bereitgestellt. Der Bereitstellungspunkt kann unter dem Pfad gefunden werden, auf den die Einstellung „automount“ (Standardwert: /mnt/wsl) verweist.`
`Führen Sie „wsl--unmount \\.\PHYSICALDRIVE1“ aus, um die Bereitstellung aufzuheben und den Datenträger zu trennen.`

Expected behavior
---------------------

The last line should be
`Führen Sie „wsl --unmount \\.\PHYSICALDRIVE1“ aus, um die Bereitstellung aufzuheben und den Datenträger zu trennen.`
The quotation marks changed, but it is still missing a space between wsl and --unmount
