### ISSUE TITLE
Passing empty parameter to wsl --exec fails with "The parameter is incorrect"

### ISSUE THREAD

**Issue by segrey** [microsoft/WSL#6072]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.546]
Your Distribution version: Ubuntu-20.04
Whether the issue is on WSL 2 and/or WSL 1: the issue is both on WSL 1 and WSL 2
```

# Steps to reproduce

Run `wsl.exe --distribution Ubuntu-20.04 --exec /bin/echo ""` in cmd.exe.

![image](https://user-images.githubusercontent.com/607109/95689858-7bc41e00-0c1c-11eb-9735-99961eca8700.png)

**WSL logs**: 

#  Expected behavior

`wsl.exe --distribution Ubuntu-20.04 --exec /bin/echo ""` should output an empty line, like `wsl.exe --distribution Ubuntu-20.04 --exec /bin/bash -c "/bin/echo ''"` does.

# Actual behavior

The command fails with error `The parameter is incorrect.`.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by segrey** [comment]
Done: https://aka.ms/AA9ypz2

**Comment by licanhua** [comment]
This is a bug.
@benhillis When LxssCreateProcess parse arguments, "" is treated as Invalid parameter. maybe we should support empty parameter and convert empty back to "" before we pass it to linux.
