### ISSUE TITLE
WSL2 No External Connectivity

### ISSUE THREAD

**Issue by rsaanon** [microsoft/WSL#6075]
**ENV**: 
 * 2 Hosts: Win 10 Pro 10.0.20231 Build 20231 (Clean Install) 
 * Defender Firewall DISABLED on BOTH hosts.

**PROBLEM**: 
---- HOST A: has external network connectivity regardless of WSL version being used
---- HOST B: only has external network connectivity using configured to use WSL1 
On host B, Linux distributions set for using WSL2 have no external network connectivity; however, if the distribution is set for WSL1 external network connectivity is established.

**OBERVATIONS (for WSL2): HOST B**
-- DNS resolution is not an issue as we are pinging external host using IP address.
-- IP & Default route of the instance are correct based on host B.
-- Running Ubuntu instance does have network connectivity to the host via the NAT 

**IP Info for eth0 on Host B:**  
Windows host: 172.22.48.1/20 (vEthernet WSL)
Ubuntu WSL2:  172.22.49.39/20 brd 172.22.63.255 scope global eth0
Route Info:
-- default via 172.22.48.1 dev eth0
-- 172.22.48.0/20 dev eth0 proto kernel scope link src 172.22.49.39

----------
For troubleshooting purpose, WSL was completely uninstalled & reinstalled with the same problem.

**Comment by licanhua** [comment]
I didn't understand your question. Do you mean host B has problem to access www.microsoft.com, or host B has problem to connect to Windows which WSL 2 distro is installed.
If you mean you have problem to ping the Windows, it's possible that the firewall blocked the ping.(you can try add an ICMP inbound rule although you said you disabled the firewall)

**Comment by lukee1234** [comment]
If I understand your issue, look at #5256
