### ISSUE TITLE
WSL version 2 Stopped Working

### ISSUE THREAD

**Issue by jasonp019** [microsoft/WSL#6080]
I'm running Windows 10 version 2004 (build 19041.508) under Bootcamp on my Macbook Pro version 11,1 (late 2013).  I have WSL 2 installed, along with the required kernel upgrade.  My debian WSL 2 instance had been working until I tried to start it up today and now it fails, saying:

Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

msinfo32 reports that "Hyper-V Virtualization Enabled in Firmware" is "No."  However, if that is the case, how was it *ever* working?

This is incredibly frustrating because it *was* working.  Has anyone had any issue with this occurring?

Thank you!

**Comment by jasonp019** [comment]
I am closing this issue.  Apparently, all I had to do to make MS Windows happy about Hyper-V Virtualization being enabled in firmware was to reboot to Mac OS and then reboot into Windows.  No idea why, but that's what fixed it for me.  WSL 2 working properly now.

**Comment by fbl773** [comment]
I appear to be having this issue... what is it that you had to do on both sides? I'm not following.

**Comment by fbl773** [comment]
> I appear to be having this issue... what is it that you had to do on both sides? I'm not following.

Wow. It literally was boot in / out of macos again. I did go through the install steps again... Was not expecting things to be this simple after some of the Bootcamp battles I've had.
