### ISSUE TITLE
Inconsistent file counts using PHP via Docker Desktop on WSL2

### ISSUE THREAD

**Issue by themizzi** [microsoft/WSL#6081]
# Environment

Windows 10 Pro
Version 2004
OS build 19041.546
Docker Desktop 2.4.0.0 (48506)
Reproducible on WSL2

# Steps to reproduce

Please use this repository: https://github.com/themizzi/wsl2-php-recursive-directory-iterator-bug

```bash
git clone https://github.com/themizzi/wsl2-php-recursive-directory-iterator-bug.git
cd wsl2-php-recursive-directory-iterator-bug
docker-compose run php php test.php
```

**WSL logs**: 

https://aka.ms/AA9ytk1

#  Expected behavior

File counts remain the same whether using PHP's `scandir` or `RecursiveDirectoryIterator`.

# Actual behavior

File counts diverge after 65 files.

**Comment by therealkenc** [comment]
Taking the PHP folks' [analysis](https://bugs.php.net/bug.php?id=80227) this is /dupe #5074.
