### ISSUE TITLE
Cannot get the host IP using  /etc/resolv.conf on windows 20H2 19042.527

### ISSUE THREAD

**Issue by jpcoding** [microsoft/WSL#6086]
It returns the wsl2 IP rather than windows host IP

**Comment by jpcoding** [comment]
OK, I used a very nasty way and it's solved ......
**export DISPLAY=$(ipconfig.exe | grep IPv4 |grep -v $(tail -1 /etc/resolv.conf | cut -d' ' -f2) |  cut -d: -f2 |tr -d ' '|tr -d '\r \n'):1.0
export LIBGL_ALWAYS_INDIRECT=1**

**Comment by jpcoding** [comment]
> 2

This is used to forward x windows. Works for me.

**Comment by benhillis** [comment]
Can you share the output of the following commands?
```
cat  /etc/resov.conf
ip addr
```

**Comment by therealkenc** [comment]
Also output of:
```
$ ip route
```

There is some unconfirmed/inclusive evidence (eg [this](https://github.com/microsoft/WSL/issues/4619#issuecomment-702460899)) that `/etc/resolve.conf` sometimes ends up pointing at a router not Windows.

**Comment by jpcoding** [comment]
Hi this returns the  wsl2's IP only.
I used to use this to get the host IP for x forwarding. Maybe I was wrong?
________________________________

**Comment by therealkenc** [comment]
What is the output of: 
```
$ ip route
$ ip addr show dev eth0
$ cat /etc/resolv.conf
```

**Comment by jpcoding** [comment]
> What is the output of:
> 
> ```
> $ ip route
> $ ip addr show dev eth0
> $ cat /etc/resolv.conf
> ```

All returns 172.21.176.1

**Comment by jpcoding** [comment]
I was using /etc/resolv.conf  for X forwarding on windows 10 2004.

**Comment by ylm98** [comment]
resolv.conf only include windows DNS IP

cat /etc/resolv.conf
`$This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
$ [network]
$ generateResolvConf = false
nameserver 114.114.114.114
nameserver 8.8.8.8
nameserver fec0:0:0:ffff::1
search Home`

ip addr show dev eth0
`12: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether 54:05:db:15:08:2e
    inet 192.168.1.4/24 brd 192.168.1.255 scope global dynamic
       valid_lft 85336sec preferred_lft 85336sec
    inet6 fe80::8485:81e8:b99d:bdf0/64 scope link dynamic
       valid_lft forever preferred_lft forever`

**Comment by dwmuller** [comment]
I am having similar issues, and have seen other more recent reports that seem related. I'm using Windows 10 Pro build 19042.867, and Ubuntu in WSL2.

ipconfig shows the vEthernet Default Switch with address 172.19.64.1, vEhternet WSL with 172.28.16.1, Ethernet 3 (my hardwired connection to my home network) with 192.168.16.62. In Ubuntu, /etc/resolv.conf lists the nameserver as 172.28.16.1.

On Windows, I can ping 172.28.16.1 sucessfully. From Ubuntu, it times out.

On Windows, I run 

`  python -m http.server 8080`

This listens on all interfaces; "netsh -an" shows it listening on 0.0.0.0.
From the Windows host, I get the expected response in a browser at 127.0.0.1, 172.28.16.1, and 192.168.16.62.
From Ubuntu, testing with curl, 127.0.0.1 fails immediately, 172.28.16.1 times out, and 192.168.16.62 works.

Using the host's external address is less than ideal, as I actually want to run proxy development tools on Windows that should not listen on the external interface. As a temporary workaround on a private network it should be OK.

On Ubuntu:

```
> ip route
default via 172.28.16.1 dev eth0
172.28.16.0/20 dev eth0 proto kernel scope link src 172.28.29.229

> ip addr show dev eth0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:a8:63:ca brd ff:ff:ff:ff:ff:ff
    inet 172.28.29.229/20 brd 172.28.31.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fea8:63ca/64 scope link
       valid_lft forever preferred_lft forever
       
> cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.28.16.1       
```
