### ISSUE TITLE
升级wsl2出现了这样的错误谁会呀教教我。

### ISSUE THREAD

**Issue by 1334065186** [microsoft/WSL#6087]
ystem.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: �S��v�[a�{|�W
N/ec\Ջ�v�d\O0
 stderr: 
   在 Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:行号 142
   在 Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:行号 82
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:行号 99
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:行号 29
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 67
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() 位置 C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 92

**Comment by licanhua** [comment]
The output is not readable, so it's impossible for me to know what the actual error is.
From your log, docker has problem to call WSL to execute a command. You can check:
1. `wsl -l -v`. I expect there at least 3 distros. 2 of them are docker distros, and one of them is something like Ubuntu
2. execute `wsl -d Ubuntu` to launch the distro.
If launching failed, they please post the error message.
If everything is OK, then you can use [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to know the actual command line, and then execute command line manually.

If you still can't get the actual error message, please [collect wsl log and share the link](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by 1334065186** [comment]
你说的我也不懂，希望远程操作一下。

**Comment by 1334065186** [comment]
对于不懂电脑，简直是天书。

**Comment by licanhua** [comment]
`stdout: �S���v�[a�{|�W` 是乱码，需要知道这错误具体是什么
打开一个控制台窗口（cmd.exe)，然后执行 `wsl -l -v`

我装的是Ubuntu，另外两个是docker的
```
C:\WINDOWS\system32>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running        2
  docker-desktop         Running        2
  docker-desktop-data    Running        2
```

然后你一个一个执行
`wsl -d Ubuntu`
`wsl -d docker-desktop`
`wsl -d docker-desktop-data`
直到有一个有错误消息打印出来，然后你把错误消息内容贴出来

**Comment by xds95** [comment]
你还是找人有偿帮你搞吧，不懂电脑整那wsl2干嘛，整出wsl2然后呢？在不懂电脑的基础上进行linux开发吗

**Comment by 1334065186** [comment]
突然出现更新我以为是正常更新。

**Comment by kiritowch** [comment]
> 你还是找人有偿帮你搞吧，不懂电脑整那wsl2干嘛，整出wsl2然后呢？在不懂电脑的基础上进行linux开发吗

为你的回答刚到羞耻。https://zhuanlan.zhihu.com/p/151392411

**Comment by xds95** [comment]
> 可以参考下这个，https://zhuanlan.zhihu.com/p/151392411 。（另外为你的回答感到羞耻

你看清了没，上面已经有人提供了简单的方法，人家看不懂，要求远程一下。你提供的方法怎么了，就突然能让他看懂了？
如果你能付出时间精力远程帮忙解决，那我心服口服。又或者，您这样单纯的圣母举动能让您的心里得到慰藉，请随意。我不会为你感到难堪

**Comment by 1334065186** [comment]
> 你还是找人有偿帮你搞吧，不懂电脑整那wsl2干嘛，整出wsl2然后呢？在不懂电脑的基础上进行linux开发吗



> `stdout: �S���v�[a�{|�W`是乱码，需要知道这错误具体是什么
> 打开一个控制台窗口（cmd.exe），然后执行`wsl -l -v`
> 
> 我装的是Ubuntu，另外两个是docker的
> 
> ```
> C:\WINDOWS\system32>wsl -l -v
>   NAME                   STATE           VERSION
> * Ubuntu                 Running        2
>   docker-desktop         Running        2
>   docker-desktop-data    Running        2
> ```
> 
> 然后你一个一个执行
> `wsl -d Ubuntu`
> `wsl -d docker-desktop`
> `wsl -d docker-desktop-data`
> 直到有一个有错误消息打印出来，然后你把错误消息内容贴出来

**Comment by 1334065186** [comment]
![image](https://user-images.githubusercontent.com/72840008/97651476-25b5fe00-1a97-11eb-804c-7d92093554f7.png)
我把这个关了行不行

**Comment by abserari** [comment]
https://github.com/docker/for-win/issues/5256#issuecomment-561153467 see here with

or exec this command

把 jako 换成你自己的用户名.
```bash
cd
mkdir custom-docker-desktop
wsl --import docker-desktop c:\Users\jako\custom-docker-desktop 'C:\Program Files\Docker\Docker\resources\wsl\wsl-bootstrap.tar' --version=2
```

如果说已经有版本了, 先注销
```bash
wsl --unregister docker-desktop
```

**Comment by longletian** [comment]
别用wsl2版本 就只用wsl版本就可以了，系统版本换成专业版

**Comment by gclsoft** [comment]
打开网站 https://czf-net.xyz/res/

下载wsl.msi

一路Next

重启Docker解决！

**Comment by 2bon** [comment]
czf-net.xyz/res/

下载wsl.msi

**Comment by BreakALegCml** [comment]
感谢大佬，解决问题了

**Comment by wyd0817** [comment]
cmd管理员模式运行
`netsh winsock reset
`
重启计算机后解决问题。

**Comment by kiritowch** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
