### ISSUE TITLE
Exit code 0xe000020b at WSL2 distro startup

### ISSUE THREAD

**Issue by aioloswong** [microsoft/WSL#6089]
# Environment

```none
Windows build number: 10.0.19041.572
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

click the "Ubuntu 20.04 LTS" icon in the start menus.
![image](https://user-images.githubusercontent.com/10336303/95990663-62121900-0e5e-11eb-984a-4fe0e95aed78.png)

**WSL logs**: 

https://aka.ms/AA9z38n

#  Expected behavior

bootup Ubuntu 20.04 LTS successfully. 

# Actual behavior

unable to start up Ubuntu 20.04 LTS.

**Comment by licanhua** [comment]
Error is coming from Hyper-V, and it has problem to create network.

**Comment by aioloswong** [comment]
@licanhua 
I'm using WSL2, without Hyper-V enabled.

**Comment by licanhua** [comment]
I have incorrect description. I thought HNS(networking) is part of Hyper-V but actually it's not.

**Comment by aioloswong** [comment]
@licanhua 
The cause of the problem is that my network adapter list is empty. I fixed the problem by executing the following command：
netsh winsock reset
netcfg -d
Then restart the computer and the problem is solved.

**Comment by licanhua** [comment]
Thanks to share this.

**Comment by licanhua** [comment]
@aioloswong may I ask: how did you determine your network adapter list was empty?

**Comment by aioloswong** [comment]
@licanhua I opened my computer's "Control Panel \Network and Internet\Network Connections" and found that there was no network connection(it was empty). Nevertheless, I could access the Internet.
