### ISSUE TITLE
ARM64+KB4579311: WSL2 distros do not start and generate an error: "the parameter is incorrect" process terminated with code 4294967295

### ISSUE THREAD

**Issue by AlfrFerr** [microsoft/WSL#6090]
# Environment

```none
Windows build number: Microsoft Windows [Versione 10.0.19041.572] (Windows on ARM on Surface Pro X)
Your Distribution version: Ubuntu 20.04, Ubuntu 18.04, Kali 2020.3
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Launch Windows Terminal and open a new tab with a linux distro (e.g., Ubuntu 20.04) or, alternatively, from Windows Command Prompt (CMD) run wsl.exe.

**WSL logs**:  https://aka.ms/AA9yx5u
#  Expected behavior
The selected linux distro starts and the bash prompt appears.

# Actual behavior
The following error is reported:
The parameter is incorrect.
[Process terminated with code 4294967295]

![2020-10-14](https://user-images.githubusercontent.com/72878571/96014968-49e2cf80-0e47-11eb-8ef8-279f35936a49.png)

The issue appeared after Windows Update installed KB4579311. Uninstalling KB4579311 makes wsl2 working properly again.

**Comment by licanhua** [comment]
From the log, you have problem to create the virtual machine. the error is coming from Hyper-V

**Comment by licanhua** [comment]
Combined with #6085, look like issues are related to KB4579311 + Surface Pro X

**Comment by shuffle2** [comment]
Also hitting this after applying windows updates today on Surface Pro X. Unsure if KB4579311 specifically caused it.
Do you mention KB4579311 specifically because the issue is known / there is a workaround?

**Comment by asampal** [comment]
Just want to note that I had what I thought the same issue (#6091) where WSL 2 doesn't seem to start/work, but I'm not using a Surface device.

**Comment by tamoanxx** [comment]
I have tried numerous times today to uninstall that update but fails with the message couldn't uninstall successfully. I'm on a surface pro x sq2

**Comment by licanhua** [comment]
>From Ben: We've identified the bug that introduced this regression and will work on servicing this ASAP. In the meantime I'd suggest reverting this update (and pausing future updates until this is fixed).

If you are not ARM based, that should be another issue.

**Comment by joshkerr** [comment]
How would I go about uninstalling this update? Is there another workaround? I've already upgraded to the insider beta to try to mitigate this bug to no avail. Do I need to refresh my windows install to correct it?

**Comment by onomatopellan** [comment]
@joshkerr Use Settings -> Update & Security -> Recovery -> Rollback to get your previous build. If you are lucky you will be able to uninstall the update KB or even use System Restore.

**Comment by benhillis** [comment]
@licanhua - the title specifies this is ARM, so this is a duplicate.

**Comment by joshkerr** [comment]
I reset my Surface Pro X SQ2 to Windows version 2004 Pro. With no updates installed, I enabled the Linux subsystem, the virtual machine, and installed the ARM version of the Linux kernel update. I installed Ubuntu 20.04 LTS from the Microsoft store. Then tried to set the version to 2.

wsl --set-version Ubuntu.20.04 2

I got the same parameter incorrect error.

**Comment by joaomoreno** [comment]
@benhillis Is there another way except rolling back? Is there a patch update coming soon to fix this?

**Comment by Alovchin91** [comment]
@benhillis  It is a duplicate of which issue? I can't find anything ARM-specific in regard of this. Can you please re-open this issue?

**Comment by joaomoreno** [comment]
I confirm that rolling back KB4579311 makes WSL2 work again.

**Comment by joaomoreno** [comment]
@benhillis As I have my SPX joined to corp, I can't really pause updates at all. Please provide information on whether a fix is coming soon as this really blocks my dev scenario on SPX.

**Comment by benhillis** [comment]
@joaomoreno - fix is coming soon, today I think.

**Comment by puzzone** [comment]
Same UX on Samsung Galaxy Book S (ARM), rollback to KB4579311 heals the pain, I really need WSL2 to work. Thanks!

**Comment by wangfys** [comment]
@benhillis
Hello, is there any information about the fix? For example, the name of the corresponding windows update patch that fix this problem? I usually cannot receive the latest update automatically so I want to manually download the update and install it if it has been published already.

@joaomoreno
By the way, thanks to the windows arm64 version of VSCode. I'm a little surprised to see your comment here. I hope your work can go back on track soon.

**Comment by Alovchin91** [comment]
@benhillis @nhobson99 Why is this issue closed? It's not resolved and we have no idea when and if it will be resolved!

**Comment by mirogl** [comment]
Seems the new insider Build fixed this problem - https://mspoweruser.com/windows-10-insider-preview-build-19042-608/ 

Microsoft fixed an issue with starting Windows Subsystem for Linux 2 (WSL2) on ARM64 devices that occur after installing KB4579311.

Hopefully it will also be released soon for all.

**Comment by Alovchin91** [comment]
@mirogl Thanks for the info. Unfortunately, this update appears to break Outlook for some users: https://answers.microsoft.com/en-us/msoffice/forum/all/this-morning-10232020-windows-10-installed-an/30f8455c-f7ea-4487-8fcf-be14cbaafeee

They just can't get it right ¯\_(ツ)_/¯

**Comment by mirogl** [comment]
Hi @Alovchin91 - on my Surface Pro X and Galaxy Book S Outlook 2019 works without any problem.
So at least it seems not to be a general problem, like the problem with WSL2. I'm glad, WSL2 works again.

**Comment by jasonrandrews** [comment]
Fix worked for me on Galaxy Book S, very glad to have WSL 2 back, but pretty scary that it was broken for a week.

**Comment by AlfrFerr** [comment]
@mirogl, @jasonrandrews: did you install KB4580364 on version 20H1 or 20H2? On my Surface Pro X 20H2 is not yet available in Windows update. Thanks.

**Comment by mirogl** [comment]
> @mirogl, @jasonrandrews: did you install KB4580364 on version 20H1 or 20H2? On my Surface Pro X 20H2 is not yet available in Windows update. Thanks.

Hi @AlfrFerr - I installed KB4580364  on 20H2 manually, like described in https://github.com/microsoft/WSL/issues/6090#issuecomment-715459214 , since I didn't get it offered via Windows Update.

**Comment by ac1982** [comment]
> @joaomoreno @puzzone @wangfys @Alovchin91 - the patch KB4580364 was released now
> 
> _`Microsoft fixed an issue with starting Windows Subsystem for Linux 2 (WSL2) on ARM64 devices that occur after installing KB4579311.`_
> 
> here the download Link for arm64 http://download.windowsupdate.com/c/msdownload/update/software/updt/2020/10/windows10.0-kb4580364-arm64_cbf23c33fda7abeed9a20e5bb0af5f0419e543fc.cab
> 
> 1. Download cab and save it under a directory, with only the cab in it - for e.g. c:\temp\cab\
> 2. open cmd as adminstrator and execute "DISM.exe /Online /Add-Package /PackagePath:c:\temp\cab"
> 
> I tested it on my Microsoft Surface Pro X (SQ1) & Samsung Galaxy S (8cx) - WSL2 works now again.

Like rolling back.

**Comment by ntw-au** [comment]
I also can confirm that manually installing the new patch resolved this issue on Windows 10 20H2 running on a Samsung Galaxy Book2 (Snapdragon 850).

**Comment by ac1982** [comment]
> @joaomoreno @puzzone @wangfys @Alovchin91 - the patch KB4580364 was released now
> 
> _`Microsoft fixed an issue with starting Windows Subsystem for Linux 2 (WSL2) on ARM64 devices that occur after installing KB4579311.`_
> 
> here the download Link for arm64 http://download.windowsupdate.com/c/msdownload/update/software/updt/2020/10/windows10.0-kb4580364-arm64_cbf23c33fda7abeed9a20e5bb0af5f0419e543fc.cab
> 
> 1. Download cab and save it under a directory, with only the cab in it - for e.g. c:\temp\cab\
> 2. open cmd as adminstrator and execute "DISM.exe /Online /Add-Package /PackagePath:c:\temp\cab"
> 
> I tested it on my Microsoft Surface Pro X (SQ1) & Samsung Galaxy S (8cx) - WSL2 works now again.

After update ```kb4580364```, WSL 2.0 Ubuntu 20.04 break again.

**Comment by mirogl** [comment]
Hi @ac1982 - since for me and others KB4580364 fixes the problem - do you have an arm based pc  or intel/amd ? My comment is only for arm based PCs. If your PC is arm based - that should be another problem - not the problem caused by KB4579311. I'm also Using Ubuntu 20.04  - end evertything works.  If you have arm64 - did you try to reinstall Linux kernel upgrade from: https://docs.microsoft.com/en-us/windows/wsl/install-win10 - Step 4 - Download the Linux kernel update package : https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by dennisameling** [comment]
An even easier way to install the fix is to download KB4580364 from the update catalog: https://www.catalog.update.microsoft.com/Search.aspx?q=KB4580364 - the `.msu` file that you get allows for a one-click install of the update.

Happy to have a working WSL2 again 🚀

**Comment by cgfork** [comment]
m

**Comment by ac1982** [comment]
> Hi @ac1982 - since for me and others KB4580364 fixes the problem - do you have an arm based pc or intel/amd ? My comment is only for arm based PCs. If your PC is arm based - that should be another problem - not the problem caused by KB4579311. I'm also Using Ubuntu 20.04 - end evertything works. If you have arm64 - did you try to reinstall Linux kernel upgrade from: https://docs.microsoft.com/en-us/windows/wsl/install-win10 - Step 4 - Download the Linux kernel update package : https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

@mirogl thanks for your reply. Yes, I am using the Surface X one of ARM based PC. After reboot my PC twice manualy, wsl works fine now.
