### ISSUE TITLE
WSL2/Distro doesn't start after Windows update on 10/13/2020

### ISSUE THREAD

**Issue by asampal** [microsoft/WSL#6091]
Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Can't get into WSL, but I had been using an Ubuntu (2004.2020.812.0) distro on WSL 2 (with kernel update 4.19.128 applied)
```

# Steps to reproduce

After Windows startup, attempting to start the WSL by using the Windows Terminal does not work and results in an error dialog of "Could not find your default profile in your list of profiles - using the first profile. Check to make sure the "defaultProfile" matches the GUID of one of your profiles.", the default profile being for my Ubuntu distro.

I had been using WSL 2 with no issues until this update. Currently `wsl -l` just hangs. I tried installing the Alpine WSL distro to see if it was the Ubuntu distro at fault, but after seemingly installing that successfully, trying to start it from the Start menu pops up a terminal which just hangs (same as for the Ubuntu distro).

**WSL logs**: 
Collected via feedback app.
https://aka.ms/AA9z3lx

#  Expected behavior

Linux subsystem should start

# Actual behavior

Linux subsystem doesn't start

**Comment by asampal** [comment]
Closing as dupe of #6090

**Comment by asampal** [comment]
Reopening since this is not ARM64 or Surface Pro related like the other issues I assumed this was a duplicate of. Feel free to close if indeed it is.

**Comment by asampal** [comment]
Has this been confirmed as a general problem in non-ARM or Surface Pro X cases?

**Comment by coxoperationsengineer** [comment]
I have what I believe is this same issue, not an ARM processor or Surface Pro, but an older HP laptop, had Ubuntu 20.04 installed with WSL2 to an external drive, working fine for months, and after this update the other day I woke the machine up and it did its requisite reboots for the update, afterwards it won't even mount the drive that has my WSL2 version of Ubuntu on it, but Windows Store still thinks its installed, and wsl -l still shows it is there too.  At this point, I can't even access nor format that drive because it just hangs windows as soon as you try to access it.

**Comment by asampal** [comment]
@coxoperationsengineer have you tried uninstalling KB4579311 ?

**Comment by coxoperationsengineer** [comment]
> @coxoperationsengineer have you tried uninstalling KB4579311 ? BTW, for me `wsl -l` just seemed to hand and not return to the promt - true that I only waited a minute or so.

I have not tried uninstalling that update, only recently found your post, and thought maybe something was wrong with the drive at first, even though literally it would have had to have died during the update as I was using it up until that point.  I swapped to a new enclosure, swapped USB ports, etc still hangs when its plugged in and the only thing on it is my WSL2 distro of 20.04.  I will see if I can rollback that update tonight, but I have not had good luck with doing that in the past, but I'm not particularly attached to anything on this machine if things go south.

**Comment by asampal** [comment]
I think the KB was reissued and it looks like even with that KB update my WSL works. Closing.
