### ISSUE TITLE
Error 0x80070643 while updating wsl

### ISSUE THREAD

**Issue by secretchaudhary** [microsoft/WSL#6094]
It isn't updating. Every other windows update works perfectly fine and is updated. Tried troubleshooting but no gain....
There were some problems installing updates, but we'll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0x80070643)
![Screenshot (222)](https://user-images.githubusercontent.com/55019287/96054410-3e22f780-0e9f-11eb-81b7-f0d97f1d397e.png)
![Screenshot (223)](https://user-images.githubusercontent.com/55019287/96054419-4418d880-0e9f-11eb-8a12-84a92f473949.png)

**Comment by benhillis** [comment]
This isn't a WSL-specific issue.  I'd suggest filing an issue via feedback hub so this is routed to the correct team.

**Comment by claudioperez** [comment]
I was able to fix a similar problem by using a troubleshooter downloaded from the following link:
[https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed).

For anyone experiencing similar problems, there is a helpful issue thread here: [https://github.com/microsoft/WSL2-Linux-Kernel/issues/127](https://github.com/microsoft/WSL2-Linux-Kernel/issues/127).

**Comment by chrisdr2** [comment]
Thanks for that tip, it worked for me.

**Comment by secretchaudhary** [comment]
> I was able to fix a similar problem by using a troubleshooter downloaded from the following link:
> https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed.
> 
> For anyone experiencing similar problems, there is a helpful issue thread here: https://github.com/microsoft/WSL2-Linux-Kernel/issues/127.

Thanks... worked for me as well!

**Comment by maicol07** [comment]
@claudioperez @chrisdr2 @secretchaudhary what steps have you don eto fix the issue into the troubleshooter? (Which options and app from the list did you choose?)

**Comment by ksavelev** [comment]
> I was able to fix a similar problem by using a troubleshooter downloaded from the following link:
> https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed.
> 
> For anyone experiencing similar problems, there is a helpful issue thread here: https://github.com/microsoft/WSL2-Linux-Kernel/issues/127.

This advise also helped with similar issue `Windows Subsystem for Linux WSLg Preview - 1.0.19 - Error 0x80070643`

**Comment by laszlovandenhoek** [comment]
This problem started for me after manually installing a newer version of WSL2. Technically, there is nothing "wrong": Windows Update is just refusing to automatically downgrade from a manually installed version. Still, the error message was bothering me, so to fix this, I had uninstalled the _Windows Subsystem for Linux Update_ from the "Apps" panel in Windows Settings:

![image](https://user-images.githubusercontent.com/998449/120991479-fa5c6580-c781-11eb-9914-12b6cf720261.png)

After that, retrying Windows Update did work without the error.

**Comment by james-glenn** [comment]
worked for mee too

**Comment by samuelcarreira** [comment]
On **windows 11** I had the same issue
Couldn't install directly from the add / remove programs section


Solution:

1. download troubleshooter from microsoft https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab
2. Choose the option: cannot uninstall a program
3. Search in the list of programs the Windows Subsystem for Linux Update
4. Click Uninstall and wait for the process to be completed
3. Run Windows update again

**Comment by AndreaCicca** [comment]
> On **windows 11** I had the same issue Couldn't install directly from the add / remove programs section
> 
> Solution:
> 
> 1. download troubleshooter from microsoft https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab
> 2. Choose the option: cannot uninstall a program
> 3. Search in the list of programs the Windows Subsystem for Linux Update
> 4. Click Uninstall and wait for the process to be completed
> 5. Run Windows update again

Thanks, it works

**Comment by PapaEmeritusX** [comment]
> On **windows 11** I had the same issue Couldn't install directly from the add / remove programs section
> 
> Solution:
> 
> 1. download troubleshooter from microsoft https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab
> 2. Choose the option: cannot uninstall a program
> 3. Search in the list of programs the Windows Subsystem for Linux Update
> 4. Click Uninstall and wait for the process to be completed
> 5. Run Windows update again

Thank you! Could not resolve the issue for months

**Comment by chinkysight** [comment]
> On **windows 11** I had the same issue Couldn't install directly from the add / remove programs section
> 
> Solution:
> 
> 1. download troubleshooter from microsoft https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab
> 2. Choose the option: cannot uninstall a program
> 3. Search in the list of programs the Windows Subsystem for Linux Update
> 4. Click Uninstall and wait for the process to be completed
> 5. Run Windows update again

Thanks worked for me 💗💗💗

**Comment by titaneric** [comment]
> On **windows 11** I had the same issue Couldn't install directly from the add / remove programs section
> 
> Solution:
> 
> 1. download troubleshooter from microsoft https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab
> 2. Choose the option: cannot uninstall a program
> 3. Search in the list of programs the Windows Subsystem for Linux Update
> 4. Click Uninstall and wait for the process to be completed
> 5. Run Windows update again

Thank you! that helps
