### ISSUE TITLE
Windows Eclipse has issues accessing mounted WSL file system.

### ISSUE THREAD

**Issue by timcanham** [microsoft/WSL#6095]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1110]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1) Mount WSL file system root:

![image](https://user-images.githubusercontent.com/8086374/96055386-c4f0b980-0e38-11eb-824b-64d9bfe9d491.png)

2) Download and install Eclipse (Mine is 2020-09, C++ dev package)

3) Attempt to create a workspace on the Linux volume

4) Get error:

![image](https://user-images.githubusercontent.com/8086374/96055519-2add4100-0e39-11eb-8d6f-ec557ad6eb8d.png)

5) I tried creating the workspace on a Windows volume and then importing projects from the Linux volume, but I saw strange behaviors like empty directories, etc.

**WSL logs**: 

#  Expected behavior

I was expecting to get a normal Eclipse workspace or projects that I could edit.

# Actual behavior

See above...

**Comment by therealkenc** [comment]
Faceplants on LockFile. /dupe #5762. Work around would be a Samba share. Or wait on #938.

![image](https://user-images.githubusercontent.com/7049700/96062602-ef4b7280-0e4a-11eb-920d-a79e8eb915a4.png)
