### ISSUE TITLE
Unable to run msfdb on WSL2: System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by martin15560** [microsoft/WSL#6102]
# Environment

```none
Windows build number: Windows 10 10.0.18363 (x64-based)
Your Distribution version: Kali 2020.3
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (WSL 2)
```

# Steps to reproduce

`user@host:~$ sudo /etc/init.d/postgresql start`
`Starting PostgreSQL 12 database server: main.`
`user@host:~$ sudo msfdb init`
`System has not been booted with systemd as init system (PID 1). Can't operate.`
`Failed to connect to bus: Host is down`
`[+] Starting database`
`System has not been booted with systemd as init system (PID 1). Can't operate.`
`Failed to connect to bus: Host is down`

#  Expected behavior

Proper start of metasploit-framework with systemd and with connection to bus (host up).

# Actual behavior

System is not booted with systemd. Host is down.

**Comment by martin15560** [comment]
I have solved the issue by installing the systemd-genie.

**Comment by ruoshui-git** [comment]
@martin15560 Even though in Windows build 2004, you still get an error, but it looks like metasploit will work with postgreql on wsl now.

Here's my output:
```
msf6 > db_status
[*] Connected to msf. Connection type: postgresql.
msf6 >
```
And I'm on wsl kali:
```
PS > wsl -l -v
  NAME                   STATE           VERSION
* kali-linux             Running         2
```


You only have to install postgresql according to [Microsoft's instructions](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database).

And then start postgresql,
```
└─$ sudo service postgresql start
[sudo] password for known:
Starting PostgreSQL 13 database server: main.
```

And because I've tried `init` before but failed, now I need to run `reinit`. But if you never did this, I guess just run `init`:
```
└─$ sudo msfdb reinit
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Starting database
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Deleting configuration file /usr/share/metasploit-framework/config/database.yml
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[i] Database already stopped
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Starting database
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Creating database user 'msf'
[+] Creating databases 'msf'
┏━(Message from Kali developers)
┃
┃ This is a minimal installation of Kali Linux, you likely
┃ want to install supplementary tools. Learn how:
┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
┃
┗━(Run “touch ~/.hushlogin” to hide this message)
[+] Creating databases 'msf_test'
┏━(Message from Kali developers)
┃
┃ This is a minimal installation of Kali Linux, you likely
┃ want to install supplementary tools. Learn how:
┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
┃
┗━(Run “touch ~/.hushlogin” to hide this message)
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
```
And now things should work.

**Comment by martin15560** [comment]
> 
> 
> @martin15560 Even though in Windows build 2004, you still get an error, but it looks like metasploit will work with postgreql on wsl now.
> 
> Here's my output:
> 
> ```
> msf6 > db_status
> [*] Connected to msf. Connection type: postgresql.
> msf6 >
> ```
> 
> And I'm on wsl kali:
> 
> ```
> PS > wsl -l -v
>   NAME                   STATE           VERSION
> * kali-linux             Running         2
> ```
> 
> You only have to install postgresql according to [Microsoft's instructions](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database).
> 
> And then start postgresql,
> 
> ```
> └─$ sudo service postgresql start
> [sudo] password for known:
> Starting PostgreSQL 13 database server: main.
> ```
> 
> And because I've tried `init` before but failed, now I need to run `reinit`. But if you never did this, I guess just run `init`:
> 
> ```
> └─$ sudo msfdb reinit
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> [+] Starting database
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> [+] Deleting configuration file /usr/share/metasploit-framework/config/database.yml
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> [i] Database already stopped
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> [+] Starting database
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> [+] Creating database user 'msf'
> [+] Creating databases 'msf'
> ┏━(Message from Kali developers)
> ┃
> ┃ This is a minimal installation of Kali Linux, you likely
> ┃ want to install supplementary tools. Learn how:
> ┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
> ┃
> ┗━(Run “touch ~/.hushlogin” to hide this message)
> [+] Creating databases 'msf_test'
> ┏━(Message from Kali developers)
> ┃
> ┃ This is a minimal installation of Kali Linux, you likely
> ┃ want to install supplementary tools. Learn how:
> ┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
> ┃
> ┗━(Run “touch ~/.hushlogin” to hide this message)
> [+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
> [+] Creating initial database schema
> ```
> 
> And now things should work.

I tried to install: "postgresql-contrib" package but I got following:
``
``
``
``
``
``
``
``
``

**Comment by ruoshui-git** [comment]
> > @martin15560 Even though in Windows build 2004, you still get an error, but it looks like metasploit will work with postgreql on wsl now.
> > Here's my output:
> > ```
> > msf6 > db_status
> > [*] Connected to msf. Connection type: postgresql.
> > msf6 >
> > ```
> > 
> > 
> > And I'm on wsl kali:
> > ```
> > PS > wsl -l -v
> >   NAME                   STATE           VERSION
> > * kali-linux             Running         2
> > ```
> > 
> > 
> > You only have to install postgresql according to [Microsoft's instructions](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database).
> > And then start postgresql,
> > ```
> > └─$ sudo service postgresql start
> > [sudo] password for known:
> > Starting PostgreSQL 13 database server: main.
> > ```
> > 
> > 
> > And because I've tried `init` before but failed, now I need to run `reinit`. But if you never did this, I guess just run `init`:
> > ```
> > └─$ sudo msfdb reinit
> > System has not been booted with systemd as init system (PID 1). Can't operate.
> > Failed to connect to bus: Host is down
> > [+] Starting database
> > System has not been booted with systemd as init system (PID 1). Can't operate.
> > Failed to connect to bus: Host is down
> > [+] Deleting configuration file /usr/share/metasploit-framework/config/database.yml
> > System has not been booted with systemd as init system (PID 1). Can't operate.
> > Failed to connect to bus: Host is down
> > [i] Database already stopped
> > System has not been booted with systemd as init system (PID 1). Can't operate.
> > Failed to connect to bus: Host is down
> > [+] Starting database
> > System has not been booted with systemd as init system (PID 1). Can't operate.
> > Failed to connect to bus: Host is down
> > [+] Creating database user 'msf'
> > [+] Creating databases 'msf'
> > ┏━(Message from Kali developers)
> > ┃
> > ┃ This is a minimal installation of Kali Linux, you likely
> > ┃ want to install supplementary tools. Learn how:
> > ┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
> > ┃
> > ┗━(Run “touch ~/.hushlogin” to hide this message)
> > [+] Creating databases 'msf_test'
> > ┏━(Message from Kali developers)
> > ┃
> > ┃ This is a minimal installation of Kali Linux, you likely
> > ┃ want to install supplementary tools. Learn how:
> > ┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
> > ┃
> > ┗━(Run “touch ~/.hushlogin” to hide this message)
> > [+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
> > [+] Creating initial database schema
> > ```
> > 
> > 
> > And now things should work.
> 
> I tried to install: "postgresql-contrib" package but I got following:
> `Errors were encountered while processing:`
> ` udev`
> ` sudo`
> ` tpm-udev`
> ` kali-menu`
> ` xserver-xorg-core`
> ` xserver-xorg-video-nvidia-legaxy-390xx`
> ` libsane1:amd64`
> ` libsane1:i386`
> ` sane-utils`
> ` nvidia-legacy-390xx-driver`
> ` libsane:amd64`
> ` libsane:i386`
> `E: Sub-process /usr/bin/dpkg returned an error code (1)`
> 
> Do you know what should I do about that?

I've not seen that myself. Are you sure you're on wsl2 and Windows 2004 or higher? But I think it's not directly related to this systemd problem.

**Comment by scottvr** [comment]
My very simple fix to get this working easily was to do this (as root):

`mv /usr/bin/systemctl /usr/bin/systemctl.orig
cat > /usr/bin/systemctl <<EOF
#!/bin/bash

service $2 $1
EOF
chmod 755 /usr/bin/systemctl`


This obviously doesn't setup ystemd as your init sytem, but it saves you from having to change scripts (like msfdb) to work with the "service" syntax.
