### ISSUE TITLE
在WSL2中使用图形化界面VcXsrv时遇到桌面被占用的情况

### ISSUE THREAD

**Issue by yiwozhisha** [microsoft/WSL#6103]
以下是报错信息：

startxfce4
/usr/bin/startxfce4: X server already running on display 172.24.240.1
xrdb: Can't open display '172.24.240.1'
Unable to init server: Could not connect: 拒绝连接
xfce4-session: Cannot open display: .
输入 ‘xfce4-session --help’ 获取用法。

查看进程并未找到相关进程，将物理机重新启动问题依然未得到解决

**Comment by Waiginal** [comment]
> 以下是报错信息：
> 
> startxfce4 /usr/bin/startxfce4: X server already running on display 172.24.240.1 xrdb: Can't open display '172.24.240.1' Unable to init server: Could not connect: 拒绝连接 xfce4-session: Cannot open display: . 输入 ‘xfce4-session --help’ 获取用法。
> 
> 查看进程并未找到相关进程，将物理机重新启动问题依然未得到解决

事实上，这就是因为networkingMode=mirrored，使用镜像网络模式后，vEthernet (WSL (Hyper-V firewall))就失效了，你需要将export DISPLAY=后面的IP地址改成无线局域网适配器 WLAN的ipv4地址，你可能会发现export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0无法解决问题，因为它获取的是默认网关地址而不是ipv4地址。

blog:https://blog.csdn.net/Waigi/article/details/139586911
