### ISSUE TITLE
Returns error 0x803b0017 (HCN_E_DEGRADED_OPERATION) when installing distribution 

### ISSUE THREAD

**Issue by KurehaD** [microsoft/WSL#6107]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.19041.572]]
Your Distribution version: trying to install [Ubuntu 20.04 LTS] BUT FAILED
Whether the issue is on WSL 2 and/or WSL 1: [WSL 2]
```

# Steps to reproduce

launch the newly installed Linux distribution from https://www.microsoft.com/store/apps/9n6svws3rx71

# Actual behavior

```none
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x803b0017
Error: 0x803b0017 ????????????????

Press any key to continue...
```

**Comment by KurehaD** [comment]
### WSL logs
https://aka.ms/AAa0ioh

**Comment by licanhua** [comment]
@KurehaD The error is coming from network, and it has problem(Error: Entity is in invalid State) to create the network.
I don't know if [reset network](https://github.com/microsoft/WSL/issues/6089#issuecomment-711701697) will help resolve this.
