### ISSUE TITLE
Can't Start Win-KeX in Seamless Mode

### ISSUE THREAD

**Issue by martin15560** [microsoft/WSL#6108]
# Environment

```none
Windows build number: Windows 10 10.0.18363 (x64-based)
Your Distribution version: Kali 2020.3
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (WSL 2)
```

# Steps to reproduce

`user@host:~$ sudo apt update && sudo apt install kali-win-kex`
`user@host:~$ kex --sl`

        `Checking /root/.cache/sessions/xfce4-session-ip_address:0`
        `Enabling SL mode`
        `Waited 100 seconds for desktop, giving up`
        `Saving Win-KeX SL session`
        `Started Win-KeX SL`

#  Expected behavior

I would like the GUI environment to start on top of the Windows like here: [https://www.kali.org/docs/wsl/win-kex-sl/win-kex-sl.png](url)

# Actual behavior

There is nothing happening. I have tried to use "-w" parameter also but after 100 (300) seconds the process is closed. 
I can open Kali in Window Mode with `kex --win` but the SL Mode doesn't work.

**Comment by DHowett** [comment]
You’re probably going to need to seek support on the Win-KeX issue tracker. Graphical applications aren’t an officially supported scenario for WSL in this version of Windows (or any prior versions.)

**Comment by Biswa96** [comment]
> Graphical applications aren’t an officially supported scenario for WSL

https://twitter.com/craigaloewen/status/1308452901266751488 🤔

**Comment by DHowett** [comment]
“In this version of windows” my dude. Come on 😉

**Comment by martin15560** [comment]
# Environment

```none
Windows build number: Windows 10 version 2004 build 19041
```

# Steps to reproduce

`user@host:~$ sudo apt update && sudo apt install kali-win-kex`
`user@host:~$ kex --sl`

        `Checking /home/admin/.cache/sessions/xfce4-session-172.28.96.1:0`
        `Enabling SL mode`
        `Waited 100 seconds for desktop, giving up`
        `Saving Win-KeX SL session`
        `Started Win-KeX SL`

I have upgraded the Windows to 2004 version but I still can't launch the `kex --sl`.

Additionally I can't start apps from icons (desktop) in GUI environment (RDC via mstsc.exe) e.g. when I try to start the Wireshark I am asked for password, I will input the passwd but the app won't launch. I can start the app only from the 
![sc](https://user-images.githubusercontent.com/43177220/96366523-62553180-1148-11eb-8590-7c8f59f7a3ce.png)
terminal.

**Comment by sswwyyaatt** [comment]
Hi. I have this problem too. 

But i have log win-kexsl
```
Release: 1.20.1.4

OS: Windows NT 6.2 build 9200 (64-bit)
Contact: marha@users.sourceforge.net

LoadPreferences: C:\Users\user\AppData\Roaming\.XWinrc not found
LoadPreferences: Loading \\wsl$\kali-linux\usr\lib\win-kex\VcXsrv\system.XWinrc
```

Anybody can post this -> **.XWinrc**  here ?

**Comment by sswwyyaatt** [comment]
Try this -> **kex --sl --wtstart -s**

**Comment by martin15560** [comment]
I tried the `kex --sl --wtstart -s` command and reinstall also. But do not work for me. I don't get any error but the SL mode won't show up.

**Comment by sswwyyaatt** [comment]
> 
> 
> I tried the `kex --sl --wtstart -s` command and reinstall also. But does not work for me. I don't get any error but the SL mode won't show up.

Check your firewall and try to off default windows antimalware.

And don't forget -> `sudo kex stop` & `sudo kex kill` many many times..
And try to  `sudo kex --sl --wtstart -s`
And try to reboot windows 
And try to reboot windows many many times...  я не знаю что тут ещё можно сделать... ¯\_(ツ)_/¯

**Comment by martin15560** [comment]
Thank you for the advice. It was the firewall what was causing the problem.  I can use the `sudo kex --sl --wtstart -s` command but just with the firewall turned off. I have tried to set up the antivirus in the past for the WSL 2 but obviously with no success. 

Do you run win-kex without the firewall? Otherwise can you please tell me how did you set up the exception?

**Comment by sswwyyaatt** [comment]
> 
> 
> Thank you for the advice. It was the firewall what was causing the problem. I can use the `sudo kex --sl --wtstart -s` command but just with the firewall turned off. I have tried to set up the antivirus in the past for the WSL 2 but obviously with no success.
> 
> Do you run win-kex without the firewall? Otherwise can you please tell me how did you set up the exception?

In general, they seem to be automatically applied, but in principle I disable the firewall.
I could throw off a few articles about firewall exceptions, but they are in Russian, try google and install exceptions for **VcXsrv** and **pulseaudio**

**Comment by sswwyyaatt** [comment]
Created a new release in  [gitlab](https://gitlab.com/kalilinux/packages/kali-win-kex/-/issues/9) , sort of like a developer there. Don't close yet.

**Comment by Re4son** [comment]
@martin15560  and @sswwyyaatt,  

`Checking /root/.cache/sessions/xfce4-session-ip_address:0`  

Is an indication that your virtual network interface is not up.

Are you able to ping 8.8.8.8?

**Comment by sswwyyaatt** [comment]
> 
> 
> @martin15560 and @sswwyyaatt,
> 
> `Checking /root/.cache/sessions/xfce4-session-ip_address:0`
> 
> Is an indication that your virtual network interface is not up.
> 
> Are you able to ping 8.8.8.8?

```
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=106 time=18.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=106 time=18.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=106 time=18.6 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=106 time=18.7 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=106 time=18.6 ms
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4004ms
rtt min/avg/max/mdev = 18.326/18.582/18.705/0.135 ms
```
**and ifconfig (liniux wsl)**

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.33.71  netmask 255.255.240.0  broadcast 172.22.47.255
        inet6 fe80::215:5dff:fe8c:4235  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:8c:42:35  txqueuelen 1000  (Ethernet)
        RX packets 294149  bytes 69097263 (65.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 210038  bytes 595000646 (567.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2373  bytes 10529610 (10.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2373  bytes 10529610 (10.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**and ipconnfig (windows)** ### sorry for the Russian
```
Адаптер Ethernet Ethernet:

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::d8fd:b3e:fd84:728%16
   IPv4-адрес. . . . . . . . . . . . : 192.168.10.106
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . : 192.168.10.1

Адаптер Ethernet vEthernet (Default Switch):

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::5c20:222e:ea35:9007%19
   IPv4-адрес. . . . . . . . . . . . : 172.23.160.1
   Маска подсети . . . . . . . . . . : 255.255.240.0
   Основной шлюз. . . . . . . . . :

Адаптер Ethernet vEthernet (WSL):

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::e806:c842:29a5:b7e5%30
   IPv4-адрес. . . . . . . . . . . . : 172.22.32.1
   Маска подсети . . . . . . . . . . : 255.255.240.0
   Основной шлюз. . . . . . . . . :
```

**Comment by Re4son** [comment]
Hmmm, interesting. What's the output of:

`grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'`

**Comment by sswwyyaatt** [comment]
> grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'

```
$ grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'
grep: /etc/resolv.conf: No such file or directory
```

**Comment by Re4son** [comment]
Therein lies the problem.
I query /etc/resolv.conf to obtain the host's ip address to connect to

**Comment by Re4son** [comment]
@DHowett any more reliable way for us to obtain the host ip address?

**Comment by sswwyyaatt** [comment]
> 
> 
> Therein lies the problem.
> I query /etc/resolv.conf to obtain the host's ip address to connect to
I tried to reset windows network settings, now `grep -m 1 nameserver /etc/resolv.conf | awk '{print $ 2}'`
```
$ grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'
172.24.80.1
```

**Comment by Re4son** [comment]
Is it working now?

**Comment by sswwyyaatt** [comment]
If you try ` kex --sl`

![изображение](https://user-images.githubusercontent.com/8285144/96387819-94e54580-11ad-11eb-9c0a-d97468b164ba.png)

![изображение](https://user-images.githubusercontent.com/8285144/96387762-37e98f80-11ad-11eb-9ded-ec29e1771050.png)


I think it shouldn't work that way ...

**Comment by Re4son** [comment]
are there any instances of vcxsrv running already? maybe as root?

Now that the WSL2 /etc/resolv.conf issue is sorted, why don't we move this discussion to the kali-win-kex issue tracker?  
I have reopened the issue:  
https://gitlab.com/kalilinux/packages/kali-win-kex/-/issues/9

**Comment by sswwyyaatt** [comment]
We found a solution!
---
**1) Reset all firewall settings**
![изображение](https://user-images.githubusercontent.com/8285144/96489468-2b664500-1248-11eb-9f40-2df74d916382.png)

**2) Reinstalled the kali-win-kex **  <-- Perhaps this is not necessary.
```
sudo apt-get purge kali-win-kex
sudo apt-get install kali-win-kex
```
3) **run** `$ kex --sl` **and allow access (Private & Public)** 
![изображение](https://user-images.githubusercontent.com/8285144/96489504-34efad00-1248-11eb-84ed-2acde77bd2a5.png)

Thanks @Re4son !
