### ISSUE TITLE
WSL 2 Installation: Package is not supported by this Processor Type 

### ISSUE THREAD

**Issue by g13wm** [microsoft/WSL#6116]
I've just installed the latest rev of Docker on a new laptop and I'm getting below error.
I have downloaded the WSL 2 on another PC several days ago upon being prompted and the installation went smooth and I could use Docker without issue afterwards. 

Anyone has any idea of workaround for below error message? 
"The installation package is not supported by this processor type. Contact your product vendor"

#### Processor that has this Error Msg 
Intel(R) Xeon(R) E-2286M CPU @ 2.4GHz 2.40 

After running the installation package from the link, I get below error messge: 
![image](https://user-images.githubusercontent.com/71781872/96397806-e9fc7800-11fc-11eb-8fd9-c098f2131e0f.png)

**Comment by DHowett** [comment]
What is the filename of the MSI file you downloaded?

**Comment by licanhua** [comment]
If you downloaded wsl_update_arm64.msi, please switch to wsl_update_x64.msi. The first one is for ARM

**Comment by g13wm** [comment]
@licanhua @DHowett Thanks guys -resolved!

Didn't realize I've downloaded the wrong msi
wsl_update_arm64 >> wsl_update_x64

**Comment by justSteve** [comment]
I'm installing a new arm-based mobo and am getting that error when trying to run wsl_update_arm64.
