### ISSUE TITLE
Partial problem with wsl path.

### ISSUE THREAD

**Issue by AR-jpeg** [microsoft/WSL#6124]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Your Distribution version: Ubuntu Release: 20.04
Whether the issue is on WSL 2 and/or WSL 1: **WSL version 2** -- Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce
I had previously installed wsl 2, but by accident uninstall it. Next I  just followed the docs for installing wsl 2 from https://docs.microsoft.com/en-us/windows/wsl/install-win10, stuck on the 5th step.

**WSL logs**: 

#  Expected behavior

When I type in `wsl` in powershell / pwsh / cmd, it should just open my default distro.

# Actual behavior

Whenever I type in `wsl` in pwsh core 7, this is what happens

![image](https://user-images.githubusercontent.com/58893337/96636182-89e00180-12e2-11eb-8f4c-695c00122d47.png)

Note that System32 **is** in my path: 
![image](https://user-images.githubusercontent.com/58893337/96636381-d88d9b80-12e2-11eb-9697-d34ca9d78dd9.png)

**Comment by 0xbadfca11** [comment]
Maybe #223.

**Comment by AR-jpeg** [comment]
Aha! I fixed it... I had to uninstall pwsh core 7 x86 and install pwsh core 7 x64! For some reason, pwsh x86 was 32 bit.
