### ISSUE TITLE
Failed to Boot My Ubuntu20.04 in Windows Terminal since Upgrading from WSL1 to WSL2

### ISSUE THREAD

**Issue by dynastywind** [microsoft/WSL#6126]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Several minutes after computer startup, open Windows Terminal and then it starts to load my Ubuntu setting. (Do not open it immediately after signing into Windows)
2. It never ends loading.
3. Close Windows Terminal and open it again, it says missing profile settings with given GUID.
4. Open Powershell in Admin mode, type in `wsl -l` command, always running, never ends.

However, if I restart Windows and open Windows Terminal immediately after I signing into Windows, my Ubuntu can be booted in WSL2.

**WSL logs**: Don't know where to gather them.

#  Expected behavior

Should start my Ubuntu in WSL2 normally.

# Actual behavior

Always loading something, never ends.

# Hope someone can help！

**Comment by licanhua** [comment]
@dynastywind This is a problem I'm tracking, but never get a repro. Could you please help to collect the logs by [Feedback Hub](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).
After you reboot the machine, start Feedback Hub and start recording, re-produce the problem, then stop recording and submit the logs, and finally share the link in GitHub.

**Comment by therealkenc** [comment]
> Open Powershell in Admin mode, type in wsl -l command, always running, never ends.

Instructions for gathering logs is [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs). Please post the backlink to the feedback item here. Catching that `wsl -l` hang from a non-admin `cmd.exe` is the repro to catch (as opposed to starting Windows Terminal). [I think there is a dupe for the `wsl -l` hang somewhere, but the keywords make for a hopeless search.]

**Comment by dynastywind** [comment]
> > Open Powershell in Admin mode, type in wsl -l command, always running, never ends.
> 
> Instructions for gathering logs is [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs). Please post the backlink to the feedback item here. Catching that `wsl -l` hang from a non-admin `cmd.exe` is the repro to catch (as opposed to starting Windows Terminal). [I think there is a dupe for the `wsl -l` hang somewhere, but the keywords make for a hopeless search.]

Thank you for your support.
I've recorded some logs with FeedbackHub for my new feedback ticket but this ticket never shows up in My Feedback tab. So I tried several times (none of them appear right now), sorry. If you receive a ticket named with "**Failed to Boot My Ubuntu20.04 in Windows Terminal since Upgrading from WSL1 to WSL2**", this should be my ticket. If there's anything I can provide, please let me know.

**Comment by licanhua** [comment]
I didn't see the logs with this name

**Comment by therealkenc** [comment]
@dynastywind Does `wsl.exe --help` also hang?

**Comment by dynastywind** [comment]
> I didn't see the logs with this name

I saw them in *My feedback* now. Can you check again? There are totally 4 tickets there.

**Comment by dynastywind** [comment]
> @dynastywind Does `wsl.exe --help` also hang?

Works.

If I firstly open Windows Terminal to boot my Ubuntu and start to load, then I cannot use `wsl -l` in PowerShell again. Instead, if I use `wsl -l` before opening Windows Terminal, this works.

`wsl --help` always works, whether I open Windows Terminal or not.
