### ISSUE TITLE
Window Snapping Causes Horizontal Scroll Bar When Inside Programs

### ISSUE THREAD

**Issue by loganp** [microsoft/WSL#6131]
# Environment

Windows build number: 19041
Distribution version: Ubuntu 20.04
WSL Version: WSL 2

# Steps to reproduce 

**Window snapping with keyboard shortcuts required to reproduce**

1. Open program inside WSL e.g. vim
2. Snap window to full screen: meta+UP
3. Snap window to left or right half of screen: meta + LEFT/RIGHT
4. Minimize window: meta + DOWN
5. Un-minimize window: *any method*

#  Expected behavior

These actions should cause no changes to the window size properties

# Actual behavior

Minimizing causes a nonscrollable horizontal scroll bar to appear. 
Bar is drawn on top of window contents (in vim, the horizontal bar covers the bottom command line) obscuring the content completely

![image](https://user-images.githubusercontent.com/4074662/96769447-00890780-1394-11eb-9303-80cc9be1542c.png)

**Comment by therealkenc** [comment]
> If this is a console issue (a problem with layout, rendering, colors, etc.), please post the issue to the Terminal tracker: https://github.com/microsoft/terminal/issues
