### ISSUE TITLE
Windows updates disabled - Can't upgrade to WSL 2

### ISSUE THREAD

**Issue by bbgobie** [microsoft/WSL#6132]
# Environment
Windows 1909 Build 18363.1139
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
Stuck on Step 6 Install your Linux distribution of Choice.
I've tried both Ubuntu and Ubuntu 20.04 LTS.

When clicking install, I get an error from the app store.  On the details link it tells me I need to turn on Windows Update
Windows Update is disabled. You can repair Windows Update by running the Windows Update troubleshooter in Settings.
Code: 0x80070422

I'm unable to enable this as updates on my system are managed by corporate policy.

**WSL logs**: 

#  Expected behavior

As long as required Windows build version and whatever updates are necessary, WSL should install without requiring Windows Update to be enabled.
# Actual behavior
Windows Updates need to be enabled to install Ubuntu

**Comment by licanhua** [comment]
This is a question to Microsoft Store.
You can try to download https://wsldownload.azureedge.net/Ubuntu_2004.2020.424.0_x64.appx and then install the appx manually.
If you are using ARM, please change the name to Ubuntu_2004.2020.424.0_ARM64.appx
