### ISSUE TITLE
Installed Ubuntu from rootfs, no /run/resolvconf/resolv.conf is generated

### ISSUE THREAD

**Issue by c-goes** [microsoft/WSL#6136]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Install Ubuntu as rootfs instead of appx (https://wiki.ubuntu.com/WSL#Installing_Ubuntu_on_WSL_via_rootfs) `wsl --import <DistributionName> <InstallLocation> <FileName>`
2. Start using `wsl -d <DistributionName>`
3. No `/run/resolvconf/resolv.conf` is present. Instead there is a link `lrwxrwxrwx 1 root root 39 Oct 16 23:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`.

**WSL logs**: 

#  Expected behavior

Ubuntu installed via rootfs should have DNS configuration like Ubuntu installed from appx.

Example from appx-Installation:

```
lrwxrwxrwx 1 root root 29 Oct  5 11:31 /etc/resolv.conf -> ../run/resolvconf/resolv.conf
```

# Actual behavior

 `/run/resolvconf/resolv.conf` isn't present in the filesystem from Ubuntu installed from rootfs.

`lrwxrwxrwx 1 root root 39 Oct 16 23:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`

**Comment by sirredbeard** [comment]
/etc/resolv.conf should be auto-generated for you reach time you launch WSL unless you have manually disabled that option in /etc/wsl.conf.

**Comment by Biswa96** [comment]
OP means that `/etc/resolv.conf` already is a symbolic link to `../run/systemd/resolve/stub-resolv.conf` in the tarball provided by canonical. It should not present to be automatically generated by WSL's `init` blob. For example, see this file https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-wsl.rootfs.tar.gz

**Comment by c-goes** [comment]
Correct, this is was I meant @Biswa96 . I found it confusing that WSL rootfs image is different from the appx-Release.
I haven't disabled anything in `/etc/wsl.conf`.

**Comment by sirredbeard** [comment]
I don't think we made a change to livecdrootfs that would have done this, I will have to investigate.
