### ISSUE TITLE
Issues while enabling SSH in WSL2 

### ISSUE THREAD

**Issue by Maverick4902** [microsoft/WSL#6138]
I have been using Ubuntu 20.04 on WSL2. I have successfully installed SSH in it, but while trying to connect with my IP Address, it shows the error "ssh: connect to host <IP Address> port 22: connection refused". I have already tested the same installation procedure in Ubuntu 20.04 and it worked great. What is wrong with WSL or WSL2?

**Comment by Biswa96** [comment]
Firewall?

**Comment by benhillis** [comment]
Please fill out the issue template.
