### ISSUE TITLE
WSL2 Images created on Hypervisor fail on Physical PC

### ISSUE THREAD

**Issue by falloutphil** [microsoft/WSL#6140]
# Environment

v2004.19041.264
WSL2

I've been doing a deployment of a WSL2 image - and have seen this issue consistently across the 5 desktop PCs tested.  I have tested across 6 Hypervisors and seen no issue there.

# Steps to reproduce

Install Ubuntu 18.04 on a Hypervisor hosted Windows virtual PC.  Using WSL2.
export it to a tar file
Move to a physical desktop using the same version of Windows/WSL2 - and import the image.

#  Expected behavior

The image is usable just as if I import the image onto another Hypervisor.

# Actual behavior

Image fails to load a random amount of times, before finally loading:

C:\phil>wsl --import My-Ubuntu-18.04 wsl_distro C:\phil\My_v2.tar.gz

C:\phil>wsl
The Windows Subsystem for Linux instance has terminated.

C:\phil>wsl
The Windows Subsystem for Linux instance has terminated.

C:\phil>wsl
The Windows Subsystem for Linux instance has terminated.

C:\phil>wsl -l -v
  NAME               STATE           VERSION
* My-Ubuntu-18.04    Stopped         2

C:\phil>wsl
The Windows Subsystem for Linux instance has terminated.

C:\phil>wsl
root@DESKTOP81:/mnt/c/phil#

There is a workaround of sorts, that so far seems to work - if you user --version 1 on the import and then:
wsl --set-version My-Ubuntu-18.04 2

It seems to work OK.

Other people are eluding to similar behavior, but tickets are being closed with suggestions for workaround, but no root cause:
https://github.com/microsoft/WSL/issues/5318

**Comment by sirredbeard** [comment]
> Hypervisor hosted Windows virtual PC.

Which hypervisor?

Sounds like a nested virtualization issue.

> if you user --version 1 on the import and then:
wsl --set-version My-Ubuntu-18.04 2 It seems to work OK.

So you can import an image as WSL 1 and convert it to WSL 2, and when you run 'wsl' it will boot into the WSL 2 image just fine?

**Comment by falloutphil** [comment]
Thanks for the reply.

> Which hypervisor?
> 

I'll have to follow-up on this - will confirm shortly.


> So you can import an image as WSL 1 and convert it to WSL 2, and when you run 'wsl' it will boot into the WSL 2 image just fine?

Yes exactly this - the orignal image is WSL2 and exported from a hypervisor.  if I import this image WSL2 and then run the image always has trouble starting up (The Windows Subsystem for Linux instance has terminated.) - but if I persist it will normally work after 3 or 4 goes without changing anything..... but if I import the exact same image as WSL1, and then covert to WSL2, so far I have so had no problem starting it first time.

**Comment by falloutphil** [comment]
> > Hypervisor hosted Windows virtual PC.
> 
> Which hypervisor?
> 

Windows Hyper-V server 2019
