### ISSUE TITLE
cant run wsl2 in a virtual Windows 10 Pro 2004 created from qemu

### ISSUE THREAD

**Issue by baslr** [microsoft/WSL#6141]
# Environment

```none
Host: Debian sid on Intel CPU
Windows build number: `Versio 2004 (OS Build 19041.572`
Your Distribution version: Debian from Windows Store
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```
![Screenshot_2020-10-23_08-33-46](https://user-images.githubusercontent.com/1494154/97052278-fd9f3a00-1580-11eb-9377-d1a97e3eaab2.png)

# Steps to reproduce

1. download windows 10 iso
2. create qemu image with `qemu-img create -f qcow2 windows10.img 50G`
3. run qemu-system-x86_64 with `-cpu host -accel kvm` to get all feature from the cpu
4. install windows
5. run steps from https://docs.microsoft.com/en-us/windows/wsl/install-win10
6. install debian from Store
7. run `wsl --set-default-version 2`
8. run `debian`

#  Expected behavior
wsl2 setup should run normal

# Actual behavior
```
> systeminfo
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

> debian
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

Press any key to continue...

```

![Screenshot_2020-10-22_15-16-12](https://user-images.githubusercontent.com/1494154/97053635-99ca4080-1583-11eb-8635-b24593fe7ff7.png)
guest vm cpu features.

![Screenshot_2020-10-22_15-16-29](https://user-images.githubusercontent.com/1494154/97053639-9c2c9a80-1583-11eb-8b5f-e59b4605a035.png)
guest vm cpu features.

![Screenshot_2020-10-22_15-16-47](https://user-images.githubusercontent.com/1494154/97053644-9d5dc780-1583-11eb-82e6-5e3eba0766dc.png)
guest vm cpu features.

![Screenshot_2020-10-22_15-17-09](https://user-images.githubusercontent.com/1494154/97053646-9df65e00-1583-11eb-9cb5-3eaa3821b7e5.png)
guest taskmanager.

![Screenshot_2020-10-22_15-18-12](https://user-images.githubusercontent.com/1494154/97053647-9e8ef480-1583-11eb-8271-1795dd9573f5.png)
running hyper-v services in guest

![Screenshot_2020-10-22_15-22-28](https://user-images.githubusercontent.com/1494154/97053649-9e8ef480-1583-11eb-9243-775a79b4dca4.png)
tried to run a virtual machine in the guest

![Screenshot_2020-10-22_15-37-11](https://user-images.githubusercontent.com/1494154/97053650-9f278b00-1583-11eb-81e9-a11a19efd962.png)
error from the error log in the virtual machine

![Screenshot_2020-10-22_16-03-22](https://user-images.githubusercontent.com/1494154/97053651-9fc02180-1583-11eb-9742-1565380a9690.png)
cpu features of a debian guest with the same qemu start config

![Screenshot_2020-10-22_16-06-21](https://user-images.githubusercontent.com/1494154/97053656-a189e500-1583-11eb-9760-7d2b22cc4fbc.png)
host cpu features

I don't know what else to enable to get wsl2 running.

**Comment by sirredbeard** [comment]
Maybe try:
- running QEMU with --enable-KVM
- specifying a chipset closer to yours with --machine or even just kvm64
- passing as many virtualization related flags as possible through to your guest, I see vmx above, but ideally you would have more like: '+vmx-activity-hlt,+vmx-cr3-load-noexit,+vmx-cr3-store-noexit,+vmx-cr8-load-exit,+vmx-cr8-store-exit,+vmx-desc-exit,+vmx-entry-ia32e-mode,+vmx-entry-load-efer,+vmx-entry-load-pat,+vmx-entry-noload-debugctl,+vmx-ept,+vmx-ept-1gb,+vmx-ept-2mb,+vmx-ept-execonly', and so on, see [here](https://pastebin.ubuntu.com/p/GqHbMQSN99/)

**Comment by baslr** [comment]
Hi @sirredbeard,

I run the guest with `-cpu host` which is
```
$ qemu-system-x86_64 -cpu help
Available CPUs:
[...]
x86 host                  KVM processor with all supported host features
[...]
Recognized CPUID flags:
  vmx vmx-activity-hlt
  vmx-activity-shutdown vmx-activity-wait-sipi vmx-apicv-register
  vmx-apicv-vid vmx-apicv-x2apic vmx-apicv-xapic vmx-cr3-load-noexit
  vmx-cr3-store-noexit vmx-cr8-load-exit vmx-cr8-store-exit vmx-desc-exit
  vmx-encls-exit vmx-entry-ia32e-mode vmx-entry-load-bndcfgs
  vmx-entry-load-efer vmx-entry-load-pat vmx-entry-load-perf-global-ctrl
  vmx-entry-load-rtit-ctl vmx-entry-noload-debugctl vmx-ept vmx-ept-1gb
  vmx-ept-2mb vmx-ept-advanced-exitinfo vmx-ept-execonly vmx-eptad
  vmx-eptp-switching vmx-exit-ack-intr vmx-exit-clear-bndcfgs
  vmx-exit-clear-rtit-ctl vmx-exit-load-efer vmx-exit-load-pat
  vmx-exit-load-perf-global-ctrl vmx-exit-nosave-debugctl
  vmx-exit-save-efer vmx-exit-save-pat vmx-exit-save-preemption-timer
  vmx-flexpriority vmx-hlt-exit vmx-ins-outs vmx-intr-exit vmx-invept
  vmx-invept-all-context vmx-invept-single-context
  vmx-invept-single-context vmx-invept-single-context-noglobals
  vmx-invlpg-exit vmx-invpcid-exit vmx-invvpid vmx-invvpid-all-context
  vmx-invvpid-single-addr vmx-io-bitmap vmx-io-exit vmx-monitor-exit
  vmx-movdr-exit vmx-msr-bitmap vmx-mtf vmx-mwait-exit vmx-nmi-exit
  vmx-page-walk-4 vmx-page-walk-5 vmx-pause-exit vmx-ple vmx-pml
  vmx-posted-intr vmx-preemption-timer vmx-rdpmc-exit vmx-rdrand-exit
  vmx-rdseed-exit vmx-rdtsc-exit vmx-rdtscp-exit vmx-secondary-ctls
  vmx-shadow-vmcs vmx-store-lma vmx-true-ctls vmx-tsc-offset
  vmx-unrestricted-guest vmx-vintr-pending vmx-vmfunc
  vmx-vmwrite-vmexit-fields vmx-vnmi vmx-vnmi-pending vmx-vpid
  vmx-wbinvd-exit vmx-xsaves vmx-zero-len-inject vpclmulqdq waitpkg
  [...]
```
`host` means the guest has access to all the hosts cpu features.
As I understand it `vmx` includes all the `vmx-*` options. Thats why in `cat /proc/cpuinfo` is only `vmx` shown.
I will retry with all additional vmx-* options. I can imagine that all the `vmx-*` options are there to enable live migration to another host, so you have a strict vmx subset that source host and target host support.

Regarding kvm, I am sorry, I forgot to add `kvm` to `-accel`.

**Comment by baslr** [comment]
@sirredbeard I tried it with all additional `vmx-*` options. No luck. I also updated the guest to Windows 10 20H2.
The error message is still the same.

**Comment by GowthamKudupudi** [comment]
I'm also unable to reboot qemu windows guest after enabling Hyper-V; I had restore to previous restore point to boot
```
C:\Users\Gowtham>systeminfo

Host Name:                 BLIZLAC
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Gowtham
Registered Organization:
Product ID:                00331-10000-00001-AA259
Original Install Date:     13-08-2021, 23:49:47
System Boot Time:          18-08-2021, 21:16:37
System Manufacturer:       QEMU
System Model:              Standard PC (Q35 + ICH9, 2009)
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 12 GenuineIntel ~3696 Mhz
BIOS Version:              EFI Development Kit II / OVMF 0.0.0, 06-02-2015
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              00004009
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     16,379 MB
Available Physical Memory: 11,961 MB
Virtual Memory: Max Size:  19,323 MB
Virtual Memory: Available: 12,641 MB
Virtual Memory: In Use:    6,682 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\BLIZLAC
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5004342
                           [02]: KB5001030
                           [03]: KB5003792
                           [04]: KB5004567
                           [05]: KB5005190
                           [06]: KB5005668
Network Card(s):           1 NIC(s) Installed.
                           [01]: Red Hat VirtIO Ethernet Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.122.1
                                 IP address(es)
                                 [01]: 192.168.122.2
                                 [02]: fe80::5508:2df1:7672:c6d9
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by Necktwi** [comment]
I too tried all the options but couldn't reboot after `wsl --install`.
