### ISSUE TITLE
WSL2 networking fail with Windows Shadowsocks

### ISSUE THREAD

**Issue by Aaronself** [microsoft/WSL#6143]
# Environment
my windows is Win2004 19041.572

After I install the Ubuntu-18.04 for WSL2. I try the `sudo apt-get update` and i didn't not work.
Then I try to change the apt sources from mirrors.aliyun.com and i didn't not work too.
so i search in the Internet and find that someone say it maybe the DNS problem, but i try to
`ping www.baidu.com` and `ping 111.1.167.116` it can work.

and now i will show you the what it returns when `sudo apt-get update`
`Err:1 http://mirrors.aliyun.com/ubuntu bionic InRelease
    connection failed [IP: 183.146.18.248 80]
Err:2 http://mirrors.aliyun.com/ubuntu bionic-security InRelease
    connection failed [IP: 183.146.18.248 80]
Err:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease
    connection failed [IP: 183.146.18.248 80]
Err:4 http://mirrors.aliyun.com/ubuntu bionic-proposed InRelease
    connection failed [IP: 183.146.18.248 80]
Err:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease
    connection failed [IP: 183.146.18.248 80]
Reading package lists....Done
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic/InRelease Connection failed [IP: 183.146.18.248 80]
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-security/InRelease Connection failed [IP: 115.233.31.228.80]
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-updates/InRelease Connection failed [IP: 115.233.31.229 80]
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-proposed/InRelease Connection failed [IP: 183.131.210.242 80]
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-backports/InRelease Connection failed [IP: 183.131.210.250 80]
W: Some index fiels failed to download. Then have been ignored, or old ones used instead`

**Comment by sirredbeard** [comment]
Can you ping other websites from WSL?

Do you have third-party security or firewall software installed?

**Comment by Aaronself** [comment]
yes I try to `ping www.baidu.com` and i did work
I use the ShadowsocksR in windows, and i just use windows defender, dose it matter?

**Comment by EmanekaT** [comment]
Should be the same as https://github.com/microsoft/WSL/issues/4285. 
Try `echo \"nameserver 8.8.8.8\" | sudo tee /etc/resolv.conf > /dev/null`

**Comment by Aaronself** [comment]
do you mean the DNS problem?
i try to add these lines in my `/etc/resolv.conf`
`nameserver 8.8.8.8
nameserver 5.5.5.5
nameserver 4.4.4.4`
but it did not work. sad story

**Comment by EmanekaT** [comment]
I encountered the same error and changing dns fixed it. I guess it's different then.

**Comment by Aaronself** [comment]
thank you, but maybe i have a different problem

**Comment by todes-l33ter** [comment]
Ah friend of mine had the same issue, i told him to try it without sudo - and it worked

**Comment by Aaronself** [comment]
i tried but it shows
`Reading package lists... Done`
`E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)`
`E: Unable to lock directory /var/lib/apt/lists/`
`W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)`
`W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)`

**Comment by therealkenc** [comment]
> [ShadowsocksR](https://en.wikipedia.org/wiki/Shadowsocks)

Effectively dupe #4402 ([message](https://github.com/microsoft/WSL/issues/4402#issuecomment-520333571)) #4507. Do the proxy inside WSL2.

Whether this is discussion/by-design is hard to say. Depends on how WSL2 networking writ large plays out. We can leave this one an open LZ for the shadowsocks scenario (the two above are closed).

**Comment by Aaronself** [comment]
i only use the SSR in windows.
In WSL, i just download the ubuntu in microsoft store and install it. change the `/etc/apt/sources.list` and change the `/etc/resolv.conf` file， but i find the `sudo apt-get update` did not work. 
So i attempt to convert the wsl2 to wsl1. In wsl1, it can communicate with the windows network instead of an other IP address
