### ISSUE TITLE
USB for serial devices

### ISSUE THREAD

**Issue by JonMcG** [microsoft/WSL#6144]
Do you have a timeline for implementing serial USB devices in WSL?

**Comment by shaggygi** [comment]
Referencing #4322

**Comment by JonMcG** [comment]
I saw that but mine is a specific question, as it looks like it is being ignored by MS.

**Comment by sirredbeard** [comment]
Duplicating an existing feature request doesn't make it make happen quicker, it just clutters up the issues section and means less time on features.
