### ISSUE TITLE
Cannot connect to Internet from WSL2

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#6146]
The issue described in https://github.com/microsoft/WSL/issues/5821 is showing up again!
Although, the adapters don't show up as disconnected, still `ping example.com` does not work anymore.

Windows 20241

**Comment by ad-on-is** [comment]
Ok, I just re-enabled Hyper-V and Windows Hypervisor Platform and everything works again

**Comment by nacho-marin** [comment]
I recently moved my WSL distros to WSL2, suffered the network problem and noticed I was in stable Version 2004. I updated to the latest release in the official/stable channel (Version 20H2) this morning and everything is working now. 

Maybe trying to move to 20H2 can fix the problem but I do not know how hard it is to move from a more recent Developer Program version to the current stable one.

**Comment by ad-on-is** [comment]
I figured that BitDefenders Firewall is blocking all WSL2 traffic.
