### ISSUE TITLE
WSL mount need admin but target user-based distro

### ISSUE THREAD

**Issue by moutonjr** [microsoft/WSL#6147]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.572]
Your Distribution version: Debian 10.6
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce

Trying to mount SD partition disk (ext-4 formatted) in Linux using https://docs.microsoft.com/fr-fr/windows/wsl/wsl2-mount-disk .

## Running as admin:
```powershell
PS C:\WINDOWS\system32> wsl
Le sous-système Windows pour Linux n'a pas de distributions installées.
Vous pouvez installer les distributions en visitant le Microsoft Store :
https://aka.ms/wslstor
```

## Running as user:
```powershell
PS C:\Users\USER> wsl --mount dummy
Option de ligne de commande non valide : --mount
Copyright (c) Microsoft Corporation. Tous droits réservés.

Utilisation: wsl.exe [Argument] [Options...] [CommandLine]
...manpage...
```

#  Expected behavior

Be able to mount drives in my user-based WSL instance

# Actual behavior

* Either WSL runs in admin mode (not a best practice)
* Or Unable to mount drives.

**Comment by craigloewen-msft** [comment]
Hi @moutonjr , you're on a build of Windows that does not support `wsl --mount` (You're on Windows 10 build 19041, you need to be on build 20211 or higher to have access to the `wsl --mount` command!). 

Please upgrade your Windows build and try using --mount again! You can upgrade by joining the Windows Insiders program and using the 'Dev Channel'. 

I'll update the documentation to make the build number required for `wsl --mount` clearer. Thanks for filing!

**Comment by FormindGMO** [comment]
Hi, please reopen, @hadeutscher is right indeed. Sorry for wsl1 still remaining, but he's right.
```
wsl --mount \\.\PHYSICALDRIVE1
L’accès administrateur est nécessaire pour monter un disque.
```
(pardon French)

**Comment by FormindGMO** [comment]
@craigloewen-msft
