### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80072736

### ISSUE THREAD

**Issue by CARASO** [microsoft/WSL#6149]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
# Steps to reproduce

**WSL logs**: 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80072736
Error: 0x80072736 ????????????????

Press any key to continue...
#  Expected behavior

Install Ubuntu18.04 LTS
# Actual behavior

Can't install Ubuntu18.04LTS

**Comment by therealkenc** [comment]
`WSAENOTSOCK` (`0x80072736`) is novel. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by zazomazzo** [comment]
Had the same error. with Ubuntu20.04 LTS and Debian.
After I disconnected my running NordVPN connection it worked fine.

**Comment by Hotrod369** [comment]
> Had the same error. with Ubuntu20.04 LTS and Debian. After I disconnected my running NordVPN connection it worked fine.

I had the same issue and after disconnecting NORD VPN all is well.

**Comment by Travelsteve** [comment]
I can also confirm that NORDVPN does not play nicely with any Linux Distros in Windows 11 via wsl. Same error 0x80072736 error about a Socket...

**Comment by facundofacio** [comment]
Same error, solved disabling Nord VPN temporarily

**Comment by Big0290** [comment]
Same error, solved disabling Nord VPN temporarily

**Comment by pedromello** [comment]
Same error here, solved by stopping the VPN

**Comment by killshot13** [comment]
Ditto. Same error, same solution. I actually filed a support ticket with Nord about this issue, but that was before reading this thread. I will mention it to them and see if they have any appetite to support a fix or at least look into it.🤷‍♂️ If anything comes of it, I will post an update here.

**Comment by Emi1305** [comment]
> Ditto. Same error, same solution. I actually filed a support ticket with Nord about this issue, but that was before reading this thread. I will mention it to them and see if they have any appetite to support a fix or at least look into it.🤷‍♂️ If anything comes of it, I will post an update here.
> 
> Also, it is worth noting this problem is not caused by the `Threat Protection` service NordVPN provides. I told Nord to trust my current network (this auto-disconnects the VPN), and WSL2 worked fine even with `File Protection` and `Web Protection` still enabled.

Disabling split tunneling on Nord seemed to fix it for me

**Comment by yapcibello** [comment]
> > Ídem. Mismo error, misma solución. De hecho, presenté un ticket de soporte a Nord sobre este problema, pero eso fue antes de leer este hilo. Se lo mencionaré y veré si tienen algún deseo de apoyar una solución o al menos investigarla. 🤷‍♂️ Si surge algo, publicaré una actualización aquí.
> > Además, vale la pena señalar que este problema no es causado por el `Threat Protection`servicio que brinda NordVPN. Le dije a Nord que confiara en mi red actual (esto desconecta automáticamente la VPN) y WSL2 funcionó bien incluso con `File Protection`y `Web Protection`aún habilitado.
> 
> **Desactivar el túnel dividido en Nord pareció solucionarlo**

Confirmado
