### ISSUE TITLE
bind mount fails on WSL2

### ISSUE THREAD

**Issue by stefanloerwald** [microsoft/WSL#6150]
# Environment

```none
Windows build number:  Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

1. Create a directory `/foo`
2. Create a directory `/mnt/wsl/foo`
3. Verify that you can `sudo mount --bind /foo/ /mnt/wsl/foo`
4. This mount bind will be lost on reboot, so I want to have that in `/etc/fstab`
5. Add line `/foo /mnt/wsl/foo none bind 0 0` to `/etc/fstab`
6. Restart wsl
7. Notice that this didn't do anything, there is no `mnt/wsl/foo` :-(

#  Expected behavior

I need a way to bind this permanently, as this seems to be the only way to make kubernetes see directories with docker-for-win.

# Actual behavior

I lose the binding every time wsl restarts.

**Comment by therealkenc** [comment]
> Create a directory /mnt/wsl/foo

![image](https://user-images.githubusercontent.com/7049700/97212069-1f651080-177d-11eb-996d-f9184241a141.png)

/dupe #5851
