### ISSUE TITLE
Set default user in imported WSL distro

### ISSUE THREAD

**Issue by alannt777** [microsoft/WSL#6151]
**Is your feature request related to a problem? Please describe.**
Is there a way to change the default user in an exported distro. The docs says to use "distro.exe config ..." which is not really a applicable 

**Describe the solution you'd like**
Be able to change the default user using wsl.exe

**Describe alternatives you've considered**
There is this [superuser post](https://superuser.com/questions/1566022/how-to-set-default-user-for-manually-installed-wsl-distro) that tells how to do this by using regedit.exe
But I don't want to mess around with the registry.

##### I have never used linux apart from WSL. Keep up the great work!

cc @craigloewen-msft

**Comment by craigloewen-msft** [comment]
There is an option to set the default user by modifying the content in /etc/wsl.conf!

if you add: 
```
[user]
default=<yourUsername, e.g: craig for me>
```

You can view our docs on this here: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user

Where did you see the docs describing this? I'll update them! :)

**Comment by alannt777** [comment]
@craigloewen-msft sorry because I was too lazy to check the docs and believed that guy who asked that question. He said that the docs said to use 'distro.exe config..'

I should have checked the docs. Sorry for the inconvenience that you experienced because of my laziness.

**Comment by craigloewen-msft** [comment]
No problem! :) Thank you for filing the issue!
