### ISSUE TITLE
Reopen: ls: cannot access '/mnt/c': Input/output error

### ISSUE THREAD

**Issue by kwint** [microsoft/WSL#6161]
This issue: https://github.com/microsoft/WSL/issues/4377 has been bugging me and quite some others for quite some time now.
Somehow the issue got closed, but the issue till exists, or at least exists again.

I'm making this issue to get some attention to this issue, since it seems to have gotten under the radar because it was closed.

Feel free to remove or close this issue whenever, sorry for the spam

**Comment by therealkenc** [comment]
What is the output of `cmd.exe /c ver`.

**Comment by daniluk4000** [comment]
> 
> 
> What is the output of `cmd.exe /c ver`.

Mine is: Microsoft Windows [Version 10.0.19041.572]

**Comment by kwint** [comment]
`Microsoft Windows [Version 10.0.19042.608]`

**Comment by kwint** [comment]
Altough probabaly relevant, the issue #6174  is not the same as the issue linked in op #4377. wsl --shutdown does fix it for all the users commenting in 4377
