### ISSUE TITLE
Autocomplete moves cursor to the next line. 

### ISSUE THREAD

**Issue by nd7141** [microsoft/WSL#6164]
# Environment

```none
Windows build number: Version 10.0.18362.1139
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020
```

# Steps to reproduce

When I connect to the remote environment via WSL and try to use autocomplete, my cursor moves to the next line and there is a visible break in the path, which hinders readability. See below. 

![image](https://user-images.githubusercontent.com/4607709/97460322-effd0200-193c-11eb-85de-89444e1a978f.png)

Is it a known issue? How can I fix it? What it can be related to?

**Comment by Biswa96** [comment]
Is that in Command Prompt? Try to use a terminal emulator like mintty, putty, ConEmu etc.

**Comment by nd7141** [comment]
Can you please elaborate? I connect via WSL to a remote machine.
