### ISSUE TITLE
windows clipboard not working on WSL 2 - Debian

### ISSUE THREAD

**Issue by masnm** [microsoft/WSL#6165]
# Environment
Windows:
        Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

WSL Debian:
        PRETTY_NAME="Debian GNU/Linux 10 (buster)"
        NAME="Debian GNU/Linux"
        VERSION_ID="10"
        VERSION="10 (buster)"
        VERSION_CODENAME=buster

WSL 2
        Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

# Steps to reproduce

Command:        cat ./main.cpp | clip.exe
Trying to copy the content of a file from wsl debian to my windows clipboard.

#  Expected behavior

Expected to copied the content on the clipboard

# Actual behavior

Output:            -bash: clip.exe: command not found

**Comment by therealkenc** [comment]
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> Output: -bash: clip.exe: command not found

/dupe #5779 ([message](https://github.com/microsoft/WSL/issues/5779#issuecomment-689299875))
