### ISSUE TITLE
WSL Enabled Ubuntu Not Working

### ISSUE THREAD

**Issue by SleepBag123** [microsoft/WSL#6167]
Hi, 
I have enabled the WSL feature on WIN 10 but still I get this screen 
![Capture](https://user-images.githubusercontent.com/72369801/97526435-1ec3b880-19cf-11eb-977e-0b31bc4e0bbd.PNG)
Here is the optional features window
![Capture](https://user-images.githubusercontent.com/72369801/97526642-9396f280-19cf-11eb-82c2-41b6148d1939.PNG)

**Comment by therealkenc** [comment]
Enable Hypervisor Platform.

**Comment by licanhua** [comment]
If you use powershell to turn this feature on, please reboot the machine.
Reboot is required to make it take into effect
