### ISSUE TITLE
On drvfs 'cp -al' sometimes fails to hard link symlink-to-dir. 'linkat' returns EISDIR

### ISSUE THREAD

**Issue by JoshNoel** [microsoft/WSL#6171]
# Environment

```none
Windows build number: 19041.508
Distribution Version: Ubuntu 18.04
WSL2
```
# Steps to reproduce 

Attempting yocto build process on NTFS partition through wsl2 fails due to error copying directory tree through ```cp -alf```.

For others reference (irrelevant to bug): on ```petalinux-build``` for some recipes we see error like the following:
> 'cp -aflv --preserve=xattr ./* /mnt/pool/data/Avnet/petalinux/projects/ultra96v2_oob_2020_1/build/tmp/sysroots-components/x86_64/icu-native' returned non-zero exit status 1
cp: cannot create hard link .....

Debugging has led to differing ```linkat``` behavior on drvfs vs lxfs. This seems unrelated to access errors seen in #5108. Smaller test case repro steps below

On an NTFS filesystem mounted through drvfs "cp -al" does not always work. It completes without error on lxfs partition.

With the following working directory structure "cp -al testsrc/* testdst" fails sometimes (depending on root location?) in drvfs.

.-------------------------------------------
├── testdst
└── testsrc
    ├── dir
    │   └── file.txt
    └── dir_link -> dir/

.--------------------------------------------
$ cp -al testsrc/* testdst
cp: cannot create hard link 'testdst/dir_link' to 'test/dir_link': Is a directory
$ cp -al testsrc/dir_link testdst
cp: cannot create hard link 'testdst/dir_link' to 'test/dir_link': Is a directory
.--------------------------------------------
drvfs mount options:
H: on /mnt/pool type 9p (rw,relatime,dirsync,aname=drvfs;path=H:;metadata;uid=1000;gid=1000;case=dir;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=3,wfd=3)
.--------------------------------------------

I was unable to produce this error on lxfs. On the same drvfs mount I was **only able to produce this error for some working directories**? For example with the above structure at both "./" and "./passing", the command produces no error when executed on the testsrc/testdst tree at "./passing" but fails with the same files at "./". I've verified the files are unique with the same stat.

### STRACE
Relevant portions of the 3 strace show failure at ```linkat``` with: src ```testsrc/dir_link" (symlink-to-dir), dst ```testdst/dir_link```, and no flags set (i.e. no ```AT_SYMLINK_FOLLOW``` flag (see https://linux.die.net/man/2/linkat):

**LXFS**

> 16656 stat("testdst", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16656 lstat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16656 lstat("testdst/dir", 0x7ffef8eca460) = -1 ENOENT (No such file or directory)
16656 lstat("testdst/dir", 0x7ffef8eca580) = -1 ENOENT (No such file or directory)
16656 mkdir("testdst/dir", 0700)        = 0
16656 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
16656 openat(AT_FDCWD, "testsrc/dir", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
16656 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16656 getdents(3, /* 3 entries */, 32768) = 80
16656 getdents(3, /* 0 entries */, 32768) = 0
16656 close(3)                          = 0
16656 lstat("testsrc/dir/file.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
16656 linkat(AT_FDCWD, "testsrc/dir/file.txt", AT_FDCWD, "testdst/dir/file.txt", 0) = 0
16656 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
16656 utimensat(AT_FDCWD, "testdst/dir", [{tv_sec=1604025348, tv_nsec=154084300} /* 2020-10-29T22:35:48.154084300-0400 */, {tv_sec=1604025325, tv_nsec=414084300} /* 2020-10-29T22:35:25.414084300-0400 */], 0) = 0
16656 lchown("testdst/dir", 1000, 1000) = 0
16656 llistxattr("testsrc/dir", NULL, 0) = 0
16656 llistxattr("testsrc/dir", 0x7ffef8eca190, 0) = 0
16656 getxattr("testsrc/dir", "system.posix_acl_access", 0x7ffef8eca050, 132) = -1 ENODATA (No data available)
16656 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16656 getxattr("testsrc/dir", "system.posix_acl_default", 0x7ffef8eca050, 132) = -1 ENODATA (No data available)
16656 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16656 setxattr("testdst/dir", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
16656 removexattr("testdst/dir", "system.posix_acl_default") = 0
16656 lstat("testsrc/dir_link", {st_mode=S_IFLNK|0777, st_size=4, ...}) = 0
16656 lstat("testdst/dir_link", 0x7ffef8eca440) = -1 ENOENT (No such file or directory)
16656 lstat("testdst/dir_link", 0x7ffef8eca560) = -1 ENOENT (No such file or directory)
**16656 linkat(AT_FDCWD, "testsrc/dir_link", AT_FDCWD, "testdst/dir_link", 0) = 0**
16656 lstat("testdst/dir_link", {st_mode=S_IFLNK|0777, st_size=4, ...}) = 0

**DRVFS - EISDIR**
> 17081 stat("testdst", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17081 lstat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17081 lstat("testdst/dir", 0x7ffe6e456590) = -1 ENOENT (No such file or directory)
17081 lstat("testdst/dir", 0x7ffe6e4566b0) = -1 ENOENT (No such file or directory)
17081 mkdir("testdst/dir", 0700)        = 0
17081 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
17081 openat(AT_FDCWD, "testsrc/dir", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
17081 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17081 getdents(3, /* 3 entries */, 32768) = 80
17081 getdents(3, /* 0 entries */, 32768) = 0
17081 close(3)                          = 0
17081 lstat("testsrc/dir/file.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
17081 linkat(AT_FDCWD, "testsrc/dir/file.txt", AT_FDCWD, "testdst/dir/file.txt", 0) = 0
17081 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
17081 utimensat(AT_FDCWD, "testdst/dir", [{tv_sec=1604031447, tv_nsec=586558200} /* 2020-10-30T00:17:27.586558200-0400 */, {tv_sec=1604031191, tv_nsec=415400600} /* 2020-10-30T00:13:11.415400600-0400 */], 0) = 0
17081 lchown("testdst/dir", 1000, 1000) = 0
17081 llistxattr("testsrc/dir", NULL, 0) = 0
17081 llistxattr("testsrc/dir", 0x7ffe6e4562c0, 0) = 0
17081 getxattr("testsrc/dir", "system.posix_acl_access", 0x7ffe6e456180, 132) = -1 ENODATA (No data available)
17081 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17081 getxattr("testsrc/dir", "system.posix_acl_default", 0x7ffe6e456180, 132) = -1 ENODATA (No data available)
17081 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17081 setxattr("testdst/dir", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
17081 removexattr("testdst/dir", "system.posix_acl_default") = -1 ENODATA (No data available)
17081 lstat("testsrc/dir_link", {st_mode=S_IFLNK|0777, st_size=3, ...}) = 0
17081 lstat("testdst/dir_link", 0x7ffe6e456570) = -1 ENOENT (No such file or directory)
17081 lstat("testdst/dir_link", 0x7ffe6e456690) = -1 ENOENT (No such file or directory)
**17081 linkat(AT_FDCWD, "testsrc/dir_link", AT_FDCWD, "testdst/dir_link", 0) = -1 EISDIR (Is a directory)**

**DRVFS Passing**
> 16678 stat("testdst", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16678 lstat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16678 lstat("testdst/dir", 0x7ffda61a52a0) = -1 ENOENT (No such file or directory)
16678 lstat("testdst/dir", 0x7ffda61a53c0) = -1 ENOENT (No such file or directory)
16678 mkdir("testdst/dir", 0700)        = 0
16678 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
16678 openat(AT_FDCWD, "testsrc/dir", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
16678 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16678 getdents(3, /* 3 entries */, 32768) = 80
16678 getdents(3, /* 0 entries */, 32768) = 0
16678 close(3)                          = 0
16678 lstat("testsrc/dir/file.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
16678 linkat(AT_FDCWD, "testsrc/dir/file.txt", AT_FDCWD, "testdst/dir/file.txt", 0) = 0
16678 lstat("testdst/dir", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
16678 utimensat(AT_FDCWD, "testdst/dir", [{tv_sec=1604030190, tv_nsec=858308900} /* 2020-10-29T23:56:30.858308900-0400 */, {tv_sec=1604030190, tv_nsec=858308900} /* 2020-10-29T23:56:30.858308900-0400 */], 0) = 0
16678 lchown("testdst/dir", 1000, 1000) = 0
16678 llistxattr("testsrc/dir", NULL, 0) = 0
16678 llistxattr("testsrc/dir", 0x7ffda61a4fd0, 0) = 0
16678 getxattr("testsrc/dir", "system.posix_acl_access", 0x7ffda61a4e90, 132) = -1 ENODATA (No data available)
16678 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16678 getxattr("testsrc/dir", "system.posix_acl_default", 0x7ffda61a4e90, 132) = -1 ENODATA (No data available)
16678 stat("testsrc/dir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
16678 setxattr("testdst/dir", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
16678 removexattr("testdst/dir", "system.posix_acl_default") = -1 ENODATA (No data available)
16678 lstat("testsrc/dir_link", {st_mode=S_IFLNK|0777, st_size=4, ...}) = 0
16678 lstat("testdst/dir_link", 0x7ffda61a5280) = -1 ENOENT (No such file or directory)
16678 lstat("testdst/dir_link", 0x7ffda61a53a0) = -1 ENOENT (No such file or directory)
**16678 linkat(AT_FDCWD, "testsrc/dir_link", AT_FDCWD, "testdst/dir_link", 0) = 0**
16678 lstat("testdst/dir_link", {st_mode=S_IFLNK|0777, st_size=4, ...}) = 0

Full strace logs @ https://gist.github.com/JoshNoel/71ea86d30d9641a4aaa9418fe443d07e

### File stat
Confirmed both the failing and passing drvfs testcases have the same initial state created by:
```
mkdir testdst
mkdir testsrc
mkdir testsrc/dir
touch testsrc/dir/file.txt
cd testsrc
ln -s dir dir_link
```

For the passing drvfs case we indeed see the same inode for the hard linked symlink:

>   File: testsrc/dir_link -> dir/
>   Size: 4               Blocks: 0          IO Block: 4096   symbolic link
> Device: 6eh/110d        Inode: 3096224743902665  Links: 2
> Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    Josh)   Gid: ( 1000/    Josh)

>   File: testdst/dir_link -> dir/
>   Size: 4               Blocks: 0          IO Block: 4096   symbolic link
> Device: 6eh/110d        Inode: 3096224743902665  Links: 2
> Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    Josh)   Gid: ( 1000/    Josh)
> 

#  Expected behavior

1) At a minimum expect same ```cp -al``` and ```linkat``` behavior for trees at different locations in drvfs filesystem.
2) Expect no error from ```cp -al``` and linkat in drvfs. A hard link should be created at the destination to the src symlink.
Specifically, I believe ```linkat(AT_FDCWD, "testsrc/dir_link", AT_FDCWD, "testdst/dir_link", 0)``` should return 0 for symlink ```testsrc/dir_link``` and existing directory ```testdst```.
3) linkat returning EISDIR seems nonstandard (unlisted on manpage)? Document meaning of this errno.

**Comment by therealkenc** [comment]
Likely same #3943
