### ISSUE TITLE
vhdx file for distribution disappeared

### ISSUE THREAD

**Issue by vladdu** [microsoft/WSL#6173]
# Environment

```none
Windows build number:  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I started wsl today and was greeted with a message: "The system cannot find the path specified. [process exited with code 4294967295]". Another distribution that I have installed works fine. I checked and the ext4.vhdx file containing the file system is missing! 

%APPDATA%\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_*\LocalState\ext4.vhdx

I did not remove it myself. I did not use wsl for a week or so, there has been a windows update in between. It might not be a wsl issue, but I can't see why other apps would delete just that file.

Losing all my Linux files is bad. 

**WSL logs**: I don't know what kind of logs or information to provide. Please advise.

#  Expected behavior

# Actual behavior

**Comment by Biswa96** [comment]
There was a similar issue about one and half year ago, here https://github.com/microsoft/WSL/issues/4063.

**Comment by vladdu** [comment]
Thanks, I didn't find that. Seems to be the same issue.

**Comment by vladdu** [comment]
Closing as duplicate of #4063
