### ISSUE TITLE
pkexec returns "error getting authority" (Kali Linux, WSL 2)

### ISSUE THREAD

**Issue by LRitzdorf** [microsoft/WSL#6178]
# Environment

```none
Windows build number: 19041.572
Your Distribution version: Kali Rolling (currently on 2020.3)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

The `pkexec` command, when used to run at least some other commands, returns `Error getting authority: Error initializing authority: Could not connect: No such file or directory`. This was discovered using Wireshark in Kali Linux (on WSL 2) -- the "start menu" shortcut for Wireshark runs `pkexec wireshark`, and does not function. However, running `sudo wireshark` from the command line works as expected, so the issue does not lie with Wireshark. For ease of testing, the error also appears with `pkexec ls`.

This was tested in Kali Linux, and has not yet been verified for other WSL distributions.

#  Expected behavior

```
$ pkexec wireshark
[Wireshark starts, printing status messages in the process]
```

# Actual behavior

```
$ pkexec wireshark
Error getting authority: Error initializing authority: Could not connect: No such file or directory
```

**Comment by therealkenc** [comment]
You don't have `dbus` running. You can do a `sudo service dbus start` to get one step of the way, but there would be more to it to get [polkit](https://gitlab.freedesktop.org/polkit/polkit/) running on a headless Linux box such as WSL. Spiritually dupe #6117.
