### ISSUE TITLE
WSL2 can't open display

### ISSUE THREAD

**Issue by peter-jerry-ye** [microsoft/WSL#6181]
# Environment

```none
Windows build number: 10.0.19041.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

- Install VcXSrv
- Go to Windows Defender Firewall to enable all network connection for VcXSrv
- Start VcXsrv with "Multiple windows", "Start no client", enable every option (including Disable access control)
- run `ip route` to get ip of host os, which is `default via 172.30.96.1 dev eth0`
- run `DISPLAY=172.30.96.1:0.0 xeyes` to test xserver

https://gist.github.com/peter-jerry-ye/725d6768fde7a5c37294ce9faf70bbb4

**WSL logs**: 

#  Expected behavior

Xeyes being started

# Actual behavior

`Error: Can't open display: 172.30.96.1:0.0` after a few seconds

**Comment by luochen1990** [comment]
Check which address your VcXSrv is listening, by hover the tray icon of VcXSrv, it could be `hostname:x.0` and you should check `x` is `0`

**Comment by peter-jerry-ye** [comment]
> Check which address your VcXSrv is listening, by hover the tray icon of VcXSrv, it could be `hostname:x.0` and you should check `x` is `0`

It' s listening at "hostname:0.0", and with the ip adresse shown in `ip route`, it doesn't work.

**Comment by onomatopellan** [comment]
>Go to Windows Defender Firewall to enable all network connection for VcXSrv

Maybe that's not enough. Close everything and go to Windows Firewall with Advanced Security -> Inbound rules and delete every rule you see for Vcxsvr.exe. After that the first time you launch Vcxsvr make sure you Allow access for Private AND Public networks.

**Comment by peter-jerry-ye** [comment]
> 
> 
> > Go to Windows Defender Firewall to enable all network connection for VcXSrv
> 
> Maybe that's not enough. Close everything and go to Windows Firewall with Advanced Security -> Inbound rules and delete every rule you see for Vcxsvr.exe. After that the first time you launch Vcxsvr make sure you Allow access for Private AND Public networks.

It works! Thanks a lot.

**Comment by varadhraj** [comment]
@peter-jerry-ye works like a charm. thanks.

**Comment by jha-prateek** [comment]
> > Go to Windows Defender Firewall to enable all network connection for VcXSrv
> 
> Maybe that's not enough. Close everything and go to Windows Firewall with Advanced Security -> Inbound rules and delete every rule you see for Vcxsvr.exe. After that the first time you launch Vcxsvr make sure you Allow access for Private AND Public networks.

It works!

**Comment by hongbo-zhu-cn** [comment]
> > Go to Windows Defender Firewall to enable all network connection for VcXSrv
> 
> Maybe that's not enough. Close everything and go to Windows Firewall with Advanced Security -> Inbound rules and delete every rule you see for Vcxsvr.exe. After that the first time you launch Vcxsvr make sure you Allow access for Private AND Public networks.

Or double click the VcXsrv rules and change action to "Allow the connection" .

**Comment by scotinus** [comment]
> > > Go to Windows Defender Firewall to enable all network connection for VcXSrv
> > 
> > 
> > Maybe that's not enough. Close everything and go to Windows Firewall with Advanced Security -> Inbound rules and delete every rule you see for Vcxsvr.exe. After that the first time you launch Vcxsvr make sure you Allow access for Private AND Public networks.
> 
> Or double click the VcXsrv rules and change action to "Allow the connection" .

Thank you, thank you @jha-prateek and @hongbo-zhu-cn. I finally got there with a combination of these answers. Enabling inbound PUBLIC networks was the key.

**Comment by RorisangSitoboli** [comment]
- Open Xlaunch as an 'administrator' in your host (Windows). Right click on the app and select that option.
- If you happen to see a '-1' near the bottom of the XLaunch first page, you can smile already.
- Choose option that disables 'control'. forgot on what page of the set up GUI it is on (maybe two).
- Launch WSL. 
- Type exactly this as I am not using placeholders: 'export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"
- Test in Ubuntu by typing: 'xcalc'
- Make sure you have browser installed if you go online with a GUI.
- Good luck.

**Comment by javierportillo** [comment]
Hey guys, I found another solution if you are still not getting results.
If you're using ip route to get the host IP be careful with that command introducing invicible color codes to the output.
You can install colorized-logs package in ubuntu and use the ansi2txt tool to clean the output of ip route like this:
`DISPLAY=$(ip route list exact default | awk '{print $3}' | ansi2txt):0`
This solved it for me.
