### ISSUE TITLE
vi / vim editor on WSL2 hangs when opening any file

### ISSUE THREAD

**Issue by firealone147** [microsoft/WSL#6184]
**Env**
Microsoft Windows [Version 10.0.18362.1082]
wsl2: Ubuntu-20.04

**Problem**
`vi` just hangs. same as `vim --clean`
kill pid or Ctrl+C can continue open vi but cannot read any content of the file.

**Strace of the command**
https://gist.github.com/firealone147/a22d5c092f1c49540ad4ee128c46196c

**Comment by luochen1990** [comment]
check `echo $DISPLAY`  and try `unset DISPLAY` before run `vi` ?

**Comment by therealkenc** [comment]
Thanks for the `strace(1)` log output (always appreciated).

```
connect(3, {sa_family=AF_INET, sin_port=htons(6000), sin_addr=inet_addr("192.168.134.193")}, 16
```

That IP address doesn't look like a Windows host. On WSL2 they end in `.1`.

**Comment by firealone147** [comment]
Since you mentioned $DISPLAY, I just find out the problem is X11 fowarding setting.
If I close X11 forwarding daemon on Windows, this will happen.

It behaves normally if I open the daemon on Windows.

Thanks for the help.
