### ISSUE TITLE
wsl --install syntax should be simpler if wsl is already installed

### ISSUE THREAD

**Issue by kodymoodley** [microsoft/WSL#6185]
# Environment

```none
Windows build number: Win32NT             10.0.20246.0 Microsoft Windows NT 10.0.20246.0
Your Distribution version: -
Whether the issue is on WSL 2 and/or WSL 1: -
```

# Steps to reproduce

- Open Windows Powershell with administrator privileges

- Type: wsl --install and hit enter

**WSL logs**: 

#  Expected behavior

Windows Powershell to execute installation of WSL e.g. [like this](https://devblogs.microsoft.com/commandline/wp-content/uploads/sites/33/2020/10/wslinstall.png)

# Actual behavior

WSL installation process does not start. I get usage manual information for the "wsl" command.
![image](https://user-images.githubusercontent.com/13569029/97865082-ecd18f80-1d09-11eb-893d-753f6899f296.png)

**Comment by Biswa96** [comment]
See the usage out put carefully. There are already two examples.

**Comment by 0xbadfca11** [comment]
If WSL is already installed, ``wsl --install`` does nothing.

**Comment by thernstig** [comment]
I'd argue that if `wsl --install` requires `--distrubition` if one has already been installed, then the output should indicate just that and exit early (i.e. not printing the full help at all).

**Comment by therealkenc** [comment]
To the extent this ask becomes actionable (the code gets touched), the `-d` option is superfluous and adds an unnecessarily lengthy documentation burden. The command `wsl.exe --install <Distro>` is objectively easier to explain, with no loss in fidelity.

**Comment by kodymoodley** [comment]
running `wsl --install --distribution Ubuntu` worked for me. I was just working on the announcements made about WSL e.g. https://devblogs.microsoft.com/commandline/distro-installation-added-to-wsl-install-in-windows-10-insiders-preview-build-20246/ which states that all you need is `wsl --install`. The announcement does not mention that there should be at least one distro already installed. I assume that `wsl --install` will take the default distro (if one is installed). So there was none in my case, so that is why it is giving the full usage help.

**Comment by thernstig** [comment]
@kodymoodley Maybe you can update the subject line and issue description to indicate that the output should be updated, preferably with the suggestion by @therealkenc ?

**Comment by skandaprasad** [comment]
I too have WSL installed and set to version 2.
If I enter the command `wsl --install` or `wsl --update`, output is the user manual.

What exactly is supposed to be done to rectify this?
