### ISSUE TITLE
Error installing Ubuntu and Debian - WslRegisterDistribution failed with error: 0x80070426 Error: 0x80070426 The service has not been started.

### ISSUE THREAD

**Issue by ursus-code** [microsoft/WSL#6191]
# Environment
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
I did not have WSL installed before so went directly to WSL2 on this page:
I followed https://docs.microsoft.com/en-us/windows/wsl/install-win10 
error free till Step 6 and got this error in the Debian or Ubuntu windows as they were trying to install:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070426
Error: 0x80070426 The service has not been started.

when trying to install either:
Ubuntu 20.04 LTS
Debian GNU/Linux

I tried several googled fixes, like looking for Microsoft Security Essentials (not there), making sure my BIOS has Virtualization on (yes, see Task Manager Performance Tab says Virtualization: Enabled) and start/stop/restart LxssManager and LxssManagerUser_7f71a multiple times in Services with multiple reboots.

PS C:\Windows\system32> wsl --list
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

PS C:\Windows\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

#  Expected behavior

That Ubuntu or Debian install in WSL

# Actual behavior

See above, but inshort, after install WSL 2 - I get this error trying to install Debian or Ubuntu:
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070426
Error: 0x80070426 The service has not been started.

**Comment by ursus-code** [comment]
Submitted recording and screenshots in Windows Feedback.

Thanks!

**Comment by cdunford** [comment]
I have run into the same error trying to install Ubuntu 20.04 manually on 1909 (18363.1139):

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070426
Error: 0x80070426 The service has not been started.
```

Anyone know what "service" it is referring to here?

**Comment by m5nv** [comment]
Same issue here. Since I was unable to launch the distribution from the store, I downloaded and `installed` distro [manually](https://docs.microsoft.com/en-us/windows/wsl/install-manual). I don't see any errors after `launching` the distro. Neither does it actually do anything after launching. I suspect it's silently bailing out.

Net result is that I don't see a distribution that I can use after going through all the hoops.

```shell
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   ServerComponent\Description : Provides services and environments for running native user-mode Linux
                   shells and tools on Windows.
                   ServerComponent\DisplayName : Windows Subsystem for Linux
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux
```

```shell
PS C:\WINDOWS\system32> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

PS: I have rebooted several times and have gone through the process from scratch a couple of times.

**Comment by cdunford** [comment]
I managed to track down my specific issue. The "DNS Client' on my box was disabled. I set it to Automatic, fired it up and I was able to install/start a distro. Can't promise that's the only service that will break it, but worth a check.

**Comment by ursus-code** [comment]
> I managed to track down my specific issue. The "DNS Client' on my box was disabled. I set it to Automatic, fired it up and I was able to install/start a distro. Can't promise that's the only service that will break it, but worth a check.

THAT WAS IT!!!   THANK YOU SOOOOO MUCH!!!  Thank you for posting here to let other know

**Comment by ursus-code** [comment]
> Same issue here. Since I was unable to launch the distribution from the store, I downloaded and `installed` distro [manually](https://docs.microsoft.com/en-us/windows/wsl/install-manual). I don't see any errors after `launching` the distro. Neither does it actually do anything after launching. I suspect it's silently bailing out.
> 
> Net result is that I don't see a distribution that I can use after going through all the hoops.
> 
> ```shell
> PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> 
> FeatureName      : Microsoft-Windows-Subsystem-Linux
> DisplayName      : Windows Subsystem for Linux
> Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
>                    ServerComponent\Description : Provides services and environments for running native user-mode Linux
>                    shells and tools on Windows.
>                    ServerComponent\DisplayName : Windows Subsystem for Linux
>                    ServerComponent\Id : 1033
>                    ServerComponent\Type : Feature
>                    ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
>                    ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux
> ```
> 
> ```shell
> PS C:\WINDOWS\system32> wsl --list --verbose
> Windows Subsystem for Linux has no installed distributions.
> Distributions can be installed by visiting the Microsoft Store:
> https://aka.ms/wslstore
> ```
> 
> PS: I have rebooted several times and have gone through the process from scratch a couple of times.

Per the thread below - check if your DNSClient is running under Services.

**Comment by m5nv** [comment]
@ursus-code 
 
> Per the thread below - check if your DNSClient is running under Services.

That is **not** it for me. The DNS Client service is enabled and running. Can anyone tell me how to "launch" the "distro" from command line. Perhaps that will provide additional information. Right now when I launch it from Start Menu I can't tell what's really going on. Thanks in advance.

**Comment by m5nv** [comment]
Previously I was installing the "distro" from command line using:
```shell
Add-AppxPackage -Path "C:\Path\to\DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx"
```

This would "install' the distro but as I mentioned nothing happens when I "launch" it from start menu.

This time around I double clicked on the file to get it to install using the GUI when then gave me an option to launch it after installation. I managed to at least produce an error dialog done this way. I have no clue what that error means though. Including it here for reference and see if it means anything to anyone.

![Post Launch Unsuccessful Error Message ](https://user-images.githubusercontent.com/45653160/99143795-37f67700-2615-11eb-8e68-8e20f70c04fd.png)

**Comment by manuth** [comment]
@cdunford, @ursus-code I just wanted to mention, that it seems like the "Microsoft Account Sign-in Assistant" (`wlidsvc`) (no idea whether it's actually called like this in English) service is required to be running as well.

I made sure this service was running which helped me to solve the error `The service has not been started`.

@m5nv You're facing an issue other than the one mentioned in this topic.
You might want to use the (rather dirty) workaround in #3437

**Comment by Lukanite** [comment]
@manuth Enabling this fixed it for me, thanks!

**Comment by Mygirl** [comment]
thanks

**Comment by SparksFlyx3** [comment]
I had the same issue & fixed it with this [Microsoft forum solution](https://answers.microsoft.com/en-us/windows/forum/all/microsoft-sign-in-assistant-disable/ee54bac2-7720-4526-9711-3563684cc449):
- Type `services.msc` into the start search box and press Enter. This will open the Services snap-in of the console.
- In the list of services, locate the service ( `wlidsvc` is called "Microsoft Account Sign-in Assistant" in English and "Anmelde-Assistent für Microsoft-Konten" in German) and **double-click** on it to open its properties dialogue.
- Select "Starttype" -> auto
- Start the service
- Try starting your Ubuntu/Debian again. It should work now.
