### ISSUE TITLE
WSL1 Permission denied when mv -f -rw-rw file to -r--r--

### ISSUE THREAD

**Issue by blami** [microsoft/WSL#6193]
# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.19041.572]`
Your Distribution version: `Ubuntu 20.04`
Whether the issue is on WSL 2 and/or WSL 1: WSL1, `Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020`
```

``` none
$ cat /etc/wsl.conf
[automount]
enabled = true
mountFsTab = true
root = /mnt/
options = "metadata,umask=2,fmask=1,case=off"

[network]
generateHosts = true
generateResolvConf = true
```

# Steps to reproduce
``` none
# Native Windows filesystem - buggy permissions
$ cd /mnt/c/Users/blami
$ touch a
$ touch b
$ chmod a-w a
$ ls -la a b
-r--r--r-- 1 blami blami 0 Nov  4 18:09 a
-rw-rw-r-- 1 blami blami 0 Nov  4 18:09 b
# here comes the bug
$ mv -f b a
mv: cannot move 'b' to 'a': Permission denied
# when permissions corrected
$ chmod a+w a
-rw-rw-r-- 1 blami blami 0 Nov  4 18:09 a
-rw-rw-r-- 1 blami blami 0 Nov  4 18:09 b
$ mv -f b a
$ echo $?
0
```

``` none
# WSL1 virtual filesystem - as expected
$ cd /home/blami
$ touch a
$ touch b
$ chmod a-w a
$ ls -la a b
-r--r--r-- 1 blami blami 0 Nov  4 18:10 a
-rw-rw-r-- 1 blami blami 0 Nov  4 18:10 b
# here all is as it should be
$ mv -f b a
$ echo $?
0
```

## Relevant `strace` output
``` text
geteuid()                               = 1000
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
renameat2(AT_FDCWD, "b", AT_FDCWD, "a", RENAME_NOREPLACE) = -1 ENOSYS (Function not implemented)
newfstatat(AT_FDCWD, "a", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
stat("a", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
lstat("b", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
newfstatat(AT_FDCWD, "a", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
rename("b", "a")                        = -1 EACCES (Permission denied)
```

**WSL logs**: 

#  Expected behavior
When I `mv -f a b` in WSL1 on native Windows filesystem (under `/mnt/c/Users/blami`); where file `a` is owned by user `blami` with read only permissions and file `b` has same owner and read write permissions, the move is successful.

I expect Linux permissions on native Windows filesystem (under `/mnt/c/Users/blami`) are interpreted same as on WSL virtual filesystem (given I have access to these files on Windows filesystem as Windows user running WSL). 

# Actual behavior
When I `mv -f a b` in WSL1 on native Windows filesystem (under `/mnt/c/Users/blami`); where file `a` is owned by user `blami` with read only permissions and file `b` has same owner and read write permissions, the move fails with "permission denied" error. On WSL virtual filesystem same operation under same condition succeeds.

**Comment by WSLUser** [comment]
`wsl.conf` isn't set correctly. Use this instead: 

```
[automount]
enabled = true
options = "metadata,uid=1000,gid=1000,umask=0022,fmask=11,case=off"
mountFsTab = false
crossDistro = true

[filesystem]
umask = 0022

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
appendWindowsPath = true
```

**Comment by blami** [comment]
@WSLUser I tried to make these changes to `wsl.conf` and restarted computer but it still does not work and I can reproduce the issue same as I posted above. Can you elaborate a bit what is exactly wrong with my original settings (except using different `umask` and `fmask` which should be fine and make no difference)?

**Comment by WSLUser** [comment]
I actually believed the different umask and fmask would make a difference in how WSL would read it. Try 2 things if you haven't already and don't change the `wsl.conf`. The config I listed is good as is.

1) Run your WSL session in an elevated instance, usually through "Runas Administrator". You'll need to do this to your terminal or the app itself (which just runs conhost in background for your terminal). 

2) If this isn't enough on its own, also add sudo. You won't be able to obtain a higher permission than that. If you still can't then you have a permissions issue on the files itself and will need adjusting through the Security tab in the file Properties.

**Comment by WSLUser** [comment]
Since you stated this does still work on the 9P file explorer side, that would mean the permissions are either not being properly allowed and providing more access than it should or there's something wrong with the distro itself. As a last resort, I'd reset your WSL app in Settings and re-launch from the Settings for the re-install to occur.Add the` /etc/wsl.conf `config back, do `wsl --shutdown` in Powershell or CMD, then try relaunching again.

**Comment by blami** [comment]
@WSLUser Please note that I don't use 9P at all (that's way how WSL2 mounts native filesystems), in case of WSL1 I believe DrvFs is being used - I'd expect bug to be in there. Where it works is the native WSL1 filesystem.

As for running elevated WSL instance that doesn't make any difference (just tried) as I create all those files from within WSL running under my user (`blami`). My testcase is selfcontained to WSL so Windows permissions on files created from within WSL are all right on Windows side (checked right after creating `a` and `b` and also after `chmod`). I use `metadata` which means as long as Windows permissions are ok WSL1 should honor POSIX permissions stored in the file metadata - which it does improperly. I am able to reproduce the bug with elevated instance of WSL. Testing without `/etc/wsl.conf` is kind of pointless as it doesn't use DrvFs metadata at all so then it obviously works but many other things don't.

And yes, noted. From now on I run all tests in clean room VM with fresh Windows 10 Pro [Version 10.0.19041.572] install with no additional software and with fresh Windows Store Ubuntu running in WSL1  - on a newly created set of files. The only change I've made is enabling my specific `*mask` (I need it that way to be compatible with my work environment) and `metadata` options in `/etc/wsl.conf`. Still able to reproduce the bug.

**Comment by WSLUser** [comment]
9P works for both WSL1 and WSL2. I guess workaround would be to use that for now. From the CLI, you could enter powershell or cmd from wsl and perform the rename. I think your mask is likely too restrictive but clearly something is broken you can access from one but not the other.

**Comment by blami** [comment]
@WSLUser I'm running into this issue when trying to build something using make (so dropping out to PS interactively is no choice - but I get the point).  This `mv -f a b` is just minimal reproducible case taken from complex Makefile. For now I simply symlinked my build dir to other filesystem but I'd prefer to build in `/mnt/c/Users/` so I don't have to copy files over everytime I edit them in WSL unaware proprietary IDE. 

I don't get your point with mask. Mask is only used when creating files, not when accessing them (as long as they have metadata - and they have in my case as I have metadata turned on and I can see NTFS properties even from Windows side).

**Comment by therealkenc** [comment]
Cannot reproduce on 20257. You might try Insiders on the off the problem has been addressed. Probably dupe #5019, which despite being open I can no longer reproduce either.

![image](https://user-images.githubusercontent.com/7049700/99324016-2e912880-2828-11eb-8ecf-078c95019222.png)

**Comment by blami** [comment]
Thanks @therealkenc , unfortunately this is corporate env so I can't go to Insider builds. Good to know it is fixed!

**Comment by therealkenc** [comment]
Call this /dupe #5019 under the preponderance of evidence.
