### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by jiawei163com** [microsoft/WSL#6197]
I execute Sudo SystemCTL restart Docker, System has not been Booted with systemd as init System (PID 1). Can't Operate it once.How can this be resolved

**Comment by shackrack2** [comment]
+1

**Comment by WSLUser** [comment]
Dupe https://github.com/microsoft/WSL/issues/994

**Comment by therealkenc** [comment]
/dupe #994 similar #2374 ([message](https://github.com/microsoft/WSL/issues/2374#issuecomment-389462712))

> How can this be resolved

There's a discussion #4872. Use initrc, aka `sudo service docker restart`.

**Comment by jiawei163com** [comment]
> /dupe #994 similar #2374 ([message](https://github.com/microsoft/WSL/issues/2374#issuecomment-389462712))
> 
> > How can this be resolved
> 
> There's a discussion #4872. Use initrc, aka `sudo service docker restart`.



> this command helped me, start it with: `sudo /etc/init.d/docker start`

Thank you all. This command is indeed valid

**Comment by CHINOBv** [comment]
How can resolve this?
