### ISSUE TITLE
mv borks on case changes

### ISSUE THREAD

**Issue by mcandre** [microsoft/WSL#6202]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Microsoft Windows [Version 10.0.18363.1139]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]

Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020
```

# Steps to reproduce

```console
$ touch a.txt
$ mv a.txt A.txt
mv: 'a.txt' and 'A.txt' are the same file
```

**WSL logs**: 

#  Expected behavior

mv renames the file to "A.txt".

# Actual behavior

mv reports an error.

As a workaround, you have to include an extra prefix or suffix, rename to the desired case with that extra prefix/suffix, then finally rename a second time to remove the prefix/suffix.

**Comment by heidemn** [comment]
This only happens when the file is located on a Windows filesystem.
Works fine for files in ext4.
