### ISSUE TITLE
"is the docker daemon running?" Docker, Linux version

### ISSUE THREAD

**Issue by jimmyff** [microsoft/WSL#6204]
I've just followed the docker installation guide [here](https://docs.docker.com/engine/install/ubuntu/), and although docker is installed the daemon doesn't run.

```
jimmyff@jbox:/mnt/z/dev/dart/os_cloudrun$ docker -v
Docker version 19.03.13, build 4484c46d9d
```

```
jimmyff@jbox:/mnt/z/dev/dart/os_cloudrun$ docker info
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

I can't start the service or check it's status as i doesn't seem to be registered.

```
jimmyff@jbox:/mnt/z/dev/dart/os_cloudrun$ sudo service docker status
docker: unrecognized service
```

As well as the official repo as used in the above example I've also tried to install the versions straight out of the ubuntu repos and that also has the same issue.

**Comment by jimmyff** [comment]
Installing docker desktop in windows  and enabling integration with the WSL container fixed my issue

**Comment by meicale** [comment]
I use the same method and it works. But, I can not use the docker if I export the container and imported again. Do you guys know to solve this?
