### ISSUE TITLE
Vvmem doesn't release memory after high memory usage

### ISSUE THREAD

**Issue by selimrecep** [microsoft/WSL#6205]
# Environment
Microsoft Windows NT 10.0.19041.0
WSL 2
Release:        2020.4 (Kali)

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
Start WSL. And run `sudo apt install -y kali-win-kex`. During the install memory goes up to 2.5 GB of RAM (Vvmem) and after the job is done, the proccess doesn't release the memory.

**WSL logs**: 
I can't provide logs because I don't have enough data to download all 500 MB packages :/
#  Expected behavior
It should release memory after the command is executed.

# Actual behavior
I don't think it should go up to 2.5 GBs of RAM when I run the command I mentioned before, it uses 2.5 GBs of RAM. And the worst thing is it should free memory that used after the job is done.  It doesn't.

**Comment by Sean12697** [comment]
I'm having a similar issue with Docker, I've found Issue #4166 which is similar and is still open :/
