### ISSUE TITLE
Development boards not visible under /dev/tty*

### ISSUE THREAD

**Issue by scubachristopher** [microsoft/WSL#6206]
Environment

```
Windows build number:  10.0.19041.572
Your Distribution version:  Ubuntu 18.04, updated
WSL 2
```

# Steps to reproduce

Attach a device (like a Olimex ESP32-EVB board or a Huzza Feather 32) via USB:

chris@Christopher-PC:~$ ls -al /dev/ttyS*
crw------- 1 root root 4, 64 Oct  3 12:59 /dev/ttyS0
crw------- 1 root root 4, 65 Oct  3 12:59 /dev/ttyS1
crw------- 1 root root 4, 66 Oct  3 12:59 /dev/ttyS2
crw------- 1 root root 4, 67 Oct  3 12:59 /dev/ttyS3

#  Expected behavior

Device should be visible under /dev/tty*

# Actual behavior

Device is not visible

WSL 2, Ubuntu 18.04, updated.
Attach a device (like a Olimex ESP32-EVB board or a Huzza Feather 32) via USB:

What COULD be fabulous about this environment is development of ESP32 devices via MS Code. In fact, installing code via:

~$ code .

installs the WSL code version. I can build, all is wonderful. Except you can't serial monitor the device because of this issue.

Please fix! You would unleash a path from MacOS back to Windows.

**Comment by Biswa96** [comment]
Serial devices can be accessed through \\Device\COM interfaces with Putty like programs.

**Comment by Biswa96** [comment]
Serial devices can be accessed through `\\Device\COM` interfaces with Putty like programs in Windows.

**Comment by therealkenc** [comment]
> WSL 2

That `ls` output is confusing, because serial devices are not available in WSL2. Assume that output is not the output, but rather you get nothing.

/dupe #4322

**Comment by scubachristopher** [comment]
@Biswa96 -- you totally missed the point of the issue.  It's NOT available in WSL2 / Ubuntu.

Fine, it's a dupe, apologies.  But until you support ls -al /dev/[SOMETHING], WSL is dead for IoT developers.  Which sucks, given how powerful that would be for developing on Ubuntu under WINDOWS (the thing I think you're trying to sell...)

**Comment by Rki009** [comment]
A Windows batch script to load over port COM4:

set "ESPTOOL=C:/Ubuntu/ESP32-IDF/esp/esp-idf/components/esptool_py/esptool/esptool.py"

python3 %ESPTOOL% --chip esp32 -p COM4 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x10000 .\build\hello-world.bin

pause
exit
