### ISSUE TITLE
Find inteprets $PATH elements with spaces as relative paths

### ISSUE THREAD

**Issue by james-mcguire** [microsoft/WSL#6208]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Your Distribution version: Release:        20.04 (Ubuntu)
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

* Install WSL2
* Install Ubuntu
* Confirm `$PATH` has paths with spaces:
```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/Owner/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Owner/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
```
* Execute `find` command with `-execdir`
* Observe `find` command fails due to having a relative path
```
find: The relative path 'Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_x64__79rhkp1fndgsc' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
```

**WSL logs**: N/A

#  Expected behavior

* Find recognizes an item in the PATH environment variable with spaces as a full path (ie, not a relative path) and does not return an error

# Actual behavior

* Find recognizes an item in the PATH environment variable with spaces as a relative path and returns an error.

**Comment by DHowett** [comment]
This appears to be an issue with find? It will trivially reproduce outside of WSL (on bare-metal Linux) if you put a path with spaces on your `PATH`.

**Comment by therealkenc** [comment]
"Execute `find` command with `-execdir`" is not a repro. Same #5099, although over there the assumption was the `$PATH` was borked. Discussion can continue over there.

![image](https://user-images.githubusercontent.com/7049700/98749710-11b0ad00-2371-11eb-87be-6fb0fa3dab05.png)

**Comment by james-mcguire** [comment]
Thanks.  I was building openwrt as well.
