### ISSUE TITLE
attaching USB devices

### ISSUE THREAD

**Issue by mamoorkhan** [microsoft/WSL#6210]
**Is your feature request related to a problem? Please describe.**
I would like to access the usb devices attached to my host(windows) machine, as it would allow me to load the code that I write for the devices that I write the code for (arduino/FPGA)

**Describe the solution you'd like**
A usb passthrough

**Additional context**
I know this issue was brought up by a now deleted user in the ticket #5158 but that issue has since been closed by the OP and there are so many people upvoting the ticket without realizing that the ticket is closed.

**Comment by gmos** [comment]
+1 (again)

**Comment by gaia** [comment]
+1
This would essentially eliminate the need to run an Ubuntu box for me.

**Comment by cheynewallace** [comment]
+1 here,  we were investigating if it were possible to move over to using WSL2 from Mac.   We publish Raspberry Pi disk images and have a number of scripts and tooling based on bash scripts that mount USB disk volumes and perform image operations.  Without this we're blocked, or have to re-write out tool chain for native windows (which wont happen).   Hopefully this can be addressed soon

**Comment by therealkenc** [comment]
> A usb passthrough

/dupe #2195
