### ISSUE TITLE
WSL doesn't let VMware or VBox work

### ISSUE THREAD

**Issue by Gikone** [microsoft/WSL#6213]
After installing WSL and WSL2 my virtual machines stopped working. I uninstall WSL2  and WSL because maybe that was the issue but the problem persist.
How should I proceed to make my virtual machines work again?

**Comment by fuomag9** [comment]
Latest VMware release has support for HyperV as an hypervisor, as WSL forces it, I don't know about virtualbox but I believe there should be a setting to change to use HyperV as well
