### ISSUE TITLE
Intermittent 9p mount problem

### ISSUE THREAD

**Issue by 5eb** [microsoft/WSL#6214]
# Environment
Microsoft Windows [Version 10.0.19042.572]
Ubuntu 20.04.1 LTS
WSL2

# Steps to reproduce

Intermittent issue, so not easy to reproduce. Turning it off-and-on-again fixes the problem (most of the time) but this does not invalidate the bug. 

In a freshly booted Windows, start Ubuntu/WSL2. 

#  Expected behavior

After starting WSL2, the windows drive should be mounted correctly and usable. 

# Actual behavior

Trying to read the mounted windows filesystem fails.

---

$ mount says:
C:\ on /win/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;umask=22;fmask=11;symlinkroot=/win,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)

/proc/mounts line:
C:\134 /win/c 9p rw,dirsync,noatime,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;umask=22;fmask=11;symlinkroot=/win,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8 0 0

$ stat /win/c
stat: cannot stat '/win/c': Input/output error

----
$ cat /etc/wsl.conf
[interop]
enabled = true
appendWindowsPath = false

[automount]
enabled = true
root = /win
options = "metadata,umask=22,fmask=11"
mountFsTab = true

[network]
generateResolvConf = false

------

After a wsl restart (wsl --shutdown, start new wsl2 terminal) the mount is working fine.

**Comment by aflyhorse** [comment]
For me, this phenomenon often occurs when I turn the laptop into sleep mode or hibernation and then bring it up again. I need to manually ```mount -t drvfs C:\ /mnt/c``` to remount, or shutdown and restart wsl completely to fix it.
