### ISSUE TITLE
Poor performance of file system (Webpack,Next.js) performance

### ISSUE THREAD

**Issue by makuzaverite** [microsoft/WSL#6215]
# Environment

![image](https://user-images.githubusercontent.com/53856673/98535363-d4e29a00-223a-11eb-8f96-00b23535b0ca.png)

![image](https://user-images.githubusercontent.com/53856673/98535447-f9d70d00-223a-11eb-8d48-82323b4d76f9.png)

# Steps to reproduce

I'm facing extremely poor performance when running Next.js server/ Nuxt.js server, This is meant to reload on file save inside my vscode, I have read alot about file system in wsl includidng moving all files to wsl but nothing sem to help.

If there is any other option you may let me know 

 

#  Expected behavior

Those Servers should reload on file save 

# Actual behavior

No reload on file save

**Comment by ad-on-is** [comment]
- Store your project files inside WSL like `/home/user/projects`
- install NodeJs inside WSL
- execute your node-commands inside WSL
- Run VSCode Remote WSL to work on your project
- Edit, save filescas you please - everything should work

**Comment by makuzaverite** [comment]
Fixed Thanks @ad-on-is
