### ISSUE TITLE
WSL closes immediately

### ISSUE THREAD

**Issue by jmoteka** [microsoft/WSL#6218]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1139]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020)
```

# Steps to reproduce

Running: "Open Linux shell here" from context menu, run "wsl" from cmd or PowerShell.

#  Expected behavior

Shell opens. Shell opens at the location I selected "Open Linux shell here".

# Actual behavior

This results in a window which closes immediately. No possibility of interacting or even taking a look a the error message.
If running in the command line this is followed by no response.

wsl only works if distro is mentioned explicitely: `wsl -d ubuntu`

**Comment by alannt777** [comment]
Which is your default distro?

**Comment by therealkenc** [comment]
> Which is your default distro?

Or better, output of `wsl.exe -l -v`.

**Comment by alannt777** [comment]
@therealkenc You are thinking what I am thinking.

**Comment by mathball31** [comment]
I have the same issue.
` wsl.exe -l -v
  NAME      STATE           VERSION
* Legacy    Running         1`

**Comment by alannt777** [comment]
What is Legacy?

**Comment by therealkenc** [comment]
Well that's interesting, insofar as `wsl.exe -d ubuntu` launches successfully, but `Ubuntu` is not in your list. Which is at least a little like #6024.

You might try:
```
C:\> wsl.exe --set-default Ubuntu
```

_Assuming_ that takes, `Ubuntu` will be your default. You won't need the `-d` parameter to `wsl.exe`, and with fingers crossed, it might launch from the context menu as well.

Before doing so, out of an abundance of caution, you might want to backup your Ubuntu distribution with `wsl.exe --export Ubuntu <filename>` (if you have any valuable data in there). You can also try installing another distribution with a different name (say [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab)) to see if it shows up in the `wsl -l -v` list. Then set `Ubuntu-20.04` as the default.

> No possibility of interacting or even taking a look a the error message.

Trying running `wsl.exe -d Legacy` from a command prompt. Presumably the Legacy distro will fail to launch.

If it fails to launch, and you like, collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Although in the circumstance, you are probably shooting for WSL2 `Ubuntu` anyway.

> What is Legacy?

It is the distribution that used to ship with the now-deprecated `bash.exe`. Ref some commentary in #4717, including `--export` and `--import`.

**Comment by alannt777** [comment]
Same thing happens when your default distro is `docker-desktop` or `docker-desktop-data`.

**Comment by ktre2017** [comment]
Hi, I have the same issue

WSL is closing immediately

wsl.exe -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1

Please advise how to fix this

**Comment by alannt777** [comment]
@ktre2017 Does running `wsl -d Ubuntu-18.04` work?

**Comment by ktre2017** [comment]
> @ktre2017 Does running `wsl -d Ubuntu-18.04` work?

I tried but it didn't work.

**Comment by jmoteka** [comment]
@therealkenc  thanks! basically the default distro was docker

**Comment by Elia-238** [comment]
The same thing happened to me. 
I was able to find the problem after running as root: 
```bash
 wsl -d Ubuntu-22.04 --user root
```
Then I did:
```
su my_username
```
And I saw that there was a problem with my shell prompt.  
I fixed it, and then everything went back to normal.

**Comment by jasojone** [comment]
![image](https://user-images.githubusercontent.com/55056061/188169790-4c8c5042-79e3-4ee6-b1b4-c6df3e3795c0.png)
Not sure if any can help me with my issue. So I just got a refurb replacement note 8, and the WSL is not opening. I can't even install Ubuntu, I get this error for that,
![image](https://user-images.githubusercontent.com/55056061/188170158-78fe16d2-d872-4986-b702-dc427ce64365.png)

**Comment by anayarojo** [comment]
In my case, I didn't have `Ubuntu` distribution.

So, I installed it, using this command:
```bash
wsl --install -d Ubuntu
```

Then I used the following command to set the `Ubuntu` distribution as default:
```bash
wsl --set-default Ubuntu
```

Other useful commands: 
```
# To list all installed distributions
wsl --list --verbose
wsl -l -v

# To see the available distributions to install
wls --list --online
```

**Comment by majid-2002** [comment]
I can't install ubuntu distro using my wsl and open it . I tried to install the Ubuntu using this command

```bash
wsl --install -d Ubuntu
```
And then the Ubuntu shell opens and then it asks to press a key to continue but when I press the key the window immediately closes. And when I try to open again it shows you have no distros installed.

```bash
Windows Subsystem for Linux has no installed distributions.                                                            
Distributions can be installed by visiting the Microsoft Store:                                                        
https://aka.ms/wslstore              
```

**Comment by majid-2002** [comment]
> I can't install ubuntu distro using my wsl and open it . I tried to install the Ubuntu using this command
> 
> ```shell
> wsl --install -d Ubuntu
> ```
> 
> And then the Ubuntu shell opens and then it asks to press a key to continue but when I press the key the window immediately closes. And when I try to open again it shows you have no distros installed.
> 
> ```shell
> Windows Subsystem for Linux has no installed distributions.                                                            
> Distributions can be installed by visiting the Microsoft Store:                                                        
> https://aka.ms/wslstore              
> ```
> 
> I tried listing the distros using this command
> 
> ```shell
> wsl --list --verbose
> ```
> 
> but it shows no distros installed.


Finally solved this doing a kernel file from the wsl docs

[https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package](kernel-update)

**Comment by DeleMike** [comment]
@therealkenc Thank you!

**Comment by rin67630** [comment]
Same same here.
Win 11 just updated.
Freshly installed WSL Debian from the store.
wsl-exe -l -v 
issues 
* Debian Stopped 1

wsl -d debian 
issues 
Fehler beim bereit stellen eines Ihrer Datei Systeme. Führen Sie "dmesg" aus, um weitere Details anzuzeigen.
Which translate to 
Error mounting one of your file systems. Run dmesg to see more details.

All partitions are clean, the last one is Ext4

**Comment by ThomasSpare** [comment]
Had this problem to. Probably because some change to WSL as default.
Solution: If you already have Ubuntu installed
RUN THIS IN POWERSHELL
wsl --set-default Ubuntu

**Comment by sunchojack** [comment]
Had the same behavior with WSL from Company Portal; my suspicion was it's some company policies. cmd.exe didn't work, but powershell did (distro installation and further)
