### ISSUE TITLE
WSL2 rootfs directory disappeared

### ISSUE THREAD

**Issue by gjwatts** [microsoft/WSL#6221]
# Environment

```none
Windows build number:  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Your Distribution version: 16.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce
First off, I can get into my Ubuntu shell and run commands just fine.  From my Ubuntu shell, I can access my /c/ drive just fine.

I used to be able to access my ubuntu distro using Windows explorer at
`C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs`
However, I just checked and now the rootfs directory is gone.  All the directories before that are there and in `LocalState` I see a `temp` directory and file named `ext4.vhdx`, but no `rootfs`.

If I go into the Windows Explorer and try using `\\wsl$`, it delays for a few seconds and then comes back with the error:
```
Windows cannot access \\wsl$
Check the spelling of the name.  
Otherwise, there might be a problem with your network.  
To try to identify and resolve network problems, click Diagnose
```

If I go into a Ubuntu shell and run `explorer.exe .` instead of it bringing up an explorer window inside the Ubuntu file system, it opens it in my `Document` folder in the Windows file system.

I have not used the rootfs directory for several weeks now, but as far as I know, nothing major has happened to my PC other than a few MS updates.

#  Expected behavior
`C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs` should exist and allow me access into my Ubuntu file system.

# Actual behavior
The directory `C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs` has been removed somehow and I can not access my Ubuntu file system from within Windows.

**Comment by gjwatts** [comment]
Feedback link -> https://aka.ms/AAab32e

**Comment by JuiceDrinker** [comment]
Any update on this? Running into the exact same issue

**Comment by moonseokho85** [comment]
let me know about the error please~

**Comment by Lermamitibla** [comment]
Same thing, and cant open ext4.vhdx anyway

**Comment by ChristineChetty11** [comment]
Same problem

**Comment by andrasmakoviczki** [comment]
Same for me too.

**Comment by Jakejamesreid** [comment]
Having the same issue. Rootfs folder is missing. Any update on this issue?

**Comment by ayushm2003** [comment]
facing the same issue. Although i am able to see `\\wsl$\Ubuntu-20.04` folder in explorer but not able to access it via shell. Any updates on how can we resolve this?

**Comment by talhaanwarch** [comment]
same issue

**Comment by ajkessel** [comment]
ditto
