### ISSUE TITLE
insert personal configuration in /etc/resolv.conf

### ISSUE THREAD

**Issue by JonathanTaquet** [microsoft/WSL#6224]
Hello,

In order to make my network work properly when I am connected using a vpn I would like to add the following to my /etc/resolv.conf:

```
options rotate
options timeout:1
```

This is workaround because the nameserver list that is automatically generated is not in the correct order to access some servers through the vpn.

The problem is that each time vpn is disconnected I need to re-edit the file (but I want to keep dynamic generation to use correct nameserver if I am not connected though vpn)

It would be nice if the generator could use for instance: 
/etc/resolvconf/resolv.conf.d/head
/etc/resolvconf/resolv.conf.d/tail

**Comment by JonathanTaquet** [comment]
finally this does not solve my Issue, so maybe the feature is not needed

**Comment by s8186255** [comment]
test
