### ISSUE TITLE
Unable to use explorer.exe to open deeper folder in WSL2

### ISSUE THREAD

**Issue by maple3142** [microsoft/WSL#6230]
# Environment

```none
Windows build number: 10.0.20246.1
Your Distribution version: Pengwin Linux (Debian 11)
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Open WSL
2. `explorer.exe folder_a`
3. `explorer.exe folder_a/folder_b`

**WSL logs**: 

https://aka.ms/AAabw9t

#  Expected behavior

Both command opens the path in explorer.exe

# Actual behavior

Can't open the deeper folder: https://streamable.com/uqt58y

**Comment by therealkenc** [comment]
I was able to reproduce this locally. Without thinking too hard about it, it is not obvious (to me anyway) why `explorer.exe folder_a` works in the first instance. But it does.

Standard operating procedure would be:
```
$ explorer.exe $(wslpath -w folder_a/folder_b)
```

Or even better:
```
$ powershell.exe -Command "Start $(wslpath -w folder_a/folder_b)"
```

![image](https://user-images.githubusercontent.com/7049700/99310148-6f307800-280f-11eb-8ebb-44a1a0186a1c.png)
