### ISSUE TITLE
WSL Corrupted Windows 10 Dell XPS?

### ISSUE THREAD

**Issue by puremana** [microsoft/WSL#6239]
# Environment
Windows 10 (unsure of exact version but would be latest up to date personal)
```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```
WSL 1
# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

I am not 100% sure if WSL is the issue but figured it would be safer to report than not. After starting WSL on Windows 10 Dell XPS 15 9530 I changed directory a few times and did `code .` into one of my ruby projects as per usual however as soon as I did this, all applications on my computer froze and eventually after trying to ctrl alt delete without any luck I got a black screen only able to move the cursor.

When trying to start up the laptop I now get a internal hard disk not found error, no bootable devices.

After running hardware diagnostics all hardware is fine. Changing bios boot options however doesn't resolve anything. This would then seem like the OS is the issue and I was curious as to whether WSL specifically did something to corrupt windows.

Unable to provide any logs as not many people have a mini ssd reader that is necessary for these dell xps models and will likely just have to reformat with a new bootable OS anyway.

**Comment by onomatopellan** [comment]
That sounds like an excessive use of resources. Try reducing the RAM used for WSL2. See [this](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig).

**Comment by onomatopellan** [comment]
>WSL 1
Is your project in a `/mnt/*` folder? Try copying that folder in a `/home/*` one and call `code .` from there.

**Comment by puremana** [comment]
Update: After trying different bios settings and Windows Repair tools, I was unable to boot Windows and therefore had to reinstall Windows which has wiped everything. There is no Windows.old folder so I doubt I can recover anything or provide any logs.

> > WSL 1
> 
> Is your project in a `/mnt/*` folder? Try copying that folder in a `/home/*` one and call `code .` from there.

My projects were simply in a `projects` folder.

I think your previous comment might have been onto something if an excessive use of resources could have caused the crash and corruption of Windows 10 but if that was the case I'd say there is a fundamental issue with WSL if that is how it handles the crashes. My RAM and/or CPU usage would have been quite high at this point so this seems plausible.

The other explanation that people have mentioned is that Windows released a big update the day I had the crash which supposedly could have caused issues with my firmware as it is 5 years old and wasn't updated.

**Comment by benyaminl** [comment]
> 
> 
> Update: After trying different bios settings and Windows Repair tools, I was unable to boot Windows and therefore had to reinstall Windows which has wiped everything. There is no Windows.old folder so I doubt I can recover anything or provide any logs.
> 
> > > WSL 1
> > 
> > 
> > Is your project in a `/mnt/*` folder? Try copying that folder in a `/home/*` one and call `code .` from there.
> 
> My projects were simply in a `projects` folder.
> 
> I think your previous comment might have been onto something if an excessive use of resources could have caused the crash and corruption of Windows 10 but if that was the case I'd say there is a fundamental issue with WSL if that is how it handles the crashes. My RAM and/or CPU usage would have been quite high at this point so this seems plausible.
> 
> The other explanation that people have mentioned is that Windows released a big update the day I had the crash which supposedly could have caused issues with my firmware as it is 5 years old and wasn't updated.

ehm mine is 10 years old at this point and I doesn't get any problem with it. Anyway if it lead to no bootable found then there're problem on disk driver, that lead to spin until it's overheat and cause it can't be detected by the computer. I've seen that many times on my lab, especially if it's old HDD running windows 10.

**Comment by DanPinGF** [comment]
> When trying to start up the laptop I now get a internal hard disk not found error, no bootable devices.

Whoa! Sounds like WSL tried to replace your operating system. Don't try to use it next time if you're not sure what you're doing.

**Comment by puremana** [comment]
> > When trying to start up the laptop I now get a internal hard disk not found error, no bootable devices.
> 
> Whoa! Sounds like WSL tried to replace your operating system. Don't try to use it next time if you're not sure what you're doing.

Not sure what I am doing? I was sure of what I was doing, very basic commands. If this was a bug in WSL, it wasn't anything to do with my inputs

**Comment by DanPinGF** [comment]
> Not sure what I am doing? I was sure of what I was doing, very basic commands. If this was a bug in WSL, it wasn't anything to do with my inputs

Oh… sorry for the confusion. Perhaps your hard disk failed and corrupted the Windows 10 installation when running WSL?
