### ISSUE TITLE
WSL not being usable after computer startup when Fast Startup enabled

### ISSUE THREAD

**Issue by kevinbioj** [microsoft/WSL#6244]
# Environment

```none
Windows build number: 19042.630
Your Distribution version: Debian 10
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

**To reproduce this issue, you must have enabled (or left enabled, because it's default) the Fast Startup option in power settings.**
- Install WSL 2 and a Linux distribution of your choice.
- Configure an app to work with WSL : for this example use Visual Studio Code's WSL integration.
- Shutdown your computer (through the "Shutdown" option, not "Restart").
- Turn it back on.
- Open Visual Studio Code and notice that it cannot launch WSL properly.

**WSL logs**: 

#  Expected behavior

When using the Visual Studio Code example, the editor would load up correctly and the opened bash terminal should wait for user input.

# Actual behavior

We are getting some odd input/output errors probably due to Linux kernel not being recovered well from the "fast startup". If you disable this option, the whole Windows and Linux kernel are being shut down, like what "Restart" does (and which is why we never encounter this issue after a "Restart"), so everything is loaded up correctly at next boot.

At the moment, we either need to disable fast startup which can be pretty idiot because it offers a really great boot time on fast SSDs, or run "wsl --shutdown" when we login either ourselves or via a planned task (what I did for now).

I don't really know what would be a fix, maybe shutting down WSL properly when "Shutting computer down" or going deeper to find the actual root cause, no idea.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Goal of the diagnostic run would be to catch the "odd input/output errors".

**Comment by tomartarun89** [comment]
Whenever I enable WSL2 along with Virtual Machine Platform and move the mouse the screen starts to flicker. I have tried it several times but the issue still persists. WSL1 works fine.

**Comment by tmtron** [comment]
I have the same issue. Windows Restart is a workaround for now.
Windows version 10 Build 19041.630

**Comment by tomartarun89** [comment]
> I have the same issue. Windows Restart is a workaround for now.
> Windows version 10 Build 19041.630
> Not sure if this is related, but it stopped working after I have updated docker to 3.x

I was able to figure a workaround. Just disable the fast boot from BIOS. It will increase the boot time by 3-4 sec but the issue will be resolved. The issue is that the WSL is not getting initialized properly.

**Comment by xBsWYA2wYfuxW0FB** [comment]
> 
> 
> Whenever I enable WSL2 along with Virtual Machine Platform and move the mouse the screen starts to flicker. I have tried it several times but the issue still persists. WSL1 works fine.

I had the same exact problem with WSL1.
