### ISSUE TITLE
Error 0x80041002 while running kali linux and other linux

### ISSUE THREAD

**Issue by lakshaykathuria** [microsoft/WSL#6246]
![Screenshot (136)](https://user-images.githubusercontent.com/74535080/99236055-b2451800-281c-11eb-81e5-3ca7cd3c1d95.png)

```none
When i try to run any linux i receive this error
I had many restarted "windows sub system for linux",v hyper,virtual machine
but the problem is still there
any help??```

**Comment by therealkenc** [comment]
/dupe #5329. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in that issue.

**Comment by lakshaykathuria** [comment]
https://aka.ms/AAaclgq

**Comment by lakshaykathuria** [comment]
> /dupe #5329. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in that issue.

https://aka.ms/AAaclgq
