### ISSUE TITLE
AMD Radeon(TM) graphics error code 43

### ISSUE THREAD

**Issue by Dnewgate** [microsoft/WSL#6249]
After installing WSL 2 and rebooting my laptop, my resolution display settings greyed out. In device manager, under Display Adapters I noticed Error Code 43 under my graphics card. I tried to uninstall and reinstall the drivers but nothing changed. I also tried to uninstall WSL 2.

**Comment by craigloewen-msft** [comment]
Hi @Dnewgate could you please resubmit your issue with the issue template filled out? We need the info there to help accurately diagnose and try and resolve your issue! Thank you!
