### ISSUE TITLE
Video recording of Bash on Ubuntu on Windows doesn't work, but can record PowerShell

### ISSUE THREAD

**Issue by mobluse** [Microsoft/WSL#625]
I can record video using the built-in system (Xbox) in Windows 10 (started with Win+G) of PowerShell but not of Command or Bash on Ubuntu on Windows. In the latter cases it says my graphics card can't handle it. I can also record video from Cygwin. I have the same font in all consoles: DejaVu Sans Mono, 16. Display adapter: Intel(R) HD Graphics. Computer: LENOVO 80MJ Lenovo ideapad 100-15IBY. Operating System: Windows 10 Home (x64) Version 1607 (build 14379.0). Still a problem in Build 14955.1000.amd64fre.rs_prerelease.161020-1700.

Here is a video with PowerShell in Swedish:
https://youtu.be/7c6u9lJ6aW4

**Comment by zadjii-msft** [comment]
Huh. That's really peculiar, especially because the host window for cmd.exe, bash.exe and powershell.exe is the same, so I wouldn't think there would be a difference. I'm gonna tap in @bitcrazed to investigate some more.

**Comment by bitcrazed** [comment]
Hmmm. Odd indeed! PowerShell does appear to support background recording, but Bash and CMD do not! Will dig in and take a look.

**Comment by mobluse** [comment]
It works in Microsoft Windows [Version 10.0.17134.1] 17134.1.amd64fre.rs4_release.180410-1804.
