### ISSUE TITLE
WSL2 port forwarding is not working if accessed from java

### ISSUE THREAD

**Issue by Vigneshr6** [microsoft/WSL#6253]
# Environment
Windows 10 Home
```none
Windows build number: [Version 10.0.19042.630]
Your Distribution version: [Ubuntu 18.04]
Whether the issue is on WSL 2 and/or WSL 1: [WSL 2]
```

# Steps to reproduce
1) Start a webserver in WSL2 ubuntu 18.04
2) Access the webserver from a java HTTP client application from windows.

![image](https://user-images.githubusercontent.com/20204734/99671083-8b464a80-2a97-11eb-8e2f-20eaf63a70a9.png)

**WSL logs**: 

#  Expected behavior
WSL webserver should be accessible with localhost from java application.

# Actual behavior
could not connect the webserver with localhost. But I could connect with private IP from the same java application. Powershell `Invoke-WebRequest` command can also work with localhost.

**Comment by hb020** [comment]
See #4150
This has been discussed often, and MS does not seem to care about it. This behaviour is as designed.
My suggestion: go back to WSL or set up a real VM.

**Comment by therealkenc** [comment]
> 10.0.19042.630

Likely #4851 with a side of #5298, like #5706 ([message](https://github.com/microsoft/WSL/issues/5706#issuecomment-668170117)), others.

Moving over to discussion (similar #6240) for work-arounds to the specific use-case since there isn't a novel actionable.
