### ISSUE TITLE
Why my wsl.conf automount options not working?

### ISSUE THREAD

**Issue by suntong** [microsoft/WSL#6258]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`] `Microsoft Windows [Version 10.0.18363.1139]`
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] `Debian Release:        10`
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] WSL 1, `Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020`
```

# Steps to reproduce

Setup `/etc/wsl.conf` as such, then:

```sh
$ cat /etc/wsl.conf
[automount]
options = "metadata,case=dir"

$ ls -l /etc/wsl.conf
-rw-r--r-- 1 root root 42 2020-11-18 16:06 /etc/wsl.conf

sudo umount /mnt/d; sudo mount -t drvfs D: /mnt/d

mount -l | grep ^D
```

**WSL logs**: 

```
sudo umount /mnt/d; sudo mount -t drvfs D: /mnt/d

$ mount -l | grep ^D
D: on /mnt/d type drvfs (rw,relatime,case=off)
```

This is done after I exit all the WSL session and start it again, many times.

#  Expected behavior

mount option has both "`metadata,case=dir`"

# Actual behavior

mount option not haing "`metadata,case=dir`"

There is also a similar question at https://stackoverflow.com/questions/59959090/ that doesn't have an answer, which basically asks the same thing as this.

**Comment by 0xbadfca11** [comment]
Why are you run umount command?
When you run the mount command manually, that is not automount.

**Comment by suntong** [comment]
Good point! 

The reason that I did that was I saw the "`metadata,case=dir`" was not there in the `mount -l` output, when I exited _**all**_ the WSL session and start it again. Will play more and see...

**Comment by suntong** [comment]
- exit all the WSL session and start it again won't work
- rebooting will
