### ISSUE TITLE
Error 4294967295 after wake from hibernation on Surface Pro X / arm64

### ISSUE THREAD

**Issue by dennisameling** [microsoft/WSL#6259]
# Environment

```none
Windows build number: 10.0.19042.630
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. On a Surface Pro X, hibernate the device (this happens automatically after a few hours).
2. Start the device (note: if you don't see the Windows boot logo first, the device wasn't in hibernation mode!).
3. Open Task Manager, notice that the `Vmmem` process is using ~20% CPU constantly.
4. Try to open the Ubuntu terminal. Nothing will happen for a few seconds, after which the process crashes with exit code 4294967295.

**WSL logs**: 

Added through Feedback Hub: https://aka.ms/AAafqed

#  Expected behavior

WSL2 should still be working after resuming from hibernation on the Surface Pro X.

# Actual behavior

WSL2 is hanging (CPU loop) and crashing after resuming from hibernation on the Surface Pro X.

**Comment by maxboone** [comment]
+1

**Comment by maxboone** [comment]
Also not able to run (something like) htop in the VM to see why the distribution is hanging:

```
C:\>wsl -d fedora htop
The Windows Subsystem for Linux instance has terminated.
```

Trying to start a terminal results in

```
The Windows Subsystem for Linux instance has terminated.
[process exited with code 4294967295]
```

Yet

```
C:\>wsl --list -v
  NAME          STATE           VERSION
* Fedora        Running         2
  Debian        Stopped         1
  debian-x86    Stopped         2
```

And
![image](https://user-images.githubusercontent.com/6454510/140663517-95cf36f3-8432-4762-a491-de65524c5058.png)

Running on Surface Pro X 2

**Comment by maxboone** [comment]
@dennisameling does this happen on your set-up all the time, or just sporadically, as I feel that it often does this but sometimes resolves on it's own as well. It especially happens often in combination with running Visual Studio Code (using the WSL-connection / so not in WSLg).

**Comment by maxboone** [comment]
Possibly related - https://github.com/microsoft/WSL/issues/6982#issuecomment-953220476

**Comment by mmichal3** [comment]
I have this problem as well. I can get back to a Linux prompt if I open taskman and kill windows services for Linux. 

WSLg ( aarch64 ): 1.0.34+Branch.main.Sha.a6f7a68801278da2a3ba96b9e6a631e5f67d1adb
Mariner: VERSION="1.0.20220226"
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 6eebe8febc213ba5034737e11c5ab36b3f0bbacc
versions.txt (END)

**Comment by frumioj** [comment]
I have this exact issue, only NOT on aarch64 - is there a related/corresponding issue with x86_64 and non-Surface laptops?
