### ISSUE TITLE
WSL2 loosing network at night/hibernate with VPN

### ISSUE THREAD

**Issue by 4integration** [microsoft/WSL#6261]
# Environment
```
C:\>ver
Microsoft Windows [Version 10.0.18363.1139]

$ lsb_release -r
Release:        20.04

$ cat /proc/version
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

PS C:\> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-18.04           Stopped         2
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu-20.04           Running         2

```

# Steps to reproduce
* Doing a fresh boot of computer
* Login
* Login to VPN (Pulse Secure 9.1.9 (4983) )
* Start WSL2 with Ubuntu 20.04
* WSL networking works fine

End of the workday
* Disconnecting VPN overnight and/or puts computer to hibernate

Next workday
* Ev starts computer from hibernate and login to VPN
* WSL networking is not working
* Tried `wsl --shutdown` and started WSL but doesn't work 
* Only a complete reboot solves the issue

#  Expected behavior

Working WSL network after hibernate

# Actual behavior

See "Steps to reproduce" above
I get the feeling that WSL starts quicker after `--shutdown` than after a reboot.
Any other command to execute to do a "deeper" restart of WSL ?

**Comment by hb020** [comment]
See #4150
This has been discussed often, and MS does not seem to care about it. This behaviour is as designed.
My suggestion: go back to WSL or set up a real VM.

**Comment by therealkenc** [comment]
/dupe #4992 as the active landing zone.
