### ISSUE TITLE
Add support for Windows style file path format to basic Linux commands

### ISSUE THREAD

**Issue by alphavector** [microsoft/WSL#6266]
**Is your feature request related to a problem? Please describe.**
Hi. Add support for the Windows style file path format to the basic Linux commands as it is done for PowerShell. I would like to get the same result inside Ubuntu as I get PowerShell.
Windows version: 10.0.19042 
Ubuntu version: Ubuntu 20.04.1 LTS
PowerShell version: 5.1.19041.610

**Describe the solution you'd like**
The solution is to add Windows path support.

**Describe alternatives you've considered**
Now the alternative is to lead the way with the correct Unix format on your own.

**Additional context**
![](https://i.imgur.com/jGdZzfM.png)

**Comment by alannt777** [comment]
I believe that you can do that using `wslpath`

**Comment by alphavector** [comment]
Wow, I did not know about `wslpath`. Thank you .
