### ISSUE TITLE
wsl --import fails with: Parameter is incorrect after successful export

### ISSUE THREAD

**Issue by excelsi** [microsoft/WSL#6267]
Microsoft Windows [Version 10.0.19042.630]
Ubuntu actual release
WSL2

Tried importing WSL after successful export
https://blog.iany.me/2020/06/move-wsl-to-another-drive/

Exporting works great but importing fails:
E:\VM\WSL>wsl --import Ubuntu E:\VM\WSL\Ubuntu E:\VM\WSL\ubuntu.tar
The parameter is incorrect.

Any help?

**Comment by excelsi** [comment]
Solved it
Did not use elevated CMD

**Comment by DKalenscher** [comment]
Maybe you should put a note as to how you solved it so other can referrence?
