### ISSUE TITLE
Python3 TemporaryFile().truncate() fails in WSL2 (breaking pytest)

### ISSUE THREAD

**Issue by DerekParks** [microsoft/WSL#6268]
# Environment
```
Windows build number: Microsoft Windows [Version 10.0.19041.630]
Your Distribution version: Ubuntu  18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 - Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

Creating a temp file in python and calling truncate on it doesn't work in WSL2. This came up when running a set of `pytests` that work in a linux vm but don't work on WSL2. 

`$ python3 -c "import tempfile; tempfile.TemporaryFile().truncate()"`

I can provide an strace if needed but I'm hoping it will be easy enough to reproduce.

#  Expected behavior

In a ubuntu 18.04 vm, the above command succeeds without error.

# Actual behavior

On WSL2 I get the following error.

```
$ python3 -c "import tempfile; tempfile.TemporaryFile().truncate()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by therealkenc** [comment]
That error is from userspace; you are on a VM in WSL2. A gist to a threaded `strace(1)` log would show what file is missing.

![image](https://user-images.githubusercontent.com/7049700/99994251-9e923800-2d6d-11eb-9017-95b7868bf798.png)

**Comment by DerekParks** [comment]
@therealkenc What version of python are you using? I was using 3.6. Maybe I need to upgrade.

Either way, it looks like my issue not WSL's. Feel free to close. Sorry to trouble.

**Comment by therealkenc** [comment]
No trouble. I'll move over to discussion. Python version is probably not it.

![image](https://user-images.githubusercontent.com/7049700/99998177-1ca50d80-2d73-11eb-8e5f-f77b2b1718e0.png)
