### ISSUE TITLE
wsl mount external USB drive doesn't work

### ISSUE THREAD

**Issue by Darkvater** [microsoft/WSL#6270]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20262.1010]
Your Distribution version: Debian GNU/Linux 10 (buster)
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce
Followed the instructions to update windows to dev channel, install wsl2 and all pre-requisites (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then to mount the external drive. It is an external USB3 seagate 2TB drive formatted as ext4 used in my raspberry pi4 previously

```
PS C:\WINDOWS\system32> wmic diskdrive list brief
Caption                               DeviceID            Model                                 Partitions  Size
SAMSUNG MZMTD256HAGM-000MV            \\.\PHYSICALDRIVE0  SAMSUNG MZMTD256HAGM-000MV            6           256052966400
Seagate BUP Slim BK SCSI Disk Device  \\.\PHYSICALDRIVE1  Seagate BUP Slim BK SCSI Disk Device  1           2000396321280
PS C:\WINDOWS\system32> wsl --mount \\.\PHYSICALDRIVE1 --partition 1
The disk \\.\PHYSICALDRIVE1 was successfully mounted under the name 'PHYSICALDRIVE1p1'. The mountpoint can be found under the path pointed to by the automount setting (default: /mnt/wsl).
To unmount and detach the disk, run 'wsl --unmount \\.\PHYSICALDRIVE1'.
```

From the above all looks good, however /mnt/wsl only includes a single file
```
tomi@ARRAKIS:~$ ls -al /mnt/wsl
total 8
drwxrwxrwt 2 root root   60 Nov 22 23:26 .
drwxr-xr-x 4 root root 4096 Nov 22 23:11 ..
-rw-r--r-- 1 root root  198 Nov 22 23:26 resolv.conf
```

**WSL logs**: 
link to feedback hub: https://aka.ms/AAadzh1
There is nothing in dmesg or journalctl.
```
PS C:\WINDOWS\system32> wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType                 Model                                 Name                Partitions
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media     SAMSUNG MZMTD256HAGM-000MV            \\.\PHYSICALDRIVE0  6
              {3, 4}        {"Random Access", "Supports Writing"}                        \\.\PHYSICALDRIVE1  SCSI           TRUE         External hard disk media  Seagate BUP Slim BK SCSI Disk Device  \\.\PHYSICALDRIVE1  1
```

#  Expected behavior

access to data from ext4 drive

# Actual behavior

no files

**Comment by Darkvater** [comment]
So, played around a bit more and got it working. But!
* the reason things didn't mount was because for some reason the ext4 partition wasn't clean. However this information wasn't available in dmesg (more about that later) so I had a hard time finding the reason. As soon as I cleaned the system it worked. Hurray!

###BUT###
* things only seem to be working from under an administrator account. Obviously I need to run the mount as an admin (which I can do from a normal user account selection "run as adminisitrator" for powershell, but the mounted drive only shows up for the admin user. 
  * I got into wsl from the admin powershell (for which I need to install a linux distribution actually being logged in as an admin, otherwise it launches a wsl under a normal user) the drive is mounted, seen, and accessible
```
[  428.331862] scsi 0:0:0:2: Direct-Access     Seagate  BUP Slim BK      0304 PQ: 0 ANSI: 6
[  428.341969] sd 0:0:0:2: Attached scsi generic sg2 type 0
[  428.344837] sd 0:0:0:2: [sdc] 3907029167 512-byte logical blocks: (2.00 TB/1.82 TiB)
[  428.344845] sd 0:0:0:2: [sdc] 4096-byte physical blocks
[  428.348894] sd 0:0:0:2: [sdc] Write Protect is off
[  428.348902] sd 0:0:0:2: [sdc] Mode Sense: 0f 00 00 00
[  428.369624] sd 0:0:0:2: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  428.369637] sd 0:0:0:2: [sdc] Optimal transfer size 33553920 bytes not a multiple of physical block size (4096 bytes)
[  428.398699]  sdc: sdc1
[  428.407492] WSL2: Mapped partition 1 from device /sys/block/sdc to /dev/sdc1
[  428.487998] sd 0:0:0:2: [sdc] Attached SCSI disk
[  429.542677] EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts:
```
  * however using my local users's wsl the drive is not attached, nor is it available in windows explorer

It seems the drive is only mounted for the administrator user (and since you  need to run mount as an admin, only ever for the admin user) and there is no way to access it as a normal non-admin user.

Will this be resolved at some point or is it expected behaviour? In my book it would go against every security advice to run windows as an admin user for day-to-day use.

**Comment by bwanaaa** [comment]
similar problem here:
 ```
wmic diskdrive list brief
Caption                                DeviceID            Model                                  Partitions  Size
ASMT ASM1156-PM SCSI Disk Device       \\.\PHYSICALDRIVE5  ASMT ASM1156-PM SCSI Disk Device       3           2000396321280
Samsung SSD 870 QVO 4TB                \\.\PHYSICALDRIVE2  Samsung SSD 870 QVO 4TB                1           4000784417280
NVMe Samsung SSD 970 SCSI Disk Device  \\.\PHYSICALDRIVE3  NVMe Samsung SSD 970 SCSI Disk Device  1           2000396321280
Samsung SSD 850 EVO 500GB              \\.\PHYSICALDRIVE0  Samsung SSD 850 EVO 500GB              3           500105249280
Samsung SSD 860 EVO 1TB                \\.\PHYSICALDRIVE1  Samsung SSD 860 EVO 1TB                1           1000202273280
Samsung SSD 970 EVO Plus 1TB           \\.\PHYSICALDRIVE4  Samsung SSD 970 EVO Plus 1TB           3           1000202273280
```


`wsl --mount \\.\PHYSICALDRIVE5 --partition 1
`

gives


`Invalid command line option: --mount`

**Comment by MX10-AC2N** [comment]
I've the issue with "wsl --mount \\.\PHYSICALDRIVE2 --partition 1"
gives => Invalid command line option: --mount
there is a another way for access to my usb stick with armbian os on it (ext4..)

**Comment by Kottoz** [comment]
i have that same issue, and i can't solve it

**Comment by MX10-AC2N** [comment]
Hi @Kottoz 
 indeed unless you are insider and have the correct version it is impossible to mount a usb (ext4) but I found the solution using "linux files system for windows" from Paragon, there is the full version is a free trial for 7 days ..
 To be used with "Run As Date" as we are still in the free trial period, please understand ..
 ;-)

**Comment by Amondale** [comment]
So here's a mount of the Paragon-mounted L: drive, for some reason I keep getting "function not implemented" though:

L:             110961664  15348804  95612860  14% /mnt/l
~$ ls /mnt/l
ls: reading directory '/mnt/l': Function not implemented

here is /etc/fstab:
L: /mnt/l drvfs ro,noatime,uid=1000,gid=1000 0 0


Is use of cifs preferable to Paragon? ext2fsd didn't work for me whatsoever. 
My build:
Version	10.0.19043 Build 19043 [21H1]

Wondering which insider build will allow direct mounting of ext4 volumes from WSL2/g?

**Comment by chrisbitmead** [comment]
@Amondale interesting, I still haven't got the windows preview version that supports wsl --mount to try it myself. Certainly, it would not work with Paragon, and if one is going to go down the wsl route, one might as well uninstall it I think.

At first I thought this wsl feature was going to be having the Linux kernel directly access the partition. But since the wsl command doesn't ask for a Linux instance... and since some of the commands explicitly say you can access it from any instance... it sounds like the ext4 support is actually in WSL, and they've set up a conduit to their custom Linux kernel. Sounds ok, but they should then go the whole hog and give it a drive letter for ease of Windows access. Though I suppose you can still access it with the \\wsl$ incantation? Though I'm not sure if all Windows programs will be happy with that or not.

**Comment by Amondale** [comment]
@chrisbitmead  interesting as well; I think you're correct about ext4 support being in the WSL kernel itself. 

n.b., however, I am not seeking a "Paragon replacement" that can read/write an ext4 partition in Windows; rather, if I want to munge through a TB or 2 of data or run a large-scale mysql instance, I don't want to create a ballooning VHDX file on my C: drive to do so; that's what 4T external USB3/USB-C drives are built for!

Happily this is not an urgent need. I can for the moment boot happily off one of these 4T-8T USB drives, and have the full goodness (and use the full memory footprint of my PC rather than having to reserve 4-8 GB for the host Windows OS. 

What I should do is to attach an external disk containing to ext4 partitions to a running Hyper-V VM running a flavor of Linux; then I'll be sure Canonical could actually achieve the ask with a little effort.

With the Paragon "solution" you have antivirus and other resident processes scanning all windows mounted drives, causing extra CPU consumption. However, with WSL I can at least have the protection of the VPN software that for the moment runs only on Win32, affording extra protection (needed more and more on Linux and Android systems). Just a fact of mid-21st century life, I'm afraid.

**Comment by Amondale** [comment]
[https://github.com/microsoft/WSL/issues/5997](this) is worth a peek as well. The --mount subcommand has been around at least a year, just that the --partition sub-subcommand is declared invalid, evidently, if one of the partitions is in use by host OS (Windows).

**Comment by Amondale** [comment]
Finally got it to work, with a snag or 3 along the way.  My external USB drive has 4 primary partitions, one extended ext4 partition, as follows:
o FAT32 Linux UEFI boot partition
o ext4 (converted from swap, currently holds swapfile)
o ext4 (extended partition was created out of this one at Ubuntu 20.04 installation)
o ntfs (with automount on in Windows 11, this becomes F: drive and keeps wsl --mount from working)

So the only sequence that worked correctly for me was to first turn off automount through DISKPART, reboot, run (admin powershell prompt):

wsl --mount \\.\PHYSICALDRIVE1
The disk \\.\PHYSICALDRIVE1 was attached from WSL2, but failed to mount (error code: -22). For more details, run 'dmesg' inside WSL2.
To detach the disk, run 'wsl --unmount \\.\PHYSICALDRIVE1'.

dmesg showed:

[  316.807969] sd 0:0:0:3: [sdd] Synchronizing SCSI cache
[  316.808523] sd 0:0:0:3: [sdd] Synchronize Cache(10) failed: Result: hostbyte=0x01 driverbyte=0x00
[  336.955500] scsi 0:0:0:3: Direct-Access     Netac    Mobiledatastar   1101 PQ: 0 ANSI: 6
[  336.958055] sd 0:0:0:3: Attached scsi generic sg3 type 0
[  336.962686] sd 0:0:0:3: [sdd] 488397168 512-byte logical blocks: (250 GB/233 GiB)
[  336.962689] sd 0:0:0:3: [sdd] 4096-byte physical blocks
[  336.963592] sd 0:0:0:3: [sdd] Write Protect is off
[  336.963595] sd 0:0:0:3: [sdd] Mode Sense: 0f 00 00 00
[  336.965544] sd 0:0:0:3: [sdd] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  336.965548] sd 0:0:0:3: [sdd] Optimal transfer size 33553920 bytes not a multiple of physical block size (4096 bytes)
[  336.972219]  sdd: sdd1 sdd2 sdd3 < sdd5 > sdd4
[  336.973540] EXT4-fs (sdd): VFS: Can't find ext4 filesystem
[  336.973561] ERROR: Mount:2528: mount(/dev/sdd, /share/PHYSICALDRIVE1, ext4, 0x0, ) failed
[  336.973563] 22
[  336.978538] sd 0:0:0:3: [sdd] Attached SCSI disk

which was promising, assumed the errors were harking to the failure to map the extended partition. So then, ran:
PS >wsl --unmount \\.\PHYSICALDRIVE1
PS >wsl --mount \\.\PHYSICALDRIVE1 --partition 5
The disk \\.\PHYSICALDRIVE1 was successfully mounted under the name 'PHYSICALDRIVE1p5'. The mountpoint can be found under the path pointed to by the automount setting (default: /mnt/wsl).
To unmount and detach the disk, run 'wsl --unmount \\.\PHYSICALDRIVE1'.

And, voila:
/mnt/wsl/PHYSICALDRIVE1p5$ ls -l
total 108
drwxr-xr-x  23 root root  4096 Sep 28 10:23  ./
drwxrwxrwt   5 root root   120 Oct  9 12:22  ../
drwxr-xr-x   2 root root  4096 Aug 19 22:03 'System Volume Information'/
lrwxrwxrwx   1 root root     7 Aug 20  2020  bin -> usr/bin/
drwxr-xr-x   4 root root  4096 Oct  5 12:35  boot/
...

**Comment by Amondale** [comment]
A bit of a p.s.: no need to `chown` (nor is it probably advisable if it is a bootable partition) as long as the same username is used in wsl for the directories you want to access, or you plan to sudo -i or the like elsewhere.
