### ISSUE TITLE
Error when importing CSV file into Excel from WSL location - The supplied file path must be a valid absolute path.

### ISSUE THREAD

**Issue by olivier-monaco** [microsoft/WSL#6273]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.572]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

- Create a CSV file in WSL environment, eg. /home/olivier/a.csv
- Open Excel, go to "Data" tab and choose "From Text" (on left)
![image](https://user-images.githubusercontent.com/3101457/99971255-352a1d80-2d9d-11eb-9513-56dddba4ee42.png)
- Navigate to your CSV file. You will have a path like \\wsl$\Ubuntu-20.04\home\olivier\a.csv
![image](https://user-images.githubusercontent.com/3101457/99971407-67d41600-2d9d-11eb-9bcf-2cc4f91d2cf6.png)
- Validate open dialog box
- Excel will show an error box with "The supplied file path must be a valid absolute path."
![image](https://user-images.githubusercontent.com/3101457/99971484-7fab9a00-2d9d-11eb-821b-034524ae2221.png)

# Work around

- Mount \\wsl$\Ubuntu-20.04 as W:
- Import data from W:\home\olivier\a.csv
- Excel load data and show the import dialog box

# Notes

- Same problem on another workstation.
- No problem with other UNC path like CSV files on file servers (ex. \\my-server\olivier\a.csv).

**Comment by benhillis** [comment]
I believe this will work in current Insider builds that use \\\\wsl.localhost (instead of \\\\wsl$).
