### ISSUE TITLE
WSL/Bash closing immediatly upon starting on Windows 10

### ISSUE THREAD

**Issue by fabi262** [microsoft/WSL#6274]
When trying to start WSL/Bash using Run a terminal opens but after a split second it closes again. Trying to start from CMD doesnt print anything in the terminal and there is no window opening. I tried disabling and enabling the windows-feature for wsl. In some forums I saw there should be a folder in appdata/local called lxss but there is no such folder for me.
Im using win 10 education version 1909
Dev Mode is on if that is even relevant

**Comment by DHowett** [comment]
Can you try running...

`wsl bash -l -i -x`

from another console window?

If WSL is getting far enough along, this will produce a list of shell commands that are being run on startup. We can look further at that list to determine what’s failing.

**Comment by therealkenc** [comment]
Also please post output of `wsl.exe -l -v` to get a handle on the context.

**Comment by fabi262** [comment]
![image](https://user-images.githubusercontent.com/57033353/100010287-55270480-2dd0-11eb-9957-0d9a59167d0a.png)

**Comment by DHowett** [comment]
Excellent. And if you use `wsl -e /bin/bash -l -i -x`? The `-e` should attempt to invoke your shell directly.

**Comment by fabi262** [comment]
![image](https://user-images.githubusercontent.com/57033353/100010716-f7df8300-2dd0-11eb-8f05-634a355fea39.png)

**Comment by fabi262** [comment]
wsl.exe -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
  Ubuntu                 Stopped         1


Totally forgot this, sry

**Comment by fabi262** [comment]
Are pictures better than text?

**Comment by DHowett** [comment]
Text is almost always better. It looks like your _default_ WSL distribution is the docker service distribution. That'll explain why it's not working properly.

You can run `wsl --set-default Ubuntu` and WSL should start working again. It looks like your ubuntu install is in WSL 1 mode instead of WSL 2 mode, but that's fine if it's what you want.

**Comment by fabi262** [comment]
Well thank you
That fixed it
It also seems to work on "docker-desktop"
Just not on "docker-desktop-data"
Thank you again for the quick help
Hopefully I can get back on track now

**Comment by therealkenc** [comment]
Same #6218 (➡️ #6024)
