### ISSUE TITLE
After upgrading my bios to 1.3.0 I get There are no more endpoints available 

### ISSUE THREAD

**Issue by chiptus** [microsoft/WSL#6275]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.630]
Your Distribution version: 18.04
Whether the issue is on WSL 2 and/or WSL 1: wsl 2
```

# Steps to reproduce

Not sure. Everything worked perfectly until yesterday when I upgrade my bios to 1.3.0 (dell xps 9300) and some more drivers. Since then I can't open WSL and I get:

```
There are no more endpoints available from the endpoint mapper.

[process exited with code 4294967295]
```

**WSL logs**: 

#  Expected behavior
To be able to use WSL

# Actual behavior
```
There are no more endpoints available from the endpoint mapper.

[process exited with code 4294967295]
```

https://aka.ms/AAaee42

**Comment by Koesters** [comment]
Have you (re)enabled Hyper v in BIOS?

**Comment by chiptus** [comment]
virtualization is enabled, @Koesters. thanks

**Comment by chiptus** [comment]
> virtualization is enabled, @Koesters. thanks

but it didn't fix my issue

**Comment by therealkenc** [comment]
Ref #4403

**Comment by chiptus** [comment]
Thanks, seems like the same error, but couldn't fix it using the approaches suggested there

**Comment by chiptus** [comment]
I had to reinstall windows for this to be fixed.
