### ISSUE TITLE
Downloadable Alpine Linux distro for WSL2

### ISSUE THREAD

**Issue by ibeketov** [microsoft/WSL#6276]
Currently is possible to manually download Windows Subsystem for Linux distro packages for all supported systems except Alpine Linux ( [Downloading distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distros)).  AL is a great minimal distro especially as a hosting system for Docker, so it would be great if it will be possible to download it manually.

**Comment by 8549** [comment]
https://www.microsoft.com/en-us/p/alpine-wsl/9p804crf0395?activetab=pivot:overviewtab

**Comment by Biswa96** [comment]
Here is another popular one https://github.com/yuk7/AlpineWSL

**Comment by ibeketov** [comment]
> https://www.microsoft.com/en-us/p/alpine-wsl/9p804crf0395?activetab=pivot:overviewtab
Thank you but this is the distro installation from MS Store but it would be great to have the downloadable version.

> Here is another popular one https://github.com/yuk7/AlpineWSL
Thank you it looks great but I would prefer to have the official distro from MS

**Comment by therealkenc** [comment]
#6190
