### ISSUE TITLE
Lost distros+data after disabling/reenabling WSL features

### ISSUE THREAD

**Issue by 8549** [microsoft/WSL#6277]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20262.1010]
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

I had WSL2 installed since its release and it always worked while having VirtualBox installed. Then sometimes ago it stopped working, and the solution was to uninstall VirtualBox. Last week I needed to emulate a graphical Linux environment so I disabled Windows features for Hyper-V, WSL, and Virtual Machine Platform in order to disable WSL and make VirtualBox work. I installed VirtualBox+extensionpack and used it a bit. Today i didn't need VirtualBox anymore, I re-enabled the 3 features and then uninstalled VirtualBox. Restarted my system and my distros, with all my user data, were gone. The folders in `%appdata%/[...]/LocalState/rootfs` were empty. `wsl --list` reported no distros installed. Launching the distros app from the Start Menu resulted in the distro asking for a kernel update.

I lost all my distros data, including private keys for a number of servers, code changes i didn't push yet to remote repos, etc.

**WSL logs**: N/A

#  Expected behavior

WSL distros would survive a feature disable/reenable.

# Actual behavior

I lost my files, configs, etc.

I don't know who is the culprit here. If the features re-enabling before uninstalling VirtualBox, a Windows update in the last days (i'm on Insiders Preview Fast Ring), the VirtualBox uninstall. If this is intended behavior then my bad, but i would have expected a warning somewhere.

**Comment by esteban-benitez** [comment]
I lost my files too after system repair in powershell.

**Comment by sirredbeard** [comment]
> I don't know who is the culprit here.

It was disabling WSL.

I know this is little consolation now but in the future, you can back up WSL distros with wsl.exe --export... and then restore them later with wsl.exe --import...

VirtualBox can co-exist with WSL 2 but you have to use the optional Hyper-V backend, not VirtualBox's own type 2 virtualization.

>  I needed to emulate a graphical Linux environment

In the future you should try out Quick Create in Hyper-V to quickly set up Linux desktops.

**Comment by 8549** [comment]
Lesson learned, I will export backups of the distros from now on.

Just out of curiosity, which one of the three Windows features causes WSL to be erased from disk?

**Comment by Baalkikhaal** [comment]
> you can back up WSL distros with wsl.exe --export... and then restore them later with wsl.exe --import...

Do you suggest to regularly backup the WSL distro? Is there a central location where important trade practices is recorded? I am intending to migrate from a casual WSL2 tester to a dependent user to publish my github pages using jekyll from WSL2 instead of Ruby on Windows installation.

**Comment by Baalkikhaal** [comment]
[WSL FAQ on backing up distros](https://docs.microsoft.com/en-us/windows/wsl/faq#how-can-i-back-up-my-wsl-distros--or-move-them-from-one-drive-to-another-) 😄

**Comment by bpulliam** [comment]
There was a bug where the WSL state was not being preserved on OS upgrade (such as taking the next Insider build) if WSL was turned off.  The repro would be "1) turn off WSL, 2) install new build, 3) turn on WSL and find state missing".  The fix will work once you take build 21376, so on upgrades FROM that build to a higher one (not upgrading TO that build).
