### ISSUE TITLE
apt install problems with 20262

### ISSUE THREAD

**Issue by blackliner** [microsoft/WSL#6279]
# Environment

```none
Windows build number: [Version 10.0.20262.1010]
Your Distribution version: [Release:        18.04]
Whether the issue is on WSL 2 and/or WSL 1: [2]
```

# Steps to reproduce
I am setting up a new machine, went straight for the newest insider build, and I do have many errors trying to install some packages. At some point it was libboost-all-dev, I unregistered the distro and started from scratch. It was libboost 2 more times, no I am stuck with cuda...
I used the new `wsl --install -d Ubuntu-18.04` if that is relevant.

Oh, also, the very first time, `sudo apt update` ran, but basic things like `ninja-build` were not found by apt, that was my first reset of that wsl distro.

`sudo apt install cuda-11-0`

Errormessage:
```
dpkg: error processing package cuda-runtime-11-0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of cuda-11-0:
 cuda-11-0 depends on cuda-runtime-11-0 (>= 11.0.3); however:
  Package cuda-runtime-11-0 is not configured yet.

dpkg: error processing package cuda-11-0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of cuda-demo-suite-11-0:
 cuda-demo-suite-11-0 depends on cuda-runtime-11-0; however:
  Package cuda-runtime-11-0 is not configured yet.

dpkg: error processing package cuda-demo-suite-11-0 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nvidia-compute-utils-455
 cuda-drivers-455
 nvidia-driver-455
 cuda-drivers
 cuda-runtime-11-0
 cuda-11-0
 cuda-demo-suite-11-0
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**WSL logs**: 

#  Expected behavior
It should just install without error.

# Actual behavior
Errors

**Comment by blackliner** [comment]
I had some other strange problems with Windows docker containers not being able to pull layers, I had to disable some hardware acceleration with my AVM fritz!box router. Maybe the package is corrupted during the download?

**Comment by blackliner** [comment]
Now I ran `wsl --update`
```
Checking for updates...
Downloading updates...
Installing updates...
This change will take effect on the next full restart of WSL. To force a restart, please run 'wsl --shutdown'.
Kernel version: 5.4.72
```
Did I have 4.xx previously and this was the problem?

**Comment by sirredbeard** [comment]
> basic things like ninja-build were not found by apt

That is odd. You ran sudo apt update so the apt cache should be fresh.

> cuda-runtime-11-0

Are you installing these from the Nvidia apt repo or the Ubuntu restricted repo?

Have you tried using Ubuntu 20.04?

**Comment by blackliner** [comment]
> Are you installing these from the Nvidia apt repo or the Ubuntu restricted repo?

I used the following:
```bash
NVIDIA_GPGKEY_SUM=d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5
NVIDIA_GPGKEY_FPR=ae09fe4bbd223a84b2ccfce3f60f4b3d7fa2af80
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +5 > cudasign.pub
echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub
echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
```

> Have you tried using Ubuntu 20.04?

No, we are bound to using 18.04

**Comment by sirredbeard** [comment]
I do not have an explanation for not being able to install ninja-build from Ubuntu, other than a temporary network glitch. Are you able to install it now?

As for the broken dependencies, you appear to be installing CUDA from the Nvidia repository, which is the right thing to do. If there is a dependency breakage in their package then perhaps [reporting in their forum](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-on-windows-subsystem-for-linux/303) would be helpful.

**Comment by blackliner** [comment]
I think it has something todo with the system, because if I do that on my device (same hardware and software setup), it works.
