### ISSUE TITLE
[WSL2] Getting Error 0x80041002 Installing or Upgrading WSL2 (Not Comodo Firewall Issue)

### ISSUE THREAD

**Issue by Asiimoviet** [microsoft/WSL#6284]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.19041.630]
Your Distribution version: Kali Linux / ArchWSL
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (WSL 1 not effected)
```

# Steps to reproduce

Method 1: Change the default version to 2 and install whether kali linux or archwsl
Method 2: Upgrading an existed wsl instance to 2

**WSL logs**: This is the upgrading capture
[Critical_{1B96BCC2-1B1B-4_ce5eb7b0111624146853d1dedaaa1f66bf82b7ea_00000000_cab_d3331430-10c8-4b0d-8b81-841ffd9d92e1.zip](https://github.com/microsoft/WSL/files/5606782/Critical_.1B96BCC2-1B1B-4_ce5eb7b0111624146853d1dedaaa1f66bf82b7ea_00000000_cab_d3331430-10c8-4b0d-8b81-841ffd9d92e1.zip)

#  Expected behavior
The wsl being upgraded to wsl2 or installed as a wsl2 instance

# Actual behavior
Cannot be upgraded and get an error: 0x80041002
![image](https://user-images.githubusercontent.com/66727875/100428690-3f1a8c00-30cf-11eb-8b76-2a714ffc08c7.png)
![image](https://user-images.githubusercontent.com/66727875/100428955-9caed880-30cf-11eb-9d30-2d230454cf5b.png)

I know there are duplicate issues, but I have read them and did the suggested moves. Basically none of them worked.
Most of the known cases I found are caused because of Comodo firewall, but I have never installed that thing.
I tried reinstalling it, re-enable wsl feature, uninstalling something that might causes the 'loopback' thing, basically everything I could do.

**Comment by sirredbeard** [comment]
> Most of the known cases I found are caused because of Comodo firewall

Several issues are caused by third-party security software, like Comodo, Kaspersky, and others. You do not have any of them installed?

**Comment by Asiimoviet** [comment]
@sirredbeard unfortunately I don't have any of them installed.
Is Windows defender accounting one?

**Comment by Biswa96** [comment]
> You do not have any of them installed?

Smelling monopoly 🤔

**Comment by sirredbeard** [comment]
> Is Windows defender accounting one?

No, Windows Defender doesn't cause issues.

Is this a company device or a personal machine?

**Comment by vanelk** [comment]
Can someone help I have been having the same issue
