### ISSUE TITLE
在wsl2上编译android11失败

### ISSUE THREAD

**Issue by 568240761** [microsoft/WSL#6285]
# Environment

Microsoft Windows [版本 10.0.18363.1198]

Ubuntu Release:        18.04
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

# Actual behavior

执行 make 命令后，出现 Failed to listen for path logs: listen unix out/.path_interposer_log: bind: operation not supported

**Comment by piqjen-1xofFi-sikxyh** [comment]
🦄

**Comment by piqjen-1xofFi-sikxyh** [comment]
[](https://login.verizonwireless.com/vzauth/UI/https//secure.verizon.com/vzauth/UI/Login)
