### ISSUE TITLE
Error 0x8008005 Server Execution Failed

### ISSUE THREAD

**Issue by dexter-dz** [microsoft/WSL#6287]
My WSL2 was working fine.. I hadn't opened my laptop couple of days, Fired up my kali and This error started..
In PowerShell "WSL -l -v" takes forever to output a reply and manually starting kali.exe or even the app icon of Kali-Linux gives a response saying Installing and then the error is printed.

![image](https://user-images.githubusercontent.com/17889782/100514405-743fe080-319a-11eb-9a7c-9d1b7f754374.png)

In some closed thread I read they were unable to install. This is a large image of Kali-Linux with KEX for graphical interface whioch was working smooth till 3 days ago.

**Comment by sirredbeard** [comment]
I would disable WSL 2, remove Kali, re-enable WSL 2, and reinstall Kali as a first set of steps with an error like this.

**Comment by dexter-dz** [comment]
After 1 Week I came back, I was out of my house for a week and now I launched Kali and It launched normally, I think windows update fixed this issue automatically, Today I launched Kali-Linux and I was greeted by my default Terminal screen 
![image](https://user-images.githubusercontent.com/17889782/101259337-489a9880-374e-11eb-9969-2859bfd9f8fc.png)
Sorry I couldn't contribute much to the solution guys
