### ISSUE TITLE
Network drive not being auto mounted

### ISSUE THREAD

**Issue by samcro1967** [microsoft/WSL#6289]
# Environment
Microsoft Windows [Version 10.0.19042.630]
Ubuntu Release: 20.04
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

# Steps to reproduce

mkdir /mnt/k
sudo nano /etc/wsl.conf
[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=11"
mountFsTab = true

sudo nano /etc/fstab
\\\\192.168.1.125\data /mnt/k drvfs uid=1000,gid=1000 0 0

**WSL logs**: 
submitted via feedback hub

#  Expected behavior

/mnt/k to automatically be  mounted to  to \\\\192.168.1.125\data

# Actual behavior

Drive is not mounted.  Does mount with sudo mount -a.

**Comment by Tw3aky81** [comment]
Seems to me that OP is mounting network share and most probably related to #6093?
