### ISSUE TITLE
"Attempt to access invalid address." when trying to open FUSE mount in Explorer

### ISSUE THREAD

**Issue by bauerj** [microsoft/WSL#6293]
# Environment

```none
Windows build number: 10.0.19041.630
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020)
```

# Steps to reproduce
1. I mount a remote directory using SSHFS in WSL 2:
```
$ sudo mkdir /mnt/test
$ sudo chown 1000:1000 /mnt/test
$ sshfs -o idmap=user,uid=1000,gid=1000 server:/root/test /mnt/test
$ ls -lan test
 total 8
 drwxr-xr-x  1 1000 1000 4096 Nov 30 13:47 .
 drwxrwxrwx 14    0    0 4096 Nov 30 13:24 ..
 -rw-r--r--  1 1000 1000    0 Nov 30 13:47 1
 -rw-r--r--  1 1000 1000    0 Nov 30 13:47 2
 -rw-r--r--  1 1000 1000    0 Nov 30 13:47 3
```
2. I open Explorer in the `/mnt` directory:
```
$ explorer /mnt
```
![image](https://user-images.githubusercontent.com/598790/100613230-7c239000-3314-11eb-8058-72bc557a7685.png)

So far so good.

3. I try to open the `test` directory by double-clicking it in the `/mnt` directory now open in Explorer.

#  Expected behavior

The folder opens.

# Actual behavior

This error message appears:

![image](https://user-images.githubusercontent.com/598790/100613197-6dd57400-3314-11eb-8c67-f701375e15ba.png)

This translates to 

> \wsl$\Ubuntu-20.04\mnt\test is not accessible. You might not have permission to use this network resource. Contact the administrator of this server to find out if you have access permissions.
Attempt to access invalid address.

# Additional information:

The same issue has been reported in a comment [here](https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/#comment-5241). According to Pierre Boulay it should work if uid/gid is changed accordingly. I have tried that unsuccessfully which is why I create this issue.

**WSL logs**: 

I tried to use the Feedback Hub to send the logs but that didn't work either:

![image](https://user-images.githubusercontent.com/598790/100614545-978f9a80-3316-11eb-9fbf-07bac4b9ac76.png)

> Something went wrong
>
> The recording couldn't be started. Choose "Start Recording" to try again."

**Comment by sirredbeard** [comment]
> it should work if uid/gid is changed accordingly. I have tried that unsuccessfully

What did you try?

**Comment by bauerj** [comment]
I used 

    sshfs -o idmap=user,uid=1000,gid=1000

to set the uid/gid in the mount to that of my user in the WSL environment.

**Comment by diddledan** [comment]
This is due to the sshfs mount refusing to allow root to access the files by default. You can fix this by editing `/etc/fuse.conf` to uncomment or add `user_allow_other` on a new line by itself. Once that's done you need to add `allow_root` to your `-o` parameter:

```bash
sshfs -o idmap=user,uid=1000,gid=1000,allow_root server:/root/test /mnt/test
```

**Comment by bauerj** [comment]
Thanks Daniel, that was precisely it!

I'm closing this then since it's not an issue in WSL.
