### ISSUE TITLE
WSL2 terminates the moment my laptop is unplugged from electricity

### ISSUE THREAD

**Issue by laralex** [microsoft/WSL#6296]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Your Distribution version: Debian 10
Whether the issue is on WSL 2 and/or WSL 1: WSL 2, Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
Device: laptop Acer Aspire 3 A315-42G-R68U
```

# Steps to reproduce

1. I launch WSL on my laptop  while it's plugged in
2. I unplug the laptop

or

1. I launch WSL on my laptop while it's unplugged
2. I plug the laptop in
3. I unplug the laptop (duration of being plugged in doesn't matter)
 

**WSL logs**: 
https://aka.ms/AAagc4m

#  Expected behavior

WSL stays working normally

# Actual behavior

WSL terminates with no error message 1.5 seconds after: at first the console area disappears and only light-gray window is left, then the window closes as well. The whole termination takes about 1 sec more than manual closing (e.g. Alt-F4)

**Comment by Biswa96** [comment]
Did you try with WSL1?

**Comment by laralex** [comment]
@Biswa96 I used to use WSL1 for a little while, but it's hard to say whether this issue doesn't happen with WSL1 or I just never tried to unplug the laptop with WSL1 running.
[dmesg.log](https://github.com/microsoft/WSL/files/5621269/dmesg.log)

**Comment by benyaminl** [comment]
> 
> 
> @Biswa96 I used to use WSL1 for a little while, but it's hard to say whether this issue doesn't happen with WSL1 or I just never tried to unplug the laptop with WSL1 running. Here are the logs:
> [dmesg.log](https://github.com/microsoft/WSL/files/5621269/dmesg.log)

By Anychance you use Battery Care? If yes then, it's the problem, probably. It stop some service and probably some service needed by WSL is killed

**Comment by laralex** [comment]
> 
> 
> > @Biswa96 I used to use WSL1 for a little while, but it's hard to say whether this issue doesn't happen with WSL1 or I just never tried to unplug the laptop with WSL1 running. Here are the logs:
> > [dmesg.log](https://github.com/microsoft/WSL/files/5621269/dmesg.log)
> 
> By Anychance you use Battery Care? If yes then, it's the problem, probably. It stop some service and probably some service needed by WSL is killed

I just tested with Windows' power saver mode off and everything switched to maximum performance on battery and it crashes anyway. I'm not sure if the issue is indeed in some service being shutdown, because services usually take some time to launch, but in my case I can immediately launch WSL after crash (so the needed services are probably intact or launched by WSL itself).

**Comment by CeSiumUA** [comment]
Are there any updates for WSL2?
Because it still reproduces with WSL2, it is not loading while working unplugged

**Comment by benyaminl** [comment]
@CeSiumUA Seems there are none, and tied specifically to some brand or updates, I try to reproduce on clean install, can't reproduce. Can you share the build ID of the windows, the laptop brand, and paste it here? It will help, I think to narrow down the problem. 

NOTE: I'm not microsoft employee, just some other user

**Comment by benyaminl** [comment]
@CeSiumUA 
No Need for serial, please remove the serial. I hope the dev pick this, 

Hmm you already get the latest January Monthly update, strange.... I have same Build number, on different manufacture, not reproduceable... Last time, on windows 10, they suddenly fix the code, without any notice, using monthly update... I don't know whether they will done the same to windows 11

**Comment by kierke-gaard** [comment]
My wsl2 stops working after I set my Laptop on sleep mode. Everytime...
