### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by alannt777** [microsoft/WSL#6299]
I am curating the [Windows Subsystem for Linux topic](https://github.com/topics/wsl) and can I get a "Windows ❤️ Linux" logo?

I need to add more content and I thought I should have an image as well

/cc @craigloewen-msft

**Comment by craigloewen-msft** [comment]
We do not have an official logo for WSL, or any official logo of "Windows ♥ Linux" to provide you unfortunately! However, I think it would be very easy to make your own image for this effort using PowerPoint or Figma :)

**Comment by alannt777** [comment]
Hey @craigloewen-msft 

Can I use/get the Windows logo?

**Comment by alannt777** [comment]
Sorry for bothering you 😅

**Comment by craigloewen-msft** [comment]
I'm not the best subject matter expert here for that question, unfortunately the best I can do is link you to some online documentation for it! [Use of Copyrighted content](https://www.microsoft.com/en-us/legal/intellectualproperty/permissions/default#:~:text=Microsoft%20logos%2C%20including%20our%20well-known%20product%20names%20such,and%20brand%20guidelines.%20No%20other%20use%20is%20permitted.)
