### ISSUE TITLE
Can't start wsl: 4294967295

### ISSUE THREAD

**Issue by peter-jerry-ye** [microsoft/WSL#6300]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.662]
Your Distribution version: Can't start WSL2. Should be Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

execute `wsl -d Ubuntu`

**WSL logs**: 

#  Expected behavior

Open wsl 2
# Actual behavior

'参考的对象类型不支持尝试的操作。' and quit with 4294967295

**Comment by therealkenc** [comment]
/dupe #4177. If you like, please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in that issue.
