### ISSUE TITLE
Deleting node_modules through WSL 1 freezes Windows.

### ISSUE THREAD

**Issue by mthines** [microsoft/WSL#6303]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.630]   
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce

1. Clone down a heavy Javascript Node project (The github project the issue occur on is private but I can give you access.)

2. Install the project using either NPM or Yarn.
```bash
npm install
# or 
yarn
```
3. Delete the newly generated node_modules folder using WSL.
```bash
rm -rf node_modules
```
4. The node_modules folder will be deleted after a while, but then the operating system stops functioning.
I can't open task manager, shutdown or restart, the machine is just frozen.
I need to shutdown the machine through the physically power button.

**WSL logs**: 
Will add later.

#  Expected behavior

I'm expecting to being able to delete the node_modules folder, and reinstall it.

# Actual behavior

The operating system freezes, and I'm stuck.

**Comment by sirredbeard** [comment]
Are you storing the node_modules folder on /mnt/c or in a Linux folder?

**Comment by mthines** [comment]
> Are you storing the node_modules folder on /mnt/c or in a Linux folder?

`/mnt/c` folder.

**Comment by sirredbeard** [comment]
My first suggestion would be to host that project in a folder on WSL side for performance purposes.

Second can you please suggest a large public node project to try this with so I can attempt to reproduce?

**Comment by mthines** [comment]
> My first suggestion would be to host that project in a folder on WSL side for performance purposes.
That's interesting, I'll try that. Even if it's WSL 1? I've had crazy slow 'yarn install' on WSL 2 so i dropped it for now.

> Second can you please suggest a large public node project to try this with so I can attempt to reproduce?
Yeah, I'll try and make an empty repo, with big package.json and share it.

Thanks!

**Comment by mthines** [comment]
I'll mark this as stale, as I never got to test it out. :)

**Comment by Dvaranir** [comment]
Same problem, project on /mnt/e
