### ISSUE TITLE
Can't remove created hidden file

### ISSUE THREAD

**Issue by QAnders** [microsoft/WSL#6305]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`] 19042.630
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] 18.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce

```
cd /mnt/c/Temp
mkdir test
cd test
mkdir .test
cd .test
touch .test-file
rm .test-file
```

**WSL logs**: 

#  Expected behavior

The file to be deleted

# Actual behavior

Getting an error: `rm: cannot remove '.test-file': No such file or directory`

Trying to access the file in Windows Explorer it has no permissions and I (as an Admin) can't change owner and/or add permissions:
![image](https://user-images.githubusercontent.com/12028885/101043070-2d792e80-357e-11eb-8647-f3dff3cbf3bd.png)

**Comment by sirredbeard** [comment]
I am unable to reproduce here. 

What C:\Temp originally created in Windows or WSL?

![image](https://user-images.githubusercontent.com/33820650/101193701-f90f7c00-362a-11eb-9a65-f74e43242c21.png)
