### ISSUE TITLE
Errors have been written by someone who has never developed or used software

### ISSUE THREAD

**Issue by pluc** [microsoft/WSL#6306]
I don't know who wrote your errors but:

```
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

Is completely useless. Which feature is not installed? How do I fix it? Do you seriously want your users only option to search for an error identification string? Do you do that because you can't be bothered to write your own documentation and are instead waiting for the community to rank their own support pages? I can't see why you would do such beginner stuff.

It would be great if you took the time to write meaningful error messages so that users know what to do when they encounter them.

**Comment by randomascii** [comment]
The twitter thread may be  helpful for diagnosing the problem:

https://twitter.com/BruceDawson0xB/status/1304656073312202752

In my case the problem was that I needed to enable virtualization. YMMV.
