### ISSUE TITLE
Enabling WSL2 and Windows Virtualization Platform causes Intel Wi-Fi 6 ax200 160mhz driver to be blocked

### ISSUE THREAD

**Issue by MingLu8** [microsoft/WSL#6307]
![image](https://user-images.githubusercontent.com/5847065/101048551-b5e0da80-3550-11eb-8b93-4e36f8508366.png)
![image](https://user-images.githubusercontent.com/5847065/101049437-84b4da00-3551-11eb-9feb-9cf4dd649173.png)
![image](https://user-images.githubusercontent.com/5847065/101051135-225cd900-3553-11eb-95ca-791aada6aa22.png)

This is similar to this issue: https://github.com/microsoft/WSL/issues/5911

System Details: Eluktronic THINN 15 (MechRevo code01) with AMD Ryzen 4800H with Windows 10 Pro
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎20/‎2020
OS build	19042.662
Experience	Windows Feature Experience Pack 120.2212.551.0
Wireless Card driver version: 22.10.0.7, driver date: 10/20/2020.

Steps to reproduce

    Install the 'Virtual Machine Platform' features, following steps here to install WSL 2.
    Reboot machine.
    Open Device manage, and notice that Intel Wi-Fi 6 ax200 160mhz fails with: The driver for this device has been blocked from starting because it is known to have problems with Windows. Contact the hardware vendor for a new driver. (Code 48). The wireless card is no longer visible in network settings and cannot be used anymore.    
    Disable 'Virtual Machine Platform'
    Reboot.
    Observe that resolution is restored to normal, and driver loads successfully and the wireless card can be used again.
    WSL 2 image no longer work. WSL 1 based image works fine.

Expected behavior

I would like to run WSL 2 based Linux and be able to use my ethernet card.
Actual behavior

Some conflict occurs between the Virtual Machine Platform feature and wireless card drivers. BTW, i tried installing the latest drivers too but they don't work. The problem right now is that they cannot co-exist.

I'd like to know whether this is a Windows or intel wireless card driver issue, so I can followup for support accordingly.
Any other logs/debugging I can gather or provide?

**Comment by flairling** [comment]
I have the same problem
