### ISSUE TITLE
Kaspersky disabled WSL1

### ISSUE THREAD

**Issue by 1ceaham** [microsoft/WSL#6308]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1198]
Your Distribution version: Ubuntu-18.04 (Can't get in to view version...)
Whether the issue is on WSL 2 and/or WSL 1: WSL1
```

# Steps to reproduce

I am required to run Kaspersky Endpoint Security for work. Yesterday, it registered a false positive and quarantined WSL. Despite restoring the (presumably) affected files, I have been unable to recover the system.

At the time, I was unzipping a tar.gz file, and Kaspersky reports that it quarantined bash, gzip, and tar, at the following addresses:
\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\bin\bash
\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\bin\gzip
\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\bin\tar

![image](https://user-images.githubusercontent.com/15150383/101113098-830c0600-3593-11eb-80b5-2560b791b91e.png)

I have restored the files, and disabled Kaspersky to the best of my ability (while also whitelisting the above addresses for good measure), but running wsl.exe returns immediately, and starting Windows Terminal returns `[process exited with code 1]`. Repairing from Add or Remove Programs has not been successful.

Unfortunately, I haven't backed up the installation in about a year, and would like to recover it if at all possible. Is it possible to recover from this?

If it isn't possible to repair the system, please feel free to open another issue to discuss how I might go about safely recovering the data from my home directory to a fresh installation. Thanks!

**WSL logs**: https://aka.ms/AAaiyvd

#  Expected behavior

WSL starts as usual.

# Actual behavior

WSL does not start.

**Comment by oldium** [comment]
Most probably the restoration process did not restore all the file attributes, so you will need to reinstall your distro. See https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/

Report the error to Kaspersky, they screwed it up, so they should fix it.

**Comment by DHowett** [comment]
You can _likely_ generate an archive of yohr distro with `wsl.exe --export` which you can use in a new installation to extract your home directory.

**Comment by 1ceaham** [comment]
Thanks for the advice; I expect that corruption is the case. I also didn't realize the proscription on modifying the files in `%localappdata%` extended to access, which I certainly did at some point, so that is probably the culprit here.

Fortunately, I was able to generate the archive with `wsl.exe --export`. Are there details of the format that I can use to extract what I need? If there was a way to diff the contents of the archive with a clean distro, that would be ideal... Just want to make sure I don't miss anything outside of the home directory.

I'll leave this open for the time being until I get a response from Kaspersky, but at the moment will proceed with a reinstallation (barring any other tricky ideas).

**Comment by DHowett** [comment]
So, the exported archive is a standard tar or tar.gz file -- you can access it, or extract it, with the `tar` utility. Diffing the contents is going to be a bit of a bear...

**Comment by DHowett** [comment]
This is going t obe a bit wild.

Can you try launching your existing distribution and specifying the shell directly?

```
wsl -e /bin/sh
```

This might get you in.

If you can get in:

```
chmod +x /bin/bash /bin/gzip /bin/tar
```

Then try launching wsl normally.

**Comment by 1ceaham** [comment]
Wow! That worked! I had to `sudo chmod`, but everything appears to be in order otherwise. Thank you so much!
