### ISSUE TITLE
WslRegisterDistribution failed with error: 0x8037010d

### ISSUE THREAD

**Issue by HaoKunT** [microsoft/WSL#6317]
# Environment
Microsoft Windows [version 10.0.18363.1198]
I don't known the distribution version because it error when it is installing.
It should be WSL 2
```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
I enable the Windows subsystem Linux
![image](https://user-images.githubusercontent.com/16379361/101285701-92a07e80-3821-11eb-8ba7-7664ca5ec71d.png)
 follow the steps with [this](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package).
When I install the Ubuntu 20.04, when I start it , it return this error:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8037010d
Error: 0x8037010d ?????? JSON ?????

Press any key to continue...
```
![image](https://user-images.githubusercontent.com/16379361/101285785-03479b00-3822-11eb-83f6-2115c24bf8dc.png)

I try another distribution like Ubuntu 18.04, it also failed. The same problem.

It seems a json invalid, but I don't known which json file invalid.

 I try to uninstall wsl and reinstall it, but it also failed!

**WSL logs**: 

#  Expected behavior
It can be installed correctly.

# Actual behavior
It failed!

**Comment by HaoKunT** [comment]
It's ok now. I enabled the Virtual Machine Platform feature, it's ok now. But there is still something confuse me because I remember I enabled it before. I run this command
```powershell
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

**Comment by Quadre** [comment]
I got the same problem, and resolution was to remove Bridge network config from `c:\Users\<myUser>\.wslconfig` file.
Setup: Windows 10 22h2, WSL 2.0

**Comment by iam-Robo** [comment]
I'm using Windows 11 and got the same issue. But there is no .wslconfig in my files :-s

**Comment by hiiamboris** [comment]
Had this on W10/WSL2 after a forced update from MF$. No bridged networks, no config.
Solved by removing WSL and Virtual Machine Platform, REBOOTING, then adding both back and rebooting again. VM virtual drive survives thru this process.

**Comment by qingzheng-web** [comment]
> I'm using Windows 11 and got the same issue. But there is no .wslconfig in my files :-s我正在使用 Windows 11 并遇到了同样的问题。但是我的文件中没有 .wslconfig ：-s

You can make a file named .wslconfig,the place is %userprofile%\.wslconfig

**Comment by qingzheng-web** [comment]
> I'm using Windows 11 and got the same issue. But there is no .wslconfig in my files :-s

You can make a file named .wslconfig,it's directory is %userprofile%\.wslconfig.
