### ISSUE TITLE
Networking issue in WSL2 under first windows local user account

### ISSUE THREAD

**Issue by yacchi** [microsoft/WSL#6318]
I logged in to Windows using a local user account.
This account was created in the Windows installation wizard many years ago.

Unreachable to another computer in the same network or any internet host from WSL2 under this user account session.

I tried to disable the Windows firewall, run "Windows refresh feature" and clean install use install media before create this issue post.

# Environment
```none
Windows build number:
Microsoft Windows [Version 10.0.19042.662]

Your Distribution version:
Ubuntu 20.04
Same issue occurs in Kali linux (maybe no distribution dependent).

Whether the issue is on WSL 2 and/or WSL 1:
WSL2
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

Does not occur this issue if you're logged in an account are Microsoft account or after the secondary user.

1. Create the first local user account using the installation wizard. **You must not log in or create a Microsoft account**.
2. Install WSL2.
3. Install Linux distribution from Microsoft Store.
4. Start and set up a Linux environment.
5. Network connectivity check use ping, host, and so on.

**WSL logs**: I collect it if required.

#  Expected behavior

I expect any response from ping or any other Internet access.

# Actual behavior

Send Ping request was successful, and the reply packet was delivered to Windows.
However, the reply packet was not delivered to WSL2.

![icmp_screenshot](https://user-images.githubusercontent.com/1259154/101287961-f5e8db80-3836-11eb-850f-3f350d6614c5.png)

States of networking in WSL2.

```none
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether fe:44:b8:c4:da:43 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:77:bb:4d:cd:ba brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:36:7f:64 brd ff:ff:ff:ff:ff:ff
    inet 172.25.207.205/20 brd 172.25.207.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe36:7f64/64 scope link
       valid_lft forever preferred_lft forever
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

$ ip route
default via 172.25.192.1 dev eth0
172.25.192.0/20 dev eth0 proto kernel scope link src 172.25.207.205
```

**Comment by OneBlue** [comment]
Thanks for reporting the issue @yacchi.

Can you please follow [these instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and share the script output, and both `wsl.etl` and `packets.etl` ?

**Comment by yacchi** [comment]
@OneBlue 
Thanks for the reaction to this issue.
I collected `wsl.etl` and `packets.etl` use `network.bat`, and uploaded them to the feedback hub in the following link.

Please see the https://aka.ms/AAazyie.

**Comment by OneBlue** [comment]
Thank you @yacchi. Can you please also share the script output ?

**Comment by yacchi** [comment]
@OneBlue I captured the script output.
(Sorry,  I couldn't add this file to the feedback hub.)

[diagnostics.txt](https://github.com/microsoft/WSL/files/5939236/diagnostics.txt)
