### ISSUE TITLE
Can't install wsl on Dell XPS 9310

### ISSUE THREAD

**Issue by 810** [microsoft/WSL#6321]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.20270.1]
Your Distribution version: none
Whether the issue is on WSL 2 and/or WSL 1: 2

Dell Xps 13 9310
Bios: 1.1.1
i7-1165G7
32Gb memory
1TB ssd
```

# Steps to reproduce
Install windows subsystems for linux by features.

Restart laptop.
De updates can't be installed, the spinner is slow/hanging , until the logon screen is almost loading (seeing blue background and sound/power icon on bottom right).
The machine is restarting.

You can only login when "virtualization is disabled on the bios"

**WSL logs**: 

none, because can't login with virtualization enabled.

# Actual behavior

restarting, memory issue with loading, until logon screen.

# Reddit post:
https://www.reddit.com/r/bashonubuntuonwindows/comments/k8r6el/cant_install_wsl_on_dell_xps_9310/

**Comment by KristianFJones** [comment]
Odd, I'm rocking WSL2 on my XPS 13 9310. No issues.

**Comment by KristianFJones** [comment]
I'll share my bios config within the next day.

**Comment by scryla** [comment]
I have similar issue when trying to enable wsl. Constant reboot until I go to safe mode then get message unable to install feature, roll back changes. Would be good to see your bios settings.

**Comment by bpulliam** [comment]
Can't do much without logs or BIOS config.  Closing.

**Comment by 810** [comment]
Issue has been resolved, by updating wsl package.

**Comment by bpulliam** [comment]
Glad to hear it. Just cleaning up our issues to ensure that nothing gets lost.
