### ISSUE TITLE
WSL recognizes only half of my available RAM

### ISSUE THREAD

**Issue by beneyal** [microsoft/WSL#6322]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.20270.1]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1:  WSL 2
```

# Steps to reproduce

Run `htop` or `free -m`.

#  Expected behavior

Both `htop` and `free -m` should show I have 32GB memory.

# Actual behavior

I have only 16GB memory:

![image](https://user-images.githubusercontent.com/3891274/101627188-a1a44e00-3a26-11eb-9e9f-366e1a10c027.png)

**Comment by onomatopellan** [comment]
That's expected in Insider builds. See https://github.com/microsoft/WSL/issues/4166#issuecomment-662705705

**Comment by beneyal** [comment]
Thanks, that's exactly what I needed! I created a `.wslconfig` file and now `htop` shows 32GB of memory.
