### ISSUE TITLE
Calling win32 lib.exe with long arg line freezes shell

### ISSUE THREAD

**Issue by dgud** [microsoft/WSL#6327]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`]
Microsoft Windows [Version 10.0.19042.685]

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Release:        20.04

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
WSL2      (it works fine in WSL1 which I have used until now) 
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

```

# Steps to reproduce

Full build instructions are here: https://github.com/erlang/otp/blob/master/HOWTO/INSTALL-WIN32.md
But I think the following should work if Visual Studio is installed in default path:
```
git clone https://github.com/erlang/otp.git
cd otp
eval `./otp_build env_win64`
./otp_build setup -a
```

**WSL logs**: 

Normally invoked via a script in a Makefile,  but same issue directly from the shell..
And this is just a 1/3 of the command line :-)
But as I said I have not had any problems with the same build chain in WSL1.

```Ubuntu:/mnt/e/src/otp/lib/erl_interface> lib.exe /nologo -out:"E:\src\otp\lib\erl_interface\obj\win32\ei_mdd.lib" "E:\src\otp\lib\erl_interface\obj.mdd\win32\ei_connect.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\ei_resolve.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\eirecv.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\send.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\send_exit.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\send_reg.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_atom.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_big.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_bignum.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_binary.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_boolean.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_char.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_double.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_fun.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_intlist.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_iodata.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_list_header.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_long.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_pid.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_port.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_ref.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_skip.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_string.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_trace.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_tuple_header.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_ulong.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_version.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_longlong.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\decode_ulonglong.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_atom.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_big.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_bignum.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_binary.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_boolean.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_char.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_double.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_fun.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_list_header.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_long.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_pid.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_port.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_ref.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_string.o" "E:\src\otp\lib\erl_interface\obj.mdd\win32\encode_trace.o"```

strace.log  https://gist.github.com/dgud/03bff7e36a20603f2bfb6b4026b48dcc

#  Expected behavior

A nice lib file, and get my bash back.

# Actual behavior

The shell  freezes/hangs, I  can not CTRL-C nor CTRL-Z back I'll have to kill the tab in the terminal.

**Comment by soinipe** [comment]
Can be reproduced with artificial command line from WSL2 - Ubuntu 20.04, 4017 bytes:
```
findstr.exe "abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz" abcdefghijklmnopqrstuvxyz
```
Expected output, similar as when run from CMD.EXE:
```
FINDSTR: Cannot open abcdefghijklmnopqrstuvxyz
```
Actual behaviour: hangs, need to `wsl --shutdown` and re-run of `ubuntu2004.exe`

Randomly shortened command (2587 bytes) works as expected:
```
findstr.exe "abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz abcdefghijklmnopqrstuvxyz" abcdefghijklmnopqrstuvxyz
```

Tested versions:
- Microsoft Windows [Version 10.0.19042.985]
- WSL2: Ubuntu_2004.2020.424.0_x64.appx
- uname -a: Linux ***** 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Originally problem was seen in build system which generates long commands.

**Comment by sslivins** [comment]
ran into this issue as well on Linux *** 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

It does indeed seem to be some type of command line character limit.  I was able to work around it using the lib.exe command file option (dump everything you would have put on the command line into a file then use `lib.exe @<file name>` but this is far from ideal

**Comment by sslivins** [comment]
just tested this with the store version of wsl (https://www.microsoft.com/store/productId/9P9TQF7MRM4R) which is on version  5.15.79.1.  I confirmed it fixed my issue as well as the simple test case provided by @soinipe
