### ISSUE TITLE
Cannot mount /mnt/c/Users/my_home over /home/my_home automatically

### ISSUE THREAD

**Issue by cjshowalter** [microsoft/WSL#6330]
**Is your feature request related to a problem? Please describe.**
I would like to mount my windows home, over the linux home, so they both have the same workspace / access to the same .ssh files, etc. (It can work with making your home path /mnt/c/Users/my_home in /etc/passwd, so it's not a block. You then have a really long path when you cd somewhere, so I'd like to work from /home if possible.).

I can add a bind mount to /etc/fstab like so, but it only works if after I login, I "sudo mount --all", then "cd ~" to get to the mount.
```
/mnt/c/Users/my_home     /home/my_home    auto    defaults,bind   0 0
```
I've tried explicitly setting mountFsTab=true in /etc/wsl.conf

**Describe the solution you'd like**
A way for my windows home to be mounted over the linux one, and then the .bashrc, .profile, etc files to be loaded from the new windows home.
You can set the root for the entire c drive in wsl.conf, maybe add a way to mount the home somewhere else in there maybe?

**Describe alternatives you've considered**
Other than what was mentioned above, I tried adding "mount --all" to /etc/init.d, and symlinking it to happen at startup. Same with adding "@reboot mount --all" to root's crontab. I cannot get it to run without me explicitly telling it to when I login. I'd like it to happen before .profile and .bashrc loads if possible.

**Additional context**
If I missed any info, feel free to ask. I have no clue if this is a bug/feature request, or I'm just missing something obvious.

Versions:
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
Microsoft Windows [Version 10.0.19042.685]
Release:        20.04

**Comment by 0xbadfca11** [comment]
This is because the fstab process is executed before the implicit drvfs mount. (``/mnt/c`` is still empty when mount ``/mnt/c/Users/my_home`` is execting.)

- Workaround 1
mount C:\ in fstab before mount /mnt/c/Users/my_home.
```text
C:\	/mnt/c	drvfs	defaults,noatime	0 0
/mnt/c/Users/my_home     /home/my_home    auto    defaults,bind   0 0
```

- Workaround 2
``` ln -s /mnt/c/Users/my_home /home/my_home```

**Comment by cjshowalter** [comment]
I tried out the second, with deleting my home and replacing that with a symlink, and it working great! I wasn't sure about the first one, because of c getting mounted twice to /mnt/c, and didn't feel like messing with that. I guess you could turn off the second mount regardless, with adding "enabled: false" to the automount section in wsl.config. Is one any more/less stable than the other in any way?

**Comment by cjshowalter** [comment]
That solved my use case, so I'll close this. If one way has an advantage over the other, I'd love to know more! The symlink was definitely easy to setup.
