### ISSUE TITLE
The system cannot find the path specified. 

### ISSUE THREAD

**Issue by eve-alt** [microsoft/WSL#6333]
### Windows Build Number:

```
C:\> ver
Microsoft Windows [Version 10.0.19041.450]
```

### Distro ver:

Ubuntu 20.04 LTS

### What you're doing and what's happening:

I'm trying to move into WSL2 but everytime I do `wsl --set-version Ubuntu-20.04 2` it tells me that the system cannot find the path specified. I have made sure that I have followed every step listed in [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps).

```
PS C:\WINDOWS\system32> wsl.exe --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The system cannot find the path specified.
```

I have also tried uninstalling the installed Ubuntu that is on version 1 then doing `wsl --set-default-version 2` and then trying to install it again just to get:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003 
Error: 0x80070003 The system cannot find the path specified.
```

### What should be happening instead:

It should work without raising any errors.

**Comment by KELVIIN-HUANG** [comment]
i have the same problem ,and all the the solutions of closed issues don't work

**Comment by kyaru92** [comment]
did you check this? https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation
the first item is a solution to error 0x80070003.
i guess the problem is caused by microsoft store

**Comment by eve-alt** [comment]
> did you check this? https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation
> 
> the first item is a solution to error 0x80070003.
> 
> i guess the problem is caused by microsoft store

Hi! Yes, I have tried those things too. Unfortunately, they couldn't help me. First item is kinda irrelevant to my situation since I only have a single drive which is the system drive. I've also checked other issues that had the same error code and that solution applies to them since they were trying to install it in another drive.

**Comment by licanhua** [comment]
Have you installed the [Linux kernel](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)? If yes, you may [collect-wsl-logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by speyck** [comment]
Try unregistering the distro from WSL with this command:

    wslconfig /u Ubuntu-20.04
then re-install the distro to WSL

**Comment by dransidu** [comment]
> Try unregistering the distro from WSL with this command:
> 
> ```
> wslconfig /u Ubuntu-20.04
> ```
> 
> then re-install the distro to WSL

Thanks may it's work on my pc!

**Comment by baflo** [comment]
Wow, this was one of my biggest fails till today. I needed more RAM, so I just copied the example config from [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#global-configuration-options-with-wslconfig) and replaced the default RAM by 12GB without further inspection of the other config. Well, it replaced the kernel with a non-existing path 🤦‍♂️ 

```
[wsl2]
kernel=C:\\temp\\myCustomKernel
memory=4GB # Limits VM memory in WSL 2 to 4 GB
processors=2 # Makes the WSL 2 VM use two virtual processors
```

Maybe my outing helps other people.

**Comment by SolanaGuru** [comment]
Thank you

**Comment by lupyd** [comment]
Nothing worked for me, tried to install linux kernal package, but it says I've already have the latest version installed, windows store doesn't install or uninstall anything, any distro. all of sudden wsl stopped working. I might probably switch completely to linux and ditch windows at this point, but I have a lot of things to pack up and I'm lazy that's why I'm still on windows, but wsl is very essential for me
