### ISSUE TITLE
Change the option name to English and keep the Chinese description

### ISSUE THREAD

**Issue by kyaru92** [microsoft/WSL#6335]
**Is your feature request related to a problem? Please describe.**

###  install Windows and set the default language to Chinese, the message `wsl -h` shows is confusing
![image](https://user-images.githubusercontent.com/13380455/101991046-0e4c7080-3ce5-11eb-9811-1d157fc857bc.png)

**Describe the solution you'd like**
### we can show the help message like this:  
> --shutdown  
>        立即终止所有运行的分发及 WSL 2  
>       轻型工具虚拟机。

**Describe alternatives you've considered**
OR
> --关闭 (--shutdown)  
>        立即终止所有运行的分发及 WSL 2  
>       轻型工具虚拟机。

**Additional context**

**Comment by licanhua** [comment]
Thanks to report it. it's a bug and dup #6328

**Comment by tingjhenjiang** [comment]
I get into this trouble as well after upgrade to wsl 1.0 .
[Refer](https://github.com/microsoft/WSL/issues/6328#issuecomment-1328207929)
