### ISSUE TITLE
Setup Nvidia CUDA on WSL2

### ISSUE THREAD

**Issue by vedmed85** [microsoft/WSL#6340]
I'm trying to setup Cuda toolkit in WSL2(Ubuntu18) by this manual

```
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-wsl-ubuntu-11-1-local_11.1.1-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-11-1-local_11.1.1-1_amd64.deb
sudo apt-key add /var/cuda-repo-wsl-ubuntu-11-1-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda
```

source [](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=WSLUbuntu&target_version=20&target_type=deblocal) or this `https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2`

linux kernelup to date

uname -r
4.19.128-microsoft-standard
WSL2 is enabled (version of wsl disto is set 2)

 NAME                   STATE           VERSION
* docker-desktop         Stopped         2
  Ubuntu-18.04-D         Running         2
Windows host nvidia drivers is updated, windows updated too

nvidia-smi.exe 
NVIDIA-SMI 465.12 Driver Version: 465.12 CUDA Version: 11.2 GeForce GTX 1080ti WDDM

lspci | grep -i nvidia
show nothing

When i'm tying to compile and after this run executebles i'm reciving this:

alexander@i5:/usr/local/cuda-11.1/samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
**-> CUDA driver version is insufficient for CUDA runtime version**
Result = FAIL
Maybe someone has an experience of the successful solution of this error?

**Comment by thealtruist** [comment]
Hi @vedmed85, I haven't experienced that specific error but I was able to get CUDA working on WSL2 after piecing together the documentation from several sources. Here's an [article](https://medium.com/swlh/how-to-install-the-nvidia-cuda-toolkit-11-in-wsl2-88292cf4ab77) I wrote that should cover everything you need from start to finish.

**Comment by xldsdr124** [comment]
Refer to nvidia documentation:
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-nvidia-drivers

You do not need to install the nvidia driver in wsl, if you need to use cuda, you can install it directly:
apt-get install -y cuda-toolkit-{version}
E.g:
`apt-get install -y cuda-toolkit-11-0`

**Comment by vedmed85** [comment]
Thanks for your attention! But this sulution don't work for me. 
As i understand problem in nvidia driver for wsl:  Driver Version: 465.12  CUDA Version: 11.2 (this info from nvidia-smi.exe from powershell)
From WSL Ubuntu18 i can't install cuda-toolkit-11-2
```
sudo apt-get install -y cuda-toolkit-11-2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cuda-toolkit-11-2
```
sudo apt-get install -y cuda-toolkit-11-1 is exist.
And when i compile and execute ./deviceQuery in WSL i recive
```
./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 100
-> no CUDA-capable device is detected
Result = FAIL

```

i think i need wait for cuda-toolkit-11-2

**Comment by xldsdr124** [comment]
You need to update the package list, please refer to here:
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-wsl2

**Comment by vedmed85** [comment]
After updating same story
E: Unable to locate package cuda-toolkit-11-2

**Comment by thealtruist** [comment]
@vedmed85 I don't think there is an CUDA Toolkit 11.2 yet. Have you tried any of the following yet: 
`sudo apt-get --yes install cuda-toolkit-11-1`
`sudo apt-get --yes install cuda-toolkit-11-0`
`sudo apt-get --yes install cuda-toolkit-10-2`
`sudo apt-get --yes install cuda-toolkit-10-1`
`sudo apt-get --yes install cuda-toolkit-10-0`

**Comment by vedmed85** [comment]
yes of course. all exist (only 11-2 not exist )
i install cuda-toolkit-11-1 and previous errors from there
```
cudaGetDeviceCount returned 100
-> no CUDA-capable device is detected
Result = FAIL
```
or 
```
cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

```

**Comment by thealtruist** [comment]
@vedmed85, `E: Unable to locate package cuda-toolkit-11-2` made it appear as if you were having trouble installing CUDA Toolkit 11.2.

I was able to complete the tutorial you referenced but some of the necessary commands were missing. You need to correctly set up CUDA and CUDA Toolkit before you can complete your tutorial. Go to the article I referenced, follow the instructions, and then try retry your tutorial. 


![example1](https://user-images.githubusercontent.com/30560737/102129208-d851de00-3e03-11eb-9a26-099889359743.PNG)

![example2](https://user-images.githubusercontent.com/30560737/102129206-d7b94780-3e03-11eb-84de-d8d850b80913.PNG)

**Comment by vedmed85** [comment]
> @vedmed85, `E: Unable to locate package cuda-toolkit-11-2` made it appear as if you were having trouble installing CUDA Toolkit 11.2.
> 
> I was able to complete the tutorial you referenced but some of the necessary commands were missing. You need to correctly set up CUDA and CUDA Toolkit before you can complete your tutorial. Go to the article I referenced, follow the instructions, and then try retry your tutorial.
> 
> ![example1](https://user-images.githubusercontent.com/30560737/102129208-d851de00-3e03-11eb-9a26-099889359743.PNG)
> 
> ![example2](https://user-images.githubusercontent.com/30560737/102129206-d7b94780-3e03-11eb-84de-d8d850b80913.PNG)

it looks like you are advertise your blog on medium.com only. did not  understand the essence of the question

E: Unable to locate package cuda-toolkit-11-2 
this means version 11-2 not exist in repository. now you know)

your screenshots do not show the toolkit version and driver version, and therefore it is not clear why you sent them. Your article on medium about toolkit version 11-1

**Comment by thealtruist** [comment]
Perhaps, but it also could be that it's unclear what you're trying to ask. 

`this means version 11-2 not exist in repository. now you know)` thanks for that.

For a person that's asking for help, the general tone of your messages has been quite unpleasant which makes it difficult to want to help you further.

**Screenshot:**

<img width="600" alt="Screen Shot 2020-12-14 at 2 52 54 PM" src="https://user-images.githubusercontent.com/30560737/102146304-8fa71e80-3e1d-11eb-8903-a451577baa9a.png">

**Comment by vedmed85** [comment]
> @vedmed85 Perhaps, but it also could be that it's unclear what you're trying to ask.
> 
> `this means version 11-2 not exist in repository. now you know)` thanks for that.
> 
> For a person that's asking for help, the general tone of your messages has been quite unpleasant which makes it difficult to want to help you further.
> 
> **Screenshot:**
> 
> <img alt="Screen Shot 2020-12-14 at 2 52 54 PM" width="600" src="https://user-images.githubusercontent.com/30560737/102146304-8fa71e80-3e1d-11eb-8903-a451577baa9a.png">

Please stop to annoy me.

**Comment by thealtruist** [comment]
`sudo apt-get --yes install cuda-toolkit-11-2`
<br><br>


![Screen Shot 2020-12-31 at 10 49 05 AM](https://user-images.githubusercontent.com/30560737/103422382-fafb2b00-4b55-11eb-90bf-b5314cbe9896.png)

**Comment by ashishpatel26** [comment]
**End to End Nvidia Cuda Installation Guide on WSL2 Windows 11.** : [🔗](https://github.com/ashishpatel26/Cuda-installation-on-WSL2-Ubuntu-20.04-and-Windows11) :⬅ Click Here
