### ISSUE TITLE
I can`t  run explorer.exe when import ubuntu.tar to a new computer

### ISSUE THREAD

**Issue by xxiaocheng** [microsoft/WSL#6343]
# Environment
Microsoft Windows [版本 10.0.19042.685]
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

![image](https://user-images.githubusercontent.com/25473324/102369900-71951600-3ff7-11eb-9f60-2fa89230b645.png)

**Comment by therealkenc** [comment]
This almost certainly means `/mnt/c/WINDOWS` is not in your `$PATH`. The Windows paths are possibly being blown away by your `zsh`-related startup scripts. Also check `/etc/profile` ref #5296 #5779 (although that is usually not a problem on Ubuntu).
