### ISSUE TITLE
Message Passing between WSL1.0 & "Windows host" other than TCP?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/WSL#6346]
TCP, evening including loopback, has way too much latency and unnecessary memory copy to transfer buffer data between WSL1.0 and Windows executable. Any other choices, like sharing memory, message queue, or event signal, .., ..,  will work for their communication?

**Comment by Biswa96** [comment]
Other methods maybe Unix sockets (documented) or LxBus (undocumented).

**Comment by ghostplant** [comment]
@Biswa96 Thanks. How to do that? Any examples/documentation?

**Comment by OneBlue** [comment]
@ghostplant : Can you provide a bit more details about your scenario ? What exactly are you trying to copy ? 

Without more context, I'd say that the simplest is probably to use a pipe between a Windows executable and a Linux executable . 
Something like:

``` 
wsl ./myprogram | MyProgram.exe
```

**Comment by ghostplant** [comment]
@OneBlue The example you provide is only a single-direction message passing. I just want an alternative other than TCP which can allow bi-direction message passing, like `/dev/shm`, `msg_queue`, etc,

**Comment by ghostplant** [comment]
@Biswa96  Maybe LxBus is the one I needed most. Is there a hello-world example of how to use LxBus?

**Comment by OneBlue** [comment]
Ah, I see what you mean.

Unix sockets aren't supported between WSL & Windows yet, but you could do the same as what [this issue](https://github.com/microsoft/WSL/issues/4131) describes.

`instead of using hv socks for win32/Linux process communication, we wrote a bridge witch exposes our unix sockets in the Linux world as windows named pipes and vice versa.
The bridge consist of a win32 executable that spawns a Linux executable within the target wsl distro, and they communicate exclusively via stdio streams (we previously multiplexed the unix socket and named pipe connections trough a single hv sock, we now multiplex the same thing trough stdio).`

lxbus isn't public API at this time so I don't recommend taking a dependency on it.

**Comment by ghostplant** [comment]
@OneBlue OK, so do you mean to use `socat` on a unix socket, or using `hvsocket`? I am using WSL1.0 without linux kernel so I don't think `hvsocket` will work in 1.0, right?

**Comment by ghostplant** [comment]
@OneBlue Another possible solution is for a linux application in WSL to create a subprocess of windows executable, and making a `pipe IO` between them. Will it work?

**Comment by ghostplant** [comment]
@ghostplant I just write a pipe test using `fork`, `execl` and `pipe`. The child process is to execute a Windows executable while the main process is to feed input & fetch output stream to the child process. This method works well if the child process is for starting a Linux native program. However, when the child process target is changed to a Windows executable. It will just hang when the main process is fetching output stream. Is this a bug?

**Comment by OneBlue** [comment]
@ghostplant : Can you share a repro for this issue ? 

What do you mean by 'hanging' ? A blocked read / waitpid ?

**Comment by ghostplant** [comment]
@OneBlue I figured out how to reproduce the hang issue. Firstly, this is the Linux code that should be executed inside WSL. It will fork a subprocess and pipe messages to communicate with the child process.
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <errno.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/prctl.h>
#include <linux/prctl.h> 

namespace {
    static int start_subprocess(const char* command[], FILE** fin, FILE** fout, int* pid = nullptr)
    {
        int p1[2], p2[2];
        if (!fin || !fout)
            return false;
        if (pipe(p1) == -1)
            goto err_pipe1;
        if (pipe(p2) == -1)
            goto err_pipe2;
        int local_pid;
        if ((local_pid = fork()) == -1)
            goto err_fork;
        if (local_pid) {
            /* Parent process. */
            *fin = fdopen(p1[1], "wb");
            *fout = fdopen(p2[0], "rb");
            close(p1[0]);
            close(p2[1]);
            if (pid)
                *pid = local_pid;
            return 0;
        }
        else {
            /* Child process. */
            dup2(p1[0], 0);
            dup2(p2[1], 1);
            close(p1[0]);
            close(p1[1]);
            close(p2[0]);
            close(p2[1]);
            prctl(PR_SET_PDEATHSIG, SIGHUP);
            execvp(*command, (char* const*)command);
            abort();
        }
    err_fork:
        close(p2[1]);
        close(p2[0]);
    err_pipe2:
        close(p1[1]);
        close(p1[0]);
    err_pipe1:
        return -1;
    }
}

int main() {
	const char *command[] = {"/bin/cat", NULL};
	// const char *command[] = {"../x64/Release/cat.exe", NULL};
	FILE *fin, *fout;
	start_subprocess(command, &fin, &fout);

	static unsigned char buff[1024], recv[1024];
	for (int i = 0; i < sizeof(buff); ++i) {
		buff[i] = i;
                // if (buff[i] == 26) buff[i] = 0; // A windows subprocess doesn't support receiving a buffer that contains character ASCII-26, which triggers the windows subprocess to hang.
	}
	assert(sizeof(buff) == fwrite(buff, 1, sizeof(buff), fin));
	fflush(fin);
	assert(sizeof(recv) == fread(recv, 1, sizeof(recv), fout));
	for (int i = 0; i < sizeof(recv); ++i) {
		assert(recv[i] == buff[i]);
	}
	puts("PASS");
	return 0;
}
```

If the subprocess is a normal Linux program like `/bin/cat`, piping the message from main process to child process doesn't have any problem. However, for a windows child process. When writing a message contains ASCII-26 over the pipe. It makes the Windows program hang at "still reading message from input pipe".

I requirement is to pipe some random binary data to the child process.

**Comment by OneBlue** [comment]
Thanks for the sample @ghostplant. Unfortunately I couldn't repro the hang you're describing.

I used the cat.exe that's shipped with git, and everything appears to be working as expected on both WSL1 and WSL2.
Sample [strace output](https://pastebin.com/6vgEaYfU)


Can you please share the output of `strace -f [your-program]` and your windows build number ?

**Comment by ghostplant** [comment]
@OneBlue Were you using WSL2.0? The case fails at WSL1.0 in my environment.
I just append the `cat.exe` source which can collaboratewith the linux source above to reproduce this issue.
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <errno.h>

int main() {
    while (1) {
        fprintf(stderr, "Waiting for next input ..\n");
        static char buffer[1024];
        fread(buffer, 1, sizeof(buffer), stdin);
        fwrite(buffer, 1, sizeof(buffer), stdout);
        fflush(stdout);
    }
    return 0;
}
```

**Comment by ghostplant** [comment]
If the line `if (buff[i] == 26) ..` is uncommented. The communication will success:
```sh
g++ main_process.cpp && ./a.out
Waiting for next input ..
PASS
```

If the line `if (buff[i] == 26) ..` is commented. The main linux program will fail to communicate with windows child program because the buffer will contains ascii-26:
```sh
g++ main_process.cpp && ./a.out
a.out: main_process.cpp:70: int main(): Assertion `sizeof(recv) == fread(recv, 1, sizeof(recv), fout)' failed.
Aborted (core dumped)
```

**Comment by ghostplant** [comment]
@OneBlue Any progress in trying this bug?
