### ISSUE TITLE
Auto tmux on startup fails with error "Not a terminal" on zsh

### ISSUE THREAD

**Issue by jediahkatz** [microsoft/WSL#6349]
# Environment

```none
Windows build number: 10.0.19042.685
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
I am running `zsh` 5.8 (with `oh-my-zsh`).
```

# Steps to reproduce

1. Add the following to `~/.zshrc`:
```
# Always work in a tmux session if tmux is installed
# Based on https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
    tmux new-session -A -s main; exit
  fi
fi
```
2. Set Windows Terminal default to WSL and set default shell to `zsh`.
3. Try repeatedly opening Windows Terminal (if it opens successfully, then do CTRL+D and try again).
Note that I could not reproduce this on bash.

**WSL logs**: 

Windows Terminal should always open normally with `zsh` inside `tmux`.

# Actual behavior

Windows Terminal frequently fails on startup with:
```
open terminal failed: not a terminal

[process exited with code 1]
```

If it helps, here is the original issue I opened on the Windows Terminal repo: https://github.com/microsoft/terminal/issues/8553

**Comment by yevgenykuz** [comment]
I've seen this too.
I'm using the following workaround in my Windows Terminal settings for the WSL session properties (attaching to tmux manually):
`"commandline" : "wsl.exe tmux attach"`

**Comment by jediah-shoreline** [comment]
That's great, thank you!

**Comment by marioolofo** [comment]
I know I'm a little late to the party, but the solution I found was to create a bash file inside linux (I'm using openSUSE):

/home/{user_name}/shell_start.sh
```
#!/usr/bin/sh

# needed to prevent errors with tmux unable to create folder in /run
sudo systemd-tmpfiles --create

# attach or creates a new session
tmux attach || tmux
```

To use sudo this way, or you keep the message asking for the password, or add to the /etc/sudoers file the line:

/etc/sudoers
```
{user_name} ALL=(ALL) NOPASSWD: /usr/bin/systemd-tmpfiles --create
```

after that, in command line you just change your shell to the bash script (don't forget to add the executable bit to the file):

```
#> sudo chsh {user_name} --shell /home/{user_name}/shell_start.sh
```

And that's it, you have a tmux persistent session until you reboot your Windows machine.
