### ISSUE TITLE
UDP port proxy for WSL2 (in order to support HTTP/3 which uses UDP/QUIC)

### ISSUE THREAD

**Issue by fuweichin** [microsoft/WSL#6351]
**Is your feature request related to a problem? Please describe.**
I cannot access my HTTP/3 service running in WSL2/Ubuntu. because the service UDP port is not proxied/exposed to outer Windows.

**Describe the solution you'd like**
Consider supporting UDP port proxy, or adopting an existing UDP port proxy implemetation like [Simple UDP proxy/pipe](http://aluigi.altervista.org/mytoolz.htm).

**Describe alternatives you've considered**
N/A

**Additional context**
+ Windows 10 Build 19042
+ WSL 2, Ubuntu Ubuntu 20.04 LTS

![udp-port-proxy-support](https://user-images.githubusercontent.com/1687235/102688900-059ff100-4235-11eb-8f79-798242c2ab6d.png)

**Comment by therealkenc** [comment]
The following repros. Disabling firewall does not resolve.

![image](https://user-images.githubusercontent.com/7049700/102831583-035aa580-43a1-11eb-9b38-8e82c4797f52.png)

/dupe #4825 as landing zone

**Comment by fluffy** [comment]
It would be really nice to have a pointer to which issue this is a duplicate of.
