### ISSUE TITLE
WSL incorrectly sanitises filenames and volume security descriptors

### ISSUE THREAD

**Issue by dmex** [microsoft/WSL#6352]
WSL incorrectly validates the disk volume security descriptor allowing users to create files in the volume root directory when the DACL explicitly forbids non-administrators from preforming these operations. 

WSL also does not properly sanitise reserved filenames allowing anyone to create unreadable/undeletable files and can also render the machine unable to boot or startup.

# Environment

Windows build number: 10.0.19042.685
Your Distribution version: 20.04
Linux version 4.19.128-microsoft-standard

# Steps to reproduce
```
wsl -e touch /mnt/c/COM1
wsl -e touch /mnt/c/COM2
wsl -e touch /mnt/c/CON
wsl -e mkdir /mnt/c/COM1
wsl -e mkdir /mnt/c/COM2
wsl -e mkdir /mnt/c/CON
```

There are just some (reasonably safe) examples of reserved names that can be created. There are some other names which can used to render the machine unrecoverable/unbootable. This is an issue for various reasons:

1) Files such as C:\COM1 are in fact valid filenames for system devices due to legacy compatibility reasons and Windows restricts the creation of files with those names in the volume root directory. WSL however doesn't prevent the creation of reserved filenames causing legacy applications to crash and/or hang and can be used to make the machine bluescreen and/or the machine unbootable.

2) A faulty linux application that does not properly escape `"/mnt/c/Program\ Files/"` will create a file or directory named `C:\Program` causing legacy applications (that also don't escape paths when calling APIs such as LoadLibrary) to crash and/or hang since they attempt to first open C:\Program before attempting to open C:\Program Files\

3) The wsl.exe process was executed using Medium-IL and the default volume security descriptor explicitly forbids the Users group from creating/writing files in the root directory. WSL however bypassed the DACL for the volume root allowing anything to create these files.

#  Expected behavior

STATUS_ACCESS_DENIED

# Actual behavior

STATUS_SUCCESS

# Notes

Please see the following document for some other examples of reserved filenames that can be created using WSL:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

![image](https://user-images.githubusercontent.com/1306177/102694050-acef4900-4272-11eb-9c8c-cbb32f9d01e3.png)

**Comment by 0xbadfca11** [comment]
1. If it causes problems it can be done without using WSL.
```cmd
mkdir \\?\C:\COM1
mkdir \\?\C:\COM2
mkdir \\?\C:\CON
```
2.  3 & 1.
3. Creating directory in the root directory of C: is not prohibited.
Creating file in the root directory of C: is prohibited, but I couldn't create them from WSL1/2.
Did you really can make file?

**Comment by dmex** [comment]
> can be done without

\\?\ passes the path directly to the file system driver. So I guess it isn't a WSL issue.

> Did you really can make file?

F5 refresh to see the files
