### ISSUE TITLE
Network is down if swap file cannot be created on WSL2 startup

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [microsoft/WSL#6355]
# Environment
Microsoft Windows [Version 10.0.19042.685]
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

# Steps to reproduce
wsl --shutdown
rmdir $env:USERPROFILE\AppData\Local\Temp
start wsl2
ip link
lo: <LOOPBACK> mtu 65536 qdisc noop state **DOWN** mode DEFAULT group default qlen 1000
eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state **DOWN** mode DEFAULT group default qlen 1000
wsl --shutdown
mkdir $env:USERPROFILE\AppData\Local\Temp
start wsl2
lo: <LOOPBACK,UP,**LOWER_UP**> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state **UP** mode DEFAULT group default qlen 1000

#  Expected behavior

Networking should be available regardless of swap space configuration,
or dmesg should be clearly stating that "Cannot start networking because could not configure swap space"

# Actual behavior

Networking is down if swap space is not configured

**Comment by 0xbadfca11** [comment]
#5437
