### ISSUE TITLE
cat /dev/random breaks console

### ISSUE THREAD

**Issue by snobu** [Microsoft/WSL#636]
`cat /dev/random` for longer than a few seconds freezes up things horribly

![random](https://cloud.githubusercontent.com/assets/6472374/16669065/43533b56-449c-11e6-9f4d-2896337f3451.png)

Can't kill that, can't spawn a new shell via **Start -> Bash on Ubuntu on Windows**

```
C:\>ver
Microsoft Windows [Version 10.0.14372]
```

**Comment by jackchammons** [comment]
Running `cat /dev/random` spits out random bytes directly to STDOUT. It is likely that some of these bytes contain control codes that change the behavior of the terminal in [wonky ways](http://superuser.com/questions/637860/why-does-cat-dev-urandom-break-your-terminal).

It may be that what you are seeing is expected behavior but we will take a look to make sure that is it. Thanks for submitting this.

**Comment by benhillis** [comment]
@jackchammons Excellent point, Jack.  @snobu does the same usage break native Ubuntu as well?

**Comment by snobu** [comment]
While I agree with the control characters part, in native Linux the worst thing that happens to the console is to become unreadable (I.e.squares instead of ASCII). This is then easily fixed by typing `reset`.

**Comment by snobu** [comment]
Just to be clear, the expectation here is not to gracefully handle all garbage chars but to not get into that state where you can't kill the process. If it crashes, so long, we'll start another.

**Comment by Herst** [comment]
Cannot be reproduced using `dd` or similar, so I guess reading from `/dev/random` is not the issue here:
```sh
$ time dd if=/dev/random of=/dev/null count=3MB
3000000+0 records in
3000000+0 records out
1536000000 bytes (1.5 GB) copied, 4.0079 s, 383 MB/s

real    0m4.024s
user    0m1.031s
sys     0m2.984s
```

**Comment by snobu** [comment]
I believe this is now fixed. It's now throwing i/o error instead of console host falling apart.

```
root@speshulK:~# cat /dev/random
&K$3*ϴ>^EhIqŽ`GE)5ɞE=HK-b$78K1f~ĸa(2 oK0Uq@ډKɁӈ8%ؖdFl{W#}e7p(^d~W
[ʒj9Ī}4=MEMP:#Z(&7taFL^vk8+)fbhb*ag1XP8RXT弬ʴu&Kv]Cy~Y fh8sZv)N|I'(ܛN~%WLDCZu]Gn:X%Bbq]wʛsoN⊨˱g+
Y\?i>

cat: write error: Input/output error
```

**Comment by therealkenc** [comment]
Meh. Close if you like (not going to look a gift horse in the mouth) but that's not Linux behaviour. On Linux it blocks once it runs out of entropy. WSL doesn't have to implement some fancy-schmancy entropy pool just now, of course. But that IO error is just going to cause a fail somewhere eventually.

**Comment by snobu** [comment]
```
root@speshulK:~# cat /dev/random > file
[5 sec later]
^C

root@speshulK:~# cat /dev/urandom > file
[5 sec later]
^C

root@speshulK:~# cat file
cat: write error: Input/output error

root@speshulK~# xxd file | more

root@speshulK:~# xxd file | more
00000000: a92e 6129 07eb 24b6 f885 1fac c416 4f20  ..a)..$.......O
00000010: 39c4 994b 3d68 063d 6bae 58d9 ef3d a990  9..K=h.=k.X..=..
00000020: 273c 3568 ef51 fca6 92ff 4363 09a4 32f2  '<5h.Q....Cc..2.
00000030: 73de 263a afe4 a133 9989 2299 4202 bb6e  s.&:...3..".B..n
00000040: 383d 8987 ae4b 332f 586a 5506 4548 301c  8=...K3/XjU.EH0.
00000050: 6fad 0980 2207 76d0 ee2e c983 4654 d737  o...".v.....FT.7
00000060: d4c3 433c b195 e0a6 73ac 2443 3d80 0edc  ..C<....s.$C=...
00000070: e75e 38b2 e97b 5c37 b6a8 8cd0 ca73 a769  .^8..{\7.....s.i
00000080: f0f9 5f54 5cd7 44aa a3e0 6ac1 a38d aee5  .._T\.D...j.....
00000090: 8c96 841b aa8b c363 63b8 651d c916 2da1  .......cc.e...-.
000000a0: 15c9 66ba cf6c c982 be9f 61e6 8917 8b4c  ..f..l....a....L
000000b0: 1fdb 314b 2e96 e0b3 75f7 62ce a912 655d  ..1K....u.b...e]
000000c0: f170 a3c1 5c7e a9b3 df06 ade8 dff0 fdf3  .p..\~..........
000000d0: 3d78 1400 43e9 4b0f b4c4 9f83 5d4c f564  =x..C.K.....]L.d
000000e0: 3a58 f717 4271 5507 ee27 f4ab 9a2f cf5a  :X..BqU..'.../.Z
000000f0: f38a 9996 afff acff 0320 3f65 20f5 e64b  ......... ?e ..K
00000100: b987 88d1 8da5 d8d3 57b1 3327 8637 43dc  ........W.3'.7C.
[...]
```
It's just a matter of the console panicking when reading non-printables..
I don't think this will cause any trouble, `/dev/random` and `urandom` seem to do their job the Linux way.

**Comment by therealkenc** [comment]
> It's just a matter of the console panicking when reading non-printables..

Ahh, gotcha; thanks. It's a _write_ error (to `stdout` aka `/dev/tty`) not a _read_ error (from `/dev/random`). It doesn't look like `/dev/random` reads proper were broken in the first place. That I/O error still incorrect behaviour though. But I suppose different issue#, if one wants to quibble. But the book-keeping problem with closing is this one is it wasn't marked bug and wasn't marked fixed in any build number.

**Comment by snobu** [comment]
Reopening until things settle down.

**Comment by snobu** [comment]
@therealkenc You're spot on:

```
root@speshulK:~# for i in `head junk`; do echo $i; echo $i > /dev/tty; done

%YV^'"\f`~S(庋6gڀZfw0ۡ܎pBt'RT*ƎPGnPSa'4(uP&CȐ&SZ
%YV^'"\f`~S(庋6gڀZfw0ۡ܎pBt'RT*ƎPGnPSa'4(uP&CȐ&SZ
PC0ۜag4+Y[VXD˯5%*}}>ć*1~:97"Bw90{
PC0ۜag4+Y[VXD˯5%*}}>ć*1~:97"^LB90{
OLD{pbR
`^@X}R4R]C5ag3ކ'kiMyk=;YO9.];%7bFg+!Z
>SUyRHRoY.Q9mju,t1WV36QA5;4l"d7wQƴ";e;-zHp*
}f:HXQ|']D5w
bash: echo: write error: Input/output error
```

**Comment by therealkenc** [comment]
Best to re-open this one over in the [windows console issue tracker](https://github.com/microsoft/console). I just did a quick test and the input/output error doesn't manifest in mintty or PuTTY.
