### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070003

### ISSUE THREAD

**Issue by wxxiong6** [microsoft/WSL#6363]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 ???????????

Press any key to continue...

**Comment by sirredbeard** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and provide a link the feedback hub item.

**Comment by benyaminl** [comment]
https://github.com/microsoft/WSL/issues/6512#issuecomment-773173169

Please do https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html and try to enable wsl again, it should work correctly. It mean there're some file missing. I seen this in many windows installation (clean windows), and the only way to fix it is either reset the windows or in-place upgrade. I choose In-place upgrade.

**Comment by pdebuitlear** [comment]
Saying "there's some file missing" isn't helpful. Not everyone in corporate settings can do an in-place upgrade.

**Comment by Biswa96** [comment]
Instead of relying on Microsoft's Windows Store, try to manually install a distribution with `wsl.exe --import` command.

**Comment by benyaminl** [comment]
> 
> 
> Saying "there's some file missing" isn't helpful. Not everyone in corporate settings can do an in-place upgrade.

I agree with that, but til about 6 month looking into log, there're nothing that help, and my lab need to go on, so I just in-place upgrade each computer on my lab. It's troublesome. The mod on reddit also doesn't help at all and state there won't be any 0x80070003 if we put the wsl on C: drive. In-place ugrade is my last resort, at least it's working now, but https://github.com/microsoft/WSL/issues/5718 hasn't fixed yet till now.

**Comment by therealkenc** [comment]
Logs from #6512 [here](https://github.com/microsoft/WSL/files/5919670/wsl.etl.zip).

**Comment by EduardoCabria** [comment]
> 
> 
> Saying "there's some file missing" isn't helpful. Not everyone in corporate settings can do an in-place upgrade.

Hi ! 
I have the same problem, when I try to install a Linux distribution on my Windows (because it is a WSL2 requirement, in order to run Docker Desktop on my local Windows10 laptop), I get this message:
![imagen](https://user-images.githubusercontent.com/55672109/118448371-373cbb80-b6f2-11eb-9da4-ac8349a2d640.png)

**Have you found a solution other than the one proposed by @benyaminl  ?**

It happens to me like @pdebuitlear , I have a corporative settings and I can't do an in-place upgrade.

Thankyou!

**Comment by pdebuitlear** [comment]
> > Saying "there's some file missing" isn't helpful. Not everyone in corporate settings can do an in-place upgrade.
> 
> Hi !
> I have the same problem, when I try to install a Linux distribution on my Windows (because it is a WSL2 requirement, in order to run Docker Desktop on my local Windows10 laptop), I get this message:
> ![imagen](https://user-images.githubusercontent.com/55672109/118448371-373cbb80-b6f2-11eb-9da4-ac8349a2d640.png)
> 
> **Have you found a solution other than the one proposed by @benyaminl ?**
> 
> It happens to me like @pdebuitlear , I have a corporative settings and I can't do an in-place upgrade.
> 
> Thankyou!

The fix for me was to set the following registry key value to 1:
HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive

**Comment by lokinmodar** [comment]
My system: 
```
Edition	Windows 10 Pro
Version	Dev
Installed on	‎5/‎21/‎2021
OS build	21382.1
Experience	Windows 10 Feature Experience Pack 321.12100.0.3
```
Fresh installed system and it produced the op error. Did the inplace upgrade by iso and no success. Even docker is giving me errors:
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to %LOCALAPPDATA%\Docker\wsl\distro: exit code: -1
 stdout: The system cannot find the path specified.
```

Funny thing is: before I format the PC due to another issue everything was working flawlessly (I was already using this Dev Channel Build)

**Comment by benyaminl** [comment]
Does the folder exist? Because if that folder doesn't exist than it will
raise such error.




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by lokinmodar** [comment]
> Does the folder exist? Because if that folder doesn't exist than it will raise such error.

Yes it does but i managed to finally solve the issue by deleting the file `%USERPROFILE%\.wslconfig`, restarting wsl and retrying the distro install. It is worth to check for this before doing any in-place upgrade...

**Comment by ksugiarto** [comment]
> > Does the folder exist? Because if that folder doesn't exist than it will raise such error.
> 
> Yes it does but i managed to finally solve the issue by deleting the file `%USERPROFILE%\.wslconfig`, restarting wsl and retrying the distro install. It is worth to check for this before doing any in-place upgrade...

Thanks a lot, this is finally the one that able to solve mine as well.

I tried to do the upgrade-reset windows as well as I forgot someone said it is working on him but I cannot find his post again now. Didn't work though.

**Comment by rbalmeida** [comment]
I was having issues reinstalling, just deleted the wslconfig file as suggested by @lokinmodar and it resolved my issue as well. Thanks for sharing.

**Comment by walfredocarneiro** [comment]
> 
> 
> > > Does the folder exist? Because if that folder doesn't exist than it will raise such error.
> > 
> > 
> > Yes it does but i managed to finally solve the issue by deleting the file `%USERPROFILE%\.wslconfig`, restarting wsl and retrying the distro install. It is worth to check for this before doing any in-place upgrade...
> 
> Thanks a lot, this is finally the one that able to solve mine as well.
> 
> I tried to do this repair-install
> 
> > [#6512 (comment)](https://github.com/microsoft/WSL/issues/6512#issuecomment-773173169)
> > Please do https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html and try to enable wsl again, it should work correctly. It mean there're some file missing. I seen this in many windows installation (clean windows), and the only way to fix it is either reset the windows or in-place upgrade. I choose In-place upgrade.
> 
> Didn't work for me.

====> This work for me.

**Comment by ioweb-gr** [comment]
For my case there's no .wslconfig file. The error persists on fresh install of windows 11.

**Comment by huang-tianwen** [comment]
> For my case there's no .wslconfig file. The error persists on fresh install of windows 11.

any luck in fixing this?
I regretted so much to upgrade my windows..

**Comment by robinduerhager** [comment]
None of the provided workarounds helped me.
I also don't have a `.wslconfig`. I still get the following error:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 Das System kann den angegebenen Pfad nicht finden.

Press any key to continue...
```

Really enjoyed working with WSL so i hope this can get fixed 😞.

**Comment by huang-tianwen** [comment]
> None of the provided workarounds helped me. I also don't have a `.wslconfig`. I still get the following error:
> 
> ```
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80070003
> Error: 0x80070003 Das System kann den angegebenen Pfad nicht finden.
> 
> Press any key to continue...
> ```
> 
> Really enjoyed working with WSL so i hope this can get fixed 😞.

Back up data and reinstall win 11, I also reset it and it works.
But all applications need to re-install.

**Comment by robinduerhager** [comment]
> > None of the provided workarounds helped me. I also don't have a `.wslconfig`. I still get the following error:
> > ```
> > Installing, this may take a few minutes...
> > WslRegisterDistribution failed with error: 0x80070003
> > Error: 0x80070003 Das System kann den angegebenen Pfad nicht finden.
> > 
> > Press any key to continue...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Really enjoyed working with WSL so i hope this can get fixed 😞.
> 
> Back up data and reinstall win 11, I also reset it and it works. But all applications need to re-install.

I'm on Windows 10. Idk why, but WSL just suddenly stopped working.
I really don't want to reinstall windows all over again... I'd rather use a Linux Machine on Hyper-V, haha.
I feel like there must be another wokraround or fix.

**Comment by VAllens** [comment]
Any progress?
I am using windows 11

**Comment by miron** [comment]
> > Does the folder exist? Because if that folder doesn't exist than it will raise such error.
> 
> Yes it does but i managed to finally solve the issue by deleting the file `%USERPROFILE%\.wslconfig`, restarting wsl and retrying the distro install. It is worth to check for this before doing any in-place upgrade...

Forgot about this lurking around when I compiled a custom kernel :)

**Comment by VincentSastra** [comment]
I came across this same issue on Windows 10 Home.
I have enabled virtualization on my BIOS and enabled both `Virtual Machine Platform` and `Windows Hypervisor Platform` Windows Features. I have tried re-installing these features multiple times but I couldn't make it work.

I was finally able to fix the issue by doing a a Windows In-Place Upgrade. More specifically I followed the direction in this tutorial: [repair-install-windows-10-place-upgrade](https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html) to do the upgrade with the ISO file.

Hope this can help someone :)

**Comment by Shadow-Cipher** [comment]
> > > Saying "there's some file missing" isn't helpful. Not everyone in corporate settings can do an in-place upgrade.
> > 
> > 
> > Hi !
> > I have the same problem, when I try to install a Linux distribution on my Windows (because it is a WSL2 requirement, in order to run Docker Desktop on my local Windows10 laptop), I get this message:
> > ![imagen](https://user-images.githubusercontent.com/55672109/118448371-373cbb80-b6f2-11eb-9da4-ac8349a2d640.png)
> > **Have you found a solution other than the one proposed by @benyaminl ?**
> > It happens to me like @pdebuitlear , I have a corporative settings and I can't do an in-place upgrade.
> > Thankyou!
> 
> The fix for me was to set the following registry key value to 1: HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive

THANK YOU!!!!  This fixed my WSL issue, awesome!

**Comment by rudolphos** [comment]
> HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive

Didn't work:

![image](https://user-images.githubusercontent.com/4366810/209989901-82b3d868-216b-45e3-b43c-1d2ea0e6b799.png)

Windows 10, 19045.2364; Windows Feature Experience Pack 120.2212.4190.0

**Comment by mozhuanzuojing** [comment]
1. Open regedit
2. Find `计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`
3. 删除Lxss下空的注册表项，例如：`{24022fa9-20a9-4e2a-9cde-9c1bfe4e67f3}`
4. <img width="1280" alt="wsl-regedit" src="https://user-images.githubusercontent.com/63572041/227429961-dd685cf2-dd29-4a9c-9029-b9cd6dc84624.png">

**Comment by mohdwaseem** [comment]
Try this simple solution, it works with me 
[https://stackoverflow.com/a/67639264/1849480](url)

**Comment by LouieMartin** [comment]
I have not coded  for like a month because of this issue, any progress?

**Comment by Cyterg** [comment]
Disabling core isolation (VBS) and then reenabling and reinstalling WSL fixed the problem for me.

**Comment by ptomato** [comment]
I managed to fix the problem by going to "Turn Windows featuers on or off" in Settings, unchecking "Virtual Machine Platform" and "Windows Subsystem for Linux", rebooting, and then reinstalling WSL.

**Comment by yuanqingye** [comment]
> > Does the folder exist? Because if that folder doesn't exist than it will raise such error.
> 
> Yes it does but i managed to finally solve the issue by deleting the file `%USERPROFILE%\.wslconfig`, restarting wsl and retrying the distro install. It is worth to check for this before doing any in-place upgrade...

works for me!!

**Comment by robinduerhager** [comment]
I just tried this solution but with Ubuntu-18.04.6 and Ubuntu-22.04.6 and it finally worked for me :)

https://github.com/microsoft/WSL/issues/3054#issuecomment-1783150815

**Comment by ScofieldaCreep** [comment]
> > Resolved `WslRegisterDistribution failed with error: 0x80070003`
> 
> 1. Open `regedit`
> 2. Find `计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`
> 3. 删除`Lxss`下空的注册表项，例如：`{24022fa9-20a9-4e2a-9cde-9c1bfe4e6700}`
> 4. <img alt="wsl-regedit" width="1280" src="https://user-images.githubusercontent.com/63572041/227429961-dd685cf2-dd29-4a9c-9029-b9cd6dc84624.png">

This works for situations like you mishandle the regits qaq

**Comment by EllieShan** [comment]
> > Resolved `WslRegisterDistribution failed with error: 0x80070003`
> 
> 1. Open `regedit`
> 2. Find `计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`
> 3. 删除`Lxss`下空的注册表项，例如：`{24022fa9-20a9-4e2a-9cde-9c1bfe4e6700}`
> 4. <img alt="wsl-regedit" width="1280" src="https://user-images.githubusercontent.com/63572041/227429961-dd685cf2-dd29-4a9c-9029-b9cd6dc84624.png">

it works for me after delete items under Lxss, thanks.

**Comment by Jacquwes** [comment]
Hello, I'm having the same error since installing Atlas OS on my computer. I have enabled the optional features, virtualization is enabled in BIOS, there is no .wslconfig file, there is no Lxss entry in my registry. I cannot do an in-place system upgrade. Any other solutions?

**Comment by craigloewen-msft** [comment]
This issue has been open for a long time, and so we're going to close it out for bookkeeping purposes. 

If you're still seeing this issue please check out this workaround: https://github.com/microsoft/WSL/issues/6363#issuecomment-1789786151 and if that doesn't fix you please file a new issue on our GitHub so we can actively triage you! Thanks!

**Comment by LeonardoAragaoDev** [comment]
In my case, I resolved the issue by reinstalling WSL with the following steps:
1. Running `wsl --uninstall`
2. Running `wsl --install`
3. Registering a root user
4. Opening a normal terminal
