### ISSUE TITLE
[WSL2] Cannot access windows service running on host from a container using `host.docker.internal`

### ISSUE THREAD

**Issue by mgcrea** [microsoft/WSL#6364]
# Environment

```none
Windows build number: 10.0.19042.572
Your Distribution version: lsb_release: not found
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

It's running on a clean Windows10 install followed by a docker desktop 3.0 setup and a `docker-compose up -d`.

# Steps to reproduce

Start a service on the windows host:

```sh
npm i -g http-server
http-server -p8080
```

Run a container with a bind on host-gateway:

```sh
docker run -it --rm --add-host=host.docker.internal:host-gateway alpine
```

Try to curl the windows host inside (`/etc/hosts` properly has `192.168.65.1    host.docker.internal`):

```sh
curl http://host.docker.internal:8080
```

#  Expected behavior

Working access according to the [WSL docs: Accessing Windows networking apps from Linux (host IP)](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-windows-networking-apps-from-linux-host-ip)

So not sure if the docs are outdated (WSL1?) or if I have something misconfigured but this is on a clean install and with Windows Defender turned off.

# Actual behavior

```
/ # curl http://host.docker.internal:8080
curl: (28) Failed to connect to host.docker.internal port 8080: Operation timed out
```

Does work if I use the `vEthernet (WSL)` ip (eg. `curl http://172.27.64.1:8080`), but since it changes at every restart and I haven't found a reliable way to expose this IP address to my container, I'm stuck.

**Comment by simonferquel** [comment]
You should try without adding the `--add-host` flag (it is not needed on Desktop). We fixed it lately, but not sure if it is in a public build yet.

**Comment by mgcrea** [comment]
@simonferquel looks like it is still currently needed in my build:

```
PS C:\Users\User> docker run -it --rm --add-host=host.docker.internal:host-gateway alpine cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.65.1    host.docker.internal
172.17.0.2      b2cf9d3b8df1
```

```
PS C:\Users\User> docker run -it --rm alpine cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      3902d9cb5dc4
```

Do you know if it is supposed to work like the docs says? iirc host.docker.internal targets the linux VM running inside windows and it "should" forward the incoming request to the windows host to reach actual services?

Or do I actually don't need the linux VM IP (host.docker.internal) but the actual windows vEthernet IP (auto-configured by docker 172.xxx.xxx.1 with a netmask of 255.255.240.0).

**Comment by THEMrinaal** [comment]
Hi There,
I am getting the same error!
```python
r = adapter.send(request, **kwargs)
  File "/opt/bitnami/python/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=30002): Max retries exceeded with url: /api/v1/datastore/write (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdbccf2e130>: Failed to establish a new connection: [Errno -2] Name or service not known'))
127.0.0.1 - - [18/Feb/2021 03:48:40] "POST /api/v1/user/ HTTP/1.1" 500 -
```
