### ISSUE TITLE
ffmpeg nvenc does not detect the driver in wsl2 and exits

### ISSUE THREAD

**Issue by tadam98** [microsoft/WSL#6367]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`] 20279.1
Your Distribution version: [On Debian or Ubuntu run  in WSL] `Release:	18.04`
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
nvidia driver on windows 465.12
Cuda 10.2
```

# Steps to reproduce
$ ffmpeg -version
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
$ ffmpeg -i video.mp4 -vf scale=iw/2:ih/2 -vcodec h264_nvenc "video_2.mp4" 
Cannot load libnvidia-encode.so.1
[h264_nvenc @ 0x55e21d81f020] The minimum required Nvidia driver for nvenc is 378.13 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x55e21d81d780] Qavg: 29185.615
[aac @ 0x55e21d81d780] 2 frames left in the queue on closing
Conversion failed!

ffmpeg does not detect the driver version (well....the driver is downbelow in the windows host...) and refuses to use the hardware acceleration.

**WSL logs**: 

#  Expected behavior
Detected WSL2 and somehow either detected the underlying driver or continue to work.

# Actual behavior
Program exits.

**Comment by tadam98** [comment]
Could it be associated with:
https://forums.developer.nvidia.com/t/building-ffmpeg-with-nvenc-inside-docker-container-in-wsl-2-linux-distro/155102/2

$ ls -la /usr/lib/wsl/lib/
total 82064
dr-xr-xr-x 1 root root     4096 Dec 15 15:55 .
drwxr-xr-x 4 root root     4096 Nov 10 07:29 ..
-r--r--r-- 1 root root   133088 Nov 11 18:09 libcuda.so
-r--r--r-- 1 root root   133088 Nov 11 18:09 libcuda.so.1
-r--r--r-- 1 root root   133088 Nov 11 18:09 libcuda.so.1.1
-r--r--r-- 2 root root   785480 Dec 10 13:02 libd3d12.so
-r--r--r-- 2 root root  5300896 Dec 10 13:02 libd3d12core.so
-r--r--r-- 2 root root 25263616 Dec 10 13:02 libdirectml.so
-r--r--r-- 2 root root   827632 Dec 10 13:02 libdxcore.so
-r--r--r-- 1 root root   191976 Nov 11 18:09 libnvidia-ml.so.1
-r--r--r-- 1 root root 51243080 Nov 11 18:09 libnvwgf2umx.so

**Comment by tadam98** [comment]
Updateing the nvidia windows driver to 465.21 did not help.

**Comment by therealkenc** [comment]
Your earlier post /dupe #6357 as landing zone
