### ISSUE TITLE
[NeedHelp] How to install WSL in E: instead of in C:? 

### ISSUE THREAD

**Issue by 517030910405** [microsoft/WSL#6368]
I am trying to install WSL Ubuntu20 in a customized directory using Microsoft Store. 

1) I created a link in `C://Users…………` pointing to the `E://Users…………`. 
2) I use the default installation with Microsoft Store. 

The method above worked for Ubuntu18. But it failed with Ubuntu20. 

Does anyone have a guide for the standard method of installing in a customized directory? 

Thanks

**Comment by therealkenc** [comment]
/dupe #449. Or feel encouraged to open a [discussion](https://github.com/microsoft/WSL/discussions). SOP these days is to use `wsl --import` mostly.
