### ISSUE TITLE
Possible to restore WSL from disk file(vhdx)?

### ISSUE THREAD

**Issue by dotSlashLu** [microsoft/WSL#6371]
**Is your feature request related to a problem? Please describe.**
I reinstalled Windows and the system disk is wiped so the wsl entries are gone, but the WSL disk file(.vhdx) is located in another disk and unaffected. I couldn't find a way to restore it. 

**Describe the solution you'd like**
A command to restore it? Or maybe `wsl --import` can already do this?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by therealkenc** [comment]
/dupe #4849 ➡️ #4762. Could also start a [discussion](https://github.com/microsoft/WSL/discussions) for work-arounds.
