### ISSUE TITLE
OpenCL support on WSL

### ISSUE THREAD

**Issue by jackz314** [microsoft/WSL#6372]
These blogposts: [1](https://devblogs.microsoft.com/directx/directx-heart-linux/), [2](https://devblogs.microsoft.com/directx/in-the-works-opencl-and-opengl-mapping-layers-to-directx/) from months ago suggest that OpenCL and OpenGL support will come to WSL via mapping layer on DX12. I just tested out OpenGL and it seems to work fine (albeit an old version), however, I also tried to test OpenCL (with `clinfo`), but it shows "Number of platforms 0". Is OpenCL not supported yet or is this not normal? 

I am running the latest dev preview version of Windows (10.0.21277.1000, build 21277.1000), and Ubuntu 20.04 on WSL with kernel version 5.4.72-microsoft-standard-WSL2.

**Comment by mSv1306** [comment]
Hi, did you get any new info about opencl?

**Comment by aerorohit** [comment]
Hi, is there any update on OpenCL compatibility?

**Comment by therealkenc** [comment]
forward /dupe to #6951 which is more recent WSL2 with WSLg and includes some logging.
