### ISSUE TITLE
Kill "Vmmem" in task manager

### ISSUE THREAD

**Issue by Msadr471** [microsoft/WSL#6373]
Hello everyone, how can I close this program that is open in the background! When I open Linux and run the command `kex --sl -s`, a graphical environment opens, but when I exit it, even when I run the command `kex --sl --stop`, this ``Vmmem`` is still open in the background of Windows! Do you have a solution? Occupies a lot of laptop RAM! thank you.
![image](https://user-images.githubusercontent.com/49529241/102995127-9fb5b100-4535-11eb-8821-53a12a8dafc3.png)
![image](https://user-images.githubusercontent.com/49529241/102995763-fbcd0500-4536-11eb-818d-f4ada391b7ed.png)

Kali Linux
![image](https://user-images.githubusercontent.com/49529241/102995702-ddffa000-4536-11eb-8958-242262477b6f.png)

**Comment by therealkenc** [comment]
Variation this [question](https://devblogs.microsoft.com/oldnewthing/20180717-00/?p=99265). Your virtual machine is still running, by design. This is unrelated to 'kex'. You could in principle do `wsl.exe --shutdown`.
