### ISSUE TITLE
cant't upgrade to WSL2

### ISSUE THREAD

**Issue by Adamkaram** [microsoft/WSL#6376]
i'm tryong to upgrade my wsl to wsl2 
every time i got a proplem 
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
![uuu](https://user-images.githubusercontent.com/52092726/103112007-054f8d80-465b-11eb-88f6-e48eca3af0b1.png)

i have ubuntu on my C patrtaion installe and swap between windows 10 and Ubuntu
why there's No version displaying to me when i command wsl -l -v

i'm installing WSL Ubuntu from here 
https://www.microsoft.com/en-eg/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab
Not a specific version

try it with 
wsl --set-version Ubuntu-18.04 2 
and
wsl --set-version Ubuntu-20.04 2
both give me : 
There is no distribution with the supplied name.
![عع3](https://user-images.githubusercontent.com/52092726/103112217-95420700-465c-11eb-8d3b-8a6fbf75e7ab.png)

my os build 
![d2](https://user-images.githubusercontent.com/52092726/103112241-c15d8800-465c-11eb-8cc1-67dbaee2ebe1.png)

My windows
![version](https://user-images.githubusercontent.com/52092726/103112261-ebaf4580-465c-11eb-8bbd-168fd861e215.png)

virtualization is enabled 
![u2](https://user-images.githubusercontent.com/52092726/103112101-bce49f80-465b-11eb-8d00-3e8109b80ed6.png)

 Virtual Machine Platform Windows feature is enable

![uu3](https://user-images.githubusercontent.com/52092726/103112108-d2f26000-465b-11eb-95c3-1a3db28a880d.png)

I followed all instructions here
https://docs.microsoft.com/en-us/windows/wsl/install-win10

updating my karel linux 
![upd](https://user-images.githubusercontent.com/52092726/103112315-34ff9500-465d-11eb-8946-3588eb2391b9.png)

and it's the same probleme

**Comment by 0xbadfca11** [comment]
The Core 2 Duo E8400 lacks the Intel EPT (aka SLAT) required by WSL2, Hyper-V, and Windows hypervisor.

**Comment by Adamkaram** [comment]
> The Core 2 Duo E8400 lacks the Intel EPT (aka SLAT) required by WSL2, Hyper-V, and Windows hypervisor.

so i need to upgrade my CPU

**Comment by JABirchall** [comment]
> so i need to upgrade my CPU

Yup, WSL2 requires minimum i or e 3000 series CPU.

**Comment by Adamkaram** [comment]
ok thanks all i'll upgrade my pc
