### ISSUE TITLE
WSL enabled but not visible, cannot install Ubuntu

### ISSUE THREAD

**Issue by chris1121voi** [microsoft/WSL#6384]
Windows 10 Enterprise 

Windows build number:
 Build 19042.685

Your Distribution version:
Version 20H2

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
WSL 1

Enabled WSL 1 by running the following command in PowerShell 64 (run as Admin):
```
     dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```
Then rebooted device.

After reboot, get the following results from PowerShell 64 (run as Admin):

![image](https://user-images.githubusercontent.com/63471568/103249460-f572ca80-4934-11eb-8030-475f39dfad40.png)

-- Get-WindowsOptionalFeature command shows Microsoft-Windows-Subsystem-Linux as enabled.
-- wsl -l -v command returns "wsl: The term 'wsl' is not recognized as the name of a cmdlet, function, ..."

I have disabled WSL 1 via PowerShell 64 and rebooted, then reinstalled & rebooted.  Same result.
I have turned Windows Subsystem for Linux off via Programs and Features/Turn Windows features on/off followed by reboot, then turned on again via same method followed by reboot.  Same result as above (enabled, not recognized).

When I attempt to install Ubuntu in this state, Ubuntu returns:
```
"WslRegisterDistribution failed with error: 0x8007019e
```
The Windows Subsystem for Linux optional component is not enabled.  Please enable it and try again."

[wsl_1_ubuntu_fail.zip](https://github.com/microsoft/WSL/files/5749249/wsl_1_ubuntu_fail.zip)

# Expected behavior:
Expect WSL 1 enabled and recognized by system; allow Ubuntu install.
According to Microsoft WSL docs, should be able to enable WSL 1 feature & install Ubuntu.

# Actual behavior
WSL 1 is enabled but not recognized by PowerShell or Ubuntu for install.

**Comment by therealkenc** [comment]
> After reboot, get the following results from PowerShell 64 (run as Admin):

From a non-admin CMD prompt (sic) what is the output of `where wsl` (like this):

![image](https://user-images.githubusercontent.com/7049700/103712643-38552380-4f6f-11eb-91a9-bd6dc7981461.png)

**Comment by benyaminl** [comment]
Try to run in-place upgrade first with lastest iso 
https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html

That should help.

**Comment by igor-teresco** [comment]
Also have this problem, tried reinstalling - no luck.

**Comment by ToasterDEV** [comment]
Running in Windows 10 Pro 19043.1023 (21H1), I was able to run wsl distros after running `cd C:\Windows\System32` and calling WSL.exe as a locally available executable (`.\wsl.exe`) from Powershell 7.1.3 while running as Administrator.

This was tested with WSL2 and Ubuntu 20.10, however trying to invoke the command by itself (`wsl --foo -bar`) from anywhere else still seems to fail, leading me to believe it might be a PATH-related issue. I'm not quite sure which logs would be needed to confirm this, so if anyone knows let me know and I'll send them this way.
```
PS C:\Users\ToasterDEV> wsl
wsl: The term 'wsl' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\ToasterDEV> where wsl
PS C:\Users\ToasterDEV> cd C:\Windows\System32
PS C:\Windows\System32> .\wsl
Welcome to Ubuntu 20.10 (GNU/Linux 5.4.72-microsoft-standard-WSL2 x86_64)
```
