### ISSUE TITLE
WSL No Reponses without any error code.

### ISSUE THREAD

**Issue by ohideyuki** [microsoft/WSL#6385]
All installation are successfully, but after reboot the windows 10, sometimes WSL could not launch successfully.
And could not get the error message. The screenshot has been attached for your reference.
![screen](https://user-images.githubusercontent.com/9860811/103328313-63350880-4a93-11eb-962b-02190e347892.PNG)

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. What you are trying to catch while logging is `wsl` hanging from the powershell prompt.

Also what is the output of: `cmd.exe /c ver`
