### ISSUE TITLE
CMake doesn't seem to recognize the path with "/mnt/"

### ISSUE THREAD

**Issue by AndaOuyang** [microsoft/WSL#6386]
# Environment

```none
Windows build number: [10.0.19042.685]
Your Distribution version: [Release:      Ubuntu  20.04]
Whether the issue is on WSL 2 and/or WSL 1: [WSL2]
```

# Steps to reproduce

**WSL logs**: 

I am configuring CMake in VSCode, WSL2. 
The CMake doesn't seem to treat"mnt/e/" and "E:/" as equal.

#  Expected behavior

# Actual behavior

The cmake error message shows below. I have no idea why the directory is recognized as "e:/" instead of "mnt/e/". Is there any way that I can fix it?

```
[main] Configuring folder: 20t2-cs6771-tut02 
[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/mnt/e/comp6771/20t2-cs6771-tut02/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE:STRING=/mnt/e/comp6771/20t2-cs6771-tut02/config/cmake/toolchains/clang-libcxx.cmake -DVCPKG_TARGET_TRIPLET:STRING=x64-linux-libcxx -DCMAKE_C_COMPILER:STRING=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++-11 -DCMAKE_PREFIX_PATH:STRING=/usr/lib/llvm-11 -H/mnt/e/comp6771/20t2-cs6771-tut02 -B/mnt/e/comp6771/20t2-cs6771-tut02/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error: The current CMakeCache.txt directory /mnt/e/comp6771/20t2-cs6771-tut02/build/CMakeCache.txt is different than the directory e:/comp6771/20t2-cs6771-tut02/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
[cmake] CMake Error: The source "/mnt/e/comp6771/20t2-cs6771-tut02/CMakeLists.txt" does not match the source "E:/comp6771/20t2-cs6771-tut02/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

PS: I put this folder in windows so that I can access the files from both windows and wls

**Comment by MathiasMagnus** [comment]
You are configuring twice into the same build folder. Once from Windows and once from WSL. The error message tells you exactly what's gone wrong:
```
[cmake] CMake Error: The source "/mnt/e/comp6771/20t2-cs6771-tut02/CMakeLists.txt" does not match the source "E:/comp6771/20t2-cs6771-tut02/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```
Delete the leftover files (the cache most importantly) from your Windows build and you'll be good to go.

**Comment by MathiasMagnus** [comment]
You are configuring twice into the same build folder. Once from Windows and once from WSL. The error message tells you exactly what's gone wrong:
```
[cmake] CMake Error: The source "/mnt/e/comp6771/20t2-cs6771-tut02/CMakeLists.txt" does not match the source "E:/comp6771/20t2-cs6771-tut02/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```
Delete the leftover files (the cache most importantly) from your Windows build and you'll be good to go.

**Comment by xubury** [comment]
Although this error was casued by different cache, I do get the problems as described.
```
cmake.exe -G "Unix Makefiles" -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S /mnt/e/codes/OpenGLApp/
CMake Error: The source directory "/mnt/e/codes/OpenGLApp" does not appear to contain CMakeLists.txt.
```

**Comment by BlurringShadow** [comment]
I've got the same issue for WSL while configuring CMake project. Seems like wsl doesn't handle the path very well. I've tried Ubuntu in MS Store or Docker.
This is my [project](https://github.com/BlurringShadow/stdsharp-utility/). I'm now using docker but it falied with the following message
` 
[8/9] RUN cmake -S ./ -DCMAKE_MAKE_PROGRAM=ninja -GNinja -
DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_COMPILER=clang++-12:
#13 0.358 -- Running vcpkg install
#13 0.380 Detecting compiler hash for triplet x64-linux...
#13 0.381 A suitable version of ninja was not found (required v1.10.2). Downloading portable ninja v1.10.2...
#13 0.381 Downloading ninja...
#13 0.381   https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip -> /home/stdsharp/vcpkg/downloads/ninja-linux-1.10.2.zip
#13 2.710 Extracting ninja...
#13 2.714 sh: /home/stdsharp/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja: not found
#13 2.714 Failed to get version of /home/stdsharp/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja
#13 4.434 -- Running vcpkg install - failed
`
