### ISSUE TITLE
powershell breaks cmd.exe styling

### ISSUE THREAD

**Issue by B44ken** [microsoft/WSL#6390]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.685]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1 (Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020)
```
and
```none
Windows build number: Microsoft Windows [Version 10.0.18363.1256]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1 (Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01 PST 2020)
```
# Steps to reproduce

- Launch windows command prompt
- `powershell.exe echo hi > hi.txt` (file/command can be anything)
- `wsl`
- `powershell.exe echo bye > bye.txt` (file/command can be anything)

#  Expected behavior

nothing (the file would be written silently)

# Actual behavior

the file write works, but cmd.exe's font also changes instantly. terminal size, colours, and font size are unchanged.

**Comment by therealkenc** [comment]
> the file write works, but cmd.exe's font also changes instantly

Please grab a screencap like below. That might help give some context on "font also changes instantly". Maybe do a before and after. 

![image](https://user-images.githubusercontent.com/7049700/103713200-9a625880-4f70-11eb-8fee-8dfa8dac3bf5.png)

Also just for the data point, what is your codepage:

![image](https://user-images.githubusercontent.com/7049700/103713978-6b4ce680-4f72-11eb-8b88-4ed110f1d29e.png)

**Comment by B44ken** [comment]
https://user-images.githubusercontent.com/16675719/103715189-f687a580-4f8d-11eb-9da0-09e337c05bab.mp4

My code page is 437. Can you try reproducing in Command Prompt?

**Comment by therealkenc** [comment]
Thanks Brad, I was able to reproduce here. The variable is that my `cmd` prompt was inside [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab). Use that as the work-around.
