### ISSUE TITLE
Ubuntu `who` command

### ISSUE THREAD

**Issue by DGamer007** [microsoft/WSL#6393]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.685]
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

These command should be showing me Username of Ubuntu

# Actual behavior

`who` and `logname` command is not working on WSL 2 Ubuntu

**Comment by heidemn** [comment]
I can confirm that above commands don't work.
But `id` and `whoami` seem to work correctly.
