### ISSUE TITLE
*Server execution failed* while updating WSL 1 to WSL 2 

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/WSL#6397]
# Environment

Microsoft Windows [Version 10.0.19041.685]

lsb_release -r: cannot access to the WSL now 

Whether the issue is on WSL 2 and/or WSL 1: You can say this issue is about both of the versions 

# Steps to reproduce

I'm updating WSL to WSL 2 ` wsl --set-version Ubuntu 2` and it's been two hours already. And when I type command `wsl --list -v` this shows me an error `server execution failed`. What does this mean?? 

#  Expected behavior

This updating process should ends within minutes since it says "Conversion in progress, this may take a few minutes..." and also, I don't want to get this mysterious error message `server execution failed` 

# Actual behavior

PS > wsl --list -v
server execution failed

**Comment by yuis-ice** [comment]
It's been 4 hours

**Comment by yuis-ice** [comment]
solved.

**Comment by starkizard** [comment]
why was this closed?

**Comment by norandomtechie** [comment]
> why was this closed?

I assume they figured it out.

I noticed this issue only after I tried restarting LxssManager from Task Manager > Services, but now it just says "Stopping" forever.  I've tried starting it again from there as well as the Services panel, but neither one works.  Only a full restart seems to solve the issue.

**Comment by yuis-ice** [comment]
I closed the issue because no one seemed to answer.

I solved the issue long while ago by myself. 

This is just my case, so remember that how to solve the error may depends on your environment scenario. you know how ambiguous the error message is. must be all sort of problems will lead the same error. 

For me, I solved the issue by disabling Virtual machine platform. Not only Hyper-v.

(similar case)

[Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS. · Issue #5363 · microsoft/WSL](https://github.com/microsoft/WSL/issues/5363)

Run the below in admin cmd/psl and reboot: 

```
$ dism.exe /online /disable-feature /featurename:VirtualMachinePlatform /norestart
$ dism.exe /online /disable-feature /featurename:Microsoft-Hyper-V /norestart
```
