### ISSUE TITLE
Mounting broken drive in WSL2

### ISSUE THREAD

**Issue by kryogenic** [microsoft/WSL#6398]
**Is your feature request related to a problem? Please describe.**
I was trying to use WSL to run ddrescue on a drive that failed. When I try to mount the drive I get the following error:
`C:\WINDOWS\system32>wsl --mount \\.\PHYSICALDRIVE0 --bare
The system cannot find the file specified.`

**Describe the solution you'd like**
Ideally the drive should be mountable since it does show up in Disk Management. [screenshot](https://i.imgur.com/bS4yzE5.png)

**Edit:**
Actually this seems to be a general problem with my WSL installation, I cannot seem to mount any drive, flash drive, or other.

**Comment by OneBlue** [comment]
@kryogenic: If the disk is broken on Windows, it's expected the WSL can't mount it.

Also, [USB flash drives aren't supported at this time](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations).
