### ISSUE TITLE
File Transfer to /mnt uses up all RAM and crashes PC

### ISSUE THREAD

**Issue by MustafaElshani** [microsoft/WSL#6403]
# Environment

```none
Windows build number: 21277.rs
Your Distribution version: [On Debian or Ubuntu run Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
File Transfer (in particular large transfers, 1TB) through CLI or Windows explorer, continuously increases RAM usage until all of it (beyond the limit set in `.wslconfig`) is used up than it crashes PC -->

No Logs available

#  Expected behavior
Due to large data created in Ubuntu environment, occasionally transfer to other hard drives for back up, during transfer all expected not to use all RAM or crash 

# Actual behavior

PC crashes with it occasionally corrupting the wsl2 `.ext4` drive

**Comment by craigloewen-msft** [comment]
I wasn't able to repro this problem. In both cases when I moved a large file the Vmmem process stopped growing when it reached the size limit specified in the `.wslconfig` file, and I saw no crashes. 

@MustafaElshani could you please check the total memory available to your distro by running `free -h`? Is the Vmmem process growing larger than what is shown in that output? If it is, could you please attach logs of you doing a large transfer using [the instructions here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).

I'm going to close this issue out for bookkeeping purposes, but please reopen it with the logs attached if you're still seeing this. Thanks!

**Comment by MustafaElshani** [comment]
Hi @craigloewen-msft Thank you prompt reply. I have assigned 196GB of the 256GB available 

>total        used        free      shared  buff/cache   available
> Mem:           192G        347M        192G         68K         74M        191G
> Swap:           49G          0B         49G
for df 

> Filesystem       1K-blocks        Used  Available Use% Mounted on
> /dev/sdb        2518767844  2287395524  126271588  95% /

The transfer involves thousand of files totaling 1TB+, the Vmmem process keeps going up up until it crashes I have submitted logs via feedback.

Currently transferring chunks less than the capacity of the RAM available which seems to work

Kindest of Regards

**Comment by craigloewen-msft** [comment]
@MustafaElshani glad that you were able to submit logs for this! Could you please post the link to the Feedback Hub item here in this thread so we're more easily able to find it? Thank you. I'll also reopen this issue since you have logs submitted for it :)

**Comment by MustafaElshani** [comment]
Hi @craigloewen-msft again thank you for looking into this, the feedback logs are on https://aka.ms/AAarl5d

After further testing what seems to be causing the crash is the use of `mv` I think henceforth  I tested the transfer with `cp` this was slower however after reaching maximum assigned RAM it stayed there until the end of copying, without crashing the PC.

I guess this will have to do with the way `mv` vs `cp` handles the memory between filesystems

Hope this helps 

Mustafa

**Comment by MustafaElshani** [comment]
UPDATE
Hi @craigloewen-msft it seems that the removal of the files is causing the crash, I just attempted to` rm -rf `the folder copied earlier and it instantly crashed.
This workstation is being accessed remotely will generate logs when I initiate the rm
