### ISSUE TITLE
[WSL2] - vEthernet (WSL) switch reset/lost configuration after system reboot

### ISSUE THREAD

**Issue by rabsym** [microsoft/WSL#6406]
# Environment

Windows build number: Versión 10.0.20231.1000
Your Distribution version: Debian 10.5 buster (thought not distribution related)
Whether the issue is on WSL 2 and/or WSL 1: WSL 2

# Steps to reproduce

Configuration changes to vEthernet (WSL) switch making it bound to external network are reset/lost after system reboot. 

Step 1 - Configure in Hyper-V Administration Console vEthernet (WSL) switch as external network - bound to a physical network adapter as seen in screenshot 1.

![image](https://user-images.githubusercontent.com/63374639/103822295-24ddb180-5070-11eb-9085-cb071316db4e.png)

Step 2 - Configure vEthernet (WSL) switch network parameters, ip, mask, gateway, dns.

![image](https://user-images.githubusercontent.com/63374639/103822689-e694c200-5070-11eb-975d-e3f66697fff2.png)

Step 3 - Inside WSL distribution (Debian) configure network interface and assign  IP parameters in the same network 192.168.1.0/24 plus gateway and dns resolution config.

Step 4 - Check that everything works as it should: WSL distribution networking works as expected in bridge mode with accesible ports from network, Windows host networking working as expected too. Even checked that if using this vEthernet (WSL) switch in other Hyper-V machines working too with external link. EVERYTHING WORKING. 

Step 5 - Use the system as much as you need, hours...days...

Step 6 - Reboot System.

Step 7 - Check in Hyper-V Administration Console that vEthernet (WSL) is not there until you start any WSL distribution and it appears again but changed to internal. Check also that vEthernet (WSL) switch network parameters, ip, mask, gateway, dns reset to adquire auto and everything stop working as it was previous to rebooting system.

![image](https://user-images.githubusercontent.com/63374639/103824242-cfa39f00-5073-11eb-9682-2860b1d00077.png)

![image](https://user-images.githubusercontent.com/63374639/103824392-15f8fe00-5074-11eb-8f89-e0f6c7ccce6f.png)

#  Expected behavior

Only expecting that WSL system having the same configuration made and working before rebooting system. 

First thing that vEthernet (WSL) it's at Hyper-V Administration Console of Virtual Switchs and also having the same config before rebooting, that is External binding.

# Actual behavior

After rebooting in Hyper-V Administration Console - vEthernet (WSL) switch dissapear till any WSL distribution started and then it changed his binding to internal and vEthernet (WSL) network parameters (ip, mask, gateway, dns) also reset to adquire auto.

Didn't know if this is by design thought i don't think so.

Thanks in advance.
Raimon

**Comment by mrslezak** [comment]
This is driving me crazy as well.  There's no good workaround to set a static IP for WSL2.  Every time I open Debian or any other distro the eth0 address changes so I can't get to my XFCE4 without an: ip a and changing the port address.  Please fix!

**Comment by therealkenc** [comment]
/dupe #4210 since that is really the intent here. This issue is expressing a work-around that doesn't work.

**Comment by mrandreastoth** [comment]
> Hi! We've identified this issue as a duplicate of another one that already exists in this repository. This specific instance is being closed in favor of tracking the concern over on the referenced thread.
> 
> Thanks for your report!

Duplicate of which issue? Please link.
