### ISSUE TITLE
Couldn't start wsl2(ubuntu 18.04) after reboot with errcode  4294967295

### ISSUE THREAD

**Issue by 2ez4Rtzip** [microsoft/WSL#6409]
### Environment
Microsoft Windows [Version 10.0.19042.631]

PS C:\Users\****> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2

### Terminal Output
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[已退出进程，代码为 4294967295]

after expand vhdx max size from 256 to 400GB, i reboot my computer, then can't start wsl2 instance. i tried "netsh winsock reset" after find answers in Issues, unfortunately it doesn't work, and the same as uninstall drivers recently.

**Comment by therealkenc** [comment]
> The connection attempt failed because the connecting party did not respond correctly or the connected host did not respond after a period of time.

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by H-YaoDong** [comment]
> ### Environment
> Microsoft Windows [Version 10.0.19042.631]
> 
> PS C:\Users****> wsl -l -v
> NAME STATE VERSION
> 
> * Ubuntu-18.04    Stopped         2
> 
> ### Terminal Output
> 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> [已退出进程，代码为 4294967295]
> 
> after expand vhdx max size from 256 to 400GB, i reboot my computer, then can't start wsl2 instance. i tried "netsh winsock reset" after find answers in Issues, unfortunately it doesn't work, and the same as uninstall drivers recently.

Did you solve this problem?

**Comment by 2ez4Rtzip** [comment]
not yet， have no idea how to solve. so i change to use vmware temporary




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月4日(星期天) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/WSL] Couldn&#39;t start wsl2(ubuntu 18.04) after reboot with errcode  4294967295 (#6409)





  
Environment
 
Microsoft Windows [Version 10.0.19042.631]
 
PS C:\Users****&gt; wsl -l -v
 NAME STATE VERSION
  
Ubuntu-18.04    Stopped         2
  
Terminal Output
 
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 [已退出进程，代码为 4294967295]
 
after expand vhdx max size from 256 to 400GB, i reboot my computer, then can't start wsl2 instance. i tried "netsh winsock reset" after find answers in Issues, unfortunately it doesn't work, and the same as uninstall drivers recently.
  
Did you solve this problem?

**Comment by H-YaoDong** [comment]
> not yet， have no idea how to solve. so i change to use vmware temporary
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月4日(星期天) 下午5:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [microsoft/WSL] Couldn&#39;t start wsl2(ubuntu 18.04) after reboot with errcode 4294967295 (#6409) Environment Microsoft Windows [Version 10.0.19042.631] PS C:\Users****&gt; wsl -l -v NAME STATE VERSION Ubuntu-18.04 Stopped 2 Terminal Output 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [已退出进程，代码为 4294967295] after expand vhdx max size from 256 to 400GB, i reboot my computer, then can't start wsl2 instance. i tried "netsh winsock reset" after find answers in Issues, unfortunately it doesn't work, and the same as uninstall drivers recently. Did you solve this problem? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I have found my accounts.Because I use the way [Windows Server Installation Guide]("https://docs.microsoft.com/zh-cn/windows/wsl/install-on-server"), but my machine is win10.In the end, I installed the subsystem ubuntu-18.04 from  microsoft store successfully.Besids, I got suggestion that wsl2 takes way too much RAM.I hope this would help you.

**Comment by 2ez4Rtzip** [comment]
thx for your suggestion, also my os version is win10, but my problem is not about installation, i have used for&nbsp; a period of time, the err code becomes after once reboot. in the meanwhile i send feedback follow the guide of microsoft, but have no solution yet&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月11日(星期天) 晚上6:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/WSL] Couldn&#39;t start wsl2(ubuntu 18.04) after reboot with errcode  4294967295 (#6409)





  
not yet， have no idea how to solve. so i change to use vmware temporary
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年4月4日(星期天) 下午5:49 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [microsoft/WSL] Couldn't start wsl2(ubuntu 18.04) after reboot with errcode 4294967295 (#6409) Environment Microsoft Windows [Version 10.0.19042.631] PS C:\Users****&gt; wsl -l -v NAME STATE VERSION Ubuntu-18.04 Stopped 2 Terminal Output 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [已退出进程，代码为 4294967295] after expand vhdx max size from 256 to 400GB, i reboot my computer, then can't start wsl2 instance. i tried "netsh winsock reset" after find answers in Issues, unfortunately it doesn't work, and the same as uninstall drivers recently. Did you solve this problem? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
I have found my accounts.Because I use the way Windows Server Installation Guide, but my machine is win10.In the end, I installed the subsystem ubuntu-18.04 from  microsoft store successfully.Besids, I got suggestion that wsl2 takes way too much RAM.I hope this would help you.
