### ISSUE TITLE
Can not upgrade from wsl 1 to 2, i9-9900X intel, and bios virtualization and virtual machine platform are on.

### ISSUE THREAD

**Issue by virigould** [microsoft/WSL#6411]
# Environment

```none
Windows build number: 10.0.19042.685
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Can't update from wsl1 to wsl2
```

# Steps to reproduce + error screen

![image](https://user-images.githubusercontent.com/30817125/103956650-fe268600-5116-11eb-8302-6b8c8a1a2fba.png)

System Info:
![image](https://user-images.githubusercontent.com/30817125/103956854-5e1d2c80-5117-11eb-8bb9-30bcd24c049a.png)

**Comment by dharmadroid** [comment]
By any means i am not WSL expert, but is possible some running software blocks Hyper-V functionality

I am using  some kind of this software for local wordpress development with Docker, uninstall them and problem gome

**Comment by therealkenc** [comment]
/dupe #5363. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback in that issue.
