### ISSUE TITLE
Mounting a Linux disk requires administrator priviledges

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/WSL#6414]
I am following https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk. When not using Administrator console I get:
```
Administrator access is needed to mount a disk.
```

If it is not possible to mount entire disk without administrator priviledges, I would like to mount at least specific partition without administrator priviledges.

**Comment by OneBlue** [comment]
Thanks for reaching out @vvavrychuk .

When a partition is attached to WSL2, even though only the partition is mounted, the entire disk has to be detached from Windows and attached to WSL2.

By design, administrator access is required to do that, because users have root access in WSL, so `wsl --mount` could be used to bypass the filesystem ACL's if the user doesn't have administrator access.

**Comment by vvavrychuk** [comment]
Without this mounting Linux disks is very tedious. It should be redone every time wsl is restarted via
```
wsl --shutdown
wsl
```

Maybe it makes sense to duplicate "wsl --mount" via system-wide wslconfig to automate disk mounting?

**Comment by OneBlue** [comment]
`wsl --shutdown` unmounts all disks by design, as this command is intended to 'reset' the state of WSL2.

You can automatically mount disks at boot by following [these instructions](https://github.com/microsoft/WSL/issues/6073#issuecomment-707304914) though.

**Comment by vvavrychuk** [comment]
> wsl --shutdown unmounts all disks by design, as this command is intended to 'reset' the state of WSL2.

I am fine with this. I only what WSL to mount disks back again once I start it with `wsl` again.

> You can automatically mount disks at boot by following these instructions though.

This will work for the first time on boot, but if I restart WSL using
```
wsl --shutdown
wsl
```
disk won't be mounted.

**Comment by atkinson** [comment]
why is this issue closed? The problem persists.
