### ISSUE TITLE
/dev/disk/ does not exists in Ubuntu 18.04 LTS in WSL2 (Urgent Help Needed)

### ISSUE THREAD

**Issue by HarshKhilawala** [microsoft/WSL#6422]
# Environment

```none
Windows build number: 19041.685
Your Distribution version: Ubuntu 18.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

/dev/disk/by-id/   does not exist. 
Only dev directory is there. Not even disk.

**Comment by HarshKhilawala** [comment]
![Screenshot_2021-01-07_10-08-52](https://user-images.githubusercontent.com/61461050/104272714-bfe8e800-54c3-11eb-9ad3-55d9c52dac97.png)

**Comment by HarshKhilawala** [comment]
@craigloewen-msft Please take a look and assign someone to provide me support on this!

**Comment by HarshKhilawala** [comment]
@fosslinux

**Comment by fosslinux** [comment]
Why am I being pinged?

**Comment by HarshKhilawala** [comment]
> Why am I being pinged?

@fosslinux  sorry, I though you would be helpful in solving this. I saw you from contributors that's why.

**Comment by Juliaria08** [comment]
> > Why am I being pinged?
> 
> @fosslinux sorry, I though you would be helpful in solving this. I saw you from contributors that's why.

He contributed a fix for a typo

**Comment by HarshKhilawala** [comment]
Anyone who can help on this ? Anyone in your context ?

**Comment by fosslinux** [comment]
Exactly.. I don't use WSL on a day to day basis. Frankly, I find it quite rude to ping random contributors who have not contributed anything at all related to the issue at hand. Also, even if I could help I don't think I would want to with your very 'urgent' 'give me free support' attitude. It's very demanding.

<sub>P.S. you could take 10 seconds to google 'mounting disks wsl2' and another 5 mintues to read the first result which I think is what you need rather than wasting other people's time</sub>

**Comment by HarshKhilawala** [comment]
@fosslinux I apologise mate, 

I already took more than a week searching for this issue. I only thought you would be helpful and didn't know that you fixed a typo and your name is there is contributor list.

**Comment by craigloewen-msft** [comment]
@HarshKhilawala I don't fully understand the issue that you're seeing here, or what you're being blocked by. The /dev/disk/ folder (to my understanding) points to symbolic links that point to the disks stored in /dev/, so you should still be able to access these disks at the end of the day. 

I'm going to close this issue as the template isn't fully filled out, and I don't see any actionable work here for the team. Please feel free to add more context here and edit your issue above and we can evaluate reopening it. Thanks! :)

**Comment by HarshKhilawala** [comment]
@craigloewen-msft Thanks for getting back! I am done with the issue and found an alternative to deal with that.
