### ISSUE TITLE
[WSL 1] Windows takes minutes to launch new programs after running make in Ubuntu

### ISSUE THREAD

**Issue by mzxrules** [microsoft/WSL#6429]
# Environment

```none
Windows build number: [Version 10.0.19041.685]
Your Distribution version: Ubuntu [Release:        20.04]
WSL 1: [Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020]
```

# Steps to reproduce

Set up this repository on the windows file system https://github.com/zeldaret/oot

Run make setup
Run make -j4

**WSL logs**: 

#  Expected behavior

Windows launches my programs in a reasonable timeframe.

# Actual behavior

It takes several minutes to launch a new instances of programs like cmd.exe

The problem started when updating Windows 10

**Comment by therealkenc** [comment]
> It takes several minutes to launch a new instances of programs like cmd.exe

Please post a screencap like the following for context:

![image](https://user-images.githubusercontent.com/7049700/104648381-e5aef200-5667-11eb-8cf3-2329d6c4976e.png)

**Comment by mzxrules** [comment]
![10 minutes](https://user-images.githubusercontent.com/1130747/104670272-8376e100-56a9-11eb-99c5-26d360e3f172.png)
