### ISSUE TITLE
Can't Ping Default switch from WSL2

### ISSUE THREAD

**Issue by iamonlysaiful** [microsoft/WSL#6433]
Here is my host machine Deafault Switch: 
![image](https://user-images.githubusercontent.com/25750962/104683929-1c494300-5722-11eb-98eb-2fc6cf67fd8a.png)

Can't Ping from WSL2
![image](https://user-images.githubusercontent.com/25750962/104683980-384ce480-5722-11eb-9c86-414ca7c5697e.png)

**Comment by sercansebetci** [comment]
I thought the discussion on [this page](https://github.com/microsoft/WSL/issues/4171) might be useful.

**Comment by therealkenc** [comment]
Was able to reproduce here on WSL2 21292. It is the same behavior from within Hyper-V, so this treads by-design or intended behavior on some level. You might try the Hyper-V forum to confirm or see if there is a solution.

What is your use case?

![image](https://user-images.githubusercontent.com/7049700/104947749-12694f00-5971-11eb-899a-38d723184d25.png)

**Comment by Biswa96** [comment]
Is this a feature request or a question? WSL2 uses the `vEthernet (WSL)` virtual network switch which is in different network than `vEthernet (Default Switch)`. There is no routing between them. One could list the networks with `HcnEnumerateNetworks` API and there will be two.

**Comment by therealkenc** [comment]
> vEthernet (WSL) virtual network switch which is in different network than vEthernet (Default Switch)

Yeah, I came close to chalking variation #4150 #4928 et al, but these are outgoing packets and it isn't immediately obvious (to me this morning anyway) why the ping wouldn't reply. Does from Windows. Worst case it is a feature request. Hence the use case ask.

**Comment by iamonlysaiful** [comment]
@therealkenc my use case is I have ubuntu vm with default switch & and a WSL2 ubuntu in my windows 10 machine, From my WSL2 ubuntu I am trying to connect to my ubuntu vm.

**Comment by Biswa96** [comment]
> From my WSL2 ubuntu I am trying to connect to my ubuntu vm.

Then vSockets (AF_HYPERV) can be used for inter-VM communication.

**Comment by iamonlysaiful** [comment]
@Biswa96, Is WSL2 is VM? I successfully communicate two vm by creating two ubuntu vm using hyper-v with default switch. but can't ping vm from wsl2 & In my case all are in local network. Can you explain in details about vSockets (AF_HYPERV).

**Comment by wcpmahmudul** [comment]
We need to set Forwarding to be enabled across the two v-Switches. Using this command (with admin rights) based on my v-Switch names works.

`Get-NetIPInterface | where {$_.InterfaceAlias -eq 'vEthernet (WSL)' -or $_.InterfaceAlias -eq 'vEthernet (Default Switch)'} | Set-NetIPInterface -Forwarding Enabled`

**Comment by Biswa96** [comment]
☝️ This brilliant idea should be in WSL documnetation.

**Comment by Biswa96** [comment]
☝️ This brilliant idea should be in WSL documentation.

**Comment by maroskukan** [comment]
@wcpmahmudul this works well, any idea how to make this configuration permanent across host reboots?

**Comment by Biswa96** [comment]
The virtual network interface for WSL2 VM is not persistent across host reboots. Maybe you can setup a scheduled task or something similar to run that command.
