### ISSUE TITLE
Kali Linux not Installing or responding upon download

### ISSUE THREAD

**Issue by chrisdiamond10** [microsoft/WSL#6438]
![image](https://user-images.githubusercontent.com/66639554/104817317-2d5b8800-57e6-11eb-91f4-4e7dd6f00456.png)
When I open Kali Linux, this is the screen I get, with no "Installing..." message whatsoever. What should I do?

**Comment by therealkenc** [comment]
/dupe #5845 #6405. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in #6405. Also please including your Windows build number per the template.
