### ISSUE TITLE
WSL2 networking issue: unable to connect to localhost for dev server

### ISSUE THREAD

**Issue by teikjun** [microsoft/WSL#6439]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.746]
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
To reproduce the issue, set up the project and development server for the TEAMMATES project. 

**Set up project (Complete instructions [here](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md))**
1. Run `git clone https://github.com/TEAMMATES/teammates.git`
2. Run `npm ci`

**Set up dev server (Complete instructions [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md))**

There are two ways to set up the development server, both methods run into the same issue.

A) **First method**
1. Run `npm run build`. This enables the backend dev server to serve frontend files
2. Run `./gradlew appengineStart`. This command starts the backend dev server on localhost:8080
3. View localhost:8080 on your browser

B) **Second method**
1. Run `npm run start`. This command starts the frontend dev server on localhost:4200
2. Run `./gradlew appengineStart`. This command starts the backend dev server on localhost:8080
3. View localhost:4200 on your browser. Click on sign in button at the top right of the page.

**WSL logs**: 
I'm unable to pinpoint what the issue is. Hence, I'm unsure about which command I should be recording logs for.

**Other logs**:
After running `./gradlew appengineStart`, there is a process on port 8080 as expected, but it cannot be accessed on localhost:8080 (see next section)
![image](https://user-images.githubusercontent.com/46853051/104819841-5eca6700-586b-11eb-9cb8-cf639c90ae82.png)

#  Expected behavior

The expected behavior is displayed on a regular linux VM (using VMware workstation player).

**First method**
localhost:8080 should serve the frontend together with the backend. Upon clicking the login button, the login page is shown.
![image](https://user-images.githubusercontent.com/46853051/104821071-4f9be700-5874-11eb-9cf9-c5ee071b5c07.png)

**Second method**
localhost:4200 should serve the frontend. Upon clicking the login button, the login page is shown.

# Actual behavior

**First method**
Unable to connect to localhost:8080. No errors logged in console.
![image](https://user-images.githubusercontent.com/46853051/104819638-c97aa300-5869-11eb-9b79-f2b612798b72.png)

**Second method**
localhost:4200 is accessible, but it cannot use backend functionality (e.g. Authentication). So, the user is redirected back to the static home page.

## Summary 
I am unable to set up the frontend and backend development server together with WSL2. When localhost:8080 is accessed, I receive a 404 error with no other errors logged in the console. On the other hand, I am able to set up the dev server properly on a linux VM with the exact same steps. I am unable to pinpoint the specific issue in WSL2 that is causing this problem.

**Comment by rlabrecque** [comment]
Try replacing localhost:8080 in your application with 0.0.0.0:8080

Maybe here: https://github.com/TEAMMATES/teammates/blob/a5cad8417129abd6bb223b35e396047358d1c17e/src/web/environments/environment.ts

**Comment by teikjun** [comment]
> Try replacing localhost:8080 in your application with 0.0.0.0:8080

I just tried this, but the outcome is the same - 404 error received on http://localhost:8080

**Comment by rlabrecque** [comment]
When it's up and running are you able to hit it with curl http://localhost:8080 from inside WSL2?

**Comment by teikjun** [comment]
>When it's up and running are you able to hit it with curl http://localhost:8080 from inside WSL2?
Yes I am able to hit it with `curl http://localhost:8080`, it returns the following result:
![image](https://user-images.githubusercontent.com/46853051/104846735-f89b1e00-5916-11eb-9ee9-7bfde994fecd.png)

**Comment by therealkenc** [comment]
Merging into similar /dupe #4885. These are often variation #4851.

**Comment by teikjun** [comment]
Thanks @therealkenc and @rlabrecque for the help!
Just in case anyone faces a similar issue, here is the link to the comment that resolved my issue: https://github.com/microsoft/WSL/issues/5298#issuecomment-695181844.
