### ISSUE TITLE
WSL session always stop prematurely

### ISSUE THREAD

**Issue by menih** [microsoft/WSL#6440]
With WSL2, sessions terminated for no reason. I speculate this has to do with the introduction of vmIdleTimeout, but there is no way to modify it and it does not take. Documentation is very poor about where to place the config and how to set it. I found a few blogs in Chinese discussion <User Profile>/.wslconfig and an entry there. But it does not obey the setting.

**Comment by menih** [comment]
I think this is not related to idle time at all... it simple terminate the whole subsystem prematurely all of a sudden, with in few minutes into the session, for no evident reason. How do I debug this...? I am desperate. I do any meaningful work like this.

**Comment by benhillis** [comment]
Please take a trace, instructions are in the issue template.
