### ISSUE TITLE
WSL2 error code 0x800701bc

### ISSUE THREAD

**Issue by mdogwoop** [microsoft/WSL#6442]
I have a problem when using wsl, it prompts error code 0x800701bc. In other issues, the solution is to install a file from https://aka.ms/wsl2kermel, but when I install it, it will prompt A later version of the  Windows Subsystem for Linux Update is already installed. Setup will now exit.

**Comment by therealkenc** [comment]
Please post the output of `cmd.exe /c ver`, and collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. A screencap for context will help as well.

**Comment by DewLangrial** [comment]
I am experiencing this issue as well. "a later version of windows subsystem for Linux update is already installed. setup will now exit."
Any solutions?

**Comment by xinxilas** [comment]
Me too, cannot activate WSL2

**Comment by laurin1** [comment]
Me too
