### ISSUE TITLE
Problema ao iniciar o ubuntu wsl2

### ISSUE THREAD

**Issue by Lincolnbiancard** [microsoft/WSL#6444]
# Environment

```none
Habilite o recurso Plataforma de Máquina Virtual do Windows e verifique se a virtualização está habilitada no BIOS.     Para obter mais informações, acesse https://aka.ms/wsl2-install                                                         Press any key to continue...
```

# Steps to reproduce

**WSL logs**: 
Habilite o recurso Plataforma de Máquina Virtual do Windows e verifique se a virtualização está habilitada no BIOS.     Para obter mais informações, acesse https://aka.ms/wsl2-install                                                         Press any key to continue...
#  Expected behavior

# Actual behavior

**Comment by Bruno-26** [comment]
Executa no power shell como adm:

dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Reinicia o pc...

Executa esses:

DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V

bcdedit /set hypervisorlaunchtype auto

Reinicia o pc e pronto.

**Comment by stavski** [comment]
Obrigado funcionou corretamente mas tive que executar esses dois comandos antes de tudo e reiniciar o pc.

DISM /Online /Cleanup-image /Scanhealth
DISM /Online /Cleanup-image /Restorehealth

**Comment by k3rnelkill** [comment]
> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.

It worked on win11

**Comment by baconzin** [comment]
> Obrigado funcionou corretamente mas tive que executar esses dois comandos antes de tudo e reiniciar o pc.
> 
> DISM /Online /Cleanup-image /Scanhealth DISM /Online /Cleanup-image /Restorehealth

Aqui funcionou depois que fiz isso também, boa! obrigado!

**Comment by dragao1995** [comment]
Tem como usar o wsl2 sem ligar o Hyper-V?

**Comment by rafaelportomoura** [comment]
[dragao1995](https://github.com/dragao1995) eu uso sem o Hyper-V

**Comment by codigoperfeito** [comment]
> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.

depois de muito tempo procurando como consertar a merda que fiz depois de instalar alguns emuladores de android finalmente tu me salvo parabéns ! solucionado erro "erro habilite o componente opcional "plataforma de maquina virtual" " do WSL

**Comment by gabrielduete** [comment]
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart



> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.

Thanks!! It worked on win11 2023. /o/

**Comment by gabrielleite96** [comment]
> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.



> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.

**Comment by gabrielleite96** [comment]
> Executa no power shell como adm:
> 
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> 
> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Reinicia o pc...
> 
> Executa esses:
> 
> DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
> 
> bcdedit /set hypervisorlaunchtype auto
> 
> Reinicia o pc e pronto.

**Comment by gabrielleite96** [comment]
Cara, me salvou... tive esse problema após mexer em configurações de hyper na maquina para o minikube, valeu!

**Comment by iPrincesaDark** [comment]
Nice, funcionou aqui mesmo utilizando o Windows na versão home, com com o comando "DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V" não funcionando para essa versão do windows. Seguindo os passos ignorando esse funcionou. Happy :)

**Comment by marcossantosscott** [comment]
> Obrigado funcionou corretamente mas tive que executar esses dois comandos antes de tudo e reiniciar o pc.
> 
> DISM /Online /Cleanup-image /Scanhealth DISM /Online /Cleanup-image /Restorehealth

**Comment by Jhonatha1** [comment]
Boa! Problema resolvido! O passo a passo é:

**Esses primeiro:**

1. DISM /Online /Cleanup-image /Scanhealth
2. DISM /Online /Cleanup-image /Restorehealth

3. dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
4. dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

**Reinicia o pc e esses:**

1. DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V

2. bcdedit /set hypervisorlaunchtype auto

**Reinicia dnv**
