### ISSUE TITLE
numa_available() return 0 on WSL2

### ISSUE THREAD

**Issue by dimarusyy** [microsoft/WSL#6446]
I'm using Ubuntu-20.04 under WSL2.
Unfortunately, the call to `numa_available()` returns 0 that is not an error meaning NUMA is not supported.
On the other hand, 
> $ numactl --show
> physcpubind: 0 1 2 3 4 5 6 7
> No NUMA support available on this system.
>

**Comment by craigloewen-msft** [comment]
Hi @dimarusyy could you please resubmit this issue with the full template included? A lot of those details (especially things like your Windows build number and logs) will help us understand your problem and help you out!

I'll close this issue out, if you edit the issue above to include this detail I'll reopen it or just open up a new issue. Thank you!

**Comment by dimarusyy** [comment]
Hm, that's rather interesting but after restarting container with Ubuntu-20.04 I can't reproduce the issue.
OS details:
> Windows 20H2 (19042.746)

WSL2:
> Ubuntu 20.04 with updated packages

Simple example (build and run):
```
#include <numa.h>
#include <iostream>

int main()
{
    auto n = numa_available();
    std::cout  << "numa_available=" << n << "\n";

    return 0;
}
```

Let's keep it closed for now. I'll reopen with details if I get it reproducible again.

**Comment by dimarusyy** [comment]
My previous description was incorrect.
I'm not sure it's wsl issue but the steps to reproduce the case :
1. Have wsl2 installed
2. Have docker desktop installed on windows
3. Have docker installed in Ubunut-20.04 on wsl using host Docker server
4. Run numactl --show in wsl 
`$ numactl --show
physcpubind: 0 1 2 3 4 5 6 7
No NUMA support available on this system.`
5. Create docker container via wsl with installed numa librearies
6. Create simple test-case and compile in wsl :
`#include <numa.h>
#include <iostream>

int main()
{
    auto n = numa_available();
    std::cout  << "numa_available=" << n << "\n";

    return 0;
}`
7. Run `./test_numa` in wsl :
`$ ./test_numa
numa_available=-1`
8. Run docker image 
`$ docker run -it -v `pwd`/:/app --entrypoint /app/test_numa 53fda3c718da
numa_available=0`

**Comment by dimarusyy** [comment]
@craigloewen-msft, please take a look to the description to clarify if this issue  should be reopened and filed to docker.

**Comment by craigloewen-msft** [comment]
Could you please file this on Docker? Given that numa is available and working inside of WSL in general (i.e: The platform pieces all seem to be working correctly) I believe that Docker would be in the best position here to resolve this error.

**Comment by dimarusyy** [comment]
sure, thanks for update!

**Comment by scotgopal** [comment]
Hi @dimarusyy , if you had posted the issue to Docker, could you send a link to the issue here?

**Comment by lorenzeszz** [comment]
I am on Win 11 22H2 with WSL2 and Ubuntu 22.04.2 LTS and get:

numactl --show
physcpubind: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
No NUMA support available on this system.

**Comment by W1M0R** [comment]
Linking issue #10277
