### ISSUE TITLE
Cannot install InterSystems IRIS in my Ubuntu 20.04 distro on WSL2. It says systemd not as init system PID1

### ISSUE THREAD

**Issue by jtsalten** [microsoft/WSL#6447]
I'm trying to install an instance of InterSystems IRIS DataPlatform in my Ubuntu distro. I managed to install a previous version in September with Windows 10 20H1 (May release).... Now, when I try to install it, it says:

=================
Confirm InterSystems IRIS installation <Yes>?

Starting installation
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Couldn't install all projects.

==================

But I'm sure this was possible before... my prove is that I still have and IRIS version installed on my Ubuntu distro... but that same version, if I try to install another instance, I get that message and I can't.

Any idea what has changed? Is this a knwon bug or is there any workaround? Perhaps I have to configure something in WSL but I don't know what.

**Comment by sirredbeard** [comment]
WSL init runs as PID 1, running systemd as PID 1 is possible if you manually start it in it's own namespace and then run your application in that namespace. There are some handy scripts to get you started: https://github.com/diddledan/ubuntu-wsl2-systemd-script/tree/master You can also join us in the Telegram channel if you have any questions: https://t.me/joinchat/SK14TGZ7O2bYtRyo

**Comment by jtsalten** [comment]
That worked!!!
I recognize I don't fully understand where is the magic behind it... doing it in this way have any drawbacks?
Many thanks!

**Comment by therealkenc** [comment]
There is a landing zone for `systemd` magic at /dupe #994.
