### ISSUE TITLE
Change Login Banner

### ISSUE THREAD

**Issue by Databyte8** [microsoft/WSL#6449]
Hello. I have an Kali WSL on Windows and everytime I launch it, It displays:

┏━(Message from Kali developers)
┃
┃ We have kept /usr/bin/python pointing to Python 2 for backwards
┃ compatibility. Learn how to change this and avoid this message:
┃ ⇒ https://www.kali.org/docs/general-use/python3-transition/
┃
┗━(Run “touch ~/.hushlogin” to hide this message)

But I want to change it (Not remove it). I searched everywhere but I found nothing. Please help

**Comment by Biswa96** [comment]
Try to edit `/etc/motd` or `/etc/update-motd.d/*` files.

**Comment by Mushroomician** [comment]
In case you did'nt find the correct file, you could do:
`grep -r "to hide this message" /etc/`
This will show you the correct filename you'd like to change the content off.

**Comment by Databyte8** [comment]
> Try to edit `/etc/motd` or `/etc/update-motd.d/*` files.

I looked into the /etc/motd but its empty. And in update-motd.d, there are 3 Files called 10-uname, 85, 92-unattended-upgrades.

The 10-uname contains:

```
#!/bin/sh
uname -snrvm
```

And the 85-fwupd contains:

```
#!/bin/sh

if [ -f /run/motd.d/fwupd/85-fwupd ]; then
        cat /run/motd.d/fwupd/85-fwupd
fi
```

And the Folder "/run/motd.d" doesn't exists
```
#!/bin/sh

if [ -x /usr/share/unattended-upgrades/update-motd-unattended-upgrades ]; then
    exec /usr/share/unattended-upgrades/update-motd-unattended-upgrades
fi
And the 92-unattended-upgrades contains:

```
