### ISSUE TITLE
`wsl env` is different to `wsl` followed by `env`

### ISSUE THREAD

**Issue by Clonkex** [microsoft/WSL#6454]
I use `~/.bashrc` inside WSL to set the environment variable `LANG=en_US.UTF-8`. That works fine from within WSL, I can do `echo $LANG` and it gives me:

```en_US.UTF-8```

However if I execute the command from outside WSL with `wsl echo $LANG` I see:

```C.UTF-8```

Why doesn't `wsl echo $LANG` give me the same results as `wsl` followed by `echo $LANG`?

**Comment by 0xbadfca11** [comment]
#6339 #5801 etc etc

Use `update-locale` instead (for only $LANG).

**Comment by Clonkex** [comment]
@0xbadfca11 Since my ultimate goal was to be able to do this:

```wsl ssh 192.168.x.x "perl -e exit"```

...without Perl complaining, I discovered that I could solve my problem by simply adding `LANG=en_US.UTF-8` to `~./bashrc` on the remote machine.

This doesn't solve this weirdness in WSL, but... well I guess your linked issues show that it's just the way WSL works. It sorta makes sense, I suppose, if you think of WSL as being bash. IMO the way bash loads startup scripts is pretty [disgustingly overcomplicated](https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html), but I assume that's a result of decades of backwards compatibility.
