### ISSUE TITLE
Mounting a partition fails due to "the" file being used by another process

### ISSUE THREAD

**Issue by dagguh** [microsoft/WSL#6456]
# Environment

```none
Windows build number: 10.0.21292.1010
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce
1. create a raw partition using diskpart
2. format it to ext4 with 3rd party tools
3. open admin PowerShell
4. `wsl --mount \\.\PHYSICALDRIVE0 --partition 4`

**WSL logs**: I recorded repro in a  [Feedback Hub case](https://aka.ms/AA1py9w). Hopefully it recorded the logs?

#  Expected behavior

The partition is mounted and available within WSL (e.g. Ubuntu can read/write there).

# Actual behavior
The `wsl --mount` call fails with an errors:
> The process cannot access the file because it is being used by another process.

**Comment by 0xbadfca11** [comment]
If PHYSICALDRIVE0 is a disk with Windows installed, that is the current limitation.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations

**Comment by dagguh** [comment]
Ah, now the limitation clear 👍 
There's a difference between attach and mount. I didn't understand it, so I was confused by the limitation, because it seemed contradicting at first:
> To mount a specific partition ...

> it's not possible to attach only a partition

Now all is clear as day. Thanks!

**Comment by tadam98** [comment]
Please fix this. I have a usb disk that has windows and ubuntu side by side. Thus, when the disk is connected windows identifies the windows partition and assigns a drive letter. From now the disk is busy. 

Trying to mount the ext4 partition fails. Although this partition is not being used.

**Comment by herrwinfried** [comment]
Do you have any solution suggestions?

**Comment by herrwinfried** [comment]
Do you have any solution suggestions? @0xbadfca11

**Comment by sorin-c** [comment]
I've encountered this when trying to mount an ext4 partition using wsl --mount:
`PS C:\Windows\system32> wsl --mount \\.\PHYSICALDRIVE9 --partition 2
The process cannot access the file because it is being used by another process.`

@dagguh - are there are workarounds for this?
