### ISSUE TITLE
How to access Linux partitions in WSL2

### ISSUE THREAD

**Issue by sujay1844** [microsoft/WSL#6458]
This looks like a google search, I know. But I didn't find an answer.

**Describe the solution you'd like**
I have Windows and Arch installed via dualbooting. How do I access my ext4 partitions from WSL2.
I read some articles about this but they all talk about ext4 drives, not partitions. I thought this feature is not there so I made it a feature request.

**Describe alternatives you've considered**
Alternatives?? For now I'm using [DiskInternals Linux reader.](https://www.diskinternals.com/linux-reader/) But this thing is cumbersome and inconvenient.

**Comment by ROBYER1** [comment]
I believe this is for insiders builds only right now https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/

**Comment by sujay1844** [comment]
Well I should've read the documentation correctly. It's given right there in plain text: 😭😭😭
https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations

**Comment by ROBYER1** [comment]
> This looks like a google search, I know. But I didn't find an answer.
> 
> **Describe the solution you'd like**
> I have Windows and Arch installed via dualbooting. How do I access my ext4 partitions from WSL2.
> I read some articles about this but they all talk about ext4 drives, not partitions. I thought this feature is not there so I made it a feature request.
> 
> **Describe alternatives you've considered**
> Alternatives?? For now I'm using [DiskInternals Linux reader.](https://www.diskinternals.com/linux-reader/) But this thing is cumbersome and inconvenient.

You can use \\wsl$ in the address bar of file explorer!

From this guide https://www.howtogeek.com/426749/how-to-access-your-linux-wsl-files-in-windows-10/

**Comment by sujay1844** [comment]
@ROBYER1 I think you didn't understand my question. I need to access linux partition in wsl. Not wsl files in windows. But anyways, thanks
