### ISSUE TITLE
Arch Linux please??

### ISSUE THREAD

**Issue by sujay1844** [microsoft/WSL#6459]
### I love Arch Linux. ###

**Describe the solution you'd like**
Can you please bring Arch to WSL2??

**Describe alternatives you've considered**
As an alternative, I'm using Ubuntu for now.
I know about [yuk7/ArchWSL.](https://github.com/yuk7/ArchWSL)
But I wish it to be official and can be downloaded from the Microsoft Store just like the other distros.

**Comment by benhillis** [comment]
The ball is in their court, if they'd like to be an official distro we would be happy to have them.
