### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102, Unable to set SVM on BIOS to on/enable

### ISSUE THREAD

**Issue by JagritiJ** [microsoft/WSL#6463]
# Environment

```none
Windows build number: 
                                                            OS Name	Microsoft Windows 10 Home
                                                            Version	10.0.18363 Build 18363
                                                            Other OS Description 	Not Available
                                                            OS Manufacturer	Microsoft Corporation
                                                            System Name	LAPTOP-53H8DLEO
                                                            System Manufacturer	ASUSTeK COMPUTER INC.
                                                            System Model	TUF Gaming FX505DV_FX505DV
                                                            System Type	x64-based PC
                                                            Processor	AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx, 2300 Mhz, 4 Core(s), 8 Logical Processor(s)
                                                            BIOS Version/Date	American Megatrends Inc. FX505DV.311, 22/09/2020
                                                            BIOS Mode	UEFI


Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] - WSL crashes, so I downloaded Ubuntu from the Windows store
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] WSL2 
```

# Steps to reproduce
1. Installed WSL 2 using the Microsoft Documentation
2. Enabled 'Virtual Machine Platform' , 'Windows Hypervisor Platform', 'Windows Subsystem for Linux'  on Windows Features
3. Enabled SVM on BIOS
4. Save and Exit BIOS
5. Black screen for 15-20 min
6. Reset to Default settings on BIOS
7. Tried the above 3-4 times, didn't work

**WSL logs**:  https://drive.google.com/drive/folders/1INhYyKyLAmhRIRoxDSht7zc5WOsQL7jf?usp=sharing

#  Expected behavior

After enabling SVM on BIOS, laptop should boot and I should be able to run Ubuntu on Windows 10

# Actual behavior

Laptop gives black screen after enabling SVM

**Comment by therealkenc** [comment]
Ref #5921 #5430 #4120.

**Comment by JagritiJ** [comment]
Hey,

I have enabled all the required settings under Windows Features for
virtualization.

The problem in my case is that my laptop doesn't boot after enabling SVM on
BIOS.

Thus I had to disable to it so laptop atleast boots.

Thus I can't use wsl on my laptop. Let me know what else can I do to solve
this.

Regards,
Jagriti

**Comment by Manguil** [comment]
I have the same problem as you but I can run version 1 of wsl
