### ISSUE TITLE
Is it possible for Linux app from WSL1.0 to access DirectX resources?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/WSL#6467]
The application in WSL1.0 is a standard ELF64 Linux program, so whether there are DX SDK (headers/libs/drivers/..) for them to invoke to make them able to utilize DX resources?

**Comment by therealkenc** [comment]
Direct X on WSL 1? No.

**Comment by ghostplant** [comment]
OK, do you mean WSL 2 is possible?

**Comment by therealkenc** [comment]
There is a blog post [here](https://devblogs.microsoft.com/directx/directx-heart-linux/). See also issue #938, which is in the works. The short answer to whether there are DX SDK (libraries, headers) for WSL is also no, as of this writing anyway. #938 is mostly about OpenGL mapped onto DX12. But we can recategorize your ask back to 'feature' on the "anything possible" hypo of a DX SDK for Linux.

**Comment by ghostplant** [comment]
Got it, and thank you even though WSL 2 is not my preference.
