### ISSUE TITLE
I am also using Ethernet IP for Windows 10 on WSL now. Virtual Ethernet itself is not installed at all, and is being used normally, such as the Internet.

### ISSUE THREAD

**Issue by tenbirds** [microsoft/WSL#6468]
I am currently using Windows 10's Ethernet fixed IP in WSL. 
Virtual Ethernet itself is not installed at all and is in normal use, such as the Internet.
Wsl shares Windows' Ethernet IP.

I don't know why it's like this.

![image](https://user-images.githubusercontent.com/3597361/105814339-9a47fc80-5ff4-11eb-919b-d17643a9e76f.png)

**Comment by therealkenc** [comment]
What is the output of:
```
$ cat /proc/version
$ cmd.exe /c ver
```

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by tenbirds** [comment]
wsl's ip and Windows' ip are shared, and vEthernet is not installed. I can't figure out what this phenomenon is like.

**$ cat /proc/version**
==> Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

**$  cmd.exe /c ver**
Microsoft Windows [Version 10.0.19042.746]

# window ip address
ethernet Adapter:
    IPv6 주소 . . . . : fe80::f8c3:94e5:6f63:6cf1%14
   IPv4 주소 . . . . . . . . . : 10.0.122.58
   sub net . . . . . . . : 255.255.0.0
   gateway . . . . . . : 10.0.0.1

# WSL ip address
root@DESKTOP-U0R0CB2:/# ip addr
14: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether 8c:b0:e9:22:fa:f0
    inet 10.0.122.58/16 brd 10.0.255.255 scope global dynamic
       valid_lft forever preferred_lft forever
    inet6 fe80::f8c3:94e5:6f63:6cf1/64 scope link dynamic
       valid_lft forever preferred_lft forever

**Comment by therealkenc** [comment]
>  Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) 

You are on WSL 1. There is no vEthernet adapter.

**Comment by tenbirds** [comment]
Thank you so much for your reply. 
But I was using wsl2.
and I installed everything again and it's working fine. 

============================
> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
============================
