### ISSUE TITLE
WSL2 - cpu usage in the task manager is reported as half of the WSL one.

### ISSUE THREAD

**Issue by bartoszek** [microsoft/WSL#6470]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.746]
Your Distribution version: `Ubuntu:20.04,Arch:current,Ubuntu:18.04`
Whether the issue is on WSL 2 and/or WSL 1: `both WSL{1,2}`
Workstation: {Lenovo:W530,cpu:i7-3720QM CPU @ 2.60GHz,nproc:8}
```

# Steps to reproduce

* Got to `wsl{1,2}` start multithreaded job like `ffmpeg` transcode.
* Check the CPU load reported by Linux host `{h}top`
* Check the CPU load reported by the `windows taskmanager`
* Check the CPU load reported by `HWInfo`
* Values shown in `windows taskmanager` is a half of what it actually is.

![image](https://user-images.githubusercontent.com/1213348/105842762-fd2a9b00-5fd6-11eb-9b91-85fc7550df92.png)

**Comment by benhillis** [comment]
@bartoszek - you claim this is for both WSL1 and 2, but I have a feeling this is only for WSL2 and thus expected.  Can you confirm?
