### ISSUE TITLE
Cannot ping WSL2 from its Windows host

### ISSUE THREAD

**Issue by oregonduckman** [microsoft/WSL#6472]
# Environment

```none
Microsoft Windows [Version 10.0.18363.1316]
Release:        20.04
Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

ping 172.17.112.15

Pinging 172.17.112.15 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.17.112.15:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**WSL logs**: 

#  Expected behavior

successful ping
# Actual behavior

ping returns Request timed out.

**Comment by therealkenc** [comment]
Please screencap the following to get a handle on the state of `eth0`:
```
$ cat /proc/version
$ ip addr show eth0
$ ping.exe <ip address of eth0>
```

Looks something like (if it were working):

![image](https://user-images.githubusercontent.com/7049700/105916519-e0e22a80-5fe5-11eb-90f9-ba047f175725.png)

Are you able to access the outside world (f.e. `/bin/ping 8.8.8.8`) from within WSL 2?

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. The run would be starting the distro (run wsl.exe) and do the sequence above. Also please identify any third-party networking software that has been installed on Windows.

Disabling Windows firewall (temporarily) is sometimes worth trying on a lark.

**Comment by oregonduckman** [comment]
I did a re-install of Windows and WSL and it seems that WSL now gets a DHCP lease since its IP address is from my subnet and I can now ping the WSL2 instance. However now unable to ssh into WSL...

**Comment by fkadeal** [comment]
Request timed out.
Request timed out.
