### ISSUE TITLE
`wsl --install` stuck at `No action was taken as a system reboot is required.`

### ISSUE THREAD

**Issue by govizlora** [microsoft/WSL#6474]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21296.1010]
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: N/A
```

# Steps to reproduce
In powershell, run `wsl --install -d Ubuntu-20.04`

I see
```
Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: Ubuntu 20.04 LTS
The requested operation is successful. Changes will not be effective until the system is rebooted.
```

Then I reboot, and I see a welcome screen that prompts me to try office 365.

Then nothing happened. If I run `wsl --install -d Ubuntu-20.04` again, I see
```
No action was taken as a system reboot is required.
```

It persists after more reboot trys

**WSL logs**: 
https://aka.ms/AAaxwf9
#  Expected behavior

WSL2 with Ubuntu should be installed

# Actual behavior

WSL2 with Ubuntu is not installed

**Comment by therealkenc** [comment]
Thanks for the report and the logs. After doing the `--install` and reboot, is "Windows Hypervisor Platform" and "Windows Subsystem for Linux" checked in Windows Features? Ideally it should look something like below, though for you it probably won't. You can try checking them manually on a lark, and do another reboot round. That will probably result in the same "nothing happened" but it is worth a try.

Also is this the first time you've tried enabling WSL on this machine (have you installed it before)? 

![image](https://user-images.githubusercontent.com/7049700/106219466-4113d080-618e-11eb-8464-f36d828d9937.png)

**Comment by govizlora** [comment]
@therealkenc Thanks for the suggestions!

I tried it again today, and it succeeded! After I see `The requested operation is successful. Changes will not be effective until the system is rebooted.`, I reboot my PC, and when it trying to shut down, it says `Program Manager` is blocking the shutdown. Previously, I always click `force restart` since I thought it was unrelated. This time, I clicked `wait for the program`, and then it goes to "Getting Windows ready" or like. After the reboot, I see ubuntu being started automatically.

I think the key difference is that I have to `wait for the program` instead of force quit. I hope this helps, and this ticket can be closed, thank you!

**Comment by daniel-brat-eskon** [comment]
I am having the same problem, however, I don't see the system waiting for any apps when rebooting as the original poster described. After reboot, I can see the 'Virtual Machine Platform', 'Windows Hypervisor Platform' and 'Windows Subsystem for Linux' enabled in Windows features.
System: Windows 10 Pro build 19043.1237

**Comment by RobertoMaurizzi** [comment]
I was getting the same but all 2 features were shown as installed.
I uninstalled the XPS printer feature, it asked me for a reboot and after that WSL was ok with installing Ubuntu-20.04...

**Comment by manognyaa** [comment]
> @therealkenc Thanks for the suggestions! Every time after the reboot, I can see `Virtual Machine Platform` and `Windows Subsystem for Linux` being added to the features.
> 
> I tried it again today, and it succeeded! After I see `The requested operation is successful. Changes will not be effective until the system is rebooted.`, I reboot my PC, and when it tries to shut down, it says `Program Manager` is blocking the shutdown. Previously, I always click "force restart" since I thought it was unrelated. This time, I clicked "wait for the program", and then it says "Getting Windows ready" before the shutdown. After the reboot, I see Ubuntu being started automatically.
> 
> I think the key difference is that I have to "wait for the program" instead of force quit. I hope this helps, and this ticket can be closed, thank you!

thanks a ton !!

**Comment by CarloCattano** [comment]
Thanks for the issue , I had the same problem and now is solved !

**Comment by james-latiste** [comment]
There is no Hyper-V option in Windows Home edition. You need to active virtualization on BIOS setup when booting your Windows in that case.

**Comment by espoirndayishimiye4** [comment]
for me "wsl --install -d Ubuntu" command solved the issue

**Comment by Rprobot2** [comment]
> for me "wsl --install -d Ubuntu" command solved the issue

This is what worked for me, many thanks. I also had to enable virtualisation in my BIOS: 
[https://www.asus.com/support/FAQ/1038245](https://www.asus.com/support/FAQ/1038245)

**Comment by esayyasahmed1012** [comment]
restart your computer and it will start installation again and it will work fine
