### ISSUE TITLE
Bug: wsl cannot run.系统找不到指定的文件

### ISSUE THREAD

**Issue by laizewei** [microsoft/WSL#6475]
win10 19042.746.
A few days ago I run netsh winsock restart in cmd.
Now I run ubuntu2004.exe.
prompt:系统找不到指定的文件.Press any key to continue...

Then I run DISM.exe /Online /Cleanup-image /Restorehealth   in cmd.
run sfc /scannow in cmd.
But still cannot  run ubuntu2004.exe.

**Comment by crramirez** [comment]
Hello,

I didn't understand anything about the problem you are facing. I don't see the relation of the commands and ubuntu2004.

Could you please tell us in English this part? 系统找不到指定的文件

Regards,
Carlos

**Comment by laizewei** [comment]
netsh winsock restart    The specified file could not be found. 
I restored win10 to fix this problem.

**Comment by crramirez** [comment]
This error usually happens when you install Ubuntu on another drive than C. But I see this is not the case. Did the Windows restore fixed the problem?

**Comment by laizewei** [comment]
I install Ubuntu on G(mobile hard disk drive).

**Comment by laizewei** [comment]
Maybe the registry is corrupt.
Windows Recovery fixes this problem.

**Comment by therealkenc** [comment]
There are similar-ish issues on the books #6341 #5906 #4959 (others). If you can catch it failing again please open a new issue and collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).
