### ISSUE TITLE
WSL2 Network is unreachable

### ISSUE THREAD

**Issue by samuelguesnier** [microsoft/WSL#6480]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.746]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Run ping command.

samsam@WX-OR6223205:~$ ping 8.8.8.8
ping: connect: Network is unreachable

**WSL logs**: 

#  Expected behavior

On WSL1, internet connectivy works perfectly fine.
I except ping command to execute and try to send data, and eth0 to have ip for example on WSL1:

sam@WX-OR6223205:/mnt/c/Users/XNWW3722$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---

7: eth0: <> mtu 1500 group default qlen 1
    link/ether f8:0d:ac:c9:57:47
    inet 169.254.197.80/16 brd 169.254.255.255 scope global dynamic
       valid_lft forever preferred_lft forever
    inet6 fe80::6d9f:f854:7d27:c550/64 scope link dynamic
       valid_lft forever preferred_lft forever

# Actual behavior

samsam@WX-OR6223205:~$ ping 8.8.8.8
ping: connect: Network is unreachable

samsam@WX-OR6223205:~$ ip addr
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 1a:a6:24:ab:54:9f brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether a2:db:97:fd:f2:42 brd ff:ff:ff:ff:ff:ff
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
5: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:15:5d:88:79:25 brd ff:ff:ff:ff:ff:ff

**Comment by therealkenc** [comment]
```
5: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
link/ether 00:15:5d:88:79:25 brd ff:ff:ff:ff:ff:ff
```

There is no IP address assigned in your WSL2 instance; this is oftentimes #5437. If [turning off swap](https://github.com/microsoft/WSL/issues/5437#issuecomment-647161596) doesn't help, please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by samuelguesnier** [comment]
I tried to turn off the swaps but didn't seems to work. I have a proxy on my computer and also a cisco Anyconnect vpn that I must use to connect to my company's network. I tried to turn off proxy + vpn but nothing changes whereas on WSL1 it works.

I'm gonna try to send you the logs. Thanks for your help

**Comment by samuelguesnier** [comment]
My bad, I tried to again to deactivate swap, and now it works. Thanks so much !
