### ISSUE TITLE
which command can be use to replace 'systemctl deamon-reload'

### ISSUE THREAD

**Issue by jevonsnotes** [microsoft/WSL#6485]
# Environment
```
ubuntu Release:        20.04
```

i want to set the docker proxy and then refresh it by using 'systemctl deamon-reload',but got 'Unknown operation deamon-reload'.try 'chkconfig docker --add' then got 'chkconfig: command not found'. i had search in many ways  but isn't working.

**Comment by therealkenc** [comment]
`systemctl` is #1579. There is a discussion thread about running docker inside WSL2 at [#4872](https://github.com/microsoft/WSL/discussions/4872). The OP of that thread was about Debian, but the discussion applies just as well to any distro. Or feel free to open a new [discussion](https://github.com/microsoft/WSL/discussions) for your use case.
