### ISSUE TITLE
Command "wsl --set-default-version 2" doesn't change version of WSL

### ISSUE THREAD

**Issue by GeadSolutions** [microsoft/WSL#6486]
# Environment
Microsoft Windows [10.0.19042.746]
Windows 10 Pro, 20H2
Experience: Feature Experience Pack 120.2212.551.0

# Copy of the terminal output
On my Windows Terminal I type:
`wsl -l`
_Distribuições do Subsistema do Windows para Linux:
Ubuntu (Padrão)
Ubuntu-20.04_

Then, after run `wsl --set-default-version 2` I get:
_Para obter informações sobre as principais diferenças em relação ao WSL 2, visite https://aka.ms/wsl2_

What translated from pt-br mean "To get info about main differences relation to WSL 2, visit https://aka.ms/wsl2". But, unfortunelly, the default version keep on version_number 1. 

What possibly be wrong?

**Comment by therealkenc** [comment]
> But, unfortunelly, the default version keep on version_number 1.

Your default version is now 2. You can change the version of an already installed distro with [`--set-version`](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2) not `--set-default-version`.

**Comment by GeadSolutions** [comment]
OK, but when I run "wsl -l" it shows me that version "Ubuntu" is default (see the word "Padrão" on command output below).

```
Ubuntu (Padrão)
Ubuntu-20.04
```
Also, on this MS tutorial [here](https://docs.microsoft.com/pt-br/windows/wsl/install-win10) they said on Step 5 to use `wsl --set-default-version 2` to DEFINE the default version.

So it got a little complicated.

How can I confirm what version my system is running now?
