### ISSUE TITLE
WSL won't start anymore: error 0x80070715

### ISSUE THREAD

**Issue by Martin-Poellot** [microsoft/WSL#6494]
# Environment

```
Windows build number: Build 20221 rs_prerelease.200919-1857
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I simply start up the wsl by using any of the calls: wsl; bash; Ubuntu. (edit: I should add, that the "Installing, this may take a few minutes..." only appeared after I uninstall my original WSL2 distribution.)
![WSL-Error0x80070715](https://user-images.githubusercontent.com/24700309/106495415-ef37b700-64bb-11eb-90ce-29d0a3eec50a.png)

**WSL logs**: Unable to produce any readable WSL logs.
[wsl.txt](https://github.com/microsoft/WSL/files/5905595/wsl.txt) <- Original .etl-file

#  Expected behavior

I expect WSL2 to start up, letting me hack away my code.

# Actual behavior

Appart from the error nothing happens. Also docker crashes since the file system seems to be corrupted.

# Further Description

I am doing a lot of docker containers with python and GPU support, which is why i am using WSL2 and Docker. Everything was working fine, until i restarted my laptop. Since then, when I started the WSL (through task bar icon), it says:

```
WslRegisterDistribution failed with error: 0x80070715
Error: 0x80070715 Der angegebene Ressourcentyp wurde nicht in der Image-Datei gefunden.
Press any key to continue...
```
When pressing any key, of course it exits. I did not change my Ubuntu 20.04 image or anything.

I tried to reset and repair the image, but had no luck. The given error code did not return anything useful (in my eyes).

I tried to download another image, but neither Ubunut 16/18.04 or debian were working. They all threw the same error. Yes, even the Debian one.

System Specs:

-     Windows 10 Pro Insider Preview (64 bit), Version 2004
-     Build 20221 rs_prerelease.200919-1857
-     Intel Core i7-9750H
-     Hyper-V Activated
-     WSL Kernel Version: 5.4.72

**Comment by Rathil** [comment]
I also have a similar error.
When I try to run an old distribution I get this error:
```bash
The specified resource type cannot be found in the image file.                                                                                                  
                                                                                                                                                                
Press Enter or Esc to exit...
```

When trying to install a new distribution it says this:
```bash
Temporary directory: C:\Users\rathil\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/alpine-minirootfs-3.12.1-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\rathil\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: 5c81856823d1ee629af5245d4023a31f0144696c00edc9091db43c404e1cd02b

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070715
WslRegisterDistribution failed
Error: 0x80070715 The specified resource type cannot be found in the image file.

Press any key to continue...
```

**Comment by macarr** [comment]
Having the same issue, tried reinstalling Ubuntu from the windows store after getting "The specified resource type cannot be found in the image file." and now on start I get 
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070715
Error: 0x80070715 The specified resource type cannot be found in the image file.

Press any key to continue...
```

**Comment by Rathil** [comment]
Could it be because the certificate has expired?
![image](https://user-images.githubusercontent.com/2794944/106512991-02a64a80-64db-11eb-9529-e9813780686b.png)

**Comment by ligerzero459** [comment]
Same error. Existing Ubuntu 20 installation fails to start with
```
The specified resource type cannot be found in the image file.                                                                                                  
                                                                                                                                                                
Press Enter or Esc to exit...
```

Attempted to install a new Debian image and got
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070715
Error: 0x80070715 The specified resource type cannot be found in the image file.

Press any key to continue...
```

**Comment by stephankistmann** [comment]
Same issue here, started after the last windows update, have tried everthing possible, nothing works.

**Comment by gmackie** [comment]
Same issue. pretty sure I accidentally wiped out my old distro while trying to get things working :( Now I can't use WSL at all

**Comment by Darival** [comment]
![Capture](https://user-images.githubusercontent.com/10416020/106549352-65491780-64d6-11eb-88d2-a3e5dbda34ed.JPG)
![Capture](https://user-images.githubusercontent.com/10416020/106549543-d4267080-64d6-11eb-9366-1c290c081d45.JPG)

**Comment by ligerzero459** [comment]
I managed to find a solution. I installed Insider Preview 10.0.21301.1010 (rs_prerelease) and my ability access my original Ubuntu 20 instance and the newly installed image returned.

If you're not on that version, I'd recommend updating

**Comment by epieddy** [comment]
Hello everyone,

I had the same problem just minutes ago and I found that the Windows 20H2 update was pending. I was still on Windows 2004 / 20H1 when the bug manifested itself.

After launching the 20H2 update and restarting my PC, everything was back to normal.

Hope it helps.

++

**Comment by Martin-Poellot** [comment]
> I managed to find a solution. I installed Insider Preview 10.0.21301.1010 (rs_prerelease) and my ability access my original Ubuntu 20 instance and the newly installed image returned.
> 
> If you're not on that version, I'd recommend updating

I guess this answer requires me to change from the Windows Insider Beta-Channel to the Dev Channel? I specifically switched to the Beta-Channel as I had problems earlier concerning stability.

**Comment by stephankistmann** [comment]
> I managed to find a solution. I installed Insider Preview 10.0.21301.1010 (rs_prerelease) and my ability access my original Ubuntu 20 instance and the newly installed image returned.
> 
> If you're not on that version, I'd recommend updating

This worked for me too!

**Comment by ItzLevvie** [comment]
> I specifically switched to the Beta-Channel as I had problems earlier concerning stability.

Dev Channel builds are permanent prerelease builds, and you will have to clean install Windows 10 if you want to run a stable build of Windows.
