### ISSUE TITLE
WSL Ubuntu 20.04 LTS Claiming Invalid Data and Not Allowing to Run Commands

### ISSUE THREAD

**Issue by ottonieljimenez** [microsoft/WSL#6509]
Hello all, 

I currently use WSL with Ubuntu 20.04 LTS to use Tensorflow with an NVIDIA GPU (from my laptop). This mainly allows me to run commands to both activate my Tensorflow environment and open a Jupyter notebook on a separate browser to carry out Python coding that uses an OpenAI Gym environment. Today, however, I encountered the following issue: when I tried opening the Ubuntu 20.04 LTS command shell, the output "The data is invalid. Press any key to continue" showed up (see screenshot attached). Hence, I am not able to run any commands at all and what concerns me the most is that my files in my Tensorflow environment (which are VERY important) be somehow affected by this. I have tried updating the Windows Insider Program since I thought this might have been related to the issue, but up to this point, the updates are still being downloaded (after approximately five hours) and I can't tell for sure that this might be the right solution. Hence, I wanted to ask you if you could please help me solve this issue. It is extremely important and necessary for me to find a solution to this problem and your help would be truly appreciated. Thank you in advance!
![Ubuntu_Startup_Issue](https://user-images.githubusercontent.com/71956502/106528747-dffe3c80-64ae-11eb-9f30-ef9bed0d6758.PNG)

**Comment by randaz81** [comment]
I have the same issue from yesterday. Windows 10, version 2004, build 20241.1005.
I think that the error comes from some windows update. What should I do to recover my data? 
Should I update my windows insider build?

**Comment by nagromnortara** [comment]
I'm in Insider build Version 10.0.20251 and having the same issue still, but now I'm also getting greenscreens of deaths frequently. So I can't recommend that direction.

**Comment by 4b71nmdx** [comment]
The only fix I've found is to change the system date. 

The expired Windows Insider Build is the cause of this. I haven't bothered to figure out the expiry method. I also had the green screen issues.
 Best of luck.

**Comment by ottonieljimenez** [comment]
@4b71nmdx Thank you for the input. Were you able to actually write commands again on WSL 2 after changing the system date? Moreover, how exactly did you proceed to change the system date itself? Thanks!

**Comment by alexanderluce** [comment]
I have the same issue, I need to recover the files lost in WSL. I noticed that when I try to access disk management, Windows says "This app has been blocked for your protection". I would update my build but I am worried that will cause permanent loss of my files. Has anyone tried upgrading?

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. The best sequence to capture is probably starting your distro from the commandline. `wsl.exe` or `wsl.exe -d <distro name>`. Three likes on the OP in just a few days so the problem might be fleeting. Also, does the problem manifest on 21301 (or better)? Green screen or no, any potential fix that addresses the issue is going to come by way of a Windows Update, by definition.

**Comment by etscott** [comment]
I encountered this issue this morning. I was still on build 20262 on the Dev channel, which I discovered was listed as expiring on 1/31. I had been putting off updating to make sure I finished a GPU-enabled task in case I encountered any issues with a newer build.

An update to 21301, and all is well again. Seems to just be a Windows version expiry issue.

**Comment by ottonieljimenez** [comment]
The Feedback Hub link corresponding to this issue is the following: https://aka.ms/AAb2wny

**Comment by ottonieljimenez** [comment]
The Feedback Hub link corresponding to this issue is the following: https://aka.ms/AAb2wny

**Comment by Umar-Farooq-Shafi** [comment]
I got same issue in
Edition	           Windows 10 Pro
Version	           Dev
Installed on	   ‎6/‎1/‎2021
OS build	           21390.2025
Experience	  Windows 10 Feature Experience Pack 321.13302.10.3
Any idea how to fix this or when next build is coming?

**Comment by Biswa96** [comment]
According to https://blogs.windows.com/

> FINAL Build Expiration Reminder: We have updated the build expiration for Dev Channel builds to be 9/15/2022. Previous Dev Channel builds from the RS_PRERELEASE branch will expire on 10/31/2021. To avoid hitting this expiration, please be sure to update to the latest Dev Channel build today.

**Comment by Biswa96** [comment]
Then Windows 10 stable build will be the only option for you. BTW, the "incompatibility" is not so incompatible 😉

**Comment by petersmagnusson** [comment]
Like @Nickesh says ... perhaps time for just native Linux.  I understand the need to have expirations etc, but the "hard lock" effect on a system is simply too fragile to accept as a professional user.  I do have support licenses etc etc so I can switch to  11.  But if I really needed this system right now, and couldn't wait for update?  Or if I wanted to go into WSL environment and before the upgrade make sure that all my git repos and other work-in-progress are all backed up/ synced?  Etc.  Just one more indicator of our dependence on fewer and fewer platform providers that ultimately don't really care that much.

**Comment by tilda** [comment]
yep, just encountered this on windows 10 dev (21364). this is like the worst experience i've had with windows period, literally not allowing you to use the software beyond a certain date... what a pain. i'd certainly be on pure linux by now if i didn't have software that requires me to still have windows installed (and if it was easier to move) >_>

**Comment by rideorwalk** [comment]
> The only fix I've found is to change the system date.
> 
> The expired Windows Insider Build is the cause of this. I haven't bothered to figure out the expiry method. I also had the green screen issues. Best of luck.

Thank you for this! I spent the last 6 hours trying to figure out why I couldn't load wsl anymore, tried so many different fixes. To think that simply changing the date would get me back access to my data 😆 

I honestly do not understand how Microsoft thought it would be acceptable to lock you out of your data because of an expired version.

**Comment by chull434** [comment]
Same issue here, this is so stupid that you can't just leave the dev channel. 

In other news mother board did have a TPM it was just disabled in BIOS, windows 11 health check now passes and off we go

**Comment by maulberto3** [comment]
Hi, this WIP has been so unpleasant. First, even if I changed my Beta/Dev/Release option, Windows itself changed to whatever option it may felt good. Strange. Then, it seems my CPU is not allowed for Windows 11, therefore, I got the 10/31/2021 expiry message, locking my WSL along the way. Now, each time I try to use it, it says invalid data. Also, the Docker Desktop can't start up, because of the same thing. So pretty much I just got locked in a dead end, WTF. This is so frustrating. Microsoft, I hope you are hearing, fix this.

**Comment by neojp** [comment]
Changing the date to October let me in to my WSL. This is really dumb. At the very least they should have added a message about this somewhere. I had no idea this would happen if I didn't update to Windows 11.

**Comment by xxzhan321** [comment]
1 ❯ wsl
   The data is invalid.
2  hyper-v virtul machine is not start up :message:Start-VM: 'win11' failed to start.
Microsoft Virtual BIOS (Instance ID AC6B8DC1-3257-4A70-B1B2-A9C9215659AD): Error 'The data is invalid.'.
'win11' failed to start. (Virtual machine ID 23771B2B-5279-4F0A-A0CD-7E3C415F34AE)
'win11' Microsoft Virtual BIOS: Failed to start reserving resources with Error 'The data is invalid.' (0x8007000D). (Virtual machine ID 23771B2B-5279-4F0A-A0CD-7E3C415F34AE)..  

changing the date to October. wsl hyper-v is ok.

**Comment by Nickesh** [comment]
You only need to **change the date** in your system for the moment of **WSL or Docker Desktop startup**. After they start, you can normally **re-set your system date back** to the automatic setting and everything works fine.

In fact you really should do it for the reasons mentions by @neojp.

**Comment by AwokeKnowing** [comment]
This just happened to me and I lost all day trying to figure it out.  Our clients schedule is now delayed and we did not meet a very urgent deadline  I was just about to clean format my system which would cause me to loose a full day of software dev work.  This is an absolutely untenable situation, over absurd TPM module.  Microsoft is out of control.  This experience will likely result in leaving the dev program and migrating fully to linux for all work.

Unfathomably wrong move microsoft.  you need to extend the non-tpm build for at least a year. you cannot just instantly trash millions of developer machines.

**Comment by 27Bslash6** [comment]
Yeah, this is horrific DevEx, Microsoft.  Back to Mac for a more cohesive developer / GUI experience.  Or maybe it's time for PopOS...

**Comment by adelina-t** [comment]
This is horrible. Just ran into this myself. Well, I guess it's back to linux for my desktop. As a dev, if I can't have WSL2, Windows is basically pointless to me.

**Comment by chiqui3d** [comment]
Same problem https://github.com/microsoft/WSL/issues/7644, this is called murder in my village.

**Comment by Biswa96** [comment]
As suggested previously, you can change the system date before 31/10/2021 to run WSL2 and get your data asap. But remember web browser will not work with that date.

Then switch back to other stable Windows build or install any GNU/Linux distribution.

**Comment by adelina-t** [comment]
> As suggested previously, you can change the system date before 31/10/2021 to run WSL2 and get your data asap. But remember web browser will not work with that date.
> 
> Then switch back to other stable Windows build or install any GNU/Linux distribution.

You can change system date, start WSL2 and then change system time back to automatic. Worked for me, using WSL2 as we speak.

**Comment by chiqui3d** [comment]
Ok, but now I don't know what to do whether to install Ubuntu directly or some way to go back to the stable version of Windows no "insiders" without losing the data and without having to format the system again, I don't want to have to reconfigure my PC all over again, this is crazy.

**Comment by reganh48** [comment]
per Nickesh above: change the sysdate to 31-Oct, then start up any linux instance with wsl, afterwards revert to auto date and all is irritatingly well. Once once instance is booted, then others will boot. I started with ubuntu-20.04 then kali

**Comment by chiqui3d** [comment]
I have already fixed it. Thanks https://github.com/microsoft/WSL/discussions/7646#discussioncomment-1599751

**Comment by iTem186** [comment]
No more update the build expiration?

> FINAL Build Expiration Reminder: We have updated the build expiration for Dev Channel builds to be 9/15/2022. Previous Dev Channel builds from the RS_PRERELEASE branch will expire on 10/31/2021. To avoid hitting this expiration, please be sure to update to the latest Dev Channel build today.
 
Since 9/15/2022 I have the same problem with WSL:
>The network name cannot be found.
>
>[process exited with code 4294967295 (0xffffffff)]

Edition	Windows 11 Pro Insider Preview
Version	Dev
OS build	22471.1000

And no possibilities to update on new release because of hardware requirements for Windows 11.

Only change system date allow to start WSL, but there are new problems inside WSL, because of:
![изображение](https://user-images.githubusercontent.com/26230210/191166910-e74832e0-0bc7-4b15-a508-8ef573181bb4.png)
