### ISSUE TITLE
Can't echo correctly when pasting multiple lines to WSL 2

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/WSL#6510]
> The following was originally posted by @jiasli in microsoft/terminal#9002. Since it's a WSL2 issue, I'm moving it here.
<hr>

# Environment

```none
> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```
Windows Terminal version (if applicable):
1.5.10271.0

Any other software?
WSL 2

# Steps to reproduce

Paste multiple lines to Windows Terminal running WSL 2 and Ubuntu 18.04/20.04.

```
# test line 1
# test line 2
# test line 3
# test line 4
```

# Expected behavior

Lines should be echoed line by line:

![image](https://user-images.githubusercontent.com/4003950/106602339-d13f8480-6597-11eb-96ab-418bacdf5bc6.png)

# Actual behavior

The echoed text is corrupted.

![image](https://user-images.githubusercontent.com/4003950/106602052-6ee68400-6597-11eb-80f0-6d8dc18a5eb1.png)

The same issue also happens in Windows 10's built-in terminal.

![image](https://user-images.githubusercontent.com/4003950/106602123-87ef3500-6597-11eb-8483-a178d2b37af3.png)

Also VS Code Terminal:

![image](https://user-images.githubusercontent.com/4003950/106603181-eec11e00-6598-11eb-8116-b726d9cf58de.png)

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/107071359-6d84a980-6799-11eb-864e-979b7899b091.png)

**Comment by jiasli** [comment]
This issue becomes annoying especially when the content matters:

```
cat >out.txt <<EOF
testtest
EOF
```

The output is barely readable:

![image](https://user-images.githubusercontent.com/4003950/156331731-c18c550f-a869-4ab8-946a-cf1b957a23d4.png)
