### ISSUE TITLE
\r\n line endings make commands like grep and awk unusable

### ISSUE THREAD

**Issue by francesco1119** [microsoft/WSL#6518]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19035.1]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Create a file called `1.txt` with the content: 

        apple
        orange
        butter
        flower

2. Create a file called `2.txt` with the content: 

        dog cat Butter tower

3. Run `awk `to find the common words in the 2 files:

`awk 'NR==FNR{a[tolower($0)];next} tolower($0) in a' 1.txt  RS="[\n ]" 2.txt`

but nothing is returned

![1](https://user-images.githubusercontent.com/3397477/106961132-7182de00-673d-11eb-8771-d22caf22fa1a.png)

4.  Run `grep `to find the common words in the 2 files:

`grep -oiwFf 1.txt 2.txt`

again nothing is returned

![2](https://user-images.githubusercontent.com/3397477/106961169-83fd1780-673d-11eb-8db2-6ba2484dbdb5.png)

5. But if you use awk to skip the `\r\n` line endings:

`awk -v RS='[ \r\n\t]' 'FNR==NR{words[tolower($0)]; next} tolower($0) in words' 1.txt 2.txt`

the shell finally returns the word "Butter"

![3](https://user-images.githubusercontent.com/3397477/106961192-8c555280-673d-11eb-9e99-84e9702c5066.png)

#  Expected behavior

`grep` and `awk ` should return the word Butter anyway without need to add `\r\n`. Not sure if there is even a way to tell grep to skip `\r\n` line endings.

# Actual behavior

regex scripts and common shell commands like `grep` or `awk` are unusable on WSL. 
`dos2unix` doesn't fix the issue.

**Comment by drkvogel** [comment]
I don't think this is an issue with WSL. It's just how grep and awk work with files on Windows, i.e. not very well. If there is an issue, it's with awk or grep, not WSL.

However, if you want to use awk or grep in WSL as normal, then keep your files in the Linux filesystem, e.g. in /home/franc` rather than `/mnt/c/Users/franc`.

**Comment by drkvogel** [comment]
Actually, I just tried your example, in Ubuntu 20.04 in WSL, with files created in the Windows filesystem, and `grep` works for me. I used `vi` to create the files and it looks like they have Unix line endings, what did you use to create the files?

```
21/02/5 15:03:33 /mnt/c/Users/cbird/Downloads
❯ vi 1.txt
❯ vi 2.txt
❯ file 2.txt
2.txt: ASCII text
❯ file 1.txt
1.txt: ASCII text
❯ man grep
❯ grep Butter *.txt
2.txt:dog cat Butter tower
❯ man grep
❯ grep -oiwFf 1.txt 2.txt
Butter
```

**Comment by francesco1119** [comment]
Thank you @drkvogel 

I created the files with `nano` and both commands are working in WSL file system

![Nano](https://user-images.githubusercontent.com/3397477/107054281-3382ca00-67d0-11eb-8aef-b2091c9571d0.png)

Then I did the same on Windows file system (my desktop) and the are working as well:

![Nano Windows](https://user-images.githubusercontent.com/3397477/107054341-4a292100-67d0-11eb-8b72-47447104e49b.png)

The commands `grep` and `awk` were not working because the files `1.txt` and `2.txt` were created in Windows through Notepad++.
So we can state that when using WSL just use it with files created by WSL. 
Quite sure Microsoft is aware of this and they are not going to fix, right?

**Comment by drkvogel** [comment]
Great. Well glad you found a way to do what you want to do, but again, this isn't really an issue with WSL, it's to do with `grep`, and `grep` is not maintained by Microsoft. The authors of `grep` are [here](https://github.com/mfragkoulis/grep/blob/master/AUTHORS). But `grep` hasn't changed for years and it not likely to - it's not meant for Windows files, it's a Linux utility! So keep your files in Linux format you won't have these problems.

**Comment by Bjelke98** [comment]
I am now getting this issues running my Ruby on rails dev server on WSL2.
I run Ubuntu LTS on my laptop where everything works, but when i pull from the git repo on my WSL Ubuntu it somehow reads \r on alot of script files. The project folder is inside the linux file system and it works perfectly fine on my laptop where i have the OS installed natively.
Example of my issue:
```SHELL
bjelke@LAPTOP-CI06G18G:~/projects/myProject$ bin/dev
/usr/bin/env: ‘sh\r’: No such file or directory
```
Here it has added the \r for some reason. There are many other scripts like this also.
I am also cloning the git from within WSL.
