### ISSUE TITLE
Bluescreen after enabling two required characteristics.

### ISSUE THREAD

**Issue by SmolShibe** [microsoft/WSL#6527]
# Environment

```none
Windows build number: [Version 10.0.19041.746]
Your Distribution version: [Can't check]
Whether the issue is on WSL 2 and/or WSL 1: [Can't check]
```

# Steps to reproduce

Enabling "Windows subsystem for linux"
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
as well as "Virtual machine feature"
`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

**WSL logs**: https://aka.ms/AAb2wes

#  Expected behavior
Normal functioning of WSL

# Actual behavior
It has crashed my computer after the restart step a total of 5 times (blue screen). I can't see the error type because it flashes too fast before I can read anything.
In the BIOS the virtualization is enabled, yet I can't enable it on Windows. Neither with the control panel nor commands. I made an effort to install a preview build of Windows 10 (OS build 20262 or higher) with Windows Insider but I suppose it failed because I can't use the `wsl.exe --install` command either. 
I can’t use Linux or any virtual machine as a result.
If you can help me I would appreciate it.

**Comment by craigloewen-msft** [comment]
Thank you for the initial logs! Could you please attach a file called 'MEMORY.DMP' to a Feedback Hub item and attach a link to that feedback hub item here? 

You can find the file in your Windows directory, e.g: `C:\Windows\MEMORY.DMP` and please make sure to upload it only to Feedback Hub and not to attach it directly to this issue. :)

**Comment by SmolShibe** [comment]
https://aka.ms/AAb2wes
It's on a zip file but it is there.

**Comment by gayuna** [comment]
I had a similar problem today. In my case, error message was 'kmode exception not handled' with 'cbfltfs4.sys'. After I downgrade my wsl to 1, there was no problem. I wonder why there's a problem with wsl2.

**Comment by stehufntdev** [comment]
> https://aka.ms/AAb2wes
> It's on a zip file but it is there.

@SmolShibe thanks for the reporting the issue.

I've done an initial pass over the bug details and dumps, and I believe this is due to buggy or outdated drivers on your system.  Can you please check that your drivers are up-to-date specially your graphics card?  I need to dig a bit more into one of the dumps but so far there is nothing specific to WSL2 but instead looks like there is an issue when enabling the optional components with certain drivers.

**Comment by stehufntdev** [comment]
> I had a similar problem today. In my case, error message was 'kmode exception not handled' with 'cbfltfs4.sys'. After I downgrade my wsl to 1, there was no problem. I wonder why there's a problem with wsl2.

@gayuna really appreciate the feedback since we are trying to narrow this one down.

Can you provide some more context on your repro steps similar to the original post?  For example does the bugcheck hit consistently after enabling WSL2, are you able to provide a dump, ...?

**Comment by stehufntdev** [comment]
Closing this out since it's been a week with an update on the repro.  If this hits again please follow the directions above to collect a complete dump.

**Comment by ohomeo** [comment]
I had the same problem, it still exists after reinstalling the system. Once I enabled "Virtual machine feature", the windows 10 became bluescreen immediately，I could not record the err code. By the way, I Updated the graphics driver last time and try again, bluescreen again. I gave it up.

**Comment by adrastogi** [comment]
@ohomeo thanks for letting us know. We're really interested in trying to get to the bottom of this; if you are able to, please consider reporting this through the Feedback Hub so we investigate your case further. (There are additional instructions in the response [here](https://github.com/microsoft/WSL/issues/6527#issuecomment-804333844) for generating a dump file as well.)

**Comment by gayuna** [comment]
> > I had a similar problem today. In my case, error message was 'kmode exception not handled' with 'cbfltfs4.sys'. After I downgrade my wsl to 1, there was no problem. I wonder why there's a problem with wsl2.
> 
> 
> 
> @gayuna really appreciate the feedback since we are trying to narrow this one down.
> 
> 
> 
> Can you provide some more context on your repro steps similar to the original post?  For example does the bugcheck hit consistently after enabling WSL2, are you able to provide a dump, ...?

Hi, sorry for such a late reply. I have dump file but I have a compliance issue that I cannot send them to outside of my company. I'll just leave my development environment just in case. I hope this could be a clue.

I have a PC with windows 10 and Linux machine. My windows is connected to internet outside, but The linux one is only to internal repo.
So when I want to push my code to outside, I use WSL. Basically, I mount my working directory of linux machine with SAMBA. And then I move to working directory using wsl (like /mnt/workdir) and start using git command.
The blue screen usually occured when I use git commands.

**Comment by SmolShibe** [comment]
@stehufntdev 
Sorry for the late reply
Yes, my graphic drivers are up to date. I have NVIDIA graphics, I don't know if that causes problems or not. 

I'll do the complete crash dump in a day or two, and hopefully, nothing breaks.
