### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by kentahikaru** [microsoft/WSL#6531]
# Environment
* Windows build number: [run `cmd.exe /c ver`]

Microsoft Windows [Version 10.0.18363.1316]

* Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]

lsb_release  -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

* Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]

cat /proc/version                                                                                                                                                                                                      Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020       

# Steps to reproduce
I was following this guide
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux

But stumble upon this error: (anonymizes username)
$ sudo blobfuse /mnt/blob/ --tmp-path=/mnt/tmpblob  --config-file=/home/<user>/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
fuse: device not found, try 'modprobe fuse' first
$ modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-18362-Microsoft

Is there something i need to install ?

**Comment by 0xbadfca11** [comment]
You must use WSL2.

**Comment by kentahikaru** [comment]
Thanks. I will try that.

**Comment by kentahikaru** [comment]
Also the linux i'm running has to be "wsl 2 compatible" ? or can i switch wsl 1 linux into wsl 2 ?

**Comment by kentahikaru** [comment]
after installing wsl 2 and converting distro into wsl 2 , it works. thanks.
