### ISSUE TITLE
Failed to install Ubuntu 20.04 with 0x8007023e

### ISSUE THREAD

**Issue by cms42** [microsoft/WSL#6537]
## Environment
```
WSL2
Windows 10 Prefessional Insider Preview 2004
Version 21301.1010
Windows Feature Experience Pack 221.501.0.3
```

## Steps required to reproduce
```
wsl --install -d Ubuntu-20.04
```

## Copy of the terminal output
```
Ubuntu 20.04 LTS is already installed.
Launching Ubuntu 20.04 LTS...
<New Window Opened>
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007023e
Error: 0x8007023e {??????}
???????? s (0x
Press any key to continue...
```

##  Expected Behavior
Installation successfully completed

## WSL Logs

[wsl.etl.zip](https://github.com/microsoft/WSL/files/5965131/wsl.etl.zip)

**Comment by craigloewen-msft** [comment]
I took a quick look at your logs and the error is coming from when the network is being created. This needs a deeper dive on debugging, I'll follow up with the team!

**Comment by craigloewen-msft** [comment]
Saw this is a dupe! /dupe #5508 

I'll link to the etl in that thread to simplify tracking. :) Thanks @therealkenc
