### ISSUE TITLE
重装wsl后，无法设置用户名。/指定的网络名不再可用。/The specified network name is no longer available.

### ISSUE THREAD

**Issue by xslzlccc** [microsoft/WSL#6545]
当我重装wsl后，进行到设置账户名密码阶段时，出现bug，我无法设置任何账户名，无论是与之前相同的或是另一个新的用户名，并且尝试过全部小写，大写+小写，大写+小写+数字等等方式，并且此问题在之前的"issue"中也存在，但并无解决方案。如果你希望通过英文与我交流，那只能祝我们好运。(Hope you have a good relationship with Google Translate !)
以下是问题的屏幕截图:

Installing, this may take a few minutes...
指定的网络名不再可用。
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: kali
指定的网络名不再可用。

Installing, this may take a few minutes...
指定的网络名不再可用。
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: 
The specified network name is no longer available.
![image](https://user-images.githubusercontent.com/50007642/107800157-62350d80-6d99-11eb-879e-d5536b80ef30.png)

**Comment by xslzlccc** [comment]
![image](https://user-images.githubusercontent.com/50007642/107803964-4aac5380-6d9e-11eb-9728-81f7e0fdcc64.png)

**Comment by benyaminl** [comment]
Try to do inplace upgrade https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html
Then try again to run wsl.

**Comment by therealkenc** [comment]
/dupe #6378. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in #6378. Also please identify any third-party networking software that has been installed on Windows.

**Comment by wxdx110** [comment]
我也遇到了这个问题，不过我已经修复了。该问题和.NET版本有关，你可以卸载.net更新，然后重新开启.NET功能来解决该问题。
I also encountered this problem, but I have fixed it. The problem is related to the .NET version. You can uninstall the .net update and then re-enable the .NET Framework to solve the problem.
![image](https://user-images.githubusercontent.com/24190389/108832236-3706b580-7606-11eb-92ef-b65d72e54790.png)

**Comment by typ431127** [comment]
我也遇到了这个问题
![Uploading Snipaste_2021-03-08_17-44-25.png…]()

**Comment by xslzlccc** [comment]
希望早日解决 ，上面那个重装.net 试过了，没用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/WSL"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午5:45
收件人:&nbsp;"microsoft/WSL"<WSL@noreply.github.com&gt;;
抄送:&nbsp;"1808486333"<1808486333@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/WSL] 重装wsl后，无法设置用户名。/指定的网络名不再可用。/The specified network name is no longer available. (#6545)





 
我也遇到了这个问题

**Comment by typ431127** [comment]
> 希望早日解决 ，上面那个重装.net 试过了，没用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/WSL" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月8日(星期一) 下午5:45 收件人:&nbsp;"microsoft/WSL"<WSL@noreply.github.com&gt;; 抄送:&nbsp;"1808486333"<1808486333@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [microsoft/WSL] 重装wsl后，无法设置用户名。/指定的网络名不再可用。/The specified network name is no longer available. (#6545) 我也遇到了这个问题

我也试了，没用

**Comment by typ431127** [comment]
我解决了这个问题，尝试了很多方法终于解决了，我卸载了电脑里面的安卓模拟器，使用管理员权限执行了下面的命令。
`bcdedit /set hypervisorlaunchtype auto`
然后重启电脑，再次执行wsl已经可以使用了。
![Snipaste_2021-03-15_18-48-23](https://user-images.githubusercontent.com/20376675/111141956-16a39880-85bf-11eb-8d2e-3bfc012a189f.png)
参考: [https://blog.csdn.net/u010071211/article/details/113857825](https://blog.csdn.net/u010071211/article/details/113857825)

**Comment by xslzlccc** [comment]
牛逼，我电脑里确实也装了安卓模拟器，等我忙完了去试一下！------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月15日(星期一) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/WSL] 重装wsl后，无法设置用户名。/指定的网络名不再可用。/The specified network name is no longer available. (#6545)

**Comment by forfullstack** [comment]
> 我解决了这个问题，尝试了很多方法终于解决了，我卸载了电脑里面的安卓模拟器，使用管理员权限执行了下面的命令。
> `bcdedit /set hypervisorlaunchtype auto`
> 然后重启电脑，再次执行wsl已经可以使用了。
> ![Snipaste_2021-03-15_18-48-23](https://user-images.githubusercontent.com/20376675/111141956-16a39880-85bf-11eb-8d2e-3bfc012a189f.png)
> 参考: https://blog.csdn.net/u010071211/article/details/113857825

I have been struggled an hour to fix this issue.
Now it's working.
Thanks typ431127.
![image](https://user-images.githubusercontent.com/70382697/112248833-98678600-8c91-11eb-93ec-c3f9882702ca.png)

**Comment by Moriarty16** [comment]
Run cmd as admin, run "bcdedit /set hypervisorlaunchtype auto", then reboot.
And the ubuntu WSL works now. Thanks a lot.

**Comment by MCC12138** [comment]
”bcdedit /set hypervisorlaunchtype auto“
It worked.
Thanks.

**Comment by xslzlccc** [comment]
> > 希望早日解决 ，上面那个重装.net 试过了，没用
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "microsoft/WSL" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年3月8日(星期一) 下午5:45 收件人: "microsoft/WSL"<[WSL@noreply.github.com](mailto:WSL@noreply.github.com)>; 抄送: "1808486333"<[1808486333@qq.com](mailto:1808486333@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [microsoft/WSL] 重装wsl后，无法设置用户名。/指定的网络名不再可用。/The specified network name is no longer available. (#6545) 我也遇到了这个问题
> 
> 我也试了，没用

哥们，能把这个回复删了吗？这泄露了我的个人邮箱，麻烦了，谢谢。

**Comment by SRbone** [comment]
![image](https://github.com/microsoft/WSL/assets/20855228/38d91357-f28a-4d87-a8fe-2775dc8f54ac)

bcdedit /set hypervisorlaunchtype auto
然后重启电脑，再次执行wsl已经可以使用了。
上述操作已经试过了，还是不行啊。

指定的网络名不再可用。
找不到元素。
Press any key to continue...
