### ISSUE TITLE
Running windows executables using python's "subprocess.check_output()" in WSL2 does not work

### ISSUE THREAD

**Issue by robin865** [microsoft/WSL#6547]
# Environment
Microsoft Windows [Version 10.0.18363.1316]
Ubuntu 20.04
WSL2

# Steps to reproduce

In a python shell, run a windows binary (.exe) file using "subprocess.check_output()"

Ex:

subprocess.check_output(['/c/SomeDummyBinary.exe'])

python -c "import subprocess; subprocess.check_output(['/c/SomeBinary.exe'])"

Result:

Application Error popup, with text "The application was unable to start correctly (0xc0000142). Click OK to close the application"

**Comment by therealkenc** [comment]
Was not able to reproduce here.

![image](https://user-images.githubusercontent.com/7049700/107979026-a4657700-6f72-11eb-94f1-3779e559b980.png)

**Comment by robin865** [comment]
So weirdly enough, when I "cmd.exe /c ver" it works fine; but when I try to run that command and pipe it into "tail -n -1" I get the same popup error. I've attached strace output of "cmd.exe /c ver" and the same command piped into tail.

![image](https://user-images.githubusercontent.com/773106/108098568-6468c780-7038-11eb-86eb-342a5c0567ed.png)

[strace_failing_tail.txt](https://github.com/microsoft/WSL/files/5990377/strace_failing_tail.txt)
[strace_success_cmd.txt](https://github.com/microsoft/WSL/files/5990378/strace_success_cmd.txt)

**Comment by therealkenc** [comment]
Thank-you for the `strace(1)` logs, appreciated.
```
poll([{fd=0, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=3, events=POLLIN}], 5, -1) = 1 ([{fd=8, revents=POLLIN}])
recvfrom(8, "\7\0\0\0\f\0\0\0", 8, MSG_WAITALL, NULL, NULL) = 8
recvfrom(8, "B\1\0\300", 4, 0, NULL, NULL) = 4
poll([{fd=0, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=3, events=POLLIN}], 5, 0) = 0 (Timeout)
close(4)                                = 0
close(3)                                = 0
```

You might try 20H2 aka build 19042 and see if that fares better. At the very least the upgrade might shake some variable loose. If you like, collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. The sequence to record would be starting `wsl.exe` from the command line and then doing the `cmd.exe /c ver | tail -n 1`. But there doesn't appear to have been a previous report of the behavior (it isn't a duplicate), and there would be more screeching if not being able to pipe interop commands was widespread. No easy guesses on what externality could be the cause on your system. One usual suspect is AV software. What is the output of (from Powershell):

```
PS> Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntivirusProduct
```

**Comment by robin865** [comment]
Hmm, so I noticed had some pending updates (docker desktop, windows updates, maybe others) and restarted my laptop.

The cmd.exe | tail command works after the restart and so does the original subprocess.check_output command.

Not sure what was wrong; but it seems to have fixed itself

**Comment by therealkenc** [comment]
Alright thanks for the update; won't look a gift horse in the mouth.
