### ISSUE TITLE
MICROSOFT !!! Please we need a fix for this

### ISSUE THREAD

**Issue by K2ouMais** [microsoft/WSL#6549]
Hello everyone,

at the company where we work we all got Surface Laptop 3 (High Spec Laptops) and as developer we want to use WSL2 and Docker.

Just one thing that I want to be clear... We work on a financial company and so we dont have admin rights to change anything on our working maschines and so I think there has to be a solution from Microsoft for companies that have the same standards as we have.

After long discussions the company agreed on upgrading our maschines (Windows 10 build 1909) from WSL1 to WSL2.

At first everything worked normal in VPN, but because the VPN Network was having problems with people on DS-Light, the company had to change the MTU of the VPN Network.

Here is where all the problems started. From now on our WSL2 wouldnt get any connection to the internet.
- Updating Ubuntu doesnt work
- Connection to our internal Gitlab doesnt work
- Composer doesnt work
- NPM doesnt work
- Ping doesnt work

With other words, WSL2 is failing on everything.

Of course I tried almost every solution found here in the Issues, like:
- Stoping the auto generation of the wsl.conf and giving it the nameserver 8.8.8.8 and 1.1.1.1
- Changing the MTU in the WSL2 Distro
- and so on...

The only thing that really worked was converting from WSL2 to WSL1, but than I loose the ability to work with it on Docker.

Every single fix failed on me, but on the other end I cant try every fix, because I dont have the admin rights for it. Remember????

Here is where I really need you to help us out, with a fix, so that I can send it to our Operations Team and for them to try to fix it for us.

I am seeing people here having the exact same Problem since 2019 and 2020 and I cant believe that we are already in 2021 and because of the pandemic Microsoft knows that almost every people over the world is working from home and still refuses to give us a fix for this.

PLEASE, PLEASE, PLEASE MICROSOFT... HELP US HERE...

Thanks

**Comment by bplasmeijer** [comment]
duplicated of #6264 
Please use feedback hub, and add ID to #6264

**Comment by K2ouMais** [comment]
As you can see in my post... I dont have Admin Rights and so I cant use the Feedback Hub at all.

**Comment by Biswa96** [comment]
> we dont have admin rights to change anything on our working maschines 

Do you have permission to install another OS or boot from external drive? If yes install any GNU/Linux distribution and use docker there.

**Comment by bplasmeijer** [comment]
> As you can see in my post... I dont have Admin Rights and so I cant use the Feedback Hub at all.

Talk to your IT, without proper report MS can not solve the issue.
