### ISSUE TITLE
Bad French translation in wsl.exe tool

### ISSUE THREAD

**Issue by odalet** [microsoft/WSL#6550]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.804]
Your Distribution version: Debian 10 (but irrelevant)
Whether the issue is on WSL 2 and/or WSL 1: none: Windows side (wsl.exe)
```

# Steps to reproduce

From a Windows prompt, on a French machine, I'm converting my WSL 1 Debian instance to WSL 2:

```
> wsl --set-version Debian 2
La conversion est en cours. Cette opération peut prendre quelques minutes...
Pour plus d’informations sur les différences de clés avec WSL 2, visitez https://aka.ms/wsl2
```

#  Expected behavior

In French, the last line of the message should say: 

```
Pour plus d’informations sur les différences clé de WSL 2, visitez https://aka.ms/wsl2
```

# Actual behavior

```
Pour plus d’informations sur les différences de clés avec WSL 2, visitez https://aka.ms/wsl2
```

NB: I suppose this was translated from something like "For more information regarding the key differences of WSL 2...". The current French sentence makes no sense (it's talking about keys as in the keys I use to close a door... or cryptographic keys, which is a bit confusing).

PS: Obviously this is not a major issue and I'm not even sure it belongs here...

**Comment by WSLUser** [comment]
Related: https://github.com/microsoft/terminal/issues/9238. It appears the loc team did a poor job on translating French in general. Providing the proper words here like in the other issue for proper translation would help the loc team to update necessary words (hopefully they got some ai working in the background that helps improve the translation better with the input of the proper words used in different tools).

**Comment by odalet** [comment]
@WSLUser, I'm not sure I understand your comment: do you mean I could provide some table similar to the one by @gpotter2 in the issue you mention? I'd be glad to, but:
* I only spotted this one translation error in `wsl.exe`
* I don't think `wsl.exe` source code is available and therefore, I can't tell what the translation key is for this particular message
* I provided what I think is a better translation in "Expected behavior"

However, if there's something I can do to ease the translation fix, just let me know!

Btw, the translation is not as bad as what I've seen in https://github.com/microsoft/terminal/issues/9238; such a mistake in the use of 'Key' is understandable... and for a bit of fun, I remember that Oracle used to - at least up to Oracle 9i - translate its `ORA-02291` error (parent key not found) by _Touche parent introuvable_. Well... here 'touche' means a piano or keyboard 'key', not a PK or FK; should have been "clé"!

**Comment by gpotter2** [comment]
Please don't ping me.
IMHO the translation here is actually correct /shrug

**Comment by odalet** [comment]
Apologies. I've edited your mention out.

That said, I still think there's a translation error there. I know there's this json configuration file for wsl that exists, but the link in the message does not point to any specific information on it. I even suspect the link is wrong as well. It should point to <https://docs.microsoft.com/en-us/windows/wsl/compare-versions> instead of <https://docs.microsoft.com/en-us/windows/wsl/about>

**Comment by WSLUser** [comment]
> I only spotted this one translation error in wsl.exe

Yeah, a table isn't needed for just one word. I don't speak French myself, I just noticed the translation issues. I've seen other ones but not for French specifically on other MS projects. The tool they use for doing these translations seems to be a work in progress. The winget repo for example has a few translation issues and PRs that are used for correcting the issues. But I've always seen the feedback of filing issues where translation errors occur being met positively with intent to correct the deficiencies and encouragement to file more issues like it when issues are spotted.

**Comment by bpulliam** [comment]
It now reads: Pour plus d’informations, visitez https://aka.ms/wsl2kernel

**Comment by odalet** [comment]
Even better than my proposition :)
