### ISSUE TITLE
wsl --exec won't mount drvfs on WSL 1

### ISSUE THREAD

**Issue by karuboniru** [microsoft/WSL#6551]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18363.1316]
Your Distribution version: Ubuntu 20.04.1 LTS
Whether the issue is on WSL 2 and/or WSL 1: 1
```

# Steps to reproduce
Iets imagine one who broke his WSL instance by messing with glibc
1. `rm /usr/lib/x86_64-linux-gnu/libc-2.31.so`
2. A system reboot, or `wsl.exe --shutdown`, or to kill `init` process in Task Manger in Windows side.

Then he wants to rescue the system via a busybox-static binrary placed in `C:/`

3. `wsl -d Ubuntu-20.04 --exec /mnt/c/misc/busybox-x86_64 sh` and hoping to see a shell

If the guy is lucky enough to have a busybox in WSL rootfs, for example `/busybox-x86_64`

4. `wsl -d Ubuntu-20.04 --exec /busybox-x86_64 sh` and hoping to see a shell

#  Expected behavior

One may wants to see shell in both step 3 or step 4

# Actual behavior

Only step 4 will work, which means `/mnt/c/` as drvfs is not accessible when `wsl --exec` is used. This may block people from fixing a broken WSL release.

**Comment by therealkenc** [comment]
Looks like this is addressed in WSL2.

![image](https://user-images.githubusercontent.com/7049700/107982549-180a8280-6f79-11eb-87f9-ce17f9c9e8e7.png)
