### ISSUE TITLE
ls command has no output in mounted drives

### ISSUE THREAD

**Issue by serkonda7** [microsoft/WSL#6556]
# Environment
Microsoft Windows [Version 10.0.19042.746]
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
```sh
sudo mkdir /mnt/z
sudo mount -t drvfs Z: /mnt/z
cd /mnt/z
ls
```

>  strace: command not found

**WSL logs**: cannot be provided
```
C:\Users\localadmin\Downloads>wpr -start wsl.wprp -filemode

        Error code: 0xc00cee4f
```

# Additional Information
Output of `mount`:
```
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
Z: on /mnt/z type drvfs (rw,relatime,case=off)
```

**Tab autocomplete of files and paths doesn't work too.**

#  Expected behavior

I expect to see my files and folders on this drive listed.

# Actual behavior

Instead I have no output.
The exit code of `ls` is 0 though.

**Comment by Biswa96** [comment]
I think the cause is the absence of mount metadata options. Try this command 

```
sudo mount -t drvfs Z: /mnt/z -o metadata,uid=1000,gid=1000
```

**Comment by serkonda7** [comment]
Sadly this doesn't fix the problem. 

Also he docs say that metadata is enabled by default.

**Comment by serkonda7** [comment]
Maybe this additional information is helpful:
- The problem is in Virtual Box Windows VM on a Win10 host (I have no rights to use WSL outside a VM). 
- The Z drive is the mounting point of a shared folder between Host and VM.

**Comment by therealkenc** [comment]
Landing zone /dupe #2896.
