### ISSUE TITLE
Unable to run systemctl / service command in WSL2 Ubuntu20.4

### ISSUE THREAD

**Issue by AnuragYadav171** [microsoft/WSL#6561]
Hi,

Thanks for WSL2, its a great service to cope up with Linux within Windows !

However, I am unable to run systemctl / service command in WSL2 Ubuntu20.4
Is systemctl services not available in WSL2 or I need some other configuration procedure.

```
(base) anurag@DESKTOP-5A47SBM:~$ sudo systemctl status docker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
(base) anurag@DESKTOP-5A47SBM:~$
(base) anurag@DESKTOP-5A47SBM:~$
(base) anurag@DESKTOP-5A47SBM:~$ sudo service docker start
docker: unrecognized service
```

**Comment by therealkenc** [comment]
> sudo service docker start

There is a docker use-case discussion [here](https://github.com/microsoft/WSL/discussions/4872#discussioncomment-76635).
