### ISSUE TITLE
faccessat2 throws EPERM instead of ENOSYS

### ISSUE THREAD

**Issue by agowa338** [microsoft/WSL#6562]
# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.21313.1000]`
Your Distribution version: docker using wsl2
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (through docker)
```

# Steps to reproduce

1. `docker run --network=host --rm -it archlinux/base:latest /bin/bash`
2. `pacman -Syy`
3. `pacman -S glibc runc` To update glibc and runc individually.
4. `pacman -Syu` Just a command that uses the affected (missing) syscall.

strace:
```
faccessat2(AT_FDCWD, "/var/lib/pacman/", F_OK, AT_EACCESS) = -1 EPERM (Operation not permitted)
```
and if run using `--privileged`
```
faccessat2(AT_FDCWD, "/var/lib/pacman/", F_OK, AT_EACCESS) = -1 ENOSYS (Function not implemented)
```

**WSL logs**: 

#  Expected behavior

The syscall should either be implemented (updating to kernel >5.8) or throw the "ENOSYS" instead of "EPERM".

# Actual behavior

Linux 5.8 introduced a new syscall "faccessat2" which is required by current glibc and runc versions. Because of that ArchLinux docker containers fail to run on WSL2 right now with strange errors. Also the package manager pacman is suffering from this issue.

For the above mentioned example with pacman the output is:
```
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
```

Note: also whitelisting this syscall using `--security-opt seccomp=test.json` didn't work. As it still returns EPERM instead of ENOSYS...

# Workarounds

1. Running the docker container with `--privileged` works around this issue, as it returns the correct ENOSYS response.

# Relates to
https://bugs.archlinux.org/index.php?do=details&task_id=69563

**Comment by DHowett** [comment]
As I understand it, _WSL 2_ does not reimplement or interpose itself between the application and any system calls. Since it uses the actual Linux kernel, the response you get is in line with what you should get from 5.4 or 4.19 (depending on which you’re currently running.)

**Comment by therealkenc** [comment]
Same behavior under `docker` on a Real Linux™ Ubuntu 20.10 box. The linked thread in the OP mostly speaks for itself.

![image](https://user-images.githubusercontent.com/7049700/108267414-07484100-7120-11eb-9d3a-bb61f9a8785d.png)
