### ISSUE TITLE
wsl2: ulimit: value exceeds hard limit

### ISSUE THREAD

**Issue by thep0y** [microsoft/WSL#6564]
# Environment

```none
Windows build number: 10.0.19042.804
Your Distribution version: Debian 10
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Increase ulimit:
```shell
ulimit -n 65535
```
Then get the output:
```shell
ulimit: value exceeds hard limit
```

#  Expected behavior
`ulimit -n` can only be 1024 and cannot be increased.
Ulimit can be increased in wsl1.
This problem occurred when I switched linux to wsl2.

**Comment by therealkenc** [comment]
/dupe #4575. Looks like the hard default was increased on more recent builds. If your hard limit is 1024, it can be increased with `prlimit`. There is a discussion thread at #6226.

![image](https://user-images.githubusercontent.com/7049700/108351507-7a8e9900-719a-11eb-8147-a5a726d32b7f.png)

**Comment by qaqRose** [comment]
i solve my problem by `su username`
see [#1688](https://github.com/Microsoft/WSL/issues/1688)
![Uploading image.png…]()
