### ISSUE TITLE
Ports that a program is listening to inside WSL 2 are not accessible from Windows

### ISSUE THREAD

**Issue by narrowtux** [microsoft/WSL#6567]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Your Distribution version: Ubuntu 18.04
in WSL 2
```

# Steps to reproduce
 1. In WSL, open a webserver at port 4000
 2. In Windows, point your browser to `http://localhost:4000`. It should load whatever side is hosted in the webserver
 3. In WSL, navigate to a Windows folder (`/mnt/c/...`) and then write to some file. I was using `youtube-dl` and writing to the `~/Downloads` folder
 4. After that, refresh your browser, for me, the site wouldn't load any more.
 5. Inside WSL, the port is still accessible

#  Expected behavior

Port should continue staying open in windows

# Actual behavior

Port is not accessible in windows any more

---

I'm happy to provide more detail later, today I'd rather not try to reproduce it another time since I need WSL for work and restarting WSL is a bit cumbersome.

**Comment by therealkenc** [comment]
"Open a webserver at port 4000" is not a repro. Near always /dupe #4851 (and sometimes #5298) plus in general #4150.
