### ISSUE TITLE
WSL2 - libc-bin block upgrade and install of new packages

### ISSUE THREAD

**Issue by tutosfaciles48** [microsoft/WSL#6570]
# Environment

Note: I am unable to install lsb-release packet

```
Windows build number: 10.0.19042.804
Your Distribution version:  Debian 10.7
WSL2
```

# Steps to reproduce

[sudo] apt update && [sudo] apt install lsb-release

**WSL logs**: 

log send via feedback application

#  Expected behavior

The is no problem with installing/upgrading packets

# Actual behavior

No packets can be upgraded/installed as dpkg block on libc-bin

**Comment by therealkenc** [comment]
What is the error message returned by `apt`. A screencap will give some context. Also what is the result of `sudo ping security.debian.org`.
