### ISSUE TITLE
Cant Migrate to WSL2 Error code: 0x80070002

### ISSUE THREAD

**Issue by kunosee** [microsoft/WSL#6579]
# Environment

```none
Microsoft Windows [Version 10.0.19042.804]
Ubuntu-20.04 (Standard)
Migration from WSL1 to WSL2
```

# Steps to reproduce

**wsl --set-version Ubuntu-20.04 2**

After two minutes I receive this message:

> Die Konvertierung wird ausgeführt. Dieser Vorgang kann einige Minuten dauern...
> Informationen zu den wichtigsten Unterschieden zu WSL 2 finden Sie unter https://aka.ms/wsl2
> Aktivieren Sie bitte das Windows-Feature „Virtual Machine Platform” und stellen Sie sicher, dass die Virtualisierung im BIOS aktiviert ist.
> 
- Virtual machine platform is activated
- Intel VT is activated in Bios (Virtualbox 6.1.16 is running w/o any problems)
- CPU is two XEON X5550
-  Intel CPUid reports VT-x with Extended Page Tables is active
- I tried with Hyper-V and Windows Hypervisor Platform activated and deactivated

In addition, when trying co create logs with 
**wpr -start wsl.wprp -filemode**
I receive this error-message:
> Das System kann die angegebene Datei nicht finden.
> Error code: 0x80070002

**Comment by jamdoeswork** [comment]
![image](https://user-images.githubusercontent.com/56378742/109226060-1eaabc80-77f9-11eb-9539-591b3d9990c8.png)

**Comment by kunosee** [comment]
![grafik](https://user-images.githubusercontent.com/6794152/109657996-68333880-7b66-11eb-95b4-fe5a21df7b56.png)
As I wrote in my initial statement:  **Virtual machine platform is activated**

That is the reason, why I ask, what can I do/research else?

**Comment by kunosee** [comment]
Are there any log files or is there a _VERBOSE_ option, to see, what **wsl --set-version Ubuntu-20.04 2** is doing?
There must be something beyond _Virtual machine platform_, which is failing.

**Comment by kunosee** [comment]
I managed to get some Log Information:
```
Ebene,Datum und Uhrzeit,Quelle,Ereignis-ID,Aufgabenkategorie

Informationen,04.03.2021 17:52:21 Uhr,,0,Keine,
repeated 50 times

(6),04.03.2021 17:52:20 Uhr,Microsoft-Windows-Host-Network-Service,0,Keine,"Die Beschreibung für die Ereignis-ID ""0"" aus der Quelle ""Microsoft-Windows-Host-Network-Service"" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.
Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.
Die folgenden Informationen wurden mit dem Ereignis gespeichert: 
Die Nachrichtenressource ist vorhanden, die Nachricht wurde in der Nachrichtentabelle jedoch nicht gefunden
repeated 20 times


Informationen,04.03.2021 17:51:52 Uhr,Microsoft-Windows-Hyper-V-Compute,2000,Keine,"[216C377B-8987-4C46-B8AD-AD895F51BB02] Computesystem erstellen, Ergebnis 0x80370102"
Informationen,04.03.2021 17:51:52 Uhr,,0,Keine,
Informationen,04.03.2021 17:51:52 Uhr,Microsoft-Windows-Hyper-V-Compute,2009,Keine,[216C377B-8987-4C46-B8AD-AD895F51BB02] Systembenachrichtigung in Warteschlange einreihen: 1/0x80004005
Informationen,04.03.2021 17:51:52 Uhr,,0,Keine,
Fehler,04.03.2021 17:51:52 Uhr,Microsoft-Windows-Hyper-V-Compute,102,Keine,"onecore\vm\compute\management\shared\compute\EventReporting.h(189)\vmcompute.exe!00007FF627A6B0FB: (caller: 00007FF627AEA3CC) Exception(1) tid(cec) 80370102 Der virtuelle Computer konnte nicht gestartet werden, da ein erforderliches Feature nicht installiert ist.
    CallContext:[\HcsRpc_CreateSystem\ComputeSystemManager_Create\VirtualMachine_Construct] 

(6),04.03.2021 17:51:49 Uhr,Microsoft-Windows-Host-Network-Service,0,Keine,"Die Beschreibung für die Ereignis-ID ""0"" aus der Quelle ""Microsoft-Windows-Host-Network-Service"" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.
Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.
Die folgenden Informationen wurden mit dem Ereignis gespeichert: 
Die Nachrichtenressource ist vorhanden, die Nachricht wurde in der Nachrichtentabelle jedoch nicht gefunden

Ausführlich,04.03.2021 17:51:38 Uhr,,0,Keine,
Fehler,04.03.2021 17:51:38 Uhr,Microsoft-Windows-Hyper-V-Compute,11008,Keine,"System ""216C377B-8987-4C46-B8AD-AD895F51BB02"" kann nicht erstellt werden, da Hyper-V nicht auf dem Host installiert ist."
Informationen,04.03.2021 17:51:38 Uhr,,0,Keine,
Fehler,04.03.2021 17:51:38 Uhr,Microsoft-Windows-Hyper-V-Compute,102,Keine,"onecore\vm\compute\management\orchestration\shared\vmcommon\vmcommonhelpers.cpp(226)\vmcompute.exe!00007FF627AEA3B8: (caller: 00007FF627A9D0BF) LogHr(1) tid(cec) 80370102 Der virtuelle Computer konnte nicht gestartet werden, da ein erforderliches Feature nicht installiert ist.
    CallContext:[\HcsRpc_CreateSystem\ComputeSystemManager_Create\VirtualMachine_Construct] 

(6),04.03.2021 17:51:34 Uhr,Microsoft-Windows-Host-Network-Service,0,Keine,"Die Beschreibung für die Ereignis-ID ""0"" aus der Quelle ""Microsoft-Windows-Host-Network-Service"" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.
Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.
Die folgenden Informationen wurden mit dem Ereignis gespeichert: 
Die Nachrichtenressource ist vorhanden, die Nachricht wurde in der Nachrichtentabelle jedoch nicht gefunden
repeated 20 times

```

**Comment by kunosee** [comment]
For me it looks like, that some thing related to **Microsoft-Windows-Host-Network-Service** is missing, and **Microsoft-Windows-Hyper-V-Compute** throws an error message.
Unfortunately all error messages are very generic. So the only piece of information is, which components may be involved in the problem.

**Comment by houz92** [comment]
Hi @kunosee ,

Have you been able to solve your issue?

I previously had a working wsl 2 install. 
For some reason, I installed VMWare Player which turn out to now work and then uninstalled it.
That was the beginning of my trouble.

In the current state, I get the exact same error and I strongly suspect the now missing defaut virtual net adapter to be at the origin of the issue.
However, I haven't been able to restore it

**Comment by McTom234** [comment]
Hello @kunosee,

do you have a hint for me where I can find this error log? I have the same problem as you described (including same error code while trying to create logs).
If I have the same error as you, have you solve this problem?

**Comment by MuhammadWaseem29** [comment]
PS C:\Windows\system32> wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
The operation completed successfully.
