### ISSUE TITLE
wsl --mount on LUKS encrypted partition give error 22

### ISSUE THREAD

**Issue by adelin-b** [microsoft/WSL#6584]
# Environment

```none
Microsoft Windows [Version 10.0.21318.1000]
Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

```
 wmic diskdrive list brief
Caption                          DeviceID            Model                            Partitions  Size
Samsung SSD 850 EVO 500GB        \\.\PHYSICALDRIVE1  Samsung SSD 850 EVO 500GB        2           500105249280
SanDisk Cruzer Blade USB Device  \\.\PHYSICALDRIVE2  SanDisk Cruzer Blade USB Device  1           15998169600
Samsung SSD 870 QVO 1TB          \\.\PHYSICALDRIVE0  Samsung SSD 870 QVO 1TB          4           1000202273280
```
```
wsl --mount \\.\PHYSICALDRIVE1 --partition 2
```

**WSL logs**: 

#  Expected behavior

Disk should mount
# Actual behavior

Error 22 while mounting
```
The disk \\.\PHYSICALDRIVE1 was attached from WSL2, but failed to mount (error code: -22). For more details, run 'dmesg' inside WSL2.
```

Here is dmesg 

```
[  393.864749] proc: Bad value for 'hidepid'
[  410.877060] hv_pci 6abf7068-fc28-43fa-800e-637db710096e: PCI VMBus probing: Using version 0x10002
[  410.877592] 9pnet_virtio: no channels available for device drvfsa
[  410.877599] WARNING: mount: waiting for virtio device...
[  410.917882] hv_pci 6abf7068-fc28-43fa-800e-637db710096e: PCI host bridge to bus fc28:00
[  410.917883] pci_bus fc28:00: root bus resource [mem 0xe00010000-0xe00012fff window]
[  410.919144] pci fc28:00:00.0: [1af4:1049] type 00 class 0x010000
[  410.922810] pci fc28:00:00.0: reg 0x10: [mem 0xe00010000-0xe00010fff 64bit]
[  410.924142] pci fc28:00:00.0: reg 0x18: [mem 0xe00011000-0xe00011fff 64bit]
[  410.925481] pci fc28:00:00.0: reg 0x20: [mem 0xe00012000-0xe00012fff 64bit]
[  410.934859] pci fc28:00:00.0: BAR 0: assigned [mem 0xe00010000-0xe00010fff 64bit]
[  410.935836] pci fc28:00:00.0: BAR 2: assigned [mem 0xe00011000-0xe00011fff 64bit]
[  410.936821] pci fc28:00:00.0: BAR 4: assigned [mem 0xe00012000-0xe00012fff 64bit]
[  410.984691] hv_pci 27394e3e-6330-4748-93db-6849bf1f0a20: PCI VMBus probing: Using version 0x10002
[  411.027064] hv_pci 27394e3e-6330-4748-93db-6849bf1f0a20: PCI host bridge to bus 6330:00
[  411.027066] pci_bus 6330:00: root bus resource [mem 0xe00014000-0xe00016fff window]
[  411.028554] pci 6330:00:00.0: [1af4:1049] type 00 class 0x010000
[  411.032001] pci 6330:00:00.0: reg 0x10: [mem 0xe00014000-0xe00014fff 64bit]
[  411.033392] pci 6330:00:00.0: reg 0x18: [mem 0xe00015000-0xe00015fff 64bit]
[  411.035043] pci 6330:00:00.0: reg 0x20: [mem 0xe00016000-0xe00016fff 64bit]
[  411.044715] pci 6330:00:00.0: BAR 0: assigned [mem 0xe00014000-0xe00014fff 64bit]
[  411.045676] pci 6330:00:00.0: BAR 2: assigned [mem 0xe00015000-0xe00015fff 64bit]
[  411.046612] pci 6330:00:00.0: BAR 4: assigned [mem 0xe00016000-0xe00016fff 64bit]
[  418.076446] scsi 0:0:0:4: Direct-Access     Samsung  SSD              EMT0 PQ: 0 ANSI: 5
[  418.077233] sd 0:0:0:4: Attached scsi generic sg4 type 0
[  418.078399] sd 0:0:0:4: [sde] 976773168 512-byte logical blocks: (500 GB/466 GiB)
[  418.078724] sd 0:0:0:4: [sde] Write Protect is off
[  418.078726] sd 0:0:0:4: [sde] Mode Sense: 0f 00 10 00
[  418.079229] sd 0:0:0:4: [sde] Write cache: enabled, read cache: enabled, supports DPO and FUA
[  418.081533]  sde: sde1 sde2
[  418.083703] sd 0:0:0:4: [sde] Attached SCSI disk
[  418.086745] WSL2: Mapped partition 2 from device /sys/block/sde to /dev/sde2
[  418.087155] EXT4-fs (sde2): VFS: Can't find ext4 filesystem
[  418.087178] ERROR: Mount:2486: mount(/dev/sde2, /share/PHYSICALDRIVE1p2, ext4, 0x0, ) failed
[  418.087179] 22
[  434.842439] WSL2: Mapped partition 2 from device /sys/block/sde to /dev/sde2
[  434.845504] EXT4-fs (sde2): VFS: Can't find ext4 filesystem
[  434.845655] ERROR: Mount:2486: mount(/dev/sde2, /share/PHYSICALDRIVE1p2, ext4, 0x0, ) failed
[  434.845656] 22
[  448.830396] WSL2: Mapped partition 2 from device /sys/block/sde to /dev/sde2
[  448.833441] EXT4-fs (sde2): VFS: Can't find ext4 filesystem
[  448.833585] ERROR: Mount:2486: mount(/dev/sde2, /share/PHYSICALDRIVE1p2, ext4, 0x0, ) failed
[  448.833586] 22
[  537.295387] init: (156) ERROR: LogException:33: TELEMETRY: (null) Invalid argument @d:\os\src\onecore\VM\linux\mountutil\mountutilcpp.h:19 (MountEnum)

[  561.220602] WSL2: Mapped partition 2 from device /sys/block/sde to /dev/sde2
[  561.223658] EXT4-fs (sde2): VFS: Can't find ext4 filesystem
[  561.223795] ERROR: Mount:2486: mount(/dev/sde2, /share/PHYSICALDRIVE1p2, ext4, 0x0, ) failed
[  561.223796] 22
```

It look related to telemetry but I do not have a clue how.

**Comment by 0xbadfca11** [comment]
Try ``blkid`` command.

**Comment by PavelSosin-320** [comment]
@0xbadfca11 I got it today too! 
MSI-wsl login: [ 1555.416304] ERROR: Mount:2486: mount(/dev/sdb, /distro, ext4, 0x0, discard,errors=remount-ro,data=ordered
[ 1709.223077] ERROR: Mount:2486: mount(/dev/sdb, /distro, ext4, 0x0, discard,errors=remount-ro,data=ordered
It happens after when running wsl as root user and the following log lines.
Starting [0;1;39mUpdate UTMP about System Runlevel Changes[0m...
[[0;32m  OK  [0m] Finished [0;1;39mUpdate UTMP about System Runlevel Changes[0m.

How to run something if no all distros stopped to start and even to be opened in the File Explorer.

**Comment by PavelSosin-320** [comment]
It looks like OpenSSH not only unable to start but kills the distro:
[[0;1;31mFAILED[0m] Failed to start [0;1;39mOpenBSD Secure Shell server[

**Comment by adelin-b** [comment]
> Try `blkid` command.
I do not see how it can be usefull because it didnt managed to mount and could not start the session but here is the result in a normal wsl session
```
/dev/loop0: BLOCK_SIZE="2048" UUID="2021-01-13-09-34-21-00" LABEL="wsl-cli-bundle" TYPE="iso9660"
/dev/loop1: BLOCK_SIZE="2048" UUID="2021-01-13-11-46-09-00" LABEL="LinuxKit" TYPE="iso9660"
/dev/sda: UUID="3255683f-53a2-4fdf-91cf-b4c1041e2a62" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sdb: UUID="3255683f-53a2-4fdf-91cf-b4c1041e2a62" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sdc: UUID="3255683f-53a2-4fdf-91cf-b4c1041e2a62" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sdd: UUID="3255683f-53a2-4fdf-91cf-b4c1041e2a62" BLOCK_SIZE="4096" TYPE="ext4"
```

**Comment by WSLUser** [comment]
> Also I might add that the partition are LUKS encrypted but it shouldnt prevent mount

LUKS aren't supported in the default kernel for WSL2. There was an issue filed on the WSL2 repo for it but it's gone now. So the mount being prevented makes sense as the kernel is unable to read it. Try compiling a kernel with support for LUKS and then try the mount. If it then works, then the fix is to add the support to the default kernel. If it still does not, then that would also mean fixing the `wsl --mount `to support that partition type.

**Comment by therealkenc** [comment]
> LUKS aren't supported in the default kernel for WSL2. 

What specific `=y` entries are missing from the [5.4.91 config](https://github.com/microsoft/WSL2-Linux-Kernel/blob/eaa73a2d52ff620a8c71ba23d57a73a0e33eae03/Microsoft/config-wsl) (_as it pertains to LUKS_)? I did a brief look but nothing stood out.

**Comment by adelin-b** [comment]
Maybe it can help if I do not try to mount it as default ? Im fine with booting with usual wsl and then mounting and chroot inside. Does that seems possible? All I found to mount another disc was the --mount option but maybe I can mount in another way.

**Comment by 0xbadfca11** [comment]
Use --mount with --bare option, will attach disks without mount.

**Comment by adelin-b** [comment]
> Use --mount with --bare option, will attach disks without mount.

Exactly what I needed, thank you, I can now chroot into my other linux dualboot and use it instead of using the wsl system. Its amazing.

**Comment by Marietto2008** [comment]
I have the same error :

![2021-04-23_18-05-42](https://user-images.githubusercontent.com/755339/115920315-52613600-a47a-11eb-8442-73391ac6df1b.png)

![2021-04-23_18-07-47](https://user-images.githubusercontent.com/755339/115920318-52f9cc80-a47a-11eb-80f7-9a1665857331.png)

this is my .wslconfig file now :

[wsl2]
nestedVirtualization=true
debugConsole=true
pageReporting=true
kernelCommandLine=intel_iommu=on iommu=pt kvm.ignore_msrs=1 kvm-intel.nested=1 kvm-intel.ept=1 kvm-intel.emulate_invalid_guest_state=0 kvm-intel.enable_shadow_vmcs=1 kvm-intel.enable_apicv=1

the kernel version that Im using is : 

Linux DESKTOP-N9UN2H3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by onomatopellan** [comment]
@Marietto2008 As @0xbadfca11 said:

> Use --mount with --bare option, will attach disks without mount.

**Comment by Marietto2008** [comment]
The solution is here : https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/comment-page-2/

wsl --mount \\.\PHYSICALDRIVE3 --partition 1

the linux partition has been mounted successfully,anyway the error "no channel available for device drvfsa" is still there.

**Comment by Marietto2008** [comment]
how can I automount the partitions that aren't mounted automatically as soon as ubuntu is landed ?
