### ISSUE TITLE
Erroneous DNS request from WSL2 takes >10s in specific conditions

### ISSUE THREAD

**Issue by lassi-niemisto** [microsoft/WSL#6585]
# Environment

```none
Windows build number: 10.0.19042.804
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Inside WSL2 Ubuntu:
`time dig +time=20 somenonexistentdomain.com`
should return pretty fast, but when I connect my OpenVPN, it starts to take ~12 seconds which causes all sorts of trouble, knowing the WSL DNS is somehow queuing the requests in single thread as mentioned in https://github.com/microsoft/WSL/issues/4285

Problem seems to be between windows services **"Dnscache"** and **"SharedAccess"** doing their part in DNS relaying.

Different setups and results:
* Without VPN everything works
* With our older Sophos OpenVPN everything works (uses Sophos SSL network adapter, hereafter "SophosTap")
* With our new OpenVPN this strange delay happens (uses TAP-Windows Adapter V9, hereafter "OpenTap")

I have 2 Wiresharks monitoring both the "vEthernet (WSL)" and the "SophosTap"/"OpenTap" adapter to see how it goes. The dns traffic visible in the "WSL" adapter is logical and immediate in all cases (request goes immediately out to one of the Taps and when reply is seen in WSL adapter, dig terminates immediately. 

Thus it is mostly interesting to see what happens in the Tap adapters and compare the two VPN setups. For better understanding of the participants, I have used LiveTcpUdpWatch tool to translate UDP traffic to PIDs. The process in "SophosTap"/"OpenTap" goes:
* Windows service "Dnscache" sends DNS request to correct DNS server
* Server replies logically and fast. _NOTE: This reply does not cause any activity in "WSL" interface!_
* **At this point, the ~10sec delay happens with "OpenTap"**
* Windows service "SharedAccess" sends again the same DNS request to correct DNS server
* Server replies logically and fast.
* This reply causes a (translated) reply to be immediately sent to "WSL" interface, which completes the activity

Some additional things found/tried:
* It does not matter in which order the VPNs/WSL are started up
* Correct requests always return fast and the "SharedAccess" service does not play a role in the traffic 
* The first reply from DNS server in both cases is identical and does not explain the difference in what happens next
* The DNS sequence is immediate  even in the problem conditions if the correct target server is provided to dig command, bypassing the WSL host side resolver mechanism
* Specifying the correct target DNS inside WSL Ubuntu (bypassing the WSL DNS) provides immediate response

#  Expected behavior

Inside WSL2 Ubuntu:
Erroneous request such as `time dig +time=20 somenonexistentdomain.com` should return pretty fast

# Actual behavior

When I connect my OpenVPN, above starts to take ~12 seconds which causes all sorts of trouble

![image](https://user-images.githubusercontent.com/10462438/108885136-180d2100-7610-11eb-9249-6f475f89cbdd.png)

# Targets with this issue

Ultimate target would be to get WSL automatically use the host side DNS settings provided by any VPN setup and without needing any special configuration or hacks (e.g. runtime resolv.conf updaters) on the Ubuntu side.

Since the DNS resolving mechanism is a black box, I would appreciate any documentation or hints regarding how it is supposed to work or how to debug this further.

![image](https://user-images.githubusercontent.com/10462438/108951148-23903480-7670-11eb-834a-6bc10c2e2d56.png)

**Comment by lassiniemisto** [comment]
As said, I am available for further debugging if I get any guidance or information how the different services should interact.

**Comment by lassiniemisto** [comment]
Still reproduces with windows build 10.0.19042.868

**Comment by ProximaB** [comment]
I also have stumbled on this issue. If you need any insights into that problem, please tell me what kind of information you would like me to provide.

**Comment by lassi-niemisto** [comment]
I am currently using OpenVPN open source edition instead of Sophos / OpenVPN Connect, it works without trouble.
