### ISSUE TITLE
unable to run windows command from wsl2

### ISSUE THREAD

**Issue by klever1988** [microsoft/WSL#6588]
![image](https://user-images.githubusercontent.com/56048681/109214948-717e7700-77ed-11eb-8e07-15685d80675e.png)

![image](https://user-images.githubusercontent.com/56048681/109215073-9d016180-77ed-11eb-92e6-b1e512711c32.png)

$PATH is right, wslinterop is enabled,
only exit code 1 is returned when I tried to run any windows exe

long time ago I had done a release upgrade from ubuntu-18 to ubuntu-20 inside wsl, but I am not sure if it's which cause this issue.

I tried to install fresh ubuntu-20/debian instances from MicrosoftStore, and both of them worked.

Dose anyone know why?

**Comment by therealkenc** [comment]
If you like you can post a link to a [gist](https://gist.github.com/) of the output from `strace -f -o notepad.strace notepad.exe`, as well as the missing Windows build version and `cat /proc/version` output from the template, as well as `wsl.exe -l -v`. The trace might show something glaring, but it is a long shot. Given that the problem does not manifest on a fresh install, there is no easy way (that I can think of anyway) to identify what might be different between the userland in your distro that fails and the distos that does not fail. Wild ass guess, post the output of `env | grep WSL_" on the distro that fails.

**Comment by klever1988** [comment]
Thanks for the reply, here is the info

https://gist.github.com/klever1988/0997193a25380c427b56bbbd8d7bef25

![image](https://user-images.githubusercontent.com/56048681/109235215-3473ae00-7808-11eb-96c9-a3d7998ba9c6.png)

**Comment by therealkenc** [comment]
Thanks for the `strace` log, it does show a fail:

```
8325  access("/run/WSL/8322_interop", F_OK) = -1 ENOENT (No such file or directory)
8325  open("/proc/8322/stat", O_RDONLY) = 5
8325  readv(5, [{iov_base="", iov_len=0}, {iov_base="8322 (strace) S 8 8322 8 34816 8"..., iov_len=1024}], 2) = 315
8325  close(5)                          = 0
8325  access("/run/WSL/8_interop", F_OK) = -1 ENOENT (No such file or directory)
8325  open("/proc/8/stat", O_RDONLY)    = 5
8325  readv(5, [{iov_base="", iov_len=0}, {iov_base="8 (bash) S 7 8 8 34816 8322 4210"..., iov_len=1024}], 2) = 321
8325  close(5)                          = 0
8325  access("/run/WSL/7_interop", F_OK) = -1 ENOENT (No such file or directory)
8325  open("/proc/7/stat", O_RDONLY)    = 5
8325  readv(5, [{iov_base="", iov_len=0}, {iov_base="7 (init) S 6 6 6 0 -1 4210752 14"..., iov_len=1024}], 2) = 167
8325  close(5)                          = 0
8325  access("/run/WSL/6_interop", F_OK) = -1 ENOENT (No such file or directory)
```

On WSL2, you should have `WSL_INTEROP` assigned to a socket in `/run/WSL`. On your working ("fresh") WSL2 distros, it will look something like:

![image](https://user-images.githubusercontent.com/7049700/109251508-779a3680-77a0-11eb-9d24-f85f7b5b425c.png)

On your `Ubuntu` distro, the `WSL_INTEROP` environment variable is not set. I can't tell you why, but you might be able to differentiate between it not getting set by `/init` and it (somehow) getting clobbered from inside the `Ubuntu` distro by trying:

![image](https://user-images.githubusercontent.com/7049700/109252573-c2b54900-77a2-11eb-89fe-2a9c313b3128.png)

What it should be set to is the highest PID `/init` from within the distro. Like:

![image](https://user-images.githubusercontent.com/7049700/109253401-90a4e680-77a4-11eb-91b6-1e083a8d54b3.png)

You can set the variable to `/run/WSL/NN_interop` by hand as an experiment, which will probably get interop running (fleetingly). But the question remains why it is not set (or gets clobbered) in the first instance.

**Comment by DHowett** [comment]
Have you followed one of the unrecommended guides on the internet for using “systemd” or “systemd-nspawn” inside WSL? This can cause trouble with the initial WSL environment being discarded.

**Comment by therealkenc** [comment]
Yeah, [this](https://github.com/microsoft/WSL/issues/994#issuecomment-643460881). Thanks Dustin.

**Comment by klever1988** [comment]
Thanks.


![image](https://user-images.githubusercontent.com/56048681/109394424-e672bd80-7961-11eb-9c61-de58e20562a3.png)
![image](https://user-images.githubusercontent.com/56048681/109394465-14580200-7962-11eb-890a-568cea7128fc.png)

There is no values to set variables, I think I have to destroy this instance...
