### ISSUE TITLE
wsl2 kernel not probing scsi disks asynchronously cause a slow booting

### ISSUE THREAD

**Issue by peigongdsd** [microsoft/WSL#6594]
actually not a feature or a bug. Wsl 2 kernel provided by Microsoft doesn't seems to have the switch "asynchronously probing scsi disks" in kernel config on which has caused a booting slow-down for about 0.4 seconds. Maybe turn it on will somehow improve experience.

**Comment by therealkenc** [comment]
Assume the ask is `CONFIG_SCSI_SCAN_ASYNC`. Interested parties should try (a) compiling a custom [kernel](https://github.com/microsoft/WSL2-Linux-Kernel), (b) confirm it boots, (c) confirm it helps.

![image](https://user-images.githubusercontent.com/7049700/109711131-5f853700-7b53-11eb-95f4-37ed91803823.png)

**Comment by Macmee** [comment]
my boot time in wsl2 is 3 seconds and I identified this as a ~450ms slowdown too on my i7 SP8
