### ISSUE TITLE
vEthernet (WSL) accessible via localhost after disabling.

### ISSUE THREAD

**Issue by sorabh86** [microsoft/WSL#6596]
If you disable vEthernet(WSL) from Network connection on Windows 10, still you can connect to http://localhost to apache server running on Ubuntu 20.04 but you cannot access it by IP address of subsystem Ubuntu.

# Environment

```none
Windows build number: [run `cmd.exe /c ver`]
Microsoft Windows [Version 10.0.19042.804]

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Release:        20.04

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

1. Open control Panel
2. Network and Internet
3. Network and Sharing Center -> Change adapter settings.
4. Right click on vEthernet (WSL) and disable.
5. open cmd run `ipconfig` verify no Virtual NAT is available.
6. run wsl to login to Ubuntu
7. `ip a | grep eth0` -> eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.21.61.6/20 brd 172.21.63.255 scope global eth0
8. run `sudo service apache2 start`
8. open web browser. 
9. go to url http://172.21.61.6 ->ERR_CONNECTION_TIMED_OUT
10. go to url http://localhost -> Status 200: Content of index.html page.

What is meaning of this behavior? 
It means there is two NAT one is used for accessing localhost another for ip address access?

**WSL logs**: 

#  Expected behavior

If we disable vEthernet (WSL) there will no connection between host and WSL, If there are two different vEthernet one for IP and another for localhost then they must be listed.

# Actual behavior

**Comment by therealkenc** [comment]
What is your use case (what you are trying to do)?

**Comment by sorabh86** [comment]
I was just trying to building a network between micro services using docker containers.
Accidently, found this behavior. Those are messing with services running on windows on port 80 and different containers on Ubuntu 20.04, in that process, i thought, why don't i disable this network instead of shutting down whole linux subsystem. That didn't worked, i am still accessing wrong page, then i used docker container ip address for correct page.  
It was really surprise virtual LAN was disabled, but you can access it in priority on localhost running application, nginx server on windows 10 port 80 have less priority over apache server running on subsytem have greater priority even if your vLAN is disabled.

**Comment by therealkenc** [comment]
You can disable localhost forwarding in [`.wslconfig`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wsl-2-settings). The feature is enabled by default.

**Comment by sorabh86** [comment]
I follow requirements found in following page [.wslconfig](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
create a file .wslconfig for global configuration in c:\User\ssora\.wslconfig
```# Enable extra metadata options by default
[automount]
enable=false

[wsl2]
memory=4G
localhostForwarding=false
```
save & close.

In powershell
PS C:\Users\ssora> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
PS C:\Users\ssora> wsl --shutdown
PS C:\Users\ssora> wsl
sorabh86@sos-pc:/mnt/c/Users/ssora$ top
```
top - 22:36:20 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.2 sy,  0.0 ni, 99.6 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  12686.0 total,  12555.7 free,     63.5 used,     66.8 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used.  12441.2 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0     892    544    484 S   0.0   0.0   0:00.17 init
    8 root      20   0     892     76     16 S   0.0   0.0   0:00.00 init
    9 root      20   0     892     76     16 S   0.0   0.0   0:00.00 init
   10 sorabh86  20   0   13592   8520   3268 S   0.0   0.1   0:00.07 bash
  204 sorabh86  20   0   10876   3648   3132 R   0.0   0.0   0:00.00 top
```
Still 12G of total memory used
Also i can access running apache webserver of ubuntu with url http://localhost/ not the nginx server running on windows 10.

May be those are upcoming features or improvements, those will be working with some beta version.

**Comment by therealkenc** [comment]
Could not reproduce here. Possible the problem is that `[automount]` is not a `.wslconfig` section.

![image](https://user-images.githubusercontent.com/7049700/110010133-d4cb4600-7cd2-11eb-9e00-c634209a27cf.png)

**Comment by sorabh86** [comment]
This is working correctly now, .wslconfig file contains some hidden special characters in the file.
![image](https://user-images.githubusercontent.com/1220531/110098437-35877b00-7dc6-11eb-99fd-7055120404fe.png)
![image](https://user-images.githubusercontent.com/1220531/110098484-459f5a80-7dc6-11eb-8a3e-79290aed41f3.png)
I create new file and it works.
Problem was related to Window PowerShell Command
![image](https://user-images.githubusercontent.com/1220531/110098772-8f884080-7dc6-11eb-8673-368a4adde1c9.png)
I have used for generating .wslconfig file
![image](https://user-images.githubusercontent.com/1220531/110099063-e261f800-7dc6-11eb-9d1e-930c1262bde8.png)
