### ISSUE TITLE
Windows can not access C:\Program Files\WindowsApps\CanonincalGroupLimited.Ubuntu2...

### ISSUE THREAD

**Issue by slim-hmidi** [microsoft/WSL#6599]
# Environment

```none
Windows build number: 18363.1379
Your Distribution version: ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: wsl2
```

# Steps to reproduce

**WSL logs**: 

After the update of the windos to version 1909, the docker I used to work with (v 2.3.0) does not work and there was errors while launching it, I upgraded to version 3.1.0. I downloaded Ubuntu 20.04 manually following this link: https://docs.microsoft.com/en-us/windows/wsl/install-manual#installing-your-distro

#  Expected behavior

The ubuntu distribution should be launched successfully.
# Actual behavior

The distribution is not launched and I got this error:
![network_error](https://user-images.githubusercontent.com/31925861/109540213-73cd2380-7ac2-11eb-9df9-8112d4d670dd.PNG)

There is no folder windowsApps under Program files.

**Comment by Biswa96** [comment]
Try this type of manual installation https://docs.microsoft.com/en-us/windows/wsl/install-on-server 😄

**Comment by Biswa96** [comment]
Try this type of manual installation https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Comment by slim-hmidi** [comment]
does not fix the issue
