### ISSUE TITLE
WSL1 many wsl.exe instances persist after wsl.exe --shutdown

### ISSUE THREAD

**Issue by dacid44** [microsoft/WSL#6600]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.804]
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: Mainly WSL1 but WSL2 may be involved
```

# Steps to reproduce

I upgraded my WSL installation (after enabling the virtual machine platform) using `wsl --set-version Ubuntu 2`, then after learning of the differences in networking I decided to downgrade back to WSL1 using `wsl --set-version Ubuntu 1`. Both of these caused high memory usage, as I would expect (based on that it's copying and processing a lot of data and based on reading posts elsewhere.) However it's been approximately a week and I've restarted my computer multiple times since then and my regular memory usage has not dropped below 90% since then, despite no processes in Task Manager using significant memory (I have 16 GB installed):
![image](https://user-images.githubusercontent.com/53133576/109540437-0b615080-7a88-11eb-8b88-47afa3270e22.png)
Today I tried using the SysInternals RamMap utility, which reports that there are possibly hundreds of "wsl.exe" processes all using memory (this screenshot is after running `wsl --shutdown`, and `htop` within wsl shows only the bare minimum processes, none even registering above 0.1% usage:
![image](https://user-images.githubusercontent.com/53133576/109540784-904c6a00-7a88-11eb-85f4-275d2e0efc3b.png)
![image](https://user-images.githubusercontent.com/53133576/109540844-a6f2c100-7a88-11eb-846a-62a975d8d3d9.png)

If this can't be solved here I would really appreciate help or direction on where else I should post this, as my computer is nearing becoming unusably slow and especially development apps are near impossible to run.

Thanks a ton!

To clarify: I am now running WSL 1.

**WSL logs**: 

# Expected behavior

WSL should not be using this much memory especially after it is shut down

# Actual behavior

I'm experiencing extremely high memory usage, most likely by WSL, even after running `wsl --shutdown`

**Comment by Biswa96** [comment]
There are ton of issues here with high memory usage. General workaround is to use `wsl.exe --shutdown` which will close the VM and the memory will be freed. In Task Manager, try to use the details tab to see the actual process which is hoarding memory.

**Comment by dacid44** [comment]
@Biswa96 That is exactly the problem. Those screenshots (save for `htop`) were_after_ running `wsl --shutdown`. The Task Manager details tab gave no more insights.

**Comment by Kleptine** [comment]
I just tracked down this exact same issue on my machine. I have thousands of lingering wsl.exe entries which have bloated my Page Table to over 8Gb:
<img width="1317" alt="RAMMap_6zArbBqNlW" src="https://user-images.githubusercontent.com/1078792/184242051-180ba48c-4c06-4ba0-8af4-8090f6ef4cec.png">
![image](https://user-images.githubusercontent.com/1078792/184242029-ef95f26e-eb79-4024-a1ee-107d49eb0682.png)

The scroll bar there is very tiny, and nearly every single entry is wsl.exe. Most of these processes are no longer running, but still taking up RAM.

**Comment by Kleptine** [comment]
Update: With some help from Bruce, I tracked down the offending process. Docker's daemon was still holding onto handles within all of these dead processes. Killing it resolves the issue for me.
<img width="903" alt="Taskmgr_fVX2r4svcx" src="https://user-images.githubusercontent.com/1078792/184242810-ca1df16e-9f1c-40f0-8cd0-50437a349343.png"
<img width="676" alt="Taskmgr_KUQ3tV2JGl" src="https://user-images.githubusercontent.com/1078792/184242815-73a92725-cd43-4b26-b5da-5079775ae5f1.png">
>

**Comment by mwm-twx** [comment]
There is a docker desktop issue for the growth of handles on the backend process: https://github.com/docker/for-win/issues/12916
