### ISSUE TITLE
WSL2 - Temporary failure in name resolution

### ISSUE THREAD

**Issue by brvaland** [microsoft/WSL#6601]
Hi, 

I have installed WSL2 and Ubuntu 20.04 on Windows 10 (1909 - OS Build 18363.1379) and having issues with DNS. I tried the ping command `ping google.com` and got an error `ping: google.com: Temporary failure in name resolution`.

I did try few things but no luck

- Updated Windows Subsystem for Linux Update - 5.4.91
- Configured wsl.conf & resolv.conf as below and restarted with `wsl --shutdown` :

```
administrator@TEMPPC:/etc$ cat wsl.conf
[network]
generateResolvConf = false 
```

```
administrator@TEMPPC:/etc$ cat resolv.conf
nameserver 8.8.8.8
nameserver 1.1.1.1
```
- ping to nameserver works fine
```
administrator@TEMPPC:/etc$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=115 time=39.9 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=115 time=21.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=115 time=20.7 ms
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 19.394/24.707/39.909/7.651 ms
```
```
administrator@TEMPPC:/etc$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=57 time=40.9 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=57 time=29.1 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=57 time=24.1 ms
--- 1.1.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 16.177/27.574/40.872/8.958 ms
```

I have Symantec Endpoint Security and Cisco AnyConnect for VPN, I tried to connect/disconnect from VPN and that did not make any difference to dns resolution.

Finally i tried to set Ubunto distro version **WSL 1** and that works fine so not sure why WSL 2 fails.

Any suggestion will be appreciated.

**Comment by therealkenc** [comment]
Landing zone for Anyconnect /dupe #4277 (plus #5068 etc).

**Comment by lKrayola** [comment]
Same problem, one day suddenly DNS inside wsl2 stopped working, but pings to ips work fine

**Comment by chuck-wood** [comment]
> Same problem, one day suddenly DNS inside wsl2 stopped working, but pings to ips work fine

Look at https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2 for a workaround.
