### ISSUE TITLE
Specified network name is no longer available

### ISSUE THREAD

**Issue by trampboy495** [microsoft/WSL#6605]
I was using Ubuntu 16.04, quite some time on my Windows 10 pc. However recently when I tried to open it, it prompted me Specified network is no longer available, press any key to continue. I uninstall it and install ubuntu 20.4, but still, the same problem persists. I am attaching a screenshot for better understanding .
![Screenshot (46)](https://user-images.githubusercontent.com/61736652/109599610-7c187380-7b41-11eb-836b-11f466017ddc.png)

**Comment by therealkenc** [comment]
/dupe #6378. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in #6378.
