### ISSUE TITLE
Attempting to install WSL 5.4.91 fails

### ISSUE THREAD

**Issue by wi-ry** [microsoft/WSL#6613]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21322.1000]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-21322-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1000-Microsoft Sat Feb 20 16:51:00 PST 2021
```

# Steps to reproduce
Try to update to latest version of WSL (5.4.91).

**WSL logs**: 
https://aka.ms/AAbcxoh

#  Expected behavior
WSL updates successfully

# Actual behavior

From command line:
```none
wsl --update
Checking for updates...
Downloading updates...
Installing updates...
Fatal error during installation.
```

From Windows Update:
```none
0x80070643
```

From wsl_update_x64.msi:
![image](https://user-images.githubusercontent.com/9650258/109762649-ce8b7b80-7ba5-11eb-8b52-38250af2958d.png)

**Comment by MrAusnadian** [comment]
I ended up solving this by doing the following. Sharing here in case others have similar issues.

1. Download the MSI installer for WSL Update 4.19.128 from http://download.windowsupdate.com/d/msdownload/update/software/updt/2020/08/wsl_update_x64_05ec8d8e559e59127779754fc202b1fd9a3b87f8.cab
2. Extract the installer from .cab file
3. Right-click the WSL Update 4.19.128 installer and choose uninstall
4. Go through (un)installer
5. Download WSL Update 5 installer from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
6. Go through the installer
7. All done!

**Comment by kinglionsz** [comment]
the same error:

OS Name:                   Microsoft Windows 10 Enterprise Insider Preview
OS Version:                10.0.21327 N/A Build 21327

wsl --status
Default Distribution: kali-linux
Default Version: 2

Windows Subsystem for Linux was last updated on 2020/12/16
WSL automatic updates are on.

The WSL 2 kernel is in the rollback state and is using a previous kernel version.
Kernel version: 4.19.128

linux 5.4.91 update install error:(0x80070643)

![Screenshot 2021-03-05 203212](https://user-images.githubusercontent.com/51827261/110116449-7b5a3880-7df2-11eb-903f-bbb8506eafb5.png)
![Download error - 0x80070643 Screenshot 2021-03-05 182927](https://user-images.githubusercontent.com/51827261/110116453-7dbc9280-7df2-11eb-9d04-0b38d07a82c3.png)

**Comment by renanlido** [comment]
> I ended up solving this by doing the following. Sharing here in case others have similar issues.
> 
> 1. Download the MSI installer for WSL Update 4.19.128 from http://download.windowsupdate.com/d/msdownload/update/software/updt/2020/08/wsl_update_x64_05ec8d8e559e59127779754fc202b1fd9a3b87f8.cab
> 2. Extract the installer from .cab file
> 3. Right-click the WSL Update 4.19.128 installer and choose uninstall
> 4. Go through (un)installer
> 5. Download WSL Update 5 installer from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
> 6. Go through the installer
> 7. All done!

It worked for me! Thanks!

**Comment by lwu-ox** [comment]
> I ended up solving this by doing the following. Sharing here in case others have similar issues.
> 
> 1. Download the MSI installer for WSL Update 4.19.128 from http://download.windowsupdate.com/d/msdownload/update/software/updt/2020/08/wsl_update_x64_05ec8d8e559e59127779754fc202b1fd9a3b87f8.cab
> 2. Extract the installer from .cab file
> 3. Right-click the WSL Update 4.19.128 installer and choose uninstall
> 4. Go through (un)installer
> 5. Download WSL Update 5 installer from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
> 6. Go through the installer
> 7. All done!

My installed WSL Update version is 4.19.104, how to find the relevant oringinal install package link in step 1. please?

**Comment by will-gluwa** [comment]
I got it from https://www.catalog.update.microsoft.com/Search.aspx?q=wsl but they seem to have hidden older versions now.

Check out https://github.com/microsoft/WSL/issues/5529 and hopefully that'll help you get updated.

**Comment by Rougnt** [comment]
https://github.com/microsoft/WSL/issues/5529#issuecomment-740010393
I use this method to uninstall.

**Comment by wi-ry** [comment]
Gonna close this issue. It's no longer a problem for me after using the workaround I suggested here:
https://github.com/microsoft/WSL/issues/6613#issuecomment-789481722
