### ISSUE TITLE
WSL2 breaks OpenVPN connection

### ISSUE THREAD

**Issue by poul1x** [microsoft/WSL#6614]
# Environment

```none
Windows build number: [Version 10.0.19041.804]
Your Distribution version: [Debian: 10,  Ubuntu: 20.04]
The issue is on WSL 2 and/or WSL 1: [WSL2]
OpenVPN GUI version: 11.12.0.0
```

# Steps to reproduce

1. Enable wsl
2. Install fresh version of Ubuntu / Debian
3. Install OpenVPN and connect to vpn server. Verify all is ok
4. Launch wsl
5. (Optional) run `dig` command to ensure dns can be resolved:

```none
user:~$ dig <dns-address>
; <<>> DiG 9.16.1-Ubuntu <<>> <dns-address>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41404
;; flags: qr rd ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; ANSWER SECTION:
server1.    0       IN      A       ip1
server2.    0       IN      A       ip2
server3.    0       IN      A       ip3
```
6.  Run curl: `curl <dns-address>` <- **stucks**

```
curl -vvv <dns-address>
*   Trying <ip>...
* TCP_NODELAY set
* Expire in 149974 ms for 3 (transfer 0x55e2821def90)
* Expire in 200 ms for 4 (transfer 0x55e2821def90)
* Connected to <dsn-address> (<ip>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 300197 milliseconds with 0 out of 0 bytes received
* Closing connection 0
```

7.  Refresh the page of service under vpn (browser) <- **ERR_CONNECTION_TIMED_OUT**
8.  VPN connection is broken and I need to reconnect. But I still can `curl google.com` from WSL

**WSL logs**: 

https://drive.google.com/file/d/1Ty3ckbB_NzClD2KrqhiTaZx5-zH2pay_/view?usp=sharing

#  Expected behavior

Curl can fetch page contents from service under VPN.

# Actual behavior

Curl stucks when it tries to fetch page contents. And VPN connection is broken

# Additional info

I've tried to do the same on WSL1. After some manipulations on `resolv.conf` I was able to connect to VPN server and fetch the page. So, it's not an WSL1 issue.

**Comment by poul1x** [comment]
Disabling firewall does not help

**Comment by therealkenc** [comment]
Similar #4517
