### ISSUE TITLE
Change the file permission, owner, group in Windows file system

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/WSL#6618]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`]: Microsoft Windows [Version 10.0.19042.804]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]: Release:        18.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

1. Open PowerShell terminal
2. run 'bash' and switch to WSL mode.
3. See below commands; I'd like to change the file permission to 766 or owner/group to my user. But each command returns 0, but no change. In WSL termianl, chmod, chown and chgrp commands are working well.

juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ whoami
juhlee
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ ls
dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ ls -al
total 4
drwxr-xr-x 1 root root 4096 Mar  3 16:59 .
drwxr-xr-x 1 root root 4096 Mar  3 17:00 ..
-rw-r--r-- 1 root root 1724 Mar  3 16:59 dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ chmod 766 dump.json
chmod: changing permissions of 'dump.json': Operation not permitted
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ sudo chmod 766 dump.json
[sudo] password for juhlee:
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ echo $?
0
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ ls -al
total 4
drwxr-xr-x 1 root root 4096 Mar  3 16:59 .
drwxr-xr-x 1 root root 4096 Mar  3 17:00 ..
-rw-r--r-- 1 root root 1724 Mar  3 16:59 dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ sudo chown juhlee dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ echo $?
0
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ ls -al
total 4
drwxr-xr-x 1 root root 4096 Mar  3 16:59 .
drwxr-xr-x 1 root root 4096 Mar  3 17:00 ..
-rw-r--r-- 1 root root 1724 Mar  3 16:59 dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ sudo chgrp juhlee dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$ ls -al
total 4
drwxr-xr-x 1 root root 4096 Mar  3 16:59 .
drwxr-xr-x 1 root root 4096 Mar  3 17:00 ..
-rw-r--r-- 1 root root 1724 Mar  3 16:59 dump.json
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases/scratch/pods$

https://gist.github.com/juhlee-microsoft/78bbe953c75e8fb705a29ba51154e324

**WSL logs**: 

#  Expected behavior
File permission changes to 766
File owner changes to juhlee
File group changes to juhlee

# Actual behavior
File permission, owner and group do not change, but bash command result '0'

**Comment by therealkenc** [comment]
You need to enable metadata in [wsl.conf](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options). It is off by default. Looks something like:

![image](https://user-images.githubusercontent.com/7049700/109913727-55525e00-7c63-11eb-9932-745a347738e5.png)

**Comment by juhlee-microsoft** [comment]
I don't know why I don't have the conf file. Everything is from the official installation.

PS C:\Users\juhlee\source\Repo\Azure-Dedicated-AVS-Releases> wsl --shutdown
PS C:\Users\juhlee\source\Repo\Azure-Dedicated-AVS-Releases> wsl
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases$ ls -al /etc/wsl.conf
ls: cannot access '/etc/wsl.conf': No such file or directory
juhlee@MININT-NIMI2CK:/mnt/c/Users/juhlee/source/Repo/Azure-Dedicated-AVS-Releases$

**Comment by therealkenc** [comment]
Create the file with `sudo nano /etc/wsl.conf` (or similar). Changes need a `wsl --shutdown` to take.

**Comment by juhlee-microsoft** [comment]
Thanks. This works. I can change the file owner/group to non-root.
