### ISSUE TITLE
CUDA and NVIDIA Driver error in WSL2

### ISSUE THREAD

**Issue by bahetibhakti** [microsoft/WSL#6623]
# Environment

```none
Windows build number: 21327
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

I had installed WSL and configured CUDA and NVIDIA drivers. Everything was running perfectly fine and the code successfully getting executed on GPU. Meanwhile, WSL got closed automatically and now is showing error "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

Then I re-installed the NVIDIA driver and CUDA by following instructions on https://docs.nvidia.com/cuda/wsl-user-guide/index.html . But when I execute "./BlackScholes", I get an the error: 
![image](https://user-images.githubusercontent.com/6376680/109989652-b23b2c00-7cd6-11eb-88ca-d4a9fa53ba7a.png)

Nvidia-smi.exe is working fine
![image](https://user-images.githubusercontent.com/6376680/109990025-06dea700-7cd7-11eb-82ad-d6a75fbf4d9b.png)

#  Expected behavior
When I run the ./BlackScholes, I should get output like
![image](https://user-images.githubusercontent.com/6376680/109989801-d565db80-7cd6-11eb-9924-5b31beb69a4b.png)

# Actual behavior
getting above posted error in ./BlackScholes and " No NVIDIA derivers found error" while executing program on GPU

Has anyone encountered such issue? Kindly help

**Comment by tobiaskohlbau** [comment]
This is a known issue, @craigloewen-msft  posted it yesterday over at #6617

**Comment by craigloewen-msft** [comment]
/dupe #6617 

This is known and fixed internally, we are working on getting a build out for it! More details in the linked post. : )
