### ISSUE TITLE
WSL1 works, WSL2 timesout

### ISSUE THREAD

**Issue by Lauren-Buchholz-Moxe** [microsoft/WSL#6627]
# Environment

Windows build number: [run `cmd.exe /c ver`]
Microsoft Windows [Version 10.0.19043.844]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
20.04, but cannot get into Ubuntu to run this.
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
WSL2 only.  machines work fine in WSL1, but I cannot install a WSL2 image or upgrade an existing one.

# Steps to reproduce

```
PS C:\Users\lbuchholz> wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
PS C:\Users\lbuchholz> cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.844]
PS C:\Users\lbuchholz> wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation timed out because a response was not received from the virtual machine or container.
```

**WSL logs**: 
https://aka.ms/AAbdx7q

#  Expected behavior
WSL2 machine installs from store or WSL2 machine upgrades.  Both give the same error about not being able to connect to virtual machine or container.

# Actual behavior

sits for 30 seconds, and then gives this error

I have tried completly uninstall the linux subsystem, Ubuntu, Hyper-V, Virt Platform etc.

**Comment by therealkenc** [comment]
Thanks for linking logs; appreciated.

> WSL2 machine installs from store or

If you set the default version to WSL2 and then install a different distribution name (say [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6#activetab=pivot:overviewtab) vs [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab)) from the Store, does it also timeout? Setting the default version looks like:
```
PS C:\> wsl.exe --set-default-version 2
```
Afterwards install the new distro, which (assuming it succeeds) will be WSL2.

**Comment by Lauren-Buchholz-Moxe** [comment]
I fresh install gives this error, which I think is the same underlying problem.

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.

Press any key to continue...

**Comment by therealkenc** [comment]
Thanks, getting an error code is good. Capturing that error in [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) would be useful if you can. The error code gets a hit on open #5194.

**Comment by Lauren-Buchholz-Moxe** [comment]
I'll take a look at 5194, but I did a record of the actual process if that gives you anything useful.

https://aka.ms/AAbdxh0

**Comment by Lauren-Buchholz-Moxe** [comment]
Yea, looks like it may be the same issue as 5194

**Comment by Lauren-Buchholz-Moxe** [comment]
Just checking back to see if there is anything else I can do to troubleshoot
