### ISSUE TITLE
Default-jdk doesn´t compile

### ISSUE THREAD

**Issue by ricardosantos9521** [Microsoft/WSL#663]
Cannot compile a java file with the default-jdk package (the package ecj-jdk work)

Expected results: after a the comand "javac file.java" the program compile or give the errors of file

Actual results: No error appear and the terminal crash

Build 14390

Ps: The package default-jdk Works on build 14366 (if I'm not mistaken).

**Comment by sundhaug92** [comment]
Do you have an strace?

**Comment by ricardosantos9521** [comment]
what do you mean? you want a strace of the comand a execut?

**Comment by ricardosantos9521** [comment]
#
[thread 140008803600128 also had an error]# A fatal error has been detected by the Java Runtime Environment:

#
#  Internal Error (safepoint.cpp:325), pid=391, tid=140008592508672
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.6
# Distribution: Ubuntu 14.04 LTS, package 7u101-2.6.6-0ubuntu0.14.04.1
# Core dump written. Default location: /mnt/c/Users/ricar/OneDrive/dev/java/core or core.391
#
# An error report file with more information is saved as:
# /mnt/c/Users/ricar/OneDrive/dev/java/hs_err_pid391.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
fish: Job 4, 'strace -o ola.txt -c javac Prog…' terminated by signal SIGABRT (Abort)

**Comment by ricardosantos9521** [comment]
[hs_err_pid391.txt](https://github.com/Microsoft/BashOnWindows/files/367615/hs_err_pid391.txt)

**Comment by tjfryan** [comment]
I'm running into the same issue when I try to use the scala compiler or repl

**Comment by tara-raj** [comment]
Closing stale issue. If you run into this again please reopen.
