### ISSUE TITLE
WSL2 : Doesnt get 192.168.x.x IP post upgrading to 20H2

### ISSUE THREAD

**Issue by rajeshvt** [microsoft/WSL#6631]
Environment

Windows 10 Version 20H2 (OS Build 19042.844)
WSL2 Ubuntu 20.04

Issue: 

1. WSL2 doesnt get 192.168.x.x IP post upgrading to 20H2. 
2. Used to work with workaround mentioned in https://github.com/microsoft/WSL/issues/5764 on ver 1903.

Steps to reproduce

1. Start WSL2 from Windows 10 in powershell or Windows Terminal.
2. The IP on the WSL2 will now be 172.30.x.x.
3. WSL2 doesnt ping/communicate with internet or intranet (192.168.x.x).
4. Applied the fix mentioned by @josmartin in https://github.com/microsoft/WSL/issues/5764 , also doesnt work.

**Comment by therealkenc** [comment]
/dupe #5764 ref Ref #5275 ➡️ #4601 ➡️ #4210. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in #5764. Also please identify any third-party networking software that has been installed on Windows.
