### ISSUE TITLE
Executable file attribute not coming across \\wsl$ network share

### ISSUE THREAD

**Issue by riverar** [microsoft/WSL#6634]
# Environment

```none
Windows 10 10.0.19042.844
Ubuntu 20.04
Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC))
#1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

1. Install [QT Creator](https://download.qt.io/official_releases/qtcreator/4.14/4.14.1/qt-creator-opensource-windows-x86_64-4.14.1.exe) for Windows, take defaults
2. Open QT Creator and navigate to Tools > Options > Kits and click the Compilers tab
3. Click the Add > GCC > C++
4. Specify `\\wsl$\Ubuntu\usr\bin\base64` as the Compiler Path
5. Observe the path is highlighted in red
6. Observe tooltip on path indicates: `"The path [...] is not an executable file"`

![image](https://user-images.githubusercontent.com/475132/110168315-db79bc00-7dab-11eb-864b-1477d24f5344.png)

**WSL logs**: https://aka.ms/AAbe0sl

#  Expected behavior

QT Creator recognizes the file is executable and lets me continue configuring the compiler toolchain.

# Actual behavior

QT Creator blocks further configuration of the compiler toolchain as it does not believe the specified file is executable. It appears that information is being lost when traversing the `\\wsl$` share.

**Comment by DHowett** [comment]
Does Windows QT Creator have the capacity to execute ELF binaries?

Wouldn’t it need to have a feature where it runs them inside a translation layer or VM ... like WSL?

**Comment by DHowett** [comment]
Like... just because the executable has the +x bit doesn’t mean that arbitrary Windows applications can _execute them_.

**Comment by riverar** [comment]
@DHowett I'm configuring QT Creator with the goal of setting up remote build steps. Sounds like this is "as designed" and I should forget about it though.

**Comment by DHowett** [comment]
Ah, that’s curious. I wonder what path format their remote build configuration expects!

**Comment by riverar** [comment]
@DHowett Not sure, to be honest. Didn't get far and not intimately familiar with the software. I'm scrapping the idea and will just install it in WSLv2 directly and X11 forward it out of the VM. Thanks for making me rethink my plan 😅

**Comment by Biswa96** [comment]
Possible options:
1. Qt Creator can call a ~backdoor~ backend in WSL side to build the job, just like VSCode or the `init` itself.
2. Qt Creator can give the job to `qmake` in WSL side then take back the built binaries in build folder.
