### ISSUE TITLE
"Your kernel headers for kernel 5.4.72-microsoft-standard-WSL2 cannot be found."

### ISSUE THREAD

**Issue by 0x14307** [microsoft/WSL#6635]
I'm trying to install a package with dpkg and I get this error:
"Error! Your kernel headers for kernel 5.4.72-microsoft-standard-WSL2 cannot be found.
Please install the linux-headers-5.4.72-microsoft-standard-WSL2 package"

How can I fix this?

**Comment by gabefair** [comment]
Can you tell us which package or information about the software you are trying to install? For example if it is a 10g lan driver that can help us narrow down the issue.

**Comment by 0x14307** [comment]
I'm trying to install Darling-DKMS.
