### ISSUE TITLE
WSL2 networking issue: unable to connect to localhost for dev server after update

### ISSUE THREAD

**Issue by teikjun** [microsoft/WSL#6638]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.804]
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```
# Issue
Previously, I ran into this issue https://github.com/microsoft/WSL/issues/6439 on build 19041.746. The issue was fixed after applying the fix detailed in https://github.com/microsoft/WSL/issues/5298#issuecomment-695181844. 

After updating to build 19041.804, the exact same problem has resurfaced.  However, the same fix (https://github.com/microsoft/WSL/issues/5298#issuecomment-695181844) did not work anymore. 

Please refer to https://github.com/microsoft/WSL/issues/6439 for the full details of this issue. To summarize, I am unable to get the frontend and backend development server working together with WSL2. When the backend development server is accessed on localhost:8080, I receive a 404 error with no other errors logged in the console. When the frontend is accessed on localhost:4200, the page is rendered, but it cannot communicate with the backend. On the other hand, I am able to set up the dev server properly on a linux VM with the exact same steps. I am unable to pinpoint the specific issue in WSL2 that is causing this problem. 

There were 2 updates that were installed together (either of which may have triggered the issue). They are:
- Lenovo - System - 15.11.29.61 (A driver update) 
- [2021-KB4601554 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Windows 10](https://support.microsoft.com/en-us/topic/february-24-2021-kb4601554-cumulative-update-preview-for-net-framework-3-5-and-4-8-for-windows-10-version-2004-windows-server-version-2004-windows-10-version-20h2-and-windows-server-version-20h2-958fff0c-783b-27b3-8a93-226f7798225a)

What could the updates have changed to cause this networking issue in wsl2? Would appreciate any advice on how to resolve this.

# Remarks
I have tried applying the suggested fixes in #4885, #4851 and #5298 - they do not resolve the issue.

**Comment by dchen327** [comment]
I'm also on 10.0.19041.804, but I can't even get anything to show on localhost. I've tried `npm run dev` for a Next.js project, and a simple Python http server, but going to `localhost:3000` or `127.0.0.1:3000` or `0.0.0.0:3000` just says it refused to connect.

Everything was working before I updated to 10.0.19041.804 I believe. I've tried toggling firewall with no effect, and my laptop doesn't have the option to disable fast startup (even after clicking `change additional settings`).

**Comment by dchen327** [comment]
I uninstalled the recent Windows update (now I'm on 19041.746), and everything is working again. I'm clueless about what broke in the update, but I guess for now just downgrade if you can?

**Comment by teikjun** [comment]
Thanks for the suggestion, I think downgrading would certainly fix the problem for now. 

I would like to stay on an updated build, so I'm still trying to find a solution to this problem. So far, I've tried updating to a more recent version (20H2 build `19042.844`), but the problem still persists.

**Comment by dchen327** [comment]
Wow. Hopefully we get a fix soon!

**Comment by teikjun** [comment]
@therealkenc Do you know if there are any updates in Windows Insider (slow ring) that may resolve this networking issue?

**Comment by dchen327** [comment]
For some reason, my localhost has broken again today (I haven't updated anything and it was working perfectly yesterday).

Is there a fix? This is incredibly annoying.

**Comment by therealkenc** [comment]
forward /dupe #6725 which has a repro.
