### ISSUE TITLE
Internet Connection Sharing (ICS) cannot be disabled

### ISSUE THREAD

**Issue by rg9400** [microsoft/WSL#6646]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`] Microsoft Windows [Version 10.0.19042.804]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] WSL 2
```

# Steps to reproduce

To reproduce, update to Windows version `19042.804`, start a WSL 2 distro and notice that ICS is running. Try to disable ICS (be warned as it can lead to BSOD). 

#  Expected behavior

I should be able to stop the ICS service and keep it disabled. I should be able to keep port 53 free on my machine even while running a WSL2 distro.

# Actual behavior

Since last week after a Windows update, ICS has been constantly running. I cannot disable the service or stop it. In fact, trying to stop it sometimes results in a BSOD. This is a problem because ICS listens on port 53, which prevents me from running something like PiHole/AdGuard. 

After some digging, I was able to figure out that if I stop Host Network Service, then ICS can safely be disabled. However, with Host Network Service disabled, WSL Distros fail to start. With it enabled, ICS is no longer able to be disabled. If WSL is not started, then also you can disable ICS, but as soon you start a WSL distro, disabling ICS is either prevented or leads to BSOD.

**Comment by Biswa96** [comment]
# Conclusion

WSL2 needs ICS service.

**Comment by rg9400** [comment]
This is new behavior that was only introduced a week ago. I had no issues keeping ICS disabled prior to that. Additionally, ICS listens on port 53, preventing any other service or container from binding to that port, neutralizing the ability to run your own DNS server. I think that if there was some network architecture change that requires ICS, does it also require ICS bind to port 53? If so, is the consequence (not allowing anything else to listen on 53), an acceptable one?

**Comment by Biswa96** [comment]
DOH? 🤔

**Comment by rg9400** [comment]
or DNS ad-filtering (pihole or adguardhome)

**Comment by tdesaules** [comment]
Hi there I have the smae strange issue I think.
Trying to run my coredns container on top of docker desktop with WSL (https://github.com/docker/for-win/issues/10601) strange thing is that I doesn't have this issue using docker desktop 3.2.0

**Comment by rg9400** [comment]
> Hi there I have the smae strange issue I think.
> Trying to run my coredns container on top of docker desktop with WSL ([docker/for-win#10601](https://github.com/docker/for-win/issues/10601)) strange thing is that I doesn't have this issue using docker desktop 3.2.0

I thought this as well, but I completely uninstalled Docker for Desktop, and I still could not fix the issue. On a restart, it was possible to disable ICS, but as soon as I started a WSL instance, ICS would turn itself back on. The issue did become noticed by me when I updated to Docker 3.2.0, but I think that was just because I might have restarted WSL after the update. It seems like something on WSL/Windows has changed that is making ICS necessary. 

Maybe ICS was required before, but it did not use to listen to port 53 as I had been able to run my container without issue for almost a year now.

**Comment by cbs-clicrdv** [comment]
I have had the same problem since installing the latest version of Docker 3.2.1 for Windows.
I use hyper-V backend on Windows 10 pro 64. I had to reinstall Docker version 3.1.0 for it to work again.

**Comment by rg9400** [comment]
Closing this issue as it is actually a Docker for Windows problem, not WSL. Indeed, it does seem like ICS is a required service for WSL to function, but that by itself is okay. The actual problem was that it was listening on port 53 (which is why we were trying to find a way to disable it), but that is not normal and is related downstream with Docker. You can follow the relevant issue here:

https://github.com/docker/for-win/issues/10601

**Comment by aogg** [comment]
+1 The same trouble.

**Comment by Spongman** [comment]
this is _not_ a docker issue. it doesn't even need to be installed to repro this. just start a wsl2 instance, and the SharedAccess service starts listening on udp/53.

please add a way to disable this. it serves no purpose and it breaks running a DNS server in wsl2.

**Comment by jurakovic** [comment]
Seven months later, is there any workaround for this? I face this issue while trying to run Pi-hole in WSL2.

**Comment by 7djs7** [comment]
Seriously, this is dumb. I'm trying to run Pi-hole in WSL2 as well and can't due to ICS listening on udp/53.

**Comment by gbzcarilla** [comment]
Is there any workaround for this?

**Comment by rmnilin** [comment]
I was able to stop ICS after setting Host Network Service's Startup type to Disabled and then stopping it.

https://learn.microsoft.com/en-us/answers/questions/3753205/(solved)-unable-to-stop-internet-connection-sharin

https://www.reddit.com/r/techsupport/comments/hjeuou/program_requires_port_67_but_in_use_by_ics_cant/
