### ISSUE TITLE
How can I connect two WSL2 instances?

### ISSUE THREAD

**Issue by AbhinavMir** [microsoft/WSL#6654]
I have a program running on a Debian Subsystem and another program running on Ubuntu Subsystem. I need to connect these two, what is the IP I need to be looking at, how can I find the IP of my device and are there any other steps I need to take?

**Comment by Biswa96** [comment]
Are those in WSL1 or in WSL2?

**Comment by AbhinavMir** [comment]
WSL2 @Biswa96

**Comment by Biswa96** [comment]
Those distribution will get same IP address as being inside same WSL2 VM.
