### ISSUE TITLE
WSL2 Kernel do not support `nftables` and causing docker failed to start up in Ubuntu 20.10+

### ISSUE THREAD

**Issue by patrick330602** [microsoft/WSL#6655]
# Environment

```none
Windows build number: 21327
Your Distribution version: Ubuntu Hirsute Hippo (development branch)
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Installing Ubuntu 20.10 (the best way is Ubuntu on Windows Community Preview)
2. installing docker from the ubuntu repository (`sudo apt install docker.io`)
3. start `dockerd`;

#  Expected behavior

`dockerd` should end up at the state `API listen on /var/run/docker.sock`

# Actual behavior

`dockerd` throws the following error:

```
 failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-1 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN: iptables v1.8.7 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain DOCKER-ISOLATION-STAGE-1
 (exit status 4))
```

# Some related stuff
related article: https://patrickwu.space/2021/03/09/wsl-solution-to-native-docker-daemon-not-starting/
related bug report: https://bugs.launchpad.net/ubuntu-wsl-integration/+bug/1908539

**Comment by WSLUser** [comment]
In the kernel config: 
```
#
# IP: Netfilter Configuration
#
CONFIG_NF_DEFRAG_IPV4=y
# CONFIG_NF_SOCKET_IPV4 is not set
# CONFIG_NF_TPROXY_IPV4 is not set
CONFIG_NF_TABLES_IPV4=y
# CONFIG_NFT_DUP_IPV4 is not set
# CONFIG_NFT_FIB_IPV4 is not set
# CONFIG_NF_TABLES_ARP is not set
# CONFIG_NF_DUP_IPV4 is not set
# CONFIG_NF_LOG_ARP is not set
CONFIG_NF_LOG_IPV4=y
CONFIG_NF_REJECT_IPV4=y
```

IPv4 is supported as shown here. Are you trying to use IPv6? There are some NAT options that aren't enabled by default also but don't seem related to your error..

**Comment by therealkenc** [comment]
/dupe #6044. There is some docker talk in #4872 ([message](https://github.com/microsoft/WSL/discussions/4872#discussioncomment-76635)).

**Comment by Unintendedz** [comment]
wsl2 ubuntu 22.04, This worked for me
```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

sudo dockerd &
```

**Comment by wooncherk** [comment]
> wsl2 ubuntu 22.04, This worked for me
> 
> ```
> sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
> sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> 
> sudo dockerd &
> ```

This saved the day! Thanks! :)

**Comment by Narc17** [comment]
> wsl2 ubuntu 22.04, This worked for me
> 
> ```
> sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
> sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> 
> sudo dockerd &
> ```

Thanks a lot. wsl2 ubuntu 22.04 with Docker Desktop in Windows 10 Enterprise 21H2 here.
You saved my day! :D

**Comment by jlegido** [comment]
It also works in Debian distro

**Comment by bolodecenouracomcafe** [comment]
Thanks! Works for me too with Windows 11 Home 22H2, WSL version 2 with Ubuntu


> wsl2 ubuntu 22.04, This worked for me
> 
> ```
> sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
> sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> 
> sudo dockerd &
> ```

**Comment by Biswa96** [comment]
This seems to be an old issue. dockerd works without those iptables commands in newer Linux distributions with WSL from Windows Store.

**Comment by drehermi** [comment]
@Biswa96 : can you please be more precise? 

I mean I'm using the following versions of "Debian" and can't get it running:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux md1u9ddc 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 GNU/Linux
```

To be more precise the `iptables` command gives the following error:
```
$ sudo iptables-legacy -L
iptables v1.8.7 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

But there seems to be no newer kernel version:
```
wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.102.1
```

 Michael

**Comment by Biswa96** [comment]
From the output of `uname -a` in your Debian distribution, it seems that it is still running in WSL1 environment. You can confirm that by running `wsl.exe -l -v` command. If yes, try to convert the distribution with `wsl.exe --set-version Debian 2` command.

**Comment by drehermi** [comment]
@Biswa96: thanks, exactly that was the problem, now it is working!

I was installing WSL2 and assuming that all distributions would then run wsl2 but as you said the Debian one was still running WLS1. I was not aware that it is possible to mix WSL2 and WSL1.

**Comment by Biswa96** [comment]
> The output of `wsl -d Debian --status` is misleading...

That command is not valid or at least it does not work the way you intended. The `--status` option is not distribution specific, just like `--help` or `--version` etc. The `wsl.exe --status` command would show the same output.

**Comment by randuladela** [comment]
> sudo dockerd &

Whoever you are ,you saved my day,thanks

**Comment by liuya1s** [comment]
> wsl2 ubuntu 22.04, This worked for me
> 
> ```
> sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
> sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> 
> sudo dockerd &
> ```

Thanks a lot,  docker is running！

**Comment by jlriven** [comment]
using systemctl start docker mistake:
![Image](https://github.com/user-attachments/assets/9973d01e-121c-4465-959d-e8c684e2eee8)

**Comment by StephanVoelkl** [comment]
works for me as well. can highly recommend that fix

**Comment by nishaalnaseer** [comment]
i had this issue as wel on pop os 22.04 kernel version 3.16

```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

this diddnt work at first but after some shenanigans on messing with kernel modules and a reboot it worked

here is a part of my bash history
```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo systemctl start docker
sudo systemctl status docker
sudo journalctl -u docker -f
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
sudo systemctl start docker
sudo systemctl stop docker
sudo systemctl start docker
sudo journalctl -u docker -f
sudo iptables --version
sudo ip6tables --version
sudo modprobe iptable_nat
sudo modprobe iptable_filter
modprobe
lsmod | grep iptable
uname -r
ls -la /lib/modules/$(uname -r)/kernel/net
dockerd
sudo dockerd &
sudo update-alternatives --set iptables /usr/sbin/iptables
iptables --version
sudo update-alternatives --set iptables /usr/sbin/iptables-ntf
sudo update-alternatives --auto -iptables
sudo update-alternatives --auto -ip6tables
sudo apt update
sudo apt install --reinstall iptables
iptables --version
sudo update-alternative --display iptables
ls -la /usr/sbin/iptables*
.//usr/sbin/iptables-nft
./usr/sbin/iptables-nft
sudo update-alternatives --display iptables
sudo update-alternative --auto
sudo update-alternatives --auto iptables
sudo update-alternatives --auto ip6tables
sudo apt update && sudo apt upgrade -y
iptables --version
sudo apt remove iptables ip6tables -y
sudo apt remove iptables
sudo dpkg --remove --force-remove-reinstreq iptables
sudo apt purge
iptables
sudo modprobe nf_tables
find /lib/modules/$(uname -r) -name "*nf_tables*"
sudo modprobe nfnetlink
sudo apt install --reinstall linux-modules-6.16.3-76061603-generic
iptables --version
dpkf -l | grep linux-image
dpkg -l | grep linux-image
sudo apt install --reinstall linux-modules-extra-6.16.3-76061603-generic
dpkg -l | grep linux-modules
sudo update grub
sudo update-grub
sudo reboot now
```

as for why it actually workked ... idk... if it it worked it works lmao
