### ISSUE TITLE
wslenv not respecting p, nor allowing spaces in variables

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/WSL#6661]
# Environment

```none
Windows build number: 10.0.19043.867
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

I have some scripts that I have not run in a while and while setting up a new machine last week I saw that they are broken. I am pretty sure this used to work before.

The first issue is that it looks like I am not required to either use 'u' or 'w'. I think I did not need to use any of those in the past. What I see now:

```
C:\Users\tiagoma>set WSLENV=USERNAME/p

C:\Users\tiagoma>wsl echo $USERNAME


C:\Users\tiagoma>

```

In the past I am pretty sure the variable would be present in the wsl side before - ie the echo command above would actually print.

The other issue I am seeing is that I cannot have spaces in the variable names anymore, ex:

```
C:\Users\tiagoma>set WSLENV=USERNAME/u

C:\Users\tiagoma>wsl echo $USERNAME
tiagoma

C:\Users\tiagoma>set WSLENV= USERNAME/u

C:\Users\tiagoma>wsl echo $USERNAME


C:\Users\tiagoma>
```

Before both echoes would print, but not anymore.

**Comment by craigloewen-msft** [comment]
Hi @tiagomacarios overall what you're describing seems to be 'as design'. Please take a look at [this blog post](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) that describes the WSLENV variable in detail. The /p flag is for paths, and the /u translates variables from Windows to WSL. My guess is that you might have been on an older build (like 17063) and as we improved this behaviour you ran into these changes. I'll close this out as we don't have actionable items on the engineering team to resolve these. Are you able to fix your script to resolve this on your end? 

Thanks!
