### ISSUE TITLE
How to increase wsl2 disk space ?

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/WSL#6663]
**Is your feature request related to a problem? Please describe.**
I want to increase wsl2 disk space because I run a mysql in wsl2 and its performance is affected by disk allocation .

**Describe the solution you'd like**
I run 
```Powershell
wsl.exe --shutdown
resize-vhd -Path .\ext4.vhdx -SizeBytes 300GB
``` 
But it doesn't seem to work ...

**Comment by WSLUser** [comment]
Use .wslconfig. Check the MS WSL Docs.

**Comment by craigloewen-msft** [comment]
@DachuanZhao could you try following the instructions here and letting us know if that solves your issue:
https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk

Thanks!
