### ISSUE TITLE
Wine and/or qemu-user is broken in WSL2

### ISSUE THREAD

**Issue by Ley0k** [microsoft/WSL#6668]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.844]
Your Distribution version: Release:        10 (Debian 10 Buster)
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

If not done, make sure to start from a clean install of Debian or Ubuntu on Windows.

## 1. Add the i386 architecture for amd64 and install packages for repository signing
```bash
dpkg --add-architecture i386 && apt update && apt install -y curl gnupg2
```

## 2. Install release keys, and add the wine repository, and the OSB repository to fix faudio dependencies when installing Wine
```bash
curl -kL https://dl.winehq.org/wine-builds/winehq.key | apt-key add - \
 && curl -kL https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10/Release.key | apt-key add - \
 && echo "deb https://dl.winehq.org/wine-builds/debian/ buster main" >/etc/apt/sources.list.d/wine.list \
 && echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./" >/etc/apt/sources.list.d/faudio.list \
 && apt update
```

## 3. Wine depend on libfaudio0 library, so the library needs to be installed first
```bash
apt install -y libfaudio0 libfaudio0:i386 \
 && rm /etc/apt/sources.list.d/faudio.list \
 && apt update
```

## 4. Install Wine 6.0
```bash
apt install -y --install-recommends winehq-stable=6.0.0~buster-1 wine-stable=6.0.0~buster-1 wine-stable-amd64=6.0.0~buster-1 wine-stable-i386=6.0.0~buster-1
wine --version # should print wine-6.0
```

## 5. Then run
```bash
winecfg
```

**WSL logs**: 
Attached archive with detailed information from strace: [wine.zip](https://github.com/microsoft/WSL/files/6126482/wine.zip)

#  Expected behavior

Winecfg takes time to configure wine for the current user.
```
wine: created the configuration directory '/root/.wine'
...
wine: configuration in L"/root/.wine" has been updated.
```
It is working on a clean network installation of Debian 10 on a Virtual Machine.

# Actual behavior

winecfg returns immediately with the following error:
```
wine: created the configuration directory '/root/.wine'
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```
On Wine 4.0.x and 5.0.x, winecfg works, but 32-bit applications regularly crash with the following error:
```
006a:err:seh:raise_exception Exception frame is not in stack limits => unable to dispatch exception.
wine client error:5e: write: Bad file descriptor
wine client error:38: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Docker on Windows is affected by the issue when it uses WSL 2.

**Comment by therealkenc** [comment]
Landing zone for nested scenarios (qemu in WSL2) is /dupe #4193. Open up a discussion for the Wine on WSL scenario if you like. It is likely (?) possible to take `qemu` out of the equation, but that would be a userspace thing.
