### ISSUE TITLE
WSL2 DNS server adds additional records to answers

### ISSUE THREAD

**Issue by digininja** [microsoft/WSL#6669]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```
```
PS C:\Users\Robin> cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.804]
```

```
$ cat /proc/version
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

It is on WSL2 and both Debian and Ubuntu hosts

# Steps to reproduce

A full write up here:

<https://digi.ninja/blog/wsl2_dns.php>

In summary, look at the query below, the answer should be just the google IP, the two root servers should be in the additional section. Putting them in with the answers can cause connections to be made to the root servers (or other DNS server) if the actual answer times out.

```
$ dig google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9758
;; flags: qr rd ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             0       IN      A       216.58.210.46
e.root-servers.net.     0       IN      AAAA    2001:500:a8::e
g.root-servers.net.     0       IN      AAAA    2001:500:12::d0d
```

**WSL logs**: 

Don't think they are needed but can send anything required.

#  Expected behavior

The additional records should be in the additional section.

# Actual behavior

The DNS server is responding with the additional record fields in the answer section not the additional section and so the DNS server itself becomes an answer.

**Comment by therealkenc** [comment]
Ref #4839 #5806

**Comment by digininja** [comment]
Agreed, same problem, still not fixed.

**Comment by therealkenc** [comment]
Okay let's call it /dupe #4839 #5806 subscribe those.
