### ISSUE TITLE
Run Gui Apps using nautilus

### ISSUE THREAD

**Issue by mraufrufi** [Microsoft/WSL#667]
Nautilus can provide eassy way to run application.
Step Required:

1.Fix the Dbus and install unity by follwoing [https://github.com/Microsoft/BashOnWindows/issues/637] 
2. Instead of running compiz , run nautilus  and navigate to /usr/share/application/ 
<img width="838" alt="nautilus" src="https://cloud.githubusercontent.com/assets/8577480/16938113/78e9f7c8-4da7-11e6-9b33-575e636ee12e.png">

now you can try the application you want . I tried following application that are running very smoothly.
<img width="838" alt="Libra office " src="https://cloud.githubusercontent.com/assets/8577480/16938033/bb946870-4da6-11e6-9f78-8265f5d4c1b2.png">
<img width="837" alt="Thunderbird and Sudoku" src="https://cloud.githubusercontent.com/assets/8577480/16938046/d345093e-4da6-11e6-989d-d7717efa384b.png">

**Comment by mraufrufi** [comment]
Please provide the list of applications that you are able to run successfully.

**Comment by sunilmut** [comment]
With better support for AF_LOCAL socket, dbus seems to be happy and the dbus workarounds to use TCP sockets will hopefully no longer be needed. The changes haven't made it to the release branch yet, but are moving fast. Keep an eye out on the release notes.

**Comment by niutech** [comment]
Tip: you can easily add a theme to your GTK+ apps by installing the package `gnome-themes-standard` and replace `Ambiance` with `Adwaita` in `/etc/gtk-3.0/settings.ini` and `/etc/gtk-2.0/gtkrc`.

**Comment by therealkenc** [comment]
OP here was about `dbus` which is working to a first order these days. Landing zone for running graphic apps is #637.
