### ISSUE TITLE
WSL changed to version 1 after Win 10 Pro upgrade and got stuck in this version

### ISSUE THREAD

**Issue by edueter** [microsoft/WSL#6672]
# Environment

```none
Windows build number: 
Microsoft Windows [versão 10.0.19042.867]

Your Distribution version: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Whether the issue is on WSL 2 and/or WSL 1: 
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020 


```

# Steps to reproduce

I had this Windows update on queue since last Friday and restarted the computer today with the intend to let it happen. I'm not sure what build number it was before this.
Was using WSL2 normally with vscode extension while building this site (front-end dev) right after the update.
Once it was done, Windows restarted normally with everything seeming right.

Started Windows Terminal Preview (which defaults to Ubuntu) and opened vscode on the previously used folder.
Vscode opened with this warning telling me to use WSL2.
Closed it and checked the version in powershell with `wsl -l -v` and it returned version 1 to my Ubuntu distro (the only one I have installed).
Tried resetting it to version to with no luck. `wsl --set-default-version 2` returns a standard message telling me (simply translated from pt-br) 'For more information on the major differences of WSL 2, visit...' and `wsl -l -v` will tell me again that it's on version 1.
![image](https://user-images.githubusercontent.com/39069806/111079562-49736100-84d9-11eb-9b59-bb5796548433.png)

Done the procedure to re-install WSL1 and upgrade it to WSL2 again, like it's said on https://docs.microsoft.com/en-us/windows/wsl/about, using admin powershell to enable wsl and virtual machine feature. Reinstalled the kernel too. 
Then, once again tried setting up --set-default-version and no changes were made. I'm stuck with version 1.

Not sure on how to document this issue. Please, let me know if I can improve this.

#  Expected behavior

WSL2 to be fully functional and set as default version, after win 10 update.

# Actual behavior

WSL1 is the default and I can't change it

**Comment by therealkenc** [comment]
Discussion at #6505.
