### ISSUE TITLE
font changed when I usse less or vim

### ISSUE THREAD

**Issue by zhouzhendiao** [microsoft/WSL#6673]
When I open WSL, the font like this:
![image](https://user-images.githubusercontent.com/12294679/111091244-4c1f9600-856d-11eb-9c8d-0ecc9b1093a0.png)
But after I used Vim or Less: 
the font would change like this: 
![image](https://user-images.githubusercontent.com/12294679/111091286-69ecfb00-856d-11eb-8ef4-71fa72bc8105.png)
Can Someone figure it out the reason?

**Comment by therealkenc** [comment]
For font related issues please post over at [windows terminal](https://github.com/microsoft/terminal/issues) they will have a better idea.
