### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070002

### ISSUE THREAD

**Issue by sebastianbuechler** [microsoft/WSL#6674]
# Environment

```none
Windows build number: 10.0.19042.867
Your Distribution version: Not installable
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Install WSL2
2. Download Ubuntu-20.04 from Microsoft Store
3. Try to start Ubuntu-20.04 -> Error appearing

**WSL logs**:  Logs can not be found because of the same error: Error code: 0x80070002

#  Expected behavior

Start Ubuntu 20.04 properly

# Actual behavior

Error in cmd/ps: 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002  (something like: system could not find file)

**Comment by therealkenc** [comment]
/dupe #6579 (they couldn't get logs either) and maybe #6674.

**Comment by loudy2000** [comment]
ccleaner fixed it here
