### ISSUE TITLE
External application can't connect to Redis Cluster container running in WSL 2

### ISSUE THREAD

**Issue by sh2sg** [microsoft/WSL#6686]
# Environment

```none
Windows build number: [Version 10.0.19042.804]
Your Distribution version: [Ubuntu 20.04]
Whether the issue is on WSL 2 and/or WSL 1: [WSL 2]
```

# Steps to reproduce

Quick background:

I am having Nginx web server and Redis Cluster running as separate docker container in WSL 2, Application in Nginx container connects to Redis Cluster container on hostname (redis-cluster).

I want to load application B in my Windows IDE, it needs to connect to the same Redis Cluster container running in WSL 2 on localhost. So I can change code and debug application in IDE.

I am using docker daemon from Ubuntu Distribution (apt-get install... service docker start), also tried Docker Desktop for Windows (using WSL2 backend), same issue.

Web server and Redis Cluster docker-compose looks like:
```none
version: "3"
services:
    web:
        image: nginx
        ports:
          - "8080:80"
    redis-cluster:
        image: grokzen/redis-cluster:latest
        ports:
          - "7000:7000"
          - "7001:7001"
          - "7002:7002"
          - "7003:7003"
          - "7004:7004"
          - "7005:7005"
```
Start containers by
```none
$ docker-compose up
``` 

From Windows Host browser, visit Nginx port 8080 like http://localhst:8080/health, it connects to Redis Cluster container on redis-cluster:7000, I get response like "Redis is up",

Now in IDE, I have another application that uses the same Redis Cluster.

#  Expected behavior

Application (from Windows host) connects to Redis Cluster (in WSL 2) on localhost:7000

# Actual behavior

In application's log:
```none
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7000]: connection timed out: /172.18.0.2:7000
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7004]: connection timed out: /172.18.0.2:7004
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7001]: connection timed out: /172.18.0.2:7001
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7003]: connection timed out: /172.18.0.2:7003
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7002]: connection timed out: /172.18.0.2:7002
2021-03-17 13:20:05.184  WARN 2568 : Unable to connect to [172.18.0.2:7005]: connection timed out: /172.18.0.2:7005
```

# Analysis

Application from outside of WSL2 is able to connect to localhost:7000 since the port is exposed by container, but when it requests master node address, Redis Cluster returns the internal NAT'd address (172.18.0.2) which the external application knows nothing about, so connection is refused when application tries to connect to actual node address.

For the Nginx container, since it is started by the same docker compose under the same docker network, it is able to connect on either hostname or internal address.

**Comment by therealkenc** [comment]
There is no repro steps in the OP, but the problem is likely a variation of /dupe #4851 with a side of #5298, with nods to #4885 #6638 (etc), plus overarching #4150. You can open a [discussion](https://github.com/microsoft/WSL/discussions) for your specific use case, but it is going to be a steep repro step hill to climb. Oftentimes eschewing `localhost` entirely and using `avahi-daemon` will get you there. Examples #5706 ([message](https://github.com/microsoft/WSL/issues/5706#issuecomment-668353533)) or #5368 ([message](https://github.com/microsoft/WSL/issues/5368#issuecomment-645316048)).

**Comment by sh2sg** [comment]
> There is no repro steps in the OP, but the problem is likely a variation of dupe #4851 with a side of #5298, with nods to #4885 #6638 #6657 (etc), plus overarching #4150. You can open a [discussion](https://github.com/microsoft/WSL/discussions) for your specific use case, but it is going to be a steep repro step hill to climb. Oftentimes eschewing `localhost` entirely and using `avahi-daemon` will get you there. Examples #5706 ([message](https://github.com/microsoft/WSL/issues/5706#issuecomment-668353533)) or #5368 ([message](https://github.com/microsoft/WSL/issues/5368#issuecomment-645316048)).

I checked mentioned issues, don't seem to be related to my case, let me summarize it:
1. Windows host can access docker containers running in WSL2 on localhost on exposed ports.
2. Windows host can't access docker internal NAT'd address, this only applies to those cluster setup in which client needs to lookup actual node address
