### ISSUE TITLE
recurring Init PID 101 zombie wsl2 Ubuntu

### ISSUE THREAD

**Issue by ntaken** [microsoft/WSL#6689]
First my apology if this been fixed in develop channel insider. Could not find any mentioning of it.

# Environment

Microsoft Windows [Version 10.0.19043.899]
UBUNTU Release:        20.04
Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

# Steps to reproduce

Recur even if successfully killed or if you would terminate 

>  ps axo stat,ppid,pid,comm | grep -w defunct

Z       98   101 init <defunct>

>  ps -auxf

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   1172   864 ?        Sl   16:33   0:00 /init
root        98  0.0  0.0    892    88 ?        Ss   16:33   0:00 /init
root        99  0.0  0.0    892    88 ?        S    16:33   0:00  \_ /init
ntaken     100  0.0  0.1 764268 42800 pts/0    Ssl+ 16:33   0:01  |   \_ docker serve --address unix:///home/ntaken/.doc
root       101  0.0  0.0      0     0 ?        Z    16:33   0:00  \_ [init] <defunct>
root       126  0.0  0.0    892    88 ?        S    16:33   0:00  \_ /init
root       127  0.0  0.0 1464120 25628 pts/1   Ssl+ 16:33   0:00      \_ /mnt/wsl/docker-desktop/docker-desktop-proxy --
root       142  0.0  0.0   1256   360 ?        Ss   22:09   0:00 /init
root       143  0.0  0.0   1256   368 ?        S    22:09   0:00  \_ /init
ntaken     144  0.0  0.0  10052  5052 pts/2    Ss   22:09   0:00      \_ -bash
ntaken     337  0.0  0.0  10856  3396 pts/2    R+   22:24   0:00      |   \_ ps -auxf
ntaken     239  0.0  0.0   6032  2612 ?        Ss   22:09   0:00      \_ ssh-agent

#  Expected behavior

No zombie.

# Actual behavior

zombie

**Comment by therealkenc** [comment]
Huh. Thanks for the submission and tight repro.

![image](https://user-images.githubusercontent.com/7049700/111544292-79b53c80-8731-11eb-8016-9fa0f7abccf6.png)

**Comment by benhillis** [comment]
@therealkenc - What Windows build are you running?  I'm not seeing this on a recent Insider build.

**Comment by viceice** [comment]
Seeing this too very frequently

```
  PID TTY      STAT   TIME COMMAND
    1 ?        Sl     0:00 /init
   98 ?        Ss     0:00 /init
   99 ?        S      0:00  \_ /init
  100 pts/0    Ssl+   0:11  |   \_ docker serve --address unix:///home/user/.docker/run/docker-cli-api.sock
  101 ?        Z      0:00  \_ [init] <defunct>
  107 ?        S      0:00  \_ /init
  108 pts/1    Ssl+   0:03      \_ /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Ubuntu --docker-desktop-root /mnt/wsl/docker-desktop
  153 ?        Ss     0:00 /init
  154 ?        S      0:00  \_ /init
  155 pts/2    Ss+    0:00      \_ -bash
 1466 ?        Ss     0:00 /init
 1467 ?        S      0:00  \_ /init
 1468 pts/3    Ss     0:00      \_ -bash
 1675 pts/3    R+     0:00          \_ ps axf
```

`Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020`

**Comment by Orillian** [comment]
I'm seeing this a lot lately on Ubuntu 20.04.2 LTS (GNU/Linux 5.4.72-microsoft-standard-WSL2 x86_64)
![image](https://user-images.githubusercontent.com/823192/123983845-69903880-d981-11eb-9352-5742a7fa202d.png)

**Comment by taylorbarrera** [comment]
I'm not sure if it's exactly related or not, but I was having an issue with my 20.04 Ubuntu on wsl2 starting with about 16 zombie processes every time. I narrowed the source down to the docker desktop WSL integration that was causing the zombie processes.

If I killed wsl ```wsl --shutdown``` and opened Ubuntu before restarting the docker daemon then I would not see the zombie processes, and as soon as I allowed docker's distro to restart the zombie would appear after it started up the docker client in my Ubuntu distro. I just disabled the integration in docker's setting for now.

With further testing, just disabling the integration with docker's settings kills the zombie init processes right away, no manual work required. However this means that you just can't use that feature if you don't want zombie processes.

**Comment by ntaken** [comment]
I have docker desktop WSL integration also. Seems like that is the cause.

**Comment by supernovae** [comment]
I see the same on WSL2 + Fedora34

![image](https://user-images.githubusercontent.com/1461719/127506425-dce66ba6-dbc0-4f99-9c21-ef4a5fca43af.png)

**Comment by ravihara** [comment]
> I have docker desktop WSL integration also. Seems like that is the cause.

Yep, Docker for desktop with WSL integration seems to be the actual cause.

**Comment by andrewdalpino** [comment]
Same

![image](https://user-images.githubusercontent.com/18690561/128588441-615c7d9c-4f7b-4a00-a966-259249784f84.png)

**Comment by djs55** [comment]
Although Docker Desktop's WSL integration seems to trigger this, it also happens without Docker installed:

If I shut down Docker, there are no `init` zombies in my WSL distro:
```
dave@beast:~$ ps uax | grep defunct | grep init
dave@beast:~$
```
If I run bash on Windows and:
```
$ wsl sleep 30 & wsl sleep 3
[1] 957
```
And then back in my WSL distro I see a zombie appearing after 3s (corresponding to the `sleep 3`) which is only removed after the `sleep 30` terminates:
```
dave@beast:~$ ps uax | grep defunct | grep init
root     18116  0.0  0.0      0     0 ?        Z    11:59   0:00 [init] <defunct>
```
The Docker Desktop WSL integration is running a couple of shell commands which are similar to the `sleep 3` in this example. Normally if I run `sleep 30 & sleep 3` inside Linux then the `sleep 3` will exit, the parent (shell) will get a signal and call `waitpid`, removing the zombie.

(Thanks to @fredericdalleau for the example)

**Comment by RyanZurrin** [comment]
I take it this is just something that is never going to be fixed. I just noticed this happening and traced the cause back to Docker Desktop and WSL integration and figured I would see if there were any info and found this dating back almost 2 years now.
