### ISSUE TITLE
Solr and port 8983

### ISSUE THREAD

**Issue by JulienMarliac** [Microsoft/WSL#669]
Hi,

I'm trying to run solr.

The installation is OK. 

But solr can't listen to port 8983

`
Waiting to see Solr listening on port 8983 [\]  Still not seeing Solr listening on 8983 after 30 seconds!
Solr process 843 running on port 8983
WARN  - 2016-07-19 10:30:42.175; org.apache.solr.util.SolrCLI; Request to http://localhost:8983/solr/admin/info/system failed due to: Connexion refusée, sleeping for 5 seconds before re-trying the request ...
Solr at http://localhost:8983/solr/ not online.
`

Any clues ?

**Comment by benhillis** [comment]
Have you opened that port in the windows firewall?

**Comment by JulienMarliac** [comment]
Yeah I tried, apache is working fin on 80. Should I try to totally remove Mcafee ?

**Comment by benhillis** [comment]
We've seen issues with anti virus blocking networking in the past, it would be worth disabling it to see if that resolves your issue.

**Comment by JulienMarliac** [comment]
Hi again,

I did remove my anti virus and disabled the windows firewall, but still have the same issue :/

**Comment by JulienMarliac** [comment]
I found workaround by installing solr on windows and it's working fine.  (since windows and ubuntu share the same IP).

Still can't figure out why Sollr can't listen 8983 with ubunutu but can with windows.

**Comment by JulienMarliac** [comment]
Me again,

Got exactly the same issue with Rabbitmq Server.

**Comment by sunilmut** [comment]
@JulienMarliac - Thanks for reporting the issue. Can you collect a strace of the command that you are using to start 'solr' and share that with us? `strace -o <strace_output_file> -ff <command>`

Please share the <strace_output_file>

**Comment by sunilmut** [comment]
@JulienMarliac - Thanks for reporting the issue. Can you collect a strace of the command that you are using to start 'solr' and share that with us? strace -o <strace_output_file> -ff <command>
Please share the <strace_output_file>

**Comment by sunilmut** [comment]
@JulienMarliac - Thanks for reporting the issue. Can you collect a strace of the command that you are using to start 'solr' and share that with us? `strace -o <strace_output_file> -ff <command>`

Please share the 'strace_output_file'

**Comment by JulienMarliac** [comment]
@sunilmut Hi. I ve done the strace but it never stop and generate me a lot of files <strace_output_file>.XXXX . I ve stoped at 149 files, do you want them all ?

**Comment by benhillis** [comment]
A lot has changed since July 2016.  Could you please upgrade to 1803 and see if your issues persist?

**Comment by sdivakarrajesh** [comment]
I had the same issue and upgrading to WSL2 fixed the issue

**Comment by noxidsoft** [comment]
Still an issue on WSL2.
I can't get a Windows 11 located browser to load the localhost:$PORT provided, even though I can successfully start the server.
![image](https://github.com/microsoft/WSL/assets/729135/3e59bc7c-c206-4219-8ff2-bdc5f9d134e0)
