### ISSUE TITLE
Linux 5.4.91 - High Memory use / Memory given back is less

### ISSUE THREAD

**Issue by RajvanshR** [microsoft/WSL#6690]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.868]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1:Linux version 5.4.91-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP Mon Jan 25 18:39:31 UTC 2021
```

# Steps to reproduce

Vmmem process shows 450 MB of RAM usage on initial start up. If I start some new process like opening up a IDE, the RAM shoots up to about 2.5 GB. The CPU usage spikes to about 70 %, but comes down within a couple of seconds.  After closing the IDE, the RAM usage shown is about 1.9 GB. So it releases the RAM; but the amount released is very less.

RAM usage reported with free -m command is only about 1.2G when the IDE is open and when IDE is closed free -m reports just 94MB of memory used where as Vmmen still occupies around 1.9 GB.

**WSL logs**: 

#  Expected behavior

Memory is given back to host once the process in WSL 2 is closed.

# Actual behavior

Memory is still showing as used under Vmmem process even after the process is closed in WSL 2. The amount of memory released back to host is very less.

**Comment by fas3r** [comment]
Hello @therealkenc , 

well [#4166](https://github.com/microsoft/WSL/issues/4166) is close for comment and yet after 2 years this issue of memory usage at 100% is not solve . 

The workaround to set the max memory allocated to a WSL Image is not a solution, its just a fix to prevent all the available memory on the machine to be consumed by a virtual machine which is doing nothing. 

I can not wait WSL 3 maybe M$ will do that properly for once and identity such issue when running their test unit. Until then I will just keep using virtualbox, maybe its not as integred as WSL but at least it works as expected.
