### ISSUE TITLE
Does WSL 2 Manage Serial Ports?

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/WSL#6692]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.868]
Your Distribution version: Release:        10
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

+ Connect serial device on USB.
+ Check serial ports show up on **Device Manager**

![Capture 2021-03-18 13-40-20](https://user-images.githubusercontent.com/951776/111628195-3c63b400-87f0-11eb-986d-bae747573608.png)

+ As per [Serial Support on the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/archive/blogs/wsl/serial-support-on-the-windows-subsystem-for-linux), check in registry that the serial prots are enumerated.

![Capture 2021-03-18 13-40-38](https://user-images.githubusercontent.com/951776/111628217-44235880-87f0-11eb-81f5-e4ad97aed623.png)

+ On WSL2 Debian, list the `/dev/ttyS*` ports.

![Capture 2021-03-18 13-46-19](https://user-images.githubusercontent.com/951776/111628342-67e69e80-87f0-11eb-840a-9b53afe59974.png)

I have already checked other issues (_e.g._ #5158 #4861), but it is not entirely clear whether they relate to WSL 1 or WSL 2.

So the questions are: 
+ Does WSL 2 manage serial ports?
+ How to manage serial ports with WSL 2?

If WSL 1 used to and WSL 2 no longer does, this is a serious regression.

#  Expected behaviour

Serial ports show up as `/dev/ttyS10` and `/dev/ttyS11`.

# Actual behaviour

Serial ports do not show up as `/dev/ttyS10` and `/dev/ttyS11`.

Thank you!

**Comment by Makurisan** [comment]
The same problem on my machine. Windows 10 Version 10.0.21337

**Comment by Makurisan** [comment]
I have defined a COM TCP tunnel with "CommTunnel"  and under WSL2 with "sudo socat - tcp4:192.168.0.189:2101" made the connection. It is important that you open the port 2101 in defender.

**Comment by therealkenc** [comment]
LZ /dupe #5203

**Comment by rei-vilo** [comment]
Well, #5203 reads « COM port device not enumarating in WSL 1 #5203 » and talks about WSL1 not WSL2. 

So the title is really misleading.

**Comment by therealkenc** [comment]
For WSL2, #4322

**Comment by Chris-Idema-WizzDev** [comment]
> As a workaround I have defined a COM TCP tunnel with "CommTunnel" and under WSL2 with "sudo socat - tcp4:192.168.0.189:2101" made the connection. It is important that you open the port 2101 for the app in defender.

I was able to get your solution working to access serial from ubuntu 18 on WSL2, but I cannot control the RTS and DTR pins. Did you get that to work?

**Comment by josegpulido** [comment]
> 
> 
> > As a workaround I have defined a COM TCP tunnel with "CommTunnel" and under WSL2 with "sudo socat - tcp4:192.168.0.189:2101" made the connection. It is important that you open the port 2101 for the app in defender.
> 
> I was able to get your solution working to access serial from ubuntu 18 on WSL2, but I cannot control the RTS and DTR pins. Did you get that to work?

Hey there! Where can I find a guide or something to achieve this?

**Comment by Chris-Idema-WizzDev** [comment]
@josegpulido 
For flashing an ESP32 on WSL2 I used this guide:
https://matevarga.github.io/esp32/m5stack/esp-idf/wsl2/2020/05/31/flashing-esp32-under-wsl2.html
Example that worked for me (including control of RTS and DTR pins):
```
on windows power shell:
./com2tcp-rfc2217.bat COM6 5555

on wsl2:
idf.py flash -b 115200 -p rfc2217://10.0.0.159:5555
or
idf.py -monitor -p rfc2217://10.0.0.159:5555
```
You should be able to use this for other applications as well, but I have only tested it with the idf application.
I haven't used it in a while since I switched to Ubuntu completely due to other issues.

**Comment by probonopd** [comment]
```
PS \hub4com-2.1.0.0-386>  ./com2tcp-rfc2217.bat COM12 5555

hub4com-2.1.0.0-386>"hub4com"  --create-filter=escparse,com,parse --create-filter=purge,com,purge  --create-filter=pinmap,com,pinmap:"--rts=cts --dtr=dsr --break=break" --create-filter=linectl,com,lc:"--br=remote --lc=remote" --add-filters=0:com --create-filter=telnet,tcp,telnet:" --comport=server --suppress-echo=yes"  --create-filter=lsrmap,tcp,lsrmap --create-filter=pinmap,tcp,pinmap:"--cts=cts --dsr=dsr --dcd=dcd --ring=ring" --create-filter=linectl,tcp,lc:"--br=local --lc=local" --add-filters=1:tcp --octs=off "COM12" --use-driver=tcp "*5555"
ComIo::OpenPath(): CreateFile("COM12") ERROR 2 - The system cannot find the file specified.
```

Device is definitely at COM12 and nothing else is accessing it.
