### ISSUE TITLE
Does WSL 2 have 8021q Module?

### ISSUE THREAD

**Issue by Leo1726** [microsoft/WSL#6698]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.19042.867]]
Your Distribution version: [Ubuntu Release:18.04]
Whether the issue is on WSL 2 and/or WSL 1: [Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020]
```

# Steps to reproduce

**WSL logs**: 
![image](https://user-images.githubusercontent.com/53190920/111725584-4940e000-88a2-11eb-8fb0-ba15915b6f63.png)
I want to enable 8021q module which could let me to set the VLAN. But, it seems that there is no 8021q module in the kernel.
How could I enable or add this function/module?

**Comment by WSLUser** [comment]
In https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.4.y/Microsoft/config-wsl you have

```
CONFIG_VLAN_8021Q=y
# CONFIG_VLAN_8021Q_GVRP is not set
# CONFIG_VLAN_8021Q_MVRP is not set
```

So it's enabled by default.  If you need GVRP or MVRP, those will need to be manually enabled with a custom compile of the kernel. Secondly, WSL2 doesn't yet support kernel modules natively. The kernel is monolithic as a result. Lastly, I notice your Linux kernel is out of date. Try updating it.

**Comment by therealkenc** [comment]
That repro is missing an `add` and needs root. 

![image](https://user-images.githubusercontent.com/7049700/112063692-09d2f780-8b1f-11eb-86e1-3a641dc71db7.png)

Try `sudo vconfig add eth0 10` and see if it takes.

**Comment by Leo1726** [comment]
Got it！Thanks! @therealkenc
