### ISSUE TITLE
Launching Windows executables from the Linux file system doesn't work reliably

### ISSUE THREAD

**Issue by emilio** [microsoft/WSL#6701]
**Is your feature request related to a problem? Please describe.**

I have a build system that can generate windows executables from Linux via cross-compilation. The executable ends up in the Linux file system.

However, in order to launch most of the executables, I need to move it to the Windows drive, which seems unfortunate.
Some extremely basic executables work, but anything a bit more complicated fails with either `executable.exe: Invalid argument` (with no extra description of what goes wrong), or a window like:

```
---------------------------
TestUtf8.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000280). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

The only info I found to this respect is [here](https://stackoverflow.com/questions/38920710/how-can-i-run-a-windows-executable-from-wsl-ubuntu-bash/47663269#47663269).

> Note that any win-executable must reside in the windows (DrvFs) file-system - not on the Linux's file-system (VolFs) - in order to inherit a proper Windows working-directory.

So not sure if it's an expected limitation.

**Describe the solution you'd like**

Launching the executable works just as if it was launched from the windows drive.

**Describe alternatives you've considered**

N/A

**Additional context**

Not sure I have much, but let me know if you have any question?

**Comment by emilio** [comment]
Ah, `0xC0000280` is `STATUS_REPARSE_POINT_NOT_RESOLVED`: The NTFS symbolic link could not be resolved even though the initial file name is valid. I could try using some less symlinks, let's see if that helps.

**Comment by emilio** [comment]
Ok, I think that's a file system case-insensitivity issue. SXSTrace says:

```
INFO: Resolving reference mozglue,language="&#x2a;",type="win32",version="1.0.0.0".
        INFO: Resolving reference for ProcessorArchitecture mozglue,language="&#x2a;",type="win32",version="1.0.0.0".
                INFO: Resolving reference for culture en-US.
                        INFO: Applying Binding Policy.
                                INFO: No binding policy redirect found.
                        INFO: Begin assembly probing.
                                INFO: Did not find the assembly in WinSxS.
                                INFO: Did not find manifest for culture en-US.
                        INFO: End assembly probing.
                INFO: Resolving reference for culture en.
                        INFO: Applying Binding Policy.
                                INFO: No binding policy redirect found.
                        INFO: Begin assembly probing.
                                INFO: Did not find the assembly in WinSxS.
                                INFO: Did not find manifest for culture en.
                        INFO: End assembly probing.
                INFO: Resolving reference for culture Neutral.
                        INFO: Applying Binding Policy.
                                INFO: No binding policy redirect found.
                        INFO: Begin assembly probing.
                                INFO: Did not find the assembly in WinSxS.
                                INFO: Attempt to probe manifest at \\wsl$\Debian\home\emilio\src\moz\mozilla-central\obj-debug-win-cross\dist\bin\mozglue.DLL.
                                INFO: Attempt to probe manifest at \\wsl$\Debian\home\emilio\src\moz\mozilla-central\obj-debug-win-cross\dist\bin\mozglue.MANIFEST.
                                INFO: Attempt to probe manifest at \\wsl$\Debian\home\emilio\src\moz\mozilla-central\obj-debug-win-cross\dist\bin\mozglue\mozglue.DLL.
                                INFO: Attempt to probe manifest at \\wsl$\Debian\home\emilio\src\moz\mozilla-central\obj-debug-win-cross\dist\bin\mozglue\mozglue.MANIFEST.
                                INFO: Did not find manifest for culture Neutral.
                        INFO: End assembly probing.
        ERROR: Cannot resolve reference mozglue,language="&#x2a;",type="win32",version="1.0.0.0".
```

**Comment by emilio** [comment]
Ok, so with the case-insensitivity issue fixed and the symlinks and hardlinks removed, then this works.

**Comment by benhillis** [comment]
@emilio - What build are you running on?

**Comment by therealkenc** [comment]
@emilio - can you please post the output of the following:
```
$ cat /proc/version
$ cmd.exe /c ver
```

Also what is the source of your `TestUtf8.exe` application, or the steps required to produce it with the The NTFS symbolic link.

**Comment by emilio** [comment]
Welp, I read the request for info from Linux, and forgot to reply, my bad!

```
$ cat /proc/version
Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19042.867]
```

**Comment by emilio** [comment]
TestUtf8 is [this](https://searchfox.org/mozilla-central/source/mfbt/tests/TestUtf8.cpp). It doesn't do much special stuff except linking to `mozglue.dll`. A firefox checkout and build is one way to get this setup, but I can try to find a more reduced test-case.

@benhillis @therealenc could you reopen please? I don't have the permission to do so.

Sorry again for the lag replying

**Comment by therealkenc** [comment]
The link above is to a source file. What are the CLI repro steps to evoke the error?
