### ISSUE TITLE
Build 21337 not working with cuda; previous version worked

### ISSUE THREAD

**Issue by laurelrr** [microsoft/WSL#6702]
# Environment

```none
Windows build number: 21337.1000
Your Distribution version: ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.91-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP Mon Jan 25 18:39:31 UTC 2021
```

# Steps to reproduce

After my computer upgraded to build 21337, I lost GPU support.  I knew that build 21327 had a known issue but that it would be fixed in this version. I am unable to roll back to my previous version (it was the one before 21327) and was working correctly with GPU.
Since the upgrade, I upgraded to latest NVIDIA driver (461.92 ) by running 461.92-quadro-rtx-desktop-notebook-win10-64bit-international-dch-whql.exe and then restarting my machine.

Opening a terminal and starting wsl, I check the output of nvidia-smi.exe
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.92       Driver Version: 461.92       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000    WDDM  | 00000000:65:00.0  On |                  N/A |
| 30%   43C    P8    12W / 125W |    620MiB /  8192MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1744    C+G   C:\Windows\System32\dwm.exe     N/A      |
|    0   N/A  N/A      4120    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A      7832    C+G   ...batNotificationClient.exe    N/A      |
|    0   N/A  N/A      8424    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     10700    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     10984    C+G   ...TeamViewer\TeamViewer.exe    N/A      |
|    0   N/A  N/A     11228    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     12100    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     12376    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     13328    C+G   ...ap Camera\Snap Camera.exe    N/A      |
|    0   N/A  N/A     13772    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     14716    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     15100    C+G   ...lack\app-4.14.0\slack.exe    N/A      |
|    0   N/A  N/A     17644    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     19272    C+G   ...obeNotificationClient.exe    N/A      |
|    0   N/A  N/A     20256    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     20640    C+G   ...b3d8bbwe\WinStore.App.exe    N/A      |
+-----------------------------------------------------------------------------+

However, I am unable to see the device:
`$ ~/NVIDIA_CUDA-11.2_Samples/1_Utilities/deviceQuery/deviceQuery` 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 100
-> no CUDA-capable device is detected
Result = FAIL

`ll /usr/local/`
total 56
drwxr-xr-x 14 root root 4096 Mar 19 12:24 ./
drwxr-xr-x 11 root root 4096 Mar  5 14:32 ../
drwxr-xr-x  2 root root 4096 Mar  9 13:57 bin/
lrwxrwxrwx  1 root root    9 Mar 19 12:24 cuda -> cuda-11.2/
drwxr-xr-x 16 root root 4096 Mar  3 14:59 cuda-10.2/
drwxr-xr-x 15 root root 4096 Feb 24 12:57 cuda-11.0/
drwxr-xr-x 14 root root 4096 Mar  4 10:41 cuda-11.1/
drwxr-xr-x 15 root root 4096 Mar 18 13:27 cuda-11.2/
drwxr-xr-x  3 root root 4096 Feb 24 14:54 etc/
drwxr-xr-x  2 root root 4096 May 21  2019 games/
drwxr-xr-x  3 root root 4096 Feb 24 13:31 include/
drwxr-xr-x  7 root root 4096 Mar  5 14:32 lib/
lrwxrwxrwx  1 root root    9 May 21  2019 man -> share/man/
drwxr-xr-x  2 root root 4096 May 21  2019 sbin/
drwxr-xr-x  7 root root 4096 Feb 24 14:54 share/
drwxr-xr-x  2 root root 4096 May 21  2019 src/

**WSL logs**: 

#  Expected behavior
I expect if the NVIDIA driver is up to date and the cuda libraries are installed then I should be able to use the GPU.

# Actual behavior

The basic query fails to find a CUDA capable device.

**Comment by dmitrii-badretdinov** [comment]
Fixed in the next version.
https://github.com/microsoft/WSL/issues/6617
