### ISSUE TITLE
Can't upgrade to WSL2, even thought all is enabled

### ISSUE THREAD

**Issue by SNvMK** [microsoft/WSL#6704]
# Environment

```none
Windows build number: 10.0.19041.867
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce
1. Run `wsl --set-version ubuntu 2`
2. Get error like this: `Enable Windows feature for vitual machine platform and make sure that virtualization enabled in BIOS.`

**WSL logs**: 

#  Expected behavior
WSL is setting to version 2

# Actual behavior
It fails with above error

# Additional info
- Hyper-V enabled
- Hypervisor enabled
- Virtual Machine Platform enabled
- Intel VT-x enabled
Sorry but I dont understand which log file to send

**Comment by EAZYBLACK** [comment]
Search Turn Windows Features On Or Off
Open It
and enable 
Viurtal Machine Platform

**Comment by SNvMK** [comment]
![image](https://user-images.githubusercontent.com/51151590/111899551-e85f0680-8a5f-11eb-9036-f9bbc6366693.png)

**Comment by SNvMK** [comment]
![image](https://user-images.githubusercontent.com/51151590/111899567-075d9880-8a60-11eb-9529-b4228646af32.png)

**Comment by EAZYBLACK** [comment]
Now u can run the command to update to wsl2

**Comment by SNvMK** [comment]
![image](https://user-images.githubusercontent.com/51151590/111899579-1cd2c280-8a60-11eb-89de-d1e6f2daf423.png)
Error that I said in issue

**Comment by EAZYBLACK** [comment]
open winver.exe and send me what build do u have

**Comment by SNvMK** [comment]
![image](https://user-images.githubusercontent.com/51151590/111899630-776c1e80-8a60-11eb-878c-2b879d0383e4.png)

**Comment by EAZYBLACK** [comment]
do u have 64 bit windows?

**Comment by EAZYBLACK** [comment]
if u have 64 bit windows download this
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
If u have 32 bit windows sorry its not supported

**Comment by SNvMK** [comment]
yes
![image](https://user-images.githubusercontent.com/51151590/111899762-0a0cbd80-8a61-11eb-8cbf-c65f4e7b0a11.png)

**Comment by SNvMK** [comment]
> if u have 64 bit windows download this
> https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
> If u have 32 bit windows sorry its not supported

i installed it

**Comment by EAZYBLACK** [comment]
check in bios if viurtalazation is enabled
wsl doesnt support old cpus

**Comment by SNvMK** [comment]
> check in bios if viurtalazation is enabled
> wsl doesnt support old cpus

my cpu is Intel Pentium N3540. Virtualization enabled, checked maby times

**Comment by EAZYBLACK** [comment]
open cmd as admin
and run this comamnd
bcdedit /set hypervisorlaunchtype auto
if again didnt work after this command try reboot ur pc to take effect

**Comment by SNvMK** [comment]
THAAAAAANKS WORKED

**Comment by hyperdawg** [comment]
still doesn't work for me
