### ISSUE TITLE
iptable error while installing Lamp on ubuntu (installed in windows 10)

### ISSUE THREAD

**Issue by rashmisn96** [microsoft/WSL#6705]
I have installed ubuntu on my windows 10 os..im getting below error on sudo ufw status..
i referred https://github.com/Microsoft/WSL/issues/767 this link. somebody  please help me to resolve this issue

error:
ERROR: problem running iptables: iptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

Thanks in advance

**Comment by therealkenc** [comment]
What is the output of:
```
$ cat /proc/version
$ cmd.exe /c ver
$ lsb_release -r
$ update-alternatives --get-selections | grep iptables
```

![image](https://user-images.githubusercontent.com/7049700/112064594-77335800-8b20-11eb-8b7d-2d28b9fb5b10.png)

**Comment by CRIS19N** [comment]
> Haga una captura de pantalla de lo siguiente para el contexto:
> 
> ```
> $ cat /proc/version
> $ cmd.exe /c ver
> $ lsb_release -r
> $ update-alternatives --get-selections | grep iptables
> ```
> 
> Igual que:
> 
> ![imagen](https://user-images.githubusercontent.com/7049700/112064594-77335800-8b20-11eb-8b7d-2d28b9fb5b10.png)

tengo en mismo problema:

![image](https://user-images.githubusercontent.com/60001912/135148481-7f8cf1a3-6f8f-476a-8917-42e6291e65c4.png)
