### ISSUE TITLE
Unable to install new fonts into WSL

### ISSUE THREAD

**Issue by Zelatrix** [microsoft/WSL#6706]
I am trying to set up the JetBrains Mono font to use with WSL, and I have successfully managed to get it working with Windows Terminal, as that uses a JSON config file. But when I try and install the JetBrains Mono font which I have downloaded from NerdFonts as follows: 

```
unzip JetBrains Mono -d /usr/share/fonts/truetype
fc-cache -fv
```
and then restart my WSL terminal and check the settings, the list of fonts I can pick hasn't changed and I still can't use the new font. Is there something that I have done wrong here, as I feel like I've tried to put the fonts in every possible location I have found references to online, and none of them seem to have worked. In Windows Terminal, all I have to do is install the font and point the config file to the font, so why am I not able to do it as I have seen before using just WSL and not through the Windows Terminal?

**Comment by DHowett** [comment]
WSL is usually hosted in the Windows console host (a windows application that uses Windows fonts), which is fairly strict about the fonts it will allow you to use. Installing the font _inside the hosted distribution_ won’t help with that, unfortunately.

**Comment by Zelatrix** [comment]
Do you know if there's another way to do it, because I noticed that NeuralNine on YouTube has a video about his Vim setup, and it looks like he's managed to include the JetBrains Mono font in the font options for WSL, and I would like it if I could do the same.

**Comment by craigloewen-msft** [comment]
I'm closing this issue out since the issue template was deleted.

However as @DHowett mentioned, fonts are controlled by the Windows Console Host. In my mind the simplest way to do this here would be to find the JetBrains Mono font online, install that into Windows,  and then set that as your default font in Windows Console. Or upgrade to using Windows Terminal which makes that really easy! Thanks!
