### ISSUE TITLE
Cannot Run rsync from Scheduled Task

### ISSUE THREAD

**Issue by leeand00** [microsoft/WSL#6707]
New-Credential -Username 

```
$taskTrigger1 = New-ScheduledTaskTrigger -Once -At 2:50PM

$taskAction = New-ScheduledTaskAction `
   -Execute "powershell.exe" `
   -Argument "-ExecutionPolicy ByPass -File `"<path>\schtask_rsync\backup.ps1`""

$taskName = "Backup Stuff"
$description = "Rsync Backup Stuff"

Register-ScheduledTask `
   -TaskName $taskName `
   -Action $taskAction `
   -Trigger $taskTrigger1 `
   -Description $description

$taskPrinciple = New-ScheduledTaskPrincipal -UserId "Domain\someadmin" -RunLevel Highest
$taskSettings = New-ScheduledTaskSettingsSet -Compatibility Win8
Set-ScheduledTask -TaskName $taskName -Principal $taskPrinciple -Settings $taskSettings
Set-ScheduledTask -TaskName $taskName -User $taskPrinciple.UserID -Password '******'
```
_^The code that I use to create the scheduled task ^_

```
...
# Pull the creds for a user account that has WSL installed on it.
$cred = Get-StoredCredential -Target "some-non-admin-credz"

$psi = New-Object System.Diagnostics.ProcessStartInfo -Property @{
 RedirectStandardError = $true
 RedirectStandardOutput = $true
 UseShellExecute = $False
 UserName = $cred.GetNetworkCredential().Username
 Domain = $cred.GetNetworkCredential().Domain
 Password = $cred.Password
 WorkingDirectory = "C:\windows\"
 FileName = "wsl"
 Arguments = "-d Ubuntu-18.04 -e rsync -av --delete /mnt/c/stuff/ /mnt/o/stuff_bk/"
 WindowStyle = "Hidden"
}

$p = New-Object System.Diagnostics.Process
$p.StartInfo = $psi
$p.WaitForExit()
$p.ExitCode

...
```
**backup.ps1** - The powershell code that I use to backup my files with rsync...this is called by the scheduled task.

```
Windows PowerShell transcript start
Start time: 20210321103623
Username: domain\someuser
RunAs User: domain\someuser
Configuration Name:
Machine: MEBOX (Microsoft Windows NT 10.0.17763.0)
Host Application: c:\Windows\System32\WindowsPowershell\v1.0\powershell.exe -ExecutionPolicy ByPass -File C:\Users\someuser\OneDrive - SomeCompany\Projects\bak_schtask_rsync\backup.ps1
Process ID: 35180
PSVersion: 5.1.17763.1490
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.1490
BuildVersion: 10.0.17763.1490
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\temp\rsync_bk.txt

Attempting stop...
Internet services successfully stopped

Status for IIS Admin Service ( IISADMIN ) : Stopped
Status for Windows Process Activation Service ( WAS ) : Stopped
Status for World Wide Web Publishing Service ( W3SVC ) : Stopped
Starting Rsync 03/21/2021 10:37:39
ERRORS:

OUTPUT:

-1073741502
Ending Rsync 03/21/2021 10:38:38

Attempting start...
Internet services successfully started

Status for IIS Admin Service ( IISADMIN ) : Running
Status for Windows Process Activation Service ( WAS ) : Running
Status for World Wide Web Publishing Service ( W3SVC ) : Running
**********************
Windows PowerShell transcript end
End time: 20210321103847
**********************
```
_^The output of the Powershell Audit^_

Additional information about what has already been tired: [link]( https://stackoverflow.com/questions/66727315/process-runs-in-powershell-prompt-but-not-as-a-scheduled-task)

The return code from WSL is -1073741502 and I don't know why...but it also adds the following dialog box contents to my logs:

EventData -> Caption: `wsl.exe - Application Error`

EventData -> Message: `The application was unable to start correctly (0xc0000142).  Click OK to close the application.`

# Environment
Microsoft Windows [Version 10.0.17763.1518]

Release:        16.04

# Steps to reproduce
(see above)

**WSL logs**: See attached.

#  Expected behavior

The rsync command runs as a scheduled task and copies any and all changes from /mnt/c/stuff to /mnt/h/stuff

# Actual behavior

The scheduled task completes fine.  But rsync is never called from WSL instead it returns a negative error code and I get messages in my System Event Log see below:

The return code from WSL is -1073741502 and I don't know why...but it also adds the following dialog box contents to my logs:

EventData -> Caption: `wsl.exe - Application Error`

EventData -> Message: `The application was unable to start correctly (0xc0000142).  Click OK to close the application.`

**Comment by leeand00** [comment]
[wsl.zip](https://github.com/microsoft/WSL/files/6178290/wsl.zip)

**Comment by therealkenc** [comment]
Possibly variation #1917 and #4652 ➡️ #223

**Comment by leeand00** [comment]
> 
> 
> @leeand00 your Windows 10 build version is much older than what is currently available and there are lots of WSL improvements since that build. Are you able to upgrade your build to a more modern build like Windows 10 version 19H2?
> 
> I'll close this issue out for our bookkeeping as there isn't any actionable items for the WSL team here, but please reopen this issue if you do upgrade and hit the same problem! Thank you!

Yes, I just upgraded to 20H2 a bit after I posted this, I will have to give it another try with it upgraded.

**Comment by leeand00** [comment]
Yeah it's still doing the same thing after the 20H2 upgrade; do I need to upgrade to WSL2 as well?

**Comment by craigloewen-msft** [comment]
Please try using WSL 2 as I anticipate this would solve your issue! :)

**Comment by leeand00** [comment]
Is there a way to do this without losing my existing WSL stuff?

**Comment by leeand00** [comment]
Also can I still use Hyper-V?

**Comment by craigloewen-msft** [comment]
Yes! You can just run `wsl --set-version <distroName> 2` so for me using Ubuntu it's `wsl --set-version Ubuntu 2`. You can move back and forth any time. And yes you can still user Hyper-V with this setup.

Full info here:
https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2
