### ISSUE TITLE
Cannot connect to db servers from local network

### ISSUE THREAD

**Issue by klonuo** [microsoft/WSL#6708]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.867]
Your Distribution version: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

While running Postgres server or Redis server, I cannot connect to the servers from local network, but only from localhost.

For example I have these setting for Postgres:

 - `/etc/postgresql/12/main/postgresql.conf`:
```
listen_addresses = '*'
```

- `/etc/postgresql/12/main/pg_hba.conf`:
```
local   all    postgres                 peer

local   all    all                      peer
host    all    all         0.0.0.0/0    md5
host    all    all         ::0/0        md5

host    all    all         0.0.0.0/0    md5
host    all    all         ::0/0        md5
host    all    all         all          md5
```

These same setting work fine if I run Postgres on linux machine - I can connect from any device, but I cannot with WSL - with WSL I can access these servers only from localhost.

Similarly for Redis server.

Please advise what could be the problem, or if this is supported.

Thanks

**Comment by therealkenc** [comment]
> I cannot connect to the servers from local network

/dupe #4150
