### ISSUE TITLE
Allow configurable automatic shutdown of WSL if no users are logged in

### ISSUE THREAD

**Issue by heftymouse** [microsoft/WSL#6709]
**Is your feature request related to a problem? Please describe.**
Most of the time, after I'm done using WSL, I simply close the console window or Ctrl+D to quit it, as with most other terminal applications. This, however, does not shut down the VM, and it remains running and using system resources until I manually type `wsl --shutdown` into a console.

**Describe the solution you'd like**
I would like for there to be a system where WSL VM can automatically be stopped if no users are logged in. The timeout for this should be configurable in some way, perhaps in the `.wslconfig` file.

**Describe alternatives you've considered**
I attempted to use a shell script meant for ordinary Linux to shut down if no users are logged in, but this did not work as the shutdown failed with the following error:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to talk to init daemon.
```

**Comment by Biswa96** [comment]
Generally the WSL2 VM shutdown takes a minute or two. But if you want to shut it down after some seconds add these following lines in `C:\Users\username\.wslconfig` file:

```ini
[wsl2]
vmIdleTimeout=1
```

This will shutdown the VM after a little timeout. Source: https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20190

**Comment by heftymouse** [comment]
Thank you so much!
