### ISSUE TITLE
WSLENV=APPDATA/up fails to translate APPDATA variable

### ISSUE THREAD

**Issue by pagerc** [microsoft/WSL#6710]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.868]
Your Distribution version: Alpine Linux edge
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce
1. Update Windows SYSTEM environment with:
`WSLENV=APPDATA/up`
2. Launch WSL shell via Microsoft Terminal or WSLtty. 
3. Run `echo $APPDATA`
```
C:\Users\username\AppData\Roaming
```

#  Expected behavior
1. Update Windows SYSTEM environment with:
`WSLENV=APPDATA/up`
2. Launch WSL shell via Microsoft Terminal or WSLtty. 
3. Run `echo $APPDATA`
```
/mnt/c/Users/username/AppData/Roaming
```

# Actual behavior
3. Run `echo $APPDATA`
```
C:\Users\username\AppData\Roaming
```

**Comment by therealkenc** [comment]
From `cmd.exe` inside Windows Terminal, please screencap following for context:

```
C:\> echo %APPDATA%
C:\> echo %WSLENV%
C:\> reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" | find "WSLENV"
C:\> wsl.exe -d <some distro>  # or just wsl.exe
$ echo $APPDATA
```

![image](https://user-images.githubusercontent.com/7049700/112068865-0132ef00-8b28-11eb-96d0-0f1de8c7b06b.png)

**Comment by pagerc** [comment]
I can no longer replicate the issue. I believe I rebooted my system at some point and that may have fixed the environment settings.
