### ISSUE TITLE
dotnet publish get SSL error in WSL 1

### ISSUE THREAD

**Issue by zyd2001** [microsoft/WSL#6714]
I also report the problem to .Net team
https://developercommunity.visualstudio.com/t/dotnet-publish-get-SSL-error-in-WSL1/1379035

# Environment

```none
Windows build number: 10.0.18363.1440
Your Distribution version: Debian 10 or Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

I install the fresh new Ubuntu 20.04 from Microsoft store and follow the instruction on dotnet documentation.
https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-ubuntu#2004-
Then use
```
dotnet new console -o test
cd test
dotnet publish -r win-x64
```
which gives me the error

**WSL logs**: 

#  Expected behavior

![image](https://user-images.githubusercontent.com/25120292/112127194-22ffa500-8c00-11eb-8870-94adbe9afe05.png)
I got the expected behavior from another installation of Ubuntu 20.04 but in WSL 2 and also in a Ubuntu on my machine natively.
# Actual behavior

![image](https://user-images.githubusercontent.com/25120292/112126973-f055ac80-8bff-11eb-8a68-8f94d221d654.png)
I also try this with Debian 10 in the Microsoft Store which gives me the same output.

I first thought it may be my network problem, but after I got right behavior on my native Ubuntu installation, I thought it should be some problem with WSL. And I then change this WSL1 Ubuntu to WSL2. Everything works fine.
![image](https://user-images.githubusercontent.com/25120292/112128589-8807ca80-8c01-11eb-9f23-d2ce4977b733.png)

Another interesting finding is that when I export the correct version of WSL2 Ubuntu and import it again as WSL1 or just change the version to WSL1, the problem will not happen.

**Comment by craigloewen-msft** [comment]
This is something that works correctly in WSL 2, and we would recommend that you upgrade and use WSL 2 for this scenario.

**Comment by therealkenc** [comment]
Was not able to repro on WSL1, so the cause isn't a WSL1 syscall falling over. WAG the cause is some extern networking variable (commonly proxy related). If using WSL2 solves for the OP, so much the better.

![image](https://user-images.githubusercontent.com/7049700/112226454-6e5b8880-8beb-11eb-87f2-33cf3c579ed1.png)
