### ISSUE TITLE
Issue with Shell Scripting

### ISSUE THREAD

**Issue by buckydebugs** [microsoft/WSL#6716]
# Environment
Windows Build 19042.868
Ubuntu version 20210222
WSL 2
```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
1. Open notepad copy paste the following code
echo To get Area and perimeter
echo enter radius
read x
p=`expr 2 \* 22 / 7 \* $x`;
echo perimeter $p
a=`expr 22 / 7 \* $x \* $x`
echo area is $a
2.  Save it as .sh file
3. Open Ubuntu in windows terminal direct to the directory in which the file is saved.
4. Run using any shell command i.e. sh bash zsh etc
sh filename.sh

**WSL logs**: https://aka.ms/AAbnxa8

#  Expected behavior
![WhatsApp Image 2021-03-24 at 10 17 26 PM (3)](https://user-images.githubusercontent.com/73716542/112364943-144ae800-8cfd-11eb-97ad-68a75a0f7216.jpeg)

# Actual behavior
![Screenshot 2021-03-25 000141](https://user-images.githubusercontent.com/73716542/112365165-5542fc80-8cfd-11eb-8e20-39f0805542fd.png)

**Comment by benhillis** [comment]
This is an issue with Windows-style line endings (CRLF).  You have two options:
1. Change notepad to use unix-style line endings.
2. Run "dos2unix" on your script after saving in notepad.
