### ISSUE TITLE
Internet disconnection after working with wsl for a while

### ISSUE THREAD

**Issue by mmdbalkhi** [microsoft/WSL#6717]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`] Microsoft Windows [Version 10.0.19042.804]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL] Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] WSL2
```

# Steps to reproduce

- I connect to the Internet with WSL
- The whole Windows internet crashed
- For the whole problem, I have to disconnect and connect the computer internet

#  Expected behavior

Do not disconnect from the Internet while working
# Actual behavior
when I connect to the Internet with WSL. The whole Windows internet crashed and For the whole problem, I have to disconnect and connect the computer  internet

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows if applicable.

Does the problem ("whole Windows internet crashed") when you start `wsl.exe`, or when you access the internet inside WSL? For example, are you running `apt update` or some command. How are you disconnecting and connecting? Are you rebooting, disconnecting and reconnecting to wi-fi, or restarting a VPN?

**Comment by KomeilParseh** [comment]
Hi, when I do anything that requires the Internet, whether Linux updates or other things, the Internet of the Windows operating system is completely disconnected and I have to physically disconnect and connect the computer Internet. No VPN or DNS change system is running.
