### ISSUE TITLE
WSL shutdown -> WSL access is denied with administrator rights

### ISSUE THREAD

**Issue by anh193** [microsoft/WSL#6718]
# Environment

```none
Windows build number: Windows 10 v20H2 build 19042.870
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. `wsl --shutdown Ubuntu`
2. `wl`

**WSL logs**: 

#  Expected behavior
WSL should be booted up.
I've tried the following:
- `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
- `Restart-Service LxssManager`

# Actual behavior
`Access is denied.`

**Comment by benhillis** [comment]
Logs needed to diagnose.

**Comment by anh193** [comment]
> Logs needed to diagnose.

I realized that the issue was caused by the `.wslconfig` file, there I defined a wrong path to the kernel, correcting it solved the problem. Thanks!
