### ISSUE TITLE
kconfig based make always remakes

### ISSUE THREAD

**Issue by aquaherd** [microsoft/WSL#6719]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18363.1377]
Your Distribution version: Debian bullseye testing
Whether the issue is on WSL 2 and/or WSL 1: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
```

# Steps to reproduce

cross-compile a kconfig based make system, like the linux kernel or busybox, for arm-linux-gnueabi

**WSL logs**: 
- FEEDBACK HUB is blocked by your administrator

#  Expected behavior

After performing the first pristine make to be full, I'd expect incremental makes only to reflect on actual changes.

# Actual behavior

- A full remake is performed every time, even if no file has been touched.

# Additional Info
- Problem is in kconfig only:
  - plain makefile projects don't show this behaviour
  - automake based projects don't show this behaviour
- GNU make does not complain of any clock skews
- no suspend / hibernate, after fresh start of WSL2
- cross toolchain shows same behaviour regardless if 32 or 64 bits
- debian compiles the same kernel or busybox incrementally in a hyper-v vm
- debian compiles the same kernel or busybox incrementally in a WSL1
- void linux WSL2 shows the same issue so it does not seem to be a debian problem

**Comment by aquaherd** [comment]
**Addendum:**

I am trying to narrow down this issue. These are the most recent findings:

I tried to replicate it via docker-desktop on top of WSL2.

- docker image of debian:buster-slim compiles incrementally.
- docker image of debian:bullseye-slim **does not** compile incrementally.

I seem to have unearthed a new vs. old userland triggered incompatibility.

**Comment by therealkenc** [comment]
If `debian:bullseye-slim` compiles incrementally on WSL2 proper (I assume this is the case) then it is pretty safe to say this is a userland issue.

**Comment by aquaherd** [comment]
Agreed.

Since `debian:bullseye-slim` is already in hard freeze it may leak into future versions like `ubuntu:22.04` as well.
I also see this in `voidlinux:latest` which is a bleeding edge glibc distribution but not in `alpine:latest` which is musl only. 

Perhaps a recent glibc offers finer grained timestamps which are not yet available in WSL2?

**Comment by therealkenc** [comment]
Hard to say with certainty without a repro. If the behavior manifests on Linux on bare metal or in a full VM, but not WSL, then that would be a diverge. Confirm you are doing the build in `/home/you` not `/mnt/c/somewhere`. Generally if the behavior does not manifest on `/home/you` then it is unlikely it will manifest on a Linux box.

**Comment by aquaherd** [comment]
After some extensive tests on bare metal Linux I can confirm that this is a pure userland problem:

The gcc 9 and 10 shipped with debian bullseye can no longer generate working incremental kconfig for older kernels and busyboxes, whereas the gcc 8 in debian buster still can.

Sorry for the false alarm.
