### ISSUE TITLE
WSL2 not starting when prevent device installation Group Policy is Enabled

### ISSUE THREAD

**Issue by ardalon** [microsoft/WSL#6724]
Version: Microsoft Windows [Version 10.0.19042.870] ... Hardware: Bootcamped mbp pro 16" i7, 32gb

I am not installing any new devices when I start Ubuntu etc so I'm not sure why Enabling: "Prevent installation of devices not described by other policy settings" in the Local Group Policy Editor prevents any WSL2  linux distro from loading via Windows Terminal or from within powershell or from start menu results in a long pause and finally:

1) Enable this policy in Local Group Policy editor

2) pwsh:

`PS C:\Users\ardalon> bash
Error: 0x80041002`  

OR 

Start via GUI windows terminal 
`Error: 0x80041002  [process exited with code 4294967295]`

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.
