### ISSUE TITLE
pthread_cond_timedwait extremely slow

### ISSUE THREAD

**Issue by akodat** [microsoft/WSL#6726]
[timedWait.zip](https://github.com/microsoft/WSL/files/6216496/timedWait.zip)

When I compile and run timedWait.cc in the attached ZIP file using:

gcc -g -pthread timedWait.cc -o timedWait -lstdc++

under a native linux VM I see something like:

std = true, secs = 0.107078
std = false, secs = 0.106607

which is quite good. 100 one millisecond waits takes ~106-107 milliseconds. But when I run it under WSL (on a roughly comparable machine) I see:

std = true, secs = 0.148573
std = false, secs = 1.562075

The std = true runs use std::this_thread::sleep_for calls for one millisecond while the std = false runs use pthread_cond_timedwait. Obviously, times vary from run to run but these are typical values. While the std::this_thread::sleep_for times aren't thrilling, they're acceptable and a price worth paying for the convenience of WSL. But the pthread_cond_timedwait are crazy bad, taking 15+ milliseconds for a one millisecond timed wait. 

I tried messing around with the Windows timer resolution to no avail though the general advice is "don't do that". The 15 msec delay does seem suspiciously like the 15 msec timer resolution

The reason this is an issue is that the Google V8 JavaScript engine uses pthread_cond_timedwait in its profiling driver thread and the long delays wreak havoc with the profiling. FWIW, the Windows compilation of V8 simple does a CPU loop in its profilling driver thread because the Windows timer support exhibits the same behavior as we're seeing with pthread_cond_timedwait under WSL. This would lead me to believe that WSL is using standard Windows timers for pthread_cond_timedwait but something else for std::this_thread::sleep_for. 

I realize that this is kind of at the border of a bug report and a feature request but, in any case, it seems that pthread_cond_timedwait should have reasonably similar timings to what it does under Linux.

# Environment

```none
Windows build number: [run `cmd.exe /c ver`]

cmd.exe /c ver
Microsoft Windows [Version 10.0.19041.867]

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]

Release:        20.04

Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

```

# Steps to reproduce

Compile the program in the ZIP attachment with:

gcc -g -pthread timedWait.cc -o timedWait -lstdc++

And then run it using:

./timedWait

I 

**WSL logs**: 

#  Expected behavior

As noted above would expect to see timings like:
std = true, secs = 0.107078
std = false, secs = 0.106607

Seeing tmings like:

std = true, secs = 0.148573
std = false, secs = 1.562075

**Comment by therealkenc** [comment]
Thank-you for the report. I was not able to reproduce on either WSL1 or WSL2 on 21343. Please try the scenario under WSL2 with 19041 (going Insiders won't be necessary unless you want). If you'd like to keep your WSL1 intact, do a `wsl.exe --set-default-version 2` and then install a differently named distribution. Say [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab) vs [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab).

![image](https://user-images.githubusercontent.com/7049700/112904377-ba03ab80-909d-11eb-83c1-31f88077b821.png)

**Comment by akodat** [comment]
I feel like an idiot. I thought I had set the default before installing Ubuntu to 2 but I guess not. In my defense, it's a little less than obvious that I was running WSL 1. In any case sorry. I have a couple of other open issues that are now fixed.
