### ISSUE TITLE
Can't login in Ubuntu with the user which created the first time.

### ISSUE THREAD

**Issue by lusains** [microsoft/WSL#6727]
List my steps :
1、install wsl2 
2、install ubuntu
3、install Windows terminal
3、setting env(mirrors),user: lvshan
4、login in ubuntu with lvshan
![image](https://user-images.githubusercontent.com/7510547/112757271-a7e12900-901b-11eb-87c7-1e6d333d8c03.png)

I don't know if it's a problem~ 3Q

**Comment by DHowett** [comment]
There is a popular script that says it lets you use “systemd” by replacing your login profile with one that runs `nsenter`. Are you using this script?

**Comment by lusains** [comment]
> There is a popular script that says it lets you use “systemd” by replacing your login profile with one that runs `nsenter`. Are you using this script?

Thank you for your answer, but I used that script.
1、apt install -yqq fontconfig daemonize
2、`# Create the starting script for SystemD
vi /etc/profile.d/00-wsl2-systemd.sh
SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')

if [ -z "$SYSTEMD_PID" ]; then
   sudo /usr/bin/daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
   SYSTEMD_PID=$(ps -ef | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')
fi

if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
    exec sudo /usr/bin/nsenter -t $SYSTEMD_PID -a su - $LOGNAME
fi`

**Comment by DHowett** [comment]
Then that script is broken. This is not a WSL issue!

When you report a bug, make sure you include details like that 😄

**Comment by lusains** [comment]
> Then that script is broken. This is not a WSL issue!
> 
> When you report a bug, make sure you include details like that 😄

Thanks for your advice~ I'm trying to pre-install nsenter
