### ISSUE TITLE
wslconfig file being ignored

### ISSUE THREAD

**Issue by Joanthan17** [microsoft/WSL#6728]
So, I've compiled WSL2-Kernel, copied bzImage to %USERPROFILE% and created a .wslconfig file there pointing to this bran new kernel. However, WSL seems to be ignoring my .wslconfig file as uname -r still shows the original version. Any clues on this?

PS **I'm running version 20H2 (OS Build 19042) on windows home edition**

**Comment by Biswa96** [comment]
What is in the .wslconfig file?

**Comment by Joanthan17** [comment]
```
[wsl2]
kernel=c:\\wslkernel\\bzImage
memory=4GB # Limits VM memory in WSL2 to 4 GB
processors=2 # Makes the WSL2 VM use two virtual processors
```

**Comment by Joanthan17** [comment]
the wslconfig file location - C:\Users\Jonathan Elkabas\.wslconfig

**Comment by Smithienious** [comment]
The wslconfig file location should be `C:\Users\Jonathan Elkabas\.wslconfig`

**Comment by Joanthan17** [comment]
yeah I know, it was a typo  ><

**Comment by Reignable** [comment]
I'm having the same issue but not trying a different kernel.
The only setting I have is:
```
[wsl2]
memory=4GB
```

**Comment by Joanthan17** [comment]
I fear that the whole .wslconfig file thing is a feature available only on Pro edition although i didn't find any mention about it in the documentation

**Comment by therealkenc** [comment]
The `kernel=` feature is not limited to Pro.

**Comment by benhillis** [comment]
@Joanthan17 - are you running x64 or arm64?

**Comment by 0xbadfca11** [comment]
Make sure you are definitely using WSL2.
So far there is no evidence that you are using WSL2. You may be using WSL1 by mistake. 
- wsl.exe -l -v
  Is the ``VERSION`` column 2? 
- uname -r
  Isn't the kernel version 4.4? It's WSL1.

**Comment by Joanthan17** [comment]
@benhillis im using x64-based processor
@0xbadfca11 please have a look:
on debian:
![image](https://user-images.githubusercontent.com/72089812/113246237-48a44280-92c1-11eb-8741-c14fbc40a75c.png)
on PS:
![image](https://user-images.githubusercontent.com/72089812/113246264-5c4fa900-92c1-11eb-8849-5b6e99fe8246.png)

**Comment by Smithienious** [comment]
@Joanthan17 I'm not sure about the kernel, but `memory` and `processors` definitely requires WSL2. You can find more information [here](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md#configure-global-options-with-wslconfig).

**Comment by Joanthan17** [comment]
![image](https://user-images.githubusercontent.com/72089812/113252983-3f20d780-92cd-11eb-999e-0956c01e91db.png)

**Comment by Smithienious** [comment]
@Joanthan17 
```
wsl --set-version Ubuntu-20.04 2
```

**Comment by Joanthan17** [comment]
turns out i was running wsl1 and not wsl2 ><
![image](https://user-images.githubusercontent.com/72089812/113254223-fb2ed200-92ce-11eb-836a-e1cb27368feb.png)

now the wslconfig file work!
![image](https://user-images.githubusercontent.com/72089812/113254321-1568b000-92cf-11eb-89f0-41f4e6c7cd36.png)

guys thanks a lot for your help (:

**Comment by Reignable** [comment]
So I am on WSL2 and the wslconfig file is still being ignored
![image](https://user-images.githubusercontent.com/18505669/113256903-bfd9d680-92c1-11eb-82b5-183a6149db07.png)

**Comment by Smithienious** [comment]
@Reignable Are you using version 19041? `.wslconfig` is only available on build 10941 and later.

**Comment by Reignable** [comment]
@Smithienious I'm currently on 19042
![image](https://user-images.githubusercontent.com/18505669/113262531-a0927780-92c8-11eb-826d-816a34c841b7.png)

**Comment by Smithienious** [comment]
@Reignable can you show the content of wslconfig?

**Comment by Reignable** [comment]
```
[wsl2]
memory=4GB
swap=0
```

**Comment by Smithienious** [comment]
@Reignable how do you know the file is being ignored? Excessive ram usage?

**Comment by Reignable** [comment]
Yeah, especially when using Docker although when running other node applications it gets sucked up and doesn't get freed again

![image](https://user-images.githubusercontent.com/18505669/113266582-5a8be280-92cd-11eb-887b-9b475994e748.png)

**Comment by Smithienious** [comment]
@Reignable try running the program given [here](https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/). If WSL is still using more than 4GB, shut down WSL completely then try again. If it still doesn't work, delete and create a new `.wslconfig`, shutdown WSL then try again. If these don't work, you should create a new issue.

**Comment by Reignable** [comment]
Thanks @Smithienious, I've managed to limit it by updating Windows to 21343 which brings in the changed default WSL memory to 8GB which is fine for me. I've done with you suggested and `.wslconfig` still isn't recognised but it's not a problem anymore
Thanks for your help.

**Comment by ThiloFink** [comment]
You have to make sure that the **.wslconfig** is **not a txt file** but a wslconfig-file type.
![2021-07-13_11h07_12](https://user-images.githubusercontent.com/80856469/125424681-d1c15b7b-3951-47f1-8161-4b1c32f25c5e.png)

Create the .wslconfig not with a text-editor, but inside the `C:\Users\<user>` with:
`code .wslconfig
`

**Comment by starkblaze01** [comment]
Make sure when you create a .wslconfig file the type of the file is WSLCONFIG File, not TXT Document:
![ba0fe00d-6035-4578-bda2-a02e012bd76c](https://user-images.githubusercontent.com/22374162/162901684-29d30775-4952-4867-8414-c3e3894285df.jpg)

**Comment by moon548834** [comment]
> You have to make sure that the **.wslconfig** is **not a txt file** but a wslconfig-file type. ![2021-07-13_11h07_12](https://user-images.githubusercontent.com/80856469/125424681-d1c15b7b-3951-47f1-8161-4b1c32f25c5e.png)
> 
> Create the .wslconfig not with a text-editor, but inside the `C:\Users\<user>` with: `code .wslconfig `

you save my life!!

**Comment by 24628** [comment]
Hello can some help me, I have followed all the steps here. But the issue is still there 
![image](https://github.com/microsoft/WSL/assets/32679142/53e012fe-5df8-4030-94d5-ee2879fcf7f8)
Its saved as an WSConfig so not a text what should be correct the insides of the files are as follows 
![image](https://github.com/microsoft/WSL/assets/32679142/46883e31-0ea4-4bf5-8175-3d7971de89f7)
But some1 how the memory goes to 8k what is the default max setting for windows but it just ignore the file?

the file it self: 
![image](https://github.com/microsoft/WSL/assets/32679142/f860da80-97b1-41b7-9a63-98e54b19e147)

If some1 can let me know what I'm doing wrong it would be amazing
