### ISSUE TITLE
ssh not working with wsl 2

### ISSUE THREAD

**Issue by techbrarian** [microsoft/WSL#6732]
When I try to ssh into boxes I'm told DNS cannot resolve. Attempts to restart the relevant service are ineffective; I had to download another wsl instance and set it to version1 to use ssh.

**Comment by Biswa96** [comment]
Are you ssh-ing from WSL2 into another box? Does deleting `/etc/resolv.conf` have any effect? i.e.

```
sudo rm /etc/resolv.conf
echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
```

**Comment by techbrarian** [comment]
Yes, I was. That's a common use case for me for a linux shell. No, deleting
resolv.conf does not seem to solve the issue.

Best regards,

*Jason Bengtson*


*http://www.jasonbengtson.com/ <http://www.jasonbengtson.com/>*

**Comment by therealkenc** [comment]
Please collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and link `wsl.etl`. Also please identify any third-party networking software that has been installed on Windows.

Please also post the output of:
```
$ cat /proc/version
$ wsl.exe /c ver
$ ip addr show eth0
$ ping 1.1.1.1
```
The `ip` command is in `iproute2` (`sudo apt install iproute2`).
