### ISSUE TITLE
wsl1  The specified network name is no longer available

### ISSUE THREAD

**Issue by Iatbzh** [microsoft/WSL#6736]
# Environment

```none
Windows build number:  10.0.19042.867]
Your Distribution version: Ubuntu-20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

**WSL logs**:  https://aka.ms/AAbr57v

#  Expected behavior

I can start Ubuntu 20.04 by inputting bash through windows + R
# Actual behavior

![image](https://user-images.githubusercontent.com/28798107/112932731-06f48a00-9151-11eb-9938-3edab116c414.png)

**Comment by Iatbzh** [comment]
wsl2 和VMware冲突



***@***.***
 
From: therealkenc
Date: 2021-04-01 02:53
To: microsoft/WSL
CC: Iatbzh; Author
Subject: Re: [microsoft/WSL] wsl1 The specified network name is no longer available (#6736)
There is no way to tell what might have happened in the 20 days for a repro. Suggestion would be to install a WSL2 distro.

**Comment by Iatbzh** [comment]
There is a conflict between wsl2 and VMware. Although there are improvement methods, it will make VMware difficult to use, so I choose the combination of wsl1 and VMware. However, at present, this problem appears after I update the system patch during this period, so I hope to solve this problem

**Comment by Iatbzh** [comment]
> 没有办法告诉您20天内可能发生的问题。建议是安装WSL2发行版。
There is a conflict between wsl2 and VMware. Although there are improvement methods, it will make VMware difficult to use, so I choose the combination of wsl1 and VMware. However, at present, this problem appears after I update the system patch during this period, so I hope to solve this problem

**Comment by Iatbzh** [comment]
> There is no way to tell what might have happened in the 20 days for a repro. Suggestion would be to install a WSL2 distro.
I've made an update. Please check. There are logs and screenshots in the feedback center

**Comment by djibal** [comment]
`need-repro`
`I am running into`: Version 10.0.19042 Build 19042
`Bash` failure-launch
`Ubuntu 20.04 LST`: failed with error 0x8000000d , error illegal state change was requested
