### ISSUE TITLE
WSL stucks in Windows Insider preview after update to the build .21343.1000 (Feature pack)

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/WSL#6737]
# Environment

```none
Microsoft Windows [Version 10.0.21343.1000]
Your Distribution version: [any]
Whether the issue is on WSL 2 Lxss service hangs
```

# Steps to reproduce

After upgrade to the Insider dev-preview wsl command
 wsl -l -v hangs.
wsl --status hangs too 

Lxss service is shown as running / manual
Attempts to restart Lxss Manager result in 
![LxssManagerRestart](https://user-images.githubusercontent.com/54495912/112867126-352b8880-90c3-11eb-9157-8485ff25b742.png)

**WSL logs**: 

#  Expected behavior
It was OK in the post-2004 builds and  pre - 21xxx (Feature pack) Insider preview builds.

# Actual behavior
All wsl commands stuck, Attempt to open "Linux" folder in the File explorer stucks
Task manager -> Performance shows almost zero CPU and Disk usage.

Root filesystems of some Linux distros are located on the separate partition (Disk D) although the same physical SSD disk.

**Comment by PavelSosin-320** [comment]
Ooh. I just learned something new about this Feature pack:

1. It allows NVidia GPU to allocate as much shared memory as it wants and it wants 6Gb in the case of GForce 20xx leaving less than 10GB for WSL. I'm afraid in Amper-based workstation it will be even more.
2. IPConfig doesn't show WSL V-Switch Network interface WSL. It disappeared after the upgrade.
3. When I'm trying to import my saved as tar file distro back into WSL it doesn't show any signs of progress. Both
 WSL.exe and svchost.exe                  13092 LxssManager are running but The resource management looks too low.

**Comment by therealkenc** [comment]
Thank-you for the report. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows if applicable. Catch the `wsl.exe --status` or `wsl.exe -l -v` hang while recording.

**Comment by PavelSosin-320** [comment]
@therealkenc Unfortunately, my WSL logs are too old and created on the same day when I successfully started WSL.  Then WSL started to be unresponsive and hangs on any wsl command as well on any attempt to stop or restart LXss service manually as I mentioned above without displaying any CPU or Disk workload. No new WSL log is created 
Something went wrong in the latest Feature pack serial of builds that 1st failed to start Windows then displayed ugly Desktop UI then allocated 1/3 memory to GPU throttling System Disk I/O to zero. I'm using the gaming Laptop as a workstation (I5Gen9 +Geforce 20xx+16Gb memory:
Device name	MSI
Processor	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	00BDFB82-86C6-41CF-A07D-A8B3C67A5A03
Product ID	00330-80000-00000-AA642
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
With
Edition	Windows 10 Pro Insider Preview
Version	Dev
Installed on	‎27/‎03/‎2021
OS build	21343.1000
Experience	Windows 10 Feature Experience Pack 321.7401.0.3

Did somebody in Microsoft test Feature packs on the Laptops purchased from Amazon?

**Comment by PavelSosin-320** [comment]
@therealkenc WSL works only with newly installed / upgraded distros, Fedora33 remix -> Fedora 34 in my case. All re-installed from Microsoft Store and reimported using wsl --import distros are stillborn:
_wsl -l -v
  NAME            STATE           VERSION
* fedoraremix     Running         2 <--fresh install
  Fedora34        Installing      2 <-- Import, more than 24H in the same state.
  Ubuntu-20.04    Installing      2 <-- re-install from MS Store._
Maybe, running more than 1 distro with networking is impossible by design when Distro ports are forwarded to the Host ports? In this case, randomization is necessary. 
Force-terminate-others is an option too.
