### ISSUE TITLE
"System has not been booted with systemd as init system (PID 1). Can't operate" when i run  timedatectl command in WSL1

### ISSUE THREAD

**Issue by ZihaoXingUP** [microsoft/WSL#6739]
![image](https://user-images.githubusercontent.com/68001792/113082170-8bf0a980-920c-11eb-991e-193c3cc1b2de.png)

**Comment by therealkenc** [comment]
This is effectively /dupe #1579 ➡️ #994. The [`systemd-timesyncd`](`https://man7.org/linux/man-pages/man8/systemd-timesyncd.service.8.html`) service is not running (on WSL1 or WSL2). This ask has different specifics than `[systemctl(1)](https://man7.org/linux/man-pages/man1/systemctl.1.html)`, but any out-of-box solution for WSL `systemd` would in all likelihood address both. In the event #1579 flips status but `[timedatectl(1)](https://man7.org/linux/man-pages/man1/timedatectl.1.html)` is still not supported out of the box we can revisit/reopen.
