### ISSUE TITLE
is .wslconfig file NOT supported in Windows Home edition?

### ISSUE THREAD

**Issue by Joanthan17** [microsoft/WSL#6740]
i've been trying for many hours to run the .wslconfig file and read pretty much everything about the problem online and for some reason its still not configured properly to run at my system. 

is there any chance this feature is disabled on Windows Home edition?

thanks a lot for your time (=

**Comment by shawnz** [comment]
Do you mean "wslconfig.exe"? That only existed prior to Windows 10 version 1903. Now you should use "wsl.exe" instead.

See: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#managing-multiple-linux-distributions-in-earlier-windows-versions

**Comment by Joanthan17** [comment]
hi @shawnz , thanks for your answer. 
thats not what i meant.  ".wslconfig" file is the file for configuring global WSL options. 

```
You can configure global WSL options by placing a .wslconfig file into the root directory of your users folder: C:\Users\<yourUserName>\.wslconfig. Many of these files are related to WSL 2, please keep in mind you may need to run wsl --shutdown to shut down the WSL 2 VM and then restart your WSL instance for these changes to take affect.
```
from https://docs.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by Joanthan17** [comment]
im trying to add a different kernel. 

i opened another issue regarding this - #6728
