### ISSUE TITLE
Can't install WSL1 with hardware virtualization disabled on Insider builds

### ISSUE THREAD

**Issue by shawnz** [microsoft/WSL#6741]
# Environment

```none
Windows build number: Version 10.0.21343.1000
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

Try and install Ubuntu on a fresh installation of Windows with hardware virtualization disabled.

**WSL logs**: [wsl.zip](https://github.com/microsoft/WSL/files/6236937/wsl.zip)

#  Expected behavior

WSL1 is installed.

# Actual behavior

The following message is shown (regardless of whether Virtual Machine Platform is installed or not):

```none
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

Running `wsl.exe --set-default-version 1` has no effect.

**Comment by therealkenc** [comment]
Thank-you for the report and logs. 

> with hardware virtualization disabled

Do you mean not-enabled in your BIOS?

**Comment by shawnz** [comment]
As a workaround I was able to install the Ubuntu rootfs from here: https://cloud-images.ubuntu.com/focal/current/ using `wsl --import`. This worked on both architectures

Also, I think this may be a dupe of #5768 which appears to have been wrongly closed.

**Comment by benhillis** [comment]
#5768 is a different issue, this is a recent regression in Insider builds, fix is on the way.

**Comment by shawnz** [comment]
Thank you for the info!

**Comment by shawnz** [comment]
This now appears to be working for me on build 21354
