### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070005

### ISSUE THREAD

**Issue by agowa** [microsoft/WSL#6744]
Regression of #4004 and #3020

# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.21343.1000]`
Your Distribution version: Alpine Linux
Whether the issue is on WSL 2 and/or WSL 1: While installing (call to `_registerDistribution`)
```

# Steps to reproduce

Call:
```
HRESULT WslApiLoader::WslRegisterDistribution(PCWSTR tarGzFilename)
{
	HRESULT hr = _registerDistribution(_distributionName.c_str(), tarGzFilename);
	if (FAILED(hr)) {
		Helpers::PrintMessage(MSG_WSL_REGISTER_DISTRIBUTION_FAILED, hr);
	}

	return hr;
}
```

(Or use Alpine Linux App from Store)

**WSL logs**: https://github.com/agowa338/wsl_etl/blob/main/wsl.etl?raw=true

#  Expected behavior

API Call succeeds

# Actual behavior

API Call throws Access Denied instead of registering the tar.gz

# Workaround

1. Uninstalling:
* Hyper-V
* Hypervisor Platform
* Container
* WSL
2. Reboot
3. Reinstall all 4 features
4. Reboot
5. Call the API again. Now it works.

**Comment by adrastogi** [comment]
Thanks for reporting the issue, and for including a trace. The access denied is coming from an attempt to open HKCU (via [RegOpenCurrentUser](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regopencurrentuser)). 

Can you check the permissions on that key for your device? And can you share more details about how you are invoking that code fragment? 

On a clean VM of 21343, after running wsl.exe --install to get WSL configured, I was able to install the Alpine Linux trial from the Store, and was also able to programmatically register [Alpine's .tar.gz](https://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.4-x86_64.tar.gz) from a test console app. So I'm suspecting there's something more subtle going on in the environment where you're seeing this.

**Comment by agowa338** [comment]
> Can you check the permissions on that key for your device?

Unfortunately I cannot, as I already ran the workaround steps above which fixed the issue. Maybe @airtonix can help (but for him the issue occurred in October)

> And can you share more details about how you are invoking that code fragment?

Sure, but it's basically similar to the reference implementation: https://github.com/agowa338/WSL-DistroLauncher-Alpine/blob/master/DistroLauncher/DistroLauncher.cpp

> On a clean VM

I suspect it's a bug with the windows release upgrades. At least that was the root of the issue the last few times this occurred. Sadly I haven't been able to find a consistent way to trigger this issue (some semi-annual upgrades go without this problem others cause it). But uninstalling and reinstalling the features listed above fixed the issue in all of these cases.

**Comment by F9Alejandro** [comment]
Here is what I have for permissions on my HKCU:
`Path   : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : NT AUTHORITY\RESTRICTED Allow  ReadKey
         NT AUTHORITY\SYSTEM Allow  FullControl
         BUILTIN\Administrators Allow  FullControl
         DESKTOP-7R3414T\Bytor Allow  FullControl
         APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  ReadKey`

Omitted entries starting with S-*, as well as Audit and Sddl. Please let me know if these are needed.

**Comment by kiatng** [comment]
I encoutnred the following error when installing from _Microsoft Store_:

```
Temporary directory: C:\Users\kiat\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : https://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.4-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\kiat\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: 8e21c85c4a5bb406180136aa03f814c56ffc7498ba7886c5ea13fec92d528ead

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
WslRegisterDistribution failed
Error: 0x80070005 Access is denied.

Press any key to continue...
```

I am running _Version 2004 (OS Build 19041.985)_. The HKCU is

```
PS C:\Users\kiat> $acl = Get-Acl HKCU:
PS C:\Users\kiat> $acl |Format-List


Path   : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : NT AUTHORITY\RESTRICTED Allow  ReadKey
         NT AUTHORITY\SYSTEM Allow  FullControl
         BUILTIN\Administrators Allow  FullControl
         WIN10\kiat Allow  FullControl
         APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  ReadKey
         S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681 Allow
         ReadKey
Audit  :
Sddl   : O:BAG:SYD:P(A;OICI;KR;;;RC)(A;OICI;KA;;;SY)(A;OICI;KA;;;BA)(A;OICI;KA;;;S-1-5-21-2545381894-377512648-30371149
         96-1001)(A;;KR;;;AC)(A;;KR;;;S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-40
         53264122-3456934681)
```

I am not able to resolve the issue as I have close to zero knowledge on WSL and OS in general.

**Comment by Amondale** [comment]
What worked for me when I got this error: 

- Open *Elevated* (Administrator) Powershell or Command window
- cd %TEMP%\wsl_Alpine_setup
- mkdir C:\AlpineWSL [or wherever you want to put Alpine]
- run command: WSL --import Alpine C:\AlpineWSL .\install.tar.gz
- run command: WSL -d Alpine

You will be logged on as the almighty root user, but Alpine is a very lightweight distro, and it is unlikely you will do much that you wouldn't want root privileges to execute. If you are running Windows Terminal (you should) you'll see the Alpine distro added to your available launchers. Check out https://docs.microsoft.com/en-us/learn/modules/get-started-with-windows-subsystem-for-linux/7-manage-multiple-distributions which will walk you through creating a (non-root) user in the distro, and then setting that user to default.

**Comment by agowa338** [comment]
any update on this?

**Comment by MichaIng** [comment]
@Amondale 
Many thanks, this worked, which means it is a permissions issue with the directory, the `install.tar.gz` is located, or where it is tried to be installed to? In my case it's `C:\Program Files\WindowsApps\TheDebianProject.DebianGNULinux_*`, which is pretty much the Windows apps default, i.e. *should* work. But I'm not sure where it would create the VHDX normally.

**Comment by cabiamdos** [comment]
I got the same exact problem!
After entering registry editor, take ownership of the files, installing and reisntalling wsl and the update; what worked for me is to
move the kali linux files of the microsoft store, to somewhere else (like the Downloads folder for example), and then click install.

And worked everything

**Comment by jackeymason** [comment]
wsl --update
wsl.exe --list  
...to see what linux distros you have.
Oddly, though wsl --update reported "The most recent version of Windows Subsystem for Linux is already installed."
I could start Ubuntu after running it.

**Comment by MichaIng** [comment]
```
wsl.exe --list
```
Due to the error this issue is about, the list was empty, hence no WSL could start. But maybe the issue has been fixed and the `wsl --update` installed one automatically? I will test with an additional distro.

**Comment by andersonn-roberto** [comment]
If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.

It was installed here after running `wsl --update` command.

![image](https://user-images.githubusercontent.com/6409097/223299686-461dbf35-2c37-4129-924a-bddccaa73b06.png)

**Comment by venimus** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223299686-461dbf35-2c37-4129-924a-bddccaa73b06.png)

Works after I removed and did `wsl --update` again (required it). Which installed the app again after that. I guess store tries to update it and mess with the permissions

**Comment by chowieuk** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223299686-461dbf35-2c37-4129-924a-bddccaa73b06.png)

Thank you very much for this solution. - I can echo what venimus said in that it works as expected again after removing and then running `wsl --update`

For those concerned about their data, the individual distros installations I have seem to be unaffected by this procedure - just made accessible again.

**Comment by Mistic92** [comment]
How do you remove it? I don't have uninstall button in Microsoft Store.

**Comment by mari0rh** [comment]
After the issue, I restarted my computer. Ran `wsl --update` and everything worked again (even when nothing was updated tho)

**Comment by tschoeller** [comment]
I faced this issue as well and ThreatLocker was blocking vmw.exe/vmcompute.exe. Switched to learning mode for the install.

**Comment by crramirez** [comment]
Today I faced the same issue. Using the Uninstall Store version, restart, `wsl --update`

Just now instead of issuing `wsl --update` I directly installed the previous release [1.2.5](https://github.com/microsoft/WSL/releases/tag/1.2.5) and finally the issue is gone. Looks like there is a new issue with the recently shipped 2.0.9 version

**Comment by gerroon** [comment]
The issue is still there with WSL 2 .  

I literally followed MS help page and this tuff fails. I already have working Debian and Mint so it is not my WLS2 installation. This is really sad.

What I did based on https://learn.microsoft.com/en-us/windows/wsl/install-manual

`Invoke-WebRequest -Uri https://aka.ms/wslubuntu2204 -OutFile Ubuntu.appx -UseBasicParsing`

`Add-AppxPackage .\app_name.appx`

It fails to start with the error in the original post.


This worked for me

```
I got the same exact problem!
After entering registry editor, take ownership of the files, installing and reisntalling wsl and the update; what worked for me is to
move the kali linux files of the microsoft store, to somewhere else (like the Downloads folder for example), and then click install.

And worked everything
```

**Comment by Takuchan** [comment]
I deleted C:\Users\username.wslconfig and it fixed the problem.
