### ISSUE TITLE
suddenly no more sound over HDMI?

### ISSUE THREAD

**Issue by RangerFX4** [microsoft/WSL#6746]
Hi,

I installed wsl2 and docker desktop. It works but then suddenly when I want to watch YouTube videos/Netflix/Spotify, I cannot hear any sound through my tv. I check if my tv and speaker is broken with my ps4 and it works. Also, when I access the pc remotely, I have sound in TeamViewer. btw I reinstalled windows to check if PC HDMI port or cable is broken but everything works but when I install again Docker Desktop its not working again. Please Help !

Thanks!

**Comment by RangerFX4** [comment]
got the problem solved! 

[https://social.technet.microsoft.com/Forums/en-US/416ff4fc-8e9c-400c-978d-2e43e23b901c/intel-display-audio-and-hyper-v?forum=win10itprovirt](url)

**Comment by rosti-il** [comment]
> got the problem solved!
> 
> [https://social.technet.microsoft.com/Forums/en-US/416ff4fc-8e9c-400c-978d-2e43e23b901c/intel-display-audio-and-hyper-v?forum=win10itprovirt](url)

Your URL can't be opened. Could you explain what was the solution on your case?

**Comment by AthulNoobie** [comment]
> got the problem solved! 
> 
> [https://social.technet.microsoft.com/Forums/en-US/416ff4fc-8e9c-400c-978d-2e43e23b901c/intel-display-audio-and-hyper-v?forum=win10itprovirt](url)

Link is not working, I have the same sound problem with wsl
