### ISSUE TITLE
`sudo apt update` Fails in WSL2

### ISSUE THREAD

**Issue by adamgranthendry** [microsoft/WSL#6748]
# Environment

```none
Windows build number: 10.0.18363.1440
Your Distribution version: 19.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
```

# Steps to reproduce

1. I am on a corporate computer and am not permitted to upgrade Windows 10 beyond Version 1909 (OS Build 18363.1440). I am also not permitted to use the Windows Insiders Build.
2. Our company uses the Juniper PulseSecure VPN (Version 9.1.7 (2525))
3. I have installed WSL 2 and Ubuntu 18.04-LTS on my machine.
4. I attempt to run the following

```sudo apt update```

which yields a `Connection failed` error for

```http://archive.ubuntu.com/ubuntu bionic InRelease```

5. I have attempted writing `/etc/resolv.conf` as

```
nameserver **.**.***.***
search corporate.proxy.address.com
```

where the `*`s are number placeholders (I have entered the appropriate IP and url's corresponding to my company's DNS/proxy). The appropriate nameservers were determined by running the following in `PowerShell`:

```
Get-DnsClientServerAddress -AddressFamily ipv4 | Select-Object -ExpandProperty ServerAddresses
```

I have also set `/etc/wsl.conf` to

```
[network]
generateResolvConf = false
```

6. Per #4253, I have tried setting the `MTU` equal to that of our VPN interface (1500) as follows:

```sudo ifconfig eth0 mtu 1500```

7. Per #5061, I have tried running the following in `PowerShell`:

```New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow```

8. Per #5336, I have tried this in Command Prompt as Admin:

```
wsl --shutdown
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns
```

and then restarted my PC.

9. Per #5061, I have tried creating a `proxy.conf` in `/etc/apt/apt.conf.d` with the following lines:

```
Acquire {
     HTTP::proxy "http://corporate.proxy.address.com:port";
     HTTPS::proxy "http://corporate.proxy.address.com:port";
}
```

10. I have tried running the `WSL2-Net-Fix.ps1` script from [this gist](https://gist.github.com/danvy/9486bf730371436131cb888ff4c2ceb6)

11. I can successfully run `ping 8.8.8.8` and `ping archive.ubuntu.com`

12. `Get-NetAdapter` in `PowerShell` shows `vEthernet (WSL)` is up.

13. I have disabled and re-enabled each of the `Hyper-V Virtual Switch Extension Adapter`'s in `Device Manager`.
14. Per [this gist](https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6), I have tried running the following in `PowerShell`:

```
PS> Get-NetIPInterface -InterfaceAlias "vEthernet (WSL)" | Set-NetIPInterface -InterfaceMetric 1 
PS> Get-NetAdapter | Where-Object {$_.InterfaceDescription -Match "Cisco AnyConnect"} | Set-NetIPInterface -InterfaceMetric 6000
```

Nothing has worked so far.

**WSL logs**: 

#  Expected behavior

`sudo apt update` works as expected (updates `apt`)

# Actual behavior

`sudo apt update` fails

**Requests:**

1. Has this issue been fixed?
2. If it has, can the solution be backported to those using the same Versions of Windows 10 (non-Insider's Edition)?

**Comment by adamgranthendry** [comment]
As an additional item,

3. What is the minimal build of Windows 10 where this issue does not surface for WSL 2?

**Comment by therealkenc** [comment]
PulseSecure landing zone is /dupe #5068

**Comment by adamgranthendry** [comment]
Lastly, I am dubious that this problem can be classified as a "dupe" of anything as Microsoft has yet to identify the root cause of the problem. Since they cannot conclusively say any VPN is the culprit of the issue, it is unclear which issue this problem should go under. I am afraid this problem will inevitably get lost in an endless array of user comments and temporary fixes with no true solution in sight.

**Comment by adamgranthendry** [comment]
@therealkenc and @msftdata Please also note, our company uses Blue Coat Unified Agent and CrowdStrike. This issue is still occuring for me when I am explicitly off Pulse Secure. I just wanted to update my issue to include that info.

**Comment by xbmlz** [comment]
if you use vpn proxy, ni needed `rm -rf /etc/apt/apt.conf.d/proxy.conf`
