### ISSUE TITLE
NO WAY to install pytorch + cuda + wsl 2 using guides from Microsoft, Pytorch and Nvidia

### ISSUE THREAD

**Issue by helviett** [microsoft/WSL#6752]
Please review your guide and do something. There is no way to get pytorch working using CUDA on modern WSL 2 (spent hours trying to solve it). Also there is no compatible version of cuda for wsl available (pytorch requires 10.1 or 11.1, nvidia allows you to install 11.2 only).

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by WSLUser** [comment]
> pytorch requires 10.1 or 11.1

So file a bug on pytorch to support 11.2. That's not a WSL actionable.

**Comment by patfla** [comment]
What do you mean by "no way to install" - you need to show some of your work, or rather the errors.

I have all these things installed.  The only problem is that CUDA isn't working at the moment.  Got the latest Nvidia (Win10) driver, 465.89, but still no joy:

> MyId@DESKTOP-930EG0A:~$ nvidia-smi
> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
> 

And all my other software components are up-to-date.  Insider Preview Build 21343.rs_prerelease.210320-1757.  Have done 

```
wsl --update
sudo apt update
sudo apt upgrade
```

But CUDA won't run.  Neither nvidia-smi nor the other thing I test /usr/local/cuda/samples/1_Utilities/deviceQuery

etc.

Nor torch or torchvision - with CUDA - which is what I ultimately want.

**Comment by jhirschibar** [comment]
https://medium.com/swlh/how-to-install-the-nvidia-cuda-toolkit-11-in-wsl2-88292cf4ab77#:~:text=1%20Visit%20the%20official%20website.%202%20Click%20%E2%80%9CJoin,9%20Click%20%E2%80%9CSubmit%E2%80%9D.%2010%20Enter%20user%20information.%20

This guide works with latest build

**Comment by NUNIDEcainiao** [comment]
I tried to install nvidia-docker using wsl but I failed

**Comment by NUNIDEcainiao** [comment]
I don't think it can support GPU at the moment

**Comment by xBLOCK-HEADx** [comment]
Any update on this? I feel like I'm nearly there but not quite, build ran at 100% CPU for a long time going through endless permutations of
```
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Compiling  reduce_scatter.cu                   > /pytorch/build/nccl/obj/collectives/device/reduce_scatter_sumpostdiv_bf16.o
```

then finally gave me:

```
[  1%] No install step for 'nccl_external'
[  1%] Completed 'nccl_external'
[  1%] Built target nccl_external
gmake: *** [Makefile:160: all] Error 2
```

I'm on 21H2 build 19044, Linux Kernel is  4.4.0-19041, CUDA 11.8 installed on Linux Debian 11 distro.
