### ISSUE TITLE
"Crash" File Explorer's "access" to show Hard Drive list, Network list and Quick access list (for lack of better words)

### ISSUE THREAD

**Issue by Sausbolle** [microsoft/WSL#6754]
Not sure what to describe this as, but you can "crash" (I assume some lock or similar is set and never released) that hinders File Explorer to access the list of Quick access entries, Hard Drives, OneDrive and Network.

If you use youtube-dl to download multiple files (mp3) and add video thumbnail in ID3 tag while at the same time have File Explorer open in the folder you download to you will crash both the youtube-dl and Windows access to list  drives and Quick access, network etc.
_Note: This is only the case if you download to a folder in your home directory not if you download to a directory outside it_

You can still browse the file system as normal except the `C:\Users\[uername]\Downloads` folder by typing in drive letter or path you want to navigate to.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.867]
Your Distribution version: Kali Linux - Release: 2021.1
WSL version: Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC))

ffmpeg: ffmpeg version 4.3.2-0+deb11u1
youtube-dl: 2021.04.01
```
_Note: this was also the case when I ran Ubuntu_

# Steps to reproduce

## Prerequirement
* Install youtube-dl
`sudo apt install python3-pip ffmpeg atomicparsley`
`sudo pip3 install --upgrade youtube-dl`

(note: Have set File Explorer to open in "This PC", but probably not important at all)

## Reproduce
* Create a folder in Windows to download to and have it open in File Explorer
Ex: `C:\Users\[uername]\Downloads\Test`

* Navigate to this folder in Linux
`cd /mnt/c/Users/[username]/Downloads/Test/`

* Start a test download _(link is for test purposes)_ to this folder using the following command
`youtube-dl -i -o "%(playlist_index)s - %(title)s - %(id)s - %(upload_date)s.%(ext)s" --embed-thumbnail --add-metadata -f 140 https://youtu.be/EZzbh9YjVhQ?list=RDEZzbh9YjVhQ`
_(many other combinations of youtube-dl flags might give same result)_

* Go to File Explorer and watch it update the list of files
* youtube-dl will stop running after a little while
* File Explorer will start the green "refresh" progressbar at top that never completes

* Try open an new File Explorer window and you will be presented with an empty window (with refresh load "bar" at top) and only having
*** Quick access (empty)
*** This PC (empty)
_Note: can take a few seconds before this complete crash happens_

# Steps to fix
None that I have found, tried the following:
* Tried to kill the youtube-dl process (both SIGTERM, SIGKILL)
* Tried to terminate the wsl distro `wsl -t kali-linux`
* Tried shutting down `wsl --shutdown` (runs never completes)

Only way I've been able to use File Explorer again normally and see Hard Drives and Network etc. is to do a full reboot.

**Comment by Sausbolle** [comment]
I can add/clarify that if you don't have File Explorer open in the folder you download to this "crash" don't happen.

**Comment by therealkenc** [comment]
Thank-you for the report and concise repro steps. I was not able to reproduce the problem with 21343. It is _possible_ the problem has been addressed. Plausible work-arounds are (a) use `youtube-dl` in `/home/you/Downloads` or (b) use a CIFS share with `cifs-utils` package and `mount.cifs`.

![image](https://user-images.githubusercontent.com/7049700/113634831-542a9d00-9624-11eb-9929-3edd6c65170c.png)

**Comment by Sausbolle** [comment]
Sorry for probably adding more confusion with this reply. Initially I thought all was solved after updating Windows, but it just got a bit more inconsistent in how to reproduce/induce the error.  _My initial thought that the update had fixed the error, was that I could download the playlist in the "Steps to reproduce" without causing the crash (tried several times) which prior to update caused the "crash" to happen every time._

* _Note: One thing that might be contributing factor to trigger this bug is that I have the folder on "Details" view and not "List"_

Tried to update Windows to "2021-03 Cumulative Update Preview (KB5000842)" [Version 10.0.19042.906] and for a while it looked like the problem was not present after that update. It was less prone but it still crept up on me at times, but not as often.

Tried to reproduce the error on a laptop that was still running Windows [Version 10.0.19042.867], and and was able to reproduced the error on it consistently. _Except the empty File Explorer and loosing ability to browse to the "Downloads" directory was not consistent/present on it._  After I updated Windows on the laptop to [Version 10.0.19042.906] the problem was not present on that either (well less often present after more thorough testing as noted initially).

So looks like there is a bug in Windows [Version 10.0.19042.867] that caused it which has been made less prone to occur in [Version 10.0.19042.906], and could be that the version you run have the problem fully eliminated.

_Another playlist that caused crash on both computers after update `https://youtu.be/DDGhKS6bSAE?list=RDDDGhKS6bSAE`_
_Two songs from playlist that caused crash (because playlist is different for all based on YT algorithm) `u6LahTuw02c` and `tuw1ziytBDk`_

_I can add a long paragraph about File Explorer showing empty result, but it became less consistent after the update and I guess adding that will just dilute the search for cause of bug (if not already fixed in later Windows versions). To force (but not consistently) the "Empty result" windows you can close all File explorer windows, reopen to the folder you downloaded to and then refresh the view, then open a a new File explorer window._ 

<img width="937" alt="Screenshot" src="https://user-images.githubusercontent.com/54682125/113644602-6b4da700-9685-11eb-9fce-e99eda9ba14a.png">
