### ISSUE TITLE
Default Display for WSL console

### ISSUE THREAD

**Issue by tariver** [microsoft/WSL#6758]
# Environment
Windows build number: `Microsoft Windows [Version 10.0.19042.867]`
Your Distribution version: `Release: 20.04`
Whether the issue is on WSL 2 and/or WSL 1: `Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020`

# Steps to reproduce
Following the instructions [here](https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/default-display-for-applications-under-win10-and/850fcd2c-e295-4a16-9053-69f1eec8b592)
1. Have two monitors on Windows 10.
2. Open the application. It opens in the primary monitor.
3. Re-size the window so that it is not maximized or minimized.
4. Move the window to the secondary monitor.
5. Close the application.  Do not re-size prior to closing.
6. Open the application.
7. It again opens in the primary monitor.

#  Expected behavior
As mentioned in the link above it should open in the secondary monitor as any other Windows application.

# Actual behavior
WSL console is the only Windows application that doesn't "remember" the monitor to be opened in.

**Comment by DHowett** [comment]
We’re not going to fix this in the vintage console host. :)

**Comment by tariver** [comment]
> 
> 
> We’re not going to fix this in the vintage console host. :)

Vintage? :)

**Comment by DHowett** [comment]
Ah, so, my team's efforts (hi! we own the console host that WSL, cmd, powershell, etc. run inside) have been focused on [Windows Terminal](https://docs.microsoft.com/windows/terminal) as the new UI for text-mode applications. It's built from much of the same code as conhost, and both of them are open-source and community-driven. :smile:

**Comment by tariver** [comment]
I see now. Well, I guess I have no other choice than to try it out. :)

**Comment by therealkenc** [comment]
> WSL console is the only Windows application that doesn't "remember" 

See it now. You'll get the same behavior with ⊞Win+R `cmd.exe`. Dual monitor or relocating on one monitor being the same.
