### ISSUE TITLE
apt not found within WSL openSUSE

### ISSUE THREAD

**Issue by MegalexMaster** [microsoft/WSL#6759]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1440]
Your Distribution version: openSUSE-Leap-15.2
Whether the issue is on WSL 2 and/or WSL 1: WS1, Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020
```

# Steps to reproduce

Attempting in install pip/python

> sudo apt install python3-pip

#  Expected behavior

Installation of pip/python

# Actual behavior

sudo: apt: command not found

**Comment by therealkenc** [comment]
SUSE uses [RPM](https://documentation.suse.com/sbp/all/html/SBP-RPM-Packaging/index.html)
