### ISSUE TITLE
Error 0x800700d8 about 64bit incompatibility

### ISSUE THREAD

**Issue by tionand** [microsoft/WSL#6760]
# Environment

```none
Windows build number: 10.0.19042.867
Your Distribution version: N.A.
Whether the issue is on WSL 2 and/or WSL 1: WLS 1
```

# Steps to reproduce

After enabling wsl feature:
-install Ubuntu 18.04 (or any other distribution) and start it
and/or
-run command wslconfig.exe /l /all in powershell

#  Expected behavior

-the selected distribution is installed and started without errors
and/or
-all registered distributions are listed

# Actual behavior

All operations that involve using wsl.exe give 0x800700d8 error and a message about incompatibility with 64 bit OS version is showed.

I point up that it was working correctly on the same exact machine until a few days ago, then it suddenly stopped working.

![1](https://user-images.githubusercontent.com/81976400/113591634-6f9da400-9634-11eb-8ed1-4517cd065339.png)
![2](https://user-images.githubusercontent.com/81976400/113592774-e0918b80-9635-11eb-8cbf-9baff5f4459c.png)
![3](https://user-images.githubusercontent.com/81976400/113591646-762c1b80-9634-11eb-88d2-062728c6cbf4.png)

**Comment by adrastogi** [comment]
Thanks for reporting this. Can you please share a repro-mode trace of the problem? Instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).

**Comment by tionand** [comment]
link to trace feedbacks: https://aka.ms/AAbthz5 https://aka.ms/AAbtwy9

**Comment by adrastogi** [comment]
Thank you for gathering the traces. Could you also please run [sigcheck](https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck) on wsl.exe and share the output? It'll confirm the bit-ness of the binary.

**Comment by tionand** [comment]
Hello @adrastogi repro has been provided. Is there any news? Thank you

**Comment by adrastogi** [comment]
I didn't spot any clues in the Store trace, unfortunately (if there is meaningful data related to the dialog box you're seeing in that scenario, I'm not able to locate it amongst the other events). 

The wslconfig.exe trace showed that the program is attempting to call CreateProcess on wsl.exe, and that API is what is generating the 0x800700d8 (ERROR_EXE_MACHINE_TYPE_MISMATCH) error. So, this error is coming from outside of WSL.

From the error messages you're seeing in both cases, the OS seems to think there's something wrong with the bit-ness of wsl.exe. Could you try running sigcheck on wsl.exe and sharing the output? This will validate if the binary is truly 64-bit or not.

**Comment by tionand** [comment]
PS C:\Windows\System32> sigcheck wsl.exe

Sigcheck v2.80 - File version and signature viewer
Copyright (C) 2004-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Windows\System32\wsl.exe:
        Verified:       Unsigned
        File date:      21:05 08/03/2021
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    n/a

Should I set any other option to sigcheck ?

**Comment by adrastogi** [comment]
Thanks for trying that out- no, I don't think you need any other flags. I would have expected to see something like this:

```
F:\Sysinternals\SysinternalsSuite>sigcheck C:\Windows\system32\wsl.exe

Sigcheck v2.80 - File version and signature viewer
Copyright (C) 2004-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

c:\windows\system32\wsl.exe:
        Verified:       Signed
        Signing date:   10:04 AM 4/9/2021
        Publisher:      Microsoft Windows
        Company:        Microsoft Corporation
        Description:    Microsoft Windows Subsystem for Linux Launcher
        Product:        Microsoft« Windows« Operating System
        Prod version:   10.0.21354.1001
        File version:   10.0.21354.1001 (WinBuild.160101.0800)
        MachineType:    64-bit
```

At this point I am suspecting the file got corrupted. Could you try running the [SFC utility](https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-10-365e0031-36b1-6031-f804-8fd86e0ef4ca) to see if this finds any issues? From an elevated command prompt:

```
C:\WINDOWS\system32>sfc /verifyfile=C:\Windows\system32\wsl.exe


Windows Resource Protection did not find any integrity violations.
```
(There's a `/scanfile` option which will actually attempt to repair the file if an issue is found.)

**Comment by tionand** [comment]
[CBS.log](https://github.com/microsoft/WSL/files/6294708/CBS.log)

Actually it looks like there's something wrong with file integrity (in attachment CBS.log for /verifyfile). 

/scanfile says it is not able to repair the file. 

What could i do to solve the problem? Thank you

**Comment by adrastogi** [comment]
Thanks for sharing that information. Since the component store is corrupted, it can be repaired by running `DISM.exe /Online /Cleanup-image /Restorehealth`. More information on that command available [here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/deployment/fix-windows-update-errors#resolution-for-windows-81-windows-10-and-windows-server-2012-r2). 

Once the component store has been repaired, per that article you can try running a full scan (e.g. `sfc.exe /scannow`) in case there are other files that have been corrupted.

**Comment by tionand** [comment]
Hi @adrastogi sorry for the late response. I confirm that the procedure that you suggested solved the problem.

Among other things DISM logged:

2021-06-06 09:10:37, Info                  CSI    000000ca Hashes for file member [l:7]'wsl.exe' do not match.
 Expected: {l:32 ml:33 b:9cae9642354c4bb0fc45fa7f5e0aa93398d9cc23e3f5d89da682a9055dad9657}.
 Actual: {l:32 b:9d61e8c4c4cd3bc6f0d1a9329c1d2e0a306ad283f0c5fa58627138312ae5fca2}.
2021-06-06 09:10:37, Info                  CSI    000000cb [SR] Repairing file \??\C:\Windows\System32\\wsl.exe from store

Thank you for support.
