### ISSUE TITLE
wsl con't install pip in python3

### ISSUE THREAD

**Issue by m-mstafa** [microsoft/WSL#6762]
# Environment

```none
Windows build number: [run `cmd.exe /c ver`]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

E: Unable to locate package python3-pip

**Comment by m-mstafa** [comment]
abd21@DESKTOP-E3NLP50:~$ sudo apt install python3-pip3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-pip3
abd21@DESKTOP-E3NLP50:~$

**Comment by m-mstafa** [comment]
no one cal solve this problem

**Comment by m-mstafa** [comment]
on wsl 2 ubuntu 20.04 the message my be like: competable

**Comment by m-mstafa** [comment]
please help me

**Comment by Sausbolle** [comment]
Have you tried running `sudo apt update` first?

**Comment by m-mstafa** [comment]
yes,didn't eork

في الاثنين، ٥ أبريل ٢٠٢١ ١١:٤٠ م Sausbolle ***@***.***> كتب:
