### ISSUE TITLE
uname in WSL2 returns incorrect machine type for 32-bit process running under 64-bit OS

### ISSUE THREAD

**Issue by danieljennings** [microsoft/WSL#6763]
WSL2, unlike typical Linux installations, incorrectly states that the machine type is "i686" for an x86_64 OS installation, if the process that's invoking `uname` is a 32-bit process. This causes 32-bit processes (such as steamcmd) that are attempting to determine whether the underlying OS is 64-bit or not to incorrectly perceive that they are 32-bit.

**uname.cc**:
```c++
#include <sys/utsname.h>
#include <cstdio>

int main()
{
        struct utsname buf;
        uname( &buf );

        printf( "sysname: %s\n", buf.sysname );
        printf( "release: %s\n", buf.release );
        printf( "version: %s\n", buf.version );
        printf( "machine: %s\n", buf.machine );

        return 0;
}
```

**WSL2 - Compiled natively (64-bit)**:
```
$ cc uname.cc
$ ./a.out
sysname: Linux
release: 5.4.72-microsoft-standard-WSL2
version: #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine: x86_64
```

**WSL2 - Compiled with 32-bit toolchain**:
```
$ cc -m32 uname.cc
$ ./a.out
sysname: Linux
release: 5.4.72-microsoft-standard-WSL2
version: #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine: i686 # oh no!
```

**Native 64-bit Arch - Compiled with 32-bit toolchain**:
```
# cc -m32 uname.cc
# ./a.out
sysname: Linux
release: 5.11.6-arch1-1
version: #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000
machine: x86_64
```

**Native 64-bit Ubuntu - Compiled with 32-bit toolchain**:
```
$ cc -m32 uname.cc
$ ./a.out
sysname: Linux
release: 5.8.0-48-generic
version: #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021
machine: x86_64
```

Is there a fundamental underlying property of WSL2 that causes this problem?

**Comment by therealkenc** [comment]
Thank-you for the report and concise repro. I was unable to reproduce, but am curious what is the variable. Maybe if were lucky something will show up in an `strace(1)` log if you can post a gist. Mine looks like [this](https://gist.github.com/therealkenc/77dcea5ca09d5c96e81165430d1e7068). The command would be:
```
$ strace -f -s 1024 -v -o myuname.strace ./a.out
```

![image](https://user-images.githubusercontent.com/7049700/113642488-ce631d80-9634-11eb-8d8f-862bf03764b0.png)

**Comment by danieljennings** [comment]
I don't know what to say, because I went back to take an `strace` and it didn't repro... I had restarted my WSL2 instance shortly after submitting this report (for an unrelated reason), so whatever was broken must've been fixed by that restart, which is a bit disconcerting because I don't know how I got into that state.

I went back through my bash history to see if I could identify anything weird, but I couldn't find anything, so I'm kind of stumped. I re-ran the builds I had done before to make sure they didn't somehow pollute my running OS (not even sure what that would mean here, though, since it went away after restarting).

You can close this out as unreproducable, but I wanted to jot down a few notes here in case I see this again so I can narrow down what's going on (even though it's gotta be my fault somehow?)

- I had been making chroots and importing them into Docker via docker import.
- I was using native Linux Docker, not the Docker Desktop proxy (which I know because Docker Desktop can't run steamcmd)
- When I ran steamcmd (not built locally) inside of the resulting Docker container, it tripped asserts about running under a 32-bit OS, so I looked at the implementation of that code and saw it was just doing a `uname`.
- I quit out of the docker container and into the homedir of my WSL2 instance and wrote/ran that test application. I see that in my bash_history and the code/binary were still in my homedir after I restarted the WSL2 instance, so I don't see how I could've been secretly trapped inside of a chroot or container (which also de-color my prompt).
- I wasn't mounting anything weird like my root in Docker, I would've seen that in my history.
- Even if I try to reproduce this problem inside the chroots/docker containers I've been working with, it doesn't reproduce. It still shows me x86_64 correctly for the m32 architecture builds. And steamcmd no longer produces the assert...

So something was weird enough that it was affecting the root WSL2 OS, as well as a program running inside of newly minted Arch chroot running inside of containerd (which is why I assumed a WSL2 kernel bug). But now there's no problem, and I haven't the slightest clue what could've triggered this even if I wanted to make it happen intentionally.

Thanks again for your time, sorry it was apparently wasted. If I see this again and believe it's not my fault I'll get (at least) an strace of the program which may very well tell me what's going on.

**Comment by therealkenc** [comment]
Thanks for the follow up. WSL2 runs a x86_64 Real Linux™ kernel, and you can't get the `uname(2)` _syscall_ to cough up `i686` on an unmodified 64-bit kernel for love or money. I'll close out since the chances of a "+1 me2" is pretty slim (though never zero). Do post if you figure out what happened though. I am curious too. If it is something actionable we'll reopen natch.
