### ISSUE TITLE
Windows Terminal Ubuntu-20.04  starts with sysctl , DNAT and Fatal errors

### ISSUE THREAD

**Issue by newcanopies** [microsoft/WSL#6768]
# Environment

```
Microsoft Windows [Version 10.0.19041.867]
Ubuntu Focal 20.04
Linux   version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0   (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
--
```

# Steps to reproduce

Opening the Windows Terminal Ubuntu shell starts with the following:

```
sysctl: permission denied on key "net.ipv4.ip_forward"
sysctl: permission denied on key "net.ipv4.conf.all.route_localnet"
DNAT: Could not determine whether revision 2 is supported, assuming it is.
DNAT: Could not determine whether revision 2 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied
DNAT: Could not determine whether revision 2 is supported, assuming it is.
DNAT: Could not determine whether revision 2 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
```

![image](https://user-images.githubusercontent.com/65022111/113764052-bd8cd780-971a-11eb-9114-b2db720d0020.png)

Please advise how to resolve these start-up errors. 
Thank you

**Comment by therealkenc** [comment]
Likely something has been inserted into one of your startup scripts (`.bashrc` or similar) which is calling `sysctl(8)` as an unprivileged user ('you'), and you do not have permission to modify `net.ipv4.ip_forward` etc. A big hammer fix would be to install a differently-named distribution [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71) vs [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6), or visa-versa, start it with `wsl.exe -d <distro name>` and confirm whether the unadulterated install starts without error.

**Comment by newcanopies** [comment]
thank you @therealkenc 
are any of these Windows/cmd/PowerShell based errors, 
or the fresh Ubuntu install should wipe the slate clean on all of them?

**Comment by newcanopies** [comment]
@therealkenc 

WSL2 specific issue: 

getting these errors from running various programs, even after exporting export   XDG_RUNTIME_DIR=/run/user/1000
![image](https://user-images.githubusercontent.com/65022111/114077174-cb239800-98a7-11eb-8386-49f7a1860155.png)

running `w`, `who -H`, `who -u` returns blank!

**Comment by newcanopies** [comment]
@therealkenc 

gedit error inside Visual Studio Code
![image](https://user-images.githubusercontent.com/65022111/114077686-5a30b000-98a8-11eb-8ce0-c8bfabc57a8f.png)
