### ISSUE TITLE
CUDA not working again?

### ISSUE THREAD

**Issue by patfla** [microsoft/WSL#6772]
# Environment

```none
Microsoft Windows [Version 10.0.21343.1000]
Ubuntu Release:        20.04
Linux version 5.4.91-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP Mon Jan 25 18:39:31 UTC 2021
Latest Nvidia Win10 driver 465.89
CUDA 11.1 and 11.2 both installed.  /usr/local/cuda points to 11.2.
```

# Steps to reproduce

```

MyId@DESKTOP-930EG0A:~$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

MyId@DESKTOP-930EG0A:~$ /usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery
/usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 100
-> no CUDA-capable device is detected
Result = FAIL


```

#  Expected behavior

CUDA loads and runs.

# Actual behavior
CUDA won't load.

**Comment by patfla** [comment]
Generated a wsl.etl using the 'manual' instructions - but don't know where to send or put it.

**Comment by patfla** [comment]
Continuing to fumble around here ... submitted a Feedback Hub problem pointing to this github ticket and attached wsl.etl.

**Comment by craigloewen-msft** [comment]
This is a known issue for this build! I've filed an issue on this on ourselves and pinned it over here https://github.com/microsoft/WSL/issues/6773

The good news is that it is already fixed internally and we are aiming for it to be available for the next Insiders flight. Thank you for filing this! :)

/dupe #6773
