### ISSUE TITLE
WSL2: 0x80070003 when disabling the "Require case insensitivity" policy

### ISSUE THREAD

**Issue by florinDNL** [microsoft/WSL#6776]
# Environment

```none
Microsoft Windows [Version 10.0.19041.867]
Applicable to all distros
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

•	Enable WSL 
•	Install WSL2 Kernel Upgrade
•	Install a WSL2 Distro and make sure it's running properly
•	Disable the Case Insensitivity Policy: Computer Configuration -> Windows Settings -> Security Settings -> Security Options -> [**System objects: Require case insensitivity for non-Windows subsystems**](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj852277(v=ws.11)#:~:text=%20System%20objects%3A%20Require%20case%20insensitivity%20for%20non-Windows,Enabled.%20All%20subsystems...%204%20Location.%20%20More%20)
•	Reboot
•	Try to run the WSL 2 Distro or install a new distro

# Expected behavior

•	Launch WSL2 distro successfully
•	Install additional distros
 

# Actual behavior

•	WSL2 Distros will not launch: Path not found  

![image](https://user-images.githubusercontent.com/79944491/114000896-16b45280-9864-11eb-8e26-c168a6ef21ba.png)

•	Installing additional distros will fail with the same error

![image](https://user-images.githubusercontent.com/79944491/114000987-2f246d00-9864-11eb-905e-7696ca733e47.png)
![image](https://user-images.githubusercontent.com/79944491/114001031-3cd9f280-9864-11eb-9224-18bd55f9589f.png)

•	WSL 1 Distros still work

•      In the non-working scenario, wslhost doesn't start:

![image](https://user-images.githubusercontent.com/79944491/114001994-22544900-9865-11eb-8809-5b8c377079a3.png)

**Comment by shockogit** [comment]
WSL Distros that were already installed/registered seem to work but I cannot install new distros (WSL1 or 2) when this policy setting is set to Disabled. Have tested on 1909,2004 and 20H2.

**Comment by florinDNL** [comment]
Launched Debian inside the debugger and skipped ahead to the handled exception. Looks like wsl fails when trying to load LXSS. 


```none
2:011> gh
ModLoad: 00007ff8`d2910000 00007ff8`d2922000   C:\Windows\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ff8`d4c80000 00007ff8`d4d00000   C:\Windows\System32\bcryptPrimitives.dll
ModLoad: 00007ff8`d56c0000 00007ff8`d575c000   C:\Windows\System32\sechost.dll
ModLoad: 00007ff8`d6e90000 00007ff8`d6f39000   C:\Windows\System32\clbcatq.dll
ModLoad: 00007ff8`cb9f0000 00007ff8`cb9f9000   C:\Windows\System32\lxss\LxssManagerProxyStub.dll
onecore\vm\wsl\lxss\wsl\main.cpp(380)\wsl.exe!00007FF762C3A602: (caller: 00007FF762C4BAEC) Exception(1) tid(cb8) 80070003 The system cannot find the path specified.
```

More or less the same thing when trying to install Kali, but a different error

```none
0:000> gh
ModLoad: 00007ff8`cba00000 00007ff8`cba0e000   C:\Windows\SYSTEM32\wslapi.dll
ModLoad: 00007ff8`d50b0000 00007ff8`d51b0000   C:\Windows\System32\ucrtbase.dll
ModLoad: 00007ff8`d64b0000 00007ff8`d6805000   C:\Windows\System32\combase.dll
ModLoad: 00007ff8`d5310000 00007ff8`d543b000   C:\Windows\System32\RPCRT4.dll
ModLoad: 00007ff8`d2910000 00007ff8`d2922000   C:\Windows\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ff8`d68a0000 00007ff8`d693e000   C:\Windows\System32\msvcrt.dll
ModLoad: 00007ff8`d4c80000 00007ff8`d4d00000   C:\Windows\System32\bcryptPrimitives.dll
ModLoad: 00007ff8`d56c0000 00007ff8`d575c000   C:\Windows\System32\sechost.dll
ModLoad: 00007ff8`d6e90000 00007ff8`d6f39000   C:\Windows\System32\clbcatq.dll
ModLoad: 00007ff8`cb9f0000 00007ff8`cb9f9000   C:\Windows\System32\lxss\LxssManagerProxyStub.dll
onecore\vm\wsl\lxss\wslapi\wslsession.cpp(103)\wslapi.dll!00007FF8CBA04F32: (caller: 00007FF8CBA029C7) ReturnHr(1) tid(2140) 80040302 ModLoad: 00007ff8`cb9f0000 00007ff8`cb9f9000   C:\Windows\System32\lxss\LxssManagerProxyStub.dll

0:000> !err 80040302 
0x80040302 = MAPI_E_INVALID_TYPE
Error code: (HRESULT) 0x80040302 (2147746562)
```

**Comment by florinDNL** [comment]
> WSL Distros that were already installed/registered seem to work but I cannot install new distros (WSL1 or 2) when this policy setting is set to Disabled. Have tested on 1909,2004 and 20H2.

**Comment by craigloewen-msft** [comment]
Could you please collect logs for this issue? That will help us diagnose what's going on here. 

Full intructions here: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs 

Please post the feedback link to here! Thank you!

**Comment by florinDNL** [comment]
> Could you please collect logs for this issue? That will help us diagnose what's going on here.
> 
> Full intructions here: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs
> 
> Please post the feedback link to here! Thank you!

Feedback link: https://aka.ms/AAbxhxd
