### ISSUE TITLE
`sudo` can't find vscode: `sudo: code: command not found`

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/WSL#6777]
# Environment

Windows build number: [run `cmd.exe /c ver`]: Microsoft Windows [Version 10.0.19042.867]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]: Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL] Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020 (wsl2)

# Steps to reproduce
`sudo` can't find vscode
```
$ sudo code /etc/profile.d/custom-profile.sh
[sudo] password for xxxx:
sudo: code: command not found
```

#  Expected behavior

Open files, modify them and save as root with vscode.

# Actual behavior

Can't open vscode as root

**Comment by benhillis** [comment]
The root user has a different path than your non-root user.  From non-root, what is the output of "where code".

**Comment by therealkenc** [comment]
That `sudo` sets up its own `$PATH` is by-design Linux. Eg:

![image](https://user-images.githubusercontent.com/7049700/114085401-2f256c80-9866-11eb-856f-3672b33711d8.png)

In principle you can do `sudo env "PATH=$PATH" code`, but that won't have the semantics implied. Windows VS Code "Remote 
\- WSL" extension is unawares of the UID across the Windows↔️Linux boundary. Ref #4508.

**Comment by YoniChechik** [comment]
From WSL this is the output:
```
$ which code
/mnt/c/Users/chech/AppData/Local/Programs/Microsoft VS Code/bin/code
$ whereis code
code: /mnt/c/Users/chech/AppData/Local/Programs/Microsoft VS Code/bin/code /mnt/c/Users/chech/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd
$ where code
where: command not found
```

**Comment by therealkenc** [comment]
Call this dupe #4508 ie linux-behavior regarding the OP fail. The `sudo` resets the $PATH environment by design. To the extent the "`Remote - WSL`" extension could be made more root aware, that is external VS Code.

**Comment by pushkarski** [comment]
@YoniChechik Hey Yoni, hope you're doing great! I bumped into the same issue yesterday and eventually found a workaround. Check my short how-to if this issue is still relevant for you: https://dev.to/pushkarski/sudo-code-in-wsl2-doesn-t-work-short-guide-to-the-rescue-4fb4

**Comment by ShiqingGuo** [comment]
if you are not using wsl, first use `which code` to locate the full path of vscode, then use `sudo -E <vscode full path> <filename>` to open the file.
