### ISSUE TITLE
Live-build doesn't work on WSL

### ISSUE THREAD

**Issue by fernandomartinsrib** [microsoft/WSL#6778]
I'm using Debian live-build to customize my setup. I'm trying to do this using WSL on Windows 10, but following every step that I had found in tutorials, nothing work. I receive the same errors every time.

Used commands/Steps to reproduce:

` $ sudo lb config --architecture amd64 -d buster --debian-installer live -b hdd`
`$ sudo lb build`

and returned:

![Capturar](https://user-images.githubusercontent.com/40044919/114031378-b4525680-9851-11eb-9e06-86e4866524db.PNG)

"cp: preserving permissions for 'chroot/dev/*': Operation not permitted"

I've tried to execute as "root" and nothing changes.

Thanks

**Comment by benhillis** [comment]
Please fill out the issue template.

**Comment by therealkenc** [comment]
I was not able to reproduce with the couple of steps there were.

![image](https://user-images.githubusercontent.com/7049700/114096721-f7bdbc80-9873-11eb-9030-a794e96b042d.png)
