### ISSUE TITLE
External file changes are not detected

### ISSUE THREAD

**Issue by DrkCoater** [Microsoft/WSL#678]
when we are running a file watcher in bashOnWindows. Any external files updates from windows programs can't be caught by the watch. I'm running MeteorJS on bashOnWindows. When I'm editing a file externally using an editor such as Visual Studio Code. The meteor watcher doesn't pick up any file save changes and restart the meteor server.

**Comment by benhillis** [comment]
Can you clarify a few things for me?

1. That directory are you working out of (/mnt/c or somewhere like your home directory).
2. Do file modifications from within bash show up with MeteorJS?
3. Do you happen to know how MeteorJS is registering for file change notifications?  Inotify?

**Comment by fpqc** [comment]
@benhillis I just did a test with the watch util

`watch -n 0.2 "ls -lh test.txt"`

where test.txt was a file I was editing and saving in Notepad.  

As soon as I saved the file, my watcher did update as long as the file test.txt was in driveFS.

**Comment by therealkenc** [comment]
Meteor is [exceptionally clever](https://github.com/meteor/docs/blob/version-NEXT/long-form/file-change-watcher-efficiency.md) about avoiding #216, and does it's best with a `stat()` storm.

The `tail -f` issue @fpqc found is interesting though. `tail` is checking a [whitelist](https://fossies.org/dox/coreutils-8.25/fs_8h_source.html) of fs magic numbers and can't grok fs type `0x53464846`. As a result it punts defensively to stat polling, and avoids `inotify` altogether. Possibly WSL should lie like a rug and return `S_MAGIC_NTFS` for NTFS on DrvFs, and be as bug/limititation compatible as possible with [native](https://github.com/torvalds/linux/blob/master/fs/ntfs/ntfs.h) NTFS on Linux. What to do about VolFs is a harder question. Looks like the [bug-coreutils](https://lists.nongnu.org/archive/html/bug-coreutils/2016-04/msg00047.html) people have already picked up on it.
```
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <fcntl.h>

#define S_MAGIC_NTFS 0x5346544E

void main(void)
{
	struct statfs buf;
	int fd = open("foo", O_CREAT|O_RDWR);
	int err = fstatfs (fd, &buf);
	unsigned long int fs_type = buf.f_type;
	printf("fs_type: 0x%08lx\n", fs_type);
	if (fs_type != S_MAGIC_NTFS) {
		printf("...not fs type NTFS, whatever I am\n");
	}
}

```

**Comment by benhillis** [comment]
@therealkenc Good call. This isn't the first time our fstype has caused bad behavior.  I think you're right though if we report S_MAGIC_NTFS things might work a lot better.

**Comment by therealkenc** [comment]
I think it is a seriously hard question what to return, with no right answer. One can also imagine a Samba daemon on WSL looking at the fstype magic number and saying "NTFS share, no unix symlinks for you!", even though DrvFs has the new reparse points.

**Comment by therealkenc** [comment]
The OP on this one is #216. The `tail` thing is #925.
