### ISSUE TITLE
Error on Kali Linux WSL 2  XRDP 

### ISSUE THREAD

**Issue by robisonweb** [microsoft/WSL#6784]
Windows 10 V. 2004 (CSO 19041.867)
[https://github.com/robisonweb/public/blob/master/kali_error_03_09-04-21.png](url)
WSL 2
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.1
Codename:       kali-rolling

I installed Kali Linux on Windows10 WSL 2, but for me wifi0 appears as a connection on Kali not eth0.
````
eth4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.21.224.1  netmask 255.255.240.0  broadcast 172.21.239.255
        inet6 fe80::353a:bdf4:2e95:7b70  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 00:15:5d:b1:69:4a  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0xfe<compat,link,site,host>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wifi0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.88  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::c07d:f566:febf:41d  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 34:7d:f6:4d:d1:86  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

````

On Windows 10 Network Conections Show

vEhernet (WSL)[Hyper-V Virtual Ethernet Adapter
IP 172.21.224.1
Mask 255.255.240.0
[https://github.com/robisonweb/public/blob/master/kali_error_02_09-04-21.png](url)
Win10 image

When I connect oo: XRDP via Remote Desktop connection, Kali shows Network Disable: Network Manager is Not Runnig, and does not allow to open the Terminal.

I tried to install it on Kali but was unsuccessful.
[https://github.com/robisonweb/public/blob/master/kali_error_01_09-04-21.png](url)
error image

Can anybody help me?

**Comment by therealkenc** [comment]
> WSL 2

That `ifconfig` output looks like WSL1. You can verify with `cat /proc/version` (from the deleted issue template) or `wsl.exe -l -v`.

The links to the `.png` files do not resolve. If you have installed [Win-KeX](https://www.kali.org/docs/wsl/win-kex/) you may get better eyeballs in the [Kali Forums](https://forums.kali.org/).

**Comment by robisonweb** [comment]
I fixed the image link

**Comment by therealkenc** [comment]
The image links do not resolve. Have you installed Win-KeX.
