### ISSUE TITLE
WSL.exe adds null characters between characters

### ISSUE THREAD

**Issue by ccrutchf** [microsoft/WSL#6787]
### Windows Build Number

Microsoft Windows [Version 10.0.21354.1]

### WSL Version

2

### Distro Version

Ubuntu-20.04

### Repro Steps

WSL.exe adds null characters between letters
```powershell
PS C:\Users\user> $results = wsl --status
PS C:\Users\user> $results[0]
Default Distribution: Ubuntu-20.04
PS C:\Users\user> $results[0][0]
D
PS C:\Users\user> $results[0][1]

PS C:\Users\user> $results[0][2]
e
PS C:\Users\user> [int]$results[0][1]
0
```

### Expected Behavior

WSL.exe does not add null characters between letters

### Actual Behavior

WSL.exe adds null characters between letters.

**Comment by 0xbadfca11** [comment]
https://en.wikipedia.org/wiki/UTF-16

**Comment by DHowett** [comment]
I am surprised that PowerShell isn’t handling UTF-16 correctly.

**Comment by therealkenc** [comment]
Variation on #4456.

![image](https://user-images.githubusercontent.com/7049700/114466768-c3ad0900-9b9d-11eb-9372-dcf2e7c4ef4f.png)

**Comment by NotTheDr01ds** [comment]
And #4707.  There's a workaround in [this comment](https://github.com/microsoft/WSL/issues/4607#issuecomment-717876058).

**Comment by ccrutchf** [comment]
After getting some time to test this, I have confirmed that UTF-16 is my issue.  Setting PowerShell to handle it does address my issue.

**Comment by therealkenc** [comment]
Let's call this /dupe #4607 and #4456 since they have the same underlying cause.
