### ISSUE TITLE
ghost display

### ISSUE THREAD

**Issue by rikirill** [microsoft/WSL#6788]
### Windows Build Number

Version 10.0.19042.867

### WSL Version

WSL 1

### Repro Steps

followed to https://docs.microsoft.com/ru-ru/windows/wsl/install-win10#manual-installation-steps
and after the step 3 i restart my pc
my second display begin to repeat main and in display settings I didn't see it, but i see my main display now is 2/1 and i have two display "4" and "5"

### Expected Behavior

I have second display and after restart it should be work normal, like, two monitors for one pc

### Actual Behavior

![image](https://user-images.githubusercontent.com/61277473/114267090-195da600-9a24-11eb-9cef-1149aa522340.png)

as you can see on the skreen, I have the second display but in setting I have 3, but in irl I use now only one display

**Comment by sr229** [comment]
I doubt this is related to WSL at all, might be your Windows installation or a bug within WIndows, if so, this isn't the appropriate channel.

**Comment by therealkenc** [comment]
> I doubt this is related to WSL at all

It isn't, strictly speaking, but we're tracking (shadowing) hypervisor platform issues, to the extent enabling it is required to run WSL2. You can also try cross-posting in the [windows hyper-v Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-server-hyper-v.html). This problem will manifest at "step 3" whether you make it to installing WSL2 or not.
