### ISSUE TITLE
Exporer does not show borgbackup mount

### ISSUE THREAD

**Issue by monreal** [microsoft/WSL#6790]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.906]

### WSL Version

WSL 2

### Distro Version

Fedora Remix for WSL

### Other Software

borgbackup 1.1.16

### Repro Steps

Mount a borg backup in WSL. Try to open the folder in Explorer.

### Expected Behavior

In the WSL shell the mount works, it should also work Explorer.

### Actual Behavior

Attempt to access invalid address

![Untitled](https://user-images.githubusercontent.com/54005/114271482-dabef000-9a11-11eb-9f8c-917dd8c28e94.png)

**Comment by therealkenc** [comment]
A repro...
```
$ sudo apt install borgbackup
$ cd ~ && mkdir -p borg-repo borg-mnt tmp
$ borg init -e none borg-repo
$ borg create borg-repo::tmp tmp
$ borg mount borg-repo borg-mnt
$ mount | grep borgfs
```

![image](https://user-images.githubusercontent.com/7049700/114473241-b9dcd300-9ba8-11eb-8c0a-cfc7f38f5672.png)

Almost certainly same #6711.
