### ISSUE TITLE
insmod: ERROR: could not insert module hello.ko: Function not implemented

### ISSUE THREAD

**Issue by XW-git** [microsoft/WSL#6792]
I build a simple kernel model. hello.ko in WSL. when I try to install. it gives me error.
the example is from Raspberry pi.  copy Makefile, and hello.c over.
since 
there is no package of linux-header-4.4.0-19041-Microsoft.  I use linux-headers-generic instead.
change Makefile to reflect that.
make
no issue, and hello.ko is generated
insmod hello.ko

insmod: ERROR: could not insert module hello.ko: Function not implemented

source code attached. please help.

[driver.zip](https://github.com/microsoft/WSL/files/6290361/driver.zip)

**Comment by DHowett** [comment]
You are using WSL1. WSL1 does not use a real Linux kernel. You need to use WSL2 if you need a real kernel (and loadable module support.)

**Comment by XW-git** [comment]
I'm sure I installed WSL2.
![image](https://user-images.githubusercontent.com/63622661/114309039-1229ad00-9aa3-11eb-8ac2-87bdc830dcaf.png)
How to check mine is WSL1 or WSL2?

**Comment by adrastogi** [comment]
Can you run `wsl.exe -l -v` and share the output? That should tell you the version for each distro registered on your system.

**Comment by XW-git** [comment]
PS C:\Windows\system32> wsl.exe -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1

**Comment by therealkenc** [comment]
> if it is WSL1, how to remove WSL1 and install WSL2?

#6505
