### ISSUE TITLE
Cannot start any service

### ISSUE THREAD

**Issue by BlackDogLi** [microsoft/WSL#6795]
### Windows Build Number

19042.906

### WSL Version

WSL 2

### Distro Version

centos8

### Other Software

Docker version 20.10.5, build 55c4c88
php7.4

### Repro Steps

1、yum install php74
2、php74 -v
3、systemctl restart php74-php-fpm

### Expected Behavior

Can start php-fpm

### Actual Behavior

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by newcanopies** [comment]
piggy-backing on this issue as it is likely also related to WSL2 not using systemctl but sysvinit (stand to be corrected).


$ snap install chromium
`error: cannot communicate with server: Post http://localhost/v2/snaps/chromium: dial unix /run/snapd.socket: connect: no such file or directory`

$ sudo systemctl unmask snapd.service
$ sudo systemctl enable snapd.service
$ sudo systemctl start snapd.service
`error: cannot communicate with server: Post http://localhost/v2/snaps/chromium: dial unix /run/snapd.socket: connect: no such file or directory`
