### ISSUE TITLE
Network home drive mounted read only (CreateProcessParseCommon:839: Failed to translate)

### ISSUE THREAD

**Issue by btreut** [microsoft/WSL#6798]
### Windows Build Number

Microsoft Windows [Version 10.0.17763.1817]

### WSL Version
C:\ >wsl -l -v 
returns:
Ungültige Befehlszeilenoption: -l

10.0.17763.1075 dated 16.03.2020 06:29 (no idea if this is WSL 1 or 2)

### Distro Version

Debian 9 stretch 

### Repro Steps

I have the following lines in my .bashrc (I found them somewhere quite some time ago):
```
if [ ! -d /mnt/h/Desktop ]
then
   sudo mount -t drvfs -o noatime,uid=1000,gid=1000,umask=22,metadata,case=off H: /mnt/h
   sudo mount -t drvfs -o noatime,uid=1000,gid=1000,umask=22,metadata,case=off K: /mnt/k
   sudo mount -t drvfs -o noatime,uid=1000,gid=1000,umask=22,metadata,case=off V: /mnt/v
fi
```

It used work without any problems, but since some time (I cannot say exactly when and/or if it is connected to the last Windows update, but that might be the case) my home drive is mounted read only and I see the following message, when issueing `dmesg`
`init: (3) ERROR: CreateProcessParseCommon:839: Failed to translate H:\`

the other drives are mounted correctly:
```
ll /mnt
total 0
drwxr-xr-x 1 root     root     4096 Apr 12 15:49 .
drwxr-xr-x 1 root     root     4096 Jul 23  2020 ..
drwxr-xr-x 1 bernhard bernhard 4096 Apr  6 20:53 c
drwxr-xr-x 1 bernhard bernhard 4096 Apr 13 12:10 d
dr-xr-xr-x 1 bernhard bernhard  512 Apr 12 15:58 h
drwxr-xr-x 1 bernhard bernhard  512 Mar 30 12:44 k
drwxr-xr-x 1 bernhard bernhard  512 Mar 26 10:29 v
```

### Expected Behavior

```
$ ll /mnt/h
drwxr-xr-x 1 bernhard bernhard  512 Apr 12 15:58 h
```

### Actual Behavior

see above in Repro steps

### Diagnostic Logs

init: (3) ERROR: CreateProcessParseCommon:839: Failed to translate H:\

**Comment by craigloewen-msft** [comment]
@Btreut you're on a very old build, could you try updating to a newer Windows version and trying this again? If you still see this problem please reopen this issue! Thank you!

**Comment by btreut** [comment]
no chance. This is a managed environment and I don't have any influence on the Windows version.

**Comment by craigloewen-msft** [comment]
Got it! Unfortunately the [Windows build that you're on is out of support](https://en.wikipedia.org/wiki/Windows_10_version_history) and likely we have fixed this issue on more up to date versions. I'm unable to reproduce your issue on my machine, so I don't believe there's any actionable items here for us on the WSL team besides recommending that you upgrade your Windows version. Please let us know if we can help in any other way!

**Comment by btreut** [comment]
I am sorry to read this. I'll try to ask for an update, but I fear that it our IT will refuse.

**Comment by btreut** [comment]
BTW, I do not see any way to re-open the issue and as I understand [this issue](https://github.com/isaacs/github/issues/583) I am not allowed to do that ...

**Comment by btreut** [comment]
> I'm unable to reproduce your issue on my machine

interestingly, this happenes only for one of the three network drives which I try to access via `mount -t drvfs`. The other two are mounted without error message have the w flag set in the `ls -l` listing. I cannot really tell you, what the difference are between H:, K:, and V:, all three are residing on DFS server, but H: is mapped per user, whereas K: is mapped for a group and V: different groups with different subdirs.

**Comment by craigloewen-msft** [comment]
@btreut the level of support depends on your SKU, (LTSC, Home, Pro, etc.). Mostly I wanted to emphasize that our only method on the WSL team to help for this solution is for you to upgrade to a newer build as that likely contains a fix for your bug. I'm sorry you're unable to update, but that's really the only tool that we have to help you given that WSL is part of the Windows image. 

Thank you for the link on you not being able to reopen an issue, I actually didn't realize they didn't allow that for the original poster. I can reopen this issue if needed, but I believe your issue is already solved given that this isn't behaviour that we've seen on the latest builds and that your version is much older.

**Comment by btreut** [comment]
thanks for the (disappointing) update.

**Comment by btreut** [comment]
I realized today that the problem is much more intricate. I do not have write permissions in the root of the networked home drive, but I can modify files and create files in some subdirectories of the home drive, but not all. Eg. in H:\Destop and H:\ a `touch bla` results in an error, but in H:\Test and others it works. Quite strange, but I can (and have to) live with it.
