### ISSUE TITLE
Interop not working from WSL2

### ISSUE THREAD

**Issue by joedborg** [microsoft/WSL#6799]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.906]

### WSL Version

WSL 2

### Distro Version

Ubuntu 20.04

### Other Software

VS Code 1.55.1

### Repro Steps

Run any .exe from WSL

### Expected Behavior

.exe runs

### Actual Behavior

`<3>init: (747) ERROR: UtilConnectToInteropServer:300: connect failed 2`

### Diagnostic Logs

https://aka.ms/AAbxvmk

**Comment by craigloewen-msft** [comment]
@joedborg can you please attach logs when you're reproing this problem? We aren't able to repro this issue and would need more info to diagnose it:

Instructions here:
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs

**Comment by joedborg** [comment]
Hi there, thanks for the reply.  I've done some digging and can see that the issue is that the env var `$WSL_INTEROP` is not pointing to a valid socket:

```
c/Users/Joe
➜ echo $WSL_INTEROP
/run/WSL/1587_interop

c/Users/Joe
➜ ls /run/WSL
1353_interop  3750_interop  7_interop
```

If I set this variable to the last created socket file, it works again.

**Comment by craigloewen-msft** [comment]
Awesome, thanks so much! Could you still collect logs using the link above? The info in the logs will help us diagnose why $WSL_INTEROP isn't behaving as expected.

**Comment by joedborg** [comment]
Thanks @craigloewen-msft, added the link in the original post.

**Comment by therealkenc** [comment]
This is likely going to be spiritually similar #5065 #4148 (with a side of #6588). You can confirm with a new user with an unadulterated shell startup script.
```
$ sudo useradd -s /bin/bash foo
```

Looks like:

![image](https://user-images.githubusercontent.com/7049700/114787195-3c45ce00-9d34-11eb-92d0-26fbea7ec472.png)

**Comment by joedborg** [comment]
Thanks @therealkenc,

It could also be that I'm using systemd instead of initd.  Is there anywhere (or could you explain) that can show the chain of how WSL_INTEROP gets set, please?  That way I can at least try and check to see where is overwriting it / isn't setting it correctly.

Cheers!

**Comment by therealkenc** [comment]
> It could also be that I'm using systemd 

Thanks. /dupe #6588 ➡️ #994.
