### ISSUE TITLE
How would you connect a Windows Browser to Linux Port (e.g. 0.0.0.0:8080)

### ISSUE THREAD

**Issue by dragonBall561** [microsoft/WSL#6804]
I have a node.js project I am working on in WSL. When I run `npm start` it starts the server on `0.0.0.0:8080`. I want to access this from a Browser running in Windows (e.g. Chrome for Windows).

For now, I have set up a GUI for WSL. I can use firefox to access the localhost, but it is slow and doesn't support some features like WebGL.

How would you do this?

**Comment by therealkenc** [comment]
When your node server running, what is the output of:
```
$ wsl.exe /c ver
$ cat /proc/version
$ ip addr show dev eth0   # make a note of the ipv4 address w.x.y.z
$ netstat -nl | grep 8080
```

`sudo apt install iproute2` if you don't have `ip`.


And from Powershell on the Windows side:
```
PS> curl.exe localhost:8080
PS> curl.exe w.x.y.z:8080
```

**Comment by dragonBall561** [comment]
Ah ok tysm that worked!

That was bugging me for a really long time!
