### ISSUE TITLE
Android emulator slow.

### ISSUE THREAD

**Issue by patfla** [microsoft/WSL#6806]
Build 21354.co_release.210402-1630.

I'm back to the Android emulator.  It's working (unlike 2 or 3 mths ago) - but it's very slow. Android Studio told me:

>     Detected ADB
>     The ADB binary found at D:\AndroidSDK\platform-tools\adb.exe is obsolete and has seriousperformance problems with
>     the Android Emulator. Please update to a newer version to get significantly faster app/file transfer.
>     OK

Upgraded Android SDK Platform-Tools (and other out-of-date SDK Tools).

However Haxm won't install - the prereqs aren't met and I believe this has to do with Hyper-V being turned on. I don't believe I'm supposed to have Hyper-V on Win10 Home but this is what I see in services.msc:

https://imgur.com/a/qkYZqYP

**Comment by patfla** [comment]
Haxm install log:

> Version: 7.6.5
> Output folder: C:\Program Files\Intel\HAXM
> Extract: checktool.exe... 100%
> Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
> CPU vendor          *  GenuineIntel
> Intel64 supported   *  Yes
> VMX supported       -  No
> VMX enabled         -  No
> EPT supported       -  No
> NX supported        *  Yes
> NX enabled          *  Yes
> Hyper-V disabled    -  No
> OS version          *  Windows 10.0.21354
> OS architecture     *  x86_64
> Guest unoccupied    *  Yes. 0 guest(s)
> The system requirements are not satisfied.

**Comment by benhillis** [comment]
This is unrelated to WSL. On Windows 10 Home you are looking for "Virtual Machine Platform" optional component.
