### ISSUE TITLE
Terminal does not save command

### ISSUE THREAD

**Issue by felipeyonehara** [microsoft/WSL#6810]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.804]

### WSL Version

WSL2

### Distro Version

Ubuntu 18.04

### Repro Steps

Just execute any command with space before and arrow up to see that the command wasnt stored in history.

Example: 
-normal command works perfectly
$date

-bug1 (put a space before)
$ date

-bug2 (put a space after the command)
$date <cursor here then enter>

Then check the history. It will not show the executed command.

### Expected Behavior

Show up command executed with arrow up keyboard tap.

### Actual Behavior

Command history not safe.

### Diagnostic Logs

No logs needed due the simplicity.

**Comment by therealkenc** [comment]
Thank-you for the report. [This](https://unix.stackexchange.com/questions/115917/why-is-bash-not-storing-commands-that-start-with-spaces) is linux-behavior.

![image](https://user-images.githubusercontent.com/7049700/114946678-7bd9ec00-9e00-11eb-87d3-fe50f5327fca.png)
