### ISSUE TITLE
WSL frequently requires restart before working as expected

### ISSUE THREAD

**Issue by Sub-Xaero** [microsoft/WSL#6812]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

WSL 2

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop (Windows): Docker version 20.10.5, build 55c4c88

### Repro Steps

Not sure whether it's the same bug, or multiple that manifest the same symptoms, but WSL often requires a restart before behaving "normally". 

This manifests itself in multiple ways.

## Not being able to run Windows commands:
```
> ipconfig.exe
Command `ipconfig.exe` not found
````

In CMD ```wsl --shutdown```

After re-opening WSL:
```
> ipconfig.exe

Windows IP Configuration
...

Ethernet adapter Ethernet:
...

Ethernet adapter vEthernet (Default Switch):
...

Wireless LAN adapter WiFi:
...

Ethernet adapter vEthernet (WSL):
...
````

## Not being able to bridge to the host machine's network

Reproducible when developing a React app using `create-react-app` or similar.

When launching a development server that binds to localhost, but when opening a browser window - neither the windows `localhost:3000` address nor the WSL IP address gets through to the app.

![image](https://user-images.githubusercontent.com/9960703/114999841-1df9e280-9e9a-11eb-8d8e-65fca36c22ad.png)

After restarting WSL from `cmd` using `wsl --shutdown`, and re-running `yarn dev`, the page loads from the first try. 

## Commands just hanging

`rails g simple_form:install`

~30 mins elapsed. No progress.

`wsl --shutdown`

New ubuntu terminal:
`rails g simple_form:install`

Completes in under 2s.

--- 

More often than not, WSL needs a reboot straight after starting a PC for the first time, but sometimes stops working during the day and requires another restart. 

### Expected Behavior

WSL to behave as expected without requiring frequent restarts.

### Actual Behavior

WSL often hangs or throws strange errors until restarted using `wsl --shutdown`.

**Comment by craigloewen-msft** [comment]
Do you have fast start up enabled on your machine? If you turn that option off, do you still see this problem occurring?

**Comment by Sub-Xaero** [comment]
Interesting, yes it was enabled. Didn't know that was a thing. I've turned it off and will see if that helps. Thank you!

Do you think that turning off fast startup will help with the issue where WSL stops working mid-session, as well as on first boot?

**Comment by bmallen1** [comment]
I also experience this same behavior developing rails apps with VSCode+WSL+Ubuntu.

**Comment by brandoncollins7** [comment]
I am also experiencing this issue. WSL and docker frequently becoming non responsive in the middle of the work day forcing me to do a full reboot, what a pain!!!

**Comment by phong-phuong** [comment]
Same here, constantly need to do: `wsl --shutdown`, then restart docker.
