### ISSUE TITLE
After Enebling Hyper V I have Only Black Screen on my Computer 

### ISSUE THREAD

**Issue by Allanur1999** [microsoft/WSL#6815]
i Tryed this video https://www.youtube.com/watch?v=_Yp_qJxEkkg but my computer is not working And I cant Go inside Bios I have Only Black Screen And My Videcar Very Noisy after enebling Hyper v Please help my Guys

**Comment by craigloewen-msft** [comment]
This is likely an issue from a specific driver. I would recommend that you update your drivers on your machine, and take a look at these threads for possible fixes: 
https://github.com/microsoft/WSL/issues/5911
https://github.com/microsoft/WSL/issues/4784

If you're still running into issues after that please file logs and upload a link to those threads and we can go and take a look to see what driver is affected. We're still trying to diagnose these issues. Thank you!

/dupe #5911
