### ISSUE TITLE
add tag for issues of WSL on Intel and ARM64 devices separately.  

### ISSUE THREAD

**Issue by mbalcerzyk** [microsoft/WSL#6817]
**Is your feature request related to a problem? Please describe.**
Some issues of WSL are solved long time ago, but they exist in WSL2 on ARM64 Windows. 
Examples: 
1. firefox can be run smoothly on Intel PC with Ubuntu and VcXsrv, however the ARM64 Ubuntu with Xwindows VcXsrv it starts but each tab is crashing. Errors in console show Firefox looking and not finding GPU. Disabling hardware acceleration in settings does not help. 
2. Chromium web browser exists as a build for ARM64 and can be installed on Ubuntu but trying to run chromium-browser requires "snap install chromium", which is not implemented in WSL. On Intel, you can simply install microsoft-edge.

**Describe the solution you'd like**
Additional tag for WSL on ARM64 Windows.

**Comment by DHowett** [comment]
But.. neither of those seem to be issues with WSL? Missing snap support is well-known, and graphical applications are explicitly unsupported. Filing them again and tagging them with “arm64” will not change those facts. :smile:

**Comment by craigloewen-msft** [comment]
Our goal is for ARM64 to have the same user experience as x64 with WSL. As Dustin mentioned, both of the problems above are understood, snaps is not yet supported as we don't have systemd support, and GUI apps are (not yet) supported. Those issues are not unique to ARM64 devices. If you do find something ARM64 specific our current mode of operation is to handle that just like any other bug :) I'll close this issue out for our bookkeeping as I don't believe there's anything here actionable for the team, but please feel free to continue the discussion if you like!

**Comment by hwine** [comment]
While the OP gave bad examples, the issue of "works everywhere but ARM64" still appears to exist, and consistent labeling would be helpful. Current examples:
- #9611 <= labeled as "feature"??
- #9454 (my bug, which seems to have stalled out)

I know triaging such a large project is a challenge, but at least the 2 bugs above are both "arm64 doesn't work the same as amd64". There may be more, per [this query](https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+arm64+OR+aarch64+-label%3Awsl1).
