### ISSUE TITLE
No mic device recognized in wsl2

### ISSUE THREAD

**Issue by daniele777** [microsoft/WSL#6818]
### Windows Build Number

Windows 10

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Kali Linux kex 

### Other Software

Windows 10
Docker app desktop 

### Repro Steps

Setting up  wsl2 ambient download from Microsoft store Kali Linux ...apply kali Linux kex 

### Expected Behavior

Mic record ok 

### Actual Behavior

After install Kali Linux kex ,for long time i try  enabled mic device but nothing ...Output work ok but mic no ...  
Help !

**Comment by craigloewen-msft** [comment]
We don't explicitly support microphone on WSL as of right now. This seems to be a problem that is originated with Kali Linux kex, and we on the WSL team wouldn't have the right tools to help solve you. I'd recommend looking for support with the Kali Linux Kex team. Thank you for filing this!
