### ISSUE TITLE
Networking breaks if %TEMP% is not the default

### ISSUE THREAD

**Issue by lcsondes** [microsoft/WSL#6823]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.867]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72-microsoft-standard-WSL2

### Distro Version

Gentoo

### Repro Steps

1. Have a WSL distro with working networking (e.g., `ping 1.1.1.1` works as you'd expect)
2. Change the TEMP and TMP environment variables (in Windows) to something other than the default, preferably also on another drive like D:\Temp when WINDIR is C:\WINDOWS - it seems that the per-user ones are the ones that matter but change all 4 of them just in case
3. Reboot
4. Start the very same WSL distro and try step 1 again

Note that the non-default Temp folder existed and was **NOT** NTFS-compressed in this scenario, which is [another bug](https://github.com/microsoft/WSL/issues/5336#issuecomment-770494713) that will break WSL networking.

### Expected Behavior

Networking to keep working regardless of what TEMP/TMP are on the Windows side if they still point to a sensible path

### Actual Behavior

`Network is unreachable` or `Temporary failure in name resolution` depending on you pinging an IP address or a domain name

**Comment by 0xbadfca11** [comment]
#5437
