### ISSUE TITLE
Device Encryption Support failed automatic device encryption

### ISSUE THREAD

**Issue by djibal** [microsoft/WSL#6824]
# OS Name Microsoft Windows 10 Pro
 [Version	10.0.19042 Build 19042]

## Device Encryption Support Reasons for failed automatic device encryption:
PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable

**Comment by DHowett** [comment]
Is this a WSL issue? Can you explain how these are related?

**Comment by craigloewen-msft** [comment]
Agreed with @DHowett , this seems unrelated. I'm going to close this out for bookkeeping, please add more context and a precise description of your issue so that we can understand it and reopen this if needed.

**Comment by djibal** [comment]
Never use Docker before, So for this first time I'm getting an error, An error occurred.

Relating errors, I am not sure 100% 

but I think it's related to: 

Hyper-V - VM Monitor Mode Extensions >Yes
Hyper-V - Second Level Address Translation Extensions >No
Hyper-V - Virtualisation Enabled in Firmware >No
Hyper-V - Data Execution Protection 


>Yes
![Shot002](https://user-images.githubusercontent.com/81055330/115476100-04112480-a239-11eb-8307-a8af49c51237.png)
![Shot003](https://user-images.githubusercontent.com/81055330/115476101-05425180-a239-11eb-81f9-261e2625f6d0.png)
![Shot004](https://user-images.githubusercontent.com/81055330/115476104-05dae800-a239-11eb-8c8d-fa804fe4f2d8.png)
