### ISSUE TITLE
[Question] What's the future for WSL1?

### ISSUE THREAD

**Issue by alshdavid** [microsoft/WSL#6826]
Apologise in advance for submitting the question here but just wanted to understand where Microsoft is taking WSL.

As of right now WSL1 is far more useful to me than WSL2. I am seeing a lot of feature updates on WSL2 but nothing on WSL1. Has Microsoft dropped development on WSL1 and focusing their efforts on WSL2?

**Comment by 0xbadfca11** [comment]
No future #5326

**Comment by alshdavid** [comment]
Ah well, that's a shame. WSL1 was game changing and it's been a good ride. WSL2 is almost exactly how I was already developing software on Windows before WSL1 came onto the scene. 

The additional magic that auto expands memory and port allocation is nice, but not compelling enough a reason to use it over a Linux VM in HyperV or VMWare.
