### ISSUE TITLE
Can't connect to github.com with WSL2

### ISSUE THREAD

**Issue by GolfingSuccess** [microsoft/WSL#6827]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Visual Studio Code 1.55.2 with Remote-WSL Extension 0.54.6

### Repro Steps

Either in WSL directly or through VSCode, try `ping github.com`, `git push` or `git pull` (the last two in a repo, obviously).

### Expected Behavior

A response from GitHub.

### Actual Behavior

```
PING github.com (140.82.121.4) 56(84) bytes of data.
From PC-NAME-001.station (192.168.2.8) icmp_seq=3 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=6 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=9 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=12 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=15 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=18 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=21 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=24 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=27 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=30 Destination Host Unreachable
From PC-NAME-001.station (192.168.2.8) icmp_seq=33 Destination Host Unreachable
^C
--- github.com ping statistics ---
35 packets transmitted, 0 received, +11 errors, 100% packet loss, time 35170ms
```
`PC-NAME` isn't the actual name of my PC. Also, this only happens with GitHub as far as I can see, other sites work normally, and it's only my ethernet connection that is affected.

### Diagnostic Logs

https://aka.ms/AAc0gg0

**Comment by craigloewen-msft** [comment]
Are you using a VPN? Could you please attach logs for this issue? [Instructions here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by GolfingSuccess** [comment]
Here is the log link: https://aka.ms/AAc0gg0
No, I'm not using a VPN either from Windows or from WSL. I can connect to github.com from Windows, but not from WSL.

**Comment by therealkenc** [comment]
> I had disabled Wi-Fi to record it

This is likely variation #5313. That one was framed in terms of 'tethering' (and the discussion wandered to "SonicWall" besides), which might not be (probably isn't) your specific use case. The problem manifests when the route to the Internet on the host changes, typically when going on (and maybe off) wifi, because ethernet+wifi are the two common routes out of the host.

**Comment by GolfingSuccess** [comment]
> That one was framed in terms of 'tethering'

Woah, so I had no idea the mobile hotspot function could be causing it... so I think it affects the "adapter" whose connection is being shared, after fiddling with the settings a bit. Now I'm wondering why this could be happening, tho, because it doesn't block all sites.

**Comment by therealkenc** [comment]
> not sure if that's what's being meant by "tethering"

If your mobile hotspot is connected to your box with a usb cord it is sometimes called "tethering". If you are using your box's wifi adaptor (ie "no cord") then sometimes that's called a "mobile hotspot". [To the extent any of these terms have definitions.]

Either way there is no route (from WSL2) to (in your case) `140.82.121.4`. You might mention what third-party software you are using for '_the_ mobile hotspot function', if any, if you know, for the data point.

**Comment by GolfingSuccess** [comment]
> there is no route (from WSL2) to (in your case) `140.82.121.4`
Huh, that sounds weird, because with the (built-in) tethering on (I have a tp-link high gain wifi USB adaptor with its own driver) I can still ping `142.250.187.174` (google.com) normally, but not `140.82.121.4`. Is there a possibility that routes are being blocked by something?

**Comment by therealkenc** [comment]
WSL2 does not know one address from another.

**Comment by GolfingSuccess** [comment]
> WSL2 does not know one address from another.

That's what I thought too. Also, google.com just changed its IP address to `172.217.169.174` and it looks like that one has problems too, but the old `142.250.187.174` is still working perfectly, so I'm starting to suspect it might be having a problem with the address itself and not the destination...?

Oh, by the way, thanks for taking your time for my issue!
