### ISSUE TITLE
WSL uninstall deleted all files

### ISSUE THREAD

**Issue by benmartell93** [microsoft/WSL#6829]
Hello, As I was upgrading my WSL from 1 to 2, I uninstalled Ubuntu by going to the windows menu and uninstalling ubuntu. When I reinstalled I was prompted for a new username and password. Now all my files in my home directory are gone. Is there any way I can get my files back? 

[Version 10.0.19042.928]

**Comment by benhillis** [comment]
No, unfortunately uninstalling the Ubuntu application will remove your entire distribution as well.
