### ISSUE TITLE
WslRegisterDistribution failed with error: 0x8007007b

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#6836]
### Windows Build Number

Microsoft Windows [Versione 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

Stock downloaded from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

### Distro Version

Ubuntu-20.04

### Repro Steps

I have followed the steps shown in the following guide

https://docs.microsoft.com/en-us/windows/wsl/install-win10

### Expected Behavior

That I could install wsl2 correctly

### Actual Behavior

After the installation of WSL goes through without problems I have problems in converting to WSL2 through the command ' wsl --set-version <distribution name> <versionNumber> ', which remodeled for my needs becomes ' wsl --set- version Ubuntu-20.04 2 '.

But I get the following error: https://prnt.sc/11spu4w

Executing the following command I don't get any errors: https://prnt.sc/11spvio

At this point I have uninstalled Ubuntu and reinstalled, I get the following error: https://prnt.sc/11sr6j1

**Comment by benhillis** [comment]
Can you please include logs?

**Comment by Threefish4096** [comment]
> 
> 
> Can you please include logs?

I don't have any logs, I just reported what I see, if you tell me how to capture them I could try ..

**Comment by Threefish4096** [comment]
> 
> 
> Can you please include logs?

https://mega.nz/file/FYwSUCbK#uJfVM1lbanZnAQnxaRLwKaO0fJGk7zkpKb6yIZJJmRM

**Comment by cshei** [comment]
I'm also seeing this error on 2 different machines that I upgraded to build 21364.  My existing FedoraRemix WSL2 instance fails to launch with "The parameter is incorrect", and a new Ubuntu instance installed from the store fails with the error in the title.

Feedback here: https://aka.ms/AAc106k

**Comment by adrastogi** [comment]
@Threefish4096 thanks for reporting this and providing logs. At least from what I am seeing in the traces, Hyper-V is not able to open the kernel. Could you confirm that it's present under `C:\Windows\system32\lxss\tools`? Was the kernel installed prior to attempting these commands?

@cshei, thanks for collecting logs. I couldn't see any data in that link, unfortunately; your machine may need to be configured to allow diagnostics to go through (Windows Error Reporting in particular needs to be turned on). Also, can you confirm the error code you are seeing? If it is indeed ERROR_INVALID_PARAMETER (0x80070057) as you mentioned, then I suspect this is a potentially-different issue on 21364 which is being investigated in #6839 .

**Comment by Threefish4096** [comment]
> 
> 
> @Threefish4096 thanks for reporting this and providing logs. At least from what I am seeing in the traces, Hyper-V is not able to open the kernel. Could you confirm that it's present under `C:\Windows\system32\lxss\tools`? Was the kernel installed prior to attempting these commands?
> 
> @cshei, thanks for collecting logs. I couldn't see any data in that link, unfortunately; your machine may need to be configured to allow diagnostics to go through (Windows Error Reporting in particular needs to be turned on). Also, can you confirm the error code you are seeing? If it is indeed ERROR_INVALID_PARAMETER (0x80070057) as you mentioned, then I suspect this is a potentially-different issue on 21364 which is being investigated in #6839 .

Yes, the kernel is present, I followed the guide, the link is above, so I think I have installed the kernel correctly via the installer in the guide.( https://prnt.sc/11vv3hl )

The contents of the folder: https://prnt.sc/11vuy4o

**Comment by bpulliam** [comment]
Even though you have the correct MSI, the kernel itself is not being updated. That kernel file is definitely outdated.  To get back into a good state, you can remove the kernel file (or move it to another location), remove the kernel MSI packages, and then download the current MSI from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi.  That is currently kernel version 5.4.72.

You can also turn on MSI logging by creating the following reg key (with that on, all MSI operations create a log file in the %TEMP% directory):
Path:HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer
	Type: Reg_SZ
	Value: Logging
	Data: voicewarmupx

**Comment by Threefish4096** [comment]
> 
> 
> Even though you have the correct MSI, the kernel itself is not being updated. That kernel file is definitely outdated. To get back into a good state, you can remove the kernel file (or move it to another location), remove the kernel MSI packages, and then download the current MSI from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi. That is currently kernel version 5.4.72.
> 
> You can also turn on MSI logging by creating the following reg key (with that on, all MSI operations create a log file in the %TEMP% directory):
> Path:HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer
> Type: Reg_SZ
> Value: Logging
> Data: voicewarmupx

In the meantime, thank you very much!
I deleted the contents of the folder, uninstalled the MSI, downloaded the one you proposed and 2 new files appeared in the tools folder.
I started Ubuntu and the following error appeared:
![immagine](https://user-images.githubusercontent.com/43168947/115899848-9266ef80-a45f-11eb-9261-4b5a4cfab0a1.png)

There is already something more online than the original error, I will try to solve it later, if I can publish how I solved it.
If you know how to fix it or it has already been talked about, suggestions are welcome.

**Comment by Threefish4096** [comment]
> 
> 
> > Even though you have the correct MSI, the kernel itself is not being updated. That kernel file is definitely outdated. To get back into a good state, you can remove the kernel file (or move it to another location), remove the kernel MSI packages, and then download the current MSI from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi. That is currently kernel version 5.4.72.
> > You can also turn on MSI logging by creating the following reg key (with that on, all MSI operations create a log file in the %TEMP% directory):
> > Path:HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer
> > Type: Reg_SZ
> > Value: Logging
> > Data: voicewarmupx
> 
> In the meantime, thank you very much!
> I deleted the contents of the folder, uninstalled the MSI, downloaded the one you proposed and 2 new files appeared in the tools folder.
> I started Ubuntu and the following error appeared:
> ![immagine](https://user-images.githubusercontent.com/43168947/115899848-9266ef80-a45f-11eb-9261-4b5a4cfab0a1.png)
> 
> There is already something more online than the original error, I will try to solve it later, if I can publish how I solved it.
> If you know how to fix it or it has already been talked about, suggestions are welcome.

I follow this mini [guide](https://www.windowsphoneinfo.com/threads/how-to-resolve-wslregisterdistribution-failed-with-error-0x800706be-in-kali-linux.459516/#post-2237047) and obtain another error..

![immagine](https://user-images.githubusercontent.com/43168947/115912587-cd711f00-a46f-11eb-9719-b536a9f98de0.png)

Again...
So i return to `C:\Windows\system32\lxss\tools` , inside the latter I found old files when instead I had previously emptied it leaving only the kernel and license files.
I again removed everything and left the previous 2 files, but nothing, I keep getting: WslRegisterDistribution failed with error: 0x80004005

**Comment by craigloewen-msft** [comment]
Could you please record logs again and attach them to this thread?

/logs

**Comment by Threefish4096** [comment]
> 
> 
> Could you please record logs again and attach them to this thread?
> 
> /logs

Sorry I'm late but I was busy with an exam.
So, since I could not use the 'recreate my problem' feature I had to proceed manually using 'Windows Performance Recorder', I added the [wsl.wprp](https://github.com/microsoft/WSL/blob/master/diagnostics/wsl.wprp) profile, I started Ubuntu-20.04, the problem occurred and I stopped the tool.
[Here ](https://mega.nz/file/EEJ0jRgD#JZ7f-pw9BXuE8fmb-dkNP0-_fqedLaleBVYOetjvumo)the link to the file .etl

**Comment by sanihaq** [comment]
Hi, any update on this. Having the same problem.
