### ISSUE TITLE
dash shell is broken

### ISSUE THREAD

**Issue by alvinseville7cf** [microsoft/WSL#6838]
### Windows Build Number

10.0.19042.867

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) 

### Distro Version

Ubuntu 20.04.2 LTS

### Repro Steps

- run `chsh -s /bin/sh` (/bin/sh points to dash on my system)
- open new Windows Terminal tab and obtain `-sh: 6: export: Files/PowerShell/7:/mnt/c/tools/ruby30/bin:/mnt/c/Python39/Scripts/:/mnt/c/Python39/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program: bad variable name` error

### Expected Behavior

No error expected.

### Actual Behavior

`-sh: 6: export: Files/PowerShell/7:/mnt/c/tools/ruby30/bin:/mnt/c/Python39/Scripts/:/mnt/c/Python39/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program: bad variable name` error is reported every time I log in.

**Comment by alvinseville7cf** [comment]
It can be fixed with replacing 6-th line in /etc/profile.d/apps-bin-path.sh with `export PATH="$PATH:${snap_bin_path}"`

**Comment by therealkenc** [comment]
That is the correct fix. Looks like that file is part of the [snapd](https://packages.ubuntu.com/focal/snapd) package. The launchpad page is [here](https://launchpad.net/ubuntu/+source/snapd).

**Comment by alvinseville7cf** [comment]
I've reported this issue [here](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1925810).
