### ISSUE TITLE
WSL2: cannot execute (some) Linux executables - "No such file or directory"

### ISSUE THREAD

**Issue by dertseha** [microsoft/WSL#6841]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.870]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Alpine 3.13.4

### Other Software

Primary case:
Go, 1.16.3 ( https://golang.org/dl/go1.16.3.linux-amd64.tar.gz )

Similar cases, may require X11 setup:
SublimeText3, 3211 ( https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2 )
GoLand, 2021.1 ( https://download.jetbrains.com/go/goland-2021.1.tar.gz ) 

### Repro Steps

* Download Go from link (see "Other Software") -> Archive available
* Open a `bash` shell, and execute:
* Extract archive with `tar -xzf go1.16.3.linux-amd64.tar.gz` -> Content extracted in subfolder `go`
* Execute `./go/bin/gofmt -help` -> Usage output is displayed
* Execute `./go/bin/go version` -> `bash` reports error `-bash: ./go/bin/go: No such file or directory`

### Expected Behavior

`go` binary is properly executed; In the particular request, the version information is displayed.

(For the similar cases using other software, the respective application is started)

### Actual Behavior

`bash` reports error `-bash: ./go/bin/go: No such file or directory` and returns to shell.

(For the similar cases using other software, the same error is reported for `sublime_text_3/sublime_text` or `GoLand-2021.1/jbr/bin/java`)

### Diagnostic Logs

`ls -la` does show the files, and lists them as executable:
```
ls -la ./go/bin/
total 17116
drwxr-sr-x    2 dertseha dertseha      4096 Apr  1 19:41 .
drwxr-sr-x   10 dertseha dertseha      4096 Apr  1 19:39 ..
-rwxr-xr-x    1 dertseha dertseha  14065061 Apr  1 19:41 go
-rwxr-xr-x    1 dertseha dertseha   3449719 Apr  1 19:41 gofmt
```

A `readelf -h` does show proper output; For example for `go`:
```
 readelf -h ./go/bin/go
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x46f440
  Start of program headers:          64 (bytes into file)
  Start of section headers:          624 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         36
  Section header string table index: 9
```
(output for `gofmt` looks similar)

`strace` however fails, similar to bash:
```
strace -ff ./go/bin/go
execve("./go/bin/go", ["./go/bin/go"], 0x7ffc52fe5978 /* 27 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++
```

Dependencies are satisfied:
```
ldd ./go/bin/go
        /lib64/ld-linux-x86-64.so.2 (0x7f8fd0cb4000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f8fd0cb4000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f8fd0cb4000)
```

For reference, installing Go via `apk` does work - though this doesn't help for SublimeText or GoLand.

**Comment by dertseha** [comment]
Addendum: I've now cross-checked the problem with `Debian GNU/Linux 10` -- here this issue does not happen. Maybe Alpine-specific.

**Comment by therealkenc** [comment]
```
$ sudo apk add libc6-compat
```

![image](https://user-images.githubusercontent.com/7049700/115778687-e7293e00-a36b-11eb-92d6-f10cab59bd0d.png)

I _think_ the guidance is to use Alpine's `golang` package rather than play glibc tricks, but for an authoritative answer you'd be better to ask in those forums.
