### ISSUE TITLE
[Help Wanted] libdirectml.so

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/WSL#6842]
I accidentally deleted `libdirectml.so` in `C:\Windows\System32\lxss\lib` when I want to delete duplicate `libd3d12 (1).so`s
(Actually I deleted the whole folder.......)
Now how can I get it back?
Really appreciate any help.

Windows version 10.0.21364.1

**Comment by onomatopellan** [comment]
You will need to reinstall your Windows GPU driver.
