### ISSUE TITLE
ls: reading directory '.': Function not implemented / init: (1) ERROR: MountPlan9WithRetry

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#6845]
### Windows Build Number

Windows 10 vers. Build 21354.co_release.210402-1630

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.8.0-rc3-microsoft-standard

### Distro Version

Ubuntu 20.10

### Other Software

no one.

### Repro Steps

WSL

### Expected Behavior

That I can access every disk that's on my Windows 10 workstation.

### Actual Behavior

DMESG LOG :

swapon: swapfile has holes

ERROR: CreateSwap:875: swapon failed 22

FS-Cache: Duplicate cookie detected

FS-Cache: O-cookie c=000000006320c1f7 [p=00000000dbf76e64 fl=222 nc=0 na=1]

FS-Cache: O-cookie d=00000000c0578065 n=0000000025442b40

FS-Cache: O-key=[10] '34323934393337393337'

FS-Cache: N-cookie c=000000004bc50700 [p=00000000dbf76e64 fl=2 nc=0 na=1]

FS-Cache: N-cookie d=00000000c0578065 n=0000000036816ff5

S-Cache: N-key=[10] '34323934393337393337'

9pnet_virtio: no channels available for device drvfsa

init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/t (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=T:\;uid=1000;gid=1000;symlinkroot=/mnt/

### Diagnostic Logs

Hello to everyone.

I'm running Windows 10 vers. Build 21354.co_release.210402-1630 and WSL with this kernel version :

root@DESKTOP-N9UN2H3:/mnt/h# uname -a

Linux DESKTOP-N9UN2H3 5.8.0-rc3-microsoft-standard #1 SMP Mon Jun 29 17:48:47 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux

As soon as I run WSL I see these error messages :

Error during the mounting of one of the file system. For informations,run "dmesg".

swapon: swapfile has holes

ERROR: CreateSwap:875: swapon failed 22

FS-Cache: Duplicate cookie detected

FS-Cache: O-cookie c=000000006320c1f7 [p=00000000dbf76e64 fl=222 nc=0 na=1]

FS-Cache: O-cookie d=00000000c0578065 n=0000000025442b40

FS-Cache: O-key=[10] '34323934393337393337'

FS-Cache: N-cookie c=000000004bc50700 [p=00000000dbf76e64 fl=2 nc=0 na=1]

FS-Cache: N-cookie d=00000000c0578065 n=0000000036816ff5

S-Cache: N-key=[10] '34323934393337393337'

9pnet_virtio: no channels available for device drvfsa

init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/t (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=T:\;uid=1000;gid=1000;symlinkroot=/mnt/

so,when I try to access into the drive h (that's formatted with the ext4 fs),I get this error message :

root@DESKTOP-N9UN2H3:/mnt/h# ls

ls: reading directory '.': Function not implemented

**Comment by therealkenc** [comment]
> 5.8.0-rc3-microsoft-standard

You are on 21354, so you should be able to get the matching kernel. `wsl.exe --upgrade`. Upgrading the kernel might or might not help in your instance, but it's a good baseline to start.

![image](https://user-images.githubusercontent.com/7049700/115910720-05ea0c00-a422-11eb-8ae6-4d5df95e4c92.png)

**Comment by Marietto2008** [comment]
ok. I've removed the custom kernel. this is what happened :

![Uploading 2021-04-23_18-05-42.png…]()

![2021-04-23_18-07-47](https://user-images.githubusercontent.com/755339/115919694-796b3800-a479-11eb-9bac-b32ea42cda00.png)

**Comment by therealkenc** [comment]
The 'no channels' is common, and gerally harmless.

![image](https://user-images.githubusercontent.com/7049700/115931874-c54dbb00-a440-11eb-80d5-1bea23d06ee9.png)

Mounting the boot device is not supported per [limitations](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations). Your `error code: -22` I could not reproduce with an unadulterated `.wslconfig`.

![image](https://user-images.githubusercontent.com/7049700/115932934-cf70b900-a442-11eb-8edc-13ea75dcda0c.png)

**Comment by Marietto2008** [comment]
The solution is here : https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/comment-page-2/

wsl --mount \\.\PHYSICALDRIVE3 --partition 1

the linux partition has been mounted successfully,anyway the error "no channel available for device drvfsa" is still there.

**Comment by Marietto2008** [comment]
how can I automount the partitions that aren't mounted automatically as soon as ubuntu is landed ?

**Comment by therealkenc** [comment]
It is a pain because of the admin requirement. Maybe something like:

```
$ powershell.exe -c Start-Process -WindowStyle hidden -Verb runas -FilePath \(Get-Command wsl.exe\).Path -ArgumentList '--mount','\\.\PHYSICALDRIVE2','--bare'
```

![image](https://user-images.githubusercontent.com/7049700/116325923-25fa3200-a778-11eb-9ffd-b79224f0720e.png)

Put it in `.bashrc` and test for existence `/dev/sd?` so it only runs once. It would take some _effort_ to make that more phancy and avoid the UAC prompt. Tips and tricks welcome in the [discussions](https://github.com/microsoft/WSL/discussions).
