### ISSUE TITLE
Massive performance drop in Node between 19043.962 and 21364

### ISSUE THREAD

**Issue by mwidmann** [microsoft/WSL#6851]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.962]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Distro Version

Ubuntu 20.04, tried with Ubuntu Community Preview as well

### Other Software

Node v12.18.3, npm v6.14.6
also tried with Node v14.16.1, npm v6.14.12

### Repro Steps

Install the required node version with nvm
in a clean folder make a new nuxt project (`npx create-nuxt-app test-app`)
Choose the following options:

```
? Project name: nuxt-test
? Programming language: TypeScript
? Package manager: Npm
? UI framework: Tailwind CSS
? Nuxt.js modules: Axios - Promise based HTTP client, Progressive Web App (PWA)
? Linting tools: ESLint, Prettier
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
```

cd into `test-app`
run `npm run dev`

### Expected Behavior

I expected the same process to run at approx the same amount of time in both wsl2 in v19043.962 and wsl2 in v21364.

### Actual Behavior

In v19043.962 both the server and client compile in about 10 seconds.

In v21364 it takes about 3x the time averaging way above 30 seconds in all tests.

This is a just a basic small project. In the project I'm working on the time until the server and client are compiled and ready to work is about 1m 30s in v19043.962 and way over 3m 45s in v21364. 

This is why I had to rollback to the version in the beta channel as it hinders my work.

I used the same installation of Ubuntu 20.04 updated to the latest packages.

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

On v21364 I ran `wsl.exe --update` before trying anything out. Gladly wsl still runs after the rollback to the previous version.

I also tried installing the ubuntu community preview to be sure my installation wasn't the cause. The results are the the same.

**Comment by K2ouMais** [comment]
I am also seeing performance drops, but with composer.

It takes almost 1 minute now to check for dependency updates where it was 5-10 sec before.

I am not sure if this is a problem with WSL2 or with node/composer.

**Comment by mwidmann** [comment]
I thought that maybe it could be related to Windows Defender not using the exclusions. But the Windows Security Center seems to be broken and therefore I can't check that.

**Comment by onomatopellan** [comment]
I think it's worth trying to disable GUI support that runs by default on build 21364.
In your [.wslconfig ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file add these:
```
[wsl2]
guiapplications=false
```
and run `wsl.exe --shutdown` to make the changes effective next time you run WSL2.

**Comment by craigloewen-msft** [comment]
> I think it's worth trying to disable GUI support that runs by default on build 21364.
> In your [.wslconfig ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file add this:
> 
> ```
> [wsl2]
> guiapplications=false
> ```
> 
> and run `wsl.exe --shutdown` to make the changes effective next time you run WSL2.

Could you please try @onomatopellan 's suggestion above and disable GUI apps, does this restore performance?

**Comment by ByteProject** [comment]
I am having massive performance problems as well, as already discussed with @craigloewen-msft on Twitter, not related to node though. Generally everything that I do from Windows on the WSL2 partition is painfully slow, including VSCode, which edits the project files I have on my WSL2 partition. It took VSCode about 7 seconds to open a 456byte (!) file. It takes minutes for opening an webpage that has been generated with one of my build scripts. I actually don't notice much performance drop in Linux itself more when Win / Linux cross operate. It takes 2 minutes to copy a folder with more than one megabyte. The GIT control in VSCode is broken because the file access is so slow that it takes too long to read in my repository information. 

I confirm that I have deactivated WSLg in .wslconfig and it did not change anything, suggesting that the performance drop might not be WSLg related. 

I can't even tell what steps necessary to produce the issues, all I did was updating to build 21364 and I also did update WSL via "WSL --update". My computer is very performant, I'd generally would rule out any performance related issues caused by my hardware. I also confirm that all previous builds together with WSL2 ran very fast and performant. The performance drop now though is significant. When I am saving a 100kb source file I need to wait for a minute until the file is saved and I am able to compile the sources, you can imagine it's a pain to work that way.

**Comment by ByteProject** [comment]
One thing to add here, maybe that helps. I noticed that the performance issue for me only relates to files that haven't changed. So for example when I open the 456kb file the first time, it takes 7 seconds. The next time I open it, it's straight there. If I change the file and the reopen it, it's slow again. Does that make any sense?

**Comment by benhillis** [comment]
@ByteProject - Where are you storing your files?  In one of your mounted Windows drives (/mnt/c/...) or somewhere in the ext4 volume?

**Comment by ByteProject** [comment]
@benhillis The files are stored directly on the ext4 volume. They are not on the mounted Windows drives.

**Comment by onomatopellan** [comment]
@ByteProject Please take a look at the thread https://github.com/microsoft/WSL/issues/4498. Almost all the usual suspects for slowdowns in WSL2 are commented there.

**Comment by mwidmann** [comment]
> I think it's worth trying to disable GUI support that runs by default on build 21364.
> In your [.wslconfig ](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file add this:
> 
> ```
> [wsl2]
> guiapplications=false
> ```
> 
> and run `wsl.exe --shutdown` to make the changes effective next time you run WSL2.

Thanks for the suggestion. Doesn't seem to make any difference. 

My .wslconfig looks like this:

```
[wsl2]
memory=6GB
guiapplications=false
```

**Comment by mwidmann** [comment]
Just to be more precise. The files I try to run are all inside the Linux ext4 filesystem and not on any `/mnt/*` drive. That was the first thing I had to change when I moved to wsl2 as soon as it was available.

Could this be related to Windows defender doing stuff on wsl processes files? What are the correct settings for windows defender? So far I excluded the `vmmem`, `node`, `npm` processes.

**Comment by ByteProject** [comment]
> 
> 
> @ByteProject Please take a look at the thread #4498. Almost all the usual suspects for slowdowns in WSL2 are commented there.

None of this works for me. Either build 21364 is the root cause somehow or it really came with the WSLg or new Linux Kernel update. I have no other explanation for this. Prior to these events everything was faster than lightspeed.

**Comment by benhillis** [comment]
@ByteProject - would it be possible to try the older kernel? You should be able to switch to it using

```wsl.exe --update --rollback & wsl.exe --shutdown```

Ensure you're using the older kernel by running ```wsl.exe cat /proc/version```

**Comment by ByteProject** [comment]
@benhillis I reverted to the old Kernel and that did not change anything. What I found out is that my issue is mostly related to Windows applications accessing the WSL2 ext4 volume. When I copy for example a folder from the ext4 drive onto the Windows Destkop it takes more than 2 minutes for a 120 byte content folder. It copied those files with average 5 bytes per second. If I copy the same folder from my ext4 volume via `cp -r Release/ /mnt/c/Users/Stefan/OneDrive/Desktop/` it only takes a second. I have a SSD btw, so hard drive performance can be ruled out here. It is almost as if Windows apps accessing the ext4 partition only get a very limited bandwidth if that makes sense somehow. 

![grafik](https://user-images.githubusercontent.com/153544/116436456-b73ad880-a84c-11eb-9b34-2a6638ca4d70.png)

**Comment by benhillis** [comment]
@ByteProject - You're accessing the ext4 volume via \\\\wsl.loclahost?  That will definitely be slower than inside the VM, you're going over a file server.

**Comment by ByteProject** [comment]
Yes, but not "3 minutes for a 120 kilobyte folder slow", right? What I experience here also massively affects VSCode, which takes one minute to save a 98kb file and VSCode uses the WSL Remote plugin. I've been working for quite a few months with WSL2, I've been using Explorer to share files inbetween the Win partition and EXT4, I've been copying files over Bash, I did everything and never did I experience such massive performance drops. The system is unusable slow, which happened after I upgraded to current build 21364 and updated WSL.

**Comment by mwidmann** [comment]
> @ByteProject or @mwidmann - would it be possible to try the older kernel? You should be able to switch to it using
> 
> `wsl.exe --update --rollback & wsl.exe --shutdown`
> 
> Ensure you're using the older kernel by running `wsl.exe cat /proc/version`

Well this is strange.

I opened a powershell as admin and tried running the commands as you said.

Before that I ran a `cat /proc/version` in my Ubuntu installation

```
Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021
```

First try:

```
PS C:\WINDOWS\system32> wsl.exe --update --rollback & wsl.exe --shutdown
At line:1 char:29
+ wsl.exe --update --rollback & wsl.exe --shutdown
+                             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Second try:

```
S C:\WINDOWS\system32> wsl.exe --update --rollback
Rollback failed. No kernel is available to rollback and the WSL 2 kernel is already the earliest available version.
```

So I thought. OMG, did the rollback and re-installation of the 21364 build revert the update I made? But then..

```
PS C:\WINDOWS\system32> wsl.exe --update
Checking for updates...
No updates are available.
Kernel version: 5.10.16
```

So it seems I can't rollback.

**Comment by mwidmann** [comment]
As for copying files between linux and windows or accessing files from inside wsl in either VSCode using the WSL remote extension or IntelliJ using a Windows mount to U:, I don't notice the problems @ByteProject is facing. Copying is snappy, opening files works fine.

**Comment by craigloewen-msft** [comment]
Reading through this thread it seems like all the general peformance issues are gone. The only one that still seems alive is the \\wsl.localhost\ copy performance that @ByteProject is seeing 

@ByteProject could you please collect logs and attach them here? That will help us determine what could be going on here. /logs
