### ISSUE TITLE
Unable to Run Python3 in WSL2

### ISSUE THREAD

**Issue by yonicarver** [microsoft/WSL#6856]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.867]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

Run "python3" in Ubuntu

### Expected Behavior

Launch into Python3

### Actual Behavior

Got this traceback

/usr/bin/python3: line 1: $'\225:\362n\002Y\236P\264': command not found
/usr/bin/python3: line 1: $'\201\272\223\363\215\365^\223\200G\255\326\373w': command not found
/usr/bin/python3: line 2: $'\311+\341\213\350i\263.9J^\207ʘ\230\315\ER\265': command not found
/usr/bin/python3: line 2: $'\217\030\345': command not found
/usr/bin/python3: line 3: syntax error near unexpected token `)'
/usr/bin/python3: line 3: `e<tP-U1< z>됪kT��mCNf7*ancɈ%r0RF{s9 >[EaoלӝIWyM5OܒN-F4QQW|aiRH8T{:<Ӯf- OGMLL0qUC{+)ZW~͟Gkid0-56H5؛].\ڠAEԣ]*FQBNK$fȷ\rІ|X.+uKZ|ip$<'OJ-!e2sCz{PED'(Bx[M~k0        .OŮK5O(w"@:&V9Wy08F4hlBqoUYV,m=ڄ)tA<q#Aowܳ<?~䐍X)H~b/eHT7#jy$cWJ>b'+I)Y<[|/jK{K]xٰ'

**Comment by therealkenc** [comment]
Ref #6325 in the sense that python is receiving garbage input.

**Comment by craigloewen-msft** [comment]
I'm unable to reproduce this issue, when I try and run python3 I am able to. 

If you try this on another distro do you get the same error (Like Debian)? 

As well, could you please collect logs for us? /logs

**Comment by therealkenc** [comment]
Logs never hurt, but like #6325 the error is from inside the Linux distro. The python interpreter (via the Linux kernel, via the VM) is faithfully executing garbage in the script text itself. Why the script text gets corrupted is unknown. That `/bin/bash` binary is not _also_ corrupt is presumably by sheer luck. Otherwise you'd never make it to a prompt.
