### ISSUE TITLE
Can't use my Windows built-in VPN with WSL2?

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#6859]
### Windows Build Number

21364

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Debian latest version

### Repro Steps

I have PPTP VPN connected in Windows 10 from the settings, no 3rd party app.

### Expected Behavior

I'm expecting WSL2 OS to access to the VPN.

### Actual Behavior

WSL2 doesn't have access to the VPN.

**Comment by craigloewen-msft** [comment]
Could you explain more what cannot access to the VPN means for you? Are you able to access general internet resources? Or are you looking to access the VPN specific endpoints?

**Comment by Cortana-117** [comment]
> Could you explain more what cannot access to the VPN means for you? Are you able to access general internet resources? Or are you looking to access the VPN specific endpoints?

Hi,
my ISP blocks some websites, on the host when VPN is connected, I can access them, but on WSL2 OS (with WSLg), I can't.
tried on Ubuntu and Debian with Microsoft Edge Dev.

**Comment by craigloewen-msft** [comment]
Got it, could you please provide logs and reproduce this problem (i.e: Open up Microsoft Edge Dev and try to access a site) and attach the link to the logs here? /logs

**Comment by Cortana-117** [comment]
> Got it, could you please provide logs and reproduce this problem (i.e: Open up Microsoft Edge Dev and try to access a site) and attach the link to the logs here? /logs

Hi, sure, I just submitted a feedback in feedback hub with "recreate my problem", here is the link to it: 
https://aka.ms/AAc2epo

**Comment by AgrawalAmey** [comment]
I am facing the same issue with Ubuntu 20.04.

**Comment by bhushant3769** [comment]
I am having the same issues with Ubuntu 20.04 on WSL2 kernel 5.10.60
