### ISSUE TITLE
stable crash(may be msrc is on holliday best wish)

### ISSUE THREAD

**Issue by avboy1337** [microsoft/WSL#6869]
### Windows Build Number

Microsoft Windows [版本 10.0.20339.2]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-20339-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #2-Microsoft Sat Apr 17 11:00:00 PST 2021

### Distro Version

Ubuntu-18.04

### Other Software

not important

### Repro Steps

when compile v8 use windows subsystem (ubuntu 18)
it will stable reproduce a system crash like that:

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
cd depot_tools
export PATH=/home/!!!!!!!!!!!!!!YourUserName!!!!!!!!!!!!!!/depot_tools:$PATH
./update_depot_tools
fetch --nohooks v8
cd v8
./build/install-build-deps.sh
gclient runhooks -v

then crash !!

stable crash

### Expected Behavior

no crash 

### Actual Behavior

crash

**Comment by avboy1337** [comment]
system is server2022 datacenter with desktop
as following:
![image](https://user-images.githubusercontent.com/5463104/116016153-59e93080-a66e-11eb-9e0f-e8874e3bba9b.png)

**Comment by Biswa96** [comment]
Any sneak peak into the money dump?

**Comment by avboy1337** [comment]
> Any sneak peak into the memory dump?

certainly OK / and leave email is OK

**Comment by craigloewen-msft** [comment]
@avboy1337  could you please attach the MEMORY.DMP file located in your Windows folder to a feedback hub issue? (Likely it will be in C:\Windows) 

The instructions on how to attach logs can be found in the next comment, just make sure to click 'attach' and then attach the file after putting it into a .zip please. 

/logs

**Comment by avboy1337** [comment]
> @avboy1337 could you please attach the MEMORY.DMP file located in your Windows folder to a feedback hub issue? (Likely it will be in C:\Windows)
> 
> The instructions on how to attach logs can be found in the next comment, just make sure to click 'attach' and then attach the file after putting it into a .zip please.
> 
> /logs

https://drive.google.com/file/d/1GixcgfVEO79HpRv6Szyxhpp43yaFPIne/view?usp=sharing

**Comment by avboy1337** [comment]
> > @avboy1337 could you please attach the MEMORY.DMP file located in your Windows folder to a feedback hub issue? (Likely it will be in C:\Windows)
> > The instructions on how to attach logs can be found in the next comment, just make sure to click 'attach' and then attach the file after putting it into a .zip please.
> > /logs
> 
> https://drive.google.com/file/d/1GixcgfVEO79HpRv6Szyxhpp43yaFPIne/view?usp=sharing

https://drive.google.com/file/d/1GixcgfVEO79HpRv6Szyxhpp43yaFPIne/view?usp=sharing

**Comment by avboy1337** [comment]
the full details to replay crash is to compile v8 in wsl.
full command is as following 

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
cd depot_tools
export PATH=/home/!!!!!!!!!!!!!!YourUserName!!!!!!!!!!!!!!/depot_tools:$PATH
./update_depot_tools
fetch --nohooks v8
cd v8
./build/install-build-deps.sh
gclient runhooks -v

may be it is a long time to replay this bluescreen for Chinese , because of speed to google server that not easy to .... .
i think its not a problem for you .

**Comment by therealkenc** [comment]
Folks have been compiling chromium on WSL1 for a long time. It might be OOM related, or it might be general flakiness unrelated to WSL. For a big compile job like that, you'll have a better experience on WSL2 (setting aside the blue screen).

**Comment by avboy1337** [comment]
> Folks have been compiling chromium on WSL1 for a long time. It might be OOM related, or it might be general flakiness unrelated to WSL. For a big compile job like that, you'll have a better experience on WSL2 (setting aside the blue screen).

confused for native linux compiling job , just eat 4G mem is enouth.
and WSL1 runing on native Windows (not in vm ) with 64GB mem is also going to bsod.

**Comment by therealkenc** [comment]
> and WSL1 runing on native Windows (not in vm ) with 64GB mem is also going to bsod.

Interestingly enough, your repro steps took down my machine as well. No bsod, just a hard reboot. Which is novel, and a regress.

You are on WSL1. The work-around remains using WSL2.

**Comment by avboy1337** [comment]
> > and WSL1 runing on native Windows (not in vm ) with 64GB mem is also going to bsod.
> 
> Interestingly enough, your repro steps (on WSL1) took down my machine as well. No bsod, just a hard reboot. Which is novel, and a regress.
> 
> You are on WSL1. The work-around remains using WSL2.
> 
> ![image](https://user-images.githubusercontent.com/7049700/116349622-44c2ed80-a7a5-11eb-9ddd-a5f2f0124314.png)

any how , big 3ks for your attention !!
bro You are very professional !!
and close it as your plesure.

**Comment by avboy1337** [comment]
the newest server 20344 is also bluescreen =reboot , and can not add wsl2 in it.
when compiling v8 using wsl1.

**Comment by therealkenc** [comment]
> the newest server 20344 is also bluescreen =reboot

Right, I should have stated my ver. My hard reset (without bluescreen) with your reproduction steps was on 21364. It is a good catch, thank-you.

There are instructions for installing WSL2 on Windows Server [here](https://docs.microsoft.com/en-us/windows/wsl/install-on-server). If it fails go ahead and open a new submission for that.

**Comment by avboy1337** [comment]
> > the newest server 20344 is also bluescreen =reboot
> 
> Right, I should have stated my ver. My hard reset (without bluescreen) with your reproduction steps was on 21364. It is a good catch, thank-you.
> 
> There are instructions for installing WSL2 on Windows Server [here](https://docs.microsoft.com/en-us/windows/wsl/install-on-server). If it fails go ahead and open a new submission for that.

bro you are so quick!
and sadly to show yout that it is really blocked for WSL2. before yesterday i had make a full test that wsl2 is not ok on server 20344.

**Comment by therealkenc** [comment]
This was closed (won't look a gift horse in the mouth) but as a data point, I got the hard reboot on WSL1 installing VS Code. It is something networking related.
