### ISSUE TITLE
Bitlocker with WSL

### ISSUE THREAD

**Issue by prabhumns** [microsoft/WSL#6871]
### Windows Build Number

Microsoft Windows [Version 10.0.21364.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Bitlocker

### Repro Steps

Partition your disk.
Use Bitlocker and lock one of the partition of that disk. (Don't turn on Auto unlock in bitlocker)
Restart the system (Ignore, if the partition is locked, or lock it manually)
Open wsl

### Expected Behavior

No error while mounting all partitions.
A way to ignore automount for a partition.

### Actual Behavior

No error should appear and a way to ignore mounting the locked partition.

An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

### Diagnostic Logs

[   17.863397] init: (1) ERROR: MountPlan9WithRetry:285: mount drvfs on /mnt/f (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=F:\;uid=1000;gid=1000;symlinkroot=/mnt/
[   17.863400] ) failed: 13
[   20.621194] init: (97) ERROR: CreateProcessEntryCommon:606: execvpe docker failed 2
[   20.621198] init: (97) ERROR: CreateProcessEntryCommon:616: Create process not expected to return

**Comment by OneBlue** [comment]
Thanks for reporting this @prabhumns.

Can you please [collect logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and attach share them on this issue ?
