### ISSUE TITLE
Error while loading module fuse in Fedora33remix

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/WSL#6873]
Fedora33 distro doesn't start clean using Fedora icon in Startup pane, i.e. using systems
Microsoft Windows [Version 10.0.21364.1000]
uname -a
Linux MSI-wsl 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

systemctl status:
   State: degraded
     Jobs: 0 queued
   Failed: 1 units
systemctl --failed
systemd-modules-load.service loaded failed failed Load Kernel Modules
systemctl status
● systemd-modules-load.service - Load Kernel Modules
     Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static)
     Active: failed (Result: exit-code) since Mon 2021-04-26 10:33:12 IDT; 10h ago
       Docs: man:systemd-modules-load.service(8)
             man:modules-load.d(5)
    Process: 1897 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
   Main PID: 1897 (code=exited, status=1/FAILURE)

Apr 26 10:33:12 MSI-wsl systemd[1]: Starting Load Kernel Modules...
Apr 26 10:33:12 MSI-wsl systemd-modules-load[1897]: Failed to look up module alias 'fuse': Function not implemented
Apr 26 10:33:12 MSI-wsl systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 10:33:12 MSI-wsl systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
Apr 26 10:33:12 MSI-wsl systemd[1]: Failed to start Load Kernel Modules.

modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.10.16.3-microsoft-standard-WSL2

Indeed, /lib/modules/5.10.16.3-microsoft-standard-WSL2 is empty but Console log contains fuse: init (API version 7.31)

Does it mean that fuse module is built in and can be used or Either Microsoft or Fedora33remix distro provider must provide this module. How to hide this error, using blacklist?
Upgraded to ver 34 Fedora assumes Kernel version 5.11. Can built-in into Kernel 5.10 can be used as module for 5.11?

**Comment by craigloewen-msft** [comment]
Hi @PavelSosin-320 , we don't have active support for systemd in WSL yet, though it is an item on our backlog. The scenario you're using right now isn't fully supported by us so we don't have an actionable item here to unblock you. If you'd like the community to take a look I would recommend you post this under the 'Discussions' section above as a community item. Thank you for filing!
