### ISSUE TITLE
Can't upgrade kali-linux to wsl2

### ISSUE THREAD

**Issue by sagniksen31** [microsoft/WSL#6875]
Hello, 
I am Having a issue that I can't Upgrade my kali linux to wsl2 
Here is the output when i try to upgrade it
`PS C:\Windows\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
PS C:\Windows\system32> wsl --set-version kali-linux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation could not be started because a required feature is not installed.
PS C:\Windows\system32>`

Can Anyone explain what am I doing Wrong
As I have enabled virtualisation in BIOS and enadbled WSL and Virtual Machine platform.
Please help I am stuck on it for days.

PC Specs-
GPU-Nvidia GT610 2GB
CPU - Intel i3 3220
Ram-4GB

Virtualization is also enabled.

**Comment by avboy1337** [comment]
tried on server 2022 ,also can not  and some body says it can not on server 2022.
dont know why

**Comment by sagniksen31** [comment]
I am on windows 10 pro And the OS build is latest

**Comment by benhillis** [comment]
@sagniksen31 - I suspect virtualization is not enabled in your BIOS.

**Comment by sagniksen31** [comment]
> @sagniksen31 - I suspect virtualization is not enabled in your BIOS.

No, It is enabled.I have checked it 3 times.

**Comment by benhillis** [comment]
@sagniksen31 - could you share the output of msinfo32.exe?

**Comment by sagniksen31** [comment]
> @sagniksen31 - could you share the output of msinfo32.exe?

![Screenshot (152)](https://user-images.githubusercontent.com/73706036/116276908-961dad80-a7a2-11eb-8183-0802ca2be612.png)

**Comment by sagniksen31** [comment]
hope this helps

**Comment by sagniksen31** [comment]
This is my msinfo32 ss

**Comment by sagniksen31** [comment]
Please help I am stuck in it for days

**Comment by onomatopellan** [comment]
Are you using any other virtualization solution like VirtualBox or VMware)? It seems the hypervisor has been disabled even if you have virtualization enabled in the BIOS.

Try opening an elevated cmd and run `bcdedit /set hypervisorlaunchtype auto`. After restart msinfo32 should show "Hypervisor has been detected".

**Comment by sagniksen31** [comment]
> Are you using any other virtualization solution like VirtualBox or VMware? It seems the hypervisor has been disabled even if you have virtualization enabled in the BIOS.
> 
> Try opening an elevated cmd and run `bcdedit /set hypervisorlaunchtype auto`. After reboot msinfo32 should show "Hypervisor has been detected" and WSL2 should work.

Yes, I use bluestacks beta 5, and VMware, So if I enable Hypervisor I won't be able to use bluestacks beta 5

**Comment by sagniksen31** [comment]
> Are you using any other virtualization solution like VirtualBox or VMware? It seems the hypervisor has been disabled even if you have virtualization enabled in the BIOS.
> 
> Try opening an elevated cmd and run `bcdedit /set hypervisorlaunchtype auto`. After reboot msinfo32 should show "Hypervisor has been detected" and WSL2 should work.

Did as you told so, still no change

**Comment by onomatopellan** [comment]
>Yes, I use bluestacks beta 5, and VMware, So if I enable Hypervisor I won't be able to use bluestacks beta 5 .So is it only the solution?

Correct. You need the hypervisor running if you want to use WSL2. Read [this](https://support.bluestacks.com/hc/en-us/articles/360041390952-How-to-run-BlueStacks-with-Hyper-V-enabled) for a working BlueStacks under hyper-v. Latest version of VMware >15.5 already works under hyper-v.

>Did as you told so, still no change

Can you post the output of running `bcedit`?

**Comment by sagniksen31** [comment]
So, after  enabling the hypervisor, I found that it shows "a hypervisor is detected " in msinfo32 and I tried to upgrade kali Linux to wsl2,  but still got the same error

**Comment by sagniksen31** [comment]
> >Yes, I use bluestacks beta 5, and VMware, So if I enable Hypervisor I won't be able to use bluestacks beta 5 .So is it only the solution?
> 
> Correct. You need the hypervisor running if you want to use WSL2. Read [this](https://support.bluestacks.com/hc/en-us/articles/360041390952-How-to-run-BlueStacks-with-Hyper-V-enabled) for a working BlueStacks under hyper-v. Latest version of VMware >15.5 already works under hyper-v.
> 
> >Did as you told so, still no change
> 
> Can you post the output of running `bcdedit`?

So, after enabling the hypervisor, I found that it shows "a hypervisor is detected " in msinfo32 and then I tried to upgrade kali Linux to wsl2, but still got the same error

**Comment by onomatopellan** [comment]
Now that you are under the hypervisor you can follow the [steps for installing WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps)

**Comment by sagniksen31** [comment]
Thanks, If I have any issues I will leave a comment here

**Comment by sagniksen31** [comment]
> Yes, pay special attention to step 3 and 4.

`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.

Press any key to continue...`

Still This Error :(

The Machine is Talking about which feature?

**Comment by onomatopellan** [comment]
@sagniksen31 You are now at this point https://github.com/microsoft/WSL/issues/4626. Try gajama solution as it helped lots of people.

**Comment by sagniksen31** [comment]
> @sagniksen31 You are now at this point https://github.com/microsoft/WSL/issues/4626. Try gajama solution as it helped lots of people.
> 

I also tried it, It didn't work.

**Comment by onomatopellan** [comment]
Then I don't know what's happening. What I'd try is disabling WSL2 and enabling it again.

- Open Windows features

![GitHub Logo](https://storage.googleapis.com/static.configserverfirewall.com/images/windows10/wsl/wsl2-virtual-machine-platform.webp)
- uncheck Windows Subsystem for Linux and Virtual Machine Platform
- reboot
- Open Windows features again
- check Windows Subsystem for Linux and Virtual Machine Platform
- reboot
- try running WSL2 again

**Comment by sagniksen31** [comment]
I tried this, But I will try it once more

**Comment by ojeh-a** [comment]
![IMG_20240419_063932_917.jpg](https://github.com/microsoft/WSL/assets/113605336/581791c7-c450-418a-a941-7c059af65482)
I got stuck while upgrading at 5% for 10 hours, then I restarted the system and tried again, I've been stuck here since. What do I do?

**Comment by alphaxlegion** [comment]
try this command it fixed my issue in kali linux wsl

Steps

1. Open Powershell as administration 
2. Run this command wsl --unresgister <Linux Distro Name> 
3. Uninstall Linux WSL from Windows 
4. Again download from Microsoft store 
5. Then run your Linux WSL after installation 
6. Don't run any upgrade just run sudo apt-get update 
7. After that run these two command in Linux WSL 
8. "sudo mv /usr/sbin/telinit /usr/sbin/telinit.bak "
9. "sudo ln -s /usr/bin/true /usr/sbin/telinit"
10. After this then run sudo apt-get update && sudo apt-get upgrade
11. Boom Problem fixed
