### ISSUE TITLE
WSL Shutdown problem

### ISSUE THREAD

**Issue by mshane911** [microsoft/WSL#6878]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.4.72

### Distro Version

Kali Linux 2021.1

### Repro Steps

1. Run WSL
2. Open Task Manager
3. Observe vmmem is running
4. Shutdown WSL (wsl --shutdown)
5. VMMEM shutdown for a while then run again after a few seconds
6. check wsl (wsl -l -v)
7. WSL is running again

### Expected Behavior

i want to stop vmem if im not using wsl

### Actual Behavior

vmem kept running after wsl shutdown

**Comment by therealkenc** [comment]
> Kali Linux 2021.1

Did you install Win-Kex?

**Comment by mshane911** [comment]
> > Kali Linux 2021.1
> 
> Did you install Win-Kex?

Nope

**Comment by therealkenc** [comment]
I cannot reproduce here; Kex was the wild ass guess. You would have mentioned Docker if you were using it, and that wouldn't start a WSL distribution (kali-linux). Breathing on the `\\wsl$\kali-linux` filesystem (for example in Explorer) will start it, but that probably isn't your case either. That's all I have for guesses I have on the externality that is starting your kali-linux distro.

**Comment by benhillis** [comment]
I suspect that a file from \\\\wsl$ of \\\\wsl.localhost is in your recently used files.  Can you clear your file explorer history and see if the problem persists?

![image](https://user-images.githubusercontent.com/17727402/116591387-9bc6e080-a8d3-11eb-906c-7b621c34d401.png)

**Comment by avboy1337** [comment]
> I suspect that a file from \\wsl$ of \\wsl.localhost is in your recently used files. Can you clear your file explorer history and see if the problem persists?
> 
> ![image](https://user-images.githubusercontent.com/17727402/116591387-9bc6e080-a8d3-11eb-906c-7b621c34d401.png)

i am going to test it now .
and suddenly i successed because install another driver and reboot forced.

**Comment by Iskers** [comment]
I have this problem. Same steps.
