### ISSUE TITLE
Failed WSL2 login and problematic WSL1 login after win10 upgrade  

### ISSUE THREAD

**Issue by pchiang5** [microsoft/WSL#6880]
### Windows Build Number

Microsoft Windows [Version 10.0.21364.1011]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-21364-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) )

### Distro Version

Ubuntu 20.04

### Repro Steps

Everything was fine with both WSL1 and WSL2 (Win10 21H1). 

After upgrading to 21364.1011. I could not log in to the existing WSL2 with 'Exit code 4294967295' in the windows terminal. 

When I tried fresh installation of Ubuntu 20.04 (--set-default-version 2), the installation failed with the following error message: 

> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x8037011e
> Error: 0x8037011e The host compute system service has disconnected unexpectedly.

Then I use --set-default-version to 1 and install Ubuntu-20.04 again. There were several error messages during the installation:

> Installing, this may take a few minutes...
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> Please create a default UNIX user account. The username does not need to match your Windows username.
> For more information visit: https://aka.ms/wslusers
> Enter new UNIX username:
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> New password:
> Retype new password:
> passwd: password updated successfully
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> Installation successful!
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> To run a command as administrator (user "root"), use "sudo <command>".
> See "man sudo_root" for details.
> 
> Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 4.4.0-21364-Microsoft x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu Apr 29 10:36:26 CST 2021

dmesg showed following:

> [    0.040669]  Microsoft 4.4.0-21364.1011-Microsoft 4.4.35
> [    0.324915] <3>init: (1) ERROR: UtilCreateProcessAndWait:656: /bin/mount failed with status
> [    0.324926] 2000
> 

I tried to perform a fresh install with the Dev iso 21354 and the situation was the same. Everything went back to normal when I rolled back to the 21H1 with system recovery. 

### Expected Behavior

Successful login to WSL2. 
Normal login to WSL1 without error message. 

### Actual Behavior

1. Cannot log in to WSL2
2. WSL1 ERROR: UtilCreateProcessAndWait:656: /bin/mount failed with status

**Comment by benhillis** [comment]
We will need logs to diagnose this.

**Comment by pchiang5** [comment]
After automatic update to 21370.1. Now both WSL1 and WSL1 failed to log in identically with the error message "The host compute system service has disconnected unexpectedly."

I have submitted it through the feedback hub and below is the manual log. 
[wsl.zip](https://github.com/microsoft/WSL/files/6402849/wsl.zip)

**Comment by CowboyRobotInDisguise** [comment]
very helpful, would read again
