### ISSUE TITLE
ssh from Windows to WSL2 failed with error: 10061

### ISSUE THREAD

**Issue by astroboylrx** [microsoft/WSL#6882]
### Windows Build Number

Microsoft Windows [Version 10.0.21370.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Nothing special, I followed the official [guide](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) and installed OpenSSH using PowerShell. 

On the WSL2 side, I also have OpenSSH installed:
```bash
openssh-server/focal-updates,focal-security,now 1:8.2p1-4ubuntu0.2 amd64 [installed]
```
and the server is running:
```
➜  ~ sudo service ssh status
 * sshd is running
```
and is listening to port 2222 with the following setup in `/etc/ssh/sshd_config`:
```bash
ListenAddress 127.0.0.1
Port 2222
PasswordAuthentication yes
PubkeyAuthentication yes
```

### Expected Behavior

Given the setup I have, executing the command `ssh myself@localhost -p2222` should connect me to WSL2 from Windows.

### Actual Behavior

Since build 21354.1, I cannot ssh into WSL2 from Windows with `ssh myself@localhost -p2222`, which I have used w/o problem for quite some time.

Now it always gives error 10061
```powershell
PS C:\Users\astro> ssh -vvv myself@localhost -p2222
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Reading configuration data C:\\Users\\myself/.ssh/config
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolving "localhost" port 2222
debug2: ssh_connect_direct
debug1: Connecting to localhost [::1] port 2222.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:0000022654ACBB70
debug1: connect to address ::1 port 2222: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:0000022654ACBB70
debug1: connect to address 127.0.0.1 port 2222: Connection refused
ssh: connect to host localhost port 2222: Connection refused
```

In build 21354, sometimes I was able to change the port number (e.g., 2225) and make this work. Though this workaround fails since build 21364. In rare cases, a reboot fixes this issue. But it feels like lottery and I haven't found the pattern.

### Diagnostic Logs

If you have suggestions about extra logs that I may find and add here, please let me know. Thanks.

**Comment by therealkenc** [comment]
Thanks for the report; I was able to reproduce here on 21364. As a work-around WSL2's `eth0` address takes.

![image](https://user-images.githubusercontent.com/7049700/116616081-10f4de80-a8f1-11eb-9e0a-83550b75ad69.png)

**Comment by astroboylrx** [comment]
> Thanks for the report; I was able to reproduce here on 21364. As a work-around WSL2's `eth0` address takes.
> 

Thanks a lot for the prompt follow-up!

Interesting, I saw your WSL2 has an `eth0` address starting with `192.168`. I thought WSL2 is often assigned an address within `172.16.0.0/12`. I only encountered `192.168` once after upgrading to build 21354 (at the first reboot). After that, the address changed back to `172.XX` and never become`192.168.XX` again. I wonder what's behind this and under what circumstance will WSL2 get `192.168.XX`?

**Comment by therealkenc** [comment]
> I wonder what's behind this and under what circumstance will WSL2 get 192.168.XX?

How WSL2 comes up with it's `eth0` IP address is a mystery to not just you. I had to reboot, and mine is now `172.*`. Don't read anything into it (I don't).

![image](https://user-images.githubusercontent.com/7049700/116619727-b01bd500-a8f5-11eb-8a77-d556bcfa4e90.png)

`Wsl.etl` [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) are [here](https://1drv.ms/u/s!AgPhYKrkK6_3gdxzwCxw3lxHYRpLpw?e=ykgjFv) and the bat output is [here](https://gist.github.com/therealkenc/a20caca1084c0259e7d1a83e0218e7e9).

**Comment by Gornoka** [comment]
I have the same issue on my new Windows 11 machine, the error occures both in WSL2 and in the Windows powershell.

**Comment by jvrfaria** [comment]
Any update? :(

**Comment by astroboylrx** [comment]
I think I finally found what happened behind it. As pointed out by this [article](https://hungyi.net/posts/wsl2-reserved-ports/), 

> Allegedly a botched Windows update resets the dynamic TCP port range in some cases. When this happens, Hyper-V ends up aggressively reserving it for its own Windows Container Host Networking Service (HNS).

The reserved ports for TCP was sparsely distributed from 49152 to 65536. However, some earlier Windows update made the reserved ports ranged from 1259 to 65536, and the exact ports change each reboot. That's why sometimes `ssh`-ing from Windows to WSL via port 2222 works and sometimes it fails with error 10061.

As a solution, one may follow the aforementioned [article](https://hungyi.net/posts/wsl2-reserved-ports/) and manually restrict the port range allowed for reservation. Alternatively, one may follow this [post](https://github.com/docker/for-win/issues/3171#issuecomment-459205576) to prevent Windows reserving certain ports they desire.

**Comment by gyurmogyuri** [comment]
Oh, this report is good to I found.
Its have same:
```
@PS C:\Windows\system32> wsl --version
WSL-verziďż˝: 1.0.3.0 
Kernelverziďż˝: 5.15.79.1
WSLg-verziďż˝: 1.0.47
MSRDC verziďż˝ja: 1.2.3575
 Direct3D-verziďż˝: 1.606.4 
 DXCore verziďż˝ja: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp 
Windows verziďż˝ja: 10.0.1904
```

```
PS C:\Windows\system32> ssh -p 2022 gyx@172.31.81.48
gyx@W10-xx:~$ exit 
 logout
 Connection to 172.31.81.48 closed
```


 **debug3: finish_connect - ERROR: async io completed with error:** 

```
PS C:\Windows\system32> ssh -vvv -p 2022 gyx@192.168.0.12                                                            OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2 
debug3: Failed to open file:C:/Users/gyurmo/.ssh/config error:2 
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 192.168.0.12 is address
debug2: ssh_connect_direct
debug1: Connecting to 192.168.0.12 [192.168.0.12] port 2022.
 debug3: finish_connect - ERROR: async io completed with error: 10061, io:000001D271465780
 debug1: connect to address 192.168.0.12 port 2022: Connection refused 
ssh: connect to host 192.168.0.12 port 2022: Connection refused 
```

```
PS C:\Windows\system32> netsh interface portproxy show v4tov4                                                                                                                                                                                   Listen on ipv4:             Connect to ipv4:                                                                                                                                                                                                    Address         Port        Address         Port
--------------- ----------  --------------- ---------- 
192.168.0.12    2022        172.31.81.48    2022                                                                                                                               
```

**Comment by gyurmogyuri** [comment]
I'm sorry. I solved:
` netsh interface portproxy delete v4tov4 listenport=2022 listenaddress=192.168.0.12`
` netsh interface portproxy set v4tov4 listenport=2022 listenaddress=192.168.0.12 connectport=2022 connectaddress=127.0.0.1 ` 

Because I have:
[localhostforwarding=true](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file)

**Comment by lk-1984** [comment]
I have this same issue.
