### ISSUE TITLE
WSLg Fullscreen Frame doesnt align

### ISSUE THREAD

**Issue by Schokokex** [microsoft/WSL#6884]
# Reconstruction:

0. 2-Monitor Setup, resolution 1920x1080 and 1680x1050
1. Fresh installation of Windows Insider 21364.1011 with WSLg update and installation of Ubuntu/Debian.
2. apt install firefox
3. launch firefox from Windows Start Menu 
4. Press fullscreen button (without resizing window prior to that)

Tested it with Windows Taskbar on left and bottom

# Expected behaviour:

Window frame aligns to monitor without peeking into second monitor

# Actual behaviour:

Window content and scrollbar aligns to monitor 1, but top frame has <kbd>_</kbd> button on monitor 1, <kbd>O</kbd><kbd>X</kbd> are on monitor 2 including some transparent window and the thin border.

**Comment by therealkenc** [comment]
The WSLg issue tracker is [here](https://github.com/microsoft/wslg/issues).
