### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070057

### ISSUE THREAD

**Issue by mcrae-rzhang** [microsoft/WSL#6887]
### Windows Build Number

Microsoft Windows [Version 10.0.21370.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Repro Steps

install wsl distribution

### Expected Behavior

wsl distribution installed.

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

**Comment by arunse** [comment]
This is a duplicate of [WSL2 distro not starting since 21364 build ](https://github.com/microsoft/WSL/issues/6839)

**Comment by mcrae-rzhang** [comment]
Thanks arunse, this fixed the issue.
