### ISSUE TITLE
[Feature suggestion, smaller] Would it be possible for a short feedback as to whether "wsl --set-default-version 2" was a success?

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/WSL#6892]
Hey there to the WSL team,

I hope this includes WSL1 and WSL2. :)

I have been using WSL1 for ... perhaps 3 years by now, or something like that, on my laptop.

Anyway; WSL1 was really nice. There were a few minor things but these were minor so I
did not care much. I also could use "linux" GUIs e. g. both QT and GTK, vix xming/mingx or
whatever the name was for that xorg-server (I forgot).

Lately I read that WSL2 actually did a TON of GUI-related improvements. I already write a
lot of ruby-gtk3 code in particular but I also use other GUIs, so switching to WSL2 would
make sense. I initially wanted to delay this but today I decided to give it a try.

So far it's ok, but I noticed a minor thing.

I was using this here:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

And I was using this command:

"wsl --set-default-version 2"

I got this line:

"For information on key differences with MSL 2 please visit https://ak.ms/wsl2"

That message is ok, but would it be possible to also inform us that the --set-default-version
was a success or not? I assume it was a success but I don't know yet. So I don't know
whether I may be using wsl1 or wsl2. I assume wsl2 but it would be helpful if some 
message could be used when we use --set-default-version.

Something like:

"Success."

Or if you want more text, perhaps:

"WSL2 is now the default and will be used when starting ... "

Not sure how WSL2 works, so the above message has to be tweaked a bit. But that
is only a suggestion for many other possibilities.

Reasoning: I actually would like some confirmation that what I was doing so far was
successful. Right now I don't seem to get much indication, other than the "please
visit xyz", but I already work through a tutorial on docs-microsoft, so it is unlikely I
want to visit yet another random website. My mind set is to work through the whole
thing right now! :P So a bit of feedback would be useful. Thanks for reading, please
close as you see fit at any moment in time. The good thing is that it's a minor change
so only just an additional sentence perhaps.

**Comment by Biswa96** [comment]
Workaround: You can list the distributions with `wsl.exe -l -v` or `wsl.exe --list --verbose` which shows the WSL version.

**Comment by therealkenc** [comment]
> wsl.exe -l -v

That will show the distribution's WSL version (1 or 2). To get the default use `wsl.exe --status` on recent-ish WSL, I think circa 20246 (but don't quote me). For what it is worth, `--set-default-version` doesn't have much in the way of failure modes (if any at all). It just makes note of the default version. No news is good news (success is the absence of an error) is pretty standard behavior. [Contrast failure without an error, which is a bug.]

![image](https://user-images.githubusercontent.com/7049700/116934362-c093be80-ac19-11eb-8920-1fb24365717e.png)

**Comment by bpulliam** [comment]
This was added to Insiders in build 20237.  The text now reads:
c:\directory>wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.
