### ISSUE TITLE
0x800701bc

### ISSUE THREAD

**Issue by umbrella-k** [microsoft/WSL#6894]
### Windows Build Number

Microsoft Windows [Version 10.0.21370.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04 LTS

### Repro Steps

Start ubuntu. After the new insider release it doesn't work with following error.

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 ???????????? ??????????????????????? https://aka.ms/wsl2kernel ?????????

Press any key to continue...

### Expected Behavior

Doesn't work.

### Actual Behavior

Should work.

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/6409582/wsl.zip)

**Comment by onomatopellan** [comment]
Download this file and install it:
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by umbrella-k** [comment]
This display will appear
![image](https://user-images.githubusercontent.com/68675858/116800296-d2526480-ab3a-11eb-9d38-f0885aaddf44.png)
![image](https://user-images.githubusercontent.com/68675858/116800299-db433600-ab3a-11eb-8c6d-0b567d6d615e.png)

**Comment by onomatopellan** [comment]
First do right click on the downloaded `wsl_update_x64.msi` file and click on Uninstall. After that try installing it again.

**Comment by umbrella-k** [comment]
![image](https://user-images.githubusercontent.com/68675858/116811227-18cbb180-ab83-11eb-9720-0330a91cb357.png)
It's like this.
This is Japanese, but when translated into English,
This operation is valid only for currently installed products. It is written.

**Comment by onomatopellan** [comment]
Please take a look at https://github.com/microsoft/WSL/issues/5014. The entire thread is about people solving a similar issue by installing the kernel manually.

**Comment by umbrella-k** [comment]
Manually extract the kernel file and
It worked when I put it under% Windir% system32 \ lxss \ tools.
Thank you.
