### ISSUE TITLE
init: (147) ERROR: LogException:33: TELEMETRY

### ISSUE THREAD

**Issue by microhobby** [microsoft/WSL#6895]
### Windows Build Number

Microsoft Windows [Version 10.0.21364.1011]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.12

### Distro Version

Ubuntu Community Preview

### Repro Steps

Using normally, check the `dmesg -w`

### Expected Behavior

No `init` errors on Kernel logs

### Actual Behavior

```
[  201.810459] init: (147) ERROR: LogException:33: TELEMETRY: (null) No such file or directory @d:\os\src\onecore\VM\linux\mountutil\mountutilcpp.h:19 (MountEnum)

[  373.096594] init: (147) ERROR: LogException:33: TELEMETRY: (null) Invalid argument @d:\os\src\onecore\VM\linux\mountutil\mountutilcpp.h:19 (MountEnum)
```

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also, what is the output of `cat /proc/version`.

**Comment by OneBlue** [comment]
Thanks for reporting @microhobby.
Do you have a custom wsl.conf / fstab ?
