### ISSUE TITLE
WSL2 distro: I can't manage to update to Build 21370.

### ISSUE THREAD

**Issue by andalou** [microsoft/WSL#6897]
### Windows Build Number

Microsoft Windows [Version 10.0.21364.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Every time I try to update to Build 21370, I get:

Windows Update
Error encountered
Last checked: Today, 10:02 a.m.

There were some problems installing updates, but we'll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0xc1900101)

### Expected Behavior

I would expect to have the system updated to Build 21370. Before, I
updated my system to 21364 but wsl2 didn't work anymore, even after
putting this

[wsl2]
guiapplications=false

on %userprofile%\\.wslconfig

### Actual Behavior

Windows Update
Error encountered
Last checked: Today, 10:02 a.m.

There were some problems installing updates, but we'll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0xc1900101)

**Comment by onomatopellan** [comment]
What's your CPU and motherboard?

**Comment by therealkenc** [comment]
WSL does not manage windows updates. Quick search of community got these [hits](https://answers.microsoft.com/en-us/search/search?SearchTerm=0xc1900101&tab=&status=all&advFil=&IsSuggestedTerm=false&isFilterExpanded=undefined&CurrentScope.ForumName=&CurrentScope.Filter=&ContentTypeScope=QnA,Discussion,Article,MicrosoftSupport&page=1&sort=Relevance&dir=Desc).
