### ISSUE TITLE
prevelege is not enough to install wsl on server 2022

### ISSUE THREAD

**Issue by avboy1337** [microsoft/WSL#6898]
### Windows Build Number

10.0.20344.1

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Ubuntu-20.04

### Distro Version

Ubuntu-20.04

### Repro Steps

powershell Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart
powershell Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform -NoRestart
wsl --list --online
wsl --install -d Ubuntu-20.04

### Expected Behavior

install wsl as we need

### Actual Behavior

not enouth prevelege to install 
going to double click the installer of ubuntu20 , it notified that this dir need system prevelege.

**Comment by therealkenc** [comment]
From an Admin Powershell, please screencap the first command, as a starting point. 

```
PS C:\> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

Looks something like this before pressing enter:

![image](https://user-images.githubusercontent.com/7049700/116946469-0b6c0100-ac2f-11eb-95f0-1ed108a6b46a.png)

**Comment by avboy1337** [comment]
you are so quick and thanks for your patient , i'm going to try it .
