### ISSUE TITLE
Maximized window position

### ISSUE THREAD

**Issue by kopilkus** [microsoft/WSL#6899]
### Windows Build Number

Microsoft Windows [Version 10.0.21370.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Use two monitors. Move windows task panel to left. Maximize window of wsl gui application.

### Expected Behavior

Fit window to monitor.

### Actual Behavior

![image](https://user-images.githubusercontent.com/78064620/116817532-5f2c0b00-ab99-11eb-9dd0-b9341bd9361e.png)
Part of border of wsl application window goes to right monitor.

**Comment by onomatopellan** [comment]
For GUI issues the place is
https://github.com/microsoft/wslg/issues
