### ISSUE TITLE
Changes to System Distribution don't persist between launches 

### ISSUE THREAD

**Issue by artman41** [microsoft/WSL#6901]
### Windows Build Number

Microsoft Windows [Version 10.0.21370.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

CBL-Mariner 1.0.20210224

### Repro Steps

1. Enter System distro `wsl --system`
2. Install an application / create a file in `/etc/`
3. Exit distro
4. Shutdown wsl `wsl --shutdown`
5. Re-enter System distro `wsl --system`

### Expected Behavior

Applications, Files & Changes should be persisted between launches.

### Actual Behavior

No changes can be made to the System Distribution

**Comment by github348** [comment]
from wslg readme

> While a user can get a terminal into the system distro, the system distro is not meant to be used directly by users. Every instance of the system distro is loaded read-only from it's backing VHD. Any modifications, made to the in-memory instance of the system distro (such as installing new packages or creating a new file), is effectively discarded when WSL is restarted. The reason we do this is to enable a servicing model for the system distro where we replace the old one with the new one without having to worry about migrating any user data contained within. We use a read-only mapping such that the user gets a well known discard behavior on any changes, every time WSL is restarted, instead of getting a surprise when WSL is serviced.

**Comment by artman41** [comment]
> from wslg readme
> 
> > While a user can get a terminal into the system distro, the system distro is not meant to be used directly by users. Every instance of the system distro is loaded read-only from it's backing VHD. Any modifications, made to the in-memory instance of the system distro (such as installing new packages or creating a new file), is effectively discarded when WSL is restarted. The reason we do this is to enable a servicing model for the system distro where we replace the old one with the new one without having to worry about migrating any user data contained within. We use a read-only mapping such that the user gets a well known discard behavior on any changes, every time WSL is restarted, instead of getting a surprise when WSL is serviced.

Well that's sad - for those who want to modify the System Distro, it looks like you'll need to make your own https://github.com/microsoft/wslg/blob/main/CONTRIBUTING.md#build-instructions
