### ISSUE TITLE
McAfee support

### ISSUE THREAD

**Issue by mvanwaveren** [microsoft/WSL#6906]
**Is your feature request related to a problem? Please describe.**
Cybersecurity in my enterprise wants to be able to add an anti-virus in the WSL Linux instance.

**Describe the solution you'd like**
I read on page:
https://github.com/MicrosoftDocs/WSL/blob/a34db960f821149833c4f75276ba76f6dac46d29/WSL/enterprise.md
that McAfee support is on your backlog. Do you have any idea when it would be available?

**Describe alternatives you've considered**
Are there alternative solutions?

**Comment by craigloewen-msft** [comment]
McAfee can now support direct integration with WSL by creating a plugin!

https://learn.microsoft.com/en-us/windows/wsl/wsl-plugins
