### ISSUE TITLE
wsl --install -d Ubuntu : Fails  WslRegisterDistribution failed with error: 0x8037011e

### ISSUE THREAD

**Issue by noeldiviney** [microsoft/WSL#6907]
Unable to submit "BUG" issue because The Distro "Ubuntu" failed to install,therefore, not able to execute 
"sudo apt-get install traceroute && traceroute www.microsoft.com" 
[DxDiag.txt](https://github.com/microsoft/WSL/files/6421225/DxDiag.txt)
[eicon.zip](https://github.com/microsoft/WSL/files/6421226/eicon.zip)
![Ubuntu-install-failure](https://user-images.githubusercontent.com/3682585/117007712-4f453000-ad2d-11eb-9b35-8be91b572ed7.PNG)
![wsl--install](https://user-images.githubusercontent.com/3682585/117007723-52d8b700-ad2d-11eb-9cf2-0374f9f5c7f7.PNG)

**Comment by ShemSargent-ITCWA** [comment]
I just switched to Dev ring (21382.co_release.210511-1416) to test WSL GUI App Support. I'm getting the same error as OP's first image.

I had VMP and WSL installed before the upgrade to Dev ring, so to troubleshoot, I removed VMP and WSL, rebooted and ran WSL --install. I got the same output as OP's second image. I rebooted and the system launched the WSL window and I got the same error as OP's first image again.

Also getting the same error when installing distro through Microsoft Store and when installing other distros besides Ubuntu.

**Comment by OneBlue** [comment]
Thanks for reporting this @noeldiviney.

The error code maps to `The host compute system service has disconnected unexpectedly. `, so it looks like HCS isn't behaving correctly on your machine.

Does disabling and enabling the 'Virtual machine platform' Windows feature help ? 
Also, does your machine have virtualization support ?

**Comment by noeldiviney** [comment]
W:\bin>Coreinfo.exe -v

Hello @OneBlue
I have been running WSL 2 Ubuntu successfully before upgrading to Insider Dev Channel
So My PC is capable of installing and launching WSL 2 and the Ubuntu Distro.
Also note above report from @ShemSargent-ITCWA showing similar results

The Virtualization Test results from "CoreInfo.exe -v "     is shown below 

Coreinfo v3.31 - Dump information on system CPU and memory topology
Copyright (C) 2008-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

Note: Coreinfo must be executed on a system without a hypervisor running for
accurate results.

Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
Microcode signature: 0000001F
HYPERVISOR      *       Hypervisor is present
VMX                  -       Supports Intel hardware-assisted virtualization
EPT                    -       Supports Intel extended page tables (SLAT)

Best regards NoelDiviney

**Comment by noeldiviney** [comment]
Upgraded to Build 21382.co_release.210511_1416.
Still fails to Launch as follows 👎 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8037011e
Error: 0x8037011e The host compute system service has disconnected unexpectedly.

Press any key to continue...

NoelDiviney

**Comment by ShemSargent-ITCWA** [comment]
Similar coreinfo results on my end:

Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Intel64 Family 6 Model 63 Stepping 0, GenuineIntel
Microcode signature: 00000043
HYPERVISOR      *       Hypervisor is present
VMX             -       Supports Intel hardware-assisted virtualization
EPT             -       Supports Intel extended page tables (SLAT)
URG             -       Supports Intel unrestricted guest

**Comment by ShemSargent-ITCWA** [comment]
Ubuntu first run logs this message in `Microsoft-Windows-Hyper-V-Compute-Operational`: `Create compute system, result 0xC0370103`

I see the same error in #6361, but in a different context. The error appears to be related to nested virtualization. The virtual machine in question does have nested virtualization enabled on the host and the nested virtualization worked with WSL2 as expected on the same VM with the current Insiders Release Preview Channel flight before I updated to Dev channel.

**Comment by OneBlue** [comment]
Thanks for the update @noeldiviney.

Let's looks at the hyper-V logs, there might be something useful in there.

Can you please follow the ['Records WSL logs manually' section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) and share the output ?

**Comment by noeldiviney** [comment]
@OneBlue 
Thank you for your help so far.
I have now upgraded to build 21387.co ans the results are the same.
[WSL.zip](https://github.com/microsoft/WSL/files/6527371/WSL.zip)

After upgrading I then did a clean install by first uninstalling ie turning off "Virtual Machine Platform" and "Windows Subsystem for Linux"
Uploading (and also Pasting) WSL.zip which contains the the various files for your perusal.

Best regards
Noel Diviney

**Comment by OneBlue** [comment]
Thank @noeldiviney.

Based on the output, it looks like vmcompute is crashing.

Could you please follow the ['Collect WSL logs' section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and share the feedback hub URL ? 

That should allow us to capture the crash and investigate it.

**Comment by noeldiviney** [comment]
@OneBlue
![ubuntu-install 05-23-21 at 10 26 AM](https://user-images.githubusercontent.com/3682585/119806914-fdf02100-bf25-11eb-95a4-7163bdcc3b82.gif)
![wsl-install 05-23-21 at 10 17 AM](https://user-images.githubusercontent.com/3682585/119807001-0fd1c400-bf26-11eb-90c3-2b30d2f20ddf.gif)
[wsl-install-23052021.etl.txt](https://github.com/microsoft/WSL/files/6553032/wsl-install-23052021.etl.txt)
[wsl-ubuntu-install-23052021.etl.txt](https://github.com/microsoft/WSL/files/6553034/wsl-ubuntu-install-23052021.etl.txt)

I had already uploaded the above files as WSL.zip see previous comment, as .etl is not being accepted.
You will need to rename the last two files by removing the .txt extension
Will upgrade the next update and have another try.
Hope this helps 

Noel Diviney

**Comment by OneBlue** [comment]
@noeldiviney: Unfortunately the .etl files aren't enough. What's probably happening is that the HostComputeService is crashing (which causes the error you're seeing).

To diagnose that, you'd need to [Collect logs with feedback hub](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs). That should capture the crash dump so we can look at what happened there.

**Comment by noeldiviney** [comment]
WSL install has been working successfully for a week now so my issue has been fixed with the 21390.co update.
I am now closing this issue.

Thanks and Best regards Noel Diviney
