### ISSUE TITLE
RUSAGE_THREAD not implemented

### ISSUE THREAD

**Issue by EagleErwin** [Microsoft/WSL#691]
According to the manpage, `getrusage(2)` supports `RUSAGE_THREAD` since Linux 2.6.26. WSL reports to be Linux 3.4.0 (`uname -a`).

However, when I try to run this minimal working example ...

``` c
#define _GNU_SOURCE
#include <sys/resource.h>
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <string.h>
#include <errno.h>

struct tinfo {
  pthread_t thread;
  struct rusage result;
};

static void * thread_start(void *arg)
{
  struct tinfo *inf = arg;
  if (getrusage(RUSAGE_THREAD, &inf->result) < 0) {
    printf("getrusage failed: %s\n", strerror(errno));
    abort();
  };
  return 0;
}

int main() {
  struct tinfo status;
  const int s = pthread_create(&status.thread, NULL, &thread_start, &status);
  const int t = pthread_join(status.thread, NULL);
  printf("Thread done: %ld maximum resident set size.\n", status.result.ru_maxrss);
  return 0;
}
```

... after building it with `gcc main.c -lpthread -o main`, it outputs:

```
getrusage failed: Invalid argument
Aborted (core dumped)
```

When running on a native Linux machine (kernel 2.6.32), it outputs:

```
Thread done: 704 maximum resident set size.
```

When `RUSAGE_SELF` is used instead of `RUSAGE_THREAD`, the program executes correctly.

Is this a bug, or is `RUSAGE_THREAD` not (yet) implemented? And if the latter: is there any chance that it will be implemented in the near future?

I'm running build 14393.5 of Windows 10.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, I confirmed  RUSAGE_THREAD is not currently supported by WSL.  We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well.

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by EagleErwin** [comment]
I tried to reproduce this issue on build 16299.248(Fall Creators Update) of Windows 10, and RUSAGE_THREAD seems to be supported now.

**Comment by therealkenc** [comment]
Wonder when.
