### ISSUE TITLE
wslhost.exe stops listening for opened ports after a while

### ISSUE THREAD

**Issue by alex-pravdin-sn** [microsoft/WSL#6918]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.104

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 3.3.1 (63152) WSL2 backend, engine 10.10.5
PHPStorm

### Repro Steps

1. Run PHPStorm under WSL and an X server on Windows host. PHPStorm is listening for incoming XDebug connections on port 9000.
2. Run PHP with XDebug in a Docker container.
3. Configure XDebug to connect to the `host.docker.internal` host.
4. Perform a number of debug sessions.

### Expected Behavior

It works well forever.

### Actual Behavior

After some number of requests, debugging stops working. The issue is that the `wslhost.exe` process stops listening for ports opened in WSL2. So XDebug that is connecting to the `host.docker.internal` host can't connect to the port that should be opened on the Windows host.

After running `wsl --shutdown` it works for a while:

```
$ sudo netstat -ntlp
[sudo] password for alex:
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:20080           0.0.0.0:*               LISTEN      431/java
tcp        0      0 0.0.0.0:10137           0.0.0.0:*               LISTEN      431/java
tcp        0      0 127.0.0.1:6942          0.0.0.0:*               LISTEN      431/java
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      431/java
tcp        0      0 0.0.0.0:9003            0.0.0.0:*               LISTEN      431/java
tcp        0      0 127.0.0.1:63342         0.0.0.0:*               LISTEN      431/java
```

You may see the `9000` and `9003` XDebug ports opened. The same on the Windows host:

![image](https://user-images.githubusercontent.com/61450549/117250151-bf62cb80-ae7d-11eb-88b9-fd0cd217200e.png)

After a while, the `wslhost.exe` process stops listening for any ports.

How to fix that?

**Comment by OneBlue** [comment]
Thanks for reporting this @alex-pravdin-sn.

Could you [capture logs (see 'Record WSL logs manually')](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) before starting the relay and until the relay disappears so that we can have a closer look ?

**Comment by alex-pravdin-sn** [comment]
@OneBlue When I'm trying to run the command mentioned by your link, I'm getting an error:

```
wpr -start wsl.wprp -filemode

        Error code: 0xc00cee4f
```

**Comment by OneBlue** [comment]
This looks like a parsing error.
 Can you check that the content of [wsl.wprp](https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/wsl.wprp) isn't corrupted ?

**Comment by alex-pravdin-sn** [comment]
@OneBlue You're right, an HTML page was downloaded instead of the file... Downloaded the correct version and it works well. Will try to capture the issue, thanks.

**Comment by speller** [comment]
@OneBlue I just caught this issue when the logging was turned on and I've submitted a ticket with the log: https://aka.ms/AAdx082. It took a long time so the log may contain a lot of useless data, but somewhere close to the end the `wlshost.exe` process stopped listening for 9000 and 9003 ports while they were still opened inside WSL.
