### ISSUE TITLE
SSH Timeout with VPN 

### ISSUE THREAD

**Issue by Anasme** [microsoft/WSL#6919]
### Windows Build Number

Microsoft Windows [version 10.0.19043.962]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Debian 10

### Other Software

OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d

VPN SonicWall NetExtender (windows client) 10.2.30

### Repro Steps

The connections have random timeouts when we go through WSL2 via our VPN to access our remote servers.

When a timeout occurs, we restart the "hns" service which sometimes allows the ssh to work again.

This does not always work, the ultimate solution is to restart the client, which is quite painful.

The term random is vague I admit, I noticed that it often happens in standby mode, and requires a reboot of the PC.

I can provide you with more information and log if you give me the procedures to play, thank you in advance.

### Expected Behavior

SSH should connect to server

### Actual Behavior

SSH timeout, need to reboot network service or computer.

### Diagnostic Logs

λ   dev ✗ ssh -vv -T git@censored
OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019
debug1: Reading configuration data /home/censored/.ssh/config
debug1: /home/censored/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "censored" port 22
debug2: ssh_connect_direct
debug1: Connecting to censored [ip_censored] port 22.
debug1: connect to address ip_censored port 22: Connection timed out
ssh: connect to host censored port 22: Connection timed out

**Comment by gradinarot** [comment]
Did you mange to resolve this?

**Comment by Anasme** [comment]
Hello, not yet, do you have any ideas?

**Comment by gradinarot** [comment]
https://github.com/sakai135/wsl-vpnkit

**Comment by andyneff** [comment]
@AmmarRahman was kind enough to wrap some of this up into a set of scripts to automatically set up wsl-vpnkit here: https://github.com/AmmarRahman/wsl-vpn

**Comment by Anasme** [comment]
Thanks for your answers, the vpn toolkit solution seems to work as a workaround.

Waiting for a more permanent solution specific to wsl.

Have a nice day!
