### ISSUE TITLE
Unable to start Ubuntu 20.04 under WSL2

### ISSUE THREAD

**Issue by aviraldg** [microsoft/WSL#6922]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

N/A

### Repro Steps

Start Ubuntu 20.04 under WSL2.

### Expected Behavior

Ubuntu should start.

### Actual Behavior

The following error is logged out:

> There was an operation attempted on a degraded object.
> 
> [process exited with code 4294967295]

### Diagnostic Logs

https://aka.ms/AAcfjzc

**Comment by aviraldg** [comment]
Started working again after a reboot.

**Comment by benhillis** [comment]
@aviraldg - it does not look like you included repro logs in your feedback hub issue.  If you are able to hit this again, please open a new issue.
