### ISSUE TITLE
Incorrect distribution version fetched by WslGetDistributionConfiguration

### ISSUE THREAD

**Issue by segrey** [microsoft/WSL#6924]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.964]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

### Distro Version

Ubuntu-18.04

### Repro Steps

1. Configure a WSL distribution with version 1
```
> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Stopped         2
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu-18.04           Running         1
```
2. Use [WslGetDistributionConfiguration](https://docs.microsoft.com/en-us/windows/win32/api/wslapi/nf-wslapi-wslgetdistributionconfiguration) API function to retrieve distribution version. See C++ code below:
```cpp
#include <iostream>
#include <windows.h>
#include <wslapi.h>

typedef HRESULT(STDAPICALLTYPE* WSL_GET_DISTRIBUTION_CONFIGURATION)(PCWSTR, ULONG*, ULONG*, WSL_DISTRIBUTION_FLAGS*, PSTR**, ULONG*);

WSL_GET_DISTRIBUTION_CONFIGURATION _WslGetDistributionConfiguration;

void printVersion(PCWSTR distributionName) {
  ULONG distributionVersion, defaultUID, defaultEnvironmentVariableCount;
  WSL_DISTRIBUTION_FLAGS wslDistributionFlags;
  PSTR *defaultEnvironmentVariables;

  HRESULT hr = _WslGetDistributionConfiguration(
      distributionName,
      &distributionVersion,
      &defaultUID,
      &wslDistributionFlags,
      &defaultEnvironmentVariables,
      &defaultEnvironmentVariableCount);
  if (FAILED(hr)) {
    printf("%ls: WslGetDistributionConfiguration failed\n", distributionName);
  } else {
    printf("%ls: version %ld\n", distributionName, distributionVersion);
  }
}

int main() {
  HMODULE dll = LoadLibraryEx(L"wslapi.dll", NULL, LOAD_LIBRARY_SEARCH_SYSTEM32);
  if (dll == nullptr) {
    printf("wslapi.dll not found\n");
    return 1;
  }
  _WslGetDistributionConfiguration = (WSL_GET_DISTRIBUTION_CONFIGURATION)GetProcAddress(dll, "WslGetDistributionConfiguration");
  if (_WslGetDistributionConfiguration == nullptr) {
    printf("WslGetDistributionConfiguration not found\n");
    return 1;
  }
  printVersion(L"Ubuntu-18.04");
  printVersion(L"Ubuntu-20.04");
}
```
3. Running it produces the following output:
```
Ubuntu-18.04: version 2
Ubuntu-20.04: version 2
```

### Expected Behavior

Expected output of running the C++ code:
```
Ubuntu-18.04: version 1
Ubuntu-20.04: version 2
```

### Actual Behavior

`WslGetDistributionConfiguration` sets `distributionVersion` to 2 for Ubuntu-18.04. However, according to `wsl.exe -l -v`, its version is 1.

**Comment by segrey** [comment]
WSL logs in Feedback Hub: https://aka.ms/AAcgewu

**Comment by 0xbadfca11** [comment]
Its argument does not indicate whether it is WSL2 because it was used for something else in the days when WSL2 was not there. https://github.com/microsoft/WSL/issues/5578

**Comment by Biswa96** [comment]
AFAIK, that version paramter gives the verison of virtual file system i.e lxfs (1) and wslfs (2), remember those days with NTFS Extended Attributes? It's not related with ext4 in WSL2 VHDX. Whereas the WSL1/2 can be known from Flags in the registry i.e. WSL1 (0x7) and WSL2 (0xF). But it's _strictly prohibited_.

**Comment by segrey** [comment]
Thanks for the answers! Looks like the documentation for `distributionVersion` parameter of [WslGetDistributionConfiguration](https://docs.microsoft.com/en-us/windows/win32/api/wslapi/nf-wslapi-wslgetdistributionconfiguration) should be updated.
Would be great to extend wslapi.h with ability to fetch distribution version - WSL1/2.
