### ISSUE TITLE
Enable React Native development

### ISSUE THREAD

**Issue by davisjr** [microsoft/WSL#6929]
**Is your feature request related to a problem? Please describe.**
Setting up WSL for React Native development is quite painful currently. I was able to install adb and emulator using the command line tools that Google provides but apparently they don't work from inside WSL. Trying to start the emulator fails with `ProbeKVM: This user doesn't have permissions to use KVM (/dev/kvm)` although the user has access. Looks like we need to use a mix of Windows and WSL tools to make it work from what I could figure after searching around on the web. Since many RN developers have a React background and most of the toolchain might be already configured in WSL, would be great if we don't have to replicate the setup in Windows.

**Describe the solution you'd like**
I would like to see adb and emulator running from within WSL, similar to how it would happen on Mac/Linux. Hopefully I can just do `react-native run-android` or `npm run android` and it should bring up the app on the emulator and connect to the instance.

**Describe alternatives you've considered**
I am following these guides to set things up - which uses adb server and emulator on Windows and configures WSL to connect to it:
https://gist.github.com/bergmannjg/461958db03c6ae41a66d264ae6504ade
https://medium.com/@pellea/using-the-android-emulator-on-windows-10-with-wsl2-39c2bae30c49
https://medium.com/@pellea/using-adb-with-wsl2-7aebbb070a47

**Additional context**
While many RN devs would be using Macs as it's required for iOS development/testing, given the focus on "RN for Windows" and that Android testing is still possible, would be great if developers on our platform could try this out easily. Since many of the React Native developers are likely to have a React background, for which WSL works great, WSL might be the first place they look to in order to do this.

**Comment by benhillis** [comment]
What version of Windows are you running? Insider Dev has had nested virtualization (required for KVM) enabled by default for some time.

**Comment by davisjr** [comment]
Tried to debug this a little bit and was able to make some progress. Looks like the emulator is failing to startup because of incorrect permissions on /dev/kvm. From the above error message, group should be `kvm` and not `root`

```
crwxrwxr-x 1 root root 10, 232 Jun 13 12:58 /dev/kvm
```

Changing the group and granting permissions helps fire up the emulator, at the least. 

```
sudo chgrp kvm /dev/kvm
sudo chmod g+rw /dev/kvm
```

However, the group and permissions seems to get auto-reverted on restart.

**Comment by craigloewen-msft** [comment]
Likely solved with WSL 2, please reopen if you find issues running this workflow in the latest builds.
