### ISSUE TITLE
Syncing files in git folder using rsync sometimes results in Permission denied error

### ISSUE THREAD

**Issue by Zythyr** [microsoft/WSL#6932]
### Windows Build Number

Microsoft Windows 10 20H2 OS Build 19042.964

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

rsync  version 3.1.3  protocol version 31

### Repro Steps

I use _rsync_ via _WSL_ on Windows 10 to backup files to an external drive. Sometimes I get _Permission denied (13)_ error when _rsync_ is trying to transfer files. I have noticed, a consistent pattern where this occurs when transferring files that may be located in a _.git_ folder of a project. 

In order to duplicate this issue, isolated one of the files that had  _Permission denied (13)_ error. This file originally belonged in a _.git_ folder of a project.  In the commands below, I am using rsync to update the file in a _destination/_ folder which contains an older version of the file. The _source/new_file/_ contains the newer version. To duplicate the issue, I have uploaded the files used in the commands below [rsync-issue.zip](https://github.com/microsoft/WSL/files/6456112/rsync-issue.zip) 

```console
myusername@myhostname:/mnt/c/rsync-issue$ lsb_release -d
Description:    Ubuntu 20.04.2 LTS
myusername@myhostname:/mnt/c/rsync-issue$ wsl.exe -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
myusername@myhostname:/mnt/c/rsync-issue$ ls -la
total 0
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 .
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 ..
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 destination
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 source
myusername@myhostname:/mnt/c/rsync-issue$ ls -la destination/
total 4
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 .
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 ..
-r-xr-xr-x 1 myusername myusername 2242 Sep 16  2020 de9b716532d903d29b86db2410da9c249b9841
myusername@myhostname:/mnt/c/rsync-issue$ ls -la source/new_file/
total 4
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 .
drwxrwxrwx 1 myusername myusername 4096 May 10 21:51 ..
-r-xr-xr-x 1 myusername myusername 2242 Oct  2  2020 de9b716532d903d29b86db2410da9c249b9841
myusername@myhostname:/mnt/c/rsync-issue$ rsync -avhP source/new_file/ destination/
sending incremental file list
de9b716532d903d29b86db2410da9c249b9841
          2.24K 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/2)
rsync: rename "/mnt/c/rsync-issue/destination/.de9b716532d903d29b86db2410da9c249b9841.8Jyo5m" -> "de9b716532d903d29b86db2410da9c249b9841": Permission denied (13)

sent 2.39K bytes  received 201 bytes  5.19K bytes/sec
total size is 2.24K  speedup is 0.86
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

### Expected Behavior

n/a

### Actual Behavior

n/a

**Comment by Zythyr** [comment]
> 
> 
> > Sometimes I get Permission denied (13)
> 
> Fiver says #1529. Make sure nothing is breathing on any of those files in Windows.
> 
> If you can catch the error with an `strace -f -o rsync.strace rsync -avhP source/new_file/ destination/` that would be golden, but unfortunately there is a good chance it will go away under `strace(1)`. Worth a try if "sometimes" happens often enough. Run `grep EACCES rsync.strace` to filter just the fails.
> 
> Couldn't repro here unfortunately.


I tested your suggestion and below is the output. I have few other files that similar issue. Would it helpful if I provided the files? 

**Contents of rsync.strace file:** https://pastebin.ubuntu.com/p/pVmFpHcGR5/ 

```console
myusername@myhostname:/mnt/c/rsync-issue$ rsync -avhP source/new_file/ destination/
sending incremental file list
de9b716532d903d29b86db2410da9c249b9841
          2.24K 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/2)
rsync: rename "/mnt/c/rsync-issue/destination/.de9b716532d903d29b86db2410da9c249b9841.SfKit4" -> "de9b716532d903d29b86db2410da9c249b9841": Permission denied (13)

sent 2.39K bytes  received 201 bytes  5.19K bytes/sec
total size is 2.24K  speedup is 0.86
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
myusername@myhostname:/mnt/c/rsync-issue$ strace -f -o rsync.strace rsync -avhP source/new_file/ destination/
sending incremental file list
de9b716532d903d29b86db2410da9c249b9841
          2.24K 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/2)
rsync: rename "/mnt/c/rsync-issue/destination/.de9b716532d903d29b86db2410da9c249b9841.0v6p5x" -> "de9b716532d903d29b86db2410da9c249b9841": Permission denied (13)

sent 2.39K bytes  received 201 bytes  5.19K bytes/sec
total size is 2.24K  speedup is 0.86
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
myusername@myhostname:/mnt/c/rsync-issue$ grep EACCES rsync.strace
31    rename(".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", "de9b716532d903d29b86db2410da9c249b9841") = -1 EACCES (Permission denied)
myusername@myhostname:/mnt/c/rsync-issue$
```

**Comment by therealkenc** [comment]
> Would it helpful if I provided the files?

No the contents of the files won't matter. Thanks for the `strace(1)` logs, they are very helpful. One other data point: do you have metadata enabled? Looks like:

![image](https://user-images.githubusercontent.com/7049700/117913172-b87cf400-b295-11eb-9e87-d6583899b92e.png)

**Comment by Zythyr** [comment]
> 
> 
> > Would it helpful if I provided the files?
> 
> No the contents of the files won't matter. Thanks for the `strace(1)` logs, they are very helpful. One other data point: do you have metadata enabled? Looks like:
> 

Glad the strace was helpful. I am not really sure what you mean by metadata enabled. I don't have a wsl.conf file. See below. 

```console
myusername@myhostname:~$ cat /etc/wsl.conf
cat: /etc/wsl.conf: No such file or directory
```

**Comment by therealkenc** [comment]
Metadata is *nix file permissions etc. Documentation [here](https://docs.microsoft.com/en-us/windows/wsl/file-permissions) and [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options). There is a [`chmod(2)`](https://man7.org/linux/man-pages/man2/chmod.2.html) and just before the fail on [`rename(2)`](https://man7.org/linux/man-pages/man2/rename.2.html). That `chmod` behaves different depending on whether metadata is enabled.

```
29    openat(AT_FDCWD, "de9b716532d903d29b86db2410da9c249b9841", O_RDONLY) = 3
29    fstat(3, {st_mode=S_IFREG|0555, st_size=2242, ...}) = 0
29    write(1, "de9b716532d903d29b86db2410da9c24"..., 39) = 39
29    read(3, "x\1\325Z\335o\3336\20\337\263\377\n\302\3050eH\205\304\216\3236C\37\222tM\2135]R"..., 2242) = 2242
29    getpgrp()                         = 26
29    ioctl(1, TIOCGPGRP, [26])         = 0
29    write(1, "\r          2.24K 100%    0.00kB/"..., 46) = 46
29    write(1, "\r          2.24K 100%    0.00kB/"..., 65) = 65
29    close(3)                          = 0
29    select(6, [5], [4], [5], {tv_sec=60, tv_usec=0}) = 1 (out [4], left {tv_sec=59, tv_usec=999998})
29    write(4, "\355\10\0\7\3\10\200\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\302\10\0\0x\1\325Z\335"..., 2289) = 2289
31    <... select resumed>)             = 1 (in [0], left {tv_sec=59, tv_usec=991112})
29    select(6, [5], [], [5], {tv_sec=60, tv_usec=0} <unfinished ...>
31    read(0, "\355\10\0\7\3\10\200\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\302\10\0\0x\1\325Z\335"..., 32768) = 2289
31    openat(AT_FDCWD, "de9b716532d903d29b86db2410da9c249b9841", O_RDONLY) = 1
31    fstat(1, {st_mode=S_IFREG|0555, st_size=2242, ...}) = 0
31    getpid()                          = 31
31    openat(AT_FDCWD, ".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
31    fchmod(3, 0700)                   = 0
31    mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcf15240000
31    write(3, "x\1\325Z\335o\3336\20\337\263\377\n\302\3050eH\205\304\216\3236C\37\222tM\2135]R"..., 2242) = 2242
31    close(1)                          = 0
31    close(3)                          = 0
31    lstat(".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", {st_mode=S_IFREG|0777, st_size=2242, ...}) = 0
31    utimensat(AT_FDCWD, ".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", [UTIME_NOW, {tv_sec=1601624042, tv_nsec=0} /* 2020-10-02T03:34:02-0400 */], AT_SYMLINK_NOFOLLOW) = 0
31    chmod(".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", 0555) = 0
31    rename(".de9b716532d903d29b86db2410da9c249b9841.0v6p5x", "de9b716532d903d29b86db2410da9c249b9841") = -1 EACCES (Permission denied)
31    unlink(".de9b716532d903d29b86db2410da9c249b9841.0v6p5x") = 0
```

**Comment by Zythyr** [comment]
> 
> 
> Metadata is *nix file permissions etc. Documentation [here](https://docs.microsoft.com/en-us/windows/wsl/file-permissions) and [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options). There is a [`chmod(2)`](https://man7.org/linux/man-pages/man2/chmod.2.html) and just before the fail on [`rename(2)`](https://man7.org/linux/man-pages/man2/rename.2.html). That `chmod` behaves different depending on whether metadata is enabled.
> 
Thanks for the insight. I did not have any custom configurations in my WSL. Thus I am guessing I don't have a /etc/wsl.conf. I have done a fresh uninstall and reinstall to WSL prior to posting the issue. 

Is there anything else that is needed on my end to troubleshoot?

**Comment by therealkenc** [comment]
> Is there anything else that is needed on my end to troubleshoot?
 
No not really; thank-you again for the logfiles. On a lark you can try enabling metadata by creating `/etc/wsl.conf` with the contents in the screencap and a `wsl.exe --shutdown` for the change to take, just to see if it will make a difference. I did try the opposite and disabled metadata in the hopes it would reproduce, but also no such luck. The reason I brought it up at all is that trying to preserve *nix file permissions (as `rsync` does) on a filesystem without *nix file permissions is at best fraught. But either way the `rename(2)` `EACCES` is "wrong", cause unknown.

![image](https://user-images.githubusercontent.com/7049700/118069707-7c12cc00-b359-11eb-9dea-27b5b87bd75f.png)

**Comment by Zythyr** [comment]
> 
> 
> > Is there anything else that is needed on my end to troubleshoot?
> 
> No not really; thank-you again for the logfiles. On a lark you can try enabling metadata by creating `/etc/wsl.conf` with the contents in the screencap and a `wsl.exe --shutdown` for the change to take, just to see if it will make a difference. I did try the opposite and disabled metadata in the hopes it would reproduce, but also no such luck. The reason I brought it up at all is that trying to preserve *nix file permissions (as `rsync` does) on a filesystem without *nix file permissions is at best fraught. But either way the `rename(2)` `EACCES` is "wrong", cause unknown.
> 

I tried with `/etc/wsl.conf` file with the metadata option as you suggested. I am still getting the same issue. Also just to let you know, I confirmed this issue on two separate PCs with Windows 10 and wsl v2. In both PCs, wsl was fully uninstalled and reinstalled prior to testing. I also made sure to download the uploaded test files and not use the original test files that already had issues when discovered.
