### ISSUE TITLE
Windows Subsystem for Linux update setup wizard ended prematurely 

### ISSUE THREAD

**Issue by hatfact** [microsoft/WSL#6934]
### Windows Build Number

Microsoft windows version 10.0.19042.928

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Other Software

  Docker version 20.10.6, build 370c289
visual studio code - 1.55.2

### Repro Steps

install the docker Desktop and try to install wsl2 by downloading it .

### Expected Behavior

Docker should able to run Linux containers

### Actual Behavior

I have installed docker VScode now i need my cloud windows VM to run docker container on windows(10) environment. But while switching to Linux container I am getting error while installing WSL2. If we download the WSL2 from <https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi> and this is getting downloaded but while installing I am getting the error windows subsystem for Linux update setup wizard ended prematurely.
I have enabled these features
Microsoft-Windows-Subsystem-Linux
VirtualMachinePlatform
And also I have verified the C:\Windows\System32\lxss\tools kernel file in this folder.

Please give a solution for this issue

**Comment by ghc-laile** [comment]
me too

**Comment by craigloewen-msft** [comment]
Please install the latest WSL version and retry this scenario. Thank you for the feedback!
