### ISSUE TITLE
Manually installed distro - Unregister distro leaves traces on filesystem

### ISSUE THREAD

**Issue by marbaa** [microsoft/WSL#6944]
### Windows Build Number

Microsoft Windows [Version 10.0.18363.1500]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Repro Steps

1. Download any distro from [Docs page](https://docs.microsoft.com/en-us/windows/wsl/install-manual) - in my case Kali-linux
2. Install it by executing .appx file
3. List installed distros
```
PS T:\> wslconfig.exe /l
Windows Subsystem for Linux Distributions:
Debian (Default)
kali-linux
````
4. Unregister distro
```
PS T:\> wslconfig.exe /u kali-linux
Unregistering...
PS T:\> wslconfig.exe /l
Windows Subsystem for Linux Distributions:
Debian (Default)
PS T:\>
```

### Expected Behavior

According documentation `wsl --unregister <distro>` or `wslconfig /u <distro>` will delete whole distro. I'm expecting that there will be no traces for kali-linux after unregistering.

### Actual Behavior

After unregistering distro, I can see empty files and folders of unregistered distro - in my case kali-linux
![image](https://user-images.githubusercontent.com/40859847/118266769-5ac9f100-b4bb-11eb-95ec-f76b2ee41ccb.png)
I can still se kali-linux in Start menu, which will start installing distro again. There is no uninstall button on right click menu, under Settings -> Apps & features Uninstall button is grayed.
I don't see any way how to properly delete that **manually installed** distro, only by manually searching for files on filesystem, and hoping that there are no more places where some files could be (%APPDATA%, Program Files, etc).

**Comment by benhillis** [comment]
Unregistering a distro does not uninstall the associated app, it only deletes the Linux filesystem.
