### ISSUE TITLE
Wrong path resolution for windows drive paths!

### ISSUE THREAD

**Issue by Animeshz** [microsoft/WSL#6945]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

20.04

### Repro Steps

1. Make any file in Windows drives: `touch /mnt/c/somefile`
2. Try to open file: `notepad.exe /mnt/c/somefile` or `notepad++.exe /mnt/c/somefile`

### Expected Behavior

The path should be resolved successfully to `C:\somefile`

### Actual Behavior

![image](https://user-images.githubusercontent.com/26714676/118302386-c6cf4800-b501-11eb-9c31-20da5cee520a.png)

Throws error with path resolved as follows, `<drive currently in>:\mnt\<directory where file exists>\somefile`

**Comment by Animeshz** [comment]
Connected issue: https://github.com/npm/cli/issues/3248

**Comment by therealkenc** [comment]
/dupe #6266 #6207, others. Use:

```
$ notepad.exe "$(wslpath -w /mnt/c/Users/there/hello.txt)"
```
