### ISSUE TITLE
wsl$ is invalid hostname

### ISSUE THREAD

**Issue by hetasanghvi-zz** [microsoft/WSL#6946]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu-18.04

### Other Software

You will have to install liveshare extension on the VSCode.

### Repro Steps

1. Open temirnal Ubuntu (WSL2)
2. open VSC by 'code .'
3. Try to start a live share
4. see error, Share Failure: Invalid URI: The hostname could not be parsed

when we narrowed down this error we saw that the underlying issue is we have been passing, \\\\wsl$\\Ubuntu-18.04\\home, as path. if we look at UNC path $ is not valid character in hostname. 

I can provide a little more insight into this. On Windows, network file paths are represented as \\<host>\<share>\<path...> So when Windows mounts the WSL2 drive into the Windows filesystem, it is apparently mounted as a virtual network drive, in the form \\wsl$\<distro>\<path...>

However that seems to fail with a $ in the host name.

I am hoping to get some help here. 

### Expected Behavior

1. Open temirnal Ubuntu (WSL2)
2. open VSC by 'code .'
3. Try to start a live share
4.  User able to do liveshare

**Comment by therealkenc** [comment]
Variation of #4308.
