### ISSUE TITLE
when update always get Error with File has unexpected size  on kali linux

### ISSUE THREAD

**Issue by CRYBOII** [microsoft/WSL#6947]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

MSYS_NT-10.0-19042 version 3.1.6-340.x86_64 (@fv-az314) (gcc version 9.3.0 (GCC) ) 2020-07-09 14:33 UTC

### Distro Version

Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

### Repro Steps

1.install kali linux, but sometimes  it's got error with Error Code 0X80073D05 , i tried for few times untill it's installed 
2.i run command  $ sudo apt-get update 
3.see error like this:
`Get:1 http://mirror.kku.ac.th/kali kali-rolling InRelease [30.5 kB]
Get:2 http://mirror.kku.ac.th/kali kali-rolling/non-free amd64 Packages [204 kB]
Ign:2 http://mirror.kku.ac.th/kali kali-rolling/non-free amd64 Packages
Get:3 http://mirror.kku.ac.th/kali kali-rolling/contrib amd64 Packages [108 kB]
Ign:3 http://mirror.kku.ac.th/kali kali-rolling/contrib amd64 Packages
Ign:2 http://http.kali.org/kali kali-rolling/non-free amd64 Packages
Ign:3 http://http.kali.org/kali kali-rolling/contrib amd64 Packages
Err:2 http://http.kali.org/kali kali-rolling/non-free amd64 Packages
  File has unexpected size (187520 != 203953). Mirror sync in progress? [IP: 202.28.95.174 80]
19% [Working]E: Transaction http://http.kali.org/kali/dists/kali-rolling/InRelease was already aborted and is aborted again
Err:3 http://http.kali.org/kali kali-rolling/contrib amd64 Packages
  File has unexpected size (104948 != 107970). Mirror sync in progress? [IP: 202.28.95.174 80]
Reading package lists... Done
E: Transaction http://http.kali.org/kali/dists/kali-rolling/InRelease was already aborted and is aborted again`  

### Expected Behavior

kali linux should be able to update

### Actual Behavior

it's keep showing error, even i tried to reinstall kali linux and also face same problem
but  few day ago, it's work normally

**Comment by therealkenc** [comment]
Does the error manifest on a Ubuntu-20.04 install? On a lark, try putting `8.8.8.8` in `/etc/resolv.conf`. Also check `date` from your `bash` prompt and check that it is accurate(ish).

>  but sometimes it's got error with Error Code 0X80073D05

If this happens often enough to catch in the act, please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by CRYBOII** [comment]
> Does the error manifest on a [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71#activetab=pivot:overviewtab) install? On a lark, try putting `8.8.8.8` in `/etc/resolv.conf`. Also check `date` from your `bash` prompt and check that it is accurate(ish).
> 
> > but sometimes it's got error with Error Code 0X80073D05
> 
> If this happens often enough to catch in the act, please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

Thank for reply, today it's working again i can update without any errors
but before i tried to fix in many ways , change DNS , off firewall  , edit sourcelist 
but these settings not worked for me, anyways in 3 day later it's became working  again,
so i think this peoblem maybe about server
