### ISSUE TITLE
WSL --unmount syntax?

### ISSUE THREAD

**Issue by AskAlice** [microsoft/WSL#6950]
I don't see anything in the docs or in the --help page as to how to use WSL --unmount.

on a related note with WSL1, ever since I've installed the latest google drive, which mounts it to a disk letter on windows, i get 
```
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
```
I know I can work around this by creating an fstab for all of my drives... but I would like to automatically mount every drive except this one, and I'd rather not use an fstab so if I ever plug/unplug a drive there aren't issues.

I've tried `wsl --unmount X:\` `wsl --unmount X`, `wsl --unmount /mnt/x/` etc but it always says 
`The system cannot find the file specified.`

**Comment by OneBlue** [comment]
Hi @AskAlice,

`wsl --mount` is designed to attach a physical disk to WSL2 (and so this is a completely separated feature from the fstab).

To mount all drives except a specific one, the fstab is indeed the way to go (along with disabling [automount](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/))


For reference, `wsl --umount` takes a physical disk as argument, so it would be of the form `wsl --umount \\.\\PhysicalDrive1`.

[Documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#unmount-the-disk)

**Comment by Universal-Invariant** [comment]
> I don't see anything in the docs or in the --help page as to how to use WSL --unmount.
> 
> on a related note with WSL1, ever since I've installed the latest google drive, which mounts it to a disk letter on windows, i get
> 
> ```
> An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
> ```
> 
> I know I can work around this by creating an fstab for all of my drives... but I would like to automatically mount every drive except this one, and I'd rather not use an fstab so if I ever plug/unplug a drive there aren't issues.
> 
> I've tried `wsl --unmount X:\` `wsl --unmount X`, `wsl --unmount /mnt/x/` etc but it always says `The system cannot find the file specified.`

I'm having similar issues

Mounted a drive(partition) using --mount  and it shows up but couldn't unmount it. To unmount it I had to use `wsl --shutdown` and then use diskpart to make the disk come back online. UI've tried the physical disk and the \\wsl stuff(drive is mounted as \\wsl.Ubuntu IIRC). Nothing seemed to work to unmount properly.
