### ISSUE TITLE
Localhost port forwarding doesn't work for ports >= 61222

### ISSUE THREAD

**Issue by dtoch** [microsoft/WSL#6953]
### Windows Build Number

Microsoft Windows [Version 10.0.18363.1500]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Alpine Linux 3.13.4  (but same issue on Fedora 34)

### Repro Steps

In the Linux instance start a process listening on 61222 : 

```
while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; } | nc -l -p 61222; done
```

and then connect from the WSL Linux instance : 

```
wget http://localhost:61222
```

and from the Windows host : 

```
curl -v http://localhost:61222
```

Result : port 61222 accessible from inside the WSL Linux instance but **not** from the Windows host.

If in the above commands the port is changed to 61221 then there is NO issue. The issue only appears for port 61222 or higher (tested with about 10 ports >= 61222 to be sure).

### Expected Behavior

Services running in a WSL instance and listening on ports >= 61222 should also be accessible from the Windows host.

### Actual Behavior

Services running in a WSL instance and listening on ports >= 61222 are not accessible from the Windows host.

**Comment by dtoch** [comment]
Ok found the root cause : when looking at : 

```netsh int ip show excludedportrange protocol=tcp```

I noticed that the Windows winnat service had already automatically allocated a port range including 61222 as ephemal ports causing the WSL2 localhost port forwarding not to work anymore.

However I would have expected in WSL2 an error indicating that 61222 could not be used anymore but it silently ignored the port conflict.

**Comment by jamespacileo** [comment]
I'm having the same issue, how do we fix this?

**Comment by dtoch** [comment]
The solution I've done for example for the above case of 61222 : 

`$netsh int ipv4 add excludedportrange protocol=tcp startport=61222 numberofports=1 store=persistent`
