### ISSUE TITLE
"Attempted operation not supported.." error when trying to launch Ubuntu 20.04.

### ISSUE THREAD

**Issue by neelsbrink** [microsoft/WSL#6956]
# Title
"Attempted operation not supported.." error when trying to launch Ubuntu 20.04.
# Windows version
Microsoft Windows [Version 10.0.19041.985]

# Steps required to reproduce
Install WSL
Reboot
Upgrade to Ver 2
Set version 2 as default
Install Ubuntu 20.04 from MS Store
Launch

# Copy of the terminal output
"The attempted operation is not supported for the type of object referenced."

# Expected behaviour
Installation of Ubuntu and prompt to create a default Unix user account

# Additional Information
I tried
1. Uninstalling Ubuntu, disabling WSL feature, restarting PC and enabling WSL again, installing wsl-Ubuntu.
2. wsl.exe --shutdown
    netsh winsock reset
3. www.proxifier.com/tmp/Test20200228/NoLsp.exe (NoLsp.exe c:/windows/system32/wsl.exe)

**Comment by km-kurisu** [comment]
im having the same issue i tried redoing everything again yet the same error
