### ISSUE TITLE
Floppy Disks not working on WSL 2.0

### ISSUE THREAD

**Issue by OskarZyg** [microsoft/WSL#6960]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Plug a floppy disk into your computer
2. Try to navigate to /mnt/a or /mnt/b

### Expected Behavior

I am able to navigate to those disks

### Actual Behavior

Disks do not appear to exist

**Comment by benhillis** [comment]
We do not automatically mount removable media, but you should be able to manually mount these drives:

```
sudo mount -t drvfs A: /mnt/a
```

**Comment by OskarZyg** [comment]
Thank you, that appears to work.
