### ISSUE TITLE
WSL Version 1 locks process files which prevents them from being read in Python

### ISSUE THREAD

**Issue by Emperornero** [microsoft/WSL#6962]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) 

### Distro Version

Ubuntu 20.04

### Other Software

Python 3.8

### Repro Steps

When attempting to access a file created by another process via python, python cannot access the file, because it is locked by Windows, and Python does not have access to it.

WSL Version 1:

![image](https://user-images.githubusercontent.com/10823892/119040574-707f6080-b96a-11eb-917c-ce076e249c13.png)

![image](https://user-images.githubusercontent.com/10823892/119040794-b6d4bf80-b96a-11eb-8e0a-cb21d2037d95.png)

WSL Version 2: 

![image](https://user-images.githubusercontent.com/10823892/119041019-f7343d80-b96a-11eb-8b58-4e0d31552770.png)

![image](https://user-images.githubusercontent.com/10823892/119041191-2cd92680-b96b-11eb-8fe5-5910e21473f5.png)

### Expected Behavior

This behavior is not observed in WSL Version 2.  Python should be able to read the file in Version 1.

WSL 2 cannot be used due to significant cross OS I/O issues still unresolved by Microsoft.

### Actual Behavior

Python is unable to access the locked file for extracting information.

**Comment by therealkenc** [comment]
What are the CLI repro steps?

**Comment by Emperornero** [comment]
The current example I have for this is reproduced via these steps....

```
sudo apt-get update
sudo apt-get upgrade -y

# Install Git
sudo apt install git -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
cd chia-blockchain

sh install.sh

# Launch the environment

. ./activate

# Install Python monitoring program

pip3 install --force-reinstall git+https://github.com/ericaltendorf/plotman@main

# Generate configuration

plotman config generate

# Run the python program and view error

plotman plot

plotman status
```

**Comment by therealkenc** [comment]
The path to the logs in your screencap where scribbled, but for me, with the given repro steps, on WSL2 (sic), the path is `/home/chia/chia/logs...`. Looks like:

![image](https://user-images.githubusercontent.com/7049700/119416147-e60b6980-bca7-11eb-8295-5079ce85e010.png)

That path can't exist without some `sudo` step that would create `/home/chia`.

**Comment by Emperornero** [comment]
> The path to the logs in your screencap where scribbled, but for me, with the given repro steps, on WSL2 (sic), the path is `/home/chia/chia/logs...`. Looks like:
> 
> ![image](https://user-images.githubusercontent.com/7049700/119416147-e60b6980-bca7-11eb-8295-5079ce85e010.png)
> 
> That path can't exist without some `sudo` step that would create `/home/chia`.

Hello,

Apologies, I missed this step, you must change the log location located in `/home/USER/.config/plotman/plotman.yaml` to an existing log directory, or create one with `sudo mkdir /home/USER/plotmanlogs/`.

**Comment by therealkenc** [comment]
What is/are the missing repro step(s).

> significant I/O hit, due to #4197

None of the steps presented so far actually involve `/mnt/c`. That there is a WSL1/WSL2 diverge here exists, but is small. Both WSL1 and WSL2 use 9p for Windows filesystem interop. Going to re-tag this wsl1 for lack (I'll take your word for it).

**Comment by Emperornero** [comment]
I use several mounted drives, as this "plotting"  process generates 256 GB
of hash tables, then compresses them.

**Comment by Emperornero** [comment]
But the issue is not with the performance it's with the program reading the
log files because the files are locked by Windows and WSL does not have
read access to them.

**Comment by therealkenc** [comment]
> I use several mounted drives

None of the steps presented so far involve one or several mounted drives. Your `/proc/35/fd` is pointing to a path on `/home`, which is not a Windows path.

> because the files are locked by Windows and WSL does not have read access to them

I can't confirm whether that is the case as I have not been able to reproduce the behavior with the steps on offer. For the purpose of tracking, I'll take your word that your scenario is addressed with WSL2.

**Comment by ghertko** [comment]
> 
> But the issue is not with the performance it's with the program reading the log files because the files are locked by Windows and WSL does not have read access to them.

This sounds plausible to me. I used to develop with a PHP framework (symfony) on WSL1. Then after update 2021—KB5003173, the framework wasn't able to rewrite the cache files any more. I had to move my setup to Windows, which was possible but performance is poor.
