### ISSUE TITLE
system date is not same with windows (WSL 2)

### ISSUE THREAD

**Issue by axsaucedo** [microsoft/WSL#6974]
### Windows Build Number

 Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 18.04

### Repro Steps

As title suggests, there's drift on WSL2 distro and system clock. This causes unexpected behaviour such as incorrect date for git commits, etc. Reopening #4245 as not fixed - suggestions in this other issue are just workarounds. 

More specifically, workarounds suggested are one of the following:

* Running `sudo ntpdate pool.ntp.org`
* Running `sudo hwclock -s`
* Adding either of the previous to crontab (eg run every 10 mins)

# To reproduce 

To reproduce ause then resume the virtual machine reproduces issue (or getting laptop to go sleep)

![image](https://camo.githubusercontent.com/5c8a653c5e953b77d629c28c58055de63dbc94589f65fa13e4749a2630501b9c/68747470733a2f2f7777772e74656e666f72756d732e636f6d2f6174746163686d656e74732f7669727475616c697a6174696f6e2f3130313033376431343835393731373532742d73757370656e642d726573756d652d766d2d6d7563682d736c6f7765722d68797065722d762d7468616e2d766d776172652d696d6167652e706e67)

### Expected Behavior

System clock shouldn't drift from windows clock.

### Actual Behavior

Clock drifts.

### Diagnostic Logs

[    0.335041] rtc_cmos 00:00: setting system clock to 2019-06-21 22:54:24 UTC (1561157664)
[    0.335057] Unstable clock detected, switching default tracing clock to "global"
               If you want to keep using the local clock, then add:
                 "trace_clock=local"
               on the kernel command line

**Comment by 0xbadfca11** [comment]
This has fixed, but on Insider Preview.
https://devblogs.microsoft.com/commandline/servicing-the-windows-subsystem-for-linux-wsl-2-linux-kernel/
https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes
If you want to fix it now, you need to update the kernel yourself.
https://www.catalog.update.microsoft.com/Search.aspx?q=Windows%20Subsystem%20for%20Linux
```cmd
curl.exe -O http://download.windowsupdate.com/c/msdownload/update/software/updt/2021/04/wsl_update_x64_7694655b042eb3715cdc68f17da1bca6ca11f743.cab
expand.exe -R wsl_update_* .
cmd.exe /c start wsl_update_x64.msi
```
