### ISSUE TITLE
Reopen #5158

### ISSUE THREAD

**Issue by SheepReaper** [microsoft/WSL#6979]
### Windows Build Number

Microsoft Windows [Version 10.0.21382.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Insert USB dongle (mine is z-wave.me uzb (but also USB sd reader or USB hdd mounted with --mount))
2. Start wsl

```shell
ls /dev
```

### Expected Behavior

/dev/ttyACM0 should appear
(or mounted usb disk)

### Actual Behavior

It does not

**Comment by SheepReaper** [comment]
Reopen #5158

**Comment by txf-** [comment]
The real shame here is that this works in WSL1. But then WSL1 has other limitations, so in effect I can never fully use WSL for my purposes.

**Comment by therealkenc** [comment]
> /dev/ttyACM0 should appear

/dupe #2195
