### ISSUE TITLE
WSL.exe hangs on run. LxssManager is permanently in state "Stopping" (new problem)

### ISSUE THREAD

**Issue by jodavaho** [microsoft/WSL#6980]
Previously ran fine but the updates in the dev/preview channel in the last month have caused a lot of hangs. New information here is LXSS completely frozen in "stopping".

### Windows Build Number

21387.co_release.210518-1436

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Unknown (wsl will not run).

### Distro Version

Ubuntu 20.04

### Other Software

Nothing but startup applications / clean login. I logged out / in because that usually fixes WSL

### Repro Steps

launch ubuntu app. Nothing happens (black screen). Or, launch powershell and type 'wsl' nothing happens either. In an attempt to manually reset WSL, I have heard that running `services.msc` and stopping /restarting LxssManager would do the trick. 

### Expected Behavior

I expect WSL to launch per usual.

### Actual Behavior

WSL hangs. Any wsl.exe command. Lxss stuck in "stopping"

![image](https://user-images.githubusercontent.com/6580327/119285715-86ee1c00-bbf7-11eb-9b96-4b337faddd04.png)

**Comment by petternett** [comment]
I have the exact same issue on my machine (same windows build), though I don't know which logs to attach to help solve the problem. LxssManager is also permanently "stopping".

**Comment by jodavaho** [comment]
Alright, I've recorded logs at https://aka.ms/AAczgdt

**Comment by therealkenc** [comment]
> Or, launch powershell and type 'wsl' nothing happens either

Thanks. Please confirm the nature of "nothing happens". If you type `wsl.exe` at a Windows PS prompt, the command does not return? Usually there is a timeout error eventually (or some error) as opposed to "nothing". Maybe it hangs forever in your scenario, but knowing the fail condition ("hangs forever") that was captured in the logs helps.

**Comment by therealkenc** [comment]
> Or, launch powershell and type 'wsl' nothing happens either

Thanks. Please confirm the nature of "nothing happens". If you type `wsl.exe` at a Windows P prompt, the command does not return? Usually there is a timeout error eventually (or some error) as opposed to "nothing". Maybe it hangs forever in your scenario, but knowing the fail condition ("hangs forever") that was captured in the logs helps.

**Comment by MarJose123** [comment]
for my end this the solution.
https://stackoverflow.com/questions/70567543/cant-restart-wsl2-lxssmanager-hangs-in-stopping-state-how-to-restart
