### ISSUE TITLE
Failed mouting NTFS partition using `wsl --mount`

### ISSUE THREAD

**Issue by suxpert** [microsoft/WSL#6984]
### Windows Build Number

Microsoft Windows [Version 10.0.21387.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Kali rolling 2021.1

### Repro Steps

My computer have an SSD (C, system disk) and a 1TB HDD (D), after I set the HDD offline from disk manager, I tried to mount this disk inside wsl2 following [this tutorial](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk):

1. Open PowerShell as administrator
2. `wmic diskdrive list brief` show that this HDD was `\\.\PHYSICALDRIVE0`
3. `wsl --mount \\.\PHYSICALDRIVE0 --type ntfs` gives the following error:
  > The disk \\.\PHYSICALDRIVE0 was attached from WSL2, but failed to mount (error code: 19). For more details, ....
4. But I can mount with `--bare` and the HDD can be seen under wsl using `fdisk` or `lsblk`, and it shows that there are actually 2 partitions (where under windows I can see only one).
5. But with `wsl --mount \\.PHYSICALDRIVE0 --partition X --type ntfs`, I got the same error, no matter the X is 0, 1 or 2.
6. Comments: I can mount this partition under WSL after `wsl ... --bare`, using `sudo mount -t ntfs /dev/sdc2 /mount_point`, but the behavior is somewhat strange, see #6985 for details.

**Shuting down WSL or even rebooting the computer does not help.**

### Expected Behavior

I've noticed that (perhaps) no one had ever tried mounting a NTFS partition in WSL2, but it should be quite straightforward, similar to what has been described in the tutorial. Using 2 mount commands from powershell to wsl seems too complex for this task.

### Actual Behavior

`> wsl --mount \\.PHYSICALDRIE0 --type ntfs`
> The disk \\.\PHYSICALDRIVE0 was attached from WSL2, but failed to mount (error code: 19). For more details, run 'dmesg' inside WSL2.
To detach the disk, run 'wsl --umount \\.\PHYSICALDRIVE0'.

`$ dmesg | tail -11`
> [   34.769117] scsi 0:0:0:3: Direct-Access     ST1000DM 010-2EP102       1001 PQ: 0 ANSI: 5
[   34.770395] sd 0:0:0:3: Attached scsi generic sg3 type 0
[   34.772104] sd 0:0:0:3: [sdd] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)
[   34.772106] sd 0:0:0:3: [sdd] 4096-byte physical blocks
[   34.772365] sd 0:0:0:3: [sdd] Write Protect is off
[   34.772367] sd 0:0:0:3: [sdd] Mode Sense: 0f 00 10 00
[   34.772798] sd 0:0:0:3: [sdd] Write cache: enabled, read cache: enabled, supports DPO and FUA
[   34.775795]  sdd: sdd1 sdd2
[   34.778130] sd 0:0:0:3: [sdd] Attached SCSI disk
[   34.779258] ERROR: Mount:2528: mount(/dev/sdd, /share/PHYSICALDRIVE0, ntfs, 0x0, ) failed
[   34.779260] 19

**Comment by 0xbadfca11** [comment]
Expected.

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations
> Only filesystems that are natively supported in the kernel can be mounted by wsl --mount. This means that it's not possible to use installed filesystem drivers (such as __ntfs-3g__ for example) by calling wsl --mount.

https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/Microsoft/config-wsl#L2648
> \# CONFIG_NTFS_FS is not set

**Comment by therealkenc** [comment]
> Expected.

I could have swore there was a dupe but I can't find it.

**Comment by suxpert** [comment]
@therealkenc  I post this issue because the searching returns no relative ones (or I missed it).

@0xbadfca11 Thank you for pointing out, so this issue should be closed now.

**Comment by tbarbette** [comment]
Does anybody actually knows why? I'd expect the performance to be much better with a direct mount...
