### ISSUE TITLE
WSL2 drive too full, wont start. 

### ISSUE THREAD

**Issue by saippua** [microsoft/WSL#6986]
### Windows Build Number

10.0.21387.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

1) fill up the WSL system image with whatever data. I used a python script to save matrix data, which ended up exceeding the available space on the drive.
2) when its full, the saving process will crash

I have WSL installed on a 120 GB SSD if thats relevant. Theres nothing other than ubuntu 20.04 on the drive.

### Expected Behavior

I want to be able to start WSL again and recover my work

### Actual Behavior

After the saving process which exceeds drive capacity crashes, all subsequent commands give an input/output error. I tried even simple commands like `ls` but they werent working. I was still able to browse the mounted drive in explorer.exe but was not able to delete the file I had saved that way.
After doing `wsl.exe --shutdown`, WSL no longer starts. It gives the message: `An error occurred mountiong one of your file systems. Please run 'dmesg' for details.` and then exits with code 1. I cant run dmesg because the command prompt doesnt come up at any point. Trying `wsl.exe -e dmesg` in cmd hangs for a long time then times out because response was not received.
I also cannot browse the drive in explorer.exe either, as the drive is no longer mounted.

**Comment by saippua** [comment]
I'm not sure what logs I should be attaching. Can someone give me a hand?

**Comment by therealkenc** [comment]
> I want to be able to start WSL again and recover my work

There's some suggestions for recovery in #5322 (h/t 0xbadfca11).

**Comment by saippua** [comment]
@therealkenc Thanks for those, but I havent been able to get them to work. I converted the ext4.vhdx to a .raw image using `qemu-img` as per suggestion, but I have not been able to mount it. When attached to a loop device, no partitions are recognized.

There was another suggestion to initialize a new WSL and replace the fresh ext4.vhdx with my old one, but I have not been able to replace the ext4 as it is in use by System.. I've tried `wsl --shutdown`, `wsl -t Ubuntu-20.04`, multiple system restarts, but the ext4.vhdx is always mounted as a network drive on startup.

**Comment by OneBlue** [comment]
@saippua: The WSL2 disks aren't partionned so that's expected. To mount the disk you'd need to mount the whole device directly at ext4 (that would look something like `mount /dev/sdb {mountpoint}`  (replace /dev/sdb with the actual block device )

**Comment by ShyPixie** [comment]
I have exactly same issue. I managed to recover some data using guestmount (from libguestfs-tools) on another wsl instance with debian installed, but I can't make the vhdx work with wsl again, sad

**Comment by Kulgar** [comment]
@ShyPixie : could you explain a bit more how you repaired the partition journal? Providing some command lines maybe?
I have the same issue. 
I tried using virt-rescue but I don't seem to be able to unmount the partition to run e2fsck check on it.

**Comment by ShyPixie** [comment]
> @ShyPixie : could you explain a bit more how you repaired the partition journal? Providing some command lines maybe?
> I have the same issue.
> I tried using virt-rescue but I don't seem to be able to unmount the partition to run e2fsck check on it.

You must run virt-rescue without mounting the partition `sudo virt-rescue -a <vhdx path>`

**Comment by Kulgar** [comment]
@ShyPixie : Thanks. I was able to run e2fsck - had to use the "-f" option, but it didn't seem to solve the problem :-/

**Comment by kh-abd-kh** [comment]
I had the same problem. something like 9 giga free and installing some big prog
run out of space. I spent a terrible night trying many things. Rebooting , deleting swap file.s Free some space 5Giga
nothing worked even opening the ext4.vhdx in 7z didn't work gives me a corrupted file.

imagine 80 Giga of work lost in a moment. it doesn't start. jut gives me:

The operation timed out because a response was not received from the virtual machine or container

Then out of the blue, i opened in the explorer my other wsl and it,  my old
wsl ubuntu 20.04 was there and i could access it.
Then it works.
Hoping  this might be useful for someone googling and having the same problem.

1-Reboot, 
2- Free space 
3- mount it in the explorer 

Now, it is fine and i deleted the corrupted installed progs and everything seems ok so far.

**Comment by yeousunn** [comment]
I have the same problem today. I was building a project which require around 40Gb of disk space. I have few different clones of the project as I am required to work on different branches. I have 400Gb of total disk assigned to the wsl, now the disk is full and I am not able to connect to it or open it in the explorer. The only option right now seems like to connect a new disk and move the vhdx and try to connect. 

The following is the error:
> running uname in "Ubuntu" distro: running WSL command "wsl.exe -d Ubuntu uname" 
> failed with output "The operation timed out because a 
> response was not received from the virtual machine or container. 
> \r\nError code: Wsl/Service/CreateInstance/HCS_E_CONNECTION_TIMEOUT\r\n": exit status 0xffffffff

**Comment by OneBlue** [comment]
@yeousunn: This should be fixed with store WSL.

Can you share /logs ?

**Comment by yeousunn** [comment]
@OneBlue , I worked around it for now by emptying the drive a little. I will save the logs when it happens again. 
I can inform you that this happens only when there is no more diskspace left and wsl can't expand anymore. 
The work around here is to empty any files in the same drive or try to open the \\wsl$ (may require few restarts/tries to open) and delete large files.

**Comment by OneBlue** [comment]
Sounds good ! 

I'll resolve the issue for now, feel free to reopen if you experience this again

**Comment by tebys** [comment]
For me the drive was encrypted and couldn't mount it on windows. The solution that worked was exporting it. Using an admin powershell run the following
`wsl --list --verbose` to list all your linux distros (note the name)
`wsl --export <name> <path>`. Where the name is from the previous and the path can be any windows drive.  i.e. `wls --export Ubuntu c:\ubuntu.tar`

This generate as tar archive from where files can be recovered.

**Comment by ericblade** [comment]
I just ran out of disk space on a second WSL2 instance that I just installed (failing to remember that it always installs to C, and has to be moved to other disks), and now my wsl command just hangs.  attempting to launch into either wsl shell just hangs.  weirdly, the running wsl2 that ran out of disk space had absolutely no idea that it was out of disk space, and just kept on running, but i couldn't kill any of the processes in it

**Comment by wynnw** [comment]
This definitely still happens - I ran out of disk space inadvertently running an overnight test and the entire wsl system was completely unresponsive. I filled up an entire 1tb ssd e: drive where my ext4.vhdx file was. Had to jump through many hoops to get that vhdx file mounted in another hyper-v linux vm to clear out the test files and then wsl would start again once the vhdx file has free space inside it.

**Comment by IzioDev** [comment]
> This definitely still happens - I ran out of disk space inadvertently running an overnight test and the entire wsl system was completely unresponsive. I filled up an entire 1tb ssd e: drive where my ext4.vhdx file was. Had to jump through many hoops to get that vhdx file mounted in another hyper-v linux vm to clear out the test files and then wsl would start again once the vhdx file has free space inside it.

can you please provide step by step resolution step ? my WSL is now stucked, commands hanging forever.

i would like to retreive some private key before droping this whole WSL shit, again.

**Comment by wynnw** [comment]
I love wsl, it's definitely not shit. For sure it has bugs like every other piece of software I use (and write). This is a bad unfortunate bug that is very painful for sure.

My steps to resolve were to shutdown wsl (may have had to reboot), then use a hyper-v linux vm I had laying around and mounted the vhdx to that running linux vm using the hyper-v UI. Then from within the hyper-v linux vm, I explicitly mounted the device (I forget what it was exactly) to a /mnt/wsl directory I created. I was able to go clear out the data I created to reduce the disk size. You could retrieve your key as well that way.  Once I pruned the wsl disk, I shut down my hyper-v vm, removed the vhdx file from that vm, then rebooted and was able to run my wsl distro again.

**Comment by kh-abd-kh** [comment]
> I had the same problem. something like 9 giga free and installing some big prog run out of space. I spent a terrible night trying many things. Rebooting , deleting swap files Free some space 5Giga nothing worked even opening the ext4.vhdx in 7z didn't work gives me a corrupted file.
> 
> imagine 80 Giga of work lost in a moment. it doesn't start. just gives me:
> 
> The operation timed out because a response was not received from the virtual machine or container
> 
> Then out of the blue, i opened in the explorer my other wsl and it, my old wsl ubuntu 20.04, was there and i could access it. Then it works. Hoping this might be useful for someone googling and having the same problem.
> 
> 1- Reboot, 2- Free space 3- Mount it in the explorer
> 
> Now, it is fine and i deleted the corrupted installed progs and everything seems ok so far.
