### ISSUE TITLE
WSL1 Cannot start any Windows applications anymore

### ISSUE THREAD

**Issue by xploSEoF** [microsoft/WSL#6988]
### Windows Build Number

Version	10.0.19042 Build 19042

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020

### Distro Version

Ubuntu 20.04

### Other Software

Things like Windows Explorer (standard, see windows build number) and VS Code (v1.56.2) 

### Repro Steps

From the WSL terminal, run `explorer.exe`

### Expected Behavior

An explorer window should open

### Actual Behavior

`-bash: /mnt/c/Windows/explorer.exe: cannot execute binary file: Exec format error`

**Comment by xploSEoF** [comment]
Equally, running `code .` (which triggers VS Code to run with the current directory) errors in the same way:
`/mnt/c/Users/Liam/AppData/Local/Programs/Microsoft VS Code/bin/code: 61: /mnt/c/Users/Liam/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error`

**Comment by benhillis** [comment]
Something specific to your environment it seems, do you have any more details that can help us diagnose?

**Comment by xploSEoF** [comment]
Not too sure what further information I could provide.

Everything worked a month ago, then I applied a few updates on Windows, and now I can't invoke any Windows application from within WSL1.

**Comment by xploSEoF** [comment]
I've just exported my WSL installation and imported it onto a new machine, and I'm still having the same issue. Perhaps there's something in the WSL instance that needs changing to be able to invoke windows applications? It's either that, or it is an issue with WSL1 and the rest of Windows since the update earlier this year.

**Comment by jhwblender** [comment]
Personally getting this issue myself with WSL2 after recompiling the Kernel to include some CAN bus features.

**Comment by xploSEoF** [comment]
@jhwblender I suspect the two are different issues. WSL2 most likely has an altered kernal to handle windows specific things, and your recompile doesn't include the alterations necessary.

My understanding is that one of the Windows updates I received changed the way the Windows side handled the request, requiring a change to WSL instances, but these changes weren't passed on to those in legacy WSL1. Unfortunately, with no easy migration from WSL1 legacy to the newer WSL1 instances and my bug report having been abandoned and forgotten (I'm surprised it hasn't been closed) I have to put up with this issue until I find the time to go through the lengthy process of starting from scratch.
