### ISSUE TITLE
Alt+Shift+3 behaves weirdly

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/WSL#6989]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.985]

### WSL Version

- [x] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Open WSL.
2. Write anything in the command prompt
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>3</kbd>

### Expected Behavior

That keyboard shortcut should comment the current line

### Actual Behavior

After pressing those keys the command prompt acts weirdly. If you move the cursor to the left and write anything, the text moves backwards. In fact, in order to comment the current line I have to press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>3</kbd> instead.

**Comment by adriancuadrado** [comment]
Please note that I only selected WSL1 because I only have WSL1, but it might be worth checking if this happens in WSL2 as well.

**Comment by therealkenc** [comment]
> That keyboard shortcut should comment the current line

Nothing in WSL would "comment the current line" at the "command prompt" when pressing "Ctrl+Shift+3". Nothing in `bash` ("the command prompt") would either. This can't even reasonably be punted to [console](https://github.com/microsoft/terminal).

What are the repro steps from a clean distro install to manifest "If you move the cursor to the left and write anything, the text moves backwards".

**Comment by adriancuadrado** [comment]
This keyboard shortcut is supposed to comment the current line, according to Daniel Andersson.

https://superuser.com/a/641582/669882

> Documented in the bash manual [here](http://www.gnu.org/software/bash/manual/bashref.html#index-insert_002dcomment-_0028M_002d_0023_0029):
> 
> `M-#` or <kbd>Alt</kbd><kbd>Shift</kbd><kbd>3</kbd>

### What are the repro steps from a clean distro install to manifest "If you move the cursor to the left and write anything, the text moves backwards".

1. Write "qwertyuiop" in the command line
2. Press <kbd>←</kbd> 5 times.
3. Press <kbd>q</kbd> 10 times.

You will see something like this:
![image](https://user-images.githubusercontent.com/29214635/119889433-d35a9400-bf36-11eb-8e1a-8e8f7f542694.png)
The 'q's overlap the prompt.

**Comment by therealkenc** [comment]
> Documented in the bash manual here:

Thanks for the reference; very appreciated.

I wasn't able to reproduce here with windows terminal or legacy console. What is the output of `echo $TERM`. Assuming it returns `xterm-256color`, I don't have any great guesses on the external variable.

![image](https://user-images.githubusercontent.com/7049700/119895424-9a98cb80-bef2-11eb-985c-05dbfc38352d.png)

First thing would be to try [windows terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab) just to get that out of the way. Start WSL from a cmd or powershell prompt inside terminal with `wsl.exe` or `wsl.exe -d [distro-name]`.

The other usual suspect is something in userspace, although your prompt looks clean as it goes (contrast some highly modded setup). When you tried WSL2, did you do it via an upgrade of your WSL1 distro, or install a new distro? If it was an upgrade, maybe try installing a new distro to start from scratch. For example, if your distro is [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6#activetab=pivot:overviewtab), install [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab), or visa-verse. It isn't the distro that matters here, it is just eliminating any local changes vs. a clean install, to the extent that might be applicable.

**Comment by adriancuadrado** [comment]
![image](https://user-images.githubusercontent.com/29214635/119899973-27b84080-bf44-11eb-9eb1-e083300b3bd0.png)
Alt+Shift+3 seems to insert a bell character instead. Apart from that in the windows terminal everything works as expected.

Running wsl.exe in cmd leads to the same symptoms (the 'q' overlaps the prompt again).

I had [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab), so I installed [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6#activetab=pivot:overviewtab). Same problem.

I started to suspect it is just the fault of the cmd, so I run cmd and tried the same without wsl, but this insert the '·' character.

I doubt this is related, but I am using the Spanish keyboard layout:
![image](https://user-images.githubusercontent.com/29214635/119900739-35ba9100-bf45-11eb-8618-f2e870aef257.png)

**Comment by adriancuadrado** [comment]
```
adrian@DESKTOP-EF8FQ3I:~$ echo $TERM
xterm-256color
```

**Comment by therealkenc** [comment]
Alright. Thanks for trying out a clean install. That was overkill given your scenario, but at least you can say definitively it is not a userspace problem. I should have been quicker on the uptake regarding the meta key-sequence. It isn't a WSL-proper actionable; WSL is consuming the terminal sequence bytes it is getting down the pty (which is why WSL1 v. WSL2 isn't going to make a difference). I can't reproduce "Alt+Shift+3 seems to insert a bell character instead". I get the `#` comment. For what might be going on there for you, the windows terminal people will have better [answers](https://github.com/microsoft/terminal/issues). The sequence you want really is alt-shift-3, not ctrl-shift-3 (the sequence in your OP repro). On Windows Terminal ctrl-shift-3 spawns a new tab, because it is a shortcut for the terminal app itself. Thanks again for pursuing this with all the details.

![image](https://user-images.githubusercontent.com/7049700/119907484-3af7eb80-bf05-11eb-8610-654c5e8fec4c.png)

**Comment by adriancuadrado** [comment]
@therealkenc Thanks for your support. I reported this bug here as you said: https://github.com/microsoft/terminal/issues/10244

**Comment by magiblot** [comment]
Adrián, I suspect this is a Bash issue. I'm seeing the same issue on Linux with Konsole. When typing Alt+Shift+3, the following bytes are emmited:

```r
0x1B # ESC (alt modifier)
0xC2 # first byte of '·'
0xB7 # second byte of '·'
```

Note that with the Spanish layout Shift+3 produces the character `·`, which is multibyte in UTF-8.

Typing other multibyte characters with the Alt modifier (e.g. Alt+`º`, Alt+`€`) also results in invalid characters being printed. So I am certain this is Bash's fault for failing to process multibyte characters preceded by an ESC byte.

Saludos.

**Comment by therealkenc** [comment]
> I'm seeing the same issue on Linux with Konsole.

Yesterday I was almost going to suggest trying [WSLg](https://github.com/microsoft/wslg) with gnome-terminal (or konsole, or whatever) and see if it behaves the same. If someone with a Spanish keyboard can confirm or deny, that'd be a decent data point. Or even try other "competing" terminal emulators. I use [ttyd](https://github.com/tsl0922/ttyd) now and then, and [wsltty](https://github.com/mintty/wsltty) has a following. Worth trying before rattling any chains over in the Windows Terminal tracker, anyway.
