### ISSUE TITLE
Thin web server

### ISSUE THREAD

**Issue by sonhc** [Microsoft/WSL#699]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  -Thin Web Server doesn't work correctly.  The server run successfully but can't be reached from browser pointing at localhost:3000
- Expected results
  -Should be able to hit the server from the browser
- Actual results (with terminal output if applicable)
  -Server run correctly but can't be reached by the browser.  See below for the console output o the server:
  => Booting Thin
  => Rails 4.2.6 application starting in development on http://localhost:3000
  => Run `rails server -h` for more startup options
  => Ctrl-C to shutdown server
  Thin web server (v1.6.4 codename Gob Bluth)
  Maximum connections set to 1024
  Listening on localhost:3000, CTRL+C to stop
- Your Windows build number
  -14393.5
- Steps / commands required to reproduce the error
  -Run Thin Web Server on any Ruby on Rails app.  I'm using Ruby 2.1.2 and Rails 4.2.7.

**Comment by benhillis** [comment]
Have you made sure that port 3000 is open in Windows Firewall or any third party firewall you are using?

**Comment by sonhc** [comment]
Yep.  It works perfectly fine with WEBrick.

**Comment by sunilmut** [comment]
@sonhc - Can you do a "netstat -a" on a Windows cmd prompt and make sure that localhost:3000 port is in a listening state? If the port is not in a listening state, can you grab a strace of the starting of the "Thin webserver" and share it with us: "strace -o <strace_output_file> -ff <cmd_to_start_webserver>"

**Comment by sonhc** [comment]
I ran 'netstat -a' and when I run the WEBrick server, 127.0.0.1:3000 is in listening state.  However, when I run Thin web server, 127.0.0.1:3000 doesn't show up (not in listening state).
[strace.zip](https://github.com/Microsoft/BashOnWindows/files/389860/strace.zip)

**Comment by sonhc** [comment]
Any update on this bug and whether Thin server will be supported?

**Comment by emonhaider** [comment]
+1

**Comment by aseering** [comment]
Are folks here using the current stable build of Windows (14394), or the latest [Insider build](https://insider.windows.com/) (14986)?

There are a *lot* of improvements to WSL's networking stack that are available in Insider builds but that won't be released to stable Windows users until the next major Windows release (the "Creators Update") in a few months.  It would be interesting to know whether this is still an issue in more-recent builds.

**Comment by sunilmut** [comment]
On top of what @aseering mentions above, if the issue still persists in 14986, please provide all the files necessary for the repro. It really makes a big difference for us when we want to repro an issue and a huge time saver.

**Comment by sonhc** [comment]
There's really no need to provide any log file.  It's quite easy to reproduce.  I started with a blank bash on windows install.  Then I follow the instruction here to set up a rails environment here: https://gorails.com/setup/ubuntu/16.04.  Then I created the test myapp as shown in the bottom of the link I provided.  I then make it boot using Thin instead of WEBrick by adding "gem 'thin'" in the Gemfile.  After I did that, localhost:3000 is no longer hitting the rails server.  However, without the gem 'thin', I was able to hit localhost:3000.  BTW, I'm running 14986.

**Comment by pupeno** [comment]
I manage to reproduce this as well. I have an app and I started with both, webrick and thin. Webrick is very slow to respond to static files requests (a very old Windows issue) but it works. Thin never responds to requests.

Furthermore, thin has to be killed -9 to exit.

**Comment by MosesMendoza** [comment]
This is still an issue for me running on the Creators Update / Ubuntu 16.04. Thin starts up but cannot be reached. I tried on port 80, 8080, 3000, tried disabling all firewalls. I even installed lynx and tried navigating to a page directly from within bash to no avail - of course that makes sense since it doesn't appear anything is actually listening when it starts. I started thin with --trace and it never receives a connection attempt.

**Comment by sudheesh001** [comment]
The issue still exists as @MosesMendoza described. Any updates?

**Comment by aseering** [comment]
There's some recent discussion on #1554 that might be relevant?

**Comment by sunilmut** [comment]
@all - As @aseering points out, please see the discussion on [#1554](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927) and let us know if it resolves the issue for you.

**Comment by swiftster** [comment]
@sunilmut I don't have the TDI driver installed, and can get a Python SimpleHTTPServer to work, but not Thin.

**Comment by sunilmut** [comment]
@swiftster - Can you please fill out the issue [template](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) so that we can have a better idea of what is not working for you?

Please don't forget to note your Windows version, output of the `ver` command.

**Comment by tara-raj** [comment]
As per the above comment https://github.com/Microsoft/WSL/issues/699#issuecomment-363284510, please continue this discussion on https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927.
