### ISSUE TITLE
Why .wslconfig  settings dosen't  effect , when i limit the memory used by wsl2 ?  

### ISSUE THREAD

**Issue by triump2020** [microsoft/WSL#6990]
### Windows Build Number

Windows 10  19043.1023

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.19.104-microsoft-standard

### Distro Version

Ubuntu 20.4

### Repro Steps

       1.  Change the settings  in .wslconfig  like this :
            [wsl2]
               memory=8GB
             swap=8GB
            localhostForwarding=true

       2. Restart the wsl2  or   the windows ,  then run the cmd: free -h   in wsl2 .  the result like this :
       
![image](https://user-images.githubusercontent.com/63033222/119532154-33c2c780-bdb7-11eb-96ac-a50c6f9d420f.png)

### Expected Behavior

      The settings in .wslconfig  should effect  after wsl2 or windows restart

### Actual Behavior

  Settings seems that hava no effect !

**Comment by benhillis** [comment]
You will need to run wsl.exe --shutdown after changing this file for it to take effect.  Also it looks like you may have some whitespace in your config file, I'm not sure the parsing library likes that...

**Comment by triump2020** [comment]
@benhillis    It dosen't take a effect even i reboot the windows !   screenshots of my config file : 
![Uploading image.png…]()

**Comment by triump2020** [comment]
![image](https://user-images.githubusercontent.com/63033222/119552747-7394a980-bdcd-11eb-89a0-7fb35a1121a4.png)

**Comment by onomatopellan** [comment]
I's not `.wslconfig.txt` but `.wslconfig`. Get rid of the `.txt` and it should work after running `wsl.exe --shutdown`.

**Comment by therealkenc** [comment]
Screencap FTW.

**Comment by triump2020** [comment]
@onomatopellan    Thanks !  😄
