### ISSUE TITLE
wsl --mount is not working.

### ISSUE THREAD

**Issue by rappysaha** [microsoft/WSL#6997]
### Windows Build Number

Microsoft Windows [Version 10.0.21387.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.19.128-microsoft-standard (oe-user@oe-host)

### Distro Version

Ubuntu 16.04, Ubuntu 20.04

### Repro Steps

1. Open Windows terminal at administrator mode.
2. run `wmic diskdrive list brief`
![image](https://user-images.githubusercontent.com/43848926/119754810-eee48100-bedb-11eb-8f6c-e15997fb25d1.png)

3. We can see a  SanDisk Ultra Luxe USB Device listed as \\.\PHYSICALDRIVE2. Besides, we can see the drive at file explorer also.
![image](https://user-images.githubusercontent.com/43848926/119755260-ae393780-bedc-11eb-84ff-57ff337d2b48.png)

4.  run `wsl --mount \\.\PHYSICALDRIVE2 --partition 1`
![image](https://user-images.githubusercontent.com/43848926/119755551-29025280-bedd-11eb-88e8-42c3e1ec7ba4.png)

5. And after trying to run the `wsl --mount \\.\PHYSICALDRIVE2 --partition 1` . I cannot see the USB in the file explorer also.
![image](https://user-images.githubusercontent.com/43848926/119756238-3c61ed80-bede-11eb-9bf7-dea19adc2f62.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/43848926/119755671-59e28780-bedd-11eb-9aa4-c62c814cbc3c.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/43848926/119755551-29025280-bedd-11eb-88e8-42c3e1ec7ba4.png)

### Diagnostic Logs

![image](https://user-images.githubusercontent.com/43848926/119755946-cb223a80-bedd-11eb-8ee9-d38e4e686b97.png)

**Comment by 0xbadfca11** [comment]
> USB flash drives and SD cards are not supported at this time and will fail to attach to WSL 2. USB disks are supported though.
> https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#limitations
