### ISSUE TITLE
wsl mount error

### ISSUE THREAD

**Issue by shajul** [microsoft/WSL#7002]
`The process cannot access the file because it is used by another process`

This is the error message on trying to mount using wsl2 on insider dev build

**Comment by OneBlue** [comment]
Thanks for reporting this @shajul.

Can you please follow the [wsl --mount section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#wsl---mount) and share the output ? 

Which disk are you trying to mount ?

**Comment by 4t4nner** [comment]
@OneBlue , hello. I have the same error. 
```
PS C:\Users\user> wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType              Model                      Name                Partitions
              {3, 4}        {"Random Access", "Supports Writing"}                        \\.\PHYSICALDRIVE3  SCSI           TRUE         Fixed hard disk media  Samsung SSD 970 PRO 512GB  \\.\PHYSICALDRIVE3  5
```
`./networking.bat` output "Syntax error in file name, folder name, or volume label."

Partition has EXT4 and when I open Drive director it offers initialize it, but my second ubuntu system works fine.
