### ISSUE TITLE
Windows touch keyboard - special characters not working

### ISSUE THREAD

**Issue by leoshusar** [microsoft/WSL#7005]
### Windows Build Number

Microsoft Windows [10.0.19043.1023]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

- set keyboard to Czech
- open touch keyboard
- type any "AltGr char" (like `@`, `$`, `€`, `[`, `]`, `^`)

*EDIT: found out that it happens even on English touch keyboard, but there I can write those characters using shift key. I still cannot write for example `€` character using AltGr*

### Expected Behavior

Those characters should work normally

### Actual Behavior

When I write those characters, they won't appear in WSL and Windows "error" sound plays.
One difference I found is when you write `#` char, it writes it and sends "return" (or newline) after it.

When using physical keyboard, everything works as it should.

**Comment by therealkenc** [comment]
WSL doesn't have a keyboard device (touch or otherwise); the keystrokes are handled by the terminal/console application on the Windows side. Please open up an issue in the windows terminal [issue tracker](https://github.com/microsoft/terminal/issues).

**Comment by OneBlue** [comment]
This looks like [this RDP issue](https://social.technet.microsoft.com/Forums/windows/en-US/3a34cd32-9f63-4501-b27a-fd43ba8831ee/altgr-randomly-disable-when-using-rdp?forum=win10itprogeneral)

@leoshusar: Does this happen consistently ? Do you have any RDP window opened when that happens ? (note that wslG windows are using RDP)

**Comment by leoshusar** [comment]
I don't have any RDP window opened and it happens every time. I have noticed it on my MS Surface for the first time (clean Windows installation), then tried it on my desktop and laptop and it happens everywhere.
