### ISSUE TITLE
WSL2 distro start failed with 0x80070057 on build 21390

### ISSUE THREAD

**Issue by HartmonWang** [microsoft/WSL#7007]
### Windows Build Number

Microsoft Windows [Version 10.0.21390.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

1. Enable WSL2 from msft, everything seems OK.
https://docs.microsoft.com/en-us/windows/wsl/install-win10

2.  Update kernel to the lastest version: `wsl --update`

3. Set WSL default version to `2`

4.  Restart Windows and try to install ubuntu-20.04:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...
```
![wsl2_start_fail](https://user-images.githubusercontent.com/8011191/120179358-09e92500-c23d-11eb-90d1-a156d852a1de.png)

5. Additional information:
   - WSL 1 app start successfully.
   - Disable GUI(`guiapplications=false` in .wslconfig) dosn't work for me.  See #6839 for more details. 

### Expected Behavior

The `Ubuntu-20.04` should work.

### Actual Behavior

WSL2 report  0x80070057 The parameter is incorrect.

### Diagnostic Logs

[network_diag_info.zip](https://github.com/microsoft/WSL/files/6569558/network_diag_info.zip)
[wsl_logs.zip](https://github.com/microsoft/WSL/files/6569581/wsl_logs.zip)

**Comment by craigloewen-msft** [comment]
Thank you for providing the logs! We took a look and saw that this was networking related and are looking into this further.

**Comment by OneBlue** [comment]
Thank you for reporting this @wangdan1600.

Can you share the output of:
```
Get-WindowsOptionalFeature -Online | ? State -eq Enabled | select FeatureName
``` 
In an elevated powershell prompt ? 

Also, does the issue still reproduce after a reboot ?

**Comment by wangdan1600** [comment]
> Thank you for reporting this @wangdan1600.
> 
> Can you share the output of:
> 
> ```
> Get-WindowsOptionalFeature -Online | ? State -eq Enabled | select FeatureName
> ```
> 
> In an elevated powershell prompt ?
> 
> Also, does the issue still reproduce after a reboot ?


I'm sorry, I **reinstall win10 OS last week, and the WSL2 run normally.**

Before I open this issue, I tried enable/disable/reenable VirtualMachinePlatform feature many times, and reboot many times, and none of these methods worked.

If you couldn't find any usable information from the logs,  I think you can close this issue. 

Thanks, BR.

**Comment by adarsha2003** [comment]
Not starting WSL2 on Windows 11 22000.51 DEV Build

**Comment by craigloewen-msft** [comment]
@adarsha2003 can you please share the output of running this command in an elevated powershell prompt?

`Get-WindowsOptionalFeature -Online | ? State -eq Enabled | select FeatureName`

As well does this still happen after a reboot? And can you please [include networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues)?

**Comment by adarsha2003** [comment]
@craigloewen-msft Sorry now i cant share logs. Now i have reinstalled windows 11, now WSL2 is working fine. I think the problem is due to because i have upgraded many times using dev channel. There could be problem in one of the windows 10 upgrades.
Thanks for you support

**Comment by sushshring** [comment]
I'm seeing a similar issue, the etl trace shows a networking issue while creating the network for WSL2. The output for the Get-FeatureName command above is
```
Printing-PrintToPDFServices-Features
Printing-XPSServices-Features
SearchEngine-Client-Package
WorkFolders-Client
Printing-Foundation-Features
Printing-Foundation-InternetPrinting-Client
MSRDC-Infrastructure
VirtualMachinePlatform
Microsoft-Windows-Subsystem-Linux
MicrosoftWindowsPowerShellV2Root
MicrosoftWindowsPowerShellV2
NetFx3
WCF-Services45
WCF-TCP-PortSharing45
NetFx4-AdvSrvs
SmbDirect
MediaPlayback
WindowsMediaPlayer
```

**Comment by rgianassi** [comment]
I'm seeing a similar issue on Windows 10 21H2 19044.1415. The output of above command is:

```
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online | ? State -eq Enabled | select FeatureName

FeatureName
-----------
Printing-PrintToPDFServices-Features
Printing-XPSServices-Features
WCF-Services45
WCF-TCP-PortSharing45
MediaPlayback
WindowsMediaPlayer
SmbDirect
MSRDC-Infrastructure
NetFx4-AdvSrvs
SearchEngine-Client-Package
MicrosoftWindowsPowerShellV2Root
MicrosoftWindowsPowerShellV2
WorkFolders-Client
Internet-Explorer-Optional-amd64
Printing-Foundation-Features
Printing-Foundation-InternetPrinting-Client
Microsoft-Windows-Subsystem-Linux
HypervisorPlatform
VirtualMachinePlatform
Containers-DisposableClientVM
Microsoft-Hyper-V-All
Microsoft-Hyper-V
Microsoft-Hyper-V-Tools-All
Microsoft-Hyper-V-Management-PowerShell
Microsoft-Hyper-V-Hypervisor
Microsoft-Hyper-V-Services
Microsoft-Hyper-V-Management-Clients
```

I sent logs through Feedback Hub (they reference this issue in the title, I did not find the share link). A strange thing is happening with Hyper-V Virtual Switches:

![image](https://user-images.githubusercontent.com/45180195/147978444-16739696-2cbc-421e-82ee-83cd27630e97.png)

in practice, every time I try to run/install a Linux image a new WSL Switch is created.
I have only one Ethernet adapter and is already associated with the Bridge Switch.
I also removed the Bridge Switch and retried to run Ubuntu, but the error is still the same.
Hope this helps.

**Comment by liorko87** [comment]
Still happen on Windows 11 when I'm trying to install Ubuntu 22.04 LTS from Microsoft store.

I ran the command above and got this output:
```
FeatureName
-----------
Printing-PrintToPDFServices-Features
Printing-XPSServices-Features
WCF-Services45
WCF-TCP-PortSharing45
MediaPlayback
WindowsMediaPlayer
MicrosoftWindowsPowerShellV2Root
MicrosoftWindowsPowerShellV2
WorkFolders-Client
SearchEngine-Client-Package
Printing-Foundation-Features
Printing-Foundation-InternetPrinting-Client
MSRDC-Infrastructure
Microsoft-Windows-Subsystem-Linux
NetFx4-AdvSrvs
```

**Comment by ZhangHongbin9** [comment]
[WslLogs-2022-05-25_20-44-47.zip](https://github.com/microsoft/WSL/files/8771203/WslLogs-2022-05-25_20-44-47.zip)
Same issue, wsl 2 with ubuntu 22.04, here is the log file.

**Comment by ZhangHongbin9** [comment]
https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
Linux kernel update package is needed.Seems like it works
