### ISSUE TITLE
problem install Ubuntu in Win10

### ISSUE THREAD

**Issue by Raurent** [microsoft/WSL#7008]
When I start the Ubuntu in Win10, it is showing 'The specified network name is no longer avaiable', and I can't use it. Why?

**Comment by craigloewen-msft** [comment]
Could you please file a bug report for this issue? The template there has the info we need to help diagnose and fix your issue. Could you also be sure to include the WSL networking logs [described here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) as part of your issue? As of right now this report isn't actionable for us, so I'll close it out, but I'll look out for another one, thank you!
