### ISSUE TITLE
I Can't Launch my WSL2 anymore

### ISSUE THREAD

**Issue by SJoJoK** [microsoft/WSL#7012]
### Windows Build Number

Microsoft Windows [Version 10.0.21390.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

I just reboot my computer and then cant use anything about my WSL2
It takes longer time on connecting when i use VSCode than yesterday, so i realize there must be some problem
Then i launch my windows terminal, but this happens
![image](https://user-images.githubusercontent.com/50450335/120436401-75540380-c3b1-11eb-848c-f2f15cc27f5e.png)
The Chinese Text means 
"No response from the virtual machine or container was received, and the operation timed out."
"Progress exited, Code is 4294967295"
Then I want to access my file in the WIndows File Explorer, but it just loading...with a ERROR as last
"Try to access invalid address"
Well.. After many times of reboot and relaunch the WSL service, it just keep wrong

### Expected Behavior

I WANT TO RE-CONNECT TO MY WSL.

### Actual Behavior

cant launch it

**Comment by SJoJoK** [comment]
Well...A weird solution is that I install Ubuntu-18.04 in MS store, it installed correctly, and then my 20.04 just works well.
Now all my files back, but i think the bug still exists

**Comment by fl4m3x** [comment]
@SJoJoK Just install and configure 18.04 for the first time?

**Comment by SJoJoK** [comment]
> @SJoJoK Just install and configure 18.04 for the first time?

Yes, install it from MS Store, after setting the username and password, i found that 20.04 can be launched

**Comment by DeletorDev** [comment]
Same issue for me, but when I was trying to navigate to /mnt/c the message error was "Input/Output Error"

Helped me below solution commented in issue[ #4122](https://github.com/microsoft/WSL/issues/4122)

```
powershell -> wsl --shutdown
powershell -> wsl
```

**Comment by therealkenc** [comment]
> "No response from the virtual machine or container was received, and the operation timed out."

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Ref #6627.

**Comment by SJoJoK** [comment]
> Same issue for me, but when I was trying to navigate to /mnt/c the message error was "Input/Output Error"
> 
> Helped me below solution commented in issue[ #4122](https://github.com/microsoft/WSL/issues/4122)
> 
> ```
> powershell -> wsl --shutdown
> powershell -> wsl
> ```

Shutdown wasnt work for me.. but thanks

**Comment by SJoJoK** [comment]
> > "No response from the virtual machine or container was received, and the operation timed out."
> 
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Ref #6627.

@therealkenc To recreate my problem I need to shutdown (press the button to power off) my computer , idk whether the capturing keeps working or not during recreating the bug ... sorry for that

**Comment by SJoJoK** [comment]
I may find the cause of this bug: Ever time after a **Force Shutdown**(press the button to power off), the WSL goes wrong. However, normally shut down the computer from Window Start Menu doesnt lead to the bug. Maybe the **Force Shutdown** broke some files that WSL needed.

**Comment by therealkenc** [comment]
>  idk whether the capturing keeps working or not during recreating the bug

Your reproduction step was:

> Then i launch my windows terminal, but this happens

When following the [collect logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) instructions, start recording prior to "then I launch my windows terminal".

**Comment by SJoJoK** [comment]
> > idk whether the capturing keeps working or not during recreating the bug
> 
> Your reproduction step was:
> 
> > Then i launch my windows terminal, but this happens
> 
> When following the [collect logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) instructions, start recording prior to "then I launch my windows terminal".

Got it, i will do it when im available, thank you

**Comment by therealkenc** [comment]
> so i will collect the log next time when i must force it shut down

Please open a new issue if/when the problem manifests again.
