### ISSUE TITLE
Problem with network

### ISSUE THREAD

**Issue by bouseman** [microsoft/WSL#7015]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1023]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

no

### Repro Steps

just right after installation type "sudo apt update"

### Expected Behavior

no problem with updating

### Actual Behavior

isaev@MSC:~$ sudo apt update
[sudo] password for isaev:
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 https://download.docker.com/linux/ubuntu focal InRelease
  Temporary failure resolving 'download.docker.com'

### Diagnostic Logs

лог https://yadi.sk/d/yoXH5H9PqCRe8Q

**Comment by mabasic** [comment]
On Windows 10 Pro, dns resolution works inside wsl2, but on Windows 10 enterprise it does not work. They are both the same versions and everything.

Which version are you using?

**Comment by OneBlue** [comment]
Thanks for reporting @bouseman.

Can you please follow the [Networking issues](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) section and share the output, along with wsl.etl ?

**Comment by sleepm** [comment]
vim /etc/resolv.conf
change your nameserver to your router, like '192.168.2.1'
then test
dig google.com
