### ISSUE TITLE
Chrome crashing due to /dev/shm filesystem lacking execution permissions for Docker Desktop and the WSL2 setup.

### ISSUE THREAD

**Issue by theddub** [microsoft/WSL#7018]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

docker-desktop

### Other Software

Docker Desktop(Windows) 3.3.3(My issue works with using the Hyper-V backend but not the WSL2 backend)
Selenium Grid 4

### Repro Steps

I believe there is a defect/issue with the /dev/shm filesystem which causes Chrome(and Edge) to crash while in a Docker container AND executed from a WSL2 distro. This only happens in a Windows environment and Docker Desktop etc..
I say this because we get a message from the remote Selenium Grid Docker from the Dynamic Grid container(Execution with Standalone roles OR Execution with Hub & Node roles etc…) saying Chrome has crashed in the standalone Chrome container:

"Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)"

Usually when we get a Chrome has “crashed” error it’s due to the /dev/shm filesystem. Either not in the right spot, not -v mounted in the container or not big enough. Obviously we have fixed this before doing the increasing the  --shm-size flag or -v /dev/shm:/dev/shm or -disable-dev-shm-usage etc.. However, when executing a standalone Chrome container from Selenium Grid 4, the Dynamic Grid feature to be exact, we encounter a new version of the Chrome has “crashed” error.
If we run the Dynamic Grid in Linux w/Selenium Grid 4 and Docker ….we do not have this or any errors. If we run the Dynamic Grid in Windows with Docker Desktop and Docker Engine using the Hyper-V backend and DockerDesktopVM….we do not have any errors. If we run the Dynamic Grid in Windows with Docker Desktop and Docker Engine using WSL2 backend(and the docker-desktop WSL2 distro)THEN we get this error and ONLY then do we get the above error. I can further elaborate on the error and what we discovered.
What we see is that the /dev/shm size exists and is sufficiently large enough for Chrome to startup in ALL cases. But what my coworker discovered is that the PERMISSIONS for the /dev/shm filesystem is different for the WSL2 setup versus the Hyper-V backend with Docker Desktop.
Obviously Chrome isn’t ready to start up in the small lifespan of the WSL2 supported container, but we tried it and received the information about the permissions to look into it further:
 
![image](https://user-images.githubusercontent.com/14294692/120680139-324c6b80-c457-11eb-998f-b4fafde6a1a5.png)

“Caused by incorrect permission on /dev/shm” etc…
Compare the WSL2 supported Chrome container /dev/shm permissions to the Hyper-V supported Chrome container we get:
WSL2(Chrome crashes):

![image](https://user-images.githubusercontent.com/14294692/120680166-3bd5d380-c457-11eb-8abc-f902fdc7f85d.png)

 
Versus Hyper-V(Chrome works):

![image](https://user-images.githubusercontent.com/14294692/120680194-455f3b80-c457-11eb-9b41-bea11a7f462c.png)

 
So where it work on Hyper-V, we have x(execute) permissions for all 3 User, Group and Other. Whereas we do not have execute permissions for any of the 3 categories in the WSL2 setup. 
I don’t think the issue lies with Selenium Grid 4(or Selenium Grid for that matter) as they are just executing Docker commands in their code and it works for Linux and Hyper-V supported Docker Desktop on Windows. Since we believe this is a permissions issue with the “Linux” backed WSL2, we are unsure if the root cause or issue lies with Docker Desktop and how it’s docker-desktop WSL2 distro interacts with the WSL2 or if this possible permissions issue lies with WSL2 in the same said interaction. I personally suspect it has to do more with the WSL2. Thanks for any support and/or information.

### Expected Behavior

/dev/shm has "execution" permissions in the standalone Chrome container from Selenium Grid(This is with Docker Desktop using "legacy Hyper-V backend"

![image](https://user-images.githubusercontent.com/14294692/120679891-eb5e7600-c456-11eb-8a28-31ff39a02e0d.png)

### Actual Behavior

/dev/shm doesn't have "execution" permissions in the standalone Chrome container from Selenium Grid(This is with Docker Desktop using WSL2 backend)

![image](https://user-images.githubusercontent.com/14294692/120679822-d4b81f00-c456-11eb-8e56-1c1e15bcdba5.png)

### Diagnostic Logs

Diagnostics provided in Repro Steps.

**Comment by therealkenc** [comment]
> Response code 500. Message: unknown error: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)

What is the sequence of CLI repro steps from initial WSL2 distribution install to manifest the above error.

**Comment by theddub** [comment]
Hi @therealkenc . Thank you for the response. We are using Docker Desktop with the WSL2 integration enabled on Windows 10. This works with using the "legacy" Hyper-V backend in Docker Desktop. The newer Docker Desktop way one would use the WSL2 integration in Docker Desktop which has a WSL2 distro that it using call Docker Desktop and docker desktop data. I wasn't sure whether to log this issue against the WSL2 maintainers or Docker Desktop, so I logged it in both places.

**Comment by theddub** [comment]
Can you please explain why this issue was closed? It's clearly either an issue with Docker Desktop or WSL2...

**Comment by therealkenc** [comment]
> May I ask why this issue was closed?

The issue was closed due to an absence of steps which would manifest the error `"Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.`

> I clearly provided repro steps

What was provided was "I believe there is a defect/issue with the /dev/shm filesystem which causes..." 

I _did_ try play "guess the repro" before asking. Which I figured, _might_ be something like:

```
PS C:\> docker.exe run selenium/standalone-chrome
PS C:\> docker.exe exec -it container_name bash
```

But that guess did not manifest your `ls -al /dev` permission screencap.

![image](https://user-images.githubusercontent.com/7049700/121120388-4f27cc80-c7d2-11eb-9669-e971356a8acd.png)

**Comment by theddub** [comment]
You requested, "What is the sequence of CLI **repro steps from initial WSL2 distribution** install to manifest the above error." CLI repro steps from initial WSL2 distribution **install**. I do not have the docker-desktop WSL2 distro install steps because that is handled by Docker Desktop when it gets installed.

Had you mention Docker CLI steps, I could have provided that. In my original post I did mention that I was using Selenium Grid to setup Docker containers. Selenium Grid 4 with the beta "Dynamic Grid" feature. I mentioned that with Selenium Grid 4 and Docker Desktop not using the WSL2 backend and using the "legacy" Hyper-V backend, the shm file permissions are there and correct but not with Docker Desktop using the WSL2 backend , ie...docker-desktop WSL2 distro.

Those steps are as follows: 
(from: https://github.com/seleniumhq/docker-selenium/)
Under "**Execution with Standalone roles**":

1)docker run --rm --name selenium-docker -p 4444:4444 \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v /path/on/your/host/machine:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-20210608

NOTE: The config.toml setup is the one under "**Configuration example**" with only the standalone Chrome container

2)Then sending a webdriver request to http://localhost:4444 (I do this in Java code with the Serenity-Cucumber CLI executing with Serenity BDD in java code, but there are simpler ways I'm sure to trigger a webdriver request) (But it's:

 log.info("Serenity exit status: " + Main.run(options, ClassLoader::getSystemClassLoader)); (ie.. import net.serenitybdd.cucumber.cli.Main;)

That will spring up a dynamic "standalone Chrome container" (selenium/standalone-chrome:4.0.0-beta-4-20210608 from the config.toml) which is the logs I provided in my original post for the 10 seconds or so that container runs before crashing and exiting:

"Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)"

NOTE: Because I'm sending webdriver requests via the serenity-cucmber CLI in Java, The Selenium Grid docs says

          Point your WebDriver tests to http://localhost:4444 *

          (Optional) To see what is happening inside the container, head to http://localhost:7900 (password is secret).

          Grid 3 used "/wd/hub", while it should also work, it is no longer required

Since I've only ever ran against http://localhost:4444 or http://localhost/wd/hub on Selenium via JUNIT directly or Serenity-Cucumber runner programmatically using those tools in Java,  I don't know desired JSON payload structure to initiate a POST request maybe so you could get the second , Chrome standalone container kicked off from a webdriver request. I'm hoping you'll work with me on this one.


3)If during those 10 seconds of execution time one looks at the logs in the container, one clicks on the CLI interaction in Docker Desktop on the randomly named spun up standalone Chrome docker container....ie.....the container is already running, spun up from the dynamic "standalone-docker"  "parent" container. I know CLI wise that command would be similar to docker.exe exec -it container_name bash if one had to start the container themselves, but since this is the Dynamic Selenium Grid 4 Dynamic Grid feature it spins it up for you and Docker Desktop easily allows one to open a CLI window after the container is already running. If the CLI on the already running container is opened, one can run or  try to run google chrome(I know if would have other issues but this will lead to the idea of not having sufficient file privileges, One gets:

![image](https://user-images.githubusercontent.com/14294692/121198280-40233780-c82f-11eb-9cec-94c9c8a6234b.png)

“Caused by incorrect permission on /dev/shm” etc…

4)That leads one to run an ls command on the dev file structure

ls -la /dev

Which shows no executable file permissions for /dev/shm for any of the 3 categories, group, user or other

![image](https://user-images.githubusercontent.com/14294692/121199111-e4a57980-c82f-11eb-8655-a9b5b1d52c67.png)

NOTE: So this issue only arises with Docker Desktop w/WSL2 and Windows 10 when a container spins up another container that run Chrome in the other spunned up container

If instead all this , 1-4, is ran with Docker Desktop and Hyper-V instead of WSL2 integration, everything works, Chrome launches just fine etc...no errors and from step 4 inspecting /dev/shm we get:

![image](https://user-images.githubusercontent.com/14294692/121199424-26362480-c830-11eb-80cc-812bc4e15255.png)

**Comment by theddub** [comment]
Btw the updated and edited and re-edited post above will make more sense then the original form of immediately above reply

**Comment by theddub** [comment]
@therealkenc Is there any update on this? Does it needs further repro steps that I can give(I see the "needs-repro" tag continues to be on the issue)

**Comment by theddub** [comment]
@therealkenc I PR'd a "fix" for the selenium/docker repo but I feel like it is just part of the problem. 1) On 1 hand, the WSL2 Docker Desktop distro works(and has correct executable file permission for /dev/shm) with other Linux containers that I've tried for a "child" container from the Selenium Dynamic Grid works but does not with the standalone-chrome container as a "child" container. 2)In reverse, on the other hand, the standalone-chrome container works with Docker Desktop and the Hyper-V legacy engine, Docker Desktop VM, whereas it doesn't work with the WSL2 engine and distro. My "fix" makes standalone-chrome test container work as a "child" container for the Selenium Dynamic Grid but I still feel the there is something to be done and fixed in the WSL2 kernel as well and my "fix" will just "mask" the issue there, at least for the selenium/docker repo material. 

I think it's something along the lines of 1)If the  executable file permission is not EXPLICITly stated in the docker container;, then when said container is launched from another container("parent") via the Docker daemon, then as a type or form of inheritance, the "child" container doesn't have executable permission on /dev/shm whereas it does as a "parent" container but not "child". Since the image is already built, my fix here: https://github.com/SeleniumHQ/docker-selenium/pull/1334 for selenium/docker explicitly assigns executable permissions for /dev/shm which results in it having executable permissions as a "child" container and just not the "parent" container.

@therealkenc You can close this issue, but I feel like it still exists as a "combination of causes" problem in the WSL2 kernel. I don't think it's the Docker-desktop WSL2 distro because I also tried the Ubuntu WSL2 distro and it's problematic there too as well with the same problem, and where it also works great in Linux or in the Hyper-V engine (Linux VM) for Docker Desktop, I leave with the message that I believe it resides here in the WSL2 kernel.
