### ISSUE TITLE
File download to WSl disto

### ISSUE THREAD

**Issue by prabhumns** [microsoft/WSL#7024]
**Is your feature request related to a problem? Please describe.**
I try to download a file from edge on Windows and I am choosing where to save the file. I am unable to directly save the file inside WSL distro. I have to save the file in local partition and then put the copy paste the file into WSL distro using windows file explorer,

**Describe the solution you'd like**
I want to be able to directly download a file into WSL distro.

**Describe alternatives you've considered**

**Additional context**

**Comment by therealkenc** [comment]
Type `\\wsl$` in the `File name:` dialog and navigate to your distro and path inside the distro. For example, a save-link-as on WSL's README.md below.

![image](https://user-images.githubusercontent.com/7049700/120874513-d0295e80-c55b-11eb-961f-4317861b7eed.png)

![image](https://user-images.githubusercontent.com/7049700/120874635-75dccd80-c55c-11eb-80c6-fb02e9fdf56b.png)
