### ISSUE TITLE
scp/ssh failures

### ISSUE THREAD

**Issue by ismailhkose** [microsoft/WSL#7030]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 20.04.2 LTS

### Other Software

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
Windows Terminal Version: 1.8.1444.0

**WSL2:**
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
Ubuntu 20.04.2 LTS

**Remote Machine:**
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
Ubuntu 18.04.5 LTS"
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 10:37:52) Included patches: 1-1303

### Repro Steps

scp <SSH_USER>@<REMOTE_HOST>:~/.tmux.conf ~
.tmux.conf                                                                                                            0%    0     0.0KB/s   --:-- ETA

### Expected Behavior

It's supposed to copy file as seen following. 
.tmux.conf                                                                                                          100% 7922   483.7KB/s   00:00

### Actual Behavior

scp doesn't copy file from remote host, and gets stuck at copying until I interrupt it with Ctrl + C.
.tmux.conf                                                                                                            0%    0     0.0KB/s   --:-- ETA

Another problem which I believe it's connected to this problem;
ssh can connect, and it disconnects or terminal hangs when I open a file on remote machine using vim. Ubuntu in Windows Terminal doesn't response at all. However, I don't see any issue when I use powershell terminal with ssh/scp/vim with remote machine.

I can even copy a file from WSL to remote machine. However, I can't copy file from remote machine to WSL. I have never had such an issue before, while using Ubuntu 18.04 on WSL. It's frustating problem. I wasted lots of time to troubleshoot and research about this.

### Diagnostic Logs

~ scp -v <SSH_USER>@<REMOTE_HOST>:~/.tmux.conf ~
Executing: program /usr/bin/ssh host <REMOTE_HOST>, user <SSH_USER>, command scp -v -f ~/.tmux.conf
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to <REMOTE_HOST> [<REMOTE_IP>] port 22.
debug1: Connection established.
debug1: identity file /home/<SSH_USER>/.ssh/id_rsa type 0
debug1: identity file /home/<SSH_USER>/.ssh/id_rsa-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_dsa type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_dsa-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ecdsa type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ed25519 type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ed25519-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ed25519_sk type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_xmss type -1
debug1: identity file /home/<SSH_USER>/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to <REMOTE_HOST>:22 as '<SSH_USER>'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:P8KBlLGCjrPiTDLzBYA2i+5FdpH7EVL8TegEwi+DWNM
debug1: Host '<REMOTE_HOST>' is known and matches the ECDSA host key.
debug1: Found key in /home/<SSH_USER>/.ssh/known_hosts:2
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_rsa RSA SHA256:<SHORT_KEY>
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_dsa
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_ecdsa
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_ecdsa_sk
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_ed25519
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_ed25519_sk
debug1: Will attempt key: /home/<SSH_USER>/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received

      ____              _    _      _ _         _              ____
     / / /_____        | |  | |    | | |       | |        _____\ \ \
    / / /______|_____  | |__| | ___| | | ___   | |  _____|______\ \ \
   < < < _____|______| |  __  |/ _ \ | |/ _ \  | | |______|_____ > > >
    \ \ \______|       | |  | |  __/ | | (_) | |_|       |______/ / /
     \_\_\             |_|  |_|\___|_|_|\___/  (_)             /_/_/

debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /home/<SSH_USER>/.ssh/id_rsa RSA SHA256:<SHORT_KEY>
debug1: Server accepts key: /home/<SSH_USER>/.ssh/id_rsa RSA SHA256:<SHORT_KEY>
debug1: Authentication succeeded (publickey).
Authenticated to <REMOTE_HOST> ([<REMOTE_IP>]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = C.UTF-8
debug1: Sending command: scp -v -f ~/.tmux.conf
Sending file modes: C0664 7922 .tmux.conf
Sink: C0664 7922 .tmux.conf

.tmux.conf                                                                                                            0%    0     0.0KB/s   --:-- ETA

~ scp -vvv <USER>@<HOST_NAME>:/home/<USER>/.tmux.conf .
Executing: program /usr/bin/ssh host <HOST_NAME>, user <USER>, command scp -v -f /home/<USER>/.tmux.conf
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "<HOST_NAME>" port 22
debug2: ssh_connect_direct
debug1: Connecting to <HOST_NAME> [<REMOTE_IP>] port 22.
debug1: Connection established.
debug1: identity file /home/<USER>/.ssh/id_rsa type 0
debug1: identity file /home/<USER>/.ssh/id_rsa-cert type -1
debug1: identity file /home/<USER>/.ssh/id_dsa type -1
debug1: identity file /home/<USER>/.ssh/id_dsa-cert type -1
debug1: identity file /home/<USER>/.ssh/id_ecdsa type -1
debug1: identity file /home/<USER>/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/<USER>/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/<USER>/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/<USER>/.ssh/id_ed25519 type -1
debug1: identity file /home/<USER>/.ssh/id_ed25519-cert type -1
debug1: identity file /home/<USER>/.ssh/id_ed25519_sk type -1
debug1: identity file /home/<USER>/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/<USER>/.ssh/id_xmss type -1
debug1: identity file /home/<USER>/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to <HOST_NAME>:22 as '<USER>'
debug3: hostkeys_foreach: reading file "/home/<USER>/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/<USER>/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from <HOST_NAME>
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:P8KBlLGCjrPiTDLzBYA2i+5FdpH7EVL8TegEwi+DWNM
debug3: hostkeys_foreach: reading file "/home/<USER>/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/<USER>/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from <HOST_NAME>
debug3: hostkeys_foreach: reading file "/home/<USER>/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/<USER>/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from <REMOTE_IP>
debug1: Host '<HOST_NAME>' is known and matches the ECDSA host key.
debug1: Found key in /home/<USER>/.ssh/known_hosts:2
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/<USER>/.ssh/id_rsa RSA SHA256:<SSH_SHORT_KEY>
debug1: Will attempt key: /home/<USER>/.ssh/id_dsa
debug1: Will attempt key: /home/<USER>/.ssh/id_ecdsa
debug1: Will attempt key: /home/<USER>/.ssh/id_ecdsa_sk
debug1: Will attempt key: /home/<USER>/.ssh/id_ed25519
debug1: Will attempt key: /home/<USER>/.ssh/id_ed25519_sk
debug1: Will attempt key: /home/<USER>/.ssh/id_xmss
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 53
debug3: input_userauth_banner

      ____              _    _      _ _         _              ____
     / / /_____        | |  | |    | | |       | |        _____\ \ \
    / / /______|_____  | |__| | ___| | | ___   | |  _____|______\ \ \
   < < < _____|______| |  __  |/ _ \ | |/ _ \  | | |______|_____ > > >
    \ \ \______|       | |  | |  __/ | | (_) | |_|       |______/ / /
     \_\_\             |_|  |_|\___|_|_|\___/  (_)             /_/_/

debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/<USER>/.ssh/id_rsa RSA SHA256:<SSH_SHORT_KEY>
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/<USER>/.ssh/id_rsa RSA SHA256:<SSH_SHORT_KEY>
debug3: sign_and_send_pubkey: RSA SHA256:<SSH_SHORT_KEY>
debug3: sign_and_send_pubkey: signing using rsa-sha2-512 SHA256:<SSH_SHORT_KEY>
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to <HOST_NAME> ([<REMOTE_IP>]:22).
debug2: fd 4 setting O_NONBLOCK
debug2: fd 5 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env HOSTTYPE
debug1: Sending env LANG = C.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env PATH
debug3: Ignored env TERM
debug3: Ignored env WSLENV
debug3: Ignored env WT_SESSION
debug3: Ignored env WT_PROFILE_ID
debug3: Ignored env WSL_INTEROP
debug3: Ignored env NAME
debug3: Ignored env HOME
debug3: Ignored env USER
debug3: Ignored env LOGNAME
debug3: Ignored env SHELL
debug3: Ignored env WSL_DISTRO_NAME
debug3: Ignored env SHLVL
debug3: Ignored env PWD
debug3: Ignored env OLDPWD
debug3: Ignored env ZSH
debug3: Ignored env PAGER
debug3: Ignored env LESS
debug3: Ignored env LSCOLORS
debug3: Ignored env LS_COLORS
debug3: Ignored env _
debug1: Sending command: scp -v -f /home/<USER>/.tmux.conf
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: rcvd ext data 42
Sending file modes: C0664 7922 .tmux.conf
debug2: channel 0: written 42 to efd 6
Sink: C0664 7922 .tmux.conf
.tmux.conf                                                                                                                                                                                                0%    0     0.0KB/s   --:-- ETA

### Interrupted

^Cdebug3: send packet: type 1
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 4/5/6 sock -1 cc -1)

debug1: fd 0 clearing O_NONBLOCK
debug3: fd 1 is not O_NONBLOCK
Killed by signal 2.

**Comment by ismailhkose** [comment]
This looks Ubuntu 20.04 specific issue on WSL. Ubuntu 18.04 on WSL looks fine.

**Comment by Petros626** [comment]
I did the following, which worked for me (Windows 10 & WSL2):
1. `sudo nano /etc/ssh/ssh_config`
2. Under section **Host*** add **ServerAliveInterval 5** (I guess any value is okay?)
3. `sudo nano /etc/ssh/sshd_config`
4. Near the end of the file search for: **ClientAliveInterval 60**; **TCPKeepAlive yes**; **ClientAliveCountMax 10000**
5. `service ssh restart`
6. `ssh nameofmachine@xxx.xxx.xxx.xx`
