### ISSUE TITLE
Can't access WSL2-Ubuntu-20.04's file system by "\\wsl$Ubuntu-20.04"

### ISSUE THREAD

**Issue by atwwww** [microsoft/WSL#7039]
I **installed** the Ubuntu-20.04 of WSL2 through Microsolft Store.
**Then in the subsystem**:
"sudo apt update" 
...
"sudo apt upgrade"
...

**After that,**
the explorer of windows10 will always be loading state when I type "\\\wsl$\\Ubuntu-20.04" in its search box,
seems that it can't find the Ubuntu-20.04's files.

**However,**
I can successfully access the Ubuntu-18.04's files by typing "\\\wsl$\\Ubuntu-18.04"

Is it a Bug of WSL2-Ubuntu-20.04?

**Comment by fetherolfjd** [comment]
I need to access my distros via `\\wsl$\Ubuntu-20.04`. Note the slash between the dollar sign and the distro name. Does that fix your issue?

**Comment by therealkenc** [comment]
What is the output, from a powershell or CMD prompt:
```
C:\> cmd.exe /c ver
C:\> wsl.exe -l -v
```

**Comment by atwwww** [comment]
The prompts are like the picture showing.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月8日(星期二) 上午6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/WSL] Can&#39;t access WSL2-Ubuntu-20.04&#39;s file system by &quot;\\wsl$Ubuntu-20.04&quot; (#7039)

**Comment by atwwww** [comment]
@fetherolfjd 
It didn't work...

**Comment by atwwww** [comment]
@therealkenc 
The prompts are as follows:

C:\> cmd /c ver
Microsoft Windows [version 10.0.19042.985]

C:\ wsl -l -v
  NAME            STATE           VERSION
* kali-linux      Stopped         2
  Ubuntu-18.04    Stopped         2
  Ubuntu-20.04    Running         2

**Comment by therealkenc** [comment]
> Is it a Bug of WSL2-Ubuntu-20.04?

All things being equal, WSL proper doesn't know one distribution from the next. And the distributions (f.e. Ubuntu-20.04) isn't responsible for sharing `\\wsl$\Ubuntu-20.04`.

![image](https://user-images.githubusercontent.com/7049700/121134452-43470500-c7e8-11eb-96d5-36c0e754a9ec.png)

If `kali-linux` and `Ubuntu-18.04` both work, but `Ubuntu-20.04` "always be loading state", one thing to try on a lark is install [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6) (sic) from the store and see how that fares.
