### ISSUE TITLE
change the language of the distribution (ubuntu 20.04) ?

### ISSUE THREAD

**Issue by Sid281216** [microsoft/WSL#7044]
### Windows Build Number

Microsoft Windows [version 10.0.19043.1023]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

sudo update-locale LANG=fr_FR.UTF8

### Expected Behavior

/

### Actual Behavior

*** update-locale: Error: invalid locale settings:  LANG=fr_FR.UTF8

### Diagnostic Logs

In official wsl docs(https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-change-the-display-language-of-wsl-) it says we can change the language of wsl. We will have the exact same change as if in a real ubuntu installation ? 
I used this command to install the needed files : sudo apt-get install language-pack-XX language-pack-XX-base manpages 
is it the right one we should use on wsl 2  ?
Regards

**Comment by Biswa96** [comment]
I think it's `UTF-8`.

**Comment by Sid281216** [comment]
Hi, I tried with the "-" and it seems to be the same thing. Actually I'm able to change the language after doing sudo apt-get install language-pack-XX language-pack-XX-base manpages, otherwise refer to the questions I asked 

Thanks
