### ISSUE TITLE
can not show infomation properly after use command clear the screen

### ISSUE THREAD

**Issue by avboy1337** [microsoft/WSL#7047]
### Windows Build Number

Microsoft Windows [版本 10.0.17763.1971]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-17763-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1432-Microsoft Mon Aug 18 18:18:00 PST 2020

### Distro Version

Release:        20.04

### Repro Steps

sudo apt update
and after update is over
try 
list file as ls
then nothing showed because right scroling bar is mis-scrolled

### Expected Behavior

show info after command

### Actual Behavior

command output shows not ok

**Comment by therealkenc** [comment]
> then nothing showed because right scroling bar is mis-scrolled
> 4.4.0-17763-Microsoft 

WSL does not control the behavior of the terminal scrollbar. Suggestion would be to try updating to Windows 20H2 (aka build 19043) using [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab), and retry your scenario from a clean install of your distribution.

**Comment by avboy1337** [comment]
i think you are right , and i am going to have a try of 20H
