### ISSUE TITLE
Support SSH_AUTH_SOCK Unix Domain Sockets for Windows

### ISSUE THREAD

**Issue by WSLUser** [microsoft/WSL#7050]
**Is your feature request related to a problem? Please describe.**

Many Win32-OpenSSH users need gpg and gpg-agent support opening a Unix Domain Socket in Windows for use with SSH. However, this appears to fail as Win32-OpenSSH does not support Unix Domain Sockets when configured in SSH_AUTH_SOCK. Per  Win32-OpenSSH team, the socket support should be raised here. Once implemented in Windows, WIn32-OpenSSH can be updated to make use of it. Since we have limited support of AF_Unix, I think the changes needed to add this likely go in the same place that the AF_Unix support lives in the Windows source code.

**Describe the solution you'd like**
Allow usage of the SSH_AUTH_SOCK on Windows.

**Describe alternatives you've considered**

There are ways to bridge this using third-party programs such as https://github.com/benpye/wsl-ssh-pageant and configuring gpg and gpg-agent to run in pageant mode and using the aforementioned program to open a named pipe that can work with OpenSSH for Windows when set to SSH_AUTH_SOCK.

**Additional context**
Related: https://github.com/PowerShell/Win32-OpenSSH/issues/1761 and https://github.com/PowerShell/Win32-OpenSSH/issues/1024

This request is to be routed to the Linux Systems Group which WSL team is part of in order to get this feature request implemented.

**Comment by WSLUser** [comment]
@craigloewen-msft Was this issue ever brought up to anyone?

**Comment by craigloewen-msft** [comment]
Just pinged folks internally about this, people are OOF until the new year. I see you've already filed this at the Win32-OpenSSH repo https://github.com/PowerShell/Win32-OpenSSH/issues/1761 which seems like the right place to track this. I've let folks know about this feature request and pointed them to the Win32-OpenSSH thread which is where we should track this (As it isn't directly related to WSL). So the relevant folks have been pinged to the right issue, and I'll close this issue out for bookkeeping on the WSL repo. Thanks for filing!

**Comment by WSLUser** [comment]
Great thanks. Yeah I expected that many people will be OOF until next year. Just wanted to be sure it's on the roadmap.
