### ISSUE TITLE
Running `wsl <command>` from windows command line is missing environment variables

### ISSUE THREAD

**Issue by Mkassabov** [microsoft/WSL#7053]
### Windows Build Number

10.0.19042 Build 19042

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

from the windows command line running

`wsl echo $PATH`

### Expected Behavior

print the $PATH environment variable (e.g. `echo $PATH` from within wsl)

### Actual Behavior

print an empty line

**Comment by microhobby** [comment]
You need to use single quote to solve the WSL environment instead a Powershell variable. Example:

![image](https://user-images.githubusercontent.com/2633321/121631693-f5cfcf80-ca55-11eb-9419-ac3d05d4e6ec.png)

**Comment by microhobby** [comment]
You need to use single quote to solve the WSL environment instead a Powershell variable. Example:

![image](https://user-images.githubusercontent.com/2633321/121631929-6aa30980-ca56-11eb-9c4e-2426d986ab51.png)

**Comment by therealkenc** [comment]
By-design Powershell. In the OP you've expanded `$PATH` (which expands to an empty string... except when it doesn't).

![image](https://user-images.githubusercontent.com/7049700/121738942-c64db100-caaf-11eb-98a4-11c9a410dcb3.png)
