### ISSUE TITLE
[GPU and pytorch related]: after cuda installation, 'nvcc -V' works fine but 'nvidia-smi' returns errors. While using pytorch (python), 'torch.cuda.is_available()' always returns 'false' in wsl.

### ISSUE THREAD

**Issue by qijqij** [microsoft/WSL#7056]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software
python (version 3.8.10) 
   - pytorch package (version 1.7.1)

### Repro Steps

Those are the steps I followed:
1. install cuda on wsl driver (geforce, driver version 470.76) https://developer.nvidia.com/cuda/wsl/download]
2. download cuda toolkit https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=runfile_local
3. run the code shown in step 2: 
     wget https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda_11.3.1_465.19.01_linux.run
     sudo sh cuda_11.3.1_465.19.01_linux.run (unselect the driver and then install)
4. add path in ~/.bashrc
5. nvcc -V to check the installation
![image](https://user-images.githubusercontent.com/72549351/121693582-ddb28b80-cafb-11eb-8b0f-bce574eb93e9.png)

This is the stage I am at:
6. nvidia-smi returns error (details in the 'Actual Behavior' section).
7. While using the pytorch package in python, 'torch.cuda.is_available()' always returns 'false' in wsl (ubuntu). But it works perfectly fine in windows, e.g. returns 'true'.

### Expected Behavior

Nvidia-smi does not return the expected message, like:
![image](https://user-images.githubusercontent.com/72549351/121695812-0045a400-cafe-11eb-841a-581e4fd257ae.png)

While using pytorch (python):
'torch.cuda.is_available()' returns 'true'.
![image](https://user-images.githubusercontent.com/72549351/121889723-2a8ca100-cd4c-11eb-85c2-bc813aa1b314.png)

### Actual Behavior

nvidia-smi returns this error:
![image](https://user-images.githubusercontent.com/72549351/121693718-f7ec6980-cafb-11eb-887b-62d0d7604b2d.png)

It does not return the installed nvidia-smi, driver and cuda version after following the steps list above. 

Additionally, the provided choices do not include the 470 version. But installing 'sudo apt install nvidia-utils-460-server' returns 'nvidia-smi has failed because it couldn't communicate with the nvidia driver. make sure that the latest nvidia driver is installed and running.'

While using pytorch (python):
'torch.cuda.is_available()' returns 'false'.
![image](https://user-images.githubusercontent.com/72549351/121889055-4e031c00-cd4b-11eb-969a-48f5701ba4ae.png)

**Comment by tz3** [comment]
I have the same issue, at the same time, `nvidia-smi.exe` responds perfectly

**Comment by Jiongqi** [comment]
> I have the same issue, at the same time, `nvidia-smi.exe` responds perfectly

Thank you for the reply. 'nvidia-smi.exe' returns the expected figure, but I am still struggling in using the GPU. I am trying to use the cuda installed to train a model using the pytorch package. But torch.cuda.is_available() still returns 'false' in ubuntu (it returns 'true' in windows). Did you meet a similar issue before? Could I ask how did you solve it?

**Comment by kuramin** [comment]
Hi, I have the same problem. Did you find any explanation or solution? Thanks)

**Comment by Ayke** [comment]
If your `nvidia-smi` is not available, it means your Ubuntu in WSL2 cannot find Windows CUDA. The following reasons might be the cause:

Windows version too low (Win 10 20145+ is needed)
Ubuntu Kernel version too low (`cat /proc/version` should be 5+)

To verify that, in your WSL2 try access `ll /usr/lib/wsl/lib`. If the directory doesn't exist or there's no `nvidia-smi` (without the .exe extension), then my above guess is confirmed.

Or in windows check `C:\Windows\System32\lxss\lib` (replace C:\Windows with your Windows directory if needed), it should be just like `/usr/lib/wsl/lib`, you should see `libcuda.so` and `nvidia-smi`. If you don't see it, it means your Windows/WSL/Ubuntu kernel version is too low.

You may have my notes for reference: https://gist.github.com/Ayke/5f37ebdb84c758f57d7a3c8b847648bb

**Comment by MohsenFazaeli** [comment]
I have same Issue in actual installation of ubuntu 22.04. Once I isntall nvidia-utils nvcc crashes and vise versa.
