### ISSUE TITLE
ssh -T git@github.com hanging after showing "open confirm rwindow 32000 rmax 35000" message

### ISSUE THREAD

**Issue by aaronamm** [microsoft/WSL#7058]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1055]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 18.04

### Other Software

- OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
- git version 2.17.1

### Repro Steps

- Setup a new SSH key from GitHub tutorial:
  - https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
  - https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
- Test SSH connection with `ssh -T git@github.com -vvv` command.
- ssh printed details log and get hanging on a line with message `debug2: channel 0: open confirm rwindow 32000 rmax 35000`

### Expected Behavior

I should get successful messages after running `ssh -T git@github.com -vvv`
For example:
```
Hi aaronamm! You've successfully authenticated, but GitHub does not provide shell access.
debug2: channel 0: written 90 to efd 6
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r43 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
debug3: fd 1 is not O_NONBLOCK
Transferred: sent 3564, received 2868 bytes, in 0.5 seconds
Bytes per second: sent 6567.1, received 5284.6
debug1: Exit status 1

```

### Actual Behavior

Hanging process on the line with message "debug2: channel 0: open confirm rwindow 32000 rmax 35000"

```
.... some messages from the begging are omitted 
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to github.com ([13.250.177.223]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env SHELL
debug3: Ignored env WSL_DISTRO_NAME
debug3: Ignored env WT_SESSION
debug3: Ignored env NAME
debug3: Ignored env PWD
debug3: Ignored env LOGNAME
debug3: Ignored env MOTD_SHOWN
debug3: Ignored env HOME
debug1: Sending env LANG = C.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env WSL_INTEROP
debug3: Ignored env LS_COLORS
debug3: Ignored env LESSCLOSE
debug3: Ignored env TERM
debug3: Ignored env LESSOPEN
debug3: Ignored env USER
debug3: Ignored env SHLVL
debug3: Ignored env WSLENV
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env PATH
debug3: Ignored env HOSTTYPE
debug3: Ignored env WT_PROFILE_ID
debug3: Ignored env OLDPWD
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 32000 rmax 35000 <=== It hangs forever.
```

### Diagnostic Logs

https://aka.ms/AAcwddk

### Third party networking software
- Realtek PCIe GBE Family Controller

### Additional information
I have tried many ways to fix issue by myself but one of them work.
- [Change MTU setting](https://github.com/microsoft/WSL/issues/4698#issuecomment-628682785)
- [Restart LxssManager](https://github.com/microsoft/WSL/issues/3434#issuecomment-445052500)
- Install new Windows OS without docker or any special tools.
- The issue found in both Ubuntu 18.04 & 20.04
- ssh works properly on Windows OS
- When I switch to WSL version 1 with the following command, it works.
```
PS> wsl --set-version Ubuntu-18.04 1
```

**Comment by therealkenc** [comment]
Current custom/tradition is to collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and post (or link) the etl here. Also please identify any third-party networking software that has been installed on Windows if applicable.

Shame the MTU work-around didn’t take.

**Comment by aaronamm** [comment]
@therealkenc Thank for you feedback, I have updated the content to have all information you need.
My main distro is 18.04 so I updated all information to Ubuntu 18.04 and diagnosis log are from 18.04.

Please let me know if you need any further information.
Thanks.

**Comment by aaronamm** [comment]
We fixed the problem. It is because my new router `TP-Link Archer VR2600` cannot handle **IPQoS** properly.
With help from my friend @waf, so thankful to him.

### Here is how we fix the issue:
- We started by using `ssh -T git@github.com -vvv -o ProxyCommand='nc %h %p'` to use `natcat` and it works.
- Then I informed my friend that I've just had a new router. Since he has some experiences with DD-WRT, Tomato router firmware and knows that many routers' firmware have problems with IPQoS.  He recognized it is possible with IPQoS. 
- Therefore, we tried to issue a command `ssh -T git@github.com -vvv -o IPQoS=0` and it works.
- We continue to configure the router, TP-Link Archer VR2600 to enable brandwidth control and it works without setting IPQoS=0. 
However, this causes my internet is not reliable.
- Finally we ended up with setting IPQoS=0x000 in ~/.ssh/config

### Here is how we set our ~/.ssh/config.
- Create and edit a new file with Vi
```
$ vi ~/.ssh/config
```
- Add the following content:
```
Host *
  IPQoS=0x00

```
- Save and quit with
```
:wq
```
- Test ssh command again and it works.
```
 ssh -T git@github.com
```

### Other useful links.
- https://stackoverflow.com/questions/52415943/trying-to-git-clone-via-ssh-but-getting-broken-pipe-error
- https://wiki.debian.org/SSH#Resolution_with_IPQoS_0x00
- https://en.wikipedia.org/wiki/Quality_of_service

I want to close this issue but I still have some questions that people here can help before closing it.
- How is SSH on Windows work? I don't have any issue with IPQoS and my new router.
- How can we make SSH logging message to contain current IPQoS value or having some useful information that can help us figure out the root cause faster.

Thanks.

**Comment by therealkenc** [comment]
> How is SSH on Windows work?

Speculating, probably because the windows port works-around this by not trying ref #1869 ([message](https://github.com/microsoft/WSL/issues/1869#issuecomment-293028871)) #6222.

> How can we make SSH logging message to contain current IPQoS value 

You'd get a more authoritative answer to that in an OpenSSH forum.

**Comment by aaronamm** [comment]
@therealkenc Thanks for your reply. This PR is solved.

**Comment by Ibrahim-Achkar** [comment]
Sorry for commenting on this closed issue but this is the closest I have gotten to solving this issue. @aaronamm Any reason that it worked for me using `ssh -T git@github.com -vvv -o IPQoS=0` but not when adding `Host * IPQoS=0x00` to the config file?
