### ISSUE TITLE
Can't Start WSL2 - Getting [process exited with code 4294967295] after Windows 10 Insider Upgrade to Build 21390

### ISSUE THREAD

**Issue by MaximoTrinidad** [microsoft/WSL#7060]
### Windows Build Number

Microsoft Windows [Version 10.0.21390.1010]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04 (Default)

### Other Software

conda info

     active environment : base
    active env location : /home/maxt/anaconda3
            shell level : 1
       user config file : /home/maxt/.condarc
 populated config files :
          conda version : 4.10.1
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/maxt/anaconda3  (writable)
      conda av data dir : /home/maxt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/maxt/anaconda3/pkgs
                          /home/maxt/.conda/pkgs
       envs directories : /home/maxt/anaconda3/envs
                          /home/maxt/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.24.0 CPython/3.8.5 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    cc8c0abb32

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### Repro Steps

1. Install Windows 10 latest upgrade Build- 21390.
2.The first time, start WSL2 - Ubuntu-20.04 (Default distro)
3. Window Terminal will open, Then wait for the following message which shows only the first time without any error#:
4
![First errorOnce2021-05-17_21-15-37](https://user-images.githubusercontent.com/19892435/121823308-723efa00-cc72-11eb-8dd8-ee58aa3046aa.jpg)

5. Second time you start WSL2 then you get  [process exited with code 4294967295]
6. Try opening the second Distro: Ubuntu-18.04.
7. Same results; [process exited with code 4294967295]

### Expected Behavior

That any WSL installed distro will start without any errors.

### Actual Behavior

Every time you start WSL.. you get:the error [process exited with code 4294967295] 

### Diagnostic Logs

Found this in the Application Event log:
Faulting application name: ubuntu2004.exe, version: 0.0.0.0, time stamp: 0x60c17791
Faulting module name: wslapi.dll, version: 10.0.21390.1, time stamp: 0xfdb7f665
Exception code: 0xc0000005
Fault offset: 0x0000000000014597
Faulting process id: 0x284c
Faulting application start time: 0x01d7608d8c5b25ee
Faulting application path: C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.610.0_x64__79rhkp1fndgsc\ubuntu2004.exe
Faulting module path: C:\WINDOWS\SYSTEM32\wslapi.dll
Report Id: 153cc6b7-82c6-498c-b6c3-7a58f3066a3d
Faulting package full name: CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.610.0_x64__79rhkp1fndgsc
Faulting package-relative application ID: ubuntu2004

-------

Fault bucket 2148407986584012041, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.610.0_x64__79rhkp1fndgsc
P2: praid:ubuntu2004
P3: 0.0.0.0
P4: 60c17791
P5: wslapi.dll
P6: 10.0.21390.1
P7: fdb7f665
P8: c0000005
P9: 0000000000014597
P10: 

Attached files:
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CanonicalGroupLi_84ecc5dc3046c3f83bb13be58b6e533861688f19_ec293a2e_b7f01740-92e1-4736-b755-50cf2868a0d3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 153cc6b7-82c6-498c-b6c3-7a58f3066a3d
Report Status: 268435456
Hashed bucket: d686f72d60f6e5315dd0adae58f3c509
Cab Guid: 0

-----
I have attached the file "Report.wer" in the zip file.
[WSLterminationReport.zip](https://github.com/microsoft/WSL/files/6644764/WSLterminationReport.zip)

**Comment by MaximoTrinidad** [comment]
Now, here's the GOLDEN NUGGET!!

The only way I can "FInally " Start WSL2 is by opening a PowerShell console and trying to open WSL2 twice; 
(see image)
![WSL2restart_2021-06-13_17-18-22](https://user-images.githubusercontent.com/19892435/121823950-8edd3100-cc76-11eb-8e09-83d2a3c2b415.jpg)

FYI ..my other distros started working again.

**_Please don't close this issue as resolved!  This is a recurring issue every time you update Windows 10 Insider build._**

**Comment by MaximoTrinidad** [comment]
WOOO!! One thing I just realized.  The errors only happen when you click on either of the Ubuntu short-cuts icons. I have no more issues after starting WSL2 twice from the Windows Terminal.  I will create a separate incident for the short-cuts.

**Comment by DanPinGF** [comment]
@therealkenc - Hmmm... appears that this issue hasn't had any activity for quite a while. No 'needs-author-feedback' label so far. :\
