### ISSUE TITLE
Cannot access \\wsl$\Ubuntu from explorer

### ISSUE THREAD

**Issue by darrensimons** [microsoft/WSL#7061]
### Windows Build Number

10.0.19403.1052

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Load Ubuntu VM via WSL
Type wsl -l from command line to confirm Ubuntu (Default) is the correct name of my VM

Either:
(1) From From Explorer chose \\wsl$ and double click Ubuntu
=> Error msg: You might not have permission to use this network resource.... Attempt to access invalid address

or (2) From From Explorer chose \\wsl$\Ubuntu
=> Error msg: You might not have permission to use this network resource.... Attempt to access invalid address

or (3) from cmd.exe type "dir \\wsl$\Ubuntu"
=> Error: The system cannot find the path specified.  
Note: I'm not 100% sure #3 should work anyway, but the first two should.

I can map the drive though so setting U: drive to be Ubuntu from wsl$ works fine and I see the full directory when I type dir u:

I have read lots of articles about this and tried all suggestions but am stumped.  I've tried reinstalling Ubuntu, I've also tried reinstalling WSL (uninstall/reboot/install(.  The only thing I wondered was that I was running WSL 1 which I then updated to WSL 2.  Could that be the issue?

It's really frustrating - I have it working fine on a different PC when I installed WSL2.

### Expected Behavior

Should show \\wsl$\Ubuntu directory

(need this to link in vscode from Linux)

### Actual Behavior

error message - You might not have permission to use this network resource.... Attempt to access invalid address

**Comment by therealkenc** [comment]
Continuation #4260.

> It's really frustrating - I have it working fine on a different PC when I installed WSL2.

You've labeled this WSL1 in the OP but given the kernel version cited trust this is WSL2. [If you _are_ on WSL1 on _this_ PC, try a differently-named instance of WSL2 and see if the problem persists on the failing PC. You can install a fresh WSL2 instance by doing a `wsl.exe --set-default-version 2` and then installing a new distro from the Store.]

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking or AV software that has been installed on Windows if applicable.

**Comment by darrensimons** [comment]
Sorry, my mistake when creating the ticket.  I do indeed mean WSL2.  I have amended the ticket accordingly.

There's no third-party networking installed but I am running Avast Free Edition (Program Ver. 21.4.2464 - build 21.4.6266.670; virus builds 210614-4).  I tried disabling AV then restarted WSL but it made no difference.

Feedback link here: https://aka.ms/AAcw8yk <-- I hope this is the format you wanted.  Thanks

**Comment by darrensimons** [comment]
@OneBlue I'm having issues following the instructions described - specifically when I type wpr -start wsl.wprp -filemode at an admin command prompt I get the error message "Error code: 0xc00cee4f"

I did try to re-submit the screenshot feedback via Feedback Hub though with the recorded screenshare.  Did that work?  Can you see that?

**Comment by OneBlue** [comment]
This error code looks like the .wprp file is corrupted, can you make sure you downloaded [the raw version of the file][https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/wsl.wprp) ?

**Comment by darrensimons** [comment]
Apologies for that.  I've done as requested and attached that here as a ZIP.
[wsl.zip](https://github.com/microsoft/WSL/files/7093277/wsl.zip)

**Comment by darrensimons** [comment]
I don't know if this helps but I upgraded from Windows 10 Home to Windows 11 home this weekend and the issue is resolved.

**Comment by OneBlue** [comment]
Glad to hear this. We did solve multiple issues around \\wsl$ for Windows 11 so that was probably it
