### ISSUE TITLE
WSL2 GUI - How to setup proper font smoothing on a high-res monitor?

### ISSUE THREAD

**Issue by speller** [microsoft/WSL#7063]
I'm running WSL2 GUI app under Windows Insider Preview build 21390.1010. The default system scaling is 300%. When I run a program under WSL, font smoothing doesn't work properly and the app looks pixelated:

![image](https://user-images.githubusercontent.com/1829515/121915268-bcd87900-cd3b-11eb-9fe6-68b9b66a9cab.png)

How to solve it?

**Comment by craigloewen-msft** [comment]
HI @speller issues related to WSLg are being tracked on the microsoft/wslg repo! Could you please take a look at the issue list there and open any new issues if you don't see them there already?

Here's the one that's tracking this issue: https://github.com/microsoft/wslg/issues/3

Thanks!

**Comment by speller** [comment]
@craigloewen-msft Thanks for pointing it out. I came to this repo from the https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps documentation page which states that issues should be posted here. 

![image](https://user-images.githubusercontent.com/1829515/122012992-6a906a00-cdc6-11eb-9317-ce9898f48bbe.png)

Please fix the link to WSL GUI issues to the proper repository.
