### ISSUE TITLE
WSL 2 using 6GBs of RAM on my 8GB machine

### ISSUE THREAD

**Issue by Blonteractor** [microsoft/WSL#7080]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Visual Studio Code 1.57.1 with WSL extension 0.56.5

### Repro Steps

Running WSL for a few minutes/hours slowly ramps up memory usage, running vscode with the WSL extension makes it go even higher

### Expected Behavior

WSL uses a sensible amount of memory with no lag

### Actual Behavior

WSL is using 6GB of memory and is making my pc lag

### Diagnostic Logs
![image](https://user-images.githubusercontent.com/48821041/122542186-0977c900-d048-11eb-98fd-7890cce85ecf.png)

_No response_

**Comment by kl3sk** [comment]
You can use a [config file](https://www.bleepingcomputer.com/news/microsoft/windows-10-wsl2-now-allows-you-to-configure-global-options/) to suit your needs.

**Comment by therealkenc** [comment]
The `.wslconfig` docs [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wsl-2-settings). Ref #4166.
