### ISSUE TITLE
The parameter is incorrect. occurs when default termial application is set to windows terminal preview

### ISSUE THREAD

**Issue by minpeter** [microsoft/WSL#7088]
### Windows Build Number

Microsoft Windows [Version 10.0.21390.2025]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

ubuntu 20.04

### Other Software

windows terminal previwe 1.9.1523.0

### Repro Steps

Windows Insider Program -> dev channel
install windows terminal preview
set default termial application -> windows terminal preview
(open cmd or powershell and command wsl) or (open ubuntu)

### Expected Behavior

wsl2 open with windows terminal

### Actual Behavior

The parameter is incorrect.
(error msg)

**Comment by ugalaw97** [comment]
I am having the same issue and iI have tried everything short of reinstalling windows (uninstall ubuntu app, reset app, disable wsl in the windows optional settings and then activating it again)  I have discovered if you launch ubuntu as administrator, it opens a bash window as the root user but that obvviously isn't an actual fix.

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking or AV software that has been installed on Windows if applicable.

**Comment by minpeter** [comment]
> Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking or AV software that has been installed on Windows if applicable.

https://aka.ms/AAczw9o
I don't know if I understood correctly

**Comment by onomatopellan** [comment]
The "parameter is incorrect" should be fixed with https://github.com/microsoft/terminal/pull/10415
You will need to wait for an upcoming Windows Terminal Preview update.

**Comment by minpeter** [comment]
good news!
thanks for letting me know
I'll keep you waiting :)
