### ISSUE TITLE
WSL Don't works on Windows 11

### ISSUE THREAD

**Issue by SsNiPeR1** [microsoft/WSL#7092]
### Windows Build Number

10.0.21996.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

idk

### Distro Version

any

### Other Software

none

### Repro Steps

Just installed Windows 11 leak, WSL seems to doesn't work, but on Windows 10 it worked fine. I started setup.exe on flash drive with leak and selected update option with saving files and options

### Expected Behavior

It must work, but it don't, says something like "Enable virtualization in BIOS and some features are not installed"

### Actual Behavior

WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

### Diagnostic Logs

none

**Comment by starfrost013** [comment]
Seriously?
