### ISSUE TITLE
Microsoft Teams in WSL2 installed successfully but not opened.

### ISSUE THREAD

**Issue by sefatanam** [microsoft/WSL#7097]
### Windows Build Number

Microsoft Windows [Version 10.0.21390.2025]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

I have all default configuration. 

### Expected Behavior

Opening teams startup window.

### Actual Behavior

Not showing any kinds behavior or error messages.

**Comment by WSLUser** [comment]
Are you using WSLg?

**Comment by sefatanam** [comment]
> Are you using WSLg?

no.

**Comment by OneBlue** [comment]
WSLg is required to use GUI apps.

Please see https://github.com/microsoft/wslg.

**Comment by sefatanam** [comment]
> WSLg is required to use GUI apps.
> 
> Please see https://github.com/microsoft/wslg.

after installation WSLg gedit is working but not teams .
