### ISSUE TITLE
Can't use MIDI input inside WSL 2 (ALSA lib seq_hw.c:466 error)

### ISSUE THREAD

**Issue by Balthus1989** [microsoft/WSL#7098]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1081]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubunto 20.04 LTS

### Other Software

PyGame 2.0.1
Python 3.8.5

### Repro Steps

I wrote the following script in order to print the MIDI devices available:

```python
import pygame
import pygame.midi
from pygame.locals import *

#Printing device info
pygame.midi.init()

for i in range(pygame.midi.get_count()):
    r = pygame.midi.get_device_info(i)
    (interf, name, inpu, output, opened) = r

    int_out = ""
    
    if inpu:
        in_out = "(input)"
        
    if output:
        in_out = "(output)"
        

    print ("%2i: interface :%s:, name :%s:, opened :%s:  %s" %
            (i, interf, name, opened, in_out))
pygame.midi.quit()
```

In WSL 2, I run the command `python print_device_midi_list.py `

However, I get the following error message:
`pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory`

### Expected Behavior

- Reproducing the aforementioned Python script
- Using MIDI devices in WSL 2

### Actual Behavior

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)&nbsp;
Hello from the pygame community. https://www.pygame.org/contribute.html&nbsp;
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

**Comment by OneBlue** [comment]
Thanks for reporting this, we don't support MIDI right now, so can you please file this as a feature request instead of a bug ?
