### ISSUE TITLE
.wslconfig memory value not respected when set to 16GB

### ISSUE THREAD

**Issue by wizonesolutions** [microsoft/WSL#7099]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Arch Linux (Release:	rolling)

### Other Software

Docker Desktop (Windows) 3.4.0 (65384)

### Repro Steps

With the following .wslconfig:

````ini
[wsl2]
;kernel=/path/to/kernel
memory=16GB
````

run WSL 2.

### Expected Behavior

WSL 2 should use 16 GB of memory and show roughly that amount in `htop` or when running `free -m`.

### Actual Behavior

WSL 2 appears to use the default amount of memory (roughly 25 GB of my 32 GB).

### Diagnostic Logs

I wonder if the commented-out kernel line is confusing the parser? I have since removed it and switched to this configuration:

````ini
[wsl2]
memory=8GB
processors=6
````

which works. I haven't since tried 16GB again, since I was just trying to stop my system from occasionally hanging (which I think was actually due to CPU usage rather than memory).

I figured I would report the potential issue anyway.

**Comment by craigloewen-msft** [comment]
I'm not able to reproduce this problem on my machine. Could you try replacing the `;` character with a `#` to comment it out? (e.g: `#kernel=/path/to/kernel`) 

As well, if you do see this again, could you try running `wsl --shutdown` to shut down the VM and reload it? (This will reload your settings).

**Comment by wizonesolutions** [comment]
Ah, is # the commenting character? That would explain it. ; is the typical
character used for INI format. But I think we know what happened here,
then, and this can probably be closed.

**Comment by therealkenc** [comment]
Ref #7013 for the '`;`' thing.
