### ISSUE TITLE
Mouse Input not detected across entire terminal

### ISSUE THREAD

**Issue by LouChiShu** [microsoft/WSL#7101]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

ImTui example project found [here](https://github.com/ggerganov/imtui)

### Repro Steps

- Clone and build ImTui and the example project.
- Try to drag one of the windows to the far right of the terminal or hover over the right side of the terminal with the mouse cursor

### Expected Behavior

The mouse cursor position in the example project should update regardless of where it is. Additionally the window should be draggable to any part of the terminal

### Actual Behavior

The cursor stops being detected once you reach a certain position in the terminal. In my case it was around the 94th column.

### Diagnostic Logs

I have tried this example project in the WSL terminal and in the Windows Terminal via the Ubuntu profile, neither detect mouse input once you reach column 94. I did try the same program in an Ubuntu VM's gnome terminal and it worked perfectly fine across the entire terminal.

**Comment by LouChiShu** [comment]
Adding some gifs to illustrate the issue:
Ubuntu WSL
![wsl](https://user-images.githubusercontent.com/55987090/123127583-51309300-d442-11eb-9b2d-5cdb822472fb.gif)

Ubuntu VM
![vm](https://user-images.githubusercontent.com/55987090/123127608-5988ce00-d442-11eb-8fa2-4bc8c441bf94.gif)

**Comment by therealkenc** [comment]
I was not able to reproduce on 21390. Absent something external, the (mis)behavior might have been addressed between 19043 and recent Insiders. Before posting in the Windows Terminal [tracker](https://github.com/microsoft/terminal/issues), try installing the latest Windows Terminal and starting your distribution from `cmd` or `powershell` prompt. It worked for me on the "legacy" "Ubuntu" console too (I tried both), but trying Windows Terminal first is a good place to start.

**Comment by LouChiShu** [comment]
I have just: 
- Done a fresh reinstall of windows on my laptop (previously all testing was done on my Desktop)
- Reinstalled Windows Terminal via the Microsoft Store
- Enabled WSL and updated to WSL2
- Reinstalled Ubuntu via the Microsoft store
- Redownloaded the repo and build it

I still have the same issue where I don't get mouse input on almost 2/3rds of the screen. I tried the command prompt, powershell prompt, the ubuntu console and Windows Terminal. I am not sure what sort of external behaviour could be causing this
