### ISSUE TITLE
EcryptFS support

### ISSUE THREAD

**Issue by caleb15** [microsoft/WSL#7102]
**Is your feature request related to a problem? Please describe.**
I want to encrypt certain folders

**Describe the solution you'd like**
Ability to encrypt via [ecryptfs](https://www.ecryptfs.org/home)

**Describe alternatives you've considered**
LUKS / gpg / [DMcrypt](https://gist.github.com/d4v3y0rk/e19d346ec9836b4811d4fecc1e1d5d64), but it either seems complicated or slow

**Additional context**
```
 sudo apt-get install ecryptfs-utils
caleb@DESKTOP-AE53KE4:~$ ecryptfs-setup-private
ERROR:  Cannot get ecryptfs version, ecryptfs kernel module not loaded?
```

I read https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Documentation/security/keys/ecryptfs.rst and thought ecryptfs might be supported but I guess not 🤔

**Comment by caleb15** [comment]
Note this is ubuntu 20 on wsl2

**Comment by therealkenc** [comment]
[CONFIG_ECRYPT_FS](https://cateee.net/lkddb/web-lkddb/ECRYPT_FS.html) et al

![image](https://user-images.githubusercontent.com/7049700/123171155-44a33f00-d430-11eb-8f82-ed2af9d29865.png)

It is `=y` on Real Ubuntu.

![image](https://user-images.githubusercontent.com/7049700/123171613-e6c32700-d430-11eb-88d4-19ab83436921.png)

**Comment by WSLUser** [comment]
I'd add this to my config but I want to ensure it's placed in the appropriate section and not just have it unorganized at the end. If I knew which config comes before and after, I'd place it there and test it.

**Comment by luke1100** [comment]
Hi everyone, does it resolved?

**Comment by WenTesla** [comment]
> i

kali wsl2 has the same problem,could others sovle this problem?
![image](https://user-images.githubusercontent.com/88094223/235699659-44ae2837-b8cb-4cf6-aeaa-88ebb0414f36.png)
