### ISSUE TITLE
The specified network name is no longer available. [Unbuntu for Windows]

### ISSUE THREAD

**Issue by EPIVIO** [microsoft/WSL#7103]
### Windows Build Number

Microsoft Windows [version 10.0.19042.1052]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Other Software

Unbuntu for Windows

### Repro Steps

I really don't know how to reproduce the bug

### Expected Behavior

A complete and clean install of Unbuntu WSL

### Actual Behavior

The install failed.
![Sans titre](https://user-images.githubusercontent.com/86328798/123009577-3ec04600-d3bd-11eb-9b7b-d883c3a55823.png)

**Comment by therealkenc** [comment]
> I really don't know how to reproduce the bug

Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item in /dupe #5257. It is okay that you don't know how to reproduce the bug, collecting logs on the fail always helps (or at least never hurts).

These are showing a WSL1 pattern (#6378 and #6736 are also on the books). Seeing if the problem persists on WSL2 is also helpful.
