### ISSUE TITLE
WSL2 completely breaks after resetting ubuntu 

### ISSUE THREAD

**Issue by SeleDreams** [microsoft/WSL#7112]
### Windows Build Number

19043.1055

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

- Reset Ubuntu 20.04 from the program advanced settings after having used it with WSL2

### Expected Behavior

It should normally start back normally, be uninstallable and we could install other distros.

### Actual Behavior

Ubuntu doesn't start anymore, even after being uninstalled and not being in the program list anymore it still appears in the start menu, moreover, it broke the entire wsl install process. 
Trying to install any wsl distro, even others than Ubuntu results in the install button doing nothing

https://user-images.githubusercontent.com/16335601/123240784-e5e9ce00-d4e0-11eb-8143-cdfe081048e9.mp4

### Diagnostic Logs

I don't know where to get them for this

**Comment by craigloewen-msft** [comment]
Hi could you please add logs for this issue? /logs

As well, could you try running `wsl -l -v` in CMD or PowerShell and showing us the output? 

If you're looking to completely uninstall your distro (and *wipe all data inside of the distro*) could you also try running `wsl --unregister <DistroName>` where `<DistroName>` is an output of a WSL distro name from above? Does that remove the distro and allow you to launch it again?
