### ISSUE TITLE
remotely access Jupyter notebook on wsl2

### ISSUE THREAD

**Issue by woreom** [microsoft/WSL#7121]
### Windows Build Number

Build21390.co_release.210521-1658

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 18.04

### Repro Steps

So I have a jupyter notebook running on my wsl 2 with the command:
'python3 -m jupyterlab'
On the computer browsing http://localhost:8888/ while display my jupyter notebook normally as this bug was fixed. but when I want to open my notebook on another computer, I can't, I usually forward the port like this:
`ssh -NL localhost:2323:localhost:8888 windows_pc_name/remote_user@remote_ip`
I understand that there should be an additional step that map my wsl IP:8888 to my windows localhost:8888 but doing something like:
`ssh -NL localhost:8888:localhost:8888 wsl_user@wsl_ip` will result in `ssh: connect to host 172.31.218.111 port 22: Connection refused`
I find my wsl IP with 
`
ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
`
Can anyone help me, my livelihood depends on this

### Expected Behavior

on a normal ubuntu it will bring up the jupyter notebook when  browsing http://localhost:8888/

### Actual Behavior

This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by therealkenc** [comment]
> on another computer

/dupe #4150

Take "has workaround" with a grain of salt yrmv.
