### ISSUE TITLE
WSL vEthernet adapter not working as expected

### ISSUE THREAD

**Issue by explogx** [microsoft/WSL#7125]
### Windows Build Number

10.0.19042.1052

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

20.04

### Other Software

Virtualbox 6.1.22

### Repro Steps

Create a virtual machine in Virtualbox and in the network tab choose "Bridged Adapter" and "Hyper-V Virtual Ethernet Adapter" then in the VM configuration choose an IP address in the range 172.19.144.0/20 and assign it statically.

### Expected Behavior

From the WSL distro, you should be able to successfully ping the newly created VM via the vEthernet connectivity over the range 172.19.144.0/20 on the LAN network.

### Actual Behavior

Message "Destination Host Unreachable" when you issue the ping command.

**Comment by craigloewen-msft** [comment]
This behaviour is expected. The VirtualBox engine is completely different than the one that WSL uses, so these adapters are not able to communicate with eachother.

I'll close this issue out, as it's not actionable for the team. However I'd recommend taking a look at port forwarding [(like this example)](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) to see if you can get yourself unblocked.
