### ISSUE TITLE
Provide option to store Docker images/containers/volumes on other drives

### ISSUE THREAD

**Issue by SetTrend** [microsoft/WSL#7128]
## Is your feature request related to a problem? Please describe.

My system disk (C:) is full, just filled with WSL 2 containers and images.

My D: drive, however, is ...
1. empty
2. larger
3. expandable

But there's no viable way of defining a destination folder for images, containers a/o volumes.

## Describe the solution you'd like

I'm not sure if this touches WSL, but I created a [feature request in the Docker repository](/docker/cli/issues/3165) about this sadly missing feature.

Probably the WSL team may need to provision some API extension so the `docker-desktop` and `docker-desktop-data` WSL 2 VMs will be able to store their data on drives other than the confined C: drive.

**Comment by WSLUser** [comment]
You can do a wsl --export, then move the export to a different drive then do a wsl --import. You can remove the Store installed version after the export is complete or after the import to verify all is working well.

**Comment by therealkenc** [comment]
> but I created a feature request in the Docker repository 

For WSL proper this is effectively /dupe #4320 and LZ #449. For Docker Desktop looks like docker/for-win#5829.

**Comment by SetTrend** [comment]
@therealkenc:

Your assumption is not quite correct. What I'm suggesting is to be able to store individual images, containers or volumes on **_different_** drives _**individually**_.

That's something that the Docker team needs to piece together. But perhaps the WSL team needs to add support for this.

Would you mind re-opening this feature request?

**Comment by SetTrend** [comment]
The requested feature could be realized by mounting/dismounting virtual disks for each Docker image/container/volume from within WSL 2.
