### ISSUE TITLE
Systemctl not started on Centos 8 WSL

### ISSUE THREAD

**Issue by netbeansfan** [microsoft/WSL#7129]
C:\Users\Win10Pro>cmd.exe --version
Microsoft Windows [Version 10.0.19043.1081]

Hi WSL Team,

I have successfully installed Centos 8 on Windows 10 via Microsoft Appstore but am not able to Putty (ssh) to Centos session from the same Windows 
desktop host with "**connection refused**" error. I have updated /etc/ssh/sshd_config to enable ssh connection but 
encountered the following errors when trying to restart systemctl:

#sudo systemctl start sshd
**System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down**

Below is the IP addresses from ipconfig on Windows 10 host:

```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : modem
   IPv4 Address. . . . . . . . . . . : 192.168.0.142
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::74ea:18b1:a46d:4240%25
   IPv4 Address. . . . . . . . . . . : 172.19.64.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::99d9:8474:7e5b:a9fc%50
   IPv4 Address. . . . . . . . . . . : 172.22.80.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```

On the other hand, Centos WSL gives the following IP address:

```
[root@mars ssh]$ ip addr
5: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:8c:e0:14 brd ff:ff:ff:ff:ff:ff
    inet 172.22.84.118/20 brd 172.22.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe8c:e014/64 scope link
       valid_lft forever preferred_lft forever
```
	   
Any assistance would be much appreciated.

Thanks,

George

**Comment by therealkenc** [comment]
/dupe #1579

You can start `sshd` manually as a work-around.

```
# /usr/sbin/sshd
```

**Comment by ldo** [comment]
Aren’t you supposed to include a reference to the issue that is supposedly being duplicated?
