### ISSUE TITLE
WSL - suddenly all distro give error "The network does not have a subnet for this endpoint" when launching

### ISSUE THREAD

**Issue by varvizzignoDRA** [microsoft/WSL#7130]
### Windows Build Number

10.0.18363 Build 18363

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

Also Docker Desktop is not working anymore on WSL

### Repro Steps

- At windows startup wsl distro were usually running (eg docker desktop or Ubuntu)
- Now, after months of straightforward usage, suddenly Docker Desktop at win startup gives exception with message "The network does not have a subnet for this endpoint."
- I open cmd as Admin
- I type wsl -l -v --> i detect both Ubuntu and Docker are "stopped"
- I try to type wsl -d Ubuntu-20.04 --> get error "The network does not have a subnet for this endpoint."
- I try to type wsl -d docker-destkop-data -> get error "The network does not have a subnet for this endpoint."
- Restarting or any other command dont fix it

### Expected Behavior

WSL distro launched and working as previous

### Actual Behavior

WSL distro not launching 
![image](https://user-images.githubusercontent.com/81296493/123663497-bfa49500-d836-11eb-9d5f-0c2b2d6b0463.png)

**Comment by therealkenc** [comment]
Please collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and post (or link) the etl here.

**Comment by varvizzignoDRA** [comment]
Hi, thanks for the support. WSL started working again suddenly, without me doing any action.
So i think it probably broke cause of a central company windows update / pc config, that got fixed in a following update.

Closing the issue.
