### ISSUE TITLE
Windows 11 dev preview broken WSLg

### ISSUE THREAD

**Issue by wormwang** [microsoft/WSL#7132]
### Windows Build Number

Windows 11 dev preview,build 22000.51

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.+

### Distro Version

Ubuntu 20.04

### Repro Steps

click ubuntu icon, lock in black screen many mins, then it exit 

### Expected Behavior

WSL2 run

### Actual Behavior

icon exit

##fix steps
fixed it by follow steps
1, open a terminal as admin right
2, run 
wsl --update
update to 5.10.16
3, wsl --shutdown
4, wsl

**Comment by rajbos** [comment]
After starting a terminal to Ubuntu 20.04 I had the same issue. I ran these commands from a PowerShell window to get something working:

``` shell
wsl shutdown # no feedback
wsl # An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
```

Then I opened the terminal again and things seem to work again, even my docker installation seems to be up and running again :-)

**Comment by craigloewen-msft** [comment]
Could you please gather logs for this issue and post a link here? The logs will allow us to determine what's going on.

/logs

**Comment by rajbos** [comment]
Hmm, first reboot and no issues.
Second reboot had the same issue. I can only record the info about shutting down and restarting wsl to get things working again. Did so with [this feedback item](https://aka.ms/AAd2psx). Hope it helps :-)

**Comment by wormwang** [comment]
fixed it by follow steps
1, open a terminal as admin right
2, run 
wsl --update
update to 5.10.16
3, wsl --shutdown
4, wsl

**Comment by rajbos** [comment]
Can't get anything out of the wsl command today :-(. No response for minutes, then no message, just a return.  So no way to update after upgrading to Win11, just broken. Will try to find a way to remove and reinstall wsl then.

**Comment by rajbos** [comment]
Removing and reinstalling Ubuntu. still nothing. Clicking in the Ubuntu window now displays 'Select Ubuntu' in the title bar?

![image](https://user-images.githubusercontent.com/6085745/124180806-043d6400-dab5-11eb-826c-68f3df549eb4.png)
