### ISSUE TITLE
Lots of redundant “Carriage return” appeared in other terminal by wslg

### ISSUE THREAD

**Issue by micsama** [microsoft/WSL#7133]
### Windows Build Number

Microsoft Windows [版本 10.0.21390.2025]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

1. open wsl2 
2. open a terminal (like kitty, st, terminology)with windows terminal preview 

### Expected Behavior

It works

### Actual Behavior

sometimes it works ,but occasionally until i press a key ,the entry key was pressed.
![8](https://user-images.githubusercontent.com/41811005/123752686-a0b40a80-d8eb-11eb-8376-d7dd2d10febd.png)

**Comment by onomatopellan** [comment]
Known bug in WSLg. Sometimes the xserver remembers the last key pressed. They are working in a fix in https://github.com/microsoft/wslg/issues/58

**Comment by craigloewen-msft** [comment]
As @onomatopellan mentioned this is a known issue in WSLg and is tracked on the WSLg repo: microsoft/wslg#58

I'll close this issue out for bookkeeping, please follow up on the issue thread in the WSLg repo!
