### ISSUE TITLE
WSL2 Ubuntu 18.06 lost normal connectivity after the latest windows update 21H1

### ISSUE THREAD

**Issue by emonakov** [microsoft/WSL#7135]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.104-microsoft-standard

### Distro Version

18.04

### Other Software

git version 2.31.1
GNU Wget 1.19.4 built on linux-gnu
and anything that should be able to download

### Repro Steps

1. Install latest windows update 21H1
2. Try to run commands like git clone or wget example.com or use curl

### Expected Behavior

everything should download as it supposed to and not stuck

### Actual Behavior

the process is stuck for minutes and fails in the end, cannot clone, pull or curl anything with the command line

### Diagnostic Logs
```
wget github.com
--2021-06-30 13:59:05--  http://github.com/
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ [following]
--2021-06-30 13:59:15--  https://github.com/
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
Unable to establish SSL connection.`

`wget http://www.columbia.edu/~fdc/sample.html
--2021-06-30 14:21:22--  http://www.columbia.edu/~fdc/sample.html
Resolving www.columbia.edu (www.columbia.edu)... 128.59.105.24
Connecting to www.columbia.edu (www.columbia.edu)|128.59.105.24|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34975 (34K) [text/html]
Saving to: ‘sample.html’

sample.html                     0%[                                                  ]       0  --.-KB/s    in 4m 15s

2021-06-30 14:25:47 (0.00 B/s) - Read error at byte 0/34975 (Connection reset by peer). Retrying.

--2021-06-30 14:25:48--  (try: 2)  http://www.columbia.edu/~fdc/sample.html
Connecting to www.columbia.edu (www.columbia.edu)|128.59.105.24|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34975 (34K) [text/html]
Saving to: ‘sample.html’

sample.html                     0%[                                                  ]       0  --.-KB/s
```

**Comment by therealkenc** [comment]
Please collect [networking logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and post (or link) the etl here.

**Comment by emonakov** [comment]
@therealkenc https://disk.yandex.ru/d/DyrG-HCAE4ssQQ

**Comment by emonakov** [comment]
I attached logs here. Is there any chance to find a solution?

**Comment by craigloewen-msft** [comment]
We're following up with the networking team here, thank you for providing logs we'll reach out if we need more info!

**Comment by Keith-Mange** [comment]
I'm from the networking team.  Would you be able to do the following:
1) Reboot
2) [startpacketcapture.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/startpacketcapture.ps1)
3) Small repro (one wget)
4) stop packet capture
5) [collectlogs.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1)

The logs can get big really fast so a small repro is great and please let me know what you tried to access.

Thanks!

**Comment by emonakov** [comment]
I tried `wget ya.ru`

https://disk.yandex.ru/d/qAR7_ukcqcnuXQ

**Comment by emonakov** [comment]
This can be closed.  Solved by uninstalling hyper-v and wsl from windows components and installing wsl back.
