### ISSUE TITLE
Massive issue 4197 was closed but no visible changes so far, 2 years later. I think it should be re-opened and addressed. It's a massive problem for everyone who are using WSL every day.

### ISSUE THREAD

**Issue by centur** [microsoft/WSL#7139]
### Windows Build Number

Version 10.0.19042.1055

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2.

### Distro Version

Ubuntu 20.04

### Repro Steps

Filesystem performance is abysmally bad. See issue https://github.com/microsoft/WSL/issues/4197

### Expected Behavior

Issue is addressed, not silenced and forgotten. Community discussion there shows that it's a massive problem for everyone. Please reopen the original issue or update on a progress in this area.

### Actual Behavior

Issue was suppressed by moderation team and silenced.

**Comment by benhillis** [comment]
/dupe #4197 was locked a while back because nothing new or helpful was being added, I've unlocked the thread.

We are actively working on this.
