### ISSUE TITLE
Random BSOD - IRQL_NOT_LESS_OR_EQUAL - tcpip.sys

### ISSUE THREAD

**Issue by aravindvnair99** [microsoft/WSL#7140]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 21.04 Hirsute Hippo

### Repro Steps

Setup Ubuntu and use it normally

### Expected Behavior

The laptop shouldn't crash

### Actual Behavior

The laptop occasionally crashes. Usually, it happens when WSL machines are running. but right now, I got 3 back-to-back BSOD just while it restarted from bug check. Does not happen always, but it's quite frequent. Sometimes, it's back-to-back BSOD.

### Diagnostic Logs

CPU: Intel Core i5-4200U
RAM: 12 GB DDR3
SSD: Samsung 870 Evo 1 TB
Wireless card: Intel Wireless N 7260 Single Band
GPU: Intel HD Graphics 4400

The laptop is a Dell Inspiron 15R 5537.

I assume something is going wrong with my wireless driver. I have tried reinstalling both Windows and only the driver, but neither helped. When I did uninstall the driver and didn’t install it back for a while, it was fine, atleast for the duration, I waited. Let me know if I should provide the dumps of BSODs or anything else. I have also reported the issue via email to `secure@microsoft.com` as per [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#important-reporting-bsods-and-security-issues).

**Comment by aravindvnair99** [comment]
I downloaded [BlueScreenView v1.55](https://www.nirsoft.net/utils/blue_screen_view.html) and this is what I see:

![image](https://user-images.githubusercontent.com/22199259/124267735-4965a280-db56-11eb-8b16-f1d055797748.png)

![image](https://user-images.githubusercontent.com/22199259/124267982-93e71f00-db56-11eb-920d-4b12c338e36c.png)

![image](https://user-images.githubusercontent.com/22199259/124268144-c42ebd80-db56-11eb-9c5e-4867ca6195ad.png)

Time when the screenshot was taken: 16:55 Had to split it into 3 to paste it here. Clicking on any of the reports, shows the same thing with the only difference being the `From Address` and `To Address`:

![image](https://user-images.githubusercontent.com/22199259/124268268-eaecf400-db56-11eb-80e1-6341fae33c03.png)

**Comment by benhillis** [comment]
tcpip.sys is not WSL

**Comment by aravindvnair99** [comment]
> tcpip.sys is not WSL,

@benhillis Yeah I understand, but I didn't know where else to report to. This only started happening after I installed WSL.

> I will check with the networking folks to see if they are aware of any current bugchecks in their driver.

Thank you for your time! Will wait for you.

**Comment by benhillis** [comment]
@aravindvnair99 - thanks for your understanding. Letting the WSL github be the landing spot for all Windows bugs isn't sustainable.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 - thanks for your understanding. Letting the WSL github be the landing spot for all Windows bugs isn't sustainable.

@benhillis I agree. Without WSL installed, things work fine for me though. I have doubts about my wireless driver or the Hyper-V Virtual Ethernet Adapter malfunctioning.

**Comment by aravindvnair99** [comment]
> I will check with the networking folks to see if they are aware of any current bugchecks in their driver.

Hey @benhillis! I was wondering if you happened to have a chance to check with them and if you had any updates for me?

**Comment by aravindvnair99** [comment]
Hey @benhillis! I was curious to know if you had anything to share. I still continue to face the issue frequently almost rendering my laptop unusable.

**Comment by aravindvnair99** [comment]
> tcpip.sys is not WSL, I will check with the networking folks to see if they are aware of any current bugchecks in their driver.

Hey @benhillis! Any updates?

**Comment by aravindvnair99** [comment]
Hey @benhillis! Any updates? I still continue to get frequent BSOD and it's been a few months now. :(

**Comment by aravindvnair99** [comment]
Update for anyone who stumbles upon this thread:

I updated to Windows 11 and so far no crashes at all. WSL is also much faster. Hope it stays this way.

**Comment by DevCortez** [comment]
This is the first place on the internet that helps me make sense of what has been happening to me lately, i was having very frequent bsods with WSL2 installed and since the error made no sense at all i considered it being some sort of file corruption or some hw malfunction but i figured out that just disabling WSL2 seems to solve the entire thing.

![image](https://user-images.githubusercontent.com/2830351/159129513-303353ac-b4e3-4d43-8a69-605b4cb27611.png)

The is one curiosity about these crashes, it only seems to happen while i'm away from the computer (a few minutes, sometimes a few hours), it didn't happen once while i was doing any work on the computer (but sometimes going to grab a coffee was enough for it to happen, others i could cook lunch and things would still be working).

**Comment by aravindvnair99** [comment]
@DevCortez Was facing the same here until I upgraded to Windows 11. Which Windows are you on?

I have noticed certain versions of the Intel wireless driver does bring up the issue though on Windows 11. I have an Intel Wireless N 7260 single band. Which do you have?

**Comment by DevCortez** [comment]
> @DevCortez Was facing the same here until I upgraded to Windows 11. Which Windows are you on?
> 
> I have noticed certain versions of the Intel wireless driver does bring up the issue though on Windows 11. I have an Intel Wireless N 7260 single band. Which do you have?

I'm currently running win 10 (19044.1586)  and my internet is cabled (no wifi adapter whatsoever).

Before i realized WSL was causing the issue, i tried disabling all but the active network adapter and i still had problems.

**Comment by aravindvnair99** [comment]
> I'm currently running win 10 (19044.1586) and my internet is cabled (no wifi adapter whatsoever).
> 
> Before i realized WSL was causing the issue, i tried disabling all but the active network adapter and i still had problems.

@DevCortez For me disabling didn't help. But uninstalling the adaptor from Device Manager did.

You could try upgrading to Windows 11. That's what really helped me. But then like I said, certain drivers, do give me trouble. You could try different driver versions. Older driver versions are what works for me. None of the recent ones for my model work right for me.

**Comment by aravindvnair99** [comment]
> tcpip.sys is not WSL, I will check with the networking folks to see if they are aware of any current bugchecks in their driver.

@benhillis Disappointed to not hear back from you after https://github.com/microsoft/WSL/issues/7140#issuecomment-873119066. It's been almost a year. Would be great if you had any updates.
