### ISSUE TITLE
When I first boot wsl, it says the parameters are wrong

### ISSUE THREAD

**Issue by umbrella-k** [microsoft/WSL#7142]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Debian

### Repro Steps

Install debian from the store and start up

### Expected Behavior

You will be able to create a UNIX user account, set a password, and use WSL.

### Actual Behavior

"Incorrect parameters" is displayed and the UNIX user name and password cannot be set.
"パラメーターが間違っています。" in the image is written in Japanese as "The parameter is wrong".
![image](https://user-images.githubusercontent.com/68675858/124355921-93ca4a80-dc4e-11eb-96ba-c560b2291646.png)

![image](https://user-images.githubusercontent.com/68675858/124355722-a4c68c00-dc4d-11eb-814c-6d8bf2f4f7fe.png)

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/6758492/wsl.zip)

**Comment by craigloewen-msft** [comment]
@umbrella-k this is related to an issue when you have Windows Terminal set as your default console Window. Could you please disable that feature and then try this again?

As well this Terminal bug has been fixed internally and will be fixed in later versions.

**Comment by bpulliam** [comment]
This issue is fixed in Insider build 22000.65 (out today 7/8)
