### ISSUE TITLE
invalid command line option --mount

### ISSUE THREAD

**Issue by samvup** [microsoft/WSL#7145]
I'm running on windows version 21H1 and I am receiving this error each time I try to mount a disk.

`PS C:\Windows\system32> wsl --mount \\.\PHYSICALDRIVE1
Invalid command line option: --mount
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.`

I have the latest WSL version as well (WSL2)

**Comment by shi429101906** [comment]
Same problem, I waited for a year

**Comment by rouke-broersma** [comment]
This feature is still in preview, you need to be on the insider channel.

**Comment by craigloewen-msft** [comment]
@samvup please fill out the bug template so we can have the right info to help solve your problem. It's very likely that this is because you are not on the correct Windows version. This feature is only available right now on the Windows Insiders program. Your [Windows build needs to be 20211 or higher](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) to access this.

**Comment by realsarm** [comment]
Almost 2022 and no progress on this

**Comment by craigloewen-msft** [comment]
@realsarm this is because you are not on the right Windows version. Please ensure you have the right Windows build to access this feature (If you're on Win11 you should have access! )

**Comment by eggcar** [comment]
> 

what is the 'right Windows version'? only win11 supported? now 2022/10 and still no support on win10
