### ISSUE TITLE
No compatible GPUs found for path tracing. Cycles will render on the CPU !

### ISSUE THREAD

**Issue by Marietto2008** [microsoft/WSL#7146]
Hello to everyone.

I'm using Windows 11 pro Build 22000.co_release.210604-1628 and I have installed the WSL2 with Ubuntu 21.04 on top of it. Inside the Ubuntu OS I have installed Blender 2.82. And then I went on User Preferences / System because I wanted to check if blender cycles was able to render using the GPU exposed by windows 11 while launched within WSL2. This is what happened with my big disappointment :

![2021-07-04_12-59-02](https://user-images.githubusercontent.com/755339/124386094-e6e8df80-dcd8-11eb-8981-c5adba0888db.png)

Is there a fix or a workaround for this problem ? Not being able to render something using blender cycles inside WSL2 is a serious missing.  My graphic card is the Nvidia RTX 2080 ti and blender detects it correctly on Windows 11.

![2021-07-04_13-16-34](https://user-images.githubusercontent.com/755339/124386468-e0f3fe00-dcda-11eb-8498-ae649fd53785.png)

**Comment by craigloewen-msft** [comment]
This is likely becuase your WSL Distro version does not have the right Mesa packages to utilize your GPU. Please check out [this blog post](https://discourse.ubuntu.com/t/announcing-ubuntu-on-windows-community-preview/19789) to see how you can get the Ubuntu Community Preview which does have the right Mesa packages, as well as making sure that you have a [WSL GPU ready driver installed](https://github.com/microsoft/wslg#pre-requisites)!

**Comment by craigloewen-msft** [comment]
If you're still seeing this issue please file it over at the WSLg repo at https://github.com/microsoft/wslg , I'll close this out as it's not an actionable item for the WSL team, thanks for filing it!

**Comment by Raoggame** [comment]
Please help me. My seem Problem. Please please please 🙏🙏🙏🙏🙏
