### ISSUE TITLE
Incorrect permissions on `/dev/kvm`

### ISSUE THREAD

**Issue by davisjr** [microsoft/WSL#7149]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

KVM

### Repro Steps

Incorrect permissions on `/dev/kvm` is preventing startup of Android emulator although the user is a member of the required group. 

```
$ emulator -avd api29
emulator: Android emulator version 30.6.5.0 (build_id 7324830) (CL:N/A)
ProbeKVM: This user doesn't have permissions to use KVM (/dev/kvm).
The KVM line in /etc/group is: [kvm:x:108:davisj]

If the current user has KVM permissions,
the KVM line in /etc/group should end with ":" followed by your username.

If we see LINE_NOT_FOUND, the kvm group may need to be created along with permissions:
    sudo groupadd -r kvm
    # Then ensure /lib/udev/rules.d/50-udev-default.rules contains something like:
    # KERNEL=="kvm", GROUP="kvm", MODE="0660"
    # and then run:
    sudo gpasswd -a $USER kvm

If we see kvm:... but no username at the end, running the following command may allow KVM access:
    sudo gpasswd -a $USER kvm

You may need to log out and back in for changes to take effect.

handleCpuAcceleration: feature check for hvf
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: This user doesn't have permissions to use KVM (/dev/kvm).
The KVM line in /etc/group is: [kvm:x:108:davisj]

If the current user has KVM permissions,
the KVM line in /etc/group should end with ":" followed by your username.

If we see LINE_NOT_FOUND, the
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

Permissions on `/dev/kvm` is currently (incorrect group and permissions):
```sh
$ ls -l /dev/kvm
crw------- 1 root root 10, 232 Jul  5 13:27 /dev/kvm
```

This should ideally be:
```sh
crw-rw---- 1 root kvm 10, 232 Jul  5 13:27 /dev/kvm
```

Manually changing it helps boot up the emulator. However, the settings are reverted on restart. 

```sh
sudo chgrp kvm /dev/kvm
sudo chmod g+rw /dev/kvm
```

Looks like the correct permissions are part of udev defaults but this is not getting applied on WSL:
https://github.com/microsoft/WSL/issues/4193#issuecomment-646991317 (#4193)

```
KERNEL=="kvm", GROUP="kvm", MODE="0660", OPTIONS+="static_node=kvm"
```

This is causing issues with React Native development on WSL where the manual step is required on every boot. 
#6929
 
The issue is reproducible on Windows 10 21H1 builds as well.

### Expected Behavior

Permissions on `/dev/kvm` should be as follows:
```
crw-rw---- 1 root kvm 10, 232 Jul  5 13:27 /dev/kvm
```

### Actual Behavior

Current permissions on `/dev/kvm`:
```
crw------- 1 root root 10, 232 Jul  5 13:27 /dev/kvm
```

**Comment by OneBlue** [comment]
That's expected, WSL2 doesn't have udev.

You can use wsl.conf to change those permissions at boot time with something like this though:


``` 
# /etc/wsl.conf
[boot]
command = /bin/bash -c 'chown root:lvm /dev/kvm && chmod 660 /dev/kvm'
```

**Comment by OneBlue** [comment]
Release notes for boot.command: https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-21286

**Comment by BreeceW** [comment]
> That's expected, WSL2 doesn't have udev.
> 
> You can use wsl.conf to change those permissions at boot time with something like this though:
> 
> ```
> # /etc/wsl.conf
> [boot]
> command = /bin/bash -c 'chown root:lvm /dev/kvm && chmod 660 /dev/kvm'
> ```

For anyone who comes across this, I wanted to add that this works if you change `lvm` to `kvm`, which I assume was a typo.

**Comment by gregaton** [comment]
If you still see the incorrect permissions error add your user to the `kvm` group and restart WSL.
```
sudo usermod -a -G kvm <username>
```

**Comment by felipemarques** [comment]
great ! works for me!

**Comment by Herbias** [comment]
> That's expected, WSL2 doesn't have udev.
> 
> You can use wsl.conf to change those permissions at boot time with something like this though:
> 
> ```
> # /etc/wsl.conf
> [boot]
> command = /bin/bash -c 'chown root:lvm /dev/kvm && chmod 660 /dev/kvm'
> ```

Restart your WSL after. Works like a charm.

**Comment by proccedure-caze** [comment]
I cant find this folder, can anyone help me?

**Comment by smenard** [comment]
> > That's expected, WSL2 doesn't have udev.
> > You can use wsl.conf to change those permissions at boot time with something like this though:
> > ```
> > # /etc/wsl.conf
> > [boot]
> > command = /bin/bash -c 'chown root:lvm /dev/kvm && chmod 660 /dev/kvm'
> > ```
> 
> Restart your WSL after. Works like a charm.

Doesn't work for me. 

I Tried 
> > ```
> > # /etc/wsl.conf
> > [boot]
> > command = /bin/bash -c 'sudo chown USER:kvm /dev/kvm && chmod 660 /dev/kvm'
> > ```
> 
but it didn t work . Does someone has a hint for me ?

**Comment by Biswa96** [comment]
Though not a Linux command, `wsl.exe --version` command from Windows would show some version details without any error or help message.

**Comment by smenard** [comment]
Here are the corresponding informations : 
```
wsl.exe --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2604
```

**Comment by Biswa96** [comment]
This issue seem to be fixed in WSL from Windows Store if systemd is enabled.

* Without systemd:

```
$ ls -l /dev/kvm
crw------- 1 root root 10, 232 Mar 1 00:00 /dev/kvm
```

* With systemd:

```
$ ls -l /dev/kvm
crw-rw---- 1 root kvm 10, 232 Mar 1 00:00 /dev/kvm
```

So, you have to enabled systemd in wsl.conf file.

**Comment by Herbias** [comment]
It's pretty strange -- I did make it work by running the android virtual device on my machine before, but after I re-install my OS. I can't seem to make it work again.

**Comment by smenard** [comment]
> This issue seem to be fixed in WSL from Windows Store if systemd is enabled.
> 
> * Without systemd:
> 
> ```
> $ ls -l /dev/kvm
> crw------- 1 root root 10, 232 Mar 1 00:00 /dev/kvm
> ```
> 
> * With systemd:
> 
> ```
> $ ls -l /dev/kvm
> crw-rw---- 1 root kvm 10, 232 Mar 1 00:00 /dev/kvm
> ```
> 
> So, you have to enabled systemd in wsl.conf file.

Thanks it works now.
