### ISSUE TITLE
How can I disable Windows sounds in Bash?

### ISSUE THREAD

**Issue by mout12** [Microsoft/WSL#715]
If I try to move the cursor passed the end of a block of text, Windows chimes a sound.  How can I disable all such sounds?

**Comment by osimons** [comment]
I use ```set bell-style none``` in ```~/.inputrc``` to silence all shell beeps.

**Comment by xiuluo** [comment]
(Sorry,My English is poor)This method does not take effect for VIM, you need to close the Windows Sound.you shuld Open the Control Panel -> Hardware and Sound Open -> Open Sound -> Sound Select -> Modify the critical stop sound scheme(打开控制面板——>打开硬件和声音——>打开声音——>选择声音——>修改关键性停止的声音方案)
![201608033](https://cloud.githubusercontent.com/assets/2190708/17364421/a988cc12-59b2-11e6-925f-54b3ede1016e.jpg)

**Comment by bennyyip** [comment]
`set bell-style none` doesn't works for me. I use `Volume Mixer` to mute `Console Window Host`.

**Comment by NelsonMinar** [comment]
bennyyip's suggestion to mute Console Window Host is the only thing that works for me.

But I still want a sound, just a nicer one. I think it's being played by the [Beep Driver](https://blogs.msdn.microsoft.com/larryosterman/2010/01/04/whats-up-with-the-beep-driver-in-windows-7/), which in Windows 10 plays the event "Critical Stop" which is "Windows Foreground.wav". It's a singularly horrible sound to have mapped to a console bell that rings every time bash completion is unhappy. You can set which sound is played in the Sound Driver (Windows Ding is better). Perhaps someone on the WSL team is equally annoyed by the sound and will sneak in a more mellifluous user experience.

**Comment by yveslange** [comment]
The solution of @xiuluo worked for me !!!

**Comment by paretech** [comment]
I wanted to let folks know that @osimons solution regarding bell in .inputrc worked for me after restarting bash/Ubuntu. I'm using Windows 10 Insider Preview 16278.

As of July 10, 2017 Ubunto Linux is now Available in the Windows Store. As such I could see this page getting some more attention in the near future.

**Comment by herrmanthegerman** [comment]
In Linux, I usually disable the audible bell and enable the visual bell by adding `set bell-style visible` to `~/.inputrc` or `/etc/inputrc` as I find the flashing terminal less annoying than the audible bell.

While this works in WSL in term of silencing the audible bell, it does not enable the visual bell. I wonder whether this is worth filing a separate bug...

**Comment by yoctozepto** [comment]
This is not a bug, this is a feature. :-)

For bash (and other readline-based programs) use:
`set bell-style visible`
in
`~/.inputrc`

For vim use:
`set visualbell`
in
`~/.vimrc`

However, visual bells do not seem to work. I will file another bug report.

**Comment by eL0ck** [comment]
Great solution @yoctozepto. 

The problem with @xiuluo 's solution is that it is disabling the 'critical stop' sound for every application on the machine. It is unclear which key combination @xiuluo is using to produce this noise but my problem in WSL/VIM was coming from TAB autocomplete and was playing the 'Default Beep' sound.

@yoctozepto 's solution fixes all sounds on vim (tab complete, ESC etc) and in bash whilst leaving them available outside.

**Comment by mbpakalin** [comment]
@eL0ck Yea, that fixed mine too. But in vim i can still hear that annoying sound :(

**Comment by yoctozepto** [comment]
@mbpakalin Make sure vim read ~/.vimrc successfuly.

**Comment by mbpakalin** [comment]
@yoctozepto I forgot adding the .vimrc stuff, now i added `set visualbell` and its working now.
Thanks.

**Comment by sargentogato** [comment]
@yoctozepto solution works for me. I added 

set bell-style visible

**Comment by bjtucker** [comment]
I added the same 
`set bell-style visible`
to my .inputrc
... it stopped the noise, but there's no visible bell. I guess I'll take it.

**Comment by JHBalaji** [comment]
Another way is to open the Volume Mixer by right clicking on the volume control in the Windows taskbar and mute the Console.

![image](https://user-images.githubusercontent.com/304528/81005977-64cf0380-8e14-11ea-96a9-1307ee2cd409.png)

**Comment by qfan** [comment]
This is a feature but can we have a feature to disable this feature?

Particularly, can we have an option in the WSL itself to permanently remove the "hardware support" presented to the sub system? So that disabling this sound will no longer be system and software dependent?

**Comment by hugoam** [comment]
@yoctozepto solution kind of works, until you do for example a `git diff` and there again is this obnoxious bell sound

**Comment by chilipepper987** [comment]
"Console Window Host" doesn't show up in my volume mixer. I edited the file for "Windows Default Beep" (not Critical Stop) to fix it.

**Comment by wellloy1** [comment]
Tired of fixing this..
Disabling all system sounds on Win has been the most effective solution of my life.
I can't explain why I didn't do this sooner.
NEVER EVER system sounds on my Win. 
You
just
don't
need
that
sh$t.

**Comment by JonathanDotCel** [comment]
Yep, can we have an option to shut this up please, and store the setting from the Windows side of things please?
It's a bit tiresome having to re-set the volume via the sound mixer every so often.
Thanks.

**Comment by wellloy1** [comment]
> Yep, can we have an option to shut this up please, and store the setting from the Windows side of things please? It's a bit tiresome having to re-set the volume via the sound mixer every so often. Thanks.

Bro, you can disable all systems sounds via system settings. I think we don't need it in 2022. 😉
