### ISSUE TITLE
WSL installed but no distro when run Bash

### ISSUE THREAD

**Issue by fortAtheo** [microsoft/WSL#7151]
### Windows Build Number

Windows Versin 20H2 (OS Build 19042.a052) 64 bit

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.0

### Distro Version

Ubuntu 20.04

### Repro Steps

In Powershell as Admin, enable WSL and VM, and reboot.
Windows Versin 20H2 (OS Build 19042.a052) 64 bit
Updated WSL2 Linux kernel
Set WSL 2 as default
Installed Ubintu 20.04 LTS
Set up username and password
Set up completed
Admin user prompt appear
Run Bash in cmd and get this message
"Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore"

### Expected Behavior

I should be able to run Bash in cmd.

### Actual Behavior

Run Bash in cmd and get this message
"Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore"

**Comment by fortAtheo** [comment]
I will try to get it. Thanks.

Fort Hui
IT Support Analyst
Agriculture and Agri-Food Canada / Government of Canada
***@***.******@***.***> / Cel: 226-332-0923 / Tel: 226-217-8303

Analyste de soutien de la TI
Agriculture et Agroalimentaire Canada / Gouvernement du Canada
***@***.******@***.***> / Cel: 226-332-0923 / Tél. : 226-217-8303

***@***.***D56A09.D0463690]

**Comment by fortAtheo** [comment]
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: bipasha123
New password:
Retype new password:
passwd: password updated successfully
Installation successful!
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.72-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Jul  8 14:05:22 EDT 2021

  System load:  0.08               Processes:             8
  Usage of /:   0.4% of 250.98GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 172.25.94.188
  Swap usage:   0%

0 updates can be installed immediately.
0 of these updates are security updates.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update


This message is shown once once a day. To disable it please create the
/home/bipasha123/.hushlogin file.

bipasha123@ONGUELA686874P:~$ sudo apt update
[sudo] password for bipasha123:
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

Reinstalled again and get the error after it. And run Bash in cmd and get the following:
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

**Comment by OneBlue** [comment]
Thank you @fortAtheo. 

Can you please [collect logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) of the issue and upload them here ?  (see the 'record-wsl-logs-manually' section)
