### ISSUE TITLE
Linux fanotify api does not appear to be working on WSL2

### ISSUE THREAD

**Issue by capiro** [microsoft/WSL#7153]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

Debugging in Visual Studio Code app that uses fanotify api.

### Repro Steps

Just trying to understand if the api is supported or not.

### Expected Behavior

Program should received fanotify events

### Actual Behavior

No events are received.

### Diagnostic Logs

No logs available

**Comment by craigloewen-msft** [comment]
Are you running this on /mnt/c? I believe you're seeing this issue which we are tracking here: https://github.com/microsoft/WSL/issues/4739

A quick work around is to store your files in the Linux file system and use VS Code Remote!
