### ISSUE TITLE
Cannot locate WSL 2 vEthernet Properties (on Windows 11)

### ISSUE THREAD

**Issue by petersmagnusson** [microsoft/WSL#7155]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Control Panel > Network Connections
Look for "vEthernet (WSL)" adapter (or similar).

### Expected Behavior

Should see a dialog box for the vEthernet (WSL) adapter.

### Actual Behavior

It's not showing up.  It's working fine.  It's showing up with "ipconfig":

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : <cut>
   IPv4 Address. . . . . . . . . . . : <cut>
   Subnet Mask . . . . . . . . . . . : 255.255.240.0

As well as:

PS C:\WINDOWS\system32> Get-VMNetworkAdapter -All

Name                   IsManagementOs VMName SwitchName     MacAddress   Status IPAddresses
----                   -------------- ------ ----------     ----------   ------ -----------
Container NIC <snip> True                  Default Switch <snip> {Ok}
Container NIC <snip>  True                  WSL            <snip> {Ok}

From the Device Manager (with Show Hidden) I can see "Wi-Fi Direct Virtual Adapter", but from that UI I cannot access "Properties".

My objective is to experiment with Large Send Offload Version 2 (IPv4) to try to get better download performance within WSL 2.

I can find the WSL Virtual Switch in the Virtual Switch Manager from Hyper-V Manager, but, again, cannot access adapter properties from there.

Yes, I can use "Disable-NetAdapterLso" (and I can query state with "Get-NetAdapterLso -Name *") and that changes the adapter, but, shouldn't it be visible somewhere in the UIs?

(I fear I am missing something (very) obvious ...)

**Comment by petersmagnusson** [comment]
Perhaps related, but, I can't make the (command line) Set-NetAdapterLso commands "stick" to the adapter. I am able to disable LSO, and then (after recovering the way DNS then breaks down by manually modifying resolv.conf and doing the "chattr +i" magic on it.  But on (host) system restart, kicking WSL off again sets LSO defaults back to being "True".

(Note, the reason for all the above is to fix WSL 2 download speeds.  The fix for me works, eventually, with a 50x performance boost ...  so the struggling is worth it, but, should this really be so cumbersome to adjust?)

**Comment by benhillis** [comment]
@petersmagnusson - I think what's happening is you're modifying the host adapter on the WSL2 network, not the adapter in the VM.

**Comment by petersmagnusson** [comment]
> @petersmagnusson - I think what's happening is you're modifying the host adapter on the WSL2 network, not the adapter in the VM.

you mean with respect to why the "Disable-NetAdapterLso" command is not "sticking"?   (because to be clear, the changes "work" in the sense that download speed *is* fixed.)
