### ISSUE TITLE
wsl --update being an unknown command

### ISSUE THREAD

**Issue by StormProductionsMusic** [microsoft/WSL#7156]
### Windows Build Number

Windows 10 20H2 (64-bit) build 19042.1081

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:

### Distro Version

Kali Linux 2021.2

### Other Software

I'm always getting an error when running swl --update in CMD. It just shows as an unknown command, showing me other commands I can use instead.

### Repro Steps

Simply register to Insider Build, update till the latest Release Preview, and then try running swl --update into your CMD.

### Actual Behavior

C:\Users\nicus>wsl --update
Invalid command line option: --update
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.

C:\Users\nicus>

**Comment by sirredbeard** [comment]
--update requires [build 20175 or higher](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175). You are on 19042.

**Comment by StormProductionsMusic** [comment]
How do I make my insider program update to that build? 
I'm on Release Preview channel and it says I'm up to date.

**Comment by benhillis** [comment]
You will have to switch to the Dev Insider channel.

**Comment by StormProductionsMusic** [comment]
I can't, as it will try downloading Windows 11, which is not compatible with my device.
Any other way around?
