### ISSUE TITLE
Where can I get Incremental patch from vanilla linux kernel to WSL2-linux-kernel

### ISSUE THREAD

**Issue by hollowknight** [microsoft/WSL#7157]
Where can I get Incremental patch from vanilla linux kernel to WSL2-linux-kernel?

Thank you

**Comment by 0xbadfca11** [comment]
Merge these commits with using git.
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/MSFT-Merge/log

**Comment by hollowknight** [comment]
> Merge these commits with using git.
> https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/MSFT-Merge/log

thank you, I will try
