### ISSUE TITLE
Ubuntu extremely slow on /mnt/d (hdd)

### ISSUE THREAD

**Issue by ZeruxMiatoll** [microsoft/WSL#7158]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.43.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Jun 16 23:47:55 UTC 2021

### Distro Version

Ubuntu 20.04

### Other Software

none

### Repro Steps

zerux@DESKTOP-RESND2P:~$ sudo su
[sudo] password for zerux:
root@DESKTOP-RESND2P:/home/zerux# cd /mnt/d/kernel/ZeruxMiatoll
bash: cd: /mnt/d/kernel/ZeruxMiatoll: No such file or directory
root@DESKTOP-RESND2P:/home/zerux# cd /mnt/
root@DESKTOP-RESND2P:/mnt# cd d
root@DESKTOP-RESND2P:/mnt/d# cd kernel
root@DESKTOP-RESND2P:/mnt/d/kernel# cd ZeruxKernel
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# KERNEL_DIR=$(pwd)
ENT_DIR="$(dirnamroot@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# PARENT_DIR="$(dirname "$KERNEL_DIR")"
N_IMG=$KEroot@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# KERN_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# CONFIG_PATH=$KERNEL_DIR/arch/arm64/configs/$CONFIG
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# export PATH="$PARENT_DIR/proton-clang/bin:$PATH"
rt LD_LIBRARY_Proot@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# export LD_LIBRARY_PATH="$PARENT_DIR/proton-clang/lib:$LD_LIBRARY_PATH"
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# export KBUILD_BUILD_USER="Miatoll"
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# export KBUILD_BUILD_HOST="kernel"
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# export TZ="Europe/Paris"
root@DESKTOP-RESND2P:/mnt/d/kernel/ZeruxKernel# make O=out ARCH=arm64 cust_defconfig
make[1]: Entering directory '/mnt/d/kernel/ZeruxKernel/out'
#
# configuration written to .config
#
make[1]: Leaving directory '/mnt/d/kernel/ZeruxKernel/out'
make -j$(nproc --all) O=out \
>                           ARCH=arm64 \
>                           CC=clang \
>                           LD=ld.lld \
>                           AR="llvm-ar" \
>                           NM="llvm-nm" \
>                           OBJCOPY="llvm-objcopy" \
>                           OBJDUMP="llvm-objdump" \
>                           STRIP="llvm-strip" \
>                           CROSS_COMPILE=aarch64-linux-gnu- \
>                           CROSS_COMPILE_ARM32=arm-linux-gnueabi-
make[1]: Entering directory '/mnt/d/kernel/ZeruxKernel/out'

### Expected Behavior

normally compilation take only 7min on my ssd (wsl ubuntu)

### Actual Behavior

Compile take soo long time on /mnt/d between of ubuntu or here that take only 7min for compile it

### Diagnostic Logs

none

**Comment by craigloewen-msft** [comment]
This is tracked in the long standing issue here: https://github.com/microsoft/WSL/issues/4197

We are investigating ways to improve cross os file perf in WSL 2, for an immediate work around I'd recommend putting your files in the Linux File system (Like /home/craig for me). I'll close this out as a dupe!

/dupe #4197
