### ISSUE TITLE
from cmd prompt as administrator, after removing wsl; wsl --install and wsl.exe --install Invalid command line option: --install

### ISSUE THREAD

**Issue by ubhub** [microsoft/WSL#7160]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1083]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Other Software

Visual Studio Code 1.57.1
[wsl-install-fail.log](https://github.com/microsoft/WSL/files/6781451/wsl-install-fail.log)
[wsl-version-nil.log](https://github.com/microsoft/WSL/files/6781452/wsl-version-nil.log)
[wsl-status-nil.log](https://github.com/microsoft/WSL/files/6781454/wsl-status-nil.log)

### Repro Steps

I've been running ubuntu 20 but unable to run GUIs, although I thought gedit worked once. Certainly not nautilus. 
I followed https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps to have GUIs working on my ubuntu distro. Have a recurring problem arising when trying to run  a GUI. This is one from nautilus attempt.
...cannot autolaunch D-Bus without X11 $DISPLAY 
Unable to init server: Could not connect: Connection refused
(org.gnome.Nautilus:22): Gtk-WARNING **: 13:32:27.503: cannot open display:
I installed the intel graphics adaptor upgrade as recommended but it shoed no apparent change in the driver that I can read. I determined the problem was not having hyper-v. I bought a win 10 pro upgrade and installed without changing any of my WSL. Since having no more success, I reinstalled ubuntu twice I think. Once with unregistering and then installing from windows store .exe file. I later reinstalled from settings with app reset. Last, I've unregistered ubuntu again and removed wsl through windows apps. 
"From "Apps & Features" (a.k.a. "Add or remove programs") in Windows, remove the "Windows Subsystem for Linux Update". I'm fairly certain this is the Linux kernel update. Probably reboot if you want to be sure it's fully gone before the next step.
From "Turn Windows Features on or off" in Windows, disable the "Virtual Machine Platform". This is the WSL2 Hyper-V support. Probably reboot if you want to be sure it's fully gone before the next step.
From "Turn Windows Features on or off", disable "Windows Subsystem for Linux."
https://superuser.com/questions/1619233/completely-rei
After reboot I've returned to https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps and attempted to run wsl --install or wsl.exe --install. Have no result.

### Expected Behavior

I wasn't able to have wsl --install or wsl --update recognised before removing distro and wsl. And now I still don't. When I last ran the distro ubuntu, the drop down in windows terminal was showing ubuntu only and not ubunt 20.4 which it would have before. I don't know if that's relevant. Now I can even run gedit. I was sure I had that running before. 
Have no inkling of seeing any GUI running from my distro. Feeling foolish now for buying a pro upgrade.

### Actual Behavior

Expecting responses to the like of wsl --status from the cmd line as is instructed. Expect to have a working gedit but, was hoping more to be able to run the sqlite browser. I can't run so much as gedit now.

**Comment by benhillis** [comment]
You need Windows 10 Insider Preview build 21362+
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites

**Comment by ubhub** [comment]
I’m running version 21H1. But I’ll try to upgrade if I can attain the correct link.
brian

***@***.***D77414.7B531790]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ubhub** [comment]
I can’t attain the build through insider program. The optional diagnostics option is grayed out and I believe I need that on in order to have access to the pre-releases.
Brian
***@***.***D77416.5B80CFF0]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ubhub** [comment]
Can anyone help with this? As I understand, I need to have the optional diagnostics data switch on. I can't access it. It's grayed out. I've tried to run settings as administrator through task scheduler but can't crack it. I am administrator in my normal login. But can't work out how to run this task as an administrator. I am trying to get the windows 11 build so that I can run GUIs on my WSL.
