### ISSUE TITLE
Can't import Fedora 33

### ISSUE THREAD

**Issue by Codeer12** [microsoft/WSL#7161]
### Windows Build Number

Microsoft Windows 11 Preview [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Repro Steps

wsl --import Fedora-33 "C:\distros\Fedora-33\fedora-33.20210513-x86_64.tar" "C:\Users\MaxGa\Downloads\"

### Expected Behavior

Supposed to import Fedora 33

### Actual Behavior

`The system cannot find the path specified.`
![image](https://user-images.githubusercontent.com/39409827/124873821-f4ca8900-df94-11eb-87d8-083d08b19b64.png)

**Comment by Biswa96** [comment]
Where did you get the fedora-33.20210513-x86_64.tar file from?

**Comment by Codeer12** [comment]
[https://fedoramagazine.org/](url)

**Comment by Biswa96** [comment]
There are multiple article, which one?

**Comment by Codeer12** [comment]
my bad; here's a direct link

[https://fedoramagazine.org/wsl-fedora-33/](url)

**Comment by Biswa96** [comment]
The command is wrong in your original post. The correct one would be `wsl --import <Distro> <InstallLocation> <FileName> [Options]`. You've swap the commandline parameters InstallLocation and FileName.

**Comment by Codeer12** [comment]
But C:\Distros is where the Fedora system is installed.

**Comment by Codeer12** [comment]
I've now realized my mistake, but now it says it can't find the file specified.
![image](https://user-images.githubusercontent.com/39409827/125152336-f6718980-e119-11eb-9f59-bd8c027d5030.png)

**Comment by Codeer12** [comment]
Now I feel stupid🤦‍♂️
I flipped the paths and instead put where Fedora is installed and it's working now. Thanks for the help!

**Comment by Codeer12** [comment]
frffrefuillokjkjijuhyggfgfggyygyhbhghghjgfgftgu[pdrstdtrfguukhhuhhjuhhyugugy
