### ISSUE TITLE
WSL cannot install Ubuntu releases in win11

### ISSUE THREAD

**Issue by vaualbus** [microsoft/WSL#7163]
### Windows Build Number

22000.51

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

When trying to install a new ubuntu distro errors occours.

### Expected Behavior

I cannot install any Ubuntu distro in win11. After I write wsl --install -d Ubuntu a new PowerShell windows open and start installing than two errors occurs:
Two line are shown saying The parameter is incorrect. than the terminal show me to enter a user name. Not metter which username I put it errors saying The parameter is incorrect. 
The distro that updated from win10 worked fine. I attach an image to make it clear. I run this with preview terminal version:
![image](https://user-images.githubusercontent.com/1986920/124963970-c0041380-e020-11eb-855c-ca66482ca68a.png)

A part from this I can still use the installed distr by typing wsl but no user is created so I am at the same level as the cmd windows and the default path is the windows user path .

### Actual Behavior

I should be able to add new distros without any error.

**Comment by vaualbus** [comment]
It turns out this have to do with the interection with windows terminal. If I switch back the default terminal to cmd and run the wsl  install command from cmd.exe with cmd.exe as conhost I do not got any errors. Shall I open a bug report also on the terminal github?

**Comment by adrastogi** [comment]
Based on the info in your report, it sounds like the known issue [here](https://github.com/microsoft/terminal/issues/10134).

**Comment by vaualbus** [comment]
I think it's an entaglement of different bugs because apparently in today win11 update they noted that they fix something realting to The parameter is incorrect. So I guess is multiple things going on at the same time?

**Comment by craigloewen-msft** [comment]
@vaualbus based on your earlier comment, we can conclude that this is Terminal related, is known and is is already fixed by the Terminal team (Yay!). So in later builds this use case should be good to go. 

I'll close this out since there aren't any actionable items for us. Thank you for filing!
