### ISSUE TITLE
<3>init: (4830) ERROR: UtilConnectUnix:467: connect failed 111 - When gnome-terminal is opened with shortcut

### ISSUE THREAD

**Issue by swinder0161** [microsoft/WSL#7166]
created gnome-terminal shortcut with wslusc

in shortcut properties, command is: C:\Users\swind\AppData\Local\Microsoft\WindowsApps\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\ubuntu2004.exe run "cd ~;  gnome-terminal"

run gnome-terminal using shortcut

interop doesnot work

![image](https://user-images.githubusercontent.com/397543/125206251-f00f1900-e2a3-11eb-91d3-cceffb87b76c.png)

**Comment by craigloewen-msft** [comment]
Hi @swinder0161 could you please refile this bug report with the template added? This helps us have all the right info to solve your problem. Thank you!

**Comment by swinder0161** [comment]
https://github.com/microsoft/WSL/issues/7174 new bug created with template

**Comment by caioeserpa** [comment]
Hi, someone can help me?

$ docker compose up -d
<3>init: (9182) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9183) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9184) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9185) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9186) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9187) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9188) ERROR: UtilConnectUnix:467: connect failed 111
[+] Running 0/0
 ⠋ postgres Pulling                                                                                                                   0.0s
 ⠋ redis Pulling                                                                                                                      0.0s
 ⠋ airflow-scheduler Pulling                                                                                                          0.0s
 ⠋ airflow-worker Pulling                                                                                                             0.0s
 ⠋ airflow-init Pulling                                                                                                               0.0s
 ⠋ airflow-webserver Pulling                                                                                                          0.0s
 ⠋ airflow-triggerer Pulling                                                                                                          0.0s
error getting credentials - err: exit status 255, out: ``
