### ISSUE TITLE
Please include "FreeBSD" a pure UNIX distro. That would be awesome.

### ISSUE THREAD

**Issue by rajhlinux** [microsoft/WSL#7167]
You have Linux distros WSL, this is nice.

 It would be better to have a UNIX distro such as "FreeBSD" could be called WSU (windows subsytem unix).

**Comment by craigloewen-msft** [comment]
Hi @rajhlinux , all distros come from the distro maintainers themselves! This is a great request, but unfortunately not something that we can help with in the future so I'll close it out. I'd recommend reaching out to the owners of FreeBSD and asking them to create a WSL distro!
