### ISSUE TITLE
WSL2 causing "bluescreen" on W11

### ISSUE THREAD

**Issue by totalgaara** [microsoft/WSL#7168]
### Windows Build Number
22000.65

### Quick Hardware Info : 
CPU : AMD FX 8320
RAM : 16 GB of DDR3
GPU : AMD Sapphire R9 290

### WSL Version
* [x]  WSL 2
* [x]  WSL 1

### Repro Steps
When trying to install a distrubution, a bluscreen/greenscreen errors occours.

### Explanation of the issue
Hello,
I wanted to try WSL2 on my computer, however I encounter a problem that I can't fix. As soon as the installation of a distribution of my choice starts (whatever it's Ubuntu or Debian or something else..), the computer freezes and then displays a "bluescreen". 

I have tried to activate WSL by several means, by hand by adding the functionality, by command line, however the result is the same.

By curiosity I also tried with WSL 1, this time it works but makes the system very unstable, freezing and blue screen "HYPERVISOR ERROR" after a while

I also noticed something weird form the device manager :  

![Screenshot_1](https://user-images.githubusercontent.com/1378194/125316278-43cb4200-e338-11eb-8690-010565edf551.png)

Here is some picture of the bluescreens : 

When using WSL 1 : 
![IMG_20210711_183947](https://user-images.githubusercontent.com/1378194/125316538-7e34df00-e338-11eb-901e-a41316c4a0e2.jpg)

When using WSL 2 : (the screen was before i join back the insider program)
![IMG_20210707_115338](https://user-images.githubusercontent.com/1378194/125316580-89880a80-e338-11eb-8a91-b3df722e10e8.jpg)

Thank for your help

**Comment by craigloewen-msft** [comment]
@totalgaara can you please take a Feedback Hub logs here on your machine and post the link to the Feedback Hub item here? This will help us determine what's going on.

/logs

Could you also please attach the C:\Windows\MEMORY.DMP file to the FeedbackHub item?

**Comment by totalgaara** [comment]
Hello, Thank you for your answer

Unfortunately, I don't have any files that I can provide because they are not present on the system.

When a bluescreen occurs, the computer freezes completely and the BSOD status remains blocked at 0% even after 10 minutes, forcing me to shut down the computer so I think that unfortunately the dump does not occur

I have some news however, I saw that the AMD FX had this problem at one time, it concerned a problem with the AVX instructions as far as i could understand

This command allowed to disable them if I understand well, something I did by typing :

bcdedit /set xsavedisable 1

and this time the installation that it is in WSL1 or 2 of a distribution becomes possible without that the computer does not crash... at least it does not have BSOD during approximately 3 hour. Unfortunately the problem continues in spite of this light improvement

I've made a Insider Hub feedback for that, but unforurtunaly, i can't provide dump :/

https://aka.ms/AAd6s1o

Thanks for your help :)

**Comment by craigloewen-msft** [comment]
That's helpful! If you ever do get a dump please file it as a feedback hub item, we'll take a look at what you provided. Thanks!

**Comment by totalgaara** [comment]
I got it ! I've send it to my feedback hub link  :)

**Comment by totalgaara** [comment]
Hello,

I have a second error code that could help solve the problem, at first I thought it was not related to the use of WSL but forced to note that when the virtualization is disabled I do not encounter "Hypervisor_error" or "CLOCK_WATCHDOG_TIMEOUT"

This morning I activated the virtualization, I was able to use WSL during approximately one hour before having this new error code forcing me to deactivate the virtualization again because with the reboot I had immediately after connection a freeze of the system

I have published the dump on the comment hub and also on my one-drive link above (just in case)

Kind regards :)

**Comment by craigloewen-msft** [comment]
@totalgaara I've downloaded those files, could you please remove them from OneDrive (just to be safe on the security side :) )

I've also made sure that the Hyper-V team has these files available to take a look. Please let us know if you keep seeing this and if you find any work arounds. Thank you for your help here!

**Comment by totalgaara** [comment]
Hello,
I did remove the files from my Onedrive :) Thanks again for your answer.

Unfortunately the problem continues and I can't really find a solution on my side, I have the impression that I have done everything possible, reinstall the graphics driver, try with an older version, I did the same thing with the driver of my network card because I saw on some forums that some Realtek cards were a source of problem, unfortunately not in my case, I also installed the driver manufacturer of my motherboard for the USB ports

I also tried to disable the maximum of features in the bios to try to isolate the problem, but again it is not conclusive, the problem continues.

I have the impression however that it is not the WSL module that is at fault but more "Windows hypervisor platform".

I understood that the Windows hypervisor was of type 2, so to make some tests. :

I temporarily unchecked the functionalities necessary for the operation to install a proprietary hypervisor (VMWare) which is also of type 2, with this one I didn't really have any BSOD except for 1 which concerned "VMWare USB Arbitration Service" so this is the one which gave me the idea to update the USB driver using the one by the manufacturer of my motherboard (Gigabyte).

Of course I'm still mainly motivated by the use of WSL so I also proceeded to a complete system check:

sfc /scannow : No integrity problem detected
DISM /Online /Cleanup-Image /CheckHealth : No problem
DISM /Online /Cleanup-Image /ScanHealth : No problem


One interesting thing about my brother's computer, it has a perfect copy of my configuration except for my motherboard which is slightly different

_Mine is :_
**CPU:** AMD FX 8320
**GPU** : AMD R9 290
**MB :** Gigabyte GA-970A-DS3P FX
**North Bridge:** AMD 990FX
**South Bridge:** AMD SB950

_My brother's configuration :_ 
**CPU:** AMD FX 8320
**GPU:** AMD R9 290
**MB:** Gigabyte GA-970A-DS3P
**North Bridge:** AMD 970
**South Bridge:** AMD SB950

My brother does not participate in the Windows Insider program, so it is currently under Windows 10 I have with his permission tried to use WSL on his computer and he has no problem, everything works normally, I have for example in no need  to enter the command

```bcdedit /set xsavedisable 1```

While on my configuration, if I do not enter it, the BSOD is immediate when i try to launch Ubuntu or something else

I hesitate therefore that to eliminate some doubt possibly make a dualboot with Windows 10 and see if with I have the same problem?

It is probably the tests that I will make today and give some feedback :)

Thanks again

**Comment by craigloewen-msft** [comment]
Hi @totalgaara I brought this to the attention of the Hypervisor team. From the memory dump we identified that this is a hardware issue with your processor. We would recommend that you contact AMD to ask them why the IOMMU flushes timeout on this system and see if they can resolve you. Since this is hardware related, we don't have a way of solving it directly on the WSL team so I'll close this issue out for bookkeeping purposes. Thank you for filing this feedback for us!

**Comment by asvishnyakov** [comment]
@totalgaara Did you find the way to fix it? I'm getting something similar with Hyper-V and WSL and I have similar configuration: AMD FX-8150 and Gigabyte GA-990XA-UD3. I also saw a lot of similar issues on Microsoft-related resources, but common solutions like disabling IOMMU, USB3 support or `bcdedit /set xsavedisable 0` aren't working for me. Did you get a chance to somehow get virtualization working with Windows 11?
