### ISSUE TITLE
There are no more endpoints available from the endpoint mapper

### ISSUE THREAD

**Issue by mojodevops** [microsoft/WSL#7170]
### Windows Build Number

Microsoft Windows [版本 10.0.19043.1052]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux PC 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

### Distro Version

Ubuntu 20.04

### Repro Steps

Env:
Microsoft Windows [版本 10.0.19043.1052]
版本 Windows 10 企业版
版本号 21H1
安装日期 ‎2021/‎6/‎26
操作系统内部版本 19043.1083
体验 Windows Feature Experience Pack 120.2212.3530.0

Problem:
After a  reboot, when execute wsl, i got "终结点映射器中没有更多的终结点可用", There are no more endpoints available from the endpoint mapper.

When use WSL 2, i got this error, and found it was related to windows ICS service which displayed as Internet Connection Sharing(ICS) and named SharedAccess in services.msc.
Recently, my machine installed KB5004945 and rebooted, then i found ICS service was disappeared.
Before that, i had the ICS service and WSL 2 worked well.
Another PC of mine has the ICS service and WSL 2 works well.
WSL 1 worked correctly.

### Expected Behavior

Using wsl to connect my wsl ubuntu 20.04.

### Actual Behavior

When execute wsl, i got "终结点映射器中没有更多的终结点可用", There are no more endpoints available from the endpoint mapper.

**Comment by craigloewen-msft** [comment]
Could you please file logs for this issue? 

The [instructions are here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually), and could you then add the logs to this thread?

**Comment by licanhua** [comment]
maybe you can try this:

https://github.com/microsoft/WSL/issues/5845#issuecomment-879241809

**Comment by dingzhengkai** [comment]
> maybe you can try this:
> 
> [#5845 (comment)](https://github.com/microsoft/WSL/issues/5845#issuecomment-879241809)

did not work

**Comment by dingzhengkai** [comment]
@craigloewen-msft  i used both of windows feedhub and manual collect log, but feebhub seems having private info, so just upload wsl.etl.
[wsl.zip](https://github.com/microsoft/WSL/files/6813092/wsl.zip)

**Comment by dingzhengkai** [comment]
In my case, i lost the ICS service, that caused the problem.
Several days ago, when i reinstalled the OS, ICS worked well, and WSL 2 worked well, but recently ICS disappeared again.

**Comment by craigloewen-msft** [comment]
@dingzhengkai are you still seeing networking issues related to this?

**Comment by dingzhengkai** [comment]
> @dingzhengkai are you still seeing networking issues related to this?

I didn't know how to repair ICS service when is disappeared, though i googled some articles, so i thought the problem may still there.

**Comment by licanhua** [comment]
Don't know if you have same problem with this or not: https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/ics-not-work-after-computer-or-service-restart

**Comment by dingzhengkai** [comment]
This image was captured from a machine on which WSL 2 was **working**.
![image](https://user-images.githubusercontent.com/7904001/128128500-c12e9290-f369-48b1-b868-0b6cc31087af.png)

This image was captured from a machine on which WSL 2 is **not working**.
**ICS disappeared.**
![image](https://user-images.githubusercontent.com/7904001/128128868-a13bc56f-c419-4e93-9886-6594849f8c1f.png)

@licanhua ICS service disappeared, which caused the problem.

**Comment by rwibm** [comment]
I appreciate this is an old thread -- but is there any way to remove the ICS requirement in WSL2? My org does not allow ICS to be enabled due to security concerns with bridging internal and external networks, and since this has been required it has completely broken WSL for me.

It never used to be a requirement I swear, what changed?

Is there really no alternative? I really don't want to have to swap back to virtualbox :(

**Comment by SkippityPaps** [comment]
ICS is on. Endpoint mapping errors persist. 
Was working *just fine* 10 hours ago and now WSL gives endpoint mapping errors. No system changes. How is this possible?
