### ISSUE TITLE
"Could not open windows subsystem shell" on the vs2019

### ISSUE THREAD

**Issue by muse117** [microsoft/WSL#7172]
### Windows Build Number

Microsoft Windows [版本 10.0.19043.1083]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu

### Other Software

visual studio 2019

### Repro Steps

Probably after I ran the "sudo apt update" command, VS2019 cannot connect to WSL2 in WSL mode, but it can connect to WSL2 in SSH mode.

### Expected Behavior

I want VS2019 to be debugged through WSL.

### Actual Behavior

I want VS2019 to be debugged through WSL.

### Diagnostic Logs

1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018: “Compile”任务意外失败。
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018: System.AggregateException: 发生一个或多个错误。 ---> liblinux.Local.Shell.WindowsSubsystemShellException: Could not open windows subsystem shell ---> liblinux.Local.Shell.WindowsSubsystemShellException: Failed to start WSL process ---> liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.Open(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand[CommandType](CommandType command)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 Microsoft.Build.Linux.WSL.Tasks.Compile.<>c__DisplayClass55_0.<Execute>b__0(ITaskItem source)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.InnerInvoke()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.Wait()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 Microsoft.Build.Linux.WSL.Tasks.Compile.Execute()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018: ---> (内部异常 #0) liblinux.Local.Shell.WindowsSubsystemShellException: Could not open windows subsystem shell ---> liblinux.Local.Shell.WindowsSubsystemShellException: Failed to start WSL process ---> liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.WindowsSubsystemShell.Open(TimeSpan timeout)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    --- 内部异常堆栈跟踪的结尾 ---
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand[CommandType](CommandType command)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 Microsoft.Build.Linux.WSL.Tasks.Compile.<>c__DisplayClass55_0.<Execute>b__0(ITaskItem source)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.InnerInvoke()
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
1>E:\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.WSL.targets(264,5): error MSB4018:    在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by muse117** [comment]
> Could you please collect WSL logs while this is happening? It is possible WSL is failing to start which is why you're seeing this error.
> 
> /logs

WSL starts normally,  However, it cannot connect to WSL using VS2019. I attach logs of vs2019.

23:43:31.0219707 [Info, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: Connecting to WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:31.0319721 [Info, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho sentinel:ff79babf-910e-44f3-a2f2-2f1175d3f7c8 id:fa76e9a8-da30-4a27-8cc6-0fe33ab0561d
23:43:31.0329719 [Info, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: Writing "echo ff79babf-910e-44f3-a2f2-2f1175d3f7c8" to WSL shell
23:43:31.0379741 [Info, Thread 6]	liblinux.Local.Shell.WindowsSubsystemShell: Read async: fa76e9a8-da30-4a27-8cc6-0fe33ab0561d
23:43:31.2109720 [Info, Thread 5]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: CreateVisualStudioNotificationsTask delegate start
23:43:31.2119731 [Info, Thread 5]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: CreateVisualStudioNotificationsTask CreateLocalSysroot
23:43:31.2309744 [Info, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: Connecting to WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:31.2409745 [Info, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho sentinel:adb4febe-1cda-4979-a22f-223c6f6d0129 id:0c5d125d-cde2-4579-acf0-5780b67c1e53
23:43:31.2409745 [Info, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: Writing "echo adb4febe-1cda-4979-a22f-223c6f6d0129" to WSL shell
23:43:31.5471941 [Info, Thread 6]	liblinux.Local.Shell.WindowsSubsystemShell: fa76e9a8-da30-4a27-8cc6-0fe33ab0561d is exiting
23:43:31.5721911 [Info, Thread 10]	liblinux.Local.Shell.WindowsSubsystemShell: Read async: 0c5d125d-cde2-4579-acf0-5780b67c1e53
23:43:31.5741872 [Info, Thread 31]	liblinux.Local.Shell.WindowsSubsystemShell: Disconnecting from WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:31.5781883 [Info, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho failed fa76e9a8-da30-4a27-8cc6-0fe33ab0561d
23:43:31.5891862 [Error, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: Exception starting WSL process
23:43:31.6181889 [Error, Thread 13]	liblinux.Local.Shell.WindowsSubsystemShell: liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
23:43:31.6651925 [Info, Thread 10]	liblinux.Local.Shell.WindowsSubsystemShell: 0c5d125d-cde2-4579-acf0-5780b67c1e53 is exiting
23:43:31.6831881 [Info, Thread 31]	liblinux.Local.Shell.WindowsSubsystemShell: Disconnecting from WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:31.6831881 [Info, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho failed 0c5d125d-cde2-4579-acf0-5780b67c1e53
23:43:31.6841871 [Error, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: Exception starting WSL process
23:43:31.6841871 [Error, Thread 5]	liblinux.Local.Shell.WindowsSubsystemShell: liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
23:43:31.6841871 [Error, Thread 5]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: Exception during AfterUpdateHeaders
23:43:31.8071880 [Error, Thread 5]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: liblinux.Local.Shell.WindowsSubsystemShellException: Could not open windows subsystem shell ---> liblinux.Local.Shell.WindowsSubsystemShellException: Failed to start WSL process ---> liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.Open(TimeSpan timeout)
   在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
   --- 内部异常堆栈跟踪的结尾 ---
   在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
   在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand(String commandText, TimeSpan timeout)
   在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand(String commandText, Int32 timeout)
   在 liblinux.IO.PathUtils.GetFullPath(ICommandHost`2 shell, String remotePath)
   在 liblinux.Local.IO.WindowsSubsystemFileSystem.GetFullPath(String remotePath)
   在 liblinux.Services.RemoteCompiler.ExpandRemotePaths(IEnumerable`1 paths, HashSet`1 expandedPaths)
   在 liblinux.Services.RemoteCompiler.<CreateLocalSysrootAsync>d__115.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 liblinux.Services.RemoteCompiler.<UpdateSysrootForProjectAsync>d__111.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare.<>c__DisplayClass26_0.<<UpdateHeaders>b__0>d.MoveNext()
23:43:31.8071880 [Info, Thread 5]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: UpdateHeadersFailed Failed updating headers from 'wsl_wsl'.
23:43:32.0111870 [Info, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: Connecting to WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:32.0161876 [Info, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho sentinel:eb8512a4-5ac7-4a0a-b927-66521cc19640 id:857ac3ab-32b2-46c2-9402-800e42e6a28a
23:43:32.0161876 [Info, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: Writing "echo eb8512a4-5ac7-4a0a-b927-66521cc19640" to WSL shell
23:43:32.0161876 [Info, Thread 10]	liblinux.Local.Shell.WindowsSubsystemShell: Read async: 857ac3ab-32b2-46c2-9402-800e42e6a28a
23:43:32.4371863 [Info, Thread 10]	liblinux.Local.Shell.WindowsSubsystemShell: 857ac3ab-32b2-46c2-9402-800e42e6a28a is exiting
23:43:32.4871876 [Info, Thread 19]	liblinux.Local.Shell.WindowsSubsystemShell: Disconnecting from WSL at "C:\WINDOWS\sysnative\wsl.exe"
23:43:32.4891895 [Info, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho failed 857ac3ab-32b2-46c2-9402-800e42e6a28a
23:43:32.4921884 [Error, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: Exception starting WSL process
23:43:32.4931877 [Error, Thread 11]	liblinux.Local.Shell.WindowsSubsystemShell: liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
00:44:35.7384390 [Info, Thread 9]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: CreateVisualStudioNotificationsTask delegate start
00:44:35.9520549 [Info, Thread 9]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: CreateVisualStudioNotificationsTask CreateLocalSysroot
00:44:36.1534787 [Info, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: Connecting to WSL at "C:\WINDOWS\sysnative\wsl.exe"
00:44:36.6215104 [Info, Thread 15]	liblinux.Local.Shell.WindowsSubsystemShell: Read async: f5fe7529-fec8-4aea-a38b-3d4e093a8270
00:44:36.6215104 [Info, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho sentinel:6548958a-1984-4a2e-b4cd-a4beffe65bcf id:f5fe7529-fec8-4aea-a38b-3d4e093a8270
00:44:36.6215104 [Info, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: Writing "echo 6548958a-1984-4a2e-b4cd-a4beffe65bcf" to WSL shell
00:44:37.8248056 [Info, Thread 53]	liblinux.Local.Shell.WindowsSubsystemShell: f5fe7529-fec8-4aea-a38b-3d4e093a8270 is exiting
00:44:37.8268086 [Info, Thread 14]	liblinux.Local.Shell.WindowsSubsystemShell: Disconnecting from WSL at "C:\WINDOWS\sysnative\wsl.exe"
00:44:37.8268086 [Info, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho failed f5fe7529-fec8-4aea-a38b-3d4e093a8270
00:44:37.8660374 [Error, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: Exception starting WSL process
00:44:37.9101938 [Error, Thread 9]	liblinux.Local.Shell.WindowsSubsystemShell: liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
00:44:37.9976543 [Error, Thread 9]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: Exception during AfterUpdateHeaders
00:44:38.5837131 [Error, Thread 9]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: liblinux.Local.Shell.WindowsSubsystemShellException: Could not open windows subsystem shell ---> liblinux.Local.Shell.WindowsSubsystemShellException: Failed to start WSL process ---> liblinux.Local.Shell.WindowsSubsystemShellException: Echo command failing
   在 liblinux.Local.Shell.WindowsSubsystemShell.VerifyEcho(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---
   在 liblinux.Local.Shell.WindowsSubsystemShell.StartWSLProcess(TimeSpan timeout)
   在 liblinux.Local.Shell.WindowsSubsystemShell.Open(TimeSpan timeout)
   在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
   --- 内部异常堆栈跟踪的结尾 ---
   在 liblinux.Local.Shell.Commanding.LocalHostedCommand.Initialize(WindowsSubsystem windowsSubsystem)
   在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand(String commandText, TimeSpan timeout)
   在 liblinux.Local.Shell.Commanding.LocalCommandHost.ExecuteCommand(String commandText, Int32 timeout)
   在 liblinux.IO.PathUtils.GetFullPath(ICommandHost`2 shell, String remotePath)
   在 liblinux.Local.IO.WindowsSubsystemFileSystem.GetFullPath(String remotePath)
   在 liblinux.Services.RemoteCompiler.ExpandRemotePaths(IEnumerable`1 paths, HashSet`1 expandedPaths)
   在 liblinux.Services.RemoteCompiler.<CreateLocalSysrootAsync>d__115.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 liblinux.Services.RemoteCompiler.<UpdateSysrootForProjectAsync>d__111.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare.<>c__DisplayClass26_0.<<UpdateHeaders>b__0>d.MoveNext()
00:44:38.5837131 [Info, Thread 9]	Microsoft.VisualStudio.Linux.LinuxHeadersUpdateTaskBare: UpdateHeadersFailed Failed updating headers from 'wsl_wsl'.

**Comment by licanhua** [comment]
@muse117 The log you provided doesn't help too much, please submit the log from [Feedback Hub](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)
