### ISSUE TITLE
Old gcc "Value too large for defined data type" error

### ISSUE THREAD

**Issue by lcavalli** [microsoft/WSL#7175]
### Windows Build Number

Microsoft Windows [Versione 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2

### Distro Version

Arch Linux

### Other Software

Docker version 20.10.7, build f0df350 (Docker Desktop for Windows)

### Repro Steps

I have a quite old SPARC CPU (Leon) cross compiler toolchain based on GCC 4.4.2 (32 bit version). I create a docker image based on i386/debian:bullseye-20210621-slim and I can map a local folder to a folder in the docker image and execute a Makefile script. The native folder with my project source tree is into an NTFS Windows 10 filesystem, mounted to /mnt/c/<...snip...> inside WSL2. When GCC is executed the "Value too large for defined data type" error messgae is shown:

```
root@f43ac2c97451:/build# make
make[1]: Entering directory '/build/XxxXX'
Compiling src/startup.S
/opt/sparc-elf-4.4.2/bin/sparc-elf-gcc -ggdb -Wall -mtune=ut699 -mv8 -mfpu -nostdinc -fno-builtin -mno-app-regs -fno-common -fno-strict-aliasing -DMHZ=40 -I./../Common -O2 -c -o obj/startup.o src/startup.S
cc1: error: ./../Common: Value too large for defined data type
cc1: error: src/startup.S: Value too large for defined data type
make[1]: *** [Makefile:69: startup.o] Error 1
make[1]: Leaving directory '/build/XxxXX'
make: *** [Makefile:14: default] Error 2
```

I then tried to rebuild the docker image from a 64 bit debian (including i686 libc libraries to execute the toolchain) but the behaviuor was the very same as above.

After a google search it seems that the problem may be related to mounting options of native filesystem into WSL2.

I finally copied my whole project source tree into my home folder under WSL2 (ext4 in a vhdx image) and executed the docker image from there. The Makefile script completes without any error.

I have found that the issue #3472 is similar but it was closed without a clear solution.

### Expected Behavior

GCC executes without error messages.

### Actual Behavior

GCC stops with "Value too large for defined data type" error message.

**Comment by 0xbadfca11** [comment]
You need to build the entire 32-bit toolchain you are using with _FILE_OFFSET_BITS=64.
> https://www.mjr19.org.uk/sw/inodes64.html

**Comment by lcavalli** [comment]
Made a quick test with the LD_PRELOAD hack described in the link and it worked. Recompiling the toolchain _FILE_OFFSET_BITS=64 is the way to go.
Thank you.
