### ISSUE TITLE
Fedora 33 - can't install any Snaps

### ISSUE THREAD

**Issue by Codeer12** [microsoft/WSL#7176]
### Windows Build Number

Microsoft Windows 11 Preview [Version 10.0.22000.51]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Fedora-33

### Repro Steps

`sudo dnf install snapd`
`sudo snap install core`

### Expected Behavior

Snap is supposed to install core.

### Actual Behavior

`error: cannot communicate with server: Post "http://localhost/v2/snaps/core": dial unix /run/snapd.socket: connect: no such file or directory`
![image](https://user-images.githubusercontent.com/39409827/125687497-ce63f331-d208-4cbb-96f1-208afa9c3797.png)

**Comment by craigloewen-msft** [comment]
Snaps rely on systemd support and as of right now WSL doesn't support systemd. We're tracking this issue here:
https://github.com/microsoft/WSL/issues/994

I'll close this out as this is part of that feature request. Thanks for filing!

/dupe #994
