### ISSUE TITLE
wsl install end correctly but wsl is not executable

### ISSUE THREAD

**Issue by leonardinux** [microsoft/WSL#7177]
### Windows Build Number

Microsoft Windows [Versione 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

don't install

### Distro Version

debian latest

### Repro Steps

https://www.windowscentral.com/install-windows-subsystem-linux-windows-10

### Expected Behavior

debian wsl working

### Actual Behavior

Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:

**Comment by licanhua** [comment]
Have you input the username and password? You have to setup a default unix account during the installation. look like you didn't finish the installation.

**Comment by craigloewen-msft** [comment]
This is the expected behaviour from the new distro! It starts and you enter your Linux username and password and then you should be good to go. :)
