### ISSUE TITLE
ram limited after updating to KB5004237 

### ISSUE THREAD

**Issue by bwhitearg** [microsoft/WSL#7186]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 20.04

### Repro Steps

Running scripts in WSL2 via VSCode. Virtual machine never exceeds 2GB ram.

### Expected Behavior

WSL is actually able to use all the ram allotted to it in .wslconfig

### Actual Behavior

Was running a script I wrote a month ago to parse some PDF files, ran fine previously and would utilize the 16GB of RAM I assigned. After recent update, won't go past 2GB.

**Comment by benhillis** [comment]
Can you share the contents of your %userprofile%\.wslconfig file?
