### ISSUE TITLE
cudaErrorOperatingSystem on WSL2g

### ISSUE THREAD

**Issue by mw7301** [microsoft/WSL#7187]
Whenever  run the marchingCubes or the Mandelbrot nVidia CUDA graphical examples under WSL2g on Windows 11 build 22000.71 I get the error message "CUDA error at marchingCubes.cpp:484 code=304(cudaErrorOperatingSystem)". The non-graphical CUDA applications work fine it is the graphical ones that are having problems running.

**Comment by craigloewen-msft** [comment]
Hi @mw7301 can you please file a new issue with the full template filled out, and include logs for this problem? This info is invaluable to us to help fix your problem and we don't have enough info from what you provided above to help you yet. Thank you for filing and I'll look for a new issue with the logs!

**Comment by mw7301** [comment]
Where are these logs located?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by craigloewen-msft** [comment]
There's a link to instructions on how to collect these logs in the new issue template, as well as in the comment below

/logs
