### ISSUE TITLE
GET requests are working but all POST requests don't work 

### ISSUE THREAD

**Issue by amralica** [microsoft/WSL#7193]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC))

### Distro Version

20.04

### Other Software

GET requests are working but all POST requests don't work.
I can get the data in the browser but when I try to make a post request the request doesn't work,
when I switch back to the windows system it works fine.

thanks

### Repro Steps

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Expected Behavior

GET requests are working but all POST requests don't work.
I can get the data in the browser but when I try to make a post request the request doesn't work,
when I switch back to the windows system it works fine.

thanks

### Actual Behavior

GET requests are working but all POST requests don't work.
I can get the data in the browser but when I try to make a post request the request doesn't work,
when I switch back to the windows system it works fine.

thanks

### Diagnostic Logs

GET requests are working but all POST requests don't work.
I can get the data in the browser but when I try to make a post request the request doesn't work,
when I switch back to the windows system it works fine.

thanks

**Comment by craigloewen-msft** [comment]
Can you please collect logs for this issue using the instructions in the comment below?

/logs
