### ISSUE TITLE
WSL instances won't launch after installing Windows Version 10.0.22000.71

### ISSUE THREAD

**Issue by dsoselia** [microsoft/WSL#7195]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.71] 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 18.04

### Repro Steps

Launching Ubuntu 18.04, Ubuntu 20.04 after installing 22000.71

### Expected Behavior

Ubuntu instance starts, allows entering commands

### Actual Behavior

Freezes for a few minutes and crashes. Impossible to input any commands.
![ub18](https://user-images.githubusercontent.com/36576137/126051513-f178e949-f828-49b0-9aec-b4b84d210805.PNG)

**Comment by geneing** [comment]
KB5004252 breaks wsl. Uninstalling this patch restores wsl. Strangely, no changes to wsl are listed in the release notes.

**Comment by dsoselia** [comment]
Any way to get it working on KB5004252?

**Comment by benhillis** [comment]
I suspect you are hitting a known scsi timeout, could you try running wsl.exe --shutdown and launching again?

**Comment by ronburk** [comment]
> 
> 
> I suspect you are hitting a known scsi timeout, could you try running wsl.exe --shutdown and launching again?

This worked for me, and I could some message about an operation timing out flash briefly before the terminal would disappear.

**Comment by zzjin** [comment]
`wsl.exe --shutdown` slove my issue when upgrade from `22000.71` to `22000.100`.
But after upgrade `22000.100` to `22000.120` all wsl commands hang.
