### ISSUE TITLE
WSL2 CUDA/CUDF Unable to establish a shared memory space between system and Vram

### ISSUE THREAD

**Issue by EricPell** [microsoft/WSL#7198]
# Environment

```
Windows build number: 22000.65
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.25
```
# Steps to reproduce

Install python Rapids: `conda install -c nvidia -c rapidsai -c conda-forge  rmm cudatoolkit=11.2`

Execute this notebooks to create a merged memory space, and read a large object into the buffer: https://github.com/rapidsai/cugraph/blob/branch-21.08/notebooks/demo/uvm.ipynb

#  Expected behavior

Without enabling shared memory the full 12GB of VRAM is available to store data, confirmed by my own testing.

On a native Ubuntu machine, using the same cuda, python and ubuntu versions, that it works as expected, and creates a much larger shared memory space which allows an object larger than VRAM  to spill over from the GPU onto the system memory.

# Actual behavior

`MemoryError: std::bad_alloc: CUDA error at: /home/<username>/anaconda3/envs/rapids-21.06/include/rmm/mr/device/managed_memory_resource.hpp:73: cudaErrorMemoryAllocation out of memory`

On WSL2 the available memory buffer is full after loading only 1GB of the data set into memory, which goes to VRAM. It is as if the buffer was already initialized, perhaps as interop between Windows and WSL, and Python isn't making  a new larger memory space, but attaching to the existing one.

**Comment by aroidzap** [comment]
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-apps
