### ISSUE TITLE
WSL completely hangs - non-responsive, persistent after reboots

### ISSUE THREAD

**Issue by RooneyMcNibNug** [microsoft/WSL#7199]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Debian 10

### Repro Steps

Attempting to launch WSL2 Debain

### Expected Behavior

A functioning WSL terminal

### Actual Behavior

A blank, non-responsive and non-functioning terminal

### Diagnostic Logs

Very recently, Debain has abruptly stopped working for me. Now when I open it I don't even see the normal username and terminal prompt - it is just a completely blank terminal.

Corresponding services seem to be completely unresponsive in Task Manager/Services, and I can't even shut WSL down via CMD:

```
C:\Users\User>wsl.exe --shutdown
Server execution failed
```

This persists after multiple days worth of reboots of the host machine.

**Comment by zefie** [comment]
Last night I shut my PC down and this morning nothing WSL related is working. I was just using WSL yesterday. I am still running WSL 1 as far as I know, but even `wsl.exe --list` is just hanging indefinitely. my "Debian" entry in `Windows Terminal` also vanished! Not sure if its related.

**Comment by zefie** [comment]
> What's your Win Build Number, @zefie ?

19043

**Comment by FYHSSGSS** [comment]
So am I, I have the same problem as you.

**Comment by FYHSSGSS** [comment]
I solved this problem, I just reinstall the windows terminal, and the WSL is recovered.

**Comment by RooneyMcNibNug** [comment]
The screenshot in https://github.com/microsoft/WSL/issues/7195 is very similar to what I am experiencing here, FWIW.

**Comment by zefie** [comment]
> The screenshot in #7195 is very similar to what I am experiencing here, FWIW.

FWIW that screenshot shows that the user has entered terminal "select" mode which freezes execution of the underlying application. But if you are having the issue without "Select" mode then it is similar to the issue originally reported here.

**Comment by RooneyMcNibNug** [comment]
It doesn't really matter how I enter terminal - not even `wsl.exe` will launch successfully, it just hangs. I can't even check the status of things.

**Comment by vhawk19** [comment]
I have the same issue too.

**Comment by craigloewen-msft** [comment]
If you're seeing this issue can you please collect logs and post the link to the Feedback Hub item for them to this thread? That will help us determine what's going on. Instructions for this can be found below!

/logs

**Comment by RooneyMcNibNug** [comment]
Not entirely sure what changed tbh, but now my WSL Debian terminal loads appropriately and generally runs fine.

**Comment by craigloewen-msft** [comment]
That's very strange, but thank you for reporting it! Please reopen this issue if you see it again.
