### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370114

### ISSUE THREAD

**Issue by Amondale** [microsoft/WSL#7201]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

wsl --status returns verbose help only

### Distro Version

install time error

### Other Software

Docker was uninstalled, no change in behavior. Hyper-V components were removed prior to this error, also the 21H1 feature update was installed in the last few days (since Ubuntu prompt ran correctly).  I may try a recovery point if one is available. Windows Update indicates all current. 

### Repro Steps

pull ubuntu 20.04 LTS from Windows Store; Click Install button; following output is from powershell/cmd window entitled "Ubuntu":

### Expected Behavior

installs ubuntu 20.04 LTS distro

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.

Press any key to continue...

**Comment by Amondale** [comment]
HP Evo 360 with i7 8550 VT-X mode verified (Hyper-V ran OK)

**Comment by Amondale** [comment]
still working on Surface Pro 4 with all the same patches/features enabled? So must be HW-related? Any chance some PrintNightmare countermeasures are responsible? Same thing seemed to happen a year ago with a series of critical patches, somehow may have been "use case" didn't include hypervisor-based scenarios.

**Comment by Amondale** [comment]
missing Docker components?? C'mon, mystic error handler, throw me a frickin bone here!

**Comment by Amondale** [comment]
anywhere in eventvwr I should be looking for the root cause of "required components not installed"?

**Comment by Amondale** [comment]
or ... any way to clean up wsl2 components and install as if fresh? I would think if the (used to be) four hardware virtualization requirements weren't available, WSL2 wouldn't correctly install or instantiate.

**Comment by benhillis** [comment]
I suspect you're missing the "Virtual Machine Platform" optional component.

**Comment by Amondale** [comment]
Enabled/disabled that component a few times with reboots in between, using dism commands and control panel. Sure would b nice to see if anyone knows the 114 error code and the missing component it references. Docker no longer launches either.

**Comment by bpulliam** [comment]
For any issues where virtualization is failing, check the following(all use the same hresult):
1) Is the Virtual Machine Platform OC on?
2) Is virtualizaiton enabled in the bios?
3) Do you have another virtualization service installed (virtual box)?

**Comment by Amondale** [comment]
I think the issue dates to hyper-v previously installed  or recent security patches. Wonder if I might have screwed up the installation when I upgraded windows to 21H1, or removed HV components?

**Comment by Amondale** [comment]
Problem disappears after re-enabling all Hyper-V components and *disabling* the Windows Hypervisor OC. Any ideas why this should be so? I don't wish to run with both (HV *and* WSL2), so I don't yet feel I am at a "problem solved" point quite yet. Anybody have thoughts?

**Comment by Amondale** [comment]
Not logical to me that WSL2 would be dependent on any H-V components, although with Docker in the mix, and the "less than transparent" synergy between Docker, H-V, and WSL2, there may be a "thing" there and I may have just hit it... The machine in question has 16 GB RAM so possibly I can have all three VT services running -- Docker Engine started makes available RAM go down by 2 GB with no containers running.

**Comment by RAMADAN1900** [comment]
https://github.com/microsoft/WSL/issues/11634#issue-2325507649
