### ISSUE TITLE
Can't connect to MySQL server on WSL2, until I restart WSL

### ISSUE THREAD

**Issue by HugoKampsSB** [microsoft/WSL#7202]
### Windows Build Number

10.0.19043.1110

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

MySQL Server 8.0.25-0ubuntu0.20.04.1
Windows Terminal version 1.8.1521.0

### Repro Steps

- Start a WSL2 terminal (I use Windows Terminal)
- Run `sudo service mysql start`
- Try to connect to local database (I use TablePlus) with details below (I've removed the root user password)
![image](https://user-images.githubusercontent.com/37140671/126271269-faeac84a-7c43-4fad-8ac8-b01a64e1d07d.png)

### Expected Behavior

The client should be able to succesfully connect to the database. 

### Actual Behavior

I get the following message:  `Can't connect to MySQL server on '127.0.0.1' (10061)`

The weird part is that I can get it to work by restarting WSL:
- start cmd.exe and enter `wsl --shutdown`
- open a new WSL terminal and enter `sudo service mysql start` again
- now try to connect to the database, and it works!

**Comment by Schahin-R** [comment]
Same Problem here.

**Comment by craigloewen-msft** [comment]
Could you please collect logs for when you're in this state? Instructions are in the comment below. 

And if possible, are you able to upgrade to the Windows Insiders program and try this on the latest build? We have improvements to the localhost relay in those latest builds and I am trying to determine if that would help unblock your scenario. 

/logs

**Comment by Schahin-R** [comment]
I switchted from the mysql server on the host to a mariadb container, which is booted by docker unless stopped. 
So i did not have to solve this issue.  For me its a more cleaner way on the host.  Networking works also.

**Comment by HugoKampsSB** [comment]
After upgrading to the Windows Insiders program the problem has been resolved, so I take it that this issue has been fixed in a later Windows / WSL version!

**Comment by amcquade** [comment]
having this same issue with wamo except with "localhost/phpmyadmin". "127.0.0.1/phpmyadmin" loads up but im not able to log in. need to shutdown wsl to allow the first URL to work..
