### ISSUE TITLE
Passwd  command does not work 

### ISSUE THREAD

**Issue by techiechap** [microsoft/WSL#7210]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu-20.04

### Other Software

docker-desktop         
docker-desktop-data   
Vscode-WSL-Remote       

### Repro Steps

Open cmd.exe
Type wsl -u root
Type passwd username (usr01)and change the password
Type exit
Type wsl
Type sudo echo hi to confirm the new password works.

Open Windows terminal 
Type passwd usr01
Current Passwd:   Key in the password that you just changed eariler
`Current password:
passwd: Authentication token manipulation error
passwd: password unchanged`

### Expected Behavior

should be able to accept new password

### Actual Behavior

`Current password:
passwd: Authentication token manipulation error
passwd: password unchanged`

### Diagnostic Logs

`[    0.779864] scsi 0:0:0:0: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    0.780435] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    0.789320] sd 0:0:0:0: [sda] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    0.789322] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    0.790604] sd 0:0:0:0: [sda] Write Protect is off
[    0.790607] sd 0:0:0:0: [sda] Mode Sense: 0f 00 00 00
[    0.793951] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.131192] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    1.214396] sd 0:0:0:0: [sda] Attached SCSI disk
[    1.484100] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    1.809558] Adding 4194304k swap on /swap/file.  Priority:-2 extents:2 across:4202496k
[    2.794359] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    2.794944] sd 0:0:0:1: Attached scsi generic sg1 type 0
[    2.796292] sd 0:0:0:1: [sdb] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    2.796293] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[    2.796371] sd 0:0:0:1: [sdb] Write Protect is off
[    2.796372] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 00 00
[    2.796619] sd 0:0:0:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    2.799358] sd 0:0:0:1: [sdb] Attached SCSI disk
[    2.817552] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[   49.353466] hv_balloon: Max. dynamic memory size: 12958 MB
[  121.789150] WSL2: Performing memory compaction.
[  242.814287] WSL2: Performing memory compaction.
[  483.833567] WSL2: Performing memory compaction.`

**Comment by craigloewen-msft** [comment]
What's the output of your `wsl -l -v`? 
I'm not able to repro this issue, I think it might be because you're loading straight into the docker desktop distro.
