### ISSUE TITLE
Setting Folder Case Sensitivity/Insensitivity

### ISSUE THREAD

**Issue by wdeshazer** [microsoft/WSL#7211]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.71]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

20.04

### Repro Steps

touch DUMMY_FILE
cp DUMMY_FILE dummy_file

mkdir dum
getfattr -n system.wsl_case_sensitive dum
setfattr -n system.wsl_case_sensitive -v 1 dum

### Expected Behavior

Expect DUMMY_FILE and dummy_file to be different based on case.

### Actual Behavior

cp: 'DUMMY_FILE' and 'dummy_file' are the same file

dum: system.wsl_case_sensitive: Operation not supported

setfattr: dum: Operation not supported

### Diagnostic Logs

I researched extensively the per-directory-case-sensitivity articles:
https://devblogs.microsoft.com/commandline/improved-per-directory-case-sensitivity-support-in-wsl/
and
https://www.tenforums.com/tutorials/111293-enable-disable-case-sensitive-attribute-folders-windows-10-a.html

and none of the documentation seemed to provide me with insight. Case insensitivity affects my Linux workflow tremendously.

**Comment by benhillis** [comment]
@wdeshazer - how are you mounting your windows drives?  Are you setting the case=dir mount option?
You can do this by adding this line to /etc/wsl.conf (and restarting wsl via wsl --shutdown).
```
[automount]
options=case=dir
```

You can check what your mount options are by sharing the output of the `mount` command.

**Comment by benhillis** [comment]
Looks like the getfattr / setfattr commands will only work for WSL1.  That blog post was written before wsl2 existed.  You should be able to use fsutil.exe to accomplish this:

```
fsutil.exe file setCaseSensitiveInfo dum enable
fsutil.exe file setCaseSensitiveInfo dum disable
```

**Comment by wdeshazer** [comment]
Thanks. I didn’t have a default /etc/wsl.conf so I created one “sudo vi /etc/wsl.conf” and put the text that you suggested. I then ran wsl --shutdown in PowerShell. It did not seem to have an impact on the case sensitivity.

 

Here is the output from “mount”

 

/dev/sdc on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)

none on /mnt/wslg type tmpfs (rw,relatime)

none on /mnt/wsl type tmpfs (rw,relatime)

tools on /init type 9p (ro,relatime,dirsync,aname=tools;fmask=022,loose,access=client,msize=65536,trans=fd,rfd=7,wfd=7)

none on /dev type devtmpfs (rw,nosuid,relatime,size=8166836k,nr_inodes=2041709,mode=755)

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)

proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)

devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620,ptmxmode=000)

none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)

none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)

none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)

none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)

binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)

tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)

cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)

cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)

cgroup on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)

cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)

cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)

cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)

cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)

cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)

cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)

cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)

cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio)

cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)

cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)

cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)

none on /mnt/wslg/versions.txt type overlay (rw,relatime,lowerdir=/system/lower,upperdir=/system/rw/upper,workdir=/system/rw/work)

none on /mnt/wslg/doc type overlay (rw,relatime,lowerdir=/system/lower,upperdir=/system/rw/upper,workdir=/system/rw/work)

drivers on /usr/lib/wsl/drivers type 9p (ro,nosuid,nodev,noatime,dirsync,aname=drivers;fmask=222;dmask=222,mmap,access=client,msize=65536,trans=fd,rfd=4,wfd=4)

lib on /usr/lib/wsl/lib type 9p (ro,nosuid,nodev,noatime,dirsync,aname=lib;fmask=222;dmask=222,mmap,access=client,msize=65536,trans=fd,rfd=4,wfd=4)

drvfs on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;case=dir;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)

drvfs on /mnt/d type 9p (rw,noatime,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;case=dir;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)

**Comment by benhillis** [comment]
I see case=dir in our mount output.  Did you also try to use fsutil to set the per-thread case sensitivity?

**Comment by wdeshazer** [comment]
Thanks for your responses Ben.

 

So, first. I added the option:

[automount]
options=case=dir

 

to /etc/wsl.conf, which I had to create because it didn’t exist initially.

 

I then went to the directory where dum is located on /mnt/d/, which is a mount that I created and may not be configured properly, because I don’t know what I am doing.

 

I tried:

fsutil.exe file setCaseSensitiveInfo dum enable

 

and get the result:

Error:  The directory is not empty.

 

It does contain the file: DUMMY_FILE.

 

I am not sure what to check next.

**Comment by benhillis** [comment]
As the error implies, you can only change the sensitivity of empty directories.

**Comment by wdeshazer** [comment]
Surprisingly, that never occurred to me. LOL 

 

I have a directory full of files with file names with mixed case. Is there a way to change the state of directory with content or do I have to create a directory, enable it and then move the files over?

**Comment by benhillis** [comment]
No worries, the error could be more explicit for sure.  Yes generally what I will do is create the directory I want case-sensitive, mark as case sensitive, then git clone or untar into that location.  If you already have the files somewhere case-insensitive (and there were conflicts) you probably ended up overwriting some files, if that makes sense.

**Comment by wdeshazer** [comment]
Yes it does. Thank you! I’m good to go. I now have the ability to rename files with the same name but different cases. I think we can close this thread.

**Comment by benhillis** [comment]
Great, no problem.  I think you identified a gap in our documentation.  I'll follow up and make sure things are more clear.
