### ISSUE TITLE
^Z [1]+ Stopped 

### ISSUE THREAD

**Issue by tohzen** [microsoft/WSL#7213]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.71

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu 20.04 LTS

### Other Software

Ubuntu and or windows terminal.

### Repro Steps

Open powershell as admin, follow microsoft documents to install wsl2 ubuntu.    (wsl --install -d Ubuntu)

### Expected Behavior

install and run, without error

### Actual Behavior

installs, and misses keystrokes, randomly keeps us
![image](https://user-images.githubusercontent.com/70733544/126571218-299962b8-9ea3-47a0-af72-99ca29facb43.png)
ing ^Z on its own. Stopping updates, development etc.

**Comment by tohzen** [comment]
has anyone had any luck with this yet? i am still trying to figure it out!
![Screenshot 2021-07-24 174722](https://user-images.githubusercontent.com/70733544/126876972-29897079-6493-43f7-8a87-a2113e533372.png)

**Comment by craigloewen-msft** [comment]
This is strange, but doesn't seem to be anything we can repro on our end. Is your keyboard doing this for other applications or just for WSL? If you open up CMD or PowerSHell do you see the same behaviour? Do you see this using Windows Terminal as well and not just console host?

**Comment by craigloewen-msft** [comment]
Could you also try disabling WSLg by creating a file called `.wslconfig` in your Windows home directory (So for me that's `C:\Users\craig\`) and add the content:

```
[wsl2]
guiApplications=false
```

And then see if this issue still exists?
