### ISSUE TITLE
WSL2 VM crashes and starts using all available host memory

### ISSUE THREAD

**Issue by radu-matei** [microsoft/WSL#7215]
### Windows Build Number

10.0.19043.1147

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.128

### Distro Version

Ubuntu 20.04

### Repro Steps

Unfortunately, I don't have much information here, as the crash happened randomly - the distro became unresponsive, and the Vmmem process started using all available memory on the host:

![image](https://user-images.githubusercontent.com/13103165/126604840-5c637c09-b5ae-4340-8f5b-2b6855ffb4e9.png)

I had to manually terminate the process, as `wsl --shutdown` didn't work.

Hopefully this was a one-off crash, but wanted to start documenting it.
In case it happens again, I'll try to provide some more logs and environment info.

### Expected Behavior

-

### Actual Behavior

-

**Comment by Lechenx** [comment]
https://github.com/microsoft/WSL/issues/4166
This issue has been introduced for two years since the first version of wsl2 and haven't get repaired.
One workaround is set a limit to memory usage in wslconfig which you can find it on link above.

**Comment by WSLUser** [comment]
This is a valid issue. Despite setting a limit, it's possible for the WSL2 VM to ignore that limit and make the entire OS nearly impossible to do anything with. Rebooting is the only solution there.

**Comment by craigloewen-msft** [comment]
I'll keep this open so I can keep an eye on this, it's not a bug we've seen. If you do see this again let us know if there are any repro steps!

**Comment by bravik** [comment]
I would add that it uses not only memory, but CPU to.. In my case it happens several times per day, constantly using 25% of CPU and eating up all available RAM until system becomes unresponsive...
Even when I terminate Docker, PhpStorm and other tools I use with WSL it keeps eating CPU and RAM, untill I restart `LxssManager service`
