### ISSUE TITLE
[Documentation] WSL1 to WSL2 guide

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/WSL#7217]
Hey folks,

This is a request for a bit more documentation; ideally linked in from the main README.md, or another
page (the github wiki in general confuses me, but I am fine using links and exploring stuff).

I am still using WSL1. I don't recall when I started; 2018 or so? Anyway - I suppose in the long run
everyone will be on WSL2 eventually. Inertia and laziness means that I am a bit slow to move ... but
I want to prepare eventually, so any documentation in this regard may be helpful. Not so much the
command to do so (that's a simple one liner), but specifically the DIFFERENCES explained, including
potential trade-offs from a move.

To explain this a bit: I realized eventually that I can just put files and directories into the rootfs/ directory
that handles the state of that particular distribution (such as ubuntu on WSL1). So I can compile
on linux and then just re-use these binaries anyway, as-is. But this is for WSL1. On WSL2 I don't
quite know whether this can work or not. And whether the paths have changed and such stuff.

So any documentation in general for people who want to move away from WSL1 to WSL2 would be
very appreciated. Please don't invest too much time into this issue - it's mostly a nudge towards more
documentation in this regard, linked to from somewhere within the github repository (a simple link
may suffice, but also a .md file or something like that would be fine. Some document that can
help us old-time WSL1 users to make the transition lateron simpler.)

**Comment by Biswa96** [comment]
This article already explains your query https://docs.microsoft.com/en-us/windows/wsl/install-win10
