### ISSUE TITLE
Can i send command from Linux to Windows? 

### ISSUE THREAD

**Issue by OguzKahramn** [microsoft/WSL#7220]
Hi. I am working high accuracy of timers in Windows. But timers in Windows are not accurate. Therefore, I have installed Windows Subsystem for Linux (WSL) which is maybe not a solution for my application. I have seen many resources and videos regarding file sharing between them. My question is that is it possible to use Linux high accuracy timers in WSL. Another words, I would like to send command from Linux to Windows to execute task more precisely. It is a new concept, I hope there is already this kind of feature. Thanks for your comment.

**Comment by Biswa96** [comment]
There is some ambiguity in the "send command" words. Would you like to provide an simple example? Here is a documentation to use WSL and Windows side tools and vice versa https://docs.microsoft.com/en-us/windows/wsl/interop.

**Comment by benhillis** [comment]
This is more appropriate for the discussions section.
