### ISSUE TITLE
Windows Update error 0x80070643 during Kernel Update 5.16.10 + Msi says "Enter CD-ROM"

### ISSUE THREAD

**Issue by averyfreeman** [microsoft/WSL#7222]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

Method 1:
run "Check for updates" in Windows Update (UWP settings app)

Method 2: 
Download WSL 5.16.10 update from Windows Update Catalog website

Method 3:  
Extracted wsl_update_x64.msi from .cab file

### Expected Behavior

Method 1:
Windows updates to download and install'

Method 2:
Cab file to install

Method 3:  
Msi installer to run and install files

### Actual Behavior

Method 1:
Received download error 0x80070643 in Windows Update:
![image](https://user-images.githubusercontent.com/1308847/126859867-9e38e0d1-ab30-4baa-b205-957c1e40886c.png)

Method 2: 
Attempting to install from .cab file produced smartscreen error, "Ran Anyway" - failed before installer started

Method 3: 
Msi installer complained about missing CD-ROM.  Opening wsl_update_x64.msi through installer did not satisfy requirements.  I could not find a way to mount .cab file.

Unarchiving the .msi file, I saw a license file and a kernel file.

I also tried Windows Update troubleshooter (built-in) and one [downloaded from this link:](https://download.microsoft.com/download/7/E/9/7E9188C0-2511-4B01-8B4E-0A641EC2F600/MicrosoftProgram_Install_and_Uninstall.meta.diagcab)

I saw an issue about this same problem from 2020 that was closed.  Was pretty depressing.  I backed up my vhd, unregistered, and removed WSL features.  Tired of troubleshooting more than getting work done.

I just wanted you to have the issue so you know it's back.

**Comment by Ruomengsiming** [comment]
I also encountered the same problem, now would you solve it?

**Comment by itsakt** [comment]
Same issue. Windows 11 update can't install update for wsl and running wsl --update also fails.
![image](https://user-images.githubusercontent.com/8027805/136693848-85f1d72b-845e-456d-9f6f-f822ee945696.png)

**Comment by DiplNext** [comment]
when I try to install from cab file  it give me this error 
![image](https://user-images.githubusercontent.com/42368950/181699415-e3115fd9-31d4-4889-822f-392c74525332.png)
