### ISSUE TITLE
WSL Name resolution failure when connected to company VPN

### ISSUE THREAD

**Issue by nidiculageorge** [microsoft/WSL#7224]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.19.128-microsoft-standard

### Distro Version

20.04

### Repro Steps

My Windows 10 machine has environmental variable set with our company proxy setting.

But when i disconnect my company vpn name resolution is happening fine and able to connect to internet. 

### Expected Behavior

My WSL machine needs to connect to internet while connected to company VPN. Checked the company firewall and there is no blocking

### Actual Behavior

When i ping google its failing with

root@NIDICULA1:/# ping www.google.com
ping: www.google.com: Temporary failure in name resolution

### Diagnostic Logs

root@NIDICULA1:/# ping www.google.com
ping: www.google.com: Temporary failure in name resolution

Issue happening when my company VPN is connected. We have checked the company firewall but there is no blocking happening from my machine .

**Comment by craigloewen-msft** [comment]
What VPN are you using? Are you able to collect logs for this issue? Instructions below! /logs

**Comment by jaclag** [comment]
Hi, same thing on our side even on the company's internal network.
Due to the fact that the IP range of DHCP for the vm is conflicting with our internal network IP range. So with the company routing rules, the packets sent cannot get back to the vm. 
We had the same issue with docker containers on 172.16 or 172.17 subnets, easy to fix on docker : simply create a docker network on a subnet not conflicting. Same for virtualbox.
But unfortunately this is not possible in WSL, quite confusing ... A lot of people are complaining about this, you can look for issues like static IPs feature requests and so on. A lot of blogs propose workarounds, create dummy interfaces so that WSL choose other subnets etc.
It would be so simple just to add a configuration line in the wsl config file to specify the NAT subnet ... But it seems MS doesn't want to do it like this ...
So on our side, we tried to use WSL, we think it's a great solution, but totally useless for us because of the network configuration conflicting with our real subnets. So we keep using virtualbox, it's a pitty ...

**Comment by nidiculageorge** [comment]
@craigloewen-msft we are using CISCO VPN ANY CONNECT.

I have also set environment variables in my windows machine which proxy is mentioned

![image](https://user-images.githubusercontent.com/43850474/128600020-2d58bf78-0d18-4b2d-8e68-5c67120580a5.png)

My doubt is there any thing that we have to mention or configure in WSL machine to allow internet access .We have checked the firewall logs in the office and there was no blocking from my Host machine or this WSL machine IP

**Comment by karasjoh000** [comment]
#6039

**Comment by karasjoh000** [comment]
see if switching to wsl version 1 will work as a temporary fix. Mentioned here: #6039

**Comment by craigloewen-msft** [comment]
@nidiculageorge could you please try updating to the latest Cisco AnyConnect version? Are you able to use the Store version? They mentioned in I believe version 4.10 or higher that they added in WSL 2 specific fixes.

Does upgrading fix you?

**Comment by nidiculageorge** [comment]
![image](https://user-images.githubusercontent.com/43850474/135126514-fc4c4810-dd64-46a3-b6f1-445e89ae2df4.png)


This is the current version used in our company.The Network team need to update the version.

**Comment by karasjoh000** [comment]
Issue is tracked here: https://github.com/microsoft/WSL/issues/4277 
Follow this workaround

**Comment by b-diggity** [comment]
It could be that local network routing isn't allowed on VPN. We had that issue when using Pulse Secure. For WSL2 to function on VPN, local network access had to be allowed.

**Comment by Niradnik** [comment]
Same issue with Pulse Secure VPN, so it is impossible to work. 
@haxorof the  "split tunneling for Pulse Secure" is on server side right ?

**Comment by haxorof** [comment]
> Same issue with Pulse Secure VPN, so it is impossible to work. 
> @haxorof the  "split tunneling for Pulse Secure" is on server side right ?  

Yes, so the company may manage that centrally. It is a configuration on the server-side which is set on the client when it get assigned a role. 

For reference:
https://docs.pulsesecure.net/WebHelp/PDC/9.0R1/Content/PDC_AdminGuide_9.0R1/Pulse_Connect_Secure_Split.htm

**Comment by b-diggity** [comment]
> > Same issue with Pulse Secure VPN, so it is impossible to work. 
> > @haxorof the  "split tunneling for Pulse Secure" is on server side right ?  
> 
> Yes, so the company may manage that centrally. It is a configuration on the server-side which is set on the client when it get assigned a role. 
> 
> For reference:
> https://docs.pulsesecure.net/WebHelp/PDC/9.0R1/Content/PDC_AdminGuide_9.0R1/Pulse_Connect_Secure_Split.htm

Here is an updated [page](https://help.ivanti.com/ps/help/en_US/PDC/9.1R13/cg_ics_pdc/split-tunneling-overview.htm#:~:text=Pulse%20Clientusers%20may%20choose%20to%20suspend%20the%20Pulse,determine%20which%20IP%20resources%20the%20user%20can%20access).  Scroll down to the heading 'Pulse Client Split Tunneling Summary' and look at the second graphic to allow local network access.

**Comment by haxorof** [comment]
> > > Same issue with Pulse Secure VPN, so it is impossible to work. 
> > > @haxorof the  "split tunneling for Pulse Secure" is on server side right ?  
> > 
> > Yes, so the company may manage that centrally. It is a configuration on the server-side which is set on the client when it get assigned a role. 
> > 
> > For reference:
> > https://docs.pulsesecure.net/WebHelp/PDC/9.0R1/Content/PDC_AdminGuide_9.0R1/Pulse_Connect_Secure_Split.htm
> 
> Here is an updated [page](https://help.ivanti.com/ps/help/en_US/PDC/9.1R13/cg_ics_pdc/split-tunneling-overview.htm#:~:text=Pulse%20Clientusers%20may%20choose%20to%20suspend%20the%20Pulse,determine%20which%20IP%20resources%20the%20user%20can%20access).  Scroll down to the heading 'Pulse Client Split Tunneling Summary' and look at the second graphic to allow local network access. 

Local access might not be an option depending on how restrictive the company is, since it is less secure than the "full tunnel".

**Comment by b-diggity** [comment]
> > > > Same issue with Pulse Secure VPN, so it is impossible to work. 
> > > > @haxorof the  "split tunneling for Pulse Secure" is on server side right ?  
> > > 
> > > Yes, so the company may manage that centrally. It is a configuration on the server-side which is set on the client when it get assigned a role. 
> > > 
> > > For reference:
> > > https://docs.pulsesecure.net/WebHelp/PDC/9.0R1/Content/PDC_AdminGuide_9.0R1/Pulse_Connect_Secure_Split.htm
> > 
> > Here is an updated [page](https://help.ivanti.com/ps/help/en_US/PDC/9.1R13/cg_ics_pdc/split-tunneling-overview.htm#:~:text=Pulse%20Clientusers%20may%20choose%20to%20suspend%20the%20Pulse,determine%20which%20IP%20resources%20the%20user%20can%20access).  Scroll down to the heading 'Pulse Client Split Tunneling Summary' and look at the second graphic to allow local network access. 
> 
> Local access might not be an option depending on how restrictive the company is, since it is less secure than the "full tunnel". 

Without doing this, Pulse is sending all WSL traffic into the tunnel since WSL has its own local network on the computer. You could apply this to a group of people in the org to limit scope.

**Comment by haxorof** [comment]
> > > > > Same issue with Pulse Secure VPN, so it is impossible to work.
> > > > > @haxorof the  "split tunneling for Pulse Secure" is on server side right ?
> > > > 
> > > > 
> > > > Yes, so the company may manage that centrally. It is a configuration on the server-side which is set on the client when it get assigned a role.
> > > > For reference:
> > > > https://docs.pulsesecure.net/WebHelp/PDC/9.0R1/Content/PDC_AdminGuide_9.0R1/Pulse_Connect_Secure_Split.htm
> > > 
> > > 
> > > Here is an updated [page](https://help.ivanti.com/ps/help/en_US/PDC/9.1R13/cg_ics_pdc/split-tunneling-overview.htm#:~:text=Pulse%20Clientusers%20may%20choose%20to%20suspend%20the%20Pulse,determine%20which%20IP%20resources%20the%20user%20can%20access).  Scroll down to the heading 'Pulse Client Split Tunneling Summary' and look at the second graphic to allow local network access.
> > 
> > 
> > Local access might not be an option depending on how restrictive the company is, since it is less secure than the "full tunnel".
> 
> Without doing this, Pulse is sending all WSL traffic into the tunnel since WSL has its own local network on the computer. You could apply this to a group of people in the org to limit scope.

That is all true, in the end it is up to what the organization allow. 😄
