### ISSUE TITLE
WSL2 keeps nagging me to install matlab every time I install other tools.

### ISSUE THREAD

**Issue by BillRenCN** [microsoft/WSL#7228]
### Windows Build Number

10.0.19042.1052

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

install any tools in the wsl2 system

### Expected Behavior

install the valgrind successfully

### Actual Behavior

proped out the window to nag me installing matlab
![png](https://user-images.githubusercontent.com/76474805/126894621-d7a4e274-65bc-4870-9917-7c9cb745943b.png)

**Comment by BillRenCN** [comment]
Is there a way the installed matlab? Or if I want to install anything I will need to install matlab? That totally make no sense to me.

**Comment by Diablo-D3** [comment]
This isn't part of WSL, this is part of your Debian or Ubuntu distribution. `dpkg -l *matlab*` to figure out which package this is (seems to be possibly matlab-support), and remove it.

**Comment by BillRenCN** [comment]
![uTools_1627261324663](https://user-images.githubusercontent.com/76474805/126919933-c08f40b6-b836-45f9-a81f-7b42e1fdfb15.png)
Will it told me that I haven't installed matlab yet.
So I tried to install the matlab-support and recieved the same error message which nags me to figure out where I had installed the matlab! But I was just trying to installed matlab-support....... This totally does't make sense!

**Comment by BillRenCN** [comment]
So should I ask the question in the ubuntu community? I'm afraid it's not appropriate to ask this qustion here?

**Comment by NaiveTomcat** [comment]
> ![uTools_1627261324663](https://user-images.githubusercontent.com/76474805/126919933-c08f40b6-b836-45f9-a81f-7b42e1fdfb15.png)
> Will it told me that I haven't installed matlab yet.
> So I tried to install the matlab-support and recieved the same error message which nags me to figure out where I had installed the matlab! But I was just trying to installed matlab-support....... This totally does't make sense!

Maybe you should use bash to execute the command. `zsh` messes with `*`.

**Comment by Diablo-D3** [comment]
> So should I ask the question in the ubuntu community? I'm afraid it's not appropriate to ask this qustion here?

Yes.

**Comment by craigloewen-msft** [comment]
@BillRenCN agreed this seems to be something specific to your installation and isn't an actionable item for us here on the WSL team. As others have identified in the thread asking this to the Ubuntu community seems appropriate. I'll close this issue out as it's not a WSL specific issue!
