### ISSUE TITLE
WSL2 can't list kernel modules by the lsmod command

### ISSUE THREAD

**Issue by e3243eric** [microsoft/WSL#7231]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1149]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

I try to build the hello world kernel module, but I can't find any kernel modules by `sudo lsmod` command and the /proc/modules folder.

### Expected Behavior

`$sudo lsmod` should list the status of kernel modules.

### Actual Behavior

There is nothing list by the lsmod command.
```
$ sudo lsmod
Module                  Size  Used by
```

**Comment by craigloewen-msft** [comment]
This is expected behaviour, the WSL 2 kernel is monolithic and doesn't have kernel modules installed. You can view the kernel source code here: https://github.com/microsoft/WSL2-Linux-Kernel
