### ISSUE TITLE
Windows 11 sudo upgrade -y failing

### ISSUE THREAD

**Issue by allanpfreitas** [microsoft/WSL#7237]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.100]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.43

### Distro Version

Ubuntu 20.04

### Repro Steps

- Fresh install of Windows 11
- installed wsl using this command wsl --install -d Ubuntu
- Sudo apt update ran successful
- Sudo apt upgrade -y  

### Expected Behavior

Should be possible to upgrade WSL2

### Actual Behavior

![image](https://user-images.githubusercontent.com/2490836/127070331-4698ba4e-5fc5-4aee-ad92-66d0eca7ea9f.png)

**Comment by gbiagini** [comment]
Can confirm the same issue on a fresh Windows 10 install on an x86_64 machine and a non-fresh Windows 10 on an ARM64 machine.
Both are Ubuntu 20.04, WSL2.

**Comment by gabrieldonadel** [comment]
I'm facing the same problem on an x86_64 machine running Windows 10  Ubuntu 20.04 WSL2.

**Comment by zzjin** [comment]
I'm facing the same problem on Windows 11 22000.100 Ubuntu 20.04.2 5.10.43.3-microsoft-standard-WSL2

**Comment by allanpfreitas** [comment]
@benhillis can you help us ?

**Comment by gabrieldonadel** [comment]
Seems to be a bug in the package itself https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1938097

**Comment by allanpfreitas** [comment]
Guys seems that I fixed that running these commands:
sudo apt remove --purge cloud-init
sudo apt install cloud-init
run sudo apt upgrade without problems 
![image](https://user-images.githubusercontent.com/2490836/127164415-5cc708f2-1a99-4503-be3c-6d10f07bb217.png)

**Comment by gbiagini** [comment]
> Guys seems that I fixed that running these commands:
> sudo apt remove --purge cloud-init
> sudo apt install cloud-init
> run sudo apt upgrade without problems
> ![image](https://user-images.githubusercontent.com/2490836/127164415-5cc708f2-1a99-4503-be3c-6d10f07bb217.png)

Appreciate the fix! This worked for me as well.

**Comment by benhillis** [comment]
Issue is in cloud-init package.
