### ISSUE TITLE
Is there a way to use docker.io package in Ubuntu?

### ISSUE THREAD

**Issue by tasty0tomato** [microsoft/WSL#7246]
### Discussed in https://github.com/microsoft/WSL/discussions/7245

<div type='discussions-op-text'>

<sup>Originally posted by **tasty0tomato** July 29, 2021</sup>
Ubuntu provides a community package docker.io and in ordinary Ubuntu server, I can use it easily by
```
sudo systemctl start docker
# or
sudo service docker start
```
But this does not work in Ubuntu WSL2 version. Because it seems that services can only be started only if they are under /etc/init.d/ ( which docker in Ubuntu WSL2 does not ).

**BTW:**
1. I know Docker Desktop is recommended.
2. I know Docker's official docker-ce package is recommended.
3. Debain WSL2 version can start docker.io because docker service is under /etc/init.d/ (https://github.com/microsoft/WSL/discussions/4872)

And I just want to know if it is possible to start docker.io service in Ubuntu WSL. And if there is a way to use it.</div>

**Comment by davidgarciaMontreal** [comment]
The Windows Docker desktop relies on WSL to manager the docker daemon.
Why would you want to manage the docker service/daemon if it's already being managed by the desktop application?

**Comment by tasty0tomato** [comment]
> 
> 
> Why would you want to manage the docker service/daemon if it's already being managed by the desktop application?

There was no Windows Docker desktop when I tried it.

**Comment by davidgarciaMontreal** [comment]
ah ok. Please have a look at this article: https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2.
It might help you :)

**Comment by tasty0tomato** [comment]
> 
> **BTW:**
> 
>     1. I know Docker Desktop is recommended.

Well, I used Docker Desktop with WSL2 in the past, and I will still use it in the future.

In this issue, maybe my question is not very perfect. My first question is that if it is possible to use docker.io package in WSL2, and maybe the second is more important which is if one service is not under '/etc/init.d/', is it possible to enable this service?
