### ISSUE TITLE
Unable to start Electron App no matter in WSL 1 or 2 with X Server

### ISSUE THREAD

**Issue by JeffersonQin** [microsoft/WSL#7249]
### Windows Build Number

Microsoft Windows [Version10.0.19042.1110]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 18.04/20.04

### Other Software

VcXsrv: 1.20.9.0

### Repro Steps

I have configured everything for X Server, and apps like `xcalc` can show up. However, I cannot start any `Electron` app.

Steps followed: https://www.beekeeperstudio.io/blog/building-electron-windows-ubuntu-wsl2

Besides, I tested on this repository: https://github.com/Molunerfinn/PicGo

Every time when I run `yarn run electron:serve` it just ended like the following image:

![image](https://user-images.githubusercontent.com/30655701/127514123-eb436db9-5ee2-4533-8617-afd6143ea17b.png)

### Expected Behavior

There should be an app start up.

### Actual Behavior

Nothing happens.

**Comment by benhillis** [comment]
Running GUI apps is not officially supported unless you are using WSLg (which requires Win11).
