### ISSUE TITLE
Linux GUI was not working in wsl2

### ISSUE THREAD

**Issue by AbdulMohamedM** [microsoft/WSL#7250]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

Gedit
and all the Linux GUI Apps 

### Repro Steps

I install the gedit in Ubuntu 20.04 on WSL2 and uptodate all packages and drivers.
install the gedit using "sudo apt install gedit" successfully installed open the gedit using "gedit" not opening.

### Expected Behavior

open the Linux GUI apps

### Actual Behavior

Unable to init server: Could not connect: Connection refused

(gedit:336): Gtk-WARNING **: 18:06:59.829: cannot open display: localhost:0.0

**Comment by krshrimali** [comment]
From what I know, WSLg updates aren't on the Windows 10 insiders/general updates. You need to be on Windows 11 to be able to use WSLg.

**Comment by AbdulMohamedM** [comment]
I updated the Windows 10 Insider Preview build 21362+
problem fixed
https://github.com/microsoft/wslg

**Comment by rmaries** [comment]
I am not using windows insider preview. I update my windows today.
Below is my update. I tried gui apps in wsl - ubuntu. It is not showing any error and also not opening.


![image](https://user-images.githubusercontent.com/3794595/129372433-8e2cd39d-f22a-46eb-94ba-3be99bd99765.png)

**Comment by rfog** [comment]
Same here with Windows 11, 22000.194

**Comment by beedrill** [comment]
Updated Windows 11, installed Nvidia driver, after wsl --update and wsl --shutdown and also apt update, I still get the same error.
Unable to init server: Could not connect: Connection refused
(gedit:472): Gtk-WARNING **: 20:26:29.949: cannot open display:

I tried on two different machines, the same error, any suggestions?

**Comment by MichaelChampigny** [comment]
Same here. No luck getting WSLg working to enable GUI applications.

Using Windows 11 Pro, build 22000. WSL Ubuntu Community Preview freshly installed, which is Ubuntu 21.04 with kernel 5.10.60.1.

$ sudo apt install x11-apps -y
...looks good...
$ xcalc
Error: Can't open display: :0

The whole WSLg situation is very confusing. If you run "sudo ubuntuwsl visual", you can enable "legacy integration" of GUI and audio apps, but it requires an _external_ Xserver and PulseAudio server running on native Windows. I assume that is **NOT** what you want to do to make use of WSLg.

So this doesn't "just work" as you'd expect. I suspect the issue is there is no X server running on Linux itself. But before I go about installing xserver-xorg-core or a desktop, I'd like to have confirmation of someone out there getting this working. Maybe there is a simpler way to enable WSLg without having to install a full desktop on Linux.

**Comment by doublechiang** [comment]
Have you upgraded to Windows 11? I followed @LohiKarma97's instructions and https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps. And it works now.

**Comment by Aquariu** [comment]
It looks like you may have got Wayland-native apps to work but not X11 ones ? (just a hunch based on [this ](https://arstechnica.com/gadgets/2021/10/the-best-part-of-windows-11-is-a-revamped-windows-subsystem-for-linux/)article)

**Comment by MichaelChampigny** [comment]
That's possible. I subsequently got nautilus working, but pretty much everything else does not work. I always get the "Error: Can't open display :0" message. This would imply there is no Xserver. But isn't the point of WSLg to avoid installing an X server? At this point, I've pretty much given up on it, assuming that when the WSL2 Community Preview moves into production, everything will "just work".

**Comment by Aquariu** [comment]
Yes that's the point.  Personally I had to remove everything X-related (things I had tried to make GUIs work in WSL1 and failed),  reinstall everything, and then follow the procedure above.

**Comment by MichaelChampigny** [comment]
@Aquariu, did you do this with the WSL2 Community Preview, or were you using the production version of WSL2? I'm sure this all works on the production version, but that version is stuck on the old LTS version of Ubuntu. I went with the Community Preview to be able to use 21.04.

**Comment by moefear85** [comment]
Hi,

I'm on Win11 22000.318. I installed a fresh copy of ubuntu 20.04 and upgraded wsl2 and everything else, even ubuntu. typing "gedit", opens up gedit beautifully. But typing "sudo gedit", gives:
cannot open display: :0

Is there any way to get native gui working for sudo too?

**Comment by educobuci** [comment]
> 

I was having the same issue as you but I finally managed to fix it by running `wsl --update` from Power Shell running in admin mode.

**Comment by ksbrar** [comment]
+1 here, powershell procedure (in admin mode) also worked for me as I went through the tutorial. Thanks all!

**Comment by Chandler-Kluser** [comment]
> @MichaelChampigny I was having the same issue, I just did the following to resolve it:
> 
> a. Run PowerShell in Admin Mode. b. Execute wsl --update c. Execute wsl --shutdown d. Run gedit in Ubuntu
> 
> That resolved my issue :)

thanks a lot buddy! Solved my issue!!

**Comment by mdobns** [comment]
just type on powershell this command
wsl --update

**Comment by islamarab** [comment]
> > @MichaelChampigny I was having the same issue, I just did the following to resolve it:
> > a. Run PowerShell in Admin Mode. b. Execute wsl --update c. Execute wsl --shutdown d. Run gedit in Ubuntu
> > That resolved my issue :)
> 
> The `Run PowerShell in Admin Mode` is critical. Thank you.

Helped me this commands, thank you.

**Comment by AM-ash-OR-AM-I** [comment]
> I got the same problem on Windows 11 and, since I was using XServer on Windows 10, I just needed to remove (or comment) these lines out:
> 
> ```shell
> # export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
> # export LIBGL_ALWAYS_INDIRECT=1
> ```
> 
> Then, I've shutdown the wsl (`wsl.exe --shutdown`) and it did the trick.

This is it I also had added those lines. Once I removed it worked! Thanks.

**Comment by ZhuLinsen** [comment]
> I got the same problem on Windows 11 and, since I was using XServer on Windows 10, I just needed to remove (or comment) these lines out:
> 
> ```shell
> # export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
> # export LIBGL_ALWAYS_INDIRECT=1
> ```
> 
> Then, I've shutdown the wsl (`wsl.exe --shutdown`) and it did the trick.

It's worked for me. Thanks!!!!

**Comment by inobelar** [comment]
@saulotdr thanks!
