### ISSUE TITLE
WSL2 clock becomes unsynced on Desktop system

### ISSUE THREAD

**Issue by gitbls** [microsoft/WSL#7255]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Debian 10

### Repro Steps

I restarted my Desktop (a Dell box, nothing funky) 3 days ago after installing the latest WSL update. At that point, the date/time in my Debian WSL was spot on with the rest of the world.

Now, 3 days later, it's off by 7 or 8 seconds.

I tried `sudo hwclock -s` but no joy. It didn't reset the time in WSL.

### Expected Behavior

Clock stays in sync, or there's a reasonable workaround to keep it in sync.

### Actual Behavior

Time falls behind about 2 seconds per day.

### Diagnostic Logs

Filled out the info in Windows Feedback and added a screenshot of two dclocks: a blue clock running on my chrony server, and a  green dclock running in WSL2 Debian.  As you can see, the time in the WSL2 Debian system is 7 seconds behind reality.

**Comment by rob3c** [comment]
Are either of you running Windows in a VM and using your hypervisor to suspend it? I explained my solution to clock sync issues with using WSL2 in a Windows guest VM using Parallels on a Mac this comment:
https://github.com/microsoft/WSL/issues/5324#issuecomment-971128754

**Comment by anacierdem** [comment]
No, the wsl2 host is on bare metal for me.

**Comment by gitbls** [comment]
No, this is on a Windows desktop system bare metal that I never sleep or hibernate,

**Comment by shanz1999** [comment]
I updated the WSL kernel version using cabinet and msi files but the date and time was still drifting after pausing the VMWare VM which contains my Windows 10 and WSL.
Instead I have created my own solution as follows - 
in WSL
/home/myuser/.bashrc

add these lines at the end so WSL bash runs the powershell script, syncdates,ps1 everytime WSL bash is opened.

```
# fix wsl time sync
powershell.exe -File "c:\Users\myuser\syncdates.ps1"
```
The script syncdates.ps1 is

```
echo "Running syncdates.ps1..."
#syncdates.ps1 can be run on startup 
# save current Windows host's time and date into variable $TimeStr
$TimeStr = Get-Date -Format "MMddHHmmyy.ss"
# eg: wsl sudo date 1115204821.10
wsl sudo date $TimeStr
```

**Comment by trevor-scheer** [comment]
Is anyone working around this in a way that doesn't require manual intervention? I'm fairly new to wsl and this is a major inconvenience. And is this somehow not affecting everyone? I'd expect an issue like this to have a lot of traction.

**Comment by ben-page** [comment]
Yes, this is pretty big inconvenience. It needs to be fixed.

**Comment by yorickdowne** [comment]
I see this on a Win11 on baremetal that's been configured to stay in sync by making sure w32time starts and MaxPollInterval is set, as per https://eth-docker.net/docs/Support/Windows . `date` in Powershell matches https://time.is. However, `date` in WSL2 Ubuntu 20.04 with kernel `5.10.102.1-microsoft-standard-WSL2` is two seconds off. In my case, `sudo hwclock -s` does resolve this clock skew.

For anything Windows not-domain-joined, first, the host sync needs to be fixed, as it is Terribad(tm) out of the box. From there, there's still an issue of WSL2 getting out of sync without scheduled `hwclock -s` intervention: `schtasks /Create /TN WSL2TimeSync /TR "wsl -u root hwclock -s" /SC ONEVENT /EC System /MO "*[System[Provider[@Name='Microsoft-Windows-Kernel-Power'] and (EventID=107 or EventID=507) or Provider[@Name='Microsoft-Windows-Kernel-General'] and (EventID=1)]]" /F`

**Comment by mcollier** [comment]
@owenschupp When would be the most helpful time to gather the logs?  Would it be after the PC resumes from sleep and the WSL clock is out of sync with Windows?

**Comment by owenschupp** [comment]
@mcollier that would be a great time, thanks!

**Comment by dlchet** [comment]
i started a recording, let my surface book go to sleep, waited a few minutes, woke it up, confirmed the clock had lagged, and stopped recording. let me know if i should re-do this in a different way to be more helpful. also i'm on the beta preview build if that matters. thanks for any insight into how to get the wsl clock to stay synced!

https://aka.ms/AAgr1pp

**Comment by gitbls** [comment]
As I noted in OP, my scenario requires that it run for up to 24 hours before the clock skew becomes obvious. I'm not sure how to show that the clock is skewed without doing a video, but seems that would make a rather large recording.

How little skew would you find compelling as a demonstration that the clock is not in sync?

**Comment by wolf99** [comment]
I'm still seeing this issue also.

Also on Windows 10 (21H2) with WSL 2.

I remember back in the hazy halcyon days of #4245, #4975, #4677, #5324 where we still held out hope that this issue may actually be fixed. Whole internet eons have ground by since then... 😉

**Comment by s-boris** [comment]
> I'm still seeing this issue also.
> 
> Also on Windows 10 (21H2) with WSL 2.
> 
> I remember back in the hazy halcyon days of #4245, #4975, #4677, #5324, et al, where we still held out hope that this issue may actually be fixed. Whole internet eons have ground by since then... 😉

Yea the clock does not seem to ever get synced after startup. Especially putting your pc to sleep desyncs the time so much that I can't even interface with a lot of external API's which is super annoying. There are a lot more people still reporting and commenting on those issues like #5324

**Comment by craigloewen-msft** [comment]
/dupe #10006

We're migrating all clock skew issues to a megathread so we can keep the top comment up to date with any updates and work arounds. Thank you for filing this!
