### ISSUE TITLE
Security: wsl.conf "generate resolv.conf" and resolv.conf template allow to use untrusted DNS service

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/WSL#7259]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Any

### Repro Steps

1. Use the default WSL configuration
2. Try any Network test involving Name resolution

### Expected Behavior

resolve.conf generation must involve simple check that ensure that DNS offers basic security features. Otherwise, issue warning, at least. Internet infrastructure can easily block insecure DNS requests. Use http://www.dnssec-or-not.com/ at least!

### Actual Behavior

User can get any fake insecure DNS resolver when uses over-the-air connection or enter insecure DNS resolver. It doesn't work in a such way in any place today. Either whitelist is provided as in browsers or both whitelist is offered and "probe" of security quality is done as in Linux.

**Comment by OneBlue** [comment]
Hi @PavelSosin-320, thanks for reporting this.

The IP address WSL writes in resolv.conf is a proxy IP address that actually points to the host which will proxy DNS queries, so by default WSL is just using the host's DNS settings.
