### ISSUE TITLE
wsl opensuse can't run service <servicename> start

### ISSUE THREAD

**Issue by cecep31** [microsoft/WSL#7261]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

opensuse

### Other Software

postgrsql, nginx

### Repro Steps

i dont know

### Expected Behavior

#opensuse s

### Actual Behavior

pilput@server:/mnt/c/Users/cecep> nginx -version
nginx version: nginx/1.19.8
pilput@server:/mnt/c/Users/cecep> sudo service nginx status
[sudo] password for root:
service: no such service nginx
pilput@server:/mnt/c/Users/cecep>

### Diagnostic Logs

i trying on ubuntu-20.04 and work, ia tryngin run nginx and postgresql

**Comment by ShornyH** [comment]
vscode://vscode.github-authentication/did-authenticate?windowid=1&code=ebc599948423f2c3aedc&state=4db5448a-f23a-4788-8e37-efd3252fe1ec

**Comment by OneBlue** [comment]
Thanks for reporting this @cecep31.

WSL doesn't support running daemons that way at this time. If you want to run nginx, you can do so by running `nginx -g 'daemon off;'`.
