### ISSUE TITLE
WSL unable to mount win volumes after windows 11 preview update

### ISSUE THREAD

**Issue by AnasKhchaf** [microsoft/WSL#7263]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.100]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019

### Distro Version

Release:        18.04

### Repro Steps

Windows 11 update

### Expected Behavior

access to my windows filesystem

### Actual Behavior

Hello,
I am no able longer to access to my windows files from wsl. on each session start i am getting the following with "dmesg":
![image](https://user-images.githubusercontent.com/6990967/127853958-eda314be-505e-4075-ba36-ca1c4e1b1d85.png)
Have you please any workaround until the official fixe ?
Thank you !

**Comment by 0xbadfca11** [comment]
Linux kernel is too old.
Do ``wsl --update``.

**Comment by AnasKhchaf** [comment]
`developer@core:livyPayloads$ sudo apt-get install wsl
Reading package lists... Done
Building dependency tree
Reading state information... Done
wsl is already the newest version (0.2.1-1).
The following packages were automatically installed and are no longer required:
  gyp javascript-common libjs-async libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libuv1-dev node-abbrev node-ansi node-ansi-color-table node-archy
  node-async node-balanced-match node-block-stream node-brace-expansion node-builtin-modules node-combined-stream node-concat-map node-cookie-jar node-delayed-stream
  node-forever-agent node-form-data node-fs.realpath node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-hosted-git-info
  node-inflight node-inherits node-ini node-is-builtin-module node-isexe node-json-stringify-safe node-lockfile node-lru-cache node-mime node-minimatch node-mkdirp
  node-mute-stream node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once node-osenv node-path-is-absolute node-pseudomap node-qs node-read
  node-read-package-json node-request node-retry node-rimraf node-semver node-sha node-slide node-spdx-correct node-spdx-expression-parse node-spdx-license-ids node-tar
  node-tunnel-agent node-underscore node-validate-npm-package-license node-which node-wrappy node-yallist
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 242 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up plexmediaserver (1.21.0.3711-b509cc236) ...
PlexMediaServer install: PlexMediaServer-1.21.0.3711-b509cc236 - Installation starting.
PlexMediaServer install:
PlexMediaServer install: Now installing based on:
PlexMediaServer install:   Installation Type:   Update
PlexMediaServer install:   Process Control:     systemd
PlexMediaServer install:   Plex User:           plex
PlexMediaServer install:   Plex Group:          plex
PlexMediaServer install:   Video Group:         video
PlexMediaServer install:   Metadata Dir:        /var/lib/plexmediaserver/Library/Application Support
PlexMediaServer install:   Temp Directory:      /tmp
PlexMediaServer install:   Lang Encoding:       en_US.UTF-8
PlexMediaServer install:   Intel QSV Hardware:  Not found
PlexMediaServer install:
PlexMediaServer install:   OpenCL library:      Not Installed
PlexMediaServer install:   Beignet package:     Not Installed
PlexMediaServer install:
PlexMediaServer install: WARNING: Package 'Beignet', required for hardware transcoding of HDR content, is missing.
PlexMediaServer install:          Please install package:  'beignet-opencl-icd'
PlexMediaServer install: WARNING: The OpenCL library, required for hardware transcoding of HDR content, is missing.
PlexMediaServer install:          Please install package:  'ocl-icd-libopencl1'
PlexMediaServer install:
PlexMediaServer install: Completing final configuration.
dpkg: error processing package plexmediaserver (--configure):
 installed plexmediaserver package post-installation script subprocess returned error exit status 2
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 plexmediaserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
developer@core:livyPayloads$ sudo wsl --update
Unknown command: --update
WSL
Wsman Shell commandLine, version 0.2.1

USAGE: wsl COMMAND [PARAMS...]

COMMANDS:
identify  - WS-Identify
enum      - WS-Enumerate
get       - WS-Get
put       - WS-Put
invoke    - WS-Invoke
xclean    - Delete all files generated by this tool set
xcred     - Create or display credential file
xcert     - Get server certificate (saved to <IPADDRESS>.crt)

PARAMS specification is specific to a COMMAND.

Output will be saved to ./response.xml. If you want to run parallel
executions in the same directory, define RTFILEPREFIX in the environment.
Doing so may significantly increase files generated.

Requires: curl, xmllint, GNU core utilities.
Optional: xsltproc for output formatting, gpg for encrypted credential.
Optional: wget as alternate for curl when not available.
developer@core:livyPayloads$`

**Comment by AnasKhchaf** [comment]
![image](https://user-images.githubusercontent.com/6990967/127865979-39d4d02d-e1ff-4976-90df-c03630b0895e.png)
`
installation issue and unkown --update flag

**Comment by Prunoideae** [comment]
>
> installation issue and unkown --update flag

run the windows powershell as administrator, and type `wsl --shutdown` then `wsl --update` there

![image](https://user-images.githubusercontent.com/24620047/127903666-078968ba-4402-4832-a1ab-221957a065c5.png)

**Comment by AnasKhchaf** [comment]
> > installation issue and unkown --update flag
> 
> run the windows powershell as administrator, and type `wsl --shutdown` then `wsl --update` there
> 
> ![image](https://user-images.githubusercontent.com/24620047/127903666-078968ba-4402-4832-a1ab-221957a065c5.png)

Thank you, what a wonderful fix !
