### ISSUE TITLE
netdiscover tool doesn't work

### ISSUE THREAD

**Issue by JaK0B-Pro** [microsoft/WSL#7265]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1151]

### WSL Version

- [ ] WSL 2
- [x] WSL 1

### Kernel Version

4.4.0-19041

### Distro Version

-bash: lsb_release: command not found

### Repro Steps

`$ git clone https://github.com/netdiscover-scanner/netdiscover.git`
`$ cd netdiscover`
`$ ./update-oui-database.sh (optional, to update the MAC addresses list)`
`$ ./autogen.sh`
`$ ./configure`
`$ make`
`$ make install`
`$ make distclean`
`$ sudo netdiscover`
`pcap_open_live(): eth1: socket: Address family not supported by protocol`

### Expected Behavior

![2021-08-02 20_24_44-5  Scanning - Google Drive](https://user-images.githubusercontent.com/87572423/127907257-1c5655df-38b2-4ad4-9f61-fe85f33fb448.png)

### Actual Behavior

`pcap_open_live(): eth1: socket: Address family not supported by protoco`

**Comment by JaK0B-Pro** [comment]
what i saw: pcap_open_live(): eth1: socket: Address family not supported by protocol

**Comment by OneBlue** [comment]
Thanks for reporting this.

Given that WSL2 runs NATed, I wouldn't expect tools like these which appear to rely on ARP to discover machines to work.

Now `pcap_open_live` is interesting. I wonder which address family isn't supported here. Can you share an strace of that command so we can figure that out ?

**Comment by JaK0B-Pro** [comment]
> Thanks for reporting this.
> 
> Given that WSL2 runs NATed, I wouldn't expect tools like these which appear to rely on ARP to discover machines to work.
> 
> Now `pcap_open_live` is interesting. I wonder which address family isn't supported here. Can you share an strace of that command so we can figure that out ?

didn't understand

**Comment by OneBlue** [comment]
You can find more info about ARP [here](https://en.wikipedia.org/wiki/Address_Resolution_Protocol). Basically WSL runs in its own 'network', and ARP requests can only be sent on the same network (they don't traverse routers).

Regarding the strace, you can find instructions on how to do that [here](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#6-strace-of-the-failing-command) (see '6) Strace of the failing command
')

**Comment by 0xbadfca11** [comment]
> 4.4.0-19041

This kernel version indicates that you are using WSL1.

**Comment by JaK0B-Pro** [comment]
> 
yes i got it when i run 

> > 4.4.0-19041
> 
> This kernel version indicates that you are using WSL1.

yes, I discover it when I run the command 'wsl --list --verbose' on an administration PowerShell.

**Comment by chezis45** [comment]
My netdiscover works WSL but no machines found.
