### ISSUE TITLE
WSL Distro Installation Error after Windows File System Cleanup

### ISSUE THREAD

**Issue by maddes-b** [microsoft/WSL#7266]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1151]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu

### Repro Steps

> wsl --install -d Ubuntu
Ubuntu ist bereits installiert. / Ubuntu is already installed.
Ubuntuwird gestartet... / Ubuntu is started...

>wsl --list -v
Für das Windows-Subsystem für Linux wurden keine Distributionen installiert.
Distributionen zur Installation finden Sie im Microsoft Store:
https://aka.ms/wslstore

### Expected Behavior

Installation installs Ubuntu distro.

### Actual Behavior

No installation.

### Diagnostic Logs

Assuming that a file system cleanup removed some files of the Ubuntu distro in %LOCALAPPDATA%.
[wsl.zip](https://github.com/microsoft/WSL/files/6919380/wsl.zip)

**Comment by maddes-b** [comment]
I was able to fix it with a workaround:
Go to the MS Store app, search for the distro, download it, then `wsl` worked correctly again.

**Comment by OneBlue** [comment]
Based on the logs it does look like the app was removed.  Closing since a workaround has been found.

**Comment by maddes-b** [comment]
wsl should recognize that the distro got removed and reinstall it via `wsl --install` instead of reporting that it is already installed.
