### ISSUE TITLE
Cant install feature WSL

### ISSUE THREAD

**Issue by Rubikon23** [microsoft/WSL#7275]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1151]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

-

### Distro Version

-

### Repro Steps

- run command in Poweshell console (run as administrator) dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
- reboot pc
- "we couldn't complete the updates undoing changes" after reboot

### Expected Behavior

the WSL function is installed

### Actual Behavior

the WSL function is not installed

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/6929587/wsl.zip)
logs DISM and CBS

**Comment by Rubikon23** [comment]
i will try this workaround but it doesn't work for me.
[https://github.com/microsoft/WSL/issues/931#issuecomment-265616518](comment)

**Comment by Ruomengsiming** [comment]
I uninstalled the wsl update using this tool from this url [https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d](url), and reinstall the update from this url [https://www.catalog.update.microsoft.com/Search.aspx?q=wsl](url). Hope this help.

**Comment by Rubikon23** [comment]
> I uninstalled the wsl update using this tool from this url [https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d](url), and reinstall the update from this url [https://www.catalog.update.microsoft.com/Search.aspx?q=wsl](url). Hope this help.

i can uninstalled the wsl. But installing update doesn't work(
![image](https://user-images.githubusercontent.com/51418727/128160612-31945bf5-2de9-4990-a089-b55bbbbeb0c5.png)
![image](https://user-images.githubusercontent.com/51418727/128160636-8ec76f56-39f5-431a-be93-ac375e9bcde3.png)

**Comment by Rubikon23** [comment]
after reinstalling wondows everything works) problem solved

**Comment by Ruomengsiming** [comment]
Not uninstall wsl, but uninstall wsl update, I solved it.
