### ISSUE TITLE
Can not start flink on windows from wsl2

### ISSUE THREAD

**Issue by wloverine** [microsoft/WSL#7276]
### Windows Build Number

Microsoft Windows [Version 10.0.18363.1679]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 18.04

### Repro Steps

- cd /mnt/c/modules/flink-1.11.1/
- ./bin/start-cluster.sh 
- then i got error:
> Starting cluster.
Starting standalonesession daemon on host CNPC1CG7AT.
/mnt/c/modules/flink-1.11.1/bin/flink-daemon.sh: error reading input file: Input/output error
/mnt/c/modules/flink-1.11.1/bin/taskmanager.sh: error reading input file: Input/output error
./bin/start-cluster.sh: error reading input file: Input/output error

### Expected Behavior

In wsl1,i can do this without any issue,but when i do the same thing, something just wrong, and i have to restart wsl.
I just want to put flink dir in windows, and i want to start flink from wsl2.

### Actual Behavior

Starting cluster.
Starting standalonesession daemon on host CNPC1CG7AT.
/mnt/c/modules/flink-1.11.1/bin/flink-daemon.sh: error reading input file: Input/output error
/mnt/c/modules/flink-1.11.1/bin/taskmanager.sh: error reading input file: Input/output error
./bin/start-cluster.sh: error reading input file: Input/output error

**Comment by wloverine** [comment]
Does anyone meet the same problem?

**Comment by wloverine** [comment]
no body?

**Comment by Rupesh99201** [comment]
Hey Wloverine,

I faced the same problem a few days ago. Might the below-given link help you?

https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by wloverine** [comment]
> Hey Wloverine,
> 
> I faced the same problem a few days ago. Might the below-given link help you?
> 
> https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

Thanks，Rupesh!
