### ISSUE TITLE
If you can help me please help me out 

### ISSUE THREAD

**Issue by MR-pentestGuy** [microsoft/WSL#7278]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1151]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Ubuntu app 

### Distro Version

Ubuntu

### Other Software

I have installed my windows 10 OS in on of the drive and that particular drive has been corrupted and my os has stopped working so i had to buy a new one and install my os on it 

So the thing i have another ssd where i have stored my wsl distro in it but since the main ssd drive which consists of my windows os has been killed . I had to install a new one now but here is the thing the wsl i am running is Ubuntu . and it is running in wsl2 i dont know how to retrive my data from ext4.vhdx now i need some files from it so that i can install new ubuntu . since i this is my new os Does anyone know how can i retrive my files from ext4.vhdx 

### Repro Steps

NIL

### Expected Behavior

NIL

### Actual Behavior

I just need the files from ext4.vhdx

**Comment by licanhua** [comment]
If you knows powershell, use [mount-vhd](https://docs.microsoft.com/en-us/powershell/module/hyper-v/mount-vhd?view=windowsserver2019-ps).
I didn't do the testing, but [tutorials](https://www.tenforums.com/tutorials/61391-mount-unmount-vhd-vhdx-file-windows-10-a.html) looks more easier for you to understand

**Comment by benhillis** [comment]
https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl
