### ISSUE TITLE
The core dumps when I run the Carla

### ISSUE THREAD

**Issue by acetyline** [microsoft/WSL#7279]
### Windows Build Number

Microsoft windows 11 22000:100

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu 20.04

### Other Software

Carla 0.9.12

### Repro Steps

Download the carla0.9.12 and then uncompress it. Then run the CarlaUE4.sh

### Expected Behavior

wslg open the carlaUE4

### Actual Behavior

The terminal gives:
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.

**Comment by Chan0081** [comment]
Got the same issue. According to [this](https://github.com/carla-simulator/carla/issues/3196#issuecomment-678344107), there is no core dumps. The real problem is there is no GUI rendered.
My question is: is wsl able to render carla GUI?

**Comment by Phoolore** [comment]
hi there. ChatGPT said I need vulcan
after
```
sudo apt install vulkan-tools
```
check with
```
vulkaninfo | less
```
and it worked, you can also try doing so with -nosound
```
./CarlaUE4.sh --quality-level=Low -nosound
```
