### ISSUE TITLE
Not found .exe file of custom distribution

### ISSUE THREAD

**Issue by AntKerf** [microsoft/WSL#7280]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Install Ubuntu 20.04 from Microsoft Store
Run Ubuntu 20.04, create user.
wsl --export ubuntu-20.04 d:\wsl\ubuntu20.04.tar
wsl --import WorkUbuntu d:\wsl\WorkUbuntu D:\wsl\ubuntu20.04.tar
Uninstall Ubuntu 20.04 in start menu

### Expected Behavior

Now WorkUbuntu uses the Root user by default, but using the `wsl -u user` command, it successfully authenticates
I would like to set the default user using the command `WorkUbuntu config --default-user user`

### Actual Behavior

WorkUbuntu: The term "WorkUbuntu" is not recognized as the name of a cmdlet, function,....
```
+ WorkUbuntu config --default-user user
    + CategoryInfo          : ObjectNotFound: (WorkUbuntu:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
    
I tried to find the WorkUbuntu.exe or Ubuntu-20.04.exe file in the `C:\Windows\System32` folder, but there I only find wsl.exe and wslconfig.exe    

### Diagnostic Logs

https://aka.ms/AAdctaj

**Comment by 0xbadfca11** [comment]
Use wsl.conf instead.
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user

**Comment by benhillis** [comment]
Importing a distro does not create an executable, that's a property of the appx you install.
