### ISSUE TITLE
Cannot build aosp on wsl2

### ISSUE THREAD

**Issue by XiaochenFTX** [microsoft/WSL#7283]
### Windows Build Number

10.0.19042.1110

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Repro Steps

1. install Ubuntu 18.04
2. set wsl version 2 for Ubuntu 18.04
3. download aosp source code
4. try to build

Then it shows this error：
Failed to listen for path logs: listen unix out/.path_interposer_log: bind: operation not supported

system info:
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=mini_emulator_x86_64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86_64
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-Ubuntu-18.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QP1A.191105.004

### Expected Behavior

Can be built successfully like in a linux host

### Actual Behavior

Failed to listen for path logs: listen unix out/.path_interposer_log: bind: operation not supported

**Comment by benhillis** [comment]
What directory are you trying to build from?

**Comment by XiaochenFTX** [comment]
> What directory are you trying to build from?

/mnt/c/aosp

**Comment by WSLUser** [comment]
Have you tried /home/user instead? It may be an interop issue. At the very least, you're going to have a major perf drop using a Windows directory,.

**Comment by benhillis** [comment]
Yes for building android I'd strongly suggest building out of the ext4 file system (like your home directory).

**Comment by YuanYingqiu** [comment]
重新挂载aosp文件夹所在的盘符，指定文件系统为drvfs，比如我的是H盘。

sudo umount /mnt/h
sudo mount -t drvfs H: /mnt/h -o metadata

这个问题是真的坑爹，网上说的全是WSL升级为WSL2。但是WSL2照样碰到这个问题。
