### ISSUE TITLE
WSL Still Fundamentally Broken and Inoperative on Windows 10:  "Invalid argument" on program launch from terminal/shell

### ISSUE THREAD

**Issue by kevinsullivan** [microsoft/WSL#7285]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1151]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.16

### Distro Version

Ubuntu 18.04, Ubuntu 20.04. Problem confirmed on both up-to-date distributions

UPDATE: In addition, I have now confirmed that the problem exists on both Windows 10 Home and Windows 10 Education, which is Windows Enterprise plus some educational cruftware.

### Other Software

Docker Desktop Windows. Current version. 

### Repro Steps

Follow any of the online instructions for installing Docker Desktop on Windows (Home) 10. 
- Enable Intel virtualization in BIOS (was already done)
- Run Windows Update as many times as necessary to obtain most recent build
- Enable required windows features in Windows Features
- Install WSL 2 Ubuntu 20.04 (I currently have 18.04  to see if dropping back would help. It didn't.)
- Install required kernel patch
- Boot up WSL Ubuntu 20.04, set username and password, launches and works ok
- Install Docker Desktop 3.5.2 (66501), with option for Install Windows component checked, succeeds
- Install VSCode, but problem is not VSCode specific)
- Run "code" command. Works first time. Thereafter is produces the error indicated under Actual Behavior below

### Expected Behavior

The expected behavior is that I can run applications from a WSL 2 Ubuntu 20.04 (or 18.04 or whatever) terminal window. I do this all the time on my Windows 10 Professional machines at both home and work, but I need this to work on Windows HOME, as that's what almost all of my students use. 

### Actual Behavior

The actual behavior is that I invariably get the following message:

``` sh
code .
/mnt/c/Program Files/Microsoft VS Code/Code.exe: Invalid argument
```

Note that I get this message when trying to run a variety of Windows programs

### Diagnostic Logs

For what it's worth, I've got a PhD in computer science, expertise in software engineering. I've spent quite a few hours trying all manner of combinations and permutations to get WSL 2 and Docker for Window running on a *completely up-to-date* install of Windows 10 Home. It's always worth being skeptical of bug reports due to possible user error. I'm highly confident that this isn't user error. I could still be wrong, but I don't think so.

**Comment by benhillis** [comment]
Also dmesg output would be helpful (and won't be included in the logs).
