### ISSUE TITLE
WSL1 Support

### ISSUE THREAD

**Issue by tamusjroyce** [microsoft/WSL#7288]
Could WSL1 support be continued? And strong recommendations to use WSL2 be furloughed? Filesystem performance and Linux Kernel compatibility aren't as important as being able to run something. I have a cloud VM that doesn't support virtualization. 

A pipe dream would be to push WSL1 to zsh and work to remove all GPL licensed software. And maybe some day paragon can remedy the filesystem performance issues.

**Comment by tamusjroyce** [comment]
Feel free to close after reading if this is a duplicate or within scope / the current road map

**Comment by benhillis** [comment]
We have no immediate plans to stop supporting WSL1.
