### ISSUE TITLE
Export the distro to a tar file without home

### ISSUE THREAD

**Issue by OhCrazy7** [microsoft/WSL#7296]
**There is no export options**
By now, I can only backup my distro with the whole home directory. It would generate a huge tar file that contains the repos or downloads. The repos are on the server or GitHub, and the download can be downloaded again. The only thing I may need to backup is ".oh-my-zsh" and any other files contain the user's config in the home.

So, I think my home directory is not necessary to be packed.

**Please add --exclude-file option for export**
wsl --export --exclude-file=/home backup.tar
wsl --export --exclude-file=/home/username/Repo,/home/username/Downloads backup.tar
Please add the "--exclude-file" option to exclude the selected files, as the tar option does.

**Comment by Biswa96** [comment]
Instead of using wsl.exe, you could use bsdtar or tar binary in that distribution to export. You would have more command line options to fine tune the tarball.

**Comment by OhCrazy7** [comment]
> Instead of using wsl.exe, you could use bsdtar or tar binary in that distribution to export. You would have more command line options to fine tune the tarball.

I do use the tar binary to backup my previous linux by:
`tar -czpvPf /home/backup/backup.tar.gz --exclude-from=/home/backup/exclude /`
and backup with the live cd:
`tar -zxvpf /mnt/home/backup/backup.tar.gz -C /mnt`
However, I don't how to use wsl to do that. If there are some other ways to do this, I'm glad to learn.

**Comment by Biswa96** [comment]
wsl.exe just executes C:\Windows\System32\lxss\tools\bsdtar binary to do that, no extra magic. But wsl.exe don't accept other options (like `--exclude`) that you've said in original post.

**Comment by benhillis** [comment]
Agreed with @Biswa96 - if you want better control over what gets exported you can always do something like:

`wsl.exe tar -c --one-file-system -f - . > distro.tar`
