### ISSUE TITLE
--set-version 2 does not work

### ISSUE THREAD

**Issue by TobixDS** [microsoft/WSL#7297]
### Windows Build Number

Microsoft Windows [Version 10.0.19041.867]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

I am trying to convert a fresh installed Ubuntu-20.04 from WSL1 to WSL2

Trying to convert with
`wsl --set-version Ubuntu-20.04 2`

But the distro stays on WSL 1

I have studied several articles on the internet with similar issues and checked several times their hints:
- Windows is not running inside  a VM
- Feature Virtual Machine Platform is enabled
- Feature Windows-Subsystem for Linux is enabled
- Feature Hyper-V is enabled
- BIOS VT and DEP are on
- bcdedit hypervisorlaunchtype is set to auto

### Expected Behavior

The distro upgrades to WSL2 or at least a helpful error message is displayed.

### Actual Behavior

Distro stays on WSL1 - no error message what went wrong.

### Diagnostic Logs

I have taken logs using the wpr
[wsl2.zip](https://github.com/microsoft/WSL/files/6962098/wsl2.zip)

**Comment by benhillis** [comment]
The error is still indicating that the hypervisor isn't running.  Could you check `msinfo32` and see if the virtualization settings look right?  Are there any errors in eventvwr about the hypervisor not starting?

**Comment by TobixDS** [comment]
Hi Ben,
thanks for your reply.
msinfo32 looks fine  
![image](https://user-images.githubusercontent.com/59607923/128916684-83d69240-fe00-42fc-aa18-85cc43a9a511.png)

But the Eventvwr shows a failing hvservice.sys which then blocks HvHost.
The error message is for both of them: "Element not found".

Any ideas what might block the hvservice.sys?

**Comment by TobixDS** [comment]
I Found a promising link. 

https://rog.asus.com/forum/showthread.php?112543-Hyper-V-Broken-in-BIOS-1902-for-PRIME-X299-DELUXE

It seems that my motherboard's BIOS is the culprit.

I will report as soon I have made a BIOS upgrade.

**Comment by benhillis** [comment]
Excellent, thanks @TobixDS.  I'm trying to see if we can make more specific error codes for this case.  Currently there is no distinction between the hypervisor not being installed, and the hypervisor failing to start.

**Comment by TobixDS** [comment]
Hi Ben,
Hyper-V is now running an the distro migrated to version 2.
It was indeed the non-running Hyper-V caused by the v1902 BIOS from ASUS.
Thanks for your help.
