### ISSUE TITLE
WSL2 does not start right away

### ISSUE THREAD

**Issue by jamestut** [microsoft/WSL#7298]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Repeatedly call `wsl.exe -- (command)` from a Windows program or script.
2. That's it! Not every `wsl.exe` call works. If you do this in a rapid succession, let's say four times a second, then probably out of 10 `wsl.exe` calls, 5 succeeded, while the other 5 failed as if nothing happened.

### Expected Behavior

`wsl.exe` should start the requested program inside the WSL2 Linux distro right away.

![image](https://user-images.githubusercontent.com/15940448/128889865-5c17199e-d4fa-42bd-9779-abdd525f7e47.png)

### Actual Behavior

Sometimes WSL2 does not want to start immediately. Instead it just bail out. This problem gets worse the more often I invoke the `wsl.exe` from a Windows program or script. As I was doing something here with a program, the problem is very easy to reproduce. As can be seen in this terminal, `wsl.exe` just does nothing after several attempts.

![image](https://user-images.githubusercontent.com/15940448/128890237-d84d596d-142d-46b9-b562-76acf7175a6e.png)

Note that this problem is not limited to 1904x builds, but all insider builds as well all the way to Windows 11 beta builds like 22000.

**Comment by GrumpyMeow** [comment]
I'm also having this issue. I was setting up a new Windows 10 2004 machine. I suspect the issue is caused by one of the Windows Updates.

**Comment by jamestut** [comment]
@GrumpyMeow hmm, actually I have been experiencing this issue long time ago, around early 2004 release (19041.267). However, with this latest update, the problem is even more pronounced. Previously it would only fail in the script, but never failed on manual `wsl` invocation. This time it can fail consistently even with manual invocation and after the script has long been stopped. Will check again (and make a dump) when I got the chance to rapid fire WSL2 from my script.

The problem doesn't appear right away in my case. Has to do prolonged scripting WSL2 on a Windows app for it to appear. Once appeared, I can consistently reproduce it until next WSL2 shutdown.
