### ISSUE TITLE
Add wsl --mount support to Server 2022

### ISSUE THREAD

**Issue by JonahMGDV** [microsoft/WSL#7299]
**Is your feature request related to a problem? Please describe.**
We are a BaaS/DRaaS provider, trying to leverage a new API added to our backup software. This API allows us to mount data from backed-up systems using iSCSI to access the data in a read-only manner. This works fine with Windows systems, but the data isn't accessible if the API is used on a Linux machine. 

**Describe the solution you'd like**
Ideally, we would like wsl --mount to be a feature in Server 2022, so that we can programmatically mount the Linux data to perform virus scans and other data manipulation to the data without accessing/affecting the production environment.

**Describe alternatives you've considered**
DiskInternals Linux Reader however there doesn't seem to be support to make the data accessible using a CLI.

**Comment by OneBlue** [comment]
Hello, thanks for the request.

Unfortunately wsl --mount requires wsl2, which isn't supported on server. We don't have plans to add wsl2 to Windows Server at the moment, so my recommendation would be to use Windows desktop to use wsl --mount.
