### ISSUE TITLE
wsl not umount the old `root` value in config file.

### ISSUE THREAD

**Issue by Abunwer** [microsoft/WSL#7304]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 

### Distro Version

Ubuntu 20.04

### Repro Steps

* I created wsl.conf file using `sudo nano /etc/wsl.conf` inside the ubuntu distro, with the following content:
``` 
[automount]
enabled=true
root=/mnt/
```
* then shutdown it from windows `wsl --shutdown Ubuntu` then wait 8 seconds, and run it again
* the `/mnt/` directory contains the mounted directories and files as expected.
* update the `wsl.conf` file again with the following content: 
``` 
[automount]
enabled=true
root=/mnt2/
```
* shutdown the distro as before and rerun it again.

### Expected Behavior

it should mount the directories to `/mnt2/` and umount the old directory which is `/mnt/`.

### Actual Behavior

What happend instated is the two directories are mounted, `/mnt/` and `/mnt2/`.

### Diagnostic Logs

I'm not sure if that's right or not but for me it make sense to mount the new configured directory and unmount the old ones.

**Comment by 0xbadfca11** [comment]
Are you looking at empty directories in /mnt?
https://github.com/microsoft/WSL/issues/3155#issuecomment-388119693

**Comment by Abunwer** [comment]
@0xbadfca11 okay I see, I just look into the folders and they were empty, sorry I didn't check if they contains files or not.
