### ISSUE TITLE
First time WSL installation of Ubuntu

### ISSUE THREAD

**Issue by joebednarz** [microsoft/WSL#7307]
### Windows Build Number

Microsoft Windows [Version 10.0.18363.1679]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.02

### Other Software

Docker Desktop 3.6.0

### Repro Steps

First time setting up WSL 2.  Need to use Ubuntu 20.04
NO access to Microsoft  Store so using instructions to manually install, found here:  https://docs.microsoft.com/en-us/windows/wsl/install-manual

Downloaded Ubuntu_2004.2020.424.0_x64.appx

PS C:\Docker-Data> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2

PS C:\Docker-Data> Add-AppxPackage .\Ubuntu_2004.2020.424.0_x64.appx

--- shows a progress bar across top and then goes back to prompt once finished.

PS C:\Docker-Data> wsl --list --verbose
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2

### Expected Behavior

From documentation, I suppose once I use the Add-AppxPackage command, I should be prompted to enter credentials for the Ubuntu machine, but that never happens.

### Actual Behavior

Nothing happens.

**Comment by benhillis** [comment]
Docs are a bit unclear this is required.

**Comment by joebednarz** [comment]
Thank you for the reply Ben.  I just found this link:  https://docs.microsoft.com/en-us/windows/wsl/install-on-server

Is that what you are talking about when you say to launch your distribution?
