### ISSUE TITLE
SSH port forwarding isn't always reachable from Windows applications

### ISSUE THREAD

**Issue by idl0r** [microsoft/WSL#7311]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1151]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04 + 21.04

### Other Software

OpenSSH

### Repro Steps

Only tested with IPv4 so far:
`ssh -4 -L 1337:10.8.6.1:80 -L 4389:192.168.100.2:3389 -L 5900:127.0.0.1:5900 -L 11334:127.0.0.1:11334 -L 28016:127.0.0.1:28016 ...`

### Expected Behavior

Firefox, Chrome and other stuff running on the same Windows client should be able to connect to it

### Actual Behavior

From a WSL Shell itself, like using curl or something else, it works just fine. So the actual forwarding via SSH is ok.
Firefox, Chrome from within Windows doesn't work. Chrome says connection refused and indeed it doesn't look like a timeout. Using PowerShell and like curl also fails with connection refused.
Disabling the Windows firewall doesn't help. WSL shutdown / restart helps.
So there must be something wrong between the connection of WSL and Windows.
This only happens sometimes! So like it works a few days / boots and then suddenly it doesn't until I reboot or restart WSL entirely. No idea what may cause it. Started the WSL shell too early?

**Comment by sorenwacker** [comment]
I use in WSL2 

    ssh -L 8000:localhost:8000 hostname

And then start a service at port 8000 on  the remote host, but cannot connect to that service anymore. 
This was working perfectly until a few weeks ago. Now, I have constantly issues. It is not restricted to ssh,
also services started locally cannot be reached with the browser. I have seen issues about this, but they were closed without being resolved.

**Comment by Gbeschbacher** [comment]
- Microsoft Windows [Version 10.0.22000.1515]
- WSL 2

Same Issue. The command I use inside WSL looks like this:
```
ssh -o ExitOnForwardFailure=yes -N -4 -p 951 -f -M -S .tmp_sock.sock 3000:127.0.0.1:3000 -L 9000:127.0.0.1:9000 tmp_hostname
```

Looks like there could be a Problem with ssh running in background? If I start the connection, the port forwarding sometimes work for 10 seconds and then stops. In the windows process list I could figure out that wslhost.exe is responsible for forwarding ports and disappeares after some time. This is the moment where the browser cannot connect to the port anymore and the connection is refused (can also be reproduced by curl commands from the command-line).

**Comment by Gbeschbacher** [comment]
I could figure out that this is an issue with the current release preview of windows 11 - here is the Feedback i sent them:
https://aka.ms/AAjf5us

**Comment by Hazzard17h** [comment]
I can workaroud this by binding the forwarding to all interfaces and using WSL2 IP from Windows.
Forwarding with: `ssh -L 0.0.0.0:8000:localhost:8000 hostname`
Find WSL IP with something like: `ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`
