### ISSUE TITLE
uLimit should not need root password removal for system-wide softwares (without shell access).

### ISSUE THREAD

**Issue by storm1er** [microsoft/WSL#7312]
### Windows Build Number

Microsoft Windows [version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

VSCode 1.59.0 with remote-wsl v0.58.2

### Repro Steps

Use a lot of extension and/or open a workspace with a lot of file

### Expected Behavior

All extensions are loaded correctly

### Actual Behavior

Extensions fail to load due to `EMFILE (too many open files)`
Not always the same extension.

## More information

As stated [here](https://github.com/Microsoft/WSL/issues/1688#issuecomment-638479701) by @JohnSully
> It's crazy that this is somehow marked closed and fixed. The sudo su workaround works for me, but that really shouldn't be necessary. **Needing to disable sudo passwords is a security risk.**

Also, the actual workaround remove WSL_* env vars which not viable in some cases, stated [here](https://github.com/Microsoft/WSL/issues/1688#issuecomment-643799147) by @pecigonzalo
> It actually does not even work, as doing sudo su - username removes all the WSL_ vars.

I see people around me still downgrading to WSL1, but it's clearly not a good option given the drawbacks.
Even [here](https://github.com/Microsoft/WSL/issues/1688#issuecomment-657142818) people do the same by @rbabayoff

The existing workaround from within the terminal does not work (like [this](https://github.com/Microsoft/WSL/issues/1688#issuecomment-663771496), [this](https://github.com/Microsoft/WSL/issues/1688#issuecomment-701244040) and more) and can't be used with VSCode with remote WSL as when the soft start it's already "logged in" to the WSL VM.

In the current state, there's no solution.

### Diagnostic Logs

Not needed.

**Comment by storm1er** [comment]
Related to #1688

**Comment by storm1er** [comment]
And even by using the "remove root password", it doesn't work

![image](https://user-images.githubusercontent.com/9821946/129363764-9e9d9322-7c8c-4773-a304-4ef0c9f20f37.png)

**Comment by pecigonzalo** [comment]
FYI, I do this now with https://github.com/pecigonzalo/dotFiles/blob/master/wsl/wsllogin.sh#L25 and a `sudoers` config that allows me to call that command without a password.

**Comment by storm1er** [comment]
Well thanks for the tips, even if it does not solve the initial issue.

**Comment by storm1er** [comment]
@pecigonzalo 

End of `~/.profile`:

```
sudo prlimit -p "$$" --nofile=10000:10000
exec sudo su storm --shell $SHELL
```

I shutdown WSL, then restarted VSCode:
![image](https://user-images.githubusercontent.com/9821946/129544648-fbd3902f-c3ca-4904-a986-52349f1923dc.png)

And in output of extensions I'm still getting EMFILE errors.

**Comment by pecigonzalo** [comment]
I dont undersand that output. In any case `sudo prlimit -p "$$" --nofile=10000:10000` works without `exec` info the shell again, as it changes it for the current process.
Regarding VSCode, I load this in my `.zshrc` file, not in `.profile` so YMMV. I believe `.profile` is only loaded for login shells, which VSCode is likely not. Additionally, I believe `.profile` is not hit if you have `.bash_profile` or `.bash_login` FYI.

**Comment by storm1er** [comment]
- I don't have any `.bash_*` files
- Moved the given lines onto `.zshrc`
- Same results, I need `exec ...` command to see the new limit
