### ISSUE TITLE
Snap and other etc.

### ISSUE THREAD

**Issue by Mikary31** [microsoft/WSL#7313]
I would like to see snap working, other than that I don't see what there is left to do. Except help with packages for the repos so they are updated and compiling problems are over come quickly. Thanks you all.

**Comment by cerebrate** [comment]
The short version is that snapd requires systemd, requests for which are the super-extra-mega-large-issue #994 . If you are willing to use one of the assorted third-party tools to get systemd running under WSL, snapd works now; otherwise...

/dupe #994

**Comment by Mikary31** [comment]
Thank you for returning an answer to my question.

**Comment by craigloewen-msft** [comment]
@cerebrate is correct we are tracking this at issue #994! /dupe #994
