### ISSUE TITLE
Missing files in C:\Windows\System32\lxss\lib

### ISSUE THREAD

**Issue by lewsmith** [microsoft/WSL#7314]
### Windows Build Number

10.0.19043.1165

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

Enable WSL

### Expected Behavior

To see libdxcore.so, libd3d12.so, libd3d12core.so, libdirectml.so in the C:\Windows\System32\lxss\lib

### Actual Behavior

I don't see these files, I only see 

```
Directory: C:\Windows\System32\lxss\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        16/12/2020     00:32         133088 libcuda.so
-a----        16/12/2020     00:32         133088 libcuda.so.1
-a----        16/12/2020     00:32         133088 libcuda.so.1.1
-a----        29/06/2021     13:04        6175952 libnvcuvid.so.1
-a----        29/06/2021     13:04         424448 libnvidia-encode.so.1
-a----        16/12/2020     00:32         192160 libnvidia-ml.so.1
-a----        29/06/2021     13:04         354816 libnvidia-opticalflow.so.1
-a----        16/12/2020     00:32       48606768 libnvwgf2umx.so
-a----        29/06/2021     13:04         678392 nvidia-smi
```

Any reason for why these files may be missing? 

I've followed WSL / NVIDIA Cuda guide, reinstalled numerous graphics drivers and disabled/re-enabled WSL.. I'm stumped.

Because of this all cuda tests fail

**Comment by htfy96** [comment]
Same. I performed a search in C:\ but found no library with these names

**Comment by craigloewen-msft** [comment]
You are on Windows build 19043, you need to be on Windows build 20150 or higher. I updated the docs to make this clearer!

https://github.com/MicrosoftDocs/WSL/commit/751f01af374534e7bd3423aa36aec52bb28da402

So to fix this please upgrade to the latest preview build on the Windows Insiders program!

Thank you for filing this!
