### ISSUE TITLE
Error 0x800704cf when launching a linux distribution after installation

### ISSUE THREAD

**Issue by alteiract** [microsoft/WSL#7318]
### Windows Build Number

Microsoft Windows [version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

wsl --install -d ubuntu : install ok
           C:\Users\alteirac>wsl --install -d ubuntu
           Téléchargement en cours : Ubuntu
            Installation en cours : Ubuntu
            Ubuntu a été installé.
            Lancement de Ubuntu...

Error windows : "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc\ubuntu.exe"
The network location cannot be reached. 

When i try to launch the distribution : 
Error windows : "Erreur réseau. Windows ne peut pas accéder à C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2020.424.0_x64__79rhkp1fndgsc\ubuntu.exe"
Error code : 0x800704cf

### Expected Behavior

lauching distribution

### Actual Behavior

![image](https://user-images.githubusercontent.com/89073959/129709624-f8e5bd18-ec37-41c9-8193-0ea247079143.png)

### Diagnostic Logs

[wsl logs.zip](https://github.com/microsoft/WSL/files/6999096/wsl.logs.zip)
[wsl2.zip](https://github.com/microsoft/WSL/files/6999115/wsl2.zip)

**Comment by somyaSarathi** [comment]
I've had experienced similar issue in the past. I had to reinstall it

**Comment by alteiract** [comment]
Thank you for your answer but I uninstalled and reinstalled with no more success.

**Comment by shreyansh** [comment]
Hi @alteiract

were you able to resolve this issue? I'm facing the same issue when ubuntu is getting launched:

>wsl --install -d ubuntu
Ubuntu is already installed.
Launching Ubuntu...

![image](https://user-images.githubusercontent.com/265734/163820461-2f954f19-12b6-4c05-a24b-8a29b68b743a.png)

**Comment by alteiract** [comment]
Hello shreyansh
No i I couldn't solve this problem

**Comment by N1nt3n** [comment]
> Hello shreyansh No i I couldn't solve this problem

I connect the network and open this app again then I can Install correctly. After that I can run wsl offline

**Comment by OBDE** [comment]
Any solution on this?

**Comment by Biswa96** [comment]
Which Ubuntu version did you install from Windows Store?
