### ISSUE TITLE
SDE64 cmd fails

### ISSUE THREAD

**Issue by cepera** [microsoft/WSL#7319]
works (on real linux):
```
$ cat hi.c
#include <stdio.h>

int main(void)
{
    if (__builtin_cpu_supports ("avx512vl"))
        printf("yay!\n");
    else
        printf("ops!\n");
    return 0;
}
# no sde
$ g++ hi.c && ./a.out
ops!
# sde without avx512
$ g++ hi.c && sde64 -hsw -- ./a.out
ops!
# sde with avx512
$ g++ hi.c && sde64 -skx -- ./a.out
yay!
```
wsl2 (same piece of code):

```
$ g++ hello.c && sde64 -skx -- ./a.out
E: Fork for injector launcher failed: Bad address
```
From intel side it probably won't be fixed: [same bug at community.intel.com](https://community.intel.com/t5/Intel-ISA-Extensions/SDE-on-Windows-Subsystem-for-Linux-WSL-fails/td-p/1184656)

_Originally posted by @cepera in https://github.com/microsoft/WSL/issues/5212#issuecomment-886268482_

**Comment by WSLUser** [comment]
Is this from WSL1 or 2? WSL2 shouldn't experience this issue since it uses a real kernel.

**Comment by cepera** [comment]
ok, I was sure for some reason I'm using wsl2, but figured out i'm wrong here. Sorry, closing this one.
