### ISSUE TITLE
Perl/tk menus not working for graphical applications

### ISSUE THREAD

**Issue by adinriv** [microsoft/WSL#7324]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.132]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu  20.10

### Other Software

Texlive 2021
Perl/tk 1:804.033-2build3

### Repro Steps

- Install texlive 2021
- Install `sudo apt-get perl-tk`
- Open `tlmgr --gui`
- Open a menu
- See the menu floating around.  Also, the menu doesn't work
![wrong menu](https://user-images.githubusercontent.com/624792/129979144-c4d7708c-69c0-4084-af73-f47e0fe831b7.png)

### Expected Behavior

Working menus in the correct places on the graphical interface (based on `python-tk`)

### Actual Behavior

Menus floating around and not working at all.  Clicking in the options makes the menu disappear and opening it again doesn't work.

**Comment by craigloewen-msft** [comment]
Can you please file this issue on the [WLSg repo](https://github.com/microsoft/wslg) as that is where we track GUI app related issues! Thank you!
