### ISSUE TITLE
metadata mount option does not work with Google Drive

### ISSUE THREAD

**Issue by ahupp** [microsoft/WSL#7333]
### Windows Build Number

10.0.19043.1165

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Debian 10.10

### Repro Steps

Google Drive appears as "G:" in Windows.  In WSL it's mounted with the metadata option:

$ mount | grep /mnt/g                                             
G:\ on /mnt/g type 9p (rw,noatime,dirsync,aname=drvfs;path=G:\;uid=0;gid=0;metadata;umask=22;fmask=11;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)

If I change ownership of a file on C: (also mounted with metadata on), the ownership change persists.  However, if I change ownership of a file in /mnt/g its silently ignored:

~ ❱ cd /mnt/g/My\ Drive                                           
/m/g/My Drive ❱ sudo touch hello                                      
/m/g/My Drive ❱ sudo chown adam hello                             
/m/g/My Drive ❱ ls -l hello                                           
-rwxr--r-- 0 root root 0 Aug 19 15:55 hello*

### Expected Behavior

Metadata changes are reflected on google drive mounts.

### Actual Behavior

Metadata changes are ignored on Google Drive mounts.

**Comment by benhillis** [comment]
@ahupp - do you know if Google Drive supports extended attributes?

**Comment by benhillis** [comment]
From a quick read it seems like they do not, which is how WSL stores Linux metadata.

**Comment by ahupp** [comment]
Ah that makes sense.  I found t[his doc](https://eclecticlight.co/2018/01/12/which-file-systems-and-cloud-services-preserve-extended-attributes/) which says Dropbox supports them, I've verified this works fine.  Issue can probably be closed then.

**Comment by benhillis** [comment]
Thanks for filing, this is good to know...
