### ISSUE TITLE
[Question] Redistribution rights on libraries C:\Windows\System32\lxss\lib

### ISSUE THREAD

**Issue by htfy96** [microsoft/WSL#7334]
Hi,

I'm wondering if people are allowed to redistribute libraries under C:\Windows\System32\lxss\lib, specifically:

```
libdxcore.so
libd3d12.so
libnvwgf2umx.so
libcuda.so
```

Asking this because I'm looking for ways to pack it into an unofficial distro and use it on regular HyperV machines, without going through the WSL infrastructure.

**Comment by craigloewen-msft** [comment]
These have the same redistribution rights as the rest of Windows, and are part of the Windows OS, they follow those same rules. You can check out the full [Windows License here](https://www.microsoft.com/en-us/licensing/product-licensing/windows10)!
