### ISSUE TITLE
wsl.exe --install displays usage

### ISSUE THREAD

**Issue by vcvuwac** [microsoft/WSL#7338]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Run `wsl --install`.

### Expected Behavior

You can install everything you need to run WSL2.

### Actual Behavior

You will see usage as if you run `wsl --help`.

### Diagnostic Logs

Similer to [this](https://github.com/MicrosoftDocs/WSL/issues/1054), but the explanation about `--install` can be found in the usage. In addition, I can run commands that were added in the same build, `wsl --update` and `wsl --status`.
I also tried `wsl --install -d Ubuntu`. It installed Ubuntu, but not the kernel. After I installed Ubuntu by the command, "The WSL2 kernel file cannot be found." was displayed by `wsl --status`, and `4.4.0-19041-Microsoft` was displayed by `uname -r` on installed Ubuntu.
Similer to #7332. I think KB5005033 has a bug that makes certain options of wsl.exe unrecognizable in certain environments.

**Comment by licanhua** [comment]
Are you using Windows server or Edition Windows 10 Enterprise for Virtual Desktops?

**Comment by willeccles** [comment]
This appears to be working as intended. The kernel is not installed by this command, only Linux distros. See here for instructions to install the kernel: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by benhillis** [comment]
@willeccles - agreed, but the error message could be better. I'll take a look at this.

**Comment by vcvuwac** [comment]
@licanhua 
I'm using Windows 10 Home.

@willeccles @benhillis 
> agreed, but the error message could be better.

I didn't write the exact error message when I ran `wsl --status`.
It is "The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl.exe --update'."
This message is appropriate if `wsl --install -d <DistroName>` is intended not to install the kernel.
However, [Microsoft Dev Blog](https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/) seems to say that the command can also be used for the first installation, which means that you don't have to manually install the kernel.
> Replace <DistroName> with the name of a Linux distribution found in the previous list command. This install command can be used for first time installation or for adding additional distributions after you already have WSL installed with the default Ubuntu distribution.

**Comment by benhillis** [comment]
@vcvuwac - that's a good callout, --install could / should ensure the kernel is installed as well.

**Comment by nlucis** [comment]
> This appears to be working as intended. The kernel is not installed by this command, only Linux distros. See here for instructions to install the kernel: https://docs.microsoft.com/en-us/windows/wsl/install-win10

These instructions say to use the `wsl --install` command.

**Comment by willeccles** [comment]
> > This appears to be working as intended. The kernel is not installed by this command, only Linux distros. See here for instructions to install the kernel: https://docs.microsoft.com/en-us/windows/wsl/install-win10
> 
> These instructions say to use the `wsl --install` command. Which still displays usage.

If you look in the Note box beneath that, it explains this behavior:

> The above command only works if WSL is not installed at all, if you run `wsl --install` and see the WSL help text, please try running `wsl --list --online` to see a list of available distros and run `wsl --install -d <DistroName>` to install a distro.

This issue states that `wsl --install` shows usage information, which is expected (and intended) behavior if WSL is already installed. The WSL kernel is installed separately from WSL (or at least was at the time of the issue--I've not been following along since then, so that may have changed).

**Comment by pjmartel** [comment]
I really don't understand why the intended and expected behavior should be to display usage information when WSL is already installed. It seems to me it should display a message saying something like "WSL already installed, please use wsl --install -d <distro> to install a distro". It is misleading as it is.

**Comment by bater53** [comment]
wsl --install -d What distro? 15-10? or 15-15?  Will that be understood?

**Comment by bater53** [comment]
And where would you request this?  PS or command line as admin I would believe.
