### ISSUE TITLE
Add Arch Linux WSL on Microsoft Store

### ISSUE THREAD

**Issue by Jimmy-Blue** [microsoft/WSL#7343]
Since many Distro like Ubuntu, openSUSE, Debian or Kali arrived on WSL through Microsoft Store, it should have a function where community can create their own WSL distro and upload it so people can download and use them.

**Comment by Biswa96** [comment]
The GNU/Linux distributions are provided by the creators, Microsoft Store just hosts them. ArchLinux developers do not want to provide the distributions for WSL. But if you are using ArchLinux then you should have already knew the ways to install it in WSL 😎

**Comment by Biswa96** [comment]
The GNU/Linux distributions are provided by the creators, Microsoft Store just hosts them. ArchLinux developers do not want to provide the distributions for WSL. But if you are using ArchLinux then you should have already known the ways to install it in WSL 😎

**Comment by Jimmy-Blue** [comment]
> 
> 
> The GNU/Linux distributions are provided by the creators, Microsoft Store just hosts them. ArchLinux developers do not want to provide the distributions for WSL. But if you are using ArchLinux then you should have already known the ways to install it in WSL 😎

I know how to install Arch Linux in WSL, but it can be kind of tricky for people to install it for the first time. I think we should add some kind of store that powered by community, where they can distribute different kind of distro, I guess.

**Comment by Biswa96** [comment]
> it can be kind of tricky for people to install it for the first time

That's the fun part of it.

> I think we should add some kind of store that powered by community

Many devs are already doing that and we're ending up to this https://xkcd.com/927/

> where they can distribute different kind of distro

Technically speaking, we already have https://archlinux.org/download/ 

Maybe start with this https://github.com/yuk7/ArchWSL

**Comment by Jimmy-Blue** [comment]
Hmm, I see. Thanks for the information.
