### ISSUE TITLE
Wildfly CLI/Remoting Connectivity Issues on Windows

### ISSUE THREAD

**Issue by ahmedalnuaimi** [microsoft/WSL#7344]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.160]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu 20.04

### Other Software

We have Wildfly 20 images that we run in Docker as a part of a Docker Compose cluster. We officially work on Macs but sometimes have to use Windows/PC for some development tasks. On Mac, everything works as expected. On Windows, we use WSL2 + the latest version of Docker Desktop (3.6.0) to run the same cluster. First, I noticed that I was unable to deploy using IntelliJ which uses remoting for deployment. The I started testing using a command like this: jboss-cli.sh/.bat --connect "ls" --user=admin --password=admin
I noticed that it would timeout exactly twice and then work on the third timeout. If I run the command in a loop it would fail twice, run successfully for a few times and then fail again. Increasing the connection-timeout in JBoss CLI's settings had no impact other than delaying the timeout message.
The most important observation is that this problem happens when I run jboss-cli from a Windows command prompt or from inside WSL. However, it DOESN'T happen if I open an interactive shell with docker exec -it [container] /bin/bash. Which means that it is most probably a routing problem.
I did make some tests with Wireshark and I can see some exchange of HTTP packets, and UPGRADE one included (from HTTP to JBoss Remoting protocol), and some ACKS.
The last thing that I want to mention is that I have absolutely no connectivity issues with any other type of connection. I'm running inside the same Docker Compose cluster Kafka, Redis, ActiveMQ, and many other microservices and I never had such problem with any of them. I can even access the Wildfly dashboard from the browser and use it for various deployment and configuration tasks without any problem.

### Repro Steps

1- Run Wildfly 20's Docker container

2- Try connecting to it using jboss-cli.bat/.sh

Ex command: jboss-cli.sh/.bat --connect "ls" --user=admin --password=admin

### Expected Behavior

CLI command run everytime.

### Actual Behavior

CLI commands mostly timeout.

**Comment by ecalcutin** [comment]
Probably same issue as https://github.com/microsoft/WSL/issues/7254

**Comment by ahmedalnuaimi** [comment]
> Probably same issue as #7254

That's a possibility although increasing the timeout had no impact on the final results.
