### ISSUE TITLE
When trying to start WSL2 "The RPC server is unavailable"

### ISSUE THREAD

**Issue by moss-acrid** [microsoft/WSL#7345]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

- Attempt to run WSL with the `wsl` command
- Get `The RPC server is unavailable.`
- Attempt to intall a a distro
- The following error message is displayed.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706ba
Error: 0x800706ba The RPC server is unavailable.
```

I think this could be related to DNS issues as I've displayed in the diagnostic logs. I'm using a VPN but disabling this does not fix my issue.

### Expected Behavior

WSL Boots

### Actual Behavior

`The RPC server is unavailable.`

### Diagnostic Logs

In event viewing I found that Host-Network-Service is missing the following parameters.

```
HostDnsServerList = '-Missing-'.
HostDnsSuffix = '-Missing-'.
```

Running `Get-DnsClientServerAddress` shows no DNS addresses.

```

InterfaceAlias               Interface Address ServerAddresses
                             Index     Family
--------------               --------- ------- ---------------
Local Area Connection 2              4 IPv4    {}
Local Area Connection 2              4 IPv6    {}
Local Area Connection               22 IPv4    {}
Local Area Connection               22 IPv6    {}
Ethernet                            15 IPv4    {}
Ethernet                            15 IPv6    {}
VirtualBox Host-Only Network        16 IPv4    {}
VirtualBox Host-Only Network        16 IPv6    {}
Local Area Connection* 8             9 IPv4    {}
Local Area Connection* 8             9 IPv6    {}
Local Area Connection* 10           12 IPv4    {}
Local Area Connection* 10           12 IPv6    {}
WiFi                                 8 IPv4    {}
WiFi                                 8 IPv6    {}
Loopback Pseudo-Interface 1          1 IPv4    {}
Loopback Pseudo-Interface 1          1 IPv6    {}
```

Running `ipconfig \all` also shows no DNS.

[wsl.etl](https://github.com/moss-acrid/file-dump/blob/main/wsl.etl)

EDIT: Added wsl.etl

**Comment by moss-acrid** [comment]
I've uploaded a WSL event log to a [repo](https://github.com/moss-acrid/file-dump/blob/main/wsl.etl).

**Comment by benhillis** [comment]
@moss-acrid - thanks, looks like the host network service is failing. I'll forward them this thread, thanks for reporting.

**Comment by benhillis** [comment]
@moss-acrid - as you've pointed out it looks like the dns cache service is not running. Is that something that you have disabled?

**Comment by moss-acrid** [comment]
I have not stopped the dns cache service as far as I am aware. But when I try to check in the console it says the dns cache cannot be displayed. If i try and start the service, it says it is already running. Bellow is a copy from cmd.

```
C:\Windows\system32>ipconfig /displaydns

Windows IP Configuration

Could not display the DNS Resolver Cache.

C:\Windows\system32>net start dnscache
The requested service has already been started.
```

**Comment by moss-acrid** [comment]
Another _possibly_ related issue I've been having is with the `Network Setup Service`. I've found that when this is enabled I get loads of [DIAL](http://www.dial-multiscreen.org/) packets being sent and recived, causing lag on my PC. When this is disabled WSL gives the error code `Error: 0x800106d9`, so I enable it when I'm attempting to use WSL.

**Comment by moss-acrid** [comment]
I finally found a solution to my issue. It was caused by PIA replacing the DNS Client service. Even after unintalling PIA the service wouldn't start because the registry still listed the Dnscache service as PIA's. To fix this I had to edit the registry entry to the correct bin path and then run the service.

**Comment by moss-acrid** [comment]
For anyone else with this issue here is detailed step by step as to how I fixed it.

- Open services and right click the `DNS Client` service, if the path to execuatble is not `%SystemRoot%\system32\svchost.exe -k NetworkService -p` then you may be having the same issue as me.
- Unintall PIA or whatever application has replaced this service.
- Check if the path was set to default, if so run the service.
- If the unintall did not clean up this issue, you will need to alter the registry entry for this service.
- In regedit go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache`
- Set the `Image Path` value to `%SystemRoot%\system32\svchost.exe -k NetworkService -p`
- Try and run the `DNS Client` service.

This is what worked for me, hope it can help anyone else.

**Comment by jibnew** [comment]
> For anyone else with this issue here is detailed step by step as to how I fixed it.
> 
>     * Open services and right click the `DNS Client` service, if the path to execuatble is not `%SystemRoot%\system32\svchost.exe -k NetworkService -p` then you may be having the same issue as me.
> 
>     * Unintall PIA or whatever application has replaced this service.
> 
>     * Check if the path was set to default, if so run the service.
> 
>     * If the unintall did not clean up this issue, you will need to alter the registry entry for this service.
> 
>     * In regedit go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache`
> 
>     * Set the `Image Path` value to `%SystemRoot%\system32\svchost.exe -k NetworkService -p`
> 
>     * Try and run the `DNS Client` service.
> 
> 
> This is what worked for me, hope it can help anyone else.

I have the same issue but the DNS Client service is running and the path to executable is as you say.

**Comment by dvglab** [comment]
> > For anyone else with this issue here is detailed step by step as to how I fixed it.
> > ```
> > * Open services and right click the `DNS Client` service, if the path to execuatble is not `%SystemRoot%\system32\svchost.exe -k NetworkService -p` then you may be having the same issue as me.
> > 
> > * Unintall PIA or whatever application has replaced this service.
> > 
> > * Check if the path was set to default, if so run the service.
> > 
> > * If the unintall did not clean up this issue, you will need to alter the registry entry for this service.
> > 
> > * In regedit go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache`
> > 
> > * Set the `Image Path` value to `%SystemRoot%\system32\svchost.exe -k NetworkService -p`
> > 
> > * Try and run the `DNS Client` service.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is what worked for me, hope it can help anyone else.
> 
> I have the same issue but the DNS Client service is running and the path to executable is as you say.

I had the same issue too. I just turned off PIA autostart at windows boot and now wsl works like a charm.

**Comment by temtasian** [comment]
For the people using PIA (or other VPN) Open Settings > go to Network > scroll all the way down the Split Tunnel apps list and find the "Name Servers" entry > select "VPN DNS Only"

**Comment by dvglab** [comment]
> For the people using PIA (or other VPN) Open Settings > go to Network > scroll all the way down the Split Tunnel apps list and find the "Name Servers" entry > select "VPN DNS Only"

Thanx @temtasian it works like a charm. No more mess with turn on/off PIA VPN when you need kubectl.

**Comment by Tinmanx64** [comment]
> For the people using PIA (or other VPN) Open Settings > go to Network > scroll all the way down the Split Tunnel apps list and find the "Name Servers" entry > select "VPN DNS Only"

Thanks much!
