### ISSUE TITLE
WSL rendered useless

### ISSUE THREAD

**Issue by rpuenter** [microsoft/WSL#7346]
Hi, I was having troubles with dpkg, anf following this link to try to fix them: 

https://askubuntu.com/questions/1160366/apt-not-working-installed-libc-bin-package-post-installation-script-subprocess

After doing 

sudo mv /var/lib/dpkg/info/libc-bin.* /tmp/

An error such as

 *** stack smashing detected ***: <unknown> terminated

appeared in the prompt and the WSL has been rendered useless. It does not start any more. That is the same output typing wsl -e ls in a powershell. The \\wsl$\ubuntu drive is not accessible either.

I have tried restarting both Windows and the WSL with the Restart-Service LxssManager command in a powershell. In addition, right click in App Settings brings up a menu that never stops trying to load something.

Windows version: 10.0.19042.0
WSL version 1
Ubuntu version in WSL 18.04.1 

If I need to reinstall the WSL, will the files in \\wsl$\ubuntu be deleted? I would rather avoid that.

Thanks in advance.

**Comment by craigloewen-msft** [comment]
It appears that you have a WSL start up error. 

What I would recommend is that you install a new WSL distribution (like Ubuntu or Debian) and then use the `wsl --mount` feature to mount the VHD from your past distro to access your files. [Instructions are here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl). 

However to do that you'll need to upgrade to the latest Insiders build.

If you can't upgrade, you could look at mounting the VHD manually into WSL using Linux commands. 

I'll close this issue out as it isn't actionable for our team (and the template isn't filled out) but let me know if you have more questions.
