### ISSUE TITLE
ls: cannot access 'c': Input/output error

### ISSUE THREAD

**Issue by xngyng** [microsoft/WSL#7347]
### Windows Build Number

Microsoft Windows [版本 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu18.04

### Other Software

Visual Studio Code with extension:Remote-WSL-v0.58.2

### Repro Steps

step1: open vscode,connect to wsl,and reports error:
sh: 1: /mnt/c/Users/admin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.58.2/scripts/wslServer.sh: Input/output error
step2: open wsl,use commond 'ls /mnt/,and reports error:
ls: cannot access 'c': Input/output error

### Expected Behavior

vscode can connect to wsl
ls can access 'c'

### Actual Behavior

ls: cannot access 'c': Input/output error

**Comment by licanhua** [comment]
Will `wsl --shutdown` help with your problem?
Not sure if you are hitting the same problem with #6174 or #3256.
Without a log, you may check `dmesg` in Ubuntu first. most likely you will see a error

**Comment by xngyng** [comment]
Well， it's ok  after running commond 'wsl --shutdown' 
Thanks!
