### ISSUE TITLE
Emojis made of multiple code points break tmux status bar rendering

### ISSUE THREAD

**Issue by carlpaten** [microsoft/WSL#7355]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

tmux 2.6 or 3.0a
Windows Terminal 1.9.1942.0 or Ubuntu Windows Store app 2004.2021.222.0

### Repro Steps

In Ubuntu command line:

```
tmux new-session -n 🕊️ 
```

### Expected Behavior

As on native Ubuntu: tmux status bar has only one line; clicking a window's name in the status bar switches to it

### Actual Behavior

tmux status bar wraps and spills onto a second line; clicking on a window's name in the status bar does nothing

**Comment by OneBlue** [comment]
@duhowett this looks like a console issue. How can we diagnose it ?

**Comment by lilred** [comment]
FYI I also posted this in the Terminal GH repo and apparently this is a known issue https://github.com/microsoft/terminal/issues/11053

**Comment by armanschwarz** [comment]
Is there a workaround for this in the meantime (other than just not using those characters)?
