### ISSUE TITLE
WSL2  can't ping any ip address  , and all Network status is DOWN

### ISSUE THREAD

**Issue by wangyongshuai88** [microsoft/WSL#7356]
### Windows Build Number

20H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

19042.1165

### Distro Version

debian Release:        10

### Other Software

Docker Desktop  3.6.0
VSCODE WSL remote

### Repro Steps

(base) shuidonger@FrozenOcean:~$ ping 127.0.0.1
connect: Network is unreachable

(base) shuidonger@FrozenOcean:~$ ip addr
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether a6:83:c7:b2:f1:e8 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:9d:b9:20:c9:da brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:15:5d:2b:b4:2d brd ff:ff:ff:ff:ff:ff
5: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
6: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

### Expected Behavior

please help me to fix this problem 

i have read lots of relate problem ,they all can't solve it.

when i  use     "ip  addr "

there all no ip address show in below.

And not only my Debian can't connected to Windows 10   ， but also  My docker desktop 。

My situation is so similar to：
https://stackoverflow.com/questions/66338549/wsl2-network-unreachable?r=SearchResults#
but i am not as lucky as him。

### Actual Behavior

acrodding to this page.
https://github.com/microsoft/WSL/issues/5286

when i manually configure eth0 and add a default route:

sudo ip address add 172.21.0.10/20 broadcast 172.21.15.255 dev eth0

(base) shuidonger@FrozenOcean:~$ sudo ip route add default via 172.21.0.1
Error: Nexthop has invalid gateway.

**Comment by ikrajshaik** [comment]
for me also same issue

**Comment by OneBlue** [comment]
Thanks for reporting @wangyongshuai88.

Can you please follow the ['networking issues'](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and share the output and the log file ?

**Comment by wangyongshuai88** [comment]
#

> Thanks for reporting @wangyongshuai88.
> 
> Can you please follow the ['networking issues'](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and share the output and the log file ?





Thank you very much  for your attention to this issue.  

The attach file is  my  log file。

I have also upload the  log file "WSL.etl"   in address https://github.com/wangyongshuai88/wslnetworkissue/blob/main/wsl.etl
[wsl.zip](https://github.com/microsoft/WSL/files/7147156/wsl.zip)

**Comment by jameslloyd** [comment]
I had this issue managed to solve with :

```
wsl --shutdown
```

Then opening the WSL terminal (ubuntu in my case) again

**Comment by amouhzi** [comment]
Check your antivirus. I had the same problem, I solved it by uninstalling the antivirus. (Note: it is recommended to have an antivirus).

**Comment by wangyongshuai88** [comment]
> I had this issue managed to solve with :
> 
> ```
> wsl --shutdown
> ```
> 
> Then opening the WSL terminal (ubuntu in my case) again

**Comment by wangyongshuai88** [comment]
> I had this issue managed to solve with :
> 
> ```
> wsl --shutdown
> ```
> 
> Then opening the WSL terminal (ubuntu in my case) again





I always do it  when i close my  wsl  .   I retry it  by now ，and found It don‘t work

**Comment by wangyongshuai88** [comment]
> Check your antivirus. I had the same problem, I solved it by uninstalling the antivirus. (Note: it is recommended to have an antivirus).

thank you ，when i close my antivirus ，it still the same status.    
I have using my wsl for 1 year , but found it broke recently .

**Comment by sma11black** [comment]
@wangyongshuai88 This may be caused by the **Memory Compression** feature in Windows 10. I fix a same problem  with disabling swap for wsl. You can check out https://github.com/microsoft/WSL/issues/5437#issuecomment-647161596 to try it out.

**Comment by wangyongshuai88** [comment]
> 
#5437 
oh my god!!!!!!!!   you are right  ！     windows   compress  the  “%temp%”   .
