### ISSUE TITLE
Kali Linux installation issue

### ISSUE THREAD

**Issue by PrayashPatel** [microsoft/WSL#7360]
![image](https://user-images.githubusercontent.com/52368768/131166042-b5bbecb6-7665-4e2c-a415-b1b79cfddeaf.png)

**Comment by owenschupp** [comment]
Hello, please refile this issue with the bug template found [here.](https://github.com/microsoft/WSL/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.yaml)
