### ISSUE TITLE
df gives wrong output

### ISSUE THREAD

**Issue by mcandre** [microsoft/WSL#7361]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

`df -h /`

### Expected Behavior

The command should output accurate numbers.

### Actual Behavior

WSL's df measures capacity in terms of the host resources, but measures usage in terms of the guest resources.

The numbers given are wrong and imply a lot more spare disk space than is actually available. Windows takes up many gigabytes, but that is not reflected in the df report.

**Comment by benhillis** [comment]
Thanks for reporting. Since the WSL2 file system is stored on a virtual hard disk, df is reporting the (maximum) size of that virtual disk.  We do have some backlog work items to make this experience better but plumbing through actual usage of the disk where the VHD is stored is not planned.
