### ISSUE TITLE
Error on Apche2 service start 

### ISSUE THREAD

**Issue by shubhamcloud9** [microsoft/WSL#7362]
### Windows Build Number

10.0.19042 Build 19042

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

ubuntu 18.04 LTS

### Other Software

 * Starting Apache httpd web server apache2                          [Sat Aug 28 13:55:57.704119 2021] [core:warn] [pid 209:tid 140156452080576] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

### Repro Steps

just hit

sudo service apache2 start

 * Starting Apache httpd web server apache2                          [Sat Aug 28 13:55:57.704119 2021] [core:warn] [pid 209:tid 140156452080576] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

### Expected Behavior

there should be no error .

 * Starting Apache httpd web server apache2                          [Sat Aug 28 13:55:57.704119 2021] [core:warn] [pid 209:tid 140156452080576] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

### Actual Behavior

its giving out the error:
 * Starting Apache httpd web server apache2                          [Sat Aug 28 13:55:57.704119 2021] [core:warn] [pid 209:tid 140156452080576] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

**Comment by stehufntdev** [comment]
Thanks for reporting the issue!  I did a quick search online for the error code above and found a number of references for resolving the issue by adding a file to the Linux filesystem (i.e. http://www.codza.com/blog/lamp-in-wsl-win10#:~:text=You%20can%20now%20start%20the%20apache%20server%3A%20You,should%20look%20like%20this%3A%20Install%20mysql%20by%20running%3A)

I do not think this is specific to WSL but please let me know if I misread the original issue.

**Comment by Aldo-f** [comment]
That url is not working anymore.
Please don't add only a link for future reference.

> Thanks for reporting the issue! I did a quick search online for the error code above and found a number of references for resolving the issue by adding a file to the Linux filesystem (i.e. http://www.codza.com/blog/lamp-in-wsl-win10#:~:text=You%20can%20now%20start%20the%20apache%20server%3A%20You,should%20look%20like%20this%3A%20Install%20mysql%20by%20running%3A)
> 
> I do not think this is specific to WSL but please let me know if I misread the original issue.

**Comment by Aldo-f** [comment]
This did the trick for me:

> Add the following line to the end of the /etc/apache2/apache2.conf file: 
> `AcceptFilter http none`

Source:
* https://github.com/microsoft/WSL/issues/1953#issuecomment-295370994
