### ISSUE TITLE
wsl is freezed after latest build update and not working 

### ISSUE THREAD

**Issue by Fighteros** [microsoft/WSL#7363]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.168]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

wsl command isn't working

### Distro Version

kali-linux

### Repro Steps

when i type bash or wsl the command is keep waiting and nothing returns to me the cursor keep blanking though everything worked just fine before latest build update 

### Expected Behavior

doing commands

### Actual Behavior

keep waiting to be executed

**Comment by JiiPee74** [comment]
Same here with ubuntu. File Explorer also hangs if you try to browse wsl home via it.

```
PS C:\Users\User> wsl
The operation timed out because a response was not received from the virtual machine or container.
```

**Comment by CoskunSunali** [comment]
Possibly related to #7351
