### ISSUE TITLE
Unable to change wsl version to 2. "wsl --set-default-version 2" prints usage.

### ISSUE THREAD

**Issue by ratheesh98** [microsoft/WSL#7369]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1165]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Steps:

1) Set up a Desktop VM on Azure with Windows 10 OS and FSV2 series machine. (Virtualization is enabled)
2) Install WSL 2 using steps listed in https://docs.microsoft.com/en-us/windows/wsl/install-win10 using Ubuntu 20.04 as distribution.

### Expected Behavior

WSL 2 should be installed and Ubuntu distribution should be running with version 2.

### Actual Behavior

The command ":wsl --set-version <distribution name> 2" fails printing the usage. No error is printed out by the command, so it is difficult to understand the reason for failure.

**PS C:\Windows\system32> wsl -l -v**
  NAME            STATE           VERSION
 Ubuntu-20.04    Running         1

**PS C:\Windows\system32> wsl --set-version "Ubuntu-20.04" 2**
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.

### Diagnostic Logs

strace output:

xxxx:/mnt/c/Windows/system32$ strace -ff wsl.exe --set-version "Ubuntu-20.04" 2
execve("/mnt/c/Windows/system32/wsl.exe", ["wsl.exe", "--set-version", "Ubuntu-20.04", "2"], 0x7ffff00a26e0 /* 19 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x29d800)       = 0
set_tid_address(0x29d838)               = 91
brk(NULL)                               = 0xbf5000
brk(0xbf6000)                           = 0xbf6000
sched_getaffinity(0, 128, [0, 1, 2, 3]) = 64
getpid()                                = 91
getcwd("/mnt/c/Windows/system32", 4096) = 24
uname({sysname="Linux", nodename="IN3AZCPUVDI-3", ...}) = 0
open("/dev/lxss", O_RDWR)               = 3
ioctl(3, _IOC(_IOC_NONE, 0, 0x2f, 0x22), 0x7ffff33cbea8) = 0
getcwd("/mnt/c/Windows/system32", 4096) = 24
open("/mnt/c/Windows/system32/wsl.exe", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_PATH) = 5
readlink("/proc/self/fd/5", "/mnt/c/Windows/system32/wsl.exe", 4095) = 31
fstat(5, {st_mode=S_IFREG|0555, st_size=107520, ...}) = 0
stat("/mnt/c/Windows/system32/wsl.exe", {st_mode=S_IFREG|0555, st_size=107520, ...}) = 0
close(5)                                = 0
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - wslfs r"..., iov_len=1024}], 2) = 972
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
getcwd("/mnt/c/Windows/system32", 4096) = 24
open("/proc/self/mountinfo", O_RDONLY)  = 5
readv(5, [{iov_base="", iov_len=0}, {iov_base="2 2 0:2 / / rw,noatime - wslfs r"..., iov_len=1024}], 2) = 972
readv(5, [{iov_base="", iov_len=0}, {iov_base="", iov_len=1024}], 2) = 0
close(5)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGPGRP, [88])               = 0
getpgid(0)                              = 88
fstat(0, {st_mode=S_IFCHR|0660, st_rdev=makedev(0x4, 0x1), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(0x4, 0x1), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0660, st_rdev=makedev(0x4, 0x1), ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=36, ws_col=172, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 -opost -isig -icanon -echo ...}) = 0
                                                                                 dup(0)                                  = 5
                                                                                                                            ioctl(4, _IOC(_IOC_NONE, 0, 0xb7, 0x22), 0x7ffff33cbe58) = 0
            ioctl(4, _IOC(_IOC_NONE, 0, 0xb7, 0x22), 0x7ffff33cbe58) = 0
                                                                        ioctl(4, _IOC(_IOC_NONE, 0, 0xb7, 0x22), 0x7ffff33cbe58) = 0
                                                                                                                                    write(4, "\0\0\0\0\317\0\0\0\r\0\0\0\0\0\0\0\16\0\0\0\0\0\0\0\17\0\0\0\0\0\0\0"..., 207) = 207
                                                      close(0)                                = 0
                                                                                                 close(1)                                = 0
                                                                                                                                            close(2)                                = 0
           rt_sigprocmask(SIG_BLOCK, [INT WINCH], NULL, 8) = 0
                                                              signalfd4(-1, [INT WINCH], 8, 0)        = 0
                                                                                                         poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
                       read(4, "\t\0\0\0 \0\0\0\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
                                                                                                           ioctl(4, _IOC(_IOC_NONE, 0, 0xa3, 0x22), 0x7ffff33cbe78) = 0
                                                                                                                                                                       poll([{fd=4, events=POLLIN}, {fd=0, events=POLLIN}], 2, -1Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.
) = 1 ([{fd=4, revents=POLLIN}])
                                read(4, "\7\0\0\0\f\0\0\0\377\377\377\377", 32) = 12
                                                                                    write(4, "\7\0\0\0\f\0\0\0\377\377\377\377", 12) = -1 EPIPE (Broken pipe)
                                                                                                                                                             close(1)                                = 0
                            close(3)                                = 0
                                                                       close(4)                                = 0
                                                                                                                  ioctl(5, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
close(5)                                = 0
exit_group(-1)                          = ?
+++ exited with 255 +++

**Comment by florinDNL** [comment]
Just came across the same issue - in my case it seems to be specific to Multi-Session Windows 10 WVD. Single-session works as expected. Confirmed virtualization is enabled and working.

If you try to change the version of only specific Distros using set-version, the same will happen. Weirdly, if you use these commands with version 1, everything is fine:


`C:\Users\wsltest>wsl --set-version debian 2
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.`

`C:\Users\wsltest>wsl --set-default-version 1
The operation completed successfully.`

**Comment by ratheesh98** [comment]
Event Viewer shows the following exception event. Not sure if it is related to the cause of this issue.

Line #, Provider Name, Task Name, Opcode Name, Id, Process, Event Name, Cpu, ThreadId, File (Field 1), FunctionName (Field 2), Line number (Field 3), Type (Field 4), HRESULT (Field 5), Message (Field 6), Code (Field 7), Field 8, Field 9, Count, Time (s)
3, Microsoft.Windows.Subsystem.Lxss, LxssException, win:Info, 0, Unknown, LxssException, 2, 7396, onecore\vm\wsl\lxss\wslclient\dll\wslclient.cpp, , 928, 0, 0x80040301, , , , , 1, 6.922484400

**Comment by florinDNL** [comment]
Could be related to: https://github.com/microsoft/WSL/issues/7332

I just checked on 2 fresh WVDs (2004 and 21H1) and KB5005033 is present on both, and so is the issue: 

![image](https://user-images.githubusercontent.com/79944491/131328268-cb790a32-2cea-4dbc-990f-1033cdc33014.png)

Sadly it cannot be uninstalled

**Comment by ratheesh98** [comment]
Thanks @florinDNL This worked after uninstalling KB5005033.

**Comment by ratheesh98** [comment]
Closing as dupe of https://github.com/microsoft/WSL/issues/7332
