### ISSUE TITLE
wsl.exe frozen (unable to run any distributions or wsl --list)

### ISSUE THREAD

**Issue by sfreed141** [microsoft/WSL#7372]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

unable to run

### Distro Version

n/a

### Repro Steps

Open terminal (cmd or powershell doesn't matter) and run `wsl.exe`. I see the same behavior with `wsl.exe --list` and `wsl.exe --status`

### Expected Behavior

WSL terminal opens

### Actual Behavior

wsl.exe appears to freeze. Must be killed with ctrl+c.

Possibly related to #7363.

### Diagnostic Logs

I attached a debugger and this is the callstack:
<img width="286" alt="wsl-hang" src="https://user-images.githubusercontent.com/6880264/131407481-5147242b-e17a-45bd-b42d-40a37712d2b1.png">

**Comment by benhillis** [comment]
Could you check the status of the "lxssmanager" service? I suspect it is stuck in the stopping state, I've seen this previously.

**Comment by sfreed141** [comment]
![image](https://user-images.githubusercontent.com/6880264/131542318-98dee3ff-ede9-4270-9bbf-9045753cf0a3.png)
LxssManager appears to be running, but the two *User variants are stopped. I tried starting them both but LxssManagerUser wouldn't start and LxssManagerUser_34193772 would go back to stopped after a few seconds.

**Comment by benhillis** [comment]
The LxssManagerUser service isn't used in this path, that's for a niche scenario of trigger starting distros through \\\\wsl$.

Looks like a deadlock in the lxssmanager service, that process is pretty locked down so there's not a great way to generate a dump of it.  Do you have any repro steps for how you got into this state?

**Comment by sfreed141** [comment]
No repro steps unfortunately. I ran into it while using Visual Studio (the CMake extension tries listing WSL distros at some point and caused VS to hang). I can't confirm because of the hang but believe I only have two distros installed, Ubuntu 18.04 LTS and Ubuntu 20.04 LTS. I think they're both WSL1 but I'm not 100% sure.

I'll try reinstalling WSL and restarting Windows to see if that fixes the issue (I was holding off in case there were any additional logs you might want).

**Comment by sfreed141** [comment]
Confirmed restarting my computer fixed the issue. Here's the output of `wsl --list -v` and `wsl --status` in case it helps:
```
❯ wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Stopped         1
  docker-desktop         Stopped         2
  Ubuntu-18.04           Stopped         1
  docker-desktop-data    Stopped         2

❯ wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 7/20/2021
WSL automatic updates are on.

Kernel version: 5.10.16
```

Also as for repro steps I remember I had VSCode open and connected to one of the WSL instances (using the remote extension). Perhaps having that open for a long time (and sleep cycles from closing/opening laptop) could've been part of the issue.

**Comment by zzjin** [comment]
I/m face the same issue when closing vscode. After using and closing vscode and wait some time, wsl will try to shutdown itself, but cannot start forever.

Any command `wsl`, `wsl --shutdown` `wsl --status` hang for ever with not any output message.

**Comment by silvano** [comment]
Similar issue here.

System
- Windows Surface Pro X, arm64
- WSL2 
- Ubuntu-22.04.1 LTS (only distro)

Description
- WSL freezes after some time of use. It usually happens after 30-120 min. after startup.
- It seems the freeze happens earlier on heavier use, e.g. running a Python debugging session in the VSCode terminal usually causes it to freeze after 30 min.
- When the freeze happens VmmemWSL CPU load is constantly at 15-20%, which seems to be the maximum on my system.
- Sometimes the system recovers after around 10-20 minutes, then CPU load of VmmemWSL goes back down.
- Sometimes the system does not recover which requires a full Windows restart. Even after closing all Distor terminals and/or VSCode, wsl --shutdown does not manage anymore to stop WSL in this case.
- This happens each time I use WSL2

Other things I noticed
-  "Virtual Machine Worker Process" is constantly at 15-20% as soon as WSL2 was started and idle.
- Running top inside Ubuntu does not show any excessive CPU load (all processes are at 0-1%)
- I have an identical setup (WSL2, Ubuntu 20.04.1, with the same packages installed) on an Intel x64 laptop. Running without issues. Also, VmmemWSL and "Virtual Machine Worker Process" on this machine never show maxed out CPU usage, when idling they are at 0-1%.

Measures taken so far
- Made a clean reinstall of the Ubuntu distro
- Disabled all extensions in VSCode, then I have more time until the freeze happens
- Other memory / CPU intensive operations like "tar -czvf" a larger folder directly from the Terminal (never starting VSCode), also cause freezes, but usually recover after 10-20 min.
- Tried many different settings in .wslconfig (limiting core, limiting memory, change swap, gui settings, etc.). None of them eliminate the freezes.

WLS Status
```
wsl --status
Default Version: 2
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401 
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.590
```

**Comment by hohwille** [comment]
After a long timeout I get an error message:
```
$ wsl -l
Server execution failed
```
