### ISSUE TITLE
can not find GPU by lspci

### ISSUE THREAD

**Issue by wqh17101** [microsoft/WSL#7376]
### Windows Build Number

Microsoft Windows [version10.0.19043.1200]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop Windows ver 3.2.2
![image](https://user-images.githubusercontent.com/26429138/131662397-b90c45aa-7611-48a6-b596-b0aa30f00c9e.png)

### Repro Steps

follow https://docs.nvidia.com/cuda/wsl-user-guide/index.html#ch03a-setting-up-cuda to set my env
```lspci```
got nothing 

### Expected Behavior

got GPU 

### Actual Behavior

nothing got by `lspci`
![image](https://user-images.githubusercontent.com/26429138/131662032-f42cc440-b453-4cfc-b251-33195f224a4a.png)

### Diagnostic Logs

i find a issue #6340 that had similiar problem

**Comment by wqh17101** [comment]
i can get the result after i update OS to win11 the latest ver

**Comment by brut0** [comment]
Same problem. But I can't update OS to win11
