### ISSUE TITLE
WSL Not working after windows 11 updates

### ISSUE THREAD

**Issue by ps60194** [microsoft/WSL#7379]
### Windows Build Number

22000 rekease 210604

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

ubuntu and kali and dockeer

### Other Software

WSL not working receive error message on virtualization not being enabled.  Completed all verification steps and virtualization is activated 

### Repro Steps

attempt to access ubuntu or kali linux installation and receive error message on virtualization not enabled.  completed all verification steps and virtualization is configured properly

### Expected Behavior

wsl will work

### Actual Behavior

wsl does not work

**Comment by somyaSarathi** [comment]
I had the same issue. Then I had to reinstall.
