### ISSUE TITLE
Bash User Configurability / Winning Developers

### ISSUE THREAD

**Issue by jlukic** [Microsoft/WSL#738]
I'm a Win user who has previously done all my [FOSS](https://github.com/Semantic-Org/Semantic-UI)/Proprietary work on an Ubuntu VM. 
### Missing User Configuration

One of the things that would make bash for windows much more viable for converting developers like me would be to reach parity with ubuntu's terminal for customization and ease-of-use.
- Add ability to launch multiple bash tabs (_this is essential_), and add standard ubuntu keyboard shortcut (ctrl + shift + t)
- Add ability to swap between tabs with keyboard shortcuts (ctrl + page down / up)
- Add menus for color scheme, font size, font face of bash terminal,
- Add standard ubuntu shortcuts for copy and paste #235 
- Add customizable linux path in windows during install (`C:/Ubuntu` anyone?)
### Missing Performance Details

Perhaps outside the scope of a bug tracker, but another thing that would very clearly help win hearts and minds is real-world performance/benchmarking comparisons of server performance in VM'ed Ubuntu vs Bash on Ubuntu for Windows.

**Comment by fpqc** [comment]
@jlukic I mean, there are literally tons and tons of improvements I think that need to be made to the Windows Console, but right now at least, you can use rxvt-unicode-256colors with tmux (in mouse mode), which should give you a terminal with the functionality you want (I use shift+left/right to switch between tabs).  urxvt can be configured with the .Xdefaults file to do all that stuff you wanted.

**Comment by adeeb1** [comment]
+1 for multiple bash tabs; that's the most important feature I would like to have right now. I'm having an awesome time with Bash on Windows (it has replaced my Ubuntu virtual machine), but I'm missing tabs.

**Comment by lordgreg** [comment]
Please don't let us wait for another anniversary update for this things :(

**Comment by benhillis** [comment]
@lordgreg We will begin fighting new features and functionality via the Insider program.

**Comment by theg1nger** [comment]
Yes PLEASE add these functionality improvements. Much needed.

**Comment by jlukic** [comment]
@fpqc Can you explain what you mean by using `rxvt-unicode-256colors ` for now? Would love a work around, but I dont think I understand what you're suggesting.

**Comment by fpqc** [comment]
That's the package name for urxvt (the terminal emulator)

**Comment by hzhang-cl** [comment]
The [ConsoleZ](https://github.com/cbucher/console) wrapper allows you to use `bash.exe` inside it, however the arrow keys do not work for some reason.

**Comment by keton** [comment]
The [conemu](https://conemu.github.io) and [cmder](https://github.com/cmderdev/cmder) which is built around it has all those features plus some more and works nicely with Bash on Win10. Just let it `add default tasks` so Bash appears in new task menu.

**Comment by fpqc** [comment]
@keton not exactly, mouse support (and other esc sequence things) doesn't work.  Maximus will tell you himself why (the console wrapper does not send the ansi codes through to bash).

**Comment by bitcrazed** [comment]
Thanks for the discussion. 

> Note: 
> 1. Please post one issue per bug/ask - piling a ton of asks into one issue makes them very diffult to manage
> 1. Please don't duplicate existing asks

Closing this issue since:
1. Most of the asks in this issue have been delivered in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).
