### ISSUE TITLE
How to fix WslRegisterDistribution failed with error: 0x800106d9 ?

### ISSUE THREAD

**Issue by Hammaduddin561** [microsoft/WSL#7380]
### **_How to fix WslRegisterDistribution failed with error: 0x800106d9 ?_**

![Screenshot 2021-09-02 123408](https://user-images.githubusercontent.com/67366622/131798130-5cd9851f-f5a5-40db-af2b-a5a49ded9763.png)

### **_My windows specification :_**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎22/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

**_I have enabled the "Windows Subsystem for Linux" optional feature.
I hava enabled the 'Virtual Machine Platform' optional component
I have installed the wsl kernel
I have set WSL 2 as my default version
I tried Ubuntu20.04 , debain and kali, and then both encountered the same problem
I tried restarting and reinstalling, but the problem is still not solved_**

**Comment by benhillis** [comment]
Looks like EPT_S_NOT_REGISTERED, could you take a trace?

/logs
