### ISSUE TITLE
Cannot find direct download URL for Ubuntu (non-versioned) AppX

### ISSUE THREAD

**Issue by felipecrs** [microsoft/WSL#7381]
For solving https://github.com/microsoft/winget-pkgs/issues/26805, I need the URL where I can download the Ubuntu.appx (the non-versioned version) which is found at https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6.

I suppose this download URL exists already, as `wsl --install --distribution ubuntu` works.

**Comment by felipecrs** [comment]
It's possible to get the `appxbundle`s with https://store.rg-adguard.net/ by referring to https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6:

![image](https://user-images.githubusercontent.com/29582865/131865694-22d5e23c-9b87-4b01-986d-68573caa17b0.png)

But I cannot download such files in the regular download serves, as we need a direct link for integrating with WinGet.

**Comment by D3vil0p3r** [comment]
@felipecrs did you find a solution to your issue? I have the same issue (look the reference here above).

**Comment by felipecrs** [comment]
Not exactly the way I wanted but:

1. Winget can now install MS Store apps directly
2. wsl --install Ubuntu is simple enough
