### ISSUE TITLE
Can't run any linux distro

### ISSUE THREAD

**Issue by SquirrelOn0IQ** [microsoft/WSL#7385]
### Windows Build Number

10.0.19043.1165

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

Literally just start it.

### Expected Behavior

Allow me to set up my unix username and pass, then take me to a cmd line.

### Actual Behavior

It just says "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." I've tried everything man please help.

**Comment by blizzyblake278** [comment]
I've got the same issue as well that just happened. I cannot for the life of me figure out what is going on.

**Comment by CoskunSunali** [comment]
Possibly related to #7351
