### ISSUE TITLE
HDD not showing after WSL enabled

### ISSUE THREAD

**Issue by reconftw010101** [microsoft/WSL#7387]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1202]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

I just enabled wsl and installed ubuntu app from microsoft store.

### Expected Behavior

Everything has to works fine.

### Actual Behavior

Everything works fine but my laptop has ssd and hdd both my windows 10 installed in ssd after I installed and enabled WSL my hdd is not showing and I'm not able to access it. It says Disk Not initilized.

**Comment by benhillis** [comment]
Unclear what is going on here... does not appear to be a WSL issue.
