### ISSUE TITLE
conversion to wsl2 command not getting recognized

### ISSUE THREAD

**Issue by jdiazcr** [microsoft/WSL#7390]
### Windows Build Number

Windows 10 21H1 19043.1165

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 20.04 LTS

### Repro Steps

wsl --set-version Ubuntu-20.04 2 
wsl --set-default-version 2
wsl -set-default-version 2
wsl --help

Both in CMD or Powershell, result is the same
wsl_update_x64 package was installed and reinstalled, no difference
It was tried to be run before installing ubuntu, after installing ubuntu, makes no difference
Ubuntu machine runs fine, can modify files and be seen in windows explorer and vice-versa, however the command to transform is just not recognized, others as wsl -l -v are ok
![MicrosoftTeams-image](https://user-images.githubusercontent.com/90066537/132070260-f1d981a1-bf16-46a8-93a6-9b6e0bd6d1ec.png)

### Expected Behavior

command to be recognized and conversion to happen

![image](https://user-images.githubusercontent.com/90066537/132071959-cc3632dc-4f59-4f7e-9bdf-abb779fe3efc.png)

### Actual Behavior

when running wsl --set-version Ubuntu-20.04 2 to change wsl version from 1 to 2 or when running --set-default-version to set all future instances to WSL2, the output is list of parameters possible as if using the --help switch

### Diagnostic Logs

[lxcore_service.txt](https://github.com/microsoft/WSL/files/7108803/lxcore_service.txt)

**Comment by ratheesh98** [comment]
@jdiazcr  This may help. https://github.com/microsoft/WSL/issues/7369#issuecomment-908426418
