### ISSUE TITLE
Stuck on the first step in my setting up

### ISSUE THREAD

**Issue by Des9938** [microsoft/WSL#7401]
I was instructed by my professors at school that before installing any Linux distros for WSL, enable the "Windows Subsystem for Linux" feature, to do this by opening PowerShell as administrator (type PowerShell into the search bar, right-click Windows PowerShell, and then click Run as administrator) and run this command:
**Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-WindowsSubsystem-Linux**
But when I run this command, I get this error message: 
Enable-WindowsOptionalFeature : Feature name Microsoft-WindowsSubsystem-Linux is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-WindowsS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
Am I doing something wrong? Do I perhaps need to download something, or alter any settings?

**Comment by owenschupp** [comment]
Hello, if this continues to be an issue, please resubmit with the issue template provided. Since it seems like the problem is in your installation, please follow the steps [here.](aka.ms/wslinstall)
