### ISSUE TITLE
"reason: Address already in use" all time in workspace wls2

### ISSUE THREAD

**Issue by Lineez** [microsoft/WSL#7402]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Visual studio code

### Repro Steps

don't know
if i can help write me

sry for my eng

### Expected Behavior

it worked

### Actual Behavior

it work for me last week, but today 06.09.21 i run "yarn dev" if my pc was loaded and all time i have a message
[Mon Sep  6 20:09:59 2021] Failed to listen on 127.0.0.1:8000 (reason: Address already in use)

i trying "lsof -i :8000" this return
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    22276 lineez   25u  IPv4  70349      0t0  TCP localhost:8000 (LISTEN)

if i try in workspace "kill -9 22276" it close my connect to wsl
if i try with out workspace "kill -9 22276" port closed? (i don't know) and i can run "yarn dev"

**Comment by benhillis** [comment]
I'd suggest using a different port, looks like node is already using that one.

**Comment by Lineez** [comment]
It sometimes happens if wls started in workspace. Now it work, but i didn't do anything. I have not ideas why it happens. Thanks for answer
