### ISSUE TITLE
Mongodb cluster is not able to connect from WSL2 windows terminal

### ISSUE THREAD

**Issue by khushal123** [microsoft/WSL#7411]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.928]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

NodeJS v14.17.6
"mongoose": "^5.9.4"

### Repro Steps

I am trying to connect to the MongoDB cluster via mongoose. It is not working from wsl2.
Connection:
```
const uri = 'mongodb+srv://user:password@cluster.mongodb.net/flydb?retryWrites=true&w=majority';


mongoose.connect(uri, {
    useUnifiedTopology: true,
}).then((o) => {
    console.log(o)
}).catch(e => {
    console.log(e)
})

```

### Expected Behavior

It should connect to MongoDB cluster. It was working perfectly in wsl1.

### Actual Behavior

I get this message

`querySrv ETIMEOUT _mongodb._tcp.cluster0.46q3p.mongodb.net`
It works for time being after I restart the computer. But after 10 minutes again same error happens.

### Diagnostic Logs

```
Error: querySrv ETIMEOUT _mongodb._tcp.<clustername>.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:206:19) {
  errno: undefined,
  code: 'ETIMEOUT',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.<clustername>.mongodb.net'
}
```

**Comment by emmekappa** [comment]
having the same issue

**Comment by gaia** [comment]
> This issue is still open @gaia

I think you tagged the wrong guy :)

**Comment by RaviMauryaHootowl** [comment]
Same issue here :(

**Comment by joaoschneider** [comment]
Facing same issue here when trying to connect to a Mongo Atlas cluster from a Node application running on WSL2 environment.

It seems to be related to Node + WSL2, as I can connect to the cluster via `mongosh`, but can't when trying to connect to the cluster via a Node app. 

Changing WSL version to 1 is a workaround:
```bash
wsl --set-version <DistroName> 1 
```

**Comment by RaviMauryaHootowl** [comment]
For me, upgrading to Windows 11, solved the issue. Still not sure about the cause of the issue.

**Comment by nolbuDev** [comment]
I have same the issue.
My environment is wsl2, window11, ubuntu20.04.4.
Thank @joaoschneider for your solution.
On wsl1, it works

**Comment by ah2k-dev** [comment]
Having same issue. MongoDB connects with the uri for node 2.2.12 but I am not able to access data with it.  I don't want to use wsl1. Any fixes would be appreciated.

**Comment by joaoschneider** [comment]
We found another workaround that may be useful. In our case, we were attempting connection with a connection string that contained the `-pri` suffix (apparently it was generated via the `Private IP for peering` option under `Connect` on Mongo Atlas). 

Using the string generated by `Connect -> Standard Connection` or Node.js 4.0 or later driver, which does not contain the `-pri` suffix, fixed the WSL2 + Node connection issue.

Hope it helps.

**Comment by angelplusultra** [comment]
Is downgrading to WSL 1 the only workaround for this issue at this point?

**Comment by khushal123** [comment]
I feel like the solution is in the proper networking. I don't think the documentation elaborates on this part. 
The issue is gone for me now I am using localhostforwarding=true in .wslconfig.

**Comment by khushal123** [comment]
Closing this issue since it is solved.
