### ISSUE TITLE
Folder created from File Explorer has the root owner after I installed a WSL2 distro in Windows 11

### ISSUE THREAD

**Issue by floating-cat** [microsoft/WSL#7412]
Microsoft Windows [Version 10.0.22000.176]

Steps:
1. Install a **new** WSL2 distro in Windows 11 (don't restart the Windows after installing the WSL2 distro)
2. Open this distro Terminal to start it.
3. Open Window File Explorer, click Linux entry on the left, then go to this Linux distro's home folder.
4. Right-click to create an empty folder.
5. Run `ls -al` in WSL2 distro Terminal.

This issue seems to occur after you installed a WSL2 distro without restart the system. You need to install a new WSL2 distro to reproduce it. (reproduced in the Ubuntu 18 and Debian)

Result:
The newly created folder is root owner.
If I use `mkdir` to create a folder, the owner is correct (the current user).
(new_created_folder is the file I created from File Explorer)
![image](https://user-images.githubusercontent.com/6748077/132463652-e559e378-b825-4154-aea5-17807a629689.png)

Expected:
The folder's owner is not the root, but the current Linux user.
Use the command (`wsl --terminate` or `wsl --shutdown`) to restart the WSL looks help too.

Already attached log in Feedback Hub.

**Comment by giggio** [comment]
I just tried the repro steps and could reproduce the bug. I'm on Windows 11, Version `10.0.22000.978`. All updates are installed, using the latest Linux kernel available officially to wsl.
And yes, `wsl --shutdown` fixes the problem without needing to restart Windows.
