### ISSUE TITLE
issue with printing characters in conhost

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#7415]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1202]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

20.04.3

### Other Software

bash
conhost

### Repro Steps

cat /dev/urandom

### Expected Behavior

This should print characters eternally into the console. Some of them will not render correctly but it should constantly scroll.

### Actual Behavior

The printing halts after a certain point and this error is returned:

cat: write error: Input/output error

**Comment by benhillis** [comment]
My understanding is that this is by-design since you are writing random bytes to the console, which are being interpreted as VT100 sequences.  Adding @DHowett to keep me honest.
