### ISSUE TITLE
apt update && apt upgrade weird behaviour

### ISSUE THREAD

**Issue by Zubair373** [microsoft/WSL#7417]
apt update && apt upgrade
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
BUT when i run it with root, it works properly?

**Comment by Biswa96** [comment]
Many answers are here https://duckduckgo.com/?q=Could+not+open+lock+file+%2Fvar%2Flib%2Fapt%2Flists%2Flock&ia=web
