### ISSUE TITLE
Unable to use while using chinese system

### ISSUE THREAD

**Issue by rsj123** [microsoft/WSL#7419]
### Windows Build Number

Microsoft Windows [版本 10.0.20348.169]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

While using some command such as:
```
wsl --set-default-version 2
wsl --date
```
It will print help in Chinese, I think it might a translate problem.

### Expected Behavior

Work well

### Actual Behavior

![Pic1](https://user-images.githubusercontent.com/16500070/132954071-2c3a88d4-6f02-4c0e-ac5f-f863e0847104.png)
![Pic2](https://user-images.githubusercontent.com/16500070/132954074-730813de-0c5f-40ae-9805-9732dc856a46.png)

**Comment by KotoriK** [comment]
not a language pack issue
see #7332

**Comment by rsj123** [comment]
> not a language pack issue see #7332

Thanks for ur reply.
Updated to windows11 and solved.
:)
