### ISSUE TITLE
Incorrect render after minimize and restore

### ISSUE THREAD

**Issue by pqvst** [Microsoft/WSL#742]
When using tmux, the pane lines disappear after minimizing and restoring the command prompt window. I would expect the lines to remain. The workaround at the moment is to restart tmux. I'm not sure if this affects other programs as well.

Steps to reproduce:
1. `tmux`
2. ctrl+b, %
3. Minimize window
4. Restore window

Before:
![before](https://cloud.githubusercontent.com/assets/4990657/17376767/4a2682a0-59b7-11e6-8ed3-d25677db7242.png)

After:
![after](https://cloud.githubusercontent.com/assets/4990657/17376759/440f7714-59b7-11e6-8f65-890e7a3b4910.png)

Version 1607 (OS Build 14393.10)

**Comment by fpqc** [comment]
Other workaround is to use a better terminal like rxvt and an X server (or another solution is PuTTY + ssh, which is a little bit harder to set up working on startup, imo).  Here's a link to some instructions: https://github.com/Microsoft/BashOnWindows/issues/741#issuecomment-237325357

**Comment by zadjii-msft** [comment]
I do see that minimizing and restoring the console does corrupt tmux a bit (it places the cursor after any output which shifts the entire tmux display up by one).
Though, by default, C-r should redraw tmux, and looks to me like it fixes the issue for me. (it may be remapped in your .tmux.conf)

@pqvst Which font are you using? I've noticed another tmux pane separator bug that seems to be connected to the selected font, but more data would help me pin it down.

**Comment by pqvst** [comment]
Ah, thanks for the C-r tip @zadjii-msft. I'm using Consolas. I tried switching to Courier New, but same problem there.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue has been fixed since it was originally posted
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by wieczoreko** [comment]
@bitcrazed 
sorry for getting this old pr up but the issue in the console repo is still open and not solved.
You said it has been fixed? If yes can you tell me how?
Thanks in regards

**Comment by zadjii-msft** [comment]
TBH I don't think this one was ever solved - I think Rich was just copy-pasting and bulk moving old issues from this repo.

If you have a current repro, I'm happy to help investigate over at the Console repo.
