### ISSUE TITLE
the network of wsl2 does not work

### ISSUE THREAD

**Issue by Angel0726** [microsoft/WSL#7421]
![image](https://user-images.githubusercontent.com/32816780/133019014-20ae2fe8-ccfe-4ca6-a7f8-03bfa398ae3f.png)

version: ubuntu20.04
when I use wsl1 the network is working; but when I update the wsl1 to the wsl2, the network does not work。

**Comment by RickRoss101** [comment]
same problem overhere! I used Windows Terminal and Debian yesterday evening. Today, Windows Terminal does not open up debian. Its a weird behavior...

**Comment by craigloewen-msft** [comment]
@Angel0726 could you please reopen this with the full issue template filled out? That will help us resolve your issue.

As well, are you using any VPNs?
