### ISSUE TITLE
WSL crashes when operating with GitKraken

### ISSUE THREAD

**Issue by f-liva** [microsoft/WSL#7422]
### Windows Build Number

10.0.22454.1000

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Debian 11

### Other Software

Docker Desktop (Windows), version 4.0.0
PhpStorm (Windows), version 2021.2.1
GitKraken (Debian), version 7.7.2

### Repro Steps

1. Place a big git repo within your WSL distro
2. Stash/push/commit/checkout brenches with GitKraken running from WSL distro
3. Wait until WSL crash, GitKraken crash, Docker Desktop crash
4. If not, try another intensive Git operation

### Expected Behavior

No crashes

### Actual Behavior

Crashes

**Comment by f-liva** [comment]
I start recording crashes as they occur.

Here the first one: https://aka.ms/AAdtvug

**Comment by f-liva** [comment]
How to find that information?

**Comment by benhillis** [comment]
`cat /proc/version`

**Comment by f-liva** [comment]
Linux version 5.10.43.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Jun 16 23:47:55 UTC 2021

**Comment by f-liva** [comment]
Dear

How will I proceed with the update once it is released? Through Windows Update regularly?

**Comment by benhillis** [comment]
Correct.
