### ISSUE TITLE
`cd` in .bashrc Overrides `wsl --cd` launch argument from Windows

### ISSUE THREAD

**Issue by Chiramisu** [microsoft/WSL#7424]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Launch WSL.
2. Add `cd ~` to your `.bashrc` file.
3. Close WSL.
4. Browse to some folder on your local disk. For Example: `C:\` (backslash important).
5. <kbd>Shift</kbd> + <kbd>Right-Click</kbd> the folder.
6. Select 'Open Linux shell here' from the context menu.
7. WSL launches at `~` as defined in `.bashrc` rather than the folder specified in the context menu in Windows.

**Note**: Steps 4-6 can be replaced by running the following from PowerShell: `wsl --cd C:\`

### Expected Behavior

WSL should open at the directory specified by the context of it's invocation / launch, rather than being overridden by the `.bashrc` file. In other words, the `--cd` argument should always be honored.

I might suggest that this argument should be processed by WSL **AFTER** the login process has run its course, including loading the `.profile`, `.bash_profile`, and `.bashrc` files. Only then, should WSL process the `--cd` argument passed in by Windows.

### Actual Behavior

WSL incorrectly launches at the last-most directory specified by any `cd` command specified in the login files, thereby entirely ignoring the `--cd` argument passed in from the `wsl` launch command in Windows.

I've experienced this issue for years and have searched through all the Linux, Bash, and WSL documentations, as well as developer and Microsoft blogs, and even reached out to the WSL team on [Twitter](https://twitter.com/Chiramisuu/status/1433877641635852292). I have found no solution to this problem.

**Comment by Biswa96** [comment]
Isn't your "Actual Behavior" the "Expected" one? The `--cd` argument changes directory with chdir(2) in `init` process. Then init fork and exec bash. bash then reads `.bashrc` and changes directory again. So, the last working directory is determined by `.bashrc`.

**Comment by owenschupp** [comment]
While I see your point, this is the expected behavior when using `.bashrc`, as explained in the comment above. The best solution would to be to remove the `cd` command from your `.bashrc`.
