### ISSUE TITLE
`set` command error in *zsh* on Ubuntu 20.04, wsl2

### ISSUE THREAD

**Issue by HUGHNew** [microsoft/WSL#7427]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

# Q1
no info about `set --help` in my **zsh** on Ubuntu 20.04, wsl2. 

However it show me the help doc if I switch to **bash**. So there is something wrong with wsl2 or zsh?
What's more, I try this command, `set --help`, in Alpine, and it works.

```bash
[11:31:12] In [/home/hugh]
λ > set --help
[11:31:19] In [/home/hugh]
λ > echo $SHELL
/usr/bin/zsh
[11:30:33] In [/home/hugh]
λ > bash
hugh:~
$ set --help
set: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    Set or unset values of shell options and positional parameters.
...
    Returns success unless an invalid option is given.
hugh:~
$ exit
exit
```
# Q2

Otherwise, the command, `set -e`, behaved unexpectedly.

```bash
[11:41:42] In [/home/hugh]
λ > set -e
[11:41:43] In [/home/hugh]
λ > e
[process exited with code 1]
```
After `set -e` typed, I input `e`. No matter I press any key then, it exited with code 1 without any error message.

### Expected Behavior

The same result as it does on **bash**

![image](https://user-images.githubusercontent.com/52786639/133550607-9b0cf3ca-7454-427a-9526-446ece592044.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/52786639/133546313-2ad98e55-07ca-46a7-8a14-b2b771713a1d.png)

**Comment by elsaco** [comment]
For zsh use "run-help set". All zsh help topics are in "/usr/share/zsh/help". This is a shell feature not a bug!

**Comment by HUGHNew** [comment]
Thanks, I didn't know this before
