### ISSUE TITLE
WSL2 Consumes more than half of system memory

### ISSUE THREAD

**Issue by thisismydesign** [microsoft/WSL#7429]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1202]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.128

### Distro Version

Ubuntu-18.04

### Repro Steps

I have 16GB RAM, running projects in Docker that take up a lot of memory apparently. The memory usage is often through the roof and makes the system unstable. Supposedly this should be limited to 50% of system memory: https://github.com/microsoft/WSL/issues/4166#issuecomment-662705705

![limited memory](https://user-images.githubusercontent.com/3299948/133615652-6761fb01-6a51-4164-a4c1-f9133f9a6b02.PNG)

I have no `.wslconfig`

### Expected Behavior

Vmmem process doesn't use more than 50% of system memory.

### Actual Behavior

Vmmem process uses all memory.

**Comment by 0xbadfca11** [comment]
> 10.0.**19043**.1202

> In build **20175** we've changed the default memory scheme in WSL 2 to use 50% of your memory in Windows, or 8GB (whichever is smaller).

19043 < 20175

This change hasn't come to Windows 10 stable release.

**Comment by thisismydesign** [comment]
I see, thanks
