### ISSUE TITLE
File or directory damaged or unreadable when launching linux distro

### ISSUE THREAD

**Issue by Kulgar** [microsoft/WSL#7433]
### Windows Build Number

Microsoft Windows [version 10.0.19043.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 18.04

### Other Software

N.A.

### Repro Steps

The launch of my Ubuntu 18.04 VM just stopped working. 
It was working perfectly fine yesterday. 

The error message I get is: 
File or directory is damaged and unreadable 
[process ended with code 4294967295]

I wonder if it stopped working because of a windows update I did recently.
Also, I really don't know what could have corrupted the vhdx file... 

### Expected Behavior

I just want the VM to launch again... thanks in advance if you have any idea on how I can repair my VM... 

### Actual Behavior

Getting the error message 

File or directory is damaged and unreadable 
[process ended with code 4294967295]

I am able to mount the ext4.vhdx file from another Ubuntu VM. I am actually extracting all the files I can to get my environment back... But I'd prefer being able to repair my existing VM. 

### Diagnostic Logs

Let me know if I can provide you with any relevant logs.

**Comment by Kulgar** [comment]
Well... I reinstalled another distribution (Ubuntu 20) and got all my files back. 
But today, WSL 2 is having the same bug again... It all started with the same problem as in this issue: https://github.com/microsoft/WSL/issues/6220

I run the adviced fix "sudo e2fsck /dev/sdd -p", and it does find problems that it can "fix". But then the distrib doesn't even start with the error above (file or directory unreadable). So I guess the e2fsck command is doing more harm than good... I'm guessing this is all due to the recent Windows update I did as I never got these problems before (but I had others...)...

I'm sorry but I'm sick of all these issues... I already lost several days of work because of them... I'm going back to VMWare...

**Comment by mixxen** [comment]
@Kulgar, how did you get all your files back? I'm seeing the same error:

The file or directory is corrupted and unreadable.
Press any key to continue...

[process exited with code 4294967295]

Any advice is appreciated. Thanks.

**Comment by Kulgar** [comment]
@mixxen I mounted the corrupted WSL 2 virtual disk on another fresh WSL 2 install and extracted the files from there... Do you know how to do that?

**Comment by mixxen** [comment]
@Kulgar, thanks for the advice. I see that my ext4.vhdx file is 0kb. I'm pretty sure that chkdsk corrupted the virtual disk file and everything is lost. I had to start from scratch...I'll be sure the backup the vhdx file regularly from now on.

**Comment by Kulgar** [comment]
ow, shit... I didn't have this problem, my ext4 wasn't 0 Ko, it was more sth like 30 Go...
What a shame that you lost everything. I would have gone pretty mad if that happened to me :-/

**Comment by Xirzag** [comment]
Also the same. I notice that when Windows was starting it was fixing the C partition, so I think it saw somthing like ext4 and delete it.
Another great day in the windows enviorement

**Comment by stevenlafl** [comment]
Same. Complete garbage sometimes. All my work project files that I didn't save into a repository are gone. Thankfully I put important stuff on the cloud.

**Comment by SBKK** [comment]
@Kulgar how to mount the corrupted WSL 2 virtual disk?
