### ISSUE TITLE
WSL2 Network problem not working ~ Trying to fix since 2 days. shit couldn't get it

### ISSUE THREAD

**Issue by MahbbRah** [microsoft/WSL#7434]
### Windows Build Number

19043.1165

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-18.04

### Other Software

Nothing installed yet now.. it's just a fresh one.

### Repro Steps

I have just installed WSL and Ubuntu 18.04  that's it

After installation is done it doesn't work networking.  I can't install packages or anything. 

### Expected Behavior

Because it's just a fresh setup, I was expecting everything to work out of the box including the network

### Actual Behavior

When I tried to use the internet throughout my WSL2 Ubuntu setup it just doesn't work

suppose when I do `sudo apt-get install PACKAGE` it retrieve package details. but then can't do the download and stack like this

![image](https://user-images.githubusercontent.com/10045253/133853153-86988ea4-f0c2-43a4-8807-88846656cbf9.png)
and when it happens my network on windows also doesn't work, I mean when I'm trying to use the internet inside the WSL box my local Windows internet also seems gone.. I'm using the internet through a WIFI network.

### Diagnostic Logs

I have tried to get this done for the last few days. managed to waste enough hours but still, it seems doesn't work. 

Tried few configs from people here who facing similar issues but doesn't work at all.

Tried things
# I haven't had enabled Hyper-V, then enable it and did network bridging with `VETHERNET WSL2`  with my wifi network, didn't work.

#I checked that the virtual Adapter that trying to use the internet has different IP address series than the one I have on my local windows.
#I tried a few more stuff it didn't work at all

NOTE; When I do make my mobile phone a hotspot and then connect it through WIFI it works. but my regular router's internet doesn't work

network details FROM WSL2 Ubuntu
![image](https://user-images.githubusercontent.com/10045253/133853898-083b7136-9e06-40c3-96dd-02d8d4d752d6.png)
![image](https://user-images.githubusercontent.com/10045253/133854138-19bb5673-c80e-42ff-ad3d-f66835fea280.png)
This config below assigns automatically, by selecting obtain IP automatically, it still doesn't work
![image](https://user-images.githubusercontent.com/10045253/133854241-ed2941fd-4122-4d1d-9d6b-154d876bb2a0.png)

details from windows
![image](https://user-images.githubusercontent.com/10045253/133854013-8f654a97-261e-414b-a85c-56a0ef56742e.png)

at this moment I'm super stack with this issue. Can't get it to work. countless hours have been wasted and messing my head.

**Comment by ivanandresdiaz** [comment]
Me too

**Comment by emilioaray-dev** [comment]
I try to stay in windows as a developer, but they insist this is a disaster.

After a fresh install wsl2 totally useless. There is no way to at least do apt-get update

**Comment by MahbbRah** [comment]
> 
> 
> I try to stay in windows as a developer, but they insist this is a disaster.
> 
> After a fresh install wsl2 totally useless. There is no way to at least do apt-get update

Same here.. I might need to switch to Linux based system again. as it's not working at all.

**Comment by amouhzi** [comment]
Check your antivirus. I had the same problem, I solved it by uninstalling the antivirus. (Note: it is recommended to have an antivirus).

**Comment by MahbbRah** [comment]
> 
> 
> Check your antivirus. I had the same problem, I solved it by uninstalling the antivirus. (Note: it is recommended to have an antivirus).

The one I have is Windows defender, disabled all the security and then tried again, seems to have no result. it's not that easy thing I guess.

**Comment by Dariusz1989** [comment]
I cant make it work either.
I'm new to linux/wsl and this is pure bananase. 
I've got literally 0 idea how to fix it & every post/forum I follow does not solve the issue. Nice one MS nice one.
