### ISSUE TITLE
Enable kernel headers for eBPF tools.

### ISSUE THREAD

**Issue by chadbrewbaker** [microsoft/WSL#7437]
**Is your feature request related to a problem? Please describe.**
Kernel headers are turned off  Microsoft/config-wsl which barfs eBPF tracing tools:
```bash
# CONFIG_IKHEADERS is not set
```
should be

```bash
CONFIG_IKHEADERS=y
```

**Describe the solution you'd like**
Enable the flag so [Prodfiler](https://www.prodfiler.com) and bccutils work.

**Describe alternatives you've considered**
You can build your own kernel, but this should be a default for non-technical users.

**Additional context**
I tested on https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.43.3 and it seems to work.

@tyhicks if you were doing a build for Linux Plumbers Conf next week, please include this :)

**Comment by benhillis** [comment]
Thanks for the suggestion, taking a look at adding this.

**Comment by chadbrewbaker** [comment]
I should probably create another ticket, but your releases could also include the perf binary pinned to Microsoft's WSL2 kernel build. I know WSL2 hasn't exposed all the hardware counters yet - but at least you wouldn't have to build from source yourself, and there would be eyeballs on missing features.

**Comment by arcamelo** [comment]
perf probably was the first tool to link with libbpf, for 'perf trace', nowadays, besides that, it also uses BPF skels, as mentioned in my talk.
Also perf's version doesn't need to be the same as the kernel it runs on, fallbacks happen when using a new perf on an older kernel and older tools also should work on newer kernels, when possible (matching requested features from tool/kernel features).

**Comment by chadbrewbaker** [comment]
@arcamelo can you point me to the list of kernel config settings that the latest perf needs? I didn't see it when browsing the docs: https://github.com/torvalds/linux/tree/master/tools/perf/Documentation

**Comment by tyhicks** [comment]
@chadbrewbaker does it make more sense to enable CONFIG_DEBUG_INFO_BTF, instead of using the kernel headers provided by CONFIG_IKHEADERS, as mentioned in [this blog post](https://www.brendangregg.com/blog/2020-11-04/bpf-co-re-btf-libbpf.html)?

**Comment by tyhicks** [comment]
We've enabled BTF support in [5.10.74.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.74.3).
