### ISSUE TITLE
Windows 11 destroys WHPX on Ryzen processors

### ISSUE THREAD

**Issue by aTerminal** [microsoft/WSL#7438]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Debian 11

### Other Software

Android Studio 4.2.2
Build #AI-202.7660.26.42.7486908, built on June 24, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

### Repro Steps

1. Install WSL 2, and activate Windows Hypervisor Platform
2. Install Android Studio, and starting an Android Virtual Device

### Expected Behavior

Android Virtual Device should be started normally

### Actual Behavior

The emulator process returned:

C:\Users\myfolder\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: WHPX: Failed to setup partition, hr=c0350005
C:\Users\myfolder\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: failed to initialize WHPX: Invalid argument

### Diagnostic Logs

Executed commandline:
PS C:\Users\myfolder\AppData\Local\Android\Sdk\emulator> .\emulator.exe -netdelay none -netspeed full -studio-params C:\Users\myfolder\temp\emu7.tmp -avd Nexus_5X_API_28
emulator: Android emulator version 30.7.5.0 (build_id 7491168) (CL:N/A)
handleCpuAcceleration: feature check for hvf
added library vulkan-1.dll
Failed to open /qemu.conf, err: 2
C:\Users\myfolder\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: WHPX: Failed to setup partition, hr=c0350005
C:\Users\myfolder\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: failed to initialize WHPX: Invalid argument

**Comment by benhillis** [comment]
The default hypervisor used by Android Studio is not compatible with Hyper-V.
https://devblogs.microsoft.com/visualstudio/hyper-v-android-emulator-support/

**Comment by aTerminal** [comment]
> The default hypervisor used by Android Studio is not compatible with Hyper-V.
> https://devblogs.microsoft.com/visualstudio/hyper-v-android-emulator-support/

According to the Android Developer official site [Configure VM acceleration on Windows](https://developer.android.com/studio/run/emulator-acceleration#vm-windows) ,I can use the Android Studio Emulator in WHPX mode to compatible with Hyper-V. If I understand correctly, WHPX is the solution to the incompatibility problem, and I used WHPX in this run.

**Comment by Jictyvoo** [comment]
I have the same problem on Windows 11, can't use both WSL 2 and Android Studio Emulators. The emulator only works if I disable Virtual Machine Platform, but in this way WSL 2 can't work

**Comment by aTerminal** [comment]
> The default hypervisor used by Android Studio is not compatible with Hyper-V. https://devblogs.microsoft.com/visualstudio/hyper-v-android-emulator-support/

Please consider re-opening this issue. There are many people mention this bug in this issue.

**Comment by kypeli** [comment]
Also as per the comment in the Android issue tracker: this is not only AMD Ryzen related, but issue can be reproduced at least on Intel i7 also.

**Comment by mgood7123** [comment]
any fix ?
