### ISSUE TITLE
Kernel update 5.10.43.3 does not show.

### ISSUE THREAD

**Issue by 1Nick1Name** [microsoft/WSL#7439]
### Windows Build Number

10.0.19043.1237

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu-20.04

### Repro Steps

`wsl --shutdown`
`wsl --update`

### Expected Behavior

Kernel updating to 5.10.43.3

### Actual Behavior

Output is:

Checking for updates...
No updates are available.
Kernel version: 5.10.16

**Comment by 0xbadfca11** [comment]
That is only release for Prerelease (=Insider Preview).
https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes
