### ISSUE TITLE
Entering python's virtual environment results in all the letters to be changed into gibberish

### ISSUE THREAD

**Issue by ashrasmun** [microsoft/WSL#7440]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

1. Add this line to your `.bashrc`:
`export PS1="\[\e[1;30m\]\w\[\e[0m\] > "`
That's my modified prompt, which should just show the path in gray.

2. Create python's virtual environment on your hard drive. (virtualenv)
3. Activate it.

### Expected Behavior

Entering virtual environment should make all the letters go berserk. Example of how it should look after entering virtual environment: 
![image](https://user-images.githubusercontent.com/12000269/134046487-6bd1b30a-796f-432b-87e8-e6b159fcd6da.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/12000269/134046557-4a3780ec-ef72-4fbe-aade-d6102b2449ee.png)
![image](https://user-images.githubusercontent.com/12000269/134046569-27d3afa0-4cf7-42bd-aaff-2fb871b83066.png)
Right after sourcing the activate script, WSL changed all my letters into incomprehensible mess.  In Command Prompt the issue persists even after quitting WSL. 
![image](https://user-images.githubusercontent.com/12000269/134046721-a40cf59c-f847-45fd-9380-39c3efc7f438.png)
In command prompt opened from outside Windows Terminal the problem is... different. I cannot input newlines and I'm writing from the beginning of the line. I can however exit WSL and access it again in the same session, which is cool.

I found out that ConEmu has the least problems, as the only problem is with the string inside parentheses, which should express the name of virtual environment i'm in. New lines work and even though it looks ugly, it's usable.
![image](https://user-images.githubusercontent.com/12000269/134047473-23fb2e90-cedd-48e0-b60e-ac3118ba7ed4.png)

**Comment by craigloewen-msft** [comment]
Hmm I'm not able to reproduce this behaviour on Windows 11 build 220000

![image](https://user-images.githubusercontent.com/42221804/134215326-e7b581d4-21a5-4ad4-9e16-278c9f8e6ffe.png)

Are you able to try this same workflow on a Windows 11 machine? Or are there any other steps here to help reproduce this?

**Comment by ashrasmun** [comment]
Hey @craigloewen-msft ! I have no access to Windows 11 machine **but** I found the scenario in which I get the same output as you do. 
![image](https://user-images.githubusercontent.com/12000269/134380222-080d0ef1-310f-433b-8832-2763f064f22c.png)

To my understanding, I'm wrongly using WSL. As far as I understand, the virtual environment that you created was created in WSL after `sudo apt install python3-virtualenv`, right? My "mistake" was that I created the virtual environment using Windows and then activated it in WSL - please notice that I wrote `source env/Scripts/activate` instead of `source env/bin/activate`. I cannot really tell if it's an issue with WSL or me 😊 so I'll just let you decide, how about that.

**Comment by WSLUser** [comment]
This is a Windows Terminal issue.  Per the WSL README, all console issues should be filed there. https://github.com/microsoft/terminal They can probably help you identify the issue with your bash prompt setting.

**Comment by ashrasmun** [comment]
Hm, but this issue could also be reproduced on good old Windows Command Prompt and in some emulators... I'll report it to "terminal" team then, thanks :)
