### ISSUE TITLE
Docker Hangs Up  & Stays Stuck on "Downloading Fs" on "Docker-Compose Up" WSL 

### ISSUE THREAD

**Issue by jackie1santana** [microsoft/WSL#7442]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Every time I run ` docker-compose up` in an application, the images start to pull and then midway, one of the images get stuck and it says waiting or retry for what it seems like forever. Then  I'll get a few errors

### Expected Behavior

N/A

### Actual Behavior

`ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

`Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.65.5:53: read udp 192.168.65.4:33122->192.168.65.5:53: i/o timeout`

I don't understand.. I've changed my `resolv.conf dns name server to 8.8.8.8 & 8.8.4.4` & it still doesn't work.
I've disabled hyper -V and turned it back on. Still nothing.

Btw I am using a company computer, so I don't know if that is the issue but it exhibits the same behavior whether I have the VPN on or off.

Can anyone help?

**Comment by craigloewen-msft** [comment]
Are you using a VPN? 
From a WSL instance are you able to access the network at all? (Can you run `sudo apt update`)?

**Comment by jackie1santana** [comment]
> Are you using a VPN?
> From a WSL instance are you able to access the network at all? (Can you run `sudo apt update`)?

I figured it out. My companies McAffee security system were blocking the docker ports. I uninstall McAffee & now it works !
