### ISSUE TITLE
@benayat please open issue at my repo. I did not try to use wifi interface.

### ISSUE THREAD

**Issue by benayat** [microsoft/WSL#7447]
@benayat please open issue at my repo. I did not try to use wifi interface.
If i understand you correctly - you bridged wsl switch to WiFi adapter and would like to do same on linux side? 

_Originally posted by @pawelgnatowski in https://github.com/microsoft/WSL/issues/4150#issuecomment-924196851_

Exactly that.
 could that be possible?
In the end, in the wsl terminal/ifconfig, instead of the eth0 network, I'd like it to show as a wifi network,with the iwconfig command. Since I'm no expert,any lead/idea will be appreciated.

**Comment by pawelgnatowski** [comment]
> @benayat please open issue at my repo. I did not try to use wifi interface.
> If i understand you correctly - you bridged wsl switch to WiFi adapter and would like to do same on linux side? 
> 
> _Originally posted by @pawelgnatowski in https://github.com/microsoft/WSL/issues/4150#issuecomment-924196851_
> 
> Exactly that.
>  could that be possible?
> In the end, in the wsl terminal/ifconfig, instead of the eth0 network, I'd like it to show as a wifi network,with the iwconfig command. Since I'm no expert,any lead/idea will be appreciated.

Not sure really as i never used wifi on linux myself. What do you plan to accomplish by hooking it to virtual wifi interface anyway, if i may ask?

If just to use host wifi then all you need is just to brigde wsl network to the host wifi and linux side would be same.
