### ISSUE TITLE
wsl.exe --list prints help page when WSL is disabled

### ISSUE THREAD

**Issue by segrey** [microsoft/WSL#7448]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1237]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

WSL is disabled in Windows features

### Distro Version

None, WSL is disabled in Windows features

### Repro Steps

Disable "Windows Subsystem for Linux" in "Turn Windows features on or off" and, if needed, restart the system to apply changes.
`wsl.exe --list` prints
```
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument]

Arguments:

    --install <Options>
        Install Windows Subsystem for Linux features. If no options are specified,
        the recommended features will be installed along with the default distribution.

        To view the default distribution as well as a list of other valid distributions,
        use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Specifies the distribution to be downloaded and installed by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --list, -l [Options]
        Lists distributions.

        Options:
            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --help
        Display usage information.
```

### Expected Behavior

Would be great if it would output 0 distributions in the same format as it does when "Windows Subsystem for Linux" is enabled. This will allow 3rd party tools parsing `wsl.exe --list --verbose` or `wsl.exe --list --quiet` to work as expected.

### Actual Behavior

`wsl.exe --list` prints the help page

**Comment by benhillis** [comment]
Good call, I'll make this change.

**Comment by benhillis** [comment]
Unfortunately changing this behavior will break people who are already parsing this output, for example the Windows Terminal.

**Comment by segrey** [comment]
Do you mean that printing an empty distribution list in default format (i.e. when "Windows Subsystem for Linux" is enabled) will break Windows Terminal?

**Comment by rentalhost** [comment]
So, there is none solution until now? Maybe create a new flag so it can reports none?

Eg. `wsl --list --verbose --force`
