### ISSUE TITLE
Windows 10 file access to WSL2 stops working after 1 to 3 days

### ISSUE THREAD

**Issue by mlawdawg** [microsoft/WSL#7450]
Windows 10   Version	10.0.19042 Build 19042
WSL2:     Default Distribution: Ubuntu-20.04          Default Version: 2

I use wsl2 for development.  My source files are in wsl2 and I use Windows 10 apps to edit, search the source.  Everything works for 1 - 3 days.  Then, windows file access to wsl2 stops working; both using \\wsl$\Ubuntu-20.04 or using a mapped network drive letter.  The fix is closing all my Ubuntu-20.04 terminal windows, then in a windows powershell I run "wsl --shutdown".  Note, when the problem is present the "wsl --shutdown" takes 10-20 secs.  When the issue is not present, it takes only 2-3 secs.

My windows file access is fairly large, at times, when in my windows 10 app I rebuild it's source "tag" dbase over the 30k + files in my project.  That alone, or doing it a few times on different projects of that size, doesn't immediately cause the issue though.

**Comment by arafatx** [comment]
Well, if you use ubuntu, I can recommend the best is to use multipass.

**Comment by mlawdawg** [comment]
Thanks. I didn't know about multipass but after doing quick search/read about it I don't think it can work for me. I need windows 10 file access to Ubuntu running in the VM which I don't think multipass provides.

**Comment by mlawdawg** [comment]
File Explorer error when windows file access to wsl STOPS working after 1-2 days of it working fine:

![file explorer WSL win 10 cannot access wsl 2_LI](https://user-images.githubusercontent.com/91216310/135348715-eff451ce-7efb-48b7-80a5-c5c1dc7046ae.jpg)

**Comment by arafatx** [comment]
> I need windows 10 file access to Ubuntu running in the VM which I don't think multipass provides.

multipass is an ubuntu virtual machine developed by ubuntu with ubuntu kernel. Yes, it can also access files between windows 10 and ubuntu where you need to enable the mount option. It works faster than WSL 2. WSL 2 is good but not yet mature.
