### ISSUE TITLE
Python is so slow and I cannot disable appendWindowsPath

### ISSUE THREAD

**Issue by moracabanas** [microsoft/WSL#7457]
### Windows Build Number

Microsoft Windows [Versión 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu 20.04

### Other Software

Visual Studio Code 1.60.2

### Repro Steps

Execute Python commands so you will notice some of them takes minutes to run

I read this is due to default `appendWindowsPath` so `PATH` is full of `/mnt/c....` useless stuff. Some of them slows down Python execution on WSL2.

The solution is to `appendWindowsPath`. I can't do that because I need to do `code .` mostly.

I need to edit *appended windows path* to remove unnecessary stuff so I can run `code .` but Python runs fine

### Expected Behavior

Python commands should run instantly

### Actual Behavior

Python commands takes minutes to run

**Comment by benhillis** [comment]
I would suggest either manually editing your path in your bashrc or creating an alias to vscode.

**Comment by moracabanas** [comment]
Thank you. I also discovered this issue goes away if I unset `$DISPLAY` with `export DISPLAY=`

I commented any `export DISPLAY` on `~/.bashrc` but it keeps loading from somewhere.

Trying to empty`export DISPLAY=` from `~/.bashrc` or `~/.bash_aliases` didn't work.
 How could I track this?
