### ISSUE TITLE
Interrupted system call exception in p9io.cpp WatchThread terminates the init process

### ISSUE THREAD

**Issue by mjz19910** [microsoft/WSL#7459]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

strace, Version: 5.5

### Repro Steps

any of the following cause an abort of a process handling wsl p9io
1. Run the following from windows (cmd.exe/powershell.exe) `bash -c "strace -s 128 -p 1 -f -o >(head -100)"`

2. try to ptrace pid 7(usually the first child of `/init`) `strace -s 128 -p 7 -o >(head -100)`

### Expected Behavior

When an exception of this type is caught, the WatchThread restarts the system call that was interrupted.

### Actual Behavior

```
strace: Process 1 attached with 2 threads
1     recvfrom(100,  <unfinished ...>
7     writev(2, [
           {iov_base="terminating with uncaught exception of type wil::ResultException: ", iov_len=66},
           {iov_base="Interrupted system call @.\\p9io.cpp:201 (WatchThread)\n", iov_len=54}
       ], 2) = 120
7     writev(2, [{iov_base="", iov_len=0}, {iov_base=NULL, iov_len=0}], 2) = 0
7     writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2) = 1
7     rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [CHLD], 8) = 0
7     gettid()                          = 7
7     tkill(7, SIGABRT)                 = 0
7     rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
7     --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=1, si_uid=0} ---
7     rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
...
```
(the SIGSEGV line repeats until you stop tracing the process, then crashes the wsl2 init process)
```
...
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
7     --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
^Cstrace: Process 1 detached
strace: Process 7 detached
```
```
# wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```

In the p9io WatchThread in the init process(usually pid 7) that is a child of the inital init process(pid 1),
an interrupted syscall should be restarted, not cause process termination because of an exception.

**Comment by WSLUser** [comment]
If you compile the latest stable kernel with the same config options, do you still see the issue?

**Comment by DanPinGF** [comment]
Does the issue continue after updating your Windows, if not already?

**Comment by benhillis** [comment]
Thanks for posting, I have a fix for this I will be submitting soon.

**Comment by marchelzo** [comment]
I've been running into this for a couple of weeks now -- currently using kill(1) to stop the broken process right after I log in, but it seems to be causing some weird PTY issues. Is there another way I can work around this for now?

**Comment by benhillis** [comment]
Fixed in https://github.com/microsoft/WSL/releases/tag/0.51.0.
