### ISSUE TITLE
Problems with git clone

### ISSUE THREAD

**Issue by burbanox** [microsoft/WSL#7461]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Release:        20.04

### Other Software

Git 2.33.0 
Github

### Repro Steps

git clone https://github.com/burbanox/responsive-design.git

### Expected Behavior

Cloning the repository

### Actual Behavior

Show error :
`fatal: unable to access 'https://github.com/path/to/repo.git/': gnutls_handshake() failed: Error in the pull function`

**Comment by owenschupp** [comment]
From the sound of this, this does not appear to be a WSL-related issue. I would suggest running `sudo apt-get install libssl-dev` because the `gnutls_handshake` failure may be due to an SSL issue. If this persists, check if you are behind a proxy and modify your `.config` accordingly.
