### ISSUE TITLE
Unable to start distros - WSL instance has terminated

### ISSUE THREAD

**Issue by kingp0dd** [microsoft/WSL#7476]
2) Windows version / build number

```
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.
```

```
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 9/28/2021
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.16
```

3) Steps required to reproduce

`wsl -d Ubuntu`

Info:

I've been using this WSL2 (Ubuntu-18.04) for a couple of months now to run a web server. This morning, with no configuration modified, it suddenly won't open.

I tried:
- uninstalling all distros and using `wsl --unregister`
- installed WSL Kernel from `https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi`
- turned off Virtual Platform and WSL in "Windows Features", and then re-run `wsl --install`
- downloaded and installed the default distro (Ubuntu) from Microsoft Store

4) Copy of the terminal output

```
C:\WINDOWS\system32>wsl -d Ubuntu
The Windows Subsystem for Linux instance has terminated.
```

5) Expected Behavior

`Will enter WSL bash`

6) ETL File

[wsl.etl.zip](https://github.com/microsoft/WSL/files/7242126/wsl.etl.zip)

**Comment by OneBlue** [comment]
Thanks for reporting this @kingp0dd.

Looking at the logs, I can see:

```
hr: 	0x80072745 (An established connection was aborted by the software in your host machine. )
```

So it looks like something is going wrong inside the guest.

Can you enable the debug console by adding

```
[wsl2]
debugConsole=true
```

in .wslconfig and share its output during a repro ?

**Comment by kingp0dd** [comment]
I read your message only now. It seems that the issue has been fixed.

I think it was caused by a failing secondary hard drive. I noticed my other
drive (not the one the OS, WSL, and distro are installed in) was having
100% usage constantly.

Unplugged it, restarted, and the distro booted up the first time. Is it
because it's trying to mount all drives at startup?

**Comment by benhillis** [comment]
@kingp0dd - potentially, although if trying to mount your second hard drive failed I would still expect your distro to boot.  Closing since the issue no longer occurs.
