### ISSUE TITLE
ssh to external servers blocked in WSL2, wasn't in WSL1

### ISSUE THREAD

**Issue by mw55309** [microsoft/WSL#7482]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

I used to use SSH successfully with github, and various other servers, successfully in WSL1

I upgraded to WSL2 and it instantly stopped.

ssh cannot connect to *anything*

Nothing else has changed.

### Expected Behavior

SSH should be able to connect to e.g. github to clone repos

It cannot. It just hangs then says:

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

### Actual Behavior

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

**Comment by mw55309** [comment]
Just downgraded my WSL back to 1 and suddently SSH works again :)

**Comment by hockeybrad** [comment]
Yep I have been troubleshooting this for weeks and today I'm just going to have to revert to WSL1. I made sure port 22 was not being blocked internally or externally. Any other ssh terminal works fine. Just not WSL2. It's a darn shame.
