### ISSUE TITLE
Allow the user to not install any distro when first running wsl --install

### ISSUE THREAD

**Issue by beni69** [microsoft/WSL#7483]
**Is your feature request related to a problem? Please describe.**
This applies to machines where WSL is not yet installed. By running `wsl --install`, this command enables WSL2, and installs a distro. This is Ubuntu by default, but this can be changed, however there doesn't seem to be an option to skip this step and not install any distro.

**Describe the solution you'd like**
I think there should be a way to skip installing a default distro for the users that will install their own one that's not in the Microsoft Store. Something like `wsl --install --no-distro` or simply `wsl --install -d none`

**Describe alternatives you've considered**
Well, the alternative is to wait for Ubuntu to download and install, and then remove it, which is just wasting time and bandwith.

**Additional context**
This would really come in handy at my school, where we are installing WSL2 to a whole room of computers and having to wait for Ubuntu to download on the slow school internet just to remove it later seems really pointless.

**Comment by craigloewen-msft** [comment]
This has been added in the latest builds on Windows Insiders as a `wsl --install --no-distro` option! Thank you for the feedback.
