### ISSUE TITLE
WSL file explorer stopped working after upgrading to Win11

### ISSUE THREAD

**Issue by d3vel0per** [microsoft/WSL#7488]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu-18.04

### Repro Steps

Try opening WSL file explorer post update to Win11 and it gives the following error.

![image](https://user-images.githubusercontent.com/3216900/136011675-24d43279-37e1-445b-948a-5a35690ccaee.png)

### Expected Behavior

Should provide access to the file system from within file explorer

### Actual Behavior

Unable to access WSL file system due to permission error.

**Comment by mataslib** [comment]
I've got same issue. It starts working after turning on docker desktop app.

**Comment by gcarneiro** [comment]
Same error here, Ubuntu 20.04

Windows info
Edição	Windows 11 Home Single Language
Versão	21H2
Instalado em	‎02/‎11/‎2021
Compilação do SO	22000.282
Experiência	Pacote de Experiência de Recursos do Windows 1000.22000.282.0

**Comment by Ryton** [comment]
Idk what caused it but found a temporary fix: 
One way at least, to mount the windows drives again from linux side, by running:
run: 
$ sudo mount -t drvfs c: /mnt/c (if /mnt/c is empty:)

then cd .. and cd /mnt/c and the content is available again

can be added to the bash script too.

**Comment by dstengele** [comment]
Same here after the Windows 11 upgrade. WSL1 instances can be accessed normally, the error occurs only with WSL2.
