### ISSUE TITLE
Internet connection takes too long.

### ISSUE THREAD

**Issue by emmanuelanaya** [Microsoft/WSL#749]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- **A brief description:** Connection to the internet takes too much time.

When running `sudo apt -get install | update`, after accepting the installation of packages, it shows the following message: `0% [Conectando a archive.ubuntu.com (2001:67c:1360:8001:21)]` (Spanish by the way, it just says `Connecting to archive.ubuntu.com ...`). It stays like that for about 1:30 min, then the installation proceeds normally. This happens with each run of one of the `apt-get` commands stated above. The last number of the output (`21`) changes after each run of the command, or even within the execution.

Using `elinks`, loading `google.com` takes about 4 min, after that pages load normally until `elinks` is closed. Closing and running `elinks` again throws the same issue. 

I can´t even `ping google.com` as it returns `ping: icmp open socket: Permission denied`. Probably this is not related but I write it down anyway.
- **Expected results:** For this commands to take a reasonable amount of time, as the provider's internet speed is definitely not an issue.
- **Actual results (with terminal output if applicable):** Stated above.
- **Your Windows build number:** Microsoft Windows [Version 10.0.14393]
- **Steps / commands required to reproduce the error:** Running `apt-get install` _any package_ or `apt-get update` or trying browsing with `elinks`
- **Required packages and commands to install:** `elinks`

**Comment by aseering** [comment]
@emmanuelanaya -- hm...  If you try to connect to that IPv6 address (2001:67c:1360:8001:21) from a Windows application, is it fast?  Or is it equally slow?

I'm wondering if there's an issue with the IPv6 configuration on your system.

**Comment by emmanuelanaya** [comment]
Yes, its also slow when trying to access from Chrome.

Which kind of issue could it be?

**Comment by sunilmut** [comment]
@emmanuelanaya - Can you share the contents of your '/etc/resolv.conf' from your WSL setup?
I am wondering if there is a way you can force the use of IPv4. WSL currently does not support '/etc/sysctl.conf' or 'sysctl'. Can you try disabling all the IPv6 addresses from '/etc/hosts' and see if that will force the use of IPv4? Note that the '/etc/hosts' file will get overwritten during the next bash launch. Unfortunately, the change to allow users to manager their own '/etc/hosts' is not present in this build.

**Comment by sunilmut** [comment]
Alternatively, you can also try disabling IPv6 on your Windows setup to see if that helps.

**Comment by emmanuelanaya** [comment]
@sunilmut Here´s my `/etc/resolv.conf`:

`#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN`
`nameserver 192.168.1.254`
`nameserver fec0:0:0:ffff::1`
`nameserver fec0:0:0:ffff::2`

Neither disabling IPv6 addresses from `/etc/hosts` nor in Windows worked.

**Comment by max-kovpak** [comment]
I have the same issue. Really slow internet connection..

**Comment by ATouhou** [comment]
This fixed it for me: 
echo nameserver 192.168.1.254 > /etc/resolv.conf

**Comment by max-kovpak** [comment]
@ATouhou but not for me

**Comment by ATouhou** [comment]
Also run in administrator mode and turn off all firewall applications

**Comment by max-kovpak** [comment]
@ATouhou thanks! This is was problem in my avast antivirus.

**Comment by dege88** [comment]
For me the issue was with unconnected VPNs like hamachi.
Disabling all virtual network card made the network extremly fast.

**Comment by sunilmut** [comment]
While this issue manifests as networking problems, the real underlying issue is from a lack of tighter integration with Antivirus applications. We have a [document out](https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/) to which will help us work with the AV vendors for better integration. Please bear with us as we work with the AV vendors for that, which might take some time.

**Comment by sunilmut** [comment]
Also, see #475 for more details on AV integration with WSL.

**Comment by starnostar** [comment]
I solved this with by commenting out everything in /etc/apt/sources.list and adding: 

`deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse`
`deb mirror://mirrors.ubuntu.com/mirrors.txt trusty-updates main restricted universe multiverse`
`deb mirror://mirrors.ubuntu.com/mirrors.txt trusty-backports main restricted universe multiverse`
`deb mirror://mirrors.ubuntu.com/mirrors.txt trusty-security main restricted universe multiverse`

which should pick the fastest mirror every time you update

**Comment by Holt59** [comment]
@starnostar Thanks, made my day after going through all the opened issues regarding `/etc/resolv.conf`, firewalls and antivirus issues... The default `sources.list` should certainly be updated to avoid such headache for future users.

**Comment by botimer** [comment]
@starnostar @Holt59 I just ran into this and tried the mirror solution. Much better. Something to note, though: I just upgraded to 16.04 (Xenial) with `lxrun /uninstall` and `lxrun /install`, so the sources need to be set for your release. For example:

```
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-backports main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse
```

**Comment by jdevora** [comment]
I had the same issue and I fix it with https://askubuntu.com/questions/574569/apt-get-stuck-at-0-connecting-to-us-archive-ubuntu-com


> solved this  by editing /etc/gai.conf and uncommenting the line:
```
#
#    For sites which prefer IPv4 connections change the last line to
#
precedence ::ffff:0:0/96 100
```
>This lets you keep IPv6 enabled, but sets the order of precedence to prefer IPv4 over IPv6.

**Comment by botimer** [comment]
@jdevora Worked flawlessly. Thanks! 👍

**Comment by sagudev** [comment]
tnx

**Comment by arnabanerji** [comment]
Still working for me now

**Comment by therealkenc** [comment]
This one was marked as a dupe but never closed. The OP is a slow to establish connection, possibly attributed to ipv6 in the resolver. Then Avast was blamed, even though the OP doesn't mention Avast (this caused the dupe). #475 is a discussion thread, which suits in the circumstance.
