### ISSUE TITLE
Windows host network connections to WSL Ubuntu instance stops after period of time

### ISSUE THREAD

**Issue by appymedia** [microsoft/WSL#7492]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Jetbrains DataGrip 2021.2.3
Jetbrains PhpStorm (Latest)
Jetbrains Rider (Latest)

### Repro Steps

I'm using JetBrains DataGrip (or their PhpStorm or Rider products) installed on native Windows and connecting to databases for dev tasks like opening DB tables, editing data and so on.  After a period of time (ranges from 5-60 minutes of working) I'm unable to connect to the DB servers running on my WSL instance.  I can connect to the WSL terminal and see the processes still running and I can connect to the DB server from within WSL on the command line etc.  I just can't connect from my Windows host.

At the same time ANY connection from the windows host to a WSL hosted service seems to stop working as well.  For example a working node instance running an express app I can no longer see in Microsoft edge once the DB connection issue starts.  Same with Apache / PHP and so on.

The DB servers are installed within WSL.  I've tried both PostgreSQL and MySQL with the same results being reproduced (and on a different machine as well).  You can repro this by repeatedly disconnecting and reconnecting to the DB server from within the JetBrains products for a period of time (you might need to be patient, it will break eventually).

I've seen this issue for some period of time with different WSL Kernels and different JetBrains product versions and given its happening for both MySQL and PostgreSQL it seems the issue is somewhere in the network stack?

The only way I've been able to recover the networking is restarting the LxssManager windows service.  Restarting the DB servers from WSL does nothing to help once the connection breaks.

Seems like the JetBrains products way of connecting to DB servers in WSL is provoking an issue but I wouldn't expect it to completely stop ALL host to WSL network connectivity regardless?

### Expected Behavior

Successfully connect to DB server within WSL and other hosted WSL network services like node, Apache etc.

### Actual Behavior

Connection denied with following error reported in JetBrains products  (for PostgreSQL as example):

[08001] Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Also, at the same time I'm unable to connect to WSL hosted services like node, Apache / PHP from Windows.  The whole network stack seems to stop.  I can connect via the terminal still and see services running fine within WSL.

### Diagnostic Logs

JetBrains Error is reported as (for PostgreSQL as example):

[08001] Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by abdusco** [comment]
Yeah, I've been [discussing this issue](https://news.ycombinator.com/item?id=28816569) on HackerNews, and this is still a problem and there is still no reliable solution that works every time. 

> I limit using the localhost relay for now the better. Such a shame as its really spoiled what would have otherwise been a great experience dev wise.

Agreed. Every time I upgrade to a newer Insider build, I keep my fingers crossed hoping that it's been fixed, but it still happens. 

I don't expect that it will be addressed soon, so I just keep the scheduled task enabled, which keeps updating the IP in hosts file. This way, I can always access services running inside WSL using the alternate hostname, and it works more reliably than `localhost`.

**Comment by appymedia** [comment]
Yes, thought about this more and just accepting the fact that these rough edges will probably just need more time to get resolved.  I do appreciate the work.  I think for for now and me I'll keep two dev solution's, one WSL and one non-WSL in-case I get blocked.

**Comment by appymedia** [comment]
@Kcharle Not sure it this will help but did you try restarting the LxssManager windows service, that normally gets things working again for me with my original issue (that's without applying @abdusco workaround as well)?  I'm pretty sure I've seen folks get things working by doing a 'wsl --terminate Ubuntu' (Ubuntu for me for example, replace with your distro) as well?  I might be misunderstanding your issue exactly though!

I actually deleted a comment where I was getting a bit frustrated about this issue as I've spent tons of time trying to get things working in a way I trust the workflow.  My main concern about if I use a workaround is what other consequences are there as I imagine most tooling and things for WSL will expect the local host relay to be working? @abdusco Have you noticed any problems when the local relay stops and you use your (fantastic) work around please?  VS Code, Docker / Docker Desktop etc are things I'm thinking might need it still, working ok?

Also, it might not be a solution for you but have you considered using a full Ubuntu VM either with Hyper-V, VirtualBox or VMWare Player / Workstation?  I've been using VirtualBox / VMWare and things have gone a lot better, albeit at the cost of some perf (not enough to effect me but YMMV) and relying on a 3rd party hypervisor.

I'm sure the Microsoft folks are working hard to sort all this (I hope) and once things are resolved and more stable for me I'll want to look at switching at it seems this will be the logical path of least resistance / best supported for my workloads.

**Comment by Kcharle** [comment]
@appymedia yeah it's definitely a bit of a confusing one.

I'm fairly familiar with Linux and dev ops enough to find my way around, but new to the Windows + WSL system. Was a Mac user for years.

I'll give your suggestion a try today and post my results.

**Comment by benhillis** [comment]
@appymedia - that is great news, thanks again :)

This fix is in the pipeline to be backported to earlier versions of Windows 10, not sure on timeline yet.

**Comment by nd** [comment]
@benhillis is it correct that connecting to service in WSL from Windows using an internal WSL ip address should work more reliably than connecting via localhost or 127.0.0.1?

**Comment by benhillis** [comment]
@nd - both should work, but there are less moving pieces if you connect directly.

**Comment by alberto-i** [comment]
Having the same problem. Keeps happening daily and it requires a full windows restart.

Using an address other than localhost is not an option for web development because many browser features (like clipboard api) are disabled on http when the hostname is not localhost.
