### ISSUE TITLE
WSL blocks Bitvise SSH Server

### ISSUE THREAD

**Issue by axfelix** [Microsoft/WSL#750]
WSL appears to bind to port 22 and block Bitvise SSH Server from starting up.

This is the only _conflict_ I've so far incurred from installing WSL, which I will say is quite impressive, as I'm a very heavy user of msysgit and other bash shells on Windows already, and it hasn't messed up my path or anything else. However, I previously had Bitvise configured to load my msysgit bash shell when connecting over ssh (which is my preference as it includes all of my environment variables and can accept scp connections) and I'd like to return to this if possible. Any way I can prevent WSL from taking over port 22 (assuming this is the issue)?

**Comment by axfelix** [comment]
For the moment I'm just running bitvise on port 22222 instead, which appears to work. I only really ssh to this machine from my laptop anyway, so this is an acceptable workaround.

**Comment by axfelix** [comment]
Might I also recommend adding an alias to the WSL bash shell called just "wsl.exe"? Having the mingw binaries earlier on my path than C:\Windows means I always get my msys git bash shell when I call bash, which is good, but when I do want to hop into the wsl environment, I wound up just making my own alias from C:\Windows\System32\bash.exe to wsl.exe.

**Comment by axfelix** [comment]
Incidentally, trying to launch wsl from over an msys bash ssh connection throws Error 80070005.

**Comment by sunilmut** [comment]
@axfelix - Thanks for the feedback! bash\WSL by default should not start the ssh service. If you are manually starting the sshd service on WSL and running into conflicts with Bitvise, then yes, that makes sense. As @rodrymbo also notes, WSL is not a container or VM environment, but rather aiming to provide a native experience. To unblock yourself, you should be able to configure the settings of either of these apps to use a different port. And, many thanks for using WSL!

**Comment by benhillis** [comment]
I believe this is the same issue as #777.  @axfelix could you confirm that if you stop the below two services you're able to use Bitvise ssh server on port 22 again?

"Windows SSH Server": "SSH Server Proxy" and "SSH Server Broker"

Full disclosure: those two services don't have anything to do with WSL.  They're just another part of Windows.

**Comment by tara-raj** [comment]
WSL no longer requires "Developer Mode" so this issue should now be resolved.
