### ISSUE TITLE
WSL 2 sometimes has no response

### ISSUE THREAD

**Issue by chenjunnn** [microsoft/WSL#7503]
### Windows Build Number

Microsoft Windows [版本 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

run `wsl --shutdown` then restart it.

### Expected Behavior

WSL should start within 5s.

### Actual Behavior

Any command line of `wsl` have no response for a long time.
![image](https://user-images.githubusercontent.com/57067221/136387105-71264e2c-f0b1-4145-b159-19328376d1ef.png)

**Comment by sink0918** [comment]
This is the share link of the [feedback](https://aka.ms/AAel4hy).
