### ISSUE TITLE
Running "bash echo $PATH" throws "Cannot execute binary file"

### ISSUE THREAD

**Issue by GeorgeMD** [microsoft/WSL#7504]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1237]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 18.04

### Repro Steps

1. (Optional) Run WSL
2. From WSL (or from PowerShell) run any command as if you want to run it in another bash. For example `bash echo $PATH`

### Expected Behavior

The command is ran successfully. In the example above it should return the content of the `PATH` variable.

### Actual Behavior

An error is thrown. In the example above the error is `/bin/echo: /bin/echo: cannot execute binary file`.

**Comment by RyanJarv** [comment]
I don't remember off hand how this behaves normally but I'm not sure this is unexpected, bash can't interpret a binary so this error does make sense.

Imagine you intended to run something more like this?

> bash -c "echo $PATH"

**Comment by GeorgeMD** [comment]
`bash -c "echo $PATH"` is a valid command in linux, it returns the contents of $PATH. I might not understand WSL, but I thought it's supposed to run as much like linux in a VM as possible.

**Comment by Rauxon** [comment]
The behaviour in a 'real' linux system matches:

> $ bash echo $PATH
> /usr/bin/echo: /usr/bin/echo: cannot execute binary file

compared to:
> $ cat test.sh
> /usr/bin/echo $PATH
> $ bash test.sh
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Therefore this is definitely a 'behaving as expected', and would be a query against bash rather than WSL.

**Comment by RyanJarv** [comment]
@GeorgeMD with -c bash interprets the following arguments as a script and executed them assuming it's a valid shell script.

Without -c it attempts to read the contents of the file passed as an argument and interpret's it as a script. If the file is not a script, but a binary, it won't know what to do, simply can't interpret the contents of a binary as a valid bash script. It just ends up reading gibberish.

Of course this might be dependent on the sh implementation and version, not sure if I can say much there.
