### ISSUE TITLE
"'wsl' is not recognized as an internal or external command" after Win 7 -> Win 10 upgrade

### ISSUE THREAD

**Issue by danfireman** [microsoft/WSL#7513]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.928]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

NA

### Distro Version

NA

### Repro Steps

Attempting to install WSL by following the instructions here after a win 7 -> win 10 upgrade: https://docs.microsoft.com/en-us/windows/wsl/install

Attempting to run `wsl --install` fails with it unable to find "wsl":
![image](https://user-images.githubusercontent.com/6192259/136660360-f8f0c3b8-05fd-4273-8e55-b3fda3ee497b.png)
![image](https://user-images.githubusercontent.com/6192259/136660479-f9eaf9c1-4fe9-411f-88c3-beb6b967f585.png)

Running a search for all files called `wsl.exe` in the `C:\Windows` folder reveals that only one version compatible with my OS exists, but it cannot run successfully:
![image](https://user-images.githubusercontent.com/6192259/136660788-6a1e4b59-a612-4184-b1a1-1ccb75055ff4.png)
![image](https://user-images.githubusercontent.com/6192259/136660680-734fd2ce-05c5-4360-acec-dbaa6e58d909.png)

### Expected Behavior

The wsl executable should be found and WSL installed.

### Actual Behavior

> wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.

![image](https://user-images.githubusercontent.com/6192259/136660360-f8f0c3b8-05fd-4273-8e55-b3fda3ee497b.png)

**Comment by 0xbadfca11** [comment]
Do Windows Update.
19043.928 is very old.

**Comment by TheDarkerPhantom** [comment]
You also are attempting to run WSL.exe from within your WinSXS. Additionally, you are not even running the correct executable, the file you ran, was only 5 KB.

**Comment by 106AbdulBasit** [comment]
> Do Windows Update. 19043.928 is too old. Support for `wsl --install` started in 19043.1151. https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/

this one saved my life :D

**Comment by zain12333** [comment]
not response please help to install ubuntu in window 8

**Comment by Sharif-Minhaz** [comment]
You can manually download WSL from the Microsoft Store too.

[https://apps.microsoft.com/detail/9p9tqf7mrm4r?ocid=pdpshare&hl=en-us&gl=US](https://apps.microsoft.com/detail/9p9tqf7mrm4r?ocid=pdpshare&hl=en-us&gl=US)
