### ISSUE TITLE
No Linux entry in Explorer with Store WSL version

### ISSUE THREAD

**Issue by Ansuel** [microsoft/WSL#7520]
### Version

Microsoft Windows [Versione 10.0.22471.1000]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 21.10

### Repro Steps

1. Remove Optional Component Windows Subsystem Linux
2. Install WSL from the Microsoft Store
3. Reboot the system
4. Check explorer
5. Notice Linux shortcut disappeared and any quick access entry that point to wsl.localhost removed

### Expected Behavior

Linux shortcut and quick access entry not removed. wsl.localhost is still accessible and recent entry pointing to wsl.localhost in explorer are not removed.

### Actual Behavior

Linux shortcut and quick access entry removed.

**Comment by Ansuel** [comment]
I think it would be good to add this to the known issue so people won't complain about missing entry and all...
I think many with this new Store version will remove the optional component and install the store variant.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/0.61.4.
