### ISSUE TITLE
The preview version of WSL in the Microsoft Store does not work with wsl2-ssh-pageant

### ISSUE THREAD

**Issue by DavidZidar** [microsoft/WSL#7521]
### Version

10.0.22000.194

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Debian 11

### Other Software

wsl2-ssh-pageant v1.3.0

### Repro Steps

1. Install WSL preview from Microsoft Store
2. Try to use wsl2-ssh-pageant with a Yubikey

### Expected Behavior

It should still be working, just like before.

### Actual Behavior

I am not authorized by the SSH key in my Yubikey, SSH is asking me for my password.

If I uninstall the Microsoft Store WSL it all starts working again.

**Comment by benhillis** [comment]
@DavidZidar - I would suggest also posting the issue there, might be more actionable from that side.

**Comment by DavidZidar** [comment]
Just to confirm, this was the issue on my system as well.
