### ISSUE TITLE
Should uninstall of OS feature reclaim disk/storage space used by the WSL feature?

### ISSUE THREAD

**Issue by dmealo** [microsoft/WSL#7524]
### Version

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Note OS drive free space.
2. Install Store Preview version of WSL.
2. Uninstall WSL OS feature via Control Panel > Windows Features
3. Reboot when prompted.
4. Note no change in OS drive free space (in GBs at least).

### Expected Behavior

Would expect at least some change in free space, but perhaps this is impossible due to OS or feature architecture?

### Actual Behavior

No additional free space in OS drive.

**Comment by DavidMtbg** [comment]
With the Store version of WSL weighing in at 442.2 MB, I'm sure I'm not the only person who will think they might as well reclaim some space by uninstalling the OS installed version of WSL - that was my thinking here, not a big deal, but curious.
