### ISSUE TITLE
Windows 11 update causing Kali Linux failure

### ISSUE THREAD

**Issue by CoolGames** [microsoft/WSL#7536]
### Version

Windows version: 10.0.22000.194

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.60.1

### Distro Version

Default Distribution: kali-linux

### Repro Steps

Start without Windows 11 but latest Windows 10 20H2
Update History reflect 3/27/21 installation.

Go to Microsoft Store install [Kali Linux](https://www.microsoft.com/store/productId/9PKR34TNCV07)
Run WSL with Kali Linux

[Upgrade to Windows 11](https://www.microsoft.com/en-us/windows/windows-11)

**Try to do Kali Linux and follow suggested troubleshooting steps.**

`$ wsl
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization

$ wsl --status
Default Distribution: kali-linux
Default Version: 2
WSL version: 0.47.1.0
Kernel version: 5.10.60.1
WSLg version: 1.0.29
Windows version: 10.0.22000.194

$ Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

FeatureName : Microsoft-Windows-Subsystem-Linux
DisplayName : Windows Subsystem for Linux
Description : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired : Possible
State : Enabled
CustomProperties :
ServerComponent\Description : Provides services and environments for running native user-mode Linux
shells and tools on Windows.
ServerComponent\DisplayName : Windows Subsystem for Linux
ServerComponent\Id : 1033
ServerComponent\Type : Feature
ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux`

### Expected Behavior

I expect it to work or point to updated troubleshooting for **Windows 11 UPGRADED** system.

### Actual Behavior

REPEATING

`$ wsl
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization

$ wsl --status
Default Distribution: kali-linux
Default Version: 2
WSL version: 0.47.1.0
Kernel version: 5.10.60.1
WSLg version: 1.0.29
Windows version: 10.0.22000.194

$ Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

FeatureName : Microsoft-Windows-Subsystem-Linux
DisplayName : Windows Subsystem for Linux
Description : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired : Possible
State : Enabled
CustomProperties :
ServerComponent\Description : Provides services and environments for running native user-mode Linux
shells and tools on Windows.
ServerComponent\DisplayName : Windows Subsystem for Linux
ServerComponent\Id : 1033
ServerComponent\Type : Feature
ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux`

**Comment by benhillis** [comment]
The store app still requires virtual machine platform, is that enabled?
