### ISSUE TITLE
Mounting a drive in WSL2 cause a BSOD on Windows11

### ISSUE THREAD

**Issue by guillemcanal** [microsoft/WSL#7549]
### Version

Microsoft Windows [version 10.0.22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

A pCloud Drive mounted on Windows as P:

### Repro Steps

```powershell
wsl -d Ubuntu
```

```shell
mkdir -p /mnt/p
sudo mount -t drvfs P: /mnt/p
cd /mnt/p
ls
```

### Expected Behavior

Being able to access the drive from WSL2

### Actual Behavior

Got a BSOD with a `MEMORY MANAGEMENT` error

**Comment by benhillis** [comment]
Interesting, WSL2 shouldn't be causing blue screens.  If you file a feedback hub item and I'll see if there are any dumps from your machine.

**Comment by guillemcanal** [comment]
@benhillis unfortunately it seems that I cannot submit a Feedback Hub report. Clicking on "Recreate My Problem", and reproducing the issue in the WSL crash the system. After the reboot, the app lost my record. Any suggestions ? Thanks :)

**Comment by guillemcanal** [comment]
@benhillis I sent a report and referenced the github issue in the description. I'm not sure if any error logs were captured by the system. Let's hope so :)

**Comment by emanuel-schmid** [comment]
Hi all
I'm having exactly the same issue. Are there are any updates?

**Comment by jaredtconnor** [comment]
+1 on this, got the same issue.

**Comment by accipiterHawk** [comment]
Same issue on windows 10

**Comment by JasonSFuller** [comment]
@benhillis this seems to be fixed now, at least in Windows 11, though hopefully @guillemcanal will chime in.  The instructions posted in the Repro Steps above worked for me:

```bash
# as root, i.e. `sudo -i`
mkdir -p /mnt/p
sudo mount -t drvfs P: /mnt/p
cd /mnt/p
ls
```

I've only played around with modifying text files for the past few minutes, but reading and writing (both in Windows and WSL2) seems to work.  FYI, I'm running:

* Windows 11 Pro (21H2, build 22000.527)
* Kernel 5.10.60.1-microsoft-standard-WSL2
* Ubuntu 20.04.3 LTS (`apt upgrade` as of 2022-02-16)
* pCloud Drive 3.11.10 (Windows 64-bit)

Thumbs up if anyone can confirm.

**Comment by guillemcanal** [comment]
@JasonSFuller Thanks for the heads up, I can report that the latest Windows update fixed the issue.
