### ISSUE TITLE
Do releases here get pushed to the MS Store?

### ISSUE THREAD

**Issue by gaia** [microsoft/WSL#7550]
Do releases here get pushed to the MS Store under _Windows Subsystem for Linux Preview_ and if yes, how long usually between a release here and the store app being updated?

Reason I ask is bc IDK of a way to get notified of available updates on MS Store, but I can [get notified of new releases on Github](https://gitpunch.com/) for any repo I follow.

**Comment by Theleonano** [comment]
is there an app for wsl?

**Comment by Biswa96** [comment]
* Here https://github.com/microsoft/WSL/releases
* And here https://www.microsoft.com/store/productId/9P9TQF7MRM4R

But for Win11 only (officially)

**Comment by benhillis** [comment]
@gaia - yes. Store certification can take some time, usually less than 24 hours.
