### ISSUE TITLE
GNS3 run in wsl2 failed with docker (on wsl)

### ISSUE THREAD

**Issue by amirhakh** [microsoft/WSL#7577]
### Version

Microsoft Windows [Version 10.0.22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 4.0.0

### Repro Steps

I was installed GNS3 network simulator from `http://ppa.launchpad.net/gns3/ppa/ubuntu` repository. I start a project with one switch and 8 docker hosts. When started a docker based host, I see below error:
```
error while starting h6.netlab: Internal server error http://localhost:3080/v2/compute/projects/cb763298-6bd5-4f06-b8be-62d2a3d299b6/docker/nodes/e2cee6bb-dca7-450a-9120-eddd525918de/start
Internal server error http://localhost:3080/v2/compute/projects/cb763298-6bd5-4f06-b8be-62d2a3d299b6/docker/nodes/e2cee6bb-dca7-450a-9120-eddd525918de/start
```

I was set up GNS3 from [this](https://github.com/UT-Network-Lab/TCP-IP-Laboratory/blob/master/INSTALL.md) link.

### Expected Behavior

Run the GNS3 project like when run in Ubuntu vm

### Actual Behavior

Get error as below when run project with docker based hosts.
```
error while starting h6.netlab: Internal server error http://localhost:3080/v2/compute/projects/cb763298-6bd5-4f06-b8be-62d2a3d299b6/docker/nodes/e2cee6bb-dca7-450a-9120-eddd525918de/start
Internal server error http://localhost:3080/v2/compute/projects/cb763298-6bd5-4f06-b8be-62d2a3d299b6/docker/nodes/e2cee6bb-dca7-450a-9120-eddd525918de/start
```

**Comment by denioma** [comment]
Bump.
It would be great if either this was fixed or Docker support was added to Windows without using the GNS3 VM...

**Comment by amirhakh** [comment]
I was to update Docker Desktop to version 4.5.0 and gns3 to version 2.2.31,  but the problem has existed.
