### ISSUE TITLE
Cuda samples using OpenGL throw runtime error "cudaErrorOperatingSystem"

### ISSUE THREAD

**Issue by TortillaZHawaii** [microsoft/WSL#7589]
### Version

Microsoft Windows [Version 10.0.22000.282]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Cuda 11.4
OpenGL version string: 3.1 Mesa 21.0.3

### Repro Steps

I installed cuda-toolkit as in: [CUDA on WSL User Guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html), and OpenGL using apt [How to install OpenGL/GLUT libraries](https://askubuntu.com/questions/96087/how-to-install-opengl-glut-libraries).

I tested cuda install by running samples from [CUDA samples](https://github.com/NVIDIA/cuda-samples) by running various samples. Ones that didn't use OpenGL run without issues (for example BlackScholes, vectorAdd, simpleTexture). Also glxgears run without issues:
```
tortilla@GL73:~/cuda/cuda-samples/Samples/vectorAdd$ ./vectorAdd
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
tortilla@GL73:~/cuda/cuda-samples/Samples/vectorAdd$ glxgears
783 frames in 5.0 seconds = 156.425 FPS
687 frames in 5.0 seconds = 136.859 FPS
651 frames in 5.0 seconds = 130.059 FPS
563 frames in 5.0 seconds = 112.449 FPS
441 frames in 5.0 seconds = 88.116 FPS
580 frames in 5.0 seconds = 115.998 FPS
```

Problem arise when I try running samples that use OpenGL, like simpleGL or Mandelbrot. Each one of them creates window, and after a brief moment throws an error `code=304(codecudaErrorOperatingSystem)` when running function `cudaGraphicsGLRegisterBuffer`:
```
tortilla@GL73:~/cuda/cuda-samples/Samples/simpleGL$ ./simpleGL
simpleGL (VBO) starting...

GPU Device 0: "Turing" with compute capability 7.5

CUDA error at simpleGL.cu:421 code=304(cudaErrorOperatingSystem) "cudaGraphicsGLRegisterBuffer(vbo_res, *vbo, vbo_res_flags)"
CUDA error at simpleGL.cu:433 code=400(cudaErrorInvalidResourceHandle) "cudaGraphicsUnregisterResource(vbo_res)"
```
```
tortilla@GL73:~/cuda/cuda-samples/Samples/Mandelbrot$ ./Mandelbrot
[CUDA Mandelbrot/Julia Set] - Starting...
GPU Device 0: "Turing" with compute capability 7.5

Data initialization done.
Initializing GLUT...
OpenGL window created.
Creating GL texture...
Texture created.
Creating PBO...
CUDA error at Mandelbrot.cpp:916 code=304(cudaErrorOperatingSystem) "cudaGraphicsGLRegisterBuffer( &cuda_pbo_resource, gl_PBO, cudaGraphicsMapFlagsWriteDiscard)"
Segmentation fault
```

### Expected Behavior

CUDA applications using OpenGL continue running showing various animations on created window.

### Actual Behavior

Application throws an error `code=304(cudaErrorOperatingSystem)` when running function `cudaGraphicsGLRegisterBuffer`. The window shows up only for a brief moment.

**Comment by aroidzap** [comment]
OpenGL-CUDA Interop is not yet supported.
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#features-not-yet-supported

**Comment by Dtouch24680** [comment]
Hello! I have the same problem. Have you solved it？

**Comment by TortillaZHawaii** [comment]
Hi @Dtouch24680. It looks like this feature is still unsupported https://docs.nvidia.com/cuda/wsl-user-guide/index.html#features-not-yet-supported.

 I have end up using dual boot with Ubuntu where OpenGL works with CUDA without issues.

**Comment by jibnew** [comment]
Why is this issue closed? Could you at least update us on its current status?

**Comment by AwokeKnowing** [comment]
I have same issue
