### ISSUE TITLE
X11 forwarding request failed on channel 0

### ISSUE THREAD

**Issue by roachsinai** [microsoft/WSL#7597]
### Version

10.0.22000.282

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu-20.04

### Other Software

ssh/focal-updates,now 1:8.2p1-4ubuntu0.3 all [installed]

### Repro Steps

1. add config to ssh

```
Host *
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
    IdentityFile ~/.ssh/id_rsa
    Port 22
    Protocol 2
    XauthLocation /usr/bin/xauth

Host notebook
    HostName 192.158.50.2
    User wt
```

2. `ssh notebook`
3. run a program, like a pytho script to plot a figure

### Expected Behavior

Picture shows on local.

### Actual Behavior

Fisrt get warning and error:

```
Warning: No xauth data; using fake authentication data for X11 forwarding.
X11 forwarding request failed on channel 0
Last login: Tue Oct 26 20:13:38 2021 from 192.168.50.13
```

Then no figure show on local.

**Comment by OneBlue** [comment]
Thanks for reporting this @roachsinai. 

Can you share the verbose output of your ssh command ? (ssh -v [...]);

I also wonder if the `XauthLocation` config entry affects this path, can you try to remove it ?

**Comment by roachsinai** [comment]
Hi @OneBlue 

1. the output of `ssh -v wc-gui` was posted at https://pastebin.com/bDWtCrU4
2. the output of `ssh -v wc-gui` with `XauthLocation` setting removed was posted at https://pastebin.com/A735yCha

**Comment by OneBlue** [comment]
@roachsinai: I don't see X11 forwarding error in output you shared (X11 forwarding request failed on channel 0). 

What's wc-gui and what does it do ? Based on the logs it looks like it's trying to interact with the xrandr outputs, which I'm not is possible over X11 forwarding.

Does any X11 program succeed for you ? Can you share the ssh -v output for xeyes ?

**Comment by morgan-greywolf** [comment]
This actually looks like xauth is not installed on notebook.

**Comment by roachsinai** [comment]
> This actually looks like xauth is not installed on notebook.

Hi @morgan-greywolf I've installed xorg-xauth as shows on below:

![image](https://user-images.githubusercontent.com/9500049/141876983-dc63c9db-9849-49a8-8481-04363c7c6e17.png)

**Comment by roachsinai** [comment]
> @roachsinai: I don't see X11 forwarding error in output you shared (X11 forwarding request failed on channel 0).
> 
> What's wc-gui and what does it do ? Based on the logs it looks like it's trying to interact with the xrandr outputs, which I'm not is possible over X11 forwarding.
> 
> Does any X11 program succeed for you ? Can you share the ssh -v output for xeyes ?

@OneBlue sorry for that, wc-gui is also alias name of other host,

```
Host wc-gui
    HostName 192.168.13.2
    User ******
    IdentityFile ~/.ssh/office_server_ed25519
```

And so wierd (for me) that xeyes and python script all worked. For some reason I can't access host `notebook`.

But all get warning:

`Warning: No xauth data; using fake authentication data for X11 forwarding.`

And @morgan-greywolf I've check that `xauth/xenial,now 1:1.0.9-1ubuntu2 amd64` was installed on `wc-gui`.

**Comment by roachsinai** [comment]
Ohhh, I remembered one thing，x11 forwarding lost maybe caused by `genie` and now genie is not running so x11 forwarding is OK.

I've post that issue https://github.com/arkane-systems/genie/issues/214

So for now the problem is xauth warning.

**Comment by OneBlue** [comment]
Thanks for the update.
Closing since the issue doesn't appear to come from WSL.
