### ISSUE TITLE
Java program running in WSL2 JRE has no internet connection 

### ISSUE THREAD

**Issue by michaelyang02** [microsoft/WSL#7600]
### Version

10.0.22000.282

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)

### Repro Steps

1. Install openjdk using `sudo apt install openjdk-17-jdk`
2. Copy following test code into a file named `test.java`:

```
import java.io.IOException;
import java.net.InetAddress;

public class Test {

    public static void main(String[] args) {
        try {
            System.out.println(InetAddress.getByName("github.com").isReachable(1000));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
3. Compile and run using `javac test.java` and `java test`

### Expected Behavior

This program should have outputted `true` given an Internet connection.

I have compiled and run this piece of code using jdk-17 in Windows (even with the file still in WSL2 system), and it would return `true` every time. I think I may be overlooking some extremely simple problem or limitation, but I am at a loss here.

### Actual Behavior

This program outputs `false` after 1s timeout, failing to connect to `github.com`.

**Comment by OneBlue** [comment]
Thanks for reporting this @michaelyang02.

1 second is not a lot for a timeout, does this also reproes with higher timeouts (let's say 10 seconds) ? 

Also, what's the full exception stack trace when this fails ? 
Can you also share the content of /etc/resolv.conf ?

**Comment by michaelyang02** [comment]
Thank you for getting back to me, @OneBlue.

I have modified it to both 10 seconds and 60 seconds, but neither of them worked.

The problem is that it didn't really fail per se, as it is a best effort method, it simply returned false rather than raising an exception.

I have found the following description of the `isReachable` method if it is of any help ([documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#isReachable(int))):

> Test whether that address is reachable. Best effort is made by the implementation to try to reach the host, but firewalls and server configuration may block requests resulting in a unreachable status while some specific ports may be accessible. A typical implementation will use ICMP ECHO REQUESTs if the privilege can be obtained, otherwise it will try to establish a TCP connection on port 7 (Echo) of the destination host.

`/etc/resolv.conf` has the following content:

```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.27.32.1
```

The IP address at the end is the same as the vEthernet adaptor IPv4 address from `ipconfig` in command prompt.

**Comment by OneBlue** [comment]
Ok, makes sense.

Thanks for the explanation, closing this.
