### ISSUE TITLE
WSL2 does not start after upgrading to windows 11

### ISSUE THREAD

**Issue by philippwitte** [microsoft/WSL#7601]
### Version

Windows 11 Enterprise [22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ununtu 18.04

### Repro Steps

- Upgraded my systems to Windows 11
- After upgrading, launching my existing WSL2 kernel does not work anymore. Running wsl.exe or starting an Ubuntu terminal leads to:
`The operation timed out because a response was not received from the virtual machine or container.`
or 
`Insufficient system resources exist to complete the requested service.`
- Installing a new WSL2 distro worked (Ubuntu 20.04), but even then, the kernel sometimes times out and does not start.

### Expected Behavior

WSL2 should be able to start a virtual machine with my previously installed distro.

### Actual Behavior

![bug_report](https://user-images.githubusercontent.com/8646933/138958495-a08dfc07-f167-41b8-8d38-600520e802f0.png)

**Comment by maulberto3** [comment]
> 
> 
> This issue is fixed in Insider builds, and the fix is queued for the November servicing update.

I believe that there is a CRITICAL fix needed for WSL users, since some of them are not eligible for Windows 11, then the 10/31/2021 expiry message appeared locking both Docker and WSL unable to start! When you try to start WSL it can't saying data is invalid. when Docker wants to start, it errors and says the same thing.

**Comment by t3hcr** [comment]
On Windows 11, was able to get WSL2 to work again after experiencing this issue by opening an admin-elevated shell and ran:

wsl --update 
wsl --shutdown

Ran wsl from the same admin-elevated shell and that proceeded to work. 

From here, my attempts as regular (non-admin) and admin elevated shells running wsl all work as desired.

**Comment by vadimkantorov** [comment]
@t3hcr workaround helped. but it would be nice if it updated itself or not hung in the first place
