### ISSUE TITLE
explorer.exe /select,'C:\Path With Spaces' does not work, but works with no /select switch

### ISSUE THREAD

**Issue by damonlynch** [microsoft/WSL#7603]
### Version

Microsoft Windows [Version 10.0.22000.282]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

This works on WSL 1 (tested on Microsoft Windows [Version 10.0.19043.1288]) and WSL 2:
```bash
explorer.exe /select,'C:\some\path'
```
It works because there are no spaces in the path. When spaces are introduced, e.g. 
```bash
explorer.exe /select,'C:\Program Files\Common Files'
```
explorer fails to open the correct path and select the child folder.  Removing the `/select,` command line switch does open explorer displaying the correct folder's contents even when the path has spaces, however:

```bash
explorer.exe 'C:\Program Files\Common Files'
```

These behaviors occur in both WSL 1 and WSL 2.

### Expected Behavior

I expect the Explorer `/select,` command line switch to work irrespective of whether the path has spaces in it. 

### Actual Behavior

Windows Explorer opens, but it does not open the specified path and select the child folder as instructed &mdash; instead it displays a default folder (`D:\Documents` in my case).

Possibly related issue: #2835

**Comment by willeccles** [comment]
This is not related to WSL. This behavior occurs in command prompt as well. This is because CMD argument parsing is extremely convoluted, but the long story short is that if you replace the single quotes `''` with double quotes `""`, it should work just fine.

**Comment by ebarzilay-godaddy** [comment]
In case anyone runs into this: to make it work, separate the path into its own argument:

```
explorer.exe /select, 'C:\Program Files\Common Files'
```
