### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102

### ISSUE THREAD

**Issue by zausenecz** [microsoft/WSL#7604]
I realize that I am not the first person to face this problem, but nothing has helped me. All virtualization, hyper-v, etc have already turned off and on again. If I try to create a virtual machine through hyper-v, there is no error. Previously I got the error that the service hyper-v is not enabled but I've downloaded some additional libraries and everything was fine. But the terminal ubuntu still writes this error.

upd i tried to create virtual machine, still doesn't work

Translated with www.DeepL.com/Translator (free version)
![image](https://user-images.githubusercontent.com/93251054/139030316-4ed92aec-7498-4bf4-809e-9b2b0d57e2da.png)
![image](https://user-images.githubusercontent.com/93251054/139030364-cba639a7-4b13-4323-b7ea-8d5f9daf77d9.png)

> If it is possible to hide pictures under a spoiler, I'm sorry, I have not found where

**Comment by benhillis** [comment]
Do you have the "Virtual Machine Platform" OC installed?

/logs

**Comment by zausenecz** [comment]
> Do you have the "Virtual Machine Platform" OC installed?
> 
> /logs

yes i have. i think so

**Comment by OneBlue** [comment]
@zausenecz: Can you try to collect logs by following [record-wsl-logs-manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually)  ?
