### ISSUE TITLE
WSL2 Powershell exec commands not returning output

### ISSUE THREAD

**Issue by Mekadrom** [microsoft/WSL#7610]
### Version

Microsoft Windows [Version 10.0.18363.1801]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Intellij Idea 2021.2.3
Gradle 7.2.0

### Repro Steps

1. Start WSL2
2. Open Powershell
3. Type `wsl.exe --exec ip addr show eth0`
An even simpler example is `wsl.exe --exec sleep 100` returning instantly.

### Expected Behavior

It should output the same value that running the command `ip addr show eth0` outputs inside of the distro. This also happens for other commands such as `echo "hello"`. The lack of output here causes integration failures with Intellij Idea and gradle. Note that the problem still exists without Intellij and gradle being involved, I'm just mentioning them because they're my motivation for posting this issue.

### Actual Behavior

The commands seem to not be run at all, presenting no output.

**Comment by SamButterfield** [comment]
@Mekadrom Did you find a fix for this?
I've now got a similar issue after installing WSL

**Comment by SamButterfield** [comment]
Actually, I was having this issue on my PC after installing WSL. Simply Uninstalling it with this guide fixed it: https://pureinfotech.com/uninstall-wsl2-windows-10/
