### ISSUE TITLE
wsl command doesn't work and Ubuntu process in WT exits with 3221226505

### ISSUE THREAD

**Issue by webmandman** [microsoft/WSL#7611]
### Version

Microsoft Windows [Version 10.0.19043.1288]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0

### Distro Version

Ubuntu 20.04

### Repro Steps

First, `wsl --list` command doesn't output anything. Neither do other commands.

![image](https://user-images.githubusercontent.com/991677/139113589-b7fa098d-58ca-4b91-a608-4ab116f862d1.png)

Second, I installed Ubuntu 20.04 from the distro download (not the store, since I don't have access to it). I can launch Ubuntu from start menu. But from Windows Terminal I get this error: `[process exited with code 3221226505]`. Here are my WT profile settings: 
![image](https://user-images.githubusercontent.com/991677/139114072-c9e2ef14-e50f-4758-a98e-6a0c8c0ec4e5.png)

### Expected Behavior

I should be able to successfully launch Ubuntu from WT. 

### Actual Behavior

In WT I get this: 
[process exited with code 3221226505]

### Diagnostic Logs
ETL file here: 
https://drive.google.com/file/d/1gaHHQpsewccTq8VFT0LjzzJyIFaJxfpU/view?usp=sharing

**Comment by webmandman** [comment]
@benhillis is that .etl file enough. have you had a change to look at it?

**Comment by anphetamina** [comment]
Same issue but Ubuntu has been installed from the Store

**Comment by ajhalili2006** [comment]
I also have the same situation as I am right now, maybe I guess because of the recent 21H1 update?

**Comment by Biswa96** [comment]
Please provide the logs as mentioned above.

**Comment by ajhalili2006** [comment]
> Please provide the logs as mentioned above.

@Biswa96 I also reproduced the problem in my own and submitted it through Feedback Hub: https://aka.ms/AAeu8de

**Comment by wake7777** [comment]
Guys, I have solved this problem. Roll back the ads in PowerShell or the command line.
Instruction manual:
1. open PowerShell
2. write: wmic qfe list brief /format:table
![image](https://user-images.githubusercontent.com/88939478/141697133-e3e791e4-e76e-4300-9864-c3a6f4bb8753.png)
3. Deleting the latest update. If it didn't help, we delete another earlier one.
4. To delete a specific update, write: wusa /uninstall /code: Update ID (for example, KV:3156421);
![image](https://user-images.githubusercontent.com/88939478/141697191-ec702985-6dce-4756-877a-ae3c8f669b82.png)
5. Restarting the PC.
6. Done!
Who helped please like my git.

**Comment by Jo-Seungjun** [comment]
> rovide the logs as mentioned abo

I was having the same issue with **21H1**.
so I updated to **21H2** and the problem solved

**Comment by Jo-Seungjun** [comment]
> I also have the same situation as I am right now, maybe I guess because of the recent 21H1 update?

I was having the same issue with **21H1**.
so I updated to **21H2** and the problem solved

**Comment by SixBytesUnder** [comment]
I had this problem for a while and was able to resolve it by running below command in cmd **as admin**
```bash
sc config LxssManager start=auto
```
Alternatively click Start -> Services -> find LxssManager service and make sure Startup type is set to Automatic and the service is running.

Note, every now and again, WSL will stop working and throw `[wsl process exited with code 3221226505]` error again. Just run above command again and you're good to go.

**Comment by teaGod-s** [comment]
I had this problem for a while and was able to resolve it by running below command in cmd as admin
`wsl --update --rollback`
`wsl --shutdown`

**Comment by ErickNic** [comment]
> I had this problem for a while and was able to resolve it by running below command in cmd **as admin**
> 
> ```shell
> sc config LxssManager start=auto
> ```
> 
> Alternatively click Start -> Services -> find LxssManager service and make sure Startup type is set to Automatic and the service is running.
> 
> Note, every now and again, WSL will stop working and throw `[wsl process exited with code 3221226505]` error again. Just run above command again and you're good to go.
-----

I used this command and everything works out. I also want to add that I recently install karpersky antivirus and I quickly did all the suggestions it suggests me, so one of them apparently was disabling linux files, so its also disable lxssmanager too...
