### ISSUE TITLE
Error when starting WSL Preview (Store version) from command prompt

### ISSUE THREAD

**Issue by minusium** [microsoft/WSL#7623]
### Version

Microsoft Windows [Version 10.0.22000.282]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Other Software

WSL version: 0.48.2.0
Kernel version: 5.10.60.1
WSLg version: 1.0.29
Windows version: 10.0.22000.282

WSL1 is disabled from optional features

### Repro Steps

1) Install WSL from store
2) Install any distro, from any source
3) Start command prompt or terminal, then type wsl, you'll get the error below
![image](https://user-images.githubusercontent.com/21140798/139452509-13fe652a-f8aa-411f-a6b5-4b1d818f4f62.png)

Note: It's ok when you start WSL from Start menu, and it's ok if WSL is already running.
I mean if you start wsl from start menu and it's running already, you can start wsl from command prompt. 

### Expected Behavior

Start WSL normally

### Actual Behavior

Getting an error, and wsl won't start
![image](https://user-images.githubusercontent.com/21140798/139452509-13fe652a-f8aa-411f-a6b5-4b1d818f4f62.png)

**Comment by MatthewL246** [comment]
This looks like it might be the same problem that I am having (#7626).

**Comment by minusium** [comment]
@MatthewL246 Yes, #7626 is duplicate.
