### ISSUE TITLE
All WSL2 mac address and ip address are the same 

### ISSUE THREAD

**Issue by bingoct** [microsoft/WSL#7624]
### Version

Microsoft Windows [version 10.0.19042.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.128

### Distro Version

Ubuntu 20.04

### Repro Steps

I install three different WSL2 Distro Version on my computer.
I use `wsl --export` and `wsl --import` to remove those WSL2 release to other disk space.
Then I find all the wsl2 have the same mac and same ip, which trouble me a lot.
At first, I think this is because the random mac address of the virtual network interface card is set to the same. So I use `ip link set dev eth0 address` to set mac.
But when I modify one of them, other WSL2 mac address has also changed.
So how could I set different mac/ip address for diferent WSL2. Is it a feature of WSL2 or bug?

### Expected Behavior

different mac and different ip

### Actual Behavior

All WSL2 mac address and ip address are the same

**Comment by benhillis** [comment]
In WSL2 each distro shares the same virtual machine and same network namespace.

**Comment by poisson-fish** [comment]
should be labeled "by horrible design."
are you guys for real with this?
