### ISSUE TITLE
Error in running docker container with gpu use in WSL2

### ISSUE THREAD

**Issue by doo5643** [microsoft/WSL#7627]
### Version

Microsoft Windows [Version 10.0.19043.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Docker Engine - Community : 20.10.10
NVIDIA Driver Version: 510.06 
CUDA Version: 11.6

### Repro Steps

Error happens with `docker run --gpus all hello-world` while `docker run hello-world` works.

### Expected Behavior

Docker containers with gpu use should be available in wsl2.

### Actual Behavior

Using this command `docker run --gpus all hello-world` in wsl2, following error returns.
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0002] error waiting for container: context canceled
```

**Comment by teddybee** [comment]
Same here with the final Win10 21H2, Nvidia driver 510.x
nvidia-smi result:
`Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system`

**Comment by teddybee** [comment]
I have put on today the November update, but it seems this is not the 20H2 service pack, that is compulsory for GPU acceleration in WSL. 
My version is: Windows 10 Pro 21H1 19043.1348

**Comment by doo5643** [comment]
> 21H2

@teddybee How to update service pack to 21H2?

**Comment by teddybee** [comment]
@doo5643 I have tried to do it manually by Update Assistant, but no luck. After several BSOD on installation, I gave up.
