### ISSUE TITLE
Cannot use WSL.exe to invoke Linux commands in PowerShell

### ISSUE THREAD

**Issue by noelmcgrath** [microsoft/WSL#7628]
### Version

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Open Windows terminal
2. Open pwsh tab
3. Run `wsl.exe echo 'hello'`

### Expected Behavior

It should work and get hello back

### Actual Behavior

No result returned.

When I open powershell as admin it works, but do not want to be running powershell as admin(least privilege).
There is no mention in documentation I believe that you need to be running as admin

### Diagnostic Logs

n\a

**Comment by mtelbertbiker** [comment]
I have same issue.

**Comment by sirredbeard** [comment]
Able to reproduce. 

![image](https://user-images.githubusercontent.com/33820650/139696257-cb058c4b-717f-43af-8de5-774edcdceeb2.png)

WT 1.12.2931.0
PS 5.1.22000.282
Windows 22000.282

**Comment by mtelbertbiker** [comment]
> I have same issue.

My issue is resolved.    From Add & Remove Features, selected Windows Subsystem for Linux and clicked Uninstall, then rebooted.     Then retried wsl.exe echo 'hello', which worked!   Must have been some type of installation / update conflict.

**Comment by noelmcgrath** [comment]
My default distribution had been set to  `docker-desktop-data`  which resulted from installing docker desktop.
I swithed back to ubuntu as default and working now: w`sl --distribution Ubuntu-20.04 --user xxx`

```
wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
```

```
wsl.exe echo 'hello'
hello
```

**Comment by benhillis** [comment]
Will follow up with the docker folks to see if they can make a better error message if one of their distros gets set to the default.

**Comment by noelmcgrath** [comment]
FYI there was no error message, it just returned.  Powershell $Error was empty
