### ISSUE TITLE
Install rust on WSL of Win 11 brings Green screen of Death

### ISSUE THREAD

**Issue by kimlimjustin** [microsoft/WSL#7630]
### Version

Microsoft Windows [Version 10.0.22000.282] (It's Win 11 Insider build)

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

1. Use windows 11 insider build
2. Install Ubuntu WSL
3. Open the WSL
4. Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` to install
5. Just wait and Green Screen of Death will come up

### Expected Behavior

installing rust on WSL going smooth

### Actual Behavior

Installation of Rust went smooth on Windows 11 and Ubuntu itself, but when trying to install it on the Ubuntu subsystem of Windows 11, my computer went into Green screen of Death with the error code `MEMORY_MANAGEMENT`.

This issue is originally created on rust-lang/rustup#2887 but they ask me to open an issue here.

**Comment by sirredbeard** [comment]
Note, unable to reproduce on 22000.282. 

![image](https://user-images.githubusercontent.com/33820650/139694638-ed42e7a1-d4db-4eb7-bf40-bafff9faa2d1.png)

**Comment by benhillis** [comment]
/logs

Filing a feedback hub issue will let me search for memory dumps, so please do so.

**Comment by kimlimjustin** [comment]
done https://aka.ms/AAeqalp

**Comment by kimlimjustin** [comment]
https://user-images.githubusercontent.com/61906684/139791983-da565a45-3316-4e8e-8cf9-cb8483681651.mp4

**Comment by selfagency** [comment]
I'm encountering the same issue right now on Pengwin running Windows 11 Insider Edition Beta channel.

**Comment by NervosaX** [comment]
Just adding I encountered this error before the insider channel AND after, so I don't think it's necessarily related to one or the other.

**Comment by kimlimjustin** [comment]
Any idea to deal with this?

**Comment by DesktopECHO** [comment]
> Any idea to deal with this?

What's the output of `uname -a` on your machine running the Rust install?

**Comment by NervosaX** [comment]
In my case I was on WSL1 without realizing it. Upgrading to WSL2 has fixed the issue.

**Comment by kimlimjustin** [comment]
Oh yeah, forgot to update, some days ago, I decided to reinstall the wsl and the ubuntu subsystem, and after reinstalling, finally, it works!
