### ISSUE TITLE
Closing WSL terminal causes win32 exception

### ISSUE THREAD

**Issue by shemminger** [microsoft/WSL#7631]
### Version

Microsoft Windows [Version 10.0.22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Debian11

### Repro Steps

Closing a session under Windows Terminal gives:
An unhandled win32 exection occured in [16740] debian.exe

This is repeatable and happens every time.

### Expected Behavior

Windows terminal should just close

### Actual Behavior

Traps into Visual Studio and logs execption

### Diagnostic Logs

<lambda_3345f21c034bc71f493d11be7ec1f1aa>::<lambda_invoker_cdecl>(void)

00007FFEE59F4527  mov         rcx,qword ptr [rdi]  
00007FFEE59F452A  mov         dword ptr [rcx],eax  
00007FFEE59F452C  mov         rax,qword ptr [rdi]  
00007FFEE59F452F  mov         r9d,dword ptr [rax]  
00007FFEE59F4532  mov         rcx,qword ptr [rsp+48h]  
00007FFEE59F4537  test        r9d,r9d  
00007FFEE59F453A  jns         <lambda_3345f21c034bc71f493d11be7ec1f1aa>::<lambda_invoker_cdecl>+60h (07FFEE59F4550h)  
00007FFEE59F453C  lea         r8,[string "onecore\\vm\\wsl\\lxss\\wslapi\\laun@"... (07FFEE5A04200h)]  
00007FFEE59F4543  mov         edx,3Fh  
00007FFEE59F4548  call        wil::details::in1diag3::_Log_Hr (07FFEE59F35C8h)  
00007FFEE59F454D  mov         rax,qword ptr [rdi]  
00007FFEE59F4550  mov         rbx,qword ptr [rsp+20h]  
00007FFEE59F4555  cmp         dword ptr [rax],0  
00007FFEE59F4558  jl          <lambda_3345f21c034bc71f493d11be7ec1f1aa>::<lambda_invoker_cdecl>+8Ch (07FFEE59F457Ch)  
00007FFEE59F455A  mov         rax,qword ptr [rdi+20h]  
00007FFEE59F455E  mov         r9,qword ptr [rax]  
00007FFEE59F4561  mov         rax,qword ptr [rdi+18h]  
00007FFEE59F4565  mov         r8d,dword ptr [rax]  
00007FFEE59F4568  mov         rax,qword ptr [rdi+10h]  
00007FFEE59F456C  mov         rdx,qword ptr [rax]  
00007FFEE59F456F  mov         rcx,rbx  
00007FFEE59F4572  call        WslSession::LaunchInteractive (07FFEE59F4AA0h)

**Comment by Biswa96** [comment]
Is this only with the Debian distribution launcher?

**Comment by shemminger** [comment]
Yes, it appears to happen if started from the distro launcher into windows terminal.
But not from Windows terminal icon

**Comment by benhillis** [comment]
We have a fix for the crash in wslapi.dll that is slated to go out during November 2021.
