### ISSUE TITLE
Pip doesn't work within a conda env, always times out

### ISSUE THREAD

**Issue by hhlei** [microsoft/WSL#7637]
### Version

Version 1909 OS Build 18363.1556

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

Conda 4.10.3
Pip 21.1.3

### Repro Steps

Install Miniconda
conda create -n test python=3.7.10 pip
conda activate test
pip install pip-install-test

### Expected Behavior

should pip install the package

### Actual Behavior

Pip fails. Error seems to be a timeout error, but I've tried increasing the default timer and it still fails. I've disabled my antivirus and windows defender, but it still fails. Please help, I'm at my wit's end trying to set up environments on windows/wsl and it is so frustrating that this basic functionallity doesn't work properly.

pip install pip-install-test
Errors:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
ERROR: Could not find a version that satisfies the requirement pip-install-test (from versions: none)
ERROR: No matching distribution found for pip-install-test

pip install pip-install-test -v
Using pip 21.1.3 from /home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-kucpy7qq
Created temporary directory: /tmp/pip-req-tracker-3h7vo130
Initialized build tracking at /tmp/pip-req-tracker-3h7vo130
Created build tracker: /tmp/pip-req-tracker-3h7vo130
Entered build tracker: /tmp/pip-req-tracker-3h7vo130
Created temporary directory: /tmp/pip-install-5cs7a66e
1 location(s) to search for versions of pip-install-test:
* https://pypi.org/simple/pip-install-test/
Fetching project page and analyzing links: https://pypi.org/simple/pip-install-test/
Getting page https://pypi.org/simple/pip-install-test/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip-install-test/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/pip-install-test/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/pip-install-test/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/pip-install-test/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/pip-install-test/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/pip-install-test/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip-install-test/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip-install-test/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip-install-test/ (Caused by ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")) - skipping
Skipping link: not a file: https://pypi.org/simple/pip-install-test/
Given no hashes to check 0 links for project 'pip-install-test': discarding no candidates
ERROR: Could not find a version that satisfies the requirement pip-install-test (from versions: none)
ERROR: No matching distribution found for pip-install-test
Exception information:
Traceback (most recent call last):
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('pip-install-test')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pip-install-test'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/hhlei/miniconda3/envs/test1/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pip-install-test
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Fetching project page and analyzing links: https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=5)")) - skipping
Skipping link: not a file: https://pypi.org/simple/pip/
Given no hashes to check 0 links for project 'pip': discarding no candidates
Removed build tracker: '/tmp/pip-req-tracker-3h7vo130'

**Comment by hamind** [comment]
hello, I have the same question. Have you solved this?

**Comment by tirelesskoriel** [comment]
I have the same question
