### ISSUE TITLE
Unable to reach Microsoft OAuth endpoint within Docker

### ISSUE THREAD

**Issue by spencerericfong** [microsoft/WSL#7639]
### Version

Microsoft Windows [Version 10.0.19042.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64

### Distro Version

Ubuntu 20.04 LTS

### Other Software

Docker Desktop (Windows), version 4.1.1 [69879]
Python 3.9

### Repro Steps

1. Set up new Docker container with Python 3.9
2. Install MSAL for Python: https://github.com/AzureAD/microsoft-authentication-library-for-python
2. Import ConfidentialClientApplication in .py script
3. Call `ConfidentialClientApplication(
            client_id,
            client_credential=client_secret,
            authority=API_OAUTH_AUTHORITY
)
`

### Expected Behavior

Receive the following prompt: `To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXX to authenticate.`

### Actual Behavior

Exit out to tracebacks, all of which cite `Failed to establish a new connection: [Errno -5] No address associated with hostname'` at terminus. Full traceback logs attached below.

### Diagnostic Logs

[error_text.txt](https://github.com/microsoft/WSL/files/7470853/error_text.txt)
[error_traceback.txt](https://github.com/microsoft/WSL/files/7470854/error_traceback.txt)

**Comment by spencerericfong** [comment]
Also please note that this issue only occurs within a Docker container; when running the same script within a Python venv, there is no issue reaching the endpoint.

**Comment by OneBlue** [comment]
Hi @spencerericfong, thanks for reporting this.

This looks like a DNS issue, can you share the content of /etc/resolv.conf, and the output of `nslookup login.microsoftonline.com` ?
