### ISSUE TITLE
can't connect to localhost ::1 servers

### ISSUE THREAD

**Issue by jpmorrison** [microsoft/WSL#7641]
### Version

Microsoft Windows [Version 10.0.19043.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Windows etc/hosts
::1     www.myserver.com

Ubuntu wsl2:
socat tcp6-listen:9443 -

netstat -na
tcp6       0      0 :::9443                 :::*                    LISTEN

Windows:

telnet ::1 9443
Connecting To ::1...Could not open connection to the host, on port 9443: Connect failed

This was working until I rebooted with BSOD. 
Using ::1 was my workaround because 127.0.0.1 has *never* worked as advertised

telnet 172.x.x.x 9443  works but this IP changes randomly

### Expected Behavior

working tcp connection to 127.0.0.1 or ::1  

### Actual Behavior

telnet ::1 9443
Connecting To ::1...Could not open connection to the host, on port 9443: Connect failed

telnet www.myserver.com  9443
Connecting To www.myserver.com...Could not open connection to the host, on port 9443: Connect failed

**Comment by OneBlue** [comment]
Hi @jpmorrison, thanks for reporting this.

This is expected because WSL2 doesn't support IPV6 right now.

**Comment by jpmorrison** [comment]
It was was also failing with ipv4 127.0.0.1
