### ISSUE TITLE
Win32 apps launched via interop lack taskbar icons in Win11

### ISSUE THREAD

**Issue by 0xabu** [microsoft/WSL#7645]
### Version

Microsoft Windows [Version 10.0.22000.282]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

Since updating to Windows 11, I've noticed that Win32 applications launched from WSL via interop lack their usual taskbar icons.

(It could be argued that this is a regression in the taskbar, but it's also somehow unique to WSL and I didn't already see it reported here.)

### Expected Behavior

When launching an app from cmd.exe:
```
C:\Users\me\AppData\Local\SumatraPDF>SumatraPDF.exe
```

Taskbar shows as normal:
![image](https://user-images.githubusercontent.com/13037682/140557942-032a8738-2634-4012-85a8-990c92878fc3.png)

### Actual Behavior

When launching the same exe in the same directory via WSL interop:
```
 ~/AppData/Local/SumatraPDF $ ./SumatraPDF.exe
```

Taskbar shows:
![image](https://user-images.githubusercontent.com/13037682/140558034-29011a8f-0d2b-416c-8681-2552fea9471e.png)

**Comment by 0xabu** [comment]
Confirmed repro in WSL2, and updated description.

**Comment by benhillis** [comment]
@0xabu - no repro for me on 22489 or 22000, I tried notepad.exe, explorer.exe, and vscode.

**Comment by 0xabu** [comment]
@benhillis I think it needs to be a standalone exe. Try msinfo32.exe

**Comment by 0xabu** [comment]
I'm guessing the others you tried are all special, in that the exe you run from interop isn't directly responsible for the window that appears. (notepad surprises me, but I see the same thing.)

**Comment by benhillis** [comment]
msinfo32.exe also works.

**Comment by benhillis** [comment]
In any case, we're just calling CreateProcess, nothing special.  Smells like a shell bug.

**Comment by 0xabu** [comment]
Really? Huh. It's 100% reliable repro for me on 22000.282

![image](https://user-images.githubusercontent.com/13037682/140580116-7b25c345-bf37-4760-9506-b5bb521a23f6.png)

Left is msinfo32.exe via interop, right is from cmd.

**Comment by 0xabu** [comment]
I filed a feedback bug against taskbar: https://aka.ms/AAerscz

**Comment by benhillis** [comment]
My test machine is on 22000.194, I'll install updates and try again.

**Comment by benhillis** [comment]
No repro on 22000.258 rebooting again ;)

**Comment by 0xabu** [comment]
Also no repro on a different user's 22000.258. It may be something about my taskbar, or it may be .282

**Comment by benhillis** [comment]
No repro for me on .282 either, strange.

**Comment by benhillis** [comment]
Maybe your icon cache is corrupted?

**Comment by 0xabu** [comment]
I tried another machine I had handy, where I went through a similar set of upgrade steps to Win11 then .282, with no repro before or after the .282 update. So it's something about this specific machine/config. (I also tried clearing the icon cache and restarting explorer, with no changes.)

**Comment by 0xabu** [comment]
Since a recent update, apps are now appearing with the new WSL logo:
![image](https://user-images.githubusercontent.com/13037682/143484780-8f4b6538-376d-4c9b-9c9d-a8eb93cca258.png)

I've also noticed that unrelated win32 apps launched from WSL are all grouped together on the taskbar as one group, so it seems to be picking up the WSL launcher process and using that for the taskbar icons. The mystery of why it repros only on one device remains, however.
