### ISSUE TITLE
WSL 2 read access significantly slower since update to WIndows 11

### ISSUE THREAD

**Issue by k-risc** [microsoft/WSL#7650]
### Version

Version	10.0.22000 Build 22000

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 4.1.1 (69879)
PhpStorm 2021.2.3 (but also previous versions)

### Repro Steps

1. Copy a folder from the Ubuntu on WSL 2 distro to Windows
2. Open a project residing on the Ubuntu WSL 2 distro in PhpStorm (installed under Windows)
3. Work on a project residing on the Ubuntu WSL 2 distro in PhpStorm
34 Open a file (or files) from the Ubuntu WSL 2 distro in Notepad++
5. Run a job in Cobian Backup which is supposed to backup a folder from the Ubuntu WSL 2 distro to some where else
6. Copy a folder from Windows to the Ubuntu distro on WSL 2

### Expected Behavior

For all of the four items, to work as fast as when Windows 10 was installed.

### Actual Behavior

1. Copying a folder is extremely slow, the Windows copy dialog is not able to calculate the estimated time for a long while, and files are copied in a very slow manner, but often it seems that nothing happens at all.
2. It takes a very long time until one can start actually working in PhpStorm, because "Opening components" and "Opening files" takes very long.
3. Saving files let's PhpStorm hang, and if the same file is open somewhere else (e.g. in Notepad++), it takes a long time until the changes are reflected there.
4. Sometimes takes very long, e.g. opening one not massively huge text file takes more than 10 second.
5. Takes much, much longer than before. In fact since the update to Windows 11, I have not managed to backup a folder on WSL 2 to somewhere else since the update.
6. This actually goes as fast as usual

**Comment by k-risc** [comment]
Deactivating Avira Personal Antivir seems to help.

**Comment by OneBlue** [comment]
Unfortunately antivirus slowing down WSL is a know issue, and it's not something that WSL can do anything about.

Closing given that deactivating the antivirus seems to resolve the issue.

**Comment by Biswa96** [comment]
> Unfortunately antivirus slowing down WSL is a know issue

Windows Defender too... 😥

**Comment by k-risc** [comment]
But using the same Antivirus software under Windows 10, there was no such delay. Or if there was some, it was much smaller. After updating to Windows 11 this started to be significantly slower.
Also, no when using Microsoft Defender, it is much faster again.

So something must have changed from Windows 10 to Windows 11...

**Comment by Hessam-Koucheki** [comment]
I had this issue also, I put the LINUX\DEBIAN folder into the whitelist of my Avast Antivirus, I guess it helps a little.
I also switch my ohmyzsh theme from "robbyrussell" to "sunrise", and it seems to work fast again. however it is slow in folders containig VirtualEnv of python... Hope it fix in future updates...

**Comment by nojitsi** [comment]
Adding root wsl folder to windows defender excludion list helped a lot after restart.
Win 11, WSL2, Ubuntu 20.04, Zsh, Powerlvl10K.
Input lag is gone completely.

**Comment by throwable-one** [comment]
Unfortunately, issue still exists in W11, see https://github.com/microsoft/WSL/issues/9430

**Comment by eperrichon** [comment]
2 days lost searching about this : adding WSL distro root folder to Avira Exclusion list totally help. Thanks !

**Comment by rafaeloledo** [comment]
> Adding root wsl folder to windows defender excludion list helped a lot after restart. Win 11, WSL2, Ubuntu 20.04, Zsh, Powerlvl10K. Input lag is gone completely.

I've done that in Kaspersky exclusions and seems to be working. The file explorer was struggling when using yt-dlp+aria2 to download a playlist.
ArchWSL, W11, fish, tide.

**Comment by vicentematus** [comment]
> > Adding root wsl folder to windows defender excludion list helped a lot after restart. Win 11, WSL2, Ubuntu 20.04, Zsh, Powerlvl10K. Input lag is gone completely.
> 
> I've done that in Kaspersky exclusions and seems to be working. The file explorer was struggling when using yt-dlp+aria2 to download a playlist. ArchWSL, W11, fish, tide.

The path corresponding to the root of WSL should be like  `\\wsl.localhost\` right?

**Comment by rafaeloledo** [comment]
> > > Adding root wsl folder to windows defender excludion list helped a lot after restart. Win 11, WSL2, Ubuntu 20.04, Zsh, Powerlvl10K. Input lag is gone completely.
> > 
> > 
> > I've done that in Kaspersky exclusions and seems to be working. The file explorer was struggling when using yt-dlp+aria2 to download a playlist. ArchWSL, W11, fish, tide.
> 
> The path corresponding to the root of WSL should be like `\\wsl.localhost\` right?

Yes, but i experiencied some slowed chargins of files in explorer eve after creating this exception. I don't know why struggle sometimes, i just restart the explorer task on task manager.

**Comment by dvdknaap** [comment]
what a waste of time is wsl, ti's to slow to do anything with it!

**Comment by oomek** [comment]
WSL2 on automount drives is 3x slower than it was on WSL1.
Will this ever be fixed?
