### ISSUE TITLE
Fresh install didn't install/enable/prompt about Hyper-V

### ISSUE THREAD

**Issue by tianon** [microsoft/WSL#7651]
### Version

```console
PS C:\Users\Tianon> wsl --version
WSL version: 0.48.2.0
Kernel version: 5.10.60.1
WSLg version: 1.0.29
Windows version: 10.0.22000.282
```

### WSL Version

- WSL 2

### Other Software

- None :smile:

### Repro Steps

I did a completely fresh install of Windows 11, and the very first application I installed (before literally anything else) is Windows Subsystem for Linux Preview from the Microsoft Store.

After doing so, I did `wsl --install Debian`, which successfully downloaded, installed, and tried to start Debian.

### Expected Behavior

I expected WSL to enable Hyper-V for me when I installed it from the store, when I installed Debian (before it tried to run it), or at least tell me that I should go do so such that it would work seamlessly when I tried to use it. :smile:

### Actual Behavior

I was greeted with the following when Debian tried to start:

```console
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 The operation could not be started because a required feature is not installed.
```

I then went into the Windows optional features and enabled the `Hyper-V Platform` manually, which forced a reboot.  After doing so, launching Debian worked just fine and prompted me to initialize with a username/password appropriately.

**Comment by tianon** [comment]
(This might be the same problem as https://github.com/microsoft/WSL/issues/7638)

**Comment by benhillis** [comment]
Thanks for the feedback, we're working with the Store team to help make this experience better.

**Comment by osde8info** [comment]
still an issue with 22H2 :(

wsl install does NOT auto enable "Virtual Machine Platform" and / or "Windows Subsystem for Linux"

**Comment by Sekker007** [comment]
For me this worked:
*open the Windows PowerShell with administrator privileges
*Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

type "y" for yes, restart.

**Comment by Himanshu-holmes** [comment]
good

**Comment by tianon** [comment]
Ooh, it looks like this might be fixed in that latest release? 👀
(I have not tested, but the release notes rang a bell in my head!)

> Install missing optional components if needed in wsl.exe --install

https://github.com/microsoft/WSL/releases/tag/1.3.10

**Comment by tianon** [comment]
That's pretty contributor hostile and encourages "+1 me too" style spammy comments 🫤

I did happen to do a new WSL install recently and it didn't enable Hyper-V for me, but it did suggest that I would likely need to do so, which is fair enough.
