### ISSUE TITLE
Cannot launch WSL using a non admin user account in Windows 11 Home edition

### ISSUE THREAD

**Issue by vranjan2** [microsoft/WSL#7653]
I just upgraded to windows 11 home edition. I have setup my machines as one admin account and many user accounts. Within the admin account I installed WSL 2. Then I switch to my non-admin user account. Launch windows terminal. I do not see any way to start a WSL ubuntu. I can do this in the admin account though. 

Is this the expected behavior? Or there is a way I can launch wsl within my non-admin user account?

**Comment by benhillis** [comment]
Yes this is expected, WSL distros are per-user.

**Comment by vranjan2** [comment]
Is there a way I can run wsl with ubuntu from non admin user account? I am not able to find any documentation on this.
