### ISSUE TITLE
WSL completely stuck after KB5007215

### ISSUE THREAD

**Issue by InPhoenity** [microsoft/WSL#7661]
### Version

10.0.22000.318

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 4.0.1

### Repro Steps

Just run any WSL command (except --help)

### Expected Behavior

I expect to be able to list the installation or launch one

### Actual Behavior

Nothing happen, it just hang

![2021-11-10_05-11-59](https://user-images.githubusercontent.com/64818122/141048316-988d2c25-4541-4af9-856b-5d7b995272fb.png)
.

**Comment by InPhoenity** [comment]
I have already tested almost all the solution suggested in similar kind of problem.
Even installing a new distribution doesn't work.

**Comment by hootanht** [comment]
similar problem

![](https://user-images.githubusercontent.com/27281206/141050001-c2a8bba7-2f77-41a7-940d-71dc06f5573a.png)

**Comment by InPhoenity** [comment]
Complementary Feedback : I have removed everything, unregister all instance, uninstall WSL, uninstall Docker Desktop, reinstall WSL. Command wsl -l works fine until I am adding a first distribution. And then, once again, everything hang...

**Comment by jackL999** [comment]
I have exactly the same issue after updating Windows 10 21H1 with KB5007186.

**Comment by catchin** [comment]
I have the same issue after the KB5007215 update. Typing e.g. `wsl` takes ~5-10 minutes to complete and shows an error that the Server failed to start. When uninstalling the mentioned update, wsl works again.

I submitted the logs via Feedback Hub before uninstalling the KB5007215 update. Unfortunately it did not show a link that I can provide you with. However, I published it around 25 minutes ago and included the github issue in the description, so you may find it?

**Comment by prathapk1990** [comment]
didn't see this thread before raising this  🤦 
https://github.com/microsoft/WSL/issues/7692

**Comment by catchin** [comment]
I uninstalled the mentioned update. After this, wsl started again. Windows automatically installed the KB update some time later and wsl still starts after reboot. So uninstalling and reinstalling fixed the issue for me.

Did someone try this as well and did it fix the issue?

**Comment by nextkara** [comment]
remove update ,
and restart, 
it's work!

**Comment by Stanzilla** [comment]
Had this as well, also my Ubuntu user dir was gone. A restart (without reverting the update) fixed it here.

**Comment by anandbhaskaran** [comment]
I have the same problem and you can access the logs here: https://aka.ms/AAew9os

**Comment by anandbhaskaran** [comment]
By the way, can someone tell me how can I uninstall a update. For me Windows 11 Insider Preview 22504.1000 (rs_prerelease) broke the WSL
