### ISSUE TITLE
Unable to update WSL2 kernel

### ISSUE THREAD

**Issue by rmcmilli** [microsoft/WSL#7668]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

`wsl --update`

Inside of Ubuntu 20.04:  `uname -rp`

### Expected Behavior

The kernel version in WSL2 should match 

```
wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.60.1
```

```
User:~$ uname -rp 
 5.10.60-microsoft-standard+ x86_64 
```

Or something similar

### Actual Behavior

Kernel in Ubuntu does not update. 

```
wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.60.1
```

```
User:~$ uname -rp 
 4.19.72-microsoft-standard+ x86_64 
```

**Comment by owenschupp** [comment]
Are you using the Windows Store version of WSL2? Also, is this still an issue? I tried reproducing it on my end but did not run into an issue

**Comment by rmcmilli** [comment]
This turned out to be an issue on my install. I had an alternate kernel installed.
