### ISSUE TITLE
Unable to open Ubuntu GUI program from start menu

### ISSUE THREAD

**Issue by gh565923562** [microsoft/WSL#7671]
### Version

Microsoft Windows [version 10.0.22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

All GUI programs cannot be opened from the windows start menu, 
but you can open the graphical interface in bash.

### Repro Steps

windows start menu -> Text Editor (Ubuntu-20.04)  ->  no response

cmd C:\Windows\System32\wslg.exe  ->  no response

cmd C:\Windows\System32\wslg.exe ~ -d Ubuntu-20.04 gedit  ->  no response

bash gedit  ->  Successfully opend

### Expected Behavior

Open the graphical interface from the start menu.

### Actual Behavior

no response

**Comment by tare2M** [comment]
Me too 
I can't open the GUI apps whatsoever
