### ISSUE TITLE
/proc/net/unix missing

### ISSUE THREAD

**Issue by PrismaComputer** [microsoft/WSL#7677]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Look into '/proc/net'.
You'll see 'unix' is missing.

### Expected Behavior

/proc/net/unix must be present for several software products. 

### Actual Behavior

/proc/net/unix is missing

**Comment by Biswa96** [comment]
It exists in my setup running Windows 10 19043.

**Comment by PrismaComputer** [comment]
At the moment, I installed Ubuntu 20.04, Kernel 5.10.60.1 was NOT running. As far as I can remember, it's been 4.4, but not for sure.
I upgraded the Kernel manually later with "wsl.exe --update".

Could this make the difference?
And if yes, is it possible to get /proc/net/unix in retrospect? Would be bad to have to completely re-install 20.04 app from store.

**Comment by Biswa96** [comment]
> As far as I can remember, it's been 4.4, but not for sure.

The 4.4.0 version is from WSL1 which is emulated. Check if the distribution is in WSL2 environment.

**Comment by PrismaComputer** [comment]
![image](https://user-images.githubusercontent.com/9677018/141487294-1471c549-5479-4ea1-8b4e-d668dedc0444.png)

As I said, not sure if it's been exactly 4.4. If you say it's not possible, then so it is. Then it's been another version.

So let me ask again and in another way:
Is it possible that the behaviour is a result of having installed an older kernel before?
And if yes, is it possible to re-initialize /proc without having to re-install the app?

**Comment by Biswa96** [comment]
Not sure. What does `uname -r` show in that distribution?

**Comment by PrismaComputer** [comment]
> 4.4.0-19041-Microsoft

What the heck happend?

**Comment by Biswa96** [comment]
The WSL distribution is in WSL1 state. You have to convert it to WSL2 with `wsl --set-version` command. You can find more information here https://docs.microsoft.com/en-us/windows/wsl/basic-commands

**Comment by PrismaComputer** [comment]
This did the trick. Thank you so much. I'm an IT pro and I hate bothering you with such easy stuff. This shouldn't have happened. Sorry for that.
It's completely unclear why the environment was in this state. The PC is rather new and came with Win 10 1909 but is now upgrade to 21H1. May migration from 1909 be the reason? Or did I something wrong while downloading Ubuntu from store?
Are there different Ubuntu 20.04 versions in the store?

**Comment by Biswa96** [comment]
> May migration from 1909 be the reason?

I don't assume that. WSL1 is default in a clean install Windows until someone runs `wsl --set-default-version 2`. Or manually set that in registry.

> Are there different Ubuntu 20.04 versions in the store?

There are different Ubuntu versions in Windows Store. But those are only LTS versions.

**Comment by PrismaComputer** [comment]
wsl.exe --status says "default version: 2". Please see above screenshot. In German it's "Standardversion: 2".

Therefore we have no explanation for the observed behaviour. But a solution. Next time I'll know what to check first.

Thank you again. I'll close this (non-)issue.
