### ISSUE TITLE
Windows won't boot after installing WSL

### ISSUE THREAD

**Issue by DPorichis** [microsoft/WSL#7678]
### Version

Windows 10

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

preseted

### Distro Version

preseted

### Repro Steps

Used the wsl --install command to download wsl to my HP laptop

### Expected Behavior

Booting Machine

### Actual Behavior

After the restart, I have been experiencing blue screens before boot. This is the second time I am trying to install and the first time I thought it was a coincidence. Please help me resolve this issue.

**Comment by OneBlue** [comment]
Thanks for reporting this @DPorichis. Can you share a kernel dump / minidump ?

**Comment by JeightAn** [comment]
I'm having same problem. After I used wsl --install on my LG notebook (Windows 10 Home edition), I'm experiencing blue screens again and again.

**Comment by DPorichis** [comment]
Unfortunately, I had to work, so I reinstalled windows all over again. I don't have the kernel dump file.
I have not tried reinstalling wsl for fear of a new windows crush.
