### ISSUE TITLE
Unable to start linux environment using wsl

### ISSUE THREAD

**Issue by CCCCC7** [microsoft/WSL#7679]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Not possible

### Repro Steps

I open CMD, type wsl and recieve this error. An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

### Expected Behavior

It should startup my default distro which would be kali-rolling. 

### Actual Behavior

When I am able to start kali through the windows start menu it starts but no commands are able to be done since it cant mount or find my filesystem for some odd reason...

**Comment by owenschupp** [comment]
Can you provide any logs/could you provide output of `wsl -e dmesg`? /logs
