### ISSUE TITLE
USBC external card reader support

### ISSUE THREAD

**Issue by HongKongFooey78** [microsoft/WSL#7684]
I am trying to create a Yocto image for booting a Variscite imx8m mini evaluation board but I can't seem to copy and paste image files from WSL to windows.  I have tried copy and paste within windows explorer via \\wsk$ and cp or mv to the appropriate folder via mnt/.  I would therefore love it if it was possible for my USBc external sd card reader to be able to be mounted un WSL2 Ubuntu 18.04 running in windows 11 so that I can create a boot disk directly from within WSL.  I have dome a bit of reading into this and it seems that USB devices are not supported.  I certainly can't fine mine via al the appropriate commands in WLS (eg lsblk/lsusb).

**Comment by OneBlue** [comment]
Hey, attaching USB devices is documented [here](https://docs.microsoft.com/en-us/windows/wsl/connect-usb)
