### ISSUE TITLE
WSL2 - fstab nofail is ignored, terminal won't start - The Windows Subsystem for Linux instance has terminated.

### ISSUE THREAD

**Issue by veqryn** [microsoft/WSL#7685]
### Version

10.0.19043.1288

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

20.04

### Repro Steps

Create an fstab entry to a valid NFS, including `nofail`:
`192.168.xx.xx:/volume1/mynfs /mnt/mynfs nfs defaults,nofail,x-systemd.automount,x-systemd.mount-timeout=30,_netdev 0 0`

Confirm it work by completely shutting down wsl then bring it back up. Everything is great.

Now shut down wsl again, and turn off the NFS (ie: disable your NAS or whatever is serving your NFS) or disconnect yourself from the network.

Try to start wsl terminal, and it fails.

### Expected Behavior

`nofail` should let wsl ignore the fstab entry if it is having problems.
I should be able to start WSL2 when my laptop is not at home on the same network as my NFS, and have it work.  I should also be able to automount an NFS when I am at home.

### Actual Behavior

![wsl_terminated](https://user-images.githubusercontent.com/1897829/141629221-22452173-0c92-4bd8-8423-6c9a60d8ffbc.png)

**Comment by veqryn** [comment]
Feedback submitted through the hub as per the instructions.
The recording shows me changing my `/etc/fstab` entry from `noauto` to `nofail`, then stopping wsl, connecting to my Cisco VPN (just one of many ways to show this, I could also show the same by turning off my wifi, or leaving the house with my laptop), then trying to start the Ubuntu terminal (which fails). Then I disconnect from the VPN and show that my Ubuntu works again.

**Comment by 5had3z** [comment]
I have found the same issue, either using my VPN or turning off networking results in WSL failing to start. Commenting out the nfs line in /etc/fstab results in wsl loading with no issues with VPN or no networking. Same use case for me, I'd like to auto mount my home nfs if its available, and be able to start up as usual if its not available.

**Comment by OneBlue** [comment]
@veqryn : Can you please share the feedback hub link to your feedback or follow the [record WSL logs manually section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually)  and attach the .etl file on this issue ?

**Comment by veqryn** [comment]
@OneBlue if you aren't logged in to Windows with a Windows online account (ie: outlook.com), instead of a local account, then feedback hub will not give you a link. Instead it will just say success and that is the end of it. You will have to search through feedback hubs bug reports or whatever manually.

**Comment by OneBlue** [comment]
Ok in that case please follow the [Record WSL logs manually section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) and share the .etl file here so I can look at it.

**Comment by veqryn** [comment]
Can you look it up please? I already submitted it once, and I am not sure I have time to do it again right now

**Comment by OneBlue** [comment]
I have no way to find those logs unless I have the feedback hub link. If you can't get the link collecting logs manually is the only solution

**Comment by veqryn** [comment]
So when I submit everything through the feedback hub, completely following the directions provided, and it says Success, but doesn't provide a link, where has the bug report and logs gone to?
This is probably the 3rd bug report I've submitted with the feedback hub, and it has never given me a link, I assume because I have no 'microsoft' account.

**Comment by OneBlue** [comment]
If Feedback hub didn't give you link, please follow the [Record WSL logs manually section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) instead .

**Comment by veqryn** [comment]
Keep open

**Comment by veqryn** [comment]
re-open
