### ISSUE TITLE
wslconfig being ignored

### ISSUE THREAD

**Issue by ejones12** [microsoft/WSL#7687]
### Version

Microsoft Windows [Version 10.0.19043.1348] 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 18.04

### Repro Steps

I am attempting to increase the amount of memory allocated to my wsl instance in order to run some benchmarking tests. I have created a .wslconfig file (Located at: C:\Users\"my username"\.wslconfig) and changed the allowed memory to 20GB, but these changes are being ignored. I was able to increase the memory size to 16GB once, but it has not be able to change since.

### Expected Behavior

![wslconfig pic](https://user-images.githubusercontent.com/49533066/141654002-4e95be1f-fc8f-4999-a8a4-25ebd8492920.PNG)
Here I have updated my .wslconfig file to allow for 20GB of memory, but this is not being properly updated.

### Actual Behavior

![output](https://user-images.githubusercontent.com/49533066/141654020-781fb365-6e0e-4734-862d-2d8722c6a0b0.PNG)
When running the free -h command, only 15G has been allocated. I have tried shutting down wsl, restarting the LxssManager, and deleting the .wslconfig file, but nothing has seemed to chnage this issue. If anyone has any suggestions on how to fix this issue, I would greatly appreicate it.

**Comment by zachradtka** [comment]
I am running into the same issue. Did you have a solution for this?

**Comment by Carnageous** [comment]
Same issue with docker desktop on windows - takes up 20 gigs of ram, no matter how much I set in .wslconfig.

**Comment by zachradtka** [comment]
I found in another thread, sorry I don't have the link, that the files `.wslconfig` must be a UTF-8 file without the BOM. Once I converted my file to that encoding it worked.
