### ISSUE TITLE
WSL2 on windows 11 wont start after 12/11/21 insider update

### ISSUE THREAD

**Issue by prathapk1990** [microsoft/WSL#7692]
### Version

Microsoft Windows [Version 10.0.22000.346]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Any

### Other Software

had Docker Desktop running with wsl, un installed it

### Repro Steps

* I did an update on 12/11/21 via insider beta, attached screenshot for update pack.
* Restarted PC

WSL service won't start.

I know this is very vague, but that all I got unfortunately. :(

![image](https://user-images.githubusercontent.com/26737757/141675026-2fbf9269-ab43-4141-a803-b72ef1591a85.png)

### Expected Behavior

WSL service to work

### Actual Behavior

** WSL won't start after upgrade followed by a restart.

I tried to solve this issue by following various suggestion on similar forums. nothing worked.

* Restarted LxssManager
* disable/restart --> enable/restart wsl, hyper-v features.
*  enable dns-cache
*  uninstall docker-desktop

```
* Can't dir this file , but it is on directory. checked it


PS C:\WINDOWS\system32> dir %windir%\System32\p9np.dll
dir : Cannot find path 'C:\WINDOWS\system32\%windir%\System32\p9np.dll' because it does not exist.
At line:1 char:1
+ dir %windir%\System32\p9np.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\syst...stem32\p9np.dll:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

PS C:\WINDOWS\system32> reg query HKLM\SYSTEM\CurrentControlSet\Control\NetworkProvider /s

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\HwOrder
    PROVIDERORDER    REG_SZ    P9NP,RDPNP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    PROVIDERORDER    REG_SZ    P9NP,RDPNP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\ProviderOrder
    LanmanWorkstation    REG_DWORD    0x7d0
    P9NP    REG_DWORD    0x1f4
    RDPNP    REG_DWORD    0x3e8
    webclient    REG_DWORD    0xbb8

PS C:\WINDOWS\system32> reg query HKLM\SYSTEM\CurrentControlSet\Services\p9np /s

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9np
    Description    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-101
    DisplayName    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-100

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9np\NetworkProvider
    DeviceName    REG_SZ    \Device\P9Rdr
    DisplayName    REG_EXPAND_SZ    @%systemroot%\system32\p9np.dll,-100
    Name    REG_SZ    Plan 9 Network Provider
    ProviderPath    REG_EXPAND_SZ    %SystemRoot%\System32\p9np.dll
    TriggerStartCompleteNotification    REG_BINARY    7510BCA3541EC641
    TriggerStartNotification    REG_BINARY    7508BCA3541EC641
    TriggerStartPrefix    REG_SZ    wsl$

PS C:\WINDOWS\system32> reg query HKLM\SYSTEM\CurrentControlSet\Services\p9rdr /s

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\p9rdr
    DependOnService    REG_MULTI_SZ    RDBSS
    Description    REG_SZ    @%SystemRoot%\System32\drivers\p9rdr.sys,-101
    DisplayName    REG_SZ    @%SystemRoot%\System32\drivers\p9rdr.sys,-100
    ErrorControl    REG_DWORD    0x1
    ImagePath    REG_EXPAND_SZ    System32\drivers\p9rdr.sys
    Start    REG_DWORD    0x3
    Type    REG_DWORD    0x1

```

![image](https://user-images.githubusercontent.com/26737757/141675068-d98c1bab-69f1-428b-bec0-aabcf153f81e.png)

### Diagnostic Logs

https://aka.ms/AAeu37j

**Comment by OneBlue** [comment]
Based on the logs, the issue is:
HcnCreateNetwork {"Success":false,"Error":"The service has not been started. ","ErrorCode":2147943462}

So the issue comes from the HostNetworkService, which we use to setup networking.
 Here it looks like one of its dependent services fail to start, but not sure which one.

**Comment by Keith-Mange** [comment]
What does "sc.exe qc hns" show?  It will show the dependent services.  Are they are all started?

**Comment by prathapk1990** [comment]
too late, unfortunately I had re install windows.  :(

**Comment by Keith-Mange** [comment]
What does "sc.exe qc hns" show? Is it started?  How the dependent services?  If it's a problem with HNS this will collect more useful information  [collectlogs.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1).
