### ISSUE TITLE
File not appearing on mount in Linux, some directories are there

### ISSUE THREAD

**Issue by Danack** [microsoft/WSL#7693]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 20.04 LTS

### Other Software

Docker Desktop 2.3.0.2 (45183)

### Repro Steps

i. Turn on computer and boot to windows.

ii. Start Ubuntu LTS 20.04

iii. run `cd /mnt/e/projects` then `ls -l`

### Expected Behavior

All the files that exist in the directory E:/projects are listed in the Ubuntu directory /mnt/e/projects. 

### Actual Behavior

Since about 2 weeks ago about half the time I boot Ubuntu none of the files are there, and only a few directories are listed. 

Shutting the WSL subsystem down with `wsl --shutdown` and then starting Ubuntu again normally fixes the problem. Sometimes it takes two restarts.

Additionally it seems that docker on ubuntu has failed to start properly and needs to be restarted.

output of ls in ubuntu
![image](https://user-images.githubusercontent.com/1505719/141678640-92c23021-fc6c-42b9-aeb7-64d0c29e3579.png)

Directory in Explorer
![image](https://user-images.githubusercontent.com/1505719/141678622-c16e3ac6-02e8-45fa-85ac-f5a901b85a5f.png)

### Diagnostic Logs

Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType              Model                   Name                Partitions
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE1  IDE            TRUE         Fixed hard disk media  SanDisk SSD PLUS 480GB  \\.\PHYSICALDRIVE1  1
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media  SanDisk SSD PLUS 480GB  \\.\PHYSICALDRIVE0  3
              {3, 4}        {"Random Access", "Supports Writing"}                        \\.\PHYSICALDRIVE2  SCSI           TRUE         Fixed hard disk media  INTEL SSDPEKKW256G7     \\.\PHYSICALDRIVE2  1

**Comment by benhillis** [comment]
Could you please share the output of `cat /proc/self/mountinfo`?

**Comment by Danack** [comment]
Apparently, no I can't as the issue seems to have gone away.

Anecdotally, my C drive was running low on space (5GB left) so I did a `docker system prune` which recoved about 10GB.

Since I did that, I haven't seen the problem again.

**Comment by Danack** [comment]
Seeing this happen again, after a few months so re-opening.

> Could you please share the output of cat /proc/self/mountinfo?

Sure.

```
$ cat /proc/self/mountinfo
1095 920 8:64 / / rw,relatime - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
1096 1095 0:18 / /mnt/wsl rw,relatime shared:1 - tmpfs tmpfs rw
1102 1096 8:32 /isocache /mnt/wsl/docker-desktop-data/isocache rw,relatime shared:2 - ext4 /dev/sdc rw,discard,errors=remount-ro,data=ordered
1103 1096 8:32 /version-pack-data /mnt/wsl/docker-desktop-data/version-pack-data rw,relatime shared:3 - ext4 /dev/sdc rw,discard,errors=remount-ro,data=ordered
1126 1096 0:48 /guest-services /mnt/wsl/docker-desktop/shared-sockets/guest-services rw,nosuid,noexec,noatime shared:4 - tmpfs none rw,mode=755
1127 1096 0:48 /host-services /mnt/wsl/docker-desktop/shared-sockets/host-services rw,nosuid,noexec,noatime shared:5 - tmpfs none rw,mode=755
1391 1096 8:16 /docker-desktop-proxy /mnt/wsl/docker-desktop/docker-desktop-proxy rw,relatime shared:6 - ext4 /dev/sdb rw,discard,errors=remount-ro,data=ordered
1392 1096 7:0 / /mnt/wsl/docker-desktop/cli-tools ro,relatime shared:7 - iso9660 /dev/loop0 ro,nojoliet,check=s,map=n,blocksize=2048
1393 1096 8:32 /version-pack-data/community /mnt/wsl/docker-desktop-data/data rw,relatime shared:3 - ext4 /dev/sdc rw,discard,errors=remount-ro,data=ordered
1401 1095 0:19 /init /init ro,relatime - 9p tools ro,dirsync,aname=tools;fmask=022,loose,access=client,trans=fd,rfd=6,wfd=6
1402 1095 0:6 / /dev rw,nosuid,relatime - devtmpfs none rw,size=13099648k,nr_inodes=3274912,mode=755
1403 1095 0:17 / /sys rw,nosuid,nodev,noexec,noatime - sysfs sysfs rw
1404 1095 0:176 / /proc rw,nosuid,nodev,noexec,noatime - proc proc rw
1405 1402 0:177 / /dev/pts rw,nosuid,noexec,noatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
1406 1095 0:178 / /run rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
1407 1406 0:179 / /run/lock rw,nosuid,nodev,noexec,noatime - tmpfs none rw
1408 1406 0:180 / /run/shm rw,nosuid,nodev,noatime - tmpfs none rw
1409 1406 0:181 / /run/user rw,nosuid,nodev,noexec,noatime - tmpfs none rw,mode=755
1410 1404 0:20 / /proc/sys/fs/binfmt_misc rw,relatime - binfmt_misc binfmt_misc rw
1411 1403 0:182 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
1412 1095 0:183 / /usr/lib/wsl/drivers ro,nosuid,nodev,noatime - 9p drivers ro,dirsync,aname=drivers;fmask=222;dmask=222,mmap,access=client,msize=65536,trans=fd,rfd=4,wfd=4
1413 1095 0:184 / /usr/lib/wsl/lib ro,nosuid,nodev,noatime - 9p lib ro,dirsync,aname=lib;fmask=222;dmask=222,mmap,access=client,msize=65536,trans=fd,rfd=4,wfd=4
1414 1411 0:31 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime - cgroup2 cgroup2 rw,nsdelegate
1415 1411 0:32 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
1416 1411 0:33 / /sys/fs/cgroup/cpu rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu
1417 1411 0:34 / /sys/fs/cgroup/cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuacct
1418 1411 0:35 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
1419 1411 0:36 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
1420 1411 0:37 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
1421 1411 0:38 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
1422 1411 0:39 / /sys/fs/cgroup/net_cls rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls
1423 1411 0:40 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
1424 1411 0:41 / /sys/fs/cgroup/net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_prio
1425 1411 0:42 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
1426 1411 0:43 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
1427 1411 0:44 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,rdma
1517 1095 0:185 / /mnt/c rw,noatime - 9p C:\134 rw,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1001;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8
1518 1095 0:186 / /mnt/d rw,noatime - 9p D:\134 rw,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1001;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8
600 1096 8:64 /mnt/e/projects/ImagickRegressionTests /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/299aeca36b5a074b28b7f6d561c8413eaed38cdc22d799bf984a635412f26a6b rw,relatime shared:167 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
601 1096 8:64 /mnt/e/projects/ImagickDemos /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/5e1c852b943b9f3c9c5f84c40d907231f2bb9dbfba1acc291d1d38eccefe6ceb rw,relatime shared:171 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
602 1096 8:64 /mnt/e/projects/ImagickDemos/containers/redis/redis.conf /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/b0a44a3809548fd3f67bbbf54950322fd8f037a5a5ac8565d045ca9bcdf02003 rw,relatime shared:175 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
603 1096 8:64 /mnt/e/projects/imagemagicktest /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/7ed6ec27aca0eeca856e5b0ac3a57aa7603cf7d4cc24c0478d803511e8e4d8c1 rw,relatime shared:179 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
604 1096 8:64 /mnt/e/projects/Params /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/659b4ee0a1938023a86f5fd2924a450f64d7c4c627347b5e0bd76f270cfcb6e4 rw,relatime shared:183 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
605 1096 8:64 /mnt/e/projects/PHPOpenDocs /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/1998a099e3def19ab0e088f55cc05be4cac7369de4803bfce32d5886e09839d8 rw,relatime shared:187 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
606 1096 8:64 /mnt/e/projects/imagick /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/50d0f43c7d443a5db87ddfc0124bc35fdb60932e0bdc1971bc0fa3ef495c4c82 rw,relatime shared:191 - ext4 /dev/sde rw,discard,errors=remount-ro,data=ordered
```

I will avoid freeing up disk space for the time being, on the assumption that doing so would stop this from occuring, so that I can run other diagnostics that you need. FYI, this is mildly inconvenient as I'll need to switch to another computer to work. Or have a great reason for avoiding programming....

**Comment by piratformat** [comment]
@benhillis Did you have any thoughts on this?

**Comment by bstory2001** [comment]
I also had occur exactly what you are describing.  The difference is that it occured in a proxmox containter, ubuntu 22.10, and I don't have wsl installed .  

Conclusion after some troubleshooting:
The mount fails on startup.  It appears that maxing out storage corrupts something in the mount pipeline when using the fstab method to automount on startup.  Removing the mount entry in /etc/fstab and configuring the mount using systemd solved the issue even after reboot.  I think it isn't 'missing files and directories' that is the unexpected behavior but 'present files and directories'.

Troubleshooting
```
# systemctl list-units *.mount
```
-the mount in question shows 'failed' under both the Active column and the SUB column.  Normal results would be 'active' and 'mounted' respectively.

-Files and directories exist in the mnt directory even though it isn't mounting.

-In my case, the visible files were likely the files that were being accessed when the storage topped out.  

-The directories returned after a "mount -a" command.

-On reboot it returned to the missing directory condition.

-I happened to have another mount from the same previously maxed pool that was set up not through fstab that mounted fine.  So I set up the problem mount the same way.
