### ISSUE TITLE
Vim not showing in wsl as of today

### ISSUE THREAD

**Issue by markodraisma** [microsoft/WSL#7694]
As of today whenever I start VIM from wsl / ubuntu, I just get a non-blinking cursor and a black screen. I've tried to reinstall wsl and ubuntu, but it doesn't seem to help. My windows 10 version is 1809 (Enterprise N LTSC) - build 17763.2300

I've tried strace -o strace.txt -ff vim: the resulting file is copied in here.
[strace.txt](https://github.com/microsoft/WSL/files/7533975/strace.txt)

I hope someone can help me out, it has cost me most of my day.

Regards, Marko

**Comment by malletp** [comment]
I have the same issue since today with windows server 2019 1809 build 17763.2300. Tmux is also not working (black sreen too).

**Comment by malletp** [comment]
If I use another terminal based on mintty to launch wsl (like https://github.com/mskyaxl/wsl-terminal), everything works.

**Comment by Guigui37** [comment]
Same thing here, and also happen for less or tmux.
I can run vim, but only gets a non blinking cursor. If I enter ":q" then enter, I exit from vim...

**Comment by bouvetcj** [comment]
Sounds a lot like this:
https://github.com/microsoft/WSL/issues/7694

**Comment by craigloewen-msft** [comment]
Tracking thi sover at 7660 /dupe #7660
