### ISSUE TITLE
Windows 11 crashes with volmgr

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#7695]
I don't know whether my issue is related to WSL or not, but I started to encounter a problem lately, which mostly happens when I do my regular work, which involves WSL2, VSCode, `wsl --mount` and Docker.

## Problem
Ever since I updated to Windows 11 I get random crashes, caused by volmgr. Sometimes it happens a few times in a row, sometimes I can go for days without it to happen. I don't get the typical BSOD, but the PC just freezes for a moment and restarts.

Since the MEMDUMP is about 2 Gigs, I went ahead and enabled Minidump, but the file does not get created, and I cannot find the cause of the issue. I've read, that Windows sometimes crashes so fast, that it doesn't get to the point to create a minidump.

## Obeservations

One thing I've noticed, is, that it mostly happens when I do stuff in VSCode (Remote WSL2) and have Docker Desktop running inside WSL2.
I also use `wsl --mount` to mount a vhdx-file into my WSL2-instance and `mount --bind` it to `/home/<username>` where I mostly work in. This is why I assume that it might have something to do with volmgr and WSL, but I'm not sure.

![image](https://user-images.githubusercontent.com/9553253/141693778-88a6d61d-9c6c-4a8d-8df8-120a443ad974.png)

## System
- Microsoft Windows [Version 10.0.22499.1010]
- Docker Desktiop 4.1.1
- WSL2 (5.10.60.1-microsoft-standard-WSL2)

**Comment by Biswa96** [comment]
Please provide the logs.

**Comment by benhillis** [comment]
This is unrelated to WSL. I would suggest posting a feedback hub issue against the storage team, that will allow them to see dumps from your machine.
