### ISSUE TITLE
Directory from /mnt/c not getting bind mounted automatically by /etc/fstab

### ISSUE THREAD

**Issue by AdelCraftZ** [microsoft/WSL#7696]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [x] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Modify /etc/fstab to have a directory bind mounted from /mnt/c to anywhere on the Ubuntu system.

### Expected Behavior

Bind mount `/mnt/c/Users/<my Windows user>/Documents` to `/home/<my Linux user>/documents` permanently.

### Actual Behavior

I'm trying to bind mount `/mnt/c/Users/<my Windows user>/Documents` to `/home/<my Linux user>/documents`. When I do it manually by executing `mount --bind /mnt/c/Users/<my Windows user>/Documents /home/<my Linux user>/documents`, it works. But when I try to make it persistent by editing `/etc/fstab` and adding the entry `/mnt/c/Users/<my Windows user>/Documents /home/<my Linux user>/documents none defaults,bind 0 0`, it doesn't. My guess is that WSL processes `/etc/fstab` before mounting `/mnt/c`.

**Comment by benhillis** [comment]
/etc/fstab is processed before the drvfs drives are mounted. This is done so the default mount options can be overridden by /etc/fstab.  If you want to do this, please add a drvfs mount to /etc/fstab before the bind mount.
