### ISSUE TITLE
Issue with WSL kernel update

### ISSUE THREAD

**Issue by BharathS11** [microsoft/WSL#7702]
### Version

Microsoft Windows [Version 10.0 19044.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.84

### Distro Version

Ubuntu 20.04

### Repro Steps

Hi, 
I did distribution upgrade of my wsl2 ubuntu from 18.04 to 20.04, but the wsl --list --verbose still shows version 18.04 
`* Ubuntu-18.04    Running         2  `
and recently I installed 21h2 update and ran wsl2 --update, it updated to latest kernel. (trying update again outputs this)
`Checking for updates...                                                                                                 
No updates are available.                                                                                               
Kernel version: 5.10.60.1`
this is the output of lsb_release -a
`
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
`
and this is the output of wsl cat /proc/version
`Linux version 4.19.84-microsoft-standard+ (uname@DESKTOP) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #1 SMP Sun Sep 27 13:27:24 CEST 2020`

I want to update the linux version so that I can use cuda (Need kernel version 4.19.120+), Unfortunately I'm not able to update. Any help is appreciated. Thank you. Happy to provide any more details.

### Expected Behavior

NA

### Actual Behavior

NA

**Comment by 0xbadfca11** [comment]
Do ``wsl.exe --shutdown`` first.
While the instance is running, use the old kernel.

If you still have old kernel, you will manually apply the update.
https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

The registered name displayed by wsl --list cannot be changed from the one registered first.
It will be displayed as Ubuntu-18.04, even if you did to replace all contents into Fedora.

**Comment by BharathS11** [comment]
Hi, I tried manually updating it by downloading the cab file, extracting it and executing the wsl_update_x64.exe, 
![image](https://user-images.githubusercontent.com/8677272/142005748-005d6604-2878-4a05-af9e-6ee683828955.png)

But when I check `wsl cat /proc/version` , still shows 4.19.84

**Comment by benhillis** [comment]
Are you using a private kernel perhaps?  You'll have to reboot for the new kernel to take effect.

**Comment by BharathS11** [comment]
Hi, No I'm not using private kernel, not sure what it means.
I restarted and it still shows the same
![image](https://user-images.githubusercontent.com/8677272/142716994-15bf150f-c4b2-4cb7-afb5-fa121207a249.png)

**Comment by onomatopellan** [comment]
@BharathS11 That's a custom/private kernel. Try typing `notepad.exe $env:USERPROFILE/.wslconfig` and post the content here.

**Comment by BharathS11** [comment]
Hi @onomatopellan ,
Apologies for the delay, here is the output of what you asked.
`[wsl2]
kernel=C:\\Users\\bhara\\bzImage
swap=16GB
localhostForwarding=true
processors=8`

**Comment by onomatopellan** [comment]
@BharathS11 Thanks. That kernel line means WSL2 is using the custom kernel `bzImage` which seems version 4.19.84.
You need to delete the kernel line or put a # in the front like this:
```
[wsl2]
#kernel=C:\\Users\\bhara\\bzImage
swap=16GB
localhostForwarding=true
processors=8
```
Save the changes to the file and run `wsl.exe --shutdown`. After that you should see it's using latest kernel from windows update version 5.10.60.1.

**Comment by didyouexpectthat** [comment]
I have this problem but I am not using a custom kernel.  The kernel version is supposed to be 5.15.57.1  The wsl2 reports 5.10.102.1. I've tried....

- Converting from WSL2 to WSL1 and back, did not upgrade kernel
- Converting to WSL2 over the top of existing WSL2, same.
- wsl.exe --update, but already using the latest
- wsl.exe --shutdown, yep, did this, and restarted PC and everything. 

```
me@computer:/$ wsl.exe --version
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.978
me@computer:/$ uname -a
Linux computer 5.10.102.1-microsoft-standard-WSL2+ #1 SMP Tue Mar 22 09:06:14 PDT 2022 x86_64 GNU/Linux

```
Any suggestions?

**Comment by onomatopellan** [comment]
@didyouexpectthat Run `notepad.exe $env:USERPROFILE/.wslconfig` from PowerShell and post the content of the file if it exists.

**Comment by Ayke** [comment]
I had the same thing. wsl --unregister them, uninstall wsl, reboot then reinstall wsl and ubuntu got it solved.

**Comment by Jai-GAY** [comment]
try all, no, none steps work. anything to do with multiple WSL installed?

notepad.exe $env:USERPROFILE/.wslconfig
no such file, create an empty file, 
[wsl2]
swap=16GB
localhostForwarding=true
processors=4

edit and save, wsl --shutdown, reboot PC, same.

PS C:\WINDOWS\system32> wsl cat /proc/version
Linux version **4.4.0-19041**-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #3393-Microsoft Mon Aug 14 14:52:00 PST 2023

PS C:\WINDOWS\system32> wsl.exe --list --online
The following is a list of valid distributions that can be installed.
Install using 'wsl.exe --install <Distro>'.

NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
OracleLinux_7_9                        Oracle Linux 7.9
OracleLinux_8_7                        Oracle Linux 8.7
OracleLinux_9_1                        Oracle Linux 9.1
openSUSE-Leap-15.5                     openSUSE Leap 15.5
SUSE-Linux-Enterprise-Server-15-SP4    SUSE Linux Enterprise Server 15 SP4
SUSE-Linux-Enterprise-15-SP5           SUSE Linux Enterprise 15 SP5
openSUSE-Tumbleweed                    openSUSE Tumbleweed

PS C:\WINDOWS\system32> wsl --version
WSL version: 1.2.5.0
**Kernel version: 5.15.90.1**
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3393

PS C:\WINDOWS\system32> wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.

uname -a still 4.4.0.xx not 5.15.90.1, why?
Linux XXXXXXX 4.4.0-19041-Microsoft #3393-Microsoft Mon Aug 14 14:52:00 PST 2023 x86_64 x86_64 x86_64 GNU/Linux

![image](https://github.com/microsoft/WSL/assets/12781023/3aa7eb2f-64fe-4d4e-a6ee-dc26ca23a55c)
