### ISSUE TITLE
Program automatically gets killed

### ISSUE THREAD

**Issue by nileshop22** [microsoft/WSL#7706]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Just run a normal deep learning training.

### Expected Behavior

Expected to complete the training.

### Actual Behavior

After around half an hour of training, the terminal becomes unresponsive and then after a while it gets automatically killed. I'm using Pytorch with CUDA Toolkit 11.02 if that is relevant.  

The terminal just shows _"Killed"_ nothing more.

**Comment by benhillis** [comment]
Likely a kernel panic, can you post a feedback hub issue please?

**Comment by arnavmehta7** [comment]
It is still an Issue
