### ISSUE TITLE
Installing "Windows Subsystem for Linux Preview" using Microsoft Store hangs on Windows 11

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/WSL#7707]
### Version

Microsoft Windows [Version 10.0.22000.258]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Repro Steps

I have WSL already installed using old method. When I try to install through Microsoft Store it hangs. I click on install button and it displays rotating animation that never ends.

### Expected Behavior

"Windows Subsystem for Linux Preview" installs successfully

### Actual Behavior

It hangs

**Comment by vvavrychuk** [comment]
Okay, all of a sudden, when I open "Windows Subsystem for Linux Preview" in Microsoft Store, button "Install" is replaced with "Open".

Well, I have a suspect that this was not all of a sudden, but after I installed Ubuntu via Microsoft Store. Previously, I had installed Debian. So maybe reproducing steps could be:

1. Install WSL with some distribution not via Microsoft Store.
2. Observe that install via Microsoft Store hangs.
3. Install some distribution via Microsoft Store.
4. Observe that "Windows Subsystem for Linux Preview" is now detected in Microsoft Store as installed.

But, I am not sure if this will be reproducible.

**Comment by benhillis** [comment]
Sounds like a store UI issue to me. Probably not actionable by the WSL team.

**Comment by alex180500** [comment]
I tried doing the same thing but had no problem on windows 11, it just updated the existing WSL istance.
This is my `wsl --status` (weirdly it displays a wrong windows version)

```Default Distribution: Ubuntu
Default Version: 2
WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29
Windows version: 10.0.22000.318

**Comment by benhillis** [comment]
@alex180500 - that windows version looks right to me, can you share the output of `cmd.exe /k ver` and see if it matches?

**Comment by alex180500** [comment]
`Microsoft Windows [Version 10.0.22000.318]`

yeah it seems right, sorry I thought it would display windows 11.etc :/

**Comment by benhillis** [comment]
@alex180500 - no worries, it's a bit confusing. Windows 11 is the display name, but we didn't rev the major version number.

**Comment by vvavrychuk** [comment]
I guess we have to close this as non reproducible.
