### ISSUE TITLE
Latest 0.50.2 release msixbundle will not install

### ISSUE THREAD

**Issue by SteveALee** [microsoft/WSL#7708]
### Version

Version 10.0.19043.1348

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Download and open the 0.50.2 MSI in releases [here on GitHub](https://github.com/microsoft/WSL/releases/tag/0.50.2)

### Expected Behavior

Successful install

### Actual Behavior

![image](https://user-images.githubusercontent.com/618922/142199240-ea2ac345-819d-48c7-9833-d697e727feb8.png)

**Comment by Biswa96** [comment]
It is for Windows 11 only.

**Comment by SteveALee** [comment]
What! Please add this critical info to the releases info!
Better still, get the MSI to give a proper error.

I used the release as it appeared in the win 10 store but there was no version given so I had no clues :( The new icon did show

Not a nice experience here :(

**Comment by Biswa96** [comment]
Maybe you missed some news from previous month. The blog post[^1] which mentioned Windows 11 requirement explicitly. Also the Windows Store page for WSL Preview[^2] mentions Windows 10 version 22000.0 or higher as minimum OS requirement.

[^1]: https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/
[^2]: https://www.microsoft.com/en-us/p/windows-subsystem-for-linux-preview/9p9tqf7mrm4r?activetab=pivot:regionofsystemrequirementstab

**Comment by SteveALee** [comment]
@Biswa96 thanks I was follow a twitter thread introducing it.

The confusion is that:

- there are now 3 variants of WSL (WSL1, WSL2 & WSLWin11) and it was not at all clear which one this update is for 
- I also had no way to tie the blog post you mentioned to to this release.
- I had no idea that Windows 11 is AKA Windows 10 version 22000.0, Genius D'oh. I saw 10 and assumed Windows 10.
- no version given in the store page, just a release date from ages ago (icon was the new one).
- "preview" usually indicates a new version not just a new release channel so I thought this was new
- no indication of how to update - the store says "get" and I already have it

Hope you can see why I got confused?

**Comment by craigloewen-msft** [comment]
@SteveALee this is great feedback! I think you've pointed out some good ways we can make it easier for people to get onto the WSL Store version. For now the easiest way is to please take a look at the store page to install: https://aka.ms/wslstorepage and I'll investigate improving our docs to make this more apparent :) (I also think I sent you the same links on Twitter, so apologies for the double message!) 
I'll close this issue out as resolved and track it as a work item for the docs repo. Thank you!

**Comment by SteveALee** [comment]
Thanks @craigloewen-msft 

I guess the use case is when I land on the release page without any more context. :)
