### ISSUE TITLE
Memory lose

### ISSUE THREAD

**Issue by lysShub** [microsoft/WSL#7712]
### Version

Microsoft Windows [版本 10.0.19043.1288]   

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Repro Steps

after long time use

![image](https://user-images.githubusercontent.com/55095917/142387301-2e79759a-76a8-45e1-92a1-30bb52d31fc9.png)

### Expected Behavior

sub system use about 2GB memery, Expect Vmmem use 2.x GB memery

### Actual Behavior

Vmmem use 7 GB memery, lose 5GB memery

**Comment by onomatopellan** [comment]
You can add `memory=2GB` to your [.wslconfig file](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#global-configuration-options-with-wslconfig).

**Comment by craigloewen-msft** [comment]
The amount of memory usage you're seeing here is due to Linux caching. You can fix this by changing your .wslconfig file as mentioned above. We are working on a long term solution for this, thank you for filing this!

/dupe #4166
