### ISSUE TITLE
How to share environment variables between WSL2 and host Windows 10?

### ISSUE THREAD

**Issue by krave1986** [microsoft/WSL#7713]
I am looking for some way to share environment between WSL2 and host machine - Windows 10.
I checked [this article](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) until I found it is WSL related instead of WSL2.

Do you have any advices how to do this in WSL2 ?

Thank you!

**Comment by Biswa96** [comment]
AFAIK, it is same in WSL2.

**Comment by krave1986** [comment]
@Biswa96 Thank you for your prompt reply.

I have tried:

1. Run `setx WSLENV "$env:WSLENV:ONEDRIVE"/p` from PowerShell which is the same syntax listed in the article I mentioned earlier. But it turns out the syntax is not valid. 
![syntaxError](https://user-images.githubusercontent.com/16416541/142479843-10f9b42a-c86b-4034-9e44-4f14f0f26f32.png)

2. Run `export WSLENV=HOME/p` from WSL2 Ubuntu disto. The HOME variable is only available within `cmd.exe` which is invoked directly from the session in which I exported the variable. It is not available in other session.

I have no idea about what have I done wrong? My purpose is to access $OneDrive from within Ubuntu in order to bind mount it into Docker container.

**Comment by Biswa96** [comment]
What I understand is that you want to pass an environment variable from Windows to WSL. Then the correct flag might be `/u`. Here is an example to pass `%UserProfile%`.

1. In Command Prompt:

```cmd
C:\> set WSLENV=USERPROFILE/u
```

2. In WSL, the result will be like this :

```sh
$ env | grep -i user
USERPROFILE=C:\Users\x
USER=x
WSLENV=USERPROFILE/u
```

**Comment by krave1986** [comment]
@Biswa96 I can confirm that your solution works but constrined in one single session.

For example, open cmd.exe first, set WSLENV as you did. I have to run `ubuntu` right away to enter WSL2. That way $USERPROFILE can be accessed normally. By the way, I do need `/p` flag because I need path translation between Windows and WSL2.
![正常](https://user-images.githubusercontent.com/16416541/142495230-03788263-80f4-49de-80c9-d02405af043f.png)

But if I open another terminal , I can no loager access the variable. No need to say availability across system reboot.
![异常](https://user-images.githubusercontent.com/16416541/142495485-1bc3db89-0e9b-4af4-b7a9-66e57560a36a.png)

Maybe any suggestion about the variable persistence?

On the other hand, we can't set WSLENV from PowerShell, can we?

**Comment by Biswa96** [comment]
> But if I open another terminal , I can no loager access the variable.

Mine was just an example. To make the variable persistant, you need to use setx command or control panel's advanced system settings. The article already mentioned that.
