### ISSUE TITLE
Deleting a directory that explorer.exe is accessing causes explorer.exe crash

### ISSUE THREAD

**Issue by Worldwidebrine** [microsoft/WSL#7715]
### Version

Windows 10.0.22000.318

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu-20.04

### Other Software

explorer.exe

### Repro Steps

1. `mkdir /home/myuser/test`
2. `explorer.exe \\wsl.localhost\Ubuntu-20.04\home\myuser\test`
3. `rm /home/myuser/test`
4. Wait (explorer.exe will crash and self-restart)

### Expected Behavior

explorer.exe alerts
or
`rm /home/myuser/test` fails

### Actual Behavior

explorer.exe crashes

**Comment by benhillis** [comment]
I cannot repro this. I would suggest filing a feedback hub issue so I can take a look at explorer.exe crashdumps from your machine.

**Comment by Worldwidebrine** [comment]
I can't reproduce anymore. It could be coincidence.
