### ISSUE TITLE
WSL Preview Store version not working after wake up from sleep

### ISSUE THREAD

**Issue by roja45** [microsoft/WSL#7719]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Uninstalled WSL2 from windows
Installed version from store.
Installed Ubuntu distro
All working fine.
Put computer to sleep.
Next day, opening terminal and nothing happens, won't show command line blank screen in terminal.

### Expected Behavior

Should start as normal

![image](https://user-images.githubusercontent.com/19314911/142626213-89eef5ba-6955-4980-9dc3-e8be912ce521.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/19314911/142626242-f74a5fd4-d9b7-4b9c-9ff1-c5fdb8782456.png)

No command line, stuck here.

**Comment by roja45** [comment]
I can't restart the service either.

![image](https://user-images.githubusercontent.com/19314911/142626661-06113127-625a-4a29-8250-fa9daefb6e1b.png)

**Comment by benhillis** [comment]
Can you share the output of the following command?

`sc query wslservice`

**Comment by roja45** [comment]
SERVICE_NAME: wslservice
        TYPE               : 210  WIN32_PACKAGED_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0


However I have restarted the machine and it is working again at the moment.  I can do this again if it repeats after putting it to sleep again.

**Comment by roja45** [comment]
Computer has woken from sleep, and there is no response from the linux instance.  This is the response from the command above:
SERVICE_NAME: wslservice
        TYPE               : 210  WIN32_PACKAGED_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by benhillis** [comment]
Ok, service is running. Must be something inside the virtual machine.  Can you try to:

`wsl.exe --shutdown`
and collect logs /logs?

**Comment by roja45** [comment]
The only problem with collecting those logs it that wsl.exe is unresponsive when in this state, but will try it again.

**Comment by roja45** [comment]
Opening a new WSL terminal window is not working, just waits.

I don't seem to be able to generate the logs.

This command just freezes:
![image](https://user-images.githubusercontent.com/19314911/144424808-d33e582b-4b4c-475a-bfe5-ee424cfe2dfa.png)

Generating the logs raises an error
![image](https://user-images.githubusercontent.com/19314911/144424847-c9f45a17-ce3e-484c-89d8-062dceb07132.png)

**Comment by benhillis** [comment]
We have identified a few possible causes for this. The fixes will be in an upcoming Windows Insider build.

**Comment by Cosss7** [comment]
https://github.com/microsoft/WSL/issues/7719

Same like this, but still bad utill now.

**Comment by tziemek** [comment]
Finally got 22H2 for my company laptop. Working fine now.

**Comment by craigloewen-msft** [comment]
Closing this as we've made lots of fixes to Hyper-V and WSL to help address issues like this. If you're still seeing this please open a new issue for us to triage! Thanks!
