### ISSUE TITLE
wslg is not installed in 21H2

### ISSUE THREAD

**Issue by wxie2013** [microsoft/WSL#7720]
### Version

Microsoft Windows [Version 10.0.19044.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I followed the procedure in the following documents: 

     https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

the wslg is missing under /mnt, i.e. 

$ ls -l /mnt
total 0
drwxrwxrwx 1 tom david 4096 Nov 19 09:24 c
drwxrwxrwt 2 root root   40 Nov 19 09:24 wsl

### Expected Behavior

when running xclock, a clock GUI show up. 

### Actual Behavior

$ xclock
Error: Can't open display:

**Comment by benhillis** [comment]
WSLg is currently only supported on Windows 11.
