### ISSUE TITLE
wsl.exe not working in 22504 build

### ISSUE THREAD

**Issue by anandbhaskaran** [microsoft/WSL#7721]
### Version

?? Could not see as wsl.exe is not working

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 16.04

### Repro Steps

It was working totally fine till the recent update

Once I updated to 22504 build entire WSL is broken and I cant access wsl at all from command line and from the explorer

### Expected Behavior

It should work as usual

### Actual Behavior

wsl.exe hangs and does not start

**Comment by anandbhaskaran** [comment]
My Kernel version is Microsoft Windows [Version 10.0.22504.1000]

And diagnostic log is available here: https://aka.ms/AAew9os

**Comment by anandbhaskaran** [comment]
Would really appreciate it if you can prioritize this PR as I have multiple reports inside this container that I need for my everyday work.

**Comment by benhillis** [comment]
I am not seeing any WSL-related logs in your trace. Could you try rebooting and collecting logs manually please?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually

**Comment by anandbhaskaran** [comment]
I am sorry :( I roll back the build as I have urgent work and now WSL work. I am pretty sure it is the build that broke the WSL, but unfortunately I would not be able to provide you the logs :(

**Comment by benhillis** [comment]
No problem, please let us know if you're able to reproduce.
