### ISSUE TITLE
Cannot browse SSHFS-mounted folders in File Explorer's Linux Integration

### ISSUE THREAD

**Issue by suhailrehman** [microsoft/WSL#7729]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

SSHFS version 2.10.0
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

### Repro Steps

1. Mount a remote folder via SSHFS in /mnt/ using a command like so:
```
sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,uid=$(id -u),gid=$(id -g) server.address:/path/to/folder/ /mnt/remotefolder/
```
2.  Browse to the folder in File Explorer:
```
explorer.exe .
```

### Expected Behavior

Expect to be able to browse the remote files

### Actual Behavior

I get the following error from within Explorer instead:
![image](https://user-images.githubusercontent.com/7931270/142688339-03eb5fb2-96c9-4a25-95ea-7108d9094e3a.png)

### Diagnostic Logs

I noticed that the remote folder mounted by SSHFS is mounted without read/write permissions for others, but that's not a requirement to browse local files in explorer.exe.

**Comment by OneBlue** [comment]
This might indeed be a permission issue.

Which user is your default user  ? That's what the explorer file access runs as.

Also, what's the output of:
`ls -la /mnt/remotefolder/` ?

**Comment by suhailrehman** [comment]
I've mounted the remote folder using the `uid` and `gid` mapped to my default user and group (suhail). My remote folder is called `roscoe`

```
: /mnt$ ls -la /mnt
ls: cannot access '/mnt/g': No such device
total 24
drwxr-xr-x 11 root   root   4096 Nov 19 14:30 .
drwxr-xr-x 19 root   root   4096 Nov 15 14:32 ..
drwxrwxrwx  1 suhail suhail 4096 Nov 22 00:05 c
drwxrwxrwx  1 suhail suhail 4096 Nov 22 00:05 d
drwxrwxrwx  2 root   root   4096 Jun  2  2020 e
drwxrwxrwx  2 root   root   4096 May  1  2020 f
d?????????  ? ?      ?         ?            ? g
drwxrwx---  1 suhail suhail    9 Nov 19 13:53 roscoe
drwxrwx---  2 suhail suhail 4096 Nov 19 14:30 test
drwxrwxrwt  2 root   root     60 Nov 15 14:24 wsl
drwxrwxrwt  6 root   root    260 Nov 23 12:55 wslg
```

**Comment by OneBlue** [comment]
Ok thanks for the update. If suhail is the default user then this shouldn't be a permission issue.

Can you please follow the [Record wsl logs manually section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) to collect logs of a repro ?
