### ISSUE TITLE
Fully passthrough keyboard to wslg

### ISSUE THREAD

**Issue by MikeCoder96** [microsoft/WSL#7730]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.60.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Aug 25 23:20:18 UTC 2021

### Distro Version

Kali Linux

### Repro Steps

Press Windows key while using VM in QEMU

### Expected Behavior

Windows key will prompt start menu from Guest OS in QEMU

### Actual Behavior

Pressing Windows key while using VM in QEMU will prompt Start Menu from Windows 11.

**Comment by craigloewen-msft** [comment]
Could you please open this as a feature request on the WSLg repo? That way the right folks will be able to get visibility onto this ask.

You can use this link: https://github.com/microsoft/wslg/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=

I'll close out this issue in favour of tracking it over on the WSLg repo (Feel free to link back to this issue if you like). Thank you for the feedback! :)
