### ISSUE TITLE
win-kex-kali only runs with root privileges

### ISSUE THREAD

**Issue by sajiddotm** [microsoft/WSL#7733]
I have set up a win-kex-kali in the kali-linux, but whenever I try to run it without sudo, it throws the following error
` unable to connect to socket: Connection refused (10061)`

Running with sudo privileges works fine, but land you in the vncserver with overall root privileges, which is overall a security risk and even some apps don't like running with root permissions.

**Comment by craigloewen-msft** [comment]
Can you please file this with the Kali Linux team? We do not have the right controls on the WSL team to fix this problem. 

Thanks!
