### ISSUE TITLE
Can't open windows programs in WSL2 that is not under the /mnt/c directory

### ISSUE THREAD

**Issue by Nukiloco** [microsoft/WSL#7736]
### Version

Microsoft Windows [Version 10.0.19042.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Other Software

Any Windows software that you can launch with WSL2
Aka the commands like ``code``

### Repro Steps

1. Leave PC on for a very long time (Around a few hours)
2. Then try to run ``code``
3. Program does not launch open and you have to ``Ctrl C`` out of it.

### Expected Behavior

Program should launch open, even when leaving my computer on for a very long time.

### Actual Behavior

When running a command like ``code``, it will show no message nor the windows program will appear.

**Comment by wonsu** [comment]
I had the same on Windows 11 Pro 21H2 build 22000.318 with Ubuntu 20.04 on WSL2.
I was unable to run Intellij Idea with project stored on wsl or even enter wsl directory in Windows File Explorer - it was loading endlessly.
When I tried to open wsl shell in Windows Terminal it showed blank window although I was able to enter wsl by calling wsl.exe in powershell.

**Comment by Nukiloco** [comment]
I'm not going to provide logs for this one since I have some private stuff that I don't want to show on my screen and the feedback hub seems to record all of your monitors. Hopefully someone else can provide them.

**Comment by Nukiloco** [comment]
Just found out, this is no longer an issue with how long it stays open now.
It does open when its under the ``/mnt/c/`` directory. But if it's under any other directory, it will refuse to open.
Note that if I do ``code`` in any directories under ``/mnt/c``, I can navigate to the directory I want to in vscode in wsl mode.

**Comment by Nukiloco** [comment]
Attempted to update and upgrade Ubuntu, it didn't seem to do anything. Especially when running ``wsl --shutdown`` in powershell and starting Ubuntu again.

**Comment by Nukiloco** [comment]
Oddly enough when executing a command like ``code``, you can type anything in afterwards though nothing executes, aka the only way to leave is to ``Ctrl C``.
https://user-images.githubusercontent.com/16618467/143319523-a72b6656-aaab-4445-9648-a4f52c33f492.mp4

**Comment by RoRElessar** [comment]
I have the same problem on Windows 11. When I try to reach my files that are located in my /home directory like `\\wsl$\Ubuntu\home`, or just trying to execute `explorer.exe .` - explorer is not able to open it, just an infinite load bar is displayed. `wsl --shutdown` doesn't help. Only `Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` => reboot => `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` => reboot => `wsl --shutdown` helps. But in a few minutes, sometimes 10 or more, it is always random, the access to `\\wsl$\Ubuntu`  is disabled via the explorer.

**Comment by bedecarroll** [comment]
Adding what I've found:

* You can only open a Windows exe two or three times before it stops
* Restarting WSL via `wsl --shutdown` or `wsl --terminate` does not help
* Full reinstall of the distro using `wsl --unregister` does not help
* A full reboot of the host Windows OS is required to get applications to start working again for a short time
* An strace between a working (`/mnt/c`) and non-working (`/home/`) showed nothing but an exec and then output stops
* Distribution isn't a factor, used Ubuntu 20.04 and 21.04 community preview and both had the same issue (I can't remember if one breaking also meant the other breaking however, I _think_ it did but I'm not 100%)

Now some good news however, I've narrowed it down to `Windows Subsystem for Linux Preview` from the Microsoft Store. If you go into apps, uninstall it and reboot then launching apps from non-Windows dirs will stay working. I'm at 12+ hours of exe's launching.

**Comment by Nukiloco** [comment]
I don't have ``Windows Subsystem for Linux Preview`` in the ``Microsoft Store`` though I do see ``Windows Subsystem for Linux Update`` in ``Apps & features`` in ``Settings``

**Comment by RoRElessar** [comment]
> Now some good news however, I've narrowed it down to `Windows Subsystem for Linux Preview` from the Microsoft Store. If you go into apps, uninstall it and reboot then launching apps from non-Windows dirs will stay working. I'm at 12+ hours of exe's launching.

I have `Windows Subsystem for Linux Preview`, and sometimes it works for a long period of time, but then something goes wrong, and `explorer` and my IDE hang. So, I have to reboot, and sometimes do the manipulations I have mentioned in a comment above. After it will work for a couple of minutes.

**Comment by Nukiloco** [comment]
I wonder if this issue is caused from upgrading Ubuntu?

**Comment by Nukiloco** [comment]
Someone told me to check to see if mono is installed on ubuntu. They told me that mono installs a binary handler which is what I was told of.

They told me to do ``apt list --installed | grep mono`` to see if mono was installed.
This is the output I then got:
```
ubuntu-mono/focal,now 19.04-0ubuntu3 all [installed,automatic]
```

After that I was then told to run this command: ``sudo apt remove ubuntu-mono``

Now I can run windows programs again on wsl2 anywhere. I'm not sure if this will work for other people.

**Comment by frhun** [comment]
For anyone interested in investigating this issue further, look into removing the binfmt_misc handler for mono; that clashes with the handler for windows PE2 exes because they have the same magic number.
