### ISSUE TITLE
bug: "WARNING: your terminal doesn't support cursor position requests (CPR)."

### ISSUE THREAD

**Issue by sabotagebeats** [microsoft/WSL#7740]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

github.com/eth-brownie

### Repro Steps

use wsl with brownie, issues moving cursor, get error

### Expected Behavior

cursor goes in right place

### Actual Behavior

when deleting text the text comes back, the cli often breaks and forces me to reconnect

**Comment by sabotagebeats** [comment]
this is using vscode with remote extension

**Comment by benhillis** [comment]
Sounds like this should be filed with the VsCode folks.

**Comment by craigloewen-msft** [comment]
@sabotagebeats you can file it here: https://github.com/Microsoft/vscode-remote-release
