### ISSUE TITLE
\\wsl$\ path is case sensitive for 'wslpath -a'

### ISSUE THREAD

**Issue by umairsair** [microsoft/WSL#7744]
### Version

Microsoft Windows [Version 10.0.18363.1854]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.60.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Aug 25 23:20:18 UTC 2021

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Repro Steps

`wslpath -a` expects wsl$ in lower case while windows allows any case of individual letters, like WSL, Wsl etc. If user simply copy paste the path from explorer and try to use it, it fails.

wslpath should support any casing of WSL$

Following works fine.
```
$ wslpath -a //wsl$/Debian/home
/home
```

### Expected Behavior

```
$ wslpath -a //WSL$/Debian/home
/home
$ wslpath -a //Wsl$/Debian/home
/home
```

### Actual Behavior

```
$ wslpath -a //WSL$/Debian/home
wslpath: //WSL$/Debian/home
$ wslpath -a //Wsl$/Debian/home
wslpath: //Wsl$/Debian/home
```

**Comment by benhillis** [comment]
Good call - we will go ahead and make this change.

**Comment by benhillis** [comment]
Fixed in https://github.com/microsoft/WSL/releases/tag/0.51.0.
