### ISSUE TITLE
WSL 2 GUI application is not aware of Windows screen dimensions

### ISSUE THREAD

**Issue by smuehlst** [microsoft/WSL#7745]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Debian GNU/Linux 11 64-bit from Microsoft Store

### Other Software

Eclipse 2021-09 Linux 64-bit

### Repro Steps

- Run Eclipse for Linux under WSL 2.
- Open a C/C++ Editor window.
- Right-click into the editor window to open the editor popup window.
- Open the "Team" sub-menu from the popup menu.

### Expected Behavior

The "Team" sub-menu should be opened so that it is fully visible on the Windows screen.

This is a screenshot of running the Windows version of Eclipse, after right-clicking into the editor window to open a popup menu and after opening the sub-menu "Team":

![Windows GUI Eclipse](https://user-images.githubusercontent.com/98944/143020298-d994ddab-408e-492c-9a5f-a205df29cea6.png)

Note that the "Team" sub-menu is popped up upwards so it can be fully displayed on the screen. If the sub-menu were popped up downwards it wouldn't fit on the screen

This is a screenshot of the Linux version of the same Eclipse version, when opening the same editor popup menu and "Team" sub-menu:
 
![WSL2 GUI Eclipse](https://user-images.githubusercontent.com/98944/143020302-a20d3436-620a-43ea-9fb5-624295ea2195.png)

Note that the "Team" sub-menu is opened downwards, and extends beyond the screen so some of the sub-menu entries are invisible and cannot be clicked. This does never happen when running Eclipse under a real Linux graphical desktop.

### Actual Behavior

The "Team" sub-menu is opened downwards so that it is not fully visible on the Windows screen, and some of the menu entries can't be clicked.

Apparently the Linux GUI application running under WSL 2 is not aware of the actual screen dimensions.

**Comment by craigloewen-msft** [comment]
Could you please file this as an open item on the WSLg repo? The full team that works on WSLg monitors that repo instead at: microsoft/wslg

You can file the issue here: https://github.com/microsoft/wslg/issues/new?assignees=&labels=bug&template=bug_report.md&title=

And feel free to link back to this issue if you like. I'll close this one for bookkeeping purposes so it can be tracked on the wslg repo instead. Thanks!
