### ISSUE TITLE
Running Linux App on WSL2 is very unreliable

### ISSUE THREAD

**Issue by wwang2016** [microsoft/WSL#7750]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.60.1

### Distro Version

Ubuntu-18.04

### Repro Steps

(1) Normal usage and should not expect flickering of Task manager sometimes every day
(2) start Eclipse from WSL

### Expected Behavior

(1) I was expecting Intel GPU driver to work seamlessly without causing issue (like flickering)
(2) I was expecting a more reliable experience starting Linux app from WSL 

### Actual Behavior

I followed the link (https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) to install Intel GPU driver for WSL, and I was able to start up Eclipse from WSL. However, the use experience is bad.
(1) I experience flickering of Task manager everyday. It is not all the time, but there will be sometime everyday. This issue never happened before installing the Intel GPU driver for WSL

(2) Starting Eclipse from WSL worked. However, it exits many times a day. It is a lot worse than when I used a X server to support starting Eclipse from WSL.
The following are some typical messages related to exit of Eclipse
Error reading events from display: Connection reset by peer
Error reading events from display: Broken pipe

(3) Sometimes I could not start up Eclipse from WSL after a while, and I had to do wsl --shutdown from  a powershell

**Comment by wwang2016** [comment]
Gdk-Message: Unable to load left_ptr_watch from the cursor theme
Gdk-Message: Unable to load sb_v_double_arrow from the cursor theme
Gdk-Message: Unable to load sb_h_double_arrow from the cursor theme
Gdk-Message: Unable to load sb_v_double_arrow from the cursor theme
Gdk-Message: Error reading events from display: Connection reset by peer


Gdk-Message: Unable to load sb_v_double_arrow from the cursor theme
Gdk-Message: Unable to load fleur from the cursor theme
Gdk-Message: Unable to load crossed_circle from the cursor theme
Gdk-Message: Error reading events from display: Broken pipe

Gdk-Message: Unable to init server: Could not connect: connection refused

**Comment by mstephe4** [comment]
Have this bug too. 
eckButton

(wxgui.py:49431): Gtk-CRITICAL **: 04:58:08.717: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(wxgui.py:49431): Gtk-CRITICAL **: 04:58:08.735: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(wxgui.py:49431): Gtk-CRITICAL **: 04:58:09.435: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton
Gdk-Message: 04:58:10.663: Unable to load sb_h_double_arrow from the cursor theme
Gdk-Message: 04:58:10.663: Unable to load sb_h_double_arrow from the cursor theme

**Comment by elsaco** [comment]
On Ubuntu, after installing `adwaita-icon-theme-full` there are no more `Gdk-Message(s)` about the cursor theme when launching GUI apps.

**Comment by aruprakshit** [comment]
> On Ubuntu, after installing `adwaita-icon-theme-full` there are no more `Gdk-Message(s)` about the cursor theme when launching GUI apps.

I still get these after installing it via ` sudo apt-get -y install adwaita-icon-theme`.

```sh
─arup at deadpool in ~ 24-02-13 - 22:21:11
╰─○ emacs .
Gdk-Message: 22:21:16.102: Unable to load sb_v_double_arrow from the cursor theme
Gdk-Message: 22:21:16.102: Unable to load sb_h_double_arrow from the cursor theme
Gdk-Message: 22:21:16.138: Unable to load hand2 from the cursor theme
Gdk-Message: 22:21:16.138: Unable to load sb_h_double_arrow from the cursor theme
Gdk-Message: 22:21:16.138: Unable to load sb_v_double_arrow from the cursor theme
```

**Comment by elsaco** [comment]
@aruprakshit you need to install `adwaita-icon-theme-full` also. Notice the difference between the package name:

```
elsaco@texas:~$ apt list adwaita-icon-theme
Listing... Done
adwaita-icon-theme/jammy 41.0-1ubuntu1 all
elsaco@texas:~$ apt list adwaita-icon-theme-full
Listing... Done
adwaita-icon-theme-full/jammy 41.0-1ubuntu1 all
```
