### ISSUE TITLE
Windows binaries won't run unless CWD is in /mnt/c

### ISSUE THREAD

**Issue by bedecarroll** [microsoft/WSL#7761]
### Version

Microsoft Windows [Version 10.0.22000.348] (Windows 11)

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.74.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Mon Oct 18 19:27:44 UTC 2021

### Distro Version

Ubuntu 21.04

### Other Software

WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29
Windows version: 10.0.22000.348

### Repro Steps

* cd into any Linux path (e.g. /home/)
* Run notepad.exe
* notepad.exe does not start
* cd into /mnt/c/
* Run notepad.exe
* notepad.exe starts

### Expected Behavior

* notepad.exe starts

### Actual Behavior

* notepad.exe does not start

### Diagnostic Logs

Not sure if this is known but I could find nothing to say that this was expected and that your CWD needed to be somewhere in the mount for the Windows drive. This is my binfmt_misc:

```
$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /tools/init
flags: F
offset 0
magic 4d5a
```

And my interop level in env:

```
$ printenv | grep WSL
WSL_DISTRO_NAME=Ubuntu-CommPrev
WSL_INTEROP=/run/WSL/303_interop
WSLENV=WT_SESSION::WT_PROFILE_ID
```

**Comment by Drakota** [comment]
Duplicate of #7736 and possibly related to #7754

**Comment by bedecarroll** [comment]
Sorry, yes it really is a duplicate of #7736.
