### ISSUE TITLE
useless output from "wsl --? | more"

### ISSUE THREAD

**Issue by hteibler** [microsoft/WSL#7763]
### Version

windows 10 and 11

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

execute in a windows cmd 
wsl --? | more

then every letter has its own line

### Expected Behavior

how the more command works normally

### Actual Behavior

every letter is in a new line

**Comment by zhang616123** [comment]
I also noticed a problem may related, see https://github.com/microsoft/WSL/issues/7767.
