### ISSUE TITLE
Uploading file to browser from WSL folder 

### ISSUE THREAD

**Issue by nike1v** [microsoft/WSL#7764]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu 20.04

### Other Software

Google Chrome (Windows) 96.0.4664.45

### Repro Steps

1. Open Google Chrome on page where you might upload some files (any type).
2. Open modal upload window and choose file from WSL folder.
3. Wait until file uploads.
4. Click on a button to upload new file.

### Expected Behavior

After second click to upload new file, modal window might be opened on top of the browser and wait until I choose the file.

### Actual Behavior

Chrome window turns inactive and when you try to click anywhere inside of the window it makes sound, like you click out of the exploere.exe window (to choose the file). But you still can you browser with keyboard.

You can only close Chrome to make it active again to mouse clicks and only system restart will helps you to open file loading window again.

Also after one file upload, you can't access WSL FS via explorer.exe, but you still can work in it via terminal.

**Comment by OneBlue** [comment]
Thanks for reporting this @nike1v. Can you share picture / videos of a repro ?
