### ISSUE TITLE
Cannot install newly compiled wsl kernel 5.10.60.1

### ISSUE THREAD

**Issue by picatostas** [microsoft/WSL#7765]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2 

### Distro Version

Ubuntu 20.04

### Repro Steps

I have downloaded https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-5.10.60.1.tar.gz

- make -j12 KCONFIG_CONFIG=Microsoft/config-wsl
- make -j12 modules_install KCONFIG_CONFIG=Microsoft/config-wsl
- sudo make -j12 install KCONFIG_CONFIG=Microsoft/config-wsl

### Expected Behavior

Install the kernel and out out 5.10.60.1 when using:
- uname -r 

### Actual Behavior

$ sudo make -j12 install KCONFIG_CONFIG=Microsoft/config-wsl
sh ./arch/x86/boot/install.sh 5.10.60.1-microsoft-standard-WSL2 arch/x86/boot/bzImage \
        System.map "/boot"
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.10.60.1-microsoft-standard-WSL2 /boot/vmlinuz-5.10.60.1-microsoft-standard-WSL2
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.10.60.1-microsoft-standard-WSL2 /boot/vmlinuz-5.10.60.1-microsoft-standard-WSL2
update-initramfs: Generating /boot/initrd.img-5.10.60.1-microsoft-standard-WSL2
W: Couldn't identify type of root file system for fsck hook
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 5.10.60.1-microsoft-standard-WSL2 /boot/vmlinuz-5.10.60.1-microsoft-standard-WSL2
run-parts: executing /etc/kernel/postinst.d/update-notifier 5.10.60.1-microsoft-standard-WSL2 /boot/vmlinuz-5.10.60.1-microsoft-standard-WSL2
run-parts: executing /etc/kernel/postinst.d/xx-update-initrd-links 5.10.60.1-microsoft-standard-WSL2 /boot/vmlinuz-5.10.60.1-microsoft-standard-WSL2

Output of uname -r:
5.10.16.3-microsoft-standard-WSL2

**Comment by OneBlue** [comment]
Hi @picatostas.

To use a custom wsl kernel, put the following in `%userprofile%/.wslconfig` : 

```
[wsl2]
kernel=C:\Path\To\Kernel
```
