### ISSUE TITLE
The console output of wsl.exe with unfriendly encoding

### ISSUE THREAD

**Issue by zhang616123** [microsoft/WSL#7767]
### Version

Microsoft Windows [版本 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

Not need

### Distro Version

NA

### Repro Steps

#Set your system lanuage to Chinese
PS > wsl.exe --list > test.txt
#the test.txt has garbled
PS > notepad.exe test.txt

### Expected Behavior

NA

### Actual Behavior

NA

**Comment by Jaykul** [comment]
Same problem also reported in https://github.com/microsoft/WSL/issues/7865
