### ISSUE TITLE
wsl2 won't start working?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/WSL#7768]
### Version

Microsoft Windows [版本 10.0.19044.1387]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu-20.04

### Repro Steps

When I type `wsl` in the windows power shell, the following error pops up, how do I fix it?
![1](https://user-images.githubusercontent.com/22857777/143802231-6789d349-8659-42ef-a435-7d1103a6e889.jpg)

![2](https://user-images.githubusercontent.com/22857777/143802234-ddf560cb-2d36-4087-bbe1-977ac369f54f.jpg)

### Expected Behavior

Working correctly

### Actual Behavior

nsenter: failed to parse pid: '77
78'

[已退出进程，代码为 1]

**Comment by Biswa96** [comment]
Do you have some custom script which runs after WSL2 distro starts?

**Comment by OneBlue** [comment]
@cuixing158: Are you using https://github.com/arkane-systems/genie ?

**Comment by cuixing158** [comment]
Sorry for the late reply to you guys, I've fixed the problem by restarting now. I did install[ this systemd script](https://github.com/DamionGans/ubuntu-wsl2-systemd-script) before this in order to install the gnome desktop, I don't know if this affected it.

**Comment by benhillis** [comment]
Yes, this is being caused by the unsupported systemd script you are using.

**Comment by garriton** [comment]
> Sorry for the late reply to you guys, I've fixed the problem by restarting now. I did install[ this systemd script](https://github.com/DamionGans/ubuntu-wsl2-systemd-script) before this in order to install the gnome desktop, I don't know if this affected it.

我也用了这个，然后一样的报错。请问您如何解决的，只需重启wsl就行吗
