### ISSUE TITLE
support scoop while winget is on holidays

### ISSUE THREAD

**Issue by BentramLawrence** [microsoft/WSL#7771]
### Version

version

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

this issue https://github.com/ScoopInstaller/Scoop/issues/4546

### Expected Behavior

crashes, panics, just bad support

### Actual Behavior

this is what im seein

**Comment by BentramLawrence** [comment]
they banned me because im black https://github.com/microsoft/vscode/issues/138080#issuecomment-981903154

**Comment by benhillis** [comment]
@BentramLawrence - That comment is not appropriate on this forum.
