### ISSUE TITLE
Unable to start react app

### ISSUE THREAD

**Issue by ovezjin** [microsoft/WSL#7775]
### Version

Microsoft Windwos [10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

openSUSE-Leap-15.3

### Other Software

create-react-app
I successfully created a project with "npx create-reate-app part1"
I‘m having trouble when i starting up with "npm start"
it's display "laptop-****:3000"
not "localhost:3000"
like this
![1](https://user-images.githubusercontent.com/37098200/144060632-871dd1fe-988d-4df8-a2ea-c932bf5fdaf9.png)
![2](https://user-images.githubusercontent.com/37098200/144060702-8bbdbef1-706d-483f-968f-caefeeb33e0c.png)

### Repro Steps

zypper in nodejs-common
zypper in npm
npx create-reate-app part1
cd part1
npm start

### Expected Behavior

i want display "localhost:3000"
and access it from a Windows app (like your Edge or Chrome internet browser) using localhost (just like you normally would).

### Actual Behavior

it display "laptop-*****:3000"
and can't access it from a edge browser using localhost .

**Comment by DjArt** [comment]
Use WSL1 for accessing apps by `localhost` hostname.

**Comment by OneBlue** [comment]
Hey @ovezjin, thanks for reporting this.

Indeed http://localhost:3000 should be the correct endpoint to access your app here.
When in doubt, you can use `netstat -lntp` to list the bound ports in WSL.

**Comment by ovezjin** [comment]
> Hey @ovezjin, thanks for reporting this.
> 
> Indeed http://localhost:3000 should be the correct endpoint to access your app here. When in doubt, you can use `netstat -lntp` to list the bound ports in WSL.

i can't access "localhost:3000" also
run `netstat -lntp`
![1](https://user-images.githubusercontent.com/37098200/144152122-d82ba213-0cb6-4286-a2ab-41f82dd22575.jpg)
it show "127.0.1.1:3000" not "127.0.0.1:3000"
and in the file `/etc/hosts`
there is `127.0.1.1 laptop-****`
This looks like the key to the problem ？

**Comment by ovezjin** [comment]
> Use WSL1 for accessing apps by `localhost` hostname.
I read the Microsoft documentation，it can access `localhost` in wsl2
and i need linux kernel

**Comment by OneBlue** [comment]
@ovezjin indeed it does look like `/etc/hosts`'s format might cause the app to bind the wrong ip address (127.0.1.1).

Does changing the line:

```
127.0.1.1 laptop-****
```

With:

```
127.0.0.1 laptop-****
```

And restarting the app help ?

**Comment by ovezjin** [comment]
> @ovezjin indeed it does look like `/etc/hosts`'s format might cause the app to bind the wrong ip address (127.0.1.1).
> 
> Does changing the line:
> 
> ```
> 127.0.1.1 laptop-****
> ```
> 
> With:
> 
> ```
> 127.0.0.1 laptop-****
> ```
> 
> And restarting the app help ?

yes, it's can solve the problem.
it's also display
`laptop-****:3000`
but i can access by `localhost:3000`

**Comment by OneBlue** [comment]
Awesome ! Closing this then.
