### ISSUE TITLE
WSL macchanger isn't working

### ISSUE THREAD

**Issue by B2K-oof** [microsoft/WSL#7779]
### Version

Microsoft Windows [Version 10.0.19042.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.4.0

### Distro Version

20.04

### Repro Steps

![image](https://user-images.githubusercontent.com/69972546/144117841-52718445-a83f-40f4-9cdb-83b2cc83b125.png)
![image](https://user-images.githubusercontent.com/69972546/144118452-ca956a00-b79c-4e95-b900-d4d1c6e6e785.png)

### Expected Behavior

The adapter should shut down and the mac should change.

### Actual Behavior

It can't read the permanent mac address and fails to change the mac address nor can it shutdown the adapter.

**Comment by Biswa96** [comment]
The MAC address is generated by Hyper-V Compute Network system and tied to that specific WSL2 VM's nat network endpoint.

**Comment by B2K-oof** [comment]
Then is it possible to spoof with wsl2? I've been trying to spoof but none of the methods I've encountered has worked.

**Comment by Biswa96** [comment]
Hope your intention is good 😇 It is possible to attach a new virtual network interface with known IP and MAC address. But it requires some programming. Also the IP address will not be same as of host Windows OS.

**Comment by B2K-oof** [comment]
Alright, thx for the answer. Time to find out how to do that.

**Comment by Biswa96** [comment]
If you are familiar with C or C++ programming I can try to help with a sample source code.

**Comment by Biswa96** [comment]
If you are familiar with C or C++ programming I can try to help with a sample source code. But remember this is not officially supported. You have to trust some random dude in The Internet.

**Comment by B2K-oof** [comment]
I'll do it on my own ig, since it isn't that important to me atm.
