### ISSUE TITLE
WSL can't connect to microsoft.com and some of its subdomains

### ISSUE THREAD

**Issue by Karl255** [microsoft/WSL#7789]
### Version

Microsoft Windows [Version 10.0.19043.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04, Ubuntu 18.04

### Other Software

microsoft.com
packages.microsoft.com
pypi.org

I wasn't able to find any other domains that exhibited this issue.

### Repro Steps

Run `curl -v https://microsoft.com` in WSL.

### Expected Behavior

`curl` manages to establish a secure connection and prints the returned data.

### Actual Behavior

`curl` gets stuck during the TLS handshake. I've left it for minutes and it just stayed at the same step, without crashing and showing an error.

```
$ curl -v https://microsoft.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 40.113.200.201:443...
* TCP_NODELAY set
* Connected to microsoft.com (40.113.200.201) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0^C⏎
```

### Diagnostic Logs

There are no issues with any of this outside WSL. I tried everything that got to my mind: using the same software for making network requests (curl, Insomnia...) on both Windows and WSL. It consistently works without issues on Windows and 99% of the time gets stuck at the TLS handshake in WSL. The very rare successful TLS handshakes I've experienced while trying to compile curl from source with [different TLS backends](https://curl.se/docs/install.html#select-tls-backend), though there was no pattern whatsoever in the successful connections. Every time I got a successful connection I tried to curl that same server again by specifying the IP address form curl's verbose output, but it never worked again which means the issue probably isn't at Microsoft's end. Other things I've tried: using a VPN, analyzing the network traffic with Wireshark, turning off the firewall and built-in AV, uninstalling networking-related software and whatnot.

I've been having this issue for at least 2 years now and during this time I've reinstalled Windows, reinstalled my WSL instances at least twice... but the issue still persisted during that whole time.

It would seem that the issue might be related to either #3761 or #5248, but no, they're both different, one being an issue with an AV and the other with a VPN.

Captured network traffic with Wireshark: [wsl-curl-wireshark-capture.zip](https://github.com/microsoft/WSL/files/7634514/wsl-curl-wireshark-capture.zip)

**Comment by Reintjuu** [comment]
I had exactly the same issue, and this fixed the issue for me: https://github.com/microsoft/WSL/issues/4698#issuecomment-728967624.

**Comment by gc250274** [comment]
Open windows firewall and add wsl application and check all the boxes and restart the computer.
This solved my connection issue.
