### ISSUE TITLE
Unnecessary network devices created

### ISSUE THREAD

**Issue by shemminger** [microsoft/WSL#7791]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Repro Steps

Tools that show list of network interfaces discover unwanted devices:  bond0, dummy0, etc

This is an unwanted side effect caused by bonding, dummy, etc being built into the kernel rather being loadable modules.
A workaround would be to add parameters to those modules to not have them create default devices.

### Expected Behavior

I would expect:
```
$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128
eth0             UP             192.168.126.91/20 fe80::215:5dff:feee:2fe/64
```

### Actual Behavior

What I see when doing network device commands is.
```
$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128
bond0            DOWN
dummy0           DOWN
tunl0@NONE       DOWN
sit0@NONE        DOWN
eth0             UP             192.168.126.91/20 fe80::215:5dff:feee:2fe/64
```

**Comment by zer0-memory** [comment]
> This is an unwanted side effect caused by bonding, dummy, etc being built into the kernel rather being loadable modules.
> A workaround would be to add parameters to those modules to not have them create default devices.

Do you know what settings I would have to change in the kernel to stop these from being created? I found the setting to disable sit0, but I'm not sure about tunl0; I have to disable them as due to their abnormal MAC address length a program I'm using is getting a segfault since it tries reading their MAC address for license activation

**Comment by Biswa96** [comment]
Those network interfaces are enabled by default. Generally those do not interfere with eth0 or any network operations. If you want to remove those network interface you can use basic `ip` commands.

```sh
sudo ip link delete dummy0
sudo ip link delete bond0
```

Or you can disable creation of dummy0 by recompiling Linux kernel with `CONFIG_DUMMY` disabled.

It is possible to set a MAC address by creating a new virtual network and endpoint, detach the old one and attach the new one in WSL2.

**Comment by zer0-memory** [comment]
> Those network interfaces are enabled by default. Generally those do not interfere with eth0 or any network operations. If you want to remove those network interface you can use basic `ip` commands.
> 
> ```shell
> sudo ip link delete dummy0
> sudo ip link delete bond0
> ```
> 
> Or you can disable creation of dummy0 by recompiling Linux kernel with `CONFIG_DUMMY` disabled.
> 
> It is possible to set a MAC address by creating a new virtual network and endpoint, detach the old one and attach the new one in WSL2.

I'm only able to delete **dummy0** and **bond0** with **ip link delete**, I'm having a problem with **sit0** and **tunl0** though, they have the MAC address 00-00-00-00 which is an abnormal size as usually MAC addresses are in the form **xx-xx-xx-xx-xx-xx**; this is causing a segmentation fault on a program I'm trying to use. 

Do you know which settings I would need to disable in the kernel to disable the **sit0** and **tunl0** interfaces?

**Comment by shemminger** [comment]
The root cause is that WSL kernel is monolithic and does not use kernel modules.
Some of these drivers allow setting module parameters that might help. But these would have to go on kernel boot command line, not sure how to change that with WSL.
Examples:

- bonding.max_bonds=0|
- dummy.numdummies=0
- fb_tunnels=0

**Comment by Biswa96** [comment]
Linux kernel command line options can be added in .wslconfig file. Create a `.wslconfig` file in `%UserProfile% directory and add the lines like this

```ini
[wsl2]
kernelCommandLine = bonding.max_bonds=0 dummy.numdummies=0 fb_tunnels=2
```

Run `wsl.exe` to forcefully shutdown WSL2 VM and re-run the Linux distribution in WSL2.

**Comment by zer0-memory** [comment]
> Linux kernel command line options can be added in .wslconfig file. Create a `.wslconfig` file in `%UserProfile%` directory and add the lines like this
> 
> ```ini
> [wsl2]
> kernelCommandLine = bonding.max_bonds=0 dummy.numdummies=0 fb_tunnels=2
> ```
> 
> Run `wsl.exe --shutdown` to forcefully shutdown WSL2 VM and re-run the Linux distribution in WSL2.

This removed the **dummy0** and **bond0** interfaces for me, but **sit0** and **tunl0** are still there. Are there any other settings needed to remove those?

**Comment by Biswa96** [comment]
> but sit0 and tunl0 are still there. 

Those do not have any MAC address.

> it tries reading their MAC address for license activation but tries reading beyond their length.

Wait a second! It seems that the issue is with that software. Why does a software (or a spyware) scan all available network interfaces?

> I'm having a problem with sit0 and tunl0 though, they have the MAC address 00-00-00-00

They don't have MAC address. Only bond0 and dummy0 have MAC address which are in valid format always.

**Comment by zer0-memory** [comment]
> > but sit0 and tunl0 are still there.
> 
> Those do not have any MAC address.
> 
> > it tries reading their MAC address for license activation but tries reading beyond their length.
> 
> Wait a second! It seems that the issue is with that software. Why does a software (or a spyware) scan all available network interfaces?
> 
> > I'm having a problem with sit0 and tunl0 though, they have the MAC address 00-00-00-00
> 
> They don't have MAC address. Only bond0 and dummy0 have MAC address which are in valid format always.

It reads them for licensing purposes; this is the strace output from the application:
`ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr={sa_family=ARPHRD_LOOPBACK, sa_data=00:00:00:00:00:00}}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="eth0", ifr_hwaddr={sa_family=ARPHRD_ETHER, sa_data=00:15:5d:55:c2:20}}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="tunl0", ifr_hwaddr={sa_family=ARPHRD_TUNNEL, sa_data=00:00:00:00}}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="sit0", ifr_hwaddr={sa_family=ARPHRD_SIT, sa_data=00:00:00:00}}) = 0
read(4, "", 1024)                       = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffff600400} ---
+++ killed by SIGSEGV +++
Segmentation fault`

Is there something I can change in the config-wsl file for the kernel to remove these interfaces? I tried turning off **CONFIG_NET_IPIP** and **CONFIG_IPV6_SIT** but I get errors while compiling the kernel with those settings.

**Comment by benhillis** [comment]
This is not an area I'm very experienced in, what would the implications be of setting max_bonds, numdummies, and fb_tunnels to zero / none?  Would this break any existing workflow?

**Comment by shemminger** [comment]
I doubt it would cause problems, these default devices are a legacy thing from early days of Linux (like 10+ yrs ago).
Earlier versions of WSL kernel did not appear to have this.

**Comment by benhillis** [comment]
@shemminger - thanks for the context - I'll see if I can figure out why these got added.

**Comment by zer0-memory** [comment]
> 

I 

> This is workaround that worked for me
> 
> ```
> kernelCommandLine = bonding.max_bonds=0 dummy.numdummies=0 fb_tunnels=none
> ```
> 
> Any license code that reads list of available network devices is broken. There is no way to be sure network device MAC address is not changed or will be the same under a whole range of scenarios.
> 
> One could argue all DRM code is fundamentally flawed.

I fixed my segfault, turned out that it wasn't caused by the extra network devices; I fixed it by adding "vsyscall=emulate" to my kernelCommandLine. I'm still trying to work out how to keep the MAC address on WSL constant while keeping the network connection working, if you know how I could go about doing that please let me know.

**Comment by romarowski** [comment]
how would you go about recovering these extra networks if they suddenly dissappeared?

**Comment by shemminger** [comment]
These devices are not useful or used. Modern Linux distros handle device management using network manager or related infrastructure.

**Comment by zer0-memory** [comment]
> ok, but I need bond0 to verify my MATLAB license,

Same here

**Comment by shemminger** [comment]
Then make a dummy bond device with command line or with  /etc/network/interfaces.

**Comment by shareefj** [comment]
For others who have come here looking for a solution after their tools stop working, add the following to your `.bashrc`:

```shell
# Define the interface name and MAC address 
ifname=bond0
wantmac=<your_mac_here>

# Check if the interface already exists
ip link show $ifname |& grep -q ether 
if [[ $? ]]; then
    sudo ip link add $ifname type bond
fi

# Set the MAC address if it's different to what we want
mac=$(ip link show $ifname | awk '/ether/ {print $2}')
if [[ $mac != $wantmac ]]; then
    sudo ip link set dev $ifname address $wantmac
fi
```
