### ISSUE TITLE
Breaking Changes by Docker GUI Contracts required on Jan 1

### ISSUE THREAD

**Issue by chadbrewbaker** [microsoft/WSL#7793]
### Version

NA

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

NA

### Distro Version

NA

### Other Software

Docker Desktop after license change which goes into effect Jan 1.

### Repro Steps

Megacorp IT sent out a nastygram today warning that the Docker Desktop GUI can no longer be used without signing a contract and paying Docker for enterprise licencing.

### Expected Behavior

A way to allow toggling of Docker container access to WSL2 instances without paying an enterprise license for the Docker GUI.

### Actual Behavior

I need a third party contract for the GUI feature I need - the toggle that allows WSL2 instances to access Docker containers. 

### Diagnostic Logs

NA

**Comment by chadbrewbaker** [comment]
CC @tyhicks  @lramos15 - the current best path for installing WSL2 on enterprise machines is to install the VSCode remote extension. Might be some cross cutting concerns with the vscode team.

**Comment by chadbrewbaker** [comment]
@sickcodes I don't know the strace equivalent on Windows or else I would try to reproduce with a Powershell script. Customers paying Microsoft and Apple licenses should not also need a Docker license to connect to DockerOSX from WSL2. Step 4 is what needs to be traced https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

**Comment by benhillis** [comment]
This is a Docker issue, not WSL actionable.

**Comment by chadbrewbaker** [comment]
Your documentation breaks on January 1 and every WSL2 user will have to reach for their wallet. This means megacorp buying more M1 laptops and less Windows11 due to the extra expensing headache. I’ll try the Rancher workaround https://jason-umiker.medium.com/replacing-docker-desktop-with-wsl2-and-or-rancher-desktop-on-windows-5e036f9dc3a4

**Comment by craigloewen-msft** [comment]
@chadbrewbaker are you able to run Docker instances directly inside of WSL using instructions like these: https://docs.docker.com/engine/install/ubuntu/

**Comment by Biswa96** [comment]
Crazy idea! What if the system distro will act a docker server 🤯

**Comment by Biswa96** [comment]
What if the system distro will act a docker server.

**Comment by benhillis** [comment]
Good call, we will update our docs.
