### ISSUE TITLE
with latest nodejs and npm while starting react application getting "digital envelope routines::unsupported" error

### ISSUE THREAD

**Issue by gulshanmudgal** [microsoft/WSL#7795]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

**Steps to reproduce**
1. Create new vanilla react app using the command: "npx create-react-app test-app --template typescript"
2. Go to the app directory
3. Try starting the application by typing "npm start"
4. Observe the error.

**Prerequisites:**
NodeJs version: v17.1.0
npm version:  8.1.2

**Workaround:**
in package.json replace start script with "start": "react-scripts --openssl-legacy-provider start"

### Expected Behavior

The application should start correctly.

### Actual Behavior

Throws exception that digital envelope routines::unsupported

**Comment by OneBlue** [comment]
Thanks for reporting this @gulshanmudgal, this does not look like a WSL issue so closing this

**Comment by gulshanmudgal** [comment]
looks like it's time to upgrade the open SSL algorithms used in WSL. 
Someone can correct me here.
