### ISSUE TITLE
windows files owned by root 

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#7798]
### Version

Version 10.0.22000.348

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Starting a terminal puts me in /mnt/c/Users/mlwp if I do "ls -l" all windows files are shown as being owned by root but I set my default Linux user by 

ubuntu.exe config --default-user mwoodpatrick

How to debug/fix

### Expected Behavior

I expect all my windows files to show up as owned by mwoodpatrick as documented in

https://docs.microsoft.com/en-us/windows/wsl/file-permissions

### Actual Behavior

All windows files shown as user and group both being root

    drwxrwxrwx 1 root root

**Comment by Biswa96** [comment]
What does this command show `mount | grep -i C:`

**Comment by mwoodpatrick** [comment]
mount | grep -i C:
drvfs on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)

**Comment by Biswa96** [comment]
The uid and gid options are zero, means root. Generally it should be 1000. Close all the WSL instances with `wsl.exe --shutdown` command. Then just run wsl.exe from command prompt. Does that change anything?

**Comment by mwoodpatrick** [comment]
Yes that does change the uid/gid for the mount command. I actually have multiple distributions and different distributions appear to be using different uid/gid values any idea where these values afre coming from I did not see anything in the /etc/fstab of the distribution

**Comment by Biswa96** [comment]
AFAIK, init grabs the uid from default user of that running distribution.

**Comment by mwoodpatrick** [comment]
The default user is the same for all the distributions so this does not seem to explain the difference I'm seeing

**Comment by benhillis** [comment]
Do you have any settings in `/etc/wsl.conf`?

**Comment by mwoodpatrick** [comment]
cat /etc/wsl.conf
# [network]
# generateResolvConf = false

**Comment by rmdes** [comment]
I have this issue for a folder, it's owned by root albeit it's a windows folder from my D: drive
I have this on my /etc/wsl.conf

`[boot]
systemd=true

[automount]
options = "metadata"
`

**Comment by aetelani** [comment]
Remounting with proper user fixed issue for me
`sudo umount /mnt/c; sudo mount -t drvfs C: /mnt/c -o metadata,uid=1000,gid=1000`
