### ISSUE TITLE
ping (DUP!) error in WSL2 after upgrading to windows 11

### ISSUE THREAD

**Issue by saiyen2002** [microsoft/WSL#7799]
I just recently upgraded to windows 11, OS build 22000.348.
I am using WSL2 kernel version 5.10.60.1 with Ubuntu 20.04.

I am noticing when i ping i get duplicate or damaged packets error

```
arahman10@DESKTOP-A0169SA:~$ ping www.google.com
PING www.google.com (216.58.212.196) 56(84) bytes of data.
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=1 ttl=114 time=14.1 ms
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=1 ttl=114 time=14.1 ms (DUP!)
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=2 ttl=114 time=14.2 ms
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=2 ttl=114 time=14.2 ms (DUP!)
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=3 ttl=114 time=15.4 ms
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=3 ttl=114 time=15.4 ms (DUP!)
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=4 ttl=114 time=15.4 ms
64 bytes from ams16s21-in-f196.1e100.net (216.58.212.196): icmp_seq=4 ttl=114 time=15.4 ms (DUP!)
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 received, +4 duplicates, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 14.136/14.784/15.444/0.616 ms
```

i do not get the same error when doing it from my native powershell.

**Comment by QrackEE** [comment]
Hi, I may not be very helpful at this moment, but I just noticed that too. However, I also noticed my local network acting weird on native system too, ie. Zenmap has trouble accessing network port resource and I can't ping RPi devices which I can access from other machines. Interestingly, I have some linux machine in my network which I can access with no problem... 
At this moment I am looking at some weird native Windows quirk - can you check similar cases in your local network too?

**Comment by kxtcd950** [comment]
I am seeing this too:

```
$ ping -c 4 192.168.248.15
PING 192.168.248.15 (192.168.248.15) 56(84) bytes of data.
64 bytes from 192.168.248.15: icmp_seq=1 ttl=63 time=400 ms
64 bytes from 192.168.248.15: icmp_seq=1 ttl=63 time=400 ms (DUP!)
64 bytes from 192.168.248.15: icmp_seq=2 ttl=63 time=1013 ms
64 bytes from 192.168.248.15: icmp_seq=2 ttl=63 time=1013 ms (DUP!)
64 bytes from 192.168.248.15: icmp_seq=3 ttl=63 time=921 ms
64 bytes from 192.168.248.15: icmp_seq=3 ttl=63 time=921 ms (DUP!)
64 bytes from 192.168.248.15: icmp_seq=4 ttl=63 time=0.999 ms
--- 192.168.248.15 ping statistics ---
4 packets transmitted, 4 received, +3 duplicates, 0% packet loss, time 3013ms
rtt min/avg/max/mdev = 0.999/667.642/1013.570/369.384 ms, pipe 2

```
I have tried resetting the network stack, as mentioned elsewhere on the internet:
```
wsl --shutdown
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns

```
And also (from an elevated powershell prompt) this from the internet:
```
Restart-Service LxssManager
```
To absolutely no avail; the same duplicated ping packets are still received.

If I do a packet capture using Wireshark on the Windows' network interface connected to the network in question, I only see the correct packets captured (a count of 8 packets - 4 requests, 4 replies).  So the device at the far end is only sending one packet back, therefore no switch in the chain (there's only one anyway) is echoing/mirroring the requests back to the computer.

Windows 11 as the host OS.

**Comment by elduds** [comment]
I have seen the same issue on Win11. In Hyper-V manager, on top of the WSL vSwitch, I had an additional external/bridged virtual switch configured. Deleting this switch resolved the issue. 

However I've been unable to re-create the problem by re-creating the switch, but it sure seems related.

**Comment by pabloisaak** [comment]
I was able to solve this issue. Here's how

1. Open Hyper-V
2. Click on Virtual Switch Manager
3. Select the your virtual switch
4. Deselect the option to "Allow management operating system to share this network adapter"

Hope this helps!
