### ISSUE TITLE
WSL completely broken

### ISSUE THREAD

**Issue by jaknapp** [microsoft/WSL#7800]
### Version

Microsoft Windows [Version 10.0.19044.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Other Software

Most recent software install was NoMachine.

### Repro Steps

Run any WSL command or try to open WSL. For example, `wsl -l -v` prints out usage.

Note, I have been using WSL for a year or more with no issues. I haven't done anything recently that I know of to affect it.

### Expected Behavior

WSL opening bash terminal and parsing CLI arguments.

### Actual Behavior

Prints usage always.

**Comment by Biswa96** [comment]
Please provide the logs as stated here https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

**Comment by jaknapp** [comment]
https://aka.ms/AAf38k7

**Comment by benhillis** [comment]
@jaknapp - unfortunately I'm not seeing any WSL logs in that trace. Did you do a repro trace and attempt launching WSL during the recording?

**Comment by jaknapp** [comment]
Yes I did

**Comment by jaknapp** [comment]
`wsl -l -o` works. I guess somehow I just lost my installed distribution? Is there a way to recover that?
