### ISSUE TITLE
Error 0x80041002 while Installing or Converting (No Comodo)

### ISSUE THREAD

**Issue by Marly212** [microsoft/WSL#7804]
### Version

Microsoft Windows [Version 10.0.19044.1387]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

1. Install Subsystem for Linux
2. Install Virtual Platforms
3. Reboot
4. Download Ubuntu from the MC Store
5. Try to Install it

### Expected Behavior

The Installation of Ubuntu is working and not crashing

### Actual Behavior

![grafik](https://user-images.githubusercontent.com/42452096/144991567-c200a0d1-f4c2-4a77-915b-1ef413ab11ff.png)

Getting this error while Installing

### Diagnostic Logs

[jzs3c232.vax.zip](https://github.com/microsoft/WSL/files/7666635/jzs3c232.vax.zip)

WSL Log 
[wsl.zip](https://github.com/microsoft/WSL/files/7666844/wsl.zip)

If you need further log files, pls tell me

**Comment by ChrisPHL** [comment]
Any news on this issue in the meanwhile?

I encounter nearly the same issue:
```
PS C:\WINDOWS\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-20.04 2
Die Konvertierung wird ausgeführt. Dieser Vorgang kann einige Minuten dauern...
Informationen zu den wichtigsten Unterschieden zu WSL 2 finden Sie unter https://aka.ms/wsl2
Fehler: 0x80041002
PS C:\WINDOWS\system32>
```
Btw: This error message appears when I try the above mentioned steps by Marly212, too. I'm even using the same Windows version.

This needs to be fixed soon. :-|

**Comment by ChrisPHL** [comment]
Update:
I solved the issue on my computer by editing group policy as shown:
![grafik](https://user-images.githubusercontent.com/314065/182771941-83a61c63-6544-47d2-b0be-7429f7f1ee82.png)

The configuration showed "actived" before, which seemed to cause the error.

Hope that helps some people out there.


Kind regards
Christian
