### ISSUE TITLE
Is windows11 capable of installing KDE desktop?

### ISSUE THREAD

**Issue by dongwhfdyer** [microsoft/WSL#7811]
### Version

22000.318

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

I have tried a tons of times on installation of KDE desktop. I downloaded Ubuntu 20.04 from Microsoft Store and tried different way to install a KDE desktop. After following the steps and noticing the "finishing signs", all I can see is the blank and black console as before. 
In the picture below, I clicked the sddm choice and restarted the apps because most tutorials requires us to reboot while it's just a app so I restarted the app.
![image](https://user-images.githubusercontent.com/59996817/145352413-b7ef51b9-a51c-4300-81e7-07956f8dd418.png)

Then I could only see empty console. Maybe I have installed it but I still don't know how to launch it. Or else, I simple didn't follow the right steps. Or maybe, Win11 is not capable of installing the KDE desktop.
But I DON'T KNOW THE REASON. Can someone help me?🙏 

### Repro Steps

Just following the instructions on many tutorials of installation of KDE desktop. 
Like 
1.  
` sudo apt install kde-full`
2. 
```
sudo apt update
sudo apt upgrade
sudo apt install kubuntu-desktop
```

3. `sudo apt install kde-plasma-desktop`

Those are things I tried. Everything went smoothly when I was doing those steps. But all of them comes to the same scenario that nothing happened but blank console left.

### Expected Behavior

A normal KDE desktop after installing. 

### Actual Behavior

Nothing but blank and black console as usual.
![image](https://user-images.githubusercontent.com/59996817/145352628-8f98e796-d3a4-4c24-be42-0ee03d73e026.png)

**Comment by sirredbeard** [comment]
WSLg is not really intended to run a full replacement desktop shell, it is intended to run individual Linux applications.

It _is_ possible to get KDE Plasma running on WSL, you need to start several services and then Plasma manually. gdm or lightdm will not work.

It is easier to get individual components, like xfce4-panel, working than an entire DE.

It is even possible, with registry changes, to replace the default Explorer shell with a script that runs KDE Plasma or XFCE. https://twitter.com/unixterminal/status/1385081856174043137?s=20

Question though is, why do you want to do that? It's a fun hack, but has limited usefulness.

If you want to use Kate or Kdevelop, just install those.
