### ISSUE TITLE
Can't access Linux filesystem from Windows 

### ISSUE THREAD

**Issue by Jeroeny** [microsoft/WSL#7812]
### Version

WSL-versie: 0.50.2.0 
Kernelversie: 5.10.74.3 
WSLg-versie: 1.0.29 
Windows-versie: 10.0.22000.348

### WSL Version

- [X] WSL 2
- [ ] WSL 1

Installed via Microsoft Store (https://aka.ms/wslstorepage).

### Kernel Version

Linux version 5.10.74.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Mon Oct 18 19:27:44 UTC 2021

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop 4.3.0
PhpStorm 2021.3 (with a deployment config to sync files to a Linux directory)

### Repro Steps

After a fresh (re)boot, accessing Linux files works. But after a while, the link/mount to the Linux distro breaks. Accessing the `\\wsl$\Ubuntu` or `\\wsl.localhost` will hang. E.g. executing `dir \\wsl$\Ubuntu` in powershell or using Explorer to go to Network -> Linux -> Ubuntu will cause the command to hang or the Explorer window to keep loading.

### Expected Behavior

To be able to access the Linux directories.

### Actual Behavior

Hanging command or Explorer on an attempt to read something from a Linux filesystem.

### Diagnostic Logs

`Trace-Command dir \\wsl$\Ubuntu` also hangs.

`wsl --shutdown` doesn't help. Only rebooting my PC makes the filesystem accessible again (temporarily).

When I used Docker desktop, it created two distros. Those were still accessible (`docker-desktop` and `docker-desktop-data`).
Though I use `docker.io` inside wsl directly at the moment, with the daemon also running inside wsl.

Feedback issue: https://aka.ms/AAf45u9

Other issues I've read and tried to fix my problem with no success:
https://github.com/microsoft/WSL/issues/2613 https://github.com/microsoft/WSL/issues/4027 https://github.com/microsoft/WSL/issues/4260 https://github.com/microsoft/WSL/issues/4936 https://github.com/microsoft/WSL/issues/4992 https://github.com/microsoft/WSL/issues/5718 https://github.com/microsoft/WSL/issues/5821

**Comment by Jeroeny** [comment]
Possible related: https://github.com/microsoft/WSL/issues/7773 https://github.com/microsoft/WSL/issues/7782

**Comment by korpa** [comment]
Same issue: #7479

**Comment by wojtas** [comment]
Same here.
