### ISSUE TITLE
generateResolvConf = false doesn't work

### ISSUE THREAD

**Issue by iranvir** [microsoft/WSL#7816]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

I have noticed the following behaviour on my Windows 11 Build:

1. I create the following entry in /etc/wsl.conf:
```
[network]
generateResolvConf = false
```
2. I remove /mnt/wsl/resolv.conf and the symlink to this file, i.e., /etc/wsl.conf

3. I create a new /etc/resolv.conf file with the contents `nameserver 1.1.1.1`

4. I shutdown wsl using `wsl --shutdown` command

5. I restart wsl

6. The file /etc/resolv.conf has been removed and the /mnt/wsl/resolv.conf has been regenerated.

My other settings in wsl.conf (like default user) works, but everytime the subsystem is restarted, I have to manually create resolv.conf file.

Reproducible on Ubuntu and Alpine Linux

### Expected Behavior

I expect WSL2 to not remove (or overwrite) my `/etc/resolv.conf` file after every WSL2 restart.
If possible, I would love to have a global option to completely disable this feature from using `.wslconfig` option.

### Actual Behavior

After setting `generateResolvConf = false` in wsl.conf. WSL2 **removes** my custom `/etc/resolv.conf` after every restart.

**Comment by ggrn** [comment]
I think `wsl` always update `/mnt/wsl/resolv.conf` and `wsl.conf`'s `generateResolvConf = false` option just affects to recreation of symlink.


resolve issue steps >> 

1. remove or backup resolv link file. `sudo mv /etc/resolv.conf /etc/resolv.conf.bak`
2. hard copy resolv file from link origin. `sudo cp /mnt/wsl/resolv.conf /etc/resolv.conf`
3. edit resolv (`vi`, `nano`, ...)
4. restart resolv using `wsl --shutdown`
5. check resolv `wsl cat /etc/resolv.conf`
6. ping `ping google.com` successfully


(Windows 11, Ubuntu distro)

**Comment by iranvir** [comment]
Didn't work. The custom `/etc/resolv.conf` file is still being removed (not even being replaced by the default symlink, just removed)
Also not sure why there's a need to oopy the `/mnt/wsl/resolv.conf` to `/etc/resolv.conf` and then edit it. But I did it anyways.

**Comment by sboden** [comment]
The commands to execute are as follows:

```
sudo rm /etc/resolv.conf
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "[network]" > /etc/wsl.conf'
sudo bash -c 'echo "generateResolvConf = false" >> /etc/wsl.conf'
sudo chattr +i /etc/resolv.conf
```

Then restart WSL2. I took the google DNS 8.8.8.8, but you can take another IP address.

**Comment by benhillis** [comment]
This behavior has been tweaked in 0.56.3

**Comment by iranvir** [comment]
Tweaked in what way?
Also how do we switch to that particular version?

**Comment by nmofonseca** [comment]
> This behavior has been tweaked in 0.56.3

Hi @benhillis ,

Can you please provide more details?

I just upgraded windows 10 to windows 11 and now I am facing this exact issue. 

/etc/wsl.conf is correctly  setup, no symbolic link, everytime I reboot the laptop or shutdown my wsl ,  boom, resolv.conf gone.

This was working just fine in windows 10 btw.

I would like to see this open again, it doesn't seem to be fixed

**Comment by Killerbear** [comment]
same problem here
i got a new workstation at work with windows 11 and now i have the same issue.
WSL in Windows 11 seems to delete the resolv.conf file if generateResolvConf is set to false.

**Comment by nmofonseca** [comment]
Hello @Killerbear ,

There was another thread where I also commented and I got a solution there, you will need to update to one of the latest releases manually.

#8030  check onomatopellan reply to my comment, it explains where you can get it and how to install it.

Hope that helps
