### ISSUE TITLE
Windows Firewall is blocking access of entire WSL distro to network after update to the Store version on Windows 11 Dev ring

### ISSUE THREAD

**Issue by dckface** [microsoft/WSL#7823]
### Version

10.0.22518.1012

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Arch WSL (rolling distro)

### Other Software

Windows Firewall apparently

### Repro Steps

After upgrading WSL to the Store version (through `wsl --update`) on the most recent Windows 11 Dev ring update, the WSL distros lost access to the internet. Running any command that requires network access times out, unless I manually deactivate Windows Firewall on the host for Public networks (I'm being connected to the Private network though).

Basically, following steps reproduce it for me:
1. Update WSL to the Store version on the most recent Windows 11 Dev update (`wsl --update`).
2. Open any distro.
3. Run any command requiring network access (i.e. `sudo pacman -Syu`)

### Expected Behavior

All network traffic should go through, just like before the update to the Store version.

### Actual Behavior

The commands requiring network access just time out. After deactivating Windows Firewall on the host machine for the Public networks (regardless of the network type the host is currently connected to), everything works as expected, and without any issues.

**Comment by OneBlue** [comment]
Thanks for reporting this @dckface.

Can you please follow the ['networking issues' section](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and share the script output ?
