### ISSUE TITLE
WSLg not working inside a tmux session

### ISSUE THREAD

**Issue by NikZy** [microsoft/WSL#7825]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

tmux 3.1c
gedit - Version 40.1

### Repro Steps

1. Start WSL `wsl`
2. Start new tmux session `tmux` 
3. Open gedit `gedit`

### Expected Behavior

Expected gedit to open.

### Actual Behavior

Nothing happens in the terminal, as if it succseffully launched gedit, but no X window is launched on windows.
Everything works as expected outside tmux.

**Comment by benhillis** [comment]
I'm not able to reproduce this with the store version of WSL.
