### ISSUE TITLE
Both, WSL and `wsl` command stop working after a while

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/WSL#7826]
I have some strange issue, where WSL would hang after some time, preventing me from opening new sessions or even executing the `wsl` command itself.

## Steps to reproduce

- Docker Desktop running
- Open one or multiple _WSL2 sessions_ (tabs) within Microsoft Terminal
- Open VSCode _Remote WSL_
- Run some intensive tasks (NodeJS servers) inside WSL in one of the sessions

## Actual behavior
- Opening another _WSL-session (tab)_ within Microsoft Terminal does not open a new WSL session, nor does it throw an error. 
- Working within already opened sessions  (tabs) works just fine.
- Working within existing VSCode session still works
- Opening a new VSCode session does not work
- Opening a _PowerShell_ session within the terminal works, **but** executing `wsl --list` within PowerShell just hangs.
- Running `wsl --shutdown`  also hangs, which prevents me from at least restarting WSL

## Expected behavior
WSL and `wsl` should work. Opening WSL sessions should work. Running `wsl --list` should list the installed distros, etc...

# Question
Is there a way to see *logs/errors* of WSL/Hyper-V to evaluate what could be wrong?

## System

- Windows build 22518
- Docker Desktop 4.3.0

**Comment by ilsme** [comment]
- Windows build 22000.376

I have exactly the same problem:
- After something happens to WSL during the intensive WSL system usage(in my case compilation of the big C++ project using Ninja)  any `wsl ..` command just hanging for some significant amount of time, I thought it hangs forever but seems it actually worked after some time.
- The `wsl --shutdown` command actually works after hanging for 10-15 minutes.
- All VSCode Remote WSL sessions were disconnected in my case, no new sessions or terminals were able to be opened, I tried to restart the `LxssManager` but with no luck, it was in a `stopping` state.
- Already opened terminals are working, I can see the following error messages in dmesg:

> [26825.546540] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546542] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546544] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546546] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546547] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546549] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.546551] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26825.563548] init: (645) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26963.738262] init: (31241) ERROR: InitCreateProcessUtilityVm:1748: write failed 32
[26963.752690] init: (31241) ERROR: InitCreateProcessUtilityVm:1885: recv failed 0 32

I believe this problem appeared after the `KB5008215` update was installed on my system, at least I didn't notice such a problem before, but after this update was installed I had this problem twice in a couple of hours.

**Comment by ad-on-is** [comment]
@ilsme What distro are you running in your WSL? 
I use Arch. (no pun intended)

**Comment by ilsme** [comment]
@ad-on-is Ubuntu 20.04.

**Comment by ad-on-is** [comment]
Thx, at least a distro specific issue can be ruled out

**Comment by wlwtvr** [comment]
Hi, I also encountered the very same problem just yesterday. After some digging, I managed to fix the issue by enabling dev channel in windows insider program settings. Got the clue from #7644 . If somehow you don't have dev channel option available because windows 11 upgrade are not supported, you can try this [workaround](https://winaero.com/how-to-enable-windows-11-dev-channel-on-unsupported-device/) to enable it. Good luck!
