### ISSUE TITLE
WSL Windows Feature to WSL Windows Store

### ISSUE THREAD

**Issue by Wizards-god** [microsoft/WSL#7828]
Hi, I wanted to know if transitioning from the WSL(available as a windows feature) to WSL that is available in the Store delete the data of my Linux distros(I have 2 of them). Or delete my distros entirely.
I couldn't find an answer to this anywhere online, so I opened it as an issue.

**Comment by Biswa96** [comment]
Theoretically, it should not delete any installed distribution. WSL Store version just registers new COM server and file aliases.

**Comment by Wizards-god** [comment]
So I can safely uninstall(remove) the windows feature that enables wsl(i have WSLg installed). And install the Store version without the loss of any data.

**Comment by herrwinfried** [comment]
in file explorer and when a new app is installed it wasn't showing up in the latest store version fixed this?

**Comment by benhillis** [comment]
@Wizards-god - correct. The optional component gets you two things:
1. WSL1 support
2. File explorer integration (we're working on brining this to the store version as well)

**Comment by Wizards-god** [comment]
> @Wizards-god - correct. The optional component gets you two things:
> 
> 1. WSL1 support
> 2. File explorer integration (we're working on brining this to the store version as well)

Which component brings file explorer integration?
I didn't quite get you there
