### ISSUE TITLE
Unable to mount disk to non-administrator user

### ISSUE THREAD

**Issue by natanbc** [microsoft/WSL#7829]
### Version

WSL version: 0.50.2.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu 20.04

### Repro Steps

Running `wsl --mount <disk> --bare` fails as expected when running as a regular user:
```
PS C:\Users\Natan> wsl --mount \\.\PHYSICALDRIVE1 --bare
Administrator access is needed to mount a disk.
PS C:\Users\Natan> wsl --list -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```
But when running as an administrator, it cannot find any distros, because those are installed on my (non administrator) account:
```
PS C:\WINDOWS\system32> wsl --mount \\.\PHYSICALDRIVE1 --bare
This operation is only supported by WSL2.
PS C:\WINDOWS\system32> wsl --list -v
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore 
```

### Expected Behavior

Being able to mount disks to distros running under non-administrator accounts.

### Actual Behavior

Only administrator accounts can mount disks with `wsl --mount`

**Comment by nichite** [comment]
I get this issue even though my user is an Administrator and I'm using an elevated Powershell prompt. Is this possibly a different problem?
