### ISSUE TITLE
WSL 2 Not starting

### ISSUE THREAD

**Issue by Wizards-god** [microsoft/WSL#7831]
### Version

Microsoft Windows [Version 10.0.22000.348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04(maybe), Arch Linux

### Other Software

PowerToys
Zoom
Cisco Webex
Cloudflare
Spotify
Windows Terminal
Glasswire

### Repro Steps

Open Ubuntu.

### Expected Behavior

Ubuntu to start normally, and I continue on my work.

### Actual Behavior

It exits with this error.
The operation timed out because a response was not received from the virtual machine or container.

[process exited with code 4294967295]

**Comment by Wizards-god** [comment]
This issue has been opened as #5092 and #4929, But none of the solutions seems to work for me. I have even tried completely uninstalling WSL, Hyper-V and all kinds of virtualisation features. But none of them works. So I thought I'd open a new issue in the hope to get my issue resolved.

**Comment by Wizards-god** [comment]
I have logged it in the Feedback hub app

**Comment by Wizards-god** [comment]
Could you find time to look into my issue

**Comment by OneBlue** [comment]
Thanks @Wizards-god. Can you please share the link to your feedback hub entry ?

**Comment by Wizards-god** [comment]
> Thanks @Wizards-god. Can you please share the link to your feedback hub entry ?

https://aka.ms/AAf6ee8 , Here is the link to my issue on Feedback Hub.

**Comment by OneBlue** [comment]
Thanks @Wizards-god.

Looking at the logs, I can see:

```
[   36.631216] EXT4-fs (sdc): VFS: Can't find ext4 filesystem
[   36.631819] ERROR: Mount:2683: mount(/dev/sdc, /distro, ext4, 0x0, discard,errors=remount-ro,data=ordered
```

Based on that, it looks like your distribution VHD is corrupted. 

Can you share the content of `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss` ? The path to the distribution VHD is under that key.

**Comment by Wizards-god** [comment]
I did not know how to export individual keys, so just exported it and attached it here
[VHD.txt](https://github.com/microsoft/WSL/files/7732031/VHD.txt)
<img width="715" alt="image" src="https://user-images.githubusercontent.com/70703332/146488132-d4d524c8-06b5-4775-a700-c5cb3a83181d.png">
.

**Comment by OneBlue** [comment]
Ok, based on that I can see that the disk for ubuntu is in `C:\\Users\\parja\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState`. There should be a file named `ext4.vhdx` in that folder.

To recover its content the simplest I can think of would be to use `wsl --mount`, so something like:


```
wsl --mount C:\Users\parja\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx --vhd --bare
```

And then use [fsck](https://linux.die.net/man/8/fsck) on the disk to try to recover its content (you can use `lsblk` to list the available disks)

Note that:

- If you don't care about the files inside that distro, simply uninstalling and reinstalling it should work
-  wsl --mount --vhd is only available in [WSL from the store](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) so you'd need to install to use it

**Comment by Wizards-god** [comment]
> Ok, based on that I can see that the disk for ubuntu is in `C:\\Users\\parja\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState`. There should be a file named `ext4.vhdx` in that folder.
> 
> To recover its content the simplest I can think of would be to use `wsl --mount`, so something like:
> 
> ```
> wsl --mount C:\Users\parja\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx --vhd --bare
> ```
> 
> And then use [fsck](https://linux.die.net/man/8/fsck) on the disk to try to recover its content (you can use `lsblk` to list the available disks)
> 
> Note that:
> 
> * If you don't care about the files inside that distro, simply uninstalling and reinstalling it should work
> * wsl --mount --vhd is only available in [WSL from the store](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) so you'd need to install to use it

Thank you so much, I could recover all my files from the distro. Now it is working like before.

**Comment by OneBlue** [comment]
Happy it worked ! Closing this.
