### ISSUE TITLE
Password autocomplete

### ISSUE THREAD

**Issue by whiteLine0** [microsoft/WSL#7836]
**Is your feature request related to a problem? Please describe.**
It is tedious having to type the password every time it is needed.

**Describe the solution you'd like**
Be able to enter the password of any Linux distribution with Windows Hello.

**Comment by craigloewen-msft** [comment]
This isn't a feature that we are currently going to be adding. I'd recommend taking a look at ways to edit your sudoers file to not need to input a password. Here's a quick article with a command you can run to easily do this (Keep the security implications in mind! :) )

echo "%${USER} ALL=(ALL) NOPASSWD:ALL" | sudo EDITOR='tee ' visudo --quiet --file=/etc/sudoers.d/passwordless-sudo
