### ISSUE TITLE
wsl.conf [boot] command init ssh  to the keychain 

### ISSUE THREAD

**Issue by MihailProcudin** [microsoft/WSL#7837]
### Version

Microsoft Windows [Version 10.0.22000.318]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.60.1

### Distro Version

Ubuntu 21.04

### Other Software

keychain 2.8.5

### Repro Steps

add to `wsl.conf` under `[boot]` a `command` entry 

```
[boot]
command = eval keychain --eval --agents ssh id_rsa

```

### Expected Behavior

When running `eval keychain --eval --agents ssh ~ id_rsa` in Bourne shell it prompts something like:

```
wsl@Access-B8WK9C3:~$ eval keychain --eval --agents ssh id_rsa

 * keychain 2.8.5 ~ http://www.funtoo.org
 * Found existing ssh-agent: 294
 * Adding 1 ssh key(s): /home/wsl/.ssh/id_rsa
Enter passphrase for /home/wsl/.ssh/id_rsa:
```

I would expect when added under `boot` in `wsl.conf` 
that it should output on every wsl fresh boot this keychain output. But it doesn't 

Termination of wsl deamon nor of just single distro haven't helped 
```
wsl -d Ubuntu --shutdown
wsl --shutdown 
```

### Actual Behavior

Doesn't happen anything under [boot].

for example `[user]` works fine.
```
[user]
default=root/user
```

**Comment by WSLUser** [comment]
That shouldn't be needed. On Pengwin, if you install keychain, it shows every time that it's running.  I'd check out how the pengwin-setup script for installing keychain works.

**Comment by benhillis** [comment]
The boot.command setting runs in the background and won't print anything to the console.
