### ISSUE TITLE
Alder Lake \ W11 poor performance

### ISSUE THREAD

**Issue by holmesb** [microsoft/WSL#7838]
### Version

10.0.22000.348

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

git clone https://github.com/hashicorp/terraform-provider-azurerm.git
cd terraform-provider-azurerm
go clean -modcache && time go build -a

Wait interminably.  vmmem process is hardly utilised (<10%) according to task manager.  

On DOS\W11 CLI, finishes > 34 times faster.  CPU is i5-12600K, but same prob occurs on other Alder Lake CPUs.  %userprofile%\\.wslconfig and /etc/wsl.conf are empty, which (unless I'm mistaken) should default to all cores being used.  lscpu shows [this](https://gist.github.com/holmesb/47836e6c821afdf543d883908f07fc0f).

### Expected Behavior

Good performance (~1 min on Windows 11\DOS CLI)

### Actual Behavior

Intertia on WSL: 
`real    34m18.238s`

**Comment by OneBlue** [comment]
Hi @holmesb. Are you running this command inside the Windows or Linux filesystem? (/mnt/C vs /home/*)? The Windows filesystem is much slower and if you need better performance, I'd recommend using the Linux filesystem.

**Comment by holmesb** [comment]
Hi @OneBlue, no I'm running it from /tmp/
