### ISSUE TITLE
Install WSL2 without a distribution

### ISSUE THREAD

**Issue by scott-moxham** [microsoft/WSL#7840]
On previous machines I've installed WSL2 but not added a distribution, i.e. follow steps 1-5 on https://docs.microsoft.com/en-us/windows/wsl/install-manual but skipping step 6, which is sufficient for running linux containers in Docker, but the new `wsl.exe --install` doesn't seem to have any option to skip the distribution.

Can you add an option to say no distribution, e.g. `wsl.exe --install -d none`

This would seem as though it would be a simple option that would allow saving lots of disk space for scenarios where it's not needed.

**Comment by craigloewen-msft** [comment]
We've added this as a flag in the latest WSL versions on Windows Insiders!  :) Thank you for filing this!

**Comment by decrux-io** [comment]
Is this live already?

**Comment by sirredbeard** [comment]
Did this ever land?
