### ISSUE TITLE
progress on `wsl --set-version`, or at least time elapsed

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/WSL#7842]
**Is your feature request related to a problem? Please describe.**
`wsl --set-version <name> <1|2>` this is one of the most time-consuming commands, but there is no progress, nor time elapsed. It is really confusing sometimes if it is working or not.

**Describe the solution you'd like**
 - Show progress if possible
 - Show time-elapsed at least
 - Some additional info like, system load maybe be helpful

**Describe alternatives you've considered**
nAn

**Additional context**
And finally, show the total time elapsed.

**Comment by craigloewen-msft** [comment]
We've added animated loading dots for this in the latest WSL versions! If you use WSL from the Microsoft Store you can see this in action. Thanks for filing!
