### ISSUE TITLE
WSL2 defaults to root directory (/) instead of user home (~) on start up

### ISSUE THREAD

**Issue by navneethc** [microsoft/WSL#7846]
### Version

Microsoft Windows [Version 10.0.19044.1415]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Windows Terminal 1.11.2921.0

### Repro Steps

Open WSL2 using Windows Terminal and look at the landing directory.

### Expected Behavior

It should be in the user's home directory, `~` or `/home/navneethc`.

### Actual Behavior

It is the `/` (root) directory 

### Diagnostic Logs

This has always been the home directory. 

The profile in Windows Terminal for this disto points to `//wsl$/Ubuntu-20.04/home/navneethc` as the starting directory.

The changes that have happened between the last time I saw `~` (in the last week or so) is I installed a few Windows updates including 21H2 for Windows 10.

**Comment by yes89929** [comment]
Change starting directory from `//wsl$/Ubuntu-20.04/home/navneethc` to `/home/navneethc` likes below.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/33365390/146466677-aac62d3e-52f4-4a82-b5d3-a0d28863daf2.png">

**Comment by navneethc** [comment]
@yes89929, thank you, that worked! When did this change happen? Is it due to the 21H2 update?
