### ISSUE TITLE
Support --no-distro or --import with --install

### ISSUE THREAD

**Issue by n1hility** [microsoft/WSL#7847]
If you intend to import your own custom distro, you are still forced to download and install an additional online distribution from the store (e.g. ubuntu).  This wastes quite a bit of extra time for something that you turn around and delete anyway. 

It would be great if there was an option to disable downloading a distribution so you can then import quickly after a reboot. Alternatively allowing the import command to be specified with --install be great as well. 

At the moment I work around this issue by manually enabling the features and using wsl --update. 

Thanks!

**Comment by craigloewen-msft** [comment]
There is support for `--no-distro` on the latest versions on Windows Insiders as well as some other WSL install improvements! So this request has already been completed. Thank you for filing! :)

**Comment by craigloewen-msft** [comment]
Here's the relevant blog post:
https://blogs.windows.com/windows-insider/2021/12/08/announcing-windows-11-insider-preview-build-22518/

**Comment by n1hility** [comment]
@craigloewen-msft awesome news, thanks!
