### ISSUE TITLE
Server running in WSL can only be accessed on version 1, version 2 blocks most of the port

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/WSL#7848]
### Version

Microsoft Windows [Version 10.0.19044.1415]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu-20.04 + Ubuntu-18.04

### Other Software

Docker Desktop 4.3.1 (72247)

### Repro Steps

 - Create an empty Django project
 - Copy it inside WSL instance folder, mounted under network
 - Try to access from a browser in Windows, from outside the WSL distro instance

### Expected Behavior

Should be able to access it. But in `WSL2` it can't access, but in `WSL1` it can access these ports.

### Actual Behavior

Needed to downgrade to `WSL1`, to access those ports. But some ports were working. This was kind of creepy. And I created another react project, which was able to call those APIs on the backend. So my server is up running. 

So WSL2 is blocking some ports, when it is being accessed outside WSL VM.

**Comment by Lunatig** [comment]
WSL 2 has a virtualized ethernet adapter with its own unique IP address
https://docs.microsoft.com/en-us/windows/wsl/networking

**Comment by maifeeulasad** [comment]
But, @Lunatig, I was able to access some ports running inside `Ubuntu-18.04` with `WSL2`. Those applications were docker app.

**Comment by Lunatig** [comment]
I have exactly the same story. Docker works without dancing with tambourines. and for the node, port forwarding required. 

and that's another thing. after each reboot of the computer, the IP of WSL2 changes. 

get the first id here
`ip addr | grep eth0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.18.206.220/20 brd 172.18.207.255 scope global eth0
`

 and then run powerWhell as admin 
`netsh interface portproxy add v4tov4 listenport=3000 listenaddress=0.0.0.0 connectport=3000 connectaddress=172.18.206.220`


you can chek port forwarding 
`netsh interface portproxy show all`

after that you can get all you need from your 3000 port from local net ip and localhost and local domans in C:\Windows\System32\drivers\etc\hosts (127.0.0.1 site.test)

http://172.18.206.220:3000/
http://192.168.1.89:3000/
http://site.test:3000/
http://localhost:3000/
http://127.0.0.1:3000/

**Comment by Lunatig** [comment]
add this and run wsl as admin

```
~/.bashrc

ip=$(ip -4 addr show eth0 | grep -oP "(?<=inet ).*(?=/)")
for wslproxyport in 80 443 3000; do
	netsh.exe interface portproxy delete v4tov4 listenport=$wslproxyport listenaddress=0.0.0.0 > /dev/null
	netsh.exe interface portproxy add v4tov4 listenport=$wslproxyport listenaddress=0.0.0.0 connectport=$wslproxyport connectaddress=$ip > /dev/null
done

```

**Comment by OneBlue** [comment]
@maifeeulasad: WSL2 has a localhost port relay. If a port is bound in WSL2, it should be accessible from Windows via 127.0.0.1.

For instance, this:

```
$ wsl python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

Bind a port that can be accessed via:

```
$ curl http://127.0.0.1
```

In Windows.
