### ISSUE TITLE
Failed to retrieve available kernel versions.Ubuntu

### ISSUE THREAD

**Issue by Piot1998** [microsoft/WSL#7853]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Distro Version

Ubuntu 21.04

### Repro Steps

I use wsl. I downloaded from the microsoft store ubuntu version 20.04 LTS. I wanted to update to ubuntu 21.10. So I updated sequentially first to 10/20, then to 4/21 and finally to 10/21. But when the installation of ubuntu 21.10 finished, I got the following messages:

Failed to retrieve available kernel versions.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

User sessions running outdated binaries:
 piotrek @ / dev / pts / 0: bash [116]
 root @ / dev / pts / 0: apt [1011,1130]. I installed all versions sequentially using the first method in this tutorial
https://discourse.ubuntu.com/t/installing-ubuntu-20-10-on-wsl/18941. When I type lsb_release -a it shows me that I have ubuntu 21.10 installed, with a code name
impish. What should I do in this case to get rid of these errors? Please help. I am a beginner in these matters. Thanks

### Expected Behavior

That the installation will go smoothly

### Actual Behavior

I didn't notice anything disturbing except these errors at the end of the installation
```Failed to retrieve available kernel versions.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

User sessions running outdated binaries:
 piotrek @ / dev / pts / 0: bash [116]
 root @ / dev / pts / 0: apt [1011,1130]```

### Diagnostic Logs

```
Failed to retrieve available kernel versions.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

User sessions running outdated binaries:
 piotrek @ /dev/pts/0: bash[116]
 root @ /dev/pts/0: apt[1011,1130]
```

**Comment by Biswa96** [comment]
May I ask what you want to actually achieve? Do you only want to install Ubuntu 21.10 in WSL2?

**Comment by Biswa96** [comment]
I have not seen that type of error message in WSL ever. There may be some process running behind. See `ps -elf` output.

**Comment by Piot1998** [comment]
<img width="960" alt="wsl" src="https://user-images.githubusercontent.com/30383648/147093924-7482f278-f4f7-4c7a-b977-918f1b0a0a10.png">

**Comment by Biswa96** [comment]
O, that one is a Ubuntu related thing and not from WSL. I am not familiar with Ubuntu distribution. But as the message says, run the `touch ~/.hushlogin` command to disable the message.

**Comment by Piot1998** [comment]
how to deal with it.
<img width="960" alt="wsl3" src="https://user-images.githubusercontent.com/30383648/147104242-b93ba24f-c2ea-470d-87e1-717c11ab9b90.png">
<img width="960" alt="wsl4" src="https://user-images.githubusercontent.com/30383648/147104254-77af982d-74fa-4884-8eab-1f2731ddb331.png">
<img width="960" alt="wsl1" src="https://user-images.githubusercontent.com/30383648/147104258-c7289613-883e-42fe-85a1-92b9d8e5ee27.png">
<img width="960" alt="wsl2" src="https://user-images.githubusercontent.com/30383648/147104263-ce84eb82-a7b5-4dbb-8835-067cefc63914.png">

**Comment by Piot1998** [comment]
this is what happens after running sudo apt update

**Comment by Piot1998** [comment]
I am asking seriously how to solve this. I am asking for help because when it comes to wsl and linux, no matter what distribution, I am a beginner in these matters

**Comment by roy-nard** [comment]
I similar "problems" I installed using the --import on "ubuntu-21.04-server-cloudimg-amd64-wsl.rootfs.tar.gz".

these are images meant to be run on public clouds. They are however marked as "WSL".
I would just download another one fromt the store or export/import the current one to fic that problem.

**Comment by mrcaidev** [comment]
There's a comprehensive explanation [here](https://askubuntu.com/questions/1404129/ubuntu-22-04-lts-on-wsl-failed-to-retrieve-available-kernel-versions-failed). I just removed package `needrestart` and everything works fine again.

**Comment by Piot1998** [comment]
Unfortunately, it did not help. It is still the same. Anyone else have any ideas. Standard, non-standard whatever.

**Comment by Piot1998** [comment]
Successfully updated to version 22.04 
<img width="1858" alt="lin" src="https://user-images.githubusercontent.com/30383648/167672715-0d7dd586-1f54-4972-a8f6-54a5db557945.png">
using the method described here https://discourse.ubuntu.com/t/installing-ubuntu-20-10-on-wsl/18941 previously I did what was described by @mrcaidev and finally got it:
<img width="1858" alt="wsl" src="https://user-images.githubusercontent.com/30383648/167673710-a3d3b521-45eb-4c04-9387-79717f8081b7.png"> I want everything to be okay with these two messages: Failed to retrieve available kernel versions.
Failed to check for processor microcode upgrades. How to do it?
