### ISSUE TITLE
WslRegisterDistribution failed with error

### ISSUE THREAD

**Issue by LolekLiam** [microsoft/WSL#7854]
### Version

Microsoft Windows [Version 10.0.19044.1415]

### Repro Steps

Run Ubuntu or any other linux distro.

### Expected Behavior

Install within distro and use it.

### Actual Behavior

Didn't even install and wsl can't even detect the distro.

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80041002
Error: 0x80041002 (null)
Press any key to continue...

### Diagnostic Logs

I already tried turning off the firewall, but got the same error.

**Comment by XJIOP** [comment]
same here
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80041002
Error: 0x80041002 (null)
Press any key to continue...
```

**Comment by LolekLiam** [comment]
> same here
> 
> ```
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80041002
> Error: 0x80041002 (null)
> Press any key to continue...
> ```

i found a solution. open powershell as admin and type this command:
wsl --set-default-version 1
wait till it's done and open your distro again. if it doesn't work, try opening cmd as admin and paste the same command above. that worked for me

**Comment by XJIOP** [comment]
> i found a solution. open powershell as admin and type this command:
> wsl --set-default-version 1

After that, can you resume to WSL2?

**Comment by LolekLiam** [comment]
> > i found a solution. open powershell as admin and type this command:
> > wsl --set-default-version 1
> 
> After that, can you resume to WSL2?

I think you can't. I haven't tried yet. Try it and let me know if it works.

**Comment by Polemus** [comment]
still getting this issue, all was working then it just somehow stopped working

Win 11
ubuntu 22.04.1 LTS from store

Docker desktop also fails to launch

**Comment by ZeyuLiao** [comment]
> Thank you! you are my fking hero!

**Comment by quangtrinh1312** [comment]
i delete all previous vm, disable vpn, turn of some defender about app in window defender and restart, switch wsl 1 and it work!

**Comment by aliyousafzai183** [comment]
This command worked for me!
Open powershell as administrator and type:
`wsl --update`

then restart the docker-desktop
