### ISSUE TITLE
Can't get latest kernel via wsl --update

### ISSUE THREAD

**Issue by jiashenren** [microsoft/WSL#7856]
### Version

Microsoft Windows [Version 10.0.19044.1415]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Checked web: https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.74.3, the latest kernel is 5.10.74.3
2. When uses command "wsl --update" to update, got response:
```
wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.60.1 
```

### Expected Behavior

On Windows 11(Version 10.0.22518.1000), I can update WSL kernel to 5.10.74.3 via "wsl --update"

### Actual Behavior

wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.60.1

**Comment by Biswa96** [comment]
Linux kernel version 5.10.74.3 is not in the update list, here https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

You can get that version with a little cheating 😉 Download the msixbundle file from here https://github.com/microsoft/WSL/releases. Extract the msix file from it using 7zip like tools. There will be a kernel file in it.
