### ISSUE TITLE
How to update the WSL2 kernel via PowerShell.

### ISSUE THREAD

**Issue by bryn1u** [microsoft/WSL#7857]
Hello,

Is there any way to update WSL2 kernel via command line for example using PowerShell ? I can't it do it via gui because restriction. I have admin rights but the only way is install everything via cmd. I was reading but didnt find any answer.

Thanks,

**Comment by Biswa96** [comment]
You can follow [these steps][1] to update Linux kernel in WSL2 manually and use [msiexec][2] to install it.

[1]: https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
[2]: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec

**Comment by OneBlue** [comment]
Hi @bryn1u.

You can use `wsl --update` to download and install the latest WSL kernel.
