### ISSUE TITLE
Server Windows 2022 not upgrade for version 2 

### ISSUE THREAD

**Issue by blin25** [microsoft/WSL#7858]
### Version

Server Windows 2022

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

1) Install wsl_update_x64.msi  No problem 
2) Update wsl   No problem 
PS C:\Users\Administrator> wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.16
3 No update for  version 2  always  1 

### Expected Behavior

No

### Actual Behavior

No

**Comment by DesktopECHO** [comment]
WSL2 Is not supported in Windows Server 2022.

**Comment by OneBlue** [comment]
@DesktopECHO  is correct. Only WSL1 is supported on Windows server 2022.
