### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by igor87z** [Microsoft/WSL#786]
I need Python 3.5 but in it don't exists in repos. Current version BashOnWindows based on Ubuntu Trusty Tahr. Can I upgrade to more fresh version where Python 3.5 available?

**Comment by fpqc** [comment]
You can try Xenial by a guide on this issues page, but it is tough and does not fully work

**Comment by bparker98** [comment]
Try the deadsnakes ppa. 
I was able to use the python 2.7 version to upgrade to python 2.7.12

https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes

**Comment by srinath29** [comment]
You can get it from Continuum. https://www.continuum.io/downloads

**Comment by aseering** [comment]
@srinath29 -- Continuum provides Anaconda, which is Python + package manager.  It changes the meaning of `pip install`, can conflict with Ubuntu's own package management when packages are available through both, etc.  It also makes it easy to install a bunch of cool stuff.  Point being, installing Anaconda is significantly more than just installing Python.

**Comment by srinath29** [comment]
Yeah. No. Actually it sets the environment to use it's pip instead of system's pip. If you don't want all the packages, then you can just download miniconda. And install necessary packages.

**Comment by jaypeedevlin** [comment]
And pip works fine within conda environments, so you can forget conda is there once you install, if that's your preference: https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/

**Comment by aseering** [comment]
@jaypeedevlin -- "fine" is relative :-)  Yes, `pip` exists and works in lots of simple cases.  But I've seen a number of systems where people tried to switch between multiple versions of Python, install packages manually, etc, and Anaconda's `pip` got into a state where it could install packages but Anaconda's `python` couldn't see those packages, or Anaconda's `pip` couldn't find dependencies that were present and accessible to Anaconda's `python`, etc.

If you use Anaconda exclusively, then yeah, things probably do well.  But on a default Anaconda install, you still have the system Python available at `/usr/bin/python` (and ditto for `pip`); if you, for example, run a script that calls those paths directly, then you can still get into trouble.

**Comment by jaypeedevlin** [comment]
That's not about anaconda then, that's about a script that's poorly written.

**Comment by aseering** [comment]
If I run a series of scripts that simply fo things like `pip install`, `pip uninstall`, etc, and Python breaks for me, are you really telling me that the fault is the scripts and not pip?  Or, by extension, Anaconda, as the tool that configured pip.

Anaconda is a platform.  I expect my platforms to provide isolation -- if I mess with something outside the platform, it won't break the platform; and robustness -- if I use the platform as documented, it will behave as documented, moreover commonly-run commands should be unlikely to cause the whole platform to stop working in a way that is nonintuitive.

**Comment by jaypeedevlin** [comment]
I'm not quite sure how you define platform, but Anaconda is a distribution of Python and Conda is a package manager. You many need to adjust your expectations based on what it is and isn't.

I was responding to your direct example with a script that uses a hard coded path. Yes, if you have >1 version of Python on your system and use the wrong hardcoded path, that's your fault.

The OP wants to know how to get py3.5 working easily in the windows/Bash environment and Anaconda or Miniconda is their best option.

Whichever way they proceed they will have multiple versions of pip and need to be careful.  Aliases can help make this less stressful.

You've taken this off topic so let's bring it back. If not Anaconda, what would you suggest is the best option for the OP?

**Comment by aseering** [comment]
@jaypeedevlin -- this thread was IMO effectively answered by its first response, above, a year ago.  See that response for what would also be my suggestion.

You re-started the thread recently.  (It had been inactive for about a year previously, with a question and some suggested answers posted.)  As such, I'm responding to you.  If you think you've gotten what you wanted out of re-opening the thread, let's call it a day.

Regarding "platform" -- I'm using the word as a technical term in the field of product management, regarding the role that Continuum.io envisions for Anaconda.  Specifically, and at a high level, they expect people to build applications of various sorts on top of it.  Hence "platform".  (If you're just playing around, or building small tools for a few people, then yeah, Anaconda can be great.  But if you're on a big team that's getting paid to write Python code, which a lot of people are, then that code probably has to get deployed somewhere, the environment has to be maintained by someone, you have to consider differences between your dev and production environments and make sure that they don't confuse/frustrate your team, etc.)  I'm not expressing personal opinions per se, though I do believe them; rather, I'm doing my best to outline my understanding of what people who study platforms have learned are important attributes.  If you think my summary is overly reductive, that's a fair criticism.  If you think it's wrong, do you have some references?  As you say, this ticket is the wrong format for an extended discussion, but I'm always happy to learn.

**Comment by therealkenc** [comment]
> Can I upgrade to more fresh version where Python 3.5 available?

[Yes](https://askubuntu.com/questions/798123/how-do-i-install-python-3-5-2).
