### ISSUE TITLE
.wslconfig support on Windows Build 18362/18363

### ISSUE THREAD

**Issue by sohtsuka** [microsoft/WSL#7860]
Hello,

[Advanced settings configuration in WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#:~:text=Global%20configuration%20options%20with%20.wslconfig%20is%20only%20available%20for%20distributions%20running%20as%20WSL%202%20in%20Windows%20Build%2019041%20and%20later)  page says:

> **Note**
> Global configuration options with .wslconfig is only available for distributions running as WSL 2 in Windows Build 19041 and later.

Which does this mean?
1. WSL 2 on Windows Build 18362/18363 doesn't support .wslconfig
2. This note is just out of date (written before WSL 2 was backported to 18362/18363) and all WSL 2 versions support .wslconfig

**Comment by Biswa96** [comment]
As far as I know, the answer is option 1.

You can verify if WSL supports .wslconfig using [Strings from Sysinternals][1]. Just run this command:

```
strings64.exe C:\Windows\System32\lxss\LxssManager.dll | find /i "wslconfig"
```

If WSL supports .wslconfig the output of that command will be `\.wslconfig` else there will be no output.

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/strings

**Comment by sohtsuka** [comment]
Thanks, I have verified that the command outputs `\.wslconfig`.

```
> cmd /c ver

Microsoft Windows [Version 10.0.18363.1977]

> C:\bin\Strings\strings64.exe C:\Windows\System32\lxss\LxssManager.dll | findstr /I "wslconfig"
\.wslconfig
```

Also, I have verified that setting `processors` takes effect.

```
> wsl -- nproc
8
```

After applying this:
```
[wsl2]
processors=4
```

The number of processors changed.
```
> wsl -- nproc
4
```

WSL 2 on Windows Build 18363 seems to support `.wslconfig`.
