### ISSUE TITLE
12007 File system error when starting debian or ubuntu

### ISSUE THREAD

**Issue by gandbg** [microsoft/WSL#7863]
### Version

Microsoft Windows [Versione 10.0.19044.1415]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

I tried Debian and Ubuntu-20.04 but i suspect that it's the same with every other

### Repro Steps

1. `>wsl --install -d Ubuntu` or `>wsl --install -d Debian`

### Expected Behavior

After downloading and installing the appx file, wsl tries to run it to start the configuration, after wsl asks for username, password and you have sucessfully installed your favorite linux distribution on wsl

### Actual Behavior

After downloading and installing the appx file, wsl tries to run it to start the configuration but at this time (that can be replicated by just re-running the `wsl --install` command), wsl returns [this](https://i.imgur.com/INHtlfa.png) error massage

**Comment by microhobby** [comment]
@GreenAndBlueG you are trying to install directly from the appx file without using the Microsoft Store?

**Comment by GreenAndBlueG** [comment]
I'm trying to install it with the `wsl --install` command that i suspect simply downloads the appx file and installs it. That's why i above i wrote
> After downloading and installing the appx file

**Comment by elsaco** [comment]
@microhobby `wsl --install -d Ubuntu` will download in this case the Ubuntu package, install and launch it in order to setup username and password. There's no need to access the Microsoft Store client. Here's sample output when installing Ubuntu:

```
PS C:\Users\tux> wsl --install -d Ubuntu
Downloading: Ubuntu
Installing: Ubuntu
Ubuntu has been installed.
Launching Ubuntu...
```

There's a progress indicator at `Downloading:` step. @GreenAndBlueG you might have a corrupt appx package. Delete the existing one with `winget uninstall Ubuntu` and try again please.

**Comment by GreenAndBlueG** [comment]
I tried to delete and reinstall the package, the situation hasn't changed: download completed, installation completed, startup failed
```
> wsl --install -d Ubuntu
Download in corso: Ubuntu
Installazione in corso: Ubuntu
Ubuntu è stato installato.
Avvio di Ubuntu in corso...
```

**Comment by view836** [comment]
FWIW I have this exact same issue, found this thread looking for others who might have found a solution. The default wsl --install crashes post-reboot at the point when it launches ubuntu, pop-up window with file system error 12007.
