### ISSUE TITLE
setxkbmap

### ISSUE THREAD

**Issue by Choronz0n** [Microsoft/WSL#787]
I'm trying to run GNU APL under Linux Subsystem for Windows.  Executing "setxkbmap" in an xterm under WSL yields an error message "Error loading new keyboard description."  

This command works under Cygwin, so there shouldn't be a problam mapping it to the Windows API.

I realize that this issue involves a number of things you don't publicly support at the moment, and I can always use a Cygwin xterm to get around it.  Still, it would be nice to not have to drag all of Cygwin onto the machine to have an APL session.

Thanks.

**Comment by sunilmut** [comment]
@Choronz0n - Our focus so far has been command line based tools and not so much of GUI/xterm. If you feel that this scenario is important to you, please help us prioritize it by voicing (up vote or create a new item) your opinion at our [user voice page] (https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)

**Comment by therealkenc** [comment]
Flies here.
```
$ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us,us
variant:    ,
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+us:2+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+us:2+inet(evdev)"        };
        xkb_geometry  { include "pc(pc105)"     };
};
```
