### ISSUE TITLE
WSL hang for more than one hour when start SLES-12

### ISSUE THREAD

**Issue by zhufeizzz** [microsoft/WSL#7870]
### Version

Microsoft Windows [version10.0.19041]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

SLES-12

### Repro Steps

**1. Flow this guide to install WSL2**
https://docs.microsoft.com/zh-cn/windows/wsl/install-manual

**2. Download linux kernel and suse12 package to install offline.**
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
https://aka.ms/wsl-sles-12

**3. Use these command to install WSL2**
```
msiexec /i wsl_update_x64.msi
wsl --set-default-version 2
Add-AppPackage SLES-12_v1.appx
```

**4. Nothing happend (no windows popped out) when I try to start Suse linux at the first time**
```
explorer shell:AppsFolder\${suse_id}!SLES12
```

I can't reproduce this problem, because it only occurs when WSL is first installed. But it occurs at least 3 times on some computers. 

Is there anyway to solve this problem? Because I want to provide a tool for my workmates to install wsl automaticlly.

### Expected Behavior

Complete the installation in a short time.

### Actual Behavior

There should pop out a window when I execute this commad, but just nothing happend.
```
explorer shell:AppsFolder\${suse_id}!SLES12
```
![image](https://user-images.githubusercontent.com/4591255/147382238-52beb2b3-0956-4acb-8255-4ef9fdcfebd3.png)

I wait for more than one hour, then this windows popped out.

When I uninstall SLES-12 and reinstall again, it's back to normal, the windows pop out in only  few seconds.

Problem Summary：
- Normal computer first install cost: 3~5min
- Normal computer reinstall cost: 10s
- **Abnormal computer first install cost: 30~60min**
- Abnormal computer reinstall cost: 10s

### Diagnostic Logs

**systeminfo**
```
主机名:           LxxxMBP
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19041 暂缺 Build 19041
OS 制造商:        Microsoft Corporation
OS 配置:          成员工作站
OS 构建类型:      Multiprocessor Free
初始安装日期:     2020/9/28, 8:59:29
系统启动时间:     2021/12/24, 16:28:38
系统制造商:       HUAWEI
系统型号:         MACHR-WX9
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1792 Mhz
BIOS 版本:        HUAWEI 1.27, 2021/5/10
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,230 MB
可用的物理内存:   1,749 MB
虚拟内存: 最大值: 18,662 MB
虚拟内存: 可用:   2,397 MB
虚拟内存: 使用中: 16,265 MB
页面文件位置:     C:\pagefile.sys
登录服务器:       \\DGGAD114-DC
修补程序:         安装了 7 个修补程序。
                  [01]: KB4534170
                  [02]: KB4537759
                  [03]: KB4545706
                  [04]: KB4570334
                  [05]: KB4598481
                  [06]: KB5003173
                  [07]: KB5003242
网卡:             安装了 5 个 NIC。
                  [01]: Array Networks SSL VPN Adapter
                      连接名:      以太网 2
                      状态:        没有硬件
                  [02]: Intel(R) Wireless-AC 9560 160MHz
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 10.129.xx.xx
                      IP 地址
                        [01]: 10.24.xx.xx
                  [03]: Bluetooth Device (Personal Area Network)
                      连接名:      蓝牙网络连接
                      状态:        媒体连接已中断
                  [04]: Hyper-V Virtual Ethernet Adapter
                      连接名:      vEthernet (Default Switch)
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.240.1
                  [05]: Hyper-V Virtual Ethernet Adapter
                      连接名:      vEthernet (WSL)
                      启用 DHCP:   否
                      IP 地址
                        [01]: 172.30.32.1
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。
```
Feature Switch
```
FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : 适用于 Linux 的 Windows 子系统
Description      : 提供服务和环境以在 Windows 上运行本机用户模式 Linux shell 和工具。
RestartRequired  : Possible
State            : Enabled
CustomProperties : 
                   ServerComponent\Description : 提供服务和环境以在 Windows 上运行本机用户模式 Linux shell 和工具。
                   ServerComponent\DisplayName : 适用于 Linux 的 Windows 子系统
                   ServerComponent\Id : 1033
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
                   ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux

FeatureName      : VirtualMachinePlatform
DisplayName      : 虚拟机平台
Description      : 为虚拟机启用平台支持
RestartRequired  : Possible
State            : Enabled
CustomProperties : 


FeatureName      : Microsoft-Hyper-V-All
DisplayName      : Hyper-V
Description      : 提供一些帮助创建和运行虚拟机及其资源的服务和管理工具。
RestartRequired  : Possible
State            : Enabled
CustomProperties : 
                   
```

**Comment by zhufeizzz** [comment]
@OneBlue @

I can't reproduce this problem, because it only occurs when WSL is first installed, and only about one tenth of computers have this problem.

Is there anyway to collect logs afterwards? [This guide](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) need me to reproduce and record the actions.

**Comment by zhufeizzz** [comment]
@OneBlue 
Good news, I reproduced the problem on a computer, and this ([wsl.zip](https://github.com/microsoft/WSL/files/7785067/wsl.zip)) is the logs for the first 10 mins.

**Comment by OneBlue** [comment]
Thanks @zhufeizzz.

Looking at the logs, I don't see anything from WSL, did you start the log collection before starting WSL ? 

Also, can you share the output of `dmesg` after this long startup time

**Comment by zhufeizzz** [comment]
@zhufeizzz 
This log start from when I click the SUSE button in the windows start menu. Here is [dmesg.zip](https://github.com/microsoft/WSL/files/7787089/dmesg.zip)

I found some other information on this problem computer. When I clicked suse12 button, windows store is force updated.

This picture says: 'Give us some time. We are updating suse12 and should be able to use it again soon'.
![image](https://user-images.githubusercontent.com/4591255/147619979-50e6226d-a9de-42e1-aeb6-e70adb05d5e5.png)

This picture says: 'Suse12 is updating from 1.0.2 to 1.1.0'.
![image](https://user-images.githubusercontent.com/4591255/147619989-58e36ccb-6ab6-4b1f-906b-44c20f469393.png)

**Comment by zhufeizzz** [comment]
@OneBlue 
Hi, could you give me some advice?

**Comment by benhillis** [comment]
@zhufeizzz - I suspect the store is somehow stuck updating the package which is preventing the suse executable from running. What is the output of `wsl.exe -l -v`?

**Comment by zhufeizzz** [comment]
@benhillis 
This picture says: 'SUSE 12 is already installed by SLES-12_v1.appx file,  but wsl -l -v return nothing'
![截图2](https://user-images.githubusercontent.com/4591255/148184048-a0b50c3c-156e-4672-b96b-9f2ca6a2e171.PNG)

There are installation progress bar in start menu, nothing happened when I click the button.
![截图4](https://user-images.githubusercontent.com/4591255/148184065-5e0e0cd7-8365-436f-9fce-8cdd93b98059.PNG)

**Comment by zhufeizzz** [comment]
@OneBlue @benhillis 
I found some very important information. 

Everytime I reinstall Windows OS, if I just start to install WSL2 without doing anything else, the installation will be blocked for a long time. But if I opened the ms store once in advance, the installation will finished quickly. 

I speculate that the WSL2 linux distro installation requires some initialization of the ms store.

Now I know how to reproduce and avoid this problem, but my original goal was to install offline and automaticlly, do you know how to reslove this problem?

https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions

**Comment by OneBlue** [comment]
Based every you shared on this issue, it looks like the store is what's getting stuck and taking a long time to make the app available (especially given that there's basically no entries from WSL in the traces).

If you want to manually install SLES faster without interaction, once thing I can recommend is to export SLES with wsl --export and then import it with wsl --import. That will bypass the store and should be much faster

**Comment by zhufeizzz** [comment]
@OneBlue 
Thinks for your reply. But it may not be suitable for my scene, because I don't want release SUSE12 binary by myself. 

https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions
This guide tell us that we can install WSL2 manually and offline, but actually we can't.  I think this is a document mistake or a WSL program bug.

Do you know any way to skip ms store initialization?
