### ISSUE TITLE
Access is denied in WIN11

### ISSUE THREAD

**Issue by tzyking1** [microsoft/WSL#7882]
### Version

10.0.22000.376

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

In power shell or cmd window, I want to run "wsl", but got a "access is denied"

### Expected Behavior

WSL can work properly

### Actual Behavior

WSL can't work anymore

### Diagnostic Logs

[wsl_log.zip](https://github.com/microsoft/WSL/files/7795393/wsl_log.zip)

**Comment by tzyking1** [comment]
I also tried some other commands, like:
wsl --set-version xxxx
wsl --mount xxxx
All of them got "access is denied"

**Comment by tzyking1** [comment]
After I perform "--set-default-version 1", I can install the "Ubuntu-18.04(wsl-1)",
but when I tried to "wsl --set-version Ubuntu-18.04 2", I also got the "access is denied"..
That is so frustrate. Many source codes in my wsl2... I can't open them now..
Who can help me?

**Comment by DanPinGF** [comment]
You need to be running as an administrator. That is what’s causing the problem.

**Comment by benhillis** [comment]
Looks like creating the virtual network is failing. I will follow up with the networking team to see if they can determine why.

**Comment by Keith-Mange** [comment]
It would be great if you could do the following:

1. [starthnstrace.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/starthnstrace.ps1)
2. Repro
3. Stop the trace in #1
4. [collectlogs.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1)

The trace initiated in #1 will give us more information on the failure.

The files gathered in #4 will gives us more state and system logs.

Thanks,
Keith

**Comment by zerofo** [comment]
same issue 
user: Administrator
```
PS C:\Windows\System32> wsl
拒绝访问。
```


> It would be great if you could do the following:
> 
> 1. [starthnstrace.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/starthnstrace.ps1)
> 2. Repro
> 3. Stop the trace in 1
> 4. [collectlogs.ps1](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1)
> 
> The trace initiated in 1 will give us more information on the failure.
> 
> The files gathered in 4 will gives us more state and system logs.
> 
> Thanks, Keith

**Comment by csh0101** [comment]
> 

hava you solved it?

i have the smae problem
