### ISSUE TITLE
After distro has been imported from backup it opens with root user

### ISSUE THREAD

**Issue by vyushin** [microsoft/WSL#7884]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 18.04

### Repro Steps

1. Make file in `~\.wslconfig`
2. Put to file:
```
[user]
default=evgeny
```
3. Install distro, create a user with name `evgeny`
```
wsl --install -d Ubuntu-18.04
```
4. Make sure, that the distro opens with default user `evgeny`
```
 wsl -d Ubuntu-18.04
```
5. Shutdown
```
wsl --shutdown
```
6. Make backup
```
wsl --export Ubuntu-18.04 Ubuntu-18.04_backup
```
7. Unregister the distro
```
wsl --unregister Ubuntu-18.04
```
9. Make suer the distro unregistered
```
wsl -l -v
```
10. Import the distro from backup (replace `evgeny` to your username)
```
wsl --import Ubuntu-18.04 C:\Users\evgeny\WSL\Ubuntu-18.04 C:\Users\evgeny\Ubuntu-18.04_backup
```
11. Make sure that the distro imported
```
wsl -l -v
```
12. Run the distro
```
wsl -d Ubuntu-18.04
```

### Expected Behavior

The imported distro have to opens with default user `evgeny` because `.wslconfig` contains this rule

### Actual Behavior

The imported distro opens with `root` user by default

**Comment by elsaco** [comment]
@vyushin set the default user in `/etc/wsl.conf` (create file if not present) before exporting your distro.

**Comment by vyushin** [comment]
@elsaco, exactly **before** exporting? Do you mean that if i create `/etc/wsl.conf` after exporting the distro it won't working?

**Comment by vyushin** [comment]
@elsaco, I have this. In this case `wsl.conf` have been made after importing.
![image](https://user-images.githubusercontent.com/8006957/147861938-fc53286f-09d6-41cf-9e51-09b39fd94bf6.png)

**Comment by elsaco** [comment]
In this case try:

```
wsl --terminate
ubuntu1804 config --default-user evgeny
```

**Comment by vyushin** [comment]
> In this case try:
```
wsl --terminate
ubuntu1804 config --default-user evgeny
```

This is working for me. Thank you!
