### ISSUE TITLE
Can't launch wsl

### ISSUE THREAD

**Issue by Cmdone** [microsoft/WSL#7889]
### Version

Microsoft Windows [版本 10.0.19044.1415]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu (Default)

### Repro Steps

Launch WSL

### Expected Behavior

Launch WSL normally, and enter unbuntu successfully

### Actual Behavior

It notice no VT-X support
![image](https://user-images.githubusercontent.com/17610440/148009301-82098fd8-6ac5-4c66-b689-d2e6acca0d34.png)

But I enable everything
![image](https://user-images.githubusercontent.com/17610440/148009326-cce01fe0-f474-442d-8df5-d2e6b47727ba.png)

PS: It happends suddenly after reboot windows, I'm sure it worked before 2022 year.

**Comment by VooDooC** [comment]
Identical, absolutely everything

**Comment by Shrimpwr** [comment]
Facing exactly identical situation, I've tried reinstalling the windows and it **temporarily** solved the problem last night, but this afternoon it happened again.

**Comment by xerx593** [comment]
same issue here: `wsl.exe --status` (and all other options, docker-desktop(!)) hangs.
`cmd.exe /c ver`
gives:
```
Microsoft Windows [Version 10.0.19044.1415]
```

**Comment by Cmdone** [comment]
I find the reason by #4930 , and the [solution](https://www.spacedesk.net/de/forums/topic/wsl2-not-starting-after-spacedesk-installation/)

Although I can relaunch wsl now, sadly I must reinstall distribution and lost all my data.

Best wishes to all you guys.
