### ISSUE TITLE
Folder mounted as separate drive (NTFS) not appearing in /mnt

### ISSUE THREAD

**Issue by sryze** [Microsoft/WSL#789]
I mounted a folder located on an NTFS partition as a separate drive using the following (registry) method:

http://superuser.com/a/899846/50200

It works perfectly on Windows but inside Bash on Windows it won't show up in the /mnt directory. 

Windows version:

Microsoft Windows [Version 10.0.14393]

**Comment by coldacid** [comment]
WSL only shows NTFS partitions on fixed disks at this time, so drive hacks like this are very unlikely to work for now.

**Comment by EricGT** [comment]
Additional note of interest:

If using dos [subst](https://technet.microsoft.com/en-us/library/bb491006.aspx) command from a command propmpt

**Comment by benhillis** [comment]
In 16176 you are now able to NTFS drive mounting support has been added:

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/
