### ISSUE TITLE
MySQL connections dropping, potentially from reverse DNS lookups

### ISSUE THREAD

**Issue by rideron89** [microsoft/WSL#7892]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Debian 10

### Other Software

**Local (Windows 11)**
Mysql-client Ver 8.0.26 for Win64 on x86_64 (MySQL Community Server - GPL)
SonicWall Global VPN Client

**Local (WSL 2)**
MariaDB-client Ver 15.1 Distrib 10.3.31-MariaDB

**Server (Windows 2016)**
MariaDB 10.3.8

### Repro Steps

**Note:** After having typed this all out, I decided to try my old Ubuntu 18.04 (which I haven't used in over a year), and **was not able to reproduce the issue**.

I am connecting to a remote database on a server via a VPN connection. Connecting is fine, but running queries timeout. I have 2 machines on the same local network that are running into this issue.

1) Open a terminal in WSL 2 (Debian 10)
2) Connect with the `mysql` command, specifying the server IP with the `-h` (host) option
3) Run `use [database name];`
4) Wait 30+ seconds for previous command to finish (no error reported)
5) Run `select * from [table name]`
6) Receive `No connection. Trying to reconnect...` error, followed by `MySQL server has gone away`
7) Check MariaDB error log to see that my connection was aborted during step 4

In the database's host cache, I am noticing errors for `COUNT_ADDRINFO_PERMANENT_ERRORS`. Here's the [documentation](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-host-cache-table.html) on that:
| The number of permanent errors during host name-to-IP reverse DNS resolution.

I know about trying to run the database with `--skip-name-resolve` and the `-A` option. Unfortunately, I cannot rely on either of these solutions long-term, so would like to figure out the root cause. Interestingly, when I use `-A`, the `use [database name];` command is quick again, and I can SELECT some data just fine. However, if I try to SELECT around 10 or more (depends on column count, I think) records, I lose the connection.

This sounded like a MySQL issue to me, but I do not run into this issue when connecting via MySQL for windows in Powershell. I can also connect perfectly fine with HeidiSQL and DBeaver from Windows. It seems to me like there is an issue between Windows & WSL 2 that is breaking my connection.

I have verified that the remote server can perform a reverse DNS lookup (via nslookup) for my local machine's VPN IP address.

I also have a portproxy binding (using `netsh interface portproxy add v4tov4`) between `0.0.0.0:3306` and my WSL IP.

I've tried restarting WSL 2 and allowing it to generate a `resolv.conf`, and I've tried using my own `nameserver 1.1.1.1` setting. No difference.

I **think** I was able to resolve this issue at one point by setting my connection type (in Windows) to private so my device would be discoverable. But that is not working this time around.

### Expected Behavior

I should be able to connect to a remote MariaDB database, run some queries, and have no issues with my connections dropping.

### Actual Behavior

After connecting, my connection gets dropped while running `use [database name]`, preventing any further queries from working.

**MariaDB error log**
```
Aborted connection 293840 to db: '[database name]' user: '[username]' host: '192.168.0.38' (Got an error reading communication packets)
```

**MariaDB client error**
```
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    293840
```

**Comment by saade** [comment]
same here
