### ISSUE TITLE
Prevent WSL2 from mounting local drives

### ISSUE THREAD

**Issue by maz-1** [microsoft/WSL#7894]
**Is your feature request related to a problem? Please describe.**
I would like to allow my fellow to connect to my ubuntu installed via wsl2, so I want to hide all my local drives from ubuntu in case he accidently do something like "rm -rf". I can't simply use virtual machine because I need cuda support.

**Describe the solution you'd like**
provide an option to hide all local drives, exposing only the virtual file system of wsl2

**Describe alternatives you've considered**

**Additional context**

**Comment by Biswa96** [comment]
Add the following in `/etc/wsl.conf` file:

```ini
[automount]
enabled=false
```

See further information here https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/
