### ISSUE TITLE
error 0x80370102 while Virtualization is enabled from BIOS

### ISSUE THREAD

**Issue by d1ndonlymdhe** [microsoft/WSL#7899]
### Version

Microsoft Windows [Version 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Repro Steps

First I installed Ubuntu from Store.
Both WSL and Hyper-V were Disabled
Got an error while launching Ubuntu
Uninstalled it
Tried Installing from Terminal [wsl --install -d ubuntu]
Ubuntu was downloaded but install failed with error 0x80370102
Turned on WSL and Hyper-V
Virtualization in on in BIOS
but i cant install Ubuntu or any distro getting error 0x80370102

### Expected Behavior

wanted to install a distro

### Actual Behavior

got error 0x80370102

**Comment by HunterZ** [comment]
Check out issue #7902. The Hyper-V _feature_ is not required by WSL, and may in fact get in the way.
