### ISSUE TITLE
Automount filter

### ISSUE THREAD

**Issue by joshua-barnett** [microsoft/WSL#7906]
**Is your feature request related to a problem? Please describe.**
Currently we can enable and disable `automount` via the `/etc/wsl.conf`.

This will automount all drives assigned a letter by default to the `/mnt/*` directory.

**Describe the solution you'd like**
I would like to be able to filter which drives are automounted.

e.g. I would like to just mount the C drive and no other drives.

**Comment by 0xbadfca11** [comment]
Disable automount and add C: drive entry to fstab.

**Comment by OneBlue** [comment]
0xbadfca11's answer would be the best way to do that. 

To disable automount, add this to `/etc/wsl.conf` :

```
[automount]
enabled=false
```

Then add this to `/etc/fstab` to mount a specific drive:

```
C: /mnt/c drvfs defaults 0 0
```
