### ISSUE TITLE
WSL Ubuntu20.04

### ISSUE THREAD

**Issue by m1mohamad** [microsoft/WSL#7917]
Exit Code
===========
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@LAPTOP-MU4A5RHR:/home# dpkg --configure -a

Setting up python3-py (1.8.1-1ubuntu0.1) ...
/var/lib/dpkg/info/python3-py.postinst: 6: py3compile: not found
dpkg: error processing package python3-py (--configure):
 installed python3-py package post-installation script subprocess returned error exit status 127
Setting up python3-jdcal (1.0-1.3) ...
/var/lib/dpkg/info/python3-jdcal.postinst: 6: py3compile: not found
dpkg: error processing package python3-jdcal (--configure):
 installed python3-jdcal package post-installation script subprocess returned error exit status 127
Setting up python3-olefile (0.46-2) ...
/var/lib/dpkg/info/python3-olefile.postinst: 6: py3compile: not found
dpkg: error processing package python3-olefile (--configure):
 installed python3-olefile package post-installation script subprocess returned error exit status 127
Setting up python3-bcrypt (3.1.7-2ubuntu1) ...
/var/lib/dpkg/info/python3-bcrypt.postinst: 6: py3compile: not found
dpkg: error processing package python3-bcrypt (--configure):
 installed python3-bcrypt package post-installation script subprocess returned error exit status 127
Setting up hplip-data (3.20.3+dfsg0-2) ...
/var/lib/dpkg/info/hplip-data.postinst: 6: py3compile: not found
dpkg: error processing package hplip-data (--configure):
 installed hplip-data package post-installation script subprocess returned error exit status 127
Setting up python3-webencodings (0.5.1-1ubuntu1) ...
/var/lib/dpkg/info/python3-webencodings.postinst: 6: py3compile: not found
dpkg: error processing package python3-webencodings (--configure):
 installed python3-webencodings package post-installation script subprocess returned error exit status 127
Setting up python3-tz (2019.3-1) ...
/var/lib/dpkg/info/python3-tz.postinst: 6: py3compile: not found
dpkg: error processing package python3-tz (--configure):
 installed python3-tz package post-installation script subprocess returned error exit status 127
Setting up python3-atomicwrites (1.1.5-2build1) ...
/var/lib/dpkg/info/python3-atomicwrites.postinst: 6: py3compile: not found
dpkg: error processing package python3-atomicwrites (--configure):
 installed python3-atomicwrites package post-installation script subprocess returned error exit status 127
Setting up python3-monotonic (1.5-0ubuntu2) ...
/var/lib/dpkg/info/python3-monotonic.postinst: 6: py3compile: not found
dpkg: error processing package python3-monotonic (--configure):
 installed python3-monotonic package post-installation script subprocess returned error exit status 127
Setting up python3-pil:amd64 (7.0.0-4ubuntu0.4) ...
/var/lib/dpkg/info/python3-pil:amd64.postinst: 6: py3compile: not found
dpkg: error processing package python3-pil:amd64 (--configure):
 installed python3-pil:amd64 package post-installation script subprocess returned error exit status 127
Setting up python3-decorator (4.4.2-0ubuntu1) ...
/var/lib/dpkg/info/python3-decorator.postinst: 6: py3compile: not found
dpkg: error processing package python3-decorator (--configure):
 installed python3-decorator package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-eventlet:
 python3-eventlet depends on python3-monotonic (>= 1.4); however:
  Package python3-monotonic is not configured yet.

dpkg: error processing package python3-eventlet (--configure):
 dependency problems - leaving unconfigured
Setting up python3-pygments (2.3.1+dfsg-1ubuntu2.2) ...
/var/lib/dpkg/info/python3-pygments.postinst: 6: py3compile: not found
dpkg: error processing package python3-pygments (--configure):
 installed python3-pygments package post-installation script subprocess returned error exit status 127
Setting up python3-wcwidth (0.1.8+dfsg1-3) ...
/var/lib/dpkg/info/python3-wcwidth.postinst: 6: py3compile: not found
dpkg: error processing package python3-wcwidth (--configure):
 installed python3-wcwidth package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-pandas:
 python3-pandas depends on python3-tz; however:
  Package python3-tz is not configured yet.

dpkg: error processing package python3-pandas (--configure):
 dependency problems - leaving unconfigured
Setting up python3-pyparsing (2.4.6-1) ...
/var/lib/dpkg/info/python3-pyparsing.postinst: 6: py3compile: not found
dpkg: error processing package python3-pyparsing (--configure):
 installed python3-pyparsing package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-openpyxl:
 python3-openpyxl depends on python3-jdcal; however:
  Package python3-jdcal is not configured yet.

dpkg: error processing package python3-openpyxl (--configure):
 dependency problems - leaving unconfigured
Setting up python3-cycler (0.10.0-3) ...
/var/lib/dpkg/info/python3-cycler.postinst: 6: py3compile: not found
dpkg: error processing package python3-cycler (--configure):
 installed python3-cycler package post-installation script subprocess returned error exit status 127
Setting up python3-xlwt (1.3.0-3) ...
/var/lib/dpkg/info/python3-xlwt.postinst: 6: py3compile: not found
dpkg: error processing package python3-xlwt (--configure):
 installed python3-xlwt package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-html5lib:
 python3-html5lib depends on python3-webencodings; however:
  Package python3-webencodings is not configured yet.

dpkg: error processing package python3-html5lib (--configure):
 dependency problems - leaving unconfigured
Setting up python3-numpy (1:1.17.4-5ubuntu3) ...
/var/lib/dpkg/info/python3-numpy.postinst: 6: py3compile: not found
dpkg: error processing package python3-numpy (--configure):
 installed python3-numpy package post-installation script subprocess returned error exit status 127
Setting up python3-pluggy (0.13.0-2) ...
/var/lib/dpkg/info/python3-pluggy.postinst: 6: py3compile: not found
dpkg: error processing package python3-pluggy (--configure):
 installed python3-pluggy package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-reportlab:
 python3-reportlab depends on python3-pil; however:
  Package python3-pil:amd64 is not configured yet.

dpkg: error processing package python3-reportlab (--configure):
 dependency problems - leaving unconfigured
Setting up python3-notify2 (0.3-4) ...
/var/lib/dpkg/info/python3-notify2.postinst: 6: py3compile: not found
dpkg: error processing package python3-notify2 (--configure):
 installed python3-notify2 package post-installation script subprocess returned error exit status 127
Setting up python3-lxml:amd64 (4.5.0-1ubuntu0.3) ...
/var/lib/dpkg/info/python3-lxml:amd64.postinst: 6: py3compile: not found
dpkg: error processing package python3-lxml:amd64 (--configure):
 installed python3-lxml:amd64 package post-installation script subprocess returned error exit status 127
Setting up python3-dnspython (1.16.0-1build1) ...
/var/lib/dpkg/info/python3-dnspython.postinst: 6: py3compile: not found
dpkg: error processing package python3-dnspython (--configure):
 installed python3-dnspython package post-installation script subprocess returned error exit status 127
Setting up python3-et-xmlfile (1.0.1-2.1) ...
/var/lib/dpkg/info/python3-et-xmlfile.postinst: 6: py3compile: not found
dpkg: error processing package python3-et-xmlfile (--configure):
 installed python3-et-xmlfile package post-installation script subprocess returned error exit status 127
Setting up python3-xlrd (1.1.0-5) ...
/var/lib/dpkg/info/python3-xlrd.postinst: 6: py3compile: not found
dpkg: error processing package python3-xlrd (--configure):
 installed python3-xlrd package post-installation script subprocess returned error exit status 127
Setting up python3-dateutil (2.7.3-3ubuntu1) ...
/var/lib/dpkg/info/python3-dateutil.postinst: 6: py3compile: not found
dpkg: error processing package python3-dateutil (--configure):
 installed python3-dateutil package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-paramiko:
 python3-paramiko depends on python3-bcrypt (>= 3.1.3); however:
  Package python3-bcrypt is not configured yet.

dpkg: error processing package python3-paramiko (--configure):
 dependency problems - leaving unconfigured
Setting up python3-soupsieve (1.9.5+dfsg-1) ...
/var/lib/dpkg/info/python3-soupsieve.postinst: 6: py3compile: not found
dpkg: error processing package python3-soupsieve (--configure):
 installed python3-soupsieve package post-installation script subprocess returned error exit status 127
Setting up python3-sip (4.19.21+dfsg-1build1) ...
/var/lib/dpkg/info/python3-sip.postinst: 6: py3compile: not found
dpkg: error processing package python3-sip (--configure):
 installed python3-sip package post-installation script subprocess returned error exit status 127
dpkg: dependency problems prevent configuration of python3-matplotlib:
 python3-matplotlib depends on python3-dateutil; however:
  Package python3-dateutil is not configured yet.
 python3-matplotlib depends on python3-pyparsing (>= 1.5.6); however:
  Package python3-pyparsing is not configured yet.
 python3-matplotlib depends on python3-numpy (>= 1:1.16.0~rc1); however:
  Package python3-numpy is not configured yet.
 python3-matplotlib depends on python3-numpy-abi9; however:
  Package python3-numpy-abi9 is not installed.
  Package python3-numpy which provides python3-numpy-abi9 is not configured yet.
 python3-matplotlib depends on python3-cycler (>= 0.10.0); however:
  Package python3-cycler is not configured yet.

dpkg: error processing package python3-matplotlib (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-3parclient:
 python3-3parclient depends on python3-eventlet; however:
  Package python3-eventlet is not configured yet.
 python3-3parclient depends on python3-paramiko; however:
  Package python3-paramiko is not configured yet.

dpkg: error processing package python3-3parclient (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-scipy:
 python3-scipy depends on python3-decorator; however:
  Package python3-decorator is not configured yet.
 python3-scipy depends on python3-numpy (>= 1:1.16.0~rc1); however:
  Package python3-numpy is not configured yet.
 python3-scipy depends on python3-numpy-abi9; however:
  Package python3-numpy-abi9 is not installed.
  Package python3-numpy which provides python3-numpy-abi9 is not configured yet.

dpkg: error processing package python3-scipy (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-tables-lib:
 python3-tables-lib depends on python3-numpy (>= 1:1.16.0~rc1); however:
  Package python3-numpy is not configured yet.
 python3-tables-lib depends on python3-numpy-abi9; however:
  Package python3-numpy-abi9 is not installed.
  Package python3-numpy which provides python3-numpy-abi9 is not configured yet.

dpkg: error processing package python3-tables-lib (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-pandas-lib:
 python3-pandas-lib depends on python3-numpy (>= 1:1.16.0~rc1); however:
  Package python3-numpy is not configured yet.
 python3-pandas-lib depends on python3-numpy-abi9; however:
  Package python3-numpy-abi9 is not installed.
  Package python3-numpy which provides python3-numpy-abi9 is not configured yet.

dpkg: error processing package python3-pandas-lib (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-tables:
 python3-tables depends on python3-numpy; however:
  Package python3-numpy is not configured yet.
 python3-tables depends on python3-tables-lib (>= 3.6.1-2build1); however:
  Package python3-tables-lib is not configured yet.
 python3-tables depends on python3-tables-lib (<< 3.6.1-2build1.1~); however:
  Package python3-tables-lib is not configured yet.

dpkg: error processing package python3-tables (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-bs4:
 python3-bs4 depends on python3-soupsieve; however:
  Package python3-soupsieve is not configured yet.

dpkg: error processing package python3-bs4 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-packaging:
 python3-packaging depends on python3-pyparsing; however:
  Package python3-pyparsing is not configured yet.

dpkg: error processing package python3-packaging (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-numexpr:
 python3-numexpr depends on python3-numpy (>= 1:1.16.0~rc1); however:
  Package python3-numpy is not configured yet.
 python3-numexpr depends on python3-numpy-abi9; however:
  Package python3-numpy-abi9 is not installed.
  Package python3-numpy which provides python3-numpy-abi9 is not configured yet.

dpkg: error processing package python3-numexpr (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-pyqt5:
 python3-pyqt5 depends on sip-py3api-12.7; however:
  Package sip-py3api-12.7 is not installed.
  Package python3-sip which provides sip-py3api-12.7 is not configured yet.

dpkg: error processing package python3-pyqt5 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python3-py
 python3-jdcal
 python3-olefile
 python3-bcrypt
 hplip-data
 python3-webencodings
 python3-tz
 python3-atomicwrites
 python3-monotonic
 python3-pil:amd64
 python3-decorator
 python3-eventlet
 python3-pygments
 python3-wcwidth
 python3-pandas
 python3-pyparsing
 python3-openpyxl
 python3-cycler
 python3-xlwt
 python3-html5lib
 python3-numpy
 python3-pluggy
 python3-reportlab
 python3-notify2
 python3-lxml:amd64
 python3-dnspython
 python3-et-xmlfile
 python3-xlrd
 python3-dateutil
 python3-paramiko
 python3-soupsieve
 python3-sip
 python3-matplotlib
 python3-3parclient
 python3-scipy
 python3-tables-lib
 python3-pandas-lib
 python3-tables
 python3-bs4
 python3-packaging
 python3-numexpr
 python3-pyqt5

**Comment by m1mohamad** [comment]
I tried all the suggested solutions available on Canonical and suggested bug fixes but non worked.

**Comment by OneBlue** [comment]
Closing this issue since it doesn't have repro instructions or details.

Please follow [the template](https://github.com/microsoft/WSL/issues/new?assignees=&labels=&template=Bug_Report.yaml)
