### ISSUE TITLE
'<' operator is reserved for future use

### ISSUE THREAD

**Issue by StephenChristopherHeinrich** [microsoft/WSL#7919]
The instructions indicate that to "Change the default Linux distribution installed
By default, the installed Linux distribution will be Ubuntu. This can be changed using the -d flag.

To change the distribution installed, enter: wsl --install -d <Distribution Name>.
BUT
 At line:1 char:18
+ wsl --install -d <kali-linux>
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by benhillis** [comment]
No issue template.
