### ISSUE TITLE
wsl.conf - Backslashes need to be escaped

### ISSUE THREAD

**Issue by akuropka** [microsoft/WSL#7920]
### Version

Microsoft Windows [Version 10.0.22000.434]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3-microsoft-standard-WSL2+

### Distro Version

Ubuntu 20.04

### Other Software

`/etc/wsl.conf`:

> [boot]
> command="echo ':qemu-arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:CF' > /proc/sys/fs/binfmt_misc/register"

### Repro Steps

Apply the above command to your `wsl.conf` and restart WSL.

### Expected Behavior

Command runs succesful handing over the echo command for registration.
Running this command as `root` user or with the help of `sudo tee` does work.

### Actual Behavior

Nothing happens; interpreter is not registered.
(If I divert the `echo` command to a file, e.g. `>/home/user/register.txt`, the file is not created, too.)

### Diagnostic Logs

It turns out that the backslash `\` needs to be escaped (`\\`).
The [documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl-config) only advises this for Windows paths.
Since the command is within double quotes (`"`) and the text part itself within quotes (`'`) there should be no need of escaping backslashes.

**Comment by NyaMisty** [comment]
Well, but I think that you should use bash -c to wrap your command

**Comment by NyaMisty** [comment]
It's really rude to close an issue which was here for 2 years but still no one responded.
We should at least triage this issue, instead simply closing using that stupid bot.
