### ISSUE TITLE
WSL2 on Win10 will not start after recent windows update

### ISSUE THREAD

**Issue by alandsidel** [microsoft/WSL#7922]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Repro Steps

1. Update Windows 10.
2. Attempt to start WSL2.

WSL2 has been working as expected for quite a while now.  Today I applied the following Windows 10 updates, and since then, WSL has not been able to start.

- KB5009543
- KB5008876
- KB4023057
- KB2267602
- KB5005463
- KB890830
- Windows Subsytem for Linux Update - 5.10.60.1
- Intel Corporation - System - 2.14.101.1
- Intel Corporation - SoftwareComponent - 2.14.101.1
- SAMSUNG Electronics Co., Ltd.  - USB - 2.17.16.0
- FTDI - Ports - 2.12.36.4
- FTDI - Ports - 2.12.36.4
- Intel - net - 20.70.25.2
- Intel Corporation - Bluetooth - 22.70.0.3
- SAMSUNG Electronics Co., Ltd. - Modem - 2.17.6.0
- SAMSUNG Electronics Co., Ltd. - AndroidUsbDeviceClass - 2.17.6.0

Presumably it is that WSL update that caused the problem.

### Expected Behavior

WSL should start.

### Actual Behavior

WSL does not start and the error given is : `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by alandsidel** [comment]
Update to indicate that both uninstalling and reinstalling the WSL update did not resolve the issue, nor did uninstalling and reinstalling the entire WSL feature.  It still refuses to launch and instead simply displays the unhelpful error message noted above.

**Comment by yuanchen-zhu** [comment]
I encountered the same problem after the recent Windows Update where the following updates were installed: KB5008876 and KB5009543. The following message is shown after running `wsl`:

`An address incompatible with the requested protocol was used.`

Please find the collected log attached:
[wsl.zip](https://github.com/microsoft/WSL/files/7928835/wsl.zip)

Moreover, docker for window also stopped working at the same time, and Hyper-V Manager shows an empty list of Virtual Machines, though I'm not sure if this is related since I haven't run docker for windows or inspected the Hyper-V manager for a while.

![mmc_207](https://user-images.githubusercontent.com/23563836/150864198-adc85b57-d876-4dc9-870b-a16df19829a3.png)

**Comment by alandsidel** [comment]
I "fixed" the problem on my end before the useless replies 2 days later by deleting and reinstalling the Ubuntu distribution.  Thankfully I do actually make nightly backups of my workstation so, after the reinstall, restored the old vmfs file from backup, shrunk it down (it's supposed to be a sparse file), and found Ubuntu unable to start once again.

Finally I reinstalled Ubuntu again to make sure it was working, then manually created a new VM to use as an Ubuntu live-CD system, to which I attached the old VMFS file.  Inside the VM I was able to mount the attached disk and copy the data I needed to off of it and into the new one over ssh.

Was a hassle, but it got me back up and running.  I have absolutely no idea what the update did the the filesystem to break it, and almost certainly never will, but maybe it'll help you out @yuanchen-zhu .

**Comment by yuanchen-zhu** [comment]
@alandsidel  Thanks for the note. Yeah I also et the sense from other posts that reinstalling windows while preserving data might also fix it, but that's not a satisfactory solution.

**Comment by alandsidel** [comment]
> @alandsidel Thanks for the note. Yeah I also et the sense from other posts that reinstalling windows while preserving data might also fix it, but that's not a satisfactory solution.

Reinstalling windows would be extreme overkill, all you should need to do is reinstall the Ubuntu distribution for WSL, if your problem is the same as mine was.  Data inside the WSL system will be lost if you do this, so you should copy the vmfs file somewhere else first if there is data inside you need to recover.

Good luck.

**Comment by the-dag** [comment]
I am having very similary problems. Only using WSL to run Rancher Desktop, and it suddenly stopped working after Windows shoved updates down my throat (no questions asked; I found my PC shut down though I had left it running, and upon booting I was met with the dreaded "Hi, we have some updates for you, this will only take a minute" thing that so often forebodes trouble.

Rancher Desktop now reports `Error: wsl.exe exited with code 4294967295` on startup. It's a `wsl --import` command using `--version 2` that fails. `wsl --update` reports `The WSL 2 kernel file is not found and may need to be reinstalled or repaired manually. For more information please visit https://aka.ms/wsl2kernel` and the MSI found at that link reports that a newer version is already installed.

I've attempted removing the WSL feature and adding it back in again, but everything behaves exactly the same afterwards. 

FWIW, WSL "kernel version 1" (AFAIU a Wine-like translation layer, whereas version 2 is a full-blown virtual machine) seems to be working as it should. I can run `wsl --install -d debian` for instance, and everything seems to be working fine. But `wsl --set-version debian 2` results in the same error as reported by `wsl --update`.

**Comment by the-dag** [comment]
@alandsidel Are you able to reopen the issue? 

IDK how this works but can't find a way to reopen the issue. Am hopeful you as the OP will get a button or something. Their annoying bot just closed the issue, because Microsoft doesn't consider it worthwhile to have a human actually take a look if there's not a lot of people generating activity on an issue... that is literally their explicitly stated policy, with no regard to the severity for those affected. I lose time every day because I have to work around not having WSL2 (Rancher) up and running.

**Comment by Biswa96** [comment]
Try to download the latest Linux kernel for WSL2 from here https://www.catalog.update.microsoft.com/Search.aspx?q=wsl. It'll download a CAB file which contains the MSI file. Make sure to correct CPU architecture (x86_64 or aarch64).

**Comment by the-dag** [comment]
@Biswa96 Thank you! I downloaded the newest one for x64 architecture, ran the MSI, and didn't even need to reboot. `wsl --update` no longer reports any errors, and Rancher Desktop is starting up normally. (I'll have to set up my cluster again, but that's no biggie in my case.)
