### ISSUE TITLE
Windows executable output overwritten by appended string

### ISSUE THREAD

**Issue by DanStory** [microsoft/WSL#7931]
### Version

Microsoft Windows [Version 10.0.19044.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

PowerShell 7.2.1 (for repro steps)

### Repro Steps

- Open WSL distro terminal
- Execute `echo $(pwsh.exe -c Write-Output 123)456`

### Expected Behavior

`echo` output to result in `123456`

### Actual Behavior

`echo` output results in `456`

**Comment by equation-group** [comment]
This is not WSL issue, your experimenting syntax is wrong.
try this: `echo "$(powershell.exe -c echo hi)"; echo "123";`

**Comment by DanStory** [comment]
> This is not WSL issue, your experimenting syntax is wrong. try this: `echo "$(powershell.exe -c echo hi)"; echo "123";`

this would be two lines, was wanting one line as shown in expected behavior. 

it did dawn on me that later this is because the Windows command output is including a carriage return (CR), causing the cursor to return to the beginning overwriting the first few characters - stripping that out via `tr -d '\r'` solved it
