### ISSUE TITLE
How to access a WSL folder from a new operating system on a separate SSD?

### ISSUE THREAD

**Issue by AsafYus** [microsoft/WSL#7934]
Hi, I had to install Win10 on a new SSD because there were problems with the booting operation of the previous Windows 10 OS.
The SSD on which the previous Windows 10 is installed is OK and all the files can be accessed, this drive named `D:\`
In the previous Win 10, I have a lot of important works and files in my WSL2 system.
How to access a WSL folder from the new operating system on a separate SSD, while the rest of the previous operating system with WSL2 is on another SSD?

I tried: \\wsl$ and get that the network path was not found. Just in case, I tried D:\wsl$ but Windows can't find it.
Thanks.

**Comment by elsaco** [comment]
@AsafYus if you didn't change the default location, WSL installs the VHDX for each distro in `C:\Users\<username>\AppData\Local\Packages` subfolder corresponding to each WSL distro . Search your old SSD for `*.vxdx` and import it to a new WSL instance. For Ubuntu on my system the virtual hard driver is at:

`C:\Users\tux\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\ext4.vhdx`

**Comment by AsafYus** [comment]
@elsaco OK, I have this file.
I have number of distros on old SSD, what is important to me is the files that I had in Ubuntu 20.04.
So what I need to do is install WSL2 in the new system, then install Ubuntu 20.04 as usual, it will create a similar folder in drive C and then I will just copy the ext4.vhdx file to the new folder and then all the files I had will appear?
Thanks.

**Comment by AsafYus** [comment]
?

**Comment by LeeHounshell** [comment]
Thank you @elsaco You saved me. my WSL2 crashed trying to do an ubuntu dist-upgrade. With your help i was able to mount my old WSL2 install in my new one and recover.
