### ISSUE TITLE
[0.51.0] wsl --import hangs after a short time

### ISSUE THREAD

**Issue by akuropka** [microsoft/WSL#7939]
### Version

Microsoft Windows [Version 10.0.22000.466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu-CommPrev

### Other Software

Recent updates:
- Windows 11 to 10.0.22000.466
- WSL to 0.51.0 from store.

### Repro Steps

`wsl --import Ubuntu-CommPrev2 C:\TEMP\system\..\compactwsl C:\TEMP\system\..\compactwsl\Ubuntu-CommPrev.tar`

### Expected Behavior

Import always succeeds.

### Actual Behavior

Most of the time import hangs at a point and does not go further. The command runs for hours but actually there's no further writing activity.

### Diagnostic Logs

https://user-images.githubusercontent.com/22570574/149669247-2507eb7c-cb64-437f-a7ed-1e6a84674696.mp4

**Comment by nicholasio** [comment]
I am having the exact same issue. It sounds like the issue has to do with symlinks. WSL is unable to extract the tar file.

**Comment by akuropka** [comment]
At least at my end locations are not symlinked…

**Comment by asifmohtesham** [comment]
So, what is the solution to this?

**Comment by Biswa96** [comment]
Use smaller tar file.

**Comment by Biswa96** [comment]
Try to use latest WSL Preview from Windows Store and smaller tar file.

**Comment by nicholasio** [comment]
> Try to use latest WSL Preview from Windows Store and smaller tar file.

I'm sorry but using a smaller tar file is in no world the solution to this problem.

Apparently this is the same issue as https://github.com/microsoft/WSL/issues/8714

**Comment by osorionicolas** [comment]
Seems to be fixed on the latest release 0.78.0 (pre-release) and do not see the hang issue anymore.

**Comment by qri57i** [comment]
> Seems to be fixed on the latest release 0.78.0 (pre-release) and do not see the hang issue anymore.

sorry for my noobism, but how can that be installed? I ahve downloaded it but "This app package is not supported for installation by App Installer because it uses certain restricted capabilities."

**Comment by Skaggio** [comment]
I fixed the issue on my side by using the "wsl --update" command: the "WSL version" reported in the output of the "wsl --version" command increased from "0.70.4" to "1.0.0.0" after the update and then I imported a 56GB tar at first attempt (whereas the import had always failed with the previous version).
HIH!
