### ISSUE TITLE
WSL2 on Win11 shows as Win 10 in neofetch

### ISSUE THREAD

**Issue by Matts** [microsoft/WSL#7942]
### Version

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

neofetch

### Repro Steps

sudo apt-get install neofetch

neofetch

### Expected Behavior

Expecting neofetch to show OS as Ubuntu 20.04 LTS on Windows 11 x86_64

### Actual Behavior

Ubuntu 20.04 LTS on Windows 10 x86_64

**Comment by elsaco** [comment]
@Matts with neofetch version 7.0.0 it won't show the Windows version:

![neofetch_ubuntu](https://user-images.githubusercontent.com/3933920/149864594-4647a1fb-2d1e-402c-9cb1-1c0029502990.png)

This is on Win11. How do you get to display more OS info? Thx.

**Comment by Erisa** [comment]
This was a problem with neofetch itself rather than anything wrong with WSL, because neoftech was detecting WSL and putting Windows 10 there. So neofetch resolved it by being less specific.

**Comment by equation-group** [comment]
@Matts If you issue has been resolved, kindly consider closing the issue.

**Comment by giuliolastra** [comment]
Hi @Matts, have you tried with wslfetch command? I've same issue when I run wslfetch or neofetch, it says "Windows 10 Linux Subsystem" but I'm running Windows 11 build 22000.593
