### ISSUE TITLE
I am not able to install wsl.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/WSL#7944]
I have decided to reinstall wsl component and when i deselected it in windows components and restarted I was not able to reinstall it.
here is my cbs.log
[CBS.log.zip](https://github.com/microsoft/WSL/files/7891530/CBS.log.zip)

**Comment by equation-group** [comment]
check #2703

try turning off your antivirus

**Comment by kotenok2000** [comment]
I was able to reinstall wsl by deleting antivirus, but when I try to install distribution i see
only 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 ?? ??????? ????????? ??????????? ??????, ????????? ??????????? ??????? ?? ???????????.

Press any key to continue...

**Comment by kotenok2000** [comment]
It seems wsl has decided to switch to version 2 by itself, but hypervisor was disabled with bcdedit /set hypervisorlaunchtype off
