### ISSUE TITLE
WSL2 will be unavailable for some softwares after amount of time in Windows 11

### ISSUE THREAD

**Issue by wisnupramoedya** [microsoft/WSL#7945]
### Version

Windows version: 10.0.22000.438

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

Ubuntu-20.04

### Other Software

- Windows Explorer
- Visual Studio Code 1.63.2 x64
- PHPStorm x64 2021.3.1

### Repro Steps

There is a clear step over here. But, I see some patterns that always create this bug.
1. Use your application, like in my case PHPStorm
2. Change your PHPStorm/VS Code to another window
3. After some time, you will realize your application has been blank.
4. Then, I try close it using the close button but could not. Then use Task Manager to close it.
5. Start to use WSL using Windows Terminal. Everything normal, until use command to open an app.
![image](https://user-images.githubusercontent.com/62658181/150294459-52dd8fb3-7bf1-4093-96f1-29b9176e35c0.png)

### Expected Behavior

I could open my application as usual or access the WSL directory using Windows Explorer

### Actual Behavior

- Try to open it again. Nothing works.

![image](https://user-images.githubusercontent.com/62658181/150293608-993a0a3f-e494-4bdc-93d7-e21729453b6a.png)
> When I open my PHPStorm again in the WSL location

- Try using WSL with Windows Terminal. It works. But, when I try to call the application (like `phpstorm64.exe .` or `code .`), it will get stuck in the front or not show anything.

![image](https://user-images.githubusercontent.com/62658181/150293173-43d89f84-6798-4903-bd0d-6b807181fae5.png)
> When I used VS Code, nothing happened

- I use Windows Explorer and access straight to `\\wsl$\Ubuntu-20.04`. It will get a very long loading.
![image](https://user-images.githubusercontent.com/62658181/150293015-add2d36e-1f25-4791-8b49-55e76f824b0e.png)
>> Very long loading in Windows Explorer

**Comment by rvanlaak** [comment]
see https://github.com/microsoft/WSL/discussions/7869

There are many cases similar to your case.
