### ISSUE TITLE
0x800701bc错误

### ISSUE THREAD

**Issue by GiveMeFive-wgw** [microsoft/WSL#7949]
### Version

Mircosoft Windows 11 professional previous

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

ubuntu-20.04

### Repro Steps

I meet some problems in my previous WSL2, so I delete it by wsl --unregister ubuntu-20.04.
After that, I installed the new wsl2 with kernel vision ubuntu-20.04. However, when I get the APP from Microsoft Store and install it, I meet the problem below:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel

### Expected Behavior

I just want to install the WSL without error

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800701bc
Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel

**Comment by equation-group** [comment]
You all do not read documentation properly and come here with your issue.  Are you inherently illiterate? 

Enable virtual machine platform and window subsystem for linux from Windows features.
https://user-images.githubusercontent.com/23298862/138331445-ba0cb9f9-a2c7-47d9-a375-60b16fb0098a.png

then do `wsl --update` and `wsl --shutdown`   then  `wsl --set-default-version 2`  and run your dist.

**Comment by owenschupp** [comment]
@equation-group treat other users with respect. I will delete any post you make that does not comply with our [code of conduct](https://github.com/microsoft/WSL/blob/master/CODE_OF_CONDUCT.md). You can provide help without being rude to other users.

@GiveMeFive-wgw I would recommend uninstalling WSL and then following our installation steps [here](https://docs.microsoft.com/en-us/windows/wsl/install) for a clean WSL2 install.

**Comment by GiveMeFive-wgw** [comment]
@owenschupp Thank you for your reply. I have solved the problem!
