### ISSUE TITLE
Can't use Raid0 data inside WSL2 

### ISSUE THREAD

**Issue by guba-odudkin** [microsoft/WSL#7952]
### Version

Microsoft Windows [Version 10.0.19042.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

 20.04

### Repro Steps

- Have a software Raid0 on your system
- Create junction to it inside your normal volume
- Try to cd into it from WSL

### Expected Behavior

Being able to use the files inside

### Actual Behavior

Input/output error

**Comment by OneBlue** [comment]
Hi @guba-odudkin, thanks for reporting this.


Can you provide the details of what exactly you're doing inside WSL (how the raid is configured), and what's the exact output you're getting ?
