### ISSUE TITLE
microsoft / WSL2-Linux-Kernel repo needs to be updated.

### ISSUE THREAD

**Issue by dslater38** [microsoft/WSL#7954]
I updated to Windows 11 build 22538.rs_prerelease.220114-1500. My WSL2 kernel reports now version:
5.10.81.1-microsoft-standard-WSL2

However, the linux-msft-wsl-5.10.y branch at https://github.com/microsoft/WSL2-Linux-Kernel is still on version 5.10.74.3
I use your source to build a custom kernel with aufs enabled. Your git repo needs to be updated so I can update my kernel to 5.10.81.1

**Comment by elsaco** [comment]
@dslater38 if you build your own kernel, grab the latest stable release from https://kernel.org. I'm running 5.16.0 w/out issues. Microsoft is not adding anything to the Linux kernel.

**Comment by 0xbadfca11** [comment]
> Microsoft is not adding anything to the Linux kernel.

That's not true.
DirectX for WSL2 and few features has not merged to main tree.
https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-DXGKRNL-2022
https://github.com/torvalds/linux/tree/master/drivers/hv
https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-5.10.y/drivers/hv
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/MSFT-Merge/log

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.81.1
