### ISSUE TITLE
WSL2 is deleted by itself after registry edited

### ISSUE THREAD

**Issue by fengdasuk19** [microsoft/WSL#7955]
### Version

10.0.19042.1466

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

Open `Regedit`, direct to the following location [as this comment says](https://github.com/microsoft/WSL/issues/1493#issuecomment-417639271):

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\
```

Double click the variable `Flags`, edit its value to `5` or `7`, click OK to confirm.

### Expected Behavior

The WSL runs normally as usual, and environment variable `PATH` under WSL will not read `PATH` value defined under Windows.

### Actual Behavior

The WSL process running before just exits with error code `1`.

I try to start WSL but fail. My terminal emulator (Microsoft Windows Terminal) only gives me error code `4294967295`.

I check the registry location mentioned above a.k.a. `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{GUID}\`, only to find nothing but a variable `DefaultVersion` with type `REG_DWORD` and value `0x2`.

I check the Windows path `C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState` and find this directory is empty now.

[Another user has encountered the same problem as me before.](https://github.com/microsoft/WSL/issues/1493#issuecomment-877719705) @iuliandita 

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/7916110/wsl.zip)

**Comment by equation-group** [comment]
check #5092  and #4929

**Comment by OneBlue** [comment]
Thanks for reporting this @fengdasuk19. 

Looking at the logs it looks like the registry settings are indeed corrupted, so WSL fails to start the default distribution.
The easiest would be to back up the Lxss key, then copy any distribution vhdx that might want to keep, then uninstall the distribution apps and re-register your WSL distributions again. 

That should reset's WSL's state.
