### ISSUE TITLE
Application Error. code 4294967295

### ISSUE THREAD

**Issue by develooper1994** [microsoft/WSL#7956]
### Version

Microsoft Windows [Version 10.0.22000.438]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I updated windows 11 to latest version and wsl stops working. I am not using docker or anything else. I reinstalled ubuntu and wsl. It doesn't work.
open wsl without problem.

### Expected Behavior

open wsl without problem.

### Actual Behavior

{Application Error}
The application was unable to start correctly (0x%lx). Click OK to close the application.

Press any key to continue...

[process exited with code 4294967295]

### Diagnostic Logs

{Application Error}
The application was unable to start correctly (0x%lx). Click OK to close the application.

Press any key to continue...

[process exited with code 4294967295]

**Comment by sylvain-fano** [comment]
same here !

**Comment by equation-group** [comment]
The errors only happen when you click on either of the Ubuntu short-cuts icons. You can start WSL2 from the Windows Terminal.
Download [Windows terminal](https://www.microsoft.com/store/productId/9N0DX20HK701) and type `wsl` to run. 
If you want to run from cmd/ps , open it and click on its icon on top-left of titlebar and go to properties, uncheck **legacy mode**.

also try uninstalling **docker** and running `netsh winsock reset`.  possible /dupe #4904 #4929 #4364

**Comment by develooper1994** [comment]
I am using the windows terminal, powershell and wsl2 by default. I don't use docker.
Also `netsh winsock reset` didn't resolve the issue.

> The error only happens when you click on either of the Ubuntu short-cuts icons. You can start WSL2 from the Windows Terminal. Download [Windows terminal](https://www.microsoft.com/store/productId/9N0DX20HK701) and type `wsl` to run. If you want to run from cmd/ps , open it and click on its icon on top-left of titlebar and go to properties, uncheck **legacy mode**.
> 
> also try uninstalling **docker** and running `netsh winsock reset`. possible /dupe #4904 #4929 #4364

**Comment by equation-group** [comment]
check the issues #4904 #4929 #4364
