### ISSUE TITLE
PHP Built-In Server Never Stops Loading

### ISSUE THREAD

**Issue by gerardojbaez** [microsoft/WSL#7958]
### Version

Microsoft Windows [Version 10.0.22538.1010]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu 20.04

### Other Software

- Tried fresh installs of PHP 8.1.1 and PHP 8.0 (haven't tried on older releases)
- Tried on Firefox Developer Edition 97.0b6
- Tried on Chrome 97.0.4692.99
- Tried on a fresh install of Ubuntu 20.04 (i.e., `wsl --install Ubuntu-20.04`)

### Repro Steps

1. Open your WSL Terminal
2. Install PHP CLI: `sudo add-apt-repository ppa:ondrej/php -y && sudo apt update && sudo apt install php8.1-cli` 
2. Create a basic PHP file: `echo "<?php phpinfo(); ?>" > info.php`
3. Serve the file: `php -S 127.0.0.0:8000`
4. Open your web browser and navigate to http://127.0.0.0:8000/info.php

### Expected Behavior

The file page is loaded and displayed in a second or less.

### Actual Behavior

The file page is loaded, but loading never stops. For Laravel apps, using `php artisan serve` (which uses PHP built-in server under the hood) causes the same problem, and in some cases, the page isn't even displayed (no response from the backend). 

It doesn't matter what you serve, as long as it is a PHP file, the loading never stops. Static files are loading fine, e.g., index.html or a CSS file. Other services besides PHP seem to be working fine (e.g., `npx serve`).

This video shows exactly the behavior:
https://user-images.githubusercontent.com/11788389/150651944-1c509af3-8876-46ad-8b68-1631a5374519.mp4

This started happening yesterday. Never had this issue before; this is why I'm opening an issue here.

### Diagnostic Logs

wsl.etl: [wsl.zip](https://github.com/microsoft/WSL/files/7919096/wsl.zip)

**Comment by gerardojbaez** [comment]
Just installed [Laravel Sail](https://laravel.com/docs/8.x/sail#introduction), it is properly serving the application from http://localhost. It is really weird that everything seems to be working from Docker/Sail and not straight from the PHP built-in server.

**Comment by gerardojbaez** [comment]
I've been experiencing [freezing issues on Phpstorm](https://youtrack.jetbrains.com/issue/WI-64872), [one user suggested](https://youtrack.jetbrains.com/issue/WI-64872#focus=Comments-27-5713833.0-0) to uninstall Windows Subsystem For Linux Preview, which is available from Microsoft Store; I proceeded to uninstall it, then ran `wsl --update --inbox` to get a kernel update. After doing so, I tried `php artisan serve` and it seems to be working again... It may be possible that the never-ending issue is caused by the WSL Preview available from Microsoft Store. I'm hoping that this workaround also fixes the freezing issues on Phpstorm.

**Comment by marco-pm** [comment]
I too have a similar issue after the last update of Windows Subsystem For Linux Preview from the store. After starting a php-apache container on docker on WSL2, accessing it from the browser (http://localhost) hangs indefinitely 90% of the times.
Never had this problem before the last update. Uninstalling the store version solved the problem for me as well.

**Comment by davwheat** [comment]
I've been having an issue for the past few days, and this also happens for a Docker-hosted Laravel (ish) web application.

90% of the time, requests will be stuck loading in a web browser, not even reaching the Apache instance running inside the Docker container (no request is logged).

Sometimes restarting the container will fix the issue temporarily. Other times, it will always hang for 5-10 mins before working for a few mins and then hanging again.

**Comment by fmiqbal** [comment]
I also comment this on https://github.com/microsoft/WSL/issues/4340#issuecomment-1025470447

happening on PHP (73, 74, 80) vanilla built-in webserver, bound to 127.0.0.1 or 0.0.0.0 port 8000 (or anything)

- accessed via `127.0.0.1:8000`, the request will never finish
- accessed via WSL eth0 ip and it doesn't have this problem
- doesn't looks like intermittent, it happen everytime

**Comment by Yovach** [comment]
> I've been having an issue for the past few days, and this also happens for a Docker-hosted Laravel (ish) web application.
> 
> 90% of the time, requests will be stuck loading in a web browser, not even reaching the Apache instance running inside the Docker container (no request is logged).
> 
> Sometimes restarting the container will fix the issue temporarily. Other times, it will always hang for 5-10 mins before working for a few mins and then hanging again.
> 
> The workarounds mentioned above have worked perfectly for me too:
> 
> 1. `wsl --shutdown`
> 2. Uninstall WSL Preview from the Windows Store
> 3. Run `wsl --update --inbox` (first time I got "file cannot be accessed", but second time worked)
> 4. Run `wsl`
> 5. Restart Docker Desktop
> 6. Everything works again!

tysm !! You just fixed my problem !
If `wsl --update --inbox` doesn't work, you can enable in optional features in settings

**Comment by ajitid** [comment]
@Yovach  @davwheat I'm unable to make `--inbox` option to work. Where can I find it? I'm on Win 11 (upgraded from Win 10 Home)

![image](https://user-images.githubusercontent.com/26769888/153029268-3a90cfdd-de17-493f-a5ca-5eb0212471ed.png)

**Comment by Yovach** [comment]
> @Yovach @davwheat I'm unable to make `--inbox` option to work. Where can I find it? I'm on Win 11 (upgraded from Win 10 Home)
> 
> ![image](https://user-images.githubusercontent.com/26769888/153029268-3a90cfdd-de17-493f-a5ca-5eb0212471ed.png)

To use this command, you must be in the "windows insiders" program !
I modified my message because it was confusing

**Comment by mabar** [comment]
`wsl --update` and `wsl --shutdown` fixed the issue for me, reinstall was not needed
