### ISSUE TITLE
DNS resolver responds with a non-zero transaction ID to a request with transaction ID zero

### ISSUE THREAD

**Issue by andras-gerendas** [microsoft/WSL#7964]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Scapy, but it would work the same with any other DNS client which sends a DNS request with a 0 transaction ID.
(Tested it with a custom DNS application as well)

### Repro Steps

Get the resolver IP address (for me it was 172.19.192.1)
`cat /etc/resolv.conf | grep nameserver | cut -d " " -f2`

Start up scapy:
`sudo scapy`

Prepare and execute the following query:
```
req = IP(dst='172.19.192.1') / UDP(sport=RandShort(), dport=53) / DNS(rd=1, qd=DNSQR(qname='google.com', qtype='A'))
res = sr1(req)
```

### Expected Behavior

If you run the same query with a non-zero transaction ID:

>>> req = IP(dst='172.19.192.1') / UDP(sport=RandShort(), dport=53) / DNS(id=42, rd=1, qd=DNSQR(qname='google.com', qtype='A'))
>>> res = sr1(req)
Begin emission:
Finished sending 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets

It responds with the same transaction ID so scapy can parse the answer.

### Actual Behavior

The result will be an infinite wait:

>>> req = IP(dst='172.19.192.1') / UDP(sport=RandShort(), dport=53) / DNS(rd=1, qd=DNSQR(qname='google.com', qtype='A'))
>>> res = sr1(req)
Begin emission:
Finished sending 1 packets.
...^C
Received 3 packets, got 0 answers, remaining 1 packets

In wireshark you can see that the request will fail as the resolver responds with a non-zero transaction ID to a request with a transaction ID with zero.

If the same packet exchange is run in a vanilla Windows command line it works as expected:

PS C:\> python3 -m scapy
... removed the welcome message from scapy ...
>>> req = IP(dst='192.168.0.1') / UDP(sport=RandShort(), dport=53) / DNS(rd=1, qd=DNSQR(qname='google.com', qtype='A'))
>>> res = sr1(req)
Begin emission:
WARNING: Mac address to reach destination not found. Using broadcast.
Finished sending 1 packets.
......................*
Received 23 packets, got 1 answers, remaining 0 packets
>>>

**Comment by elsaco** [comment]
@andras-gerendas I run your DNS request on a Fedora 35 and scapy (so there was no WSL layer involved) and Cloudflare name server. Here's the result:

```
req3 = IP(dst='1.1.1.1') / UDP(sport=RandShort(), dport=53) / DNS(rd=1, qd=DNSQR(qname='google.com', qtype='A'))
>>> res3 = sr1(req3)
Begin emission:
Finished sending 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
>>> res3.show()
###[ IP ]###
  version   = 4
  ihl       = 5
  tos       = 0x20
  len       = 72
  id        = 20080
  flags     = DF
  frag      = 0
  ttl       = 59
  proto     = udp
  chksum    = 0x2ca8
  src       = 1.1.1.1
  dst       = 192.168.1.195
  \options   \
###[ UDP ]###
     sport     = domain
     dport     = 37202
     len       = 52
     chksum    = 0x807b
###[ DNS ]###
        id        = 0
        qr        = 1
        opcode    = QUERY
        aa        = 0
        tc        = 0
        rd        = 1
        ra        = 1
        z         = 0
        ad        = 0
        cd        = 0
        rcode     = ok
        qdcount   = 1
        ancount   = 1
        nscount   = 0
        arcount   = 0
        \qd        \
         |###[ DNS Question Record ]###
         |  qname     = 'google.com.'
         |  qtype     = A
         |  qclass    = IN
        \an        \
         |###[ DNS Resource Record ]###
         |  rrname    = 'google.com.'
         |  type      = A
         |  rclass    = IN
         |  ttl       = 0
         |  rdlen     = None
         |  rdata     = 142.250.69.206
        ns        = None
        ar        = None
```
It depends on the DNS server if you get an answer or not when `id=0`

**Comment by andras-gerendas** [comment]
This just means that the issue is present on that DNS server as well.

The DNS specification (RFC 1035) doesn't say anything about treating the value 0 for ID differently than the others.

If the DNS resolver behind WSL receives a message with ID zero it has to send the response back with it otherwise there's an ID mismatch and the response is not valid.
If it treats the number 0 in the ID as a malformed query it should return with a non-zero response code.
