### ISSUE TITLE
donate to stop climate change

### ISSUE THREAD

**Issue by jordan69420** [microsoft/WSL#7967]
plz donate something to lobby against lobbyists for coal and oil in the US, because soon there will be no one left to buy Microsoft products (or any other product) because humans destroyed earth.

**Comment by jordan69420** [comment]
I am saying to do this in the US because it is a big emitter, and trying to get China to do anything is pointless

**Comment by elsaco** [comment]
@jordan69420 please stop spreading misinformation or do it on Twitter. This is GitHub!

**Comment by equation-group** [comment]
> @jordan69420 please stop spreading misinformation or do it on Twitter. This is GitHub!

Climate change is misinformation ?
