### ISSUE TITLE
Shell user@hostname prompt prints diagonally

### ISSUE THREAD

**Issue by equation-group** [microsoft/WSL#7969]
### Version

Microsoft Windows [Version 10.0.19043.1469]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.60.1

### Other Software

tmux 3.2a

### Repro Steps

Step1: launch tmux, then create new window "ctrl + b,  c" 
step2: type any command like 'top" , press enter
step3: go to tmux terminal using command "ctrl + b,  : "
step4:  then press Esc button few times (6 times)

### Expected Behavior

It should show user prompt in new line as usual.

### Actual Behavior

It gives error  "[server exited unexpectedly]" and tmux closes automatically,  now I see shell prompt printed diagonally i.e. with tab indentaion.
I mean, if you give any command to shell and press enter, it process and gives output, then  user prompt will show diagonally.
It also hides the cursor.

### Diagnostic Logs

[tmux-server.log](https://gist.github.com/equation-group/1eea13e6d0f5ec156f400f9868d60961/raw/9cfdf2b2d9665709d80af538c90e1c6cee762210/tmux-server.log)
[tmux-client.log](https://gist.githubusercontent.com/equation-group/32bbecca2c322756313d4af8f348b939/raw/626a853f45cef527ce327a86cb04cd2b25067a91/tmux-client.log)

**Comment by elsaco** [comment]
@equation-group since `tumx` crashes the terminal needs to be reset. Just type `stty sane` or `reset` to recover your terminal. This issue was reproduces with `tmux 3.2.a` only, `tmux 3.0a` and `tmux 3.1c` did not crash when pressing `ESC` multiple times.

**Comment by craigloewen-msft** [comment]
I also wasn't able to reproduce on tmux 3.0a as @elsaco mentioned. This seems like a tmux related error, and not something directly related to WSL.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/42221804/151071489-d3da4a5f-f57c-4325-bdf1-ff8cea512c31.png">

**Comment by equation-group** [comment]
@craigloewen-msft yes, it's related to tmux. thanks
