### ISSUE TITLE
Please Enable CONFIG_F2FS_FS

### ISSUE THREAD

**Issue by macromorgan** [microsoft/WSL#7973]
Please enable the F2FS filesystem for the WSL2 kernel. This will allow me to mount certain mobile and flash friendly Linux devices on Windows, and allow me to do some development for mobile devices that require F2FS disk images.

CONFIG_F2FS_FS=y (this symbol to enable the filesystem)
CONFIG_F2FS_STAT_FS=y (nice to have, needs to be y or n)
CONFIG_F2FS_FS_XATTR=y (looks like this is enabled for EXT4 and BTRFS)
CONFIG_F2FS_FS_POSIX_ACL=y (looks like this is enabled for EXT4 and BTRFS)
CONFIG_F2FS_FS_SECURITY=y (looks like this is enabled for EXT4 and BTRFS)
CONFIG_F2FS_CHECK_FS=n
CONFIG_F2FS_IO_TRACE=n
CONFIG_F2FS_FAULT_INJECTION=n
CONFIG_F2FS_FS_COMPRESSION=y (nice to have)
CONFIG_F2FS_FS_LZO=y (nice to have)
CONFIG_F2FS_FS_LZ4=y (nice to have)
CONFIG_F2FS_FS_ZSTD=y (nice to have)
CONFIG_F2FS_FS_LZORLE=y (nice to have)

**Comment by AlessandroGandolfi** [comment]
why was this issue closed without any reply or info? i'd like too see this feature implemented as well

**Comment by Fede2782** [comment]
I would like to use F2FS on wsl2 as well

**Comment by zhenruyan** [comment]
I would like to use F2FS on wsl2 as well too too too

**Comment by wally4000** [comment]
Ditto

**Comment by zhenruyan** [comment]
https://github.com/zhenruyan/WSL-libre-linux-kernel

This is my compiled wsl kernel based on gnu libre kernel code

Modules such as ntfs.

Modules such as exfat.

Modules such as f2fs.

Modules such as btrfs.

@macromorgan @Fede2782 @wally4000

**Comment by wally4000** [comment]
cool, thank you On 11 Oct 2023, at 17:20, 真如赝 ***@***.***> wrote:﻿
https://github.com/zhenruyan/WSL-libre-linux-kernel
This is my compiled wsl kernel based on gnu libre kernel code
Modules such as ntfs.
Modules such as exfat.
Modules such as f2fs.
Modules such as btrfs.
@macromorgan @Fede2782 @wally4000

**Comment by okineadev** [comment]
I have my own fork with `f2fs` support, you can compile it yourself and use it - https://github.com/okineadev/WSL2-Linux-Kernel/tree/f2fs-support

**Comment by mshcherbyna99** [comment]
Hello, @macromorgan, @AlessandroGandolfi, @Fede2782, @zhenruyan and @wally4000.

What do you all think about my proposal [above](https://github.com/microsoft/WSL/issues/7973#issuecomment-2783268143)?

Thank you.

**Comment by wally4000** [comment]
Not sure why I'm being tagged here but I've switched away to Fedora Linux mostly to be able to use the tooling needed to do the tasks required.
:)
