### ISSUE TITLE
**ANYTHING** I install on wsl it **keeps** Installing

### ISSUE THREAD

**Issue by zgyt4033** [microsoft/WSL#7975]
### Version

Microsoft Windows [Version 10.0.19044.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

Try to install Debian

### Expected Behavior

install success

### Actual Behavior

keep getting WslRegisterDistribution failed with error: 0x8000000d or 0x800706be.
And when I try wsl -l -v it shows:
  NAME      STATE           VERSION
  Debian    Installing      2

Actually **ANYTHING** I install on wsl it **keeps** Installing, include Docker Desktop

Have tried methods from issue 5768 and nothing works.
 virtual machine platform and window subsystem for linux had been enabled from Windows features. 
2 Years ago I've succeed install Ubuntu 1804 on wsl.

**Comment by equation-group** [comment]
Try installing distros manually, follow this: [arch_linux_wsl2](https://github.com/nckslvrmn/arch_linux_wsl2) 
or [debian](https://github.com/Rishu20/Debian_WSL) ,  follow same tutorial from arch.

**Comment by craigloewen-msft** [comment]
Can you please try running this to check your system health:
`DISM /Online /Cleanup-Image /CheckHealth`

And please see this issue describing a similar error:
https://github.com/microsoft/WSL/issues/4084

It could be that you have something malformed in the registry. 

Could you also please provide logs for us? It'll help us narrow down the error. /logs

Thanks!

**Comment by zgyt4033** [comment]
> Can you please try running this to check your system health: `DISM /Online /Cleanup-Image /CheckHealth`
> 
> And please see this issue describing a similar error: #4084
> 
> It could be that you have something malformed in the registry.
> 
> Could you also please provide logs for us? It'll help us narrow down the error. /logs
> 
> Thanks!
Tried DISM:
no component store corruption detected
manually cleaning registry is hard.


> Hello! Could you please provide more logs to help us better diagnose your issue? You can find instructions on how to [attach logs here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), please make sure to post the link to the Feedback Hub item in this chat so we can see it.
> 
> Thank you!

uploaded with Feedback Hub

**Comment by craigloewen-msft** [comment]
Can you please link me to the feedback hub item? It will help me find it quickly. Thanks!

**Comment by equation-group** [comment]
> Can you please link me to the feedback hub item? It will help me find it quickly. Thanks!

I have not reported to feedback hub, it is related to WSL so i wrote here.

**Comment by benhillis** [comment]
I suspect that something crashed while you were installing the Debian distro. I'd suggest unregistering via `wsl.exe --unregister debian`
