### ISSUE TITLE
Fetch requests to web app accessed on localhost gets stuck in pending state

### ISSUE THREAD

**Issue by 39digits** [microsoft/WSL#7982]
### Version

Windows 11 Pro 21H2 (10.0.22000.469)

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu 20.04

### Other Software

Node web app using any of the following:

- [Express JS](https://expressjs.com/)
- [Next.js](https://nextjs.org/)
- [Remix](http://remix.run/)

### Repro Steps

I've experienced the issue describe below using a few Node frameworks but the quickest way to reproduce is to do one of the following

### Next.js Blog Example

1. Open a Terminal into WSL2 within which Node is installed.
2. Get the IP address for WSL2 `ip addr | grep eth0` for use later
3. Create a directory to use for our app and cd into it.
4. Create the Next.js app using the blog template `npx create-next-app -e blog .`
5. Run `npm run dev` to start the app on port 3000 (default port)
6. In Windows open any browser and open the Dev Tools on the Networking tab
7. Access the app on http://localhost:3000
8. Wait over 5 seconds and click on "Posts" link
9. Note the fetch request in the Network tab is stuck in a pending state.  The Timing section of the fetch request in the Network tab shows it stuck in the Initial Connection phase.
10. Now access the site against the IP address on port 3000 and you'll see the fetch requests always work

### Express-based Hello World

1. Open a Terminal into WSL2 within which Node is installed
2. Get the IP address for WSL2 `ip addr | grep eth0` for use later
3. Create a directory to use for our app and cd into it.
4. Initialise a new Node app `npm init -y`.
5. Install Express `npm install --save express`
6. Create `app.js` with the following Hello World code
```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

const server = app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```
7. Run the app `node app.js`
8. In Windows open any browser and open the Dev Tools on the Networking tab
9. Access the app on http://localhost:3000
10. Refresh the app a few times and you'll notice the fetch request eventually gets stuck in a Pending state.  The Timing section of the fetch request in the Network tab shows it stuck in the Initial Connection phase.
11. Now access the site against the IP address on port 3000 and you'll see the fetch requests always work
12. Close the app (`Ctrl + C`) and edit the `app.js` and add the following as the last line in the app 
```
server.keepAliveTimeout = 0;
```
13. Rerun the app `node app.js` and you'll find the app no longer gets stuck in a pending state against http://localhost:3000.

### Expected Behavior

Browsing a node-based web app running in WSL2 should not have network issues when accessed on localhost.

### Actual Behavior

If I access a Node application running inside of WSL2 in the browser on localhost, the Network tab will show that some fetch requests get stuck in a pending state. The Network details shows that it gets stuck in the Initial Connection stage. This is corroborated by there being no hits in the app logs if logging is implemented in the app.

This only happens if I try to access the app from Windows using http://localhost against the relevant port (usually 3000 or 8000 depending on the app I'm running). If I access the site using the IP address for WSL2 then the GET requests are never stuck in the pending state.

I have had the issue since the last update - everything was running perfectly against localhost prior to the update.

The common thread is Node's HTTP library which has a default keep-alive timeout of 5 seconds. I have experienced the issue using Express, Next.js, and Remix - Gatsby was unaffected.

I confirmed this by creating the Hello World Express app, verified the issue still occurred under this simplest of apps, then explicitly set the http server's keepAliveTimeout setting to 0. The issue went away completely.

To reiterate, the issue only showed up since the last update and was working as expected prior to that allowing localhost to be used without issue.

**Comment by Rauttis** [comment]
I've started seeing the same issue since yesterday as well, this completely broke my current web dev workflow.

**Comment by guilhermetod** [comment]
Same here. It's really breaking productivity there days.

**Comment by pikadun** [comment]
network packet capture: https://github.com/microsoft/WSL/issues/7979

**Comment by AdamArutyunov** [comment]
Same issue, Windows 11 Insider Preview Dev from week ago.

**Comment by timur-khakhalev** [comment]
Same issue, it works ok only under VPN

**Comment by jaredholdcroft** [comment]
Uninstalling the store version of WSL fixed it for me.

**Comment by fmiqbal** [comment]
try accessing via eth0 wsl ip

**Comment by rvzug** [comment]
Uninstalling "Windows Subsystem for Linux Preview" and running ``wsl --update`` in PS did the trick for me.

**Comment by HollyIT** [comment]
I can also confirm this and that uninstalling the store version fixed the problem. Probably the most interesting thing is that this is only affecting Chromium based browsers (Chrome, Edge). Firefox is working fine.

**Comment by Dozorengel** [comment]
> Uninstalling "Windows Subsystem for Linux Preview" and running `wsl --update` in PS did the trick for me.

If I uninstall the store version, will I lose all the distro with my data as well?

**Comment by HollyIT** [comment]
@Dozorengel - My data was fine after uninstalling the store version, both on my desktop and laptop. Just to be safe though, you might want to do an export of your distro.

**Comment by n1cholson** [comment]
Reinstalled to Windows 11 release version and no longer seeing the issue.

**Comment by benhillis** [comment]
Release 0.51.3 is in testing and has a fix for this issue.

**Comment by benhillis** [comment]
Fixed in https://github.com/microsoft/WSL/releases/tag/0.51.3. Should be available via the Microsoft Store in a few hours.

**Comment by gxtaillon** [comment]
@benhillis I'm on 0.56.2 (5.10.102.1) and it's still dropping. Although it seems lees frequent.

**Comment by genesiscz** [comment]
This is still happening to me :(

**Comment by FrankBevr** [comment]
Same
