### ISSUE TITLE
wsl2 Warning! D-Bus connection terminated. Failed to start service: Connection reset by peer

### ISSUE THREAD

**Issue by kanhaiyabaranwal** [microsoft/WSL#7985]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Starting nginx service from powershell gives below error

**[sudo] password for <kan>: Warning! D-Bus connection terminated.
Failed to start nginx.service: Connection reset by peer
See system logs and 'systemctl status nginx.service' for details.**

Starting the same service from inside distro works with user kan.

Command to start the service is
sudo /usr/bin/systemctl start nginx.service

Note: this is reproducible on few machines while working on others.

### Repro Steps

Have WSL2 distro 20.04 and nginx installed inside it.

Run the service from outside distro. 

This works fine on some machine but fails on others.

### Expected Behavior

nginx and mssql-server should start from outside with sudo

### Actual Behavior

services not starting from outside. However, this starts when I go manually inside the distro and then run the same command

**Comment by OneBlue** [comment]
Thanks for reporting this @kanhaiyabaranwal.

Which command are you running to start nginx ? Based on the output, it looks like a systemd command, which isn't supported at the moment.

**Comment by siddharthmagadum16** [comment]
If the command is not supported, then is there any other way to fix this issue?
