### ISSUE TITLE
Command unrecognized

### ISSUE THREAD

**Issue by MakesYT** [microsoft/WSL#8001]
### Version

Microsoft Windows [Version 10.0.20348.169]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu-18.04

### Repro Steps

in powershell ：
Run the command：”wsl --set-default-version 2“ and ”wsl --set-default-version“

### Expected Behavior

Change the default version of the WSL

### Actual Behavior

but return 
<details>
`PS C:\Users\Administrator> wsl --set-default-version 2
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.

    --mount <Disk>
        Attaches and mounts a physical disk in all WSL2 distributions.

        Options:
            --bare
                Attach the disk to WSL2, but don't mount it.

            --type <Type>
                Filesystem to use when mounting a disk, if not specified defaults to ext4.

            --options <Options>
                Additional mount options.

            --partition <Index>
                Index of the partition to mount, if not specified defaults to the whole disk.

    --unmount [Disk]
        Unmounts and detaches a disk from all WSL2 distributions.
        Unmounts and detaches all disks if called without argument.` 
</details>
but another command 
PS C:\Users\Administrator> wsl --set-default-version  

A version number could not be parsed.

“wsl --set-default-version”works fine, but when I add the version number, it can't recognize the version parameter

**Comment by OneBlue** [comment]
Thanks for reporting this @MakesYT.

What exactly command are you running ? The correct syntaxes would be:

- wsl --set-default-version 2

Or 

- wsl --set-default-version 1

**Comment by MakesYT** [comment]
> Thanks for reporting this @MakesYT.
> 
> What exactly command are you running ? The correct syntaxes would be:
> 
> - wsl --set-default-version 2
> 
> Or 
> 
> - wsl --set-default-version 1

both but only the “wsl --set-default-version 1” is working
when running the “wsl --set-default-version 2” returns command help

**Comment by OneBlue** [comment]
Oh I know what's happening @MakesYT:  You're on a Windows server build, and Windows server doesn't support WSL2, that's why you're getting this error.

We recently added WSL2 support to Windows Server, but at the moment it's only available on the insider preview builds.

**Comment by MakesYT** [comment]
> Oh I know what's happening @MakesYT:  You're on a Windows server build, and Windows server doesn't support WSL2, that's why you're getting this error.
> 
> We recently added WSL2 support to Windows Server, but at the moment it's only available on the insider preview builds. 

How soon will WSL 2 be available in the official release of Windows Server？
