### ISSUE TITLE
wsl.conf silently ignored if DOS line endings.

### ISSUE THREAD

**Issue by engineerkatie** [microsoft/WSL#8002]
We machine generate wsl.conf files. Naively assumed they would need \r\n line-endings to be DOS/WIN compatible & hence generated them so. It appears to be silently ignored if it has them. Switching to \n meant the file was honoured at next start.

It would nice if it 'just worked', or if the file format requirements were more tightly specified somewhere around the https://docs.microsoft.com/en-us/windows/wsl/wsl-config page. Also, although trickier, some error message regarding bad formats would be useful but I appreciate there may be no easy channel for this.

**Comment by craigloewen-msft** [comment]
Similar to this request, we added a change to the docs to make it explicit that this file requires Unix based file endings. 

https://github.com/MicrosoftDocs/WSL/issues/1439

I've marked this as a bug to track this as an open issue so we can give better errors to users when config isn't parsed correctly.
