### ISSUE TITLE
unable to view wsl files in explorer

### ISSUE THREAD

**Issue by sparsh-b** [microsoft/WSL#8005]
### Version

Microsoft Windows [Version 10.0.22000.469]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-18.04

### Other Software

Have VSCode 1.63.2 with Remote WSL v0.63.13 installed. But don't know if the below problem relates to it.

### Repro Steps

1) Open powershell
2) type `wsl` & enter
3) change directory to home: `cd ~`
4) `explorer.exe .`

### Expected Behavior

A window of file explorer should open showing the contents of the folder `/home/<wsl-LinuxDistro_username>`

### Actual Behavior

A window of file explorer opens showing the contents of the folder `C:\Users\windows_username\Documents`

### Diagnostic Logs
Opening File explorer & typing `\\wsl$` returns an error as shown [here](https://drive.google.com/file/d/1C1jA-dr-9x3Z5QmLKo5r0nw4DjIQlnux/view?usp=sharing). 

Clicking Linux from the quick access menu returns [this](https://drive.google.com/file/d/1UASEohG5pQenw0k0JIFr6yWdShcDRTbw/view?usp=sharing) error.

Saw [this](https://github.com/microsoft/WSL/issues/7834) issue & [this](https://github.com/microsoft/WSL/issues/5999#issuecomment-720728455) comment, but unsure how they'll help me.

**Comment by equation-group** [comment]
How did you assume the expected behaviour ?  
windows GUI and linux distro is unrelated, you could only launch program from one into another.  The Actual behaviour is expected behaviour, this is not a bug.

**Comment by sparsh-b** [comment]
Thanks for the reply @equation-group !
Is there a way to view the files in `/home/<wsl-LinuxDistro_username>` in windows GUI?

**Comment by sparsh-b** [comment]
Raising a new issue. closing this one :)
