### ISSUE TITLE
gnome-disks does not see any drives

### ISSUE THREAD

**Issue by mslinn** [microsoft/WSL#8006]
### Version

Version 10.0.19044 Build 19044

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

21.10

### Repro Steps

Simply run:

```shell
$ gnome-disks&
```

### Expected Behavior

I expected to see the Linux system disk and all mounted disks, at a minimum. For example, this is what a machine natively running the same version of Ubuntu shows. Note that the removable Voyager S3 drive is included (attached via USB).
![image](https://user-images.githubusercontent.com/485818/152002027-c0c028e5-6632-49e1-8166-d5164c34b947.png)

`gnome-disks` is useful for backing up images of drives, which can be mounted via loopback. Much better than trying to make a tar from a WSL/WSL2 instance!

### Actual Behavior

No disks are shown. 
![image](https://user-images.githubusercontent.com/485818/152001747-e6585a72-6f23-4b96-a710-1df582bcf819.png)

**Comment by OneBlue** [comment]
Thanks for reporting this @mslinn.

This is actually by-design given that WSL2 run in a VM, and block devices aren't accessible from inside the VM (unless you specifically attach them with `wsl --mount`)

See: https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

**Comment by mslinn** [comment]
I believe it would be helpful to be able to access the virtual file system as a drive. Administration would be much easier.
