### ISSUE TITLE
arm64: wsl --cd \\wsl$\Distro\xxx failing

### ISSUE THREAD

**Issue by DHowett** [microsoft/WSL#8007]
### Version

22000.466

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Repro Steps

From CMD on ARM64, @cinnamon-msft runs:

```
wsl --cd \\wsl$\Ubuntu\home\cinnamon
```

### Expected Behavior

WSL starts in `/home/cinnamon`.

### Actual Behavior

```
Microsoft Windows [Version 10.0.22000.466]
(c) Microsoft Corporation. All rights reserved.
C:\Users\cinnamon>wsl --cd \\wsl$\Ubuntu\home\cinnamon
The parameter is incorrect.
C:\Users\cinnamon>
```

```
> wsl --status
Default Distribution: Ubuntu
Default Version: 2
Windows Subsystem for Linux was last updated on 10/4/2021
WSL automatic updates are on.
Kernel version: 5.10.60.1
```

**Comment by DHowett** [comment]
She further reports that `\\wsl$\Ubuntu\home\cinnamon` works properly in Explorer!

**Comment by DHowett** [comment]
Linking: https://github.com/microsoft/terminal/issues/12195

**Comment by zadjii-msft** [comment]
MSFT:34471859 may be relevant

**Comment by benhillis** [comment]
I have a repro of this, currently debugging.

With the --cd change, why are you passing a Windows path to get to the Linux file system?  You could also just pas /home/cinnamon? I verified that will work.

**Comment by benhillis** [comment]
I've also verified this is only an issue for inbox WSL, this works for lifted.

**Comment by DHowett** [comment]
> With the --cd change, why are you passing a Windows path to get to the Linux file system?  You could also just pass `--cd /home/cinnamon`? I verified that works.

That's a fair question! Couple reasons:

1. When we decided on this, it was to bridge the gap for all terminal users s.t. we didn't have to treat some paths as "a directory for CreateProcess," and some as "a directory for the command line"
2. There was some issue about CreateProcess not working for `\\wsl$` paths before WSL had started, so we believed that deferring resolution until *after* it had started would help.

**Comment by benhillis** [comment]
I'm not sure I follow, either way you're passing cd on the command line?

For the second, if the path is a Windows Path, WSL calls SetCurrentDirectoryW on the Windows path, so it's no different than the behavior you're trying to avoid.

**Comment by DHowett** [comment]
Right. For any WSL, we always promote the starting directory to `--cd`.

We can refine that logic _for sure_. We have to service a release v quickly for the broken localizations anyway :)

**Comment by benhillis** [comment]
Cool, can you guys start adding our team to wsl-related terminal pull requests? We'd like to be in the loop to help spot things like this in the future.

I tracked down this bug to something we fixed in October in the OS (and around the same time for lifted).

**Comment by DHowett** [comment]
Gladly!

**Comment by zadjii-msft** [comment]
> I tracked down this bug to something we fixed in October in the OS

That might explain why we weren't seeing this on our machines on selfhost builds, but Kayla was seeing it on the a 22000.466 machine. This was in fact MSFT:34471859 which was fixed a while back, so you guys should feel free to close this one out. Thanks for taking the look!
