### ISSUE TITLE
WSL memusage reporting not correct and cause OOM in windows applications. 

### ISSUE THREAD

**Issue by pwang2** [microsoft/WSL#8013]
### Version

Microsoft Windows [Version 10.0.19042.1415] 

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

.wslconfig
```
[wsl2]
localhostForwarding = true
pageReporting=true
idleThreshold=1
```

### Expected Behavior

The memory reporting should reflect the actual usage in WSL

### Actual Behavior

![image](https://user-images.githubusercontent.com/1592014/152217454-4b79e6ba-b066-472d-ac5e-5aaefc2a0862.png)
 
![image](https://user-images.githubusercontent.com/1592014/152217543-f9283bf1-f605-4025-afe1-924391df5b94.png)

### Diagnostic Logs

No other Hyper-V powered VM or software are installed.

**Comment by Stevad** [comment]
I think this is caused by how Linux works with memory. `htop` reports only "used" memory (in green) by running applications and does not include "cached" memory (in yellow). But this memory is also reserved by the Linux kernel and Windows sees that this memory is in use, so it cannot free it and return it to the host.

Some kind of explanation: https://medium.com/marionete/linux-disk-cache-was-always-there-741bef097e7f

**Comment by pwang2** [comment]
Yes, That's also what I think.  Thanks for confirming.  

I was trying to use the pageReporting in WSL2, then it defaults allocating 12GB out of 16GB. When I run some language server feature,  the cache could goes up to 10GB(crazzzzzzzzzy!)    Sometimes I have to `# sync; echo 1 > /proc/sys/vm/drop_caches`  when windows memory is 99% occupied and running really slow.   maybe, I should give WSL VM a fixed Memory quota instead.

**Comment by Stevad** [comment]
You can configure the amount of memory and number of CPUs for VM with WSL.

Check out this article - https://docs.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file

**Comment by pwang2** [comment]
@Stevad , I am aware of that. Thank again!   I just have some illusion about page reporting will be more capable to work with linux pagecaches here. (crazy npm eco system and language servers could be the culprit in my case.)  I would just make an oneliner to drop caches when needed.   :)
