### ISSUE TITLE
I can't typing  only lowercase 'i' in my wsl2 + ubuntu environment. How can i fix  it?  

### ISSUE THREAD

**Issue by EdwardYoungMoon** [microsoft/WSL#8016]
### Version

10.0.19042.867

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 16.04

### Repro Steps

don't needed

### Expected Behavior

don't know

### Actual Behavior

nothing

### Diagnostic Logs

don't needed

**Comment by EdwardYoungMoon** [comment]
only lowercase type 'i' don't work in wsl2

**Comment by owenschupp** [comment]
Closing as this is not helpful for giving context as to what is happening and how to investigate. Highly likely that this is not even related to WSL
