### ISSUE TITLE
WSL2 cannot SSH to any servers

### ISSUE THREAD

**Issue by hockeybrad** [microsoft/WSL#8018]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

ssh userid@IPaddress
OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to xx.xxx.xx.220 [xx.xxx.xx.220] port 22.
debug1: connect to address xx.xxx.xx.220 port 22: Connection timed out
ssh: connect to host xx.xxx.xx.220 port 22: Connection timed out

I can ssh from a VirutalBox VM running CentOS, and I can ssh from a simple command line (cmd) with this command. I expect if I installed any other ssh client it would work. It just doesn't work in WSL2. 

After reading many pages of forums, I added a rule for incoming port 22 connections to the windows firewall. That didn't work so I just turned the whole firewall off and the ssh command still doesn't work. I don't think it's windows firewall preventing this. I do have Sophos Safeguard on this machine but am not able to detect if it has another layer of network protection. I will ask my company about this.

### Expected Behavior

I am expecting a successful ssh connection.

### Actual Behavior

ssh: connect to host xx.xxx.xx.220 port 22: Connection timed out

**Comment by saade** [comment]
same here

**Comment by badr-ou** [comment]
I had the same problem and it was because of the network, I solved it by following this solution : 

Open Command Prompt as an Administrator and type these

netsh winsock reset 
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns

Reboot your machine.

**Comment by OneBlue** [comment]
Thanks for reporting this @hockeybrad. Does the command also time out if use ssh.exe on Windows ? 

Are you trying to connect to a local ip address ?
