### ISSUE TITLE
wsl.exe --list --online 报错:无法解析服务器的名称或地址

### ISSUE THREAD

**Issue by qingyun2016** [microsoft/WSL#8025]
### Version

Microsoft Windows [版本 10.0.22543.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Repro Steps

wsl.exe --list --online
无法解析服务器的名称或地址

### Expected Behavior

![wsl_error](https://user-images.githubusercontent.com/19773922/152715324-4d7b3d78-b46e-4cb3-84f9-483069e92801.png)

### Actual Behavior

I got this error when list linux version use wsl --list --online

**Comment by equation-group** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by craigloewen-msft** [comment]
@equation-group please see our [Code of Conduct](https://github.com/microsoft/WSL/blob/master/CODE_OF_CONDUCT.md) for interacting with users on this repo.

**Comment by craigloewen-msft** [comment]
This seems like an internet connection issue from what you posted, can you please check your network connection and provide logs? 

/logs

**Comment by dbgee** [comment]
![image](https://user-images.githubusercontent.com/46910972/191880122-28d7d2b0-e295-4c83-9cf5-14248b0bba8a.png)

same issue

**Comment by qinshuze** [comment]
> > ### 版本
> > 微软视窗 [版本 10.0.22543.1000]
> > ### 温控超版本
> > 
> > * [x] 断续器 2
> > * [ ] 断续器 1
> > 
> > ### 内核版本
> > 5.10.81.1
> > ### 发行版
> > _无响应_
> > ### 其他软件
> > _无响应_
> > ### 重现步骤
> > wsl.exe --list --online 无法解析服务器的名称或地址
> > ### 预期行为
> > ![wsl_error](https://user-images.githubusercontent.com/19773922/152715324-4d7b3d78-b46e-4cb3-84f9-483069e92801.png)
> > ### 实际行为
> > 当列表linux版本使用wsl时，我得到了这个错误 --列表 --在线
> > ### 诊断日志
> > _无响应_
> 
> 老哥 你的解决了吗 我遇到一样的问题

我遇到同样的问题了，在我修改了

> > ### 版本
> > 微软视窗 [版本 10.0.22543.1000]
> > ### 温控超版本
> > 
> > * [x] 断续器 2
> > * [ ] 断续器 1
> > 
> > ### 内核版本
> > 5.10.81.1
> > ### 发行版
> > _无响应_
> > ### 其他软件
> > _无响应_
> > ### 重现步骤
> > wsl.exe --list --online 无法解析服务器的名称或地址
> > ### 预期行为
> > ![wsl_error](https://user-images.githubusercontent.com/19773922/152715324-4d7b3d78-b46e-4cb3-84f9-483069e92801.png)
> > ### 实际行为
> > 当列表linux版本使用wsl时，我得到了这个错误 --列表 --在线
> > ### 诊断日志
> > _无响应_
> 
> 老哥 你的解决了吗 我遇到一样的问题

我遇到了同样的问题，似乎是DNS引起的，在我修改了DNS之后，该问题得到解决
![image](https://user-images.githubusercontent.com/22045080/192083319-63f19583-1fa7-4d65-be6e-ac3a2a87a5d1.png)

**Comment by qinshuze** [comment]
我遇到了同样的问题，这似乎是DNS引起的，在我修改了DNS之后，该问题得到解决
![image](https://user-images.githubusercontent.com/22045080/192083494-b934a435-99db-405e-83d7-1d7a23f4b689.png)

**Comment by qingyun2016** [comment]
这个问题是由于安装包地址被墙了的缘故，最终的解决方案，在hosts中增加：
185.199.108.133&nbsp; raw.githubusercontent.com
即可解决，但是有时执行wsl.exe --list --online命令还是会有连不上的情况，多执行几次就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月24日(星期六) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/WSL] wsl.exe --list --online 报错:无法解析服务器的名称或地址 (Issue #8025)





   
版本
 
微软视窗 [版本 10.0.22543.1000]
 
温控超版本
  
 断续器 2
 
 断续器 1
  
内核版本
 
5.10.81.1
 
发行版
 
无响应
 
其他软件
 
无响应
 
重现步骤
 
wsl.exe --list --online 无法解析服务器的名称或地址
 
预期行为
 

 
实际行为
 
当列表linux版本使用wsl时，我得到了这个错误 --列表 --在线
 
诊断日志
 
无响应
  
老哥 你的解决了吗 我遇到一样的问题
  
我遇到同样的问题了，在我修改了
   
版本
 
微软视窗 [版本 10.0.22543.1000]
 
温控超版本
  
 断续器 2
 
 断续器 1
  
内核版本
 
5.10.81.1
 
发行版
 
无响应
 
其他软件
 
无响应
 
重现步骤
 
wsl.exe --list --online 无法解析服务器的名称或地址
 
预期行为
 

 
实际行为
 
当列表linux版本使用wsl时，我得到了这个错误 --列表 --在线
 
诊断日志
 
无响应
  
老哥 你的解决了吗 我遇到一样的问题
  
我遇到了同样的问题，似乎是DNS引起的，在我修改了DNS之后，该问题得到解决

**Comment by qingyun2016** [comment]
统一回复下如何解决方案：

1. 执行wsl --list --online时wsl会到raw.githubusercontent.com这个接口去取已经支持的的linux版本，如果报错，那就说明这个地址访问不了，这个时候你可以到https://ipaddress.com这个网站，将“raw.githubusercontent.com”查询到服务器地址有四个

![image](https://user-images.githubusercontent.com/19773922/192084483-df15113f-53ee-471e-9978-d0e71fae5ec9.png)

2.接下来从查到的4个地址，在你电脑上ping 查到的地址 -t，看哪个地址能连接上
3.然后再将这个ping通的这个地址配置的你的hosts文件当中：添加“185.199.108.133（我这里这个地址能ping通，你们的填自己能ping通的） raw.githubusercontent.com”就可以了：

![image](https://user-images.githubusercontent.com/19773922/192084636-91778e67-ec08-4a96-8043-4abdb3229684.png)

**Comment by wufeng87** [comment]
谢谢分享 开启wsl2
删除appdata下所有Docker目录，然后重启应用就好了

**Comment by yuanshun-guo** [comment]
You can access it by connecting to the VPN, I have resolved it

**Comment by bGZo** [comment]
TL;DR: Go `ms-settings:network-proxy`

我试了 `export http_proxy`, `$env:http_proxy`, `Proxifier`，全都没用，最后发现设置一下系统代理就能 install，OMG, So mess window is!

**Comment by mydaoyuan** [comment]
china shit network

**Comment by javascripet** [comment]
傻逼ccp这也封那也封

**Comment by Darrenpig** [comment]
## 解决了，兄弟们。修改代理（其实不算是被墙，准确来说是域名污染，就像访问GIthub可以直接改host一样）
Clash配置问题，之前由于图省事放弃了winget,打开微软商店，也是调试了半天（Clash里关闭了系统模式）

![Image](https://github.com/user-attachments/assets/8e087715-e4bc-4868-a987-9569270b8988)
这个是前后的对比图打印
- 错误代码: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND
- 成功代码：以下是可安装的有效分发的列表。使用 'wsl.exe --install <Distro>' 安装。......
## 具体实现步骤：
### 1.打开 Clash
### 2.修改 Clash 系统代理【system proxy】

![Image](https://github.com/user-attachments/assets/7b20ed0a-0e60-4074-94d7-2a73ed2b6543)
再次打开cmd，输入wsl.exe --list --online 即可，看见前面的打印
