### ISSUE TITLE
[Error: 0x80070005] I cannot install WSL Distribution with error code 0x80070005.

### ISSUE THREAD

**Issue by Tanar-tech** [microsoft/WSL#8026]
### Version

Microsoft Windows[20H2, 19042.1415]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu20.04

### Repro Steps

①Install Ubuntu20.04 from Microsoft Store.
②Launch the app.
③App display below.

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 ?????????????

Press any key to continue...

### Expected Behavior

WslRegisterDistribution successed.

### Actual Behavior

WslRegisterDistribution failed with error: 0x80070005

**Comment by owenschupp** [comment]
This is a HRESULT error from Windows. I believe 0x80070005 corresponds to ACCESS_DENIED. Could you try relaunching the Ubuntu 20.04 application as an administrator? Or opening WSL from an elevated powershell?

**Comment by luis-torrescisneros-tfs** [comment]
Hi everyone, I am also getting this issue. I ran "wsl --install -d Ubuntu-18.04" as admistrator in command promt and suddenly pops the error 0x80070005 up. Does anyone know what is this for?

**Comment by Mildred34** [comment]
Hi everyone,

Got the same issue, I launched "wsl --install -d Ubuntu-18.04" as admistrator in powershell when trying to install Ubuntu 22.04.

When I tried to install Ubuntu 20.04, I got another error:  Code d’erreur : 0x8000ffff 
[WslLogs-2023-01-30_15-03-36.zip](https://github.com/microsoft/WSL/files/10536658/WslLogs-2023-01-30_15-03-36.zip)

Don't know, if there be anything interesting in that log.
