### ISSUE TITLE
vscode not available after logging out and logging back in

### ISSUE THREAD

**Issue by plastikfan** [microsoft/WSL#8029]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Windows 10 bootcamp
Remote WSL: v0.64.2
Version: 1.64.0 (system setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

### Repro Steps

- Reboot system
- Log back in
- open WSL in terminal
- run "which code"
this shows that vsocde is available at path: "/mnt/c/Program Files/Microsoft VS Code/bin/code"
- Log out
- Log back in
- open WSL in terminal
- run "which code"
now vscode is no longer available: "code not found"

From here, you can restart the whole process, and the same will happen. So effectively, if you log out of windows something is happening to the WSL environment to prevent vscode from launching.

### Expected Behavior

Logging out and logging back in should not have an effect on wether applications will launch from WSL or not and not require a reboot to restore order.

Also, I am using zsh/oh-my-zsh, neither of which appear to be modifying the path.

### Actual Behavior

The path variable in ubuntu does not appear to be affected by logging out/rebooting. The path on my system contains the following (and remains the same regardless of logging out/logging back in):

(Also, to be clear, this is the value of the path variable inside linux, ie echo $path)
```
/home/plastikfan/.nvm/versions/node/v14.18.1/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/usr/lib/wsl/lib
/mnt/c/Program Files/ImageMagick-7.1.0-Q16-HDRI
/mnt/c/Program Files (x86)/Intel/iCLS Client/
/mnt/c/Program Files/Intel/iCLS Client/
/mnt/c/Windows/system32
/mnt/c/Windows
/mnt/c/Windows/System32/Wbem
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/
/mnt/c/Windows/System32/OpenSSH/
/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL
/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL
/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT
/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT
/mnt/c/Program Files/Microsoft VS Code/bin
/mnt/c/Program Files/Git/cmd
/mnt/c/Program Files/PowerShell/7/
/mnt/c/Users/Plastikfan/AppData/Local/Microsoft/WindowsApps
```

**Comment by owenschupp** [comment]
When you are referring to "logging out/in" do you mean as your default user in your Linux distro or do you mean logging in/out of Windows?

**Comment by plastikfan** [comment]
Sorry, for now being explicit about that. When I mean logout, I mean logout of windows entirely, not just the linux distro. Similarly when I say reboot, I mean reboot windows not just restart the linux session.

**Comment by owenschupp** [comment]
@plastikfan thanks for your response. I forgot to ask, but do you have the WSL Remote VSCode extension installed?

**Comment by plastikfan** [comment]
yes I do.
