### ISSUE TITLE
generateResolvConf = false did not work in wsl.conf

### ISSUE THREAD

**Issue by mikezerosix** [microsoft/WSL#8030]
### Version

Windows 10 Enterprise H20

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

OpenSuse15.3 and Ubuntu 20.4 

### Other Software

nada

### Repro Steps

Create file in linux : 

/etc/wsl.conf 

containing text 

```bash
[network]
generateResolvConf = false
```

### Expected Behavior

when you start the WSL with current distro the /etc/resolv.conf in no autogenerated and file is overwritten. 
Per the Micker Mouse WSL documentation. 

 

### Actual Behavior

/etc/resolv.conf is always overwritten. It does matter that you restart wsl or the wsl service or the whole computer. This setting has no effect no matter what you do. /etc/resolv.conf is ALWAYS auto generated and overwritten.

**Comment by mikezerosix** [comment]
No matter what you restart or what distro you use the setting is still not working in WSL 2.

**Comment by owenschupp** [comment]
@mikezerosix I've been investigating this issue, and I wanted to double-check and see something first. Do you and the others having this issue have the `resolvconf` package installed? Could you post the output of running `wsl --exec resolvconf`? Also, how are you making changes to the `/etc/resolv.conf` file?

**Comment by owenschupp** [comment]
@mikezerosix for a quick fix, try deleting `/etc/resolv.conf` and re-making it with your changes. If `generateResolvConf = false` those changes should persist after restarting WSL.

**Comment by owenschupp** [comment]
@mikezerosix has this resolved your issue?

**Comment by mikezerosix** [comment]
It is completely random and inconsistent. I made changed I restarted WSL service per documentation. Then I do nothing and few days later when I restart the whole machine and it takes effect. 

I copy working resolve.conf copy over the auto generated. I have wsl.conf per instructions and it does not seem to work. chattr -i /etc/resolv.conf after whole machine reboot seemd to work preventing the overwriting of manually edited file.

**Comment by owenschupp** [comment]
@mikezerosix this issue has been fixed in Store WSL, please update if you haven't done so. Thanks!

**Comment by nmofonseca** [comment]
hello  @owenschupp,

I don't believe this should be closed, I am facing this issue, when you say Store WSL what does this mean?

Unfortunately, I can't use the Windows store since it's blocked by my IT, to install WSL I needed to follow the manual instructions provided by Microsoft [here](https://docs.microsoft.com/en-us/windows/wsl/install-manual)

I am using Ubuntu  20.04.4 LTS  which was downloaded from the [link ](https://aka.ms/wslubuntu2004) available in the instructions mentioned.

**Comment by onomatopellan** [comment]
@nmofonseca Are you in Windows 11? Since you are blocked I think it's worth trying to install the store version manually. Download the latest `.msixbundle` file from https://github.com/microsoft/WSL/releases and install it from elevated Powershell like this:
```
Add-AppxPackage .\Microsoft.WSL_0.58.3.0_x64_ARM64.msixbundle
```

**Comment by nmofonseca** [comment]
> Add-AppxPackage .

Hello @onomatopellan ,

I believe this has sorted my issue, In have installed the latest release as you described, and this is the output I get now from --version:

```
wsl --version
WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.675
```

Then I removed the immutable flag from my /etc/resolv.conf and restarted wsl using wsl --shutdown and when my Ubuntu started again the /etc/resolv.conf is still there intact.

I will try a new distro also to  double-check this.

Cheers
