### ISSUE TITLE
dmsetup does not create entry in /dev/mapper [WSL2]

### ISSUE THREAD

**Issue by thymbahutymba** [microsoft/WSL#8033]
Hi all, I'm trying to create a logical device with dmsetup on WSL2 using the following commands `losetup -f` that returns the first loop device available (loop0); then I run the following command:
`sudo dmsetup create diskimage '0 10000 linear /dev/loop0 0'` that should create an entry on `/dev/mapper/` but it does not. However, I can seed the device running `sudo dmsetup ls`. What's missing? Why the entry is not create under /dev/mapper?

**Comment by owenschupp** [comment]
Hello! Please re-file this issue according [to our guide](https://github.com/microsoft/WSL/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.yaml) if you believe this is a WSL-related issue. Thanks!

**Comment by Torvin** [comment]
turns out it needed `sudo dmsetup mknodes`
