### ISSUE TITLE
Wrong home when using C:\WINDOWS\System32\bash.exe as DefaultShell for OpenSSH

### ISSUE THREAD

**Issue by shalak** [microsoft/WSL#8036]
### Version

Microsoft Windows [Version 10.0.18363.1500]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

OpenSSH

### Repro Steps

- Install OpenSSH via `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`
- start it up and enable via `Start-Service sshd` and `Set-Service -Name sshd -StartupType 'Automatic'`
- set `DefaultShell` for it via `New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\WINDOWS\System32\bash.exe" -PropertyType String -Force`

### Expected Behavior

After SSHing into this machine, I expect to be in `/home/username` directory, just like when I open Ubuntu from Menu Start

### Actual Behavior

After SSHing into this machine I'm in `/mnt/c/Users/Username` directory

**Comment by shalak** [comment]
When I was using WSL1, the issue did not occur (I was observing the expected behavior)

**Comment by owenschupp** [comment]
@shalak  Could you provide context as to how WSL figures into this issue? Are you SSHing into another Windows machine from WSL? Also if you look at `man scp` you can see that if you can specify the target location for the copy on the remote machine, ex. `scp file.txt user@host1.com:/path/to/directory`

**Comment by shalak** [comment]
@owenschupp The `DefaultShell` of OpenSSH is set to `C:\WINDOWS\System32\bash.exe`, which I assume is under WSL (am I correct?)

Sure, I can set the path and it works, but I'd like to have the default dir to WSL home, not the OS one. Is this possible?
