### ISSUE TITLE
Destribution installation stucks

### ISSUE THREAD

**Issue by shyu216** [microsoft/WSL#8037]
### Version

Microsoft Windows [版本 10.0.22000.469]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

ubuntu

### Repro Steps

>wsl --install -d ubuntu

### Expected Behavior

Ubuntu installation finishs.

### Actual Behavior

After I execute 
` wsl --install -d ubuntu `
and it shows ubuntu window, then shows
`  Installing, this may take a few minutes...`, and then it stucks and in task manager, the usage of ubuntu terminal is alomost 0. Could you give me a hand? thanks a lot.

**Comment by shyu216** [comment]
I am fresh here, may I ask can I attach some screenshots here?

**Comment by shyu216** [comment]
Oh, it then shows an error that `Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370114
Error: 0x80370114 ??????????????????

Press any key to continue...`

**Comment by shyu216** [comment]
I have tried many times and only this time I have waited that long and get this error, problem solved then. Same problem as https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74[https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74](https://answers.microsoft.com/en-us/insider/forum/all/wsl-2-installing-linux-failed-error-code/bae391d1-4215-4d93-b0c4-3d96404a7c74)

**Comment by nacayu** [comment]
@shyu216 hello, I have met the same question, and your link is not valid.
