### ISSUE TITLE
Installing Kali via PowerShell installs an outdated version.

### ISSUE THREAD

**Issue by kjkent** [microsoft/WSL#8044]
### Version

Microsoft Windows [Version 10.0.22000.493]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

2019.2 / 2021.4 / 2022.1

### Repro Steps

`wsl --install -d kali-linux`

### Expected Behavior

WSL installs the latest (or a recent) Kali build (Currently 2021.4 if installed via the Microsoft Store).

### Actual Behavior

WSL installs Kali build 2019.2 when installed through PowerShell.

This build is not updatable as `apt` / `apt-get` throws an error due to expired key signatures. A workaround exists, but attempting to update this build then throws another error that breaks the OS (or at least `sudo` / `su` functionality as far as I've tested, but Google shows other folks have encountered deeper issues).

**Comment by sirredbeard** [comment]
The WSL distro images downloaded by `wsl --install...` are hosted by Microsoft and have to be manually updated. They can get a little behind. The Kali team will need to provide an updated .appx to Microsoft and Microsoft will need to update it on their side.
