### ISSUE TITLE
Unable to start Ubuntu app normally, showing file system error

### ISSUE THREAD

**Issue by kouxichao** [microsoft/WSL#8062]
### Version

Microsoft Windows [Version 10.0.19044.1526]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Enter _wsl --install -d Ubuntu-20.04_ in powershell, it shows that the installation is successful, it is starting, 
![image](https://user-images.githubusercontent.com/18493402/154491409-f84a84ec-ade7-42e7-b2eb-c5285f895749.png)

then an error prompt box pops up (as shown in Actual Behavior)，when I try to launch Ubuntu from the start menu, the error will also appear.

### Expected Behavior

Ubuntu started successfully

### Actual Behavior

![image](https://user-images.githubusercontent.com/18493402/154490206-4dbb55b8-c3c9-40de-8d7a-482bc20253cd.png)

**Comment by owenschupp** [comment]
@kouxichao what does the error say?
