### ISSUE TITLE
Importing OS with WSL dont work on windows 11 in trying to install ubuntu server and any of import work on any os made for wsl

### ISSUE THREAD

**Issue by ExodusEngineering** [microsoft/WSL#8063]
### Version

Wsl —version dont work nothing working

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Wsl —status dont work

### Distro Version

Ubuntu server (any)

### Other Software

Cant install ubutun server with import. Nothing is working

### Repro Steps

Cant import new distro

50% of cmd from wsl.exe dont work on windows 11

— status dont work
— version dont work
— import dont work

When i try it it do —help on wsl

### Expected Behavior

I dont know almost everything not working on windows 11

### Actual Behavior

Import dont work it do —help after each try

**Comment by owenschupp** [comment]
@ExodusEngineering did you install WSL from the Windows Store since you are using Windows 11? I would suggest trying to re-install WSL and see if your problem persists.
