### ISSUE TITLE
pdfgrep on PowerShell :: file name not shown

### ISSUE THREAD

**Issue by francesco1119** [microsoft/WSL#8066]
### Version

Microsoft Windows [Version 10.0.19043.1466]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

PowerShell: 
Major: 5
Minor: 1
Build: 19041
Revision: 1320

### Repro Steps

1. `apt-get install pdfgrep `
2. `pdfgrep -HinR 'DSINDIP' DatenModel/`

### Expected Behavior

In WSL2 on Terminal you see the file name: 

![image](https://user-images.githubusercontent.com/3397477/154648853-d24437a6-3e9f-43af-8f5b-f69ba88a1bed.png)

### Actual Behavior

In WSL2 on PowerShell you don't see the file name: 

![image](https://user-images.githubusercontent.com/3397477/154648903-483330bd-787f-45ce-8c39-4cf53b0e5703.png)

**Comment by owenschupp** [comment]
@francesco1119 thank you for filing this issue, but I believe this is not a WSL-related issue. It appears that the behavior is due to how the output is displayed on Powershell. I would recommend filing this issue there:

https://github.com/PowerShell/PowerShell/issues
