### ISSUE TITLE
"Access is denied" when opening wsl.exe from a SSH connection to windows host.

### ISSUE THREAD

**Issue by leoleoasd** [microsoft/WSL#8072]
### Version

Microsoft Windows [版本 10.0.22000.493]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.93.2

### Distro Version

Archlinux

### Repro Steps

Setup openssh-server on windows, ssh into windows, and open "wsl.exe".

### Expected Behavior

opens wsl

### Actual Behavior

Access is denied

**Comment by DanPinGF** [comment]
Can you try explaining the issue more in detail? The explanation appears to be too small.

**Comment by leoleoasd** [comment]
> Can you try explaining the issue more in detail? The explanation appears to be too small.

I can't open wsl.exe from an SSH connection from remote to windows host. 
The ssh server is installed using `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`.

**Comment by owenschupp** [comment]
@leoleoasd when ssh'd into the Windows machine, is the output of running `whoami` in PowerShell is the same user that has WSL installed on the system? Also, just to avoid any confounding errors, did you follow the steps [here](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) for enabling OpenSSH on your Windows machine? There is some initial configuration that has to be done if not done already. Thanks!

**Comment by leoleoasd** [comment]
@owenschupp I followed those steps on the document, including setting up firewall, and I didn't change the sshd configuration file.
Local cmd output:
```
Microsoft Windows [版本 10.0.22000.493]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Leo>whoami
leo-pc\leo

C:\Users\Leo>wsl.exe
(win/x64)  ➜  /mnt/c/Users/Leo
```
SSH connection output:
```
Microsoft Windows [版本 10.0.22000.493]
(c) Microsoft Corporation。保留所有权利。

leo@LEO-PC C:\Users\Leo>whoami
leo-pc\leo

leo@LEO-PC C:\Users\Leo>wsl.exe
拒绝访问。 # Translates to Access is denied
```

**Comment by DanPinGF** [comment]
Do you have admin rights? Not running WSL as an administrator can cause this error.

**Comment by leoleoasd** [comment]
Yes, my account is the only account on this PC, and is created during a freash install of Windows 11.

**Comment by leoleoasd** [comment]
Yes, my account is the only account on this PC, and is created during a freash install of Windows 11.

**Comment by DanPinGF** [comment]
> Yes, my account is the only account on this PC, and is created during a freash install of Windows 11.

Hmm... then I would probably say you should run an elevated cmd.exe and start WSL there.

**Comment by leoleoasd** [comment]
My wsl VM is already started. Opening wsl.exe or bash.exe from regular, non-admin cmd or windows terminal works. But I want to access my WSL from a remote machine. Running another openssh server within wsl and port-forward seems too heavy since it would require running two openssh servers on the same machine.

**Comment by zguo235** [comment]
I have the same problem.  After connected to my remote windows host by ssh,  windows terminals showed I logged in as an administrator. I can also edit the administrators_authorized_keys file under c:\ProgramData\ssh. Starting wsl failed as "Access is denied"
`PS C:\ProgramData\ssh> wsl
アクセスが拒否されました。# Translates to Access is denied
PS C:\ProgramData\ssh> wsl -l
アクセスが拒否されました。# Translates to Access is denied
`

**Comment by DanPinGF** [comment]
Maybe it could be firewall- or network-related?

**Comment by zguo235** [comment]
```
> Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP"

Name                          : OpenSSH-Server-In-TCP
DisplayName                   : OpenSSH SSH Server (sshd)
Description                   : Inbound rule for OpenSSH SSH Server (sshd)
DisplayGroup                  : OpenSSH Server
Group                         : OpenSSH Server
Enabled                       : True
Profile                       : Any
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LooseSourceMapping            : False
LocalOnlyMapping              : False
Owner                         :
PrimaryStatus                 : OK
Status                        : 規則は、ストアから正常に解析されました。 (65536)
EnforcementStatus             : NotApplicable
PolicyStoreSource             : PersistentStore
PolicyStoreSourceType         : Local
RemoteDynamicKeywordAddresses : {}
```

**Comment by leoleoasd** [comment]
> @leoleoasd One idea I had for a workaround is that you could try using the `runas` command in cmd.exe to try to run wsl.exe explicitly as an administrator.
> 
> https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc771525(v=ws.10)?redirectedfrom=MSDN

Tried `runas` as my own account, it doesn't work either. What do you mean by `as an administrator`? My account should be an administrator, and there are no other accounts on my machine.

> Maybe it could be firewall- or network-related?

How does `wsl.exe` open bash, is it connected to WSL over the network?

**Comment by zguo235** [comment]
`runas` didn't work in my environment, either.

**Comment by DanPinGF** [comment]
> runas didn't work in my environment, either.

Then maybe you should try enabling the built-in Administrator account to try to pinpoint the issue and see if that'll make a difference. You might need some piece of software like Winaero Tweaker to do that.

**Comment by zguo235** [comment]
```
administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>wsl
Access is denied.

administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>runas /user:administrator wsl
Enter the password for administrator:
Attempting to start wsl as user "DESKTOP-7D4OTO7\administrator" ...

administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>
```
Failed to start wsl even I logged in as administrator. `runas` also failed to start wsl. I checked the process explorer and found no wsl (ubuntu) process there.
Windows subsystem for linux preview and ubuntu 20.04 were installed from microsoft store

**Comment by leoleoasd** [comment]
@zguo235  maybe try run cmd with administrator, try `whoami`, then open wsl.exe?

**Comment by DanPinGF** [comment]
If it's still not working, perhaps try to reinstall WSL. A faulty installation maybe causing this error.

**Comment by zguo235** [comment]
```
administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>type nul >> C:\ProgramData\ssh\filt.txt

administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>whoami
desktop-7d4oto7\administrator

administrator@DESKTOP-7D4OTO7 C:\Users\Administrator>wsl
Access is denied.
```
`type nul >> C:\ProgramData\ssh\filt.txt` failed without admin rights.
```
PS C:\ProgramData\ssh> type nul >> C:\ProgramData\ssh\filt.txt
Out-File: Access to the path 'C:\ProgramData\ssh\filt.txt' is denied.
```

**Comment by zguo235** [comment]
I installed the wsl and ubuntu 20.02 after I activate the administrator account today. I also checked i can use them after the installation.

**Comment by zguo235** [comment]
This is what I did to start the wsl in a ssh connection.
1. Change my account from administration to standard user.
2. SSH to my windows host and type `wsl` in the shell.
3. An instruction appeared and told me I have to update my kernel component. Follow here: https://aka.ms/wsl2kernel 
4. Update and start my wsl.
```
C:\Users\zguo>wsl
WSL 2 を実行するには、カーネル コンポーネントの更新が必要です。詳細については https://aka.ms/wsl2kernel を参照してください #Update the kernel component.

 C:\Users\zguo>wsl

16:43 /mnt/c/Users/zguo $
```

**Comment by DanPinGF** [comment]
Don't use the built-in administrator account. I'm finding that running WSL there causes the 'access denied' error.

**Comment by demfabris** [comment]
> This is what I did to start the wsl in a ssh connection.
> 
> 1. Change my account from administration to standard user.
> 2. SSH to my windows host and type `wsl` in the shell.
> 3. An instruction appeared and told me I have to update my kernel component. Follow here: https://aka.ms/wsl2kernel
> 4. Update and start my wsl.
> 
> ```
> C:\Users\zguo>wsl
> WSL 2 を実行するには、カーネル コンポーネントの更新が必要です。詳細については https://aka.ms/wsl2kernel を参照してください #Update the kernel component.
> 
>  C:\Users\zguo>wsl
> 
> 16:43 /mnt/c/Users/zguo $
> ```

Followed your instructions but any attempt to execute `wsl` just returns the `--help` output

**Comment by zguo235** [comment]
This has never happened to me. There is another issue talking about wsl.exe failed with "Access is denied" #4920 . Maybe that is helpful.

**Comment by DanPinGF** [comment]
> This has never happened to me. There is another issue talking about wsl.exe failed with "Access is denied" #4920 . Maybe that is helpful.

@OneBlue - I agree; this is obviously a duplicate of said issue.

**Comment by leoleoasd** [comment]
I think this is a different issue. The difference is that I can access my WSL from my windows PC. I just can't access it from a remote PC. To fix this, I think we need to allow sshd to access some resources that `wsl.exe` needs.
Another reason why I need to open `wsl.exe` from ssh connection is that I need to open EXEs from WSL, and I can't open EXE from an ssh connection to WSL sshd.

**Comment by whschultz** [comment]
This appears to be a known issue:

https://docs.microsoft.com/en-us/windows/wsl/store-release-notes

**Comment by andremacola** [comment]
The only way I could connect is getting the wsl ip running ´ hostname -I ´ inside wsl 

Connect to windows openSSH server with ´ssh myuser@windows-lanip´ and  then ´ssh mywsluser@wsl-ip´

**Comment by mattieb** [comment]
> This appears to be a known issue:
> 
> https://docs.microsoft.com/en-us/windows/wsl/store-release-notes

Can you point out where in the release notes this is? I can't find it.

**Comment by neersighted** [comment]
> > This appears to be a known issue:
> > https://docs.microsoft.com/en-us/windows/wsl/store-release-notes
> 
> Can you point out where in the release notes this is? I can't find it.

At the top:

> * Launching Windows Subsystem for Linux from session zero does not currently work (for example from an ssh connection).

**Comment by ddddavid-he** [comment]
I encountered the same problem after I updated to 22H2 and 5.15 kernel of wsl2

**Comment by Acceyuriko** [comment]
Today wsl reminded me that I can upgrade it to a new version, but after I upgraded it I can't open wsl in the ssh connection.
So I found this answer [Cannot run WSL2 over ssh](https://superuser.com/questions/1714736/cannot-run-wsl2-over-ssh-on-windows-11/1714740#1714740).

I found that there was an app in my app list called "Windows Subsystem For Linux Preview" that I just installed today. After uninstalling this app, everything went back to normal.

```
Start Menu -> Settings -> Apps

Find and uninstall Windows Subsystem For Linux Preview.
```

Hope it could help everyone

**Comment by ddddavid-he** [comment]
> Today wsl reminded me that I can upgrade it to a new version, but after I upgraded it I can't open wsl in the ssh connection. So I found this answer [Cannot run WSL2 over ssh](https://superuser.com/questions/1714736/cannot-run-wsl2-over-ssh-on-windows-11/1714740#1714740).
> 
> I found that there was an app in my app list called "Windows Subsystem For Linux Preview" that I just installed today. After uninstalling this app, everything went back to normal.
> 
> ```
> Start Menu -> Settings -> Apps
> 
> Find and uninstall Windows Subsystem For Linux Preview.
> ```
> 
> Hope it could help everyone

This do work in a way, but it will revert the wsl kernel version back to 5.10.

Thanks anyway.

**Comment by psztoch** [comment]
If you have WSL "Access is denied" problem, at first check where have you your WSL installed.
If you use WSL from Microsoft Store (it is good choice, because you have got fresh and current version) then WSL is installed in C:\Program Files\WindowsApps\ folder. And this folder has very limited access. Local administrators can't access this folder.
I took over ownership of files in this directory to LOCAL-DOMAIN\Administrators. Then it was possible to add Read/Execute rights to LOCAL-DOMAIN\Administrators. After it WSL start working via SSH or other remote access.

**Comment by MichaelHipp** [comment]
> If you have WSL "Access is denied" problem, at first check where have you your WSL installed. If you use WSL from Microsoft Store (it is good choice, because you have got fresh and current version) then WSL is installed in C:\Program Files\WindowsApps\ folder. And this folder has very limited access. Local administrators can't access this folder. I took over ownership of files in this directory to LOCAL-DOMAIN\Administrators. Then it was possible to add Read/Execute rights to LOCAL-DOMAIN\Administrators. After it WSL start working via SSH or other remote access.

I have this problem. There is folder such as C:\Program Files\WindowsApps\. Where else should I look? This is a fresh Win11 install.

**Comment by guocheng2018** [comment]
@MichaelHipp C:\Program Files\WindowsApps is a hidden folder, you need to enable "show hidden items" in File Explorer.

**Comment by DanPinGF** [comment]
> @MichaelHipp C:\Program Files\WindowsApps is a hidden folder, you need to enable "show hidden items" in File Explorer.

Actually, the problem with trying to open the WindowsApps folder is that it is completely protected from being accessed. If you try to open it in File Explorer, you'll get a warning that you don't have permission to access the folder, and clicking 'Continue' does not do anything, instead telling you to change its security properties first.

![image](https://user-images.githubusercontent.com/28827920/219900038-a31d7ffe-fc02-4d5d-b65b-bc471c379789.png)

**Comment by ZhangTianrong** [comment]
> If you have WSL "Access is denied" problem, at first check where have you your WSL installed. If you use WSL from Microsoft Store (it is good choice, because you have got fresh and current version) then WSL is installed in C:\Program Files\WindowsApps\ folder. And this folder has very limited access. Local administrators can't access this folder. I took over ownership of files in this directory to LOCAL-DOMAIN\Administrators. Then it was possible to add Read/Execute rights to LOCAL-DOMAIN\Administrators. After it WSL start working via SSH or other remote access.

Can you clarify more on which folder to take ownership of and what permission to be added? Is it the `WindowsApp` folder itself whose owner was initially `NT Service\TrustedInstaller` or the folder for the WSL whose original owner is `SYSTEM`? Did you encounter errors saying that it cannot list children of some subfolders when updating the permissions? Am I supposed to add  only `Read/Execute` permission to `<hostname>\Administrator` to get `wsl` accessible in an SSH session? I have read some others' replies saying that you can just allow `every` to have complete control over everything in this folder. I guess it'll work but I would rather not completely ruin the permissions.

**Comment by matchaxnb** [comment]
Extremely dirty solution here, but one that works:

- Get permissions for C:\Program FIles\WindowsApps
- Enter C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*
- Take ownership of that directory and grant your user access to it (recursively). Then give back ownership to System
- Now you can call C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__xxxx\wsl.exe directly
- Relinquish the permissions you granted yourself.
- Should work.

**Comment by ZhangTianrong** [comment]
> Extremely dirty solution here, but one that works:
> 
> * Get permissions for C:\Program FIles\WindowsApps
> * Enter C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*
> * Take ownership of that directory and grant your user access to it (recursively). Then give back ownership to System
> * Now you can call C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__xxxx\wsl.exe directly
> * Relinquish the permissions you granted yourself.
> * Should work.

I tried your solution and indeed this enables accessing `wsl` from an SSH session, but only if the instance is already running or if it is a `wsl1` instance. When the system has just started and nobody has logged on through the graphical interface, calling `wsl` from an SSH session to open a `wsl2` instance results in the following error
```
{Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
```
Do you also encounter such errors? If so, do you have a fix for it?

**Comment by lordscales91** [comment]
> > Extremely dirty solution here, but one that works:
> > 
> > * Get permissions for C:\Program FIles\WindowsApps
> > * Enter C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*
> > * Take ownership of that directory and grant your user access to it (recursively). Then give back ownership to System
> > * Now you can call C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__xxxx\wsl.exe directly
> > * Relinquish the permissions you granted yourself.
> > * Should work.
> 
> I tried your solution and indeed this enables accessing `wsl` from an SSH session, but only if the instance is already running or if it is a `wsl1` instance. When the system has just started and nobody has logged on through the graphical interface, calling `wsl` from an SSH session to open a `wsl2` instance results in the following error
> 
> ```
> {Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> ```
> 
> Do you also encounter such errors? If so, do you have a fix for it?

I have a workaround to be able to fire up the WSL from the SSH session, so then you can run the wsl.exe directly. I created a scheduled task that runs a command on my target distro, I just used an echo. Then, I just fire up that task, prior to executing the wsl.exe.

You can create the task like this:
1. In the general tab just give it some meaningful name, I just named it StartUbuntu
2. In actions add a new action that starts a program, the program will be `%windir%\System32\cmd.exe` and for the arguments just type `/c wsl -d Ubuntu -- echo "WSL Started"` (change Ubuntu by your target distro).

Now, from your SSH session you can run this task with `schtasks /run /tn StartUbuntu`.
Right after running that command run the wsl.exe directly like @matchaxnb says and you should be able to get in. It seems like there's only a small time window because after running the command the VM is automatically shutdown, so you need to be quick.

I hope it helps.

**Comment by ZhangTianrong** [comment]
> > > Extremely dirty solution here, but one that works:
> > > 
> > > * Get permissions for C:\Program FIles\WindowsApps
> > > * Enter C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*
> > > * Take ownership of that directory and grant your user access to it (recursively). Then give back ownership to System
> > > * Now you can call C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__xxxx\wsl.exe directly
> > > * Relinquish the permissions you granted yourself.
> > > * Should work.
> > 
> > 
> > I tried your solution and indeed this enables accessing `wsl` from an SSH session, but only if the instance is already running or if it is a `wsl1` instance. When the system has just started and nobody has logged on through the graphical interface, calling `wsl` from an SSH session to open a `wsl2` instance results in the following error
> > ```
> > {Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you also encounter such errors? If so, do you have a fix for it?
> 
> I have a workaround to be able to fire up the WSL from the SSH session, so then you can run the wsl.exe directly. I created a scheduled task that runs a command on my target distro, I just used an echo. Then, I just fire up that task, prior to executing the wsl.exe.
> 
> You can create the task like this:
> 
> 1. In the general tab just give it some meaningful name, I just named it StartUbuntu
> 2. In actions add a new action that starts a program, the program will be `%windir%\System32\cmd.exe` and for the arguments just type `/c wsl -d Ubuntu -- echo "WSL Started"` (change Ubuntu by your target distro).
> 
> Now, from your SSH session you can run this task with `schtasks /run /tn StartUbuntu`. Right after running that command run the wsl.exe directly like @matchaxnb says and you should be able to get in. It seems like there's only a small time window because after running the command the VM is automatically shutdown, so you need to be quick.
> 
> I hope it helps.

Thanks for the workaround, but that is not an option for me, because for your task to correctly run `wsl`, you will need to configure it to start only when a user has logged on (using a graphical interface), as otherwise it encounters the exact same error I posted (correct me if I am wrong). However, when a machine is restarted in a completely unattended way, you cannot expect someone to promptly log on either physically or through RDP.

As to the short time window issue, you can replace the echo with some other commands that runs in the background, e.g. `keyring`, `sshd` (works only if you configured your WSL2 to not use `systemd`) and then you can prevent it from shutting down itself.

**Comment by lordscales91** [comment]
> Thanks for the workaround, but that is not an option for me, because for your task to correctly run `wsl`, you will need to configure it to start only when a user has logged on (using a graphical interface), as otherwise it encounters the exact same error I posted (correct me if I am wrong). However, when a machine is restarted in a completely unattended way, you cannot expect someone to promptly log on either physically or through RDP.

I just used this to access my personal computer when I'm out. It's running Windows 10 and probably thanks to the fast boot setting, it automatically initializes a session with my account while it's still on the lock screen, I still have to login with my password or image password to access the desktop, but the session is already initialized before that.

**Comment by ZhangTianrong** [comment]
> I just used this to access my personal computer when I'm out. It's running Windows 10 and probably thanks to the fast boot setting, it automatically initializes a session with my account while it's still on the lock screen, I still have to login with my password or image password to access the desktop, but the session is already initialized before that.

I just tried. This does seem to make a difference. This is what I do:
1. Restart the target machine
2. Login through ssh
3. Run the task
4. Run wsl -d <distro_name>

It's still not launching but the error I got is different:
```
The server process could not be started because the configured identity is incorrect. Check the username and password.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8000401a
```

Just to be clear, the task doesn't need to be configure to run even when no user has logged on or to run with highest privilege, right?

**Comment by lordscales91** [comment]
> I just tried. This does seem to make a difference. This is what I do:
> 
>     1. Restart the target machine
> 
>     2. Login through ssh
> 
>     3. Run the task
> 
>     4. Run wsl -d <distro_name>

The problem is step 4, you don't launch the normal wsl, you launch directly the wsl.exe located at: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*xxxx*\wsl.exe but before that you need to take over that folder and give your user permissions like matchaxnb says



> * Get permissions for C:\Program FIles\WindowsApps
> 
> * Enter C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__*
> 
> * Take ownership of that directory and grant your user access to it (recursively). Then give back ownership to System
> 
> * Now you can call C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.1.6.0_x64__xxxx\wsl.exe directly
> 
> * Relinquish the permissions you granted yourself.
> 
> * Should work.

The only difference is that I didn't relinquish my permissions, only gave the ownership of that folder back to System. Also, to avoid having to write the full path every time, I created a bat file named wsl_trick.bat like this:

```
"C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wsl.exe" %* 
```
I added the bat file to the path, so I can type just `wsl_trick -d <distro name>`

As for the scheduled task itself, I have configured it to run only when the user has logged in, the user being my own user. It doesn't run with highest privileges.

I hope it helps. But ideally Microsoft should fix this issue.

**Comment by jjlorenzo** [comment]
I didn't like messing with WindowsApps permissions, so what I did was a copy of the "MicrosoftCorporationII.WindowsSubsystemForLinux.." folder to another location and run that wsl copy.

**Comment by mobluse** [comment]
I also have this problem that wsl.exe cannot be accessed by the system when I login using the OpenSSH Server from Microsoft. I have Swedish Windows 10.
```
Microsoft Windows [Version 10.0.19045.3086]
(c) Microsoft Corporation. Med ensamrätt.

pi@IDEAPAD100 C:\Users\pi>wsl
Systemet kan inte komma åt filen.

pi@IDEAPAD100 C:\Users\pi>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\pi> wsl.exe
Systemet kan inte komma åt filen.
```
This used to work before. It must be some update that changed permissions.

**Comment by RGD2** [comment]
I hit this issue trying to connect to a WSL2 which was running a jupyterlab server on 127.0.0.1:8888 on the windows host.
My workaround was to establish the ssh connection with the option `-L 8888:127.0.0.1:8888` .
(This can be added at any time on an active ssh session with `enter`, `shift-~C` used to get an `ssh>` command line).
Of course, you still need to remote desktop into the server to get the jupyter lab link with the 127.0.0.1 address and token attached, which you put into your local web browser on the ssh client side whilst the ssh connection exists, but once you have that, you can close the remote desktop connection down.

You may be better off just using the start-task trick, and running a openssh server within the WSL, disabling the windows OpenSSH server, and connecting directly to that - perhaps having wsl2 start on boot?

If you can't, you could try putting the wsl openssh server on an alternate port (E.G. as jupyterlab is serving https on 8888 above), and then try using the above ssh port forwarding to connect a secondary ssh session to the forwarded port.  E.G.  `ssh wsluser@localhost:8888`

Then, you're already running your long-running tasks in WSL2 using tmux, right? Once you're in, you can reconnect to that tmux session, and you're good to go.

**Comment by nelsonaloysio** [comment]
I have an SSH server running on both Windows and WSL (v1). Managed to connect by setting up my client `~/.ssh/config`:

```
Host windows
  HostName windows.local
  IdentityFile ~/.ssh/windows.rsa
  User windows-user

Host wsl
  HostName localhost
  IdentityFile ~/ssh/wsl.rsa
  ProxyJump windows
  User wsl-user
```

After that, it's business as usual - I can just `ssh wsl` and I'm dropped on my WSL's zsh shell. Thanks go to @andremacola.

On a sidenote, I also had to follow [this instructions](https://stackoverflow.com/a/50502015) in order to allow authenticating with a pubkey instead of a password.

**Comment by paperdave** [comment]
my workaround is to simply call `C:\Program Files\WSL\wsl.exe` instead of whatever is in path. I don't know if this binary path is universal but it works on the machines i am testing with. it is so confusing that there is more than one wsl.exe binary and some have permission issues that prevent administrators from accessing them.

**Comment by RaulSofia** [comment]
@paperdave thank you so much, been having the same exact problem and this solved the issue, no need for dirty workarounds and I don't mind typing the full path

**Comment by jesse-savary** [comment]
> my workaround is to simply call `C:\Program Files\WSL\wsl.exe` instead of whatever is in path. I don't know if this binary path is universal but it works on the machines i am testing with. it is so confusing that there is more than one wsl.exe binary and some have permission issues that prevent administrators from accessing them.

For anyone needing the command to configure Windows' SSH server to use the correct path:
`New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Program Files\WSL\wsl.exe" -PropertyType String -Force`

Thank you @paperdave for closing the loop for me on [this tutorial](https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine) which was written ~5 years ago.

**Comment by paperdave** [comment]
Was this issue actually fixed, or was it closed because a workaround exists? I still observe `wsl` on it's own to have issues in ssh without the workaround.

<img width="486" alt="image" src="https://github.com/microsoft/WSL/assets/24465214/f124d2bb-18e6-4cf1-a82e-9b012ad8d4ac">

Other people are going to run into this, and be confused.

**Comment by pedrohgmacedo** [comment]
> > my workaround is to simply call `C:\Program Files\WSL\wsl.exe` instead of whatever is in path. I don't know if this binary path is universal but it works on the machines i am testing with. it is so confusing that there is more than one wsl.exe binary and some have permission issues that prevent administrators from accessing them.
> 
> 
> 
> For anyone needing the command to configure Windows' SSH server to use the correct path:
> 
> `New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Program Files\WSL\wsl.exe" -PropertyType String -Force`
> 
> 
> 
> Thank you @paperdave for closing the loop for me on [this tutorial](https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine) which was written ~5 years ago.

Unfortunately, using the windows ssh server means using the windows console infrastructure, which makes any terminal output 100x slower.
