### ISSUE TITLE
hfsplus file system support for Ubuntu 20.04

### ISSUE THREAD

**Issue by ElrohirGT** [microsoft/WSL#8073]
I'm sorry if this isn't the right place to post this. I tried searching for duplicates and couldn't find any, closed or open.

**Is your feature request related to a problem? Please describe.**
I've been developing an avalonia app and wanted to compile and ship it to mac from my windows computer. I managed to compile it in windows targetting mac using wsl, and it works wonderfully, but when I try to create the .dmg it doesn't work because the kernel doesn't support HFS+. As you can see from the command  cat /proc/filesystems:
nodev   sysfs
nodev   tmpfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   cgroup2
nodev   cpuset
nodev   devtmpfs
nodev   binfmt_misc
nodev   debugfs
nodev   tracefs
nodev   sockfs
nodev   bpf
nodev   pipefs
nodev   ramfs
nodev   hugetlbfs
nodev   rpc_pipefs
nodev   devpts
        ext3
        ext2
        ext4
        squashfs
        vfat
        msdos
        iso9660
nodev   nfs
nodev   nfs4
nodev   nfsd
nodev   cifs
nodev   smb3
nodev   autofs
        fuseblk
nodev   fuse
nodev   fusectl
nodev   virtiofs
nodev   overlay
        udf
        xfs
nodev   9p
nodev   ceph
nodev   mqueue
        btrfs

**Describe the solution you'd like**
I would like the kernel to support the HFS+ filesystem.

**Describe alternatives you've considered**
I've tried a lot of tutorials online, but all of them just asked to use hfsplus, hfsutils, and hfssprogs, none of them work. Finally I've reached this [reddit thread](https://www.reddit.com/r/raspberry_pi/comments/3h9zdy/mount_says_unknown_filesystem_type_hfsplus_but/). They recommend to talk to the distributors, so I decided to come and talk.

I've tried Ubuntu 20.04 and the Debian distros, they don't support HFS+, maybe the other support it? Haven't checked with them.

**Additional context**
Adding this would help .net core developers compile their application to macos from within windows. The change from windows to macos just to compile won't be needed anymore. At least if your creating a .dmg.

**Comment by sirredbeard** [comment]
You could rebuild the Microsoft WSL2 kernel with HFS+ support.

You could [follow the steps outlined here](https://boxofcables.dev/kvm-optimized-custom-kernel-wsl2-2022/) for building a custom WSL 2 kernel, but skip the KVM optimizations and instead enable HFS+ in `make menuconfig`: 
![image](https://user-images.githubusercontent.com/33820650/155187876-491afee8-322a-4363-b57b-81c878cc1a90.png)

or apply the setting directly to your `.config` with:
`sed -i 's/# CONFIG_HFSPLUS_FS is not set/CONFIG_HFSPLUS_FS=y/g' .config`

Note that the HFS+ Linux kernel driver does not support HFS+ journaled, mounting is possible but could result in data loss.

To lend a hand, I went ahead and built you a kernel from the current release with no other changes but HFS+ enabled:

[bzImage.zip](https://github.com/microsoft/WSL/files/8119012/bzImage.zip)

Unzip, then it somewhere readable in your Windows file system and add:

```
[wsl2]
kernel=C:\\path\\to\\bzImage
```

Give that a try.

**Comment by ElrohirGT** [comment]
Thank you! I'll test it out later today and tell you how it goes.

**Comment by ElrohirGT** [comment]
Thank you! You really helped a man here, you really didn't need to go through the trouble of compiling it yourself but did anyways, I'm using your kernel and it appears to support hfsplus using the cat /proc/filesystems command.

Thank you!
