### ISSUE TITLE
Password is required when connecting to wsl

### ISSUE THREAD

**Issue by Freddd13** [microsoft/WSL#8078]
### Version

Microsoft Windows [版本 10.0.22000.493]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 18.04

### Repro Steps

Use windows terminal or vscode terminal to connect to wsl.

### Expected Behavior

Everytime I connected to wsl, I was asked a password. 

### Actual Behavior

When using muliple terminals, it's really inconvenient. Is this normal? If not, how can I disable this?

**Comment by owenschupp** [comment]
@Freddd13 can you post a sample of the output you get while trying to connect to WSL?

**Comment by Freddd13** [comment]
![terminal](https://user-images.githubusercontent.com/50367552/155438816-f631b8a1-9cab-4507-9a96-ca5c35615c2a.gif)

**Comment by Freddd13** [comment]
The output from vscode is the same as above.
I have the following settings in my windows terminal:

```json
            {
                "acrylicOpacity": 0.80000000000000004,
                "commandline": "C:/Program Files/PowerShell/7/pwsh.exe -nologo",
                "font": 
                {
                    "face": "MesloLGL Nerd Font",
                    "size": 11
                },
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "historySize": 9001,
                "name": "PowerShell",
                "padding": "15",
                "snapOnInput": true,
                "source": "Windows.Terminal.PowershellCore",
                "useAcrylic": true
            },
            {
                "guid": "{d1569d34-e3dc-506e-b3ef-3ca18387f714}",
                "name": "Ubuntu-CommPrev",
                "source": "Windows.Terminal.Wsl"
            }
        ]
    },
```

and in vscode:
```json
    "terminal.integrated.automationShell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
    "terminal.integrated.shellArgs.windows": [
        "-nologo"
    ],
```
---
I use powershell 7, maybe there's something related to that?

**Comment by owenschupp** [comment]
@Freddd13 do you have some sort of command in your `.bashrc` file (or any configuration to run a command when a bash shell or wsl starts) that would require `sudo`?

**Comment by Freddd13** [comment]
> @Freddd13 do you have some sort of command in your `.bashrc` file (or any configuration to run a command when a bash shell or wsl starts) that would require `sudo`?

Yes, I found a sudo command setting proxy IP. After uncommenting it, there's no password requirement anymore.
Thanks a lot!
