### ISSUE TITLE
Knowing about VDisk

### ISSUE THREAD

**Issue by missemily2022** [microsoft/WSL#8085]
My WSL Ubuntu VDisk Size is 256 GB 

If anybody can tell me from where is this 256 GB is allocated? 
I mean is it foma single partition of hard drive or small parts taken from many partitions that my PC has

**Comment by Biswa96** [comment]
Documentation https://docs.microsoft.com/en-us/windows/wsl/vhd-size

**Comment by elsaco** [comment]
256GB is the default virtual size. The actual size can be seen with `diskpart`. Here's sample reading for an Arch vdisk of about 2GB:

```
DISKPART> detail vdisk

Device type ID: 0 (Unknown)
Vendor ID: {00000000-0000-0000-0000-000000000000} (Unknown)
State: Added
Virtual size:  256 GB
Physical size: 2039 MB
Filename: C:\distros\Arch\ext4.vhdx
Is Child: No
Parent Filename:
Associated disk#: Not found.
```

`diskpart` can compact the vdisk also. As to where those disk extents are located, my guess it's up to the operating system.

**Comment by missemily2022** [comment]
Thanks
