### ISSUE TITLE
How to move the conda virtual environment of wsl2 to another Linux

### ISSUE THREAD

**Issue by YQisme** [microsoft/WSL#8088]
I want to run a demo of deep-learning in my Conda virtual environment, but I want to train the data on another Linux system with a high-performance GPU without setting extra config.

How can I do this?

Does conda-pack work here?

**Comment by OneBlue** [comment]
I don't have any deep knowledge of conda-pack, but looking at the documentation I can't think of any reason why it wouldn't work inside WSL.
