### ISSUE TITLE
Missing space character

### ISSUE THREAD

**Issue by Riffecx** [microsoft/WSL#8094]
### Version

Microsoft Windows [Version 10.0.22000.527]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

20.04

### Repro Steps

``wsl --update``

### Expected Behavior

After a successful update you will be asked to shutdown the WSL with ```wsl--shutdown``. There is just one space missing.  

### Actual Behavior

nothing ^^

**Comment by benhillis** [comment]
What locale of Windows are you using? Looks like a translation issue because the en-US is fine.

**Comment by Riffecx** [comment]
![image](https://user-images.githubusercontent.com/15014849/156363207-1066237c-3d14-4bb4-b848-0cc64f653f70.png)
![Shutdown-all-distro-and-restart-Windows-to-update-kernel](https://user-images.githubusercontent.com/15014849/156363782-38efbb25-3be1-48f0-998f-4d79dc20f874.jpg)
Hi. I use the German language pack. Unfortunately I can't attest to it with a picture until another update comes. I used the German language pack. You are right. In the English one this does not occur. But this is not really a problem, because you can see that something is missing. I just wanted to say it :)

The one picture shows that my WSL is up to date and therefore I can't show that and the other picture shows where the spacebar is missing. The second picture is from the Internet.

**Comment by Riffecx** [comment]
> What locale of Windows are you using? Looks like a translation issue because the en-US is fine.

I'm afraid I don't quite know what you mean. I use Windows in German language. I think what you want to know is .
``de_DE``

**Comment by Riffecx** [comment]
![image](https://user-images.githubusercontent.com/15014849/156364941-339afd64-b16c-416b-b952-eb7391610b2a.png)
I uninstalled and reinstalled my WSL once. Now I can show you this properly.

**Comment by Riffecx** [comment]
Hi @benhillis 

I don't think anything else will happen here.  Therefore I close the issue. Furthermore, it is not really a problem, because everyone understands where the spacebar is missing.

With kind regards
@Riffecx
