### ISSUE TITLE
ERROR:[2] Could not read registry key

### ISSUE THREAD

**Issue by dotsinspace** [microsoft/WSL#8099]
### Version

Windows version: 10.0.22557.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.93.2

### Distro Version

Arch Linux

### Other Software

WSL version: 0.51.3.0
Kernel version: 5.10.93.2
WSLg version: 1.0.30
Windows version: 10.0.22557.1

### Repro Steps

Error is thrown on opening distro terminal. with no error trace.

### Expected Behavior

Error shouldn't be thrown.

### Actual Behavior

ERROR:[2] Could not read registry key

**Comment by owenschupp** [comment]
@dotsinspace This is interesting behavior. Are you trying to mount any drives in WSL?

/logs

**Comment by dotsinspace** [comment]
> @dotsinspace This is interesting behavior. Are you trying to mount any drives in WSL?
> 
> /logs

No...it is already mounted...this error is always thrown when I open wsl terminal in this case arch terminal
