### ISSUE TITLE
vmstat Error: /proc must be mounted

### ISSUE THREAD

**Issue by kdefombelle** [microsoft/WSL#8104]
- `C:\Windows>cmd.exe --version`

> Microsoft Windows [Version 10.0.19043.1466] (c) Microsoft Corporation. All rights reserved.

- `cat /proc/version`

> Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1237-Microsoft Sat Sep 11 14:32:00 PST 2021

- `vmstat 1`

> procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
>  r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
> Error: /proc must be mounted
>   To mount /proc at boot you need an /etc/fstab line like:
>       proc   /proc   proc    defaults
>   In the meantime, run "mount proc /proc -t proc"

- `strace -ff vmstat`

> openat(AT_FDCWD, "/proc/vmstat", O_RDONLY) = -1 ENOENT (No such file or directory)`

Looks like [#1071](https://github.com/Microsoft/WSL/issues/1071),  [#3159](https://github.com/Microsoft/WSL/issues/3159)  or [#3673](https://github.com/microsoft/WSL/issues/3673) closed in (much) older windows 10 versions but sill having the issue in 10.0.19043.1466

**Comment by elsaco** [comment]
@kdefombelle unless you made changes, the WSL kernel has `CONFIG_PROC_FS=y`  and mounts `procfs` automatically. What is the output of `findmnt` before you manually mount `procfs`? Thx!

**Comment by elsaco** [comment]
Even with kernel 4.4.0 `procfs` must be already enabled in the kernel, otherwise @kdefombelle wouldn't be able to mount it manually. I'm surprised the mounting doesn't happen automatically at boot time and requires user intervention.

**Comment by kdefombelle** [comment]
**issue solved, thanks a million**

- `wsl --list -v` indeed was the root cause

> NAME                   STATE           VERSION
> * Ubuntu                 Running         1

- `vmstat 1` once moved to WSL2.

> procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
>  r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
>  1  0      0 10155696 151744 2011316    0    0    67  1335   39  115  1  1 98  0  0
>  0  0      0 10155696 151744 2011316    0    0     0     0    7   50  0  0 100  0  0

PS: I did not mount /proc, it was mounted by default

- `findmnt | grep -i proc`

> ├─/proc                                                                                                                                                         proc                            proc        rw,nosuid,nodev,noexec,noatime
> │ └─/proc/sys/fs/binfmt_misc                                                                                                                                    binfmt_misc                     binfmt_misc rw,relatime
>
