### ISSUE TITLE
After upgrade to windows 11 terminal no longer opens at startingDirectory

### ISSUE THREAD

**Issue by DiegoMcDipster** [microsoft/WSL#8106]
Hi,

After I upgraded my pc to windows 11 the terminal no longer opens on the home directory '~', but instead opens on the root '/'

My settings.json has these settings:
```
      {
        "guid": "{defaultProfile}",
        "hidden": false,
        "name": "Ubuntu",
        "source": "Windows.Terminal.Wsl",
        "startingDirectory": "//wsl$/Ubuntu/home/{username}"
}
```

Any suggestions?

Note: everything else seems to be working fine. I can access the startingDirectory via '~' enter.  If anything it's better than on windows 10... less flakey.

**Comment by DiegoMcDipster** [comment]
I tried: 
"startingDirectory": "~"

Unfortunately, that gives the error: The system cannot find the file specified.

**Comment by benhillis** [comment]
Perhaps try a backslash?

**Comment by DiegoMcDipster** [comment]
fyi: This fixed itself.  I think there must've been a windows update.
