### ISSUE TITLE
Cannot start even though hardware virt is enabled

### ISSUE THREAD

**Issue by wx4cb** [microsoft/WSL#8107]
### Version

Windows 11 [Version 10.0.22000.527] - all up to date

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

ubuntu 20.04 (from store)

### Other Software

Clean fresh install - only extra programs are the nvidia drivers for the 1650gt, cpu-Z, services for NFS are there to access my NFS shares on my server
I have tried all the bcdedit stuff that i can find on google.

PLEASE NOTE: WSL ran perfectly fine under windows 10 pro

### Repro Steps

Enabled Hardware virtualisation in the bios

Installed hyperV, virtual environment platform, windows subsystem for linux from "add/remove windows features" and rebooted when requested

Installed Ubuntu and Ubuntu 20.04 from the MS store

Ran windows update to make sure no outstanding updates

rebooted when requested

run ubuntu (and ubuntu 20.04)  from start menu

### Expected Behavior

Ubuntu runs in a window

### Actual Behavior

running "ubuntu" and "ubuntu2004" from the command line (cmd.exe) results in the following errors:

```
Installing, This may take a few minutes
WslRegisterDistribution failed with error 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

When running "ubuntu2004":
```
Installing, This may take a few minutes
WslRegisterDistribution failed with error 0x80370102
Please enable virtual machine platform windows feature and ensure virtualisation is enabled in the bios
```
![Screen-3-1-2022_114917_AM](https://user-images.githubusercontent.com/1495297/156238964-99095b89-ef2a-4a3b-b009-bae1cc421c94.png)
![Screen-3-1-2022_114938_AM](https://user-images.githubusercontent.com/1495297/156238967-b5b9cbc0-a870-485e-808a-bad12430d096.png)

![image](https://user-images.githubusercontent.com/1495297/156239371-10625d74-3355-494c-a881-8e8cb57ac18e.png)
![image](https://user-images.githubusercontent.com/1495297/156239402-4bc39839-7496-4772-b470-f4a760d00754.png)
![image](https://user-images.githubusercontent.com/1495297/156239853-bec2036b-4fa9-4830-9f00-50e34f4a9957.png)

**Comment by wx4cb** [comment]
ok update.... if i set it to wsl1 it works, but i want WSL-2 not 1 for the gui access

```
wsl --set-default-version 1
```

**Comment by abdurraheemali** [comment]
Same thing happens on my machine.

**Comment by wx4cb** [comment]
> Same thing happens on my machine.

i've seen plenty of issues on here about it but the fixes in there dont work here... i know it's not the fastest machine in the world, but it runs perfectly fine for testing stuff.

and ran perfectly fine in win10

**Comment by 0xbadfca11** [comment]
Pentium E5700 is too old CPU.
https://www.intel.com/content/www/us/en/support/articles/000034303/processors.html

**Comment by wx4cb** [comment]
> Pentium E5700 is too old CPU. https://www.intel.com/content/www/us/en/support/articles/000034303/processors.html

it ran wsl2 perfectly fine on windows 10, runs virtualbox perfectly fine.

**Comment by 0xbadfca11** [comment]
No matter how other software uses the CPU features, [WSL2 requires SLAT](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#:~:text=WSL2%20requires%20that%20your%20CPU%20supports%20the%20Second%20Level%20Address%20Translation%20(SLAT)%20feature) and the [Pentium E5700 does not support SLAT](https://ark.intel.com/content/www/us/en/ark/compare.html?productIds=42801,219435#:~:text=O%20(VT%2Dd)%20%E2%80%A1-,Intel%C2%AE%20VT%2Dx%20with%20Extended%20Page%20Tables%20(EPT),-%E2%80%A1) (as known as Intel Extended Page Tables).
[SLAT is an extension of VT-x](https://en.wikipedia.org/wiki/X86_virtualization#Intel_virtualization_(VT-x)) and the word "VT-x" may or may not include SLAT. CPU-Z doesn't seem to include.

**Comment by daviangel** [comment]
> Pentium E5700 is too old CPU. https://www.intel.com/content/www/us/en/support/articles/000034303/processors.html

Well just ran into this issue on my 12th Intel i5-12600K cpu.
Weird thing is have works fine in one version of Windows 11 I'm running, In the second copy of Windows 11 on same machine the only difference in the one that doesn't work is that I downloaded and tried to install Ubuntu from the Microsoft app store before enabling the Linux subsystem and after trying to correct that nothing seemed to work except setting wsl to version 1 as mentioned above!
