### ISSUE TITLE
Couldn't detect Raspberry Pi Pico (RPI-RP2) as mass storage drive

### ISSUE THREAD

**Issue by HughGrant** [microsoft/WSL#8120]
### Version

Microsoft Windows [Version 10.0.22000.527]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.60.1-microsoft-standard-WSL2

### Distro Version

20.04

### Repro Steps

1. press bootsel on your rp pi pico and connect it to your windows pc.
2. windows shows up RPI-RP2 disk correctly as a mass storage drive.
3. But within WSL, it doesn't list RPI-RP2 under /mnt
4. I can see my all local drives under /mnt

### Expected Behavior

list RPI-RP2 as expected.

### Actual Behavior

couldn't detect rp pi pico as mass storage drive within WSL.

**Comment by MySurmise** [comment]
Same Problem here. I am using usbip, but it does not seem to work...
