### ISSUE TITLE
When opening windows mobile hotspot, WSL has no network connecting. Is there any solution for this?

### ISSUE THREAD

**Issue by JSHT** [microsoft/WSL#8123]
### Version

Microsoft Windows [Version 10.0.22000.527]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

When I open windows mobile hotspot, WSL can't connect to the network.
After stop windows mobile hotspot, WSL network work.

### Expected Behavior

They can work simultaneously.

### Actual Behavior

![image](https://user-images.githubusercontent.com/48956859/156775472-daf7afdf-f243-4152-b48f-b2748cb3369c.png)
![image](https://user-images.githubusercontent.com/48956859/156775536-1c12d6b1-e41e-4c22-8964-1efb8c502657.png)
=> WSL Unreachable
![image](https://user-images.githubusercontent.com/48956859/156775601-6f4a5be1-db5d-4a8c-a063-15072024c907.png)
=> ping success

**Comment by Anonymous-AAAA** [comment]
Same issue here.
When I enable the hotspot, I can't do neither apt update nor ping.
In other words, I can't connect to network in WSL.

---


| System       | Windows 10 Pro (21H2 19044.1706) |
|-------------:|:-----------------------------------------|
| Linux distro | Ubuntu-20.04                                   |
| WSL          | WSL 2 (5.10.102.1)                              |

### I've done the following actions, but still not solved :
- Clean installation of WSL
- Clean installation of Ubuntu distro
- Edit the default DNS [Here for details](https://github.com/microsoft/WSL/issues/4285#issuecomment-522201021)
- Reset the network options in CMD [Here for details](https://github.com/microsoft/WSL/issues/3438#issuecomment-410518578)
