### ISSUE TITLE
WSL2 multiple Instances Communication

### ISSUE THREAD

**Issue by skyfall01** [microsoft/WSL#8125]
**Is your feature request related to a problem? Please describe.**
I use ansible a lot for my development workflows. During testing I run the playbook on the control node which will trigger the plays on multiple nodes. Since all the WSL2 instances regardless of the distro, they are running share the same network-space have same IP address, ansible fails to run plays on other instances. Also we need to invoke terminal for that instance to be online/running. Because of this it's difficult to use such kind of development workflows

**Describe the solution you'd like**
A VNIC would be best which can assign different ip address to different instances. The same VNIC can also be used for port forwarding host port to instance port (similar to virtualbox)
While we're at it it would be nice to run some wsl instances in background without having to open the respective terminal of instance(like headless service)

Such functionalities like managing instances, managing network space can be done using some WSL 2 GUI accessed from windows

**Describe alternatives you've considered**
The solution described above is possible in virtualbox where we can create NAT network(not same as NAT ❌) and assign multiple VM's in the same subnet. This can be used for both VM-to-VM communication(different ip addresses) as well as VM-to-hostORInternet(port forwarding)

Also we can run multiple VM's in the background as headless service without invoking any terminal as such.

All the functionalities can be neatly done in virtualbox GUI 

**Additional context**

**Comment by Biswa96** [comment]
AF_LOCAL or AF_UNIX can be used to communicate between two WSL2 instances.

**Comment by skyfall01** [comment]
@Biswa96 Unfortunately AF_LOCAL cannot be used with ansible. We have inventory file in ansible which has the IP address of all the hosts where it will run the plays.

Also AF_LOCAL can only be used for process-to-pricess communication running in the same machine

**Comment by yume-chan** [comment]
In fact, multiple distros are running in the same VM, sharing the same kernel, so also having the same IP address.

The file system is isolated, except the `/mnt/wsl` directory, so you can create `AF_UNIX` sockets there from one distro and connect from another.
