### ISSUE TITLE
Failure to update WSL v1 to v2

### ISSUE THREAD

**Issue by Ywandung-Lyou** [microsoft/WSL#8127]
### Version

Microsoft Windows [版本 10.0.22000.527]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu-20.04

### Repro Steps

```shell
wsl -l -v
wsl --set-version Ubuntu-20.04 2
wsl -l -v
```

### Expected Behavior

<img width="446" alt="无法升级WSL2" src="https://user-images.githubusercontent.com/57492327/156921018-a4a84f35-09ba-48ee-b156-af969dd6b131.png">

### Actual Behavior

WSL is not updated.

**Comment by owenschupp** [comment]
Just to double-check before investigating further, have you followed the steps for upgrading to WSL 2 listed [here](https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2)? You may need the [virtual machine optional component](https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-3---enable-virtual-machine-feature) and the [Linux kernel package update](https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package) if you have not done so already
