### ISSUE TITLE
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS

### ISSUE THREAD

**Issue by ZachHandley** [microsoft/WSL#8137]
### Version

Microsoft Windows [Version 10.0.19044.1566]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I start Windows, Ubuntu 20.04 should run

I've enabled Virtualization in my CPU BIOS settings https://i.imgur.com/Fni8TL8.png
I've enabled the Windows Virtual Machine Platform in the Turn Windows Features On or Off section https://i.imgur.com/W1GOfcb.png

I've tried enabling/disabling WSL2 with the /DISM commands and rebooting in between

Nothing works and the error doesn't change

### Expected Behavior

It should run, but instead I get an error about virtualization

### Actual Behavior

```Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

[process exited with code 4294967295]

### Diagnostic Logs

_No response_

**Comment by Biswa96** [comment]
Make sure `bcdedit` command shows `hypervisorlaunchtype auto`.

**Comment by ZachHandley** [comment]
> 

it does indeed https://i.imgur.com/djDmFJE.png

**Comment by DanPinGF** [comment]
Do you have Hyper-V enabled? In most instances other virtualization software may not work correctly if you have that feature turned on.

**Comment by ZachHandley** [comment]
> Do you have Hyper-V enabled? In most instances other virtualization software may not work correctly if you have that feature turned on.

I ended up updating to Windows 11, changing nothing, and it works now. Seems to be a Windows 10 bug.

**Comment by DanPinGF** [comment]
> I ended up updating to Windows 11, changing nothing, and it works now. Seems to be a Windows 10 bug.

Well, good for you! May I suggest closing this issue?

**Comment by RefriZaddo** [comment]
I use Windows 11 and it doesn't work, even though I have VirtualBox 7, which supports Hyper-V

**Comment by RefriZaddo** [comment]
maybe i have to update to 22H2?
