### ISSUE TITLE
WSL (Ubuntu) networking does not work

### ISSUE THREAD

**Issue by wslrocks** [microsoft/WSL#8138]
I have the **WSL** service enable and downloaded Ubuntu from the Windows Store.

networking is not working (cannot ping anything)

---

**Config:  WSL Version 2 | Ubuntu 20.04**

On the many other machines I use it works OK without issue (WSL2, Ubuntu 20.04 from Windows store)

I am not able to access networking in the shell/bash.  I cannot ping yahoo.com for example (by domain or IP address).

Host networking is OK.

---
I thought it might be my employers **VPN**, but I turned that off and it still does not work.

The machine is supplied by my employer.  I believe there may be something configured so that I do not have internet access within WSL, but I do not know what.

It could be a group policy, it could be some setting in the firewall.

When searching on this issue, I am given hundreds of commands to try.  Before I start typing commands, I want to understand the issue, find the problem and only then a solution.

--
**the error message I get is:**
ping: yahoo.com: Temporary failure in name resolution

--
**$ping 203.0.178.191**
PING 203.0.178.191 (203.0.178.191) 56(84) bytes of data.
From 172.29.191.180 icmp_seq=1 Destination Host Unreachable

---
I have these network adapters enabled

vEthernet (WSL)
enabled
Hyper-V Virtual Ethernet Adapter

vEthernet (Ethernet)
Enabled
Hyper-V Virtual Ethernet Adapter

vEthernet (WiFi)
Enabled
Hyper-V Virtual Ethernet Adapter

---
**/etc/resolv.conf**

#This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
#[network]
#generateResolvConf = false
nameserver 172.29.176.1

(changing this to something like:  8.8.8.8 does not fix it)

---
I don't see any antivirus installed other than defender

---
Following these steps does not fix things

cmd prompt as admin:
wsl --shutdown
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns

Windows Search > Network Reset

Restart Windows

--
In Windows Security > Firewall & Network Protection > Public Network > Block all incoming connections is OFF (allows all incoming connections)

---
I followed all suggested remedies here, and none of them work
https://github.com/microsoft/WSL/issues/5336

---
What steps can I take to resolve this?  My companies IT dept is of no help.

**Comment by gregid** [comment]
I had similar problem after connecting via VPN - then even after the disconnect the problem persisted. It was finally resolved by:

https://github.com/microsoft/WSL/issues/5256#issuecomment-995616961

**Comment by iwhy** [comment]
why should ms carelessly published such rubblish waste our so much time and effort，，，FFF KKK

**Comment by Babiole77** [comment]
I had a similar problem, the following approach helped:
1. check your local DNS server from cmd: nslookup
2. change/add the address in /etc/resolv.conf: nameserver ip_address

**Comment by bman6in** [comment]
In your WSL ```sudo chmod 4711 /bin/ping```

**Comment by manojkumarorg** [comment]
I can't able to ping while using wsl without reaching my network service I can't able to do any kind os installation

**Comment by bert-w** [comment]
This seemed to work for me (Windows 11):

Use the `.wslconfig` file in your windows user directory, and add the contents:
```
[wsl2]
networkingMode=mirrored
```

This was the only thing that worked for me. Something got messed up in the networking configuration before and I couldnt repair it any other way. By setting it to `mirrored` it is using a new architecture that is mirroring your Windows network setup.

Additional info:
- https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking
- https://learn.microsoft.com/en-us/windows/wsl/wsl-config
