### ISSUE TITLE
$SUDO_UID in wsl.conf boot command

### ISSUE THREAD

**Issue by NPhMKgbDNy1M** [microsoft/WSL#8144]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 21.10

### Repro Steps

in /etc/wsl.conf:

[user]
default=podman
[boot]
command="sudo bash -c 'echo $SUDO_UID' >> /home/podman/test.tmp"

logout
wsl -t ...
wsl -d ...

### Expected Behavior

content of test.tmp:
1000

1000 is the uid of user podman.

### Actual Behavior

content of test.tmp:
0

0 is the uid of user root

**Comment by 0xbadfca11** [comment]
[This command is run as the root user.](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings)

**Comment by NPhMKgbDNy1M** [comment]
yes and [$SUDO_UID](https://www.sudo.ws/docs/man/1.8.27/sudo.man/#SUDO_UID) is the UID of the user who invoked sudo.
So in my opinion, if i start wsl with default user podman, the root command of wsl.conf should give me the correct invoker, right?

**Comment by NPhMKgbDNy1M** [comment]
Okay. Alright. Then I got it wrong. Would be a great feature if $SUDO_UID worked.
