### ISSUE TITLE
start bash.exe error , print '????????????????'

### ISSUE THREAD

**Issue by falseUtopia** [microsoft/WSL#8147]
### Version

Microsoft Windows [版本 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.60.1

### Distro Version

Debian

### Repro Steps

C:\Windows\System32\bash.exe

详见下图

### Expected Behavior

print bash.exe help

### Actual Behavior

详见下图

![image](https://user-images.githubusercontent.com/19901195/158180307-38877463-81e3-4bc3-b12e-a06bc9d1656b.png)

**Comment by Tommy131** [comment]
那试一下 `chcp 936` 看一下有没有解决，或者在启动cmd的时候使用管理员模式。我在管理员模式下输入 `bash.exe` 时提示的是 `拒绝访问`。
![image](https://user-images.githubusercontent.com/19190746/158201824-ec12c15b-0e22-453b-a641-218165d47829.png)

**Comment by falseUtopia** [comment]
> 那试一下 `chcp 936` 看一下有没有解决，或者在启动cmd的时候使用管理员模式。我在管理员模式下输入 `bash.exe` 时提示的是 `拒绝访问`。 ![image](https://user-images.githubusercontent.com/19190746/158201824-ec12c15b-0e22-453b-a641-218165d47829.png)


![image](https://user-images.githubusercontent.com/19901195/158202998-3fdee579-21cf-4bb2-b5ae-5bafd915fc2f.png)

感觉不是编码的问题, 大佬, 还有招不

**Comment by falseUtopia** [comment]
> 那试一下 `chcp 936` 看一下有没有解决，或者在启动cmd的时候使用管理员模式。我在管理员模式下输入 `bash.exe` 时提示的是 `拒绝访问`。 ![image](https://user-images.githubusercontent.com/19190746/158201824-ec12c15b-0e22-453b-a641-218165d47829.png)

![image](https://user-images.githubusercontent.com/19901195/158203291-c26929e5-63a6-4840-80ec-1226e4069c7f.png)

**Comment by Tommy131** [comment]
那可能是官方的问题了，不清楚我这里为何可以正常显示

**Comment by falseUtopia** [comment]
> 

 你的发行版是哪个哇 ,我更换试试

**Comment by Tommy131** [comment]
> > 
> 
>  你的发行版是哪个哇 ,我更换试试

我用的是DebianGNU 11，不太清楚是官方的问题还是系统的编码问题

**Comment by falseUtopia** [comment]
![image](https://user-images.githubusercontent.com/19901195/170154952-a5555811-6c54-4944-9cb6-130d789358e9.png)

执行 ps1 时 程序报错了: "get-acl : 找不到路径“C:\ProgramData\Microsoft\Windows\WindowsApps”，因为该路径不存在。"

我不知道是否有影响

**Comment by falseUtopia** [comment]
[WslLogs-2022-05-25_00-41-30.zip](https://github.com/microsoft/WSL/files/8767098/WslLogs-2022-05-25_00-41-30.zip)

**Comment by OneBlue** [comment]
Thank you @falseUtopia. I'm not seeing anything that jumps out in the logs.

I'm wondering if your windows installation could be corrupted. Can you please share the output of:

```
sfc.exe /scannow
```

In an elevated command prompt ?

**Comment by falseUtopia** [comment]
sorry :(   @OneBlue 
因为 Github 给我发的邮件被系统认为是垃圾邮件。所以很迟才回复你

![image](https://user-images.githubusercontent.com/19901195/173243160-42cab881-e2fa-4c8c-9de9-26b22e6f89cd.png)


`Start the system scanning. This process will take some time.`  
`\n`  
`Start the verification phase of system scanning.`  
`Verification 100% is completed.`  
`\n`  
`Windows resource protection has not found any complete conflict.`  
（by Google Translate）

**Comment by OneBlue** [comment]
Thanks for sharing this @falseUtopia. I wonder if this is a language configuration issue.

I wonder if that's a language configuration issue. Can you try disabling the WSL optional component, rebooting, and enabling it again ? I wonder if that will fix the issue

**Comment by ljyslyc** [comment]
Has everyone solved it yet? I'm having the same problem ？？？？？？？

**Comment by falseUtopia** [comment]
我不知道为什么现在又是正常的，难道是我升级到了Windows11？

```
C:\>bash.exe
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)
...
```
