### ISSUE TITLE
Include module nf_conntrack in WSL2 kernel

### ISSUE THREAD

**Issue by c0ffeec0der** [microsoft/WSL#8149]
**Is your feature request related to a problem? Please describe.**
Yes, [Istio issue 37885](https://github.com/istio/istio/issues/37885) WSL2 kernel (5.10.60.1-microsoft-standard-WSL2) does not have nf_conntrack module

**Describe the solution you'd like**
Include module nf_conntrack

**Describe alternatives you've considered**
N/A

**Additional context**
Without the module istio dns proxy will not run. for more details check [Istio issue 37885](https://github.com/istio/istio/issues/37885)

**Comment by c0ffeec0der** [comment]
Thanks @elsaco 

How to enable "# CONFIG_NF_CONNTRACK_ZONES is not set"?

Is it by changing in /proc/config.gz and reboot WSL?

**Comment by elsaco** [comment]
@c0ffeec0der to enable `CONFIG_NF_CONNTRACK_ZONES` download the latest `WSL2-Linux_kernel` from https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-5.10.102.1.tar.gz and compile a new kernel. After a successful build, copy the new `bzImage` to the Windows filesystem and reference the new kernel in your `.wslconfig` file. Run `wsl --shutdown` to make sure the new kernel is used for new WSL instances.

This is a `make config` screenshot with the above setting enabled:

![wsl_kernel_options](https://user-images.githubusercontent.com/3933920/158275426-aeb65f02-d2d8-4914-a690-b58ce027d743.png)

**Comment by c0ffeec0der** [comment]
@elsaco Thank you very much! I am able to compile the kernel
