### ISSUE TITLE
nodejs not working, exec format error

### ISSUE THREAD

**Issue by wangqr** [microsoft/WSL#8151]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Arch

### Repro Steps

Install nodejs from Archlinux repo with `pacman -S nodejs`, and run `node`

### Expected Behavior

nodejs starts

### Actual Behavior

nodejs does not start. exec format error.
```
wangqr@ocalhost:~$ node
zsh: exec format error: node
```

### Diagnostic Logs

nodejs can start if we manually invoke ld-linux, although it is already the interpreter in the ELF.
```
wangqr@ocalhost:~$ /usr/bin/node
zsh: exec format error: /usr/bin/node
wangqr@ocalhost:~$ strace /usr/bin/node
execve("/usr/bin/node", ["/usr/bin/node"], 0x7ffff42aefa0 /* 25 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
wangqr@ocalhost:~$ /lib/ld-linux-x86-64.so.2 /usr/bin/node
Welcome to Node.js v17.7.1.
Type ".help" for more information.
>
wangqr@ocalhost:~$ /lib64/ld-linux-x86-64.so.2 /usr/bin/node
Welcome to Node.js v17.7.1.
Type ".help" for more information.
>
wangqr@ocalhost:~$ file /usr/bin/node
/usr/bin/node: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=10ec67f51a763d04ac6e1fe305ce214fb40eabda, for GNU/Linux 4.4.0, stripped
wangqr@ocalhost:~$ readelf -h /usr/bin/node
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              DYN (Position-Independent Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x6aa570
  Start of program headers:          64 (bytes into file)
  Start of section headers:          34087608 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         16
  Size of section headers:           64 (bytes)
  Number of section headers:         30
  Section header string table index: 29

```

**Comment by wangqr** [comment]
Some more information:
1. I do find a way to solve the issue:
    * In a docker, downgrade glibc from 2.35 to 2.33 using [Archlinux Archive](https://wiki.archlinux.org/title/Arch_Linux_Archive) on [2022-02-14](https://archive.archlinux.org/repos/2022/02/14/core/os/x86_64/)
    * Compile nodejs (`asp checkout nodejs; cd nodejs/trunk; makepkg`)
    * The resulting pkg.tar.zst will work fine on WSL1
    * Note: I built the package in a docker container running on a real archlinux machine. I haven't tried if downgrading glibc on WSL1 works. Because downgrading glibc is likely to break other packages, and fixing glibc issue in WSL1 is difficult.

1. Compiling from source on WSL1 with the current glibc 2.35-2 will fail halfway with "Exec format error":
```
  g++ -o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/mkcodecache -pthread -rdynamic -m64 -Wl,-z,noexecstack -Wl,--whole-archive /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_snapshot.a -Wl,--no-whole-archive -Wl,-z,relro -Wl,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,--start-group /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/mkcodecache/src/node_snapshot_stub.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/mkcodecache/src/node_code_cache_stub.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/mkcodecache/tools/code_cache/mkcodecache.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/mkcodecache/tools/code_cache/cache_builder.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/libnode.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/histogram/libhistogram.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/uvwasi/libuvwasi.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_snapshot.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_libplatform.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/llhttp/libllhttp.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_base_without_compiler.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_libbase.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_zlib.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_compiler.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_initializers.a -lz -luv -lbrotlidec -lbrotlienc -lcares -lnghttp2 -lcrypto -lssl -licui18n -licuuc -licudata -ldl -Wl,--end-group
  g++ -o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/node_mksnapshot -pthread -rdynamic -m64 -Wl,-z,noexecstack -Wl,--whole-archive /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_snapshot.a -Wl,--no-whole-archive -Wl,-z,relro -Wl,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,--start-group /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/node_mksnapshot/src/node_snapshot_stub.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/node_mksnapshot/src/node_code_cache_stub.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/node_mksnapshot/tools/snapshot/node_mksnapshot.o /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/libnode.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/histogram/libhistogram.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/uvwasi/libuvwasi.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_snapshot.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_libplatform.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/deps/llhttp/libllhttp.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_base_without_compiler.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_libbase.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_zlib.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_compiler.a /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj.target/tools/v8_gypfiles/libv8_initializers.a -lz -luv -lbrotlidec -lbrotlienc -lcares -lnghttp2 -lcrypto -lssl -licui18n -licuuc -licudata -ldl -Wl,--end-group
  LD_LIBRARY_PATH=/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/lib.host:/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen; "/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/mkcodecache" "/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen/node_code_cache.cc"
  LD_LIBRARY_PATH=/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/lib.host:/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen; "/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/node_mksnapshot" "/home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen/node_snapshot.cc"
/bin/sh: line 1: /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/mkcodecache: cannot execute binary file: Exec format error
make[1]: *** [node.target.mk:13: /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen/node_code_cache.cc] Error 126
make[1]: *** Waiting for unfinished jobs....
/bin/sh: line 1: /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/node_mksnapshot: cannot execute binary file: Exec format error
make[1]: *** [node.target.mk:26: /home/wangqr/nodejs/trunk/src/node-17.7.1/out/Release/obj/gen/node_snapshot.cc] Error 126
rm 153bac10d83d38fd810d27369039858f690025da.intermediate 5fb9d05e8e7a809bf286a9a99430b12e50e12e34.intermediate 8c61239488171a14609c6ceaa1326c094866c228.intermediate 04b2e589442e78ea5b814ca0512cab45489617e8.intermediate
make: *** [Makefile:113: node] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by gavenkoa** [comment]
The same problem on Debian:

```
bash# apt-cache show nodejs                                                                                                                                                                                                                Package: nodejs                                                                                                                                                                                                                            Version: 16.13.2+really14.19.1~dfsg-6                                                                                                                                                                                                      Installed-Size: 949                                                                                                                                                                                                                        Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@alioth-lists.debian.net>                                                                                                                                                   Architecture: amd64                                                                                                                                                                                                                        Replaces: libnode72 (<< 12.22.10~dfsg~), libnode83 (<< 16.13.2+really14.19.1~dfsg~), nodejs-legacy
Provides: node-types-node (= 14.18.12~16.13.2+really14.19.1~dfsg-6)
Depends: libc6 (>= 2.2.5), libnode83 (= 16.13.2+really14.19.1~dfsg-6)
```

When run:

```
/usr/bin/node --version
-bash: /usr/bin/node: cannot execute binary file: Exec format error
```

libc6 is v2.33-7.

```
bash# strace -f node --version
execve("/usr/bin/node", ["node", "--version"], 0x7fffdc8ab7e0 /* 30 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
```

**Comment by gavenkoa** [comment]
As in https://github.com/microsoft/WSL/issues/5875 following succeeds:

```
/lib64/ld-linux-x86-64.so.2 /usr/bin/node --version
v14.19.1
```

**Comment by gavenkoa** [comment]
Similar symptoms in https://github.com/microsoft/WSL/issues/5154

**Comment by qyb** [comment]
the same error: https://github.com/microsoft/WSL/issues/8219

**Comment by srogerf** [comment]
Had the same issues and upgrading to WSL 2 worked for me
` wsl --set-version <name> 2`

Use <name> from 
`wsl -l -v`

I did follow https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-3---enable-virtual-machine-feature (and step 4) but node is working for me now. This is with Ubuntu 22.04

**Comment by gavenkoa** [comment]
As a workaround I updated `npm` tool (actual file is `/usr/share/nodejs/npm/bin/npm-cli.js`):

```js
#!/lib64/ld-linux-x86-64.so.2 /usr/bin/node
//#!/usr/bin/env node
require('../lib/cli.js')(process)
```

**Comment by gavenkoa** [comment]
It is possible to make a workaround for `node` itself:

```sh
sudo mv /usr/bin/node /usr/bin/node-orig
printf '#!/bin/sh\nexec /lib64/ld-linux-x86-64.so.2 /usr/bin/node-orig "$@"' | sudo tee /usr/bin/node
sudo chmod a+x /usr/bin/node
```

My previous fix for `npm` won't work with the updated `node` executable, needs to be reverted.

**Comment by andreineculau** [comment]
@gavenkoa my general fix is to run

`wsl-fix-exec-format-error $(realpath $(command -v node))`

The script is here: https://github.com/ysoftwareab/yplatform/blob/master/bin/wsl-fix-exec-format-error

Based on https://gist.github.com/the-moog/179753aacc52b262d1068878d520e9c9 by @the-moog @wangqr 🙌

Running realpath is needed because sometimes (eg homebrew) node in your $PATH is a symlink

PS: I have found that I need to patch gzip as well, not just node, so a generic patch script is really good to have

**Comment by gavenkoa** [comment]
@andreineculau I understand the solution, the initial analysis was done by https://github.com/microsoft/WSL/issues/8219#issuecomment-1094123281 stating that it is a bug in `lxcore.sys`. 

`ls.so` loads image like the `exec` call but avoids problems in Microsoft's `lxcore.sys`. It is better for sysadmins who are afraid binary patching with `elftools.elf.elffile import ELFFile` ))

**Comment by wangqr** [comment]
> ```shell
> sudo mv /usr/bin/node /usr/bin/node-orig
> printf '#!/bin/sh\nexec /lib64/ld-linux-x86-64.so.2 /usr/bin/node-orig "$@"' | sudo tee /usr/bin/node
> sudo chmod a+x /usr/bin/node
> ```

@gavenkoa This method can be problematic for modules that assume argv[0] be node itself when running node. For example, after your workaround, `npm i node-sass` will fail:
```
wangqr@ocalhost:~$ npm i node-sass
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/wangqr/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-35c885a8.sh
npm ERR! Building: /usr/lib/ld-linux-x86-64.so.2 /home/wangqr/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! /home/wangqr/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js: error while loading shared libraries: /home/wangqr/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js: invalid ELF header
npm ERR! node-gyp not found!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wangqr/.npm/_logs/2022-08-04T10_51_18_640Z-debug-0.log
```

**Comment by gavenkoa** [comment]
@wangqr wrote:
> For example, npm i node-sass will fail:

I had the same issue. I think you altered `npm` script, I warned about this above;

> My previous fix for npm won't work with the updated node executable, needs to be reverted.

**Comment by qchencc** [comment]
I got the same problem.
Win10 21H2 and Ubuntu 22.04  WSL1 

after `sudo apt install nodejs`
only get `/usr/bin/node: cannot execute binary file: Exec format error`

I fixed this problem by using nodejs package
https://github.com/nodesource/distributions/blob/master/README.md#debinstall
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by lexavey** [comment]
i got same problem.


i fix this problem using this code, hope help other

```
wget https://gist.githubusercontent.com/lexavey/155a95d803224d7c0af7e225d0d82396/raw/3b4c103e4c3ff702674f96dd12cc412e9c8766ad/fixexec.py
sudo python3 ./fixexec.py $(realpath $(command -v node))
node -v
```

**Comment by PovelikinRostislav** [comment]
Update to WSL v2 as @srogerf suggested - worked for me.
Ubuntu 22.04.1
Node v12.22.9

**Comment by justonia** [comment]
@qchencc 's solution worked for me on WSL1 + Ubuntu 18.04 + Windows 11 22H2, but required switching to Node v16:

```
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by ytrezq** [comment]
There were a similar issue with Qt. It was fixable using a strip command for removing `.note` section from the binary. But which one it would be in that case?

**Comment by vlatkodimeski** [comment]
root@GM00234:/mnt/c/api-service-js# sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme at-spi2-core fontconfig gtk-update-icon-cache gyp hicolor-icon-theme humanity-icon-theme javascript-common libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libauthen-sasl-perl libc-ares2 libcairo-gobject2
  libcairo2 libclone-perl libcolord2 libcups2 libdata-dump-perl libdatrie1 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libencode-locale-perl libepoxy0 libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl
  libfile-mimeinfo-perl libfont-afm-perl libfontenc1 libgdk-pixbuf-2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgl1 libgl1-amber-dri libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libgraphite2-3 libgtk-3-0
  libgtk-3-bin libgtk-3-common libgtkd-3-0 libharfbuzz0b libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl
  libhttp-negotiate-perl libice6 libio-html-perl libio-socket-ssl-perl libio-stringy-perl libipc-system-simple-perl libjs-events libjs-highlight.js libjs-inherits libjs-is-typedarray libjs-psl libjs-source-map libjs-sprintf-js
  libjs-typedarray-to-buffer liblcms2-2 libllvm11 libllvm13 liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnode-dev libnode72 libnotify-bin
  libnotify4 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpciaccess0 libphobos2-ldc-shared98 libpixman-1-0 librsvg2-2 librsvg2-common libsensors-config libsensors5 libsm6 libssl-dev libthai-data libthai0 libtie-ixhash-perl
  libtimedate-perl libtry-tiny-perl liburi-perl libuv1-dev libvte-2.91-0 libvte-2.91-common libvted-3-0 libvulkan1 libwayland-client0 libwayland-cursor0 libwayland-egl1 libwww-perl libwww-robotrules-perl libx11-protocol-perl libx11-xcb1
  libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxft2 libxi6 libxinerama1
  libxkbcommon0 libxkbfile1 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl libxmu6 libxrandr2 libxrender1 libxshmfence1 libxt6 libxtst6 libxv1 libxxf86dga1 libxxf86vm1 mesa-vulkan-drivers node-abab node-abbrev node-agent-base
  node-ansi-regex node-ansi-styles node-ansistyles node-aproba node-archy node-are-we-there-yet node-argparse node-arrify node-asap node-asynckit node-balanced-match node-brace-expansion node-builtins node-chalk node-chownr
  node-clean-yaml-object node-cli-table node-clone node-color-convert node-color-name node-colors node-columnify node-combined-stream node-commander node-console-control-strings node-core-util-is node-cssom node-cssstyle node-debug
  node-decompress-response node-defaults node-delayed-stream node-delegates node-depd node-diff node-encoding node-end-of-stream node-err-code node-escape-string-regexp node-events node-fancy-log node-foreground-child
  node-fs-write-stream-atomic node-fs.realpath node-function-bind node-gauge node-get-stream node-glob node-got node-graceful-fs node-growl node-has-flag node-has-unicode node-hosted-git-info node-https-proxy-agent node-iconv-lite
  node-iferr node-imurmurhash node-indent-string node-inflight node-inherits node-ini node-ip node-ip-regex node-is-buffer node-is-plain-obj node-is-typedarray node-isarray node-isexe node-json-buffer node-json-parse-better-errors
  node-jsonparse node-kind-of node-lcov-parse node-lodash-packages node-log-driver node-lowercase-keys node-lru-cache node-mimic-response node-minimatch node-minimist node-minipass node-ms node-mute-stream node-negotiator
  node-normalize-package-data node-npm-bundled node-npm-package-arg node-npmlog node-object-assign node-once node-osenv node-p-cancelable node-p-map node-path-is-absolute node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-psl node-pump node-punycode node-quick-lru node-read node-read-package-json node-readable-stream node-resolve node-retry node-rimraf node-run-queue node-safe-buffer node-semver node-set-blocking node-signal-exit
  node-slash node-slice-ansi node-source-map node-source-map-support node-spdx-correct node-spdx-exceptions node-spdx-expression-parse node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils node-stealthy-require
  node-string-decoder node-string-width node-strip-ansi node-supports-color node-text-table node-time-stamp node-tmatch node-tough-cookie node-typedarray-to-buffer node-unique-filename node-universalify node-util-deprecate
  node-validate-npm-package-license node-validate-npm-package-name node-wcwidth.js node-webidl-conversions node-whatwg-fetch node-wide-align node-wrappy node-write-file-atomic node-yallist perl-openssl-defaults tilix tilix-common
  ubuntu-mono x11-common x11-utils x11-xserver-utils xdg-utils
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  nodejs
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.2 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_16.x jammy/main amd64 nodejs amd64 16.19.0-deb-1nodesource1 [27.2 MB]
Fetched 27.2 MB in 3s (9991 kB/s)
(Reading database ... 51521 files and directories currently installed.)
Preparing to unpack .../nodejs_16.19.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (16.19.0-deb-1nodesource1) over (12.22.9~dfsg-1ubuntu3) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_16.19.0-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_16.19.0-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@GM00234:/mnt/c/api-service-js# node -v
bash: /usr/bin/node: cannot execute binary file: Exec format error
root@GM00234:/mnt/c/api-service-js#



Any solution for this?

**Comment by ZenCodeXY** [comment]
I also encountered the same problem and solved it by:
1. Download the Linux Binary file package from Nodejs official website (https://nodejs.org/en/download) and decompress it;
2. Establish a soft connection for node/npm/npx;

**Comment by brennandio** [comment]
@justonia  's solution didn't work at first because I had previously tried to install nodejs using sudo apt install nodejs. Which I think resulted in interfering with the installation of the v16 nodejs

I ended up fixing it by doing:
1. sudo apt remove nodejs
2. sudo apt-get purge nodejs (not sure if this is even necessary since it said "Package 'nodejs' is not installed, so not removed", but including it here anyway just in case)
3. sudo apt autoremove

Then I followed @justonia  's v16 install and it just worked

**Comment by vadimkantorov** [comment]
Similar issue with WSL1 + Ubuntu 22.04:
```shell
$ npm
/usr/bin/node: 1: ELF: not found
/usr/bin/node: 2: �: not found
/usr/bin/node: 2: Syntax error: word unexpected (expecting ")")
`` `

```shell
$ /lib64/ld-linux-x86-64.so.2 /usr/bin/node --version
v12.22.9
```

attaching `/usr/bin/node` in 
[bug.zip](https://github.com/microsoft/WSL/files/13637969/bug.zip)

**Comment by stuartmau** [comment]
The v16 deprecation warnings scared me off. I followed the following link and was able to install via nvm

https://phpout.com/questions/ubuntu/npm-show-npm-elf-not-found-error-in-wsl-ubuntu/
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl

**Comment by vadimkantorov** [comment]
Aside of the ELF error, my conclusion was that NPM's install from Ubuntu is somehow broken in WSLv1...

**Comment by kotenok2000** [comment]
This bash script fixed it for me.
I ran  sudo ./wsl-fix-exec-format-error.sh /usr/bin/node
[wsl-fix-exec-format-error.sh.txt](https://github.com/microsoft/WSL/files/14473141/wsl-fix-exec-format-error.sh.txt)

**Comment by epigramx** [comment]
The suggestion "upgrade to WSL2" is both partly off topic and also potentially wrong. It's potentially very wrong under certain contexts because WSL2 requires the Windows operating system to turn on the Hypervisor. This is completely unnecessary when there is no other requirement for it because the Hypervisor takes up resources to run everything from boot time (including the Operating System of Windows itself (because it's a type 1 Hypervisor instead of a type 2)).

**Comment by hiteshsahu** [comment]
Complete answer

```

// start wsl terminal
wsl    
// Install node 16 
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```

```
// Update Node Js 
sudo npm install -g n
sudo n stable
```

**Comment by splitice** [comment]
This issue is very annoying and still existing in WSL1.

The [wsl-fix-exec-format-error.sh.txt](https://github.com/microsoft/WSL/files/14473141/wsl-fix-exec-format-error.sh.txt) script does work but is quite tedious when trying to for example fix all the binaries used in a nodejs make execution.

**Comment by splitice** [comment]
Heres a patch for node that disables the larger code page sizes that does not work on WSL1 during the build process. It also detects WSL1. It doesnt currently work on  the main node binary however, there appears to be somewhere else forcing it to 8kb instead of the default 4kb that WSL1 incorrectly assumes so you will need to call the python script on the resulting binary for now.

https://github.com/HalleyAssist/node/commit/1c48afc4e51f6306b1eedb0289b7e2397bf7fdbc.patch

**Comment by gustavosbarreto** [comment]
Given that Microsoft has effectively deprioritized addressing core issues in WSL1, I’ve implemented a workaround  for this issue with ELF binaries.

The solution uses a custom wrapper (`elf_wrapper.c`) with `ld.so.preload` to automatically intercept and redirect ELF execution through `/lib64/ld-linux-x86-64.so.2`, enabling system-wide compatibility without user intervention. Unlike direct invocations of `/lib64/ld-linux-x86-64.so.2`, this approach captures ELF execution at the system level, eliminating the need for wrapper scripts, shell aliases, or direct binary modifications with `patchelf`.

`elf_wrapper.c` source code:

```c
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>

// Path to the ELF interpreter used to execute ELF binaries
static const char *ld_linux_so = "/lib64/ld-linux-x86-64.so.2";

// Pointer to the original execve function
static int (*original_execve)(const char *filename, char *const argv[], char *const envp[]) = NULL;

// Wrapper function for execve
int execve(const char *filename, char *const argv[], char *const envp[]) {
    if (!original_execve) {
        // Load the original execve function
        original_execve = dlsym(RTLD_NEXT, "execve");
    }

    // Check if the original file has the SUID bit set
    struct stat file_stat;
    if (stat(filename, &file_stat) == 0 && (file_stat.st_mode & S_ISUID)) {
        // If the SUID bit is set, call the original execve directly
        return original_execve(filename, argv, envp);
    }

    // Check if the file is an ELF binary
    FILE *file = fopen(filename, "rb");
    if (file) {
        char magic[4];
        fread(magic, 1, 4, file);
        fclose(file);

        // Check the ELF magic number: 0x7f 0x45 0x4c 0x46
        if (memcmp(magic, "\x7f""ELF", 4) == 0) {
            int argc;
            for (argc = 0; argv[argc] != NULL; argc++);

            char **new_argv = malloc((argc + 2) * sizeof(char *));
            new_argv[0] = (char *)ld_linux_so;
            new_argv[1] = (char *)filename;

            int i;
            for (i = 1; i < argc; i++) {
                if (argv[i] != NULL) {
                    new_argv[i + 1] = argv[i];
                }
            }

            new_argv[i + 1] = NULL;  // Finalize the array with NULL

            // Execute the binary with the ELF interpreter
            int result = original_execve(ld_linux_so, new_argv, envp);
            free(new_argv);
            return result;
        }
    }

    // If not ELF, execute normally
    return original_execve(filename, argv, envp);
}
```
Run:

```sh
sudo gcc -shared -fPIC -o /usr/local/lib/libelf_wrapper.so elf_wrapper.c -ldl
echo "/usr/local/lib/libelf_wrapper.so" | sudo tee -a /etc/ld.so.preload
```

**Comment by benhillis** [comment]
I've been trying to get a repro of this invalid elf format error but haven't found one that works on new versions of Windows. If you can reproduce this on windows 22621 or later please let me know by opening a new issue.

**Comment by gustavosbarreto** [comment]
@benhillis This issue is easily reproducible. I'm not sure if you've tried it.

![Image](https://github.com/user-attachments/assets/062a8513-5a1c-437f-a2c3-8c399a34ec54)

**Comment by vadimkantorov** [comment]
@benhillis Yep, it well reproduces for me on `Microsoft Windows [Version 10.0.22631.4460]`

WSLv1 with Ubuntu 24.04:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
$ sudo apt install nodejs
$ node
-bash: /usr/bin/node: cannot execute binary file: Exec format error
$ nodejs
-bash: /usr/bin/nodejs: cannot execute binary file: Exec format error
```

**Comment by vadimkantorov** [comment]
Somehow the 23 version of node fails with the same error while 22 version does not:

All on WSLv1 Ubuntu 24.04:

Breaks with exec format error:
```shell
curl -fsSL https://deb.nodesource.com/setup_23.x | sudo -E bash -
sudo apt-get install -y nodejs
node --version
```

Woks:
```shell
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
sudo apt-get install -y nodejs
node --version
```

**Comment by splitice** [comment]
Yes, this is not fixed.

**Comment by gustavosbarreto** [comment]
It's clear that Microsoft isn't prioritizing support for older processors, as seen with recent Windows 11 decisions. Since the issue wasn't even reproduced, it might be more practical to focus on migrating to WSL2 instead.

**Comment by kotenok2000** [comment]
It was reproduced in this issue
https://github.com/microsoft/WSL/issues/12359#issuecomment-2532624541

**Comment by gaoqiangks** [comment]
It's still there.

**Comment by MakaEdgarTFS** [comment]
Still present.

**Comment by suewonjp** [comment]
Still present.

**Comment by lygstate** [comment]
Still present on 
```
Microsoft Windows [Version 10.0.26100.32860]
(c) Microsoft Corporation. All rights reserved.
```

Better reopen this issue
