### ISSUE TITLE
Enable extra kernel options to support Istio dns proxy feature

### ISSUE THREAD

**Issue by davidshen84** [microsoft/WSL#8153]
**Is your feature request related to a problem? Please describe.**

Istio DNS proxy fails with the current kernel build, `Linux/x86 5.10.60.1`. There's a discussion on this [issue][1].

[1]: https://github.com/istio/istio/issues/37885

**Describe the solution you'd like**

Enable these two kernel option:

- CONFIG_NF_CONNTRACK_ZONES=y
- CONFIG_NETFILTER_XT_TARGET_CT=y

**Describe alternatives you've considered**
Use native Linux

**Additional context**

Istio version: 1.12.0

**Comment by thesuperzapper** [comment]
@kelsey-steele I see that you were the [last person to update the `config-wsl`](https://github.com/microsoft/WSL2-Linux-Kernel/commits/linux-msft-wsl-5.15.y/arch/x86/configs/config-wsl) kernel build options in the WSL repo. I would greatly appreciate you taking a look at this. 

How do you feel about enabling `CONFIG_NF_CONNTRACK_ZONES` and `CONFIG_NETFILTER_XT_TARGET_CT`, as doing so will unblock running Kubernetes clusters (with service meshes like Istio) on WSL2. 

(Read more about the Istio issue here: https://github.com/istio/istio/issues/37885)

---

_PS: I tried to raise a PR, but the [`microsoft/WSL2-Linux-Kernel`](https://github.com/microsoft/WSL2-Linux-Kernel) repo is limited to collaborators only._

**Comment by kelsey-steele** [comment]
@thesuperzapper  hello o/  

Happy to check into this. Give me time to do a little research and testing, then I'll come back here with an update. I'll do my best to provide an update here before I update the kernel next (~end of month). 

I appreciate you taking the time on the PR and sorry the WSL2 repo isn't open to taking that at this time.

**Comment by kelsey-steele** [comment]
Quick swing by to note this isn't forgotten. I have these configs added to a kernel in testing now. I should have a proper update here next week.

**Comment by kelsey-steele** [comment]
@thesuperzapper sorry on such a delay for this task! This config change is part of a larger WSL update where WSL will support loadable modules. This will be the config changes in the upcoming kernel:

NF_CONNTRACK_ZONES=y
NETFILTER_XT_TARGET_CT=m

The next kernel release with the updated config file con be found in the WSL2-Linux-Kernel repo: https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.137.3

The loadable modules rely on a WSL update that is coming soon; this will first be seen as a pre-release. I'm keeping an eye out for that pre-release and plan to come back and update here when that happens. :) 

Thank you for the patience!

**Comment by kelsey-steele** [comment]
@thesuperzapper this update can be found in the latest WSL pre-release: https://github.com/microsoft/WSL/releases/tag/2.1.1

I'm going to close this issue now, though please report and ping me if any problems are found. Thank you! :)
