### ISSUE TITLE
SGX support in WSL

### ISSUE THREAD

**Issue by shalabhjain** [microsoft/WSL#8157]
It seems SGX is not supported in WSL2. 

Since there is SGX support both within Hyper-V, and since Jan in CBL-Mariner (https://github.com/microsoft/CBL-Mariner/releases/tag/1.0.20220122-1.0), is there any plan for adding the support to WSL2?

**Comment by elsaco** [comment]
@shalabhjain the in-kernel driver for SGX support was mainlined in version 5.11. WSL is using 5.10, still. Since WSL kernel supports module loading/unloading you could try building an out-of-tree driver.
