### ISSUE TITLE
wsl2 execve system call overrides argv[0] when excecuting Windows binary via interop service

### ISSUE THREAD

**Issue by alonbl** [microsoft/WSL#8162]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

## Reproduction repo

https://github.com/alonbl/wsl2-execve-args

## Reproduction

```sh
$ make deps
$ make check
```

```
Native test
./exec-args dump-args | tee dump-args.out
CWD: '/home/alonbl/tmp/wsl2-args'
argv[0]='arg0'
argv[1]='arg1'
argv[2]='arg2'
PASS
Windows test
./exec-args dump-args-win.exe | tee dump-args-win.out
CWD: '\\wsl.localhost\Ubuntu\home\alonbl\tmp\wsl2-args'
argv[0]='dump-args-win.exe'
argv[1]='arg1'
argv[2]='arg2'
FAILED
make: *** [Makefile:31: check] Error 1
```

Notice that `argv[0]` is not preserved when executing Windows executable.

### Expected Behavior

`argv[0]` should be preserved for executable to be able to operate correctly:

1. Usually an execution needs `argv[0]` to locate the path from which it runs.
2. The `argv[0]` is used to differentiate between applets/mode of operation and required for normal functionality.

This should be applied for all executable, Windows and linux as the same practices apply to both operating systems.

In most cases the `argv[0]` is the path name of executable, please notice that the WSL2 working directory is preserved correctly, so the only fixup is required (if any) is to replace `/` to `\` if `argv[0]` resolves into the executable that is being run.

In all other cases the `argv[0]` would have preserved as-is.

Expected output from reproduction:
```
argv[0]='arg0'
```

### Actual Behavior

When executing Windows executable from WSL2 the `argv[0]` is replaced with the program name.

Actual:
```
argv[0]='dump-args-win.exe'
```
Expected:
```
argv[0]='arg0'
```

### Diagnostic Logs

The problem is at the WSL2 linux side not on the Windows native side.

Using strace I can see:

```
connect(4, {sa_family=AF_UNIX, sun_path="/run/WSL/721_interop"}, 110) = 0
write(4, "\6\0\0\0\360\0\0\0\352\10s\241\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\09\0\0\0\203\0\0\0\304\0\0\0\3\0\0\0\273\0\0\0\0\0\0\0\0\\\\wsl.localhost\\Ubuntu\\home\\alonbl\\tmp\\wsl2-execve-args\\dump-args-win.exe\0\\\\wsl.localhost\\Ubuntu\\home\\alonbl\\tmp\\wsl2-execve-args\0WSLENV=\0\0dump-args-win.exe\0arg1\0arg2\0", 240) = 240
```

Notice that the `arg0` is already gone when communicating the information to the interop service. Seems like someone forgot that the program name and `argv[0]` may be different when communicating between the environments, I expected to see both program name and `argv[0]` sent but ignored at the Windows side so that the fix will be on one environment. Now it seems that the fix should be applied in both.

**Comment by benhillis** [comment]
Thanks for reporting, looks like this is because we do not pass the `P` flag when registering our binfmt interpreter. Let me take a look and see if that's straightforward to add.

**Comment by alonbl** [comment]
Thanks @benhillis

I tried to set it up:
```
$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

However, I now see that the `argv[0]` is received by the program, however, it is received as `argv[1]` while `argv[0]` is the program executable.

```
argv[0]='dump-args-win.exe'
argv[1]='arg0'
argv[2]='arg1'
argv[3]='arg2'
```

The expected behavior is to preserve the `argv[0]` value in `argv[0]` as the Windows executable is not aware that it is an interpreter :)

I guess the interop should set the `P` flag and shift the `argv` when executing the Windows process.

**Comment by alonbl** [comment]
Hi @benhillis ,

Thanks, but...
How does it resolve this issue for you? What you have done exactly? I am getting `argv[0]` at `argv[1]`.

I pushed the fix into my repo.

At `Makefile`:

```make
fixup:
        sudo -- sh -c "echo -1 > /proc/sys/fs/binfmt_misc/WSLInterop; echo ":WSLInterop:M::MZ::/init:FP" > /proc/sys/fs/binfmt_misc/register"
```

Then I get:

```
Native test
./exec-args dump-args | tee dump-args.out
CWD: '/home/alonbl/tmp/wsl2-execve-args'
argv[0]='arg0'
argv[1]='arg1'
argv[2]='arg2'
PASS
Windows test
./exec-args dump-args-win.exe | tee dump-args-win.out
CWD: '\\wsl.localhost\Ubuntu\home\alonbl\tmp\wsl2-execve-args'
argv[0]='dump-args-win.exe'
argv[1]='arg0'
argv[2]='arg1'
argv[3]='arg2'
FAILED
make: *** [Makefile:34: check] Error 1
```

**Comment by elsaco** [comment]
@alonbl running `dump-args` directly, the output is different. I was expecting only `argv[0]` to be printed out. This is the output of `WSLInterop` after running `make fixup`:

```
tux@RIPPER:~/GitHub/wsl2-execve-args$ cat /proc/sys/fs/binfmt_misc/WSLInterop 
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

Output of `dump-args`:
```
tux@RIPPER:~/GitHub/wsl2-execve-args$ ./dump-args
CWD: '/home/tux/GitHub/wsl2-execve-args'
argv[0]='./dump-args'
```

And output of `dump-args-win.exe`:
```
tux@RIPPER:~/GitHub/wsl2-execve-args$ ./dump-args-win.exe 
CWD: '\\wsl$\Ubuntu\home\tux\GitHub\wsl2-execve-args'
argv[0]='dump-args-win.exe'
argv[1]='./dump-args-win.exe'
```

Do you have any input on why there are two arguments when running `dump-args-win.exe`? Thx!

**Comment by alonbl** [comment]
Hello @elsaco.

I guess that the `P` flag preserves the `argv[0]` as the 1st argument to the interpreter which is expected to handle the information and reconstruct the execution path.

Please run the program via my wrapper which demonstrates exactly the separation between what the `execve()` provides and what the underline operating system modifies.

Thanks,
Alon

**Comment by benhillis** [comment]
@alonbl - the binfmt interpreter also needs a change (basically it needs to know that an extra argument is being passed - the original argv[0]). The fix for this is twofold:

1. Register the binfmt interpreter with the `P` flag
2. Update the binfmt interpreter to expect the behavior

This will be fixed in a future version of the WSL package.

**Comment by alonbl** [comment]
Thank you @benhillis.

Will it work on WSL1 as well? It has the same issue.
I tried to set the `P` flag and it seems like unsupported.

I just found out that WSL2 is not available in Windows Servers for some unknown [reason](https://github.com/microsoft/WSL/issues/6301).

Thanks!

**Comment by alonbl** [comment]
Hello @benhillis ,

I see that the `P` flag was added in recent fix.

```
$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /tools/init
flags: PF
offset 0
magic 4d5a
```

The behavior is inconsistent, I modified my test program at https://github.com/alonbl/wsl2-execve-args to show this.
When `argv[0]` is a misc string it is working, but when it is matches the file name the file name is processed as `basename $file`, please run `make check` to reproduce.

```
Windows test program argument
./exec-args ./dump-args-win.exe ./dump-args-win.exe | tee dump-args-win.out
CWD: '\\wsl.localhost\Ubuntu-22.04\home\alonbl\tmp\wsl2-execve-args'
argv[0]='dump-args-win.exe'
argv[1]='arg1'
argv[2]='arg2'
FAILED
```

The root cause of this PR is the inability for executable to find itself as the full path was stripped, along side with the ability to pass any `argv[0]` string.

In addition there is a regression, I cannot find the root cause.

Check a new program in the repo `spawn-win.c`, what I am noticing is that when I run this program from WSL it fails to execute a windows program using `_spawnv` library call. However, when the same program is executed from cmd it works correctly. I thought that the working directory may be the problem but I modified it so I could not find the reason of the new breakage.

From within WSL:

```
/tmp$ ./spawn-win.exe
cwd: C:\Temp
prog: \\wsl.localhost\Ubuntu-22.04\tmp\dump-args-win.exe
ret=-1 errno=22
```

From CMD, the same file at the same location.

```
C:\>\\wsl.localhost\Ubuntu-22.04\\tmp\\spawn-win.exe
cwd: C:\Temp
prog: \\wsl.localhost\Ubuntu-22.04\tmp\dump-args-win.exe
CWD: 'C:\Temp'
argv[0]='\\wsl.localhost\Ubuntu-22.04\tmp\dump-args-win.exe'
ret=0 errno=0
```

I modified https://github.com/alonbl/wsl2-execve-args to show this, run `make check-spawn` to reproduce.

This regression breaks the environment entirely I could not find a workaround.

Regards,

```
C:\>wsl --version
WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.613
```
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```

**Comment by alonbl** [comment]
Hi @benhillis ,
I would like to make sure you captured my previous comment of an issue with the altered implementation.
Regards,
Alon

**Comment by benhillis** [comment]
Sorry, I lost track of this thread. Taking anothe rlook now.

**Comment by alonbl** [comment]
Thank you @benhillis 

Just reporting that recent wsl update still suffers from the same issue:

```
Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.61.4.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.739
```

**Comment by alonbl** [comment]
Latest WSL update, still fails

```
>wsl --version
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.856
```

**Comment by alonbl** [comment]
Hello @benhillis, 

Can you please have another look, this is still reproduced with recent 22H2 WSL.

It makes very difficult for programs to:
1. find their relative position from the working directory 
2. use command alias as `argv[0]`

```
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674
```

Execute the test program I provided at https://github.com/alonbl/wsl2-execve-args

```
Windows test program argument
./out/exec-args ./out/dump-args-win.exe ./out/dump-args-win.exe | tee dump-args-win.out
CWD: '\\wsl.localhost\Ubuntu-22.04\home\alonbl\tmp\wsl2-execve-args'
argv[0]='dump-args-win.exe'
argv[1]='arg1'
argv[2]='arg2'
FAILED
```

The `argv[0]` is expected to be `./out/dump-args-win.exe` while something overrides it to be `dump-args-win.exe`

Regards,

**Comment by alonbl** [comment]
@benhillis : I can reproduce this in release version of WSL,  `execve` system call is not working as expected to windows binaries.

```
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

Reproduction: https://github.com/alonbl/wsl2-execve-args
