### ISSUE TITLE
wsl mount vhd not working

### ISSUE THREAD

**Issue by SquallATF** [microsoft/WSL#8165]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

wsl --mount --vhd workdata.vhdx
but if use `Mount-VHD` command, and mount with DiskPath will successful mount.

### Expected Behavior

mount vhd successful

### Actual Behavior

```
K:\>wsl --mount --vhd workdata.vhdx
拒绝访问。
```

**Comment by benhillis** [comment]
The `--vhd` option is only available via the Store version of WSL.

**Comment by SquallATF** [comment]
my wsl is store version
```
wsl --version
WSL 版本： 0.56.2.0
内核版本： 5.10.102.1
WSLg 版本： 1.0.30
MSRDC 版本： 1.2.2924
Direct3D 版本： 1.601.0
Windows 版本： 10.0.22000.556
```

**Comment by SquallATF** [comment]
> Hi @SquallATF , try this:
> 
> If you mounted the disk in the past using wsl --mount, before installling the wsl preview from the store:
> 
>     1. run wsl --shutdown
> 
>     2. make a copy of the vhdx file
> 
>     3. try now wsl --mount --vhd 'vhdx copy'
> 
> 
> Does it show the same error?

I have make a copy of the vhdx and mount successful. Then I tested create new vhd and vhdx, all of them can mount successful.
But I still have a question the vhdx file that cannot be mounted is actually a new one created by Device Manager. That vhdx file still mount failed.

**Comment by leonidasthe300** [comment]
> 



> > Hi @SquallATF , try this:
> > If you mounted the disk in the past using wsl --mount, before installling the wsl preview from the store:
> > ```
> > 1. run wsl --shutdown
> > 
> > 2. make a copy of the vhdx file
> > 
> > 3. try now wsl --mount --vhd 'vhdx copy'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does it show the same error?
> 
> I have make a copy of the vhdx and mount successful. Then I tested create new vhd and vhdx, all of them can mount successful. But I still have a question the vhdx file that cannot be mounted is actually a new one created by Disk Management. That vhdx file still mount failed.
> 
> I seem to have found the cause of the problem, if vhd/vhdx is created by Disk Management and did not detach from Disk Management, then run `wsl --mount --vhd` command to mount that vhdx will report access denied. Then detach that vhdx from Disk Management, wsl mount will always report access denied. After that, even delete the vhdx and then create a new vhdx with the same name, it still cannot be mounted. Even after reboot the computer.
> 
> Some test, message is translated from Chinese
> 
> ```
> K:\>wsl --mount --vhd test1.vhdx
> access denied.
> 
> 
> K:\>copy test1.vhdx test2.vhdx
>          1 file(s) copied.
> 
> K:\>ren test1.vhdx test3.vhdx
> 
> K:\>wsl --mount --vhd test2.vhdx
> Disk attached but mount failed: Operation not permitted.
> For more information, run 'dmesg' in WSL2.
> To detach the disk, run 'wsl.exe --unmount \\?\K:\test2.vhdx'.
> 
> K:\>wsl --mount --vhd test3.vhdx
> access denied.
> 
> K:\>wsl --unmount test2.vhdx
> The operation completed successfully.
> 
> K:\>ren test2.vhdx test1.vhdx
> 
> K:\>ren test3.vhdx test2.vhdx
> 
> K:\>wsl --mount --vhd test1.vhdx
> Disk attached but mount failed: Operation not permitted.
> For more information, run 'dmesg' in WSL2.
> To detach the disk, run 'wsl.exe --unmount \\?\K:\test1.vhdx'.
> 
> K:\>wsl --mount --vhd test2.vhdx
> access denied. 
> ```

Yes, you can run  
 `wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions`  
and check the states of the disks after a restart to see it.

**Comment by SquallATF** [comment]
> Yes, you can run
> `wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions`
> and check the states of the disks after a restart to see it.

vhdx is not show in that list

**Comment by leonidasthe300** [comment]
> > Yes, you can run
> > `wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions`
> > and check the states of the disks after a restart to see it.
> 
> vhdx is not show in that list

Yes, the same happens here. Even if the disk is not mounted, we get the message `access denied`. I uploaded the logs with the 2 scenarios.

**Comment by SquallATF** [comment]
I found the reason for wsl return access denied. if the vhd is created under the user profile directory , the vhd owner is `BUILTIN\Administrators` and access is `NT AUTHORITY\SYSTEM`. But if  the vhd is created outsise the user profile directory,  the vhd access will changed to `BUILTIN\Administrators`, then `wsl --mount --vhd` will get `access denied`. when make a copy of that vhd the owner will changed to local user and mount will succeed.

![image](https://user-images.githubusercontent.com/1386803/159625416-ec189003-30d0-4c5d-9508-c77102d46e26.png)

![image](https://user-images.githubusercontent.com/1386803/159625185-2de70e56-6820-42cb-9ab5-7b5c34e33f44.png)

After fix vhd acl, the vhd can be mounted successfully.

**Comment by leonidasthe300** [comment]
> I found the reason for wsl return access denied. if the vhd is created under the user profile directory , the vhd owner is `BUILTIN\Administrators` and access is `NT AUTHORITY\SYSTEM`. But if the vhd is created outside the user profile directory, the vhd access will changed to `BUILTIN\Administrators`, then `wsl --mount --vhd` will get `access denied`. when make a copy of that vhd the owner will changed to local user and mount will succeed.
> 
> ![image](https://user-images.githubusercontent.com/1386803/159625416-ec189003-30d0-4c5d-9508-c77102d46e26.png)
> 
> ![image](https://user-images.githubusercontent.com/1386803/159625185-2de70e56-6820-42cb-9ab5-7b5c34e33f44.png)
> 
> After fix vhd acl, the vhd can be mounted successfully.

I just checked th ACL on the vhdx files like you said. 

But my vhdx files always are created and kept outside user profile directory. 

I tried New-VHD and the Disk Manager for creating the files, both creates it with the same ACL.

I wonder, isn´t the original ACL the correct way? Should we really changed it? For now, it works.

**Comment by SquallATF** [comment]
> 
> I just checked th ACL on the vhdx files like you said.
> 
> But my vhdx files always are created and kept outside user profile directory.
> 
> I tried New-VHD and the Disk Manager for creating the files, both creates it with the same ACL.
> 
> I wonder, isn´t the original ACL the correct way? Should we really changed it? For now, it works.

There is a small mistake in the previous explanation, the local user has access rights to the vhdx created in the user profile directory but does not have access rights to the vhdx created outside the user profile directory.
![图片](https://user-images.githubusercontent.com/1386803/160239869-a07ac4d0-6155-4e03-838c-23d321bcf9dd.png)
![图片](https://user-images.githubusercontent.com/1386803/160239912-f38f38da-0587-4f96-b490-e4806f5f0309.png)

**Comment by OneBlue** [comment]
Thanks for reporting this @[SquallATF](https://github.com/SquallATF).

Looking at the logs, WSL is getting access denied when trying to attach the disk to the VM, which shows that the ACL on the file don't allow full control the user.

Closing since this is by-design (WSL can't bypass the filesystem ACL when mounting vhd's).
