### ISSUE TITLE
wsl2 can not excute "systemctl daemon-reload" command

### ISSUE THREAD

**Issue by remainfox** [microsoft/WSL#8167]
In order to update the docker image source in wsl2, I ran the following command
```shell
systemctl daemon-reload
```
but an error was reported, the error message is as follows
```shell
System has not been booted with systemd as init System (PID 1). Can't operate.  
```
Try service daemon-reload, it won't work either  

## wsl version
```shell
NAME            STATE           VERSION
Ubuntu-18.04    Running         2
```
------------------
System Information
------------------
      Time of this report: 3/18/2022, 16:57:10
             Machine name: PC
         Operating System: Windows 10  64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
      System Manufacturer: LENOVO
             System Model: 81Q5
                     BIOS: BHCN35WW (type: UEFI)
                Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16304MB RAM
                Page File: 22187MB used, 3155MB available

**Comment by elsaco** [comment]
@remainfox `systemd` is not supported on WSL at this time. There are hacks to enable it, but YMMV.

**Comment by remainfox** [comment]
ok

**Comment by tobiillz** [comment]
Is there a way to run the daemon reload service on WSL?

I successfully installed the Daemon-reload service but on running the below in the terminal, i get "unrecognized service"

               $ sudo service daemon-reload
