### ISSUE TITLE
Access \\wsl$ or \\wsl.localhost$ in Explorer, Explorer is not responding

### ISSUE THREAD

**Issue by SunJun8** [microsoft/WSL#8170]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

linux-msft-wsl-5.10.93.2

### Distro Version

Debian

### Other Software

- explore.exe for windows 11
> Not sure if it has something to do with these softwares, but I'm using them
- Windows Terminal 1.11.3471.0
- usbipd-win 2.1.0
- vscode windows 1.65

### Repro Steps

> I'm not sure if this problem occurs on every device, but it happens on both thinkbook14 (4800u) and (5800u)

1. Fresh install win11
2. Install Windows Subsystem for Linux Preview from the Microsoft Store. (At this point you already have the wsl2 kernel and wslg)
3. Install debian in microsoft store
4. Install usbip via winget (lastest version)
5. May need to connect a usb device to wsl or open a wsl GUI program
6. wait (maybe)
7. Access \\wsl$ or \\wsl.localhost$ in Explorer

### Expected Behavior

Open the root directory of wsl

### Actual Behavior

Explorer is not responding

**Comment by SunJun8** [comment]
Any attempt to access \\wsl$\debian, including
- explore.exe .
- \\wsl$ or \\wsl.localhost$
- ...

will cause Explore noresponding

**Comment by lewisgauss** [comment]
I am experiencing the exact same problem. 

Additionally, when this is happening, any attempt to do `git push` or `code .` will yield no response. It just keeps running forever.

**Comment by SunJun8** [comment]
@FDCTLC 
For me it seems to be related to adding \\wsl.localhost\distribution to quick access

**Comment by SunJun8** [comment]
@lewisgauss 
For me, git is still working fine, only affects windows access to wsl paths

**Comment by lewisgauss** [comment]
@SunJun8 Is your Git in WSL2 setup to use Git Credential Manager from your Windows host?

**Comment by SunJun8** [comment]
> @SunJun8 Is your Git in WSL2 setup to use Git Credential Manager from your Windows host?

nope

**Comment by lewisgauss** [comment]
> > @SunJun8 Is your Git in WSL2 setup to use Git Credential Manager from your Windows host?
> 
> 
> 
> nope

You've confirmed my suspicions then, seems like for whatever reason, the connection between the host and WSL2 becomes lost, randomly. Or at least I've not seen a pattern yet...

**Comment by FDCTLC** [comment]
> > > @SunJun8 Is your Git in WSL2 setup to use Git Credential Manager from your Windows host?
> > 
> > 
> > nope
> 
> You've confirmed my suspicions then, seems like for whatever reason, the connection between the host and WSL2 becomes lost, randomly. Or at least I've not seen a pattern yet...

For the moment I have the same feeling. 
The connection is lost randomly but with some relation with programming activities (visual studio code with WSL or visual studio [professional] with remote compilation)

**Comment by SunJun8** [comment]
hey buddy i found a way to reproduce：
Add \wsl.localhost\distribution to "library"

**Comment by benhillis** [comment]
We have recently resolved a few issues that would explain the hang when accessing `\\wsl.localhost`, a new version of the Store package will have the fix, but a few of the issues are in the Windows OS so an upcoming Insider build will have the fixes for those.

**Comment by danchitnis** [comment]
@benhillis Is the update propagating to insider Beta as well since now both versions of Beta and Dev are matching? The recent Store update of the WSL kernel seems to freeze more than the previous version.

**Comment by kissgyorgy** [comment]
I have the exact same problem after installing the Microsoft Store version of WSL 2 and running the `wsl.exe --update` command. It is working for a couple of minutes after reboot, then everything is inaccessible, commands like `wsl --status` or wsl --shutdown` doesn't work.

I'm on Windows Insider Program Beta Channel, the above mentioned fixes are not included in it yet.
Output of `wsl --status` command:
```
Default Distribution: Ubuntu
Default Version: 2
WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22581.200
```

Having a Quick access shortcut to a WSL folder, OR accessing the WSL filesystem from Windows (e.g. clicking on the Linux\Ubuntu folder in the sidebar) OR starting VS Code seems to be instantly freezing WSL and from that point on, I can't interact with it in any way.

Any recommended workarounds until it get fixed?

**Comment by danchitnis** [comment]
I might have found a workaround if you are using VS code. Connect to WSL via VS Code's remote connection. Use the left-hand tree view to browse folders and files. if you want to access a file in WSL, right-click and "Download" the file to the Windows file system. At the moment `explorer.exe` is very buggy beyond the WSL issue and it is freezing for many reasons.

**Comment by benhillis** [comment]
@oaklandcorp-jkaiser - the fix will be contained in 0.58.0 of the WSL store package which is going through test passes currently and (if everything goes well) will be available later this week.

**Comment by oaklandcorp-jkaiser** [comment]
That's great news! Thank you for the insight.

**Comment by azzazkhan** [comment]
Still facing this issue, this is the biggest issue that makes WSL undependable. In the middle of my work WSL stops and I have to shut down the WSL manually using `wsl --shutdown` due to which all my active processes and Docker containers get terminated.

**Comment by OneBlue** [comment]
@azzazkhan: Can you please share dumps when you hit this issue ? 

/dumps
