### ISSUE TITLE
can't setup cuda for wsl pytorch

### ISSUE THREAD

**Issue by rzsgrt** [microsoft/WSL#8174]
Here's detail about my laptop  
1. Microsoft Windows [Version 10.0.19043.1586]
2. WSL version 2
3. Kernel version: Linux version 5.10.16.3-microsoft-standard-WSL2 
4. Ubuntu 20..04

I follow this tutorial [enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda](https://ubuntu.com/tutorials/enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda-platform#community)[](https://user-images.githubusercontent.com/47804549/159137819-55c570c2-3454-4db8-96fb-3110a2902a61.png) . I carefully follow all step until I try to compile sample application. After successfully run `sudo make` then I execute `./deviceQuery` But there's error says:

```bash

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
``` 
Here i show my driver and cuda version.

![image](https://user-images.githubusercontent.com/47804549/159137907-b81dc93e-ea0a-4b25-a2dc-650eae3a0ecd.png)

I also try to install torch via pip and test if torch detect gpu and it says False. Any idea what i need to do?
Thanks

**Comment by elsaco** [comment]
@rzsgrt here's a quick test, from https://github.com/chathhorn/cuda-semantics/blob/master/examples/

```
#include <cuda.h>
#include <stdio.h>

int main(int argc, char** argv) {
      int driver_version = 0, runtime_version = 0;

      cudaDriverGetVersion(&driver_version);
      cudaRuntimeGetVersion(&runtime_version);

      printf("Driver Version: %d\n"
             "Runtime Version: %d\n",
             driver_version, runtime_version);

      return 0;
}
```

Build the above code with `nvcc` and it will output driver and runtime versions. Sample output on my WSL setup:

```
tux@RIPPER:~/test$ nvcc -o getVersion getVersion.cu 
tux@RIPPER:~/test$ ./getVersion 
Driver Version: 11040
Runtime Version: 10010
```

If it doesn't compile, try `nvcc --version` to find info about your CUDA setup.

**Comment by rzsgrt** [comment]
Hi, thanks for the answer, unfortunately `nvcc --version` return me `Command 'nvcc' not found`. But i already run `sudo apt-get -y install cuda-toolkit-11-4` Is there any thing I miss here?  
Output from `update-alternatives --display cuda`:  
```
cuda - auto mode
  link best version is /usr/local/cuda-11.4
  link currently points to /usr/local/cuda-11.4
  link cuda is /usr/local/cuda
/usr/local/cuda-11.4 - priority 114
```

Output from `update-alternatives --list cuda`:
```
/usr/local/cuda-11.4
```

**Comment by Krish-sysadmin** [comment]
@rzsgrt Hey! Please add this to the end of your .bashrc file

``` 
export PATH="/usr/local/cuda-11.4/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.4/lib64:$LD_LIBRARY_PATH"
```

and open and close the terminal and run ``nvcc --version``. Does that fix the issue for you?

**Comment by rzsgrt** [comment]
> export PATH="/usr/local/cuda-11.4/bin:$PATH"
> export LD_LIBRARY_PATH="/usr/local/cuda-11.4/lib64:$LD_LIBRARY_PATH"

Yes, thats fix my `nvcc not found issue`. Thanks a lot!
Now I'll try suggestion from elsaco

**Comment by rzsgrt** [comment]
> @rzsgrt here's a quick test, from https://github.com/chathhorn/cuda-semantics/blob/master/examples/
> 
> ```
> #include <cuda.h>
> #include <stdio.h>
> 
> int main(int argc, char** argv) {
>       int driver_version = 0, runtime_version = 0;
> 
>       cudaDriverGetVersion(&driver_version);
>       cudaRuntimeGetVersion(&runtime_version);
> 
>       printf("Driver Version: %d\n"
>              "Runtime Version: %d\n",
>              driver_version, runtime_version);
> 
>       return 0;
> }
> ```
> 
> Build the above code with `nvcc` and it will output driver and runtime versions. Sample output on my WSL setup:
> 
> ```
> tux@RIPPER:~/test$ nvcc -o getVersion getVersion.cu 
> tux@RIPPER:~/test$ ./getVersion 
> Driver Version: 11040
> Runtime Version: 10010
> ```
> 
> If it doesn't compile, try `nvcc --version` to find some info about your CUDA setup. Also, try `update-alternatives --display cuda` and `update-alternatives --list cuda`.

Done run that code and get
```
Driver version: 0
Runtime version: 0
```
Not sure what happen here, but since I can execute `nvidia-smi.exe` the driver already installed right?

**Comment by Krish-sysadmin** [comment]
@rzsgrt Run the command ``nvidia-smi`` and share the output please

**Comment by rzsgrt** [comment]
> @rzsgrt Run the command `nvidia-smi` and share the output please

So, if run `nvidia-smi` i got 
``` 
Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```
But if i use `nvidia-smi.exe` It return
```
NVIDIA-SMI 511.79  
Driver Version: 511.79  
CUDA Version: 11.6
```

**Comment by Krish-sysadmin** [comment]
dmesg command will help in this case. You will be able to see the detailed error printed by nvidia-smi

**Comment by rzsgrt** [comment]
> dmesg command will help in this case. You will be able to see the detailed error printed by nvidia-smi

I saw several red text line. I'll copy here:
```
PCI: Fatal: No config space access function found 
kvm: no hardware support
hv_utils: cannot register PTP clock: 0

FS-Cache: Duplicate cookie detected
FS-Cache: O-cookie c=00000000f81159a4 [p=00000000e59cd572 fl=222 nc=0 na=1]
FS-Cache: O-cookie d=000000003fdc1949 n=000000006d49e0c1
FS-Cache: O-key=[10] '34323934393337353930'
FS-Cache: N-cookie c=0000000061676bb5 [p=00000000e59cd572 fl=2 nc=0 na=1]
FS-Cache: N-cookie d=000000003fdc1949 n=000000002a60e60e
FS-Cache: N-key=[10] '34323934393337353930'
FS-Cache: Duplicate cookie detected
FS-Cache: O-cookie c=0000000029b001ab [p=00000000e59cd572 fl=222 nc=0 na=1]
FS-Cache: O-cookie d=000000003fdc1949 n=00000000d9ebe410
FS-Cache: O-key=[10] '34323934393337363131'
FS-Cache: N-cookie c=0000000006e023ce [p=00000000e59cd572 fl=2 nc=0 na=1]
FS-Cache: N-cookie d=000000003fdc1949 n=0000000024463b1e
FS-Cache: N-key=[10] '34323934393337363131'
init: (1) WARNING: /etc/resolv.conf updating disabled in /etc/wsl.conf
init: (1) WARNING: /etc/resolv.conf updating disabled in /etc/wsl.conf
```

**Comment by Krish-sysadmin** [comment]
Try this: ``wsl --shutdown``

**Comment by rzsgrt** [comment]
> Try this: `wsl --shutdown`

So I need to shutdown my wsl?

**Comment by Krish-sysadmin** [comment]
Yes

**Comment by rzsgrt** [comment]
So if I shut my wsl, and check `nvidia-smi` through powershell, I get same result as if I run `nvidia-smi.exe` through wsl.

**Comment by elsaco** [comment]
To run Linux binaries inside a PowerShell session use `wsl nvidia-smi` for the default distro, otherwise use the `-d` flag, i.e. `wsl -d Ubuntu nvidia-smi`. 

Sample run, locating `nvidia-smi`:

```
PS C:\Users\tux> wsl which nvidia-smi
/usr/lib/wsl/lib/nvidia-smi
```

**Comment by rzsgrt** [comment]
> 

I got same error if I use wsl -d ubuntu nvidia-smi. 
if I run `wsl which nvidia-smi` I got same result with you

**Comment by rzsgrt** [comment]
Do you guys have any idea what happen? Because I feel just throwing any cli command here

**Comment by Krish-sysadmin** [comment]
Yes, I do now after testing a few things on my machine. Run ``dpkg -l | grep cuda-toolkit`` to find out the cuda toolkit version installed within the Linux environment

**Comment by elsaco** [comment]
There are two `nvidia-smi` binaries. One is an ELF  executable that runs on Linux and one is a PE executable that runs on Windows only:

```
tux@RIPPER:~$ file /usr/lib/wsl/lib/nvidia-smi
/usr/lib/wsl/lib/nvidia-smi: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped

tux@RIPPER:~$ file /c/Windows/system32/nvidia-smi.exe
/c/Windows/system32/nvidia-smi.exe: PE32+ executable (console) x86-64, for MS Windows

```

If you run `nvidia-smi` inside a PS session, the Windows version will be executed. To run the Linux version in a PS session use `wsl nvidia-smi` command, or run it inside a WSL session. The header will display the same driver information, however the processes will be different depending on the OS.

**Comment by rzsgrt** [comment]
> There are two `nvidia-smi` binaries. One is an ELF executable that runs on Linux and one is a PE executable that runs on Windows only:
> 
> ```
> tux@RIPPER:~$ file /usr/lib/wsl/lib/nvidia-smi
> /usr/lib/wsl/lib/nvidia-smi: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
> 
> tux@RIPPER:~$ file /c/Windows/system32/nvidia-smi.exe
> /c/Windows/system32/nvidia-smi.exe: PE32+ executable (console) x86-64, for MS Windows
> ```
> 
> If you run `nvidia-smi` inside a PS session, the Windows version will be executed. To run the Linux version in a PS session use `wsl nvidia-smi` command, or run it inside a WSL session. The header will display the same driver information, however the processes will be different depending on the OS.
> 
> Since you're using a DEB based Linux distro, look at `http://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/` and pick one CUDA package that works for you. Set this link as a repo and use `apt` to install/remove CUDA packages. It will take care of all dependencies for you.

But I can't access `wsl nvidia-smi`, got error
```
Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```
So it seems I only have `nvidia-smi` windows version and wsl can't access my gpu.

**Comment by elsaco** [comment]
On Windows, open `C:\Windows\System32\lxss\lib` and see what libraries are there. The Linux version of NVIDIA System Management Interface (nvidia-smi) should be there also. This folder is exported to WSL instances and mounted under `/usr/lib/wsl/`.

This is how it looks on my workstation:
```
PS C:\Windows\System32\lxss\lib> ls

    Directory: C:\Windows\System32\lxss\lib

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           3/17/2022  9:33 AM         137240 libcuda.so
-a---           3/17/2022  9:33 AM         137240 libcuda.so.1
-a---           3/17/2022  9:33 AM         137240 libcuda.so.1.1
-a---           9/15/2021  7:33 AM         828840 libd3d12.so
-a---           9/15/2021  7:33 AM        4834848 libd3d12core.so
-a---           9/15/2021  7:33 AM         878768 libdxcore.so
-a---           3/17/2022  9:33 AM        5864608 libnvcuvid.so
-a---           3/17/2022  9:33 AM        5864608 libnvcuvid.so.1
-a---           3/17/2022  9:33 AM       35512144 libnvdxdlkernels.so
-a---           3/17/2022  9:33 AM         424400 libnvidia-encode.so
-a---           3/17/2022  9:33 AM         424400 libnvidia-encode.so.1
-a---           3/17/2022  9:33 AM         207360 libnvidia-ml.so.1
-a---           3/17/2022  9:33 AM         354768 libnvidia-opticalflow.so
-a---           3/17/2022  9:33 AM         354768 libnvidia-opticalflow.so.1
-a---           3/17/2022  9:33 AM       45922856 libnvwgf2umx.so
-a---           3/17/2022  9:33 AM         690808 nvidia-smi
```

**Comment by rzsgrt** [comment]
> On Windows, open `C:\Windows\System32\lxss\lib` and see what libraries are there. The Linux version of NVIDIA System Management Interface (nvidia-smi) should be there also. This folder is exported to WSL instances and mounted under `/usr/lib/wsl/`.
> 
> This is how it looks on my workstation:
> 
> ```
> PS C:\Windows\System32\lxss\lib> ls
> 
>     Directory: C:\Windows\System32\lxss\lib
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---           3/17/2022  9:33 AM         137240 libcuda.so
> -a---           3/17/2022  9:33 AM         137240 libcuda.so.1
> -a---           3/17/2022  9:33 AM         137240 libcuda.so.1.1
> -a---           9/15/2021  7:33 AM         828840 libd3d12.so
> -a---           9/15/2021  7:33 AM        4834848 libd3d12core.so
> -a---           9/15/2021  7:33 AM         878768 libdxcore.so
> -a---           3/17/2022  9:33 AM        5864608 libnvcuvid.so
> -a---           3/17/2022  9:33 AM        5864608 libnvcuvid.so.1
> -a---           3/17/2022  9:33 AM       35512144 libnvdxdlkernels.so
> -a---           3/17/2022  9:33 AM         424400 libnvidia-encode.so
> -a---           3/17/2022  9:33 AM         424400 libnvidia-encode.so.1
> -a---           3/17/2022  9:33 AM         207360 libnvidia-ml.so.1
> -a---           3/17/2022  9:33 AM         354768 libnvidia-opticalflow.so
> -a---           3/17/2022  9:33 AM         354768 libnvidia-opticalflow.so.1
> -a---           3/17/2022  9:33 AM       45922856 libnvwgf2umx.so
> -a---           3/17/2022  9:33 AM         690808 nvidia-smi
> ```

Mine looks similar with your result 
```
    Directory: C:\Windows\System32\lxss\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/17/2022  11:33 PM         137240 libcuda.so
-a----         3/17/2022  11:33 PM         137240 libcuda.so.1
-a----         3/17/2022  11:33 PM         137240 libcuda.so.1.1
-a----         10/2/2021   1:46 PM         828840 libd3d12.so
-a----         10/2/2021   1:46 PM        4834848 libd3d12core.so
-a----         10/2/2021   1:46 PM         878768 libdxcore.so
-a----         3/17/2022  11:33 PM        5864608 libnvcuvid.so
-a----         3/17/2022  11:33 PM        5864608 libnvcuvid.so.1
-a----         1/11/2022   6:54 AM       35512144 libnvdxdlkernels.so
-a----         3/17/2022  11:33 PM         424400 libnvidia-encode.so
-a----         3/17/2022  11:33 PM         424400 libnvidia-encode.so.1
-a----         1/28/2022   6:28 PM         207360 libnvidia-ml.so.1
-a----         3/17/2022  11:33 PM         354768 libnvidia-opticalflow.so
-a----         3/17/2022  11:33 PM         354768 libnvidia-opticalflow.so.1
-a----         3/17/2022  11:33 PM       45922856 libnvwgf2umx.so
-a----         3/17/2022  11:33 PM         690808 nvidia-smi
```

**Comment by Krish-sysadmin** [comment]
@rzsgrt What did  ``dpkg -l | grep cuda-toolkit`` output?

**Comment by rzsgrt** [comment]
> @rzsgrt What did `dpkg -l | grep cuda-toolkit` output?

Oh this is the output
```
ii  cuda-toolkit-11-0                       11.0.3-1                           amd64        CUDA Toolkit 11.0 meta-package
ii  cuda-toolkit-11-4                       11.4.4-1                           amd64        CUDA Toolkit 11.4 meta-package
ii  cuda-toolkit-11-4-config-common         11.4.148-1                         all          Common config package for CUDA Toolkit 11.4.
ii  cuda-toolkit-11-config-common           11.6.55-1                          all          Common config package for CUDA Toolkit 11.
ii  cuda-toolkit-config-common              11.6.55-1                          all          Common config package for CUDA Toolkit.
```

**Comment by Krish-sysadmin** [comment]
@rzsgrt It seems you have a version mismatch. Install cuda 11.6. 

```
wget https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda_11.6.2_510.47.03_linux.run
sudo sh cuda_11.6.2_510.47.03_linux.run
```

**Comment by rzsgrt** [comment]
> @rzsgrt It seems you have a version mismatch. Install cuda 11.6.
> 
> ```
> wget https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda_11.6.2_510.47.03_linux.run
> sudo sh cuda_11.6.2_510.47.03_linux.run
> ```

Previously I use cuda 11.6. I use 11.4 because I'm following tensorflow guide.

**Comment by Krish-sysadmin** [comment]
Tensorflow should work with 11.6 perfectly. Use it. Don't follow any guide blindly as you will never know their exact setup

**Comment by Krish-sysadmin** [comment]
```
sudo apt-get --purge remove "*cublas*" "cuda*" "nsight*" 
sudo rm -rf /usr/local/cuda*
sudo /usr/local/cuda-*/bin/cuda-uninstaller 
sudo apt-get update 
```

**Comment by rzsgrt** [comment]
> ```
> sudo apt-get --purge remove "*cublas*" "cuda*" "nsight*" 
> sudo rm -rf /usr/local/cuda*
> sudo /usr/local/cuda-*/bin/cuda-uninstaller 
> sudo apt-get update 
> ```

Thank you so much @Krish-sysadmin

**Comment by rzsgrt** [comment]
So now I can use `nvidia-smi` on my wsl but it show no running process and neither pytorch nor tf detect gpu 
 
![image](https://user-images.githubusercontent.com/47804549/162363261-3b2c9e89-b408-4890-81ea-5f7747e3c549.png)

**Comment by Krish-sysadmin** [comment]
You need to install the Pytorch and TensorFlow with GPU support. And there are no running processes since this is WSL but on a regular Linux box, you would see the graphical server for example Xorg

**Comment by elsaco** [comment]
@rzsgrt `nvidia-smi` does show running Linux GUIs. Here's sample `xterm` using `Xwayland` and `wslg`. Notice I'm running the same driver version, so `pytorch` and `tensorflow` should run fine on your setup, too:

![nvidia-smi_xwayland](https://user-images.githubusercontent.com/3933920/162593496-b827209b-7bd3-43d3-82ed-528c5a373caf.png)

**Comment by rzsgrt** [comment]
> You need to install the Pytorch and TensorFlow with GPU support. And there are no running processes since this is WSL but on a regular Linux box, you would see the graphical server for example Xorg

yes I already install pytorch and tensorflow with gpu support

**Comment by Krish-sysadmin** [comment]
"You will need to be on Windows 11 Build 22000 or higher to access this feature" - @rzsgrt is using Windows 10. Graphical apps won't work

**Comment by Krish-sysadmin** [comment]
@elsaco

**Comment by elsaco** [comment]
@Krish-sysadmin `nvidia-smi` works the same on Win10 WSL, however since there's no `wslg` for Win10 a display server needs to be provided. I'm using `VcXsrv` for Linux GUIs.

Sample ouput running `firefox` browser:

![win10_Xorg_firefox](https://user-images.githubusercontent.com/3933920/162638452-61df0728-0ba4-42fe-afd3-eb8d544f132d.png)

Notice that X is not on the process list. It is shown by `nvidia-smi.exe` since it's a Windows process.

**Comment by Krish-sysadmin** [comment]
Hey, yes I do understand that. The thing though is that @rzsgrt probably hasn't set an X server and are not running an app, thus nothing would show as running on the NVIDIA GPU

**Comment by rzsgrt** [comment]
I saw this exact same problem in this so question [here](https://stackoverflow.com/questions/70808339/the-host-has-cuda-and-gpu-installed-but-pytorch-wsl2-cannot-find-it). And its solve by downgrading nvidia version. I think i'm gonna try that and if still fail I'll sell my laptop 🤣

**Comment by elsaco** [comment]
@rzsgrt don't sell the notebook! Wipe Windows and install Linux. Your CUDA woes will disappear, and the Linux experience will be much better compared to WSL.

**Comment by rzsgrt** [comment]
> @rzsgrt don't sell the notebook! Wipe Windows and install Linux. Your CUDA woes will disappear, and the Linux experience will be much better compared to WSL.

yeah,i already did that (dual boot ubuntu) after buy this laptop and my wifi not detected. some source say its wifi hardware and ubuntu kernel problem(mine mediatek). But maybe i should  try another ubuntu version, maybe 21.04

**Comment by Krish-sysadmin** [comment]
Just install fedora. Less pain and works very well out of the box. Best Linux distribution in my opinion and obviously much better than Windows

**Comment by Krish-sysadmin** [comment]
And Mediatek wifi cards have a bad history of working with Linux (and sometimes Windows). Like the new ASUS ROG laptops also have them and so many users even on Windows have issues with them. Swap it out for an Intel wifi card

**Comment by rzsgrt** [comment]
> Just install fedora. Less pain and works very well out of the box. Best Linux distribution in my opinion and obviously much better than Windows
well any linux better than windows 😅 

> And Mediatek wifi cards have a bad history of working with Linux (and sometimes Windows). Like the new ASUS ROG laptops also have them and so many users even on Windows have issues with them. Swap it out for an Intel wifi card

yeah i'm also thinking about this.

**Comment by Krish-sysadmin** [comment]
Yeah, my friends using Windows with Mediatek hate it

- https://www.reddit.com/r/ZephyrusG14/comments/q97mxx/fix_zephyrus_g14_wifi_issues_mediatek_card/
- https://www.reddit.com/r/ZephyrusG14/comments/ohsox6/mediatek_mt7921_suddenly_not_working/
- https://www.reddit.com/r/LenovoLegion/comments/q3237p/if_your_lenovo_legion_5_pro_with_a_mediatek/
- https://www.reddit.com/r/LenovoLegion/comments/tchaqg/l5p_mediatek_wifi_card_not_recognized_at_all/

these issues on Windows. Imagine how many issues are on Linux with a wifi card (Mediatek) that barely contributes anything and is a bad card in general. (However, the kernel version 5.17.2 seems to have fixed all these issues - for now). Intel wifi cards however are perfect for Windows and Linux and they actively contribute to the kernel as well

**Comment by 52hpfans** [comment]
> I saw this exact same problem in this so question [here](https://stackoverflow.com/questions/70808339/the-host-has-cuda-and-gpu-installed-but-pytorch-wsl2-cannot-find-it). And its solve by downgrading nvidia version. I think i'm gonna try that and if still fail I'll sell my laptop 🤣

Could you pass the test in this link? [https://docs.nvidia.com/cuda/wsl-user-guide/index.html#ch03a-setting-up-cuda](url) Once you can pass the test, that means the CUDA in your WSL2 is correctly installed. Then maybe you can try my method in this answer [https://stackoverflow.com/a/71877189/18806648](url)

**Comment by rzsgrt** [comment]
woah

> > I saw this exact same problem in this so question [here](https://stackoverflow.com/questions/70808339/the-host-has-cuda-and-gpu-installed-but-pytorch-wsl2-cannot-find-it). And its solve by downgrading nvidia version. I think i'm gonna try that and if still fail I'll sell my laptop 🤣
> 
> Could you pass the test in [this link](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#ch03a-setting-up-cuda)? Once you can pass the test, that means the CUDA in your WSL2 is correctly installed. Then maybe you can try my method in [this answer ](https://stackoverflow.com/a/71877189/18806648).
> 
> Moreover, Nvidia has said that `nvidia-smi` in WSL2 does not support showing the running process. So what you have encountered is normal.

![image](https://user-images.githubusercontent.com/47804549/164892366-d6590360-225c-4e7c-aadc-11860ae3e22b.png)


woahhhhhhh thank you guys for your help especially @52hpfans. that linking method solve my problem. so I keep my laptop for now 😄

**Comment by jistiak** [comment]
> @rzsgrt Hey! Please add this to the end of your .bashrc file
> 
> ```
> export PATH="/usr/local/cuda-11.4/bin:$PATH"
> export LD_LIBRARY_PATH="/usr/local/cuda-11.4/lib64:$LD_LIBRARY_PATH"
> ```
> 
> and open and close the terminal and run `nvcc --version`. Does that fix the issue for you?

Hi! Thanks for this tips!

Adding this to the end of .bashrc file solves the problem of not being able to find cuda, but brings in more errors as it cannot find the conda path anymore. Is there any way to use cuda within anaconda virtual envs within WSL2?
