### ISSUE TITLE
error after loading a nvidia docker container 

### ISSUE THREAD

**Issue by abdessamad-abid** [microsoft/WSL#8182]
### Version

Microsoft Windows [Version 10.0.19044.1620]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Docker 20.10.13
nvidia driver Version: 511.65

### Repro Steps

sudo docker load -i ubuntu_opencv.tar

sudo docker run --runtime=nvidia -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all ubuntu_opencv ./DeepSortTest

### Expected Behavior

the app runs succesfully

### Actual Behavior

terminate called after throwing an instance of 'cv::dnn::cuda4dnn::csl::CUDAException'                                    
what():  OpenCV(4.5.4) /home/Downloads/opencv-4.5.4/modules/dnn/src/cuda4dnn/csl/memory.hpp:54: error: (-217:Gpu API call) no CUDA-capable device is detected in function 'ManagedPtr'

**Comment by craigloewen-msft** [comment]
Please try re-running this command with `--gpus=all` as an added argument to the command you're running above. Like so:

`sudo docker run --runtime=nvidia --gpus=all -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all ubuntu_opencv ./DeepSortTest`

**Comment by abdessamad-abid** [comment]
> Please try re-running this command with `--gpus=all` as an added argument to the command you're running above. Like so:
> 
> `sudo docker run --runtime=nvidia --gpus=all -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all ubuntu_opencv ./DeepSortTest`
> 
> And let us know what the results are from this!
