### ISSUE TITLE
"Installation package is not supported by this processor type" error when running wsl --update

### ISSUE THREAD

**Issue by pdrgnclvs** [microsoft/WSL#8184]
### Version

Microsoft Windows [Version 10.0.19044.1620]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Simply check for updates
2. Windows Update reports an update for Windows Subsystem for Linux (kernel 5.10.93.2)

### Expected Behavior

The installation should go smoothly (I don't think it would pose a problem)

### Actual Behavior

The installation halts with error 0x80070661, and doing wsl --update through Command Line as a workaround yields the "Installation package is not supported by this processor type" message

**Comment by inf1nityhhd** [comment]
I have encountered the same problem when am tring to upgrade WSL on my ryzen laptop. (AMD 5800H cpu).

**Comment by danny-burrows** [comment]
I also have the same issue attemping the update on an intel processor running Windows 11

**Comment by ravik694** [comment]
Seeing the same issue on my own system running Windows 11 Pro.

### Version

```
cmd.exe /c ver
Microsoft Windows [Version 10.0.22000.556]
```

### WSL Version

```
wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```

### Kernel Version

```
 wsl.exe --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 2022-03-11
WSL automatic updates are on.

Kernel version: 5.10.60.1
```

### Repro Steps

- Run `wsl --update` as admin in Windows Terminal.

### Expected Behavior

WSL is upgraded to the newest version. Currently this is `5.10.93.2` according to Windows Update.

### Actual Behavior

```
 wsl --update
Checking for updates...
Downloading updates...
Installing updates...
This installation package is not supported by this processor type. Contact your product vendor.
```

Diagnostic Logs

**Comment by NoahELE** [comment]
got the same problem with my intel processor laptop with Windows 11

**Comment by Garphy** [comment]
same err this morning...
windows update fail 0x80070661

**Comment by elsaco** [comment]
Here's a quick workaround:

- download latest WSL2 release from https://github.com/microsoft/WSL/releases/download/0.56.2/Microsoft.WSL_0.56.2.0_x64_ARM64.msixbundle
-  rename file to `Microsoft.WSL_0.56.2.0_x64_ARM64.zip`
- run `Expand-Archive Microsoft.WSL_0.56.2.0_x64_ARM64.zip`
- change into `Microsoft.WSL_0.56.2.0_x64_ARM64` folder
- run `Add-AppPackage Microsoft.WSL_0.56.2.0_x64.misx`
- run `wsl --status` to check the upgrade

It should show `WSL version: 0.56.2.0` This workaround ...worked on my  Win11 notebook!

**Comment by kahennig** [comment]
Same here... wsl is working fine but the update package fails to install. 
It fails both trying to update via Windows Update as well as with:
`wsl --update`

**Comment by 4x0v7** [comment]
Also experiencing this:
Win 10 19044.1586
Intel Core i7 1165G7

**Comment by joeloguete** [comment]
run Add-AppPackage Microsoft.WSL_0.56.2.0_x64.misx  should be
run Add-AppPackage Microsoft.WSL_0.56.2.0_x64.msix

**Comment by jackgallivan** [comment]
I had the same issue. After I updated Windows to release 22581.1 (Beta Insider channel), the WSL kernel update disappeared from windows update, but "wsl --update" worked again and updated WSL from 5.10.60.1 to 5.10.102.1.

**Comment by pcbeard** [comment]
I installed the workaround, and wsl --update does tell me that I have the latest. However, Windows update is still showing the error `Install error - 0x80070661`. I'm hoping this will get fixed on the Microsoft side.

**Comment by shubhamsethi97** [comment]
Facing the same issue with my Intel processor laptop with Windows 10.

**Comment by yongzhang** [comment]
the issue happens today

**Comment by erbanku** [comment]
> Same here... wsl is working fine but the update package fails to install. It fails both trying to update via Windows Update as well as with: `wsl --update` this is what it looks like:
> 
> ❯ wsl --update Checking for updates... Downloading updates... Installing updates... This installation package is not supported by this processor type. Contact your product vendor.
> 
> and on windows update:
> 
> ![Screenshot 2022-03-24 224605](https://user-images.githubusercontent.com/3522117/160038430-fac05d75-9202-4f0c-977e-ba1c402fe4ad.png)

### Same here.
![image](https://user-images.githubusercontent.com/79493862/160053004-6f577ea9-9b5d-418a-87fd-754ec36a2c90.png)

**Comment by markstachowski** [comment]
I see the same errors and waiting for a fix.

**Comment by d2kx** [comment]
Same here. Windows Update error, Windows 11 Stable, Surface Laptop Studio.

**Comment by aguther** [comment]
Same for me, Windows 11 Stable:
![image](https://user-images.githubusercontent.com/6629914/160061762-9f1b3ade-93ff-4aae-8422-192edc642323.png)

**Comment by favefan** [comment]
Same issue on Windows 10 pro with AMD R7 5800H processor.

**Comment by pcaversaccio** [comment]
same on Windows 11
![image](https://user-images.githubusercontent.com/25297591/160077163-b3c28169-0548-45a1-83fa-e3ce5afbeb98.png)

![image](https://user-images.githubusercontent.com/25297591/160077126-a33e9bcf-9b99-47ea-a029-f16c71a05840.png)

**Comment by woxihuanjia** [comment]
same for me !maybe a mistake of microsoft.

**Comment by Alexey71** [comment]
1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
2. Unpuck `xxxxxxxx.cab` file
3. Install `wsl_update_x64.msi`

**Comment by marcorotondi** [comment]
> 1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> 2. Unpuck `xxxxxxxx.cab` file
> 3. Install `wsl_update_x64.msi`

Confirm that workaround is a valid solution!

**Comment by pdrgnclvs** [comment]
As @marcorotondi already confirmed, the workaround provided by @Alexey71 works wonders 🙏

Based on this, we can assume that Windows Update is incorrectly trying to install the ARM64 binary on the X64 platform; that's kind of weird since there should be some sort of check in place to make sure that Windows Update only installs updates for that specific Windows architecture 🤔

Anyway, thanks to @Alexey71 and everyone else who gave a workaround 👏

I could close the issue, but I'm going to wait for someone high above us to give some sort of an explanation to what happened 🤨

**Comment by markstachowski** [comment]
@pdrgnclvs who can we git blame 😆 - but in all seriousness thank you guys for finding a quick workaround. Happy Friday!

**Comment by cr08** [comment]
Also seeing this on a Ryzen 7 5800X running Windows 11. Error code `0x80070661` in Windows Update.

```
wsl --update
Checking for updates...
Downloading updates...
Installing updates...
This installation package is not supported by this processor type. Contact your product vendor.
```

Can confirm the workaround above took care of it though. Cheers!

**Comment by elsaco** [comment]
The `wsl_update_x64.msi` from https://www.catalog.update.microsoft.com/Search.aspx?q=wsl has two files inside, the license and a Linux kernel:

```
PS C:\Catalog\wsl_update_x64> ls


    Directory: C:\Catalog\wsl_update_x64


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/31/2022   8:33 PM          19292 FID_LICENSE
-a----         1/31/2022   8:34 PM       43301584 FID_LXSS_KERNEL
```

The kernel is version is `5.10.93.2-microsoft-standard-WSL2 #1 SMP Wed Jan 26 22:38:54 UTC 2022` It boots fine, but it's an older kernel.

**Comment by pdrgnclvs** [comment]
And now it's doing the same thing with version 5.10.102.1, the most recent, meaning that a new version of the kernel is available but still being incorrectly applied architecture-wise 🤔

![WSL_FAIL](https://user-images.githubusercontent.com/46295920/160169061-31c7b116-9659-4f24-959a-b863a7517517.gif)

Thankfully, repeating @Alexey71's workaround, it gets fixed once again 🙏

**Comment by CodesauceOverflow** [comment]
> 1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> 2. Unpuck `xxxxxxxx.cab` file
> 3. Install `wsl_update_x64.msi`

How do you upack? I try at command line Expand-Archive ("Operation stopped"), and when going inside the .cab file i see the msi file but only get option to "Extract" when right-clicking on the msi file but then destination file does not show anything or just don't know where to extract it to (file- not folder) and I don't get any option to simply extract the contents of the .cab file through the windows Explorer..

**Comment by Alexey71** [comment]
> How do you upack? I try at command line Expand-Archive ("Operation stopped"), and when going inside the .cab file i see the msi file but only get option to "Extract" when right-clicking on the msi file but then destination file does not show anything or just don't know where to extract it to (file- not folder) and I don't get any option to simply extract the contents of the .cab file through the windows Explorer..

`Winrar` or `7z` no problem. U can rename `.cab` to `.zip` and open

**Comment by arencambre** [comment]
The update just now worked, and it didn't downgrade my kernel.

**Comment by d2kx** [comment]
> And now it's doing the same thing with version 5.10.102.1, the most recent, meaning that a new version of the kernel is available but still being incorrectly applied architecture-wise 🤔

Can't confirm. The new 5.10.102.1 has updated successfully for me through Windows Update on both of my systems.

**Comment by pdrgnclvs** [comment]
> > And now it's doing the same thing with version 5.10.102.1, the most recent, meaning that a new version of the kernel is available but still being incorrectly applied architecture-wise 🤔
> 
> Can't confirm. The new 5.10.102.1 has updated successfully for me through Windows Update on both of my systems.

Because since my last message and now maybe someone at Microsoft fixed the problem on their side 😉

**Comment by CodesauceOverflow** [comment]
Thank you. I had tried all the renaming and unpacking options on that .cab file and none worked, and tried changing it to .exe file and windows couldn’t run it. When attempting to unpack, it seemed to show a windowsbase file or something. Lost the screen. I’m running Acer Nitro5 with intel cpu, 32gb ram (crucial), windows 11 pro, 1TB +265 gb ssd storage.
BUT!!

Regular windows update just went through and updated it.

Thank you all for your replies.. people are quick on this stuff lol. Love it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alexey71** [comment]
I uninstall `Windows Subsystem for Linux Update`
And try `wsl --update`. No error, MS fixed poblem

**Comment by Hananel-Hazan** [comment]
It seems the issue as been corrected. I just refresh windows update and it installed without a issue. I had the same issue couple of hours ego, I didnt apply the workaround, waited for Microsoft fix, so it arrived it seems.

(win 10 10.0.19044.1620)

**Comment by pdrgnclvs** [comment]
> It seems the bug in the WSL update as been corrected. I just refreshed windows update and the update been downloaded and installed without a problem. 
> I had the same issue couple of hours ago, I didn't apply the workaround, waited for Microsoft official fix, so it arrived it seems.
> 
> (win 10 10.0.19044.1620)

Yes, it's been fixed since around 5PM-6PM (GMT) so it shouldn't pose a problem again 😉

**Comment by Nigh02** [comment]
> Here's a quick workaround:
> 
> * download latest WSL2 release from https://github.com/microsoft/WSL/releases/download/0.56.2/Microsoft.WSL_0.56.2.0_x64_ARM64.msixbundle
> * rename file to `Microsoft.WSL_0.56.2.0_x64_ARM64.zip`
> * run `Expand-Archive Microsoft.WSL_0.56.2.0_x64_ARM64.zip`
> * change into `Microsoft.WSL_0.56.2.0_x64_ARM64` folder
> * run `Add-AppPackage Microsoft.WSL_0.56.2.0_x64.msix` - thanks [@joeloguete](https://github.com/joeloguete)
> * run `wsl --status` to check the upgrade
> 
> It should show `WSL version: 0.56.2.0` This workaround ...worked on my Win11 notebook!
> 
> When running `wsl --update` it should output `The most recent version of Windows Subsystem for Linux is already installed`

PS C:\Windows\system32> wsl --status
Default Version: 2

The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl.exe --update'.
PS C:\Windows\system32> wsl.exe --update
Checking for updates...
Downloading updates...
Installing updates...
This installation package is not supported by this processor type. Contact your product vendor.
PS C:\Windows\system32> wsl --update
Checking for updates...
Downloading updates...
Installing updates...
This installation package is not supported by this processor type. Contact your product vendor.
