### ISSUE TITLE
Failed to install update 5.10.93.2

### ISSUE THREAD

**Issue by totsukasaika** [microsoft/WSL#8186]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- WSL 2

### Kernel Version

5.10.60.1

### Other

CPU: Intel Celeron N3350

### Repro Steps

Windows Update: Windows Subsystem for Linux Update - 5.10.93.2
or
wsl --update

### Expected Behavior

Update successful.

### Actual Behavior

I executed the "wsl --update" command.

Then it appears:
>Installation packages are not supported for this processor type. Please contact your product supplier.

However, Windows Update pushed the update 5.10.93.2 to me.

**Comment by KokoKan** [comment]
I have the same problem, but i don't really know how to fix it

**Comment by artur-ag** [comment]
Duplicate of #8184. Let's check that issue instead for when a fix is available.

**Comment by jmwoods301** [comment]
The logs in <username>/AppData/Local/Temp show it's trying to download and install "wsl_update_arm64.msi" on x64 machines.

**Comment by gatoroto** [comment]
Same problem for me. When I run `wsl --update` command the error is: _This installation package is not supported by this processor type. Contact your product vendor._

**Comment by totsukasaika** [comment]
This update can be hidden using *wushowhide.diagcab*.

**Comment by Alexey71** [comment]
1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
2. Unpuck `xxxxxxxx.cab` file
3. Install `wsl_update_x64.msi`

**Comment by jmwoods301** [comment]
You'll get a warning that the .cab file can't be downloaded safely, because it's using http instead of https in the URL.

Copy and modify the link to use https, and it downloads with no issues.

It's a workaround, but the correct file needs to be downloaded for x64 systems.

**Comment by totsukasaika** [comment]
Download link:
http://download.windowsupdate.com/d/msdownload/update/software/updt/2022/03/wsl_update_x64_2c7a964320d5e3f70a6d39827b1f8a672dbbf507.cab

Please verify the digital signature.

**Comment by mattish91** [comment]
> 1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> 2. Unpuck `xxxxxxxx.cab` file
> 3. Install `wsl_update_x64.msi`

This solves the issue perfectly well. As others mention, Windows Update tries to install the WSL ARM64 update on x64 machines, which doesn't work for obvious reasons. Hopefully does Microsoft sort this issue before it gets too wide spread during the next few days.

**Comment by benhillis** [comment]
I fixed this earlier today, let me know if you're still having issues.

**Comment by benhillis** [comment]
Sorry about this, the filter to offer the correct processor architecture binary got dropped from the update somehow - working on putting some checks in place to make sure this doesn't happen agian.

**Comment by Samix10ds** [comment]
> 1. Windows Subsystem for Linux Update - 5.10.93.2

it tells me that i dont have wsl installed when i do

**Comment by DoctorWho8** [comment]
> > 1. Windows Subsystem for Linux Update - 5.10.93.2
> 
> it tells me that i dont have wsl installed when i do

Hello!
Isn't that the kernel version whatever you're using runs around?

**Comment by bwilliamsrmf** [comment]
> 1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> 2. Unpuck `xxxxxxxx.cab` file
> 3. Install `wsl_update_x64.msi`

Absolute legend right here. Works for 5.10.102.1 as well!

**Comment by TheWhiteAmbit** [comment]
This also happened to me and the solution worked. MS needs to put back in place some quality control! This bug is becoming 4 years old.

**Comment by solusops** [comment]
> > 1. Download latest `Windows Subsystem for Linux Update - 5.10.93.2`  https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
> > 2. Unpuck `xxxxxxxx.cab` file
> > 3. Install `wsl_update_x64.msi`
> 
> Absolute legend right here. Works for 5.10.102.1 as well!

Yes, yes it does!
