### ISSUE TITLE
usbipd: error: WSL 'usbip' client not correctly installed.

### ISSUE THREAD

**Issue by xiaolongba** [microsoft/WSL#8192]
### Version

Microsoft Windows [Version 10.0.19042.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

 Ubuntu-20.04

### Other Software

Docker Desktop windows 4.6.1 

### Repro Steps

1. I followed the instructions from the [Connect USB devices](https://docs.microsoft.com/en-us/windows/wsl/connect-usb)
2. when I execute the step 2 of [attach a USB device section](https://docs.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device), it showed me the following error info:
```c
PS C:\WINDOWS\system32> usbipd wsl attach --busid=8-1
usbipd: error: WSL 'usbip' client not correctly installed. See https://github.com/dorssel/usbipd-win/wiki/WSL-support for the latest instructions.
```

### Expected Behavior

the USB device can be attached successfully

### Actual Behavior

when I execute the step 2 of [attach a USB device section](https://docs.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device), it showed me the following error info:
```c
PS C:\WINDOWS\system32> usbipd wsl attach --busid=8-1
usbipd: error: WSL 'usbip' client not correctly installed. See https://github.com/dorssel/usbipd-win/wiki/WSL-support for the latest instructions.
```

**Comment by elsaco** [comment]
@xiaolongba you need to have `usbipd` running inside WSL also. As root type `usbipd -D` to run in daemon mode.

When attaching a USB device in Windows, follow the system messages in WSL with `dmesg -w` to see when a device is connected/disconnected. It helps with troubleshooting. 

Sample messages on WSL Ubuntu when attaching a USB flash drive on host:

```
[  349.678522] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(3)
[  349.679506] vhci_hcd vhci_hcd.0: devid(131075) speed(3) speed_str(high-speed)
[  349.680550] vhci_hcd vhci_hcd.0: Device attached
[  350.024845] usb 1-1: new high-speed USB device number 2 using vhci_hcd
[  350.194837] usb 1-1: SetAddress Request (2) to port 0
[  350.235431] usb 1-1: New USB device found, idVendor=154b, idProduct=00ee, bcdDevice= 1.00
[  350.236656] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  350.237294] usb 1-1: Product: USB 2.0 FD
[  350.237537] usb 1-1: Manufacturer: PNY
[  350.237783] usb 1-1: SerialNumber: 071916C5042ACB65 
```

**Comment by xiaolongba** [comment]
pls close this ticket, I have resolved it already, the details pls refer to [here](https://github.com/dorssel/usbipd-win/issues/251#issuecomment-1079961293)
