### ISSUE TITLE
WSL1 Ubuntu distribution disappeared after Windows 10 update

### ISSUE THREAD

**Issue by em-ex** [microsoft/WSL#8196]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [x] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1237-Microsoft Sat Sep 11 14:32:00 PST 2021

### Distro Version

Ubuntu 16.04

### Repro Steps

1. Install WSL1 via Optional Features with Ubuntu in 2017
2. Deal with issues installing Windows 10 updates years later, trying to go from 20H2 to something newer (mostly because IKE2 VPN suddenly stopped working)
	- Use external drive due to low disk space
4. Witness something go wrong with the updates (like getting stuck at 0% after reboot for 5 hours). Update finishes, `winver` is reporting version 2004
	- VPN still doesn't work, but also WSL is now broken, saying "**no installed distributions**"
6. Download Windows 10 Update Assistant to finally get to 21H2. Everything seems to work fine except for WSL

### Expected Behavior

Running `bash.exe` opens terminal ("classic", not the new one from Store) with my Ubuntu installation which is still preserved in `%LocalAppData%\lxss\`

### Actual Behavior

Running `bash.exe` shows message:
```
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```
---

I know this is not advised, but out of curiosity I tried registering the distribution by creating a key in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\` (there were no keys there after updates). This allowed me to access my instance of Ubuntu but without access to my /home/user directory.

I don't really need WSL2 for my daily needs, I just want to have access to my legacy Ubuntu via WSL1 with my rootfs and home directories properly mounted.

**Comment by em-ex** [comment]
Solved by re-registering the distribution directory using https://github.com/DDoSolitary/LxRunOffline/ (the only difference between this new registration and my manually created one — `Version` is now set to 0, while I was trying 1)

**Comment by lawliet89** [comment]
Steps:

- Find your WSL files in "C:\Users\USER\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_<some UUID>\LocalState"
- Do `LxRunOffline.exe rg -n "Ubuntu" -d ""C:\Users\USER\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_<some UUID>\LocalState"`


You will get your WSL installation back, but it will default to UID 0 (root).

- Do `LxRunOffline.exe su -n Ubuntu -v 1000`
