### ISSUE TITLE
"Access is denied" message when importing disks

### ISSUE THREAD

**Issue by shaneboulden** [microsoft/WSL#8197]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Fedora

### Repro Steps

I've downloaded a Fedora rootfs, from https://kojipkgs.fedoraproject.org/packages/Fedora-Container-Base/36/20220326.n.0/images/, and unpacked the rootfs tar-ball. 

When I attempt to import it, I receive the following error:
```
 PS c:\> wsl.exe --import Fedora-36 c:\WSL\Fedora $HOME\Downloads\fedora-36-rootfs.tar
Access is denied.
```

### Expected Behavior

The Fedora filesystem is successfully imported into WSL

### Actual Behavior

An "Access is denied" message is displayed

**Comment by Biswa96** [comment]
That file looks like a Docker image which contains extra files including rootfs. This is what I did in my Windows 10 machine.

1. Download [Fedora-Container-Base-36-20220326.n.0.x86_64.tar.xz](https://kojipkgs.fedoraproject.org/packages/Fedora-Container-Base/36/20220326.n.0/images/Fedora-Container-Base-36-20220326.n.0.x86_64.tar.xz) file.
2. Extract it with `tar -xf` command.
3. There will be a layer.tar file in a folder with random number.
4. Install that layer.tar with `wsl --import` command.

**Comment by shaneboulden** [comment]
Ah, you're exactly right. That worked, thanks!
