### ISSUE TITLE
"semop(1): encountered an error: Function not implemented" in fakeroot under qemu

### ISSUE THREAD

**Issue by mforkel** [microsoft/WSL#8198]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Debian 11 (Bullseye)

### Other Software

[libc-bin 2.31-13+deb11u2](https://packages.debian.org/bullseye/libc-bin)
[qemu-user-static 1:5.2+dfsg-11+deb11u1](https://packages.debian.org/bullseye/qemu-user-static)
[fakeroot 1.25.3-1.1](https://packages.debian.org/bullseye/fakeroot)
[pbuilder 0.231](https://packages.debian.org/bullseye/pbuilder)

### Repro Steps

I build packages for armhf on an am64 host with pbuilder and qemu (qemu-user-static). This works in the Debian distro (both with Buster and Bullseye) for packages for Raspbian Buster. But it fails when I try to build packages for RPi OS Bullseye with
```
$ DIST=rpi-bullseye pdebuild
...
dpkg-buildpackage: info: host architecture armhf
 fakeroot debian/rules clean
semop(1): encountered an error: Function not implemented
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 1
```
I do not encounter that problem with the same pbuilder configuration in a regular installation of Debian Bullseye. A problem resulting in the same error was [fixed in qemu 1:5.0-9](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965109).

### Expected Behavior

No error in fakeroot

### Actual Behavior

Error in fakeroot

**Comment by 0x000000FF** [comment]
I got the same error when I try to build the example image，did you solved the problem？How did you do ?thanks

**Comment by Biswa96** [comment]
Is it possible to use WSL2 instead?

**Comment by mforkel** [comment]
Sorry for the late reply

>did you solved the problem？How did you do ?

Unfortunately, I didn't solve it

> Is it possible to use WSL2 instead?

I got the same error with WSL 2 and Debian Bullseye (versions at the time I tested: pbuilder 0.231, fakeroot 1.25.3-1.1, qemu-user-static 1:5.2+dfsg-11+deb11u1 and libc-bin 2.31-13+deb11u2)
