### ISSUE TITLE
docker service doesn't auto-start

### ISSUE THREAD

**Issue by JoeHCQ1** [microsoft/WSL#8207]
### Version

Microsoft Windows [Version 10.0.19043.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04 LTS

### Repro Steps

Given brand new Ubuntu install with user created:

**Install docker:**

```bash
# Per https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions remove any old versions of docker
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

# Add docker repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

# Note, unsurprisingly, that docker isn't running:
service docker status

# Start it and then run docker to verify install:
sudo service docker start
sudo docker run hello-world  # ignoring adding user to docker group for now
```

**Restart computer**

Note that docker isn't running automatically but must be manually started:

```bash
service docker status
```

First work-around, I attempted to add it to the startup services:

```bash
# add docker to auto start: https://askubuntu.com/questions/9382/how-can-i-configure-a-service-to-run-at-startup
sudo update-rc.d docker defaults
sudo updated-rc.d docker enable
```

**Restart computer**

Note that docker still isn't running automatically but must be manually started:

```bash
service docker status
sudo service docker start
```

### Expected Behavior

Docker would run automatically when system starts the way it always has when I run Ubuntu as my main OS.

### Actual Behavior

Docker is never running until you tell it to via:

```bash
sudo service docker start
```

**Note:** there is a `systemctl` version of that command but that fails because `System has not been booted with systemd as init system (PID 1).`. I wonder if this change in PID numbers from normal Ubuntu/Linux may also be why the fix in **Retro Steps** failed and why docker doesn't automatically run on startup like it normally would in my prior experience on linux only laptops.

**Comment by OneBlue** [comment]
Closing since this is not a WSL issue.

I'd recommending creating this issue on https://github.com/docker/for-win/issues
