### ISSUE TITLE
WSL 5.10.102.1 access from Windows Explorer seems to freeze

### ISSUE THREAD

**Issue by zejal** [microsoft/WSL#8211]
### Version

Microsoft Windows [version 10.0.22581.200]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Distro Version

Release:        21.10

### Repro Steps

Simply open Windows Explorer and click on Linux entry in left side.

### Expected Behavior

Display Linux root directory.

### Actual Behavior

Windows Explorer or other exe referring to WSL seem to freeze.

**Comment by zejal** [comment]
It's very annoying issue, as it makes use of Emacs or other editors on windows to reliably edit files on WSL distro. 
Is there any way to revert the wsl update please? Thanks

**Comment by longfield-tech** [comment]
Not the author but I have the same issue.
Added logs via feedback hub. Thank you for your help 😊

WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22581.200
Linux distro: Ubuntu 20.04

**Comment by zejal** [comment]
Thanks a lot.

**Comment by leonardok** [comment]
I seem to be having the same issue. using rubymine with wsl project everything freezes. in explorer it doesnt load my ubuntu filesystem.

```
wsl --version
WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.593
```

**Comment by benhillis** [comment]
@longfield-tech - I agree, likely the same as the issue you linked.

**Comment by mmalack** [comment]
For me, the problems occur in connection with DDEV.
When I start DDEV (Docker Desktop), it doesn't take long before I can no longer access the file system.

If I don't use DDEV (Docker), then it seems to run.
