### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070057

### ISSUE THREAD

**Issue by scyto** [microsoft/WSL#8216]
### Version

Microsoft Windows [Version 10.0.22581.100]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian using wsl --install Debian

### Other Software

None

### Repro Steps

uninstall wsl prview from store

open command line and run wsl --install
then run wsl --install Debian

get
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...
```

### Expected Behavior

Debain should install just fine.

### Actual Behavior

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...
```

### Diagnostic Logs

https://aka.ms/AAgk6ot

**Comment by scyto** [comment]
and local logs just incase hub didnt collect what was needed
[wsl.zip](https://github.com/microsoft/WSL/files/8393404/wsl.zip)

**Comment by scyto** [comment]
issue also present after upgrade today to Microsoft Windows [Version 10.0.22581.200]

**Comment by scyto** [comment]
roll back to Microsoft Windows [Version 10.0.22579.100] did not fix - get "file not found" when dsitro attempts to install

**Comment by scyto** [comment]
Then i did 
```
C:\Windows\System32>wsl --update
Installing: Windows Subsystem for Linux
```
resulting in
```
C:\Windows\System32>wsl --status
Default Distribution: docker-desktop
Default Version: 2
WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22581.200
```
Debian stayed working.
So uninstalled Debian from ARP settings/

and tried to reinstall
```
C:\Windows\System32>wsl --install debian
Installing: Debian GNU/Linux
An error occurred during installation. Distribution Name: 'Debian GNU/Linux': An error occurred while deleting the package's previously existing application data.
```
Ran install command again, it appeared to complete the download and now says this when bootstraping the Debian configuration.

```
The system cannot find the file specified.

Press any key to continue...
```
Methinks this version of WSL preview is borked.

**Comment by scyto** [comment]
confirmed, uninstalling WSL preview and re-installing the Debian distro worked

**Comment by scyto** [comment]
still broken

Default Version: 2
WSL version: 0.58.1.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22598.100

**Comment by scyto** [comment]
Uninstalling preview.
Installing kernel update from here https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi 
Then installing debian from command line works

```
STUDY\C:\Users\alex> wsl --status
Default Distribution: Debian
Default Version: 2

Windows Subsystem for Linux was last updated on 4/18/2022
WSL automatic updates are on.

Kernel version: 5.10.16
```

**Comment by scyto** [comment]
then a wsl --update breaks the install

this is utterly borked IMHO

**Comment by OneBlue** [comment]
Thanks for reporting this @scyto. In the logs I can see:

```
VmSwitch not found: 'wsl-switch'
```

Do you have a vmswitch configured in .wslconfig ? If so it looks like this switch doesn't exists

**Comment by scyto** [comment]
@OneBlue thanks, interesting, at the time the logs were created the switch existed in the hyper-v switch manager
when i was tearing down networking and other things at the weekend i got weird errors trying to edit that switch and in the end did a full netsh network stack reset and removing the switch

i just recreated the switch and now all is goo

1.) i think something broken the hyper-v switch (i have noticed that the hyper-v network infrastructure can get very freaked out by build to build upgrades - i have other comments in other threads - last time i had a repro of a upgrade / longhaul break i ping craig but he never replied (more than willing to let someone do a remote dbg).  I think this caused the initial issue as it was in the UI - but apparently borked under the hood.

2. maybe improving the returned error message would help - in this scenario if it had said 'switch foo' doesn't exist - i would have recreated....

I can close this as fixed - next time i have a general longhaul break in the network stack (like when DNS fails in WSL) should i ping someone?

**Comment by scyto** [comment]
oh @OneBlue And TBH having a switch like this is essential given the default behaviour of wsl2.... https://blog.alexbal.com/ 
:-)  when will this be the default behaviour - proper bridging?

**Comment by OneBlue** [comment]
Bridge networking in WSL is still very experimental (and not even officially released), but right now we have no plans to make bridged the default network mode

**Comment by Atams777** [comment]
I know this is flagged as closed, but it's the top google hit for this issue for 2022. I just ran into this issue because of a network adapter on my computer. I ended up disabling the adapter installing Ubuntu and then enabling the adapter, and I was able to get things up and going. If someone else runs into this issue make sure you don't have any non-standard adapters enabled.

**Comment by beingmerry** [comment]
Seeing this error and not sure how to fix.  Windows 11 build 25905 WSL2 Ubuntu

**Comment by OneBlue** [comment]
> Seeing this error and not sure how to fix. Windows 11 build 25905 WSL2 Ubuntu

This is caused by a Hyper-V bug that made it to Windows insider builds. Either downgrading to an older build or waiting for the next update should solve the issue.

**Comment by bjmageto** [comment]
@OneBlue I re-installed Windows to get rid of the issue...it was probably time for a refresh anyways! Wish I would have though of trying to downgrade the insider edition first though 😅
