### ISSUE TITLE
WslRegisterDistribution failed with error: 0xe000020b

### ISSUE THREAD

**Issue by saykin** [microsoft/WSL#8220]
### Version

Microsoft Windows [Version 10.0.19042.1586]

### WSL Version

- [ ] WSL 2
- [x] WSL 1

### Kernel Version

5.10.102.1

### Repro Steps

Unsure of how this happened, I'm working off a VDI. I am the only one getting this issue at the moment and support doesn't know why. I've tried installing the Ubuntu distro on the MS Store and it gives me this error:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xe000020b
Error: 0xe000020b (null)
Press any key to continue...

![image](https://user-images.githubusercontent.com/8566744/161266959-51fbc3b7-9019-4732-b961-1be3ece42d5b.png)

### Expected Behavior

I was expecting it to install and run just fine like it did on my local machine. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/8566744/161267097-ca69acf9-2a11-4d75-be75-37c042cfcd9b.png)

I found another ticket with the same error, I tried following the steps he listed to fix it, but that didn't work for me.

**Comment by saykin** [comment]
I can't seem to open the feedback hub and github won't let me upload the .etl file that's mentioned in the last step of how to attack a log link the bot gave me.

**Comment by onomatopellan** [comment]
Another user had same problem and solved it resetting the networking adapters. See https://github.com/microsoft/WSL/issues/6089

**Comment by onomatopellan** [comment]
@saykin If resetting the network adapters didn't work you can upload your .etl file to your gist and post a link here.

**Comment by onomatopellan** [comment]
@saykin If resetting the network adapters didn't work you can upload your .etl file renaming it to `.txt` first.

**Comment by OneBlue** [comment]
If feedback hub doesn't work for you, can you follow the [Records logs manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) section and share the log file ?

**Comment by rllames** [comment]
Does anyone able to resolve this 0xe000020b error? I have the same error when installing version 20 and 22 of WSL.

**Comment by Swaz002** [comment]
I'm still experiencing the same issue

**Comment by KubeDevMax** [comment]
I'm also experiencing the same issue.
