### ISSUE TITLE
Line-Breaks 'Break' when using multiple commands.

### ISSUE THREAD

**Issue by sadigaxund** [microsoft/WSL#8221]
### Version

Microsoft Windows [Version 10.0.19042.1586]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.4.0

### Distro Version

Ubuntu 20.04.4 LTS

### Repro Steps

Run following command:
`sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -`

Then hit 'enter' key(or enter incorrect password) until it stops prompting. And that's it, it breaks.

### Expected Behavior

After doing aforementioned steps, it should've displayed line breaks whenever I hit 'enter'.

### Actual Behavior

![image](https://user-images.githubusercontent.com/48419889/161268670-742cbb07-a053-4b73-b1ab-283805b382ba.png)

**Comment by elsaco** [comment]
@sadigaxund I run your test on Ubuntu 20.04 and WSL2. You're using WSL1, but that shouldn't matter. Here is the output after six failed sudo attempts when the command terminates and drops to shell prompt:

```
tux@RIPPER:~$ sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
[sudo] password for tux:
Sorry, try again.
[sudo] password for tux:
Sorry, try again.
[sudo] password for tux:
sudo: 3 incorrect password attempts
[sudo] password for tux:
Sorry, try again.
[sudo] password for tux:
Sorry, try again.
[sudo] password for tux:
sudo: 3 incorrect password attempts
tux@RIPPER:~$ ls
GitHub  backup  dot.config  helix  test       tmp1  tmp3  tmp5          wsl-5.10.93.2
attic   cuda    download    temp   text1.txt  tmp2  tmp4  unicode_test  wsl_kernels.txt
tux@RIPPER:~$ echo $SHELL
/bin/bash
tux@RIPPER:~$
```

The shell used for testing was `bash`. What shell are you using? Thx!

**Comment by sadigaxund** [comment]
When I run `echo $SHELL` it returns `/bin/bash`.

**Comment by sadigaxund** [comment]
@elsaco I'm using `Windows Terminal` app by Microsoft utilizing `bash`. Now that you asked. I believe it is Microsoft's bug, is not it?
