### ISSUE TITLE
Clearer "help" Documentation

### ISSUE THREAD

**Issue by KerickHowlett** [microsoft/WSL#8222]
**Is your feature request related to a problem? Please describe.**
Is there a way to more explicitly label the shorthand flags, such as `-s` for `--set-default` as a flag alias?

I know it's a minor thing, but I spent far longer than I needed to on a WSL command that wasn't working, because, while attempting to set `Ubuntu-20.04` as my default dsitro, I read the `--help` documentaiton to mean the proper command to be:
```bash
wsl --set-default -s Ubuntu-20.04
```
I had thought `-s` was the flag used to select a specific distro, much in the same way you have to use `--distribution` or `-d` to select the specific distro/distribution to install with `wsl --install -d Ubuntu`.

I'm sure maybe people don't have this problem, but I figured there'd may be some with poor eyesight out there who may fail to see the separating comma like I did.

**Describe the solution you'd like**
I'd just simply label the shorthand flags as aliases.

For example:
```bash
---set-default <Distro>
    Sets the distribution as the default.
    Aliases: -s
```

I can understand this not being a high priority. I just figured it'd be a "nice to have" to provide a tad bit clearer documentation.

**Comment by Biswa96** [comment]
`wsl.exe --help` already shows this:

```
    --set-default, -s <Distro>
        Sets the distribution as the default.
```

Means `-s` (short option) is same as `--set-default` (long option). It is common format to specify short & long option for many command line tools. For example, `sed --help` has this:

```
  -s, --separate
                 consider files as separate rather than as a single,
                 continuous long stream.
```

**Comment by KerickHowlett** [comment]
I know it does and I'm aware it's common practice.

It's just sometimes, depending on the person's eyesight or the quality of their display, that comma can be hard to see.

I've seen the `aliases: ...` sections in a lot of Bash tools, which is something I really liked, and I thought there may be some people -- even if the count of total people is an, admittedly, tiny number -- may benefit from it.

But I'll admit, my suggestion is strongly opinionated and I may very well be the only person who thinks this, so I really have no qualms about closing this non-Issue.

**Comment by ariyawongkraso** [comment]
Reya wongkraso

**Comment by owenschupp** [comment]
@KerickHowlett could you link to an example of the `aliases: ...` section you are referring too?

**Comment by KerickHowlett** [comment]
Apologies, but I believe myself to have misremember that.

Totally my bad, and I apologize for wasting your time.

I'll just go ahead and close the ticket.
