### ISSUE TITLE
Latest update made WSL almost unusable.

### ISSUE THREAD

**Issue by nitanmarcel** [microsoft/WSL#8225]
### Version

Microsoft Windows [Version 10.0.22581.200]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Can't detect it. Wsl commands hung up

### Distro Version

Debian Bullseye but happens with any distro even the default one

### Repro Steps

Using wsl.exe from windows terminal hangs up. Wsl starts up just fine on boot but it has random crashes both terminal and GUI apps seem to randomly fail.

Latest crash that happened now left whole WSL unusable leaving this error behind when trying to open gui apps

![image](https://user-images.githubusercontent.com/41646249/161381032-f612330f-76df-4fb9-891b-3585c1a37ea2.png)

Running WSL from terminal or just start the distribution terminal hangs up.

![image](https://user-images.githubusercontent.com/41646249/161381057-2652872a-8821-472b-ab58-24b5f1fe1ba5.png)

![image](https://user-images.githubusercontent.com/41646249/161381062-f71e9faf-1726-44e4-b745-2cf13e70938d.png)

### Expected Behavior

Before the last updates everything was fine. After the latest wsl update and windows update wsl is buggy,

### Actual Behavior

Random crashes. Can't start wsl again.

### Diagnostic Logs

wsl.etl: https://transfer.sh/RbLKuJ/wsl.etl

**Comment by dbfx** [comment]
Seeing the exact same with Ubuntu

**Comment by OneBlue** [comment]
Hi @nitanmarcel, thanks for reporting this.

I'm not seeing anything in the logs, can you run wsl --shutdown, and capture logs again ? I'd like to see the VM instanciation logs.  

If you manage to get the machine in this 'stuck' state again, can you also share a dump of the wsl service host process ? 
To figure out which process it is, look for an svchost.exe with the following command line: `C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s LxssManager`
