### ISSUE TITLE
Docker in WSL from Store

### ISSUE THREAD

**Issue by muhammadsalmanafzal** [microsoft/WSL#8229]
**Is your feature request related to a problem? Please describe.**
Docker enables the WSL Optional Feature from Control Panel even if we have WSL Preview from Store installed.

**Describe the solution you'd like**
If WSL Preview from Store is installed, it should use that, and NOT the Optional Feature

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by benhillis** [comment]
Agreed, but this isn't the docker issue tracker :)
