### ISSUE TITLE
Can not find command `--export`.

### ISSUE THREAD

**Issue by EiEddie** [microsoft/WSL#8230]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

`wsl --export Ubuntu D:\wsl\ubuntu-20.04 wsl-ubuntu-20.04.tar`

### Expected Behavior

I want to see wsl **export** an archive.

### Actual Behavior

_It seems print all param..._

And I find this two param are **_exactly the same_**!!
I think the one below should be the command to export( `--export` ), BUT it is `--set-default-version <version>`.
Is this intentional?

![image](https://user-images.githubusercontent.com/55616830/161581230-b19b9fb5-b336-48d0-ac83-1e06b8860a3b.png)

**Comment by benhillis** [comment]
Nope, looks like a translation issue.

**Comment by OneBlue** [comment]
@craigloewen-msft  to help with the translation issue
