### ISSUE TITLE
Can't connect "ssh -p 29418 review.example.com" for gerrit ssh server

### ISSUE THREAD

**Issue by BruceChang08** [microsoft/WSL#8234]
### Version

Microsoft Windows [版本 10.0.22000.593] 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

ubuntu 18.04

### Repro Steps

when I try to connect gerrit client . It's can't connet for WSL2 ,but in general ubuntu can conect 
ubuntu cmd line
ssh -p 29418 username@xxxxgerritserver.com

can you help us to sovle this question 

### Expected Behavior

ubuntu cmd line
ssh -p 29418 username@xxxxgerritserver.com

**** welcome to gerrit code review ********

hi username ,you have successfully connected over ssh

### Actual Behavior

ubuntu cmd line
ssh -p 29418 username@xxxxgerritserver.com

ssh: connect to host username@xxxxgerritserver.com port 29418: Connection timed out

**Comment by OneBlue** [comment]
Thanks for reporting this @BruceChang08.

Can you share the output of ssh with the verbose (-v) parameter set so we get more output ?

**Comment by dannielrm** [comment]
Any news on that? I'm having the same issue.
