### ISSUE TITLE
Copying files inside a ZIP file on Windows to WSL2 by drag-and-drop is very slow

### ISSUE THREAD

**Issue by tueda** [microsoft/WSL#8235]
### Version

Microsoft Windows [Version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Prepare a ZIP file on the Windows file system, containing some files.
2. Open File Explorer for the ZIP file (without uncompressing) and also for a directory in the WSL2 file system (via `\\wsl$`).
3. Drag and drop some files inside the ZIP file to WSL2.

### Expected Behavior

Files should be copied instantly.

### Actual Behavior

Copying files takes more than 1 minute. Actually, the progress bar for copying files completely stops for, like, 70-100 seconds.

- I feel the timing is somewhat discretized (like some timeout??) but sometimes largely fluctuates, so unsure.
- Copying uncompressed files to WSL2 has no problem.
- Last month, I upgraded the PC's OS from Windows 10 to 11. Before that, I remember copying files inside ZIP files to the WSL2 system had no problem. So, I guess this was triggered by the upgrade or a recent update of the kernel, etc...

**Comment by OneBlue** [comment]
Thanks for reporting this Tueda.
This isn't something that we can fix since writing zip files through \\wsl$ will always be expensive.

Closing.

**Comment by tueda** [comment]
Thank you for your response. I am not writing a ZIP file; indeed reading it on Windows. But if you say copying a 0-byte file from a 113-bytes ZIP file takes 1 minute by design (or due to some complicated IO systems), that might be the case...

**Comment by matej-marcisovsky** [comment]
Why is this closed?

**Comment by blckmn** [comment]
This should not be closed the issue is very real: 

![image](https://user-images.githubusercontent.com/6168871/211174133-fd5e2e8e-6d53-488b-8d2f-fe1f01b04675.png)

46 files less than 10 meg in total... 45 minutes.

To replicate: take any zip file, open it in explorer. Copy contents to some location on \\wsl.local\...
