### ISSUE TITLE
Slow connection to anaconda servers 

### ISSUE THREAD

**Issue by ATpoint** [microsoft/WSL#8238]
### Version

Microsoft Windows [Version 10.0.22000.527]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

In WSL2 run:

```bash
#/ In "native" WSL2 via terminal this is somewhere at 5kb/s download
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh

#/ inside docker it works perfectly fine, downloads several Mb/s
docker pull continuumio/miniconda
docker run -it continuumio/miniconda:latest bash
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh
```

### Expected Behavior

Proper download with full bandwidth

### Actual Behavior

Specifically all downloads related to the anaconda servers are painfully slow, also anything via `conda install` is super slow (few kb/s). Downloads via same URL within Windows11 Pro or inside WSL2 via a Docker container are perfectly fine. It is only the anaconda URLs that cause trouble. I tried everything that one can find via google. Please suggest some systematic steps to debug.

**Comment by akuropka** [comment]
![20220407_213622_ubuntupreview](https://user-images.githubusercontent.com/22570574/162282705-12b199b0-574f-44e8-a4f6-0e262e5e1038.png)
(ann. line gives max. 100 mbit/s)

**Comment by ATpoint** [comment]
How do you think does this help me debugging? Nice that it works for you, for me it doesn't.

**Comment by elsaco** [comment]
@ATpoint if you have `curl` installed try downloading with it instead of `wget` and see if it makes any difference.  Also, if you have `ab` installed (the ApacheBench) try benchmarking `repo.anaconda.com`. This tool is part of `apache2-utils` package. It will show some good information about connection.

**Comment by akuropka** [comment]
@ATpoint, it helps you determining if it is a general problem of WSL or an individual one. Aside you’ve not given any information such as logs which helps the community to see what may be the issue in your case.

**Comment by ATpoint** [comment]
Tried curl, same result. Output of the `ab` benchmark:

```
atpoint@DESKTOP-O7JK99H:~$ ab -n 20 https://repo.anaconda.com/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking repo.anaconda.com (be patient).....done


Server Software:        cloudflare
Server Hostname:        repo.anaconda.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-ECDSA-CHACHA20-POLY1305,256,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        repo.anaconda.com

Document Path:          /
Document Length:        6250 bytes

Concurrency Level:      1
Time taken for tests:   10.376 seconds
Complete requests:      20
Failed requests:        0
Total transferred:      143744 bytes
HTML transferred:       125000 bytes
Requests per second:    1.93 [#/sec] (mean)
Time per request:       518.793 [ms] (mean)
Time per request:       518.793 [ms] (mean, across all concurrent requests)
Transfer rate:          13.53 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       49  178 109.8    256     311
Processing:    29  340 354.2    264    1561
Waiting:       20   28   6.8     29      42
Total:         89  519 384.6    357    1811

Percentage of the requests served within a certain time (ms)
  50%    357
  66%    541
  75%    582
  80%    751
  90%    990
  95%   1811
  98%   1811
  99%   1811
 100%   1811 (longest request)
```
Does that give any insights?
