### ISSUE TITLE
launching newly installed WSL fails - multiple computers - ( same corporation) - Faulting module name: ucrtbase.dll

### ISSUE THREAD

**Issue by sgutkinMadrid** [microsoft/WSL#8256]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

n/a - cannot get that far

### Distro Version

n/a - cannot get that far

### Repro Steps

Two individuals at the same corporation observe the same issue.    We use two different methods of installation:

Method 1:
1. dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
2. dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
3. reboot
4. WSL /install

Method 2:  
1. Docker for Windows
2. WSL /install
3. reboot
4. dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
5. dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
6. reboot
7. disable the features
8. reboot
3. dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
4. dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
5. then enable HypervisorPlatform, Microsoft-Hyper-V-All, Microsoft-Hyper-V, Microsoft-Hyper-V-Tools-All
 Microsoft-Hyper-V-Management-PowerShell, Microsoft-Hyper-V-Hypervisor, Microsoft-Hyper-V-Services,
Microsoft-Hyper-V-Management-Clients

### Expected Behavior

I expected a linux prompt or to be able to get information about wsl by typing wsl.exe --status

### Actual Behavior

Windows command prompt
```
C:\Users\sgutkin>wsl

C:\Users\sgutkin>
```

Windows Application Log

```
Faulting application name: wsl.exe, version: 10.0.19041.1566, time stamp: 0x3c6b46b2
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x4a4
Faulting application start time: 0x01d84b72e4bffa34
Faulting application path: C:\WINDOWS\system32\wsl.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 2273027f-8a51-4253-adb0-0c1a018274cf
Faulting package full name: 
Faulting package-relative application ID: 
```

### Diagnostic Logs

_No response
[wsl.etl.log](https://github.com/microsoft/WSL/files/8455877/wsl.etl.log)
_

**Comment by OneBlue** [comment]
Thanks for reporting this @sgutkinMadrid. 

Based on the logs, it looks like the WSL service is failing to start.

Can you share a screenshot of what 'optionalfeatures.exe' shows ? I'm wondering if some features failed to install

**Comment by sgutkinMadrid** [comment]
![image](https://user-images.githubusercontent.com/103285049/163066534-e2416587-01f8-4225-b7fe-918aa8dc4ad7.png)

**Comment by sgutkinMadrid** [comment]
![image](https://user-images.githubusercontent.com/103285049/163066656-38352c6f-cbfe-4f52-8de5-06c1e46da9d0.png)

**Comment by sgutkinMadrid** [comment]
Any updates ?

**Comment by OneBlue** [comment]
@sgutkinMadrid: Based on the logs it looks like something is preventing the wsl service from starting. I'm wondering if ones of its dependencies is disabled.

Can you share the output of `sc.exe query` so we can check if anything is disabled / missing ?

**Comment by sgutkinMadrid** [comment]
[ScExeQueryResults.txt](https://github.com/microsoft/WSL/files/8534942/ScExeQueryResults.txt)

Yes.  Also I added the Windows Feature "containers".

**Comment by OneBlue** [comment]
Thanks @sgutkinMadrid . Looking at the output I can see that `lxssmanager` isn't there, which is what's causing the error you're seeing.

When wsl is installed you should see an lxssmanager service looking like this:
```
sc query lxssmanager

SERVICE_NAME: lxssmanager
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
``` 

What happens if you disable the Windows subsystem for linux feature, reboot, then enabling it again and reboot again, does the service appear ?

**Comment by sgutkinMadrid** [comment]
I tried following the steps outlined.  Here is the result:

>sc query lxssmanager

SERVICE_NAME: lxssmanager
        TYPE               : 20  WIN32_SHARE_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

>net start lxssmanager
System error 1058 has occurred.

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

In the event logs I am still seeing this: 

Faulting application name: wsl.exe, version: 10.0.19041.1566, time stamp: 0x3c6b46b2
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0xb00
Faulting application start time: 0x01d855df45f29a1e
Faulting application path: C:\WINDOWS\system32\wsl.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 16e21b5e-6e1f-4939-b33d-fed29efe97a9
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sgutkinMadrid** [comment]
I am going to try to get my local access to the laptop OS promoted.   I am allocated admin access but only when I spawn processes through a command line prompt.  I am starting to suspect this is insufficient to launch docker.

**Comment by sgutkinMadrid** [comment]
I was able to start lxssmanager


C:\Users\sgutkin>sc query lxssmanager

SERVICE_NAME: lxssmanager
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by sgutkinMadrid** [comment]
Good news.  I was able to get wsl working enough to run Docker.  That was my goal.   The WSL prompt still exist immediately.. which is odd but docker runs.

**Comment by OneBlue** [comment]
Thank you @sgutkinMadrid. This is interesting. Can you run wsl distributions now ?

**Comment by sgutkinMadrid** [comment]
Sorry for the delayed response.  I was able to launch Docker Desktop which was my immediate goal.   I was not able to launch the WSL command line.  I see a number of issues in my Eventlog.  Some seem to indicate GPO / security issues.  I am going to try to examine the GPO on this laptop to see if that resolves the issue.
 
Faulting application name: wsl.exe, version: 10.0.19041.1566, time stamp: 0x3c6b46b2
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x6bf0
Faulting application start time: 0x01d85f1065f3cca9
Faulting application path: C:\WINDOWS\system32\wsl.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 6c6d1ca8-8c13-4736-8363-e2b729aab4b6
Faulting package full name: 
Faulting package-relative application ID: 

 
Could not get local Administrator account. Error 0x80070534.

**Comment by sgutkinMadrid** [comment]
FYI,  we are trying a 3rd engineer's laptop with a different mix of GPO .   I'll publish results later.

**Comment by timeichfeld-msa** [comment]
Hello,

Not sure how to re-open or assign a new related issue. (I don't want to lose the knowledge in this thread as it is related.)
We just had a recent Windows update:
Running Windows 10 [OS Build : 19044.2251]

Not seeing this on the upgrade/update, rather we are seeing this after the update running an in-house application.
We had not seen this error prior to Windows Update:

Faulting application name: ******************************
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x3754
Faulting application start time: 0x01d8faaaf85feff3
Faulting application path: ********************************
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: b56fdb9c-6b0a-4186-9d0e-73570b51c0d2
Faulting package full name: 
Faulting package-relative application ID: 

This happens in our release build, and while running our application in Visual Studio in Debug.
Application is written in WPF C#.
Crash shuts down the application, not trapped in the debugger. Only recorded in event log.
Please inform me how to trap this in the debugger to get you more information?

Possible issue is reproduced when we are rapidly changing our Viewports using SciChart API's in a multi-monitor configuration. 
Please advise on how to get more information that you need to address the issue?

Thanks much,
-Timothy
