### ISSUE TITLE
Any commands related to wsl suddenly stopped to work

### ISSUE THREAD

**Issue by GabrielBrandao13** [microsoft/WSL#8262]
### Version

Microsoft Windows [version 10.0.19043.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Any distro, actually

### Repro Steps

Just run any wsl command
For example `wsl` or `wsl --version`

### Expected Behavior

In the case of the first command(`wsl`), it should just start just like it used to do before(it suddenly stopped to work)

### Actual Behavior

The command just doesn't respond, just like it takes a eternity to start, but even waiting for more than 30 minutes, nothing happens

The following print screen show what happens if i run the command `wsl`, but it happens to any wsl command, even commands like `wsl --version`
![image](https://user-images.githubusercontent.com/62272513/162594965-eda99264-d2eb-42cc-ae93-ec73d693a315.png)

(The language is pt-br)

Seems there's nothing wrong, but i ran this command about 15 minutes ago.

**Comment by owenschupp** [comment]
Are you still experiencing this behavior? I would try `wsl --shutdown` and try to restart it.  You may also want to try restarting the WSL service (this example is in an elevated cmd window):

`sc stop wslservice`
`sc start wslservice`

If that doesn't work, please attach some logs! \logs
