### ISSUE TITLE
Failed to open KASAN

### ISSUE THREAD

**Issue by zidong6344** [microsoft/WSL#8264]
### Version

19043.1586

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.15.17

### Distro Version

Ubuntu 18.04

### Repro Steps

Using WSL2 .config compiles the kernel of 4.15
Add in. Config：
CONFIG_SLUB_DEBUG=y
CONFIG_KASAN=y
next：
make

### Expected Behavior

I think WSL is a good learning platform, but I want to be told how to turn on KASAN correctly when using my own kernel in WSL.

### Actual Behavior

/usr/src/linux-source-4.15.0$ sudo make -j16
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  DESCEND  objtool
  CHK     include/generated/utsrelease.h
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC [M]  ubuntu/xr-usb-serial/xr_usb_serial_common.o
  CHK     kernel/config_data.h
  CC [M]  ubuntu/vbox/vboxguest/common/log/log.o
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_ctrl_irq’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:301:21: warning: unused variable ‘tty’ [-Wunused-variable]
  struct tty_struct *tty;
                     ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_process_read_urb’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:433:24: warning: unused variable ‘tty’ [-Wunused-variable]
     struct tty_struct *tty;
                        ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_softint’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:508:24: warning: unused variable ‘tty’ [-Wunused-variable]
     struct tty_struct *tty;
                        ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_tty_ioctl’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:918:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
                 if (get_user(val, (int __user *)(arg + 2 * sizeof(int))))
                 ^~
ubuntu/xr-usb-serial/xr_usb_serial_common.c:921:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    if (channel == -1)
    ^~
  CC [M]  ubuntu/vbox/vboxguest/common/log/logrelellipsis.o
  CC [M]  ubuntu/vbox/vboxguest/common/log/logcom.o
  CC [M]  ubuntu/vbox/vboxguest/common/log/logformat.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg1Weak.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2Add.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2AddWeak.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2AddWeakV.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2Weak.o
In file included from ./include/linux/bitmap.h:9:0,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:21,
                 from ./arch/x86/include/asm/cpufeature.h:5,
                 from ./arch/x86/include/asm/thread_info.h:53,
                 from ./include/linux/thread_info.h:39,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:81,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:10,
                 from ./ubuntu/vbox/vboxguest/include/internal/iprt.h:56,
                 from ubuntu/vbox/vboxguest/common/log/log.c:32:
In function ‘memcpy’,
    inlined from ‘rtLogStPNCpyPad’ at ubuntu/vbox/vboxguest/common/log/log.c:3587:9,
    inlined from ‘rtLogOutputPrefixed’ at ubuntu/vbox/vboxguest/common/log/log.c:3819:25:
./include/linux/string.h:374:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
readelf: Warning: [31]: Info field (30) should index a relocatable section.
scripts/Makefile.build:333: recipe for target 'ubuntu/vbox/vboxguest/common/log/log.o' failed
make[3]: *** [ubuntu/vbox/vboxguest/common/log/log.o] Error 1
make[3]: *** Waiting for unfinished jobs....
scripts/Makefile.build:607: recipe for target 'ubuntu/vbox/vboxguest' failed
make[2]: *** [ubuntu/vbox/vboxguest] Error 2
scripts/Makefile.build:607: recipe for target 'ubuntu/vbox' failed
make[1]: *** [ubuntu/vbox] Error 2
make[1]: *** Waiting for unfinished jobs....
readelf: Warning: [31]: Info field (30) should index a relocatable section.
Makefile:1087: recipe for target 'ubuntu' failed
make: *** [ubuntu] Error 2

### Diagnostic Logs

/usr/src/linux-source-4.15.0$ sudo make -j16
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  DESCEND  objtool
  CHK     include/generated/utsrelease.h
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC [M]  ubuntu/xr-usb-serial/xr_usb_serial_common.o
  CHK     kernel/config_data.h
  CC [M]  ubuntu/vbox/vboxguest/common/log/log.o
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_ctrl_irq’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:301:21: warning: unused variable ‘tty’ [-Wunused-variable]
  struct tty_struct *tty;
                     ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_process_read_urb’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:433:24: warning: unused variable ‘tty’ [-Wunused-variable]
     struct tty_struct *tty;
                        ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_softint’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:508:24: warning: unused variable ‘tty’ [-Wunused-variable]
     struct tty_struct *tty;
                        ^~~
ubuntu/xr-usb-serial/xr_usb_serial_common.c: In function ‘xr_usb_serial_tty_ioctl’:
ubuntu/xr-usb-serial/xr_usb_serial_common.c:918:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
                 if (get_user(val, (int __user *)(arg + 2 * sizeof(int))))
                 ^~
ubuntu/xr-usb-serial/xr_usb_serial_common.c:921:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    if (channel == -1)
    ^~
  CC [M]  ubuntu/vbox/vboxguest/common/log/logrelellipsis.o
  CC [M]  ubuntu/vbox/vboxguest/common/log/logcom.o
  CC [M]  ubuntu/vbox/vboxguest/common/log/logformat.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg1Weak.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2Add.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2AddWeak.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2AddWeakV.o
  CC [M]  ubuntu/vbox/vboxguest/common/misc/RTAssertMsg2Weak.o
In file included from ./include/linux/bitmap.h:9:0,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:21,
                 from ./arch/x86/include/asm/cpufeature.h:5,
                 from ./arch/x86/include/asm/thread_info.h:53,
                 from ./include/linux/thread_info.h:39,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:81,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:10,
                 from ./ubuntu/vbox/vboxguest/include/internal/iprt.h:56,
                 from ubuntu/vbox/vboxguest/common/log/log.c:32:
In function ‘memcpy’,
    inlined from ‘rtLogStPNCpyPad’ at ubuntu/vbox/vboxguest/common/log/log.c:3587:9,
    inlined from ‘rtLogOutputPrefixed’ at ubuntu/vbox/vboxguest/common/log/log.c:3819:25:
./include/linux/string.h:374:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
readelf: Warning: [31]: Info field (30) should index a relocatable section.
scripts/Makefile.build:333: recipe for target 'ubuntu/vbox/vboxguest/common/log/log.o' failed
make[3]: *** [ubuntu/vbox/vboxguest/common/log/log.o] Error 1
make[3]: *** Waiting for unfinished jobs....
scripts/Makefile.build:607: recipe for target 'ubuntu/vbox/vboxguest' failed
make[2]: *** [ubuntu/vbox/vboxguest] Error 2
scripts/Makefile.build:607: recipe for target 'ubuntu/vbox' failed
make[1]: *** [ubuntu/vbox] Error 2
make[1]: *** Waiting for unfinished jobs....
readelf: Warning: [31]: Info field (30) should index a relocatable section.
Makefile:1087: recipe for target 'ubuntu' failed
make: *** [ubuntu] Error 2

**Comment by elsaco** [comment]
@zidong6344 you might want to use `make menuconfig` or another kernel configuration option instead of directly editing `.config` file. Enabling one options many times depends on other options that might not be enabled if manually editing the kernel configuration file. Such is the case for `CONFIG_KASAN=y`

I noticed you're using an older kernel. On latest WSL2 kernel release enabling KASAN works fine. On latest kernels `CONFIG_SLUB_DEBUG` is enabled by default also.

Here's a screenshot of WSL kernel 5.10.102.1 with KASAN enabled:

![wsl_kasan](https://user-images.githubusercontent.com/3933920/162640140-ef17f085-df2f-4492-bfef-ab5b0c657431.png)

**Comment by zidong6344** [comment]
> @zidong6344 you might want to use `make menuconfig` or another kernel configuration option instead of directly editing `.config` file. Enabling one options many times depends on other options that might not be enabled if manually editing the kernel configuration file. Such is the case for `CONFIG_KASAN=y`
> 
> I noticed you're using an older kernel. On latest WSL2 kernel release enabling KASAN works fine. On latest kernels `CONFIG_SLUB_DEBUG` is enabled by default also.
> 
> Here's a screenshot of WSL kernel 5.10.102.1 with KASAN enabled:
> 
> ![wsl_kasan](https://user-images.githubusercontent.com/3933920/162640140-ef17f085-df2f-4492-bfef-ab5b0c657431.png)

I encountered the same problem using make menuconfig

My approach is to download configwsl from GitHub and put it into the kernel and use make menuconfig to make changes. I don't know if there is a problem with this.

Without using the configuration file provided by Microsoft, it can be generated normally, but it cannot be applied on WSL.

**Comment by zidong6344** [comment]
Thank you for answering the question. I finally solved this problem. I found that the problem was caused by the mismatch of GCC versions. I updated to the latest GCC 9.3.0, and this problem was solved.
