### ISSUE TITLE
Using an html tag in webpack says < is a special character. This is not an issue in Windows

### ISSUE THREAD

**Issue by gadgetcrawford** [microsoft/WSL#8267]
### Version

Windows 11[10.0.0.22000 Build 22000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5/10.16

### Distro Version

Ubuntu 20.04

### Other Software

VS CODE 1..65.2

### Repro Steps

I am creating a webpack.  In template.html, I have a line of code like this:
<title><%= htmlWebpackPlugin.options.title %></title>

In wsl, IT is saying the opening and closing brackets <% ... %> needs to be escaped as it is a special character.

This is not an issue in Windows
![error](https://user-images.githubusercontent.com/31297763/162626779-f50985e2-bb2c-463f-a45b-2e017c47a73b.png)
.

### Expected Behavior

No special character warning

### Actual Behavior

Warning for special character and output not needed

**Comment by OneBlue** [comment]
Closing since this isn't a WSL issue. I recommend creating an [VSCode issue](https://github.com/microsoft/vscode/issues) for this
