### ISSUE TITLE
My Ubuntu WSL2 distros fail to boot upon WSL update to 0.58.0

### ISSUE THREAD

**Issue by oscarbg** [microsoft/WSL#8272]
### Version

Microsoft Windows [Versión 10.0.22489.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-CommPrev (21.04)

### Repro Steps

Launching wsl by any means like wsl from command line (cmd.exe)..
or not default distros like:
wsl -d Ubuntu
note all distros installed fail with same error..

### Expected Behavior

to launch the Ubuntu WSL machine as expected..

### Actual Behavior

returns (in Spanish):
"El documento JSON de la máquina virtual o del contenedor no es válido."

### Diagnostic Logs

I use fairly frequently WSL so seems is due to update WSL 0.5.8 as few days ago all worked with previous update 0.56.2..

wsl.exe --status
Distribución predeterminada: Ubuntu-CommPrev
Versión predeterminada: 2
Versión de WSL: 0.58.0.0
Versión de kernel: 5.10.102.1
Versión de WSLg: 1.0.32
Versión de MSRDC: 1.2.2924
Versión de Direct3D: 1.601.0
Versión de Windows: 10.0.22489.1000

**Comment by oscarbg** [comment]
just tried to install a new Ubuntu version to see what's the error and I see:
```
wsl --install Ubuntu-18.04
Instalando: Ubuntu 18.04 LTS
Se ha instalado Ubuntu 18.04 LTS.
Iniciando Ubuntu 18.04 LTS...
```

and the new window booting Ubuntu says:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8037010d
Error: 0x8037010d El documento JSON de la mßquina virtual o del contenedor no es vßlido.

```

**Comment by elsaco** [comment]
@oscarbg try `wsl.exe --update --rollback` and revert to the previous working configuration. After, apply the update again.

**Comment by TimonTerBraak** [comment]
I am having the same issue:

> The virtual machine or container JSON document is invalid.
> 
> [process exited with code 4294967295 (0xffffffff)]

System info:

> $ wsl --status
> Default Distribution: Ubuntu
> Default Version: 2
> WSL version: 0.58.0.0
> Kernel version: 5.10.102.1
> WSLg version: 1.0.32
> MSRDC version: 1.2.2924
> Direct3D version: 1.601.0
> Windows version: 10.0.22526.1000

**Comment by hironichu** [comment]
Same issue here, after manually installing earlier version everything works in my machine 

I'm running Windows 11 build 22533.1001

:/ I just discovered that issue.. and removed my entire WSL VMs this mornings cause I was sure the error came from some changes I've made :c

Using 0.56.0 
![image](https://user-images.githubusercontent.com/64388064/163057086-e26a6d21-70ab-4db7-8812-acb08193a3a0.png)

Using 0.58.0 
![image](https://user-images.githubusercontent.com/64388064/163057688-64c629dd-8db5-40e7-b3cf-2f124a0b2393.png)

**Comment by virenpawar** [comment]
Since today morning, I am facing the same issue. 

![image](https://user-images.githubusercontent.com/18348610/163064908-5f02f1cc-6b31-4aad-9b09-0d923b266256.png)

**Comment by oscarbg** [comment]
I'm curious if that happens with WSL 0.58 with latest insider build i.e. 22593 or only with somewhat old builds like mine (22489)  and @hironichu (22533)..
anyway thanks @hironichu for pointing to which I hope is a temporary solution (i.e. I hope WSL 0.59 or WSL 0.60 to fix this for us)

**Comment by TimonTerBraak** [comment]
Downgrading the package as suggested by @hironichu worked for me:
`$ Add-AppxPackage -ForceUpdateFromAnyVersion .\Microsoft.WSL_0.56.2.0_x64_ARM64.msixbundle`

(I had to terminate some VM/Hypervisor services first.)

**Comment by benhillis** [comment]
Thanks for posting - FYI it seems everybody that is hitting this issue is running a rather old Insider build. Could you check your Insider settings?

Fix is inbound.

**Comment by hironichu** [comment]
> Thanks for posting - FYI it seems everybody that is hitting this issue is running a rather old Insider build. Could you check your Insider settings?
> 
> Fix is inbound.

Thanks !, and for my case I have the Preview build because I'm on unsupported hardware which stops me from updating to 
Dev/Beta build.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/0.58.1.
