### ISSUE TITLE
[WSL Preview] chcp returns "Parameter format not correct - /c" when ran

### ISSUE THREAD

**Issue by shinji257** [microsoft/WSL#8276]
### Version

WSL version: 0.58.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.32
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22593.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.102.1

### Distro Version

Ubuntu 20.04.4 LTS

### Repro Steps

On 20.04 just running wslvar without arguments is enough.
```
┏[shinji]
┖[~]
   wslvar
Parameter format not correct - /c
Parameter format not correct - /c
```
On 22.04 development you have to actually give it something to translate as (at least on that release) it seems to give the usage back properly.
```
shinji@Tinym:~$ wslvar
[error] No Input. Aborted.
shinji@Tinym:~$ wslvar localappdata
Parameter format not correct - /c
Parameter format not correct - /c
C:\Users\shinj\AppData\Local
```

### Expected Behavior

wslvar shouldn't give back those messages and just return results or help information (if no arguments given)

### Actual Behavior

It throws "Parameter format not correct - /c" twice during operation however it does still appear to operate properly otherwise.  The issue appears to be cosmetic beyond (possibly) preventing help output on 20.04.

**Comment by Biswa96** [comment]
wslvar is not part of official WSL environment. The issue should be reported to original developer. Link https://wslutiliti.es/wslu/man/wslvar.html

**Comment by shinji257** [comment]
Ok.  Good to know.  This is something that is included with the default distribution packages for the Ubuntu WSL installs so (given the name) I though it was part of it.  Anyways it isn't even the script that is the issue.  I found the issue elsewhere (after copying the script and forcing it to output each command being ran) but not sure where to report it to...

The call to the Windows chcp binary is causing it.  Do you know where I can report that?
```
┏[shinji]
┖[~]
   /mnt/c/Windows/System32/chcp.com 437
Parameter format not correct - /c
```

**Comment by Biswa96** [comment]
Working in my manually installed Linux distribution in WSL2.

```
x@y:/mnt/c/Users/x
$ /mnt/c/Windows/System32/chcp.com 437
Active code page: 437
```

wslvar is from https://github.com/wslutilities/wslu repository.

**Comment by shinji257** [comment]
What version of Windows and WSL2 are you on?  Is it the same as mine?

C:\Users\shinj>wsl --version
WSL version: 0.58.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.32
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22593.1

**Comment by Biswa96** [comment]
I'm using the good old Windows 10 :)

**Comment by shinji257** [comment]
Ok.  So, this looks to be a bug in WSL introduced with the beta release since I do have a preview version.  I already removed the script as a factor the moment I found chcp reproduced it outside the script itself.  I need someone on preview to reproduce and I'll go throw this on the Feedback Hub with a link for attention there.

**Comment by shinji257** [comment]
I went and checked the Store listing for WSL Preview and followed the support links and it comes back here so I updated the bug title accordingly noting it is a Preview issue.

**Comment by craigktreasure** [comment]
There's an [issue filed in the wslutilities](https://github.com/wslutilities/wslu/issues/231) repo already for this. Looks like the author has a fix, but is having Ubuntu packaging issues.

**Comment by shinji257** [comment]
Yea. That's my ticket that I posted over there to see if something could be done about it. Waiting to see what the dev did to fix it. Still wondering why chcp throws that error in preview though.

**Comment by OneBlue** [comment]
Closing since this isn't a WSL issue.
