### ISSUE TITLE
WSL2 - Upgrade/Install returns error 0x80070032 or request is not supported

### ISSUE THREAD

**Issue by Shossi** [microsoft/WSL#8280]
### Version

Microsoft Windows [Version 10.0.19044.1526]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

ubuntu 20.04

### Repro Steps

wsl --set-default-version 2
wsl --install -d ubuntu-20.04 
produces this :
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070032
Error: 0x80070032 The request is not supported.

Press any key to continue...

wsl --set-default-version 1
wsl --install -d ubuntu-20.04
Works fine but then:
wsl --set-version ubuntu-20.04 2
returns this:
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The request is not supported.

### Expected Behavior

I would like the upgrade/installation to work

### Actual Behavior

wsl 2 upgrade/installation returns a error

### Diagnostic Logs

Hyper-V / VM Platform / WSL - all enabled on windows features
Virtualization is enabled on bios
tried this fix : https://askubuntu.com/questions/1401830/wsl-not-working-after-update-from-microsoft-store
my distribution name was ubuntu-20.04, so it didnt help.

Edit: Added logs: https://aka.ms/AAgn5dh

**Comment by Shossi** [comment]
https://aka.ms/AAgn5dh

**Comment by Shossi** [comment]
Reinstalled windows and it works now, sorry we couldn't find the problem, hope it won't happen to anyone else

**Comment by thesalmonidae** [comment]
I had this today after a Windows updates. I was able to save ext4.vhdx's, but I simply cannot get WSL2 working again.

So for 6 months that setup, Windows 10 Enterprise, worked without any issues.

Something needs to be reset, but what?

**Comment by Csega** [comment]
I have the same issue now, yesterday it worked perfectly. Windows 11 Pro 21H2.
