### ISSUE TITLE
Curl doesn't work as expected on WSL 2

### ISSUE THREAD

**Issue by gilmishal** [microsoft/WSL#8285]
### Version

 Microsoft Windows [Version 10.0.22593.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Run `curl -v google.com`

### Expected Behavior

Get a valid http response from google.com

### Actual Behavior

 receiving a loop of the following:
 
 TCP_NODELAY set
* Immediate connect fail for 2001:4860:4802:38::a: Network is unreachable
*   Trying 2001:4860:4802:32::a:80...

### Diagnostic Logs

I noticed that the IP curl is using is invalid, trying to ping the ip received from curl -v doesn't work. Using curl from windows powershell with that IP results with the same error.

If I ping google.com before running curl, curl works well.
If I run nslookup google.com before running curl, curl works well.

If I take the IP from curl on windows powershell, curl works well on that IP.

I suspect this is an issue with DNS resolution, and it specifically affects curl, ping is not affected, and neither is nslookup

I did try this on other Ubuntu version on WSL, all had the same issue.

**Comment by elsaco** [comment]
@gilmishal this is output from `curl -v google.com` on WSL2 Ubuntu:

```
root@eleven:~# curl -v google.com
*   Trying 142.251.33.78:80...
* Connected to google.com (142.251.33.78) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Wed, 13 Apr 2022 19:44:07 GMT
< Expires: Fri, 13 May 2022 19:44:07 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
<
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
```

It connects to an IPv4 address. Why is your curl client trying an IPv6 address?

**Comment by gilmishal** [comment]
I dropped the initial part, it starts with an IPv4

`
*   Trying 216.239.32.10:80...
* TCP_NODELAY set
*   Trying 2a00:1450:4001:813::200e:80...
* TCP_NODELAY set
* Immediate connect fail for 2a00:1450:4001:813::200e: Network is unreachable
*   Trying 2001:4860:4802:32::a:80...
`

If I curl -v 216.239.32.10:80 on powershell it just hangs (ping works actually)

If I curl - google.com

`
*   Trying 142.250.185.238:80...
* Connected to google.com (142.250.185.238) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Wed, 13 Apr 2022 20:06:04 GMT
< Expires: Fri, 13 May 2022 20:06:04 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
<
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
`

If I `curl -v 142.250.185.238:80` on powershell or WSL it works fine.

could the issue be that it's immediately tries ipv6 on failure? whereas on powershell it tries other ipv4s? why is it behaving this way?

**Comment by gilmishal** [comment]
Update: `curl -4 google.com` works everytime.
I could use an alias `curl = curl -4` but I am not sure what to make of it.

Why is curl on a newely installed wsl distro behaves the way it does?
I do see that ipv6 is not supported on WSL2, so that explains those failures.

**Comment by OneBlue** [comment]
Thanks for reporting this @gilmishal. Can you share the content of `/etc/resolv.conf` ?

**Comment by PauloDaniel1993** [comment]
Any news about this one?

**Comment by Tyler-Odenthal** [comment]
Our team can't curl a docker container using WSL2.

curl -v http://localhost:9001/
* Trying 127.0.0.1:9001...
* TCP_NODELAY set
* connect to 127.0.0.1 port 9001 failed: Connection refused
* Failed to connect to localhost port 9001: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9001: Connection refused

**Comment by gonultasbu** [comment]
looks like the same issue:

https://github.com/microsoft/WSL/issues/8358

**Comment by LongLiveCHIEF** [comment]
Can we stop closing these issues? Workarounds are not fixes, and by closing them, we keep persisting the problem. If the issue stays open it can get prioritized... and basic networking failing on basic WSL distro installations would probably be a priority issue.
