### ISSUE TITLE
WSLENV is broken from one direction but not the other

### ISSUE THREAD

**Issue by tan-wei-xin-alez** [microsoft/WSL#8286]
### Version

Microsoft Windows [Version 10.0.19042.1466]

### WSL Version

WSL 2

### Kernel Version

Linux version 5.10.60.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

### Distro Version

Distributor ID: Ubuntu
Description: Ubuntu Jammy Jellyfish (development branch)
Release: 22.04
Codename: jammy

### Repro Steps

1. Install and set up WSL2
2. Run C:\Windows\System32\wsl.exe and execute the following commands
```
export FORWSL=/mnt/c/Users/
export WSLENV=FORWSL/p
cmd.exe
set FORWSL
```
&nbsp;&nbsp;&nbsp;&nbsp; and `FORWSL=C:\Users\` is returned which means it works <br>
3. Run C:\Windows\System32\cmd.exe and execute the following commands
```
set FORWSL=C:\Users\
set WSLENV=FORWSL/p
wsl.exe
echo $FORWSL
```
&nbsp;&nbsp;&nbsp;&nbsp; but `$FORWSL` is empty and `echo $WSLENV` also returns nothing <br>

The behavior is the same regardless of whether cmd.exe was run with or without administrator rights.

The above was based on the instructions at https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/ so either `WSLENV` is broken in one direction or the documentation is wrong.

### Expected Behavior

```
set FORWSL=C:\Users\
set WSLENV=FORWSL/p
wsl
echo $FORWSL
```
&nbsp;&nbsp;&nbsp;&nbsp; should return `/mnt/c/Users/` <br>

### Actual Behavior

```
set FORWSL=C:\Users\
set WSLENV=FORWSL/p
wsl
echo $FORWSL
```
&nbsp;&nbsp;&nbsp;&nbsp; returns nothing <br>

**Comment by benhillis** [comment]
Looks like this is working on 22000 and version 0.58.0 of store WSL.

**Comment by elsaco** [comment]
It seems to work on a slightly updated Windows 10, also:

```
Microsoft Windows [Version 10.0.19044.1645]
(c) Microsoft Corporation. All rights reserved.

C:\Users\tux>set WSLENV
WSLENV=WT_SESSION::WT_PROFILE_ID

C:\Users\tux>set FORWSL=C:\Users\

C:\Users\tux>set FORWSL
FORWSL=C:\Users\

C:\Users\tux>set WSLENV=%WSLENV%:FORWSL/p

C:\Users\tux>set WSLENV
WSLENV=WT_SESSION::WT_PROFILE_ID:FORWSL/p

C:\Users\tux>wsl
tux@RIPPER:/c/Users/tux$ echo $FORWSL
/c/Users/
tux@RIPPER:/c/Users/tux$

```

WSL info:

```
C:\Users\tux>wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 3/26/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

**Comment by tan-wei-xin-alez** [comment]
Ok, running `wsl --update` and then restarting it makes the issue go away

**Comment by tertek** [comment]
I am still having this issue:

wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3086
