### ISSUE TITLE
8% vmmem CPU usage on windows when top in WSL shows ~0 CPU usage when running WSL2 with the task scheduler of Windows 11

### ISSUE THREAD

**Issue by epigramx** [microsoft/WSL#8288]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Run WSL, in a way that in the ubuntu itself there's no siginificant cpu usage. See task manager show vmmem have near 10% cpu usage on an 8-thread CPU.

### Expected Behavior

It used to be near 0% usage.

### Actual Behavior

near 10% cpu usage on an 8-thread CPU

### Diagnostic Logs

![image](https://user-images.githubusercontent.com/2960257/163333329-7c849bd5-0f47-46d9-a746-b16bd8020bb8.png)

![image](https://user-images.githubusercontent.com/2960257/163333394-b27df791-e33e-4fbf-bd1c-84f2a4a4f061.png)

**Comment by epigramx** [comment]
It probably started, after I installed 11 over windows 10, but I'm not sure if it's related.

**Comment by epigramx** [comment]
It appears to alleviate if I `wsl --shutdown` and then start it again, but I don't see why that would happen, since the only thing different is that I start it on a schedule task at windows boot by to bring ubuntu cont and syslogd up but if I kill those two processes during the problem: it does not fix it and they appear 0% cpu usage in `top` even when they run anyway.

**Comment by epigramx** [comment]
OK there's definitely a problem with starting wsl with the windows 11 task scheduler specifically, even if no service is run with it at all or even if wsl.conf runs no service. I can't imagine what might cause is when `top` in-linux shows ~0 cpu usage.

**Comment by elsaco** [comment]
@epigramx don't rely too much on those readings. With one single idling WSL instance, the output is different when checked as admin:

As administrator:

```
PS C:\Users\tux> get-process -name vmmem

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      0   939.91     938.02       3.11   13228   0 vmmem
```


As non-admin user:

```
PS C:\Users\tux> get-process -name vmmem

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      0   937.91     936.02       0.00   13228   0 vmmem
```

While the PM (paged memory) and WS (working sets) are very close, the CPU usage is different.

Also, the `top` readings have no relationship to the host. While your vm is idle, with top showing zero cpu usage, the hypervisor is not. `vmmem` is what the hypervisor thinks the vm(s) is using.

**Comment by epigramx** [comment]
@elsaco it's definitely correlated to actual hardware usage, because I can physically hear the CPU fan working harder when vmmem is at 8% cpu usage instead of ~0%.

There's something weird going on when it starts from the task scheduler instead of normally (even if it's not done at boot but with a right click on the scheduler).

**Comment by fgielow** [comment]
It's odd because if I use `htop` instead of `top`, it still does not show correct CPU usage on the processes listed (similar to top), but the graphical represensation of the cores show they are all really busy (which indeed happens inside WSL2 as I am running tilt there, which is the routine strressing all my cores as it serves a kubernetes cluster locally).

![Captura de tela 2022-06-16 114738](https://user-images.githubusercontent.com/805927/174054483-82c461b9-aad1-483d-b16f-7932716243a0.png)
