### ISSUE TITLE
Cannot find GPU devices on Bash

### ISSUE THREAD

**Issue by forhonourlx** [microsoft/WSL#829]
Does win10 bash support GPU devices?

**Comment by benhillis** [comment]
Not currently. This is a[ highly requested feature on our User Voice forum](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250010-ubuntu-shell-access-to-system-gpu-ability-to-run).  I would suggest you add your workflow to the discussion there so help us prioritize features we work on in the future.

Thanks for trying out WSL!

**Comment by fpqc** [comment]
@forhonourlx I wonder if it ever will (and if it did, how would it work).  If MS could code some kind of generic driver that passed openGL DRM stuff to the Windows driver stack and passed the rest of it onwards to an X or Wayland server on Windows, maybe it could work, but otherwise I think the best you might get is something that will inevitably be kind of crappy virtualized graphics card.  

If not, AIGLX is still a supported (if not the absolute fastest) way of doing graphics rendering in Linux (and according to my sources (Arch Wiki) was still the way that most desktop composition was done until at least 2009).  Support for something like AIGLX (which is hardware-agnostic on the X client side) already exists in vcXsrv (although the most important plugin GL_PIX_FROM_TEXMAP) is not implemented right now in hardware accelerated mode.

**Comment by aseering** [comment]
Another major use case for GPUs is OpenCL/CUDA/etc, which I don't think AIGLX will help with?  And it's more relevant to the sorts of use cases that WSL is initially targeting.

If there were enough demand and if the relevant players felt like playing nice, in principle the WSL team could collaborate with NVidia (I'd list all vendors but really NVidia seems to be the big player in this particular field) and build a WSL driver.  Not saying that's the best approach, nor that it would ever necessarily happen; just saying it could.

(If you care about CUDA in particular, it might be worth making some noise on the NVidia forums as well; make sure they also hear about any demand for support.)

**Comment by thesby** [comment]
If cuda is okay on bash, maybe some deep learning tools, such as tensorflow, caffe, can  directly run on windows.

**Comment by roachsinai** [comment]
Truly!

**Comment by IvanFarkas** [comment]
Would be nice!

**Comment by jotaf98** [comment]
Any insights on how challenging, technically, this would be? Just to adjust expectations accordingly.

**Comment by XinliZ** [comment]
Expecting...

**Comment by vickylance** [comment]
Ok it's 2017 November. Any updates on this so far?

**Comment by IvanFarkas** [comment]
Can we have it for **Thanksgiving** or a **super early Christmass** present the latest, please?

**Comment by sunilmut** [comment]
We are quite aware of the demand of this feature and are working to see how best we can support it. It's very unlikely to be part of the next (FCU + 1) release.

@jotaf98 - The challenge here is not just technical but also logistical and other. Because there are multiple players involved here, and not everything is in direct control. But, we are exploring all possibilities here.

**Comment by jotaf98** [comment]
@sunilmut Thanks for the insight! Rooting for you guys to find a way to make it work.

**Comment by yuchenlin** [comment]
Looking forward!

**Comment by IvanFarkas** [comment]
Ditto!

**Comment by riceshrug** [comment]
I'd like to add to the chorus, **OpenCL** support from the bash shell is very important to me. Thank you.

**Comment by omaralvarez** [comment]
Any new updates on this? I would love to be able to run OpenGL apps.

**Comment by gigagem** [comment]
Really looking forward to being able to use WSL for running/testing our GPU-intensive programs. Now executing nvidia-smi in WSL Ubuntu, I get "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

**Comment by GusSand** [comment]
+1 on @peterjc123 request.  I'm trying to run some deep learning libs on WSL and can't. Some help here guys.  Can you get Abolade on the case? 👍

**Comment by zawawawa** [comment]
C'mon guys, I really need this feature...

**Comment by Biswa96** [comment]
@zawawawa Microsoft is finalizing Windows 10 for October update. This feature may be added in 19H1. We've to wait 😪

**Comment by Khalilsqu** [comment]
please add also sound system. no sound can be played from wsl

**Comment by vickylance** [comment]
@Biswa96 Do you have any source for that info? Because from what I believe this is something cannot be implemented. As it would require a complete architecture change in Windows OS.

**Comment by Yay295** [comment]
Where did you get the idea that this can't be implemented from?

**Comment by Biswa96** [comment]
@vickylance That was just an assumption. If you see the insider builds there is no watermark. So Win10 is ready to be launched and no more feature adding. Also see the latest commits of 19H1 in riverar/mach2 repo. There is a feature "WSL_Command_Line_Updates". So something is going on with CMD.

Nothing is impossible with a kernel mode driver, e.g. LxCore.sys in WSL. To add GPU features, developers need time to implement it.

**Comment by vickylance** [comment]
@Yay295 This was said by Rich Turner. Here,

> It’s on the backlog, but not currently planned.

We know many of you would like to be able to accelerate your numerical analysis code via CUDA/OpenCL, etc.

One thing to explore in the meantime is to try running your code in Windows. Windows actually has very powerful GPU-acceleration capabilities and you may well find that much of your existing code may well work already or require trivial effort to port to Windows itself.

in the meantime, bear with us, and UPVOTE THIS ISSUE if you care (please don’t create another duplicate ask – that doesn’t help us prioritize asks).

Thanks.


This can be found in this link.
https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support#{toggle_previous_statuses}

**Comment by therealkenc** [comment]
> Because from what I believe this is something cannot be implemented. As it would require a complete architecture change in Windows OS.

[this](https://github.com/Microsoft/WSL/issues/2422)

**Comment by justanhduc** [comment]
Hi. I would like to ask if there is any update on this? Maybe its too much to ask for a time frame but is there any development team working on this now or the project still on hold? Thank you very much.

**Comment by AbhimanyuAryan** [comment]
I want to use it for Deep Learning in **PyTorch**. Please support it so we don't have to download Ubuntu or other Linux distributions separately. Thanks

**Comment by peterjc123** [comment]
@AbhimanyuAryan For PyTorch, it is already supported on Windows since April 2018 (0.4.0).

**Comment by royharoush** [comment]
+1

**Comment by AbhimanyuAryan** [comment]
@peterjc123 you mean I can use PyTorch GPU inside WSL?

**Comment by peterjc123** [comment]
@AbhimanyuAryan Yes if without GPU and No if with GPU. Actually, there's no need to use it in WSL because there is already a native one for Windows.

**Comment by robelgeda** [comment]
Any updates on this?

**Comment by Yay295** [comment]
The update is that WSL 2 is coming soon and does not fix this issue. Due to the release of WSL 2 there probably won't be an update on this for a while as they deal with the inevitable new bugs found.

**Comment by robelgeda** [comment]
That's disappointing but I suppose they have a lot more urgent things to work on. I am planning on purchasing new equipment and based on your comments I shouldn't consider Window os.

**Comment by AceHack** [comment]
WSL2 requires Hyper-V, seems like a step backward.

**Comment by vickylance** [comment]
@AceHack Ah damn is it? I was excited for WSL2 until you said Hyper-V :(

**Comment by AceHack** [comment]
@vickylance same

**Comment by therealkenc** [comment]
> WSL2 requires Hyper-V, seems like a step backward.

These are odd sentiments, given the move to a Real Linux container on Windows approach shifted the probability of this three-digit August 2016 feature request being realized from "probably never" to "at least [hypothetically possible](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/vfio) sometime if not in the initial WSL2 release". 

There are a couple of check-boxes in the "con" column with respect to running a Real Linux kernel under a virtual machine, but this particular tracker is not one of them. I wouldn't even be surprised if the highly voted [CUDA request](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support) was the tail that wagged the "fine, we'll ship a Linux Kernel" dog. 

The recent posts here run a non-zero risk of not aging well. I'm just 'sayin.

**Comment by vickylance** [comment]
@therealkenc  If GPU will be accessible because of the hyper-v requirement I am cool with that. But it breaks some other things enabling Hyper-V on my machine. So I have to kinda back and forth turning on and off it. But if it needs to be worth that effort for me to constantly switch between then it better support CUDA.

**Comment by glesur** [comment]
I would like to push forward opencl, cuda and openacc support in WSL for the following simple reason;
up to now, many scientists (me included) were using and developping high performance computing codes on macos. Reason has always been that it's an "easy to use" unix-type os. This included codes developped on the top of MPI library (used to run on super computers) and cuda/opencl.

Except that Apple has decided to drop opencl/cuda support altogether. This means that  scientists developping numerical codes which relies on opencl will not be able to work on macos with the next macos update.

So at the moment, I'm trying windows with WSL using bootcamp. Performance looks good, and the MPI library (using openmpi) is fully functionnal, with limited impact on performances (suprisingly, WSL1 is faster than WSL2).

The only thing which prevents me from switching is the lack of GPU support on WSL. So please implement this, and you'll make many scientists happy, who will switch from macs to windows.

and thanks for the hard work!

**Comment by machineko** [comment]
Anything new?

**Comment by thoward27** [comment]
This is one of the few things keeping me on Ubuntu. If WSL supported CUDA, I could make the switch.

**Comment by AceHack** [comment]
Any update?

**Comment by ForrestBarnes** [comment]
Some of the tools I absolutely need to use (ROS Gazebo, YOLOv3) require a Linux system with a graphics card, while some of the other tools I absolutely need to use (SolidWorks) require a Windows system with a graphics card. If there was any way for me to switch between these applications without rebooting every time or buying a second computer...

**Comment by aerydna** [comment]
any update on this? i'm using wsl2

**Comment by boshng95** [comment]
It would be great if Cuda is supported in WSL

**Comment by robelgeda** [comment]
@benhillis @craigloewen-msft  @jackchammons @bitcrazed you now have over 100 people supporting this ticket. Any news? 
You should discuss about this and let us know a rough timeline (assuming its still possible)

**Comment by AceHack** [comment]
Bump

**Comment by GusSand** [comment]
Bump bump !!

**Comment by aerydna** [comment]
dear Santa, if you think i've been a good boy this year it would be great to find Cuda support for wsl under the tree this Christmas..

**Comment by machineko** [comment]
@aerydna That was so good xD

**Comment by MichaelHazani** [comment]
Bump, but also, layperson's question: does this mean everyone here who relies on CUDA uses linux? Are the drivers stable enough? I'm at my wits' end as most RNN and GAN implementations I run into seem to be clearly oriented towards linux...

**Comment by machineko** [comment]
@MichaelHazani It is almost every deep learning lib is writen for linux mostly ubuntu env.
 Thats why we need this freaking gpu support 🗡

**Comment by suvl** [comment]
what about VAAPI, will it be supported anytime soon?

**Comment by rickstaa** [comment]
Although I'm really impressed with WSL2, I will stick with dual booting until GPU support is added.

**Comment by machineko** [comment]
Coca Cola ads are out so "Holidays Are Coming ..." and let's wish GPU magic happen this year ❤️

**Comment by aronsar** [comment]
WSL is a very exciting project, and if it offered GPU support I would use it much more extensively. The reason I would like GPU support on WSL is because as researcher in computer vision and natural language processing I often find myself running other people's code, which is almost exclusively written on linux. Since I don't own a linux machine, I rely on my university for sys admining, and I have to deal with unplanned downtimes and no sudo access. In fact, what brought me here was a "hardware upgrade" I was notified about 20 minutes before the system was shut down, in the middle of training a model. Please WSL team, we need GPU support! Can we get a kickstarter going for this or something? I would definitely pitch in $20.

**Comment by GusSand** [comment]
+20.

**Comment by DiegoJRR** [comment]
+ $20

**Comment by robelgeda** [comment]
+$50

**Comment by rickstaa** [comment]
> +$20
> +$50
+$50

**Comment by 6etacat** [comment]
+$50

**Comment by xiongzubiao** [comment]
+$10000

**Comment by bitcrazed** [comment]
Thanks everyone for your enthusiasm for this feature. Instead of posting meaningless +$'s which just dilute the thread, please **thumbs-up** upvote the topmost post in this thread so we can see a measurable indicator of interest. 

![image](https://user-images.githubusercontent.com/961950/72460989-d3fbeb80-3782-11ea-93d7-5f18167bf73f.png)

Thanks.

**Comment by privacyguy123** [comment]
Even if we could get something like [Bumblebeed](https://github.com/Bumblebee-Project/Bumblebee/wiki/Install-and-usage) working - but that would require full systemd support.

**Comment by garzillo** [comment]
I would move back to Windows 10 from a MacBook Pro for development (ML engineer) if this were supported.

**Comment by 6etacat** [comment]
@garzillo Wait, I think macOS don't support NVIDIA in general.

**Comment by garzillo** [comment]
@6etacat Right - WSL2 NVIDIA support would the the killer feature that would entice me to completely switch.

**Comment by machineko** [comment]
@bitcrazed 
So can u tell us anything new? 
Machine learning community fell kinda ignored in this issue.
GPU support was hottest request for about a year or even more, and we dont even know if wsl team is doing something in way to bring gpu and machine learning on windows or we should just ignore all of that and fully move to linux.
A lot of my colleagues from work was big windows fans before moving from data science/analytics roles to more ML based where they just cant do most of the stuff needed from them cause there is no GPU support in WSL (a lot of medium sized companies are working on thier own machines with ML stack, ignoring cloud because of high gpu pricing).

**Comment by 12101111** [comment]
Nvidia does not allow consumer graphics card used for virtualization purposes, so using Nvidia graphics cards in wsl2 is not possible unless Microsoft and Nvidia reach an agreement.

**Comment by Yiannis128** [comment]
MS needs to do something about this since it is pretty much one of the biggest issues with WSL at the moment... I wish NVIDIA wasn't so anti consumer...

**Comment by bitcrazed** [comment]
We hear you and we're as eager for a solution in this space as you all are. But do understand that implementing GPU compute support for WSL is a monumental piece of work spanning several teams and partners.

Be sure to follow @craigloewen-msft [on Twitter](https://twitter.com/craigaloewen) and visit the command-line blog for news of up-and-coming WSL features and improvements.

We thank you all for your patience. It'll be worth it in the end :)

**Comment by cloudhan** [comment]
So can I take your comment as "we are working on it"? Since you are not saying "It is on the backlog." or "I have nothing to say". @bitcrazed

**Comment by bitcrazed** [comment]
We have been exploring this feature for > 2 years now so, yes, we are 'working on it', but don't raise expectations of a delivery schedule for this feature until you see an announcement blog post by [Craig on Twitter](https://twitter.com/craigaloewen) and/or on https://devblogs.microsoft.com/commandline

**Comment by bloodgain** [comment]
Man, I just spent a whole day getting my toolchain working for CUDA on some slightly outdated training material (but hey, it was "free") to finally get "no CUDA-capable device" and find this thread. I could have spent the time setting up a VM or dual-booting my test PC instead. Some sort of warning or feature-list on the "package" for WSL would sure be helpful to warn people about things like this.

**Comment by machineko** [comment]
@bloodgain VM cant share gpu u need dual-booting :)

**Comment by Yiannis128** [comment]
Just saying... It's gonna probably be Windows 10's best feature. Having a fully powered Linux virtual environment that doesn't have the slowness and sluggishness of a VM.

Even if Nvidia doesn't allow MS to implement such a feature for their GPUs I still think they should do it for AMD GPUs.

**Comment by bloodgain** [comment]
> @bloodgain VM cant share gpu u need dual-booting :)

Thanks for the head's up. So silly. If standard VMs can do this and Docker containers can do it, why not hosted VM's?

**Comment by cloudhan** [comment]
> > @bloodgain VM cant share gpu u need dual-booting :)
> 
> Thanks for the head's up. So silly. If standard VMs can do this and Docker containers can do it, why not hosted VM's?

VM cannot do this if you are using GeForce or RTF card, nvidia does not allow GPU virtualization.

**Comment by Yiannis128** [comment]
Nvidia being anti consumer forcing you to buy their VM cards. 🙄👀

**Comment by 6etacat** [comment]
> @bloodgain VM cant share gpu u need dual-booting :)

You may also use GPU passthrough if you have 2 GPUs in the system. One for Linux VM and one for Windows. A lot of people use this method to play Windows games on Linux.

**Comment by delivey** [comment]
Really looking forward to this. Can't install a certain video-inpainting program on Windows, because the bash scripts are written for Linux, so there's no way to do it except to install a VM. Any updates?

**Comment by AnalogRez** [comment]
Thanks for the update @bitcrazed! Plenty of people would make the switch to Windows, definitely worth prioritizing

**Comment by MarkusPfundstein** [comment]
PLEASE

**Comment by AbhimanyuAryan** [comment]
I definitely greyed out my hair waiting for this. Moved back to Ubuntu 18.04...this is definitely going to take till 2022

**Comment by jurneo** [comment]
Hoping WSL 2 have this feature. But Let's see for WSL 3.

**Comment by Biswa96** [comment]
There are some work going on (maybe) about implementing this feature. Here are two hints I found:

1. This one is so old. Go to this [mach2] repository. The [mach2] repository lists all the insider build features. Then grep `WSL_Device_GPU` in features folder. You can find that it remains way back in 18932 insider build. Also `WSL_Device_GPU_WSL1` feature is present in 19624 build.

2. This one I found today. Go to [WSL2 Linux kernel] repository, `linux-msft-wsl-4.19.y` branch. See the [gpu: dxgkrnl: core code] commit. There is a config saying -- Microsoft virtual GPU support. And `dxgkrnl.sys` is the kernel mode DirectX graphics driver. Calculate the rest... 🤩


[mach2]: https://github.com/riverar/mach2.git
[WSL2 Linux kernel]: https://github.com/microsoft/WSL2-Linux-Kernel.git
[gpu: dxgkrnl: core code]: https://github.com/microsoft/WSL2-Linux-Kernel/commit/63f9db60b70829ad89d78d4f64427d34ee60e340

**Comment by craigloewen-msft** [comment]
Hi folks, we announced today that WSL will support GPU compute! I'll be posting more details about this change today. :)

**Comment by Biswa96** [comment]
Some queries:

1. Will those DirectX user mode .so libraries be open sourced?
2. The post only mentions about glibc based distributions, what about musl based ones e.g. Alpine? AFAIK, the init binary is statically linked to musl libc.
3. As some of the directx headers (e.g. d3dkmthk.h) are open sourced with GPL in Linux kernel tree, will this somehow affect the Windows SDK DirectX headers also?
4. Will there be some ways/docs about using the `/dev/dxg` interface through ioctl instead of relying on those libraries? May be someone will come up their own implementation.

**Comment by machineko** [comment]
@Biswa96 You should probably move this questions to blog post comments section and admin should close/lock this issue cause most people was just waiting for announcement and that is included in @craigloewen-msft comment, so if people come to this issue they should see this as last answer :)

**Comment by severian1778** [comment]
I spent $4000 on my surfacebook2 and I can't use my GPU in bash?   How does a centi-billion dollar firm not solve this problem.    I cant just go and buy a new computer like Bill Gates when I feel like it,   maybe the devs at MS can grow up and service their customers.  I have CUDA intensive tasks I want to run on something I paid out of the nose for.

**Comment by bitcrazed** [comment]
> Polite ask: Please keep conversations around here respectful.

@severian1778 In case you missed the news this week from Build2020, you'll want to read these two posts:

* https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/
* https://devblogs.microsoft.com/directx/directx-heart-linux/

In addition, there's a ton of work going on right now on DirectML which aims to enable you to run AI/ML type workloads across any compatible GPU from any silicon vendor:

* https://blogs.windows.com/windowsdeveloper/2020/03/18/extending-the-reach-of-windows-ml-and-directml/
* https://docs.microsoft.com/en-us/windows/win32/direct3d12/dml-intro

This work by Microsoft and our silicon partners will be leveraged by any app running atop DirectML including apps running in WSL.

**Comment by cloudhan** [comment]
@bitcrazed regarding with DirectML,
1. Will it support dynamic shape? This will be critical for NLP/ASR task.
2. Will it support custom op?

**Comment by bitcrazed** [comment]
@cloudhan - great questions for https://twitter.com/crahrig

**Comment by craigloewen-msft** [comment]
The first preview of this work hit the Windows Insiders Dev channel today. Please find all the details [on this blog post](https://devblogs.microsoft.com/commandline/gpu-compute-wsl-install-and-wsl-update-arrive-in-the-windows-insiders-fast-ring-for-the-windows-subsystem-for-linux/). 🎉🎉🎉

**Comment by YaaZ** [comment]
@craigloewen-msft cool to hear that! Are there any updates about rendering, like Vulkan/OpenGL support?

**Comment by MichaelHazani** [comment]
this is incredible - years in the making but worth the wait. Thank you!

**Comment by craigloewen-msft** [comment]
@YaaZ not yet, but please stay tuned. :)

**Comment by therealkenc** [comment]
No instant gratification here unfort. The bind mount of the drivers took, but no `/dev/dgx`. `dmesg` looks clean at a glance. Problem between monitor and chair, probably. Still early.

![image](https://user-images.githubusercontent.com/7049700/84946216-32642780-b09d-11ea-8857-e30d2a385f25.png)

**Comment by ningacoding** [comment]
Finally WSL2 And Genymotion Working <3 Thanks Microsoft

![image](https://user-images.githubusercontent.com/17342546/84950263-3e0f1880-b0b4-11ea-8f4f-dbb47221d02f.png)

**Comment by robelgeda** [comment]
I literally took a shot 🥃🍻
Some good news during bad times.
Thanks for listing to the people WSL team ❤️

**Comment by Riccorl** [comment]
I followed the documentation and it seems like it's successfully installed, but this code hangs indefinitely with one cpu core at 99%

```
python -c 'import torch; print(torch.rand(2,3).cuda())'
```

is this the normal behavior and I should just wait?

**Comment by onomatopellan** [comment]
@Riccorl It could be a nvdia driver problem https://forums.developer.nvidia.com/t/known-limitations-with-cuda-on-wsl-2/128506

**Comment by Riccorl** [comment]
> @Riccorl It could be a nvdia driver problem https://forums.developer.nvidia.com/t/known-limitations-with-cuda-on-wsl-2/128506

Unfortunately, I'm using a Ryzen CPU. I think I should just wait then. Thank you for the link!

**Comment by Hendiadyoin1** [comment]
I'm not on the insider branch and from the blog entry it seems, that the rocm/rock and opencl apis arent yet supported, and therefore the hip library not functional.  
will there be support for these api's in the next "stable" version or do we have to wait for the amd devs to make a move on a windows compatible version of hip?

**Comment by onomatopellan** [comment]
New nvidia drivers 455.41 available should fix some freeze problems
https://developer.nvidia.com/cuda/wsl/download

**Comment by duxie** [comment]
My dream came true   ！！！
![image](https://user-images.githubusercontent.com/18651969/85226269-44c9c280-b409-11ea-8544-142bea815130.png)

**Comment by catskillsresearch** [comment]
Mark as complete? https://devblogs.nvidia.com/announcing-cuda-on-windows-subsystem-for-linux-2/

**Comment by Kyle2142** [comment]
Can someone please post the steps to get this working?
- I have windows build 20150
- I installed the WSL-compatible drivers (455.41) from nvidia's blogpost
- I have ubuntu on wsl 2
- /dev/dxg exists
- `sudo lspci` does not show my GPU

Sorry if this is hijacking the thread, but I do think my problem is "cannot find gpu devices on bash"

**Comment by onomatopellan** [comment]
@Kyle2142 what's the output of `uname -a` ? You need kernel 4.19.121 for cuda to work.

**Comment by Kyle2142** [comment]
> @Kyle2142 what's the output of `uname -a` ? You need kernel 4.19.121 for cuda to work.

please see edit above

**Comment by onomatopellan** [comment]
It seems the gpu is available only for the first wsl2 running distro. Try `wsl.exe --shutdown` and run the distro again. Can you see the libs in `/usr/lib/wsl/lib` ?

**Comment by Kyle2142** [comment]
```
>wsl --shutdown
>ubuntu1804
$ ls /usr/lib/wsl/lib/
libcuda.so  libcuda.so.1  libcuda.so.1.1  libd3d12.so  libdirectml.so  libdxcore.so
```
lspci still shows no nvidia device

**Comment by onomatopellan** [comment]
Any error message related to dxg in `sudo dmesg`?

**Comment by Kyle2142** [comment]
```
$ conda create -n torch python=3.7
$ conda activate torch
$ pip install torch -y
$ python -c 'import torch; print(torch.rand(2,3).cuda())'
tensor([[0.4829, 0.4576, 0.9950],
        [0.3608, 0.6088, 0.7283]], device='cuda:0')
```
It still does not show on `lspci` but the above works, I am sure the problem was running debian by default. Thank you for the assistance @onomatopellan and if you know who to ask, please document the gotcha of multiple distros!

**Comment by y0d4a** [comment]
> 
> 
> Can someone please post the steps to get this working?
> 
>     * I have windows build 20150
> 
>     * I installed the WSL-compatible drivers (455.41) from nvidia's blogpost
> 
>     * I have ubuntu 18.04 on wsl 2
> 
>     * kernel version 4.19.121-microsoft-WSL2-standard
> 
>     * /dev/dxg exists
> 
>     * `sudo lspci` does not show my GPU
> 
> 
> Sorry if this is hijacking the thread, but I do think my problem is "cannot find gpu devices on bash"

how did you upgrade the kernel? i have 4.19.104 and cannot upgrade to latest.. in downlaod section, only get source... do i need to compile?!

**Comment by onomatopellan** [comment]
@y0d4a You need to be in build 20150 it comes via Windows Update or with `wsl.exe --update`

**Comment by y0d4a** [comment]
aha, i have 20h2, ok tnx.

**Comment by Hendiadyoin1** [comment]
Again asking will and drivers and therfor rocm/hip sopport come to wsl or is there already a way to get it to work

**Comment by catskillsresearch** [comment]
I can't get WSL 2 and Ubuntu and NVidia GPU to work.  I started [a thread on AskUbuntu ](https://askubuntu.com/questions/1252964/please-help-configuring-nvidia-smi-ubuntu-20-04-on-wsl-2 )with my experience.  Microsoft/NVidia please help and contribute that thread to raise the visibility for the idea of having a complete, correct and simple set of instructions for WSL 2/Ubuntu/NVidia.  I am doing this on a Lenovo Yoga P40 with latest Windows fast track and Quadro M500M with latest NVidia drivers, as described in the thread.

**Comment by eternalphane** [comment]
> @y0d4a You need to be in build 20150 it comes via Windows Update or with wsl.exe --update

or you can manually build the [kernel](https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-4.19.y).

**Comment by ningacoding** [comment]
> how did you upgrade the kernel? i have 4.19.104 and cannot upgrade to latest.. in downlaod section, only get source... do i need to compile?!

Enable update for other Microsoft products.

![Vfqi3pA0rp](https://user-images.githubusercontent.com/17342546/85458053-4f4d9e80-b566-11ea-84af-40b3adcc96f0.gif)

**Comment by craigloewen-msft** [comment]
I'm marking this issue as complete, since the original ask (Making GPU devices available in WSL) is fulfilled. If you're running into specific issues please open another issue on this repo using our bug template! :)
