### ISSUE TITLE
Windows Update (KB5012599) perhaps rendered WSL unusable

### ISSUE THREAD

**Issue by vls-tomra** [microsoft/WSL#8290]
### Version

Microsoft Windows [Version 10.0.19044.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Debian / Ubuntu

### Other Software

Windows updates
KB5012599, 
perhaps also: KB5012117, KB5013437, KB5013354

### Repro Steps

I believe an update to windows destroyed my wsl machine. It can't be started and the directory `\\wsl$` is empty/(does not exist)

Starting my existing Debian WSL gives the error: 
Element not found.

Trying to Install new Ubuntu Distribution:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070490
Error: 0x80070490 Element not found.
```

is there any way to recover the files in my wsl debian instance?

### Expected Behavior

Starting Debian runs as usual.

### Actual Behavior

Debian does not run.

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/8488542/wsl.zip)

**Comment by Thernn88** [comment]
First check if Virtual Machine Platform is enabled in Windows Features. Maybe it was turned off. 

Also check CPU virtualization is enabled in the BIOS.

Failing that we should attempt to locate the .vdhx file were the image is stored.

Option1: Does the ext4.vdhx file still exist? This is where the distro image is stored. 
Open up regedit.exe and input the following into the address bar, hit enter to see such details:

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss

Under Lxss you should find all your WSL distro entries and and the BasePath key should give you the folder that a given distro's virtual drive file exists within.

Option2: Use WizTree and look for the biggest files on your disk, Likely the .vdhx file is among them.

Make a backup of the .vdhx image (for safety). 

1. You can try to extract the contents of the copy using 7zip. 
2. You can reinstall WSLg and then attach the .vdhx directly.

**Comment by benhillis** [comment]
Something is off with your trace, I'm not seeing any "element not found" error, but setting a single access denied error. Are you sure this was a repro trace started before observing the behavior and stopped after?

**Comment by vls-tomra** [comment]
@benhillis, the trace was actually of an instance where wsl did not start at all. This seems to be the case when I run it out of the console. As you can see in the trace it took almost an hour to exit without giving the user any error. What could have been the Problem was that the "Windows Hypervisor Platform" was disabled in the features. I can't really test this anymore as I am in the middle of reinstalling WSL and trying to attach the vdhx.

**Comment by vls-tomra** [comment]
Trying to reinstall Debian gives me the same error as I have had for Ubuntu:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070490
Error: 0x80070490 Element not found.

Press any key to continue...
```

[wsl2.zip](https://github.com/microsoft/WSL/files/8518796/wsl2.zip)

**Comment by vls-tomra** [comment]
After rebooting this seems to go away? Since I have done other things (messing around with network drivers) I'm not sure what really solved the issue...
