### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by YQisme** [microsoft/WSL#8292]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 18.04

### Repro Steps

I  downloaded Anaconda3 but I didn't activate it. The problem occurred when I downloaded other packages or unzipped a file.I think it will happen at other times.

### Expected Behavior

Successful results.

### Actual Behavior

When I use WSL2 in Terminal,it writes '[process exited with code 1 (0x00000001)]'.
When I use WSL2 in Terminal MobaXterm, it writes 'Remote side unexpectedly closed network connection'.

**Comment by owenschupp** [comment]
\logs

**Comment by YQisme** [comment]
> Hello! Could you please provide more logs to help us better diagnose your issue? You can find instructions on how to [attach logs here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), please make sure to post the link to the Feedback Hub item in this chat so we can see it.
> 
> Thank you!

Thanks for your reply. I've submitted it on the Feedback Hub. Here is the link:https://aka.ms/AAgny3u

**Comment by YQisme** [comment]
> /logs

https://aka.ms/AAgny3u

**Comment by YQisme** [comment]
Sorry, it's my fault. My virtual memory is set up wrong, I reset it, and now everything is normal.
