### ISSUE TITLE
Opening Terminal shows the following issue: The network name cannot be found.  [process exited with code 4294967295 (0xffffffff)]

### ISSUE THREAD

**Issue by AtrikGit6174** [microsoft/WSL#8293]
### Version

Microsoft Windows [Version 10.0.19044.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

kali-linux Kernel version: 5.10.102.1

### Distro Version

Distributor ID: Kali Description:    Kali GNU/Linux Rolling Release:        2022.1 Codename:       kali-rolling

### Repro Steps

1. Opening Terminal
2. response: 
The network name cannot be found.

[process exited with code 4294967295 (0xffffffff)]

![Uploading image.png…]()

3. Using "wsl.exe" in the cmd works perfectly.

### Expected Behavior

The Terminal shows the path location.

### Actual Behavior

![image](https://user-images.githubusercontent.com/64845750/163417156-fce6f25c-177d-40c8-9eaa-1e2af2b67cf4.png)

**Comment by elsaco** [comment]
@AtrikGit6174 is your Kali a fresh install? After pulling Kali from the MS store, `winget install --id=9PKR34TNCV07`, it stared okay. There is a Kali package served by the `winget` repository also.

Sample run:

![wsl_kali_store_fresh_install](https://user-images.githubusercontent.com/3933920/163471989-9bc29b06-cb71-4504-8cfa-e57cc642579f.png)

OS info `Microsoft Windows [Version 10.0.19044.1645]`

**Comment by AtrikGit6174** [comment]
@elasco
I think I installed it in July 2021, and I get the same response as you for "cat /etc/*-release"
I had opened my Kex using cmd after I had created the issue.
-> wsl.exe"
-> kex --esm --ip
-> kex --esm -stop

I opened the terminal again and now it is working fine.

Again, I tried using kali-undercover after I had RDP'ed to the Kex, and I wasn't able to exit the undercover mode (Shell & GUI Application responded that Undercover mode could only be use with Xfce4 panel. Of course I had that, or else I would not be able to switch on undercover). It didn't even show the "Windows-like" taskbar.
I switched back to the Windows cmd, "kex --esm --stop" and then again "kex --esm --ip". It opened kex in undercover mode with the taskbar, and this time the Kali shell inside Kex responded positively to "kali-undercover".

Some things surely do seem like magic.
If you have a guide or solution to permanently getting rid of these problems w/o ridding of Kali Linux, please show me the path!

Thanks a lot! 😄

**Comment by dakhar** [comment]
I had got same problem, when starting "wsl -d "DistroName"' from Windows Terminal.
Problem was solved, when I change "Starting directory" option in Settings for this distros from "~" to ".\".
![image](https://github.com/microsoft/WSL/assets/1272469/6d8546e1-dde6-4d12-a67d-68ba989b1456)
