### ISSUE TITLE
Enable CONFIG_USB_HIDDEV kernel flag by in the official kernel

### ISSUE THREAD

**Issue by davidshen84** [microsoft/WSL#8302]
**Is your feature request related to a problem? Please describe.**

The [usbipd-win][1] project, which is the official [recommended][2] way to connect USB devices from WSL to host devices, enables users to use their Yubico Key in the WSL environment. However, some Yubico features require the `CONFIG_USB_HIDDEV` to be enabled. E.g., the `pamu2fcfg` tool cannot read from the Yubico key without this feature.

[1]: https://github.com/dorssel/usbipd-win
[2]: https://docs.microsoft.com/en-us/windows/wsl/connect-usb

**Describe the solution you'd like**
Enable the `CONFIG_USB_HIDDEV` flag in the kernel by default.

**Describe alternatives you've considered**
not using WSL

**Additional context**

**Comment by Neurrone** [comment]
I would love to see this implemented as well.

**Comment by LazieKat** [comment]
YES PLEASE!

I am trying to connect an Intel Realsense camera to WSL2, it shows in `lsusb` but dmesg says `hid-generic 0003:8086:0B5C.0005: device has no listeners, quitting`

Reading online I found that enabling `CONFIG_USB_HIDDEV` should solve such an issue. I'm not so familiar with the Linux kernel but I wish there was a way to modify that without rebuilding the kernel.

**Comment by foxtrot75** [comment]
```
CONFIG_HIDRAW
CONFIG_USB_HIDDEV
```

Please

**Comment by davidshen84** [comment]
I have enabled these options and built my own WSL kernel, and it works very well, at least for my Yubikey.

I wonder if there's anything I can do to test the impact of this change.

**Comment by kelsey-steele** [comment]
CONFIG_HIDRAW and CONFIG_USB_HIDDEV are now enabled in the latest WSL2 kernel release [linux-msft-wsl-5.15.150.1](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.150.1)

Please keep in mind the kernel is released to the WSL2-linux-kernel repo first and will be included in an upcoming WSL release.

**Comment by luistango04** [comment]
I am grateful thank you! 

I spend many days trying t get work around for my peripheral cameras to work on Linux WSL because of this. I am testing it now with a realsense camera. building this from source.
