### ISSUE TITLE
Windows 11 Pro - .wslconfig ignored

### ISSUE THREAD

**Issue by mitsos1os** [microsoft/WSL#8304]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I am trying to add some configuration in `.wslconfig` regarding the [fractional scaling issue](https://github.com/microsoft/wslg/issues/23), however, it seems that my configuration in the file is being ignored

These are the contents of my file:
```
[system-distro-env]
WESTON_RDP_DISABLE_HI_DPI_SCALING=false
WESTON_RDP_DISABLE_FRACTIONAL_HI_DPI_SCALING=false
WESTON_RDP_DEBUG_DESKTOP_SCALING_FACTOR=200

```
![image](https://user-images.githubusercontent.com/8208733/163811793-b5f97e99-789c-4401-ae8e-4b3fcc93518e.png)

You can see that it is:
 - in the correct location
 - correct filename
 - correct encoding

However, it does not get picked up. According to the thread I should be able to see the added vars in `/mnt/wslg/weston.log` but this is not the case for me.

Also, note that I have issued `wsl --shutdown` before checking to see if it is there, and also did a full restart

### Expected Behavior

I would expect the options to get picked up and appear in `weston.log` as they are supposed to.
Most importantly to have the effect of the linked WSLg fractional scaling issue.

### Actual Behavior

Seems like the `.wlsconfig` is ignored

**Comment by benhillis** [comment]
These files go in %userprofile%\.wslgconfig

**Comment by mitsos1os** [comment]
Ohhhhhh sh**t... Thanks!
