### ISSUE TITLE
No access on a LUKS encrypted drive with BTRFS filesystem via Windows Explorer

### ISSUE THREAD

**Issue by nemihome** [microsoft/WSL#8306]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel-Version: 5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I have mounted a LUKS enrypted drive with BTRFS file system via:
GET-CimInstance -query "SELECT * from Win32_DiskDrive"

In this case drive 4 is the one which I do need:
wsl --mount \\.\PHYSICALDRIVE4 --bare

lsblk

Find the drive which is the one which should be mounted in Linux:
in this case sdc

Unlock:
sudo cryptsetup luksOpen /dev/sdc1 cryptroothd

Mount:
sudo mount -o compress=zstd:1 /dev/mapper/cryptroothd /wd12tb
or
sudo mount -o compress=zstd:1 /dev/mapper/cryptroothd /mnt/wsl/wd12tb

After that the drive is fully usable within WSL. But I get no access via explorer. In the first case /wd12tb is just shown as directory and the mount is ignored
In the second case I'm getting the error message that access is not possible and maybe I have no rights. 

If I try explorer.exe from the wd12tb folder (mount point) I'm getting the error invalid argument. One folder higher (which means without the mount) this is working.

When I access the folder via Samba this is working but that's an additional layer which should not be necessary and it will cost performance.

### Expected Behavior

According to this guide access should be possible via Windows Explorer:
https://devblogs.microsoft.com/commandline/servicing-the-windows-subsystem-for-linux-wsl-2-linux-kernel/

### Actual Behavior

Access via Windows Explorer is not possible

### Diagnostic Logs

[wsl.zip](https://github.com/microsoft/WSL/files/8511493/wsl.zip)

**Comment by OneBlue** [comment]
Thanks for reporting this @nemihome. 

If you're mounting in /wd12tb, the issue is probably [this](https://github.com/microsoft/WSL/issues/5999#issuecomment-720728455)


Regarding the mount in /mnt/wsl .
What's the default user of your distro ? That what's the explorer access files as, so if the mount isn't accessible to the user, then the explorer can't access.

What I'd recommend would to do something like:

```
sudo mount -o compress=zstd:1 /dev/mapper/cryptroothd /mnt/wsl/wd12tb o uid=my-user -o gid=my-user
```

That way the mount should be accessible by the explorer

**Comment by nemihome** [comment]
Hello @OneBlue  Thanks for reply

Default user is root. That's the same which did the mount. So basically that should work.

I also tried to set another user (same name which is logged on in windows with all groups mapped to it) but that did not help.

The options uid / gid seems to be not supported in this way. At least the command does not work.
sudo mount -o compress=zstd:1 /dev/mapper/cryptroothd /mnt/wsl/wd12tb -o uid=0 -o gid=0
I also tried just one -o with only UID.

sudo mount -o uid=0 /dev/mapper/cryptroothd /mnt/wsl/wd12tb

mount: /mnt/wsl/wd12tb: wrong fs type, bad option, bad superblock on /dev/mapper/cryptroothd, missing codepage or helper program, or other error.

I also tried it with 1002 instead of 0 (that's the user which I created with the same name than Windows logon user) but if root is standard user and mount is done with it that should work, shoudn't it? And at least if I start "explorer.exe ." in Ubuntu command prompt the user which is logged on should be used for access in my opinion. But this is also not working.

**Comment by OneBlue** [comment]
Thanks @nemihome. uid & guid are a bit misleading, they actually take user / group names (and not identifiers).

But if the default user is root that's probably not the issue. 

Can you follow the [Records WSL logs manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) section and share the log file of a repro, along with the content of `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` ?

**Comment by elsaco** [comment]
@nemihome WSL filesystem access from Windows is provided by `drvfs` driver. `ext4` is supported, however `btrfs` might not be at this time.

**Comment by nemihome** [comment]
> Thanks @nemihome. uid & guid are a bit misleading, they actually take user / group names (and not identifiers).
> 
> But if the default user is root that's probably not the issue.
> 
> Can you follow the [Records WSL logs manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) section and share the log file of a repro, along with the content of `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` ?

Thank you. I have taken a look in manpage of mount. The option uid / gid seems to be depending on file system. I have not found them for BTRFS.

The log is already included in the first post as zip. 

The Regedit entry is 2

**Comment by nemihome** [comment]
> @nemihome my previous comment about `drvfs` not supporting `btrfs` is void. It does work with `btrfs` encrypted partitions also.

Thank you for sharing. So basically that should work.

**Comment by nemihome** [comment]
@elsaco Thank you. That is really strange. Seems to be the behavior is different on my system. You are on 21H2?

**Comment by OneBlue** [comment]
@nemihome: I just realized that you're probably hitting #6711. Can try to you install [Store WSL][https://aka.ms/wslstorepage) which has the fix and see if that fixes the issue ?

**Comment by nemihome** [comment]
@OneBlue That's it. Thank you.
