### ISSUE TITLE
WSL2 distro shell can't launch an executable copied from outside

### ISSUE THREAD

**Issue by ptrts** [microsoft/WSL#8308]
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Alpine Linux v3.15.0

### Repro Steps

In Windows create a file like this

C:\hello.sh
```
#!/bin/ash
echo Hello!
```
Open the Alpine distro shell
```
wsl --distribution Alpine
```
Now you're in the shell

Switch to the home directory
```
cd
```
Copy the script here
```
cp /mnt/c/hello.sh .
```
Make it executable
```
chmod agu+x
```
Try to launch it
```
./hello.sh
```
The output will be like this
```
-ash: ./hello.sh: not found
```
At the same time, launching it like this would work (thought it wouldn't have worked if it had been a binary executable rather than a script)
```
$ ash hello.sh
Hello!
```

### Expected Behavior

If being in a distro shell your most recent history is like this

```
$ ls -l

-rwxr-xr-x    1 pavel    pavel           25 Apr 19 19:10 hello.sh

$ cat ./hello.sh

#!/bin/ash
echo Hello!
```

then if you enter this

```
$ ./hello.sh
```

you should get this

```
Hello!
```

### Actual Behavior

```
$ ls -l

-rwxr-xr-x    1 pavel    pavel           25 Apr 19 19:10 hello.sh

$ cat ./hello.sh

#!/bin/ash
echo Hello!

$ ./hello.sh
-ash: ./hello.sh: not found
```

**Comment by OneBlue** [comment]
Thanks for reporting this @ptrts.

Can you please share the output of:

```
strace -f ./hello.sh
```

When hello.sh fails to execute ?

**Comment by elsaco** [comment]
@OneBlue it's because of difference between Windows and Linux return, the `^M` problem. 

Here's sample run:

```
RIPPER:~# ./hello.sh
ash: ./hello.sh: not found
RIPPER:~# sed -i 's/\r$//' hello.sh
RIPPER:~# ./hello.sh
Hello!
```

Use `sed` or `dos2unix` to fix scripts created on Windows side.

**Comment by ptrts** [comment]
@OneBlue, in regards to the shell script part of the issue, as @elsaco pointed out, it's the ^M characters indeed
