### ISSUE TITLE
Can't connect WSL Client to Windows Server on localhost

### ISSUE THREAD

**Issue by andrearosasco** [microsoft/WSL#8312]
### Version

10.0.19044.1586

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 18.04

#### On Windows
```python
import socket

#Create a socket object.
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

#Bind the socket.
sock.bind(("127.0.0.1", 5050))

#Start listening.
sock.listen()

#Accept client.
print('Waiting for connections...')
client, addr = sock.accept()
print('Connection received')
```
####  On WSL
```python
import socket

#Create a socket object.
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

#Connect to the server.
print('Connecting to process...')
sock.connect(("172.30.160.1", 5050))
print('Connected to process')
```

### Repro Steps

I found the IP `172.30.160.1` in `/etc/resolv.conf` and allowed connection from the WSL by running `New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow`.

If I run `ping "$(hostname).local"` I'm able to ping the IP. 

### Expected Behavior

I was expecting a successful connection between client and server.

### Actual Behavior

When I start the client on WSL while the server is running on Windows it hangs until it returns a time-out error after some time.
Also `nc -zv 172.30.160.1 5050` from WSL fails to connect to the open port.

Running both server and client either on Windows or WSL works without any problem.

**Comment by Biswa96** [comment]
You have to allow inbound connection in Windows Firewall. WSL2 is just a VM and assumed as a separate machine.

**Comment by andrearosasco** [comment]
Shouldn't `New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow` have created a rule to allow inbound connection? Before running it `ping "$(hostname).local"` didn't work but after I ran it an inbound rule got created and `ping "$(hostname).local"` started working.

**Comment by elsaco** [comment]
@andrearosasco you won't be able to connect to host's `127.0.0.1`, a.k.a `localhost`, from inside WSL2. But you can bind your Windows socket to the IP address returned by `Get-HnsEndpoint` cmdlet. That's also the address you see in `/etc/resolv.conf`. On Linux side bind your socket to the IP  of `eth0`. Then you'll be able to communicate between host and vm. Open the firewall to allow python to communicate over this private networks. On Windows you'll get the familiar pop-up warning, if the firewall is was opened already:

![python_firewall_warning](https://user-images.githubusercontent.com/3933920/164567641-beb34c45-d731-477d-a8a3-7cb6ae91cbc4.png)


Sample output from Windows side:

```
PS C:\Users\Toor> py
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sock.bind(('172.21.128.1', 5050))
>>> sock.listen()
>>> client, addr = sock.accept()
>>> print(client)
<socket.socket fd=332, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.21.128.1', 5050), raddr=('172.21.138.138', 5050)>
>>> print(addr)
('172.21.138.138', 5050)
```

and from WSL2 side:

```
toor@beta:~$ sudo python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sock.bind(('172.21.138.138', 5050))
>>> sock.connect(('172.21.128.1', 5050))
```

**Comment by andrearosasco** [comment]
It worked! I feel stupid for not having tried this before... I thought the Windows server still needed to listen on localhost and that somehow the requests from the WSL sent to the IP address returned by Get-HnsEndpoint were forwarded to Windows localhost.
Thanks a lot :)
