### ISSUE TITLE
Error code 0xd0000022 when trying to start WSL after Windows Update 22598.200

### ISSUE THREAD

**Issue by BobbyWibowo** [microsoft/WSL#8313]
### Version

Microsoft Windows [Version 10.0.22598.200]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

* Update to Windows Insiders build `22598.200`
* Attempt to start WSL

### Expected Behavior

Starts normally

### Actual Behavior

```cmd
PS C:\Users\bobby> wsl
Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
Error: 0xd0000022
```

### Diagnostic Logs

Log created with wsl.wprp: https://i.fiery.me/Eexz.etl

**Comment by benhillis** [comment]
@BobbyWibowo - this is a pretty niche issue, but I have something that should work for you.

1. Make sure WSL optional component is installed.
2. Uninstall the WSL "app"
3. Attempt to launch your distro
4. The upgrade should complete.
5. Re-install the WSL "app" (wsl.exe --update)

**Comment by benhillis** [comment]
Long story short, the logic in wslservice.exe for upgrading old distro file systems needs to be updated to not use per-thread case sensitivity.

**Comment by cnchenpu** [comment]
Uninstall wsl-app solve the error, but the error happened again after re-install (--update) it.
