### ISSUE TITLE
Windows crashed by using WSL interpreter

### ISSUE THREAD

**Issue by Perenn1s** [microsoft/WSL#8314]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-22000-Microsoft 

### Distro Version

Ubuntu 20.04

### Other Software

PyCharm 2022.1 (Professional Edition) #PY-221.5080.212
Miniconda (in wsl)
Python 3.10

### Repro Steps

(Not sure if this step is necessary) Create a Conda environment in wsl. [environment.yml.txt](https://github.com/microsoft/WSL/files/8536571/environment.yml.txt)

Specify WSL interpreter in PyCharm with my conda environment.

Stopped at any breakpoint and click stop(to quit debugger)

### Expected Behavior

Quit debug process.

### Actual Behavior

Windows crashed and reboot.

### Diagnostic Logs

![image](https://user-images.githubusercontent.com/38245945/164590324-8448f55f-3c73-4a5f-8fd3-5638599e9da3.png)

Log Name:      System
Source:        Microsoft-Windows-Kernel-Power
Date:          4/21/2022 12:19:19 PM
Event ID:      41
Task Category: (63)
Level:         Critical
Keywords:      (70368744177664),(2)
User:          SYSTEM
Computer:      PexMachina
Description:
The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" />
    <EventID>41</EventID>
    <Version>8</Version>
    <Level>1</Level>
    <Task>63</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000400000000002</Keywords>
    <TimeCreated SystemTime="2022-04-21T16:19:19.8007453Z" />
    <EventRecordID>557</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="8" />
    <Channel>System</Channel>
    <Computer>PexMachina</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="BugcheckCode">313</Data>
    <Data Name="BugcheckParameter1">0x3</Data>
    <Data Name="BugcheckParameter2">0xffffcc0f0d1070b0</Data>
    <Data Name="BugcheckParameter3">0xffffcc0f0d107008</Data>
    <Data Name="BugcheckParameter4">0x0</Data>
    <Data Name="SleepInProgress">0</Data>
    <Data Name="PowerButtonTimestamp">0</Data>
    <Data Name="BootAppStatus">0</Data>
    <Data Name="Checkpoint">0</Data>
    <Data Name="ConnectedStandbyInProgress">false</Data>
    <Data Name="SystemSleepTransitionsToOn">0</Data>
    <Data Name="CsEntryScenarioInstanceId">0</Data>
    <Data Name="BugcheckInfoFromEFI">false</Data>
    <Data Name="CheckpointStatus">0</Data>
    <Data Name="CsEntryScenarioInstanceIdV2">0</Data>
    <Data Name="LongPowerButtonPressDetected">false</Data>
  </EventData>
</Event>

Log Name:      System
Source:        Microsoft-Windows-Kernel-Power
Date:          4/21/2022 9:15:53 PM
Event ID:      41
Task Category: (63)
Level:         Critical
Keywords:      (70368744177664),(2)
User:          SYSTEM
Computer:      PexMachina
Description:
The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" />
    <EventID>41</EventID>
    <Version>8</Version>
    <Level>1</Level>
    <Task>63</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000400000000002</Keywords>
    <TimeCreated SystemTime="2022-04-22T01:15:53.5554265Z" />
    <EventRecordID>786</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="8" />
    <Channel>System</Channel>
    <Computer>PexMachina</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="BugcheckCode">313</Data>
    <Data Name="BugcheckParameter1">0x3</Data>
    <Data Name="BugcheckParameter2">0xffffcc05a31f70b0</Data>
    <Data Name="BugcheckParameter3">0xffffcc05a31f7008</Data>
    <Data Name="BugcheckParameter4">0x0</Data>
    <Data Name="SleepInProgress">0</Data>
    <Data Name="PowerButtonTimestamp">0</Data>
    <Data Name="BootAppStatus">0</Data>
    <Data Name="Checkpoint">0</Data>
    <Data Name="ConnectedStandbyInProgress">false</Data>
    <Data Name="SystemSleepTransitionsToOn">0</Data>
    <Data Name="CsEntryScenarioInstanceId">0</Data>
    <Data Name="BugcheckInfoFromEFI">false</Data>
    <Data Name="CheckpointStatus">0</Data>
    <Data Name="CsEntryScenarioInstanceIdV2">0</Data>
    <Data Name="LongPowerButtonPressDetected">false</Data>
  </EventData>
</Event>

**Comment by Perenn1s** [comment]
It actually worked in wsl2

**Comment by DanPinGF** [comment]
From what I'm looking at from the screenshot, it seems you've experienced a Stop error (blue screen) when trying to run WSL as there are 'BugCheck' entries in the System event log. What was the Stop code by any chance?

**Comment by benhillis** [comment]
Could you please file an issue on FeedbackHub? That would allow me to look at dumps sent from your machine.

/logs

**Comment by Perenn1s** [comment]
I can not repeat the bug because I moved my environment to wsl2 already. Everything is ok now.
