### ISSUE TITLE
`%1 is not a valid Win32 application.` when trying to start WSL

### ISSUE THREAD

**Issue by Steve-Tech** [microsoft/WSL#8316]
### Version

Microsoft Windows [Version 10.0.22593.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Trying to start WSL, e.g. `wsl` in CMD, Ubuntu in Windows Terminal, Docker desktop, basically doing anything relying on WSL.

### Expected Behavior

I was expecting it to work.

### Actual Behavior

`%1 is not a valid Win32 application.` gets printed.
![image](https://user-images.githubusercontent.com/19366353/164613867-5623c272-5360-412b-bd88-e4c2f853268e.png)
![image](https://user-images.githubusercontent.com/19366353/164614085-31a97aae-09f8-4e25-b715-4f1db028b5f5.png)

Docker desktop also errors
![image](https://user-images.githubusercontent.com/19366353/164614048-666d5d2d-394b-47f7-8130-a4d7a8192b0c.png)

**Comment by DanPinGF** [comment]
Hmm, could it be a faulty WSL installation?

**Comment by Steve-Tech** [comment]
So, I've done a `wsl --update` (it didn't error), unticking and reticking WSL in the Windows features dialog, and installing another version of Ubuntu off the store; none of those seemed to do anything.

I don't really want to nuke my current install of Ubuntu because I've got things on there, I've tried `wsl --export` and it errors out as well.

**Comment by benhillis** [comment]
@OneBlue - could you please take a look at this?  Seems like it may be wslservice.exe crashing.  @Steve-Tech - can you check if wslservice.exe is running?  If not, can you try running "sc start wslservice" and seeing if it is able to?

**Comment by Steve-Tech** [comment]
Here's the feedback hub item: https://aka.ms/AAgqwrg

WslService was stopped, but no change after starting.

**Comment by Steve-Tech** [comment]
Oh, it works now, maybe it needed a restart after starting the service.
