### ISSUE TITLE
Clock skew detected during build

### ISSUE THREAD

**Issue by bengalih** [microsoft/WSL#8318]
### Version

Microsoft Windows [Version 10.0.19042.1348]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04.4 LTS

### Repro Steps

When building a kernel I would often get multiple clock skew errors as has been discussed in prior bugs such as #4975 when performing a:

`sudo make -j 8`

During compile my Vmmem and COM Surrogate processes are taking up close to 100% of my CPU cycles.
This is on a i7-3820QM:

```
bengalih@MOBILEONE:/mnt/c/Users/bengalih$ getconf _NPROCESSORS_ONLN
8
```
As my system date/time appears normal when starting the build process, I theorized that the heavy hit to the CPU may have been contributing to a small clock drift during compile time.  I tested this theory by running with:

`sudo make -j 6`

I performed at least 3 builds each using 6 and 8 respectively and without fail the clock skew error appeared when using the full 8 core, but never when I ran with 6.
(EDIT: On last build with "6" I did get one skew error when I also opened a zoom meeting on my device during build.  This was an anomaly as on all other 6 builds I did not get any skew and on the 8 runs I would get multiple per run).

While this is not a "bug" per-se, many people seeing this issue at build time may be in a similar situation where they are using slightly older processors.  However, it may be considered a bug that the kernel scheduler is not reserving cycles for keeping time in sync (as there have been reported other clock skew issues outside of just build).

I wanted to give this as a PSA for others having the issue, and maybe a more official note can be made somewhere, perhaps in the build instructions:

https://github.com/microsoft/WSL2-Linux-Kernel

### Expected Behavior

clock can remain in sync even when running highly CPU intensive tasks.

### Actual Behavior

clock appears to lose time when running highly CPU intensive tasks.

### Diagnostic Logs

make[3]: warning:  Clock skew detected.  Your build may be incomplete.

**Comment by bengalih** [comment]
Update.  Upon doing more testing, it appears that this issue isn't wholly eliminated by reducing the number of processing cores.  However it does seem that the occurrences are considerably less when using less than the number of cores available in the system.  The occurrence when using fewer cores may have to do with other processing (outside of WSL) that is taking place on the system.  Note some instances that occurred on one test using only 4 cores (where CPU appeared to average closer to 80% for WSL):

` AR      drivers/video/backlight/built-in.a
make[2]: Warning: File 'drivers/video/backlight/modules.order' has modification time 0.021 s in the future
  AR      drivers/video/fbdev/core/built-in.a
make[3]: Warning: File 'drivers/video/fbdev/core/modules.order' has modification time 0.025 s in the future
  AR      drivers/video/fbdev/omap2/omapfb/dss/built-in.a
make[5]: Warning: File 'drivers/video/fbdev/omap2/omapfb/dss/modules.order' has modification time 0.015 s in the future
  AR      drivers/video/fbdev/omap2/omapfb/displays/built-in.a
  AR      drivers/video/fbdev/omap2/omapfb/built-in.a
make[5]: warning:  Clock skew detected.  Your build may be incomplete.
  AR      drivers/video/fbdev/omap2/built-in.a
  AR      drivers/video/fbdev/built-in.a
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
  AR      drivers/video/built-in.a
make[2]: warning:  Clock skew detected.  Your build may be incomplete.`

Note the extremely small skew (0.025 s in the future) which shows that the overall date/time on the system is probably correct and that only a very small time drift appears to be happening.  My working theory is this is still due to WSL "loosing time" because of a heavily utilized CPU and poor kernel scheduling not keeping time in sync.

**Comment by bengalih** [comment]
Additional update:  

I'm not sure what is happening.  In my first 3 builds with -`j 8` set I averaged ~6 clock skew errors per run.
When I changed it to `-j 6` I had 2 runs with no issues and the third with only 1 skew event.
All of these runs nothing else was happening on the system other than some light web browsing.

However, on additional runs trying reducing values as low as `-j 1` I have runs with multiple skew events.
I believe that @rupor-github may be correct in his observation here:
https://github.com/microsoft/WSL/issues/4975#issuecomment-623163116

As this appears to not give these errors when run in an ext4 mount like `/home`, but do occur on a 9p NTFS mount like `/mnt/d/data`.

I don't see an active bug for a similar issue as most deal with loss of time over the course of days or when waking from sleep, such as #5324 #4677 and #4975.  All of these have been closed with what doesn't seem like much of a solution.

As stated, the clock is synced properly prior to the `make` being issued and apparently goes off by milliseconds during the build causing these errors.

I also notice that the build process takes a fraction of the time (maybe 50-70% less time when being run on the ext4 mount than the 9p mount).  I believe at the very least there needs to be more visibility in the documentation, ,best practices, etc, on the limitations of the 9p mounted systems.

Were we able to mount external drives (physical or VHDX), this might be easier to mitigate on other file systems, but #7940 excludes Windows 10 users from being able to mount an ext4 drive.

**Comment by makersite-dkeil** [comment]
Might be related to #8204

I also face this issue but I haven't found a reliable trigger for it. It may or may not be triggered by sleep/resume with WSL running but even a WSL shutdown and restart of the VM does not fix it afterwards.

```
# chronyc tracking
Reference ID    : B97DBE3A (prod-ntp-5.ntp4.ps5.canonical.com)
Stratum         : 3
Ref time (UTC)  : Wed Dec 14 10:14:02 2022
System time     : 3.982856989 seconds fast of NTP time
Last offset     : -4.546419621 seconds
RMS offset      : 4.450622082 seconds
Frequency       : 74443.312 ppm fast
Residual freq   : -79802.383 ppm
Skew            : 14688.409 ppm
Root delay      : 0.034386788 seconds
Root dispersion : 4.902681828 seconds
Update interval : 63.8 seconds
Leap status     : Normal
```

```
wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

**Comment by craigloewen-msft** [comment]
/dupe#10006

We're migrating all clock skew issues to a megathread so we can keep the top comment up to date with any updates and work arounds. Thank you for filing this!
