### ISSUE TITLE
Zooming in GnuPlot plot which was created from Octave leads into segmentation fault

### ISSUE THREAD

**Issue by thesalmonidae** [microsoft/WSL#8325]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

GNU Octave, version 5.2.0
gnuplot 5.2 patchlevel 8

### Repro Steps

Run following commands in the console at WSL2 Ubuntu 20.04:

Install octave:

```
sudo apt install octave
```

Install gunplot

```
sudo apt install gnuplot
```

Start octave:

```
octave
```

Type octave commands:

```
x = -10:0.1:10;
y = sin(x);
p = plot(x, y);
```

Now, the GnuPlot window containing the plot should open. Select +z or -z, and click the plot.

### Expected Behavior

The plot would be zoomed in or zoomed out without crashing.

### Actual Behavior

Octave crashes.

### Diagnostic Logs

```
octave:1> x = -10:0.1:10;
octave:2> y = sin(x);
octave:3> plot(x, y);
octave:4> fatal: caught signal Segmentation fault -- stopping myself...
Segmentation fault
```

**Comment by psymbio** [comment]
Any resolution to this?

**Comment by thesalmonidae** [comment]
At least I am not aware of any.

**Comment by thesalmonidae** [comment]
I'll try to check this at weekend.

**Comment by thesalmonidae** [comment]
```
PS C:\WINDOWS\system32> .\collect-wsl-logs.ps1                                                                                                                                                                                                  
    Directory: C:\WINDOWS\system32


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/30/2022   8:05 PM                WslLogs-2022-05-30_20-05-45
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
get-acl : Cannot find path 'C:\ProgramData\Microsoft\Windows\WindowsApps' because it does not exist.
At C:\WINDOWS\system32\collect-wsl-logs.ps1:35 char:1
+ get-acl "C:\ProgramData\Microsoft\Windows\WindowsApps" | Format-List  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
    + FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand

Log collection is running. Please reproduce the problem and press any key to save the logs.
Saving logs...
Press Ctrl+C to cancel the stop operation.
100%  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
The trace was successfully saved.
Logs saved in: C:\WINDOWS\system32\WslLogs-2022-05-30_20-05-45.zip. Please attach that file to the GitHub issue.
```



[WslLogs-2022-05-30_20-05-45.zip](https://github.com/microsoft/WSL/files/8799908/WslLogs-2022-05-30_20-05-45.zip)

**Comment by OneBlue** [comment]
Hmm I'm not seeing anything in the logs.

Can you share the output of `strace -f [your command]` when it crashes ?

**Comment by Joakim-Wallman** [comment]
@OneBlue Do you still need the strace -f output?
I have uploaded the strace from my system. Let us know if you need more information.

[octavestrace.txt.gz](https://github.com/microsoft/WSL/files/9863686/octavestrace.txt.gz)

**Comment by profiling** [comment]
I got the same problem. I  follow the steps from  https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#5-install-and-use-a-gui-package 

when I zoom+ the  fractal image generated after run juliatest, I got sinal 11 in wsl2.
