### ISSUE TITLE
Cant upgrade dist to wsl 2 (required by Docker desktop)

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/WSL#8326]
### Version

Microsoft Windows [Version 10.0.19044.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

wsl -l -v reports that my ubuntu dist is on swl1

Running wsl --set-version ubuntu 2 

### Expected Behavior

Distribution is updated to wsl 2

### Actual Behavior

Get error

> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
> For information please visit https://aka.ms/wsl2-install

I have that feature installed 

![image](https://user-images.githubusercontent.com/817577/164972986-0fac6fee-01aa-4af3-a3cc-33a177ce9032.png)

I have AMD SVM enabled in bios (Asus HERO VIII)

**Comment by AndersMalmgren** [comment]
I tried to unregister my ubuntu wsl 1 dist. And setr default to wsl and register a new ubuntu dist. Now I get this error instead

> WslRegisterDistribution failed with error: 0x80370102
> Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

I tried uninstallaing Hyper-V and Virtual Machine Platform, restart, reinstall them, restart. Didnt help still error above

**Comment by Biswa96** [comment]
Does `bcdedit` show `hypervisorlaunchtype Auto`?

**Comment by AndersMalmgren** [comment]
> Does `bcdedit` show `hypervisorlaunchtype Auto`?

I tried enabling that. Didn't help

**Comment by AndersMalmgren** [comment]
Installing windows 11 now to see if that helps

**Comment by AndersMalmgren** [comment]
Installing windows 11 did the trick actually.

**Comment by Biswa96** [comment]
I'm using exactly same OS version as in the original post. Merely reinstalling Windows OS and switing to WSL2 will fix more than half of the issues here.

**Comment by AndersMalmgren** [comment]
> I'm using exactly same OS version as in the original post. Merely reinstalling Windows OS and switching to WSL2 will fix more than half of the issues here.

Not very user friendly is it
