### ISSUE TITLE
Please restore the /upgrade config option of wslconfig.

### ISSUE THREAD

**Issue by ytrezq** [microsoft/WSL#8332]
Lastest wsl update removed support for the Volfs leaving only DrvFs in wsl1. And before that, the options for upgrading from Volfs was removed because it was considered buggy.

Please at least restore the possibility to upgrade instead of leaving all my work unreadable.

**Comment by benhillis** [comment]
Very sparse on details here - what versions are you referring to here?

**Comment by ytrezq** [comment]
@benhillis the latest I installed through Windows update last Friday on my Windows 10 insider preview build.
After that, every files appeared as missing in the legacy install path. Also, as this is a bug, please remove the feature label.

`wsl --update` was repurposed and `wslconfig` complains the `/update` flag is no longer recognized.

**Comment by ytrezq** [comment]
@benhillis but please add the bug label.
