### ISSUE TITLE
Running Windows Programs from WSL ignores the first argument

### ISSUE THREAD

**Issue by IsaacOscar** [microsoft/WSL#8335]
### Version

WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.613

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

openSUSE Tumbleweed 20220424

### Repro Steps

Since I installed the windows store version of WSL, executing windows programs from wsl no longer works properly.

Specfically, when I run any windows program from WSL, the first argument to it will be ignored:

* `cmd.exe "anything here" "/?"` acts just like `cmd.exe "/?"` would in windows, i.e. it prints the help for `cmd.exe`
* `cmd.exe "anything here" /C "echo hello"` acts like `cmd.exe /C "echo hello"`, i.e. it prints `hello`
* `cmd.exe` alone, without any arguments, does nothing except set the exit status to 1.

The same behaviour occurs for other windows programs, I've tested `wsl.exe`, `reg.exe` and even `explorer.exe`

I hypothesis that it is using the first argument as the program name (i.e. as argv[0]), however I don't know how to check this.

Bat files are even weirder:
* running `./foo.bat args...` seems to just do `cmd.exe /C args...`, regardless of the contents of `foo.bat`, provided that file is readable and non-empty.
* running `./foo.bat` without any arguments, does nothing but set the exit status to 1.

The same behaviour occurs if I proceed my WSL commands with `/init`.

### Diagnostic Logs

This is my `/etc/wsl.conf` file:

```
[automount]
root = /
enabled = true
options = "metadata,umask=022,case=dir"
mountFsTab = true

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
appendWindowsPath = true

[user]
default = root
```

And my `C:\Users\Isaac\.wslconfig` file:
```
[wsl2]
guiApplications=true
memory=26084MB # 80% of total hardware ram
processors=16 # number of hardware threads
```

**Comment by elsaco** [comment]
@IsaacOscar what is the output of `cat /proc/sys/fs/binfmt_misc/WSLInterop`? Thx!

**Comment by IsaacOscar** [comment]
> @IsaacOscar what is the output of `cat /proc/sys/fs/binfmt_misc/WSLInterop`? Thx!

```
# cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: F
offset 0
magic 4d5a
```

**Comment by IsaacOscar** [comment]
Ok, I've determined the issue is actually with https://github.com/arkane-systems/genie,
things work normally untill I start `genie`.
So it's probably a bug with the latter and now WSL itself.
