### ISSUE TITLE
Windows Subsystem for Linux + Docker + WSL 2 in Conflict with USB GPO

### ISSUE THREAD

**Issue by mgenevrier** [microsoft/WSL#8337]
### Version

Microsoft Windows 10 21H2 build 19044.1645

### WSL Version

- [X] WSL 2
- [x] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

All

### Other Software

Docker Desktop 3.3.3

### Repro Steps

1/. A Windows 2019 v.1809 build 17763.2746 server with Active Directory.

2/. A Microsoft Windows 10 21H2 build 19044.1645 post client in the domain.

3/. A GPO blocking USB devices on client workstation 
Only the following GUID classes were allowed:
{5989FCE8-9CD0-467D-8A6A-5419E31529D4}
{53D29EF7-377C-4D14-864B-EB3A85769359}
{E0CBF06C-CD8B-4647-BB8A-263B43F0F974}
{CA3E7AB9-B4C3-4AE6-8251-579EF933890F}
{745A17A0-74D3-11D0-B6FE-00A0C90F57DA}
{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}
{4D36E96B-E325-11CE-BFC1-08002BE10318}
{4D36E96E-E325-11CE-BFC1-08002BE10318}
{4D36E96F-E325-11CE-BFC1-08002BE10318}
{D94EE5D8-D189-4994-83D2-F68D7D41B0E6}
{36FC9E60-C465-11CF-8056-444553540000}
{36FC9E60-C465-11CF-8056-444553540000}
{C166523C-FE0C-4A94-A586-F1A80CFBBF3E}
{4D36E96C-E325-11CE-BFC1-08002BE10318}
{4D36E97D-E325-11CE-BFC1-08002BE10318}

4/. Activation of the windows subsystem for linux
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

5/. Activate the virtual machine functionality
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

6/. WSL installation
wsl --install

7/. WSL2 installation
download from: https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

8/. Installation of Docker

9/. Installation of the latest Debian distribution on the windows store

10/. Upgrade to WSL2
wsl --set-version <distro name> 2 

11/. Launching Docker   

12/. See the following errors :
It is no longer possible to install a distribution (error 0x80041002) as for the distributions that was already installed, these are no longer seen by WSL.

### Expected Behavior

Docker connects well when the GPO is disabled on the client PC. 

As soon as the GPO is applied it is not possible to launch Docker anymore due to the WSL error

### Actual Behavior

It is no longer possible to install a distribution (error 0x80041002) as for the distributions that was already installed, these are no longer seen by WSL.

**Comment by mgenevrier** [comment]
GPO Info :
Computer Configuration\Policies\Administrative Templates\System\Device Installation\Device Installation Restrictions
* Allow administrators to override Device Installation Restriction policies : Enable
* Allow installation of devices using drivers that match these device setup classes : Enable

**Comment by mgenevrier** [comment]
Here are the logs when the error occurs

[WslLogs-2022-05-06_10-15-50.zip](https://github.com/microsoft/WSL/files/8638595/WslLogs-2022-05-06_10-15-50.zip)

**Comment by OneBlue** [comment]
Thanks @mgenevrier.

Based on the logs, I can see that problem is that the swap disk (C:\\Users\\mgenevrier\\AppData\\Local\\Temp\\swap.vhdx) can't be attached to the machine.

Based on your build number, I think it's because this folder is either encrypted or compressed (since support for that was added in a later build).

Does adding this:

```
[wsl2]
swap=0
```

In `%USERPROFILE%/.wslconfig` solve the issue ?

**Comment by mgenevrier** [comment]
Hello,

Thank you for your feedback, unfortunately the proposed solution does not work.

Here attached the .wslconfig file created and the log report when Docker is launched
[.wslconfig.txt](https://github.com/microsoft/WSL/files/8661575/default.wslconfig.txt)
[log.txt](https://github.com/microsoft/WSL/files/8661576/log.txt)

As a reminder, everything works fine when the USB restriction policy is disabled

**Comment by OneBlue** [comment]
Thank you @mgenevrier. Just checking, did you create the config file as "%USERPROFILE%/.wslconfig", or "%USERPROFILE%"/.wslconfig.txt" ? 

If you're still experiencing the issue with the .wslconfig changes, can you please run [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) again and share the logs ?

**Comment by mgenevrier** [comment]
Hello the created file is well as follows: "%USERPROFILE%/.wslconfig"

Here are the last log

[WslLogs-2022-05-11_09-23-27.zip](https://github.com/microsoft/WSL/files/8667662/WslLogs-2022-05-11_09-23-27.zip)
![01](https://user-images.githubusercontent.com/104441998/167793949-3c2c3c8f-23e4-487b-8a7c-979ea4e05254.PNG)
![02](https://user-images.githubusercontent.com/104441998/167793951-2b73c7b9-4406-4ac0-bb70-c4129349a1ad.PNG)
s

**Comment by OneBlue** [comment]
Thank you @mgenevrier.

Based on the logs I can see that the issue is that WSL fails to create the VHD for docker-desktop (in `C:\Users\mgenevrier\AppData\Local\Docker\wsl\distro\ext4.vhdx`).

I wonder if that's because this folder is encrypted or compressed (since your Windows build doesn't support VHD is compressed / encrypted folders).

Can you share the output of `(get-item C:\Users\mgenevrier\AppData\Local\Docker\wsl\distro).Attributes` in a powershell prompt (if that folder doesn't exist anymore, replace it with the parent folder) ? 

If this folder is indeed encrypted or compressed this should be fixed by disabling encryption / compression manually for that folder, or by upgrading to a more recent Windows build, which would add support for such folders

**Comment by mgenevrier** [comment]
Hello, thank you for your feedback.

Here is the return of the requested operations, moreover I confirm that the hard disk is not encrypted.
![05](https://user-images.githubusercontent.com/104441998/168014342-6658cd90-9be7-41b8-ac04-9fceebe0f36e.PNG)
![03](https://user-images.githubusercontent.com/104441998/168014346-7366dce5-ad5a-4266-b7fa-6e7c2343319e.PNG)
![04](https://user-images.githubusercontent.com/104441998/168014348-190d224e-6f3c-48a9-b213-fafa6c417f0f.PNG)

**Comment by mgenevrier** [comment]
Hello,

I'll try again, the problem is still not solved. Were you able to reproduce the problem and find a solution?

**Comment by mgenevrier** [comment]
relance .... someone was able to solve this problem?

**Comment by mgenevrier** [comment]
Re-UP

**Comment by mgenevrier** [comment]
Hello,

I'll try again, the problem is still not solved. Were you able to reproduce the problem and find a solution?
