### ISSUE TITLE
WSL sometimes won't boot up and cause the whole system stuck

### ISSUE THREAD

**Issue by liyafe1997** [microsoft/WSL#8338]
### Version

22598.200

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian Testing

### Repro Steps

just run wsl.exe or run Debian in the start menu.

### Expected Behavior

The bash comes out 

### Actual Behavior

![屏幕截图 2022-04-26 163155](https://user-images.githubusercontent.com/18359157/165324050-5500b753-1424-405d-ad68-0736c9f12756.png)

It cames nothing in the terminal. It also unable to shutdown by wsl --shutdown (also stuck like this).
Then after few seconds/minutes, the whole Windows stucked, only mouse can move, everything no response, Ctrl+Alt+Del also doesn't work. Only thing I can do is power off my computer by long press powerbutton.

It does not always happen. If the bash came out, it will works fine unless you shutdown WSL. I think about 50% chance it happens. 

### Diagnostic Logs
![1](https://user-images.githubusercontent.com/18359157/165325724-447a9bba-e1a4-4efc-a948-01ea609b154e.png)

I can't grab the log file if this happened. Because if the WSL stucked at boot up, even the system seems still working, but all the modern UWP Apps (include the Feedback App) can't start. It stucked at the LOGO, then the whole system become stucked.

If I don't start WSL or the WSL start successfully, everything include the Feedback App works fine.

**Comment by OneBlue** [comment]
Thanks for reporting this @liyafe1997.

If Feedback hub doesn't work, can you try [recording logs manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually)  ? (see the 'Record WSL logs manually' section)

**Comment by liyafe1997** [comment]
> Thanks for reporting this @liyafe1997.
> 
> If Feedback hub doesn't work, can you try [recording logs manually](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) ? (see the 'Record WSL logs manually' section)

If the WSL stucked, even the wpr also got stuck when I run wpr -stop wsl.etl
![00](https://user-images.githubusercontent.com/18359157/165633912-d3eceb7b-f395-4c9d-b4dc-8451a05fc07a.png)

**Comment by liyafe1997** [comment]
I grabbed the log when I was able to start WSL successfully, I don't know if it is helpful or not. 
[wsl.zip](https://github.com/microsoft/WSL/files/8577998/wsl.zip)

**Comment by OneBlue** [comment]
Thanks @liyafe1997.

In the logs I can see: ` init: (1) WARNING: Debian root file system is compressed, performance may be severly impacted.`.

This might be the reason why it's hanging. 

Does this also happen if you register a brand new distribution (with let's say wsl --install ubuntu) ?

**Comment by liyafe1997** [comment]
> Thanks @liyafe1997.
> 
> In the logs I can see: ` init: (1) WARNING: Debian root file system is compressed, performance may be severly impacted.`.
> 
> This might be the reason why it's hanging.
> 
> Does this also happen if you register a brand new distribution (with let's say wsl --install ubuntu) ?

Yes it is compressed, I always use it as compressed(it can save a lot of disk space), but I am pretty sure it is not this problem, because 1. Before Win11 22598 everything works fine, I have been using this WSL disto with compressed vhdx for months. 2. Even I have **tried to decompress it**, this problem **still happens**, nothing changed. 

I haven't tried to install another disto, but I can try it later. But I guess it is not this problem. Because seems if something happened "inside" WSL, it shouldn't make the whole Windows stucked. I mean, things inside the VM shouldn't impact outside world, this is a security problem.

**Comment by liyafe1997** [comment]
Seems this problem has gone after upgraded to Win11 22610.1
But I am not pretty sure because it happens randomly before, but at least, I have used this new version of OS for 3 days and have no problem with WSL.

**Comment by OneBlue** [comment]
Closing since the issue is solved after an OS upgrade.
