### ISSUE TITLE
WSL2 consumes memory as much as 13GB when installing Microsoft SQL Server inside.

### ISSUE THREAD

**Issue by kanhaiyabaranwal** [microsoft/WSL#8341]
### Version

Microsoft Windows 10 Enterprise [10.0.19044 N/A Build 19044]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Microsoft SQL Server 2019 Express Edition

### Repro Steps

I am installing Microsoft SQL Server 2019 Express Edition inside WSL2. I am doing it to use my linux application along with SQL server inside Windows environment.

Issue: SQL Server consumes almost 13 GB during installation time. The installation itself fails many times if less memory is available. It kills the unix process silently. 

Both SQL Server and WSL2 is notorious to consume as much memory as it can. In my case, the installation fails many times which is a very ugly experience. Setting .wslconfig to less memory like 8GB restricts the memory, but installation itself fails many times. Setting SWAP memory to 16GB does not help.

How to avoid? 

### Expected Behavior

SQL Server installation should complete with 8GB of memory.

### Actual Behavior

SQL Server installation fails silently.

**Comment by elsaco** [comment]
@kanhaiyabaranwal how are you installing `mssql-server`? Using the instructions at https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15 works w/out needing lots of memory:

```
tux@RIPPER:~$ apt show mssql-server
Package: mssql-server
Version: 15.0.4198.2-10
Priority: extra
Section: misc
Maintainer: Microsoft Data Platform Group <dpgswdist@microsoft.com>
Installed-Size: 1196 MB
Depends: libatomic1, libunwind8, libnuma1, libc6, adduser, libc++1, gdb, debconf, hostname, openssl (>= 1.0.1g), python3, libgssapi-krb5-2, libsss-nss-idmap0, gawk, sed, libpam0g, libldap-2.4-2, libsasl2-2, libsasl2-modules-gssapi-mit, tzdata
Conflicts: mssql-server-agent
Breaks: mssql-server-fts (<< 15)
Replaces: mssql-server-agent
Download-Size: 253 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal/main amd64 Packages
Description: Microsoft SQL Server Relational Database Engine
 The mssql-server package contains the Microsoft SQL Server Relational Database Engine.

```

The above test was done with a 4GB WSL memory reservation.

**Comment by pmartincic** [comment]
If you open another shell to the same terminal can you post what `top` shows?
