### ISSUE TITLE
ADB hangs while trying to connect to daemon host

### ISSUE THREAD

**Issue by Newbie012** [microsoft/WSL#8342]
### Version

Microsoft Windows [Version 10.0.22000.613]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Android Debug Bridge version 1.0.41
Version 33.0.1-8253317
Installed as /home/eliya/dev/Android/platform-tools/adb

### Repro Steps

1. wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
2. unzip commandlinetools-linux-8092744_latest.zip /home/user/dev/Android/cmdline-tools
3. sdkamanger "platform-tools"
4. `adb --version`
5. receive output above
6. `adb devices`

### Expected Behavior

Should output the devices list or an empty list

### Actual Behavior

Hangs for a few moments and then fails with timeout error:

```
adb W 04-28 16:43:11 20145 20145 network.cpp:149] failed to connect to '172.23.160.1:5037': Connection timed out
* cannot start server on remote host
adb: failed to check server version: cannot connect to daemon at tcp:172.23.160.1:5037: failed to connect to '172.23.160.1:5037': Connection timed out
```

### Diagnostic Logs

more information in my original question - https://stackoverflow.com/questions/72044894/adb-devices-hangs-and-after-a-while-times-out-on-wsl2?noredirect=1#comment127301497_72044894

**Comment by elsaco** [comment]
@Newbie012 what Java version are you using? I did a quick test with `openjdk-8-jre` and `adb` starts okay:

```
tux@RIPPER:~/dev/Android/platform-tools$ ./adb --version
Android Debug Bridge version 1.0.41
Version 33.0.1-8253317
Installed as /home/tux/dev/Android/platform-tools/adb
tux@RIPPER:~/dev/Android/platform-tools$ ./adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
```

Java info:
```
tux@RIPPER:~/dev/Android/platform-tools$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

OS info:
```
tux@RIPPER:~/dev/Android/platform-tools$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

WSL info:
```
PS C:\Users\elsaco> wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 3/26/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

**Comment by Newbie012** [comment]
@elsaco 

```
➜  platform-tools ./adb --version
Android Debug Bridge version 1.0.41
Version 33.0.1-8253317
Installed as /home/eliya/dev/Android/platform-tools/adb

➜  platform-tools ./adb devices
adb W 04-28 23:45:32  2862  2862 network.cpp:149] failed to connect to '192.168.0.1:5037': Connection timed out
* cannot start server on remote host
adb: failed to check server version: cannot connect to daemon at tcp:192.168.0.1:5037: failed to connect to '192.168.0.1:5037': Connection timed out

➜  platform-tools java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

**Comment by elsaco** [comment]
What is the output of `strace ./adb devices`?

**Comment by Newbie012** [comment]
I think I fixed it.

@elsaco I eventually removed and purged:
1. java
2. android studio
3. android SDK

and then reinstalled only android studio, but it still didn't work, so I was almost certain it doesn't have to do with Ubuntu.

After hours of trying to figure out, it turns out I had to kill `adb.exe` and everything went well.

Thank you for your help!
