### ISSUE TITLE
3 vmmem processes using 50% RAM at idle

### ISSUE THREAD

**Issue by github-account1111** [microsoft/WSL#8350]
### Version

Microsoft Windows [Version 10.0.22000.652]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Docker Desktop

### Repro Steps

Do a full reboot (Alt+f4 > Restart).

### Expected Behavior

Nothing is using unnecessary amounts of memory.

### Actual Behavior

My computer is idling at 8/16GB, mostly because of WSL - that is absolutely dismal by any standards.
There are 3 vmmem processes that are consistently at the top of memory usage no matter what I'm doing, even on a fresh boot:

![image](https://user-images.githubusercontent.com/5728319/165885107-74b035dc-e57b-4acc-ac46-48b448a4099b.png)

They're so hungry I've been unable to use Hyper-V because the VM simply didn't have enough memory to start.

The top one is Docker because after I close Docker Desktop it disappears in ~a minute.
Now, that's still _a lot of memory_ considering it stays like that even after I purge all containers and even all images (basically all data).
The thing is literally _idling at 3 Gigs._
How's that okay?

But the worst part is I've no idea _where the other 2 processes come from_.
Process Explorer just shows `NT VIRTUAL MACHINE\82BB62F0-45A5-4621-8EAF-DA18D3931FBB` and `NT VIRTUAL MACHINE\929700F8-219B-4AC1-AE76-594EE6E7BD62`.
I know it's not my Hyper-V VM because:
1. Hyper-V isn't even on.
1. The Hyper-V VM has a different ID:
```
> get-vm | foreach {Write-Host NT VIRTUAL MACHINE\$($_.Id) - $($_.VMName)}
NT VIRTUAL MACHINE\932c7f5b-757d-4b9a-a04d-53b5f517910e - win11
```

**Comment by benhillis** [comment]
Could you pleas share the output of `hcsdiag.exe list`?
