### ISSUE TITLE
Unable to upgrade/change from WSL 1 to WSL 2 version.

### ISSUE THREAD

**Issue by ravikiran-talluri** [microsoft/WSL#8351]
### Version

Microsoft Windows [Version 10.0.20348.643]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

I installed wsl  using the command "wsl --install -d ubuntu" - it is installed Version 1
Output of: wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         1

I am trying to update the version with following commands

```
PS C:\Users\Administrator> wsl --set-version Ubuntu-20.04 2
There is no distribution with the supplied name.

wsl --set-version Ubuntu 2 --> This command giving me the help page
wsl --set-default-version 2 --> This command giving me the help page
```

I am using a Microsoft Windows Server 2022 Base from amazon: ami-03fe02556b17692cb (64-bit (x86))

### Expected Behavior

https://docs.microsoft.com/en-us/windows/wsl/install --> As per these document "wsl --install" should install Version 2 but not happening and also wsl should get updated to version 2 when we use the listed commands in the document but not happening.

### Actual Behavior

![image](https://user-images.githubusercontent.com/94987319/165885921-df601c26-4c88-4ef9-a037-f779be92c3ca.png)

**Comment by pmartincic** [comment]
What's the output of `wsl -v`?

**Comment by pmartincic** [comment]
Ignore that, missed that it was on 10.

**Comment by pmartincic** [comment]
We don't currently support WSL2 on server :(
