### ISSUE TITLE
WSL2 installs kernel 5.10.102.1 but using 4.19.104

### ISSUE THREAD

**Issue by JesperKrogPoulsen** [microsoft/WSL#8361]
### Version

10.0.22610.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Updated to Windows 11, updated wsl using wsl --update,  rebooted
```
PS C:\Users\Jesper> wsl -l -v
NAME STATE VERSION
* Ubuntu-22.04 Running 2

PS C:\Users\Jesper> wsl --update
Checking for updates...
No updates are available.
Kernel version: [5.10.102.1](https://5.10.102.1/)

PS C:\Users\Jesper> wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2

Windows Subsystem for Linux was last updated on 01/05/2022
WSL automatic updates are on.

Kernel version: [5.10.102.1](https://5.10.102.1/)
```

Launching wsl and look at kernel version:
```
/mnt/c/Users/Jesper$ cat /proc/version
Linux version 4.19.104-microsoft-standard (jkp@DESKTOP-DKG6ENQ) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #5 SMP Mon Jun 15 23:43:17 CEST 2020
```

### Expected Behavior

cat /proc/version should return kernel 5.10.102.1

### Actual Behavior

/proc/version returns kernel 4.19.104

**Comment by elsaco** [comment]
Ubuntu 22.04 pulled from the MS Store has id `9PN20MSR04DW` and the kernel is indeed `5.10.102.1`. What is the output when you run `winget show --name 'Ubuntu 22.04 LTS'` or `winget show --id 9PN20MSR04DW`?

Sample output:

```
PS C:\Users\valli> winget show --id 9PN20MSR04DW
Found Ubuntu 22.04 LTS [9PN20MSR04DW]
```

**Comment by JesperKrogPoulsen** [comment]
They both show the right ID:

`PS C:\WINDOWS\system32> winget show --id 9PN20MSR04DW                                                                                                                                                                                                                            Found Ubuntu 22.04 LTS [9PN20MSR04DW] ` 
`PS C:\WINDOWS\system32> winget show --name 'Ubuntu 22.04 LTS'                                                                                                                                                                                                                    Found Ubuntu 22.04 LTS [9PN20MSR04DW]     `

**Comment by 0xbadfca11** [comment]
> 4.19.104-microsoft-standard (jkp@DESKTOP-DKG6ENQ) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) <span>#</span>5 SMP Mon Jun 15 23:43:17 CEST 2020

This doesn't seem to be the kernel released by Microsoft.
Is kernel specified in .wslconfig?

**Comment by JesperKrogPoulsen** [comment]
@0xbadfca11 , THANKYOU!!! That was it. I had totally forgotten about .wslconfig. I had specified a custom kernel a year or two ago and completely forgotten about it. After deleting it, the kernel is the correct one.
