### ISSUE TITLE
CD into large Windows directory taking 100% CPU and never return

### ISSUE THREAD

**Issue by Cerclique** [microsoft/WSL#8363]
### Version

Microsoft Windows [Version 10.0.22000.652]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Directory location : `/mnt/d/my_dir` (local partition on my machine)
This is a 18Go Git directory containing 150k+ files.

- Launch Ubuntu through WSL
- `cd /mnt/d/my_dir`

### Expected Behavior

Command is changing my active directory as the one specified in the path and return.

### Actual Behavior

The command never return (I did let it run for ~20min before manually cancelling) . 
When looking at performance, I can see that my CPU is using constant 90-100% CPU on all cores.

If I `Ctrl+C`, I can see that the active directory is the one specified by the path (like the command succeeded) but any new command in the same directory (eg: ls) now have the same behaviour. 

Note: For other small directory in `/mnt/d`, I don't have the problem.

**Comment by OneBlue** [comment]
Thanks for reporting this @Cerclique.

Sadly this is expected if you have a folder with many, many files given that this has to go through our plan9 server.

It might be worsened by your shell prompt though.

Does doing something like this helps ? 

PS1='no-prompt$ ' 
cd /mnt/d/my_dir

**Comment by Cerclique** [comment]
Thanks for the information @OneBlue. 

Same behavior with your proposed trick.

If it's good for you, I think we can close this issue.
I'll look for a workaround on my own.
