### ISSUE TITLE
WSL2 host NAT issue, early expire and limited rules

### ISSUE THREAD

**Issue by TrevorMarvinPNNL** [microsoft/WSL#8369]
### Version

Microsoft Windows [Version 10.0.19042.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

A program is run within WSL.  It communicates with a device connected to a network that the host Windows computer is connected to.  It communicates via UDP.  It sends a packet to the remote device via UDP and receives a response.  That is expected and correct.  It then sends a UDP packet which solicits a continuing response of UDP packets from the device.  For a few minutes, these responses are received.  After a few minutes, the responses are being sent by the device but no longer received by the program within WSL.  I presume the NAT (between WSL and its Windows host) rule is being expired, even though responses are still being sent by the device (even at a frequency of about one per 5 seconds).  This issue was mitigated by sending null/dummy packets from the program within WSL at a regular interval.

### Expected Behavior

The expected behavior is that the dynamic NAT rule would not be expired while data is still being received from the the device at such a rate.  (At least once every 5 seconds.)  (Additionally, making the assumption that the loss of the connection is due to the NAT rule expiring, which is still open for review.)

### Actual Behavior

(Issue pretty much described in the Repro Steps section.)

**Comment by TrevorMarvinPNNL** [comment]
(The original report was edited due to realizing that the second issue reported was related to the fact that the NAT was mangling the UDP packet and changing the port numbers.  This is being resolved in a different way.  The original first issue still stands.)

**Comment by OneBlue** [comment]
Closing since the repro instructions are not actionable.

**Comment by TrevorMarvinPNNL** [comment]
Can action not be taken on changing the NAT tracking to not expire when data continues to be received from a remote device?
