### ISSUE TITLE
../sysdeps/posix/getaddrinfo.c:2583: error

### ISSUE THREAD

**Issue by raphaelquati** [Microsoft/WSL#838]
- A brief description
  I'm trying to install Qt in WSL using the installer.
  It starts to download the packages but it crashs with the error.
  I've checked other posts (check /etc/resolv.conf, /etc/hosts) with no success.
- Expected results
  No error
- Actual results (with terminal output if applicable)
  qt-unified-linux-x64-online.run: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(**extension** ({ const st
  ruct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 &
  & __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
  Aborted (core dumped)
- Your Windows build number
  Microsoft Windows [versão 10.0.14393]
- Steps / commands required to reproduce the error
  export DISPLAY=:0
  sudo touch /etc/mtab
  wget http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
  chmod 755 qt-unified-linux-x64-online.run
  ./qt-unified-linux-x64-online.run
- Required packages and commands to install
  Install [xming ](https://sourceforge.net/projects/xming/)

**Comment by fpqc** [comment]
If you're going to use a free X server, I suggest vcXsrv, although according to some sources, Colin Harrison's new versions of Xming on his website straightrunning support AIGLX rendering through WGL.

**Comment by therealkenc** [comment]
Ref #1202, #1113, #614 (and friends). This probably fixed in concert with #982. Unfortunately there is no good landing zone for the (partial?) IPv6 improvements done since the OP. In any event, the same `gettaddrinfo()` manifestation used to happen with `sshd` as well, and doesn't in recent releases. If the problem persists in recent versions of Qt please re-open a new issue.
