### ISSUE TITLE
Triple Fault - Kernel 5.10.102.1 

### ISSUE THREAD

**Issue by 1m0g** [microsoft/WSL#8387]
### Version

21H2 (Win 10) April 2022 build 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04 LTS

### Repro Steps

It's unclear if the bugs I experienced are related to the event described as a triple fault within event viewer and if it is reproducible or not. The issue is that the update catalog has a duplicate 5.10.102.1 kernel under the link for 5.10.102.2 (was it pulled?). Two serious bugs were experienced while attempting to create a sparse.img with dd (aligning sectors(count, seek, bs)); first, lock screen all of a sudden appears and I have to log back in, which was event id 1000 100 and shows the lock app crashed; other bug was also event id 1000 100 and within the same package as the lock app: screen went black but was still in active session as keyboard, sound, etc responded as if I was still navigating the desktop, but I had to force shutdown to get out of the display lock (crash of display service I assume). There is a serious issue with how the session allocates memory (how can I set the RAM limits of the subsystem without the need of a page file?), as the lock screen crash made me realize something is tampering with memory. Please look into why there is a duplicate of 5.10.102.1 instead of what is listed on the update catalog.

### Expected Behavior

WSL2 shouldn't be initiating a lock of my device while producing a sparse .img.  I'd like to know what can be done to prevent the issue from ever reoccuring. I have 8GB of RAM and the largest .img file mounted was 5.3GB and the result was a 6.5GB sparse .img which I did succeed in creating. Would the need of 6.5gb of RAM shut down basic system services triggering what I experienced? Forgot to note: I was not connected to the internet during the events experienced.

### Actual Behavior

Some sort of overflow crashing system services.

**Comment by benhillis** [comment]
Going to need a stack to help diagnose this, if you're running the store version of WSL can you please collect /logs?

If not, debug console will have the stack:

```
%userprofile%\.wslconfig
[wsl2]
debugConsole=true
```
