### ISSUE TITLE
WSL2 - DNS Issues(Temporary failure in name resolution) with VMWare workstation pro installed

### ISSUE THREAD

**Issue by zhizhang77** [microsoft/WSL#8390]
### Version

Microsoft Windows [version 10.0.19044.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Distro Version

Ubuntu 20.04

### Other Software

VMware® Workstation 16 Pro: version 16.2.3 build-19376536

### Repro Steps

I've used WSL2 on this PC for one year on this PC and it works perfect for me until yesterday. I installed VMware® Workstation 16 Pro together with Virtual Machine Platform. After reboot `sudo apt update` get jammed.  

An interesting detail is I can ping internet successfully before `sudo apt update` , but after that "Temporary failure in name resolution" appears when I'm pinging the same website.  Try it a few minutes later and it works again.  

Editing **/etc/resolv.conf** and set nameserver to 8.8.8.8 will resolve the issue temporary but I want to dig out the root cause if possible...

btw. I could't access my microsoft account in win10 after VMWare is installed.  Disabling VMware network adapter fixed this issue . But it won't help the WSL2 problem.

### Expected Behavior

`sudo apt update` work as usual.

### Actual Behavior

![130019](https://user-images.githubusercontent.com/24850729/167344040-a4b3c73d-6aa9-42c2-8e40-47d60443d7a4.jpg)

**Comment by ashoklathwal** [comment]
If you are getting a Temporary Failure In Name Resolution error on WSL2 then [follow these solutions ](https://wealthquint.com/fix-temporary-failure-in-name-resolution-wsl2-62554/)to fix the issue in no time
