### ISSUE TITLE
git-wsl documentation bug

### ISSUE THREAD

**Issue by wnim** [microsoft/WSL#8395]
### Version

10.0.19044.1526

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16.3

### Distro Version

Ubuntu  20.04

### Other Software

git 2.25.1 on wsl
git 2.36.1 on windows

### Repro Steps

Go here

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git

and follow "Git Credential Manager setup" steps

### Expected Behavior

>git push

should be successful

### Actual Behavior

>git push
/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe get: 1: /mnt/c/Program Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe: not found
Username for 'https://github.com': ^C

**Comment by wnim** [comment]
The solution is to change the step to this:

`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"`

because they moved the exe to a different directory

**Comment by owenschupp** [comment]
Closing due to the issue being solved above

**Comment by wnim** [comment]
> Closing due to the issue being solved above

Perhaps change the documentation as well?

**Comment by adthonb** [comment]
> Closing due to the issue being solved above

Page on this [document](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git) still `libexec/git-core/git-credential-manager-core.exe`

**Comment by sys13** [comment]
This should be reopened to fix the documentation

**Comment by benhillis** [comment]
https://github.com/MicrosoftDocs/WSL/pull/1556/files

**Comment by pmartincic** [comment]
I'm so confused: GCM tooling moved to new location. by pmartincic * Pull Request #1555 * MicrosoftDocs/WSL (github.com)<https://github.com/MicrosoftDocs/WSL/pull/1555>

**Comment by zzJZzz** [comment]
This was helpful for me in solving it.
https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/rename.md
I edited my ~/.config

This was the OLD
	`helper = /mnt/c/Program\\ Files/Git/mingw64/bin/git-credential-manager-core.exe`
	
This is the NEW
  ```
  helper =
    helper = /mnt/c/Program\\ Files/Git/mingw64/bin/git-credential-manager.exe
```
There is a blank helper on purpose. See the link above.

**Comment by kozell** [comment]
This might be related: [Git Credential Manager Rename](https://aka.ms/gcm/rename)

**Comment by ozumahe** [comment]
For version 2.34.1 this worked for me.
`git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"`

To check for the directory of git credential manager on you system, Do the following.
 
Check for the version of your git using `git --version`

**If GIT installed is >= v2.39.0**
- Open File Explorer 
- Open **Local Disk (C:)**
- Open **Program Files** Folder
- Open **Git** Folder
- Open **mingw64** Folder
- Open **bin** Folder
- search for **git-creadential** or any related file name with **.exe** extension

else if version is < v2.36.1 enter this command:
- Open File Explorer 
- Open **Local Disk (C:)**
- Open **Program Files** Folder
- Open **GIt** Folder
- Open **mingw64** Folder
- Open **libexec** Folder
- Open **git-core** Folder
- search for **git-creadential** or any related file name with **.exe** extension

**Comment by zephyrdark** [comment]
To add on, my git version is `git version 2.45.1.windows.1`. It does not contain `git-credential-manager-core.exe` but it does contain `git-credential-manager.exe`.

I setup my git in WSL via `git config --global credential.helper "/mnt/c/Program Files/Git/mingw64/bin/git-credential-manager.exe"` (and configs for user.name and user.email), which I validated that it works by successfully cloning a repo, committing, and pushing changes.
