### ISSUE TITLE
Would love to have ability to open USB serial devices.

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/WSL#840]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

I'm developing for this http://dev.px4.io/ and BashOnWindows can build this code base now which is awesome.  Now all I need is to upload the compiled code to the pixhawk light controller, and for that I need to be able to open a serial device "/dev/ttyS4" and read/write from it and set terminal interface settings, like this:

```
_io_fd = open(PX4IO_SERIAL_DEVICE, O_RDWR);

if (_io_fd < 0) {
    log("could not open interface");
    return -errno;
}

/* save initial uart configuration to reset after the update */
struct termios t_original;
tcgetattr(_io_fd, &t_original);

/* adjust line speed to match bootloader */
struct termios t;
tcgetattr(_io_fd, &t);
cfsetspeed(&t, 115200);
tcsetattr(_io_fd, TCSANOW, &t);
```

then it uses read(), write(), for actual data transfer, and close() when done....
- Expected results
  firmware upload succeeds 
- Actual results (with terminal output if applicable)
  fails to find the device
- Your Windows build number
  10.0.14393.0
- Steps / commands required to reproduce the error
  See  https://github.com/PX4/Firmware/blob/master/src/drivers/px4io/px4io_uploader.cpp
- Strace of the failing command
- Required packages and commands to install
  We do need a PX4 FMU Windows Driver to talk to this device, this makes the device appear to be a serial device.  It is a Windows USB CDC ACM Setup for USB RS-232 Emulation Driver.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

The inf for the windows driver is as follows:
    ;************************************************************
    ; Windows USB CDC ACM Setup File
    ; Copyright (c) 2000 Microsoft Corporation

```
[Version]
Signature="$Windows NT$"
Class=Ports
ClassGuid={4D36E978-E325-11CE-BFC1-08002BE10318}
Provider=%MFGNAME%
LayoutFile=layout.inf
CatalogFile=%MFGFILENAME%.cat
DriverVer=04/11/2013,2.0.0.0

[Manufacturer]
%MFGNAME%=DeviceList, NTamd64

[DestinationDirs]
DefaultDestDir=12


;------------------------------------------------------------------------------
;  Windows 2000/XP/Vista-32bit Sections
;------------------------------------------------------------------------------

[DriverInstall.nt]
include=mdmcpq.inf
CopyFiles=DriverCopyFiles.nt
AddReg=DriverInstall.nt.AddReg

[DriverCopyFiles.nt]
usbser.sys,,,0x20

[DriverInstall.nt.AddReg]
HKR,,DevLoader,,*ntkern
HKR,,NTMPDriver,,%DRIVERFILENAME%.sys
HKR,,EnumPropPages32,,"MsPorts.dll,SerialPortPropPageProvider"

[DriverInstall.nt.Services]
AddService=usbser, 0x00000002, DriverService.nt

[DriverService.nt]
DisplayName=%SERVICE%
ServiceType=1
StartType=3
ErrorControl=1
ServiceBinary=%12%\%DRIVERFILENAME%.sys

;------------------------------------------------------------------------------
;  Vista-64bit Sections
;------------------------------------------------------------------------------

[DriverInstall.NTamd64]
include=mdmcpq.inf
CopyFiles=DriverCopyFiles.NTamd64
AddReg=DriverInstall.NTamd64.AddReg

[DriverCopyFiles.NTamd64]
%DRIVERFILENAME%.sys,,,0x20

[DriverInstall.NTamd64.AddReg]
HKR,,DevLoader,,*ntkern
HKR,,NTMPDriver,,%DRIVERFILENAME%.sys
HKR,,EnumPropPages32,,"MsPorts.dll,SerialPortPropPageProvider"

[DriverInstall.NTamd64.Services]
AddService=usbser, 0x00000002, DriverService.NTamd64

[DriverService.NTamd64]
DisplayName=%SERVICE%
ServiceType=1
StartType=3
ErrorControl=1
ServiceBinary=%12%\%DRIVERFILENAME%.sys


;------------------------------------------------------------------------------
;  Vendor and Product ID Definitions
;------------------------------------------------------------------------------
; When developing your USB device, the VID and PID used in the PC side
; application program and the firmware on the microcontroller must match.
; Modify the below line to use your VID and PID.  Use the format as shown below.
; Note: One INF file can be used for multiple devices with different VID and PIDs.
; For each supported device, append ",USB\VID_xxxx&PID_yyyy" to the end of the line.
;------------------------------------------------------------------------------
[SourceDisksFiles]
[SourceDisksNames]
[DeviceList]
%DESCRIPTION%=DriverInstall, USB\VID_26AC&PID_0001, USB\VID_26AC&PID_0002, USB\VID_26AC&PID_0003, USB\VID_26AC&PID_0010, USB\VID_26AC&PID_0011, USB\VID_26AC&PID_0012, USB\VID_26AC&PID_0013, USB\VID_26AC&PID_0014

[DeviceList.NTamd64]
%DESCRIPTION%=DriverInstall, USB\VID_26AC&PID_0001, USB\VID_26AC&PID_0002, USB\VID_26AC&PID_0003, USB\VID_26AC&PID_0010, USB\VID_26AC&PID_0011, USB\VID_26AC&PID_0012, USB\VID_26AC&PID_0013, USB\VID_26AC&PID_0014


;------------------------------------------------------------------------------
;  String Definitions
;------------------------------------------------------------------------------
;Modify these strings to customize your device
;------------------------------------------------------------------------------
[Strings]
MFGFILENAME="CDC_vista"
DRIVERFILENAME ="usbser"
MFGNAME="3D Robotics"
INSTDISK="3DR PX4 Installer"
DESCRIPTION="PX4 FMU"
SERVICE="USB RS-232 Emulation Driver"
```

**Comment by russalex** [comment]
Thanks @lovettchris, it's a great writeup.

We have been tracking feature requests like this one over on our [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash).  It's a great place for people to see what others are requesting and up-vote on the features they would like to see us work on.  It's a direct line to help inform the team of what's important to the community.

For this particular one, we have had various requests for serial devices (see #415) or other requests for hardware interactions ([GPU access](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250010-ubuntu-shell-access-to-system-gpu-ability-to-run) being the big one).

**Comment by benhillis** [comment]
@lovettchris - Support for this was added in our most recent Windows Insider build.

**Comment by therealkenc** [comment]
Working on the assumption based on the `/dev/ttyS*` reference in the OP this is dupe #415.
