### ISSUE TITLE
Missing info in WSL configuration advanced options

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#8403]
### Version

10.0.22000.675

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

1. run `ubuntu2204.exe config`
2. click `Setup` and go to next screen
3. under `Auto-Mount` observe hint for the 2nd option

### Expected Behavior

valid hint

### Actual Behavior

![ubuntu2204 exe_config](https://user-images.githubusercontent.com/3933920/167932569-d768a911-c3be-4c4e-8083-31dac484aa6a.png)

**Comment by OneBlue** [comment]
Thanks for reporting this @elsaco.

This setting page is not part of WSL, so I'd recommend [creating an issue on launchpad](https://bugs.launchpad.net/ubuntuwsl)  instead
