### ISSUE TITLE
WSLENV variables not available during [boot]

### ISSUE THREAD

**Issue by anttiah** [microsoft/WSL#8406]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

Environment variables that are passed from Win32 to Wsl are not available when running commands from wsl.conf `[boot]` section.

Add command that dumps environment variables to a text file:
```
# Assuming that there is no [boot] section in /etc/wsl.conf
cat <<EOF | sudo tee -a /etc/wsl.conf > /dev/null
[boot]
command = env > /tmp/env_boot
EOF
```

Exit Wsl instance and terminate it from Win32 PowerShell by running `wsl -t ubuntu`.

Using PowerShell set the environment variables:
```
$env:TEST_ENV = 'This is not available during [boot]'
$env:WSLENV = 'TEST_ENV'
```

Start the Wsl instance from the same PowerShell by running `ubuntu`.

### Expected Behavior

The `/tmp/env_boot` file contains our `TEST_ENV` variable and its value.

```
$ grep TEST_ENV /tmp/env_boot
TEST_ENV=This is not available during [boot]
WSLENV=TEST_ENV
```

### Actual Behavior

The `/tmp/env_boot` file does not contain neither `TEST_ENV` nor `WSLENV` variables.

Variables are available only after interactive user session has started:
```
$ env > /tmp/env_run
grep TEST_ENV /tmp/env_run
TEST_ENV=This is not available during [boot]
WSLENV=TEST_ENV
```

**Comment by elsaco** [comment]
@anttiah do a `wsl --shutdown` not just terminate the instance for the changes to take effect. Be advised, this will terminate all your running WSL instances.

**Comment by anttiah** [comment]
> @anttiah do a `wsl --shutdown` not just terminate the instance for the changes to take effect. For the record, this will terminate all your running WSL instances.

Already tested it, as well as rebooting the whole Windows. Doesn't make difference.

**Comment by elsaco** [comment]
@anttiah is `WSLENV` available during boot also. It does show after booting:

```
tux@beta:~$ echo $WSLENV
WT_SESSION::WT_PROFILE_ID::Test123
```

`Test123` was the string assigned to `$env:TEST_ENV` and appended to `$env:WSLENV` in pwsh.

This is what `printenv` outputs when booting:

```
tux@beta:~$ cat /tmp/env_boot
WSL_DISTRO_NAME=Ubuntu-22.04
NAME=beta
WSL_FEATURE_FLAGS=1
PWD=/
WSL2_GUI_APPS_ENABLED=1
```
