### ISSUE TITLE
dmsetup does not show device in /dev/mapper/

### ISSUE THREAD

**Issue by CKingX** [microsoft/WSL#8409]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04 and Ubuntu 18.04 (both)

### Other Software

dmsetup (running sudo dmsetup --version gives this output in Ubuntu 20.04: Library version:   1.02.167 (2019-11-30) Driver version:    4.43.0) (running the version command on Ubuntu 18.04 gives this: Library version:   1.02.145 (2017-11-03) Driver version:    4.43.0)

### Repro Steps

We first need an image. 
1. For this quick demonstration, create one by running `truncate -s 8192 ./test.bin`. This will create an 8 KiB image (I kept it small as it should make it easy to test). 
2. Then, mount it. First, find an empty loop number with `losetup -f`. Finally, run `sudo losetup {/dev/loop#} ./test.bin` (replace loop# with whatever you got with losetup -f. You can verify by checking if the loop device exists in /dev/loop#
3. Finally run `sudo dmsetup create test --table "0 16 linear {/dev/loop#} 0"`

### Expected Behavior

This should create a device /dev/mapper/test

### Actual Behavior

The device does not show up on /dev/mapper/test. However, dmsetup did create it as you can tell with `sudo dmsetup ls`. On a real version of Ubuntu (in a VM and in dualboot), this correctly mounts the device.

**Comment by elsaco** [comment]
@CKingX WSL kernel has  `CONFIG_DM_MULTIPATH is not set`

**Comment by CKingX** [comment]
So there is no other way than compiling your own kernel?

**Comment by elsaco** [comment]
Compiling a new kernel works fine for WSL2. WLS1 no, because the integration with the host OS is different. Only in WSL2 you get the full Linux kernel to play with!

**Comment by CKingX** [comment]
Yeah I meant WSL2. Thanks for the information!

**Comment by ilan-schemoul** [comment]
It does not work even if DM_MULTIPATH enabled with the commands described by the original poster. Despite appearing in dmsetup ls it is not in /dev/mapper
/proc/config.gz
CONFIG_DM_MULTIPATH=y
CONFIG_DM_MULTIPATH_QL=y
CONFIG_DM_MULTIPATH_ST=y
CONFIG_DM_MULTIPATH_HST=y
CONFIG_DM_MULTIPATH_IOA=y
# CONFIG_DM_DELAY is not set
# CONFIG_DM_DUST is not set
CONFIG_DM_INIT=y
CONFIG_DM_UEVENT=y
CONFIG_DM_FLAKEY=y
CONFIG_DM_VERITY=y
CONFIG_DM_VERITY_VERIFY_ROOTHASH_SIG=y

**Comment by Torvin** [comment]
turns out it needed `sudo dmsetup mknodes`
