### ISSUE TITLE
Use bind mount for /tmp/.X11-unix for better compatibility.

### ISSUE THREAD

**Issue by dingdang66686** [microsoft/WSL#8411]
**Is your feature request related to a problem? Please describe.**
Some programs (Eg. snaps, flatpaks) need to remount it in the chroot environment. But symbolic link can't be remounted.

**Describe the solution you'd like**
Make it a bind mount instead of a symbolic link.

**Describe alternatives you've considered**
None.

**Comment by benhillis** [comment]
Good suggestion, I've made this change and it will be available in the future version of WSL.

**Comment by Chicken-Bones** [comment]
Has this fix been released? Encountered this issue with WSL and Steam today.
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
```

Error:
```
bwrap: Can't mount tmpfs on /newroot/tmp/.X11-unix: No such file or directory
```

Workaround (no idea if this is the correct way to do it):
```
sudo rm /tmp/.X11-unix
mkdir /tmp/.X11-unix
sudo mount --bind /mnt/wslg/.X11-unix /tmp/.X11-unix
```
