### ISSUE TITLE
Two different versions of WSL when I open as regular user versus Admin

### ISSUE THREAD

**Issue by Psychotechnopath** [microsoft/WSL#8415]
### Version

Microsoft Windows [Version 10.0.19043.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Just install Ubuntu20.04 from microsoft store on a system with my specifications. 

### Expected Behavior

When I try to run WSL on the laptop of my co-worker, regular user simply gives me a non su bash, whereas running as admin gives me a root @ bash (Which is more in line with what I would expect). 

Running as regular user:
![image](https://user-images.githubusercontent.com/47820228/168544791-32a2d07c-0726-4ca2-933f-aa5bdaf1fb2f.png)

Running as admin:
![image (1)](https://user-images.githubusercontent.com/47820228/168544875-6e5a9bea-e6cd-4d8c-be6b-c98238aba8a9.png)

### Actual Behavior

Recently, I have installed WSL on my company laptop - so I could use docker and Minikube on Windows. After some debugging with DNS settings I got it to work. Now I wanted to do the same for my co-worker, who has a similar laptop. However, going through the same process made me realize that something very strange is happening in my installation. There seem to be _two different_ installations when I run WSL as regular user versus running as admin user. 

I have done some investigating myself and will share the results here. 

First of all, running `wsl -l -v` gives me the following results:
![image](https://user-images.githubusercontent.com/47820228/168283843-2ad8535e-875b-4f01-ab46-6f331bc0bdf1.png)

So nothing seems off there. However, when I open my WSL as regular user and type some commands:
![wsl_regular_user](https://user-images.githubusercontent.com/47820228/168543941-c7955d51-81ca-46fb-abde-5aac469d1968.png)

You can see that I create an empty python file in my home dir `touch hoi.py`. Subsequently i run `ls` to see if it's there, and it is (also when I close and re-open WSL). 

Then, I open WSL as admin. The first thing that I notice is that a different version of ubuntu is shown in the MOTD: 20.04.4 LTS versus 20.04.3LTS in the regular user WSL:
![wsl_cool](https://user-images.githubusercontent.com/47820228/168544198-058c67f9-c506-4e59-98bd-f6d41fa99b30.png)

Also when I run `ls` to see whether my `hoi.py` file I created as regular WSL user - it is not. And when I run `docker `command (which gave a docker is not installed error in regular WSL user) it now correctly gives me docker options:
![image](https://user-images.githubusercontent.com/47820228/168285910-59470950-c26e-42bc-9a84-219da777f2f3.png)

**Comment by craigloewen-msft** [comment]
/dupe #5151 

We're tracking this as a feature request over at the issue linked! Thank you for filing
