### ISSUE TITLE
WSL2 won't boot up again after adding new user

### ISSUE THREAD

**Issue by VenRoot** [microsoft/WSL#8417]
### Version

10.0.22621.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian 11

### Repro Steps

Add a new user to the distro with adduser newuser

Reboot Windows

Try to start wsl

### Expected Behavior

WSL would start up and display the prompt

### Actual Behavior

WSL just gets stuck in the boot

### Diagnostic Logs

.wslconfig is empty, no custom kernel.
All packages were up to date, everything was working fine. 

I added the new user to connect my second github remote with a seperate user. Did some git stuff (git pull, git push), shutdown my pc, rebooted, wanted to continue working and wsl is just stuck at boot

WSL-Version: 0.58.3.0
Kernelversion: 5.10.102.1
WSLg-Version: 1.0.33
MSRDC-Version: 1.2.2924
Direct3D-Version: 1.601.0
Windows-Version: 10.0.22621.1

**Comment by elsaco** [comment]
@VenRoot add `debugConsole=true` to your `.wslconfig` to get more feedback, and start WSL under a different user, like `wsl -u root` or the user that was previously working. If it recovers fix whatever issue is with the new user.

**Comment by VenRoot** [comment]
Very wird...

Added the `debugConsole` option

Tried `wsl --system`, didn't work properly but the debug showed up

Tried again with just `wsl` and now it suddenly works... logging me in in my default user

But that you, @elsaco 

I'll reopen the issue once that happens again

Closes #8417
