### ISSUE TITLE
sshfs contents only visible in Windows Explorer when mounted in /mnt/wsl and /mnt/wslg

### ISSUE THREAD

**Issue by Seeky90** [microsoft/WSL#8423]
### Version

Microsoft Windows [Version 10.0.22000.434]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.02

### Other Software

SSHFS version 2.10.0
FUSE library version: 2.9.9
fusermount version: 2.9.9

### Repro Steps

mkdir /mnt/folder
mkdir /mnt/wsl/folder

sshfs -o reconnect,ServerAliveInterval=15,allow_other,password_stdin [username[@[ip]:/ /mnt/folder
sshfs -o reconnect,ServerAliveInterval=15,allow_other,password_stdin [username[@[ip]:/ /mnt/wsl/folder

#Verify that the content is visible in WSL
ls /mnt/folder
ls /mnt/wsl/folder

### Expected Behavior

Windows Explorer can show content in
\\wsl.localhost\Ubuntu-20.04\mnt\wsl\folder and 
\\wsl.localhost\Ubuntu-20.04\mnt\folder

### Actual Behavior

Windows Explorer can show content in:
\\wsl.localhost\Ubuntu-20.04\mnt\wsl\folder

but NOT in:
\\wsl.localhost\Ubuntu-20.04\mnt\folder and

**Comment by owenschupp** [comment]
If this is something that you want to be using frequently, my recommendation would be to place it in `/etc/fstab`- that should resolve your issue!

**Comment by Seeky90** [comment]
Hi @owenschupp 

your solution apprarently has nothing to do with the bug?
fstab does not offer me the versatality i am achieving with a script running in a cronjob. Hosts should be mounted if they are available, removed when they are gone.

Anyway, the bug still persists, despite anything you could write into fstab.
