### ISSUE TITLE
Unable to locate packages lib64readline-dev lib64readline8

### ISSUE THREAD

**Issue by beanboi7** [microsoft/WSL#8424]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04 

### Repro Steps

```
sudo apt-get install lib64readline-dev
sudo apt-get install lib64readline8
```

### Expected Behavior

A normal package installation success message should've come up

### Actual Behavior

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib64readline-dev
```
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib64readline8
```

**Comment by Biswa96** [comment]
It seems that your provided packages are wrong. Please find the correct package from here https://packages.ubuntu.com/search?keywords=libreadline&searchon=names&suite=jammy&section=all

**Comment by elsaco** [comment]
`lib32readline8` is 32-bit versions of `libreadline8`. There is no `lib64readline8` package in Focal, and `libreadline8` is installed by default. Same with the `dev` version.
