### ISSUE TITLE
"wsl --install" stuck on "Downloading: GUI App Support"

### ISSUE THREAD

**Issue by ChelsyMena** [microsoft/WSL#8429]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Repro Steps

wsl --install

### Expected Behavior

The installation completes successfully

### Actual Behavior

Although the Windows Subsystem and the WSL Kernel seem to install properly, the command gets stuck in the Downloading: GUI App Support step. For me at 53.7% although some people have reported online 97.5%

### Diagnostic Logs

C:\WINDOWS\system32>wsl --install
Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
Installing: WSL Kernel
WSL Kernel has been installed.
Downloading: GUI App Support
[==========================53,7%                           ]

**Comment by leimeter-joaquin** [comment]
I wanted to mention that I did 
- Fresh windows 11 install
- Updated
- Installed video drivers
- Windows: `Version 10.0.22000 Build 22000`
- Ran `wsl --isntall -d Ubuntu`
- Got the same output but stuck at 43%
- `ctrl + c` out after 30 minutes or so
- Attemped to restart got propmted that i needed to restart, did so
- Ran `wsl --list`  and got no distribution installed
- Ran `wsl --install -d Ubuntu` and installed ubuntu normally
- Using WSL Ubuntu just fine now
