### ISSUE TITLE
How to connect windows client proxy application to WSL2 [KALI LINUX TERMUX]

### ISSUE THREAD

**Issue by danksuperuser** [microsoft/WSL#8431]
I am using [Kali linux terminal] WSl in WINDOWS11

How to connect windows application proxy[local host] to WSL [KALI LINUX TERMINAL].
The proxy address is 127.0.0.1:9050

 I had tried 
 to set temporarily  ```export http_proxy=http://127.0.0.1:9050``` its failed & showing error connection refused.

Next 

I had tried adding this ``` export http_proxy=http://127.0.0.1:9050
export ftp_proxy=http://127.0.0.1:9050
https_proxy=http://127.0.0.1:9050``` 
**nano /etc/bash.bashrc** ,**nano ~/.bashrc**,**nano /etc/environment**

Nothing had worked.Hoping for a fast solution

THANKS IN ADVANCE

**Comment by Biswa96** [comment]
Please provide all the steps to reproduce this issue.

**Comment by danksuperuser** [comment]
@Biswa96 i don't think it is an issue.
How can i connect my connect windows application proxy[local host] to WSL [KALI LINUX TERMINAL].

**Comment by elsaco** [comment]
@danksuperuser what version of WSL are you using, WSL1 or WSL2? The networking is different between WSL1 and WSL2.

If you're using WSL2 set `portproxy` with `netsh`. The host firewall will have to be opened also.  Find your WSL2 endpoint IP and try, replace x.x.x.x with actual IP address:

`netsh interface portproxy add v4tov4 listenport=9050 connectport=9050 connectaddress=x.x.x.x protocol=tcp
`

then use `export http_proxy=http://x.x.x.x:9050` inside Kali. If you need UDP also, add another `portproxy` rule.

Might not work, didn't test it.

**Comment by danksuperuser** [comment]
I am using WSL 2.
Let me try this .

**Comment by danksuperuser** [comment]
@elsaco i tried it but it didn't work.

**Comment by OneBlue** [comment]
Thanks for reporting this @danksuperuser.

Can you share the exact steps for what you're trying to do ? Access a network endpoint running in Windows from within WSL or the opposite ?

**Comment by OneBlue** [comment]
Ok I see. So if you want to connect WSL to an application running on Windows, @elsaco's solution should work, as long as the socks proxy is listening on the correct address, but that might not be what you want, since that would open it to the whole network.

One thing can try is an ssh port proxy. If you run an ssh server in WSL, something like: ` ssh -R 9050:localhost:9050 user@localhost`  should forward the traffic into your socks proxy

**Comment by danksuperuser** [comment]
@OneBlue  No! @elsaco 's solution didn't work.

**Comment by elsaco** [comment]
@danksuperuser you also need to open the Windows firewall and allow inbound/outbound TCP traffic on port 9050, after you set the portproxy . If possible, disable the host firewall and see if proxy works as you'd expect. If it does, turn the firewall back on and add rules.

**Comment by elsaco** [comment]
`127.0.0.1:9050` means WSL's loopback interface not host's. You need to set your `http_proxy` in WSL to the `ip:port` linked with `netsh interface portproxy` rule.

The mapping should be, using 172.16.21.1 as example:

```
Windows proxy             WSL
127.0.0.1:9050 <-----> 172.16.28.1:9050
```

then set `http_proxy=171.16.21.8:9050` for your WSL clients.
