### ISSUE TITLE
zcat cannot be used

### ISSUE THREAD

**Issue by Shengbao-Bao** [microsoft/WSL#8434]
### Version

Microsoft Windows [version 10.0.19043.1706]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Ubuntu-22.04

### Repro Steps

 zcat test_R1.fq.gz | less -S
/usr/bin/zcat: 51: exec: gzip: Exec format error

### Expected Behavior

read the content of a gz file

### Actual Behavior

/usr/bin/zcat: 51: exec: gzip: Exec format error

### Diagnostic Logs

/usr/bin/zcat: 51: exec: gzip: Exec format error

**Comment by wangqr** [comment]
Might be related to #8219

**Comment by hakanai** [comment]
Tried to install nmap-common today, got the exact same error.

```
Setting up nmap-common (7.91+dfsg1+really7.80+dfsg1-2build1) ...
/usr/bin/zcat: 51: exec: gzip: Exec format error
dpkg: error processing package nmap-common (--configure):
 installed nmap-common package post-installation script subprocess returned error exit status 126
```

Trying to run just gzip:

```
$ gzip
-bash: /usr/bin/gzip: cannot execute binary file: Exec format error
```

Verdict: gzip executable is probably corrupt.

Who owns it?

```
$ dpkg --search /usr/bin/gzip
dpkg-query: no path found matching pattern /usr/bin/gzip
```

No package owns it, so it must be part of the base system. Here's what I have:

```
$ ls -la /usr/bin/gzip
-rwxr-xr-x 1 root root 97520 Apr  8  2022 /usr/bin/gzip
```

Usually "Exec format error" means you're trying to run a binary that wasn't built for the current system, but at least the file headers look normal:

```
$ file /usr/bin/gzip
/usr/bin/gzip: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=09387e1f48c88dcc27c89d83dec42856690b93b0, for GNU/Linux 3.2.0, stripped
```

And Ubuntu is:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by hakanai** [comment]
Looks like there is a second ticket, so this one can be considered a duplicate.
https://github.com/microsoft/WSL/issues/8219
