### ISSUE TITLE
WSL installation get stuck, then generate en error message

### ISSUE THREAD

**Issue by mikaelpeltier** [microsoft/WSL#8436]
### Version

Windows 11 Pro (1000.22000.675.0)

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

Default version installed by wsl --install

### Distro Version

Default version installed by wsl --install

### Other Software

No other Software used

### Repro Steps

wsl --install

### Expected Behavior

No error and installation should be done

### Actual Behavior

Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
Installing: WSL Kernel
WSL Kernel has been installed.
Downloading: GUI App Support
Installing: GUI App Support
GUI App Support has been installed.
Downloading: Ubuntu
A error was encountered during installation, but installation may continue. Component: 'Ubuntu' Error Code: 0x80072eff
The requested operation is successful. Changes will not be effective until the system is rebooted.

**Comment by xiaoboshuaia** [comment]
[WslLogs-2022-11-15_10-42-54.zip](https://github.com/microsoft/WSL/files/10008673/WslLogs-2022-11-15_10-42-54.zip)
