### ISSUE TITLE
Mouse Input not detected across entire terminal

### ISSUE THREAD

**Issue by RoiEXLab** [microsoft/WSL#8439]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Repro Steps

This is basically a duplicate of #7101, which is completely reproducible for me. So the repro steps remain the same:
 * Clone and build [ImTui ](https://github.com/ggerganov/imtui) and the example project.
 * Try to drag one of the windows to the far right of the terminal or hover over the right side of the terminal with the mouse cursor

I personally can reproduce this issue with a basic ncurses application, which seems to be the library imtui uses behind the scenes.

### Expected Behavior

The mouse input should be caught across the entire terminal width, even if the terminal window is maximised.

### Actual Behavior

At some specific offset the click event is no longer caught correctly.
Curiously enough this issue **_does not happen_** inside the console provided by Visual Studio code (when running with WSL integration). Because of  this, my best guess is that this doesn't seem to be an issue of WSL directly, but rather how the default console (and windows terminal too) interact with WSL

**Comment by craigloewen-msft** [comment]
Can you please file this on the Windows Terminal repo? This is best fixed by the Windows Terminal team:
http://github.com/microsoft/terminal

**Comment by RoiEXLab** [comment]
As i said, the issue isn't exclusive to windows terminal. It happens on the default wsl window too. Can the terminal team do something about that too?
