### ISSUE TITLE
All the windows act 'selected to unselected loop' at a frequency same with mouse cursor

### ISSUE THREAD

**Issue by wangjunbo4** [microsoft/WSL#8440]
### Version

10 / 11

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

Windows Terminal
Powershell

### Repro Steps

I open a windows termianl and input command 'wsl', then wsl start correctly. Meanwhile, all the windows starting blink as 'selected->unselected->loop'. 
after that I input command 'wsl --shutdown', all the problems disappeared.
this problem happened many times on Windows10/Windows11.

### Expected Behavior

it shouldn't interrupt my option by blink i think

### Actual Behavior

it always interrupt all my option

**Comment by craigloewen-msft** [comment]
Are you using Windows Terminal or Windows console? Also could you please give us your Windows version?

It is likely that you will need to file an issue on the Terminal repo for this as they own that code.
http://github.com/microsoft/terminal

**Comment by wangjunbo4** [comment]
Thank you for your relpy. My Windows 11 version is 10.0.22000, and Windows Terminal 1.12.10983.0. But this problem occured when I use Windows 10 and powershell core without windows terminal. Meanwhile, if i don't shutdown WSL, it will blink even if i close all the powershell and Windows terminal windows.
