### ISSUE TITLE
SMART Status of Host with smartctl?

### ISSUE THREAD

**Issue by erythana** [microsoft/WSL#8445]
### Version

Version 10.0.19042.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

latest Fedora Remix

### Other Software

smartmontools --> smartctl

### Repro Steps

Hello,

i want to achieve the following: Query the SMART-Status via SNMP from Windows. Ultimately, this doesn't seem to work without a extended agent on windows - and therefor needs unmanaged code to do so. 

Anyway, i try to hack my way around that a bit and have set up a WSL2 with snmpd and extended it with a script. With that script i can query via "smartctl -H /dev/sda".
This setup seems to work, but i am not sure if the returned Health-Status is plausible and display the REAL health status.

smartctl --all crashes due to 
">> Terminate command early due to bad response to IEC mode page
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options."

Does someone have any insights on this and how i could test the SMART output?

### Expected Behavior

Displaying actual information about SMART Status

### Actual Behavior

Probably not showing actual SMART Status

**Comment by elsaco** [comment]
The `/dev/sda` in WSL doesn't represent a real device, it is a virtual device.

**Comment by erythana** [comment]
Sad to hear, thanks though.
That calls for even more hackery!
