### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070424

### ISSUE THREAD

**Issue by PMPP** [microsoft/WSL#8446]
### Version

Microsoft Windows [Version 10.0.22621.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

The specified service does not exist as an installed service.

### Distro Version

WslRegisterDistribution failed with error: 0x80070424

### Repro Steps

Opening a cmd prompt and running `wsl` results in:
`The specified service does not exist as an installed service.`

Opening `Windows Terminal` results in:
```
The specified service does not exist as an installed service.


[process exited with code 4294967295 (0xffffffff)]
```

Opening Ubuntu from the Microsoft Store results in:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070424
Error: 0x80070424 The specified service does not exist as an installed service.

Press any key to continue...
```

Running `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` in a PowerShell with Admin Rights results in:
```
Path          :
Online        : True
RestartNeeded : False
```

More Windows Features has the checkbox CHECKED for:
```
Hyper-V (and its descendants)
Virtual Machine Platform
Windows Subsystem for Linux
```

I've tried to UNCHECK them, restart the computer, CHECK them again, restart. The problem continues.

Since I saw on other tickets requests to do share logs by performing 
```
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
Set-ExecutionPolicy Bypass -Scope Process -Force
.\collect-wsl-logs.ps1
```

I've done it, what I attempted to do while collecting logs:
- executing `wsl` from a cmd prompt
- Opening Windows Terminal (linked to my Ubuntu)
- Opening Ubuntu as the app

### Expected Behavior

I would expect WSL to run, but I would also expect a clearer message on what service is exactly expected to be running.

I would also expect any service linked to WSL to be registered once I try to install WSL, and if there is any failure in the installation of WSL to be notified of such.

### Actual Behavior

I am instead presented with error messages like this one when trying to open the Ubuntu APP:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070424
Error: 0x80070424 The specified service does not exist as an installed service.

Press any key to continue...
```

### Diagnostic Logs

[WslLogs-2022-05-26_02-07-51.zip](https://github.com/microsoft/WSL/files/8773574/WslLogs-2022-05-26_02-07-51.zip)

**Comment by PMPP** [comment]
As I continued to try to resolve this problem, and I was going through my Apps on my Microsoft Store, I saw I add the app "Windows Subsytem for Linux Preview" installed. Trying to "open" it, would show the same error.

I went to Settings > Installed Apps > Windows Subsytem for Linux Preview
here, under "Reset" I clicked "Repair" which, well, seems to have repaired the issue, and now I am able to get into my Ubuntu Distro.

It would seem that if WSL is installed via the Store, then any interaction from the optional features does little to nothing in terms of reinstating the necessary configurations/services.

**Comment by OneBlue** [comment]
Thanks for reporting this @PMPP. It looks like something is weird with the way the WSL service is registered.

Can you share the output of `Start-Service WslService` in an elevated powershell ?

**Comment by PMPP** [comment]
Hi @OneBlue , executing `Start-Service WslService` in an elevated powershell didn't produce any results:
```
PS C:\WINDOWS\system32> Start-Service WslService
PS C:\WINDOWS\system32>
```

But as a reminder, I was already able to solve the situation, so I wasn't able to run this command while I was having the problem.

**Comment by OneBlue** [comment]
Thanks @PMPP. It's interesting that you're getting this error given that it looks like the service is correctly installed.

Immediately after you start the service, what's the output of `get-service wslservice` ?

**Comment by Man-On-Earth** [comment]
> As I continued to try to resolve this problem, and I was going through my Apps on my Microsoft Store, I saw I add the app "Windows Subsytem for Linux Preview" installed. Trying to "open" it, would show the same error.
> 
> I went to Settings > Installed Apps > Windows Subsytem for Linux Preview here, under "Reset" I clicked "Repair" which, well, seems to have repaired the issue, and now I am able to get into my Ubuntu Distro.
> 
> It would seem that if WSL is installed via the Store, then any interaction from the optional features does little to nothing in terms of reinstating the necessary configurations/services.

I also encountered the same problem. This is the only one in a large number of search results that solved my problem, thanks a lot!

**Comment by zyazhb** [comment]
> As I continued to try to resolve this problem, and I was going through my Apps on my Microsoft Store, I saw I add the app "Windows Subsytem for Linux Preview" installed. Trying to "open" it, would show the same error.
> 
> I went to Settings > Installed Apps > Windows Subsytem for Linux Preview here, under "Reset" I clicked "Repair" which, well, seems to have repaired the issue, and now I am able to get into my Ubuntu Distro.
> 
> It would seem that if WSL is installed via the Store, then any interaction from the optional features does little to nothing in terms of reinstating the necessary configurations/services.

Meet this problem and fixed it by pressed Repir button, tnx.

**Comment by rohiitgit** [comment]
i tried every possible method i found on internet including the ones mentioned here, nothing seems to work for me.

**Comment by ermax775** [comment]
That is probably because though wsl is updated, specific services hasn't been started and initialized. So, just start all the wsl services using this command: 
Start-Service WslService  
 ... on the PowerShell terminal and reopen Kali from the Store. It will start installing Kali shortly after that.

**Comment by rohiitgit** [comment]
actually i solved it, it started working properly as soon as I uninstalled WSL from windows settings. It had two WSL installations, one named WSL and other as Updates for WSL

**Comment by valeraparafin** [comment]
same for me. Resolved by uninstall WSL from win settings.
got this error while upd docker 4.26.1 (wsl 2 was installed before)

**Comment by caminashell** [comment]
For me, the cause was Comodo Auto-Containment.

To explain . . .

I went through a process of deduction to find out what the cause was for my terminal not running as expected. I tried to stop/start the `virtualization platform` - negative. Tried `netsh winsock reset` - negative. I even went as far as checking my UEFI SVM setting, which was fine.

Then I thought back to what I had changed since I last ran the container. The only things I could think of were Malwarebytes, and Comodo Firewall (which comes with some fancy features).

I quit Malwarebytes - negative. I turned off all Comodo features - **SUCCESS!** Then narrowed it down to `Auto-containment`, so whilst it was off, I added the terminal process to an ignore rule, and now all is fine.

**Comment by nilpat** [comment]
> As I continued to try to resolve this problem, and I was going through my Apps on my Microsoft Store, I saw I add the app "Windows Subsytem for Linux Preview" installed. Trying to "open" it, would show the same error.
> 
> I went to Settings > Installed Apps > Windows Subsytem for Linux Preview here, under "Reset" I clicked "Repair" which, well, seems to have repaired the issue, and now I am able to get into my Ubuntu Distro.
> 
> It would seem that if WSL is installed via the Store, then any interaction from the optional features does little to nothing in terms of reinstating the necessary configurations/services.

So simple fix , it worked for me :)

**Comment by JamesTheZ** [comment]
`wsl --update` works for me.
