### ISSUE TITLE
modprobe fails

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/WSL#845]
Hi,
I'm testing hubicfuse (https://github.com/TurboGit/hubicfuse) and all works fine, but I cannot use it because:

```
root@BESTIA:~# mkdir /mnt/hubic
root@BESTIA:~# hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
fuse: device not found, try 'modprobe fuse' first
root@BESTIA:~# modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin'
```

Any idea/workaround?

**Comment by russalex** [comment]
Thanks for the interest in WSL.

Fuse is not currently supported.  We have a User Voice page on Fuse [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl).  I would recommend heading over and voting there (already one comment about hubiC).

Knowing WSL was shipping as a beta, we created a list of the high priority features on our [FAQ](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-your-high-priority-feature-set-for-the-windows-10-anniversary-edition) page.  We will be updating this with new features as we get into the next release.

**Comment by fpqc** [comment]
@russalex Pretty impressive to see how far the project has come from those goals only a few months ago (although all of those things don't work absolutely perfectly yet, they are all more or less functional for many use cases)

**Comment by iz0eyj** [comment]
@russalex Yes Alex, I know, I don't know why but I have two accounts here... the comment was mine.
I reported here because I don't find any bug report on Fuse.

**Comment by iz0eyj** [comment]
```
Federico@BESTIA ~ % lsmod
libkmod: ERROR ../libkmod/libkmod-module.c:1619 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory

```

**Comment by aseering** [comment]
For what it's worth, #412 is relevant to FUSE

**Comment by therealkenc** [comment]
#17 looks to be the github landing zone for FUSE and the [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) was already cited. #412 is (of late and for better or worse) acting as a LZ for outstanding USB devicey stuff.
