### ISSUE TITLE
Does WSL really require Hyper-V?

### ISSUE THREAD

**Issue by RealFX-Code** [microsoft/WSL#8451]
**Is your feature request related to a problem? Please describe.**
So yea, I want to use virtual machines through Virtualbox or Bluestacks and Can't becuse WSL is enabled in the "optional features"

**Describe the solution you'd like**
Well, I don't know really. I'd just like a way to temporarily disable Hyper-v so I can keep WSL while also having Virtual Machine support.

**Describe alternatives you've considered**
Well, I've considered ditching WSL entirely and going for something like cygwin instead.

**Additional context**
Well, Virtualbox just hangs and VMware just errors out. And bluestacks just tells me I have to disable WSL to open it.

**Comment by OneBlue** [comment]
Thanks for reporting this @RealFX-Code. Which Windows build are you using ?

**Comment by benhillis** [comment]
WSL requires the hyper-v hypervisor which is incompatible with other hypervisor offerings. There is a vmware backend that uses hyper-v mode: https://blogs.vmware.com/workstation/2020/05/vmware-workstation-now-supports-hyper-v-mode.html
