### ISSUE TITLE
wsl2 ubuntu，shift+arrows output ABCD

### ISSUE THREAD

**Issue by shuohao** [microsoft/WSL#8452]
### Version

Microsoft Windows [版本 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

![image](https://user-images.githubusercontent.com/4637107/170661042-e50d7a0c-cab3-4d34-9172-e6ed579ef34b.png)

shit+left output D
shift+up output A

### Expected Behavior

Shift + left and right   select text

### Actual Behavior

output ABCD

**Comment by elsaco** [comment]
@shuohao PowerShell is using `PSReadLine` to process text, and that module offers options like `Shift+LeftArrow` to select text. In Linux the shell is using `ReadLine` which doesn't have this option. That's expected behavior when pressing `Shift+LeftArrow` in a Linux shell session.
