### ISSUE TITLE
Ubuntu installation stuck on WSL (Windows 11 Home -21H2) 

### ISSUE THREAD

**Issue by AhmedKamelAli** [microsoft/WSL#8456]
### Version

 10.0.22000.613

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Other Software

Docker Desktop windows Version (4.8.2)

### Repro Steps

1)step 1: turn on Microsoft-Windows-Subsystem-Linux  in widows features
.\Dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

2)step 2: turn on VirtualMachinePlatform  in widows features
.\Dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

3)step 3:
package download:
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

4)step 4: install wsl_update_x64.msi

5) step 5: Restart windows

6) step 6: download & install Ubuntu-20.04
In powerShell (Admin):  wsl.exe --install -d Ubuntu-20.04

Ubuntu window opens, says "Installing, this may take a few minutes" for several hours.

WSL logs:

### Expected Behavior

Ubuntu should install and ask me to configure my user account.

### Actual Behavior

Hangs on "Installing, this may take a few minutes..." 

### Diagnostic Logs

[WslLogs-2022-05-28_21-44-17.zip](https://github.com/microsoft/WSL/files/8791660/WslLogs-2022-05-28_21-44-17.zip)

**Comment by pmartincic** [comment]
Do you have any interest in trying more recent builds of WSL preview https://www.microsoft.com/store/productId/9P9TQF7MRM4R ?

I didn't see anything in the logs. Did you let the trace program record while performing step 6?

**Comment by chrascher** [comment]
sounds like
https://github.com/microsoft/WSL/issues/7505
