### ISSUE TITLE
WSL2 not using all the cpu available.

### ISSUE THREAD

**Issue by VinceGHER** [microsoft/WSL#8463]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.472

### Distro Version

Ubuntu 22

### Other Software

Windows 11 

### Repro Steps

load your cpu on a WSL2 Ubuntu 22 distro

### Expected Behavior

CPU on the task manager at 100%

### Actual Behavior

Only using 50% of my cpu

### Diagnostic Logs

<img width="958" alt="image" src="https://user-images.githubusercontent.com/29159082/171129184-79defc03-4c68-4a28-a706-f9a409533d18.png">

**Comment by firewave** [comment]
Could you check the `Details` tab or use `Process Explorer` (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) instead?

It appears some parts of `Task Manager` will not show the actual CPU usage for WSL processes. It is at least that is true for WSL1.
