### ISSUE TITLE
WSL2 does not support mounting F2FS partition

### ISSUE THREAD

**Issue by yetdragon** [microsoft/WSL#8467]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian 11

### Repro Steps

```console
sudo mount some_f2fs_partition /mnt/root
```

### Expected Behavior

Linux kernel newer than 3.8 should support mounting F2FS partition.

### Actual Behavior

```console
mount: /mnt/root: unknown filesystem type 'f2fs'.
```

**Comment by elsaco** [comment]
@yetdragon you need to rebuild the WSL kernel with flash-friendly file system support enabled. The current WSL kernel (5.10.102.1-microsoft-standard-WSL2) has `# CONFIG_F2FS_FS is not set`

**Comment by okineadev** [comment]
I have my own fork with `f2fs` support, you can compile it yourself and use it - https://github.com/okineadev/WSL2-Linux-Kernel/tree/f2fs-support

**Comment by mshcherbyna99** [comment]
Hello, @elsaco and @yetdragon.

I visit you to a [first GitHub Issue](https://github.com/microsoft/WSL/issues/7973#issuecomment-2783268143), created about proposal for implementation of F2FS file system.

Thank you and have a nice day.
