### ISSUE TITLE
WSL freezes if it has to download something

### ISSUE THREAD

**Issue by davdfr** [microsoft/WSL#8471]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

sudo apt update && sudo apt upgrade
nvm install --lts

### Expected Behavior

The download should simply start
Sometimes it works, sometimes it doesn't

### Actual Behavior

It stands still, the downloads do not go on
Sometimes ctrl + C and redoing works

**Comment by owenschupp** [comment]
Hello, thanks for reaching out! Unfortunately, this isn't actionable- this could be the result of a network connection or various other parameters. Closing as due the that.
