### ISSUE TITLE
Prohibitively slow interop after upgrade to Windows 11

### ISSUE THREAD

**Issue by bowmanjd** [microsoft/WSL#8472]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04.4 LTS

### Other Software

clip.exe
win32yank.exe 0.0.4
wsl.exe
any other executable I have tried

❯ wsl --version
WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.708

### Repro Steps

`cd $HOME`
Pipe some text to the clipboard using clip.exe
`printf "Hello, World!" | /mnt/c/Windows/System32/clip.exe`
It takes about 10 seconds to complete successfully. This happens with any executable I have tried.
`cd /mnt/c`
Try it again, but this time from the Windows filesystem.
`printf "Hello, World!" | /mnt/c/Windows/System32/clip.exe`
Successfully completed immediately.

### Expected Behavior

While still on Windows 10, before I upgraded to Windows 11 two days ago, these commands completed immediately whether or not I was in a Windows directory or WSL directory.

### Actual Behavior

Very slow completion when in WSL filesystem, even though the executable is on the Windows side and does not reside in any WSL directory.

### Diagnostic Logs

```
C:\WINDOWS\system32>wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                 DeviceID            InterfaceType  MediaLoaded  MediaType              Model                       Name                Partitions
              {3, 4}        {"Random Access", "Supports Writing"}  \\.\PHYSICALDRIVE0  SCSI           TRUE         Fixed hard disk media  SAMSUNG MZVL2512HCJQ-00BL7  \\.\PHYSICALDRIVE0  3
```
[WslLogs-2022-06-05_06-33-44.zip](https://github.com/microsoft/WSL/files/8839790/WslLogs-2022-06-05_06-33-44.zip)

**Comment by bowmanjd** [comment]
For now, anytime I need to execute a Windows script or executable from within WSL, I will `cd /mnt/c` or similar first. Or, if I want the executable more easily accessible, I might wrap the executable in a shell script like this, placed somewhere in my PATH, such as `~/.local/bin/clip.exe`:

```sh
#!/bin/sh

cd /mnt/c
/mnt/c/Windows/System32/clip.exe "$@"
cd $OLDPWD
```

**Comment by benhillis** [comment]
This must be something strange, because I'm not able to reproduce.

```
ben@BENHILL-DEV:~$ time bash -c " printf Hello,World! | /mnt/c/Windows/System32/clip.exe"

real    0m0.109s
user    0m0.004s
sys     0m0.006s
ben@BENHILL-DEV:~$ cd /mnt/c
ben@BENHILL-DEV:/mnt/c$ time bash -c " printf Hello,World! | /mnt/c/Windows/System32/clip.exe"

real    0m0.077s
user    0m0.004s
sys     0m0.005s
```

**Comment by bowmanjd** [comment]
Hmmm... Wonder why I am only experiencing it after a move to Windows 11. Maybe antivirus? Seems odd.

**Comment by benhillis** [comment]
Yes something strange is happening. I suspect it has to do with running a Windows executable with a `\\wsl.localhost\<distro>` path as the current working directory.

**Comment by bowmanjd** [comment]
Curious. Is there another way to specify the directory, other than \\wsl.localhost or \\$wsl?
