### ISSUE TITLE
WSL cannot read cmd arguments on Windows 11

### ISSUE THREAD

**Issue by keklick1337** [microsoft/WSL#8488]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 1

### Kernel Version

Linux version 4.4.0-22000-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #653-Microsoft Wed Apr 27 16:06:00 PST 2022

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Update Windows 11 to version 22000.708
2. Try to upgrade WSL1 to WSL2
3. You will get a failure

https://user-images.githubusercontent.com/86933883/172475331-51ce7710-547b-4959-99c2-f22268222ff6.mp4

### Expected Behavior

I expected to see wsl1 upgrade to wsl2

### Actual Behavior

wsl does not accept command line arguments for updating.

### Diagnostic Logs

Before i try re-enable VirtualMachinePlatform via dism

```
PS C:\Users\x>  dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.22000.653

Image Version: 10.0.22000.708

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
PS C:\Users\x> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.22000.653

Image Version: 10.0.22000.708

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
```

**Comment by benhillis** [comment]
What SKU are you running?

**Comment by benhillis** [comment]
Can you make sure you have this patch installed?

https://support.microsoft.com/en-us/topic/may-24-2022-kb5014021-os-build-20348-740-preview-2b180bd4-dceb-4c49-b8cf-402b342ebc84

**Comment by elsaco** [comment]
@keklick1337 based on your video clip, you're trying to convert Ubuntu-20.04 from WSL1 to WSL2 while being in use. You need to shutdown WSL first, just use `wsl --shutdown`, then convert it to WSL2.

**Comment by benhillis** [comment]
For WSL2 you need to enable the virtual machine platform optional component, and ensure that your machine has virtualization configured in the bios.

**Comment by mikebeaton** [comment]
Make sure you have added the `Windows Subsystem for Linux` Windows component, using old skool `Control Panel/Programs and Features/Turn Windows features on or off`. Not sure if this applies even on the most current versions of Windows, but I just factory reset a machine, and the behaviour of the `wsl` command out of the box, before installing that component, was to act as if it could not see any command line parameters I was giving it.
