### ISSUE TITLE
Git Credential Manager Not Working

### ISSUE THREAD

**Issue by sys13** [microsoft/WSL#8491]
### Version

Windows version: 10.0.22621.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

Git for Windows 2.36.1.windows.1

### Repro Steps

`git clone https://github.com/sys13/gtm.git`

### Expected Behavior

Expected it to pull the repo using the windows credential manager

### Actual Behavior

```
Cloning into 'gtm'...
/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe get: 1: /mnt/c/Program Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe: not found
```

### Diagnostic Logs

In my ~/.gitconfig I have:

```
[credential]
        helper = /mnt/c/Program\\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe
```

**Comment by benhillis** [comment]
https://github.com/MicrosoftDocs/WSL/pull/1556/files
