### ISSUE TITLE
Spaces put in PATH

### ISSUE THREAD

**Issue by andyj513** [microsoft/WSL#8496]
### Version

Microsoft Windows [Version 10.0.22000.652]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Distro Version

Ubuntu 20.04

### Repro Steps

Run:
    env | grep ^PATH

Note that the path contains some directories from Windows that contain spaces.  For example, mine (edited) is:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/andyj/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/andyj/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin

Note that some of the directories (from Windows) have spaces, such as: "/mnt/c/Program Files/dotnet/"

This causes problems in some cases, when using some Bash scripts written by others.  They may do things like:
    PATH=$PATH:/new-stuff command
to temporarily change the path and then run the command.  But having the spaces in the path breaks this.

One solution is to add a backslash before each space.  I am able to do this myself by running:
    export PATH=${PATH// /\\ }

However, I consider it a bug that whatever component is adding the directories with spaces to the path is not doing this itself.  It would save others from having to figure this out, etc.

### Expected Behavior

PATH variable should have backslashes before all spaces.

### Actual Behavior

PATH variable includes Windows directories with spaces, and no leading backslashes.  E.g., "/mnt/c/Program Files/dotnet/"

**Comment by benhillis** [comment]
@andyj513 - from my experimentation, escaping spaces in the $PATH variable does not seem to work. The issue is that bash scripts should be wrapping the $PATH variable in quotes.
