### ISSUE TITLE
Explorer unable to access SSHFS mounted directory

### ISSUE THREAD

**Issue by paulmenzel** [microsoft/WSL#8498]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

(default)

### Distro Version

(default)

### Repro Steps

Follow [*Access Linux filesystems in Windows and WSL 2*](https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/) and mount remote directory over SSHFS:

    $ id -u
    1000
    $ sshfs -⁠o idmap=user example.net:/⁠project/X ~/mnt -o uid=1000

`ls -l` shows the users to be mapped to the user with id 1000. Reading files inside the mount directory works.

### Expected Behavior

The Microsoft Windows Explorer should be able to access the mounted directory.

### Actual Behavior

The Microsoft Windows Explorer is unable to access the mounted directory.

**Comment by elsaco** [comment]
@paulmenzel edit `/etc/fuse.conf` and add `user_allow_other`. Most likely the setting is there already, just  uncomment it. This will allow the remote file system to show inside Windows file explorer.

This is the command I use to mount remotes from DO droplets:

`sshfs -o allow_other,default_permissions elsaco@x.x.x.x:/home/elsaco/droplet ~/droplet`

I'm using Windows 10, but it should work on Windows 11 also.
