### ISSUE TITLE
wsl2 loses file changes and reverts to older state of files

### ISSUE THREAD

**Issue by jaydonnell** [microsoft/WSL#8499]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

 Ubuntu-20.04

### Repro Steps

I don't know a reliable way to reproduce this. It's very intermittent. I edited several text files through vscode, saved them, and left the computer sleeping. When I opened again after a couple weeks, the files reverted to an older state and I lost all of the work I had done. This is the second or third time this has happened. This last time the battery died while it was sleeping, maybe it's related to that.  

### Expected Behavior

The contents of my files should NOT be reverted after I save them. 

### Actual Behavior

My file edits were lost after saving them. 

### Diagnostic Logs

My computer is an HP Spectre x360 if that matters

**Comment by jaydonnell** [comment]
One additional detail, it did not revert back to the previous save. I had saved some of the files many times over a few days, and all of that was lost.

**Comment by jaydonnell** [comment]
My apologies, this was user error on my part.

**Comment by muhammedMoussa** [comment]
> My apologies, this was user error on my part.

what was the error and how you resolved it? i have the same issue
