### ISSUE TITLE
I cannot install WSL to my Laptop.

### ISSUE THREAD

**Issue by hothotsyu** [microsoft/WSL#8501]
Would you like to help me install WSL correctly?
I installed it, but failed as bellow.
1. open a Powershell command prompt by "Run as Administrator".
=================================================
PowerShell 7.2.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.2.4
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.2.4
=================================================
2. check WSL has not been installed.
=================================================
PS C:\Program Files\PowerShell\7> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\Program Files\PowerShell\7>
=================================================
3. install it
=================================================
PS C:\Program Files\PowerShell\7> wsl --install --distribution Ubuntu
Downloading: Ubuntu
Installing: Ubuntu
Ubuntu has been installed.
Launching Ubuntu...
PS C:\Program Files\PowerShell\7>
=================================================
4. check whether it has been installed or not.
=================================================
PS C:\Program Files\PowerShell\7> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\Program Files\PowerShell\7>
PS C:\Program Files\PowerShell\7> date

2022年6月12日 17:03:08

PS C:\Program Files\PowerShell\7>
PS C:\Program Files\PowerShell\7>
=================================================
5. reboot my Laptop
* After rebooted my laptop. 
=================================================
PowerShell 7.2.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.2.4
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.2.4

PS C:\Program Files\PowerShell\7> date

2022年6月12日 17:10:57

=================================================
6. check whether it has been installed or not.
=================================================
PS C:\Program Files\PowerShell\7> wsl --list --verbose
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\Program Files\PowerShell\7>
=================================================
7. at last, I cannot run WSL.exe.
=================================================
PS C:\Program Files\PowerShell\7> WSL.exe
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
PS C:\Program Files\PowerShell\7>
=================================================

Best regards,
Peter.Woodland

**Comment by benhillis** [comment]
Thanks Peter, you have to launch ubuntu.exe after installing it.
