### ISSUE TITLE
wsl2 import error after update to windows 11

### ISSUE THREAD

**Issue by equation-group** [microsoft/WSL#8503]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Repro Steps

file location:  %appdata%/local/packages/mylinux

wsl --import mydistro . ./alpine_rootfs_distro.tar.xz   gives unspecified error. 
[WslLogs-2022-06-13_02-16-08.zip](https://github.com/microsoft/WSL/files/8886810/WslLogs-2022-06-13_02-16-08.zip)

### Expected Behavior

unable to import, gives unspecified error

### Actual Behavior

should be able to import and register

### Diagnostic Logs

attached logs in zip

**Comment by benhillis** [comment]
Looks like you're using xz compression? Unfortunately we only support gzip.
```
bsdtar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"
```

**Comment by Biswa96** [comment]
As a workaround, the .tar file can be extracted from the .tar.xz file using tools like 7zip and others. Then .tar file can be imported as usual.

**Comment by equation-group** [comment]
i dont want a workaround, i want a proper solution, give it to me...
where are the microsoft employees ?

I especially bought microsoft windows 11 license to use WSL2,

------ Original Message ------
From "Biswapriyo Nath" ***@***.***>
To "microsoft/WSL" ***@***.***>
Cc "EQN-GROUP" ***@***.***>; "Author" 
***@***.***>
Date 14/06/2022 09:47:31
Subject Re: [microsoft/WSL] wsl2 import error after update to windows 11 
(Issue #8503)

**Comment by benhillis** [comment]
Taking a look at this, might have some options for WSL2.
