### ISSUE TITLE
Updated WSL Kernel Offline Update

### ISSUE THREAD

**Issue by dmlb2000** [microsoft/WSL#8506]
### Version

Microsoft Windows [Version 10.0.19042.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Fedora 36

### Repro Steps

I have an off-line installation of Windows 10 I run at work. It can't have access to standard update mechanisms. Is there a way to get the updated 5.10.102.1 WSL Linux Kernel without going through windows update? 

The https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi link seems to have the 5.10.16.3 kernel.

### Expected Behavior

Getting the generic wsl_update_x64.msi should give me the latest kernel version.

### Actual Behavior

Online system at home running Windows 10 can get updated kernel via selecting the "Receive updates for other Microsoft products when you update Windows" advanced Windows Update option. But I can't seem to find an MSI to download to get the latest for my off-line system at work.

**Comment by elsaco** [comment]
Download the package, extract contents and move kernel to your `c:\windows\system32\lxss\tools` directory.

Sample run with `c:\foo\wsl_update_x64.msi` package:

`msiexec /a C:\foo\wsl_update_x64.msi /qb targetdir=c:\bar
`

and the new kernel:

```
PS C:\bar\System32\lxss\tools> ls


    Directory: C:\bar\System32\lxss\tools


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         4/13/2021  12:06 PM       70722784 kernel
-a----         4/13/2021  11:22 AM          19292 license
```

**Comment by elsaco** [comment]
That was just an example how to grab a new kernel from the package. Here's what's available at `Microsoft Update Catalog`:

![wsl_updates](https://user-images.githubusercontent.com/3933920/173435020-28a50629-1042-4d86-9090-d2cfca551e3d.png)

Also, `wsl --shutdown` is required to load a new kernel.

**Comment by dmlb2000** [comment]
Ah, this works. Thank you!

**Comment by dmlb2000** [comment]
https://www.catalog.update.microsoft.com/Search.aspx?q=wsl direct link for those that find this later.
