### ISSUE TITLE
Updating the Linux Kernel branches for WSL2

### ISSUE THREAD

**Issue by ohault** [microsoft/WSL#8507]
The next Linux longterm release kernel is already approaching.

With the upcoming default support of the latest Linux longterm release (currently version 5.15) in WSL2, can you please also update it on https://github.com/microsoft/WSL2-Linux-Kernel/branches ?

**Comment by benhillis** [comment]
Yes, we will be updating to 5.15 (hopefully) soon.

**Comment by ohault** [comment]
Great, but why are you closing this ticket meanwhile updating to 5.15 is not yet done?

**Comment by ohault** [comment]
Congratulation to have solved the blocking 9p issue and published a [first version](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.57.1) of the Kernel 5.15 source code.
