### ISSUE TITLE
WSL file system not available to any windows applications until after I start WSL Terminal

### ISSUE THREAD

**Issue by kyle-mcknight** [microsoft/WSL#8508]
### Version

10.0.22000.675

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Any time I restart windows and attempt to access anything located within a linux distro in WSL, no application is able to access it until after I start WSL manually.

1. Restart you machine
2. Attempt to access the linux file system via \\wsl$\<distro>\ in any application

The file system is unavailable.

3. Start a WSL terminal with your linux distro you wanted to access
4. Retry accessing the filesystem through the application

Note that you can now access the filesystem with any application

### Expected Behavior

The application is able to access the linux distro filesystem

### Actual Behavior

The application fails to access the location say it isn't available (or whatever error they happen to show when that happens)

**Comment by pmartincic** [comment]
If you could call `wsl --shutdown`, then start logging, and then attempt access it would be helpful.
