### ISSUE TITLE
localhost:3000 / 127.0.0.1:3000 nodejs server unable to connect via windows browsers

### ISSUE THREAD

**Issue by Sandy-Garrido** [microsoft/WSL#8509]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubunutu 20.04.4 LTS

### Repro Steps

- Start a nodejs server with port 3000 via WLS
- Try to access via windows browser localhost:3000 or 127.0.0.1:300
- Unable to access it.

### Expected Behavior

- be able to connect via localhost:3000 or 127.0.0.1:3000

### Actual Behavior

Unable to connect to localhost wsl nodejs server

I am however able to access it via the wsl ip 172.29.229.115:3000 but this IP changes every time I restart or restart WSL which isn't useful for me every time as the project I'm working on requires the host to be a particular domain which I set via HOSTS.

I don't recall this working in the past as it's the first time I've needed to have a specific domain set in my host file

**Comment by elsaco** [comment]
@Sandy-Garrido the `loopback` interface in Windows is separate from the `loopback` interface in a WSL instance. However, you can use `portproxy` to make the connection. A similar issue was discussed here not too long ago. Please check https://github.com/microsoft/WSL/issues/8431

**Comment by Sandy-Garrido** [comment]
> @Sandy-Garrido the `loopback` interface in Windows is separate from the `loopback` interface in a WSL instance. However, you can use `portproxy` to make the connection. A similar issue was discussed here not too long ago. Please check #8431

Hmm, thanks, though That answer suggests to enter the wsl ip all the time, this changes, so does that mean I will have to change this every time ?
Did I mention already that I can already connect if I just wsl.ip.x.x:3000 but I need a solution that doesn't require me to edit something every time I log into my pc

**Comment by elsaco** [comment]
@Sandy-Garrido is this what you're trying to connect?

```
   Window               WSL/node
127.0.0.1:3000 <---> 127.0.0.1:3000
```

**Comment by Sandy-Garrido** [comment]
> @Sandy-Garrido is this what you're trying to connect?
> 
> ```
>    Window               WSL/node
> 127.0.0.1:3000 <---> 127.0.0.1:3000
> ```

Doh 🤦‍♂️ I see where you're going with that I think. I'll give that solution a try haha

**Comment by Sandy-Garrido** [comment]
Okay, whilst yes, what I wanted didn't work. With your comments etc, I've managed to at least create a logon script that will get the WSL IP and run the netsh command so that I don't need to keep changing it! thanks for you're help!

**Comment by Majikmikewrightedu** [comment]
Calc84

**Comment by RaizoRanz** [comment]
http://<your-server-ip>:3000/phantom-

**Comment by rangsano** [comment]
[](url)
