### ISSUE TITLE
Can't create a username just after installing Ubuntu and can't switch to WSL 2

### ISSUE THREAD

**Issue by Sandman192** [microsoft/WSL#8510]
### Version

Edition	Windows 10 Pro Version	21H2 Installed on	‎7/‎6/‎2021 OS build	19044.1706 Experience	Windows Feature Experience Pack 120.2212.4170.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

wsl --install -d ubuntu

### Expected Behavior

Ubuntu asks me to create a Username but give me this instead.
> adduser: Please enter a username matching the regular expression configured
> via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
> option to relax this check or reconfigure NAME_REGEX.

### Actual Behavior

wsl --install -d ubuntu

**Comment by Sandman192** [comment]
I found out you can't use capital letters in username.
Windows WSL site doesn't mention that.

**Comment by laurafstrube** [comment]
If anyone is still following this thread, is there a way to return to the automated "enter username" prompt? 

I received this error and "CTRL-C'd" out of the prompt thinking I could come back and start over once I'd figured out what was going on.

**Comment by Gunhedo** [comment]
> I found out you can't use capital letters in username. Windows WSL site doesn't mention that.

Thank you random user for solved the problem with your statement! :)

**Comment by RFBomb** [comment]
This problem plagued me today. 

Now my username is "exit"

Fucking ridiculous. Atleast tell us what the regex is in the error, or give us a better way to diagnose it.
