### ISSUE TITLE
Can't read mounted NTFS folder

### ISSUE THREAD

**Issue by CarlGao4** [microsoft/WSL#8511]
### Version

10.0.22000.708

### WSL Version

WSL 2

### Kernel Version

5.10.102.1

### Distro Version

imported Arch Linux

### Repro Steps

I mounted another NTFS volume into a NTFS folder with diskpart:
![image](https://user-images.githubusercontent.com/57826826/173482582-6cb5f182-6fc4-45a1-83f1-4390ac528430.png)
Sorry I'm using Chinese but I think it is not difficult to understand what I'm doing from the commands I used. 
Then it is impossible to read inside WSL. 

### Expected Behavior

This is what inside the volume:
![image](https://user-images.githubusercontent.com/57826826/173483151-acf01075-a648-4a38-a80d-efa8f5aa4739.png)

### Actual Behavior

I tried to read it in WSL, in fact it is impossible:
![image](https://user-images.githubusercontent.com/57826826/173482910-c8169245-e857-44c8-9e6b-ccf4e03520cc.png)

**Comment by owenschupp** [comment]
Hello! For this usage, I would either look at using `wsl --mount` (https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) with the block device or mount it with drvfs if you assign it a drive letter instead of a share. For example, `mount -t drvfs G: /mnt/g`

**Comment by CarlGao4** [comment]
I know it can be mounted using `mount`. But I think it would be better if WSL can directly use mounted directory.
