### ISSUE TITLE
wsl --cd command line option doesn't accept tilde path prefix

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/WSL#8515]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

 4.4.0-22000-Microsoft 

### Distro Version

Ubuntu 22.04

### Repro Steps

Start wsl
create folder in home directory (mkdir ~/folder)
Exit wsl
Try to start wsl in ~/folder ( wsl --cd ~/folder)
get incorrect parameter error.
"wsl --cd ~" works, "wsl --cd /home/user/folder" also works

### Expected Behavior

wsl --cd ~/folder works

### Actual Behavior

C:\Users\frolo>wsl --cd ~/folder
Параметр задан неверно.

**Comment by benhillis** [comment]
Support for that was added in the store version of WSL. Looks like you're running inbox?

**Comment by kotenok2000** [comment]
I have downloaded ubuntu 22.04 appxbundle CanonicalGroupLimited.Ubuntu22.04LTS_2204.0.9.0_neutral___79rhkp1fndgsc.AppxBundle and then extracted it to E:\wsl\ubuntu
What is inbox?

**Comment by benhillis** [comment]
You need to download the Windows Subsystem for Linux app from the Microsoft Store.

**Comment by kotenok2000** [comment]
You mean this one? 
https://apps.microsoft.com/store/detail/9P9TQF7MRM4R?hl=en-us&gl=US

24.06.2022 21:17:40, Ben Hillis пишет:
