### ISSUE TITLE
UtilCreateProcessAndWait:501: in startup 

### ISSUE THREAD

**Issue by Jessen-Li** [microsoft/WSL#8517]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.18.3linux-5.18.ylinux-5.9.18.y+

### Distro Version

20.04

### Repro Steps

I install git, and git clone the linux kernel. I checkout linux-5.18.y, copy the configuration from wsl github, and run $make menuconfig to apply some changes. 
Then $make; $make modules; $make modules_install; $make install. 
Then copy the bzImage to C:\Windows\System32\lxss\tools to replace the old kernel file.
And then I reboot the wsl.  I run dmesg, it shows:
```
[    5.575693] init: (1) ERROR: UtilCreateProcessAndWait:501: /bin/mount failed with status 0x
[    5.575700] 2000
[    5.575714] init: (1) ERROR: MountPlan9:493: mount cache=mmap,noatime,trans=fd,rfdno=7,wfdno=7,msize=65536,aname=drvfs;path=G:\;uid=1000;gid=1000;metadata;symlinkroot=/mnt/
```

### Expected Behavior

no error

### Actual Behavior

```
[    5.575693] init: (1) ERROR: UtilCreateProcessAndWait:501: /bin/mount failed with status 0x
[    5.575700] 2000
[    5.575714] init: (1) ERROR: MountPlan9:493: mount cache=mmap,noatime,trans=fd,rfdno=7,wfdno=7,msize=65536,aname=drvfs;path=G:\;uid=1000;gid=1000;metadata;symlinkroot=/mnt/
```

**Comment by benhillis** [comment]
Any output in dmesg?

**Comment by benhillis** [comment]
@Jessen-Li - you're probably missing some required kernel config options. I'd suggest comparing your kernel config to that of the support kernel.
