### ISSUE TITLE
Windows 10 Enterprise install fails with error code 80070005

### ISSUE THREAD

**Issue by phawxby** [Microsoft/WSL#852]
- A brief description
  When installing bash on Windows 10 Enterprise the install fails with error code 80070005. Weirdly all files seem to be getting properly extracted into AppData\Local\lxss\rootfs. 
- Expected results
  Bash installs
- Actual results (with terminal output if applicable)
  Error 80070005
- Your Windows build number
  Version 1607, Build 14393.51
- Steps / commands required to reproduce the error
  Elevated command prompt. 

```
C:\WINDOWS\system32>lxrun /uninstall /full /y
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Uninstalling...

C:\WINDOWS\system32>LxRun.exe /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070005
```

**Comment by benhillis** [comment]
Would you be able to take a trace and share it with me?

1. Download the below two .txt files and rename them .cmd
2. Run start_lxcore_trace.cmd from an admin command prompt
3. Launch bash.exe
4. Wait until you see the error.
5. Run stop_lxcore_trace.cmd from an admin command prompt
You should now see three .etl files in the directory you ran the script from.
Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill and russalex. Also kindly include the build number you're running.
https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by phawxby** [comment]
Done. Thank you!

**Comment by benhillis** [comment]
Thanks for sharing the traces.  The failure is coming from when we are extracting the .tar.gz file, somewhere in the middle one of the file creations fails with access denied.  Is there anything non-standard with your user's configuration or anything "interesting" you can think of you've done to your user directory (C:\Users\<username>).

Could you share the contents of the below registry key?
HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\ dword:ObCaseInsensitive

**Comment by phawxby** [comment]
There is a lot about this machine which is "interesting". It's running within the corporate domain but not running a standard corporate build (so I could get Windows 10). I've got group policy restrictions and lumbered with McAfee which I can't even temporarily disable. The one thing I do have going for me is I have full admin access.

![image](https://cloud.githubusercontent.com/assets/1090602/17562942/06d39dee-5f25-11e6-8d02-26f22d0a4098.png)

**Comment by benhillis** [comment]
I wonder if the McAfee filter driver is failing the file creation.

**Comment by phawxby** [comment]
I'll see what I can do about getting McAfee turned off and report back, it may take a little while.

**Comment by phawxby** [comment]
@benhillis mystery solved. I spoke with systems and had McAfee temporarily disabled and all appears to be working. Weirdly it stalled at this point and didn't go any further, but opening a second window and running bash brought up bash. 

```
C:\WINDOWS\system32>LxRun.exe /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
```

I've tried out installing a few things and everything appears to be behaving so I don't know why it stalled.
