### ISSUE TITLE
Run Debian GNU/Hurd natively.

### ISSUE THREAD

**Issue by Zopolis4** [microsoft/WSL#8521]
Currently, I do GNU/Hurd development under the Xen hypervisor, in a Debian WSL2 setup, but this presents some challenges, and is a hassle.

I'm not sure how feasible it would be, but having the ability to install and use mach in the same way that the linux kernel is used would be extremely convinent.

**Comment by WSLUser** [comment]
If it's a matter of determining if all the kernel config options are enabled for mach, I'd check mach's documentation for the required config entries, and then search the kernel config for WSL2 to determine if there's anything missing. You are free to use a custom kernel config, even a custom kernel if desired and simply map it in the .wslconfig file.

**Comment by elsaco** [comment]
The Hurd kernel API is not compatible with the Linux kernel.  All WSL instances use the same kernel and even though a custom one can be specified in `.wslconfig` this is systemwide not per distro. It helps to think of WSL instances as containers and not vms.

**Comment by Zopolis4** [comment]
I'm aware its incompatible, but where does that break WSL? Is the area that would need to be modified open source?
