### ISSUE TITLE
Ubuntu 22.04 WSL2 opens to GUI with blank screen

### ISSUE THREAD

**Issue by thesalmonidae** [microsoft/WSL#8525]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop 4.9.1

### Repro Steps

Go to Microsoft store, search for Ubuntu 22.04, install, open.

### Expected Behavior

I expect that at the GUI I could create an user.

### Actual Behavior

The GUI is blank, cannot create an user.

### Diagnostic Logs

<img width="485" alt="Screenshot 2022-06-18 110311" src="https://user-images.githubusercontent.com/37503589/174428938-9d5e015b-19c6-4f70-8a89-66928d483214.png">
<img width="867" alt="Screenshot 2022-06-18 110535" src="https://user-images.githubusercontent.com/37503589/174428940-a4c1cc5b-f2a0-4db0-905e-d25f6630a423.png">
<img width="674" alt="Screenshot 2022-06-18 110958" src="https://user-images.githubusercontent.com/37503589/174429037-9299a20a-65bf-4071-9c32-619c84bc4f2a.png">

**Comment by thesalmonidae** [comment]
Oh, btw, I have Lenovo X1 Nano 1st gen and it indeed has the Intel gpu.

**Comment by gnsmrky** [comment]
Same for me.  Intel 12th gen Core i7.  From the error output, seems like some fonts or config files missing.  May be the files needed by the Ubuntu OOBE.

![wsl2_ubuntu2204-oobe-error](https://user-images.githubusercontent.com/18223627/175552237-7e9ed6f3-f4b7-48f8-91ae-d8451c2a5a55.png)

I've worked around this using text UI profile setup.
1. Install Ubuntu 22.04 from Microsoft Store.
2. Launch Ubuntu 22.04.
3. Once OOBE unpacks completed and shows the blank "Ubuntu WSL" windows, simply close the window.  
   - It will bring up the Ubuntu console window as root user.  Close this console window.
4. Open PowerShell and run the following.  It brings up the text mode `tui` profile setup instead.
   ```
   wsl --shutdown
   wsl --unregister Ubuntu-22.04
   ubuntu2204.exe --ui=tui
   ```
![Ubuntu2204-tui-00](https://user-images.githubusercontent.com/18223627/175556514-657c3720-5ebb-48ce-a60f-56ae7f054108.png)
![Ubuntu2204-tui](https://user-images.githubusercontent.com/18223627/175555418-9c817532-5f85-400e-b4e5-c0a82acf18db.png)
![Ubuntu2204-tui-02](https://user-images.githubusercontent.com/18223627/175556041-4c3f9018-bf16-4bbf-8f41-2eb172613037.png)
![Ubuntu2204-tui-03](https://user-images.githubusercontent.com/18223627/175556054-ce555323-7516-4c7a-a747-f81e28cd75b0.png)

**Comment by benhillis** [comment]
We do not own the Ubuntu 22.04 app. This should be reported to the folks at Canonical.

**Comment by gnsmrky** [comment]
Posted at [launchpad Ubuntu Wsl Bug #1979881](https://bugs.launchpad.net/ubuntuwsl/+bug/1979881)

**Comment by onomatopellan** [comment]
Quick test to know if it's gpu related. From Ubuntu22.04 bash run:
`sudo LIBGL_ALWAYS_SOFTWARE=1 /usr/libexec/wsl-setup`

If it shows the window correctly then it's a problem with with the indel windows driver.

**Comment by pawangond** [comment]
> Quick test to know if it's gpu related. From Ubuntu22.04 bash run: `sudo LIBGL_ALWAYS_SOFTWARE=1 /usr/libexec/wsl-setup`
> 
> If it shows the window correctly then it's a problem with the intel windows driver.

I tried this , it shows the setup properly after running this command but when you fill all the details and click finish setup , it crashes the pc 

Running : Latest intel beta driver (30.0.101.3113) & latest windows 11 pro insider build 25151 _220625-1835
![IMG_20220705_222442](https://user-images.githubusercontent.com/25777101/177379394-58ad0997-9018-4cea-95fb-d46eabccd18f.jpg)

**Comment by onomatopellan** [comment]
@pawangond That's a [known issue](https://blogs.windows.com/windows-insider/2022/06/29/announcing-windows-11-insider-preview-build-25151/#:~:text=%5BNEW%5D%20We%E2%80%99re%20investigating%20reports%20that%20some%20Insiders%20are%20experiencing%20bugchecks%20with%20error%20message%20KMODE_EXCEPTION_NOT_HANDLED%20in%20NetAdapterCx.sys%20starting%20with%20Build%2025145.) for build 25151. They are investigating it.

**Comment by EOM** [comment]
My Problem Windows 11 ;(
![image](https://user-images.githubusercontent.com/1219132/182258754-75b2e09f-6810-4b5e-b38f-ffee4fbed1c3.png)

**Comment by soumesh2002** [comment]
Debian (WSL 2) should be good alternative. Stable enough👌

**Comment by edurojasr** [comment]
This happen to me with WSL2 from the MS Store and Ubuntu 22.04.1

**Comment by soumesh2002** [comment]
Don't know when they gonna release a fix

**Comment by framerate** [comment]
FYI - I was trying to fix something before I had my coffee, but be aware the solution posted erases all your data. Don't be like me.

> * wsl --shutdown
> * wsl --unregister Ubuntu-22.04
> * ubuntu2204.exe --ui=tui
> * ubuntu2204 config --default-user

**Comment by jacobus** [comment]
People should be warned that `wsl --unregister` will destroy all their data in the distribution.
