### ISSUE TITLE
WSL still in Preview or not, but else where is the next Preview of WSL ?

### ISSUE THREAD

**Issue by ohault** [microsoft/WSL#8526]
Is there an Insider or Preview Program dedicated for testing upcoming version of WSL and/or kernel updates ?

On the Windows store, we can still see "Windows Subsystem for Linux Preview", but is it still a preview or not ?
The Linux kernel seems to be frozen a 5.10 meanwhile 5.20/6.0 are already coming to the horizon.

Why such a long delay? How to test upcoming support of v5.15 already available via Mariner 2.0 ?

On my Windows 11 Insider dev channel, I have see I'm using these versions, but it's not easy to figure out if it's preview or not.

WSL version: 0.60.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.34
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25140.1000

My suggestion would be to create such a program and being able to activate the channel you want.
- WSL
- WSL Preview w/o Kernel Preview
- WSL Preview /w Kernel Preview

**Comment by benhillis** [comment]
We've hit a number of issues with the 5.15 linux kernel (mostly related to 9p) that have delayed the rollout. We currently do not have plans for an external preview program, but we may revisit in the future.

**Comment by ohault** [comment]
Hi @benhillis, thank you to share this information. It helps to understand that this work is in progress and it is neither a change of direction nor a silent decision to stop this project (remember WSL1).

We can list two needs:
- official documentation of 9P implementation by Microsoft on the Windows side. 
- official documentation on https://docs.microsoft.com/en-us/windows/wsl/ of the complete WSL 2 architecture - WSL https://i.redd.it/po98dksksjx21.png

The big question is then the following

If you currently encounter difficulties on the Linux side where both 9P Linux implementation and Linux kernel are Open Source, why don't you work with the corresponding communities to solve these problems ?

**Comment by ohault** [comment]
Thank you for the [WSL preview for Insiders](https://twitter.com/benhillis/status/1554619646812164096). 
Congratulation to have solved the 9P issue with [5.15 kernel](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.57.1).
About documentation needs, I have just created in follow-up [this ticket](https://github.com/microsoft/WSL/issues/8731)
