### ISSUE TITLE
Importing root filesystem larger than 256GB fails

### ISSUE THREAD

**Issue by DanTheMan827** [microsoft/WSL#8532]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

Attempt to import a root filesystem larger than 256GB, the specific command I used is as follows:

```
wsl xz -cd myroot.tar.xz | wsl --import mydistro "X:\mydistro" -
```

### Expected Behavior

Either the import should fail, or it should grow the drive image until the import has finished.

### Actual Behavior

The vhdx file grows to approximately 252GB while the import command reports no errors, and also never finishes.

### Other Thoughts

Perhaps a command argument could be added to specify the maximum size of the Linux file system during import or creation

**Comment by extinguisha999** [comment]
![Uploading Image_262914_1544853572.jpeg…]()

**Comment by benhillis** [comment]
This is resolved in the store version of WSL.

**Comment by extinguisha999** [comment]
Willis who plz no tip officer
