### ISSUE TITLE
WSL startup problem

### ISSUE THREAD

**Issue by LiHanGod** [microsoft/WSL#8534]
### Version

Microsoft Windows [版本 10.0.19043.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-22.04

### Repro Steps

```shell
PS C:\Users\hanli> wsl
请启用虚拟机平台 Windows 功能并确保在 BIOS 中启用虚拟化。
有关信息，请访问 https://aka.ms/wsl2-install

Enable the virtual machine platform windows feature and ensure virtualization is enabled in the BIOS
```

![](https://raw.githubusercontent.com/LiHanGod/saveData/master/wslBug.png)

I started 
- [X] Hyper-V,
- [X]  windows virtual machine monitoring platform 
- [X]  virtual machine platform

### Expected Behavior

Successfully run WSL

### Actual Behavior

When running WSL, Enable the virtual machine platform windows feature and ensure virtualization is enabled in the BIOS

**Comment by LiHanGod** [comment]
### Self solving steps
I used the answer to this question [https://github.com/microsoft/WSL/issues/5363#issuecomment-641418120](https://github.com/microsoft/WSL/issues/5363#issuecomment-641418120)
1. Open corresponding environment
    - Hyper-V
    -  windows virtual machine monitoring platform
    - virtual machine platform
1. `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
3. `bcdedit /set hypervisorlaunchtype auto`
4. reboot

Same error reporting
```shell
PS C:\Users\hanli> wsl
请启用虚拟机平台 Windows 功能并确保在 BIOS 中启用虚拟化。
有关信息，请访问 https://aka.ms/wsl2-install

Enable the virtual machine platform windows feature and ensure virtualization is enabled in the BIOS
```

### Using log scripts
i use collect logs using this page [https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md)

```xml
<?xml version="1.0"?>
<WindowsPerformanceRecorder Version="1">
  <Profiles>
    <EventCollector Id="Collector" Name="Collector">
      <BufferSize Value="256"/>
      <Buffers Value="1024"/>
    </EventCollector>
   
    <EventProvider Id="lxcore_kernel" Name="0CD1C309-0878-4515-83DB-749843B3F5C9"/>
    <EventProvider Id="lxcore_user" Name="D90B9468-67F0-5B3B-42CC-82AC81FFD960"/>
    <EventProvider Id="lxcore_service" Name="B99CDB5A-039C-5046-E672-1A0DE0A40211"/>
    <EventProvider Id="vm_chipset" Name="de9ba731-7f33-4f44-98c9-6cac856b9f83"/>
    <EventProvider Id="vmcompute_dll" Name="AF7FD3A7-B248-460C-A9F5-FEC39EF8468C"/>
    <EventProvider Id="vmcompute" Name="17103E3F-3C6E-4677-BB17-3B267EB5BE57"/>
    <EventProvider Id="vmmm" Name="6066F867-7CA1-4418-85FD-36E3F9C0600C"/>
    <EventProvider Id="vmwp" Name="51DDFA29-D5C8-4803-BE4B-2ECB715570FE"/>
    <EventProvider Id="9p" Name="e13c8d52-b153-571f-78c5-1d4098af2a1e"/>
    <EventProvider Id="p9rdr" Name="bb1d36f0-e0e0-48cc-9493-fef0e3d0b28c" />
    <EventProvider Id="mup" Name="20c46239-d059-4214-a11e-7d6769cbe020" />
    <EventProvider Id="rfsmon" Name="51734B23-5B7E-4892-BA8E-45BC110B735C" />
    <EventProvider Id="hyperv_storage" Name="c7ad62c6-5c99-5a1b-bbc4-0821ae5b765e" />
    <EventProvider Id="hns" Name="0c885e0d-6eb6-476c-a048-2457eed3a5c1" />
    <Profile
      Id="WSL.Verbose.File"
      Name="WSL"
      Description="Traces for all WSL components"
      LoggingMode="File"
      DetailLevel="Verbose"
      >
      <Collectors>
        <EventCollectorId Value="Collector">
          <EventProviders>
            <EventProviderId Value="lxcore_kernel"/>
            <EventProviderId Value="lxcore_user"/>
            <EventProviderId Value="lxcore_service"/>
            <EventProviderId Value="vm_chipset"/>
            <EventProviderId Value="vmcompute_dll"/>
            <EventProviderId Value="vmcompute"/>
            <EventProviderId Value="vmmm"/>
            <EventProviderId Value="vmwp"/>
            <EventProviderId Value="9p"/>
            <EventProviderId Value="p9rdr"/>
            <EventProviderId Value="mup"/>
            <EventProviderId Value="rfsmon"/>
            <EventProviderId Value="hyperv_storage"/>
            <EventProviderId Value="hns"/>
          </EventProviders>
        </EventCollectorId>
      </Collectors>
    </Profile>
  </Profiles>
</WindowsPerformanceRecorder>
```'

Are there any more ways to find problems？

**Comment by fuwaa** [comment]
Some of the uncommon solutions posted here might help probably?
Ref #4930 #6808  [MicrosoftDocs/#602](https://github.com/MicrosoftDocs/WSL/issues/602)

**Comment by LiHanGod** [comment]
@fuwaa thank you，I have seen these problems and tried these solutions
Is there a tutorial on how to reinstall WSL

**Comment by fuwaa** [comment]
This might be worth a shot for uninstalling:
https://pureinfotech.com/uninstall-wsl2-windows-10/

Then you can try reinstalling using the official method again
https://docs.microsoft.com/en-us/windows/wsl/install

---

Other than that I'm stumped, wouldn't hurt to try double checking your BIOS too since you haven't mentioned anything about it

**Comment by LiHanGod** [comment]
@fuwaa I solved my problem，I used the software on this page to update to the latest version of win10，WSL reinstallation succeeded
[https://www.microsoft.com/zh-cn/software-download/windows10](https://www.microsoft.com/zh-cn/software-download/windows10)

**Comment by fuwaa** [comment]
> @fuwaa I solved my problem，I used the software on this page to update to the latest version of win10，WSL reinstallation succeeded
> [https://www.microsoft.com/zh-cn/software-download/windows10](https://www.microsoft.com/zh-cn/software-download/windows10)

That's really good to hear!
