### ISSUE TITLE
read() past EOF has side effects - leads to program failure

### ISSUE THREAD

**Issue by RaymondCheng** [microsoft/WSL#8535]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Other Software

FFmpeg (built from source)

### Repro Steps

1. Set WSL2, install Ubuntu 22.04 LTS from Store. If it matters, this is Win11 VM Guest running under Win11 Host.
2. sudo apt-get -y install autoconf automake build-essential cmake git-core libtool pkg-config wget zlib1g-dev yasm nasm gawk libunistring-dev libgnutls28-dev
3. cd ~ (for speed)
4. git clone https://github.com/FFmpeg/FFmpeg.git
5. cd FFmpeg
6. ./configure
6.5. [ADDED 2022/07/09]: mkdir /mnt/c/OSS/fate-suite if necessary, then ln -s /mnt/c/OSS/fate-suite ~/fate-suite. This is necessary, NO REPRO on ext4, only NTFS. You can also just use /mnt/c/OSS/fate-suite directly instead of ~/fate-suite or ../../fate-suite, the reason I do the symbolic link in my development environment is because I cross-compile ffmpeg for Windows as well, so I like to share the relatively large fate-suite directory between the two environments.
7. make -j`nproc` fate-rsync SAMPLES=../../fate-suite
8. make -j`nproc` libavformat/tests/seek
9. libavformat/tests/seek ../../fate-suite/mkv/codec_delay_opus.mkv

### Expected Behavior

No red error messages at console.

### Actual Behavior

Red error messages:
Element at 0x2da ending at 0x<offset> exceeds containing master element ending at 0x2571
0x00 at pos 2852 (0xb24) invalid as first byte of an EBML number

ROOT CAUSE
Install VS Code, run "code ." from FFmpeg dir, set breakpoint at libavformat/file.c, in file_read()'s call to read(). On the second call to this function, pay attention to value of buf[0] before and after the call to read(): on native Linux 22.04 LTS (non-WSL2), this function returns 0 and buf[0] is same before/after the call, under WSL2, buf[0] has changed even though return value of 0 SHOULD have meant NO SIDE EFFECTS.

### Diagnostic Logs

https://gist.github.com/RaymondCheng/07661791a72abe2e3d47463bca01fd66

**Comment by pmartincic** [comment]
I'd suggest filing this over at https://github.com/microsoft/WSL2-Linux-Kernel

**Comment by pmartincic** [comment]
If you want to know what's writing the buffer you should be able to set a write access breakpoint on the location in question.

**Comment by RaymondCheng** [comment]
> I'd suggest filing this over at https://github.com/microsoft/WSL2-Linux-Kernel

Hi Peter, that repo says it's not possible to report issues there, that they should either be reported here (which is what this is), or else work with the upstream developers.

> If you want to know what's writing the buffer you should be able to set a write access breakpoint on the location in question.

I followed your suggestion and did an awatch -l *(int*)0x<address of buffer passed to read()>. What I find is that this only captures user-mode accesses, so the unexpected write must be happening in kernel mode. So in other words:
a) Set awatch before calling first read().
b) Step over first read() returns 9585, indicating that many bytes read. The data breakpoint did not get hit, but clearly read() did modify the memory as expected, in order to write those 9585 bytes.
c) Running from this point DOES hit the data breakpoint, as the buffer is accessed by user-mode code.
d) Step over second read() returns 0 bytes, data breakpoint NOT hit, buffer passed to read() IS modified (NOT EXPECTED).

Can you suggest how I can work with the upstream developers to find out why read() is modifying the buffer passed to it even when it has read nothing (returns 0)?

**Comment by tyhicks** [comment]
@RaymondCheng could you give me the output of `findmnt -no FSTYPE -T <PATH/TO/codec_delay_opus.mkv>`?  Also, can you check to see if this happens on a different filesystem. Perhaps try this under /dev/shm/. Thanks!

**Comment by RaymondCheng** [comment]
I think you've figured out something quite important: I get 9p from your findmnt command, which means that my repro instructions were actually WRONG. I had forgotten that between steps 6 and 7:

6.5. ln -s /mnt/c/OSS/fate-suite ~/fate-suite

Without this step 6.5, my repro steps above FAIL. I have now verified that the bug only repros when the source file is in NTFS, NOT in ext4. I've amended my repro steps above to add a step 6.5.

**Comment by tyhicks** [comment]
@RaymondCheng just to be crystal clear, the file being operated on is within a 9p mount inside of the WSL2 VM that's backed by NTFS on the Windows host, correct?

**Comment by RaymondCheng** [comment]
@tyhicks, yes, exactly as you state, the file in question (/mnt/c/OSS/fate-suite/mkv/codec_delay_opus.mkv) uses the standard WSL2 /mnt/c mount point, and the file itself resides on the host Windows C:\OSS\fate-suite\mkv\codec_delay_opus.mkv which happens to be an NTFS partition.

**Comment by kelsey-steele** [comment]
Hi @RaymondCheng. Thank you for your patience on this issue. Can you please update to the latest WSL2 kernel (5.15.62.1-microsoft-standard-WSL2) and verify if this problem still exists?

**Comment by RaymondCheng** [comment]
Verified fixed in kernel version 5.15.57.1-microsoft-standard-WSL2, and further verified that all FFmpeg FATE tests pass now (make -j`nproc` fate SAMPLES=<path-to-fate-suite-dir>). Thanks!
