### ISSUE TITLE
perf/builtin-sched.c:673:13 error: comparison of distinct pointer types [-Werror,-Wcompare-distinct-pointer-types]

### ISSUE THREAD

**Issue by benoit-dubreuil** [microsoft/WSL#8540]
### Version

Microsoft Windows [Version 10.0.19043.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.y

### Distro Version

Ubuntu 22.04 LTS

### Other Software

Software in WSL2:
`tools/perf`, see [builtin-sched.c line 673](https://github.com/microsoft/WSL2-Linux-Kernel/blame/linux-msft-wsl-5.10.y/tools/perf/builtin-sched.c#L673)
`clang` version `1:14.0-55~exp2`

### Repro Steps

In WSL2:

```sh
export CC=clang

git clone --depth=1 https://github.com/microsoft/WSL2-Linux-Kernel.git
cd WSL2-Linux-Kernel/tools/perf
make
```

### Expected Behavior

I expected `perf` to compile flawlessly.

### Actual Behavior

`WSL2-Linux-Kernel/tools/perf/builtin-sched.c` breaks at the line 673, character 13, due to a warning that is actually an error (`-Werror`).
The warning is `-Wcompare-distinct-pointer-types`.

The type of the expression `& (16 * 2014)` is `int *`.
The type of the expression `(__sysconf(75))` is `long *`.
The macro `max(_max1, _max2)` from `WSL2-Linux-Kernel/tools/include/linux/kernel.h:43:17` compares both expressions and thus a warning is emitted.

### Diagnostic Logs

```
builtin-sched.c:673:13: error: comparison of distinct pointer types ('typeof (16 * 1024) *' (aka 'int *') and 'typeof (__sysconf(75)) *' (aka 'long *')) [-Werror,-Wcompare-distinct-pointer-types]
                        (size_t) max(16 * 1024, PTHREAD_STACK_MIN));
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WSL2-Linux-Kernel/tools/include/linux/kernel.h:43:17: note: expanded from macro 'max'
        (void) (&_max1 == &_max2);              \
                ~~~~~~ ^  ~~~~~~
  CC       builtin-report.o
```

**Comment by pmartincic** [comment]
Please make a PR on the other repo.

**Comment by iwonder1996** [comment]
I encountered the same problem as you did. I resolved the issue by updating WSL2.
In powershell:
```powershell
wsl --update
``` 

Then in WSL2 do your Repro Steps：

```shell
export KERNEL_VERSION=$(uname -r | cut -d'-' -f1)
git clone --depth 1 --single-branch --branch=linux-msft-wsl-${KERNEL_VERSION} https://github.com/microsoft/WSL2-Linux-Kernel.git
cd WSL2-Linux-Kernel/tools/perf
make
```
