### ISSUE TITLE
/sys/kernel/debug empty

### ISSUE THREAD

**Issue by Jessen-Li** [microsoft/WSL#8542]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.18.3linux-5.18.ylinux-5.9.18.y+

### Distro Version

20.04

### Repro Steps

enabled debug in .config by $Make Menuconfig, e.g. `CONFIG_DEBUG_INFO=y`
and rebuilt the kernel, reboot, the /sys/kernel/debug directory is empty

### Expected Behavior

the /sys/kernel/debug directory is not empty, may contain directory like _tracing_

### Actual Behavior

the /sys/kernel/debug directory is empty

**Comment by elsaco** [comment]
@Jessen-Li you need to mount `debugfs` also.
