### ISSUE TITLE
no modules loaded after reboot

### ISSUE THREAD

**Issue by Jessen-Li** [microsoft/WSL#8543]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.18.3linux-5.18.ylinux-5.9.18.y+

### Distro Version

20.04

### Repro Steps

enabled **m**  in a few options in `$Make Menuconfig`. And rebuilt the kernel, and `$make modules_install` has the following output:
![image](https://user-images.githubusercontent.com/26531654/175245086-8bd1ed1d-eda6-44f3-bd98-2ba17835b590.png)
But after replace the kernel image and reboot, and run `$lsmod`, 

### Expected Behavior

run `$lsmod ` should output some modules loaded automatically during reboot

### Actual Behavior

![image](https://user-images.githubusercontent.com/26531654/175245811-c0ac62f2-dd0f-4f34-a2c0-bcb9960e69d7.png)

**Comment by elsaco** [comment]
@Jessen-Li what is the content of `/etc/modules`?

**Comment by Jessen-Li** [comment]
![image](https://user-images.githubusercontent.com/26531654/175324263-35969493-b78a-4c39-8224-03153eadc21d.png)
Why is this? Is it set by default config? And adding modules there would take effect after reboot?

**Comment by Jessen-Li** [comment]
I add the following:
![image](https://user-images.githubusercontent.com/26531654/175326103-129d527b-3694-402c-b361-02fd0ad12014.png)
And reboot, still the same, no module is loaded.
