### ISSUE TITLE
Run WSL under Jenkins fails with exit code 0xC0000409

### ISSUE THREAD

**Issue by renekempen** [microsoft/WSL#8545]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-18.04 and Rocky

### Other Software

Jenkins version 2.332.3 on Windows 
Jenkins master is Windows Server 2016 version 1607
Jenkins Slave/Node where wsl2 is running is Windows 10 Pro version 21H2 OSBuild 19044.1706

Installed 2 wsl versions
> wsl -l -v
  NAME            STATE           VERSION
* Rocky           Stopped         2
  Ubuntu-18.04    Stopped         2

Ubuntu-18.04 is default distribution from MS site, Rocky is based on Centos 7.

### Repro Steps

Create a Jenkins job as a freestyle project, restrict this job to only run on the wsl node and enable in Build tab "Execute windows batch command"
The batch command is:
echo Exit Code is %errorlevel%
wsl -d Ubuntu-18.04 -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build
echo Exit Code is %errorlevel%
wsl -d Rocky -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build
echo Exit Code is %errorlevel%

### Expected Behavior

When running this in a command prompt or PowerShell as user ovl-svc-embedded-ba i would get:

>echo Exit Code is %errorlevel%
Exit Code is 0
>wsl -d Ubuntu-18.04 -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build
echo Exit Code is %errorlevel%
total 28
........<folder list>
>echo Exit Code is %errorlevel%
Exit Code is 0
>wsl -d Rocky -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build
echo Exit Code is %errorlevel%
total 28
........<folder list>
>echo Exit Code is %errorlevel%
Exit Code is 0

### Actual Behavior

Jenkins console output is:
09:30:41 Exit Code is 0
09:30:41 
09:30:41 d:\jenkins\workspace\Tano-WSL-Build>wsl -d Ubuntu-18.04 -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build 
09:30:41 
09:30:41 d:\jenkins\workspace\Tano-WSL-Build>echo Exit Code is -1073740791 
09:30:41 Exit Code is -1073740791
09:30:41 
09:30:41 d:\jenkins\workspace\Tano-WSL-Build>wsl -d Rocky -u ovl-svc-embedded-ba --cd /mnt/d/jenkins/workspace/Tano-WSL-Build --exec ls -lisa /mnt/d/jenkins/workspace/Tano-WSL-Build 
09:30:42 
09:30:42 d:\jenkins\workspace\Tano-WSL-Build>echo Exit Code is -1073740791 
09:30:42 Exit Code is -1073740791

### Diagnostic Logs

No data available (yet)

**Comment by renekempen** [comment]
I get the same error when Jenkins is running a basic wsl command, like: wsl -l -v

09:45:28 d:\jenkins\workspace\Tano-WSL-Build>wsl -l -v 
09:45:29 
09:45:29 d:\jenkins\workspace\Tano-WSL-Build>echo Exit Code is -1073740791 
09:45:29 Exit Code is -1073740791

**Comment by renekempen** [comment]
Seems that the Jenkins Slave service is running as wsadmin.
Running wsl commands in a command window as wsadmin gives the same errors, somehow wsl commands need to be run as user on a Windows 10 pc...

**Comment by renekempen** [comment]
Closing issue

**Comment by mathieu-b** [comment]
Hi @renekempen 
I see the issue has been closed. I believe I'm facing a similar issue, where when wsl is called from a Jenkins context, it silently fails (a non-zero error-code is probably returned).

How did you solve this issue in the end?

Best regards.

**Comment by renekempen** [comment]
We run Jenkins swarm client under the nssm program as a service.
When running it as wsadmin we get the error.
When loging in as a user then manually run the swarm client (not using nssm) the issue is solved.
Somehow wsl cannot be executed as admin but as another user it is no problem...

**Comment by mathieu-b** [comment]
> Hi @mathieu-b We run Jenkins swarm client under the nssm program as a service. When running it as wsadmin we get the error. When loging in as a user then manually run the swarm client (not using nssm) the issue is solved. Somehow wsl cannot be executed as wsadmin but as another user it is no problem...

Ok, many thanks for the clarification @renekempen !

So you are using this system https://nssm.cc/ 👌🏻

In our case we are using winsw, as suggested by the "official" video tutorial here: 
- https://www.youtube.com/watch?v=N8AQTlHoBKc&t=249s
- https://github.com/winsw/winsw

We are now at the point of trying to run the service as a plain non-admin user.

Thanks again
