### ISSUE TITLE
Problem with wildcarding in csh

### ISSUE THREAD

**Issue by acb764se** [microsoft/WSL#8546]
### Version

Microsoft Windows [Version 10.0.19044.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1237-Microsoft Sat Sep 11 14:32:00 PST 2021

### Distro Version

Release:        20.04

### Repro Steps

`
myPrompt:~/BRLanal> ls rootFiles/ccbar/Run?/prodDb.txt
rootFiles/ccbar/Run1/prodDb.txt  rootFiles/ccbar/Run3/prodDb.txt  rootFiles/ccbar/Run5/prodDb.txt
rootFiles/ccbar/Run2/prodDb.txt  rootFiles/ccbar/Run4/prodDb.txt  rootFiles/ccbar/Run6/prodDb.txt

myPrompt:~/BRLanal> ls rootFiles/ccbar/Run[1-3]/prodDb.txt
rootFiles/ccbar/Run1/prodDb.txt  rootFiles/ccbar/Run2/prodDb.txt  rootFiles/ccbar/Run3/prodDb.txt

myPrompt:~/BRLanal> ls rootFiles/ccbar/Run[4-6]/prodDb.txt
rootFiles/ccbar/Run1/prodDb.txt  rootFiles/ccbar/Run3/prodDb.txt  rootFiles/ccbar/Run5/prodDb.txt
rootFiles/ccbar/Run2/prodDb.txt  rootFiles/ccbar/Run4/prodDb.txt  rootFiles/ccbar/Run6/prodDb.txt
`

### Expected Behavior

Last command should list 3 files only (shell is /bin/tcsh)

### Actual Behavior

It lists all 6.

**Comment by OneBlue** [comment]
This look like a csh issue and not a WSL issue. Closing
