### ISSUE TITLE
Docker compose with `--abort-on-container-exit` returns a strange error

### ISSUE THREAD

**Issue by jonsnowseven** [microsoft/WSL#8547]
### Version

Microsoft Windows [Version 10.0.19044.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop (Windows) v4.9.0

### Repro Steps

Using [this example](https://docs.docker.com/compose/gettingstarted/) but changing the `CMD`, in Dockerfile, to `CMD ["pip", "list"]`. Then run `docker-compose up --abort-on-container-exit`.
 

### Expected Behavior

Execute command without any error.

### Actual Behavior

```command-line
...
docker-compose-test-web-1    | WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
docker-compose-test-web-1    | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
docker-compose-test-web-1 exited with code 0
Aborting on container exit...
[+] Running 2/2
 ⠿ Container docker-compose-test-web-1    Stoppe...                                       0.0s
 ⠿ Container docker-compose-test-redis-1  Stop...                                         0.4s
ERRO[0003] 0  <----------------- STRANGE ERROR
```

**Comment by benhillis** [comment]
@jonsnowseven - should probably post this on the moby github.

**Comment by jonsnowseven** [comment]
Should I create an issue [here](https://github.com/moby/moby), @benhillis?
