### ISSUE TITLE
Can't install distro in WSL2, also can't upgrade WSL to WSL2 even Virtualization been enabled

### ISSUE THREAD

**Issue by Tisoy21** [microsoft/WSL#8553]
### Version

Microsoft Windows [Version 10.0.19044.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

Need to install "Docker Desktop" since it requires the WSL2.

### Repro Steps

![Screenshot 2022-06-27 193401](https://user-images.githubusercontent.com/44186119/175958128-98646580-a53f-48f8-ab77-c26ced042862.png)
![Screenshot 2022-06-27 193306](https://user-images.githubusercontent.com/44186119/175958221-1b344fb5-cee6-4617-980b-31c345f6e975.png)
![Screenshot 2022-06-27 215401](https://user-images.githubusercontent.com/44186119/175958374-a906e3dd-55a8-4bc2-974b-34147d5ba057.png)

### Expected Behavior

Expecting successfully install the ubuntu distro

**Comment by SirMishaa** [comment]
![image](https://user-images.githubusercontent.com/42717232/175966863-2febf93d-217d-4042-8b52-86baf67cdd2d.png)

It looks like you just need to reboot

**Comment by Tisoy21** [comment]
@SirMishaa Yes, I did it try multiple times

**Comment by Tisoy21** [comment]
Sure thing, here's the logs
[WslLogs-2022-06-29_11-13-17.zip](https://github.com/microsoft/WSL/files/9006970/WslLogs-2022-06-29_11-13-17.zip)

**Comment by Tisoy21** [comment]
when I try to execute that .ps1 file, It shows like this
![Screenshot 2022-06-29 111648](https://user-images.githubusercontent.com/44186119/176343647-c0be01b3-4b29-4469-8a22-854b15153701.png)
