### ISSUE TITLE
Upgrading to WSL2 broke my internet drivers

### ISSUE THREAD

**Issue by EwenQuim** [microsoft/WSL#8554]
### Version

Microsoft Windows [Version 21H1, build 19043.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop

### Repro Steps

- Upgrade following [this guide ](https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2). 
- Reboot.
- Now, no network appear on the network list, and the network card isn't recognized anymore.

### Expected Behavior

The network card should work

### Actual Behavior

The network card isn't recognized anymore

**Comment by OneBlue** [comment]
Thanks for reporting this @EwenQuim.

It's difficult to imagine how WSL2 could impact your network adapter. Maybe something else was pending a reboot and caused the issue you're seeing ? 

Do you still see the network adapter in the device manager ?

**Comment by EwenQuim** [comment]
Now I can't see the network anymore because after a restart, I have a BSoD. 
My Windows OS is completely broken.

I can boot on a linux drive and internet works, though.

I am very sad to lose my Windows after this upgrade :/
