### ISSUE TITLE
Windows time zone configuration not reflected into WSL box

### ISSUE THREAD

**Issue by wyoung** [Microsoft/WSL#856]
The installation of the Perl `Date::Manip` package fails due to its inability to figure out the local time zone. It is likely that forcing the install would work, but then it would fail in operation for the same reason.

Simple test case:

```
$ sudo apt install cpanminus
$ sudo cpanm Date::Manip
```
- Actual results

<pre>--> Working on Date::Manip
Fetching http://www.cpan.org/authors/id/S/SB/SBECK/Date-Manip-6.54.tar.gz ... OK
Configuring Date-Manip-6.54 ... OK
Building and testing Date-Manip-6.54 ... FAIL
! Installing Date::Manip failed. See /home/me/.cpanm/work/1470853508.18607/build.log for details. Retry with --force to force install it.
</pre>

The `build.log` file contains a bunch of complaints of the form:

<pre>ERROR: Date::Manip unable to determine Time Zone.
ERROR LOADING MODULE: Date::Manip::DM6 at /home/me/.cpanm/work/1470853508.1Compilation failed in require at t/base._fix_year.50.t line 8.
BEGIN failed--compilation aborted at t/base._fix_year.50.t line 8.</pre>

- Expected results

Install without fuss as it does on "real" Ubuntu :)
- Your Windows build number

14393 (Anniversary Edition, upgraded from 10xxx just yesterday)

**Comment by aseering** [comment]
Hm...  Do you know offhand how the `Date::Manip` package tries to figure out the local time zone?  My WSL system has a correct `/etc/localtime`, and the `date` command correctly reports the time zone that I'm in.

**Comment by iz0eyj** [comment]
@aseering check "timedatectl":
Federico@BESTIA:~$ timedatectl status
Failed to get D-Bus connection: Failed to connect to socket /var/run/dbus/system_bus_socket: File o directory non esistente

dbus... please dbus... :)

**Comment by iz0eyj** [comment]
@aseering look @ #869

**Comment by dimo414** [comment]
I think I've run into the same issue in Java (it could be a configuration mistake on my part since I installed Java manually, though I'd still expect it to read the system time zone).

If I run:

    System.out.println(
        java.time.ZoneId.systemDefault() + " " +
        java.time.ZonedDateTime.now(java.time.ZoneId.systemDefault()).getOffset());

Via `cmd` or Cygwin (both using the same Java binary) I see:

    America/Los_Angeles -07:00

But from WSL I see:

    GMT Z

Despite this, the `date` command in Bash prints the right timezone:

    $ date '+%:z'
    -07:00

**Comment by marwatk** [comment]
> `sudo dpkg-reconfigure tzdata`

This seems to work for Date::Manip as well (it passes all tests after)

**Comment by wyoung** [comment]
Ridiculous, but correct!

Thank you, @marwatk

**Comment by dimo414** [comment]
@wyoung why'd you mark this closed? I think `dpkg-reconfigure` is a workaround - people shouldn't have to re-configure the timezone manually in WSL (or, if they really, really should, that needs to be documented clearly).

**Comment by wyoung** [comment]
@dimo414 This bug is nearly a year old now, with no movement from Microsoft on it. I closed it because the best expectation I have for this is that people will now be able to Google up the answer.

**Comment by dimo414** [comment]
Well closing the issue when it's not actually resolved is a good way to ensure it takes longer... Just because it hasn't been addressed yet doesn't mean it won't be once the WSL folks have time to prioritize it.

**Comment by rkeithhill** [comment]
We're seeing the same issue in some gtest failures that are testing a date/time class.  There doesn't seem to be a default timezone set.  :-(

**Comment by wyoung** [comment]
@rkeithhill  Did you try `sudo dpkg-reconfigure tzdata`?

**Comment by rkeithhill** [comment]
No, I added `export TZ=/usr/share/zoneinfo/America/Denver` to my .bashrc file.  I take it the `sudo dpkg-reconfigure tzdata` is a better way to go?

**Comment by wyoung** [comment]
@rkeithhill It's the right way to fix it, given the current state of WSL. The only reason I allowed myself to be arm-twisted into keeping this bug open is the off chance that Microsoft will chose to automate this in some fashion. Ideally, changing the TZ settings in the Control Panel would update the TZ settings inside the WSL box. 

Meanwhile, we have this workaround.

**Comment by heldchen** [comment]
if microsoft decides to push the windows timezone into the WSL please make it an option. my WSL instance deliberately runs on a different timezone (UTC).

**Comment by andyneff** [comment]
@wyoung am I correct in understanding that *now* WSL does have a mechanism to do this? 

This works in WSL Ubuntu 14.04.5:

```
sudo apt-get install cpanminus
cpanm install -l Date::Manip
```

And it worked (even with `/etc/localtime` hardlinked to `/usr/share/zoneinfo/Msft/localtime` which is now the default out of the box behavior)? No `sudo dpkg-reconfigure tzdata` or `TZ` workaround needed.

- Running Windows 10 Pro Build 17134

**Comment by wyoung** [comment]
[It would seem so](https://github.com/Microsoft/WSL/issues/3109#issuecomment-381669899)

I just removed my `/etc/timezone` file and restarted WSL, and `date` continues to return the correct information.

**Comment by nitai-wipay** [comment]
> [It would seem so](https://github.com/Microsoft/WSL/issues/3109#issuecomment-381669899).
> 
> I just removed my `/etc/timezone` file and restarted WSL, and `date` continues to return the correct information.

This worked for me. And I don't have to run `sudo dpkg-reconfigure tzdata` whenever I start wsl

**Comment by tijko** [comment]
I've tried to `dpkg-reconfigure tzdata` on about half dozen WSL2 installs and all of them are still broken.  They report the correct timezone and `date` is correct but `dmesg` still has errors as shown above.
