### ISSUE TITLE
Importing Alpine Linux distribution 3.16 .tar Mini Root Filesystem to use with WSL FAILS with "Incorrect function." ERROR Message

### ISSUE THREAD

**Issue by sre-data-engineer** [microsoft/WSL#8560]
### Version

Microsoft Windows [Version 10.0.19044.1766] Pro 21H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Alpine 3.16.0 x86_64

### Other Software

Docker version 20.10.13, build a224086
Windows Subsystem for Linux was last updated on 29.03.2022

### Repro Steps

 wsl --import Alpine316 v:\wslAlpine316storage\ .\alpine-minirootfs-3.16.0-x86_64.tar

### Expected Behavior

progress bar

### Actual Behavior

_Incorrect function._

### Diagnostic Logs

[WslLogs-2022-06-29_09-55-04.zip](https://github.com/microsoft/WSL/files/9008016/WslLogs-2022-06-29_09-55-04.zip)

**Comment by Biswa96** [comment]
I can not reproduce your issue. I am using same Windows 10 version as you mentioned. Alpine 3.16 can be registered in WSL2 without any error.
