### ISSUE TITLE
Failed to install Ubuntu - WslRegisterDistribution failed with error: 0x80040307 Error: 0x80040307 (null)

### ISSUE THREAD

**Issue by shapovalovdev** [microsoft/WSL#8561]
### Version

PS C:\Users\swamp> cmd.exe /c ver  Microsoft Windows [Version 10.0.22000.778] PS C:\Users\swamp> wsl.exe --version Версия WSL: 0.61.4.0 Версия ядра: 5.10.102.1 Версия WSLg: 1.0.39 Версия MSRDC: 1.2.3213 Версия Direct3D: 1.601.0 Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows версии: 10.0.22000.778

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

PS C:\Users\swamp> wsl.exe --status Версия по умолчанию: 2 Версия WSL: 0.61.4.0 Версия ядра: 5.10.102.1 Версия WSLg: 1.0.39 Версия MSRDC: 1.2.3213 Версия Direct3D: 1.601.0 Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows версии: 10.0.22000.778

### Distro Version

Ubuntu 18.04

### Repro Steps

In powershell
wsl.exe --install Ubuntu

### Expected Behavior

Ubuntu launched

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80040307
Error: 0x80040307 (null)
Press any key to continue...

### Diagnostic Logs

[WslLogs-2022-06-29_09-48-36.zip](https://github.com/microsoft/WSL/files/9008166/WslLogs-2022-06-29_09-48-36.zip)

**Comment by shapovalovdev** [comment]
Somehow i fixed it
1. WSL was installed from Microsoft Store. So i decided to delete everything related to WSL [](https://pureinfotech.com/remove-linux-distro-wsl/)
`> winget uninstall`
2. Somehow i had a custom kernel in .wslconfig. Advide from this article helped me [this issue](https://github.com/microsoft/WSL/issues/5107)
3. Delete .wslconfig or remove every line except [wsl2] 
4. Remove every additional optional package from appwiz.cpl (if you not did it in 1 step)
5. Restart 
6. Make steps from [this issue](https://github.com/microsoft/WSL/issues/4618) 
- I have tried running "sfc /scannow" and rebooting
- I have tried running "DISM /Online /Cleanup-Image /Scanhealth" and 
nothing bad was reported
7. Restart
8. Reinstall wsl by recommended way. In powershell  (DO NOT turn on WSL/virtualization features or install anything before)
`wsl --install`

**Comment by OneBlue** [comment]
Looking at the logs, it looks like the issue was that your machine indeed had a custom kernel configured in .wslconfig, but the file was not found so WSL failed to start. 

Closing since the issue since it's resolved
