### ISSUE TITLE
Problem launching code or code-insiders from Fedora 35 distro on windows 11

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#8573]
### Version

WSL version: 0.61.8.0 Kernel version: 5.10.102.1 WSLg version: 1.0.39 MSRDC version: 1.2.3213 Direct3D version: 1.601.0 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22621.160

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Fedora Linux 35 (Container Image)

### Other Software

Podman  4.1.1

### Repro Steps

In bash: run

 "/mnt/c/Users/mlwp/AppData/Local/Programs/Microsoft VS Code/bin/code"

or 

 "/mnt/c/Users/mlwp/AppData/Local/Programs/Microsoft VS Code"/mnt/c/Users/mlwp/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders"

### Expected Behavior

vscode starts up and connects to distro

### Actual Behavior

<3>init: (635) ERROR: UtilAcceptVsock:245: accept4 failed 110

Note that I don't see this issue when running the same command from my Debian 11 distro

### Diagnostic Logs

[WslLogs-2022-07-02_12-29-06.zip](https://github.com/microsoft/WSL/files/9033595/WslLogs-2022-07-02_12-29-06.zip)

**Comment by mwoodpatrick** [comment]
Note I am able to Remote WSL window/folder in the Fedora distro directly from VS Code: but this connects as root is there a way to specify the desired user when using this method?

**Comment by mwoodpatrick** [comment]
This command also works

     code --remote wsl+podman-westie  /mnt/wsl/projects/git/containers/devcontainers/nix-example/

but opens as root is there a way to specify the remote username is this documented somewhere? I could not find it documented on:

     https://code.visualstudio.com/docs/remote/wsl

**Comment by elsaco** [comment]
@mwoodpatrick you'll have to setup the default user for your Fedora instance. After you'll be able to use `code --remote` and connect as user and not root.

The faster way is to user `/etc/wsl.conf` file inside Fedora, or use the registry key.

Here's sample run using `code --remote wsl`, Fedora being the default distro:


![code_wsl_f35](https://user-images.githubusercontent.com/3933920/177016428-2d5edf57-755e-44c3-8bc5-bbad34880fa9.PNG)

I didn't run into your issue, however `podman` is not installed.
