### ISSUE TITLE
BSOD with error code KERNEL_SECURITY_CHECK_FAILURE whenever I exit python3 using Ctrl+D

### ISSUE THREAD

**Issue by chausies** [microsoft/WSL#8574]
### Version

Microsoft Windows [Version 10.0.22000.778]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

20.04

### Repro Steps

```bash
$ python3
>>> # hit Ctrl+D to exit
# Whole computer crashes (BSOD) with error code KERNEL_SECURITY_CHECK_FAILURE
```

### Expected Behavior

Should just exit python normally without BSOD-ing.

### Actual Behavior

Whole computer crashes (BSOD) with error code KERNEL_SECURITY_CHECK_FAILURE

### Diagnostic Logs

Here's a stackoverflow user who had the same exact problem: https://superuser.com/q/1288190/481641

I never had this problem before. Then I upgraded to WSL2. But when I switched back to WSL 1 (with `wsl --set-version Ubuntu 1`), then this problem started happening. Btw, when I switch back to WSL2, then there's no problem.

Also, if it's relevant, I upgraded my computer from 32GB of RAM to 64 GB of RAM, which may be part of the cause.

**Comment by anthonyvdotbe** [comment]
I'm unable to reproduce with Windows 11 22H2 (using WSL 0.66.2).
