### ISSUE TITLE
BSOD with no errcode, wsl crash windows 11 when run`code`/`code-insder`

### ISSUE THREAD

**Issue by zzjin** [microsoft/WSL#8575]
### Version

10.0.25151.1010

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

ubuntu 20.04

### Other Software

vscode-insider:
```
Version: 1.69.0-insider (user setup)
Commit: 0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce
Date: 2022-07-01T05:17:04.343Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.25151
```

### Repro Steps

login in to wsl and type "vscode-insiders .", after a while the whole windows ccrash with green screen and with no bug id.

### Expected Behavior

start using vscode normarly.

### Actual Behavior

crash windows with green screen.
![IMG_20220703_191525](https://user-images.githubusercontent.com/679757/177037089-268e81b6-4707-49f6-a59f-a213861b4f37.jpg)

### Diagnostic Logs

Already tried `event viewer` but only show: `The previous system shutdown at 16:47:30 on ‎2022/‎7/‎3 was unexpected.`

Already Tried: `Collect WSL logs with Feedback hub`, but since windows crash so there is not log.

Any method can to done to issue detailed problems? thx!

Note: same version vscode-insider running on windows works fine. 
Note2: also code stable version crash windows too.so there must be the wsl2 bug.

**Comment by benhillis** [comment]
I can't totally read the name of the driver in your screen shot, but I see enough to know it's not WSL-related. I'd suggest filing an issue on feedback hub, which will be able to collect the system memory dump.

**Comment by zzjin** [comment]
> 

I've used feedback hub but since it's always suddenly crash with BOSD, so there is no log in feedback hub.
Anything I/ve missed?

**Comment by onomatopellan** [comment]
It's a [known issue](https://blogs.windows.com/windows-insider/2022/06/29/announcing-windows-11-insider-preview-build-25151/#:~:text=%5BNEW%5D%20We%E2%80%99re%20investigating%20reports%20that%20some%20Insiders%20are%20experiencing%20bugchecks%20with%20error%20message%20KMODE_EXCEPTION_NOT_HANDLED%20in%20NetAdapterCx.sys%20starting%20with%20Build%2025145.) for some users in build 25151.
