### ISSUE TITLE
Fuse folder cannot be accessed from explorer.exe 

### ISSUE THREAD

**Issue by ICHx** [microsoft/WSL#8580]
### Version

Microsoft Windows [Version 10.0.19043.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04.4 LTS

### Other Software

➜  ~ ratarmount --version
ratarmount 0.11.1
ratarmountcore 0.3.1

System Software:

Python 3.8.10
FUSE 2.9.9
libsqlite3 3.31.1

Compression Backends:

indexed_bzip2 1.3.1
indexed_gzip 1.6.13
rarfile 4.0
xz 0.4.0
indexed_zstd 1.1.3

### Repro Steps

> ratarmount xxx_output.tar.gz 
A folder mounting the tarball is then created. I could access the archive inside the wsl terminal.

### Expected Behavior

Hi, I was using ratarmount (FUSE archive mount) on Ubuntu 20.04, on WSL2 Windows 10 21H1.

I could access the archive inside the wsl terminal. I expect direct access from windows explorer.

### Actual Behavior

 I am unable to browse it from explorer.exe, with path "\\wsl$\Ubuntu\home\..."
![image](https://user-images.githubusercontent.com/11556527/177463976-cd54b1ef-b652-4d4a-b1a3-ee9479a6618b.png)

Have anyone encountered this issue?

**Comment by zcobol** [comment]
@ICHx this might help: https://github.com/microsoft/WSL/issues/8498#issuecomment-1152936607

Make sure you edit `/etc/fuse`

**Comment by ICHx** [comment]
Thank you, your advice helped.
https://github.com/mxmlnkn/ratarmount/issues/92#issuecomment-1177278026

> @ICHx this might help: [#8498 (comment)](https://github.com/microsoft/WSL/issues/8498#issuecomment-1152936607)
> 
> Make sure you edit `/etc/fuse`
