### ISSUE TITLE
Failed to find specified qdisc 

### ISSUE THREAD

**Issue by Perhurb** [microsoft/WSL#8584]
### Version

Microsoft Windows [版本 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 4.19.128/5.10

### Distro Version

Ubuntu 20.04

### Repro Steps

write append on the configwsl as follow:
```
CONFIG_NET_SCHED=y
CONFIG_NET_SCH_CBQ=m
CONFIG_NET_SCH_HTB=y
CONFIG_NET_SCH_CSZ=m
CONFIG_NET_SCH_PRIO=m
CONFIG_NET_SCH_RED=m
CONFIG_NET_SCH_SFQ=m
CONFIG_NET_SCH_TEQL=m
CONFIG_NET_SCH_TBF=m
CONFIG_NET_SCH_GRED=m
CONFIG_NET_SCH_DSMARK=m
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_QOS=y
CONFIG_NET_ESTIMATOR=y
CONFIG_NET_CLS=y
CONFIG_NET_CLS_TCINDEX=m
CONFIG_NET_CLS_ROUTE4=m
CONFIG_NET_CLS_ROUTE=y
CONFIG_NET_CLS_FW=m
CONFIG_NET_CLS_U32=m
CONFIG_NET_CLS_RSVP=m
CONFIG_NET_CLS_RSVP6=m
CONFIG_NET_CLS_POLICE=y
CONFIG_NET_SCH_NETEM=y
```
exec following commands: 
`tc qdisc add dev eth0 root netem delay 1000ms 10ms`
`tc qdisc add dev ens33 root handle 1:0 htb default 1`

### Expected Behavior

[https://github.com/microsoft/WSL/issues/6065](url)
I need to use `tc` tool to limit dev eth0. However, it looks like not supporting the module. I used those config above and start `CONFIG_NET_SCH_NETEM=y`. But there are always some wrongs.
Is there a solution that is avialable with any linux kernel version? I really need the specified solution or the alternative `Microsoft/config-wsl`.

### Actual Behavior

exec ` wondershaper eth0 2000 240` using `wondershaper` command which using the `tc` module. The error information as follow:
```
Error: Specified qdisc not found.
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
Error: Failed to find specified qdisc.
Error: Failed to find specified qdisc.
Error: Failed to find specified qdisc.
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
Error: Specified qdisc not found.
Error: Parent Qdisc doesn't exists.
We have an error talking to the kernel
```
It may cause by my error configwsl.

**Comment by elsaco** [comment]
@Perhurb after `write append on the configwsl` do you build and load a new kernel with those features enabled? It's not clear from your issue description if you did.

Most of the kernel options in network `queuing/scheduling` and `classification` are not set in the default WSL kernel.

**Comment by Perhurb** [comment]
> 

Sure. I have built and load the new kernel. But it does not work well. Do you have a recommended config?

**Comment by Perhurb** [comment]
@elsaco 
Sure. I have built and load the new kernel. But it does not work well. Do you have a recommended config?

**Comment by Wxn-625** [comment]
@elsaco 
Hello.I met the same problem.And I want to know what configuration can let me use the tc command ，if I use `make menuconfig`.

**Comment by elsaco** [comment]
@Wxn-625 the setting are in `Networking Support --> Networking options --> QoS and/or fair queuing`

It should look like, with network emulator selected:

![wsl_linux_kernel_qos](https://user-images.githubusercontent.com/3933920/216847965-84e3d7fa-42f1-4a12-a2ed-fdd5247bf57a.png)

**Comment by dudeisbrendan03** [comment]
> @elsaco Hello.I met the same problem.And I want to know what configuration can let me use the tc command ，if I use `make menuconfig`.

You'll have to compile the kernel yourself to access the menuconfig for kernel configuration

https://github.com/imunes/imunes/issues/111#issuecomment-1470004708

**Comment by shimachao** [comment]
> @Wxn-625 the setting are in `Networking Support --> Networking options --> QoS and/or fair queuing`
> 
> It should look like, with network emulator selected:
> 
> ![wsl_linux_kernel_qos](https://user-images.githubusercontent.com/3933920/216847965-84e3d7fa-42f1-4a12-a2ed-fdd5247bf57a.png)

I tried this method many times, but it didn't work
