### ISSUE TITLE
WSL command from windows not executed in appropriate folder in WSL file system

### ISSUE THREAD

**Issue by theotherp** [microsoft/WSL#8585]
### Version

Microsoft Windows [Version 10.0.19044.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

In windows execute `wsl.exe pwd`.

### Expected Behavior

pwd should print the mounted folder from which the command was excuted. For example running the command from `C:\temp` should print `/mnt/C/temp`.

### Actual Behavior

I get `/`, i.e. the wsl command is always executed in the root folder. I forward calls to docker via a custom docker.cmd file but that means that the commands are not executed in the current working directory.

**Comment by benhillis** [comment]
> I forward calls to docker via a custom docker.cmd file but that means that the commands are not executed in the current working directory.

Can you please clarify what you mean by this?

**Comment by theotherp** [comment]
1. Under Windows do `cd c:\` (or any other folder)
2. Run `wsl pwd`

You'd expect the output to be `/c/` but instead it's `/`. Until a few days ago the working directory WSL was mapped from the windows working directory from where the wsl command was executed.

As for the docker thing... I have a file `docker-compose.cmd` in my path:
```
@echo off
c:\windows\system32\wsl.exe -d Ubuntu-20.04 -- %*
`` 
That way any command made to this batch file is executed in WSL using the provided parameters. Running this script from `c:\temp` originally ran it in `/mnt/c/temp` but now it`s run in `/` and the docker-compose.yml which is in the folder where I ran the script is not found.

**Comment by elsaco** [comment]
@theotherp does it work outside `docker`? Using your script, it works when run in a `pwsh` session:

```
PS C:\Temp> cat .\wsl_bug.cmd
@echo off
c:\windows\system32\wsl.exe -d Ubuntu-20.04 -- %*
PS C:\Temp> .\wsl_bug.cmd pwd
/mnt/c/Temp
PS C:\Temp> pwd

Path
----
C:\Temp

PS C:\Temp>
```

Tested on Windows 10 and 

```
PS C:\Temp> wsl --status
Default Distribution: Jammy
Default Version: 2

Windows Subsystem for Linux was last updated on 3/26/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```
