### ISSUE TITLE
[WSL2] git is very slow even on the same filesystem

### ISSUE THREAD

**Issue by Ralender** [microsoft/WSL#8588]
### Version

Microsoft Windows [Version 10.0.19042.1288] 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.104

### Distro Version

Ubuntu 22.04

### Other Software

git version 2.36.0

### Repro Steps

open a WSL2 console.
go to a temporary directory on the linux filesystem not /mnt/c
```bash
> git clone https://github.com/torvalds/linux.git
```
running git clone on any large repository witin WSL2 is a lot slower then natively on linux

### Expected Behavior

on a native linux:
```bash
> time git clone https://github.com/torvalds/linux.git
Cloning into 'linux'...
remote: Enumerating objects: 8849316, done.
remote: Total 8849316 (delta 0), reused 0 (delta 0), pack-reused 8849316
Receiving objects: 100% (8849316/8849316), 3.63 GiB | 28.83 MiB/s, done.
Resolving deltas: 100% (7342108/7342108), done.
Updating files: 100% (76963/76963), done.

real    4m45.603s
user    15m0.480s
sys     1m26.538s
```

### Actual Behavior

I would expect WSL2 to have performances close to native (within 20%) not 11x slower.
on WSL2 with the same filesystem on the same network
```bash
> time git clone https://github.com/torvalds/linux.git
Cloning into 'linux'...
remote: Enumerating objects: 8849316, done.
Receiving objects: 100% (8849316/8849316), 3.63 GiB | 1.18 MiB/s, done.
remote: Total 8849316 (delta 0), reused 0 (delta 0), pack-reused 8849316
Resolving deltas: 100% (7342108/7342108), done.
Updating files: 100% (76963/76963), done.                                                                                                                                                                                                 

real    55m25.672s
user    14m45.398s
sys     5m50.113s
```
once again I am cloning into the linux filesystem of WSL.

**Comment by elsaco** [comment]
@Ralender this is the result on Win10 + WSL2 + Ubuntu 22.04 + git 2.34.1:

```
tux@RIPPER:~$ pwd
/home/tux
tux@RIPPER:~$ time git clone https://github.com/torvalds/linux.git
Cloning into 'linux'...
remote: Enumerating objects: 8849399, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 8849399 (delta 21), reused 18 (delta 15), pack-reused 8849361
Receiving objects: 100% (8849399/8849399), 3.63 GiB | 10.40 MiB/s, done.
Resolving deltas: 100% (7344879/7344879), done.
Updating files: 100% (76963/76963), done.

real    9m14.004s
user    6m38.311s
sys     0m34.823s

```
About 9 min for a new Linux kernel repo clone. The only major difference from your setup is the WSL kernel (version 5.10.201.1) and git.

This post is for comparison only!

**Comment by benhillis** [comment]
From the git output it looks like what's taking the most time is actually the network, not the filesystem.

**Comment by kytosai** [comment]
Today, i had the same problem, everything was really bad, i git clone my repo only 25kb/s compared to git clone on windows host 25mb/s

In WSL2 Ubuntu 22.04
![image](https://user-images.githubusercontent.com/1908652/214864327-d6fb23b2-ad98-4484-9f99-316a9e02bc08.png)

In host Windows 11 22H2
![image](https://user-images.githubusercontent.com/1908652/214864515-69ef353b-69bf-4a3b-a0a0-e4c4f0bc0cfb.png)

**Comment by AndersHogqvist** [comment]
I have a similar issue here but for me it's only when I work with repositories on Azure Devops. Cloning and pushing/pulling from github is as fast as it gets, but doing the same with a Azure repo a git fetch takes several minutes.
