### ISSUE TITLE
WSL2 (Ubuntu-20.04) always crashes after a faulty command

### ISSUE THREAD

**Issue by Riffecs** [microsoft/WSL#8589]
### Version

Windows Version: 10.0.22621.160

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernelversion: 5.10.102.1

### Distro Version

Ubuntu-20.04

### Other Software

Microsoft Terminal  @ [https://github.com/microsoft/terminal](https://github.com/microsoft/terminal)

### Repro Steps

I start a terminal. I then start the WSL in it. 
I enter my commands there. To generate the error, I enter an invalid command. 

```shell
git error
````

### Expected Behavior

The WSL should tell me that the command is faulty and show me a new prompt.

### Actual Behavior

<img width="443" alt="image" src="https://user-images.githubusercontent.com/102326693/178065199-39b3a4e5-5f14-4ddd-b28a-6ada8bdec79c.png">

Every time I enter an incorrect command or syntax, the entire WSL crashes. I can restart it, but that is not the point.

**Comment by Riffecs** [comment]
Basically, my concern is simply that the WSL crashes within itself every time. I have not changed anything in the settings. I have absolutely no idea why this happens. 
I'll put all the versions in for you. If you have any further questions, please ask.

```
Windows Version: 10.0.22621.160
Standard-Distribution: Ubuntu-20.04
Standardversion: 2
WSL-Version: 0.61.8.0
Kernelversion: 5.10.102.1
WSLg-Version: 1.0.39
MSRDC-Version: 1.2.3213
Direct3D-Version: 1.601.0
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
```

**Comment by Riffecs** [comment]
The problem seemed to be with my zshrc. I recreated it and now it seems to work.

**Comment by AceHack** [comment]
Yeah I had the same problem, I was sourcing a set -e somewhere
