### ISSUE TITLE
Accidentally deleted wsl.exe

### ISSUE THREAD

**Issue by MaelAbgrall** [microsoft/WSL#8591]
Hello,
I was part of the first people to use wsl (before it was embeded in windows) and I wanted to have a clean install, so I could use wsl2.
However, by mistake, I deleted the wsl.exe located in C:\Windows\System32

Is there any way to get this exe back? I haven't seen anything to help so far, and obviously I cannot use any of the wsl command anymore.
if this can help, I'm running windows [Version 10.0.19044.1806]

**Comment by Biswa96** [comment]
wsl.exe can be found in C:\Windows\WinSxS folder.

**Comment by MaelAbgrall** [comment]
Thank you!

**Comment by Shisheer** [comment]
@MaelAbgrall, hello. Can you tell me how you deleted wsl.exe? My wsl.exe is in the system32 even several feature install/ uninstall. WSL is corrupted. It hangs after re-installing. help

**Comment by MaelAbgrall** [comment]
It's been years, I have no idea sorry; I don't use windows anymore
