### ISSUE TITLE
Command not found: clip.exe whenever I press CTRL+ C to cancel the execution of a process

### ISSUE THREAD

**Issue by Scarwolf** [microsoft/WSL#8595]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Open WSL, press CTRL + C to discard what you've typed on that line or to halt the execution of a running daemon.

![image](https://user-images.githubusercontent.com/8727623/178352752-5dd1f37f-5376-46d0-897a-86dae545ce44.png)

### Expected Behavior

The daemon's execution should be stopped without any error message.

### Actual Behavior

The daemon/process is stopped, but the error message `r-copy-to-xclip:2: command not found: clip.exe` is shown and apparently spawns another process which you can't leave using CTRL + C either. You have to press Enter for example to be able to type anything again.

**Comment by owenschupp** [comment]
@Scarwolf could you post a more detailed example of how you encountered this issue? It's a little difficult to tell what's happening from the terminal snippet you posted? Thanks!

**Comment by Scarwolf** [comment]
> @Scarwolf could you post a more detailed example of how you encountered this issue? It's a little difficult to tell what's happening from the terminal snippet you posted? Thanks!

![WindowsTerminal_WEhDjWVxPk](https://user-images.githubusercontent.com/8727623/178611310-07202f98-c4b9-4d14-a55d-62ce0c44f18f.gif)
I hope this GIF clarifies a bit. It always happens whenever I press CTRL + C which I've used for years to exit all kinds of programs.

**Comment by snth** [comment]
I'm experiencing the same problem.
