### ISSUE TITLE
OpenGL acceleration does not work for Intel UHD 630 + Arch linux combination

### ISSUE THREAD

**Issue by anup-das** [microsoft/WSL#8596]
### Version

Microsoft Windows [Version 10.0.22000.778]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Arch

### Other Software

WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.778

[root@DEV-PC anupb]# ls -l /dev/dxg
crw-rw-rw- 1 root root 10, 63 Jul 12 04:14 /dev/dxg

[root@DEV-PC anupb]# ls -la /usr/lib/dri/d3d12_dri.so
-rwxr-xr-x 12 root root 25395504 Jul  3 15:37 /usr/lib/dri/d3d12_dri.so

[root@DEV-PC anupb]# glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 14.0.6, 256 bits) (0xffffffff)
    Version: 22.1.3
    Accelerated: no
    Video memory: 7867MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 14.0.6, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.1.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.1.3
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

On the same system Ubuntu 22.04 works fine.  How should i fix the issue ? I am using unmodified default Mesa 22.1.3 in arch and this should work by default but it doesn't. :-(

### Repro Steps

Install Arch in WSL by following the steps mentioned at
https://github.com/nckslvrmn/arch_linux_wsl2

### Expected Behavior

Accelerated OpenGL should work in any distribution under WSL as long as latest version of MESA is used.

### Actual Behavior

Mesa 22.1.3 under Arch linux is using software rendering (llvmpipe)

**Comment by anup-das** [comment]
DxDiag report on my syste
[DxDiag.txt](https://github.com/microsoft/WSL/files/9088020/DxDiag.txt)
m

**Comment by elsaco** [comment]
@anup-das what driver are you using?

This is with `nvidia-512.96`. The only package added to Arch was `mesa-utils` to get `glxinfo`:

```
[tux@eleven ~]$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA GeForce RTX 3060 Ti) (0xffffffff)
    Version: 22.1.3
    Accelerated: yes
    Video memory: 24348MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 4.2
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 3060 Ti)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 22.1.3
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.2 (Compatibility Profile) Mesa 22.1.3
OpenGL shading language version string: 4.20
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

Segmentation fault
```

Notice the `segfault` at the end. This is an ongoing issue, reported many times.

ArchLinux info:

```
[tux@eleven ~]$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
IMAGE_ID=archlinux
IMAGE_VERSION=2022.07.01

```

and WSL2 info:

```
PS C:\> wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.778

```

**Comment by anup-das** [comment]
@elsaco Thanks. The issue of not having h/w accel seems to be with Intel UHD 630 + arch combination only.  Ubuntu 22.04 LTS works just fine. 

I have 2 identical systems one with NVIDIA Graphics and other with Intel Graphics. The one with NVIDIA works fine with both ubuntu and arch.  For arch, at the end i get a segfault (as you correctly indicated).

**Comment by Ultra-Code** [comment]
@anup-das is opengl acceleration working for you now :thinking:   if so, how did you solve it.

**Comment by carschandler** [comment]
Looking for a resolution here as well... working fine on Ubuntu but failing on Arch

**Comment by Ultra-Code** [comment]
The following helped me to resolve my OpenGL issue

```conf
# Put in ~/.config/user-tmpfiles.d/wayland.conf
# Then systemctl --user enable --now systemd-tmpfiles-setup.service systemd-tmpfiles-clean.timer
# https://github.com/microsoft/wslg/issues/1032#issuecomment-2458021984
# https://github.com/yuk7/ArchWSL/issues/357#issuecomment-2062677233
# Type Path  Mode User Group Age Argument
L+ %t/wayland-0  - - - - /mnt/wslg/runtime-dir/wayland-0
L+ %t/wayland-0.lock - - - - /mnt/wslg/runtime-dir/wayland-0.lock
L+ %t/pulse - - - - /mnt/wslg/runtime-dir/pulse
```

```conf
# Put in /etc/tmpfiles.d/x11.conf
# https://github.com/microsoft/WSL/issues/6999#issuecomment-2303010704
# Type Path  Mode User Group Age Argument
L+ /tmp/.X11-unix - - - - /mnt/wslg/.X11-unix
```

https://github.com/microsoft/wslg/issues/1032#issuecomment-2458021984
https://github.com/yuk7/ArchWSL/issues/357#issuecomment-2062677233
https://github.com/microsoft/WSL/issues/6999#issuecomment-2303010704
