### ISSUE TITLE
I can't update wsl if Windows Store is disabled

### ISSUE THREAD

**Issue by lucianoctorres** [microsoft/WSL#8603]
### Version

Microsoft Windows [Version 10.0.19042.1766]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

Run wsl --update on a PC with Windows Store disabled (per company guidelines)

### Expected Behavior

WSL updates itself

### Actual Behavior

PS C:\WINDOWS\system32> wsl --update
Checking for updates...
Error: 0x8024500c

**Comment by ferrerogg** [comment]
Same problem here, using Win11, no Windows Store app

```
PS C:\WINDOWS\system32> wsl --update
Ricerca aggiornamenti in corso...
Errore: 0x8024500c
```


Using 'get-windowsupdatelog' command, I found the following log

```
2022/08/19 11:54:17.0184320 18172 19368 ComApi          * START *   Federated Search ClientId = WSL (cV: GfO4nsL+d0+KkqPe.1.0)
2022/08/19 11:54:17.0192200 4752  3808  IdleTimer       WU operation (SR.WSL ID 21) started; operation # 185; does use network; is not at background priority
2022/08/19 11:54:17.0192223 4752  3808  IdleTimer       Activate PDC state for Network
2022/08/19 11:54:17.0193150 4752  3808  IdleTimer       Incremented PDC RefCount for Network to 1
2022/08/19 11:54:17.0193790 4752  18260 Agent           Processing auto/pending service registrations and recovery.
2022/08/19 11:54:17.0195511 4752  18260 Agent           *FAILED* [8024500C] file = onecore\enduser\windowsupdate\client\lib\endpointproviders\endpointproviders.cpp, line = 1878
```

**Comment by Biswa96** [comment]
What component of WSL do you want to update?

**Comment by ferrerogg** [comment]
I want to update kernel, Windows Update is on and I've checked that also "give me updates for other Microsoft products" is on.

Current kernel version is

```
PS C:\WINDOWS\system32> wsl --status
Distribuzione predefinita: Ubuntu-20.04
Versione predefinita: 2

Il sottosistema Windows per Linux è stato aggiornato l'ultima volta il 31/05/2022
Aggiornamenti automatici di WSL abilitati.

Versione del kernel: 5.10.102.1
```

As far as I can see, there should be a newer kernel v5.15.57.1 listed here
https://github.com/microsoft/WSL2-Linux-Kernel/releases

but cannot upgrade to it using wsl --update command, and checking for Windows Updates does not found any upgrades.

Are there any other ways to manually install wsl kernel?

**Comment by Biswa96** [comment]
The Linux kernel version used in WSL2 does not always match the latest release tag. The latest version in Windows update pipeline is indeed 5.10.102.1. See this link https://www.catalog.update.microsoft.com/Search.aspx?q=wsl.

The WSL preview has Linux kernel version 5.1.5.57.1. It can be downloaded from here https://github.com/microsoft/WSL/releases

**Comment by ferrerogg** [comment]
Thanks for the explanation :)
So, why do wsl --update returns 0x8024500c instead of quitting without errors?

**Comment by Biswa96** [comment]
It is not possible to clearly answer that because Windows is not a open-source software. But from the error message, it seems that the error does _not_ come from any WSL component.

**Comment by ghusta** [comment]
I have the same error. No Windows Store, on a corporate computer with Windows 10 Pro, version 20H2.

Trying to update, in french :

```
>wsl --update
Recherche de mises à jour en cours... Veuillez patienter
Erreur : 0x8024500c
```

And checking status : 

```
>wsl --status
Version par défaut : 2

La dernière mise à jour effectuée du Sous-système Windows pour Linux date du 28/01/2021
Les mises à jour WSL automatiques sont activées.

Le fichier noyau WSL 2 est introuvable. Pour mettre à jour ou restaurer le noyau, veuillez exécuter 'wsl.exe --update'.
```

I'll have a look at : 
- https://github.com/microsoft/WSL/issues/5650
- https://github.com/microsoft/WSL/issues/5642
- https://github.com/microsoft/WSL/issues/5014

**Comment by ghusta** [comment]
Well, I tried to follow this link to update my WSL kernel : https://aka.ms/wsl2kernel .

Then I DL https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi and installed it.

Status command now displays : 

```
>wsl --status
Distribution par défaut : Ubuntu
Version par défaut : 2

La dernière mise à jour effectuée du Sous-système Windows pour Linux date du 26/09/2022
Les mises à jour WSL automatiques sont activées.

Version du noyau : 5.10.16
```

The good news is I am now able to install a distribution, like with : 

```
>wsl --install -d Ubuntu
```

**Comment by mluckam** [comment]
Have you tried using the option --web-download?  
`
wsl --update --web-download
`

From wsl --help
```
--update
        Update the Windows Subsystem for Linux package.

        Options:
            --web-download
                Download the update from the internet instead of the Microsoft Store.
```

**Comment by samba2** [comment]
> Have you tried using the option --web-download? `wsl --update --web-download`
> 
> From wsl --help
> 
> ```
> --update
>         Update the Windows Subsystem for Linux package.
> 
>         Options:
>             --web-download
>                 Download the update from the internet instead of the Microsoft Store.
> ```

Got the mentioned error. I assume this is due to a not-updated policy restriction (WSL2 is ok to use). 
Used `--web-download` in an admin shell and update just worked flawlessly. @mluckam Tnx for pointing that out! 👍🏼

**Comment by ndan2801** [comment]
Thanks @samba2 who put me on the path.
If you face that error just run:

wsl --install --web-download -d <distrib>

**Comment by OneBlue** [comment]
If the store is disabled, wsl.exe --update --web-download is indeed the way to go.
