### ISSUE TITLE
all changes lost in WSL after HOST win10 system shutdown

### ISSUE THREAD

**Issue by xcf007** [microsoft/WSL#8605]
### Version

win10

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04

### Repro Steps

ip netns add ns1
ip netns add ns2
 ip link add veth2 type veth peer name veth3
 ip link add veth0 type veth peer name veth1
...
... ...

after shutdown ,all veth device LOST.

### Expected Behavior

persised changes

### Actual Behavior

all changes LOST

**Comment by benhillis** [comment]
This is by design. The WSL2 is created from scratch each time WSL is launched, these types of changes are not persisted.
