### ISSUE TITLE
My WSL can't show the desktop environment after my laptop reboot

### ISSUE THREAD

**Issue by cyberduck465** [microsoft/WSL#8608]
### Version

Microsoft Windows [Version 10.0.19044.1806]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.102.1

### Distro Version

Ubuntu (All Versions) / Debian

### Repro Steps

Before Reboot: xfce / lxde are running normally (IP address is 172.16.224.1)

After Reboot: Due to the IP address changed, the X Server connections are refused

### Expected Behavior

The X server launched, and the desktop showed

### Actual Behavior

administrator@LAPTOP-U440BO2:~$ startlxde
** Message: 00:59:49.244: main.vala:102: Session is LXDE
** Message: 00:59:49.245: main.vala:103: DE is LXDE

(lxsession:15530): Gtk-WARNING **: 00:59:49.246: cannot open display: 192.168.128.1:0.0

/usr/bin/startxfce4: X server already running on display 192.168.128.1:0.0
xrdb: Connection refused
xrdb: Can't open display '192.168.128.1:0.0'
Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.

**Comment by cyberduck465** [comment]
All of the Ubuntu and Debian are updated and upgraded

**Comment by MateuszDuda-allegro** [comment]
Can you provide a resolution? I am having a similar issue right now.
