### ISSUE TITLE
Can't start Ubuntu normally

### ISSUE THREAD

**Issue by QinGuodong1287** [microsoft/WSL#8616]
### Version

Microsoft Windows [版本 10.0.25151.1010]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

Start WSL with Windows Terminal, like this.
![image](https://user-images.githubusercontent.com/60057724/179232906-cab2b3fe-c61b-420d-a268-95b9ded47ca0.png)

### Expected Behavior

It prints error, like this.
![image](https://user-images.githubusercontent.com/60057724/179232743-3aca3f12-d8bd-4a89-8805-09b5f1ee6e67.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/60057724/179232770-09f14a27-c270-4047-aef8-43d78b8a1492.png)

**Comment by ashemedai** [comment]
The error 0x8007041d indicates that a Windows service could not be started. Check your event viewer to see which service failed.

Alternatively, another Chinese user in #3203 had a similar error due to language settings, it seems. You might want to check that.

**Comment by QinGuodong1287** [comment]
Now this question has been solved, thanks for your help!
