### ISSUE TITLE
Git does not detect changes

### ISSUE THREAD

**Issue by twobiers** [microsoft/WSL#8622]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

git version 2.25.1

### Repro Steps

```
cd /tmp
mkdir test-repo
cd test-repo
git init
echo "a" >> README.md
git add .
git commit -m "initialize repo"
echo "a" >> README.md
git status
```

### Expected Behavior

git should detect the change done in `README.md`

### Actual Behavior

Git does not detect the change. the `git status` command gives the following output:
```
On branch master
nothing to commit, working tree clean
```
To make git see the change I have to manually update index:
```
git update-index --no-assume-unchanged README.md
```

**Comment by twobiers** [comment]
I have overcome the issue by installing Ubuntu 22.04 LTS, where I can't reproduce it. However, i have left my 20.04 instance unchanged where the issue still exists in case you need more information.

**Comment by willeccles** [comment]
Does this happen outside of `/tmp`?

**Comment by twobiers** [comment]
Yes, I originally had this issue in my home directory and can still reproduce it there.

**Comment by willeccles** [comment]
Interesting. I can't reproduce this using 5.10.102.1 on Debian, Ubuntu 20.04, Ubuntu 18.04, or Void, using git versions 2.36.1, 2.25.1, 2.17.1, and 2.37.1, respectively.

**Comment by twobiers** [comment]
I expected this answer... Can I do anything to help you reproducing or to exclude WSL as a factor?

**Comment by willeccles** [comment]
Not sure. Can you confirm you do not have any git configurations anywhere? E.g. ~/.gitconfig, etc.? I can't recall all the potential locations for configs (if there are more at all), but `man git-config` I believe should be enlightening.

**Comment by twobiers** [comment]
You got me. It seems to be the `core.fsmonitor` option which was set to true. Disabling it solves the issue for me.

**Comment by jrj2211** [comment]
THANK YOU!!!!!! 

For weeks I've been running into git randomly stopping tracking changes (but new files did show up as a change). I finally googled the right thing to get me here and `core.fsmonitor` seems to have done the trick for me as well.

**Comment by jrj2211** [comment]
After months of this not being an issue, the issue began again within the last week. I double checked the core.fsmonitor is still false, so seems like theres a new issue causing this.
