### ISSUE TITLE
Problem making / in my Debian shared

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#8623]
### Version

Microsoft Windows [Version 10.0.22622.290]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian 11

### Repro Steps

wsl.exe -u root -e mount --make-rshared /

findmnt -o PROPAGATION /
PROPAGATION
private

### Expected Behavior

Should make propagation for / shared

### Actual Behavior

I get:

<3>init: (8) ERROR: CreateProcessParseCommon:746: Failed to translate \\wsl.localhost\Debian\home\mwoodpatrick

I see the same error when first starting the distro

### Diagnostic Logs

dmesg shows

[   19.949205] Exception:
[   19.949209] Operation canceled @p9io.cpp:258 (AcceptAsync)

[   26.686030] init: (1) ERROR: ConfigApplyWindowsLibPath:2485: open /etc/ld.so.conf.d/ld.wsl.conf
[   26.686034]  failed 2
[   26.732754] init: (1) WARNING: /usr/share/zoneinfo/America/Los_Angeles not found. Is the tzdata package installed?

**Comment by elsaco** [comment]
The `--make-rshared` is for `recursively mark a whole subtree as shared`. I'm not sure it applies to the top of the tree, `/`.

**Comment by owenschupp** [comment]
@mwoodpatrick it appears that this issue is more central to your WSL install, could you provide /logs?
