### ISSUE TITLE
update the list on wsl --list --online

### ISSUE THREAD

**Issue by forkicks** [microsoft/WSL#8634]
What is the process to have a distribution listed under wsl --list --online? There are others that can be deployed through the app store, but are not listed there and that is a more efficient/practical/faster/better to automate way to deploy them.

I'm particularly interested in AlmaLinux showing there.

**Describe the solution you'd like**
I would like to see more available distributions under wsl --list --online.

**Describe alternatives you've considered**
Deploying through the app store (the store may not be available) or manual deployment is more error prone (more steps involved).

**Comment by benhillis** [comment]
Submit a PR!

https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json

**Comment by benhillis** [comment]
If the distro partner wants to be included on our storage server, they should reach out and provide an appx.
