### ISSUE TITLE
WSLENV only gets populated if it exists in Windows in all caps

### ISSUE THREAD

**Issue by ashemedai** [microsoft/WSL#8639]
### Version

10.0.19043.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Open a command or PowerShell prompt
2. `setx wslenv whatever`
3. Start Windows Terminal
4. Open a WSL environment
5. `env | grep WSL`

### Expected Behavior

`WSLENV=whatever`

### Actual Behavior

`WSLENV=`

**Comment by elsaco** [comment]
_Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters..._   by convention on Linux environment variables are capitalized. `WSLENV` being shared between Windows and Linux might be the reason why using lowercase  won't work.

**Comment by ashemedai** [comment]
@elsaco Which is fair from the side of POSIX. But given that Windows does not enforce that for environment variables on its side, this will lead to confusion. I could envision WSL to look at the envvars on Windows and uppercasing them prior to passing them along to WSL to avoid these issues. It otherwise enforces Linux semantics on Windows aspects, which seems to defy the principle of least astonishment to me.
