### ISSUE TITLE
Get-Service : Cannot find any service with service name 'LxssManager'.

### ISSUE THREAD

**Issue by arnon001** [microsoft/WSL#8644]
### Version

Microsoft Windows [Version 10.0.22622.436]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I can't use git so i used this 2 guides:
https://stackoverflow.com/questions/55649015/could-not-resolve-host-github-com-only-in-windows-bash
and 
https://superuser.com/questions/1725594/windows-lxssmanager-is-missing-from-services-msc
and still i can't use LxssManager

### Expected Behavior

I expect the LxssManager to work, i dont have 

### Actual Behavior

```powershell
Get-Service : Cannot find any service with service name 'LxssManager'.
At line:1 char:1
+ Get-Service LxssManager | Restart-Service
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LxssManager:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
```

**Comment by owenschupp** [comment]
@arnon001 if you have WSL from the Windows Store, try `Get-Service WslService` instead. That might be what you're looking for

**Comment by arnon001** [comment]
> @arnon001 if you have WSL from the Windows Store, try `Get-Service WslService` instead. That might be what you're looking for

I did it,
I getting this:
![image](https://user-images.githubusercontent.com/58848496/180992269-64aa70e1-69f7-4560-a9bb-e6ffa2a7df2f.png)

**Comment by mavaddat** [comment]
> > @arnon001 if you have WSL from the Windows Store, try `Get-Service WslService` instead. That might be what you're looking for
> 
> I did it, I getting this: ![image](https://user-images.githubusercontent.com/58848496/180992269-64aa70e1-69f7-4560-a9bb-e6ffa2a7df2f.png)

Why would you expect an interface called `LxssManager`?

Recall:

1. The [earlier comment](https://github.com/microsoft/WSL/issues/8644#issuecomment-1194772945) which you yourself quoted explicitly stated that the service is called `WslService`, not `LxssManager`. It's like someone tells you their name is _Wassle_ and you continue to call them _Lix_.   
_Why aren't you answering me, Lix?_  
_Um, that's not my name._
2. You cannot invoke[ system services](https://learn.microsoft.com/en-us/windows/win32/services/interactive-services) by using their names. This is not [how to interact with services on Windows](https://learn.microsoft.com/en-us/windows/win32/services/interactive-services). They are not executables.
