### ISSUE TITLE
No Arch Linux compatible distribution available on Microsoft store.

### ISSUE THREAD

**Issue by kevincrans** [microsoft/WSL#8646]
**Is your feature request related to a problem? Please describe.**
The problem is, I'm always frustrated when dev-tools require my favourite pacman package manager, while MS-store has no solution.
**Describe the solution you'd like**
I want you to either co-operate with either Steam-OS/Manjaro LX/Arch LX to make a version on the MS-store happen.
**Describe alternatives you've considered**
Alternative solutions I considered is installing Arch-WSL, someone made custom, but it installed in my downloads folder, I deleted it and it's cancelled because of a bug (likely lack of SystemD)
**Additional context**
It's SystemD, so once you finally do that correctly, you can install the same Snap software as on Ubuntu.

**Comment by NickDeBeenAIE** [comment]
No WSL Linux distro uses systemd bud. Its not booting from a drive, nor is it booting from the UEFI or BIOS of your board or device.

**Comment by kevincrans** [comment]
True, but Canonical was doing something about it (don't know if it's already available).
It's not about what's behind the scene, it's about native compatibility,
