### ISSUE TITLE
WSL2 installation does not complete when installing Ubuntu 22.04

### ISSUE THREAD

**Issue by roalvesrj** [microsoft/WSL#8647]
### Version

Microsoft Windows [versão 10.0.22622.436]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Open Microsoft Store;
2. Install Ubuntu 22.04 LTS;
3. Open start menu and run Ubuntu 22.04 LTS;
4. The configuration screen will open;
5. When selecting the language, you will be taken to the screen to configure the profile;
6. When filling in the data and clicking on "continue", the screen is stuck and nothing happens.

### Expected Behavior

I was waiting for the configuration to complete or an error to be presented.

### Actual Behavior

When filling in the data and clicking on "continue", the screen is stuck and nothing happens.

**Comment by Biswa96** [comment]
Did you try installing or using another distribution in WSL2? If the issue is only in ubuntu 22.04 this repository may help https://github.com/ubuntu/WSL. It has some similar issues.

**Comment by elsaco** [comment]
@roalvesrj if you run from shell prompt `ubuntu2204.exe config` and make changes does it `save` or gets stuck also? Thx!

**Comment by roalvesrj** [comment]
> Did you try installing or using another distribution in WSL2? If the issue is only in ubuntu 22.04 this repository may help https://github.com/ubuntu/WSL. It has some similar issues.

Yes, I tried @Biswa96. Other distributions work just fine. The issue only occurs in Ubuntu 22.04. I'll look for something similar in the repository, thanks!

**Comment by roalvesrj** [comment]
@elsaco it also gets stuck and displays the following message at the prompt:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: setIdentity({"realname":"Rômulo Alves","username":"roalvesrj","crypted_password":"*********","hostname":""}) returned error 500
500 Internal Server Error`

**Comment by wmakley** [comment]
Having this issue with Intel integrated graphics.

**Comment by Biswa96** [comment]
That seems to be related with Ubuntu installer. Please report the issue in ubuntu/WSL repository also.
