### ISSUE TITLE
WSL2 and Windows 11 Home (WslRegisterDistribution failed with error: 0x80370102)

### ISSUE THREAD

**Issue by iFlxy** [microsoft/WSL#8649]
### Version

Microsoft Windows [Version 10.0.22000.739]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04.4 LTS

### Repro Steps

1. Get Ubuntu 20.04.4 LTS from the Microsoft Store
2. Follow the Installation tips described on the Microsoft Store page
![image](https://user-images.githubusercontent.com/102528232/180669921-57108d6c-6a8d-4a32-8a23-15b414c25ad0.png)
3. Try to install the distro

### Expected Behavior

I am able to install Ubuntu without any issues.

### Actual Behavior

When trying to install the distro, I get this error:

![image](https://user-images.githubusercontent.com/102528232/180670242-1e1e9810-9070-4fe1-82e4-c39ef8854bbe.png)
`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...`

Virtual Machine Platform is enabled, just like virtualization in my BIOS.

**Comment by Biswa96** [comment]
Run this command in command prompt as administrator `bcdedit | find /i "hypervisor"`. Does it return `hypervisorlaunchtype Auto` string?

**Comment by iFlxy** [comment]
> Run this command in command prompt as administrator `bcdedit | find /i "hypervisor"`. Does it return `hypervisorlaunchtype Auto` string?

Yes, I just had to restart my PC. If anyone has the same issue, run "bcdedit /set hypervisorlaunchtype auto" in the command prompt as administrator and restart your computer. Thanks for your help.

**Comment by jkupchanko** [comment]
@iFlxy I don't get why it still hasn't worked for me - I tried everything.

check out my issue: https://github.com/microsoft/WSL/issues/11674
