### ISSUE TITLE
WLS starts in terminal instead of starting the Linux Distro in it's own GUI Window

### ISSUE THREAD

**Issue by Chaoschaot232** [microsoft/WSL#8652]
### Version

Microsoft Windows [Version 10.0.22622.436]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Debian 11

### Other Software

Debian App from Microsoft Store

### Repro Steps

Enable WSL
Install Debian over the Microsoft Store and start it from there or from your Start Menu

### Expected Behavior

That Debian App's OWN GUI/Console opens but not in the shitty windows terminal style or started from the PS terminal

### Actual Behavior

My Debian is startet unallowed and unwanted within the Terminal or PS from Windows and without auto-completion (TAB-Key) but looking at the Microsoft Store Debian App has it's OWN GUI where you can setup the used font and a few more settings.

I am unsure why this is happen but it shouldn't happen.

### Diagnostic Logs

N/A

**Comment by owenschupp** [comment]
@Chaoschaot232 would you mind posting a screenshot of what you mean? I'm not exactly sure what you mean by the description

**Comment by jasondraether** [comment]
Not author, but a similar issue has been happening for me on Ubuntu. Typing `wsl.exe` in an admin powershell doesn't launch a separate terminal window. I can still manually launch Ubuntu by just searching for the `ubuntu` command, but launching from powershell doesn't appear to work. For the image below, the second line is what pops up after typing `wsl.exe`. From there I can type commands like `ls`, but it appears to be starting in the `/mnt/host/c/Windows/system32` directory.

![image](https://user-images.githubusercontent.com/20545022/181587424-c04eea43-9675-40e9-9b88-6b32ebb40a2a.png)

**Comment by NickDeBeenAIE** [comment]
This is weird, have either of you checked your WSL versions? ``wsl -l -v``

**Comment by jasondraether** [comment]
Here is the result of running `wsl -l -v`

<img width="277" alt="image" src="https://user-images.githubusercontent.com/20545022/182242331-5b415157-527d-4b84-a342-17de055293b9.png">

Recently upgraded to Windows 11, but the same thing happened on Windows 10.

**Comment by NickDeBeenAIE** [comment]
> Here is the result of running `wsl -l -v`
> 
> <img alt="image" width="277" src="https://user-images.githubusercontent.com/20545022/182242331-5b415157-527d-4b84-a342-17de055293b9.png">
> 
> Recently upgraded to Windows 11, but the same thing happened on Windows 10.

News flash:

Please downgrade to Windows 10 to preserve the stability of your system.

Windows 11 is way too unstable as it likes to corrupt itself on purpose when you install a GPU driver, or Chipset driver.

I should know as this has happened to me.

Microsoft likes to keep Windows 11 in an unstable state.

**Comment by NickDeBeenAIE** [comment]
And also, your WSL service is stopped so no wonder.

``wsl.exe --start``

If this doesn't work, let me know.

**Comment by slycordinator** [comment]
The issue seems to be that when you run a distro from the start menu, it may or may not open in a modern terminal.

I have Windows Terminal installed and it's set as my default terminal. As well, I have Debian installed from the Store.

When I run "Debian" from the start menu, it opens in Windows Terminal.
When pick "Debian" in the start menu and select "Run As Administrator", it opens in a DOS-style CMD window.

**Comment by A-s-a-d** [comment]
I have the same problem.

When launch i launch Ubuntu from start menu it opens in windows terminal. 
 ![Image](https://github.com/user-attachments/assets/9f8fc5e4-0bca-4097-84c7-995f33ef92e1)

When i open new Ubuntu terminal from inside the terminal it opens "Ubuntu style" terminal.
![Image](https://github.com/user-attachments/assets/ef561135-1b04-47aa-8068-b55d263c270f)
![Image](https://github.com/user-attachments/assets/47577333-d154-482d-bc1d-c740763078fe)

and as @slycordinator said from start menu i do "Run As Administrator" it opens this terminal.
![Image](https://github.com/user-attachments/assets/6ee62d18-5fc5-46b1-9bed-57b85dc28867)

and if i launch it fro powershell suing "wsl -d Ubuntu" it launches inside powershell.

It's very annoying that it's different depending on where you launch it from. 
![Image](https://github.com/user-attachments/assets/c149ef2a-a80e-4b5c-a235-ef647a47326c)

**Comment by hashguide** [comment]
If anybody has this issue where launching WSL through taskbar/start-menu icon and it launches in Windows console style instead of your WSL version, do the following to reset. 

1. Open any terminal. Command Prompt, PS, or WSL.
2. Right-click on title bar and go to settings.
3. Change **Startup -> Default Profile** to your WSL version.
4. Click Save.
