### ISSUE TITLE
Cannot mount exfat disks

### ISSUE THREAD

**Issue by neilgd** [microsoft/WSL#8653]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Set up a completely new install, and install Ubuntu 22.04 from the app store.

Try to mount an exfat drive

### Expected Behavior

The drive should mount

### Actual Behavior

I get the following error:

`mount: /media/test: unknown filesystem type 'exfat'.`

Also, output of cat /proc/filesystems doesn't include exfat

**Comment by owenschupp** [comment]
@neilgd how are you going about mounting your disk? If you use `wsl --mount` it should detect the fs type automatically. I also believe `exfat` is mapped to `vfat` in `/proc/fileystems` so I'd try that as well. Let me know if that fixes your issue. Thanks!

**Comment by 0xbadfca11** [comment]
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/Microsoft/config-wsl#L2941

**Comment by andwan0** [comment]
This is still an issue. how to reopen this issue?

**Comment by DoctorWho8** [comment]
> This is still an issue. how to reopen this issue?

I believe there are steps to reopen it, but I am not familiar with how GitHub works. Or you can create an entirely new one based on your own experiences.
