### ISSUE TITLE
Run Swift from Ubuntu Subsystem not response or hang (?)

### ISSUE THREAD

**Issue by ryudith** [microsoft/WSL#8656]
### Version

Microsoft Windows [Version 10.0.19044.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

20.04

### Other Software

Swift 5.6.2 for ubuntu 20.04

### Repro Steps

run command :
```
sudo apt-get install \
          binutils \
          git \
          gnupg2 \
          libc6-dev \
          libcurl4 \
          libedit2 \
          libgcc-9-dev \
          libpython2.7 \
          libsqlite3-0 \
          libstdc++-9-dev \
          libxml2 \
          libz3-dev \
          pkg-config \
          tzdata \
          uuid-dev \
          zlib1g-dev
```

change dir `cd /mnt/h/program_files/swift_lang/5.6.2`

then download by run `wget https://download.swift.org/swift-5.6.2-release/ubuntu2004/swift-5.6.2-RELEASE/swift-5.6.2-RELEASE-ubuntu20.04.tar.gz`

extract with `tar xzf swift-5.6.2-RELEASE-ubuntu20.04.tar.gz`

move `mv ./swift-5.6.2-RELEASE-ubuntu20.04/* ./`

add PATH to file .bashrc -> `export PATH="/mnt/h/program_files/swift_lang/5.6.2/usr/bin:$PATH"`
refresh bash `source /home/username/.bashrc`
run `swift`

### Expected Behavior

swift repl command line, something like:
```
Welcome to compnerd.org Swift version 5.6.2 (swift-5.6.2-RELEASE).
Type :help for assistance.
1> 
```
(I get that from Swift repl for windows, not subsystem)

### Actual Behavior

```
Swift version 5.6.2 (swift-5.6.2-RELEASE)
Target: x86_64-unknown-linux-gnu

Welcome to Swift!

Subcommands:

  swift build      Build Swift packages
  swift package    Create and work on packages
  swift run        Run a program from a package
  swift test       Run package tests
  swift repl       Experiment with Swift code interactively (default)

  Use `swift --help` for descriptions of available options and flags.

  Use `swift help <subcommand>` for more information about a subcommand.

```
not show repl command line, I don't know what is wrong, run "swift --version" is work.

**Comment by OneBlue** [comment]
This looks like a Swift REPL issue, not a WSL issue.

I recommend raising it on the [Swift Github](https://github.com/apple/swift/issues)  instead

**Comment by ryudith** [comment]
> This looks like a Swift REPL issue, not a WSL issue.
> 
> I recommend raising it on the [Swift Github](https://github.com/apple/swift/issues) instead

Thanks for reply and show me the way to go.
