### ISSUE TITLE
LxssManager Not Found

### ISSUE THREAD

**Issue by arnon001** [microsoft/WSL#8658]
@arnon001 if you have WSL from the Windows Store, try `Get-Service WslService` instead. That might be what you're looking for

_Originally posted by @owenschupp in https://github.com/microsoft/WSL/issues/8644#issuecomment-1194772945_

I did it,
I getting this:
![image](https://user-images.githubusercontent.com/58848496/180992269-64aa70e1-69f7-4560-a9bb-e6ffa2a7df2f.png)

**Comment by elsaco** [comment]
I'm on Windows 10 and `lxssmanager` service is available:

```
PS C:\Users\elsaco> get-service -name lxssmanager

Status   Name               DisplayName
------   ----               -----------
Running  LxssManager        lxssmanager
```

The command run by this service is `C:\Windows\system32\svchost.exe -k netsvcs -p`. There's in no `lxssmanager` binary to run, thus `The term 'lxssmanager' is not recognized as a name of a cmdlet, function, script file, or executable program` error message.

**Comment by OneBlue** [comment]
@arnon001: LxssManager is the inbox service for WSL. It's only present of the WSL optional component is enabled. If you're using WSL from the store, then WslService is present.
