### ISSUE TITLE
No OpenGL hardware acceleration in WSL2 for Tigerlake

### ISSUE THREAD

**Issue by Tillmann75** [microsoft/WSL#8664]
### Version

10.0.22622.436

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Fedora 36

### Repro Steps

type glxinfo -B in the Linux terminal 

### Expected Behavior

tigerlake-Gpu should be recognized and OpenGl hardware acceleration by the gpu should be available

### Actual Behavior

glxinfo says 

Device: llvmpipe (LLVM 14.0.0, 256 bits) (0xffffffff)
Version: 22.1.4
Accelerated: no

So it doesn't recognize the gpu

### Diagnostic Logs

![Screenshot (8)](https://user-images.githubusercontent.com/96116449/181398211-9da08e09-735f-4e76-ac7b-affbdacaa284.png)

**Comment by hez2010** [comment]
Do you have WDDM 3.0+ compatible graphic driver installed on your machine?

**Comment by Tillmann75** [comment]
Hello Steve,  yes, I’m on the newest Windows 11 graphics driver 31.0.101.3222.  By the way, I have also Ubuntu 22.04 on the same Windows 11  Laptop  with WSL2 installed . The issue seems to be the same there. When I start firefox from a terminal it says  [GFX1-]: No GPUs detected via PCI [GFX1-]: glxtest: process failed (received signal 11)  (I can’t start glxinfo in Ubuntu because it gives me Segmentation fault)You can also tell from the sticky behaviour of the Windows that no GPU-acceleration is present either in Fedora or Ubuntu. BW Tillmann Gesendet von Mail für Windows Von: SteveGesendet: Samstag, 30. Juli 2022 03:35An: microsoft/WSLCc: Tillmann75; AuthorBetreff: Re: [microsoft/WSL] No OpenGL hardware acceleration in WSL2 for Tigerlake (Issue #8664) Do you have WDDM 3.0+ compatible graphics driver installed on your machine?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Tillmann75** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/96116449/182044459-ca5fe190-2b0b-4e50-a33f-41df8caa0d3b.png)

Here's a screenshot of the output from device manager. I've installed the 31.0.101.3222 driver through the Intel Driver & Support Assistant (although windows update constantly tries to replace this by an older graphics driver from the 27 series)

**Comment by Tillmann75** [comment]
Following a similar issue https://github.com/microsoft/WSL/issues/8664 I'm typing  "ls -la /dev/dxg" and "MESA_LOADER_DRIVER_OVERRIDE=D3D12 D3D12_DEBUG=all LIBGL_DEBUG=verbose glxinfo -B" into a Linux terminal. The output is as follows:
![Screenshot (15)](https://user-images.githubusercontent.com/96116449/182520398-c20bf291-25e8-4706-a6ef-a703258669ca.png)

**Comment by Tillmann75** [comment]
In any case, here's also the dxdiag.ex
[DxDiag.txt](https://github.com/microsoft/WSL/files/9247843/DxDiag.txt)

**Comment by Tillmann75** [comment]
... and the output of ll /usr/lib/wsl/lib
![Screenshot (16)x](https://user-images.githubusercontent.com/96116449/182521512-cf0eb483-908c-4177-a432-da929dbf4cde.png)

**Comment by MouriNaruto** [comment]
I have met the similar issue on the same OS version.

Kenji Mouri

**Comment by psmolkin** [comment]
Has anyone been solved the problem on Fedora?

**Comment by psmolkin** [comment]
after some investigation 
```sh
LIBGL_DEBUG=verbose glxinfo -B
#and 
strace glxinfo -B
```
I found the current version of `mesa-dri-drivers` lib swrast_dri.so doesn't load drivers from the `/usr/lib/wsl/` path

The ugly way is to copy `swrast_dri.so` from Ubuntu distro and resolve dependencies
```
sudo mv /usr/lib64/dri/swrast_dri.so /usr/lib64/dri/swrast_dri.so_back
sudo cp /mnt/ubuntu/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so  /usr/lib64/dri/
sudo cp /mnt/ubuntu/usr/lib/x86_64-linux-gnu/libLLVM-13.so.1 /usr/lib64/

sudo ln -s /usr/lib64/libedit.so.0.0.69 /usr/lib64/libedit.so.2

sudo dnf install -y lm_sensors-libs
sudo ln -sf /usr/lib64/libsensors.so.4.5.0 /usr/lib64/libsensors.so.5
```
but it works 
```sh
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (Intel(R) Iris(R) Xe Graphics) (0xffffffff)
    Version: 22.0.5
    Accelerated: yes
    Video memory: 16256MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (Intel(R) Iris(R) Xe Graphics)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 22.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 22.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
