### ISSUE TITLE
Allow setting for WSL to *not* sleep/stop due to being unused

### ISSUE THREAD

**Issue by Tristan971** [microsoft/WSL#8665]
**Is your feature request related to a problem? Please describe.**
WSL distro keeps shutting down shortly after not being in use, and the following cold start gets slow in many ways (WSL reinit, WSLg stack reinit, ...)

**Describe the solution you'd like**
I'd like my WSL distro to start alongside Windows, and not stop/sleep. Even if I'm not using it.

**Describe alternatives you've considered**
N/A. Currently, having Docker Desktop with WSL2 integration running seems to be the least invasive hack to achieve this to some extent.

**Additional context**
I appreciate that this is probably a power saving feature, but I'm using a desktop and I care much more about the various slownesses this introduces, alongside causing issues for apps on the Windows side not happily waiting however long that takes for the WSL filesystem or WSLg to be responsive again, for example. (or worse, slow polling of something on WSL side and WSL "disappears" between 2 probes)

**Comment by NotTheDr01ds** [comment]
I agree it would be nice to have, but I think that this is already covered by a combination of the feature request in #6782 and [`vmIdleTimeout`](see discussion #8659 from earlier this week).

The "cold start" issue can probably be *mostly* mitigated by adding the following to your `%userprofile%\.wslconfig` (note that is your *Windows* user profile):

```
[wsl2]
vmIdleTimeout=-1
```

**Comment by Tristan971** [comment]
Oh, I see. Well this mostly dupes #6782 then, even if reading #8659 isn’t particularly encouraging…

Thanks

**Comment by NotTheDr01ds** [comment]
Well, if we get #6782, then #8659 will work as the OP expected.

**Comment by Tristan971** [comment]
@NotTheDr01ds Let's hope they do hear us out...

At least keeping the managed VM up with the idle timeout change does indeed help alleviate parts of the problem I was having, so thanks for that tip
