### ISSUE TITLE
Wsl/E_INVALIDARG

### ISSUE THREAD

**Issue by LionH** [microsoft/WSL#8674]
### Version

Microsoft Windows [Versión 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Versión de WSL: 0.64.0.0
Versión de kernel: 5.10.102.1
Versión de WSLg: 1.0.40
Versión de MSRDC: 1.2.3213
Versión de Direct3D: 1.601.0
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.22000.795

### Repro Steps

I got Windows blue screen and then had to repair Windows because it wasn't booting.

### Expected Behavior

wsl should start and also my Ubuntu distro

### Actual Behavior

Docker Desktop started complaining so I opened Powershell and here the error:
```
PS C:\WINDOWS\system32> wsl
El parámetro no es correcto.
Error code: Wsl/E_INVALIDARG

```

**Comment by LionH** [comment]
Just updated wsl in the Microsoft Store and now I'm given the following:
```
PS C:\Users\lione> wsl
No se pudo iniciar la operación porque no se instaló una característica requerida.
Error code: Wsl/Service/CreateInstance/CreateVm/0x80370114
```

**Comment by LionH** [comment]
Ok, installing a new version of Ubuntu on the Microsoft Store magically repair my other distributions...

**Comment by OneBlue** [comment]
Closing since the issue has been resolved

**Comment by reubenjohn** [comment]
For me updating the problem was that the starting directory was set to `./`. Updating it to something like this fixed the problem:
![image](https://user-images.githubusercontent.com/4802052/208211207-af384a20-8c57-4f24-b91f-10ed22622605.png)

**Comment by naveensethupathy** [comment]
> For me updating the problem was that the starting directory was set to `./`. Updating it to something like this fixed the problem: ![image](https://user-images.githubusercontent.com/4802052/208211207-af384a20-8c57-4f24-b91f-10ed22622605.png)

where will be this setting available

**Comment by rpatterson** [comment]
> where will be this setting available

Those are the settings for the "Windows Terminal" app, @naveensethupathy, and it doesn't make much sense that changing that setting will have any bearing on this issue.  I tried changing it and it didn't have any effect on this issue for me.
