### ISSUE TITLE
WSL2 - internet connection is lost after running dockerd

### ISSUE THREAD

**Issue by sorspyro** [microsoft/WSL#8675]
### Version

Microsoft Windows [Version 10.0.19044.1865]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Other Software

Docker version 20.10.17, build 100c701

### Repro Steps

I've used to use docker inside WSL2 (without docker desktop) with running daemon on WSL2 start.

ping google.com  <--- this ping works
sudo /etc/init.d/docker start
//wait ~30s
ping google.com <--- this ping does not

I'm using this approach for quite a while and there were no issues related to this method. I've got my /etc/resolv.conf set up correctly.

### Expected Behavior

ping works correctly

### Actual Behavior

ping: google.com: Temporary failure in name resolution

**Comment by samucancld** [comment]
bump
