### ISSUE TITLE
Don't exist /proc/slabinfo file

### ISSUE THREAD

**Issue by cxz66666** [microsoft/WSL#8676]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Just run 
```bash
cat /proc/slabinfo
```

### Expected Behavior

Show slabinfo which described in https://man7.org/linux/man-pages/man5/slabinfo.5.html

### Actual Behavior

```bash
cat: /proc/slabinfo: No such file or directory
```

**Comment by OneBlue** [comment]
Thanks reporting this @cxz66666. 

/proc/slabinfo only exists in kernel build with CONFIG_SLAB, which the WSL2 kernel doesn't have. If you need this file, you can get it by building a custom kernel with CONFIG_SLAB (see https://github.com/microsoft/WSL2-Linux-Kernel)
