### ISSUE TITLE
localhost:PORT from windows host no longer gets handled by process running in WSL2

### ISSUE THREAD

**Issue by mwidmann** [microsoft/WSL#8679]
### Version

Microsoft Windows [Version 10.0.25169.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 20.04

### Repro Steps

- update WSL to the newest insider store version
- spin up any kind of server inside WSL (tried with node applications running on Port 3000, 4400, 8080 and a mysql instance running on docker on port 3306)
- try to access the exposed service from f.e. Edge by running http://localhost:3000

### Expected Behavior

Whatever is running on localhost:3000 in WSL is getting delivered to the Browser requesting it.

### Actual Behavior

Edge get's an `ERR_CONNECTION_REFUSED` error.

Accessing through the IP address of eth0 with the port works. So f.e. http://localhost:3000 or http://127.0.0.1:3000 fail, but http://172.25.170.221:3000 works.

This worked until this morning when I updated to the latest version (0.65.1) in the store.

**Comment by benhillis** [comment]
Thanks for reporting. @pmartincic could you please take a look?

**Comment by micktg** [comment]
Maybe this has something do with that:
I cannot reach my Kubernetes cluster build with KinD anymore.
I also tested the Kubernetes cluster from Docker Desktop

Suddenly, I got (for Docker Desktop)
`The connection to the server kubernetes.docker.internal:6443 was refused - did you specify the right host or port?`
or for the KinD cluster
`The connection to the server 127.0.0.1:30000 was refused - did you specify the right host or port?`

I worked perfectly for months. The only thing changed was a Windows Update with update of WSL to 0.65.1

```
❯ wsl --version
WSL version: 0.65.1.0
Kernel version: 5.15.57.1
WSLg version: 1.0.41
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.450
```

**Comment by olivierchatry** [comment]
Same here, minikube cannot ssh to it container anymore.
I can SSH to it from a "normal" windows prompt, but not from WSL linux distro.
Happen since the last update I got this morning :
```

**Comment by benhillis** [comment]
Are you guys by chance using a private kernel? Could you share the output of `cat /proc/version`?

**Comment by micktg** [comment]
❯ cat /proc/version
Linux version 5.15.57.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Jul 27 02:20:31 UTC 2022

> Are you guys by chance using a private kernel? Could you share the output of `cat /proc/version`?

**Comment by felpasl** [comment]
uninstalling 10.0.22622.450 on `Windows Update>Update history>Uninstall updates` doesn't fix remain the message

`The connection to the server kubernetes.docker.internal:6443 was refused - did you specify the right host or port?`

I'm trying to find an option to downgrade wsl back to [0.64.0]

```
Versão do WSL: 0.65.1.0
Versão do kernel: 5.15.57.1
Versão do WSLg: 1.0.41
Versão do MSRDC: 1.2.3213
Versão do Direct3D: 1.601.0
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows versão: 10.0.22622.440
```

**Comment by NotTheDr01ds** [comment]
Just an additional data point that I am *not* able to reproduce after installing 0.65.1 on Windows 11 non-Insider (10.0.22000.795).  I installed from the Releases page using `Add-AppxPackage` in an Administrative PowerShell:

```
$ $env:WSL_UTF8=1
$ wsl --status | clip.exe

Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.65.1.0
Kernel version: 5.15.57.1
WSLg version: 1.0.41
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.795
```

In Ubuntu 22.04:

```
python3 -m http.server
```

And can browse in Edge to `localhost:8000` and view the directory contents.  Also tried with port 3000, which worked as well.

So perhaps it's something else in Insider causing the issue rather than the WSL update?  Or perhaps an interaction between the two.

**Comment by felpasl** [comment]
I'm using Insider back to  22622.450, the connection from windows to localhost:80 hosted in kubernetes WSL2 "Docker Desktop" worked.

from WSL2 Ubuntu `docker ps` worked

from WSL2 Ubuntu `kubectl get namespaces` doesn't work 

from windows Powershell `kubectl get namespaces` worked

i'm trying to export my wsl Ubuntu distro, to uninstall wsl from windows, and try reinstall wsl without the Preview, in last scenario start work again in windows powershell until solution or work around is found 😥

**Comment by micktg** [comment]
> I'm using Insider back to 22622.450, the connection from windows to localhost:80 hosted in kubernetes WSL2 "Docker Desktop" worked.
> 
> from WSL2 Ubuntu `docker ps` worked
> 
> from WSL2 Ubuntu `kubectl get namespaces` doesn't work
> 
> from windows Powershell `kubectl get namespaces` worked
> 
> i'm trying to export my wsl Ubuntu distro, to uninstall wsl from windows, and try reinstall wsl without the Preview, in last scenario start work again in windows powershell until solution or work around was found 😥

I can confirm the same behavior.
I can also add, that I installed a new WSL distro Ubuntu 18.04 and got the same behavior with the freshly installed distro.

**Comment by pmartincic** [comment]
Ahhhh, this helps. I read the original bug description as saying that localhost:port was inaccessible from the windows host.


> I'm using Insider back to 22622.450, the connection from windows to localhost:80 hosted in kubernetes WSL2 "Docker Desktop" worked.
> 
> from WSL2 Ubuntu `docker ps` worked
> 
> from WSL2 Ubuntu `kubectl get namespaces` doesn't work
> 
> from windows Powershell `kubectl get namespaces` worked
> 
> i'm trying to export my wsl Ubuntu distro, to uninstall wsl from windows, and try reinstall wsl without the Preview, in last scenario start work again in windows powershell until solution or work around was found 😥

**Comment by DmytryEmery** [comment]
> I'm trying to find an option to downgrade wsl back to [0.64.0]

Any luck on this?
[0.65.1] has broken Kind cluster.

Everything (docker, kind) latest version, but since yesterday when this got updated it doesn't work, even with clean install.

**Comment by benhillis** [comment]
@DmytryEmery - I'd suggest downloading a previous release from the github releases page.

**Comment by DmytryEmery** [comment]
@benhillis thanks! 
just to confirm reverting to 0.64.0 resolved the issue for me

**Comment by benhillis** [comment]
While debugging this locally we have pushed https://github.com/microsoft/WSL/releases/tag/0.65.2 which will revert to the previous behavior.

**Comment by mwidmann** [comment]
Sadly the update was installed before I could get the logs, but I can confirm that with this version, the described issues are gone.

**Comment by Tychoblood** [comment]
> @benhillis thanks! just to confirm reverting to 0.64.0 resolved the issue for me

Can you explain how you did it ? Downloaded the packages and launched the installer but it wouldn't finish.
Tried in Powershell via this command : Add-AppPackage -path "C:\Users\xxxxxx\Downloads\Microsoft.WSL_0.64.0.0_x64_ARM64.msixbundle"
but to no avail. It states that the superior version is already installed and so cant downgrade...

Having the same problem after this night update , and of course the day it is most needed (merge and review for client project release...)

**Comment by mwidmann** [comment]
> > @benhillis thanks! just to confirm reverting to 0.64.0 resolved the issue for me
> 
> Can you explain how you did it ? Downloaded the packages and launched the installer but it wouldn't finish. Tried in Powershell via this command : Add-AppPackage -path "C:\Users\xxxxxx\Downloads\Microsoft.WSL_0.64.0.0_x64_ARM64.msixbundle" but to no avail. It states that the superior version is already installed and so cant downgrade...
> 
> Having the same problem after this night update , and of course the day it is most needed (merge and review for client project release...)

The update was just offered to me through the Windows Store. That's why it was faster than my logs gathering.

**Comment by mwidmann** [comment]
This is getting stranger and stranger. It appears that the problems start when a second port is opened with the same process. Running one node process on port 8080 works, starting a second one on port 4400 produces the `ERR_CONNECTION_REFUSED`. Same with the simple python webserver. Running `python3 -m http.server` works, but starting a second instance `python3 -m http.server 8080` breaks both.

Here's a new set of logs...
[WslLogs-2022-08-04_08-50-11.zip](https://github.com/microsoft/WSL/files/9257357/WslLogs-2022-08-04_08-50-11.zip)

**Comment by olivierchatry** [comment]
Still the same issue with minikube using 0.65.2.

Forcing downgrade to  0.64.0 fixed the issue.

Sidenote, to downgrade, download the package from github then, on a
powershell prompt :
```powershell
Add-AppxPackage -Path .\Microsoft.WSL_0.64.0.0_x64_ARM64.msixbundle
-ForceUpdateFromAnyVersion  -ForceApplicationShutdown
```

**Comment by hf35** [comment]
Have the same issue with opening localhost and 127.0.0.1 on diffrent ports. It can work with localhost:3000, but doesn't work on localhost:3020 or vise versa. Both 0.65.1 and 0.65.2 have this issue.

Downgrade to 0.64.0 is fixed problem

Added logs (while launched server and tryed to get it from Windows)
[WslLogs-2022-08-04_13-39-38.zip](https://github.com/microsoft/WSL/files/9257904/WslLogs-2022-08-04_13-39-38.zip)

**Comment by hf35** [comment]
One more thing
react application doesn't work on localhost:3000, but "nc -l 3000" - worked correctly on localhost:3000

**Comment by Tychoblood** [comment]
> Still the same issue with minikube using 0.65.2. Forcing downgrade to 0.64.0 fixed the issue. Sidenote, to downgrade, download the package from github then, on a powershell prompt : ```powershell Add-AppxPackage -Path .\Microsoft.WSL_0.64.0.0_x64_ARM64.msixbundle -ForceUpdateFromAnyVersion -ForceApplicationShutdown ```

I can confirm this work, I was just missing the ForceUpdate part.
Downgrading to 0.64.0 also fixed the issue , whereas the 0.65.2 would work for a few requests and then no more, with ERR_CONNECTION_REFUSED http status.

**Comment by ZedG2** [comment]
0.65.2 not work for me

**Comment by felpasl** [comment]
0.65.2 doesn't work, thx @olivierchatry, reverting is an solution, but an --upgrade "version" or some type of downgrade procedure in docs will be easy.

**Comment by micktg** [comment]
Another thing I noticed is that my computer freezes now regularly when I do `wsl --shutdown`. This never happened before in previous versions. It's a complete freeze and I can't do anything. Have to unplug the A/C connector.

**Comment by hf35** [comment]
> Another thing I noticed is that my computer freezes now regularly when I do `wsl --shutdown`. This never happened before in previous versions. It's a complete freeze and I can't do anything. Have to unplug the A/C connector.
> 
> EDIT: I also downgraded to 0.64 and everything works again. Kubernetes in WSL is reachable again. No sudden connection lost with react apps and no freeze during `WSL --shutdown`

Btw, i had the same complete freezes after "WSL --shutdown" on 0.65...

**Comment by benhillis** [comment]
Taking another look, the revert should have fixed the issue...

**Comment by benhillis** [comment]
@hf35 - looks like your trace is for 0.65.1, do you have one for 0.65.2?

**Comment by benhillis** [comment]
Ok I sorted this out, I tagged the wrong commit. Pushing a new build (0.65.3) here shortly.

**Comment by benhillis** [comment]
@hf35 - coudl you please file a new bug for that issue? I suspect this is vgpu related.

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL/releases/tag/0.65.3

**Comment by swichers** [comment]
@benhillis Should we be seeing 0.65.3 as an update for insiders at this point, or is that for manual install?

**Comment by ZedG2** [comment]
> @benhillis Should we be seeing 0.65.3 as an update for insiders at this point, or is that for manual install?

![image](https://user-images.githubusercontent.com/7886856/182988629-3f41e865-8ce1-42e6-a322-15a92531d612.png)

**Comment by hf35** [comment]
@benhillis everyhing is ok on 0.65.3 with localhost

>@hf35 - coudl you please file a new bug for that issue? I suspect this is vgpu related.

About freezes? I am not sure, how i can save log, because after shutdown command - my pc is completly freeze and and can't press button to collect logs

**Comment by nunix** [comment]
I went through podman/docker desktop/rancher desktop/k3d/kind with 0.65.3 and as far as I can tell, it's fixed now.

Thank you @benhillis and team for the fast fix, really appreciated

**Comment by micktg** [comment]
> 

I haven't tested it myself yet with the new version but I can only say also thanks especially for the extremely fast response time and fixes. Very much appreciated.

**Comment by Ankit1598** [comment]
Hey guys I am also facing the same issue, can anyone just help me downgrading. I tried the steps given by @olivierchatry but I am getting the following result

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher version of this package is already installed.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForLinux_0.64.0.0_x64__8wekyb3d8bbwe because it has version 0.64.0.0. A higher version 0.65.3.0 of this package is already installed.
NOTE: For additional information, look for [ActivityId] 1436d026-a8e9-000f-db43-5214e9a8d801 in the Event Log or use the command line Get-AppPackageLog -ActivityID 1436d026-a8e9-000f-db43-5214e9a8d801
At line:1 char:1
+ Add-AppxPackage -Path .\Microsoft.WSL_0.64.0.0_x64_ARM64.msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\...RM64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

Can anyone help me with the steps to downgrade, cannot find anything in the docs.

**Comment by benhillis** [comment]
Thanks everyone for the kind words, we're working on a fix here because the new localhost behavior is really neat (minus this bug).

@hf35 - please file a new issue, that is unrelated.

**Comment by Ankit1598** [comment]
I downgraded wsl, rolledback windows update, tried all the combinations possible but nothing works, when I run any of my WebApp (React, Next, Nuxt, etc) and try to access [https://localhost:3000](https://localhost:3000), I keep getting `ERR_CONNECTION_RESET`

WSL Versions tried: [0.65.3](https://github.com/microsoft/WSL/releases/tag/0.65.3), [0.64.0](https://github.com/microsoft/WSL/releases/tag/0.64.0), [0.61.8](https://github.com/microsoft/WSL/releases/tag/0.61.8)

$ ver
Microsoft Windows [Version 10.0.25169.1000]

$ wsl.exe --status
Default Distribution: Ubuntu-20.04
Default Version: 2
WSL version: 0.65.3.0
Kernel version: 5.15.57.1
WSLg version: 1.0.41
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25169.1000

**Comment by onomatopellan** [comment]
@Ankit1598 Make sure you are not hitting https://github.com/microsoft/WSL/issues/5575

**Comment by filippomc** [comment]
The same issue appears on wsl 1.1.0 (now installed by default on insider previews). Downgrading to 1.0.3 fixed for me

**Comment by olivierchatry** [comment]
Yup, same for me.

**Comment by forberg** [comment]
Same with WSL 1.1.0 for me. Works if i downgrade to 1.0.3. Maybe create a new issue? Seems to be some localhost related updates in 1.1.0: https://github.com/microsoft/WSL/releases/tag/1.1.0

**Comment by pmartincic** [comment]
Back from the dead!

Sorry for the inconvenience. This issue you're experiencing in 1.1.0 is currently being worked on and tracked at #9508 This issue, 8679, tracked other problems with the relay.

**Comment by felpasl** [comment]
same behavior again, downgraded from 1.1.2 to 1.0.3 and worked:

`Add-AppxPackage -Path .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle -ForceUpdateFromAnyVersion  -ForceApplicationShutdown`

**Comment by pmartincic** [comment]
@persedes, I just realized that this bug was tracking code that was reverted. Could you open a new bug and post logs? Thanks!

I'm going to lock this thread to direct people elsewhere.
