### ISSUE TITLE
How to remove or disable Nvidia driver in WSL2

### ISSUE THREAD

**Issue by kuroneko306** [microsoft/WSL#8687]
I am using an Ubuntu 18.04 LTS distribution with WSL2.
The distribution comes with Nvidia drivers as a pre-installed virtual packages.
However the program I was trying to run can only use CPU graphics, and an Nvidia driver will cause it to crash because Ubuntu will try to use graphic cards if Nvidia driver exists.

If I try to uninstall the Nvidia driver, the terminal shows the messages like ''Virtual packages like 'nvidia-smi' can't be removed''.
Is there any way to remove or disable Nvidia drives in a WSL2 distribution ?
Or the only way I can do is physically remove the graphic card and re-install the distribution ?

**Comment by NickDeBeenAIE** [comment]
CPU's have no graphical output unless the chip has an on board iGPU.

Chipsets however, are a thing, and they do come with drivers.

**Comment by NickDeBeenAIE** [comment]
The command to use to uninstall the driver is:

First, run this: ``sudo lspci``

Then this: ``sudo apt-get -purge nvidia``

If this does not work, standby, I'll get you the correct command.

**Comment by NickDeBeenAIE** [comment]
Command number 2 should be: ``sudo apt-get remove --purge nvidia``

**Comment by NickDeBeenAIE** [comment]
This should completely remove the Nvidia driver from the Ubuntu distro.

Yet, I still am unsure if Microsoft allowed the removal of packages within a distro installed from the store.
