### ISSUE TITLE
Cannot enable WSL (Error code: Bash/Service/CreateInstance/CreateVm/ERROR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by TonyyJp** [microsoft/WSL#8688]
`bash`
or
`wsl.exe start`

The system can not find the file specified.

`Error code: Bash/Service/CreateInstance/CreateVm/ERROR_FILE_NOT_FOUND`

**Comment by bsqsbylt** [comment]
![图片](https://github.com/microsoft/WSL/assets/2088504/5961080b-b0b6-41ba-83ce-7252428304dc)

同样遇到这个问题了

**Comment by bsqsbylt** [comment]
Fix by this way
![图片](https://github.com/microsoft/WSL/assets/2088504/27f88128-0445-4d2a-be85-464605170a5e)
