### ISSUE TITLE
Why /dev/sdb is so full but I haven't installed many things in my wsl2 ?

### ISSUE THREAD

**Issue by greenhandzpx** [microsoft/WSL#8689]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

ArchLinux

### Repro Steps

sudo df -h

### Expected Behavior

As I know, /dev/sdb is related to the wsl2's file system vhdx, so the size of the space occupied in /dev/sdb should be the same as the size of my ext4.vhdx file.

### Actual Behavior

But why the space that has been used in /dev/sdb is so large(168GB) ? my ext4.vhdx file is only 4.15 GB.
![df2](https://user-images.githubusercontent.com/74168957/183017590-533e36f5-1755-4a27-a2d2-e2f9f78090af.png)
![vhdx](https://user-images.githubusercontent.com/74168957/183017709-dc0a4ca0-2603-4c0c-97cd-5ef65bc1b177.png)

**Comment by greenhandzpx** [comment]
Ok, I find that the huge files are located in /tmp. But I still don't know why it seems that those tmp files don't occupy real space?

**Comment by Biswa96** [comment]
WSL2 does not release free space back to disk. See this issue `https://github.com/microsoft/WSL/issues/4699`. It is possible to release that space.
1. Shutdown all WSL session with `wsl.exe --shutdown` command.
2. Optimize the vhdx file with `optimize-vhd -mode full -path C:\archlinux\Arch\ext4.vhdx` command in Powershell.

**Comment by greenhandzpx** [comment]
> WSL2 does not release free space back to disk. See this issue `https://github.com/microsoft/WSL/issues/4699`. It is possible to release that space.
> 
>     1. Shutdown all WSL session with `wsl.exe --shutdown` command.
> 
>     2. Optimize the vhdx file with `optimize-vhd -mode full -path C:\archlinux\Arch\ext4.vhdx` command in Powershell.

Ok, thanks.
