### ISSUE TITLE
timedatectl fails

### ISSUE THREAD

**Issue by iz0eyj** [microsoft/WSL#869]
Federico@BESTIA:~$ timedatectl status
Failed to get D-Bus connection: Failed to connect to socket /var/run/dbus/system_bus_socket: File o directory non esistente

Dbus strikes again :)

**\* I'm using  <listen>tcp:host=localhost,port=0</listen> in dbus config to run XFCE

**Comment by aseering** [comment]
Hm...  Out of curiosity, does it work if you [fix dbus](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=12)?  Or does it get stuck on another issue?

**Comment by iz0eyj** [comment]
@aseering I was edit the post to specify that I'm using the fix... so yes, it crashes with the fix.

**Comment by aseering** [comment]
Hm, interesting -- the fix makes dbus use TCP, so if you're using the fix, why's it trying to connect over `/var/run/dbus/system_bus_socket`?  (ie., a socket file, not TCP)

**Comment by iz0eyj** [comment]
@aseering the fix don't fixes all. For example, XFCE works fine, but at the start you get:
(xfsettingsd:37): libupower-glib-WARNING **: Couldn't connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: File o directory non esistente

Dbus *MUST* be fixed.

**Comment by sunilmut** [comment]
With better support for AF_LOCAL socket, dbus seems to be happy and timedatectl also works. Fixes are moving fast to the release build, keep an eye on the release notes.

**Comment by therealkenc** [comment]
>  dbus seems to be happy and timedatectl also works

Came across this strange one cleaning up old fixinbounds. This was closed because of long past AF_UNIX improvements enabling `dbus`, which is great, as it goes. But there is no way [`timedatectl`](https://www.freedesktop.org/software/systemd/man/timedatectl.html) flies without [`systemd-timedated`](https://www.freedesktop.org/software/systemd/man/systemd-timedated.service.html) on the other end. Which, it isn't, because we don't have `systemd`. Trying to start `timedated` and `timesyncd` (NTP) manually worms.
```
$ sudo service dbus start
$ exec dbus-run-session -- bash
$ timedatectl  # the 'permission denied' error below is wrong/misleading. The service isn't there.
Failed to query server: Failed to execute program org.freedesktop.timedate1: Permission denied
$ /lib/systemd/systemd-timedated
/etc/localtime should be a symbolic link to a time zone data file in /usr/share/zoneinfo/.
Failed to determine whether NTP is enabled: Input/output error
$ /lib/systemd/systemd-timesyncd
Failed to create state directory: No such file or directory
```
The services might be able to be coerced into starting without `systemd` but that's as far as I pursued it.

**Comment by EmilRehnberg** [comment]
`timedatectl` still fails for me. After installing `dbus` and everything. 

```
$ timedatectl                                                                                                                                                                                                                                                                                                Failed to query server: Message recipient disconnected from message bus without replying 
```
Is this still a current issue? Or should it be solved by now?

**Comment by therealkenc** [comment]
> Is this still a current issue? Or should it be solved by now?

Yes still open. WSL1 and WSL2 use a house brand `init(8)` so no `systemd`, by extension no `systemd-timesyncd.service(8)`, ergo no `timedatectl(1)`.

> and everything.

Doing "and everything" on WSL2 is possible for the determined. Hangout is #994.

**Comment by therealkenc** [comment]
LZ #994.

**Comment by mangelozzi** [comment]
> Hm... Out of curiosity, does it work if you [fix dbus](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=12)? Or does it get stuck on another issue?

This link no longer works. Any suggestions on what to try to get `timedatectl` to work?

**Comment by effolkronium** [comment]
+1
