### ISSUE TITLE
wsl.exe does not reflect custom kernel

### ISSUE THREAD

**Issue by jibnew** [microsoft/WSL#8690]
### Version

Microsoft Windows [Version 10.0.22000.832]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.19

### Distro Version

Ubuntu 22.04

### Other Software

May `cygwin` mess things up somehow?

### Repro Steps

Compile custom kernel following the steps in [https://wsl.dev/wsl2-kernel-zfs/](https://wsl.dev/wsl2-kernel-zfs/)
Ensure `cat /proc/version` returns
```Linux version 5.19.0-microsoft-standard (me@DESKTOP-M4AP3T8) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #2 SMP PREEMPT_DYNAMIC Wed Aug 3 01:11:12 +04 2022```

### Expected Behavior

wsl.exe --status shows kernel version 5.19

### Actual Behavior

wsl.exe --status returns 
```Default Distribution: Ubuntu-22.04
Default Version: 2

Windows Subsystem for Linux was last updated on 27-Mar-22
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

**Comment by benhillis** [comment]
This is by design, this is meant to tell you the version of the kernel that we are supporting.
