### ISSUE TITLE
WSL --import cannot find file

### ISSUE THREAD

**Issue by dsmarcelo** [microsoft/WSL#8692]
I had to restore my windows yesterday and i exported 2 wsl distros before reinstalling windows, but now i can't restore the backup.
------------------------------------------------------------------------

 - If i type `wsl --import Ubuntu f:\Backup\Ubuntu.tar` i get the same
   result as the `wsl --help` command.
 - If i type `wsl --import Ubuntu f:\Backup .\Ubuntu.tar` i get `The
   system cannot find the file specified.` as an response, but the file is in this folder, [as the image shows][1].

----------

I have installed wsl and removed the default Ubuntu with the `--unregister` command before trying to restore my backup distro. 

 - The same thing happens with my custom Arch distro.
 - I already tried to change the file to the C: drive and rename the
   file without success.
 - I tried changing the distro name in the import command and it didn't
   work.
 - I have no distros in wsl at the moment.

What can i try now?

  [1]: https://i.stack.imgur.com/AYNbF.png

**Comment by Biswa96** [comment]
The import command is like this `--import <Distro> <InstallLocation> <FileName> [Options]`. So, rule out the first one because it does not mention install location. For the second one, check if the current working directory is same as the .tar file. If not, mention full path of that .tar file.

**Comment by dsmarcelo** [comment]
@Biswa96 It was the working directory, it's working now, thank you!
