### ISSUE TITLE
The default virtual size of ext4.vhdx became 1024GB when wsl was installed, and the vhdx file size grew too fast

### ISSUE THREAD

**Issue by DreamGallery** [microsoft/WSL#8695]
### Version

Microsoft Windows [Version 10.0.22622.450]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Just after installing wsl, I used diskpart in Powershell to view the virtual disk size and found that the virtual size shows 1024GB by default.This seems to be unadjustable.
After a period of use,enter the df command in wsl, /dev/sdc shows that it just uses 47GB but the vhdx file takes up about 341G of hard drive space and cannot be compressed using diskpart

### Expected Behavior

I wonder if it is possible to change the default virtual size instead of 1024GB and increase the vdhx file size to match the actual use or to compress it.
The official documentation shows that using diskpart can expand the virtual size but there is no mention of a way to reduce it.

### Actual Behavior

```
DISKPART> detail vdisk

Device type ID: 0 (Unknown)
Vendor ID: {00000000-0000-0000-0000-000000000000} (Unknown)
State: Added
Virtual size:  1024 GB
Physical size: 341GB
Filename: %USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\LocalState\ext4.vhdx
Is Child: No
Parent Filename:
Associated disk#: Not found.
```

```
➜  ~ df   -hl
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc       1007G   47G  910G   5% /
rootfs           32G  1.9M   32G   1% /init
none             32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
none             32G  4.0K   32G   1% /run
none             32G     0   32G   0% /run/lock
none             32G     0   32G   0% /run/shm
none             32G     0   32G   0% /run/user
drivers         954G  565G  389G  60% /usr/lib/wsl/drivers
none             32G     0   32G   0% /usr/lib/wsl/lib
none             32G  4.0K   32G   1% /mnt/wsl
none             32G   28K   32G   1% /mnt/wslg
none             32G   76K   32G   1% /mnt/wslg/versions.txt
none             32G   76K   32G   1% /mnt/wslg/doc
drvfsa          954G  565G  389G  60% /mnt/c
drvfsa          932G  472G  461G  51% /mnt/d
drvfsa          932G   44G  888G   5% /mnt/e
drvfsa          1.9T  794M  1.9T   1% /mnt/f
```

**Comment by DreamGallery** [comment]
About using diskpart tool to compact vdisk，I learned that I need to defragment the virtual disk in WSL with a command like 
```
sudo dd if=/dev/zero of=/0bits bs=20M 
```
to effectively compact.
But this is only a temporary solution, regular use may have a bad effect on the SSD and vhdx file size is still growing fast.
If there was some way to safely resize or set default value of the virtual size when new install, may helpful to me.

**Comment by Biswa96** [comment]
WSL2 does not release free space back to disk. See this issue `https://github.com/microsoft/WSL/issues/4699`. It is possible to release that space.
1. Shutdown all WSL session with `wsl.exe --shutdown` command.
2. Optimize the vhdx file with `optimize-vhd -mode full -path C:\path\to\ext4.vhdx` command in Powershell.

**Comment by DreamGallery** [comment]
> In response to my question, optimize-vhd or diskpart-compact both need to defragment or zero-fill the vhdx file first to have a noticeable effect, making the compressed size close to the size used.
The main problem is why the default virtual size of the vhdx file is 1024GB after I install wsl and not 256GB like others. on my other computer it is also 256GB. changing the wsl distribution the default virtual size does not change either

**Comment by DreamGallery** [comment]
> WSL2 does not release free space back to disk. See this issue `https://github.com/microsoft/WSL/issues/4699`. It is possible to release that space.
> 
> 1. Shutdown all WSL session with `wsl.exe --shutdown` command.
> 2. Optimize the vhdx file with `optimize-vhd -mode full -path C:\path\to\ext4.vhdx` command in Powershell.


To my case, optimize-vhd or diskpart-compact both need to defragment or zero-fill the vhdx file first to have a noticeable effect, making the compressed size close to the size used.
The main problem is why the default virtual size of the vhdx file is 1024GB for me and not 256GB like others. on my other computer it is also 256GB. changing the wsl distribution the default virtual size does not change either

**Comment by Biswa96** [comment]
> why the default virtual size of the vhdx file is 1024GB for me and not 256GB like others

The default max size was changed to 1TB in recent WSL Preview version [0.58.0][1].

[1]: https://github.com/microsoft/WSL/releases/tag/0.58.0

**Comment by DreamGallery** [comment]
> > why the default virtual size of the vhdx file is 1024GB for me and not 256GB like others
> 
> The default max size was changed to 1TB in recent WSL Preview version [0.58.0](https://github.com/microsoft/WSL/releases/tag/0.58.0).

I see, I just defragment and compress vhdx file regularly , although a little inconvenient.
Hope the virtual disk size allocation of wsl can be more intelligent in future update.

**Comment by ZoeZhong-AAXIS** [comment]
> WSL2 does not release free space back to disk. See this issue `https://github.com/microsoft/WSL/issues/4699`. It is possible to release that space.
> 
> 1. Shutdown all WSL session with `wsl.exe --shutdown` command.
> 2. Optimize the vhdx file with `optimize-vhd -mode full -path C:\path\to\ext4.vhdx` command in Powershell.

Thanks. This solution works for me.
