### ISSUE TITLE
\\wsl.localhost\ not accessible from sshd on windows

### ISSUE THREAD

**Issue by anatawa12** [microsoft/WSL#8697]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Other Software

OpenSSH server (windows) OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

### Repro Steps

1. configure & launch ssh server on windows
2. connect to the ssh server on windows
3. start wsl
4. run `ls '\\wsl.localhost\Ubuntu-22.04'`

### Expected Behavior

show list of files of '/' of Ubuntu

### Actual Behavior

```
> ls '\\wsl.localhost\Ubuntu-22.04'
Get-ChildItem: Cannot find path '\\wsl.localhost\Ubuntu-22.04' because it does not exist.
```

### Diagnostic Logs

[WslLogs-2022-08-06_21-52-45.zip](https://github.com/microsoft/WSL/files/9275057/WslLogs-2022-08-06_21-52-45.zip)

**Comment by NickDeBeenAIE** [comment]
Can you confirm that you can actually see the file directories, or the files directory that WSL created?

**Comment by anatawa12** [comment]
Yes. I confirm the directory is exists in explorer and pwsh on windows desktop. 
However, its not accessible from pwsh on ssh.
