### ISSUE TITLE
Beginner needs to access WSL2 application attached to a specific port. Is there a way to create a static ip or custom domain?

### ISSUE THREAD

**Issue by mahmoud-shihab** [microsoft/WSL#8699]
I currently have a Ubuntu WSL2 instance up and running on my machine, and within it, I have installed an application I need for my work.
To access the application, I need to enter the ip address of the Ubuntu image and connect to port 11000.
Now, every time I reset my machine, I have to find the new ip address and connect to the machine.
Is there not a way I can just make the ip-address of the Ubuntu WSL2 machine static, or give it a domain so I don't have to keep constantly finding the ip-address and connecting to it?

**Comment by NickDeBeenAIE** [comment]
This should only depend on what your IP sets it to (IP Stands for Internet Provider in this case), but, I have had the same problem apply to myself once.

**Comment by NickDeBeenAIE** [comment]
Just use a VM man.

Download VMWare Workstation, and install a Linux VM in there, you'll be required to redownload your work application, but at least you get a static IP address for it.

**Comment by OneBlue** [comment]
@mahmoud-shihab: You can always use localhost:<port> from Windows, this will forward traffic to WSL as long as the wsl2.localhostForwarding setting is set to true. see https://docs.microsoft.com/en-us/windows/wsl/wsl-config
