### ISSUE TITLE
[WSL2] F5 VPN breaks network connectivity

### ISSUE THREAD

**Issue by RishikeshDarandale** [microsoft/WSL#8704]
### Version

Microsoft Windows [Version 10.0.19044.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-22.04

### Other Software

F5 Edge VPN Client

### Repro Steps

- Logon to f5 VPN
- Start the WSL
- Do a curl to `curl www.google.com` 

As per f5 [knowledge article](https://support.f5.com/csp/article/K30258362), we have to launch the WSL2 once we are on VPN, but it does not work.  FYI: I do not have admin rights on the windows 10.

### Expected Behavior

network connectivity should work from WSL 2

### Actual Behavior

network connectivity is not working from WSL 2

**Comment by RishikeshDarandale** [comment]
I have also tried [these](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#bash-loses-network-connectivity-once-connected-to-a-vpn) steps, but it's not resolving the issue.

**Comment by RishikeshDarandale** [comment]
I tried [`wsl-vpnkit`](https://github.com/sakai135/wsl-vpnkit) and it worked

**Comment by dfaivre** [comment]
Same issue using the Azure VPN client where the remote VNET has conflicting IP routes with the WSL2 ethernet

**Comment by geovalexis** [comment]
Same here
