### ISSUE TITLE
Running debug version of "Crawl" (tiles) twice stops entire WSL system including other distros.

### ISSUE THREAD

**Issue by zzxyz** [microsoft/WSL#8708]
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

https://github.com/crawl/crawl/issues/2406

Use Windows 11 "built-in" x-server.  (not reproducible with vcxsrv)

Note: the release version which can be apt installed also exhibits bad behavior, but may not be a WSL issue.  The debug version definitely is.

Run debug version of crawl (I'm happy to attach the executable but assume you'd prefer I didn't--
```
git clone https://github.com/crawl/crawl.git
cd crawl/crawl-ref/source
git submodule update --init
sudo apt install libsdl2-image-dev
make -j4 debug TILES=y
```
Run ./crawl
Exit Crawl with escape key from crawl ui (it may be necessary to hit it twice)
Run ./crawl

### Expected Behavior

WSL remains responsive.

### Actual Behavior

All running WSL instances stop, including other distributions.
[process exited with code 1 (0x00000001)]

`wsl --shutdown` is necessary to recover

### Diagnostic Logs

[WslLogs-2022-08-09_11-24-56.zip](https://github.com/microsoft/WSL/files/9293853/WslLogs-2022-08-09_11-24-56.zip)

**Comment by OneBlue** [comment]
Thanks for reporting this @zzxyz.

Unfortunately to diagnose this I'd need to look at the dmesg output, which isn't captured in the version of WSL you're running.

Can you try to install to install [Store WSL](http://aka.ms/wslstorepage) and get another repro with logs ?

**Comment by zzxyz** [comment]
[WslLogs-2022-08-12_09-37-45.zip](https://github.com/microsoft/WSL/files/9328573/WslLogs-2022-08-12_09-37-45.zip)

**Comment by zzxyz** [comment]
Behavior is much less deterministic in Store WSL.  I've reproduced it on my first run of the *release* version of Crawl (0.28).  In the log case above it took 3 runs.
Debian instructions here.
http://crawl.develz.org/download.htm#linux

**Comment by zzxyz** [comment]
Still reproduceable (although much less consistent) with newest crawl (0.29.1) and this:

~> wsl -v
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521
~>
