### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/0x8000ffff

### ISSUE THREAD

**Issue by Easonqsp** [microsoft/WSL#8711]
### Version

Microsoft Windows [Version 10.0.25174.1010]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-22.04

### Repro Steps

PS ****> wsl
灾难性故障
Error code: Wsl/Service/CreateInstance/0x8000ffff

### Expected Behavior

I was starting the WSL

### Actual Behavior

It throw "Error code: Wsl/Service/CreateInstance/0x8000ffff"

**Comment by duncanmak** [comment]
[WslLogs-2022-09-08_00-52-33.zip](https://github.com/microsoft/WSL/files/9523673/WslLogs-2022-09-08_00-52-33.zip)

I have been experiencing this issue on my Surface Pro X running Windows 11.

**Comment by zeejay09** [comment]
I encountered this issue when my computer suddenly shutdowns due to power interruption, is there any way to recover or fix it? Or a reinstall is a must?

[WslLogs-2022-12-02_15-14-06.zip](https://github.com/microsoft/WSL/files/10138937/WslLogs-2022-12-02_15-14-06.zip)

**Comment by OneBlue** [comment]
@zeejay09: Looking at the logs, it looks like your distribution vhdx needs fsck.

```
3116	False	Microsoft.Windows.Lxss.Manager	GuestLog	0	12-01-2022 23:14:21.375	30380	"text: 	""[    2.541583] EXT4-fs error (device sdc): ext4_validate_inode_bitmap:105: comm init: Corrupt inode bitmap - block_group = 66, inode_bitmap = 5315 ""
vmId: 	{6eee6f5c-f6cc-48ac-9028-94b3653cc640}"		"	"				10372	5		00000000-0000-0000-0000-000000000000		

```

To solve this you could use another distribution and mount the distribution disk via [wsl .exe--mount](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) 

(You can find the path to the distribution vhdx under Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss)

Once mounted, you can use `lsblk` to find the block device path, and then use `fsck /dev/sdX` to repair the disk (replace sdX by the block device name)

**Comment by emmyapi** [comment]
> 
[WslLogs-2022-12-18_00-38-39.zip](https://github.com/microsoft/WSL/files/10252918/WslLogs-2022-12-18_00-38-39.zip)

My error message is just: 
PS C:\Users\Kenneth>  wsl --install -d Ubuntu-20.04
Installing: Windows Subsystem for Linux
Catastrophic failure
PS C:\Users\Kenneth>

For me, WSL 2.0 is installed I think. But I can't install any distributions

**Comment by OneBlue** [comment]
> > 
> 
> [WslLogs-2022-12-18_00-38-39.zip](https://github.com/microsoft/WSL/files/10252918/WslLogs-2022-12-18_00-38-39.zip)
> 
> My error message is just: PS C:\Users\[redacted]> wsl --install -d Ubuntu-20.04 Installing: Windows Subsystem for Linux Catastrophic failure PS C:\Users\[redacted]>
> 
> For me, WSL 2.0 is installed I think. But I can't install any distributions

This probably the same issue as #9258

**Comment by leocoolmitra** [comment]
> > 
> [WslLogs-2022-12-18_00-38-39.zip](https://github.com/microsoft/WSL/files/10252918/WslLogs-2022-12-18_00-38-39.zip)
> 
> My error message is just: 
> PS C:\Users\\[redacted]>  wsl --install -d Ubuntu-20.04
> Installing: Windows Subsystem for Linux
> Catastrophic failure
> PS C:\Users\\[redacted]>
> 
> For me, WSL 2.0 is installed I think. But I can't install any distributions

Hello I am facing the same issue.  Just want to know how did you resolve the issue

**Comment by emmyapi** [comment]
> > > 
> > 
> > 
> > [WslLogs-2022-12-18_00-38-39.zip](https://github.com/microsoft/WSL/files/10252918/WslLogs-2022-12-18_00-38-39.zip)
> > My error message is just:
> > PS C:\Users\[redacted]>  wsl --install -d Ubuntu-20.04
> > Installing: Windows Subsystem for Linux
> > Catastrophic failure
> > PS C:\Users\[redacted]>
> > For me, WSL 2.0 is installed I think. But I can't install any distributions
> 
> Hello I am facing the same issue. Just want to know how did you resolve the issue

I realized it wasn't good enough to "open as administrator". I tried from the admin account, and it worked the first time
