### ISSUE TITLE
Traceroute do not work in WSL2/Ubuntu 

### ISSUE THREAD

**Issue by jhaveDK** [microsoft/WSL#8717]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

traceroute (GNU inetutils) 1.9.4

### Repro Steps

I have upgraded my PC from windows 10 to 11 but now do traceroute not work in WSL2 :( 

### Expected Behavior

traceroute google.com
  1     2 ms    <1 ms    <1 ms  192.168.1.1
  2    46 ms    58 ms     *     xxx.xxx.xxx.xxx
  3     6 ms     9 ms     6 ms  xxx.yyy.zzz [xxx.xxx.xxx.xxx]
  4    15 ms    15 ms    15 ms  google.telecity5.nl-ix.net [193.239.117.141]
  5    16 ms    16 ms    16 ms  108.170.241.237
  6    16 ms    17 ms    16 ms  142.250.46.79
  7    28 ms    28 ms    27 ms  142.250.62.109
  8    28 ms    29 ms    28 ms  216.239.47.207
  9    40 ms    30 ms    30 ms  142.251.51.184
 10    29 ms    29 ms    38 ms  209.85.241.44

### Actual Behavior

**traceroute google.com**
traceroute to google.com (142.250.74.110), 64 hops max
  1   *  *  *
  2   *  *  *
  3   *  *  *
  4   *  *  *
  5   *  *  *
  6   *  *  *
  7   *  *  *
  8   *  *  *
  9   *  *  *
 10   *  *  *

**Comment by NotTheDr01ds** [comment]
As far as I can tell, this is a side-effect of #8610.  It occurs for me on both Windows 10 (21H2) and Windows 11, so perhaps you had an older build of Windows 10 before upgrading.

(At least) two workarounds:

* You can use ICMP via `traceroute -I googe.com`.

* Or, as [mentioned](https://github.com/microsoft/WSL/issues/8610#issuecomment-1197053685) in the original issue, you can turn off transmission checksumming via `sudo ethtool -K eth0 tx off`.  You'll need to repeat this command after each WSL2 restart.

**Comment by OneBlue** [comment]
Thanks for reporting this @jhaveDK. Are you using inbox WSL or store WSL ? 

If you're using inbox WSL, I'd be curious to see if the behavior is different in [store wsl](http://aka.ms/wslstorepage)

**Comment by jhaveDK** [comment]
HI  @OneBlue 

Its the Inbox WSL and Ubuntu from the store. 

But is there a diffrence between the store versions and the inbox versions ?

**Comment by OneBlue** [comment]
@jhaveDK: Yes there are, we've made many networking improvements in the store version, so I'd be curious to see if you still see the same issue in the [store version](http://aka.ms/wslstorepage)

**Comment by jhaveDK** [comment]
@OneBlue yes its the same result, its work fine on W10 but not on W11

**Comment by NotTheDr01ds** [comment]
@jhaveDK Curious if the workarounds above worked for you?

**Comment by jhaveDK** [comment]
> @jhaveDK
> 
> I'm curious -- Did either or both of the workarounds above work for you?

Yes its work both, but its only a quickfix not a final solution :)

**Comment by jhaveDK** [comment]
@OneBlue I do not get its confirmed is a bug or its a local setup problem?
