### ISSUE TITLE
Landing in root user by default

### ISSUE THREAD

**Issue by hdadhich01** [microsoft/WSL#8736]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

22.04

### Repro Steps

* Confirm that your default version of WSL is `2`
* Install Ubuntu from the Windows store
* Click the Ubuntu app tile from the Windows search bar

### Expected Behavior

I will get the "installing distribution" installer window which will properly run everything, and launch a terminal to prompt me for a UNIX username and password.

### Actual Behavior

I am not able to input a UNIX username as every input from my keyboard is invisible on my terminal. However the cursor stops upon every key input, so I thought the output might be invisible. Pressing enter after this doesn't do anything either. However, when I close the terminal tab and relaunch it, I automatically land in `root@[my computer's name]`. I have tried reinstalling and resetting Ubuntu. I have also made sure I am using WSL2 on each instance and that it is up to date through `wsl --update`. I was able to type my own username when I uninstalled Ubuntu, set my default version to WSL1, installed Ubuntu, and set the version back to WSL2.

**Comment by NotTheDr01ds** [comment]
Related to #8737.  In my experience (and from answering a number of Ask Ubuntu questions), the new installer is a bit error prone.  AFAIK, it's written entirely by Canonical (they call it the out-of-box-experience, or OOBE), and bug reports should probably be made on the [Ubuntu Launchpad](https://launchpad.net/ubuntu), but I'm sure a member of the WSL team here can confirm that.

Please see my workaround in #8737.

**Comment by benhillis** [comment]
Agreed, this is an issue with the Ubuntu 22.04 installer and should be reported to Canonical.

**Comment by hdadhich01** [comment]
https://bugs.launchpad.net/ubuntu-wsl-integration/+bug/1987128
