### ISSUE TITLE
Ubuntu with a new installer for WSL 2 not installing in Windows 11

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/WSL#8737]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04.1

### Repro Steps

After installing Ubuntu from store, then a white dialog box appears with no content, but on hover it causes flickering in my screen... Same with my other laptop

### Expected Behavior

The installer should install all the necessary file required in a window asking for username and password at first. 

### Actual Behavior

Empty dialog after installation get completed. Too annoying

**Comment by NotTheDr01ds** [comment]
You have this listed as 20.04, but the new installer with dialog box is only in 22.04.  Assuming that you are installing the "Ubuntu" (unversioned) from the Store, that's now been updated to 22.04.

Anyway, the new, graphical installer is, AFAIK written entirely by Canonical.  They call it their new "Out-of-box Experience" (OOBE).  I believe issues should be filed on their [Launchpad site](https://launchpad.net/ubuntu).

In my opinion, the OOBE is a pretty big step backward.  It's extremely slow compared to the old text-based WSL installer, which only takes 11 seconds on my system.  And the only purposes it serves are:

* Marketing text
* The ability to change a bunch of options that first-time users shouldn't be changing anyway.

You can, fortunately, fall back to the old install process:

* After installing from the Store, *do not select "Open"*
* Instead, close the Store
* Open PowerShell (as a regular, *non*-administrator user) and:
    ```
    ubuntu install --ui=none
    ```

If the graphical installation did not complete successfully, you may need to first remove the distribution with:

```
wsl --unregister Ubuntu
```

Note that this is a destructive operation, so only use it if you have just installed and do not have any user data in the distribution.
