### ISSUE TITLE
Erro na execução do Linux pós instalação

### ISSUE THREAD

**Issue by quinhone** [microsoft/WSL#8738]
Não consigo usar o meu WSL no windows 10, sempre que instalo uma distro, dá esse erro.
Já fiz o procedimento de mudar as permissões da pasta WindowsApp mas não resolveu.

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Acesso negado.

Press any key to continue...

**Comment by microhobby** [comment]
@quinhone você está instalando pela store? Caso positivo tente em um terminal, em modo administrativo, instalar pelo winget.

https://docs.microsoft.com/pt-br/windows/package-manager/winget/

**Comment by quinhone** [comment]
@microhobby Instalei pelo Store e ja tentei pelo terminal, o problema está na pasta WindowsApp, tudo que tento fazer que envolva ela dá acesso negado, como o WSL instala lá, no Store dá como instalado, mas na realidade não instala pq não consegue permissão. Aí quando tento acessar qualquer distro instalada dá acesso negado.
Já entrei na pasta, coloquei permissão, mas não resolveu. Isso ocorre tanto no Windows 10 como no Windows 11.
