### ISSUE TITLE
WSL Interop: cannot execute exe binary file

### ISSUE THREAD

**Issue by jamal** [microsoft/WSL#8749]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

From WSL run `notepad.exe`, `whoami.exe`, etc.

### Expected Behavior

These exes should run as normal

### Actual Behavior

Returns the following error: ```cannot execute binary file: Exec format error```

Examples:
```
$ which notepad.exe
/mnt/c/Windows/system32/notepad.exe
$ notepad.exe
-bash: /mnt/c/Windows/system32/notepad.exe: cannot execute binary file: Exec format error
```

### Diagnostic Logs

Running strace provides the following:
```
$ strace -ff notepad.exe
execve("/mnt/c/Windows/system32/notepad.exe", ["notepad.exe"], 0x7ffd587940b8 /* 27 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
```

WSL_INTEROP appears to be set correctly:
```
$ echo $WSL_INTEROP
/run/WSL/8_interop
$ ls /run/WSL
1_interop  8_interop
```

**Comment by benhillis** [comment]
Can you provide the output of these commands?

```
ben@BENHILL-DEV:~$ ls /proc/sys/fs/binfmt_misc/
WSLInterop  register  status
ben@BENHILL-DEV:~$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

**Comment by jjueljc** [comment]
Ran them and I have:

 ls /proc/sys/fs/binfmt_misc
jar                     llvm-13-runtime.binfmt  python2.7   python3.9  status
llvm-11-runtime.binfmt  llvm-14-runtime.binfmt  python3.10  register
┌─[talon@Office-PC] - [/root] - [Wed Sep 28, 08:20]
└─[$]> ls /run/WSL
2_interop  659_interop
