### ISSUE TITLE
unable to launch ubuntu : ( '{Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f' )

### ISSUE THREAD

**Issue by 0ussamaBernou** [microsoft/WSL#8750]
### Version

Microsoft Windows [Version 10.0.22504.1010]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.57.1

### Distro Version

Ubuntu 20.04

### Repro Steps

executing ubuntu.exe , from a Terminal preview profile.

### Expected Behavior

launch ubuntu terminal

### Actual Behavior

```
{Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f

```

**Comment by 0ussamaBernou** [comment]
[collect-wsl-logs.zip](https://github.com/microsoft/WSL/files/9397856/collect-wsl-logs.zip)

**Comment by MuhammadArslan90** [comment]
hello plz fix this issue in Ubuntu
Wsl/Service/CreateInstance/CreateVm/0x8007000d

my /logs


[collect-wsl-logs.zip](https://github.com/microsoft/WSL/files/9482241/collect-wsl-logs.zip)

**Comment by AnTerNoZ** [comment]
Got the Same Error.

PowerShell
```
PS C:\Users\27> wsl
{Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
PS C:\Users\27> wsl Ubuntu-22.04.1
{Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
PS C:\Users\27> wsl Ubuntu-22.10
{Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
```

Terminal Profile wsl.exe -d Ubuntu-22.10

```
{Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f

[Verarbeitung des Prozesses mit Code 4294967295 (0xffffffff) beendet]
```

When I direct start the "Ubuntu" or "Windows Subsystem for Linux" app, the System loads both Ubuntu Versions.

Logs:
[collect-wsl-logs.zip](https://github.com/microsoft/WSL/files/9489733/collect-wsl-logs.zip)

**Comment by LuXDAmore** [comment]
Same here on Windows 11 ✋🏻

But, from Docker Desktop:
> Failed to deploy distro docker-desktop to C:\Users\lucab\AppData\Local\Docker\wsl\distro: : {Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. 
Error code: Wsl/Service/CreateVm/0x8007023f


[Wsl Logs Zip](https://github.com/microsoft/WSL/files/9506309/WslLogs-2022-09-07_14-49-56.zip)

---

![Docker desktop error](https://user-images.githubusercontent.com/3841171/188882882-dc98521b-fc3b-4f63-bfa0-66275e338f8d.png)

**Comment by IzaGz** [comment]
Have same issue, please help, how to restore the ubuntu and dont lose the data.
[here the person advises not to do unregister its removed all data](https://github.com/microsoft/WSL/issues/5092#issuecomment-1193882805)
please, help to fix this

**Comment by AnTerNoZ** [comment]
> Got the Same Error.
> 
> PowerShell
> 
> ```
> PS C:\Users\27> wsl
> {Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
> Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> PS C:\Users\27> wsl Ubuntu-22.04.1
> {Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
> Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> PS C:\Users\27> wsl Ubuntu-22.10
> {Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
> Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> ```
> 
> Terminal Profile wsl.exe -d Ubuntu-22.10
> 
> ```
> {Fehler in Anwendung} Die Anwendung konnte nicht ordnungsgemäß gestartet werden (0x%lx). Klicken Sie auf "OK", um die Anwendung zu beenden.
> Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f
> 
> [Verarbeitung des Prozesses mit Code 4294967295 (0xffffffff) beendet]
> ```
> 
> When I direct start the "Ubuntu" or "Windows Subsystem for Linux" app, the System loads both Ubuntu Versions.
> 
> Logs: [collect-wsl-logs.zip](https://github.com/microsoft/WSL/files/9489733/collect-wsl-logs.zip)

With Update 22H2 the Error is gone for me!

**Comment by IzaGz** [comment]
Why closed, i tryed everything, nothing helps, please help!

**Comment by 0ussamaBernou** [comment]
> Why closed, i tryed everything, nothing helps, please help! 

I copied my ubuntu files through windows, and reinstalled wsl and ubuntu, then I pasted my files back and it's working well now.

**Comment by Botv0091** [comment]
> Why closed, i tryed everything, nothing helps, please help!

Begin works after update my Windows 11 to 25206.1000 ....  As a fallback, the focus was triggered with a date change to September 14.
