### ISSUE TITLE
-bash: .: filename argument required and .: usage: . filename [arguments] whenever opening new shell window

### ISSUE THREAD

**Issue by BoseSj** [microsoft/WSL#8752]
### Version

Microsoft Windows [Version 10.0.22621.382]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.57.1

### Distro Version

Kali Linux Rolling

### On Windows PowerShell:

```wsl --update```
```wsl --install kali-linux```
![image](https://user-images.githubusercontent.com/58129377/185915697-b763e196-90c3-4731-95a1-afdfa9db7b70.png)

### On Kali Linux Window:
_After inputting new UNIX username and pass >>_

![image](https://user-images.githubusercontent.com/58129377/185916233-c8b526da-773f-4d0c-b82f-a7c8178ff8c3.png)

### Expected Behavior

**The kali-linux distro is successfully installed and runs without any error message every time.**

### Every time when a new kali-Linux window is opening:

![image](https://user-images.githubusercontent.com/58129377/185917499-af87e462-5223-41aa-a292-c29dbbc61ddc.png)

### Previously:
 I was customizing zsh shell in kali. When I encountered some error messages and cant anyway get rid of those, I decided to remove the distro completely.

### Using following steps:

1.  Uninstalled Kali Linux from Apps
2.  Open PowerShell

run: ```wsl -l```

![image](https://user-images.githubusercontent.com/58129377/185926300-e69de7c5-6aa1-4ae8-929f-4791c39e22bb.png)

run: ```wsl --unregister kali-linux```

![image](https://user-images.githubusercontent.com/58129377/185926558-c9953fe0-3c10-45ae-8e2e-30370f3697f2.png)

run: ```wsl -l```

![image](https://user-images.githubusercontent.com/58129377/185926714-53dc596e-ba44-4a71-a68e-baf4bd7a5bee.png)

### Then:
I reinstalled the kali-linux again using ```wsl --install kali-linux``` command. And started facing this error. 
I have tried again to uninstall and reinstall but the issue persists.

![image](https://user-images.githubusercontent.com/58129377/185927530-2dedbf0d-16ba-4867-84dc-167dce7839e6.png)

**Comment by BoseSj** [comment]
When I delved more into this, I found out there is an error in ```/etc/profile``` file in the shell at a certain line. I could fix the issue by adding ```$i``` in a line after a ```.```  as seen in other distros' same file.

![image](https://user-images.githubusercontent.com/58129377/185930603-4b0ec1b0-f9b6-4590-a541-330da8c890d0.png)

The issue is solved temporarily, but further, down the road, it introduces more errors. For example, when I try to reset the Kali Linux app, it'd not reset back to its first state but would not run anymore. Then I would go into further error checking and go into solving the further issues.

**Comment by benhillis** [comment]
If this is an issue in the /etc/profile file of Kali's distribution, that file is owned by the Kali team.

**Comment by NotTheDr01ds** [comment]
A few notes:

* Good find on the `/etc/profile` bug.  Would recommend filing a bug report for the Kali Team.  Please see [Submitting Bugs for Kali Linux](https://www.kali.org/docs/community/submitting-issues-kali-bug-tracker/).
* Also might want to bring up the other issues either in a discussion or in questions on [Super User](https://superuser.com) or the [Unix & Linux Stack Exchange](https://unix.stackexchange.com).  We can try to sort them out to the point where we either (a) have solutions for them, and/or (b) have enough info to report additional bugs to the Kali team.

**Comment by NotTheDr01ds** [comment]
Note that the `/etc/profile` in the new Kali update is foobar in more ways than just this.  It appears to me to be some type of issue with a build tool improperly quoting/escaping, so multiple items have been lost:

* Backquotes
* Other variables
* Some items that should be variables have been replaced with the hardcoded results from the build system.

Here's the `/etc/profile` from the 2019.something release of Kali for comparison.  I don't think any changes were made to the file that were *intentional* - It's just that the results have been unintentionally interpolated:

```
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

IS_WSL=`grep -i microsoft /proc/version` # WSL already sets PATH, shouldn't be overridden
if test "$IS_WSL" = ""; then
  if [ "`id -u`" -eq 0 ]; then
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  else
    PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
  fi
fi
export PATH

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```

What worries me is that there may be *other* files which were also corrupted in the 2022.3 Kali release for WSL that we haven't found yet.

**Comment by BoseSj** [comment]
Yes, I bet there are a few. While exploring this one problem I faced many other different issues when reinstalling it multiple times. But this one particular issue is what persisted till the end. I have transferred to Ubuntu for a few days now. I hope these are only _kali wsl_ issues, but not the issue of kali distro _as a whole_.

**Comment by nbow2** [comment]
Check your shell config files (.bashrc, .profile, or .bash_profile) for a bad line like:
.

Run this command to find it:

grep -n '^\.\s*$' ~/.bashrc ~/.profile ~/.bash_profile 2>/dev/null

Then edit the file and remove the line:

nano ~/.bashrc

Save and restart the terminal.
