### ISSUE TITLE
WSL2  doesn't support the scrollback when the command outputs are large

### ISSUE THREAD

**Issue by madhurnitc** [microsoft/WSL#8753]
### Version

Microsoft Windows [Version 10.0.19042.1826]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1237-Microsoft Sat Sep 11 14:32:00 PST 2021

### Distro Version

Ubuntu 22

### Repro Steps

Just run any command where the output of the command doesn't fit the WSL window size.
There is no scrollbar to scroll up or down.

The previous bugs have been closed saying that they might have been fixed. 

The History Size setting in WSL  doesn't seem to work either

### Expected Behavior

There should be a scroll back to allow you scroll back/forth based on history size.

### Actual Behavior

No way of scrolling back/forth.

**Comment by NotTheDr01ds** [comment]
A couple of notes:

* First, you have "WSL 2" checked in your issue report, but the kernel that you are using indicates that you are using WSL 1.  You should confirm with `wsl -l -v`.  That shouldn't matter for the issue you are having, though.

* Second, the scrollbar is a feature of the terminal.  It sounds like you are using the legacy Windows Console Host.  You might want to try Windows Terminal, the replacement from Microsoft.  It's:

    * Installable from the Microsoft Store
    * Actively developed
    * [Open source](https://github.com/microsoft/terminal)
    * Feature rich (tabs, profiles, and much more)


* And
    > The previous bugs have been closed saying that they might have been fixed.

    While I'm not sure if the issue you are having is necessarily fixed or not, you say you are running 10.0.19042.1826.  There have been at least two releases of Windows 10 (which includes both WSL and the Console) that I'm aware of since then.  It's very possible that, if this particular issue is fixed, then it's is in one of those releases, and you'll need to upgrade.

    Also my understanding is that release is no longer actively supported.
