### ISSUE TITLE
Missing WSL Blob Links for AlmaLinux Packages

### ISSUE THREAD

**Issue by saenzfco** [microsoft/WSL#8762]
Hi there -

Could you update the list in the [Downloading distributions](https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions) section to include links to AlmaLinux packages?  Thank you!

**Comment by Biswa96** [comment]
Duplicate of https://github.com/microsoft/WSL/issues/8634.

**Comment by benhillis** [comment]
Agreed, submit a PR!
