### ISSUE TITLE
WSL2 mount option in windows 10 is still possible?

### ISSUE THREAD

**Issue by reisraff** [microsoft/WSL#8766]
**I would like to use the mount option in windows 10**
Reading this [article](https://blogs.windows.com/windows-insider/2020/09/10/announcing-windows-10-insider-preview-build-20211/) we see that for Windows 10 Insider Preview Build 20211 we can use the mount option of the wsl2.

Today I can't install Windows 11 because of my chip that is not supported. So I have upgraded to Windows 10 pro and joined in the insider program as well to get this build. 

But I can't install this. Today my version is:
Windows10 pro Version 22H2 (OS Build 19045.1947), there is no more updated after this.

Is there something I am missing? Or is there another way to get this mount feature? Could anyone help me?

**Comment by NotTheDr01ds** [comment]
> Reading this [article](https://blogs.windows.com/windows-insider/2020/09/10/announcing-windows-10-insider-preview-build-20211/) we see that for Windows 10 Insider Preview Build 20211 we can use the mount option of the wsl2.

Windows 10 Insider builds from the time period when that article was written ultimately became Windows 11.  Any Insider builds from that time have expired and are no longer available for download or installation.  Any current Windows 10 Insider build, to my knowledge, do not have this feature.

From the [current (not Preview) doc](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk):

> You will need to be on Windows 11 Build 22000 or later to access this feature.

However, there's an *outdated message* there about joining the Insiders program to get access to the latest preview builds.  I filed a [doc issue](https://github.com/MicrosoftDocs/WSL/issues/1574) on the topic, but I really need to do a PR to get it updated.

Perhaps a member of the WSL team can provide some other information that I'm not aware of, but I just don't have much good news for you here.  The feature is simply only available in Windows 11.

I personally don't expect many (or any) of the Windows 11 WSL features to be backported to Windows 10 at this point.  The same release that brought in `--mount` also included WSLg, which according to previous Microsoft posts relies on new functionality that is only available in Windows 11.

What's your use-case for needing `--mount`?  Perhaps there's a workaround (VM maybe?) that can help accomplish the task.

**Comment by reisraff** [comment]
I'd like to mount my ext4 partition natively without third party software or even VM.

Want to work in both windows and linux at the same time, but having available my partition that I use in the dual boot.

I think I will by pass the unsupported hardware meanwhile I don't by a supported chip... Since I have an i7 7700HQ and saw couple of videos and there is no one saying it has bug.

**Comment by Biswa96** [comment]
> Is there something I am missing?

If you really need `--mount` option with wsl.exe you can install Windows 11 alongside Windows 10 in unsupported hardware.
