### ISSUE TITLE
Cannot launch Ubuntu 20.04 WSL on Windows Server 2019 Datacenter Evaluation

### ISSUE THREAD

**Issue by axg-shawn** [microsoft/WSL#8768]
### Version

Windows Server 2019 Datacenter Evaluation ver 1809 build 17763.3346

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

I logged in windows by user 'Administrator', and I followed instructions below to install WSL on Windows Server 2019 Datacenter **_Evaluation_** ver 1809 build 17763.3346.
https://docs.microsoft.com/en-us/windows/wsl/install-on-server#install-wsl-on-previous-versions-of-windows-server

While I launched the WSL and I got error description "Program 'ubuntu.exe' failed to run: Access is deniedAt line:1 char:1".
![image](https://user-images.githubusercontent.com/112071365/186696451-952484d6-2358-454c-8c16-014ca5112961.png)

WSL Ubuntu distribution I installed is CanonicalGroupLimited.UbuntuonWindows_2004.2021.825.0.AppxBundle.
https://aka.ms/wslubuntu2004

Any idea or thought on this issue?
Is windows server 2019 evaluation version limited to WSL feature? Should I use a full version, not evaluation version?

### Expected Behavior

Launch WSL Ubuntu 20.04 successfully and entered e.g. CLI terminal.

### Actual Behavior

"Program 'ubuntu.exe' failed to run: Access is deniedAt line:1 char:1".
![image](https://user-images.githubusercontent.com/112071365/186700802-35f840fe-f99e-4240-8bda-71e851a0b7ec.png)

**Comment by sirredbeard** [comment]
What happens if you just run `wsl.exe -d <distroname>`?

**Comment by axg-shawn** [comment]
Thanks sirredbeard
It didn't work to run `wsl.exe -d <distroname>`

I followed Microsoft's instruction to run PowerShell cmd `Add-AppxPackage .\app_name.appx` and it will install WSL to the protected WindowsApps folder.

My colleague helped me managing to get this fixed with steps below

1.	Uninstalled Ubuntu from Control Panel.
2.	Unzipped ubuntu2004.appx package to expose contents.
3.	Unzipped Ubuntu_2004.2021.825.0_x64.appx into C:\Program Files\Ubuntu (since after the next step, Ubuntu installation will be wherever you execute Ubuntu.exe from)
