### ISSUE TITLE
Error when i up the docker-compose using `docker-compose up -d`

### ISSUE THREAD

**Issue by caioeserpa** [microsoft/WSL#8770]
### Version

Microsoft Windows [versão 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

$ docker compose up -d
<3>init: (9182) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9183) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9184) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9185) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9186) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9187) ERROR: UtilConnectUnix:467: connect failed 111
<3>init: (9188) ERROR: UtilConnectUnix:467: connect failed 111
[+] Running 0/0
 ⠋ postgres Pulling                                                                                                                   0.0s
 ⠋ redis Pulling                                                                                                                      0.0s
 ⠋ airflow-scheduler Pulling                                                                                                          0.0s
 ⠋ airflow-worker Pulling                                                                                                             0.0s
 ⠋ airflow-init Pulling                                                                                                               0.0s
 ⠋ airflow-webserver Pulling                                                                                                          0.0s
 ⠋ airflow-triggerer Pulling                                                                                                          0.0s
error getting credentials - err: exit status 255, out: ``

### Expected Behavior

updating my docker compose

### Actual Behavior

i got an error when i tried to updating my docker compose using wls2

**Comment by NotTheDr01ds** [comment]
This is likely *not* a WSL *issue*, but you'd need to provide more info to be sure.  As submitted, it's unfortunately simply not going to be possible for anyone else to reproduce your issue using just `docker compose up -d`.

Can you provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) (MRE) of a `dockerfile`, `docker-compose.yaml`, and any other necessary files to reproduce the problem?

Did the command work at some point and then stop?  Or has it never worked?

The more relevant details that you can provide, the better the chances of getting help!
