### ISSUE TITLE
ssh: Could not resolve hostname \342\200\223v name or service unknown 

### ISSUE THREAD

**Issue by NoSubstitute** [microsoft/WSL#8775]
### Version

Microsoft Windows [Version 10.0.19044.1889]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.1

### Repro Steps

When I start Terminal I have WSL Ubuntu as default shell, and it autostarts sshd (/etc/init.d/ssh).
I then get an error message complaining about not being able to resolve hostname.
It completes the start and works just fine, but it's annoying to get an error message on every start and restart of WSL.

The error message only occurs on boot of WSL. Not when restarting sshd when WSL is already running.

If this had been when trying to connect to the sshd, I have found other people suggesting there's an incorrect - somewhere on the command line, but I am only starting the daemon. I have also gone through all files I can find that are related to sshd, and there are no broken characters what I can see.

### Expected Behavior

sshd should just start without the error message.

### Actual Behavior

Starting SSH server:
ssh: Could not resolve hostname \342\200\223v: Name or service not known
 * Stopping OpenBSD Secure Shell server sshd                                                                     [ OK ]
 * Starting OpenBSD Secure Shell server sshd                                                                     [ OK ]

$ sudo service ssh status
[sudo] password for MyUser:
 * sshd is running

Connecting to it works fine.

$ ssh MyUser@127.0.0.1 -p 22
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)

**Comment by elsaco** [comment]
`\342\200\223` is octal for `0xE2 0x80 0x93` which is the `En Dash` in UTF-8 (U+2013). You might be using the wrong hyphen character somewhere in your config files.

**Comment by NoSubstitute** [comment]
Hi, Tux.
Yes, that much I have learned, but I can't for the life of me find which
config file it is referring to, and as I said, in many of them, I have
already manually replaced all dashes I could find.

**Comment by NoSubstitute** [comment]
Found it!
Part of the start-up of the sshd I had "ssh -V" and that hyphen was wrong.
Replaced with proper - and all is good now. Closing this.
