### ISSUE TITLE
Ubuntu WSL graphical setup fails.

### ISSUE THREAD

**Issue by MiniFlames** [microsoft/WSL#8778]
### Version

10.0.22621.457

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 22.04.1

### Repro Steps

- Install WSL from store.
- Install 'Ubuntu' from store.
- 'Open' Ubuntu to run graphical setup.

### Expected Behavior

- Setup utility decompresses image
- Setup proceeds to user creation window
- Everything's good and working

### Actual Behavior

- Setup completes decompressing image.
- Setup spits out a bunch of errors [invisible to the end user if they don't click to show the console log]
_I wasn't able to capture the full output of the errors because the setup utility doesn't seem to allow copying the output, this screencap is the best I could do -_ 
![unknown](https://user-images.githubusercontent.com/7881404/187210415-0f71bae9-3c1f-4c33-a93e-ccd4df852a56.png)

- Setup prompts you to continues as if nothing has failed
- User creation step hangs/doesn't complete/spins its wheels indefinitely

If you exit/close at the user creation step before creating the user it seems to fallback to the old cli user creation method which works fine as far as I can see.

Collected WSL logs using the instructions provided - unsure of what utility they will be:

[WslLogs-2022-08-29_14-09-31.zip](https://github.com/microsoft/WSL/files/9444820/WslLogs-2022-08-29_14-09-31.zip)

**Comment by Biswa96** [comment]
Please report the issue here https://github.com/ubuntu/WSL/issues. The issue is specific to Ubuntu installer and not part of system WSL.
