### ISSUE TITLE
OpenAFS Unusable

### ISSUE THREAD

**Issue by bazald** [Microsoft/WSL#878]
After apt-get installing `krb5-auth-dialog krb5-user libpam-afs-session libpam-krb5 openafs-client openafs-krb5 openafs-modules-dkms`, I (foolishly) expected to be able to run `/etc/init.d/openafs-client start` successfully.

Of course, the message I receive is:

```
Starting AFS services:
AFS module /lib/modules/3.4.0+/fs/openafs.ko does not exist.
Not starting AFS.  Please consider building kernel modules using
instructions in /usr/share/doc/openafs-client/README.modules
```

I understand that there is no Linux kernel and therefore(?) there are no kernel headers to allow the module to be built. I'd like to know if there's any way that such a module could be provided, or if there's an alternative method for connecting to AFS from the Linux userspace (i.e. possibly indirectly through the Windows version, for example).

**Comment by fpqc** [comment]
The difficulty is that the Kernel-mode API of WSL is under heavy development, and has therefore neither been documented nor have headers been developed for compilation of such drivers nor would such headers allow you to just compile those kernel modules.  Moreover, it seems like it would be very hard to maintain given the fact that Linux's kernel-mode ABI is not a stable target and can move at any time.  

It may be possible one day if/when MS releases a WSL driver SDK and documentation for WSL (which could be as easy as allowing an NT kernel driver to be exposed as a WSL object in /dev or /proc or /sys or whatever.  However, you will likely not be able to compile such a driver using the Linux code directly.  Likely you would need to port it in the difficult way (or maybe cygwin has developed some kind of way to cross-compile Linux kernel modules and drivers for Windows) in that case.  I guess it will be possible in the future, but right now if you need a kernel-mode module or driver, you are out of luck.

**Comment by therealkenc** [comment]
#1893
