### ISSUE TITLE
`wsl --help | more` outputs one character per line

### ISSUE THREAD

**Issue by countingpine** [microsoft/WSL#8785]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

Open a Command Prompt or PowerShell, and run `wsl --help | more`

### Expected Behavior

```
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

(...)
```

### Actual Behavior

```
C
o
p
y
r
i
g
h
t

(
c
)
(...)
```

**Comment by NotTheDr01ds** [comment]
Looks like the same as #4456, which although still open is really the same root-cause as #4607 (closed with workaround).
