### ISSUE TITLE
wsl import does not complete (for some container tar images)

### ISSUE THREAD

**Issue by macton** [microsoft/WSL#8787]
### Version

Windows version: 10.0.22622.586

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.57.1

### Distro Version

N/A

### Other Software

Image built with Docker version 20.10.17, build 100c701

### Repro Steps

No reliable repro atm. I can however provide a tar image that will repro the issue if someone wants to give me a place to upload it.

### Expected Behavior

wsl --import should complete in a reasonable span of time, or a least a human lifetime.

### Actual Behavior

wsl --import does not complete for /some/ tar container images. (import unfinished after 12 hours.)

Workaround has been to change the image and rebuild. 

Best guess to cause is internally to wsl there's some search or sort that gets triggered under certain conditions and is pathologically slow. I can provide an example tar image and someone on wsl team with a debugger and a profiler should be able to see where it's spending all the time.

**Comment by Biswa96** [comment]
So far only size is the limit for importing a distribution in WSL2. More or less 1 GB sized tarball is ideal.

**Comment by macton** [comment]
Someone needs to open wsl up in a profiler. Size *may* be a limitation, but it's only that at smaller sizes you're less likely to trigger this issue. It's certainly possible to successfully import much larger containers in wsl when whatever issue this is isn't triggered.

**Comment by NotTheDr01ds** [comment]
My understanding is that `wsl --import` is using, at the core, `bsdtar`.  You might try extracting the problematic tarball using `/mnt/c/Windows/System32/lxss/tools/bsdtar` and see if you encounter any errors or hints as to what's going wrong in `--import`.

**Comment by macton** [comment]
@NotTheDr01ds Thanks for the idea. ```bsdtar``` has no problem extracting it. (Of course not - hard to imagine something more battle tested than tar.) But now I wonder if I can workaround by making a ext4.vhdx image myself and trying to get that to import somehow.

**Comment by NotTheDr01ds** [comment]
@macton Very interesting, and odd.  Glad you have a workaround, at least!

Where did the tarball come from, out of curiosity?  I'm assuming it's not a from a `wsl --export` of an existing distro, since you could have just reused the `ext4.vhdx` in that case.  I'm also assuming it wasn't downloaded from some source, or you'd probably just point us to that source to test.

**Comment by damnkiwi6120** [comment]
I've encountered the same problem, and I workaround the problem by using the new `--vhd` import/export argument. I didn't notice this argument before, so I guess it's being add in recent updates.

**Comment by TerminatedProcess** [comment]
OMG the --vhd option is so fast. Yes it does create very large backups. I've been having a persistent issue with restoring tar files for a while now. One time a specific backup works, the next it doesn't. Just spins forever. Thanks for the tip on the --vhd option. Here is some example calls for anyone just encountering this option. 

Where c:\wslbackup is where I'm keeping my backups and..
c:\wsl2distros is where I'm keeping my active distros.

wsl --export Ubuntu C:\wslbackups\<yourfilename>.vhdx --vhd
wsl --import Ubuntu c:\wsl2distros C:\wslbackups\<yourfilename>.vhdx --vhd

**Comment by Biswa96** [comment]
If you are using latest WSL Preview from Windows Store there is an option `wsl.exe --import-in-place` to take an existing .vhdx file and register it as a distro.

**Comment by troy-mac** [comment]
Call me blind or dumb, but I do not see the --vhd switch in command prompt or PowerShell.  My Windows updates are recent as of today.   I have tried using it and when using it I get the Usage: wsl.exe [Argument] [Options...] [CommandLine] error and in the help there is no --vhd switch.  @TerminatedProcess can you point me in the direction to get this?

**Comment by NotTheDr01ds** [comment]
@troy-mac It's a new feature, so it's only available in:

* Preview releases (available from the Microsoft Store or the [Releases](https://github.com/microsoft/WSL/releases) page in this repo.
* Potentially (I don't know yet) Windows 11 22H2 that was just released.

Either way, like all new WSL features, it does require Windows 11.

**Comment by troy-mac** [comment]
Thanks NotTheDr01ds, I took a different approach, 

- I installed a sacrificial Ubuntu distro on my new laptop
- copied my ext4.vhdx file from my old laptop to new laptop
- found the ext4.vhdx file on my new laptop that was created from the installation of the sacrificial Ubuntu distro
- in PowerShell ran wsl --shutdown
- deleted the new sacrificial ext4.vhdx 
- copied my ext4.vhdx that was on my old laptop to the new laptop location (replacing the sacrificial ext4.vhdx file)
- In PowerShell, type WSL to start the distro
- Opened terminal and bam got my old WSL distro

**Comment by NotTheDr01ds** [comment]
@troy-mac Excellent - That'll definitely work as well, and was my recommendation on a Stack Exchange answer back some time before the `--mount` and `--vhd` options were available.

**Comment by TerminatedProcess** [comment]
@troy-mac  I am using a Windows 11 dev channel release. But just to make sure, have you tried doing a wsl --update?

**Comment by ngmariusz** [comment]
I have also experience this issue; wsl --update didn't work for me but I figure out I have 'space' in path. When I simplified situation by renaming folders and image file, it worked. Strange, i guess or just trying fifth time got me lucky ;)

**Comment by z357904947** [comment]
I exported the container as a tar file using Docker and encountered the same issue when importing it into WSL. The commands are as follows:
``
docker export fce8ddd692d2 > C:\wsl\opentest.tar
wsl --import openwrttest C:\wsl\openwrttest\ `C:\wsl\opentest.tar`
``
