### ISSUE TITLE
WSL not updating to latest release version

### ISSUE THREAD

**Issue by Anutrix** [microsoft/WSL#8798]
### Version

Microsoft Windows [Version 10.0.22000.918]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Kali GNU/Linux Rolling 2022.3

### Repro Steps

1. Open a terminal.
2. Run `wsl --update`. See following response.
```
> wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.102.1
```

### Expected Behavior

Should update to latest WSL version:  Currently https://github.com/microsoft/WSL/releases/tag/0.66.2.
[0.65.1](https://github.com/microsoft/WSL/releases/tag/0.65.1) has kernel version 5.15.57.1 so 0.66.2 should be that or newer.

### Actual Behavior

Says there's no update.
5.10.102.1(current kernel) is older than 5.15.57.1(0.65.1) so there should be an update.

**Comment by OneBlue** [comment]
Thanks for reporting this @Anutrix. It looks like you're using the Inbox version of WSL. 

To get WSL 0.66.2, you need to install the [Store version of WSL](http://aka.ms/wslstorepage)

**Comment by Anutrix** [comment]
That named Windows Subsystem for Linux Preview but WSL is in preview so that makes sense.

But is migrating from Inbox version to Store version as simple as installing it from the Store?
How is it different from the [.msixbundle](https://github.com/microsoft/WSL/releases/download/0.66.2/Microsoft.WSL_0.66.2.0_x64_ARM64.msixbundle) on the github release page?

A documentation note regarding if added would be helpful too. I only see this "Inbox" version mentioned in some Issues but not in any documentation or notes.

Thx.

**Comment by OneBlue** [comment]
@Anutrix: Those two things are actually the same. If you install WSL via the store it will end up downloading the same .msixbundle as the ones published on Github.

**Comment by Anutrix** [comment]
Just a note to people for who might stumble upon this in the future:
After updating to Windows 22H2, I ran `wsl --update` which somehow worked and installed the latest version(from the Store), even though I had Inbox version of WSL before the upgrade.

**Comment by MukulAJoshi** [comment]
- Updated to the latest Windows 22H2
- `wsl --update` gives the same information note above, since it seems to be the "inbox" version
- Trying to update from the store version, gives the below error  :
- "Windows version 10.0.19045.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue..._"
