### ISSUE TITLE
wsl --install and cannot reboot the computer without recover or reset the window agian

### ISSUE THREAD

**Issue by BYK82** [microsoft/WSL#8800]
### Version

Microsoft Windows [ver

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

once restore Windows 11 pro to my workstation, I installed Nvidia GPU driver for RTX A6000 and wsl --install to the cmd. (tried to the powershell as well.)  
I also checked it is the latest update and the turn on the windows feature and the vm is on. 
windows software shop is working well.

But whenever i rebooted the computer after wsl --install, it goes to recover mode.

### Expected Behavior

After install wsl --install, should be rebooted and installed it.

### Actual Behavior

Cannot boot the computer at all. unless reinstalling windows.

### Diagnostic Logs

Since i couldn't boot my workstation, i couldn't see the diagnostic logs but recovery section.

**Comment by owned139** [comment]
Which network adapter are you using? Intel?

**Comment by BYK82** [comment]
Using amd! I downgraded windows11 to 10. It seems working. 


> 2022. 9. 6. 오후 6:31, owned139 ***@***.***> 작성:
> 
> Intel?

**Comment by mich2k** [comment]
Sadly has not been addressed in 3 years and won't be done now for sure

Downgrading is not a fix
