### ISSUE TITLE
Upgrading to ubuntu kinetic installs systemd and systemd-resolved which messes up resolving sites.

### ISSUE THREAD

**Issue by mpotane** [microsoft/WSL#8801]
### Version

Microsoft Windows [Version 10.0.22000.856] 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.10

### Repro Steps

Upgrade to Ubuntu Kinetic

### Expected Behavior

/etc/resolv.conf should be managed by wsl. 

### Actual Behavior

/etc/resolv.conf is turning red for some reason. Means some program interfering and overwriting the file.

**Comment by mpotane** [comment]
I can now resolve sites after removing /etc/resolv.conf and maybe after stopping systemd-resolved service (unlikely because systemd is disabled).

**Comment by elsaco** [comment]
When `systemd-resolved` package is being update (and if you use `Kinetic Kudu` there are daily updates) the package overrides `/etc/resolv.conf` provided by WSL.

From package description:

```
 Installing this package automatically overwrites /etc/resolv.conf and switches
 it to be managed by systemd-resolved.
```

Because `systemd` is not available on WSL, not officially yet, you end up with a broken resolver.

**Comment by mpotane** [comment]
The newest update for systemd and systemd-resolved appears to have fixed the problem. We will now close this issue.
