### ISSUE TITLE
Get WSL2 IP address

### ISSUE THREAD

**Issue by bablenaferenc** [microsoft/WSL#8804]
### Version

Microsoft Windows [Version 10.0.19044.1949]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 20.04

### Repro Steps

In windows power shell:

`((wsl hostname -I) -split " ")[0]`

### Expected Behavior

I expect get a valid IP address from WSL.

### Actual Behavior

I get an invalid IP address. Not respond to ping.

### Diagnostic Logs

```
PS C:\> ((wsl hostname -I) -split " ")
172.18.2.231
172.27.0.1
172.19.0.1
172.25.0.1
172.23.0.1
172.26.0.1
172.20.0.1
172.22.0.1
172.18.0.1
172.21.0.1
172.24.0.1
172.29.0.1
172.17.0.1

PS C:\> ((wsl hostname -I) -split " ")[0]
172.18.2.231
PS C:\> ping 172.18.2.231

Pinging 172.18.2.231 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.18.2.231:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by netdjw** [comment]
+1

**Comment by bablenaferenc** [comment]
After a restart I got this:
```
PS C:\> ((wsl hostname -I) -split " ")
172.30.45.15
172.24.0.1
172.29.0.1
172.21.0.1
172.25.0.1
172.17.0.1
172.20.0.1
172.22.0.1
172.27.0.1
172.26.0.1
172.18.0.1
172.19.0.1
172.23.0.1

PS C:\> ((wsl hostname -I) -split " ")[0]
172.30.45.15

PS C:\> ping 172.30.45.15

Pinging 172.30.45.15 with 32 bytes of data:
Reply from 172.30.45.15: bytes=32 time<1ms TTL=64
Reply from 172.30.45.15: bytes=32 time<1ms TTL=64
Reply from 172.30.45.15: bytes=32 time<1ms TTL=64
Reply from 172.30.45.15: bytes=32 time<1ms TTL=64

Ping statistics for 172.30.45.15:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**Comment by elsaco** [comment]
When a WSL instance is being run, the host creates a network endpoint that is shared by all WSL instances. However, the endpoint is being destroyed when there are no active WSL instances. So, if ping didn't work might be because the endpoint was terminated already. Use `Get-HnsEndpoint` for details, must be run as administrator.

Also, the `-I, --all-ip-addresses` option says `Do not make any assumptions about the order of the output`. The IP at index zero might not be what is expected!

**Comment by netdjw** [comment]
@elsaco It's possible the WSL terminating immediately after it is started and WSL console is open? I think not (if the "terminated" mean same thing like in Linux terminated).

And my question is: how can we detect the actual IP address of WSL after it's started?

**Comment by elsaco** [comment]
A quick way to get the WSL instances IP address is to run `(get-hnsendpoint).ipaddress` in an elevated powershell session. Example:

```
 PS C:\Users\elsaco> (get-hnsendpoint).ipaddress
 172.20.200.116
```

This IP is assigned to `eth0`:


![wsl_ip_example](https://user-images.githubusercontent.com/3933920/188909088-127792b6-16ac-4c59-97cc-dda81a334b55.PNG)

**Comment by netdjw** [comment]
I tried to use your suggestion:

```
PS C:\Users\netdjw> (get-hnsendpoint).ipaddress
172.20.9.71
PS C:\Users\netdjw> ping 172.20.9.71

Pinging 172.20.9.71 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.20.9.71:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
Any idea?
