### ISSUE TITLE
BSOD with error code MEMORY_MANAGEMENT whenever I exit jshell using Ctrl+D

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/WSL#8805]
### Version

Windows version: 10.0.22000.918

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Kernel version: 5.15.57.1

### Distro Version

Debian 11

### Other Software

JDK

### Repro Steps

* download and unpack https://download.oracle.com/java/18/archive/jdk-18.0.2_linux-x64_bin.tar.gz
* run `bin/jshell`
* press Ctrl+D

### Expected Behavior

Clean exit

### Actual Behavior

BSOD with stop code MEMORY_MANAGEMENT

### Additional Information
This might be a duplicate of https://github.com/microsoft/WSL/issues/8574 but since the stop code is different, I'm filing a new issue

**Comment by DesktopECHO** [comment]
Looks like https://github.com/microsoft/WSL/issues/7480 but that's for WSL1
Try updating your Windows 11 install to 22h2 and see if the issue persists.

**Comment by anthonyvdotbe** [comment]
After upgrading to 22H2, this works as expected. Thanks for the tip.
