### ISSUE TITLE
{Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application. Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f

### ISSUE THREAD

**Issue by lanyuer** [microsoft/WSL#8807]
### Version

Microsoft Version [10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-20.04

### Repro Steps

Cannot reboot wsl2, it tells:

{Application Error} The application was unable to start correctly (0x%lx). Click OK to close the application.
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007023f

### Expected Behavior

Should be started successful

### Actual Behavior

![image](https://user-images.githubusercontent.com/5697909/188800009-ec96b9f1-8f70-4303-98fc-ca0ef2e36088.png)

### Diagnostic Logs

[WslLogs-2022-09-07_13-53-08.zip](https://github.com/microsoft/WSL/files/9503095/WslLogs-2022-09-07_13-53-08.zip)

**Comment by lanyuer** [comment]
Fixed when I update 'Windows Subsystem for Linux Preview'

**Comment by lanyuer** [comment]
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:346: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:350: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:523: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:532: Create process not expected to return

**Comment by nlundquist** [comment]
I am also experiencing this bug.

**Comment by LikeGhost** [comment]
> Processing fstab with mount -a failed.
> 
> <3>WSL (8) ERROR: CreateProcessEntryCommon:346: getpwuid(0) failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:350: getpwuid(0) failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:523: execvpe /bin/sh failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:532: Create process not expected to return

Maybe you can set the default wsl to ubuntu or other system you needed by using the order `wsl --set-default <Name>`.
Because you may use the docker based wsl and the docker for windows has set the defalut wsl as docker-desktop-data.
You can use `wsl --list` to check.
I got the message from the other issue #5923.
I hope it was helpful for you!

**Comment by LikeGhost** [comment]
OK，I'm sorry I couldn't help you

**Comment by eternalphane** [comment]
As stated in #8750, this issue seems to be fixed in 22H2. However, I can't upgrade to this version since a safeguard hold is on my device. A temporary workaround would be to backup `C:\Windows\System32\wsl.exe` and make a symlink targeting `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\wsl.exe`.

**Comment by caiqi** [comment]
Same problem here. `wsl --set-default <Name>` works.

> > Processing fstab with mount -a failed.
> > <3>WSL (8) ERROR: CreateProcessEntryCommon:346: getpwuid(0) failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:350: getpwuid(0) failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:523: execvpe /bin/sh failed 2 <3>WSL (8) ERROR: CreateProcessEntryCommon:532: Create process not expected to return
> 
> Maybe you can set the default wsl to ubuntu or other system you needed by using the order `wsl --set-default <Name>`. Because you may use the docker based wsl and the docker for windows has set the defalut wsl as docker-desktop-data. You can use `wsl --list` to check. I got the message from the other issue #5923. I hope it was helpful for you!
