### ISSUE TITLE
Unable to resize vhdx file from diskpart: File is encrypted

### ISSUE THREAD

**Issue by EllyptiumOfficial** [microsoft/WSL#8814]
### Version

Microsoft Windows [Versión 10.0.22000.918]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

`wsl --install -d Ubuntu`

After ubuntu download+installation, follow [https://docs.microsoft.com/en-us/windows/wsl/vhd-size](url) 

On Diskpart (running as an admin), after selecting vdisk and file properly, type `expand vdisk maximum=XXXXXX`

After that, DISKPART says file is encrypted and the user doesn't has the abbility to decrypt it. 

### Expected Behavior

Expected to get no error

### Actual Behavior

File is encrypted, couldn't find any info, docs don't expect this to happen

**Comment by OneBlue** [comment]
Thanks for reporting this @EllyptiumOfficial.

Have you tried [Resize-Vhd](https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=windowsserver2022-ps) ? This should be the best tool to do this

**Comment by EllyptiumOfficial** [comment]
> Thanks for reporting this @EllyptiumOfficial.
> 
> Have you tried [Resize-Vhd](https://docs.microsoft.com/en-us/powershell/module/hyper-v/resize-vhd?view=windowsserver2022-ps) ? This should be the best tool to do this

User doesn't have permission (encrypted)

**Comment by L53317** [comment]
When I want to release some unused space, I get the same problem.
Some more detail:
I move the Ubuntu 20.04 from the system disk(C:) to "\D:" in Windows11's application board(application list).
I use Optimize-VHD and the diskpart tool, and after trying both of these methods, the system says that the selected file is encrypted and the user doesn't have the ability to decrypt it.
I can use these two tools to compact other ext4.vhdx files (in the system disk, related to Docker), although there was some other problem.

**Comment by goggle555** [comment]
I suffer from the same problem. When I try to optimize the capacity of the VHDX after shutting down WSL in PowerShell, which I launched with administrative privileges, I get an error that the file is encrypted and can not be opened.
```
PS ~\VhdxPath> wsl --shutdown
PS ~\VhdxPath> gci

    Directory: ~\VhdxPath

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            4/3/2023 12:38 AM   109415759872 ext4.vhdx

PS ~\VhdxPath> Optimize-VHD -Path .\ext4.vhdx -Mode full
Optimize-VHD: Failed to compact the virtual disk.
Failed to open attachment '~\VhdxPath\ext4.vhdx'. Error: 'The specified file is encrypted and the user does not have the ability to decrypt it.'.
```

**Comment by FosanzDev** [comment]
> I found the reason after a lot of Googling. This is because the default installation of WSL is installed in the data folder of UWP, and the files in it are encrypted. The solution is very simple, first execute `wsl --export <Distro> <FileName>` to export WSL, then execute `wsl --import <Distro> <InstallLocation> <FileName>` to import  WSL back, where `<InstallLocation>` should be specified as the folder that is not encrypted. 

Seems to be the solution since I also saw it's encrypted. I'll try it and close the thread if solved.

**Comment by EllyptiumOfficial** [comment]
Solved
