### ISSUE TITLE
Browser calls stopped working in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by filipetavares** [microsoft/WSL#8823]
### Version

Microsoft Windows [Version 10.0.19041.508

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04 LTS

### Other Software

Python 3.10 and Python 3.8

### Repro Steps

Install Ubuntu 22.04 LTS 
run python3 -m webbrowser -t "www.google.pt"

### Expected Behavior

The command should call the browser with the requested URL (this works in Ubuntu 20.04)

### Actual Behavior

Nothing happens, and if we run this command in an python shell it returns "False" (again this only happens in Ubuntu 22.04 LTS, this is working correctly in 20.04).

**Comment by OneBlue** [comment]
Closing since this doesn't look like a WSL specific issue.
