### ISSUE TITLE
WSL local port can't be accessed by windows following deep sleep

### ISSUE THREAD

**Issue by eyalk5** [microsoft/WSL#8825]
### Version

10.0.19044.1889

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.102.1

### Distro Version

Ubuntu 20.,04

### Repro Steps

I am not sure it is reliable replicates. Following a deep sleep, I sometimes need to disable and enable wifi interface to get it to work. 
Once I do it and reconnect to the internet, It no longer shares ports with the Windows machine. 

I am not sure able just reenable of interface .
I also have bridged interfaces related to hyperV.  

### Expected Behavior

Have ports shared. ie. when listen on WSL on port 9900 , I can connect to it from windows by localhost:990.  

### Actual Behavior

Ports are not shared

**Comment by benhillis** [comment]
Do you happen to have "fast startup" enabled? I recall an bug we fixed a long time ago with similar signature.

**Comment by eyalk5** [comment]
Yes I do. I turned it off and will report if it happens.
