### ISSUE TITLE
Allow wslpath to keep trailing slash for directories (possibly via an option e.g. --preserve-trailing-slash or --force-trailing-slash)

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#8827]
Usecase: from a WSLv1 bash get a Windows absolute dir path, to be passed to a python script to be passed to Chrome headless via selenium.

Succinctly: ` wslpath -a -w .` gets me what I want except that I need this path to have a trailing backslash. Unfortunately, ` wslpath -a -w ./"`  still returns the same path. It would be nice to have an option to return a trailing backslash for a directory in an easy way. My current workaround: `$(wslpath -a -w .)\\`. This is not too bad, just a bit inconvenient, and less clear to the reader as the backslash here may be somehow leaking through the abstraction

Also, it might be nice if `wslpath -a -w` directly returned path to the current directory - again, not very important.

**Comment by benhillis** [comment]
`wslpath -a -w .` should already do what you want for current directory. Seems like appending a trailing slash should be pretty easy to do in the python script as well?

**Comment by vadimkantorov** [comment]
Python script in WSLv1 thinks it's completely in Linux land, so `os.sep` is forward slash. So keeping it at the upper level of wslpath would be good. I agree, it's a minor issue, but it would be a bit nicer if wslpath could produce trailing slash as well (probably via opt-in option is best)

**Comment by benhillis** [comment]
Looks like this got lost in the churn, I've got a fix for this in PR.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5
