### ISSUE TITLE
WSL2 crashed after a long period (about 6 hours) 

### ISSUE THREAD

**Issue by Sigmoni** [microsoft/WSL#8828]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

- Connect to WSL in Terminal or VSCode Remote
- Leave the computer while the Terminal / VSCode still connected to WSL
- Come back after about 6-8 hours

### Expected Behavior

WSL is still connected and functioning

### Actual Behavior

WSL is disconnected and cannot be reconnected.
`wsl --shutdown` still works, after which WSL can be reconnected.

**Comment by yayster** [comment]
I am experiencing this behavior as well.  Started just last week.

`wsl --shutdown ` does clear the issue and allows start-up again.

start-up takes about 10 seconds.  Seeing the following in dmesg:
`[    3.420289] FS-Cache: Duplicate cookie detected
[    3.420291] FS-Cache: O-cookie c=00000000c0aa36d9 [p=000000001090ebc7 fl=222 nc=0 na=1]
[    3.420291] FS-Cache: O-cookie d=000000001ebf2149 n=000000002215f754
[    3.420292] FS-Cache: O-key=[10] '34323934393337363332'
[    3.420295] FS-Cache: N-cookie c=000000004c59adfe [p=000000001090ebc7 fl=2 nc=0 na=1]
[    3.420295] FS-Cache: N-cookie d=000000001ebf2149 n=000000004109ce24
[    3.420296] FS-Cache: N-key=[10] '34323934393337363332'`
