### ISSUE TITLE
IP address switches range between172.xxx to 192.xxx - no connectivity

### ISSUE THREAD

**Issue by mhechthz** [microsoft/WSL#8829]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel-Version: 5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Just start windows an wait to be surprised.

### Expected Behavior

Static IP or selection of random IP that hat has network connection.

### Actual Behavior

IP address of WSL2 (Hyper-V?) is changed from day to day. Most of the time there are IP addresses starting with 172 but sometimes also 192.

With 192.168.xxx I always have network connectivity. With 172.xxx it is difficult. 172.18, 21 and 31 always have network connectivity. 172.17, 19, 20, 25, 26, 27, 28, 29, 30 never have network connectivity. I checked this over months.

It seems not to be possible to have a static IP and not to fix the range of the IP. So I have to wait to get a day where the right IP is assigned.

**Comment by Biswa96** [comment]
There are already many issues about this topic, see https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+IP
