### ISSUE TITLE
"wsl --install" stuck on "Downloading: WSL Kernel" won't get past 2.1%

### ISSUE THREAD

**Issue by scedwards** [microsoft/WSL#8834]
### Version

Microsoft Windows [Version 10.0.19043.2006]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Closed the powershell during "Downloading: WSL Kernel" install after over 2 hours of waiting. Turned off Widows Subsystem for Linux and Virtual Machine Platform and restarted the computer. Attempted the "wsl --install" again after restart and had the same issue.

### Expected Behavior

Correct install of WSL

### Actual Behavior

PS C:\WINDOWS\system32> wsl --install
Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
[=                          2.1%                           ]

Its been hung here for over 2 hours multiple times.

**Comment by Biswa96** [comment]
You can download latest Linux kernel installer from this page https://www.catalog.update.microsoft.com/Search.aspx?q=wsl. Extract the MSI file from the downloaded one. Install it as usual.

**Comment by odigity** [comment]
This just happened to me.  First time trying Windows in 13 years, bought new computer with Windows 11 Pro on it, set it up, then opened an admin shell and ran `wsl --install`.  It got to "WSL Kernel has been installed.", then got stuck on "Downloading: GUI App Support".

**Comment by geeneeva** [comment]
This is happening to me as well. I have the Virtual Machine Platform feature on, virtualization is enabled on my PC. 
When inputting `wsl --install -d Ubuntu`, the load bar gets stuck at 0%.
