### ISSUE TITLE
Error on first start: Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x800706bf

### ISSUE THREAD

**Issue by jwgn** [microsoft/WSL#8841]
### Version

Microsoft Windows [Version 10.0.22622.436]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-22.04

### Repro Steps

Install Ubuntu 22.04 LTS from Microsoft Store.
Run it.

### Expected Behavior

It should install and open a shell when done.

### Actual Behavior

Der Remoteprozeduraufruf ist fehlgeschlagen und wurde nicht ausgeführt.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x800706bf
Der Remoteprozeduraufruf ist fehlgeschlagen und wurde nicht ausgeführt.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x800706bf
Der Remoteprozeduraufruf ist fehlgeschlagen und wurde nicht ausgeführt.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x800706bf
Press any key to continue...

[Verarbeitung des Prozesses mit Code 4294967295 (0xffffffff) beendet]

### Diagnostic Logs

https://f1sh.de/nxcd/s/BmD75ELgbgkCFtP

**Comment by phive151** [comment]
@jwgn #8841

Do you have OneDrive backing up your 'C:\\\Users\\%USERPROFILE%\Desktop' directory?  Because when OneDrive started removing all my local files to "save space and store them on the cloud" all kinds of errors, including this one, showed up but here is my output after running sfc:

```PowerShell
C:\Windows\System32>sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection found corrupt files and successfully repaired them.
For online repairs, details are included in the CBS log file located at
windir\Logs\CBS\CBS.log. For example C:\Windows\Logs\CBS\CBS.log. For offline
repairs, details are included in the log file provided by the /OFFLOGFILE flag.
```
After running "sfc" and disabling OneDrive Backup settings, the problem fixed itself.
I hope that helps!

Ich spreche nur ein bisschen Deutsch, aber es ist ein wunderschöner Ort!!

**Comment by jwgn** [comment]
I think I fixed it just now. Seems the network adapter for WSL was missing. I uninstalled WSL completely and did a full reset of all Windows network settings. After the reboot, re-installation of WSL and another reboot, I now have a network adapter `vEthernet (WSL)` and I was finally able to install Ubuntu.

**Comment by HomeOfTheWizard** [comment]
restarting the networking service for wsl worked for me
https://superuser.com/questions/1783419/how-to-fix-wsl-network-was-not-found

**Comment by jdannemann** [comment]
+1 This also happens with Debian.

**Comment by STmihan** [comment]
> restarting the networking service for wsl worked for me https://superuser.com/questions/1783419/how-to-fix-wsl-network-was-not-found

Works for me too, thanks
