### ISSUE TITLE
Installing Ubuntu 22.04.1 LTS from Microsoft Store freezes when setting username and password

### ISSUE THREAD

**Issue by andremarcondesteixeira** [microsoft/WSL#8851]
### Version

10.0.22621.521

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 22.04.1

### Repro Steps

Install Ubuntu 22.04.1 LTS from Microsoft Store

### Expected Behavior

It should work when clicking the Continue button in the screen that asks for setting username and password
![image](https://user-images.githubusercontent.com/4294962/191787010-f5306612-3359-4e82-bf5e-2ae48c80d276.png)

### Actual Behavior

Nothing happens when you click the Continue button on the screen that asks for username and password. If you just close the window, there will be a persistent error when you try to close WSL from GUI and it will break the menu for restarting the computer. You will have to forcefully end WSL from task manager.

**Comment by andremarcondesteixeira** [comment]
When click the 'X' button in the running WSL instance, this persistent error shows up and will continue showing forever. You will not be able to restart the computer from the start menu until you finish WSL from task manager: 
![image](https://user-images.githubusercontent.com/4294962/191787981-1764275d-df1f-4f04-bfe4-00c042733fb5.png)

**Comment by Biswa96** [comment]
If the issue is Ubuntu specific try to report the issue here https://github.com/ubuntu/wsl. Make sure other GNU/Linux distributions can be installed without any issue.

**Comment by andremarcondesteixeira** [comment]
reported there, thank you
