### ISSUE TITLE
WSL does not start when Systemd is enabled

### ISSUE THREAD

**Issue by nanasess** [microsoft/WSL#8856]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Gentoo

### Repro Steps

1. Update WSL to 0.67.6
2. Add these lines to the /etc/wsl.conf:
    ```
    [boot]
    systemd=true
    ```

### Expected Behavior

WSL starts successfully

### Actual Behavior

WSL does not start with the following message:
```
致命的なエラーです。
Error code: Wsl/Service/0x8000ffff

[プロセスはコード 4294967295 (0xffffffff) で終了しました]
```

### Diagnostic Logs

[WslLogs-2022-09-23_10-05-48.zip](https://github.com/microsoft/WSL/files/9630234/WslLogs-2022-09-23_10-05-48.zip)

**Comment by nanasess** [comment]
Solved by importing stage3-amd64-systemd-YYYYMMDDTHHMMSSZ.tar.xz

**Comment by YiuTerran** [comment]
> Solved by importing stage3-amd64-systemd-YYYYMMDDTHHMMSSZ.tar.xz

Hello, can you tell me how to import this file when the wsl cannot be started?
