### ISSUE TITLE
Network "disappears" all of a sudden (WSL2/Win11)

### ISSUE THREAD

**Issue by QAnders** [microsoft/WSL#8861]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Docker version 20.10.17, build 100c701
VSCode 1.70.2 (WSL Extension 0.66.3)

### Repro Steps

Developing using node.js and having PostgresSQL (v12) running in WSL with Docker running a container. Node.js local application (Serverless) accesses both Docker container (http) and Postgres DB fine after a restart.

DBeaver is used on Windows to access Postgres DB as well over `localhost:5432` which is also working fine.
Postman client is using on Windows to send requests (GET/POST) to node.js application running in WSL2 over localhost:1337 and localhost:3001 which is also working fine.

Some time later, can be 15 minutes or 3 hours, the network access halts and hosts are no longer accessible. Node.js running in WSL2 terminal can no longer access Postgres DB or http endpoints in the Docker container.

Postman client on Windows can't access the running application in WSL2 over `localhost:1337`, but can access the application if using the WSL2 container IP, e.g. `172.27.138.84:1337`.

Postgres DB (running on port 5432 in WSL2) can't be accessed from DBeaver on Windows at all, not on `localhost:1337` nor on `172.27.138.84:5432`.

Node.js applications running in WSL2 can't access Postgres DB on anything, not `localhost`, `127.0.0.1` nor on `172.27.138.84` so Postgres DB is not reachable at all.

Windows firewall is set and verified, and as stated it works for some time and then stops all of a sudden.

Fast Startup is disabled.

We have the same issue on two separate laptops in the team and we have the same versions/settings on both.

I realize that there are a lot of similar issues open already, but none of them (that I found) describes this problem where the network issue is intermittent, and also where some ports work (1337 and 3001) but not others, e.g. 8080 (HTTP) or 5432 (DB).

Also Internet is accessible from WSL2.

### Expected Behavior

Network should continue the work throughout the day (without having to restart laptop 4-5 times a day).

### Actual Behavior

Network stops working.

**Comment by soup-eater** [comment]
same issue. running docker as well. the /mnt/ locations had changed to docker Bind mounts and had a restart didnt fix it. had to build again from the docker compose file.
