### ISSUE TITLE
wsl not starting anymore after fail update to last insider build

### ISSUE THREAD

**Issue by StephaneKazmierczak** [microsoft/WSL#8862]
### Version

build 25179.rs_prerelease.220805-1349

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

debian 

### Repro Steps

while trying to start wsl from command line I am getting the error message : 
"the data is invalid."  
and wont start

### Expected Behavior

should drop into wsl shell 

### Actual Behavior

the data is invalid error message is displayed

**Comment by benhillis** [comment]
This is due to a certificate expiring because you are an old Insider build. I'd suggest moving to Windows 22H2, or switching Insider rings to get a new build to install.

**Comment by StephaneKazmierczak** [comment]
do you have a workaround to at least backup the distro ? the windows update doesn't seems to work, it is showing update succeed but then I am still on the same build, the mmc is locking most of the commands even though I am admin and I can't report feedback to windows the insider app is not login
