### ISSUE TITLE
Installing from store Ubuntu 22.04.1 install got error ls -l /tmp/.X11-unix failed.

### ISSUE THREAD

**Issue by kangarooo** [microsoft/WSL#8863]
### Version

21H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Installing from store Ubuntu 22.04.1 install got in show more info while installing an error 
ls -l /tmp/.X11-unix failed.
But still all worked and works.

![Screenshot (707)](https://user-images.githubusercontent.com/73187/191952163-da93c9f2-eee6-46ae-953b-dff71b51164c.png)

### Expected Behavior

Shouldnt have to have error

### Actual Behavior

Got error.
But all works.

**Comment by benhillis** [comment]
Could you please follow up with Canonical? They own this installer and should take a first look at this. Thanks!
