### ISSUE TITLE
Clean ubuntu 22.04.1 updating gives error

### ISSUE THREAD

**Issue by kangarooo** [microsoft/WSL#8864]
### Version

21H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Distro Version

Ubuntu 22.04.1

### Repro Steps
Updating
sudo apt update
sudo apt dist-upgrade
 got this error

Failed to retrieve available kernel versions.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

User sessions running outdated binaries:
 root @ /dev/pts/1: apt[350,2226]

No VM guests are running outdated hypervisor (qemu) binaries on this host.

Screenshot

![image](https://user-images.githubusercontent.com/73187/191951308-1cf2eb10-ef54-4858-a3e1-4878d6ab7f93.png)

### Expected Behavior

Should update all

### Actual Behavior

Didnt update

**Comment by elsaco** [comment]
@kangarooo those are harmless warnings. They are from `needrestart`. I think they can be turned off in one of the `/etc/needrestart` config files. I never bothered to disabled them!

**Comment by whoismaruf** [comment]
I'm also looking for the solutions 👀

**Comment by Biswa96** [comment]
@whoismaruf Those messages are just warning and does not cause any issue in WSL2 environment.

**Comment by c0d3pbob** [comment]
sudo apt-get purge needrestart
