### ISSUE TITLE
Blue screen of death on fresh install

### ISSUE THREAD

**Issue by jameschapman19** [microsoft/WSL#8865]
### Version

Microsoft Windows 11

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Repro Steps

Install windows 10 on reset device. Upgrade to windows 11. Do “wsl -install”. Restart.

### Expected Behavior

Normal boot

### Actual Behavior

Blue screen of death “inaccessible_boot_device”

**Comment by benhillis** [comment]
Could you please submit a feedback hub item? That will allow me to see dump files sent from your machine.

**Comment by jameschapman19** [comment]
What is a feedback hub item?

**Comment by jameschapman19** [comment]
Ok I’m not able to do this because I literally can’t start the computer it just does a blue screen loop.

I’ve repeated the steps again:

Fresh install windows 10
Upgrade to windows 11
Install all updates
Start following Ubuntu windows 11 instructions
Check the box for Virtual Machine Platform
First restart after doing this blue/green screen inaccessible boot device windows dead

**Comment by Biswa96** [comment]
Can you install Windows 11 directly without installing and upgrading from Windows 10?

**Comment by jameschapman19** [comment]
No - dell recovery does windows 10

**Comment by BertKooij** [comment]
I am currently running a fresh install of Windows 11 22H2. I am also unable to boot after enabling the Virtual Machine Platform feature (or running `wsl --install`). The system asks for a reboot, that takes a long time and eventially results in a bluescreen 'inaccessible_boot_device'. After a few cycles of reboots the system goes into recovery mode. Booting into safe mode works and will remove the feature update automatically. After that booting is possible again but the Virtual Machine Platform is not installed. 

No issues while enabling `Hyper-V management tools` . Virtualisation is enabled in the BIOS and the same machine was able to run WSL on Windows 10 and the previous version of Windows 11.

I was able to create a feedback hub item: https://aka.ms/AAidb20  (but this was after the recovery in safe mode).

**Comment by JasonBSteele** [comment]
I am getting this too.

I am on a Dell laptop which was originally Windows 10. After updating to Windows 11 I joined the Insider Program Beta channel.

Whenever I try to install WSL or Virtual Machine platform I get a GSOD after reboot with inaccessible_boot_device as the error

**Comment by jameschapman19** [comment]
Boot in safe mode once and it will be fixed - no idea why thank me later!

**Comment by JasonBSteele** [comment]
> Boot in safe mode once and it will be fixed - no idea why thank me later!

Haha, I actually tried that already! And while it does recover from the GSOD I still do not have WSL or VM Platform installed!

When I boot in safe mode I get a message on the screen saying there is a problem installing updates (presumably VM platform) and it rolls them back.

**Comment by cadtek91** [comment]
I got the same thing - I installed Ubuntu from the store and then WSL via "wsl --install" in terminal as one normally would.  And then hit restart as normal.  When it gets to booting and says updates are happening, it'll BSOD with Inaccessible Boot Device.

I did try to run a repair on it, no luck. So I fresh installed.

Tried to install wsl again today before I reinstalled all my other stuff (did install drivers and Bitwarden app) -- same thing happened, BSOD Inaccessible Boot Device.  Dell's SupportAssist preboot check says theirs no drive, *but* it is accessible via the recovery command prompt, I copied files off last night before the reinstall.

Dell 7590 with Windows 11 22h2 production/non-insider.

**Comment by cadtek91** [comment]
Today, I reinstalled again, my media creation drive has 21H2.  I did `wsl --install` in the elevated terminal before the automatic updates started (so it was still on 21H2) and I did not get a BSOD this time. Logged in and it started the window with installing Ubuntu automatically 👍

**Comment by cadtek91** [comment]
Sorry for leaving a another comment but... as the laptop rebooted for the installation of the 22H2 update, it happened again, same BSOD.

**Comment by Pakl23** [comment]
I got same problem with my dell Laptop. Updated from win 10 to win 11 and tried to Install docker Desktop leads to bsod with inaccessible_boot_device at restarting Windows. I tried a lot, and i could enclose the problem to wsl. When I was tryiing to install wsl 2 Ubuntu, got the same problems after win restart without any docker stuff. 
For me worked following:
* Open BIOS (F12 at start) and set virtualization - direct i/o  to false
* Windows Feature: mark "virtual Platform"

Then just installed docker Desktop with wsl2 enabled and everythings works as expected. Good luckl

**Comment by kaporal159** [comment]
> I got same problem with my dell Laptop. Updated from win 10 to win 11 and tried to Install docker Desktop leads to bsod with inaccessible_boot_device at restarting Windows. I tried a lot, and i could enclose the problem to wsl. When I tried to install wsl 2 Ubuntu, got same problems after win restart without any docker stuff. For me worked following:
> 
> * Open BIOS (F12 at start) and set virtualization - direct i/o  to false
> * Windows Feature: mark "virtual Platform"
> 
> Then just installed docker Desktop with wsl2 enabled and everythings works as expected. Good luckl

Works like charm! Thanks dude!

**Comment by andreasfernandez** [comment]
Thanks a lot, @Pakl23. This issue drove me nuts and I thought Windows 11 is incompatible with my 2019 Dell XPS.

**Comment by grenoult** [comment]
This worked well as well. The options in the BIOS where slightly different, but in the end it worked out well. Thanks!

**Comment by fareedfauzi** [comment]
https://stackoverflow.com/a/75903390/8774448

I faced the same problem with my Lenovo X1 Extreme.

My problem was solved when I configure these things in BIOS.

Enter BIOS > Security > Virtualization > Set this values:

```
Kernel DMA Protection = Disabled
Intel virtualization technology = Enabled
Intel VT-d feature = Enabled
Enhanced Windows Biometric Security = Disabled
```

**Comment by bristley** [comment]
I can confirm Kernel DMA Protection disabled as well as the enhanced biometric security worked with my Lenovo X1. Thank you so much fareedfauzi - this is the first place I've seen the Kernel DMA Protection mentioned as a possible solution after going through all the steps and multiple reboots everyone has done trying to solve this on their laptops.  So relieved.

**Comment by sunba23** [comment]
Thank you so much for the fix @Pakl23, this issue drove me insane and i thought my dell xps won't ever run wsl 🥇
