### ISSUE TITLE
Windows 11 Beta channel hangs on "wsl --shutdown" for a systemd-enabled wsl2 instance

### ISSUE THREAD

**Issue by TotiTolvukall** [microsoft/WSL#8875]
What I did leading to my computer completely freezing (resources exhausted):

1) have Windows 11 with all updates installed except the 2H22 update.
2) enter said Windows machine in the insider preview and install the preview.
3) after the preview is installed and the latest update to it applied, install wsl from the store
4) enable systemd on the Ubuntu 22.04 installation I had under WSL2
5) use the machine for a while (find that display :0 is inaccessible as well)
6) in powershell do wsl --shutdown
7) watch the computer get completely unresponsive except for the mouse - which got gradually more sluggish until some time later it was dead too.
8) power-cycle.

Winver shows 22H2 - 22622.601

❯ wsl --version
WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.601

❯ wsl -l -v
  NAME                                   STATE           VERSION
* Ubuntu-20.04                           Stopped         2
  Ubuntu-18.04                           Stopped         1

**Comment by TylerJaacks** [comment]
This happens on the Stable/Retail version of Windows 11 22H2.

**Comment by hypeitnow** [comment]
I can confirm, typing wsl --shutdown after the instance hangs has been going for 20 minutes now and still vmmem consumes 80% of cpu

**Comment by benhillis** [comment]
@OneBlue - might be another symptom of the hang you have been debugging.

**Comment by Pir-CHILD** [comment]
The same thing happended in wsl --version 0.68
\>wsl --version
WSL version: **0.68.2.0**
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.521

\>wsl -l -v
NAME      STATE           VERSION
\* Debian    Running         2

**Comment by doublefx** [comment]
Same here:

``` bash
» wsl --version
Version WSL : 0.70.5.0
Version du noyau : 5.15.68.1
Version WSLg : 1.0.45
Version MSRDC : 1.2.3575
Version direct3D : 1.606.4
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
version Windows : 10.0.22621.819
PS C:\tools\Cmder
```

**Comment by totszwai** [comment]
Was able to "un-hang" it by doing Ubuntu 22.04 > Reset > Repair

But as soon as I try to do anything related to `systemctl` it hangs.

```
C:\Windows\System32>wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```
