### ISSUE TITLE
alsa, arecord sometimes breaks until next restart

### ISSUE THREAD

**Issue by marcIhm** [microsoft/WSL#8880]
### Version

Microsoft Windows [Version 10.0.22622.601]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

arecord (i.e. alsa, advanced linux sound architecture)
Windows Remote Desktop Protocol, which (I think) is used to bring the sound from notebooks microphone to wsl.

### Repro Steps

arecord -r 4800 >/dev/null
after a reboot this works  (records my microphone), which means I can record with arecord, kill it e.g. with ctrl-C record again 
 for seconds or minutes and so on; multiple times.
But then it breaks: i.e. if I invoke arecord, I get the error message below. I need to restart wsl (wsl --shutdown) or even restart windows, after which arecord again works quite well for some time.
Btw: If it works, the recording quality seems to be better than it used to be ...

### Expected Behavior

Sound from my microphone should be recorded to a file.

### Actual Behavior

Arecord aborts with this error message:

ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
arecord: main:831: audio open error: No such file or directory

### Diagnostic Logs

I have been using arecord regularly for a year now, but after the last update to wsl (Sept 23) it started to failed intermittantly and can only be brought back to function with a reboot, but only until its next failure. 

Aside from the wsl-update I did not change anything in my configuration.

**Comment by kaxing** [comment]
Had the same sound problem with a customized distro. Then I notice `wsl.exe env` seems missing some variables.
So, I manually declare these environment variables to make aplay/arecord work again:
```
$ env|grep -E "DISP|PUL"
WAYLAND_DISPLAY=wayland-0
DISPLAY=:0
PULSE_SERVER=/mnt/wslg/PulseServer
```

Also, since 0.67.6 is the first release to officially support systemd.
The modification that I made for the distro is having some problem when I turn on the systemd by wsl, I had to turn this off as well:
```
$ wsl.exe -v
WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

$ cat /etc/wsl.conf
[boot]
systemd = false
```

**Comment by marcIhm** [comment]
Thanx for the suggestion; but this sounds more like a workaround ...
In fact, most of the time it works for me, so environment variables (which would be wrong consistently) cannot be the cause.
And as systemd is the major point of this update, it should not be disabled ...

**Comment by hagronnestad** [comment]
I think I am experiencing the same issue. I've been working on playing audio cross platform using SDL2-bindings and .NET 6. Thought I was doing something wrong until I realized that the audio system in WSL2 seems to break "after a while".

If I shutdown WSL2 (using `wsl --shutdown`) and then reopen a terminal (`wsl.exe -d Ubuntu-20.04`) the audio is working fine. An audio device called `RDP Sink` exists and I can play audio using the `play` command.

Then, after closing the terminal session (or just waiting a while, I think), the audio device seems to disappear and I get the following error from `play`:

```
$ play audio.wav
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
play FAIL sox: Sorry, there is no default audio device configured
```

`play`-command
```
$ play --version
play:      SoX v14.4.2
```

WSL2 Version
```
> wsl -v
WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1098
```

Ubuntu Version
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

**Comment by marcIhm** [comment]
Yes, sounds like my problem.
Still hoping, that one of the many microsoft updates will bring a fix or otherwise the upcoming Ubuntu-Update to 22.10 ...

**Comment by marcIhm** [comment]
With the latest updates applied, this problem seems so be gone:

`wsl -v
WSL-Version: 0.70.4.0
Kernelversion: 5.15.68.1
WSLg-Version: 1.0.45
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22623.870`

and Ubuntu:

`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic`

Thanx for fixing !

**Comment by marcIhm** [comment]
After the latest updates I haven't seen this problem for some days:
```
wsl -v
WSL-Version: 1.0.0.0
Kernelversion: 5.15.74.2
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22623.891
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

keeping fingers crossed.

**Comment by marcIhm** [comment]
Consistently works for me. This has been fixed :-)
