### ISSUE TITLE
Cannot access RabbitMQ server in host from WSL2

### ISSUE THREAD

**Issue by ThejaniYapa** [microsoft/WSL#8887]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 

### Other Software

Docker Desktop 2.5.0.1
Ms Visual Studio Code 1.71.2 with Remote - WSL v0.66.3
Anaconda3 2020.02 (Python 3.7.6. 64-bit)

### Repro Steps

Repro Steps
Host IP found with cat /etc/resolv.conf : 172.21.112.1
ping "$(hostname).local" was unsuccessful, Allowed inbound from the WSL by with: New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow.

ping "$(hostname).local" is successful

### Expected Behavior

Connection opens when:
telnet 172.21.112.1 8888

### Actual Behavior

telnet 172.21.112.1 8888 is unsuccessful with below response.

> Trying 172.21.112.1...
> telnet: Unable to connect to remote host: Connection timed out

### Diagnostic Logs

**Output of [networking.bat](https://github.com/Microsoft/WSL/blob/master/diagnostics/networking.bat):**

If you see 'ping: socket: Operation not permitted' errors, run this command as root.
+ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
+ uname -a
Linux LAPTOP-LQNAVCCU 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
+ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 26:28:2e:53:26:8d brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ca:03:81:68:36:a8 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:3e:de:80 brd ff:ff:ff:ff:ff:ff
    inet 172.21.123.116/20 brd 172.21.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe3e:de80/64 scope link
       valid_lft forever preferred_lft forever
+ ip route show
default via 172.21.112.1 dev eth0
172.21.112.0/20 dev eth0 proto kernel scope link src 172.21.123.116
++ ip route show
++ awk '/default/ { print $3 }'
+ gateway=172.21.112.1
+ ping -c 4 172.21.112.1
PING 172.21.112.1 (172.21.112.1) 56(84) bytes of data.
64 bytes from 172.21.112.1: icmp_seq=1 ttl=128 time=0.585 ms
64 bytes from 172.21.112.1: icmp_seq=2 ttl=128 time=0.306 ms
64 bytes from 172.21.112.1: icmp_seq=3 ttl=128 time=1.02 ms
64 bytes from 172.21.112.1: icmp_seq=4 ttl=128 time=0.721 ms

--- 172.21.112.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3122ms
rtt min/avg/max/mdev = 0.306/0.658/1.020/0.257 ms
+ ping -c 4 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=56 time=19.8 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=56 time=21.1 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=56 time=19.4 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=56 time=17.6 ms

--- 1.1.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 17.614/19.485/21.115/1.253 ms
+ traceroute 1.1.1.1
networking.sh: line 28: traceroute: command not found
+ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.21.112.1
+ type curl
+ curl -m 5 -v https://microsoft.com
*   Trying 20.84.181.62:443...
* TCP_NODELAY set
* Connected to microsoft.com (20.84.181.62) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=microsoft.com
*  start date: Sep 15 21:33:50 2022 GMT
*  expire date: Sep 10 21:33:50 2023 GMT
*  subjectAltName: host "microsoft.com" matched cert's "microsoft.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 05
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5594a3a577c0)
> GET / HTTP/2
> Host: microsoft.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< date: Mon, 26 Sep 2022 03:32:40 GMT
< server: Kestrel
< location: https://www.microsoft.com/
< content-length: 0
< strict-transport-security: max-age=31536000; includeSubDomains
<
* Connection #0 to host microsoft.com left intact

**Comment by FabriceReneCorail** [comment]
Well it's look like this issue can be fixe an other version of the engine docker desktop. For me it's a pain cauz im developping on an old macbook and the 2.5.0.1 version is the only support by High Sierra and the engine version is 19... shit i need at least a 20.10  crap :s
