### ISSUE TITLE
Running windows executables from ssh session gives no output

### ISSUE THREAD

**Issue by mavaa** [microsoft/WSL#8889]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

openssh-server 1:8.2p1-4ubuntu0.5

### Repro Steps

1. Run any windows executable like git.exe, winget.exe or wsl.exe from WSL Ubuntu in the Windows Terminal without problem.
2. Install openssh-server and start with `service ssh start`
3. Run the following to set up firewall and port forwarding to make WSL ssh available to external connections (from Powershell):

```
# Set up port forwarding & firewall
$remoteport = bash.exe -c "ifconfig eth0 | grep 'inet '"
$found = $remoteport -match '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}';

if( $found ){
  $remoteport = $matches[0];
} else{
  Write-Output "The Script Exited, the ip address of WSL 2 cannot be found";
  exit;
}

#[Ports]

#All the ports you want to forward separated by coma
$ports=@(14990);


#[Static ip]
#You can change the addr to your ip config to listen to a specific address
$addr='0.0.0.0';
$ports_a = $ports -join ",";


#Remove Firewall Exception Rules
Invoke-Expression "Remove-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' ";

#adding Exception Rules for inbound and outbound Rules
Invoke-Expression "New-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' -Direction Outbound -LocalPort $ports_a -Action Allow -Protocol TCP";
Invoke-Expression "New-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' -Direction Inbound -LocalPort $ports_a -Action Allow -Protocol TCP";

for( $i = 0; $i -lt $ports.length; $i++ ){
  $port = $ports[$i];
  Invoke-Expression "netsh interface portproxy delete v4tov4 listenport=$port listenaddress=$addr";
  Invoke-Expression "netsh interface portproxy add v4tov4 listenport=$port listenaddress=$addr connectport=$port connectaddress=$remoteport";
}
```
4. Connect from a Linux machine using SSH to the WSL server
5. Need to set up `$PATH` to the Windows executables from the SSH session
6. Try running any of the mentioned exe-files -> Produces no output, and from task manager it seems like they don't run at all
7. Go back to the windows terminal and try running the same exe-files agan -> Also produces no output like step 5!
8. Reboot the machine and start WSL again -> Everything works fine. But as soon as you start up ssh-server and connect lige steps 2-5 again, exe-files completely stops working. No output, no error messages

### Expected Behavior

Exe files which are command line only should still work, even if an ssh-connection is active, preferably both in the remote session and in Windows Terminal.

I suspect there might be some kind of security mechanism preventing me from doing this, but if so I cannot find any documentation for it. At the bare minimum I should get some sort of error message telling me what went wrong.

### Actual Behavior

Running windows executables from WSL after an ssh connection has happened produces no output or error messages, and doesn't seem to start any of the processes.

**Comment by mavaa** [comment]
This is a bit emparrasing, after weeks of this not working, right after posting this, I found out I could change to the windows Store version of WSL, and suddenly everything works!

**Comment by mavaa** [comment]
Okay, this seems to be a surefire way to reproduce my issue.
1. Start powershell.exe as an administrator user
2. If your wsl distro was previously running, run `wsl --shutdown`
3. Run the following, still as administrator:

```
# Start ssh server
wsl.exe -u root -- service ssh start

# Set up port forwarding & firewall
$remoteport = wsl.exe -- zsh -c 'ifconfig eth0 | grep inet\ '
$found = $remoteport -match '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}';

if( $found ){
  $remoteport = $matches[0];
} else{
  Write-Output "The Script Exited, the ip address of WSL 2 cannot be found";
  exit;
}

#[Ports]

#All the ports you want to forward separated by coma
$ports=@(14990);


#[Static ip]
#You can change the addr to your ip config to listen to a specific address
$addr='0.0.0.0';
$ports_a = $ports -join ",";


#Remove Firewall Exception Rules
Invoke-Expression "Remove-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' ";

#adding Exception Rules for inbound and outbound Rules
Invoke-Expression "New-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' -Direction Outbound -LocalPort $ports_a -Action Allow -Protocol TCP";
Invoke-Expression "New-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock' -Direction Inbound -LocalPort $ports_a -Action Allow -Protocol TCP";

for( $i = 0; $i -lt $ports.length; $i++ ){
  $port = $ports[$i];
  Invoke-Expression "netsh interface portproxy delete v4tov4 listenport=$port listenaddress=$addr";
  Invoke-Expression "netsh interface portproxy add v4tov4 listenport=$port listenaddress=$addr connectport=$port connectaddress=$remoteport";
}
```
(Note: I changed from bash.exe to wsl.exe from my previous example to exclude that as the culprit)

Now there's two things you can do, one will ensure everything works, the other ensures the no output issue:

Working method: Start a normal wsl session on your computer (not running as root), for instance through Windows Terminal. Then open a ssh connection. Running windows executables works completely fine, I can even start GUI applications like notepad.exe (the window will open in my remote desktop session of course).

Not working: After running the script, immediately open an ssh connection, without starting a local one first. The connection goes through, but windows executables will just exit with no output, CLI and GUI apps alike. This even carries over when starting a local session in Windows Terminal after the ssh connection. If I re-run the above command and start a local session BEFORE the ssh session, everything works again.

**Comment by jkurkure** [comment]
I'm also facing this issue.

**Comment by tim-rex** [comment]
Having similar issues with remote ssh connections unable to launch windows executables..
What's particularly interesting is..

I can ssh into my windows machine, which I've configured to provide a default bash shell..
From there I can launch a cmd.exe shell, fine

From there, windows executables behave as if they do not exist.

```
$ echo $0
-bash
$ cmd.exe
Microsoft Windows [Version 10.0.26100.2033]
(c) Microsoft Corporation. All rights reserved.

>where notepad.exe

>where git.exe

>notepad.exe

>echo %errorlevel%
-1073741502

>git.exe

>echo %errorlevel%
-1073741502

>echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Automator\AppData\Local\Microsoft\WindowsApps;C:\Users\Automator\AppData\Local\Programs\Git\cmd
```


Those exit codes..  would appear to map to a generic "unable to start" error condition.. the following seems semi-related

https://support.microsoft.com/en-au/topic/-0xc0000142-or-1073741502-stop-error-when-many-powershell-scripts-call-the-console-write-method-or-when-you-try-to-start-many-console-applications-on-a-powershell-console-in-windows-7-or-in-windows-server-2008-r2-19f475a2-cbe9-c463-a2b4-b7fe7a1d236d


Please reopen
