### ISSUE TITLE
Admin user does not see a Ubuntu installation

### ISSUE THREAD

**Issue by toncho11** [microsoft/WSL#8890]
### Version

Microsoft Windows [version 10.0.19042.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Other Software

Docker version 20.10.12, build e91ed57

### Repro Steps

I installed Ubuntu 20.04 as either normal user or Administrator. 

### Expected Behavior

`wsl -l -v` to list "Ubuntu" as available distro after installation.

### Actual Behavior

`wsl -l -v` does NOT list "Ubuntu" as available distro after installation when using the administrative account. Even if I install it as an administrator it still does not appear. It only lists Ubuntu when using a non-administrative account.

I need to run  `usbipd wsl attach --busid 2-14` as an administrator user, but when I use an admin cmd or powershell wsl does not see Ubuntu 20.04. It only sees some docker distros.

**Comment by benhillis** [comment]
WSL distros are per-user. Are you running a separate user account, or the same user account as Elevated?

**Comment by toncho11** [comment]
This is the problem. It seems it only works if you login as an administrator and not as elevated administrator account.

**Comment by dorssel** [comment]
> I need to run usbipd wsl attach --busid 2-14 as an administrator user

Not true. Only the binding part has to be run as an admin. You can first `--bind` as an admin, and then `wsl --attach` as a normal user.
