### ISSUE TITLE
start systemd - Unable to upgrade files

### ISSUE THREAD

**Issue by rye2020** [microsoft/WSL#8895]
### Windows build number:

Platform ServicePack Version      VersionString -------- ----------- -------      -------------  Win32NT             10.0.25206.0 Microsoft Windows NT 10.0.25206.0

### Your Distribution version:

Release:        20.04

### Your WSL versions:

WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25206.1000

### Steps to reproduce:

sudo apt upgrade

### Actual behavior:

jrm@OPX3050:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libnss-systemd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
 libpam-systemd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
 systemd : Depends: libsystemd0 (= 245.4-4ubuntu3.17) but 245.4-4ubuntu3.18 is installed
 systemd-container : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
 systemd-sysv : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
 systemd-timesyncd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by tusharsnn** [comment]
can you share the contents of `/etc/apt/sources.list`?

**Comment by rye2020** [comment]
For my Ubuntu 20.04:
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal universe
deb http://archive.ubuntu.com/ubuntu/ focal-updates universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu/ focal multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
deb http://archive.canonical.com/ubuntu focal partner
# deb-src http://archive.canonical.com/ubuntu focal partner

deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
# deb-src http://security.ubuntu.com/ubuntu/ focal-security main restricted
deb http://security.ubuntu.com/ubuntu/ focal-security universe
# deb-src http://security.ubuntu.com/ubuntu/ focal-security universe
deb http://security.ubuntu.com/ubuntu/ focal-security multiverse
# deb-src http://security.ubuntu.com/ubuntu/ focal-security multiverse

For a clean install of Ubuntu 20.04:
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal universe
deb http://archive.ubuntu.com/ubuntu/ focal-updates universe
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu/ focal multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu focal partner
# deb-src http://archive.canonical.com/ubuntu focal partner

deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
# deb-src http://security.ubuntu.com/ubuntu/ focal-security main restricted
deb http://security.ubuntu.com/ubuntu/ focal-security universe
# deb-src http://security.ubuntu.com/ubuntu/ focal-security universe
deb http://security.ubuntu.com/ubuntu/ focal-security multiverse
# deb-src http://security.ubuntu.com/ubuntu/ focal-security multiverse

**Comment by tusharsnn** [comment]
I think I found a fix. 

#### TL'DR:
To fix the update issue:
1. boot the distro with disabled systemd (`systemd=false in wsl.conf`).
2. Run `sudo apt update && sudo apt upgrade`. This will update the systemd to the newest release (245.4-4ubuntu3.17 -> 245.4-4ubuntu3.18), systemd cannot be updated within the wslsystemd environment (more details later).
3. After the update, enable the systemd back in `wsl.conf`.
4. Now the issue should be gone.

**Comment by tusharsnn** [comment]
wslsystemd seems to modify `/usr/lib/tmpfiles.d/tmp.conf` and `/usr/lib/tmpfiles.d/X11.conf` so that they don't interfere with wsl.
```sh
ls -al /usr/lib/tmpfiles.d/                                                             tushar
total 88
drwxr-xr-x  2 root root 4096 Sep 26 18:10 .
drwxr-xr-x 85 root root 4096 Sep 24 13:24 ..
-rw-r--r--  1 root root  465 Nov 16  2021 00rsyslog.conf
-rw-r--r--  1 root root   80 Oct 27  2021 apport.conf
-rw-r--r--  1 root root   35 Aug  4 17:38 cryptsetup.conf
-rw-r--r--  1 root root  365 Apr  1 22:32 dbus.conf
-rw-r--r--  1 root root  517 Feb 16  2022 debian.conf
-rw-r--r--  1 root root  362 Mar 11  2022 home.conf
-rw-r--r--  1 root root 1096 Mar 11  2022 journal-nocow.conf
-rw-r--r--  1 root root  812 Jun 27 23:58 legacy.conf
-rw-r--r--  1 root root   61 Feb 16  2022 lvm2.conf
-rw-r--r--  1 root root   33 Mar 18  2022 man-db.conf
-rw-r--r--  1 root root  239 Nov 10  2021 passwd.conf
-rw-r--r--  1 root root   29 Feb 23  2021 screen-cleanup.conf
-rw-r--r--  1 root root   27 Sep 26 18:10 sshd.conf
-rw-r--r--  1 root root  763 Jun 27 23:58 static-nodes-permissions.conf
-rw-r--r--  1 root root   27 Feb  8  2022 sudo.conf
-rw-r--r--  1 root root 1790 Jun 27 23:58 systemd.conf
-rw-r--r--  1 root root  597 Mar 11  2022 systemd-nologin.conf
-rw-r--r--  1 root root 1514 Mar 11  2022 systemd-pstore.conf
-rw-r--r--  1 root root  823 Mar 11  2022 systemd-tmp.conf
crw-rw-rw-  1 root root 1, 3 Sep 27 18:45 tmp.conf
-rw-r--r--  1 root root  568 Jun 27 23:58 var.conf
crw-rw-rw-  1 root root 1, 3 Sep 27 18:45 x11.conf
```

output of dmesg:
```sh
[ 2418.148562] WSL (1): systemd: /usr/lib/tmpfiles.d/tmp.conf is disabled
[ 2418.148586] WSL (1): systemd: /usr/lib/tmpfiles.d/x11.conf is disabled
```
However, when systemd is updated it tries to make backup of the files under `/usr/lib/tmpfiles.d/*` and after finding those files as modified just errors out as it complains:
```sh
dpkg: error processing archive /var/cache/apt/archives/systemd_245.4-4ubuntu3.18_amd64.deb (--unpack):
unable to make backup link of './usr/lib/tmpfiles.d/tmp.conf' before installing new version: Invalid cross-device link
```
*full error message [here](https://github.com/microsoft/WSL/issues/8895#issuecomment-1258439211)*

**Comment by tusharsnn** [comment]
Systemd cannot update under an active systemd session within wsl. For now systemd has to be disabled before updating it. This could present some pitfalls for regular user as each time a new update is available it will complain. Focal (Ubuntu-20.04) seems to have received an update for systemd recently (09/22).

**Comment by rye2020** [comment]
Upgrading my installed Ubuntu 20.04 with systemd turned off gives the following error message:

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
>  libnss-systemd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
>  libpam-systemd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
>  systemd : Depends: libsystemd0 (= 245.4-4ubuntu3.17) but 245.4-4ubuntu3.18 is installed
>  systemd-container : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
>  systemd-sysv : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
>  systemd-timesyncd : Depends: systemd (= 245.4-4ubuntu3.18) but 245.4-4ubuntu3.17 is installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

Upgrading the clean install of Ubuntu 20.04 ran with no error messages.

I should note that my installed Ubuntu (not the clean install) had wsl2hack installed to provide systemd.  My guess is there is a conflict there when the systemd files are upgraded.

would appreciate any thoughts you might have.  

To install wsl2hack, one of the steps is sudo apt install dbus policykit-1 daemonize.  I am unable to remove any of those packages.  On sudo apt remove for any of three, I get an error messaage:

> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

VOILA!!  Turning off systemd on wsl.conf and running sudo apt --fix-broken install seems to have corrected the problem.  My installed Ubuntu (not the clean install) ran sudo apt upgrade with NO error messages.  For my purposes I think we can treat this as closed.

**Comment by namiltd** [comment]
```
cd /bin && mv -f systemd-sysusers{,.org} && ln -s echo systemd-sysusers && cd -
```
