### ISSUE TITLE
Git Push fails on WSL2 via both SSH and HTTPS above a certain filesize (around 1KB). 

### ISSUE THREAD

**Issue by wongchongkai** [microsoft/WSL#8907]
### Version

Microsoft Windows [Version 10.0.22621.521]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.57.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Setup:

Client:
- git version 2.25.1

Server:
- Rootless gitea (1.17.1-rootless, pulled from Docker.io) running in a rootless Podman (version 3.4.4, installed via apt) container.
- Remote server also has containerless Caddy v2 set up as a reverse proxy, though it only handles HTTP(S) requests and should not affect SSH.

Steps to reproduce:
git push any commit using either HTTPS or SSH where git-receive-pack (displayed when running `git push --verbose` using HTTPS) is greater than about 1000 bytes.

### Expected Behavior

Expected git push to self-hosted Gitea to succeed.

### HTTPS
```
git push --verbose --progress
Pushing to [remote repo]
Username for ...
Password for ...
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 137.68 KiB | 137.68 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
POST git-receive-pack (141133 bytes)
```
^
Stuck here.

### SSH
```
git push --verbose --progress
Pushing to [remote repo]
Enter passphrase for key '[SSH keyfile]':
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.   
Delta compression using up to 16 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 76.36 KiB | 76.36 MiB/s, done.
Total 9 (delta 1), reused 0 (delta 0)
```
^
Stuck here.

Things that I've tried:
1. Pushing to containerless plain Git instead of Gitea -> Still doesn't work, so probably not a Gitea nor a Podman issue.
2. Turning PC VPN on/off -> no change in behavior in either case.
3. Making very tiny changes to the code (< 1KiB) and pushing -> this works.
4. Copying the files to Windows and pushing from there -> works like a charm.

**Comment by aysabzevar** [comment]
I am using WSL2 on Windows 11 for quite a while now. I did git clone, add, commit, push successfully last night, but **git push** doesn't work anymore.

It can resolve github.com, but stuck at git push:
```
[ali@fedora CAF_Terraform_StepByStep]$ dig  github.com

; <<>> DiG 9.16.33-RH <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42342
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             23      IN      A       140.82.121.3

;; Query time: 10 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Oct 13 10:49:47 CEST 2022
;; MSG SIZE  rcvd: 55

[ali@fedora CAF_Terraform_StepByStep]$ git push --verbose --progress origin fix-README
Pushing to github.com:aysabzevar/CAF_Terraform_StepByStep.git
```

**Comment by Alexmhack** [comment]
I started having this same issue in my system recently, I had to switch to WSL 1 which is very slow comparatively. 

Did you find any solution for WSL 2?

**Comment by SergiuCornea** [comment]
Same here, i started having the same issue

**Comment by jyee-ctm** [comment]
Having issues now

![Image](https://github.com/user-attachments/assets/05827880-6434-425c-a3f4-0705069c6e4c)

if i chunk it to way smaller commits (single files) it works.
