### ISSUE TITLE
Removable disks (USB and CD) not detected on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by outOfServiceNow** [Microsoft/WSL#891]
- A brief description
  USB & CD drive not detected in the /mnt folder.
  USB & CD Drive letters do not appear on issuing command-> ls /mnt.
- Expected results
  on issue of command-> ls /mnt
  c d e f is expected. e should be my USB. c & d are my hard drive. e is my CD drive. f is my USB.
- Actual results (with terminal output if applicable)
  c d
- Your Windows build number
  Version 1607 (OS Build 14393.51)
- Steps / commands required to reproduce the error
- open Bash on Ubuntu on Windows
- issue the command-> ls /mnt

**Comment by fpqc** [comment]
This is a "bydesign-mightfix" feature.  Easiest way to convince MS you need support for this is on the uservoice page.

**Comment by AnneTheAgile** [comment]
Here's one userVoice url [1], for USB, which is on the backlog for consideration. The exact match is [2] which is not yet as high rated.

1.Unable to access USB devices from bash – Welcome to the Windows developer feedback site! ; ; https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13355724-unable-to-access-usb-devices-from-bash 
2.Access to network shares and removable drives – Welcome to the Windows developer feedback site! ; ; https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13313280-access-to-network-shares-and-removable-drives

**Comment by melt7777** [comment]
I am also affected by this bug. Need USB / SD cards to be mounted for scripting.

**Comment by emiliogozo** [comment]
Good news!!! Mounting FAT* and NTFS removable drives and CDs is now possible:

https://blogs.msdn.microsoft.com/wsl/2017/04/18/file-system-improvements-to-the-windows-subsystem-for-linux/

**Comment by huzq85** [comment]
@emiliogozo, thanks for giving the link to help to resolve this problem.
