### ISSUE TITLE
Versions of wsl above 0.65.3 cause networking issues

### ISSUE THREAD

**Issue by carylewis** [microsoft/WSL#8912]
### Version

wsl 0.67.6_0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

I configured a hyper-v virtual switch to bridge my wifi adapter so that I can get a local LAN address in wsl2 and the distros rather than a private IP, as I want to be able to connect to servers running within wsl2 from other devices on my local LAN.

.wslconfig:

`[WSL2]
memory=6GB
processors=2
networkingMode=bridged 
vmSwitch=Bridge
guiApplications=true
`

### Repro Steps

After upgrading to wsl 0.67.6, I started experiencing several different networking issues:

1. Degraded internet access. Following a reboot, over time, my internet connect became unstable. I experienced dropped packets when testing with ping, and video calls, etc. were unusable. Doing a reboot restored internet connectivity, and things didn't degrade if I didn't start wsl2.

2. With wsl v. 0.65.3, I am able to run servers inside the Ubuntu sessions and reach them from other devices on my local LAN. 

This stopped working with 0.67.6.

I can not connect to any server running in the Ubuntu distro from the local LAN address. I can connect to services running in the wslg distro, e.g. I can do a nc -v x.x.x.x 22 and it does connect. I can also connect locally from within the distro using the local lan address.

### Expected Behavior

The network shouldn't degrade, and any servers running with the distros should be accessible on the local lan.

### Actual Behavior

The network degrades, and the servers are not accessible from other devices on the LAN.

**Comment by benhillis** [comment]
networkingMode=bridged is not yet officially supported supported.

**Comment by carylewis** [comment]
But bridged mode does work fine with v. 0.65.3
