### ISSUE TITLE
x window system completely broken after enabling systemd

### ISSUE THREAD

**Issue by c4artisan** [microsoft/WSL#8915]
### Windows build number:

22622.0

### Your Distribution version:

Ubuntu 22.04

### Your WSL versions:

Versión de WSL: 0.67.6.0
Versión de kernel: 5.15.62.1
Versión de WSLg: 1.0.44
Versión de MSRDC: 1.2.3401
Versión de Direct3D: 1.606.4
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.22622.601
(i know it's in spanish but ig it still works)

### Steps to reproduce:

1. enable systemd on the distro
2. restart and try to run any xapp (the x11-apps bundle, firefox, google chrome and chromium, etc.)

### WSL logs:

[stderr.log](https://github.com/microsoft/wslg/files/9660148/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/9660149/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/9660150/pulseaudio.log)

### Expected behavior:

the application runs with no problems

### Actual behavior:

the app won't launch, complaining about a missing x server/no display variable
wayland applications (such as gnome, even though strangely i thought gnome wasn't able to run on wayland?) do work however.

cerebrate had been diagnosing my case on the wsl repo [[https://github.com/microsoft/WSL/issues/8899](url)] and unfortunately i think this is going deeper than what it should've gone. most details are on that issue.

**Comment by cq01** [comment]
this also appear in wsl 0.70

# Your Distribution version:
kali-linux

# Your WSL versions:**
WSL 版本： 0.70.0.0
内核版本： 5.15.68.1
WSLg 版本： 1.0.45
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22623.746

**Comment by c4artisan** [comment]
#8899
issue is fixed
