### ISSUE TITLE
wsl tar export gets stuck at 21GB. VHD export fails with 0x80070017

### ISSUE THREAD

**Issue by asubmani** [microsoft/WSL#8917]
### Version

Microsoft Windows [Version 10.0.22000.856]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-22.04.01-LTS UPGRADED from Ubuntu-18.04  using `sudo do-release-upgrade`
NOTE: I upgraded after getting same failures. The upgrade did not change anything

### Other Software

Default Distribution: Ubuntu-22.04.01-LTS
Default Version: 2
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.856

### Repro Steps

wsl --export  Ubuntu-18.04 --vhd f:\wsl2\ubuntu18.vhdx` this fails with below error:

`Export in progress, this may take a few minutes.
Data error (cyclic redundancy check).
Error code: Wsl/Service/0x80070017`

`wsl --export  Ubuntu-18.04  f:\wsl2\ubuntu18.tar `

This starts exporting but takes too long (waited more than 24 hrs) and the tar file does not grow after 21,649,070 KB

The distro virtual disk is `C:\Users\Sm\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx` is `49,632,256 KB` in size

### **My goal is to move the location of my WSL disk from `C:` drive to another drive (`F:`)**

I am able to successfully export other distributions (Ubuntu 22).

I am using an Nvme ssd disk (2TB) SAMSUNG SSD 980 PRO and have achieved "Sequential Write" of `5179 MB/s` and Random write speed of `188964 IOPS`
The source disk `C:\` drive has been tested to `7117 MB/s`

### Expected Behavior

I would expect the export (either tar or -vhd) to complete

### Actual Behavior

`wsl --export  Ubuntu-18.04 --vhd f:\wsl2\ubuntu18.vhdx`

`Export in progress, this may take a few minutes.
Data error (cyclic redundancy check).
Error code: Wsl/Service/0x80070017`

### Diagnostic Logs

I booted in safe mode and ran `sfc /scanfile=C:\Users\Sm\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx`  This reports an error:

`Windows Resource Protection could not perform the requested operation.`

chkdsk does not report any problems.

**Comment by asubmani** [comment]
I am also unable to manually copy the file `C:\Users\sm\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx`  to another location.

I get a "Can't read from the source file or disk"

**Comment by herry1234** [comment]
having the same issue. in my case, vhd is about 23GB and copy abort at around 10GB

**Comment by Tony-Lowe** [comment]
Has anyone found the solution? My vhd is about 389GB and copy abort at 372MB.

**Comment by corrupted-bios** [comment]
Same thing happens to me, even tried booting into a linux system, but copy still fails

**Comment by strongQ** [comment]
having the same issue, please help me ,this is a bug.

**Comment by iamqiz** [comment]
same issue when exporting VHD
```
wsl --export Ubuntu-20.04 "J:\wsl-export\ubuntu-ext4.vhdx" --format vhd
正在导出，这可能需要几分钟时间。 (23584 MB)

数据错误(循环冗余检查)。
错误代码: Wsl/Service/0x80070017
```
