### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by Xcaliburr101** [microsoft/WSL#8921]
### Version

WSL version: 0.67.6.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

kali linux

### Other Software

**nessusd**
`systemctl start nessusd`

### Repro Steps

I made a new file in my user profile called `.wslconfig` and added the` [boot] systemd=true` (the file was not present yet)
I made a file called wsl.conf in `/etc/wsl.conf` and added the same data as above
I restarted wsl in powershell with `wsl --shutdown`

systemctl list-unit-files --type=service **does**  work, what indicates to me that systemd works

### Expected Behavior

Program (nessus) starts

### Actual Behavior

System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down

### Diagnostic Logs

[WslLogs-2022-09-29_11-57-04.zip](https://github.com/microsoft/WSL/files/9673527/WslLogs-2022-09-29_11-57-04.zip)

**Comment by benhillis** [comment]
interesting, can you share the output of 'ps -auxf'?

**Comment by Xcaliburr101** [comment]
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2408  1804 ?        Sl   09:35   0:00 /init
root         7  0.0  0.0   2412   112 ?        Ss   09:35   0:00 /init
root         8  0.0  0.0   2428   116 ?        S    09:35   0:00  \_ /init
xcalibu+     9  0.6  0.1 160360  8324 pts/0    Ssl  09:35   0:00      \_ -fish
xcalibu+    25  0.0  0.0   9860  3184 pts/0    R+   09:35   0:00          \_ ps -auxf

**Comment by Xcaliburr101** [comment]
[psoutput.txt](https://github.com/microsoft/WSL/files/9682870/psoutput.txt)

**Comment by Xcaliburr101** [comment]
> interesting, can you share the output of `ps -auxf` ?
[psoutput.txt](https://github.com/microsoft/WSL/files/9682890/psoutput.txt)

**Comment by BuddyBalkan** [comment]
i meet the same problem with the Author's. this is mine.
[psoutput.txt](https://github.com/microsoft/WSL/files/9927268/psoutput.txt)

**Comment by Xcaliburr101** [comment]
Hey, my issue was an typo in the file I made in wsl. Please check for that
:)
