### ISSUE TITLE
Kernel version in wsl --version differs in uname -r

### ISSUE THREAD

**Issue by guilherme-argentino** [microsoft/WSL#8929]
### Version

Microsoft Windows [versão 10.0.19044.2075]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04.1 LTS

### Repro Steps

Updating
sudo apt update
sudo apt dist-upgrade
sudo do-release-upgrade

`
PS C:\Users\rrant> wsl.exe --status
Distribuição Padrão: Ubuntu
Versão Padrão: 2

O Subsistema do Windows para Linux foi atualizado pela última vez em 29/09/2022
As atualizações automáticas da WSL estão ativadas.

Versão do kernel: 5.10.102.1
PS C:\Users\rrant> wsl lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
`

### Expected Behavior

Kernel 5 in distrib

### Actual Behavior

Kernel 4 still in distrib

### Diagnostic Logs

[WslLogs-2022-09-30_02-06-20.zip](https://github.com/microsoft/WSL/files/9680909/WslLogs-2022-09-30_02-06-20.zip)

**Comment by guilherme-argentino** [comment]
PS C:\Users\rrant\collect-wsl-logs> wsl uname -r
4.19.128-microsoft-standard
PS C:\Users\rrant\collect-wsl-logs>

**Comment by NotTheDr01ds** [comment]
Your `.wslconfig` shows a custom kernel.  Remove that line ;-).  It's found in your Windows (not WSL) profile directory.

**Comment by benhillis** [comment]
Yes, `wsl.exe --version` will show the version of the kernel that is packaged with WSL. Not the custom kernel you may be using.

**Comment by 0xdrop** [comment]
I have a error that is somehow equal to this one. 

```
# ls /lib/modules

6.0.0-kali3-amd64
```
```
# uname -r

5.15.79.1-microsoft-standard-WSL2
```
depmod or modprobe only looks for the result of uname -r. 

The error below:
`depmod: ERROR: could not open directory /lib/modules/5.15.79.1-microsoft-standard-WSL2: No such file or directory`

Any sort of fix?

**Comment by Biswa96** [comment]
> Any sort of fix?

Compile those kernel modules for the Linux kernel used in WSL2. Source code of that can be found here https://github.com/microsoft/WSL2-Linux-Kernel

**Comment by 0xdrop** [comment]
@Biswa96 How do I should this?

**Comment by Biswa96** [comment]
The procedure can not be summarize in a single comment. This documentation may help https://docs.kernel.org/kbuild/modules.html. Also other articles can be found through [here](https://www.google.com/search?q=compile+Linux+kernel+module).

**Comment by 0xdrop** [comment]
Could not get it

WSL does not have its /lib/modules/___/build folder and I cant understand how to compile it
