### ISSUE TITLE
How to disable the use of dedicated GPU in WSL ?

### ISSUE THREAD

**Issue by AnMaillard** [microsoft/WSL#8931]
Hi ! 

I am using WSL 2 (Ubuntu 22.04, with kernel 5.15.62.1) on Windows 11 22622.601 on my laptop (Surface Book 2). The issue I have is that since the use of the discrete GPU in WSL was activated, everytime I use WSL my dedicated GPU gets in use, so I can not use the detach feature of the Surface Book, and moreover my battery drains much more rapidly. 

Is there a way to deactivate / remove the nvidia drivers from WSL so that it does not use the GPU everytime it is on ? (I really have no need for GUI graphics in WSL). I did not find any nvidia package installed in WSL, so I assume that these drivers are built in the WSL system.

Thanks a lot !

**Comment by benhillis** [comment]
Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig

%userprofile%\\.wslconfig
```
[wsl2]
gpuSupport=false
```

**Comment by DariuszRybak** [comment]
I have the same issue as @AnMaillard but on G14. the given solution didnt worked and Ubuntu triggers dGPU. The only fix is to restart WSL service.

**Comment by masi0** [comment]
I have the same issue as @AnMaillard and given solution didn't resolved the dGPU triggering when Ubuntu starts. Only fix is to manually restart WSL service. I have removed nvidia/cuda drivers from Linux but this also didnt helped.

**Comment by chuanjin-su** [comment]
> I have the same issue as @AnMaillard and given solution didn't resolved the dGPU triggering when Ubuntu starts. Only fix is to manually restart WSL service. I have removed nvidia/cuda drivers from Linux but this also didnt helped.

It seems that add the folloing into `C:\Users\[your user name]\.wslgconfig` (note it's `wslgconfig` rather than `wslconfig`) works for me:

```
[system-distro-env]
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1
```

Ref: [https://github.com/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging](https://github.com/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging), [https://www.v2ex.com/t/848703](https://www.v2ex.com/t/848703)

**Comment by masi0** [comment]
Thanks, but this still doesnt work. Each time Ubuntu starts, Nvidia Kicks in.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.02    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    10W /  N/A |     11MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        27      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

**Comment by DaDummy** [comment]
For anyone running into the same issue. The solution by @benhillis does work, but is missing a step:

You need to reboot your system or run `wsl --shutdown` after changing the config file for it to become effective.

> Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> 
> %userprofile%\.wslconfig
> 
> ```
> [wsl2]
> gpuSupport=false
> ```

**Comment by hamedhf** [comment]
> Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> 
> %userprofile%\.wslconfig
> 
> ```
> [wsl2]
> gpuSupport=false
> ```

Is it possible to do this per distro?
I created a config file (/etc/wsl.conf) and added the configs you said but it didn't work.

**Comment by georgealar** [comment]
> For anyone running into the same issue. The solution by @benhillis does work, but is missing a step:
> 
> You need to reboot your system or run `wsl --shutdown` after changing the config file for it to become effective.
> 
> > Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> > %userprofile%.wslconfig
> > ```
> > [wsl2]
> > gpuSupport=false
> > ```

thank you a lot! works perfectly 👌

**Comment by vathanac** [comment]
> For anyone running into the same issue. The solution by @benhillis does work, but is missing a step:
> 
> You need to reboot your system or run `wsl --shutdown` after changing the config file for it to become effective.
> 
> > Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> > %userprofile%.wslconfig
> > ```
> > [wsl2]
> > gpuSupport=false
> > ```

What if I want GPU acceleration and didn't want Nvidia GPU turn on when using laptop on battery.

**Comment by DaDummy** [comment]
> > For anyone running into the same issue. The solution by @benhillis does work, but is missing a step:
> > You need to reboot your system or run `wsl --shutdown` after changing the config file for it to become effective.
> > > Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> > > %userprofile%.wslconfig
> > > ```
> > > [wsl2]
> > > gpuSupport=false
> > > ```
> 
> What if I want GPU acceleration and didn't want Nvidia GPU turn on when using laptop on battery.

You could write two batch scripts that adjust the config and restart wsl and then toggle it on whenever you use it and keep it off otherwise. Since this involves stopping wsl I wouldn't automate that on battery status change as that might not always be the right time to kill all wsl processes :)

So far it appears that there is no support for on-demand APIs like DRI PRIME to toggle the GPU state but instead it's pretty much as bad as it is on native Linux with nvidia GPUs in that you'll have to manually toggle it and then restart your session. I'd suggest opening a new issue for that in case this would work for you as well.

**Comment by vathanac** [comment]
> > > For anyone running into the same issue. The solution by @benhillis does work, but is missing a step:
> > > You need to reboot your system or run `wsl --shutdown` after changing the config file for it to become effective.
> > > > Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> > > > %userprofile%.wslconfig
> > > > ```
> > > > [wsl2]
> > > > gpuSupport=false
> > > > ```
> > 
> > 
> > What if I want GPU acceleration and didn't want Nvidia GPU turn on when using laptop on battery.
> 
> You could write two batch scripts that adjust the config and restart wsl and then toggle it on whenever you use it and keep it off otherwise. Since this involves stopping wsl I wouldn't automate that on battery status change as that might not always be the right time to kill all wsl processes :)
> 
> So far it appears that there is no support for on-demand APIs like DRI PRIME to toggle the GPU state but instead it's pretty much as bad as it is on native Linux with nvidia GPUs in that you'll have to manually toggle it and then restart your session. I'd suggest opening a new issue for that in case this would work for you as well.

I don't want to automate it. I mean when I run [`export MESA_D3D12_DEFAULT_ADAPTER_NAME=INTEL`](https://github.com/microsoft/wslg/wiki/GPU-selection-in-WSLg) and `glxinfo -B` it switched to intel gpu, but Nvidia Gpu still on as [mention here](https://github.com/microsoft/WSL/issues/8931#issuecomment-1327360837).

**Comment by TheBestPessimist** [comment]
@benhillis the help page is not yet updated. Please reopen this issue.

![image](https://user-images.githubusercontent.com/4482210/229992287-3fe9bca5-1804-4bf2-8241-2da97a747abd.png)

**Comment by githubuser6000** [comment]
Please reopen @benhillis

**Comment by ThatOtherAndrew** [comment]
Same issue here. I would like to use hardware acceleration, however only on the integrated GPU. Is this possible to do through e.g. Windows graphics settings?

**Comment by KyleRAnderson** [comment]
I was looking for this today on the docs page for `.wslconfig`, it seems like it's still not mentioned there. Would be really nice to update those docs.

**Comment by githubuser6000** [comment]
Disabling GPU acceleration from .wslconfig isn't useful as (from my understanding) it disables all hardware acceleration, when we just want it to use the integrated GPU (with hardware acceleration, just from a more efficient device). 

I doubt MS is going to fix this as it took them ages to bring back task manager on taskbar, and this problem is definitely their concerns, so probably never going to get fixed. And this issue hasn't been re-opened. 

I have been using this to disable gpu, launch wsl, and then re-enable it after the first shell launches. This prevents dGPU usage. 

These need to be executed as admin. And since `sudo` isn't a thing, I couldn't automate this without also launching wsl as admin. Maybe I just need to switch to Linux. Thank for the push I guess, MS. 
```
Get-PnpDevice -Class Display -FriendlyName "*nvidia*" | Disable-PnpDevice -Confirm:$false
```

To enable it again, 

```
Get-PnpDevice -Class Display -FriendlyName "*nvidia*" | Enable-PnpDevice -Confirm:$false
```

**Comment by ThaDaVos** [comment]
I couldn't find a feature request for this and as I also am having this issue but with a notebook with intel Integrated and NVidia RTX 3080 TI - I created a feature request for it as this issue seems to be ignored.

Please go upvote the request (or leave comment with your setup and what you have tried)

**Comment by Lewiscowles1986** [comment]
Hilariously, I encountered this on a Microsoft Dev Kit 😆 I think they've done a pretty amazing job to be clear. This was surprising, but not the end of the world.

**Comment by LandChit** [comment]
> Yep! Looks like we need to update our docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
> 
> %userprofile%\.wslconfig
> 
> ```
> [wsl2]
> gpuSupport=false
> ```

did this but it now falls back to llvmpipe
