### ISSUE TITLE
The WSL cannot be used

### ISSUE THREAD

**Issue by ybqdren** [microsoft/WSL#8933]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I cannot get WSL information through `wsl -l -v` command in the terminal, it is always in a stalling state, I confirm that there is WSL in my process.

### Expected Behavior

WSL information should be displayed correctly:
![image](https://user-images.githubusercontent.com/46752566/193393952-ca2e295e-bca9-4b4f-ad86-7e383fad021f.png)

### Actual Behavior

The instruction to execute the WSL is always in a blocking state, with no return and no stop.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/46752566/193394018-8b4135a6-8afa-4da1-bf0f-a8ecf7c783be.png">

In fact, this is the second time I've had this problem, before I fixed it by [resetting the network](https://github.com/docker/for-win/issues/12576#issuecomment-1193311913), which did solve my problem, but it happened again today.

### Diagnostic Logs

```
'Virtual Machine' failed to restore. (Virtual machine ID BDE5013F-116B-4654-A625-CA75D2A590B5)

'Virtual Machine' Virtual SMB Device (Instance ID FEA6E63B-45DA-4E32-8B3D-1873B2CE50E7): Failed to restore with Error 'Cannot restore this virtual machine because a file read from the vSMB saved state data could not be found. Delete the saved state data and then try to start the virtual machine. ' (0xC0370400). (Virtual machine ID BDE5013F-116B-4654-A625-CA75D2A590B5)
```

**Comment by benhillis** [comment]
Looks like something probably crashed when you tried to install the first time. I suggest doing `wsl.exe --unregister <distro>` and re-trying (with tracing enabled).
