### ISSUE TITLE
systemd graceful shutdown

### ISSUE THREAD

**Issue by hi0t** [microsoft/WSL#8939]
### Version

Windows version: 10.0.22621.608

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Ubuntu 20.04

### Other Software

WSL version: 0.68.2.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44

### Repro Steps

1. enable systemd support:
```
[boot]
systemd=true
```
2. install Docker Engine
3. log off from WSL
4. wait until the distribution goes into the stooped state
5. log in again
6. check `journalctl -u docker`

### Expected Behavior

the logs show that WSL interrupts the service:
```
Oct 03 10:12:56 Ubuntu dockerd[430]: time="2022-10-03T10:12:56.975405500+03:00" level=info msg="Docker daemon" commit=>
Oct 03 10:12:56 Ubuntu dockerd[430]: time="2022-10-03T10:12:56.975796200+03:00" level=info msg="Daemon has completed i>
Oct 03 10:12:57 Ubuntu systemd[1]: Started Docker Application Container Engine.
Oct 03 10:12:57 Ubuntu dockerd[430]: time="2022-10-03T10:12:57.247919800+03:00" level=info msg="API listen on /run/doc>
Oct 03 10:13:52 Ubuntu systemd[1]: Starting Docker Application Container Engine...
Oct 03 10:13:52 Ubuntu dockerd[426]: time="2022-10-03T10:13:52.568264690+03:00" level=info msg="Starting up"
Oct 03 10:13:52 Ubuntu dockerd[426]: time="2022-10-03T10:13:52.572733188+03:00" level=info msg="parsed scheme: \"unix\>
```

### Actual Behavior

WSL should execute `systemctl poweroff` command and gracefully shut down all services. Such behavior can be dangerous for services such as data bases.

**Comment by cerebrate** [comment]
That is what I had assumed as well, but this seems to suggest that isn't true. Also, while I haven't worked out a test for it myself yet, I do note that idle timeouts seem to end the WSL instance notably faster than manually running `systemctl poweroff`.
