### ISSUE TITLE
WSL hangs repeatedly when vscode indexing files.

### ISSUE THREAD

**Issue by roja45** [microsoft/WSL#8941]
### Version

Microsoft Windows [Version 10.0.22622.598]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Ubuntu 20.04

### Repro Steps

I have vscode and intellisense installed.  After a while, usually while indexing, vmmemWSl maxes out the CPU and the wsl instance freezes.  only killing the windows subsystem for linux process in task manager lets me restart it again.

### Expected Behavior

it to not crash every hour or so.

### Actual Behavior

Crashing, unresponsive, unusable.

Error message sometimes
```
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Error code: Wsl/Service/0x8007274c

[process exited with code 4294967295 (0xffffffff)]
```

### Diagnostic Logs

[WslLogs-2022-10-03_10-41-28.zip](https://github.com/microsoft/WSL/files/9696850/WslLogs-2022-10-03_10-41-28.zip)

[WslLogs-2022-10-03_13-32-42.zip](https://github.com/microsoft/WSL/files/9697602/WslLogs-2022-10-03_13-32-42.zip)

**Comment by arjun-phuyel** [comment]
my vs code editor terminal frequently terminated showing some exit code
any solution for this annoying kind of behaviour of vs code

**Comment by roja45** [comment]
Closing this and following #8824 as that is exactly the issue I am facing.
