### ISSUE TITLE
WSL does not start at all, all commands return blank

### ISSUE THREAD

**Issue by DariusChit** [microsoft/WSL#8945]
### Version

10.0.19043.2006

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I attempted to install the latest Ubuntu version (the first time I have tried installing Linux on this machine). I also tried using wsl --help and such commands

### Expected Behavior

Ubuntu would install and the commands would do their required job.

### Actual Behavior

I get the following error message from Ubuntu:
Please restart WSL with the following command and try again:
wsl --shutdown
wsl -- unregister DISTRO_NAME

however, whenever I try to use any wsl commands there is no output what so ever and the terminal is ready for another command

**Comment by mzmoosa01** [comment]
I'm also dealing with this issue.
