### ISSUE TITLE
Linux terminal disappears after sleep

### ISSUE THREAD

**Issue by tsteven4** [microsoft/WSL#8947]
### Version

Microsoft Windows [Version 10.0.22621.608]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu-22.04

### Other Software

Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.608

### Repro Steps

start Ubuntu-22.04 from start menu.
let computer go to sleep
wake up computer
repeat until terminal window disappears.  In this case it took two wake ups.

### Expected Behavior

I expect the terminal window to still be present.

### Actual Behavior

The terminal window is gone.  wsl -l -v reports
``` 
NAME            STATE           VERSION
* Ubuntu-22.04    Stopped         2
```

### Diagnostic Logs

[WslLogs-2022-10-04_09-56-31.zip](https://github.com/microsoft/WSL/files/9708807/WslLogs-2022-10-04_09-56-31.zip)

**Comment by zadjii-msft** [comment]
What Terminal application are you using? Conhost, the Windows Terminal, or something else?

If you're using the Windows Terminal, you might want to look at https://github.com/microsoft/terminal/issues/12513#issuecomment-1369795207. If that's set to Always, then you might be hitting some variation of https://github.com/microsoft/terminal/issues/14483, if you're on 1.15.x.

**Comment by tsteven4** [comment]
I rebuilt my system and I haven't experienced this issue since, although not enough time has passed to be definitive.  I am using windows terminal, and it is set to power optimized.  I think my original issue might have been at least partially explained by bugchecks rebooting the machine.  I was certainly getting some bugchecks, but I am not sure if they explained all the lost terminal sessions.  Before the rebuild I was also using windows terminal, but I can't verify the version or what the background apps permissions were.

I am now running windows terminal 1.15.3466.0 and
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.963
