### ISSUE TITLE
WSL2 (Preview) cannot run .exe files: exec format error: wsl.exe

### ISSUE THREAD

**Issue by blami** [microsoft/WSL#8952]
### Version

Microsoft Windows [Version 10.0.22621.521]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

systemd 249.11-0ubuntu3.3

WSL version: 0.68.2.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

### Repro Steps

- [optional] disable wslg
- [optional] enable `systemd` support
- make sure `interop` is __not disabled__
- attempt to run `wsl.exe --version` from any shell inside WSL2
- `ls /proc/sys/fs/binfmt_misc/` for presence of `WSLInterop`

### Expected Behavior

- `wsl.exe` will exe will execute and output version on terminal
- `/proc/sys/fs/binfmt_misc/` will contain custom binary format for WSL interop

### Actual Behavior

After upgrade to preview version of WSL2 (ver. 0.68.2.0 from Github on non-Insider build) it was possible to run Windows binaries from within WSL2 by simply having them in `PATH` and typing `binary.exe` with `systemd` enabled and disabled.

After Windows build 22H2 upgrade this is not longer possible. Shell sees binaries in PATH but its not possible to run them, error message being `exec format error: wsl.exe`. After further inspection I found WSL interop is not registered with `binfmt_misc`:
``` shell
~ $ ls /proc/sys/fs/binfmt_misc/
llvm-15-runtime.binfmt  qemu-arm     qemu-mips64el  qemu-riscv64  register
qemu-aarch64            qemu-mips64  qemu-ppc64le   qemu-s390x    status
```

After upgrade I noticed Hypervisor Platform was disabled although I am sure I had it enabled before. I reenabled it but it didn't solve the issue.

### Diagnostic Logs

``` shell 
~ $ cat /etc/wsl.conf
[boot]
systemd = true

[automount]
enabled = true
mountFsTab = true
root = /mnt/
options = "metadata,umask=2,fmask=1,case=off"

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
```

``` shell
~ $ cat /mnt/c/Users/blami/.wslconfig
[wsl2]
guiApplications = false
```

**Comment by blami** [comment]
I collected logs while trying to run `wsl.exe`. 

There's repeating exception trace: `D:\a\1\s\src\windows\common\svccomm.cpp(95)\wsl.exe!00007FF6EF4D3D14: (caller: 00007FF6EF4D07F6) Exception(1) tid(1840) 80070006 The handle is invalid. "`

[WslLogs-2022-10-05_17-08-44.zip](https://github.com/microsoft/WSL/files/9713946/WslLogs-2022-10-05_17-08-44.zip)

**Comment by blami** [comment]
Disabling systemd support in `/etc/wsl.conf` resolves the issue. 

``` shell
~ $ cat /etc/wsl.conf
[boot]
#systemd = true

[automount]
enabled = true
mountFsTab = true
root = /mnt/
options = "metadata,umask=2,fmask=1,case=off"

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
```

After `wsl.exe --shutdown` and relaunch:
``` shell
~ $ powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu\home\blami>

~ $ ls /proc/sys/fs/binfmt_misc
register  status  WSLInterop
```

**Comment by cerebrate** [comment]
That's exactly what it is. Specifically, it's #8843 , and I posted a workaround over in that issue.

**Comment by blami** [comment]
@cerebrate Thanks! Not sure why I did not find that one. Will mark mine as duplicate of it. And thanks for workaround. Did some reading and TIL how `binfmt` works!

**Comment by Dragon1573** [comment]
## Environments

- Microsoft Windows 11 Professional 22H2 (10.0.22621.1555)
- Windows Subsystem Linux (Version 2)
  - WSL Version 1.2.5.0
  - Kernel Version 5.15.90.1
  - WSLg Version 1.0.51
- Ubuntu 23.04 Lunar Lobster

## Details

I upgrade to Ubuntu 23.04 today by executing `do-release-upgrade`. After upgrade process, I find `wslfetch` goes wrong on my device.

<details><summary><code>systemd</code> enabled</summary>

```
21:39:41 ~/Documents 0ms $ wslfetch --colorbar --options "windows-build,windows-rel-branch,wsl-release,wsl-kernel,windows-uptime"
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
/usr/bin/wslfetch: line 233: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
/usr/bin/wslsys: line 233: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 233: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 233: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 441: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 233: /mnt/c/Windows/System32/reg.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 267: [: : integer expression expected
/usr/bin/wslsys: line 260: /mnt/c/Windows/System32/chcp.com: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 268: /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe: cannot execute binary file: Exec format error
/usr/bin/wslsys: line 270: [: : integer expression expected
/usr/bin/wslsys: line 260: /mnt/c/Windows/System32/chcp.com: cannot execute binary file: Exec format error
               .-/+oossssoo+/-.               Windows Subsystem for Linux (WSL1)
           `:+ssssssssssssssssss+:`           dragon1573@ubuntu.localhost
         -+ssssssssssssssssssyyssss+-         Build:
       .ossssssssssssssssssdMMMNysssso.       Branch:
      /ssssssssssshdmmNNmmyNMMMMhssssss/      Release: Ubuntu 23.04
     +ssssssssshmydMMMMMMMNddddyssssssss+     Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
    /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Uptime (Windows): 0d 0h 0m
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
    /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
     +sssssssssdmydMMMMMMMMddddyssssssss+
      /ssssssssssshdmNNNNmyNMMMMhssssss/
       .ossssssssssssssssssdMMMNysssso.
         -+sssssssssssssssssyyyssss+-
           `:+ssssssssssssssssss+:`
               .-/+oossssoo+/-.
21:39:45 ~/Documents 245ms $ ls /proc/sys/fs/binfmt_misc
jar  python3.11  register  status

21:40:41 ~/Documents 3ms $ code .
/usr/local/bin/code: 61: /mnt/d/Applications/WinGet/Microsoft/VSCode/Code.exe: Exec format error
```

</details> 

When switching `systemd = false` in `/etc/wsl.conf`, this issue does solved with some other informations.

<details><summary><code>systemd</code> disabled</summary>

```
21:42:41 ~/Documents 0ms $ ls /proc/sys/fs/binfmt_misc
register  status  WSLInterop
21:42:44 ~/Documents 9ms $ wslfetch --colorbar --options "windows-build,windows-rel-branch,wsl-release,wsl-kernel,windows-uptime"
找不到“GetEncoding”的重载，参数计数为:“0”。
所在位置 行:1 字符: 59
+ ... ing]::UTF8; [Console]::InputEncoding = [System.Text.Encoding]::GetEnc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

               .-/+oossssoo+/-.               Windows Subsystem for Linux (WSL2)
           `:+ssssssssssssssssss+:`           dragon1573@ubuntu.localhost
         -+ssssssssssssssssssyyssss+-         Build: 22621
       .ossssssssssssssssssdMMMNysssso.       Branch: ni_release
      /ssssssssssshdmmNNmmyNMMMMhssssss/      Release: Ubuntu 23.04
     +ssssssssshmydMMMMMMMNddddyssssssss+     Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
    /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Uptime (Windows): 0d 5h 12m
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
    /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
     +sssssssssdmydMMMMMMMMddddyssssssss+
      /ssssssssssshdmNNNNmyNMMMMhssssss/
       .ossssssssssssssssssdMMMNysssso.
         -+sssssssssssssssssyyyssss+-
           `:+ssssssssssssssssss+:`
               .-/+oossssoo+/-.
```

</details> 

My `/etc/wsl.conf` looks like follows:

```
[boot]
systemd = false

[network]
hostname = "ubuntu.localhost"

[interop]
enabled = true
appendWindowsPath = false

[user]
default = dragon1573

[automount]
enabled = true
mountFsTab = true
root = /mnt/
options = "metadata,umask=022,fmask=011"

[filesystem]
umask = 022
fmask = 011
```

**Comment by Mystic8b** [comment]
Same problem after upgrade to Ubuntu 23.04.
```
❯ code
/mnt/c/Users/mystic/AppData/Local/Programs/Microsoft VS Code/bin/code: 61: /mnt/c/Users/mystic/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error
❯ explorer.exe .
zsh: exec format error: explorer.exe
```

**Comment by ViniciusBastosTR** [comment]
Same issue here.

/etc/release

```shell
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Only works when disabling systemd

```shell
[user]
default=vinicius

[boot]
systemd=false
```

**Comment by the-moog** [comment]
The issue is that enabling systemd somehow alters `/proc/sys/fs/binfmt_misc/`
The file (or filelike??) entry `WSLInterop.conf` goes missing.

I've re-written the answer here rather than just linking as the original reference thread is getting rather long and has dead links.
The oneliner elimiates that problem.

The solution ([from here](https://github.com/microsoft/WSL/issues/8843#issuecomment-1255454596)) is to replace that file.  Windows executable files start with the two letters `MZ`
The following tells Linux what to do when trying to run files that start with those letters.
```
sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
sudo systemctl restart systemd-binfmt
```
I;m using the 23.04 image from links in [this post](https://github.com/CloudBytes-Academy/CloudBytes.dev/discussions/140)
I guess this is a bug in packaging, or during installation, but I've no idea who to tell.

**Comment by tardis89** [comment]
@the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
```
sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
sudo systemctl unmask systemd-binfmt.service
sudo systemctl restart systemd-binfmt
sudo systemctl mask systemd-binfmt.service
```

**Comment by khushal123** [comment]
just in case if anyone is still facing the issue, try disabling systemd in /etc/wsl.conf in the distro.

**Comment by renanlido** [comment]
> just in case if anyone is still facing the issue, try disabling systemd in /etc/wsl.conf in the distro.

Thanks man! This worked for me!

**Comment by hros** [comment]
Thanks @tardis89 
The command solves the issue, and now `code` starts from `wsl`.
Can you explain what was the problem, and how do these command solve the issue?


> @the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
> 
> ```
> sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> sudo systemctl unmask systemd-binfmt.service
> sudo systemctl restart systemd-binfmt
> sudo systemctl mask systemd-binfmt.service
> ```

**Comment by abrahamprz** [comment]
> The issue is that enabling systemd somehow alters `/proc/sys/fs/binfmt_misc/` The file (or filelike??) entry `WSLInterop.conf` goes missing.
> 
> I've re-written the answer here rather than just linking as the original reference thread is getting rather long and has dead links. The oneliner elimiates that problem.
> 
> The solution ([from here](https://github.com/microsoft/WSL/issues/8843#issuecomment-1255454596)) is to replace that file. Windows executable files start with the two letters `MZ` The following tells Linux what to do when trying to run files that start with those letters.
> 
> ```
> sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> sudo systemctl restart systemd-binfmt
> ```
> 
> I;m using the 23.04 image from links in [this post](https://github.com/CloudBytes-Academy/CloudBytes.dev/discussions/140) I guess this is a bug in packaging, or during installation, but I've no idea who to tell.

Thanks for the solution!

**Comment by sanjayojha** [comment]
> @the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
> 
> ```
> sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> sudo systemctl unmask systemd-binfmt.service
> sudo systemctl restart systemd-binfmt
> sudo systemctl mask systemd-binfmt.service
> ```

Thank you so much. It solved my problem.
Not only this I had problem in running ddev launch command it also fixed it.

**Comment by bpkroth** [comment]
[like]  Brian Kroth (GSL) reacted to your message:
________________________________

**Comment by sanjaybip** [comment]
> > > @the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
> > > ```
> > > sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> > > sudo systemctl unmask systemd-binfmt.service
> > > sudo systemctl restart systemd-binfmt
> > > sudo systemctl mask systemd-binfmt.service
> > > ```
> > 
> > 
> > Thank you so much. It solved my problem. Not only this I had problem in running ddev launch command it also fixed it.
> 
> For me this helps but it doesn't solve it, because the problem reappears later and I need to run these commands again!

Not sure why, but there is no such problem on my side. The mentioned solution fixed it for once and all.

**Comment by aravindsomaraj** [comment]
> The issue is that enabling systemd somehow alters `/proc/sys/fs/binfmt_misc/` The file (or filelike??) entry `WSLInterop.conf` goes missing.
> 
> I've re-written the answer here rather than just linking as the original reference thread is getting rather long and has dead links. The oneliner elimiates that problem.
> 
> The solution ([from here](https://github.com/microsoft/WSL/issues/8843#issuecomment-1255454596)) is to replace that file. Windows executable files start with the two letters `MZ` The following tells Linux what to do when trying to run files that start with those letters.
> 
> ```
> sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> sudo systemctl restart systemd-binfmt
> ```
> 
> I;m using the 23.04 image from links in [this post](https://github.com/CloudBytes-Academy/CloudBytes.dev/discussions/140) I guess this is a bug in packaging, or during installation, but I've no idea who to tell.

Works perfectly! Thank you...

**Comment by Eliezer134** [comment]
> > The issue is that enabling systemd somehow alters `/proc/sys/fs/binfmt_misc/` The file (or filelike??) entry `WSLInterop.conf` goes missing.
> > I've re-written the answer here rather than just linking as the original reference thread is getting rather long and has dead links. The oneliner elimiates that problem.
> > The solution ([from here](https://github.com/microsoft/WSL/issues/8843#issuecomment-1255454596)) is to replace that file. Windows executable files start with the two letters `MZ` The following tells Linux what to do when trying to run files that start with those letters.
> > ```
> > sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> > sudo systemctl restart systemd-binfmt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I;m using the 23.04 image from links in [this post](https://github.com/CloudBytes-Academy/CloudBytes.dev/discussions/140) I guess this is a bug in packaging, or during installation, but I've no idea who to tell.
> 
> Thanks for the solution!

Muchísimas gracias, esos 2 comandos me solucionaron el problema.

**Comment by stephanlamoureux** [comment]
I am getting this error because of minikube. The commands above would fix the problem until I ran minikube again. Are there any other options?

**Comment by akagami-harsh** [comment]
> > > @the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
> > > ```
> > > sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> > > sudo systemctl unmask systemd-binfmt.service
> > > sudo systemctl restart systemd-binfmt
> > > sudo systemctl mask systemd-binfmt.service
> > > ```
> > 
> > 
> > Thank you so much. It solved my problem. Not only this I had problem in running ddev launch command it also fixed it.
> 
> For me this helps but it doesn't solve it, because the problem reappears later and I need to run these commands again!

me too getting the same problem

**Comment by stephanlamoureux** [comment]
> I am getting this error because of minikube. The commands above would fix the problem until I ran minikube again. Are there any other options?

My only fix was to stop using Docker Desktop and to manually install docker onto WSL. After that, minikube stopped breaking my command line.

**Comment by FilipeVMartins** [comment]
> @the-moog's solution worked! The only extra step I had to add was unmasking the systemd-binfmt service in order to get it working. So to add to his steps. I unmask the service, restart it, then re-mask it to return it back to its previous protected state besides the new modification.
> 
> ```
> sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
> sudo systemctl unmask systemd-binfmt.service
> sudo systemctl restart systemd-binfmt
> sudo systemctl mask systemd-binfmt.service
> ```

thanks that worked for me, just had to also restart wsl

**Comment by surgiie** [comment]
Solutions here didnt work for me for vscode 😭 

`/mnt/d/Microsoft VS Code/bin/code: 61: /mnt/d/Microsoft VS Code/Code.exe: Exec format error` 

The only thing that **_temporarily_** fixes the issue for me:

1. open `cmd`
2. run `wsl`
3. `rm -rf ~/.vscode-server`
4. exit
5. back in cmd terminal, run: `wsl --shutdown`
6. relaunch `wsl`

VS code will work for a short period before the error randomly comes back and I have to repeat my steps.

Anybody else having this issue or know of a permanent fix?

**Comment by keivanipchihagh** [comment]
In my case, I found out my Docker Desktop wasn't running (:

**Comment by trallnag** [comment]
For me restarting the distribution was sufficient. @surgiie have you tried it without uninstall vscode server? It should not be related to the problem, as it is Windows interop in general

**Comment by krystan** [comment]
running docker desktop with container d support running causes this issue the only way to solve it is not to use container d support or to shut down launch vscode then restart which is quite frankly a terrible solution, anyone any other ideas? this is not a solved problem

**Comment by tassoman** [comment]
Solved updating Docker Desktop 🤷

**Comment by goranovs** [comment]
Only https://github.com/microsoft/WSL/issues/8952#issuecomment-2019312519 worked for me. The issue happened after Docker Desktop update 4.54.0.

**Comment by mnorrsken** [comment]
I am having the same issue intermittently, can be solved temporarily by restarting wsl with wsl --shutdown but would really like a permanent fix.

**Comment by acelinkio** [comment]
Encountered this issue with Windows 11 2025H2.  Had to do the solution that others mentioned with 
```sh
wsl --shutdown
```

**Comment by joaquimbarreto** [comment]
@surgiie solution worked for me just now so I do not know if it is only temporary. I thought that it was because I just finished installing Android Studio and I made the following alias on bash: alias studio="/snap/bin/android-studio > /dev/null 2>&1 &" and maybe it had to do with something with /dev/null

> The only thing that **_temporarily_** fixes the issue for me:
> 
> 1. open cmd
> 2. run `wsl`
> 3. `rm -rf ~/.vscode-server`
> 4. exit
> 5. back in cmd terminal, run: `wsl --shutdown`
> 6. relaunch wsl
> 
> VS code will work for a short period before the error randomly comes back and I have to repeat my steps.
> 
> Anybody else having this issue or know of a permanent fix?

**Comment by Edison0019** [comment]
> For me restarting the distribution was sufficient. [@surgiie](https://github.com/surgiie) have you tried it without uninstall vscode server? It should not be related to the problem, as it is Windows interop in general

This solution worked for me

**Comment by sondretordal** [comment]
I also experience this issue after installing Windows 2025H2, doing the `wsl --shutdown` and reopening the WSL distro works to get the `code .` working, but it is a pretty annoying workaround.

**Comment by NafeesMadni** [comment]
I had the same issue, but a device restart fixed it. The command is working fine now. Even when I tried to access Antigravity, i got the same issue.

**Comment by monaabishek2003** [comment]
For me restarting the distribution worked as mentioned by many here.
```
wsl --shutdown
```

**Comment by itsjayeshrathi** [comment]
Docker Desktop overwrites wsl.conf on startup, breaking application launches. Use `sudo chattr +i` to lock it. To edit, use `sudo chattr -i` to unlock, make changes, run `wsl --shutdown` to restart, then re-lock with `sudo chattr +i`.

**Comment by bigsk1** [comment]
if needing systemd and windows  .exe files not working, 

My issue

systemd-binfmt had been masked, so the WSL interop binfmt handler was missing; restarting/unmasking it brought WSLInterop back

My fix was

```bash
sudo systemctl daemon-reload
sudo systemctl unmask systemd-binfmt
sudo systemctl restart systemd-binfmt
ls /proc/sys/fs/binfmt_misc
```

**Comment by amindev7** [comment]
On WSL Ubuntu 22.04, installing binfmt-support solved the issue for me

`sudo apt install binfmt-support`

**Comment by rromerson** [comment]
as per @amindev7, 
`sudo apt install binfmt-support` 
worked for me!

**Comment by joegajeckyj-gl** [comment]
for f in /proc/sys/fs/binfmt_misc/qemu-*; do echo -1 | sudo tee "$f" > /dev/null; done

worked for me

**Comment by markeissler** [comment]
Is this still an ongoing issue? Just happened to me after updating wsl2 to `2.7.3.0` and docker-desktop to `4.73.0` on Windows 11 Pro. What a huge pain.

After finally being able to get desktop to launch using PowerToys Command Palette (nothing else seems to work), I started getting this error in Ubuntu when running `code .` in a WSL directory....it's something I always do.

Instead of immediately running `wsl --shutdown` I ran `nala update` followed by `nala upgrade` (you could just run the `apt` commands of course). And then also ran `brew update` and `brew upgrade` because I may as well. Then quit docker-desktop. Then ran `wsl --shutdown`. Then started docker-desktop. I discovered long ago that I have to let docker-desktop start WSL otherwise other weird things happen once I open a terminal, which launches Ubuntu by default.

**Comment by Mystic8b** [comment]
> Is this still an ongoing issue?

I haven't encountered this problem in about three years, but many other people have faced it during that time. It seems that no one has figured out why it happens yet.

**Comment by markeissler** [comment]
I'm wondering if it's a systemd-related issue as the `nala upgrade` did apply some systemd updates. There are reports comments in here that discuss disabling systemd in wsl.conf. But yeah, this was the first time I came across this problem which is how I landed here, on a `closed` issue.

**Comment by shaneknapp** [comment]
> > Is this still an ongoing issue?
> 
> I haven't encountered this problem in about three years, but many other people have faced it during that time. It seems that no one has figured out why it happens yet.

it still randomly happens to me (as of ~15m ago), and the `sysctl` cycle fixed it:

```
(base) ➜  ~ code
/c/Users/XXX/AppData/Local/Programs/Microsoft VS Code/bin/code: 62: /c/Users/XXX/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error
(base) ➜  ~ cat /usr/lib/binfmt.d/WSLInterop.conf
:WSLInterop:M::MZ::/init:PF
(base) ➜  ~ sudo systemctl unmask systemd-binfmt.service
sudo systemctl restart systemd-binfmt
sudo systemctl mask systemd-binfmt.service
Removed "/etc/systemd/system/systemd-binfmt.service".
Created symlink /etc/systemd/system/systemd-binfmt.service → /dev/null.
```
