### ISSUE TITLE
wslhost.exe holding onto folder

### ISSUE THREAD

**Issue by dailytabs** [microsoft/WSL#8956]
Downloaded a zip. Extracted it to Windows Desktop folder. Navigated to it in WSL2 Ubuntu using Windows Terminal's "Open in Terminal" context menu entry. The directory did not open, I was prompted for my ssh password to unlock my agent, after entering pw the directory still did not open (this is expected, as I have a `cd` in my bash profile that breaks it). `cd`'d manually into `/mnt/c/Users/.../Desktop` and went into a sub-dir of the extract. Performed a single grep and exited the Terminal.

Tried to delete the extract folder and Windows refused, saying it was still open by another process. Used resource manager to track it down to `wslhost.exe` keeping the sub-dir (where I ran the grep command from) opened.

I'd expect folder handles to be properly dropped when no longer in use.

Restarting PC or WSL is only fix I know of.

**Comment by benhillis** [comment]
Thanks for posting, do you have firm set of repro steps? I tried this and wasn't able to repro.
