### ISSUE TITLE
port range forwarding to WSL

### ISSUE THREAD

**Issue by dkalog** [microsoft/WSL#8963]
### Version

Microsoft  win 10 19044.2075

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

any software that wants  port range access.

### Repro Steps

a) install an Ubuntu  20.04
b) disable Firewall across all zones on windows host
c) In a power shell with administrative rights:   add  netsh interface portproxy add v4tov4 listenport=30000-50000 listenaddress=0.0.0.0 connectport=30000-50000 connectaddress=<WSL_IP addres>
d)start any service somewhere btw the ports 30000-50000 i.e. ssh on port 32222

You can not access this from outside.
 you get  connection refused

 

### Expected Behavior

To forwarded port according to netsh port range

### Actual Behavior

Services are not accessible in the port range

### Diagnostic Logs

PS C:\WINDOWS\system32> netsh int portproxy show v4tov4

Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
0.0.0.0         30000-50000  172.23.188.236  30000-50000

no diagnostic logs as services are not accessible

**Comment by elsaco** [comment]
@dkalog you might need to include `protocol=TCP` also when adding `portproxy` rule.

**Comment by dkalog** [comment]
> @dkalog you might need to include `protocol=TCP` also when adding `portproxy` rule.

@elsaco This (i.e TCP) is the default selection, as UDP is not supported yet. The lack of UDP support is discussed in a [github issue in the WSL repo](https://github.com/microsoft/WSL/issues/4150)

**Comment by elsaco** [comment]
@dkalog are port ranges supported in Windows? It works when `listenport` is set to single port.

**Comment by tusharsnn** [comment]
According to the documentation, `netsh` portproxy interface's `listenport` (and `connectport`) can either be a service name or port number.

Parameter | Description
-- | --
listenport | Specifies the IPv4 port, by port number or service name, on which to listen.
connectaddress | Specifies the IPv4 address to which to connect. Acceptable values are IP address, computer NetBIOS name, or computer DNS name. If an address isn't specified, the default is the local computer.
connectport | Specifies the IPv4 port, by port number or service name, to which to connect. If connectport is not specified, the default is the value of listenport on the local computer.
listenaddress | Specifies the IPv4 address for which to listen. Acceptable values are IP address, computer NetBIOS name, or computer DNS name. If an address isn't specified, the default is the local computer.
protocol | Specifies the protocol to use.

You can run the command without `connectport` in which case it will use `listenport` as the default. And make sure you don't use those ports on Windows for any services as `listenport=0.0.0.0` (includes localhost) might redirect requests to those services to wsl.

Also refer to this docs for more details on netsh portproxy interface: https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy
