### ISSUE TITLE
Can't run `code` and `kex` after enable `systemd`

### ISSUE THREAD

**Issue by yuan21c** [microsoft/WSL#8968]
### Version

Microsoft Windows [version 10.0.25217.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 22.04 & Kali 2022.3

### Other Software

Visual Studio Code 1.72.0
kex 3.0

### Repro Steps

+ Enable `systemd` following [Systemd support is now available in WSL!](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)
+ Launch vscode in Ubuntu and Kali via command `code .`
+ Run `kex` in Kali to start a kali desktop 

### Expected Behavior

+ vscode would launch 
+ a Kali desktop would display

### Actual Behavior

+ there is an error occurred when i try to launch vscode 
```
/mnt/c/Users/xxx/AppData/Local/Programs/Microsoft VS Code/bin/code: 61: /mnt/c/Users/xxx/AppData/Local/Programs/Microsoft VS Code/Code.exe: Exec format error
```

+ when i try to start kex, nothing happens, just print this :
```
Win-KeX server sessions:

X DISPLAY #     RFB PORT #      RFB UNIX PATH   PROCESS ID #    SERVER
1               5901                            700             Xtigervnc

You can use the Win-KeX client to connect to any of these displays.
```

+ when i disabled `systemd`, everthing performs okay.

**Comment by cerebrate** [comment]
The former, at least, is #8843 (workaround in the comments to that issue). If the problem with kex is that it's not automatically launching the Windows client for the Kali desktop, that's also #8843.

**Comment by yuan21c** [comment]
> The former, at least, is #8843 (workaround in the comments to that issue). If the problem with kex is that it's not automatically launching the Windows client for the Kali desktop, that's also #8843.

thank you.
