### ISSUE TITLE
WSL manual install documentation doesn't include how to install/get dependencies

### ISSUE THREAD

**Issue by riverar** [microsoft/WSL#8969]
The WSL manual installation documentation (https://learn.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions) does not include steps on how to satisfy the dependencies of the distro packages (e.g. Microsoft.VCLibs). This is required, for example, on Windows Server 2022.

> Windows cannot install package CanonicalGroupLimited.Ubuntu22.04LTS_2204.0.10.0_x64__79rhkp1fndgsc because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ...

Surfing the information highway, you may come across this promising page on Microsoft Download Center (https://www.microsoft.com/en-us/download/details.aspx?id=102159) but it only links to a `readme.txt`.

cc: @asklar

**Comment by asklar** [comment]
Thanks for filing. I've alerted the folks that own the download, so we can focus this issue on "the WSL docs should be updated"

**Comment by krokofant** [comment]
To workaround this
```powershell
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile ~/VCLibs14.appx
Add-AppxPackage -Path ~/VCLibs14.appx
```

More download links: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages
