### ISSUE TITLE
Fix Dbus Issues using package diversion for Dbus

### ISSUE THREAD

**Issue by tsal** [Microsoft/WSL#897]
Description: Dbus issues account for a number of current issues.  Many of these can be solved with a change in the Dbus package at installation using the diversion capabilities of apt.

Expexcted results: Packages / software that expect dbus should install without warnings and should execute without issues.

Actual results: Many packages generate warnings at installation about upstart or other steps that need dbus.  In some cases, you can permanently corrupt your Ubuntu userland.

Windows Build: fresh install of anniversary

Suggestion: Using a diversion configuration, dbus-1/session.conf should be updated to use TCP instead of Unix Sockets, as no equivalent exists in lxss as of yet.

https://www.debian.org/doc/debian-policy/ap-pkg-diversions.html

**Comment by fpqc** [comment]
Sockets are coming really soon.  @sunilmut said in #262 (which I happen to be subscribed to:

"I am looking into AF_UNIX\SOCK_DGRAM support in WSL. With the initial code, it looks like I am able to get past the above error in 'weechat'. But, the connect command seems to be timing out. I also tried weechat on my native Ubuntu setup and I am not able to get it to connect as well. Here is what I am trying, please let me know if I am missing something:"

**Comment by sunilmut** [comment]
@tsal - As @fpqc points out, AF_UNIX\SOCK_DGRAM support should come online soon. Is there a good way to test the dbus functionality? If I can get some direct links, I would be happy to try them out on WSL.

**Comment by therealkenc** [comment]
@sunilmut - @tycho over at the top of #376 has a good synopsis. Basically, (as root):
```
mkdir -p /run/dbus
chown messagebus:messagebus /run/dbus
dbus-uuidgen --ensure
dbus-daemon --system --fork        # also --session
```
and then
```
dbus-monitor --system --monitor
```
Main dbus page is [here](https://www.freedesktop.org/wiki/Software/dbus/).

**Comment by therealkenc** [comment]
@sunilmut - If you download the dbus [source](https://dbus.freedesktop.org/releases/dbus/), it has an `--enable-tests`  option for `configure` and a `make check` test suite.  There's some friendly instructions [here](http://www.linuxfromscratch.org/blfs/view/svn/general/dbus.html).

**Comment by tsal** [comment]
Thanks, I didn't look for SOCK_DGRAM, I looked for DBUS so I missed it.  

and yes, as @therealkenc says, you can tests at the build step, which will tell you if your system can use it.

I'm leaving this open as #262 doesn't target the source of the issue (Dbus and sockets); maintainers can overrule me if they want.

**Comment by therealkenc** [comment]
@sunilmut says dbus is inbound over in [376](https://github.com/Microsoft/BashOnWindows/issues/376#issuecomment-242185927). Dbus is actually really close in 14905 except for #706.

**Comment by therealkenc** [comment]
dbus has been working for some time now per #376, circa 15042 or thereabouts
