### ISSUE TITLE
wsl command hanging after a while

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#8973]
### Version

10.0.22623.730

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1 

### Distro Version

any

### Repro Steps

After a while of using wsl without any issues if I try to run any wsl command even wsl --status hangs. BTW in your "Kernel Version" section of the bug report it says to run "sl.exe --status" to get kernel version but for me that just gives:

```
Default Distribution: podman-westie-test-2
Default Version: 2
```
If I run "wsl.exe --version" I get:

```
Default Distribution: podman-westie-test-2
Default Version: 2
PS C:\Windows\System32> wsl.exe --version
WSL version: 0.68.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.730
```

### Expected Behavior

Should run requested wsl command

### Actual Behavior

Command hangs indefinitely

### Diagnostic Logs

[WslLogs-2022-10-08_03-16-20.zip](https://github.com/microsoft/WSL/files/9738996/WslLogs-2022-10-08_03-16-20.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @mwoodpatrick.

This looks like another instance of  #8824 .

Can you please follow [these instructions](https://github.com/microsoft/WSL/issues/8824#issuecomment-1273258292) to share debugging information on this issue ?

**Comment by mwoodpatrick** [comment]
When I hit this issue  "wsl --shutdown" just hangs.  However I can run task scheduler, do a search on wsl and kill the wsl processes

**Comment by mwoodpatrick** [comment]
One nit in the instructions it says to run: "wsl --u root --system" this should have either one dash before the "u" or use "--user"

I will try to do the capture once it hangs again
