### ISSUE TITLE
catastrophic failure after enabling systemd in wsl.conf

### ISSUE THREAD

**Issue by Sadra-jl** [microsoft/WSL#8981]
### Version

Windows version: 10.0.25211.1010

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Repro Steps

installed pengwin from the windows store. enabled [boot] systemd=true in /etc/wsl.conf, shutdown wsl, and rerun wsl, after a few moments, I got the: "catastrophic failure Error code: Wsl/Service/CreateInstance/0x8000ffff "

note: systemd is working fine in arch Linux inside wsl with the same steps above. 

### Expected Behavior

expected to see the distro start successfully and work with systemd.

### Actual Behavior

gets the error "catastrophic failure"
with Error code:" Wsl/Service/CreateInstance/0x8000ffff "

**Comment by bangbang93** [comment]
Same problem for me.
[WslLogs-2022-10-13_23-30-15.zip](https://github.com/microsoft/WSL/files/9778273/WslLogs-2022-10-13_23-30-15.zip)

**Comment by OneBlue** [comment]
Thank you @Sadra-jl. Unfortunately I'm not seeing any WSL log entries in the file you shared.  Did you reproduce the issue while the log collection was running ?

**Comment by josesa-xx** [comment]
I've used Windows 11 with Microsoft Store WSL preview (0.70.4.0) and tried to enable cgroupv2 by doing
```
WIN_WSLCONFIG=$(wslpath $(wslvar USERPROFILE))/.wslconfig
git config -f ${WIN_WSLCONFIG} wsl2.kernelCommandLine "cgroup_no_v1=all"
wsl.exe --shutdown
```
Problem shows when starting up.
[WslLogs-2022-11-02_21-01-42.zip](https://github.com/microsoft/WSL/files/9925578/WslLogs-2022-11-02_21-01-42.zip)

**Comment by OneBlue** [comment]
Thank you @josesa-xx. Now I can see what's happening.

During boot, WSL tries to mount `/sys/fs/cgroup/memory`, but with `cgroup_no_v1=all` , this fail:

```
698	False	Microsoft.Windows.Lxss.Manager	GuestLog	0	11-02-2022 21:01:51.746	7920	"text: 	""[    2.493568] WSL (1) ERROR: Mount:1761: mount((null), /sys/fs/cgroup/memory, cgroup, 0x20000e ""
vmId: 	{4a81dc2a-f949-4fa4-b16c-abad63c1acbd}"	"	"				3384	5		00000000-0000-0000-0000-000000000000			
```

Which is why WSL fails to start

**Comment by YiuTerran** [comment]
Same problem here. Any idea to restore settings?

**Comment by josesa-xx** [comment]
> 

If you have the same problem as me it should be simple to edit the file in %USERPROFILE%\.wslconfig and remove the line about kernelCommandLine

**Comment by ilan-schemoul** [comment]
1.0.1.0 fixed the issue in my case (my exact case was putting kernelCommandLine=cgroup_no_v1=all with systemd enabled, see https://github.com/microsoft/WSL/issues/6662#issuecomment-1332316745)

**Comment by josesa-xx** [comment]
I've tried both 1.0.1.0 and 1.0.3.0 and they both start when I have kernelCommandLine=cgroup_no_v1=all with systemd enabled, however none of cgroup mounts (expected v2) are working, showing the following messages during startup:

```
mount: /sys/fs/cgroup/cpuset: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/cpu: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/cpuacct: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/blkio: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/memory: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/devices: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/freezer: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/net_cls: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/perf_event: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/net_prio: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/hugetlb: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/pids: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/rdma: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error.
mount: /sys/fs/cgroup/misc: wrong fs type, bad option, bad superblock on cgroup, missing codepage or helper program, or other error
```
