### ISSUE TITLE
WSL2 consumes too much memory when running simple python script, and process got killed when memory not configured enough for it

### ISSUE THREAD

**Issue by kaykouo** [microsoft/WSL#8984]
### Version

Microsoft Windows [Version 10.0.22000.1042]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

ubuntu 20.04

### Other Software

VSCODE 1.72.0 with WSL2 remote
python, pandas

### Repro Steps

A python script was simply trying to loaded a 245MB .parquet file to a pandas dataframe, try to add more data, and then save to the parquet file

The Vmmem usage very high, after a while WSL2 killed the python script process.

setup .wslconfig to increase the memory
[wsl2]
guiApplications=false
memory=30GB
processors=6

the python process won't be killed, but the Vmmem will consume all of the 30GB ram.

### Expected Behavior

the memory usage shouldn't be that high, and the python process shouldn't be killed

### Actual Behavior

I have a 245MB .parquet file, 

A python script was simply trying to loaded the file to a pandas dataframe, try to add more data, and then save to the parquet file, checked df with df.info(), this dataframe used ca. 486MB memory.

The Vmmem usage very high, after a while WSL2 killed the python script process.

setup .wslconfig to increase the memory
[wsl2]
guiApplications=false
memory=30GB
processors=6

the python process won't be killed, but the Vmmem will consume all of the 30GB ram.

### Diagnostic Logs

<img width="435" alt="image" src="https://user-images.githubusercontent.com/1451139/194852550-2b69c4ea-8083-4eae-b846-0cc3dc104592.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/1451139/194853050-74b4956f-e6c8-4820-83cd-2661a2b3d9b5.png">

**Comment by benhillis** [comment]
Something in the guest is really using nearly 30GB of memory.
