### ISSUE TITLE
ssh hangs

### ISSUE THREAD

**Issue by kovan** [microsoft/WSL#8985]
### Version

Microsoft Windows [Version 10.0.22610.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 22.04

### Other Software

➜  ~ ssh -V
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022

### Repro Steps

```
➜  ~ ssh -vvv git@github.com
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/k/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/k/.ssh/known_hosts2'
debug2: resolving "github.com" port 22
debug3: resolve_host: lookup github.com:22
debug3: ssh_connect_direct: entering
debug1: Connecting to github.com [140.82.121.3] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
```

Trying to clone via SSH has same behavior:
```
➜  ~ git clone git@github.com:enaqx/awesome-react
Cloning into 'awesome-react'...
```

And stays there indefinitely.

### Expected Behavior

SSH session should start.

### Actual Behavior

The connection attempt stays there indefinitely.

### Diagnostic Logs

netcat connects fine to the SSH port:

```
➜  ~ nc github.com 22
SSH-2.0-babeld-3f0fc83a
^C
```

And (IMPORTANT) on Windows the same commands work well.
And also important, all this is in a just resetted Windows, and a just installed Ubuntu.

**Comment by brainandforce** [comment]
I'm able to reproduce this here with an Arch Linux distribution running kernel `5.15.68.1-microsoft-standard-WSL2`.

**Comment by kovan** [comment]
Seems to be an Ubuntu 22.04.1 issue, because I installed Debian and it no longer happens.
Closing.

**Comment by brainandforce** [comment]
Were you able to find a solution for this issue?

**Comment by edupo** [comment]
I have the same issue. I can't use SSH but also HTTPS isn't working in WSL2. My fix is just using WSL1 at this moment.

**Comment by brainandforce** [comment]
I found a potential fix suggested in #8018 in [this comment](https://github.com/microsoft/WSL/issues/8018#issuecomment-1031373069). I just tried it myself and I'll report back to see if this solves it.

**Comment by kovan** [comment]
Happening again here, this time with a different distribution: ArchLinux.
I tried the potential fix mentioned above, and didn't work for me.

**Comment by brainandforce** [comment]
I think I've found the workaround. If you're getting stuck at a `set_sock_tos:` operation (use `ssh -v` to check) and you're on a wireless connection, it might be due to how router QoS handles SSH packets. I was able to connect to servers by using `ssh -o IPQoS=none <hostname>`. This can be set permanently by adding the line `IPQoS none` in `~/.ssh/config`.

Sources:
https://askubuntu.com/questions/1415021/cannot-ssh-to-server-linux-machine/1418608#1418608
https://serverfault.com/questions/1101269/cant-connect-ssh-via-wireless-interface-but-t-works-using-eth0

**Comment by Blaucel** [comment]
> I think I've found the workaround. If you're getting stuck at a `set_sock_tos:` operation (use `ssh -v` to check) and you're on a wireless connection, it might be due to how router QoS handles SSH packets. I was able to connect to servers by using `ssh -o IPQoS=none <hostname>`. This can be set permanently by adding the line `IPQoS none` in `~/.ssh/config`.
> 
> Sources: https://askubuntu.com/questions/1415021/cannot-ssh-to-server-linux-machine/1418608#1418608 https://serverfault.com/questions/1101269/cant-connect-ssh-via-wireless-interface-but-t-works-using-eth0

I've been stuck for 3 days with this issue. You basically saved my mental health XD
Thanks!!!

**Comment by CoryKniefel** [comment]
> I think I've found the workaround. If you're getting stuck at a `set_sock_tos:` operation (use `ssh -v` to check) and you're on a wireless connection, it might be due to how router QoS handles SSH packets. I was able to connect to servers by using `ssh -o IPQoS=none <hostname>`. This can be set permanently by adding the line `IPQoS none` in `~/.ssh/config`.
> 
> Sources: https://askubuntu.com/questions/1415021/cannot-ssh-to-server-linux-machine/1418608#1418608 https://serverfault.com/questions/1101269/cant-connect-ssh-via-wireless-interface-but-t-works-using-eth0

This saved me. THANK YOU!!!

**Comment by dufferzz** [comment]
> I think I've found the workaround. If you're getting stuck at a `set_sock_tos:` operation (use `ssh -v` to check) and you're on a wireless connection, it might be due to how router QoS handles SSH packets. I was able to connect to servers by using `ssh -o IPQoS=none <hostname>`. This can be set permanently by adding the line `IPQoS none` in `~/.ssh/config`.
> 
> Sources: https://askubuntu.com/questions/1415021/cannot-ssh-to-server-linux-machine/1418608#1418608 https://serverfault.com/questions/1101269/cant-connect-ssh-via-wireless-interface-but-t-works-using-eth0

Thank you! Git will now pull properly again, and Openssh SSH client works! 
Previously OpenSSH client would hang but Putty SSH and telnet localhost 22 worked!

**Comment by alchemizt** [comment]
Im having this problem, I tried adding `IPQoS=none <hostname>` and it changed something, now it says connecting direct to IP, but its still hanging.

**Comment by Roby5791** [comment]
Have you find a solution alchemizt ?

**Comment by Shubham-Rasal** [comment]
> Im having this problem, I tried adding `IPQoS=none <hostname>` and it changed something, now it says connecting direct to IP, but its still hanging.

Having the same issue. I am able to connect to other repos with public ssh access but not the one which I want to.
