### ISSUE TITLE
Explorer won't access folders ending with a dot character

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WSL#8987]
### Version

Microsoft Windows [version 10.0.19044.2075]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Repro Steps

- open a terminal in WSL
- type `mkdir toto...`
- type `explorer.exe .`
- double-click on `toto...`

### Expected Behavior

The `toto...` should be opened in explorer.

### Actual Behavior

An error message is displayed:

![image](https://user-images.githubusercontent.com/199648/194846237-a09aef6f-43d9-4be7-afc2-cc0c8d8c4cd8.png)

**Comment by benhillis** [comment]
Unfortunately this is a limitation of the Windows shell.

**Comment by bplasmeijer** [comment]
> Unfortunately this is a limitation of the Windows shell.

@benhillis did you log explorer PBI?🙏
