### ISSUE TITLE
WSL: vmmem shows 99% CPU - eventually crashes windows 10

### ISSUE THREAD

**Issue by dss010101** [microsoft/WSL#8991]
### Version

Microsoft Windows [Version 10.0.19044.2006]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu-20.04 Default Version: 2  Windows Subsystem for Linux was last updated on 3/26/2022 WSL automatic updates are on.  Kernel version: 5.10.102.1

### Distro Version

Release:        22.04

### Other Software

Version: 1.72.0 (system setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Repro Steps

1. Open python project in visual studio
2. Launch new WSL window (ubuntu)
3. open same project  in the new window

Initially i thought it was me trying work with files on windows mnt on ubuntu.  But after the first one, i cloned the repository locally on ubuntu and have been working with it there.  The issue still happens occasionally.

### Expected Behavior

play nicely

### Actual Behavior

This has happened 3 times now...
Performance starts to degrade significantly at some point.
Looking at task manager i see 99% CPU utilization with **vmmem** taking up about 97 to 98%
I am unable to kill the vmmem process and it requires a reboot and ofcourse when it crashes, i have to reboot.

**Comment by msingh00** [comment]
> /logs

I will try to do this the next time it happens.  but note, the last time i tried opening a cmd shell to poke around and see what's going on, i got this:
![image](https://user-images.githubusercontent.com/855627/194953748-cac9ae53-e48d-4484-a327-74d34e711c3f.png)

**Comment by benhillis** [comment]
Thanks for the screenshot - looks like a directx driver bugcheck. I'll follow up with the GPU folks.

**Comment by benhillis** [comment]
@msingh00 - If you could file a feedback hub item, and share a link, we should be able to see dumps from your machine.

**Comment by msingh00** [comment]
> @msingh00 - If you could file a feedback hub item, and share a link, we should be able to see dumps from your machine.

Done.  i've included this ticket in the description.

**Comment by Jona-Bvunza** [comment]
I am having a similar problem but in windows11,

**Comment by iourit** [comment]
Hello,
Could you configure your system to generate a full kernel dump during a crash and share c:\windows\memory.dmp?
Thanks
Iouri

**Comment by msingh00** [comment]
> Hello, Could you configure your system to generate a full kernel dump during a crash and share c:\windows\memory.dmp? Thanks Iouri

Who are you asking this question?  if me..are you saying the dump i provided was not sufficient?

**Comment by iourit** [comment]
> 
Hi @msingh00,
I cannot find a kernel memory dump from your machine. Only user mode dumps are available. Could you capture a kernel memory dump for the crash and share it?
Thanks
Iouri

**Comment by msingh00** [comment]
i have setup my system to dump the kernel data going forth. i did notice that there was a memory dump created for the last crash, though i dont know if it has the kernel info you seek.  Regardless here it is:  https://drive.google.com/file/d/1DEyVHP5vpJR4lSK6lbSqKUdGHHgxZZ8B/view?usp=sharing

**Comment by iourit** [comment]
> i have setup my system to dump the kernel data going forth. i did notice that there was a memory dump created for the last crash, though i dont know if it has the kernel info you seek. Regardless here it is: https://drive.google.com/file/d/1DEyVHP5vpJR4lSK6lbSqKUdGHHgxZZ8B/view?usp=sharing

@msingh00 Thanks for the dump, but it looks corrupt. You can ZIP the file to reduce the size. Could you resend another one?
If you have Windbg (windows debugger tools) installed, you could try to open the dump to ensure is it not corrupt.

Page 94ea152295 too large to be in the dump file.
**************************************************************************
THIS DUMP FILE IS PARTIALLY CORRUPT.
KdDebuggerDataBlock is not present or unreadable.
**************************************************************************

**Comment by msingh00** [comment]
> > i have setup my system to dump the kernel data going forth. i did notice that there was a memory dump created for the last crash, though i dont know if it has the kernel info you seek. Regardless here it is: https://drive.google.com/file/d/1DEyVHP5vpJR4lSK6lbSqKUdGHHgxZZ8B/view?usp=sharing
> 
> @msingh00 Thanks for the dump, but it looks corrupt. You can ZIP the file to reduce the size. Could you resend another one? If you have Windbg (windows debugger tools) installed, you could try to open the dump to ensure is it not corrupt.
> 
> Page 94ea152295 too large to be in the dump file.
> 
> THIS DUMP FILE IS PARTIALLY CORRUPT. KdDebuggerDataBlock is not present or unreadable.
unfortunately i get the same error trying to open in windbg.  we'll have to wait for the next crash i suppose. 
Is there anything i can do/capture if i see the vmmem at 99%, but hasnt actually crashed yet?

**Comment by iourit** [comment]
@msingh00 You could crash the OS manually. Try to hold "Left shift" + "Right shift" and press "~" twice.
If this doesn't crash the system follow this link:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard

**Comment by iourit** [comment]
@msingh00 You could take and share an ETW trace to investigate performance issues. From a CMD window:
wpr -start CPU -filemode
Repro scenario
wpr -stop log.etl

**Comment by msingh00** [comment]
> @msingh00 You could take and share an ETW trace to investigate performance issues. From a CMD window: wpr -start CPU -filemode Repro scenario wpr -stop log.etl

i get this when i try the first command:
```
C:\Users\mbsin>wpr -start CPU -filemode
        Failed to enable the policy to profile system performance.
        Profile Id: CPU.Verbose.File
        Error code: 0xc5585011
        Failed to enable the policy to profile system performance.

```
while this has not crashed in the last day or so - vmmem is still creeping and eventually take up most of the memory on my laptop.  as i need to do work - can't sit and wait for it to crash - so i have been rebooting to be able to continue to work. As mentioned, i can not kill this process for some reason.

If there is anything i can do further i can do to help resolve this pls let me know.  thx

**Comment by iourit** [comment]
> > @msingh00 You could take and share an ETW trace to investigate performance issues. From a CMD window: wpr -start CPU -filemode Repro scenario wpr -stop log.etl
> 
> i get this when i try the first command:
> 
> ```
> C:\Users\mbsin>wpr -start CPU -filemode
>         Failed to enable the policy to profile system performance.
>         Profile Id: CPU.Verbose.File
>         Error code: 0xc5585011
>         Failed to enable the policy to profile system performance.
> ```
> 
> while this has not crashed in the last day or so - vmmem is still creeping and eventually take up most of the memory on my laptop. as i need to do work - can't sit and wait for it to crash - so i have been rebooting to be able to continue to work. As mentioned, i can not kill this process for some reason.
> 
> If there is anything i can do further i can do to help resolve this pls let me know. thx
@msingh00 
Please try to run WPR from an elevated CMD window (as Administrator). You could also enable additional WPR profiles:
wpr -start CPU -start Pool -start ReferenceSet -start ResidentSet -filemode
The ETL file will be quite big

A kernel memory dump at the point where vmmem takes a lot of memory/CPU would help. I do not know why the captured dumps are corrupted.

The VMMEM process is used to back memory of the WSL2 virtual machine. If you shutdown WLS2 (wsl --shutdown), the process will exit. If you are running multiple containers (WSL2, Edge MDAG, etc.), there will be multiple VMMEM processes.

**Comment by EnzoPujol** [comment]
Any updates on this issue? I'm having the same problem

**Comment by msingh00** [comment]
Im sorry, i havent been using WSL since unfortunately - as i've been under a bit of a time crunch.
