### ISSUE TITLE
wsl --unregister <distroname> should let the user know all their data will be permanently deleted

### ISSUE THREAD

**Issue by clmnin** [microsoft/WSL#8992]
### Version

0.70.0.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Repro Steps

I migrated from a dual boot setup to WSL recently. And when systemd was launched in WSL I signed up for Windows Insider Program.

Today I updated and restarted windows. Once restarted, I came to a screen where I was asked by Ubuntu to run the following commands as it had failed to start. And so I did. Then restarted the PC again.

```
wsl --shutdown
wsl --unregister Ubuntu
```

### Expected Behavior

Let the user know this step will delete all their life's work!

### Actual Behavior

Deleted life's work with no indication that it would

**Comment by Biswa96** [comment]
`wsl --help` already explains that...

```
   --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.
```

**Comment by clmnin** [comment]
@Biswa96 Yes I ran that (--help) to understand it has deleted my data. Did it inform me while the cmd is being run? Do you think deleting a distro is a common practice?

**Comment by Biswa96** [comment]
> Do you think deleting a distro is a common practice?

It's common in *nix world. For example, `rm -rf` or `docker rmi` etc. assume that the user knows what they are doing.

**Comment by Biswa96** [comment]
> Do you think deleting a distro is a common practice?

It's common in *nix world. For example, `rm -rf` or `docker rmi` etc. assume that the user knows what they are doing 😄

**Comment by tusharsnn** [comment]
I agree with @clmnin, the user should be prompted to confirm before executing `--unregister`. As he mentioned, Ubuntu suggested this action.
> Once restarted, I came to a screen where I was asked by Ubuntu to run the following commands as it had failed to start. And so I did

Anyone who had never read the full `--help` wouldn't know what this would actually do.

**Comment by clmnin** [comment]
I'm new to wsl.  `rm -rf` is so well documented everyone knows about it. Also you need to be `superuser` to do that. I wasn't asked to enter a password. How would I know I would loose data if I didn't know the operation was a high privileged one?

I've lost my data. But this is something the wsl cmd can do to prevent future users from loosing their data.

I would say @Biswa96 is a troll and just hurting a user who is already hurt. Please refrain from making further comments

**Comment by OneBlue** [comment]
Agreed with @Biswa96 here: Users who run --unregister are expected to know what --unregister does. Changing the behavior to prompt for confirmation would break a lot of automation so it wouldn't be an option anyway.

**Comment by TW4177** [comment]
> > Do you think deleting a distro is a common practice?
> 
> It's common in *nix world. For example, `rm -rf` or `docker rmi` etc. assume that the user knows what they are doing 😄

Pro tip: @Biswa96's flippant, supercilious attitude does not win points with users whose data gets unexpectedly removed.

**Comment by jgarzagu** [comment]
I've also lost all my data, and with it my Ph.D. dissertation that I was working on. I'm glad I was able to recover it, however that was a close call.  `wsl --unregister DISTRO_NAME` is very destructive and the command should at least warn users or let users know that the whole distro will be deleted. 

- First, the name `--unregister` is very confusing, the correct flag should be `--delete` or remove. 

- Second, for people complaining about "it doesn't work with automation" a second flag should be added just for automation (e.g. --force) to delete the distro without asking.

**Comment by jacobus** [comment]
@jgarzagu How did you recover your data?

**Comment by jgarzagu** [comment]
@jacobus I couldn't recover my data. It was permanently lost. I was only able to recover part of the data that I had previously backed up.

**Comment by jacobus** [comment]
Thanks for replying @jgarzagu So sorry to hear you could not get your data back.

**Comment by aliuq** [comment]
I would like to ask, is there any way to restore the data? Where is the original data location?

**Comment by reitowo** [comment]
This should be fixed immediately
