### ISSUE TITLE
Windows can't install WSL ¿-?     error: 0x8007019e 

### ISSUE THREAD

**Issue by Guidoow** [microsoft/WSL#8994]
### Version

Microsoft Windows [Versión 10.0.19044.2006]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

Opened WSL (both console and clicking wsl.exe ):  Screen does nothing.

### Expected Behavior

WSL Opening and installing correctly.
Windows installing the characteristic correctly.

### Actual Behavior

- cmd.exe: 

> "wsl.exe --install -d Debian"   
>         Installed correctly, wanted to restart

- from Debian application (microsoft store): 

>WslRegisterDistribution failed with error: 0x8007019e
>The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
                                                                            

In the same cases, how is required ( in first case for the cmd, and in the second case, after activate the WSL in -control panel> programs > activate characteristics etc-) right after i restart my pc in the load screen, windows throws something like " **Windows can't load the characteristics/actualizations"**  _(in spanish)_

idk what is happening.

Same error happens when i tried to install **-Virtual machine platform-** and **-Windows hypervisor platform-**

**Comment by benhillis** [comment]
I would suggest filing a feedback hub item about not being able to enable the optional component. That functionality is not owned by the WSL team and it looks like something may off.
