### ISSUE TITLE
Backporting recent WSL builds to Windows 10?

### ISSUE THREAD

**Issue by mpowrie** [microsoft/WSL#8999]
Can the newer WSL builds be ported to work with Windows 10?

For those of us stuck on Windows 10 (e.g. company upgrade policies, lack of hardware support etc), it would be great to still get recent WSL improvements such as systemd support.

**Comment by benhillis** [comment]
This is tracked elsewhere.

**Comment by Zopolis4** [comment]
Where is it tracked?

**Comment by Biswa96** [comment]
WSL from Windows Store can run in Windows 10 now. See the blog post https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
