### ISSUE TITLE
WSL2 adb push large file cause BSOD

### ISSUE THREAD

**Issue by harlenli2022** [microsoft/WSL#9000]
### Version

Microsoft Windows [Version 10.0.19044.2006]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.57.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

usbipd version in Windows: 2.4.0
usbip version in WSL2: usbip (usbip-utils 2.0)
VirtualBox in Windows: 6.1.36

### Repro Steps

1.connect device to windows USB port
2.switch device to adb mode
3.usbipd wsl list can show the adb device in windows
4.usbipd wsl attach -b x-x to attach adb device to WSL2
5.in WSL lsusb can show newly attached  adb device
6.try to adb push files to device
- one single large file (e.g. 1G), windows BSOD with code SYSTEM_PTE_MISUSE
- multiple small files (e.g. 20M), when pushing the 16th file, windows BSOD with code SYSTEM_PTE_MISUSE

### Expected Behavior

No BSOD happened when using adb push in WSL

### Actual Behavior

windows BSOD with code SYSTEM_PTE_MISUSE

**Comment by pmartincic** [comment]
Assuming you have Watson enabled dumps will go there and in the hands of the kernel team for them to investigate.
