### ISSUE TITLE
WSL2 not using host's VPN connection

### ISSUE THREAD

**Issue by Rechdan** [microsoft/WSL#9004]
### Version

Microsoft Windows [versão 10.0.22621.674]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Debian 11

### Repro Steps

1. Connect to the VPN in Windows
2. Try to access it in Linux

### Expected Behavior

1. Connect to the VPN in Windows
2. Succeed when using accessing it in Linux

### Actual Behavior

1. Connect to the VPN in Windows
2. Fails when trying to use it in Linux

**Comment by weflower** [comment]
There is a suggested workaround here:
https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#wsl-has-no-network-connectivity-once-connected-to-a-vpn

but that isn't a great solution, since it requires you to do it and revert every time you connect the VPN.

**Comment by Codym48** [comment]
@janovek wrote some blog posts about better solutions: https://janovesk.com/wsl/2022/01/21/wsl2-and-vpn-routing.html

**Comment by weflower** [comment]
Thanks @Codym48!. Since I was using WSL2 to run Docker anyway, I ended up using a Docker package called wsl-vpnkit and having it start automatically with the distro.

It might do something similar to the post but I was lazy and didn't look into it much after I got it working :)
