### ISSUE TITLE
uid= and gid= options doubled on drvfs automounts when wsl.conf options used

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#9005]
### Version

10.0.22000.978

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1-20221008-2-microsoft-custom-WSL2+

### Distro Version

Debian sid

### Repro Steps

1. Configure `/etc/wsl.conf` with the following options:

```
[automount]
enabled = true
options = "uid=996,gid=996"
```

2. Restart WSL.
3. Run `mount`
4. Observe that the options listed for the `/mnt/c` filesystem include:

`uid=1000;gid=1000;uid=996;gid=996;`

### Expected Behavior

Only one set of the (mutually exclusive) uid= and gid= options should appear.

### Actual Behavior

This may not be a bug in the technical sense, inasmuch as the automounted filesystem's files are assigned the correct (i.e., specified in `/etc/wsl.conf`) uid and gid.

On the other hand, it is a mite confusing (and perhaps also an issue for scripts examining `/etc/mtab`/`/proc/self/mounts`) to see the uid and gid options specified twice in the mount options when looking at the list of mounted filesystems.

(Not a terribly big deal, IMO, in the absence of any documentable _problem_ caused up to this point, other than a moment's confusion, but it seemed like it should be on the record.)

**Comment by benhillis** [comment]
Yah, the last one specified will win. Could probably avoid passing that to the kernel so the duplicates aren't shown in the mount info files though...

**Comment by cerebrate** [comment]
It only just occurred to me to check if the same thing would happen with other mutually exclusive options, such as `options="ro"`. Fortunately not, as that would have been _really_ confusing. 😀

**Comment by benhillis** [comment]
No plans to change this behavior.

**Comment by guidoca** [comment]
This seems to be an issue when working with shared network drives mounted on WSL2. The uid/gid specified in wsl.conf doesnt overwrite the default uid/gid in the system.  In the mounted network drive, only the gid from wsl.conf is used, while it still associates the uid to the default one from wsl (causing permission errors). A workaround is to manually map the uid to the desired on in the network drive fstab, but this may be a security issue.
