### ISSUE TITLE
Enabling systemd loses access to Linux filesystems in WSL from Explorer

### ISSUE THREAD

**Issue by RotoDhoulmagus** [microsoft/WSL#9013]
### Version

10.0.22621.674

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1-microsoft-standard-WSL2

### Distro Version

openSUSE-Tumbleweed 20221008

### Repro Steps

1. Enable systemd as in https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

2. Mount the disk as in https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/
3. The filesystem is accessible in WSL, but not in Windows Explorer. 

### Expected Behavior

The filesystem is accessible from the Explorer. 
It worked all along until systemd is enabled, and it becomes accessible from the Explorer again once I disable systemd. 

### Actual Behavior

The filesystem is not accessible from the Explorer.

**Comment by exitdown** [comment]
interesting. i wonder if this is related to my bug https://github.com/microsoft/WSL/issues/9029 

I can still access the filesystems from windows. so perhaps i could try to remove access to them to see if it solves my issue (albiet without access to the filesystems)

**Comment by exitdown** [comment]
ok so i am unable to unmount my dir, it used to be wsl1, i converted to wsl2 ages ago. 

are you able to perform the below commands on your system so we can compare?


PS C:\Users\vinny\Desktop> reg query HKLM\SYSTEM\CurrentControlSet\Control\NetworkProvider /s

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\HwOrder
    ProviderOrder    REG_SZ    RDPNP,P9NP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    RDPNP,P9NP,LanmanWorkstation,webclient

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\ProviderOrder
    LanmanWorkstation    REG_DWORD    0x7d0
    P9NP    REG_DWORD    0x1f4
    RDPNP    REG_DWORD    0x3e8
    webclient    REG_DWORD    0xbb8

PS C:\Users\vinny\Desktop> wmic diskdrive list brief
Caption                   DeviceID            Model                     Partitions  Size
KBG40ZNS256G BG4A KIOXIA  \\.\PHYSICALDRIVE0  KBG40ZNS256G BG4A KIOXIA  3           256052966400
