### ISSUE TITLE
WSL App (Windows Store) returns "No such interface supported / Error code: Wsl/0x80004002"

### ISSUE THREAD

**Issue by jgregmac** [microsoft/WSL#9014]
I have been using WSL steadily on this system since WSL1 under Windows 10.  I have transitioned successfully to WSL2 on Windows 10, and now to WSL2 on Windows 11.  However, I have had no luck with the newer app store version of WSL.  It consistently returns these "No such interface supported" errors as soon as it is installed.

I have tried removing removing/rebooting/restarting.  I have removed the app, disabled native WSL, restarted, and re-installed the app.  I have removed the app, purged all of my WSL distribution instances, removed the distributions from my installed apps list, then reinstalled the app.  The results are always the same.

## Windows version / build number

Microsoft Windows [Version 10.0.22000.1098]

## Steps required to reproduce

As soon as I install the Windows Subsystem for Linux app from the Windows store, wsl.exe no longer works.  Any attempt to launch it with any parameters returns the same error.

## Terminal Output

```powershell
$ wsl -l
No such interface supported
Error code: Wsl/0x80004002
```

## Expected Behavior

I expected WSL to continue functioning as it did before installing the app store version.

## Collect WSL logs

Attached below:  
[WslLogs-2022-10-13_21-49-41.zip](https://github.com/microsoft/WSL/files/9781883/WslLogs-2022-10-13_21-49-41.zip)

**Comment by jgregmac** [comment]
Figuring it was about time anyway, I did "Reset PC" (reinstalled Windows, keeping personal files but removing all apps).  This problem persists even after re-installing Windows!  

I suppose there still could be something in my home directory (profiles) that is interfering with WSL, but it seems increasingly unlikely.  Perhaps this is a hardware issue?  FWIW I am using a Lenovo ThinkPad X1E, 1st Gen (Circa 2019).

**Comment by benhillis** [comment]
Thanks for the logs, it looks like when the WSL msix package was installed, the interface for talking to wslservice.exe was not added. Could you try removing the WSL app and re-installing it from the store?

**Comment by jgregmac** [comment]
> Thanks for the logs, it looks like when the WSL msix package was installed, the interface for talking to wslservice.exe was not added. Could you try removing the WSL app and re-installing it from the store?

I did try that with no effect. 

Yesterday I did take the extreme step of wiping the drive and doing a fresh install of Win 11, keeping no files. After that, the WSL app installed and Initialized without error. Thus it is likely that something in my user profile was interfering with the WSL app. Perhaps an environment variable/user registry setting?

**Comment by benhillis** [comment]
Likely something COM-related since that's the interface that wsl.exe is trying to use. If somebody gets into this state I'd like to inspect some reg keys to see if the interface is actually registered.

**Comment by tjnsn** [comment]
i got the exact same issue.
had wsl installed, then installed kb5020030 (win10 19044.2311 (21H2)), started wsl and got notification to run wsl --update.
the update ran fine, then when i start wsl i get

No such interface supported
Error code: Wsl/0x80004002

wsl.exe command fails all the time with above error even "wsl /?" or "wsl --help" result in above error
Ideas how to fix it?

**Comment by jpwijbenga** [comment]
Same problem after upgrading 

No such interface supported
Error code: Wsl/0x80004002

Which command to run to get diagnostics, like these registry keys/values?

**Comment by killerfurbel** [comment]
Having the same problem, after Upgrading from Win11 21H2 to 22H2 via inplace upgrade. Same result with `wsl.exe --upgrade` or starting the install directly from the microsoft store.

**Comment by Biswa96** [comment]
"Could you try removing the WSL app and re-installing it from the store?"

**Comment by killerfurbel** [comment]
I just found out that I get the same error for other Store Downloads. Just tried to install the update of "Windows Alarm & Clock", also Code `0x80004002`... probably has nothing to to with WSL itself, but is rather a Store issue?

**Comment by Biswa96** [comment]
WSL package can be installed from [release page](https://github.com/microsoft/WSL/releases) with `Add-AppxPackage` command in Powershell.

**Comment by tjnsn** [comment]
WSL from appstore appears to be installed so i dont think thats the issue, also i have completely removed wsl by unregistering all dists, removing all wsl stuff from add/remove programs included Settings/apps and the optional windows components and then reinstalled it again via wsl --instal and get exactly the same issue

also side note, because this issue was closed i created a new one related to this https://github.com/microsoft/WSL/issues/9202

**Comment by killerfurbel** [comment]
> WSL package can be installed from [release page](https://github.com/microsoft/WSL/releases) with `Add-AppxPackage` command in Powershell.

worked for me, thanks!

**Comment by dpywoo** [comment]
I had this same problem the other day too.  It was a fresh install of Windows 10 Pro with 22H2, so there was almost nothing on it.

First, I installed WSL from the Windows Store.  After that, I installed Ubuntu 22.04.1 LTS and got the same error message when trying to start Ubuntu:

```
No such interface supported
Error code: Wsl/0x80004002
```

Then I tried different iterations of installing/re-installing Ubuntu 20.04.5 and 22.04.1 from the Windows Store and through the terminal, downloading and installing/re-installing 1.0.3 and 1.0.0 from the aforementioned release page, downloading and installing/reinstalling WSL from the Windows Store, and no progress.  I even tried enabling the "Windows Subsystem for Linux" option in the "Turn Windows features on or off" settings page and still nothing.  I finally got Ubuntu 22.04.1 LTS spun up when I switched to WSL1:

`wsl --set-default-version 1`

As soon as I switched to WSL1, Ubuntu fired up immediately without any additional tinkering.

So it's possible the issue may be with WSL2.  This is probably not the ideal fix if you're hard set on using WSL2, but if you want to just get a system up and running, switching WSL1 may work for you until a solution for WSL2 is found.

**Comment by Biswa96** [comment]
The message `Error code: Wsl/0x80004002` comes from WSL Store version. So, installing/uninstalling a distribution would not work. Only installing/uninstalling the WSL Store version is the preferred way. Whereas WSL1 uses system WSL which is already registered.

I can think of some workarounds like registering WSL Store version after extracting in different directory or registering the COM interface manually. But those will be a concern from security standpoint.

**Comment by eirikwang** [comment]
I get this exact issue after upgrading to the WSL Store version. 
U had to remove the WSL store version, and reinstall the core manually using: https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by lpboss** [comment]
I met the same issue too....

**Comment by shimaode** [comment]
I run into the same issue right after a reboot, and I guess maybe some upgrade of the Windows mass up the WSL.
I really don't want to reinstall the core because I have to install tons of things with a fresh WSL like docker, python, etc.
So I searched "wsl.exe" with my "Everything" and found there's a "wsl.exe" under `C:\Windows\WinSxS\amd64_microsoft-windows-lxss-wsl_31bf3856ad364e35_10.0.19041.2311_none_f7a4fa53841d8f4e`
I started that wsl.exe and it worked. All the docker images are there.
But starting my debian from the StartMenu still gives me 0x80004002.

So if you are a lazy guy who don't want a reinstall of WSL like me, try to search and execute every "wsl.exe" under C:\Windows\WinSxS\blablabla..

I hope that helps.

**Comment by thomaspingel** [comment]
I had good luck fixing this by doing a wsl install this way:
~~~
wsl --install --inbox
~~~

**Comment by tjnsn** [comment]
> I had good luck fixing this by doing a wsl install this way:
> 
> ```
> wsl --install --inbox
> ```

Are you sure this installs the latest version?
Can you check what "wsl --version" shows? (if anything)

**Comment by shimaode** [comment]
> I had good luck fixing this by doing a wsl install this way:
> 
> ```
> wsl --install --inbox
> ```

Still gives me Wsl/0x80004002

**Comment by thomaspingel** [comment]
> > I had good luck fixing this by doing a wsl install this way:
> > ```
> > wsl --install --inbox
> > ```
> 
> Are you sure this installs the latest version? Can you check what "wsl --version" shows? (if anything)

wsl --status gives 

Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 3/25/2023
WSL automatic updates are on.

Kernel version: 5.10.102.1

**Comment by Confishua** [comment]
Please, I need help too. Mine is still showing error

**Comment by kenkit** [comment]
Open powershell as admin run this 
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

**Comment by MichaelBagnasco** [comment]
Ensure that CPU virtualization is enabled in the BIOS. It's dependent on your CPU and motherboard.

**Comment by Confishua** [comment]
I can't enable it. The BIOS is requesting for password. And I don't know it.

**Comment by Michiel-s** [comment]
See this comment here: https://github.com/microsoft/WSL/issues/9202#issuecomment-1447500031

This did the trick for me.

`wsl --update` will corrupt your wsl command.
Remove the Appxpackage that updating installed will get your wsl back.
Run Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" } in powershell to get the package fullname, and remove it using Remove-AppxPackage -Package "<packag-full-name>"

**Comment by vito0719** [comment]
> Likely something COM-related since that's the interface that wsl.exe is trying to use. If somebody gets into this state I'd like to inspect some reg keys to see if the interface is actually registered.

I've been having this issue for a while now... What reg keys do you need to inspect?

**Comment by no-stack-dub-sack** [comment]
> Open powershell as admin run this
> 
> ```
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> ```

This worked for me. After running this I got a new error:

```
WslRegisterDistribution failed with error: 0x80370114

Error: 0x80370114 The operation could not be started because a required feature is not installed.
```
Which I was able to resolve by enabling the "Virtual Machine Platform" feature in Control Panel > Programs > Turn Windows features on or off.

**Comment by axelmalahieude** [comment]
I resolved this by toggling the WSL off and then back on in Control Panel -> Programs -> Turn Windows Features on or off.

**Comment by EJCPieters** [comment]
> 

This worked for me!

**Comment by rbenvenuto** [comment]
```
I resolved this by toggling the WSL off and then back on in Control Panel -> Programs -> Turn Windows Features on or off.
```
This is what worked for me, thanks

**Comment by vito0719** [comment]
i had to do a fresh install of win11 and the ms store version wsl still didn't work...
but i was able to use the one in turn windows features on or off

**Comment by lahbouch** [comment]
i updated wsl.
and i turn on linux subsystem
and hyper-v and virtual machine platform features.
and it worked.

**Comment by iMuhammadMustafa** [comment]
> Open powershell as admin run this
> 
> ```
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> ```

This worked for me

**Comment by SoftEng-Islam** [comment]
enable Delivery Optimization service

**Comment by Ivar-7** [comment]
Go to "Turn windows features on or off"
Enable "Windows subsystem for linux"
Worked like a charm for me
