### ISSUE TITLE
CPU Performance Regression on Windows Host When WSL2 is Running

### ISSUE THREAD

**Issue by Locietta** [microsoft/WSL#9019]
### Version

Microsoft Windows [Version 10.0.22623.746]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

* Start a WSL2 instance
* Try to compile a software on windows (in my case, compile my C++ codebase with xmake/cmake)

### Expected Behavior

Whether WSL2 is running shouldn't affect the performance of host windows machine. 

### Actual Behavior

When I compile my code, CPU frequency will drop from ~2.7GHz to ~2GHz if WSL2 is running, and the CPU usage is limited to 80%.

And if I manually shut down WSL2 instances with `wsl --shutdown`, the performance goes back to normal.

Here is the CPU profile when building the same project with WSL2 running or not.
![image](https://user-images.githubusercontent.com/53137814/195978789-25a62810-b63c-487c-8188-c87b27725af4.png)

### Diagnostic Logs

I spend some time bisecting the WSL releases, the first version introducing this issue is 0.65.1. There's no such performance regression for versions <= 0.64.

I don't know if it's relevant, but my laptop uses an intel i5-9300H CPU.

**Comment by gresco** [comment]
I am seeing WSL2 eating my CPU cycles as well. This is to the point that after a day or two I have to restart my computer per the `vmmemWSL` process is protected and I can't kill it.
```
> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1219
```

**Comment by Karlheinzniebuhr** [comment]
Same here on win10, ML processes that never used more than 40% of my CPU now use 100% and take 4x longer to complete.
