### ISSUE TITLE
ubuntu preview no get button

### ISSUE THREAD

**Issue by sucicf1** [microsoft/WSL#9024]
### Version

win 11 22h2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

ubuntu preview

### Repro Steps

Hello,

I am trying to download from link https://apps.microsoft.com/store/detail/ubuntu-on-windows-community-preview/9P9Q5ZH1HRR0?hl=en-us but after opening in ms store no get button. Other apps in store including the ubuntu app (not preview) are working correctly. I tried things like reseting store, sign out login restarting services. Is it possible that the app is region locked?

### Expected Behavior

Displays the get button

### Actual Behavior

No get button to download and install

**Comment by benhillis** [comment]
We do not own the Ubuntu application - please reach out to Canonical.

**Comment by sucicf1** [comment]
I found that if you search inside ms store app for ubuntu preview you get an other page that works. So i suppose the upper link is outdated and I consider this solved.
