### ISSUE TITLE
enabling systemd makes evolution think it is offline

### ISSUE THREAD

**Issue by roblatham00** [microsoft/WSL#9027]
### Version

WSL version: 0.70.0.0 Kernel version: 5.15.68.1 WSLg version: 1.0.45 MSRDC version: 1.2.3575 Direct3D version: 1.606.4 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22623.746

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.68.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Mon Sep 19 19:14:52 UTC 2022

### Distro Version

ubuntu 22.04

### Other Software

% evolution --version
evolution 3.44.4-0ubuntu1

### Repro Steps

The `evolution` mail client for linux (https://wiki.gnome.org/Apps/Evolution) works pretty well under wsl2.  However, if I enable systemd (by adding '[boot] systemd=true' to /etc/wsl.conf) evolution thinks it is offline and I am unable to send or receive mail. 

I see the message ` evolution-shell-Message: 08:31:48.076: Network disconnected.  Forced offline.` in the console. 

### Expected Behavior

here's what evolution looks like upon startup with systemd disabled:

![image](https://user-images.githubusercontent.com/2278417/196193272-fc2ee8f5-981a-4161-bbee-eecdd4628951.png)

### Actual Behavior

When I re-enable systemd, evolution starts up like this -- note the 'offline' icon in the lower left hand corner

![image](https://user-images.githubusercontent.com/2278417/196192548-7611d4ec-45b9-4258-91b3-8fbf7258054a.png)

**Comment by roblatham00** [comment]
[WslLogs-2022-10-24_08-33-54.zip](https://github.com/microsoft/WSL/files/9852060/WslLogs-2022-10-24_08-33-54.zip)

**Comment by OneBlue** [comment]
Thank you @roblatham00. Unfortunately I'm not seeing the WSL startup in the logs.

Can you try to first run `wsl.exe --shutdown` to make sure that wsl is not running, and then run the log collection while you reproduce the issue ?

**Comment by roblatham00** [comment]
ok, deleted the bad logs and am trying agian!
[WslLogs-2022-10-27_16-47-19.zip](https://github.com/microsoft/WSL/files/9883319/WslLogs-2022-10-27_16-47-19.zip)

**Comment by OneBlue** [comment]
Thank you @roblatham00.

I'm not seeing anything that jumps out in the logs. Out of curiosity, when the email client is in that state, do other wsl commands have access to the internet ? What does `curl https://microsoft.com` output for instance ?

**Comment by roblatham00** [comment]
Other network commands seem to be able to access the internet, yes: 
* `curl https://microsoft.com` output nothing but did not encounter an error
*  `apt get upgrade` downloaded and installed Ubuntu updates.
* `wget https://github.com/microsoft/WSL/issues/9027` grabbed this web page

**Comment by OneBlue** [comment]
Thank you @roblatham00. In that case I'm going to guess that the issue is probably with `evolution`. 
Maybe it tries to connect to a specific systemd unit and if it can't, assumes that no network connection is available ? 

Closing this since it doesn't appear to be a WSL issue. I recommend following up with an [evolution issue](https://gitlab.gnome.org/GNOME/evolution/-/issues)
