### ISSUE TITLE
i18n bug in usage help

### ISSUE THREAD

**Issue by rise0chen** [microsoft/WSL#9030]
### Version

Microsoft Windows [版本 10.0.22621.674]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

![image](https://user-images.githubusercontent.com/12853908/196314631-a8930b13-d662-443c-a5b6-9d57cbdac42a.png)

### Expected Behavior

display English

### Actual Behavior

无效的命令行参数： --注销

**Comment by Yurunsoft** [comment]
Same problem
