### ISSUE TITLE
The nvidia cannot be used by wsl2 after win11 updating the nvidia driver

### ISSUE THREAD

**Issue by heijieke** [microsoft/WSL#9035]
_**After I update my nvidia driver to 522.25,when I run nvidia-smi in wsl2 follows:**_

> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
> 
> Failed to properly shut down NVML: Driver Not Loaded
_**And run glxinfo -B follows:**_

> name of display: :0
> display: :0  screen: 0
> direct rendering: Yes
> Extended renderer info (GLX_MESA_query_renderer):
>     Vendor: Mesa/X.org (0xffffffff)
>     Device: llvmpipe (LLVM 13.0.1, 256 bits) (0xffffffff)
>     Version: 22.0.5
>     Accelerated: no
>     Video memory: 7871MB
>     Unified memory: no
>     Preferred profile: core (0x1)
>     Max core profile version: 4.5
>     Max compat profile version: 4.5
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 3.2
> OpenGL vendor string: Mesa/X.org
> OpenGL renderer string: llvmpipe (LLVM 13.0.1, 256 bits)
> OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.0.5
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> 
> OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.0.5
> OpenGL shading language version string: 4.50
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> 
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.5
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
_**Any how,I can't use nvidia in my wsl2 and hope someon could help me,appreciate!**_

**Comment by heijieke** [comment]
And the same problem with nvidia driver 5.16

**Comment by heijieke** [comment]
the problem is because I change my preferred graphics processor from intel to nvidia,but i still don't know how to resolve it

**Comment by Ziy1-Tan** [comment]
https://github.com/microsoft/WSL/issues/9099#issuecomment-1312632913 Try this.
