### ISSUE TITLE
Support of mainline and stable Linux kernel releases in WSL Dev/Beta channels 

### ISSUE THREAD

**Issue by ohault** [microsoft/WSL#9037]
**Is your feature request related to a problem? Please describe.**
Current mainline and stable Linux kernel releases are not available for WSL dev/beta channels

**Describe the solution you'd like**
[WSL users in the Windows Insiders Program](https://learn.microsoft.com/en-us/windows/wsl/) for Dev and Beta should be able to use mainline and stable Linux kernel versions.

e.g. as of today, it will provide access to following Linux kernel versions:
- for Dev channel ->  mainline: 6.1-rc1
- for Beta channel -> stable: 6.0.2 or stable: 5.19.16

Corresponding Linux kernel source code will be also available in preview at https://github.com/microsoft/WSL2-Linux-Kernel

**Comment by benhillis** [comment]
Thanks for the suggestion, but we currently have no plans to support anything other than the most recent long term support kernel releases.

**Comment by ohault** [comment]
Hi @benhillis 
Can you please re-open this ticket, because if I have created it, it is indeed because this is a current major issue with WSL, and not only WSl(Mariner,...)
