### ISSUE TITLE
QT based application are not launching

### ISSUE THREAD

**Issue by Night-Hawk2000** [microsoft/WSL#9038]
### Version

Microsoft Windows [Version 10.0.22000.1098]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Install any Qt application (I tested with freecad) and try to launch it. 

### Expected Behavior

Wslg should give GUI output. 

### Actual Behavior

App launch aborted with the following logs

Log: Init: App::FreeCADInit.py done
Log: Init: Creating Gui::Application and QApplication
Log: could not connect to display :0
Log: Could not load the Qt platform plugin "xcb" in "" even though it was found.
Log: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

### Diagnostic Logs

`export QT_QPA_PLATFORM=wayland` will make the application launch however it will crash as soon user tries to open a file.

**Comment by Night-Hawk2000** [comment]
[WslLogs-2022-10-20_16-25-04.zip](https://github.com/microsoft/WSL/files/9829122/WslLogs-2022-10-20_16-25-04.zip)

**Comment by OneBlue** [comment]
Thank you @Night-Hawk2000.

Looking at the logs, it looks like systemd is enabled on this distro. Can you try disabling it, run wsl.exe --shutdown and try to start the QT app again ?

**Comment by Night-Hawk2000** [comment]
Thanks for the advice.
It seems systemd was causing the problem. After disabling that the application runs without an issue. This also fixes the issue of extremely slow IO and system freeze which I was experiencing for the past few days.
