### ISSUE TITLE
Failed to start "Alt linux" dist in WSL

### ISSUE THREAD

**Issue by DesKonstantin** [microsoft/WSL#9041]
### Version

Microsoft Windows [Version 10.0.19045.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

alt-workstation-10.0

### Repro Steps

1. Download distr alt-workstation-10.0-rpi4-aarch64.tar from https://download.basealt.ru/pub/distributions/ALTLinux/p10/images/workstation/aarch64/alt-workstation-10.0-rpi4-aarch64.tar.xz
2.  Try to import (instruction from https://learn.microsoft.com/ru-ru/windows/wsl/use-custom-distro)
_wsl --import alt C:\dist\ C:\dist\alt-workstation-10.0-rpi4-aarch64.tar\alt-workstation-10.0-rpi4-aarch64.tar_
3. Try to start 
_wsl -d alt_
_wsl -l -v_
  NAME            STATE           VERSION
  alt             Running         2
4. nothing happened. Go to alt tab and try to start

[процесс завершил работу с кодом 1 (0x00000001)]

### Expected Behavior

alt linux started

### Actual Behavior

[процесс завершил работу с кодом 1 (0x00000001)]

### Diagnostic Logs

[Uploading WslLogs-2022-10-19_16-30-14.zip…]()

**Comment by OneBlue** [comment]
Thanks for reporting this @DesKonstantin. The logs you shared just point back to this issue. Can you share another log capture ?

**Comment by NotTheDr01ds** [comment]
@elsaco Agreed, I'm assuming that the `rpi4` in the name indicates that is the image for the Raspberry Pi 4.

@DesKonstantin If possible, I would recommend using Microsoft's [doc](https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro#obtaining-a-tar-file-for-centos-example) for obtaining a tarball from a Docker container.  You should be able to pull the P10 Alt image (once Docker is installed in another distribution) with:

```
docker run -t alt:p10 bash ls /
```

**Comment by DesKonstantin** [comment]
Yes, it is my mistake. Issue is invalid
