### ISSUE TITLE
unable to launch gui apps outside of wsl

### ISSUE THREAD

**Issue by abdessamad-abid** [microsoft/WSL#9042]
Version : 10.0.19044.2130
wsl2 Kernel Version : 5.10.16
distro : Ubuntu 22.04

I'm working on a desktop application that uses GPU. so i used wsl2. 
i set up the display using an xserver by adding this to the profile file : 
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0 
export PULSE_SERVER=tcp:$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}') 
export LIBGL_ALWAYS_INDIRECT=1

I can successfully launch the app from wsl. when i use this command in cmd "wsl.exe name_of_the_app"  wsl has no longer access to display. 
can someone tell me what i'm doing wrong please ?

**Comment by OneBlue** [comment]
The profile isn't always loaded by your shell (see https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Startup-Files). Based on what you said that's the issue.

If you need GUI apps the recommendation is to use [wslg][https://github.com/microsoft/wslg), but to do that you'll need to upgrade your Windows build.
