### ISSUE TITLE
SIO_AF_UNIX_GETPEERPID after WSADuplicateSocket to a different process

### ISSUE THREAD

**Issue by elmarco** [microsoft/WSL#9045]
### Version

Microsoft Windows [Version 10.0.22000.978]
### Repro Steps

- Create a connected AF_UNIX socket pair in the source process
- Duplicate one end to a destination process, then close it in the source process
- Call SIO_AF_UNIX_GETPEERPID on the other end of the pair.

### Expected Behavior

Get the PID of the destination process.

### Actual Behavior

Get the PID of the source process.

**Comment by Biswa96** [comment]
A minimal sample code would help to reproduce the issue.

**Comment by OneBlue** [comment]
Thank you for reporting this @elmarco. Can you share a sample program demonstrating the issue ?
