### ISSUE TITLE
Remove `wsl --unregister DISTRO_NAME` from the recommended commands to  be run when "something goes wrong"

### ISSUE THREAD

**Issue by clmnin** [microsoft/WSL#9049]
### Version

WSL version: 0.70.4.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.68.1

### Distro Version

Ubuntu 22.04.1 LTS

### Repro Steps

1. Perform a windows update. 
2. On restart see an open window asking you to `--unregister` the distro

----

I had the below two windows updates performed
* Cumulative Update for Windows 11 Insider Preview (10.0.22623.870) (KB5018499)
* Update Stack Package - (Version 1022.1018.1012.0)

And on restart I see a window saying "Something went wrong". And was asked to run the following commands
```
Something went wrong.
Please restart WSL with the following command and try again:
wsl --shutdown
wsl --unregister DISTRO_NAME
```

But `wsl --unregister DISTRO_NAME` is a dangerous command and should not be run by the uninitiated.
```
--unregister <Distro>
    Unregisters the distribution and deletes the root filesystem.
```

This does not seem to be a Ubuntu issue. I asked [AskUbuntu](https://askubuntu.com/questions/1436486) and I was asked to raise a issue with MS

I've attached the image of the window asking me to run `wsl --unregister DISTRO_NAME`

![image](https://user-images.githubusercontent.com/17064666/197133618-4dd1b94a-af13-4b11-982b-ba2a510c7b56.png)

### Expected Behavior

Warn the user running `wsl --unregister DISTRO_NAME` will delete their data.

### Actual Behavior

No warning is currently given. 

I had previously faced this same issue ("Something went wrong") and had unknowingly ran `wsl --unregister` (link to my [previous issue](https://github.com/microsoft/WSL/issues/8992) raised here). Which resulted me in loosing my data, I've recovered since then. But adding a warning to let future users know of the consequence would be great.

**Comment by Biswa96** [comment]
> This does not seem to be a Ubuntu issue.

The issue should be reported here https://github.com/ubuntu/WSL/issues. The launcher is provided by Ubuntu.

**Comment by clmnin** [comment]
Closing this issue so that I can recreate it in [ubuntu/WSL](https://github.com/ubuntu/WSL/issues)

**Comment by alexiokay** [comment]
i had ubuntu  and ubuntu 24.04  i used unregister ubuntu 24.04 and it removed ubuntu! not ubuntu 24.04 so I lost my configured ubuintu wsl system.... fuc*

**Comment by hugodegieter** [comment]
hello how did u recover ur data ? i used this command too...
