### ISSUE TITLE
Win32yank weird behavior 

### ISSUE THREAD

**Issue by Souhail-JAMHOUR** [microsoft/WSL#9053]
### Version

Microsoft Windows [Version 10.0.22621.674]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 20.04

### Repro Steps

linked the wine32yank to my path 
`sudo ln -s /mnt/c/Users/souha/scoop/apps/neovim/0.8.0/bin/win32yank.exe /usr/bin/win32yank.exe
`

### Expected Behavior

copy and paste 

### Actual Behavior

![image](https://user-images.githubusercontent.com/96130102/197247488-a2345e0a-0383-412d-a7ca-177b0a5b9d83.png)

**Comment by OneBlue** [comment]
Thank you for reporting this @Souhail-JAMHOUR.

Can you share the output of `strace -f [command]` so we can see what win32yank.exe is trying to do ?

**Comment by Souhail-JAMHOUR** [comment]
Hello @OneBlue thank you for the response, i don't know what happened but i tried to update my WSLInterop.conf  to `:WSLInterop:M::MZ::/init:PF`   instead of `:WSLInterop:M::MZ::/init:F` and that worked, i don't know if that has anything to do with the issue but mine was solved doing so.
Also i updated my wsl .

**Comment by OneBlue** [comment]
Thank you for the update. Closing since the issue has been resolved.
