### ISSUE TITLE
WinDev2022 Eval WSL2

### ISSUE THREAD

**Issue by casedup** [microsoft/WSL#9055]
Trying to run WSL2 inside [Windows 11 Development](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) image . According to the website everything should work out of the box and installed perfectly however getting a weird [virtualization error](https://imgur.com/a/RYVFKzC).

Looked everywhere and all my settings check out mostly because the image provided everything out of the box.  Also to note I am using the VirtualBox provided image.

**Comment by Biswa96** [comment]
Does your hardware or the hypervisor allow nested virtualization? If not WSL1 is the only choice in that environemnt.

**Comment by casedup** [comment]
Yeah I run WSL1 and WSL2 on the same laptop.

**Comment by casedup** [comment]
I also ran Get-VM in Powershell and it's not showing the VirtualBox VM. Instead showing the Virtual instances I created with Multipass.

**Comment by benhillis** [comment]
Does running the image in a hyper-v vm work? Looks like an issue with nested virtualization.
