### ISSUE TITLE
WSL2 consume much memory when run compile jobs

### ISSUE THREAD

**Issue by iamwwc** [microsoft/WSL#9056]
### Version

WSL version: 0.70.0.0 Kernel version: 5.15.68.1 WSLg version: 1.0.45 MSRDC version: 1.2.3575 Direct3D version: 1.606.4 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22621.674

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.68.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Mon Sep 19 19:14:52 UTC 2022

### Distro Version

Debian 11

### Other Software

rust compiler 1.55.0

### Repro Steps

1. clone https://github.com/linkerd/linkerd2-proxy
2. run `cargo b && cargo clean many` times, wsl memory will increase and never release

I found https://github.com/microsoft/WSL/issues/4166, It seems only limit wsl2 memory usage, without solve WSL oom problem actually

### Expected Behavior

memory should return after compile finished

### Actual Behavior

WSL will cause windows OOM :(

**Comment by OneBlue** [comment]
Thank you for reporting this @iamwwc. 

Memory compaction inside WSL2 happens every minute, so you might have to wait up to 60 seconds to see the memory being released.

Can you check if the memory gets released after waiting 60 seconds ?

**Comment by iamwwc** [comment]
sorry too late. no, no too much memory released. before the compilation, memory usage is 25G, after compilation, usage is 31G. 60s after, 29.8G

**Comment by Anton-4** [comment]
I'm also seeing this issue when using cargo. Building my rust project tops out briefly at 14Gib when building on native Linux. When building on WSL, all my RAM (32 Gib) is being used and usage barely drops after building is done for several minutes.
