### ISSUE TITLE
[SEVERE] Cannot use / run wsl headlessly on fresh Windows 2022 install 

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/WSL#9057]
### Version

Microsoft Windows [Version 10.0.20348.1129]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Repro Steps

 1. Install Windows 2022 Datacenter Edition.
 2. Enable the OpenSSH Server feature.
 3. Login to a headless account, like `administrator`.
 4. Run `wsl.exe --install` as per the Microsoft documentation.
 5. Observe it appears to succeed, but actually failed because it failed to run Ubuntu setup.
 6. Observe the following:

Windows Subsystem for Linux is installed.
```
C:/Users/Administrator # dism /online /get-features | grep Linux -A 3 -B 3
Feature Name : VirtualMachinePlatform
State : Enabled

Feature Name : Microsoft-Windows-Subsystem-Linux
State : Enabled

Feature Name : StorageMigrationServiceProxy
```

`wsl` does not work.
```
C:/Users/Administrator # wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```

Installing Ubuntu succeeds, but fails to launch. Here is a result on the machine with exit code 26 reported.

```
C:/Users/Administrator # wsl --install -d Ubuntu; echo $?
Ubuntu is already installed.
Launching Ubuntu...
26
C:/Users/Administrator #
```

Listing all distributions shows no distributions.

```
C:/Users/Administrator # wsl --list --all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
C:/Users/Administrator #
```

### Expected Behavior

`wsl` should work on Windows 2022. You should be able to interact with it without touching a Windows UI. Probably there are essential UI-driven side effects.

### Actual Behavior

`wsl` does not work on Windows 2022.

### Diagnostic Logs

Log collection has the following errors on Windows 2022:

```
PS C:\Users\Administrator> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
PS C:\Users\Administrator> Set-ExecutionPolicy Bypass -Scope Process -Force
PS C:\Users\Administrator> .\collect-wsl-logs.ps1


    Directory: C:\Users\Administrator


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/22/2022   3:12 PM                WslLogs-2022-10-22_15-12-54
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
get-acl : Cannot find path 'C:\ProgramData\Microsoft\Windows\WindowsApps' because it does not exist.
At C:\Users\Administrator\collect-wsl-logs.ps1:35 char:1

+ get-acl "C:\ProgramData\Microsoft\Windows\WindowsApps" | Format-List  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
    + FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand

Log collection is running. Please reproduce the problem and press any key to save the logs.
Saving logs...
Press Ctrl+C to cancel the stop operation.
100%  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
The trace was successfully saved.
Logs saved in: C:\Users\Administrator\WslLogs-2022-10-22_15-12-54.zip. Please attach that file to the GitHub issue.
```

[WslLogs-2022-10-22_15-12-54.zip](https://github.com/microsoft/WSL/files/9845335/WslLogs-2022-10-22_15-12-54.zip)

**Comment by benhillis** [comment]
I'm not seeing any WSL logs in the zip file. Did you do a repro of trying to launch the Ubuntu application? Have you looked through the Event Viewer? The fact that `\programdata\microsoft\windows\windowsapps` is not present makes me think something is misconfigured.

**Comment by doctorpangloss** [comment]
> \programdata\microsoft\windows\windowsapps
Windows Apps are not available on Windows 2022 Server. This is a red herring.

The issue is that you cannot install wsl headlessly. Installing it through a GUI on Windows 2022 works. This is because `wsl --install -d Ubuntu` opens a windowed application (`ubuntu.exe`), instead of attaching to the current console.

**Comment by elsaco** [comment]
@doctorpangloss the Ubuntu installer has `--ui=[gui/tui/none]` option. Pass `[none]` to run the minimal setup experience instead of the Out of the Box Experience.

**Comment by doctorpangloss** [comment]
> @doctorpangloss the Ubuntu installer has `--ui=[gui/tui/none]` option. Pass `[none]` to run the minimal setup experience instead of the Out of the Box Experience.

What exact command should I run? The Ubuntu installer might have that option, but `wsl --install -d Ubuntu --ui=none` fails.

**Comment by doctorpangloss** [comment]
> I'm not seeing any WSL logs in the zip file. 

I ticketed this for you - https://github.com/microsoft/WSL/issues/9066

**Comment by doctorpangloss** [comment]
> Have you looked through the Event Viewer?

There is nothing relevant in Event Viewer (the problem is already figured out, but maybe there should be something in Event Viewer?)

**Comment by elsaco** [comment]
@doctorpangloss look for the command `ubuntu.exe`  then run `ubuntu.exe install --ui=none`. Some of the newer Ubuntu WSL releases have version appended to command, like `ubuntu2204.exe`. In a pwsh session run `gcm ubuntu*` and see what's available on your system.

**Comment by doctorpangloss** [comment]
> `ubuntu install --ui=none`

@elsaco this works and it's a great workaround!

@benhillis this should probably be in the Windows Server 2022 WSL installation docs.

**Comment by DawidGK** [comment]
After a couple of months, is it possible to install WSL on Windows Server 2002 CORE???
I'm using SW_DVD9_Win_Server_STD_CORE_2022_2108.17_64Bit_English_DC_STD_MLF_X23-35659.ISO and the output of wsl command is nothing like literally nothing no matter of installed features:
`PS Z:\ISO\WSL> wsl`
`PS Z:\ISO\WSL> wsl --status`
`PS Z:\ISO\WSL> wsl --install -d Ubuntu; echo $?`
`False`
