### ISSUE TITLE
Can't upgrade or install openssh-client 1:6.61-2ubuntu2.8

### ISSUE THREAD

**Issue by AdelDima** [Microsoft/WSL#906]
Hello, I'm Started to upgrade I faced an error with openssh-client so tried to install it using command : `sudo apt-get install openssh-client=1:6.6p1-2ubuntu2.8`
and this is what I get : 

```
root@PIXELDIMA:/usr/sbin# sudo apt-get install openssh-client=1:6.6p1-2ubuntu2.8
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssh-client is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up openssh-client (1:6.6p1-2ubuntu2.8) ...
dpkg: error processing package openssh-client (--configure):
 unable to install `/etc/ssh/ssh_config.dpkg-new' as `/etc/ssh/ssh_config': File exists
dpkg: dependency problems prevent configuration of openssh-server:
 openssh-server depends on openssh-client (= 1:6.6p1-2ubuntu2.8); however:
  Package openssh-client is not configured yet.

No apport report written because the error message indicates its a followup error from a previous failure.
   dpkg: error processing package openssh-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssh-client
 openssh-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@PIXELDIMA:/usr/sbin#
```

I have tried all solutions that work for users in #143 but nothing work for me.

```
root@PIXELDIMA:/# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up openssh-client (1:6.6p1-2ubuntu2.8) ...
dpkg: error processing package openssh-client (--configure):
 unable to install `/etc/ssh/ssh_config.dpkg-new' as `/etc/ssh/ssh_config': File exists
dpkg: dependency problems prevent configuration of openssh-server:
 openssh-server depends on openssh-client (= 1:6.6p1-2ubuntu2.8); however:
  Package openssh-client is not configured yet.

dpkg: error processing package openssh-server (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
   Errors were encountered while processing:
 openssh-client
 openssh-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@PIXELDIMA:/#
```

**Comment by rodrymbo** [comment]
Perhaps it would help to understand what's going on, by saying a bit more about why you issued that first command. Was there something wrong with the ssh client, and you were trying to fix it?

There are [some good instructions](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10&sid=c6b7cb83cc3e3d9cf51a093b784423ac) available for running the sshd server.  

The quick method is to use the command `sudo /etc/init.d/ssh start`, and minimize the bash console. Then you can try `ssh localhost` to see if the client is configured. The Windows firewall may need tweaking.

On the other hand apt-get should have been able to handle this a bit more elegantly. 

Do you get the same errors if you uninstall both sshd and ssh (with `apt-get`), then clear /etc/ssh (where the configurations in question are supposed to live), then reinstall both (`with apt-get`)?

**Comment by AdelDima** [comment]
@rodrymbo I was going to install python-pip in order to work with **Gitsome** command so something goes into another and I end facing this issue.

**Comment by therealkenc** [comment]
> sudo apt-get install openssh-client=1:6.6p1-2ubuntu2.8

That won't work in general because of (like dpkg says) dependency problems. You'll see the same behaviour on Real Linux.
