### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/CreateVm/0x8007000d in windows 11

### ISSUE THREAD

**Issue by neuberfran** [microsoft/WSL#9065]
### Windows build number:

22499.rs_prerelease.21105-155

### Your Distribution version:

20.04

### Your WSL versions:

 **wsl --version**
Versão do WSL: 0.70.4.0
Versão do kernel: 5.15.68.1
Versão do WSLg: 1.0.45
Versão do MSRDC: 1.2.3575
Versão do Direct3D: 1.606.4
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows versão: 10.0.22499.1010
PS C:\Users\neuberfran> wsl -l
Distribuições do Subsistema do Windows para Linux:
Ubuntu-20.04 (Padrão)
Debian

### My issue(specifications):

I have windows 11 here with issue:
(Look pic)
**Error code: Wsl/Service/CreateInstance/CreateVm/0x8007000d**
(Look pic)

When I change date to 14.09.2022 I solved this issue.
But that's not what I want

I can't update my windows because I have i7 2600. I can't reinstall too

How to solve my issue?

Pls

![issue02](https://user-images.githubusercontent.com/38701397/197438497-f20e82d1-44e3-497d-b448-f40542791570.png)
![issue01](https://user-images.githubusercontent.com/38701397/197438502-7ad2c3fe-8bb3-4c0b-b032-6784603017d0.png)

**Comment by benhillis** [comment]
You are on a quite old prerelease build - you'll have to either install a retail build or update.

**Comment by neuberfran** [comment]
@benhillis I can't update. I tried several things here
