### ISSUE TITLE
Unable to do `sudo apt-get update`

### ISSUE THREAD

**Issue by cr2007** [microsoft/WSL#9069]
### Version

Microsoft Windows [Version 10.0.22621.674]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Open Ubuntu
2. Enter the command `sudo apt update` (failing)
3. Wait for the updates to arrive
4. Enter `sudo apt upgrade`

### Expected Behavior

When I am trying to run `sudo apt update` to get the latest updates from the server, it always comes as **Failed** and produces this output.

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
```

It is expected to connect and receive any latest updates from the Ubuntu servers.

### Actual Behavior

Everytime I run the command, this is the error I get all the time.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/73425927/197854504-7456fd0a-8f17-460b-ae34-862b73f3a6f6.png">

**Comment by 03y** [comment]
By the looks of the errors; this can be solved by changing your DNS in `/etc/resolv.conf`:
```
nameserver 1.1.1.1 # Or your preference
```

You can also write into `/etc/wsl.conf` to stop this being overwritten:
```
[network]
generateResolvConf = false
```
