### ISSUE TITLE
wsl.conf `generateResolvConf = false` always deleted `/etc/resolv.conf`

### ISSUE THREAD

**Issue by kkbruce** [microsoft/WSL#9074]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

None.

### Repro Steps

I want to set up the company `nameserver` to `/etc/resolv.conf`.

step 1: 

Ref doc https://learn.microsoft.com/en-us/windows/wsl/wsl-config add `/etc/wsl.conf` and config:

```
[network]
generateResolvConf = false
```

step 2:

Close WSL terminal and run `wsl --shutdown` to restart the WSL instance. Open a new WSL terminal. 

step 3:

`ls /etc` confirm folder, no `/etc/resolv.conf` file. `sudo nano /etc/resolv.conf` set up company `nameserver`.

step 4:

re-step 2, if WSL instance restart, `/etc/resolv.conf` always is deleted. We must set up a new  `/etc/resolv.conf` for every restart WSL instance.

### Expected Behavior

```
[network]
generateResolvConf = false
```

My understanding is to turn off the auto-generating function, But he seems to have deleted the ResolvConf function. I need persistence to be set in the `/etc/resolv.conf` file.

### Actual Behavior

Every restart WSL instance, always deleted `/etc/resolv.conf`.

**Comment by haomingz** [comment]
Same issue here, I temporarily fixed the issue by using `chattr +i /etc/resolv.conf`.
