### ISSUE TITLE
Error: Can't open display: :0 on Win11 22000

### ISSUE THREAD

**Issue by nobumacsuzuki** [microsoft/WSL#9078]
### Version

Microsoft Windws 11, 22000.1908

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Other Software

x11-apps (xeye)

### Repro Steps

install WSL2 (from elevated powershell, "wsl --install")
once Ubuntu installed
-sudo apt-get update
-sudo apt-get upgrade 
-sudo apt-get install x11-apps
-xeye

### Expected Behavior

xeye launch on Windows desktop

### Actual Behavior

return error message to Ubuntu console "Error: Can't open display: :0"

### Diagnostic Logs

nsuzuki@MacMiniBookX:~$ xeyes&
[1] 3456
nsuzuki@MacMiniBookX:~$ Error: Can't open display: :0
^C
[1]+  Exit 1                  xeyes
nsuzuki@MacMiniBookX:~$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
nsuzuki@MacMiniBookX:~$ echo $DISPLAY
:0
nsuzuki@MacMiniBookX:~$ ls -la /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 Oct 27 16:59 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
nsuzuki@MacMiniBookX:~$ ls -la /tmp/.X11-unix/
total 0
drwxrwxrwx 2 root root  40 Oct 27 17:03 .
drwxrwxrwt 6 root root 260 Oct 27 16:59 ..
[weston.log](https://github.com/microsoft/WSL/files/9883819/weston.log)

**Comment by benhillis** [comment]
Are you using systemd? I'm currently looking into issues where systemd is stomping over required WSLg state.

**Comment by nobumacsuzuki** [comment]
no, not intentionally, unless systemd is installed when ubuntu is installed.
I have not installed any additional package after ubuntu installation,
rather than
run "apt-get update"
run "apt-get upgrade", and
run "apt-get install x11-apps"

Nobu,

2022年10月28日(金) 9:50 Ben Hillis ***@***.***>:
