### ISSUE TITLE
Why was bug WSL complete freeze #8824 closed this issue is still happening please reopen

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#9085]
### Version

Microsoft Windows [Version 10.0.22623.875]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Fedora Linux 37 (Container Image)

### Repro Steps

See details in Why was bug WSL complete freeze #8824 see my attached dumps and reopen this issue its definitely not fixed and I'm running latest version of wsl, why was this issue closed it have no reason

### Expected Behavior

wsl hangs after a while

### Actual Behavior

should not hang

**Comment by neoGeneva** [comment]
Hey @OneBlue, I'm also experiencing a freeze in Windows 10.0.22623.875 with WSL 0.70.4 kernel version 5.15.68.1 (though I'm running Ubuntu.)

For me at least it seems to hang very reliably after waking from sleep, I've followed the steps above to generate a dump and logs:

- [WslLogs-2022-11-01_21-09-08.zip](https://github.com/microsoft/WSL/files/9908071/WslLogs-2022-11-01_21-09-08.zip)
- [wslservice.zip](https://drive.google.com/file/d/1i7o-FSgOal5WLesFCKjNr2zSVr1hdKJb/view?usp=sharing)

**Comment by philsson** [comment]
> Hey @OneBlue, I'm also experiencing a freeze in Windows 10.0.22623.875 with WSL 0.70.4 kernel version 5.15.68.1 (though I'm running Ubuntu.)
> 
> For me at least it seems to hang very reliably after waking from sleep, I've followed the steps above to generate a dump and logs:
> 
>     * [WslLogs-2022-11-01_21-09-08.zip](https://github.com/microsoft/WSL/files/9908071/WslLogs-2022-11-01_21-09-08.zip)
> 
>     * [wslservice.zip](https://drive.google.com/file/d/1i7o-FSgOal5WLesFCKjNr2zSVr1hdKJb/view?usp=sharing)

I second this. Frozen after sleep and running `wsl --shutdown` hangs and never returns. Also CPU utilization is through the roof. @neoGeneva if you know how to resolve this without a full restart of the computer please tell.
I am also experiencing this on the same kernel version
```WSL-version: 0.70.4.0
Kernelversion: 5.15.68.1
WSLg-version: 1.0.45
MSRDC-version: 1.2.3575
Direct3D-version: 1.606.4
DXCore-version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows: 10.0.22000.1098
```
With windows version `21H2 (OS Build 22000.1098)`

**Comment by neoGeneva** [comment]
@philsson I've found that if I end task `vmwp.exe` in task manager then it'll start responding again.

**Comment by philsson** [comment]
> @philsson I've found that if I end task `vmwp.exe` in task manager then it'll start responding again.

Tried this today and it gave me the bluescreen of death 😄

**Comment by androiddisk** [comment]
I have the same problem. No new wsl shell window can be created, and the wsl -- shutdown window is stuck. Even the window cannot be closed.  Version 0.70.4.0 is not downloaded from GitHub. It is the 0.70.4.0 version automatically updated by Windows. It should be the same as GitHub https://github.com/microsoft/WSL/releases/tag/0.70.4
This problem has troubled me for a long time.




```
PS C:\Users\zhong> wsl --version
WSL 版本： 0.70.4.0
内核版本： 5.15.68.1
WSLg 版本： 1.0.45
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.674
```


I will cooperate with you if you need me. thank you

**Comment by mwoodpatrick** [comment]
> `vmwp.exe` in

This did not work for me, killing wslservice.exe did work for me

**Comment by neoGeneva** [comment]
Hey, I've figured out a little bit more of why this is happening for me. It turns out all of my Windows Store apps (and even any UWP apps I've built locally) automatically close when my computer goes to sleep.

As part of looking into that I audited what was closing, and I saw `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe\wsl.exe` is one of them, and I'm pretty sure that's my issue.

I uninstalled the WSL store version, and it seems to have fixed the issue for me, though all my Windows Store apps still close inexplicably. I've seen suggestions it's possibly driver related (updating everything didn't help me) or Modern Standby related (disabling that made my pc blue screen on sleep), so I'm stumped on that part of my issue.

**Comment by springjools** [comment]
Same thing is happening for me, killing vmwp.exe yields a BSOD. This happens after I updated the wsl to preview build

**Comment by neoGeneva** [comment]
I think I mentioned it elsewhere, but in the end the issue for me was the "Instant Hotspot" feature in the "Phone Link" app, which caused all UWP / Windows store apps to close on sleep, which in turn caused WSL to hang. Thought I should mention it just it case you use Phone Link.
