### ISSUE TITLE
No CUDA Runtime is Found on WSL2

### ISSUE THREAD

**Issue by fschvart** [microsoft/WSL#9092]
I'm using a freshly installed system.
Installed the latest Nvidia drivers, installed CUDA Toolkit 11.7
Installed WSL 2, and used Ubuntu 20.04, I ran wsl --update
Installed conda and then PyTorch 1.13 with CUDA 11.7

When I run nvidia-smi I can see my 3 GPUs, however when I try to run torch.cuda.is_available() I get False and I get this following warning:

/home/fabian/miniconda3/envs/torch/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 2: out of memory (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0

I tried some of the guide online, including delete libcuda.so and libcuda.so.1 and linking them to libcuda.so.1.1 but that didn't help.
Now when I run ldconfig within Ubuntu, I get the following error:   Can't link /usr/lib/wsl/lib/libnvoptix_loader.so.1 to libnvoptix.so.1

I'll really appreciate your help

**Comment by sirredbeard** [comment]
You installed the latest Nvidia drivers on Windows, right?

It's possible CUDA Toolkit 11.7 is causing issues, potentially pre-empting the WSL-loaded CUDA drivers.

I would start fresh without CUDA Toolkit or symlinking hacks. In my experience those cause more issues than solve them.

**Comment by fschvart** [comment]
Thank you @sirredbeard 

What do you mean by starting fresh? 
Do you mean running wsl --unregister and then register again Ubuntu 20.04?  Or do you mean something else? And once I do that, do you suggest I run PyTorch 1.13 with CUDA 11.6? 

One more important thing to mention, on Windows if I build a similar conda environment and run torch.cuda.is_available() I do get True, so there's no problem with the drivers or with the GPUs. (with latest PyTorch and CUDA 11.7).

Thanks again!

**Comment by elsaco** [comment]
@fschvart this is how I've installed `pytorch` on `Ubuntu-20.04.5` WSL image:

1. install `miniconda` from `https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`
2. run `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia` 
3.  verify:
```
(base) tux@eleven:~$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.13.0'
>>> torch.cuda.is_available()
True
>>>
```

I didn't install any `cuda-toolkits`. The Widows driver used for testing is `517.40`

**Comment by fschvart** [comment]
> @fschvart this is how I've installed `pytorch` on `Ubuntu-20.04.5` WSL image:
> 
> 1. install `miniconda` from `https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`
> 2. run `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`
> 3. verify:
> 
> ```
> (base) tux@eleven:~$ python
> Python 3.9.12 (main, Apr  5 2022, 06:56:58)
> [GCC 7.5.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> torch.__version__
> '1.13.0'
> >>> torch.cuda.is_available()
> True
> >>>
> ```
> 
> I didn't install any `cuda-toolkits`. The Windows driver used for testing is `517.40`

I tried it just now. Created a new environment with a fresh Python install and installing the packages as you showed here and it just doesn't work. I still get the same error, and I still get the same error when I try to run ldconfig

**Comment by pienapin** [comment]
for the error: Can't link /usr/lib/wsl/lib/libnvoptix_loader.so.1 to libnvoptix.so.1
i managed to fix it by renaming the **libnvoptix.so.1** on the lib directory of lxss to be **libnvoptix_loader.so.1**

i don't know if it's actually a proper solution since i don't understand what it does, but at least it got rid of the error message.

**Comment by Ayke** [comment]
`nvidia-smi` works means your CUDA in Windows works. For CUDA runtime install please see https://docs.nvidia.com/cuda/wsl-user-guide/index.html

Also you may check my notes for references: https://gist.github.com/Ayke/5f37ebdb84c758f57d7a3c8b847648bb
