### ISSUE TITLE
No systemd support on Windows DevKit 2023

### ISSUE THREAD

**Issue by Gerdya** [microsoft/WSL#9094]
### Version

 10.0.22623.875

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.68.1

### Distro Version

Ubuntu 22.04

### Repro Steps

I did a fresh install on my newly delivered Windows DevKit 2023 as follows:

Powershell:
wsl --install (which installed WSL2 and Ubuntu 20.04)

inside Ubuntu:
sudo do-release-upgrade -d (which did upgrade to 22.04)

inside Ubuntu:
create /etc/wsl.conf  with:
[boot]
systemd=true

wsl --shutdown

### Expected Behavior

xxxx@DevKit:/etc$ systemctl
Failed to connect to bus: No such file or directory

### Actual Behavior

systemctl works

### Diagnostic Logs

Please let me know if you need more information.

**Comment by Biswa96** [comment]
You have to install WSL Preview from Windows Store.

**Comment by Gerdya** [comment]
I have the following versions installed:
wsl --version
WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.875

wsl --status
Default Distribution: Ubuntu
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.

Note: I do have precisely the same WSL version ( 0.70.5.0) on my Surface Pro X, where systemd works.

**Comment by elsaco** [comment]
`systemd` works on DevKit 2023. Test was done using `Debian` but it should work with any other `Ubuntu` distros also:

```
WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.169
```

and sample `systemctl` output:

```
tux@dragon:~$ systemctl status user.slice
● user.slice - User and Session Slice
     Loaded: loaded (/lib/systemd/system/user.slice; static)
     Active: active since Mon 2022-10-31 15:49:41 PDT; 29s ago
       Docs: man:systemd.special(7)
      Tasks: 0
     Memory: 0B
     CGroup: /user.slice
```

Output of `gcim win32_baseboard`:

```
Manufacturer : Microsoft Corporation
Model        :
Name         : Base Board
SerialNumber : <deleted>
SKU          :
Product      : Windows Dev Kit 2023
```

**Comment by Gerdya** [comment]
I did created logs:
1) start logging
2) start wsl/ubuntu
3) stop logging

[WslLogs-2022-11-01_10-12-26.zip](https://github.com/microsoft/WSL/files/9908489/WslLogs-2022-11-01_10-12-26.zip)

**Comment by OneBlue** [comment]
Thank you @Gerdya.

Looking at the logs, it looks like /sbin/init just failed to start on your ubuntu distribution. 

Can share the output of `ps aux`, `ls -la /proc/1/fd` and `dmesg` inside ubuntu ?
