### ISSUE TITLE
WSL not using .wslconfig

### ISSUE THREAD

**Issue by Alex-S42** [microsoft/WSL#9098]
### Version

Microsoft Windows [Version 10.0.19042.2132]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Clone the WSL kernel repository and compile the kernel.
Copy the compiled image to (e.g.) C:\Users\<username>\vmlinux
Create a file C:\Users\<username>\.wslconfig with the following content:
```
[wls2]
kernel=C:\\Users\\<username>\\vmlinux
debugConsole=true
```
Shutdown WSL and restart WSL.

### Expected Behavior

The compiled kernel is used.
Debug-console is opened showing dmesg output.

### Actual Behavior

The kernel installed in C:\Windows\system32\lxss\tools is used. Checked via 'uname -a':
```
~$  uname -a
Linux FRECLT30391 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
No dmesg output shown on start-up.

### Diagnostic Logs

Done on a PC with corporate administration and policies, but (limited) local administrative rights.

**Comment by elsaco** [comment]
@Alex-S42 on Windows 10 there's no `debugConsole`.

However custom kernels should load.  This is on Windows 10 `build 19045` and local build kernel:

```
tux@RIPPER:~$ uname -a
Linux RIPPER 5.15.68.1-custom-WSL2+ #1 SMP Tue Nov 1 10:34:29 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

WSL info:

```
PS C:\Users\elsaco> wsl --status
Default Distribution: Jammy
Default Version: 2

Windows Subsystem for Linux was last updated on 3/26/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

Changing `CONFIG_LOCALVESION` helps knowing what kernel is running. Another way to see if the kernel location is being picked by WSL engine modify the `kernel` path and you should see this errors:

```
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
Press any key to continue...
```

At least you'll know `.wslconfig` is bein read.

**Comment by Alex-S42** [comment]
I found the problem (mea culpa 😫). I had a typo in .wslconfig, where I wrote [wls2] instead of [wsl2]. Even after looking dozens of times into that file, I didn't recognize it. Now it works.
Thank you, @elsaco and @OneBlue for your time! 🙏

**Comment by neojob** [comment]
To solve the problem, you need to check if the file is named ".wslconfig.txt" and remove the ".txt" extension if it exists. Renaming the file to ".wslconfig" will resolve the issue.
