### ISSUE TITLE
no source

### ISSUE THREAD

**Issue by Warren-ops** [microsoft/WSL#9104]
### Version

Microsoft Windows [Version 10.0.22623.875]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

kali-linux rolling

### Repro Steps

root@GHOST:/home/ghost/phone/dahdi-linux-3.2.0# make
make -C drivers/dahdi/firmware firmware-loaders
make[1]: Entering directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
Attempting to download dahdi-fwload-vpmadt032-1.25.0.tar.gz
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2022-11-01 19:02:59--  http://downloads.digium.com/pub/telephony/firmware/releases/dahdi-fwload-vpmadt032-1.25.0.tar.gz
Resolving downloads.digium.com (downloads.digium.com)... 170.249.154.172
Connecting to downloads.digium.com (downloads.digium.com)|170.249.154.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149360 (146K) [application/x-gzip]
Saving to: ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’

      dahdi-   0%       0  --.-KB/s
     dahdi-f  59%  86.74K   410KB/s
dahdi-fwload 100% 145.86K   448KB/s    in 0.3s

2022-11-01 19:03:00 (448 KB/s) - ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’ saved [149360/149360]

make[1]: Leaving directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
You do not appear to have the sources for the 5.15.68.1-microsoft-standard-WSL2 kernel installed.
make: *** [Makefile:72: modules] Error 1

### Expected Behavior

build dep

### Actual Behavior

root@GHOST:/home/ghost/phone/dahdi-linux-3.2.0# make
make -C drivers/dahdi/firmware firmware-loaders
make[1]: Entering directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
Attempting to download dahdi-fwload-vpmadt032-1.25.0.tar.gz
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2022-11-01 19:02:59--  http://downloads.digium.com/pub/telephony/firmware/releases/dahdi-fwload-vpmadt032-1.25.0.tar.gz
Resolving downloads.digium.com (downloads.digium.com)... 170.249.154.172
Connecting to downloads.digium.com (downloads.digium.com)|170.249.154.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149360 (146K) [application/x-gzip]
Saving to: ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’

      dahdi-   0%       0  --.-KB/s
     dahdi-f  59%  86.74K   410KB/s
dahdi-fwload 100% 145.86K   448KB/s    in 0.3s

2022-11-01 19:03:00 (448 KB/s) - ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’ saved [149360/149360]

make[1]: Leaving directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
You do not appear to have the sources for the 5.15.68.1-microsoft-standard-WSL2 kernel installed.
make: *** [Makefile:72: modules] Error 1

### Diagnostic Logs

root@GHOST:/home/ghost/phone/dahdi-linux-3.2.0# make
make -C drivers/dahdi/firmware firmware-loaders
make[1]: Entering directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
Attempting to download dahdi-fwload-vpmadt032-1.25.0.tar.gz
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2022-11-01 19:02:59--  http://downloads.digium.com/pub/telephony/firmware/releases/dahdi-fwload-vpmadt032-1.25.0.tar.gz
Resolving downloads.digium.com (downloads.digium.com)... 170.249.154.172
Connecting to downloads.digium.com (downloads.digium.com)|170.249.154.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149360 (146K) [application/x-gzip]
Saving to: ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’

      dahdi-   0%       0  --.-KB/s
     dahdi-f  59%  86.74K   410KB/s
dahdi-fwload 100% 145.86K   448KB/s    in 0.3s

2022-11-01 19:03:00 (448 KB/s) - ‘dahdi-fwload-vpmadt032-1.25.0.tar.gz’ saved [149360/149360]

make[1]: Leaving directory '/home/ghost/phone/dahdi-linux-3.2.0/drivers/dahdi/firmware'
You do not appear to have the sources for the 5.15.68.1-microsoft-standard-WSL2 kernel installed.
make: *** [Makefile:72: modules] Error 1

**Comment by elsaco** [comment]
@Warren-ops the source of the WSL kernel is at https://github.com/microsoft/WSL2-Linux-Kernel/releases

**Comment by Warren-ops** [comment]
@elsaco could you send me the steps to install this? I'm a noob still got tons to learn lol
