### ISSUE TITLE
Loading WSL Remote

### ISSUE THREAD

**Issue by manuelortizus** [microsoft/WSL#9105]
### Version

Microsoft Windows [Versión 10.0.22000.978]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Distro Version

20.04

### Other Software

Visual Studio Code 1.72.2 with Remote-WSL Extension 0.72.0

### Repro Steps

The Repro steps are:
- Open WSL with Windows Terminal
- Go to the directory project
- Entering: `code` or `code .`
![image](https://user-images.githubusercontent.com/106709436/199360669-b8fa399b-a98e-4411-8560-ce7779e05f07.png)
- VSC open with WSL Remote
- VSC loading stuck
![image](https://user-images.githubusercontent.com/106709436/199360694-39723765-c700-4b4d-92a2-e07a31be05a1.png)

### Expected Behavior

I expecting to see working WSL Remote to develope there as the image shows it
![image](https://user-images.githubusercontent.com/106709436/199361221-eac5ba56-f513-4bfe-b89f-2c891444c20e.png)

### Actual Behavior

Instead happened that the WSL Reamote is loading in a stuck way
![image](https://user-images.githubusercontent.com/106709436/199360793-e8c65922-860e-48e7-acf9-ba15ee796566.png)

### Diagnostic Logs

https://aka.ms/AAilkvk

https://aka.ms/AAilkvk

**Comment by NotTheDr01ds** [comment]
Might this be a better fit for the [VSCode Remote Development repo](https://github.com/microsoft/vscode-remote-release)?

**Comment by manuelortizus** [comment]
> Might this be a better fit for the [VSCode Remote Development repo](https://github.com/microsoft/vscode-remote-release)?

Yes, that's truth, thanks for the feedback

**Comment by frivard-coveo** [comment]
Seems related to my issue : https://github.com/microsoft/vscode-remote-release/issues/7858
