### ISSUE TITLE
When running Snapd programs with built-in Systemd support, there is some Waring about D-Bus session daemon

### ISSUE THREAD

**Issue by linghengqian** [microsoft/WSL#9118]
### Version

Microsoft Windows [版本 10.0.22621.755]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 22.04

### Other Software

vlc, version 3.0.18 . Refer to https://snapcraft.io/vlc .
gnome-text-editor, version 42.2 . Refer to https://snapcraft.io/gnome-text-editor .

### Repro Steps

- Download and open https://www.microsoft.com/store/productId/9PDXGNCFSCZV .
- Edit `/etc/wsl.conf` and restart the WSL instance to turn on systemd support.
- Run the following command to install the snapcraft program.
```shell
sudo apt update && sudo apt upgrade -y
sudo snap install gnome-text-editor
sudo snap install vlc
```
- Open the application with the following two commands, and we can see the log.
```shell
gnome-text-editor ~/.bashrc
vlc
```

### Expected Behavior

- Considering that D-Bus is a basic component, I don't think there should be a warning related to this.

### Actual Behavior

- When executing `vlc`, I saw some warnings related to D-Bus.
```shell
lingh@DESKTOP-TPTE5D5:~$ vlc
2022/11/05 11:00:21.215286 cmd_run.go:1055: WARNING: cannot start document portal: dial unix /run/user/1000/bus: connect: no such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
VLC media player 3.0.18 Vetinari (revision 3.0.18-0-ge9eceaed4d)
[000055593a3cb670] dbus interface error: Failed to connect to the D-Bus session daemon: Failed to connect to socket /run/user/1000/bus: No such file or directory
[000055593a3cb670] main interface error: no suitable interface module
[000055593a313a10] main libvlc error: interface "dbus,none" initialization failed
[000055593a313a10] main libvlc: 正在以默认界面运行 vlc。使用“cvlc”可以无界面模式使用 vlc。
[000055593a3d85d0] main playlist: playlist is empty
```
- ![image](https://user-images.githubusercontent.com/20187731/200098169-1317be93-f728-410c-8519-a038934cbb92.png)

- When executing `gnome-text-editor ~/.bashrc`, I also saw some warnings related to D-Bus.
```shell
lingh@DESKTOP-TPTE5D5:~$ gnome-text-editor ~/.bashrc
2022/11/05 11:03:04.902465 cmd_run.go:1055: WARNING: cannot start document portal: dial unix /run/user/1000/bus: connect: no such file or directory

(process:1852): Gdk-WARNING **: 11:03:06.028: Settings portal not found: 无法连接：No such file or directory
Gdk-Message: 11:03:06.322: Failed to get file transfer portal: 无法连接：No such file or directory
```
- ![image](https://user-images.githubusercontent.com/20187731/200098193-7050a05b-b765-4ddf-af05-4ab8b814fd3d.png)

### Diagnostic Logs

- Null.

**Comment by cerebrate** [comment]
This is #8842 ; the quick answer is that the way wsl.exe creates Linux-side processes doesn't go through PAM, so a user login session is never set up, so a user systemd instance is never started, so a user dbus is never created.

(There are various workarounds for this. Mine is [bottle-imp](https://github.com/arkane-systems/bottle-imp), which I'm mentioning here because there are also several gotchas to implementing functioning user-login-session support which it fixes, and it would take a long time to explain them all.

...WSL team, I hope it's not too bad form to advertise my own solution like this, but...)

**Comment by linghengqian** [comment]
- @pmartincic I noticed that you have made a self-assignment in https://github.com/microsoft/WSL/issues/8842 . Should I close this issue of mine?

**Comment by sbroberg** [comment]
@cerebrate: You mention that bottle-imp is a workaround.  How do you use it to fix the problem?  I've installed it according to the instructions on your link, but I'm not sure to do with it once it's installed - the README is a bit inscrutable to someone with my understanding of what systemd is doing.  I ran "imp -i", but all the other commands just produce an error that says "imp: cannot launch command; systemd-machined is not active".

**Comment by cerebrate** [comment]
@sbroberg

Which distro are you using?

_bottle-imp_ uses _systemd-machined_ (apt package name: _systemd-containerd_ for some reason) to start user sessions when you use one of the -s/-c/-l options (and thus ensure that all the PAM/systemd session initialization is done correctly). That error message is the one you get if _systemd-machined_ is somehow not enabled - despite _bottle-imp_ doing so at runtime - or not installed, which the (Debian/Arch) packaged versions of _bottle-imp_ should do automatically.

You can check the state of the service with

`systemctl status systemd-machined`

If it's not installed/can't be found, installing it should solve your problem. If it's something weirder, please open an issue over at the _bottle-imp_ repo, and I'll see what I can do.

**Comment by linghengqian** [comment]
- Now under Ubuntu 22.04.3 WSL, both warnings using `vlc` and `gnome-text-editor` are gone. This issue has been resolved. I'm going to close this issue, although https://github.com/microsoft/WSL/issues/8842 still hasn't closed.
- ![image](https://github.com/microsoft/WSL/assets/20187731/b2569f25-c483-424c-b3f7-d526031fe875)
