### ISSUE TITLE
WSL1 doesn't see some files till I `wsl --shutdown`.

### ISSUE THREAD

**Issue by gavenkoa** [microsoft/WSL#9128]
### Version

Microsoft Windows [Version 10.0.19044.2193]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Repro Steps

WSL1 `ls` showed nothing. Explorer & Cygwin `ls` showed files. Same with `tree`.

WSL1 `git status` reported that files were deleted, Cygwin reported a repository was clean.

They were all from the same directory. File permissions were same as in the other directories.

PC used hibernation several days.

Closing all WSL apps (tmux/bash/gcloud) and  `wsl --shutdown` from cmd.exe resolved issue.

I didn't want to close useful tmux session although my intuition that "reboot" of WSL 1 would help was correct.

### Expected Behavior

Windows files are visible to WSL1.

### Actual Behavior

Some files were not visible.

**Comment by gavenkoa** [comment]
I didn't know what was special about those files or containing directory nor what should I looked at to collect troubleshooting info.

**Comment by OneBlue** [comment]
Thanks for reporting this @gavenkoa. Can you please share detailed instructions on how to reproduce the issue, with the exact commands to run and the outputs you got ?

**Comment by gavenkoa** [comment]
I experienced this on the same directory once more and this time the problem disappeared after I changed working directory.

I have Sophos antivirus installed. If there's any instruction about diagnostic I could provide? The problem is rarely reproducible.
