### ISSUE TITLE
Unable to access Springboot app running on host machine from WSL or Container within WSL.

### ISSUE THREAD

**Issue by coolyoyo** [microsoft/WSL#9136]
### Version

Microsoft Windows [Version 10.0.19042.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Spring boot running on localhost machine at port 8090. Able to access it by hitting localhost:8090 or {ip}:8090 from browser.
2. I have container running on WSL mapped to host port 8080. I am able to access the application running in container via host machine browser by hitting localhost:8080/actuator/info.
3. Now when I try to access the app running on host machine at port 8090 inside container, I am getting error as "[Connection refused](curl: (7) Failed to connect to x.x.x.x port 8090: Connection refused)". I had performed below steps to debug the same,
i. I tried many steps including accessing based on IP on /etc/hosts, then opening the firewall by creating Inbound rules allowing all the connections. But nothing seems to working.
ii. From WSL if I am unable to ping the host machine ip address.

### Expected Behavior

1. From WSL terminal, I should be able to hit the service running  on host machine localhost:8090
2. From Container I should be able to hit the service running  on host machine localhost:8090

### Actual Behavior

curl: (7) Failed to connect to x.x.x.x port 8090: Connection timed out

**Comment by OneBlue** [comment]
Thank you for reporting this @coolyoyo. 

 That's by-design: there is no mechanism to relay traffic from the host to the guest. If you need to do this, the simplest would be to use the host's ip address (and make sure that the port you're trying to access is visible from that address) (see https://devdojo.com/mvnarendrareddy/access-windows-localhost-from-wsl2 )

**Comment by spyro2000** [comment]
I am having exactly the same problem. Having a Spring Boot Service running on Windows host on Port 8020 but can't curl or telnet it from inside WSL2. I created a incoming firewall rule etc. but it just doesn't work (timeout).  I can ping the host IP, but I cannot connect to port 8020 on host.

From powershell on windows host, the curl command works.

**Comment by Szafa99** [comment]
Here is what worked for me:

**sudo update-alternatives --set iptables /usr/sbin/iptables-legacy**
**sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy**
 **sudo service docker restart**

**Comment by coolyoyo** [comment]
> Here is what worked for me in wsl2 Ubuntu:
> 
> **sudo update-alternatives --set iptables /usr/sbin/iptables-legacy** **sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy** **sudo service docker restart**

Sure will give a try on this. Thanks for the reply

**Comment by coolyoyo** [comment]
Sure will give a try on this. Thanks for the reply
