### ISSUE TITLE
Ubuntu 20.04 terminal blank, no prompt, can't type any commands

### ISSUE THREAD

**Issue by jessicarowell** [microsoft/WSL#9138]
### Version

Microsoft Windows [Version 10.0.22000.1219]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

no other software, just opening the Ubuntu 20.04 terminal

### Repro Steps

Click on Ubuntu 20.04 icon to open a terminal, or issue `wsle.exe` command in Windows Search bar.

### Expected Behavior

I except the terminal window to open with a prompt that allows me to type code.  

### Actual Behavior

When I open a terminal I get a blank terminal with no cmd prompt and I cannot type anything.  No `wsl.exe` commands get executed and no error gets produced.  `wsl.exe --version` just never returns anything.

### Diagnostic Logs

Also submitted via Feedback Hub.
[WslLogs-2022-11-11_12-26-11.zip](https://github.com/microsoft/WSL/files/9992409/WslLogs-2022-11-11_12-26-11.zip)

**Comment by lpm-nova** [comment]
Having exact same problem, but with Debian 1.13.0.0.

**Comment by jessicarowell** [comment]
@lpm-nova how long has your problem persisted?  My Ubuntu 20.04 app was working fine yesterday through at least 18:00 EST.  I noticed the problem this morning just after 10:00 EST but I'm not sure when between those times it first began.

**Comment by Biswa96** [comment]
Can you provide the output of `wsl.exe -l -v` ?

**Comment by lpm-nova** [comment]
@jessicarowell everything was working fine yesterday.

@Biswa96 wsl.exe is completely unresponsive.

**Comment by lpm-nova** [comment]
@Biswa96 I went into system32 dir and checked my wsl.exe file's properties. It's 10.0.22621.1. 192 KB, modified 5/7/2022

**Comment by lpm-nova** [comment]
hrm, just did wsl.exe -l -v and nothing.
but I did wsl-exe --version and it's returning:
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

**Comment by jessicarowell** [comment]
@Biswa96 same for me - it's completely unresponsive.
@lpm-nova - where on your computer are you entering `wsl.exe --version` and getting output (e.g., are you entering in the search bar, or in cmd prompt, or somewhere else)?  I can't get any output at all.

**Comment by lpm-nova** [comment]
@jessicarowell  I was running the command in the cmd prompt. Though earlier I DID click on the windows\system32\wslconfig.exe executable.

I have absolutely no clue if that did anything, but just in case it did, I'm letting you know.

**Comment by jessicarowell** [comment]
@lpm-nova Hmm...interesting.  I tried both those things - first clicking on windows\system32\wslconfig.exe and then entering `wsl.exe --version` in Windows cmd prompt and got nothing.  It just never returns anything.

**Comment by lpm-nova** [comment]
It's magically working now...

**Comment by jessicarowell** [comment]
@lpm-nova That's great!  Mine is still broken...hope someone posts some suggestion soon. It's frustrating that I can't even provide @Biswa96 with the result of `wsl.exe -l -v` because the WSL console is unresponsive.

**Comment by muhammadsalmanafzal** [comment]
Same problem here. For me, it happens when I have wsl running and I put pc to sleep or hibernate, after waking up, I work as usual but after that, it does not shut down on its own and even `wsl --shutdown` stops working. `-l -v` is not working, and I have to manually kill the wsl preview process (with the little blue penguin icon) in task manager and then try again to start working.

**Comment by jessicarowell** [comment]
@Biswa96 My Docker Desktop also hung (t was "starting" all day).  I force-shutdown Docker Desktop using Task Manager, and confirmed that it shut down, but that didn't fix the problem.  I can see in Task Manager the VmmemWSL process is at 98% CPU usage and 1.6GB RAM usage, but I am unable to force-shutdown ("The operation could not be completed.  Access is Denied").  Following what @muhammadsalmanafzal said, I tried `wsl --shutdown` and it hangs, just like any `wsl` command I issue.

**Comment by jessicarowell** [comment]
This morning it works.  I don't see that any updates were applied last night.  I restarted my computer 3 times yesterday and finally shut it down at end of day.  This morning, Docker Desktop is running fine.  The vmmemWSL process that was running in the background at 98% CPU and 1.6GB RAM is gone from Task Manager.  `wsl.exe -l -v` opens at this address: `/mnt/c/Windows/system32` and no output.

**Comment by John-zhan** [comment]
how about this problem now is what condition. my WSL just don't respond anything.

**Comment by MansoorCod** [comment]
I have also same problem from 2 days

**Comment by msanchezr99** [comment]
I am having the same issue. I open an Ubuntu cmd and it does not show anything. It also does not let me close it
