### ISSUE TITLE
How to set bash shell for OpenSSH sessions?

### ISSUE THREAD

**Issue by ylluminate** [Microsoft/WSL#914]
At present, when one `ssh`s into a working OpenSSH session, it loads up `cmd` in `C:\Users\username`.  How can this be changed to initiate `bash` or another shell at this time?

**Comment by aseering** [comment]
Hi @ylluminate -- there are a bunch of tickets elsewhere in this tracker about setting up SSH access.  Feel free to look through the bug tracker; post if you have further questions.

In short -- you will first have to disable Windows's SSH server.  Once you've done that, you can set up WSL for SSH access per the instructions here:
http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10

**Comment by rodrymbo** [comment]
Or put the WSL sshd on a different port, or perhaps on a different IPv6 address (if supported). 

It's one machine with two operating systems, but one shared IPv4 address (usually). Only one port can be open for that IP address at a time. The machine might have thousands of IPv6 addresses available so as long as each sshd is on a different address, you could have each on the same port.

On the other hand, port 22 is attacked by script kiddies. They're more obnoxious than dangerous these days, but it's still considered better to use a different, random port. So a different, random port for each of your sshd servers is a valid option.

**Comment by benhillis** [comment]
It is now possible to run wsl.exe or bash.exe from an SSH connection (Windows ssh server).
