### ISSUE TITLE
want a GUI wsl monitor

### ISSUE THREAD

**Issue by log2dx** [microsoft/WSL#9140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by log2dx** [comment]
does the  same  thing as .wslconfig + wsl.conf

**Comment by benhillis** [comment]
Sorry I don't fully understand the ask - are you asking for a way to configure settings via some UI? If so we have this planned.
