### ISSUE TITLE
Looks like windows executables cannot launch under systemd

### ISSUE THREAD

**Issue by fquinner** [microsoft/WSL#9146]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

wsl --version
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

### Repro Steps

1. Set systemd=true in /etc/wsl.conf
2. Restart WSL
3. Then you'll get:

```
notepad.exe
Cannot open assembly '/mnt/c/WINDOWS/system32/notepad.exe': File does not contain a valid CIL image.
```
If systemd is set to false in wsl.conf, the problem goes away.

### Expected Behavior

Should be able to launch notepad.exe from wsl

### Actual Behavior

Failing to launch notepad.exe

**Comment by fquinner** [comment]
Without systemd:

```
➜  ~ ls /proc/sys/fs/binfmt_misc
WSLInterop  qemu-aarch64  qemu-arm  qemu-mips64  qemu-mips64el  qemu-ppc64le  qemu-riscv64  qemu-s390x  register  status
```

With systemd:
```
➜  ~ ls /proc/sys/fs/binfmt_misc
WSLInterop  cli  jar  llvm-12-runtime.binfmt  python2.7  python3.10  register  status
```

Looks like I do have mono installed too

**Comment by cerebrate** [comment]
Ah, that explains it, then.

When systemd runs, it sets up binfmt_misc with the formats configured by whatever packages you have installed. Ordinarily, this is what you want, but the trouble is that Mono executables are just PE files indistinguishable from any other Windows executable (which, format-wise, they _are_).

So when you enable systemd, it installs the Mono binfmt_misc ("cli"), and then when you try and run Notepad, the kernel notices that it's a Windows PE and passes it to Mono - which then gives you that "Cannot open assembly" error because Notepad isn't a .NET application.

Uninstalling Mono (or disabling its registration of a binfmt_misc entry; you can still run Mono apps by running `mono ./test.exe` manually) should get you interop back. Unfortunately, I don't believe it's possible to have both working at the same time.

**Comment by fquinner** [comment]
That's interesting and helpful thank you - I'll give that a go (deregistering mono). Its interesting the apps that fell into this issue - there were quite a few including docker credential executables.

Thanks for the succinct explanation as well that all makes sense.

**Comment by fquinner** [comment]
Wow:
```
➜  ~ update-binfmts --display
cli (enabled):
     package = mono-runtime
        type = magic
      offset = 0
       magic = MZ
        mask =
 interpreter = /usr/bin/cli
    detector = /usr/lib/cli/binfmt-detector-cli
jar (enabled):
     package = openjdk-8
        type = magic
      offset = 0
       magic = PK\x03\x04
        mask =
 interpreter = /usr/bin/jexec
    detector =
llvm-12-runtime.binfmt (enabled):
     package = llvm-12-runtime
        type = magic
      offset = 0
       magic = BC
        mask =
 interpreter = /usr/bin/lli-12
    detector =
python2.7 (enabled):
     package = python2.7
        type = magic
      offset = 0
       magic = \x03\xf3\x0d\x0a
        mask =
 interpreter = /usr/bin/python2.7
    detector =
python3.10 (enabled):
     package = python3.10
        type = magic
      offset = 0
       magic = \x6f\x0d\x0d\x0a
        mask =
 interpreter = /usr/bin/python3.10
    detector =
```

So what's cli I wonder - I mean it says `mono-runtime`, but surely something as prescriptive as mono doesn't have an executable called cli right?

```
➜  ~ ls -l /usr/bin/cli
lrwxrwxrwx 1 root root 21 Feb 10  2022 /usr/bin/cli -> /etc/alternatives/cli
➜  ~ ls -l /etc/alternatives/cli
lrwxrwxrwx 1 root root 13 Feb 10  2022 /etc/alternatives/cli -> /usr/bin/mono
```

... wrong.

So yeah despite it reading like the stupidest and most self destructive command line in the world, this fixes it for me based on what was installed:

```
sudo update-binfmts --disable cli
```

Thanks!

**Comment by Bobrokus** [comment]
> `sudo update-binfmts --disable cli`

Sorry for necroposting. This worked for me like a charm! But is there a way to make this fix permanent?

**Comment by pmartincic** [comment]
`sudo rm /var/lib/binfmts/cli` worked for me.
