### ISSUE TITLE
Unable to switch distro to run WSL2

### ISSUE THREAD

**Issue by richylyq** [microsoft/WSL#9153]
### Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu

### Repro Steps

1. Install WSL and Ubuntu Distro and change from WSL1 to WSL2
2. Install WSL and change from WSL1 to WSL2 then install Ubuntu Distro

### Expected Behavior

```bash
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```

### Actual Behavior

1. 
```bash
C:\Windows\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The system cannot find the file specified.
```
2. Unable to install Ubuntu Distro 
```bash
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070002
Error: 0x80070002 The system cannot find the file specified.

Press any key to continue...
```

**Comment by richylyq** [comment]
I've attached to log files.
[WslLogs-2022-11-16_09-11-47.zip](https://github.com/microsoft/WSL/files/10017266/WslLogs-2022-11-16_09-11-47.zip)

**Comment by OneBlue** [comment]
Thank you @richylyq.

Looking at the logs, the issue is that WSL2 failed to create its network:

```
572	True	Microsoft.Windows.Lxss.Manager	Error	0	11-15-2022 17:15:24.022	12864	"code: 	
failurecount: 	3
file: 	onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp
function: 	
hr: 	0x80070002
linenumber: 	1419
message: 	""HcnCreateNetwork failed {""""Success"""":false,""""Error"""":""""The system cannot find the file specified. """",""""ErrorCode"""":2147942402}""
threadid: 	12864
type: 	0"	"	"	onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp			7552	2		00000000-0000-0000-0000-000000000000			
```


@keith-horton: I see this logline:

```
514	False	Microsoft.Windows.Hyper.V.NetMgmt	NetMgmt::CreateVirtualSwitch	0	11-15-2022 17:15:24.020	14504	"ErrorID: 	-2147024894
Message: 	CreateVSwitchExtensionMiniport call failed"	"	"				3032	2		00000000-0000-0000-0000-000000000000			
```

Just before the failure. Any hints on what could cause that ?

**Comment by richylyq** [comment]
hey @OneBlue 
Thanks for checking up on the issue! Much appreciated!
I ended up resetting the PC and it resolved the problem. Marking the issue as resolved 🚀

**Comment by keith-horton** [comment]
Sorry, that's an odd error to show up there. I would need to get hyper-v traces to see where it failed.

**Comment by OneBlue** [comment]
@keith-horton the [logs](https://github.com/microsoft/WSL/files/10017266/WslLogs-2022-11-16_09-11-47.zip) should contain the hyper-v traces.

 Let me know if any other trace providers are needed to diagnose issues like this
