### ISSUE TITLE
Microsoft Dev Kit 2023 Windows 11 ARM WSL2 - No Graphics Hardware Acceleration Support 

### ISSUE THREAD

**Issue by mannkeithc** [microsoft/WSL#9154]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04.1 LTS on Windows 10 aarch64

### Other Software

None

### Repro Steps

$ sudo apt install mesa-utils
$ glxinfo -B

### Expected Behavior

mannk@Andromeda:~$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    **Vendor: Microsoft Corporation (0xffffffff)**
    **Device: D3D12 Qualcomm Snapdragon 8cx Gen 3 Adreno GPU (or something similar)**
    Version: 22.0.5
    **Accelerated: Yes**
    Video memory: 15775MB
    **Unified memory: Yes**
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
**OpenGL vendor string: Microsoft Corporation**
**OpenGL renderer string: D3D12 Qualcomm Snapdragon 8cx Gen 3 Adreno GPU (or something similar)**
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

mannk@Andromeda:~$

### Actual Behavior

mannk@Andromeda:~$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    **Vendor: Mesa/X.org (0xffffffff)**
    **Device: llvmpipe (LLVM 13.0.1, 128 bits) (0xffffffff)**
    Version: 22.0.5
    **Accelerated: no**
    Video memory: 15775MB
    **Unified memory: no**
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
**OpenGL vendor string: Mesa/X.org**
**OpenGL renderer string: llvmpipe (LLVM 13.0.1, 128 bits)**
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

mannk@Andromeda:~$

### Diagnostic Logs

On an Intel x64 PC running Windows 11 with a WDDM 3.0 compliant graphics driver WSL2 supports Linux GUI apps and hardware graphics acceleration.

The Microsoft Dev Kit 2023 has a Qualcomm Snapdragon 8cx Gen 3 Adreno GPU with WDDM 3.0 compliant graphics driver, viz. run dxdiag tool, display tab, and checked Drivers field. I installed WSL2 / Ubuntu 22.04 distro on Microsoft Dev Kit 2023 and as expected, Linux GUI apps install and run fine, but unlike on an Intel PC there is no hardware graphics support for the ARM processors GPU, as per glxinfo -B command output above. This limits or impedes the performance of Linux apps that can currently run on the Dev Kit with Snapdragon 8cx Gen 3 SoC under WSL 2. I had hoped this would be available from day 1.

Does the WSL2 kernel require upgrade to version >= 5.20 for Snapdragon Adreno hardware acceleration support to be included or there a bug for the ARM64 WSL2 version? If kernel related issue, what is the projected timescale for releasing an updated WSL2 kernel with Adreno hardware graphics acceleration support?

![Screenshot_20221114_143158](https://user-images.githubusercontent.com/43237916/201969783-8bf24b92-c5bd-4ddb-a2d8-2168389f4e88.png)

**Comment by dominictayloruk** [comment]
Maybe needs Linux kernel 6.0

**Comment by mannkeithc** [comment]
### WSL2 Ubuntu 22.04 on Microsoft Dev Kit 2023 with Qualcomm Snapdragon 8cx Gen3 now supports graphics hardware acceleration!

There was a system firmware update for the Microsoft Dev Kit 2023 yesterday (28 June 2023), and after an Ubuntu 22.04 software update and upgrade, **glxinfo -B** reported GPU hardware accelerated:

**mannk@Andromeda:~$ glxinfo -B**
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (Qualcomm(R) Adreno(TM) 8cx Gen 3) (0xffffffff)
    Version: 22.2.5
    Accelerated: yes
    Video memory: 16082MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.1
    Max compat profile version: 4.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (Qualcomm(R) Adreno(TM) 8cx Gen 3)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.1 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL shading language version string: 4.10
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

mannk@Andromeda:~$

Plus, when I run glxgears, it reports a steady 60 fps which matches my 4K monitor refresh rate whereas previously it was reporting over 300 fps and not sync'd with my monitor.


Other changes include a later version of Linux kernel:
**mannk@Andromeda:~$ uname -a**
Linux Andromeda 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

and **dxdiag** reports a later version of graphics driver:
<img width="544" alt="dxdiag_report" src="https://github.com/microsoft/WSL/assets/43237916/85e7eee5-6ad1-46b6-8ca9-30e4587d5b10">


Interestingly, WSL2 Debian (Bullseye) and Ubuntu 18.04 distros didn't have graphics hardware accelerate support post firmware upgrade, but then neither of these distros had **systemd** support enabled, whereas my Ubuntu 22.04 distro does have **systemd** enabled.
