### ISSUE TITLE
Offers update but then says no update available

### ISSUE THREAD

**Issue by roja45** [microsoft/WSL#9156]
### Version

Microsoft Windows [Version 10.0.22622.598]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Gives me a message that an update it available

Run  wsl.exe --update

### Expected Behavior

Should update to latest version

### Actual Behavior

A new WSL update is available. It can be installed by running: wsl.exe --update
➜  ~ wsl.exe --update
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
➜  ~ wsl.exe --version
WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

**Comment by damnkiwi6120** [comment]
I have similar problem but a bit worse. I did not see the message `A new WSL update is available. It can be installed by running: wsl.exe --update`. I've checked for update in Microsoft Store several times but no luck.

WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25236.1010

**Comment by sabino** [comment]
I was having the same problem.
My guess is this might happen if WSL2 was manually installed in the past, which is my case (but this is just a guess).

This was my version prior to the update:

```
❯  wsl --version
WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25236.1010
```

I've fixed it by opening `cmd` or `powershell` and running:
```
wsl.exe --update --web-download
```

The `--web-download` option can be found when running `wsl --help`:
```
...
    --update
        Update the Windows Subsystem for Linux package.

        Options:
            --web-download
                Download the update from the internet instead of the Microsoft Store.
...
```

After doing that, here is the `wsl --version` output:
```
❯  wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25236.1010
```

**Comment by sarim** [comment]
Having the same issue. Got the message while running ubuntu that wsl update is available. But `wsl --update` says latest version is already installed. 

```
↪  ~ ➤ wsl --version
WSL version: 0.70.5.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
↪  ~ ➤ wsl --update
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

**Comment by sabino** [comment]
@sarim, just follow the step above.
I've updated my comment by adding the `FIX` heading, hopefully making it clearer.
