### ISSUE TITLE
WSL v1.0.0 cannot be installed on Windows 10 Version 19045, whereas supported on the System Requirements on Microsoft Store

### ISSUE THREAD

**Issue by masaharu-kato** [microsoft/WSL#9157]
### Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. Go to "Windows Subsystem for Linux" app page on Microsoft Store: https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R 
(In the "System Requirements" section, Windows 10 version 19041.0 or higher are supported.)
2. Install the app
3. Run installed app

### Expected Behavior

The WSL v1.0.0 can be installed successfully.

### Actual Behavior

When run the installed WSL v1.0.0 app, the following error messages are shown, and cannot be used.
```
Windows version 10.0.19045.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue...
```
![image](https://user-images.githubusercontent.com/38909796/202177743-e06467dc-8669-4ddb-adc9-4a632f6de09c.png)

**Comment by benhillis** [comment]
Please make sure that your machine is fully up to date. The Windows Update required is KB5020030.

**Comment by masaharu-kato** [comment]
KB5020030 solved this issue. Thanks!

**Comment by the-moog** [comment]
Running windows update (optional updates) a couple times + three reboots solved this issue for me. KB5020030 and a few other things installed.

**Comment by yilmazdurmaz** [comment]
Can someone give the name of this "KB5020030" update? I use 21H2, which seemingly has all updates, and this is not in any of the available/installed lists.

The only missing thing is the 22H2 feature upgrade which I defer upgrading. The update seems to just increase patch level 19044.2251 to 19044.2311 whereas 22H2 will upgrade to 19045.xxxx.

So, What am I missing here?

**Comment by yilmazdurmaz** [comment]
I went ahead and downloaded it manually from the [Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5020030)

**Comment by the-moog** [comment]
> Can someone give the name of this "KB5020030" update? I use 21H2, which seemingly has all updates, and this is not in any of the available/installed lists (optional updates enabled).
> 
> The only missing thing is the 22H2 feature upgrade which I defer upgrading. The update seems to just increase patch level 19044.2251 to 19044.2311 whereas 22H2 will upgrade to 19045.xxxx.
> 
> So, What am I missing here?

I think "KB5020030" can only be installed over 22H2.  It took well over half an hour to install on my laptop, a lot longer than 22H2 itself.

**Comment by crramirez** [comment]
I'll add this link here if someone finds this thread. https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/

It explains everything

**Comment by Van-Dame** [comment]
I had 22H2 as well as KB5020030 installed, though my win version stayed at `19045.2251` for some reason. I installed WSL v1.0.0 from the Win Store and it still threw the same error as OP. What fixed it for me was manually installing "Virtual Machine Platform", "Windows Hypervisor Platform", and "Windows Subsystem for Linux" components from Windows Features dialog. HTH

**Comment by yilmazdurmaz** [comment]
@Van-Dame no worries about that version. `19045.2251` is Windows 10 22H2. `19044` is for W10 22H1 and so on.

**Comment by yilmazdurmaz** [comment]
my apologies, I see my error in my reply to @Van-Dame. it should have been updated to `19045.2311`.  Is it still 2251 or updated to 2311 after your manual fix?

**Comment by Van-Dame** [comment]
Still at 2251.

![image](https://user-images.githubusercontent.com/482549/204638499-7150326e-c3b1-474f-8e75-6a7e4d23ea0c.png)

**Comment by Loosewin** [comment]
WSLg is now working after I updated my Windows 10 system, including the KB5020030 update AND installing the Microsoft Store version of wsl (the `wsl --update` command did not work).

```text
cmd.exe> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2311
```

**Note:** The `wsl --update` command was not enough, I had to download WLS from the Microsoft Store.

**Comment by binael** [comment]
Please go to this website for a concise steps to get it done
[](https://medium.com/@nbinael/concise-steps-to-set-up-systemd-on-windows-subsystem-for-linux-wsl-233a6c32a1364)

This is a summary of the steps highlighted here

**Comment by TETYYS** [comment]
KB5020030 has been replaced by KB5021233.

**Comment by realsanjeev** [comment]
I have just finished updating window 10 to` 22H2.`. My current window version is: `Version 10.0.19042.631` Should I update `KB5021233` from Microsoft catalog manually. Or there is  any command in command line to check update automatically and update it

**Comment by crramirez** [comment]
@realsanjeev check again. Windows 10 22h2 is 1904**5** after that just issue `wsl --update`

**Comment by yilmazdurmaz** [comment]
@realsanjeev  19042 is for 20H2, meaning your system did not properly upgrade to 22H2, which is19045.
