### ISSUE TITLE
Windows Store wsl executables unsigned

### ISSUE THREAD

**Issue by AAANEUN** [microsoft/WSL#9159]
### Version

WSL version: 1.0.0.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2-microsoft-standard-WSL2

### Repro Steps

Run Sysinternals Sigcheck on `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe\wslservice.exe`, `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe\wslhost.exe`, `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe\wslg.exe`, and `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe\wsl.exe`.

### Expected Behavior

Sigcheck to report that the executables are signed.

### Actual Behavior

Sigcheck reports that the executables are unsigned.
![image](https://user-images.githubusercontent.com/56973230/202267049-e405fb8b-8082-41e5-9e0b-f63650f7c9c6.png)
![image](https://user-images.githubusercontent.com/56973230/202267254-62246379-9813-47f5-ab86-692267d3ccc2.png)

**Comment by Biswa96** [comment]
Do those really need to be signed? The AppxManifest.xml has PackageIntegrity enabled https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-packageintegrity

**Comment by benhillis** [comment]
Yeah that's my thinking, our package is signed, and we have package integrity enabled.

**Comment by benhillis** [comment]
I'm not sure what best practices are for other apps, if most also sign the packaged binaries we could also do that...

**Comment by AAANEUN** [comment]
> Do those really need to be signed? The AppxManifest.xml has PackageIntegrity enabled https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap10-packageintegrity

I was not aware of this, thanks for the link!

**Comment by AAANEUN** [comment]
The only other consideration i can think of is that in Sysinternals Autoruns, it highlights the wslservice executable red, due to it being unsigned, which might be undesired. Its not a large issue though.
![image](https://user-images.githubusercontent.com/56973230/202276497-2d5763a3-d712-444e-aedf-58e89804ad1d.png)

**Comment by AAANEUN** [comment]
What I have typically seen is that third party apps, such as Mozilla Firefox are traditionally signed as well as using package integrity, whereas Microsoft apps are not, such as windows terminal. I no longer believe that this is an issue, as previously I was not aware of package integrity as an option.
