### ISSUE TITLE
Can't open display: :0 after installing a desktop-environment (xfce)

### ISSUE THREAD

**Issue by haritha99ch** [microsoft/WSL#9161]
### Version

Microsoft Windows [Version 10.0.22623.891]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

kali-linux

### Other Software

X11-Aps

### Repro Steps

1. Enable systemd on the distro.
2. Restart distro.
3. Install x11-app.
4. Restart distro.
5. Run an x11-app.
6. Install kali-win-kex
7. Run an x11-app.
8. Restart distro.
9. Run an x11-app.

### Expected Behavior

x11-apps should be opening foreach attempt mentioned in **Repro Steps** (step: 3, 5, 7, 9).
`xeyes`

### Actual Behavior

Outputs an error `Can't open display: :0` at **Repro Step 9**

**Comment by haritha99ch** [comment]
The same bug was reproduced on **Ubuntu Preview** after installing `task-xfce-desktop`.

**Comment by haritha99ch** [comment]
Similar issue #8899

**Comment by c4artisan** [comment]
my issue was possibly resolved (it's been going great) in 1.0.1 so yeah there's that
hope your's is resolved tho
