### ISSUE TITLE
packaged WSL 1.0 version from Windows Store cant run 

### ISSUE THREAD

**Issue by wildtrigger** [microsoft/WSL#9162]
### Version

10.0.19044.2130

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.102.1

### Other Software

Windows 10 - 21H2 Build 19044.2130

### Repro Steps

I already had wsl installed. Using WSL 2. Previous version was installed by powershell. 

After i heard that WSL was released as WSL 1.0 in Windows store i tried to upgrade. I clicked Download/install button.

### Expected Behavior

Wsl should run without errror message for windows version

### Actual Behavior

After the download a windowed opened with error message that my windows 10 version is not supported. But in Windows version is the requirement is Windows 10- Version 19041.0 or higher

> Die verpackte Version von Windows-Subsystem für Linux wird von windows-version 10.0.19044.2130 nicht unterstützt.
Weitere Informationen finden Sie unter https://aka.ms/wslinstall
Drücken Sie eine beliebige Taste, um den Vorgang fortzusetzen...

I also tried to update by powershell with wsl ---shutdown
and wsl --update but no changes.

**Comment by Biswa96** [comment]
Please make sure that your machine is fully up to date. The Windows Update required is KB5020030.

**Comment by wildtrigger** [comment]
@Biswa96  thanks for your hint.  
Before i tried the upgrade for wsl , i updated my windows with the cumulative update today. I could not determine the version.
So i look in version history . 
![2022-11-17 09_45_35-Installierte Updates](https://user-images.githubusercontent.com/118429642/202400560-ab82bd01-4fbf-49ae-b73e-cadef642ff12.png)
The mentioned KB5020030 was not within the installed packages. So i manually installed it by the update catalog.

https://www.catalog.update.microsoft.com/Search.aspx?q=KB5020030

After that i restarted the computer and i was able to run the wsl version from Windows Store.
Now i have only a minor permission error from my ubuntu distribution. But this shuold be my problem :-)


> Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.74.2-microsoft-standard-WSL2 x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
/etc/update-motd.d/50-landscape-sysinfo: 17: cannot create /var/lib/landscape/landscape-sysinfo.cache: Permission denied
112 updates can be applied immediately.
65 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable
The list of available updates is more than a week old.
To check for new updates run: sudo apt update

**Comment by mbuchner** [comment]
@Biswa96
> Please make sure that your machine is fully up to date. The Windows Update required is KB5020030.
+1
