### ISSUE TITLE
(With Docker Desktop) "Failed to translate" errors in CreateProcessParseCommon and UtilTranslatePathList

### ISSUE THREAD

**Issue by mrjcleaver** [microsoft/WSL#9167]
### Version

Microsoft Windows [Version 10.0.22000.1219]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Release:        20.04

### Repro Steps

Start ubuntu from PS

### Expected Behavior

No error message

### Actual Behavior

An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

dmesg says
[ 9287.247218] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Windows

[ 9287.247276] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Windows\System32\Wbem

[ 9287.247333] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\

[ 9287.247389] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Windows\System32\OpenSSH\

[ 9287.247446] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Program Files\Amazon\AWSCLIV2\

[ 9287.247502] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Program Files\Docker\Docker\resources\bin

[ 9287.247558] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\ProgramData\chocolatey\bin

[ 9287.247614] init: (1622) ERROR: UtilTranslatePathList:2688: Failed to translate C:\Program Files\Git\cmd

etc

### Diagnostic Logs

[WslLogs-2022-11-17_14-55-58.zip](https://github.com/microsoft/WSL/files/10035169/WslLogs-2022-11-17_14-55-58.zip)

**Comment by funder7** [comment]
![image](https://user-images.githubusercontent.com/12503478/203224451-d0646bc4-5c2c-4bb4-a239-a4e142532b30.png)
Same issue here

**Comment by flipkickmedia** [comment]
this issue was closed in #8723 - can we either combine this or reopen #8723 as this issue is not resolved.
