### ISSUE TITLE
Sneaking WSL's emulated features into a future real-world Windows filesystem?

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#917]
So I read this repo pretty much every day, and I read the blogposts when available, and I was wondering, wouldn't it be a lot easier if the filesystem itself supported things like inodes and Linux-style owner and permission, and all of the other things that lxcore has to emulate in VolFS and all of the hard work by the team going into getting DriveFS working in a sane way for interop?

Since ReFS has not yet been widely adopted and is not even usable for booting Windows, it seems maybe natural that ReFS could add some of the stuff that is currently emulated into a future driver revision. 

Is this a stupid idea, or could something like this give better performance?

**Comment by therealkenc** [comment]
If you want interop, basically the Linux side needs to adopt [ACLs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/System_Administration_Guide/ch-acls.html) in userspace as first class citizens. It's not likely Windows is going to embrace Kernihan&Pike's 1972 security model. [PAM](http://manpages.ubuntu.com/manpages/wily/man7/pam.7.html) on the WSL side could bridge to Windows Authentication. When glibc is looking at /etc/passwd for stuff, it's looking in the wrong place. 

I think this would require a degree of cooperation witth the Linux people (which is hard to define; it isn't Canonical) that is probably not achievable. @Admin responds in this [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13292958-rethink-your-strategy-on-how-the-linux-bash-integr) well.

None of this is new of course. The Samba people have been covering [this stuff](https://wiki.samba.org/index.php/Shares_with_Windows_ACLs) for going on 15+ years now. I think real progress can be made however. It would be nice if someone above Ben's pay grade on the Windows side could work out some kind of "can't we all get along" on symlinks for example.

**Comment by fpqc** [comment]
@therealkenc Yeah, I know about ACLs, and I read a chapter of a book called Open Sources 2.0 by one of the Samba devs where he talks about the whole ACL security model and how the one they put into Samba is still not exactly compatible with the Windows one (he describes it as extremely complicated and underused in practice while also loved by computer scientists who can do all kinds of proofs of how secure it is in theory).  

I was just wondering if this hypothetical ReFS driver could have the linux-style file information automatically generated at the driver level for non-WSL stuff, maybe, and have things like inodes supported even if they aren't used in win32.  

That way maybe it wouldn't need to be emulate quite as much stuff.
