### ISSUE TITLE
Unable to start WSL2

### ISSUE THREAD

**Issue by 7-zete-7** [microsoft/WSL#9171]
### Version

Microsoft Windows [Version 10.0.22000.1281]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.74.2-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 2 19:50:29 UTC 2022

### Distro Version

WLinux

### Other Software

Docker Desktop (Windows), version 4.14.1

### Repro Steps

Just run distro or start it by `wsl.exe -d WLinux` command.

### Expected Behavior

Prompt on started distro.

### Actual Behavior

Errors
```
<3>WSL (211) ERROR: CreateProcessEntryCommon:559: chdir(/home/zete7) failed 5
<3>WSL (211) ERROR: CreateProcessEntryCommon:570: execvpe /usr/bin/zsh failed 5
<3>WSL (211) ERROR: CreateProcessEntryCommon:579: Create process not expected to return
```

and process ending with code `1`

### Diagnostic Logs

[WslLogs-2022-11-18_12-41-04.zip](https://github.com/microsoft/WSL/files/10040204/WslLogs-2022-11-18_12-41-04.zip)

**Comment by 7-zete-7** [comment]
By command
```
wsl.exe -d WLinux -u root -e sh
```

I can access to distro. But next command on distro
```
cat /proc/version
```

I give this message
```
sh: 1: cat: Input/output error
```

**Comment by Biswa96** [comment]
The issue seems to be WLinux specific and not related to WSL itself. The home directory and default shell are not set properly at the time of installation/creation of the distribution.

**Comment by PorcoRosso85** [comment]
I'm encounting same issue.

## wsl version
wsl2

## distro version
Ubuntu 22.04

## error message 
when run distro
```
<3>WSL (9) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 2
<3>WSL (9) ERROR: CreateProcessEntryCommon:579: Create process not expected to return
```

**Comment by aasitvora99** [comment]
This happened with me too when i tried to reinstall my ubuntu distro. Any suggestions on how to fix this?

**Comment by Biswa96** [comment]
How did you reinstall it?
