### ISSUE TITLE
Installing wsl on windows

### ISSUE THREAD

**Issue by Ose-Augustine** [microsoft/WSL#9174]
### Version

Microsoft Windows [Version 10.0.19042.1526]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Repro Steps

open cmd 
type in wsl --install

### Expected Behavior

I expected wsl --install to install wsl on my system 

### Actual Behavior

`A system shutdown in progress`. I keep getting this,both in powershell and cmd
And when in run wsl --version, it showsa list of instructions, rather than the wsl version installed. 
This mean the wsl --install is going through.

**Comment by benhillis** [comment]
/logs

Have you tried restarting your machine?

**Comment by Ose-Augustine** [comment]
> 
[WslLogs-2022-11-19_10-11-15.zip](https://github.com/microsoft/WSL/files/10046565/WslLogs-2022-11-19_10-11-15.zip)

**Comment by Ose-Augustine** [comment]
> /logs
> 
> Have you tried restarting your machine?

Yes i have. 
I have also run `sfc/scannow` and `dism /online /cleanup-image /restorehealth` still nothing
