### ISSUE TITLE
Git commands return error (UtilConnectUnix:510).

### ISSUE THREAD

**Issue by AbdelrhmanSaid** [microsoft/WSL#9180]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Debian 11

### Other Software

Git 2.30.2
Visual Studio Code Terminal

### Repro Steps

Open Visual Studio Code from command line
Try to push current changes 👇

```
git push origin master // <-- error occurs
```

### Expected Behavior

Push without errors.

### Actual Behavior

```
abdelrhman@Abdelrhman:~/projects/buy-or-bye$ git push origin reports
<3>WSL (1493) ERROR: UtilConnectUnix:510: connect failed 2
<3>WSL (1520) ERROR: UtilConnectUnix:510: connect failed 2
Everything up-to-date
```

**Comment by AhmedGhassani** [comment]
any solution to this, getting the same error when running `docker compose up`
```
<3>WSL (8307) ERROR: UtilConnectUnix:510: connect failed 2
```

Using:
WSL2
Ubuntu 20.04
Kernal: 5.15.74.2-microsoft-standard-WSL2
Docker: Docker version 20.10.21, build baeda1f
Docker Compose: Docker Compose version v2.12.2

Adding `sudo` to the start of my command fixes this but I don't think I should need sudo to run docker compose up

**Comment by fredmo** [comment]
From the WSL2 bash shell, I have the same issue , by trying to launch a windows exe from bash : 

sudo update-binfmts --disable cli

and :

/mnt/c/Users/my_name/wsl-notify-send.exe "test1"
<3>WSL (5828) ERROR: UtilConnectUnix:510: connect failed

**Comment by giuvincenzi** [comment]
I don't know if it helps but that is how I fixed it.

I had set up WSL git authentication via Git Credential Manager
```
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe"
```
it worked but then one day I got this error.

I solved by restarting WSL
```
$ wsl --shutdown
$ wsl
```
