### ISSUE TITLE
shutdown error

### ISSUE THREAD

**Issue by sucicf1** [microsoft/WSL#9181]
### Version

Microsoft Windows [Version 10.0.22621.819] WSL version: 1.0.0.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Debian 11.5, ubuntu preview 22.10

### Repro Steps

execute inside wsl distro the command:
sudo shutdown now

### Expected Behavior

the wsl distro and all of it services are shutdown without errors

### Actual Behavior

after executing the command sometimes the apache2 doesn't get terminated and always getting the error inside windows terminal [process exited with code 1 (0x00000001)]. If we don't use windows terminal than it sometimes doesn't display error

**Comment by OneBlue** [comment]
Thanks for reporting this @sucicf1.

The best way to do this is via `wsl.exe --terminate <distro-name>` to terminate the distribution, or `wsl.exe --shutdown` to stop all distributions.
