### ISSUE TITLE
WSL Clock still not updating correctly - frequently out of sync

### ISSUE THREAD

**Issue by kvietmeier** [microsoft/WSL#9183]
### Version

10.0.22623.891

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Ubuntu-20.04

### Repro Steps

Install WSL2 and apply all the latest updates.

```
KV C:\Users\ksvietme\repos\Terraform\azure\testing\aks\aks-2> systeminfo | Select-String "^OS Name","^OS Version"
InputStream:3:OS Name:                   Microsoft Windows 11 Enterprise
InputStream:4:OS Version:                10.0.22623 N/A Build 22623

KV C:\Users\ksvietme\repos\Terraform\azure\testing\aks\aks-2> wsl -v
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.891

KV C:\Users\ksvietme\repos\Terraform\azure\testing\aks\aks-2> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2
  Ubuntu-20.04           Running         2
  docker-desktop         Stopped         2
```

### Expected Behavior

WSL distro clock stays in sync with OS.

### Actual Behavior

Clock is frequently off by at least an hour, often whole day after a sleep/hibernation.

Last time I tried "hwclock -s" in the distro it was always an hour off but it is PST so correct TZ.

This will always work 
wsl.exe -d Ubuntu-20.04 -u root -- ntpdate time.windows.com

**Comment by dan-drew** [comment]
FYI this started recently for me about when MS Store says it applied the latest update (11/18)

```
> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

**Comment by ternst-micado** [comment]
FYI if you haven't seen it yet but look at issue 8204 since more people (including myself) are experiencing this issue - see latest comments in that ticket, the issue came back a few months ago after it got fixed at some point.
