### ISSUE TITLE
Consider updating current WSL release number from 1.0.0.0 to 3.0.0.0.

### ISSUE THREAD

**Issue by NotTheDr01ds** [microsoft/WSL#9184]
***Is your feature request related to a problem? Please describe.***

I'm getting better at it (I think), but it's still difficult for me to try to explain to a user that they need WSL 1.0.0 (the application package) for a particular feature (e.g. WSLg or `--mount`).  The natural response is, "But I thought I was on WSL2?", and/or, How is 1.0.0 different from WSL 1?"

Because I've followed along closely, I understand it myself, but I can imagine the confusion for more casual users.

***Describe the solution you'd like***

It might be easier to just go ahead and re-release 1.0.0.0 as 3.0.0.0 and then increment build numbers going forward from there.  This would make a clear break between the inbox versions and the application package/Store version.

I'm not totally sold on this myself, and I fully admit it may (or may not) be a hair-brained idea, but I'm just looking for an easier "delineation" for explaining where particular WSL features are available.

***Describe alternatives you've considered***

"WSL In-box" vs. "WSL Store App"?
"WSL that was a Windows feature" vs. "WSL that was installed from the Store"?
"WSL Feature" vs. "WSL Application Package?

Again - These terms probably make perfect sense to the WSL team, but none of those make much sense to unfamiliar users without *much* more explanation behind them.

**Comment by elsaco** [comment]
This is like the NVIDIA 12GB RTX 4080 GPU confusion 🙂
