### ISSUE TITLE
Unable to access CUDA on WSL2 via SSH

### ISSUE THREAD

**Issue by tvwenger** [microsoft/WSL#9185]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Ubuntu-22.04

### Other Software

```
C:\Users\twenger>nvidia-smi
Mon Nov 21 13:29:49 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  Off |
| 75%   62C    P2   301W / 450W |   8164MiB / 24564MiB |     97%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

### Repro Steps

CUDA is working properly. From Windows command prompt or within WSL, `nvidia-smi` outputs the expected information (see above).  When I connect to the machine via SSH, however, the command `nvidia-smi` is not found. This is because the non-local login does not add the required WSL directories to the PATH.

```
$ echo $PATH
# ... includes, for example, /usr/lib/wsl/lib
$ ssh localhost
$ echo $PATH
# ... does not include, for example, /usr/lib/wsl/lib
```

I can now add the WSL libraries to the path and run `nvidia-smi`, but the CUDA driver is not detected.
```
$ export PATH=/usr/lib/wsl/lib:$PATH
$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Failed to properly shut down NVML: Driver Not Loaded
```

### Expected Behavior

The CUDA driver should be loaded on SSH connection.

### Actual Behavior

The CUDA driver is not loaded on SSH login.

**Comment by tvwenger** [comment]
I suspect that starting WSL locally loads some libraries and whatnot that enables the CUDA driver, and these actions are not taking place when connecting remotely. I just want to know what I have to do so that a remote connection via SSH sets up the environment to mimic a local WSL connection.

**Comment by OneBlue** [comment]
This is probably by caused by the right driver not being loaded. 

@iourit is there a way to check if the right drivers are available for nvidia-smi to work ?

**Comment by iourit** [comment]
> This is probably by caused by the right driver not being loaded.
> 
> @iourit is there a way to check if the right drivers are available for nvidia-smi to work ?

nvidia-smi in /usr/lib/wsl/lib is updated when the driver on the host is installed, so it is always up to date.
There is an issue when nvidia-smi doesn't work when one instance is launched as Administrator and another as a non-Administrator. Try to shutdown WSL and start the first nvidia-smi instance via SSH.

**Comment by tvwenger** [comment]
@iourit 

> There is an issue when nvidia-smi doesn't work when one instance is launched as Administrator and another as a non-Administrator.

I am not experiencing this. All of my sessions are launched as non-administrator.

> Try to shutdown WSL and start the first nvidia-smi instance via SSH.

I have the openssh server running within WSL. If I shutdown WSL, then I won't be able to reach WSL via SSH because the SSH server won't be running.

**Comment by iourit** [comment]
> @iourit
> 
> > There is an issue when nvidia-smi doesn't work when one instance is launched as Administrator and another as a non-Administrator.
> 
> I am not experiencing this. All of my sessions are launched as non-administrator.
> 
> > Try to shutdown WSL and start the first nvidia-smi instance via SSH.
> 
> I have the openssh server running within WSL. If I shutdown WSL, then I won't be able to reach WSL via SSH because the SSH server won't be running.

I meant to say "restart WSL, start the SSH server and start the first nvidia-smi instance via SSH".

**Comment by koltenfluckiger** [comment]
You should just re-try restarting WSL. `wsl --shutdown; wsl -e sudo nvidia-smi `

**Comment by tvwenger** [comment]
@iourit 

Thanks for the clarification and help!

> I meant to say "restart WSL, start the SSH server and start the first nvidia-smi instance via SSH".

I can confirm that this works. To summarize the problem:

1. Start WSL.
2. Run `nvidia-smi`. The CUDA driver is found and all is well.
3. `ssh localhost`
4. Run `nvidia-smi`: command not found.
5. `export PATH=/usr/lib/wsl/lib:$PATH`
6. Run `nvidia-smi`. The CUDA driver is not found.

And the workaround:

1. Shutdown WSL.
2. Start WSL, but *do not* execute `nvidia-smi`
3. `ssh localhost`
4. `export PATH=/usr/lib/wsl/lib:$PATH`
5. Run `nvidia-smi`. The CUDA driver is found and all is well.

Interestingly, now the CUDA driver is loaded fine both locally and in subsequent SSH connections. This is the default behavior that I expected.

Although this is a workaround, this is not a practical long-term solution. A workflow might start locally and then migrate remotely. It is not practical to have to (1) shutdown the WSL server, (2) restart it, (3) login via SSH, (4) execute `nvidia-smi`, and (5) logout in order to ensure that the CUDA drivers are loaded for both local and remote logins.

**Comment by tvwenger** [comment]
Aha, problem solved. Thanks for the following comment @iourit 

> There is an issue when nvidia-smi doesn't work when one instance is launched as Administrator and another as a non-Administrator.

This actually ended up being my problem after all. WSL is started at log-on via a Task Scheduler script with "Run with highest privileges". Unchecking that box and restarting fixed my problem. Now the drivers are loaded both locally and on remote connections via SSH. Thanks for the hint!

**Comment by iourit** [comment]
> Aha, problem solved. Thanks for the following comment @iourit
> 
> > There is an issue when nvidia-smi doesn't work when one instance is launched as Administrator and another as a non-Administrator.
> 
> This actually ended up being my problem after all. WSL is started at log-on via a Task Scheduler script with "Run with highest privileges". Unchecking that box and restarting fixed my problem. Now the drivers are loaded both locally and on remote connections via SSH. Thanks for the hint!

I am glad it worked. NVIDIA is aware of this issue, but it is not clear at this point if this is the app issue or the OS issue.

**Comment by leeyuky9802** [comment]
This is probably because they load a bunch of extra paths when calling wsl from powershell. Idk i just add manually...
