### ISSUE TITLE
Getting "E233: Cannot open display" after 1.0.0 update

### ISSUE THREAD

**Issue by gosukiwi** [microsoft/WSL#9188]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Run `gvim`

### Expected Behavior

It should open a gvim window in my Windows installation

### Actual Behavior

It throws `E233: Cannot open display` error

This happened since updating to WSL v1.0.0

**Comment by benhillis** [comment]
Should be fixed with 1.0.1

**Comment by OneBlue** [comment]
more details on #9158.

/dupe #9158
