### ISSUE TITLE
Audio is broken under systemd on Ubuntu 22.04

### ISSUE THREAD

**Issue by c4artisan** [microsoft/WSL#9192]
### Version

Microsoft Windows [Versión 10.0.22623.891]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04 (Jammy Jellyfish/jammy)

### Other Software

ALL applications with audio

### Repro Steps

enable systemd on an ubuntu 22.04 installation (made prior to at least 0.68.2)
run an application that uses audio functionality
play a file or a video

### Expected Behavior

the audio plays just fine

### Actual Behavior

the app is silent (with the addition of gnome videos freezing for a second then continuing to play the video)

### Diagnostic Logs

[WslLogs-2022-11-22_22-35-49.zip](https://github.com/microsoft/WSL/files/10073222/WslLogs-2022-11-22_22-35-49.zip)

**Comment by c4artisan** [comment]
this is not a priority like the display thing but i'd like to see it fixed so please reply soon

**Comment by c4artisan** [comment]
7 days with no replies

**Comment by wpwoodjr** [comment]
I was having this issue too with an early version of Ubuntu 22.04.  I just re-installed it using the latest version and now Youtube audio works in Chrome, even when systemd is configured.
```
> wsl --install ubuntu
```

**Comment by wpwoodjr** [comment]
Also you have to install `libpulse0`.  Try that first before re-installing Ubuntu.

**Comment by c4artisan** [comment]
already installed
however i'm not going to reinstall ubuntu since manually reinstalling all of my packages and stuff would be a pain in the ahh

**Comment by wpwoodjr** [comment]
Try installing a new Ubuntu and test Chrome, just to verify its fixed.

**Comment by c4artisan** [comment]
issue is back on a new install

**Comment by linhns** [comment]
> Also you have to install `libpulse0`. Try that first before re-installing Ubuntu.

Thanks a lot. It fixed all my audio related issues on Ubuntu 22.04

**Comment by c4artisan** [comment]
chrome has audio now but the totem video player yet still does not play any sound

**Comment by cogwheel** [comment]
Same experience here. Audio works fine on a fresh install. After enabling systemd, which is necessary for using `snap`, there is no longer any audio. Installing `libpulse0` didn't fix it for me.

**Comment by james28909** [comment]
> Also you have to install `libpulse0`. Try that first before re-installing Ubuntu.

thanks. that fixed it for me. you would think libpulse0 would be shipped with new versions of wsl. but anyway, thanks again!
