### ISSUE TITLE
Network usage in task manager is wrong.

### ISSUE THREAD

**Issue by zozonteq** [microsoft/WSL#9195]
### Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

TaskManager

### Repro Steps

1. Download any file.
2. Open Task Manager and go to "Processes".Sorts the network usage on the tab in ascending order.

### Expected Behavior

WSL traffic should be displayed as Vmmem.

### Actual Behavior

The amount of communication in WSL is displayed as other processes.
### ScreenShot
![image](https://user-images.githubusercontent.com/77091655/203546765-b191a730-5006-4f7c-96af-734ba285fc3b.png)

**Comment by majaha** [comment]
This is still happening on Windows 10 22H2.

**Comment by stofancy** [comment]
This is still happening on Windows 11 24H2.
