### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80040323

### ISSUE THREAD

**Issue by DevPlus31** [microsoft/WSL#9196]
### Version

Microsoft Windows [Version 10.0.19045.2311]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu  22.04

### Repro Steps

Installation 

### Expected Behavior

Installation success.

### Actual Behavior

I had WSL working great, I installed the Windows Store version. then it wouldn't work 
I've remove it completely from my system and re-install it from scratch now I cannot install any distro.

output:
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80040323
Error: 0x80040323 (null)
Press any key to continue...

**Comment by DevPlus31** [comment]
[WslLogs-2022-11-23_17-44-45.zip](https://github.com/microsoft/WSL/files/10077541/WslLogs-2022-11-23_17-44-45.zip)

Here is the result.

**Comment by benhillis** [comment]
@DevPlus31 - I don't see any WSL events in that trace. Did you start the trace, try to register the distro, then stop the trace?

**Comment by DevPlus31** [comment]
I did a new tracing, sorry the other one is wrong.
[WslLogs-2022-11-23_18-23-23.zip](https://github.com/microsoft/WSL/files/10077824/WslLogs-2022-11-23_18-23-23.zip)

my wslconfig file content:
`[wsl2]
nestedVirtualization=true
kernel=C:\\Users\\Mustapha\\bzImage
`

**Comment by benhillis** [comment]
Thanks - it looks like your machine does not support nested virtualization. Try removing that line and it should work.

**Comment by DevPlus31** [comment]
Yes, I just set nestedVirtualization to false and it worked. 
Any tool or command to confirm Nested virtualization is not supported, I am a system with a Core i7 6700K.

**Comment by benhillis** [comment]
Nested virtualization is not enabled on Windows 10.

**Comment by DevPlus31** [comment]
Okay, thank you.

**Comment by benhillis** [comment]
No problem. I'll update the code to remove this error path and allow the VM to boot.
