### ISSUE TITLE
Starting WSL results in error "The file cannot be accessed by the system."

### ISSUE THREAD

**Issue by taikodragon** [microsoft/WSL#9197]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Debian

### Other Software

Docker Desktop (Windows), version 4.12.0
Visual Studio Code 1.73.1 (system setup) with Remote-WSL Extension 0.72.0

### Repro Steps

Open powershell.
Run wsl.exe
Returned response is 
```The file cannot be accessed by the system.```

### Expected Behavior

It should start the distro.

### Actual Behavior

Returned response is 
```The file cannot be accessed by the system.```

### Diagnostic Logs

https://1drv.ms/u/s!ArYWk3X9lH3jicFEE6GNcS0tDY6Dtg?e=6VEqXD

**Comment by arothenhaeuser** [comment]
I am experiencing the same issue. No matter which WSL command I run right after installing Ubuntu with wsl --install -d ubuntu, I get the same error.
Distro: Ubuntu 22.04
Host: Windows 11 Enterprise (21H2 22000.1281)
Powershell: 5.1.22000.832

I'm running the WSL commands from a ScheduledJob (powershell) after waiting for the initial user creation prompt, but having closed it without creating a user.

**Comment by StephaneKazmierczak** [comment]
I am having the same error message since this morning, except it is only happening while using a remote ssh connection, if I start the command locally then they work, if I connect to windows open ssh then type wsl then I get the error

**Comment by AidanStrong** [comment]
> I am having the same error message since this morning, except it is only happening while using a remote ssh connection, if I start the command locally then they work, if I connect to windows using OpenSSH then type wsl then I get the error I am on insider build 25201.1000

@StephaneKazmierczak did you ever fix this issue?

**Comment by MathanGeurtsen** [comment]
I have had this happen twice, last time I did the dism command and a couple of restarts and it eventually worked again, and now I have the same problem again. So I think that is not a permanent solution. And I think this issue should be reopened, there seem to be multiple people with an issue here.

**Comment by pavelgood** [comment]
I have the same issue. WSL works fine when executing from the usual graphical session but ends up with `The file cannot be accessed by the system` when using remote ssh session. The problem appeared approximately a month ago. Have no clue what could be the reason. No updates where applied or any configuration changes made. `dism` tool doesn't help in my case. Windows version: 10.0.19045.2486

**Comment by simmel** [comment]
For solution see #7900

**Comment by pavelgood** [comment]
Thanks @simmel . Removing `Windows Subsystem for Linux Preview` works to me.

**Comment by StephaneKazmierczak** [comment]
> > I am having the same error message since this morning, except it is only happening while using a remote ssh connection, if I start the command locally then they work, if I connect to windows using OpenSSH then type wsl then I get the error I am on insider build 25201.1000
> 
> @StephaneKazmierczak did you ever fix this issue?

I keep a wsl shell running on remote machine at all times. Also I was having more issues with 1.1.0 so downgraded to 1.0.3

**Comment by AidanStrong** [comment]
@marklechtermann 

Our case seems to be almost exactly the same as yours. We want to install a custom WSL image using a build agent. We noticed this issue with remote commands in Jan 2023 and found that no command with WSL at the front would work. 

We use packer and powershell scripts to provision a windows sysprep image with WSL baked in. I do not know exactly what fixed the problem but we now do the following and it works fine:

1) wsl --install 
2) RESTART
3) Download the appx package directly from https://aka.ms/wslubuntu2004
4) unpack the AMD64 package to get exe file. 
5) Start-Process "Installer\ubuntu.exe" -Verb runAs -ArgumentList 'install --root /qn /quiet /log C:\logs\wslubuntu.txt' -wait
6) After installation, we customise our WSL build. 
7) We then export to a tar and unregister before reimporting to a central location (you may not have to do this)
8) RESTART
9) Slightly unrelated but we then had to remove the appx package with the following code otherwise sysprep would not work:

```
$wslAppxToDelete = Get-AppxPackage -AllUser | where-object {$_.name -match "MicrosoftCorporationII.WindowsSubsystemForLinux"}
Remove-AppxPackage -Package $wslAppxToDelete.PackageFullName -AllUsers
```

I hope this helps.

**Comment by luceat-lux-vestra** [comment]
I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`.
I can't access that setting page after resetting. but I remember what I did.

Windows logo key -> type `linux` -> 'Windows Subsystem for Linux` appears
-> you can see `App Settings` in the right pane, hit that menu.

When Settings windows open, you can see the `Reset` button.
after the reset, **It works like a charm!**

**Comment by appleternity** [comment]
Just want to report that this solves my problem as well!!

> I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> 
> Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> 
> When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

**Comment by jmihalich** [comment]
> Just want to report that this solves my problem as well!!
> 
> > I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> > Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> > When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

This worked for me too.  seriously, wtf???

**Comment by cimmyx** [comment]
> > Just want to report that this solves my problem as well!!
> > > I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> > > Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings`in the right pane, hit that menu. When Settings windows open, you can see the`Reset` button. after the reset, **It works like a charm!**
> 
> This worked for me too. seriously, wtf???

Tried it, did not work.

**Comment by brnpimentel** [comment]
> Just want to report that this solves my problem as well!!
> 
> > I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> > Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> > When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

didn't  work.

**Comment by AshishPandagre** [comment]
> I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> 
> Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> 
> When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

Thanks a lot ❤

**Comment by stevenh** [comment]
`Add or remove programs` -> search for `linux` -> Advanced options` -> `Repair` fixed it for me.

**Comment by ktunprasert** [comment]
`Reset` worked for me and didn't wipe the data, don't worry if you're afraid of losing data after doing a system restore and bricking WSL like me

**Comment by zwancho** [comment]
> I was able to resolve my issue with a `dism /Online /Cleanup-Image /RestoreHealth` and a restart.

It works for me after a blue screen and System Restore

can also see https://superuser.com/a/1758189/1821863

**Comment by dexter69** [comment]
Removing Windows worked for me...

**Comment by ayushxx7** [comment]
> `Add or remove programs` -> search for `linux` -> `Advanced options` -> `Repair` fixed it for me.

worked for me as well. Somehow my Windows got bricked during a restart. Then I had no other choice but to "restore" to a previous version and then following the above steps worked for me.

**Comment by energister** [comment]
Got this message on Windows 11. Nothing helped, even reactivation through the "Turn Windows features on or off" -> "Windows Subsystem for Linux" from the Control Panel.

The only thing that has helped is to delete "Windows Subsystem for Linux" by the Settings (Add or remove programs -> search for "linux")

**Comment by Van-Dame** [comment]
> I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> 
> Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> 
> When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

Worked for me flawlessly!

**Comment by heniGR** [comment]
https://www.youtube.com/watch?v=T9r5d_YoIbc
DISM.exe /Online /Cleanup-image /Scanhealth 
DISM.exe /Online /Cleanup-image /Restorehealth
this worked for me!

**Comment by cimmyx** [comment]
> https://www.youtube.com/watch?v=T9r5d_YoIbc DISM.exe /Online /Cleanup-image /Scanhealth DISM.exe /Online /Cleanup-image /Restorehealth this worked for me!

Another "fix" that doesn't fix anything....  

milo> ssh -Y cimmy@iris.local

Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

cimmy@IRIS C:\Users\cimmy>wsl
The file cannot be accessed by the system.

cimmy@IRIS C:\Users\cimmy>

**Comment by MezTemplar** [comment]
If you delete the "Windows Subsystem for Linux" Windows App (APPX, not the EXE) you can run WSL commands headless again.  However then you get "WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel" if you try to start a VM.  Not a fix, but a clue.

**Comment by Saviio** [comment]
I had same issue, after I installed ubuntu 22.04 (from window store)，I lose acces to wsl from ssh.
can someone help to fix it?

**Comment by hassanila97** [comment]
> I had same issue, after I installed ubuntu 22.04 (from window store)，I lose acces to wsl from ssh. can someone help to fix it?

This answer fixed it for me: https://superuser.com/a/1814159

**Comment by maxmbed** [comment]
> I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> 
> Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> 
> When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

This did not work for me. After reset, restart of computer and running WSL give me a prompt:

```shell
WSL is finishing an upgrade...
```

Then and after a while:

```shell
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT

[process exited with code 4294967295 (0xffffffff)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by knogas** [comment]
I was running into this issue after switching my self-hosted build agent to run as a service.  I tried many of the suggestions above without success.  What worked for me was to modify my yml files to explicitly indicate the location of the WSL instance I want to execute:

`variables:
  **wslPath: '"C:\Program Files\WSL\wsl.exe"**'`
  
From here, I modified the docker commands I was using like so:

`'$(wslPath) docker buildx...`

Not ideal but currently the only thing working for me...

**Comment by vrajjbhatt** [comment]
> I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> 
> Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings` in the right pane, hit that menu.
> 
> When Settings windows open, you can see the `Reset` button. after the reset, **It works like a charm!**

This worked for me ! thanks @Van-Dame

**Comment by kev-in-shu** [comment]
> 
> `variables: wslPath: '"C:\Program Files\WSL\wsl.exe"'`
> 

Using this other wsl.exe worked for me

**Comment by MezTemplar** [comment]
> I was running into this issue after switching my self-hosted build agent to run as a service. I tried many of the suggestions above without success. What worked for me was to modify my yml files to explicitly indicate the location of the WSL instance I want to execute:
> 
> `variables: wslPath: '"C:\Program Files\WSL\wsl.exe"'`
> 
> From here, I modified the docker commands I was using like so:
> 
> `'$(wslPath) docker buildx...`
> 
> Not ideal but currently the only thing working for me...

I'm doing the same thing you are, but I don't have a "C:\Program Files\WSL\wsl.exe".  I tried C:\Windows\System32\wsl.exe with no luck.  My agents are running Windows Server 2022

**Comment by sinanejadebrahim** [comment]
GUYS , this happens after a restore for some reason - nothing worked for me. the only simple thing was to uninstall windows subsystem for linux and reinstall it, this doesn't cause any data loss - were not removing ubuntu , just the sub system app.so just remove it and reinstall from store. fixed easily

**Comment by incik** [comment]
> GUYS , this happens after a restore for some reason - nothing worked for me. the only simple thing was to uninstall windows subsystem for linux and reinstall it, this doesn't cause any data loss - were not removing ubuntu , just the sub system app.so just remove it and reinstall from store. fixed easily

Yes! Exactly this happend to me - I had to restore the system and WSL broke. Wasn't able to run the `wsl` command in Powershell to do anything (deleting and reimpoting my backup). I tried to remove and re-add the `Windows Subsystem for Linux` system feature itself, but that didn't help. Reinstalling the **WSL app from the Microsoft Store** fixed my problems. 🎉

**Comment by fabioDMFerreira** [comment]
Upgrading WSL to a pre-released version worked for me!

```
wsl --update --pre-release
```

After rebooting it should be fine.

https://superuser.com/questions/1714736/cannot-run-wsl2-over-ssh-on-windows-11

**Comment by omgmajk** [comment]
> `Add or remove programs` -> search for `linux` -> `Advanced options` -> `Repair` fixed it for me.

This worked for me too, had this happen today after a system restore. Found the answer on SO but also found this thread so thought I might reply here.

**Comment by navalega0109** [comment]
> Sub system app.so just remove it and reinstall from store

Hi I'm also facing the same issue and uninstalled the WSL from windows. Now trying to install from microsoft store, please check below screen shot if I'm installing correct app.

Need to uninstall
![image](https://github.com/microsoft/WSL/assets/116286227/f66ca0f3-a464-4797-b305-58a199ed77cd)

Need to install
![image](https://github.com/microsoft/WSL/assets/116286227/772f10b8-3761-4118-b071-1ba5d724f5b8)


Is this correct? Please let me know so that I can proceed.

**Comment by navalega0109** [comment]
> wsl --update --pre-release

This is not working for me. Getting same error: The file cannot be accessed by the system

**Comment by navalega0109** [comment]
> after the reset, **It works like a charm!**

Bingo Best Solution Thanks Mate!!!

**Comment by aaronir** [comment]
> > Just want to report that this solves my problem as well!!
> > > I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> > > Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings`in the right pane, hit that menu. When Settings windows open, you can see the`Reset` button. after the reset, **It works like a charm!**
> 
> This worked for me too. seriously, wtf???

This worked 

> > Just want to report that this solves my problem as well!!
> > > I solved this issue by Reset the `Windows Subsystem for Linux` in `App Settings`. I can't access that setting page after resetting. but I remember what I did.
> > > Windows logo key -> type `linux` -> 'Windows Subsystem for Linux`appears -> you can see`App Settings`in the right pane, hit that menu. When Settings windows open, you can see the`Reset` button. after the reset, **It works like a charm!**
> 
> This worked for me too. seriously, wtf???

Me too. I just hit `repair`, also worked. cool

**Comment by MezTemplar** [comment]
> Upgrading WSL to a pre-released version worked for me!
> 
> ```
> wsl --update --pre-release
> ```
> 
> After rebooting it should be fine.
> 
> https://superuser.com/questions/1714736/cannot-run-wsl2-over-ssh-on-windows-11

Since I'm on Windows Server 2022 I didn't have a Reset option in the GUI so I tried [Reset-AppxPackage](https://learn.microsoft.com/en-us/powershell/module/appx/reset-appxpackage?view=windowsserver2022-ps) with no luck.  The version I was using was 2.0.14.0, but with -pre-release it went to 2.1.3.0 and my problems went away!

**Comment by emmanuelux** [comment]
if you get :
> The file cannot be accessed by the system

the solution was not repair for me or not only :
> Add or remove programs -> search for linux -> Advanced options -> Repair

it was : 
> Add or remove programs -> search for linux -> Advanced options -> Reinitialize

**Comment by chandanck22** [comment]
- Go to FIle manager search bor type `\\wsl$` - It will open the file directory of linux distribution
- `wsl --list --v`  : It will list all installed Linux distributions
- `wsl --unregister ubuntu` - ubnuntu is the name it can be anything from the list
-  Again install ununtu from microsoft store

It works for me

**Comment by gabsoftware** [comment]
I tried many things, repairing Windows, dism commands, sfc /scannow, uninstalling / reinstalling the Windows Subsystem for Linux optional feature of Windows, repairing my distro app, repairing the WSL store app, but the thing that finally worked was:
- Uninstalling "Windows Subsystem for Linux" (it's a store app but you can only see it by typing "linux" in "applications and features" in Windows settings)
- At this point, the wsl command worked again but advised to run "wsl update"
- So I did, but that command fails miserably ("/bin/bash: line 1: update: command not found") because it's actually "wsl --update"
- Running "wsl --update" installs again the store app
- Finally working and I did not loose my distro!

**Comment by DmitrY66** [comment]
В моем случае проблема была решена одной простой командой: "wsl --shutdown". Значение ее можно посмотреть набрав "wsl --help". Может показаться странным, но это работает как сразу, так и после перезагрузки. Удачи!

**Comment by HumbleBee14** [comment]
> > Upgrading WSL to a pre-released version worked for me!
> > ```
> > wsl --update --pre-release
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After rebooting it should be fine.
> > https://superuser.com/questions/1714736/cannot-run-wsl2-over-ssh-on-windows-11
> 
> Since I'm on Windows Server 2022 I didn't have a Reset option in the GUI so I tried [Reset-AppxPackage](https://learn.microsoft.com/en-us/powershell/module/appx/reset-appxpackage?view=windowsserver2022-ps) with no luck. The version I was using was 2.0.14.0, but with -pre-release it went to 2.1.3.0 and my problems went away!


Tried everything possible, none worked. Eventually this helped - `wsl --update --pre-release`
which is funny! Stable version is Unstable

**Comment by bjagasia** [comment]
> `Add or remove programs` -> search for `linux` -> `Advanced options` -> `Repair` fixed it for me.

This worked after a system restore -- thank you.

**Comment by pengweiqhca** [comment]
I fixed it after installing [wsl.msi](https://github.com/microsoft/WSL/releases) manuall

**Comment by rayinfinite** [comment]
I fixed it by clicking a reinstall button in Windows Subsystem for Linux app in Microsoft Store

**Comment by DonovanPS** [comment]
In my case I managed to solve it in the following way:
delete the folder: `C:\Program Files\WSL`
If it does not allow you to eliminate, stop the wsl `service`, in the windows search engine you search for services and within the application you search for **wsl and stop it**

After that you search for `wsl` in windows and it will reinstall the wsl and it no longer gave me the error

**Comment by plato1123** [comment]
> I fixed it after installing [wsl.msi](https://github.com/microsoft/WSL/releases) manuall

wow that saved the day thank you <3

**Comment by herofahad777** [comment]
> > Sub system app.so just remove it and reinstall from store
> 
> Hi I'm also facing the same issue and uninstalled the WSL from windows. Now trying to install from microsoft store, please check below screen shot if I'm installing correct app.
> 
> Need to uninstall ![image](https://private-user-images.githubusercontent.com/116286227/297080847-c75379f7-a74b-444c-a803-d83b00935b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjY5MzUsIm5iZiI6MTcxOTEyNjYzNSwicGF0aCI6Ii8xMTYyODYyMjcvMjk3MDgwODQ3LWM3NTM3OWY3LWE3NGItNDQ0Yy1hODAzLWQ4M2IwMDkzNWI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTBiNTNjNzY0MDlkZmQ0ZmYzZjQ4ZWRhODIyMjVhNGEyMDZjMTI0ZDE5NGQ5OTQ5YWUwNWRlMTAzZDc4NTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rtqNHW82WIPWkqiz3BEqhJ8JrtmCN6HbacFZkScBJf8)
> 
> Need to install ![image](https://private-user-images.githubusercontent.com/116286227/297079729-772f10b8-3761-4118-b071-1ba5d724f5b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjY5MzUsIm5iZiI6MTcxOTEyNjYzNSwicGF0aCI6Ii8xMTYyODYyMjcvMjk3MDc5NzI5LTc3MmYxMGI4LTM3NjEtNDExOC1iMDcxLTFiYTVkNzI0ZjViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2Q0MjU4N2RhOWUzOGNjOTk2Mjg0ZTg1YTYzMDA5NjZjYjc1YzcyNzQ3ZWYyNDk0NWM1OTIxM2MwMTk2NGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ps3mStBZGuhaWOh7FxeKZuOV0XQWRHq6HDP79LPPWEU)
> 
> Is this correct? Please let me know so that I can proceed.

It worked thanks just needed to click repair, the internal windows repair functions for me are also broken i think

**Comment by robertoandrade** [comment]
Had this very issue on a Windows 11 installation and after reading through all comments here I noticed that indeed the `wsl.exe` that gets installed and is available on the standard `PATH` aren't really the actual executables, unless they get replaced or something gets changed after reboot/repair, but debugging through the instances of `wsl.exe` on the system:

```
>where wsl.exe
C:\Windows\System32\wsl.exe
C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps\wsl.exe

>dir C:\Windows\System32\wsl.exe
 Volume in drive C has no label.
 Volume Serial Number is 6E9D-788A

 Directory of C:\Windows\System32

02/25/2024  01:48 PM           196,608 wsl.exe
               1 File(s)        196,608 bytes
               0 Dir(s)  96,262,938,624 bytes free

>C:\Windows\System32\wsl.exe --version
The file cannot be accessed by the system.
```

Since while running `dir /s \wsl.exe` found many other copies in many directories including `C:\Program Files\WSL\wsl.exe` I ended up testing executing the same command with that one:

```
>"c:\Program Files\WSL\wsl.exe" --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3155
```

That file seems to be much bigger than the ones on the path:

```
>dir /s wsl.exe
 Volume in drive C has no label.
 Volume Serial Number is 6E9D-788A

 Directory of C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_2.2.4.0_x64__8wekyb3d8bbwe

06/21/2024  07:55 PM         3,633,088 wsl.exe
               1 File(s)      3,633,088 bytes

 Directory of C:\Program Files\WSL

04/25/2024  06:19 PM         3,633,088 wsl.exe
               1 File(s)      3,633,088 bytes

 Directory of C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps

06/21/2024  07:56 PM                 0 wsl.exe
               1 File(s)              0 bytes

 Directory of C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe

06/21/2024  07:56 PM                 0 wsl.exe
               1 File(s)              0 bytes

 Directory of C:\Windows\System32

02/25/2024  01:48 PM           196,608 wsl.exe
               1 File(s)        196,608 bytes

 Directory of C:\Windows\WinSxS\amd64_microsoft-windows-lxss-wsl_31bf3856ad364e35_10.0.22621.2506_none_62c8e9f54a7fa6e6

02/25/2024  01:48 PM           196,608 wsl.exe
               1 File(s)        196,608 bytes

 Directory of C:\Windows\WinSxS\amd64_microsoft-windows-lxss-wsl_31bf3856ad364e35_10.0.22621.2506_none_62c8e9f54a7fa6e6\f

02/09/2024  08:05 PM               344 wsl.exe
               1 File(s)            344 bytes

 Directory of C:\Windows\WinSxS\amd64_microsoft-windows-lxss-wsl_31bf3856ad364e35_10.0.22621.2506_none_62c8e9f54a7fa6e6\r

02/25/2024  01:48 PM               595 wsl.exe
               1 File(s)            595 bytes

     Total Files Listed:
               8 File(s)      7,660,331 bytes
               0 Dir(s)  96,284,803,072 bytes free
```

So not sure if the other ones are stubs or some sort of "symbolic link" to the actual ones but they don't seem to work out of the box after installing and rebooting.

**Comment by Knufle** [comment]
> > I fixed it after installing [wsl.msi](https://github.com/microsoft/WSL/releases) manuall
> 
> wow that saved the day thank you <3

Just for future reference, I was also a victim of this weird error after a Windows 10 system restore that showed a weird error upon finishing. I tried what other people said above, Repair, Reset, none of them worked.

What actually worked for me was reinstalling it like you suggested, thanks!

**Comment by shiftonetothree** [comment]
I delete this two file then fix this issue
```
C:\Users\AI\AppData\Local\Microsoft\WindowsApps\wsl
C:\Users\AI\AppData\Local\Microsoft\WindowsApps\wslconfig
```

**Comment by DanielAtCosmicDNA** [comment]
After testing other solutions here, this was the only one that worked for me...
> I fixed it after installing [wsl.msi](https://github.com/microsoft/WSL/releases) manuall

I tried the following solutions previously but unfortunately none of them worked:

- [Reset](https://github.com/microsoft/WSL/issues/9197#issuecomment-1493140959)
- [Repair](https://github.com/microsoft/WSL/issues/9197#issuecomment-2167933031)
- [Removing Windows Subsystem For Linux](https://github.com/microsoft/WSL/issues/9197#issuecomment-1396745109)
- [Restore Health](https://github.com/microsoft/WSL/issues/9197#issuecomment-1340628224)
