### ISSUE TITLE
When wsl.exe hangs, it should return a problem-specific error code or print a relevant error message. Currently it either prints nothing or `The file cannot be accessed by the system.`

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#9198]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

`wsl.exe --status` hangs at me and after a minute prints `The file cannot be accessed by the system.` (with error code 1)

### Distro Version

Can't launch, but I think Ubuntu 22.04

### Repro Steps

Likely I don't have a repro. Just at some point MS Terminal stopped creating WSLv1 sessions for me and started to time out. (WSLv2 as well). So I assume that some WSL service crashed or hangs. This bug report is to have somehow a nice error message or a problem-specific error code, so that Terminal at some point may show a good error message. For now they redirect me here :)

`wsl.exe --status` also hangs

Original report: https://github.com/microsoft/terminal/issues/12410#issuecomment-1325627599
<hr/>
When Terminal fails to connect to WSLv1 service, a new tab just times out and then prints an error code 1. It would be good if it showed a proper error message if it fails to connect to WSL (and maybe offers either to exit the tab on pressing a key or retrying to connect to WSL).

![image](https://user-images.githubusercontent.com/1041752/203641155-f8b3f407-51ca-4185-b3ed-2e29c25c870a.png)

### Expected Behavior

Specific error code / printed error message

### Actual Behavior

Generic error code 1, no error message

**Comment by vadimkantorov** [comment]
(on the issue of wsl.exe failing itself, Hibernate+Recover did do nothing to fix it; laptop reboot helped)

**Comment by jcrben** [comment]
Same problem appeared for me with WSL2 and the preview release 2.0.5.

**Comment by vadimkantorov** [comment]
Well, if nothing was done about this, the error message is probably still not clear about the hanging
