### ISSUE TITLE
[Suggestion - Not Bug] Make support for X Server Official

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/WSL#920]
Alot of us uses WSL and Win desktop merged to offer the best experience of both side, the result is great!
A bit of work on dbus and also the support of GUI & Desktop manager will be almost complete.
I think that the two side are not in competition, but in fact I think they are very complementary when used with the respective applications merged on a single desktop (Windows).

**Comment by sunilmut** [comment]
@iz0eyj - We are glad to hear that you are loving the Win+WSL combo pack! Work is in progress on AF_LOCAL sockets, which should get dbus mostly to a working state. If you would like to see better support for X Server, please head on to our [User Voice Page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) and also provide the feedback there. And, thanks for trying out WSL.

**Comment by iz0eyj** [comment]
@sunilmut OK, done.
To vote: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15693798-make-support-for-x-server-official

**Comment by ajaykagrawal** [comment]
which should get dbus _mostly_ to a working state
@sunilmut what things of dbus will _not_ work even with the support for AF_LOCAL sockets?

**Comment by sunilmut** [comment]
@ajaykagrawal - Currently, the work is in progress for passing credentials (SCM_CREDENTIALS), which seem to be used by XFCE. With that done, we are not aware of any more broken dbus scenarios. I haven't tried all the scenarios, but if something comes up, we would like to hear about it. Note that these changes in the AF_LOCAL support is in our dev branch and hasn't made it to the release branch yet.

**Comment by iz0eyj** [comment]
@sunilmut I installed the new Insider build... is possible to provide a new commando Win side?
The command is: lxrun /chengelog... prints the changelog for the present version :)

**Comment by russalex** [comment]
Closest thing we have to a changelog is our [Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).  I also send out each build as a "release" to our documentation repo over at [Microsoft/CommandLine-Documentation](https://github.com/Microsoft/CommandLine-Documentation).

The lxrun /changelog is an interesting idea but will be rather difficult with our current build system.  Something to keep an eye on.

**Comment by barry-scott** [comment]
I think the smart way to get your LInux apps into a Window would be to support Wayland protocol.
Once that is done all apps that use a modern tool kit will be able to open windows on the desktop and be managed by the task bar int eh normal windows way.

**Comment by iz0eyj** [comment]
@barry-scott this is Ubuntu, so Mir and not Wayland.

**Comment by FaraoneLele** [comment]
For me is a good idea!

**Comment by ViToni** [comment]
As Mir is out of the game for ubuntu I would suggest Wayland support.

**Comment by tara-raj** [comment]
Closing this comment. There are several X Servers available for use on Windows
