### ISSUE TITLE
"Nested virtualization is not enabled on this OS build."

### ISSUE THREAD

**Issue by kyanha** [microsoft/WSL#9201]
### Version

Windows version: 10.0.19044.2311 (Professional)

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.74.2

### Distro Version

n/a

### Other Software

Not reporting a bug involving WSL's interaction with other applications, only the OS itself.

### Repro Steps

1. Install OS version of WSL.
2. Observe that it works, including Docker Desktop for Windows and a Debian instance.
3. Install Microsoft Store version of WSL.
4. When trying to start WSL after this, the following error appears:
```
Nested virtualization is not supported on this Windows build.
Error code: Wsl/Service/CreateInstance/CreateVm/WSL_E_NESTED_NOT_SUPPORTED
```

Note that I can run VMs under Hyper-V, as well as under VirtualBox (as a client of Hyper-V).

### Expected Behavior

Expected the Windows Store version of WSL to operate the way the OS-inbuilt version of WSL operated.

### Actual Behavior

```
Nested virtualization is not supported on this Windows build.
Error code: Wsl/Service/CreateInstance/CreateVm/WSL_E_NESTED_NOT_SUPPORTED
```

### Diagnostic Logs

[WslLogs-2022-11-24_01-55-38.zip](https://github.com/microsoft/WSL/files/10081666/WslLogs-2022-11-24_01-55-38.zip)
[networking-log-capture.txt](https://github.com/microsoft/WSL/files/10081725/networking-log-capture.txt)

Note that I did receive the issue in #9186, and installed the KB5020030 Preview for x86 (I'm on an Intel core i5-8300H). That error went away, but this error came up in its place and I cannot figure out a way to fix it. (There is nothing at all that comes up when I search for "Nested virtualization is not supported on this Windows build" or "WSL_E_NESTED_NOT_SUPPORTED".)

As I said, I can run Hyper-V VMs and VirtualBox VMs (which are using the Hyper-V backend).

I had hoped to actually get systemd working in an official manner rather than having to use the various process namespace hacks. The hope to use wslg was rather secondary, but it still would have been nice.

**Comment by GovorovViva64** [comment]
Had the same problem. It looks like the CPU doesn't support Nested Virtualization on Hyper-V blocks it somehow.
WSL now uses Nested Virtualization by default, but you can disable it in <User Folder>/.wslconfig file:

```
[wsl2]
memory=12GB
processors=8
swap=18GB
swapFile=D:\wsl\swap.vhdx
localhostforwarding=true
nestedVirtualization=false  # <= You need to set this false
debugConsole=false
```

**Comment by bartlomiejmucha** [comment]
I have exactly the same problem, but my CPU supports nested virtualization for sure because I was able to run docker images inside hyper-v virtual machine. 

I created a new file `.wslconfig` in my %UserProfile% and added:
``` XML
[wsl2]
nestedVirtualization=false
```
The error is gone now and I'm able to successfully convert wsl 1 to wsl 2 with the command: `wsl --set-version Ubuntu-22.04 2`

**Comment by kyanha** [comment]
Okay. I guess my next question is, why isn't this documented in the error
message? Or, better yet, it simply falls back to non-nested virtualization
mode with a diagnostic and documentation of that setting to the WSL debug
console?

**Comment by 0xbadfca11** [comment]
regression bug.
https://github.com/microsoft/WSL/issues/6361#issuecomment-833639126

**Comment by Peter-76** [comment]
Same problem here.
Workaround is fixing the problem but I don't understand why it is needed (nested virtualization should work on my cpu)

**Comment by GovorovViva64** [comment]
@laoshaw version [1.0.3](https://github.com/microsoft/WSL/releases/tag/1.0.3) fixed the default behavior

> Remove failure path if nested virtualization is not supported (Fixes https://github.com/microsoft/WSL/issues/9196)

**Comment by whitemankpi** [comment]
> I can boot without setting nested to false on win10 22H2 but kvm is not working: "Your CPU does not support KVM extensions", I'm pretty sure it supports that(newest core i7 and I can run hyper-v), I also rebuild wsl2 kernel with kvm support, nothing helped.

got the same issue. Also rebuilt the kernel - did not help, I do not know what else to try to make it work

**Comment by CMingTseng** [comment]
@MoritzWohlgenannt 

i use the same CPU -- Intel® Core™ i7-12700  

if os is Win10   the wsl2 can not open  " nested virtualization"  -- i run ubuntu 20 at WSL2 & check kvm  only show one cpu

if os is win11 the wsl2 default is open " nested virtualization"

THX

**Comment by CMingTseng** [comment]
@GovorovViva64 

@whitemankpi 

@bartlomiejmucha 

the  WSL2 with " nested virtualization" only  for  Win11 

the win10  it still can not work  

PS. CPU is Intel   or AMD  the same

**Comment by its-so-fluffy** [comment]
What about Windows Server 2022 is it supported?

**Comment by Moritz-Wohlgenannt** [comment]
@its-so-fluffy 
> What about Windows Server 2022 is it supported?

Yes, as I mentioned in my comment from earlier. The link also has more detailed information:


> note that for amd cpus nested virtualization is only supported under windows 11 / server 2022 when using hyper-v. so a windows 10 machine runing hyper-v for wsl2 won't support nested virtualization for amd cpus. source: https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization
