### ISSUE TITLE
wslg not working on windows 11

### ISSUE THREAD

**Issue by Tsuna77** [microsoft/WSL#9206]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Ubuntu 20.04

### Repro Steps

start graphic application

### Expected Behavior

application start

### Actual Behavior

Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0

### Diagnostic Logs

ls -la /tmp/.X11-unix => empty

**Comment by OneBlue** [comment]
Probably a /dupe #9158

**Comment by Tsuna77** [comment]
I confirme the duplicates :) and pre-release 1.0.1 patch my problem, thanks a lot
