### ISSUE TITLE
Systemd not starting correctly on fresh install after reboot

### ISSUE THREAD

**Issue by ToasterDEV** [microsoft/WSL#9207]
### Version

Microsoft Windows [Version 10.0.22621.382] | WSL version: 1.0.1.0 Kernel version: 5.15.74.2 WSLg version: 1.0.47 MSRDC version: 1.2.3575 Direct3D version: 1.606.4 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22621.382

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.74.2-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 2 19:50:29 UTC 2022

### Distro Version

Release:        22.04

### Repro Steps

1. Enable systemd by writing ```[boot] \n systemd=true``` to `/etc/wsl.conf`
2. Execute `wsl.exe --shutdown` on a PowerShell 7 Administrator session
3. Open Ubuntu again and run `systemctl list-units --type=service`, then see successful listing of services
4. Reboot the computer from the Start menu
5. Open another terminal session to the Ubuntu distro
6. Run `systemctl is-system-running`
7. Output is `Failed to query system state: Transport endpoint is not connected \n unknown`

### Expected Behavior

Running either `systemctl list-units --type=service` or `Failed to query system state: Transport endpoint is not connected \n unknown` should output the systemd service list or a success state respectfully

### Actual Behavior

[strace](https://gist.github.com/ToasterDEV/822cac73765456b6b6692bc66cc1da06)
```
$ systemctl is-system-running
Failed to query system state: Transport endpoint is not connected
unknown
```
[strace](https://gist.github.com/ToasterDEV/39e93e84100a8283f8b0453b4ef04b61)
```
$ systemd-analyze
Failed to get timestamp properties: Transport endpoint is not connected
```

### Diagnostic Logs

[WslLogs-2022-11-24_15-29-43.zip](https://1drv.ms/u/s!AlYW1BPO6zRt9-1sg9DcWKybvJZWUw?e=EaoxEE)

**Comment by OneBlue** [comment]
Thank you for reporting this @ToasterDEV. 

Can you share the output of `dmesg` when you see that error ?

**Comment by ToasterDEV** [comment]
> Thank you for reporting this @ToasterDEV.
> 
> Can you share the output of `dmesg` when you see that error ?

Sure, when I run `` systemctl is-system-running``     then `dmesg` the output is the following [gist](https://gist.github.com/ToasterDEV/3d46d5dd0fa24908b8ff71ea8b67f8f5).

**Comment by OneBlue** [comment]
Thanks for the notification @ToasterDEV. We've made a couple fixes with WSL 1.0.3, do you still see the issue after running wsl.exe --update ? If so, can you capture /logs with the latest version so I can have a deeper look ?

**Comment by ToasterDEV** [comment]
> Thanks for the notification @ToasterDEV. We've made a couple fixes with WSL 1.0.3, do you still see the issue after running wsl.exe --update ? If so, can you capture /logs with the latest version so I can have a deeper look ?

Sure @OneBlue !

Unfortunately, even after checking I have WSL version 1.0.3.0 and `wsl --update` confirming I have the latest version, the issue remains present. As such, I'll attach the logs [here](https://1drv.ms/u/s!AlYW1BPO6zRt9_Qz8LOzvpOnYWt8yg?e=6RLsbK).

Thanks for the help!

**Comment by OneBlue** [comment]
Thanks @ToasterDEV.

Unfortunately, I'm not seeing any WSL logs in the file you shared. Can you try running: `wsl.exe --shutdown` before capturing the logs so the WSL boot is captured ?

**Comment by OneBlue** [comment]
Thank you @ToasterDEV. Looking at the logs, the last entry from systemd is: `
4926	False	Microsoft.Windows.Lxss.Manager	GuestLog	0	01-11-2023 10:18:57.322	"	"	"text: 	""         Starting Accounts Service... ""
vmId: 	{c7d0717d-4e2c-426f-af29-1662d25dda89}"				11500	38172	5		00000000-0000-0000-0000-000000000000		

```

So most likely something is getting stuck. Once wsl has started, can you share the output of: `sudo journalctl` ?

**Comment by ToasterDEV** [comment]
Sure!

Just performed another `wsl --shutdown` and ended up with the following line being repeated infinitely after entering `sudo journalctl:`

`Jan 12 21:53:30 ToastyUFO systemd[1]: Condition check resulted in ACPI event daemon being skipped.`

It goes on and on at least for 3006152 lines of the same, with that being the last one at the moment of the pipe. Show I upload the rest of the log regardless? It won't fit in a gist.

**Comment by lanmo0923** [comment]
I have the same problem, can it be fixed now?

**Comment by 0Grit** [comment]
same here

**Comment by 0Grit** [comment]
Anybody else using usbip?

**Comment by ToasterDEV** [comment]
@OneBlue Sorry if pinging you directly ends up looking like a bit much (I'm taking the liberty to do so because you self-assigned this issue, but given my lack of experience, please feel free to tell me if I'm overstepping some boundaries), though I'd like to report that the issue is still present and reproducing the exact same behavior as of a few hours ago.

If there's any information that might be required of me to continue troubleshooting, please let me know.

Kudos!

**Comment by gf9276** [comment]
I also have the same problem. After running `apt install ubuntu gnome desktop`, the system ctl encountered the same problem as you.

**Comment by gf9276** [comment]
I also have the same problem. After running 
```apt install ubuntu-gnome-desktop```, 
the system ctl encountered the same problem as you.

**Comment by evening-hs** [comment]
I'm having the same issue. When I run:

```
systemctl is-system-running
```

I get:

```
Failed to query system state: Transport endpoint is not connected
unknown
```

I get

```
[ 1071.395280] systemd-coredump[1537]: Failed to connect to coredump service: No such file or directory
```

I found this [discussion](https://github.com/microsoft/WSL/discussions/10364) but the solution brings me back to:

```
Transport endpoint is not connected
```
