### ISSUE TITLE
Cannot disable IPV6 in ubuntu WSL2 1.0.0

### ISSUE THREAD

**Issue by peterjuras** [microsoft/WSL#9211]
### Version

Windows version: 10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.74.2

### Distro Version

Ubuntu 22.04.1 LTS

### Repro Steps

1. Add the following lines to /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
2. Disable all IPV6 checkboxes for all network adapters in the control panel
3. Reboot system

### Expected Behavior

The ubuntu command: `ip addr` should no longer show an IPV6 address for eth0.

This breaks my docker desktop setup because containers can't communicate with each other. How can I disable IPV6 addresses for ubuntu in WSL2?

### Actual Behavior

It still has a ipv6 address.

**Comment by NiKiZe** [comment]
Suggestion Fix your setup properly instead.

**Comment by peterjuras** [comment]
I'm using docker-compose to run multiple containers that aim to connect to each other, with the help of [docker-host](https://github.com/qoomon/docker-host).

This doesn't work when there's an IPV6 address assigned, since docker can't handle it. How would you suggest to fix my setup?

**Comment by miyurusankalpa** [comment]
open a issue on https://github.com/qoomon/docker-host

IPv6 works fine on docker.

**Comment by NiKiZe** [comment]
> I'm using docker-compose to run multiple containers that aim to connect to each other, with the help of [docker-host](https://github.com/qoomon/docker-host).
> 
> This doesn't work when there's an IPV6 address assigned, since docker can't handle it. How would you suggest to fix my setup?

If software don't work when IPv6 is available on host, then it is just horrible broken. Disabling IPv6 is unacceptable.

If software don't work with IPv6 then it needs to be fixed. IPv4 is dead, what we need is ways to remove IPv4 from hosts.

**Comment by OneBlue** [comment]
@peterjuras: `sysctl.conf` isn't applied by WSL so changes in that files won't have any effect.

One way to disable ipv6 globally would be to add:
```
[wsl2]
kernelCommandLine=ipv6.disable=1
```

In %USERPROFILE%/.wslconfig

(you'll need to run wsl.exe --shutdown to restart WSL after making the change).

**Comment by peterjuras** [comment]
Thanks @OneBlue!
