### ISSUE TITLE
Importing a vhdx without specifying --vhd results in Unspecified error

### ISSUE THREAD

**Issue by RequiDev** [microsoft/WSL#9214]
### Version

Microsoft Windows [Version 10.0.19045.2311]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.74.2

### Distro Version

Debian 11

### Repro Steps

Export a distro as vhdx using --vhd and try to import it without using --vhd

### Expected Behavior

WSL should tell the user that they should specify --vhd if file ending is vhdx or automatically switch to --vhd behaviour.

### Actual Behavior

WSL reports:
Unspecified error
Error code: Wsl/Service/0x80004005

**Comment by Biswa96** [comment]
> WSL should tell the user that they should specify --vhd if file ending is vhdx

The command details can be found here https://learn.microsoft.com/en-us/windows/wsl/basic-commands

**Comment by OneBlue** [comment]
Unfortunately WSL can't make assumptions on file contents based on the extension.  The documentation makes it clear that --vhd is required to import VHD's.
