### ISSUE TITLE
The application cannot be started because it is currently updating when trying to wsl --install

### ISSUE THREAD

**Issue by kzkimv79** [microsoft/WSL#9220]
### Version

Microsoft Windows 11 Home

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Can't see Kernel version. Same error message appears

### Repro Steps

C:\Users\camik>wsl --install
The application cannot be started because it is currently updating.

### Expected Behavior

wsl installation

### Actual Behavior

The application cannot be started because it is currently updating.

**Comment by benhillis** [comment]
Is an update pending in the Microsoft Store?

/logs

**Comment by robUx4** [comment]
I get the same problem on Windows 10 after updating Windows. This is the second time this blocks me after a Windows update. Eventually it comes back (I hope).

I attach logs as described above.
[WslLogs-2023-07-18_13-42-42.zip](https://github.com/microsoft/WSL/files/12079995/WslLogs-2023-07-18_13-42-42.zip)
