### ISSUE TITLE
openSUSE Leap, store edition, fails to install on Windows 10 

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9226]
### Version

Microsoft Windows [Version 10.0.19045.2311]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

`openSUSE Leap` 

### Other Software

`openSUSE Tumbleweed`

WSL version used for testing:
```
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2311
```

### Repro Steps

Open Microsoft Store and install openSUSE Leap or openSUSE Tumbleweed.

### Expected Behavior

Successful install.

### Actual Behavior

![opensuse_leap_install_error](https://user-images.githubusercontent.com/3933920/204375271-4fb7230d-6f96-4519-b103-6c1626420fc9.png)

**Comment by benhillis** [comment]
I believe you have an invalid entry in your `%userprofile%\.wslconfig` file. What are the contents of that file?

/logs
