### ISSUE TITLE
[BUG] GitBash is not working with Ubuntu bash on Windows

### ISSUE THREAD

**Issue by Torvaldi** [Microsoft/WSL#923]
After installing the "Windows subsystem for Linux", my GitBash does not work. I get this message when I'm trying to download and compile BuildTools : "You must run this jar through bash (msysgit)".

The expected result will be "Pulling updates for B:\BuildTools\BuildData.git".

I have disable the subsystem and it works fine !

**Comment by benhillis** [comment]
This is due to the bash.exe name conflicting with GitBash's bash.exe.  If you type "where bash.exe" inside a CMD prompt I suspect you'll see C:\Windows\System32\bash.exe instead of the path to GitBash.

**Comment by Biswa96** [comment]
@benhillis If the bash.exe name conflicts then why not you remove the bash.exe from system32 and use only wsl.exe (like lxrun.exe was deprecated).

**Comment by tara-raj** [comment]
A workaround would be to edit your path to avoid the conflict. For example, you can move GitBash above System32.

**Comment by therealkenc** [comment]
Better: use `wsl.exe`.

**Comment by rmoscuba** [comment]
Or you can use `sh` instead of `bash` (actually it is the same exe renamed)

**Comment by mohamedds-12** [comment]
> A workaround would be to edit your path to avoid the conflict. For example, you can move GitBash above System32.

Worked for me thanks
