### ISSUE TITLE
Ubuntu and Kali on WSL are not able to update.

### ISSUE THREAD

**Issue by RealAbhishek** [microsoft/WSL#9235]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04.1 LTS, Kali-Linux

### Repro Steps

1. Make sure the distro is running on WSL version 1.
2. Open the distro shell and run `sudo apt update`.

Observe the result.

![image](https://user-images.githubusercontent.com/10286559/204756477-2be4ebc8-28bd-455f-ac85-509c9563ab9a.png)

### Expected Behavior

The command should update the package sources list with the latest versions of the packages in the repositories.

### Actual Behavior

Connection gets timed out.

` Could not connect to http.kali.org:80 (192.99.200.113), connection timed out`

**Comment by sirredbeard** [comment]
Are you able to ping or curl other URLs?

This appears to be a networking issue.

Do you have any third-party security or network software installed, like a 'security suite' or VPN?

**Comment by maroskukan** [comment]
Looks like your name resolution works well, therefore the next thing I would check is host route table

```bash
ip route get 192.99.200.113
```

The next hop should be the Windows network interface for WSL. which you can confirm from Windows:

```powershell
netsh interface ip show address "vEthernet (WSL)"
```

I have previous experience that sometimes it helps to just restart the the following service to resolve DHCP issues (perhaps it will for our connectivity issue) for WSL network:

```powershell
Restart-Service -DisplayName "Internet Connection Sharing (ICS)"
```

Finally as @sirredbeard  mentioned it may be other software on your host machine that can interfere with routing.
