### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by maroskukan** [microsoft/WSL#9236]
Hello,

First of all thanks for the hard work on WSL2, really enjoying the new features.

The [build instructions](https://github.com/microsoft/WSL2-Linux-Kernel#build-instructions) for x86_64 WSL2 kernel on Ubuntu is missing some packages for building the kernel, please add `bc` and `python3` to the list. Otherwise the build will fail on these dependencies.

Also, perhaps it would be beneficial to mention that Ubuntu Docker container can be used as build environment in case you don't want to clutter your main environment with these build dependencies.

**Comment by NotTheDr01ds** [comment]
It's worth pointing out for others reading this that, yes:

* The build instructions say that they are for Ubuntu
* *Most* Ubuntu distributions will already have `bc` and `python3`

However, the Ubuntu docker image does *not* contain these by default.  So it's a valid point that they may be an additional required dependencies under some Ubuntu distributions.

I also second the suggestion to add Docker as a recommended method for building.

**Comment by NotTheDr01ds** [comment]
@maroskukan  You might want to try submitting a PR (or two) on the `README.md` with your suggested changes and reference this issue.  I know that most PRs should be submitted upstream on the kernel, but the `README.md` is specific to that project.

**Comment by maroskukan** [comment]
@NotTheDr01ds yes I was thinking about that, but looks like this older [PR](https://github.com/microsoft/WSL2-Linux-Kernel/pull/121) suggest that this repo is the right place to "suggest" improvements. So hopefully somebody from MS team could pick this up and implement that change. Its really just 2-3 lines of text, but it would really help newcomers.

**Comment by NotTheDr01ds** [comment]
@maroskukan Good catch - And that's even specific to the `README.md` as well, so I agree you definitely did the right thing!
