### ISSUE TITLE
rsync in WSL2 to external harddrive gives Operation not permitted error

### ISSUE THREAD

**Issue by sorenwacker** [microsoft/WSL#9239]
### Version

10.0.22000.1219; Invalid command line option: --version

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.104

### Distro Version

22.04

### Other Software

Using an encrypted harddrive mounted with Veracrypt 1.25.9. 
And rsync  version 3.1.3  protocol version 31.

### Repro Steps

I mount the harddrive first with Veracrypt and then with `sudo mount...` within WSL2.

Then I run rsync with the target folder a subfolder on the harddrive.

### Expected Behavior

It should copy files and directories to the harddrive.

### Actual Behavior

Only folders are created. Files fail with the error Operation not permitted (1).

Apparently, that could be worked around with `sudo rsync...`, but this is not a very appealing and secure solution.

**Comment by NotTheDr01ds** [comment]
Try adding `-o metadata,uid=1000,gid=1000`, or at least the `uid`/`gid`.  See [this comment](https://github.com/microsoft/WSL/issues/3187#issuecomment-388904048) on #3187.

**Comment by sorenwacker** [comment]
Works.
