### ISSUE TITLE
A connection with the server could not be established

### ISSUE THREAD

**Issue by MetalDent** [microsoft/WSL#9243]
I am trying to install WSL distro on my laptop. It is new with windows 11. But I am constantly getting the following error:
"A connection with the server could not be established"

Even when I tried to clone a git repository, I got the same error.
Does anyone know how to fix this?

I am doing ` wsl --list --online`

**Comment by srvasanthan33** [comment]
> I am trying to install WSL distro on my laptop. It is new with windows 11. But I am constantly getting the following error: "A connection with the server could not be established"
> 
> Even when I tried to clone a git repository, I got the same error. Does anyone know how to fix this?
> 
> I am doing ` wsl --list --online`



> 


Hey , I'm also facing the same issue . Did it get Resolved?
