### ISSUE TITLE
Win11/WSL2/Ubuntu 20.04 serial ports have wrong group ownership

### ISSUE THREAD

**Issue by crosland** [microsoft/WSL#9247]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Run command ls -al /dev/* 

### Expected Behavior

Expect serial ports to be in dialout group with permissions 660

### Actual Behavior

All port are in group root with permissions set to 600

This seems to be the same as issue #3042 from 2018!

**Comment by crosland** [comment]
My immediate issue is fixed.

I had another issue with a R-Pi picoprobe that requires a udev rule to allow openocd to run without sudo. I was trying to access /dev/ttyACM0 and that is also fixed by the udev rule as it is in the same physical USB interface as the picoprobe.

I am now no longer sure if this is a real issue with the other entries in /dev. Feel free to close it if there is no issue.

**Comment by MarianArlt** [comment]
I can confirm this.
Happened to me today after installing a RS232 interface in my server, then connecting to it from a Windows 11 Enterprise 22H2 build 22621.1105 host with WSL2 enabled.
(I am somewhat confused on that note to see two entries in installed applications about WSL with awkward versioning):
```
Windows Subsystem for Linux WSLg Preview 1.0.27
Windows Subsystem for Linux Update 5.10.102.1
```
Installed Linux is an updated Debian, Kernel 5.10.102
```
Linux <host> 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Behavior is exactly as described, group is root and permissions are mounted 600:
```
crw------- 1 root root 4, 64 Jan 28 10:21 /dev/ttyS0
crw------- 1 root root 4, 65 Jan 28 10:06 /dev/ttyS1
crw------- 1 root root 4, 66 Jan 28 10:06 /dev/ttyS2
crw------- 1 root root 4, 67 Jan 28 10:06 /dev/ttyS3
```

**Comment by alexkoeberl** [comment]
I had the same issue with Ubuntu 5.15.133.1-microsoft-standard-WSL2, this answer solved it for me:
https://askubuntu.com/a/1449282

It seems that Systemd is not started correctly, you need to add the following to `/etc/wsl.conf` (and restart WSL):
```
[boot]
systemd=true
```

Then you can access the serial ports after joining the *dialout* group:
`
 sudo usermod -a -G dialout $USER
`

**Comment by craigloewen-msft** [comment]
It seems like this is fixed, please follow the instructions there! Systemd is now on by default in the latest WSL versions which should also address this. Thank you for filing!
