### ISSUE TITLE
/etc/wsl.conf   boot.command Cannot execute exe

### ISSUE THREAD

**Issue by androiddisk** [microsoft/WSL#9256]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.74.2

### Distro Version

Ununtu 20.04

### Repro Steps

I saw the launch of Windows executables from processes launched via /etc/wsl in my daily life. Boot conf. System

https://github.com/microsoft/WSL/releases/tag/0.68.2

But actually, $PATH doesn't have a window path

/etc/wsl.conf:
```
[boot]
command = /bin/bash /root/boot.sh > /root/boot.log 2>&1
systemd=true

[interop]
enabled = true
appendWindowsPath = true
```
/root/boot.sh:
```
#/bin/bash
echo $PATH
netsh.exe interface portproxy show all
```

### Expected Behavior

If I execute in the shell manually, I will not report an error and execute successfully

output：
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/d/apps/Bandizip/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/d/apps/Xshell/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/d/apps/jdk-11.0.16.1/bin:/mnt/d/apps/jdk-11.0.16.1/jre/bin:/mnt/c/Users/zhong/AppData/Local/Microsoft/WindowsApps:/mnt/d/apps/Microsoft VS Code/bin:/snap/bin
侦听 ipv4:                 连接到 ipv4:

地址            端口        地址            端口
--------------- ----------  --------------- ----------
0.0.0.0         22          172.26.197.135  22
0.0.0.0         80          172.26.197.135  80
0.0.0.0         888         172.26.197.135  888
0.0.0.0         8888        172.26.197.135  8888
0.0.0.0         8096        172.26.197.135  8096
0.0.0.0         8080        172.26.197.135  8080
0.0.0.0         49688       172.26.197.135  49688
0.0.0.0         8000        172.26.197.135  8000
0.0.0.0         9000        172.26.197.135  9000
0.0.0.0         2342        172.26.197.135  2342
```

### Actual Behavior

output to boo.log : 
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/boot.sh: line 3: netsh.exe: command not found

````

### Diagnostic Logs

If you need other logs, please tell me how to provide them

**Comment by NotTheDr01ds** [comment]
*Short answer:* Try calling `netsh.exe` with its full path `/mnt/c/WINDOWS/System32/netsh.exe` in your script.

This does require WSL [0.68.2](https://github.com/microsoft/WSL/releases/tag/0.68.2) or later, though, to be able to run Windows executables in the `boot.command`.

*More explanation:*

This might be borderline between an "issue" and a "feature".  It's likely just a pure `PATH` issue, but it's pretty much expected the way that WSL works at the moment.  The Windows Path only gets appended to the Linux `PATH` when in a shell (or other application) session that was launched *directly* by WSL.

Try setting your `boot.command` as follows:

```
command = sh -c 'cat /proc/$$/environ | xargs -0 -L1 echo >> /root/environ'
```

If you restart WSL and check that file (as root), you'll see the *very* minimal environment that you have access to at that point.  There's *not even a `PATH` variable*.  This means that `sh` is using it's hard-coded `PATH`.  You can see the path if you change the command to:

```
command = sh -c 'echo $PATH > /root/wsl_path'
```

That means that you'll need to call any Windows executables with their fully qualified path while inside any code running under `boot.command`'s.  The same holds true for any Systemd service.

If you are still having trouble, try one additional troubleshooting step:

```
command = /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe -c "Get-ComputerInfo" > /root/computer_info 2>&1
```

Then work your way up to the full `netsh.exe` from there.

**Comment by androiddisk** [comment]
After adding PATH, exe runs normally

However, the output of exe is garbled in Chinese

@NotTheDr01ds Please have a look


```
echo $PATH | grep -q /mnt/c/Windows/system32 || export PATH=$PATH:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/
echo $LANG | grep -q C.UTF-8 || export LANG=C.UTF-8
tcp_ports=22,80,888,8888,8096,8080,49688,8000,9000,2342
powershell.exe iex \'New-NetFireWallRule -DisplayName \"WSL 2 Firewall Unlock TCP\" -Direction Outbound -LocalPort $tcp_ports -Action Allow -Protocol TCP\'
```

![image](https://user-images.githubusercontent.com/11062371/205424553-2f559eff-b9fb-443b-b768-b23813b6dc9b.png)

**Comment by NotTheDr01ds** [comment]
@androiddisk Hmmm - I doubt I'll be able to reproduce it since I'm only running English here, but a few thoughts:

* You don't mention it, but I assume the same script runs okay when executed directly from Bash.

* Since your language setting for PowerShell seems to be Chinese already (from the `netsh.exe` output in your original question), I'm also assuming that you are expecting Chinese text strings, just not *garbled* Chinese text strings.  That looks like some type of code-page issue, but it's been a long, long time since I worked with multiple-language and codepage issues in Windows (IIRC, Windows 95/NT days).

* I'm not sure that setting `LANG` on the Linux side is going to ultimately impact the PowerShell output, but I agree it's what I would be trying first as well.

* If this is working for you in the first place, then I assume that you are running your WSL distribution in an elevated prompt.  I don't think this contributes to the problem you are seeing, but I'm not a fan of the approach myself.  There's just too much chance for something on the Linux side to impact crucial Windows functionality (including malware insertion, however unlikely an attack vector WSL->Windows may be).

    It's possible, with a little additional hackery (which you are already well into at this stage), to run the `New-NetFirewallRule` elevated *without* running the rest of the WSL distribution that way.  Of course, you'll get a UAC prompt each time you start the WSL distribution, but (a) that's good practice anyway, and (b) I assume you already have to elevate via UAC when you run the distribution in an administrative session anyway.

    ```bash
    #!/bin/bash
    echo $PATH
    echo $PATH | grep -q /mnt/c/Windows/system32 || export PATH=$PATH:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/
    
    psCmd="\"New-NetFireWallRule -DisplayName 'WSL 2 Firewall Unlock TCP' -Direction Outbound -LocalPort 8000 -Action Allow -Protocol TCP\""
    powershell.exe -c "start-process powershell.exe -verb runas -argumentList '-c',$psCmd"
    sleep 5
    powershell.exe -c "Get-NetFirewallRule -DisplayName 'WSL 2 Firewall Unlock TCP'"
    ```

    That, of course, is a simplified version that only handles one of the ports (to simplify the quoting/variable interpolation for my sake) just to demonstrate the technique.  I do find that assigning interim steps to variables (like the `psCmd`) can simplify quoting somewhat when working between Bash and PowerShell.  But then again, I don't think that the problem you are seeing has anything to do with the quoting either.

    I'm guessing there's probably a way to get the return text back from the `Start-Process`, but I just wimped out on that for now and ran a separate `Get-NetFirewallRule` to confirm the rule.  I'd kind of be curious to see if (for some unknown reason) this makes any difference in your output, but I'm not expecting it.

    I also used `-c` instead of `iex`, but again, I can't see why that would make a difference.  Just some different things to try on your end.

Of course, if all else fails, this doesn't seem to be a big deal.  The `Status` output is the only localized string that is involved here, and the numeric code is just as valid (65536 is success, I believe).

**Comment by NotTheDr01ds** [comment]
Oh, one additional thought as I was "cleaning up" my tests.  You probably realize this already, but keep in mind that the way you are calling this at the moment will create a duplicate firewall rule each time you restart the distribution.

**Comment by ThePlenkov** [comment]
Hi! Did you manage to solve it? I have the identical issue. powershell.exe works with my user but doesn't work during boot. Could it be some permission issue may be?

**Comment by ThePlenkov** [comment]
One more obeservation.
```
sudo powershell.exe
sudo: powershell.exe: command not found
```

but
```
sudo /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
```

**Comment by ThePlenkov** [comment]
ok I see why `echo "${PATH//:/$'\n'}"` in  `sudo bash`   prints this:
```
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/snap/bin
```

so no wsl folders. I guess to make it working we need to create also a symlink in  one of those
