### ISSUE TITLE
[WSL --list --online] command is missing Ubuntu 22.04

### ISSUE THREAD

**Issue by colemar** [microsoft/WSL#9259]
### Version

Windows version: 10.0.19045.2311

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Repro Steps

wsl --list --online

### Expected Behavior

Ubuntu 22.04 LTS is listed among available distributions.

I see it can be installed through MS Store, also I am downloading the appx package from https://aka.ms/wslubuntu2204

### Actual Behavior

```
PS C:\Users\colem> wsl --list --online
The following is a list of valid distributions that can be installed.
Install using 'wsl.exe --install <Distro>'.

NAME               FRIENDLY NAME
Ubuntu             Ubuntu
Debian             Debian GNU/Linux
kali-linux         Kali Linux Rolling
SLES-12            SUSE Linux Enterprise Server v12
SLES-15            SUSE Linux Enterprise Server v15
Ubuntu-18.04       Ubuntu 18.04 LTS
Ubuntu-20.04       Ubuntu 20.04 LTS
OracleLinux_8_5    Oracle Linux 8.5
OracleLinux_7_9    Oracle Linux 7.9
```

**Comment by elsaco** [comment]
@colemar first entry `Ubuntu` is `Ubuntu-22.04`:

```
       {
            "Name": "Ubuntu",
            "FriendlyName": "Ubuntu",
            "StoreAppId": "9PDXGNCFSCZV",
            "Amd64": true,
            "Arm64": true,
            "Amd64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu_2204-221101_x64.appx",
            "Arm64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu_2204-221101_ARM64.appx",
            "PackageFamilyName": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
        },
```

See details at: https://github.com/microsoft/WSL/blob/c67e3febbc4b12d0f6f0d20c418ac2a7164658e4/distributions/DistributionInfo.json#L4

**Comment by colemar** [comment]
Understood.
Thank you.

**Comment by master255** [comment]
This is not fixed. Ubuntu is still the 20.04 version.

**Comment by Biswa96** [comment]
Latest version of Ubuntu can be downloaded from here https://apps.microsoft.com/store/search?hl=en-us&gl=us&publisher=Canonical%20Group%20Limited

**Comment by master255** [comment]
@Biswa96 It's not for me. It's for all people.
