### ISSUE TITLE
Will there be a risk of data corruption when the wsl mounts the hard disk and runs raid5

### ISSUE THREAD

**Issue by androiddisk** [microsoft/WSL#9262]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Ununtu 20.04

### Repro Steps

I mount three hard disks on the wsl and set raid5.
I wonder if the group raid5 in the wsl directly shuts down Windows or runs wsl -- shutdown will affect the data loss of raid5
/etc/wsl.conf :
```
[boot]
command = time /bin/bash /root/boot.sh > /root/boot.log 2>&1
systemd=true

[interop]
enabled = true
appendWindowsPath = true
```
/root/boot.sh :
```
for wdc in $(powershell.exe GET-CimInstance -query \"SELECT \* from Win32_DiskDrive\" | grep -E "WDC  WUH721816ALE6L4|Samsung SSD 960 EVO 1TB" | awk '{print $1}') ; do
  wsl.exe --mount $wdc --bare;
done
[ -e "/dev/md0" ] || mdadm --assemble /dev/md0 --uuid=9a67938a-5a74-4d30-59d0-fecb62db04b2
if ! mount | grep " /mnt/wsl/raid5 " > /dev/null; then
    mount UUID=70a15308-ab75-462b-96b9-0f851cf7245f /mnt/wsl/raid5
    mdadm --detail /dev/md0
fi
```

### Expected Behavior

Very worried about raid5 damage

Do you need to stop raid5 to run wsl -- shutdown or shut down Windows

```
umount /mnt/wsl/raid5
mdadm --stop /dev/md0
```

### Actual Behavior

Currently in normal operation

**Comment by OneBlue** [comment]
@androiddisk: There is no mechanism to stop a mdadm raid when WSL shuts down today  so calling `mdadm --stop` is definitely a good idea.

In theory I'd imagine that mdadm raids are designed not to lose data when the machine shuts down without properly unmounting its devices, but if you're that worried about data losses, I definitely recommend doing regular backups.

**Comment by androiddisk** [comment]
> @androiddisk: There is no mechanism to stop a mdadm raid when WSL shuts down today so calling `mdadm --stop` is definitely a good idea.
> 
> In theory I'd imagine that mdadm raids are designed not to lose data when the machine shuts down without properly unmounting its devices, but if you're that worried about data losses, I definitely recommend doing regular backups.

Thank you I see
