### ISSUE TITLE
`--no-launch` option not working when distro is not specified

### ISSUE THREAD

**Issue by soredake** [microsoft/WSL#9266]
### Version

Версия WSL: 1.0.0.0 Версия ядра: 5.15.74.2 Версия WSLg: 1.0.47 Версия MSRDC: 1.2.3575 Версия Direct3D: 1.606.4 Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows версии: 10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.74.2-microsoft-standard-WSL2

### Distro Version

20.04

### Repro Steps

If you try installing wsl with options `--install --no-launch` without specifying the distro it will just list you all the options and do nothing.

### Expected Behavior

`wsl.exe --install --no-launch` should work and install default distro like `wsl.exe --install` instead of just doing nothing.

### Actual Behavior

`wsl.exe --install --no-launch` just lists you all options and then doing nothing, no wsl or distro is installed.

**Comment by pmartincic** [comment]
I think the behavior is confusing and we should change it. (store wsl vs inbox wsl behavior vs inbox wsl --nolaunch).

**Comment by soredake** [comment]
Fixed now.
