### ISSUE TITLE
Can't access a WSL share with account/password in a win32 app when \\wsl.localhost\Ubuntu\ is not mounted as a drive

### ISSUE THREAD

**Issue by JosHuybrighs** [microsoft/WSL#9267]
### Version

Windows 11 Home 22H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.74.2

### Distro Version

Ubuntu 22.04.1

### Repro Steps

Create a windows app (win32, WindowsAppSDK, etc..) which explicitly uses a account/password to add a network connection to \\wsl.localhost\Ubuntu, like so:

```
NETRESOURCE nr = new NETRESOURCE();
nr.dwScope = RESOURCE_SCOPE.RESOURCE_GLOBALNET;
nr.dwType = RESOURCE_TYPE.RESOURCETYPE_DISK;
nr.dwDisplayType = RESOURCE_DISPLAYTYPE.RESOURCEDISPLAYTYPE_GENERIC;
nr.dwUsage = RESOURCE_USAGE.RESOURCEUSAGE_CONNECTABLE;
nr.lpLocalName = null;
nr.lpProvider = null;
nr.lpRemoteName = netwShare; // i.e \\wsl.localhost\Ubuntu
nr.lpComment = null;
int errorCode = WNetAddConnection2(nr, password, userName, CONNECT_TEMPORARY);
```

Don't mount \\wsl.localhost\Ubuntu in Windows.

### Expected Behavior

The call to `WNetAddConnection2 `should return 0 (success).

### Actual Behavior

When executing the above code with "\\wsl.localhost\Ubuntu" as `netwShare`" and with what I suppose is a correct `userName `and password (the one assigned when initially configuring Ubuntu), `WNetAddConnection2 `returns `errorCode `487 (ERROR_INVALID_ADDRESS).

Should I not call `WNetAddConnection2` when the share is `\\ws.localhost\..` and there is no mounted drive to it and not bother about the account/password?

**Comment by OneBlue** [comment]
Thanks for reporting this @JosHuybrighs.

`\\wsl.localhost` isn't a 'network' share that can be opened via WNetAddConnectionX. Everything happens locally and there is no authentication required to access it.

The username / password combination in your WSL distribution isn't connected to `\\wsl.localhost` at all.
