### ISSUE TITLE
Getting error "ERROR: id not found" when running docker-compose on Alpine Linux v3.17

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#9268]
### Version

Windows version: 10.0.22623.1020

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Alpine Linux v3.17

### Other Software

docker version
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.14.1 (91661)
 Engine:
  Version:          22.06.0-beta.0-407-g7a5cce156e.m
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.18.4
  Git commit:       7a5cce156e
  Built:            Thu Oct 13 08:07:59 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Repro Steps

git clone https://github.com/mwoodpatrick/docker-compose-test
cd docker-compose-test
docker-compose up -d

### Expected Behavior

Expected to fetch & start containers

### Actual Behavior

I am getting the error:

```
ERROR: id not found
```

**Comment by mwoodpatrick** [comment]
What version of Alpine & docker, and windows were you running with? How did you install docker without also installing the client?

**Comment by mwoodpatrick** [comment]
So if I get rid of the windows client and use dockerd the unit error goes away (yeah!) and the mysql image starts but the app faiils with the output below. Does anyone know what I'm doing wrong

 docker-compose start app
Starting app ...
time="2022-12-05T18:50:24.160141003Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-12-05T18:50:24.160192808Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-12-05T18:50:24.160200249Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-12-05T18:50:24.160502962Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458 pid=14017 runtime=io.containerd.runc.v2
time="2022-12-05T18:50:25.024688167Z" level=error msg="loading cgroup for 14036" error="cgroups: cannot find cgroup mount destination"
time="2022-12-05T18:50:25.034064808Z" level=error msg="loading cgroup for 14036" error="cgroups: cannot find cgroup mounStarting app ... done
mwoodpatrick@Alpine-Test:~/projects/git/docker-compose-test (master)$ INFO[2022-12-05T18:50:25.496890152Z] shim disconnected                             id=7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458
INFO[2022-12-05T18:50:25.496917702Z] ignoring event                                container=7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
WARN[2022-12-05T18:50:25.496976566Z] cleaning up after shim disconnected           id=7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458 namespace=moby
INFO[2022-12-05T18:50:25.497002997Z] cleaning up dead shim
WARN[2022-12-05T18:50:25.504492542Z] cleanup warnings time="2022-12-05T18:50:25Z" level=info msg="starting signal loop" namespace=moby pid=14147 runtime=io.containerd.runc.v2

**Comment by Biswa96** [comment]
The docker container probably does not fails.

```
y:~/docker-compose-test$ docker-compose start app
Starting app ... done
y:~/docker-compose-test$ echo $?
0
```

The long messages are from dockerd logs. Try to run dockerd in separate console/terminal window.

**Comment by mwoodpatrick** [comment]
That still fails I'm attaching a log. I do see the error

time="2022-12-05T19:07:34.224051823Z" level=error msg="loading cgroup for 1816" error="cgroups: cannot find cgroup mount destination"
time="2022-12-05T19:07:34.225418732Z" level=error msg="loading cgroup for 1822" error="cgroups: cannot find cgroup mount destination"
time="2022-12-05T19:07:34.232885173Z" level=error msg="loading cgroup for 1822" error="cgroups: cannot find cgroup mount destination"
time="2022-12-05T19:07:34.233182224Z" level=error msg="loading cgroup for 1816" error="cgroups: cannot find cgroup mount destination"
time="2022-12-05T19:07:34.627326173Z" level=info msg="ignoring event" container=7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
time="2022-12-05T19:07:34.628226795Z" level=info msg="shim disconnected" id=7c398ad6c776cedebdae230aab2dd4db85a42585176f277625a661bdc3259458

[dockerd.log](https://github.com/microsoft/WSL/files/10157185/dockerd.log)

**Comment by Biswa96** [comment]
* Are you using the WSL from Window Store?
* Are you using the system provided Linux kernel?
* Did you change/add any Linux kernel command line option?

I am using the Linux kernel in WSL from Windows Store.

**Comment by mwoodpatrick** [comment]
I am using WSL version: 1.0.3.0, I am using the system-provided Linux kernel and I did not change any Linux kernel command line options

**Comment by Biswa96** [comment]
Just wondering, how did you fix the issue?
