### ISSUE TITLE
`apt upgrade` nonfunctional after successful `do-release-upgrade` from Jammy (22.04) to Kinetic (22.10)

### ISSUE THREAD

**Issue by PHR16384** [microsoft/WSL#9269]
### Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Ubuntu 22.10

### Other Software

WSL installed and running via "Ubuntu On Windows" Store app

### Run my normal day-to-day Linux software update **BASH script**:
(_filled with lots of just-in-cases tacked on from years of using WSL like a commandline-only Ubuntu Virtualbox_)

`$ sudo "PATH=$PATH" bash update.sh`

```
#!/bin/bash

dpkg --configure -a   # resume any interrupted installations
dpkg --configure -a --force-depends   # try to make dpkg stop whining

apt-get check  # no "apt check"??

# apt-fast obsolete?  regular apt no longer takes forever
apt update
apt upgrade -y
# apt full-upgrade -y

apt update --fix-missing
apt upgrade --fix-missing -y
# apt full-upgrade --fix-missing -y

apt install --fix-broken

apt autoremove -y
apt autoclean
```

### Script runs, all commands succeed, all installed Linux software updated:

```
[sudo] password for ____:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Get:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
Get:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease [99.9 kB]
Get:5 http://security.ubuntu.com/ubuntu kinetic-security/main amd64 Packages [112 kB]
Get:6 http://security.ubuntu.com/ubuntu kinetic-security/main Translation-en [32.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu kinetic-updates/main amd64 Packages [126 kB]
Get:8 http://archive.ubuntu.com/ubuntu kinetic-updates/restricted amd64 Packages [133 kB]
Get:9 http://archive.ubuntu.com/ubuntu kinetic-updates/universe amd64 Packages [60.0 kB]
Get:10 http://archive.ubuntu.com/ubuntu kinetic-updates/multiverse amd64 Packages [4,948 B]
Fetched 784 kB in 8s (94.2 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
...
(etc. etc. etc.)
```

### After upgrading to Kinetic (22.10), all `apt upgrade` attempts, scripted or typed manually, fail with "Could not read response to hello message from hook"; pending upgrades get marked "not upgraded" as though held back: 

```
...
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
E: Could not read response to hello message from hook [ ! -f /usr/lib/ubuntu-advantage/apt-esm-json-hook ] || /usr/lib/ubuntu-advantage/apt-esm-json-hook || true: Success
E: Could not read response to hello message from hook [ ! -f /usr/lib/ubuntu-advantage/apt-esm-json-hook ] || /usr/lib/ubuntu-advantage/apt-esm-json-hook || true: Success
Hit:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease
...
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

### Diagnostic Logs

I've confirmed that it's specifically `apt upgrade` that fails, since my alternate forced-update script (do `apt install [package] --fix-broken --fix-missing -y` for every package in `apt list --upgradable`) succeeds in fully updating all software.

Also, I've read the other WSL Issues with `apt` throwing the same kind of hook response error, with the solution to delete the offending script.  **That's not an option for me -- `/usr/lib/ubuntu-advantage/apt-esm-json-hook` doesn't exist.**

Other solutions unsuccessfully attempted:
- reinstall `apt`
- reinstall `ubuntu-advantage-tools` (the only `ubuntu-advantage*` package installed)
- close and reopen the Ubuntu On Windows app
- restart WSL via `wsl --shutdown`
- restart the LxssManager service

**Comment by watchanan554** [comment]
> ### Version
> 
> Microsoft Windows [Version 10.0.19045.2251]
> 
> ### WSL Version
> 
> - [ ] WSL 2
> - [X] WSL 1
> 
> ### Kernel Version
> 
> 4.4.0-19041-Microsoft
> 
> ### Distro Version
> 
> Ubuntu 22.10
> 
> ### Other Software
> 
> WSL installed and running via "Ubuntu On Windows" Store app
> 
> ### Repro Steps
> 
> ### Run my normal day-to-day Linux software update **BASH script**:
> (_filled with lots of just-in-cases tacked on from years of using WSL like a commandline-only Ubuntu Virtualbox_)
> 
> `$ sudo "PATH=$PATH" bash update.sh`
> 
> ```
> #!/bin/bash
> 
> dpkg --configure -a   # resume any interrupted installations
> dpkg --configure -a --force-depends   # try to make dpkg stop whining
> 
> apt-get check  # no "apt check"??
> 
> # apt-fast obsolete?  regular apt no longer takes forever
> apt update
> apt upgrade -y
> # apt full-upgrade -y
> 
> apt update --fix-missing
> apt upgrade --fix-missing -y
> # apt full-upgrade --fix-missing -y
> 
> apt install --fix-broken
> 
> apt autoremove -y
> apt autoclean
> ```
> 
> ### Expected Behavior
> 
> ### Script runs, all commands succeed, all installed Linux software updated:
> 
> ```
> [sudo] password for ____:
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Get:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease [109 kB]
> Hit:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
> Get:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease [109 kB]
> Get:4 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease [99.9 kB]
> Get:5 http://security.ubuntu.com/ubuntu kinetic-security/main amd64 Packages [112 kB]
> Get:6 http://security.ubuntu.com/ubuntu kinetic-security/main Translation-en [32.2 kB]
> Get:7 http://archive.ubuntu.com/ubuntu kinetic-updates/main amd64 Packages [126 kB]
> Get:8 http://archive.ubuntu.com/ubuntu kinetic-updates/restricted amd64 Packages [133 kB]
> Get:9 http://archive.ubuntu.com/ubuntu kinetic-updates/universe amd64 Packages [60.0 kB]
> Get:10 http://archive.ubuntu.com/ubuntu kinetic-updates/multiverse amd64 Packages [4,948 B]
> Fetched 784 kB in 8s (94.2 kB/s)
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> 1 package can be upgraded. Run 'apt list --upgradable' to see it.
> ...
> (etc. etc. etc.)
> ```
> 
> ### Actual Behavior
> 
> ### All commands succeed _except_ `apt upgrade`, which claims "Could not read response to hello message from hook"; pending upgrades get marked "not upgraded": 
> 
> ```
> ...
> 1 package can be upgraded. Run 'apt list --upgradable' to see it.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Calculating upgrade... Done
> E: Could not read response to hello message from hook [ ! -f /usr/lib/ubuntu-advantage/apt-esm-json-hook ] || /usr/lib/ubuntu-advantage/apt-esm-json-hook || true: Success
> E: Could not read response to hello message from hook [ ! -f /usr/lib/ubuntu-advantage/apt-esm-json-hook ] || /usr/lib/ubuntu-advantage/apt-esm-json-hook || true: Success
> Hit:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease
> ...
> 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
> ```
> 
> ### Diagnostic Logs
> 
> I've confirmed that it's specifically `apt upgrade` that fails, since my alternate forced-update script (do `apt install [package] --fix-broken --fix-missing -y` for every package in `apt list --upgradable`) succeeds in fully updating all software.
> 
> Also, I've read the other WSL Issues with `apt` throwing the same kind of hook response error, with the solution to delete the offending script.  **That's not an option for me -- `/usr/lib/ubuntu-advantage/apt-esm-json-hook` doesn't exist.**
> 
> Other solutions unsuccessfully attempted:
> - reinstall `apt`
> - reinstall `ubuntu-advantage-tools` (the only `ubuntu-advantage*` package installed)
> - close and reopen the Ubuntu On Windows app
> - restart WSL via `wsl --shutdown`
> - restart the LxssManager service

**Comment by elsaco** [comment]
@PHR16384 you jumped from an LTS to a non-LTS distro. Not recommended!

Try deleting `/etc/atp/apt.conf.d/20apt-esm-hook.conf` and see if `apt upgrade` finishes w/out errors. Make a backup first. Also, if you look into this file you'll see the reference to `apt-esm-json-hook`

If you want to run Kinetic grab an image from http://cloud-images.ubuntu.com/wsl/kinetic/current/ and import into WSL.

**Comment by PHR16384** [comment]
@elsaco  That seems to have done it, `apt upgrade` is working again.  Thanks!

**Comment by mattpackwood** [comment]
I do not have a `/etc/atp/apt.conf.d/20apt-esm-hook.conf` file to delete

**Comment by mattpackwood** [comment]
Slaps forehead with palm of hand....

**Comment by PHR16384** [comment]
Can confirm this is still a thing that can happen, FYI.  An update to Apache recreated 20apt-esm-hook.conf (with a prompt to keep or replace the user-made changes to the conf file)
