### ISSUE TITLE
No tracepoint events

### ISSUE THREAD

**Issue by CSWYF3634076** [microsoft/WSL#9270]
### Version

Microsoft Windows [版本 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Distro Version

Ubuntu 22.04

### Repro Steps

The following problems occur when I use ebpf tracepoint
![image](https://user-images.githubusercontent.com/58356743/205685497-cd9a7705-2fbc-462a-a9d7-d4600364d8a2.png)
Then I check tracepoint event . `ls /sys/kernel/debug/traceing/events`
![image](https://user-images.githubusercontent.com/58356743/205685770-d5771348-1198-4639-8d97-6c40ae250462.png)
------------------------------------------
Default CONFIG_DEBUG_INFO_BTF=n ?

### Expected Behavior

`ls /sys/kernel/debug/traceing/events` 
![image](https://user-images.githubusercontent.com/58356743/205686012-0ad76a13-8d89-437b-a929-b2208cd51af5.png)

### Actual Behavior

`ls /sys/kernel/debug/traceing/events` 
![image](https://user-images.githubusercontent.com/58356743/205686128-b9265cb4-a7f4-4b53-95b5-34b392063a2b.png)

**Comment by elsaco** [comment]
@CSWYF3634076 what version of WSL2 are you using? That's an old kernel! With kernel `5.15.74.2` that's included in WSL2 1.0.0 both `CONFIG_DEBUG_INFO=y` and `CONFIG_DEBUG_INFO_BTF=y` are set.

Output of `/sys/kernel/debug/tracing/events` dir:

```
tux@eleven:~/foo$ sudo ls /sys/kernel/debug/tracing/events
9p            compaction    fib           hyperv       jbd2       neigh    page_isolation  rseq    swiotlb   workqueue
alarmtimer    cpuhp         fib6          i2c          kmem       net      pagemap         rtc     syscalls  writeback
block         dev           filelock      initcall     kvm        netfs    percpu          sched   task      x86_fpu
bpf_test_run  dma_fence     filemap       intel_iommu  kvmmmu     netlink  power           scsi    tcp       xdp
bpf_trace     drm           fscache       iomap        migrate    netvsc   printk          sctp    thermal   xfs
bridge        enable        fs_dax        iommu        mmap       nfs      qdisc           signal  timer     xfs_scrub
btrfs         erofs         ftrace        io_uring     mmap_lock  nfs4     ras             skb     tlb
cgroup        error_report  header_event  irq          module     nfsd     raw_syscalls    smbus   udp
cifs          exceptions    header_page   irq_matrix   msr        nmi      rcu             sock    vmscan
clk           ext4          huge_memory   irq_vectors  napi       oom      rpcgss          sunrpc  vsyscall
```

WSL info used for testing:

```
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.900
```

**Comment by CSWYF3634076** [comment]
@elsaco Thank you for your advice. I replaced the kernel 5.15.79.1. BTF related content is available, but the tracepoint path still has no content.
The process of replacing the kernel is as follows
![image](https://user-images.githubusercontent.com/58356743/205846689-4fd1c3f1-a99f-4d02-b2eb-3081051d9752.png)
```sh
cd WSL2-Linux-Kernel-linux-msft-wsl-5.15.79.1
make -j8
```
Then modify the .wslconfig file
![image](https://user-images.githubusercontent.com/58356743/205847074-ed13336d-6c28-487e-bf69-835991dd95d5.png)

Restart wsl

![image](https://user-images.githubusercontent.com/58356743/205847409-5c0a58f4-821d-4379-a30b-658c930d0644.png)

**Comment by OneBlue** [comment]
@CSWYF3634076: `/sys/kernel/debug/` needs to be mounted.
You can do this via `mount -t debugfs none /sys/kernel/debug/` 

Closing since this is fixed in a more recent kernel.
