### ISSUE TITLE
[WIN11 22H2 WSL2]failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by JivinDotL** [microsoft/WSL#9272]
I had installed  2022-11 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5020044)

root@LAPTOP-UDGOEVA7:~/codes# export TF_ENABLE_ONEDNN_OPTS=0
root@LAPTOP-UDGOEVA7:~/codes# python tf_gpu_test.py
2022-12-06 13:53:26.782306: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From tf_gpu_test.py:3: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2022-12-06 13:53:27.576240: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-06 13:53:27.591033: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-12-06 13:53:27.591075: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (LAPTOP-UDGOEVA7): /proc/driver/nvidia/version does not exist

root@LAPTOP-UDGOEVA7:~# nvidia-smi
Tue Dec  6 14:06:42 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 522.25       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8    14W /  N/A |    572MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

**Comment by iourit** [comment]
@JivinDotL 
Are you running TensorFlow and nvidia-smi from the same WSL window?

**Comment by JivinDotL** [comment]
yes.
-----wsl2 ubuntu 22.04-------
root@LAPTOP-UDGOEVA7:~# nvidia-smi
Fri Dec  9 19:55:26 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 522.25       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8    17W /  N/A |    603MiB /  6144MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

-----widows 11-------PowerShell
PS C:\Users\Jivin> nvidia-smi
Fri Dec  9 19:55:14 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.25       Driver Version: 522.25       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P0    28W /  N/A |    591MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       668    C+G   ...8bbwe\WindowsTerminal.exe    N/A      |
|    0   N/A  N/A      3572    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      5068    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      5308    C+G   ...n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A     10656    C+G   ...e\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A     11860    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     14988    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     15072    C+G   ...cd70vzyy\ArmouryCrate.exe    N/A      |
|    0   N/A  N/A     15756    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     16724    C+G   ...perience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     17492    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     18276    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     18492    C+G   ...462.44\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     19944    C+G   ...8bbwe\WindowsTerminal.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by JivinDotL** [comment]
PS C:\WINDOWS\System32\lxss\lib> dir


    Directory: C:\WINDOWS\System32\lxss\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/6/2022  12:54 PM         149912 libcuda.so
-a----         12/6/2022  12:54 PM         149912 libcuda.so.1
-a----         12/6/2022  12:54 PM         149912 libcuda.so.1.1
-a----          5/7/2022   1:20 PM         789192 libd3d12.so
-a----          5/7/2022   1:20 PM        5913128 libd3d12core.so
-a----          5/7/2022   1:20 PM         829248 libdxcore.so
-a----         12/6/2022  12:54 PM        8989896 libnvcuvid.so
-a----         12/6/2022  12:54 PM        8989896 libnvcuvid.so.1
-a----         12/6/2022  12:54 PM       14551728 libnvdxdlkernels.so
-a----         12/6/2022  12:54 PM         514664 libnvidia-encode.so
-a----         12/6/2022  12:54 PM         514664 libnvidia-encode.so.1
-a----         12/6/2022  12:54 PM         222944 libnvidia-ml.so.1
-a----         12/6/2022  12:54 PM         358864 libnvidia-opticalflow.so
-a----         12/6/2022  12:54 PM         358864 libnvidia-opticalflow.so.1
-a----         12/6/2022  12:54 PM          68560 libnvoptix.so.1
-a----         12/6/2022  12:54 PM       60194248 libnvwgf2umx.so
-a----         12/6/2022  12:54 PM         630224 nvidia-smi

**Comment by JivinDotL** [comment]
https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl
https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by JivinDotL** [comment]
root@LAPTOP-UDGOEVA7:~# nvidia-smi
Wed Dec 14 21:46:40 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.65       Driver Version: 527.56       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8    10W / 115W |     33MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
|    0   N/A  N/A        27      G   /Xwayland                       N/A      |
|    0   N/A  N/A        33      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
root@LAPTOP-UDGOEVA7:~# sudo docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Ampere" with compute capability 8.6

> Compute 8.6 CUDA device: [NVIDIA GeForce RTX 3060 Laptop GPU]
30720 bodies, total time for 10 iterations: 27.579 ms
= 342.182 billion interactions per second
= 6843.649 single-precision GFLOP/s at 20 flops per interaction
root@LAPTOP-UDGOEVA7:~#

**Comment by JivinDotL** [comment]
root@LAPTOP-UDGOEVA7:~# **docker run -it --gpus all -p 8888:8888 tensorflow/tensorflow:latest-gpu-py3-jupyter**
Unable to find image 'tensorflow/tensorflow:latest-gpu-py3-jupyter' locally
latest-gpu-py3-jupyter: Pulling from tensorflow/tensorflow
7ddbc47eeb70: Pull complete
c1bbdc448b72: Pull complete
8c3b70e39044: Pull complete
45d437916d57: Pull complete
d8f1569ddae6: Pull complete
85386706b020: Pull complete
ee9b457b77d0: Pull complete
bebfcc1316f7: Pull complete
644140fd95a9: Pull complete
d6c0f989e873: Pull complete
7a8e64f26211: Pull complete
c33b03e4dd22: Pull complete
bca93af797c1: Pull complete
47f6c197be35: Pull complete
e5da48aa9554: Pull complete
ca68d98a90c4: Pull complete
2059de27f7c8: Pull complete
55d02aea1458: Pull complete
32162ecb0c59: Pull complete
47520dc72e8e: Pull complete
3dafed94e1f2: Pull complete
dc228e76e4f0: Pull complete
2c6922dc5a5f: Pull complete
a960e6d108fd: Pull complete
6818a780ae00: Pull complete
06dfbeeed7ba: Pull complete
5890e026a0a0: Pull complete
eeddfe30f3d2: Pull complete
187170305445: Pull complete
2e20a8960c42: Pull complete
9f1bf726c909: Pull complete
Digest: sha256:901b827b19d14aa0dd79ebbd45f410ee9dbfa209f6a4db71041b5b8ae144fea5
Status: Downloaded newer image for tensorflow/tensorflow:latest-gpu-py3-jupyter

________                               _______________
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ /
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

[I 13:56:41.252 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
[I 13:56:41.382 NotebookApp] Serving notebooks from local directory: /tf
[I 13:56:41.382 NotebookApp] The Jupyter Notebook is running at:
[I 13:56:41.382 NotebookApp] http://0bc7e69f12c6:8888/?token=b560329b2f554e58288a70fc0a7017b629a08f48f19ae879
[I 13:56:41.382 NotebookApp]  or http://127.0.0.1:8888/?token=b560329b2f554e58288a70fc0a7017b629a08f48f19ae879
[I 13:56:41.382 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by JivinDotL** [comment]
import tensorflow as tf
version = tf.__version__
gpu_ok = tf.config.list_physical_devices('GPU')
print("tf version:",version,"\nuse GPU",gpu_ok)
------------------------------------------------------
tf version: 2.1.0 
use GPU [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

<img width="448" alt="image" src="https://user-images.githubusercontent.com/45867423/207615870-a584a055-d6e0-40c4-b146-9fe3af17022e.png">
