### ISSUE TITLE
Unable to install WSL from store

### ISSUE THREAD

**Issue by andreasWallnerIFX** [microsoft/WSL#9273]
### Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 22.04

### Other Software

None

### Repro Steps

- Remove "Windows Subsystem for Linux"  as a Windows Feature via `dism /online /Disable-Feature /featurename:Microsoft-Windows-Subsystem-Linux /Remove`
- reboot
- Open Windows store via aka.ms/wslstorepage, install WSL
- reboot
- check if new wsl is installed from store via `wsl --version` -> version is not a known command (indicating I'm not using WSL from the store?)
- install via `wsl --install -d Ubuntu`
- reboot
- check WSL windows feature via `dism /online /get-features` -> Windows Feature has been activated
- `wsl --update` -> No updates available, reports kernel version `5.10.102.1`
- looking at `/mnt` in Ubuntu it seems that WSLg is not bundled

(all commands execute in powershell with admin rights)

### Expected Behavior

As hinted to in https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps WSL should be installed as an App, bundling WSLg

### Actual Behavior

As shown above it looks to me like wsl is always installed as a Windows Feature, not as an App. Therefore an version of WSL is installed that does not bundle WSLg

**Comment by swebs** [comment]
Do you have [KB5020030](https://support.microsoft.com/en-us/topic/november-15-2022-kb5020030-os-builds-19042-2311-19043-2311-19044-2311-and-19045-2311-preview-237a9048-f853-4e29-a3a2-62efdbea95e2) installed? It is required as mentioned here: https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/

**Comment by andreasWallnerIFX** [comment]
> Do you have [KB5020030](https://support.microsoft.com/en-us/topic/november-15-2022-kb5020030-os-builds-19042-2311-19043-2311-19044-2311-and-19045-2311-preview-237a9048-f853-4e29-a3a2-62efdbea95e2) installed?

Thanks, you were correct - I did not have the update installed. Thanks for the pointer!
