### ISSUE TITLE
Cannot downgrade WSL 1.0.3.0 to 1.0.0.0

### ISSUE THREAD

**Issue by colemar** [microsoft/WSL#9274]
### Version

Windows version: 10.0.19045.2311

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.79.1

### Distro Version

Irrelevant

### Other Software

```
PS C:\Users\colem> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2311
```

### Repro Steps

Attempting to downgrade to WSL 1.0.0.0 to see if issue #9261 still persist.
Download [Microsoft.WSL_1.0.0.0_x64_ARM64.msixbundle](https://github.com/microsoft/WSL/releases/tag/1.0.0).
Launch it.
It apparently hangs forever. I leaved it run (?) and when I went back about 30 minutes later the install window was gone but WSL version was still 1.0.3.0.
See attached images.
![image](https://user-images.githubusercontent.com/3066000/205999818-85932c7f-5b86-4260-93a0-b1235cbf4d3b.png)
(click on **Reinstall**)
![image](https://user-images.githubusercontent.com/3066000/205999916-16d8f244-c499-49e1-a544-136ff30a7168.png)
(click on **Reinstall**)
![image](https://user-images.githubusercontent.com/3066000/206000079-ace2372c-d454-4733-ad81-194e04be670d.png)
Wait... nothing happens.

### Expected Behavior

WSL version reverts to 1.0.0.0

### Actual Behavior

WSL version stays at 1.0.3.0

**Comment by OneBlue** [comment]
Thank you for reporting this @colemar.

Instead of using the UI, can you try installing the package via `Add-AppxPackage /path/to/package` in an elevated powershell ?

**Comment by colemar** [comment]
```
PS C:\Users\colem\Downloads> Add-AppxPackage Microsoft.WSL_1.0.0.0_x64_ARM64.msixbundle
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher version of this package is already installed.
Impossibile installare il pacchetto MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe. La versione del pacchetto è la 1.0.0.0. Una versione
successiva del pacchetto (1.0.3.0) è già installata.
NOTE: For additional information, look for [ActivityId] 626ecd06-09cf-0000-d528-6f62cf09d901 in the Event Log or use the command line Get-AppPackageLog -ActivityID
626ecd06-09cf-0000-d528-6f62cf09d901
At line:1 char:1
+ Add-AppxPackage Microsoft.WSL_1.0.0.0_x64_ARM64.msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\colem\...RM64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by OneBlue** [comment]
@colemar: The application needs to be uninstalled first.

You can do that via: 

```
$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers
Remove-AppxPackage $Package -AllUsers
```

**Comment by colemar** [comment]
Does uninstalling WSL app destroy the linux distros?
If so, can I export and reimport a distro?

**Comment by OneBlue** [comment]
> Does uninstalling WSL app destroy the linux distros? If so, can I export and reimport a distro?

No it doesn't. Removing Store WSL does not remove the distros and they will still be there once the re-install the app.

**Comment by colemar** [comment]
Done, thank you.
```
PS C:\Users\colem> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2311
```
