### ISSUE TITLE
<path> is not accessible from Windows explorer

### ISSUE THREAD

**Issue by webian** [microsoft/WSL#9282]
### Version

Windows 11 Pro 22621.900

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.74.2-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

### Distro Version

Ubuntu 20.04

### Repro Steps

If I try to browse my WSL from Windows Explorer, it often gives me permission errors as in the table below. The Windows user has the same name as the Linux user: tom
Linux user 'tom' is in the 'www-pub' group.

```
Linux path and permissions                       Accessible from Win?   Writable from Win?
------------------------------------------------------------------------------------------
drwxr-xr-x root     root    var/                 Y                      N
drwxrwsrwx www-data www-pub var/www/             Y                      Y
drwxrwsr-- www-data www-pub var/www/html/        Y                      N
drwxrws--- tom      www-pub var/www/html/test/   N                      n/a
```

Seems like inconsistent behavior to me.

### Expected Behavior

```
Linux path and permissions                       Accessible from Win?   Writable from Win?
------------------------------------------------------------------------------------------
drwxr-xr-x root     root    var/                 Y                      N
drwxrwsrwx www-data www-pub var/www/             Y                      Y
drwxrwsr-- www-data www-pub var/www/html/        Y                      Y
drwxrws--- tom      www-pub var/www/html/test/   Y                      Y
```

### Actual Behavior

See 'Repro Steps'.

**Comment by webian** [comment]
Also it doesn't allow me to browse `/var/www/html/test` until I set x for others for `/var/www/html/`:
`sudo chmod o+x /var/www/html/`
and, after this setting, I can also write in `/var/www/html/test` even if others can't write `/var/www/html/` but probably because `/var/www/html/test` is owned by me (tom)

**Comment by OneBlue** [comment]
Thanks for reporting this @webian. What's the default user and groups of your WSL distro ?

Can you share the output of `wsl.exe groups` and `wsl.exe whoami` ?

**Comment by webian** [comment]
```
PS D:\Users\tom> wsl.exe groups
tom adm dialout cdrom floppy sudo audio dip video plugdev netdev www-pub
```
```
PS D:\Users\tom> wsl.exe whoami
tom
```

A special configuration of my Windows 11 is that user folders are on partition D: instead of C:. Could this affect?

**Comment by webian** [comment]
WOW! LOL! Great way to fix bugs! /s

**Comment by OneBlue** [comment]
Thanks for the details @webian.

I confirm I can reproduce the issue. Digging into the plan9 server logic, I can tell that this is a limitation of the \\wsl.localhost at the moment: Additional groups are not processed when accessing files, which is why you're getting access denied

**Comment by nietzscheanic** [comment]
@OneBlue a reported issue since nearly 2.5 years - and a really annoying one 😢 

https://github.com/microsoft/WSL/issues/5987

**Comment by nietzscheanic** [comment]
@SvenGroot maybe something you could fix with some magic
