### ISSUE TITLE
Intel HAXM for Android development cannot be run unless hypervisorlaunchtype off and machine restarted

### ISSUE THREAD

**Issue by gregbown** [microsoft/WSL#9288]
### Version

10.0.22621.819

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04.1 LTS

### Other Software

Intel Hardware Accelerated Execution Manager (HAXM)

### Repro Steps

To run WSL
bcdedit /set hypervisorlaunchtype Auto
restart
result hypervisorlaunchtype auto --> enables WSL2 & disables HAXM

To run Intel Hardware Accelerated Execution Manager (HAXM)
bcdedit /set hypervisorlaunchtype off
restart
result hypervisorlaunchtype off --> disables WSL2 & enables HAXM

### Expected Behavior

In addition to expected, I might say desired behavior

Ideal option/behavior
A way to run both services without disabling either one

Somewhat improved behavior
A way to toggle launch type that does not require a restart

### Actual Behavior

bcdedit /set hypervisorlaunchtype Auto
restart
WSL2 working properly
HAXM fails to start
sc query intelhaxm
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
sc start intelhaxm
[SC] StartService FAILED 31:

**Comment by OneBlue** [comment]
Thanks for reporting this @gregbown.

Unfortunately, this is not something that we can solve: Conflicting hypervisors can't be running at the same time. If you need both WSL and another hypervisor running.
