### ISSUE TITLE
WSL :  Explorer failed on folder mounted by WSL sshfs 

### ISSUE THREAD

**Issue by fredmo** [microsoft/WSL#9291]
### Version

Microsoft Windows [version 10.0.22621.900]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux XXXX 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Distro Version

Release:        22.04

### Repro Steps

In WSL2 , I mount a folder : 
   sshfs 192.168.1.2:distant_folder /home/myname/local_folder
   => it s working

Now, in Windows Explorer, I navigate to \\wsl.localhost\Ubuntu\home\myname  , 
I try to open "local_folder" , 
I have : 
![image](https://user-images.githubusercontent.com/3090107/206705165-2b3db042-b68f-4aba-8802-5f14f1b8bfb1.png)

### Expected Behavior

navigation inside the local folder sshfs mounted by WSL should be accessible from the Windows Explorer

### Actual Behavior

right error : 
https://user-images.githubusercontent.com/3090107/206705165-2b3db042-b68f-4aba-8802-5f14f1b8bfb1.png

**Comment by OneBlue** [comment]
Thanks for reporting this @fredmo.

This is probably due to the namespacing difference between elevated and non-elevated WSL. Can you try to mount the folder inside `/mnt/wsl` ? This folder is shared between all namespaces.

**Comment by fredmo** [comment]
> Thanks for reporting this @fredmo.
> 
> This is probably due to the namespacing difference between elevated and non-elevated WSL. Can you try to mount the folder inside `/mnt/wsl` ? This folder is shared between all namespaces.


I confirm if the mount is done on /mnt/XXX  , it s working correctly. Explorer sees the content of the sshfs mount.
The issue is present when the mount is on : /mnt/user/XXX


Regards,
Frédéric
