### ISSUE TITLE
WSL and WSLv2 security offerings 

### ISSUE THREAD

**Issue by ozduran** [microsoft/WSL#9302]
Hello Team 
I have a general question related to how security is managed in WSL and WSLv2. Talking about policies, Antivirus, Antimalware, and anything that is normally applied to an organization to harden its cybersecurity. I checked the documentation available in GitHub but I did not find something related to it, is there anything available that could explain that part?

**Comment by craigloewen-msft** [comment]
Our current Enterprise security story can be found here: https://learn.microsoft.com/en-us/windows/wsl/enterprise

We're investigating ways to improve it, especially surrounding monitoring and managing WSL instances, if you have specific questions or concerns about setting up WSL with your Enterprise please reach out to me via email at: crloewen@microsoft.com

Thanks!
