### ISSUE TITLE
After installing a distro, when launching, get File system error (-2147416359), -l -v reports no distro installed

### ISSUE THREAD

**Issue by lampuiho** [microsoft/WSL#9305]
### Version

Microsoft Windows [Version 10.0.19044.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

20.04

### Repro Steps

Disable AppXSVC
Run following in a cmd
```
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\RuntimeBroker.exe" /v Debugger /d NUL /f
taskkill /im RuntimeBroker.exe /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ApplicationFrameHost.exe" /v Debugger /d NUL /f
taskkill /im ApplicationFrameHost.exe /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\backgroundTaskHost.exe" /v Debugger /d NUL /f
taskkill /im backgroundTaskHost.exe /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SystemSettings.exe" /v Debugger /d NUL /f
taskkill /im SystemSettings.exe /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\smartscreen.exe" /v Debugger /d NUL /f
taskkill /im smartscreen.exe /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchUI.exe" /v Debugger /d NUL /f
taskkill /im SearchUI.exe /f
wsl --install -d ubuntu20.04
```

### Expected Behavior

Should run properly

### Actual Behavior

Pops up error
![wsl_fail](https://user-images.githubusercontent.com/3599125/206898335-ff991a69-2212-4399-b58e-25cc0030eaaf.JPG)

**Comment by Biswa96** [comment]
> Disable AppXSVC

Please do not disable system services.

**Comment by Biswa96** [comment]
> It is a must because all Microsoft App Store features need to be disabled on my machine.

Then you can not use Linux distributions from Windows Store. Basically, anything under that WindowsApps directory won't work. You have to install the distributions manually with `wsl.exe --import` command. And then run them with wsl.exe command. The distribution launcher (here ubuntu2004.exe) also does not work because WindowsApps directory needs separate access permission.

**Comment by lampuiho** [comment]
I expected --install to work without Windows Store because it was built for that purpose. Anyway, I downloaded an appxbundle and unzipped it using 7zip. Running ubuntu.exe puts it in WSL1 mode. I will see if WSL1 has everything I need before trying to import it to run it in WSL2 mode.

**Comment by OneBlue** [comment]
> > Disable AppXSVC
> 
> Please do not disable system services.

Indeed without `AppXSVC` distribution apps will not run.

If you need to install apps without any Appx support, you can use `wsl.exe --import` to import a tar (see https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro#obtain-a-tar-file-for-the-distribution)
