### ISSUE TITLE
Win32 program recreating console and reopening stdout (to CONOUT$) causes io desync

### ISSUE THREAD

**Issue by LAK132** [microsoft/WSL#9308]
### Version

Microsoft Windows [Version 10.0.19043.2311]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.84-microsoft-standard

### Distro Version

Ubuntu 22.04

### Other Software

[Testing my own software](https://github.com/LAK132/lak), compiled with msvc. 

### Repro Steps

Have program print to the command line, fflush/std::flush/FlushFileBuffer/etc output io, free the current console, create and attach a new console, freopen_s stdout with CONOUT$, print more to the command line.

[This commit](https://github.com/LAK132/lak/commit/dcdbfe2d48174909a44f1adef77b5295e38429c7) contains some janky code that has repro'd the behaviour for me. `./win_setup.sh msvc && ./win_compile.sh && ./build/lak_test.exe --tests "alloc_attach_console"` in WSL2 (Ubuntu) should trigger it.

### Expected Behavior

The output shouldn't end up interlaced. The output looks correct when run with cmd, powershell and the new windows terminal:

```
D:\Repos\lak-migrate-dependencies>build\lak_test.exe --tests "alloc_attach_console"
testing alloc_attach_console
{
| DEBUG (D:\Repos\lak-migrate-dependencies\src\tests\win32/wrapper.cpp:102): hello, world!
| PASSED
}
All tests passed
```

### Actual Behavior

The initial output and the output after the reopen will end up interlaced, out of order or truncated (it seems to be random)

```
lak132@DESKTOP-45BQNFM:/mnt/d/Repos/lak-migrate-dependencies$ ./build/lak_test.exe --tests "alloc_attach_console"
testing alloc_attach_console
| DEBUG (D:\Repos\lak-migrate-dependencies\src\tests\win32/wrapper.cpp:102): hello, world!
| PASSED
}
All tests passed
```

```
lak132@DESKTOP-45BQNFM:/mnt/d/Repos/lak-migrate-dependencies$ zsh -c './build/lak_test.exe --tests "alloc_attach_console"'
| DEBUG (D:\Repos\lak-migrate-dependencies\src\tests\win32/wrapper.cpp:102): hello, world!
| PASSED
}
All tests passed
testing alloc_attach_console
{
```

**Comment by OneBlue** [comment]
Thanks for reporting this @LAK132.

The code you shared is quite a lot to go through. Can you scope down the issue and share and minimal repro program that we can use to root cause the issue? (Preferably without dependencies)
