### ISSUE TITLE
Can't install WSL from the command prompt

### ISSUE THREAD

**Issue by itsdoble** [microsoft/WSL#9314]
### Version

Microsoft Windows [Version 10.0.22621.819]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

wsl --list --online

### Expected Behavior

it should install list the available distributions.

### Actual Behavior

Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established Error code: Wsl/WININET_E_CANNOT_CONNECT

### Diagnostic Logs

C:\Users\User\Desktop>qq.bat
"WSL version (Might be help text if store WSL is not installed):"
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
Windows features:

FeatureName
-----------
Printing-PrintToPDFServices-Features
Printing-XPSServices-Features
LegacyComponents
DirectPlay
MSRDC-Infrastructure
MicrosoftWindowsPowerShellV2Root
MicrosoftWindowsPowerShellV2
NetFx4-AdvSrvs
NetFx4Extended-ASPNET45
WCF-Services45
WCF-TCP-PortSharing45
NetFx3
MediaPlayback
WindowsMediaPlayer
SearchEngine-Client-Package
WorkFolders-Client
Printing-Foundation-Features
Printing-Foundation-InternetPrinting-Client

HNS objects:
'hnsdiag' is not recognized as an internal or external command,
operable program or batch file.
Routing table:
===========================================================================
Interface List
 24...d4 5d 64 66 4c a8 ......Realtek PCIe GbE Family Controller #2
  7...0a 00 27 00 00 07 ......VirtualBox Host-Only Ethernet Adapter
  3...0a 00 27 00 00 03 ......VirtualBox Host-Only Ethernet Adapter #3
  9...c8 b2 9b 5d 9e be ......Microsoft Wi-Fi Direct Virtual Adapter #3
 17...ca b2 9b 5d 9e bd ......Microsoft Wi-Fi Direct Virtual Adapter #4
 22...c8 b2 9b 5d 9e bd ......Intel(R) Wireless-AC 9560 160MHz
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0     192.168.29.1   192.168.29.254     36
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      169.254.0.0      255.255.0.0         On-link    169.254.111.98    281
      169.254.0.0      255.255.0.0         On-link    169.254.54.106    281
   169.254.54.106  255.255.255.255         On-link    169.254.54.106    281
   169.254.111.98  255.255.255.255         On-link    169.254.111.98    281
  169.254.255.255  255.255.255.255         On-link    169.254.111.98    281
  169.254.255.255  255.255.255.255         On-link    169.254.54.106    281
     192.168.29.0    255.255.255.0         On-link    192.168.29.254    291
   192.168.29.254  255.255.255.255         On-link    192.168.29.254    291
   192.168.29.255  255.255.255.255         On-link    192.168.29.254    291
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link    169.254.111.98    281
        224.0.0.0        240.0.0.0         On-link    169.254.54.106    281
        224.0.0.0        240.0.0.0         On-link    192.168.29.254    291
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link    169.254.111.98    281
  255.255.255.255  255.255.255.255         On-link    169.254.54.106    281
  255.255.255.255  255.255.255.255         On-link    192.168.29.254    291
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
 22     51 ::/0                     fe80::7297:41ff:fed5:f35e
  1    331 ::1/128                  On-link
 22     51 2405:201:ac09:d079::/64  On-link
 22    291 2405:201:ac09:d079:7ce0:f1b5:5d5:4538/128
                                    On-link
 22    291 2405:201:ac09:d079:8542:56:858b:e041/128
                                    On-link
  7    281 fe80::/64                On-link
  3    281 fe80::/64                On-link
 22    291 fe80::/64                On-link
 22    291 fe80::3ba4:8383:e415:3d9b/128
                                    On-link
  3    281 fe80::9a28:d19c:839:c4af/128
                                    On-link
  7    281 fe80::cb8f:d634:aa3b:65b2/128
                                    On-link
  1    331 ff00::/8                 On-link
  7    281 ff00::/8                 On-link
  3    281 ff00::/8                 On-link
 22    291 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None
Deleting HNS network
Get-HnsNetwork : The term 'Get-HnsNetwork' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ Get-HnsNetwork | Where-Object {$_.Name -eq 'WSL'} | Remove-HnsNetwork
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HnsNetwork:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The Windows Subsystem for Linux service is stopping.
The Windows Subsystem for Linux service was stopped successfully.

Name               : HnsPacketCapture
CaptureMode        : SaveToFile
LocalFilePath      : C:\Users\User\Desktop\\packets.etl
MaxFileSize        : 250 MB
TraceBufferSize    : 0 KB
MaxNumberOfBuffers : 0
SessionStatus      : NotRunning

Name               : Microsoft-Windows-NDIS-PacketCapture
SessionName        : HnsPacketCapture
Level              : 5
MatchAnyKeyword    : 0xFFFFFFFFFFFFFFFF
MatchAllKeyword    : 0x0
CaptureType        : BothPhysicalAndSwitch
VmCaptureDirection : IngressAndEgress
MultiLayer         : False
LinkLayerAddress   : {}
EtherType          : {}
IpAddresses        : {}
IpProtocols        : {}
TruncationLength   : 128

Windows Subsystem for Linux has no installed distributions.

Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.

Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error code: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND
Press Ctrl+C to cancel the stop operation.
100%  [>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
The trace was successfully saved.

**Comment by OneBlue** [comment]
Thank you for reporting this @itsdoble. Does this reproduce consistently ? Based on the output it looks like an intermittent connection issue.

**Comment by ashish-atidiv** [comment]
I too get this error and tried below steps next. I am on a windows 11 machine.
- used windows features to enable WSL, restarted
- tried `wsl --status`, asked to enable next feature (in point below)
- used windows features to enable virtual machine platform, restarted
- tried `wsl --status` again, it asked to run `wsl --update`
After this WSL in installed. But if i run `wsl -l -o`, I get the same error as below.
![image](https://user-images.githubusercontent.com/120102046/207308417-0ccde57e-9f0e-42ab-87c5-c23c50ecfeda.png)

**Comment by ashish-atidiv** [comment]
Following up on the last post, I can see WSL installed in local machine. If i try to open...it gives me this error
![image](https://user-images.githubusercontent.com/120102046/207310006-d121c795-ae70-4cda-a126-38b38defb8c4.png)

**Comment by ashish-atidiv** [comment]
As an alternative, I installed Ubuntu app from Windows Store and that worked!

**Comment by NO-GAMENOLIFE** [comment]
so what happened did anyone got any solution?

**Comment by sivateja1995** [comment]
![image](https://user-images.githubusercontent.com/17886254/210100950-fbf3eca1-f1b6-4254-a682-af1db5f602a6.png)
same issue here

**Comment by ag011** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/53391954/213060934-b15534b3-9caf-43f7-af6b-c1a617a379c7.png">

**Comment by NO-GAMENOLIFE** [comment]
i got the solution. change your ip address for wifi or cable to google ip address(dns) and be sure to change ipv4 and ipv6 both. after that reinstall wsl.

**Comment by taoliu12** [comment]
I literally had a brief internet connection drop that caused this issue. So check your internet.

**Comment by mikerains** [comment]
One Windows 10, I am finding that DNS Servers include 2 that are ipv6 addresses.  I can open https://raw.githubusercontent.com in my browser, and I can curl it from wsl command line, but from WIndows Command Prompt, wsl --install Ubuntu fails with "Failed to fetch the list distribution".  

I suspect it all has to do with the DNS Name resolinv gto an IPv6 address that curl and the browser can handle but the wsl subsystem cannot?  

I just performed wsl --update, so I am on the latest WSL 2.

**Comment by omkar-kointrack** [comment]
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

I also facing this issue

**Comment by W1M0R** [comment]
I also get this issue:

![image](https://user-images.githubusercontent.com/618853/220268383-6fed7cb5-a10c-4adc-89f3-43ffc9324c60.png)

**Comment by Basit-Imam** [comment]
If you're in India and using JIO, change your operator, worked for me.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">

**Comment by ViratSrivastava** [comment]
> If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">

I can confirm that. JIO internet seems to be the issue for connection issue

**Comment by shortthirdman** [comment]
> If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">

@ViratSrivastava Just change the Preferred DNS and Alternate DNS in your Windows Settings for adapters (Jio) to use Google Public DNS (for both IPv4 and IPv6). Check here [Configure your network settings to use Google Public DNS](https://developers.google.com/speed/public-dns/docs/using)

**Comment by sultanmirza007** [comment]
![Screenshot 2023-06-09 085533](https://github.com/microsoft/WSL/assets/90542662/79d943cd-019f-4a2e-9d20-94defd212d4b)

Change your ipv4 and ipv6 addresses to Google DNS and it will work even on Jio

**Comment by patelabhilash** [comment]
> 

Can't believe this was the issue. it works!

**Comment by gauravjadhav-mjb** [comment]
yup it is issue with jio network :)

**Comment by rythmn1111** [comment]
> If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">

bro I literary have JioFiber AHHH what should I do

**Comment by patelabhilash** [comment]
> > If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">
> 
> bro I literary have JioFiber AHHH what should I do

it's a onetime thing. once installed WSL will work with jio. so, take help from any friend with a mobile hotspot. No need to ask such trivial things here. In worst case try proxy.

**Comment by dheeraj0000** [comment]
Gwtting error like this what can i do 

Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

**Comment by AbhishekAdiga** [comment]
> > If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">
> 
> @ViratSrivastava Just change the Preferred DNS and Alternate DNS in your Windows Settings for adapters (Jio) to use Google Public DNS (for both IPv4 and IPv6). Check here [Configure your network settings to use Google Public DNS](https://developers.google.com/speed/public-dns/docs/using)



> Getting error like this what can i do
> 
> Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

CHANGE THE NETWORK AND TRY IT , IT IS NOT WORKING ON JIO NETWORK.

**Comment by sultanmirza007** [comment]
> Getting error like this what can i do
> 
> Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT



Make sure you've changed ur  ipv4 and ipv6 addresses to Google DNS and it will work even on Jio....or else consider using any other network.

**Comment by thakrenikhil** [comment]
Try changing the network for me I switched to Airtel from Jio and then enabled Hyper-v and Vm under windows features. Problem was solved

**Comment by lipun12ka4** [comment]
I had the same problem. I am in Bengaluru and I am using Hathway. turned on my OpenVPN connection, and installed WSL, and disabled VPN. Everything , like apt from inside ubuntu works just fine, without VPN.

**Comment by Oluadepe** [comment]
> > > If you're in India and using JIO, change your operator, worked for me. <img alt="image" width="497" src="https://user-images.githubusercontent.com/52064250/221417295-9ef5a971-81fa-497a-b3ba-5c9abb89cb7a.png">
> > 
> > 
> > @ViratSrivastava Just change the Preferred DNS and Alternate DNS in your Windows Settings for adapters (Jio) to use Google Public DNS (for both IPv4 and IPv6). Check here [Configure your network settings to use Google Public DNS](https://developers.google.com/speed/public-dns/docs/using)
> 
> > Getting error like this what can i do
> > Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT
> 
> CHANGE THE NETWORK AND TRY IT , IT IS NOT WORKING ON JIO NETWORK.

Its not for Indians alone. If anyone is having issues just follow the instruction on how to change your DNS and it will work. I just did that from Nigerian and it worked

**Comment by DhineshAmbrose** [comment]
Use Any Vpn problem solved
<img width="621" alt="image" src="https://github.com/microsoft/WSL/assets/37982081/b59fe8b8-8c6f-46ab-a417-22aed55df5f4">

**Comment by Kishore-MK** [comment]
@DhineshAmbrose I did the same and it worked for me as well.

**Comment by rusty3699** [comment]
Potential Solutions to try:

1. Change DNS Servers - can switch to Google public DNS(8.8.8.8 and 8.8.4.4) for IPv4 and IPv6
2. Network-Specific Issues: If using Jio, consider switching the network or using a VPN. 
3. Install from Microsoft Store - if CLI fails, install wsl from Microsoft Store: this is Ubuntu 22.04.3 LTS[https://www.microsoft.com/store/productId/9PN20MSR04DW?ocid=pdpshare](url)

To Reinstall wsl using CLI:
Reinstall WSL 
wsl -l
wsl --unregister <distribution name>
wsl --shutdown
wsl --install
Restart the computer

**Comment by pklapperich** [comment]
So this is clearly a bug that lots of people are hitting. What information is required yet?

```
> nslookup raw.githubusercontent.com
Server:  UnKnown
Address:  127.0.0.2

Non-authoritative answer:
Name:    raw.githubusercontent.com
Addresses:  2606:50c0:8003::154
          2606:50c0:8002::154
          2606:50c0:8000::154
          2606:50c0:8001::154
          185.199.110.133
          185.199.111.133
          185.199.108.133
          185.199.109.133
          
> Invoke-WebRequest https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json


StatusCode        : 200
StatusDescription : OK
Content           : {
                        "Distributions": [
                            {
                                "Name": "Ubuntu",
                                "FriendlyName": "Ubuntu",
                                "StoreAppId": "9PDXGNCFSCZV",
                                "Amd64": true,
                                "Arm64": true,
                     ...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options,
                    nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 6271

> (Invoke-WebRequest https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json).Content | jq '.Distributions[] | select(.Name==\"Ubuntu\")'
{
  "Name": "Ubuntu",
  "FriendlyName": "Ubuntu",
  "StoreAppId": "9PDXGNCFSCZV",
  "Amd64": true,
  "Arm64": true,
  "Amd64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-220117.appx",
  "Arm64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-220117_ARM64.appx",
  "PackageFamilyName": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
}

> wsl --install -d ubuntu
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

> wsl -l -o
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/WININET_E_CANNOT_CONNECT
```

DNS seems to be working. `Invoke-Webrequest` can fetch the data. Browsers can load the URL. `wsl` can't. Why is `wsl` not able to reach it but other things can?

**Comment by pklapperich** [comment]
So this is clearly a bug that lots of people are hitting. What information is required yet?

```
> nslookup raw.githubusercontent.com
Server:  UnKnown
Address:  127.0.0.2

Non-authoritative answer:
Name:    raw.githubusercontent.com
Addresses:  2606:50c0:8003::154
          2606:50c0:8002::154
          2606:50c0:8000::154
          2606:50c0:8001::154
          185.199.110.133
          185.199.111.133
          185.199.108.133
          185.199.109.133
          
> Invoke-WebRequest https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json


StatusCode        : 200
StatusDescription : OK
Content           : {
                        "Distributions": [
                            {
                                "Name": "Ubuntu",
                                "FriendlyName": "Ubuntu",
                                "StoreAppId": "9PDXGNCFSCZV",
                                "Amd64": true,
                                "Arm64": true,
                     ...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options,
                    nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 6271

> (Invoke-WebRequest https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json).Content | jq '.Distributions[] | select(.Name==\"Ubuntu\")'
{
  "Name": "Ubuntu",
  "FriendlyName": "Ubuntu",
  "StoreAppId": "9PDXGNCFSCZV",
  "Amd64": true,
  "Arm64": true,
  "Amd64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-220117.appx",
  "Arm64PackageUrl": "https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu2204-220117_ARM64.appx",
  "PackageFamilyName": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
}

> wsl --install -d ubuntu
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT

> wsl -l -o
Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/WININET_E_CANNOT_CONNECT
```

DNS seems to be working. `Invoke-Webrequest` can fetch the data. Browsers can load the URL. `wsl` can't. Why is `wsl` not able to reach it but other things can? I can't change DNS servers, but DNS appears to be working.

**Comment by imjosh** [comment]
The solution for me was to uncheck IPV6 under my wifi adapter settings. Note that this doesn't disable IPV6, it causes Windows to prefer IPV4
![image](https://github.com/user-attachments/assets/179e463d-360b-4c05-bb9e-57cfa86eca9a)
