### ISSUE TITLE
UDP socket programming is not working - Data is not reaching wsl adapter

### ISSUE THREAD

**Issue by Jubin2607** [microsoft/WSL#9316]
### Version

Microsoft Windows [Version 10.0.19044.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Repro Steps

with windows are server , create a socket and try to send messages to wsl2

### Expected Behavior

message reaching wsl2 network adapter

### Actual Behavior

message not reaching wsl2 network adapter

**Comment by pmartincic** [comment]
Howdy, could you be a bit more specific, some more details? If you're trying to access via localhost:UDP that isn't currently implemented.

**Comment by Jubin2607** [comment]
Well I was trying to create a socket programming to communicate between Windows and WSL2 Ubuntu . Even though data has been send from the windows network adapter , the data is not getting received in WSL2 adapter

**Comment by pmartincic** [comment]
You really need to give me more detail. Knowing if the host is attempting to address localhost or the generated private address is example.

**Comment by Jubin2607** [comment]
It is trying to connect to a private address
