### ISSUE TITLE
[W10 22H2] Can't install WSL v1.0.1 and above on build >19041.0

### ISSUE THREAD

**Issue by rraihansaputra** [microsoft/WSL#9319]
### Version

Microsoft Windows [Version 10.0.19044.2251]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04.5

### Other Software

Docker Desktop

### Repro Steps

Try to install WSL v1.0.1 or above from Windows Store or available releases from this repository.

### Expected Behavior

WSL will install correctly as the build is later than 19041.0 which is listed in the store listing.

![image](https://user-images.githubusercontent.com/8604926/207282636-ac14a711-f97d-4f5c-b2cc-36b4d5e7604a.png)

### Actual Behavior

WSL seem to install correctly from the Store but will display this error when launched.

Installing manually from the release in the repository also results in the same error.

![image](https://user-images.githubusercontent.com/8604926/207281642-f12f052b-eb2c-4d54-bc3a-6dabf864bda7.png)

**Comment by Biswa96** [comment]
You need [KB5020030](https://support.microsoft.com/en-us/topic/november-15-2022-kb5020030-os-builds-19042-2311-19043-2311-19044-2311-and-19045-2311-preview-237a9048-f853-4e29-a3a2-62efdbea95e2).

**Comment by OneBlue** [comment]
As @Biswa96 pointed out, [This update package](https://support.microsoft.com/en-us/topic/november-15-2022-kb5020030-os-builds-19042-2311-19043-2311-19044-2311-and-19045-2311-preview-237a9048-f853-4e29-a3a2-62efdbea95e2) is required to run Store WSL.

**Comment by rraihansaputra** [comment]
Thank you for the information. Is there any plans to update the requirements on the Windows Store?

**Comment by Biswa96** [comment]
It is not clear in the 'Install WSL' page but the requirement can be found in 'Prerequisites' section. For the KB update requirement, this blog post may help https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
