### ISSUE TITLE
setsockopt with IP_TRANSPARENT return -1 with ': Protocol not available'

### ISSUE THREAD

**Issue by kuriel07** [microsoft/WSL#9329]
### Version

Microsoft Windows [Version 10.0.18363.1440]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-18362

### Distro Version

Ubuntu 18.04

### Other Software

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### Repro Steps

running normal socket program in C code (gcc compiler)

      int SocketFD = socket (AF_INET, SOCK_STREAM, IPPROTO_TCP);
	if (SocketFD == -1) {
			perror("https cannot create socket");
			exit(EXIT_FAILURE);
	}
	if (setsockopt(SocketFD, SOL_SOCKET, SO_REUSEADDR, (const char*)&reuse, sizeof(reuse)) < 0)
		perror("setsockopt(SO_REUSEADDR) failed\n");

	const char ip_trans_enable = 1;
	if(-1 == setsockopt(SocketFD, SOL_IP, IP_TRANSPARENT, (const char*)&ip_trans_enable, sizeof(ip_trans_enable))) {
		perror("setsockopt(IP_TRANSPARENT) failed\n");
		exit(EXIT_FAILURE);
	}

### Expected Behavior

setsockopt(SocketFD, SOL_IP, IP_TRANSPARENT, (const char*)&ip_trans_enable, sizeof(ip_trans_enable) should return 0

### Actual Behavior

setsockopt(IP_TRANSPARENT) failed   (return -1)
: Protocol not available

**Comment by Biswa96** [comment]
> Kernel Version
> Linux version 4.4.0-18362

You are probably not using WSL2. Also try to update to newer Windows 10 version if possible.
