### ISSUE TITLE
`wslhost` won't be killed by `wsl --shutdown`

### ISSUE THREAD

**Issue by scruel** [microsoft/WSL#9334]
### Version

10.0.22000.1335

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu-22.04

### Repro Steps

- Execute `wsl --shutdown`
- Run `taskmgr`
- wslhost.exe still alive.

Currently, `wslhost` will occupy the host local ports forwarded from WSL, even after executing the command `wsl --shutdown`.
Also, those died ports on WSL will not be released by `wslhost`, and it will keep occupying the host ports. This caused me to have to restart the entire WSL service.

### Expected Behavior

wslhost.exe should be killed.

### Actual Behavior

wslhost.exe still alive.

**Comment by mokeyish** [comment]
`wsl --shutdown` will reboot my physical machine somtimes.

**Comment by scruel** [comment]
> `wsl --shutdown` will reboot my physical machine somtimes.

I'm sorry, but I think you should consider raising a new issue for solving this.

**Comment by press0** [comment]
`wsl --shutdown` hangs on my windows 10 machine
