### ISSUE TITLE
After changing WSL to be installed from the Windows Store, running the Windows-installed Gradle from within WSL hangs on build

### ISSUE THREAD

**Issue by dandrei** [microsoft/WSL#9336]
### Version

Microsoft Windows [Version 10.0.19045.2364]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

Ubuntu 20.04.5 LTS

### Other Software

Gradle 7.5.1
openjdk 17.0.4.1 2022-08-12

### Repro Steps

Attempt to build a Java project using Gradle.

### Expected Behavior

The build process should complete successfully, like it did before I set WSL to be installed from the Windows Store.

### Actual Behavior

Calling:

    gradle.exe build -x test --warning-mode all

now hangs, until I switch to a Windows command line and run:

    taskkill /f /im java.exe

### Diagnostic Logs

[WslLogs-2022-12-15_10-52-17.zip](https://github.com/microsoft/WSL/files/10235390/WslLogs-2022-12-15_10-52-17.zip)
I started the log recording, ran the gradle build command, killed `java.exe` and waited for the build process to complete, then I ended the log recording.

**Comment by stewartadam** [comment]
Running into this too. Let me know if you need more logs.

**Comment by stewartadam** [comment]
Not sure if related but running `cmd.exe /C gradle.bat bootRun` inside of tmux causes a hang when tmux server or WSL exits. `gradle --status` shows STOPREQUESTED but none of the java.exe processes exit.
