### ISSUE TITLE
Unable to install any wsl distro.

### ISSUE THREAD

**Issue by jindalpratik** [microsoft/WSL#9345]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

N/A

### Repro Steps

Try to install any distro from the windows store.
After it downloads in the terminal step it shows.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007065d
Error: 0x8007065d Data supplied is of wrong type.

Press any key to continue...

```

### Expected Behavior

Distro installs as normal.

### Actual Behavior

Distro doesn't install.

### Diagnostic Logs

https://aka.ms/AAj0aqs

**Comment by furqanulaalam** [comment]
I am guessing that you are from India. The issue is caused due to ISP blockade. Reach out to your ISP for resolution. However, you should be able to install wsl through a VPN.

**Comment by jindalpratik** [comment]
> I am guessing that you are from India. If so, the issue is caused due to ISP blockade. Reach out to your ISP for resolution. Meanwhile, you should be able to install wsl through a VPN. 

I was already using a vpn so this probably shouldn't be the case, I'll give it a go with a different vpn just to be sure.
