### ISSUE TITLE
can not install ueberzug 

### ISSUE THREAD

**Issue by meicale** [microsoft/WSL#9359]
### Version

WSL 版本： 1.0.3.0 内核版本： 5.15.79.1 WSLg 版本： 1.0.47 MSRDC 版本： 1.2.3575 Direct3D 版本： 1.606.4 DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows版本： 10.0.22621.963

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

20.04

### Repro Steps

pip install ueberzug 

### Expected Behavior

build

### Actual Behavior

     reading manifest file 'ueberzug.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'ueberzug.egg-info/SOURCES.txt'
      copying ueberzug/lib/lib.sh -> build/lib.linux-x86_64-cpython-39/ueberzug/lib
      running build_ext
      building 'Xshm' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/Xshm
      gcc -pthread -B /home/bill/anaconda3/envs/python-ide/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/bill/anaconda3/envs/python-ide/include -I/home/bill/anaconda3/envs/python-ide/include -fPIC -O2 -isystem /home/bill/anaconda3/envs/python-ide/include -fPIC -I/home/bill/anaconda3/envs/python-ide/include/python3.9 -c Xshm/Xshm.c -o build/temp.linux-x86_64-cpython-39/Xshm/Xshm.o
      Xshm/Xshm.c:5:10: fatal error: X11/Xlib.h: No such file or directory
          5 | #include <X11/Xlib.h>
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ueberzug

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by zcobol** [comment]
@meicale you need to add the X header files. For Ubuntu install `libx11-dev` package.

**Comment by meicale** [comment]
Yes, thank you!
