### ISSUE TITLE
WSL (11) ERROR: UtilTranslatePathList:2671: Failed to translate

### ISSUE THREAD

**Issue by Newbie012** [microsoft/WSL#9360]
### Version

Microsoft Windows [Version 10.0.22000.1335]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Release:        20.04

### Other Software

Visual Studio Code (1.74.1)

### Repro Steps

1. PS C:\Users\user> wsl.exe --update
1. Open ubuntu terminal
2. Get the following output:

```
<3>WSL (4564) ERROR: UtilTranslatePathList:2671: Failed to translate F:\Users\Eliya\AppData\Local\Programs\Microsoft VS Code\bin
➜  ~
```

I'm sorry for the poor reproduction steps, it just happened when I ran `wsl.exe --update`

### Expected Behavior

Should not throw an error.

### Actual Behavior

Getting `<3>WSL (11) ERROR: UtilTranslatePathList:2671: Failed to translate F:\Users\Eliya\AppData\Local\Programs\Microsoft VS Code\bin` every time I open a terminal

### Diagnostic Logs

Let me know about any information I need to supply.

**Comment by qdm12** [comment]
Got the same translation error `<3>WSL (53) ERROR: UtilTranslatePathList:2671: Failed to translate E:\SomePath\` when trying to open a folder in WSL using VSCode.

**Comment by Newbie012** [comment]
@qdm12 and it seems like F does not exist in my machine as well. Is it hardcoded somewhere?

**Comment by qdm12** [comment]
It's in my PATH environnement variable defined on Windows. Maybe WSL should just ignore non existant path values ?

**Comment by Newbie012** [comment]
Thanks for the tip! although it looks like even after I remove that path and restart WSL, the error persists.

**Comment by qdm12** [comment]
Did you close and re-open your shell/terminal? Such that the environment variables get reloaded. Otherwise try a reboot?

**Comment by Newbie012** [comment]
@qdm12 Problem solved. Restarting the shell seems to do the trick. Thanks!

**Comment by romaluca** [comment]
Hi, I have the same problem. I tried to restart the shell and reboot but the problem persists

<3>WSL (723) ERROR: UtilTranslatePathList:2671: Failed to translate Z:\home\gianni\dev\gettse

**Comment by WinSSitaly** [comment]
I had 
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate F:\DATI\platform-tools
I was fixing it
set path | findstr platform-tools
inside it find a ... ;F:\DATI\platform-tools; ...
so check envinronment variables
follow instruction on this link 
https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html
delete the line error or correct it with the correct path in my situation my drive was E:

after correct it i fix that error/warning

**Comment by Jacen-cpu** [comment]
cool, just the path environment variable in windows, just delete it in your windows.

**Comment by PennRobotics** [comment]
My organization adds network drives to Path via _HKCU/Volatile Environment_, so I'm not able to remove via the environmental variable to fix this issue. Instead, as @protella mentioned in [another issue](https://github.com/microsoft/WSL/issues/8723#issuecomment-1356882972), I removed Windows Subsystem for Linux via "Apps & features", which reverted to the previous version and removed the error.

**Comment by huettenhain** [comment]
I have the same issue for a `subst` drive. I suspect that this might be a way to reproduce the issue; create an entry in 
```
HKLM:SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices
```
to subst any path to a new drive name, reboot the device, and launch the WSL prompt.

**Comment by PennRobotics** [comment]
I had a mystery error where WSL was terminating immediately on startup regardless of `wsl.exe` flags, and updating to WSL through the Store fixed it, so now I'm stuck needing to fix the UtilTranslatePathList problem.

The error (caused by SMB network drives being added to PATH thru _Volatile Environment_ at login) gets **resolved by appending this section to `wsl.conf`**:

```
[interop]
appendWindowsPath=false
```

**Comment by sg552** [comment]
I met the same problem~  The root cause is D: does not exists when you started windows .

How to recur this issue: 

1. stop PC
2. power off the mobile hard disk ( which is D: in my PC) 
3. restart PC,  into windows  ( there are some PATH variable in my windows ) 
4. power up the mobile hard disk
5. start WSL,  I found the error message

solution: make sure all the PATH are available and then restart wsl.

$ wsl --shutdown
$ wsl

**Comment by arun07as** [comment]
I had encountered a similar issue, but in my case, I was getting this error for all windows paths such as `C:\Windows\System32`.

Simply restarting the terminal did not work for me.

Restarting wsl seemed to fix it for me ( run `wsl --shutdown` in PowerShell and then reopen your wsl terminal )

**Comment by silverham** [comment]
I had same error, seems due to my work's antivirus software Symantec Endpoint Protection, A workaround was to install Ubuntu from the windows store and run via "ubuntu.exe" in the start menu.

**Comment by RufusJWB** [comment]
> I had a mystery error where WSL was terminating immediately on startup regardless of `wsl.exe` flags, and updating to WSL through the Store fixed it, so now I'm stuck needing to fix the UtilTranslatePathList problem.
> 
> The error (caused by SMB network drives being added to PATH thru _Volatile Environment_ at login) gets **resolved by appending this section to `wsl.conf`**:
> 
> ```
> [interop]
> appendWindowsPath=false
> ```

Thank you very much. This solved the problem for me!

**Comment by MatrixC7** [comment]
> I had a mystery error where WSL was terminating immediately on startup regardless of `wsl.exe` flags, and updating to WSL through the Store fixed it, so now I'm stuck needing to fix the UtilTranslatePathList problem.
> 
> The error (caused by SMB network drives being added to PATH thru _Volatile Environment_ at login) gets **resolved by appending this section to `wsl.conf`**:
> 
> ```
> [interop]
> appendWindowsPath=false
> ```

It works and here is a simple one-line command for adding that to the end of `wsl.conf`!
```
echo -e "[interop]\nappendWindowsPath = false" | sudo tee -a /etc/wsl.conf
```

**Comment by imranpollob** [comment]
Remove the environment variable that causing the problem. Check the user variable and system variable paths. Then reopen the terminal. 
If you use `appendWindowsPath=false` then you will lose the ability to call the programs defined in system variable. In my case vscode's `code` keyword stopped working. So, I reverted that.

**Comment by CHerSun** [comment]
> Remove the environment variable that causing the problem. Check the user variable and system variable paths. Then reopen the terminal. If you use `appendWindowsPath=false` then you will lose the ability to call the programs defined in system variable. In my case vscode's `code` keyword stopped working. So, I reverted that.

problem is - I do need a PATH to remote share, mounted as Z, in Windows. While WSL dislikes that.

**Comment by antgustech** [comment]
I have used WSL for several years. After a reboot today, I got these errors and I can no longer use my C disk

```
wsl: A localhost proxy configuration was detected but not mirrored into WSL. WSL in NAT mode does not support localhost proxies.
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot\bin
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\system32
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\Wbem
<3>WSL (649) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
...
<3>WSL (649) ERROR: CreateProcessEntryCommon:493: chdir(/mnt/c/winworkspace) failed 2
-bash: /mnt/c/Windows/System32/wsl.exe: No such file or directory
```

It seems that my C drive is no longer mounted. 

`mount -l | grep drvfs
`
Shows nothing. 
`
df -h
`
Shows that my C is not mounted. 

I have tried mounting it with
`sudo mount -t drvfs C: /mnt/c/`
But it fails with:

```
<4>WSL (715) WARNING: mount: waiting for virtio device drvfs
<3>WSL (715) ERROR: MountWithRetry:307: mount(drvfs, /mnt/c, 9p, 0x00000000, cache=mmap,msize=262144,trans=virtio,aname=drvfs;path=C:;symlinkroot=/mnt/) failed: No such file or directory
```


How can I solve this?

**Comment by WinSSitaly** [comment]
check if c is a subfolder of mnt
ls /mnt
if not present
cd /mnt
sudo makedir c
sudo mount -t drvfs C: /mnt/c/

or
try to create a different folder in mount
cd /mnt
sudo makedir myfolder
then try to mount in that folder
sudo mount -t drvfs C: /mnt/myfolder/

**Comment by antgustech** [comment]
> check if c is a subfolder of mnt ls /mnt
> 
> if present check if empty or what is inside you can try to delete the folder c not what is inside
> 
> if not present cd /mnt sudo makedir c sudo mount -t drvfs C: /mnt/c/
> 
> or try to create a different folder in mount cd /mnt sudo makedir myfolder then try to mount in that folder sudo mount -t drvfs C: /mnt/myfolder/


`ls /mnt`

Does show c but it looks empty. I tried deleting it and creating a new c directory and mounting but I still get: 

```
WSL at   angu2023-11-14 13:18:23  /mnt   
➜ sudo mkdir c
WSL at   angu2023-11-14 13:18:32  /mnt   
➜ ls
c  wsl  wslg
WSL at   angu2023-11-14 13:18:33  /mnt   
➜ sudo mount -t drvfs C: /mnt/c/
<4>WSL (1602) WARNING: mount: waiting for virtio device drvfs
<3>WSL (1602) ERROR: MountWithRetry:307: mount(drvfs, /mnt/c, 9p, 0x00000000, cache=mmap,msize=262144,trans=virtio,aname=drvfs;path=C:;symlinkroot=/mnt/) failed: No such file or directory
```


Creating a new directory with a different name also gives the same result sadly.

**Comment by WinSSitaly** [comment]
uname -a
in windows
wsl -version
ver

**Comment by antgustech** [comment]
> uname -a in windows wsl -version ver

Linux DESKTOP-XXXXX 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

There is no --version in wsl but --status is there:

Default Distribution: Ubuntu
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.

**Comment by Throne3d** [comment]
I had what was likely this same issue just now, and the related potential resolutions I found didn't seem to solve the issue:

* Locked BitLocker drive - no, it's failing on C:, rather than another drive
* Docker Desktop distribution being set as default - no, I don't have that installed; the only distro I had was Ubuntu
* Windows paths issue - disabling windows paths does hide some of the errors up top around translating paths, but still shows the C: mount failing, and the underlying C: drive still isn't mounted
   ```
   Failed to mount C:\, see dmesg for more details.
   Failed to mount G:\, see dmesg for more details.
   ```
   (G:\ is from Google Drive, and is way less important - but seems to be affected by the same issue)

I believe this started after upgrading to Windows 23H2, and happened on both 2.0.8 and 2.0.9. I tried uninstalling WSL entirely (deregistering the distro, removing the distro + WSL items from Windows Programs, removing the optional feature, rebooting, and then re-running `wsl --install`) but it showed the same issue on a fresh install of Ubuntu, weirdly enough.

Another issue suggested trying
```
[wsl2]
virtio9p=false
```
in ~/.wslconfig on Windows, then rebooting WSL (`wsl --shutdown` first) to debug the issue in more detail, which seems to have solved it for me for now, but I don't know if there are other implications here (I can't see this flag documented in [Advanced settings configuration in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)). 🤔 

I think this is the relevant part of dmesg when the issue presents itself (for C:\), which seems to match with several other threads I've seen about mounting issues, but doesn't seem to explain this specific issue:

```
[    2.995549] /usr/bin/wslpath:
[    2.995555] C:\Users\EdwardJones

[    3.002935] [13:03:50.670] <3>WSLGd: LogException:75:
[    3.002948] Exception: Invalid argument @../main.cpp:117 (TranslateWindowsPath)

[    3.137008] 9pnet_virtio: no channels available for device drvfs
[    3.143810] WSL (2) WARNING: mount: waiting for virtio device drvfs
[    3.246239] 9pnet_virtio: no channels available for device drvfs
[    3.347613] 9pnet_virtio: no channels available for device drvfs
[    3.450334] 9pnet_virtio: no channels available for device drvfs
[    3.552722] 9pnet_virtio: no channels available for device drvfs
[    3.655365] 9pnet_virtio: no channels available for device drvfs
[    3.758037] 9pnet_virtio: no channels available for device drvfs
[    3.860596] 9pnet_virtio: no channels available for device drvfs
[    3.962834] 9pnet_virtio: no channels available for device drvfs
[    4.065597] 9pnet_virtio: no channels available for device drvfs
[    4.167849] 9pnet_virtio: no channels available for device drvfs
[    4.271759] 9pnet_virtio: no channels available for device drvfs
[    4.373593] 9pnet_virtio: no channels available for device drvfs
[    4.475863] 9pnet_virtio: no channels available for device drvfs
[    4.578869] 9pnet_virtio: no channels available for device drvfs
[    4.681303] 9pnet_virtio: no channels available for device drvfs
[    4.784107] 9pnet_virtio: no channels available for device drvfs
[    4.889478] 9pnet_virtio: no channels available for device drvfs
[    4.992848] 9pnet_virtio: no channels available for device drvfs
[    5.095910] 9pnet_virtio: no channels available for device drvfs
[    5.198619] 9pnet_virtio: no channels available for device drvfs
[    5.201325] WSL (2) ERROR: MountWithRetry:307: mount(drvfs, /mnt/c, 9p, 0x00000400, cache=mmap,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/
```

**Comment by Throne3d** [comment]
Possibly related to #10727? They seem to be having a similar issue, and say it was caused by running `shutdown` (I don't remember doing that, but I did perform some Ubuntu upgrades which forces WSL to shut down, so maybe that's related?).

**Comment by antgustech** [comment]
> [wsl2]
> virtio9p=false

I also tried this option but it didnt seem to do much for me.



> Windows paths issue - disabling windows paths does hide some of the errors up top around translating paths, but still shows the C: mount failing, and the underlying C: drive still isn't mounted

Disabling the windows path thingy did reduce the number of errors but I still could not access c.

**Comment by psymbio** [comment]
Currently, I get this error:
```bash
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Common Files\Oracle\Java\javapath
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\system32
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\Wbem
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (1186) ERROR: No such file or directory @D:/a/1/s/src/linux/mountutil\mountutilcpp.h:17 (MountEnum)
<3>WSL (1186) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
```

The solution of shutting down wsl and restarting didn't seem to work for me and 
```bash
wsl --shutdown
wsl
```

And I'm not entirely sure where to edit this configuration:
```bash
[wsl2]
virtio9p=false
```

**Comment by amahpour** [comment]
I'm seeing this across multiple distros now when starting up WSL 2. I even attempted to install a new distro and got this:
```
Installing, this may take a few minutes...
<3>WSL (9) ERROR: CreateProcessParseCommon:708: Failed to translate C:\WINDOWS\system32
<3>WSL (9) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Microsoft MPI\Bin\
<3>WSL (9) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Semeru\jdk-17.0.7.7-openj9\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Python310\Scripts\
<3>WSL (9) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\Python310\
<3>WSL (9) ERROR: UtilTranslatePathList:2853: Failed to translate C:\WINDOWS\system32
```
Any recommendations on how to troubleshoot this?

**Comment by psymbio** [comment]
@amahpour did you try: https://github.com/microsoft/WSL/issues/10752#issuecomment-1813818652

**Comment by amahpour** [comment]
> @amahpour did you try: [#10752 (comment)](https://github.com/microsoft/WSL/issues/10752#issuecomment-1813818652)

I looked at that comment but I don't have `distrod` installed.

**Comment by davidwkelley** [comment]
The same problem started happening for me yesterday.  I don't have distrod installed.

[2023-11-17 06:36:54.111] Extension version: 0.81.8
[2023-11-17 06:36:54.111] L10N bundle: undefined
[2023-11-17 06:36:54.120] authorityHierarchy: wsl+Ubuntu-22.04
[2023-11-17 06:36:54.120] WSL extension activating for a local WSL instance
[2023-11-17 06:36:54.133] Resolving wsl+Ubuntu-22.04, resolveAttempt: 1
[2023-11-17 06:36:54.134] NodeExecServer run: C:\Windows\System32\wsl.exe --status
[2023-11-17 06:36:54.710] WSL feature installed: true (wsl --status)
[2023-11-17 06:36:54.710] NodeExecServer run: C:\Windows\System32\wsl.exe --list --verbose
[2023-11-17 06:36:55.339] 1 distros found
[2023-11-17 06:36:55.339] Starting VS Code Server inside WSL (wsl2)
[2023-11-17 06:36:55.339] Windows build: 22621. Multi distro support: available. WSL path support: enabled
[2023-11-17 06:36:55.340] Scriptless setup: false
[2023-11-17 06:36:55.442] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu-22.04 -e sh -c [ -f '/tmp/vscode-distro-env.BH9erW' ] && cat '/tmp/vscode-distro-env.BH9erW' || echo ''
[2023-11-17 06:36:55.562] WSL daemon log file: 
[2023-11-17 06:36:55.562] Probing if server is already installed: if [ -d ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2023-11-17 06:36:55.562] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu-22.04 -e sh -c if [ -d ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e ]; then printf 'install-found '; fi; if [ -f /etc/alpine-release ]; then printf alpine-; fi; uname -m
[2023-11-17 06:36:56.328] Probing result: install-found x86_64
[2023-11-17 06:36:56.328] Server install found in WSL
[2023-11-17 06:36:56.328] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu-22.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=1125128467-865813447-1427837231-4081809046 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2023-11-17 06:36:56.338] Using shell environment from invoking shell: /tmp/vscode-distro-env.BH9erW
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: CreateProcessParseCommon:708: Failed to translate C:\Users\sasdck\AppData\Local\Programs\Microsoft VS Code
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate c:\Users\sasdck\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\system32
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\Wbem
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Windows\System32\OpenSSH\
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Program Files\PowerShell\7\
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\sasdck\AppData\Local\Microsoft\WindowsApps
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate C:\Users\sasdck\AppData\Local\Programs\Microsoft VS Code\bin
[2023-11-17 06:36:57.022] <3>WSL (807) ERROR: UtilTranslatePathList:2853: Failed to translate c:\Users\sasdck\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\cli-bin
[2023-11-17 06:36:57.022] sh: 1: /scripts/wslServer.sh: not found
[2023-11-17 06:36:57.044] For help with startup problems, go to https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2023-11-17 06:37:04.713] Download in background is enabled

**Comment by davidwkelley** [comment]
This looks to have fixed the problem for me:

```
[wsl2]
virtio9p=false
```

**Comment by antgustech** [comment]
> > [wsl2]
> > virtio9p=false
> 
> I also tried this option but it didnt seem to do much for me.
> 
> > Windows paths issue - disabling windows paths does hide some of the errors up top around translating paths, but still shows the C: mount failing, and the underlying C: drive still isn't mounted
> 
> Disabling the windows path thingy did reduce the number of errors but I still could not access c.
> 
> EDIT:
> 
> Now it seems to work again. I think adding the virtio9p=false option solved it!

I just changed my JAVA_HOME env variable in windows and rebooted and now the problem is back with WSL not mounting C again!

**Comment by antgustech** [comment]
I have now tried reinstalling WSL but it does not work, same result as before, c not mounting.

**Comment by dancristiancecoi** [comment]
> ```
> 
> **Potential mitigation**: Another issue suggested trying
> 
> ```
> [wsl2]
> virtio9p=false
> ```
> 
> in ~/.wslconfig on Windows, then rebooting WSL (`wsl --shutdown` first) to debug the issue in more detail, which seems to have solved it for me for now, but I don't know if there are other implications here (I can't see this flag documented in [Advanced settings configuration in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)). 🤔


This worked for me and my coworkers, thank you! I did have to reboot my laptop for this to take full effect (just wsl --shutdown wasn't sufficient).

**Comment by antgustech** [comment]
I finally found the solution. It fails when I open via (win 11) terminal. But if I close everything and just open the "old" powershell prompt and type WSL, then it actually works again!

**Comment by avila-m-6** [comment]
> > **Potential mitigation**: Another issue suggested trying
> > ```
> > [wsl2]
> > virtio9p=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in ~/.wslconfig on Windows, then rebooting WSL (`wsl --shutdown` first) to debug the issue in more detail, which seems to have solved it for me for now, but I don't know if there are other implications here (I can't see this flag documented in [Advanced settings configuration in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)). 🤔
> 
> This worked for me and my coworkers, thank you! I did have to reboot my laptop for this to take full effect (just wsl --shutdown wasn't sufficient).

It worked for me w/o full reboot. Maybe you needed [to wait 8s](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule-for-configuration-changes)?

**Comment by antgustech** [comment]
Now after reboot the problem came back. But I managed to fix it by doing the following steps, maybe it will help someone else:

0.     Reboot windows
1.     Start Windows run (WINDOWS + R) 
2.     Type `pwsh `and hold `CTRL+SHIFT` to start powershell in admin mode. 
3.     Type `wsl –shutdown` to exit wsl and then type `wsl `to start it again

**Comment by Throne3d** [comment]
It looks like virtio9p has been disabled by default in the latest release: https://github.com/microsoft/WSL/releases/tag/2.0.11 - I guess that's related to this! It seems like this issue is being worked on actively, in that case =)

**Comment by hugosbg** [comment]
Mount Windows Network Drives in WSL:

```shell
$ sudo mkdir /mnt/z
$ sudo chown $USER:$USER /mnt/z
$ sudo chmod 777 /mnt/z
$ sudo mount -t drvfs Z: /mnt/z
```

**Comment by binarybasher** [comment]
First time trying to use wsl I ran into the same issues.

I checked my paths, removed missing folders from my path statements and still the issue existed.
I shutdown wsl and tried it again, same thing...

I then installed ubuntu: wsl --install ubuntu
set a password (prompted) and I was dropped to the shell prompt... hooray!

I ctrl-d to exit and then typed: wsl
Same error...

I then set ubuntu as the default distro: wsl --set-default ubuntu
Followed by trying it again: wsl
Perfect! I was dropped the shell without any errors relating to path...

I suspect the default distro was causing the issue, errors with path appear to be a diversion.

Hope this helps somebody.

**Comment by wesdevpro** [comment]
> First time trying to use wsl I ran into the same issues.
> 
> I checked my paths, removed missing folders from my path statements and still the issue existed. I shutdown wsl and tried it again, same thing...
> 
> I then installed ubuntu: wsl --install ubuntu set a password (prompted) and I was dropped to the shell prompt... hooray!
> 
> I ctrl-d to exit and then typed: wsl Same error...
> 
> I then set ubuntu as the default distro: wsl --set-default ubuntu Followed by trying it again: wsl Perfect! I was dropped the shell without any errors relating to path...
> 
> I suspect the default distro was causing the issue, errors with path appear to be a diversion.
> 
> Hope this helps somebody.

This solution worked for me after following this method https://github.com/microsoft/WSL/issues/9360#issuecomment-1810102617

**Comment by antgustech** [comment]
I am still having the issue, however restarting WSL form powershell after each reboot still seems to work until the next reboot.

**Comment by Ch1llNoodle** [comment]
This method might have helped😎[link](https://answers.microsoft.com/en-us/windows/forum/all/unable-to-install-wsl/c60525ca-ec33-4f73-acb9-37a6d5112df3)
```
Open SystemPropertiesAdvanced.exe
Click Environment variables
Double-click Path under "System variables"
Delete this entry
```

**Comment by wesdevpro** [comment]
Why is this issue closed? @Newbie012

**Comment by wesdevpro** [comment]
> This method might have helped😎[link](https://answers.microsoft.com/en-us/windows/forum/all/unable-to-install-wsl/c60525ca-ec33-4f73-acb9-37a6d5112df3)
> 
> ```
> Open SystemPropertiesAdvanced.exe
> Click Environment variables
> Double-click Path under "System variables"
> Delete this entry
> ```

This method does not work for me as I did not find this path in my local or global env

**Comment by Edw590** [comment]
I had to uninstall the distribution I had installed. Uninstalled from Settings and with the following commands (first command to list, second to uninstall). Then I installed it again and it works.
```
wslconfig /l
wslconfig /u [Distro]
```

**Comment by Davidrjx** [comment]
> > I had a mystery error where WSL was terminating immediately on startup regardless of `wsl.exe` flags, and updating to WSL through the Store fixed it, so now I'm stuck needing to fix the UtilTranslatePathList problem.
> > The error (caused by SMB network drives being added to PATH thru _Volatile Environment_ at login) gets **resolved by appending this section to `wsl.conf`**:
> > ```
> > [interop]
> > appendWindowsPath=false
> > ```
> 
> It works and here is a simple one-line command for adding that to the end of `wsl.conf`!
> 
> ```
> echo -e "[interop]\nappendWindowsPath = false" | sudo tee -a /etc/wsl.conf
> ```

also need restart wsl

**Comment by hudson-viana** [comment]
In my case, I have a C:\ (SSD) and a D:\ (HDD) drive. Today, the D: (HDD) drive did not start correctly, and only the C: (SSD) drive booted up. In my case, I discovered that this error is similar to the WSL 2 terminal telling me "I tried to access the D:\ drive" but could not find the D:\ drive.". So i restarted the PC.

**Comment by wesdevpro** [comment]
> In my case, I have a C:\ (SSD) and a D:\ (HDD) drive. Today, the D: (HDD) drive did not start correctly, and only the C: (SSD) drive booted up. In my case, I discovered that this error is similar to the WSL 2 terminal telling me "I tried to access the D:\ drive" but could not find the D:\ drive.". So i restarted the PC to fix this error.

I have a similar setup but no matter if I restart WSL always gives me the error regarding my D drive

**Comment by riojack** [comment]
For anyone coming from a Google search... I encountered this problem during `podman machine init` and again during `podman machine start`.  Turns out, I had an environment variable that pointed to a drive that I no longer had physically connected. 

Run `rundll32 sysdm.cpl,EditEnvironmentVariables` and remove any environment variables that are paths to non-existent drives.  Also, remove from the `PATH` environment variable paths to non-existent drives.

**Comment by ashish2508** [comment]
> > In my case, I have a C:\ (SSD) and a D:\ (HDD) drive. Today, the D: (HDD) drive did not start correctly, and only the C: (SSD) drive booted up. In my case, I discovered that this error is similar to the WSL 2 terminal telling me "I tried to access the D:\ drive" but could not find the D:\ drive.". So i restarted the PC to fix this error.
> 
> I have a similar setup but no matter if I restart WSL always gives me the error regarding my D drive

bro try going the the system environment variables and search in system variables (Path) and there must be mentioned delete that and enter again and then restart the system , if not solved do check your bashrc/zshrc as well

**Comment by sytelus** [comment]
In my case, this error was because of older broken distro still hanging around. You can see list of distro:

```
wsl --list
```

You can set default distro:

```
wsl --set-default Ubuntu
```

This worked for me.

**Comment by bernardolm** [comment]
If your `/etc/wsl.conf` was setted with:
```
[automount]
enabled=false
```
you will receive these errors:
> _<3>WSL (318) ERROR: UtilTranslatePathList:2866: Failed to translate C:\..._

When I commented lines above in `/etc/wsl.conf`, all erros was fixed to me.

My environment:

```bash
$ cat /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM

C:\Users\bernardo\ubuntu-home   /home/bernardo  drvfs   defaults,metadata,uid=1002      0       0

$ cat /etc/wsl.conf
[boot]
systemd=true

# [automount]
# enabled=false

[network]
generateResolvConf=false

# [interop]
# appendWindowsPath=false
```

My `%userprofile%\.wslconfig`:
```
[wsl2]
swap=0
# virtio9p=false
```

**Comment by nubblesite** [comment]
> In my case, this error was because of older broken distro still hanging around. You can see list of distro:
> 
> ```
> wsl --list
> ```
> 
> You can set default distro:
> 
> ```
> wsl --set-default Ubuntu
> ```
> 
> This worked for me.

docker-desktop strikes again...

**Comment by yanugto** [comment]
> cool, just the path environment variable in windows, just delete it in your windows.

You saved me!

**Comment by LoneWanderer-GH** [comment]
> In my case, this error was because of older broken distro still hanging around. You can see list of distro:
> 
> ```
> wsl --list
> ```
> 
> You can set default distro:
> 
> ```
> wsl --set-default Ubuntu
> ```
> 
> This worked for me.

This is exactly the issue I was facing.

```powershell
(base) PS Q:\> wsl --list
Distributions du Sous-système Windows pour Linux :
docker-desktop-data (par défaut) <==== culprit
Ubuntu
Ubuntu-22.04
```
so I added this in my powershell scripts:
``` powershell
wsl --set-default Ubuntu # just in case ... I have a docker-desktop-data by default that messed around ...
```

seems to work now, but I don't know how to revert the default, it might have broken something else

**Comment by Victor-Nyagudi** [comment]
As mentioned before, the `PATH` environment variable is also why I experienced this error. An extra colon caused it e.g. `C::/User/AppData/...`, so updating it to `C:/User/AppData/...` got rid of it. This is on WSL 2.

It's something worth considering if you don't want to delete the `PATH` entry entirely in case you need it down the road for something else. The issue might just be a typo.

**Comment by slanning76** [comment]
I had an unmounted Veracrypt volume in my Paths.  I removed the path and had to reboot my Windows system before it would no longer complain when logging into WSL.

**Comment by BassMatiOnCode** [comment]
I have programs installed on (unmounted) removable storage (SD card) that seem to cause this problem. I will permanently mount the SD card and see if the error disappears.

Update: It worked! I added the following line to /etc/fstab:
D:  /mnt/d  drvfs  defaults,metadata,uid=1000,gid=1000,umask=22,fmask=111  0  0

This mounts the Windows drive D: in Linux /mnt/d early, so the path problem does not exist anymore.
