### ISSUE TITLE
Win - kex stopped working

### ISSUE THREAD

**Issue by Qu-Bi** [microsoft/WSL#9361]
### Version

10.0.22623.1037

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Kali linux 2022.04

### Repro Steps

Hi, I got a problem, I've installed kali Linux from the Microsoft store (windows 11) and installed kali Linux packages (all) and Win-kex, which was working, but yesterday it stopped. When I type sudo kex --win it shows:

![image](https://user-images.githubusercontent.com/83206191/208292504-768bee6c-133f-4f49-a16c-09eac53f6cd5.png)

I've tried everything, but nothing worked for me.

### Expected Behavior

I was expecting to see windows with kali GUI, which I saw before, but it did not show.

### Actual Behavior

When I type sudo kex --win it shows:

![image](https://user-images.githubusercontent.com/83206191/208292526-ad3b07e1-b372-49e5-a32e-1cd13849a98e.png)

When I type sudo vncserver it shows:

![image](https://user-images.githubusercontent.com/83206191/208292562-c135878b-9c10-416e-b8fc-f9884778d422.png)

**Comment by rescenic** [comment]
See this [answer](https://github.com/microsoft/WSL/discussions/6675#discussioncomment-2101116) in another thread.
