### ISSUE TITLE
Cannot start Windows executable from powershell.exe started from WSL2 after wsl.exe --update

### ISSUE THREAD

**Issue by 0anton** [microsoft/WSL#9364]
### Version

Windows version: 10.0.19044.2364

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 20.04

### Other Software

n/a

### Repro Steps

```
$ powershell.exe

PS C:\temp> dir \\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey\AutoHotkeyU64.exe



    Directory: \\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------        12/21/2020   2:56 AM        1190400 AutoHotkeyU64.exe


PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey> .\AutoHotkeyU64.exe

Program 'AutoHotkeyU64.exe' failed to run: Incorrect functionAt line:1 char:1
+ .\AutoHotkeyU64.exe
+ ~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\AutoHotkeyU64.exe
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

```
$ cmd.exe

C:\temp>dir \\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey\AutoHotkeyU64.exe
 Volume in drive \\wsl.localhost\Ubuntu-20.04 has no label.
 Volume Serial Number is 0000-0000

 Directory of \\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey

21/12/2020  02:56         1.190.400 AutoHotkeyU64.exe
               1 File(s)      1.190.400 bytes
               0 Dir(s)  170.607.165.440 bytes free

C:\temp>\\wsl.localhost\Ubuntu-20.04\home\d057039\dotfiles\assets\AutoHotkey\AutoHotkeyU64.exe
The system cannot execute the specified program.
```

It is also impossible to open file associated with the executable:
```
d057039:AutoHotkey|master$ cmd.exe /c start FixCtrlBackspace.ahk
The system cannot execute the specified program.
```

### Expected Behavior

Executing Windows programs on WSL2 paths from cmd.exe or powershell.exe is possible if the latter it started from WSL2 environment (in current example _AutoHotkeyU64.exe_ starts.

### Actual Behavior

cmd.exe: The system cannot execute the specified program.
powershell.exe: NativeCommandFailed

### Diagnostic Logs

**Remarks:**
1. Before the `wsl.exe --update` cmd.exe and poweshell.exe could start executables on WSL2 paths just same fine as other executables.
2. WSL2 start Windows executable correctly.
3. cmd.exe or powershell.exe which are started natively from Windows also start any executable on WSL2 path perfectly.

**Comment by Rack1600** [comment]
I am seeing a similar issue, where we use a windows python.exe from WSL, and after wsl --update, processes started from within python.exe fail to run (WindowsError: [Error 1] Incorrect function).
The same python script, run in the same python.exe, but started from within windows, does not fail. 
Also, running the process directly from WSL (not via python) also works. 
Seems like exactly the same issue, but with python instead of cmd.exe or powershell.exe.

**Comment by davidtlascelles** [comment]
I also have this issue. I think it may be related to the switch to the Microsoft Store version of WSL

**Comment by Rack1600** [comment]
> I also have this issue. I think it may be related to the switch to the Microsoft Store version of WSL

@davidtlascelles  this worked for me with the store version of WSL.  It stopped working yesterday when I ran "wsl --update" and "wsl --shutdown" to get the latest features.

**Comment by enachi** [comment]
uninstall store version and It will start working again.

**Comment by Rack1600** [comment]
But the latest LTS is not available via command line - nor as a download at the Ubuntu downloads store. :( 
This needs to be fixed.   I literally did not have this problem in my store-installed Ubuntu 22.04, only 3 days ago.

**Comment by Rack1600** [comment]
> uninstall store version and It will start working again.

I did this and it did not help.
This is blocking my department from using WSL :(

**Comment by Rack1600** [comment]
It looks like this: 
https://github.com/microsoft/WSL/issues/9421
could be a variant on this issue too

**Comment by Rack1600** [comment]
[WslLogs-2023-01-06_13-31-44.zip](https://github.com/microsoft/WSL/files/10360138/WslLogs-2023-01-06_13-31-44.zip)
Logs of executable failling when run from WSL -> Powershell -> .exe

**Comment by 0anton** [comment]
See logs provided by @Rack1600. I can also generate mine, if needed...

**Comment by 0anton** [comment]
It looks like there is still no solution nor a proper workaround?

I've same behavior on `Linux 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` on the client running Windows 11 22H2.

**Comment by alastairtree** [comment]
Seems to affect all windows executables saved into WSL fileshare and being run from powershell.exe (or pwsh.exe) which was launched from WSL.

My workaround was to uninstall the store version of WSL, and then the previous version of WSL was restored which still worked.

**Comment by 0anton** [comment]
Also `cmd.exe` is not able launch anything from WSL. Uninstalling on Windows 11 is not possible, because it comes initially with the buggy versions (at least recent, fresh installs). It's a pity, that since creation, nobody from maintainers even dare to validate the problem...

**Comment by 0anton** [comment]
This is is the same to all issues reporting unusual slowness of WSL2 starting Windows executables from WSL file system.

**References**
1. https://github.com/microsoft/WSL/issues/8943
2. https://superuser.com/questions/1762576/why-are-exe-very-slow-when-run-from-wsl2-filesystem

**Comment by marqueurs404** [comment]
Are there any updates on this issue? It still hasn't been fixed it seems.
