### ISSUE TITLE
how to make pl2303 usb serial?

### ISSUE THREAD

**Issue by shiqx429** [microsoft/WSL#9366]
### Version

Windows 10.0.19045.2364

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1.download [linux-msft-wsl-5.15.79.1](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.79.1)
(1).make -j$(nproc) KCONFIG_CONFIG=Microsoft/config-wsl 
(2).sudo make modules_install
(3)sudo make install
2.copy WSL2-Linux-Kernel-linux-msft-wsl-5.15.79.1\drivers\usb\serial\pl2303.c and pl2303.h to my folder
3.the Makefile is 
`obj-m	+= pl2303.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean`

4. make all && sudo insmod pl2303.ko
5. error message is "insmod: ERROR: could not insert module pl2303.ko: Invalid parameters"

what's wrong with me? please help, thanks!

### Expected Behavior

need pl2303.ko run

### Actual Behavior

sudo insmod pl2303.ko 
insmod: ERROR: could not insert module pl2303.ko: Invalid parameters

**Comment by shiqx429** [comment]
demesg -T is

[Mon Dec 19 11:09:40 2022] pl2303: loading out-of-tree module taints kernel.
[Mon Dec 19 11:09:40 2022] BPF:[135029] STRUCT  
[Mon Dec 19 11:09:40 2022] BPF:size=16 vlen=4
[Mon Dec 19 11:09:40 2022] BPF: 
[Mon Dec 19 11:09:40 2022] BPF:Invalid name
[Mon Dec 19 11:09:40 2022] BPF:

[Mon Dec 19 11:09:40 2022] failed to validate module [pl2303] BTF: -22

**Comment by shiqx429** [comment]
`obj-m	+= pl2303.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean`

**Comment by shiqx429** [comment]
i have try to
make menuconfig KCONFIG_CONFIG=Microsoft/config-wsl to enable PL2303, then sudo insmod drivers/usb/serial/pl2303.ko,  same result.

**Comment by shiqx429** [comment]
wsl --version
1.0.3.0

**Comment by elsaco** [comment]
@shiqx429 asked _what's wrong with me?_  I can't tell what's wrong with you but have a suggestion about your module loading issue. You need to have the running kernel and module(s) from the same build.

In the top directory of your kernel source code copy `Microsoft/config-wsl` to `.config` and run `make menuconfig`. Select `USB Prolific 2302 Single Port Serial Driver` to be build as a module. Save your new config. Run `make modules` and `make modules_install` to add the module to `/lib/modules` along with all dependencies. Then build a new kernel with `make bzImage` and copy it to your `C:\` driver. Add `kernel=C:\\some_folder_name\\bzImage` to your `.wslconfig` and shutdown WSL to take effect.

After this you'll be able to load/unload the module. Sample dmesg output after running modprobe:

```
[   37.162338] usbcore: registered new interface driver pl2303
[   37.162348] usbserial: USB Serial support registered for pl2303
```

and lsmod output:

```
elsaco@toto:~$ lsmod
Module                  Size  Used by
pl2303                 24576  0
```

**Comment by shiqx429** [comment]
> @shiqx429 asked _what's wrong with me?_ I can't tell what's wrong with you but have a suggestion about your module loading issue. You need to have the running kernel and module(s) from the same build.
> 
> In the top directory of your kernel source code copy `Microsoft/config-wsl` to `.config` and run `make menuconfig`. Select `USB Prolific 2302 Single Port Serial Driver` to be build as a module. Save your new config. Run `make modules` and `make modules_install` to add the module to `/lib/modules` along with all dependencies. Then build a new kernel with `make bzImage` and copy it to your `C:\` driver. Add `kernel=C:\\some_folder_name\\bzImage` to your `.wslconfig` and shutdown WSL to take effect.
> 
> After this you'll be able to load/unload the module. Sample dmesg output after running modprobe:
> 
> ```
> [   37.162338] usbcore: registered new interface driver pl2303
> [   37.162348] usbserial: USB Serial support registered for pl2303
> ```
> 
> and lsmod output:
> 
> ```
> elsaco@toto:~$ lsmod
> Module                  Size  Used by
> pl2303                 24576  0
> ```

ok,thank you!
