### ISSUE TITLE
WSLhost won't release the occupied host ports and won't reconnect the tunnel.

### ISSUE THREAD

**Issue by scruel** [microsoft/WSL#9367]
### Version

10.0.22000.1335

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 1.0.3.0

### Distro Version

Ubuntu-22.04

### Repro Steps

1. Run some web service (e.g. jupyter notebook) on `server` port 8888.
2. On WSL, execute:
`ssh -N -L 8888:localhost:8888 scruel@server`
3. On the host, open browser, visit localhost:8888, all fine.
4. Exit ssh tunnel.
5. Rerun tunnel command:
`ssh -N -L 8888:localhost:8888scruel@server`
6. Open browser, visit localhost:8888, will get "network refused".

On the host, 8888 will continue to be occupied until you kill the `WSLhost` processes.

### Expected Behavior

On host, can visit WSL's service with same port even after it restarted.

### Actual Behavior

On host, can't visit WSL's service with same port after it restarted.

**Comment by benhillis** [comment]
@pmartincic - will you please take a look?

**Comment by pmartincic** [comment]
I can't reproduce this on 1.0.3. I'll need /logs and the output from `/proc/net/tcp`
