### ISSUE TITLE
"System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down"

### ISSUE THREAD

**Issue by ParaliyzedEvo** [microsoft/WSL#9368]
Thats the error message I get when I try to run sudo systemctl restart redis.service. Now I following a guide to download something that uses systemctl. But ik that systemctl doesn't work on wsl2 and have to download the redis server from this guide. https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-22-04
This guide helps but once I get to sudo systemctl restart redis.service I get the error message "System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down". I changed the config files (well just one line) correctly (superviser systemd) and it still doesn't work. So if you guys can please help me I would greatly appreciate it!

**Comment by shiqx429** [comment]
check your wsl.conf
[boot]
systemd=true

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by ParaliyzedEvo** [comment]
> check your wsl.conf [boot] systemd=true
> 
> https://learn.microsoft.com/en-us/windows/wsl/wsl-config

Way ahead of you
![image](https://user-images.githubusercontent.com/107338855/208362538-1b9fd2bc-390a-4e54-95f7-bb7cfb3f0e83.png)

**Comment by Biswa96** [comment]
You need WSL from Windows Store and specific minimum versions of Windows 10 and 11. See this post for more details https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/

**Comment by ParaliyzedEvo** [comment]
> You need WSL from Windows Store and specific minimum versions of Windows 10 and 11. See this post for more details https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/

**Comment by ParaliyzedEvo** [comment]
> You need WSL from Windows Store and specific minimum versions of Windows 10 and 11. See this post for more details https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/

Technically I should be able to do the commands when I kinda hacked my Windows 11 Home to get a Windows 11 Pro Feature (WSL)?
