### ISSUE TITLE
WSL is not starting when connected to the Windows machine over SSH

### ISSUE THREAD

**Issue by romanvoeikov** [microsoft/WSL#9373]
### Version

Microsoft Windows [Version 10.0.25267.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

Connect to the Windows machine over SSH and try to start WSL from the terminal.

### Expected Behavior

WSL should start with running `wsl` command from the terminal on a remote machine when connected over SSH.

### Actual Behavior

It throws the following message: 
```
The Windows Subsystem for Linux is not installed. You can install by running 'wsl.exe --install'.
For more information please visit https://aka.ms/wslinstall
```
However, when I am not connecting to this machine over SSH and have an option just to use it locally, WSL works fine and may be started from the terminal as expected.

It happened after the last update that also deleted installed WSL distribution as reported in another [issue](https://github.com/microsoft/WSL/issues/9355)

**Comment by brentmjohnson** [comment]
Same issue here.  My assumption is that it is related to this still outstanding known issue: https://learn.microsoft.com/en-us/windows/wsl/store-release-notes#known-issues

But if this is still a known issue why are insiders builds requiring the store packaged version now?

**Comment by romanvoeikov** [comment]
> Same issue here. My assumption is that it is related to this still outstanding known issue: https://learn.microsoft.com/en-us/windows/wsl/store-release-notes#known-issues


Oh, I didn't even know about this issue however I used WSL over SSH without any troubles before the last update.

**Comment by brentmjohnson** [comment]
> > Same issue here. My assumption is that it is related to this still outstanding known issue: https://learn.microsoft.com/en-us/windows/wsl/store-release-notes#known-issues
> 
> Oh, I didn't even know about this issue however I used WSL over SSH without any troubles before the last update.

Yeah the WSL installed from windows features still supported this - up until this latest insiders build.
