### ISSUE TITLE
wsl ubuntu 16.04 install not available how do i get it back?

### ISSUE THREAD

**Issue by carlos2334** [microsoft/WSL#9380]
Hi I was using ubuntu 16.04 which was available a week ago but I was having issues with the ubuntu so I decided to uninstall it however it was missing when i went to reinstall it i even factory reset my laptop but it is still missing.  Is there anything I can do? 

![thumbnail_image0](https://user-images.githubusercontent.com/120650290/208751312-dc47c492-d68e-4fe9-95dc-6784dfd751bf.jpg)
![thumbnail_image1](https://user-images.githubusercontent.com/120650290/208751383-feb45911-1d27-4b74-aa1b-7c81ab9124b0.jpg)

**Comment by Biswa96** [comment]
You have to manually installed it using `wsl.exe --import` command. The rootfs tarball can be found here https://cloud-images.ubuntu.com/releases/xenial/release/. You need to download the [ubuntu-16.04-server-cloudimg-amd64-wsl.rootfs.tar.gz](https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-wsl.rootfs.tar.gz) file.

**Comment by carlos2334** [comment]
Thank you I will give that a go. May I ask if you would know why it was available a week ago but no longer available?

**Comment by Biswa96** [comment]
I am not the right person to comment on that topic. If you would like to wait Microsoft developers may answer that. Though, according to the [official release cycle](https://ubuntu.com/about/release-cycle), Ubuntu 16.04 is in Extended Security Maintenance (ESM) timeline.

**Comment by Biswa96** [comment]
BTW, the link in your first screenshot https://aka.ms/wsl-ubuntu-1604 is still valid.

**Comment by elsaco** [comment]
`winget` has `Ubuntu 16.04 LTS` available, still:

```
PS C:\Users\elsaco> winget search ubuntu
Name               Id                    Version         Match       Source
----------------------------------------------------------------------------
Ubuntu             9PDXGNCFSCZV          Unknown                     msstore
Ubuntu 22.04.1 LTS 9PN20MSR04DW          Unknown                     msstore
Ubuntu 20.04.5 LTS 9MTTCL66CPXJ          Unknown                     msstore
Ubuntu 18.04.5 LTS 9PNKSF5ZN4SW          Unknown                     msstore
Ubuntu (Preview)   9P7BDVKVNXZ6          Unknown                     msstore
Ubuntu             Canonical.Ubuntu      2004.2021.825.0             winget
Ubuntu 22.04 LTS   Canonical.Ubuntu.2204 2204.0.10.0     Tag: ubuntu winget
Ubuntu 20.04 LTS   Canonical.Ubuntu.2004 2004.2021.825.0 Tag: ubuntu winget
Ubuntu 18.04 LTS   Canonical.Ubuntu.1804 1804.2019.522.0 Tag: ubuntu winget
Ubuntu 16.04 LTS   Canonical.Ubuntu.1604 1604.2019.523.0 Tag: ubuntu winget
```

Direct link `https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx`

**Comment by OneBlue** [comment]
Indeed Ubuntu 16 is not available via `wsl --install` anymore, but the above links with the rootfs should work if you need to install that specific version.
