### ISSUE TITLE
Incorrect hostname with systemd enabled

### ISSUE THREAD

**Issue by CCXXXI** [microsoft/WSL#9391]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04

### Repro Steps

- a ~~hostname~~ computer name with an underscore (`CCXXXI_TB` in my case)
- [enable systemd](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)
- `sudo echo`

### Expected Behavior

```
ccxxxi@CCXXXI_TB:~$ sudo echo
[sudo] password for ccxxxi:
```

or

```
ccxxxi@CCXXXITB:~$ sudo echo
[sudo] password for ccxxxi:
```

### Actual Behavior

```
ccxxxi@CCXXXITB:~$ sudo echo
sudo: unable to resolve host CCXXXITB: Name or service not known
[sudo] password for ccxxxi:
```

**Comment by elsaco** [comment]
```
Unlike domain names, hostname labels can only be made up of the ASCII
letters 'a' through 'z' (case-insensitive), the digits '0' through '9',
and the hyphen. Labels can not start nor end with a hyphen.
```

RFC 952 for reference.

**Comment by CCXXXI** [comment]
> ```
> Unlike domain names, hostname labels can only be made up of the ASCII
> letters 'a' through 'z' (case-insensitive), the digits '0' through '9',
> and the hyphen. Labels can not start nor end with a hyphen.
> ```
> 
> RFC 952 for reference.

So WSL generated an invalid hostname before I enabled systemd.

**Comment by OneBlue** [comment]
Thanks for reporting this @CCXXXI.

Can you share the output of `cat /etc/wsl.conf` inside your distro ?

**Comment by CCXXXI** [comment]
```
$ cat /etc/wsl.conf
[boot]
systemd=true
```

**Comment by OneBlue** [comment]
Thank you @CCXXXI.

Can you also share the output of `cat /etc/hosts` ?

**Comment by CCXXXI** [comment]
```
$ cat /etc/hosts
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateHosts = false
127.0.0.1       localhost
127.0.1.1       CCXXXI_TB.      CCXXXI_TB
﻿
192.168.1.104   host.docker.internal
192.168.1.104   gateway.docker.internal
127.0.0.1       kubernetes.docker.internal

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by cerebrate** [comment]
While not Unicode in this case (just a regular invalid character), I think this is the same fundamental issue as #8386 .

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/1.1.3.

**Comment by wynnw** [comment]
wsl2 started to corrupt my hostname - looks like if you put a fqdn in your /etc/wsl.conf's [network] hostname section you'll get values that won't work. Seems like the behavior has changed and wsl2 only wants a hostname label without any domain info with it. For example, if you want your hostname to be srv-wsl.foo.com and put that there, you'll end up with a hostname of srv-wsl.foocom.

There's lots of debate online over what's the "correct" way to do a fqdn hostname. The wsl updates have just broken something that used to work fine for me. I'm on version:
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1413
