### ISSUE TITLE
FIXED: WSL 2 Won't Fully Install on 22H2

### ISSUE THREAD

**Issue by DarwinJS** [microsoft/WSL#9394]
### Version

10.0.22621

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

On a fresh build of a 22H2 machine that has not had wsl installed, run 'wsl --install'
During reboot black "updates progress screen" notice it says it cannot enable a feature and does another reboot to back out.
Once restarted a wsl runonce task runs.

Then you experience the various errors in these issues:
- [WslRegisterDistribution failed with error: 0x8007023e](https://github.com/microsoft/WSL/issues/9386)
- [WSL --install fails with unknown error code (0x80240066)](https://github.com/microsoft/WSL/issues/9385)

Fix (detected when running wsl --status for a bug ticket in this gh repository):
- Start "Turn Windows features on or off"
- Select ONLY "Virtual Machine Platform"
- Reboot

WSL works.

It seems to me that the automated process that kicks off with "wsl --install" is not able to completely enable the "Virtual Machine Platform" feature + whatever other changes it makes **all at once in one reboot**.

### Expected Behavior

wsl --install is successful in configuring "Virtual Machine Platform" as it was previously.

### Actual Behavior

That feature is not installed - but it is also not called out anywhere which feature was being attempted.
Additional attempts to use wsl or to reinstall it again give a variety of red herring errors.
Only "wsl --status" reveals what service is missing.

**Comment by chazix** [comment]
Hello - I just started encountering this issue today that is referenced in this issue: https://github.com/microsoft/WSL/issues/9386#issuecomment-1453314139
WSL has been working fine for a long time

**Comment by ACGNnsj** [comment]
Thanks, guy. I could use my former WSL2 image with network now. It's quite strange that it works without hyper-v or wsl feature on.
