### ISSUE TITLE
Windows 10 22H2 WSL2 without kvm support 

### ISSUE THREAD

**Issue by laoshaw** [microsoft/WSL#9400]
### Version

Microsoft Windows [ Version 10.0.19045.2364]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83

### Distro Version

Ubuntu 22.04

### Repro Steps

sudo kvm-ok reports no kvm support.

rebuild wsl2 kernel with all kvm enabled. still kvm-ok reports no kvm support.

enabled all hyper-v and reboot, restart wsl2, still no kvm support

### Expected Behavior

kvm should work inside WSL2 on 22H2 when kernel is built with kvm support.

I'm unsure if enabling full hyper-v is a must for kvm, but I tried it anyways.

### Actual Behavior

no kvm support no matter what

**Comment by elsaco** [comment]
@laoshaw you might need nested virtualization for this, however Windows 10 doesn't support it.

**Comment by elsaco** [comment]
That's correct.  On Windows 11 WSL has `nestedVirtualization = true`  set by default. Can be turned off in `.wslconfig`. `ExposeVirtualizationExtensions` applies to Hyper-V VMs only.

**Comment by OneBlue** [comment]
Indeed nested virtualization isn't supported in Windows 10. Closing.
