### ISSUE TITLE
Problem running wsl from a ssh session

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#9402]
### Version

Windows version: 10.0.22623.1037

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

22.04.1 LTS (Jammy Jellyfish)

### Repro Steps

ssh into my account on remote desktop which puts me into PowerShell 7.3 then run 

`C:\WINDOWS\system32\wsl.exe --help` 

### Expected Behavior

I should get the wsl help mesage just as I do when running locally on the system I ssh'd into 

### Actual Behavior

I get

`The file cannot be accessed by the system.`

Please provide guidance on what I'm doing wrong or how to debug this issue

**Comment by aki-k** [comment]
https://learn.microsoft.com/en-us/windows/wsl/store-release-notes#known-issues

> Known Issues:
> 
>     Launching Windows Subsystem for Linux from session zero does not currently work (for example from an ssh connection).
