### ISSUE TITLE
Wsl can only recognize one CPU and half of the memory on a dual-CPU machine

### ISSUE THREAD

**Issue by inie0722** [microsoft/WSL#9403]
### Version

Microsoft Windows [Version10.0.22621.963]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2

### Distro Version

 Debian GNU/Linux bookworm/sid

### Repro Steps

windows task manager
![image](https://user-images.githubusercontent.com/44135026/209596172-e41e61a3-0254-4d1a-b1ea-8fbb08a8454d.png)

wsl htop
![image](https://user-images.githubusercontent.com/44135026/209596242-7f94488c-1dfe-4aaa-b36b-6e6f99211466.png)

### Expected Behavior

wsl htop identifies all CPUs and memory

### Actual Behavior

wsl failed to recognize all CPU and memory

**Comment by OneBlue** [comment]
Thanks for reporting this @inie0722.

What do you get if you write:
```
[wsl2]
processors=72
```

In %USERPROFILE%/.wslconfig, and then run wsl.exe --shutdown to restart wsl ?

**Comment by inie0722** [comment]
> [wsl2]
> processors=72

htop still only recognizes 36 cores.
