### ISSUE TITLE
CurrentDirectoryPath doesn't get updated on directory change

### ISSUE THREAD

**Issue by kauz56** [microsoft/WSL#9404]
### Version

Microsoft Windows [Version 10.0.22621.525]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

Query the CurrentDirectoryPath of a wsl.exe (or powershell.exe) process. I do this via NtQueryInformationProcess, which, I know, is an internal API. I'd assume the behaviour would be the same via injection + GetCurrentDirectory (not an internal API) though.

### Expected Behavior

CurrentDirectoryPath should change according to the path I navigate to. This is the case with cmd.exe but not wsl.exe (or powershell.exe).

### Actual Behavior

CurrentDirectoryPath stays at the starting directory.

I'll attach a video, demonstrating the behaviour:

https://user-images.githubusercontent.com/121489265/209655705-c4864749-19c4-4dcb-a990-18ae1084762b.mp4

**Comment by OneBlue** [comment]
Thanks for reporting this @kauz56.

What you're seeing is expected because wsl.exe's current directory is not correlated to the Linux's current directory inside WSL.
In other words, doing `cd *` inside wsl.exe doesn't change wsl.exe's current directory.
