### ISSUE TITLE
high CPU-Load on Snapdragon 8cx Gen2 Windows 11

### ISSUE THREAD

**Issue by roadrunner-gs** [microsoft/WSL#9415]
### Version

Microsoft Windows [Version 10.0.22000.1335]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04 LTS

### Repro Steps

This is a freshly bought Laptop.
WLS installed as per instructions, as soon as i invoke wls in powershell nearly 3 cores are fully loaded despite no load inside the launched WLS-console. All Load ist system-load as could be seen in the attached screenshot.
The load stems from 2 processes, System and vmwp.exe, both with 11 to 12 % in taskmanager details.
![image](https://user-images.githubusercontent.com/82960943/210008801-d2f3cf5f-bf6b-4896-a9b6-0ca8bd796d7f.png)

```
top - 21:30:15 up 7 min,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7793.3 total,   7600.8 free,     82.6 used,    109.9 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.   7635.5 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0    1668   1016    948 S   0.0   0.0   0:00.00 /init
    8 root      20   0    1676     72      0 S   0.0   0.0   0:00.00 /init
    9 root      20   0    1676     80      0 S   0.0   0.0   0:00.04 /init
   10 roadrun+  20   0    9664   4500   2864 S   0.0   0.1   0:00.07 -bash
   94 roadrun+  20   0   10572   3124   2672 R   0.0   0.0   0:00.00 top -d1
```

### Expected Behavior

there should be no real load when inside the wls-console.

### Actual Behavior

as above.
load vanishes as soon as the WLS console is exited and shut down via 'wsl --shutdown'
Tried %userprofile%/.wslconfig with content
```
[wsl2]
guiApplications=false
```
as i read in another issue, but to no avail.

**Comment by roadrunner-gs** [comment]
did a "wsl --update", no i have 5.15.79.1-microsoft-standard-WSL2 aarch64
problem is still there

**Comment by elsaco** [comment]
This issue is being tracked by https://github.com/microsoft/WSL/issues/9090 You might benefit from updating your OS. I was experiencing the same issue on a Volterra box (Windows DevKit 2023) and with release `10.0.22621.963` the load is much better.

Sample reading with one instance of WSL running:

![task_mngr_with_wsl_running](https://user-images.githubusercontent.com/3933920/210027146-2485abdc-a348-4e04-bc84-e6b0e60a79f3.png)

CPU-6, CPU-7 and CPU-8 are `parked` according to the task manager, whatever that means!

**Comment by roadrunner-gs** [comment]
I got no newer version than the 21H2 offered.
The KB from the linked incident won't install on my system.
Got other problems with low network speed (and no newer drivers for the Qualcomm QCA639x available from HP or Qualcomm than the Microsoft ones from 10/2021)  - am thinking of returning the thing. :|

**Comment by roadrunner-gs** [comment]
kb5021255 says it is not suited for my computer.

**Comment by roadrunner-gs** [comment]
got 22H2 today.
22621.963 in winver.
Much better now, noch excessive load any more.
![image](https://user-images.githubusercontent.com/82960943/210064913-3afdfc83-f17b-40a5-bd32-f11d6e879270.png)
But i can't position the taskbar to the top anymore!
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3 will be overridden. :(

**Comment by roadrunner-gs** [comment]
Problem ist gone with 22H2 22621.963
