### ISSUE TITLE
Unable to launch after moving `/usr/lib/x86_64-linux-gnu`

### ISSUE THREAD

**Issue by gyk** [microsoft/WSL#9416]
### Version

WSL version: 1.0.3.0 Kernel version: 5.15.79.1 WSLg version: 1.0.47 MSRDC version: 1.2.3575 Direct3D version: 1.606.4 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22623.1037

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu-20.04

### Repro Steps

After executing the command

```sh
sudo mv /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu2
``` 

WSL is unable to launch, and I cannot operate on the directories from Explorer.

### Expected Behavior

Being able to run WSL.

### Actual Behavior

In Windows Terminal:

```bash
Processing fstab with mount -a failed.

<3>WSL (13) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 2
<3>WSL (13) ERROR: CreateProcessEntryCommon:579: Create process not expected to return

[process exited with code 1 (0x00000001)]
```

**Comment by zcobol** [comment]
@gyk renaming `/usr/lib/x86_64-linux-gnu` is not a smart move! `libc.so.6` lives there, along with many other libraries. Without `libc.so.6` there's no Ubuntu.

**Comment by gyk** [comment]
@zcobol Definitely a silly `mv`! Now how can I restore WSL? All my attempts to rename it back fail because of either no privilege or directory being locked. Can I mount the VHD and change the directories from outside?
