### ISSUE TITLE
Zram doesn't work on WSL2

### ISSUE THREAD

**Issue by Dhruvgera** [microsoft/WSL#9417]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.83

### Distro Version

Ubuntu 22.04

### Repro Steps

sudo apt install zram-config
wsl --shutdown
Start wsl distro
cat /proc/swaps

System has no zram device and is using swap on disk instead

### Expected Behavior

Expected behavior is for zram devices to show up. I have tried recompiling the WSL2 kernel with CONFIG_ZRAM=m and CONFIG_ZRAM_WRITEBACK=y but it still doesn't alleviate the issue

### Actual Behavior

Filename                                Type            Size            Used            Priority
/swapfile                               file            18874364        11386788        -2

On modprobe zram:
modprobe: FATAL: Module zram not found in directory /lib/modules/

**Comment by aki-k** [comment]
> On modprobe zram:
> modprobe: FATAL: Module zram not found in directory /lib/modules/

WSL 2 doesn't use kernel modules.

**Comment by Dhruvgera** [comment]
> > On modprobe zram:
> > modprobe: FATAL: Module zram not found in directory /lib/modules/
> 
> WSL 2 doesn't use kernel modules.

I have tried building it as is into the kernel with CONFIG_ZRAM=y, but zram still fails to load

**Comment by elsaco** [comment]
`zram` does work on WSL but you need to build/install the module and have the same custom built kernel loaded. To have `zram` devices available on each WSL distro you'll need to copy the `/lib/modules/` directory to each instance. While the kernel is being shared, modules are not. I didn't try to make a `system` distro with `zram` module, but it might work. This way kernel and modules are shared by each running WSL distro.

I'm using it with kernel  `6.1.2-microsoft-standard-WSL2`:

```
elsaco@RIPPER:~$ modinfo zram
filename:       /lib/modules/6.1.2-microsoft-standard-WSL2/kernel/drivers/block/zram/zram.ko
description:    Compressed RAM Block Device
author:         Nitin Gupta <ngupta@vflare.org>
license:        Dual BSD/GPL
srcversion:     1A796665923AA9A9E04E286
depends:        zsmalloc
retpoline:      Y
intree:         Y
name:           zram
vermagic:       6.1.2-microsoft-standard-WSL2 SMP preempt mod_unload modversions
parm:           num_devices:Number of pre-created zram devices (uint)
```

Output of `zram-config` service:

```
elsaco@RIPPER:~$ systemctl status zram-config
● zram-config.service - Initializes zram swaping
     Loaded: loaded (/lib/systemd/system/zram-config.service; disabled; vendor preset: enabled)
     Active: active (exited) since Sun 2023-01-01 13:44:41 PST; 2s ago
    Process: 390 ExecStart=/usr/bin/init-zram-swapping (code=exited, status=0/SUCCESS)
   Main PID: 390 (code=exited, status=0/SUCCESS)

Jan 01 13:44:41 RIPPER systemd[1]: Starting Initializes zram swaping...
Jan 01 13:44:41 RIPPER init-zram-swapping[400]: Setting up swapspace version 1, size = 2.9 GiB (3109179392 bytes)
Jan 01 13:44:41 RIPPER init-zram-swapping[400]: no label, UUID=3026ade5-ca3d-4fba-a244-3e1a9ab3df88
Jan 01 13:44:41 RIPPER systemd[1]: Finished Initializes zram swaping.
```

and `lsblk` output, showing `zram0` device:

```
elsaco@RIPPER:~$ lsblk
NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda     8:0    0 363.1M  1 disk
sdb     8:16   0     1T  0 disk /snap
                                /mnt/wslg/distro
                                /
zram0 251:0    0   2.9G  0 disk [SWAP]
```

**Comment by Dhruvgera** [comment]
> `zram` does work on WSL but you need to build/install the module and have the same custom built kernel loaded. To have `zram` devices available on each WSL distro you'll need to copy the `/lib/modules/` directory to each instance. While the kernel is being shared, modules are not. I didn't try to make a `system` distro with `zram` module, but it might work. This way kernel and modules are shared by each running WSL distro.
> 
> I'm using it with kernel `6.1.2-microsoft-standard-WSL2`:
> 
> ```
> elsaco@RIPPER:~$ modinfo zram
> filename:       /lib/modules/6.1.2-microsoft-standard-WSL2/kernel/drivers/block/zram/zram.ko
> description:    Compressed RAM Block Device
> author:         Nitin Gupta <ngupta@vflare.org>
> license:        Dual BSD/GPL
> srcversion:     1A796665923AA9A9E04E286
> depends:        zsmalloc
> retpoline:      Y
> intree:         Y
> name:           zram
> vermagic:       6.1.2-microsoft-standard-WSL2 SMP preempt mod_unload modversions
> parm:           num_devices:Number of pre-created zram devices (uint)
> ```
> 
> Output of `zram-config` service:
> 
> ```
> elsaco@RIPPER:~$ systemctl status zram-config
> ● zram-config.service - Initializes zram swaping
>      Loaded: loaded (/lib/systemd/system/zram-config.service; disabled; vendor preset: enabled)
>      Active: active (exited) since Sun 2023-01-01 13:44:41 PST; 2s ago
>     Process: 390 ExecStart=/usr/bin/init-zram-swapping (code=exited, status=0/SUCCESS)
>    Main PID: 390 (code=exited, status=0/SUCCESS)
> 
> Jan 01 13:44:41 RIPPER systemd[1]: Starting Initializes zram swaping...
> Jan 01 13:44:41 RIPPER init-zram-swapping[400]: Setting up swapspace version 1, size = 2.9 GiB (3109179392 bytes)
> Jan 01 13:44:41 RIPPER init-zram-swapping[400]: no label, UUID=3026ade5-ca3d-4fba-a244-3e1a9ab3df88
> Jan 01 13:44:41 RIPPER systemd[1]: Finished Initializes zram swaping.
> ```
> 
> and `lsblk` output, showing `zram0` device:
> 
> ```
> elsaco@RIPPER:~$ lsblk
> NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> sda     8:0    0 363.1M  1 disk
> sdb     8:16   0     1T  0 disk /snap
>                                 /mnt/wslg/distro
>                                 /
> zram0 251:0    0   2.9G  0 disk [SWAP]
> ```

Hi, thanks for your response! I am using the 5.15.83 kernel from Microsoft stable repo, and on doing make menuconfig, it seems only the zsmalloc module can be built, the zram module doesn't show up to enable and directly adding to the .config doesn't seem to build it either.

Can you send the sources for your 6.1.2 kernel? Or any guidance as to how I can compile and install this module? sudo make modules_install only copies over zsmalloc

**Comment by Dhruvgera** [comment]
> > `zram` does work on WSL but you need to build/install the module and have the same custom built kernel loaded. To have `zram` devices available on each WSL distro you'll need to copy the `/lib/modules/` directory to each instance. While the kernel is being shared, modules are not. I didn't try to make a `system` distro with `zram` module, but it might work. This way kernel and modules are shared by each running WSL distro.
> > I'm using it with kernel `6.1.2-microsoft-standard-WSL2`:
> > ```
> > elsaco@RIPPER:~$ modinfo zram
> > filename:       /lib/modules/6.1.2-microsoft-standard-WSL2/kernel/drivers/block/zram/zram.ko
> > description:    Compressed RAM Block Device
> > author:         Nitin Gupta <ngupta@vflare.org>
> > license:        Dual BSD/GPL
> > srcversion:     1A796665923AA9A9E04E286
> > depends:        zsmalloc
> > retpoline:      Y
> > intree:         Y
> > name:           zram
> > vermagic:       6.1.2-microsoft-standard-WSL2 SMP preempt mod_unload modversions
> > parm:           num_devices:Number of pre-created zram devices (uint)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Output of `zram-config` service:
> > ```
> > elsaco@RIPPER:~$ systemctl status zram-config
> > ● zram-config.service - Initializes zram swaping
> >      Loaded: loaded (/lib/systemd/system/zram-config.service; disabled; vendor preset: enabled)
> >      Active: active (exited) since Sun 2023-01-01 13:44:41 PST; 2s ago
> >     Process: 390 ExecStart=/usr/bin/init-zram-swapping (code=exited, status=0/SUCCESS)
> >    Main PID: 390 (code=exited, status=0/SUCCESS)
> > 
> > Jan 01 13:44:41 RIPPER systemd[1]: Starting Initializes zram swaping...
> > Jan 01 13:44:41 RIPPER init-zram-swapping[400]: Setting up swapspace version 1, size = 2.9 GiB (3109179392 bytes)
> > Jan 01 13:44:41 RIPPER init-zram-swapping[400]: no label, UUID=3026ade5-ca3d-4fba-a244-3e1a9ab3df88
> > Jan 01 13:44:41 RIPPER systemd[1]: Finished Initializes zram swaping.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and `lsblk` output, showing `zram0` device:
> > ```
> > elsaco@RIPPER:~$ lsblk
> > NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> > sda     8:0    0 363.1M  1 disk
> > sdb     8:16   0     1T  0 disk /snap
> >                                 /mnt/wslg/distro
> >                                 /
> > zram0 251:0    0   2.9G  0 disk [SWAP]
> > ```
> 
> Hi, thanks for your response! I am using the 5.15.83 kernel from Microsoft stable repo, and on doing make menuconfig, it seems only the zsmalloc module can be built, the zram module doesn't show up to enable and directly adding to the .config doesn't seem to build it either.
> 
> Can you send the sources for your 6.1.2 kernel? Or any guidance as to how I can compile and install this module? sudo ![Screenshot_20230102-074536_Microsoft_Remote_Desktop~2](https://user-images.githubusercontent.com/42107491/210191373-7582203e-d9f0-41bc-91cf-50867054315b.png) ![Screenshot_20230102-075444_Microsoft_Remote_Desktop~2](https://user-images.githubusercontent.com/42107491/210191396-0d9de027-ad17-4727-9327-d81aa5a0c38b.png) make modules_install only copies over zsmalloc

NVM, fixed it and now it works
