### ISSUE TITLE
Opening server logs or top on servers causing bash/ZSH to crash and cause high background usage.

### ISSUE THREAD

**Issue by marcusw89** [microsoft/WSL#9428]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #900-Microsoft Fri Jan 01 08:00:00 PST 2016

### Distro Version

Ubuntu-18.04

### Repro Steps

Cat any log file on any servers.

open TOP on any server.

### Expected Behavior

see logs or top depending on what I am after.

### Actual Behavior

Crash of WSL window. Nothing loads, pressing ENTER does nothing.

Closing of the WSL window causes it to still run in background using 60% or more CPU. Have to fully close using either powershell or task manager.

Other windows of WSL run fine during this but any opening of logs over 200ish lines causes it to do the same behaviour. 

### Diagnostic Logs

[WslLogs-2023-01-03_10-20-21.zip](https://github.com/microsoft/WSL/files/10335830/WslLogs-2023-01-03_10-20-21.zip)

**Comment by OneBlue** [comment]
@marcusw89: How big are the files you're trying to read ? If they're really big it can hang the terminal to hang.
