### ISSUE TITLE
AWS VPN disconnects, WSL terminal locks up

### ISSUE THREAD

**Issue by jgwinner** [microsoft/WSL#9434]
### Version

Microsoft Windows [Version 10.0.25267.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Setup an AWS VPN to a VPC.
2. Connect to the AWS VPN via Windows host.
3. Open WSL. Within the WSL CLI, Connect via SSH to an Ubuntu 20.04 AWS EC2 VM
4. Randomly, the connection will drop.
5. The WSL window will hard lock. 

### Expected Behavior

The terminal should drop back to the local terminal, or allow Ctrl+D to drop back to the local terminal. (The latter may be challenging as the Ctrl+D is processed by the remote side)

### Actual Behavior

The terminal completely locks up and will process no more keystrokes. It has to be hard closed with the 'x' button.

**Comment by OneBlue** [comment]
Thanks for reporting this @jgwinner. If the ssh connection drops, this is unfortunately the default ssh behavior. Does Ctrl-Z pause the ssh session when that happens ?

**Comment by jgwinner** [comment]
> If the ssh connection drops, this is unfortunately the default ssh behavior.

No, it is not, you're not listening.

If a remote server disappears, the LOCAL VM locks hard??? 

Other terminals, for example SSH from a Putty session from a server to another server, simply disconnect. The original session is fine. Only WSL locks hard, with the BASE session, local to the machine and not on the Internet, isn't available any more.

It is literally impossible to type Ctrl-Z, it's hard locked when this happens.
