### ISSUE TITLE
HCS_E_CONNECTION_TIMEOUT after following instructions to expand vdisk size

### ISSUE THREAD

**Issue by npaolini-8** [microsoft/WSL#9443]
### Version

Windows version: 10.0.19045.2364

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.79.1

### Distro Version

Ubuntu-22.04

### Repro Steps

Followed steps from [the vdisk size expansion article](https://learn.microsoft.com/en-us/windows/wsl/vhd-size) and after setting to 512000 , could not complete step 5 as WSL instance would not start.

### Expected Behavior

WSL instance opens and is usable.

### Actual Behavior

```
The operation timed out because a response was not received from the virtual machine or container.
Error code: Wsl/Service/CreateInstance/HCS_E_CONNECTION_TIMEOUT

[process exited with code 4294967295 (0xffffffff)]
```

Previous working state: Virtual Machine Platform enabled, Hyper V and Hypervisor platform disabled
Performed wsl --update, no change.
Attempted enabling Hyper V and Hypervisor platform, rebooted, no change. Tried disabling all 3, rebooting, re-enabling, rebooting, no change.

Additionally I am unable to open \wsl$\ in File Explorer

**Comment by npaolini-8** [comment]
[WslLogs-2023-01-06_11-34-48.zip](https://github.com/microsoft/WSL/files/10361616/WslLogs-2023-01-06_11-34-48.zip)

**Comment by OneBlue** [comment]
Looking at the logs, I see: 

```
63	False	Microsoft.Windows.Lxss.Manager	GuestLog	0	01/06/2023 08:35:05.023	"	"	"text: 	""[ 5522.148308] WSL (1) ERROR: Mount:1771: mount(/dev/sdd, /distro, ext4, 0x0, discard,errors=remount-ro,data=ordered ""
vmId: 	{e17ea923-3fdf-4956-9168-49d059750b2f}"				7088	3608	5		00000000-0000-0000-0000-000000000000		
```

Which is an indication that the filesystem is probably corrupted. 

Do you still have the logs of the exact command you used ? Looks like something corrupted the ext4 filesystem

**Comment by npaolini-8** [comment]
I don't have any logs, but anecdotally I followed the steps from [here](https://learn.microsoft.com/en-us/windows/wsl/vhd-size), using diskpart and setting the size to 512000. I did it following a fresh boot where I had not touched WSL, the disk mounted and expanded successfully, I can check the vhd file and see it has a max size of 500 gb.

**Comment by OneBlue** [comment]
How big was the disk before ? With modern WSL, the default maximum size is 1TB so I wonder if you actually reduced its size, which could cause corruption

**Comment by npaolini-8** [comment]
It was 256 before, the possible wrinkle here is that my hard drive was initially 500gb total, I recently added another 1TB drive, so I wanted to expand the max for long term use/future proofing before I forgot about it. Could it be that setting the vhd max to the same size as the original/formerly sole partition would cause the corruption?

**Comment by OneBlue** [comment]
It might. It's difficult to see for sure without having the exact commands and their output.

If you want to try to recover the files from the corrupted drive, you can try to follow [this article](https://www.tomshardware.com/how-to/recover-deleted-files-from-any-drive-in-linux) (with [wsl --mount](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl)  to mount the disk inside WSL)

**Comment by azscrs** [comment]
@npaolini-8 It appears that I just stumbled into the exact same behaviour after attempting to expand the wsl vdisk as you mentioned. Can I ask what was your solution?

**Comment by tlindquistjabra** [comment]
Same issue here, expanded a 256000 disk to 512000 and now it's bricked.
Followed this: https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-expand-the-size-of-your-wsl-2-virtual-hard-disk

**Comment by sam961124** [comment]
Same issue here. Do anyone know if there's a solution for this?
Followed the same instruction of expanding disk.

**Comment by npaolini-8** [comment]
Unfortunately my solution was deleting the instance and starting over. The
support person I was working with recommended mounting the old vdisk in a
new working instance to recover files if they were needed.

**Comment by Xthkeer** [comment]
Same issue, please delete this guide to prevent more people from ruining their own wsl
https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-expand-the-size-of-your-wsl-2-virtual-hard-disk
@msftgits
