### ISSUE TITLE
WSL --status has no kernal information

### ISSUE THREAD

**Issue by jack-liew** [microsoft/WSL#9448]
### Version

Windows 11 22H2 22621.963

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

no information

### Distro Version

Debian

### Repro Steps

When i exec: `wsl.exe --status`, The result only displays:

```
Default Distribution: Debian
Default Version: 2
```
![image](https://user-images.githubusercontent.com/102201538/210932118-7c007ee9-634c-4683-87d5-510db1e5517b.png)

??? where are the linux kernal information?

Thanks

**Comment by benhillis** [comment]
`wsl.exe --version`
