### ISSUE TITLE
Unable to use nvidia hardware acceleration codec in docker containers (with docker desktop).

### ISSUE THREAD

**Issue by EternalSaga** [microsoft/WSL#9449]
**Is your feature request related to a problem? Please describe.**
I try to use wsl2 with cuda in windows 11.  I followed the [official docker tutorial](https://docs.docker.com/desktop/windows/wsl/) and installed docker desktop, everything works fine till now.  
Then I try to use ffmpeg with nvidia hardware decoder in docker. 
Here is the simplest dockerfile to build the ffmpeg with nvidia acceleration. Dockerfile is inspired by this [documentation](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/)
```Dockerfile
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04 
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install build-essential yasm git cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev
WORKDIR /ffmpeg_src
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git && \
    cd nv-codec-headers && make install && cd /ffmpeg_src && \
    git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/ && \
    cd ./ffmpeg && \
    ./configure --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared && \
    make -j 8 && \
    make install && \
    cd /ffmpeg_src && rm -rf ./nv-codec-headers && rm -rf ./ffmpeg
```

Then I try to use this ffmpeg in docker.
```bash
docker run --rm -it --gpus=all -v /to_video_path:/video nv_ffmpeg:latest
```
Take a look at the compile flags and codec: 
```bash
# ffmpeg
ffmpeg version N-109530-g4a80db5fc2 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 56.100 / 59. 56.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 53.100 /  8. 53.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}
```
Then I tried to use the hwacc decoder:
```bash
ffmpeg -y -vsync 0 -c:v h264_cuvid -i ./some_videofile.mp4 
```
The ffmpeg reports error:
```bash
Unknown decoder 'h264_cuvid'
```

**Describe the solution you'd like**
I hope I can use nvdia hardware acceleration codec in wsl2 and docker.
**Describe alternatives you've considered**
In fact I use the libav* libraries in ffmpeg in my project, the error is "cannot find library libnvcuvid.so". I downloaded it and copy it into container but ffmpeg reported that the codec open failed.

**Comment by WooDeNDark** [comment]
I solved this problem. This is not a WSL or Docker issue. Try installing the **pkg-config** package. 
```
RUN apt-get -y install build-essential yasm git cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev pkg-config
```

**Comment by EternalSaga** [comment]
> 

Oh,  thank you for your reply, I will try your solution later.
