### ISSUE TITLE
Server connection could not be etablished. Error for installling WSL

### ISSUE THREAD

**Issue by BajajAditya123** [microsoft/WSL#9450]
"Failed to fetch the list distribution from 'https://raw.githubusercontent.com/microsoft/WSL/master/distributions/DistributionInfo.json'. A connection with the server could not be established
Error code: Wsl/InstallDistro/WININET_E_CANNOT_CONNECT"
Error while running "wsl --install -d Ubuntu"

**Comment by benhillis** [comment]
I suspect a temporary internet outage, could you try again?

**Comment by BajajAditya123** [comment]
the command is not working
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:1
+ Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by SirAbhi13** [comment]
Was there any update to this? @BajajAditya123 how did you solve this? suddenly started facing the same issue. WSL can't do anything and wont even connect or browse distros.
