### ISSUE TITLE
"A connection with the server could not be established" Error for "wsl --install -d Ubuntu"

### ISSUE THREAD

**Issue by BajajAditya123** [microsoft/WSL#9460]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu

### Repro Steps

`C:\Windows\System32>tracert.exe www.microsoft.com

Tracing route to e13678.dscb.akamaiedge.net [2405:200:1630:38e::356e]
over a maximum of 30 hops:

  1     3 ms     8 ms     3 ms  2405:201:401d:6836:1a82:8cff:feec:70e3
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     6 ms     6 ms    13 ms  2405:200:801:300::dec
  5     5 ms     5 ms     5 ms  2405:200:801:300::dec
  6     6 ms     6 ms     6 ms  2405:200:1604::1
  7     7 ms     8 ms     6 ms  2405:200:1630:38e::356e`

Trace complete.

C:\Windows\System32>

### Expected Behavior

Install WSL and Ubuntu

### Actual Behavior

![image](https://user-images.githubusercontent.com/84385465/211245305-789ea575-6712-49bb-b5ee-bff52ad6a131.png)
Error "A connection with the server could not be established"

**Comment by BajajAditya123** [comment]
anyone help me?

**Comment by benhillis** [comment]
Could you try `wsl.exe --install --web-download`?

Thanks!

**Comment by BajajAditya123** [comment]
The `wsl --install --web-download` worked but when I downloaded Ubuntu from Microsoft store it showed this error
![image](https://user-images.githubusercontent.com/84385465/211726455-1f94fea3-e1ed-4e3a-b61f-45299d30fb7f.png)

@benhillis

**Comment by BajajAditya123** [comment]
Still not Working
![image](https://user-images.githubusercontent.com/84385465/211738703-cb552ce7-0bd1-4d8f-b003-2d7011db49e1.png)
Same error 
@benhillis

**Comment by BajajAditya123** [comment]
The `wsl --install` command worked before I was collecting the logs. I don't know how. But When I was Installing then It was just saying `Installing WIndows Subsystem For Linux` not `Installing WSL Kernel` or `Installing GUI Support`

**Comment by nishantbhadauria** [comment]
is this issue resolved i am facing the same

**Comment by satvik644** [comment]
> is this issue resolved i am facing the same

If you are still facing the issue. Try running on vpn.

**Comment by Basit-Imam** [comment]
If you are in India and using Jio, try other Operator.
![image](https://user-images.githubusercontent.com/52064250/221417453-347b2088-9f53-44b2-b993-df6b2bdb587f.png)

**Comment by ashishkumarpalai** [comment]
its still not work for my sysstem

**Comment by satvik644** [comment]
i suggest to check these features -  "virtual machine platform" and "windows subsystem for linux feature"

You can find these features in TURN WINDOWS FEATURES ON OR OFF which is present in control panel under PROGRAMS

**Comment by Basit-Imam** [comment]
This worked for me after installing Ubuntu from windows store.
https://learn.microsoft.com/en-us/answers/questions/1112206/a-connection-with-the-server-could-not-be-establis

**Comment by ashishkumarpalai** [comment]
yahh im tried many time after install my computer is totally blank screen

**Comment by gautamsatpathy** [comment]
> If you are in India and using Jio, try other Operator. ![image](https://user-images.githubusercontent.com/52064250/221417453-347b2088-9f53-44b2-b993-df6b2bdb587f.png)

I had the same problem while using a JioFiber connection (India). Problem resolved on switching to Airtel for internet connection.

**Comment by SritharSrithar** [comment]
> > is this issue resolved i am facing the same
> 
> If you are still facing the issue. Try running on vpn.

i faced same issue for so long , jio user may be use vpn it works.Thanks

**Comment by Chitra2409** [comment]
> > If you are in India and using Jio, try other Operator. ![image](https://user-images.githubusercontent.com/52064250/221417453-347b2088-9f53-44b2-b993-df6b2bdb587f.png)
> 
> I had the same problem while using a JioFiber connection (India). Problem resolved on switching to Airtel for internet connection.

I was facing the same problem, switching to the airtel connection worked. Thanks!!

**Comment by hiteshsuthar** [comment]
Hi folks,

There is another alternative I just found and want to share with you guys.
I had just changed my DNS Server settings to manual and used Google's public DNS servers and it just worked fine.

You shall give it a try if you do not have other operator for internet connection. Try changing your DNS server to the following IP addresses. I hope it helps you too.

### Google's public DNS Servers:
1. 8.8.8.8
2. 8.8.4.4

![New_DNS_Settings](https://github.com/microsoft/WSL/assets/6513448/d098a7d3-dbdc-402e-82de-f57a595e856c)

**Comment by Vijay-CPP** [comment]
I've Jio & JioFiber connection and same issue, but when I tried using VPN it worked!

**Comment by chamanjain199** [comment]
> Hi folks,
> 
> There is another alternative I just found and want to share with you guys. I had just changed my DNS Server settings to manual and used Google's public DNS servers and it just worked fine.
> 
> You shall give it a try if you do not have other operator for internet connection. Try changing your DNS server to the following IP addresses. I hope it helps you too.
> 
> ### Google's public DNS Servers:
> 1. 8.8.8.8
> 2. 8.8.4.4
> 
> ![New_DNS_Settings](https://private-user-images.githubusercontent.com/6513448/274499113-d098a7d3-dbdc-402e-82de-f57a595e856c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjMxMDIsIm5iZiI6MTcwMzIyMjgwMiwicGF0aCI6Ii82NTEzNDQ4LzI3NDQ5OTExMy1kMDk4YTdkMy1kYmRjLTQwMmUtODJkZS1mNTdhNTk1ZTg1NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDUyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ5ZmJhNGMxMmM1MDhiNWYwZTJiNmExMjc1YzBiZWQ4MmI2Zjk1NGI4MDI3MTJmZTNmNDUxZDgwNDZmYjRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DST2SCnZelttbQlUqduhe1Tlg9VkGxsat4Ge6-AUSyY)
> 
> ### Final Result Here
> ![OutputEffectsOfChanging_DNS-Server-Settings](https://private-user-images.githubusercontent.com/6513448/274500977-d4e27943-276a-4104-aa08-aa71600fa296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjMxMDIsIm5iZiI6MTcwMzIyMjgwMiwicGF0aCI6Ii82NTEzNDQ4LzI3NDUwMDk3Ny1kNGUyNzk0My0yNzZhLTQxMDQtYWEwOC1hYTcxNjAwZmEyOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDUyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIwZDEyZjUwM2JlYjViNGY5ODc4YWE4NTgzMDM1MmQxYmUwNjhmOWE1MjVjNmQyMjBkNzcyYmE0ZmJmZWY3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jFDrFLVAuJ1gUDxIGVw5NyoqqHaxGYZ8LvhP0tAi71A)

Thanks, it worked for me

**Comment by Gaurav3124** [comment]
> Hi folks,
> 
> There is another alternative I just found and want to share with you guys. I had just changed my DNS Server settings to manual and used Google's public DNS servers and it just worked fine.
> 
> You shall give it a try if you do not have other operator for internet connection. Try changing your DNS server to the following IP addresses. I hope it helps you too.
> 
> ### Google's public DNS Servers:
> 1. 8.8.8.8
> 2. 8.8.4.4
> 
> ![New_DNS_Settings](https://private-user-images.githubusercontent.com/6513448/274499113-d098a7d3-dbdc-402e-82de-f57a595e856c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjU0MTIsIm5iZiI6MTcwMzc2NTExMiwicGF0aCI6Ii82NTEzNDQ4LzI3NDQ5OTExMy1kMDk4YTdkMy1kYmRjLTQwMmUtODJkZS1mNTdhNTk1ZTg1NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTIwNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZiZWI0MzEzMDU1ZTcwZjM0OTUzYjM2MzdkNDA5N2M5NDUyNjE4MzU0NDQ2YTM0NGViY2YyNmM5ZmNiYzNhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F5yR-r2ubXD50t_ppWZvWFQ6WgX3mCudQPLY_oytwts)
> 
> ### Final Result Here
> ![OutputEffectsOfChanging_DNS-Server-Settings](https://private-user-images.githubusercontent.com/6513448/274500977-d4e27943-276a-4104-aa08-aa71600fa296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjU0MTIsIm5iZiI6MTcwMzc2NTExMiwicGF0aCI6Ii82NTEzNDQ4LzI3NDUwMDk3Ny1kNGUyNzk0My0yNzZhLTQxMDQtYWEwOC1hYTcxNjAwZmEyOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTIwNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU0YmJhMGRmYTg4NGFhODg1MGQ1N2Q3MzRlZDM1NjE0NDRlNjIwY2ZkNGVkMmFhMWJkMzI1ZDIyMGY5N2M4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Srw1ln-IS_j4kRaGsPtrVh1HPv2efcn264JW9ZXdW9A)

This helped! Thank you!
