### ISSUE TITLE
Docker commands blocked only in WSL2 when KB5021233 is installed

### ISSUE THREAD

**Issue by lionelperrin** [microsoft/WSL#9461]
### Version

Microsoft Windows [Version 10.0.19044.2251]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3-microsoft-standard-WSL2

### Distro Version

Release:        10

### Other Software

Docker version 20.10.14, build a224086

### Repro Steps

1. Install windows update KB5021233
2. Open a distro with WSL2
3. Run `docker pull hello-world`

### Expected Behavior

The download of the image starts immediately.

### Actual Behavior

The download of the image starts after approx 5minutes.

The same test executed from a cmd window on the host runs as expected. If the KB is uninstalled, it runs as expected from WSL too.

**Comment by Biswa96** [comment]
Are you using Docker Desktop? Would you like to try without it, just by running dockerd?

**Comment by lionelperrin** [comment]
yes using docker desktop. I'm going to try to install docker directly on the wsl2 vm.

**Comment by lionelperrin** [comment]
If I install dockerd directly on a debian VM using WSL2, then docker pull works fine.

If I use docker desktop with an integration in the same debian VM using WSL2, then docker pull seems to be blocked. (5 minutes)

**Comment by kakuzei** [comment]
I'm having exactly the same issue with the `openSUSE-Leap-15-1` distro and `Docker Desktop`.
Running a `docker pull hello-world` command takes minutes:
```
user@host:~> time docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:aa0cc8055b82dc2509bed2e19b275c8f463506616377219d9642221ab53cf9fe
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

real    4m18.117s
user    0m0.071s
sys     0m0.019s
```
I'm able to reproduce it with the `Ubuntu 22.04.1 LTS` distro and `Docker Desktop`: 
```
user@host:~$ time docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:aa0cc8055b82dc2509bed2e19b275c8f463506616377219d9642221ab53cf9fe
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

real    4m15.514s
user    0m0.018s
sys     0m0.018s
```

I don't have the issue when I run the same command with the `Ubuntu 22.04.1 LTS` distro and `dockerd`:
```
user@host:~$ time docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:aa0cc8055b82dc2509bed2e19b275c8f463506616377219d9642221ab53cf9fe
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

real    0m3.668s
user    0m0.035s
sys     0m0.000s
```
This issue started after the installation of the KB5021233.
When I remove the KB5021233, I don't have this issue anymore.
Installing the KB5021233 + KB5022282 + upgrading WSL to version 1.0.3 does not solve the issue.

**Comment by lionelperrin** [comment]
many thanks for your reply. I've captured the lgos. Is there a way for me to share it only with WSL team ? (and not publicly on github)

**Comment by kakuzei** [comment]
This issue has been solved, more details here: https://github.com/docker/for-win/issues/10247#issuecomment-1468035897
