### ISSUE TITLE
Virtual Machine Platform breaks NTLM authentication for Users with non ASCII names on Windows 11

### ISSUE THREAD

**Issue by Qowy** [microsoft/WSL#9468]
I know that this is not an issue of WSL but I have no idea how to report this to the core windows Team.
So please either point me in the right direction or forward it to the appropriate people.

I can reproducibly break NTLM authentication for the entirety of Windows (Edge and Firefox are both affected) by enabling the Virtual Machine Platform optional feature.

- We have a Windows AD environment.
- Some of our users have non ASCII characters in their username (for example ü, which is fully supported)
- When we got new lenovo Windows11 Laptops I noticed that for those users NTLM authentication with our IIS intranet site was not working.
- After much tinkering I narrowed the issue down to enabling Virtual Machine Platform (which is on by default in the lenovo image)
- I reproduced the issue on a Dell Laptop with Windows 11, disabling Virtual Machine Platform made it work again.
- However disabling Virtual Machine Platform on the Lenovo Laptop/Image is not working even after a windows System reset
- Only a new fresh install from the Microsoft Windows 11 base image without enabling Virtual Machine Platform made it work.

So to summarize (All newest Windows 10/11 22H2 Release as of 2023-01-10)

- Lenovo Laptop Factory Windows 11 Image enabled VMP -> not working
- Lenovo Laptop Factory Windows 11  Image disabled VMP -> not working
- **Lenovo Laptop Microsoft Windows 11 Image disabled VMP -> working**
- Lenovo Laptop Microsoft Windows 11 Image enabled VMP -> not working
- **Lenovo Laptop Microsoft Windows 11 Image disabled again VMP -> working**
- **Dell Laptop Upgraded Factory Windows 11 Image disabled VMP -> working**
- Dell Laptop Upgraded Factory Windows 11 Image enabled VMP -> not working
- Dell Laptop Upgraded Factory Windows 11 Image disabled again VMP -> working
- **Dell Laptop Factory Windows 10 Image disabled VMP -> working**
- **Dell Laptop Factory Windows 10 Image enabled VMP -> working**

Again please tell me how to properly report this issue, since normal customer support is clearly not cut out to handle this.
Not only do I have to reimage all of my Lenovo laptops, but also avoid upgrading to Windows 11 if I want to use WSL2

**Comment by benhillis** [comment]
@Qowy - thanks for reporting. You're right, this isn't WSL specific so the best bet would be to report this via feedback hub. Thanks!
