### ISSUE TITLE
Installation reported "The server name or address could not be resolved"

### ISSUE THREAD

**Issue by ktrNozomi** [microsoft/WSL#9470]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

NULL

### Distro Version

NULL

### Other Software

NULL

### Repro Steps

![image](https://user-images.githubusercontent.com/86712470/211623989-c879feb1-87aa-4543-b673-84661e8a9b89.png)

### Expected Behavior

It should be installed automatically.

### Actual Behavior

![image](https://user-images.githubusercontent.com/86712470/211624078-36b6d65c-572e-4048-a732-397c2d06aecc.png)

**Comment by ktrNozomi** [comment]
It's solved by enabling system proxy in Clash for Windows, I don't know why...

**Comment by OneBlue** [comment]
Closing since the issue was solved

**Comment by vighnesh153** [comment]
Clash can be downloaded from here: https://www.clashforwindows.net/clash-for-windows-download/

**Comment by harryob2** [comment]
thank you @ktrNozomi @vighnesh153 , such a weird issue lol. any theories as to why this works?

**Comment by chamalkaMarasinghe** [comment]
Both of you saved my 1 or 2 days in life : @ktrNozomi @vighnesh153 - (worked for windows 11 pro 22H2)

**Comment by Zenitugo** [comment]
Thank you so much @ktrNozomi and @vighnesh153. I wish I could hug you both right now.

**Comment by larry100y** [comment]
I configure my DNS to 114.114.114.114 and 8.8.8.8 (you may need `ipconfig /flushdns`), then hostname can be resolved. My ISP is ChinaTelecom.

**Comment by rishav0821** [comment]
wsl is not getting installed after using clash for windows too

**Comment by ft-scobra** [comment]
@ktrNozomi @vighnesh153 Thanks a lot! I couldn't find a solution anywhere before this.
