### ISSUE TITLE
Read-only  file system

### ISSUE THREAD

**Issue by tonycody** [microsoft/WSL#9474]
### Version

Windows Feature Experience Pack 1000.25272.1000.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 22.04

### Repro Steps

![image](https://user-images.githubusercontent.com/6773121/211987542-70dedfac-460f-42a6-8f67-556f498622b0.png)

Computer A, a system installed in vhdx mode, which includes WSL.

When the vhdx file on computer A is migrated to computer B, the WSL on it opens the prompt read-only system.

### Expected Behavior

nothing

### Actual Behavior

nothing

### Diagnostic Logs

nothing

**Comment by benhillis** [comment]
How did you migrate the VHD? Could you please ensure the vhd on the new system is not marked as read-only?
