### ISSUE TITLE
Getting issue while installing wsl

### ISSUE THREAD

**Issue by sameerjoshinice** [microsoft/WSL#9476]
### Version

Microsoft Windows [Version 10.0.22000.1335]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Not able to install wsl on my Windows machine.

Doing install I get following:

wsl --install
Installing: Windows Subsystem for Linux
Error: 0x80240066==========90.0%=====================      ]

### Expected Behavior

wsl should get installed. 

### Actual Behavior

wsl is not getting installed

**Comment by benhillis** [comment]
That error is WU_E_INSTALL_USERCONTEXT_ACCESSDENIED. Could you please try `wsl.exe --install --web-download`?
