### ISSUE TITLE
WSL help cannot help user.

### ISSUE THREAD

**Issue by char-46** [microsoft/WSL#9478]
### Version

10.0.22621.1105

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Repro Steps

In Chinese environment.

Type `wsl --help`

### Expected Behavior

Something shouldn't translate. Such as this:
```
\\...
    -shell-type <类型>-
        使用提供的 shell 类型执行指定的命令。

        类型:
            标准
                使用默认 Linux shell 执行指定的命令。

            登录
                使用默认的 Linux shell 作为登录 shell 执行指定的命令。

            无
                在不使用默认 Linux shell 的情况下执行指定的命令。
\\...
```

### Actual Behavior

They were mistranslated.

**Comment by OneBlue** [comment]
Fixed in WSL 1.1.0.
