### ISSUE TITLE
Lost access to Win 11 FS within WSL2 instances, <3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate issues?

### ISSUE THREAD

**Issue by johnkennyuk** [microsoft/WSL#9481]
### Version

Windows version: 10.0.25276.1000

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu

### Other Software

Docker Desktop, 
VSCode Insiders,
Terminal,

### Repro Steps

Any launch of any WSL2 distro always returns mount errors, it is passing from windows pure ENV path variables in windows format, however, I don't know if this is the cause of my mount problems.  I've tried any troubleshooting steps I can find online, but nothing has resolved the issue that I've suffered for over 6 months now, I kept hoping an update one day would fix the problem, but it hasn't.  Windows to WSL2 filesystem access still works just not WSL2 to Windows

### Expected Behavior

I should be able to access Windows Filesystem withing WSL2 instances as I can from Windows Explorer to Linux / WSL2 Instances

### Actual Behavior

<3>WSL (9) ERROR: CreateProcessParseCommon:782: Failed to translate C:\Users\username
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\PowerShell\7
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Python311\Scripts\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Python311\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Common Files\Oracle\Java\javapath
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Common Files\Oracle\Java\javapath
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\wbem
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\ProgramData\chocolatey\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\dotnet\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate P:\Azure Data Studio\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\WinSCP\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\ProgramData\chocolatey\lib\Minikube
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\IncrediBuild
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Microsoft SQL Server Migration Assistant for Access\bin\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\cloudflared
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Microsoft\Azure Functions Core Tools\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\system32
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate h:\HV\Multipass\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\minikube
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\PuTTY\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Tailscale IPN
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate E:\WORKING\DEV\GO\mage_1.14.0_Windows-64bit
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate c:\src\platform-tools
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Roaming\Python\Python311\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\PowerShell\7\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files (x86)\Nmap\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Go\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\Git\cmd
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\nodejs\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\HashiCorp\Vagrant\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\TorchStudio\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Roaming\Python\Scripts
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\PowerShell\7-preview\preview
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\system32
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\Wbem
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\WindowsPowerShell\v1.0\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\System32\OpenSSH\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Enthought\edm\
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Roaming\.dotnet
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\.cargo\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate P:\scoop\shims
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\Microsoft\WindowsApps
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\go\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\GitHubDesktop\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate p:\Azure Data Studio\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\.dotnet\tools
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\Programs\Bicep CLI
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\JetBrains\JetBrains Gateway 2022.2.1\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\dapr
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\.dapr\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\JetBrains\PyCharm 2022.3\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\JetBrains\Toolbox\scripts
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\JetBrains\JetBrains Gateway 2022.3\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\go\bin
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Roaming\npm
<3>WSL (9) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\username\AppData\Local\Microsoft\WindowsApps
Failed to mount C:\, see dmesg for more details.
Failed to mount E:\, see dmesg for more details.
Failed to mount H:\, see dmesg for more details.
Failed to mount P:\, see dmesg for more details.
Failed to mount V:\, see dmesg for more details.

sajk@JKPC:~$

### Diagnostic Logs

[WslLogs-2023-01-14_14-11-36.zip](https://github.com/microsoft/WSL/files/10417875/WslLogs-2023-01-14_14-11-36.zip)

 wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                 DeviceID            InterfaceType  MediaLoaded  MediaType              Model                                  Name                Partitions
              {3, 4}        {"Random Access", "Supports Writing"}  \\.\PHYSICALDRIVE0  SCSI           TRUE         Fixed hard disk media  Samsung SSD 980 PRO 1TB                \\.\PHYSICALDRIVE0  6
              {3, 4}        {"Random Access", "Supports Writing"}  \\.\PHYSICALDRIVE1  SCSI           TRUE         Fixed hard disk media  NVMe Samsung SSD 970 SCSI Disk Device  \\.\PHYSICALDRIVE1  2

**Comment by OneBlue** [comment]
Thank you for reporting this @johnkennyuk. I'm not seeing the WSL boot logs in the file you shared. Can you please run wsl.exe --shutdown and then run the log collection so we can see the WSL boot logs ?

**Comment by johnkennyuk** [comment]
sorry for the delay, attached wsl logs after wsl --shutdown
[WslLogs-2023-01-21_14-16-16.zip](https://github.com/microsoft/WSL/files/10472332/WslLogs-2023-01-21_14-16-16.zip)

**Comment by OneBlue** [comment]
Thank you @johnkennyuk.

I've added more logging to our log collection script to help diagnose your issue.
Can you please run the log collection script again and share the new logs? 
/logs

**Comment by johnkennyuk** [comment]
apologies for the delay, see attached!
[WslLogs-2023-02-01_13-48-59.zip](https://github.com/microsoft/WSL/files/10557639/WslLogs-2023-02-01_13-48-59.zip)

**Comment by johnkennyuk** [comment]
was that new log of any use?

**Comment by petrsnm** [comment]
I am seeing the same problem, however, I've found that if I do not run Docker Desktop, the problems goes away.

**Comment by johnkennyuk** [comment]
Problem is no longer an issue since performing a clean install as well as wsl2 Update have mitigated probably since
