### ISSUE TITLE
WSL doesn't update itself, or Install Ubuntu giving error 0x80072efd

### ISSUE THREAD

**Issue by arshdeepsch** [microsoft/WSL#9482]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.16

### Distro Version

Ubuntu

### Repro Steps

Update wsl through wsl --update.
Install Ubuntu through wsl --install -d Ubuntu
Install Ubuntu through the Microsoft Store

### Expected Behavior

Install Ubuntu.

### Actual Behavior

![image](https://user-images.githubusercontent.com/40446715/212521084-fc7ba9d0-9f65-43cb-987b-0670899e6733.png)
![image](https://user-images.githubusercontent.com/40446715/212521088-60dab771-e7c3-4aed-87ab-bc7be5a8d962.png)
![image](https://user-images.githubusercontent.com/40446715/212521122-caa08354-9483-4aa0-9c50-d7952adf5dcd.png)

When installing through the store, the button goes grey for a while, and turns back blue.

### Diagnostic Logs

[WslLogs-2023-01-14_22-09-16.zip](https://github.com/microsoft/WSL/files/10419382/WslLogs-2023-01-14_22-09-16.zip)

**Comment by pmartincic** [comment]
Looks like the machine doesn't have an internet connection?

Also, did you let the logs collect while reproducing the issue? It only collects the logs while the script is running.

**Comment by J-XL** [comment]
I encountered this on a corporate network where access to the Microsoft store was blocked.  Using --web-download allowed the installation to complete successfully.
