### ISSUE TITLE
p9rdr.sys BSOD after shutting down and restarting WSL when there are file handles open for mounted directories/files

### ISSUE THREAD

**Issue by F21** [microsoft/WSL#9484]
### Version

Microsoft Windows 11 22H2 22621.1105

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

Ubuntu 22.04.1 LTS

### Repro Steps

1. In WSL, change the directory to a mounted directory: `cd /mnt/c/something`.
2. Shutdown WSL in powershell in a new tab: `wsl --shutdown`.
3. Close the WSL tab.
4. Open a new WSL tab and let it start.
5. BSOD due to `p9rdr.sys` crashing.

### Expected Behavior

A BSOD should not happen.

### Actual Behavior

`p9rdr.sys` BSODs and crashes the system.

**Comment by OneBlue** [comment]
Thanks for reporting this @F21. Can you please follow the ['Reporting a Windows crash (BSOD) section'](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#10-reporting-a-windows-crash-bsod) so we can have a look ?

**Comment by Makishima** [comment]
I send bsod dump to the secure@microsoft.com today.
Hope it will be fixed.

**Comment by 0anton** [comment]
got the same crash now

**Comment by marcelschoen** [comment]
Got the exact same crash, also while running "wsl --shutdown" (for WSL2 / Ubuntu).

**Comment by magoun** [comment]
I'm contemplating uninstalling / reinstalling Docker Desktop and WSL2 to see if that fixes the issue, but it seems like overkill.

**Comment by magoun** [comment]
My issue was similar. On loading Docker Desktop (WSL2 backend), it would hang on engine start, then BSOD. Reinstalling Docker Desktop has solved my issue, though I lost all the data in those containers.

**Comment by ntextreme3** [comment]
Same just after `--shutdown` and trying to relaunch. My `wsl --version` is: 

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2965
```

**Comment by Heather-Herbert** [comment]
Same issue here as well
My wsl --version info is
```

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2965
```

**Comment by kkettinger** [comment]
Same issue here as well.

As soon as i start Docker Desktop, i get this error message:
![grafik](https://github.com/microsoft/WSL/assets/83078716/419e6608-dadd-4add-baab-fb37c8a7acf6)

Then some seconds later, the system crashes with `RDS_FILE_SYSTEM` and `p9rdr.sys`.
![grafik](https://github.com/microsoft/WSL/assets/83078716/29463911-7840-4fae-a3a5-bbebb3289961)

I've upgraded yesterday from Docker Desktop 4.19 to 4.20.1. Issue persists when downgrading again to 4.19.

```
PS C:\> wsl --version
WSL-Version: 1.2.5.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.51
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.3086
```

Interestingly, 4.19 shows an error box shortly before crashing:
```
System.Exception:
2 errors occurred:
	* starting keep alive in the data distro: waiting for wsl-keepalive to be ready: running wsl-keepalive in "docker-desktop-data": exit status 0xffffffff
	* checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The I/O operation has been aborted because of either a thread exit or an application request.


   bei Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__10.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:Zeile 93.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:Zeile 29.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:Zeile 79.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:Zeile 108.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__17.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:Zeile 97.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Engines.Engines.<StartAsync>d__25.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:Zeile 126.
```

**Comment by kkettinger** [comment]
I somehow fixed it. I installed the latest windows updates, the Windows-Version changed from `10.0.19045.3086` to `10.0.19045.3155`.

I have unregistered all wsl distributions:
```
wsl -l -v
wsl --unregister Ubuntu
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

And then restarted Docker Desktop - now it works.

**Comment by paramsiddharth** [comment]
Is there absolutely no solution to it that doesn’t involve unregistering my WSL distros?

**Comment by PAnandanGit** [comment]
I can't imagine Microsoft pretending to look into the issue and does practically nothing but close it.

**Comment by RzNmKX** [comment]
I'm now in a fun reboot loop where Docker Desktop tries to start whatever WSL and then I get about 1 minute until the BSOD. Not fun

**Comment by RzNmKX** [comment]
> I'm now in a fun reboot loop where Docker Desktop tries to start whatever WSL and then I get about 1 minute until the BSOD. Not fun

unregistering the docker-desktop-data WSL fixed it for me. Didn't have the option to unregister docker-desktop so didn't do that one
