### ISSUE TITLE
Error code: Wsl/Service/CreateVm/ConfigureNetworking/ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by mferreirak** [microsoft/WSL#9488]
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-22621

### Distro Version

Ubuntu 20.04

### Repro Steps

My objective is to install ubuntu with wsl2 so I can use Docker. Installing directly wsl2 with Ubuntu gives me an error, so I'm trying a different way.

In a powershell console:
1.` wsl --install`
2. `wsl --set-default-version 1`
3. `wsl --install -d Ubuntu-20.04`
4. `wsl --set-version Ubuntu-20.04 2`

### Expected Behavior

Ubuntu-20.04 installed

### Actual Behavior

In the the powershell after `wsl --set-version Ubuntu-20.04 2`:

> Conversion in progress, this may take a few minutes...
> The system cannot find the file specified.
> Error code: Wsl/Service/CreateVm/ConfigureNetworking/ERROR_FILE_NOT_FOUND

**Comment by markarnott** [comment]
Are you sure Ubuntu-20.04 finished installing before you executed the --set-version command?

What is the output on a powershell console when you execute the following command?

wsl --list --verbose

**Comment by CGH20171006** [comment]
[WslLogs-2023-07-13_15-23-24.zip](https://github.com/microsoft/WSL/files/12036596/WslLogs-2023-07-13_15-23-24.zip)
@msftbot This is the logs file when I meet this Error

**Comment by Siddharth1India** [comment]
Any solution?
