### ISSUE TITLE
Connection SSH > tmux : cannot use page down / up 

### ISSUE THREAD

**Issue by BarbareBzhdev** [Microsoft/WSL#949]
### Description

When I connect with ssh in my server unix, I use tmux for multiplex and Ctrl-b + PageDown/Up for slide in windows. But this one doesn't work. Hower that work when I use Tmux directly into BashOnWindows without ssh connection.
### Expected results

Slide Up or Down in tmux windows
### Actual results (with terminal output if applicable)

Just write the ascii caratere "[5~"
### Your Windows build number

Version 10.0.14393 Build 14393
- Steps / commands required to reproduce the error
  ssh _serverUnix_
  tmux
  cat /dev/urandom
  Ctrl-c
  Ctrl-b + PageUp

Thanks you and thanks for this wander  :)

**Comment by sthalik** [comment]
This is a terminfo problem.

**Comment by zadjii-msft** [comment]
@BarbareBzhdev I'm not seeing this reproduce for me. 
Can you do a `infocmp | grep 5~` and make sure that on the remote machine `kpp=\E[5~`? I agree with @sthalik that this is probably a terminfo problem

**Comment by bitcrazed** [comment]
@BarbareBzhdev: Please help us with the repro request above.

**Comment by BarbareBzhdev** [comment]
Sorry if i never respond you, i stay with sthalik's response and i don't see your message... :'(
I closed this issue. If i take few time to test again with all new version between my older message and see against this error, i'll reopen it.
