### ISSUE TITLE
WSL2 - Bridged networking - fixed MAC address

### ISSUE THREAD

**Issue by nwaelti** [microsoft/WSL#9492]
### Version

Windows version: 10.0.22621.1105

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Debian 11.2

### Repro Steps

1. Add Hyper-V Switch on External Network
2. Add in .wslconf the following lines:
`[wsl2]
networkingMode=bridged
vmSwitch=<my_switch_name>`
3. Restart WSL with `wsl --shutdown`
4. Repeat operation on a second machine on your LAN

### Expected Behavior

I was expecting each WSL to have a different MAC address

### Actual Behavior

Both machines do come up with the same MAC address: `5c:bb:f6:9e:ee:fa`, not taking in consideration what had been set as Default MAC Range in Hyper-V Virtual Switch Manager.
Our DHCP does not really like that :)

**Comment by nwaelti** [comment]
I've searched for a way to actually change the MAC address of my WSL2, but with no success...

Anybody else having the same issue? According to a web search, Alistair Young (https://randombytes.substack.com/p/bridged-networking-under-wsl) seems to have the same MAC address as well.

**Comment by shigenobuokamoto** [comment]
you can add to .wslconfig
```
macAddress="01:23:45:67:89:ab"
```

**Comment by nwaelti** [comment]
Thanks ;) you made my day

**Comment by niconiconi1234** [comment]
I also face the same problem. All WSL instances share the same mac and ip address. I was expecting each WSL to have a different MAC address
