### ISSUE TITLE
Lots of issues I guess, just can't get wsl working

### ISSUE THREAD

**Issue by Shikamaru5** [microsoft/WSL#9501]
So I've done the steps set by many, many different articles and videos, I've even had someone who used to be on the development team for wsl ubuntu try helping me on Twitter, but I've yet to get it working. There's been a few times where I've gotten wsl downloaded enabled wsl2 the update and kernel are good, and ubuntu downloaded with username and password set up, to have it that when I type in wsl, nothing happens. Currently though the issue it shows is:
 The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
It's enabled, the virtualization is enabled too. I had it working but the python was too old, I accidentally broke that so I decided to uninstall and reinstall wsl and ubuntu, but now it just won't ever work. Idk what to do... the things I've tried:

wsl --install or wsl --update or download wsl from microsoft store
enable online features, enable windows subsystem for linux
wsl --set-version 2
wsl --install -d ubuntu
install ubuntu on microsoft store, all three versions have been tried.
making sure I restart after every step, although my computer really hates that.
setting up username and password on ubuntu
type in wsl and nothing works.
Going to the recommended sites when something stalls me.

I don't have any third party security software running, just on local, I'm on windows 10 version 22H2 (OS build 19045.2545)
I've tried dism.exe/online/enable-feature/featurename:Microsoft-windows-subsystem-Linux/all/norestart and the same for vm
Not sure what else to try but I need to solve it now because it's even corrupted my command line in sublime text just trying to run regular programs in windows

**Comment by OneBlue** [comment]
@Shikamaru5: Can you describe the exact command you're running and the output / errors you're getting so we can help diagnose the issue ?

**Comment by Shikamaru5** [comment]
alright so I'll try and do my best, I've screenshotted pics of what I've done.

![wsl4](https://user-images.githubusercontent.com/86502093/213038436-2ee7606c-9884-49d7-a9aa-a97902a08706.jpg)
had to use the update command because just typing wsl --install provides an error. I restarted after doing that.

![wsl2](https://user-images.githubusercontent.com/86502093/213038697-359946f1-f0f6-4a0b-83f2-a2f6e53b4757.jpg)

set it to version 2 of wsl and that seemed to work alright.

![wsl](https://user-images.githubusercontent.com/86502093/213038541-c80b13ff-0bf8-417a-9156-6765d9f1762f.jpg)
Tried installing Ubuntu and when it loaded up Ubuntu didn't work.

![wsl3](https://user-images.githubusercontent.com/86502093/213038781-c173899f-b23c-4078-b58a-615494eeef44.jpg)

Tried to see if wsl was working and it said it required an update, so I visited the website to see and I got the required file.

![wsl5](https://user-images.githubusercontent.com/86502093/213038929-2892a0ab-0470-4dee-b2eb-7bf63ecd5c5b.jpg)

![ubuntu](https://user-images.githubusercontent.com/86502093/213038941-8ffef720-e012-4cfa-a0b7-89c34f7dc788.jpg)

![vm](https://user-images.githubusercontent.com/86502093/213038946-23bc53b4-c42f-4a0a-baf2-7f0afc74fcff.jpg)

![wsl6](https://user-images.githubusercontent.com/86502093/213038962-52702a1b-bc4c-4f73-92cd-67eed12fffb5.jpg)

The remaining are just what my machine says that I have but I can't think of any other steps that I need to do according to looking online. I hope this looked alright and wasn't too confusing.

**Comment by OneBlue** [comment]
@Shikamaru5: Did you install the kernel component as the error message suggested ? You can find instructions on how do that here: https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by Shikamaru5** [comment]
Ya I did, I have x64 so I just downloaded the link [WSL2 Linux kernel update package for x64 machines](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

**Comment by OneBlue** [comment]
Did you install it ?

**Comment by OneBlue** [comment]
Does wsl work after installing the kernel ? If not, can you please capture /logs ?
