### ISSUE TITLE
Set version to WSL '1' fails with 'Invalid command line option'

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/WSL#9503]
### Discussed in https://github.com/microsoft/WSL/discussions/9487

<div type='discussions-op-text'>

<sup>Originally posted by **DavidA2014** January 16, 2023</sup>
Windows 11 build 10.0.22000

Hi, we have installed WSL with Ubuntu 22.04 on Windows 11 on one of our engineer's laptops. We set the default version to 1 before installing Ubuntu (from an admin cmd prompt):

`wsl --set-default-version 1`

but Ubuntu still ended up being version 2. From a non-admin command prompt:

```>wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-22.04    Stopped         2
```

We want WSL version 1. So we execute:

`wsl --set-version Ubuntu-22.04 1`

from a non-admin cmd prompt. That gives:

`Invalid command line option: --set-version`

Why does that command fail?</div>

**Comment by 0xbadfca11** [comment]
``wsl.exe --install`` without ``--enable-wsl1`` does not enable WSL1.
You needs enable "Windows Subsystem for Linux" optional component.

**Comment by OneBlue** [comment]
Thanks for reporting this @DavidA2014. 


Until the fix is backported, you can use [store WSL](http://aka.ms/wslstorepage) to change your distribution version to WSL1
