### ISSUE TITLE
Ubuntu app error code 80070008 (registering with WSL2?)

### ISSUE THREAD

**Issue by TDavidHudson** [microsoft/WSL#9509]
### Version

Microsoft Windows [Version 10.0.19045.2364]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

1) Install WSL2 per https://learn.microsoft.com/en-us/windows/wsl/install-manual .
2) Because Microsoft Store is blocked (both for browser and for "wsl --install"), install "Ubuntu 20.04 (2021)" from SCCM.
3) (variant) add %UserProfile%\.wslconfig with two lines "[wsl2]" and "memory=4GB # Limits VM memory in WSL 2 to 4 GB
" (also tried 8GB).
4) Run (a) Ubuntu from the Start menu (cannot run elevated, nor as administrator) or (b) ubuntu.exe in an elevated cmd.exe window with working directory C:\Temp .  This is with nearly 21GB free memory out of about 31GB.

NOTE: Windows+F doesn't work, and I don't have administrator permissions.

### Expected Behavior

I was expecting ubuntu.exe to at least register with WSL2 (since wsl --list is empty), and perhaps to do more.

### Actual Behavior

This is what was output in the Ubuntu window (and "wsl --list" still shows no distributions):
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070008
Error: 0x80070008 Not enough memory resources are available to process this command.

Press any key to continue...

**Comment by TDavidHudson** [comment]
[WslLogs-2023-01-24_08-43-30.zip](https://github.com/microsoft/WSL/files/10490639/WslLogs-2023-01-24_08-43-30.zip)
I was given admin permission for this, so I was able to run the script to get the logs.  Note that VMware is installed on the laptop, but it makes no difference whether its services are running or not, for this error.

**Comment by OneBlue** [comment]
Thanks @TDavidHudson. Looking at the logs, I see:
```
1013	True	Microsoft.Windows.Lxss.Manager	Error	0	01-24-2023 05:55:11.521	"	"	"code: 	
failurecount: 	1
file: 	onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp
function: 	
hr: 	0x80070008
linenumber: 	1423
message: 	""HcnCreateNetwork failed {""""Success"""":false,""""Error"""":""""Not enough memory resources are available to process this command. """",""""ErrorCode"""":2147942408}""
threadid: 	15532
type: 	0"	onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp			17424	15532	2		00000000-0000-0000-0000-000000000000		

```

Which seems to indicate that there was not enough memory available on your machine. 

How much memory was available on your machine when WSL started ? Can you share a screenshot of the 'Performance' tab in TaskManager ?

**Comment by TDavidHudson** [comment]
![image](https://user-images.githubusercontent.com/123087292/214558757-ffeeb966-f551-4fb5-8422-e123d2f3679d.png)
As I mentioned initially, there was nearly 21GB free memory, despite the error code indicating insufficient memory.  Now, after some reinstalls, there is still over 19GB free.  It's supposed to be possible to run WSL (actually, ubuntu.exe) in only 8GB, right?  And I still have the 8GB .wslconfig file in my home directory.

**Comment by OneBlue** [comment]
Interesting. This error was return from HNS, so this shouldn't be related to the memory settings in WSL. @keith-horton: Is there something we can do to diagnose why HNS returned that error ?

**Comment by TDavidHudson** [comment]
Around the time of the ubuntu.exe error, there are two closely spaced "Metadata staging failed, result=0x80070490 for container '{00000000-0000-0000-FFFF-FFFFFFFFFFFF}'" errors reported by Microsoft-Windows-DeviceSetupManager/Admin .  There is also a "HNS-Network-Create :- 
 Network id = '{b95d0c5e-57d4-412b-b571-18a81a16e005}'.
 Network type = 'ICS'.
  Result code = '0x80070008'. " error, which you've seen, reported by Microsoft-Windows-Host-Network-Service-Admin.  There are three almost simultaneous errors "'IpICSHlpStopDnsServer' : '0x80070490'.", "'IpICSHlpStartDnsServer' : '0x80070008'." and again "'IpICSHlpStopDnsServer' : '0x80070490'." also reported by HSN.

This is probably irrelevant, but about a half hour before the ubuntu.exe error, with a reboot intervening, there is a "The hns service depends on the VfpExt service which failed to start because of the following error: 
A device attached to the system is not functioning." error reported by System.  The vfpext service is currently running.

**Comment by OneBlue** [comment]
I wouldn't be surprised if that was the root cause of the error you're seeing indeed. Sadly I don't have deep knowledge of that component so I don't have insights on how to diagnose it

**Comment by keith-horton** [comment]
@TDavidHudson , thanks for the debugging on your side! 80070008 == not enough resources. Just to double-check, can you verify that you don't have something listening on UDP port 53? NAT will use an internal DNS server to proxy DNS requests, and it will require binding to UDP 0.0.0.0:53 and ::0:53 (UDP port 53 on the ephemeral IPv4 and IPv6 addresses).

**Comment by TDavidHudson** [comment]
Port 53 appears not to be in use:

> netstat -na|select-string :53

  TCP    10.55.238.144:53661    10.73.86.194:443       ESTABLISHED
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    127.0.0.1:53866        *:*

**Comment by TDavidHudson** [comment]
FWIW, I'm able to listen on UDP port 53 using PowerShell, so there shouldn't be a problem with permissions.

**Comment by zadeluca** [comment]
@TDavidHudson I was having the same issue and finally managed to get past it... are using Cisco AnyConnect VPN?

**Comment by TDavidHudson** [comment]
@zadeluca Cisco AnyConnect is certainly installed, but no VPN is active when I'm in-office.  I don't recall trying to run ubuntu.exe outside the office.  What was your workaround?

**Comment by zadeluca** [comment]
@TDavidHudson I tried installing using WSL1 (wsl --set-default-version 1) and then converting to WSL2 (wsl --set-version Ubunti-22.04 2). This also failed, but showed me a more specific error message similar to what shows in your logs (failed to create network or something). That was my clue that AnyConnect may be the culprit, it seems to mess with a lot of different things.

I stopped the AnyConnect services - nam and namlm. There is another service called vpnagent, but even as admin I was not able to stop that one. Anyway, with those 2 services stopped, the conversion to WSL2 worked for me. Hope this helps.

**Comment by TDavidHudson** [comment]
@zadeluca Thanks!  Stopping the "Cisco AnyConnect Network Access Manager" and "Cisco AnyConnect Network Access Manager Logon Module" services allowed running C:\Users\...\AppData\Local\Microsoft\WindowsApps\ubuntu.exe in my elevated PowerShell.  No VPN was in use....  I'll see what Cisco has to say about this.

**Comment by zadeluca** [comment]
@TDavidHudson Glad I could help! You might also need this to make networking inside WSL function, but I'm not sure if it is only when the VPN is activated or not: https://github.com/sakai135/wsl-vpnkit

**Comment by TDavidHudson** [comment]
It is important to note for the workaround that those two Cisco services probably need to be restarted before shutting down, if not sooner (but see below).  Starting the laptop without having done so made it impossible for me to use the in-office network to access this web page or anything else external; I had to do a network repair inside Cisco AnyConnect after starting those services, then reboot, to fully recover the ability to use the network.  After restarting the services but before doing the repair, I lost even more network connectivity.

**Comment by TDavidHudson** [comment]
I'm leaving this issue open for a while in order to give Cisco time to react.
