### ISSUE TITLE
WSL right click menu "Open Linux Terminal Here" won't open anything

### ISSUE THREAD

**Issue by Riessarius** [microsoft/WSL#9514]
### Version

10.0.22623.891

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.4.0

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Open any folder, or stay on the desktop.
2. Press "Shift + Right Click".
3. In the menu, click "Open Linux Shell here".

### Expected Behavior

A terminal console should be opened with the current location.

### Actual Behavior

No console opened.

**Comment by 0xbadfca11** [comment]
One of the causes is that there is no default distribution. this command always use default distribution.

**Comment by Riessarius** [comment]
> One of the causes is that there is no default distribution. this command always use default distribution.

@0xbadfca11 I have checked my system. It has a default distribution which is exactly Ubuntu 20.04.

**Comment by Riessarius** [comment]
[WslLogs-2023-02-18_16-02-55.zip](https://github.com/microsoft/WSL/files/10773657/WslLogs-2023-02-18_16-02-55.zip)
