### ISSUE TITLE
`wsl --debug-shell` not working

### ISSUE THREAD

**Issue by zcobol** [microsoft/WSL#9518]
### Version

Microsoft Windows [Version 10.0.22623.1180]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu 22.04.1

### Repro Steps

Run `wsl --debug-shell`

### Expected Behavior

Open a WSL2 debug shell for diagnostics purposes.

### Actual Behavior

```
PS C:\Users\zcobol> wsl --debug-shell
The system cannot find the file specified.
Error code: Wsl/DebugShell/ERROR_FILE_NOT_FOUND
```

**Comment by OneBlue** [comment]
wsl --debug-shell only works if the VM is running. If not WSL instance is running, you'll get this error.

It's by design not connected to wslservice.exe, so it can start even if the service is in a bad state.
