### ISSUE TITLE
Setting interop.appendWindowsPath=false has no effect

### ISSUE THREAD

**Issue by willeccles** [microsoft/WSL#9520]
### Version

Window 10 [Version 10.0.19044.2364]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Void; Ubuntu 18.04

### Repro Steps

1. Open `.wslconfig` and add:

```ini
[interop]
appendWindowsPath=false
```

2. Ensure file does not have BOM and uses CRLF
3. `wsl --shutdown`
4. Wait a few seconds
5. Open a WSL distro and `echo $PATH`

### Expected Behavior

WSL PATH should not contain entries from the Windows PATH.

### Actual Behavior

WSL PATH includes all entries from the Windows PATH. Note that the other options appear to be applied--my 8GB RAM limit appears to be working.

### Diagnostic Logs

[WslLogs-2023-01-23_11-41-41.zip](https://github.com/microsoft/WSL/files/10481803/WslLogs-2023-01-23_11-41-41.zip)

**Comment by elsaco** [comment]
`[interop]` is a section for the `wsl.conf`, per-distro settings. If not present add `/etc/wsl.conf` to your distro(s) with `[interop]` settings. Terminate your distro to take effect.

**Comment by willeccles** [comment]
Ah, I see now. The documentation for this does not make that very clear. Feels un-intuitive that that's the case. Thanks!
