### ISSUE TITLE
h264 Intel hardware acceleration

### ISSUE THREAD

**Issue by SelfHostedJawn** [microsoft/WSL#9523]
### Version

Microsoft Windows [Version 10.0.19045.2486]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

22.04

### Other Software

Docker Desktop 4.15.0
Intel Graphics Driver 31.0.101.2114
ffmpeg (Ubuntu) 4.4.2
OpenGL ES 3.0 Mesa 22.3.3

### Repro Steps

Running `sudo LIBVA_DRIVER_NAME=d3d12 vainfo --display drm --device /dev/dri/renderD128`: 

libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 22.3.3 - kisak-mesa PPA for D3D12 (Intel(R) UHD Graphics 630)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

Cannot use va-api acceleration in FFMPEG at all with the same parameters:
`sudo LIBVA_DRIVER_NAME=d3d12 ffmpeg -hide_banner -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i testfile.mp4 -vcodec libx264 -crf 25 -acodec copy Output.mp4` 

### Expected Behavior

Expecting to see successful transcoding of h264 file using vaapi. File can be transcoded using CPU alone, but would like to have h264 GPU acceleration with MESA drivers. 

### Actual Behavior

`sudo LIBVA_DRIVER_NAME=d3d12 ffmpeg -hide_banner -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i testfile.mp4 -vcodec libx264 -crf 25 -acodec copy Output.mp4` 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559756f1b380] st: 0 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559756f1b380] st: 0 edit list 1 Cannot find an index entry before timestamp: 0.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'testfile.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: mp41avc1
    creation_time   : 2023-01-22T19:22:33.000000Z
    encoder         : vlc 3.0.18 stream output
    encoder-eng     : vlc 3.0.18 stream output
  Duration: 00:00:27.50, start: 0.000000, bitrate: 11417 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], 11415 kb/s, 13.85 fps, 29.97 tbr, 1000k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2023-01-22T19:22:33.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
File 'Output.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied

**Comment by OneBlue** [comment]
@iourit: Can you help with this ?

**Comment by sivileri** [comment]
Could you please try the following? Enabling loglevel trace on ffmpeg should give us more info about the VAAPI state.

```
export LIBVA_DRIVER_NAME=d3d12
sudo chmod 666 /dev/dri/*

# Should be able now to run vainfo without sudo
vainfo --display drm --device /dev/dri/renderD128

# Drop sudo from the ffmpeg call and try decoding only, discarding the output to rule out encoding issues.
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i ~/testfile.mp4 -f null - -loglevel trace

# Drop sudo from the ffmpeg call and enable ffmpeg trace logging
ffmpeg -hide_banner -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i testfile.mp4 -vcodec libx264 -crf 25 -acodec copy Output.mp4 -loglevel trace

```

I see this is a 4K resolution video file, did you try with a lower resolution one or a different mp4 file (I see some warnings about the mp4 file in the logs)?

**Comment by SelfHostedJawn** [comment]
This is the output from running vainfo as above:
```
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 22.3.3 - kisak-mesa PPA for D3D12 (Intel(R) UHD Graphics 630)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD


      VAProfileH264High               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc 
```

Trying to do decoding only with a 1080p mp4 file, I get the following:
`ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i ~/testfile2.mp4 -f null - -loglevel trace`
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied

[ffmpeg_decode_log.txt](https://github.com/microsoft/WSL/files/10501157/ffmpeg_decode_log.txt)

Running the second command with the same testfile yields the same permission denied message at the end:
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied

I can include that log too if needed.

Thank you!

**Comment by sivileri** [comment]
I see in that log that it successfully initialized the device and decoded a frame 
```

[AVHWDeviceContext @ 0x564d7f89c080] Initialised VAAPI connection: version 1.14
[AVHWDeviceContext @ 0x564d7f89c080] Format 0x3231564e -> nv12.
[AVHWDeviceContext @ 0x564d7f89c080] Format 0x30313050 -> p010le.
[AVHWDeviceContext @ 0x564d7f89c080] VAAPI driver: Mesa Gallium driver 22.3.3 - kisak-mesa PPA for D3D12 (Intel(R) UHD Graphics 630).
...
[h264 @ 0x564d7fce3580] Decode to surface 0x1b.
```

Could you please include also the log of the second command with the libx264 encoding part? Does that command produce the output.mp4 file?

`KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied` seems to be a benign warning which I also see with successful transcoding with VAAPI. Could you also check in the GPU performance tab in Task Manager that the GPU is being used when running the ffmpeg commands in WSL? You'd need an input file with at least a bunch of frames for the GPU usage spike in the graph to be noticeable.

**Comment by SelfHostedJawn** [comment]
I ran the encoding command watched the task manager, but there's no noticeable spike in the GPU usage. Video decode and processing stays at 0. The output file fails to be created. FFMPEG never seems to stop or end, it hands at the 'cur_dts....' until I exit it with ctrl+c. 

The 1080p test file is 25 seconds long at 30FPS, is that enough or should I find a larger file?

Here's the log as well. 
[ffmpeg_encode_log.txt](https://github.com/microsoft/WSL/files/10501520/ffmpeg_encode_log.txt)

**Comment by sivileri** [comment]
Does this command finish or also hangs until ctrl + c?
`ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i ~/testfile2.mp4 -f null - -loglevel trace
`

Could you please upload the video input files? 25 seconds / 30fps should be enough for the GPU to show usage. 

Just to be sure we have a comparable environment to test, could you please:
1. run `wsl --update` from an elevated powershell terminal. Then could you please run `wsl --version` and paste the output?
2. Download and install the [Intel driver 31.0.101.4032](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)
3. Run `sudo apt-get update && sudo apt-get upgrade `from WSL to make sure the latest mesa/ffmpeg are installed.

I see you listed Docker Desktop in other software, are you running this on a bare metal/native Ubuntu WSL2 console or inside a container ? [This docker documentation](https://docs.docker.com/desktop/windows/wsl/) shows some restrictions for GPU support.

**Comment by SelfHostedJawn** [comment]
Output of wsl --update:
```
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

Output of wsl --version:
```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486
```

I have an 8th gen i5-8400 with UHD630, I don't think that version of the intel driver is supported by iGPU.

I couldn't upload the original video because it had an IMEI of a cell phone in it. I retried the command using the blender bunny video from here:
https://video.blender.org/w/bf1f3fb5-b119-4f9f-9930-8e20e892b898

**Comment by sivileri** [comment]
Thanks for the quick reply.

After some more investigation, unfortunately found out that Intel 8th Gen (UHD630) does not support WSL video acceleration. Video decode support is incorrectly being advertised when [the vendor's driver is queried for feature support](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/d3d12/d3d12_video_screen.cpp#L99), which in turns gets reported to `vainfo` and other apps. The vendor was notified about this problem and future driver releases should correct this misreporting issue.

**Comment by SelfHostedJawn** [comment]
Ah ok, so it's not possible to be done, and future drivers won't enable that either right? It's just misreporting that it can for now. 

Thank you so much for your help!
