### ISSUE TITLE
MSSQL docker container fails on start on WSL 1.10

### ISSUE THREAD

**Issue by wicksipedia** [microsoft/WSL#9527]
### Version

Microsoft Windows [Version 10.0.22623.1180]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Other Software

WSL 1.1.0
Docker Desktop (Windows) - 4.16.2 (95914)
MSSQL 2022-latest

### Repro Steps

See https://github.com/microsoft/mssql-docker/issues/804

simple docker command to repro
```
docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>' -e 'CONFIG_EDGE_BUILD=0' `
    -p 1433:1433 `
    --name sql1 `
    -h sql1 `
    -d mcr.microsoft.com/mssql/server:2022-latest
```

### Expected Behavior

Container starts and database is accessible like on WSL 1.0.3 (i.e. if I rollback the WSL version, docker works as expected)

### Actual Behavior

2023-01-23 10:56:00 SQL Server 2022 will run as non-root by default.
2023-01-23 10:56:00 This container is running as user mssql.
2023-01-23 10:56:00 To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2023-01-23 10:58:43 ERROR: CoInitializeSecurity failure. (HRESULT 0x800706b5)

[WslLogs-2023-01-24_14-09-32.zip](https://github.com/microsoft/WSL/files/10486065/WslLogs-2023-01-24_14-09-32.zip)

**Comment by Biswa96** [comment]
Can you reproduce the issue without Docker Desktop and with running dockerd in the Linux distribution in WSL2?

**Comment by elsaco** [comment]
It is the same port proxy issue tracked by https://github.com/microsoft/WSL/issues/9508. On a debug console you'll see messages like:

```
GnsPortTracker: Requested the host for port allocation on port (family 2, port 1433, protocol 6) - returned 0
GnsPortTracker: Tracking bind call: family (2) port (1433) protocol (6)
GnsPortTracker: Requested the host for port allocation on port (family 10, port 1433, protocol 6) - returned 0
GnsPortTracker: Tracking bind call: family (10) port (1433) protocol (6)
GnsPortTracker: No longer tracking bind call: family (2) port (1433) protocol (6)
GnsPortTracker: No longer tracking bind call: family (10) port (1433) protocol (6)
```

**Comment by pmartincic** [comment]
Thanks @elsaco. For those wondering, this issue is actively being worked on.

/dupe #9508
