### ISSUE TITLE
Release .msix files instead of .msixbundle

### ISSUE THREAD

**Issue by rgl** [microsoft/WSL#9531]
**Is your feature request related to a problem? Please describe.**

Currently, a WSL release is a `.msixbundle`file (e.g. https://github.com/microsoft/WSL/releases/download/1.0.3/Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle) that contains the `amd64` and `arm64` architecture `.msix` files.

This is somewhat wasteful, as one only installs a specific architecture, so to cut the download size in half, it would be nice to release a `.msix` file for each architecture.

**Describe the solution you'd like**

Cut the releases in two `.msix` files (one for the `amd64` architecture, and another for the `arm64` architecture) instead of a single `.msixbundle`.

**Comment by Biswa96** [comment]
I would vote for .msixbundle. Because that file type mitigates any confusion for first time user about which file to download and install from.

**Comment by rgl** [comment]
The target user of WSL does not known about different architectures? A typical Linux user is pretty much aware of that, because the dists make it explicit.

**Comment by benhillis** [comment]
No plans to change this behavior.
