### ISSUE TITLE
VmmemWSL - using high CPU on start and unable to terminate, wsl --shutdown hangs

### ISSUE THREAD

**Issue by dazinator** [microsoft/WSL#9534]
### Version

Microsoft Windows [Version 10.0.22000.1455]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Other Software

Docker Desktop (Windows) version 4.15.0 (93002)

### Repro Steps

I'm don't recall changing anything around docker desktop or wsl, however as of yesterday, docker desktop is failing to launch  on windows startup - docker desktop just shows its waiting for docker to start and stays that way.

Meanwhile looking at task manager - wsl is going haywire, using very high CPU

![image](https://user-images.githubusercontent.com/3176632/214592087-0be86d62-bdcb-4ea2-b4bd-074460e1048d.png)

If I reboot, everything enters this same state - i.e docker desktop fails to load (just showing an empty containers screen and its message about waiting for docker to start up) and the above wsl related process starts consuming high CPU.

I am unable to kill this process from an admin command - it says "access denied" - same trying to do it within task manager.

![image](https://user-images.githubusercontent.com/3176632/214592697-3a47fc46-1de4-4bb5-b4c5-b948c30f52f0.png)

I am also not able to issue any `wsl` cli commands - the commands just hang, including `wsl -l -v` and `wsl --shutdown` which means I am not sure how to terminate WSL and prevent it from stealing my CPU.

![image](https://user-images.githubusercontent.com/3176632/214592943-238d4679-b0cd-4de2-a619-9b3b227caa70.png)

So given:

1. This process is kicked off at startup
2. I am unable to kill it
3. I am unable to shutdown wsl

I am now looking at trying to prevent wsl from starting up in the first place so I can get my CPU back!

- I will try uninstalling docker desktop and re-installing the latest version (think there has been an update released very recently)

Failing that I will to uninstall docker desktop and then look for how to uninstall wsl.

Any advice for recovering from this scenario would be useful.

### Expected Behavior

This process shouldn't be running away with my CPU.
I'd expect docker desktop to start up - I assume the two issues are related, I may be wrong.
I'd expect to be able to kill WSL in this scenario, but taskkill and other attempts are failing despite me being the owner and admin of my machine.

### Actual Behavior

As shown above.

**Comment by dazinator** [comment]
Uninstalling completely and installing fresh as per instructions above, led to a new issue. No longer any VmmemWSL run away process issue, however docker desktop remains waiting for docker to start forever on startup. Solution here worked https://stackoverflow.com/questions/71238673/docker-desktop-starting-forever-on-windows which was to close docker desktop, then run `wsl --update` then open docker desktop again.

Obviously the route I took to resolution (complete uninstall and re-install) means that I have lost all of my images locally. This may not be desirable for some.

**Comment by OneBlue** [comment]
Thanks for reporting this @dazinator. If this happens again, can you please:

- update to wsl >= 1.1.0
- Reproduce the issue
- Open a debug shell via wsl.exe --debug-shell
- Share the output of `ps aux` inside that shell

**Comment by aand18** [comment]
@dazinator i have this issue but can't follow your instruction `update to wsl >= 1.1.0`. Any advice on updating?

```cmd
wsl -v
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486

wsl --update
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

**Comment by evelynhathaway** [comment]
I am running wsl v1.1.3.0 also with a similar issue (randomly hangs after a while like @aand18) and running `wsl --debug-shell` hangs just as `wsl --shutdown`.

I can't even prevent vmmem from taking all of the available CPU using `Restart-Service LxssManager`. 

Clicking terminate on Windows Subsystem for Linux under the advanced options in the Windows Settings app results in the Settings app freezing for a moment. After the Settings app is usable again, all of the above is still true.

I have a high powered fairly new laptop (11th gen Intel i7, Quadro GPU, 32 GB of RAM) so it's odd that WSL suddenly just hangs my whole machine randomly. I can't identify any new software inside the WSL distribution that coincided with this behavior.

![Task manager with 80+% CPU usage](https://user-images.githubusercontent.com/38994283/222288899-b8cd5a95-822d-4a12-ae71-043348eed16d.png)

Closing programs does not seem to help, but restarting my entire computer does.

<details>
<summary><code>wsl --version</code> result</summary>

WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2604

</details>

**Comment by 2hansen** [comment]
Upgraded once more:
PS C:\Users\bhh> wsl --version
WSL version: 1.1.6.0
Kernel version: 5.15.90.1
WSLg version: 1.0.50
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22624.1470

Still WSL becomes unresponsive with high vmmemwsl cpu. Strange if theres was a suggested fix back in November that this haven't reached the beta-channel yet. Maybe one on canary or dev can test if the issue is present there?

**Comment by zmajeed** [comment]
Looks same as issue #6982  - this should not be closed

**Comment by marshallsetian** [comment]
ya saya jg mengalami mslh ini....
adakah yg bisa membantu persoalan ini???
tidak efektif ketika nganggur memori termakan banyak,,,

**Comment by geertjanb** [comment]
same issue here

**Comment by Bartamous** [comment]
anoyinn as shit

**Comment by SkyYap** [comment]
uninstall my docker and close up all my Hyper-V via `windows + R` > `services.msc`

Delete my Ubuntu and WSL2 too through control panel.

Installed only docker and select use another one instead of Hyper-V.

Set my VmmemWSL to efficiency mode and manage to restrict them to use only 1GB.

**Comment by gpuma** [comment]
Issue still persists. Even without docker.

**Comment by bodydisplaynone** [comment]
+1, I just ran into this. vmmemwsl constantly running the fans at 30-50%cpu and any wsl command just hangs, the virtual remote host is unreachable via docker or vscode.

I completely uninstalled the distro, disabled wsl and hyper v from programs and features, re-enabled and re-installed everything and the problem is still there. I went further and tried a different distro (Debian + Ubuntu) but when trying to launch Ubuntu the same happens: nothing.

The terminal just hangs and wsl never responds.

**Comment by BaconGabe** [comment]
Im having this issue WSL version: 2.4.13.0 has NOT been fixed

**Comment by ChrisonSimtian** [comment]
its 2026 and I'm having this issue, so still not fixed
```bash
WSL version: 2.6.3.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.7623
```

**Comment by hbsmini-lab** [comment]
PowerShell or terminal               wsl --shutdown
