### ISSUE TITLE
wslservice.exe has product name "Windows (R) Win 7 DDK Driver"

### ISSUE THREAD

**Issue by ce-dot** [microsoft/WSL#9536]
Greetings,

I was cleaning up my Win 10 installation and looking at the Sysinternals Autoruns tool to check for unwanted autostart applications.

There I noticed this entry in the Services tab, where the third column is titled "Publisher":
![image](https://user-images.githubusercontent.com/8227344/214658537-3fd78866-f845-4103-bf4c-138c639d4800.png)

It's the Windows Store version of WSL.

Looking at the Details pane of the file's properties shows this:
![image](https://user-images.githubusercontent.com/8227344/214658698-d4a5349d-9a1e-493c-a294-edf5431f2882.png)

I'm not entirely sure about the meaning of this, but it mentioning Windows 7 is probably in error?

**Comment by benhillis** [comment]
This is fixed in 1.1.0 and later.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/1.1.2.

**Comment by rewqazxv** [comment]
And the wsl service name is 'ms-resource:AppName', which is very strange.

![](https://user-images.githubusercontent.com/41326691/220698156-ebc5f7f4-109b-4dd4-9f68-c5fbf8a11acb.png)

![](https://user-images.githubusercontent.com/41326691/220697938-1c08448e-e954-4fa3-80aa-2e5d855a88c7.png)

**Comment by ForbiddenEra** [comment]
![image](https://github.com/microsoft/WSL/assets/7980490/2d3d5063-bd94-4c06-ac74-c245c0e94713)

hmm??
