### ISSUE TITLE
Error code: Wsl/InstallDistro/E_UNEXPECTED

### ISSUE THREAD

**Issue by jianastrero** [microsoft/WSL#9545]
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Version: 2

### Other Software

Dual boot enabled with secure boot enabled

### Repro Steps

>> wsl --install Ubuntu
Catastrophic failure
Error code: Wsl/InstallDistro/E_UNEXPECTED

### Expected Behavior

Install Ubuntu as it always have

### Actual Behavior

Catastrophic Failure

### Diagnostic Logs

[WslLogs-2023-01-27_07-00-46.zip](https://github.com/microsoft/WSL/files/10516312/WslLogs-2023-01-27_07-00-46.zip)

**Comment by benhillis** [comment]
Interesting, looks like we're not finding a package with the matching package id. Adding @OneBlue who wrote this logic.

**Comment by OneBlue** [comment]
Looking at the logs it looks like the store returned 0 packages for the ubuntu distro.

@jianastrero: Is the windows store available on your machine ? 

Also, does `wsl --install Ubuntu --web-download` work ?

**Comment by LegendaryTunzeverywhere** [comment]
I have the same issue, this is what i got

WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

**Comment by HanDaSeul** [comment]
I got a same problem but just changing the other network(wifi, LAN whatever) worked. Sometimes I had my PC connected to my phone Wifi hotspot and that caused problem.

**Comment by mwass** [comment]
I had the same issue, and `wsl.exe --update` fixed it.

**Comment by mhsattarian** [comment]
The same issue occurred to me, fixed it with running `wsl --shutdown` in PS and starting WSL again.

**Comment by bosswnx** [comment]
I met the same problem in China, and fixed it through setting up VPN such as Clash. I think it is probably network error.

**Comment by sofiateacoffee** [comment]
I'm facing the same issue, which I believe is due to the privacy policy on my desktop computer at the hospital. I'm unable to access the Microsoft Store and Chrome. I also tried to install Ubuntu through an APPX package, but it's blocked as well.
