### ISSUE TITLE
WSL error: Wsl/Service/CreateInstance/CreateVm/ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by dcmwong** [microsoft/WSL#9547]
### Version

Windows 10 Enterprise 21H2  19044.2486

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Ubuntu-20.04

### Distro Version

Ubuntu-20.04

### Repro Steps

- Have two accounts on the system one user and one Administrator
- run `wsl --install Ubuntu-20.04` in each account (whilst logged into that account)
- run `wsl` to see that WSL does run correctly for both
- Log into the non-Admin account
- run a command prompt as Administrator
- run `wsl` 
- I get this error message
```
The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/CreateVm/ERROR_FILE_NOT_FOUND
```

### Expected Behavior

I expect it to run WSL without any errors when the command prompt is ran as Administrator.

### Actual Behavior

- I get this error message
```
The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/CreateVm/ERROR_FILE_NOT_FOUND
```

**Comment by tehautanop** [comment]
I am experiencing this too. 

> Wsl/Service/CreateInstance/ERROR_FILE_NOT_FOUND

or 

> The system cannot find the file specified.
> Error code: Wsl/Service/CreateVm/ERROR_FILE_NOT_FOUND

FWIW I am behind corporate proxy so wsl --update is not an option for fix
