### ISSUE TITLE
Background and redirected windows commands allocate windows console when executed from wslg

### ISSUE THREAD

**Issue by albatrossen** [microsoft/WSL#9551]
### Windows build number:

10.0.19044.0 

### Your Distribution version:

22.04.1 LTS

### Your WSL versions:

WSL-version: 1.0.3.0
Kerneversion: 5.15.79.1
WSLg-version: 1.0.47
MSRDC-version: 1.2.3575
Direct3D-version: 1.606.4
DXCore-version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows: 10.0.19044.2486

### Steps to reproduce:

1. Start xterm using the shortcut in windows start menu
2. cd /mnt/c #just to get rid of a cmd.exe warning, not actually required
3. cmd.exe /c "ping -n 10 127.0.0.1" > /dev/null

### Expected behavior:

I would expect the same as when executed from a wsl shell in powershell. That is no windows console is opened.

### Actual behavior:

A windows console window pops up until the command is done executing:
![screenshot](https://user-images.githubusercontent.com/380609/214537838-cd0ffb61-fd05-4989-b400-675cfd6558e5.png)

**Comment by OneBlue** [comment]
Transferring to WSL since that issue comes from WSL interop

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/1.1.2.
