### ISSUE TITLE
Port 80/443 get closed randomly 

### ISSUE THREAD

**Issue by m7mdsa3ed** [microsoft/WSL#9554]
### Version

10.0.22621.1194

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu 22.04.01

### Repro Steps

Updating to 1.1.0

### Expected Behavior

localhost should be available unless I closed the terminal or by running wsl --shutdown

### Actual Behavior

Can't access localhost after 1 min after opening WSL terminal, and WSL still running. 

No issue nor logs from nginx.

**Comment by jonpetersathan** [comment]
Might be related to this: #9508?
