### ISSUE TITLE
Very bad performance in WSL (IO Operations)

### ISSUE THREAD

**Issue by jonpetersathan** [microsoft/WSL#9555]
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

docker-desktop-data

### Other Software

Visual Studio Code 1.74.2
Dev Container Extension v0.266.1
Docker Desktop 4.9.0

### Repro Steps

I noticed this while working on a REST-API in Rust using axum (a library to create REST APIs). Even small code changes take forever when recompiling the project. The rust compiler is using incremental compilation (which you can verify by using -v on the `cargo build` command). I assume the issue is very low IO performance.

Prerequisites: Docker Desktop and Visual Studio Code (incl. Dev Container Extension) installed.
 
1. Open Visual Studio Code in an empty folder
2. Open the VS Code command prompt and select "Dev Containers: Create Dev Container Configuration Files..."
3. Wait until the container has started and run "cargo init" from the terminal
4. Run the following commands to configure the dependencies:
```
cargo add axum
cargo add tokio -F macros -F rt-multi-thread
```
5. Add the following content to main.rs
```rust
use axum::{
    routing::get,
    Router,
};

#[tokio::main]
async fn main() {
    // build our application with a single route
    let app = Router::new().route("/hello", get(hello_world));

    // run it with hyper on localhost:3000
    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn hello_world() -> String {
    "Hello world!".to_owned()
}
```
6. Now run `cargo build` to initially compile the project.
**Note:** For some strange reason you might need to run the command multiple times, until it recognizes every library as fully compiled. When the command just outputs `Finished...` it is done. This is a different bug, but I am pretty sure this is unrelated and probably not for this place here.

Now change a single line in the code, for example "Hello world!" to "Hello!".

### Expected Behavior

This usually should take around one second, even on slow hardware. You test this by installing Rust directly in Windows and repeat the same steps, just without opening this in a Dev Container.

### Actual Behavior

It takes more then 10 seconds (on my hardware) to complete. I know this doesn't seem like much, but this is only a "hello world" project to show the problem. Even though there is some translation / virtualization happening the performance different shouldn't be as high as it is.

I am missing some fundamental knowledge about WSL and its implementation to get to the bottom of this, but it seems to be related to directories shared with the host. For example when repeating the same steps, but instead of selecting "Dev Containers: Create Dev Container Configuration Files..." in the 2. step, select "Dev Containers: Create Dev Container". This will create the container using a volume located on the native WSL filesystem, instead of using a mount path to the windows filesystem. I assume there is some kind of translation layer when accessing the windows filesystem from WSL that is the reason for this. But this shouldn't be that extreme, right?

Just for reference my hardware specs:
CPU: Ryzen 5800X (1800 MHz FCLK)
RAM: 16GB DDR4 3600 MHz
SSD: Samsung 980 Pro 512GB (NVMe)
GPU: Nvidia RTX 2060

**Comment by elsaco** [comment]
@jonpetersathan I understand you want to use a docker container but you can use a WSL distro directly. VSCode has very good integration with WSL instances. This is on a Volterra box (a.k.a Windows DevKit 2023) with low specks compared to your system:

![wsl_vscode_cargo_built_test](https://user-images.githubusercontent.com/3933920/215301557-6e05ed2b-658f-445e-aed9-dfedb9c94e67.png)

**Comment by jonpetersathan** [comment]
Is this using a folder from the Windows file system or is it in the default WSL system? Haven´t tested this using WSL directly tbh, but I don't think this is necessarily related to docker itself. Maybe it is some weird interaction between docker mounted volumes and WSL?

I will give it a shot and test this using WSL. Thanks!

**Comment by jonpetersathan** [comment]
Ok, I test this and it has nothing to do with docker. Same results when running directly in WSL (inside a windows folder):
![image](https://user-images.githubusercontent.com/32908927/215329856-6d644b31-7810-4224-880e-6c52f7618e35.png)

**Comment by elsaco** [comment]
That's due from `Duplicate cookie detected`. After you run `cargo build` check kernel messages. Here's sample output after change in `main.rs`:

<details><summary>dmesg</summary>
<p>

```
[Sun Jan 29 09:03:17 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:17 2023] FS-Cache: O-cookie c=00005a2f [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:17 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000000d7c3bb4
[Sun Jan 29 09:03:17 2023] FS-Cache: O-key=[8] '9c70030000000600'
[Sun Jan 29 09:03:17 2023] FS-Cache: N-cookie c=00005a30 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:17 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=000000009b568d92
[Sun Jan 29 09:03:17 2023] FS-Cache: N-key=[8] '9c70030000000600'
[Sun Jan 29 09:03:17 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:17 2023] FS-Cache: O-cookie c=00005a32 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:17 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000004b761960
[Sun Jan 29 09:03:17 2023] FS-Cache: O-key=[8] '9b70030000000600'
[Sun Jan 29 09:03:17 2023] FS-Cache: N-cookie c=00005a33 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:17 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=000000009dafe4d7
[Sun Jan 29 09:03:17 2023] FS-Cache: N-key=[8] '9b70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a37 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000000fe2e260
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'ae70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a38 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=0000000026d7ed71
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'ae70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a3a [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000c08716e7
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'b270030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a3b [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000913cb2b3
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'b270030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a3d [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000006076aa21
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'af70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a3e [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=000000003fc5a655
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'af70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a40 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000042cece6
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'cc70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a41 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=000000006f67e419
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'cc70030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a49 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000e26ac260
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'e070030000000700'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a4a [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=0000000036770174
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'e070030000000700'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a4c [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000fc309352
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'fc70030000000700'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a4d [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000bfaac64c
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'fc70030000000700'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a4f [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000a44e5b28
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'fe70030000000800'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a50 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=000000002d7cb747
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'fe70030000000800'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a56 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000ddceeff1
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '3571030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a57 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=0000000015126a55
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '3571030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a61 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000502fdc91
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '5d71030000000500'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a62 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000208882ea
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '5d71030000000500'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a66 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000002c067dc1
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '7671030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a67 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=0000000071afc741
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '7671030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a69 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000deb81235
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '6e71030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a6a [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000f7fc3776
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '6e71030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a6c [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=00000000235da39a
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'a171030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a6d [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000a44e5b28
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'a171030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a6f [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=0000000042d4c59a
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] 'a071030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a70 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000fc309352
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] 'a071030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005a84 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=0000000049646901
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '0572030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005a85 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000f620e6aa
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '0572030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005ab0 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000009e787672
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '0773030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005ab1 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=00000000fc309352
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '0773030000000600'
[Sun Jan 29 09:03:18 2023] FS-Cache: Duplicate cookie detected
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie c=00005ab3 [p=0000000b fl=226 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: O-cookie d=000000002605e7f9{9p.inode} n=000000001c6052f2
[Sun Jan 29 09:03:18 2023] FS-Cache: O-key=[8] '1173030000000800'
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie c=00005ab4 [p=0000000b fl=2 nc=0 na=1]
[Sun Jan 29 09:03:18 2023] FS-Cache: N-cookie d=000000002605e7f9{9p.inode} n=0000000076b3abb0
[Sun Jan 29 09:03:18 2023] FS-Cache: N-key=[8] '1173030000000800'
```
</p>
</details>

**Comment by jonpetersathan** [comment]
Ah I see, but is this supposed to happen? Is it related to #5694? If yes, I
assume I have to wait for Kernel 5.17? :(

**Comment by invy** [comment]
I've encountered a huge performance issue while running CMake in WSL. (Also 10x differenc)
My solution was to disable WSL Interop:
```
$ cat /etc/wsl.conf
[interop]
enabled = false
appendWindowsPath = false
```

**Comment by jonpetersathan** [comment]
> I've encountered a huge performance issue while running CMake in WSL. (Also 10x differenc) My solution was to disable WSL Interop:

Hm, this doesn't change anything for me. But I have seen the last setting before, it should disable filesystem access to windows all together, right? So you can't access anything in /mnt/c/... (for some reason, I still can with this setting, but there is also no improvement in performance)

**Comment by craigloewen-msft** [comment]
Are you able to put your project inside of the Linux path instead of in the Windows drive?
See here for more details:
https://learn.microsoft.com/en-us/windows/wsl/setup/environment#file-storage

**Comment by elsaco** [comment]
From above link:

`For the fastest performance speed, store your files in the WSL file system if you are working on them with Linux tools in a Linux command line (Ubuntu, OpenSUSE, etc). If you're working in a Windows command line (PowerShell, Command Prompt) with Windows tools, store your files in the Windows file system. Files can be accessed across the operating systems, but it may significantly slow down performance.`

And indeed mixing OS tools and filesystems does have a penalty. Using cargo.exe on a WSL filesystem the build speed is slightly shorter, around 9 sec:

```
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\openSUSE-Tumbleweed\home\elsaco\test2> cargo build
   Compiling test2 v0.1.0 (\\wsl.localhost\openSUSE-Tumbleweed\home\elsaco\test2)
    Finished dev [unoptimized + debuginfo] target(s) in 8.24s
```

However `CARGO_INCREMENTAL=0` must be added to the environment otherwise it fails with:

`error: incremental compilation: could not create session directory lock file: Incorrect function. (os error 1)`

---

Microsoft's has good advice to heed `We recommend against working across operating systems with your files, unless you have a specific reason for doing so.`

**Comment by jonpetersathan** [comment]
@craigloewen-msft Okay, so yes, moving the files to the native WSL does work as intended (compile times around 1 second), but it doesn't really solve the issue.

And yes, sure, I fully expect some performance loss, but there is now way the performance is over 10x when using the windows filesystem instead of the wsl native file system. And it also doesn't explain the errors on the syslog, or this a normal message for WSL?

The main issue for me with all of this, is that it basically makes Dev Container unusable, as the whole purpose of Dev Container is having all necessary binaries and libraries separated from the development files.

So my main question here, is basically: Is this a bug or is everything working as it is supposed to?
Because having a 10x performance hit and a bunch of errors in the syslog, for sure seems like a bug to me. :D

**Comment by invy** [comment]
> > I've encountered a huge performance issue while running CMake in WSL. (Also 10x differenc) My solution was to disable WSL Interop:
> 
> Hm, this doesn't change anything for me. But I have seen the last setting before, it should disable filesystem access to windows all together, right? So you can't access anything in /mnt/c/... (for some reason, I still can with this setting, but there is also no improvement in performance)

No. This disables the ability to execute Windows Programs (like notepad.exe) from inside WSL. Filesystem access (/mnt/c/...) is controlled in [automount] section and is being handled by the 'drvfs'. Indeed accessing your windows drives from WSL2 is not recomended and very slow.
You can't do.
```
$ notepad.exe
```
For me this solved that strange performance impact (from 2 minutes project configuration down to 5 seconds).

**Comment by jonpetersathan** [comment]
> No. This disables the ability to execute Windows Programs (like notepad.exe) from inside WSL. Filesystem access (/mnt/c/...) is controlled in [automount] section and is being handled by the 'drvfs'. Indeed accessing your windows drives from WSL2 is not recomended and very slow.
> 
> Without interop you can't do something like this:
> 
> ```
> $ notepad.exe
> ```
> 
> For me this solved that strange performance impact (from 2 minutes project configuration down to 5 seconds).

Ah ok, got it, I will do some more testing, but no luck so far changing these settings...

**Comment by stanliwise** [comment]
> From above link:
> 
> `For the fastest performance speed, store your files in the WSL file system if you are working on them with Linux tools in a Linux command line (Ubuntu, OpenSUSE, etc). If you're working in a Windows command line (PowerShell, Command Prompt) with Windows tools, store your files in the Windows file system. Files can be accessed across the operating systems, but it may significantly slow down performance.`
> 
> And indeed mixing OS tools and filesystems does have a penalty. Using cargo.exe on a WSL filesystem the build speed is slightly shorter, around 9 sec:
> 
> ```
> PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\openSUSE-Tumbleweed\home\elsaco\test2> cargo build
>    Compiling test2 v0.1.0 (\\wsl.localhost\openSUSE-Tumbleweed\home\elsaco\test2)
>     Finished dev [unoptimized + debuginfo] target(s) in 8.24s
> ```
> 
> However `CARGO_INCREMENTAL=0` must be added to the environment otherwise it fails with:
> 
> `error: incremental compilation: could not create session directory lock file: Incorrect function. (os error 1)`
> 
> Microsoft's has good advice to heed `We recommend against working across operating systems with your files, unless you have a specific reason for doing so.`

This solved my issue, as soon as I went to using just native, my slow disk performance issue was resolved immedidately

**Comment by jonpetersathan** [comment]
Yeah for me too, I still don´t understand why the performance penalty is so extreme, but I worked around it, by using native as well (or Linux all together :).

I think I will close this for now, if anyone comes across this and feels this should be addressed, drop a comment and I can reopen this.

**Comment by OliverRC** [comment]
```
Microsoft's has good advice to heed We recommend against working across operating systems with your files, unless you have a specific reason for doing so.
```

Except that the primary usecase in my opinion is to have a files in linux and be able to operate on them using Unix commands and tools but have the IDE in Windows with the GUI. Therefore filesystem access from Windows -> Linux is important.

**Comment by chanmaoganda** [comment]
perhaps using wsl1 could make faster compilation process
https://github.com/microsoft/WSL/issues/12555
