### ISSUE TITLE
Cannot use docker in imported docker container

### ISSUE THREAD

**Issue by meicale** [microsoft/WSL#9559]
### Version

Microsoft Windows [版本 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

I install docker desktop and the Ubuntu 20.04 WSL using Windows store. I exported it(the container) and then imported using another name. I can use docker in the original container but I cannot use docker in the imported one. 

I use the imported docker container(ubuntu20.04) quite a lot actually, it is my daily driver.  

### Expected Behavior

The expected behavior is that I can use the docker like I used in original one. Without any error.

### Actual Behavior

And I get error: 
"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Comment by pmartincic** [comment]
Exported and imported a WSL distro? Or exported and imported a docker image?

/logs

**Comment by meicale** [comment]
> Exported and imported a WSL distro? Or exported and imported a docker image?
> 
> /logs

Sorry for the unclearness. I update the descriptiop. I export and import the same WSL distro. I cannot use the original user name, too. I have to use the root user but either root or my user doesn't work.

**Comment by elsaco** [comment]
@meicale your default WSL distro is being automatically integrated with docker. To add more WSL distros (i.e. your 2nd container) open `Settings --> Resources -- WSL Integration` in dashboard, select your WSL distro(s) and `Apply & restart`

![docker_wsl_integration](https://user-images.githubusercontent.com/3933920/215947168-301af3ea-a80b-4048-8864-0052c3adc5b7.png)

**Comment by meicale** [comment]
Yes, that works. Thanks a lot! @elsaco
