### ISSUE TITLE
wsl does not start any graphical app

### ISSUE THREAD

**Issue by nerus492** [microsoft/WSL#9567]
### Version

10.0.1945.2006

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

ubuntu 22.04

### Repro Steps

sudo apt install nautilus, correct installed

### Expected Behavior

After the installation I must start it with its invocation command

### Actual Behavior

(org.gnome.Nautilus:1514): Gtk-WARNING **: 00:44:19.186: cannot open display: according to the documentation you only have to install the desired application and start it, the dependencies are installed but it does not open, the drivers are up to date

**Comment by benhillis** [comment]
Running graphical applications requires WSLg, which is available in the newest version of WSL. Run `wsl.exe --update` to update.

**Comment by nerus492** [comment]
latest wsl update is applied
