### ISSUE TITLE
wsl command hangs (will not start)

### ISSUE THREAD

**Issue by ncoder** [microsoft/WSL#9568]
### Version

Microsoft Windows [Version 10.0.22000.1335]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

(unknown)

### Distro Version

(unknown)

### Repro Steps

Fresh boot
Open powershell
wsl => hang
wsl --status => hang
wsl -l => hang

### Expected Behavior

Expect wsl to startup. 
It has worked on my machine before. Unknown state change.

### Actual Behavior

no output

### Diagnostic Logs

What logs do you need?

**Comment by ncoder** [comment]
May or may not be the same issues as #9357

**Comment by mroczynskip** [comment]
I had the same issue today and it started working after updating Windows

**Comment by ncoder** [comment]
Maybe also related to #9603

**Comment by ncoder** [comment]
Working now. Didn't get a chance to collect the logs while it was broken (as described in #9603 )
if i see it again, i will try to attach logs.
