### ISSUE TITLE
WSL takes forever to start when on wrong network (network drives not accessible?)

### ISSUE THREAD

**Issue by johannestoger** [microsoft/WSL#9570]
### Version

Microsoft Windows [Version 10.0.19045.2486]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #2311-Microsoft Tue Nov 08 17:09:00 PST 2022

### Distro Version

Ubuntu 22.04

### Other Software

N/A

### Repro Steps

1. Map a number of network drives, only accessible from my work network.
2. Connect to a different network, e.g. at home, where the network drives can not be reached.
3. Start WSL

### Expected Behavior

WSL starts within a few seconds (sub 1-second is really what I expect).

### Actual Behavior

WSL takes more than 1 minute to get to a prompt.

**Comment by benhillis** [comment]
Are you adding those drives to your /etc/fstab?

**Comment by johannestoger** [comment]
No, there is only the root drive in /etc/fstab:

LABEL=cloudimg-rootfs   /        ext4   defaults        0 0

**Comment by johannestoger** [comment]
Hi, I see that there is a "needs-author-feedback" tag on this, is there anything else that I need to add? @benhillis

**Comment by johannestoger** [comment]
Anything new on this? I still have the problem.
