### ISSUE TITLE
Invoking WSL from Batch File Fails, Exit Code 1

### ISSUE THREAD

**Issue by arrmo** [microsoft/WSL#9572]
### Version

Microsoft Windows [Version 10.0.22000.1516]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

Ubuntu 22.04

### Other Software

Plex

Potentially,
Hyper-V

### Repro Steps

I have a batch file, calling a script in WSL - but have stripped it down to `wsl --version` for debugging.

When I run the script from CMD (manually), all is OK. But when called from Plex ... WSL does not seem to invoke / execute (at all, even just `wsl --version`), and seems to exit with an exit code 1.

I have confirmed (tests in batch file), and am calling the correct (64-bit) version of `wsl.exe`. I even had the script run a `where wsl` command, and did a directory list (from the script). All show `wsl.exe` there, and in the correct path ... it's just failing to execute.

### Expected Behavior

`wsl.exe` should execute, just like when the batch file is executed manually.

### Actual Behavior

As above, `wsl.exe` does not seem to run at all, exiting with an error code 1.

### Diagnostic Logs

Nothing more than noted above, but I can collect info as needed!

**Comment by benhillis** [comment]
Does Plex happen to be x86?

**Comment by arrmo** [comment]
> Does Plex happen to be x86?

It is not - thought the same thing 😆. But I do check, "which" version of WSL to run (System32, or Sysnative).



> /logs

Absolutely. But ... is there a particular thing that would help? I have some echo's of course in my batch file, but not sure what you're after. Or is `/logs` an argument to WSL (that I just don't know .. yet 😜).

Thanks!

**Comment by arrmo** [comment]
OK, so just in case this was Linux OS related (I'm running Ubuntu), I tried openSUSE-Tumbleweed also. Same issue - really seems to be core WSL related 😞 

Thanks!

**Comment by arrmo** [comment]
OK, one more piece of information ... that may help, or not 😜. I tried using,
```
1) wsl command (wsl, or full path)
2) bash -c command
3) ubuntu run command
```
All are the same, no go.

Thanks!

**Comment by arrmo** [comment]
Ahh, more searching, as I saw the same error message as [this report](https://github.com/microsoft/WSL/issues/8623). But, that also told me what you were after with /logs 😆. Sorry, was new to me. Attached, and again - thanks!

[WslLogs-2023-02-01_22-03-09.zip](https://github.com/microsoft/WSL/files/10564629/WslLogs-2023-02-01_22-03-09.zip)

**Comment by NotTheDr01ds** [comment]
@arrmo Not your fault on the `/logs` (and glad you found it separately) - Something appears to have gone wrong with the bot since it didn't auto-respond to @benhillis's command.  Normally that would have added the instructions on log collection automatically to this thread.

**Comment by NotTheDr01ds** [comment]
> But when called from Plex

Is this the Plex media server or something else?  If Plex media server, is this being run from a Python script?  Can you provide additional details that I could use to attempt to reproduce it?

**Comment by arrmo** [comment]
> Is this the Plex media server or something else? If Plex media server, is this being run from a Python script? Can you provide additional details that I could use to attempt to reproduce it?

Actually, it looks like if called from Plex Media Server (PMS), running "normally", in a Session ID > 0, then it works fine. But, if I run PMS as a service, then it fails ... as PMS is in Session ID = 0. So this seems to be the bug in WSL of not being able to call it from Session ID = 0, agreed?

Thanks!

**Comment by NotTheDr01ds** [comment]
So this seems to be the bug in WSL of not being able to call it from Session ID = 0, agreed?

That certainly sounds like a reasonable conclusion to me!  If you see any other indications that might not be the case, let me know and I can try to repro.  I have WSL running on my Plex server as well, but I haven't tried to use it for anything like that yet.  Interesting idea, though ;-).

**Comment by arrmo** [comment]
Thanks for the info! If you want to try to duplicate - have you set up / installed [PmsService](https://github.com/cjmurph/PmsService)?

Thanks again.
