### ISSUE TITLE
wsl --import-in-place doing nothing

### ISSUE THREAD

**Issue by rafaeloledo** [microsoft/WSL#9576]
### Version

Microsoft Windows [Version 10.0.22621.1194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

ArchWSL

### Repro Steps

I want to access an existing distro on ntfs external sdd which have a wsl installation from my desktop, so i plugged in my notebook. Following the command syntax:

![image](https://user-images.githubusercontent.com/51183852/216204227-e946f463-84ff-410a-ace1-d21d0cd204a0.png)

Go to the distro place: (in pwsh 7.3.2)
``cd x:\arch``

Run the command:
``wsl --import-in-place Arch ext4.vhdx``
``wsl --import-in-place Arch ext4``
``wsl --import-in-place Arch ./ext4.vhdx``
``wsl --import-in-place Arch ./ext4``
``wsl --import-in-place Arch .\ext4.vhdx``
``wsl --import-in-place Arch .\ext4``

### Expected Behavior

``Imported the specified distro.``
or other similar output

### Actual Behavior

Prints the ``wsl --help`` output on all listed commands.

**Comment by benhillis** [comment]
I can't repro this locally, can you collect /logs please?

**Comment by rafaeloledo** [comment]
> I can't repro this locally, can you collect /logs please?

Where they are located?

**Comment by rafaeloledo** [comment]
I executed the collect-wsl-logs.ps1 script on the WSL github diagnostics folder.
There is the zip with the output:
[WslLogs-2023-02-02_16-39-47.zip](https://github.com/microsoft/WSL/files/10572824/WslLogs-2023-02-02_16-39-47.zip)

But get this error after the script execution on terminal:
![image](https://user-images.githubusercontent.com/51183852/216433897-ea265cc7-13cc-436f-bef7-51bbcd035b95.png)
``Unregistered class``

**Comment by elsaco** [comment]
It works using an external drive with `exFAT` partition. Didn't test with `NTFS` partition. However, when unregistering the distro it erases the `ext4.vhdx` which I find questionable.

Sample run:

```
PS C:\Linux\import> wsl --import-in-place SanDisk F:\ext4.vhdx
The operation completed successfully.
PS C:\Linux\import> wsl -l -v
  NAME                   STATE           VERSION
* openSUSE-Tumbleweed    Running         2
  Ubuntu-22.04           Stopped         2
  Arch                   Stopped         2
  docker-desktop         Stopped         2
  Amazon2                Stopped         2
  SanDisk                Stopped         2
  docker-desktop-data    Stopped         2
PS C:\Linux\import> wsl -d SanDisk
-bash-4.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
-bash-4.2#
```

Unregister the test distro:

```
PS C:\Linux\import> wsl --unregister SanDisk
Unregistering.
The operation completed successfully.
```

It removes the `vhdx` also from the external SSD and not the registry keys only. I should have made a backup first 😥

**Comment by rafaeloledo** [comment]
> It works using an external drive with `exFAT` partition. Didn't test with `NTFS` partition. However, when unregistering the distro it erases the `ext4.vhdx` which I find questionable.
> 
> Sample run:
> 
> ```
> PS C:\Linux\import> wsl --import-in-place SanDisk F:\ext4.vhdx
> The operation completed successfully.
> PS C:\Linux\import> wsl -l -v
>   NAME                   STATE           VERSION
> * openSUSE-Tumbleweed    Running         2
>   Ubuntu-22.04           Stopped         2
>   Arch                   Stopped         2
>   docker-desktop         Stopped         2
>   Amazon2                Stopped         2
>   SanDisk                Stopped         2
>   docker-desktop-data    Stopped         2
> PS C:\Linux\import> wsl -d SanDisk
> -bash-4.2# cat /etc/os-release
> NAME="Amazon Linux"
> VERSION="2"
> ID="amzn"
> ID_LIKE="centos rhel fedora"
> VERSION_ID="2"
> PRETTY_NAME="Amazon Linux 2"
> ANSI_COLOR="0;33"
> CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
> HOME_URL="https://amazonlinux.com/"
> -bash-4.2#
> ```
> 
> Unregister the test distro:
> 
> ```
> PS C:\Linux\import> wsl --unregister SanDisk
> Unregistering.
> The operation completed successfully.
> ```
> 
> It removes the `vhdx` also from the external SSD and not the registry keys only. I should have made a backup first 😥

I'll try backuping the files and format to ``exFAT``, might be the ``NTFS``.
If you really have losted your data, my condolences 😢

**Comment by rafaeloledo** [comment]
Changing the partition to ``exFAT`` solved missejecting error that the ssd is in use, that's good for me. But i forgot running ``wsl --update``, i installed the kernel update with the .msi, i don't really know why even i installed the updates i need to run this command. After running it, the problem is solved. The notebook is recently formatted, never mind.
