### ISSUE TITLE
can't use WSL2 despite virtualizatio and Windows machine platform feature enabled, and error message says thye're not.

### ISSUE THREAD

**Issue by iti-D** [microsoft/WSL#9583]
### Version

Microsoft Windows [Version 10.0.19045.2486]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04

### Repro Steps

I didn't tweak with any settings at all when first trying out WSL. It was by default running WSL1.
When I tried to run WSL2 I had the error message: "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS."

Now, virtualization was already enabled before as I was using Virtualbox from time to time (to make sure I went to BIOS again and made sure of that).
And VIrtual Machine Platform windows feature was enabled too.

I tried unregistering, rebooting, and registering again but it didn't help. 
I noticed that in Windows Features the Hyper-V platform wasn't enabled. 
I enabled it, rebooted laptop, and tried again but it still the same error message.

what am I missing? thanks.

### Expected Behavior

expected behavior is for the system to see that virtualization and virtual machine platform are both enabled and allow me to use WSL2

### Actual Behavior

getting an error message "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS." where both things are already enabled.

**Comment by onomatopellan** [comment]
Your Windows needs to boot under the hypervisor. Open an elevated Powershell and run `bcdedit`. You should see 
`hypervisorlaunchtype    Auto`

**Comment by iti-D** [comment]
> Your Windows also needs to boot under the hypervisor. Open an elevated Powershell and run `bcdedit`. You should see `hypervisorlaunchtype Auto`

And I really do see that under `Windows Boot Loader` I see `hypervisorlaunchtype    Auto` 
should it be different?

**Comment by onomatopellan** [comment]
@iti-D That's how it should be. From the same PowerShell terminal run `systeminfo` and post the output of "Hyper-V Requirements:".

**Comment by iti-D** [comment]
> @iti-D That's how it should be. It's your CPU Intel or AMD? Also from the same PowerShell terminal run `systeminfo` and post the output of "Hyper-V Requirements:".

`Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.`
yeah it's actually working now. after I ran the command `bcdedit` before I was able to upgrade to WSL 2.

thanks!

**Comment by OneBlue** [comment]
Closing since the issue has been resolved
