### ISSUE TITLE
WSL Crashes with [process exited with code 1 (0x00000001)] Error

### ISSUE THREAD

**Issue by mr-stegosaurus** [microsoft/WSL#9585]
### Version

Windows version: 10.0.22623.1245

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.83.1

### Distro Version

Ubunut 22.04

### Other Software

Using WSL to run Yarn script within Ubuntu alongside an Ethereum node, using the Prysm and Erigon clients. 

### Repro Steps

Using Ubuntu alongside Prysm/Erigon clients, and running some Yarn scripts will cause it to run for a couple hours (up to maybe a day at a time) then crash. Currently working to isolate if one of the specific run configurations allows it to run without crashing although I haven't noticed a pattern yet. It does seem to fail more quickly when all three are running compared to just one.

### Expected Behavior

I'm expecting them to continue to run and Ubuntu to not halt executing these programs. 

### Actual Behavior

These have all been working in tandem fine for about 6 days, up until 1/20 When it started crashing and failing to recover. Reinstalled WSL and my client software with no luck. Issue presents itself after 2-24hours, with my WSL Debug Console finally outputting:

libc++abi: terminating with uncaught exception of type SyscallError: Exception thrown by Run in SecCompDispatcher.cpp:85:ioctl(10, 3226476800, (80 bytes) {00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00}) failed with errno=2 (No such file or directory)
[ 1800.388136] potentially unexpected fatal signal 6.
[ 1800.388539] CPU: 1 PID: 211 Comm: init Not tainted 5.15.83.1-microsoft-standard-WSL2 #1
[ 1800.389088] RIP: 0033:0x2eb0b5
[ 1800.389400] Code: f3 ff b8 0e 00 00 00 41 ba 08 00 00 00 31 ff 0f 05 9b c3 48 89 fe b8 0e 00 00 00 bf 02 00 00 00 41 ba 08 00 00 00 31 d2 0f 05 <9b> c3 cc 48 63 ff 48 63 f6 b8 3e 00 00 00 0f 05 9b 48 89 c7 e9 32
[ 1800.390689] RSP: 002b:00007fd32de981b8 EFLAGS: 00000246 ORIG_RAX: 000000000000000e
[ 1800.391223] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00000000002eb0b5
[ 1800.391767] RDX: 0000000000000000 RSI: 00007fd32de981c8 RDI: 0000000000000002
[ 1800.392221] RBP: 0000000000000000 R08: 000000000000000a R09: 0000000000000000
[ 1800.392795] R10: 0000000000000008 R11: 0000000000000246 R12: 00007fd32de99470
[ 1800.393316] R13: 00007fd32de9a210 R14: 00007fd32de981c8 R15: 00000000003cf668
[ 1800.393866] FS:  00007fd32de98b38 GS:  0000000000000000

[process exited with code 1 (0x00000001)]

At this point all clients are continuing to run until I try to open up another Ubunut instance in terminal. Showing the process exit and all instances of Ubuntu stopping at this point. I can't then open Ubuntu up without going through 

wsl.exe --shutdown & wsl to restart it. The cycle then repeats.

**Comment by mr-stegosaurus** [comment]
Running just my Yarn scripts (finance bots) did not cause any issues with Ubuntu crashing over the previous 3 days. Issue seems to be due to ports not being assigned correctly and then crashing Ubuntu when I run the Erigon execution client. I have a hunch the issue is similar to [#9508](https://github.com/microsoft/WSL/issues/9508), I have reverted back to latest stable version at 1.0.3 and am going to continue to troubleshoot.

**Comment by rpatterson** [comment]
Apologies if this isn't related, but it seems like it might be so I hope this helps.  I run multiple services in Docker containers inside WSL and I've been trying to debug an issue where those services start failing in multiple ways around the same time pretty regularly at ~6 hours but with some variance; as @mr-stegosaurus says, "2-24hours".

At that time I see tons of `Function not implemented` messages in log messages, both in the containter output/log messages and in log messages in WSL's `/var/log/syslog` that aren't a part of container output.  When I look at the log message timestamps to determine when an instance of this issue has started and then look in WSL's `/var/log/syslog` around that time, I always see the kernel `potentially unexpected fatal signal 6` error before all the `Function not implemented` messages start flooding.

Using `$ sed -nE "s|^.+ $(hostname -s) ([a-zA-Z-]+)\[[0-9]+\]: (.*[Ff]unction not implemented.*)|\1 \2|p" /var/log/syslog | grep -v ' message repeated ' | sort | uniq` I find mostly messages from `dockerd` concerning `$ docker exec ...` in containers, I'm assuming for `HEALTHCHECK` commands, and for restarting them, I assume by `willfarrell/autoheal` when the containers start becoming unhealthy, and I've yet to notice one of these messages that didn't concern port forwarding.  Here's one example:

```
dockerd time="..." level=error msg="Error running exec ... in container: failed to create runc console socket: listen unix /tmp/pty.../pty.sock: bind: function not implemented: unknown"
```

The remaining messages not from `dockerd` also indicate port binding:

```
networkctl Failed to connect to netlink: Function not implemented
systemd-udevd Worker: Failed to enable receiving of device: Function not implemented
```

So seems to support @mr-stegosaurus's hunch that this may be related to #9508.  I'm going to try [downgrading WSL](https://github.com/microsoft/WSL/issues/9508#issuecomment-1404186768) and I'll try to remember to report back here if that works around the issue.

**Comment by mr-stegosaurus** [comment]
So far rolling back has resolved my issue. I will leave this open for a bit if anyone has questions or wants more logs for troubleshooting... will close it in the coming weeks if nothing else is documented here.

**Comment by rpatterson** [comment]
Indeed I forgot to report back, thanks for the reminder @mr-stegosaurus!  Rolling back to WSL v1.0.3 successfully works around this issue for me as well.  IMO, however, this issue should remain open until the underlying issue is fixed in current releases.  IOW, downgrading is not a solution so much as a workaround for a real issue that still remains.
