### ISSUE TITLE
WSL2 sock bind error: 38 function not implement

### ISSUE THREAD

**Issue by wangjf78** [microsoft/WSL#9587]
### Version

Windows version: 10.0.19044.2546

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu-18.04

### Other Software

Docker ce 23.0.0
minikube version: v1.28.0 (with k8s 1.23) 
VSCode 

### Repro Steps

Start minikube , deploy some workload 

Running after 2-3 hours. 

Any call to sock bind will report errorno 38 

### Expected Behavior

In docker / K8S bind a server sock

In WSL,  bind a server sock

e.g. ： python -m http.server  

### Actual Behavior

In docker / K8S tcp sock bind return errorno 38

docker run nginx:alpine will cause :
bind: 38: function not implemed

In WSL, any tcp sock bind call return errno 38 
python -m http.server 

<OSError> bind: errorno 38 <Unknown>

**Comment by wangjf78** [comment]
[WslLogs-2023-02-04_15-20-51.zip](https://github.com/microsoft/WSL/files/10608145/WslLogs-2023-02-04_15-20-51.zip)

grafana/loki in K8S Error: 
listen tcp :80: bind: function not implemented
error initialising module: server
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122

attach to container : 
$ docker exec -it kube-nginx-1 sh
failed to create runc console socket: listen unix /tmp/pty431848913/pty.sock: bind: function not implemented: unknown

$ python -m http.server
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/http/server.py", line 1211, in <module>
    test(HandlerClass=handler_class, port=args.port, bind=args.bind)
  File "/usr/lib/python3.6/http/server.py", line 1185, in test
    with ServerClass(server_address, HandlerClass) as httpd:
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 38] Function not implemented

**Comment by pmartincic** [comment]
@wangjf78, In the future please let the log collection run while reproducing the issue, else there isn't anything for me to see. It only collects logs from events while it is running (not a time machine).

Else go ahead and try 1.1.3

**Comment by wangjf78** [comment]
I had update to 1.1.3 in last 2 days. It's worked, thanks !
