### ISSUE TITLE
When I have multiple distributions running at the same time. They have the same IP address.

### ISSUE THREAD

**Issue by HBat11233** [microsoft/WSL#9595]
### Version

Microsoft Windows [版本 10.0.19044.2486]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Debian

### Other Software

No

### Repro Steps

![image](https://user-images.githubusercontent.com/33086330/216918217-a232207d-5d61-466a-8945-26bf05fe3e69.png)

### Expected Behavior

Why they have the same IP？Shouldn't I get a different ip?

### Actual Behavior

they have the same IP

**Comment by Biswa96** [comment]
This is expected behaviour. The Linux distributions in WSL2 shares same network namespace https://man7.org/linux/man-pages/man7/network_namespaces.7.html

**Comment by HBat11233** [comment]
> This is expected behaviour. The Linux distributions in WSL2 shares same network namespace https://man7.org/linux/man-pages/man7/network_namespaces.7.html

Thank you very much! 
So if I want to access multiple wsl distributions on windows through different ip addresses. Do I need to configure a network myself?

**Comment by HBat11233** [comment]
https://github.com/microsoft/WSL/issues/4304#issue-467982878
The same issues

**Comment by foxhacker0000** [comment]
same issue
