### ISSUE TITLE
git credential manager not working and not accurately documented (as far as I can tell)

### ISSUE THREAD

**Issue by plastikfan** [microsoft/WSL#9597]
### Version

Microsoft Windows [Version 10.0.19045.2486]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
WSL extension for Vscode: v0.72.0

### Repro Steps

following the instructions at: [git-credential-manager-setup](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup),

seeing this: "If GIT installed is >= v2.36.1"

which git is being referred to here? Is it the windows git version or the linux wsl installation git version. No matter which of these instructions is followed, an error is reported, but different ones:

- assuming Git version > v2.36.1:

```
 plastikfan@Janus  ~/dev/github/go/snivilised/extendio λ   master  git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
 plastikfan@Janus  ~/dev/github/go/snivilised/extendio λ   master  git push origin master
/mnt/c/Program Files/Git/mingw64/bin/git-credential-manager-core.exe: Invalid argument
Username for 'https://github.com':
```

- assuming Git version not < v2.36.1:
- 
```
plastikfan@Janus  ~/dev/github/go/snivilised/extendio λ   master  git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
 plastikfan@Janus  ~/dev/github/go/snivilised/extendio λ   master  git push origin master
/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe get: 1: /mnt/c/Program Files/Git/mingw64/libexec/git-core/git-credential-manager.exe: not found
Username for 'https://github.com':
```

So either way, authentication doesn't work following the documented instructions.

In 'C:\Program Files\Git\mingw64\bin' I have:

> git-credential-manager-core.exe

In 'C:\Program Files\Git\mingw64\libexec\git-core' I do NOT have

> git-credential-manager.exe

so I guess I should be using the setup for Git version > v2.36.1:

on windows side:

```
λ gcm git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.39.0.2   C:\Program Files\Git\cmd\git.exe
```

Other info:

- I have 2FA setup with a PAT
- Under WIndows credential manager, under Web Credentials, I see nothing, under Windows Credentials, I see an entry under `git:https://github.com`

### Expected Behavior

correct authentication using windows credential manager

### Actual Behavior

See the 2 errors already indicated

**Comment by pmartincic** [comment]
Please file this bug against the documentation repo, not the code repo:
https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/wsl-git.md
