### ISSUE TITLE
A web server running in WSL is not accesible from the local network

### ISSUE THREAD

**Issue by emarashliev** [microsoft/WSL#9598]
### Version

1.0.3.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.79.1

### Distro Version

Ubuntu 22.04

### Repro Steps

When I start `python -m http.server 8888` inside Ubuntu.

### Expected Behavior

I should be able to access it when I type `http://<local_ip>:8888` in a browser from other computer in the same local network.

### Actual Behavior

I'm unable to access the running web server in the WSL.
When I start the server with the same command but in PowerShell (outside of the WSL) the url it is accessible from the same other computer in my home local network.

**Comment by emarashliev** [comment]
I solved my issue by using this tutorial https://learn.microsoft.com/en-us/windows/wsl/networking just was a bit obscure to which IP I had to  bind it

**Comment by n1kk** [comment]
Had same issue. Thank you @emarashliev for a link. 

And I also had a problem with IP to bound it to, the `(wsl hostname -I)` command returned `127.0.1.1` but that didn't work, I actually had to bind it to `127.0.0.1`.

**Comment by PhilippeR** [comment]
A cool tuto here https://www.youtube.com/watch?v=-0XgLRAQ6eE
