### ISSUE TITLE
Docker Desktop mounts and WSL2

### ISSUE THREAD

**Issue by abalhomaid** [microsoft/WSL#9601]
### Version

Microsoft Windows [Version 10.0.22000.1455]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Release:        22.04

### Repro Steps

After Windows machine restarts, cannot run docker-compose up --build
I am forced to prune containers and volumes to run

Cannot create container for service db: failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/9bd5c858296c90fb44785e9a0392160a588037e402049f24068ab285099e7318:/var/lib/docker/volumes/ 0x1000: no such file or directory

### Expected Behavior

docker-compose up --build runs successfully

### Actual Behavior

Cannot create container for service db: failed to mount local volume: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/9bd5c858296c90fb44785e9a0392160a588037e402049f24068ab285099e7318:/var/lib/docker/volumes/ 0x1000: no such file or directory

**Comment by OneBlue** [comment]
Thanks for reporting this @abalhomaid. I'm not seeing anything showing that this is a WSL2 issue. I'd recommend raising a [docker desktop issue](https://github.com/docker/for-win/issues) instead.
