### ISSUE TITLE
[Bug] wsl command gives no output and does nothing on Windows Server Core

### ISSUE THREAD

**Issue by lightlike** [microsoft/WSL#9603]
### Version

Microsoft Windows [Version 10.0.20348.1487]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

unable to get

### Distro Version

unable to get

### Other Software

Google Cloud Management Software (no idea what exactly)
Otherwise: none/fresh install

### Repro Steps

1. Create System (in this case from google cloud Build 20230111)
2. try any `wsl` command in `powershell` or `cmd`. E.g.:
	- `wsl --help`
	- `wsl --version`
	- `wsl --status`
	- `wsl --install -d Debian`

### Expected Behavior

`wsl` executes the command and at least throws an error

### Actual Behavior

Wsl does absolutely nothing for a few seconds and then closes.

It does seem to execute as commands like `wsl --status` take a bit longer (about 11 sec) but there still is nothing in the console.

**Comment by lightlike** [comment]
The logs are below. I executed `wsl --status` and `wsl --install -d Debian` during the collection phase.

[WslLogs-2023-02-08_08-13-55.zip](https://github.com/microsoft/WSL/files/10683320/WslLogs-2023-02-08_08-13-55.zip)

Further update regarding the problem.
This only seems to happen with Windows Server Core and not with normal Windows Server.
This happened over multiple different machines all setup the same way via terraform.

Normal Windows Server has problems with executing my script as System-User but that seems to have nothing to do with this problem and I will research that separately.

**Comment by 573** [comment]
Same on my machine.

[WslLogs-2023-02-08_11-25-39.zip](https://github.com/microsoft/WSL/files/10684792/WslLogs-2023-02-08_11-25-39.zip)

**Comment by elsaco** [comment]
`wsl.exe` crashes on `Windows Server Core` with error `0xc0000409`. Maybe is missing some module(s). This is being logged when running `wsl.exe`:

```
TimeCreated  : 2/9/2023 8:58:09 PM
ProviderName : Application Error
Id           : 1000
Message      : Faulting application name: wsl.exe, version: 10.0.20348.1311, time stamp: 0xe3e301c5
               Faulting module name: wsl.exe, version: 10.0.20348.1311, time stamp: 0xe3e301c5
               Exception code: 0xc0000409
               Fault offset: 0x000000000001440e
               Faulting process id: 0xf34
               Faulting application start time: 0x01d93d0c44fed509
               Faulting application path: C:\Windows\system32\wsl.exe
               Faulting module path: C:\Windows\system32\wsl.exe
               Report Id: d15e3435-e3fa-4f50-a1ff-0ddd1fae9278
               Faulting package full name:
               Faulting package-relative application ID:

```

It works fine on `Widows Server 2022` + `Desktop Experience`:

```
elsaco@REDMOND:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

elsaco@REDMOND:~$ wsl.exe --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.20348.1366
```

**Comment by jalove** [comment]
same. fresh install of windows server core 2022.
[WslLogs-2023-06-10_19-55-34.zip](https://github.com/microsoft/WSL/files/11713263/WslLogs-2023-06-10_19-55-34.zip)
