### ISSUE TITLE
dconf will not work properly for a second user

### ISSUE THREAD

**Issue by castorfou** [microsoft/WSL#9609]
### Windows build number:

10.0.19044.0

### Your Distribution version:

22.04

### Your WSL versions:

Version WSL : 1.0.3.0
Version du noyau : 5.15.79.1
Version WSLg : 1.0.47
Version MSRDC : 1.2.3575
Version direct3D : 1.606.4
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
version Windows : 10.0.19044.2486

### Steps to reproduce:

1. create a new user in WSL: `sudo adduser --gecos "" fastai`, `sudo usermod -aG sudo,adm fastai`
2. switch to that user: `su - fastai`
3. setup DISPLAY env: 
```
pushd ~
tee -a .bashrc << EOF
export DISPLAY=":0"
EOF
source .bashrc
popd
```

Launch firefox (which had been installed by main user from snap)

### Actual behavior:

Firefox is launched and somehow can be used but

Here are dconf-CRITICAL error appearing in terminal
```
update.go:85: cannot change mount namespace according to change mount (/run/user/1001/doc/by-app/snap.firefox /run/user/1001/doc none bind,rw,x-snapd.ignore-missing 0 0): cannot inspect "/run/user/1001/doc": lstat /run/user/1001/doc: permission denied
mkdir: cannot create directory ‘/run/user/1001’: Permission denied
(firefox:38995): dconf-CRITICAL **: 15:30:51.740: unable to create directory '/run/user/1001/snap.firefox/dconf': Permission denied.  dconf will not work properly.
```
I can use firefox but I cannot update CA.
Have similar issues with nautilus where I cannot change shortcuts.

Is there a missing step here explaining those issues? Or it is not fully supported yet to have multiple users in WSL?

**Comment by jibal** [comment]
So MS closes bug reports because MS never responds to them? No wonder there are so many bugs.
