### ISSUE TITLE
wsl.exe --mount is not supported on ARM64

### ISSUE THREAD

**Issue by stevecapperarm** [microsoft/WSL#9611]
### Version

Microsoft Windows [Version 10.0.22621.1194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu 22.04.1 LTS

### Repro Steps

Hello!
I run:
`wsl --mount \\.\PHYSICALDRIVE1 --bare`

### Expected Behavior

I expect the physical drive to be mounted.

### Actual Behavior

I get:
```
wsl.exe --mount is not supported on ARM64.
Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED
```

**Comment by hwine** [comment]
Per @craigloewen-msft [statement](https://github.com/microsoft/WSL/issues/6817#issuecomment-823431292), shouldn't this be considered a bug?

**Comment by Rippanda12** [comment]
Same bug on W11 on ARM64

**Comment by adiantek** [comment]
same for me

**Comment by camiloa17** [comment]
Hello Team, I am encountering issues while attempting to run Docker on my new ARM Surface Pro Copilot + PC, similar to those previously experienced.

```
running WSL command wsl.exe C:\Windows\System32\wsl.exe --mount --bare --vhd <HOME>\AppData\Local\Docker\wsl\disk\docker_data.vhdx: wsl.exe --mount is not supported on ARM64.
Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED
: exit status 0xffffffff
checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
```

SS of the issue 
![image](https://github.com/microsoft/WSL/assets/45472315/d229beea-acb8-4354-9a2d-be836e7112db)

**Comment by zmedgyes** [comment]
@camiloa17 I had the same error. For me, the issue was, that I have tried to install the regular Windows version of Docker Desktop and not the Windows ARM Beta ([current latest installer](https://desktop.docker.com/win/main/arm64/153621/Docker%20Desktop%20Installer.exe)).

**Comment by camiloa17** [comment]
> @camiloa17 I had the same error. For me, the issue was, that I have tried to install the regular Windows version of Docker Desktop and not the Windows ARM Beta ([current latest installer](https://desktop.docker.com/win/main/arm64/153621/Docker%20Desktop%20Installer.exe)).

Thank you, this worked!

**Comment by christseng89** [comment]
Thanks @camiloa17, it worked for my Surface Pro 11.

**Comment by tballowe** [comment]
> @camiloa17 I had the same error. For me, the issue was, that I have tried to install the regular Windows version of Docker Desktop and not the Windows ARM Beta ([current latest installer](https://desktop.docker.com/win/main/arm64/153621/Docker%20Desktop%20Installer.exe)).

Thank you @camiloa17! I was pulling my hair out trying to figure this out on my Surface Laptop 7. Worked like a charm!

**Comment by kipters** [comment]
Bug still present in WSL v2.2.4.0

**Comment by wojtow** [comment]
> Hello Team, I am encountering issues while attempting to run Docker on my new ARM Surface Pro Copilot + PC, similar to those previously experienced.
> 
> ```
> running WSL command wsl.exe C:\Windows\System32\wsl.exe --mount --bare --vhd <HOME>\AppData\Local\Docker\wsl\disk\docker_data.vhdx: wsl.exe --mount is not supported on ARM64.
> Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED
> : exit status 0xffffffff
> checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
> ```
> 

Crowdstrike is (at the time I write this) also wanting to block the various commands run during Docker desktop installation on Win ARM64.  The error ends up being different, but that's the next hurdle one  might encounter.

**Comment by christseng89** [comment]
First, to use Docker Desktop for Windows ARM version, if k8s is enabled, then WSL version 2.2.4.0 should be worked with.  

When Docker Engine is running, then use Command Line 'wsl --shutdown' to restart the Docker Desktop then both Docker and k8s works with my new Surface Pro 11.    Hope it helps.

**Comment by garam-park** [comment]
> @camiloa17 I had the same error. For me, the issue was, that I have tried to install the regular Windows version of Docker Desktop and not the Windows ARM Beta ([current latest installer](https://desktop.docker.com/win/main/arm64/153621/Docker%20Desktop%20Installer.exe)).

Thank you👍

**Comment by lilith** [comment]
Docker is really needed on WOA to enable development.  I hope this is prioritized.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.3.21 on newer versions of Windows.

**Comment by andrea-reale** [comment]
Hi @benhillis thanks for this work, it's great to get parity on ARM64!

Can you please clarify the minimum Windows version where this is supported, please? For example I am testing on Win11Pro 22623.1250 and I see it's not supported on that version.

```
> wsl.exe --mount --bare --vhd data.vhdx

wsl.exe --mount is not supported for ARM64 on this version of Windows
Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED

> wsl.exe --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22623.1250
```

**Comment by izhyvaiev** [comment]
Still not working on latest wsl and windows 11 pro version

> wsl --mount \\.\PHYSICALDRIVE1 --bare
wsl.exe --mount is not supported for ARM64 on this version of Windows.
Error code: Wsl/Service/WSL_E_WSL_MOUNT_NOT_SUPPORTED#

> wsl --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2314

**Comment by christseng89** [comment]
You have use wsl 2.2.4 to work with Docker Desktop AMD version.   Download wsl 2.2.4 from https://github.com/microsoft/WSL/releases/tag/2.2.4.

wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.26120.2222

**Comment by izhyvaiev** [comment]
@christseng89 WSL  for x64 always worked, but using it means losses through the binary translation on Prism. This topic is about WSL running natively ARM. And Docker is not relevant here as well, as bug is WSL bug, not Docker bug.

**Comment by izhyvaiev** [comment]
@andrea-reale `wsl.exe --mount on ARM64 requires Windows version 27653 or newer.`
So for now it's generally Canary channel

**Comment by jmbIves** [comment]
On x86-64 just do "wsl --update" if "--mount" option doesn't exist, it may help also on arm

**Comment by powderblock** [comment]
Very annoying bug. Facing the same issue for weeks now on my Windows 11 PC.

I plan to upgrade Windows version to "Windows Insider" what ever the heck that even is. Will

![Image](https://github.com/user-attachments/assets/e5c66237-2846-4401-a20b-463df9eb87bb)

**Comment by sai0718** [comment]
<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/bd8c055d-5ff7-446a-8283-ae54f1c18aeb" />

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/e0410d40-5c9d-4c83-887b-2a22b4493edf" />

**Comment by sai0718** [comment]
i am facing above issue from past 4 days, i tried so many ways using Chatgpt but nothing works plz help

**Comment by sai0718** [comment]
I also used windows insider program, but when i installed its an error.

i had contacted windows support they told this :- **Windows version 27653 appears to be a specific build of Windows 11, likely part of the Windows Insider Program. This build includes updates and features that are being tested before they are released to the general public. For example, it has been mentioned in the context of supporting certain features for WSL (Windows Subsystem for Linux) on ARM64 devices.**
Windows insider is an open-source OS, specially designed for developers. So, we do not officially support Windows insiders devices.
<img width="647" alt="Image" src="https://github.com/user-attachments/assets/38d32cd7-fd2c-4f9a-8df2-0a18ff19af69" />

**Comment by gerbermarco** [comment]
What worked for me was downgrading to a lower Docker version, 4.38.0 in my case. You can try the following:

1. Uninstall Docker Desktop
2. Download Docker Desktop version 4.38.0. Make sure you choose `Windows ARM Beta`. Download link: https://docs.docker.com/desktop/release-notes/#4380
3. Run the installer
4. Run `wsl --update` in a CMD
5. Start Docker Desktop

**Comment by spirilis** [comment]
This bug is still present (Surface Pro 11, Win11 Pro) as of WSL 2.6.1.0

**Comment by powderblock** [comment]
I stopped using docker because of this issue!

**Comment by christseng89** [comment]
From https://docs.docker.com/desktop/setup/install/windows-install/ download the ARM (Early Access) version.  Hope it helps.
