### ISSUE TITLE
Error code: Wsl/0x80070424

### ISSUE THREAD

**Issue by coyoteXujie** [microsoft/WSL#9617]
### Version

22621.1105

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

Windows PowerShell displays "Error code: Wsl/0x80070424" after the computer is restarted.

### Expected Behavior

Normal information

### Actual Behavior

nothing

**Comment by PureMing** [comment]
Windows Subsystem for Linux in Microsoft Store something is wrong.
Uninstall the software fixes the problem.

**Comment by densuke** [comment]
I encountered the same issue.
I re-installed WSL and it is still the same.
(`wsl --update` is successfully(not need to update))

**Comment by coyoteXujie** [comment]
可以尝试在应用中修复它，就好了




xujie199609
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/WSL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/WSL] Error code: Wsl/0x80070424 (Issue #9617)





 
I encountered the same issue.
 I re-installed WSL and it is still the same.
 (wsl --update is successfully(not need to update))

**Comment by CMJNB** [comment]
[WslLogs-2023-07-30_00-59-20.zip](https://github.com/microsoft/WSL/files/12207621/WslLogs-2023-07-30_00-59-20.zip)
please..

> 你好！您能否提供更多日志以帮助我们更好地诊断您的问题？
> 
> 若要收集 WSL 日志，请在**管理电源外壳提示符**下下载并执行 [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1)：
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> 完成后，scipt将输出日志文件的路径。
> 
> 完成后，请将输出文件上传到此 Github 问题。
> 
> [单击此处](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method)了解有关日志记录的更多信息
> 
> 谢谢！

**Comment by bernhardkaindl** [comment]
@OneBlue Same here.

**Comment by karstengresch** [comment]
Same here, trying to install Podman for Windows.
