### ISSUE TITLE
Windows apps icon on the taskbar is a Penguin when running Windows apps from within WSL (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ctsyeh** [microsoft/WSL#9625]
### Version

10.0.19044.2486

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

Ubuntu 20.04 and Ubuntu 22.04

### Other Software

Windows applications (notepad.exe), MobaXterm, BeyondCompare (BComp.exe)

### Repro Steps

Within WSL 2 Ubuntu 20.04 distro, run notepad.exe

### Expected Behavior

Expects the icon on the taskbar to show a regular Notepad icon

### Actual Behavior

It shows a Penguin icon

This used to work before until I ran wsl --update and got the latest WSL above.

I run MobaXterm and Beyond Compare throughout the day and now, they are grouped as Windows Subystem for Linux app, with a Penguin icon, which makes it hard to identify the application.

**Comment by elsaco** [comment]
@ctsyeh change your icon to a different format than SVG. For each menu entry that uses `*.svg` it logs, and changes the icon to the default penguins:

`/usr/share/icons/hicolor/scalable/apps/org.gnome.Console.svg: unrecognized file header 0x3c 0x3f 0x78 0x6d`

**Comment by benhillis** [comment]
I was able to reproduce this on Windows 10, but not Windows 11. I'll reach out to the shell folks to see if they have any thoughts.

**Comment by owenstake** [comment]
i have the same problem

**Comment by ctsyeh** [comment]
> @ctsyeh change your icon to a different format than SVG. For each menu entry that uses `*.svg` it logs, and changes the icon to the default penguins:
> 
> `/usr/share/icons/hicolor/scalable/apps/org.gnome.Console.svg: unrecognized file header 0x3c 0x3f 0x78 0x6d`

Hi, which icon?  I didn't create any short-cut icon, I simply execute Beyond Compare from within wsl (bcomp.exe).
