### ISSUE TITLE
when i type wsl command it appears this

### ISSUE THREAD

**Issue by testtest954** [microsoft/WSL#9626]
when i type wsl when uninstalling it appears this
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
i try
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
that didnt work
is there a way to fix this?

**Comment by benhillis** [comment]
You are running a version of Windows that requires downloading a kernel .msi file. The instructions are in the above link.
