### ISSUE TITLE
Unable to install mysql 8.0

### ISSUE THREAD

**Issue by normaling** [microsoft/WSL#9628]
### Version

win11 22H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu22.04 tls

### Repro Steps

Execute command
sudo apt update
sudo apt install mysql-server

### Expected Behavior

can enter MySQL normally

### Actual Behavior

Apt has a warning when executing the installation command and the mysqld service is not started.
The warning contents are as follows.
```
Dpkg: Error processing package mysql-server-8.0 (-- configure):
Installed mysql-server-8.0 package post-installation script subprocess returned error status 1
Dpkg: The configuration of mysql-server cannot continue because of the dependency problem:
Mysql-server depends on mysql-server-8.0; However:
The software package mysql-server-8.0 has not been configured.
Dpkg: Error processing package mysql-server (-- configure):
Dependency issue - not yet configured
Because the error message indicates that this is caused by the previous problem, the apport report is not written.
Processing trigger for man-db (2.10.2-1)
An error occurred during processing:
mysql-server-8.0
mysql-server

E: Sub-process /usr/bin/dpkg returned an error code (1)
```
When I use the service mysql start command to start the mysql service, its feedback is as follows
 * Starting MySQL database server mysqld                                                                 [fail]
 
When I use the command mysql to access the mysql service, the situation is as follows
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
Access the configuration file/etc/mysql/my.cnf. The content of this configuration file is as follows

```
# The MySQL database server configuration file.
#
# You can copy this to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
# 
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/
```

**Comment by OneBlue** [comment]
Closing since this is not a WSL issue, I recommend [reporting it to mysql directly](https://bugs.mysql.com/)
