### ISSUE TITLE
GPU acceleration missing/unavailable on fresh install (Ubuntu 22.04.1)

### ISSUE THREAD

**Issue by MrSquid47** [microsoft/WSL#9632]
### Version

Microsoft Windows [Version 10.0.22621.1194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04.1

### Other Software

mesa/mesa-utils

### Repro Steps

1. Install WSL + Ubuntu
2. `sudo apt update && sudo apt upgrade` and `sudo apt install mesa-utils`
3. Run `glxinfo -B`

### Expected Behavior

My Nvidia GPU should be shown in the output using the D3D12 mesa driver.

### Actual Behavior

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 15.0.6, 256 bits) (0xffffffff)
    Version: 22.2.5
    Accelerated: no
    Video memory: 6937MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.6, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

### Diagnostic Logs

strace: https://gist.github.com/MrSquid47/d2fb6666268fdcb6cbd76d87eea7cfb0
[WslLogs-2023-02-14_14-32-28.zip](https://github.com/microsoft/WSL/files/10729119/WslLogs-2023-02-14_14-32-28.zip)
[DxDiag.txt](https://github.com/microsoft/WSL/files/10729127/DxDiag.txt)

**Comment by sbradnick** [comment]
Thanks for this. I've been seeing "Device: D3D12 ()" via iGPU for the longest time and thought nothing of it until exporting that variable; now the NVIDIA dGPU is listed in () after "Device: D3D12" :+1:

**Comment by MrSquid47** [comment]
No problem. This variable could probably be documented more prominently since it's rather important for OpenGL rendering. The choice to default to integrated graphics over the dedicated GPU is a bit questionable to me as well. I feel like this is the opposite of what most people expect. I don't regularly update my Intel GPU driver so the outdated version was not functioning with WSL. This made it difficult to identify that it was even trying to use that GPU.

**Comment by Reschivon** [comment]
`MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA` Thank you. I have been sifting through forum posts for days to no avail. For stock WSL 22.04 installs where `glxgears` crashes (given properly installed WSL CUDA drivers), this is the fix.
