### ISSUE TITLE
WSL hangs after restarting "Host Network Service"

### ISSUE THREAD

**Issue by Oppfinnaren** [microsoft/WSL#9634]
### Version

Windows: 10.0.19042.2486

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Repro Steps

wsl --shutdown
Restart-Service -name hns
wsl

### Expected Behavior

wsl should start

### Actual Behavior

**Get this following message:**
The remote procedure call failed and did not execute.
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x800706bf

Only working solution i've found to make wsl work again is to restart computer.

**Comment by Oppfinnaren** [comment]
> Why did you run `Restart-Service -name hns` ? If you run `Restart-Service -name lxssmanager` did it solve the issue?
I had some other error message in wsl which i thought could be solved by restarting all services. And then i found out that restarting this service crashed wsl completly. Running `Restart-Service -name lxssmanager` doesn't solve this issue.

**Comment by Oppfinnaren** [comment]
Also worth mentioning that i've been able to reproduce this on multiple computers.

**Comment by Biswa96** [comment]
> I had some other error message in wsl which i thought could be solved by restarting all services.

You are going into [XY problem](https://en.wikipedia.org/wiki/XY_problem). Report the actual issue rather than your attempted workaround.

**Comment by zcobol** [comment]
@Oppfinnaren how do you restart the service? It has dependencies and needs the `Force` flag set to stop it, so maybe restarting the service is not a wise idea.

**Comment by benhillis** [comment]
Restarting the HNS service with the force flag is going to kill other things. I would not suggest doing this.
