### ISSUE TITLE
WSL2 using more than "50% of total memory on Windows or 8GB, whichever is less" (my machine has 24GB)

### ISSUE THREAD

**Issue by NGRhodes** [microsoft/WSL#9636]
### Version

10.0.22621.1105

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Start WSL2 fresh (eg restart LXSSMANAGER service or reboot machine)
Open terminal to Ubuntu.
Run the command `top`.
Observe memory allocation is 50% of physical memory and which is higher than the documented 8gb.

### Expected Behavior

https://learn.microsoft.com/en-us/windows/wsl/wsl-config states "50% of total memory on Windows or 8GB, whichever is less" so in my case with 24GB physical memory should have 8GB allocated to WSL2.

### Actual Behavior

```
top - 19:49:30 up 5 min,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:   6 total,   1 running,   5 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.1 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  11892.8 total,  11404.4 free,    326.2 used,    162.2 buff/cache
MiB Swap:   3072.0 total,   3072.0 free,      0.0 used.  11340.1 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0    2276   1536   1440 S   0.0   0.0   0:00.00 init
    4 root      20   0    2292     68     68 S   0.0   0.0   0:00.00 init
    8 root      20   0    2284    100      0 S   0.0   0.0   0:00.00 init
    9 root      20   0    2300    104      0 S   0.0   0.0   0:00.00 init
   10 nick      20   0    6216   5068   3336 S   0.0   0.0   0:00.07 bash
   29 nick      20   0    7788   3624   3036 R   0.0   0.0   0:00.12 top
```

### Diagnostic Logs

[WslLogs-2023-02-14_19-35-38.zip](https://github.com/microsoft/WSL/files/10736283/WslLogs-2023-02-14_19-35-38.zip)
![Screenshot 2023-02-14 194520](https://user-images.githubusercontent.com/617587/218846218-d8b43e94-ffd3-4538-a65f-f24b29a33f0e.png)

**Comment by NGRhodes** [comment]
Work around:
Memory settings in .wslconfig are honoured, set desired memory size there.

**Comment by benhillis** [comment]
Based on previous feedback, this was modified to be 50% (without the 8GB upper limit). We will update the docs.

**Comment by chadjefferies** [comment]
Hello, it appears the docs still state "50% of total memory on Windows or 8GB, whichever is less;".
