### ISSUE TITLE
False `init` file creation time

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9638]
### Version

Microsoft Windows [Version 10.0.22621.1265]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04.1

### Repro Steps

Stat `/init` or use long listing format.

### Expected Behavior

Sane file time info.

### Actual Behavior

```
dragon% date
Tue Feb 14 17:47:11 PST 2023
dragon% ls -l /init
-rwxrwxrwx 1 root root 1870152 Dec 31  1969 /init
```

12/31/1969 is before UNIX Time!

There are other files with unsoud time signatures. Start `wsl --debug-shell` and list root fs:

```
-rwxrwxrwx   1 root root 1870152 Jan  1  1970 init
drwxr-xr-x  15 root root    4096 Jan  1  1970 systemvhd
```
Two files showing the beginning of UNIX Epoch.

**Comment by benhillis** [comment]
Thanks, will resolve this.

**Comment by benhillis** [comment]
Fixed in https://github.com/microsoft/WSL/releases/tag/1.1.5.
