### ISSUE TITLE
Buffers running out of space

### ISSUE THREAD

**Issue by arichtman-srt** [microsoft/WSL#9639]
### Version

Microsoft Windows [Version 10.0.19044.2546]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

NixOS-23.05.20230207.7479275

### Other Software

```
$ code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

### Repro Steps

1. Start WSL terminal
2. Start VSCode with WSL as remote
3. Edit files, commit and push stuff. Working normally.

### Expected Behavior

1. Try to open new tab or VSCode remote connection
2. Connection opens without error

### Actual Behavior

```
PS C:\Users\ariel.richtman> wsl
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
Error code: Wsl/Service/0x80072747
```

### Diagnostic Logs

[WslLogs-2023-02-15_13-04-55.zip](https://github.com/microsoft/WSL/files/10738896/WslLogs-2023-02-15_13-04-55.zip)

**Comment by zcobol** [comment]
If resource limits are being exceeded you'll get this kind of error messages. Is your system running out of memory?

**Comment by arichtman-srt** [comment]
Not that I saw, it was idling at ~20/32 GiB. CPU was similarly low with no spikes. It's a laptop i7 if that helps.
That said it could be the VM it's running on not getting enough share of non-compressible resources.

**Comment by ashermiddleton** [comment]
Also getting this, no abnormal resource usage, but WSL memory usage is quite high at 8GB

**Comment by arichtman-srt** [comment]
For what it's worth I stopped using VSCode and haven't had the issue reoccur.

**Comment by LiamKarlMitchell** [comment]
I'm at 52% of my ram which totals 32GB and I keep getting this error.
Not sure if related but did a windows update recently-ish and updated PHPStorm.

There is free space on my hard drives

Could it be related to too many files in /var/run/WSL ?
395 files in this directory.
```
 sudo ls -alh /var/run/WSL | wc
    395    3548   21510
```

I do notice there seem to be a lot of wslhost.exe's running not sure if its normal.

**Comment by stu177** [comment]
I've had the exact same issue when using PhpStorm (link to issue raised on Jetbrains issue tracker [here](https://youtrack.jetbrains.com/issue/GTW-3002/WSL2-crashes-with-Gateway-and-Webstorm-with-Error-code-Wsl-Service-0x80072747#focus=Comments-27-8007885.0-0)).

For me, this issue only occurs when trying to use the git executable inside of the WSL filesystem from PhpStorm. If I use a git.exe within the Windows filesystem, this issue does not occur.

**Comment by LiamKarlMitchell** [comment]
Ah, right, so I did have some ssh-agent stuff in my ~/.bash_profile for some reason.

I also had a cd in here.

After updating phpstorm recently, it had stopped working with git due to ssh-agent outputing some numbers into stdout.
Making it output to dev/null fixed that, but then it still couldn't work with git commands due to the cd, like it was using relative paths not absolute.

```
# Run ssh-agent silently.
#eval $(ssh-agent > /dev/null);
#ssh-add > /dev/null 2>&1
```

So every time PHP Storm goes to do something with git or running tests I'm thinking t makes a new connection.
And there has been a long standing bug where it does not remove previous /var/run/WSL handles/sockets?

So thats why I wondered if it was the problem.

Removing the ssh-agent for now in my bash profile has seemed to reduce the issue, but it could have just been rebooting my pc.

**Comment by stu177** [comment]
Ah good find, I think that's sorted my issue as I had a similar thing in my `.profile` to run ssh-agent. We used it for adding the current ssh-agent into an environment variable for use within docker containers but can do it manually if it prevents this issue.

**Comment by webgraphe** [comment]
I suspect the PhpStorm sessions are non-interactive but opened with `--login` as my `~/.profile` is still executed and has similar commands to load the SSH agent; so I just tested for interactivity and it greatly reduced the number of WSL handles opened by ssh-agent:

```
if test "$PS1"; then
    eval `ssh-agent -s`
    ssh-add ~/.ssh/id_rsa
fi
```

Hope this helps!
