### ISSUE TITLE
Can't run notepad++.exe from WSL Ubuntu

### ISSUE THREAD

**Issue by peterkronenberg** [microsoft/WSL#9641]
### Version

Microsoft Windows [Version 10.0.19045.2546]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Ubuntu 2

### Distro Version

Release:        22.04

### Other Software

Notepad++ 64-bit 8.4.9 
(same issue with 32-bit.  Release of Notepad++ probably irrelevant)

### Repro Steps

See https://superuser.com/questions/1768647/errors-running-notepad-from-wsl-unbuntu/1768682?noredirect=1#comment2753514_1768682

I'm trying to run `notepad++.exe` from Ubuntu.  The only time it works is if I first CD to `/mnt/c/Program\ Files/Notepad++`.  But even then, autocomplete doesn't recognize `notepad++.exe`.  I have to type it manually. 

From any other directory, if I type `/mnt/c/Program\ Files/Notepad++/notepad++.exe`, I get an error `/mnt/c/Program Files/Notepad++/notepad++.exe: Invalid argument`.  It doesn't matter what arguments I pass on the command line.

### Expected Behavior

Notepad++ should open the file specified on the command line (or just open it to an empty window if no file is specified)

### Actual Behavior

I get the error `/mnt/c/Program Files/Notepad++/notepad++.exe: Invalid argument`

**Comment by benhillis** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/17727402/220768247-55918b53-a76a-4141-ae15-8d79fd8c7621.png">

I am not able to repro this on the newest version of WSL. Could you try upgrading? `wsl.exe --update`

thanks!

**Comment by peterkronenberg** [comment]
Thanks, after struggling with this for a week or so, it all of a sudden started working.  All I can think is that it was related to this update, **Windows Subsystem for Linux Update - 5.10.102.2**, , which I just installed
