### ISSUE TITLE
ERROR: UtilTranslatePathList; "Failed to translate"

### ISSUE THREAD

**Issue by huettenhain** [microsoft/WSL#9653]
### Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Run `subst W: C:\Windows`
2. Run `New-ItemProperty -Pat 'HKLM:SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'W:' -Value "\??\C:\Windows" -PropertyType 'String'`
3. Reboot the machine
4. Run `cmd.exe`
5. Navigate to `W:`
6. Run `wsl`

### Expected Behavior

WSL launches without error.

### Actual Behavior

The following error message is displayed:
```
<3>WSL (28) ERROR: CreateProcessParseCommon:782: Failed to translate W:\
```
Note: This is a potential duplicate of #9360, but the issue is closed.

**Comment by benhillis** [comment]
Only physical drives (not virtual drives such as the ones created by subst) are automatically mounted by WSL.

**Comment by huettenhain** [comment]
If this is by design, then why does it show up as an error?

**Comment by huettenhain** [comment]
To clarify: My problem is not that the drive is not mounted. My problem is the error message itself.

**Comment by qnxor** [comment]
Darn, I just posted an issue about this too. I too have a DOS Device (virtual drive mounted via registry pointing to a folder) which is also in the %PATH%, so it gets passed to bash and I get errors, in my case `<3>WSL (349) ERROR: UtilTranslatePathList:2866: Failed to translate P:\Python3\` (different error title and number, but obviously related).

`DOS Device`s are available system wide on boot, I see no reason why WSL should ignore them. They can't be unmounted after boot more than any other drive letter can.

**Comment by bc-nine** [comment]
Seriously, this is a non-answer, if it's "by design" then it shouldn't error! It's totally common to have these subst drives set up, so your "by design" solution is to spam the user with errors on every terminal open?
