### ISSUE TITLE
WSL2 will not mount vhdx as swapfile

### ISSUE THREAD

**Issue by Dhruvgera** [microsoft/WSL#9655]
### Version

Microsoft Windows [Version 10.0.22621.963]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83

### Distro Version

Ubuntu 20.04

### Repro Steps

Create .wslconfig
Create vhdx from Disk Management on D drive
Set swapFile=D:\wsl2.vhdx in .wslconfig
Start wsl2
free -h and cat /proc/swaps show no swap partition

### Expected Behavior

Swap partition should have been created

### Actual Behavior

System doesn't create any swap partition

**Comment by Biswa96** [comment]
> Create vhdx from Disk Management on D drive

It is not required to create a vhdx file for swap partition. That vhdx file will be automatically created by WSL Service.

**Comment by Dhruvgera** [comment]
> > Create vhdx from Disk Management on D drive
> 
> It is not required to create a vhdx file for swap partition. That vhdx file will be automatically created by WSL Service.

Yes, but I want to create the swap partition on a different drive than C. Which is not working even after following the Microsoft docs

**Comment by Biswa96** [comment]
The path should be with double slash, like this `swapFile=D:\\wsl2.vhdx`

See the note here https://learn.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by Dhruvgera** [comment]
> The path should be with double slash, like this `swapFile=D:\\wsl2.vhdx`
> 
> See the note here https://learn.microsoft.com/en-us/windows/wsl/wsl-config

Have tried that to no success, same no swap issue occurs. The vhdx was created with dynamic size with a limit of 32GB

**Comment by Biswa96** [comment]
After changing wslconfig file, Have you tried shutting down the WSL2 VM with `wsl.exe --shutdown` command?

**Comment by Dhruvgera** [comment]
> After changing wslconfig file, Have you tried shutting down the WSL2 VM with `wsl.exe --shutdown` command?

Yes, that is exactly how I tested everytime to make sure wsl2 configs are applied

**Comment by elsaco** [comment]
@Dhruvgera don't create a vhdx drive, just specify the swap size and location and the swap area will be create automatically. If you first create a virtual drive you'll have to mount it. This is what I'm using:

Settings in `.wslconfig`

```
swap=2GB
swapfile=G:\\vms\\swap.vhdx
```


and this is WSL output:

```
elsaco@eleven:~$ lsblk
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda    8:0    0 363.1M  1 disk
sdb    8:16   0     2G  0 disk [SWAP]
sdc    8:32   0     1T  0 disk /snap
                               /mnt/wslg/distro
                               /
elsaco@eleven:~$ free -h
               total        used        free      shared  buff/cache   available
Mem:           5.8Gi       395Mi       5.1Gi       2.0Mi       317Mi       5.2Gi
Swap:          2.0Gi          0B       2.0Gi
elsaco@eleven:~$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
/dev/sdb                                partition       2097152         0               -2

```

**Comment by Dhruvgera** [comment]
> @Dhruvgera don't create a vhdx drive, just specify the swap size and location and the swap area will be create automatically. If you first create a virtual drive you'll have to mount it. This is what I'm using:
> 
> Settings in `.wslconfig`
> 
> ```
> swap=2GB
> swapfile=G:\\vms\\swap.vhdx
> ```
> 
> and this is WSL output:
> 
> ```
> elsaco@eleven:~$ lsblk
> NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> sda    8:0    0 363.1M  1 disk
> sdb    8:16   0     2G  0 disk [SWAP]
> sdc    8:32   0     1T  0 disk /snap
>                                /mnt/wslg/distro
>                                /
> elsaco@eleven:~$ free -h
>                total        used        free      shared  buff/cache   available
> Mem:           5.8Gi       395Mi       5.1Gi       2.0Mi       317Mi       5.2Gi
> Swap:          2.0Gi          0B       2.0Gi
> elsaco@eleven:~$ cat /proc/swaps
> Filename                                Type            Size            Used            Priority
> /dev/sdb                                partition       2097152         0               -2
> ```

Thanks! This seems to have worked!
