### ISSUE TITLE
wsl does not work. wsl list returns error: "Insufficient system resources exist to complete the requested service." Wsl/Service/CreateInstance/CreateVm/0x800705aa

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/WSL#9666]
### Version

Microsoft Windows [Version 10.0.19045.2311]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

???

### Distro Version

???

### Repro Steps

```
> wsl list
Insufficient system resources exist to complete the requested service.
Error code: Wsl/Service/CreateInstance/CreateVm/0x800705aa
```

### Expected Behavior

I expect WSL to work.

### Actual Behavior

```
> wsl list
Insufficient system resources exist to complete the requested service.
Error code: Wsl/Service/CreateInstance/CreateVm/0x800705aa
```

**Comment by elsaco** [comment]
@Ark-kun do you have and WSL distros installed? When you execute `wsl list` it will try to run the command `list` in your default distro, and it fails. 

Sample output:

```
PS C:\Users\elsaco> wsl list
/bin/bash: line 1: list: command not found

```

To see what distros are available run `wsl --list`

**Comment by Ark-kun** [comment]
Yes, I have WSL distros. I have Ubuntu and I also have Docker Desktop which installs its own distro.
In fact WSL previously worked in the current session. And now WSL just stopped working.

WSL breaks down all the time just from sitting idle. `vmmem` process starts eating CPU, `wsl --shutdown` stops working etc. But usually all these issues resolve themselves after killing the `wslservice.exe` process. This time however it's not the case. I cannot fix it.

I'm pretty sure the problem will fix itself after restart. But restarting Windows is a real pain for me (all terminals are gone etc). So I'd like WSL to work and not require restarts.

**Comment by Ark-kun** [comment]
And the fun thing is that this issue has disappeared after about a week (no reboots).

I don't know which "resources" it needed on a system with 128GB RAM, but not it has them back...

**Comment by acybppres** [comment]
I have this issue now.  I last ran my Ubuntu 20.04.06 LTS instance a couple of months ago.  Today it failed to start.  So I tried to update.  I get the following nonsensical error:
```
PS C:\> wsl.exe --update
Installing: Windows Subsystem for Linux
Insufficient system resources exist to complete the requested service.
```
I have 128 GB of disk space available, over 20GB of RAM free.  

```
WINDOWS:
Edition: Windows 10 Pro
Version: 22H2
OS Build 19045.2965

WSL:
Default Distribution: Ubuntu-20.04
Default Version: 2
Windows Subsystem for Linux was last updated on 4/3/2022
WSL automatic updates are on.
Kernel version: 5.10.102.1
```
I was able to install and run  the latest Ubuntu 22.04.2 from the store.  I am not sure why my existing distribution simply stopped working.  Fortunately I do not keep my work inside the containers.  I can now launch this instance from Terminal, but I still get the same error when trying to run `wsl --update`.

**Comment by ThomasRedstone** [comment]
> And the fun thing is that this issue has disappeared after about a week (no reboots).
> 
> I don't know which "resources" it needed on a system with 128GB RAM, but not it finds them sufficient...

Oddly, I've started getting this issue.

I can confirm that doubling the RAM doesn't help. I've got 256GB and 133GB free at the moment. It isn't CPU either, as ~40% of my 64 cores are at 0%.

All of my SSDs have hundreds of GB of free space.

**Comment by wagner-santos-ia** [comment]
Having this issue as well

**Comment by yoshikakbudto** [comment]
Having this issue on AMD Ryzen 9 7950X
The system has 32 logical CPUs

As a workaround i had to specify 14 vcpus in `%userprofile%\.wslconfig`:
```ini
[wsl2]
processors=14
```
Increasing processors value or removing the config generates error: `Insufficient system resources exist to complete the requested service. `

**Comment by olove66** [comment]
> Having this issue on AMD Ryzen 9 7950X The system has 32 logical CPUs
> 
> As a workaround i had to specify 14 vcpus in `%userprofile%\.wslconfig`:
> 
> [wsl2]
> processors=14
> Increasing processors value or removing the config generates error: `Insufficient system resources exist to complete the requested service. `

Worked as a charm for me -- thanks a lot 👍
