### ISSUE TITLE
Add command to wsl.exe to perform an Atomic restart of an instance

### ISSUE THREAD

**Issue by thawkins** [microsoft/WSL#9680]
Would it be possible to have an atomic wsl function to restart an instance with the same properties (user, start directory etc)

For example:

Wsl restart -d Ubuntu-22.04

While this can be done with multiple wsl commands, having a single atomic command would allow install scripts inside wsl to self restart

Example a linux bash script would be able to issue:

PowerShell.exe -Command "wsl restart -d Ubuntu-22.04"

**Comment by Biswa96** [comment]
Do you mean something like `wsl.exe --shutdown & wsl.exe -d Ubuntu-22.04` command but in one command line option?

> While this can be done with multiple wsl commands, having a single atomic command would allow install scripts inside wsl to self restart

Why does someone want a single command if it can be done in multiple commands?

**Comment by Biswa96** [comment]
Do you mean something like `wsl.exe --shutdown & wsl.exe -d Ubuntu-22.04` command but in one command line option?

**Comment by thawkins** [comment]
more like

wsl.exe --terminate Ubuntu-22.04 & wsl.exe -d Ubuntu-22.04

But by having it as a single atomic function it can be issued inside wsl and would effect a restart, currently there is no way to do that, you can terminate the distribution, but the wsl command stops running at that point and does not go on tyo do the start-up again. you have to then manually restart it from the windows PowerShell side
