### ISSUE TITLE
Exported and imported wsl instances boot to root.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/WSL#9684]
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1105-Microsoft Fri Jan 01 08:00:00 PST 2016

### Distro Version

openSUSE-Tumbleweed

### Repro Steps

Install openSUSE-Tumbleweed.
Run it. 
Create user.
exit.
Export with wsl --export openSUSE-Tumbleweed suse-tumblewed.tar
Unregister with wsl --unregister openSUSE-Tumbleweed
Import it with wsl --import openSUSE-Tumbleweed e:\wsl\openSUSE-Tumbleweed suse-tumblewed.tar
It boots into root.

### Expected Behavior

user@DESKTOP-P57624Q:~> whoami
user
user@DESKTOP-P57624Q:~>

### Actual Behavior

e:\wsl\openSUSE-Tumbleweed>wsl -d openSUSE-Tumbleweed
DESKTOP-P57624Q:/mnt/e/wsl/openSUSE-Tumbleweed # whoami
root
DESKTOP-P57624Q:/mnt/e/wsl/openSUSE-Tumbleweed # exit
logout

**Comment by kotenok2000** [comment]
It also happened when i exported wsl1 instance and imported as wsl2.

**Comment by thawkins** [comment]
can you see what happens when you launch using wsl.exe with the --user [userid] option?

**Comment by elsaco** [comment]
Unregistering is not necessary, just export and import a distro to see the effect. It's the same when importing a container or rootfs image, it sets  `DefaultUid=0x0`.  When you install a distro it sets `DefaultUid=0x3e8` (1000), the uid of the user added during installation. Check the registry at `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss` for details. To make it permanent modify ` DefaultUid`.

**Comment by benhillis** [comment]
You can also add the below entry to /etc/wsl.conf in the imported distro to set the default user ID:

```
[user]
default=username
```
