### ISSUE TITLE
Partially localized messages when installing

### ISSUE THREAD

**Issue by svick** [Microsoft/WSL#969]
When I installed Bash on Windows, the output was:

```
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: svick
Zadejte nové UNIX heslo:
Opakujte nové UNIX heslo:
passwd: password updated successfully
Installation successful!
The environment will start momentarily...
Documentation is available at:  https://aka.ms/wsldocs
```

Notice that all text is in English (including "Enter new UNIX username"), except for the password prompts, which are in Czech ("Zadejte nové UNIX heslo" translates to "Enter new UNIX password").

I would expect the installation to be either fully in English, or fully in Czech, not a mix of the two.

My Windows version is 1607 (OS Build 14393.51) according to winver.

I realize this could be caused by the underlying Ubuntu commands (`passwd`?), but I thought it's worth pointing out anyway.

**Comment by bitcrazed** [comment]
Hi @svick. Could you share what locale settings you're running on your PC?

**Comment by svick** [comment]
Display Language is English (United States), Input Language is Czech (Czech Republic). Inside bash, `locale` outputs:

```
LANG=cs_CZ.UTF-8
LANGUAGE=
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=
```

**Comment by benhillis** [comment]
The legasy install experience (lxrun) is deprecated.
