### ISSUE TITLE
Processing fstab with mount -a failed

### ISSUE THREAD

**Issue by bobf32** [microsoft/WSL#9691]
### Version

Microsoft Windows [Version 10.0.19045.2604]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.79.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Nov 23 01:01:46 UTC 2022

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

From a command or powershell prompt:

`bash`

### Expected Behavior

A new WSL bash session should be created

### Actual Behavior

Good: A new terminal is started
Bad: Message "Processing fstab with mount -a failed." is displayed prior to prompt

All was fine yesterday, today I did `wsl --update` and then the problems started.

**Comment by benhillis** [comment]
Could you please share the output of `dmesg`?

**Comment by bobf32** [comment]
Sure, see [dmesg.txt](https://github.com/microsoft/WSL/files/10844680/dmesg.txt)

**Comment by elsaco** [comment]
@bobf32 check you credentials:

```
[    2.941322] CIFS: Attempting to mount \\192.168.0.230\media
[    3.373557] CIFS: Status code returned 0xc000006d NT_STATUS_LOGON_FAILURE
[    3.374255] mount error(13): Permission denied
```

**Comment by bobf32** [comment]
@elsaco Oops, that did it. Thanks.

**Comment by benhillis** [comment]
Cool, glad this is sorted.
