### ISSUE TITLE
Kernel Modules added in /etc/modules and alternatively, added to /etc/modules-load.d/xxx.conf are not loaded

### ISSUE THREAD

**Issue by bernd-sprenger** [microsoft/WSL#9693]
### Version

Microsoft Windows [Version 10.0.22623.1325]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Other Software

Custom compiled Kernel with CAN-networking enabled.
With and without systemd enabled.

### Repro Steps

Compile custom kernel with following configuration changes:

> CONFIG_MODPROBE_PATH="/usr/sbin/modprobe"
> CONFIG_CAN=m
> CONFIG_CAN_RAW=m
> CONFIG_CAN_BCM=m
> CONFIG_CAN_GW=m
> CONFIG_CAN_J1939=m
> CONFIG_CAN_ISOTP=m
> CONFIG_CAN_VCAN=m
> CONFIG_CAN_VXCAN=m
> CONFIG_CAN_DEV=m
> CONFIG_CAN_CALC_BITTIMING=y
> CONFIG_CAN_8DEV_USB=m
> CONFIG_CAN_EMS_USB=m
> CONFIG_CAN_ESD_USB2=m
> CONFIG_CAN_ETAS_ES58X=m
> CONFIG_CAN_GS_USB=m
> CONFIG_CAN_KVASER_USB=m
> CONFIG_CAN_MCBA_USB=m
> CONFIG_CAN_PEAK_USB=m
> CONFIG_CAN_UCAN=m
> CONFIG_CAN_DEBUG_DEVICES=y

and add following lines to /etc/modules:

> vcan
> can
> can-bcm
> can-gw
> can-isotp
> can-raw
> can-j1939
> can-dev
> usb_8dev
> gs_usn
> peak_usb

### Expected Behavior

After reboot/restarting WSL2 the modules should be automatically loaded and shown via the lsmod command:
~/WSL2-Linux-Kernel-linux-msft-wsl-5.15.90.1$ lsmod
> Module                  Size  Used by
> peak_usb               49152  0
> gs_usb                 20480  0
> usb_8dev               20480  0
> can_dev                28672  3 usb_8dev,peak_usb,gs_usb
> can_j1939              65536  0
> can_raw                20480  0
> can_isotp              24576  0
> can_gw                 24576  0
> can_bcm                24576  0
> vcan                   16384  0
> can                    24576  5 can_isotp,can_gw,can_j1939,can_raw,can_bcm

### Actual Behavior

After reboot/restarting WSL2 the modules are not loaded and the lsmod command shows:
~/WSL2-Linux-Kernel-linux-msft-wsl-5.15.90.1$ lsmod
> Module                  Size  Used by

**Comment by elsaco** [comment]
Before adding to `/etc/modules` make sure the modules load/unload okay otherwise it will fail to load them on startup.

**Comment by bernd-sprenger** [comment]
The modules load fine, when I load them with:

> sudo modprobe can && sudo modprobe vcan && sudo modprobe can-bcm && sudo modprobe can-gw && sudo modprobe can-isotp && sudo modprobe can-raw && sudo modprobe can-j1939 && sudo modprobe can-dev && sudo modprobe usb_8dev && sudo modprobe gs_usb && sudo modprobe peak_usb

Using lsmod is showing:

> Module                  Size  Used by
> peak_usb               49152  0
> gs_usb                 20480  0
> usb_8dev               20480  0
> can_dev                28672  3 usb_8dev,peak_usb,gs_usb
> can_j1939              65536  0
> can_raw                20480  0
> can_isotp              24576  0
> can_gw                 24576  0
> can_bcm                24576  0
> vcan                   16384  0
> can                    24576  5 can_isotp,can_gw,can_j1939,can_raw,can_bcm

and /etc/modules has the content:

> \# /etc/modules: kernel modules to load at boot time.
> \#
> \# This file contains the names of kernel modules that should be loaded
> \# at boot time, one per line. Lines beginning with "#" are ignored.
> vcan
> can
> can-bcm
> can-gw
> can-isotp
> can-raw
> can-j1939
> can-dev
> usb_8dev
> gs_usn
> peak_usb

Do you have any suggestion what I might be doing wrong?

Thanks a lot for your help,
have a nice day, 
Bernd

**Comment by elsaco** [comment]
If you're using `systemd` edit `systemd-modules-load.service` and comment out `ConditionVirtualization=!container`  otherwise the service will fail.

Here's sample output using `can` module only:

```
elsaco@eleven:~$ systemctl status systemd-modules-load.service
● systemd-modules-load.service - Load Kernel Modules
     Loaded: loaded (/etc/systemd/system/systemd-modules-load.service; static)
     Active: active (exited) since Wed 2023-03-01 08:42:11 PST; 31s ago
       Docs: man:systemd-modules-load.service(8)
             man:modules-load.d(5)
    Process: 55 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=0/SUCCESS)
   Main PID: 55 (code=exited, status=0/SUCCESS)

Mar 01 08:42:11 eleven systemd-modules-load[55]: Inserted module 'can'
Mar 01 08:42:11 eleven systemd[1]: Finished Load Kernel Modules.
```

and `lsmod` output:

```
elsaco@eleven:~$ lsmod
Module                  Size  Used by
can                    24576  0
```

**Comment by bernd-sprenger** [comment]
Thanks a lot for your help - the modules are loading fine now!
