### ISSUE TITLE
Docker container not able to communicate with other service running on localhost

### ISSUE THREAD

**Issue by alia5gar** [microsoft/WSL#9694]
### Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79

### Distro Version

Ubuntu 20.04

### Other Software

Docker version 23.0.1, build a5ee5b1 (Running in WSL)
`Docker engine is installed inside of WSL`

### Repro Steps

1. Install docker engine in WSL
2. Start a docker container also specify the container port and the host port in the run command (I have a mockserver/mockserver image running in the container)
3. Start another service in WSL (In my case a python unicorn server)

### Expected Behavior

Docker container should be able to reach the service running on localhost

We get the expected result when `--net=host` is passed in the docker run command

### Actual Behavior

Calling the service running locally from the docker container, give connection refuse error

**Comment by pmartincic** [comment]
What `wsl --version` are you running?
