### ISSUE TITLE
`wsl` commands used to work but now just hang, do nothing, and never exit

### ISSUE THREAD

**Issue by loganmay** [microsoft/WSL#9700]
### Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version
2004.2022.1.0

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I can't run any `wsl` commands anymore, so any in theory would work. If I run `wsl --list` for example, it just hangs.

### Expected Behavior

I'm expected that the `wsl` commands work as anticpated

### Actual Behavior

No output is ever printed. It just hangs and the process never completes.

**Comment by Gitii** [comment]
@loganmay Hey, could it be related / the same as described here?
https://github.com/microsoft/WSL/issues/9659 
Does it work when you do a clean/full restart?
