### ISSUE TITLE
High keyboard latency when running wsl

### ISSUE THREAD

**Issue by Promisin** [microsoft/WSL#9711]
### Version

10.0.22621.1265

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

22.04

### Other Software

WSL 版本： 1.0.3.0
内核版本： 5.15.79.1
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.1265

### Repro Steps

open an wsl machine in windows terminal

### Expected Behavior

no latency when typing

### Actual Behavior

When a wsl machine is running, the keyboard latency is very high for any application not running as administrator, which is about 1-2 seconds. There is no exception when using the on-screen keyboard. But other applications running as administrator are not affected. It's so wired. Does anyone else suffer from the same problem?

**Comment by borjamunozfer** [comment]
Try this:
- Modify the **.wslconfig** file on your C:\Users\...\
- Add this line:

```toml
guiApplications=false
```

Shutdown wsl, wait 10 secs, open again & evaluate.

**Comment by borjamunozf** [comment]
I think could be related to this pending issue affecting the overall performance of WSL2 since 1.0.0 version:

- Create or modify the file **.wslconfig** on C:\Users\yourUser\
- Add this line:
```toml
guiApplications=false
```

Shutdown wsl
```cmd
wsl --shutdown
```

Wait 10 seconds & open again to evaluate it.
Tell me how it goes.

**Comment by Promisin** [comment]
> I think could be related to this pending issue affecting the overall performance of WSL2 since 1.0.0 version:
> 
> * Create or modify the file **.wslconfig** on C:\Users\yourUser\
> * Add this line:
> 
> ```toml
> guiApplications=false
> ```
> 
> Shutdown wsl
> 
> ```batchfile
> wsl --shutdown
> ```
> 
> Wait 10 seconds & open again to evaluate it. Tell me how it goes.

Thank you sooo much! It totally worked. As soon as I disabled the guiApplications, there is no keyboard latency in any application anymore.
