### ISSUE TITLE
Need to update hosts file frequently to connect to custom domain mapped to localhost

### ISSUE THREAD

**Issue by ling1726** [microsoft/WSL#9713]
Hi I'm a developer working on Microsoft Teams, and I use WSL in my day to day. I recently got this issue happening from 2months ago. Before that I didn't have issues.

Following the workaround in https://github.com/microsoft/WSL/issues/5728#issuecomment-675473289, I can get a connection to a site served by wsl on localhost. However, I often get DNS lookup errrors after a certain time.

![image](https://user-images.githubusercontent.com/20744592/221887030-84dca26c-5c7e-4384-a6e8-05fdf2ae1f7c.png)

In order to make the connection work again I have to update my _**windows**_ hosts file with some changes and undo them, then the connection will work again for a few minutes before I have to repeat the process.

```
# 1
::1 my.customdomain.com

# 2 - flush DNS
# ::1 my.customdomain.com

# 1 - flush DNS
::1 my.customdomain.com
``` 

However when I run `ping my.customdomain.com` I will get the correct resolution to `::1`.

I think I've reached the limits of what I can try on my own. if you need anymore info I'm happy to follow steps and provide that

**Comment by benhillis** [comment]
Are you modifying your Linux /etc/hosts file? If so, you'll need to set the below setting in /etc/wsl.config so we don't overwrite it.

```
[network]
generateHosts=false
```
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#network-settings

**Comment by ling1726** [comment]
No I'm talking about the windows hosts file, I'll update the issue to reflect that

**Comment by benhillis** [comment]
@ling1726 - I'm not sure I understand then, is something modifying your Windows hosts file?

**Comment by ling1726** [comment]
@benhillis sorry I might not have explained very well.

If I try to map a custom domain to localhost where the localhost server is being run from WSL as described in https://github.com/microsoft/WSL/issues/5728#issuecomment-675473289, I will get DNS errors trying to connect to that custom domain in windows unless I keep updating the windows hosts file regularly.

**Comment by ling1726** [comment]
Another update: this no longer occurs if I map my custom domain to 127.0.0.1 too, but from what I understand in #5728, WSL can't resolve IPv4 addresses

```
127.0.0.1 local.teams.office.com
::1 local.teams.office.com
```
