### ISSUE TITLE
Got process exited with code 3221225786 when running `wsl.exe --update`

### ISSUE THREAD

**Issue by einarpersson** [microsoft/WSL#9718]
### Version

WSL version: 1.1.3.0 Kernel version: 5.15.90.1 WSLg version: 1.0.49 MSRDC version: 1.2.3770 Direct3D version: 1.608.2-61064218 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19044.2604

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. I opened my Ubuntu distro
2. A message greeted me: `A new WSL update is available. It can be installed by running: wsl.exe --update`
3. I followed the instruction and ran the above command `wsl.exe --update`
4. I got an error (see Actual behaviour below)

### Expected Behavior

I except the update to not give any error messages. I just followed the instruction given to me, so I cannot see what I did wrong here. Should I have run it in Powershell instead? (if so, it should be stated clearly)

**Note:** It might be the case that the version info above is _after_ the update and I do not know what it was before. But I use WSL2 daily and this was the first time I saw the prompt to update.

### Actual Behavior

```
A new WSL update is available. It can be installed by running: wsl.exe --update
einar@x13:~$ wsl.exe --update
Checking for updates.
Updating Windows Subsystem for Linux..
[process exited with code 3221225786 (0xc000013a)]
```

**Comment by benhillis** [comment]
Interesting, you shouldn't be seeing that error. That means that the wsl.exe process has been terminated by the app platform which because the package has been updated.

**Comment by rshurts** [comment]
Does wsl still work or are you experiencing something similar to me as I reported in https://github.com/microsoft/WSL/issues/9720?

**Comment by kikohs** [comment]
Manage to get back, by rebooting. Trying to launch WSL which was hanging. Did `wsl --shutdown` then `wsl --update``, now it seems to work again.

**Comment by einarpersson** [comment]
It worked fine yesterday, but today when starting `vscode` wsl crashed in all terminals and now won't start.

```
An existing connection was forcibly closed by the remote host.
Error code: Wsl/Service/0x80072746

[process exited with code 4294967295 (0xffffffff)]
```

Help?

**Comment by raul-potor** [comment]
I can confirm this is happening to me as well. Yesterday everything worked fine, but now I cannot start `vscode` form the terminal and I get the same error when I try to update WSL

**Comment by einarpersson** [comment]
> I can confirm this is happening to me as well. Yesterday everything worked fine, but now I cannot start `vscode` form the terminal and I get the same error when I try to update WSL

Did you try exiting all WSL instances, and run `wsl --shutdown` in Powershell?

It began working for me after that (at least so far...)

**Comment by raul-potor** [comment]
> > I can confirm this is happening to me as well. Yesterday everything worked fine, but now I cannot start `vscode` form the terminal and I get the same error when I try to update WSL
> 
> Did you try exiting all WSL instances, and run `wsl --shutdown` in Powershell?
> 
> It began working for me after that (at least so far...)

It didn't work until I went into Services and did a manual restart for `LxssManager`. So, it was probably the same thing :)

**Comment by benhillis** [comment]
I'll take a look at the `wsl.exe --update` error.

For the `An existing connection was forcibly closed ` issue, I'd encourage people to post a new issue so it does not get lost.

**Comment by einarpersson** [comment]
> I'll take a look at the `wsl.exe --update` error.
> 
> For the `An existing connection was forcibly closed ` issue, I'd encourage people to post a new issue so it does not get lost.

Well, the thing is that it appeared after `wsl.exe --update` error (I had never seen it before)
