### ISSUE TITLE
Having a bit of an issue using wsl --set-version

### ISSUE THREAD

**Issue by Aeplexi** [microsoft/WSL#9724]
When I run the command, instead of doing anything AT ALL, it just prints out the other commands like this. Whys this?

![image](https://user-images.githubusercontent.com/86505664/222455489-ee97da60-1828-461b-8af7-610d4fcebed3.png)

**Comment by Biswa96** [comment]
Please fill up the issue template. It will help us to know more about your current environment.

**Comment by Aeplexi** [comment]
> Please fill up the issue template. It will help us to know more about your current environment.

What issue template?

**Comment by Biswa96** [comment]
Try to create an issue but do not create it. You'll see a form in the text box.

**Comment by Aeplexi** [comment]
> Try to create an issue but do not create it. You'll see a form in the text box. 

Ion have a bug w WSL im just trying to figure out whats the issue here

**Comment by sinyuryuu** [comment]
Your WSL version is too old (like Windows Server 2019)
This command is not supported
