### ISSUE TITLE
wsl 1.1.3 is very slow 

### ISSUE THREAD

**Issue by tutcugil** [microsoft/WSL#9725]
### Windows Version

Microsoft Windows Server 2022 [Version 10.0.20348.1547]

### WSL Version

1.1.3

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

docker-desktop-data

### Other Software

Docker Desktop v4.17.0

### Repro Steps

I was previously using wsl v1.0.3 and updated it to v1.1.3 today, and my applications response times very slowed, i downgraded to v1.0.3 and my applications runs fast again

### Expected Behavior

Application run and response performance same as previous wsl version

### Actual Behavior

Applications are running slower on v1.1.3

**Comment by tutcugil** [comment]
Especially HTTP requests seem to be too slow compared to v1.0.3, i think it is networking latency issue or something in wsl 1.1.3

**Comment by tutcugil** [comment]
I did some tests, when WSL v1.0.3 installed HTTP requests to my containered applications tooks ~100ms - 200ms, but when i update to WSL v1.1.3 same requests tooks ~1100ms - ~2600ms, it looks like there is a serious performance issue in the latest WSL version

**Comment by pmartincic** [comment]
@tutcugil,

Do you have repro examples? Sample app to run, etc.

**Comment by kysucix** [comment]
This is happening for me as well, do you have any clue what's going on?

**Comment by tutcugil** [comment]
@pmartincic 

I am using simple .NET 7 API microservice application (which have JWT operations, DB connection, etc) in docker,
under nginx proxy 

If i can program a simple app for repro it, i will inform you

**Comment by tutcugil** [comment]
Hello @pmartincic 

I created a very simple .net web api project with one controller you can find repo link [here](https://github.com/tutcugil/wsl-diagnostic) to reproduce the performance issue

When i run this project into docker (v4.17.0) with wsl 1.0.3 installed on my machine it tooks like ~90-100ms
But when i run this project into with wsl 1.1.3 installed on my machine it tooks about ~800-900ms

It shows the new release of WSL (1.1.3) has performance issue

Best Regards

**Comment by pmartincic** [comment]
@tutcugil, super thanks! I'll have a look this coming week.

**Comment by romabysen** [comment]
Yes, I have the same problem. Networking WSL2 is super slow now but it was fine previously.

**Comment by benhillis** [comment]
@romabysen - I've tried both 1.0.3 and 1.1.3 and am not seeing any noticeable difference between the network speed of the wget operations.

**Comment by romabysen** [comment]
Yes, it has since fixed itself. I have no idea why it was that bad or how it fixed itself.

**Comment by pmartincic** [comment]
Hey @tutcugil.

I'm sorry but I've gotten pulled elsewhere for the time being. I really appreciate you taking the time to put together a self contained repro. That doesn't happen very often. I was the in middle of figuring out how to deploy/run it when I got pulled off. I don't typically work on those kinds of apps. I thought I'd posted on here last week but apparently I hadn't.

**Comment by tutcugil** [comment]
> Hey @tutcugil.
> 
> 
> 
> I'm sorry but I've gotten pulled elsewhere for the time being. I really appreciate you taking the time to put together a self contained repro. That doesn't happen very often. I was the in middle of figuring out how to deploy/run it when I got pulled off. I don't typically work on those kinds of apps. I thought I'd posted on here last week but apparently I hadn't.

Hi @pmartincic, just open the project with visual studio 2022 and choose run target Docker and run it, or you can use Dockerfile inside of the repo to build and run it on docker

Regards

**Comment by tutcugil** [comment]
Hi @pmartincic, @benhillis the issue seemed to resolved on v1.1.5 but re-appeared on v1.1.6 pre release, fyi

Is there any update on this,
Regards
