### ISSUE TITLE
GNU make support

### ISSUE THREAD

**Issue by creeve4** [Microsoft/WSL#973]
Is [GNU make](https://www.gnu.org/software/make/) supported? I have attempted several times to use this command, but it merely hangs and never starts the compiling process.

I am running the Anniversary Update, v14393.51

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, can please you share out repro steps and an strace of the hang?  Many folks have had success with make, but it may be invoking another tool that is causing the hang.

**Comment by fpqc** [comment]
@creeve4 Make is supported. What are you trying to compile?  I've compiled plenty of stuff with make on WSL.

**Comment by creeve4** [comment]
I am attempting to compile Android source code.

Steps to produce:
1. Download the Repo tool and ensure that it is executable:
```
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
```
2. Initialize the repo
`repo init -u https://android.googlesource.com/platform/manifest -b android-6.0.1_r60`
3. Sync the repo
`repo sync`
4. Setup the build enviroment
`. build/envsetup.sh`
5. Choose a target
`lunch 19`
6. Start the build 
`make`

Attached is the trace.
[trace.txt](https://github.com/Microsoft/BashOnWindows/files/433328/trace.txt)

**Comment by creeve4** [comment]
I am not able to determine what is causing make to halt, any ideas?

**Comment by benhillis** [comment]
Much has changed since August 2016, I suspect this is now fixed.  Please reopen if you continue to have issues.
