### ISSUE TITLE
WSLG Not Running

### ISSUE THREAD

**Issue by thheil** [microsoft/WSL#9735]
### Windows Version

Microsoft Windows [Version 10.0.22621.1265]

### WSL Version

Updated2/20/23

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-22.04

### Other Software

None

### Repro Steps

Problem occurs immediately upon fresh boot and opening Ubuntu shell.

### Expected Behavior

WSLG should be running There should be a /mnt/wslg directory.  X-windows apps should run.

### Actual Behavior

WSLG seems to be not running at all.  There is no /mnt/wslg directory, so no logs.  

Under the WSL distro, XWindows apps will not connect to :0

thheil@grey_lenovo ~ % export DISPLAY=:0
thheil@grey_lenovo ~ % xeyes
Error: Can't open display: :0

There is no .wslconfig file.   wsl.conf is as follows:

thheil@grey_lenovo ~ % cat /etc/wsl.conf
[boot]
systemd=true

If I run wslg.exe from PowerShell, it returns without any response.

`PS C:\Users\thhei> wslg
PS C:\Users\thhei> wslg --help
PS C:\Users\thhei> wslg --version
PS C:\Users\thhei>

Are there logs I can collect?

**Comment by benhillis** [comment]
WSLg is only supported on the packaged version of WSL. Could you run `wsl.exe --update` to make sure that's what you're using?
