### ISSUE TITLE
`wsl --mount` not working (both --bare and --partition fail), "The request is not supported."

### ISSUE THREAD

**Issue by FreezyLemon** [microsoft/WSL#9739]
### Windows Version

Microsoft Windows [Version 10.0.22621.1344]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

openSUSE Tumbleweed

### Repro Steps

I'm following [these](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk) steps to try and mount my SSD inside WSL. In an elevated PowerShell session:

```
PS C:\Users\user> GET-CimInstance -query "SELECT * from Win32_DiskDrive"

DeviceID           Caption                   Partitions Size          Model
--------           -------                   ---------- ----          -----
\\.\PHYSICALDRIVE1 WDC WD40EZAZ-00SF3B0      1          4000784417280 WDC WD40EZAZ-00SF3B0
\\.\PHYSICALDRIVE2 Samsung SSD 970 EVO 1TB   3          1000202273280 Samsung SSD 970 EVO 1TB
\\.\PHYSICALDRIVE0 Samsung SSD 850 EVO 250GB 3          250056737280  Samsung SSD 850 EVO 250GB

PS C:\Users\user> wsl --mount \\.\PHYSICALDRIVE2 --bare
```

(Note: Manually selecting a partition with --partition X results in the same error)

### Expected Behavior

The `wsl --mount` command succeeds and I can access the drive from within WSL.

### Actual Behavior

```
PS C:\Users\user> wsl --mount \\.\PHYSICALDRIVE2 --bare
The request is not supported.
Error code: Wsl/Service/AttachDisk/0x80070032
```

`lsblk` and `fdisk -l` from within WSL do not show the disk.

### Diagnostic Logs

Since the issue is about `wsl --mount`, here is the additional diagnostic output:

```
PS C:\Users\user> wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType              Model                      Name                Partitions
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE1  IDE            TRUE         Fixed hard disk media  WDC WD40EZAZ-00SF3B0       \\.\PHYSICALDRIVE1  1
              {3, 4}        {"Random Access", "Supports Writing"}                        \\.\PHYSICALDRIVE2  SCSI           TRUE         Fixed hard disk media  Samsung SSD 970 EVO 1TB    \\.\PHYSICALDRIVE2  3
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media  Samsung SSD 850 EVO 250GB  \\.\PHYSICALDRIVE0  3
```

if you need more info, let me know.

**Comment by FreezyLemon** [comment]
[WslLogs-2023-03-08_17-59-40.zip](https://github.com/microsoft/WSL/files/10923075/WslLogs-2023-03-08_17-59-40.zip)

**Comment by badde-media** [comment]
I have the same problem trying to mount an EXT4 partition on an external USB HD with several partitions on WSL Ubuntu. Same error message. Any news?
