### ISSUE TITLE
Whole disk mounted when using --partition option

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9740]
### Windows Version

Microsoft Windows [Version 10.0.19045.2604]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Repro Steps

Mount some disk partition.

### Expected Behavior

Only partition to be mounted not whole disk.

### Actual Behavior

```
PS C:\Users\elsaco> wsl --mount \\.\PHYSICALDRIVE0 --partition 7
The disk was successfully mounted as '/mnt/wsl/PHYSICALDRIVE0p7'.
Note: The location will be different if you have modified the automount.root setting in /etc/wsl.conf.
To unmount and detach the disk, run 'wsl.exe --unmount \\.\PHYSICALDRIVE0'.
```

The whole drive is being mounted instead of partition 7 only.

Disk view from within WSL distro:

```
elsaco@RIPPER:~$ sudo !!
sudo parted /dev/sdb print
Model: NVMe Samsung SSD 970 (scsi)
Disk /dev/sdb: 1000GB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt
Disk Flags:

Number  Start   End     Size    File system     Name                  Flags
 1      1049kB  215GB   215GB   btrfs           Linux filesystem
 2      215GB   249GB   34.4GB  linux-swap(v1)  Linux swap            swap
 3      249GB   464GB   215GB                   Linux filesystem
 4      464GB   679GB   215GB   btrfs
 5      679GB   762GB   83.9GB
 6      762GB   972GB   210GB   ntfs            Basic data partition  msftdata
 7      972GB   1000GB  28.0GB  ext4            Linux filesystem
```

**Comment by kungFuLambda** [comment]
I am running into the same issue. 

When trying to mount only an ext4 partition of a disk, the whole disk mounts. 

I also tried with --bare and -f ext4. 

Logs as extracted from the instructions above: 
[WslLogs-2024-09-07_14-23-55.zip](https://github.com/user-attachments/files/16918386/WslLogs-2024-09-07_14-23-55.zip)
