### ISSUE TITLE
WSL Hanging/not starting

### ISSUE THREAD

**Issue by Ragarnoy** [microsoft/WSL#9747]
### Windows Version

Microsoft Windows [version 10.0.22623.1325]

### WSL Version

wont print

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

20.04

### Repro Steps

- Starting WSL

### Expected Behavior

Should start WSL

### Actual Behavior

WSL Hangs, the terminal is completely empty

### Diagnostic Logs

[WslLogs-2023-03-06_20-58-45.zip](https://github.com/microsoft/WSL/files/10902378/WslLogs-2023-03-06_20-58-45.zip)

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @Ragarnoy,

I have the same problem here since this morning, WSL is hanging and not starting.
Do you have any clue ? Maybe updating our Windows System ?

Yours faithfully,
LCDP

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Everything seems to work back now

**Comment by Ragarnoy** [comment]
Somehow, today, for no particular reason it started working again after several days of it not working?!..
