### ISSUE TITLE
OpenGL inside WSL different than my Windows

### ISSUE THREAD

**Issue by tsugg** [microsoft/WSL#9753]
### Windows Version

Microsoft Windows [Version 10.0.22000.1574]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

I have the latest NVIDIA game ready driver for my graphics card.

### Repro Steps

glxinfo | grep "OpenGL version"

### Expected Behavior

My NVIDIA drivers for my 3090ti show an OpenGL version of 4.6

![image](https://user-images.githubusercontent.com/48035539/223485729-3a8da422-a8e9-4f95-9279-71407b253ab7.png)

### Actual Behavior

glxinfo | grep "OpenGL version"
OpenGL version string: 4.2 (Compatibility Profile)

When I look on WSL, it's showing an OpenGL version of 4.2. The task I'm working on requires at least 4.4. I thought the graphics driver decides what OpenGL version you are on. So why would my WSL have a mismatch?

**Comment by elsaco** [comment]
@tsugg OpenGL in WSL distros is proved by `mesa` that's why the OpenGL version inside Ubuntu is different than on Windows side. Unfortunately we can't install Nvidia drivers inside WSL.

**Comment by elsaco** [comment]
Quick update: Mesa 22.3.6 was released on 2/22/23 and `Mesa 22.3.6 implements the OpenGL 4.6 API`. Building it might solve your OpenGL requirements on WSL side.

See more details at https://docs.mesa3d.org/relnotes/22.3.6.html

**Comment by RobertSpir** [comment]
Mesa in WSL is using the [https://docs.mesa3d.org/drivers/d3d12.html](d3d12) driver which supports only OpenGL 4.2. If you need higher OpenGL, you can use software llvmpipe driver which supports OpenGL 4.5.
using d3d12 driver:
```
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA Quadro P400) (0xffffffff)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 67478MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA Quadro P400)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
and now forcing software rendering:
```
LIBGL_ALWAYS_SOFTWARE=true glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 12.0.0, 256 bits) (0xffffffff)
    Version: 21.2.6
    Accelerated: no
    Video memory: 64301MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by tsugg** [comment]
Thank you both for the great responses. I have it working!
