### ISSUE TITLE
Cannot spawn a message bus without a machine-id

### ISSUE THREAD

**Issue by blacksnow-2** [microsoft/WSL#9754]
### Windows Version

Microsoft Windows [Version 10.0.22621.1344]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-22.04

### Repro Steps

1) Enabled optional feature Windows Subsystem for Linux. Installed Windows Subsystem for Linux Update - 5.10.102.2 and Windows Subsystem for Linux WSLg Preview - 1.0.27 from Windows Updates.
2) Opened Powershell 7 in administrator mode and ran 

>wsl --install -d  Ubuntu-22.04 
3) It ran successfully. Account creation was also successful.
4) Then ran the following commands in order

> sudo apt-get update
Successful. Screenshot of every command attached.
![Screenshot (8)](https://user-images.githubusercontent.com/127113949/223474220-efe7cf5d-86e3-44ab-b715-998c947d4810.png)

>  sudo apt-get upgrade
![Screenshot (7)](https://user-images.githubusercontent.com/127113949/223474390-c517e9b6-b294-471d-a32b-fb56ccddca75.png)

> sudo apt install nautilus
![Screenshot (6)](https://user-images.githubusercontent.com/127113949/223474586-8ed58f69-e682-4f0e-b6ff-2498f75ee8ed.png)

![Screenshot (5)](https://user-images.githubusercontent.com/127113949/223477747-bfcbcaea-14cf-4bab-bbb4-3cbe05da1363.png)

> nautilus
       

      Then

> Exit the app by clicking close icon at extreme top right.

### Expected Behavior

No error messages at all while performing the above operations.

### Actual Behavior

![Screenshot (4)](https://user-images.githubusercontent.com/127113949/223477842-a992dcdd-99b8-40b8-bc3d-89c2b9809163.png)

And then as per the attached screenshot , with every click in the nautilus app the error messages come. Even while clicking the exit icon , error messages came as per the title of the issue. 

 I want to know why is this issue coming and what should be my approach while on terminal to get rid of this. My primary reason to install WSL is to use terminal for bash shell scripting. Will there be any problem?

### Diagnostic Logs

[WslLogs-2023-03-07_21-04-42.zip](https://github.com/microsoft/WSL/files/10911773/WslLogs-2023-03-07_21-04-42.zip)

**Comment by elsaco** [comment]
@blacksnow-2 make sure `tracker` is running. What is the output of `tracker3 daemon --list-processes`? 
It should look like:

```
elsaco@RIPPER:~$ tracker3 daemon --list-processes
Found 1 PID…
Found process ID 428 for “tracker-miner-fs-3”
```

and if you check the service:

```
elsaco@RIPPER:~$ systemctl --user status tracker-miner-fs-3
● tracker-miner-fs-3.service - Tracker file system data miner
     Loaded: loaded (/usr/lib/systemd/user/tracker-miner-fs-3.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-03-07 13:57:27 PST; 8min ago
   Main PID: 428 (tracker-miner-f)
     CGroup: /user.slice/user-1000.slice/user@1000.service/background.slice/tracker-miner-fs-3.service
             └─428 /usr/libexec/tracker-miner-fs-3

Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ig>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &MUSIC. Ignori>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &PICTURES. Ign>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &VIDEOS. Ignor>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &DOWNLOAD. Ign>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &DOCUMENTS. Ig>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &MUSIC. Ignori>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &PICTURES. Ign>
Mar 07 13:57:26 RIPPER tracker-miner-f[428]: Unable to get XDG user directory path for special directory &VIDEOS. Ignor>
Mar 07 13:57:27 RIPPER systemd[400]: Started Tracker file system data miner.

```

If tracker is running you might still see warnings on the console when starting nautilus, like:

```
elsaco@RIPPER:~$ nautilus

** (org.gnome.Nautilus:509): WARNING **: 14:02:27.965: Unable to get contents of the bookmarks file: Error opening file /home/elsaco/.gtk-bookmarks: No such file or directory

** (org.gnome.Nautilus:509): WARNING **: 14:02:27.966: Unable to get contents of the bookmarks file: Error opening file /home/elsaco/.gtk-bookmarks: No such file or directory

```
Create necessary file for the warnings to go away or start nautilus from the Windows `Start` menu and there will be no messages on the console from the app.

**Comment by blacksnow-2** [comment]
@elsaco The output of the command 

> tracker3 daemon --list-processes

                      was
<img width="860" alt="Screenshot 2023-03-08 075037" src="https://user-images.githubusercontent.com/127113949/223603053-24aba537-bbd9-40f0-8c02-e5319bc13c60.png">

So I tried to start tracker-miner but it could not be started agin due to the same error, as in the screenshot below

<img width="863" alt="Screenshot 2023-03-08 075348" src="https://user-images.githubusercontent.com/127113949/223603447-9aa9b9bb-edd2-4d20-81f7-d9cac6230c0b.png">


Also, nautilus is not present in the Windows start menu also.

**Comment by elsaco** [comment]
@blacksnow-2 you'll need `systemd` enabled and if the `machine-id` is bad or missing run `systemd-machine-id-setup` to regenerate it. There should be a unique machine ID stored in `/etc/machine-id`. Is there any output if you run `systemd-machine-id-setup --print`?

 Sample output:

```
elsaco@RIPPER:~$ systemd-machine-id-setup --print
49a9b526faca4432ad94e64ccc707008
```

which is also the content of `/etc/machine-id`

Also, make sure `systemctl --user` works. Here's output with tracker service status:

```
elsaco@RIPPER:~$ systemctl --user status
● RIPPER
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Tue 2023-03-07 18:56:26 PST; 11min ago
   CGroup: /user.slice/user-1000.slice/user@1000.service
           ├─background.slice
           │ └─tracker-miner-fs-3.service
           │   └─424 /usr/libexec/tracker-miner-fs-3
           ├─app.slice
           │ ├─gvfs-goa-volume-monitor.service
           │ │ └─434 /usr/libexec/gvfs-goa-volume-monitor
           │ ├─gvfs-daemon.service
           │ │ └─416 /usr/libexec/gvfsd
           │ ├─gvfs-udisks2-volume-monitor.service
           │ │ └─429 /usr/libexec/gvfs-udisks2-volume-monitor
           │ ├─gvfs-gphoto2-volume-monitor.service
           │ │ └─443 /usr/libexec/gvfs-gphoto2-volume-monitor
           │ ├─dbus.service
           │ │ └─413 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --sysl>
           │ ├─gvfs-mtp-volume-monitor.service
           │ │ └─447 /usr/libexec/gvfs-mtp-volume-monitor
           │ └─gvfs-afc-volume-monitor.service
           │   └─438 /usr/libexec/gvfs-afc-volume-monitor
           └─init.scope
             ├─396 /lib/systemd/systemd --user
             └─397 (sd-pam)
```

**Comment by blacksnow-2** [comment]
@elsaco 
Here's what I did :-
1. Enabled systemd as given in the link   https://www.xda-developers.com/how-enable-systemd-in-wsl/  . Rebooted the distro.  Also checked that it was running also.
2. Ran

> sudo systemd-machine-id-setup
3. Then checked the above step by running 

> systemd-machine-id-setup --print

and

> cat /etc/machine-id

Both gave the same output which meant the operation was successful. Also I tried to open nautilus, which gave the warnings only (no critical error messages) , again which were present in your terminal also. So thanks a lot for it. But it is still not present in the Windows start menu.

But the second part of your comment , i.e. of running the command `systemctl --user status` and along with sudo before it, both are running into problems of bus. The screenshot below shows them all. 
<img width="857" alt="Screenshot 2023-03-08 113700" src="https://user-images.githubusercontent.com/127113949/223632787-7db78614-00c3-40c6-a9b7-8c9d40576b2e.png">

**Comment by zcobol** [comment]
@blacksnow-2 look for `Files` under `Ubuntu-22.04` in the Windows `Start` menu.

**Comment by blacksnow-2** [comment]
Thanks @zcobol for pointing it out. There is a separate app installed named Files (Ubuntu-22.04) which opens the nautilus app.
