### ISSUE TITLE
Services running in WSL 2 no longer accessible from Windows

### ISSUE THREAD

**Issue by Trey96** [microsoft/WSL#9760]
### Discussed in https://github.com/microsoft/WSL/discussions/9744

<div type='discussions-op-text'>

<sup>Originally posted by **Trey96** March  6, 2023</sup>
Not sure if anyone else is having this problem, but I searched and wasn't able to find anything related to my issue. It seems like the WSL localhost is no longer being shared with the Windows localhost, and I cannot access WSL services from Windows via localhost.

I am running multiple domains on Nginx inside of WSL 2. In my Windows hosts file I am pointing all of those domains to 127.0.0.1. Until recently that was working just fine. However it has stopped working completely, and when I try to connect to the domain from the browser (Chrome) I get a connection refused error. Further investigation reveals there are no ports listening on 80 for 127.0.0.1, in fact nothing appears to be active on 127.0.0.1 anymore, especially WSL which used to be active. It seems WSL 2 has stopped binding to localhost but I am not sure why.

```
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
Windows version: 10.0.22621.1344 (Windows 11)
Distro: Ubuntu 20.04
```

I recently installed Docker on my computer which runs on WSL. So I am not sure if that might have caused problems. Though I have since uninstalled Docker, but it had not affect. I am not sure if this is a bug with WSL or something I am doing wrong. 

Any help identifying what might be the problem or any pointers on how to resolve it (or troubleshoot further) is much appreciated!</div>

#### Log Files (Updated 3/21/2023):
[WslLogs-2023-03-21_23-12-21.zip](https://github.com/microsoft/WSL/files/11035840/WslLogs-2023-03-21_23-12-21.zip)

**Comment by pmartincic** [comment]
Please use the issue template going forward. Please provide the output of `ss -lntp` on the guest(wsl), and `netstat -an | findstr /c:"80" | findstr /c:"LISTENING"` on the host(windows)

**Comment by Trey96** [comment]
@pmartincic, thanks for the quick reply!

The following is the command output:


`ss -lntp` (WSL)

![image](https://user-images.githubusercontent.com/60182680/223878438-8fb3c9bd-b004-4ea4-86d0-1819228fe23f.png)

`netstat -an | findstr /c:"80" | findstr /c:"LISTENING"` (Windows)

![image](https://user-images.githubusercontent.com/60182680/223878532-a3d2fe11-aaad-4537-ae3b-2ab9b37d3241.png)

**Comment by pmartincic** [comment]
Can you provide /logs? 

1. `wsl --shutdown`
2. then start collecting logs
3.  Check that it's broken
4.  Stop the log collection

Smoke test on my VM seems ok?
<img width="971" alt="image" src="https://user-images.githubusercontent.com/102559858/223878828-35cf5fac-d7ea-4634-bfb6-6ed48dd20296.png">

**Comment by Chan0081** [comment]
Got a similar problem.
I've started a grpc service in wsl2, and I can access it from wsl inside. But LAN computors can't access it even after I configured port-forwarding by:
`netsh interface portproxy add v4tov4 listenport=50066 listenaddress=0.0.0.0 connectport=50066 connectaddress=192.168.79.196`
The error says:
`UNAVAILABLE: Network closed for unknown reason`

**Comment by jjz921024** [comment]
hi，I had the same problem，can't connect to grpc server written by golang running WSL2, but it fine running windows.
how can I solve it？

**Comment by sec** [comment]
Hi,
As a check/workaround try to disable IPv6 on your local LAN/WiFi card/connection - works for me at least.

**Comment by pmartincic** [comment]
I'm sorry, I've gotten routed elsewhere and won't be able to look into this for the time being.

**Comment by sec** [comment]
@pmartincic 
This seems to be issue for a lot of people - in the end, this render WSL useless in high load scenarios...

**Comment by pmartincic** [comment]
@sec, I agree with you. Unfortunately I've gotten routed elsewhere. Your logs have something interesting in them, won't be able to look much right now.

@trey9
Looks like log collection started roughly half a minute after you started the VM. Whatever I'm looking for is probably in that half minute before you started collecting logs.

wsl --shutdown
then start collecting logs
Check that it's broken
Stop the log collection

**Comment by Trey96** [comment]
@pmartincic 

I apologize about that, not sure how that happened. But I uploaded the updated logs - Let me know if there is anything else you need

**Comment by cmendible** [comment]
`az login` redirect fails with 1.1.3, 1.1.5, 1.1.6 & 1.1.7

Had to rollback to 1.0.3

WSL version: 1.1.7.0
Kernel version: 6.1.21.1-1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.23424.1000

**Comment by Trey96** [comment]
Seems to be working for me now, after updating

```
 Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    198      32     3364      10176       0.19  18008   3 wslrelay
```

```
netstat -an | findstr /c:"80" | findstr /c:"LISTENING"

  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:8090           0.0.0.0:0              LISTENING
  TCP    127.0.0.1:80           0.0.0.0:0              LISTENING
  TCP    [::]:7680              [::]:0                 LISTENING
```

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1635
```

**Comment by pmartincic** [comment]
Thanks @Trey96 for the update.

The fix was in 1.2.1

**Comment by sec** [comment]
Hi.
@pmartincic  Sorry but this was not fixed. It's still an issue even after recent update to `2.0.9.0`.
Network is crashing under high load and the only solution is to restart WSL2, but then again, when docker containers are run and accessed from Windows host, network will be down again.

**Comment by sec** [comment]
@pmartincic I have created sample code to repro this issue - https://github.com/sec/wsl-network-crash-test - should I open new issue or can we reopen this one, as it's still the same issue?

**Comment by Tacx79** [comment]
Same issue here, API running on wsl2, app running on windows. It worked for a few months, windows system crashed and after restart it doesn't work anymore, throws ERR_CONNECTION_REFUSED instead.
