### ISSUE TITLE
Documentation about how to publish your WSL image on Microsoft Store

### ISSUE THREAD

**Issue by D3vil0p3r** [microsoft/WSL#9761]
**Is your feature request related to a problem? Please describe.**
I have a Microsoft developer account for developing apps, games and Edge resources but in the Dashboard I don't see any content related to the publishing of a WSL image to the Microsoft Store.

**Describe the solution you'd like**
It could be very useful if a documentation could describe how to publish to Microsoft Store a WSL image (for example a Linux distribution).

**Comment by pmartincic** [comment]
Please file documentation bugs here: https://github.com/MicrosoftDocs/WSL
