### ISSUE TITLE
WSL crashes and can't be restarted

### ISSUE THREAD

**Issue by traycerb** [microsoft/WSL#9767]
### Windows Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.15.90.1

### Distro Version

Ubuntu  default

### Repro Steps

This may be similar to https://github.com/microsoft/WSL/issues/7368, but I felt it was different to file another report.

After enough time (minutes or hours, usually following a period of inactivity), WSL crashes and can't be recovered.  issues manifests as existing terminals sessions stop responding, and new terminals opened just hang without any error message.   Rebooting solves the issue, until it happens again.  I am on a Thinkpad Yoga.

Logs are hard to capture, but I have attached one after WSL stopped responding  (removed my name and IP from obvious places within the logs, hope that won't cause an issue).

This was happening with prior versions and I was able to work around it by using the following command:
`tasklist /svc /fi "imagename eq svchost.exe" | findstr LxssManager
`
...and killing the associated process, but that no longer works after I updated WSL (no process named as such is found anymore).  I saw somewhere else mentioned trying `Restart-Service -name lxssmanager` and also no effect.

### Expected Behavior

No crashing, able to restart

### Actual Behavior

crashing, `vmmem` consuming >75% and can't be killed.  Signout doesn't solve problem, only reboot.

### Diagnostic Logs

[WslLogs-2023-03-03_13-30-56.zip](https://github.com/microsoft/WSL/files/10934981/WslLogs-2023-03-03_13-30-56.zip)

**Comment by jeffska** [comment]
Is it happening after the machine hibernates? If so, come join the party over at #8696 .

**Comment by FLAMESpl** [comment]
It happens to me too in middle of work without hibernating windows.

**Comment by hanzlahabib** [comment]
I was working and instantly it broke

**Comment by ileathan** [comment]
Same here, in the middle of workload. I love my wsl 1.

**Comment by FLAMESpl** [comment]
Ofc. we are still experiencing this, it has been inactive for the past year because noone from microsoft have responded to the damn thing.
