### ISSUE TITLE
WIN32 call from WSL break stdout

### ISSUE THREAD

**Issue by pwang2** [microsoft/WSL#9770]
### Windows Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

UBUNTU 22.04

### Repro Steps

See below: 

![image](https://user-images.githubusercontent.com/1592014/224226716-83fc3e30-d1d9-46be-9a45-fcd0d3d3314b.png)
Setting DISPLAY from window route table in zshenv.   

### Expected Behavior

system stdout to pipe

### Actual Behavior

system stdout removed

**Comment by OneBlue** [comment]
Thanks for reporting this @pwang2. Can you please share an strace of the command you're running ? I suspect that the issue is that `route.exe`  either doesn't output something that matches the grep pattern

**Comment by pwang2** [comment]
It does output something always.  But seems in an Async way.  As you can see the DISPLAY is setup properly as per my VPN interface IP here.   

Some background here: My VPN interface changes IP after reconnect which breaks my xclip to WSL in Neovim.  I was looking forward to fixing it by adding that to zshenv to  ensure every time neovim run system() get DISPLAY refreshed. Definitely something I should not do as it is pretty slow to run 'route print'.
