### ISSUE TITLE
Missing nat module for nftables

### ISSUE THREAD

**Issue by AxelVallon** [microsoft/WSL#9772]
### Windows Version

Microsoft Windows [version 10.0.22621.1265]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu

### Other Software

Docker 20.10.23
nftables (any version)

### Repro Steps

nft add table fw_nat
nft 'add chain fw_nat postrouting { type nat hook postrouting priority 100 ; }'
Error: Could not process rule: No Such file or directory

### Expected Behavior

Nat creation

### Actual Behavior

The nat modules is not compiled by default and is not available in /proc/modules

**Comment by elsaco** [comment]
@AxelVallon you might wanna update the kernel. `5.15.90.1-microsoft-standard-WSL2` has `NAT` enabled:

```
CONFIG_NF_NAT=y
CONFIG_NF_NAT_AMANDA=y
CONFIG_NF_NAT_FTP=y
CONFIG_NF_NAT_IRC=y
CONFIG_NF_NAT_SIP=y
CONFIG_NF_NAT_TFTP=y
CONFIG_NF_NAT_REDIRECT=y
CONFIG_NF_NAT_MASQUERADE=y
CONFIG_NFT_NAT=y
CONFIG_NETFILTER_XT_NAT=y
CONFIG_NF_NAT_PPTP=y
CONFIG_NF_NAT_H323=y
CONFIG_IP_NF_NAT=y
CONFIG_IP6_NF_NAT=y
```

This was tested on Ubuntu 22.04 but it should work on any distro:

```
elsaco@RIPPER:~/junk/temp$ sudo nft list table fw_nat
table ip fw_nat {
        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
        }
}

```

**Comment by XeonKHJ** [comment]
> @AxelVallon you might wanna update the kernel. `5.15.90.1-microsoft-standard-WSL2` has `NAT` enabled:
> 
> ```
> CONFIG_NF_NAT=y
> CONFIG_NF_NAT_AMANDA=y
> CONFIG_NF_NAT_FTP=y
> CONFIG_NF_NAT_IRC=y
> CONFIG_NF_NAT_SIP=y
> CONFIG_NF_NAT_TFTP=y
> CONFIG_NF_NAT_REDIRECT=y
> CONFIG_NF_NAT_MASQUERADE=y
> CONFIG_NFT_NAT=y
> CONFIG_NETFILTER_XT_NAT=y
> CONFIG_NF_NAT_PPTP=y
> CONFIG_NF_NAT_H323=y
> CONFIG_IP_NF_NAT=y
> CONFIG_IP6_NF_NAT=y
> ```
> 
> This was tested on Ubuntu 22.04 but it should work on any distro:
> 
> ```
> elsaco@RIPPER:~/junk/temp$ sudo nft list table fw_nat
> table ip fw_nat {
>         chain postrouting {
>                 type nat hook postrouting priority srcnat; policy accept;
>         }
> }
> ```

Can't find CONFIG_NFT_NAT=y.  nft nat is not working on my WSL2 instance. I have make sure NAT is enabled and the kernel version is `5.15.90.1-microsoft-standard-WSL.`. 
This is the output of my  `zgrep -i tables /proc/config.gz`
```
CONFIG_ACPI_LEGACY_TABLES_LOOKUP=y
CONFIG_IP_MULTIPLE_TABLES=y
# CONFIG_IPV6_MULTIPLE_TABLES is not set
CONFIG_NF_TABLES=y
CONFIG_NF_TABLES_INET=y
# CONFIG_NF_TABLES_NETDEV is not set
CONFIG_NETFILTER_XTABLES=y
# CONFIG_NETFILTER_XTABLES_COMPAT is not set
# Xtables combined modules
# Xtables targets
# Xtables matches
CONFIG_NF_TABLES_IPV4=y
# CONFIG_NF_TABLES_ARP is not set
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_ARPTABLES=y
CONFIG_NF_TABLES_IPV6=y
CONFIG_IP6_NF_IPTABLES=y
# CONFIG_NF_TABLES_BRIDGE is not set
# CONFIG_BRIDGE_NF_EBTABLES is not set
```
