### ISSUE TITLE
WLS/distributions/validate.py - line 43 of master branch: incomplete charset

### ISSUE THREAD

**Issue by theGASK** [microsoft/WSL#9777]
Current Master Branch

```python
    publisher_hash = hashlib.sha256(identity.attrib['Publisher'].encode('utf-16le')).digest()[:8]
    encoded_string = ''.join(['{0:b}'.format(e).rjust(8, '0') for e in publisher_hash] + ['0'])
    encoded_hash = ''
    charset = "0123456789abcdefghjkmnpqrstvwxyz"
    for i in range(0, len(encoded_string), 5):
        encoded_hash += charset[int(encoded_string[i:i + 5], 2)]
```

Suggested Change

```python
    publisher_hash = hashlib.sha256(identity.attrib['Publisher'].encode('utf-16le')).digest()[:8]
    encoded_string = ''.join(['{0:b}'.format(e).rjust(8, '0') for e in publisher_hash] + ['0'])
    encoded_hash = ''
    charset = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for i in range(0, len(encoded_string), 5):
        encoded_hash += charset[int(encoded_string[i:i + 5], 2)]
```

**Is your feature request related to a problem? Please describe.**
The code appears to be generating a hash for a publisher's identity, where the publisher's name is encoded using UTF-16LE and then hashed using the SHA-256 algorithm. The resulting hash is then encoded in a custom format using the charset defined in the code.

The charset used in the code is missing letters, which may be intentional or unintentional. This means, for example, that if the encoded hash contains the letter 'i', it will not be included in the final output. Instead, the output will be truncated at the position of the letter 'i', resulting in a shorter encoded hash.

**Describe the solution you'd like**
The suggested change adds the missing letters to the charset used for encoding the hash. This makes the charset complete and ensures that all possible values are accounted for. The new charset includes all 26 uppercase and lowercase letters of the English alphabet, as well as the 10 Arabic numerals (0-9). 

This change reduces the risk of collisions in the hash function and improves the reliability of the system that uses this code.

**Describe alternatives you've considered**
An alternative solution would be to use a standardized encoding scheme, such as Base64 or hexadecimal, instead of a custom charset. This would ensure that all possible values are accounted for and eliminate the risk of collisions due to missing characters in the encoding scheme.

For example:

```python
import hashlib
import base64

publisher_hash = hashlib.sha256(identity.attrib['Publisher'].encode('utf-16le')).digest()[:8]
encoded_hash = base64.urlsafe_b64encode(publisher_hash).decode('utf-8')
```

**Additional context**
This can lead to collisions in the hash function, where different publisher identities may end up with the same encoded hash due to the truncation of the output.

**Comment by benhillis** [comment]
If I recall, this had to be done to match what is done by the store / app platform for hashing package family names (which we cannot change).

**Comment by OneBlue** [comment]
Yes, this is by design. We need to generate the encoded hash the same way that Windows does to validate that it's correct. You can find more details here: https://marcinotorowski.com/2021/12/19/calculating-hash-part-of-msix-package-family-name/
