### ISSUE TITLE
wsl.exe --update failed with error: 0x80070422

### ISSUE THREAD

**Issue by nmoa** [microsoft/WSL#9781]
### Windows Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

I cannot check because wsl.exe fails with an error.

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

I cannot check.

### Repro Steps

1. I ran `wsl.exe --update` with both WSL1 and WSL2 running.
2. `wsl.exe --update` failed with error code `0x80070422`. (I'm sorry, but I missed the error message.)
3. After the update failed, WSL failed to boot with the following message.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070422
Error: 0x80070422 ?????????????????????????????????????????????????

Press any key to continue...
```

### Expected Behavior

- `wsl.exe --update` should succeed.
- WSL should boot without errors.

### Actual Behavior

I got an error `0x80070422`, and WSL failed to boot.  
Is there any ways to recover WSL?

**Comment by nmoa** [comment]
[WslLogs-2023-03-14_07-19-46.zip](https://github.com/microsoft/WSL/files/10962389/WslLogs-2023-03-14_07-19-46.zip)

**Comment by benhillis** [comment]
Thanks for sharing the logs. It looks like you're on WSL 1.0.3. Could you try removing the WSL app and re-installing?

While looking through the code I did notice a change that can be made that would allow you to update your package even if the class registration is broken. I'll go ahead and make that now.

**Comment by nmoa** [comment]
Thank you for your response.
I removed the Ubuntu-20.04 App (which is WSL2). 
Then I went to Settings > Installed Apps > Windows Subsystem for Linux, and clicked "Repair", which seems to have repaired the issue. Now I can run `wsl.exe`.

**Comment by benhillis** [comment]
Good to hear, thanks.

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL/releases/tag/1.1.6

**Comment by KayCHENvip** [comment]
I have the same problem, but the solution is not working. my computer has vmware installed.
C:\Users\Cuser>wsl
无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
Error code: Wsl/0x80070422

**Comment by Haerbin23456** [comment]
> I have the same problem, but the solution is not working. my computer has vmware installed. C:\Users\Cuser>wsl 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。 Error code: Wsl/0x80070422

Same. What happened?

**Comment by Haerbin23456** [comment]
> I have the same problem, but the solution is not working. my computer has vmware installed. C:\Users\Cuser>wsl 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。 Error code: Wsl/0x80070422

我发现我是服务里面那个 wsl service 给禁用了，跟那个最新的 issue 里面说的一样，我打开之后就没事了

**Comment by mhui-po** [comment]
[WslLogs-2024-10-27_07-23-29.zip](https://github.com/user-attachments/files/17534324/WslLogs-2024-10-27_07-23-29.zip)
hi please check my logs
