### ISSUE TITLE
After Update to 1.15 get an timeout with Ubuntu

### ISSUE THREAD

**Issue by zackmuc** [microsoft/WSL#9793]
### Windows Version

Windows 10.0.25314.1010

### WSL Version

1.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Start it in Terminal I get:

Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT
Press any key to continue...

### Expected Behavior

Starting of Ubuntu

### Actual Behavior

Timeout:

Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT
Press any key to continue...

**Comment by BenokanDeepBlue** [comment]
Exactly the same issue here.
