### ISSUE TITLE
error code 0x8000ffff when try to install Ubuntu via WSL

### ISSUE THREAD

**Issue by Shuyan-Lu** [microsoft/WSL#9798]
Version
Microsoft Windows [Version 10.0.25174.1010]

WSL Version
 WSL 2
Kernel Version
unknown
`PS C:\WINDOWS\system32> wsl --statuswsl --status`
and I got output saying kernel not installed.
`PS C:\WINDOWS\system32> wsl.exe --update`
and it throws:
インストール中: Linux 用 Windows サブシステム
致命的なエラーです。

translation: Linux Windows Subsystem being installed. fatal error.

Distro Version
Ubuntu-22.04

Other Software
No response

Repro Steps
PS C:\WINDOWS\system32> wsl --list --online
インストールできる有効なディストリビューションの一覧を次に示します。
'wsl --install -d <Distro>' を使用してインストールします。

NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
OracleLinux_8_5                        Oracle Linux 8.5
OracleLinux_7_9                        Oracle Linux 7.9
SUSE-Linux-Enterprise-Server-15-SP4    SUSE Linux Enterprise Server 15 SP4
openSUSE-Leap-15.4                     openSUSE Leap 15.4
openSUSE-Tumbleweed                    openSUSE Tumbleweed
PS C:\WINDOWS\system32> wsl --install -d Ubuntu
インストール中: Ubuntu
インストール中にエラーが発生しました。ディストリビューション名: 'Ubuntu' エラー コード: 0x8000ffff
(translation: error during installation. Distribution name: Ubuntu. Error code: 0x8000ffff)

Expected Behavior
Ubuntu successfully installed 

Actual Behavior
It throw "Error code: 0x8000ffff"

Diagnostic Logs
[WslLogs-2023-03-16_18-44-34.zip](https://github.com/microsoft/WSL/files/10989492/WslLogs-2023-03-16_18-44-34.zip)

**Comment by Gitnear** [comment]
I had the same issue - Try to open ps without admin rights

**Comment by Shuyan-Lu** [comment]
Thank you @Gitnear! It works!

**Comment by Shuyan-Lu** [comment]
Issue solved

**Comment by KokilaSoumi** [comment]
> I had the same issue - Try to open ps without admin rights



> I had the same issue - Try to open ps without admin rights

Thanks, it helps!

**Comment by danielcardea** [comment]
Thank you @Gitnear 
Running the command in Powershell works. I tried Command prompt but had the same issue.

**Comment by firmanium** [comment]
Terima Kasih @Gitnear sudah seminggu bingung, tidak bisa install, akhirnya bisa. Matur Nuwun yo

**Comment by maxgira** [comment]
I had this issue on a Windows Server 2022 system, tried reinstalling WSL etc but simply running `wsl --update` is what solved the problem in the end.

**Comment by hosseinhashemi** [comment]
For Windows 10 Users:

1 - I enabled the virtualization in BIOS and Hyper-v in Windows Features.
2 - Installed the Windows Subsystem For Linux from Microsoft Store.
3 - Installed Ubuntu from Microsoft Store.

**Comment by joaoggtinoco** [comment]
> Tive esse problema em um sistema Windows Server 2022, tentei reinstalar o WSL etc., mas simplesmente executar `wsl --update`foi o que resolveu o problema no final.

Atualizar o WSL também foi minha solução.

**Comment by USSX-Hares** [comment]
Same problem here.
As I am connecting to the server via SSH, de-elevating to a non-admin user is not an option.

Logs attached.
```
PS C:\Users\***> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
PS C:\Users\***> Set-ExecutionPolicy Bypass -Scope Process -Force
PS C:\Users\***> .\collect-wsl-logs.ps1
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Log collection is running. Please reproduce the problem and once done press any key to save the logs.
Saving logs...
Logs saved in: C:\Users\***\WslLogs-2024-02-26_20-14-46.zip. Please attach that file to the GitHub issue.
```

[WslLogs-2024-02-26_20-14-46.zip](https://github.com/microsoft/WSL/files/14403761/WslLogs-2024-02-26_20-14-46.zip)

**Comment by ryanhossain9797** [comment]
> I had this issue on a Windows Server 2022 system, tried reinstalling WSL etc but simply running `wsl --update` is what solved the problem in the end.

Just reconfirming that running `wsl --update` fixed the issue on Windows Server 2022

**Comment by sanbeichahegongheguo** [comment]
> I had the same issue - Try to open ps without admin rights

It works for me. Thanks!

**Comment by adambaaron** [comment]
Catastrophic Failure

**Comment by susongliulong** [comment]
@USSX-Hares Hey, bro! I meet the same problem with you, but finally I solve this problem in another way ! try to follow this link where you can find ANOTHER WAY TO DOWNLOAD "wsl" rather than using horrible 'cmd' !
[install-manual](https://learn.microsoft.com/en-us/windows/wsl/install-manual)

**Comment by enkelmedia** [comment]
I got the same error, but after doing

```sh
wsl --update
``` 

And running the install command again it "just worked" 🎉
