### ISSUE TITLE
Running Linux executables using Windows python's "subprocess.check_output()" in WSL2 does not work

### ISSUE THREAD

**Issue by kerim371** [microsoft/WSL#9799]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Repro Steps

The task is to run Linux executables from Windows applications (python for example).
It is a reverse task from the one mentionned in [#6547](https://github.com/microsoft/WSL/issues/6547)

From Linux/wsl run Windows python with the command:
```
.\python.exe -c "import subprocess; subprocess.check_call(['nano', '--version'])"
```
The error `FileNotFoundError: [WinError 2] The system cannot find the file specified`.

### Expected Behavior

Print actual information about Linux nano version

### Actual Behavior

The error `FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Biswa96** [comment]
The correct command should be like the following

```
.\python.exe -c "import subprocess; subprocess.check_call(['nano', '--version'])"
```

**Comment by kerim371** [comment]
@Biswa96 thank you but the idea is to avoid using 'wsl.exe'.

Let's suppose we work with python package that is dedicated to use on Linux.
In the same time I would like to use it on Windows and all the stuff related to Linux could be solved by simply extending env variables with Linux. Like `os.environ["PATH"] += ";//wsl.localhost/Ubuntu/usr/bin";`

Then I expect `\python.exe -c "import subprocess; subprocess.check_call(['nano', '--version'])"` to work.
But unfortunately it doesn't...

So is there any chances to find a solution for my task?

**Comment by Biswa96** [comment]
It is not possible to execute Linux binaries without wsl.exe launcher. You could check if the command is being run in WSL or in actual bare metal Linux installation. Then append wsl.exe string in the command.

**Comment by kerim371** [comment]
@Biswa96 thank you for information. Sad but true
