### ISSUE TITLE
Wsl/0x80070020

### ISSUE THREAD

**Issue by NickLiu635** [microsoft/WSL#9802]
### Windows Version

Microsoft Windows [版本 10.0.22621.1413]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu

### Repro Steps

![image](https://user-images.githubusercontent.com/36353209/225791735-42613347-b4f1-4dd0-8dac-bae4162d2981.png)

### Expected Behavior

---

### Actual Behavior

---

**Comment by NickLiu635** [comment]
I see that there is a WSL window that is still functioning normally. Here are some details.
```
1:/$ cat /proc/version
Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1105-Microsoft Fri Jan 01 08:00:00 PST 2016
1:/$ lsb_release -r
Release:        22.04
```

**Comment by NickLiu635** [comment]
Same issue when installing a distro.
![image](https://user-images.githubusercontent.com/36353209/225793923-adcddde9-2435-44b7-aa21-ac2a37a6cf4f.png)

**Comment by OneBlue** [comment]
Thanks @NickLiu635. 

If there is no crash dump we'll need to follow what's happening with a debugger. Can you please follow the ['12) Collect wslservice time travel debugging traces'  section](https://github.com/microsoft/WSL/blob/f9bc074b180b07c7825f36619a5930b49a3bde2b/CONTRIBUTING.md#12-collect-wslservice-time-travel-debugging-traces) and share the traces so I can have a deeper look ?

**Comment by NickLiu635** [comment]
> Thanks @NickLiu635.
> 
> If there is no crash dump we'll need to follow what's happening with a debugger. Can you please follow the ['12) Collect wslservice time travel debugging traces' section](https://github.com/microsoft/WSL/blob/f9bc074b180b07c7825f36619a5930b49a3bde2b/CONTRIBUTING.md#12-collect-wslservice-time-travel-debugging-traces) and share the traces so I can have a deeper look ?

there is no `wslservice.exe` ; `Error code: Wsl/0x80070020` while `wsl -l`

**Comment by OneBlue** [comment]
Thank you @NickLiu635.

Unfortunately, the trace captured C:\windows\system32\wsl.exe, which only calls inside the store application.

Can you share another trace, but this time, with `C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\wsl.exe`  instead ?

**Comment by NickLiu635** [comment]
I found whenever I tryed `wsl -l`, an err event loggged as 
```'text
HNS 无法断开 vmswitch 端口的连接，错误为“0x80070490”，交换机 ID =“C08CB7B8-9B3C-408E-8E30-5E16A3AEB444”，端口 ID =“6FC0FE9A-0CC1-4B51-9730-8E9C458A2694”，NIC 名称 =“6FC0FE9A-0CC1-4B51-9730-8E9C458A2694”。
```

for detail
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Microsoft-Windows-Host-Network-Service" Guid="{0c885e0d-6eb6-476c-a048-2457eed3a5c1}" /> 
  <EventID>1007</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-05-09T03:25:21.4755784Z" /> 
  <EventRecordID>67213</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="3660" ThreadID="4020" /> 
  <Channel>Microsoft-Windows-Host-Network-Service-Admin</Channel> 
  <Computer>{hidden}</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
<EventData>
  <Data Name="Parameter0">0x80070490</Data> 
  <Data Name="Parameter1">C08CB7B8-9B3C-408E-8E30-5E16A3AEB444</Data> 
  <Data Name="Paramete3">6FC0FE9A-0CC1-4B51-9730-8E9C458A2694</Data> 
  <Data Name="Parameter4">6FC0FE9A-0CC1-4B51-9730-8E9C458A2694</Data> 
  </EventData>
  </Event>
```

**Comment by NickLiu635** [comment]
new .run log here https://1drv.ms/u/s!AuFyXmxD9pH_hKQovk_LEWg6qky-DA?e=pwIo0Phttps://1drv.ms/u/s!AuFyXmxD9pH_hKQovk_LEWg6qky-DA?e=pwIo0P

**Comment by NickLiu635** [comment]
This issue is no longer repeated in the new version.
