### ISSUE TITLE
WSL2 ping issue when NIC has mutiple IP addresses

### ISSUE THREAD

**Issue by escherstair** [microsoft/WSL#9803]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Assign two IP addresses (on different subnets) to a Network Interface Card (NIC)
2. Using that NIC, connect an ethernet cable to a device which has an IP address on the network of the second IP address of the NIC (not the first one)
3. ping the device from Windows, and check that it answers
4. ping the device from WSL2

### Expected Behavior

The device should answer to the ping.

### Actual Behavior

No answer from the ping.
If the device has an IP address on the network of the first IP of the NIC, the ping is successful.

**Comment by STaRDoGG** [comment]
Just curious, when you do a `ifconfig eth0 | grep 'inet '` from WSL2, does the IP change?

**Comment by escherstair** [comment]
Hi @STaRDoGG 
here is the return from `ifconfig eth0 | grep 'inet '`

`inet 172.22.214.169  netmask 255.255.240.0  broadcast 172.22.223.255`

Does this help?
