### ISSUE TITLE
execvpe /bin/bash failed 117

### ISSUE THREAD

**Issue by rangehow** [microsoft/WSL#9804]
### Windows Version

Microsoft Windows [Version 10.0.25314.1010]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04

### Repro Steps

run comman ‘wsl' in cmd or simply open Ubuntu-22.04 LTS will show the following error.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/88258534/225918843-37b895c6-b6a9-4646-b411-f281c5bf06dc.png">

I have used 'wsl -l' to check if  the most common reason that default startup docker. But only find 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/88258534/225919328-fa8f8cb0-d545-4a7e-9b77-c6a15c72cb14.png">
Still 'wsl --set-default ' is no use to me.

### Expected Behavior

Startup normally

### Actual Behavior

Can't startup wsl.

**Comment by abellorenteramirez** [comment]
Hi! @rangehow, what do you do to solve the issue?, i'm in the same situation. Thanks!

**Comment by rangehow** [comment]
> Hi! @rangehow, what do you do to solve the issue? I'm in the same situation. Thanks!

As this issue was mentioned long ago, I have forgotten how it was resolved. Consider opening a new issue and providing the steps to reproduce the problem along with the logs to get help.
