### ISSUE TITLE
Unable to terminate WSL instances

### ISSUE THREAD

**Issue by zhavir** [microsoft/WSL#9806]
### Windows Version

Microsoft Windows [Version 10.0.19042.2604]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

N/D

### Repro Steps

Execute 
`wsl --list --all --verbose`
![image](https://user-images.githubusercontent.com/8330235/225974498-9c6a1b05-a694-4199-9d5f-d6e202107094.png)

then tried to remove stopped wsl instances with 
```
wsl --unregister Debian2 
wsl --unregister Debian
```

### Expected Behavior

wsl instances will be removed

### Actual Behavior

An exception is raised saying that:
```
Unregistering.
There is no distribution with the supplied name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND
```

**Comment by Biswa96** [comment]
Your distributions name are `Debain` and not `Debian`. typo.

**Comment by zhavir** [comment]
you're absolutely right! thanks!
