### ISSUE TITLE
CreateProcessParseCommon:786: Failed to translate

### ISSUE THREAD

**Issue by AkinoKaede** [microsoft/WSL#9808]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

openSUSE Tumbleweed

### Other Software

Windows 11 on ARM: 10.0.22621.1413
CPU: Qualcomm Snapdragon 8cx Gen 3

### Repro Steps

Run `wsl` after install the distro

### Expected Behavior

Can mount the path

### Actual Behavior

The WSL cannot mount the path to Linux distro.

### Diagnostic Logs

```
<3>WSL (10) ERROR: CreateProcessParseCommon:786: Failed to translate C:\Users\<username>
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (Arm)\BellSoft\LibericaJDK-17-Full\bin\
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\system32
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32\Wbem
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files\Git\cmd
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (x86)\gnupg\bin
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Users\<username>\scoop\shims
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Users\<username>\AppData\Local\Microsoft\WindowsApps
<3>WSL (10) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin
```

**Comment by AkinoKaede** [comment]
Debian is works with WSL.

**Comment by elsaco** [comment]
@AkinoKaede are you using the ARM version of Tumbleweed? It works with downloads from https://download.opensuse.org/ports/aarch64/tumbleweed/appliances. Search for WSL. You'll need to install the certificate first otherwise the appx package won't install.

**Comment by AkinoKaede** [comment]
> 

Thanks.

**Comment by AkinoKaede** [comment]
> @AkinoKaede are you using the ARM version of Tumbleweed? It works with downloads from https://download.opensuse.org/ports/aarch64/tumbleweed/appliances. Search for WSL. You'll need to install the certificate first otherwise the appx package won't install.

Thanks

**Comment by Biswa96** [comment]
Just wondering. Did you find the reason behind that "Failed to translate" issue?

**Comment by AkinoKaede** [comment]
> Just wondering. Did you find the reason behind that "Failed to translate" issue?

No, I don't really understand how WSL works.

**Comment by elsaco** [comment]
The list of WSL distros doesn't include SUSE aarch64 versions. See details as:

https://github.com/microsoft/WSL/blob/5db50890d53406b9910026b4b7a4c8cfcd29d3e1/distributions/DistributionInfo.json#L103-L112

So an ARM kernel won't run x86 binaries thus "Failed to translate" issues. There are sites to download ARM WSL containers. SUSE has the above mentioned link and the latest release works fine on a WinDev 2023 kit.
