### ISSUE TITLE
WSL2 - Freeze each creation/update for a file/folder

### ISSUE THREAD

**Issue by AurelienPillevesse** [microsoft/WSL#9813]
### Windows Version

Microsoft Windows [version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Other Software

I have BitLocker

### Repro Steps

Install WSL with `wsl --install`
Install Ubuntu 22.04
Go on `\\wsl.localhost\Ubuntu-22.04\home\ubuntu` and create a file/folder and press enter to save it

### Expected Behavior

On my previous Windows 10 computer, it was possible to create folder/file and update a folder/file without any freeze.

On this computer, I installed it with this process : https://learn.microsoft.com/fr-fr/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
And no BitLocker on this previous computer

### Actual Behavior

Create a folder/file in the Ubuntu Subsystem from Windows File Explorer.

Windows File Explorer crash during between 20 seconds and 1 minute each time I create a file/folder or save a file.
Same with a file and everytime I save it with PhpStorm/Visual Studio Code with no WSL extension.

### Diagnostic Logs

If you want any log, tell me which command you want me to use.

**Comment by AurelienPillevesse** [comment]
And here is my execution policies : 
![image](https://user-images.githubusercontent.com/16165438/226550128-31ea5b92-db9e-4c36-bc73-08c6a115500c.png)

**Comment by OneBlue** [comment]
Thanks @AurelienPillevesse. Can you share the path of the folder you tried to create that caused the explorer to freeze ? 

Also, do you see the same behavior with let's say powershell ? Can you share the output this command in powershell:

```
Measure-Command{  mkdir \\wsl.localhost\<distro-name>\test-folder }
```

**Comment by AurelienPillevesse** [comment]
Hi, thanks for your answers.
Issue have disappear when I uninstalled HP Wolf Security.

Sorry and thanks again for your time.
