### ISSUE TITLE
lspci | grep -i nvidia retruns no results

### ISSUE THREAD

**Issue by EdSeymore** [microsoft/WSL#9821]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 

### Distro Version

Ubuntu 22.04 

### Other Software

HP 2022 OMEN 30L Gaming Desktop 
NVIDIA GeForce RTX 3080 Ti (12GB GDDR6X) 

Windows 11, WSL2, Ubuntu 22.04, CUDA 12.1, cuDNN 8.8 
NVIDIA-SMI 528.49 Driver Version: 528.49 

### Repro Steps

Reference ......: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html 
Step 2.1 lspci | grep -i nvidia retruns no results 
Problem ........: lspci | grep -i nvidia   : blank 

### Expected Behavior

lspci | grep -i nvidia to shows a results 

### Actual Behavior

lspci | grep -i nvidia still blank 

### Diagnostic Logs

./deviceQuery : no CUDA-capable device is detected 
python3, import torch, print(torch.cuda.is_available()) is False

**Comment by OneBlue** [comment]
Thanks for reporting this @EdSeymore.

In WSL the graphic adapter actually shows up as `Microsoft Corporation Device`.

For instance: 

```
lspci | grep -i Microsoft
8756:00:00.0 3D controller: Microsoft Corporation Device 008e
```

**Comment by EdSeymore** [comment]
Thanks for rapid reply. I got the following response: 
fe50:00:00.0 3D controller: Microsoft Corporation Basic Render Driver.

**Comment by EdSeymore** [comment]
On Ubuntu 22.04 terminal with WSL2: 
nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
