### ISSUE TITLE
Have the Windows home dir as an environment variable

### ISSUE THREAD

**Issue by EduardGomezEscandell** [microsoft/WSL#9828]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to access `C:\Users\JohnDoe` from WSL without having to do start a subprocess with `wslpath -ua $(powershell.exe 'echo ${HOME}' |  tr -d '\r')`.

**Describe the solution you'd like**
Have an environment variable such as `WSL_WINDOWS_HOME` with the path `/mnt/c/Users/JohnDoe`.

**Describe alternatives you've considered**
```bash
wslpath -ua $(powershell.exe 'echo ${HOME}' |  tr -d '\r')
```

**Additional context**
An example application is sharing configuration or other sort of files accross multiple distros by storing them at some location in the Windows filesystem.

It would also be helpful if systemd had access to this variable so services could access the same functionality (In this regard related to #9719).

**Comment by Biswa96** [comment]
It is possible with `WSLENV` environment variable. More info here https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/

Example:

* From Windows side:
```
> set WSLENV=USERPROFILE/u
> wsl.exe
```

* From WSL side:
```
$ echo $USERPROFILE
C:\Users\x
```

**Comment by OneBlue** [comment]
Agreed with @Biswa96 here: `WSLENV` is the best way to access the Windows user profile path.
