### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102

### ISSUE THREAD

**Issue by Tokimekis** [microsoft/WSL#9831]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
Press any key to continue...

![image](https://user-images.githubusercontent.com/5900287/227010196-9f717b72-3ec1-473b-b9e6-e7b664c5867b.png)

![image](https://user-images.githubusercontent.com/5900287/227010301-6cf86169-db26-4fc6-9b3b-2ab8d5bdc3c6.png)

![image](https://user-images.githubusercontent.com/5900287/227010438-cace6ad5-baed-4832-8152-c795638ecbb1.png)

![image](https://user-images.githubusercontent.com/5900287/227010629-ff25c5f2-7386-49ff-9f38-b6ea69f81704.png)

**Comment by Tokimekis** [comment]
logs
[WslLogs-2023-03-23_03-08-27.zip](https://github.com/microsoft/WSL/files/11043852/WslLogs-2023-03-23_03-08-27.zip)

**Comment by Tokimekis** [comment]
disable tpm, enable nx mode, the problem is solved

**Comment by timsknaht** [comment]
> 

may i ask how to enable nx mode? i can't find it in my BIOS

**Comment by Tokimekis** [comment]
> 



> > 
> 
> may i ask how to enable nx mode? i can't find it in my BIOS


Only the amd platform has this option. You can try to turn off secure boot

**Comment by timsknaht** [comment]
Thanks a lot!&nbsp; &nbsp;I’ve fixed the issue.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/WSL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/WSL] WslRegisterDistribution failed with error: 0x80370102 (Issue #9831)





      
may i ask how to enable nx mode? i can't find it in my BIOS
  
Only the amd platform has this option. You can try to turn off secure boot
