### ISSUE TITLE
After installing latest WSL, get Wsl/E_ACCESSDENIED when trying to start/use WSL

### ISSUE THREAD

**Issue by AnthonyHayes72** [microsoft/WSL#9834]
### Windows Version

Microsoft Windows 10 Enterprise 19044.2728

### WSL Version

Store version - tying to run wsl.exe gives error

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

same error using wsl.exe

### Distro Version

Ubuntu 20.04.5 LTS

### Other Software

N/A

### Repro Steps

Enable Windows Subsystem for Linux feature and restart
Use admin command prompt...
wsl --set-default-version 2 
wsl --install -d Ubuntu

All good so far

wsl --update (or install latest from microsoft store)

After install completes, any further interactions give error...

Error code: Wsl/E_ACCESSDENIED

or 

Invalid value for registry
Error code: Wsl/0x80040153

If command actioned from admin console.

Similarly selecting WSL from start menu gives ACCESSDENIED error

### Expected Behavior

WSL commands to be executed correctly

### Actual Behavior

![image](https://user-images.githubusercontent.com/128694731/227175104-9ac26e71-01f2-48e3-abb8-81c1533beb65.png)

![image](https://user-images.githubusercontent.com/128694731/227175368-c73dd4c8-42d4-4493-9cbc-71c825dd4b78.png)

### Diagnostic Logs

[WslLogs-2023-03-23_10-04-05.zip](https://github.com/microsoft/WSL/files/11049660/WslLogs-2023-03-23_10-04-05.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @AnthonyHayes72. Can you share the output of `wsl.exe --version` ?

**Comment by AnthonyHayes72** [comment]
> Thank you for reporting this @AnthonyHayes72. Can you share the output of `wsl.exe --version` ?

I cannot run wsl --exe when in this state, I get the same errors in the report for any wsl command.

**Comment by AnthonyHayes72** [comment]
> Can you also share a screen shot of `HKEY_LOCAL_MACHINE\Software\Classes\Interface\\46f3c96d-ffa3-42f0-b052-52f5e7ecbb08}` ? I wonder if that key is in a bad state

![image](https://user-images.githubusercontent.com/128694731/227465555-3cf20251-0384-47ee-8527-4bad508172ed.png)

**Comment by OneBlue** [comment]
> > Can you also share a screen shot of `HKEY_LOCAL_MACHINE\Software\Classes\Interface\\46f3c96d-ffa3-42f0-b052-52f5e7ecbb08}` ? I wonder if that key is in a bad state
> 
> Thanks for looking into this - here's the reg key...
> 
> ![image](https://user-images.githubusercontent.com/128694731/227465555-3cf20251-0384-47ee-8527-4bad508172ed.png)

Interesting. Can you capture logs for wsl.exe --version ? I wonder if it would be easier to root cause the error from there

**Comment by AnthonyHayes72** [comment]
> > > Can you also share a screen shot of `HKEY_LOCAL_MACHINE\Software\Classes\Interface\\46f3c96d-ffa3-42f0-b052-52f5e7ecbb08}` ? I wonder if that key is in a bad state
> > 
> > 
> > Thanks for looking into this - here's the reg key...
> > ![image](https://user-images.githubusercontent.com/128694731/227465555-3cf20251-0384-47ee-8527-4bad508172ed.png)
> 
> Interesting. Can you capture logs for wsl.exe --version ? I wonder if it would be easier to root cause the error from there

Image shows workflow - wsl working until I do wsl --update

After update wsl --version produces error.

Log files attached for wsl -- version execution

Thank you,

![image](https://user-images.githubusercontent.com/128694731/227589772-75de4e6b-0d0d-4d62-a716-ffb826ffef16.png)

[WslLogs-2023-03-24_16-49-26.zip](https://github.com/microsoft/WSL/files/11064586/WslLogs-2023-03-24_16-49-26.zip)

**Comment by AnthonyHayes72** [comment]
> Thank @AnthonyHayes72. Looking at the logs it's pretty clear that there's one registry key with an unexpected value that's confusing WSL.
> 
> Given that wsl --version is failing as well, I think it's probably `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion`
> 
> Can you share a screenshot of that key ?

Here's the reg key - again thanks for your help...

![image](https://user-images.githubusercontent.com/128694731/227712094-c9e867e0-8e16-4a2b-b363-253504f243e9.png)

**Comment by d0zer11st** [comment]
I had the same issue. This is what helped me:
1. Remove WSL from windows store.
2. Install [WSL2 Linux kernel update package for x64 machines](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) from Step 4 in https://learn.microsoft.com/en-us/windows/wsl/install-manual

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/1.1.7.

**Comment by d0zer11st** [comment]
seems like nothing has changed
```
PS C:\tools> wsl --version
WSL version: 1.1.7.0
Kernel version: 6.1.21.1-1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1696

PS C:\tools> wsl --list
Invalid value for registry
Error code: Wsl/0x80040153
```

**Comment by OneBlue** [comment]
@d0zer11st: Can you share /logs ?

**Comment by d0zer11st** [comment]
> @d0zer11st: Can you share /logs ?

Sure.

[WslLogs-2023-04-05_20-40-30.zip](https://github.com/microsoft/WSL/files/11161039/WslLogs-2023-04-05_20-40-30.zip)

**Comment by farzadkb** [comment]
I have same issue
![image](https://user-images.githubusercontent.com/11814299/232324765-1a665763-395c-425e-8127-01aa9967b66c.png)
![image](https://user-images.githubusercontent.com/11814299/232324793-043f94a0-cae8-47f8-a69c-0b079bccff07.png)

**Comment by luquilo** [comment]
i have the same issue, can you help me @OneBlue ? i dont really understand with these log (0x80040153)

**Comment by OneBlue** [comment]
Thank you for reporting this @nikolaikopernik. Can you share [logs](aka.ms/wsllogs) when you see this error ?

**Comment by nikolaikopernik** [comment]
Sure 
[WslLogs-2023-10-05_09-14-14.zip](https://github.com/microsoft/WSL/files/12813512/WslLogs-2023-10-05_09-14-14.zip)

**Comment by OneBlue** [comment]
> Sure [WslLogs-2023-10-05_09-14-14.zip](https://github.com/microsoft/WSL/files/12813512/WslLogs-2023-10-05_09-14-14.zip)

Thank you @nikolaikopernik. Do you get the same result if you run the command in an elevated prompt ?

**Comment by nikolaikopernik** [comment]
Yes, run it as an admin - same result

**Comment by OneBlue** [comment]
> Yes, ran it as an admin - same result

Interesting. Do you see the same issue if you manually download and install the [latest build of WSL](https://github.com/microsoft/WSL/releases/download/2.0.4/wsl.2.0.4.0.x64.msi) ?

**Comment by chetratep** [comment]
I am having the same issue. Tried with Administrator and also tried the latest build of WSL
2.0.4

```
PS C:\Users\user> wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.4.
PS C:\Users\user>
PS C:\Users\user> wsl --install  -d Debian
Installing: Debian GNU/Linux
Access is denied.           0.0%                           ]
Error code: Wsl/InstallDistro/E_ACCESSDENIED
```

**Comment by nikolaikopernik** [comment]
Hey @OneBlue 
I have error trying to install your build 
![Screenshot 2023-10-11 134238](https://github.com/microsoft/WSL/assets/1888789/9d043a8c-250d-4ff8-9348-2e6623aeda0e)

**Comment by nikolaikopernik** [comment]
@OneBlue 
After installing the latest version from MSI, I don't have the issue of updating WSL (but honestly I cannot update it as it's the latest version atm). I will wait for another version to be released and will check it then.

**Comment by LuanCristopher** [comment]
Hello! Can you guys help-me? 

![Captura de tela 2024-09-11 132517](https://github.com/user-attachments/assets/513df3af-343d-49bf-863d-c11485461dda)
