### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by Qtop23** [microsoft/WSL#9836]
### Windows Version

10.0.19045.2728

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

UBUNTU 2204.1.8.0

### Other Software

NA

### Repro Steps

NA

### Expected Behavior

UBUNTU LOAD

### Actual Behavior

ERROR

### Diagnostic Logs

NA

**Comment by OneBlue** [comment]
Closing since this issue doesn't have any diagnostic information.
