### ISSUE TITLE
iptables-nft "Chain 'MASQUERADE' does not exist"

### ISSUE THREAD

**Issue by eg-fxia** [microsoft/WSL#9844]
### Windows Version

Microsoft Windows [Version 10.0.19045.2251]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Distro Version

Ubuntu-22.04

### Repro Steps

as root run `iptables-nft -A POSTROUTING -o eth0 -j MASQUERADE`

The output shows
`iptables v1.8.7 (nf_tables): Chain 'MASQUERADE' does not exist`

Any other interface, or the `nat` table, shows the same error.

Same for Ubuntu 20.04

### Expected Behavior

Should be able to set up the rule.

### Actual Behavior

The rule is not created.

**Comment by gespau** [comment]
same for me
