### ISSUE TITLE
Quoted distribution name leads to Wsl/Service/E_INVALIDARG

### ISSUE THREAD

**Issue by vault-thirteen** [microsoft/WSL#9859]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Debian GNU/Linux 11 (bullseye)

### Repro Steps

1. Export the VM to a tar file.

> wsl --export Debian "J:\WSL\ISO\Debian\wsl-debian-11.tar"

2. Unregister the distribution.

> wsl --unregister Debian

3. Import the distribution, specifying its name with double quotes:

> wsl --import "Debian 11" "J:\WSL\VM\Debian\wsl-debian" "J:\WSL\ISO\Debian\wsl-debian-11.tar"

An error occurs:

> J:\WSL>wsl --import "Debian 11" "J:\WSL\VM\Debian\wsl-debian" "J:\WSL\ISO\Debian\wsl-debian-11.tar"
> Import in progress, this may take a few minutes.
> The parameter is incorrect.
> Error code: Wsl/Service/E_INVALIDARG

When importing and specifying distro name without double quotes, it works fine.

> J:\WSL>wsl --import Debian "J:\WSL\VM\Debian\wsl-debian" "J:\WSL\ISO\Debian\wsl-debian-11.tar"
> Import in progress, this may take a few minutes.
> The operation completed successfully.

### Expected Behavior

I expect to be able to use distribution names having a space in them and specifying disto name inside double quotes.
For example, I expect to be able to specify a distro name as: 

> "Debian" 

or 

> "Debian 11"

### Actual Behavior

> J:\WSL>wsl --import "Debian 11" "J:\WSL\VM\Debian\wsl-debian" "J:\WSL\ISO\Debian\wsl-debian-11.tar"
> Import in progress, this may take a few minutes.
> The parameter is incorrect.
> Error code: Wsl/Service/E_INVALIDARG

**Comment by elsaco** [comment]
@vault-thirteen see this https://github.com/microsoft/WSL/issues/9792#issuecomment-1470940048

**Comment by vault-thirteen** [comment]
@elsaco , thank you for the link.

I think, that if the distribution name may not have spaces, then this moment should be noted in the documentation.
https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro

> 2. Use the command wsl --import \<DistroName\> <InstallLocation> <InstallTarFile> to import the tar file.

Nothing is said there about the value of the \<DistroName\> argument.

**Comment by benhillis** [comment]
Distro names cannot have spaces in them, this is by design.

**Comment by vault-thirteen** [comment]
> Distro names cannot have spaces in them, this is by design.

Then I have two questions. 

1. Where is it stated in the documentation ?
2. What symbols are allowed to be in the distribution names in WSL ?
