### ISSUE TITLE
Instructions on first run (setting username & passwoed) appear in system locale language

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#986]
I live in Israel, therfore my system locale is Hebrew, while trying to run bash for the first time, I was asked to set a username, then I entered a username (in english, all lower case letters withouth any other character). After that, gibberish appeared, I copied it and pasted it in notepdatd (could have done it in any other unicode text box I think), and it is hebrew ("הכנס ססמת יוניקס חדשה:" which means Enter a new Unix password:). 
This shouldn't be like this I think, as the console doesn't support Hebrew characters (I think non-unicode generally but I'm not sure about that). 
It all should be in English I think. Either way, right now it's just not readable and useless.  

I am running Microsoft Windows [Version 10.0.14393]

My Windows display language is English (though either way it should print it in English since the console doesn't support Hebrew), my region is set to Israel, 

![image](https://cloud.githubusercontent.com/assets/7399103/17975973/42f480ce-6af4-11e6-91ee-ab472ef81a08.png)

**Comment by rmobis** [comment]
This happens for Brazillian Portuguese as well. And it`s not only the instructions on first run, but also the output from some commands, as seen on the screenshot below?

![image](https://cloud.githubusercontent.com/assets/2119933/19026797/7ad8e6ae-8900-11e6-93ec-8c689e9584bc.png)

However, as mentioned in this [SO question](http://askubuntu.com/questions/264283/switch-command-output-language-from-native-language-to-english), running the following command fixes it:

```
$ export LC_ALL=C
```

**Comment by benhillis** [comment]
lxrun is deprecated.
