### ISSUE TITLE
Wsl/Service/CreateInstance/ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Muram1602** [microsoft/WSL#9862]
### Discussed in https://github.com/microsoft/WSL/discussions/8729

<div type='discussions-op-text'>

<sup>Originally posted by **frankli-dev** August 10, 2022</sup>
### Version

Microsoft Windows [Version 10.0.22622.450]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Ubuntu

### Distro Version

Ubuntu

### Other Software

None

### Repro Steps

1. Install wsl default distro
2. Uninstall wsl
3. Reinstall wsl
4. Restart OS and open Ubuntu WSL
5. I get the following error
```
...
Wsl/Service/CreateInstance/ERROR_FILE_NOT_FOUND
```

### Expected Behavior

I want to see running Ubuntu WSL

### Actual Behavior

```
Wsl/Service/CreateInstance/ERROR_FILE_NOT_FOUND
```

### Diagnostic Logs

None</div>

**Comment by Muram1602** [comment]
Hello all,

The command wsl --unregister (version)

Will it remove all the old data ?

In my case, I reinstalled the opensusu tumbleweed software from Microsoft store and I got the same error.
Its a 3 month project data and we don't want to loose it.

We need to mount the old files safely and the opensusu software work fine.

Is there any way to take backup before following unregister command ?

Thanks,
Muthu Raman

**Comment by benhillis** [comment]
@Muram1602 - yes, you can use `--export` to back up an existing distro, `--unregister` removes it.

/logs
