### ISSUE TITLE
wsl: Unknown key 'interop.appendWindowsPath'

### ISSUE THREAD

**Issue by pravic** [microsoft/WSL#9869]
### Windows Version

Microsoft Windows [Version 10.0.19044.2728]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Distro Version

Ubuntu-20.04

### Repro Steps

`.wslconfig`:

```
[interop]
appendWindowsPath = false
```

```powershell
PS> wsl --shutdown
PS> wsl
wsl: Unknown key 'interop.appendWindowsPath' in $HOME\.wslconfig:2
```

### Expected Behavior

I'd expect the global `interop` to work via `.wslconfig`.

### Actual Behavior

It [looks like](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig) that the `interop` configuration was removed from the global `.wslconfig` and only [per-distribution](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) `wsl.conf` supports it.

Which is a pity, really, because now I have to (not to forget to) distribute the `interop` config to all my VMs. Why would the global `interop` hurt anyone so it had to be removed?

**Comment by benhillis** [comment]
Thanks for the issue - the appendWindowsPath setting is a per-distro setting and only for /etc/wsl.conf.

**Comment by gsusI** [comment]
@pravic  makes a good point

**Comment by privacyguy123** [comment]
There was no verdict here? I still notice these erorrs pop up in Event Viewer to this day ...
