### ISSUE TITLE
WSL - wrong printed/parsed characters on WSL Terminal

### ISSUE THREAD

**Issue by D3vil0p3r** [microsoft/WSL#9870]
### Windows Version

Microsoft Windows [Version 10.0.22621.1265]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) 1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Arch Linux latest and Ubuntu latest

### Other Software

Python 3.10.10

### Repro Steps

On WSL, the `\001` and `\002` Python characters are not parsed correctly.

Open WSL container of Ubuntu or Arch Linux. Run:

if Ubuntu:
```
python3
```

if Arch:
```
python
```
Once Python is run, type the following:
```python
MAIN = '\001\033[38;5;85m\002'
END = '\001\033[0m\002'
INFO = f'{MAIN}Info{END}'
print(f'\r[{INFO}] Core server started on')
```
The result will be:
![image](https://user-images.githubusercontent.com/83867734/228796299-c31d6307-6a2f-46bf-9de7-9a64f7f6ffdf.png)

The reason of using `\001` and `\002` when colors should be used is described in https://bugs.python.org/msg208948

This issue seems to appear only on WSL.

### Expected Behavior

The result should be:
```
[Info] Core server started on
```
Note that the real output has `Info` string colored.

### Actual Behavior

The wrong result is:
![image](https://user-images.githubusercontent.com/83867734/228796392-6fb1a02a-9e5d-4a79-962a-cc53aa717ef3.png)

It occurs because on WSL, the `\001` and `\002` Python characters are not parsed correctly.

**Comment by puellanivis** [comment]
This behavior of not displaying/printing `\001` and `\002` is a function of the `readline` library, and not a behavior of the terminal itself.

If your text is being printed _not_ as part of a readline prompt string, then there is no need for the code to care how long the printed string is in visual characters, and thus no need to wrap the color operations in `\001` and `\002`.

However, many terminals do not print control code characters like `SOH` and `STX`, though they are still being sent to the Terminal, as can be seen here:
```
> wrong-printed-characters.py | hexdump -C | head -n1
00000000  0d 5b 01 1b 5b 33 38 3b  35 3b 38 35 6d 02 49 6e  |.[..[38;5;85m.In|
```

If you want to make a case that the Terminal should not be printing these characters, that’s a matter for the Terminal https://github.com/microsoft/terminal not for WSL, as WSL, and python are acting entirely correctly here.

**Comment by D3vil0p3r** [comment]
Thank you @puellanivis I opened the issue on https://github.com/microsoft/terminal as suggested.
