### ISSUE TITLE
version update does not succeed

### ISSUE THREAD

**Issue by jqi-png** [microsoft/WSL#9882]
### Windows Version

Windows version: 10.0.19045.2728 

### WSL Version

2.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

C:\Users\jqi>where wsl 

C:\Windows\System32\wsl.exe 

C:\Users\jqi\AppData\Local\Microsoft\WindowsApps\wsl.exe 

 

C:\Users\jqi>wsl --update 

Checking for updates. 

The most recent version of Windows Subsystem for Linux is already installed. 

 

C:\Users\jqi>wsl --version 

WSL version: 1.1.6.0 

Kernel version: 5.15.90.1 

WSLg version: 1.0.50 

MSRDC version: 1.2.3770 

Direct3D version: 1.608.2-61064218 

DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp 

Windows version: 10.0.19045.2728 

 

C:\Users\jqi>wsl -l -v 

  NAME            STATE           VERSION 

* Ubuntu-18.04    Stopped         2 

  FCL             Stopped         2 

  Ubuntu          Stopped         2

### Expected Behavior

When doing wsl --update, the newest version reported is 1.1.6, but should be 2.0, according to the windows version. Uninstalling from scratch and reinstalling 2.0 reproduces the same error.

### Actual Behavior

C:\Users\jqi>where wsl 

C:\Windows\System32\wsl.exe 

C:\Users\jqi\AppData\Local\Microsoft\WindowsApps\wsl.exe 

 

C:\Users\jqi>wsl --update 

Checking for updates. 

The most recent version of Windows Subsystem for Linux is already installed. 

 

C:\Users\jqi>wsl --version 

WSL version: 1.1.6.0 

Kernel version: 5.15.90.1 

WSLg version: 1.0.50 

MSRDC version: 1.2.3770 

Direct3D version: 1.608.2-61064218 

DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp 

Windows version: 10.0.19045.2728 

 

C:\Users\jqi>wsl -l -v 

  NAME            STATE           VERSION 

* Ubuntu-18.04    Stopped         2 

  FCL             Stopped         2 

  Ubuntu          Stopped         2

**Comment by Biswa96** [comment]
> the newest version reported is 1.1.6, but should be 2.0

1.1.6 is the latest version. See this release page https://github.com/microsoft/WSL/releases

**Comment by jqi-png** [comment]
> > the newest version reported is 1.1.6, but should be 2.0
> 
> 1.1.6 is the latest version. See this release page https://github.com/microsoft/WSL/releases

That's odd, because when I want to do --set-memory, the option does not exist.
The docs say that --set-memory is an option only available in 2.0

wsl --set-memory
Invalid command line argument: --set-memory
Please use 'wsl.exe --help' to get a list of supported arguments.


I want to increase the amount of memory used for one of my wsl instances.

**Comment by Biswa96** [comment]
> The docs say that --set-memory is an option only available in 2.0

Could you provide the docs link?
