### ISSUE TITLE
wsl: Unknown key 'user.default' in C:\Users\######\.wslconfig:2

### ISSUE THREAD

**Issue by timothymowens** [microsoft/WSL#9884]
### Windows Version

10.0.19045.2788

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04.2

### Repro Steps

Add the following entry into %USERPROFILE%/.wslconfig:

```
[user]
default=#####
```

Get the following error when starting up WSL 2:

`wsl: Unknown key 'user.default' in C:\Users\#####\.wslconfig:2`

### Expected Behavior

Based on the documentation for .wslconfig (https://learn.microsoft.com/en-us/windows/wsl/wsl-config), this is a valid entry to define the default user account to use for a WSL 2 session.  This has worked just fine until reccently.

### Actual Behavior

When launching a WSL 2 session, I get the error:

`wsl: Unknown key 'user.default' in C:\Users\#####\.wslconfig:2`

**Comment by timothymowens** [comment]
As a side note, the hashes are to redact user details.

**Comment by Biswa96** [comment]
The user.default setting is a per-distro setting and can be set in /etc/wsl.conf only. See the example here https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconf-file

**Comment by timothymowens** [comment]
I'm using WSL 2, which doesn't use /etc/wsl.conf.  That file is for WSL 1.  WSL 2 uses %USERPROFILE%/.wslconfig.  See the link to the documentation in my original post for reference.

The only workaround I've found so far is uninstalling WSL v1.1.6.0 and then manually installing v1.1.3.0 to fix the issue.

**Comment by Biswa96** [comment]
AFAIK, no options have been moved from .wslconfig to wsl.conf. The user.default settings was in wsl.conf since its addition.

**Comment by timothymowens** [comment]
I'm guessing then that version 1.1.6.0 added some sort of validation checking for .wslconfig values causing me to see this message. I'll make the proper adjustments on my end
