### ISSUE TITLE
Kali Linux WSL2 cannot execute Windows binaries due to systemd

### ISSUE THREAD

**Issue by achmadafriza** [microsoft/WSL#9887]
### Windows Version

Microsoft Windows [Version 10.0.19044.2728]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Kali Linux 2023.1

### Other Software

Win-Kex

### Repro Steps

1.  Enable systemd support for WSL2 on `/etc/wsl.conf`

```
[boot]
systemd=true
```

2. Try to create a Win-Kex window following the [official documentation](https://www.kali.org/docs/wsl/win-kex/) and remounting [#6675](https://github.com/microsoft/WSL/discussions/6675#discussioncomment-5012927) `/tmp/.X11-unix`

### Expected Behavior

A vnc viewer on Windows should be opened as per https://www.kali.org/docs/wsl/win-kex/

### Actual Behavior

![image](https://user-images.githubusercontent.com/62173329/229361756-c82e9bb8-3a22-4ea5-8a8e-00d8f52df80a.png)

Win-Kex vnc server is created, but Windows vnc viewer is not executed.

### Diagnostic Logs

`kex --status` instead outputs:
```
┌──(jralphw㉿jralphw)-[~]
└─$ kex --esm -s
/usr/bin/kex: line 291: cmdkey.exe: command not found
Please enter ESM password for user jralphw:
/usr/bin/kex: line 371: mstsc.exe: command not found

```

which indicates that .exe is either: cannot be executed, or not found on PATH.

**Comment by achmadafriza** [comment]
There's a fix (https://jmtella.com/foro/forum/ejercicios-y-ejemplos/49620-tip-kali-kex-soluci%C3%B3n-a-los-fallos-con-las-ultimas-versiones-de-wsl) (in spanish) that can fix executing .exe on Kali Linux.

You need to create `/usr/lib/binfmt.d/WSLInterop.conf`:
```
:WSLInterop:M::MZ::/init:PF
```

This should be added by default.

**Comment by elsaco** [comment]
@achmadafriza looks like `interop` is broken on `x64` version. Even by adding `/usr/lib/binfmt.d/WSLInterop.conf` is not working:

 ```
elsaco@eleven:~$ cat /usr/lib/binfmt.d/WSLInterop.conf
:WSLInterop:M:MZ::/init:PF

elsaco@eleven:~$ ls /usr/lib/binfmt.d/
WSLInterop.conf  python3.10.conf  python3.11.conf

elsaco@eleven:~$ tasklist.exe
-bash: /mnt/c/Windows/system32/tasklist.exe: cannot execute binary file: Exec format error
```

It does work on `aarch64` with the same wsl 1.1.6.0 version, no file added:

```
elsaco@dragon:~$ ls /proc/sys/fs/binfmt_misc/
WSLInterop  register  status

elsaco@dragon:~$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a

elsaco@dragon:~$ tasklist.exe

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0          8 K
System                           4 Services                   0      3,276 K
---cut---
```

**Comment by gwd666** [comment]
looks like this also breaks kali kex in WSL2

**Comment by RavMonK** [comment]
There is a known issue with Kali Linux WSL2 where kex --win does not work when systemd=true is enabled in wsl.conf. This is due to a bug in the WSL interop code that prevents Windows binaries from being executed.

To fix this issue, you can add the following line to /usr/lib/binfmt.d/WSLInterop.conf:
`:WSLInterop:M::MZ::/init:PF`
This will register the WSL interop binary format, which will allow Windows binaries to be executed.
Once you have added this line, you can restart your WSL distro and kex --win should work as expected.

**Here are the steps in detail:**
1. Open a terminal window in your WSL distro.
2. Create the /usr/lib/binfmt.d/WSLInterop.conf file with the following content:
 `:WSLInterop:M::MZ::/init:PF`
3. Save the file and exit the editor.
4. Restart your WSL distro.
5. Try running kex --win again. It should now work as expected.

[https://prnt.sc/kVMBYnbnLgF-](https://prnt.sc/kVMBYnbnLgF-)
[https://prnt.sc/70oOC2OCrrk8](https://prnt.sc/70oOC2OCrrk8)

**Comment by l-33ter** [comment]
> There is a known issue with Kali Linux WSL2 where kex --win does not work when systemd=true is enabled in wsl.conf. This is due to a bug in the WSL interop code that prevents Windows binaries from being executed.
> 
> To fix this issue, you can add the following line to /usr/lib/binfmt.d/WSLInterop.conf: `:WSLInterop:M::MZ::/init:PF` This will register the WSL interop binary format, which will allow Windows binaries to be executed. Once you have added this line, you can restart your WSL distro and kex --win should work as expected.
> 
> **Here are the steps in detail:**
> 
> 1. Open a terminal window in your WSL distro.
> 2. Create the /usr/lib/binfmt.d/WSLInterop.conf file with the following content:
>    `:WSLInterop:M::MZ::/init:PF`
> 3. Save the file and exit the editor.
> 4. Restart your WSL distro.
> 5. Try running kex --win again. It should now work as expected.
> 
> https://prnt.sc/kVMBYnbnLgF- https://prnt.sc/70oOC2OCrrk8

Awesome! - Worked perfectly for me!
