### ISSUE TITLE
{Application Error} The exception %s (0x Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x8007023e

### ISSUE THREAD

**Issue by surcross** [microsoft/WSL#9888]
### Windows Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

 1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

ubuntu 22.04 20.04 ,kali,every distro exept powershell

### Other Software

just like #9016

### Repro Steps

Trying to start the WSL application or any distros 

### Expected Behavior

Should be able to start normally

### Actual Behavior

![image](https://user-images.githubusercontent.com/92565970/229362172-47ed8569-c175-4ea4-bcbe-2478d89ee304.png)
![e2af57277478eced9e9f965f5c0a9411](https://user-images.githubusercontent.com/92565970/229362187-41d72e62-6f78-456c-b36d-c988d55640f4.png)
![image](https://user-images.githubusercontent.com/92565970/229362196-48b24c7b-a636-4abb-b557-928b89eb025e.png)
![cf462c2a000e97d5d252ea33f2cb5dca](https://user-images.githubusercontent.com/92565970/229362222-f2db810c-0302-4071-98e6-dfde725e4bee.png)

### Diagnostic Logs

[WslLogs-2023-04-02_23-25-15.zip](https://github.com/microsoft/WSL/files/11132615/WslLogs-2023-04-02_23-25-15.zip)

**Comment by surcross** [comment]
![6595368bb4a65a8b288448be721398be](https://user-images.githubusercontent.com/92565970/229362995-73d7bbe4-fef4-43c8-9f59-7806b6975489.png)
I doubt this maybe the problem

**Comment by nvenhuizen14** [comment]
I'm getting the same thing. Did you ever figure it out?

**Comment by BroccoliSupreme** [comment]
Help!! Somebody

**Comment by coc-coder** [comment]
I have the same problem. How can I fix the network configuration?

**Comment by coc-coder** [comment]
I have the same problem. I can't fix the network configuration, and can't use wsl or hyper-v either.

**Comment by maxway2021** [comment]
same here....

**Comment by cdeadspine** [comment]
I fixed this: it is something preventing "network driver updating"

For my case : it was this exact problem, plus Windows Sandbox errored out immediately as well.

The "windows debloating" scripts I run included the following:

```
# Disable automatic installation of network devices
Function DisableNetDevicesAutoInst {
	Write-Output "Disabling automatic installation of network devices..."
	If (!(Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private")) {
		New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Force | Out-Null
	}
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Name "AutoSetup" -Type DWord -Value 0
}

# Enable automatic installation of network devices
Function EnableNetDevicesAutoInst {
	Write-Output "Enabling automatic installation of network devices..."
	Remove-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Name "AutoSetup" -ErrorAction SilentlyContinue
}
```

After enabling this again, In "add windows features" i unchecked : hyper-v , virtual machine platform, windows hypervisor platform, windows subsystem for linux. restarting, then checking them again installed everything fine.

Windows Sandbox works again, WSL works again, devices under : Network Connections  "vEthernet" x2  no longer show "disabled" and work correctly

**Comment by surcross** [comment]
> I'm getting the same thing. Did you ever figure it out?

nop, I  started using Ubuntu. everything is so good. it''s a new world for me . I only open windows for Valorant now.

**Comment by surcross** [comment]
windows wastes too much time for me, it's time to go

**Comment by wfycv** [comment]
> I fixed this: it is something preventing "network driver updating"
> 
> For my case : it was this exact problem, plus Windows Sandbox errored out immediately as well.
> 
> The "windows debloating" scripts I run included the following:
> 
> ```
> # Disable automatic installation of network devices
> Function DisableNetDevicesAutoInst {
> 	Write-Output "Disabling automatic installation of network devices..."
> 	If (!(Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private")) {
> 		New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Force | Out-Null
> 	}
> 	Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Name "AutoSetup" -Type DWord -Value 0
> }
> 
> # Enable automatic installation of network devices
> Function EnableNetDevicesAutoInst {
> 	Write-Output "Enabling automatic installation of network devices..."
> 	Remove-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\NcdAutoSetup\Private" -Name "AutoSetup" -ErrorAction SilentlyContinue
> }
> ```
> 
> After enabling this again, In "add windows features" i unchecked : hyper-v , virtual machine platform, windows hypervisor platform, windows subsystem for linux. restarting, then checking them again installed everything fine.
> 
> Windows Sandbox works again, WSL works again, devices under : Network Connections "vEthernet" x2 no longer show "disabled" and work correctly

many thanks to you!
this fix my wsl no ip issue and fix hyperv admin no virtual switch
