### ISSUE TITLE
Build a kernel with proper LOCALVERSION

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9901]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.1.21.1

### Repro Steps

Check kernel version string, `uname -r` or another tool.

### Expected Behavior

No `+` at the end of kernel version.

### Actual Behavior

`6.1.21.1-microsoft-standard-WSL2+` indicating it was build from an unclean git branch.  The `+` confuses some apps. Kernel config does have proper string: `CONFIG_LOCALVERSION="-microsoft-standard-WSL2"`

**Comment by benhillis** [comment]
@kelsey-steele - do you know why there is a `+` at the end of the kernel version string?

**Comment by kelsey-steele** [comment]
@benhillis This is linked to the new build process for the kernel. I'll check in to getting that changed.
