### ISSUE TITLE
Czech programmers keyboard has unexpected behaviour on wsl2

### ISSUE THREAD

**Issue by chroustradek** [microsoft/WSL#9902]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Use https://learn.microsoft.com/en-us/globalization/keyboards/kbdcz2.html czech programmers keyboard, that basically is EN keyboard with special czech characters with pressed AltGr.

Open cmd.exe on windows and type: "AltGr+2", you get: "š"
Open bash on wsl2 and type "AltGr+2", you get: "@"

Open cmd.exe on windows and type: "1234", you get: "1234"
Open bash on wsl2 and type "1234", you get: "+ěšč"

So in WSL2 there is some kind of czech keyboard layout, but behaviour is wrong.

When you switch your windows keyboard to US keyboard, windows and wsl have same layout > but you are not able to write special czech characters then...

### Expected Behavior

Open cmd.exe on windows and type: "AltGr+2", you get: "š"
Open bash on wsl2 and type "AltGr+2", you get: "š"

Open cmd.exe on windows and type: "1234", you get: "1234"
Open bash on wsl2 and type "1234", you get: "1234"

### Actual Behavior

Open cmd.exe on windows and type: "AltGr+2", you get: "š"
Open bash on wsl2 and type "AltGr+2", you get: "@"

Open cmd.exe on windows and type: "1234", you get: "1234"
Open bash on wsl2 and type "1234", you get: "+ěšč"

**Comment by OneBlue** [comment]
Thanks for reporting this @chroustradek. Unfortunately this isn't something that WSL can fix since the keyboard handling is done by terminal. Maybe [Windows Terminal](https://github.com/microsoft/terminal) would be the right place to report this.

Closing since this isn't a WSL issue.
