### ISSUE TITLE
Can't start Ubuntu, Just cursor blinking.

### ISSUE THREAD

**Issue by pugzit** [microsoft/WSL#9911]
[WslLogs-2023-04-04_22-49-33.zip](https://github.com/microsoft/WSL/files/11149958/WslLogs-2023-04-04_22-49-33.zip)

**Comment by benhillis** [comment]
Logs are mostly empty, could you please take a longer trace?

1. sc stop wslservice
2. start tracxe
3. repro
4. stop trace

**Comment by benhillis** [comment]
Also, more details in issue template would be helpful.

**Comment by pugzit** [comment]
It's ok now, I just uninstall and install the distro. Thanks..
