### ISSUE TITLE
after wsl --update: wsl and wslconfig /list return "%1 is not a valid Win32-Application." both give errorcode 0x800700c1 my problem

### ISSUE THREAD

**Issue by JohenanLi** [microsoft/WSL#9924]
### Windows Version

Microsoft Windows [版本 10.0.22621.1413]

### WSL Version

1.1.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu-20.04

### Repro Steps

Just like the link https://github.com/microsoft/WSL/issues/9678, i executed cmd ` wsl --update`.

### Expected Behavior

I want to use gui program on ubuntu.I follow the link https://superuser.com/questions/1681647/windows-11-wsl-not-opening-gui-in-my-ubuntu-shell,but i miss the wsl --update failed problem twice.Lastly i completely uninstall wsl and reinstall wsl in order to get it work.

### Actual Behavior

PS C:\Users\59919> wsl
%1 不是有效的 Win32 应用程序。
Error code: Wsl/Service/CreateInstance/CreateVm/0x800700c1

### Diagnostic Logs

[WslLogs-2023-04-06_00-55-39.zip](https://github.com/microsoft/WSL/files/11161300/WslLogs-2023-04-06_00-55-39.zip)

**Comment by ferruzoft** [comment]
I have the same problem when I installed wsl via **wsl --install** command on ### win 10 pro (19045)

![image](https://user-images.githubusercontent.com/5134413/230247448-8a489aee-4117-4e29-8295-4d3150dedc1a.png)

**Comment by JohenanLi** [comment]
After installing 1.2.0 wsl, it cannot work as before.
PS C:\Users\59919> wsl --version
WSL 版本： 1.2.0.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.1413

**Comment by JohenanLi** [comment]
I cannot open the path C:\Program Files\WindowsApps ,because i haven't access to this dir.So i change the owner to everyone.
![image](https://user-images.githubusercontent.com/17058872/231047611-f3fe4d2c-eae0-46f7-b70e-4c72f48b2b93.png)
This is my scrrenshot of the properties.
![image](https://user-images.githubusercontent.com/17058872/231047979-eda7f577-3d1c-4c88-9423-a9e3bff2eb87.png)

**Comment by dogukan6durukan** [comment]
I was having the same issue while I was tending to install WSL. But deleting any traces of subsystem and did `wsl --install -d ubuntu` with installing Ubuntu then updated WSL from [https://aka.ms/wsl2kernel](https://aka.ms/wsl2kernel). However, I still don't have any concrete idea of why this error is happening...

Also, there is the same issue opened in the same context you guys can follow [https://github.com/microsoft/WSL/issues/9678]( https://github.com/microsoft/WSL/issues/9678).
